### ISSUE TITLE
Latrophilin receptor binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10056]
Latrophilin receptor binding
Ontology 	Molecular Function
Definition 	
Interacting selectively and non-covalently with a latrophilin receptor.

child term of GO:0005102 receptor binding
PubMed=21724987

Reported by: andrestutz

Original Ticket: [geneontology/ontology-requests/9852](https://sourceforge.net/p/geneontology/ontology-requests/9852)

**Comment by ukemi** [comment]
[Term]
+id: GO:0061761
+name: alpha-latrotoxin receptor binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with an alpha-latrotoxin receptor." [GOC:dph, PMID:21724987]
+synonym: "lasso receptor binding" EXACT [GOC:dph, PMID:21724987]
+synonym: "latrophilin binding" EXACT [GOC:dph, PMID:21724987]
+is_a: GO:0001664 ! G-protein coupled receptor binding
+created_by: dph
+creation_date: 2016-04-13T10:46:42Z
