### ISSUE TITLE
TPV: pore complex/  nuclear pore

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10074]
nuclear pore is a child of "pore complex"

but pore complex is defined
GO:0046930
Name 	pore complex
Ontology 	Cellular Component
Definition 	Any small opening in a membrane that allows the passage of gases and/or liquids.

can this parentage be removed?

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9871](https://sourceforge.net/p/geneontology/ontology-requests/9871)

**Comment by ukemi** [comment]
Looks like this was done previously.
