### ISSUE TITLE
Fanconi anemia pathway

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10091]
Hello,

Here is a new term that I would need:
Fanconi anemia pathway (for review please see PMID:20713514)
As child of response to DNA damage stimulus GO:0006974
also related to Fanconi anaemia nuclear complex GO:0043240

We have a new release coming up and would appreciate to have this term as soon as possible. 

Thank you very much for your help,
Nevila Hyka-Nouspikel

Reported by: nnouspikel

Original Ticket: [geneontology/ontology-requests/9888](https://sourceforge.net/p/geneontology/ontology-requests/9888)

**Comment by dosumis** [comment]
Closing as we now have the complex term: Fanconi anaemia nuclear complex GO:0043240 - and the pathway term appears too controversial (see comments).
