### ISSUE TITLE
yolk sac/extraembryonic structure development

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10117]
Hi,

I'd like to have a term for "yolk sac development" and possibly also a grouping term for something like "extraembryonic structure development" to group my new term with the existing term "chorion development". Standard development defs will be fine.

I'm not quite sure what the right parent term would be; I'm sure David will be more knowledgeble, but these look like possible options:

GO:0009792 - embryo development ending in birth or egg hatching
GO:0043009 - chordate embryonic development

or, maybe a term that would be more specific to in utero development, somewhere under "in utero embryonic development ; GO:0001701".

Whatever you think works best in terms of creating a term that is clear without producing path violations, etc.

thanks,

-Karen

"GO:0009792

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/9914](https://sourceforge.net/p/geneontology/ontology-requests/9914)

**Comment by ukemi** [comment]
This ticket is old and has been made obsolete by the ability to create anatomical structure development terms by Termgenie.
