### ISSUE TITLE
dorsal and ventral spinal cord

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10161]
we discussed this at GOC:mtg_obo2owl_2013

GO:0021516 ! dorsal spinal cord development [DEF: "The process whose specific outcome is the progression of the dorsal region of the spinal cord over time, from its formation to the mature structure. The dorsal region of the mature spinal cord contains neurons that process and relay sensory input."]
GO:0021517 ! ventral spinal cord development [DEF: "The process whose specific outcome is the progression of the ventral region of the spinal cord over time, from its formation to the mature structure. The neurons of the ventral region of the mature spinal cord participate in motor output."]

We think this refers to the whole dorsal or ventral region, both grey and white matter. My understanding is the somas of the neurons are in the grey matter, but their axons are in the white. I don't know the order of events w.r.t somas and axons, but it seems safe to consider the GO development terms as encompassing grey matter and white matter development. A new AO term would seem to be in order here. the dorsal and ventral region of the spinal cord would incorporate the horns (grey matter) and the columns (funiculi)?

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/9958](https://sourceforge.net/p/geneontology/ontology-requests/9958)

**Comment by ukemi** [comment]
Closing this as it seems to be more of an anatomy issue than a GO issue.
