### ISSUE TITLE
pre-B cell and immature B-cell

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10179]
GO and CL are inverted here:

....................is_a CL:0000817 ! precursor B cell *** 
......................is_a CL:0000816 ! immature B cell *** 

..................is_a GO:0002327 ! immature B cell differentiation *** 
....................is_a GO:0002329 ! pre-B cell differentiation *** 

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/9976](https://sourceforge.net/p/geneontology/ontology-requests/9976)

**Comment by ukemi** [comment]
These are all automated to be consistent with the cell ontology. They all contain logical defs.
