### ISSUE TITLE
Flagellum should not be an obsolete term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10176]
According to AmiGO, "This term \[flagellum\] was made obsolete because it was an unnecessary grouping term. Eukaryotic flagella were deemed to be equivalent to cilia and merged, so the only remaining child to this term was 'bacterial-type flagellum ; GO:0009288'."

If you take some time to browse the literature, you find that there are several different types of flagella in eukaryotic organisms.  They are fundamentally different from one another in terms of structure and motion, not to mention location/ function.  Cilia appears to be a term applied to certain anatomic locations, such as the respiratory tract or oviduct.  Lumping cilia and flagella will decrease granularity, and the ability to properly relate structures and functions.

Furthermore, eubacteria have a different style/form of flagella, and archea have yet another form, which is probably not homologous.  And contrary to its current placement, it is NOT an "intracellular" part\!  

This term needs a thorough review and revision, not reduction.

Reported by: lowr

Original Ticket: [geneontology/ontology-requests/9973](https://sourceforge.net/p/geneontology/ontology-requests/9973)

**Comment by paolaroncaglia** [comment]
The issues discussed here have been, or are being, addressed as part of the ciliary GO project, in collaboration with ciliary experts.
Therefore, I’ll close this ticket.
