### ISSUE TITLE
regulation of mammary gland cord elongation by mammary fat p

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10178]
need a template for terms like this:

\[Term\]
id: GO:0060657
name: regulation of mammary gland cord elongation by mammary fat precursor cell-epithelial cell signaling
namespace: biological\_process
def: "Any process that modulates the rate, frequency, or extent of mammary gland cord elongation as a result of a signal being created by a mesenchymal cell that is a precursor to the mammary fat and its subsequent reception and interpretation by an mammary cord epithelial cell." \[GOC:dph, PMID:12558599\]
synonym: "regulation of mammary gland cord elongation by mammary fat precursor cell-epithelial cell signalling" EXACT \[GOC:mah\]
is\_a: GO:0007267 \! cell-cell signaling
relationship: regulates GO:0060654 \! mammary gland cord elongation
created\_by: dph
creation\_date: 2009-05-29T09:43:08Z

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/9975](https://sourceforge.net/p/geneontology/ontology-requests/9975)

**Comment by ukemi** [comment]
This request is covered by the 'regulation by' template.
