### ISSUE TITLE
acetylcholine receptor impairing toxin

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10186]
Hi,

I will need these 2 new GO terms:

envenomation resulting in positive regulation of G-protein coupled acetylcholine receptor activity in other organism; GO:new
def: A process that begins with venom being forced into an organism by the bite or sting of another organism, and ends with the resultant modulation of G-protein coupled acetylcholine receptor activity in the bitten organism.
- is the child of GO:0044513; envenomation resulting in modulation of G-protein coupled receptor activity in other organism

and

envenomation resulting in modulation of acetylcholine receptor activity in other organism
def: A process that begins with venom being forced into an organism by the bite or sting of another organism, and ends with the resultant modulation of nicotinic acetylcholine receptor activity in the bitten organism.
synonym: envenomation resulting in modulation of nicotinic acetylcholine receptor activity in other organism
- is the child of GO:0044511; envenomation resulting in modulation of receptor activity in other organism

many thanks
Florence

Reported by: fjungo

Original Ticket: [geneontology/ontology-requests/9983](https://sourceforge.net/p/geneontology/ontology-requests/9983)

**Comment by dosumis** [comment]
see also  #8665

**Comment by pgaudet** [comment]
Florence says we can close this ticket .
