### ISSUE TITLE
...positive regulation of argininosuccinate synthase act...

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10201]
Hi,

I will need this new term:

Process: envenomation resulting in positive regulation of argininosuccinate synthase activity in other organism; GO:new.
Def:
A process that begins with venom being forced into an organism by the bite or sting of another organism, 
and ends with the activation of the cytosolic argininosuccinate synthase in the bitten organism.

PubMed=19491403

Is the child of 
GO:0035738; envenomation resulting in modification of morphology or physiology of other organism

Best,
Florence

Reported by: fjungo

Original Ticket: [geneontology/ontology-requests/9998](https://sourceforge.net/p/geneontology/ontology-requests/9998)

**Comment by dosumis** [comment]
see also #8665 #10186

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21099671/65ef71a6-c067-11e6-88b8-2713e2a68ed9.png)

**Comment by dosumis** [comment]
CC @fjungo
