### ISSUE TITLE
NTRs for secretion terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10200]
Note: I can add most of these myself when we add a TG template. Existing secretions already have logical defs in the editors xp file. But the list below is a mix of chemicals, proteins are roles, so will require further work

bone matrix secretion
GAG secretion
surfactant secretion
seromucus secretion
serous secretion
milk secretion
tears secretion
sebum secretion
sweat secretion
seminal fluid secretion
lysozyme secretion
extracellular matrix secretion
alkali secretion
vaginal lubricant secretion
melanocyte stimulating hormone secretion
carbohydrate secretion
thyroid hormone secretion
biogenic amine secretion
norepinephrin secretion
digestive enzyme secretion
oxytocin stimulating hormone secretion
vasopressin stimulating hormone secretion
secretin stimulating hormone secretion
cholecystokin stimulating hormone secretion
bombesin stimulating hormone secretion
substance P secretion
enkephalin secretion
endorphin secretion
gastrin secretion
androgen binding protein secretion
gastrin stimulating hormone secretion
cuticle secretion
eggshell secretion
glycocalyx secretion
collagen secretion
vasoactive intestinal peptide secretion
motilin secretion
growth hormone releasing hormone secretion
interrenal epinephrin secretion

This is for defining the following CL terms:

CL:0000054 \! bone matrix secreting cell
CL:0000153 \! GAG secreting cell \[DEF: "A cell that secretes glycosaminoglycans."\]
CL:0000157 \! surfactant secreting cell \[DEF: "A cell that specializes in secretion of surfactant in the alveoli of the lung."\]
CL:0000159 \! seromucus secreting cell
CL:0000313 \! serous secreting cell \[DEF: "Columnar glandular cell with irregular nucleus, copious granular endoplasmic reticulum and supranuclear granules. Secretes a watery fluid containing proteins known as serous fluid."\]
CL:0000314 \! milk secreting cell
CL:0000315 \! tears secreting cell \[DEF: "A cell secreting tears, the fluid secreted by the lacrimal glands. This fluid moistens the conjunctiva and cornea."\]
CL:0000317 \! sebum secreting cell \[DEF: "A cell secreting sebun, an oily substance secreted by sebaceous glands, composed of keratin, fat, and cellular debris."\]
CL:0000318 \! sweat secreting cell \[DEF: "A cell secreting sweat, the fluid excreted by the sweat glands of mammals. It consists of water containing sodium chloride, phosphate, urea, ammonia, and other waste products."\]
CL:0000321 \! seminal fluid secreting cell
CL:0000323 \! lysozyme secreting cell
CL:0000327 \! extracellular matrix secreting cell
CL:0000435 \! alkali secreting cell
CL:0000436 \! vaginal lubricant secreting cell
CL:0000440 \! melanocyte stimulating hormone secreting cell \[DEF: "A cell of the intermediate pituitary that produces melanocyte stimulating hormone."\]
CL:0000447 \! carbohydrate secreting cell
CL:0000452 \! thyroid hormone secreting cell
CL:0000457 \! biogenic amine secreting cell
CL:0000459 \! norepinephrin secreting cell \[DEF: "A cell capable of producting norepiniphrine. Norepiniphrine is a catecholamine with multiple roles including as a hormone and a neurotransmitter. In addition, epiniphrine is synthesized from norepiniphrine by the actions of the phenylethanolamine N-methyltransferase enzyme."\]
CL:0000470 \! digestive enzyme secreting cell
CL:0000478 \! oxytocin stimulating hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes oxytocin stimulating hormone"\]
CL:0000479 \! vasopressin stimulating hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes vasopressin stimulating hormone"\]
CL:0000480 \! secretin stimulating hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes secretin stimulating hormone"\]
CL:0000481 \! cholecystokin stimulating hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes cholecystokin stimulating hormone"\]
CL:0000483 \! bombesin stimulating hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes cholecystokin stimulating hormone"\]
CL:0000505 \! substance P secreting cell \[DEF: "A peptide hormone secreting cell that secretes substance P."\]
CL:0000506 \! enkephalin secreting cell \[DEF: "An endorphine cell that secretes enkephalin."\]
CL:0000507 \! endorphin secreting cell \[DEF: "A peptide hormone secreting cell that secretes endorphin."\]
CL:0000509 \! gastrin secreting cell \[DEF: "A peptide hormone secreting cell that secretes gastrin."\]
CL:0000511 \! androgen binding protein secreting cell \[DEF: "A peptide hormone secreting cell that secretes androgen binding protein."\]
CL:0000554 \! gastrin stimulating hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes gastrin stimulating hormone."\]
CL:0000658 \! cuticle secreting cell \[DEF: "An epithelial cell that secretes cuticle."\]
CL:0000659 \! eggshell secreting cell \[DEF: "An extracellular matrix secreting cell that secretes eggshell."\]
CL:0000660 \! glycocalyx secreting cell \[DEF: "An extracellular matrix secreting cell that secretes glycocalyx."\]
CL:0000667 \! collagen secreting cell \[DEF: "An extracellular matrix secreting cell that secretes collagen."\]
CL:0002269 \! vasoactive intestinal peptide secreting cell \[DEF: "An endocrine cell that secretes vasoactive intestinal peptide."\]
CL:0002272 \! motilin secreting cell \[DEF: "A cell that secretes motilin, a gastric hormone that at low pH inhibits gastric motor activity, whereas at high pH has a stimulating effect."\]
CL:0002373 \! growth hormone releasing hormone secreting cell \[DEF: "A peptide hormone secreting cell that secretes growth hormone releasing hormone."\]
CL:0002517 \! interrenal epinephrin secreting cell \[DEF: "An interrenal chromaffin cell found in teleosts that contain small, homogeneous electron-lucent granules that are separated from the vesicular membrane by a visible halo."\]

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/9997](https://sourceforge.net/p/geneontology/ontology-requests/9997)

**Comment by cmungall** [comment]
won't fix
