### ISSUE TITLE
protein-nucleic acid complex displacement activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10205]
Based on http://www.genesdev.org/cgi/doi/10.1101/gad.1684008.

The authors show that the B subtilis DNA translocase SpoIIIE acts as a "wire stripper" to remove proteins from DNA as it transports DNA from the mother cell to the forespore. I'm thinking this might represent a class of activities, and terms could be vlable for capturing disinctions between proteins that are or are not blocked in their movement on nucleic acids by protein roadblocks. I think there are three things that can happen
- the moving protein is roadblocked
- the moving protein displaces the roadblock
- the moving protein bypasses the roadblock
I believe all three have been observed for translocases, helicases, and polymerases. 

A problem I see is that some proteins may act differently depending on the nature of the roadblock. 

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/10002](https://sourceforge.net/p/geneontology/ontology-requests/10002)

**Comment by ukemi** [comment]
Hi @thomaspd ,

I'm thinking of making the two terms,  'protein-nucleic acid complex displacement activity' and 'protein-DNA complex displacement activity' based on the paper that is cited above. However, I'm not sure what to pick as a parent in the MF ontology. I am not happy making it a direct child of MF, but the only other term that I can see that could possibly be a parent is nucleic acid/DNA binding. It seems that I can also make it negatively regulate DNA binding without any logical issues. What do you think?

-D

**Comment by ukemi** [comment]
Can be a child of DNA dependent ATPase along with other similar enzymes.
