### ISSUE TITLE
cross-linking homodimerization

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10212]
The new term requested is: cross-linking homodimerization. 
It would be a child term for "peptide cross-linking" \( GO:0018149\)
The definition could be: The formation of a covalent cross-link between two identical proteins
PUBMEDID:  11107061, 15750715, 15750715

Reported by: milagrosrodri

Original Ticket: [geneontology/ontology-requests/10009](https://sourceforge.net/p/geneontology/ontology-requests/10009)

**Comment by paolaroncaglia** [comment]
Closing this as 1) out of date and 2) above all, in disagreement with our attempt to move away from homodimerization terms (see e.g. obsoletion of GO:0033392 'actin homodimerization activity' in https://github.com/geneontology/go-ontology/issues/11269). Note that the suggested parent term is a process...
