### ISSUE TITLE
targeting vs. localization to nucleus

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10246]
We at PomBase are wondering if 'protein localization to nucleus' and 'protein targeting to nucleus' are really the same; if they're not, we'd really appreciate having the distinction clarified. Both seem to have standard defs plugged in (I did one of them years ago):

[Term]
id: GO:0034504
name: protein localization to nucleus
namespace: biological_process
def: "A process in which a protein is transported to, or maintained in, a location within the nucleus." [GOC:ecd]
synonym: "protein localisation to nucleus" EXACT [GOC:mah]
synonym: "protein localization in cell nucleus" EXACT []
synonym: "protein localization in nucleus" EXACT [GOC:mah]
is_a: GO:0033365 ! protein localization to organelle

[Term]
id: GO:0044744
name: protein targeting to nucleus
namespace: biological_process
def: "The process of directing proteins towards the nucleus, usually using signals contained within the protein." [GOC:jl]
is_a: GO:0006605 ! protein targeting
created_by: janelomax
creation_date: 2012-11-07T15:45:54Z

Right now the only connections I can easily see are that both have paths to cellular protein localization, and they're both part_of parents of 'protein import into nucleus':

[Term]
id: GO:0006606
name: protein import into nucleus
namespace: biological_process
def: "The directed movement of a protein from the cytoplasm to the nucleus." [GOC:jl]
synonym: "establishment of protein localization to nucleus" EXACT [GOC:mah]
synonym: "protein import into cell nucleus" EXACT []
synonym: "protein nucleus import" EXACT []
synonym: "protein transport from cytoplasm to nucleus" EXACT []
is_a: GO:0006886 {is_inferred="true"} ! intracellular protein transport
is_a: GO:0017038 {is_inferred="true"} ! protein import
is_a: GO:0051170 ! nuclear import
relationship: part_of GO:0034504 ! protein localization to nucleus
relationship: part_of GO:0044744 ! protein targeting to nucleus

This may mean that both protein localization and protein targeting need a more general cleanup, which is a bit scary.

Reported by: mah11

Original Ticket: [geneontology/ontology-requests/10043](https://sourceforge.net/p/geneontology/ontology-requests/10043)

**Comment by ValWood** [comment]
Also causes expected links not to be asserted in FYPO
https://github.com/pombase/fypo/issues/2648#issuecomment-219011736

**Comment by pgaudet** [comment]
Merged GO:0034504 protein localization to nucleus and GO:0044744 protein targeting to nucleus; 
Fixed definition: 
OLD def: "A process in which a protein is transported to, or maintained in, a location within the nucleus." [GOC:ecd]
NEW def: "A process in which a protein transports or maintains the localization of another protein to the nucleus." [GOC:ecd]

For the rest of the discussion, I create these issues: 
https://github.com/geneontology/go-ontology/issues/13756
https://github.com/geneontology/go-ontology/issues/13757
https://github.com/geneontology/go-ontology/issues/13758

Pascale

**Comment by pgaudet** [comment]
@ValWood can we close this ?

**Comment by ValWood** [comment]
It can be closed for me. We always used the "protein import" terms because they were more specific, and are under transport. It might be worth a heads-up to the list that this has been done, because if people really did mean transport they would lose specificity and might want to move their annotations down. Are there many "direct" annotations to "protein targeting"?

**Comment by pgaudet** [comment]
Hi Val, 

Here are EXP annotations to terms containing 'targeting' and numbers in parentheses: 

protein targeting to vacuole	(110)	+	-
positive regulation of protein targeting to mitochondrion	(87)	+	-
CVT pathway	(62)	+	-
protein targeting to membrane	(43)	+	-
protein targeting to mitochondrion	(41)	+	-
protein targeting to plasma membrane	(40)	+	-
protein targeting	(37)	+	-
positive regulation of protein targeting to membrane	(35)	+	-
SRP-dependent cotranslational protein targeting to membrane, translocation	(30)	+	-
protein targeting to peroxisome	(25)	+	-
protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway	(24)	+	-
protein targeting to lysosome	(21)	+	-
protein targeting to Golgi	(20)	+	-
posttranslational protein targeting to endoplasmic reticulum membrane	(19)	+	-
protein targeting to ER	(18)	+	-
cytoplasmic sequestering of transcription factor	(15)	+	-
posttranslational protein targeting to membrane, translocation	(15)	+	-
protein targeting to chloroplast	(15)	+	-
SRP-dependent cotranslational protein targeting to membrane	(12)	+	-
protein targeting to nuclear inner membrane	(12)	+	-
cytoplasmic sequestering of NF-kappaB	(11)	+	-
negative regulation of protein targeting to membrane	(8)	+	-
protein processing involved in protein targeting to mitochondrion	(8)	+	-
regulation of protein targeting to mitochondrion	(7)	+	-
negative regulation of protein targeting to mitochondrion	(6)	+	-
protein targeting to vacuolar membrane	(6)	+	-
protein targeting to lysosome involved in chaperone-mediated autophagy	(5)	+	-
N-glycan processing to lysosome	(4)	+	-
SRP-dependent cotranslational protein targeting to membrane, signal sequence recognition	(4)	+	-
protein targeting to vacuole involved in autophagy	(4)	+	-
release of cytoplasmic sequestered NF-kappaB	(4)	+	-
cotranslational protein targeting to membrane	(2)	+	-
regulation of CVT pathway	(2)	+	--
CVT vesicle assembly	(1)	+	-
negative regulation of protein processing involved in protein targeting to mitochondrion	(1)	+	-
positive regulation of protein targeting to plasma membrane	(1)	+	-
regulation of protein targeting	(1)	+	-
regulation of protein targeting to membrane	(1)	+	-
regulation of protein targeting to vacuolar membrane	(1)	+	-

I removed the 'import' terms which are children of 'targeting'. That arrangement seems odd to me, I think of targeting as a part of import (another reason to merge the terms) but I think @ValWood brought that up too. 

Thanks, Pascale

**Comment by pgaudet** [comment]
For completion, this is the list of all EXP annotations to terms that are children of 'protein targeting' 

protein targeting to vacuole	(110)	+	-
positive regulation of protein targeting to mitochondrion	(87)	+	-
CVT pathway	(62)	+	-
protein targeting to membrane	(43)	+	-
protein targeting to mitochondrion	(41)	+	-
protein targeting to plasma membrane	(40)	+	-
protein targeting	(37)	+	-
positive regulation of protein targeting to membrane	(35)	+	-
SRP-dependent cotranslational protein targeting to membrane, translocation	(30)	+	-
protein targeting to peroxisome	(25)	+	-
transcription factor import into nucleus	(25)	+	-
protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway	(24)	+	-
protein targeting to lysosome	(21)	+	-
protein targeting to Golgi	(20)	+	-
posttranslational protein targeting to endoplasmic reticulum membrane	(19)	+	-
protein import into chloroplast stroma	(19)	+	-
protein targeting to ER	(18)	+	-
cytoplasmic sequestering of transcription factor	(15)	+	-
posttranslational protein targeting to membrane, translocation	(15)	+	-
protein targeting to chloroplast	(15)	+	-
SRP-dependent cotranslational protein targeting to membrane	(12)	+	-
protein targeting to nuclear inner membrane	(12)	+	-
negative regulation of protein targeting to membrane	(8)	+	-
protein processing involved in protein targeting to mitochondrion	(8)	+	-
regulation of protein targeting to mitochondrion	(7)	+	-
negative regulation of protein targeting to mitochondrion	(6)	+	-
protein targeting to vacuolar membrane	(6)	+	-
protein targeting to lysosome involved in chaperone-mediated autophagy	(5)	+	-
N-glycan processing to lysosome	(4)	+	-
SRP-dependent cotranslational protein targeting to membrane, signal sequence recognition	(4)	+	-
protein targeting to vacuole involved in autophagy	(4)	+	-
negative regulation of SMAD protein import into nucleus	(3)	+	-
NFAT protein import into nucleus	(2)	+	-
cotranslational protein targeting to membrane	(2)	+	-
negative regulation of STAT protein import into nucleus	(2)	+	-
positive regulation of transcription factor import into nucleus in response to oxidative stress	(2)	+	-
protein import into nucleus, substrate release	(2)	+	-
protein import into peroxisome matrix, translocation	(2)	+	-
regulation of CVT pathway	(2)	+	-
regulation of SMAD protein import into nucleus	(2)	+	-
sterol regulatory element binding protein import into nucleus	(2)	+	-
CVT vesicle assembly	(1)	+	-
MAPK import into nucleus involved in osmosensory signaling pathway	(1)	+	-
glucocorticoid receptor import into nucleus	(1)	+	-
negative regulation of protein import into mitochondrial outer membrane	(1)	+	-
negative regulation of protein processing involved in protein targeting to mitochondrion	(1)	+	-
positive regulation of protein import into chloroplast stroma	(1)	+	-
positive regulation of protein import into mitochondrial outer membrane	(1)	+	-
positive regulation of protein targeting to plasma membrane	(1)	+	-
proteasome core complex import into nucleus	(1)	+	-
protein import into peroxisome matrix, substrate release	(1)	+	-
regulation of NFAT protein import into nucleus	(1)	+	-
regulation of protein import into chloroplast stroma	(1)	+	-
regulation of protein targeting	(1)	+	-
regulation of protein targeting to membrane	(1)	+	-
regulation of protein targeting to vacuolar membrane	(1)	+	-
snRNP protein import into nucleus	(1)

**Comment by ValWood** [comment]
Hmm it's definitely a mixture of localization, transport, and targeting.
But positioned incorrectly in the ontology as you say.
Can go through the list with you tomorrow?
kill, move, rename,  or ask the audience?

**Comment by pgaudet** [comment]
Targeting is a different issue. I am closing this.
