### ISSUE TITLE
qualification of cilium and determination of asymmetry' term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10241]
Hi David

There are 2 types of node cilium, one is motile and moves the fluid, the other responds to the movement which leads to calcium signalling.

According to Chen 2010 PMID:20054532 

There are  2 Different models for L-R pattern (which I guess does complicate the issue, but possibly both play a role)
1)   immotile mechanosensory cilia at edge of node with Pkd2 sense flow and release a leftsided intracellular Ca2+ signal
2)   morphogen (or membrane bound Nodal vesicular parcels (NVPs) containing morphogens Shh and Retinoic acid, becomes asymmetrically localized in response to flow. With Fgf signalling required for the release of NVPs. 

So the GO term GO:0060287 epithelial cilium movement involved in determination of left/right asymmetry has the definition: The movement of cilia of epithelial cells resulting in the transport of signals which determine asymmetry in an organism's body plan with respect to the left and right halves.

I have used this term to annotate genes involved in cilia motility in the node, however can I also use this to annotate Pkd2 which is associated with sensing flow in immotile cilia and is not involved in motile cilia? The definition as it stands could be used for either. Maybe there needs to be the 2 child terms, for the motile and the immotile cilia?

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/10038](https://sourceforge.net/p/geneontology/ontology-requests/10038)

**Comment by krchristie** [comment]
Hi,

David asked me to take a look at this item.

I completely agree with his comment that GO:0060287 should NOT be used to annotate the immotile cilia responding to the flow. 

I also completely agree with his suggestion that the appropriate term would be “detection of nodal flow”. If there was also evidence that showed that this occurred in a cilium, then additional
annotations could be made (and linked if in Noctua) to indicate that this process was occuring in a specific structure, e.g. a non-motile primary cilium.

my 2p,

-Karen
