### ISSUE TITLE
modulation by virus of host nucleoctyoplasmic transport 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10257]
Potential GO term name: modulation by virus of host nucleoctyoplasmic transport 
Definition: Any process by which a virus is able to alter or inhibit the frequency, rate, or extent of transport between the cytoplasm and nucleus of the host cell 
Location in the ontology: This is a viral version of GO:0006913 nucleocytoplasmic transport.  From looking at the current ontology, I think it would be a child of  "GO:0019054 modulation by virus of host cellular process".  For organizational purposes, possibly add the term "modulation by virus of host transport" as a child of "GO:0019054 modulation by virus of host cellular process", then add the suggested NT "modulation by virus of host nucleoctyoplasmic transport" as a child of that. 
It's also a child of "GO:0052038 modulation by symbiont of host intracellular transport", since virus/hosts fit in the definition of symbionic relationships.
References:  PMID:22334672
Aspect: biological process
Synonyms could include "viral modulation of host nucleocytoplasmic trafficking"

Reported by: biostudent09

Original Ticket: [geneontology/ontology-requests/10054](https://sourceforge.net/p/geneontology/ontology-requests/10054)

**Comment by pgaudet** [comment]
I am closing this ticket because it's old and looking at the paper, the conclusions are very vague: ICP27 mediates nuclear export of viral intronless mRNAs, which probably indirectly causes problems in nucleocytoplasmic transport.
