### ISSUE TITLE
flocculation term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10265]
I need a term which combines both
galactose-specific flocculation
and
GO:0043689 	cell-cell adhesion involved in flocculation 

i.e cell-cell adhesion involved in galactose-specific flocculation 

\(I'm still unsure why flocculation can't have an ahesion parantage, and there might be other items open about this, I will check\)
no hurry for this one

not to self c381c274e0743264

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10062](https://sourceforge.net/p/geneontology/ontology-requests/10062)

**Comment by ukemi** [comment]
This term is already in, GO:0098611.
