### ISSUE TITLE
missing parent?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10260]
Hello,

shouldn't 'negative regulation of protein autophosphorylation'

have the parent 'negative regulation of protein kinase activity' ?

Thanks\!
Antonia

Reported by: antonialock

Original Ticket: [geneontology/ontology-requests/10057](https://sourceforge.net/p/geneontology/ontology-requests/10057)

**Comment by ukemi** [comment]
Because autophosphorylation can be on one or more residues, I have made has_part relations between these terms.
