### ISSUE TITLE
NTR: regulatory RNA binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10261]
Under the "RNA binding" term, there are currently a number of terms for binding of (eukaryotic) RNA regulators, e.g. piRNA, miRNA and siRNA binding.  No terms currently exist for the prokaryotic small regulatory RNAs.  I propose a new parent term, regulatory RNA binding, as a child of RNA binding.  In addition, I'd like to request creation of a term for "small RNA binding" that would include the bacterial small regulatory RNAs; it could have the "regulatory RNA binding" term as its parent.

Thanks,
Ingrid

Reported by: imk07

Original Ticket: [geneontology/ontology-requests/10058](https://sourceforge.net/p/geneontology/ontology-requests/10058)

**Comment by pgaudet** [comment]
@keseler What do you suggest we do about this ticket; do you want to create 'small regulatory RNA binding'? If you do, please provide a reference and a definition. 

Thanks, Pascale

**Comment by keseler** [comment]
Oh my, that's a long time ago.  Yes, I'd still like a "small regulatory RNA binding" term.

Definition? perhaps: "Interacting selectively and non-covalently with a small regulatory RNA, a short RNA (usually 50-350 nt long) that is either independently transcribed or processed from a longer RNA by an RNAse enzyme."  
Publications; hmmm.  A subset of small regulatory RNAs interact with the Hfq protein; a good publication would be PMID 14622403.  Though I think what precipitated my request at the time was a much later publication about RapZ, PMID 23475961.

Thanks,
Ingrid

**Comment by hattrill** [comment]
Looks like piRNAs were forgotten - could you make GO:0034584 piRNA binding a child of GO:0061980 regulatory RNA binding?

Thanks
