### ISSUE TITLE
NTR: apical ectodermal ridge formation and regulation terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10276]
Hello,	
May we please have the following new terms to annotate PMID:9596583?

1\) Apical ectodermal ridge formation
The process pertaining to the initial formation of the apical ectodermal ridge from unspecified parts. This process begins with the migration of ventral ectodermal cells into the prospective apical ectodermal ridge field, and ends when the apical ectodermal ridge is recognizable. Apical ectodermal ridge is the transient specialized epithelial structure along the distal end of each limb bud, formed during vertebrate limb morphogenesis.
Source: PMID:9323126, PMID: 9596583and PMID:18359901.
Ontology structure: 
child \(term of\) GO:0060174 limb bud formation \(part\_of relation\)

Synonyms: AER formation

2\) Regulation of apical ectodermal ridge formation
Any process that modulates the frequency, rate or extent of apical ectodermal ridge formation. Apical ectodermal ridge is the transient specialized epithelial structure along the distal end of each limb bud, formed during vertebrate limb morphogenesis.  
Ontology structure: 
child \(term of\) apical ectodermal ridge formation \(NTR\) \(regulates relation\)
Synonyms: Regulation of AER formation

3\) Positive regulation of apical ectodermal ridge formation
Any process that activates or increases the frequency, rate or extent of apical ectodermal ridge formation. Apical ectodermal ridge is the transient specialized epithelial structure along the distal end of each limb bud, formed during vertebrate limb morphogenesis.  
Ontology structure: 
child \(term of\) regulation of apical ectodermal ridge formation \(NTR\) \(is\_a relation\)
child \(term of\) apical ectodermal ridge formation \(NTR\) \(positively regulates relation\)

Synonyms: positive regulation of AER formation

4\) Negative regulation of apical ectodermal ridge formation
Any process that stops, prevents or reduces the frequency, rate or extent of apical ectodermal ridge formation. Apical ectodermal ridge is the transient specialized epithelial structure along the distal end of each limb bud, formed during vertebrate limb morphogenesis.  
Ontology structure: 
child \(term of\) regulation of apical ectodermal ridge formation \(NTR\) \(is\_a relation\)
child \(term of\) apical ectodermal ridge formation \(NTR\) \(negatively regulates relation\)

Synonyms: negative regulation of AER formation

Thank you,
Lakshmi Pillai

Reported by: lakshmipillai

Original Ticket: [geneontology/ontology-requests/10073](https://sourceforge.net/p/geneontology/ontology-requests/10073)

**Comment by ukemi** [comment]
[Term]
id: GO:1905139
name: apical ectodermal ridge formation
namespace: biological_process
def: "The process that gives rise to the apical ectodermal ridge. This process pertains to the initial formation of a structure from unspecified parts." [GO_REF:0000081, GOC:TermGenie, PMID:18359901, PMID:9323126, PMID:9596583]
synonym: "AER formation" RELATED [GOC:TermGenie]
synonym: "apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
is_a: GO:0048646 {is_inferred="true"} ! anatomical structure formation involved in morphogenesis
intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: results_in_formation_of UBERON:0004356 ! apical ectodermal ridge
relationship: results_in_formation_of UBERON:0004356 {is_inferred="true"} ! apical ectodermal ridge
created_by: dph

also made this a part of appendage morphogenesis.
creation_date: 2016-04-13T11:46:40Z

[Term]
id: GO:1905140
name: regulation of apical ectodermal ridge formation
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of apical ectodermal ridge formation." [GO_REF:0000058, GOC:TermGenie, PMID:18359901]
synonym: "regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
is_a: GO:0022603 {is_inferred="true"} ! regulation of anatomical structure morphogenesis
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:1905139 ! apical ectodermal ridge formation
relationship: regulates GO:1905139 {is_inferred="true"} ! apical ectodermal ridge formation
created_by: dph
creation_date: 2016-04-13T12:16:40Z


[Term]
id: GO:1905141
name: negative regulation of apical ectodermal ridge formation
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of apical ectodermal ridge formation." [GO_REF:0000058, GOC:TermGenie, PMID:18359901]
synonym: "down regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "down regulation of apical ectodermal ridge formation" EXACT [GOC:TermGenie]
synonym: "down regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "down regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "down-regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "down-regulation of apical ectodermal ridge formation" EXACT [GOC:TermGenie]
synonym: "down-regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "down-regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "downregulation of AER formation" RELATED [GOC:TermGenie]
synonym: "downregulation of apical ectodermal ridge formation" EXACT [GOC:TermGenie]
synonym: "downregulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "downregulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "inhibition of AER formation" RELATED [GOC:TermGenie]
synonym: "inhibition of apical ectodermal ridge formation" NARROW [GOC:TermGenie]
synonym: "inhibition of apical epidermal ridge formation" NARROW [GOC:TermGenie]
synonym: "inhibition of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "negative regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "negative regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "negative regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
is_a: GO:0051093 {is_inferred="true"} ! negative regulation of developmental process
is_a: GO:1905140 {is_inferred="true"} ! regulation of apical ectodermal ridge formation
intersection_of: GO:0065007 ! biological regulation
intersection_of: negatively_regulates GO:1905139 ! apical ectodermal ridge formation
relationship: negatively_regulates GO:1905139 {is_inferred="true"} ! apical ectodermal ridge formation
created_by: dph
creation_date: 2016-04-13T12:16:48Z


[Term]
id: GO:1905142
name: positive regulation of apical ectodermal ridge formation
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of apical ectodermal ridge formation." [GO_REF:0000058, GOC:TermGenie, PMID:18359901]
synonym: "activation of AER formation" RELATED [GOC:TermGenie]
synonym: "positive regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "positive regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "positive regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "up regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "up regulation of apical ectodermal ridge formation" EXACT [GOC:TermGenie]
synonym: "up regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "up regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "up-regulation of AER formation" RELATED [GOC:TermGenie]
synonym: "up-regulation of apical ectodermal ridge formation" EXACT [GOC:TermGenie]
synonym: "up-regulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "up-regulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
synonym: "upregulation of AER formation" RELATED [GOC:TermGenie]
synonym: "upregulation of apical ectodermal ridge formation" EXACT [GOC:TermGenie]
synonym: "upregulation of apical epidermal ridge formation" EXACT [GOC:TermGenie]
synonym: "upregulation of crista ectodermalis apicalis formation" RELATED [GOC:TermGenie]
is_a: GO:0051094 {is_inferred="true"} ! positive regulation of developmental process
is_a: GO:1905140 {is_inferred="true"} ! regulation of apical ectodermal ridge formation
intersection_of: GO:0065007 ! biological regulation
intersection_of: positively_regulates GO:1905139 ! apical ectodermal ridge formation
relationship: positively_regulates GO:1905139 {is_inferred="true"} ! apical ectodermal ridge formation
created_by: dph
creation_date: 2016-04-13T12:16:57Z
