### ISSUE TITLE
NTR: PCNA unloading (BP)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10292]
Hi,

I would like a term called 'PCNA unloading' or something equivalent based on this paper. 
http://www.sciencedirect.com/science/article/pii/S1097276513001408
http://www.ncbi.nlm.nih.gov/pubmed/23499004

child of DNA replication. 

Thanks,

Rama

Reported by: rbalakri

Original Ticket: [geneontology/ontology-requests/10089](https://sourceforge.net/p/geneontology/ontology-requests/10089)

**Comment by ukemi** [comment]
It looks like the term 'DNA clamp unloading' was created for the annotation of this paper and the item was never closed.
