### ISSUE TITLE
clarify tapetal layer/cell terms in GO

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10301]
GO terms:

tapetal cell differentiation, GO:0048657
tapetal cell fate specification, GO:0010234

Definitions refer to anther specific tapetum but there are non-anther tapetum terms in PO.

rename as anther wall tapetum cell differentiation,
GO:0048657 and anther wall tapetum cell fate specification, GO:0010234.

In a similar way, the following terms need to be renamed, tapetal layer -&gt; anther wall tapetum

tapetal layer formation, GO:0048656
tapetal layer development, GO:0048658
tapetal layer morphogenesis, GO:0048655

Revisit all definitions to make sure they are in line.

Relevant PO Sourceforge items:
https://sourceforge.net/tracker/index.php?func=detail&aid=3298006&group\_id=76834&atid=835555
https://sourceforge.net/tracker/index.php?func=detail&aid=3609728&group\_id=76834&atid=835555

Reported by: tberardini

Original Ticket: [geneontology/ontology-requests/10099](https://sourceforge.net/p/geneontology/ontology-requests/10099)

**Comment by tberardini** [comment]
Relevant bits shown:

[Term]
id: GO:0010234
name: anther wall tapetum cell fate specification
intersection_of: GO:0001708 ! cell fate specification
intersection_of: results_in_specification_of PO:0025545 ! anther wall tapetum cell

[Term]
id: GO:0048657
name: anther wall tapetum cell differentiation
intersection_of: GO:0030154 ! cell differentiation
intersection_of: results_in_acquisition_of_features_of PO:0025545 ! anther wall tapetum cell
