### ISSUE TITLE
placement of developmental induction

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10300]
cell-cell signaling: "Any process that mediates the transfer of information from one cell to another."

developmental induction: "Signaling at short range between cells or tissues of different ancestry and developmental potential that results in one cell or tissue effecting a developmental change in the other."

currently induction is a subclass of signaling. This is in conflict with the definition - cell-cell signaling is defined as being between individual cells. inductions between cells or tissues.

basic logic:

if A is a subclass of X, and B is a subclass of X-or-Y, then B cannot be a subclass of X, unless Y is the empty class.

This isn't just fussing - we won't be able to use TermGenie for the development part of the graph until we fix the overloading of isa.

Also, why isn't 'developmental induction' a subclass of developmental process.

I suggest simple logical definitions

GO:0031128 \! developmental induction "A developmental process involving the signaling at short range between cells or tissues of different ancestry and developmental potential that results in one cell or tissue effecting a developmental change in the other."
is\_a developmental process
has\_part cell-cell signaling involved in cell fate commitment

Minor note: the def dbxref says "mah" but this definition is clearly from Gilbert.

http://www.ncbi.nlm.nih.gov/books/NBK9993/

"This kind of interaction at close range between two or more cells or tissues of different history and properties is called proximate interaction, or induction There are at least two components to every inductive interaction. The first component is the inducer: the tissue that produces a signal \(or signals\) that changes the cellular behavior of the other tissue. The second component, the tissue being induced, is the responder."

Personally I find the first part of the Gilbert definition vague and not very useful for a computable representation. The second part is great \(apart from "cell behavior"\), and clearly lends itself to a LEGO representation.

I would actually write the definition as follows:

"A developmental process involving two tissues, in which one tissue \(the inducer\) produces a signal that changes the phenotype of the cells in the other tissue \(the responder\)"

alternately "developmental progression" for "phenotype"

"producing a signal" is still vague, need to explicitly reference cell-cell signaling

Regardless of the phrasing, the model is clear - the process has two tissue participants, and occurs\_in a region overlapping both tissues. The process has as part multiple individual cell-cell signaling processes \(and could be said to be the sum of these processes at a lower level of granularity\). At the end of the process, tissue T has developmentally progresses by virtue of the fact that it's parts \(cells\) have undergone cell fate specification.

This can be used as the basis for LEGO diagrams involving induction.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10097](https://sourceforge.net/p/geneontology/ontology-requests/10097)

**Comment by ukemi** [comment]
Agreed. Added logical def and changed textual def to:

"A developmental process involving two tissues in which one tissue (the inducer) produces a signal that directs cell fate commitment of cells in the second tissue (the responder)." [GOC:cjm, GOC:dph, GOC:mah, PMID:24503535]
