### ISSUE TITLE
Rename "multicellular organismal development"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10303]
to: Rename "multicellular organism development"

The adjectival form suggests that it's anything pertaining to the organism. But the class actually means whole organism.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10101](https://sourceforge.net/p/geneontology/ontology-requests/10101)

**Comment by dosumis** [comment]
Only changed organismal -> organism where the process refers to something happening to the whole organism (e.g. development, aging), rather that a process that occurs at the organism level (now all organismal).
