### ISSUE TITLE
mitosis and meiosis I & II/ nuclear division of cell cycle

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10312]
mitosis and meiosis I & II

outstanding question:
mitosis has a nuclear division parent, meiosis meiosis I and meiosis II don't
Either 
meiosis terms are a little broader and encompass MORE than nuclear division ? OR meiosis I and meiosis II should both have a nuclear division parent 

Q If meiosis is "a specialised type of nuclear division", when people refer to "meiosis" in the broader sense,  are they  really talking about the meiotic cell cycle, or meiotic development (i.e which would include sporulation in fission yeast). 
Q Should we define meiosis and mitosis as a type of nuclear division (qualified by the cell cycle in which it takes place (meiotic or mitotic). each should have 2 parents the "x cell cycle" & "nuclear division". 

Note: If meiosis I and meiosis II are the specialised nuclear divisions there are lots of child processes which are not part of nuclear division (premeiotic DNA replication processes for example). 
We need a term which represents any of the cell-cycle events which occur during (meiosis I + interphase) 
"meiosis I cell cycle process" and "meiosis II cell cycle process" (would that work ?) to capture all the events which happen during interphase AND meiosis of those specific divisions
and  terms to represent the nulcear division part of meiosis I and meiosis II

David to consult meiosis experts 

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10110](https://sourceforge.net/p/geneontology/ontology-requests/10110)

**Comment by ukemi** [comment]
It looks as though many of the children of meiosis I and meiosis II need to be removed  as children since the terms were merged. For example, meiosis I cytokinesis is not part of meiosis I (nuclear division) but it is a type of meiotic cytokinesis. Although meiosis is not really a cycle, it seems that the term meiotic cell cycle is used extensively in the literature. I think it makes sense to create meiosis I cell cycle process and meiosis II cell cycle process and group the respective terms appropriately.

**Comment by ukemi** [comment]
@ValWood . I have created the new grouping terms for meiosis I and meiosis II cell cycle processes. I have modified the logical defs of terms and tried to sort out the processes that were misplaced. There were a lot of edits, but I think I got it straight. Let me know if you spot anything strange.

**Comment by ValWood** [comment]
Sorry, missed this, it was during the period that I was not getting notifications.

I think this looks OK, except that 
https://www.ebi.ac.uk/QuickGO/term/GO:0030989

is actually involved in meiosis I (nuclear division)

Definition (Oscillatory movement of the nucleus _involved in meiosis I._

so the parentage needs to be switched from
GO:0061982    meiosis I cell cycle process
to GO:0007127    meiosis I

(these genes no longer captured by our slim)

**Comment by ukemi** [comment]
Done.
