### ISSUE TITLE
GO:0008935 definition update

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10329]
There have been some changes to the menaquinone biosynthesis pathway, and the definition of GO:0008935 needs to be updated.  Or maybe the term needs to be obsoleted and a new one created.  The 4.1.3.36 reaction is really 4-\(2-carboxyphenyl\)-4-oxobutanoyl-CoA = 1,4-dihydroxy-2-naphthoyl-CoA + H2O, and had been updated in the EC in 2010.

Thanks,
Ingrid

Reported by: imk07

Original Ticket: [geneontology/ontology-requests/10127](https://sourceforge.net/p/geneontology/ontology-requests/10127)

**Comment by ukemi** [comment]
Changed definition as above.
