### ISSUE TITLE
TPV: telomere maintenance

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10334]
telomere maintenance
has the parentage DNA metabolic process, but I am not sure that all of its parts are DNA metabolism (capping for example).

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10132](https://sourceforge.net/p/geneontology/ontology-requests/10132)

**Comment by ukemi** [comment]
regulation of DNA metabolic process?

@ValWood

**Comment by ValWood** [comment]
Some parts are DNA metabolism (telomere replication), but some parts are regulation (capping). I think this came up because of an oddity with the annotation intersections.  Maybe its a subtlety we need not worry about...

**Comment by ValWood** [comment]
Let's ignore this for now. I'm not sure that is correct but I don't know how it could be fixed....
