### ISSUE TITLE
merge?: telomere capping, telosome assembly?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10335]
I am trying to figure out the difference or relationship  between
telosome assembly
exact synonyms
exact: Pot1 complex assembly
exact: Pot1-Tpz1 complex assembly
exact: shelterin complex formation

and
GO:0016233 telomere capping
A process in which telomeres are protected from degradation and fusion, thereby ensuring chromosome stability by protecting the ends from both degradation and from being recognized as damaged DNA. May be mediated by specific single- or double-stranded telomeric DNA binding proteins.

(I requested the 'telosome assembly'  term, but it has only 1 annotation, from fission yeast, which is also annotated to "telomere capping"

There is also a component term:

There is a component term "telosome"
A nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. The complex contains TRF1, TRF2, POT1, RAP1, TIN2 and TPP1 in mammalian cells, and Pot1, Tpz1, Ccq1, Poz1, and Rap1 in Schizosaccharomyces. Taz1 and Rap1 (or their mammalian equivalents) form a dsDNA-binding subcomplex, Pot1 and Tpz1 form an ssDNA-binding subcomplex, and the two subcomplexes are bridged by Poz1.

In addition to the telomere cap complex terms.

They just seem to be different ways of describing the same processes/components?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10133](https://sourceforge.net/p/geneontology/ontology-requests/10133)

**Comment by ukemi** [comment]
Hi Val,

It looks like a subset of the proteins function in the assembly of the cap and then a superset function as the cap itself. Have a look at PMID:16880378.
@ValWood 

-D

**Comment by ValWood** [comment]
whatever the outcome
exact: Pot1 complex assembly
exact: Pot1-Tpz1 complex assembly
exact: shelterin complex formation
can't be exact synonyms of telomere assembly for sure....

**Comment by ukemi** [comment]
If these are exactly synonymous with the telosome then they are exact, but taking a conservative approach, I have changed them all to related.
