### ISSUE TITLE
New serous membrane development terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10337]
New Term
serous membrane development:
The process whose specific outcome is the progression of serous membranes over time, from its formation to the mature structure.  Serous membranes are multi-tissue structure that is comprised of a secretory epithelial layer \(mesothelium\) and a connective tissue layer.

is\_a: GO:0060429 
development of UBERON:0000042

New Term
peritoneum development:
The process whose specific outcome is the progression of the peritoneum  over time, from its formation to the mature structure.  The peritoneum is a serous membrane that lines the peritoneal cavity.
Is\_a: serous membrane development:
development of  UBERON:0002358

New Term
parietal peritoneum  development
The process whose specific outcome is the progression of the parietal  peritoneum  over time, from its formation to the mature structure.	The parietal peritoneum is the  peritoneum that lines the walls of the peritoneal cavity.
Is\_a: peritoneum development
UBERON:0001366

New Term
visceral peritoneum development
The process whose specific outcome is the progression of the parietal  peritoneum  over time, from its formation to the mature structure. 	Visceral peritoneum is the  peritoneum that covers the external surfaces of most abdominal organs.	
Is\_a: peritoneum development
development of UBERON:0001178

Note pericardial development GO:0060039 is\_a serous membrane devleopment

Reported by: cerivs

Original Ticket: [geneontology/ontology-requests/10135](https://sourceforge.net/p/geneontology/ontology-requests/10135)

**Comment by ukemi** [comment]
Terms created using new TG template. Relations modified in Protege.
