### ISSUE TITLE
definition of primosome

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10358]
Hi,

I requested a term for the primosome on Friday but now saw that there are already names in the ontology biological process lineage that refer to this complex in eukaryotes:

GO:0071163  DNA replication preinitiation complex assembly, and
GO:0006267  pre-replicative complex assembly.

I'm struggling to see the difference between these two terms, they are entirely parallel in the ontology and don't really differ in their definition.

Although they refer to eukaryotic replication it looks as if they could also be applicable to prokaryote replication. In that case we could call the primosome complex either pre-replicative complex or replication preinitiation complex. I would probably prefer pre-replicative complex as then it can also refer to the complexes formed during restart of replication at a stalled replication fork (see SF request 3612171)

Thanks,
Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/10156](https://sourceforge.net/p/geneontology/ontology-requests/10156)

**Comment by pgaudet** [comment]
@bmeldal 
Can you please tell me what is the action remaining on this ticket ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
On 5 June 2013 Becky signed off with:

> STILL TO DO ON THIS TICKET:
- [ ] Sort out how primosome fits in with the pre-RC and pre-RI complexes.
- [ ] Rehouse Birgits DnaA/DnaB complex terms accordingly (see above)

I don't think anything further was done away from this ticket.
However, we've started started looking at the TFs with Astrid and Ruth, so I may be able to answer these points once I got my teeth into the TF philosophy! (although the GREEKC grant only seems to look at human)

I'll keep a note to come back to this ticket soon :)

**Comment by bmeldal** [comment]
@RLovering we should keep this ticket in mind when we discuss TFs with Astrid (what's her GH id?)

**Comment by RLovering** [comment]
sorry I don't know

**Comment by pgaudet** [comment]
Hi @bmeldal

This is DNA replication; are you sure it's related to tx factors ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @bmeldal - any progress on this one ?

**Comment by ValWood** [comment]
Closing as out of date. If any action is required please summarize in a new ticket.
