### ISSUE TITLE
Pre-B/immature B cell terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10368]
For CL-GO work, I've just removed the following logical definitions:

[Term]
id: GO:0002327 ! immature B cell differentiation
intersection_of: GO:0030154 ! cell differentiation
intersection_of: results_in_acquisition_of_features_of CL:0000816 ! immature B cell

[Term]
id: GO:0002329 ! pre-B cell differentiation
intersection_of: GO:0030154 ! cell differentiation
intersection_of: results_in_acquisition_of_features_of CL:0000817 ! precursor B cell

These were causing problems because the hierarchy of the cell types is inverted in GO vs. CL:

GO hierarchy:

          is_a GO:0002327 ! immature B cell differentiation
           is_a GO:0002329 ! pre-B cell differentiation ***

CL hierarchy - inverted!

          is_a CL:0000817 ! precursor B cell
            is_a CL:0000816 ! immature B cell ***

I've put in a CL ticket:
http://code.google.com/p/cell-ontology/issues/detail?id=36&thanks=36&ts=1367577233

Once the correct placement of the cell types has been solved, add the logical defs. back in.  

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/10166](https://sourceforge.net/p/geneontology/ontology-requests/10166)

**Comment by paolaroncaglia** [comment]
Added back logical def to GO:0002329 ! pre-B cell differentiation.
