### ISSUE TITLE
sympathetic neuron projection extension/guidance

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10445]
Hi
I am in discussion with Christiana Ruhrberg about annotation of her paper PMID:22790009.

GO only has the term: GO:0048846 axon extension involved in axon guidance, not dendrite or neuron projection extension involved in xxx guidance. From what is said in PMID:22790009, top right of p281, Christiana has confirmed that need new GO terms which do not include axon specifically. Please see SF ticket #10244 sympathetic neuron extension  for request for new GO terms for 'extension'. 

Firstly I think the the parents for GO:0070983 dendrite guidance and  GO:0007411 axon guidance need to be standardised. 
GO:0070983 dendrite guidance has the parent: GO:0006928 cellular component movement
GO:0007411 axon guidance has the parent:  GO:0006935 chemotaxis
I think both should have both (grand)parents.

Then a new less specific parent for both is needed:
GO:0006935 chemotaxis
GO:0006928 cellular component movement

> is_a NewGO term: neuron projection guidance
> GO:0048812 neuron projection morphogenesis
> part of NewGO term: neuron projection guidance
> 
> > is_a GO:0070983 dendrite guidance
> > 
> > is_a GO:0007411 axon guidance
> > 
> > > is_a NewGO term: sympathetic axon guidance
> > 
> > is_a NewGO term: sympathetic neuron projection guidance
> > 
> > > is_a NewGO term: sympathetic axon guidance
> > 
> > part of NewGO term: neuron projection extension involved in neuron projection guidance

See SFticket #10244 sympathetic neuron extension for NewGO term: neuron projection extension

> > is_a NewGO term: neuron projection extension involved in neuron projection guidance

New GO term neuron projection guidance 
Definition: The process in which the migration of a neuron projection is directed to a specific target site in response to a combination of attractive and repulsive cues.
Synonyms: neurite guidance
With the dbxrefs: GOC:BHF, GOC:rl

NewGO term: sympathetic neuron projection guidance
Definition: The process in which the migration of a sympathetic neuron projection is directed to a specific target site in response to a combination of attractive and repulsive cues.
Synonyms: sympathetic neurite guidance
With the dbxrefs: GOC:BHF, GOC:rl

NewGO term: sympathetic axon guidance
Definition: The process in which the migration of a sympathetic axon is directed to a specific target site in response to a combination of attractive and repulsive cues.
Synonyms: sympathetic neurite guidance
With the dbxrefs: GOC:BHF, GOC:rl

New GO term: neuron projection extension involved in neuron projection guidance
Definition:The long distance growth of a single cell process, that is involved in the migration of an neuron projection growth cone, where the migration is directed to a specific target site by a combination of attractive and repulsive cues.
synonyms: guidance of neurite extension, guidance of neuron projection extension, neurite extension involved in neurite guidance
With the dbxrefs: GOC:BHF, GOC:rl

Then some terms with semaphorin-plexin signaling:
GO:0006935 chemotaxis
GO:0006928 cellular component movement

> is_a NewGO term: neuron projection guidance
> GO:0048812 neuron projection morphogenesis
> part of NewGO term: neuron projection guidance
> 
> > part of NewGO term:semaphorin-plexin signaling involved in neuron projection guidance

GO:0071526 semaphorin-plexin signaling pathway

> is_a NewGO term:semaphorin-plexin signaling involved in neuron projection guidance
> 
> > is_a NewGO term:semaphorin-plexin signaling involved in dendrite guidance
> > is_a NewGO term:semaphorin-plexin signaling involved in axon guidance

So here I am going to assume you will use modified definitions and parents based on existing terms (and suggestions below), and synonyms with English spelling of signalling and with the dbxrefs: GOC:BHF, GOC:rl.

NewGO term:semaphorin-plexin signaling involved in neuron projection guidance
Definition:A series of molecular signals generated as a consequence of a semaphorin receptor (composed of a plexin and a neurophilin) binding to a semaphorin ligand that contributes to neuron projection guidance.
synonyms: semaphorin-plexin signalling involved in neurite guidance, semaphorin-plexin signalling involved in neuron projection guidance, semaphorin-plexin signalling involved in neurite guidance
With the dbxrefs: GOC:BHF, GOC:rl

Sorry if this could have all been done with term genie, just tricky as some of the intermediate terms are missing.

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/10245](https://sourceforge.net/p/geneontology/ontology-requests/10245)

**Comment by paolaroncaglia** [comment]
Requested CL:0011103 (sympathetic neuron) in imports_requests.obo today. When that’s available,
- [ ] add logical def to ‘sympathetic neuron axon guidance’ (is_a axon guidance, occurs_in sympathetic neuron)
