### ISSUE TITLE
def of GO:0007519 ! skeletal muscle tissue development 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10538]
```
id: GO:0007519
name: skeletal muscle tissue development
def: "The developmental sequence of events leading to the formation of adult muscle that occurs in the anima. In vertebrate skeletal muscle the main events are: the fusion of myoblasts to form myotubes that increase in size by further fusion to them of myoblasts, the formation of myofibrils within their cytoplasm and the establishment of functional neuromuscular junctions with motor neurons. At this stage they can be regarded as mature muscle fibers." [GOC:mtg_muscle]
synonym: "myogenesis" RELATED []
is_a: GO:0014706 ! striated muscle tissue development
relationship: part_of GO:0060538 ! skeletal muscle organ development
```

What is the "anima"? Is this meant to be "animal"? What exactly is "adult muscle" anyway?

Consider giving this a textual definition that conforms to genus-differentia structure. How does this kind of muscle development differ from its parent, striated muscle tissue development?

Also consider adding notes on taxon applicability. See

http://amigo2.geneontology.org/cgi-bin/amigo2/amigo/term/GO:0007519

remove Chordata from the taxon list - you'll see this has been used for insects. Is this the same of "somatic muscle tissue" in insects?

See also: https://github.com/obophenotype/uberon/issues/324

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10340](https://sourceforge.net/p/geneontology/ontology-requests/10340)

**Comment by dosumis** [comment]
Fixed
