### ISSUE TITLE
pellicle implicit taxon constraint not correct

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10561]
```
GO:0020039 ! pellicle ***  [DEF: "The structure enclosing an apicomplexan parasite cell; consists of the cell membrane with its associated infrastructure of microtubules, microfilaments and other organelles."]
```

If we believe the def, we should have a taxon constraint. 

However, I think a pellicle is found in non-apicomplexans, e.g.

http://en.wikipedia.org/wiki/Euglenid

I don't know if this is homologous, and if GO intends to restrict this.

If the intention is to be generic then adopt the def here
http://en.wikipedia.org/wiki/Protozoa#Pellicle

However, this sounds like a very fuzzy grouping here, so it might be better to have specific terms based on the constituents of the membrane.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10365](https://sourceforge.net/p/geneontology/ontology-requests/10365)

**Comment by krchristie** [comment]
paper I found during meeting on 1/29/18: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4760376/

**Comment by pgaudet** [comment]
GO:0020039 pellicle
Added taxon constraints: 
+property_value: never_in_taxon "Bacteria" xsd:string
+property_value: never_in_taxon "Opisthokonta" xsd:string

----
 id: GO:0070258
Rename: inner membrane complex
To inner membrane pellicle complex
----
GO:0032022
-name: multicellular pellicle formation
Merge into single-species surface biofilm formation
As there were not distinguishing features between the two terms. 


Pascale
