### ISSUE TITLE
possible obsoletion of mitotic/meiotic transcription terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10594]
I found some more odd transcription terms
suggest obsoletion

1# regulation of transcription during mitosis 
(I doubt we mean 'mitosis" as in nuclear division
more likely this means
regulation of tanscription during mitotic cell cycle)
PomBase 11 (query the ace2 ones)

2# negative regulation of transcription during mitosis 
SGD 6
PomBase 6
Flybase 2

3# positive regulation of transcription during mitosis
PomBase 3

For these  we would be happy to capture  by adding an extension to the transcription terms to capture  the relevant phase.

ALSO

positive regulation of transcription on exit from mitosis ; GO:0007072
is under this term..... I'm not sure that it should be (what does "on exit?" mean?)
does it mean after M-phase?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10399](https://sourceforge.net/p/geneontology/ontology-requests/10399)

**Comment by ValWood** [comment]
I think this one is pending obsoletion notice and migration of existing to the 
"regulation of transcription during mitotic/meiotic cell cycle"

**Comment by tberardini** [comment]
@ValWood :  I dug into the history a bit.  It looks like the terms for the meiosis regulation tsc terms were transformed from 'regulation of transcription, meiotic' to 'regulation of transcription during meiosis' to 'regulation of transcription involved in meiotic cell cycle' all while retaining the same id. (done in 2015)

Example:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051037#term=history

What if we just do the same for the mitosis terms?

Convert all 'during mitosis' (or , mitotic) to 'involved in mitotic cell cycle?

*regulation of transcription during mitosis
*positive regulation of transcription during mitosis
*negative regulation of transcription during mitosis
*regulation of transcription from RNA polymerase I promoter, mitotic
*positive regulation of transcription from RNA polymerase I promoter during mitosis
*negative regulation of transcription from RNA polymerase I promoter during mitosis
*regulation of transcription from RNA polymerase II promoter, mitotic
*positive regulation of transcription from RNA polymerase I promoter during mitosis
*negative regulation of transcription from RNA polymerase I promoter during mitosis
*regulation of transcription from RNA polymerase I promoter, mitotic
*positive regulation of transcription from RNA polymerase I promoter during mitosis
*negative regulation of transcription from RNA polymerase I promoter during mitosis

What about these?  Are they good as is?

*positive regulation of transcription on exit from mitosis
*positive regulation of transcription on exit from mitosis, from RNA polymerase I promoter
*positive regulation of transcription on exit from mitosis, from RNA polymerase II promoter
*positive regulation of transcription on exit from mitosis, from RNA polymerase III promoter

**Comment by ValWood** [comment]
Hi Tanya,

I don't think we can do that. These really are "during".
So   this is more about the distinction between "mitotic nuclear division" and "mitotic cell cycle"

All  these transcription terms mean is that the transcription occurs *during* the mitotic cell cycle.  In known cases where they are involved, a term already exists
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000083#term=ancchart
this term could have the "involved in" parent you suggest. But, the other annotations to the existing "during" terms are not involved in cell cycle regulation.

For example, the genes transcribed can include every cellular process  which occurs during the mitotic cell cycle.

I don't know about
"positive regulation of transcription on exit from mitosis"
(exit from mitosis is not a well defined process, and  I'm still not convinced that it isn't really a transition, rather than a process)...I hope to follow up on this at some point when I move onto cytokinesis (Need to finish chromosome segregation first) so maybe these  terms can hang around for a while longer.

**Comment by ValWood** [comment]
positive regulation of transcription on exit from mitosis
only has 3 annotations.  it wont do any harm . However the confusion in the other terms between 


during 
mitosis = GO:0007067	mitotic nuclear division
and
(incorrect)

and during 
GO:0000278 mitotic cell cycle
(correct)

Longer term "during" terms can be made consistently with annotation extensions, so potentially longer term these can all go....

**Comment by ValWood** [comment]
Actually I think you can make these terms
'regulation of transcription involved in mitotic cell cycle'

but I would not automatically merge the old term unless the annotations are checked individually (I think the other ones were)

**Comment by tberardini** [comment]
Val - there are no 'involved in mitotic cell cycle' terms to merge into.  There are only the existing 'during mitosis' and ',mitotic' terms.  If renaming is fine, that makes the job a WHOLE LOT easier.

**Comment by ValWood** [comment]
No this was the problem.

The phrase "during mitosis" appears to be used as shorthand for "during mitotic cell cycle" in the same way that  "during meiosis" was used as shorthand for "during meiotic cell cycle"

The scan of the annotations validated this, because it is used for transcription  which occurs "during the mitotic cell cycle"  but which is NOT "during mitosis"

Clearer? 

There are 2 solutions
i) change all terms and logical definitions to "during mitotic/meiotic cell cycle" not "during meiosis/mitosis" 
or 
ii) obsoletion  (probably better as the terms are not really required)

this problem all comes back to these ticket:
https://github.com/geneontology/go-ontology/issues/10864
https://github.com/geneontology/go-ontology/issues/10690

**Comment by tberardini** [comment]
Ok.  I'll write up an obsoletion email for these terms:

*regulation of transcription during mitosis
*positive regulation of transcription during mitosis
*negative regulation of transcription during mitosis
*regulation of transcription from RNA polymerase I promoter, mitotic
*positive regulation of transcription from RNA polymerase I promoter during mitosis
*negative regulation of transcription from RNA polymerase I promoter during mitosis
*regulation of transcription from RNA polymerase II promoter, mitotic
*positive regulation of transcription from RNA polymerase I promoter during mitosis
*negative regulation of transcription from RNA polymerase I promoter during mitosis
*regulation of transcription from RNA polymerase I promoter, mitotic
*positive regulation of transcription from RNA polymerase I promoter during mitosis
*negative regulation of transcription from RNA polymerase I promoter during mitosis

**Comment by ValWood** [comment]
I thought they had already been cleared for obsoletion. But I guess there are more terms now. I see what you mean. You could change all to

"during mitotic cell cycle", which is broader.

**Comment by tberardini** [comment]
Yes, I started with just the root term but when I went to look at annotations, I saw the raft of children terms and that's kind of where it stalled. 
<img width="272" alt="screen shot 2016-11-11 at 4 53 15 pm" src="https://cloud.githubusercontent.com/assets/4998871/20234387/5dca6ddc-a82f-11e6-80f0-f1ee41b26cfd.png">

This is the spread of annotations to 'regulation of transcription during mitosis' and children

**Comment by tberardini** [comment]
If looking at only experimental annotations:

<img width="278" alt="screen shot 2016-11-11 at 4 54 44 pm" src="https://cloud.githubusercontent.com/assets/4998871/20234396/99cea848-a82f-11e6-8574-f5e2b7baca2b.png">

**Comment by ValWood** [comment]
I would change to the "mitotic cell cycle" for now, which is how the terms have been used. At some future date we might want to visit the value of "precompostition" of these  transcription "during" terms

**Comment by tberardini** [comment]
>I would change to the "mitotic cell cycle" for now,

To be absolutely clear, this means changing '% regulation of transcription % **during mitosis**' or 'regulation of transcription from RNA polymerase [I or II] promoter**, mitotic**' to '%regulation of transcription % **involved in mitotic cell cycle**' and 'regulation of transcription from RNA polymerase [I or II] promoter **involved in mitotic cell cycle**'.

Final answer?

**Comment by ValWood** [comment]
Nearly;)

All should still be during not involved in (these are different)
All should be during mitotic cell cycle, not during mitosis

**Comment by tberardini** [comment]
Ok, restating:

- [ ] '% regulation of transcription % during **mitosis**' change to '%regulation of transcription % during **mitotic cell cycle**'

- [ ] 'regulation of transcription from RNA polymerase [I or II] promoter**, mitotic**' change to 'regulation of transcription from RNA polymerase [I or II] promoter **during mitotic cell cycle**'.

**Comment by ValWood** [comment]
Yes, sorry for the confusion!

**Comment by tberardini** [comment]
OK, done and done.
