### ISSUE TITLE
start of DNA replication

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10596]
When does DNA replication start? I think it starts with the binding of ORC recognition proteins to the DNA forming a complex. I also take "start", "begin" to be a synonym of "initiates", and starting implying parthood.

This is of course what we have:

DNA replication:
http://amigo2.geneontology.org/cgi-bin/amigo2/amigo/term/GO:0006260
"...DNA replication **begins when** specific sequences, known as origins of replication, are recognized and bound by initiation proteins...."

Minor point: Is there a way to define this using GO terms rather than the vague "initiation protein"?

But it's less clear in other GO definitions, where the process of initiation is mentioned. This seems a bit fuzzy as to temporal boundaries, although I would take "initiation" to be at the start. For example:

DNA replication preinitiation complex assembly:
http://amigo2.geneontology.org/cgi-bin/amigo2/amigo/term/GO:0071163
"The aggregation, arrangement and bonding together of a set of components to form the DNA replication preinitiation complex, a protein-DNA complex that is assembled at eukaryotic DNA replication origins **_immediately prior to**_ the initiation of DNA replication, by the assembly of additional proteins onto an existing prereplicative complex"

The def makes it sound like this happens prior to DNA replication, but it is (correctly) asserted as part_of replication (is this correct - preinitiation complex assembly is preceded by prereplicative complex assembly, and prereplicative complex assembly is the process that RO:starts DNA replication? Does every preinitiation complex derive_from some prepreplicative complex?).

Maybe the def should be modified: change "immediately prior to the initiation of" to "as part of"?

(also: s/prereplicative/pre-replicative/)

initiation has its own class in GO, but this is defined vaguely:
http://amigo2.berkeleybop.org/cgi-bin/amigo2/amigo/term/GO:0006270
"The process in which DNA-dependent DNA replication is started; this involves the separation of a stretch of the DNA double helix, the recruitment of DNA polymerases and the initiation of polymerase action"

Does the "this" refer to the initiation or the DNA replication as a whole? What are the defining start and end events of initiation? No ordering is given. Terms like "recrutiment of DNA polymerase" doesn't seem to correspond to the existing terms in the GO.

There are no part children of initiation. But isn't GO:0036388 pre-replicative complex assembly always part of initiation? Do we need a part_of here?

See also
http://en.wikipedia.org/wiki/DNA_replication#Initiation

Would it be correct to define initiation as starting with ORC binding, encompassing various stages of complex assembly depending on species, and ending with... DNA unwinding? (http://amigo2.geneontology.org/cgi-bin/amigo2/amigo/term/GO:0006268)

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10401](https://sourceforge.net/p/geneontology/ontology-requests/10401)

**Comment by pgaudet** [comment]
> Minor point: Is there a way to define this using GO terms rather than the vague "initiation protein"?


Changed "initiation protein" to "origin recognition complex", which is a GO CC.

> DNA replication preinitiation complex assembly:
http://amigo2.geneontology.org/cgi-bin/amigo2/amigo/term/GO:0071163
"The aggregation, arrangement and bonding together of a set of components to form the DNA replication preinitiation complex, a protein-DNA complex that is assembled at eukaryotic DNA replication origins _immediately prior to_ the initiation of DNA replication, by the assembly of additional proteins onto an existing prereplicative complex"

> The def makes it sound like this happens prior to DNA replication, but it is (correctly) asserted as part_of replication (is this correct - preinitiation complex assembly is preceded by prereplicative complex assembly, and prereplicative complex assembly is the process that RO:starts DNA replication? Does every preinitiation complex derive_from some prepreplicative complex?).

> Maybe the def should be modified: change "immediately prior to the initiation of" to "as part of"?

Changed.
