### ISSUE TITLE
Review GO terms referencing myotube

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10595]
Myotube in CL has recently been broadened to cover both arthropod somatic muscle and skeletal muscle fibers (formerly restricted to latter) - with new subclasses added for skeletal muscle fiber and somatic muscle myotube.  See [this ticket](https://code.google.com/p/cell-ontology/issues/detail?id=92) and [this commit](https://code.google.com/p/cell-ontology/source/detail?r=276).

In the light of these changes, terms in GO referencing myotubes (and the few referencing skeletal muscle fibers) need to be reviewed for whether they have skeletal muscle specific aspects to their definitions and relations.  If so, need to decide whether to add new specific or new general terms.  Probably the former but should review annotations first.

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/10400](https://sourceforge.net/p/geneontology/ontology-requests/10400)

**Comment by pgaudet** [comment]
@ukemi 
I think you did a related issue recently; did your changes take care of this issue here ?

**Comment by pgaudet** [comment]
Checked all terms with 'myotube', and they are all either general (ie, do not mention specifically somatic muscle and skeletal muscle fibers), or they are specific to somatic muscles. 
So it may be that we need more specific terms for skeletal muscle fibers but right now extsting terms and definitions are correct.
