### ISSUE TITLE
annotations to GO:0047141

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10618]
Hello,

Hoping you can help with this. Nothing at all is annotated to this term which seemed a bit strange. Am I correct in thinking that monothiol glutaredoxin catalyze this reaction:

ID 	GO:0047141
Name 	glutathione-cystine transhydrogenase activity
Ontology 	Molecular Function
Definition 	Catalysis of the reaction: cystine + 2 reduced glutathione = oxidized glutathione + 2 L-cysteine.

(which couples to glutathione reductase activity

ID 	GO:0004362
Name 	glutathione-disulfide reductase activity
Ontology 	Molecular Function
Definition 	Catalysis of the reaction: 2 glutathione + NADP+ = glutathione disulfide + NADPH + H+.)

Cheers...
Antonia.

Reported by: antonialock

Original Ticket: [geneontology/ontology-requests/10423](https://sourceforge.net/p/geneontology/ontology-requests/10423)

**Comment by ukemi** [comment]
Assuming this was resolved.
