### ISSUE TITLE
 Cellular response to protozoan 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10633]
PMID:16369915; Knockdown of IRAK1 using IRAK1 siRNA resulted in impairment of TNF production by Leishmania donovani-infected macrophages.
PMID:19104650; Upon stimulation with TLR4 agonist, IRAK1 associated with MYD88 but failed to associate with TRAF6 in Leishmania donovani-infected macrophages.

Reported by: cusin

Original Ticket: [geneontology/ontology-requests/10438](https://sourceforge.net/p/geneontology/ontology-requests/10438)

**Comment by dosumis** [comment]
Added - but worth noting that Protozoan is a very mixed class (no longer supported by taxonomies/phylogenies), so maintenance of classes under this will have to be manual.
