### ISSUE TITLE
GO:0071972 ! peptidoglycan L,D-transpeptidase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10640]
GO:0071972 ! peptidoglycan L,D-transpeptidase activity is the only peptidoglycan transpeptidase  activity I can find in GO, and defined based on a MetaCyc reaction making the crosslinks between a Lysine and a modified Lysine as found in Enterococcus faecium.  This is only one of several kinds of peptidoglycan transpeptidase activities and is not the major one common to most bacteria.

I am looking for how to propose to restructure peptidoglycan-related activity terms, but I wanted to post a ticket in case someone else can weigh in. It's more complicated than the textbook view. See

http://mmbr.asm.org/content/36/4/407.full.pdf

and 

http://www.jbc.org/content/282/18/13151.long

Cursory look at ChEBI is not finding anything helpful

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/10445](https://sourceforge.net/p/geneontology/ontology-requests/10445)

**Comment by pgaudet** [comment]
@jimhu-tamu 
Would the proteins currently annotated to http://amigo.geneontology.org/amigo/term/GO:0071972 
be OK under the "new" parent term term you proposed ? (peptidoglycan transpeptidase activity)
In this case I could just rename it ? (and all other children as requested) 

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
I think the umbrella term covers it, but they aren't EXACT, so not sure what you mean by "rename it"

**Comment by pgaudet** [comment]
I was proposing  to change label of 'GO:0071972 ! peptidoglycan L,D-transpeptidase activity' to the new umbrella term you propose: 
NTR: peptidoglycan transpeptidase activity

and yes, 'peptidoglycan L,D-transpeptidase activity' would be a 'NARROW synonym'. 

----
In fact my question was, out of the list of terms you have above, to which should have the proteins already annotated have been annotated to ?  (which would avoid reannotation). 

Or perhaps the annotations are not correct, in which case obsoletion would be better. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Out of date - if needed we'll open a new ticket.
