### ISSUE TITLE
New term: embryonic hematopoietic  or lymphoid tissue development

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10686]
The process whose specific outcome is the progression of any embryonic tissue involved in hematopoiesis (also known as hemopoiesis) or lymphoid cell activation over time, from its formation to the mature structure. Such development includes differentiation of resident cell types (stromal cells) and of migratory cell types dependent on the unique microenvironment afforded by the organ for their proper differentiation.
is_a GO:0048534  hematopoietic or lymphoid organ development

For zebrafish PMID:19168679

What I am shooting for here is a term that is general enough for Zebrafish and Mouse to use for ICM, AGM, blood islands, fetal liver and ventral wall of dorsal aorta.  I also want it to be of use to all the other MODs too. I don't really want to go to the trouble to make all the possible child terms.   

Reported by: cerivs

Original Ticket: [geneontology/ontology-requests/10495](https://sourceforge.net/p/geneontology/ontology-requests/10495)

**Comment by ValWood** [comment]
Is this still a GO issue?

**Comment by ValWood** [comment]
@cmungall

**Comment by pgaudet** [comment]
@sabrinatoro @ukemi @hdrabkin 
can you please comment ?

**Comment by hdrabkin** [comment]
Not an expert in this area.  The requester needs to add definition, parent, and PMID for each term requested.

**Comment by pgaudet** [comment]
@cerivs

**Comment by cerivs** [comment]
I am going to restate the original request (with correct spelling)   embryonic hematopoietic and lymphoid tissues aren't organs.  Experimentally defined by gene expression and cell types they are in flux during embryonic stages and it is better to have  a term that can encompass all of the dynamic processes in the early embryo.

NTR: embryonic hematopoietic or lymphoid tissue development 
The process whose specific outcome is the progression of any embryonic tissue involved in hematopoiesis (also known as hemopoiesis) or lymphoid cell activation over time, from its formation to the mature structure. Such development includes differentiation of resident cell types (stromal cells) and of migratory cell types dependent on the unique microenvironment afforded by the tissue for their proper differentiation.

Is_a tissue development
part_of GO:0009790 embryo development
development of  UBERON:0034769 lymphomyeloid tissue

**Comment by pgaudet** [comment]
Added 

 
+[Term]
+id: GO:0140152
+name: embryonic hematopoietic or lymphoid tissue development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of any embryonic tissue involved in hematopoiesis (also known as hemopoiesis) or lymphoid cell activation over time, from its formation to the mature structure. Such development includes differentiation of resident cell types (stromal cells) and of migratory cell types dependent on the unique microenvironment afforded by the tissue for their proper differentiation." [PMID:19168679]
+is_a: GO:0009888 ! tissue development
+relationship: part_of GO:0009790 ! embryo development
+created_by: pg
+creation_date: 2018-01-09T10:41:51Z
+

Cannot figure out how to add 
development of UBERON:0034769 lymphomyeloid tissue

@ukemi can you please help ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@cerivs We are wondering what children would go under this ? 
@addhiel If you have any feedback about this proposed term that would be much appreciated. 
Thanks, Pascale

**Comment by cerivs** [comment]
Off the top of my head a bunch of new embryonic lymphatic and vascular tissue development terms that I don't want to spend time requesting.
For zebrafish 
vascular cord development
ventral wall of the dorsal aorta development, mammals have agm tissue development
intermediate cell mass of mesoderm development
blood island development (caudal tissue)
rostral blood island development

I'm probably missing a bunch and mammals may have more too.

**Comment by pgaudet** [comment]
Thanks for your reply @cerivs 

So, should these terms be moved under that new term? For example: 
-     GO:0035907    dorsal aorta development
-     GO:0072360    vascular cord development
-     GO:0048389    intermediate mesoderm development ? 


Also, is this related to GO:0072358 cardiovascular system development? 
Thanks again, Pascale

**Comment by cerivs** [comment]
These should
GO:0035907 
GO:0072360   
The other gives rise to kidney & gonads. The ICM develops from the lateral plate mesoderm (which is probably different from the lateral mesoderm in zebrafish) 

The hematopoetic tissue development is related to the cardiovascular system development.  They develop several in several of the same embryonic regions but the hematopoetic regions are much more dynamic.  hematopoetic cells infiltrate vascular cells and need the vascular environment to mature.   We organize them as distinct systems since not all lymphoid cells are blood components.

**Comment by addiehl** [comment]
I am happy with the proposed term 'embryonic hematopoietic or lymphoid tissue development' which I guess has been already added but is not yet visible in AmiGO.

For mammals, a term like "fetal liver development" would be an obvious child of this term, as the fetal liver is the primary site of hematopoiesis in prenatal development (reviewed in PMID:16968814, among many places).   I would advocate for creating this term, as there are related phenotypes in KO mice that could be the basis of GO annotations (PMID:22158967, for instance).

-- Alex (@addiehl, NOT @addhiel)

**Comment by pgaudet** [comment]
How about the parent 'GO:0001568 blood vessel development'? It seems like that would be the most appropriate. 

Thanks, Pascale

**Comment by cerivs** [comment]
Tissue development would be the best parent.  Zebrafish embryonic hematopoetic tissue encompasses the rostral blood islands on the yolk sack, the intermediate cell mass of mesoderm,  the ventral wall of the dorsal aorta and eventually end up in the kindney.

**Comment by cmungall** [comment]
why aren't we inferring the parent?

**Comment by pgaudet** [comment]
Hi @cmungall OK to infer the parent (=  'tissue development' anyway) 

Don't we expect any children to be inferred based on Uberon relations?

**Comment by pgaudet** [comment]
Hi @cerivs 
Do you want development of UBERON:0034769 lymphomyeloid tissue
or development of some embryonic version of that term ? 

Thanks, Pascale

**Comment by cerivs** [comment]
How about an embryonic version of that term. That term is not wrong but we do want to restrict this term to immature stages.

**Comment by pgaudet** [comment]
Can you please provide a Uberon term for that?

**Comment by pgaudet** [comment]
I am not sure it exists; it probably had to be requested. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@cerivs Did you request the embryonic version of UBERON:0034769 lymphomyeloid tissue? 

So I can finish this ticket- 

Thanks, Pascale

**Comment by pgaudet** [comment]
@cerivs I still cannot find  the embryonic version of UBERON:0034769 lymphomyeloid tissue?
Would you please request it ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@sabrinatoro maybe you can help ?

**Comment by cerivs** [comment]
Sorry, getting too many github notifications and signal is lost to the noise https://github.com/obophenotype/uberon/issues/1457

**Comment by sabrinatoro** [comment]
@pgaudet : see Ceri's message above

**Comment by pgaudet** [comment]
thanks !

**Comment by pgaudet** [comment]
@sabrinatoro @cerivs has the term been created?

**Comment by cerivs** [comment]
http://purl.obolibrary.org/obo/UBERON_0034769

**Comment by cerivs** [comment]
That is a yes.

**Comment by cmungall** [comment]
Let me try and summarize. The uberon request is for the embryonic form of an existing class "lymphomyeloid tissue" http://purl.obolibrary.org/obo/UBERON_0034769

I can fulfil this request if this is truly required. I am not sure it is as @cerivs  says she is satisfied the term has been created, although the class you reference is the stage-neutral version.

My preference is not to create embryonic-X terms in uberon; and not to have embryonic-X development terms in GO. However, if there is a true histological or morphological or biological difference I will be much happier to create. What are your preferences @cerivs?

Note that there is no need for the embryonic-X term in uberon to have embryonic-X-development in GO. If the intent of the term is truly to qualify a developmental process with the stage of development in which it occurs, then the DP should be X-development and happens_during some Y-stage.

I am not sure we need these terms in GO, but there is precedence.

Apologies for the delay on this. This is an area where we need to dedicate some resources to refactor the existing ontology and specify design patterns in order to make ourselves more efficient.

**Comment by ukemi** [comment]
My 2 cents. I have always thought the embryonic development terms in GO were problematic. If the stage information is critical for an annotation, I prefer the solution suggested by @cmungall in the comment above.

**Comment by pgaudet** [comment]
That means we would not create 'embryonic hematopoietic or lymphoid tissue development'. 
@cerivs you seem OK with the stage-neutral term; can we close this ticket ? 

Thanks, Pascale

**Comment by cerivs** [comment]
We might be able to use noctua and the GOCAMs to work around this but I am not sure.  The embryonic developmental processes are different then the processes in the more mature organism, they have different regulatory feedback, different cells (no stem cells) and occur in different locations.  This may be one of the cases where we want to make a term to save time, or some group can come up with a model we could copy and reuse that takes into account the different progenitor cells, locations etc.

**Comment by cmungall** [comment]
Well, we can certainly make a term in GO with a happens_during differentia. Given the age of this ticket, this seems like a reasonable next step.

However, I really think we need to make time to think about use cases for the development branch of GO and which kinds of groupings are useful, and when we need to instead make more precise terms. If this process encompasses different mechanisms then is it not better to capture at the level of those mechanisms?

**Comment by ukemi** [comment]
Or more difficult but satisfying (to me), is if we can describe the processes by how they differ other than by time..... maybe by location: yolk sac-liver-spleen-bone marrow

**Comment by pgaudet** [comment]
What's the action on this one ? @cerivs Do you want to test making a model ? 

Thanks, Pascale

**Comment by cerivs** [comment]
I don't have the time to make a model.  That is why I said someone else would need to do that work.

**Comment by ValWood** [comment]
Can this ticket be closed or is there an outstanding action item?
