### ISSUE TITLE
OTR GO:0003906_!_DNA-(apurinic_or_apyrimidinic_site)_lyase_activity parentage

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10725]
GO:0003906 ! DNA-(apurinic or apyrimidinic site) lyase activity is the term for AP endonuclease, so it should be a child of GO:0004520_!_endodeoxyribonuclease_activity

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/10535](https://sourceforge.net/p/geneontology/ontology-requests/10535)

**Comment by dosumis** [comment]
Fixed in 2013. Only left open to wait for a ref.  Now closing.
