### ISSUE TITLE
OTR: GO:0070389_!_chaperone_cofactor-dependent_protein_refolding vs GO:0051085 ! chaperone mediated protein folding requiring cofactor

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10726]
Checking to see if this is what is meant:
GO:0070389_!_chaperone_cofactor-dependent_protein_refolding 
cofactor/cochaperone stimulates refolding but is not required

GO:0051085 ! chaperone mediated protein folding requiring cofactor
cofactor/cochaperone is required to observe refolding above background

In practice, I'm not sure of examples where annotation of a chaperone or cochaperone would use this distinction, as I believe the difference is seen between classes of substrates. In cases where the co-chaperone is always required, it might be viewed as a part of the chaperone, rather than as a cochaperone.

I will ask my chaperone expert to look at this.

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/10536](https://sourceforge.net/p/geneontology/ontology-requests/10536)

**Comment by ValWood** [comment]
Hi Jim,
Is this still on your radar?

Best
Val

**Comment by pgaudet** [comment]
There are EXP annotations by 
EcoCyc @keseler 
MGI @hdrabkin 
UniProt @ggeorghiou 
RDG @slaulederkind 

Can you please check if based on your annotations these two terms are different? There are many protein families annotated to both, sounds like a merge is appropriate. 

Thanks, Pascale

**Comment by amandamackie** [comment]
EcoCyc@keseler passed this query on to me. The terms appear to have been used interchangeably in EcoCyc and so a merge would be OK for us. 

Amanda

**Comment by slaulederkind** [comment]
RGD ended up with an annotation to only the refolding term.  There is probably no practical difference between the two terms.

**Comment by ggeorghiou** [comment]
I've reviewed the annotations for CAFA and UniProt and both terms are used interchangeably. A merge is ok by me.

**Comment by pgaudet** [comment]
Looks like the distinction was between protein folding and protein **re**folding; is this important ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @jimhu-tamu
(1) I merged GO:0070389_!_chaperone_cofactor-dependent_protein_refolding 
with  GO:0051085 ! chaperone mediated protein folding requiring cofactor
but I am not sure this is what was being discussed. 
The two terms above concern protein folding and refolding. I don't know whether there should be a distinction - is folding and refolding done by separate pathways ? 


(2) What I am reading above is that there is no such thing as a co-chaperone 'pathway', so there is no way to classify chaperone versus co-chaperones. 

If this is right, then we should rather merge 
GO:0051085 chaperone cofactor-dependent protein refolding and sibling 
GO:0051086 chaperone mediated protein folding independent of cofactor
with their parent 
GO:0061077 chaperone-mediated protein folding

What do you think ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi 

it is not clear to me what changes you are making, however I hope this will mean that de-novo folding and refolding terms remain distinct. 

Thanks

Ruth
