### ISSUE TITLE
Linking targets of GO functions / modifications

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10720]
I'm working with Alan Ruttenberg to see what kinds of information we can associate with PRO. We're looking at protein modifications (phosphorylation, methylation, and so on). One route is to look at the GO functions corresponding to the modifications. An example is 'histone H3-monomethyl-K4' (GO:0034649). We understand that the proteins annotated to this term act as the catalyst, but couldn't find any links to the target of this activity (the target seems to be methylated SETD7).

I would like to request axioms that link functions corresponding to modifications like this to their targets.

Reported by: jpbona

Original Ticket: [geneontology/ontology-requests/10530](https://sourceforge.net/p/geneontology/ontology-requests/10530)

**Comment by pgaudet** [comment]
@hdrabkin as a PRO representative - do you see what the action could be here ?

**Comment by hdrabkin** [comment]
This seems more like an annotation issue; 
A phosphorylated protein would get a set a specific annotations whereas it's unphosphorylated form would not; PRO would have ids for each of the two forms.

**Comment by pgaudet** [comment]
So it looks like there's nothing to do - I'll close. 

@cmungall if we misread this please reopen. 

Thanks, Pascale
