### ISSUE TITLE
tidy up GO:0043234 protein complex and GO: 0032993 protein-DNA complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10737]
I'm getting into problems because some protein-DNA complexes were placed under protein complex so tying up new terms can become invalid when a child term has parents from each branch. I know we discussed this recently and were thinking of obsoleting protein-DNA complex (moving all terms to protein complex - with an intersection of GO:0003346 DNA binding?).

I have a specific case now where I will add 3 or 4 children to GO:0009380 excinuclease repair complex (which is_a protein complex) when TG is stable again (after the Thanksgiving holidays). They are all either GO:0097520 nucleotide-excision repair, preincision complex (which is_a protein DNA Cx) or GO:0000109 nucleotide-excision repair complex (which is_a protein Cx). 

Can we please make a decision on this fairly soon so I can bind my terms at the time of creation rather than having to go backwards again in a few months time to tidy up my terms?

Many thanks,
Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/10550](https://sourceforge.net/p/geneontology/ontology-requests/10550)

**Comment by dosumis** [comment]
What we have now: 

![image](https://cloud.githubusercontent.com/assets/112839/13296856/7255653e-db27-11e5-9524-7f33668b9142.png)

label "protein-DNA complex"^^string
definition "A macromolecular complex containing both protein and DNA molecules."
comment "Note that this term is intended to classify complexes that have DNA as one of the members of the complex, that is, the complex does not exist if DNA is not present. Protein complexes that interact with DNA e.g. transcription factor complexes should not be classified here."

label "protein complex"^^string
definition "A stable macromolecular complex composed (only) of two or more polypeptide subunits along with any covalently attached molecules (such as lipid anchors or oligosaccharide) or non-protein prosthetic groups (such as nucleotides or metal ions). Prosthetic group in this context refers to a tightly bound cofactor. The component polypeptide subunits may be identical."

All looks nice and clear to me.

@bmeldal @ValWood : Please submit a fresh ticket if any current subclasses of DNA-protein complex are now wrong.

**Comment by bmeldal** [comment]
Have you made any changes? The whole question was whether protein-DNA complex and ribonucleoprotein complex should be children of protein complex so that users searching for 'protein complex' would get all complexes. With the update of the def for protein complex the prosthetic groups are included so no logical problem.

The problematic children of GO:0009380 excinuclease repair complex have not yet been created but I guess with the whole refractoring we are going to do we wouldn't add them anyway as they only differ by composition and exactly how tightly they are bound to DNA.

Birgit
