### ISSUE TITLE
query: nucleolus organization

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10746]
Is this really a "process" or is it only a phenotype that is a consequence of problems with
rRNA processing/ ribosome biogenesis?

The gene products annotated to it (only ~24 experimental appear to be defects in these processes).

If it is a 'good' term, should it have things like:
protein localization to nucleolar rDNA repeats 
recombination within rDNA repeats 
replication fork processing at rDNA locus 
rDNA condensation 
be children?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10559](https://sourceforge.net/p/geneontology/ontology-requests/10559)

**Comment by ValWood** [comment]
reopening. I'm still not really sure that "nucleolus organization"  should be a process. Any time it is used it is just the phenotypic consequence of disorganization of the rDNA. I don't know any gene that actually 'organizes' the nucleolus.  It isn't even a independent structure really, it's  nuclear region where the rDNA is located?

**Comment by ValWood** [comment]
I am asking this becasue I don't use this term, but now I have a mapping for dnt1

GO:0007000 | nucleolus organization | IBA with S000003612 , PTN002000197 , S000001718
-- | -- | --


(a protein involved in rDNA heterochromatin assembly)

**Comment by ValWood** [comment]
Older papers talk about nucleogenesis an d the nucleolus appearing, newer papers only talk about  chromatin organization of rDNA. Does nucleogenesis inlude anything else? Otherwise we would have 2 ways to say the same thing.

(Note that  nucleolus organization still only has 36  EXP annotations)

**Comment by pgaudet** [comment]
I see 18 direct EXP annotations, by the following groups: 

(5)	FlyBase
(4)	SGD
(3)	MGI
(3)	TAIR
(3)	UniProt

Annotations are here: 
https://docs.google.com/spreadsheets/d/1I5Ef-7xFELHwVQC3a5wgjP0Fh0wSoNeq8xP9opybdMk/edit#gid=0

What do you think 
@hattrill @srengel @hdrabkin @tberardini @ccasalsc 


Thanks, Pascale

**Comment by hdrabkin** [comment]
The nucleolus is a recognizable structure; its assembly/appearance would be organization; there must be things that cause it to form; I think the term is real.

**Comment by ccasalsc** [comment]
Hi, I had a look on the annotation in which I've used this term, and in the article's discussion the authors say : ' We therefore propose that the primary role of USP36 is to regulate the transcription and processing of rRNA by deubiquitylating various proteins involved in these processes, and **the aberrant nucleolar structure in its absence is secondary to deficient ribosome biogenesis.** '
So, I don't really know if you should keep the term or not but in my case I think will remove it and keep the term 'regulation of rRNA processing'.
Best

**Comment by ValWood** [comment]
1. nucleolus organization  has children
GO:0007576    ucleolar fragmentation
The cell aging process that results in the nucleolus breaking down into fragments. PMID:9271578

I don't know how the nucleolus can 'break into fragments.'This proba bly means
fragmentation of nucleolar DNA?





GO:0000183    rDNA heterochromatin assembly

**Comment by ukemi** [comment]
I would suggest looking into the plant literature as well. ping @tberardini

**Comment by ValWood** [comment]
2. the other children are
GO:0034503    protein localization to nucleolar rDNA repeats

and
GO:0017126    JSON
nucleologenesis
Biological Process
A cellular process that results in the biosynthesis of constituent macromolecules, assembly, and arrangement of constituent parts of a nucleolus, a small, dense body one or more of which are present in the nucleus of eukaryotic cells.

so maybe it is OK. I can't figure out what could be organized other than chromatin though (at least in yeast)?

**Comment by ValWood** [comment]
If it is kept it should be a parent of
GO:0000183    rDNA heterochromatin assembly

**Comment by ValWood** [comment]
I have just never seen anything which "actively organizes the nucleolus. 

There are 36 EXP annotations. all IMP. Of course if you bugger up ribosome biogenesis or  rDNA heterochromatin  organization you bugger up the nucleolar organization, but this is just a consequence of stuffing up another process. Is the organization a 'spontaneous consequence' of the rDNA heterochromatin organization?

There is one IDA, mouse, I will take a look at that one.

**Comment by ValWood** [comment]
I guess the 'nucleolar organization covers various processes like rDNA synthsis

We suggest that fundamental differences in molecular organization of rDNA synthesis and postranscriptional processes between cycling somatic and pre-implantation embryonic cells may be in selective transport of transcription and/or processing-complexes of proteins to the nucleolar organizer regions (NOR). Mol. Reprod. Dev. 59:277-284, 2001.

Let's move
GO:0000183 rDNA heterochromatin assembly 
under here and close this for now.

It would be good to make 
"nucleolar organization" not for direct annotation to get the required specificity in case things need to be pulled apart later (and also most of the descendant processes will have additional parentage).

**Comment by ValWood** [comment]
@hdrabkin  MGI pages give an error from QuickGO.

**Comment by hdrabkin** [comment]
@ValWood ; which pages (paste link here) so I can inform

**Comment by ValWood** [comment]
@hdrabkin 
with/from links
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0007000&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants&taxonId=10090&taxonUsage=descendants

**Comment by ValWood** [comment]
I just found another lost relative

GO:1990700   nucleolar chromatin organization

Currently not related to "nucleolar organization" OR  "GO:0000183 rDNA heterochromatin assembly"

**Comment by hdrabkin** [comment]
@ValWood You mean from the alleles in the with/from field.
These are valid alleles; you should check your parser
it loads 'http://www.informatics.jax.org/accession/MGI' but no allele (http://www.informatics.jax.org/accession/MGI:2445464
Also note: MGI:2445464 is the allele id
MGI:MGI:2445464 is not

**Comment by ValWood** [comment]
It's the links from QuickGO, nothing to do with any parser of mine:

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0007000&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants&taxonId=10090&taxonUsage=descendants

is presumably using information in the GO files?

**Comment by hdrabkin** [comment]
Do any of its pages with MGI alleles work do you know? I'd contact quickgo;

**Comment by ValWood** [comment]
I have no idea. They haven't been working for a while (I noticed it last week but was too busy to report it). I  don't mind, can just Google but I thought MGI might like to get it fixed.

**Comment by tberardini** [comment]
I updated the TAIR annotations, those gps had other annotations to more relevant processes (telomere maintanance for example) and the nucleolus related ones were really just downstream phenotypes.

**Comment by ValWood** [comment]
This seems to be an example of nucleolus organization that isn't rDNA organization:
https://www.pombase.org/reference/PMID:33176152
so maybe close this (although 'nuclolar organization'could maybe 'not for direct annotation'?)

**Comment by hattrill** [comment]
I think that I would rather leave it available for direct annotation - better to be vague than wrong here. Some proteins are clearly organising at some level - recruitment, etc, but difficult to draw an exact cause and effect. 

Should GO:1990700 'nucleolar chromatin organization' be under this term?

**Comment by ValWood** [comment]
Should GO:1990700 'nucleolar chromatin organization' be under this term?

I think so....
