### ISSUE TITLE
Macromolecule biosynthetic process and x protein production

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10787]
Hello, 

"Macromolecule biosynthetic process" concerning proteins and "production" of proteins are represented quite heterogeneously in the GO. 

'GO:0009059 macromolecule biosynthetic process' has a lot of children that are actually proteins, ie, where 'biosynthesis' per se does not apply, but 'production' is more appropriate. Those are: 

GO:0032800  receptor biosynthetic process
GO:0042966  biotin carboxyl carrier protein biosynthetic process
GO:0045112  integrin biosynthetic process
GO:0045341  MHC class I biosynthetic process
GO:0045342  MHC class II biosynthetic process
GO:0048152  S100 beta biosynthetic process
GO:0048153  S100 alpha biosynthetic process
GO:0050757  thymidylate synthase biosynthetic process
GO:0051767  nitric-oxide synthase biosynthetic process
GO:0032964  collagen biosynthetic process
GO:0002378  immunoglobulin biosynthetic process

Proteins under the child term "GO:0034645 cellular macromolecule biosynthetic process" 
GO:0009101  glycoprotein biosynthetic process
GO:0042158  lipoprotein biosynthetic process
GO:0042541  hemoglobin biosynthetic process
GO:0042964  thioredoxin biosynthetic process
GO:0042965  glutaredoxin biosynthetic process
GO:0042967  acyl-carrier-protein biosynthetic process
GO:0043172  ferredoxin biosynthetic process

Then in a completely different area of the GO we have 
- GO:0044707 single-multicellular organism process
  -- GO:0001816 cytokine production 
  --- having as children, many cytokines, as well as other stuff, such as GO:0032605 hepatocyte growth factor production and GO:0090269 fibroblast growth factor production,  GO:0071604 transforming growth factor beta production (surely those are misplaced?) 

I would argue that only 'translation' results in production of proteins. So, in all cases, what we are annotating is 'regulation of x production'  - in other words, all those terms could be placed under 'GO:0023019  signal transduction involved in regulation of gene expression' (since 'gene expression' as defined by GO includes protein production). 

So I propose to do the following: 
1. for all the x biosynthetic process terms above, rename to 'regulation of x production' and move under GO:0023019     signal transduction involved in regulation of gene expression
2. Merge GO:0001816 cytokine production GO:0001817  regulation of cytokine production  
3. Fix parentage of terms under 'cytokine production', we should perhaps create a term 'regulation of growth factor production'. 

Thanks, 

Pascale

Reported by: pgaudet

Original Ticket: [geneontology/ontology-requests/10600](https://sourceforge.net/p/geneontology/ontology-requests/10600)

**Comment by cmungall** [comment]
See GOC meeting discussion: https://docs.google.com/document/d/1HjFgya5d5vL63GoU4k_M0CkOBPIe7xjzOL5_WGtUcPM/edit#

```
Cytokine production, https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0001816. Proteins annotated to cytokine production should really be annotated to ‘regulation of cytokine production’, https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0001817
David H: proposes get rid of cytokine production and retain regulation of cytokine production as a regulation of biological quality where ‘cytokine production’ refers to the measurement of levels of a cytokine.
Aleks: general pattern (e.g. apoptotic process) where there is a signalling phase and an executive phase
Judy: perhaps check with Alex Diehl (who put those terms in initially)

Action Item: move protein production (and protein secretion?) to  regulation of production’. Tickets have already been generated (follow the link above)
```

I don't think the AI is quite right. We already discussed in this ticket why 'regulation of production' is not good. I think the resolution we made at the meeting was to define as 'regulation of X levels', making use of OBA

**Comment by pgaudet** [comment]
Hi Chris, 

'regulation of X levels sounds good', as long as it doesn't limit to protein, since in some instances the mRNA may be measured. The best parent is 'regulation of gene expression, since this encompasses both mRNA and protein. 

Cheers, 
Pascale

**Comment by ukemi** [comment]
Based on the discussion here: https://github.com/geneontology/go-ontology/issues/18370
I am closing this. I think that the production classes are useful to the community.

**Comment by pgaudet** [comment]
Production yes- the question was about 'biosynthetic process' ; we still have loads of those terms.
