### ISSUE TITLE
Changes in cell adhesion ontology

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10798]
Following discussions with Dr Ruth Lovering, Dr Gabriella Ructici and Prof. Zvi Kam I would like to propose some changes/additions to the cell adhesion ontology. 

Our review of the literature and personal experience suggests that adherens junctions always contain cadherins and that junctions with integrins and not cadherins are not adherens junctions. See Figure 5 of Nature review 2004, PMID: 15170449 and also Wikipedia links for adherens junctions http://en.wikipedia.org/wiki/Adherens_junction and focal adhesions http://en.wikipedia.org/wiki/Focal_adhesion. 

We would therefore suggest that two cellular component terms muscle tendon junction and focal adhesion are moved out from GO:0005924 cell-substrate adherens junction and are instead located directly under 

GO:0030055 cell-substrate junction
> is a child GO:0005927 muscle tendon junction
> is a child GO:0005925 focal adhesion

It wasn't possible to add the milestone GOC:BHF in the appropriate box above,therefore, I put the refs in the labels boxes.

Following discussions with Dr Ruth Lovering, Dr Gabriella Ructici and Prof. Zvi Kam I would like to propose some changes/additions to the cell adhesion ontology. 

Our review of the literature and personal experience suggests that adherens junctions always contain cadherins and that junctions with integrins and not cadherins are not adherens junctions. See Figure 5 of Nature review 2004, PMID: 15170449 and also Wikipedia links for adherens junctions http://en.wikipedia.org/wiki/Adherens_junction and focal adhesions http://en.wikipedia.org/wiki/Focal_adhesion. 

We would therefore suggest that two cellular component terms muscle tendon junction and focal adhesion are moved out from GO:0005924 cell-substrate adherens junction and are instead located directly under 

GO:0030055 cell-substrate junction
> is a child GO:0005927 muscle tendon junction
> is a child GO:0005925 focal adhesion

In addition this parent should also be listed for the new term suggested proteolytic and adhesive cell projection as a parent of podosome and invadopodia (more information about the request for this new term is provided below) and the new term: sealing zone adhesion.

GO:0030055 cell-substrate junction
> is a child new term proteolytic and adhesive cell projection
>> is a child GO:0002102 podosome
>> is a child GO:0071437 invadopodium 
> is a child new term: sealing zone adhesion

Obviously this would mean that the definition of GO:0005912 adherens junction would need revising to:
‘A cell junction at which cadherin anchoring proteins extend through the plasma membrane and are attached to actin filaments’.

If you disagree with this and feel that integrin containing junctions are adherens junctions then please place the new GO term: is a child new term proteolytic and adhesive cell projection as an is_a child to GO:0005924 cell-substrate adherens junction, so that it is a sibling to GO:0005925 focal adhesion.

In regards to podosome and invadopodia: 
A)  The reason I am requesting a new term proteolytic and adhesive cell projection as a parent term of the siblings invadopodium and podosome is that there is some confusion in the literature on the definitions of podosome and invadopodium: 
Copying from Hoshido D et al., J. Cell Sci 126 (2013), PMID:23843616, which is the most recent review on the subject: ‘Actin-based subcellular structures termed invadopodia or podosomes are now well-characterized as a specialized machinery for ECM degradation (Linder et al., 2011; Weaver, 2006). The term invadopodium is generally used to describe structures formed in cancer cells, whereas podosome is the term used for similar structures that are involved in matrix remodeling in non-cancerous cells, including dendritic cells, macrophages, endothelial cells, vascular smooth muscle cells (VSMCs) and osteoclasts (Burns et al., 2001; Gaidano et al., 1990; Hai et al., 2002; Kanehisa et al., 1990; Marchisio et al., 1987; Miyauchi et al., 1990; Moreau et al., 2003)’. 

However, this is not a clear-cut rule that all researchers follow.  Copying from a different part of the paper: 
‘the term invadosomes has been recently used to encompass both types of structures, as well as similar structures that are induced in normal cells by transformation with constitutively active mutant forms of the nonreceptor tyrosine kinase Src’... 

In the review (PMID:23843616) these structures are compared between cancer cells (where they are regarded as invadosomes) and in normal cells where they are regarded as podosomes). It seems that the assembly of these structures is quite different in cancer and normal cells, (see Figure 1 of paper), however, the primary structure of both is highly similar. Highly similar, doesn’t necessarily mean identical, though, and the definition of the differences between them, not only in structure but also in how they are regulated, is the subject of very active research.
That said, I would propose to keep the two terms in the ontology, keeping the cancer-non cancer cell as the main distinction between them for the moment. However, I think the parent term proteolytic and adhesive cell projection (or any equivalent, as a general term to group together invadopodia and podosome) might be also useful to have at this point of confusion, to accommodate for some papers where the term invadopodium is used in both cancer and non-cancer cells.

B) I would propose to enrich the existing definition of invadopodium:‘A cell projection that emerges from the ECM-facing surface of a cell, is enriched in actin and associated cytoskeletal proteins, and displays localized proteolytic activity toward the substrate’ as follows:
Elongated, actin-rich structures that are present at the basal surfaces of certain cells capable of crossing extracellular barriers, such as invasive cancer cells. Invadopodia form ventral projections into the underlying extracellular matrix (ECM), where their primary function appears to be the focal degradation of the ECM through the secretion of matrix metalloproteinases (MMPs). Sometimes the term invadopodium is used interchangeably with the term ‘podosome’. (Definition was adapted from www.mechanobio.info and the link to ‘podosome’ was incorporated). 

C) I would add the following sentence to the existing definition of podosome: ‘Sometimes the term ‘podosome’ is used interchangeably with the term ‘invadopodium. 

D) In addition there needs to be consistency in the parentage of GO:0002102 podosome and GO:0071437 invadopodium. At the moment this is not the case, podosome is a child of cytoskeleton, which is wrong.

To sum up:
Suggested GO ontology:

> GO:0030055 cell-substrate junction
Definition: A cell junction that forms a connection between a cell and the extracellular matrix.

>> is_a: Focal adhesion (GO:0005925)
Definition: Small region on the surface of a cell that anchors the cell to the extracellular matrix and that forms a point of termination of actin filaments

>>is_a new term: focal complex
Definition: A small, dot-like adhesion structure that anchors the cell to the extracellular matrix and can develop into a focal adhesion. It is primarily located at the cell’s leading edge, along lamellipodial structures. (PMID: 21441590).

>> is_a new term: fibrillar adhesion
Definition: An adhesion structure that anchors the cell to the extracellular matrix, believed to evolve from mature focal adhesions. It is composed of thin actin cables that are crosslinked by the actin-binding protein tensin.  It is located near focal adhesions, but more towards the cell centre, where it binds specifically to extracellular fibronectin fibrils via integrins. (Info gathered from PMID: 21441590 and www.mechanobio.info).

>> is_a: podosome  GO:0002102,currently child of cytoskeletal part: GO:0044430

>> is_an: invadopodium GO:0071437, currently child of GO:0042995 cell projection

>> is_a new term: sealing zone adhesion
Definition: In osteoclasts, podosomes become organized into a belt-like structure (sealing zone) enriched in f-actin that forms the attachment of an osteoclast to the underlying bone and ensures limited diffusion to other cells of enzymes secreted by the osteoclast, as part of the process of bone resorption.  

In addition to GOC:BHF, all of these new terms should include the dbxrefs: GOC:rl, GOC:ame

Reported by: amelidon

Original Ticket: [geneontology/ontology-requests/10611](https://sourceforge.net/p/geneontology/ontology-requests/10611)

**Comment by paolaroncaglia** [comment]
@RLovering 

Hi Ruth,

This was an old request from Anna Melidoni, that came in before we switched from SourceForge to GitHub.
Could you please review the original request and let me know if those edits and new terms are still needed.
(I confirm that no ontology work was done in this area recently, as far as I can see.)
If yes, could you please provide a reference to support the request to move ‘muscle tendon junction’ from under GO:0005924 ‘cell-substrate adherens junction’ to GO:0030055 ‘cell-substrate junction’ (I guess a paper showing that they contain integrins and not cadherins?).

Many thanks,

Paola

**Comment by paolaroncaglia** [comment]
Closing as, presumably, out of date.
