### ISSUE TITLE
TPV: mei2 nuclear dot, parentage fix

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10815]
The Mei2 nuclear do has a parent "nucleoplasm"

It is in fact chromosome/chromatin associated.

Can this be changed?

Thanks

Val

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0033620#term=ancchart

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10628](https://sourceforge.net/p/geneontology/ontology-requests/10628)

**Comment by ValWood** [comment]
Looks OK to me?
