### ISSUE TITLE
Cellular component terms for Giardia

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10828]
This ontology project stems from a request by Michael Cipriano (Scott Dawson's lab at UC Davis). New GO CC terms are needed to represent protein localization in Giardia lamblia and related species. Omar Harb and Nicholas Stover also agreed to help. We will work with the experts to make the new terms applicable to as many species as possible, and we'll add taxon constraints otherwise. 

I'm attaching the list of terms that Michael sent us originally. I'm emailing the experts directly with questions and comments, but I'd like there to be a reference to this work in SourceForge too, to make everyone aware and in case other curators wish to give feedback. Some terms look very specific with 'spatial' constraints. We've discussed this among editors and agreed to include the terms more or less as they are, provided that they're not redundant with existing terms (including recent ontology work on cilial/flagellar CC terms). 

I'll post the new GO IDs and names here when they become available.

Cheers,
Paola

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/10642](https://sourceforge.net/p/geneontology/ontology-requests/10642)

**Comment by paolaroncaglia** [comment]
Added 
id: GO:1990900
name: ciliary pocket collar

And emailed Scott Dawson and Michael Cipriano about 1) JBMS paper 2) annotation plans.

**Comment by paolaroncaglia** [comment]
Also, attaching initial file for reference (contains initial list of terms requested, but I keep a working copy with comments added along the project).
[GiardiaGoTerms_SCDrefs.docx](https://github.com/geneontology/go-ontology/files/36849/GiardiaGoTerms_SCDrefs.docx)

**Comment by paolaroncaglia** [comment]
(Old Jira ticket was at https://www.ebi.ac.uk/panda/jira/browse/GO-198, now closed.)

**Comment by paolaroncaglia** [comment]
Reviewed entire document. Terms left to add:

- For all 8 flagella (but see discussion in GiardiaGoTerms_PR_310516.doc, and updated defs. of existing ciliary terms):
axoneme transition zone
cytoplasmic axoneme 
membrane-bound axoneme
flagellar pore 

- left/right caudal axoneme microtubule root

- caudal complex / funis 

- marginal plate, with 2 children

- striated fibers, with 2 children

- marginal groove 

- ventrolateral flange 

- ventral groove 

- peripheral vesicles 

-  bare area vesicles 

-  encystation specific vesicles 

- fimbrae.

Once done, the ontology work is completed, and this ticket can be closed.

**Comment by paolaroncaglia** [comment]
Note for self: I’m going to have to leave this for now, and hopefully come back to it sometime in the near future if/when publication plans are finalised. But it makes more sense to leave it assigned to me.

**Comment by pgaudet** [comment]
Is there still a contact person for this project ? There are no references for the new terms requested. 

- Pascale

**Comment by krchristie** [comment]
@paolaroncaglia - We're trying to close tickets this week so I was wondering if this ticket is completed and could be closed.

**Comment by paolaroncaglia** [comment]
Hi,

I am on leave today and tomorrow, I will reply when I am back. Thanks.

Paola

**Comment by paolaroncaglia** [comment]
@krchristie 
This ticket is not completed, but it won't be possible to address it in the near future. So I made a note for myself somewhere else, and I'm closing this now. Thanks.

**Comment by pgaudet** [comment]
I am not sure we should close tickets that are not finished. We can put a status = pending - 
what do you think ? and @ukemi @vanaukenk ...?

**Comment by paolaroncaglia** [comment]
@pgaudet et al
'pending' would be great thanks, in fact that's the label that this ticket had until half an hour ago ;-)

**Comment by ukemi** [comment]
We shouldn't close tickets that are not finished unless the ticket has drifted so much that it would make more sense to open one or more new tickets. In that case, the existing ticket can be closed and new ones opened that all refer to one another.

**Comment by krchristie** [comment]
@paolaroncaglia - Thanks for checking on this ticket. Since the consensus is to leave tickets open unless they are done or out-of-date, I've reopened this to save you needing to come back.

**Comment by paolaroncaglia** [comment]
Thanks @krchristie .

**Comment by ValWood** [comment]
If nobody is actively curating Giardia doesn't it make sense to close this ticket, and be led by the community if and when they require the terms?

**Comment by ValWood** [comment]
I'm closing it. It's too long to read... start afresh, no point to add terms imagining that people will use them when people are waiting for terms to use.
