### ISSUE TITLE
mononuclear term parent

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10840]
Hi

please add the following is_a parent relationship 
 GO:0071674 mononuclear cell migration
 >is_a child GO:0002548 monocyte chemotaxis

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/10654](https://sourceforge.net/p/geneontology/ontology-requests/10654)

**Comment by dosumis** [comment]
@RLovering  - This one slipped through the cracks.  Do you have a ref for classification of monocyte as 'mononuclear cell' ? Looks like it should be from def + wikipedia (see linked CL ticket).  Checking with Alex first to see if OK.

**Comment by addiehl** [comment]
CL is now fixed so that monocyte is inferred to be type of mononuclear cell.

**Comment by dosumis** [comment]
Have checked that we have sufficient axiomatisation in place for requested classification to be inferred.  We appear in GO with a week of next CL release.
