### ISSUE TITLE
redundant cell cycle relations to remove

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10857]
redundant relation to remove
mitotic cytokinetic cell separation
mitotic cytokinetic process
mitotic actomyosin contractile ring contraction
mitotic actomyosin contractile ring localization
mitotic actomyosin contractile ring maintenance
assembly of actomyosin apparatus involved in mitotic cytokinesis
remove redundant part_of to mitotic cell cyle (has mitotic cytokinesis)

mitotic chromosome decondensation
(has parentage vma  mitotic sister chromatid segregation)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10671](https://sourceforge.net/p/geneontology/ontology-requests/10671)

**Comment by ValWood** [comment]
Should this be moved to a more appropriate tracer?
Or is it already done?
Val

**Comment by ValWood** [comment]
I don't think I put enough information in this ticket about  what the problem is. I'll open a new tickdet if I figure it out
