### ISSUE TITLE
Taxon Constraint: Bone-related terms in Drosophila

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10876]
Hi,

Could you please put a never_in taxon constraint on bone-related terms for D.mel/Drosophila/Insecta?

I've tried to list terms that are parent terms or isolated child terms, but there may well be some redundancy. 

Thanks

GO:0046849 bone remodeling
GO:0060348 bone development
GO:0048705 skeletal system morphogenesis
GO:0030282 bone mineralization
GO:0001503 ossification
GO:0008147 structural constituent of bone
GO:0071839 apoptotic process in bone marrow
GO:0097241 hematopoietic stem cell migration to bone marrow
GO:1901706 mesenchymal cell differentiation involved in bone development
GO:0003433 chondrocyte development involved in endochondral bone morphogenesis
GO:0035602 fibroblast growth factor receptor signaling pathway involved in negative regulation of apoptotic process in bone marrow
GO:0035604 fibroblast growth factor receptor signaling pathway involved in positive regulation of cell proliferation in bone marrow
GO:0060351 cartilage development involved in endochondral bone morphogenesis
GO:0061592 phosphatidylserine exposure on osteoblast involved in bone mineralization
GO:1900220 semaphorin-plexin signaling pathway involved in bone trabecula morphogenesis

Reported by: hattrill

Original Ticket: [geneontology/ontology-requests/10690](https://sourceforge.net/p/geneontology/ontology-requests/10690)

**Comment by dosumis** [comment]
Import of taxon constraints from Uberon (pending) will fix this.
