### ISSUE TITLE
GO:0080008 Cul4-RING ubiquitin ligase complex and children, update term/def

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10881]
Could E3 be added to 
GO:0080008 Cul4-RING ubiquitin ligase complex
and its children?

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10695](https://sourceforge.net/p/geneontology/ontology-requests/10695)

**Comment by dosumis** [comment]
Fixed ages ago, but ticket never closed.  Closing now.
