### ISSUE TITLE
relationship for subsections of CC term chromatin, etc.

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10889]
Hi,

I am annotating some genes to the component term (colocalizes with) "nuclear chromatin". I would like to indicate a specific kind of region within nuclear chromatin, specificlly RNA polymerase III promoters, with a SO term: "RNApol_III_promoter  ; SO:0000171"

I am already using the colocalizes qualifier since the experiment is a ChIP, but I don't see what existing relationship I could use in order to include a SO term to describe the specific types of regions within the chromatin. 

-Karen

Note: We discussed this at the annotation call on 3/11/14, and the ontology development group is going to discuss further how to handle this type of situation.

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/10703](https://sourceforge.net/p/geneontology/ontology-requests/10703)

**Comment by dosumis** [comment]
@krchristie

Fixed at the time, but neglected to close ticket Please annotate to:

 chromatin 'coincident with' RNApol_III_promoter ; SO:0000171
