### ISSUE TITLE
GO:0005201 extracellular matrix structural constituent - component?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10895]
Hi,

shouldn't GO:0005201 extracellular matrix structural constituent be a cellular component???
Maybe I got it wrong but it sounds like the description of a structure, not an activity (except for one of the child terms that has activity in it...)

Thanks,
Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/10709](https://sourceforge.net/p/geneontology/ontology-requests/10709)

**Comment by dosumis** [comment]
My suggested fix would require a policy change in GO to allow nested class expressions.  Some alterations to the pipeline would also be required as the resulting axioms could not be expressed in OBO - should probably live in separate, imported, edited OWL file.

**Comment by cmungall** [comment]
How does this relate to the regulation-of-biological-quality hierarchy?

or to the mf refactor. E.g. mechanistically, this is a structural constituent. The function is to increase or decrease the magnitude of some property such as tensile strength of collagen fibrils (which is itself causally linked to increasing the strength of bone and skeletal structures)

**Comment by dosumis** [comment]
Alternative pattern:

'fu structural constituent activity'
EquivalentTo: 'structural molecule activity' that part_of some 'maintenance of fu organization'

**Comment by dosumis** [comment]
> How does this relate to the regulation-of-biological-quality hierarchy?

> or to the mf refactor. E.g. mechanistically, this is a structural constituent. The function is to increase or decrease the magnitude of some property such as tensile strength of collagen fibrils (which is itself causally linked to increasing the strength of bone and skeletal structures)

> E.g. structural molecule activity and positively regulates some OBA:class

Agree that this would allow us to add without introducing nested class expressions.  Looks like the best way to fix (once we've agreed on a general pattern).

**Comment by dosumis** [comment]
Pattern summary (text def follows current pattern from ontology):

> 'fu structural constituent'
> def: "The action of a molecule that contributes to the structural integrity of a fu."
> exact_synonym: 'structural molecule activity involved in 'maintenance of fu organization
> EquivalentTo: 'structural molecule activity' that part_of some 'maintenance of fu organization'

This has the great advantage that it levers the partonomy under 'maintenance of fu' to automate classification.  Unfortunately, this partonomy is currently manually managed (could potentially be fixed with GCIs).  It is also hard to specify a DOSDP for this.  The var slot has to be the maintenance term rather than the CC term.  This means that some reg-ex would be required to derive the label and definition.  Not ideal.  Again, would be solved easily if nested class expressions allowed - as we could then use the maintenance pattern to refer to the maintenance term anonymous via the CC.

Despite these limitations, I have implemented this pattern for synapse terms.   The number of terms is relatively small so a design pattern spec not essential I think.

**Comment by dosumis** [comment]
CC (pre GitHub commenters): @mah11 @ValWood @bmeldal @paolaroncaglia

**Comment by mah11** [comment]
I haven't changed my mind; I still think any term that has an is_a path to GO:0005198 and incorporates a GO CC or anatomical term in its name or definition should eventually become obsolete.

Interesting to see the discussion of various aspects of moving the CC/anatomy info to extensions, tho.

**Comment by dosumis** [comment]
@mah11: So you suggestion is that MFs shouldn't be tied to anatomy or CC except via extensions (or LEGO)?

In this case, the terms seem pragmatically useful to me: We need a way to record when proteins play a structural role in CCs (and perhaps in some types of anatomy, like bone or eggshell).  For example, there are many gene products that play important structural roles in post-synaptic densities - they are present in the PSD and without them the PSD falls apart or is malformed. I don't think we have anything in the BP branch that works for this: maintenance, assembly, organisation are too broad.   We could shift the link to CC into an extension or split it out in LEGO, but I worry this would obscure the meaning for many users, and fail to provide a means for semantically clear enrichment/annotation grouping to replace terms like 'structural constituent of PSD'.

**Comment by mah11** [comment]
> So your suggestion is that MFs shouldn't be tied to anatomy or CC except via extensions (or LEGO)?

Yes; that's consistent with the definition in the ontology as well as the description in GO's documentation.

**Comment by dosumis** [comment]
>> So your suggestion is that MFs shouldn't be tied to anatomy or CC except via extensions (or LEGO)?

> Yes; that's consistent with the definition in the ontology as well as the description in GO's documentation.

Does this objection apply to all MF involved in BP links or only to BPs that are further defined wrt some CC?

**Comment by mah11** [comment]
I have always thought that the BP-specific MF terms sit a bit awkwardly given the way GO defines MF (what's happening at the level otherwise associated with the MF scope is the same in any BP context), but I've made my peace with the arrangement. I don't think that has anything to do with the CC- or anatomy-specific "structural constituent" MFs, though.

**Comment by pgaudet** [comment]
@ukemi @rachhuntley 
Did you guys look at this during the ECM re-organization? 

Can this be closed, or an action be decided ?

Thanks, Pascale

**Comment by ukemi** [comment]
This isn't really in the scope of what we are doing. We are looking at the components, not the activities. This is a more general issue as to whether there is a molecular function that corresponds to providing structure for something. We have always included it as an MF, but that doesn't mean we couldn't change.

**Comment by pgaudet** [comment]
OK - but there is no reason to change now ? 

Close ?

**Comment by rachhuntley** [comment]
Having skimmed the discussions, I'm not still not sure if an actual plan was laid out. In the case of the ECM terms, e.g. ' extracellular matrix structural constituent conferring tensile strength ', I have no strong feelings whether they sould be CC or MF, but I would not want them to be obsoleted as I am using them to categorise ECM components from HTP experiments in combination with the categorisation used by the Matrisome project.

**Comment by ukemi** [comment]
@rachhuntley . I'm tempted to close since some confer tensile strength and some confer elasticity. If I recall correctly these two 'functions' can have different health-related consequences when disrupted.

**Comment by rachhuntley** [comment]
Yes, I'm happy with that!
