### ISSUE TITLE
parentage?: "axoneme" & "axoneme part"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10901]
Hi,

I am looking at the terms "axoneme" and "axoneme part", both of which are shown as is_a "cytoplasmic part" as well as is_a "ciliary part".

I think that is_a "cytoplasmic part" is wrong because the cilium is a membrane organelle that is separated from the cytoplasm by a membrane that contains nuclear pore complexes, so the cilium is separated from cytoplasm and there is not free diffusion between the two (other than for small molecules) similarly to the separation between the cytoplasm and the nucleus.

thanks,

-Karen

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/10715](https://sourceforge.net/p/geneontology/ontology-requests/10715)

**Comment by paolaroncaglia** [comment]
@krchristie

This is fixed now. We un-linked the ciliary plasm from cytoplasm, and I deleted remnant links between axonemal terms and cytoplasmic ones.
