### ISSUE TITLE
Taxon rule for 'gap junction' terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10926]
Gap junction are only found in animals
(see http://en.wikipedia.org/wiki/Gap_junction).
Therefore, the following terms should have a taxon constraint 'only in Metazoa':

GO:0005921 gap junction

GO:0016264 gap junction assembly

GO:0005243 gap junction channel activity
and children

Presumably this one too:
GO:0014704 intercalated disc ("A complex cell-cell junction at which myofibrils terminate in cardiomyocytes; mediates mechanical and electrochemical integration between individual cardiomyocytes. The intercalated disc contains regions of tight mechanical attachment (fasciae adherentes and desmosomes) and electrical coupling (gap junctions) between adjacent cells.")

If a cellular component has a taxon constraint, you'd wish that functions and processes that have a logical definition pointing to that component automatically inherit the same constraint. E.g. 'gap junction assembly' results_in_assembly_of 'gap junction' where 'gap junction' is only_in Metazoa. Or can we think of cases where we wouldn't want that to be inferred? If not, will taxon rules be propagated over relationships other than is_a and part_of once we include taxon rules in the editors file?

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/10740](https://sourceforge.net/p/geneontology/ontology-requests/10740)

**Comment by paolaroncaglia** [comment]
I have reviewed this thread, and will summarise below the necessary edits. More work could be done on ‘gap junction channel/hemichannel activity’ terms, given more resources, but for now, these edits will do:

Edit def of GO:0005921 gap junction, from
“A cell-cell junction that is composed of an array of small channels that permit small molecules to pass from one cell to another. At gap junctions, the membranes of two adjacent cells are separated by a uniform narrow gap of about 2-4 nm that is spanned by channel-forming proteins called connexins, which form hexagonal tubes called connexons.”
to 
“A cell-cell junction composed of pannexins and connexins, two different families of channel-forming proteins.”;
Add dbxref PMID: 22366062, http://en.wikipedia.org/wiki/Gap_junction;
Add taxon constraint 'only in Eumetazoa’.

Rename ‘connexon complex’ as ‘connexin complex’; keep ‘connexon complex’ as a related synonym; add exact synonym ‘connexon’ (add dbxref GOC:cjm).

**Comment by hattrill** [comment]
Can you crowbar innexins in: e.g. pannexins or innexins

Thanks,

Helen

**Comment by paolaroncaglia** [comment]
Hi @hattrill ,
Sure, I updated my suggested definition in my previous comments. Thanks.

**Comment by paolaroncaglia** [comment]
All done.
