### ISSUE TITLE
flocculation and adhesion

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10958]
I know  there is some history here, but I cannot remember why flocculation cannot be a child of cell-cell adhesion (and I can't locate the old tickets due to the SF search issues).

But based on current defs, it really seems as though it could/should be?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10773](https://sourceforge.net/p/geneontology/ontology-requests/10773)

**Comment by ValWood** [comment]
I still don't understand   why sexual flocculation can't be under cell-cell adhesion.

In fungi  agglutination and flocculation are the same mechanism...they are performed by related  cell surface  glycoprotein/adhesion molecules). The only thing that distinguishes them is which processes they occur during....

**Comment by dosumis** [comment]
> I still don't understand why sexual flocculation can't be under cell-cell adhesion.

'agglutination involved in conjugation' is under 'cell-cell adhesion' (see above). Wouldn't it be sufficient to add sexual flocculation as a synonym of this?

Also TODO:  warn curators that the vast majority of annotation under cell-cell adhesion needs to be moved under 'cell-cell adhesion via plasma-membrane adhesion molecules.  This is mechanistically unrelated to adhesion between cell walls.

**Comment by ValWood** [comment]
OK got it. sounds ok to me.

**Comment by dosumis** [comment]
annotation ticket is here: https://github.com/geneontology/go-annotation/issues/1526
