### ISSUE TITLE
TPV (via Matrix project) folic-acid containing compound biosynthetic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10983]
folic-acid containing compound biosynthetic process

is a  descendent of 
 GO:0008652 cellular amino acid biosynthetic process

...looks wrong?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10798](https://sourceforge.net/p/geneontology/ontology-requests/10798)

**Comment by dosumis** [comment]
@ValWood  Fixed some time ago, but ticket got lost on SF.
