### ISSUE TITLE
OTR+NTR: CRISPR biology and GO:0043571 ! maintenance of CRISPR repeat elements

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10994]
GO:0043571 ! maintenance of CRISPR repeat elements is defined as:
"Any process involved in sustaining CRISPR repeat clusters, including capture of new spacer elements, expansion or contraction of clusters, propagation of the leader sequence and repeat clusters within a genome, transfer of repeat clusters and CRISPR-associated (cas) genes to new genomes, transcription of the CRISPR repeat arrays into RNA and processing, and interaction of CRISPR/cas loci with the host genome. CRISPR (clustered regularly interspaced short palindromic repeat) elements are a family of sequence elements containing multiple direct repeats of 24-48 bp with weak dyad symmetry which are separated by regularly sized nonrepetitive spacer sequences."

It's an is_a child of GO:0043570 ! maintenance of DNA repeat elements.

This term strikes me as an overly broad umbrella for all of CRISPR-cas biology. At the same time, it's missing the key activity of the CRISPR systems in host defense. The reference provided in the notes doesn't give a good overview of the biology.

PMID: 23495939 is an Annual Reviews article, which breaks CRISPR biology into three types of potential process terms:
- CRISPR adaptation (i.e., new spacer acquisition), is_a GO:0006259 ! DNA metabolic process. I don't think it should be an is_a of GO:0043570 ! maintenance of DNA repeat elements. The key step is the capture of new unique sequences within the repeat array.
- CRISPR-associ
- crRNA biogenesis, (transcription and RNA processing) is_a GO:0006396 ! RNA processing
- crRNA-guided target nucleic acid inactivation
  - crRNA-guided target DNA inactivation
  - crRNA-guided target RNA inactivation

IIRC cells that are defective in CRISPR adaptation can still use CRISPRs to defend against invaders that match existing crRNAs

An umbrella term for the overall process of CRISPR-mediated adaptive immunity could be over all of these, the closest appropriate parent would be GO:0044355 ! clearance of foreign intracellular DNA, but this should have a parent term that includes both RNA and DNA. Otherwise, it would be a child of GO:0006952 ! defense response. From the review, some CRISPR mediated host defense systems work against DNA and RNA (see above)

In addition to process terms, there should probably also be component terms:
- CRISPR-associated complex for antiviral defense is_a GO:0030529 ! ribonucleoprotein complex
  - CRISPR-associated complex for antiviral defense, Type I (Cascade)
  - CRISPR-associated complex for antiviral defense, Type II
  - CRISPR-associated complex for antiviral defense, Type III

One or more activity terms may also be needed.

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/10809](https://sourceforge.net/p/geneontology/ontology-requests/10809)

**Comment by dosumis** [comment]
Added:

rdfs:label "CRISPR-cas system"
has_obo_namespace "biological_process"
definition "An adaptive immune response of bacteria that serves to clear host cells of foreign DNA and RNA.  It has three distinct stage: acquisition of foreign DNA by integration into CRISPR loci in the host chromosome; CRISPR RNA (crRNA) biogenesis; and target interference.  CRISPR stands for Clustered Regularly Interspaced Short Palindromic Repeat, which describes the nature of the loci." [PMID:23495939]
SubClassOf: 'clearance of foreign intracellular nucleic acids'

**Comment by jrr-cpt** [comment]
With the expanding characterization of anti-CRISPR proteins, additional function terms to describe negative regulation of __________(CRISPR/Cas type) are needed. While we do not yet have terms that reflect the fact that there are at least six different CRISPR Types, the specific defenses against each type are encoded by a wide variety of phage-encoded anti-CRISPR proteins. Recent review here: 28749735


Additionally, CRISPR systems themselves can be completely encoded by bacteriophage, PMID:     [23446421](https://www.ncbi.nlm.nih.gov/pubmed/23446421). Other examples of partial systems can be identified in phage genomes PMID: [27302758](https://www.ncbi.nlm.nih.gov/pubmed/27302758) and [29440578](https://www.ncbi.nlm.nih.gov/pubmed/29440578). A new term allowing for phage-encoded CRISPR/Cas as a defense against host might be in order.

**Comment by pgaudet** [comment]
Thanks @jrr-cpt 
Can you please provide: 

- names of terms you would like to see
- definitions
- I assume the review you cite  (PMID:28749735) would be correct for these terms ? 

Thanks, Pascale

**Comment by raymond91125** [comment]
Current hierarchy
![image](https://user-images.githubusercontent.com/619520/126821368-a8679170-548b-4c54-8203-32e311bef3ec.png)

**Comment by pgaudet** [comment]
How about this: 

- [ ] add PMID:28749735 "The Discovery, Mechanisms, and Evolutionary Impact of Anti-CRISPRs ", as a reference to 'inhibition of host CRISPR-cas system by virus' 
- [ ] For phage CRISPR-cas: PMID: 27302758 and 29440578 - either we need a new term, or we need to adjust the definition of the current GO:0099048  CRISPR-cas system term, which is "An adaptive immune response of bacteria that serves to clear host cells of foreign DNA and RNA. It has three distinct stage: acquisition of foreign DNA by integration into CRISPR loci in the host chromosome, CRISPR RNA (crRNA) biogenesis, and target interference. CISPR stands for Clustered Regularly Interspaced Short Palindromic Repeat, which describes the nature of the loci. "

- this has 2 problems: 
- 1. Is this really an 'adaptive immune response', in the GO sense? 
- 2. Can we remove the reference to bacteria? the defnition would be "An ~adaptive immune~defense response ~of bacteria~ that serves to clear host cells of foreign DNA and RNA. It has three distinct stage: acquisition of foreign DNA by integration into CRISPR loci in the host chromosome, CRISPR RNA (crRNA) biogenesis, and target interference. CISPR stands for Clustered Regularly Interspaced Short Palindromic Repeat, which describes the nature of the loci. 


@dsiegele Would that work? 

Thanks, Pascale
