### ISSUE TITLE
OTR: translation initiation factor activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11011]
Hi,

Is this really a molecular function?- http://amigo.geneontology.org/amigo/term/GO:0003743

Rama

Reported by: rbalakri

Original Ticket: [geneontology/ontology-requests/10826](https://sourceforge.net/p/geneontology/ontology-requests/10826)

**Comment by ValWood** [comment]
Out of date. I still think these are 'factors'  which implies that we don't  know their precise function, and they are 'factors' involved in a process ( excepting 'DNA-binding transcription factor' which has evolved a more precise definoition) but we have them now.

but way out of date.....
