### ISSUE TITLE
Taxon rules for several terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11025]
Request taxon constraint for:
GO:000865 lipopolysaccharide metabolic process
GO:0008917 lipopolysaccharide N-acetylglucosaminyltransferase activity
GO:0009103 lipopolysaccharide biosynthetic process
GO:0008919 lipopolysaccharide glucosyltransferase I activity
GO:0047270 lipopolysaccharide glucosyltransferase II activity
only occurs in Gram negative bacteria; the terms have been assigned to non-bacterial species because of the similarity to the name of the enzyme e.g. it has been assigned to human  UniProtKB:C9IYY0 which is Lactosylceramide 1,3-N-acetyl-beta-D-glucosaminyltransferase 

GO:0060157 urinary bladder development
GO:0014832 urinary bladder smooth muscle contraction  
does not occur in birds excepting ostrich and rhea

GO:0060067 cervix development 
does not occur in birds; this term refers to the cervix of the female reproductive system, not the cervical vertebrae. The term has been incorrectly assigned to proteins of birds. 

GO:0001740 Barr body 
definition states "A structure found in a female mammalian cell..." Barr body is also found in non-mammalian cells.

Reported by: mikerice7

Original Ticket: [geneontology/ontology-requests/10840](https://sourceforge.net/p/geneontology/ontology-requests/10840)

**Comment by cmungall** [comment]
Additional note: urinary bladder development was previously never-in Aves. I changed to

```
relationship: never_in_taxon NCBITaxon:8825 {id="GOTAX:0010073"} ! Neognathae
```

**Comment by cmungall** [comment]
Ignore this. I think I misunderstood the discussion. Reverting back to the more reestricted statement

**Comment by rachhuntley** [comment]
Presumably if there is a taxon constraint never_in_taxon Aves on the urinary bladder terms, there should also be the same constraint on any 'urine' terms?
This would address this help request http://jira.geneontology.org/browse/GO-411?filter=10101

**Comment by paolaroncaglia** [comment]
Hi Rachael,

I re-read the thread here https://github.com/obophenotype/uberon/issues/454 and it's not entirely clear to me that all and any 'urine' terms should be restricted to never_in_Aves. In UBERON, 'urine' is defined as:

"Excretion that is the output of a kidney" 

and has this note:

"taxon_notes: kidney excreta from some taxa (e.g. in aves) may not be liquid"

(http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/UBERON_0001088)

So I'd say that the answer to your question is no. Chris, would you agree? @cmungall 
(Rachael, once we reach a resolution, could you please update and close that help request, or let me know if you'd like me to do it, thanks!)

Thanks both,
Paola

**Comment by paolaroncaglia** [comment]
Aleksandra just pointed out that you can't measure the volume of urine in birds as it is 'mixed' (sorry, sounds gross but it's biology ;-)), so I'm having second thoughts about that taxon constraint. David Hill, could you please comment from the kidney work point of view? Thanks!

@ukemi

**Comment by cmungall** [comment]
We may be getting hung up on the terminology; if you look at the GO def:

```
def: "Any process that modulates the amount of urine excreted from the body over a unit of time." [GOC:mtg_25march11, GOC:yaf]
```

measuring the volume of the urine may be the standard assay but we're not representing the assay in GO. The core thing we should be representing should be the physiology, and the question should be about whether that physiological process is conserved in different species.

**Comment by ukemi** [comment]
I'm pretty sure the term was meant to refer to liquid urine and the action of things like vasopressin controlling liquid urine volume. But as pointed out in the above comment the definition allows for any type of urine. If we consider the uric acid secreted by birds and reptiles to be urine, then the regulation of the amount they secrete would fit this term. Perhaps that is why this term is not related to micturition.

**Comment by paolaroncaglia** [comment]
Great. Thanks. I'll close this ticket again then!
(@rachhuntley 
Rachael, you'll let me know about the GO help ticket)
Paola

**Comment by rachhuntley** [comment]
Added a comment to the GO help issue and closed it :)
