### ISSUE TITLE
change parent for GO:0030509 BMP signaling pathway

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11038]
Hi

I don't think GO:0030509 BMP signaling pathway should have the parent term  GO:0006357 regulation of transcription from RNA polymerase II promoter when the definition for BPM signaling states that the pathway ends with regulation of transcription: A series of molecular signals initiated by the binding of a member of the BMP (bone morphogenetic protein) family to a receptor on the surface of a target cell, and ending with regulation of a downstream cellular process, e.g. transcription. 

There is another signaling pathway with this parent too torso signaling pathway, where as other ligand signaling pathways eg GO:0038084 vascular endothelial growth factor signaling pathway and the other receptor signaling pathways don't have this relationship. 

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/10853](https://sourceforge.net/p/geneontology/ontology-requests/10853)

**Comment by pgaudet** [comment]
@vanaukenk Whatever decision is made for the Wnt pathway should also apply here.

**Comment by pgaudet** [comment]
Done in #19366
