### ISSUE TITLE
query, where is CoQH2-cytochrome c reductase complex?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11048]
Some process terms refer to
CoQH2-cytochrome c reductase complex
electron transporter, transferring electrons from CoQH2-cytochrome c reductase complex and cytochrome c oxidase complex activity

and
electron transporter, transferring electrons within CoQH2-cytochrome c reductase complex activity 
but I cannot find this complex in GO.

I ask because a lot of mitochondrial respiratory chain complex III
are annotated to this term. Is it the same thing?

(I am trying to figure out the catalytic activity to be used with mitochondrial respiratory chain complex III and how the above differ from
ubiquinol-cytochrome-c reductase activity)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10863](https://sourceforge.net/p/geneontology/ontology-requests/10863)

**Comment by ValWood** [comment]
so
CoQH2-cytochrome c reductase complex
seems to be
mitochondrial respiratory chain complex III

**Comment by ValWood** [comment]
This answers my question
https://en.wikipedia.org/wiki/Coenzyme_Q_%E2%80%93_cytochrome_c_reductase
I just needed to be sure I was using the correct term.

Please add the terms on wikipedia as synonyms and this one can be closed. Can sweep any  other issues under the carpet for the time being.

**Comment by ValWood** [comment]
- [ ] standardize in GO on the use of one term in MF and BP

**Comment by ukemi** [comment]
Added appropriate synonyms to all terms. Did not make the term names for the function and the complex the same because it seems like the are referred to in different ways. However, a search on any of the nomenclature, should now return the correct class.
