### ISSUE TITLE
mitochondrial electron transport, child terms start and end

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11051]
I am trying to figure out where these processes  begin and end:

GO:0006123  mitochondrial electron transport, cytochrome c to oxygen  
GO:0006122  mitochondrial electron transport, ubiquinol to cytochrome c 

They sound like they were created  to single steps

complex III -> cytochrome c
cytochrome c -> complex IV
(which would make them molecular functions)

Could this be investigated and added to the defs. In either case, it isn't totally clear how to use them?

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10866](https://sourceforge.net/p/geneontology/ontology-requests/10866)

**Comment by ValWood** [comment]
closing....this isn't bothering me.
