### ISSUE TITLE
taxon rule for GO:0022601 menstrual cycle phase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11058]
GO:0022601 menstrual cycle phase
Definition: The progression of physiological phases, occurring in the endometrium during the menstrual cycle that recur at regular intervals during the reproductive years. The menstrual cycle is an ovulation cycle where the endometrium is shed if pregnancy does not occur.

Wikipedia indicates that menstrual cycles are limited to primates, elephant shrew and some bats.

I would like to add the following taxon constraints for this term:
GO:0022601 menstrual cycle phase	only_in_taxon	9443	primates
GO:0022601 menstrual cycle phase	only_in_taxon	28734	elephants shrews
GO:0022601 menstrual cycle phase	only_in_taxon	9397	Chiroptera

Thanks.

Reported by: fmccarthy

Original Ticket: [geneontology/ontology-requests/10873](https://sourceforge.net/p/geneontology/ontology-requests/10873)

**Comment by ukemi** [comment]
Looking at the ontology, it looks like the estrous cycle and menstrual cycle already have taxon restrictions. To make an only_in relation, we need to propagate up to the common parent. Only in means that is it in nothing else. So only in bats means that it is not in humans. From annotations, it looks like fish, flies and amphibians have all used the term. For now I will leave the taxon restrictions as is. If we need 'never in' tags for specific children of the current terms, please open a new ticket.
