### ISSUE TITLE
Change relation for metabolism terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11066]
This is actually multi-step
1. Define new relation in RO (cjm, DH, DOS)
2. clear TG queue and Freeze editing
3. Search and replace in editors file
4. Change TG template
5. Unfreeze

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10881](https://sourceforge.net/p/geneontology/ontology-requests/10881)

**Comment by cmungall** [comment]
Fixed with ##16910
