### ISSUE TITLE
antibody classes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11073]
Hi all,

I see that "antibody" is an exact synonym for GO:'immunoglobulin complex, circulating', which is a direct subclass of GO:'immunoglobulin complex' (for which "antibody" is not a synonym).  However, "antibody secretion" is an exact synonym for GO:'immunoglobulin secretion', "antibody production" for GO:'immunoglobulin production', "antibody biosynthesis" and "antibody biosynthetic process" for GO:'immunoglobulin biosynthetic process', but not "antibody binding" for GO:'immunoglobulin binding'.  The fact that antibody secretion, production, and biosynthesis are synonymous with immunoglobulin secretion, production, and biosynthesis, respectively, but immunoglobulin complexes aren't themselves synonymous with antibodies seems odd to me (not to mention that antibody binding isn't synonymous with immunoglobulin binding).  I actually don't a have a recommendation one way or the other other, just mainly wondering if the GO considers immunoglobulin (complex) = antibody and wanting to make sure this is all consistent.  Either way, it's very useful to have the antibody class.

Thanks!
Mike

Reported by: mbada

Original Ticket: [geneontology/ontology-requests/10888](https://sourceforge.net/p/geneontology/ontology-requests/10888)

**Comment by ValWood** [comment]
So the action here

"add antibody as narrow synonym for   immunoglobulin complex 
and this can be closed?
