### ISSUE TITLE
myofilament wrongly assumed to be restricted to striated muscle

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11078]
A believe structures commonly called 'myofilaments' are found in other muscle cell types, as well as muscle-cell-like cells such as myoepithelia, rendering this incorrect

```
[Term]
id: GO:0036379
name: myofilament
namespace: cellular_component
***def: "Any of the smallest contractile units of a myofibril (striated muscle fiber)." [Wikipedia:Myofilament]
synonym: "striated muscle filament" EXACT [GOC:bf]
is_a: GO:0044449  ! contractile fiber part
relationship: part_of GO:0030016 ! myofibril
```

Also, the parent is incorrect:

```
[Term]
id: GO:0043292
name: contractile fiber
namespace: cellular_component
def: "Fibers, composed of actin, myosin, and associated proteins, found in cells of smooth or striated muscle." [GOC:go_curators, ISBN:0815316194]
synonym: "contractile fibre" EXACT []
synonym: "muscle fiber" BROAD []
synonym: "muscle fibre" BROAD []
is_a: GO:0043232  ! intracellular non-membrane-bounded organelle
is_a: GO:0044444  ! cytoplasmic part
****relationship: part_of CL:0000737 ! striated muscle cell
```

Should be broadened. If we include myoepithelia, beyond even muscle cells

Assigned to DOS as this seemed in your area

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10893](https://sourceforge.net/p/geneontology/ontology-requests/10893)

**Comment by pgaudet** [comment]
Related to #10399

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0036379
looks OK, closing. Reopen if still an issue.
This is from 2014,  submitter not obvious and no assignee.
