### ISSUE TITLE
regulation classes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11085]
Hi there,

I'd like to request some high-level regulation classes.  I don't see these as particularly useful for functional annotation of genes/gene products; rather, these are motivated by the task of annotation of text with GO classes.  There are several requests herein, but I thought it'd be more comprehensible to aggregate these, as they're related.

First, mirroring GO:'biological regulation', which subsumes regulations of biological processes, functions, and qualities, it'd be really useful to also have GO:'positive biological regulation' and GO:'negative biological regulation' that analogously subsume positive/negative regulations of biological processes, functions, and qualities.  Though there are currently only positive/negative regulations of biological processes, it'd be much easier to annotate all mentions of positive/negative biological regulation rather than figure out which ones are positive/negative regulations of biological processes specifically.

Then, building off of these, I'd like to suggest GO:'biological activation' and GO:'biological inhibition' as subclasses of GO:'positive biological regulation' and GO:'negative biological regulation', respectively, as these are very common in biomedical text.  Other subtypes of positive regulation (e.g., acceleration, initiation, increase (in level of)) and negative regulation (e.g., delay, termination, decrease (in level of)) would be great as well, but aren't as important as the first two.

There are some followup suggestions as well, but I'll first wait for your responses to these... :)

Thanks!
Mike

Reported by: mbada

Original Ticket: [geneontology/ontology-requests/10900](https://sourceforge.net/p/geneontology/ontology-requests/10900)

**Comment by pgaudet** [comment]
The synonyms  'activation' and 'inhibition' already exist for the BPs positive regulation of biological process and negative regulation of biological process; hopefully this is sufficient, we will not create the activation and inhibition BPs, this has led to a lot of misannotation in the past, since it's hard to define and especially, characterize experimentally.
