### ISSUE TITLE
facioacoustic ganglion development terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11111]
A student from UCL (Mathew Tata) is annotating PMID:18356247, and needs some new terms to describe development of the acoustico-facial VII-VIII ganglion complex (UBERON_0012175). (The sibling trigeminal ganglion development terms are already in place).

I'd suggest the primary names to be:
facioacoustic ganglion complex development
facioacoustic ganglion complex morphogenesis
facioacoustic ganglion complex structural organisation

under 'cranial ganglion development ; GO:0061550' etc. With all the necessary intersections to the Uberon term.

For the definitions:
The facioacoustic complex comprises the vestibuloacoustic ganglion in its proximal part and the geniculate ganglion in its distal part (PMID:18356247).

synonyms: 
acoustico-facial VII-VIII ganglion complex development/morphogenesis/structural organisation (UBERON_0012175)
facioacoustic ganglia development/morphogenesis/structural organisation (PMID:18356247)

I can add these in myself- just making a note here to keep track, and in case there's any comments.

thanks.

Reported by: rebeccafoulger

Original Ticket: [geneontology/ontology-requests/10928](https://sourceforge.net/p/geneontology/ontology-requests/10928)

**Comment by rebeccafoulger** [comment]
facioacoustic ganglion morphogenesis ; GO:1904836

Decided the structural organisation term isn't needed currently, so closing this ticket.
