### ISSUE TITLE
GO terms for androgen/estrogen

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11135]
Based on the following excerpt from PMID:11792437 "The presumed rtSBP exhibited a broad binding capacity for endogenous steroids by binding estrogens and androgens and to a lesser degree P (Fig.3a)." I found GO:0005497 androgen binding and tried to do a NTR to TermGenie for "estrogen binding" using the template "chemical_binding" because I was unaware of the constraint regarding the allowed input terms for that template. Heiko informed me the term CHEBI:50114 estrogen is _only_ classified as a role.  It has no other chemical structural classification, which we could use in GO and Chris asked if I could generate a discussion since it seems CHEBI have re-classified estrogen and androgen out of the structure branch and into the role branch. Thanks

Mike Rice

Reported by: mikerice7

Original Ticket: [geneontology/ontology-requests/10952](https://sourceforge.net/p/geneontology/ontology-requests/10952)

**Comment by dosumis** [comment]
Added following the pattern for androgen for now.  Plan to switch to using role pattern (which will => better classification) but need advice on how to do that.

@cmungall  How do I add a new GOCHE term?  Do I just edit to substance_by_role.obo ?

**Comment by dosumis** [comment]
(also - shouldn't this file be using an RO relation for has_role?)

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21106254/5c382cb6-c085-11e6-8632-220de76287b5.png)

**Comment by cmungall** [comment]
You can add it by hand for now, following the same URI and design pattern.

I started this repo, but it's not in production yet:
https://github.com/cmungall/bio-chebi

**Comment by dosumis** [comment]
So add in OBO and term will be available tomorrow?

**Comment by cmungall** [comment]
Add it it the .owl. This is imported by bio-chebi.owl.

You will also need to reference it, either in the ontology, or in 
imports_requests.obo - after that it will be in chebi_import
