### ISSUE TITLE
auditory hair cell vs inner ear receptor cell

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11138]
I'm trying to figure out the difference between these two:

```
[Term]
id: GO:0042491
name: auditory receptor cell differentiation
def: "The process in which a relatively unspecialized cell acquires specialized features of an auditory hair cell." [CL:0000201, GOC:jl]
****comment: Note that this term refers to the mechanosensory hair cells of the inner ear.
synonym: "auditory hair cell differentiation" EXACT []
is_a: GO:0035315  ! hair cell differentiation
is_a: GO:0060113  ! inner ear receptor cell differentiation
intersection_of: GO:0030154  ! cell differentiation
intersection_of: results_in_acquisition_of_features_of CL:0000202

[Term]
id: GO:0060113
name: inner ear receptor cell differentiation
def: "The process in which relatively unspecialized cells, acquire specialized structural and/or functional features of inner ear receptor cells. Inner ear receptor cells are mechanorecptors found in the inner ear responsible for transducing signals involved in balance and sensory perception of sound." [GOC:dph]
synonym: "inner ear hair cell differentiation" EXACT []
is_a: GO:0042490  ! mechanoreceptor differentiation
relationship: part_of GO:0048839 ! inner ear development
```

The ARCD label sounds like it could be referring to any kind of hearing cell... but the comment forces it to be inner ear.

the GO def for ARCD has a def-xref to CL:0000201. This is an old ID, merged into:

```
[Term]
id: CL:0000202
name: auditory hair cell
namespace: cell
alt_id: CL:0000201
def: "A mechanoreceptor cell located in the inner ear that is sensitive to auditory stimuli. The accessory sensory structures are arranged so that appropriate stimuli cause movement of the hair-like projections (stereocilia and kinocilia) which relay the information centrally in the nervous system." [MESH:A08.663.650.250]
comment: In mammals these cells are located in the organ of Corti.
synonym: "auditory receptor cell" EXACT []
synonym: "cochlear hair cell" EXACT []
synonym: "inner ear hair cell" EXACT [GO:0060119]
****synonym: "inner ear receptor cell" EXACT [GO:0060119]
xref: FMA:62364
is_a: CL:0000006  ! neuronal receptor cell
is_a: CL:0002374  ! ear hair cell
is_a: CL:0002491  ! auditory epithelial cell
relationship: RO:0002215 GO:0050910 ! detection of mechanical stimulus involved in sensory perception of sound
relationship: part_of UBERON:0002227 ! spiral organ of cochlea
```

Note the highlighted ***\* exact synonym (derived from GO....)

So it seems at one point one ontology merged the concepts or split the concepts....

if inner ear receptor cells can be for things other than sound (eg balance) then the CL class needs unmerged or a new one created

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10955](https://sourceforge.net/p/geneontology/ontology-requests/10955)

**Comment by ValWood** [comment]
![nodule hpg](https://user-images.githubusercontent.com/7359272/33078267-0d238d06-ceca-11e7-8d16-5ae27a7155bd.jpg)

**Comment by ValWood** [comment]
GO:0042491   auditory receptor cell differentiation
Definition 
The process in which a relatively unspecialized cell acquires specialized features of an auditory hair cell.
Comments
Note that this term refers to the mechanosensory hair cells of the inner ear.

so action is
rename to

INNER EAR   auditory receptor cell differentiation to clarify

REFINE/CLARIFY  TEXT DEF
The process in which a relatively unspecialized ****inner ear ****cell acquires specialized features of an auditory hair cell.

GO is otherwise correct
GO:0042491 is a part GO:0060113

**Comment by ValWood** [comment]
Could then remove the comment as would be superflous

**Comment by pgaudet** [comment]
@hdrabkin 
@sabrinatoro 
You guys have the most annotations to these terms. 
1. Are you OK with the solution proposed by Val ? 
2. Should we also rename the term 'auditory receptor cell fate specification' (and regulation children, and other siblings 'development/commitment/morphogenesis) 'inner ear auditory receptor cell fate specification'? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
I'm not an expert but from just looking, It looks like
"inner ear receptor cell differentiation"  might imply that there are different types of inner ear receptor cells, of which
"auditory receptor cell differentiation" is one type. This one is defined in the comment as meaning the mechanosensory hair cells of the inner ear"; 
But if there are other types of inner ear receptors, then inner ear receptor cell diff cannot (always) be a GO:0042490  ! mechanoreceptor differentiation.

**Comment by sabrinatoro** [comment]
Is the proposal to update to "inner ear receptor cell fate specification" or to "inner ear AUDITORY receptor cell fate specification"? It is not clear.

There are 2 types of mechanoreceptor in the inner ear: the auditory receptors, and the vestibular receptors. Both type of receptors are hair cells. 
Often (at least in zebrafish), authors do not make the difference between the auditory and the vestibular receptors, so a curator would probably use "inner ear receptor cell fate specification" when curating. 
In other species, I think researchers might have be able to distinguish between both. 
Also, to my knowledge, there is not "auditory" receptor cells outside the inner ear. (the neuromast hair cells are close to it, but they are not called 'auditory')

SO: I would be ok with Val's proposal to update the term name "auditory receptor cell fate specification" to: inner ear **auditory** receptor cell fate specification. 
However, I don't think it would be a good idea to call it "inner ear receptor cell fate specification" (without the auditory)

**Comment by dosumis** [comment]
>  to my knowledge, there is not "auditory" receptor cells outside the inner ear. (the neuromast hair cells are close to it, but they are not called 'auditory')

Insects don't have ears, but do have auditory receptor cells.

This should really be co-ordinated with CL.  

Seems like CL should have

auditory receptor cell (functional definition)
    .   auditory receptor hair cell of inner ear
mechanosensory hair cell (functional + )
.     mechanosensory hair cell of inner ear
.     .    auditory receptor hair cell of inner ear
.     .    .... {perhaps term here for inner ear cells involved in perception of balance}

Don't know what granularity you want for GO, but developmental mechanisms likely to be very different for arthropods -> vertebrates so should at least be able to keep these separate.

**Comment by pgaudet** [comment]
Hi @sabrinatoro 
What I have done is change the name 
OLD: auditory receptor cell differentiation
NEW: inner ear auditory receptor cell differentiation

and the definition
OLD: "The process in which a relatively unspecialized cell acquires specialized features of an auditory hair cell." [CL:0000201, GOC:jl]
NEW: "The process in which a relatively unspecialized inner cell acquires specialized features of an auditory hair cell." [CL:0000201, GOC:jl]

Does that work ? 

Whatever we need from CL should be requested to CL ;) 

Thanks, Pascale

**Comment by sabrinatoro** [comment]
@pgaudet 
Yes, it works for me! 
Thank you!
