### ISSUE TITLE
Change specific responses to chemicals to part_of response to X

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11141]
During the [June 2014 meeting on annotation extension relations](http://wiki.geneontology.org/index.php/Annotation_Extension_meeting_2014-06-16),
it was agreed to change terms for specific responses to chemicals (see
[item 1 from 140624 annotation call minutes](http://wiki.geneontology.org/index.php/Annotation_Conf._Call,_June_24,_2014#Summary_of_proposed_action_items_from_annotation_extension_relation_meeting)).

Examples:
[chemosensory behavior](http://purl.obolibrary.org/obo/GO_0007635)
is_a 'response to chemical' -> 
[chemosensory behavior](http://purl.obolibrary.org/obo/GO_0007635)
part_of  'response to chemical' 

Motivating example (seems to be fictional term):

‘proteolysis [involved] in cellular response to drug' could have  two has_input relationships:
has_input: drug
has_input: proteolysis target.
The has_inputs work in the individual cases but when combined, how do you know which input is which?
A. The drug isn’t an input to the proteolysis. The proteolysis is part of the cellular response to drug.  So 'proteolysis [involved] in cellular response to drug' should be part of cellular response to drug, rather than is_a.

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/10958](https://sourceforge.net/p/geneontology/ontology-requests/10958)

**Comment by pgaudet** [comment]
@vanaukenk @ukemi 
This is probably out of date ? If you think so, please close. 

Thanks, Pascale

**Comment by ukemi** [comment]
I just looked at the example and it seems this was implemented. If we continue to have issues, we should model these in GO-CAM.
