### ISSUE TITLE
NTR - autoinducer 2 transport 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11158]
Can I request a BP term for autoinducer 2 (AI-2) transmembrane transport. Def: the directed movement of AI-2 across a membrane by means of a transporter or pore. Child of GO:0055085: transmembrane transport. AI-2 (CHEBI:44800) is produced by prokaryotes and is believed to play a role in quorum sensing. 

And associated new terms in the MF and CC ontologies:

AI-2 transmembrane transporting ATPase activity in the the MF ontology. Child of GO:0042626: ATPase activity coupled to TM movement of substances.

AI-2 ABC transporter complex. Child of GO:0043190 ATP binding cassette transporter complex. Def: Protein complex facilitating ATP-dependent AI-2 transport through the cytoplasmic membrane in prokaryotes.

Literature ref: PMID 15601708 (Xavier 2005)

Thanks
Amanda

Reported by: amackie

Original Ticket: [geneontology/ontology-requests/10975](https://sourceforge.net/p/geneontology/ontology-requests/10975)

**Comment by dosumis** [comment]
Added via TG:

[Term]
id: GO:1905887
name: autoinducer AI-2 transmembrane transport
namespace: biological_process
def: "The directed movement of (2R,4S)-2-methyltetrahydrofuran-2,3,3,4-tetrol (autoinducer AI-2) across a membrane. AI-2 (CHEBI:44800) is produced by prokaryotes and is believed to play a role in quorum sensing." [GO_REF:0000069, GOC:TermGenie, PMID:15601708]
synonym: "AI-2 transmembrane transport" EXACT [PMID:15601708]
synonym: "autoinducer 2 transmembrane transport" EXACT [PMID:15601708]
synonym: "(2R,4S)-2-methyltetrahydrofuran-2,3,3,4-tetrol transmembrane transport" EXACT [PMID:15601708]
intersection_of: GO:0055085 ! transmembrane transport
intersection_of: transports_or_maintains_localization_of CHEBI:44800 ! (2R,4S)-2-methyltetrahydrofuran-2,3,3,4-tetrol
created_by: dosumis
creation_date: 2017-01-31T14:34:50Z
