### ISSUE TITLE
membrane raft inferences

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11153]
'protein localization to membrane raft ; GO:1903044' is not being inferred to be is_a 'protein localization to membrane ; GO:0072657' because membrane raft is_a membrane part, not a membrane.

Change membrane raft to be is_a membrane region and recheck inferences.

Reported by: jl242

Original Ticket: [geneontology/ontology-requests/10970](https://sourceforge.net/p/geneontology/ontology-requests/10970)

**Comment by dosumis** [comment]
Fixed by improved axiomatisation of membrane regions - now inferred.
