### ISSUE TITLE
Duplicate ferrous iron transmembrane transporter terms?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11172]
http://purl.obolibrary.org/obo/GO_0015093
ferrous iron transmembrane transporter activity: "Catalysis of the transfer of ferrous iron (Fe(II) or Fe2+) ions from one side of a membrane to the other."

http://purl.obolibrary.org/obo/GO_0015639
ferrous iron uptake transmembrane transporter activity: "Catalysis of the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: Fe2+(out) + energy = Fe2+(in)."

Uptake is context (although a rather vague one). We should be relying on XPs to process to give context.  

Look in to obsoleting or merging.

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/10989](https://sourceforge.net/p/geneontology/ontology-requests/10989)

**Comment by ValWood** [comment]
This is dealt with by @pgaudet 

ferrous iron uptake transmembrane transporter activity
is merged into 
ferrous iron transmembrane transporter activity
