### ISSUE TITLE
incorrect def for ventricular cardiac muscle cell differentiation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11173]
```
[Term]
id: GO:0055012
name: ventricular cardiac muscle cell differentiation
namespace: biological_process
def: "The process in which a relatively unspecialized cell acquires specialized features of a cardiac muscle cell. Cardiac muscle cells are striated muscle cells that are responsible for heart contraction. The ventricle is the part of the heart that pumps blood out of the organ." [GOC:devbiol, GOC:mtg_heart]
synonym: "ventricular cardiomyocyte differentiation" EXACT []
synonym: "ventricular heart muscle cell differentiation" EXACT []
is_a: GO:0055007  ! cardiac muscle cell differentiation
```

The definition is identical to that of GO:0055007  ! cardiac muscle cell differentiation

"The process in which a cardiac muscle precursor cell acquires specialized features of a cardiac muscle cell."

(gloss doesn't count)

"The process in which a relatively unspecialized cell acquires specialized features of a ventricular cardiac muscle cell. Ventricular cardiac muscle cells are striated muscle cells that are responsible for heart contraction found in cardiac ventricles".

If this is correct please also add the CL term via cl.termgenie.org

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10990](https://sourceforge.net/p/geneontology/ontology-requests/10990)

**Comment by ValWood** [comment]
This seems done?

**Comment by RLovering** [comment]
yes looks done to me too
