### ISSUE TITLE
negative regulation of protein localization to cell tip involved in positive regulation of establishment of cell polarity regulating cell shape

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11170]
This ticket is for discussion and resolution of a TermGenie request for a pair of compound terms with very long names with multiple clauses.  The term genie requests have been rejected (=> obsoletion of the terms).

"protein localization to cell tip involved in positive regulation of establishment of cell polarity regulating cell shape"
intersection_of: GO:1990151 ! protein localization to cell tip
intersection_of: part_of GO:2000784 ! positive regulation of establishment of cell polarity regulating cell shape

"negative regulation of protein localization to cell tip involved in positive regulation of establishment of cell polarity regulating cell shape"
intersection_of: GO:1903067 ! negative regulation of protein localization to cell tip
intersection_of: par\t_of GO:2000784 ! positive regulation of establishment of cell polarity regulating cell shape

These terms were requested for curation of Kokkoris  et al., 2014. PMID:24554432
## Critique of term names:

These terms are hard for most people to read and understand.  The main problem is not their length (although that doesn't help), it is the multiple occurences of 'regulates'  (positive, negative and neutral) combined with involved in.
### The big picture:

"microtubule organization and cell shape form a self-reinforcing system, in which the cell shape provides physical constraints that align microtubules along the length of the cell to deliver landmarks to cell extremities, which in turn reinforce the rod shape by marking the cell ends for growth"
#### Can we simplify/clarify the terms by changing the way we capture this context?
- Doesn't all establishment/maintenance of cell polarity have some effect on cell shape? If so, do we need to mention most in the term?
- Given that we're talking about a self-reinforcing system rather than de novo establishment of a state, wouldn't it be clearer to use 'maintenance' to describe this, rather than regulation?  
- What about the relationship to polarised growth? We have a variety of terms for this (e.g. bipolar cell growth; cell tip growth), but the requested terms lack this context. Presumably polarised cell growth is always dependent on a prior establishment of cell polarity followed by ongoing maintenance of cell polarity.  It should be possible to reflect this in the ontology.
- Would be enough to capture a smaller slice of this big picture?  Rather than establishement of cell polarity regualting cell shape, perhaps: 'maintenance of cell polarity' OR 'maintenance of polarised cell growth'
### The molecular details:

Microtubules deliver Tea1-Tea4 to the poles where it activates Cdc42. This activation drives localised growth. e.g. via promoting polarised exocytosis of cell wall remodelling enzymes.

The paper focuses on how Tea4 activates Cdc42.  It does this by binding and recruiting an activator of Cdc42 (the GEF, gef1), while locally excluding a inhibitor of Cdc42 (the GAP, Rga4)
## Some suggestions

Tea4 capable_of protein localisation to cell tip involved in maintenance of polarised cell growth (localizes Gef1)
Tea4 capable_of negative regulation of protein localisation to cell tip involved in maintenance of polarised cell growth (some relationship to Rga4 ?)

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/10987](https://sourceforge.net/p/geneontology/ontology-requests/10987)

**Comment by ValWood** [comment]
Can probably close since the offending terms are obsoleted?
