### ISSUE TITLE
New term request_suppression by virus of host ISGF3 complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11197]
Term name: suppression by virus of host ISGF3 complex
Definition: any process in which a virus stops, prevents, or reduces the activity of the host ISGF3 complex, a transcription factor complex that consists of a Stat1-Stat2 heterodimer and the IRF9 protein. 
Reference: PMID:15825084

Reported by: mammari

Original Ticket: [geneontology/ontology-requests/11014](https://sourceforge.net/p/geneontology/ontology-requests/11014)

**Comment by ValWood** [comment]
There are lots of terms along these lines

GO:0039562    suppression by virus of host STAT activity  10,205 annotations
GO:0039564    suppression by virus of host STAT2 activity  8,597 annotations
GO:0039563    suppression by virus of host STAT1 activity  1,608 annotations
GO:0039560    suppression by virus of host IRF9 activity  5 annotations
GO:0039557    suppression by virus of host IRF7 activity  

are they really all different processes?

**Comment by pgaudet** [comment]
@pmasson55 wanted to keep these. 
However the terms with complexes have been replaced by 'activity', for eg suppression by virus of host ISGF3 complex would be suppression by virus of host ISGF3 activity. 

I'll obsolete the complexes. 

Thanks, Pascale
