### ISSUE TITLE
GO:0031145 - anaphase-promoting complex-dependent proteasomal ubiquitin-dependent protein catabolic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11208]
this term name seems unnecessarily verbose

GO:0031145 - anaphase-promoting complex-dependent proteasomal ubiquitin-dependent protein catabolic process

As all APC dependent catabolism is always Ub and proteasome dependent (and this is captured by the def) could it be called just

anaphase-promoting complex-dependent catabolic process ?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11025](https://sourceforge.net/p/geneontology/ontology-requests/11025)

**Comment by ValWood** [comment]
Thoughts? The proposed new name but have the same meaning but be more succint?

**Comment by dosumis** [comment]
Changed
