### ISSUE TITLE
NTR: regulation of transcription involved in carbohydrate catabolism

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11218]
Hello, 

I'd like a term to describe the regulation of transcription of sets of genes involved in carbohydrate catabolism - gylcolysis, in particular. 
Reference: PMID: 19995986
This new term would replace IMP annotations made to several different phenotypes to protein Q9NP71.

Thanks, 

Pascale

Reported by: pgaudet

Original Ticket: [geneontology/ontology-requests/11035](https://sourceforge.net/p/geneontology/ontology-requests/11035)

**Comment by dosumis** [comment]
We already had:

rdfs:label "regulation of carbohydrate metabolic process by regulation of transcription from RNA polymerase II promoter"^^xsd:string
id "GO:1900402"^^xsd:string
has_obo_namespace "biological_process"^^xsd:string
definition "A regulation of transcription from RNA polymerase II promoter that results in regulation of carbohydrate metabolic process."^^xsd:string
has_exact_synonym "regulation of carbohydrate metabolism by regulation of transcription from RNA polymerase II promoter"^^xsd:string
created_by "mah"^^xsd:string
creation_date "2012-04-20T02:45:27Z"^^xsd:string

I fixed its logical def ->

'regulation of transcription from RNA polymerase II promoter'
 and (regulates some 'carbohydrate metabolic process')

And added 

rdfs:label "regulation of carbohydrate catabolic process by regulation of transcription from RNA polymerase II promoter"
has_obo_namespace "biological_process"^^xsd:string
definition "A regulation of transcription from RNA polymerase II promoter that results in regulation of carbohydrate catabloism."^^xsd:string
has_exact_synonym "regulation of carbohydrate catabolism by regulation of transcription from RNA polymerase II promoter"^^xsd:string
created_by "dos"^^xsd:string
creation_date "2017-01-31T14:46:21Z"^^xsd:dateTime
EquivalentTo: 'regulation of transcription from RNA polymerase II promoter'
 and (regulates some 'carbohydrate catabolic process')

=> automated classification under:

'regulation of carbohydrate catabolic process'
'regulation of carbohydrate metabolic process by regulation of transcription from RNA polymerase II promoter'

@pgaudet  - discovered this ticket - lost during transition from SourceForge.  Hope above fix is good (TG template has issues).

**Comment by pgaudet** [comment]
Looks like it addresses it ! 

Thanks, Pascale
