### ISSUE TITLE
NTR: connecting the nucleus to the cytoskeleton

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11220]
Hi,

Request for new BP term to annotate the components of the SUN-KASH subunits.

Term name: connecting the nucleus to the cytoskeleton
(sorry I couldn't come up with a different/better term name).
Child of cytoskeleton organization.
http://www.ncbi.nlm.nih.gov/pubmed/20507227
http://www.ncbi.nlm.nih.gov/pubmed/23149102
http://www.ncbi.nlm.nih.gov/pubmed/?term=18396275
http://www.ncbi.nlm.nih.gov/pubmed/14655046

Thanks,
Rama

Reported by: rbalakri

Original Ticket: [geneontology/ontology-requests/11037](https://sourceforge.net/p/geneontology/ontology-requests/11037)

**Comment by ValWood** [comment]
Found this while searching for another ticket. Requested via TGFF so you can close
ID: GO:1990933 Label: microtubule cytoskeleton attachment to nuclear envelope

**Comment by ValWood** [comment]
Ah I can close.
