### ISSUE TITLE
MP GO:0071210 protein insertion into membrane raft

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11226]
add parent

membrane raft organsization?

(and for child plasma membrane term)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11043](https://sourceforge.net/p/geneontology/ontology-requests/11043)

**Comment by ValWood** [comment]
Thoughts?

**Comment by dosumis** [comment]
> it currently has 
> GO:0061024 membrane organization
> as a parent?

Not any more:

![image](https://cloud.githubusercontent.com/assets/112839/14608292/05e8ef12-057d-11e6-94d1-eb8499597b07.png)

+ agree with original comment.  Unless you have a paper suggesting protein composition is important to generating rafts, I think we shouldn't add the parent.

**Comment by ValWood** [comment]
OK!

**Comment by dosumis** [comment]
Deleted comment. My bad.

**Comment by ValWood** [comment]
HI David,

I still see "membrane organization" as a parent in the graph above.
Can you confirm?

Thanks

Val

**Comment by ValWood** [comment]
OK, cross post :)

**Comment by dosumis** [comment]
Thinking about it - I'm not too bothered either way.  I'll add it the link to org lipid raft.

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/14608576/3b234f8c-057e-11e6-9bee-e2a4a1c293f7.png)
