### ISSUE TITLE
Regulation of ... regulation of heart contraction

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11230]
Hi 

I recently used term genie to request new GO terms, which have been obsoleted.

PMID:17242280 describes how overexpression of PMCA4b (ATP2B4 P23634) reduced the beta-adrenergic contractile response. This effect appears to be via nNOS (Nos1, Q9Z0J4) as treatment with a specific nNOS inhibitor (N omega-propyl-L-arginine) reduced the beta-adrenergic response in wild-type and ct120 transgenic mice to levels comparable to those of PMCA4b transgenic animals.

Sorry this is all a bit complicated.

Firstly they use isoproterenol to mimic the effects of adrenalin, therefore I was looking at the GO term regulation of the force of heart contraction by chemical signal, rather than an adrenalin term, although based on the intention of the author possibly the GO term:
GO:0001997 positive regulation of the force of heart contraction by epinephrine-norepinephrine  would be a`more appropriate starting point than 
GO:0003099 positive regulation of the force of heart contraction by chemical signal.

The second point is that I wouldn't normally annotate based on an inhibitor, but in this case they provide good description of the specificity of the inhibitor: The potency and selectivity of nNOS inhibition by L-nPA is 149-fold relative to eNOS and 3158-fold relative to iNOS34 which suggests that the response was not due to inhibition of other NOS isoforms.

The paper results section states: To determine the effects of β-adrenergic stimulation on cardiac contractility, we analyzed the pressure-volume data after injection with isoproterenol 800 ng/kg body weight. Representative baseline and isoproterenol-induced pressure-volume loops are presented in Figure 2. End-systolic elastance (Ees), an indicator of cardiac contractility, was increased by 4017% in wild-type mice. This response was significantly attenuated in mice overexpressing PMCA4b (Ees change 1115%, P<0.05 versus wild type; Figure 2C). 

I have interpreted the pressure-volume data as an measure of heart force.

There is already the GO term
GO:0086094 positive regulation of ryanodine-sensitive calcium-release channel activity by adrenergic receptor signaling pathway involved in positive regulation of cardiac muscle contraction.

And  GO:0001997 positive regulation of the force of heart contraction by epinephrine-norepinephrine

From the experiments presented we don't know how nNOS and PMCA4b regulate the force of heart contraction after isoproterenol stimulation.

So I was looking for all three regulation terms either based on the chemical signal terms:
GO:0003099 positive regulation of the force of heart contraction by chemical signal.
ie:
GO:1903239
name: regulation of positive regulation of the force of heart contraction by chemical signal
GO:1903240
name: negative regulation of positive regulation of the force of heart contraction by chemical signal
(to associated with human PMCA4b)
And 
(I didn't request this originally) name: positive regulation of positive regulation of the force of heart contraction by chemical signal
(to associated with mouse Nnos)

Or using the GO:0001997 positive regulation of the force of heart contraction by epinephrine-norepinephrine term.

Help would be appreciated

Regards

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11047](https://sourceforge.net/p/geneontology/ontology-requests/11047)

**Comment by ukemi** [comment]
Hi Ruth,

Did this work for you?

-David

**Comment by RLovering** [comment]
yup this is fine
