### ISSUE TITLE
intra-S checkpoint related

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11240]
Based on feedback from Nick Rhind to this question, small refinements required

There are two closely related, possibly (but probably not) identical, responses to disruptions to DNA replication: one responds to treatments that slow or stall replication forks without necessarily causing DNA damage (i.e., HU aphidicolin, etc), the other responds to actual physical or chemical damage of the DNA.  Both have been referred to as the intra-S checkpoint.  I think referring to them as the intra-S DNA replication checkpoint and intra-S DNA damage checkpoint, respectively, and using the definitions below would be fine, although I would modify the definition of the intra-S DNA replication checkpoint as follows.

A mitotic cell cycle checkpoint  activated in response to nucleotide depletion or other causes of replication fork stalling during DNA replication. The intra-S phase checkpoint  detects stalled replication forks leading to the activation of the Cds1 kinase, which stabilizes DNA replication forks and prevents new origin firing to allow for replication restart after the the cause of the fork stalling is removed.

One additional consideration (which relates to your last question) is that both responses are sub-branches of more comprehensive checkpoints—the S-phase replication checkpoint (sometimes called the replication checkpoint or the S-phase checkpoint) and the S-phase DNA damage checkpoint, respectively—which, in addition to the intra-S targets (e.g. forks and origins) also regulate transcription and inhibit mitosis.
# 

in response to

O:0031573 - intra-S DNA damage checkpoint
is defined

"A mitotic cell cycle checkpoint that slows DNA synthesis in response to DNA damage by the prevention of new origin firing and the stabilization of slow replication fork progression." 

this seems incorrect ? is it a DNA damage checkpoint or a DNA replication checkpoint?

Should it be called intra-S DNA replication checkpoint?
and defined
A mitotic cell cycle checkpoint  activated in response to nucleotide depletion during DNA replication. The intra-S phase checkpoint   detects stalled replication forks leading to the activation of the Cds1 kinase to stabilizes DNA replication forks and  delay S-phase  progression to allow time for replication restart  by preventing new origin firing.
# 

So if we could have the 

intra-S DNA damage checkpoint def amended, and add 
intra-S DNA replication checkpoint

I am checking parentage.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11058](https://sourceforge.net/p/geneontology/ontology-requests/11058)

**Comment by ukemi** [comment]
Hi Val,

What should I do with this one?

-D

**Comment by ValWood** [comment]
Well I'm still not sure and its  way outside my current annotation areas. I suggest to close unless @mah11  knows. I'm not aware of the terms currently causing any problems and we can open a new ticket and refer back to this one if they do....

**Comment by mah11** [comment]
I'm not even sure what the question was. More broadly, my connection with the checkpoint terms in GO can be fairly characterized as "transcribed terms, defs, etc. after Val and others, especially Rob Nash, worked out what they wanted".
