### ISSUE TITLE
new neural crest cell migration terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11257]
Some requests for new NCC migration terms from one of our volunteer annotators, Mathew Tata. For annotation of PMID:19386662.

neural crest cell migration ; GO:0001755
-[isa]trunk neural crest cell migration ; GO:NEW1
--[isa]dorsolateral trunk neural crest cell migration ; GO:NEW2
--[isa]ventral trunk neural crest cell migration ; GO:NEW3

trunk neural crest cell migration ; GO:NEW1
The characteristic movement of trunk neural crest cells from the neural tube to other locations in the vertebrate embryo.
is_a: neural crest cell migration ; GO:0001755
part_of: trunk segmentation ; GO:0035290
PMID:2387238
GOC:mat, GOC:bf, GOC:PARL
exact synonym: trunk NCC migration [PMID:19386662]
intersection_of: GO:0016477 ! cell migration
intersection_of: has_input CL_0000011 ! migratory trunk neural crest cell

dorsolateral trunk neural crest cell migration ; GO:NEW2
The movement of trunk neural crest cells from the neural tube, travelling
dorsolaterally into the ectoderm and continuing toward the ventral midline
of the belly. These migrating trunk neural crest cells become melanocytes,
the melanin-forming pigment cells.
PMID:2387238
GOC:mat, GOC:bf, GOC:PARL

ventral trunk neural crest cell migration ; GO:NEW3
The movement of trunk neural crest cells from the neural tube, travelling
ventrally through the anterior half of each sclerotome. Trunk neural crest
cells that remain in the sclerotome form the dorsal root ganglia
containing the sensory neurons. Trunk neural crest cells that continue
more ventrally form the sympathetic ganglia, the adrenal medulla, and the
nerve clusters surrounding the aorta.
PMID:19386662
PMID:16319111
GOC:mat, GOC:bf, GOC:PARL

Adding here to remind me to do the edits when I'm back from A/L, and for any comments.
Thanks!

exact synonym: trunk NCC migration through anterior sclerotome
[PMID:19386662]
narrow synonym: trunk NCC migration within somite [GOC:mat]

trunk neural crest cell migration ; GO:NEW1

Reported by: rebeccafoulger

Original Ticket: [geneontology/ontology-requests/11075](https://sourceforge.net/p/geneontology/ontology-requests/11075)

**Comment by rebeccafoulger** [comment]
Cross-products added to 'trunk neural crest cell migration ; GO:0036484' so closing this ticket.
