### ISSUE TITLE
insulin secretion - always from pancreatic cells?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11255]
```
[Term]
id: GO:0030073
name: insulin secretion
def: "The regulated release of proinsulin from ***secretory granules (B granules) in the B cells of the pancreas***; accompanied by cleavage of proinsulin to form mature insulin." [GOC:mah, ISBN:0198506732]
is_a: GO:0030072 ! peptide hormone secretion
```

We have a two annotations to regulation of insulin secretion in worm and fly.

the pancreas and proto-pancreas structures are vertebrate-specific PMID:16417468, but insulin is a billion years old:

http://en.wikipedia.org/wiki/Insulin

Looked at the drosophila annotation abstract, insulin is indeed being secreted:
http://www.ncbi.nlm.nih.gov/pubmed/23874700

There are two possible courses of action here:
1. Weak: alter text definition to be: "The regulated release of insulin from a cell. In vertebrates, this is always from beta cells of the pancreas, and is accompanied by cleavage of the secreted proinsulin to form mature insulin"
2. Strong: change label to be "insulin secretion from B cell" and axiomatize accordingly. This will invalidate the 4 invert annotations. To accommodate, create a new grouping class "insulin secretion"

Note that 1 could be accompanied by a taxon GCI as in uberon, but we don't use these in GO yet, and probably shouldn't until Protege 5.

I would therefore vote for 2, even though this contributes to the drunk-christmas-tree effect.

Use case driving decision: a user is looking for animal models of diabetes, or disorders involving pancreatic B cells. They query GO using the CL class, they get the specific GO class, which does not yield the FB gene. They have to go one level up (note this isn't necessary with the taxon-GCI route, but the query machinery is harder), e.g. via semantic similarity query, then they get the fly genes.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/11073](https://sourceforge.net/p/geneontology/ontology-requests/11073)

**Comment by hattrill** [comment]
All of our annotations relate to release of insulin-like peptides from insulin-producing cells (IPCs) in the brain (in FBbt insulin secreting cell of pars intercerebralis FBbt:00004011). These behave like and are equivalent to vertebrate beta cells (ie respond to nutrient levels) and downstream the insulin-like peptides act like insulin. We have other cell-types that produce insulin-like peptides, but they are not part of the response to nutrients.

**Comment by pgaudet** [comment]
Hi @hattrill Thanks for looking into it. Do you think the mechanism of insulin secretion (which I assume contains some signaling) is conserved enough to use the same term (and hence either remove pancreatic cells from the def, or add something about insect beta cells) - or we could create another term. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Thanks. I fixed the definition as follows: "The regulated release of proinsulin from secretory granules accompanied by cleavage of proinsulin to form mature insulin. In vertebrates, insulin is secreted from B granules in the B cells of the vertebrate pancreas and from insulin-producing cells in insects." 

And added taxon constraint 'only in metazoa'. 

Thanks, Pascale

**Comment by cmungall** [comment]
What's the evidence for the only-in taxon? Isn't the pathway conserved as far back as Tetrahymenina?

Also: the term def references "B granules", but there is no such class in GO.

The axiom references http://purl.obolibrary.org/obo/PR_000009054  which says "An insulin family protein that is a translation product of the human INS gene or a 1:1 ortholog thereof"

is this appropriate for Dmel and Celegans? On v slow connection now hard to check.

(would be good if PRO had TCs at higher level)

**Comment by hattrill** [comment]
C.elegans/D.mel have what are termed "insulin-like peptides" - some behave more like insulin, some like IGFs and some like relaxin. 
The ILPs produced from IPCs in D.mel functionally equivalent to insulin. In terms of orthology, ILP3 and 5 are "orthologs" of human insulin, ILP2 is ortholgous to human IGF1/2.

**Comment by vanaukenk** [comment]
I've looked at the two C. elegans annotations which are to positive and negative regulation of insulin secretion, respectively.

Both annotations reflect physiologically relevant biology that appears to be well conserved phylogenetically.

One of the annotations, though, would be better captured in a GO-CAM model since it is to a transcription factor and that activity is probably best characterized as 'causally upstream of' insulin secretion.

Wrt the term definition, what are the key things we want to capture?

1.  That the secretion is regulated? If so, by what?
2.  That the secretion is accompanied by peptide processing?
3.  That the secretion acts upon a particular class of molecule?
4.  That the secretion happens in particular cell types?
5.  That the secretory vesicles share similar structural/functional features?

I think it would be helpful if we could define the beginning and end of secretion in this and other secretion term definitions, as it might help us decide at what level we can really make these comparisons.  My overall impression, though, is that insulin secretion is well conserved.

**Comment by pgaudet** [comment]
@cmungall what would be the appropriate taxon restriction ? Eukaryotes perhaps ?

**Comment by pgaudet** [comment]
@vanaukenk I moved your questions about the definition of secretion to a new ticket - I think this deserves a separate discussion.
