### ISSUE TITLE
Is "neutrophil mediated immunity" an "immune response" ? 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11262]
Hello, 

"neutrophil mediated immunity" is not a child of immune response; however it has "immune response" in its definition. Can you check whether it may be missing a parent ? 

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: [geneontology/ontology-requests/11080](https://sourceforge.net/p/geneontology/ontology-requests/11080)

**Comment by pgaudet** [comment]
Alex's response on Oct 25, 2017 

> I need to investigate this issue a bit more closely, in terms of looking back at the original immunology revision of 2006, to see if terms have moved at some point and to reread some of the discussions.  Also the QuickGO derived graph views in Amigo aren't working well today.

>I think the immune effector process terms are intended as a parts list for processes that are parts of immune responses.
As to the distinction between the two terms "immune response”  and "immune system process”, I quote from our paper describing the revision (https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btm029, PMID:17267433) :

>A new high level term in the biological process ontology, ‘immune system process’, has been created to group all processes directly related to the functioning of the immune system, including developmental and tolerance processes in addition to the activation and effector mechanisms of the immune system. Terms covering antigen sampling, processing and presentation, which operate continuously, also fall under this high-level term, as well as basic terms such as ‘leukocyte migration’ and ‘leukocyte homeostasis’, which cover processes that occur both apart from and as part of immune responses.

>The term ‘immune response’, which previously existed in the GO, is now a child of the ‘immune system process’ term. Children of the ‘immune response’ term include the basic processes of ‘innate immune response’, ‘adaptive immune response’, and ‘humoral immune response’, as well as a grouping term for organ or tissue specific immune responses such as those in the mucosa. Because the GO allows for multiple inheritance, many subterms are children of more than one of these terms covering basic types of immune response. An example is the GO term ‘humoral immune response mediated by circulating immunoglobulin’, which has is_a relationships to both ‘humoral immune response’, as a direct child, and ‘adaptive immune response’, via several intermediate terms. Such dual parentage accurately reflects how these processes are alternatively regarded by working immunologists.

>I will get back you next week.

>Thanks,
>Alex

**Comment by pgaudet** [comment]
I am still unsure what to do about this one. There are two very closely related terms in the ontology, 
* immune response process: Any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat.
and 
* immune effector process: Any process of the immune system that can potentially contribute to an immune response.


Looks like the 'immune effector processes' children are 'part of' immune response, so perhaps the 'immune effector process' term is needed for is_a completeness. 

I'll close this. 

Thanks, Pascale
