### ISSUE TITLE
NTR: some new terms for ciliary BBSome complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11280]
Hi,

I've been reading about the BBSome to do some PAINT families and I think we need some new terms. According to a couple great reviews (PMID:19575670 and PMID:20697559), the BBSome complex is a membrane coat, though it is not yet clear if the BBSome coat forms a vesicle or just a membrane patch that moves laterally within the membrane. Based on what I know now, here's what I propose:

BBSome coat ; GO:new 
is_a: membrane coat ; GO:0030117
Def: A membrane coat involved in trafficking of membrane proteins via recognition of their ciliary targeting sequences (CTS) from the plasma membrane to the ciliary membrane, the BBSome complex is composed of eight conserved proteins (commonly BBS9, BBS7, BBS2, BBS1, BBS8, BBS4, BBS5, and BBIP10 in vertebrates) that have structural elements similar to COPI, COPII, and clathrin coats and which can form patches of polymerase coat on lipid bilayer.
def_dbxrefs: GOC:krc, PMID:19575670, PMID:20697559, PMID:20603001

ciliary targeting signal binding ; GO:new
synonym: CTS binding
is_a: signal sequence binding ; GO:0005048
Def: Interacting selectively and non-covalently with a ciliary targeting sequence, a specific peptide sequence that acts as a signal to localize a membrane protein to the ciliary membrane.
def_dbxrefs: GOC:krc, PMID:19575670, PMID:20697559, PMID:20603001, PMID:18256283

thanks,

-Karen

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/11101](https://sourceforge.net/p/geneontology/ontology-requests/11101)

**Comment by paolaroncaglia** [comment]
Hi @krchristie

This was a ticket of yours from last year (opened before we moved to GitHub).
I went through it again. Summing up, there are no pending tasks about the BBSome term (which we’ll leave as is).
There was, instead, still an unresolved need on your part for ‘coating’ terms.
To speed things up, could you please review your comments one last time, and, in light of what papers you might have come across in this meantime, and of any recent updates to the ontology, please provide details for any new term(s) you may still need (name, def, placement etc as usual), and/or any necessary changes to existing terms. Alternatively, please let me know if I may close this ticket. 

Thanks and have a nice weekend!

**Comment by paolaroncaglia** [comment]
I think this ticket can be safely closed. If any need emerges, it can be captured in a new ticket. Thanks!
