### ISSUE TITLE
"Other term-related request": complexes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11287]
Hi,

I have a suggestion for how complexes are treated in GO. 

I think it would be useful to reserve the word 'complex' for only the terms where both the components and their amounts in the complex can be established. I'd suggest to change the term "macromolecular complex" to e.g. "macromolecular assembly" (or assemblage, or some similar word, see wikipedia on this:http://en.wikipedia.org/wiki/Macromolecular_assembly) and create a new term "macromolecular complex" that is a child of "macromolecular assembly". The definition of the new term would include the restriction that I mentioned above. All current complexes where the composition is not definable qualitatively or quantitatively (e.g. chromatin, microtubule, actin filament, ...) should be children of "macromolecular assembly", but not "macromolecular complex".

Thanks,
Janos

Reported by: jdemetert

Original Ticket: [geneontology/ontology-requests/11108](https://sourceforge.net/p/geneontology/ontology-requests/11108)

**Comment by paolaroncaglia** [comment]
We now have GO:0099081 'supramolecular polymer', so this ticket can be closed.
