### ISSUE TITLE
activator vs activation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11297]
I have a conundrum.

I am trying to describe a phenotype in which there is abolished "activation" of the enzyme activity  in the GO sense. I.e enzyme activators in GO are described as
Increases the activity of a enzyme x, an enzyme that catalyzes y

So, I thought I should be capturing this as "abolished activation of enzyme x"

However, the word activation in GO appears to have a totally different meaning
in this context it is used  to indicate the 'initiation' of an enzyme activity

i.e
activation of MAPKK activity
The initiation of the activity of the inactive enzyme MAP kinase kinase (MAPKK)

This seems like a problem, is it?

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11118](https://sourceforge.net/p/geneontology/ontology-requests/11118)

**Comment by dosumis** [comment]
I suspect this just ended up on the wrong tracker - should have been a S.pombe phenotype term request.   Note - definition of activator terms being cleaned up as part of MF overhaul.
