### ISSUE TITLE
inter-chromosomal DNA recombination

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11299]
Need for GO term "inter-chromosomal DNA recombination" (PMID:18680205), unless it can be replaced by another GO term.

In definition of DNA recombination, it is written "Intrachromosomal recombination occurs by crossing over. " 

The definition of the children are not consistent with this:
- The term "GO:0035825 reciprocal DNA recombination, has exact synonym= chromosomal crossover; (which seem to mean it refers to "Intrachromosomal recombination"), however,  intraschromosomal also exists: GO:1990067 intrachromosomal DNA recombination
- There is no term for inter-chromosomal recombination. 

Reported by: cusin

Original Ticket: [geneontology/ontology-requests/11120](https://sourceforge.net/p/geneontology/ontology-requests/11120)

**Comment by pgaudet** [comment]
@ValWood @mah11 (any anyone else!) can you please have a look at this ? 
1. Is it correct that "Intrachromosomal recombination occurs by crossing over." ? I thought crossing over was interchromosomal (wikipedia refers to homologous chromosomes): 
https://en.wikipedia.org/wiki/Chromosomal_crossover

2. I propose to change the name of 'reciprocal DNA recombination'  (GO:0035825) to 'homologous recombination', with 'interstrand DNA recombination' 'interchromosomal DNA recombination' as EXACT synonyms, and 'reciprocal DNA recombination a narrow' synonym. 

3. I will also add an EXACT synonym 'intrastrand DNA recombination' to 'intrachromosomal DNA recombination'. 

Please let me know if that seems OK. 

Thanks, Pascale

**Comment by ValWood** [comment]
I agree that interchromosomal recomb is by crossing over.

I'm not sure what 'intra chromosomal recombination' is?
2 manual annotation from TAIR? @tberardini 

probably refers to processes like the recombination event which can occur at telomeres (but I'm never sure if these are really 'normal' processes'

**Comment by ukemi** [comment]
What about events that result in the excision of phage and things like that. I am pretty sure they happen by a recombination mechanism.

**Comment by ValWood** [comment]
maybe that is what it is for... transposition ...

**Comment by pgaudet** [comment]
Yes I think 'intra' is rare but legit.
