### ISSUE TITLE
diff between:  attachment of spindle microtubules to kinetochore and biorientation?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11307]
GO:0051315 - attachment of spindle microtubules to kinetochore involved in mitotic sister chromatid segregation 
Definition: "The cell cycle process in which spindle microtubules become physically associated with the proteins making up the kinetochore complex during mitosis. During mitosis, the kinetochores of sister chromosomes are situated facing opposite spindle poles and bipolar attachment of the sister chromosomes to the spindle occurs." [GOC:ai, GOC:clt, GOC:dph, GOC:tb]

and
 GO:0031134 - sister chromatid biorientation  [QuickGO, AmiGO, BioPortal]

Definition: "The cell cycle process in which sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles." [PMID:15309047]

sound the same?

GO:0051315 is a parent of GO:0031134

If anything, GO:0031134 seems broader as there is probably more to biorientation than attachment?, anyway the current defs sound almost identical?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11129](https://sourceforge.net/p/geneontology/ontology-requests/11129)

**Comment by mah11** [comment]
duplicates #11674
