### ISSUE TITLE
Should "protein peptidyl-prolyl isomerization" have some link to "protein folding" ? 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11302]
Hello, 

It sounds like "protein peptidyl-prolyl isomerization" should have some link to "protein folding" ? It sounds like it: 
http://en.wikipedia.org/wiki/Prolyl_isomerase

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: [geneontology/ontology-requests/11123](https://sourceforge.net/p/geneontology/ontology-requests/11123)

**Comment by ValWood** [comment]
protein peptidyl-prolyl isomerization
is not always folding. can occur during conformational changes I believe.
