### ISSUE TITLE
new term request for FXYD family protein binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11309]
FXYD family protein  binding

Interacting selectively and non-covalently with any protein from the FXYD protein family, a family of small membrane proteins that share a 35-amino acid signature sequence domain, beginning with the amino acid sequence PFXYD and containing 7 invariant and 6 highly conserved amino acids. The FXYD family proteins are tissue-specific auxiliary subunits of the Na,K-ATPase, the principal enzyme
responsible for maintaining the distribution of Na and K ion concentrations across animal cell membranes.

is a GO:0005515 protein binding

PMID: 16403837
PMID: 10950925
PMID: 18000745

Reported by: mikerice7

Original Ticket: [geneontology/ontology-requests/11131](https://sourceforge.net/p/geneontology/ontology-requests/11131)

**Comment by ValWood** [comment]
Hi,

Can you annotate the bound protein in the with field. I don't think we are adding 
new protein family terms?
Val
