### ISSUE TITLE
MP: formation of translation initiation complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11300]
The way this is defined

Joining of the large subunit, with release of IF2/eIF2 and IF3/eIF3. This leaves the functional ribosome at the AUG, with the methionyl/formyl-methionyl-tRNA positioned at the P site.

it could be housed under GO:0002183 cytoplasmic translational initiation

(also some of the siblings)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11121](https://sourceforge.net/p/geneontology/ontology-requests/11121)

**Comment by ValWood** [comment]
Following  up on this,  so you don't need to go through the thread, all this requires is to make

GO:0001731 part_of  GO:0002183

v

**Comment by dosumis** [comment]
> GO:0001731 part_of GO:0002183

OK.  Have done this. 

Still feels like it should have something in the comment at least to make it clear why it belongs here and not on general term.  Closing anyway, but will add if you suggest something.

Ta,
david

**Comment by ValWood** [comment]
Well the def is describing the cytoplasmic TIC assembly

so why not just make:
014-09-24	Added	SYNONYM	cytoplasmic translation initiation complex assembly (exact)

the primary term name. No confusion then....
