### ISSUE TITLE
ntr's for T cell meandering migration

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11310]
Hi,

I am trying to annotate the role of Myo1g from PMID:25083865.

They show that Myo1g is involved in controlling "turning" during T cell meandering motility. I have currently annotated it to "T cell migration", but I would really like to represent that it specifically controls when the T cells turn to produce meandering motility.

Based on this paper, I have some ideas, but also some questions about appropropriate parentage for one term.

Here's what I'm thinking, but very open to suggestions for improvement; this is definitely not an area of strength for me.

GO:new - "T cell meandering migration"
is_a: GO:0072678 - "T cell migration"
exact synonym: "T cell meandering search"
??? synonym (type?): "lymph node surveillance"
def: The random-like motility pattern observed for T cells in lymph nodes to identify foreign peptides presented by major histocompatibility complex (MHC) molecules on antigenpresenting cells (APCs).
def_dbxref: 

GO:new - "T cell turning"
is_a: ??? not sure what would be an is_a parent, 
- perhaps it could go under "directional locomotion"?
  part_of: GO:new - "T cell meandering migration"
  def: The cell-intrinsic turning, aka change in direction, of a T cell, such as occurs during meandering search within the lymph node.

thanks,

-Karen

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/11132](https://sourceforge.net/p/geneontology/ontology-requests/11132)

**Comment by ValWood** [comment]
Closing, seems as though no action is required?

**Comment by ValWood** [comment]
@krchristie   reopen if anything to do

**Comment by krchristie** [comment]
Actually, it looks to me like the summary was 

Add this term:
> GO:new - "T cell meandering migration"
> is_a: GO:0072678 - "T cell migration"
> exact synonym: "T cell meandering search"
> ??? synonym (type?): "lymph node surveillance"
> def: The random-like motility pattern observed for T cells in lymph nodes to identify foreign peptides presented by major histocompatibility complex (MHC) molecules on antigenpresenting cells (APCs).
> def_dbxref:

but not this one: 
> GO:new - "T cell turning"
> is_a: ??? not sure what would be an is_a parent,

@addiehl correct me if I misunderstood your comment.

**Comment by addiehl** [comment]
Karen,
I agree with your summary:
Add this term:  GO:new - "T cell meandering migration"
But not this one:  GO:new - "T cell turning"

-- Alex

**Comment by krchristie** [comment]
@addiehl - Thanks for confirming. Incorporating your suggestions into the definition, this is what I will put in:

GO:new - "T cell meandering migration"
is_a: GO:0072678 - "T cell migration"
exact synonym: "T cell meandering search"
related synonym: "lymph node surveillance"
def: "The random-like motility observed for T cells in lymph nodes which enhances surveillance of antigens presented by major histocompatibility complex (MHC) molecules on antigen presenting cells (APCs)." 
def_dbxref: GOC:krc, GOC:add, PMID:25083865

**Comment by krchristie** [comment]
reopening so I remember to go back and use this term for annotation of Myo1g

**Comment by krchristie** [comment]
annotation for Myo1g updated so can close
