### ISSUE TITLE
suggest obsoletion :  mitochondrial nucleoid organization involved in mitochondrial fission

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11326]
I don't think this term makes sense?
The fission is involved in nucleoid organization, not the other way around?
It has no annotations......

A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the mitochondrial nucleoid that contributes to mitochondrial division.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11151](https://sourceforge.net/p/geneontology/ontology-requests/11151)

**Comment by ukemi** [comment]
I think it is an ok term. Have a look here: PMID:20014006, PMID:25288115, PMID:24429632, PMID:17362197. It looks like it is a bit of a chicken and egg problem, but in mitochondria, the nucleoid reorganizes by some kind of interaction with the ER to go to the tips of the mitochondria before division. Maybe not a part of division? I'm not sure. Does it hurt to keep it?

**Comment by ValWood** [comment]
OK, yep. I think we discussed this in another ticket...
