### ISSUE TITLE
propose obsoletion GO:0072692 chromatin silencing at centromere central core

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11322]
Can we obsolete this term, I think I requested it but it was a mistake

GO:0072692 chromatin silencing at centromere central core

there is not "silencing" at the core. It is sometimes assayed, but inserting a reporter gene, but essentially this is the region under the kinetochore so there  are no genes here, and no biological mechanism to "silence" them (i.e the RNAi based heterochromatin assembly occurs at the centric/pericentric regions).

And to corroborate this, it has no annotations

val 

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11147](https://sourceforge.net/p/geneontology/ontology-requests/11147)

**Comment by ukemi** [comment]
Maybe these terms should really be chromatin organization? 

chromatin silencing at centromere central core -->chromatin organization at centromere central core
Maybe for all of these centromere terms, this should be the case?

**Comment by ValWood** [comment]
For the core, I think yes.
There is transcription at the non core regions (which is required for heterochomatin formation). I don't think there is normally 'functional' transcription in the central core.

I changed  the go annotation  to CENP-A containing chromatin origanization.

**Comment by ukemi** [comment]
OK. I will change the core term to organization. OK?

**Comment by ValWood** [comment]
Its only this term...obsolete?
I annotated to CENP-A containing chromatin origanization instead.
Silencing at the centromere still exists, but not in the core.

**Comment by ukemi** [comment]
OK. I will wait until all the updates are done and there are no more annotations. Then I will obsolete.

**Comment by ValWood** [comment]
Its OK for us if you do it now.....( The update with this fix from us will be quite a while).
Val

**Comment by ukemi** [comment]
Dear all,

The proposal has been made to obsolete the following term:

GO:0072692 chromatin silencing at centromere central core

The reason for obsoletion is that the process does not exist.

All details here:
https://github.com/geneontology/go-ontology/issues/11322

There are no experimental annotations to this term.


We are opening a comment period for this proposed obsoletion. We'd like to
proceed and obsolete the terms above on November 24, 2016.

*** Unless objections are received by November 24, 2016, we will assume
that you agree to this change. ***

Best,

-David Hill

**Comment by ukemi** [comment]
Made this term obsolete.
