### ISSUE TITLE
query, structural molecule activity, protein complex scaffold, clarification

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11331]
Hi,

I was querying an annotation with SGD, where a chaperone, which is not part of the final complex is annotated to "protein complex scaffold"

I always assumed this  was for subunits  which complexes were assembled onto. Especially as it is a child of structural molecule activity.

However, the def is not clear:
protein complex scaffold
Definition  Functions to provide a physical support for the assembly of a multiprotein complex.
(note that all the siblings are "structural constituent of...")

Also the parent:
structural molecule activity:
The action of a molecule that contributes to the structural integrity of a complex or assembly within or outside a cell.

Here what does "assembly" refer to? I assume this refers to some macromolecule and not the assembly of the complex itself?

v

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11156](https://sourceforge.net/p/geneontology/ontology-requests/11156)

**Comment by pgaudet** [comment]
Hi @ValWood 
Do you have a suggestion for a new definition ? 
I think @ukemi and @sabrinatoro looked at MAPK-scaffold activity childs and decided to keep the term. 

Thanks, Pascale

**Comment by RLovering** [comment]
This situation was discussed in the signaling meeting last year so you might be able to find more information about why the term is required - if that helps

**Comment by pgaudet** [comment]
@ValWood 
The term label was changed  #13593

Hopefully this is clearer. Please reopen with a clear suggestion if this did not address your concern. 

Thanks, Pascale

**Comment by Antonialock** [comment]
FeS clusters are assembled onto ISCU
If I remember right a conformational change is induced in ISCU, which I think facilitates onwards transfer of the cluster. I have annotated pombe ISCU to 'molecular adaptor activity'

**Comment by ValWood** [comment]
The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way.

So what is binding to what here?


this sounds more like

iron-sulfur transferase activity contributes_to?

**Comment by Antonialock** [comment]
We've gone off on a tangent with this Val from the original ticket. Will take this to our internal tracker.
