### ISSUE TITLE
relationship between 2 terms threonylcarbamoyladenosine

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11343]
both of these are defined as modifications, but they aren't related. 

mitochondrial tRNA threonylcarbamoyladenosine modification 
The attachment of a carbonyl group and a threonine to the amino group of the adenine residue immediately 3' of the anticodon, in tRNAs that decode ANN codons (where N is any base). 

threonylcarbamoyladenosine biosynthetic process 
The chemical reactions and pathways resulting in the formation of threonylcarbamoyladenosine, a modified nucleoside found in some tRNA molecules. 

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11168](https://sourceforge.net/p/geneontology/ontology-requests/11168)

**Comment by ValWood** [comment]
Hi Harold. What's the  final solution here?
Thanks,
Val

**Comment by ValWood** [comment]
Pinging @hdrabkin  again

**Comment by ValWood** [comment]
Ooh ooh, this one  done!
