### ISSUE TITLE
OTR:GO:0008527 taste receptor activity 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11346]
GO:0008527 taste receptor activity 

This term is a child of "GO:0004930 G-protein coupled receptor activity"
And has the synonym "gustatory receptor"

There are a lot of fly gustatory receptor genes annotated with taste receptor activity .... but although they have a 7TM domain they are not GPCRs. PMID:19660932.

From a quick glance, most of these annotations are quite old and may reflect that fly Gr's were one thought to be GPCRs or that taste receptor activity was made a child of GPCR activity because the mammalian taste/gustatory receptors are GPCRs - a bit of both I suspect, looking at the log.

I guess there are two options:

1. A new term the describing non-GPCR taste receptor activity (contact chemoreception is a term often used in insects);
2. Placing taste receptor under the more general term "GO:0004888 transmembrane signaling receptor activity" - good for fly, but probably not good for everyone else who'll lose GPCR activity ancestry.

I'll defer to you.

Thanks,
Helen

Reported by: hattrill

Original Ticket: [geneontology/ontology-requests/11171](https://sourceforge.net/p/geneontology/ontology-requests/11171)

**Comment by tberardini** [comment]
@hattrill

**Comment by tberardini** [comment]
@hattrill: Well, there was a resounding silence in response to my email almost a year ago.  I guess we will proceed with this plan:

"leave the current term [GO:0008527 taste receptor activity ] defined as is, move it up to 'GO:0004888 transmembrane signaling receptor activity' and create two new children terms, one that will go under GPCR  [GPCR taste receptor activity, GO:new1, is a child of "GO:0004930 G-protein coupled receptor activity"] and [contact chemoreceptor activity? or contact chemosensation receptor activity?, GO:new2]. We'd need to figure out where the current children (bitter, sweet, sour, salty, umami) would fall under these two new child terms and whether GPCR and non-GPCR children are necessary for those (example, bitter GPCR and bitter non-GPCR). "

We could leave all the children directly under 'taste receptor activity' .  It looks like bitter and sweet should have a GPCR variant.  

I propose something like this:

transmembrane signaling receptor activity
--[i] taste receptor activity
----[i] contact chemoreceptor activity, GO:new2
----[i] GPCR taste receptor activity, GO:new1
------[i] GPCR bitter taste receptor activity, GO:new3
------[i] GPCR sweet taste receptor activity, GO:new4
------[i] umami taste receptor activity
----[i] bitter taste receptor activity
------[i] GPCR bitter taste receptor activity, GO:new3
----[i] salty taste receptor activity
----[i] sour taste receptor activity
----[i] sweet taste receptor activity
------[i] GPCR sweet taste receptor activity


G-protein coupled receptor activity
--[i] GPCR taste receptor activity, GO:new1
----[i] GPCR bitter taste receptor activity, GO:new3
----[i] GPCR sweet taste receptor activity, GO:new4
----[i] umami taste receptor activity


also:

    add 'chemoreception' as synonym for 'detection of chemical stimulus'

What do you think?  Yes, it's been ages.

**Comment by hattrill** [comment]
Hi Tanya. Better late than never - I was just thinking about this the other day, so good timing! Your solution looks sound and certainly workd for me!

Helen

**Comment by tberardini** [comment]
Proposed defs:

GPCR taste receptor activity: A G-protein coupled receptor activity that is responsible for the sense of taste.

GPCR bitter taste receptor activity: A G-protein coupled receptor activity that is responsible for the sense of bitter taste.

GPCR sweet taste receptor activity: A G-protein coupled receptor activity that is responsible for the sense of sweet taste.

contact chemosensation receptor activity: A transmembrane signaling receptor activity that is responsible for contact chemosensation.
@hattrill: do you like this term name?  something better?

I'm not entirely clear on the link between 'chemoreception' and 'detection of chemical stimulus'.  What type of synonym?  Is 'chemoreception' specific to 'tasting'?  If so, then should we add the synonym to 'detection of chemical stimulus involved in sensory perception of taste' instead?  Should 'contact chemosensation' be a synonym of the same term? 'contact chemoreception'?

I'm trying to hammer out the details so that I can sit down in a mega editing session and get this all done tomorrow.

Thanks for your help.

**Comment by cmungall** [comment]
Interesting article on evolution of taste receptors in vertebrates, and convergent evolution of sweet taste reception in hummingbirds: http://evolution.berkeley.edu/evolibrary/news/140903_hummingbirds

This would be relevant if we do a coordinate pass at PAINT annotation while working on this part of the ontology

**Comment by hattrill** [comment]
Hi Tanya,
Sorry, I managed to miss your questions before.

I prefer "contact chemoreceptor activity", with "contact chemosensation receptor activity" as the synonym. (purely based on frequency of use)

Perhaps the definition should spell out the key distinction - that this is a non-GPCR signalling mechanism.
Def: A non-GPCR transmembrane signaling receptor activity that is responsible for contact chemoreception.

Chemoreception covers any detection of chemical stimulus - i.e. odorant (volatile) and gustatory/taste (non-volatile). 

"taste receptor activity" has the synonym "gustatory receptor", which is a good thing. While we use the term "taste", it would be good to keep in mind that this covers the detection of non-volatiles such as contact chemoreception of pheromones and well as yummy things.

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090681
+name: GPCR taste receptor activity
+namespace: molecular_function
+def: "A G-protein coupled receptor activity that is responsible for the sense of taste." [GOC:hat, GOC:tb]
+synonym: "G-protein coupled taste receptor activity" EXACT []
+is_a: GO:0004930 ! G-protein coupled receptor activity
+is_a: GO:0008527 ! taste receptor activity


+[Term]
+id: GO:0090682
+name: GPCR bitter taste receptor activity
+namespace: molecular_function
+def: "A G-protein coupled receptor activity that is responsible for the sense of bitter taste." [GOC:hat, GOC:tb]
+synonym: "G-protein coupled receptor bitter taste receptor activity" EXACT []
+is_a: GO:0033038 ! bitter taste receptor activity
+is_a: GO:0090681 ! GPCR taste receptor activity

+[Term]
+id: GO:0090683
+name: GPCR sweet taste receptor activity
+namespace: molecular_function
+def: "A G-protein coupled receptor activity that is responsible for the sense of sweet taste." [GOC:hat, GOC:tb]
+synonym: "G-protein coupled receptor sweet taste receptor activity" EXACT []
+is_a: GO:0033041 ! sweet taste receptor activity
+is_a: GO:0090681 ! GPCR taste receptor activity

+[Term]
+id: GO:0090684
+name: contact chemoreceptor activity
+namespace: molecular_function
+def: "A non-GPCR transmembrane signaling receptor activity that is responsible for contact chemoreception." [GOC:hat, GOC:tb]
+synonym: "contact chemosensation receptor activity" EXACT []
+is_a: GO:0008527 ! taste receptor activity

Edited:
 name: umami taste receptor activity
-is_a: GO:0008527 ! taste receptor activity
+is_a: GO:0090681 ! GPCR taste receptor activity

name: taste receptor activity
-is_a: GO:0004930 ! G-protein coupled receptor activity
-intersection_of: GO:0004930 ! G-protein coupled receptor activity
+is_a: GO:0004888 ! transmembrane signaling receptor activity
+intersection_of: GO:0004888 ! transmembrane signaling receptor activity

name: detection of chemical stimulus
+synonym: "chemoreception" RELATED []
