### ISSUE TITLE
NTR: cytoplasmic t6A tRNA modification

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11347]
Hello GO Editors,

The term, 'mitochondrial tRNA threonylcarbamoyladenosine modification' (GO:0072670) seems to have been created for the yeast mitochondrial protein, Qri7, based on PMID:21183954. 

I need a more general term for tRNA threonylcarbamoyladenosine modification (t6A tRNA modification), based on PMID:21183954 and PMID:23258706. 

I need the term,'cytoplasmic tRNA threonylcarbamoyladenosine modification,' to annotate the proteins involved in the cytoplasmic t6A tRNA modifications described in the paper.

Thanks,

Diane

Reported by: dinglis

Original Ticket: [geneontology/ontology-requests/11172](https://sourceforge.net/p/geneontology/ontology-requests/11172)

**Comment by hdrabkin** [comment]
I would merge threonylcarbamoyladenosine biosynthetic process' into  tRNA threonylcarbamoyladenosine modification, since t6A is only made as a tRNA modification. 
I would also merge the mito  tRNA threonylcarbamoyladenosine modification into the more general  tRNA threonylcarbamoyladenosine modification. There is no difference in the two processes other than where they occur.

**Comment by ValWood** [comment]
Hi,

I would prefer that we keep the separate terms for the mitochondrial processes.
They are useful and there is a precedent throughout  the ontology for keeping the processes separate, we have done the same for every other tRNA modification.

See
![mito](https://user-images.githubusercontent.com/7359272/36072519-c8db2566-0f18-11e8-82b3-926b9a0f4208.jpg)

and you could make the same argument for mitochondrial DNA replication, translation etc.

I wouldn't mine if eventually these individual  terms were represented ONLY by functions 
in which case we could do:


tRNA U34 thiol-transferase activity part_of mitochondrial tRNA modification

but  we really need to keep these processes under mitochondrial gene expression. There may be no difference between these processes other than where they occur but this is important. They are controlled vey differently and the mitochondrial  modicfications have more in common from a modular perspective than mitochondrial and non mitochondrial tRNA modification.

see:
![slide1](https://user-images.githubusercontent.com/7359272/36072594-ecaacf40-0f19-11e8-94e7-93af0669cfa4.jpg)

**Comment by ValWood** [comment]
In fact, this difference showed up in an analysis I did for this paper
https://www.ncbi.nlm.nih.gov/pubmed/23697806
analysing phenotypes using GO.

The mitochondrial modification processes phenocopy each other. This would not be possible to show without these process terms. This is only a small portion of the table but you can see that the 19  genes involved in tRNA modification phenocopy each other and the non mitochondrial ones phenocopy each other.

![example](https://user-images.githubusercontent.com/7359272/36072654-229ef0a8-0f1b-11e8-9780-4b2490e0daf5.jpg)

Please keep them, they are different processes.

**Comment by srengel** [comment]
re cytoplasmic vs mitochondrial, i defer to Val.

**Comment by ValWood** [comment]
Should we close this?
It's really useful for modularity to have the separation between the mitochondrial and cytoplasmic processes ( these are especially useful for enrichment since  they are very separate).
Maybe in the future we will do this more cleverly, but for now all is working well....

**Comment by ValWood** [comment]
I would actually like to see cytosolic terms in the tRNA modification branch. Currently when describing  modules I need to do quite convoluted queries to tease these out sometimes. But this is a more general issue.
