### ISSUE TITLE
NTRs: ubiquitin ligase complex terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11376]
Hi,

I'd like to create several complex terms. These are all yeast (cerevisiae) complexes that are all ubiquitin ligases and are all children of GO:0019005, "SCF ubiquitin ligase complex".  

the terms are - with pmid, supporting the existence of the complex:

SCF-CDC4 ubiquitin ligase complex - pmid:9346238
SCF-Ctf13 ubiquitin ligase complex - pmid:14747994
SCF-DAS1 ubiquitin ligase complex - pmid:14747994
SCF-DIA2 ubiquitin ligase complex - pmid:14747994
SCF-GRR1 ubiquitin ligase complex - pmid:10213692
SCF-MDM30 ubiquitin ligase complex - pmid:14747994
SCF-MET30 ubiquitin ligase complex - pmid:9716410
SCF-RCY1 ubiquitin ligase complex - pmid:14747994
SCF-SAF1 ubiquitin ligase complex - pmid:11283612
SCF-SKP2 ubiquitin ligase complex - pmid:14747994
SCF-UFO1 ubiquitin ligase complex - pmid:14747994
SCF-YDR131C ubiquitin ligase complex - pmid:14747994
SCF-YDR306C ubiquitin ligase complex - pmid:14747994
SCF-YLR224W ubiquitin ligase complex - pmid:14747994
SCF-YLR352W ubiquitin ligase complex - pmid:19882662
SCF-HRT3 ubiquitin ligase complex - pmid:14747994

The definitions could be all the same:

"SCF ubiquitin ligase complex, in which the F-box protein is xxx" - where xxx is cdc4/ctf13/...

Thank you,
Janos

Reported by: jdemetert

Original Ticket: [geneontology/ontology-requests/11201](https://sourceforge.net/p/geneontology/ontology-requests/11201)

**Comment by ukemi** [comment]
I corrected the logical definition of the parent ligase term and added a logical definition for the ubiquitin conjugating enzyme complex.
