### ISSUE TITLE
dynein binding vs dynein complex binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11382]
compare text defs:

```
id: GO:0045502
name: dynein binding
def: "Interacting selectively and non-covalently with dynein, **the multisubunit protein complex** that is associated with microtubules." [GOC:bf]
is_a: GO:0005515 ! protein binding
```

and

```
id: GO:0070840
name: dynein complex binding
def: "Interacting selectively and non-covalently with a dynein complex, a protein complex that contains two or three dynein heavy chains and several light chains, and has microtubule motor activity." [GOC:BHF, GOC:mah]
is_a: GO:0032403 ! protein complex binding
intersection_of: GO:0005488 ! binding
intersection_of: has_input GO:0030286 ! dynein complex
```

The first def sounds like a complex. Consider instead:

def: "Interacting selectively and non-covalently with dynein, a motor protein that forms a multisubunit complex associated with microtubules." [GOC:bf, GOC:cjm, https://en.wikipedia.org/wiki/Dynein]

Also: add a logical def. Grouping class needs to be requested from PRO.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/11207](https://sourceforge.net/p/geneontology/ontology-requests/11207)

**Comment by pgaudet** [comment]
This comes up all the time. Can we have a proposal by the next GO meeting?

**Comment by pgaudet** [comment]
Rolling this up into Protein complex discussion.

**Comment by pgaudet** [comment]
Terms were merged 2018-02-18
