### ISSUE TITLE
possible children of "small molecule metabolism"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11389]
I was playing around with a "super slim" for a pombe paper I'm go-authoring. I noticed that w
the following processes did not slim to "small molecule metabolism"

Should they have this parentage?

D-xylose metabolic process, 
arabinose metabolic process, 
pyridoxal phosphate metabolic process, 
sorbose metabolic process

(not sure about this, but they seem to fie the def)

cheers

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11214](https://sourceforge.net/p/geneontology/ontology-requests/11214)

**Comment by ukemi** [comment]
Hi Peter and Val,

This works for me and since 'small molecule x' terms aren't axiomatized, it doesn't break an external heirarchy. It also doesn't seem to create problems itself. I have moved that monosaccharide metabolism and binding terms to be children of small molecules.

-D

**Comment by ValWood** [comment]
Looks good ;)
