### ISSUE TITLE
NTR insulin-like growth factor protein secretion

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11405]
Term: insulin-like growth factor protein secretion
Definition:  The regulated release of a member of the insulin-like growth factor family of proteins from a cell.  The insulin-like growth factor family is a complex system (often referred to as the IGF "axis") which includes two cell-surface receptors (IGF1R and IGF2R), two ligands (Insulin-like growth factor 1 (IGF-I) and Insulin-like growth factor 2 (IGF-2)), and a family of six high-affinity IGF-binding proteins (IGFBP-1 to IGFBP-6). From Wikipedia
is_a GO:0009306 protein secretion
PMID: 1280399 PMID: 1384804

I am unclear if the IGFs can be considered to constitute their own family, since the IGFBPs are termed a family and does IGFI and II fall under the super family of insulin?

Reported by: mikerice7

Original Ticket: [geneontology/ontology-requests/11230](https://sourceforge.net/p/geneontology/ontology-requests/11230)

**Comment by ukemi** [comment]
Hi Mike,

We recently decided not to make new x protein secretion terms. Can you use annotation extensions? This is the way to get the specificity you need.

-David
