### ISSUE TITLE
parent for release of sequestered calcium ion into cytosol and other terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11407]
Hi

I was wondering why many of the calcium ion transport terms (and maybe other ion transport terms) are not included under the transmembrane transport parents. For example

GO:0014808 release of sequestered calcium ion into cytosol by sarcoplasmic reticulum and GO:0060402 calcium ion transport into cytosol do not have GO:0097553 calcium ion transmembrane import into cytosol as a parent, but I would have thought transmembrane transport would occur.

At present having to annotate to both GO:0014808 release of sequestered calcium ion into cytosol by sarcoplasmic reticulum and GO:0097553 calcium ion transmembrane import into cytosol

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11232](https://sourceforge.net/p/geneontology/ontology-requests/11232)

**Comment by dosumis** [comment]
Fixed as part of general edits connected with synapse project.
