### ISSUE TITLE
cell motility query parentage

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11414]
Hi

I am not convinced that  GO:0048870 cell motility: Any process involved in the controlled self-propelled movement of a cell that results in translocation of the cell from one place to another. should be a child of  GO:0006928 cellular component movement: The directed, self-propelled movement of a cellular component without the involvement of an external agent such as a transporter or a pore.

I can see that in order for a cell to move cellular components will need to move but it just seems odd. 

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11239](https://sourceforge.net/p/geneontology/ontology-requests/11239)

**Comment by tberardini** [comment]
I can't think of a good way to augment the 'cellular component' definition to include cell.  If someone else has a flash of inspiration, please add it here. 

Have things progressed in other ontologies so that we could perhaps drop 'cell' from GO at this point in time?  @cmungall ?

**Comment by cmungall** [comment]
On 17 May 2016, at 17:13, Tanya Berardini wrote:

> I can't think of a good way to augment the 'cellular component' 
> definition to include cell.  If someone else has a flash of 
> inspiration, please add it here.
>
> Have things progressed in other ontologies so that we could perhaps 
> drop 'cell' from GO at this point in time?  @cmungall ?

Having a CL ID in GO will cause bioinformatics pipelines around the 
world to crash loudly. Sometimes forcing breakage is good to make sure 
people conform to the actual spec, but not really worth it here just for 
cell, when we can just obsolete the CL class instead

**Comment by dosumis** [comment]
Why does the CL ID have to be in GO?  As GO:cell has no SubClasses in GO, we can just obsolete it and import a relevant term.  This will be filtered out in everything but go-plus.owl.  So, we just need a suitable general term - one that encompasses encapsulating structures.  I could make sure the CARO def applies and make this the parent class to the one in CL...

**Comment by tberardini** [comment]
Thanks for input.  I was hoping that reviving discussion might spur a solution that was previously not possible. I think I understand what David is getting at but I'm not sure how to implement that solution.  There are more than a handful of experimental annotations directly to this term, not including annotations made by the BP-CC annotation inference pipeline.  They would have to be dealt with by the annotating databases if we obsoleted the GO:cell. 

<img width="788" alt="screen shot 2016-05-18 at 8 25 41 am" src="https://cloud.githubusercontent.com/assets/4998871/15364674/2da67b02-1cd2-11e6-82a6-268b15eeb39b.png">

**Comment by cmungall** [comment]
This is interesting, it looks like all those AgBase ones are proxies for tissue-specific gene expression smuggled in via annotation extensions. If they could coordinate with Bgee they may be able to ditch these.
 
Without smuggled anatomy:

<img width="1273" alt="screen shot 2016-05-18 at 9 09 02 am" src="https://cloud.githubusercontent.com/assets/50745/15366264/5cac14a6-1cd8-11e6-9e3b-b1fd6825f92d.png">

It's looking more doable, and I'm coming round to @dosumis POV. We should also check that go-basic doesn't end up looking odd with GO:cell gone

**Comment by ValWood** [comment]
the original issue pointed out by @RLovering has gone away.
Anything else to do here?
