### ISSUE TITLE
Rubidium Biological Role?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11416]
I just came across some terms that I am suspicious of. 

rubidium ion transmembrane transporter activity

negative regulation of rubidium ion transmembrane transporter activity
negative regulation of rubidium ion transport
positive regulation of rubidium ion transmembrane transporter activity
positive regulation of rubidium ion transport
regulation of rubidium ion transmembrane transporter activity
regulation of rubidium ion transport
renal rubidium ion absorption
renal rubidium ion transport
rubidium ion transport 

From what I can tell, rubidium ion is often used to measure transport (86Ru uptake).
It is used as a measure of K+ transport I think. So these terms are about an assay and not a true biological function and process...? We have 11 annotations to the processes, but across the GOC, maybe around 84 non-iea to processes, around 8 to the activity terms. 
Should these be fixed and the terms obsoleted? I have a feeling this has been addressed in the past.

Reported by: hdrabkin

Original Ticket: [geneontology/ontology-requests/11241](https://sourceforge.net/p/geneontology/ontology-requests/11241)

**Comment by ValWood** [comment]
This was the other ticket I found earlier that was easy...
obsolete!
