### ISSUE TITLE
OTR: cell migration terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11433]
Action item from last ontology call 
(http://wiki.geneontology.org/index.php/Ontology_meeting_2014-10-09#TG_template_for_.27cell_migration.27):

"TG template for 'cell migration'
What is the most appropriate relation to use? See email thread '[go-ontology] cell migration templates'
Mix of 'has_input,' 'results in movement of,' and 'RO:0002313 transportsormaintainslocalizationof'.
Action items: Check what UniProtKB has used in annotation extension, MGI uses 'results in movement of', 

[this is the action item for me:]
_update ontology to replace 'has_input' with 'results in movement of' in the 'cell migration' children terms._

Heiko to change relationship type in TermGenie for this template."

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/11258](https://sourceforge.net/p/geneontology/ontology-requests/11258)

**Comment by mcourtot** [comment]
Updating relations was done. Ticket was left open for a review of logical axioms on cell migration terms which seems low priority at this stage, thus closing. Please open distinct ticket (possibly label as mini-project) if desired.
