### ISSUE TITLE
protein deneddylation/ cullin deneddylation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11438]
would anybody object if these terms were merged?
We don't have corresponding substrate specific terms for neddylation (or any of the other conjugations), and it wouldn't really be practical to add them ....

(can be better captured with annotation extensions) 

v

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11263](https://sourceforge.net/p/geneontology/ontology-requests/11263)

**Comment by dosumis** [comment]
Merged
