### ISSUE TITLE
NTR: CD4 and CD8-positive (CD4+, CD8+) T cell-related GO terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11431]
Hi,

The authors in PMID: 24187568 report that:
"We did observe that blocking PD-L1 decreased the proportion of early apoptotic (Annexin V+ 7-AAD-) CD8+ T cells, 7 days after exposure to the H1N1 virus (Figures 2(d) and 2(f)). CD4+ T cells did not show any significant differences in apoptosis after PD-L1 blocking (Figure 2(e))"

I could find the GO:0006924: "activation-induced cell death of T cells". Would it be possible to add "activation-induced cell death of CD4-positive T cells" and 
"activation-induced cell death of CD8-positive T cells"?

Thanks,
Penelope

Reported by: pgarmiri

Original Ticket: [geneontology/ontology-requests/11256](https://sourceforge.net/p/geneontology/ontology-requests/11256)

**Comment by paolaroncaglia** [comment]
@dosumis 
I'll take this one if you don't mind ;-) as it's apoptosis stuff
[Note for self: this was ported over from SF so Penelope may need to be added to conversation]

**Comment by dosumis** [comment]
@paolaroncaglia - Thanks!  
Ideally they'd be linked to appropriate CL terms - but it seems there are no generic CD4 and CD8+ T cell terms.  Might want to ask for these on CL tracker.

**Comment by paolaroncaglia** [comment]
Cheers, will do and will post link to CL ticket here, when I get round to this.

**Comment by paolaroncaglia** [comment]
Hi @mcourtot and @zebrafishembryo
(can't find a GitHub username for Penelope)

GO:0006924 "activation-induced cell death of T cells" is defined as being this specific pathway:
“A T cell apoptotic process that occurs towards the end of the expansion phase following the initial activation of mature T cells by antigen and is triggered by T cell receptor stimulation and signals transmitted via various surface-expressed members of the TNF receptor family such as Fas ligand, Fas, and TNF and the p55 and p75 TNF receptors.”.
Looking at section 3.2 in PMID:24187568 (i.e. where the sentences quoted by Penelope are found), I’m not 100% sure that the PD-L1 Signaling described there is exactly GO:0006924. By comparing with the sibling term GO:0070238 “activated T cell autonomous cell death” defined as 
“A T cell apoptotic process that occurs towards the end of the expansion phase following the initial activation of mature T cells by antigen via the accumulation of pro-apoptotic gene products and decrease in anti-apoptotic gene products.”
my point is that it looks like there are not enough details in the paper about the specific signalling to be sure about what term to use. I could be wrong though - I’m not an immunologist and I didn’t have a chance to read the full paper. I’d suggest to annotate to the existing term GO:0070231 “T cell apoptotic process” or regulation thereof. Note that terms specifically for CD4 and/or CD8 apoptotic process may be requested via the TermGenie template “cell_apoptotic_process”. There are various options of cell ontology terms to choose from there. (If the appropriate cell ontology (CL) term is missing, that needs to be requested on the CL tracker.) Of course, regulation terms, if needed, may also be requested via TG.

Agreed with Melanie that I’ll mention her and Aleks in this ticket to look into annotations.
The ontology side is dealt with. I’m setting the ticket to pending; can be closed once annotations are made.
Thanks,

Paola

**Comment by addiehl** [comment]
The reason there are no "generic" CD4+ and CD8+ T cells in the CL, is that when immunologists experiment on and report information about these cell types, they are using shorthand for what we call in the CL 'CD4-positive, alpha-beta T cell' (CL:0000624) and 'CD8-positive, alpha-beta T cell' (CL:0000625).

95% of T cells in the blood are either 'CD4-positive, alpha-beta T cell' or 'CD8-positive, alpha-beta T cell', and alpha-beta T cell always bear CD4 or CD8.  The remaining T cells are gamma-delta T cells (they bear the gamma-delta T cell receptor), and only a small fraction of gamma-delta T cells co-express CD4 or CD8.  Unless they are specifically studied, most immunologists ignore their presence and use CD4 and CD8 as proxy markers for 'CD4-positive, alpha-beta T cell' and 'CD8-positive, alpha-beta T cell', respectively and report their data in the belief they are studying these cell types.  They have been doing so for nearly 30 years in thousands and thousands of published papers, and this biology is considered extremely well settled.

The CL is not going to introduce generic CD4+ or CD8+ T cell terms, for this very reason.

Best regards,
Alex

**Comment by paolaroncaglia** [comment]
Thanks Alex!

**Comment by cmungall** [comment]
Why not add, immediately obsolete, then point to this ticket or a FAQ, 
this comes up a lot I think

**Comment by paolaroncaglia** [comment]
Hi @cmungall ,
"Why not add, immediately obsolete, then point to this ticket or a FAQ,
this comes up a lot I think"
Because life is, really, far too short. Sorry. :-) I changed the title of this ticket to
"NTR: CD4 and CD8-positive (CD4+, CD8+) T cell-related GO terms"
so that it can come up more easily when searching the GitHub ontology tracker. I hope this is an acceptable compromise.

@mcourtot , 
Would it be ok with you if I assigned you this ticket? As agreed, looking at annotations is not a priority, and the ticket is labeled 'pending', but I don't really have anything else to contribute. Thanks!

**Comment by cmungall** [comment]
I meant in CL

**Comment by paolaroncaglia** [comment]
Ah, that's for @addiehl then :-)

**Comment by paolaroncaglia** [comment]
Assigning to Melanie to look into the annotations; labelled as low priority.
Ticket can be closed then, thanks.

**Comment by mcourtot** [comment]
Hi @paolaroncaglia - I don't see any annotation to GO:0006924 from PMID:24187568
Am I looking at the wrong thing?

**Comment by paolaroncaglia** [comment]
Hi @mcourtot 
PMID: 24187568 is the paper for which Penelope requested terms that we then evaluated should not be added. Instead, we suggested to annotate PMID: 24187568 using the existing term GO:0070231 “T cell apoptotic process” or regulation thereof.
Thanks for looking into this!

**Comment by mcourtot** [comment]
Ok - thanks! Penelope will be back from vacation next week so I'll make a note to have her look at this.

**Comment by mcourtot** [comment]
Both @paolaroncaglia and Penelope confirmed this was all done.
