### ISSUE TITLE
separase-securin complex GO:1990520

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11447]
Added through TermGenie FF:

[Term]
id: GO:1990520
name: separase-securin complex
namespace: cellular_component
def: "A protein complex that includes separase and securin as components and that inhibits chromosome separation at mitosis." [GOC:vw, GOC:dos, PMID:8978688]
synonym: "Cut1-2 complex" EXACT [PMID:8978688]
is_a: GO:0043234 ! protein complex
created_by: vw
creation_date: 2014-10-23T10:34:52Z

The functional part of the definition seems at odds with http://en.wikipedia.org/wiki/Separase

Perhaps add some more context/detail for clarification?

Would also be good to formalise the link to process.  Based on the wikipedia entry this seems reasonable

relationship: capable_of_part_of chromosome separation

But seems at odds with assertion about function.

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/11272](https://sourceforge.net/p/geneontology/ontology-requests/11272)

**Comment by ValWood** [comment]
This seems really quick:

Action
capable_of  negative regulation of mitotic sister chromatid separation 

Revised def:

A protein complex that includes separase (a protease which  cleaves cohesin as part of  mitotic sister chromatid separation)  and securin,  a protease inhibitor.  Mitotic sister chromatid separation is inhibited until securin is  degraded by the Anaphase Promoting Complex
