### ISSUE TITLE
query  positive regulation of transcription on exit from mitosis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11458]
This term name sounds (from the term name) like it refers to transcription  after exit from mitosis. If this is the case it should not be "part of" mitotic exit....
If it is part_of, the term name should be changed to "involved in"

GO:0007072
Definition	Any process that increases the frequency, rate or extent of transcription as the cell leaves M phase. M phase is the part of the mitotic cell cycle during which mitosis and cytokinesis take place.

(there are only 3 experimental annotations, all SGD)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11283](https://sourceforge.net/p/geneontology/ontology-requests/11283)

**Comment by ValWood** [comment]
Yep I just looked at one of the papers. It is "involved in"

**Comment by ukemi** [comment]
OK. Changed term names.
