### ISSUE TITLE
question GO:0006488 dolichol-linked oligosaccharide biosynthetic process parentage

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11452]
Does
GO:0006488 dolichol-linked oligosaccharide biosynthetic process
have any biological roles other than
GO:0006487	protein N-linked glycosylation

These exact synonyms imply not:

N-linked glycan precursor biosynthesis [PMID:8666161]
N-linked glycan precursor biosynthetic process [PMID:8666161]

in which case can the parentage can be added

(or specific children)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11277](https://sourceforge.net/p/geneontology/ontology-requests/11277)

**Comment by ValWood** [comment]
maybe we can close this one? It is just directly upstream of"? I'll close....
