### ISSUE TITLE
MP GO:0001731 formation of translation preinitiation complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11467]
based on this comment

See also the cellular component terms 'eukaryotic 43S preinitiation complex ; GO:0016282', 'eukaryotic 48S initiation complex ; GO:0033290', and their children.

should this term
GO:0001731 formation of translation preinitiation complex

have cytoplasmic translation initiation parent?

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11292](https://sourceforge.net/p/geneontology/ontology-requests/11292)

**Comment by ValWood** [comment]
This just needs the "translation initiation" parent adding?

**Comment by ValWood** [comment]
closing as its a duplicate of
https://github.com/geneontology/go-ontology/issues/11300
which is assigned to @dosumis
