### ISSUE TITLE
cell proliferation query and discussion

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11478]
Hello,
As many of you might know, Dictyostelium typically ‘grows’ by cells dividing, once it starts developing, no further growth happens.  Since ‘cell growth’ is restricted to gaining mass and size, we started many years ago annotating involved genes with 'GO:0008283 cell proliferation', typically by IMP. 
The definition also seems just fine "The multiplication or reproduction of cells, resulting in the expansion of a cell population”.
However, I wanted to annotate again to this term after a longer while, and I was surprised to read the comments: 

“…. Also note that this term is intended to be used for the proliferation of cells within a multicellular organism, not for the expansion of a population of single-celled organisms.”
Thus, this part of the comment suggests we should NOT use this term for Dicty. Currently we have 40 annotations to the term. Questions:
1) Why is this restriction in the comment? Is there a reason to exclude single cell organisms? 
2) If there is a reason to exclude organisms like Dicty from this term, what is the term that we should use (it should be linked in above comment!)? 
I had a thought about ‘GO:0051301cell division’, but don’t particularly like it. Dicty researchers always call it ‘ growth', we made it ‘proliferation’ as this is not such a difference. However, calling it 'cell division', while this is a parent of cytokinesis, will undoubtedly suggest ‘ ytokinesis', a process often investigated in Dicty.; it doesn’t seem a suitable term describing such a broad phenomenon people look at, the basic growth of the population.
3) Do we need a new term and what could it be? 
Thanks!
Petra

> Hi Petra,
> 
> The rationale for this was that If you try to define "proliferation" at the single celled level  you always end up describing a "population phenotype" rather than a specific cellular process. We made this restriction to prevent this term being used to capture inviability phenotypes, of for capturing things like slow growth which are really only phenotypes in single celled organisms, and probably not suitable for GO  annotation (i.e we knocked out this gene and we don't know what it does but the cells no longer proliferate/ proliferate more slowly)
> 
> If  this was a general "cell proliferation" term it would need to  have  some relationship to cell growth and mitotic division terms  which would be complicated to model

> > DOS interjected:

Need to careful very careful about entangling growth,  division and control of cell size  - they are generally coupled but separable.   For example, phenotype-wise, you can get an increase in cell proliferation without increased growth if cells divide at a smaller size.

> ( the cell proliferation grouping term has no children at the moment other than those to capture the specific multicellular cell-type specific population expansions). For illustration in yeast or bacteria the majority of  gene products are involved in   some aspect of proliferation (for example all of gene products related to DNA replication, core transcription, cell cycle, cytokinesis, most metabolism, etc)  but PomBase and SGD do not use this term in annotation at all.
> 
> ..... if still need a proliferation term could you open a SF ticket that we could track? Maybe one could be created which still excludes  annotation of a "general" proliferation of a single-cell. If not, the alternative is to remodel the  ontology  to ensure that any general "cell proliferation" term inherits annotations correctly from "mitotic cell cycle" and "cell growth", or however it is eventually defined.
> 
> I had a look at  a few of the abstracts, and some seemed to be describing more rapid cell proliferation at the population level, so the individual cells must be growing faster. So perhaps the cellular level process is  “positive regulation of cell growth" and fits with "Dicty researchers always call it ‘ growth'" (although I don't really understand the biology fully enough....).
> 
> Val

Thanks Val and David,
I agree that this term is kind of high level and a phenotype, and usually we annotate in GO when there is no other process to annotate and not much else known. That’s why I haven’t used it in a while. Dicty people usually test the growth rate because it’s very easy to do and a quick first assessment of a new mutant.  As phenotypes, we have "decreased / increased growth rate”.
I see the complications in restructuring this in the GO, and I’m also not sure about "negative/positive regulation of cell growth” as this seems too specific for what people really look at. But maybe it depends on each individual case and which gene(s) are mutated, need to look into it.
I’ll also have to mull it over with Bob, if we really need a term, or if not, what to do with the 40 existing annotations. There’s obviously no hard check on them (yet).
Thanks again for the discussion,
Petra

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11303](https://sourceforge.net/p/geneontology/ontology-requests/11303)

**Comment by dosumis** [comment]
@pfey03 you wrote: "Right, this ticket is still open, though for me it's a "closed matter". Back in December we changed all our annotations to "asexual reproduction". Since cell proliferation is already taxon restricted I guess just the Def should get updated to something reflecting the restriction."

Assuming from this that no action is required.  Please re-open if I'm wrong.  (I seem to have ended up with this ticket based on a brief interjection in an email conversation and to have nothing to do with it since!).
