### ISSUE TITLE
OTR: scope of GO:0005215 ! transporter activity and its children

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11477]
GO:0005215 ! transporter activity is defined as: 
Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells.

This definition seems to include activities that move anything, whether or not a biological membrane is crossed. Based on the absence of child term for things like microtubule-directed motor activities or terms related to actin filaments, it seems to me that this was not the intent of this term.

I'm guessing that crossing membranes was omitted to have an umbrella term that includes transport across a nuclear pore. 

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/11302](https://sourceforge.net/p/geneontology/ontology-requests/11302)

**Comment by ukemi** [comment]
Yes. The umbrella term was created to describe non-transmembrane transporters. This would also include things like lipid transporters. I don't think this term was meant to include motors.
