### ISSUE TITLE
New term request: acid sphingomyelinase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11480]
The Wikipedia entry on http://en.wikipedia.org/wiki/Acid_Sphingomyelinase
explains that the pH with optimal conditions is gives the name. I was just
aware of the acidic having a separate inhibitor from the neutral, which to
me indicated the demand for a separate GO term. I suggest
acidic sphingomyelin phosphodiesterase activity
as a specialisation of
GO:0004767: sphingomyelin phosphodiesterase activity
and propose to also add "neutral" and possibly also "alkaline" as a separate classes. The prior is currently a synonym of 4746. The annotation of UniProt entry
http://www.uniprot.org/uniprot/P17405
should eventually be updated and there is ample of literature to it, just perform a pubmed search as in 
http://www.ncbi.nlm.nih.gov/pubmed/?term=acidic+sphingomyelinase
A synonym may be aSMase activity.

Cheers,

Steffen

Reported by: smoe

Original Ticket: [geneontology/ontology-requests/11306](https://sourceforge.net/p/geneontology/ontology-requests/11306)

**Comment by ukemi** [comment]
[Term]
+id: GO:0061750
+name: acid sphingomyelin phosphodiesterase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: H(2)O + sphingomyelin = ceramide + choline phosphate + H(+) in an acidic environment." [GOC:dph, PMID:26493087]
+synonym: "acid SMase" RELATED [PMID:26493087]
+synonym: "acid sphingomyelinase" EXACT [PMID:26493087]
+is_a: GO:0004767 ! sphingomyelin phosphodiesterase activity
+created_by: dph
+creation_date: 2015-11-11T14:47:45Z
+
+[Term]
+id: GO:0061751
+name: neutral sphingomyelin phosphodiesterase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: H(2)O + sphingomyelin = ceramide + choline phosphate + H(+) in a neutral environment." [GOC:dph, PMID:26493087]
+synonym: "neutral SMase" EXACT [PMID:26493087]
+synonym: "neutral sphingomyelinase" EXACT [GOC:26493087]
+is_a: GO:0004767 ! sphingomyelin phosphodiesterase activity
+created_by: dph
+creation_date: 2015-11-11T14:48:08Z
+
+[Term]
