### ISSUE TITLE
transport inconsistency sodium /potassium

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11492]
The terms for sodium and potassium export from cell across the plasma membrane are inconsistent

GO:0036376 - sodium ion export from cell 
Definition: "The directed movement of sodium ions out of a cell." 

can this be changed to the pattern
GO:0097623 Name potassium ion export across plasma membrane?"

with synonyms for both

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11318](https://sourceforge.net/p/geneontology/ontology-requests/11318)

**Comment by ValWood** [comment]
HI David,
This isn't done, but can probably close if it will get fixed  by design patterns?
Val

**Comment by dosumis** [comment]
Fixed: Moved to standard patterns.
