### ISSUE TITLE
NTR: negative regulation by virus of cytolysis by virus of host cell

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11509]
NTR: regulation by virus of cytolysis by virus of host cell

Definition: Any process that modulates the frequency, rate or extent of the killing by a virus of a cell in its host organism by means of the rupture of cell membranes and the loss of cytoplasm.

Ontology: Biological Process

Reference: PMID:14527655  Figure 1. in this paper shows loss of T4 rI results in a much earlier lysis time of its host.  This requested go term would be more accurate for this process.

Synonyms: regulation of lytic viral release
regulation of viral release by host cell lysis
regulation of viral release by cell lysis

The resulting Child-term would be:

NTR: negative regulation by virus of cytolysis by virus of host cell

Definition: Any process that stops, prevents or reduces the rate or extent of the killing by a virus of a cell in its host organism by means of the rupture of cell membranes and the loss of cytoplasm.

Ontology: Biological Process

Reference: PMID:14527655  Figure 1. in this paper shows loss of T4 rI results in a much earlier lysis time of its host.  This requested go term would be more accurate for this process.

Synonyms: negative regulation of lytic viral release
negative regulation of viral release by host cell lysis
negative regulation of viral release by cell lysis

Reported by: notjustin43

Original Ticket: [geneontology/ontology-requests/11335](https://sourceforge.net/p/geneontology/ontology-requests/11335)

**Comment by ValWood** [comment]
Increased  host cytolysis by loss of a viral protein does not seem to be strong enough evidence for a  biological process (seems like a phenotype)? It isn't demonstrating regulation.
