### ISSUE TITLE
mitochondrial promoters core and proximal?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11505]
I notice that the ontology terms for mitochondrial promoters mirrors the polII arrangement with

mitochondrial RNA polymerase core promoter sequence-specific DNA binding
mitochondrial RNA polymerase core promoter proximal region sequence-specific DNA binding

mitochondrial RNA polymerase core promoter sequence-specific DNA binding
has only one annotation (pombe rpo41)

mitochondrial RNA polymerase core promoter proximal region sequence-specific DNA binding
has no annotation

I can't find any evidence that there are core promoters and proximal regions. Could these two terms be merged (or obsoleted) and a new term created?

(There are also mitochondrial promoter terms for heavy and light chain, should these terms be children of a general promoter term, and should they be taxon restricted...I don't know if we have heavy and light chin in yeast, or if there is anything biologically different about a promoter on a different strand)?

(For now I will use continue to use mitochondrial RNA polymerase core promoter sequence-specific DNA binding for fission yeast, and then migrate)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11331](https://sourceforge.net/p/geneontology/ontology-requests/11331)

**Comment by ukemi** [comment]
PMID:21316793 describes transcription in mitochondria and suggests that not only does RNA polymerase bind the core promoter of mitochondrial genes, but other factors also bind the core and various other regions. I would like to leave this structure as is for now.

-D

**Comment by ValWood** [comment]
OK!
