### ISSUE TITLE
methionine biosynthesis from.....

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11515]
are these really separable?

GO:0019284	L-methionine biosynthetic process from S-adenosylmethionine	IEA	HAMAP:MF_03119	GO_REF:0000020	3
GO:0019509	L-methionine biosynthetic process from methylthioadenosine	ISO	SGD:S000006322	GO_REF:0000024	6

since 

"5'-Methylthioadenosine (MTA) is a naturally occurring sulfur-containing nucleoside present in all mammalian tissues. MTA is produced from S-adenosylmethionine mainly through the polyamine biosynthetic pathway, where it behaves as a powerful inhibitory product. This compound is metabolized solely by MTA-phosphorylase, to yield 5-methylthioribose-1-phosphate and adenine, a crucial step in the methionine and purine salvage pathways, respectively." 
PMID: 15313459

It seems as though this could  be 2 terms  representing the same process....(they are currently siblings)

Peter?

v

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11341](https://sourceforge.net/p/geneontology/ontology-requests/11341)

**Comment by ValWood** [comment]
This one seems quick to close. Let us know if you have any outstanding questions?
Val

**Comment by paolaroncaglia** [comment]
Following chat with Val, I edited the def of GO:0019284 L-methionine biosynthetic process from S-adenosylmethionine as below:

-def: "The chemical reactions and pathways resulting in the formation of L-methionine from other compounds, including S-adenosylmethionine." [GOC:go_curators]
+def: "The chemical reactions and pathways resulting in the formation of L-methionine from S-adenosylmethionine." [GOC:go_curators, GOC:vw]
