### ISSUE TITLE
NTR: modification by plasmid of morphology or physiology

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11514]
NTR: modification by plasmid of morphology or physiology

Definition: The process in which genes encoded by a plasmid effect a change in the structure or processes of a second organism.

Ontology: Biological Process

Reference: PMID:3019679 Figure 3. Shows proteins encoded by a plasmid can change the morphology of a cell.

Reported by: notjustin43

Original Ticket: [geneontology/ontology-requests/11340](https://sourceforge.net/p/geneontology/ontology-requests/11340)

**Comment by dosumis** [comment]
Closing as out of scope for GO.
