### ISSUE TITLE
NTR: negative regulation of cytolysis by virus of host cell

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11510]
A parent term to the NTR is:

Parent Term: GO:0001899 - negative regulation of cytolysis by symbiont of host cells

Definition: Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of cytolysis by that organism of cells in its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction

NTR: negative regulation of cytolysis by virus of host cells

Definition: Any process in which a virus stops, prevents, or reduces the frequency, rate or extent of cytolysis by that virus of cells in its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

Ontology: Biological Process

Synonyms: inhibition by virus of cytolysis of host cells
downregulation by virus of cytolysis of host cells
down-regulation by virus of cytolysis of host cells
down regulation by virus of cytolysis of host cells
negative regulation by virus of cytolysis of host cells

Reference: PMID:14527655 Figure 1. in this paper shows loss of the T4 virus-encoded "rI protein" results in T4 inducing cytolysis at a much earlier time. This requested go term would be more accurate for describing this process

Reported by: notjustin43

Original Ticket: [geneontology/ontology-requests/11336](https://sourceforge.net/p/geneontology/ontology-requests/11336)

**Comment by suzialeksander** [comment]
Hi,

is there any progress on this term?

Thanks

**Comment by ValWood** [comment]
Increased  host cytolysis by loss of a viral protein does not seem to be strong enough evidence for a  biological process (seems like a phenotype)? It isn't demonstrating regulation.

**Comment by pgaudet** [comment]
Check PMID:20945083

**Comment by ValWood** [comment]
closing  because
https://github.com/geneontology/go-ontology/issues/13041
