### ISSUE TITLE
NTR: Modulation by symbiont of host cell motility 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11512]
NTR: Modulation by symbiont of host cell motility

Definition: Any process in which a symbiont organism modulates the frequency, rate or extent of the controlled self-propelled movement of the host that results in translocation of the host from one place to another.

Aspect: Biological process

Parent term:GO:0044068 modulation by symbiont of host cellular process

Reference: PMID:25049409

Synomyns:
regulation of host motility by symbiont
modulation of host motility by symbiont

Resulting child term

NTR: Modulation by virus of host cell type IV motility 

Definition: Any process in which a virus modulates the frequency, rate or extent of controlled self-propelled movement of the host cell which is dependent on the presence of type IV pili.

Aspect: Biological process

Reference:  PMID:25049409

Synomyns:
regulation of host type IV motility by virus
modulation of host type IV motility by virus

Reported by: tladzekpo

Original Ticket: [geneontology/ontology-requests/11338](https://sourceforge.net/p/geneontology/ontology-requests/11338)

**Comment by ValWood** [comment]
GO:1903653 Modulation by symbiont of host cell motility

exists so closing.....nothing else to  do here?

**Comment by pgaudet** [comment]
NTR: Modulation by virus of host cell type IV motility
was never created but looking at the paper, PilB seems to inhibit pilus IV assembly, so the motility problem is secondary. 

Pascale
