### ISSUE TITLE
parent for GO:1990565 HSP90-CDC37 chaperone complex?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11529]
On Paola's advise, I'm adding it here. To be discussed on Editors' call.

GO:1990565 HSP90-CDC37 chaperone complex currently hasn't got a logical parent apart from 'protein complex'. I would like to add something more specific but we only know the process rather than the function of the complex so we can't use our usual complex_by_activity inference.

[Term]
id: GO:1990565
name: HSP90-CDC37 chaperone complex
namespace: cellular_component
def: "A protein complex involved in stress-induced mitophagy (mitochondrial degradation). In mammals it consists of heat shock protein HSP90 and its co-chaperone CDC37. Experimental evidence suggests that the complex enables the autophosphorylation of ULK1. Phosphorylated ULK1 in turn phosphorylates ATG13 which is an essential step in mitophagy. HSP90-CDC37 binding prevents rapid ubiquitin-dependent proteosomal degradation of its targets. " [GOC:bhm, IntAct:EBI-9990131, IntAct:EBI-9990540, PMID:21855797, PMID:22939624]
comment: An example of this is HSP90AB1 in human (P08238) in PMID:21855797 (inferred from direct assay).
subset: termgenie_unvetted
is_a: GO:0043234 ! protein complex
is_a: GO:0044444 {is_inferred="true"} ! cytoplasmic part
relationship: capable_of GO:0019887 ! protein kinase regulator activity
relationship: capable_of_part_of GO:0032435 ! negative regulation of proteasomal ubiquitin-dependent protein catabolic process
relationship: capable_of_part_of GO:0045737 ! positive regulation of cyclin-dependent protein serine/threonine kinase activity
relationship: capable_of_part_of GO:1903599 ! positive regulation of mitochondrion degradation
relationship: part_of GO:0005737 ! cytoplasm 

I would like to create a term that describes its pos reg action in the phosphorylation chain that leads to mitophagy initiation. 'regulatory complex' is too generic and 'protein kinase complex' slightly out of scope as the paper does not describe the actual kinase activity, just that the inhibition of HSP90 leads to a drastic reduction of phosphorylated downstream targets.

Please discuss!

Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/11356](https://sourceforge.net/p/geneontology/ontology-requests/11356)

**Comment by mcourtot** [comment]
Hi @ValWood: @bmeldal proposes a NTR "chaperone complex" defined as

```
A protein complex required for the non-covalent folding or unfolding, maturation, stabilization or assembly or disassembly of macromolecular structures. Usually active during or immediately after completion of translation. Many chaperone complexes contain heat shock proteins.

Comment: An example of this is HSP90AB1 in human (P08238) in PMID:21855797 (inferred from direct assay).

is_a: GO:0043234 ! protein complex
relationship: capable_of GO:0044183 protein binding involved in protein folding
```

@paolaroncaglia mentioned you were part of the 2008-2009 chaperone discussions; would you be able to weigh in as to whether this term is ok or not in the light of those?

**Comment by ValWood** [comment]
Yes. This supports my request that 
GO:0044183 protein binding involved in protein folding
be renamed to
"protein folding chaperone activity" to be more understandable to biologists....

**Comment by mcourtot** [comment]
Looking at metallochaperone complex - should they infer under chaperone complex?

**Comment by mcourtot** [comment]
I created chaperone complex and changed the definition of HSP90-CDC37 chaperone complex/
I moved the existing chaperone/chaperonin under chaperone complex. 
Question remains for metallochaperone complexes, currently defined as 'macromolecular complex' and ('capable of' some 'metallochaperone activity'). If needed, please open a separate ticket.

**Comment by ValWood** [comment]
Actually I think there could be a problem. Chaperone isn't a single activity, its a collection of activities.

So the def:
A protein complex required for the non-covalent folding or unfolding, maturation, stabilization or assembly or disassembly of macromolecular structures. Usually active during or immediately after completion of translation. Many chaperone complexes contain heat shock proteins.

Is a problem to logically define using
GO:0044183 protein binding involved in protein folding

which refers specifically to a "protein folding chaperone"

I'm not completely sure what the solution is for chaperones. 
I always feel we need more precise terms for the activities of various flavours of chaperone (of which metallochaperone is one). 

This one isn't going to be an easy one....

**Comment by mcourtot** [comment]
I think that when we say "chaperone complex capable of GO:0044183 protein binding involved in protein folding" we don't imply that it is the *only* thing it is capable of, so this is at least not wrong. We could add different activities if needed?

**Comment by ValWood** [comment]
OK go with it. The rest is for another day ;)

**Comment by mcourtot** [comment]
well I still would like it to be clean if possible ;) 
If we want to keep the general chaperone complex term we should make sure that, as you mention,  other flavours of chaperone infer properly under it - at least for those we already have - thus the question for the metallochaperone. I'll create a new ticket to not confuse this one. Thanks for the feedback @ValWood !
