### ISSUE TITLE
complement activation part of acute inflamatory response ?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11524]
'regulation of complement activation' is_a 'regulation of acute inflamatory response' 
But
'complement activiation' has no relationship to 'acute inflamatory response'

There should be both relationships or neither.  If both, the former will (I think) be inferred.  In terms of the biology - doesn't complement activation occur in contexts outside of the acute inflamatory response?

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/11351](https://sourceforge.net/p/geneontology/ontology-requests/11351)

**Comment by pgaudet** [comment]
I removed the asserted classes in the 'regulation' branch (see attached), so the complement activation process an its regulation are the same. 

I also changed 
complement activation is_a: GO:0072376 ! protein activation cascade
-> to  has_part GO:0072376 ! protein activation cascade

@addiehl Does that seem right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Here's the screenshot of complement activation and regulation of complement activation
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/4782928/46597969-9bcb1f00-cae2-11e8-9429-a4f5385c7d04.png">


I will merge this - if it was a problem I can revert the changes. 
Thanks, Pascale
