### ISSUE TITLE
NTR: kinetochore/centromere assembly complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11541]
Hi Paola,

Can you please create the following term as per our email discussion:

centromere assembly complex

Def:
A protein complex essential for the assembly of the kinetochore on the centromeric region of the chromosome.

Relationships:
is_a GO:0043234 protein complex
capable_of_part_of GO:0034508 ! centromere complex assembly 
capable_of_part_of GO:1903099 ! positive regulation of CENP-A containing nucleosome assembly
part_of GO:0000775 ! chromosome, centromeric region

Then, please make GO:1990568 MIS18 complex a direct child of the new term.
Also adjust the relationships of MIS18 complex as discussed (remove capable_of_part_of GO:0034508 ! centromere complex assembly)

Thanks,
Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/11368](https://sourceforge.net/p/geneontology/ontology-requests/11368)

**Comment by ukemi** [comment]
@ValWood @bmeldal 

Reading through this ticket, it looks to me like everything here is done. Since you both were the main people in the conversation, can you double-check for me. If there are additional edits required, can you please summarize them and I will make them. Thanks.

-D

**Comment by bmeldal** [comment]
Hi David,

There was one more suggestion (pt 3) in one of my earlier posts (3 Dec 2014):

> Make "centromere complex" term name

There's no discussion as to why this should or shouldn't happen.

Birgit

**Comment by ukemi** [comment]
Thanks Birgit. I'm trying to clear away some of these old tickets and some require my getting up to speed on the discussions again.
I will also wait to hear from Val, but looking at the results of previous edits, 'centromere complex' is an exact synonym of 'chromosome, centromeric region' and the logical definition of 'centromere complex assembly' includes results_in_the_assembly_of 'chromosome, centromeric region'. So it seems to me that swapping the synonym with the term name is at least consistent with what is in the ontology. 
Any objections Val?

**Comment by bmeldal** [comment]
Yes, that was considered above, to swap the term name and the synonym.

I hadn't even realised this was still open but I know there are still a few open tickets from when I first started 4 years ago!

**Comment by ValWood** [comment]
I'm not sure about  making 'centromere complex'  and exact synonym of  'chromosome, centromeric region'.

From its annotations, it seems much much broader.  'chromosome, centromeric region' is  really a rather "fuzzy" legacy CC term.... we used it when things were identified in the vicinity of the  centromere locality. It includes a lot of things which are really  spindle pole body, like DASH and Aurora OR which exist at the centromere and other places (like topoisomerase), or the SHEC complex which also occur at other heterochromatic regions....

I don't think that centromere complex should be an exact synonym/ its narrow so should probably be a term in its own right.....

**Comment by bmeldal** [comment]
Ok, two terms cross-wired here :(

I agree with Val that "centromere complex" should not be EXACT synonym of "GO:0000775 chromosome, centromeric region". It's should be at least NARROW if at all a synonym.

I think what I was suggesting 2 years ago was to call the "GO:0098654 CENP-A recruiting complex" "centromere complex", and maybe make "CENP-A recruiting complex" NARROW synonym... That would allow for a slight variation in components while the function is conserved.

**Comment by ValWood** [comment]
I think that would be confusing.
The purpose of the complex will always be to recruit CENP-A (this is a completely generic name for the centromere specific histone), and CENP-A is already in all of the related GO terms
(CENP_A containing chromatin assembly etc).

(Also centromerne complex is sometimes used to refer to the CENP-A containing chromatin complex *itself* PMID: 16716197)

I would say this is one of many centromere complexes....

**Comment by bmeldal** [comment]
Ok, I have no recollection of the details from 2 years ago! Just read what we said above. 

Sounds like in that case, nothing left to do...?

**Comment by ValWood** [comment]
I haven't seen any problems with how it is now recently ;)
