### ISSUE TITLE
GO:1902560 'GMP reductase complex' needs editing

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11544]
From an email thread involving Prudence, Birgit and myself:

Hi Birgit,

Prudence just pointed me to a term whose def is unclear. Could you plese let me know what the correct def would be - asking you as you submitted this via TG (yes, a year ago...) and I'm slightly swamped at the moment.
Should the def be
"...It catalyzes the irreversible reaction: IMP + NADP(+) + NH(4)(+) <= GMP + 2 H(+) + NADPH."
?
If yes, or if you have different suggestions, let me know and I'll edit. Thanks!
Current stanza:

[Term]
id: GO:1902560
name: GMP reductase complex
namespace: cellular_component
def: "A protein complex which is capable of GMP reductase activity. It catalysis of the irreversible reaction: IMP + NADP(+) + NH(4)(+) <= GMP + 2 H(+) + NADPH." [GOC:bhm, GOC:TermGenie, PMID:12009299]
comment: An example of this is GMPR2 in human (UniProt Symbol Q9P2T1) in PMID:12009299 (inferred from direct assay).
synonym: "GMP reductase" NARROW []
synonym: "GMPR1 complex" NARROW []
synonym: "GMPR2 complex" NARROW []
synonym: "guanosine monophosphate reductase" NARROW []
xref: EC:1.7.1.7
xref: RHEA:17188
is_a: GO:1990204 {is_inferred="true"} ! oxidoreductase complex
intersection_of: GO:0043234 ! protein complex
intersection_of: capable_of GO:0003920 ! GMP reductase activity
created_by: bhm
creation_date: 2013-12-10T11:54:30Z 

Paola

Hi Paola,

According to Intenz  EC:1.7.1.7 and RHEA:17187 it's

GMP + 2 H+ + NADPH => IMP + NADP+ + NH4+

The only change would be to refer to RHEA:17187 instead to RHEA:17188 in the stanza as this particular enzyme seems to act only in one direction.

In Uniprot the reaction for Q9P2T1 is
Inosine 5'-phosphate + NH3 + NADP+ = guanosine 5'-phosphate + NADPH

which seems wrong (NH3 instead of NH4+). I will point that out to them.

The quoted reaction in the Complex Portal was also slightly off so I fixed that (had a proton missing somewhere).

I hope that helps.
Birgit

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/11371](https://sourceforge.net/p/geneontology/ontology-requests/11371)

**Comment by paolaroncaglia** [comment]
Summing up: action items for me:

Change def of GO:1902560 GMP reductase complex to:
An oxidoreductase complex which is capable of GMP reductase activity. It catalyses the irreversible reaction: GMP + 2 H(+) + NADPH => IMP + NADP(+) + NH(4)(+)

Change its RHEA xref to:
RHEA:17187

Then close.

**Comment by paolaroncaglia** [comment]
Done.
