### ISSUE TITLE
question NMS complex interaction involved in chromosome segregation (and descendants)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11543]
I just spotted a weird process term(s)

GO:0044768  
"NMS complex interaction" involved in chromosome segregation (and descendants)

The interaction and association of NMS complexes required for kinetochore-spindle binding and chromosome segregation to occur.
(which seems to be describing a specific binding interaction involved in a process rather than a process)

How does this differ  from the existing process:
GO:0051315 attachment of mitotic spindle microtubules to kinetochore
 The cell cycle process in which spindle microtubules become physically associated with the proteins making up the kinetochore complex during mitosis. During mitosis, the kinetochores of sister chromosomes are situated facing opposite spindle poles and bipolar attachment of the sister chromosomes to the spindle occurs.

(currently it does not have any annotations)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11370](https://sourceforge.net/p/geneontology/ontology-requests/11370)

**Comment by ukemi** [comment]
Hi Val and Rama,

Kinetochore assembly is now part of nuclear chromosome segregation, so that part of this issue is solved. For the term in question, looking at the paper I propose this:
NMS complex interaction involved in kinetochore assembly-->NMS complex assembly involved in kinetochore assembly 

def:The formation of a supercomplex by the association of two subcomplexes (known as MIND and Ndc80 in Schizosaccharomyces) that is required for kinetochore assembly.

**Comment by ValWood** [comment]
Yep, sounds perfect to me....

**Comment by ValWood** [comment]
=z`wqOh, except.... I think the jury is still out as to whether "kinetochore assembly" is part of "chromosome segregation", or precedes it.

"kinetochore assembly"  is excluded from the current definition  of chromosome segregation. 
"begins with the condensation of chromosomes, includes chromosome separation, and ends when chromosomes have completed movement to the spindle poles"

and I think the kinetochore is assembled onto the uncondensed chromosomes? Or maybe  *some* of the kinetochore is assembled onto incomplete chromosomes, I am not sure of the exact timing of inner vs outer...

So, I have never figured out fully if it should be like this and I keep meaning to ask chromosome segregation experts. I could go either way...

**Comment by ukemi** [comment]
Last week I made kinetochore assembly part_of nuclear chromosome segregation based on another ticket where I moved a bunch of terms. According to an earlier comment in this ticket, the kinetochore assembles on a condensed chromosome. Should I remove that part_of relation?

**Comment by rbalakri** [comment]
hmm..I am not sure of the exact timing either. I suggest we leave it like this and remove the relation later.

Rama

**Comment by ValWood** [comment]
Adding this link has other knock on effects. Currently mitotic spindle organization is also not part of mit. chromosome segregation. If kinetochore assembly is part of chromosome segregations, then the some aspects of spindle/centromere organization should be too?

Before adding these parents, we should figure out the historical reason for the way  chromosome segregation in the existing term definitions.  If kinetochore assembly and aspects of spindle assembly are considered to be part of this process, and these parents are added, the chromosome segregation definitions should also be revised accordingly.

This question has been on my list of "things to look at eventually" for a long while. It would be better to  make any large changes here in consultation with experts.

**Comment by ukemi** [comment]
So what I am hearing is that I should remove the new part_of link?

-D

**Comment by ValWood** [comment]
Yeah, and make the question a "long term project" ;)
We can have a look when the rest of cell cycle is done. Chromosome segregation is my *big* annotation project so that's what I'll be working on when I get the chance ...

**Comment by ukemi** [comment]
OK. Edited existing term as above and removed  the part of relation between kinetochore assembly and nuclear chromosome segregation.
