### ISSUE TITLE
New Term Request Dinoflagellate Peduncle

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11553]
Create new term "peduncle". It should be a child of cell part. It is a tube that is used by a dinoflagellate (and other protists) to feed on other cells. A definition can be found here http://species-identification.org/species.php?species_group=dinoflagellates&selected=definitie&menuentry=woordenlijst&record=peduncle

Reported by: diatomsrcool

Original Ticket: [geneontology/ontology-requests/11381](https://sourceforge.net/p/geneontology/ontology-requests/11381)

**Comment by paolaroncaglia** [comment]
Hi Anne,

Sorry this took so long! Looking at this request now and based on how we phrased other dinoflagellate-specific terms in GO, I opted for ‘dinoflagellate peduncle’ as I think this won’t cause any ambiguity. It is now in GO and ready to use; full stanza below.

Thanks,
Paola

[Term]
id: GO:1990905
name: dinoflagellate peduncle
namespace: cellular_component
def: "A small, flexible, finger-like appendage located near the flagellar pores in some photosynthetic as well as nonphotosynthetic dinoflagellate species. Its functions are not fully understood, but it has been associated with feeding behavior (phagotrophy)." [GOC:at, http://en.wikipedia.org/wiki/Dinoflagellate, http://species-identification.org/index.php]
comment: The term name refers to a taxonomic group to make the label unique with respect to similarly-named anatomical structures.
is_a: GO:0042995 ! cell projection
relationship: only_in_taxon NCBITaxon:2864 ! Dinophyceae
created_by: pr
creation_date: 2015-11-22T10:22:46Z
