### ISSUE TITLE
myelin sheath & Schwann cells

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11564]
From Sebastian K. This is causing problems with HPO inference, as we end up with the assumption that myelin is always in the PNS:

```
[Term]
id: GO:0043209
name: myelin sheath
namespace: cellular_component
def: "An electrically insulating fatty layer that surrounds the axons of many neurons. It is an outgrowth of glial cells: Schwann cells supply the myelin for peripheral neurons while oligodendrocytes supply it to those of the central nervous system." [GOC:jl, NIF_Subcellular:sao-593830697, Wikipedia:Myelin]
synonym: "astrocyte sheath" NARROW [NIF_Subcellular:nlx_subcell_20090204]
synonym: "oligodendrocyte myelin sheath" NARROW [NIF_Subcellular:sao1279474730]
synonym: "Schwann cell myelin sheath" NARROW []
xref: FMA:62983
xref: NIF_Subcellular:sao-593830697
xref: Wikipedia:Myelin
is_a: GO:0044464 ! cell part
***relationship: part_of CL:0000218 ! myelinating Schwann cell
```

Weaken to 'glial cell'? Introduce two subtypes (oligodend, Schwann)?

To complicate the issue further, some arthropods have 'myelin'; but I think the proposed weakening works for these too.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/11392](https://sourceforge.net/p/geneontology/ontology-requests/11392)

**Comment by paolaroncaglia** [comment]
@cmungall 
Hi Chris, any updates on this please? (Doug doesn't seem to have a github account)
Thanks,
Paola

**Comment by cmungall** [comment]
I can grant access to CL for anyone that needs it

**Comment by paolaroncaglia** [comment]
Hi @doughowe and @cmungall 

I’m closing this ticket because nothing else can be done in GO at this stage (and we’ve fixed GO as far as we could go). The ball is in CL’s park now. If you wish, could one of you please open a ticket in the CL tracker to request the changes listed by Doug in his comment dated Dec 12, 2014. 

Thanks!
