### ISSUE TITLE
more kinds of synaptic vesicles?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11567]
Hi 

In doing some annotations for human genes for the Synapse Jamboree, I made some annotations from PMID:11182090. Currently, I have annotated human CLCN3 to the term "synaptic vesicle" (GO:0008021). However, based on what the authors showed in Fig 7C, I was wondering if we should have terms for specific types of synaptic vesicles, e.g. "GABAergic vesicles", "glutamatergic vesicles", etc. Probably a question for the Synapse Jamboree experts, but I wanted to go ahead and put it here.

thanks,

-Karen

Here is the text of the relevant figure legend:

Figure 7. Subcellular Localization of ClC-3

(C) ClC-3 is present on GABAergic and glutamatergic vesicles. Synaptic vesicles were isolated by microbeads coated with antibodies against synaptophysin, VGAT, and VGLUT1/BNPI. Immunoisolates were analyzed by Western blot.

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/11395](https://sourceforge.net/p/geneontology/ontology-requests/11395)

**Comment by pgaudet** [comment]
@Pimmelorus Would you say you need these vesicles ? If you do, can you please provide definitions ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Great, thanks !
