### ISSUE TITLE
MP vacuole fusion

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11578]
'vacuole fusion' does not have the parent 'vacuole organization'
but its children 'vacuole fusion, non-autophagic'
and 'vesicle fusion with vacuole' do. Should this parent be added?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11406](https://sourceforge.net/p/geneontology/ontology-requests/11406)

**Comment by ValWood** [comment]
This is already fixed so closing....
