### ISSUE TITLE
New Term Request - child of GO:0016779 nucleotidyltransferase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11574]
suggested name: RNA nucleotidyltransferase activity
suggested definition: Catalysis of the reaction: ribonucleoside triphosphate + RNA(n) = diphosphate + RNA(n+1).
example of protein to be annotated: UniProt Accession ID O14746 TERT
example of publication as evidence: PMID 19701182
GOC:nc
GOC:BHF

Reported by: noonoo25

Original Ticket: [geneontology/ontology-requests/11402](https://sourceforge.net/p/geneontology/ontology-requests/11402)

**Comment by dosumis** [comment]
@NancyCampbell

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/22472858/c01f4816-e7ce-11e6-8127-2b1184df99d0.png)

**Comment by dosumis** [comment]
GO_0098680

**Comment by NancyCampbell** [comment]
Thank you.
Can you please add 
GOC:nc
GOC:BHF
GOC:BHF_telomere
Nancy

**Comment by ValWood** [comment]
This the  described activity?
GO:1990817 RNA adenylyltransferase activity
needs synonyms etc...

**Comment by NancyCampbell** [comment]
Yes and no.
looking for a less specific term? i.e. for any nucleotide not adenine in particular. I looked at the tree ... but can't find a suitable less granular parent.
Please advise.
thanks.

**Comment by ValWood** [comment]
There is also
GO:0050265 RNA uridylyltransferase activity


but  you are right a general "polynucleotide transferase" term would help here...
v

**Comment by dosumis** [comment]
> Thank you.
> Can you please add
> GOC:nc
> GOC:BHF
> GOC:BHF_telomere

Sorry. Rubbish at remembering to add these.  Now added

From the discussion, it seems like I should move these subclasses under the new term.

GO:1990817 RNA adenylyltransferase activity
GO:0050265 RNA uridylyltransferase activity
RNA guanylyltransferase activity

Need to be sure that these are all template-free though.

Possibly also 
tRNA nucleotidyltransferase activity
tRNA guanylyltransferase activity
tRNA cytidylyltransferase activity

etc.   Although EC numbers don't nest...

**Comment by NancyCampbell** [comment]
Thank you David.

**Comment by ValWood** [comment]
Can this one be closed?
v

**Comment by ValWood** [comment]
The terms appear to be there so closing.
Open a new ticket if any problems.
