### ISSUE TITLE
Channel activity defined too strictly?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11579]
I raised an issue with SGD about the use of "protein channel activity" to describe the Tim23 complex.

channel activity is defined 

"Catalysis of energy-independent facilitated diffusion, mediated by passage of a solute through a transmembrane aqueous pore or channel. Stereospecificity is not exhibited but this transport may be specific for a particular molecular species or class of molecules."

(also all of the children, I was particularly concerned with protein channel in this instance).

It is a child of "passive transmembrane transporter activity"

Rama pointed out
Tom40 forms the channel in the outer membrane, while Tim23 does the same in the inner membrane.
Channels operate in many ways (during facilitated diffusion or passive transport) and change in membrane potential is one of them. 
Definition could be better.

So it seems our use of "channel" is quite strictly defined (certainly many things which are annotated to 'channel' do not fit this def).

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11407](https://sourceforge.net/p/geneontology/ontology-requests/11407)

**Comment by dosumis** [comment]
Terminology issue.  Need term for the activity of these complexes that does not fall under 'channel'.

**Comment by ValWood** [comment]
Solution
Merge 
1.
protein channel activity
into parent
protein transmembrane transporter

2. Make "protein channel activity" related synonym

3. remove parent to "channel activity"
(is not a GO type channel, i.e is not energy independent)
