### ISSUE TITLE
obsolete request: regulation of histone modification by regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11583]
Hi 

I don't think this term and it's child terms are right:
GO:1900410 regulation of histone modification by regulation of transcription from RNA polymerase II promoter

it has 2 pombase annotations
histone modification regulates transcription, not the otherway round.
Please obsolete.

BTW
I have just created with Term genie the following:
- GO:1903756 Label: regulation of transcription from RNA polymerase II promoter by histone modification
- GO:1903757 Label: positive regulation of transcription from RNA polymerase II promoter by histone modification
  ( GO:1903758 Label: negative regulation of transcription from RNA polymerase II promoter by histone modification

Which need to have a parent child relationship added

Please confirm whether this would be a valid GO term:
- regulation of transcription from RNA polymerase II promoter by regulation of histone modification would 

Thanks

Ruth

Note  
- GO:0097549 'chromatin organization involved in negative regulation of transcription' has the child terms:
  - GO:0070868 heterochromatin organization involved in chromatin silencing  
  - GO:0006343 establishment of chromatin silencing

both of which concern the organisation of the chromatin into heterochromatin (or similar structure).

However, histone modifications are a type of chromatin organization which is reflected in GO:
GO:0016570 histone modification is a grandchild of  GO:0006325 chromatin organization.

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11411](https://sourceforge.net/p/geneontology/ontology-requests/11411)

**Comment by dosumis** [comment]
Happy to send out obsoletion notice for: "negative regulation of transcription from RNA polymerase II promoter by histone modification".  But note - there seems to be a BHF-UCL manual annotation on it:

UniProtKB
Q13363
CTBP1
GO:1903758
negative regulation of transcription from RNA polymerase II promoter by histone modification
P
IMP
PMID:21102443
9606
20141218
BHF-UCL

**Comment by pgaudet** [comment]
this is done.
