### ISSUE TITLE
cellular response to nutrient/ cellular response to nutrient levels

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11585]
anyone know why these are not related?
cellular response to nutrient/ cellular response to nutrient levels

The bigger question to me is why we need both terms?  Any insight into this?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11413](https://sourceforge.net/p/geneontology/ontology-requests/11413)

**Comment by dosumis** [comment]
Changed my mind after looking over usage . Keeping response to nutrient levels as general class.  This makes sense as it covers response to the *absence* of a nutrient (e.g. response to starvation).
