### ISSUE TITLE
obsolete: telomere formation via telomerase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11599]
Hi

Nancy and I feel that the GO term:  GO:0032203 telomere formation via telomerase should be obsoleted. The definition states: The addition of telomeric repeats to a non-telomeric double-stranded DNA end by telomerase.

But telomerase requires single-stranded DNA to extend. The alternative terms: GO:0007004 telomere maintenance via telomerase and/or GO:0032202 telomere assembly are more appropriate terms to use.

This term had only 4 annotations (2 of which were BHF and I have changed these to better GO terms).

Possibly this term was created before the activity of telomerase was fully understood. 

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11428](https://sourceforge.net/p/geneontology/ontology-requests/11428)

**Comment by ukemi** [comment]
I have just come across a paper PMID:12199911 that describes the de novo addition of telomeres to chromosomes of the macronucleus and to fragmented chromosomes of other species as a natural process. Therefore although not common, I think this is a valid biological process. I have tweaked the definition of the telomerase-based term as suggested.

**Comment by NancyCampbell** [comment]
Thanks for resolving this David. I have updated the annotations for the relevant entries on the complex portal accordingly.
Nancy

@bmeldal
