### ISSUE TITLE
children of GO:0034401 - regulation of transcription by chromatin organization

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11628]
**ID:** GO:0034401
**Name**    chromatin organization involved in regulation of transcription
**Definition:** Any cellular process that results in the specification, formation or maintenance of the physical structure of eukaryotic chromatin that modulates the rate, frequency or extent of DNA-dependent transcription.
**Restrictions**    This term should not be used for direct manual annotation. This term may be used for mapping to external vocabularies in order to create electronic annotations.
GONUTS  GO:0034401 Wiki Page
This transcription term is a stub.

A number of GO terms seem as though they should be under this term. For example:
1. GO:0006342 'chromatin silencing': Repression of transcription by altering the structure of chromatin, e.g. by conversion of large regions of DNA into an inaccessible state often called heterochromatin.
2. GO:0048096 'chromatin-mediated maintenance of transcription' and the processes referred to by Karen in the older closed ticket https://sourceforge.net/p/geneontology/ontology-requests/11328/ #11502
3. The terms requested by Ruth here: https://sourceforge.net/p/geneontology/ontology-requests/11411/
   (regulation of transcription by histone modification is a type of regulation of transcription by chromatin organization) #11583 

Then this restriction will make sense:
This term should not be used for direct manual annotation. This term may be used for mapping to external vocabularies in order to create electronic annotations.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11457](https://sourceforge.net/p/geneontology/ontology-requests/11457)

**Comment by dosumis** [comment]
> GO:0034401 'regulation of transcription by chromatin organization'

This term is now
'chromatin organization involved in regulation of transcription'
EquivalentTo: 'chromatin organization'
 and ('part of' some 'regulation of transcription, DNA-templated')

Renamed by Jane as part of #11502

> A number of GO terms seem as though they should be under this term. For example:
> 
> GO:0006342 'chromatin silencing': Repression of transcription by altering the structure of chromatin, e.g. by conversion of large regions of DNA into an inaccessible state often called heterochromatin.
> 

Something back to front here.  We have terms like  "heterochromatin assembly involved in chromatin silencing" , but couldn't we define 'chromatin silencing' as EquiavlentTo 

'heterochromatin assembly' *that* **part_of** *some* 'negative regulation of transcription, DNA templated'. 
Or perhaps just
'heterochromatin assembly' *that* **negatively_regulates** *some* 'transcription, DNA templated'

This fits nicely with the textual definition of chromatin silencing: "Repression of transcription by altering the structure of chromatin, e.g. by conversion of large regions of DNA into an inaccessible state often called heterochromatin."

### Proposal 

I think it was a mistake to change the name and formalisation of 'regulation of transcription by chromatin organization' in the first place.  I propose to change it back - and change all child terms to follow the pattern

\<chromatin organisation\> *that* <**regulates**> *some* 'transcription, DNA templated'

**Comment by dosumis** [comment]
Change of plan.  Still assuming chromatin silencing happens via heterochromatin formation.  Need to revist all of these patterns if there are any cases where that is false. But have moved the EC definitions down to the child classes: establishement/maintenance of chromatin silencing.

Notes on implemenation and next steps.

label "chromatin silencing"
comment "Note that this process is the opposite of chromatin-mediated maintenance of transcription. This regulation is exemplified by members of the Polycomb group, which maintain the inactive state of homeotic gene transcription."^^string
definition "Repression of transcription by altering the structure of chromatin, e.g. by conversion of large regions of DNA into an inaccessible state often called heterochromatin."^^string
SubClassOf: 
  * 'chromatin organization'
  * 'gene silencing'
  * 'negative regulation of gene expression, epigenetic'
  * 'negatively regulates' some 'transcription, DNA-templated'

(we should probably have 'negative regulation of transcription, epigenetic')


'establishment of chromatin silencing' EquivalentTo:
'heterochromatin assembly'
 and ('negatively regulates' some 'transcription, DNA-templated')

'maintenance of chromatin silencing' EquivalentTo:
'heterochromatin maintenance'
 and ('negatively regulates' some 'transcription, DNA-templated')

label "chromatin silencing at centromere"^^string
EquivalentTo: 'chromatin silencing'
 and ('occurs in' some 'chromosome, centromeric region')
(same pattern for subclasses)

(various subclasses follow the same patterns - combined).

To merge:  
* 'heterochromatin maintencance involved in chromatin silencing' with 'maintenance of chromatin silencing'
* 'establishment of chromatin silencing 

Ditto for compound subclasses (chromatin silencing at / heteorchromatin assembly involved in chromatin silencing at...)

**Comment by dosumis** [comment]
Having doubts.  Key question seems to be whether silencing by Polycomb group genes counts as 'chromatin silencing' (I think yes) and if so whether this is distinct from 'heterochromatic' (I think so - see http://www.nature.com/nrg/journal/v12/n2/full/nrg2932.html).  There may be a case for adding 'heterchromatic silencing' terms as subclasses of 'chromatin silencing'.

Even with this - chromatin silencing should be classified under GO:0034401

**Comment by dosumis** [comment]
> Even with this - chromatin silencing should be classified under GO:0034401

Actually - now think they are candidates for merge.

heterochromatic silencing terms can come from renaming subclasses of GO:0034401 that specifically refer to heterochromatin.
