### ISSUE TITLE
MP	telomere maintenance via telomerase -> DNA biosynthetic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11623]
telomere maintenance via telomerase does to have a parent to

DNA biosynthetic process, should it?

It does however have a parent to "DNA replication" but it shouldn't?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11452](https://sourceforge.net/p/geneontology/ontology-requests/11452)

**Comment by dosumis** [comment]
Added comment to 'DNA replication': DNA biosynthesis is only part of this process.
