### ISSUE TITLE
Add remaining logical definitions for 'rare genus' terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11649]
We have a number of odds and ends terms unaxiomatized following lexical patterns such as:

 * X relaxation
 * X contraction
 * X hypertrophy
 * X segmentation
 * X pigmentation
 * X mineralization
 * X adaptation
 * X cavitation
 * X elongation
 * X closure

Often there is no high level genus.

I'm going to stop my broken record routine and insist on a set of pairwise disjoint genii for these, and just going to go with specific relations, in RO. Whilst doing, also make some GORELs bona-fide ROs.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/11478](https://sourceforge.net/p/geneontology/ontology-requests/11478)

**Comment by dosumis** [comment]
This issue was moved to geneontology/design_patterns#6
