### ISSUE TITLE
either child term or synonym request for GO:0000266 mitochondrial fission

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11652]
Based on these papers, 
PMID: 19279012
PMID:11038192

I think that "mitochondrial fragmentation" is an exact synonym of: 

GO:0000266 mitochondrial fission

Please check and if in agreement, add to definition.

GOC:PARL
GOC:pad

Reported by: pauldenny

Original Ticket: [geneontology/ontology-requests/11481](https://sourceforge.net/p/geneontology/ontology-requests/11481)

**Comment by paolaroncaglia** [comment]
@pauldenny
@RLovering

**Comment by ukemi** [comment]
Paul,
I'm pretty sure that we have sorted this out now in the ontology. Mitochondrial fission and the fragmentation that take place as part of autophagy are not synonymous. The mitochondrial fragments formed as part of mitophagy are a result of failure of mitochondrial homeostasis and mitochondrial fusion. Whereas mitochondrial fission is the way the mitochondria reproduce. So having mitophagy as a child of 'mitochondrion disassembly' seems reasonable.
