### ISSUE TITLE
Obsoletion proposal for terms in the UPR branch

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11656]
Following on from my request for new terms in the UPR node: https://sourceforge.net/p/geneontology/ontology-requests/11484/

The existing two terms are confusing:
activation of signaling protein activity involved in unfolded protein response ; GO:0006987
UFP-specific transcription factor mRNA processing involved in endoplasmic reticulum unfolded protein response ; GO:0030969

1/
activation of signaling protein activity involved in unfolded protein response ; GO:0006987
The conversion of a specific protein, possessing protein kinase and endoribonuclease activities, to an active form as a result of signaling via the unfolded protein response.

The broad name of this term doesn’t match the very specific definition. I’m assuming the definition refers to the activation of the ER stress sensor IRE1 (inositol-requiring transmembrane kinase/endonuclease-1).
For an overview, see PMID review: 22013210.

Many of the current annotations come from a linking to:
Reactome_18368 (ATF6-alpha activates chaperones)
Reactome_18348 (IRE1alpha activates chaperones)
Reactome_18277 (PERK regulates gene expression)
These are the 3 main branches of the UPR pathway, and I’m considering making terms for these separately (see SF:)

The non-Reactome experimental annotations are to:

VAPB- induces IRE1alpha activity
Hspa5- aka BiP: chaperone that under ER stress conditions dissociates from IRE1alpha to probably activate IRE1alpha
PARP16- may activate IRE1alpha activity
IRE1A itself (aka ERN1)

Two possible options:
1. Rename the term to 'IRE1 activation', and remove the Reactome mappings.
2. Obsolete this term, and annotations can be transferred to the new terms I suggest in https://sourceforge.net/p/geneontology/ontology-requests/11484/ This option would loose some information since the new terms describe the whole of the IRE1 pathway.

---

2/
I’d like to rename GO:0030969, and give it some synonyms to make it less confusing:

UFP-specific transcription factor mRNA processing involved in endoplasmic reticulum unfolded protein response ; GO:0030969
The spliceosome-independent cleavage and ligation of the mRNA encoding a UFP-specific transcription factor to remove a single intron, thereby increasing both the translational efficiency of the processed mRNA and the activity of the protein it encodes.

> UFP-specific transcription factor mRNA processing
> Def: stays the same
> synonym: UFP-specific transcription factor mRNA processing involved in endoplasmic reticulum unfolded protein response ; GO:0030969
> narrow synonym: XBP1 mRNA splicing
> narrow synonym: XBP1u mRNA processing to XBP1s
> narrow synonym: XBP1s generation
> narrow synonym: HAC1 mRNA processing

And create:
Ire1 complex: capable_of_part_of: GO:0030969
UFP-specific transcription factor mRNA processing involved in endoplasmic reticulum unfolded protein response

Thanks!

Reported by: rebeccafoulger

Original Ticket: [geneontology/ontology-requests/11485](https://sourceforge.net/p/geneontology/ontology-requests/11485)

**Comment by pgaudet** [comment]
@ValWood do you have any opinion on this one ? Otherwise we'll close this.

**Comment by ValWood** [comment]
I was looking at 
activation of signaling protein activity involved in unfolded protein response ; GO:0006987
yesterday and thinking that it should be obsoleted, but I thought would deal with the other issues first...
https://github.com/geneontology/go-ontology/issues/14380

I think these are referring to  "sensors" at the beginning of the pathway, but it is unclear and 
would be correctly a MF  part of BP annotation.

**Comment by pgaudet** [comment]
Discussion with @ValWood 
- GO:0006987 activation of signaling protein activity involved in unfolded protein response : The definition is "The conversion of a specific protein, possessing protein kinase and endoribonuclease activities, to an active form as a result of signaling via the unfolded protein response. ". 
-> The fact that a specific protein is mentionned suggests that this represents a Molecular Functions. Looks like this was captured to annotate ERN1 (Serine/threonine-protein kinase/endoribonuclease IRE1); other annotated proteins are NOT kinases/endoribonucleases

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/17979529

**Comment by ValWood** [comment]
https://www.researchgate.net/publication/275046841_Endoplasmic_reticulum_stress_in_periimplantation_embryos/figures?lo=1

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPAC167.01
endoribonuclease activity  | has substrate bip1 during endoplasmic reticulum unfolded protein response

**Comment by slaulederkind** [comment]
All of the RGD annotations are imported from other databases.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: 

GO:0006987 activation of signaling protein activity involved in unfolded protein response
GO:0030969 UFP-specific transcription factor mRNA processing involved in endoplasmic reticulum unfolded protein response
GO:0070055 mRNA endonucleolytic cleavage involved in unfolded protein response
GO:1904720 regulation of mRNA endonucleolytic cleavage involved in unfolded protein response
GO:1904721	negative regulation of mRNA endonucleolytic cleavage involved in unfolded protein response
GO:1904722 positive regulation of mRNA endonucleolytic cleavage involved in unfolded protein response

The reason for obsoletion is that these processes represent MF (single steps) of the IRE1-mediated unfolded protein response (GO:0036498). 

Annotations can be reviewed and moved if needed: 
https://github.com/geneontology/go-annotation/issues/1934

There are no InterPro mappings to those terms. 

Comments can be added to the ticket here: https://github.com/geneontology/go-ontology/issues/11656

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on April 24, 2018. Unless objections are received by April 24, 2018, we will assume that you agree to this change.

Thanks, 


Pascale
