### ISSUE TITLE
Shouldn't smad complex nuclear localization be part of smad sig trans?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11660]
Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/11489](https://sourceforge.net/p/geneontology/ontology-requests/11489)

**Comment by ValWood** [comment]
@RLovering @ukemi  what was the decision about localization from the signalling meeting? I can't remember...

**Comment by pgaudet** [comment]
The decision was to obsolete these terms. There is nothing special about the transport of these proteins to the nucleus. See #13686
