### ISSUE TITLE
TPV (possible) mitochondrial transcription/DNA metabolism

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11677]
I noticed that  both
GO:0032042 mitochondrial DNA metabolic process
GO:1903109 - positive regulation of transcription from mitochondrial promoter 

are descendents of 'mitochondrial organization'.

Do mitochondrial transcription and DNA metabolism _always_ affect mitochondrial organization (assembly, arrangement of constituent parts, or disassembly)....doubtful? 

?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11506](https://sourceforge.net/p/geneontology/ontology-requests/11506)

**Comment by dosumis** [comment]
I've removed mitochondrial transcription from under 'mitochondrion organization', but have left 'mitochondrial DNA metabolic process' as this looks justified via  'part of' some 'mitochondrial genome maintenance'.

**Comment by dosumis** [comment]
Done same for 'plastid organization'
