### ISSUE TITLE
difference  GO:0051315 attachment of mitotic spindle microtubules to kinetochore/biorientation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11674]
Is there a difference between
GO:0051315 attachment of mitotic spindle microtubules to kinetochore
The cell cycle process in which spindle microtubules become physically associated with the proteins making up the kinetochore complex during mitosis. During mitosis, the kinetochores of sister chromosomes are situated facing opposite spindle poles and bipolar attachment of the sister chromosomes to the spindle occurs.

and its descendant

GO:0031134
Name	sister chromatid biorientation
The cell cycle process in which sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles. 

I can't figure out what is more specific about GO:0031134, that's how it happens, if it happens correctly (note it is quite possible that I requested both of these terms....)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11503](https://sourceforge.net/p/geneontology/ontology-requests/11503)

**Comment by dosumis** [comment]
See #12244  for fix.
