### ISSUE TITLE
ATP hydrolysis coupled transport

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11682]
Hi

The aim of this request is to generate a MF-BP link between ATPase transporters and ATP coupled transport.
(this request has come from PMID:18075585, but outside of this now really). To be honest I have tried to write this out, but I am hoping that this is easier to do looking at obo-edit than looking at a flat list (below) where it is harder to see where the links are and are missing.

GO:0098660 inorganic ion transmembrane transport (note odd child terms here silver and aluminum should be child of cation term) 

> is_a child new GO term: ATP hydrolysis coupled ion transmembrane transport
> 
> > part_of child GO:0042625 ATPase activity, coupled to transmembrane movement of ions
> 
> GO:0098662 inorganic cation transmembrane transport
> 
> > is_a child new GO term: ATP hydrolysis coupled inorganic cation transmembrane transport
> > 
> > > part_of child  GO:0019829   cation-transporting ATPase activity (should this have transmembrane in it’s name to be consistent with anion sibling below?)
> 
> GO:0098661 inorganic anion transmembrane transport
> 
> > is_a child new GO term: ATP hydrolysis coupled inorganic anion transmembrane transport
> > 
> > > part_of child  GO:0043225 anion transmembrane-transporting ATPase activity

In addition (though not really necessary so could ignore) while we are here would it be worth having grouping terms for anions and cations for some of the MF terms (although some atpases work with anion and cation so maybe not)

 GO:0015662 ATPase activity, coupled to transmembrane movement of ions, phosphorylative mechanism

> is_a Child new term: ATPase activity, coupled to transmembrane movement of cations, phosphorylative mechanism
> 
> > is_a Child GO:0008556    potassium-transporting ATPase activity (and other GO:0015662 child cation terms)
> 
> is_a Child new term: ATPase activity, coupled to transmembrane movement of anions, phosphorylative mechanism
> 
> > is_a Child  GO:0008555   chloride-transporting ATPase activity

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11512](https://sourceforge.net/p/geneontology/ontology-requests/11512)

**Comment by dosumis** [comment]
Visualization of current structure:

![image](https://cloud.githubusercontent.com/assets/112839/21109886/ec66321c-c092-11e6-8b8d-e2104e5453e1.png)

**Comment by dosumis** [comment]
Added new formal BP terms with formal defs:

![image](https://cloud.githubusercontent.com/assets/112839/21110796/94711492-c096-11e6-8093-3998fb017c00.png)

**Comment by dosumis** [comment]
Added part_of links to these from activity grouping classes + some limited formalization.
