### ISSUE TITLE
NTR - 4Fe-3S cluster binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11699]
NTR 4Fe-3S cluster binding. 

Def: interacting selectively and non-covalently with a 4 iron-3 sulfur (4Fe-3S) cluster; an uncommon iron-sulfur cluster with unique properties found in the oxygen tolerant Ni-Fe hydrogenases of various bacteria.

Child of GO:0051536 iron-sulfur cluster binding

Literature: PMID 23267108 (Pandelia 2013)

Thanks
Amanda

Reported by: amackie

Original Ticket: [geneontology/ontology-requests/11529](https://sourceforge.net/p/geneontology/ontology-requests/11529)

**Comment by paolaroncaglia** [comment]
Note for self: Fe4S3 iron-sulfur cluster (CHEBI:85620) was added to ChEBI.

**Comment by paolaroncaglia** [comment]
Added logical def.
