### ISSUE TITLE
NTR for protein family binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11693]
1) term: CRTAM  family protein binding

definition: Interacting selectively and non-covalently with any member of the class I-restricted T cell-associated molecule (CRTAM) protein family.
CRTAM is an Ig superfamily receptor containing two Ig domains in its extracellular domain. The first Ig domain represents a V type domain, followed by a C type Ig domain. As a member of the immunoglobulin superfamily originally found to be highly expressed in activated CD8+T and NKT cells which are class I major histocompatibility complex restricted, it complies with the structural characteristics of the JAM family of proteins and is phylogenetically more closely related to nectin-like proteins.  (excerpt from PMID:16904340 and 20556794)

is_a GO:0034987 	immunoglobulin receptor binding

PMID:16904340
PMID: 20556794

Synonym: CD355

2) term: Nectin and nectin-like family protein binding

definition:  Interacting selectively and non-covalently with any member of the nectin or nectin-like (Necl) protein family. Nectins and nectin-like molecules (Necls) are immunoglobulin-like transmembrane cell adhesion molecules that are expressed in various cell types. Nectins and Necls are classified by whether they can bind afadin; nectins bind afadin, whereas Necls do not. (excerpt from PMID: 18648374)

is_a  GO:0050839 cell adhesion molecule binding
is_a GO:0019865 immunoglobulin binding

PMID: 18648374

Reported by: mikerice7

Original Ticket: [geneontology/ontology-requests/11523](https://sourceforge.net/p/geneontology/ontology-requests/11523)

**Comment by tberardini** [comment]
This issue was discussed at the DC GOC meeting that just concluded.  

Decision: protein family binding terms will be removed from GO.  Annotations will be to ‘protein binding’ and the ‘with’ column (or, preferably, col. 16 using the has_input relation) will be required.  If desired, an external protein classification can be used to create virtual protein family binding terms for grouping gene products for, e.g. enrichment analysis

**Comment by tberardini** [comment]
@michaelerice 

Please read the last comment which resolves the pending request for a set of new 'protein family binding' terms.
