### ISSUE TITLE
MP cellular metabolic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11706]
missing cellular metabolic process parentage (have only metabolic process, but appear to be cellular?)

positive regulation of Rho GTPase activity
iron-sulfur cluster assembly
gene expression
regulation of Ras protein signal transduction (or possibly a parent)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11536](https://sourceforge.net/p/geneontology/ontology-requests/11536)

**Comment by ValWood** [comment]
iron-sulfur cluster assembly migrated to new ticket https://github.com/geneontology/go-ontology/issues/12404

**Comment by ValWood** [comment]
so this ticket now about is about:

positive regulation of Rho GTPase activity-> now GO:0043547 positive regulation of GTPase activity
and
regulation of Ras protein signal transduction

The questions:
Should these be under metabolism at all (Probably not based on the above?)
If they are  they should be under the "cellular metabolic process" term

**Comment by pgaudet** [comment]
Hi Val, 

I see you have created a few issues similar to this - I thought everything to do with signaling and gene expression were *not* part of metabolism. Ontology developers: Are there guidelines about this anywhere ?

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale,

I agree with you. The ones I have queried already have a metabolism parentage, and if that should exist, it should  be "cellular metabolic process", based on  the logic that it has both "cellular process" and "metabolic process" parentage.

I'm not sure how far the 'solution' would go. I thought definitely signal transduction. I'm not so sure about "gene expression" although that would make sense to me too.

The tickets I opened were carried forward from old tickets because the metabolic/cellular process parentage was present without "cellular metabolic process". If the "metabolic process" parentage is removed that's also O.K.

**Comment by paolaroncaglia** [comment]
Hi @ValWood  and @pgaudet ,

Summarising and trying to simplify, this ticket is now about whether ‘positive regulation of GTPase activity’ and ‘regulation of Ras protein signal transduction’ should be under metabolism or not. They are not at the moment, and you both agree that indeed they shouldn’t, so I’m closing this ticket. 
Pascale, I’m not aware of any existing guidelines about signaling and gene expression not being part of metabolism, just endless discussions ;-)

Thanks,

Paola

**Comment by ValWood** [comment]
Hi Paola

positive regulation of GTPase activity is currently under metabolism?

VAl

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

You’re right. Apologies, that was hard to see, as the link is far upstream of the term itself and is via
positive regulation of catalytic activity is_a positive regulation of metabolic process
This link is inferred (note for self: it’s not in the list of ETINEs). It comes from 
catalytic activity part_of metabolic process
This link, instead, was added manually.

So there are two aspects to this link:

1) The link to metabolism itself:
Based strictly on the definitions, I can see the rationale behind this link. @ukemi  commented earlier that “Just one quick comment on metabolism. I don't think it will only include biosynthesis and catabolism. There are clearly cases where biochemicals are metabolized, but are not broken down or built into something else. Examples of this can be seen in the necessary parts of some of the children of specific types of glycolysis (glycerol to glycerone phosphate metabolic process).”
@ukemi , has there been any resolution on what metabolism should include and what not? Is this documented anywhere? 

2) The inference/propagation of ‘is_a regulation’ links via ‘part_of’.
We have been incorporating these automatically in the ontology for quite some time now. I can’t recall any discussion against their validity, but am calling upon @dosumis ’ memory to confirm this.

**Comment by ukemi** [comment]
Hi Paola and Val,

As far as I know, the decision was spelled out in the item to which Pascale had referred. It looks like Jane got rid of the catabolic terms, but I think the activities were still considered part of metabolism. 

-D

**Comment by paolaroncaglia** [comment]
Thanks @ukemi . So your recollection is that, at the Barcelona GOC meeting, it was agreed that the activity terms could/should still live under metabolism? If yes, then I'll close this ticket. If instead such a resolution was never reached, we should probably bring this up at an editors' or an annotation call.

**Comment by ukemi** [comment]
I'm not sure that agreement about metabolism was ever specified. I think the agreement was to remove them from catabolism. It makes sense to me that it is still metabolism.

**Comment by ukemi** [comment]
@deustp01
Would like to hear Peter's take on this.

**Comment by ukemi** [comment]
Looking over the Barcelona notes it looks like the decision might have been to not have these terms be children of metabolism either.

**Comment by deustp01** [comment]
My take (no recollection whether I said anything in Barcelona and if so whether this now agrees or contradicts) is that GTP hydrolysis by small GTPases (RHO, RAN, RAS, etc.) has direct regulatory consequences but no direct metabolic ones. Analogously, I wouldn't classify the autophosphorylation of ligand-bound EGF and FGF receptors as metabolism, even though ATP is metabolized to ADP and an amino acid side chain hydroxyl group is phosphorylated, because the direct effect is regulatory.

**Comment by ukemi** [comment]
So we need to remove the MF-BP part_of relation between catalytic activity and metabolic process.

**Comment by deustp01** [comment]
That sounds right, yes

**Comment by paolaroncaglia** [comment]
Thanks all for your feedback. 
@ValWood , @pgaudet , now done - removed part_of link between catalytic activity and metabolic process (and between respective regulation terms).
