### ISSUE TITLE
MP translesion synthesis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11701]
should this be a child of 
DNA synthesis involved in DNA repair GO:0000731?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11531](https://sourceforge.net/p/geneontology/ontology-requests/11531)

**Comment by ValWood** [comment]
I still can't see any problem with adding this parent.

"This process can be mutagenic depending on the damaged nucleotide and the inserted nucleotide." in the translesion term def isn't a differentia, (you could remove it without changing the def) so if the rest is true , the proposed parent is OK.

**Comment by paolaroncaglia** [comment]
Done.
