### ISSUE TITLE
GO:0015103 inorganic anion transmembrane transporter activity relationship to

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11703]
GO:0015103 inorganic anion transmembrane transporter activity

should 
GO:0005452	inorganic anion exchanger activity be a child of this (or is there even a difference?)

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11533](https://sourceforge.net/p/geneontology/ontology-requests/11533)

**Comment by ValWood** [comment]
Looks like this  one just needs an is_a relationship adding?

**Comment by dosumis** [comment]
Strongly agree with Midori on this one.  Keeping exchanger activities distinct from transporters is critical for representing neurobiology.

Should be subclass of: "secondary active transmembrane transporter activity" (GO:0015291) 
as well as
'inorganic anion transmembrane transporter activity' (GO:0015103)

Have fixed.
