### ISSUE TITLE
rename cytokinesis term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11704]
Term the wrong way around:

GO:1903478 mitotic contractile ring assembly involved in actin filament bundle convergence
Any actin filament bundle convergence that is involved in mitotic actomyosin contractile ring assembly.

Should be called 

GO:1903478 actin filament bundle convergence involved in  mitotic contractile ring assembly 

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11534](https://sourceforge.net/p/geneontology/ontology-requests/11534)

**Comment by paolaroncaglia** [comment]
@ValWood

Done.
