### ISSUE TITLE
logical defs for circulating complexes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11711]
```
[Term]
id: GO:0071746
name: IgA immunoglobulin complex, circulating
namespace: cellular_component
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgA isotype and two identical immunoglobulin light chains, held together by disulfide bonds, sometimes complexed with J chain or J chain and secretory component, and present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, ISBN:0781765196, PMID:16362985]
comment: Note that an IgA immunoglobulin complex has the function of antigen binding if a suitable antigen is available.
synonym: "IgA antibody" EXACT [GOC:add]
synonym: "IgA1 antibody" NARROW [GOC:add]
synonym: "IgA2 antibody" NARROW [GOC:add]
is_a: GO:0042571 ! immunoglobulin complex, circulating
is_a: GO:0071745 ! IgA immunoglobulin complex
created_by: midori
creation_date: 2010-03-24T01:44:53Z
```

Options:
1. Differentium: is part_of some extracellular
2. Differentium: has_quality some PATO:new circulating
3. Differemtium: output_of some GO:secretion by cell
4. Differentium: located_in/part_of some circulatory system

The last seems too strong given the text definition (which allows for mucosa and non-circulatory tissues), but the label "circulating" suggests circulatory

I can make changes once I have go ahead on pattern

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/11542](https://sourceforge.net/p/geneontology/ontology-requests/11542)

**Comment by pgaudet** [comment]
According to the definitions, these complexes are identical, but either located in the plasma membrane or secreted.  

I propose we obsolete 
GO:0042571 immunoglobulin complex, circulating
GO:0071746 IgA immunoglobulin complex, circulating
GO:0071739 IgD immunoglobulin complex, circulating
GO:0071743 IgE immunoglobulin complex, circulating
GO:0071736 IgG immunoglobulin complex, circulating
GO:0071754 IgM immunoglobulin complex, circulating 

and replace_by their respective parents.

**Comment by raymond91125** [comment]
https://www.linkedin.com/pulse/membrane-bound-immunoglobulins-b-cell-receptor-part-11-roohi-bansal
"Immunoglobulins can exist in 2 forms: secreted immunoglobulin (sIg) and membrane-bound immunoglobulin (mIg). The five classes of antibodies IgG, IgA, IgD, IgE, and IgM can be expressed either as secreted immunoglobulin or membrane-bound immunoglobulin."

The membrane-bound forms have additional trans-membrane domains. Do we really want to obsolete them (with 111 EXP annotations)?

**Comment by deustp01** [comment]
Relying only on memory and hoping @addiehl will step in here, I don't think all of IgG, IgA, IgD, IgE, and IgM have soluble and membrane-associated forms due to alternative splicing to yield carboxy termini lacking (soluble) or having (membrane-associated) amino acid sequences.

But, for the immunoglobulin heavy chains that can undergo this sort of alternative splicing, do we really want to say that the two products are identical for purposes of GO annotation? (This is a question, not an argument: maybe we do want to do this, and rely on additional GO cell_component annotations to distinguish the soluble and membrane-associated complexes?)

**Comment by addiehl** [comment]
We do not want to obsolete any of these classes!

**Comment by pgaudet** [comment]
Hi Alex, 

Thanks for the feedback. Can you please provide a definition? Right now it's defined as the same complex, if the complexes are the same but present in different locations, we would specify this as an extension. 

Thanks, Pascale

**Comment by raymond91125** [comment]
I have the logical definition for GO:0042571 immunoglobulin complex, circulating as 'immunoglobulin complex' and ('output of' some 'secretion by cell'). Any objections or suggestions?

**Comment by addiehl** [comment]
I think this is a suitable solution, since we are not able to distinguish the membrane-bound and secreted forms by adding logical axioms that refer to their alternatively spliced heavy chains.

**Comment by raymond91125** [comment]
Thanks to all for inputs.
