### ISSUE TITLE
query GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11721]
I am trying to figure the differenece between these:

 GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity 
Catalysis of the reaction: a tRNA with a 3' cytidine + CTP = a tRNA with a 3' CC end + diphosphate.

 GO:0052927 CTP:tRNA cytidylyltransferase activity
Catalysis of the reaction: a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate.

the genes i am annotating seem to be annotated to both and they have identical EC number.
What is a CC end?

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11552](https://sourceforge.net/p/geneontology/ontology-requests/11552)

**Comment by ValWood** [comment]
Looks like resolution reached but not implemented?

**Comment by ValWood** [comment]
This looks close to a solution?
Also, related to this ticket?
https://github.com/geneontology/go-ontology/issues/11996

**Comment by ValWood** [comment]
It sounds like a resolution was reached but never implemented.

**Comment by ValWood** [comment]
This ticket was never assigned to anyone @pgaudet 

Assigning to Harold....
@hdrabkin  this looks like a fairly straightforward parent child relationship? or merge?

**Comment by hdrabkin** [comment]
Final (I hope comments)
My expert never got back to me (
on: CCA tRNA nucleotidyltransferase activity (<- new?)
A tRNA precursor + 2 CTP + ATP <=> a tRNA with a 3' CCA end + 3 diphosphate
 Each C is added separately, as is the A once the C's are added. THis proposed term seems more like a summary of the entire process (and note in some cases, two different enzymes are needed). SO I would feel uncomfortable making this activity term. 


ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity
Catalysis of the reaction: a tRNA with a 3' CC end + ATP = a tRNA with a 3' CCA end + diphosphate
This would appear to be GO:0004810 

>> CTP:3'-cytidine-tRNA cytidylyltransferase activity
GO:0052927 CTP:tRNA cytidylyltransferase activity
A tRNA precursor + 2 CTP <=> a tRNA with a 3' CC end + 2 diphosphate
  Again, these are done in two steps, so I'm wondering if

**Comment by ValWood** [comment]
So is no action required here?

I still don't understand the difference between these 2 terms

I have 2 GPs and both are annotated to both?  They have the same EC number

GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity
Catalysis of the reaction: a tRNA with a 3' cytidine + CTP = a tRNA with a 3' CC end + diphosphate.

GO:0052927 CTP:tRNA cytidylyltransferase activity
Catalysis of the reaction: a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate.

See original comment.

 So  merge or close  (If closed I'll assume based on the EC that our annotation is OK and remain confused....)

**Comment by ValWood** [comment]
Or parent child, are they responsibly for sucessive additions and one is a specific reaction?

**Comment by hdrabkin** [comment]
If my expert can't find a case for a separate gene product for the two CTP transferases, I'm inclined to merge. 
I also see I need to merge the two ATP transferase terms, which I should have done this morning.

**Comment by hdrabkin** [comment]
Still waiting; shouldn't be too long.

**Comment by hdrabkin** [comment]
My  expert got back to me
To his knowledge, there is no case where an just adds the first C. It's always two consecutive Cs
so
GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity
Catalysis of the reaction: a tRNA with a 3' cytidine + CTP = a tRNA with a 3' CC end + diphosphate.
GO:0052927 CTP:tRNA cytidylyltransferase activity
Catalysis of the reaction: a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate.

Should get merged.

**Comment by hdrabkin** [comment]
Ok, now I see various and sundry problems here which might require an annotation review.
There are 3 types of enzymes involved here
1. CCA tRNA nucleotidyltransferase.  adds CCA  consecutively, but can also add A to a 3' CC.
THIS is the activity that should be annotated to for most organisms.
This is EC:2.7.7.72, CCA tRNA nucleotidyltransferase.
Even if all that is measured is "A" addition, this is the enzyme that does in

2. in SOME organisms, the CC gets added by one enzyme and the A gets added by a second enzyme.   In Aquifex aeolicus, Deinococcus radiodurans, Bacillus  halodurans, and Synechocystis sp., CCA synthesis is catalyzed by two nucleotidyltransferases (CC-adding and A-adding enzyme)
in a stepwise addition of two C and one A residues.

This also means that the reaction in GO indicating addition of a single A to the 3'end of a tRNA-CC should only be used for cases like #2.

**Comment by hdrabkin** [comment]
Bottom line is that I think an annotation review might be in order.

**Comment by hdrabkin** [comment]
GO:005292 ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity; should be used only for case 2
GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity; should not be used; should be obsoleted 

GO:0052927: CTP:tRNA cytidylyltransferase activity; case 2 only, different gene product
 It's def Catalysis of the reaction: a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate., should be changed to Catalysis of the reaction: a tRNA precursor + 2CTP = a tRNA with a 3' CC end

GO:0001680 tRNA 3'-terminal CCA addition This is EC 2.7.7.72 ; this can added either the C's or the As as needed.  This is what all other organisms should be annotated to.

**Comment by hdrabkin** [comment]
OR, since I don't see any annotations properly attributed to 927 and 292, I could merge those into 1680 and all current annotations would be correct.

**Comment by ValWood** [comment]
Do the merge ;)

v

**Comment by ValWood** [comment]
Hi Harold, any closure on this one?

**Comment by hdrabkin** [comment]
Even RHEA uses a single id (does not break out the steps RHEA:14433 the EC 2.7.7.72)
However, if we wanted to annotate quifex aeolicus, Deinococcus radiodurans, Bacillus halodurans, and Synechocystis sp., CCA synthesis is catalyzed by two nucleotidyltransferases (CC-adding and A-adding enzyme) we DO need a CC synthesis term for one enzyme and an A term for the other.

**Comment by hdrabkin** [comment]
Preparing for the merge
d: GO:0004810
name: tRNA adenylyltransferase activity
def: "Catalysis of the reaction: ATP + tRNA(n) = diphosphate + tRNA(n+1)." [EC:2.7.7.25]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:2.7.7.25
=> this is a grouping term in GO, remove EC, remove comment

This should actually be merged but there is a problem (there is a ticket on this already). 
#19854, #17855, and #11721

1. in most annotations, one monitors the enzyme activity using only the A- addition, but the enzyme is still the CCA addition enzyme.  Some use CTP also.
2. However, although most organisms have ONE enzyme, there are some that have two separate enzymes, one to add the CC, and a separate to add the A.   (PMID:18523015)
So I was going to merge all of them to just CCA, BUT, needed to know if ANY of the existing annotations were to the organisms using the two enzymes. 

Note: RHEA does not break out the CCA into 3 reactions (much like they do not split out each of the AARs into two reactions, A; creation of the aa-amp, and B: transfer from aa-amp to aa-tRNA (one can measure both reactions).
So, we actually need.
1. term for the CCA enzyme; term merge for most of these
2. a separate CC term
3. a separate A term; 
2 and 3 need a taxon restriction to only those organisms that process the tRNA 3' end with 2 separate enzyme.

I will also copy this to the other tickets.

**Comment by pgaudet** [comment]
There are 2 related RHEAs: 
https://www.rhea-db.org/rhea/60012 (no EC): a tRNA with a 3' CC end + ATP = a tRNA with a 3' CCA end + diphosphate - I think this represents the 'A' only reaction you describe above
and 
https://www.rhea-db.org/rhea/14433 (EC:2.7.7.72) : a tRNA precursor + ATP + 2 CTP = a tRNA with a 3' CCA end + 3 diphosphate

**Comment by hdrabkin** [comment]
These are rectified in ticket #19854, so will close this one now.
