### ISSUE TITLE
possible MP ubiquinol-cytochrome-c reductase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11726]
should
GO:0008121 - ubiquinol-cytochrome-c reductase activity
have the parentage “election carrier activity”?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11557](https://sourceforge.net/p/geneontology/ontology-requests/11557)

**Comment by ValWood** [comment]
ubiquinol-cytochrome-c reductase activity
is the function of
mitochondrial electron transport, ubiquinol to cytochrome c
The transfer of electrons from ubiquinol to cytochrome c that occurs during oxidative phosphorylation, mediated by the multisubunit enzyme known as complex III.

in eukaryotes

Does that help?

**Comment by ValWood** [comment]
@pgaudet This one has no-one assigned.
I think its a fairly strightforward missing parentage.

ubiquinol-cytochrome-c reductase activity
is an electron carrier from the def,  but if you disagree please close.
