### ISSUE TITLE
inhibition of APC-Cdc20 complex activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11757]
GO:0060565
inhibition of APC-Cdc20 complex activity
Biological ProcessDefinitionAny process that prevents the activation of APC-Cdc20 complex activity regulating the mitotic cell cycle.

There are  a number of problems with this term, and its annotations.

1. Biology
As far as I am aware the only think which inhibits the APC-cdc20 complex is the MCC (mitotic checkpoint complex). It does this by blocking its substrate binding sites and repositioning Cdc20 away from the APC/C subunit Apc10 22898774, Fig 1
https://sourceforge.net/p/geneontology/ontology-requests/11573/

2. Existing term issues
The existing term has lots of annotations to F-box proteins which are nothing to do with the inhibition of the complex (they are substrate adaptors). Some of the annotations appear to be related to SCF ligase, not APC. I suggest we obsolete this term and start again…

The existing term is not defined fully it should be “Any process that prevents the activation of APC-Cdc20 complex activity regulating the mitotic cell cycle metaphase /anaphase transition”.

3. Suggested fix:
I think we need a replacement Molecular Function term to describe the activity of the MCC against the APC-Cdc20 complex

A molecular function which prevents the activation of the APC-Cdc20 complex activity to negatively regulate the mitotic metaphase anaphase transition.
It would have a F-P link to negative regulation of the metaphase/anaphase transition.
The only gene products which would be annotated to this term would be MCC members (excluding Cdc20 itself).

If we don’t want to do this (there is a precedent for the APC which I have followed previously but I am not sure we would want to do this on a complex by complex basis). If not we would need something like:

“ubiquitin ligase inhibitor activity” and could use extensions to say which complex, and we wouldn’t be able to add any F-P links we would need to do this at annotation time.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11589](https://sourceforge.net/p/geneontology/ontology-requests/11589)

**Comment by tberardini** [comment]
#11977 - need to look at the related CC terms as well, and get rid of those that are too specific.

**Comment by ValWood** [comment]
Hi Tanya,

Can we obsolete all of the APC-complex activity terms before the curation call where we are doing these papers?  We are doing papers related to this and their presence is going to be really confusing.

Cheers

Val

**Comment by tberardini** [comment]
Obsolete all of them without notice or very short notice?  Which ones from the set listed above with the annotation counts?  If I can reconstruct the discussion correctly, we will offer 'ubiquitin ligase activity' and similar activator/inhibitor/regulation terms as the consider terms.  Correct?

**Comment by ValWood** [comment]
Yes that is correct.
As I understand it, we should not have any "complex specific activities"

So here we should be using "ubiquitin ligase activity" "ubiquitin ligase inhibitor" "ubiquitin ligase activator" 
and all the MF terms which mention "APC" specifically should go. Actually  a merge would be better.....

**Comment by dosumis** [comment]
Strongly support this.  Danger of meaningless cycles : 'complex fu' capable of 'complex fu activity'
'Complex fu activity': "The activity if a fu complex."

**Comment by tberardini** [comment]
I like the merge idea.  No need for obsoletion notice then and the annotations will still be correct.  This should be straightforward.  

Famous last words.

**Comment by tberardini** [comment]
Here are the proposed merges, some may require the creation of new terms. Please review and advise/approve.

- GO:0051488 (96 annotations, 20 EXP)activation of anaphase-promoting complex activity

merge into 'activation of ubiquitin protein ligase activity' (**GO:new**) or into existing term 'positive regulation of ubiquitin protein ligase activity'?

- GO:0051487 (9 annotations) activation of anaphase-promoting complex activity involved in meiotic cell cycle

merge into 'activation of ubiquitin-protein ligase activity involved in meiotic cell cycle' (**GO:new**) or into existing term 'positive regulation of ubiquitin-protein ligase activity involved in meiotic cell cycle' ?

- GO:0061636 (0 annotations) mitotic anaphase-promoting complex activator activity

merge into ubiquitin ligase activator activity, GO:exists

- GO:0061637 (1 annotation) mitotic anaphase-promoting complex inhibitor activity

merge into ubiquitin ligase inhibitor activity, **GO:new**

- GO:0090645 (0 annotations) APC-Cdc20 complex inhibitor activity

merge into ubiquitin ligase inhibitor activity, **GO:new**

- GO:0007092 (43 annotations, 8 EXP) activation of APC-Cdc20 complex activity

merge into 'activation of ubiquitin protein ligase activity' (**GO:new**) or into existing term 'positive regulation of ubiquitin protein ligase activity'?

- GO:0090623 (0 annotations) activation of APC-fizzy related complex activity

merge into 'activation of ubiquitin protein ligase activity' (**GO:new**) or into existing term 'positive regulation of ubiquitin protein ligase activity'?

- GO:1903834 (1 annotation) regulation of APC-fizzy related complex activity

merge into 'regulation of ubiquitin protein ligase activity', GO:exists

- GO:0060564 (37 annotations, 7 EXP) negative regulation of APC-Cdc20 complex activity

merge into 'negative regulation of ubiquitin protein ligase activity', GO:exists

- GO:1903835 (0 annotations) positive regulation of APC-fizzy related complex activity

merge into 'positive regulation of ubiquitin protein ligase activity', GO:exists

- GO:1904190 (0 annotations) negative regulation of APC-fizzy related complex activity

merge into 'negative regulation of ubiquitin protein ligase activity', GO:exists

**Comment by tberardini** [comment]
@ValWood, please comment on the suggested merges that have questions associated to them

**Comment by ValWood** [comment]
Q1.
GO:0051488 (96 annotations, 20 EXP)activation of anaphase-promoting complex activity
merge into 'activation of ubiquitin protein ligase activity' (GO:new) or into existing term 'positive regulation of ubiquitin protein ligase activity'?

 This should definitely be  a process term, because it includes annotations which are not direct "enzyme inhibitors", so  'positive regulation of ubiquitin protein ligase activity' seems the best option here

**Comment by ValWood** [comment]
GO:0051487 (9 annotations) activation of anaphase-promoting complex activity involved in meiotic cell cycle
merge into 'activation of ubiquitin-protein ligase activity involved in meiotic cell cycle' (GO:new) or into existing term 'positive regulation of ubiquitin-protein ligase activity involved in meiotic cell cycle' ?

-
yep, this is  still a weird term, but  can look  at this later...

**Comment by ValWood** [comment]
GO:0061636 (0 annotations) mitotic anaphase-promoting complex activator activity
merge into ubiquitin ligase activator activity, GO:exists

GO:0061637 (1 annotation) mitotic anaphase-promoting complex inhibitor activity
merge into ubiquitin ligase inhibitor activity, GO:new

GO:0090645 (0 annotations) APC-Cdc20 complex inhibitor activity
merge into ubiquitin ligase inhibitor activity, GO:new


-- 
yes to all

**Comment by ValWood** [comment]
The rest seem to be process terms too. They will need to merge up to existing processes because they include  upstream regulators in addition  to those  directly inhibiting the APC

**Comment by tberardini** [comment]
Thanks, Val, for adding this in through TermGenie.
---------
id: GO:1990948
name: ubiquitin ligase inhibitor activity
namespace: molecular_function
def: "Stops, prevents or reduces the activity of a ubiquitin ligase." [PMID:21389117]
is_a: GO:0055104 ! ligase inhibitor activity

**Comment by tberardini** [comment]
Ok, I've done all the merges of the regulation and activator/inhibitor terms.  I hope it all went well, that was much more complicated that I'd hoped it would be.  

I think what remains to do in this ticket is to merge the following:

GO:0090302 APC-Cdc20 complex activity
GO:0090622, APC-fizzy related complex activity

into GO:0061630, ubiquitin protein ligase activity.

Is that right?

**Comment by ValWood** [comment]
I think so. I hope it went well ;)

**Comment by tberardini** [comment]
Term merging done.  Closing!
