### ISSUE TITLE
TPV DNA duplex unwinding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11765]
DNA duplex unwinding is under DNA geometric change, it should be under DNA metabolism instead

(DNA duplex unwinding is helicases, DNA geometric change is topoisomerases.)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11597](https://sourceforge.net/p/geneontology/ontology-requests/11597)

**Comment by ValWood** [comment]
So this was correct so closing...
