### ISSUE TITLE
TPV resolution or meiotic recombination intermediates -parent

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11762]
reciprocal meiotic recombination is not part of meiotic chromosome segregation, even though it is important for segregation it precedes it (I think this is correct).
However the descendent term “resolution or meiotic recombination intermediates” is par of meiotic chromosome separation. I don’t think it should be?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11594](https://sourceforge.net/p/geneontology/ontology-requests/11594)

**Comment by ValWood** [comment]
might crop up again will address then
