### ISSUE TITLE
TPV chromatin remodelling

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11764]
chromatin remodelling should not be is_a chromatin modification

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11596](https://sourceforge.net/p/geneontology/ontology-requests/11596)

**Comment by paolaroncaglia** [comment]
Also see https://github.com/geneontology/go-ontology/issues/8689

**Comment by paolaroncaglia** [comment]
Will be fixed by https://github.com/geneontology/go-ontology/issues/8689, so closing as duplicate.
