### ISSUE TITLE
catabolism and biosynthesis relations

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11779]
We need to create sub-relations of the has-input and has-output relations that describe the entities that are being catabolized and synthesized in x-catabolism and x-biosynthesis terms.

Then we need to globally replace all of the current has-input and has-output relations that are currently defined. 

Reported by: ukemi

Original Ticket: [geneontology/ontology-requests/11612](https://sourceforge.net/p/geneontology/ontology-requests/11612)

**Comment by ukemi** [comment]
I believe this was fixed with the new primary input/output relations
