### ISSUE TITLE
Export vs transmembrane export

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11784]
Stemming from an email request from Ruth and Klaus:

“Could you please move ferrous iron export (GO:1903988) to be a child of ferrous iron transmembrane transport (GO:1903874)​. This would provide the same ontology structure as what there is for sodium ion export.”

‘ferrous iron export’ (GO:1903988) was requested by Ruth and Klaus to annotate ferroportin. Which is in fact the only existing annotation to this term and children, as of today in QuickGO. Ferroportin is a transmembrane protein that moves iron from inside the cytoplasm to outside the cell, so a more precise term would be ‘ferrous iron transmembrane export from cell’. The rationale behind the distinction between simple ‘export’ and ‘transmembrane export’ is that, even if all known instances of ferrous iron export occurred via a membrane, we cannot imply this mechanism for granted, so we need to differentiate. (This is an issue e.g. for calcium, and something that we editors discussed at length previously, see https://sourceforge.net/p/geneontology/ontology-requests/10621/.)
Unfortunately, at the moment there isn’t a specific TG template for ‘transmembrane export’, so such a term would need to be requested via SF.
In this particular case, as BHF-UCL were the only ones using this term and clearly meaning that it’s transmembrane, I will edit it to be transmembrane rather than creating a new one. However, I will also need to edit its regulation children. Plus, the ‘ferrous iron import’ branch needs work too. ‘ferrous iron import’ is textually defined as transmembrane (but not logically), while its child ‘ferrous iron import into cell’ is textually and logically defined as being agnostic to transmembrane vs. endocytosis.

Notes for self: 
1) For a good logical def, see GO:0044746 amino acid transmembrane export, and its child.
2) The current definition comment for ‘ferrous iron export’ (GO:1903988) could be made nicer. It now reads “ferroportin, Slc40a1, Q9JHI9”.

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/11617](https://sourceforge.net/p/geneontology/ontology-requests/11617)

**Comment by paolaroncaglia** [comment]
Note for self: ferrous iron export (GO:1903988) now is_a ferrous iron transmembrane transport (GO:1903874)​, so the original request was satisfied. Looks like some cleaning up of that branch may still be beneficial.

**Comment by paolaroncaglia** [comment]
Fixed ‘ferrous iron export’.
