### ISSUE TITLE
palmitoleyl terms - spelling issues?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11790]
From an email from Susan Tweedie, now at HGNC:

I am renaming a gene that is annotated as with GO:1990699 ; palmitoleyl hydrolase activity and was a bit surprised to find that term had no matches in PubMed. I don't know anything about this subject but wondered if there could be a problem with spelling...

GO:1990699	palmitoleyl hydrolase activity
Showing results for palmitoleoyl hydrolase. Your search for palmitoleyl hydrolase retrieved no results

GO:0045234	protein palmitoleylation	
Showing results for palmitoylation. Your search for palmitoleylation retrieved no results.

GO:1990697	protein depalmitoleylation
PMD:Showing results for depalmitolyation. Your search for depalmitoleylation retrieved no results.

GO:1990698	palmitoleoyltransferase activity - term name ok but search with palmitoleyl from definition gives:  
23 matches but says, Did you mean: palmitoleoyl (83 items) (so you may not have the most common one - or these could be completely different things!

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/11624](https://sourceforge.net/p/geneontology/ontology-requests/11624)

**Comment by paolaroncaglia** [comment]
Summing up, all of those labels (as well as similar ones in GO) are legitimate. Closing now.
