### ISSUE TITLE
GO:0035068 micro-ribonucleoprotein complex parentage

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11828]
Hi,

I'm wondering whether GO:0035068 micro-ribonucleoprotein complex 
Def: A complex containing both protein and micro-RNA (miRNA) molecules. miRNAs are approximately 22 nucleotide noncoding RNAs derived from endogenous genes; they are processed from the stem of a longer hairpin like structure termed a pre-miRNA. 

should be a child of GO:0016442 RISC complex 
Def: A ribonucleoprotein complex that contains members of the Argonaute family of proteins, small interfering RNAs (siRNAs) or microRNAs (miRNAs), and miRNA or siRNA-complementary mRNAs, in addition to a number of accessory factors. The RISC complex is involved in posttranscriptional repression of gene expression through downregulation of translation or induction of mRNA degradation.

See final paragraph of http://genesdev.cshlp.org/content/16/9/1025.full.html - are the miRISC and miRNP the same thing?

Looking at the annotations to miRNP term, these are all proteins expected to be in the RISC complex, except maybe Fmr1 (Q9NFU0), but which has also been annotated to RISC complex.

If it should be a child of RISC complex, then there should be an equivalent term for siRNAs, i.e. siRISC complex (See http://www.ncbi.nlm.nih.gov/pubmed/15691656).

Thanks,
Rachael.

Reported by: rachhuntley

Original Ticket: [geneontology/ontology-requests/11664](https://sourceforge.net/p/geneontology/ontology-requests/11664)

**Comment by bmeldal** [comment]
I'm not sure, Pascale. I looked at the review from 2002 and then just checked Wikipedia as I haven't curated RISC yet. Looks like RISC is at minimum an argonaute protein (ago1 or ago2 or other equivalents) (drome has R2D2 :) ) and a non-codong RNA. Then they call the complex dep on which RNA is incorporated.

**Comment by pgaudet** [comment]
So maybe this term is not required anymore and this ticket can be closed ? 
@rachhuntley

**Comment by bmeldal** [comment]
In that case I agree that miRISC and miRNP are indeed the same thing. I'd follow Rachael's suggestion and re-house those annotations that are not to argonaute proteins to RISC-loading complex or similar.

Btw, I looked at UniProt entries, too, not just Wikipedia - written in haste ;-) and UniProt also don't have very defined defs for the RISC complex beyond argonaute+types of ncRNAs

**Comment by pgaudet** [comment]
So, is a merge OK @bmeldal ?
