### ISSUE TITLE
OTR: parentage of GO:1904091 ! peptidyl carrier protein activity involved in nonribosomal peptide biosynthesis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11829]
GO:1904091 ! peptidyl carrier protein activity involved in nonribosomal peptide biosynthesis is a child of GO:1900750 ! oligopeptide binding, which is defined as "Interacting selectively and non-covalently with an oligopeptide". This is incorrect, as the NPRS chain is covalently attached to the carrier protein. See: http://www.sciencedirect.com/science/article/pii/S0959440X10000126

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/11665](https://sourceforge.net/p/geneontology/ontology-requests/11665)

**Comment by ValWood** [comment]
GO:1900750 ! oligopeptide binding
is no longer a parent of GO:1904091
