### ISSUE TITLE
automate synonym checks

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11822]
Prevent reuse of the same string with two different scopes for the same class

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/11658](https://sourceforge.net/p/geneontology/ontology-requests/11658)

**Comment by pgaudet** [comment]
This was done for EXACT synonyms. https://github.com/geneontology/go-ontology/pull/15504
I don't think we can do it for all synonym types.

**Comment by pgaudet** [comment]
@dougli1sqrd is this implemented ?

**Comment by balhoff** [comment]
This is covered by https://github.com/geneontology/go-ontology/blob/master/src/sparql/duplicate-synonym-violation.sparql.
