### ISSUE TITLE
MP, various transporters /substrate specific

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11840]
It would be useful if the substrate-specific descriptions of transmembrane transport could be grouped under
substrate-specific transmembrane transporter activity

Currently many are, but many
phosphate transmembrane transporter activity
modified amino acid transmembrane transporter activity
salt transmembrane transporter activity
organic phosphonate transmembrane transporter activity
galactosamine transmembrane transporter activity
iron chelate transmembrane transporter activity
organic hydroxy compound transmembrane transporter activity
vitamin transmembrane transporter activity

(or there are redundant relations which could be removed)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11676](https://sourceforge.net/p/geneontology/ontology-requests/11676)

**Comment by pgaudet** [comment]
Hi @ukemi 
I merged 'substrate-specific transmembrane transporter activity' into 'transmembrane transporter activity'; was this not correct ? 
https://github.com/geneontology/go-ontology/issues/14491

Pascale

**Comment by ukemi** [comment]
This goes back to the discussion that we had at a GOC meeting a while ago where we thought it was important to distinguish between transporters that could transport more than one cargo versus transporters that were specific to a certain type of cargo.  I'm not certain the logical defs will work now if the term actually means the transporters are specific. You will have to investigate that. #11840. If I recall, @huaiyumi  felt strongly about how we represent these and has expertise in the field. Perhaps work with him to make sure everything is ok.

**Comment by ValWood** [comment]
@paolaroncaglia  asked me earlier to close,  but this request predates  @ukemi comment. Still want me to close?

**Comment by ValWood** [comment]
Actually, now that I look at the direct children of transmembrane transporter, I think it might help curators to group the  substrate specific axis of classification under a single term. Mainly to help curators when browsing for the correct term....

So the list  directly under transmembrane transport would be:



export across plasma membrane
mitochondrial transmembrane transport
import across plasma membrane
vacuolar transmembrane transport
substrate-specific transmembrane transporter activity (but this grouping terms could also be inorganic /organic compound transmembrane transport), either would be good. We probably don't need both.

**Comment by ValWood** [comment]
I did not know substrate-specific meant this:

"we thought it was important to distinguish between transporters that could transport more than one cargo versus transporters that were specific to a certain type of cargo"

I don't know how we would know this? we only know what has been assayed. If a transporter transports >1 compound we annotate to multiple activities. Why do we need to capture  in the ontology that a transporter only transports one thing? We don't do this for enzymes? It seems i) outside the scope of GO, and ii) impossible to know from most expereiments....

**Comment by paolaroncaglia** [comment]
@ValWood 
Actually, the ticket I suggested might be closed was a different one :-)
https://github.com/geneontology/go-ontology/issues/12317
I have nothing to do with the present one I'm afraid.
