### ISSUE TITLE
odd comment on term chromatin organization involved in regulation of transcription GO:0034401

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11856]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0034401

has the comment 

This term should not be used for direct manual annotation. This term may be used for mapping to external vocabularies in order to create electronic annotations.

but it has no descendants.

this rings a bell, I think there might be another ticket where some other terms 
need to be moved to be children of this term?

Will take a look later....

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11694](https://sourceforge.net/p/geneontology/ontology-requests/11694)

**Comment by dosumis** [comment]
As noted above, this is covered in #11628
