### ISSUE TITLE
problem with descendants of carbon catabolite repression

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11865]
carbon catabolite repression is correctly defined:

A transcription regulation process in which the presence of one carbon source leads to the modulation of the frequency, rate, or extent of transcription of specific genes involved in the metabolism of other carbon sources.

Note the clause *genes involved in the metabolism of other carbon sources*

However it has descendants which do not observe this specificity

GO:0046015 regulation of transcription by glucose
Any process involving glucose that modulates the frequency, rate or extent or transcription.

GO:0000409 regulation of transcription by galactose
Any process involving galactose that modulates the frequency, rate or extent or transcription.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11703](https://sourceforge.net/p/geneontology/ontology-requests/11703)

**Comment by ukemi** [comment]
I agree. I moved them to the parent.
