### ISSUE TITLE
rename GO:0000981 sequence-specific DNA binding RNA polymerase II transcription factor activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11860]
Hi David,

Can
GO:0000981 sequence-specific DNA binding RNA polymerase II transcription factor activity

be renamed for consistency  to

GO:0000981 RNA polymerase II sequence-specific DNA binding  transcription factor activity
to match parents and chidren. I can never figure why it doesn't pop up when I start typing

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11698](https://sourceforge.net/p/geneontology/ontology-requests/11698)

**Comment by ukemi** [comment]
Hi Val,

This was part of the transcription factor renaming overhaul that David did. It is now:
    RNA polymerase II transcription factor activity, sequence-specific DNA binding and is consistent with all of its parents etc.

-D
