### ISSUE TITLE
TPV detoxification

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11869]
Detoxification has a "metabolic process" ancestry.

However, the def of some descendants is, for example:
detoxification of cadmium ion

Any process that reduces or removes the toxicity of cadmium ion. These may include transport of cadmium away from sensitive areas and to compartments or complexes whose purpose is sequestration of cadmium ion. 

so, not all detoxification is metabolism.....

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11707](https://sourceforge.net/p/geneontology/ontology-requests/11707)

**Comment by dosumis** [comment]
Moved detoxification directly under biological_process.  Manually removed instantiated inferences to metabolic process terms from descendant classes.
