### ISSUE TITLE
Amino acid transporter and transport terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11868]
Hi,

Just a question about the L-amino acid transmembrane transporter terms and corresponding BP terms for L-amino acid transmembrane transport.

Would it be possible to flesh out the BP terms so that all L-amino acid transmembrane transporter MF terms had a corresponding entry in BP for L-amino acid transmembrane transport?

It looks like some are there in BP, but not all.

Thanks,
--Kimberly

Reported by: vanaukenk

Original Ticket: [geneontology/ontology-requests/11706](https://sourceforge.net/p/geneontology/ontology-requests/11706)

**Comment by paolaroncaglia** [comment]
@vanaukenk
Hi Kimberly,
I'm going to close this ticket. If you did create BP 'chemical_transmembrane_transport' terms and if these are still not linked to corresponding 'chemical_transmembrane_transporter' terms, please let me know (or make a new ticket). Thanks!
Paola

**Comment by vanaukenk** [comment]
Hi Paola,

Thanks for checking about this ticket.

The terms I created for annotating the paper were:
id: GO:1904271
name: L-proline import across plasma membrane
id: GO:1904272
name: L-tryptophan import across plasma membrane
id: GO:1904273
name: L-alanine import across plasma membrane

Right now, I don't see the F-P links in the ontology between the L-proline transmembrane transporter activity, etc. terms and these BP terms.  Do you think they are still appropriate?

Thanks,
--Kimberly

**Comment by paolaroncaglia** [comment]
Hi Kimberly,

Looking at L-proline, 
L-proline transmembrane transporter activity is part_of proline transmembrane transport
and
L-proline import across plasma membrane is_a proline transmembrane transport
But if I create the term L-proline transmembrane transport, the latter link will be added automatically, and I can then place L-proline transmembrane transporter activity more granularly as part_of L-proline transmembrane transport.
I'll add the missing (intermediate) terms via TG and revise the part_of links...

Paola

**Comment by paolaroncaglia** [comment]
Just added
ID: GO:1904555 Label: L-proline transmembrane transport
ID: GO:1904556 Label: L-tryptophan transmembrane transport
ID: GO:1904557 Label: L-alanine transmembrane transport

@cmungall , @hdietze ,
Could you please remind me where we are with the issue of inferencing the correct (granular) part_of link automatically? Pardon my juvenile Alzheimer, but I've lost track of that discussion... Did we resolve that we should still do it manually? (No problem if so.)

Thanks,

Paola
