### ISSUE TITLE
Add synonym to GO:0001191 RNA polymerase II transcription factor binding transcription factor activity involved in negative regulation of transcription

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11873]
Hi

please would you add the broad synonym: RNA polymerase II transcription repressor activity
to 
GO:0001191 RNA polymerase II transcription factor binding transcription factor activity involved in negative regulation of transcription

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11711](https://sourceforge.net/p/geneontology/ontology-requests/11711)

**Comment by ValWood** [comment]
This seems to be done. Not sure why it was re-opened?
