### ISSUE TITLE
relationship between depurination and purine deoxyribonucleotide catabolic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11870]
this is

purine deoxyribonucleotide catabolic process
--depurination

that doesn't seem quite right?

It seems that depurination
The disruption of the bond between the sugar in the backbone and the A or G base, causing the base to be removed and leaving a depurinated sugar.

is not *necessarily* part of purine catabolism ?
or is it?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11708](https://sourceforge.net/p/geneontology/ontology-requests/11708)

**Comment by paolaroncaglia** [comment]
Following chat with Val, I removed the link 
depurination is_a: GO:0009155 ! purine deoxyribonucleotide catabolic process
