### ISSUE TITLE
Proposal to revise naming for transcriptional repressors & add a few grouping classes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11878]
On a [related ticket](https://sourceforge.net/p/geneontology/ontology-requests/11712/), we've been discussing how to shorten some long and confusing names for transcriptional repressors, e.g.

RNA polymerase II activating transcription factor binding transcription factor activity involved in negative regulation of transcription

Ruth wrote a comment on the original ticket with a general proposal for renaming and grouping transcriptional repressor terms.  I've made a fresh ticket for discussion here so that original ticket can be closed ones the specific issue it covers has been adressed.

---

---

PMID:24418103 describes:
Mechanisms of transcriptional repression can be divided into three categories; 
1. inhibition of the basal transcriptional machinery: repressors that interfere with the binding of RNA polymerase, TATA box-binding protein, and/or general transcription factors to transcription start sites; thus, preventing transcription initiation
2. ablation of transcriptional activator function: repressors targeting transcriptional activators and co-activators, resulting in their degradation, nuclear export, or inhibiting their ability to bind DNA. 
3. remodeling of chromatin : recruitment of chromatin remodeling factors, which cause epigenetic alterations on the genome.
## Plus 4: non-coding RNAs in transcriptional repression by interacting with chromatin modifying factors (Wang et al., 2010).

PMID:12785719 describes:
General repression: General repressor protein (or complex) either sequesters or modifies a central component of the Pre-initiation complex (PIC) or RNA polymerase II. Thus general repressor will down-regulate expression of all genes transcribed by this RNA polymerase.
Eg 1: Phosphorylation of RNA polymerase core subunit by herpes virus ICP22, UL13  kinases, which generates a non-functional polymerase and general repression[ ref 14].
Eg 2: Nucleosomes generally repress promoter activity by sequestering promoter DNA into chromatin [ref 15].

Gene-specific repression: Gene-specific repressors act by decreasing the concentration of a functional activator/co-activator at the promoter or by counteracting the stimulatory effect of these proteins on transcription. In addition, some repressors inhibit transcription by interacting in a promoter-specific fashion with components of the PIC or by recruiting chromatin-remodelling proteins.
Gene-specific repressors may:
Bind directly or indirectly to DNA,
## Regulate transcription from binding sites proximal [short-range repressors] or at a distance [long-range repressors] from the promoter [ref 16].

So considering the type of experiments we are annotating would it be possible to create MF terms with sensible names to represent these different classes of proteins?

Firstly do we have to have ‘RNA polymerase II’ included in the name, as the ontology will provide this information, and this can be included in the exact synonym?
If this can be removed we could have:
NEW GO Term 1. General transcription repressor activity (provide more specific terms as the data is annotated?)
Exact synonyms: 
RNA polymerase II general transcription repressor activity

NEW GO Term 2. Transcription factor binding repressor activity
Exact synonyms: 
Transcription factor binding gene-specific transcription repressor activity;
RNA polymerase II transcription factor binding gene-specific transcription repressor activity

NEW GO Term 3 From initial inquiry and child of NEW GO Term 2 above: activating transcription factor binding repressor activity
Exact synonyms: RNA polymerase II activating transcription factor binding transcription factor activity involved in negative regulation of transcription;
Activating transcription factor binding gene-specific transcription repressor activity;
RNA polymerase II activating transcription factor binding gene-specific transcription repressor activity

NEW GO Term 4. DNA binding transcription repressor activity
Exact synonyms: 
DNA binding transcription gene-specific transcription repressor activity;
Gene-specific DNA binding RNA polymerase II transcription repressor activity

NEW GO Term 5. Pre-initiation complex binding transcription repressor activity
Exact synonyms: 
Pre-initiation complex binding gene-specific transcription repressor activity;
Gene-specific Pre-initiation complex RNA polymerase II transcription repressor activity

NEW GO Term 6. Transcription repressor activity by regulation of chromatin-remodeling
Exact synonyms: 
Gene-specific transcription repressor activity by regulation of chromatin-remodeling;
Gene-specific RNA polymerase II transcription repressor activity by regulation of chromatin-remodeling

Note that several repressors will be annotated to more than one of these functions.
Plus the definitions would have to make it clear that these are repressing terms and not for co-repressing terms.

I am happy to help sort out definitions for these if the concept is agreed. 
In addition, this should be discussed with the transcription factor group in Norway. 

Best

Ruth

Reported by: dosumis

Original Ticket: [geneontology/ontology-requests/11716](https://sourceforge.net/p/geneontology/ontology-requests/11716)

**Comment by pgaudet** [comment]
Hi @RLovering Do you still want these terms (or the concepts?) It seems slightly different from the direction we took in the current remodeling. 

Thank you in advance for your response, Pascale

**Comment by RLovering** [comment]
Hi Pascale

As mentioned at the top of the ticket, it seems to me that the following repressors are well known to the transcription field, although not easy to define: PMID:24418103 describes:
Mechanisms of transcriptional repression can be divided into three categories;

1. inhibition of the basal transcriptional machinery: repressors that interfere with the binding of RNA polymerase, TATA box-binding protein, and/or general transcription factors to transcription start sites; thus, preventing transcription initiation
2. ablation of transcriptional activator function: repressors targeting transcriptional activators and co-activators, resulting in their degradation, nuclear export, or inhibiting their ability to bind DNA (or inhibiting a TF activity in some way).
3. remodeling of chromatin : recruitment of chromatin remodeling factors, which cause epigenetic alterations on the genome.

It seems to me that the recent discussions led to an agreement for terms to cover activities described in 1 and 3, but I don't think there is any term to describe a protein with one of the (several) functions described in 2. I don't want to edit the protein binding TF terms until there is a term I can use if it turns out that one of the proteins has a function described in 2, otherwise I will have to go back and reannotate again. Plus as we mentioned in the discussion the other week. Many of the proteins currently associated with the GO terms now describing 1 or 3 were associated with the term(s) assuming these described the function in 2. But we can't revise these until we have these other terms. 

I appreciate that you could just cover these 'activity' as processes but I think people will expect to see a MF term to describe the repressors that act on the DNAbinding TFs.

Thanks 

Ruth

**Comment by pgaudet** [comment]
> NEW GO Term 1. General transcription repressor activity (provide more specific terms as the data is annotated?)
Exact synonyms: RNA polymerase II general transcription repressor activity

Covered by 'GO:0003714 transcription corepressor activity'

> NEW GO Term 2. Transcription factor binding repressor activity
Exact synonyms:
Transcription factor binding gene-specific transcription repressor activity;
RNA polymerase II transcription factor binding gene-specific transcription repressor activity

Also covered by 'GO:0003714 transcription corepressor activity'

> NEW GO Term 3 From initial inquiry and child of NEW GO Term 2 above: activating transcription factor binding repressor activity
Exact synonyms: RNA polymerase II activating transcription factor binding transcription factor activity involved in negative regulation of transcription;
Activating transcription factor binding gene-specific transcription repressor activity;
RNA polymerase II activating transcription factor binding gene-specific transcription repressor activity

Not needed anymore. 

> NEW GO Term 4. DNA binding transcription repressor activity
> Exact synonyms:
> DNA binding transcription gene-specific transcription repressor activity;
> Gene-specific DNA binding RNA polymerase II transcription repressor activity

Already in the ontology. 

> NEW GO Term 5. Pre-initiation complex binding transcription repressor activity
> Exact synonyms:
> Pre-initiation complex binding gene-specific transcription repressor activity;
> Gene-specific Pre-initiation complex RNA polymerase II transcription repressor activity

Also covered by corepressor

> NEW GO Term 6. Transcription repressor activity by regulation of chromatin-remodeling
> Exact synonyms:
> Gene-specific transcription repressor activity by regulation of chromatin-remodeling;
> Gene-specific RNA polymerase II transcription repressor activity by regulation of chromatin-> remodeling

Also covered by corepressor

**Comment by pgaudet** [comment]
> resulting in their degradation: p53 on gene, when phosphorylated by PIC it leaves promoter.
and 
> nuclear export: nucleoplasmic shuttling eg NFkappaB by IKKB, not part of TF ontology restructure. need GO term eg Db Transcription factor inhibitor/repressor activity include in defintion that this often occurs in the cytoplasm and may include HSPs egs would be steroid receptor/NkappaB binding proteins.

are related to sequestering, see #16157

Closing this.
