### ISSUE TITLE
xp for GO:1990755

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11879]
I've just added GO:1990755 (Label: mitotic spindle microtubule depolymerization) in TGFreeForm. I think it could have this logical definition:

  intersection_of: GO:0022411 ! cellular component disassembly
  intersection_of: results_in_disassembly_of GO:1990498 ! mitotic spindle microtubule

cheers
m

Reported by: mah11

Original Ticket: [geneontology/ontology-requests/11717](https://sourceforge.net/p/geneontology/ontology-requests/11717)

**Comment by ValWood** [comment]
Might already be done?

**Comment by mah11** [comment]
Term's been available for a while, but still doesn't have the xp.

**Comment by dosumis** [comment]
Fixed as requested.
