### ISSUE TITLE
NTR intracellular G-protein coupled receptor activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11883]
Hello, 

I came across some G proteins that are not on the plasma membrane, but rather in the nucleus (or even on the Golgi). See reviews: PMID:24568158 and  PMID:16902576. 

However the term 'GO:0004930 G-protein coupled receptor activity' has a parent 'cell surface-receptor activity', so I cannot use it. I am not sure how to deal with this; but it would be nice if the general 'G protein.coupled receptor activity' remained under 'cell surface-receptor activity', since that's the general case. 

Thanks, Pascale

Reported by: pgaudet

Original Ticket: [geneontology/ontology-requests/11721](https://sourceforge.net/p/geneontology/ontology-requests/11721)

**Comment by dosumis** [comment]
Function term no-longer has link to cell-surface receptor activity
Pathway term now includes gloss: The pathway can start from the plasma membrane, Golgi or nuclear membrane (PMID:24568158 and PMID:16902576).
