### ISSUE TITLE
NTR:mannose trimming and mannosidase terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11888]
There's 2 parts to this SF entry, which are related:

PART 1:

I’d like to RENAME the following term:

misfolded or incompletely synthesized glycoprotein catabolic process ; GO:0097466 
TO:
glycoprotein ERAD pathway ; GO:0097466 
narrow synonym: misfolded or incompletely synthesized glycoprotein catabolic process ; GO:0097466 

GO:0097466 was requested for annotation of PMID:16079177, and there are 2 annotations from PMID:16079177 to this term, including to the mannosidase enzyme that catalyses mannose trimming, thus targeting the ER glycoprotein for degradation.

Additional synonyms, and revised definition:
synonym: gpERAD (PMID:25092655)
synonym: ER-associated glycoprotein degradation [GO:bf]
synonym: glycoprotein ERAD [GOC:bf]
Revised definition: An ERAD pathway whereby endoplasmic reticulum (ER)-resident glycoproteins are targeted for degradation. Includes differential processing of its sugar chains, retrotranslocation to the cytosol and degradation by the ubiquitin-proteasome pathway.
is_a parent: ERAD pathway ; GO:0036503

----------------------------

PART 2:

I also need some new terms to annotate a group of papers characterising the mannosidase enzymes that catalyse mannose trimming (removing alpha 1,2-linked mannose residues from an attached oligosaccharide).

During gpERAD, there is a two-step mannose trimming process, with each step catalysed by different alpha1,2-mannosidases (GO:0004571/EC:3.2.1.113).

Man9(GlcNAc)2 —> Man8B(GlcNAc)2 —> Man alpha1,6E (mannose with an exposed alpha 1,6-mannose).

I want to distinguish between these reactions because there’s a lot of debate in the literature about which mannosidase(s) catalyse which step(s).

The current alpha-1,2 mannosidase term (GO:0004571) is:
mannosyl-oligosaccharide 1,2-alpha-mannosidase activity ; GO:0004571 (EC:3.2.1.113)
Catalysis of the hydrolysis of the terminal (1->2)-linked alpha-D-mannose residues in the oligo-mannose oligosaccharide Man(9)(GlcNAc)(2)

The definition of GO:0004571 is more specific than its name suggests. So I’d suggest renaming to match its definition and creating a new grouping term, and some sibling terms which specify the inputs and outputs of the reactions:

Suggested revision:

mannosyl-oligosaccharide 1,2-alpha-mannosidase activity ; GO:NEW
—[isa]mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, acting on Man9(GlcNAc)2 ; GO:0004571 (RENAMED)
——[isa]mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, Man9(GlcNAc)2 to Man8B(GlcNAc)2 (R06722) ; GO:NEW
——[isa]mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, Man9(GlcNAc)2 to Man5(GlcNAc)2 (R05982) ; GO:NEW
—[isa]mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, acting on Man8(GlcNAc)2 ; GO:NEW

I was debating whether to create BP or MF terms for these, because for M9->M8, only one mannose residue is being removed. But for M9->M5, 4 mannose residues are removed in succession and is likely to go through an M8 etc intermediate. I went for function:

mannosyl-oligosaccharide 1,2-alpha-mannosidase activity ; GO:NEW
Catalysis of the hydrolysis of the terminal (1->2)-linked alpha-D-mannose residues in an oligo-mannose oligosaccharide.
[PMID:25092655]
Note: this uses the old name of GO:0004571.

mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, Man9(GlcNAc)2 to Man8B(GlcNAc)2
Catalysis of the reaction: Man9(GlcNAc)2 + H2O = Man8(GlcNAc)2 + D-mannose. The reaction catalyses hydrolysis of the terminal (1>2)-linked alpha-D-mannose residue from the B-chain of oligo-mannose oligosaccharide Man9(GlcNAc)2.
broad synonym: Man9(GlcNAc)2 to Man8(GlcNAc)2 conversion [PMID: 22160784]
exact synonym: Man9(GlcNAc)2 to Man8B(GlcNAc)2 conversion [PMID: 22160784]
exact synonym: mannose trimming, M9 to M8B conversion [PMID:25092655]
Xref: KEGG:R06722

mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, acting on Man8(GlcNAc)2
Catalysis of the hydrolysis of the terminal (1>2)-linked alpha-D-mannose residue from a Man(8)GlcNAc(2) to form an oligosaccharide with an exposed alpha 1,6-mannose.

mannosyl-oligosaccharide 1,2-alpha-mannosidase activity, Man9(GlcNAc)2 to Man5(GlcNAc)2
Catalysis of the reaction: Man9(GlcNAc)2 + 4 H2O = Man8(GlcNAc)2 + 4 D-mannose. The reaction catalyses sequential hydrolysis of the terminal (1>2)-linked alpha-D-mannose residues from the oligo-mannose oligosaccharide Man9(GlcNAc)2.
Xref: KEGG:R05982 

----------------------------

PART 3

Corresponding new process terms:

protein deglycosylation ; GO:0006517
—[isa]protein demannosylation ; GO:NEW1
——[isa]protein 1,2-alpha-demannosylation ; GO:NEW2
———[isa]protein 1,2-alpha-demannosylation involved in ERAD ; GO:NEW2
—[isa]protein deglycosylation involved in glycoprotein catabolic process ; GO:0035977
——[isa]protein 1,2-alpha-demannosylation involved in ERAD ; GO:NEW2

I will capture the substrate specificity during ERAD using annotation extensions.

protein demannosylation ; GO:NEW1
The removal of one or more mannose residues from a mannosylated protein.
PMID:25092655

protein 1,2-alpha-demannosylation ; GO:NEW2
The removal of one or more alpha 1,2-linked mannose residues from a mannosylated protein.
broad synonym: mannose trimming [PMID:21062743]
PMID:21062743
PMID:25092655

protein 1,2-alpha-demannosylation involved in ERAD ; GO:NEW2
part_of: glycoprotein ERAD pathway ; GO:0097466 (RENAMED TERM ABOVE)
synonym: mannose trimming involved in ERAD [GOC:bf]
synonym: mannose trimming involved in ER-associated glycoprotein degradation [GOC:bf]
The removal of one or more alpha 1,2-linked mannose residues from a mannosylated protein that occurs as part of ER-associated glycoprotein degradation (ERAD). During ERAD, a two-step mannose trimming process occurs on the glycoprotein, with each step catalysed by an alpha 1,2-mannosidase.
HAS_PART: mannosyl-oligosaccharide 1,2-alpha-mannosidase activity ; GO:NEW
Comment: Consider also annotating to ‘mannosyl-oligosaccharide 1,2-alpha-mannosidase activity ; GO:NEW’ or one of its child terms.

----------------------------

Any comments before I do the edits?

Thanks!

Reported by: rebeccafoulger

Original Ticket: [geneontology/ontology-requests/11726](https://sourceforge.net/p/geneontology/ontology-requests/11726)

**Comment by rebeccafoulger** [comment]
Broadened the definition of ‘mannosyl-oligosaccharide 1,2-alpha-mannosidase activity ; GO:0004571’ so it’s not restricted to removing mannose residues from Man9GlcNAc2. There is a step-wise removal of mannose residues from Man9GlcNAc2, and in the old definition it was unclear whether the function terms covers just the first step (conversion to Man8GlcNAc2) or subsequent steps also (Reactome mappings suggest the latter).
Have changed the synonym scopes to match the broadened definition.
Added KEGG reactions: R05982, R06722 (currently also linked to GO:0036509)

Added comments to the related process terms to consider also annotating to GO:0004571.

Everything is done on this ticket now, so closing.
