### ISSUE TITLE
 refine def of  "enzyme activator activity"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11887]
Def needs sharpening to match or use parent "enzyme regulator activity"

enzyme regulator activity
Binds to and modulates the activity of an enzyme.

Enzyme activator activity
Increases the activity of an enzyme.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11725](https://sourceforge.net/p/geneontology/ontology-requests/11725)

**Comment by dosumis** [comment]
This ticket has been superceded:
