### ISSUE TITLE
confused regulation of "meiosis"  by transcription terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11886]
There is a long(ish) existing term

GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter
A regulation of transcription from RNA polymerase II promoter that results in regulation of meiosis. 

Which should be changed to use either
"regulation of meiotic cell cycle"
OR
"regulation of meiotic nuclear division"

Also
GO:1900475	positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter
GO:1900476	positive regulation of meiosis by positive regulation of transcription from RNA polymerase II promoter

Then there is also a parent

GO:0100023 regulation of meiotic nuclear division by transcription from RNA polymerase II promoter

which was added more recently (by the reasoner I think), probable because the children were being incorrectly interpreted as referring to "meiotic nuclear division", rather than cell cycle)

HOWEVER,

I think all of these should be
"regulation of meiotic cell cycle"

Is there any transcriptional regulator  which specifically regulates "meiotic division"
other than indirectly by operating the meiotic program (I don't know, but these transitions for mitosis are controlled post transcriptionally)

All of the experimental annotations are PomBase (5) or SGD (1)
We would need to reassess these to see if  they were really regulating "meiotic division".  From a quick scan it appears not (they affect all kinds of aspects of meiosis and sporulation, but it is not possible to say whether they are directly  responsible for the timing of any of these events).

I suggest that all of the existing terms are represented as
"regulation of meiotic cell cycle yada yada" rather than "meiotic nuclear division" and we request new terms for the "regulation of meiotic nuclear division via transcription" if  we have evidence that it occurs.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11724](https://sourceforge.net/p/geneontology/ontology-requests/11724)

**Comment by ValWood** [comment]
Found a duplicate. This one is well in hand by @tberardini  so closing
https://github.com/geneontology/go-ontology/issues/10594
