### ISSUE TITLE
tweak transmembrane transport def

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11891]
There is a little bit of info which is only recorded in the comment of
“transmembrane transport” should move into the definition
so instead of
The process in which a solute is transported from one side of a membrane to the other.
The process in which a solute is transported from one side of a membrane to the other across a lipid bilayer
(not that this would then explicitly exclude membrane extrusion or insertion as for this only one membrane is lipid leaflet

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11729](https://sourceforge.net/p/geneontology/ontology-requests/11729)

**Comment by dosumis** [comment]
@ValWood  Not really sure this is needed, surely the other examples you give are not solutes?

**Comment by ValWood** [comment]
OK, but which things are not solutes (.....this may have implications for the current children)

**Comment by dosumis** [comment]
Well presumably something inserted into a membrane is not soluble.  Do you have examples of the child terms you are concerned about?

**Comment by ValWood** [comment]
I guess I was thinking specifically about proteins. Does whether a protein is embedded in the membrane or transported through it depend solely on solubility? (I have no idea, but it would seem not, in the mitochondria proteins can be transported through one membrane and then embedded in another...)

**Comment by dosumis** [comment]
Added anyway.  May be redundant info, but no harm in that.
