### ISSUE TITLE
TPV: nucleotide-sugar metabolism

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11898]
nucleotide-sugar metabolism is defined
The cellular chemical reactions and pathways involving nucleotide-sugars, any nucleotide in which the distal phosphoric residue of a nucleoside 5'-diphosphate is in glycosidic linkage with a monosaccharide or monosaccharide derivative.

and positioned under nucleotide metabolism

Nucleotide metabolism is defined
The chemical reactions and pathways involving a nucleotide, a nucleoside that is esterified with (ortho)phosphate or an oligophosphate at any hydroxyl group on the glycose moiety; may be mono-, di- or triphosphate; this definition includes cyclic nucleotides (nucleoside cyclic phosphates).

However,nucleotides-sugar doesn't fit the def of nucleotide  (and isn't a nucleotide, its a nucleotide-sugar).

Nucleotide-sugar would probably work better biologically defined as the activated form of a monosaccharide

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11736](https://sourceforge.net/p/geneontology/ontology-requests/11736)

**Comment by ukemi** [comment]
Looks like this has been fixed at ChEBI. I deleted the part of relation in GO. Hopefully it won't come back.

-D
