### ISSUE TITLE
mp GO:0019430 removal of superoxide radicals

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11893]
could
GO:0019430 removal of superoxide radicals
be a descendant of
GO:0061691 detoxification of hydrogen peroxide
?

(so it gets captured by our cellular detoxification slim term)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11731](https://sourceforge.net/p/geneontology/ontology-requests/11731)

**Comment by dosumis** [comment]
Fixed - see #12124
