### ISSUE TITLE
MP protein kinase activator activity (F-P link)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11895]
MP protein kinase activator activity

should have an F-P links to

activation of protein kinase activity

(and all of the yucky gene product specific ones)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11733](https://sourceforge.net/p/geneontology/ontology-requests/11733)

**Comment by dosumis** [comment]
Suggested fix: obsolete all 'activation of X activity terms'.

For the MF terms, we already have a design pattern that works: doesn't distinguish degree of regulations, just specifies must be direct.

**Comment by dosumis** [comment]
This ticket has been superseded by #12995
