### ISSUE TITLE
suppress redundant F-P links?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11892]
I'm not sure of the correct tracker for this.
We try not to show inferred annotation when we have experimental data, but we pick up some inferences via F-P links.

For example, cut15
has
protein transporter activity by ISS to SGD:S000005133
this is generating a mapping to
protein transport ISO SGD:S000005133
via F-P link,
but we already have 3 more specific experimental annotations to
"protein import into nucleus" for this gene product.
Is it possible to suppress these inferences if we already have good data? they just add clutter....

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11730](https://sourceforge.net/p/geneontology/ontology-requests/11730)

**Comment by ValWood** [comment]
I think this is sorted. Will open a new ticket if not with more detail
