### ISSUE TITLE
ntr/tpv  tRNA-guanine transglycosylation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11905]
There is a similar issue to 
ontology-requests/11743/ for queuosine

I captured this as "GO:1990397 queuosine salvage" which is  how it is described in the paper. 
and although this seems to fit

GO:1990397 queuosine salvage
Any process which produces queuosine from derivatives of it, without de novo synthesis.

it isn't really salvage in the way that it is represented in the GO graph. Here, GO:1990397 queuosine salvage is a descendent of queuosine biosynthesis but the queuosine isn't 'salvaged' endogenously by fission yeast. it is acquired from a dietary source. So an annotation to "queuosine biosynthesis" is incorrect. 

I think to annotate this paper  I needed instead a process term
tRNA-guanine transglycosylation instead?
defined as
the  insertion of queuine into target tRNAs by the replacement of a genetically encoded guanine
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2802272/

The existing term arrangement around
queuosine salvage
and
queuosine biosynthesis looks dodgy (in particular the parentage to tRNA modification)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11744](https://sourceforge.net/p/geneontology/ontology-requests/11744)

**Comment by tberardini** [comment]
@hdrabkin, trying to get Harold into the loop

**Comment by tberardini** [comment]
@ValWood , I found this term:

queuine tRNA-ribosyltransferase activity
http://amigo.geneontology.org/amigo/term/GO:0008479

Does that help for your annotation?  We still need to do something about the queosine salvage term.

Also: GO:0008616 queuosine biosynthetic process should not be a descendent of tRNA modification unless all queuosine biosynthesis is part of tRNA modification

@hdrabkin, do you know if  all queosine biosynthesis is part of tRNA modification ?  If not, I will remove that parent and leave it straight under ribonucleoside biosynthetic process (and queosine metabolic process).

**Comment by hdrabkin** [comment]
I remember commenting on this before.

Queuine always ends up in tRNA, but the modification can occur either by re-use of queuine from diet/breakdown of tRNA in some organisms, or de nova synthesis in others.

hjd





________________________________

**Comment by ValWood** [comment]
Hi Tanya,

That is the function term we have.  I can't figure out the correct process for this. It isn't biosynthesis....

Val

**Comment by tberardini** [comment]
Hi Val,

Why not tRNA modification?   http://amigo.geneontology.org/amigo/term/GO:0006400   

Leaning towards obsoleting 'queuosine salvage' and creating the new replacement term 'tRNA-guanine transglycosylation' with direct parentage to 'tRNA modification'.  Or we could rename it since we've only got pombe annotations to it.

Based on @hdrabkin 's feedback, I will remove the 'tRNA modification' parent from 'queosine biosynthetic process' and leave it straight under ribonucleoside biosynthetic process (and queosine metabolic process).

**Comment by ValWood** [comment]
Yeah I was being picky...all our other tRNA modifiers have specific processes. 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006400#term=children

I'm not particularly attached to the modification processes if they are peformend by single activities though. Its only the inconsistency that bothers me :)

Ignoring my pickiness, the only real problem  is that
 GO:0008616 queuosine biosynthetic process
is a descendent of tNRA modification.......

**Comment by tberardini** [comment]
I've removed the link to 'tRNA modification' .  

@ValWood - shall we do anything about 'queuosine salvage' or leave it be?  If we should leave that alone, please close this issue.

**Comment by ValWood** [comment]
so you removed  queosine bio from under modification? so the salvage term will no longer be under modification.

If so, I think there is a separate issue open about the salvage terms, so  this one can be closed.

**Comment by tberardini** [comment]
Yes, I 'removed queosine bio from under modification.'

The issue on salvage and biosynthesis is this one #11890.
