### ISSUE TITLE
modify definition of GO:0009245 lipid A biosynthetic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11900]
Hi, the definition of "GO:0009245 lipid A biosynthetic process" states that lipid A has six fatty acyl chains linked to two glucosamine residues. While this is true of lipid A in E.coli it is not true in many other bacteria, which can have 4 or 5 acyl chains. Helicobacter pylori has 4 acyl chains, see PMID 22216004, in Bacteroides thetaiotaomicron it has 5 acyl chains, see PMID 20974832. As far as I can tell all lipid As do have 2 glucosamine residues. Lipid A is also subject to further modifications (phosphorylation, addition of ethanolamine etc, etc) which can be species specific. I suggest something like this for the definition:
"The chemical reactions and pathways resulting in the formation of lipid A, the glycolipid group of bacterial lipopolysaccharides, consisting of four to six fatty acyl chains linked to two glucosamine residues. Further modifications of the backbone are common."
Thanks, Andrea

Reported by: aauchincloss

Original Ticket: [geneontology/ontology-requests/11738](https://sourceforge.net/p/geneontology/ontology-requests/11738)

**Comment by dosumis** [comment]
Fixed as requested.  Added request for correction in ChEBI, but leaving link to more specific ChEBI term in place for now.  

ChEBI ticket here: https://github.com/ebi-chebi/ChEBI/issues/3246

@ValWood do you know who aauchincloss is on GitHub (If she's on).  If so, can you @ mention.  Cheers,
David

**Comment by ValWood** [comment]
I don't know who aauchincloss in real life :)

**Comment by mah11** [comment]
Andrea Auchincloss at SIB - http://www.sib.swiss/about-us/finding-people?cn=andrea%20auchincloss

I don't know whether she has a GitHub account.
