### ISSUE TITLE
NTR: Thymidylate synthase inhibitor binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11937]
Request on behalf of Hadil Alrohaif;

Can we have a new term "thymidylate synthase inhibitor binding" as a child term of drug binding (GO:0008144)?

Thymidylate synthase inhibitor is in ChEBI (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:63720), but we couldn't request this term via TermGenie as Heiko said TS inhibitors are roles rather than distinct chemicals.

Evidence is from Figure 4 in PMID:19116913.

Please add GOC references;
GOC:BHF
GOC:hal

Reported by: rachhuntley

Original Ticket: [geneontology/ontology-requests/11776](https://sourceforge.net/p/geneontology/ontology-requests/11776)

**Comment by pgaudet** [comment]
Hi @rachhuntley 

Do you still need that term? If you do - How about creating 'x compound binding' ? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
Hi Pascale,
I think we can forget about this one now.
Thanks,
Rachael.
