### ISSUE TITLE
new term/s request: anti-recombinase activity & child D loop dissociation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11946]
Hi,

I would like to request this term/s with the following suggestions or better advice please.

suggested new function term: anti-recombinase activity (child of part of GO:0006310 DNA recombination), and new function child term: D (displacement) loop dissociation activity

current recombinase activity GO:0000150 funciton term exists:  Catalysis of the identification and base-pairing of homologous sequences between single-stranded DNA and double-stranded DNA.

suggested definition anti-recombinase activity: Catalysis of the dismantling of recombination base-pairing of homologous sequences between single-stranded DNA and double-stranded DNA (preferred),

or

inhibition of the identification and base-pairing of homologous sequences between single-stranded DNA and double-stranded DNA.

As for related process: current GO:0045910 negative regulation of DNA recombination exists: Any process that stops, prevents, or reduces the frequency, rate or extent of DNA recombination, so maybe new term/s can be linked to this process? or is there need for new process (better?) e.g. DNA recombination dismantling: a process in which DNA recombination intermediates are dismantled/disocciated?

suggested definition for D loop dissociation activity: catalysis of the dismantling of D loops (displacment loops) formed at the point where linear telomeric DNA is remodeled into triple-stranded DNA, by the invasion of a 3' single-stranded overhang into the duplex region.

PMID:     10338204 (review)
PMID:     18957201

GOC: NC
GOC: BHF

Thanks

Nancy

Reported by: noonoo25

Original Ticket: [geneontology/ontology-requests/11785](https://sourceforge.net/p/geneontology/ontology-requests/11785)

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by tberardini** [comment]
Let's get this revived.  @monicacecilia, could you have a look please? I seem to recall that you were annotating genes in this area for PAINT earlier this year. Is that true? If so, input welcome!

**Comment by tberardini** [comment]
@monicacecilia !!!  If I don't hear from you soon, I'll try to tackle this on my own.

**Comment by tberardini** [comment]
Hi @NancyCampbell ,  Sorry for the horrific delay.  I've been excavating old GH tickets and ran across this one.  Way back when, you requested

1. anti-recombinase activity
2. D loop dissociation activity

I've taken a look at the ontology as it stands now, as well as the paper.  You probably want to annotate to the process terms unless the mechanism of action has been established after this paper was published.  

strand displacement (syn: D-loop dissociation)
http://amigo.geneontology.org/amigo/term/GO:0000732

and 

negative regulation of DNA recombination (as you mention above)

Would that suffice?  Perhaps additional papers on rtel1 have been published since 2008 that have clarified the function?

**Comment by NancyCampbell** [comment]
It is my turn to apologise, not sure how I missed this!! Thanks for reviving ticket!

I will use more granular term (as D-loops also exist in the mitochondria). **Though I am wondering if GO:0061820 telomeric D-loop disassembly should be child of strand displacement (syn: D-loop dissociation)**. 

GO:0061820 telomeric D-loop disassembly
A telomere loop disassembly process that results in the disassembly of telomeric D-loops. A telomeric D-loop is a three-stranded DNA displacement loop that forms at the site where the telomeric 3' single-stranded DNA overhang (formed of the repeat sequence TTAGGG in mammals) is tucked back inside the double-stranded component of telomeric DNA molecule, thus forming a t-loop or telomeric-loop and protecting the chromosome terminus.

Yes will use negative regulation of DNA recombination as suggested.

**Comment by tberardini** [comment]
Hi @NancyCampbell :  From reading both the definitions of 'strand dissociation' and 'telomeric D-loop disassembly' (see above)

**strand dissociation**
> The rejection of the broken 3' single-strand DNA molecule that formed heteroduplex DNA with its complement in an intact duplex DNA. The Watson-Crick base pairing in the original duplex is restored. The rejected 3' single-strand DNA molecule reanneals with its original complement to reform two intact duplex molecules

I don't think I should move 'telomeric D-loop disassembly' to be a child of this.

Thanks for your response.  I will now close (!) this issue.

**Comment by NancyCampbell** [comment]
I meant it to be child of both i.e. not to move it! is that possible?

**Comment by tberardini** [comment]
I think with the current definitions, 'telomeric D-loop assembly' should not have the additional parent of 'strand dissociation' and is correctly placed where it is.
