### ISSUE TITLE
review ontology relationships in transmembrane transport domain

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11959]
Hi

I have been reminded that transmembrane transport should only relate to the transport of molecules 'through' the membrane, and that transport into the cell via endocytosis should not be included as child terms.

I have gone back over my annotations and realised that:
GO:0035376 sterol import should NOT have the parent  GO:0035382 sterol transmembrane transport, instead it needs the is_a parent  GO:0015918 sterol transport

Note there are other molecule import examples in GO

I would appreciate this revision

Best

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/11798](https://sourceforge.net/p/geneontology/ontology-requests/11798)

**Comment by dosumis** [comment]
Fixed
