### ISSUE TITLE
NTR: locomotor gait pattern

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11966]
Hi, I would like to ask for a new term as below or better suggestion.

NTR:  locomotor gait pattern

Definition: The gait pattern of the locomotor activity of an organism.   Gait pattern is the pattern of movement of the limbs of animals during locomotion over a solid substrate. (as defined by Wikipedia) 
   
Parent term: is_a GO:0007626 locomotory behavior
   
PMID:22932389

Thanks,

Jinhui Zhang

Reported by: jinhuiz

Original Ticket: [geneontology/ontology-requests/11805](https://sourceforge.net/p/geneontology/ontology-requests/11805)

**Comment by tberardini** [comment]
Added:

+id: GO:0090659
+name: walking behavior
+namespace: biological_process
+def: "The behavior of an organism relating to the progression of that organism along the ground by the process of lifting and setting down each leg." [GOC:tb]
+synonym: "locomotor gait pattern" NARROW []
+is_a: GO:0007626 ! locomotory behavior
+created_by: tanyaberardini
+creation_date: 2015-08-27T16:34:28Z

and added additional parentage to this term for the existing adult and larval terms.
