### ISSUE TITLE
endosome parent of multivesicular body (rather than late endosome) 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11968]
Hello, 
In GO, multivesicular bodies (GO:0005771) are considered as late endosomes (hence prelysosomal). From what I can see in the literature, it seems that they can be indeed targeted to lysosomes (making the link to late endosomes sensible), but they can also fuse to the plasma membrane and release their internal vesicles (exosomes GO:0070062) in the extracellular milieu (see http://www.nature. com/subjects/multivesicular-bodies, based on many publications) (linking them to early endosome). My suggestion would be to link them to "endosome", not "late endosome". What do you think? As soon as I'll get your feedback, I will update the definition in the UniProtKB keyword list.

Many thanks in advance for your help.

Anne

-- 
**************************************************
Anne Estreicher, PhD
Swiss-Prot annotator
SIB Swiss Institute of Bioinformatics
CMU - 1, rue Michel-Servet
CH - 1211 Geneva 4
Switzerland
Tel: (+41 22) 379 49 30
Fax: (+41 22) 379 58 58
http://www.isb-sib.ch/
http://www.uniprot.org/
mailto:help@uniprot.org
**************************************************

Reported by: aestreich

Original Ticket: [geneontology/ontology-requests/11807](https://sourceforge.net/p/geneontology/ontology-requests/11807)

**Comment by paolaroncaglia** [comment]
@pauldenny
@RLovering

**Comment by ukemi** [comment]
Moved the term and tweaked the definition. I added PMID:16533950 as a new definition reference because it describes the process of them fusing to the plasma membrane.
