### ISSUE TITLE
MP regulation of cyclin-dependent protein serine/threonine pk activity involved in.....

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11975]
GO:0031657
Name	regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

is not a descendant of 

regulation of G1/S transition of mitotic cell cycle
only of

GO:0000082 G1/S transition of mitotic cell cycle

However, as the regulation of the transition is a switch caused by the phosphorylation status of the CDK. Therefore shouldn't anything which regulates the CDK therefore be involved in 
"regulation of G1/S transition of mitotic cell cycle"?

If this was not the case not I would need:

regulation of cyclin-dependent protein serine/threonine kinase activity involved in regulation G1/S transition of mitotic cell cycle

....it seems that 2 regulations  in the term name should not be necessary though?, if you are regulating a part, you must be regulating the whole, no?

It is possible I asked this before....

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11814](https://sourceforge.net/p/geneontology/ontology-requests/11814)

**Comment by ukemi** [comment]
Hi Val,

I did this one with the G2/S one. It should be fixed. Please let me know if it isn't.

-David
