### ISSUE TITLE
NTR: nicotinic acetylcholine receptor activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11978]
Hello

Do you think 'nicotinic acetylcholine receptor activity' is a legitimate term?

It's a subclass of ion-gated channel that activated_by acetylcholine OR nicotine.

Not sure if that can be expressed in OWL - otherwise could just be subclass of ion-gated channel.

Happy to add in TG if it sounds okay - let me know.

cheers

Jane

Reported by: jl242

Original Ticket: [geneontology/ontology-requests/11817](https://sourceforge.net/p/geneontology/ontology-requests/11817)

**Comment by dosumis** [comment]
Note, while the names are based on known agonists/antaognists, they actually correspons to ion channel. [nicotinic](https://en.wikipedia.org/wiki/Nicotinic_acetylcholine_receptor) vs GPRC, [muscarinic](https://en.wikipedia.org/wiki/Muscarinic_acetylcholine_receptor).  Defs should focus mostly on nature of receptors while keeping agonist/antagonist based names.

**Comment by bmeldal** [comment]
Hi Jane,

How does it differ from GO:0022848 acetylcholine-gated cation channel activity? Maybe it just needs a synonym or name change?

I'm currently making all the Ach receptor complexes and use the following synonyms for the complexes:

GO:0005892 acetylcholine-gated channel complex
EXACT synonym: nicotinic cholinergic receptor complex
EXACT synonym: nicotinic acetylcholine-gated receptor complex
EXACT synonym: nicotinic acetylcholine-gated receptor-channel complex
EXACT synonym: nicotinic acetylcholine-gated ion channel complex
EXACT synonym: nicotinic acetylcholine-gated cation channel complex

I also thought of changing the current CC term to "nicotinic acetylcholine receptor complex" to be in line with the literature. Should make that ticket for David OS, actually :)

Birgit

**Comment by vanaukenk** [comment]
Hi,
I was just reviewing some of our WB annotations for what are referred to in the literature as 'ionotropic acetylcholine receptors' and saw that, in addition to 'acetylcholine receptor activity', we have some annotated to:

GO:0022848
acetylcholine-gated cation channel activity
Definition
Enables the transmembrane transfer of a cation by a channel that opens when acetylcholine has been bound by the channel complex or one of its constituent parts. Source: GOC:mtg_transport, ISBN:0815340729

but there are also PAINT annotations to the same gene products to:

GO:0004889
acetylcholine-activated cation-selective channel activity
Definition
Enables the transmembrane transfer of a cation by a channel that opens upon binding acetylcholine. Source: PMID:2466967, GOC:mah

Aside from the 'selective' bit, I'm not sure, based on the definitions, what the differences are between GO:0022848 and GO:0004889.    GO:0004889 seems appropriate for what I am re-annotating, but is not suggested as another possibility when looking at acetylcholine receptor activity:

GO:0015464
acetylcholine receptor activity
Definition    
Combining with acetylcholine and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity. Source: GOC:jl, GOC:signaling 
Comment
For nicotinic acetylcholine receptors that act as ion channels, instead use 'acetylcholine-gated cation channel activity ; GO:0005892'.

--Kimberly

**Comment by bmeldal** [comment]
Hi Kimberly,

Good catch! I use GO:0022848, probably because I didn't find the other term. They look identical to me... 
They should have the same 3 is_a parents:
GO:0005261 cation channel activity
GO:0022824 transmitter-gated ion channel activity
GO:0005231 excitatory extracellular ligand-gated ion channel activity

GO:0015464 acetylcholine receptor activity:
I think this one refers to the muscarinic AchRs as they are GPCRs. In fact, GO:0016907 G-protein coupled acetylcholine receptor activity is its only is_a child. 
Def: Combining with acetylcholine and transmitting the signal across the membrane by activating an associated G-protein; promotes the exchange of GDP for GTP on the alpha subunit of a heterotrimeric G-protein complex.

I think these two could also be combined and the def made clearer.

@dosumis: these receptors are always named by their argonist in the literature, i.e. nicotinic or muscarinic AchRs. The nicotinic receptors are split into the neuronal and muscle-type receptors.

I made a bunch of notes here including some suggestions for changes to the GO structure but haven't put them in a ticket yet:
https://docs.google.com/document/d/1OmYM_1mkln_oSDCygVzSzoHqbXVrrcjthC9wQImG3-I/edit?usp=sharing
Link should be visible!

First bunch of complexes should go out with our next release next week (fingers crossed for no technical hitches...!). There are going to be nearly 70 nicotinic AchR complexes (I haven't started on the muscarinic ones yet!) by the time I'm done (4 orthologues per type: human, mouse, rat and chicken, the latter is the model organism for these receptors and has the most exp evidence [in vertebrates]).

Birgit

**Comment by vanaukenk** [comment]
Thanks, Birgit.

It looks like we also have PAINT annotations to GO:0015464 (acetylcholine receptor activity) for these ionotropic receptor subunits, so we may need to ask for some PAINT re-annotation if GO:0015464 is really intended for annotation of the muscarinic GPCRs.

I would be in favor of somewhere, either in the term name or as a synonym, referring to these ion channels as 'ionotropic acetylcholine receptors'.  We have the corresponding terms for glutamate receptors, and I think it helps clarify which term to select.  

As David suggests, keeping the agonist-containing names as synonyms for usability would be good.

In the meantime, I will work on cleaning up our WB manual annotations for the channel subunits.

**Comment by bmeldal** [comment]
Thanks, Kimberley.

I agreed, we should add the additional synonym 'ionotropic acetylcholine receptors'. I will add them to the complexes as well.

**Comment by dosumis** [comment]
Detailing fix in steps here:

1.  'acetylcholine receptor activity' is, and remains a general class for acetylcholine receptors

2. In line with all other ligand gated-channel activities, acetylcholine-gated cation channel activity is a subclass of the general receptor class (see  GABA receptor, glutamate receptor etc.

![image](https://cloud.githubusercontent.com/assets/112839/21052456/134571cc-be1d-11e6-8590-b475846178ff.png)

3. acetylchoine-gated channel activity now has 2 new synonyms:

has_exact_synonym "iontropic acetylcholine receptor activity"
has_exact_synonym "nicotinergic acetylcholine receptor activity"

4. 'G-protein coupled acetylcholine receptor activity' 
_
has_exact_synonym "metabotropic acetylcholine receptor activity"

**Comment by dosumis** [comment]
I agree that these two terms should be merged:

GO:0022848
acetylcholine-gated cation channel activity
Definition
Enables the transmembrane transfer of a cation by a channel that opens when acetylcholine has been bound by the channel complex or one of its constituent parts. Source: GOC:mtg_transport, ISBN:0815340729

GO:0004889
acetylcholine-activated cation-selective channel activity
Definition
Enables the transmembrane transfer of a cation by a channel that opens upon binding acetylcholine. Source: PMID:2466967, GOC:mah

**Comment by dosumis** [comment]
Merged term:  

![image](https://cloud.githubusercontent.com/assets/112839/21053542/c9107e76-be21-11e6-98a1-a93a3486f490.png)

**Comment by dosumis** [comment]
For future reference: 
I'm a bit worried that the 'excitatory' bit on the parent class is overloading a bit (may be some non vertebrate cases where it is not).  But leaving as-is for now.

**Comment by bmeldal** [comment]
> 'acetylcholine receptor activity' is, and remains a general class for acetylcholine receptors

Then you have to change the Comments on
ID 	GO:0015464
Name 	acetylcholine receptor activity
Ontology 	Molecular Function
Definition 	Combining with acetylcholine and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity.
Comment 	For nicotinic acetylcholine receptors that act as ion channels, instead use 'acetylcholine-gated cation channel activity ; GO:0005892'.

GO:0022848 acetylcholine-gated cation channel activity is already a is_a child but the ID in the comment is wrong:
it is actually the complex ID: GO:0005892 acetylcholine-gated channel complex

Birgit

**Comment by dosumis** [comment]
Deleted comment.  Should be obvious what to use from hierarchy & synonyms.

**Comment by bmeldal** [comment]
Great, thanks. The hierarchy must have been changed at some point after this ticket was created...

**Comment by dosumis** [comment]
> Great, thanks. The hierarchy must have been changed at some point after this ticket was created...

Yep.  Part of a general effort to make sure ligand gated-channels are treated as receptors
