### ISSUE TITLE
NTR- phosphatidylinositol-5-phosphate biosynthetic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11974]
This Review PMID_23916588
describes the process phosphatidylinositol-5-phosphate biosynthetic process
By analogy with GO: 0036092 phosphatidylinositol-3-phosphate biosynthetic process
and as a child of
GO:0006661 phosphatidylinositol biosynthetic process
We need a new term for this process
Would use to annotate Q9Y2I7 (PIFYVE) and Q13615 (MTMR3) based on PMID_25578879

Reported by: pauldenny

Original Ticket: [geneontology/ontology-requests/11813](https://sourceforge.net/p/geneontology/ontology-requests/11813)

**Comment by ukemi** [comment]
Hi Pail,

I have added the term via termgenie, but will keep this item open to have a closer look at the biochemistry. Sorry I didn't get around to this earlier, but I wanted to try to do the whole pathway and never got around to it. 

Here are the new terms:

[Term]
id: GO:1904562
name: phosphatidylinositol 5-phosphate metabolic process
namespace: biological_process
def: "The chemical reactions and pathways involving phosphatidylinositol 5-phosphate." [GO_REF:0000068, GOC:autophagy, GOC:dph, GOC:TermGenie, PMID:23916588]
synonym: "phosphatidylinositol 5-phosphate metabolism" EXACT [GOC:TermGenie]
is_a: GO:0046488 {is_inferred="true"} ! phosphatidylinositol metabolic process
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_participant CHEBI:37329 ! phosphatidylinositol 5-phosphate
relationship: has_participant CHEBI:37329 {is_inferred="true"} ! phosphatidylinositol 5-phosphate
created_by: dph
creation_date: 2015-08-18T16:21:44Z


[Term]
id: GO:1904563
name: phosphatidylinositol 5-phosphate biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of phosphatidylinositol 5-phosphate." [GO_REF:0000068, GOC:autophagy, GOC:dph, GOC:TermGenie, PMID:23916588]
synonym: "phosphatidylinositol 5-phosphate anabolism" EXACT [GOC:TermGenie]
synonym: "phosphatidylinositol 5-phosphate biosynthesis" EXACT [GOC:TermGenie]
synonym: "phosphatidylinositol 5-phosphate formation" EXACT [GOC:TermGenie]
synonym: "phosphatidylinositol 5-phosphate synthesis" EXACT [GOC:TermGenie]
is_a: GO:0006661 {is_inferred="true"} ! phosphatidylinositol biosynthetic process
is_a: GO:1904562 {is_inferred="true"} ! phosphatidylinositol 5-phosphate metabolic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_output CHEBI:37329 ! phosphatidylinositol 5-phosphate
relationship: has_output CHEBI:37329 {is_inferred="true"} ! phosphatidylinositol 5-phosphate
created_by: dph
creation_date: 2015-08-18T16:21:50Z

**Comment by Pauldenny** [comment]
No problem- thanks David!

Best regards,
Paul Denny
Sent from my mobile, please excuse spelling, brevity
Parkinson's UK Annotation Project Co-ordinator
Skype pauldennyuk | E: p.denny@ucl.ac.uk<mailto:p.denny@ucl.ac.uk> | W: http://www.ucl.ac.uk/functional-gene-annotation/neurological | M: +44-07922078038<tel:+44-07922078038> | L: +44-020-7679-6965<tel:+44-020-7679-6965>
Centre for Cardiovascular Genetics
University College London
Rayne Building
5 University Street<x-apple-data-detectors://5>
London WC1E 6JF<x-apple-data-detectors://5>

On 18 Aug 2015, at 17:27, ukemi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Pail,

I have added the term via termgenie, but will keep this item open to have a closer look at the biochemistry. Sorry I didn't get around to this earlier, but I wanted to try to do the whole pathway and never got around to it.

Here are the new terms:

[Term]
id: GO:1904562
name: phosphatidylinositol 5-phosphate metabolic process
namespace: biological_process
def: "The chemical reactions and pathways involving phosphatidylinositol 5-phosphate." [GO_REF:0000068, GOC:autophagy, GOC:dph, GOC:TermGenie, PMID:23916588]
synonym: "phosphatidylinositol 5-phosphate metabolism" EXACT [GOC:TermGenie]
is_a: GO:0046488 {is_inferred="true"} ! phosphatidylinositol metabolic process
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_participant CHEBI:37329 ! phosphatidylinositol 5-phosphate
relationship: has_participant CHEBI:37329 {is_inferred="true"} ! phosphatidylinositol 5-phosphate
created_by: dph
creation_date: 2015-08-18T16:21:44Z

[Term]
id: GO:1904563
name: phosphatidylinositol 5-phosphate biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of phosphatidylinositol 5-phosphate." [GO_REF:0000068, GOC:autophagy, GOC:dph, GOC:TermGenie, PMID:23916588]
synonym: "phosphatidylinositol 5-phosphate anabolism" EXACT [GOC:TermGenie]
synonym: "phosphatidylinositol 5-phosphate biosynthesis" EXACT [GOC:TermGenie]
synonym: "phosphatidylinositol 5-phosphate formation" EXACT [GOC:TermGenie]
synonym: "phosphatidylinositol 5-phosphate synthesis" EXACT [GOC:TermGenie]
is_a: GO:0006661 {is_inferred="true"} ! phosphatidylinositol biosynthetic process
is_a: GO:1904562 {is_inferred="true"} ! phosphatidylinositol 5-phosphate metabolic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_output CHEBI:37329 ! phosphatidylinositol 5-phosphate
relationship: has_output CHEBI:37329 {is_inferred="true"} ! phosphatidylinositol 5-phosphate
created_by: dph
creation_date: 2015-08-18T16:21:50Z

-

**Comment by ukemi** [comment]
Looks like I am not going to have time to really do this pathway justice with respect to molecular functions at this point, so I'm closing this.
