### ISSUE TITLE
difference between inflammasome and pyroptosome?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11970]
Hello,
I have to update several UniProtKB/Swiss-Prot entries linked to inflammation and I would like my UniProtKB changes to be consistent with GO annotation. Hence I have a question: what is the difference between inflammasome (GO:0061702; inflammasome complex) and pyroptosome (GO:0061703 pyroptosome complex). There is a difference in size for sure, but the impression I get from my readings is that once an inflammasome starts to form, it activates CASP1 and consequently IL1B (or IL18) and if it continues to grow, at some point it starts inducing pyroptosis, while keeping its CASP1-, IL1B-activating function. If this holds true, pyroptosome would be a subtype of inflammasome, not a separate entity. 

I couldn't find a lot of papers that would directly discuss this issue. In PubMed:17599095, Fernandes-Alnemri et al. (2007) states that inflammasomes and pyroptosomes are distinct entities, but in 2010, Schroder and Tschopp (PubMed:20303873) discuss the link between inflammasomes and pyroptosis. In PubMed:21687407, table 1 (2011), the only difference is the size (the extracellular location for the entire inflammasome looks a little strange, as far as I am aware CASP1 and IL1B can indeed be "secreted" together in intact cells, extracellular location for inflammasomes is reported after pyroptosis). 

Last year, there has been 2 really nice papers back-to-back in Cell (PubMed:24630722 and 24630723) that show the mechanism of inflammasome assembly. The final result in both publications is a huge speck adjacent to the nucleus which sizewise looks like a pyroptosome. 

In PubMed:25354325 (a review on the recent breakthrough in inflammasome assembly), one reads: "Upon stimulation by microbial and damage-associated signals, inflammasomes assemble to elicit the first line of host defense via the proteolytic maturation of cytokines interleukin-1b and interleukin-18, and by induction of pyroptotic cell death." (abstract). And in PubMed:24630722: "Caspase activation can lead to proteolytic maturation of cytokines interleukin (IL)-1b and IL-18 and elicit the inflammatory form of cell death pyroptosis, as ways to control exogenous and endogenous invasions." 

What do you think? Many thanks in advance for your help.

Anne Estreicher

Reported by: aestreich

Original Ticket: [geneontology/ontology-requests/11809](https://sourceforge.net/p/geneontology/ontology-requests/11809)

**Comment by mcourtot** [comment]
Hi Anne,

David and I talked about this during the GOC meeting; as you mention there seems to be a relationship between those 2 terms and they are not equivalent and shouldn't be merged. I'm not sure if the relation is subtype, and this requires more reading...

Cheers,
Melanie

**Comment by ukemi** [comment]
I'm closing this one now. I have looked and there isn't a common parent to link these to in the ontology.
-D
