### ISSUE TITLE
OTR: GO:0008282 ATP-sensitive potassium channel complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#11989]
The def needs broadening to allow for Kir6.1 and Kir6.2 subunits as well as SUR1, SUR2A and SUR2B subunits:

"The opening and closing of the channel is regulated by ATP: binding of ATP to the Kir6.x subunit inhibits channel activity, whereas binding of Mg2+-complexed ATP or ADP to the SURx subunit stimulates channel activity."

Also, the more commonly know name for this complex is "inward rectifying potassium channel". It should be at least a synonym.

Further synonyms to be added:
inward rectifying K+ channel
Kir6.x complex
Kir6.x-SURx complex
Kir6-SUR complex
Kir6.1-SUR complex
Kir6.2-SUR complex
KCNJ8-SUR complex
KCNJ11-SUR complex
Kir6.1-SURx complex
Kir6.2-SURx complex
KCNJ8-SURx complex
KCNJ11-SURx complex

As we are at it, it also has these relationships:
is_a GO:0034705 potassium channel complex (instead of GO:0034702 ion channel complex)
capable_of GO:0005267 potassium channel activity, or even GO:0022841 potassium ion leak channel activity (it can let some K+ through even if the MgADP doesn't bind as ATP is a weak inhibitor)
capable_of GO:0005524 ATP binding
capable_of GO:0043531 ADP binding
capable_of GO:1904517 MgATP(2-) binding (new in TG)
capable_of GO:NEW MgADP(2-) binding (to be created when MgADT2+ = CHEBI:87194 released)
capable_of GO:0030955 potassium ion binding
capable_of GO:0019808 polyamine binding
capable_of_part_of GO:0010107 potassium ion import
capable_of_part_of GO:1990573 potassium ion import across plasma membrane
[the latter two have no relationship in GO but maybe GO:1990573 should be child of GO:0010107?]

Thanks,
Birgit

**Comment by bmeldal** [comment]
I'm not sure the annotations 

GO:0005244 voltage-gated ion channel activity
GO:0005249 voltage-gated potassium channel activity
GO:0015272 ATP-activated inward rectifier potassium channel activity
 GO:0015467 G-protein activated inward rectifier potassium channel activity
and
GO:0008076 voltage-gated potassium channel complex 
and even
GO:0005242 inward rectifier potassium channel activity

are correct as:
A) ATP inhibits the channel, and
B) activation is either by mechanical means (in cardiac cells) or by changing the intracellular ATP or MgADP or extracellular glucose concentration (in pancreatic beta-cells) rather than voltage change (see def of GO:0005242 inward rectifier potassium channel activity, last annotation above). In fact, Kir6 channel activity results in voltage change and at least in pancreatic beta-cells this activates the Ca2+ channels which results in insulin release.

The names of the above terms are in parts misleading but the defs clearly refer to either ATP-dep or voltage-gated activation.

**Comment by dosumis** [comment]
Hi Birgit, can you share some refs?  Struggling to put all the pieces toghether here.

BTW - I think there are problems with the definition of inward rectifier channel activity - the def is more restricted than it should be - actually seems to refer to a subclass of inward rectifiers.  Hoping to discuss definitions of main axes of classification of general channel classification for ion channels at next synapse working group meeting.

**Comment by bmeldal** [comment]
Hi David,

Here are some (unstructured!, copy/paste) notes and a list of references:
https://docs.google.com/document/d/1ebFJLwv8yorBb1mjrBVhMcJgKK4xr-B7oxCY7dzNcQs/edit?usp=sharing

Fairly recent, comprehensive review: 20086079
Paper I curated for exp evidence: 25236767

And yes, if the def for inward rectifier potassium channel activity was broadened it could work. It's just its reliance on 'voltage-gated' that I don't agree with for Kir6.x channels.

Thanks,
Birgit

**Comment by bmeldal** [comment]
Hi David,

Looks like the def got updated (in the latest GO release report) but only adjusting the Kir subunit, not the SUR subunit. It should refer to both, SUR1 and SUR2 types (or SURx).

Thanks,
Birgit

**Comment by pgaudet** [comment]
Hi @bmeldal 

I made the following changed (lines starting with "-" are removed, lines starting with + are new): 

 id: GO:0008282
-name: ATP-sensitive potassium channel complex
+name: inward rectifying potassium channel
 namespace: cellular_component
 def: "A protein complex that comprises four pore-forming (Kir6.x) and four regulatory sulphonylurea receptor (SURx) subunits and forms a transmembrane channel through which ions may pass. The opening and closing of the channel is regulated by ATP: binding of ATP to the Kir6.x subunit inhibits channel activity, whereas binding of Mg2+-complexed ATP or ADP to the SURx subunit stimulates channel activity." [GOC:bhm, PMID:16308567, PMID:16956886]
-is_a: GO:0043234 ! protein complex
+synonym: "ATP-sensitive potassium channel complex" EXACT []
+synonym: "inward rectifying K+ channel" EXACT []
+synonym: "KCNJ11-SUR complex" RELATED []
+synonym: "KCNJ11-SURx complex" RELATED []
+synonym: "KCNJ8-SUR complex" RELATED []
+synonym: "KCNJ8-SURx complex" RELATED []
+synonym: "Kir6-SUR complex" RELATED []
+synonym: "Kir6.1-SUR complex" RELATED []
+synonym: "Kir6.1-SURx complex" RELATED []
+synonym: "Kir6.2-SUR complex" RELATED []
+synonym: "Kir6.2-SURx complex" RELATED []
+synonym: "Kir6.x complex" RELATED []
+synonym: "Kir6.x-SURx complex" RELATED []
+is_a: GO:0034705 ! potassium channel complex
 is_a: GO:0044459 ! plasma membrane part
 relationship: capable_of GO:0005267 ! potassium channel activity
+relationship: capable_of_part_of GO:1990573 ! potassium ion import across plasma membrane
 relationship: part_of GO:0005887 ! integral component of plasma membrane

Does this address your points? 

Also - if you think some annotations need review, please open a ticket in the annotation tracker. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Another thing: I didn't add capable of x binding; I don't know if we do that systematically, I could not find other examples.

**Comment by bmeldal** [comment]
Happy with the changes - Thanks @pgaudet - and copied the annotation question into the right tracker.

Binding x question - to be discussed in Complex WG next week. I will add this ticket to the project as a reference.

**Comment by pgaudet** [comment]
great, thanks !

**Comment by RLovering** [comment]
https://github.com/geneontology/go-annotation/issues/1701

**Comment by bmeldal** [comment]
We might come back to this when we get an answer to wether users use the binding to X relationships.
