### ISSUE TITLE
fix name GO:1904511

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#11984]
Hi,

I just added this in TG, and didn't spot the duplicated "microtubule" in the term name until too late (obviously, it should be "cytoplasmic microtubule plus-end"). Some of the synonyms should probably also be adjusted.

[Term]
id: GO:1904511
name: cytoplasmic microtubule microtubule plus-end
namespace: cellular_component
def: "Any microtubule plus-end that is part of a cytoplasmic microtubule." [GO_REF:0000064, GOC:TermGenie, PMID:15772152]
synonym: "growing microtubule plus end of cytoplasmic microtubule" EXACT [GOC:TermGenie]
synonym: "growing microtubule plus end of non-spindle-associated astral microtubule" NARROW [GOC:TermGenie]
synonym: "microtubule plus end of cytoplasmic microtubule" EXACT [GOC:TermGenie]
synonym: "microtubule plus end of non-spindle-associated astral microtubule" NARROW [GOC:TermGenie]
synonym: "microtubule plus-end of cytoplasmic microtubule" EXACT [GOC:TermGenie]
synonym: "microtubule plus-end of non-spindle-associated astral microtubule" NARROW [GOC:TermGenie]
is_a: GO:0035371 {is_inferred="true"} ! microtubule plus-end
is_a: GO:0044444 {is_inferred="true"} ! cytoplasmic part
intersection_of: GO:0035371 ! microtubule plus-end
intersection_of: part_of GO:0005881 ! cytoplasmic microtubule
relationship: part_of GO:0005881 {is_inferred="true"} ! cytoplasmic microtubule

Sorry for the hassle! Feeling sheepish ...

m

**Comment by mah11** [comment]
p.s. when it's corrected and live, I want to TG a protein localization term using it

**Comment by dosumis** [comment]
Fixed and committed.
