### ISSUE TITLE
MP GO:0009927 histidine phosphotransfer kinase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11983]
is missing
protein kinase activity parent

cheers

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11822](https://sourceforge.net/p/geneontology/ontology-requests/11822)

**Comment by ukemi** [comment]
Is this always a kinase activity or can it also dephosphorylate? The def implies that it just serves as an intermediate in the regulatory process.

**Comment by ValWood** [comment]
Ah maybe its OK then. I thought it was just a kinase.
