### ISSUE TITLE
Obsolete "ATPase activity uncoupled"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#11987]
I was wondering why we make  distinction between 
ATPase, coupled and 
ATPase uncoupled

mainly because:
1. ATPase, uncoupled  has NO children (should it? are there any)
2.  ATPase, uncoupled only has ONE experiemntal annotation (and I'm not sure how we would know that it was uncoupled?)

Suggest merging uncoupled and coupled?

**Comment by dosumis** [comment]
Distinction Inherited from EC.   Should probably get input from Peter D'Eustachio.  Doesn't yet seem to be on GitHub yet.

**Comment by deustp01** [comment]
I don't see how "ATPase, uncoupled" could ever be inferred computationally as that would require finding protein features consistent with ATPase activity AND protein features inconsistent with binding anything else. (Note the assumption here that transfer of the energy derived from ATP hydrolysis will require contact that is close and specific enough to qualify as binding.) For that matter, it's hard to see how to establish that an ATPase activity is uncoupled under physiological conditions, just as Val says, for the same reasons. The only reason I can think of to keep this term is to annotate papers that only demonstrate ATPase activity for a protein - the same argument that has been made for keeping X-binding terms to annotate enzymes: if catalysis has been shown then the binding annotation is redundant but there are many studies that assay only binding and one might want to capture that information.

I'm not so sure about ATPase, coupled either. I can't think of a case in mammals where ATP is hydrolyzed solely to generate heat directly, but there should be a lot where the energy-requiring activity that is coupled to the hydrolysis under physiological conditions is not clear.

Why not simple ATPase activity to annotate that bare fact, and terms like "ATP-coupled X transport" for the cases where coupling is well-established? Or if post-composition is preferable, then some sort of formula whereby juxtaposition of, say, x transport AND ATPase activity allows inference of the coupling?

**Comment by dosumis** [comment]
We have only [one annotation to uncoupled based on experimental evidence](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0042624&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIGC%2CISS%2CIDA%2CIEP%2CTAS%2CNAS%2CND%2CIC%2CRCA%2CISA%2CEXP%2CIBA%2CIBD%2CIKR%2CIRD%2CISO%2CISM&protein=&qualifier=&ref=&with=&tax=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal)

**Comment by ValWood** [comment]
yep, I looked at that and I don't see how you would know it was uncoupled...

**Comment by dosumis** [comment]
> I can't think of a case in mammals where ATP is hydrolyzed solely to generate heat directly,

http://www.ncbi.nlm.nih.gov/pubmed/12912988 
My reading of this is that some isoforms of SERCA hyrdrolyze ATP purely to generate heat as part of themo-regulation in warm blooded animals.   SERCA1 in brown adipose tissue is  capable of this activity.

**Comment by dosumis** [comment]
Added a comment: 

rdfs:comment "An example of this activity is found in brown adopise tissue, where an isoform of  sarco/endoplasmic reticulum Ca2+-ATPase (SERCA) is capable of ATPase activity not coupled to Ca2+ transport in a reaction that is more thermogenic than the coupled reaction (PMID:12912988)."
