### ISSUE TITLE
Migrate attachments (particularly images) over 

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#11985]
The script did not do this: https://github.com/cmungall/gosf2github/issues/7

Example of attachment:
https://sourceforge.net/p/geneontology/ontology-requests/11691/

crude estimate of number of attachments:

```
$ egrep  '"attachments": \[$' geneontology-backup-2015-07-24-173754/ontology-requests.json | wc
     518
```

By type:

```
1       rtf
2       gif
3       ontology
5       pptx
5       docx
8       gz
9       xlsx
11      obo
12      tiff
16      xls
18      jpg
22      pdf
23      zip
32      png
60      doc
112     txt
```

If implemented, this would place the attachment as the final comment in the ticket. It would not be as nice as seeing it in the correct place, but it's the best we can do without redoing entire thing

**Comment by cmungall** [comment]
Actually, harder than I thought, because numbering is not 1:1

**Comment by dosumis** [comment]
> If implemented, this would place the attachment as the final comment in the ticket. It would not be as nice as seeing it in the correct place, but it's the best we can do without redoing entire thing.

That would be fine.

**Comment by pgaudet** [comment]
Well, we survived without attachments for 3 years now. I think we're fine.
