### ISSUE TITLE
refinement of  septin ring structures

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11980]
GO:0032161 cleavage apparatus septin structure

has various descendents
	
 GO:0000144 cellular bud neck septin ring	
 GO:0032169 prospore septin ring	
 GO:0032174 cellular bud neck septin collar	
 GO:0032177 cellular bud neck split septin rings	
 GO:0036391 medial cortex septin ring

and one of our cummunity selected 

GO:0000144
cellular bud neck septin ring

which I would not have used. However, when I checked the def
A ring-shaped structure that forms at the site of cytokinesis; composed of members of the conserved family of filament forming proteins called septins as well as septin-associated proteins. In S. cerevisiae, this structure forms at the time of bud emergence and the septins show a high rate of exchange. 
PMID:16009555

he is completely correct as this is true.

I have used
 GO:0036391 medial cortex septin ring
but these two terms are both describing the same mitotic cytokinetic structure.

Should we merge them somehow? 
mitotic septin ring 
A ring-shaped structure that forms at the  cortex at the site  of mitotic cytokinesis; composed of members of the conserved family of filament forming proteins called septins as well as septin-associated proteins. 

If we still need the medial and bud neck terms they could go under this term...and the bud neck term should be redefined to record its differences related to its different position?

We should also correct 

GO:0036391 medial cortex septin ring
medial cortex septin ring
Definition	A double ring-shaped structure that forms at the medial cortex at the onset of cytokinesis; composed of members of the conserved family of filament forming proteins called septins as well as septin-associated proteins. 

to

medial cortex septin ring
Ontology	Cellular Component
Definition	A ring-shaped structure that forms at the medial cortex of a symetrically dividing cell at the onset of cytokinesis; composed of members of the conserved family of filament forming proteins called septins as well as septin-associated proteins. 

(starts as a single ring, but splits into 2)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11819](https://sourceforge.net/p/geneontology/ontology-requests/11819)

**Comment by ukemi** [comment]
Hi Val,

It seems to me like the definitions need to be tweaked. I am tempted to keep both terms as I suspect that they form differently and will be used as references for the process terms.

GO:0000144
cellular bud neck septin ring
A ring-shaped structure that forms at the site of cytokinesis in a budding cell; composed of members of the conserved family of filament forming proteins called septins as well as septin-associated proteins. In S. cerevisiae, this structure forms at the time of bud emergence and the septins show a high rate of exchange.
PMID:16009555

GO:0036391 medial cortex septin ring
medial cortex septin ring
Definition A double ring-shaped structure that forms at the medial cortex at the onset of cytokinesis in a symetrically dividing cell ; composed of members of the conserved family of filament forming proteins called septins as well as septin-associated proteins.

The other ones seem to necessarily and sufficiently defined, prospore, mating and hyphal.

-D

**Comment by ValWood** [comment]
> didn't get this bit
The other ones seem to necessarily and sufficiently defined, prospore, mating and hyphal.

can you skype now ? @mah11 is here too

**Comment by ukemi** [comment]
OK. Changed defs to make the terms more specific as we discussed on skype.

-D
