### ISSUE TITLE
ntr: regulation of protein localization to cell division site involved in cell separation after cytokinesis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11982]
ntr: regulation of protein localization to cell division site involved in cell separation after cytokinesis

Any regulation of protein localization to cell division site the site of cell division involved in cell separation after cytokinesis

PMID:25411334

The process of physically separating progeny cells after cytokinesis; this may involve enzymatic digestion of septum or cell wall components.

descendent of
GO:0000920
Name	cell separation after cytokinesis
GO:1901900
Name	regulation of protein localization to cell division site

(term genie not working for me, but might be network, if so can try later)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11821](https://sourceforge.net/p/geneontology/ontology-requests/11821)

**Comment by ukemi** [comment]
Hi Val,

If you need:
(regulation of protein localization to cell division site) involved in (cell separation after cytokinesis), then you should be able to do that with TG using the involved in template.
Be aware that this term will mean that the regulation of protein localization to the cell division site is part of the process of cell separation after cytokinesis. I'm not sure that is what you want. 

If you want a term describing a process that is regulating the process of (protein localization to cell division site involved in cell separation after cytokinesis) then you need:
regulation of (protein localization to cell division site involved in cell separation after cytokinesis)

-D

**Comment by ValWood** [comment]
I don't understand the difference between these 2 options biologically. Will need to discuss at some point...how would I distinguish...would need to know the beginning of "cell separation after cytokinesis" I guess   ?

**Comment by ukemi** [comment]
Spoke with Val she wants the latter of the two choices above.

**Comment by ukemi** [comment]
Do you still need this term?

**Comment by ValWood** [comment]
used it.... GO:1905391

**Comment by dianeoinglis** [comment]
"Protein localization to cell division site involved in cell separation after cytokinesis"

I see multiple issues with this term. First, the reference is PMID: 25411334 "The Rho-GEF Gef3 interacts with the septin complex and activates the GTPase Rho4 during fission yeast cytokinesis. 

1) My conclusion after examining the paper is "cell separation"is a process that is dependent on "protein localization to cell division site.

2) The term contains multiple redundant parts and is not well-constructed. By definition, the "cell division site" IS where "cytokinesis" occurs. Following cytokinesis, cell separation may occur (resulting in physically detached cells) or may not occur (resulting in individual cells that are attached). In the case where cells do separate, can "cell separation" occur at any other time than "after cytokinesis?" Further, the CC term that is incorporated, "cell division site" contains a note that specifies the site of _future_ cell division and not a cell division site that has already completed cytokinesis. I presume the use of this CC term carries all aspects of the definition. Is this presumption true?

3) Further, the logic is:
The process of "cell division" IS synonymous with the process of "cytokinesis."
The process of "cell separation"can only occur AFTER cytokinesis.
The process that this study focuses on is (protein localization to cell division site) that is involved_in (cell separation). Agreement? Disagreement?

Because "cell separation" is not mandatory, the parent term "protein localization to cell division site" covers both cases when cells separation occurs AND when cell separation does not occur following cytokinesis. I think that the most concise construction of the base term and child terms that cover both instances is:
regulation of [(cell separation) after (protein localization to cell division site)]:

A) "(protein localization to cell division site) resulting in (cell separation)" AND
B) "regulation of (protein localization to cell division site) resulting in (cell separation)"
OR possibly
C) (cell separation) after (protein localization to cell division site)
D) "regulation of (cell separation) after (protein localization to cell division site)

There is my four cents.

**Comment by ValWood** [comment]
Hi Diane, 

Just to let you know it is on my radar, but I didn't get to it this week. You are correct the terms are not very nicely constructed. I'm sure there was a reason for doing it like this. I will trace the history of the original terms, and then we will see what improvements can be made. 

Best

Val

**Comment by ValWood** [comment]
Sorry for the delay. Will address points one by one.
I agree the term name is very clunky (suggestions for revisions welcome), however I think the biology is largely correct.

First I probably didn’t use the best reference:

The first ref  says
“Consistently, Gef3 and Rho4 are in the same genetic pathways to regulate septum formation and/or cell separation. In gef3∆ cells, the localizations of two potential Rho4 effectors--glucanases Eng1 and Agn1--are abnormal, and active Rho4 level is reduced, indicating that Gef3 is involved in Rho4 activation in vivo.”
The Rho-GEF Gef3 interacts with the septin complex and activates the GTPase Rho4 during fission yeast cytokinesis.
Wang N, Wang M, Zhu YH, Grosel TW, Sun D, Kudryashov DS, Wu JQ.
Mol Biol Cell. 2015 Jan 15;26(2):238-55. doi: 10.1091/mbc.E14-07-1196.
PMID: 25411334


This later ref is probably better:
Rho4 interaction with exocyst and septins regulates cell separation in fission yeast.
Pérez P, Portales E, Santos B.
Microbiology. 2015 May;161(Pt 5):948-59. doi: 10.1099/mic.0.000062.
PMID: 25724972
Rho GTPases are small proteins present in all eukaryotic cells, from yeast to mammals, with a function in actin organization and morphogenetic processes. Schizosaccharomyces pombe Rho4 is not essential but it displays a role during cell separation at high temperature. In fact, Rho4 is involved in the secretion of the hydrolytic enzymes that are required for cell septum degradation during this process. In rho4Δ cells, vesicles accumulate in the septum area and the glucanases Eng1 and Agn1 are not secreted to the culture medium. The localization of Eng1 and Agn1 depends on the exocyst and the septins. The exocyst is a conserved multiprotein complex important for the targeting and fusion of Golgi-derived vesicles with the plasma membrane. Septins are a family of GTP-binding proteins conserved in eukaryotes that function during cytokinesis. Here we show that Rho4 is required for the proper localization of the exocyst and septins at high temperature. Moreover, pull-down experiments demonstrate that Rho4 can interact with exocyst subunits, such as Sec8 and Exo70, and septin proteins, such as Spn3. We observe that Sec8 preferentially binds to activated GTP-Rho4, suggesting that Sec8 could be an effector of this GTPase. We propose that the interaction of Rho4 with the exocyst and septins confers a precise regulation for the secretion of glucanases at the appropriate place and time during the cell cycle.

> 1. My conclusion after examining the paper is "cell separation"is a process that is dependent on "protein localization to cell division site.

This is true.
However, this dependency is real “regulation”. The GTPase  mechanistically “controls”  when the process of cell separation in a normal cell.
This means that whatever the GTPase does is truly  “regulating “ cell separation, by  regulating localisation.

So we have used the term
GO:1905391 - regulation of protein localization to cell division site involved in cell separation after cytokinesis
which is  what gef3/rho4 are doing.

Note, we have not used the term
“protein localization to cell division site involved in cell separation after cytokinesis”
and I agree that this should probably not exist, only the regulation term is required. …..

Although perhaps we could just say
“regulation of cell separation after cytokinesis”, but this would lose some information about how the regulation occurs., and the way the GTPase affect the downstream targets.
So this depends on whether  how important we think  the fact it is to capture that  the  GTPAse is regulating the “localising”.

**Comment by ValWood** [comment]
> 2) The term contains multiple redundant parts and is not well-constructed. By definition, the "cell division site" IS where "cytokinesis" occurs. Following cytokinesis, cell separation may occur (resulting in physically detached cells) or may not occur (resulting in individual cells that are attached). In the case where cells do separate, can "cell separation" occur at any other time than "after cytokinesis?" Further, the CC term that is incorporated, "cell division site" contains a note that specifies the site of future cell division and not a cell division site that has already completed cytokinesis. I presume the use of this CC term carries all aspects of the definition. Is this presumption true?

Yes
in (most?) metazoan cells (or presumably all species where no cell wall is present?),  cell separation occurs coincident  with cytokinesis not  “after cytokinesis”

- Although we could probably exclude  “ to cell division site” with no loss of information, but I don't see any particular issue with including it at this point.

**Comment by ValWood** [comment]
> 3) Further, the logic is:
> The process of "cell division" IS synonymous with the process of "cytokinesis."
> The process of "cell separation"can only occur AFTER cytokinesis.
> The process that this study focuses on is (protein localization to cell division site) that is involved_in (cell separation). Agreement? Disagreement?
>
> Because "cell separation" is not mandatory, the parent term "protein localization to cell division site" covers both cases when cells separation occurs AND when cell separation does not occur following cytokinesis. I think that the most concise construction of the base term and child terms that cover both instances is:
> regulation of [(cell separation) after (protein localization to cell division site)]:
>
> A) "(protein localization to cell division site) resulting in (cell separation)" AND
> B) "regulation of (protein localization to cell division site) resulting in (cell separation)"
> OR possibly
> C) (cell separation) after (protein localization to cell division site)
> D) "regulation of (cell separation) after (protein localization to cell division site)
>
> There is my four cents.


I don't fully understand this part fully, but we can come back to the bits I don't understand. 

For now, I can  comment on the statements
1. cytokinesis and cell division are not synonymous.
Cytokinesis is cytoplasmic division. Cell division is much broader and includes nuclear division ( mitosis or meiosis)
2. Not always, see above
3.  Almost, but it is regulation. I think  some of the confusion might be the instantiation of the non-regulation terms for a process which is only regulatory.... I agree this can be confusing. I think we had an example recently where we removed some non-regulation parents @ukemi  do you remember?

**Comment by ValWood** [comment]
Or @ukemi any thoughts otherwise? This is really 
"regulation of protein localization involved in regulation of cell separation"....
