### ISSUE TITLE
NTR: toxin-antitoxin activity and complex terms

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#11986]
from PMID:19150849:

"Bacteria that are resistant or tolerant to antibiotics are an increasing threat to human health. Indeed, ∼60% of infections in the developed world are caused by biofilms, which exhibit multidrug tolerance (MDT) (1, 2). MDT is caused by the presence of dormant bacterial cells called persisters, which account for only 10–6 to 10–4 cells in a growing population, making MDT difficult to study (3–5). Persisters are not mutants but phenotypic variants of wild-type cells that evade killing by somehow adopting a transient dormant state (6, 7). Dormancy provides protection because bactericidal antibiotics kill by corrupting their active targets into producing toxic byproducts. These protected persisters can then switch back to the growth phase after the removal of antibiotics, allowing the bacterial population to survive. The first high-persistence allele, hipA7 (high-persistence A), was identified in Escherichia coli and increased the frequency of persistence by 10,000 fold (8–10). E. coli hipA encodes a 440-residue protein, HipA, which is cotranscribed with a smaller upstream gene, hipB. HipB is an 88-residue protein that represses the hipBA operon by binding cooperatively to four operators upstream of hipBA (11, 12). HipB forms a complex with HipA, and because wild-type HipA cannot be expressed in the absence of HipB because of its deleterious effects on cell growth, hipBA has been categorized as a toxin/antitoxin (TA) module in which HipA, the toxin, is neutralized by the antitoxin, HipB (13, 14). Toxin proteins from chromosomally encoded TA modules, of which more than 10 have been identified in E. coli, appear to promote cell dormancy and may play roles in the development of persistence under certain conditions (5, 7). Chromosomal TA modules can be grouped into three main superfamilies based on whether the toxin has a ribonuclease (RNase)/gyrase–like fold, RNase barnase–like structure, or a PilT N-terminus (PIN) domain (14). The corresponding antitoxins contain DNA binding domains and C termini that are largely unfolded until bound by the toxin (14). HipA and HipB show no homology to any member of these TA superfamilies. Moreover, HipA is one of the few validated biofilm tolerance factors. Indeed, it has been demonstrated that overexpression of the HipA protein leads to MDT in E. coli (2). However, the mechanism of HipA-mediated MDT is unknown."

What activity does this complex have? It's certainly a transcriptional repressor but it's more than that as it induces a whole-organism dormancy state rather than simply silencing one gene.

Would GO:0097436 entry into dormancy or GO:0097437 maintenance of dormancy be the correct BP?

I need an activity term, if possible, and then the corresponding complex term.

Thanks,
Birgit

**Comment by bmeldal** [comment]
Ok, this might be the other way round to how I first read it: HipA on its own activates dormancy so the HipBA complex causes exit from dormancy (GO:0097438).

**Comment by bmeldal** [comment]
Maybe it has no strict activity? The complex is ready for release as soon as we have answered this.

**Comment by keseler** [comment]
I would call "no strict activity" for the complex itself.  I think the transcription repressor activity is largely the property of HipB, while the function of the HipBA complex is essentially to keep HipA inactive.  Though I just noticed a new paper, in Nature no less (PMID 26222023), that may shed more light; haven't read it yet.

Cheers,
Ingrid

**Comment by bmeldal** [comment]
I would like to release this complex with our next release.
Shall I create a generic toxin-antitoxin complex term for that?

Birgit

**Comment by dosumis** [comment]
Sorry for the delay.  High on my list this week. - David

**Comment by dosumis** [comment]
revisit once  #12766 has been adressed

**Comment by bmeldal** [comment]
#12766 has been closed. Can we finish this one then as well?

**Comment by pgaudet** [comment]
Hi @bmeldal 

What's left to do ? there is a complex 'toxin-antitoxin complex' GO:0110001
Is that what you wanted ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
I don't know if @dosumis wanted to add anything as it was 'high on his list' 2 years ago. We appear to have created the term in the meantime and it's also linked to MF terms in the ontology so I guess it's actually done...

**Comment by bmeldal** [comment]
Closing this as I don't need anything else.
