### ISSUE TITLE
which function term to use to represent a motor activity acting as a transporter for specific cargoI

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#11991]
I would like to annotate a MF term on pkl1 a
ATP-dependent microtubule motor activity, plus-end-directed
when it is acting as a microtubule based transporter, and to capture the cargo

Which term should I use?
If I use only
ATP-dependent microtubule motor activity, minus-end-directed

It is not capturing the transport function, however not all ATP-dependent microtubule motors are acting as transporters (some are microtubule sliding etc)

I need a  child term

which is a descendent of
GO:0008565 protein transporter activity
ATP-dependent microtubule motor activity, minus-end-directed

proposed def
Catalysis of movement along a microtubule, coupled to the hydrolysis of ATP.
to enables the directed movement of proteins  toward the microtubule minus end.

ATP-dependent minus-end-directed protein transporting microtubule motor activity
(it seems a bit of a mouthful but I can't think of an easy way to shorten it, and I want a MF term so that I can add the cargo Msd1 and Wdr8)

Note that the pkl1 kinesin is also responsible for the transport of Msd1 and Wdr8 into the nucleus, but here  kinesis isn't really the transporter (the unknown karyopherin to which pkl1 is attached is the transporter activity for this part. Msd1 and Wdr8 are passengers).

If this one sounds OK I can do it in TGFF

**Comment by ValWood** [comment]
![transport_term](https://cloud.githubusercontent.com/assets/7359272/8966754/0154e89c-362b-11e5-87b8-64bfd1d578d0.jpg)

**Comment by dosumis** [comment]
Perhaps more reasonable as an MF involved in BP term.  I'm worried that (most) people won't expect transporter activity to refer to movement along a microtubule by a motor.

How about:

ATP-dependent, minus-end-directed microtubule motor activity involved in protein transport
(rearranged a bit from the standard TG rolled version for clarity).

You could roll this using the standard TG template.

**Comment by ValWood** [comment]
OK will do, sounds sensible in this case.
Val

**Comment by dosumis** [comment]
Great.

**Comment by dosumis** [comment]
Noticed a couple of isses:
1. This might be a better combined term:

ATP-dependent, minus-end-directed microtubule motor activity involved microtubule-based transport

(although I could make it more specific by making a term for 'microtubule-based protein transport', which seems reasonable to add)

2. The genus of this term is motor activity not the transport, so I'm not sure that, strictly, you should extend with the cargo.  Doing so would make the implied new term both is_a transport and part_of some transport.  This could easily be done properly in LEGO, but in the absence of that, it might be better to make separate annotations:

* ATP-dependent, minus-end-directed microtubule motor activity involved microtubule-based transport 
* microtubule-based transport transports_or_maintains_localization_of Msd1

**Comment by ValWood** [comment]
I see what you mean. I  will add the cargo to  "microtubule-based transport"

**Comment by ValWood** [comment]
A question, how is it different from ATPase transmembrane transporters? They have 2 coupled activities ATPase and transporter, and we would capture the  cargo (e.g pheromone)  in the extension?
see
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015440#term=ancchart

**Comment by ValWood** [comment]
Re:
DOS: although I could make it more specific by making a term for 'microtubule-based protein transport', which seems reasonable to add

Yes that would be better.

**Comment by dosumis** [comment]
id: GO_0098840
label "protein transport along microtubule"@en
definition "The directed movement of a protein along a microtubule, mediated by motor proteins."
has_exact_synonym "microtubule-based protein transport"
has_obo_namespace "biological_process"
EquivalentTo: 'microtubule-based transport' that 'transports or maintains localization of' some protein

**Comment by dosumis** [comment]
Hi Val,  This TG request looks related:

Term]
id: GO:1904532
name: ATP-dependent microtubule motor activity, minus-end-directed involved in microtubule-based movement
namespace: molecular_function
def: "Any ATP-dependent microtubule motor activity, minus-end-directed that is involved in microtubule-based movement." [GO_REF:0000061, GOC:TermGenie, PMID:25987607]
is_a: GO:0008569 {is_inferred="true"} ! ATP-dependent microtubule motor activity, minus-end-directed
intersection_of: GO:0008569 ! ATP-dependent microtubule motor activity, minus-end-directed
intersection_of: part_of GO:0007018 ! microtubule-based movement
relationship: part_of GO:0007018 {is_inferred="true"} ! microtubule-based movement
created_by: vw
creation_date: 2015-07-31T06:45:48Z

Do you still need it?

Cheers,
David

**Comment by ValWood** [comment]
@dosumis Do you still need it?

Nope, I'll use the suggested F-P link
