### ISSUE TITLE
missing parent GO:0044695

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#11997]
Should GO:0044695 ! Dsc E3 ubiquitin ligase complex have a path to GO:0000151 ! ubiquitin ligase complex?

**Comment by paolaroncaglia** [comment]
Hi Midori,

Done, thanks. 

I think that @ukemi was going to work on ubiquitin-related complexes, so I'll leave this open for him so he knows. But, David, I assume you may close this ticket.

Thanks,

Paola
