### ISSUE TITLE
MP GO:0004810	tRNA adenylyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#11996]
GO:0004810  tRNA adenylyltransferase activity
and possibly other siblings

should be housed under the new term:
id: GO:1990817
name: RNA adenylyltransferase activity

**Comment by paolaroncaglia** [comment]
Hi Val,

I was going to add the missing parent when I noticed this definition comment: 
“This term represents a deleted EC activity and is scheduled for obsoletion.”

The EC is 2.7.7.25, moved to ‘CCA tRNA nucleotidyltransferase’ (http://enzyme.expasy.org/EC/2.7.7.72)

I couldn’t find any mention of GO:0004810 in obsoletion emails or in the go mailing list archive. A search for ‘scheduled for obsoletion’ among existing terms retrieves 13, all enzyme activities. Would you or @mah11 or maybe @rebeccafoulger have any memory of such a plan please, so I may follow up?

Thanks,

Paola

**Comment by mah11** [comment]
Sorry, I'm pretty sure the "scheduled for obsoletion" flag post-dates my GO stint (and I did fairly little work on the EC-xref'd catalytic activity terms when I was there).

**Comment by paolaroncaglia** [comment]
Thanks @mah11 !

**Comment by ValWood** [comment]
I have no memory either...but it sounds as though a merge with "CCA tRNA nucleotidyltransferase" might be more appropriate (and this term should be a descendent of  RNA adenylyltransferase activity?
Val

(note, if my response times on tickets are slow I am away for most of the time right up to the GO meeting, but I will check e-mail occasionally Val

**Comment by ValWood** [comment]
OK there are 4 EXP annotations to 
GO:0004810 tRNA adenylyltransferase activity
it seems that they should all be to
CCA tRNA nucleotidyltransferase
so  first revise to match this change and then add the correct parent.

Thanks,

Val

**Comment by hdrabkin** [comment]
There was a related item that I can'f find; I remember that in some organisms the addition of the CC can be a different enzyme from the addition of the final A. 
Will continue searching

**Comment by hdrabkin** [comment]
found it
ne might want to look at:PMID:18523015
Evolution of tRNA nucleotidyltransferases: a small deletion generated CC-adding enzymes.
" In some organisms, CCA synthesis is accomplished by the collaboration of evolutionary closely related enzymes with partial activities (CC and A addition). These enzymes carry all known motifs of the catalytic core found in CCA-adding enzymes. Therefore, it is a mystery why these polymerases are restricted in their activity and do not synthesize a complete CCA terminus. "

In some organisms ONE enzyme can add the whole CCA; In some bacteria, however, it appears TWO enzymes, one to add CC, a separate one to add the final A.
Also note that in eukaryotes, CCA is not encoded and always has to be added after removal of 3' trailer, but in bacteria, CCA is encoded; 3' end maturation stops at the CCA.
However, bacteria still do have CCA adding enzymes to maintain the CCA

Original comment by: hdrabkin

**Comment by paolaroncaglia** [comment]
Hi @ValWood  and @hdrabkin ,

This is getting a bit confused. Could you please make a summary of suggested changes for ‘tRNA adenylyltransferase activity’ and ‘tRNA 3'-terminal CCA addition’? That is, please provide suggested defs etc. so this really becomes a quick fix ;-)

Thanks.

**Comment by ValWood** [comment]
I just checked the exisiting EXP annotions to GO:0004810 tRNA adenylyltransferase activity are all describing CCA enzyme, so I think this change holds for the existing term

term should be called
CCA tRNA nucleotidyltransferase
and then add the correct parent (whatever that may be)

GO:0009022 tRNA nucleotidyltransferase activity?

**Comment by hdrabkin** [comment]
There should be two tRNA 3' nucleotidyltransferases.
One that can add CCA as well as the A; 
  Note that THIS enyzme adds a C, then another C, then an A. 
Another that just adds the CC.
  THIS enzyme adds a C, then a C.

**Comment by paolaroncaglia** [comment]
@hdrabkin , I’ll assign this ticket to you if you don’t mind. Thanks in advance!
Please note that there is an existing term, GO:0001680 tRNA 3'-terminal CCA addition, with (broad) synonym tRNA-nucleotidyltransferase activity and def “Post-transcriptional addition of the terminal 3' CCA sequence to a tRNA which does not encode this sequence within the primary transcript. CCA addition proceeds by the sequential addition of CTP, CTP, and then ATP to the 3' end of the tRNA, yielding a diphosphate with each nucleotide addition.” which seems to correspond exactly to Harold’s suggested first activity.

**Comment by hdrabkin** [comment]
GO:0004810 appears to just denote the addition of A. 
It is using an ec number, EC 2.7.7.25, that appears to have been removed from EC on 2010
The current ec is EC 2.7.7.72; but again is capable fo just adding the A, then this EC is not correct for it.

Then there is a child GO:0052929, which is the enzyme that just adds A to a tRNA that has the CC.This should not be a child of the above. 
Then there should be a third one capable of adding C, C, and A sequentially. THIS is the term that corresponds  to the process term GO:0001680 . 
Accepted name: CCA tRNA nucleotidyltransferase
Reaction: (1) a tRNA precursor + 2 CTP + ATP = a tRNA with a 3' CCA end + 3 diphosphate (overall EC 2.7.7.72
(1a) a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate
(1b) a tRNA with a 3' cytidine + CTP = a tRNA with a 3' CC end + diphosphate
(1c) a tRNA with a 3' CC end + ATP = a tRNA with a 3' CCA end + diphosphate 

The point is that if in fact all annotations are to the + 2C + A, then the easiest thing to do is to change the def to reflect this, and use the correct dbxref/xref. 
THEN create a new activity for the enzyme that can just add an A for that bacteria where the addition of CCA is a two enzyme process. 

The GO:0001680 having part GO:0052929 might be putting an unneeded relationship.
Otherwise,

**Comment by ValWood** [comment]
Hi HArold,

Isn't the correct way to do this t have to terms.

One for adding a "C"
One for adding an "A"
If you are annotating the enzyme that has both activities you use both MF terms.

I think we should keep  GO:0001680 tRNA 3'-terminal CCA addition as the process term, as this seems to be correct, based on what you have said. However, it has a lot of narrow synonyms which are confusing as they are likely to be exact synonyms of real MF terms. It would also be useful to add a comment describing the 2 mechanisms, and how to annotate the activities.

This might be what you are suggesting, but I'm not sure...

Val

**Comment by hdrabkin** [comment]
yes, I just thought myself into a corner and have modified my blathering to the discussion.

**Comment by ValWood** [comment]
Harold,
what do you suggest we do to close this one?

**Comment by ValWood** [comment]
ACTION

add 
GO:1990817    RNA adenylyltransferase activity
as a parent of 
GO:0004810 tRNA adenylyltransferase activity

Question, shouldn't logical definitions add this parent? @cmungall 


This solves my original request.
I think we can live with the rest for now.

**Comment by hdrabkin** [comment]
Ok, this is done and I removed the (now) redundant parent (Adenyytrnasferase activity).
