### ISSUE TITLE
Edit definition of GO:0003896, DNA primase activity

### ISSUE THREAD

**Issue by mariacostanzo** [geneontology/go-ontology#11994]
The current definition of GO:0003896 is:
Catalysis of the synthesis of a short RNA primer on a DNA template, providing a free 3'-OH that can be extended by DNA-directed DNA polymerases. Catalyzed by a DNA-directed RNA polymerase that forms a complex with alpha DNA polymerase.

Could we please remove the 2nd sentence, with its gene product-specific information? PMID: 26184436 shows that mitochondrial RNA polymerase has DNA primase activity, and it doesn't "form a complex with alpha DNA polymerase".

Thanks,
Maria

**Comment by paolaroncaglia** [comment]
Hi Maria,

Done, thanks,

Paola
