### ISSUE TITLE
Add  'do not annotate' flag to ALL phase terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#11998]
I am writing a short manuscript describing the cell cycle changes. Whilst reviewing the changes I noticed that so phase terms are missing the "DO NOT annotate" comment.

Includes

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0098762 meiotic cell cycle phase
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0098764 meiosis I cell cycle phase
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0098766 meiosis I M phase

**Comment by ValWood** [comment]
I don't appear to be able to edit labels, please add cell cycle/PomBase

**Comment by ValWood** [comment]
NOTE: There should be no annotations to phase terms, although currently there are some...
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0022403#term=annotation
(this might be a consequence of incorrectly  inherited annotations from part_of links, so they might dissappear...)

**Comment by paolaroncaglia** [comment]
Hi Val,

Yes. To make sure we add flags consistently and nicely, please confirm:

- All terms below GO:0022403 ’cell cycle phase’ (including ‘cell cycle phase’) should be in the subset ‘Terms not to be used for direct annotation’.

- All terms below GO:0022403 ’cell cycle phase’ (including ‘cell cycle phase’) should have a definition comment to the same extent.

- Some of the terms above already have such a comment, e.g. ‘anaphase’:
“Note that this term should not be used for direct annotation. If you are trying to make an annotation to x phase, it is likely that the correct annotation is 'regulation of x/y phase transition' or to a process which occurs during the reported phase (i.e mitotic DNA replication for mitotic S-phase). To capture the phase when a specific location or process is observed, the phase term can be used in an annotation extension (PMID:24885854) applied to a cellular component term (with the relation exists_during) or a biological process term (with the relation happens_during).”
I’d edit it slightly to:
“This term should not be used for direct annotation. If you are trying to make an annotation to x phase, it is likely that the correct annotation should be to 'regulation of x/y phase transition' or to a process which occurs during the reported phase (e.g. mitotic DNA replication for mitotic S-phase). To capture the phase when a specific location or process is observed, the phase term can be used in an annotation extension (PMID:24885854) applied to a cellular component term (with the relation exists_during) or a biological process term (with the relation happens_during).”
Agreed?

Thanks!

Paola

**Comment by paolaroncaglia** [comment]
As for your comment

"NOTE: There should be no annotations to phase terms, although currently there are some...
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0022403#term=annotation
(this might be a consequence of incorrectly inherited annotations from part_of links, so they might dissappear...)"

I see that you were discussing part_of with David OS in a recent ticket
https://github.com/geneontology/go-ontology/issues/11992
So I'd check with him if this is related 
@dosumis 
Thanks!

Paola

**Comment by dosumis** [comment]
I've fixed the one spurious link that was causing these annotations to show up.  Change should be apparent on QuickGO by end of this week.

**Comment by paolaroncaglia** [comment]
Brilliant, cheers!

**Comment by dosumis** [comment]
I've also been adding the go_check_do_not_annotate flag in line with #11992.

**Comment by dosumis** [comment]
Maybe close this ticket as duplicate?

**Comment by paolaroncaglia** [comment]
Sure! Please double-check the second sentence in the current comment, I think it might benefit from the two tiny changes I suggested above. Closing now.

**Comment by ValWood** [comment]
All sounds good to me, sorry for the duplication. I couldn't remember exactly what I put in the previous ticket.

val
