### ISSUE TITLE
 request taxon constraint for lung alveolus development

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#11993]
Request GO:0048286 lung alveolus development include constraint never_in_taxon 8782 Aves
references:
Maina JN. The Lung-Air Sac System of Birds Berlin: Springer, 2005
and
PMID:15016903
Thank you
GOC:mr

**Comment by dosumis** [comment]
@cmungall  - better added in Uberon?  What is the status of plans to use Uberon taxon constraints for checking GO?  Are these checks live yet?

**Comment by cmungall** [comment]
The main holdup is that we don't want to eat our own tail by bringing in 
uberon+ which may bring in an older GO. Should be fixed by:
https://github.com/ontodev/robot/issues/38

**Comment by dosumis** [comment]
#12223

**Comment by dosumis** [comment]
Please request addition to Uberon.  Constraint will then be imported into GO.
