### ISSUE TITLE
NTR: children of cell pole

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12007]
GO:0060187 ! cell pole

In rod shaped bacteria there are experiments that distinguish between the old and new cell poles after cell division.

**Comment by paolaroncaglia** [comment]
Hi Jim,

Could you please suggest term names and definitions for those two terms, and provide reference(s)?

Thanks,

Paola

**Comment by jimhu-tamu** [comment]
parent: GO:0060187 ! cell pole 

new terms:
GO:xxx ! old cell pole 
definition: the cell pole distal from the most recent cell division
GO:xxx ! new cell pole
definition: the cell pole proximal to the most recent cell division

references
http://www.ncbi.nlm.nih.gov/pubmed/8226658 
http://www.ncbi.nlm.nih.gov/pubmed/10231492

**Comment by paolaroncaglia** [comment]
Hi Jim,

Added:

[Term]
id: GO:1990901
name: old cell pole
namespace: cellular_component
def: "The cell pole distal from the most recent cell division. In rod-shaped bacteria, some experiments distinguish between the old and new cell poles after cell division." [GOC:jh2, PMID:10231492, PMID:8226658]
is_a: GO:0060187 ! cell pole
relationship: only_in_taxon NCBITaxon:2 ! Bacteria <prokaryote>

[Term]
id: GO:1990902
name: new cell pole
namespace: cellular_component
def: "The cell pole proximal to the most recent cell division. In rod-shaped bacteria, some experiments distinguish between the old and new cell poles after cell division." [GOC:jh2, PMID:10231492, PMID:8226658]
is_a: GO:0060187 ! cell pole
relationship: only_in_taxon NCBITaxon:2 ! Bacteria <prokaryote>

Thanks,
Paola

**Comment by ValWood** [comment]
We  have used these for the same concept  in fission yeast...
GO:0035840 old growing cell tip
GO:0035841 new growing cell tip

Our terms may be a little more specific because they refer  growing and non-growing ends, and NETO
but some of this maybe could be made more general. Either way they should probably be related somehow?. Are cell  pole and cell tip the same thing?

**Comment by jimhu-tamu** [comment]
@ValWood , I didn't use growing vs nongrowing ends because I think the actual growth is distributed across the length of the cell (at least in E. coli). It's not like there is a growing and nongrowing end, as I understand it. 

@paolaroncaglia. I'm not sure, but should the stuff about rod shaped bacteria be in the definition vs a comment?

There was an earlier item about poles vs tips that was closed last week

https://github.com/geneontology/go-ontology/issues/12162

**Comment by ValWood** [comment]
It still seems that we are trying to capture the same type of asymmetric cellular location to the old or new cell tip regardless of the part of the cell the the growth occurs.  It seems that a generic term could be useful here?  Or maybe we have too much detail about the growth mechanism in the terms describing the localization (this should probably only be in relevant process terms). This asymmetric localization is a very active area of research in fission yeast. Even though the gene products are likely to be different, there may be some convergent evolution and commonalities in the mechanisms.

For instance based on the def "GO:1990901 The cell pole distal from the most recent cell division" and the difference between a tip and a pole in previous ticket
This arrangement is logically true:
GO:1990901 old cell pole 
-- GO:0035840 old growing cell tip 

(but is prevented by the current taxon restriction on GO:1990901)

**Comment by paolaroncaglia** [comment]
Hi @jimhu-tamu and @ValWood,

Having re-read this thread and the related ticket https://github.com/geneontology/go-ontology/issues/12162, I think that it’s safer not to place GO:0035840 old growing cell tip under (is_a) GO:1990901 old cell pole (see Jim’s and David’s discussion in the related ticket). This may be revisited if and when evidences emerge about commonalities across bacteria and yeast re. asymmetric localization, but right now, it might be a bit of a stretch to try and generalise such specific terms across all taxa.

@jimhu-tamu, I removed the ‘gloss’ from the defs of old/new cell poles altogether, as it doesn’t really say much (the PMIDs associated with the terms already capture that info). Closing now, thanks.

**Comment by ValWood** [comment]
@mah11  can you take a look. You have probably thought about this more for FYPO...

**Comment by mah11** [comment]
nope, I have nothing to add.

**Comment by ValWood** [comment]
OK, I'm missing something. I don't understand after re-reading the defs, and the threads, why cell tip should not be part_of cell pole? - and any other logical relations this incurs.
(even if cell pole is applicable to multiple cell shapes)

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
I'll ask @ukemi to comment here please. Thanks and a nice weekend to all.
