### ISSUE TITLE
Incorrect inter-ontology link

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12003]
GO:0008253 5'-nucleotidase activity should not be linked to 
GO:0006470	protein dephosphorylation
It could be linked directly to dephosphorylation (GO:0016311)

Thanks, Pascale

**Comment by cmungall** [comment]
https://github.com/geneontology/go-ontology/issues/12005

Thanks

**Comment by paolaroncaglia** [comment]
Committed the following edits:
phosphatase activity part_of dephosphorylation
phosphoprotein phosphatase activity part_of protein dephosphorylation

Last thing I could do is add the reciprocal link
protein dephosphorylation has_part phosphoprotein phosphatase activity
