### ISSUE TITLE
NTR photosynthetic intracellular membrane

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12006]
Photosynthetic bacteria have different types of photosynthetic intracellular membranes derived from invagination of the plasma membrane

definition: need to consult with experts on this... will add comment when I get a def
Child of GO:0043231 ! intracellular membrane-bounded organelle

Synonym: ICM
Children:
vesicular photosynthetic intracellular membrane
tubular photosynthetic intracellular membrane
lamellar photosynthetic intracellular membrane

In addition to component terms, we will need process terms for development of the ICMs and regulation of the development of the ICMs

See: http://www.ncbi.nlm.nih.gov/pubmed/23615195

**Comment by paolaroncaglia** [comment]
Hi Jim,

Thank you. I will then wait for you to suggest definitions for your 4 new terms. 
Note that you'd then be able to create the remaining terms yourself by using TermGenie; sound like the 'cellular component assembly' and the 'regulation of BP' would do for you.

Best,

Paola

**Comment by paolaroncaglia** [comment]
Hi @jimhu-tamu ,
Are these terms still needed? If yes, could you please provide suggestions for definitions?
Many thanks.

**Comment by jimhu-tamu** [comment]
Hi Paola, 

I put this in based on a talk I heard at a meeting ... but where I can't find who the speaker was in my records. I think they're needed eventually, but I failed at tracking down an appropriate expert. So I would close this and we can do a new item if we actually need to annotate to them.

**Comment by paolaroncaglia** [comment]
Thanks @jimhu-tamu . Closing now.
