### ISSUE TITLE
NTR for "excitable cell processes"

### ISSUE THREAD

**Issue by vhinard** [geneontology/go-ontology#12004]
We'd like the following terms to annotate voltage-gated sodium channels:

neuronal action potential firing pattern
skeletal fiber action potential firing pattern
neuronal excitability
skeletal fiber excitability
cardiac cell excitability

neuronal action potential firing pattern
Definition: The process in which a neuron responds to multiple incoming signals by developing a train of action potentials.
Synonym: neuronal spikes train
Synonym: firing rate
Synonym: neural coding
Parent: 
neuronal action potential firing pattern 
-> child of GO:0019228 neuronal action potential
References: 
https://en.wikipedia.org/wiki/Neural_coding
PMID 19593378

skeletal fiber action potential firing pattern
Definition: The process in which a skeletal fiber responds to motor signals by developing a train of action potentials.
Synonym: burst of action potentials
Synonym: spikes train
Parent: 
skeletal fiber action potential firing pattern 
-> child of GO:0001508 action potential
References: 
PMID 24305449

neuronal excitability
Definition: Capacity of a neuron or a neuronal network to elicit action potentials able to support neuronal communication.
Parent: 
neuronal excitability 
-> child of cell-cell communication, perhaps with a new grouping term if appropriate.
References: 
PMID 17515599

skeletal fiber excitability
Definition: Capacity of a skeletal fiber or a skeletal muscle to respond to motor signals leading to skeletal muscle contraction.
Synonym: muscle excitability
Synonym: sarcolemma excitability
Parent: 
skeletal fiber excitability 
-> hard to say that it is a child of cell-cell communication, please advice.
References: 
http://www.hopperinstitute.com/cap_muscular.html
PMID 18059624

cardiac cell excitability
Definition: Capacity of a cardiac cell to respond to stimuli leading to heart function.
Synonym: cardiac excitability
Parent: 
cardiac cell excitability 
-> please advice.
References: 
PMID 25862830

Thanks,
Valérie H.

**Comment by paolaroncaglia** [comment]
Hi David @dosumis ,

Could you please look into Valerie Hinard's request (CALIPHO - SIB) as it's related to action potential terms and potentially to the synapse project. Let me know if you'd like me to do any edits.

Thanks,

Paola

**Comment by dosumis** [comment]
Hi Valerie,

Excitability sounds like a quality to me, making it out of scope for GO which only has processes (molecular level (MF) and above (BP)) and cellular components.   However, we can add some classes referring to the action of these sodium channels during action potentials.   These would follow the pattern MF involved in BP, e.g. voltage gated sodium channel activity involved in action potential.  Would these work for you?

I think we can probably support the firing pattern terms, as the definitions appear to refer to processes.  But the names need some work.  The synonyms look promising.   'neuronal spike chain' is nice and descriptive.  With the current definition, we would probably need something in the name about response, aren't some neurons are consitutively spiking?

Cheers,
Davod

**Comment by vhinard** [comment]
Hi David, 

thank you for your answer.

I completely agree with your comment. Excitability sounds more like a quality than a process, like synaptic plasticity. I realized that the solution for synaptic plasticity was to create the term "GO:0048167 regulation of synaptic plasticity". Could we do something the same? "Regulation of neuronal excitability"? With the definition "A process that modulates neuronal excitability, the ability of a neuron or a neuronal network to elicit action potentials able to support neuronal communication." This concept of excitability described in the literature is not otherwise described in GO as far as I can tell.

About firing pattern, "neuronal spike train" or "skeletal fiber spike train" fits, also as long as the synonyms are there, so I let you decide which is best.

Then, to answer your question: yes, some neurons can fire spontaneously. However, is this within the scope of GO ? It seems comparable to the intrinsic activity of ATPases, which as far as I know is not captured in GO. If you think it's useful to capture spontaneous firing, we can create the appropriate terms.

Best regards,
Valérie

**Comment by vhinard** [comment]
Hello David,

I was wondering if you have had a chance to look at my comments.
Do you have any suggestions?

Cheers,
Val

**Comment by paolaroncaglia** [comment]
Hi Valerie,
I'm afraid David is on leave this week. Thank you for your patience!
Paola

**Comment by vhinard** [comment]
Dear David, 
Did you have any time to think about our issue?
Tell me if I can do anything more.
Thanks,
Valérie

**Comment by dosumis** [comment]
How's this?

label "spike-train"
definition "A series of sequential, propagated action potentials occurring in a single cell."  [ISBN:978-0071390118]
synonym: burst of action potentials
SubClassOf 'regulation of membrane potential'
'has part' some 'action potential'

I think the firing pattern is a quality of the spike train.  The pattern can be regulated (sculpted),  e.g. a consitutively spiking neuron can have its spike chain sculpted by an inhibitory input:

![image](https://cloud.githubusercontent.com/assets/112839/10906292/33870c30-8218-11e5-9cf9-12263d61ad69.png)

(Source: ISBN:978-0071390118)

Wondering whether regualtion terms for this would be a bit high level for annotation.

----------------------

label: regulation of action potential firing threshold
definition: Any process that regulates the membrane potential at which firing of an action potential is triggered.
SubClassOf: 
 - regulation of action potential (?)
 - regulation of biological quality

@vhinard  - Any ideas on how we might define 'regulation of excitability' more broadly?  Can you list other types of 'regulation of excitability' besides regulatin of firing threshold?

**Comment by vhinard** [comment]
"spike train" with definition looks good.

"Wondering whether regulation terms for this would be a bit high level for annotation."

It seems that the "regulation of spike train" (if we create it ) would be redundant with "regulation of action potential".
From GO: 0098900 "regulation of action potential"
Definition 	"Any process that modulates the frequency, rate or extent of action potential creation, propagation or termination. This typically occurs via modulation of the activity or expression of voltage-gated ion channels."

**Comment by vhinard** [comment]
Hi David, 

*"@vhinard - Any ideas on how we might define 'regulation of excitability' more broadly? Can you list other types of 'regulation of excitability' besides regulation of firing threshold?"*

As another type of "regulation of excitability", there is the process that regulates the frequency of action potentials. So it could be an additional term: 

label: **regulation of action potential firing rate**
definition: Any process that regulates the frequency of action potentials.

We can say that the neuronal excitability is the ability of a neuron to elicit an action potential (=firing threshold) and to modulate the number of action potentials (=firing rate) due to the activity or expression of voltage-gated ion channels in response to a stimulus. This is referred as the “intrinsic excitability of a neuron” in the "nonsynaptic plasticity". (https://en.wikipedia.org/wiki/Nonsynaptic_plasticity)

However, neuronal excitability is often used in literature to describe neuronal network excitability. The "neuronal network excitability" is the ability of the neuronal network to trigger an action potential or spike trains across the network of neurons by synaptic transmission.

A specific term can be created for the regulation of this quality. (?)

**How’s this?**
Label: **regulation of synaptic strength**
Definition: Any process that modulates the strength or weight of a synapse. This typically occurs via modulation of the activity or expression of synaptic receptors.

Then, those three concepts could be **SubClassOf: “regulation of transmission of nerve impulse”** instead of "regulation of action potential" or "regulation of biological quality" ?

--------------------------------------------------------
By the way,  I wonder why “synaptic transmission” is not a subclass of “transmission of nerve impulse” while it is mentioned in the definition of “transmission of nerve impulse”?

GO:0019226 transmission of nerve impulse
Def: The neurological system process in which a signal is transmitted through the nervous system by synaptic transmission and the sequential electrochemical polarization and depolarization that travels across the membrane of a nerve cell (neuron) in response to stimulation.

This could help to link these new concepts to it.

But this is maybe for another ticket!

**Comment by vhinard** [comment]
Hello David, 

I would like first to thank you for all the work you have done on this issue.
However, I thought that the following NTRs would be added to GO but there is nothing for the moment.
Is the issue still open for discussion?
Can I do anything to help?

All the Best,
Valérie
@pgaudet


label: **"spike-train"**
definition "A series of sequential, propagated action potentials occurring in a single cell." [ISBN:978-0071390118]
synonym: burst of action potentials
SubClassOf: 'regulation of membrane potential'
'has part' some 'action potential'

label: **"regulation of action potential firing threshold"**
definition: "Any process that regulates the membrane potential at which firing of an action potential is triggered."
SubClassOf: 'regulation of membrane potential'

Then, I suggested those ones in respect to your comments.

label: **"regulation of action potential firing rate"**
definition: Any process that regulates the frequency of action potentials.
SubClassOf: 'regulation of membrane potential'

Label: **"regulation of synaptic strength"**
Definition: "Any process that modulates the strength or weight of a synapse. This typically occurs via modulation of the activity or expression of synaptic receptors."
SubClassOf: 'regulation of transmission of nerve impulse' ?

**Comment by dosumis** [comment]
@vhinard - I'm really sorry, I thought I'd added these. It looks like some edits I did in a branch went astray. I'll add them tomorrow.  Should be visible in QuickGO by the weekend.

**Comment by dosumis** [comment]
Added:

[Term]
id: GO:0099603
name: spike train
namespace: biological_process
def: "A series of sequential, propagated action potentials occurring in a single cell." [ISBN:978-0071390118]
synonym: "burst of action potentials" EXACT []
is_a: GO:0042391 ! regulation of membrane potential
relationship: has_part GO:0001508 ! action potential

[Term]
id: GO:0099605
name: regulation of action potential firing rate
namespace: biological_process
def: "Any process that regulates the frequency of action potentials in a spike train." [ISBN:978-0071390118]
is_a: GO:0098900 ! regulation of action potential

[Term]
id: GO:0099610
name: action potential initiation
namespace: biological_process
def: "The initiating cycle of an action potential. In vertebrate neurons this typically occurs at an axon hillock. Not all initiated axon potentials propagate." [ISBN:978-0071390118, PMID:19439602]
synonym: "action potential firing" EXACT []
synonym: "action potential triggering" EXACT []
is_a: GO:0001508 ! action potential

[Term]
id: GO:0099611
name: regulation of action potential firing threshold
namespace: biological_process
def: "Any process that regulates the potential at which an axon potential is triggered." [ISBN:978-0071390118]
is_a: GO:0098900 ! regulation of action potential

[Term]
id: GO:0099608
name: regulation of neuronal firing pattern
namespace: biological_process
def: "Any process that regulates the temporal pattern of a sequence of action potentials in a neuron." [ISBN:978-0071390118]
synonym: "spike train sculpting" EXACT []
is_a: GO:0098900 ! regulation of action potential
relationship: regulates GO:0099603 ! spike train

This one is harder:  'regulation of synaptic strength'

Need definition of synaptic strength first I think.  Right now I think it is redundant with 'modulation of synaptic transmission' - which we currently use for processes that can regulate future transmission events.

**Comment by vhinard** [comment]
Dear David, 

Thank you for all.
For the last one, 'regulation of synaptic strength', it sounds definitely redundant with 'modulation of synaptic transmission'. Let's forget it.
For me, everything is perfect like that.

Cheers, 
Val

**Comment by dosumis** [comment]
Note transferred from  #12299 - suggests something is still missing here:

"Do you suggest this term "short-term synaptic potentiation" in regard to my request of "neuronal excitability" that became "regulation of synaptic strength" as a substitute?

If this is not the case, please, tell me how I can help you, and forget the rest of the message.

But, if this is the case, I realize that the suggestions are going in a different direction of what I wanted to capture. My apologies for giving a bad suggestion with "synaptic strength".

I only wanted to capture the concept of "neuronal excitability" due to changes in intrinsic neuronal factors such as voltage-gated sodium or potassium channels. What they also called "intrinsic plasticity" or "non-synaptic plasticity".

A reference of this notion can be found in the introduction chapter of this recent paper: PMID 25697160.
"... less attention has been directed towards 'intrinsic' membrane properties: non-synaptic factors, which directly affect the probability that a neuron will fire an action potential in response to excitatory synaptic inputs. Upon the generation of the action potential at the axon initial segment, the signal continues to be strongly modulated by these intrinsic factors until it reaches the axon terminals, where it triggers the release of neurotransmitters..."

What do you think? Are we talking about the same concept?"
