### ISSUE TITLE
Typo in def of GO:0016236 macroautophagy

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12009]
Def of GO:0016236 macroautophagy currently reads
"...Macroautophagy involves the formation of double-membrane-bounded autophagosomes which enclose the cytoplasmic constituent targeted for degradation in a membrane-bounded structure, which then fuse with the lysosome (or vacuole) releasing *a single-membrane-bounded autophagic bodies which are* then degraded within the lysosome (or vacuole). ..."
should be either "releasing single-membrane-bounded autophagic bodies" or "releasing a single-membrane-bounded autophagic body which is then degraded"
Happy to do the edit but wanted to double check with the autophagy group first. Assigning to David for now. Thanks,
Paola

**Comment by ukemi** [comment]
I think it should be this:

"...Macroautophagy involves the formation of double-membrane-bounded autophagosomes that enclose the cytoplasmic constituent targeted for degradation in a membrane-bounded structure. Autophagosomes then fuse with a lysosome (or vacuole) releasing single-membrane-bounded autophagic bodies that are then degraded within the lysosome (or vacuole). ..."
-D

**Comment by paolaroncaglia** [comment]
@pauldenny
@RLovering

**Comment by ukemi** [comment]
Changed definition as above.
