### ISSUE TITLE
reorg of lysine/peptidyl-lysine acetyltransferase terms; NTR?

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12019]
I got a bit confused trying to use the GO:0052858 and GO:0090595 terms.  As far as I can tell, there are two issues: whether one substrate is lysine vs. peptidyl-lysine, and whether the other substrate is acetyl phosphate vs. acetyl-CoA.

GO:0090595 is currently defined as using lysine rather than peptidyl-lysine; part of the definition is the MetaCyc reaction LYSACET-RXN, which is involved in lysine degradation.  However, in GO, this term has a bunch of histone acetyltransferase activity children, where peptidyl-lysine is modified.  This relationship seems wrong.

On the other hand, the GO:0052858 term is defined as having peptidyl-lysine as one substrate, but acetyl-phosphate as the other.  As far as I can tell from reading around the E. coli literature a bit, the peptidyl-lysine modification with acetyl phosphate occurs spontaneously and doesn't require an enzyme (though I may be wrong, now or in the future).  

However, there is a peptidyl-lysine acetyltransferase enzyme (e.g. PMID 26251518 in E. coli, 12493915 in Salmonella) that uses acetyl-CoA as the donor.  This may also be the same kind of enzyme that modifies the histones, i.e. the histone acetyltransferase activity GO:0004402 + children terms may really belong there.  I realize that the E. coli enzyme currently has annotations to both GO:0052858 and GO:0004468, and both are wrong...

So my proposal: create a new term for peptidyl-lysine acetyltransferase using acetyl-CoA as the donor, and move the histone acetyltransferase terms to become children of that term (but please check that I'm not wrong about the histone stuff...).  

Thanks,
Ingrid

**Comment by ukemi** [comment]
Hi Ingrid,

I have created the suggested term and moved the histone and tubulin acetyltransferases as children of it. I can see no evidence that what you suggest is incorrect. Please let me know if you see any further issues.
 [Term]
+id: GO:0061733
+name: peptide-lysine-N-acetyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: acetyl-CoA + lysine in peptide = CoA + N-acetyl-lysine-peptide." [GOC:dph]
+is_a: GO:0034212 ! peptide N-acetyltransferase activity
+created_by: dph
+creation_date: 2015-09-10T10:22:19Z

-David
