### ISSUE TITLE
GO:0005663 definition update

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12018]
Moved from the paint SF tracker (#68):

It looks like the "and two in prokaryotes" was added as an afterthought to the definition for this term, with two of the cited papers referring to archaea. As far as bacteria go, I have not heard of a replication factor C complex nor of PCNA, although me not having heard of such things is by no means evidence that they don't exist. If the term really does apply to bacteria, it would be nice to see a more inclusive name/synonyms for the term.

Additional comment from Val:
I think PCNA is present in archaea and not in prokaryotes
There are a couple of 'bacterial' protein of unspeciifed taxa in Interpro with this mapping
http://www.ebi.ac.uk/interpro/entry/IPR022649

Pfam seems to support this distribution
http://pfam.xfam.org/family/PF00705#tabview=tab7
http://pfam.xfam.org/family/PF02747#tabview=tab7

I think perhaps the taxon restirctionand the definiton could be changed?

val

**Comment by ukemi** [comment]
I don't see a taxon restriction for this yet. Will this work?:

never_in_taxon: Bacteria <prokaryote> ; NCBITaxon:2

New def: A complex that loads the DNA polymerase processivity factor proliferating cell nuclear antigen (PCNA) onto DNA, thereby permitting processive DNA synthesis catalyzed by DNA polymerase. In eukaryotes the complex consists of five polypeptides.

**Comment by ukemi** [comment]
I made the above changes. Please let me know if you discover that this doesn't work.

 id: GO:0005663
 name: DNA replication factor C complex
 namespace: cellular_component
-def: "A complex of five polypeptides in eukaryotes, and two in prokaryotes, that loads the DNA polymerase processivity factor proliferating cell nuclear antigen (PCNA) onto DNA, thereby permitting processive DNA synthesis catalyzed by DNA polymerase." [PMID:14614842, PMID:14646196, PMID:16172520]
+def: "A complex that loads the DNA polymerase processivity factor proliferating cell nuclear antigen (PCNA) onto DNA, thereby permitting processive DNA synthesis catalyzed by DNA polymerase. In eukaryotes the complex consists of five polypeptides." [PMID:14614842, PMID:14646196, PMID:16172520]
 subset: goslim_pir
 subset: gosubset_prok
 synonym: "activator 1 complex" EXACT []
 synonym: "RFC complex" EXACT []
 is_a: GO:0043234 ! protein complex
 is_a: GO:0044427 ! chromosomal part
+relationship: never_in_taxon NCBITaxon:2 ! Bacteria <prokaryote>
 relationship: part_of GO:0005657 ! replication fork

**Comment by ukemi** [comment]
@ValWood

**Comment by ValWood** [comment]
Sounds good to me. It might help  to say "homooligomeric complex" in the def, I always think its odd when I only see a single gene product annotated to a complex and look for the missing subunits. This is the only case I can think of in pombe where there should only be one GP annotated....

**Comment by ukemi** [comment]
Def changed as suggested.

**Comment by ValWood** [comment]
argh sorry, I just saw  this term come through. I thought it  was PCNA which is homo-oligomer, but DNA replication factor C isn't, its a homo-oligomer!

**Comment by ukemi** [comment]
OK. Changed the definition back.

**Comment by ValWood** [comment]
Sorry about that. I thought it was the ticket about PCNA

**Comment by ukemi** [comment]
No Problem. The def now reads:

"A complex that loads the DNA polymerase processivity factor proliferating cell nuclear antigen (PCNA) onto DNA, thereby permitting processive DNA synthesis catalyzed by DNA polymerase. In eukaryotes the complex consists of five polypeptides." [PMID:14614842, PMID:14646196, PMID:16172520]
