### ISSUE TITLE
TPV pore complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12013]
GO:0046930 pore complex
Any small opening in a membrane that allows the passage of gases and/or liquids.

has nuclear pore as a descendent

(please add Pombase label)

**Comment by ValWood** [comment]
I think this might be the reasoner? has happened before...

**Comment by ukemi** [comment]
I don't see that it would be the reasoner. It looks like it just might be an error if we don't consider the nuclear pore structure to be a small opening in a membrane that allows the passage of substances.

**Comment by ValWood** [comment]
Actually maybe it is OK? but it isn't really an "opening in a membrane".  The membrane does  has no opening (topologically)
http://www.ks.uiuc.edu/Research/npc/

It doesn't particularly seem to make sense to group the nuclear pore with  the "transmembrane  spanning pores"

**Comment by ukemi** [comment]
Yup. I'm on the fence about it. The double membrane has an opening, but the membrane itself is continuous. I think we discussed this before. It seems familiar. I'll see what I can find.

**Comment by ukemi** [comment]
Found it. It was a discussion where we decided that transport through the nuclear pore was not transmembrane transport. So I remove it complex as a child of pore complex.

-David
