### ISSUE TITLE
query about NMS complex interaction involved in chromosome segregation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12014]
NMS complex interaction involved in chromosome segregation
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0044768
The interaction and association of NMS complexes required for kinetochore-spindle binding and chromosome segregation to occur. 

I'm not really sure what this term means. It doesn't seem to be well defined or correctly placed
It has the exact synonyms 
KMN network assembly involved in chromosome segregation
but I'm not sure what KMN network refers to. Is this term really part of kinetochore assembly?
(NMS complex is part of the kinetochore)

The definition implies that it is involved in  kinetochore-spindle attachment, but if it is involved in kinetochore assembly the microtubule attachment process would be a little downstream...

**Comment by ukemi** [comment]
Hi Val,

Have a look at PMID:22561345. Perhaps we should make this a part of kinetochore assembly?

**Comment by ValWood** [comment]
Yep, all the experiments point to kinetochore assembly.
The final sentence is a good summary
"Taken together, our biochemical data (Fig. 6b,c) show that the binding of Cnn1 to Spc24–Spc25 prevents the Mtw1 and Spc105 complexes from binding to the Ndc80 complex"

The biorientation  and microtubule attachment defects seem to be phenotypes which are downstream effects of compromised kinetochore structure.

**Comment by ukemi** [comment]
Moved it and regulation children to be part of kinetochore assembly. Changed names as well.
