### ISSUE TITLE
redundant is_a links under cell cycle process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12016]
There appear to be quite a lot, which is confusing when 'drilling down'

For example:
establishment of sister chromtid cohesion
maintenance of sister chromatid cohesion
spindle elongation
lots of cell cycle DNA replication parts, etc.

Does the reasoner deal with these? I can't remember...

**Comment by ukemi** [comment]
Hi Val,

When I look at these, I see multiple paths, but I'm not sure what you mean by redundant links.

-David

**Comment by ValWood** [comment]
I meant under "cell cycle process".
Actually currently for some (the chromsome segregations ones), we are not seeing redundant links , because the nuclear segregation term is missing these as descendents (which they should be part of).

For the others, like spindle elongation, there are redundant links.
They have part_of links to cell cycle, but they don't need to because they have part of links to other cell cycle descendants (spindle organization). 


Similarly  there are quite a lot under "mitotic cell cycle"  For example "G2/M transition of mitotic cell cycle" does not need to be directly under mitotic cell cycle, as it is under mitotic cell cycle phase transition.

It seems that somehow we are missing some structure under the high level terms with some long flat lists of terms which are represented as children (or should be).

**Comment by ValWood** [comment]
yep, that will be easiest!

**Comment by ValWood** [comment]
Oh.
