### ISSUE TITLE
TPV phosphatase activity F-P link

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12011]
"phosphatase activity" has F-P links to "protein phophorylation" 
but this causes TPV's for some descendants 
for example GO:0008252 nucleotidase activity

please add Pombase label, I don't have permission

**Comment by ukemi** [comment]
Hi Val,
I don't see this link. The only link I see is between 'phosphatase activity' and 'dephosphorylation'.

-David

**Comment by ValWood** [comment]
Yeah I made a note of this last week but I don't know what I was looking at, it is fine
