### ISSUE TITLE
NTR "cellular detoxification of cadmium ion"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12027]
I was about to request 
"cellular detoxification of cadmium ion" using TGFF.

However, the definitions of the 
"detoxification of cadmium ion" sounds as thought it could be referring to a cellular process
"Any process that reduces or removes the toxicity of cadmium ion. These may include transport of cadmium away from sensitive areas and to compartments or complexes whose purpose is sequestration of cadmium ion. 
PMID:16741752"

(I'm not even sure if a non-cellular term should exist? so I thought I would check before I added it)

**Comment by dosumis** [comment]
Could apply to a whole multicellular organism.  I think some plants take up heavy metals and concentrate them in particular structures.  I'll make the cellular term.

**Comment by dosumis** [comment]
id: GO_0098849
*label* "cellular detoxification of cadmium ion"@en
*definition* "Any process that reduces or removes the toxicity of cadmium cations in a cell. These include transport of cadmium cations away from sensitive areas and to compartments or complexes whose purpose is sequestration."
*EquivalentTo:* detoxification that 'occurs in' some cell and 'has input' some 'cadmium cation'
*SubClassOf:*
'detoxification of cadmium ion'  (inferred)
'part of' some 'cellular response to cadmium ion'
'cellular detoxification' (inferred)
