### ISSUE TITLE
MP ferrous iron import

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12022]
should ferrous iron import
have parent
ferrous iron transmembrane transport

(add PomBase label)

**Comment by ukemi** [comment]
Presumably it can happen by endocytosis as well as transmembrane transport.

**Comment by RLovering** [comment]
Hi Both

yes endocytosis does transport iron

Best

Ruth

**Comment by ValWood** [comment]
Its OK, the correct term exists, I missed it:
GO:0098707 ferrous iron import across plasma membrane
