### ISSUE TITLE
ntr: C-rich strand telomeric DNA binding

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12020]
Hi,
I'd like to request a new is_a child term of GO:0043047, single-stranded telomeric DNA binding:

GO:0043047 single-stranded telomeric DNA binding
-GO:new C-rich strand telomeric DNA binding

Suggested def: Interacting selectively and non-covalently with C-rich, single-stranded, telomere-associated DNA.
Reference: http://www.ncbi.nlm.nih.gov/pubmed/18329362

Thanks,
--Kimberly

**Comment by ukemi** [comment]
[Term]
+id: GO:0061730
+name: C-rich strand telomeric DNA binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with C-rich, single-stranded, telomere-associated DNA." [GOC:dph, GOC:kmv, PMID:18329362]
+is_a: GO:0043047 ! single-stranded telomeric DNA binding
+created_by: dph
+creation_date: 2015-08-20T09:08:27Z
