### ISSUE TITLE
ubiquitin transferase related follow up

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12025]
@ukemi 

Is this arrangement OK?
It maps to both "regulation of ligase" and "regulation of transferase"
it might be a left over from the "ubiquitin ligase overhaul"?
Val

**Comment by ValWood** [comment]
![ask_david](https://cloud.githubusercontent.com/assets/7359272/9407034/b40fbe88-47fd-11e5-9866-72c4b2397e85.jpg)

**Comment by ValWood** [comment]
the term is
GO:0051439 regulation of ubiquitin-protein ligase activity involved in mitotic cell cycle
which is not obvious from the screen shot. Might apply to other regulation terms too.

**Comment by ukemi** [comment]
I could have sworn I had removed all the links to the ligase term. They hopefully are gone now. Thanks Val.

-D
