### ISSUE TITLE
possible MP, adenosine kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12023]
for adenosine kinase activity

I am picking up an InterPro mapping to 
GO:0016773	phosphotransferase activity, alcohol group as acceptor
is this correct (it looks as thought the acceptor is an alcohol group)

If so can it be added as an ancestor. If not I will  address the mapping,

Thanks

**Comment by ukemi** [comment]
Looks like it to me too. Relationship is now added.
