### ISSUE TITLE
renal glomerular podocyte projection & renal glomerular podocyte foot NTR

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#12026]
I would like to request the term renal glomerular podocyte projection &renal glomerular  podocyte foot.
PMID:   24309184 (zebrafish)
PMID:   25324828 (human, rat)

cell projection (GO:0042995)
              is_a renal glomerular podocyte projection
                      part_of renal glomerular podocyte foot 
                               
             is_a renal glomerular podocyte foot  
                        part_of slit diaphram ( GO:0036057)

renal glomerular podocyte projection 
syn: podocyte major process, primary podocyte process
def:  cell projection originating from a renal glomerular  podocyte and extending to the renal glomerular podocyte foot part_of CL:1000451.

renal glomerular podocyte foot  
syn: secondary podocyte process, 
def:  cell projection that extends from the podocyte projection and terminates at the renal glomerular capillary. part_of CL:1000451 The podocyte foot contains slit diaphrams that connect adjacent podocyte foot processes.

Note: a similar request was made before and was rejected because GO didn't want to make parts of particular cells, however now most of the children of cell projection are parts of specific types of cells.   Pollen, neuron, astrocyte etc.  

If someone has a better way of naming the cell then epithelial cell of visceral layer of glomerular capsule or renal glomerular podocyte that would be great.  Issue at the moment is renal may exclude the pronephric glomerularus and those cells definitely have foot process.  The modern medical literature seems to be using the term foot process to describe the cell projection from the podocyte. 

There are several diseases and injury that cause effacement of the podocyte foot process.

**Comment by cerivs** [comment]
@cmungall  How do I add labels?

**Comment by cmungall** [comment]
go to https://github.com/geneontology/ you should see an invite, if you accept you *should* have permission to do this but if not let me know

**Comment by ValWood** [comment]
Doh *I* see how to subscribe now. Thanks.
val

**Comment by dosumis** [comment]
Seems reasonable.  One wrinkle so far: which CL term to use:

[glomerular visceral epithelial cell](http://purl.obolibrary.org/obo/CL_0000653) vs [epithelial cell of visceral layer of glomerular capsule](http://purl.obolibrary.org/obo/CL_1000451).  No relationship between the two. Possibly identical and in need of merging.  Hard to investigate further in the absence of references or usage examples.

**Comment by dosumis** [comment]
Also, looks like the slit diaphragm is not part of a single foot, but bridges between feet of adjacent cells.  GO currently reflects this, having: 'slit diaphragm' **overlaps** *some* [glomerular visceral epithelial cell](http://purl.obolibrary.org/obo/CL_0000653).  The relation should be moved down to the new foot term.

**Comment by dosumis** [comment]
How's this: 

**label** "podocyte foot"
**definition** "A cell projection of a podocyte (glomerular visceral epithelial cell) forming a foot-like structure projecting from a podocyte primary projection, that wraps around capalliaries of a renal glomerulus. Adjacent feet (pedicels) interdigitate, leaving thin filtration slits between them, which are covered by slit diaphragms." [PMID:25324828]
**has_exact_synonym** "pedicel"
**has_exact_synonym** "podocyte foot process"
**has_exact_synonym** "secondary podocyte projection"
**database_cross_reference** "Wikipedia:Podocyte"
***SubClassOf:***
* 'cell projection'
* 'part of' *some* 'glomerular visceral epithelial cell'

**Comment by cmungall** [comment]
```
[Term]
id: UBERON:0004355
name: podocyte foot process
def: "The footlike extension of podocytes that interdigitate with one 
another to form the walls of the glomerular capillaries" [MP:0008059]
property_value: editor_note "TODO - submit to GO" xsd:string
is_a: UBERON:0000470 ! cell part
relationship: part_of CL:0000653 ! podocyte
subset: pheno_slim
```

Will gladly replace as the comment suggests

**Comment by cerivs** [comment]
David's term works well for us.  Uberon term says the foot process form the capillary walls which isn't quite correct.

**Comment by dosumis** [comment]
Fixed
