### ISSUE TITLE
Patterns for axiomatisation of transcription factor activities

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12033]
We currently have patterns like this:

* molecular_function that ('has part' some 'nucleic acid binding') and ('part of' some 'regulation of transcription, DNA-templated')

* molecular_function and ('part of' some 'regulation of nucleic acid-templated transcription') and ('has part' some 'RNA polymerase core enzyme binding')

But these patterns are not safe.  It is not necessarily the case that being part of a regulatory process entails being a regulator of the regulated process.  This pattern probably arose from implementation of the general MF part_of BP pattern.  In this case, it would be better to directly assert MF regulation of BP.  But which relation to use?

Perhaps directly activates:

Current def: "p directly activates q if and only if p is immediately upstream of q and p is the realization of a function to increase the rate or activity of q."

But see [notes from 2015-07-23 eds meeting](http://gocwiki.geneontology.org/index.php/Ontology_meeting_2015-07-23#Implement_MF_patterns_using_directly_regulation_relations.3F)  on defining directly postively regulates.

CC @cmungall @ukemi

**Comment by cmungall** [comment]
I think 'directly activates' is correct here, even if we have a more general direct regulation parent that is not restricted to activities

**Comment by ukemi** [comment]
It fits the definition of directly activates.

**Comment by dosumis** [comment]
This issue was moved to geneontology/design_patterns#2
