### ISSUE TITLE
change "protein localization to cell division site after cytokinesis"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12030]
I requested this term.
GO:0098841	protein localization to cell division site after cytokinesis

but I would like to change it.

The "localization" is involved in "cell separation after cytokinesis" but I am not sure if the protein is localized there before during or after cytokinesis takes place.

The term would be better as
protein localization to cell division site involved in cell separation after cytokinesis

Could the term be changed (it has no annotations yet and this was the intended meaning).

Once that is  done I will request the regulation terms using  the TG template

**Comment by dosumis** [comment]
Hi Val, You should be able to make this with the TermGenie inolved in (BP BP) template.  I'll then merge the resulting term with the old term.
Cheers,
David

**Comment by ValWood** [comment]
OK, I did this
