### ISSUE TITLE
obsolete response to phorbol ester terms?

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12037]
Response to phorbol esters terms - should probably not have been allowed through TG (my fault). 

Phorbol esters are used to mimic DAG activiation of PKC (although probably have other effects too) - e.g. see http://www.ncbi.nlm.nih.gov/pubmed/17661218

[Term]
id: GO:1904627
name: response to phorbol 13-acetate 12-myristate
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a phorbol 13-acetate 12-myristate stimulus." [GO_REF:0000071, GOC:TermGenie, PMID:2200903]
synonym: "response to phorbol 12-tetradecanoate 13-acetate" EXACT []
synonym: "response to PMA" EXACT []
synonym: "response to tetradecanoylphorbol acetate" EXACT []
synonym: "response to TPA" EXACT []
is_a: GO:0033993 {is_inferred="true"} ! response to lipid
is_a: GO:1901700 {is_inferred="true"} ! response to oxygen-containing compound
intersection_of: GO:0050896 ! response to stimulus
intersection_of: has_input CHEBI:37537 ! phorbol 13-acetate 12-myristate
relationship: has_input CHEBI:37537 {is_inferred="true"} ! phorbol 13-acetate 12-myristate
created_by: sl
creation_date: 2015-08-28T13:44:03Z

[Term]
id: GO:1904628
name: cellular response to phorbol 13-acetate 12-myristate
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a phorbol 13-acetate 12-myristate stimulus." [GO_REF:0000071, GOC:TermGenie, PMID:2200903]
synonym: "cellular response to phorbol 12-tetradecanoate 13-acetate" EXACT []
synonym: "cellular response to response to PMA" EXACT []
synonym: "cellular response to tetradecanoylphorbol acetate" EXACT []
synonym: "cellular response to TPA" EXACT []
is_a: GO:0071396 {is_inferred="true"} ! cellular response to lipid
is_a: GO:1901701 {is_inferred="true"} ! cellular response to oxygen-containing compound
is_a: GO:1904627 {is_inferred="true"} ! response to phorbol 13-acetate 12-myristate
intersection_of: GO:0070887 ! cellular response to chemical stimulus
intersection_of: has_input CHEBI:37537 ! phorbol 13-acetate 12-myristate
relationship: has_input CHEBI:37537 {is_inferred="true"} ! phorbol 13-acetate 12-myristate
created_by: sl
creation_date: 2015-08-28T13:44:10Z

**Comment by cmungall** [comment]
Adding text "use case for assay ontology" so can find this later

**Comment by dosumis** [comment]
Also wondering what to do with this: 

[Term]
id: GO:1990840
name: response to lectin
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a lectin stimulus. A lectin is a carbohydrate-binding protein, highly specific for binding sugar moieties." [PMID:2200903]
subset: termgenie_unvetted
is_a: GO:0071216 ! cellular response to biotic stimulus
created_by: sl
creation_date: 2015-08-27T20:02:21Z

At first I thought we shouldn't allow this as in many cases experiments will be looking at toxic effects of lectins.  But after doing some more reading, I have found cases of endogenous lectins and their receptors in animals.  Probably needs a comment to say that this should NOT be used to annotated the toxic effects of exogenous lectins.

**Comment by dosumis** [comment]
Response to lectin added, but with a comment pointing out that this doesn't cover simple toxicity.

**Comment by pgaudet** [comment]
Asked for a review of the annotations 

https://github.com/geneontology/go-annotation/issues/1793
https://github.com/geneontology/go-annotation/issues/1794

Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:1904628 cellular response to phorbol 13-acetate 12-myristate and its parent GO:1904627 response to phorbol 13-acetate 12-myristate. The reason for obsoletion is that phorbol esters are used to mimic DAG activation of PKC or induce tumors  - e.g. see http://www.ncbi.nlm.nih.gov/pubmed/17661218 and https://en.wikipedia.org/wiki/Phorbol_esters


There are 18 EXP annotations to these terms: 
https://github.com/geneontology/go-annotation/issues/1793
There are no mappings to this term. 

Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/12037


We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 7, 2018. Unless objections are received by Feb 7, 2018, we will assume that you agree to this change. 


Thanks, Pascale

**Comment by slaulederkind** [comment]
I'm not seeing any reason to obsolete these terms.  If an experiment is using phorbol ester in a short time course (30 - 60 min), I can see where "PKC signaling" could reasonably be substituted.  However, in a longer time course (6-24 hrs) it is not reasonable to use "PKC signaling" because the end measurement may be far downstream from PKC.  I'd rather user a vaguer term like "response to ..." in this second case.

Based on David's comments, I think the "lectin" term should be kept.

**Comment by pgaudet** [comment]
Hi @slaulederkind 

I agree about the lectin. 

Phorbol ester is a little different, especially if it's used to mimic a pathway, but I agree with you that it could remain. Phorbol esters are natural compounds produced by plants, it seems conceivable that organisms that can encounter these plants can respond to the compounds that they produce. 

What do you think @thomaspd ? @ukemi @vanaukenk @ValWood ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
We probably need a proposal to deal with 'response to'; both at the level of rules for terms to be created, and for annotation rules.
