### ISSUE TITLE
mitochondrial fragmentation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12038]
Consider adding "mitochondrial fragmentation" as a synonym to "mitochondrial fission (GO:0000266)" and its appropriate variations in children terms. PMID:26143143

**Comment by ValWood** [comment]
Is this the same? Fragmentation is apoptotic isn't it? fission is division of the mitochondria.

**Comment by slaulederkind** [comment]
Some authors use “fragmentation” and “fission” interchangeably.  “mitochondrial fragmentation involved in apoptotic process” (GO:0043653) is a child term of “mitochondrial fission”, so it seems reasonable to use “fragmentation” as a synonym of “fission”.

Stanley J. F. Laulederkind, Ph.D.
Rat Genome Database
Human Molecular Genetics Center
Medical College of Wisconsin
8701 Watertown Plank Rd
Milwaukee WI 53226
(Phone) 414-955-7513
(Fax) 414-456-6516

**Comment by tberardini** [comment]
I'd rather add 'mitochondrial fission' as a broad synonym of "mitochondrial fragmentation involved in apoptotic process” (GO:0043653).  That way, searching on the term 'mitochondrial fragmentation' only brings up the more specific term but searching on 'mitochondrial fission' brings up both the parent and the more specific term.  People using the fission term to refer to fragmentation (and not division) will then see that there is the more specific fragmentation term that exists and that more accurately describes their process.

**Comment by tberardini** [comment]
Related to #11652. Reassigning to @ukemi.

**Comment by Pauldenny** [comment]
In conversation with an expert on mitochondrial physiology (Unit Head, Mitochondrial Molecular Cell Biology and Pharmacology Research at The Royal Veterinary College, University of London), he said that despite other authors' usage e.g. PMID: 26143143, he said that "authors which use the terms interchangeably are wrong".
