### ISSUE TITLE
NTR: midbrain neurogenesis

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12039]
Similar to the existing ‘forebrain generation of neurons ; GO:0021872’ term, I’d like to add in some corresponding midbrain terms for the annotation of PMID:19122665 and related papers.

In summary: dopaminergic neurons arise from the midbrain floor plate. In the midbrain, canonical Wnt signaling represses Shh and promotes the genesis of DA neurons from the floor plate.

One issue I have is that the intersections of the existing terms are defined based on the CL type. E.g:
id: GO:0021879
name: forebrain neuron differentiation
intersection_of: GO:0030154 ! cell differentiation
intersection_of: results_in_acquisition_of_features_of CL:0012001 ! neuron of the forebrain
relationship: part_of GO:0021872 ! forebrain generation of neurons

I can’t see a CL term for ‘neuron of the midbrain’ so my intersections currently reference the anatomical location: it’s not ideal to mix them like this, so would you prefer I request new CL terms?

generation of neurons ; GO:0048699
—[isa]midbrain generation of neurons ; GO:NEW1
——[partof]midbrain dopaminergic neuron differentiation ; GO:NEW2

dopaminergic neuron differentiation ; GO:0071542
——[isa]midbrain dopaminergic neuron differentiation ; GO:NEW2

midbrain generation of neurons ; GO:NEW1
is_a: generation of neurons ; GO:0048699
occurs_in: midbrain ; UBERON:0001891
The process in which nerve cells are generated in the midbrain.
exact synonym: mesencephalon generation of neurons (UBERON:0001891)
exact synonym: midbrain neurogenesis (GO:NEW)
narrow synonym: midbrain floor plate neurogenesis (PMID: 19122665)
GOC:PARL, GOC:bf
PMID: 19122665

midbrain dopaminergic neuron differentiation ; GO:NEW4
The process in which a midbrain floor plate cell acquires the specialized structural and functional features of a dopaminergic neuron, a neuron that secretes dopamine.
is_a: dopaminergic neuron differentiation ; GO:0071542
occurs_in: floor plate of midbrain ; UBERON:0003307
PMID:17331494, 19122665
exact synonym: midbrain DA neurogenesis [PMID:19122665]
exact synonym: DA neurogenesis from midbrain floor plate [PMID:19122665]
exact synonym: midbrain dopaminergic neuron production [PMID:19122665, GOC:bf]
exact synonym: mDA neuron differentiation [PMID:24287202, GOC:bf]

Thanks.

**Comment by tberardini** [comment]
@cmungall, can you comment on the CL-related question?

"I can’t see a CL term for ‘neuron of the midbrain’ so my intersections currently reference the anatomical location: it’s not ideal to mix them like this, so would you prefer I request new CL terms?"

**Comment by cmungall** [comment]
I'm sure there is an almost equivalent ticket from @cerivs about perhaps forebrain neurons... do we want a specific subclass or just to say it's ccurring in that part of the brain. My github fu is failing and can't find the ticket, do you know Ceri?

**Comment by tberardini** [comment]
Try these:

#11917 and #10268

**Comment by cerivs** [comment]
https://github.com/geneontology/termgenie/issues/71#issuecomment-112330898

**Comment by dosumis** [comment]
Suggested resolution:

1. Request midbrain dopaminergic neuron from CL 
2. Add GO term using pattern
intersection_of: GO:0030154 ! cell differentiation
intersection_of: results_in_acquisition_of_features_of <new CL term>

This is a fine EC definition with minimal commitment.  
optionally add occurs_in floor plate as SubClassOf axiom (relationship).

Not sure intermediate terms are worth worrying about.

**Comment by rebeccafoulger** [comment]
Request submitted to CL tracker: https://github.com/obophenotype/cell-ontology/issues/415

**Comment by rebeccafoulger** [comment]
Chris added: ID: CL:2000097 Label: midbrain dopaminergic neuron

I'll create the GO differentiation term when the CL term is live and recognised by TG.

**Comment by rebeccafoulger** [comment]
New GO term created:

Haven't added the 'midbrain generation of neuron' term for now as all my annotations will fall to the more specific term.
