### ISSUE TITLE
connective tissue replacement involved in inflammatory response wound healing - better ref needed

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12035]
Also regulates varients:

id: GO:1904596
name: regulation of connective tissue replacement involved in inflammatory response wound healing

From usage and synonyms, it looks like this term is a class for recording fibrosis.  Would be good to have a ref and perhaps a comment that makes this clearer.

**Comment by pgaudet** [comment]
MGI and BHF-UCL has annotations to these terms- do you have suggestions for definitions? 
@ukemi @RLovering 

If not we'll just close the ticket. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
how about adding more information to the parent term:  GO:0002248 
connective tissue replacement involved in inflammatory response wound healing 
Ref: PMID:9639571 
narrow synonym: tissue fibrosis development
This term already has the narrow synonym: fibrosis during inflammatory response

the regulation term also has a fibrosis synonym, but the additional narrow synonym could be added:narrow synonym: regulation of tissue fibrosis development
Is this sufficient to close this ticket?
Ruth

**Comment by pgaudet** [comment]
@addiehl

**Comment by pgaudet** [comment]
This doesn't sound like a normal process, especially given the reference cited: 
https://pubmed.ncbi.nlm.nih.gov/18245812/

but I updated the definitions as you suggested @RLovering 

Thanks for the feedback.
