### ISSUE TITLE
NTR: alpha-D-ribose 1-methylphosphonate 5-phosphate C-P-lyase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12031]
For EC 4.7.1.1.

Thanks,
Ingrid

**Comment by dosumis** [comment]
Added:
id: GO:0098848
label "alpha-D-ribose 1-methylphosphonate 5-phosphate C-P-lyase activity"@en
has_obo_namespace "molecular_function"
definition "Catalysis of the reaction: alpha-D-ribose 1-methylphosphonate 5-phosphate = alpha-D-ribose 1,2-cyclic phosphate 5-phosphate + methane."
has_exact_synonym "alpha-D-ribose-1-methylphosphonate-5-phosphate C-P-lyase (methane forming)"
database_cross_reference "EC:4.7.1.1"

**Comment by keseler** [comment]
Hi,
I can't find the new term yet - is there some sort of lag before new terms become public?
Thanks,
Ingrid

**Comment by dosumis** [comment]
Hi Ingrid,

My fault.  I thought I'd commited, but this change was stuck in a branch version of the ontology i've been working on.  I've just commited.  The new term should be in tonight's GO release.

Sorry for the delay,

David
