### ISSUE TITLE
Manually move all JIRA tickets here

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12032]
or close them

The main reason for using JIRA originally was the sub-tickets. If we need to preserve any of this we can use milestones or labels, but I think that what is left on JIRA is really isolated tickets and not really project-level items any more

**Comment by pgaudet** [comment]
@cmungall should this be closed ?

**Comment by cmungall** [comment]
Yes

**Comment by pgaudet** [comment]
Voila !
