### ISSUE TITLE
add taxon constraints on apoptosis

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12041]
Currently:

```
relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0000490"} ! Viridiplantae
```

That's it, including inherited. So it's valid to annotate E coli with apoptosis in GO.

I suggest Opisthokontes conservatively

**Comment by paolaroncaglia** [comment]
Hi Chris,

Yes, restricting ‘apoptotic process’ to Opisthokonta (Fungi/Metazoa group - Taxonomy ID: 33154) sounds like a good idea. 
If that’s ok with you, I’ll keep this edit for next week when Melanie is on her first GH/TG rotation, so I can show her an example of taxon rule edit - and one best done with OBO-Edit at the moment ;-)

Note that while the use of ‘apoptosis’ is indeed discouraged in bacteria (http://www.sciencedirect.com/science/article/pii/S1286457913001044), there is growing evidence of programmed cell death events in prokaryotes (http://www.nature.com/nrmicro/journal/v12/n1/full/nrmicro3136.html). But we’re good - ‘programmed cell death’ doesn’t have any taxon restriction.

Paola

**Comment by paolaroncaglia** [comment]
Edited taxon rule for GO:0006915 'apoptotic process' as follows:

-relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0000490"} ! Viridiplantae
+relationship: only_in_taxon NCBITaxon:33154 ! Opisthokonta

Thanks,

Paola
