### ISSUE TITLE
MP guanylate kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12047]
should this 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004385#term=ancchart
have
GO:0006163	purine nucleotide metabolic process		UniProt
in its ancestry? I am picking up a mapping from UniProt

**Comment by tberardini** [comment]
@hdrabkin, help please

**Comment by deustp01** [comment]
We decided that dephosphorylation of NTP's is not catabolism by default, and we might someday want to decide that phosphorylation of nucleosides, NMPs and NDPs is not necessarily nucleotide metabolism, but for now it is, I think. And there's probably a legitimate distinction between the shuttling between NTP and NDP versus steps between nucleoside and NDP, where the latter fall into metabolism and the "shuttle" does not.

**Comment by tberardini** [comment]
@deustp01 - does this ("but for now it [phosphorylation ...is...nucleotide metabolism] is, I think.") mean that you support making this relationship:

'guanylate kinase activity' part_of 'purine nucleotide metabolic process?'

Reaction in the MF def is 'ATP + GMP = ADP + GDP.' 

In ChEBI, GMP is a purine nucleotide, as is GDP.

**Comment by deustp01** [comment]
Yes, that's what I'm trying to say.

**Comment by tberardini** [comment]
Gotcha.  Thanks.  I'll create the link.

**Comment by tberardini** [comment]
Link created to more specific terms

part_of GMP metabolic process
part_of GDP metabolic process

The term will inherit the parentage to part_of 'purine nucleotide metabolic process'
