### ISSUE TITLE
Question about pheromone transporter terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12048]
Hello,

Would it be appropriate to have specific MF terms for "pheromone transporters"?
We currently annotate these to "peptide transporter activity" and descendants.

I ask because I am creating a config file  to propost for applicable annotation extensions in Canto. For the pheromone terms we can supply an extension, but for most peptides (glutathione, phytochelatin, siderophore, we would not as it is captured with the term.

Also, we need an intermediate term"peptide transmembrane transporter" as this does not currently exist

.....i just noticed siderophore transporter are not classed as peptide transporters, although ferrichrome is....is there a reason for that? aren't all siderophores peptides?

**Comment by tberardini** [comment]
Three separate issues here:

1. NTR pheromone transporter term: I'm inclined to not create this new term as 'pheromone' is a ChEBI role and not a classification by structure.    A similar situation (role transporter activity) exists for 'toxin transporter activity' and it is handled this way:

[Term]
id: GO:0019534
name: toxin transporter activity
namespace: molecular_function
intersection_of: GO:0005215 ! transporter activity
intersection_of: transports_or_maintains_localization_of GOCHE:27026 ! substance with toxin biological role

It's a band-aid using GOCHE. @cmungall, care to comment?

2. NTR: peptide transmembrane transporter activity - you should be able to create this using TermGenie. The template to use is 'chemical_transmembrane_transporter_activity.'

3. placement of 'siderophore transporter' in graph.  Siderophore is also a ChEBI role, band aid for this one is GOCHE:26672 ! substance with siderophore chemical property.  I don't know if *all* siderophores are peptides.  The ChEBI def (Any of low-molecular-mass iron(III)-chelating compounds produced by microorganisms for the purpose of the transport and sequestration of iron.) doesn't support that.

**Comment by tberardini** [comment]
@ValWood - thoughts?

**Comment by ValWood** [comment]
sounds good to me!

**Comment by tberardini** [comment]
Added this for you:

[Term]
id: GO:1904680
name: peptide transmembrane transporter activity
namespace: molecular_function
def: "Catalysis of the transfer of peptide from one side of the membrane to the other." [GO_REF:0000070, GOC:TermGenie, GOC:vw]
is_a: GO:0015197 {is_inferred="true"} ! peptide transporter activity
is_a: GO:0042887 {is_inferred="true"} ! amide transmembrane transporter activity
intersection_of: GO:0022857 ! transmembrane transporter activity
intersection_of: transports_or_maintains_localization_of CHEBI:16670 ! peptide
relationship: transports_or_maintains_localization_of CHEBI:16670 {is_inferred="true"} ! peptide
created_by: tb
creation_date: 2015-09-22T18:50:41Z

Closing.
