### ISSUE TITLE
refine F-P link glucose transmembrane transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12045]
Sorry one more
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005358#term=ancchart

GO:0005355 glucose transmembrane transporter activity
currently goes to
GO:0015758 glucose transport
instead of
glucose transmembrane transport

**Comment by ValWood** [comment]
glucose transmembrane transport appears not to exist. Will TG it now.

**Comment by ValWood** [comment]
ID: GO:1904659 Label: glucose transmembrane transport

some existing terms should be descendants of this

**Comment by tberardini** [comment]
the only existing term that became a child of 'glucose transmembrane transport' after creation by TG was
id: GO:0098708, glucose import across plasma membrane

**Comment by tberardini** [comment]
Done.

+is_a: GO:1904659 ! glucose transmembrane transport
-relationship: part_of GO:0015758 ! glucose transport
