### ISSUE TITLE
query about parentage of protein targeting to nucleus vs nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12049]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0042990#term=ancchart
GO:0042990 regulation of transcription factor import into nucleus

has a protein targeting parent and a nucleocytoplasmic trasnport parent.

Is all protein transport via nucleocytoplasmic transport "protein targeting"?

because some protein import and export terms have different parentage:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0046827#term=ancchart

**Comment by ValWood** [comment]
here's another example to illustrate the inconsistency.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006606#term=ancchart
Here,  "protein import into nucleus" is a descendent of  "protein targeting to nucleus"

**Comment by pgaudet** [comment]
I think this one is resolved via 
#13754  Targeting versus localization and import  
#13686 (ongoing)

If you agree, please close this ticket. 

Thanks, Pascale

**Comment by ValWood** [comment]
agreed, closing
