### ISSUE TITLE
negative regulation of GO:0061630 ubiquitin protein ligase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12046]
@ukemi
can we have

regulation of 
and
negative regulation of GO:0061630 ubiquitin protein ligase activity
(at present we only have 
negative regulation of ubiquitin-protein transferase activity...maybe we can use this but rename...I just want the regulation term to match the term name I am regulating but with the correct transferase parents.

**Comment by ukemi** [comment]
Added all three regulation types in TermGenie. I will tidy up the existing terms once these new regulation terms get added.
