### ISSUE TITLE
Request for new child term(s) and definition edit of GO:0072588, Box H/ACA RNP complex

### ISSUE THREAD

**Issue by JessBuxton** [geneontology/go-ontology#12040]
Hi,
I have been annotating the role of the box H/ACA RNP complex core proteins in the assembly of human telomerase, using information in PMID 22527283. I would like to suggest a new child of the following term, in order to better annotate this specific RNP complex:

GO:0072588 Box H/ACA RNP complex Ontology Cellular Component Definition A ribonucleoprotein complex that contains an RNA of the box H/ACA type, a subtype of the small nucleolar RNA (snoRNA) family. RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs, although some have evolved other functions. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and on U2 small nuclear RNA (U2 snRNA).

Current child terms: 
box H/ACA snoRNP complex GO:0031429
box H/ACA scaRNP complex GO: 0072589

The complex formed between the telomerase RNA and these same proteins is also a child of GO:0072588 Box H/ACA RNP complex, but the telomerase RNP is not a snoRNP or a scaRNP. Furthermore, both snoRNPs and scaRNPs have pseudouridylation synthase activity, but the telomerase RNP is one of several box H/ACA RNPs that does not have this catalytic activity.

Therefore I would like to suggest the following new child Cellular Component term of GO:0072588 Box H/ACA RNP complex:
box H/ACA telomerase RNP complex 

Definition of new term, suggestion (or better):
A box H/ACA ribonucleoprotein complex that contains the RNA component of telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell.

Reference: recent review PMID 25590339, in which the authors state 
“All H/ACA RNPs consist of one name and function specifying H/ACA RNA and the same 4 core proteins (Fig. 2). The core proteins are essential for the stability of all H/ACA RNAs and of each other, and for catalysis of pseudouridylation. Surprisingly, it appears that for the majority of H/ACA RNPs, at least in mammalian cells, the enzymatic activity of the pseudouridine synthase is irrelevant but its function in maintaining the RNAs is paramount. These structural classes of H/ACA RNPs include the telomerase RNP, intron-encoded Alu (AluACA) RNPs and small nucleolar-long noncoding (sno-lnc) RNPs (Fig. 2)13-15.Although it is not clear on which side the orphan H/ACA RNPs will come down, structural H/ACA RNPs outnumber catalytic ones in diversity by about 4 to 1, whereas the catalytic RNPs are far more abundant in terms of copy number".

Also, I suggest adding to the tree for GO:0072588 Box H/ACA RNP complex to distinguish between these 'catalytic' and 'structural' types of box H/ACA RNP complexes as summarised in Fig. 2 of PMID 25590339. Two ways this could be achieved are suggested below (and/or/better), also see attached diagram:

1.	Create two more Cellular Component children of GO:0072588 box H/ACA RNP complex, something like:
- box H/ACA RNP complex with pseudouridylation synthase activity
- box H/ACA RNP complex without pseudouridylation synthase activity

2.	Create links between the function term GO:0009982 pseudouridine synthase activity and both of the existing terms below: 
- box H/ACA snoRNP complex GO:0031429
- box H/ACA scaRNP complex GO: 0072589

Finally, perhaps it would be good to update the current definition of GO:0072588  box H/ACA RNP complex as follows, to address the above issue and also the fact that not all box H/ACA RNAs are snoRNAs, suggestion below (or better):
 
GO:0072588 Name box H/ACA RNP complex Ontology Cellular Component Definition A ribonucleoprotein complex that contains an RNA of the box H/ACA type. RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity. These include the telomerase RNP complex.

Thanks,
Jess Buxton
GOC jbu
GOC BHF
GOC BHF_telomere
@NancyCampbell
![box h_aca rnp complex term issues](https://cloud.githubusercontent.com/assets/13866702/9627996/e8f602ae-515f-11e5-89aa-2dc96cb79ac4.png)

**Comment by JessBuxton** [comment]
@NancyCampbell

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by tberardini** [comment]
@bmeldal, can you comment please?

**Comment by bmeldal** [comment]
Hi Jess and Tanya,

I agree, for the status quo situation adding the GO:NEW box H/ACA telomerase RNP complex makes sense.

As for making two subclasses for the parent term GO:0072588 Box H/ACA RNP complex: If the parent term as well as the three child terms have a sufficiently detailed defs to indicate that they can have catalytic or scaffolding functions I would hold off on creating the two extra intermediate term. If you are sure that the snoRNPs and scaRNPs are always catalytic, then they can have the capable_of link to the activity and the other two terms aren't needed at all but the reasoner will take care of the placements..

Birgit

**Comment by JessBuxton** [comment]
Hi Birgit and Tanya,

Thanks for your suggestion – so to clarify, would the best solution for now be as follows:

1. Create one new child term of GO:0072588 Box H/ACA RNP complex:

Box H/ACA telomerase RNP complex 

Definition of new term, suggestion (or better):
A box H/ACA ribonucleoprotein complex that contains the RNA component of telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell

2. Update definition of GO:0072588 Box H/ACA RNP complex, suggestion (or better):
A ribonucleoprotein complex that contains an RNA of the box H/ACA type. RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity. These include the telomerase RNP complex.

3. Create capable_of links between the function term GO:0009982 pseudouridine synthase activity and both of the existing child terms: 
- box H/ACA snoRNP complex GO:0031429
- box H/ACA scaRNP complex GO:0072589

4.Create a capable_of_part_of link between the new child term 
Box H/ACA telomerase RNP complex and:
The component term GO:0005697 telomerase holoenzyme complex and/or part_of  (or capable_of_part_of ?)the function term GO:0003720 telomerase activity

**Comment by bmeldal** [comment]
That sounds good so far. Couple of comments (I don't know how to reply in-line :( ):

@tberardini: should we have some reference to the proteins of the complexes in the defs? At the moment it only specifically refers to the RNA components.

Relationships:
GO:0031429 box H/ACA snoRNP complex
capable_of GO:0009982 pseudouridine synthase activity 
and
GO:0072589 box H/ACA scaRNP complex
capable_of GO:0009982 pseudouridine synthase activity 
are fine.

However:
GO:NEW Box H/ACA telomerase RNP complex 
should be
capable_of_part_of GO:0032206 positive regulation of telomere maintenance (or a child?)

It can only be part_of GO:0005697 telomerase holoenzyme complex
if ALL its components are also components of the telomerase. If that doesn't hold, then there cannot be a link between the two above terms.

Relationships (for complexes) work as follows:
capable_of <some MF>
capable_of_part_of <some BP>
is_a some <CC>
part_of some <CC>

Hope that helps,
Birgit

**Comment by JessBuxton** [comment]
Hi Birgit,

that's very helpful thanks - I think GO:NEW Box H/ACA telomerase RNP complex should be
capable_of_part_of GO:1904358 positive regulation of telomere maintenance via telomere lengthening (a child of GO:0032206 positive regulation of telomere maintenance) 

The four core proteins that are all part of GO:0072588 Box H/ACA RNP complex are dyskerin, NOP10, NHP2 and GAR1, ref http://www.tandfonline.com/doi/full/10.4161/15476286.2014.972855#abstract

**Comment by JessBuxton** [comment]
Hi again, on reflection I think this is a more specific term:
GO:NEW Box H/ACA telomerase RNP complex should be
capable_of_part_of GO:0032212 positive regulation of telomere maintenance via telomerase

**Comment by tberardini** [comment]
Want to make sure one last time that we are not creating GO terms for specific protein complexes but rather ones for classes of complexes.  The GO term can then be used to annotate specific complexes from various organisms.

**Comment by JessBuxton** [comment]
Hi Tanya,
the GO:NEW Box H/ACA telomerase RNP complex would refer to a specific type of H/ACA RNP complex, which contains a specific RNA plus the same 4 core proteins (conserved from yeast through  to mammals) present in all other H/ACA RNPs.  So it is a specific complex but yes could be used to annotate the same complex in other species - Ref fig 2 and the section entitled "H/ACA core proteins" in
http://www.tandfonline.com/doi/full/10.4161/15476286.2014.972855

**Comment by tberardini** [comment]
Summarizing again, for action:
1. Create one new child term of GO:0072588 Box H/ACA RNP complex:
Box H/ACA telomerase RNP complex
A box H/ACA ribonucleoprotein complex that contains the RNA component of telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell
2. Update definition of GO:0072588 Box H/ACA RNP complex:
A ribonucleoprotein complex that contains an RNA of the box H/ACA type. RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity. These include the telomerase RNP complex.
3. GO:0031429 box H/ACA snoRNP complex
capable_of GO:0009982 pseudouridine synthase activity
and
GO:0072589 box H/ACA scaRNP complex
capable_of GO:0009982 pseudouridine synthase activity 
4.GO:NEW Box H/ACA telomerase RNP complex
capable_of_part_of GO:0032212 positive regulation of telomere maintenance via telomerase
**what about** part_of GO:0005697 telomerase holoenzyme complex?
5. I will add in the names of the four core proteins into the parent term.  Are these: dyskerin, NOP10, NHP2 and GAR1, the names of the human proteins, yeast?  Thanks.

**Comment by JessBuxton** [comment]
Hi Tanya, thanks for this - in answer to your points:

5. Yes the four core proteins that are present in all Box H/ACA RNP complexes are called dyskerin, NOP10, NHP2 and GAR1 in human, and Cbf5 (ortholog of dyskerin), Nop10 Nhp2 and Gar1 in yeast. 

I realise I need to clarify a couple of issues that may affect the suggested new definitions of the GO:NEW Box H/ACA telomerase RNP complex and GO:0072588 Box H/ACA RNP complex, and also your suggestion to add a link between GO:NEW Box H/ACA telomerase RNP complex and part_of GO:0005697 telomerase holoenzyme complex.

Although the components of all Box H/ACA RNP complexes are evolutionarily conserved from yeast to humans, the formation of the telomerase RNP complex differs between vertebrates (where a Box H/ACA RNP complex forms with the four core proteins and the TERC RNA) and other taxa (ref Fig 1 of http://www.nature.com/nrm/journal/v7/n7/full/nrm1961.html)

Furthermore, during the assembly of the vertebrate Box H/ACA telomerase RNP complex, the proteins dyskerin, NOP10, NHP2 and NAF1 initially associate with TERC, then NAF1 is replaced with GAR1 in the Cajal body. So in answer to your other points (suggested changes to definitions in capital letters, sorry can't seem to get bold to work):

1. Create one new child term of GO:0072588 Box H/ACA RNP complex:
Box H/ACA telomerase RNP complex
A box H/ACA ribonucleoprotein complex that contains the RNA component of VERTEBRATE telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell. INITIALLY THIS RNP COMPLEX CONSISTS OF THE TELOMERASE RNA ASSOCIATED WITH THE PROTEINS DYSKERIN, NOP10, NHP2 AND NAF1. THE PROTEIN NAF1 IS REPLACED WITH GAR1 DURING THE BIOGENESIS OF THE TELOMERASE HOLOENZYME. 

2. Update definition of GO:0072588 Box H/ACA RNP complex:
A ribonucleoprotein complex that contains an RNA of the box H/ACA type AND THE FOUR CORE PROTEINS DYSKERIN, NOP10, NHP2 AND GAR1. RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity. These include the VERTEBRATE telomerase RNP complex.

4.GO:NEW Box H/ACA telomerase RNP complex
capable_of_part_of GO:0032212 positive regulation of telomere maintenance via telomerase
what about part_of GO:0005697 telomerase holoenzyme complex? 

Yes GO:NEW Box H/ACA telomerase RNP complex could also be part_of GO:0005697 telomerase holoenzyme complex if we are referring to the final version in which GAR1 is present (as stated above although NAF1 is part of the initial telomerase RNP complex, it isn't present in the telomerase holoenzyme), is changing the definition of GO:NEW Box H/ACA telomerase RNP complex as suggested above the best way to do this? 

Jess

**Comment by JessBuxton** [comment]
Hi again,

regarding points 1 and 4 in my previous message, about whether GO:NEW Box H/ACA telomerase RNP complex could also be part_of GO:0005697 telomerase holoenzyme complex - on reflection I think I'm overcomplicating things - I guess provided that the GO:NEW Box H/ACA telomerase RNP complex term is only used to annotate the core proteins found in the mature RNP complex (ie. dyskerin, NOP10, NHP2 and GAR1) then it will be fine to have this link to the new term, using the shorter suggested definition below:

GO:NEW Box H/ACA telomerase RNP complex
A box H/ACA ribonucleoprotein complex that contains the RNA component of VERTEBRATE telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell.

**Comment by tberardini** [comment]
Would one annotate NAF1 to the 'BOX H/ACA telomerase RNP complex' term?  I don't like the definition that states that the complex has ABCD at one point in time and ABCE at another.  Perhaps we need two terms, one for the complex with the NAF1  component and one with the GAR1 component.

**Comment by JessBuxton** [comment]
I agree - i think the definition of the new term should just be as below, and only dyskerin, NOP10, NHP2 and GAR1 should be annotated to it. Not NAF1, as this is strictly speaking an 'assembly factor' rather than a final component of the complex.

GO:NEW Box H/ACA telomerase RNP complex
A box H/ACA ribonucleoprotein complex that contains the RNA component of VERTEBRATE telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell.

**Comment by tberardini** [comment]
Ok, finally done.  Thanks, everyone, for your help.

**Comment by bmeldal** [comment]
Oh, well done, everyone!

Birgit

**Comment by JessBuxton** [comment]
Thanks very much!
