### ISSUE TITLE
refine F-P link cation transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12044]
could you remove the redundant F-P link from

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008324#term=ancchart

GO:0008324 cation transmembrane transporter activity
to
cation transport

It also has 
cation transmembrane transporter which is better.

I'm picking up an additional redundant annotation to "cation transport"
which is in  the PomBase "do not annotate" file

This is the final transport one of these!

**Comment by tberardini** [comment]
Done.

-relationship: part_of GO:0006812 ! cation transport
