### ISSUE TITLE
possible NTR - child term to microautophagy, "Endosomal microautophagy"

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12053]
PMID: 21238931
suggests a child term to microautophagy,

Endosomal microautophagy:
"we provide evidence that a microautophagy-like process occurs during multivesicular bodies (MVB) biogenesis to deliver selected soluble cytosolic proteins to the vesicles of late endosomes  (LE) / MVBs"

**Comment by Pauldenny** [comment]
On re-reading this paper, I'm not sure whether this is a child of GO:0016237 microautophagy, because authors talk about "microautophagy-like" and their end-point is the LE vesicles during MVB biogenesis and they don't show that the cargo proteins go into the lysosome - therefore this doesn't fit the definition for GO:0016237 microautophagy "...transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane..."

**Comment by Pauldenny** [comment]
I'm  not sure if this a child process - because part of definition of microautophagy is "...transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane...".  Authors show that cargo is delivered to late endosome (LE), not to lysosome.  So this might actually be a sibling process, instead of a child?

**Comment by ukemi** [comment]
How about two sibling microautophagy terms?

lysosomal autophagy (existing term and def)----The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. In S. cerevisiae, the vacuole is the lysosomal compartment.

late endosomal microphagy- The autophagy process by which cytosolic proteins targeted for degradation are tagged with a chaperone and are directly transferred into and degraded in a late endosomal compartment. PMID:21238931

Note, we should also check all mammalian annotations to the existing microautophagy term. According to this article it does not happen. Should we consider adding a taxon restriction only_in fungi to the existing term?

**Comment by ukemi** [comment]
[Term]
 id: GO:0016237
-name: microautophagy
+name: lysosomal microautophagy
 namespace: biological_process
 def: "The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. In S. cerevisiae, the vacuole is the lysosomal compartment." [PMID:14679207, PMID:15798367, PMID:16973210, PMID:9566964]
 is_a: GO:0006914 ! autophagy
@@ -249658,7 +249657,7 @@
 namespace: biological_process
 def: "Degradation of a cell nucleus by microautophagy." [GOC:jp, PMID:18701704]
 synonym: "PMN" EXACT []
-is_a: GO:0016237 ! microautophagy
+is_a: GO:0016237 ! lysosomal microautophagy
 is_a: GO:0044804 ! nucleophagy
 
 [Term]
@@ -423130,6 +423129,15 @@
 creation_date: 2015-09-15T12:58:21Z
 
 [Term]
+id: GO:0061738
+name: late endosomal microphagy
+namespace: biological_process
+def: "The autophagy process by which cytosolic proteins targeted for degradation are tagged with a chaperone and are directly transferred into and degraded in a late endosomal compartment." [GOC:autophagy, GOC:dph, PMID:21238931]
+is_a: GO:0006914 ! autophagy
+created_by: dph
+creation_date: 2015-09-24T14:40:02Z

**Comment by Pauldenny** [comment]
Hi David - is there a typo in this ?should

+name: late endosomal microphagy

Be
+name: late endosomal microautophagy
?
Best,
Paul Denny

On 24 Sep 2015, at 19:43, ukemi <notifications@github.com<mailto:notifications@github.com>> wrote:


[Term]
id: GO:0016237
-name: microautophagy
+name: lysosomal microautophagy
namespace: biological_process
def: "The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. In S. cerevisiae, the vacuole is the lysosomal compartment." [PMID:14679207, PMID:15798367, PMID:16973210, PMID:9566964]
is_a: GO:0006914 ! autophagy
@@ -249658,7 +249657,7 @@
namespace: biological_process
def: "Degradation of a cell nucleus by microautophagy." [GOC:jp, PMID:18701704]
synonym: "PMN" EXACT []
-is_a: GO:0016237 ! microautophagy
+is_a: GO:0016237 ! lysosomal microautophagy
is_a: GO:0044804 ! nucleophagy

[Term]
@@ -423130,6 +423129,15 @@
creation_date: 2015-09-15T12:58:21Z

[Term]
+id: GO:0061738
+name: late endosomal microphagy
+namespace: biological_process
+def: "The autophagy process by which cytosolic proteins targeted for degradation are tagged with a chaperone and are directly transferred into and degraded in a late endosomal compartment." [GOC:autophagy, GOC:dph, PMID:21238931]
+is_a: GO:0006914 ! autophagy
+created_by: dph
+creation_date: 2015-09-24T14:40:02Z

-

**Comment by ukemi** [comment]
AHHHHHHHH! Yes. I will fix that immediately. Thanks for spotting.

-D

**Comment by Pauldenny** [comment]
May have to make 
GO:0061738
+name: late endosomal microautophagy
no longer a is_a type of autophagy, if we define the end point of autophagy *always* occurring in the lysosome, because PMID:21238931 describes the degradation step of late endosomal microautophagy occurring in the late endosome e.g. see Figures 1B, 1L and 2H. Also, in the last paragraph of the discussion.
Perhaps we should consider it as using the some of the same machinery, but distinct from, autophagy?

**Comment by ukemi** [comment]
Currently there is no endpoint process or location of autophagy defined. So I think this is ok, don't you?

The process in which cells digest parts of their own cytoplasm; allows for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure for cell differentiation.

autophagy is_a cellular process
autophagy has_part cellular catabolic process

**Comment by Pauldenny** [comment]
Agreed - I see the point.
Thanks David
