### ISSUE TITLE
MP GO:0019430 - removal of superoxide radicals

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12051]
could
GO:0019430 - removal of superoxide radicals
have the ancestor
"cellular detoxification"?
I can't think of why not....

**Comment by tberardini** [comment]
Makes sense to me.  Added the link.

I also cleaned up the cellular detoxification (CD) terms but adding missing parentage for CD of hydrogen peroxide and CD of nitrogen compound under CD.
