### ISSUE TITLE
Regulation of somatic stem cell maintenance

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12054]
Hi,

I'm wondering whether it would be possible to have regulation terms for somatic stem cell maintenance (GO:0035019). This term is a child of negative regulation of cell differentiation, so would it cause problems to have regulation of regulation? (there are already terms for regulation of stem cell maintenance, so maybe not).

Also, I notice there is no link between GO:0017145 stem cell division and GO:0019827 stem cell maintenance. Wouldn't you expect division to be part of maintenance?

Thanks,
Rachael.

**Comment by tberardini** [comment]
@ukemi, @paolaroncaglia, @dosumis - Thoughts on the 'regulation of regulation' aspect?

**Comment by cmungall** [comment]
Double regulation is fine, but is that really what is happening here? 
Can we point to two distinct regulatory points?

**Comment by rachhuntley** [comment]
I'll explain what I'm trying to annotate.
It's this paper http://www.sciencedirect.com/science/article/pii/S0092867409002529

miRNA-145 is silencing the transcription factors OCT4, SOX2 and KLF4 and as a result of this embryonic stem cell renewal is inhibited and they undergo differentiation. If miR-145 is lost, the ESC do not differentiate and the transcription factor levels increase. The TFs have been shown to be necessary for ESC self-renewal (negatively regulate differentiation) and the miR is negatively regulating the expression of the TFs.

The authors conclude "These results indicate that the miR-145 upregulation disrupts the maintenance of the self-renewal of hESCs, which suggests that miR-145 is a critical negative regulator of self-renewal."

However, in Fig. 4 they show miR-145 reduces the number of cells entering S-phase and reduces colony formation, so maybe it should be negative regulation of somatic stem cell division? But stem cell division is not linked to stem cell maintenance, so I'd want to use both.

**Comment by tberardini** [comment]
Given the definitions of stem cell division (SCD) and stem cell maintenance (SCM, should really be stem cell population maintenance, I think), it's reasonable to link SCD by part_of to SCM.

**Comment by ukemi** [comment]
I think all of the cell maintenance terms actually refer to a population.

**Comment by rachhuntley** [comment]
OK, so if there is an agreement to relate SCD to SCM, I will go ahead and request the regulation terms of SCD from TermGenie.

**Comment by ukemi** [comment]
Thinking more about this (perhaps too much), it seems that stem cell division could also occur in the initial expansion phase of a population of stem cells, so it is not necessarily a part_of the maintenance of the population. It also might be tricky to make a has_part relation to stem cell division. It is the nature of a stem cell to be able to divide indefinitely and give rise to at least one more stem cell at every division. Classically this is the difference between a stem cell and a progenitor cell, although that distinction has become fuzzy. But, a population of stem cells can be maintained by the division of an existing stem cell to yield a cell that will leave the stem cell niche and differentiate and a second cell that will remain in the niche as a stem cell. The cell that remains is maintained as a stem cell either by a suppression of differentiation to another fate or specification of a stem cell fate depending on how you view it. So I'm not sure we can make a connection between stem cell maintenance and division.

**Comment by rachhuntley** [comment]
OK, makes sense. In that case I would want to annotate to both regulation of SCD and regulation of SCM.
Can I go ahead and make the reguation terms for stem cell maintenance in TermGenie as well, which was the original issue?

Thanks.

**Comment by tberardini** [comment]
Yes, Rachael, go ahead and request.  

@ukemi - do you think it would be beneficial to add the word 'population' into the term names (or '[x] stem cell population maintenance') for 'stem cell maintenance' and its is_a children? If yes, I can do that before closing out this issue.

**Comment by ukemi** [comment]
It might make it clearer. It looks like there are also some path issues with this term being children of processes that can all contribute to the maintenance of the population, but act at the level of a single cell. These should probably be rethought. In my opinion the stem cell development and negative regulation of cell differentiation parent should be removed. It would be better to make a term negative regulation of differentiation involved in stem cell maintenance as a part of the process to which some of the well-known genes above could be annotated. Sorry to open a can of worms.

**Comment by tberardini** [comment]
Thanks for your input, David.  Very helpful.

Added 'population' to the terms when appropriate.
Removed 'stem cell development ' and 'neg reg of cell diff' parents of SCPM. Agreed, these were not appropriate.

Rachael -  I went ahead and made this term for you:

[Term]
id: GO:1904671
name: negative regulation of cell differentiation involved in stem cell population maintenance
namespace: biological_process
def: "Any negative regulation of cell differentiation that is involved in stem cell population maintenance." [GO_REF:0000060, GOC:BHF_miRNA, GOC:rph, GOC:TermGenie, PMID:19409607]
synonym: "down regulation of cell differentiation involved in maintenance of pluripotency" RELATED [GOC:TermGenie]
synonym: "down regulation of cell differentiation involved in stem cell population maintenance" EXACT [GOC:TermGenie]
synonym: "down-regulation of cell differentiation involved in maintenance of pluripotency" RELATED [GOC:TermGenie]
synonym: "down-regulation of cell differentiation involved in stem cell population maintenance" EXACT [GOC:TermGenie]
synonym: "downregulation of cell differentiation involved in maintenance of pluripotency" RELATED [GOC:TermGenie]
synonym: "downregulation of cell differentiation involved in stem cell population maintenance" EXACT [GOC:TermGenie]
synonym: "inhibition of cell differentiation involved in maintenance of pluripotency" RELATED [GOC:TermGenie]
synonym: "inhibition of cell differentiation involved in stem cell population maintenance" NARROW [GOC:TermGenie]
synonym: "negative regulation of cell differentiation involved in maintenance of pluripotency" RELATED [GOC:TermGenie]
is_a: GO:0045596 {is_inferred="true"} ! negative regulation of cell differentiation
intersection_of: GO:0045596 ! negative regulation of cell differentiation
intersection_of: part_of GO:0019827 ! stem cell population maintenance
relationship: part_of GO:0019827 {is_inferred="true"} ! stem cell population maintenance
created_by: tb
creation_date: 2015-09-12T00:46:08Z


If you need the term specifically for somatic stem cell population maintenance, please request that through TG.
