### ISSUE TITLE
NTR: cerebrospinal fluid circulation

### ISSUE THREAD

**Issue by cindyJax** [geneontology/go-ontology#12056]
Suggested new term label:
cerebrospinal fluid circulation

Suggested Def (Written by MGI:Anna):
The dynamic process by which CSF circulates from the sites of secretion to the sites of absorption according to a unidirectional rostrocaudal flow in ventricular cavities and a multidirectional flow in subarachnoid spaces.

More description if warranted:
CSF produced by the choroid plexuses in the lateral ventricles travels through interventricular foramina to the third ventricle, and then the fourth ventricle via the cerebral aqueduct and finally to the subarachnoid spaces via the median aperture (foramen of Magendie) of the fourth ventricle. In the cranial subarachnoid space, CSF circulates rostrally to the villous sites of absorption or caudally to the spinal subarachnoid space. CSF circulation through the ventricular system is driven by motile cilia on ependymal cells of the brain. CSF flow is pulsatile, corresponding to the systolic pulse wave in choroidal arteries. Additional factors such as respiratory waves, the subject's posture, jugular venous pressure and physical effort also modulate CSF flow dynamics and pressure.

DEF SOURCES:

http://www.sciencedirect.com/science/article/pii/S1879729611001013

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3848805/

Synonyms:
cerebrospinal fluid flow
CSF circulation
CSF flow

See also https://github.com/obophenotype/mammalian-phenotype-ontology/issues/2101

**Comment by tberardini** [comment]
@ukemi

**Comment by tberardini** [comment]
Suggested is_a parent: neurological system process, GO:0050877
Modified def: The neurological system process driven by motile cilia on ependymal cells of the brain by which cerebrospinal fluid circulates from the sites of secretion to the sites of absorption.  In ventricular cavities, the flow is unidirectional and rostrocaudal, in subarachnoid spaces, the flow is multidirectional.

**Comment by ukemi** [comment]
has_part  cilium movement (GO:0003341)?

**Comment by ukemi** [comment]
or even better, since an ependymal cell (CL:0000065) is an epithelial cell (CL:0000066)

has_part epithelial cilium movement (GO:0003351)

**Comment by tberardini** [comment]
Very nice.  

has_part epithelial cilium movement (GO:0003351)
Thanks, David.

**Comment by cmungall** [comment]
yep, connection to cilia important!

**Comment by tberardini** [comment]
Added: 

+id: GO:0090660
+name: cerebrospinal fluid circulation
+namespace: biological_process
+def: "The neurological system process driven by motile cilia on ependymal cells of the brain by which cerebrospinal fluid circulates from the sites of secretion to the sites of absorption. In ventricular cavities, the flow is unidirectional and rostrocaudal, in subarachnoid spaces, the flow is multidirectional." [GOC:mgi_curators, PMID:22100360, PMID:24229449]
+synonym: "cerebrospinal fluid flow" EXACT []
+synonym: "CSF circulation" EXACT []
+synonym: "CSF flow" EXACT []
+is_a: GO:0050877 ! neurological system process
+relationship: has_part GO:0003351 ! epithelial cilium movement
