### ISSUE TITLE
MP: mRNA cleavage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12052]
mRNA cleavage appears to be missing ancestry  to mRNA metabolic process?

Val

**Comment by tberardini** [comment]
Yes, was missing.  I've added it.  Thanks.

**Comment by rachhuntley** [comment]
Hi Val, Tanya,

This was brought up in a previous ticket https://github.com/geneontology/go-ontology/issues/11894 (and another linked from that) and I think the decision was that Val was going to annotate instead to GO:0098787 mRNA cleavage involved in mRNA processing.

Rachael.

**Comment by ValWood** [comment]
Hi Rachel,

I followed the old threads back, and I'm still confused.

So when cleavage occurs isn't it *always* processing? Even when cleavage occurs as part of silincing it is still processing isn't it? If so the problem lies with the current definition of  mRNA processing as 

Any process involved in the conversion of a primary mRNA transcript into one or more mature mRNA(s) prior to translation into polypeptide.

It seems clear now,that "processing" shouldn't be restricted to the production of mature molecules, and includes production or si/miRNAs so the def of processing needs broadening, and then the  specific instances can be established.

I'm sure that @dosumis will agree that it does not make ontological sense that 
GO:0098787 mRNA cleavage involved in mRNA processing
is not part of "mRNA processing", the process it is "involved in"!

Whatever the solution, mRNA metabolism should also  be part of the ancestry.

Val

**Comment by rachhuntley** [comment]
Yes, I thought David had added the link to mRNA processing, but it seems to have gone to RNA processing.

I'll leave David to answer whether the processing definition should be broadened as he did a lot of work on this previously.

**Comment by ValWood** [comment]
yeah something looks a bit funny...

**Comment by tberardini** [comment]
@dosumis , I'm reopening and reassigning to you.  Can you please comment/edit the ontology wrt to the question on the link between 'mRNA cleavage' or 'mRNA cleavage involved in mRNA processing' and 'mRNA processing'.

The original request to link 'mRNA cleavage' and 'mRNA metabolic process' has been addressed.

**Comment by dosumis** [comment]
Fixed the link to mRNA processing.
