### ISSUE TITLE
NTR for HVC

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#12057]
Term: HVC

Definition: HVC  is a nucleus in the brain of songbirds located in the caudal nidopallium, projecting to the song motor pathway via the robust nucleus of the arcopallium and to the Anterior Forebrain Pathway via the basal ganglia nucleus Area X.
 https://en.wikipedia.org/wiki/HVC_(avian_brain_region)

formally called  hyperstriatum ventrale, pars caudalis (HVc) and high vocal center

only in Passeriformes Taxon ID: 9126

GOC:mr

**Comment by cmungall** [comment]
Hi Michael

This is in the GO tracker. Do you need a developmental process term? Either way we should add the brain structure to Uberon. Are you likely to need other avian structures in the future?

**Comment by tberardini** [comment]
Yes, this 'nucleus' is an anatomical structure, not suited for GO.  

Uberon github tracker: https://github.com/obophenotype/uberon/issues

Please close this issue if you do not require a GO term.  Thanks.

**Comment by michaelerice** [comment]
?Thanks Chris,


I do not need a process term at this time, and I am not sure if I will need other avian structures in the future. If you would like to put a hold on this until I can compile a possible list of structure that is ok for me.


Mike


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by tberardini** [comment]
I'll transfer your request to the Uberon tracker.

https://github.com/obophenotype/uberon/issues/1145

Closing this one.  Please open a new issue when you do need a GO process term.  Thanks.

**Comment by michaelerice** [comment]
?Thank you


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________
