### ISSUE TITLE
new term Bacterial extracellular vesicle

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#12058]
Hi,

I'm a UniProtKB/Swiss-Prot annotator. I'd like a new Cellular component term, Bacterial extracellular vesicle, as a child of GO:1903561 (extracellular vesicle) please. You already have GO:0061701 (outer membrane vesicle), which is bacteria specific, although the name doesn't say that. Gram-positive bacteria also generate extracellular vesicles from their plasma membranes. See PMID 25704309 for a recent review.
This is the definition I'd like to use in UniProt:
Small membrane vesicle (< 1 um) that buds off a prokaryotic cell's plasmid membrane, able to carry proteins, phospholipids, lipopolysaccharides, nucleic acids, viruses, etc. Bacterial extracellular vesicles are important in intercellular communication and pathogenesis, and can exist within host cells.                 
Thanks, Andrea

**Comment by paolaroncaglia** [comment]
@dosumis - I'm taking this request as vesicle-related.

@AndreaAuchincloss - FYI, I'm working on an ontology development project on extracellular vesicles. Mostly eukaryotic, but I'd like to make sure there is consistency across the branch.

**Comment by AndreaAuchincloss** [comment]
consistency across taxonomy would be excellent...

**Comment by AndreaAuchincloss** [comment]
Hi Paola, I know you're busy, but do you have any news on this? I'm ready to submit my annotation and would like to have everything all tied up before I do so. Thanks

**Comment by paolaroncaglia** [comment]
Hi Andrea,

Added new term:

+id: GO:0097691
+name: bacterial extracellular vesicle
+namespace: cellular_component
+def: "Small membrane vesicle (< 1 um) that buds off a prokaryotic cell plasma membrane, able to carry proteins, phospholipids, lipopolysaccharides, nucleic acids, viruses, and more. Important in intercellular communication and pathogenesis; can exist within host cells." [GOC:aa, PMID:25704309]
+is_a: GO:1903561 ! extracellular vesicle
+relationship: only_in_taxon NCBITaxon:2 ! Bacteria <prokaryote>

Also, I also edited the name of GO:0061701 (outer membrane vesicle) to be ‘bacterial outer membrane vesicle’, and added a taxon rule (only in Bacteria).

Thanks for your patience, and for your reminder.

Paola

**Comment by AndreaAuchincloss** [comment]
thanks! This helps me finish up...

Andrea

On 24.09.2015 12:37, paolaroncaglia wrote:
>
> Hi Andrea,
>
> Added new term:
>
> +id: GO:0097691
> +name: bacterial extracellular vesicle
> +namespace: cellular_component
> +def: "Small membrane vesicle (< 1 um) that buds off a prokaryotic 
> cell plasma membrane, able to carry proteins, phospholipids, 
> lipopolysaccharides, nucleic acids, viruses, and more. Important in 
> intercellular communication and pathogenesis; can exist within host 
> cells." [GOC:aa, PMID:25704309]
> +is_a: GO:1903561 ! extracellular vesicle
> +relationship: only_in_taxon NCBITaxon:2 ! Bacteria
>
> Also, I also edited the name of GO:0061701 (outer membrane vesicle) to 
> be ‘bacterial outer membrane vesicle’, and added a taxon rule (only in 
> Bacteria).
>
> Thanks for your patience, and for your reminder.
>
> Paola
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12058#issuecomment-142887090>.Web 
> Bug from 
> https://github.com/notifications/beacon/ANnCA-KmRKHzNARzwvO_-rabAO7RGaGHks5o08nQgaJpZM4F8qXJ.gif
>

-- 
Andrea Auchincloss, PhD
UniProtKB/Swiss-Prot Annotator

SIB Swiss Institute of Bioinformatics
CMU, 1 Michel-Servet
CH-1211 Genève 4
Switzerland
Tel: (+41) 22 379 58 63
FAX: (+41) 22 379 58 58
email: Andrea.Auchincloss@isb-sib.ch
http://www.uniprot.org /
