### ISSUE TITLE
NTR: a child term to "ATP transport"

### ISSUE THREAD

**Issue by jinhuiz** [geneontology/go-ontology#12055]
I would like to suggest a child term "ATP efflux" to "GO:0015867 ATP transport" term.

ATP efflux
Definition: The directed movement of ATP, adenosine triphosphate, out of cell or organelle.
Parent term: is_a GO:0015867 ATP transport
                  
PMID:24286344

thanks,

Jinhui Zhang

**Comment by tberardini** [comment]
Added using TermGenie:

[Term]
id: GO:1904669
name: ATP export
namespace: biological_process
def: "The directed movement of ATP out of a cell or organelle." [GO_REF:0000074, GOC:TermGenie, PMID:24286344]
synonym: "ATP efflux" RELATED []
is_a: GO:0015867 {is_inferred="true"} ! ATP transport
intersection_of: GO:0006810 ! transport
intersection_of: exports CHEBI:15422 ! ATP
relationship: exports CHEBI:15422 {is_inferred="true"} ! ATP
created_by: tb
creation_date: 2015-09-09T16:33:06Z
