### ISSUE TITLE
MP cytoplasmic translational inititation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12059]
based on the parentage of this to "translation initiation"
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1903675#term=ancchart

it seems that the cytoplasmic parents should refer to "cytoplasmic translational initiation"

**Comment by dosumis** [comment]
Sorry.  Not following.  What are you suggesting I should change?

**Comment by ValWood** [comment]
It's subtle, took me a while to respot it!

GO:1903675 negative regulation of cap-dependent translational initiation
has ancestors
negative regulation of cytoplasmic translation
and
and cytoplasmic translational initiation
but not
negative regulation of cytoplasmic translational initiation

**Comment by dosumis** [comment]
We don't have a term for 
"negative regulation of cytoplasmic translational initiation'

- at least not one that I can find.

Will add.

Branch needs more automation.  Terrible spaghetti tangle.
