### ISSUE TITLE
 Query parentage GO:0009225 nucleotide-sugar metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12064]
is this def correct?

GO:0009225 nucleotide-sugar metabolic process
The cellular chemical reactions and pathways involving nucleotide-sugars, any nucleotide in which the distal phosphoric residue of a nucleoside 5'-diphosphate is in glycosidic linkage with a monosaccharide or monosaccharide derivative.

is a nucleotide-sugar really a nucleotide? This doesn't seem to be consistent with how derivatives are notmally treated?

**Comment by ukemi** [comment]
My you have an eye for detail!

Changed this one and the biosynth and catab to:

The cellular chemical reactions and pathways involving nucleotide-sugars, any nucleotide-carbohydrate in which the distal phosphoric residue of a nucleoside 5'-diphosphate is in glycosidic linkage with a monosaccharide or monosaccharide derivative.

**Comment by ValWood** [comment]
I saw this  yesterday because we were getting annotations to nucleotide metabolism via PAINT. I think you maybe fixed the parentage earlier today (removed nucleotide metabolism) via another ticket (#11898) ...
