### ISSUE TITLE
leukotriene related terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12066]
Previously we used these  terms at SGD and  PomBase.

http://www.ebi.ac.uk/QuickGO/GSearch?q=leukotriene

Can taxon restriction be added? I don't know what it should be taxonomically, but only  anything which has leukocytes.

https://en.wikipedia.org/wiki/Leukotriene

v

**Comment by cmungall** [comment]
Are we sure the chemical restricted to leukocytes? lipoxygenases seem 
widespread across eukaryotes, as does arachidonic acid. If we have some 
kind of evidence like a review paper we can add.

**Comment by ValWood** [comment]
I was only going by this
https://en.wikipedia.org/wiki/Leukotriene
soI thought it was some immune specific compound...not sure...

**Comment by ValWood** [comment]
Maybe for now just add the restriction to yeast which will at least prevent any mapping from orthologs from PAINT etc.
Rama also thinks  LTA4 is not made in yeast.
Val

**Comment by rbalakri** [comment]
Hi,
Yes, please add the taxon restriction for this term for yeast.
Thanks,
Rama

**Comment by dosumis** [comment]
Should probably add a comment along with the restriction, to make assumptions clear.

**Comment by rbalakri** [comment]
Lifted off the Wikipedia. 
https://en.wikipedia.org/wiki/Leukotriene
Leukotrienes are a family of eicosanoid inflammatory mediators produced in leukocytes by the oxidation of arachidonic acid by the enzyme arachidonate 5-lipoxygenase. 
So far there is no evidence for the production of leukotrine in yeast.

Does this work?
R

**Comment by dosumis** [comment]
Added never in taxon fungi to the 2 grouping classes: 'leukotriene signalling pathway' and 'leukotriene metabolic process'
