### ISSUE TITLE
Expanding definition of 'retromer complex ; GO:0030904'

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12063]
I plan to extend the definition of 3 retromer terms to include mammalian components. Adding it to Github as a reminder and in case of any comments from e.g. @bmeldal

retromer complex ; GO:0030904
retromer complex, outer shell ; GO:0030905
retromer complex, inner shell ; GO:0030906

retromer complex ; GO:0030904
From:
A conserved multimeric membrane-associated complex involved in retrograde transport from endosomes to the Golgi apparatus. For example, the budding yeast retromer comprises Vps35p, Vps29p, Vps26p, Vps5p, and Vps17p.
To:
A conserved heteropentameric membrane-associated complex involved in retrograde transport from endosomes to the Golgi apparatus. The budding yeast retromer comprises Vps35p, Vps29p, Vps26p, Vps5p, and Vps17p. The mammalian complex shows slight variation in composition compared to yeast, and comprises SNX1 or SNX2, SNX5 or SNX6, VPS26A or VPS26B, VPS29, and VPS35.
[PMID 26220253]

retromer complex, outer shell ; GO:0030905
One of two subcomplexes that combine to form the retromer, believed to be peripherally associated with the membrane. The budding yeast complex comprises Vps5p and Vps17p, and may contain multiple copies of a Vps5p/Vps17p dimer.
to:
The dimeric subcomplex of the retromer, believed to be peripherally associated with the membrane. This dimeric complex is responsible for remodelling endosomal membranes to form a tube-structure to which cargo molecules are selected for recycling. The budding yeast complex comprises Vps5p and Vps17p, and may contain multiple copies of a Vps5p/Vps17p dimer. The mammalian complex contains 
SNX1 or SNX2 dimerized with SNX5 or SNX6. [PMID 26220253]
Exact synonym: SNX-BAR dimer [PMID 26220253]
Exact synonym: retromer tubulation complex [PMID 26220253]
Exact synonym: heterodimeric membrane-deforming retromer subcomplex [22193161, GOC:bf]
capable_of_part_of: membrane organisation ; GO:0061024

retromer complex, inner shell ; GO:0030906
From:
One of two subcomplexes that combine to form the retromer, believed to be closely associated with the membrane. In budding yeast the complex comprises Vps35p, Vps29p, and Vps26p.
To:
The trimeric subcomplex of the retromer, believed to be closely associated with the membrane. This trimeric complex is responsible for recognising and binding to cargo molecules. The complex comprises three Vps proteins in both yeast and mammalian cells: Vps35p, Vps29p, and Vps26p in yeast, and VPS35, VPS29 and VPS26A or VPS26B in mammals [PMID 11102511, PMID 26220253]
Exact synonym: retromer, cargo recognition complex [PMID: 26220253, GOC:bf]
Exact synonym: retromer, CRC [PMID: 26220253, GOC:bf]
Exact synonym: cargo-selective retromer subcomplex  [PMID:19531583, 20923837]
Exact synonym: retromer CSC [GOC:bf]

I'd like to rename the inner and outer shell terms to terms more commonly used in the literature:
retromer complex, outer shell ; GO:0030905
>
retromer tubulation complex ; GO:0030905

retromer complex, inner shell ; GO:0030906
>
retromer cargo-selective complex ; GO:0030906

Thanks!

**Comment by bmeldal** [comment]
In principle I think it works, as long as the 2:3 ratio is conserved. We want to avoid giving composition for all MODs but human and S.c. is probably a good compromise ;-)

Sorry, it almost (!) slipped through the net!

Birgit

**Comment by rebeccafoulger** [comment]
Thanks for the check Birgit! Done edits as described above, including renaming the sub complexes.
