### ISSUE TITLE
parentage of 'response to fluoxetine'

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12067]
Consider making "response to antidepressant" (GO:0036276) an additional parent of "response to fluoxetine" (GO:0014076).  Thanks.

**Comment by cmungall** [comment]
We should be getting this automatically

**Comment by slaulederkind** [comment]
Just a reminder to look at this request.  Thanks.

**Comment by dosumis** [comment]
Added manually.

But for the record: I have serious reservations about terms like this.  GO is meant to record normal activity.  Nothing evolved to respond to Fluoxetine. The normal process affected is serotonin re-uptake.  The responses are downstream effects of the resulting increased serotonin signalling.
