### ISSUE TITLE
MP 2-hexaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12065]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0043334
2-hexaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
Catalysis of the reaction: 2-hexaprenyl-6-methoxy-1,4-benzoquinone + S-adenosyl-L-methionine = 2-hexaprenyl-3-methyl-6-methoxy-1,4-benzoquinone + S-adenosyl-L-homocysteine. 

should have	GO:0008757	in parentage?

**Comment by dosumis** [comment]
Agree.  Have made it a parent to a superclass of GO:0043334:

GO_0030580
label "quinone cofactor methyltransferase activity"^^string
definition "Catalysis of the transfer of a methyl group from S-adenosylmethionine during the synthesis of quinone cofactors such as ubiquinone (coenzyme Q), menaquinone (vitamin K2), plastoquinone and phylloquinone (vitamin K1)."^^string
