### ISSUE TITLE
NTR: double-stranded miRNA binding

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12061]
Hi,
Could I please request a new term for 'double-stranded miRNA binding' (synonym miRNA duplex binding) as a child of GO:0003725 double-stranded RNA binding.

This is to annotate argonaute proteins that bind miRNA duplexes after they have been processed from pre-miRNA stem-loop structures (which is described by the term GO:0070883 pre-miRNA binding) and before further processing to single-stranded mature miRNAs (which is described by the term GO:0035198 miRNA binding). See PMID:19966796.

Could you please add GOC:rph, GPC:BHF and GOC:BHF_miRNA as references?

Thanks,
Rachael.

**Comment by dosumis** [comment]
Added:
GO_0098851
label "double-stranded miRNA binding"@en
definition "Interacting selectively and non-covalently with double-stranded miRNA. double-stranded miRNA is formed by processing of pre-miRNA stem-loop structures."
has_exact_synonym "miRNA duplex binding" [PMID:19966796, GOC:rph, GOC:BHF, GOC:BHF_miRNA
