### ISSUE TITLE
GO:0008282 ATP-sensitive potassium channel complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12071]
Please correct the def to:

A protein complex that comprises four pore-forming (Kir6.x) and four regulatory sulphonylurea receptor (SURx) subunits and forms a transmembrane channel through which ions may pass. The opening and closing of the channel is regulated by ATP: binding of ATP to the Kir6.x subunit inhibits channel activity, whereas binding of Mg2+-complexed ATP or ADP to the SURx subunit stimulates channel activity.

Replaces SUR1 with SURx to be valid for all isoforms.

Thanks,
Birgit

**Comment by paolaroncaglia** [comment]
Done.
Thanks
Paola
