### ISSUE TITLE
query old unused term related to spindle orientation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12076]
Hi David,
@ukemi  I think you should kill
"establishment of mitotic spindle orientation involved in growth plate cartilage chondrocyte division"
(no annotations).

If I understand the biology, the spindle does have a role in signalling cytokinesis generally (via the signalling pathway known as the septation initiation network in fungi).

This seems like it is connecting an upstream process to a downstream process without the intermediate processes (via phenotype observations).

correct spindle orientation established-> spindle orientation checkpoint OK -> signalling allows chromosome segregation occurs and cell division to occur.

if somebody were curating this they would probably create a more precise process term to describe the cell level processes with the cell type as an extension?

v

**Comment by ukemi** [comment]
I think you are correct about using the extension for the cell type. I think it is still a useful term and would like to change it to 'establishment of mitotic spindle orientation involved in bone morphogenesis'. Based on the definition, this is the way that the planar polarity is maintained in a growing bone.

**Comment by ValWood** [comment]
Ah Ok> I was under the impression that the setting up of asymettry was another role of the SPB (or MTOC/centrosome)  to do with localization of certain proteins asymetrically to the old or new SPB. I didn't realise it was connected to spindle orientation.

**Comment by ukemi** [comment]
So now knowing that this refers to the orientation of the division plane to maintain planar polarity, do you think this term is ok. It will always be used for this cell type even if I change it to the morphogenesis term. I think what people will be most interested in is the signaling that controls it.

**Comment by ValWood** [comment]
I'm sure its fine, I think I just don't know much about it because pombe always divides medially in WT. It makes sense.
Val

**Comment by ukemi** [comment]
Thanks Val.
