### ISSUE TITLE
ntr: Ubp3–Bre5 deubiquitination complex

### ISSUE THREAD

**Issue by rbalakri** [geneontology/go-ontology#12074]
Hi,

I would like a new term in the Component Ontology.
Term: Ubp3–Bre5 deubiquitination complex
PMID:12778054, PMID: 18391941
A protein complex that is that cleaves ubiquitin from specific substrates. In the budding yeast Saccharomyces cerevisiae, this complex consists of Ubp3p and Bre5p.
is_a: protein complex
synonym: Ubp3–Bre5 ubiquitin protease complex

Thanks,
Rama
(ps: Term genie free form won't let me have hyphen in the term name)

**Comment by paolaroncaglia** [comment]
Hi Rama,

Before I add your term manually, I'm pinging Heiko @hdietze to look into this TermGenie error:

The label 'Ubp3–Bre5 deubiquitination complex' contains a non-ASCII character: '–'

I don't recall we applied this limitation in the past? Though my memory can't be trusted all the time ;-)

Thanks,
Paola

**Comment by bmeldal** [comment]
The 'hyphen'-thing in the name is not an ASCII character, it's what a word processor makes out of '-' :( If you delete the 'thing' you pasted in and re-write with the simple hyphen it should work :)

**Comment by paolaroncaglia** [comment]
Thanks Birgit. Rama, could you please try that?

**Comment by rbalakri** [comment]
Yeap, that worked. I am closing this item.

R
