### ISSUE TITLE
ntr: Pho85-Pho80 CDK-cyclin complex

### ISSUE THREAD

**Issue by rbalakri** [geneontology/go-ontology#12075]
Hi,
term name: Pho85-Pho80 CDK-cyclin complex
PMID: 8108735
Definition: A cyclin dependent kinase (CDK) complex that contains a kinase subunit and a regulatory cyclin subunit. An example of this complex in budding yeast S. cerevisiae consists of the Pho85 kinase and the Pho80 cyclin. 
is_a: GO:0000307

Thanks,
Rama

**Comment by paolaroncaglia** [comment]
@hdietze , presumably same TG issue as reported in

https://github.com/geneontology/go-ontology/issues/12074

Thanks,
Paola

**Comment by bmeldal** [comment]
This one looks like a proper hyphen and I have used them in TG...

**Comment by paolaroncaglia** [comment]
Yes, I'm sure I've seen hyphens in TG terms before! Rama, could you please try again, maybe typing the hyphen in rather than copying. Thanks.

**Comment by hdietze** [comment]
May be unrelated, please also remove the white space from the PMID. Thank you.

**Comment by rbalakri** [comment]
Yes, that worked. Closing this item.

Rama
