### ISSUE TITLE
 suitable reference for GO:0000424	micromitophagy ?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12079]
GO:0000424	micromitophagy is defined : "Degradation of a mitochondrion by microautophagy".
Definition for the parent term, GO:0016237 microautophagy, includes this:
"The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome" - but this process is not described in the reference used for GO:0000424	micromitophagy, PMID:15798367. Furthermore, in this review, it's stated "old mitochondria disappear by a process of autophagy whereby membranes of endoplasmic reticulum sequester individual mitochondria and deliver them to lysosomes for degradation" - this does not fit with a direct lysosome-mitochondrion interaction. 
The only use of the word "micromitophagy" in PUBMED is in two papers - both reviews - one, (PMID:25009776) states:
"Micromitophagy is well characterized in yeast but differs from micromitophagy (Type 3 mitophagy) in mammalian cells in that digestive vacuoles (lysosomes) of yeast engulf whole mitochondria, whereas multivesicular bodies of mammalian cells swallow up small mitochondrial MDV [mitochondria-derived vesicle] fragments".
The yeast case sounds like the definition for the parent term, but the mammalian case sounds quite different.  NOt sure if this means we need taxon constraint for GO:0000424	micromitophagy ?
I need to talk with experts. Perhaps we should save this for next teleconference.

**Comment by ukemi** [comment]
Hi Paul,

It looks like the microautophagic route can exist in mammals as well, see PMID:27003723 . Maybe the best route is to rename GO:0000424 'microautophagy of mitochondrion' and have a broad synonym as micromitophagy. The other pathway sounds more like a MVB pathway to me. What do you think?

-D

**Comment by Pauldenny** [comment]
Hi David,
This sounds like a good idea.  The "other pathway" that is in this review relates to this:
https://github.com/geneontology/go-ontology/issues/12193
Paul

**Comment by ukemi** [comment]
Renaming and added synonym.
