### ISSUE TITLE
IPR001434 mapping

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12073]
Hi,

I don't know if this is the correct forum any more - SourceForge used to have the separate bug tracker for InterPro - GO mappings, but I don't see an InterPro label here.  Please let me know if I need to contact someone else!

The issue I have run across is a GO mapping for Domain of unknown function DUF11 (IPR001434) to GO:0005727 extrachromosomal circular DNA, which I really don't understand at all.  Is it really correct?

Thanks,
Ingrid

Btw, in case anyone knows the right person: the feedback form at http://www.ebi.ac.uk/GOA/contactus doesn't let me submit actual feedback, because it wants a subject line that I don't see a way to add.  That should of course be another bug report, but I don't know how to report it without using the non-working feedback form... :-(

**Comment by ValWood** [comment]
Hi Ingrid, correct tracker. I added an InterPro label, been meaning to do this.
Val

**Comment by paolaroncaglia** [comment]
Hi Ingrid and Val,

Actually, I'm afraid this is not the right tracker... annotation and mapping issues are being collected here:

https://github.com/geneontology/go-annotation/issues

I couldn't find an easy way to move issues from one GitHub tracker to another other than by scripting (see https://opensourcehacker.com/2013/03/11/migrating-and-moving-issues-between-github-issue-trackers/), but I sort of remember that maybe Midori had a quick tip for that? @mah11 

Ingrid, as for the GOA form, the GOA team is aware of that problem and they're chasing it up. In the meantime, they suggest emailing goa@ebi.ac.uk for any pressing issues. Thanks and apologie for the inconvenience!

Paola

**Comment by ValWood** [comment]
Ah sorry. I thought this was the annotation tracker...whoops

**Comment by mah11** [comment]
>  but I sort of remember that maybe Midori had a quick tip for that? ...

I do not. I put a brief summary of what I found when I looked into moving tickets in https://github.com/geneontology/annotation_extensions/issues/51.

**Comment by paolaroncaglia** [comment]
Thanks Val. All things considered, I moved the InterPro request manually to https://github.com/geneontology/go-annotation/issues/1323. Closing this one now.
