### ISSUE TITLE
taxon constraint for GO:0000426 micropexophagy ?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12078]
According to PMID: 15350980
"Redundant, damaged or nonfunctional peroxisomes are degraded by autophagy-related processes [23]. Most mammalian cells, and yeasts with the exception of Pichia pastoris use only macropexophagy 1, 23 and 68. Micropexophagy has been observed in P. pastoris and Aspergillus nidulans."
Furthermore, I could find only three papers that mention "micropexophagy AND mammal" in PUBMED.  All three do not present experimental evidence of micropexophagy in mammals - the words simply co-occur in reviews.
I know that a negative finding may simply mean that there is not yet evidence, but does this suggest that micropexophagy should be used only for fungi / yeast?

**Comment by Pauldenny** [comment]
Also, there are currently NO proteins annotated with GO:0000426 micropexophagy in QuickGO

**Comment by cmungall** [comment]
Thanks for looking into this Paul.

In general I am in favor of erring on the side of strictness and relaxing later if need be. But I'm a little bit uncomfortable here as these classes have such minimal axiomatization. For example

```
[Term]
id: GO:0000426
name: micropexophagy
namespace: biological_process
def: "Degradation of a peroxisome by microautophagy." [PMID:12914914, PMID:16973210]
is_a: GO:0016237 ! microautophagy
is_a: GO:0030242 ! pexophagy
```

If this is really just the combination of two processes, and those two processes exist in taxon T, then why haven't they combined in T? Is there some other mechanism here?

There should at least be equivalence axioms for the *phagy terms.

Looks like these have been in GO for a while (no datestamp on the term)

**Comment by ukemi** [comment]
Hi Chris,

There are two mechanisms involved in the degradation of the peroxisome. We are currently discussing how widespread the process of microautophagy is and where the cutoff of the process would be. Until we figure all of that out, I think it would be premature to create axioms for these terms. Once we have nailed them down, we will see if we can come up with necessary and sufficient conditions.

**Comment by paolaroncaglia** [comment]
Hi,

I restricted GO:0000426 micropexophagy to ‘only in saccharomyceta’ (NCBITaxon:716545) as that’s the furthest ancestor that Pichia pastoris and Aspergillus nidulans have in common, based on the NCBI Taxonomy browser. This is in agreement with the species quoted in the existing supporting references for GO:0000426 micropexophagy (PMID:12914914 = Hansenula polymorpha, while PMID:16973210 is about yeast and mammals but discusses macropexophagy too).

FYI, added dbxrefs:
GOC:autophagy
GOC:pad
PMID:15350980

As for missing annotations to GO:0000426 micropexophagy, Paul is there any that could suggest to SGD based on PMID:15350980?

David, I will assign this ticket back to you so we don’t forget about Chris’ comment on axiomatisation, towards the end of this project.

Thanks,
Paola

**Comment by ukemi** [comment]
I think we can go ahead and close this. We won't forget to add axioms (if we can) once we have defined the limits of the processes. I have started to do it with a few terms already and we will need to do it with every term. If we just leave items open, it will be hard to keep track of why they are open. Thoughts?

**Comment by paolaroncaglia** [comment]
Closing is fine with me - whatever works best :-)

**Comment by Pauldenny** [comment]
Hi Paola - when you say "As for missing annotations to GO:0000426 micropexophagy, Paul is there any that could suggest to SGD based on PMID:15350980?" I assume you are asking if there are any Saccharomyces cerevisiae proteins that could be annotated with GO:0000426 micropexophagy based on evidence in this paper?  If so, I can't see any...  
@paolaroncaglia

**Comment by paolaroncaglia** [comment]
Hi Paul,

yes, that's what I meant - to S. cerevisiae or to other Ascomycetes described in that paper. I was hoping SGD might be interested in annotating gene products from other (related) yeast species for this project. 

Thanks,

Paola
