### ISSUE TITLE
GO:1904564 Nbp35-Cfd1 ATPase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12070]
Something went wrong here when this terms was created. It has 4 children that shouldn't be there. It produces 1000s of wrong IEAs...

Also, the def is not defining this complex from many of it's siblings. We may need an intermediate "ATPase complex" term?

I'm adding this as an example for the working group!

Birgit

**Comment by bmeldal** [comment]
I wonder if this child, GO:0098533 ATPase dependent transmembrane transport complex, should have been the parent, and the is_a relationship got mixed up during editing... Both terms were created/changed at the same time.

**Comment by paolaroncaglia** [comment]
Assigning to David OS to take a look, as he created GO:0098533 and I'm wondering if you did other edits in this sub-branch David? Something looks weird.
@dosumis 
Thanks!
Paola

**Comment by bmeldal** [comment]
Glad I'm not the only one who thinks this looks weird... I think somewhere an is_a relationship got inverted...

**Comment by dosumis** [comment]
'Nbp35-Cfd1 ATPase complex' came through TermGenie and had a dangerously broad equivalent class definition that was causing bad inferences.  I've deleted both the equivalent class expression (noticed this yesterday) and the bad inferences (just now).

**Comment by dosumis** [comment]
@rbalakri - looks like one of yours.   Wondering why you used TG template? (should have come through freeform or ticket)

**Comment by rbalakri** [comment]
I used the template because it is a complex with X activity! 

Rama

**Comment by dosumis** [comment]
Hi Rama,

You should only use the template to define a generic complex with X
activity - not some specific one.  You defined  Nbp35-Cfd1  as 'Any complex
with ATPase activity' - so the reasoner went searching for complexes with
ATPase activity and made them subclasses of Nbp35-Cfd1.

Cheers,
David

**Comment by rbalakri** [comment]
David,

Hah! got it. Sorry about that.

Rama

**Comment by bmeldal** [comment]
In that case, the TG gate keeper could sanity check this... I don't know how obvious it is in your interface.

The template is really handy for some (me!) but it looks like it may trip up some others (Rama!)...

Thanks for fixing this, David.
Birgit

**Comment by dosumis** [comment]
On 24 Sep 2015 07:40, "Birgit" <notifications@github.com> wrote:
>
> In that case, the TG gate keeper could sanity check this... I don't know
how obvious it is in your interface.
>

Should be clear. Must've slipped through by accident.

> The template is really handy for some (me!) but it looks like it may trip
up some others (Rama!)...

**Comment by bmeldal** [comment]
If you are doing it in a hurry it might slip through, but yes, TG does give you a list of inferences and if you have 1000s for a specific complex it should ring alarm bells!
