### ISSUE TITLE
Add equivalence axioms for autphagy classes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12080]
Continued from #12708

Only one subclass of autophagy has a logical def. @dosumis if you suggest a design pattern I can add

 * GO:0000422 ! mitophagy
 * GO:0000423 ! macromitophagy
 * GO:0000424 ! micromitophagy
 * GO:0000425 ! macropexophagy
 * GO:0000426 ! micropexophagy
 * GO:0006914 ! autophagy
 * GO:0016236 ! macroautophagy
 * GO:0016237 ! microautophagy
 * GO:0030242 ! pexophagy
 * GO:0034263 ! autophagy in response to ER overload
 * GO:0034517 ! ribophagy
 * GO:0034727 ! piecemeal microautophagy of nucleus
 * GO:0035695 ! mitophagy by induced vacuole formation
 * GO:0035973 ! aggrephagy
 * GO:0044804 ! nucleophagy
 * GO:0044805 ! late nucleophagy
 * GO:0061684 ! chaperone-mediated autophagy
 * GO:0061709 ! reticulophagy
 * GO:0061723 ! glycophagy
 * GO:0061724 ! lipophagy
 * GO:0061734 ! parkin-mediated mitophagy in response to mitochondrial depolarization
 * GO:0061735 ! dynamin-like protein-mediated mitophagy in response to mitochondrial depolarization
 * GO:0075044 ! autophagy of host cells involved in interaction with symbiont
 * GO:0075071 ! autophagy involved in symbiotic interaction [XP: 'autophagy'[GO:0006914] that part of ( 'symbiosis, encompassing mutualism through parasitism'[GO:0044403] )]
 * GO:0075072 ! autophagy of symbiont cells involved in interaction with host
 * GO:0075073 ! autophagy of symbiont cells on or near host surface
 * GO:0075074 ! spore autophagy involved in appressorium formation on or near host
 * GO:0075191 ! autophagy of host cells on or near symbiont surface
 * GO:0098779 ! mitophagy in response to mitochondrial depolarization
 * GO:0098792 ! xenophagy

**Comment by dosumis** [comment]
@paolaroncaglia  How viable do you think it would be to have a standard design patterns in this branch?
I think we could specify some relations to use, even if we don't end up with complete logical definitions for all terms:

Questions:
1. How to specify target. For mitophagy we're currently using 'results_in_disassembly_of' .  This could work for lipophagy (target lipid droplets).  But nucleophagy is less clear as disassembly may be partial.

2. How to specify mechanism:
   Micro
   Macro
   chaperone-mediated
   lysosomal 
   ...

**Comment by paolaroncaglia** [comment]
Let me redirect you to David H :-) @ukemi as he's the one who's been actually editing autophagy terms. 
Thanks,
Paola

**Comment by ukemi** [comment]
Hi Chris,

We will add these as the project progresses. The issue with adding them now is that many of the terms are still in flux, both in the ontology and in the community. For example the term autophagy itself describes at least four different processes mechanistically and we are teasing out what subprocesses are in and what subprocesses are out. Once we have done that, we will add axioms for the terms that work. We might find that there is no standard 'pattern' except for some of the sub-types such as macroautophagy differentiated by organelle.
