### ISSUE TITLE
Cell component: occeloid

### ISSUE THREAD

**Issue by alanruttenberg** [geneontology/go-ontology#12086]
Consists of subcellular analogues to a cornea, lens, iris, and retina. Occeloids are built from pre-existing organelles, including a cornea-like layer made of mitochondria and a retinal body made of anastomosing plastids. 

http://www.nature.com/nature/journal/v523/n7559/full/nature14593.html

**Comment by paolaroncaglia** [comment]
@ukemi 
Assigning to myself for consistency as I've added other component terms for Dinoflagellates.

**Comment by paolaroncaglia** [comment]
Hi Alan,

I added GO:0097693 ocelloid, and gave it a taxon constraint for only in Dinoflagellates.
The full stanza is below (ignore the + signs, that's just the diff). 

Thanks,
Paola

 [Term]
+id: GO:0097693
+name: ocelloid
+namespace: cellular_component
+def: "Eye-like subcellular structure found in dinoflagellates (a large group of single-celled eukaryotes). Consists of subcellular analogues to a cornea, lens, iris, and retina. Ocelloids are built from pre-existing organelles, including a cornea-like layer made of mitochondria and a retinal body made of anastomosing plastids." [GOC:ar, PMID:26131935]
+is_a: GO:0043229 ! intracellular organelle
+relationship: has_part GO:0005739 ! mitochondrion
+relationship: has_part GO:0009536 ! plastid
+relationship: only_in_taxon NCBITaxon:2864 ! Dinophyceae
+created_by: paola
+creation_date: 2015-11-13T14:27:01Z
