### ISSUE TITLE
Autophagy-specific ATG8 modifiers lipidation

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#12085]
New Biological Process:
ATG8 family modifiers lipidation

Definition: 
Autophagy proteins involved in the conjugation of ATG8 family ubiquitin-like modifiers onto phosphatidylethanolamine leading to membrane insertion of ATG8 proteins and subsequent autophagosome assembly. Lipidation occurs through a double ubiquitylation-like system conserved in eukaryotes.

PMID:11100732. 15277523, 11096062

Is_a GO:0006501: C-terminal protein lipidation  
Part_of GO:0000045: autophagosome assembly

**Comment by ukemi** [comment]
How about something like this?

term: protein lipidation involved in autophagosome assembly

Definition: The protein lipidation process by which phosphatidylethanolamine is conjugated to a protein of the ATG8 family, leading to membrane insertion of the protein as a step in autophagosome assembly.

is_a: C-terminal protein lipidation
part_of:autophagosome assembly
starts_with ATG8 activating enzyme activity
has_part ATG8 ligase activity
intersection of: C-terminal protein lipidation
intersection of: part_of autophagosome assembly

**Comment by marcfeuermann** [comment]
This sounds good for me.
Regards,
Marc.

**Comment by ukemi** [comment]
Added the term as above.

-D
