### ISSUE TITLE
GO:0043047 single-stranded telomeric DNA binding has an is_a parent   GO:1990837 sequence-specific double-stranded DNA binding

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12082]
GO:0043047 **single-stranded** telomeric DNA binding has an is_a parent GO:1990837 sequence-specific **double-stranded** DNA binding via direct parent GO:0042162 telomeric DNA binding.

Clearly, GO:0042162 telomeric DNA binding cannot have GO:1990837 sequence-specific double-stranded DNA binding as parent as it has a ssDNA binding child...

Birgit

**Comment by dosumis** [comment]
Thanks for spotting. Probably sloppy editing on my part last week.  I'll fix this and add a disjoint to stop it happening again (should be able to bring this in from ChEBI disjoints).

**Comment by dosumis** [comment]
Fixed.  No other errors of this type slipped through and disjointness declaration is now in place.
