### ISSUE TITLE
NTRs: modification by symbiont of host occluding cell-cell junction/bicellular tight junction

### ISSUE THREAD

**Issue by mxb5379** [geneontology/go-ontology#12083]
Term Name- modification by symbiont of host occluding cell-cell junction

 

Definition- The process in which a symbiont organism effects a change in the structure or function of its host occluding junction, a cell-cell junction that seals cells together in an epithelium in a way that prevents even small molecules from leaking from one side of the sheet to the other.

 

Aspect – Biological Process

Relationship –Child Term of GO: 0044067, modification by symbiont of host intercelullar junctions.

·       

Sibling Terms- GO:0044067 does not have any children currently.

 

References – PMID 24287273,

_______________________________________________________________________________

 

 

Term Name- modification by symbiont of host bicellular tight junctions

Definition- The process in which an organism effects a change in the structure or function of its host bicellular tight junctions, an occluding cell-cell junction that is composed of a branching network of sealing strands that completely encircles the apical end of each cell in an epithelial sheet

Aspect – Biological Process

Relationship- Child Term of GO(modification by symbiont of host occluding cell-cell junction)

 

Sibling Terms- none

References- PMID 24287273,

**Comment by suzialeksander** [comment]
Hi,

This is a request for a CACAO student.  Can you please take a quick look at it? He needs to know if it's OK for class credit.  

Thank you!

**Comment by dosumis** [comment]
Added.  For ticket on how we might start formalising terms like this to infer classication, see geneontology/design_patterns#1
