### ISSUE TITLE
New neutrophil compartment terms needed

### ISSUE THREAD

**Issue by scjupe** [geneontology/go-ontology#12084]
I'm creating new events in Reactome using data from a proteomics study on human neutrophils (PMID: 23650620), where the authors refer to 'ficolin-1 rich granules', by which they mean granules that resemble gelatinase (tertiary) granules but are not rich in gelatinases. They have quantitative proteomics data that strongly supports ficolin-1-rich granules as a neutrophil granule class that is distinct from the three classical neutrophil granule subtypes. I think the term ficolin-1 rich granule was first used in this paper - PMID: 19741154, since it has been used many times by these authors and others e.g. PMID: 26108096, and this Nature Reviews in Immunology paper ( PMID: 23435331), which suggests that ficolin-rich granules may be a subtype of Specific (secondary) granules. I'm not sure about the classification, but there appears to be some consensus that ficolin-rich granules are a distinct subcellular compartment. 

To represent the processes of neutrophil granule formation and exocytosis I would like new GO compartment terms for the membrane and lumen of this new granule type, and a term for tertiary granule lumen (tertiary granule membrane and proimary/secondary granule compartment terms exist).

I won't be able to release the new events in Reactome unless I have these terms, ideally I'd like to do this in 2 months time.

Thanks, Steve.

**Comment by mcourtot** [comment]
Initial query: http://jira.geneontology.org/browse/GO-969

**Comment by mcourtot** [comment]
added ID: GO:1904724 Label: tertiary granule lumen

**Comment by mcourtot** [comment]
added ficolin-1 rich granule, http://purl.obolibrary.org/obo/GO_0101002
will add lumen and membrane tomorrow via TG if build ok.

**Comment by mcourtot** [comment]
added ID: GO:1904813 Label: ficolin-1-rich granule lumen

**Comment by mcourtot** [comment]
added 
[Term]
id: GO:0101003
name: ficolin-1-rich granule membrane

**Comment by mcourtot** [comment]
checked - all requested terms are in build 1212. Please reopen if there are any issues.
