### ISSUE TITLE
evidence for GO:0034727 piecemeal microautophagy of nucleus in mammals?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12081]
defined as "Degradation of a cell nucleus by microautophagy"
Has been used by PAINT-ing (IBA) to mammals e.g. Q7Z3C6 ATG9A (Homo sapiens).
I'm not convinced there is any experimental evidence for this process in mammalian literature. PUBMED search with "piecemeal microautophagy of nucleus mammal " finds only four reviews 
NB piecemeal microautophagy of nucleus = PMN
PMID: 12623230 is opinion piece by freelance writer, which appears to quote a conversation with David Goldfarb about this paper:
P. Roberts, et al.
Piecemeal Microautophagy of Nucleus in Saccharomyces cerevisiae
Mol. Biol. Cell, 14 (2003), pp. 129–141 
saying that "...although homologous genes have not been identified, ‘it doesn't mean an autologous process does not occur’ in mammalian cells."
PMID_22080117 doesn't cite examples PMN in mammals
PMID: 21327066 states: "The form of nucleophagy being observed in all these examples [in mammalian cells] would appear to be macroautophagy. The involvement of microautophagic processes cannot yet be unequivocally ruled out. " So, they seem pretty vague on whether PMN is actually occuring in mammals.
PMID: 24275162 has only this:
"We found homology of PF3D7_1339700 to the yeast protein Nvj1 that is present at the formation of nucleus-vacuole junctions and is involved in piecemeal microautophagy of the nucleus".
I know that "absence of evidence" is not "evidence of absence", bit I'm a bit wary about these PAINT-ed annotations, partly because ATG9A has other roles in yeast (orthologue Atg9) and mammals, e.g. autophagosome assembly that may explain the evolutionary conservation.

**Comment by marcfeuermann** [comment]
yes, this is probably an "over-annotation" that should not have been PAINTed ! This will be removed !
Marc.

**Comment by marcfeuermann** [comment]
The PAINT family for ATG9 proteins (PTHR13038) has been re-annotated. We have "un-propagated" yeast specific terms and updated annotation for new terms.
Thanks,
Marc.
