### ISSUE TITLE
link between xenophagy and "defense response to other organism"?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12090]
Should a part_of link between xenophagy and "defense response to other organism" be created? 
 GO:0098542 defense response to other organism
Reactions triggered in response to the presence of another organism that act to protect the cell or organism from damage caused by that organism
GO:0098792	xenophagy
The enclosure of a region of cytoplasm containing an intracellular pathogen or some part of intracellular pathogens (e.g. viral capsid) in a double membrane bound autophagosome, which then fuses with the lysosome leading to degradation of the contents.

**Comment by ukemi** [comment]
id: GO:0098792
 name: xenophagy
 namespace: biological_process
-def: "The enclosure of a region of cytoplasm containing an intracellular pathogen or some part of intracellular pathogens (e.g. viral capsid) in a double membrane bound autophagosome, which then fuses with the lysosome leading to degradation of the contents." [GOC:autophagy, GOC:pad, GOC:PARL, PMID:19802565, PMID:20159618, PMID:25497060]
+def: "The defense response to  other organism by a macroautophagy process in which a region of cytoplasm containing an intracellular pathogen or some part of an intracellular pathogen (e.g. viral capsid) is enclosed in a double membrane bound autophagosome, which then fuses with the lysosome leading to degradation of the contents." [GOC:autophagy, GOC:pad, GOC:PARL, PMID:19802565, PMID:20159618, PMID:25497060]
 comment: While making xenophagy a subclass of (macro)autophagy may seem to directly contradict the definition of autophagy (literally self eating), it is clear that the same pathway is involved as in macroautophagy that doesn't target foreign material: formation of double-membrane-bounded autophagosomes that enclose a region of cytoplasm for degradation.
 is_a: GO:0016236 ! macroautophagy
+is_a: GO:0098542 ! defense response to other organism

**Comment by ukemi** [comment]
It appears I made an unsatisfiable class. I need to make it a part of the defense response.

 id: GO:0098792
 name: xenophagy
 namespace: biological_process
-def: "The defense response to  other organism by a macroautophagy process in which a region of cytoplasm containing an intracellular pathogen or some part of an intracellular pathogen (e.g. viral capsid) is enclosed in a double membrane bound autophagosome, which then fuses with the lysosome leading to degradation of the contents." [GOC:autophagy, GOC:pad, GOC:PARL, PMID:19802565, PMID:20159618, PMID:25497060]
+def: "The macroautophagy process in which a region of cytoplasm containing an intracellular pathogen or some part of an intracellular pathogen (e.g. viral capsid) is enclosed in a double membrane bound autophagosome, which then fuses with the lysosome leading to degradation of the contents." [GOC:autophagy, GOC:pad, GOC:PARL, PMID:19802565, PMID:20159618, PMID:25497060]
 comment: While making xenophagy a subclass of (macro)autophagy may seem to directly contradict the definition of autophagy (literally self eating), it is clear that the same pathway is involved as in macroautophagy that doesn't target foreign material: formation of double-membrane-bounded autophagosomes that enclose a region of cytoplasm for degradation.
 is_a: GO:0016236 ! macroautophagy
-is_a: GO:0098542 ! defense response to other organism
+relationship: part_of GO:0098542 ! defense response to other organism
