### ISSUE TITLE
new terms: ATP hydrolysis coupled inorganic cation transmembrane transport and children

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12091]
Hi,

1. suggested term: ATP hydrolysis coupled inorganic cation transmembrane transport
suggested definition: The transport of inorganic cations against an electrochemical gradient, using energy from ATP hydrolysis. 
child of (?) GO:0098662 inorganic cation transmembrane transport (maybe similar to hierarchy of GO:0015991 ATP hydrolysis coupled proton transport).

![screen shot 2015-10-12 at 13 39 44](https://cloud.githubusercontent.com/assets/12081136/10428094/eebfda4c-70e6-11e5-948d-277bf3ebc3b0.png)

and children

a. child1: ATP hydrolysis coupled sodium transmembrane transport
suggested definition: The transport of sodium cations against an electrochemical gradient, using energy from ATP hydrolysis

b. child2: ATP hydrolysis coupled potassium transmembrane transport
suggested definition: The transport of potassium cations against an electrochemical gradient, using energy from ATP hydrolysis

PMID: 18075585

GOC: BHF
GOC: NC
GOC: mtg_cardiac_conduct_nov11

Thanks

Nancy

**Comment by tberardini** [comment]
Are you sure you want to add the reference to GOC: mtg_cardiac_conduct_nov11?  Unless I'm mistaken, that refers specifically to the meeting in Nov. 2011.

**Comment by tberardini** [comment]
Are you looking for a process term for the function 'sodium:potassium-exchanging ATPase activity' and the inferred 'sodium ion transmembrane transport' + 'potassium ion transmembrane transport' are not enough?  What about 'establishment or maintenance of transmembrane electrochemical gradient', GO:0010248?  I'm not convinced you need a new term.  I could potentially create this relationship:

establishment or maintenance of transmembrane electrochemical gradient
--[part_of] sodium:potassium-exchanging ATPase activity

**Comment by NancyCampbell** [comment]
I wanted to add the ATP-hydrolysis coupling concept - in parallel to GO:0015991 ATP hydrolysis coupled proton transport.

I looked at the definition of sodium ion transmembrane transport: "A process in which a sodium ion is transported from one side of a membrane to the other by means of some agent such as a transporter or pore". But this misses out the ATP hydrolysis coupling bit. What do you think?

I think it is a good idea to create the relationship and I would like that please if possible. Thanks.

**Comment by NancyCampbell** [comment]
and I am checking about GOC: mtg_cardiac_conduct_nov11. I was convinced we were using it but I am checking neverthless. Thanks Tanya.

**Comment by tberardini** [comment]
What about adding a more general term called 'ATP-coupled transmembrane transport'

Def: The transport of molecules across a membrane and against an electrochemical gradient, using energy from ATP hydrolysis.

ATP-coupled transmembrane transport, GO:new
--[part_of] sodium:potassium-exchanging ATPase activity, GO:exists
--[i] ATP hydrolysis coupled proton transport, GO:exists

I'd still keep the additional parentage:

establishment or maintenance of transmembrane electrochemical gradient, GO:exists
--[part_of] sodium:potassium-exchanging ATPase activity, GO:exists

I'm leaning towards not making the specific sodium/potassium transport terms because one does not occur without the other.  Does that make sense?  I think the general term that I propose is close to the one that you wanted and also leaves the door open for other gene products to be annotated to it.

**Comment by NancyCampbell** [comment]
Hi Tanya,
That is neat solution! Perfect. Please go ahead. 
And yes I checked, can we please use GOC: mtg_cardiac_conduct_nov11. (it is an ongoing project :-)!)
Thanks a lot
Nancy

**Comment by tberardini** [comment]
Hi Nancy,

Sorry but my computer has died and I won't get a replacement till next Thursday.  I'm limping along on my personal computer till then but it doesn't have the ontology edition software on it (and I don't want to install it :) ).  I'll get to this as soon as I can.

Thanks for your patience,

Tanya

**Comment by NancyCampbell** [comment]
no problem Tanya. There is no hurry! 
Sorry about computer dying! Hope your new computer is nicer and shinier!
:-)

**Comment by tberardini** [comment]
I hope it will be.  I'm dreading installing all the software again and figuring out how it will interact with the new operating system.

**Comment by tberardini** [comment]
Added one term and new relationships as described above:

+id: GO:0090662
+name: ATP hydrolysis coupled transmembrane transport
+namespace: biological_process
+def: "The transport of molecules across a membrane and against an electrochemical gradient, using energy from ATP hydrolysis." [GOC:BHF, GOC:mtg_cardiac_conduct_nov11, GOC:nc, GOC:tb, PMID:18075585]
+is_a: GO:0055085 ! transmembrane transport
