### ISSUE TITLE
new term for lncRNA annotation

### ISSUE THREAD

**Issue by rbalakri** [geneontology/go-ontology#12094]
term name: TFIIB class transcription factor binding involved in negative regulation of transcription
http://www.ncbi.nlm.nih.gov/pubmed/12461786
Note: annotate DHFR upstream transcripts
Rama

**Comment by tberardini** [comment]
Created using TG, not yet approved.  Shall I approve or do you want to remove some of the synonyms?

[Term]
id: GO:1904725
name: TFIIB-class transcription factor binding involved in negative regulation of transcription
namespace: molecular_function
def: "Any TFIIB-class transcription factor binding that is involved in negative regulation of DNA-templated transcription." [GO_REF:0000061, GOC:rb, GOC:TermGenie, PMID:12461786]
synonym: "TFIIB-class transcription factor binding involved in down regulation of gene-specific transcription" RELATED [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in down regulation of transcription, DNA-dependent" EXACT [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in down-regulation of gene-specific transcription" RELATED [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in down-regulation of transcription, DNA-dependent" EXACT [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in downregulation of gene-specific transcription" RELATED [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in downregulation of transcription, DNA-dependent" EXACT [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in inhibition of gene-specific transcription" RELATED [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in inhibition of transcription, DNA-dependent" NARROW [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in negative regulation of cellular transcription, DNA-dependent" EXACT [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in negative regulation of gene-specific transcription" RELATED [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in negative regulation of transcription, DNA-dependent" EXACT [GOC:TermGenie]
synonym: "TFIIB-class transcription factor binding involved in negative regulation of transcription, DNA-templated" EXACT []
synonym: "TFIIB-class transcription factor binding involved in transcription repressor activity" RELATED [GOC:TermGenie]
is_a: GO:0001093 {is_inferred="true"} ! TFIIB-class transcription factor binding
intersection_of: GO:0001093 ! TFIIB-class transcription factor binding
intersection_of: part_of GO:0045892 ! negative regulation of transcription, DNA-templated
relationship: part_of GO:0045892 {is_inferred="true"} ! negative regulation of transcription, DNA-templated
created_by: tb
creation_date: 2015-10-13T19:49:39Z

**Comment by tberardini** [comment]
Term committed to the ontology and ready to use.
