### ISSUE TITLE
GO:0006490 oligosaccharide-lipid intermediate biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12092]
GO:0006490 oligosaccharide-lipid intermediate biosynthetic process
(I was trying to figure out what it is)
Has dual aprentage to "carbohyrate metabolism" and "carbohydrate derivative metabolism"

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006490#term=ancchart

**Comment by tberardini** [comment]
Good question.  I'll look into it.

**Comment by tberardini** [comment]
Parentage to carbohydrate should go away as a oligosaccharide-lipid intermediate (like dolichol phosphate mannose, Dol-P-Man) is a carbohydrate derivative (see ChEBI, http://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:61286), not a carbohydrate.  I'll remove that.

**Comment by tberardini** [comment]
Done.  I cleaned up around this term too.
