### ISSUE TITLE
temr merge? histone mRNA 3'-end processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12095]
How doe this differ from any other  mRNA 3'-end processing?
Val

GO:0006398
Name	histone mRNA 3'-end processing
Ontology	Biological Process
Definition	Any process involved in forming the mature 3' end of a histone mRNA molecule.
GONUTS	GO:0006398 Wiki Page

**Comment by tberardini** [comment]
"The metazoan replication-dependent histone mRNAs are unusual as they are the only eukaryotic mRNAs that lack poly(A) tails. .....The 3′ end processing of replication-dependent histone mRNAs takes place with a mechanism distinct from that of polyadenylation. "

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2151031/

I propose expanding the definition like this:

Definition Any process involved in forming the mature 3' end of a histone mRNA molecule.  Histone mRNAs contain a highly conserved stem–loop sequence at the 3' end of the mRNA with a 6 base pairs (bp) stem and a 4-nt loop.  The  mRNA  is cleaved between these two elements, after the fourth or fifth nucleotide, which is typically an adenosine.  (PMID:17998288)

**Comment by ValWood** [comment]
better. This sounds familiar now, I think I probably asked about it before.

Maybe  for clarity the term name should reflect the mechanism?
i.e can we be sure that no histone mRNAs are 3' processed by any other mechanism?, or just that this mechanism is only present in protozoa and metazoa? I'm not sure what happens in yeast. Available info says that this mechanism does not occur, but there may be some histone mRNA 3' processing going on?

Conversely, do we absolutely  know that this mechanism really only operates on histones? 
Instead, maybe the term name could be specific to the process? 
e.g. mRNA 3'-end processing by stem–loop binding and cleavage (or similar)
..and mention that this mechanism necessarily involves the SLBP protein? which seems to be the differentia.
Also, add taxon constraint "never in yeast" (yeast do not appear to have SLBP but other components are shared with the adenylation dept cleavage process)

 v

**Comment by tberardini** [comment]
Without spending a great deal of time in the literature, I can answer any of your biology-related questions with a definitive answer in either direction.  Given that, I like your suggestion of altering the term name to reflect the mechanism.

(1) change term name from
 histone mRNA 3'-end processing
to
 mRNA 3'-end processing by stem–loop binding and cleavage

(2) update definition to

Any mRNA 3'-end processing that involves the binding to and cleavage of a stem-loop structure. For example, histone mRNAs contain a highly conserved stem–loop sequence at the 3' end of the mRNA with a 6 base pairs (bp) stem and a 4-nt loop. The mRNA is cleaved between these two elements, after the fourth or fifth nucleotide, which is typically an adenosine. (PMID:17998288) 

(3) Fix synonym types accordingly.

**Comment by ValWood** [comment]
sounds good
Val

**Comment by tberardini** [comment]
never in Ascomycota?  This is the new stanza.

[Term]
id: GO:0006398
name: mRNA 3'-end processing by stem-loop binding and cleavage
namespace: biological_process
def: "Any mRNA 3'-end processing that involves the binding to and cleavage of a stem-loop structure. For example, histone mRNAs contain a highly conserved stem-loop sequence at the 3' end of the mRNA with a 6 base pairs (bp) stem and a 4-nt loop. The mRNA is cleaved between these two elements, after the fourth or fifth nucleotide, which is typically an adenosine." [GOC:mah, GOC:tb, PMID:17998288]
synonym: "histone mRNA 3' end processing" NARROW []
is_a: GO:0008334 ! histone mRNA metabolic process
is_a: GO:0031124 ! mRNA 3'-end processing
relationship: never_in_taxon NCBITaxon:4890 ! Ascomycota

**Comment by ValWood** [comment]
Looks good. If it transpires that this process also occurs in Ascomycota we can relax the constraint.
Thanks
Val

**Comment by tberardini** [comment]
Wonderful.  Thanks for your help.
