### ISSUE TITLE
possible logic problem in sporulation branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12106]
GO:0030435
Name	sporulation resulting in formation of a cellular spore
has the descendant
GO:0034293	sexual sporulation (is_a)
but then
GO:0034293	sexual sporulation 
has the descendant
GO:0043935
Name	sexual sporulation resulting in formation of a cellular spore

but we have already established that sexual sporulation *is* a type of sporulation resulting in formation of a cellular spore?

**Comment by dosumis** [comment]
Yep.  It's wrong. Fixing.

**Comment by ValWood** [comment]
Let me know the fix, might need to re-annotate some stuff...
Thanks

Val

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/10706140/113e3298-79b2-11e5-9768-0b7a8482b60a.png)
