### ISSUE TITLE
new terms sub-processes GO:0061684 Chaperone-mediated autophagy (CMA)?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12103]
![image](https://cloud.githubusercontent.com/assets/12345463/10577367/a937bbe4-7662-11e5-9a92-d7b23519918c.png)
CMA 
GO:0061684 Chaperone-mediated autophagy (CMA)
Def: The autophagy process which begins when chaperones and co-chaperones recognize a KFERQ-related motif and unfold the substrate protein. The process ends with the translocation of the protein across the lysosomal membrane. 
CMA substrates are cytosolic proteins or proteins from other compartments once reach cytosol, with pentapeptide motif biochemically related to KFERQ.
CMA can be divided:
1. Motif recognized by cytosolic chaperone (plus unknown / uncertain co-chaperones), heat shock cognate protein of 70 kDa (hsc70) (human HSPA8), which targets substrate to the lysosome surface.
2. Complex binds to LAMP-2A monomer, substrate unfolded (probably involves membrane-associated HSPA8). Hsp90 (Human HSP90AA1) involved in stability of LAMP-2A complexes
3. LAMP-2A multimerises (number subunits not known - several different sizes detected). Hsp90 (Human HSP90AA1) involved in stability of LAMP-2A complexes, then substrate translocated through lysosomal membrane. HSPA8 inside the lysosomal lumen, may either pull substrates into the lysosome or prevent return to the cytosol.

NB GFAP regulates stability of LAMP-2A complexes and EF1-alpha regulates GFAP-LAMP-2A association.
Finally, degradation substrate by proteases inside lysosome.
I wondered if we should divide up into sub-processes - Or are these going to be limited to too few proteins?
NB Only a few proteins would be annotated with (for example), something like "translocation of cytosolic substrate proteins into lysosome" - HSPA8, LAMP2, HSP90AA1, plus perhaps a few co-chaperones.
@rebeccafoulger said  "I think it looks a bit odd that ‘CMA ;GO:0061684’ ends_with: ‘protein localization to lysosome ; GO:0061462’ since protein localization to lysosome (to me) covers the chaperone’s role in transporting the protein to the lysosome surface as well as getting it INTO the lysosome (import). Plus, in GO, CMA starts_with: protein unfolding ; GO:0043335. This isn’t the first step according to the diagram above."
Wikipedia:
https://en.wikipedia.org/wiki/Chaperone-mediated_autophagy

**Comment by Pauldenny** [comment]
NB I trust the content of this wikipedia page because it's edited and maintained by experts in the lab of Ana Maria Cuervo,  http://www.einstein.yu.edu/faculty/8784/ana-maria-cuervo/

**Comment by Pauldenny** [comment]
GTP negatively modulates CMA in isolated lysosomes (PMID_20797626) - not sure how we can include this in GO. This probably involves a protein called glial fibrillary acidic protein (GFAP - human UniprotKB P14136) Also, I can't find any other papers in PUBMED [using GTP AND "Chaperone-mediated autophagy" in search] confirming this observation.

**Comment by ukemi** [comment]
I made the logical definitions for these terms. I don't think we can make a term for the GTP phenomenon unless we know the mechanism and can describe a function.
