### ISSUE TITLE
Taxon constraint for X, Y chromosome in birds

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#12108]
Request review of taxon constraint for GO terms containing X chromosome and Y chromosome.
never_in Taxon:8782 Aves
PMID: 20622855
 Thanks GOC:mr

**Comment by cmungall** [comment]
And obviously restrictions on Z too

**Comment by michaelerice** [comment]
Sorry,

I just realized this is an issue that was at least partially addressed by Paola.

https://sourceforge.net/p/geneontology/ontology-requests/10840/?limit=10&page=1#9882

and you are correct Chris

**Comment by cmungall** [comment]
Yes #11025 has some discussion, but I think this is a nice valid self-contained request so we should go ahead and do this

**Comment by michaelerice** [comment]
?Thank you


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by michaelerice** [comment]
??so Z chromosome and W chromosome would be restricted to only_in birds and some reptiles; I am not sure of which taxons, when I am able I will look look these up and send them in. Thanks


Mike


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by cmungall** [comment]
I think only_in could be dangerous. Heterogametic sex determination has 
evolved multiple times, not just in vertebrates. never_ins will be safer

**Comment by michaelerice** [comment]
Fiona McCarthy <fionamcc@email.arizona.edu>
Wed 10/21/2015 8:57 AM

Also needs to be checked for ALL species, as we do computational annotation on reptiles, invertebrates, etc.

See:
https://en.wikipedia.org/wiki/XY_sex-determination_system

**Comment by paolaroncaglia** [comment]
Note for self: terms to look at:

BPs:
dosage compensation
(if not applicable, look at its children:
dosage compensation by hyperactivation of X chromosome
dosage compensation by hypoactivation of X chromosome
dosage compensation by inactivation of X chromosome)
regulation of dosage compensation by inactivation of X chromosome
sex determination, establishment of X:A ratio

CCs:
X chromosome located dosage compensation complex, transcription activating
W chromosome
X chromosome
XY body
Y chromosome
Z chromosome

**Comment by paolaroncaglia** [comment]
Hi @michaelerice,

The only constraints (and dbxrefs) I could safely add, based on my knowledge and on some quick reading, are the following:

X chromosome located dosage compensation complex, transcription activating

X chromosome

XY body

Y chromosome

dosage compensation by hyperactivation of X chromosome

dosage compensation by hypoactivation of X chromosome

dosage compensation by inactivation of X chromosome

regulation of dosage compensation by inactivation of X chromosome

sex determination, establishment of X:A ratio

=> relationship: never_in_taxon NCBITaxon:8782 ! Aves
=> GOC:mr, https://en.wikipedia.org/wiki/XY_sex-determination_system, PMID:20622855

Z chromosome

W chromosome

=> relationship: never_in_taxon NCBITaxon:40674 ! Mammalia
=> GOC:mr, https://en.wikipedia.org/wiki/ZW_sex-determination_system, PMID:20622855

These are done now. Addition of further never_ins might be complex and would require more in-depth knowledge. If you can pinpoint other such constraints, please indicate GO terms and suggested taxon rules for them in a new ticket. Thanks!
