### ISSUE TITLE
NTR response to high population density

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#12100]
Term: response to high population density

Definition: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a an excessive number of individuals living per unit of an area (e.g. mass·m−3). source dictionary.com GOC:mr

Synonym: exact crowding
exact over-population

is_a GO:0006950 response to stress

PMID:26439857

**Comment by tberardini** [comment]
http://www.ncbi.nlm.nih.gov/pubmed/?term=26439857

"The stress conditions elicited by HSD [high stocking density] altered the response of the glucosensor systems based on mitochondrial activity, sweet taste receptor, and SGLT-1 in the liver, and LXR and SGLT-1 in the BB [Brockmann bodies]."

**Comment by tberardini** [comment]
"...as a result of a an excessive number of individuals living per unit of an area."  How do we define 'excessive'?
@cmungall

**Comment by michaelerice** [comment]
Tanya,


how about:

the level at which an organism (including on the cellular level)? experiences sustained encroachment by other organisms interfering with it's ability to function normally, with ease and sufficient freedom of movement.

based on dictionary.com definition of excessive and comfort?


?

Mike


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by cmungall** [comment]
That could get a bit problematic.

I'm comfortable without a threshold. The exposure/treatment class would be a neutral rise/increase. Responses could kick in for different individuals at different levels, but we don't need to state this.

Not so different from other response classes

**Comment by tberardini** [comment]
How about:

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a higher than normal number of *multicellular* organisms living per unit area.

What's normal?  Or is it ok for that to be open to interpretation? Should we restrict to multi-cellular organisms so that we don't encompass cellular (think yeast, bacteria) population densities?  Or do we want to leave the term open for usage by unicellular organisms?

**Comment by tberardini** [comment]
What do you think of my latest proposed definition?

**Comment by cmungall** [comment]
I think we'll go with this for now. Can be refined when we have the 
exposure ontology in place

**Comment by tberardini** [comment]
Added:

 [Term]
id: GO:0090664
name: response to high population density
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or a multicellular organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a higher than normal number of multicellular organisms living per unit area." [GOC:mr, PMID:26439857]
synonym: "response to crowding" EXACT [GOC:mr]
is_a: GO:0006950 ! response to stress
is_a: GO:0044707 ! single-multicellular organism process
is_a: GO:0051707 ! response to other organism
