### ISSUE TITLE
NTR: Galanin signaling pathway

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#12101]
Dear GO editors,
would it be possible to have a term describing the signaling pathway activated by binding of the neuropeptide Galanin to its receptors GALR1 and GALR2 as described in PubMed:25691535.
Thanks for your help.
Bestr regards,
Lionel

**Comment by tberardini** [comment]
Added:

+id: GO:0090663
+name: galanin-activated signaling pathway
+namespace: biological_process
+def: "The series of molecular signals generated as a consequence of the peptide neurotransmitter galanin binding to a cell surface receptor." [GOC:lb, PMID:25691535]
+synonym: "galanin signaling pathway" RELATED []
+synonym: "galanin signalling pathway" RELATED []
+synonym: "galanin-activated signalling pathway" EXACT []
+is_a: GO:0007218 ! neuropeptide signaling pathway
