### ISSUE TITLE
which "meiosis" do these terms refer to?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12107]
We need to clean up any remaining terms referring to 'meiosis' and establish if they are refereing to 

i) meiotic cell cycle
or
ii) meiotic nuclear division

There are still these
Process  GO:0010790 meiotic sister chromatid cohesion involved in meiosis II  
Process  GO:0033621 nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts  
Process  GO:0010672 regulation of transcription from RNA polymerase II promoter during meiosis  
Process  GO:0010673 positive regulation of transcription from RNA polymerase II promoter during meiosis 
Process  GO:0010674 negative regulation of transcription from RNA polymerase II promoter during meiosis 
Process  GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter  
Process  GO:1900475 positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter  
Process  GO:1900476 positive regulation of meiosis by positive regulation of transcription from RNA polymerase II promoter

The term names can say 'meiosis' but the defs need  to specify which

I can help with this one:
GO:0033621
The chemical reactions and pathways resulting in the selective degradation of meiosis-specific transcripts during vegetative growth,
can be
The chemical reactions and pathways resulting in the selective degradation of transcripts expressed specifically during the meiotic cell cycle during vegetative growth.
(the exp annotations are all pombase)

any parentage need to be adjusted to match the def

**Comment by dosumis** [comment]
Assuming the relationships are correct:

> There are still these
> Process GO:0010790 meiotic sister chromatid cohesion involved in meiosis II
SubClassOf 'part of' some 'meiosis II'  # This is nuc div

> Process GO:0033621 nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts 

No formal link to meiosis and process not *during* meiosis, but refers to degredation of "meiosis-specific transcripts during vegetative growth".  I'd guess the def should be to the cycle term.

> Process GO:0010672 regulation of transcription from RNA polymerase II promoter during meiosis

SubClassOf 'part of' some 'meiotic nuclear division'  # inherited from superclass

> Process GO:0010673 positive regulation of transcription from RNA polymerase II promoter during meiosis

SubClassOf 'part of' some 'meiotic nuclear division'  # inherited from superclass

> Process GO:0010674 negative regulation of transcription from RNA polymerase II promoter during meiosis 

SubClassOf 'part of' some 'meiotic nuclear division'  # inherited from superclass

> Process GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter

Regulated process is defined as:
EquivalentTo: 'transcription from RNA polymerase II promoter'
 and (regulates some 'meiotic nuclear division')

> Process GO:1900475 positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter

See previous

> Process GO:1900476 positive regulation of meiosis by positive regulation of transcription from RNA polymerase II promoter

See previous

**Comment by dosumis** [comment]
Hi Val,  Is it correct to assume that the relationship are correct and adjust asserted parentage appropriately (as outlined in previous comment?  
Cheers,
David

**Comment by ValWood** [comment]
I'm not sure. I don't know of any "meiotic nuclear division" transcription, but  there is "meiotic cell cell cycle" specific  transcription.

Of the 5 experimental annotations  to
GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter
and descendants 3 pombe genes and 2 cerevisiae ...

At least for the pombe ones I think it should be "meiotic cell cycle" 
cuf2 seems to be specific for sporulation genes and mei4 is required for the expression of many genes during meiotic cell cycle. It is required for meiosis I genes, but there isn't any evidence that meiotic nuclear division is regulated transcriptionally (its post-translationally regulated).

**Comment by ValWood** [comment]
This is quick:

- [ ]  *  GO:0010790 meiotic sister chromatid cohesion involved in meiosis II
can be defined as part of 
GO:0007126	meiotic nuclear division

- [ ] 
Process GO:0033621 nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts
can be defined as part of 
GO:0051321	meiotic cell cycle



Process GO:0010672 regulation of transcription from RNA polymerase II promoter during meiosis
Process GO:0010673 positive regulation of transcription from RNA polymerase II promoter during meiosis
Process GO:0010674 negative regulation of transcription from RNA polymerase II promoter during meiosis
All of these "transcription during" terms should be obsoleted in
https://github.com/geneontology/go-ontology/issues/10594



- [ ] 
Process GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter
Process GO:1900475 positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter
Process GO:1900476 positive regulation of meiosis by positive regulation of transcription from RNA polymerase II promoter

can be defined as part of 
GO:0051321	meiotic cell cycle

**Comment by ValWood** [comment]
These are fixed or OK
