### ISSUE TITLE
Autophagy parentage

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12104]
1) Right now autophagy is considered to be a catabolic process, but it
seems like it is much more than that. Should it instead be a cellular
process and has_part catabolic process?

Moved to cellular process with has_part cellular catabolic process

2) Right now macroautophagy is a response to starvation, but it seems like
it can be triggered in other ways. As I read I am finding it is likely
that it is used to get rid of sperm mitochondria after fertilization and
can also be induced upon growth factor removal. Should we remove the
response to starvation requirement? If it is a response to starvation,
then the beginning of the process would have to be at the input of the
starvation process. It seems to me that a better place to have autophagy
start is at ATG1/UKL1 kinase complex assembly. That way the whole process
can be regulated by upstream by the mTOR pathway, which phosphorylates one
of the components of the complex. The AKT-mTOR signaling would then
negatively regulate macroautophagy. This way mTOR signaling can be a
separate pathway that negatively regulates macroautophagy and positively
regualtes protein synthesis.

Removed the response to stress parent and requested ATG1/UKL1 kinase complex assembly via TG.

**Comment by ukemi** [comment]
@Pauldenny @paolaroncaglia @marcfeuermann @RLovering

**Comment by Pauldenny** [comment]
Probably just your typo here, but please check that you've asked for **ATG1/ULK1** kinase complex assembly and not "ATG1/UKL1" kinase complex assembly.
Thanks
Paul

**Comment by ukemi** [comment]
Good catch Paul! Looks like the target term had the typo. I will fix the target term too.

-D
