### ISSUE TITLE
ntr child of nuclear migration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12102]
1. Add synonym nuclear movement to 'nuclear migration'

2. Add  grouping term
nuclear migration by microtubule
The directed movement of the nucleus by microtubules

3. Add new term
nuclear migration by microtubule mediated pushing forces
The directed movement of the nucleus by pushing forces exerted by polymerization of backward-extending microtubules.

4. Make  "nuclear migration along microtubule" a sibling of 3.

PMID: 11309419 for original ref in pombe. Currently annotating PMID:16611238

**Comment by dosumis** [comment]
Added

'nuclear migration by microtubule mediated pushing forces': The directed movement of the nucleus by pushing forces exerted by polymerization of backward-extending microtubules.

Not sure the grouping term is justified.  In one case microtubules are the agent (pushing), in the other it is motor proteins with microtubules providing the tracks.

**Comment by ValWood** [comment]
Yeah good point, skip the grouping term...
