### ISSUE TITLE
new synonym for GO:0045121	membrane raft

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12105]
In PMID: 16645198, authors also describe membrane rafts as "membrane microdomains" - I think it would be useful to add this as a related synonym.  This is relevant to the process of chaperone-mediated autophagy (CMA), because authors (PMID: 20176123) talk about how "the organization of LAMP-2A at the lysosomal membrane is regulated by its dynamic association with **discrete membrane lipid microdomains** " and how "upon CMA activation, LAMP-2A moves outside these regions into areas of higher fluidity".

**Comment by dosumis** [comment]
Perhaps a broad synonym?  Could be many criteria for microdomain.

**Comment by Pauldenny** [comment]
I'd be happy with that, thanks.

**Comment by dosumis** [comment]
Decided to make a new term.  Seems to be quite a bit of lit on these things. Much broader than lipid rafts:

Some refs:

At tight Junctions: http://www.ncbi.nlm.nih.gov/pubmed/26003050
In plants: http://www.ncbi.nlm.nih.gov/pubmed/25936559
Non-lipid raft microdomains: http://www.ncbi.nlm.nih.gov/pubmed/26419316 (and references therein)
http://www.ncbi.nlm.nih.gov/pubmed/21978926

**Comment by dosumis** [comment]
[Term]
id: GO:0098857
name: membrane microdomain
namespace: celullar_compoment
def: "A membrane region with a lipid composition that is distinct from that of the membrane regions that surround it." [PMID:26253820, PMID:20044567]
is_a: GO:0098589 ! membrane region
namespace: cellular_component
