### ISSUE TITLE
stereocilia terms lack part_of relationships

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12113]
These need better part-of links eg to CL

 * GO:0002139 ! stereocilia coupling link [subclass: "GO:0044464"] [subclass: "cell part"]
 * GO:0032421 ! stereocilium bundle [subclass: "GO:0043232"] [subclass: "intracellular non-membrane-bounded organelle"]

See diagram
![st](https://cloud.githubusercontent.com/assets/50745/10623917/51809b8c-7748-11e5-983c-b9f85b6c4c65.png)

**Comment by dosumis** [comment]
Mmmm, spaghetti .... (dreams of a glorious future where clean partonomies and local axioms on terms are sufficient).

That path through stereocillium bundle to non-membrane-bound organelle is wrong too.

**Comment by dosumis** [comment]
Cleared up lots here:

* neuromast cells have stereocillia too.  I've made CL po link to mechanosensory hair cell
This is classified in CL as a neuron.  Perhaps should also be epithelial?
* Added missing terms and partonomy links under stereocillium and stereocillium bundle
* Made new classification 'actin-based cell projection' that covers this, microvillus and fillpodium
* Added in missing details of biology of  'actin-based cell projection' s
* stereocillium bundle and micovillus are now grouped under 'cluster of actin-based cell projections' - link to intracelullar non-membrane bound organelle dropped.

Chasing up a few loose ends on this.  One of these - stereocillium seems to be used for projections in male reproductive system, but these are probably more like microvilli.
