### ISSUE TITLE
NTR: Wnt signalosome

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12118]
New term request: 

LRP5/6 signalosome ; GO:NEW
narrow synonym: LRP6 signalosome [PMID: 22899650, PMID: 25074807]
broad synonym: Wnt signalosome [GOC:bf]
is_a: protein complex ; GO:0043234
capable_of_part_of: canonical Wnt signaling pathway ; GO:0060070
has_part: Frizzled-LRP5/6 complex ; GO:1990851
Definition: A multiprotein protein complex containing membrane-localized Wnt receptors and cytosolic protein complexes, which is capable of transmitting the Wnt signal. Contains at least a Wnt protein, LRP5/LRP6, a member of the Frizzled (Fz) family, Axin and and a Dishevelled (DVL) protein.
Comment: Within the LRP5/6 signalosome, beta-catenin phosphorylation is inhibited through internalisation of the signalosome complex, resulting in the sequestration of GSK3-beta into mutli-vesicular bodies. No longer phosphorylated and targeted for degradation, beta-catenin is free to enter the nucleus and modulate downstream transcription.
PMID: 22899650
PMID: 25336320
GOC:PARL
GOC:bf

NB: See also ‘Wnt signalosome’ in the PD-map: http://minerva.uni.lu/MapViewer/?id=pdmap
NB: Similar to existing terms ‘TCR signalosome ; GO:0036398’ and ‘COP9 signalosome ; GO:0008180’
NB: I haven’t added ‘plasma membrane part’ as a parent because, although the complex assembles at the plasma membrane, it’s subsequently internalised (see PMID: 22899650)

--------

Second term request:

LRP5/6 signalosome scaffold ; GO:NEW2
is_a: receptor signaling complex scaffold activity ; GO:0030159
Definition: Functions to provide a physical support for the assembly of a LRP6 signalosome.
PMID: 22899650
GOC:PARL
GOC:bf
capable_of_part_of: LRP5/6 signalosome assembly ; GO:NEW

NB: I’ll create ‘LRP5/6 signalosome assembly’ terms in TG afterwards.

Any comments/edits?

Thank you.

**Comment by bmeldal** [comment]
@dosumis 
This is a typical example of a complex that has no functional relationship within GO. Should we allow new terms of this type before we have decided what to do with the refractoring?

>LRP5/6 signalosome scaffold ; GO:NEW2
>is_a: receptor signaling complex scaffold activity ; GO:0030159
doesn't work as the new term is CC, the is_a is MF, should that be capable_of? But,

can we please not use that weird receptor "GO:0030159 signaling complex scaffold activity" term (and in fact all it's parent's children, GO:0032947 protein complex scaffold)? Being a scaffold is not really an activity. I thought there was a ticket but I can't find it now.

Sorry Rebecca for stalling this ticket :(

Birgit

**Comment by ValWood** [comment]
Midori will be your friend, she detests these terms :)

I don't mind them so much, sometimes they are useful for the structural component of a complex upon which the rest of the complex assembles (WDR and TPR repeat proteins and the like). I would vote for keeping them to represent the functions (they are placed as a type of binding term), but remove 'activity' from the term name. I *do* think they are used a little to liberally for all sorts of complex subunits without an identifiable molecular function term.

**Comment by ValWood** [comment]
Actually, I reconsidered. I would be happy to get rid of them too.....

**Comment by bmeldal** [comment]
Started new ticket for the scaffolding terms at

https://github.com/geneontology/go-ontology/issues/12123

**Comment by rebeccafoulger** [comment]
Scaffolding MF terms aside, does the LRP5/6 signalosome term (GO:NEW1) fit with the complex guidelines @bmeldal @dosumis? I can think of lots of complexes that are part of signaling events that wouldn't have a function (other than binding).

**Comment by bmeldal** [comment]
Hi Rebecca,
I was hoping @dosumis would answer this as it's the GO term that's contentious! 

Is it capable_of GO:0042813 Wnt-activated receptor activity?
Then it would definitely survive the chop that's impending :)

As for part_of location, where does it carry out it's function, in the membrane or in the cell itself? That could determine the relationship. I find it tricky that GO does not allow several part_of relationships as some complexes really are part_of several structures... I have a very old, open ticket on that...

But I think the signalosome should be ok anyway. It's a grouping term so can be annotation target for lots of proteins/complexes.

Do you have a specific complex that we can add to the CP?

Birgit

**Comment by dosumis** [comment]
> Is it capable_of GO:0042813 Wnt-activated receptor activity?

Seems not because definition has: 

> Contains at least a Wnt protein

> Is it capable_of GO:0042813 Wnt-activated receptor activity?
> Then it would definitely survive the chop that's impending :)

Given current plans, it would need a necessary & sufficient definition to survive the chop (timescale still to be decided) - not just an assertion of function.   I think it's fine to go in for now though - potentially splitting out to InTact in future (?).

**Comment by bmeldal** [comment]
Ok, Rebecca, go ahead.

David, this complex does not define specific subunits so couldn't go into IntAct as is. It's a grouping term.

Birgit

**Comment by bmeldal** [comment]
GO:0042813 Wnt-activated receptor activity:
Def:
"Combining with a Wnt protein and transmitting the signal across the plasma membrane to initiate a change in cell activity."

Complex contains a Wnt protein... matter of semantics: the activity is carried out by some members of the Wnt signalosome that combine with Wnt to create the complex...

**Comment by rebeccafoulger** [comment]
Added: Wnt signalosome ; GO:1990909

Closing this ticket, now there's a new ticket for scaffolding terms.
Thanks!
