### ISSUE TITLE
NTR? - delivery of selective autophagic substrates to the nascent autophagosome

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12115]
As part_of GO:0016236 macroautophagy
I wonder if we can define a sub-process of: 
delivery / targeting of cargo / substrates to the autophagosome? 
I couldn't find something similar already in GO.
This could apply to many different varieties of selective autophagy and would be useful for numerous proteins e.g. SMURF1 (PMID: 22020285) and cargo adaptors such as SQSTM1(=p62 UniprotKB Q13501) (PMID: 23545414).
GOC:pad
GOC:PARL

**Comment by ukemi** [comment]
How about 
substrate localization to autophagosome
def: The localization process by which an autophagic substrate is delivered to a forming autophagosome.
is_a: GO:0051234 establishment of localization
part_of: autophagosome assembly
synonym: substrate sequestration to autophagosome
synonym: substrate sequestration to phagophore (J:199115)

**Comment by Pauldenny** [comment]
This sounds good
Thanks, David.

Best regards,
Paul Denny
Sent from my mobile, please excuse spelling, brevity
Parkinson's UK Annotation Project Co-ordinator
Skype pauldennyuk | E: p.denny@ucl.ac.uk<mailto:p.denny@ucl.ac.uk> | W: http://www.ucl.ac.uk/functional-gene-annotation/neurological | M: +44-07922078038<tel:+44-07922078038> | L: +44-020-7679-6965<tel:+44-020-7679-6965>
Centre for Cardiovascular Genetics
University College London
Rayne Building
5 University Street<x-apple-data-detectors://5>
London WC1E 6JF<x-apple-data-detectors://5>

On 18 Nov 2015, at 21:00, ukemi <notifications@github.com<mailto:notifications@github.com>> wrote:


How about
substrate localization to autophagosome
def: The localization process by which an autophagic substrate is delivered to a forming autophagosome.
is_a: GO:0051234 establishment of localization
part_of: autophagosome assembly
synonym: substrate sequestration to autophagosome
synonym: substrate sequestration to phagophore (J:199115)

-

**Comment by ukemi** [comment]
Done.

**Comment by Pauldenny** [comment]
Hi david
thanks for this term, but I wondered whether it needs a further relationship? At present, it's simply a child of  GO:0051649 establishment of localization in cell
but I wondered whether it should also be part_of macroautophagy? or capable_of_part_of ?!
@marcfeuermann ?

**Comment by ukemi** [comment]
Maybe I forgot to make it part of autophagosome assembly. I will check and add it if I forgot.
