### ISSUE TITLE
add comments to gamma-glutamyltransferase/glutathione hydrolase 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12114]
gamma-glutamyltransferase activity
Add comment: This reaction is used in assays to detect the presence of the enzyme gamma-glutamyl transpeptidase (GGT), but the physiological function of GGT is glutathione hydrolase activity

See
https://github.com/geneontology/go-annotation/issues/1324#issuecomment-149591615

.

**Comment by ValWood** [comment]
What should we do in these situations? PomBase were chatting about this the other day. I  make the  annotation to the physiological activity, and don't capture the assayed activity if it isn't considered  to be physiologically relevant.

**Comment by dosumis** [comment]
> What should we do in these situations? PomBase were chatting about this the other day. I make the annotation to the physiological activity, and don't capture the assayed activity if it isn't considered to be physiologically relevant.

I think this is the right thing to do.

**Comment by dosumis** [comment]
> What should we do in these situations? PomBase were chatting about this the other day. I make the annotation to the physiological activity, and don't capture the assayed activity if it isn't considered to be physiologically relevant.

Your summary on the annotation issues tracker is nice and clear, but I think the suggested comment is confusing as it muddles together assays, reactions and activities, and gene families.

> "This reaction is used in assays to detect the presence of the enzyme gamma-glutamyl transpeptidase (GGT) , but the physiological function of GGT is glutathione hydrolase activity."

The term refers to an activity not a reaction.  By the end of the comment GGT refers to a gene family.

How about: 

The gene family commonly referred to as gamma-glutamyl transferases (GGT) catalyze *hydrolysis* of  gamma-glutamyl bonds in gamma-glutamyl compounds such as glutathione. In a test tube one can set up conditions in which the enzyme will *transfer* the gamma-glutamyl portion of the substrate to an acceptor molecule, but this requires non-physiologic conditions, including millmolar concentrations of an acceptor such as glygly. This reaction is used in assays to detect the presence of the enzyme, but is not a physiological function of members of the GGT family (PMC4388159), which should be annotated to a suitable hydrolysis term instead (e.g. gluathione transferase).

**Comment by ValWood** [comment]
Much better. 
(althougth the final  (e.g. gluathione transferase) should be  "glutathione hydrolase"

However wait to see I dug further and I'm not sure exactly what the yeast one is doing. This comment *might* only apply to Metazoa.

val

**Comment by ValWood** [comment]
http://geneontology.org/page/go-annotation-conventions
don't mention annotating "physiologically relevant" except in passing under binding guidelines
should be documented

**Comment by dosumis** [comment]
> (althougth the final (e.g. gluathione transferase) should be "glutathione hydrolase"

Oops. 

> However wait to see I dug further and I'm not sure exactly what the yeast one is doing. This comment might only apply to Metazoa.

OK

**Comment by cmungall** [comment]
How many of these proxies are there?

If it's more than a few, then I think we need to do more than a 
machine-unreadable comment.

I think the correct place is OBI. OBI would represent the assay, and the 
assay could have two relationships, one to the activity measured (the 
proxy), the other for the inferred function.

We could then use this to periodically check annotations, suggest 
transfers.

I think OBI would be willing to do most of the work here.

**Comment by dosumis** [comment]
> If it's more than a few, then I think we need to do more than a
machine-unreadable comment.

Agreed, but in addition to comments.

**Comment by dosumis** [comment]
> http://geneontology.org/page/go-annotation-conventions
don't mention annotating "physiologically relevant" except in passing under binding guidelines
should be documented

Isn't this covered by the the general guidelines:
"A gene product should be annotated with terms reflecting its normal activity and location."

**Comment by dosumis** [comment]
Added comment as detailed above.  @ValWood - please let me know if it needs to be modified.

**Comment by ValWood** [comment]
yep its fine. I just wanted to double check, as it came up as a question for us  last week in relation to something else.

**Comment by ValWood** [comment]
Stacia at SGD confirmed:
 In Sc, it breaks down GSH into its constituent aa’s.  so the hydrolase and catabolism annotations appear to be valid for Sc.
so I think the comments are oK for all species.

I wonder in this case if the "gamma-glutamyltransferase activity"   we should also add taxon restrictions for metazoa and yeast at least until we find any evidence for   relevance?
-> 15,289 for 11,911 proteins

**Comment by ValWood** [comment]
39 annotations just for human GGT's
