### ISSUE TITLE
terms for chaperone mediated autophagy (CMA) receptor complex CC plus related processes 

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12110]
The chaperone mediated autophagy (CMA) translocation / receptor complex is cited numerous times in the literature
e.g. PMID: 24281265 (review) and https://en.wikipedia.org/wiki/Chaperone-mediated_autophagy
Consists of LAMP-2A (human UniprotKB P13473-1) "and a lysosome resident variant of hsc70 (lys-hsc70) ... only components of the translocation complex identified so far." (PMID:20797626). 
Is localised to lysosomal membrane, dynamic and involves multimers of LAMP-2A plus changes in localisation to / from GO:0045121 membrane raft in the lysosomal membrane during CMA.  
Assembly and disassembly of translocation / receptor complex multimers are key steps allowing CMA, so would like terms such as: 
LAMP-2 complex
LAMP-2 complex assembly
LAMP-2 complex disassembly

**Comment by ukemi** [comment]
Hi Paul,

Added

[Term]
+id: GO:0061742
+name: chaperone-mediated autophagy translocation complex
+namespace: cellular_component
+def: "A lysosomal membrane protein complex that enables the translocating a target protein across the lysosomal membrane as part of chaperone-mediated autophagy." [GOC:dph, GOC:pad, GOC:PARL, PMID:20797626]
+synonym: "chaperone-mediated autophagy receptor complex" RELATED [GOC:dph, GOC:pad, GOC:PARL]
+synonym: "CMA receptor complex" RELATED [GOC:dph, GOC:pad, GOC:PARL]
+synonym: "CMA translocation complex" EXACT [GOC:dph, GOC:pad, GOC:PARL, PMID:20797626]
+is_a: GO:0043234 ! protein complex
+intersection_of: GO:0043234 ! protein complex
+intersection_of: capable_of_part_of GO:0061741 ! chaperone-mediated protein transport involved in chaperone-mediated autophagy
+intersection_of: part_of GO:0005765 ! lysosomal membrane
+relationship: part_of GO:0005765 ! lysosomal membrane
+created_by: dph
+creation_date: 2015-10-23T07:39:04Z

If we need the assembly and disassembly terms, we can make them with TermGenie.
