### ISSUE TITLE
Link  GO:0000333 telomerase catalytic core complex to GO:0003720 telomerase activity

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12117]
Hi,
I can't see that these cc and mf terms are linked on QuickGO chart (screenshot below):
GO:0000333 telomerase catalytic core complex to GO:0003720 telomerase activity

<img width="1402" alt="screen shot 2015-10-22 at 14 46 14" src="https://cloud.githubusercontent.com/assets/12081136/10666785/af731632-78cb-11e5-96b3-d73f340a0852.png">

I think it makes sense to link them with a capable_of relationship perhaps as the complex is always capable of this activity. And would it then make sense to link with a capable_of part_of relationship with the process term  GO:0006278 RNA-dependent DNA replication (or will this be implied if the first relationship is created?)

There is a lot of evidence for this but here is one: PMID 18082603 fig 1c.

I looked on term genie for a template but I can't find one. I know it is available in freeform but in this instance the complex already exists. Maybe worth talking to Birgit too for input? @bmeldal 

Sorry if I missed something.

One more thing: do you need GOC xrefs for new links too? (my gut instinct is no).

Thanks
Nancy

**Comment by NancyCampbell** [comment]
@bmeldal

**Comment by bmeldal** [comment]
You are right, it would be a legitimate link but it needs adding by an editor as the complex already exists.

Full annotations are here:
http://www.ebi.ac.uk/intact/complex/details/EBI-10045577

Birgit

**Comment by NancyCampbell** [comment]
Thanks Birgit.

**Comment by NancyCampbell** [comment]
@JessBuxton

**Comment by dosumis** [comment]
Will add today.

**Comment by NancyCampbell** [comment]
Thanks David.

**Comment by dosumis** [comment]
Have added capable_of telomerase activity. No need to added link to process, as telomerase activity already has po link to this.

**Comment by NancyCampbell** [comment]
perfect. thank you david.
nancy
