### ISSUE TITLE
NTR:multivesicular body fusion to apical plasma membrane

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12112]
Hi,
I'd like to request a new term for annotating gene products from this paper:
http://www.ncbi.nlm.nih.gov/pubmed/26459596

GO:0061025 membrane fusion
  is_a GO:new multivesicular body fusion to apical plasma membrane

GO:1990182 exosomal secretion
  part_of GO:new multivesicular body fusion to apical plasma membrane

Thanks,
--Kimberly

**Comment by dosumis** [comment]
Perhaps make some link to exosome secretion?

**Comment by dosumis** [comment]
label "multivesicular body fusion to apical plasma membrane"@en
definition "The fusion of the membrane of a multivesicular body with the apical plasma membrane, resulting in release of exosomes from the cell"
EquivalentTo: 'membrane fusion' 
and (results_in_fusion_of some 'apical plasma membrane')
and (results_in_fusion_of some 'multivesicular body membrane')
and ('part of' some 'exosomal secretion')
