### ISSUE TITLE
No GO term for beta-arrestin GPCR biased signalling

### ISSUE THREAD

**Issue by ismaelresp** [geneontology/go-ontology#12119]
The only GO biological process term I found about arrestin is GPCR desensitization while in literature there are lots of papers talking about beta-arrestin biased pathway signaling. Here you have a review as example: 
Transduction of Receptor Signals by ß-Arrestins
Robert J. Lefkowitz, Sudha K. Shenoy
Science 22 April 2005:
Vol. 308 no. 5721 pp. 512-517
DOI: 10.1126/science.1109237

**Comment by ValWood** [comment]
Closing  this seems like a Molecular function involved in a  signalling process
