### ISSUE TITLE
NTR: Intramembranous bone morphogenesis AND NTR: Intramembranous bone growth

### ISSUE THREAD

**Issue by madstidham1** [geneontology/go-ontology#12111]
Potential GO term: Intramembranous bone morphogenesis
Definition: The process in which bones are generated and organized from neural crest-derived mesenchymal cells.
Aspect: biological process
Relationships: This is a child of GO:0060349 Bone morphogenesis.
GO:0001957 Intramembranous ossification is a "part of" intramembranous bone morphogenesis.
References: PMID:26399686 Figure 4
Taxon Restraints: Only_in_taxon Eukaryota 2759
only_in_taxon Vertebrata 7742
never_in_taxon Saccharomyces cerevisiae 4932
never_in_taxon Schizosaccharomyces pombe 4896

Second NTR:
Potential GO term:Intramembranous bone growth
Definition: The increase in size or mass of an intramembranous bone that contributes to the shaping of the bone.
Aspect: biological process
Relationships: This term is a child of GO: 0035265 Organ Growth and is also a child of GO:0060560 developmental growth involved in morphogenesis. This term is a "part of" intramembranous bone morphogenesis.
References: PMID:26399686 Figure 4

**Comment by jimhu-tamu** [comment]
Maddie is one of our CACAO students, so we would appreciate an update.

**Comment by dosumis** [comment]
Hi Jim & Maddie,

I'll add the terms today.

- David

**Comment by dosumis** [comment]
Added via TG:

GO:1904770 Label: intramembranous bone morphogenesis
GO:0098867 Label: intramembranous bone growth

+ a general term for bone element growth (sits in between the new term and organ growth).

Not convinced I should make the part relationship from growth term to morphogenesis terms, as it seems to me that much growth occurs outside of morphogenesis (Presumably isometric growth (change in size without changing shape) is not considered part of morphogenesis).  @ukemi  - Any comment on this? If no objections, I'll remove this relationship from the similar term 'endochondral bone morphogenesis' too.

**Comment by ukemi** [comment]
Hi David,

I agree. Only asymmetric growth would be considered part of morphogenesis.

-D

**Comment by dosumis** [comment]
OK.  Will delete.  Thanks.
