### ISSUE TITLE
GO:0032947 protein complex scaffold - obsoletion or narrowing of def?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12123]
Following on from mine and @ValWood's comment on ticket 

https://github.com/geneontology/go-ontology/issues/12118

can we please restructure this term? Being a scaffold is not really an activity. I thought there was a ticket but I can't find it now.

We could obsolete this term and its children or at least be much more strict on its use?

For starters we need to take the word 'activity' out of he child terms!

Any comments?

Birgit

**Comment by rebeccafoulger** [comment]
I've forgotten the last time we revisited the structural molecule terms, though I doubt @paolaroncaglia has! The UCL team are reluctant to see these go entirely, but I agree 'activity should be removed from the child terms, and I think they need connecting up with the related 'binding, bridging' GO terms (GO:0060090).

**Comment by paolaroncaglia** [comment]
Hi Birgit, Becky, Val @ValWood and David OS @dosumis 

Jane ‘owned’ a closely related ticket and I inherited it from her, but haven’t had a chance to work on it yet:

https://github.com/geneontology/go-ontology/issues/11331

Actually, we handed over to David OS the general restructuring, here:

https://github.com/geneontology/go-ontology/issues/10895

So, David, I’m afraid that for consistency you should own all 3 tickets. I’ll assign them to you, with many many thanks in advance.

Paola

**Comment by cmungall** [comment]
I'm not following exactly what the request is here

This is the hierarchy:
```
 / GO:0003674 ! molecular_function
  is_a GO:0005198 ! structural molecule activity
   is_a GO:0032947 ! protein complex scaffold ***
    is_a GO:0005078 ! MAP-kinase scaffold activity
    is_a GO:0030159 ! receptor signaling complex scaffold activity
```

(PCS also has a superclass of protein binding)

Is the proposal to obsolete the whole hierarchy under PCS? Or to label everything more consistently (which seems uncontroversial)?

@thomaspd recently used  GO:0005078 ! MAP-kinase scaffold activity in the lego model for IQGAP1, this one seems to fit in the scope of the MF refactor

**Comment by bmeldal** [comment]
@cmungall my grip is that if sounds like these proteins are actively doing something but they are just keeping the structure and sometimes they are even dispensable for the activity of the other partners. I don't necessarily want them obsoleted but as @rebeccafoulger above mentioned, they word 'activity' needs stripping from all scaffolding terms and linking them to 'binding' wouldn't be a bad idea either. To me, they even sound more CC class-like than MF, but that might go to far...

Compare it to a building site: the catalytic units are the workers, the scaffolding proteins just that, the scaffolding that lets the workers access the sites they are fixing :) The scaffolding does one thing, standing still and supporting the workers. 

Mini-Project I think...

**Comment by ValWood** [comment]
In the building analogy the scaffold term would represent the building foundations..... It's used to describe a "platform" onto which protein complex assembles, so although it does  not have an "activity' this "protein scaffold" is it's 'molecular function'. In GO terms, the building scaffold would be a 'chaperone' (enables the assembly but is not part of the final building (complex)...

The protein complex scaffold term
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0032947#term=ancchart
is already under protein binding.

A lot of the other "structural constituent of" terms under "structural molecule activity" do sound a bit whacky...but there have been numerous  unsuccessful attempts to address these.....

**Comment by bmeldal** [comment]
Thanks, Val!

**Comment by pgaudet** [comment]
See also #12632

**Comment by pgaudet** [comment]
This term is used quite a bit; I think it's useful. The number of EXP annotations by group is shown below. 

I could remove 'activity' but then it might sound too much like a complex...? Maybe that would be improved if use simply used 'scaffold protein', which seems to be a widely used term (https://en.wikipedia.org/wiki/Scaffold_protein)

Number of annotations per group - perhaps some people responsible for the annotation want to weigh in: 

(39)	SGD @srengel 
(26)	UniProt @ggeorghiou @sylvainpoux 
(25)	BHF-UCL @RLovering 
(13)	RGD @slaulederkind 
(12)	CGD
(8)	MGI @hdrabkin 
(4)	PomBase @ValWood 
(4)	WB @vanaukenk 
(3)	FlyBase @hattrill 
(3)	UniProtKB
(2)	CAFA
(2)	EcoCyc
(2)	TAIR
(1)	HGNC
(1)	SynGO-UCL


Thanks, Pascale

**Comment by hattrill** [comment]
I rather like this term and its friend, receptor signaling complex scaffold activity. Scaffold protein is a bit too passive for my liking.

In the case of something like dishellevd that self-associates and nucleates the "signalosome" OR axin for the beta catenin destruction complex, we really have no other way of capturing this activity. I think as the signaling project gathers pace, we will use these terms more and more.

**Comment by ValWood** [comment]
Yes I think for now we should keep it as it is.
It is the only way to annotate the activity of things like "MAP kinase scaffold"

**Comment by pgaudet** [comment]
OK, no action needed then. I'm closing this.
