### ISSUE TITLE
GO:0061742 - typo

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12129]
there's a typo in GO:0061742 chaperone-mediated autophagy translocation complex

Definition : A lysosomal membrane protein complex that enables **the translocating** a target protein across the lysosomal membrane as part of chaperone-mediated autophagy. 

Should either be 'translocating' or 'the translocation'...

Birgit

**Comment by paolaroncaglia** [comment]
Fixed, thanks.
