### ISSUE TITLE
Add a procedure to propagate taxon constraints from dependent ontologies

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12128]
Migrated from https://www.ebi.ac.uk/panda/jira/browse/GO-220

We have two strategies

 1. Do not strip out TCs when making import modules
 2. Have a procedure to instantiate TCs on GO classes using dependent ontologies

1 is more complex than it seems to do the nature of import chains, see https://github.com/ontodev/robot/issues/38

2 is attractive as it allows buffering. E.g. we can instantiate uberon-derived TCs (which are v strict) and selectively de-instantiate

Procedure to implement 2 will follow later

**Comment by paolaroncaglia** [comment]
@cmungall , assigning to you for the time being.

@dosumis , this stems from necessary work for the 'taxonomy' JBMS paper; Chris said "This one [Jira ticket] is constantly on the forefront of my and DOS' mind but it would be good to have an explicit ticket in github", so here it is :-)

Thanks,
Paola

**Comment by dosumis** [comment]
I'd be very happy to see this happen.  I guess the worry is that the
resulting cleanup job will be large.  Presumably mosty annotations that
will be hit.  Would be good to see reports of impact on both ontology and
annotations before implementing.

**Comment by paolaroncaglia** [comment]
Hi @cmungall , any update on this please? :-)

Many thanks,

Paola

**Comment by cmungall** [comment]
Choosing option 1.

Fix is in r29572
