### ISSUE TITLE
new F_P link antioxidant activity -> removal of superoxide radicals

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12124]
could antioxidant activity have a F-P link to GO:0019430 - removal of superoxide radicals?

if not some other descendant of cellular detoxification?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990748#term=children

**Comment by ValWood** [comment]
also, can 
GO:0042744 - hydrogen peroxide catabolic process
have some link to cellular detoxification, or isn't it always 'detoxification'?

**Comment by paolaroncaglia** [comment]
Hi Val,

This is very similar to https://github.com/geneontology/go-ontology/issues/11893, which is assigned to David OS, so I’m going to hand him this one too for consistency… thanks @ 

Also related, https://github.com/geneontology/go-ontology/issues/11869 and https://github.com/geneontology/go-ontology/issues/12088, so I’m going to give those to David too. 

(David, let me know if you want me to take any of your other tickets, now or next time you’re on GH duty…)

Thanks,
Paola

**Comment by ValWood** [comment]
Yes its quite possibly a duplicate. it keeps popping onto my list when I check the pombe GO slim "fallout"

**Comment by dosumis** [comment]
Added 

label "cellular oxidant detoxification"@en
definition "Any process carried out at the cellular level that reduces or removes the toxicity superoxide radicals or hydrogen peroxide."

antioxidant activity part_of some cellular oxidant detoxification
