### ISSUE TITLE
Odd default namespace 2015-10-24 release

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12127]
Looking in the header of gene_ontology_ext.obo

default-namespace: file:/Users/tanyaberardini/go_svn/ontology/extensions/ro_pending.obo

where it's usually

default-namespace: gene_ontology

**Comment by paolaroncaglia** [comment]
Hi Jim,

As you've probably seen by now, Doug reported the same issue on the go-consortium mailing list, and it was fixed. 

For reference, https://github.com/geneontology/go-ontology/issues/12141

Thanks for reporting.

Paola
