### ISSUE TITLE
Investigate why fatty acyl-coA binding no longer anion binding

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12121]
Reported here.

I removed the assertion, synced the reasoner, no joy:

<img width="954" alt="screen shot 2015-10-22 at 10 39 45 am" src="https://cloud.githubusercontent.com/assets/50745/10673171/438645f6-78a9-11e5-8c54-405fec2cfc74.png">

**Comment by cmungall** [comment]
This is an import chain problem

fatty-acyl-CoA has GCIs in biochebi

However, these get removed when making chebi_import.owl

This is the domain of the owalpi SLME. I would expect axioms to be preserved but apparently not. The SLME can be a black box. It may be that we need to write our own code here.

**Comment by deustp01** [comment]
Is the axiom tripping over an ambiguity in CHEBI? There are two fatty acyl-CoA terms, CHEBI:77636 - fatty acyl-CoA(4−) and CHEBI:37554 - fatty acyl-CoA. The first, anionic form is the one expected in cells at near-neutral pH, but both forms of the molecule are probably named in publications so there may be correctly formulated (i.e., the curator reports what the paper says) annotations to both. Or is this an irrelevant tangent?

**Comment by cmungall** [comment]
@hdietze can we run the bio-chebi tool on chebi_imports, ie post-module extraction. We'll obviously need to make sure the OPs and existential axioms are preserved during modularization, then run biochebi to add GCIs

**Comment by cmungall** [comment]
@dosumis - there are probably multiple cases like this, in theory the bio-chebi GCIs should help us here

**Comment by deustp01** [comment]
Putting this in its broader social context, there is a long, unresolved discussion about the correct pH to use in annotating cellular processes. Reality is complicated - lysosomes work at acidic pH's as do mammalian stomachs, and the range of possibilities open to organisms in deep-sea thermal vents is enormous. Groups like RHEA, I think, settle on near-neutrality for everything. Reactome is erratic - sometimes we take the physiological pH into account, but not always, and sometimes it's hard to figure out what the physiological pH is.

**Comment by cmungall** [comment]
@deustp01 - thanks for the comments. This is ticket is all about a subtle bug in the import chains that affects how the reasoner uses the conjugate base relationships in CHEBI. We had various discussions about physiological normality way back when we did the original GO-CHEBI alignment. For now everything is effectively equivalent

**Comment by cmungall** [comment]
This is now fixed, see https://build.berkeleybop.org/view/GO/job/build-go-assert-inferences-report/lastSuccessfulBuild/artifact/assert-report.txt/*view*/

This also elimates about half of the ETINEs, hurrah!

**Comment by deustp01** [comment]
“Effective equivalence” sounds exactly right.
