### ISSUE TITLE
obsolete GO:0072468 signal transduction involved in cell shape checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12125]
GO:0072468 signal transduction involved in cell shape checkpoint
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0072468#term=ancchart

we don't have any other checkpoint terms related to this term. I think it was renamed/redefined
GO:0044879 morphogenesis checkpoint
and
GO:0044878 cytokinesis checkpoint

**Comment by ukemi** [comment]
Hey Val,
Can you give a reason for obsoleting and I will send out a notice?

-D

**Comment by ValWood** [comment]
These are the 2 checkpoints related to cell shape: (I'm not sure that it gets called cell shape checkpoint, I think  that was just us!)

GO:0044879 morphogenesis checkpoint
and
GO:0044878 cytokinesis checkpoint

**Comment by ukemi** [comment]
Hi Val,

Based on the definition of GO:0044879 I think we should do the same thing we did for GO:0044878 and rename it 'mitotic morphogenesis checkpoint'. Since cell shape means basically the same thing as morphogenesis (to me anyways) and there are no genes annotated to the cell shape terms, can't we just merge them into the morphogenesis checkpoint terms and make them related synonyms?

-D

**Comment by ValWood** [comment]
Hi David,

I think we should obsolete these. They just got forgotten somehow, but they should have gone. The previous terms were very confused.
See  the end of this thread:
https://github.com/geneontology/go-ontology/issues/11354

Val

**Comment by ukemi** [comment]
Shall I obsolete the detection of stimulus one too?

**Comment by ukemi** [comment]
And the response to cell shape checkpoint? None have any annotations.

**Comment by ValWood** [comment]
Yes both. They should have gone with the other terms. They were too conflated to keep.
Val

**Comment by ukemi** [comment]
Dear all,

The proposal has been made to obsolete the following terms:

GO:0072466	detection of stimulus involved in cell shape checkpoint
GO:0072467	response to cell shape checkpoint signaling
GO:0072468	signal transduction involved in cell shape checkpoint

The reason for obsoletion is that these terms and their target process
were confusing and the original process was split into two, GO:0044879
morphogenesis checkpoint
And GO:0044878 cytokinesis checkpoint

All details here:
https://github.com/geneontology/go-ontology/issues/12125

There are no annotations to these terms.
These terms are cross-referenced in the NBO.


We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete the terms above on April 26, 2016.

*** Unless objections are received by April 26, 2016, we will assume
that you agree to this change. ***

Thanks,

David H

**Comment by ukemi** [comment]
Terms obsoleted.
