### ISSUE TITLE
Create rules for use of PR in c17 of GAF

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#12138]
From Jira GO-278

The ecocyc GAF has lines such as this:

```
UniProtKB P0AD01 dcuR GO:0006355 GO_REF:0000037 IEA SP_KW:KW-0805 P DcuR transcriptional activator dcuR|yjdG|b4124|ECK4117 protein taxon:83333 20140118 UniProtKB PR:000022415
```

Note here the c17 value is actually the superclass of the protein in c2:
http://www.proconsortium.org/cgi-bin/pro/entry_pro?id=PR:000022415

This should be invalid. c17 is for indicating a specific isoform of the generic organism-gene level entry in c2. It isn't an ID mapping column.

I propose a new annotation rule:

If a PR ID is used in c17, it must be Category=organism-gene or below (even Category=organism-gene is debatable, as this is the same level of specificity as what is in c2).

**Comment by hdrabkin** [comment]
Harold Drabkin added a comment - 31-Mar-14 16:13

Yes, we just saw this.
There are even PR: ids for IEAs
All of these map to the gene level/organism gene;

The rules as I remember were
for c17, if have isoform id, put it in
else
UniProtKB: (not isoform)

**Comment by hdrabkin** [comment]
MGI has already cleaned up (not reflected in GAF yet; fix needs to move into production;
ecocyc still may be a problem.

**Comment by paolaroncaglia** [comment]
Hi Harold,
Please assign as appropriate (to yourself presumably?).
Thank you.
Paola

**Comment by hdrabkin** [comment]
This is more of an annotation issue; maybe needs documentation?

@pgaudet can we transfer this to go/annotatation?

**Comment by pgaudet** [comment]
Sure it can be moved - but what needs to be done ? Document the rule and add a check ?

**Comment by hdrabkin** [comment]
Yes, something like that.

**Comment by pgaudet** [comment]
just checking with @cmungall that checks of the annotations go in the go-annotation tracker (sounds reasonable!) 

Thanks, Pascale

**Comment by pgaudet** [comment]
Moved to https://github.com/geneontology/go-site/issues/835
