### ISSUE TITLE
Difference between GO:0070840 and GO:0045502

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#12133]
GO:0070840: dynein complex binding
Def: Interacting selectively and non-covalently with a dynein complex, a protein complex that contains two or three dynein heavy chains and several light chains, and has microtubule motor activity.
BUT
GO:0045502 dynein binding
Def: Interacting selectively and non-covalently with dynein, the multisubunit protein complex that is associated with microtubules.. 
GO:0045502 defines dynein as a complex; 

Children of GO:0045502 are individual binding terms to the subunits (example, dynein heavy chain binding, dynein light change binding, etc.
GO:0070840 has no children

Should these be merged, OR: maybe 5502 should be renamed dynein chain binding, and change the def accordingly (no mention of complex).

Addtional relevant info:
GO:0030286, dynein  complex, defined as Any of several large complexes that contain two or three dynein heavy chains and several light chains, and have microtubule motor activity.
This has cytoplasmic and axonemal children.

**Comment by paolaroncaglia** [comment]
Hi @hdrabkin, (and @krchristie and @hattrill for dynein expertise, as we’ve discussed related terms recently)

GO:0045502 dynein binding
and
GO:0070840 dynein complex binding
indeed mean the same. Digging up some GO archeology, ‘dynein complex’ was added very early on, but was linked to the protein complex branch only in recent times. ‘dynein binding’ was added soon after ‘dynein complex’ as is_a protein binding, and was never linked to the protein complex branch. ‘dynein complex binding’ was added in 2009, and then logically defined using ‘dynein complex’. So, 
- [ ] we should retain GO:0070840 ‘dynein complex binding’, and merge ‘dynein binding’ into it.

GO:0070840 ‘dynein complex binding’ has no children, while GO:0045502 ‘dynein binding’ has 4 (individual terms for (protein) binding to heavy, intermediate, light and light intermediate chain; these 4 children have a total of 51 manual experimental annotations). We’d need to re-model this correctly via ‘dynein complex’. ‘dynein complex’ has is_a children for axonemal and cytoplasmic dynein complexes. 
- [ ] We should add links between ‘dynein complex’ and the individual PR entries for generic heavy, intermediate, light and light intermediate chain (e.g. ‘dynein light chain binding’ currently points to PR:000002201 ‘dynein light chain’). @hdrabkin, what would the right PR entries be? Also, would it be biologically correct to have has_part as well as the reciprocal part_of links?

As for terms to indicate binding to the individual chains, 
- [ ] we should logically define all of them (similarly to ‘dynein light chain binding’)

Depending on the type of relationship between ‘dynein complex’ and the individual chains, I’m not sure if/how the individual binding terms would be (automatically) linked to ‘dynein complex binding’, and whether annotations would propagate or not. But dyneins only exist and work as complexes as far as I know, so I’d say that binding to an individual chain also always means binding to the complex; if so we should have 
- [ ] dynein light chain binding is_a dynein complex binding, etc.
which should be taken care of by merging ‘dynein binding’ into ‘dynein complex binding’.

Any concern please let me know, thanks.

**Comment by hattrill** [comment]
Hmmm - yes I see what you mean. A bit of a mess. If all dynein binding terms and its children were merged  under dynein complex binding, then there would be many instances where a component of the complex is binding the complex e.g. dynein intermediate chain annotated with dynein light chain binding. So, there would need to be a bit of a clean up to remove these annotations from dynein subunits.
I can't think of any physiological instances where dyneins function as monomers (or homodimers) outside of the motor complex, so I guess merging and cleaning up is the order of the day.
I would be in favour of: "retain GO:0070840 ‘dynein complex binding’, and merge ‘dynein binding’ into it." and dropping all the different flavours of chain binding.

**Comment by krchristie** [comment]
It does seem to me that "dynein binding" and "dynein complex binding" mean exactly the same thing, so I agree with merging the two terms.

However, once they are merged, will it  be correct to say that the current child terms of "dynein binding" are IS_A children of "dynein complex binding" since none of the individual chains is a complex by itself? Would it be better to change the relationship types, perhaps to "part_of"?

I am not in favor or Helen's suggestion to drop the different flavors of chain binding. I've seen plenty of papers characterizing which type of chain various things bind, and this seems useful to the research community, so I'd prefer to keep them, possibly changing the relationship types between these and "dynein complex binding" if needed.





 I don't think we'd need to clean up these annotations to remove them from the dynein chains. I think changing the relationship between the individual chain binding terms and "dynein complex binding"

**Comment by paolaroncaglia** [comment]
Thanks @hattrill and @krchristie for your helpful input. I will do the following:

- [ ] retain the current children of ‘dynein binding’, but place them directly under ‘protein binding’. That way I can

- [ ] merge ‘dynein binding’ into ‘dynein complex binding’ (‘dynein binding’ has 21 direct, manual experimental annotations, which will be automatically moved to ‘dynein complex binding’; we’ve agreed that the two terms mean the same so we don’t need to alert databases.)

- [ ] leave it to @hdrabkin (who raised the issue first) to evaluate how to best logically define the following terms (see my suggestion in https://github.com/geneontology/go-ontology/issues/12133#issuecomment-272125692), and how to best link them to ‘dynein complex binding’. Thanks.

**Comment by hattrill** [comment]
Sounds good to me. Thanks, Paola.

**Comment by paolaroncaglia** [comment]
@hdrabkin 
Assigning this ticket to you to take care of the last task, see my earlier comment from today. Thanks.

**Comment by krchristie** [comment]
Sounds good to me too. Thanks Paola.

**Comment by ValWood** [comment]
This seems to be done? Can close? Reopen if not
