### ISSUE TITLE
Terms with same names in two different ontologies

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12139]
migrating from EBI-JIRA tracker: issue created 27-Feb-14 22:31
https://www.ebi.ac.uk/panda/jira/browse/GO-273

epidermal cell (PO:0004013) generated 1 warning: The terms epidermal cell (PO:0004013) and epidermal cell (CL:0000362) share the name or synonym "epidermal cell".

epidermal cell (CL:0000362) generated 1 warning: The terms epidermal cell (PO:0004013) and epidermal cell (CL:0000362) share the name or synonym "epidermal cell".

[Chris] 'epidermal' is pretty vague. You can pick and choose from a bunch of concepts, and get either a very broad concept (covering any outer
layer of cells) or specific (the specific layer in vertebrates that is adjacent to the dermis). Uberon has 'outer epithelial layer' and the more
specific 'skin epidermis' with the CL terms associated with the former (which is necessary as 'epidermal cell (sensu Arthropoda)' is a subclass.
There is a taxon constraint to Eumetazoa (some sponge lineages may have epithelial cells but I don't believe they form an outer layer in the same
way). I favor keeping the plants and eumetazoan concepts distinct, and PO coming up with another name (possibly encoded as 'obo foundry unique
label'). Of course, GO conflates the two concepts: http://amigo2.berkeleybop.org/cgi-bin/amigo2/amigo/term/GO:0009913

gamete (PO:0025006) generated 1 warning: The terms gamete (PO:0025006) and gamete (CL:0000300) share the name or synonym "gamete".

gamete (CL:0000300) generated 1 warning: The terms gamete (PO:0025006) and gamete (CL:0000300) share the name or synonym "gamete".

[Chris] Tanya, which is correct?
[Tanya] Defs are similar enough that they could be merged. Punt to PO folks.

micropyle (GO:0070825) generated 1 warning: The terms micropyle (GO:0070825) and micropyle (PO:0020025) share the name or synonym "micropyle".

micropyle (PO:0020025) generated 1 warning: The terms micropyle (GO:0070825) and micropyle (PO:0020025) share the name or synonym "micropyle".

[Chris] Tanya, which is correct?
[Tanya] V. interesting. Hadn't heard of the 'other' micropyle before.
Animal micropyle = opening in ovum that allows sperm to enter.
Plant micropyle = opening in ovule that allows pollen/pollen tube to enter.

**Comment by tberardini** [comment]
27-Feb-14 22:38
Re: epidermal cell and gamete

Consult PO.

Clean up GO. There's all kinds of plant stuff under skin development!

Integument -> plant integument

skin development: synonym integumentary system development?

------------------

micropyle

remove annotation from plants to 'micropyle'. This is the animal term. [TB:fixed]

PO - propose 'ovule micropyle' vs. 'ovum micropyle'

**Comment by tberardini** [comment]
27-Feb-14 22:52
xanthophore (GO:0031633) generated 1 warning: The terms xanthophore (GO:0031633) and xanthophore (CL:0000430) share the name or synonym "xanthophore".

xanthophore (CL:0000430) generated 1 warning: The terms xanthophore (GO:0031633) and xanthophore (CL:0000430) share the name or synonym "xanthophore".

[Paola] The GO term has a def. comment specifying the difference.

[Chris] One of us needs to yield here…

------------------------

Propose: CL to add 'cell' to their term, 'xanthophore cell'

**Comment by tberardini** [comment]
17-Jun-15 21:36

All the plant epidermal cell related mess under skin development and epidermis development was cleaned up. As far as I can tell, the gamete situation is cleaned up as well.

**Comment by tberardini** [comment]
Opened three github issues for remaining items:

https://github.com/cmungall/cell-ontology/issues/182
https://github.com/Planteome/plant-ontology/issues/609
https://github.com/Planteome/plant-ontology/issues/610

**Comment by tberardini** [comment]
@cmungall

**Comment by cmungall** [comment]
CL fixed in http://purl.obolibrary.org/obo/cl/releases/2015-10-29/cl.owl

Will be in go imports tomorrow

**Comment by tberardini** [comment]
PO issues closed.  Will be in their next release.

That finishes off the pending items.  Closing.
