### ISSUE TITLE
Verify that existing XPs are in place for receptor activities  (Jira GO-241)

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#12137]
Rebecca Foulger created issue - 09-Dec-13 08:23
Rebecca Foulger added a comment - 09-Dec-13 08:27

Most XPs are in gene_ontology_write.obo (for ChEBI ligands) or in x-mf-protein.obo for protein ligands. Need to check if any are missing.

For:
[Term]
id: GO:0004996 ! thyroid-stimulating hormone receptor activity
intersection_of: GO:0004872 ! receptor activity

Ask PRO for an ID for 'thyroid-stimulating hormone'. TSH is a dimer of an alpha and beta subunit. The alpha subunit is shared with other hormones. The beta subunit is unique and defines the specificity.

C

**Comment by hdrabkin** [comment]
Chris Mungall added a comment - 10-Dec-13 23:50
open modeling question:

In x-mf-protein, I experimented with a relation

starts_with_has_input = starts_with o has_input

(in OWL you only get the implication one way).

This may seem odd, but then receptor activities are odd;

The current pattern is "X receptor activity" has_part some "X binding"

so not really an "atomic" process.

implicitly, a RA starts with the binding and then ends with...

The point of the more specific relation was to allow inferences of what the input of the binding was; not so much for within-ontology inference, but for when we have instances of GO classes, as in "lego diagrams".

I think we have some work to do here. Note that in Paul's representation of Wnt signaling, there is no explicit "Wnt binding" event (it's implicitly there in the reciprocal):
https://docs.google.com/document/d/1TV8Eb9sSvFY-weVZaIfzCxF1qbnmkUaiUhTm9Bs3gRE/edit#

For now I think we should just make these has_input, same as we do for CHEBI, and return to this issue later,
Rebecca Foulger added a comment - 11-Dec-13 09:38

For the enzyme receptors, I think we can say:
starts_with: ligand binding
ends with: enzyme activity (e.g. tyrosine kinase activity)

For non-enzyme receptors, there's not one function term that would describe the function of the intracellular receptor domain.
Rebecca Foulger added a comment - 11-Dec-13 09:44

PRO request for TSH is here: https://sourceforge.net/p/pro-obo/term-requests/83/

**Comment by hdrabkin** [comment]
Chris Mungall added a comment - 11-Dec-13 17:34
Simplified relations to has_input for now. (r14011)
I will move into gene_ontology_xp_write when ready

**Comment by hdrabkin** [comment]
hris Mungall added a comment - 12-Dec-13 12:28

    GO:0001566 ! non-kinase phorbol ester receptor activity
    GO:0001571 ! non-tyrosine kinase fibroblast growth factor receptor activity
    GO:0001586 ! Gi/o-coupled serotonin receptor activity
    GO:0001587 ! Gq/11-coupled serotonin receptor activity
    GO:0001594 ! trace-amine receptor activity
    GO:0001596 ! angiotensin type I receptor activity
    GO:0001604 ! urotensin II receptor activity
    GO:0001605 ! adrenomedullin receptor activity
    GO:0001607 ! neuromedin U receptor activity
    GO:0001608 ! G-protein coupled nucleotide receptor activity
    GO:0001609 ! G-protein coupled adenosine receptor activity
    GO:0001614 ! purinergic nucleotide receptor activity
    GO:0001618 ! virus receptor activity
    GO:0001626 ! nociceptin receptor activity
    GO:0001631 ! cysteinyl leukotriene receptor activity
    GO:0001635 ! calcitonin gene-related polypeptide receptor activity
    GO:0001637 ! G-protein coupled chemoattractant receptor activity
    GO:0001639 ! PLC activating G-protein coupled glutamate receptor activity
    GO:0001640 ! adenylate cyclase inhibiting G-protein coupled glutamate receptor activity
    GO:0001641 ! group II metabotropic glutamate receptor activity
    GO:0001642 ! group III metabotropic glutamate receptor activity
    GO:0001647 ! G-protein coupled cytokinin receptor activity
    GO:0001648 ! proteinase activated receptor activity
    GO:0001792 ! polymeric immunoglobulin receptor activity
    GO:0001793 ! IgM receptor activity
    GO:0001847 ! opsonin receptor activity
    GO:0001857 ! complement component C1q receptor activity
    GO:0001858 ! complement component iC3b receptor activity
    GO:0001859 ! complement component C3dg receptor activity
    GO:0001860 ! complement component C3d receptor activity
    GO:0001861 ! complement component C4b receptor activity
    GO:0001863 ! collectin receptor activity
    GO:0002170 ! high affinity IgA receptor activity
    GO:0002171 ! low affinity IgA receptor activity
    GO:0002172 ! high affinity IgM receptor activity
    GO:0002173 ! low affinity IgM receptor activity
    GO:0004872 ! receptor activity
    GO:0004873 ! asialoglycoprotein receptor activity
    GO:0004874 ! aryl hydrocarbon receptor activity
    GO:0004875 ! complement receptor activity
    GO:0004876 ! complement component C3a receptor activity
    GO:0004877 ! complement component C3b receptor activity
    GO:0004878 ! complement component C5a receptor activity
    GO:0004886 ! 9-cis retinoic acid receptor activity
    GO:0004888 ! transmembrane signaling receptor activity
    GO:0004890 ! GABA-A receptor activity
    GO:0004896 ! cytokine receptor activity
    GO:0004904 ! interferon receptor activity
    GO:0004905 ! type I interferon receptor activity
    GO:0004906 ! interferon-gamma receptor activity
    GO:0004909 ! interleukin-1, Type I, activating receptor activity
    GO:0004910 ! interleukin-1, Type II, blocking receptor activity
    GO:0004930 ! G-protein coupled receptor activity
    GO:0004932 ! mating-type factor pheromone receptor activity
    GO:0004933 ! mating-type a-factor pheromone receptor activity
    GO:0004934 ! mating-type alpha-factor pheromone receptor activity
    GO:0004935 ! adrenergic receptor activity
    GO:0004936 ! alpha-adrenergic receptor activity
    GO:0004937 ! alpha1-adrenergic receptor activity
    GO:0004938 ! alpha2-adrenergic receptor activity
    GO:0004939 ! beta-adrenergic receptor activity
    GO:0004940 ! beta1-adrenergic receptor activity
    GO:0004941 ! beta2-adrenergic receptor activity
    GO:0004942 ! anaphylatoxin receptor activity
    GO:0004943 ! C3a anaphylatoxin receptor activity
    GO:0004944 ! C5a anaphylatoxin receptor activity
    GO:0004945 ! angiotensin type II receptor activity
    GO:0004946 ! bombesin receptor activity
    GO:0004950 ! chemokine receptor activity
    GO:0004952 ! dopamine neurotransmitter receptor activity
    GO:0004962 ! endothelin receptor activity
    GO:0004963 ! follicle-stimulating hormone receptor activity
    GO:0004964 ! luteinizing hormone receptor activity
    GO:0004965 ! G-protein coupled GABA receptor activity
    GO:0004968 ! gonadotropin-releasing hormone receptor activity
    GO:0004970 ! ionotropic glutamate receptor activity
    GO:0004972 ! N-methyl-D-aspartate selective glutamate receptor activity
    GO:0004977 ! melanocortin receptor activity
    GO:0004980 ! melanocyte-stimulating hormone receptor activity
    GO:0004982 ! N-formyl peptide receptor activity
    GO:0004984 ! olfactory receptor activity
    GO:0004985 ! opioid receptor activity
    GO:0004995 ! tachykinin receptor activity
    GO:0004996 ! thyroid-stimulating hormone receptor activity
    GO:0004997 ! thyrotropin-releasing hormone receptor activity
    GO:0004999 ! vasoactive intestinal polypeptide receptor activity
    GO:0005003 ! ephrin receptor activity
    GO:0005004 ! GPI-linked ephrin receptor activity
    GO:0005005 ! transmembrane-ephrin receptor activity
    GO:0005007 ! fibroblast growth factor-activated receptor activity
    GO:0005010 ! insulin-like growth factor-activated receptor activity
    GO:0005011 ! macrophage colony-stimulating factor receptor activity
    GO:0005017 ! platelet-derived growth factor-activated receptor activity
    GO:0005018 ! platelet-derived growth factor alpha-receptor activity
    GO:0005019 ! platelet-derived growth factor beta-receptor activity
    GO:0005021 ! vascular endothelial growth factor-activated receptor activity
    GO:0005030 ! neurotrophin receptor activity
    GO:0005035 ! death receptor activity
    GO:0005040 ! decoy death receptor activity
    GO:0005042 ! netrin receptor activity
    GO:0005044 ! scavenger receptor activity
    GO:0005049 ! nuclear export signal receptor activity
    GO:0005055 ! laminin receptor activity
    GO:0005056 ! tiggrin receptor activity
    GO:0005484 ! SNAP receptor activity
    GO:0008020 ! G-protein coupled photoreceptor activity
    GO:0008029 ! pentraxin receptor activity
    GO:0008030 ! neuronal pentraxin receptor activity
    GO:0008036 ! diuretic hormone receptor activity
    GO:0008158 ! hedgehog receptor activity
    GO:0008188 ! neuropeptide receptor activity
    GO:0008196 ! vitellogenin receptor activity
    GO:0008227 ! G-protein coupled amine receptor activity
    GO:0008261 ! allatostatin receptor activity
    GO:0008262 ! importin-alpha export receptor activity
    GO:0008288 ! boss receptor activity
    GO:0008313 ! gurken-activated receptor activity
    GO:0008329 ! signaling pattern recognition receptor activity
    GO:0008527 ! taste receptor activity
    GO:0008528 ! G-protein coupled peptide receptor activity
    GO:0009881 ! photoreceptor activity
    GO:0009882 ! blue light photoreceptor activity
    GO:0009883 ! red or far-red light photoreceptor activity
    GO:0009885 ! transmembrane histidine kinase cytokinin receptor activity
    GO:0010465 ! nerve growth factor receptor activity
    GO:0015026 ! coreceptor activity
    GO:0015052 ! beta3-adrenergic receptor activity
    GO:0015056 ! corticotrophin-releasing factor receptor activity
    GO:0015057 ! thrombin receptor activity
    GO:0015065 ! uridine nucleotide receptor activity
    GO:0015277 ! kainate selective glutamate receptor activity
    GO:0016492 ! G-protein coupled neurotensin receptor activity
    GO:0016493 ! C-C chemokine receptor activity
    GO:0016494 ! C-X-C chemokine receptor activity
    GO:0016495 ! C-X3-C chemokine receptor activity
    GO:0016496 ! substance P receptor activity
    GO:0016497 ! substance K receptor activity
    GO:0016498 ! neuromedin K receptor activity
    GO:0016500 ! protein-hormone receptor activity
    GO:0016517 ! interleukin-12 receptor activity
    GO:0016518 ! interleukin-14 receptor activity
    GO:0016519 ! gastric inhibitory peptide receptor activity
    GO:0016524 ! latrotoxin receptor activity
    GO:0016907 ! G-protein coupled acetylcholine receptor activity
    GO:0016941 ! natriuretic peptide receptor activity
    GO:0016964 ! alpha-2 macroglobulin receptor activity
    GO:0017002 ! activin-activated receptor activity
    GO:0019763 ! immunoglobulin receptor activity
    GO:0019766 ! IgA receptor activity
    GO:0019767 ! IgE receptor activity
    GO:0019768 ! high affinity IgE receptor activity
    GO:0019769 ! low affinity IgE receptor activity
    GO:0019770 ! IgG receptor activity
    GO:0019771 ! high affinity IgG receptor activity
    GO:0019772 ! low affinity IgG receptor activity
    GO:0030107 ! HLA-A specific inhibitory MHC class I receptor activity
    GO:0030108 ! HLA-A specific activating MHC class I receptor activity
    GO:0030109 ! HLA-B specific inhibitory MHC class I receptor activity
    GO:0030110 ! HLA-C specific inhibitory MHC class I receptor activity
    GO:0030229 ! very-low-density lipoprotein particle receptor activity
    GO:0030273 ! melanin-concentrating hormone receptor activity
    GO:0030373 ! high molecular weight B cell growth factor receptor activity
    GO:0031516 ! far-red light photoreceptor activity
    GO:0031517 ! red light photoreceptor activity
    GO:0032393 ! MHC class I receptor activity
    GO:0032394 ! MHC class Ib receptor activity
    GO:0032395 ! MHC class II receptor activity
    GO:0032396 ! inhibitory MHC class I receptor activity
    GO:0032397 ! activating MHC class I receptor activity
    GO:0033038 ! bitter taste receptor activity
    GO:0033039 ! salty taste receptor activity
    GO:0033040 ! sour taste receptor activity
    GO:0033041 ! sweet taste receptor activity
    GO:0033042 ! umami taste receptor activity
    GO:0034348 ! type III interferon receptor activity
    GO:0035013 ! myosuppressin receptor activity
    GO:0035236 ! proctolin receptor activity
    GO:0035237 ! corazonin receptor activity
    GO:0035472 ! choriogonadotropin hormone receptor activity
    GO:0035586 ! purinergic receptor activity
    GO:0036326 ! VEGF-A-activated receptor activity
    GO:0036327 ! VEGF-B-activated receptor activity
    GO:0036328 ! VEGF-C-activated receptor activity
    GO:0036329 ! VEGF-D-activated receptor activity
    GO:0036330 ! VEGF-E-activated receptor activity
    GO:0036332 ! placental growth factor-activated receptor activity
    GO:0036400 ! short neuropeptide F receptor activity
    GO:0036401 ! pyrokinin receptor activity
    GO:0038021 ! leptin receptor activity
    GO:0038022 ! G-protein coupled olfactory receptor activity
    GO:0038025 ! reelin receptor activity
    GO:0038046 ! enkephalin receptor activity
    GO:0038048 ! dynorphin receptor activity
    GO:0038054 ! G-protein coupled estrogen receptor activity
    GO:0038058 ! TNFSF11 receptor activity
    GO:0038062 ! protein tyrosine kinase collagen receptor activity
    GO:0038064 ! collagen receptor activity
    GO:0038117 ! C-C motif chemokine 19 receptor activity
    GO:0038121 ! C-C motif chemokine 21 receptor activity
    GO:0038122 ! C-C motif chemokine 5 receptor activity
    GO:0038131 ! neuregulin receptor activity
    GO:0038147 ! C-X-C motif chemokine 12 receptor activity
    GO:0038164 ! thrombopoietin receptor activity
    GO:0038174 ! interleukin-17A receptor activity
    GO:0038181 ! bile acid receptor activity
    GO:0038182 ! G-protein coupled bile acid receptor activity
    GO:0038186 ! lithocholic acid receptor activity
    GO:0038187 ! pattern recognition receptor activity
    GO:0039508 ! suppression by virus of host receptor activity
    GO:0039509 ! suppression by virus of host pattern recognition receptor activity
    GO:0039511 ! suppression by virus of host interferon receptor activity
    GO:0042020 ! interleukin-23 receptor activity
    GO:0042071 ! leucokinin receptor activity
    GO:0042263 ! neuropeptide F receptor activity
    GO:0042654 ! ecdysis-triggering hormone receptor activity
    GO:0042813 ! Wnt-activated receptor activity
    GO:0044508 ! glucagon-like peptide 1 receptor activity
    GO:0045028 ! G-protein coupled purinergic nucleotide receptor activity
    GO:0045029 ! UDP-activated nucleotide receptor activity
    GO:0045030 ! UTP-activated nucleotide receptor activity
    GO:0045031 ! ATP-activated nucleotide receptor activity
    GO:0045032 ! ADP-activated nucleotide receptor activity
    GO:0045125 ! bioactive lipid receptor activity
    GO:0050785 ! advanced glycation end-product receptor activity
    GO:0070053 ! thrombospondin receptor activity
    GO:0070287 ! ferritin receptor activity
    GO:0070380 ! high mobility group box 1 receptor activity
    GO:0070506 ! high-density lipoprotein particle receptor activity
    GO:0070747 ! interleukin-35 receptor activity
    GO:0071553 ! G-protein coupled pyrimidinergic nucleotide receptor activity
    GO:0097003 ! adipokinetic hormone receptor activity

Chris Mungall added a comment - 12-Dec-13 13:21

Not sure what PRO's plans are to add insect proteins like leucokinin
Rebecca Foulger made changes - 13-Jan-14 11:51
Field 	Original Value 	New Value
Assignee 	Rebecca Foulger [ rfoulger ] 	David Osumi-Sutherland [ davidos ]
Chris Mungall added a comment - 06-Feb-15 11:35

Discussed on http://wiki.geneontology.org/index.php/Ontology_meeting_2015-02-05#TermGenie_templates_for_receptor_activity

Harold will look into missing equiv axioms, e.g. for interleukin-12
Chris Mungall made changes - 06-Feb-15 16:35
Assignee 	David Osumi-Sutherland [ davidos ] 	Harold Drabkin [ harold.drabkin@jax.org ]

**Comment by cmungall** [comment]
Would you be able to take this one over Harold? Most of this is working with PR

**Comment by cmungall** [comment]
```
GO:0000155 ! phosphorelay sensor kinase activity
GO:0001566 ! non-kinase phorbol ester receptor activity
GO:0001571 ! non-tyrosine kinase fibroblast growth factor receptor activity
GO:0001586 ! Gi/o-coupled serotonin receptor activity
GO:0001587 ! Gq/11-coupled serotonin receptor activity
GO:0001588 ! dopamine neurotransmitter receptor activity, coupled via Gs
GO:0001591 ! dopamine neurotransmitter receptor activity, coupled via Gi/Go
GO:0001594 ! trace-amine receptor activity
GO:0001596 ! angiotensin type I receptor activity
GO:0001604 ! urotensin II receptor activity
GO:0001605 ! adrenomedullin receptor activity
GO:0001607 ! neuromedin U receptor activity
GO:0001608 ! G-protein coupled nucleotide receptor activity
GO:0001609 ! G-protein coupled adenosine receptor activity
GO:0001614 ! purinergic nucleotide receptor activity
GO:0001618 ! virus receptor activity
GO:0001631 ! cysteinyl leukotriene receptor activity
GO:0001635 ! calcitonin gene-related peptide receptor activity
GO:0001637 ! G-protein coupled chemoattractant receptor activity
GO:0001639 ! PLC activating G-protein coupled glutamate receptor activity
GO:0001640 ! adenylate cyclase inhibiting G-protein coupled glutamate receptor activity
GO:0001641 ! group II metabotropic glutamate receptor activity
GO:0001642 ! group III metabotropic glutamate receptor activity
GO:0001647 ! G-protein coupled cytokinin receptor activity
GO:0001648 ! proteinase activated receptor activity
GO:0001792 ! polymeric immunoglobulin receptor activity
GO:0001793 ! IgM receptor activity
GO:0001847 ! opsonin receptor activity
GO:0001857 ! complement component C1q receptor activity
GO:0001858 ! complement component iC3b receptor activity
GO:0001859 ! complement component C3dg receptor activity
GO:0001860 ! complement component C3d receptor activity
GO:0001861 ! complement component C4b receptor activity
GO:0001863 ! collectin receptor activity
GO:0002170 ! high-affinity IgA receptor activity
GO:0002171 ! low-affinity IgA receptor activity
GO:0002172 ! high-affinity IgM receptor activity
GO:0002173 ! low-affinity IgM receptor activity
GO:0004675 ! transmembrane receptor protein serine/threonine kinase activity
GO:0004714 ! transmembrane receptor protein tyrosine kinase activity
GO:0004873 ! asialoglycoprotein receptor activity
GO:0004874 ! aryl hydrocarbon receptor activity
GO:0004875 ! complement receptor activity
GO:0004876 ! complement component C3a receptor activity
GO:0004877 ! complement component C3b receptor activity
GO:0004878 ! complement component C5a receptor activity
GO:0004886 ! 9-cis retinoic acid receptor activity
GO:0004888 ! transmembrane signaling receptor activity
GO:0004890 ! GABA-A receptor activity
GO:0004896 ! cytokine receptor activity
GO:0004904 ! interferon receptor activity
GO:0004905 ! type I interferon receptor activity
GO:0004906 ! interferon-gamma receptor activity
GO:0004909 ! interleukin-1, Type I, activating receptor activity
GO:0004910 ! interleukin-1, Type II, blocking receptor activity
GO:0004930 ! G-protein coupled receptor activity
GO:0004932 ! mating-type factor pheromone receptor activity
GO:0004933 ! mating-type a-factor pheromone receptor activity
GO:0004934 ! mating-type alpha-factor pheromone receptor activity
GO:0004935 ! adrenergic receptor activity
GO:0004936 ! alpha-adrenergic receptor activity
GO:0004937 ! alpha1-adrenergic receptor activity
GO:0004938 ! alpha2-adrenergic receptor activity
GO:0004939 ! beta-adrenergic receptor activity
GO:0004940 ! beta1-adrenergic receptor activity
GO:0004941 ! beta2-adrenergic receptor activity
GO:0004942 ! anaphylatoxin receptor activity
GO:0004943 ! C3a anaphylatoxin receptor activity
GO:0004944 ! C5a anaphylatoxin receptor activity
GO:0004945 ! angiotensin type II receptor activity
GO:0004946 ! bombesin receptor activity
GO:0004950 ! chemokine receptor activity
GO:0004952 ! dopamine neurotransmitter receptor activity
GO:0004962 ! endothelin receptor activity
GO:0004963 ! follicle-stimulating hormone receptor activity
GO:0004964 ! luteinizing hormone receptor activity
GO:0004965 ! G-protein coupled GABA receptor activity
GO:0004968 ! gonadotropin-releasing hormone receptor activity
GO:0004970 ! ionotropic glutamate receptor activity
GO:0004972 ! NMDA glutamate receptor activity
GO:0004977 ! melanocortin receptor activity
GO:0004980 ! melanocyte-stimulating hormone receptor activity
GO:0004982 ! N-formyl peptide receptor activity
GO:0004984 ! olfactory receptor activity
GO:0004985 ! opioid receptor activity
GO:0004995 ! tachykinin receptor activity
GO:0004997 ! thyrotropin-releasing hormone receptor activity
GO:0004999 ! vasoactive intestinal polypeptide receptor activity
GO:0005001 ! transmembrane receptor protein tyrosine phosphatase activity
GO:0005003 ! ephrin receptor activity
GO:0005004 ! GPI-linked ephrin receptor activity
GO:0005005 ! transmembrane-ephrin receptor activity
GO:0005007 ! fibroblast growth factor-activated receptor activity
GO:0005010 ! insulin-like growth factor-activated receptor activity
GO:0005011 ! macrophage colony-stimulating factor receptor activity
GO:0005017 ! platelet-derived growth factor-activated receptor activity
GO:0005018 ! platelet-derived growth factor alpha-receptor activity
GO:0005019 ! platelet-derived growth factor beta-receptor activity
GO:0005021 ! vascular endothelial growth factor-activated receptor activity
GO:0005025 ! transforming growth factor beta receptor activity, type I
GO:0005026 ! transforming growth factor beta receptor activity, type II
GO:0005030 ! neurotrophin receptor activity
GO:0005031 ! tumor necrosis factor-activated receptor activity
GO:0005034 ! osmosensor activity
GO:0005035 ! death receptor activity
GO:0005040 ! decoy death receptor activity
GO:0005042 ! netrin receptor activity
GO:0005044 ! scavenger receptor activity
GO:0005055 ! laminin receptor activity
GO:0005056 ! tiggrin receptor activity
GO:0005220 ! inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity
GO:0008020 ! G-protein coupled photoreceptor activity
GO:0008029 ! pentraxin receptor activity
GO:0008030 ! neuronal pentraxin receptor activity
GO:0008036 ! diuretic hormone receptor activity
GO:0008158 ! hedgehog receptor activity
GO:0008188 ! neuropeptide receptor activity
GO:0008196 ! vitellogenin receptor activity
GO:0008227 ! G-protein coupled amine receptor activity
GO:0008261 ! allatostatin receptor activity
GO:0008288 ! boss receptor activity
GO:0008313 ! gurken-activated receptor activity
GO:0008329 ! signaling pattern recognition receptor activity
GO:0008528 ! G-protein coupled peptide receptor activity
GO:0009784 ! transmembrane receptor histidine kinase activity
GO:0009881 ! photoreceptor activity
GO:0009882 ! blue light photoreceptor activity
GO:0009883 ! red or far-red light photoreceptor activity
GO:0009885 ! transmembrane histidine kinase cytokinin receptor activity
GO:0010465 ! nerve growth factor receptor activity
GO:0015026 ! coreceptor activity
GO:0015052 ! beta3-adrenergic receptor activity
GO:0015056 ! corticotrophin-releasing factor receptor activity
GO:0015057 ! thrombin receptor activity
GO:0015065 ! uridine nucleotide receptor activity
GO:0015277 ! kainate selective glutamate receptor activity
GO:0016361 ! activin receptor activity, type I
GO:0016362 ! activin receptor activity, type II
GO:0016492 ! G-protein coupled neurotensin receptor activity
GO:0016493 ! C-C chemokine receptor activity
GO:0016494 ! C-X-C chemokine receptor activity
GO:0016495 ! C-X3-C chemokine receptor activity
GO:0016496 ! substance P receptor activity
GO:0016497 ! substance K receptor activity
GO:0016498 ! neuromedin K receptor activity
GO:0016500 ! protein-hormone receptor activity
GO:0016517 ! interleukin-12 receptor activity
GO:0016518 ! interleukin-14 receptor activity
GO:0016519 ! gastric inhibitory peptide receptor activity
GO:0016524 ! latrotoxin receptor activity
GO:0016907 ! G-protein coupled acetylcholine receptor activity
GO:0016941 ! natriuretic peptide receptor activity
GO:0016964 ! alpha-2 macroglobulin receptor activity
GO:0017002 ! activin-activated receptor activity
GO:0019198 ! transmembrane receptor protein phosphatase activity
GO:0019199 ! transmembrane receptor protein kinase activity
GO:0019763 ! immunoglobulin receptor activity
GO:0019766 ! IgA receptor activity
GO:0019767 ! IgE receptor activity
GO:0019768 ! high-affinity IgE receptor activity
GO:0019769 ! low-affinity IgE receptor activity
GO:0019770 ! IgG receptor activity
GO:0019771 ! high-affinity IgG receptor activity
GO:0019772 ! low-affinity IgG receptor activity
GO:0030107 ! HLA-A specific inhibitory MHC class I receptor activity
GO:0030108 ! HLA-A specific activating MHC class I receptor activity
GO:0030109 ! HLA-B specific inhibitory MHC class I receptor activity
GO:0030110 ! HLA-C specific inhibitory MHC class I receptor activity
GO:0030229 ! very-low-density lipoprotein particle receptor activity
GO:0030273 ! melanin-concentrating hormone receptor activity
GO:0030373 ! high molecular weight B cell growth factor receptor activity
GO:0030379 ! neurotensin receptor activity, non-G-protein coupled
GO:0031516 ! far-red light photoreceptor activity
GO:0031517 ! red light photoreceptor activity
GO:0032393 ! MHC class I receptor activity
GO:0032394 ! MHC class Ib receptor activity
GO:0032395 ! MHC class II receptor activity
GO:0032396 ! inhibitory MHC class I receptor activity
GO:0032397 ! activating MHC class I receptor activity
GO:0033038 ! bitter taste receptor activity
GO:0033039 ! salty taste receptor activity
GO:0033040 ! sour taste receptor activity
GO:0033041 ! sweet taste receptor activity
GO:0033042 ! umami taste receptor activity
GO:0034348 ! type III interferon receptor activity
GO:0035013 ! myosuppressin receptor activity
GO:0035236 ! proctolin receptor activity
GO:0035237 ! corazonin receptor activity
GO:0035472 ! choriogonadotropin hormone receptor activity
GO:0035586 ! purinergic receptor activity
GO:0036326 ! VEGF-A-activated receptor activity
GO:0036327 ! VEGF-B-activated receptor activity
GO:0036328 ! VEGF-C-activated receptor activity
GO:0036329 ! VEGF-D-activated receptor activity
GO:0036330 ! VEGF-E-activated receptor activity
GO:0036332 ! placental growth factor-activated receptor activity
GO:0036400 ! short neuropeptide F receptor activity
GO:0036401 ! pyrokinin receptor activity
GO:0036463 ! TRAIL receptor activity
GO:0036505 ! prosaposin receptor activity
GO:0038021 ! leptin receptor activity
GO:0038022 ! G-protein coupled olfactory receptor activity
GO:0038025 ! reelin receptor activity
GO:0038046 ! enkephalin receptor activity
GO:0038048 ! dynorphin receptor activity
GO:0038049 ! transcription factor activity, ligand-activated RNA polymerase II transcription factor binding
GO:0038050 ! RNA polymerase II transcription factor activity, glucocorticoid-activated sequence-specific DNA binding
GO:0038051 ! glucocorticoid-activated RNA polymerase II transcription factor binding transcription factor activity
GO:0038052 ! RNA polymerase II transcription factor activity, estrogen-activated sequence-specific DNA binding
GO:0038053 ! transcription factor activity, estrogen-activated RNA polymerase II transcription factor binding
GO:0038054 ! G-protein coupled estrogen receptor activity
GO:0038058 ! TNFSF11 receptor activity
GO:0038062 ! protein tyrosine kinase collagen receptor activity
GO:0038064 ! collagen receptor activity
GO:0038117 ! C-C motif chemokine 19 receptor activity
GO:0038121 ! C-C motif chemokine 21 receptor activity
GO:0038122 ! C-C motif chemokine 5 receptor activity
GO:0038131 ! neuregulin receptor activity
GO:0038147 ! C-X-C motif chemokine 12 receptor activity
GO:0038164 ! thrombopoietin receptor activity
GO:0038174 ! interleukin-17A receptor activity
GO:0038181 ! bile acid receptor activity
GO:0038182 ! G-protein coupled bile acid receptor activity
GO:0038186 ! lithocholic acid receptor activity
GO:0038187 ! pattern recognition receptor activity
GO:0038200 ! ethylene receptor histidine kinase activity
GO:0042020 ! interleukin-23 receptor activity
GO:0042071 ! leucokinin receptor activity
GO:0042263 ! neuropeptide F receptor activity
GO:0042654 ! ecdysis-triggering hormone receptor activity
GO:0042813 ! Wnt-activated receptor activity
GO:0044508 ! glucagon-like peptide 1 receptor activity
GO:0045028 ! G-protein coupled purinergic nucleotide receptor activity
GO:0045029 ! UDP-activated nucleotide receptor activity
GO:0045030 ! UTP-activated nucleotide receptor activity
GO:0045031 ! ATP-activated adenosine receptor activity
GO:0045032 ! ADP-activated adenosine receptor activity
GO:0045125 ! bioactive lipid receptor activity
GO:0050785 ! advanced glycation end-product receptor activity
GO:0061714 ! folic acid receptor activity
GO:0070053 ! thrombospondin receptor activity
GO:0070123 ! transforming growth factor beta receptor activity, type III
GO:0070287 ! ferritin receptor activity
GO:0070380 ! high mobility group box 1 receptor activity
GO:0070506 ! high-density lipoprotein particle receptor activity
GO:0070747 ! interleukin-35 receptor activity
GO:0071553 ! G-protein coupled pyrimidinergic nucleotide receptor activity
GO:0097003 ! adipokinetic hormone receptor activity
GO:0097642 ! calcitonin family receptor activity
GO:0097643 ! amylin receptor activity
GO:0098821 ! BMP receptor activity
GO:1990272 ! anti-Mullerian hormone receptor activity
GO:1990576 ! G-protein coupled glucose receptor activity
GO:1990595 ! mast cell secretagogue receptor activity
GO:1990725 ! cord factor receptor activity
GO:1990760 ! osmolarity-sensing cation channel activity
```

**Comment by hdrabkin** [comment]
I was working on it a little; mostly I was finding that there was a ref to PRO for the binding term that many of the receptors had a logical def with.
I have the list somwhere;
I was having trouble with some of the interleukins due to differences in structure
--
Harold

**Comment by paolaroncaglia** [comment]
Hi Harold,
Please assign this to yourself, thanks.
Paola

**Comment by hdrabkin** [comment]
On the matter of Interleukin-12 receptor activity. 
I am having a PR: id made for IL-12 complex, because the active form of IL-12 is a hetero-dimer of IL-12A and IL-12B. The term name however is interleukin-12 complex , not IL X like it is for the monomeric interleukins.  Is this going to be a problem? This is going to happen for a few of the interleukins which are composed of more than one chain.

**Comment by cmungall** [comment]
Doesn't matter for machines, but I favor keeping the terminology aligned

If this is deemed undesirable, then a SYSTEMATIC_SYNONYM

**Comment by hdrabkin** [comment]
I did put in a synonym of IL-12 (no complex);

**Comment by ValWood** [comment]
Is this still current? noo action since 2015

**Comment by pgaudet** [comment]
Probably not. thanks for checking.
