### ISSUE TITLE
Create template for receptors based on their ligand (Jira GO-240

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#12136]
This was Jira ticket GO-240
Create template for receptors based on their ligand. The ligand would be either:
1) A chemicals in ChEBI
2) A protein in PRO
E.g.
in ontology/editors/gene_ontology_xp_write.obo
[Term]
id: GO:0001565 ! phorbol ester receptor activity
intersection_of: GO:0004872 ! receptor activity
intersection_of: has_input CHEBI:37532 ! phorbol ester

in ontology/extensions/x-mf-protein.obo
[Term]
id: GO:0001532 ! interleukin-21 receptor activity
intersection_of: GO:0004872 ! receptor activity
intersection_of: starts_with_has_input PR:000001382 ! interleukin-21

Q: need to standardize:
intersection_of: has_input
OR
intersection_of: starts_with_has_input

Sub-Tasks
1.  Verify that existing XPs are in place for receptor activities   Sub-task    Reported    Harold Drabkin  

Actions
2.  Create TermGenie template   Sub-task    Reported    David Osumi-Sutherland  

Actions
3.  Test TermGenie Template     Sub-task    Reported    David Osumi-Sutherland  

Actions
4.  Announce TermGenie Template     Sub-task    Reported    David Osumi-Sutherland  

Actions

Activity

---

**Comment by hdrabkin** [comment]
Tanya Berardini added a comment - 21-Aug-14 11:57

Ontology design patterning for ChEBI version exists.

Look at potential mapping between PRO and GO.
Chris will open SF issue for Harold to look at this.
Paola Roncaglia added a comment - 09-Feb-15 11:23

Notes from editors call held on Feb 5th 2015:
"AI: Harold will do a first pass and try to fill in as many XPs as he can.
WIll then report back. Hold off on template. But could go ahead if we get a batch of requests."
David Osumi-Sutherland added a comment - 18-Jun-15 12:20

postpone until we have a better formalisation for receptor activity. This could come in through Paul's MF refactor.

    Comment

People

    Assignee:
        Harold Drabkin 

    Reporter:
        Rebecca Foulger 

    Watchers:
        5 Start watching this issue 

Dates

    Created:
        09-Dec-13 08:18 

    Updated:
        18-Jun-15 12:20

**Comment by paolaroncaglia** [comment]
Harold, could you please assign this ticket to yourself?
I can't do it, not sure why.
Thanks,
Paola

**Comment by hdrabkin** [comment]
hmm; I can't see to do it either; I see Assignee to the right but it's grayed out.

**Comment by dosumis** [comment]
Hi Harold,  You have a pending invitation to joint the gene ontology editors group on GitHub.  Accept that and you should have all the permissions you need on this repo.

Cheers,
David

**Comment by dosumis** [comment]
has_input won't work. Receptor activities typically have other inputs
besides the ligand:  inputs to the effector activity (kinase, channel, TF
activity).

Some cases where this could cause problems:  ATP can be a ligand and an
input for a kinase effector activity.  Some ions act as ligands for some
ion channels and cargo for others.

Possible solutions:

* create a has_ligand relation
* use a nested class expression pattern that can capture effector activity
and its relationship to ligand binding:
'receptor activity' and has_part some (\<effector activity\> that
regulated_by some (binding that has_input some \<ligand\>))

The second approach steps outside OBO.  Might not be entirely safe either.
I suspect that some thing which bind and regulate effector activities are
not considered ligands.

**Comment by hdrabkin** [comment]
While looking at some of these I noticed already that some had a has_input to something

Example:
GO:0004920 interleukin-10 receptor activity,  has input interleukin-10 (PR:000001471)
But I thought some of them also had has_part or something to the binding, like interleukin-10 binding (this one doesn't but I could swear some did
--
Harold

**Comment by cmungall** [comment]
@dosumis what about 'has substrate' 

shall we add receptor activity to the has-input doc? https://docs.google.com/document/d/1QMhs9J-P_q3o_rDh-IX4ZEnz0PnXrzLRVkI3vvz8NEQ/edit# 

how does the MF refactor play into this?

**Comment by cmungall** [comment]
@dosumis - the original version of these axioms used a shortcut relation that was similar to your nested expression, see the imported JIRA ticket here: #12137

Maybe these two tickets should be merged into a new ticket in the patterns repo? Although it's tied to the MF refactor too

**Comment by hdrabkin** [comment]
@vanaukenk , what do you think?

**Comment by ValWood** [comment]
removed label term genie, added label design patter decision and waiting for feedback (@vanaukenk )

**Comment by pgaudet** [comment]
Newer discussion is here #16972

I'll close this as a duplicate.
