### ISSUE TITLE
ntr : mitotic chromosome  arm/centromere condensation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12135]
ntr mitotic chromosome  arm condensation
ntr mitotic chromosome  condensation at kinetochore

Might seem a bit crazy, but really cool paper which demonstrates that these are separable processes and different genes in each pathway....
 
Condensin association with histone H2A shapes mitotic chromosomes.
Tada K, Susumu H, Sakuno T, Watanabe Y.
Nature. 2011 Jun 1;474(7352):477-83. doi: 10.1038/nature10179.
PMID: 21633354

**Comment by ValWood** [comment]
![2163354](https://cloud.githubusercontent.com/assets/7359272/10821676/7c55b72a-7e4b-11e5-9206-156746a31126.jpg)

**Comment by ValWood** [comment]
I think I can do this via TGFF, will do then we might be able to get through for update.

**Comment by mah11** [comment]
It's the chromosome (DNA, histones, etc) rather than the kinetochore that condenses, so I think it would be better to use "centromere" in the second term name, and "kinetochore" in a synonym.

**Comment by ValWood** [comment]
GO:1990892 Label: mitotic chromosome arm condensation
GO:1990893 Label: mitotic chromosome centromere condensation

**Comment by ukemi** [comment]
Val,

Did you do this via TGFF?

-D

**Comment by ValWood** [comment]
yep
