### ISSUE TITLE
query medial cortical node

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12131]
Is defined as a complex, but I don't think it should be.
it is a cellular component which we need to be able to annotate to.... We have tons of experiments and papers which refer to these  as cytokinetic ring precursors...

medial cortical node
Definition
A protein complex that contains the mid1, cdr2, wee1, klp8, and blt1 proteins, and is involved in contractile ring localization. Medial cortical node complexes appear as cortical dots in the middle of the cell during interphase, and function to recruit other ring components in early mitosis.
Synonyms	
mid1p medial cortical dot
midsome

===
Illustrated below  in time series >0  before the cytokinetic ring forms

**Comment by ValWood** [comment]
![cortical_node](https://cloud.githubusercontent.com/assets/7359272/10795108/187590ec-7d90-11e5-9f26-127f65ceaeac.jpg)

**Comment by paolaroncaglia** [comment]
Hi Val,

I’d be happy to move ‘medial cortical node’ out from under ‘protein complex’, but I’m not sure what other parent we could give it other than as part of something. You write “We have tons of experiments and papers which refer to these as cytokinetic ring precursors”, so I looked at the parentage of ‘actomyosin contractile ring’ and ‘contractile ring’ (both of which have ‘cytokinetic ring’ as a related synonym), but that didn’t help. Other ‘dots’ we have in GO, such as ‘Mei2 nuclear dot complex’, we managed to make is_a ‘ribonucleoprotein complex’ but I have no idea if medial cortical nodes are made of anything other than proteins. Looking at annotations doesn’t help either, all manual ones are yours. Would you have any suggestions at all based on your readings? 

Thanks,

Paola

**Comment by ValWood** [comment]
GO:0032155 cell division site part
I think. 
It isn't part of the actin ring as it precedes it.

I feel uncomfortable with protein complex because even though it is protein, I don't know if they are monomers, complexes, or multiple complexes...we just don't know yet...

**Comment by paolaroncaglia** [comment]
Hi Val,

I removed the link to protein complex, and redefined accordingly.

Thanks,
Paola
