### ISSUE TITLE
There is no connection between reproduction and reproductive process

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12148]
Why not 'reproductive process' equivalentTo biological_process that part_of some reproduction?

**Comment by cmungall** [comment]
Deleted last year http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0022414#term=history

anyone know why?

**Comment by cmungall** [comment]
so long as there are two terms they should be linked

although the text def is supervague

```
id: GO:0022414
name: reproductive process
namespace: biological_process
def: "A biological process that directly contributes to the process of producing new individuals by one or two organisms. The new individuals inherit some proportion of their genetic material from the parent or parents." [GOC:dph, GOC:isa_complete]
```

contributes-to is not part-of... and as you I know I really dislike the practice of expanding the differentium term definition into the definition of the child. Why not just say "reproduction". It's like we're trying to trick the reader into not noticing there is a nearly identical term

**Comment by cmungall** [comment]
I don't think anyone would be sad if we got rid of a bunch of those GOC:isa_complete terms. It's fine if classes are is_a root, we don't need fake groupings.

Any `ROOT and part_of some X` is suspect

**Comment by cmungall** [comment]
The original was 'developmental process' and part of reproduction

**Comment by dosumis** [comment]
We have 'developmental process involved in reproduction'  Was unaxiomatised, but from ETINE is looks like it once had

EquivalentTo: 'developmental process' and part of reproduction

See:

https://github.com/geneontology/go-ontology/issues/12150

**Comment by cmungall** [comment]
Yes it did

**Comment by dosumis** [comment]
Added back the axiom.

Finds 52 new direct subclasses.  These all look reasonable to me.

'DNA methylation involved in gamete generation'
'DNA recombinase assembly involved in gene conversion at mating-type locus'
'acrosome matrix dispersal'
'activation of meiosis involved in egg activation'
'adaptation of signaling pathway by response to pheromone involved in conjugation with cellular fusion'
'border follicle cell delamination'
'budding cell bud growth'
'cell adhesion involved in prostatic bud elongation'
'cell wall macromolecule catabolic process involved in cytogamy'
'cell wall organization involved in conjugation with cellular fusion'
'chromosome localization to nuclear envelope involved in homologous chromosome segregation'
'detection of stimulus involved in meiotic cell cycle checkpoint'
'detection of stimulus involved in meiotic spindle checkpoint'
'establishment of oocyte nucleus localization involved in oocyte dorsal/ventral axis specification'
'female pronucleus assembly'
'fertilization, exchange of chromosomal proteins'
'fusome organization'
'gene conversion at mating-type locus'
'gene conversion at mating-type locus, DNA double-strand break formation'
'gene conversion at mating-type locus, DNA double-strand break processing'
'gene conversion at mating-type locus, DNA repair synthesis'
'gene conversion at mating-type locus, termination of copy-synthesis'
'heteroduplex formation involved in gene conversion at mating-type locus'
'karyogamy involved in conjugation with cellular fusion'
'mesenchymal smoothened signaling pathway involved in prostate gland development'
'maintenance of floral organ identity'
'male pronucleus assembly'
'mucilage metabolic process involved in seed coat development'
'negative regulation of progesterone biosynthesis involved in luteolysis'
'nurse cell nucleus anchoring'
'oocyte localization involved in germarium-derived egg chamber formation'
'peptide mating pheromone maturation involved in conjugation with cellular fusion'
'peptidyl-serine phosphorylation involved in acrosome reaction'
'photoperiodism, flowering'
'pole plasm RNA localization'
'pole plasm protein localization'
'pollen tube guidance'
'positive regulation of sperm motility involved in capacitation'
'positive regulation of transcription involved in egg activation'
'prevention of polyspermy'
'pronuclear fusion'
'pronuclear migration'
'protein localization to meiotic spindle pole body'
'regulation of transcription during meiosis'
'regulation of transcription from RNA polymerase II promoter involved in spermatogenesis'
'removal of nonhomologous ends'
'response to pheromone involved in conjugation with cellular fusion'
'seed oilbody biogenesis'
'signal transduction involved in conjugation with cellular fusion'
'sperm chromatin decondensation'
'strand invasion involved in gene conversion at mating-type locus'
'transmembrane receptor protein serine/threonine kinase signaling pathway involved in floral organ abscission'

**Comment by ValWood** [comment]
'cept
removal of nonhomologous ends'  (TPV)
shouldn't be a child of 
GO:0007534 gene conversion at mating-type locus

needs 
removal of nonhomologous ends involved in gene conversion at mating-type locus etc?

I'm not evven *totally* sure that matingtye switching shouldbe considered a 'reproductive' process. as mating type switching can occu independently of mating...I would need to check that with @Antonialock and @mah11

**Comment by dosumis** [comment]
OK.  Can you make a new ticket for this?

Ta,
David

**Comment by ValWood** [comment]
'cept
removal of nonhomologous ends' (TPV)
shouldn't be a child of 
GO:0007534 gene conversion at mating-type locus

needs 
removal of nonhomologous ends involved in gene conversion at mating-type locus etc?

I'm not evven totally sure that matingtye switching shouldbe considered a 'reproductive' process. as mating type switching can occu independently of mating...I would need to check that with @Antonialock and @mah11

**Comment by ValWood** [comment]
now in issues/12161
