### ISSUE TITLE
songbird Area X

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#12142]
Request for basal ganglion(UBERON:0002420) to include Area X as child term. 
definition: Area X is a basal ganglia nucleus of songbirds

only_in Passeriformes Taxon ID 9126

PMID: 18398825
PMID: 15116398

GOC:mr

**Comment by tberardini** [comment]
Wrong github tracker?  If you're requesting an anatomical structure, please use: https://github.com/obophenotype/uberon/issues

Or are you requesting a GO cellular component term?
