### ISSUE TITLE
Endosomal transport / results_in_transport_to_from_or_mediated_by

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12149]
def: "The directed movement of substances into, out of, or mediated by an endosome, a membrane-bounded organelle that carries materials newly ingested by endocytosis. It passes many of the materials to lysosomes for degradation."
EquivalentTo:
transport and (results\_in\_transport\_to\_from\_or\_mediated\_by some endosome)

This is the *only* use of 'results\_in\_transport\_to\_from\_or\_mediated\_by', which is a leaf-node relation.  There is therefore no infered classification under this term (although there are a bunch of things that used to be inferred subclasses (see end)).

This could be fixed by moving this relation under 
results\_in\_transport\_to\_from\_or\_in  AND mediated_by*

BUT - this would be a somewhat hacky.  It would only be safe in patterns with transport in the range.

(*mediated_by = has_agent = has_active_participant?)

ETINES:
GO:0006895 'Golgi to endosome transport' GO:0016197 'endosomal transport'
GO:0008333 'endosome to lysosome transport' GO:0016197 'endosomal transport'
GO:0043485 'endosome to pigment granule transport' GO:0016197 'endosomal transport'
GO:0045022 'early endosome to late endosome transport' GO:0016197 'endosomal transport'
GO:0045324 'late endosome to vacuole transport' GO:0016197 'endosomal transport'
GO:0048227 'plasma membrane to endosome transport' GO:0016197 'endosomal transport'
GO:0061502 'early endosome to recycling endosome transport' GO:0016197 'endosomal transport'
GO:0006895 'Golgi to endosome transport' GO:0016197 'endosomal transport'
GO:0008333 'endosome to lysosome transport' GO:0016197 'endosomal transport'
GO:0043485 'endosome to pigment granule transport' GO:0016197 'endosomal transport'
GO:0045022 'early endosome to late endosome transport' GO:0016197 'endosomal transport'
GO:0045324 'late endosome to vacuole transport' GO:0016197 'endosomal transport'
GO:0048227 'plasma membrane to endosome transport' GO:0016197 'endosomal transport'
GO:0061502 'early endosome to recycling endosome transport' GO:0016197 'endosomal transport'

**Comment by cmungall** [comment]
Such a vague grouping should at least have a do_not_annotate tag

67 direct annotations, most annoying.

**Comment by dosumis** [comment]
> Such a vague grouping should at least have a do_not_annotate tag

Possibly - but I suspect the grouping reflects common usage in this case.

**Comment by dosumis** [comment]
OTOH: 

![image](https://cloud.githubusercontent.com/assets/112839/11002536/38392d28-84a5-11e5-8571-d259f8c2b8e1.png)

Perhaps we should just switch to results_in_transport_to_from_or_in and modify the def accordingly.  Should check papers annotated to first though.

**Comment by ValWood** [comment]
Sometimes the assays aren't really good enough to say from where to where. We only feel safe with "endosomal transport" as we know it is stuffed. For instance you get accumulation  in the of a vacuole of marker which is usually exported. We don't know absolutely   which stage the problem affects....

**Comment by dosumis** [comment]
@ValWood - Is results_in_transport_to_from_or_in sufficient - skipping the mediated_by ?

=>

label: endosomal transport
def: "The directed movement of substances into, out of, or in an endosome, a membrane-bounded organelle that carries materials newly ingested by endocytosis. It passes many of the materials to lysosomes for degradation."
EquivalentTo:
transport and (results_in_transport_to_from_or_in some endosome)

**Comment by ValWood** [comment]
Yes I think so. I'm not even sure transport "within the endosome". I don't think there is any "within" endosome transport process. Only into or out  of....

**Comment by dosumis** [comment]
Fixed.  (I've kept the general term valid for annotation).
