### ISSUE TITLE
Clarify the meaning of positive/negative regulation of cellular protein localization

### ISSUE THREAD

**Issue by esperetta** [geneontology/go-ontology#12144]
Dear Editors, 

Would it be possible to better explain the meaning of positive/negative regulation of cellular protein localization (respectively GO:1903829, GO:1903828)? 

I understand the necessity of a regulation term, but I don't think that the above terms provide meaningful information as they are.

Many thanks, 

Elena Speretta

**Comment by tberardini** [comment]
Dear Elena,

Thanks for bringing this up.  We can add an explanation of what cellular protein localization is, for example, for the positive regulation term, the new definition would be:

Any process that activates or increases the frequency, rate or extent of cellular protein localization.
Cellular protein localization is any process in which a protein is transported to, and/or maintained in, a specific location and encompasses movement within the cell, from within the cell to the cell surface, or from one location to another at the surface of a cell.

Would this be helpful?

Thanks,

Tanya

**Comment by esperetta** [comment]
Dear Tanya, 

thanks for looking into this. Yes, I agree with you that this definition will make the terms less ambiguous and would actually cover a lot of situations in which children of these terms are not yet listed. 

Many thanks,

Elena

**Comment by tberardini** [comment]
Added the sentence to all the regulation terms.
