### ISSUE TITLE
developmental process involved in reproduction - ETINES

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12150]
A large number of terms are no longer inferred to be subclasses of 'developmental process involved in reproduction' (see list below).  

The obvious fix is to make this term EquivalentTo: 'developmental process' that part_of some 'reproduction'.  I have added this.  Making the ticket to keep tabs on whether it fixes ETINES and in case anyone remembers why this axoim might have been dropped in the past.

GO:0001892 'embryonic placenta development' GO:0003006 'developmental process involved in reproduction'
GO:0003006 'developmental process involved in reproduction' GO:0032502 'developmental process'
GO:0010431 'seed maturation' GO:0003006 'developmental process involved in reproduction'
GO:0030476 'ascospore wall assembly' GO:0003006 'developmental process involved in reproduction'
GO:0031321 'ascospore-type prospore assembly' GO:0003006 'developmental process involved in reproduction'
GO:0031382 'mating projection assembly' GO:0003006 'developmental process involved in reproduction'
GO:0032120 'ascospore-type prospore membrane assembly' GO:0003006 'developmental process involved in reproduction'
GO:0035848 'oviduct morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0036360 'sorocarp stalk morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0045476 'nurse cell apoptotic process' GO:0003006 'developmental process involved in reproduction'
GO:0048236 'plant-type spore development' GO:0003006 'developmental process involved in reproduction'
GO:0048624 'plantlet formation on parent plant' GO:0003006 'developmental process involved in reproduction'
GO:0060530 'smooth muscle cell differentiation involved in prostate glandular acinus development' GO:0003006 'developmental process involved in reproduction'
GO:0060669 'embryonic placenta morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0060670 'branching involved in labyrinthine layer morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0060672 'epithelial cell morphogenesis involved in placental branching' GO:0003006 'developmental process involved in reproduction'
GO:0060674 'placenta blood vessel development' GO:0003006 'developmental process involved in reproduction'
GO:0060706 'cell differentiation involved in embryonic placenta development' GO:0003006 'developmental process involved in reproduction'
GO:0060713 'labyrinthine layer morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0060714 'labyrinthine layer formation' GO:0003006 'developmental process involved in reproduction'
GO:0060742 'epithelial cell differentiation involved in prostate gland development' GO:0003006 'developmental process involved in reproduction'
GO:0060743 'epithelial cell maturation involved in prostate gland development' GO:0003006 'developmental process involved in reproduction'
GO:0060744 'mammary gland branching involved in thelarche' GO:0003006 'developmental process involved in reproduction'
GO:0071998 'ascospore release from ascus' GO:0003006 'developmental process involved in reproduction'
GO:0080112 'seed growth' GO:0003006 'developmental process involved in reproduction'
GO:0080187 'floral organ senescence' GO:0003006 'developmental process involved in reproduction'
GO:0090214 'spongiotrophoblast layer developmental growth' GO:0003006 'developmental process involved in reproduction'
GO:1990058 'fruit replum development' GO:0003006 'developmental process involved in reproduction'
GO:1990059 'fruit valve development' GO:0003006 'developmental process involved in reproduction'
GO:0001892 'embryonic placenta development' GO:0003006 'developmental process involved in reproduction'
GO:0003006 'developmental process involved in reproduction' GO:0032502 'developmental process'
GO:0010431 'seed maturation' GO:0003006 'developmental process involved in reproduction'
GO:0030476 'ascospore wall assembly' GO:0003006 'developmental process involved in reproduction'
GO:0031321 'ascospore-type prospore assembly' GO:0003006 'developmental process involved in reproduction'
GO:0031382 'mating projection assembly' GO:0003006 'developmental process involved in reproduction'
GO:0032120 'ascospore-type prospore membrane assembly' GO:0003006 'developmental process involved in reproduction'
GO:0035848 'oviduct morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0036360 'sorocarp stalk morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0045476 'nurse cell apoptotic process' GO:0003006 'developmental process involved in reproduction'
GO:0048236 'plant-type spore development' GO:0003006 'developmental process involved in reproduction'
GO:0048624 'plantlet formation on parent plant' GO:0003006 'developmental process involved in reproduction'
GO:0060530 'smooth muscle cell differentiation involved in prostate glandular acinus development' GO:0003006 'developmental process involved in reproduction'
GO:0060669 'embryonic placenta morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0060670 'branching involved in labyrinthine layer morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0060672 'epithelial cell morphogenesis involved in placental branching' GO:0003006 'developmental process involved in reproduction'
GO:0060674 'placenta blood vessel development' GO:0003006 'developmental process involved in reproduction'
GO:0060706 'cell differentiation involved in embryonic placenta development' GO:0003006 'developmental process involved in reproduction'
GO:0060713 'labyrinthine layer morphogenesis' GO:0003006 'developmental process involved in reproduction'
GO:0060714 'labyrinthine layer formation' GO:0003006 'developmental process involved in reproduction'
GO:0060742 'epithelial cell differentiation involved in prostate gland development' GO:0003006 'developmental process involved in reproduction'
GO:0060743 'epithelial cell maturation involved in prostate gland development' GO:0003006 'developmental process involved in reproduction'
GO:0060744 'mammary gland branching involved in thelarche' GO:0003006 'developmental process involved in reproduction'
GO:0071998 'ascospore release from ascus' GO:0003006 'developmental process involved in reproduction'
GO:0080112 'seed growth' GO:0003006 'developmental process involved in reproduction'
GO:0080187 'floral organ senescence' GO:0003006 'developmental process involved in reproduction'
GO:0090214 'spongiotrophoblast layer developmental growth' GO:0003006 'developmental process involved in reproduction'
GO:1990058 'fruit replum development' GO:0003006 'developmental process involved in reproduction'
GO:1990059 'fruit valve development' GO:0003006 'developmental process involved in reproduction'

**Comment by cmungall** [comment]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0022414#term=history

Mining the history up to that point

narrowed to this range:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo?r1=19029&r2=r19085
see line 28451

**Comment by cmungall** [comment]
Found it:

```
r19044 | jlomax | 2014-07-22 05:33:47 -0700 (Tue, 22 Jul 2014) | 5 lines

Disjoints between biological phase and other biological processes.

Adding some phases to do_not_annotate subset
````

See:

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo?r1=19038&r2=r19044

Judging by the header, this was en edit made in Protege. There is no reason given in the commit for removing the equivalence axiom, and it's unrelated to other edits.

I'm going to put it down to the fact it's easy to slip in Protege and accidentally delete...

**Comment by dosumis** [comment]
Added axiom back
