### ISSUE TITLE
Is_a link to 'multi-organism process'

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12153]
It seems there is no is_a link between GO:0046597 'negative regulation of viral entry into host cell' to GO:0051704 ‘multi-organism process’. This was noticed after an annotation to GO:0046597 using a second tax ID was flagged in Protein2GO as incorrect because the term was not recognised as a descendent of multi-organism process. Protein2GO only looks for is_a links, not regulation. 

Melanie says this can be solved by adding an is_a link between GO:0043900 regulation of multi-organism process and GO:0051704 multi-organism process. 
She has tried this and reported: "I added the link in my local version of the ontology, and by querying for subclasses of "multi-organism process" I get "negative regulation of viral entry into host cell" - see attached screenshot. *However* this also generates inconsistent classes.... see for example the second screenshot, where "regulation of induction of conjugation upon nitrogen starvation is (ultimately) a single organism process, and ends up under multi-organism process with the new link, while single-organism and multi-organism processes are disjoints."

Could you please take a look to see whether an is_a link could be added somewhere between these two terms?

<img width="867" alt="screen shot 2015-11-06 at 14 30 38 1" src="https://cloud.githubusercontent.com/assets/7962316/11030471/3a75fdd2-86c6-11e5-8341-b5bc03043ead.png">
![screen shot 2015-11-06 at 14 45 03](https://cloud.githubusercontent.com/assets/7962316/11030473/3e6ad67e-86c6-11e5-9179-949cd5df86bb.png)

@mcourtot

**Comment by ukemi** [comment]
I'm not sure this link should be made. Is the regulatory process that regulates a multi-organism process necessarily a multi-organism process itself? For example if a cell down-regulated the expression of a receptor that binds a virus, that down-regulation would be a negative regulation of viral entry (a multi-organism process), but it wouldn't be a multi-organism process itself. Thoughts?

**Comment by dosumis** [comment]
@Ukemi :+1:

**Comment by ValWood** [comment]
I would agree with that. Otherwise the immune system would be a multi-organism process ;)

**Comment by ukemi** [comment]
OK. Enough to close this one I think.

**Comment by rachhuntley** [comment]
I guess we were comparing an extra tax ID annotation made with the term GO:0044871 negative regulation by host of viral glycoprotein metabolic process, which doesn't fail the checks because there is an is_a path to multi-organism process via  GO:0035821 modification of morphology or physiology of other organism. So it seemed as if you should be able to put an extra tax ID with an annotation to GO:0046597 'negative regulation of viral entry into host cell'.

Is there maybe a term that could be added as parent to GO:0046597 that could provide an is_a link to multi-organism process?

**Comment by ukemi** [comment]
This is very similar to the issue with other regulation terms, which I why I originally came up with the regulates_o_X chains. You want to qualify the regulated process, not the regulation process itself. It seems that creating a new term would just be a stop-gap for something more fundamentally lacking. I think modeling in Noctua will be able to solve this. For now, I don't think creating a new term is the right thing to do.

**Comment by ValWood** [comment]
It sounds as though these are  different  types of relationships between a virus an the host 

In the 
negative regulation by host of viral glycoprotein metabolic process
and
negative regulation of viral entry into host cell
 examples
its the host acting to attenuate the virus in some way (acts_on virus in extension)
(it seems as though the existing parentage for "negative regulation by host of viral glycoprotein metabolic process" is incorrect?)

If it really is a multi organism process like
"viral entry" where the virus used the host machinery you would use the dual taxon recording in the appropriate column?

I'm probably already out of my depth here already,  knowing little about multi organism interactions, but I presumed that it would be almost never that a human gene was annotated to multi organism process with a virus?

**Comment by mcourtot** [comment]
We looked to the terms with David OS earlier, and my suggestion was based on trying to see why Rachael's term was not a type of multi-organism process and looking at the definitions of "regulation of multi-organism process" (Any process that modulates the frequency, rate or extent of a multi-organism process, a process in which an organism has an effect on another organism of the same or different species.) and "multi organism process" (A biological process which involves another organism of the same or different species.)  In the regulation term, it is not obvious that the second part of the sentence refers to "multi-organism process" rather than to the process subject of this definition "regulation of multi-organism process". I assumed the latter and couldn't understand why the assertion was not made. Reading it the correct way now I do understand the distinction.

David mention that the same type of syntax/issue is true down the whole regulation branch; as a longer term action item this may be worth clarifying?
