### ISSUE TITLE
term consistency GO:0014841 "skeletal muscle satellite cell proliferation" 

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12152]
For the term "skeletal muscle satellite cell proliferation" (GO:0014841) some of its children refer to "skeletal muscle satellite cell" and some only refer to "satellite cell".   I think it would be a good idea to make them all consistent, preferably "...skeletal muscle satellite cell...".  Thanks.

**Comment by cmungall** [comment]
See also: https://github.com/obophenotype/cell-ontology/issues/384

(note that's it's not a conversation between me and me, I just migrated the tickets)

cc @dosumis

**Comment by dosumis** [comment]
Fixed
