### ISSUE TITLE
Issue with terms using 'telomeric RNA' - two different meanings

### ISSUE THREAD

**Issue by JessBuxton** [geneontology/go-ontology#12157]
Hi, I am annotating a paper (PMID 23935072) describing a human protein that binds to human TERRA (telomeric repeat-containg RNA), and have discovered that at the moment there are two different meanings for the phrase 'telomeric RNA' in GO: 

In this term, 'telomeric RNA' refers to TERRA:
GO:0097393 telomeric RNA transcription 
The synthesis of telomeric RNA from a DNA template. A telomere is a complex of DNA and proteins that seals the end of a chromosome. 
PMID:22139915 (S.pombe paper)

But in this term, 'telomeric RNA' refers to TERC, the RNA template component of telomerase
GO:0070034 telomeric RNA binding
Interacting selectively and non-covalently with the telomerase RNA template or to RNA complementary to it
PMID:16884717 (S.pombe paper)

One solution would perhaps be to replace 'telomeric RNA' with 'telomeric template RNA' in all term names referring to TERC, as is already the case for some, eg.
GO:0003721 telomeric template RNA reverse transcriptase activity
Catalysis of the extension of the 3' end of a DNA strand by one deoxynucleotide at a time. Cannot initiate a chain de novo; uses the RNA subunit of the telomerase enzyme complex as its template. 
PMID:11812242

And similarly, replace 'telomeric RNA' with 'telomeric repeat-containing RNA' (and add TERRA as synonym) in all terms that refer to TERRA?

If you agree this is a way forward, then could I also request a new term that would allow me to annotate PMID 23935072 and others, something like:

GO:NEW telomeric repeat-containing RNA binding
Interacting selectively and non-covalently with long non-coding RNA molecules transcribed from subtelomeric regions in most eukaryotes. Telomeric repeat-containing RNA (TERRA) molecules consist of subtelomeric-derived sequences and G-rich telomeric repeats.
(PMID: 20655916)

thanks, Jess
@NancyCampbell 
@ValWood

**Comment by ValWood** [comment]
hi,
Sounds reasonable. The second paper we don't appear to have curated so I'm not sure how it came to be the referencing  paper in the GO term...we will process this paper soon...
Val

**Comment by jimhu-tamu** [comment]
Stumbled on this while helping a CACAO student with something completely unrelated... Shouldn't the template RNA be *telomerase* RNA not telomeric RNA?

**Comment by JessBuxton** [comment]
Hi Jim, that would be simpler and also fit better with definition of the template RNA in RNACentral: telomerase RNA component (TERC), telomerase RNA
http://rnacentral.org/rna/URS00004A7003/9606

So updated suggestions would be:
1. Replace 'telomeric RNA' with 'telomeric repeat-containing RNA' (and add TERRA as synonym) in all terms that refer to TERRA

2. Replace 'telomeric RNA' and 'telomeric template RNA' with 'telomerase RNA' in all term names referring to TERC

3. Create new term, something like:
GO:NEW telomeric repeat-containing RNA binding
Interacting selectively and non-covalently with long non-coding RNA molecules transcribed from subtelomeric regions in most eukaryotes. Telomeric repeat-containing RNA (TERRA) molecules consist of subtelomeric-derived sequences and G-rich telomeric repeats.
(PMID: 20655916

thanks, Jess

**Comment by ukemi** [comment]
Hi Everyone,

'telomeric RNA binding' is defined as: Interacting selectively and non-covalently with the telomerase RNA template or to RNA complementary to it. So, it looks like that term refers to either the 'telomerase RNA' or the 'telomeric repeat-containing RNA'.

So I propose that we leave that term as is and create two children, 'telomeric repeat-containing RNA binding' and 'telomerase RNA binding' with the added specification. Does this make sense?

In the meantime here is what I have done to the other terms:

 [Term]
 id: GO:0003721
-name: telomeric template RNA reverse transcriptase activity
+name: telomerase RNA reverse transcriptase activity
 namespace: molecular_function
 def: "Catalysis of the extension of the 3' end of a DNA strand by one deoxynucleotide at a time. Cannot initiate a chain de novo; uses the RNA subunit of the telomerase enzyme complex as its template." [EC:2.7.7.49, PMID:11812242]
 synonym: "telomerase, catalyst" EXACT []
@@ -478000,21 +478000,23 @@
 
 [Term]
 id: GO:0097393
-name: telomeric RNA transcription
+name: telomeric repeat-containing RNA transcription
 namespace: biological_process
-def: "The synthesis of telomeric RNA from a DNA template. A telomere is a complex of DNA and proteins that seals the end of a chromosome." [GOC:al, PMID:22139915]
+def: "The synthesis of telomeric repeat-containing RNA from a DNA template. A telomere is a complex of DNA and proteins that seals the end of a chromosome." [GOC:al, PMID:22139915]
+synonym: "TERRA transcription" EXACT [PMID:22139915]
 is_a: GO:0006351 ! transcription, DNA-templated
 created_by: paola
 creation_date: 2012-10-23T10:06:17Z
 
 [Term]
 id: GO:0097394
-name: telomeric RNA transcription from RNA pol II promoter
+name: telomeric repeat-containing RNA transcription from RNA pol II promoter
 namespace: biological_process
-def: "The synthesis of telomeric RNA from a DNA template by RNA Polymerase II (Pol II), originating at a Pol II promoter." [GOC:al, PMID:22139915]
-synonym: "telomeric RNA transcription from Pol II promoter" EXACT []
+def: "The synthesis of telomeric repeat-containing RNA from a DNA template by RNA Polymerase II (Pol II), originating at a Pol II promoter." [GOC:al, PMID:22139915]
+synonym: "telomeric RNA transcription from Pol II promoter" RELATED []
+synonym: "TERRA repeat-containing RNA transcription from RNA pol II promoter" RELATED [GOC:22139915]
 is_a: GO:0006366 ! transcription from RNA polymerase II promoter
-is_a: GO:0097393 ! telomeric RNA transcription
+is_a: GO:0097393 ! telomeric repeat-containing RNA transcription
 created_by: paola
 creation_date: 2012-10-23T10:09:15Z

**Comment by JessBuxton** [comment]
Hi,
I think 'telomeric RNA binding' refers only to the telomerase template RNA at present, as TERRA is transcribed directly from telomeric DNA (they are lncRNAs of variable length/sequence, starting in the subtelomeric regions refs. original 2007 paper PMID 17916692, recent review 25926849) - so not really complementary to the telomerase template RNA molecule, of which only a small part is  complementary to telomeric DNA.

So I think it would be good if possible to have a new term as suggested for TERRA binding, as there are several proteins that are involved in telomere maintenance through this mechanism, and would be good to capture this newly discovered process in GO if possible.

Updated term suggestions look fine - small suggestion:
this
+synonym: "TERRA repeat-containing RNA transcription from RNA pol II promoter"

could be simplified to:
+synonym: "TERRA transcription from RNA pol II promoter"

thanks

**Comment by ukemi** [comment]
OK. I think I got it. I editied the synonym as you suggested and added:

 [Term]
+id: GO:0061752
+name: telomeric repeat-containing RNA binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with long non-coding RNA molecules transcribed from subtelomeric regions in most eukaryotes. Telomeric repeat-containing RNA (TERRA) molecules consist of subtelomeric-derived sequences and G-rich telomeric repeats." [GOC:dph, PMID:20655916]
+synonym: "TERRA binding" EXACT [PMID:20655916]
+is_a: GO:0003723 ! RNA binding
+created_by: dph
+creation_date: 2015-11-13T07:55:06Z

**Comment by NancyCampbell** [comment]
Hi,

I am annotating this paper PMID 16507993 figure 1A. I want to annotate mTERT IDA telomeric RNA binding. This does not exist (I think it did before). Anyway, what I can find instead is GO:0070034
Name 	telomerase RNA binding
Ontology 	Molecular Function
Definition 	Interacting selectively and non-covalently with the telomerase RNA template or to RNA complementary to it. 

As mentioned above, now there is a specific TERRA binding term:
+id: GO:0061752
+name: telomeric repeat-containing RNA binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with long non-coding RNA molecules transcribed from subtelomeric regions in most eukaryotes. Telomeric repeat-containing RNA (TERRA) molecules consist of subtelomeric-derived sequences and G-rich telomeric repeats." [GOC:dph, PMID:20655916]
+synonym: "TERRA binding" EXACT [PMID:20655916]
+is_a: GO:0003723 ! RNA binding
+created_by: dph
+creation_date: 2015-11-13T07:55:06Z

So, does it not make sense to change the definition of 
GO:0070034
Name 	telomerase RNA binding
Ontology 	Molecular Function
Definition 	Interacting selectively and non-covalently with the telomerase RNA template or to RNA complementary to it. 
to 
GO:0070034
Name 	telomerase RNA binding
Ontology 	Molecular Function
Definition 	Interacting selectively and non-covalently with the telomerase RNA template.

however if the previous definition is maintained, then,
+id: GO:0061752
+name: telomeric repeat-containing RNA binding
should be a child of GO:0070034 (though this does not make sense with its current name). And a sibling created which is the existing 
+id: GO:0061752
+name: telomeric repeat-containing RNA binding.

Am i missing something? was it agreed to change the definition of 
GO:0070034
Name 	telomerase RNA binding
and I missed it!!

Sorry to throw a spanner in the works!
Thanks
Nancy

**Comment by ukemi** [comment]
Hi Nancy,

So are you suggesting changing changing GO:0070034 back to telomeric RNA binding, retaining the def as 'Definition Interacting selectively and non-covalently with the telomerase RNA template or to RNA complementary to it.'? Then making the new 'telomeric repeat-containing RNA binding' GO:0061752 a child of it and creating a new child called 'telomerase RNA binding'? I would be ok with this.

-D

**Comment by NancyCampbell** [comment]
Hi David,

I just looked at the manual annotations that are available to GO:0070034 and they all 'mean' telomerase RNA binding. So the new name 'means' what it should mean in context of current annotations (and it makes sense somehow). But the definition itself does not i.e. the last bit referrring to "or to RNA complementary to it" is wrong. I guess there is no harm in inserting a new term which is a child of RNA binding but is parent to both: NEW telomeric RNA binding term parent to both GO:0070034 & GO:0061752 and give it the wider definition  Interacting selectively and non-covalently with the telomerase RNA template or to RNA complementary to it (currently assigned to GO:0070034). This could be a safe way to keep the current annotations as they are but assigned to a better named term with a more specific definition.
So I do agree with you that a parent term is a very good idea but due to the current annotations, maybe it can be done with a tweak?
Thoughts?
Thanks David

**Comment by ukemi** [comment]
I could just tweak the definition of the current term. 'Interacting selectively and non-covalently with the telomerase RNA template'

I think that is what Jess was getting at.

**Comment by NancyCampbell** [comment]
I am happy with that. Thanks David.

**Comment by JessBuxton** [comment]
Hi, I definitely agree with this tweak to definition:
GO:0070034
Name telomerase RNA binding
Ontology Molecular Function
Definition Interacting selectively and non-covalently with the telomerase RNA template.

BUT I don't think we should have a NEW telomeric RNA binding parent term, as it wrongly implies that these two RNAs are different subtypes of the same class of RNA, or are complementary to each other, neither of which is the case? In my opinion it would be clearer just to keep both these terms as children of the more general RNA binding as they are now, ie

parent GO:0003723 RNA binding:

children
GO:0061752 
Name telomeric repeat-containing RNA binding 
GO:0070034
Name telomerase RNA binding

My original point was that the phrase 'telomeric RNA' had been used in GO to refer to two completely different types of RNA molecule (TERRA, any lncRNA transcribed directly from telomeric DNA, variable lengths and sequences, and the telomerase template RNA, the specific 451bp RNA encoded by the TERC gene, chr3q in humans) - TERRA isn't complementary to the telomerase RNA template as only a small part of the TERC transcript is complementary to telomeric DNA.

hope that makes sense?

thanks, Jess

**Comment by ukemi** [comment]
OK. I tweaked the definition and left the structure as is. Thanks for all of your help on this.

-David

**Comment by NancyCampbell** [comment]
Thanks David.

**Comment by JessBuxton** [comment]
Hi David,
Please could you add the following GOC refs to the new term below in QuickGO:
GOC:BHF, GOC:BHF_telomere and GOC:jbu
Thanks very much and apologies for forgetting to include this at the time of the request,
bw Jess
GO:0061752
telomeric repeat-containing RNA binding
Ontology	Molecular Function
Definition	Interacting selectively and non-covalently with long non-coding RNA molecules transcribed from subtelomeric regions in most eukaryotes. Telomeric repeat-containing RNA (TERRA) molecules consist of subtelomeric-derived sequences and G-rich telomeric repeats.

**Comment by ukemi** [comment]
Hi Jess,

I must have done this, but forgot to close the ticket because the xrefs are associated with GO:0061752.

-D
