### ISSUE TITLE
standardize use of underscore in gorel term names

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12156]
Moved from GO helpdesk.
http://jira.geneontology.org/browse/GO-681

Hi,

we noticed that the gorel file sometimes has underscores and sometimes spaces. Can we standardize? I prefer underscores as that is what we have been using so far.

Thanks

Val

===
coincident_with(...)", but the name of the term is "coincident with" (with a space). The extension code looks up using the ext. rel. term name not the ID.
For all the other relations the term name is the same as the ID, with underscore rather than spaces. eg.
id: has_direct_input
name: has_direct_input
Looking at the gorel file, it seems quite random. Some names have underscore and some have spaces.

**Comment by tberardini** [comment]
Rama Balakrishnan (Inactive) added a comment - 03/Jan/15 9:39 PM

Val,
Thanks for bringing this up. I will alert the ontology editors about this issue.

Rama

**Comment by tberardini** [comment]
@ValWood @cmungall  Please close if this is no longer relevant.  Thanks.

**Comment by dosumis** [comment]
The relation names in ro.owl have been without underscores for some years now.  You are just seeing this now becuase of work to harmonise gorel with relations used in the GO (full version) and RO. The higher level RO relations are used outside of OWL, so any change would require wider debate.  I don't see any appetie for re-opening that.

> The extension code looks up using the ext. rel. term name not the ID.

It should be switched to use the ID.  No-one editing the ontology is going to assume that labels need to be stable for tracking purposes.

See also:  geneontology/annotation_extensions#3

Duplicate with geneontology/annotation_extensions#51
