### ISSUE TITLE
NTR: single-stranded DNA-dependent GTPase activity

### ISSUE THREAD

**Issue by Jkane94** [geneontology/go-ontology#12158]
GO term name: single-stranded DNA-dependent GTPase activity

Definition:
Catalysis of the reaction: GTP + H2O = GDP + phosphate; this reaction requires the presence of single-stranded DNA, and it drives another reaction. 

Aspect: Molecular Function

Relationships:
Ancestor Chart
is_a GTPase activity (GO:0003924) --> is_a GTPase activity,  coupled (NTR)--> is_a DNA-dependent GTPase activity (NTR) --> is_a single-stranded DNA-dependent GTPase activity (NTR)

References:
PMID: 26277776 
Figure 6
I've used GO:0043142 (Single-stranded DNA-dependent ATPase activity) as a reference.

Thanks, 

Javier K.
CACAO participant

**Comment by ukemi** [comment]
[Term]
+id: GO:0061745
+name: GTPase activity, coupled
+namespace: molecular_function
+def: "Catalysis of the reaction: GTP + H2O = GDP + phosphate; this reaction directly drives some other reaction." [GOC:dph, PMID:26277776]
+is_a: GO:0003924 ! GTPase activity
+created_by: dph
+creation_date: 2015-11-11T12:47:56Z
+
+[Term]
+id: GO:0061746
+name: single-stranded DNA-dependent GTPase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: GTP + H2O = GDP + phosphate; this reaction requires the presence of single-stranded DNA, and it drives another reaction." [GOC:dph, PMID:26277776]
+is_a: GO:0061745 ! GTPase activity, coupled
+created_by: dph
+creation_date: 2015-11-11T12:50:19Z
+
