### ISSUE TITLE
motor behaviour

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12154]
Curating PMID:25318560 I was looking for a term for motor behaviour. 

'voluntary musculoskeletal movement ; GO:0050882' seemed to be the closest. It currently doesn't have a link to behaviour- should it (with motor behavior as a synonym)?

If not, could additional terms be added, please:

motor behavior ; GO:NEW
The specific movement of a single organism in response to external or internal stimuli.
is_a: 
PMID:25318560
GOC:PARL
GOC:bf
is_a: single-organism behaviour  ; GO:0044708

motor learning ; GO:NEW
Any process in which an organism acquires a novel action or movement as the result of experience.
Wikipedia:Motor_learning
GOC:PARL
GOC:bf
(somewhere under learning; GO:0007612, possibly nonassociative learning)

Thank you.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061743
+name: motor learning
+namespace: biological_process
+def: "Any process in which an organism acquires a novel action or movement as the result of experience." [GOC:bf, GOC:PARL, Wikipedia:Motor_learning]
+is_a: GO:0007612 ! learning
+created_by: dph
+creation_date: 2015-11-09T12:40:29Z
+
+[Term]
+id: GO:0061744
+name: motor behavior
+namespace: biological_process
+def: "The specific movement of a single organism in response to external or internal stimuli." [GOC:bf, GOC:PARL, PMID:25318560]
+is_a: GO:0044708 ! single-organism behavior
+created_by: dph
+creation_date: 2015-11-09T12:43:11Z

**Comment by dosumis** [comment]
* Would be good to link these terms to the movement terms in some way.
* "The specific movement of a single organism in response to external or internal stimuli."
  - Doesn't this cover plants and single cells?

**Comment by ukemi** [comment]
How about?

The neuro-muscular movement of a single organism in response to external or internal stimuli.
I'm not sure how to connect to the movement terms other than has_part actin-based movement, but that seems kind of pointless.

**Comment by dosumis** [comment]
> How about?
> The neuro-muscular movement of a single organism in response to external
or internal stimuli.

Sounds good.

Maybe you're right about the movment terms.   There's a general problem
here with deciding what comes under behavior.  The ABO (and probably future
versions of the NBO) simply puts (neuro-muscular) movement under behavior.
IIRC, the reason for splitting this out in GO is that curators don't want
to record that genes with a role in muscle function have as involved in
behavior.  But perhaps this is better dealt with via annotation guidance in
comments.  In that case we could bring 'voluntary musculoskeletal movement'
under motor behavior, or perhaps just merge it in.
