### ISSUE TITLE
NTR: Forked DNA Dependent Helicase Activity

### ISSUE THREAD

**Issue by Jkane94** [geneontology/go-ontology#12159]
Go term: Forked DNA-dependent helicase activity

Definition: Catalysis of the reaction: NTP + H2O = NDP + phosphate, to drive the unwinding of a DNA helix; this reaction requires the presence of forked DNA.

Aspect: Molecular function

Relationships:
Parent: is_a DNA Helicase activity (GO:0003678)
Sibling: is_a four-way junction helicase activity (GO:0009378)

Reference:
PMID: 26277776 

Thanks,

Javier K.
CACAO Participant

**Comment by ukemi** [comment]
[Term]
+id: GO:0061749
+name: forked DNA-dependent helicase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: NTP + H2O = NDP + phosphate, to drive the unwinding of a DNA helix containing forked DNA." [GOC:dph, PMID:26277776]
+is_a: GO:0003678 ! DNA helicase activity
+created_by: dph
+creation_date: 2015-11-11T13:10:51Z
