### ISSUE TITLE
Incorrect EC mapping?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12169]
pombe tor1 and tor2 have an IEA mapping to 1-phosphatidylinositol-3-kinase activity
EC:2.7.1.137
but I think these proteins are ser/thr kinases, they are part of the PIKK family of kinases (kinases that look like PI3 kinases but are not, as far as I understand it). This should probably be removed?

cheers

**Comment by ukemi** [comment]
Hi Val,
I'm pretty sure the mapping in the ontology is correct, I think that the mapping of the gene products to that EC number are incorrect. THe definition in GO and the definition in EC for 1-phosphatidylinositol-3-kinase (activity) are the same.

-David

**Comment by ValWood** [comment]
Yep, @Antonialock  the IEA mismappings go on the annotation tracker
Val
