### ISSUE TITLE
query protein retention in Golgi apparatus 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12163]
The way this term is defined:

Definition: "The retention of proteins within the Golgi apparatus. Golgi-localized carbohydrate-modifying enzymes have a short N-terminal domain that faces the cytosol, a single transmembrane alpha helix, and a large C-terminal domain that faces the Golgi lumen and that contains the catalytic site. How the membrane-spanning alpha helix in a Golgi enzyme causes its localization and prevents its movement to the plasma membrane is not known." [ISBN:0716731363]

it doesn't sound like a process?
(i.e if the protein is being localized by a TM helix?)
It almost appears that it is defined in terms of the localixed protein itself, rather than the process of 'localization'

How would this, if logically defined differ from
GO:0034067 protein localization to Golgi apparatus
?

**Comment by ukemi** [comment]
protein localization to Golgi apparatus- has_end_location Golgi apparatus
protein retention to Golgi apparatus- has_start location Golgi apparatus; has_end_location Golgi apparatus

Clearly there must be a mechanism holding the proteins there, even if it is not know what the mechanism is, don't you think?

**Comment by ValWood** [comment]
It seems that this is a compound term representing  a number of GO  terms spanning different ontology aspects;

http://cshperspectives.cshlp.org/content/3/8/a005264.full
" From these and other studies of Golgi membrane proteins, we now understand that a variety of retention mechanisms are employed, the majority of which involve the dynamic process of iterative rounds of retrograde and anterograde transport. Such mechanisms rely on protein conformation and amino acid-based sorting signals as well as on properties of transmembrane domains and their relationship with the unique lipid composition of the Golgi."

Some proteins appear to be ‘anchored’ in the Golgi but transmembrane domains or receptors. These are ‘localised to the Golgi’

Some Golgi resident proteins are lost from the Golgi, and because of sorting signals they are returned by retrograde transport.

It seems that “retention’ can refer to either of these so it could be a related synonym of all
i) CC term for localisation to the Golgi
ii) BP term for return to the Golgi
ii) BP term GO:0051684 maintenance of Golgi location
iii) GO:0051684 retrograde transport, endosome to Golgi
The directed movement of membrane-bounded vesicles from endosomes back to the trans-Golgi network where they are recycled for further rounds of transport.
(note that this term doesn’t say anything about the cargo….or returning ‘lost’ resident proteins)

Only 16 experimental annotations use this term. Sometimes (Sol1) they seem to be describing a localisation, and sometimes the SGD ones GO:0051684 maintenance of Golgi location (by retrograde transport)

It would be better to have terms like
GO:new maintenance of Golgi location by retrograde transport linked to the correct parents
instead of the vague “Golgi retention” term which is in  a stub

**Comment by ValWood** [comment]
Isn't Mark Feuermann working on vesicle mediated transport for PAINT?
Maybe he would be able to  comment? I can't find his github ID

**Comment by ukemi** [comment]
@marcfeuermann

**Comment by ukemi** [comment]
Val,

It seems that when this term was created, the mechanism was unknown. Inherent aspects of the protein's sequence would not warrant a term, but the transport would. Maybe we should just narrow this term to be 'maintenance of Golgi location by retrograde transport'.

**Comment by ValWood** [comment]
I am not totally sure it is used in that way for the 2 sol1 annotations. I also think 'Golgi retention' has been used to describe unrelated processes above in the literature so the disambiguation by obsoletion with 'related' synonyms seems the way to  go?

**Comment by ValWood** [comment]
We don't know the biology in any more detail right now so closing.
