### ISSUE TITLE
Add licensing info in ontology file

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12168]
Any issue adding the statement
<dc:license rdf:resource="http://creativecommons.org/licenses/by/4.0/"/>
(reflecting the content at http://geneontology.org/page/use-and-license) in the ontology file? I'm specifically wondering if it would be an issue for the OBO.

**Comment by ValWood** [comment]
This made me laugh. Removing the label "development"

**Comment by balhoff** [comment]
This is done.
