### ISSUE TITLE
New GO Term: protein localization to axon

### ISSUE THREAD

**Issue by kaylamichbrown** [geneontology/go-ontology#12165]
Hello! My name is Kayla Brown and I'm with the Texas A&M CACAO class. I'm requesting a new term for protein localization to axon. It would be a child term of GO:0008104 protein localization and a parent term for GO:0002175 protein localization to paranode region of axon. The paper I am annotating is PMID: 26157139. Thank you!

**Comment by dosumis** [comment]
Added:

![image](https://cloud.githubusercontent.com/assets/112839/13145518/13dd9d92-d649-11e5-9d46-2b96b68c92fb.png)

![image](https://cloud.githubusercontent.com/assets/112839/13145524/1c35d914-d649-11e5-8e6b-66ae5e49edaa.png)

(Apologies for the delay,  slipped through the cracks. Hope the term is still useful.
- David)
