### ISSUE TITLE
obsoletion candidate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12164]
A student just used this term in a practical:
SMC family protein binding
not a useful term, if you know  something is binding to an SMC family protein, you should be able to specify the  actual bound SMC family member (these are not like histones or actins where you may not know)

(has one TAS annotation)

**Comment by ukemi** [comment]
Hi Val,

The fate of all of these terms is up in the air. I'd rather not pick them off one-by-one, but rather deal with the whole lot at some point computationally.

-D

**Comment by ValWood** [comment]
OK, they annoy me ;)

I wonder how possible it is to identify the terms computationally ....some sound like families (actin and histones)  but people want to keep them  because the antibodies cannot distinguish  (or do you  mean deal with them computationally once you have a list?). 

They bother me because it isn't clear to our community curators  that they should not use them, and as existing terms, it isn't clear they users should not request new protein family binding terms. 

Do you have a proposed timescale to address this one? I think we should get rid of the ASAP and I'd be happy to create a 'proposed kill' list if it would help.
