### ISSUE TITLE
OTR: Cell pole vs cell tip

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12162]
A CACAO student had a question about localization, which led me to a side issue related to these cell parts.

GO:0051286 ! cell tip is_a GO:0060187 ! cell pole

Cell pole and cell tip each have comments

GO:0051286 ! cell tip: Note that this term differs from 'cell pole ; GO:0060187' in that it is applicable to a narrower range of cell shapes.

GO:0060187 ! cell pole: Note that this term differs from 'cell tip ; GO:0051286' in that it is applicable to a broader range of cell shapes

I'm finding this confusing. On the one hand, I can understand that not all poles are tips. A spherical object can have poles; planets, or the animal and vegetal poles of an oocyte.  But, I think of the end of an axon as a cell tip, but not as a cell pole. So it seems to me that there's a genus-differentia issue.

In addition, it's not clear to me what the "range of cell shapes" means. If poles are for spheres, cylinders, and ellipsoids, that seems like a narrower range than the variety of shapes that can be formed from branched hyphae etc. 

So, I think the relationships and notes for these terms should be modified, but I'm not sure whether there should be something intermediate between cell part and each of the terms.

**Comment by ukemi** [comment]
Hi Jim,

I agree. I have made these two terms siblings and have adjusted the comments to hopefully make things clearer.
