### ISSUE TITLE
ntr  tm transport: and revise F-P link

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12167]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005345#term=ancchart 

Please 
add new term
"purine nucleobase transmembrane transporter"
descendant of
"purine nucleobase transport"
and
"transmembrane transport"
(I'll do the first part with TG)

move F-P link from "purine nucleobase transport" to new term

**Comment by ValWood** [comment]
GO:1904823 Label: purine nucleobase transmembrane transport

**Comment by ukemi** [comment]
done
