### ISSUE TITLE
NTR: Single-stranded DNA-dependent CTPase activity

### ISSUE THREAD

**Issue by Jkane94** [geneontology/go-ontology#12160]
GO term name: single-stranded DNA-dependent CTPase activity

Definition:
Catalysis of the reaction: CTP + H2O = CDP + phosphate; this reaction requires the presence of single-stranded DNA, and it drives another reaction.

Aspect: Molecular Function

Relationships:
Ancestor Chart
is_a CTPase activity (GO:0043273) --> is_a CTPase activity, coupled (NTR)--> is_a DNA-dependent GTPase activity (NTR) --> is_a single-stranded DNA-dependent CTPase activity (NTR)

References:
PMID: 26277776 
Figure 6
I've used GO:0043142 (Single-stranded DNA-dependent ATPase activity) as a reference.

Thanks,

Javier K.
CACAO participant

**Comment by ukemi** [comment]
[Term]
+id: GO:0061747
+name: CTPase activity, coupled
+namespace: molecular_function
+def: "Catalysis of the reaction: CTP + H2O = CDP + phosphate; this reaction directly drives some other reaction." [GOC:dph, PMID:26277776]
+is_a: GO:0043273 ! CTPase activity
+created_by: dph
+creation_date: 2015-11-11T13:02:49Z
+
+[Term]
+id: GO:0061748
+name: single-stranded DNA-dependent CTPase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: CTP + H2O = CDP + phosphate; this reaction requires the presence of single-stranded DNA, and it drives another reaction." [GOC:dph, PMID:26277776]
+is_a: GO:0061747 ! CTPase activity, coupled
+created_by: dph
+creation_date: 2015-11-11T13:05:32Z
+
