### ISSUE TITLE
difference between GO:0042175 and GO:1990578

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12179]
Hi,

I just wondered what the difference between these two terms is (if there is one):
 GO:0042175 nuclear outer membrane-endoplasmic reticulum membrane network
 GO:1990578 perinuclear endoplasmic reticulum membrane

thanks
Antonia.

**Comment by mah11** [comment]
If I'm reading the defs correctly, GO:0042175 is all of the ER membrane plus the outer nuclear membrane, whereas GO:1990578 is the membrane around the part of the ER that's close to the nucleus. And if that's right, it seems like it would also make sense for GO:1990578 to be part_of GO:0042175.

m

**Comment by mcourtot** [comment]
:------------------------------------------------------------------------
r30415 | mcourtot | 2015-12-16 14:58:52 +0000 (Wed, 16 Dec 2015) | 3 lines

added perinuclear endoplasmic reticulum membrane part of some nuclear outer membrane-endoplasmic reticulum membrane network as per https://github.com/geneontology/go-ontology/issues/12179
