### ISSUE TITLE
New term request: Accessory Outer Segment

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#12170]
Hello, 
I would like to request a new term to be added to the cellular_component part of the ontology. 

New term: Accessory Outer Segment
Definition: a cilium-like structure emanating from the inner segment and running alongside the outer segment of photoreceptors
Note: this structure was described in teleost fish and in human 
References: 
PMID: 837407
PMID: 25125189
PMID: 13936631

This term would probably be a child of 
GO:0042995 - cell projection

Children of the new term:
- Cone accessory Outer Segment : accessory outer segment in cone photoreceptor
- Rod accessory Outer Segment : accessory outer segment in rod photoreceptor

Thank you! 
Sabrina

**Comment by ukemi** [comment]
[Term]
id: GO:1990906
name: accessory outer segment
namespace: cellular_component
def: "A cilium-like cell projection emanating from the inner segment and running alongside the outer segment of photoreceptors." [GOC:dph, PMID:25125189]
subset: termgenie_unvetted
is_a: GO:0042995 ! cell projection
is_a: GO:0097458 ! neuron part
created_by: dph
creation_date: 2015-11-24T13:56:06Z
