### ISSUE TITLE
NTR - neck of caveola

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12171]
In some publications e.g. PMID: 19640926 authors describe a CC called the "neck of caveolae" which is a sub-domain / part of GO:0005901 caveola.  
Please would you create a new term to match?
I would use it to annotate Q5S007 LRRK2 in this paper  PMID: 19640926
The same wording appears in titles of PMID: 17227843, PMID: 9531551 - these structures are also claimed to "play an important role as signaling platforms" according to PMID: 17227843

**Comment by dosumis** [comment]
Added: 
* label "caveola neck"
* definition "A membrane microdomain that forms a necklace around the bulb (crater) of a caveola.  Intramembrane particles are concentrated in this region and cytoskeletal components, including actin, are highly enriched in the area underlying it." [PMID:17227843, PMID:9531551]
* SubClassOf:
  - 'membrane microdomain'
  - 'part of' some caveola

**Comment by Pauldenny** [comment]
David
please include 
xrefs
GOC:PARL
GOC:pad
in this term's records
Thanks!

**Comment by dosumis** [comment]
Done
