### ISSUE TITLE
problem with cell aging

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12174]
I spotted this anomaly recently:

Name    cell aging
Definition  An aging process that has as participant a cell after a cell has stopped dividing. Cell aging may occur when a cell has temporarily stopped dividing through cell cycle arrest (GO:0007050) or when a cell has permanently stopped dividing, in which case it is undergoing cellular senescence (GO:0090398). May precede cell death (GO:0008219) and succeed cell maturation (GO:0048469).

note
has as participant a cell after a cell has stopped dividing

but has a descendant
replicative cell aging
Definition  The process associated with progression of the cell from its inception to the end of its lifespan that occurs as the cell continues cycles of growth and division. 

One of these defs must be incorrect logically?
They seem to be describing completely different things?

**Comment by dosumis** [comment]
Replicative cell aging looks dodgy to me. Def is much broader than that of 'aging'.  Seems to refer to whole life of cell. Seems you could annotate almost anything to it.

**Comment by dosumis** [comment]
Replicative aging seems to be used in the lit though - need to revise def, based on refs from annotations.  Will also broaden cell-aging def.

**Comment by ValWood** [comment]
Yeah is more like "cessation of division". This is describing how biologists measure when it occurs? I still  have a problem with the cell "ageing" terms. They aren't really  biological processes.....

**Comment by ValWood** [comment]
It could  probably be merged with this
GO:0090399 replicative senescence
A cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging.

(badly defined too though, doesn't say what it is....and AFAIK doesn't always include dismantling of a cell)

Can of worms here, sorry.....

**Comment by ValWood** [comment]
will be useful

http://microbialcell.com/wordpress/wp-content/uploads/2017/12/2018A-Carmona-Gutierrez-Microbial-Cell.pdf

**Comment by pgaudet** [comment]
The proposal is to merge  GO:0090399  replicative senescence (14 EXP annotations) into     GO:0001302 replicative cell aging (83 EXP)

These are the groups who have annotated to 

- 7 EXP	BHF-UCL @RLovering 
- 3 EXP	SGD @srengel 
- 3 EXP	UniProt @ggeorghiou 
- 1 EXP	MGI @ukemi 

Please let me know if you're OK with the merge. 

Thanks, Pascale

**Comment by srengel** [comment]
are we sure that replicative senescence isn't its own thing?  this paper would suggest that it is a specific phenomenon.  https://mcb.asm.org/content/mcb/31/8/1637.full.pdf

**Comment by ValWood** [comment]
In the current scenario the parentage  does not make sense.

To fix, I suggest  trying to describe more fully the processes of
"replicative senescence"
and "replicative cell aging"

Are they normal processes for the organisms in question?
What are the similarities and difference?
i.e.
is telomere shortening involved?
is checkpoint activated?
Is cell dismantled?
(in yeast the process appears to be  a type of checkpoint activation, how does this differ from normal DNA integrity checkpoint activation?)

The original issue here is that 
replicative cell aging is defined much more broadly than it's parent 'cell ageing', so addressing this  first might identify  the difference between 

"replicative cell aging" and "replicative senescence"

  I *still* think  cell ageing is a phenotype and not a process, in this situation, but I'll keep quiet on that for now ;)

**Comment by RLovering** [comment]
Hi
I don't understand why you are considering this merge. "replicative senescence"
and "replicative cell aging" are not the same at all. 
replicative senescence: preprogrammed process associated with irreversible cell-cycle arrest. It is a very important process, often the cell has to decide between apoptosis and replicative senescence. If the cell is too damaged (usually at the DNA level) to continue to replicate but it is sufficiently functional that it can remain in the body/tissue etc it may choose senescence, if it is too damaged it will apoptose. 

In contrast replicative cell aging is a very broad term covering a multitude of processes, under the definition: The process associated with progression of the cell from its inception to the end of its lifespan that occurs as the cell continues cycles of growth and division. 

I am not sure what replicative cell aging is suppose to cover, possibly the fact that you cannot passage normal 'mortal' differentiated cells through more than around 25 cell cycles.  

I wouldn't like to comment on whether after 25 cycles the cells go into replicative senescence or whether they apoptose. I guess the conditions they face will decide that.

I think you could probably put replicative senescence as part_of child of replicative cell aging.

would you be happy with that?

Ruth

**Comment by ValWood** [comment]
I refer everyone back to the original point

Name cell aging
Definition An aging process that has as participant a cell after a cell has stopped dividing. Cell aging may occur when a cell has temporarily stopped dividing through cell cycle arrest (GO:0007050) or when a cell has permanently stopped dividing, in which case it is undergoing cellular senescence (GO:0090398). May precede cell death (GO:0008219) and succeed cell maturation (GO:0048469).

note
has as participant a cell after a cell has stopped dividing

but has a descendant
replicative cell aging
Definition The process associated with progression of the cell from its inception to the end of its lifespan that occurs as the cell continues cycles of growth and division.


The position of  "replicative cell aging" does not make sense logically.
The parent of  "replicative cell aging" refers to a cell which is non-dividing.

but it itself defined
"Definition The process associated with progression of the cell from its inception to the end of its lifespan that occurs as the cell continues cycles of growth and division."

Nothing should happen to anything until 
 "replicative cell aging" is defined correctly, the current def doesn't make sense. 

It is so general I could annotate *anything* to it!

**Comment by ukemi** [comment]
@tberardini  Just pinging you here because if I recall correctly, there is a distinction between aging and senescence in plants.

**Comment by ValWood** [comment]
I still think there isn't a problem with the senescence term, it's the "replicative ageing" that's the issue. it just doesn't seem to be a GO process, replicative ageing refers to "the limited number of divisions that a single cell can attain" ......
how can you write a definition for that? It's "lifespan"

**Comment by tberardini** [comment]
The terms we'd use for annotating senescence in plant are under 'plant organ senescence', a branch independent of cell aging.

http://amigo.geneontology.org/amigo/term/GO:0090693

![image](https://user-images.githubusercontent.com/4998871/45392300-96f67680-b5db-11e8-89b3-49035d8c1a69.png)

**Comment by ValWood** [comment]
superseded by https://github.com/geneontology/go-ontology/issues/18632
