### ISSUE TITLE
NTR: response to acetylcholine

### ISSUE THREAD

**Issue by vhinard** [geneontology/go-ontology#12175]
Could we have a term for the "response to Acetylcholine" in the same way as "response to dopamine" or "serotonin"? 
It only exists "response to nicotine" that is not the endogenous neurotransmitter GO:0035094.

**Name**    response to acetylcholine
**Ontology**    Biological Process
**Definition**  Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an acetylcholine stimulus. "

Best, 
Valérie

**Comment by vhinard** [comment]
Hello David, 
Did you have any time to look at this request?
Best,
Valérie

**Comment by dosumis** [comment]
Added:

[Term]
id: GO:1905144
name: response to acetylcholine
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an acetylcholine stimulus." [GO_REF:0000071, GOC:TermGenie, PMID:21238497]
is_a: GO:0010033 {is_inferred="true"} ! response to organic substance
is_a: GO:1901700 {is_inferred="true"} ! response to oxygen-containing compound
intersection_of: GO:0050896 ! response to stimulus
intersection_of: has_input CHEBI:15355 ! acetylcholine
relationship: has_input CHEBI:15355 {is_inferred="true"} ! acetylcholine
created_by: dos
creation_date: 2016-04-14T08:54:49Z

[Term]
id: GO:1905145
name: cellular response to acetylcholine
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an acetylcholine stimulus." [GO_REF:0000071, GOC:TermGenie, PMID:21238497]
is_a: GO:1901701 {is_inferred="true"} ! cellular response to oxygen-containing compound
is_a: GO:1905144 {is_inferred="true"} ! response to acetylcholine
intersection_of: GO:0070887 ! cellular response to chemical stimulus
intersection_of: has_input CHEBI:15355 ! acetylcholine
relationship: has_input CHEBI:15355 {is_inferred="true"} ! acetylcholine
created_by: dos
creation_date: 2016-04-14T08:54:58Z

[Term]
id: GO:0095500
name: acetylcholine receptor signaling pathway
namespace: biological_process
def: "The series of molecular signals generated as a consequence of an acetylcholine receptor binding to one of its physiological ligands." [GOC:dos]
synonym: "dopamine receptor signalling pathway" EXACT []
intersection_of: GO:0007165 ! signal transduction
intersection_of: starts_with GO:0015464 ! acetylcholine receptor activity
relationship: part_of GO:1905145 ! cellular response to acetylcholine
