### ISSUE TITLE
dishevelled binding

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12172]
I wanted to run-it through Github first to check it’s still okay to add children of ‘protein binding’ when it’s a family of proteins but no grouping PR term?

dishevelled protein binding ; GO:NEW
Interacting selectively and non-covalently with a dishevelled protein.
PMID: 19252499
GOC:PARL, GOC:bf
Exact Synonym: DVL binding (PMID: 19252499)
Related Synonym: DSH binding (GOC:bf, FB:FBgn0000499)

Thanks!

**Comment by tberardini** [comment]
Email to Becky: No, not ok. :-1:

**Comment by rebeccafoulger** [comment]
See minutes here for plan of protein binding terms:
http://wiki.geneontology.org/index.php/Ontology_meeting_2015-03-19
