### ISSUE TITLE
NTR - CAMKK–AMPK signalling pathway

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12188]
CAMKK–AMPK pathway 
(Calcium-calmodulin-dependent kinase kinase (CAMKK) / AMP-activated protein kinase (AMPK) pathway)
Part of a larger group of conserved, so-called 'stress-response' pathways. e.g. see Figure 2 in review PMID: 24709372
It is also one of many pathways upstream of autophagy.
Also see review:
PMID: 23010169
CAMKK and AMPK orthologues found in worms, flies, mammals.
Calcium/calmodulin-dependent kinase kinase 2 (CAMKK2) is a serine/threonine protein kinase whose activity is increased upon Ca2+ influx through Ca2+/calmodulin binding.
AMPK is a serine/threonine protein kinase composed of three subunits, including a catalytic subunit (α1 or α2 in mammals), a β adaptor subunit (β1 or β2), and a γ subunit (γ1, γ2 or γ3) that is allosterically activated upon binding to AMP or ADP. 
Ancestors would include:
GO:0019722 calcium-mediated signaling
(Grand?) Children might include (amongst many):
MF GO:0004679 AMP-activated protein kinase activity 
With GO:0004679  being part_of CAMKK–AMPK pathway.

I would use this term to annotate 
Q13131	PRKAA1 in PMID: 22012985
BUt I'm sure that it would be used many other occasions. 

GOC:pad

**Comment by tberardini** [comment]
Autophagy = ukemi.

Please reassign to me, if I mis-assigned.

**Comment by ukemi** [comment]
Hi Paul,
How does this sound?
[Term]
id: GO:NEW
name: CAMKK-AMPK signaling cascade
namespace: biological_process
def: "A series of molecular signals in which calmodulin-dependent protein kinase activity enabled by a CAMKK directly activates an AMPK. The cascade begins with calmodulin binding calcium which in turn binds CAMKK enabling its calmodulin-dependent protein kinase activity.  The cascade ends with AMP-activated protein kinase activity." [GOC:pad, PMID:23010169, PMID:24709372]
synonym: "stress-activated AMP-activated protein kinase signaling cascade" RELATED [GOC:dph]
is_a: GO:0019722 ! calcium-mediated signaling
intersection_of: GO:0019722 ! calcium-mediated signaling
intersection_of: ends_with GO:0004679 ! AMP-activated protein kinase activity
intersection_of: has_part GO:0004683 ! calmodulin-dependent protein kinase activity
intersection_of: has_part GO:0005516 ! calmodulin binding
intersection_of: starts_with GO:0005509 ! calcium ion binding
created_by: dph
creation_date: 2016-04-14T08:13:03Z

**Comment by Pauldenny** [comment]
Sounds great, David
Thanks

**Comment by Pauldenny** [comment]
Just checking, but would this term automatically be attributed to GOC:PARL because it's shown as a label?
Thanks again!

**Comment by ukemi** [comment]
Nope, but I can add it. Please keep checking or I will certainly forget!

 [Term]
+id: GO:0061762
+name: CAMKK-AMPK signaling cascade
+namespace: biological_process
+def: "A series of molecular signals in which calmodulin-dependent protein kinase activity enabled by a CAMKK directly activates an AMPK. The cascade begins with calmodulin binding calcium which in turn binds CAMKK enabling its calmodulin-dependent protein kinase activity. The cascade ends with AMP-activated protein kinase activity." [GOC:dph, GOC:pad, GOC:PARL, PMID:23010169, PMID:24709372]
+synonym: "stress-activated AMP-activated protein kinase signaling cascade" RELATED [GOC:dph]
+is_a: GO:0019722 ! calcium-mediated signaling
+intersection_of: GO:0019722 ! calcium-mediated signaling
+intersection_of: ends_with GO:0004679 ! AMP-activated protein kinase activity
+intersection_of: has_part GO:0004683 ! calmodulin-dependent protein kinase activity
+intersection_of: has_part GO:0005516 ! calmodulin binding
+intersection_of: starts_with GO:0005509 ! calcium ion binding
+created_by: dph
+creation_date: 2016-04-14T12:59:31Z
