### ISSUE TITLE
NTR: lumen and membrane children for GO:0044194 cytolytic granule

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12185]
To annotate  PMID:17272266  and PMID:21247065 for Reactome, could we have new cellular_component terms:
GO:new cytolytic granule part. Any constituent part of the cytolytic granule, the specialized secretory lysosome that is present in cells with cytolytic capability such as cytotoxic T lymphocytes and natural killer cells. This term would be a part_of child of  GO:0044194 cytolytic granule and an is_a child of  GO:0044444 cytoplasmic part, and would have a "no direct annotations" restriction.
GO:new cytolytic granule lumen. The volume enclosed by the membranes of the cytolytic granule. Is_a child of cytolytic granule part.
GO:new cytolytic granule membrane. The lipid bilayer surrounding the cytolytic granule. Is_a child of cytolytic granule part.
Thanks.

**Comment by mcourtot** [comment]
Hi Peter - thanks, I'll look into those. I'm away this week, do you need them urgently?

**Comment by mcourtot** [comment]
HI Peter,

I am wondering if the following would work. I could create terms for:
- cytolytic granule lumen, is_a 'cytoplasmic membrane-bounded vesicle lumen' and part_of some 'cytolytic granule'
 and 
- cytolytic granule membrane, defined as 'whole membrane' and ('bounding layer of' some 'cytolytic granule')

This would male it consistent with the way other granules and components have been represented, and wouldn't require the creation of cytolytic granule part.

What do you think?

**Comment by deustp01** [comment]
That should work - consistency with the organization of other cytosolic membrane-bounded vesicles is exactly what we want.
Thanks.

**Comment by mcourtot** [comment]
Added 
ID: GO:1904856 Label: cytolytic granule lumen
ID: GO:0101004 Label: cytolytic granule membrane
