### ISSUE TITLE
gene product specific protein phosphatase regulatory terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12184]
Currently we  have terms like
protein phosphatase type 2A inhibitor activity
but for the phosphatase terms the specific gene products are synonyms

eg
GO:0004721 phosphoprotein phosphatase activity
narrow	protein phosphatase-2A activity
narrow	protein phosphatase-2C activity
narrow	protein phosphatase-2B activity
narrow	protein phosphatase-1 activity

the regulatory terms should mirror this.
At present its confusing 

because you end up with two options
protein phosphatase type 2A inhibitor activity  
protein serine/threonine phosphatase inhibitor activity 
which aren't mutually exclusive

**Comment by mcourtot** [comment]
Hi Val, I'll look into those, but won't be able to before next week; let me know if this is an issue.

**Comment by mcourtot** [comment]
Hi Val,

Could you please clarify exactly what you are suggesting? I didn't understand what you mean "you end up with 2 options which aren't mutually exclusive" nor whether you are suggesting we create all the activator terms to mirror the inhibitor ones, or something else.

Cheers,
Melanie

**Comment by ValWood** [comment]
Hi Melanie,

I was annotating a 
"protein phosphatase type 2A inhibitor activity"
which is *simultaneously* a
"protein serine/threonine phosphatase inhibitor activity" 

this means I have a choice of 2 terms to describe a single activity.


That said, I think this is another example where the specificity is a bit too granular. 
I don't think that we should specify

protein phosphatase type 2A inhibitor activity because 'type 2A doesn't tell us anything specific about the molecular function.

My preferred solution would be to merge all of these into their parents and make them narrow synonyms 
 GO:1990681	protein phosphatase type 2A inhibitor activity	
GO:0008601	protein phosphatase type 2A regulator activity	
GO:0072543	protein phosphatase type 2A activator activity
(and for the other familes)

to mirror
GO:0004721 phosphoprotein phosphatase activity 
narrow protein phosphatase-2A activity
narrow protein phosphatase-2C activity
narrow protein phosphatase-2B activity
narrow protein phosphatase-1 activity


This way, I can use
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004864#term=children
GO:0004865	protein serine/threonine phosphatase inhibitor activity

rather than need to make 2 annotations concurrently to
GO:0004865	protein serine/threonine phosphatase inhibitor activity
and
GO:1990681	protein phosphatase type 2A inhibitor activity
to represent a single activity

Does that make sense?

**Comment by hdrabkin** [comment]
This reminds me of something ;
I thought that activities that have dual specificities were going to be dropped because they can't happen simultaineously.
I mean: enzyme A has an activity that can phosphorylate a serine; enzyme A has an activity that can phosphorylate a tyrosine. But it can't be doing both at the same time.

Am I remembering wrong?
--
Harold

**Comment by ValWood** [comment]
Hi Harold,

yes, but for the serine/threonine term, I think it it means it phosphorylates on serine or threonine and not both.

That said, I'd be happy to  just stop at "protein phosphatase activity".  It would be much simpler.
This is another example I discussed with @thomaspd
I guess this might be controversial but I don't like the way you end up using different terms  to describe the same thing...like this:
http://www.pombase.org/spombe/result/SPAC1782.09c

**Comment by mcourtot** [comment]
Thanks for the clarification Val. 
It seems an entity could have a serine/threonine phosphatase inhibitor activity and not the protein phosphatase type 2A inhibitor activity, and vice-versa, so maybe the 2 annotations are justified? 
There are also several annotations from PAINT and InterPro using the specific 2A/2B/2C to automatically add annotations, so this seems to be a useful distinction.

**Comment by ValWood** [comment]
We could make 2 annotation but they would  both be describing the same activity. The 2A,2B etc only exist because at some points gene product specific terms have been added into GO.
If we can't merge the terms (which I believe is the often talked about longer term solution, because GP or family specific terms are outside the scope of GO), we should at least make the parentage correct.

I think all (2A,2B,2C,1) are all serine/threonine phosphatases 
https://en.wikipedia.org/wiki/Protein_phosphatase_1
https://en.wikipedia.org/wiki/Protein_phosphatase_2

"protein phosphatase type 2A inhibitor activity"
is_a
"protein serine/threonine phosphatase inhibitor activity"
parentage could be added?

so we only need make one annotation to describe a single activity.

**Comment by mcourtot** [comment]
HI Val - so looking at the ontology again, we do have protein phosphatase type 1 complex and protein phosphatase type 2A complex being subclasses of protein serine/threonine phosphatase complex, so you're entirely right.

I looked at the different relevant sections:
- protein phosphatase inhibitor/regulator/activator activity
- regulation of protein serine/threonine activity  (and of type1&2)
- protein serine/threonine phosphatase activity (and of type1&2)
- protein serine/threonine phosphatase complex (and of type1&2)

2 issues:
- some terms are missing, such as protein serine/threonine activator activity
- It seems there ought to be propagation of the inference: if type 1 and 2 are asserted are being types of user/thr phosphatase, their activities etc ought to be propagated. Maybe this is related to the issue of transitivity over regulates.

It feels there is something fishy going on there: if "protein phosphatase type 2A" is a "protein serine/threonine phosphatase" then we should be able to automatically infer that "protein phosphatase type 2A inhibitor activity" is_a "protein serine/threonine phosphatase inhibitor activity"

I will check with other editors if they know why the inferences are not made.

**Comment by dosumis** [comment]
> It feels there is something fishy going on there: if "protein phosphatase type 2A" is a "protein serine/threonine phosphatase" then we should be able to automatically infer that "protein phosphatase type 2A inhibitor activity" is_a "protein serine/threonine phosphatase inhibitor activity"

Needs formalisation of MF definitions.  I have some branch edits to merge in that should bring in the new regulates relations (directly_inhibits/activates) needed for this.

**Comment by mcourtot** [comment]
Thanks @dosumis. Upon further investigation I did see that there were different types of axioms used such as "part of some negative regulation" "subclass of inhibitor" etc. I will wait for your changes to be merged then, and will try and clean that section up (unless you are working on this as part of the MF project?)

**Comment by thomaspd** [comment]
Sorry to put in a comment so late, but the GO grant just went in late yesterday.  An activity should not be named after a gene product, as a gene product could potentially have multiple molecular functions and not just the one it's named after.  Also, protein phosphatase inhibitor means "directly [i.e. via direct physical interaction] inhibits some protein phosphatase activity", not "directly inhibits some protein named protein phosphatase 2A"-- properly speaking you don't inhibit a protein, you inhibit the activity of a protein.

So Val is right, there should be no term "protein phosphatase 2A inhibitor activity", there should be a protein phosphatase inhibitor activity, and you can specify the molecular target (the phosphatase, i.e. the protein that has phosphatase activity) in the extension field, or in a connected annoton in LEGO.

I like her suggestion to remove the terms named after proteins, e.g. -2A, and add them as narrow synonyms of a proper activity.

Does that make sense?

**Comment by ukemi** [comment]
Makes perfect sense to me.

-D

**Comment by ValWood** [comment]
Yay! 4 down, bzillions  more to go....
and

> GO grant just went in late yesterday
yay!

**Comment by ValWood** [comment]
Just a thought, as these merges are made it might be nice to send alerts out. This way we can  do a quick check to see if we want to add  extensions if we know which P1 or P2 family member it is and we haven't captured it already...

**Comment by mcourtot** [comment]
It actually makes sense to me too :) Now re fixing... 
- @dosumis said he has changes to merge in, so I'd rather wait for those as I don't know if he touched that bit as part of the refactoring. 
- I then need to look at the different parts of the ontology where those phosphatase are used, as well as other ones (e.g. protein phosphatase 4) which are their subclasses. Some cases I'm less sure about: is "pseudophasphatase activity" a narrow synonym for phosphatase inhibitor activity?
- Finally, I need to check re merging how this will happen - it may be a deprecation of the existing terms in which case the absolution notice would be sent out (if we simply "merge" the IRIs disappear in the OWL file and we had decided this was undesirable)

If that seems like a reasonable plan, I could draft the new hierarchy, perhaps in a google doc, have you review/comment/agree and then implement. Any other suggestion?

**Comment by dosumis** [comment]
>  An activity should not be named after a gene product, as a gene product could potentially have multiple molecular functions and not just the one it's named after. Also, protein phosphatase inhibitor means "directly [i.e. via direct physical interaction] inhibits some protein phosphatase activity", not "directly inhibits some protein named protein phosphatase 2A"-- properly speaking you don't inhibit a protein, you inhibit the activity of a protein.

+1

> @dosumis said he has changes to merge in, so I'd rather wait for those as I don't know if he touched that bit as part of the refactoring.

No changes to these terms, but I have (I hope) imported the RO direct regulation relations. If this has worked, you should be able to use these to define the inhibitor activity classes by tomorrow.

> Finally, I need to check re merging how this will happen - it may be a deprecation of the existing terms in which case the absolution notice would be sent out (if we simply "merge" the IRIs disappear in the OWL file and we had decided this was undesirable)

As I understand it, we merge as usual (ID becomes an alt_id), but we are meant to have an extension to the OBO\<-\>OWL conversion that generates obsolete classes from these URIs - with a replaced_by annotation axiom linking back to the IRI of the winning term in the merge.  It looks like this extension has not yet happened  ( @cmungall @hdietze )

**Comment by mcourtot** [comment]
> No changes to these terms, but I have (I hope) imported the RO direct regulation relations. If this has worked, you should be able to use these to define the inhibitor activity classes by tomorrow.

As per the proposal above we wouldn't actually won't define the inhibitors, but rather merge with the parents.

> As I understand it, we merge as usual (ID becomes an alt_id), but we are meant to have an extension to the OBO<->OWL conversion that generates obsolete classes from these URIs - with a replaced_by annotation axiom linking back to the IRI of the winning term in the merge. It looks like this extension has not yet happened ( @cmungall @hdietze )

I thought we would stop merging and do a clean deprecation instead (as "merging" is just another way of saying "this term doesn't exist anymore and was replaced with this one), indicating the replacement term.  I added this item for discussion at the editors call tomorrow.

**Comment by dosumis** [comment]
> there should be a protein phosphatase inhibitor activity,

![image](https://cloud.githubusercontent.com/assets/112839/12610869/e8a0f732-c4e1-11e5-9f66-0585dbb6c03b.png)

Should have EC axiom using directly_inhibits

**Comment by mcourtot** [comment]
+1, but there will be only 1 inhibitor activity class, for protein phosphatase inhibitor activity.

**Comment by RLovering** [comment]
Hi All

I thought I might preempt this obsoletion by re-annotating the proteins I have annotated to these terms, but this highlighted a few things;
1: I would draw your attention to PMID:16916641 which implies that PP2A displays both phosphotyrosyl phosphatase activity and serine/threonine phosphatase activity (see bit of text below). 

2: The authors do not specify the species of the PP2A A-C dimer they use in the experiments. This might have been fine for C16 as the discussion yesterday confirmed that I can add the 'in vivo' target in C16, however there are 2 isoforms for the A and C subunits: PPP2R1A, PPP2R1B; PPP2CA, PPP2CB. The authors do not specify which isoforms they use, in this case there is no excuse because they have actually cloned them. But to be honest this is why there are these specific terms because the authors will describe experiments with these proteins (often cross species: rabbit, bovine being particular favourites) and this is why the protein phosphatase 2A binding term exists.

So what can we include in column 16 to capture the specificity of the function of this regulator? Perhaps a PRO ID? Or the GO CC: protein phosphatase type 2A complex

Thanks

Ruth

-----------------------------

PMID:16916641  states: In addition to its serine/threonine phosphatase activity, PP2A exhibits a basal level of phosphotyrosyl phosphatase activity, which is stimulated by a protein with no sequence homology to any known protein. This protein, originally named phosphotyrosyl phosphatase activator (PTPA), is highly conserved from yeast to human and requires ATP/Mg2+ for its activity in vitro (Cayla et al., 1990, Cayla et al., 1994 and Van Hoof et al., 1994). However, PTPA lacks signature sequence motifs that are common to other known classes of ATPases. PTPA is encoded by two genes in yeast, and deletion of both genes is lethal (Fellner et al., 2003). Recent studies suggest that PTPA can reactivate the serine/threonine phosphatase activity of an inactive form of PP2A that was isolated as a complex with the methyl esterase of PP2A (Fellner et al., 2003, Longin et al., 2004 and Van Hoof et al., 2005).

**Comment by mcourtot** [comment]
Trying to move forward on this.

We currently have:
![screen shot 2016-10-25 at 10 55 44](https://cloud.githubusercontent.com/assets/2214135/19681562/bfdf52da-9aa1-11e6-8caf-9660c23c9a3b.png)
Proposal is:
- [ ] merge GO:1990681 protein phosphatase type 2A inhibitor activity into protein phosphatase inhibitor
- [ ] merge GO:0008601 protein phosphatase type 2A regulator activity, GO:0008599 protein phosphatase type 1 regulator activity, GO:0030359 protein phosphatase type 2B regulator activity and GO:0030362 protein phosphatase type 4 regulator activity into protein phosphatase regulator activity
- [ ] merge GO:0072543 protein phosphatase type 2A activator activity, GO:0071862 protein phosphatase type 1 activator activity into protein phosphatase activator

Please comment as to whether this is suitable or not.

**Comment by ValWood** [comment]
That sounds great to me.

**Comment by mcourtot** [comment]
Done revision 36528.
