### ISSUE TITLE
Possible fix for taxon rules invisible to QuickGO

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12180]
@cmungall 

This issue stems from the taxonomy update paper, but is of general importance:

Recently added taxon constraints are not visible in QuickGO. This is due to the recent halt in the practice of adding GOTAX IDs, which are necessary for taxon rules to be transparent to QuickGO.
Example: GO:0006915 ‘apoptotic process’ used to be never_in_Viridiplantae, and that rule had a GOTAX ID. The rule was recently changed to only_in_Opisthokonta (Fungi/Metazoa). I did the change in OBO-Edit and did NOT run the script to automatically assign GOTAX ID, as we used to (perl script called assign-relation-ids.pl; all details in the README file here http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/quality_control/annotation_checks/taxon_checks/). As a result, not only is the new rule not visible in QuickGO, but the old one is gone too! Frustrating. 
Plus, as we discussed, the recently added taxon rules inherited from UBERON are also invisible to QuickGO. 
Tony S said that in the future he would like to work on eliminating the need for GOTAX IDs altogether. In the meantime though, may be a silly question, but I have to ask: would it be possible to do a ‘batch’ run of the assign-relation-ids.pl to add GOTAX IDs wherever they are missing?

(BTW, I'd like to mention Tony in this issue but I can't find a GH username for him, and he's away this week)

Thanks,

Paola

**Comment by mcourtot** [comment]
I *think* @tonysawfordebi (I just added him to the ontology team, thus his github user shows up) has worked on this and got rid of the tax id requirement. Perhaps best to wait until Monday when he's back to confirm, unless this is very urgent?

**Comment by paolaroncaglia** [comment]
Thanks Melanie. Of course I'll be happy to hear from Tony when he's back next week. However this should stay top priority because new, recently added taxon rules (other than UBERON-related) are also invisible to QuickGO, and the survey shows that 20% of GO users refer to QuickGO... (see e.g. http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000426, this is currently only_in_Saccharomyceta) 
If the GOTAX IDs are indeed no longer required, I'd expect these new constraints to be visible, or alternatively we need to do something to make them visible :-)
Let's see if Chris has any comment.

Cheers,
Paola

**Comment by mcourtot** [comment]
My understanding is that he has worked on it but it hasn't but deployed yet - I would expect that as P2GO and QuickGO rely on the same framework that would mean they would indeed show up in QuickGO once the fix is rolled out. But you're right, maybe Chris has a readily available fix.

**Comment by cmungall** [comment]
I suggest run the perl script for now but this won't be a long term fix for when we switch to inferred constraints from other ontologies

**Comment by paolaroncaglia** [comment]
Thanks Chris and Melanie. I'll wait and ask Tony before I run the script in case that causes any confusion. If Tony's fix is scheduled to be rolled out soon, then there should be no need to run Chris' script. If not, I'll figure out if it's safe to run the script.

**Comment by tonysawfordebi** [comment]
I do have a version of my taxon-checking stuff that removes the need for GOTAX identifiers, and which picks up the UBERON-derived constraints. It's currently in a testing phase, and seems to be working fine, but I'm hanging fire on putting it into production until I'm satisfied that none of the changes have broken anything.

**Comment by paolaroncaglia** [comment]
Thanks Tony, that's brilliant and I look forward to implementation. Of course I agree - best to play it safe - please comment here if you have updates, or if you notice any problem or have any concern, so Chris is aware too.

**Comment by tonysawfordebi** [comment]
My revised, GOTAX-less, constraint-checking code is now in production, and seems to be doing the right thing, so, as far as I'm concerned, GOTAX identifiers can now be consigned to the dustbin of history...

**Comment by paolaroncaglia** [comment]
That's fantastic! Thanks Tony!! 
I'll leave this ticket open a little longer in case @cmungall wishes to comment
(he's traveling at the moment).

**Comment by paolaroncaglia** [comment]
I spoke to @tonysawfordebi and he confirms that, as far as his side of things is concerned, GOTAX IDs may be safely deleted from the ontology file. (They are no longer needed, but they still live in gene_ontology_write.obo and I presume in other release files too.) Questions:

- Should we remove all GOTAX IDs from ontology files?
Probably yes; if they no longer serve a purpose, they are confusing to some people and could they possibly complicate/break things for others?

- When should we do this, and how to make sure we avoid potential issues?
After the holidays, and we may want to email go-friends in advance, to double-check if removing GOTAX IDs may create problems in third-party scripts and/or pipelines.

@tonysawfordebi please feel free to add if I'm forgetting anything.

@cmungall feel free to comment but we can wait until the New Year :-)

Thanks all,
Paola

**Comment by pgaudet** [comment]
Done here: https://github.com/geneontology/go-ontology/issues/16176
