### ISSUE TITLE
ooplasm

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12189]
I'm requesting the cellular component term "ooplasm" (The cytoplasm of an ovum. is_a cytoplasm PMID:19022436), because TermGenie rejected the request with this error message:

Error Messages
Your request produced the following list of errors.
Field	Message
label	The provided label is too short.
Please consider the messages and try to fix them, by changing the input from the previous step.

**Comment by dosumis** [comment]
What a strange check.  Short is definitely good in this case.

>

**Comment by tberardini** [comment]
@hdietze Is there really a check on length?

**Comment by hdietze** [comment]
Yes there is. I think the current minimum is eight. I could reduce this to seven?

**Comment by tberardini** [comment]
@hdietze : Yes, reduce to seven please, and let us know when that's implemented.

@slaulederkind : After Heiko confirms the reduced limit, you can repeat your request.  I'm still reviewing your earlier TG requests.  Sorry for the delay.

**Comment by hdietze** [comment]
The change has been deployed. The free form template can now accept the new class `ooplasm`.

**Comment by tberardini** [comment]
[Term]
id: GO:1990917
name: ooplasm
namespace: cellular_component
def: "The cytoplasm of an ovum." [PMID:19022436]
is_a: GO:0005737 ! cytoplasm
intersection_of: GO:0005737 ! cytoplasm
intersection_of: part_of CL:0000025 ! egg cell
created_by: sl
creation_date: 2015-12-10T21:40:16Z
