### ISSUE TITLE
NTR - CC mitochondrion-derived vesicle and BP child of GO:0016192 vesicle-mediated transport

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12193]
Based on
PMID: 18207745
PMID: 23300790
PMID: 22226745
PMID: 20619655
I think we need a new CC  
"mitochondrion-derived vesicle" (MDV)
child of GO:0031982 vesicle
Authors (PMID: 18207745) describe these as "highly distinct structures, 70–100 nm in diameter, emanating from the sides of the mitochondria". Also "... resembling intracellular-transport vesicles that were not attached to the larger mitochondria (Figure 1D, top left). They often contained inner mitochondrial membrane; however, cristae were rarely observed and, instead, the outer and inner membranes appeared as two concentric circles (Figure 1D, top left)."
Also a BP which would be a child of 
GO:0016192 vesicle-mediated transport (I think)
Not sure what to call this new process - intracellular mitochondrial vesicle transport?
In PMID: 20619655 , authors characterise regulation of this process and show "Silencing of Vps35 or Vps26A leads to a significant reduction in the delivery of MAPL to peroxisomes, placing the retromer within a novel intracellular trafficking route and providing insight into the formation of MAPL-positive MDVs"
I'd like to use these terms to annotate proteins in these papers, because they relate to a novel mitochondrial quality-control process involving PINK1 and parkin.

GOC:pad
GOC:PARL

**Comment by Pauldenny** [comment]
On problematic part of this proposed process - as yet un-named - but probably a child of 
GO:0016192 vesicle-mediated transport 
is that it's not clear whether it might actually be multiple processes with distinct end-points / destinations for the vesicles - in one paper they go to peroxisomes and in another, they go to lysosomes. Perhaps we need to make a  grouping term that could encompass either?

**Comment by Pauldenny** [comment]
David Hill @ukemi was assigned #12193 but David O-S @dosumis is looking after vesicle transport - which is best?!

**Comment by BarbaraCzub** [comment]
Thank you, @Pauldenny, for linking these issues.

**Comment by paolaroncaglia** [comment]
@ukemi this request is a duplicate of https://github.com/geneontology/go-ontology/issues/12586 (opened by @BarbaraCzub ) - note that @dosumis added some comments there. Thanks!

**Comment by ukemi** [comment]
Assigning to @dosumis so that it will be consistent with the vesicle transport things.

**Comment by BarbaraCzub** [comment]
Thank you, @paolaroncaglia for bringing this to my attention. Please note that in addition to the "mitochondrion-derived vesicle" (MDV), which @Pauldenny previously requested, I additionally suggested one more new term: "mitochondrion to lysosome transport", based on PMID-26618722, Figure 6 (Intended annotation: Q96QK1 VPS35   GO:mitochondrion to lysosome transport   AE transports_or_maintains_localisation_of O00429 DLP1). Thanks!

**Comment by dosumis** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/112839/17940312/71cb7944-6a26-11e6-8cdc-594cf9b704e7.png)

![image](https://cloud.githubusercontent.com/assets/112839/17940322/7ab3fbf8-6a26-11e6-9179-7f10c6f6e82d.png)

![image](https://cloud.githubusercontent.com/assets/112839/17940332/8456e602-6a26-11e6-9921-86511afe2236.png)

![image](https://cloud.githubusercontent.com/assets/112839/17940347/8f711828-6a26-11e6-9bf2-79ed5543d4f0.png)

![image](https://cloud.githubusercontent.com/assets/112839/17940353/94a79bdc-6a26-11e6-9dfe-cd68c0f70fe1.png)

**Comment by Pauldenny** [comment]
@BarbaraCzub  @dosumis @ukemi Thanks for doing this and tidying up all the loose ends! @paolaroncaglia

**Comment by Pauldenny** [comment]
@dosumis @ukemi @paolaroncaglia
NB see also #12193
Please add dbxrefs
GOC:bc
GOC:pad
GOC:PARL
to 
GO:0099075	mitochondrion-derived vesicle mediated transport
GO:0099073	mitochondrion-derived vesicle
GO:0099074	mitochondrion to lysosome transport
GO:0099076	mitochondrion to peroxisome transport

**Comment by paolaroncaglia** [comment]
Hi @Pauldenny ,
Just to make sure - is your request simply to add those dbxrefs to those 4 terms?
You wrote "NB see also #12193" but this *is* ticket #12193 :-)
Thanks. Paola

**Comment by Pauldenny** [comment]
Yes, please - sorry, got myself confused, because this ticket is basically same as #12586

**Comment by RLovering** [comment]
Hi

this term did not get the dbxref PARL-UCL,  GOC:bc GOC:pad; included, please add this to 

GO:0099075 mitochondrion-derived vesicle mediated transport
GO:0099073 mitochondrion-derived vesicle
GO:0099074 mitochondrion to lysosome transport
GO:0099076 mitochondrion to peroxisome transport

as requested by Paul above

Best

Ruth

**Comment by hdrabkin** [comment]
Added these dbxrefs as requested. @ukemi   this appears to be done right? It was reopened only to add the dbxrefs?

**Comment by ukemi** [comment]
As far as I can tell, this is correct.
