### ISSUE TITLE
new term request: establishment of protein localization to cajal body

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12198]
Hi,

New term request please.

Term: establishment of protein localization to cajal body

Definition:  The directed movement of a protein to the cajal body in the nucleus.

child of: GO:0044744 protein targeting to nucleus

or better suggestions please.

GOC: BHF
GOC: BHF_telomere
GOC: nc

PMID: 25467444.
I want to annotate the TRiC components (apart from CCT1 and CCT2) to this requested term. Figure S1F. Also author states: "Analyzing the TCAB1 channel in a similar manner, we found that TRiC subunits were also required for TCAB1 localization to Cajal bodies (Figure S1F), demonstrating that multiple telomerase components were perturbed due to TRiC depletion".

Thanks

Nancy

**Comment by tberardini** [comment]
Hi Nancy - do you know if there are protein targeting signals involved?  I'm trying to figure out how to best place your requested term and name it.

Possible names (and parentage):

(1) establishment of protein localization to cajal body (is_a establishment of protein localization to organelle)
(2) protein localization to cajal body (is_a protein localization to nucleus)
(3) protein targeting to cajal body   (is_a protein targeting to nucleus)


Parent definitions are here:

protein targeting to nucleus: The process of directing proteins towards the nucleus, usually using signals contained within the protein.

protein localization to nucleus: A process in which a protein is transported to, or maintained in, a location within the nucleus.

establishment of localization to organelle: The directed movement of a protein to a specific location on or in an organelle. Encompasses establishment of localization in the membrane or lumen of a membrane-bounded organelle.


From this issue information alone, without looking at the paper, I would recommend (2).  Feedback welcome.

**Comment by NancyCampbell** [comment]
Hi Tanya,
Thanks for looking into this and clarifiying the differences between the different possible parents.
From this, I agree, 2 seems the best option.
Thanks Tanya.
Nancy

**Comment by tberardini** [comment]
Added using TG.  The parentage was even better:


[Term]
id: GO:1904867
name: protein localization to Cajal body
namespace: biological_process
def: "A process in which a protein is transported to, or maintained in, a location within a Cajal body." [GO_REF:0000087, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:25467444]
synonym: "protein localisation in Cajal body" EXACT [GOC:TermGenie]
synonym: "protein localisation to Cajal body" EXACT [GOC:TermGenie]
synonym: "protein localization in Cajal body" EXACT [GOC:TermGenie]
is_a: GO:1903405 {is_inferred="true"} ! protein localization to nuclear body
intersection_of: GO:0008104 ! protein localization
intersection_of: has_target_end_location GO:0015030 ! Cajal body
relationship: has_target_end_location GO:0015030 {is_inferred="true"} ! Cajal body
created_by: tb
creation_date: 2015-12-17T21:48:18Z
