### ISSUE TITLE
GO:0034335 request to reinstate the obsolete term: DNA supercoiling activity

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#12197]
Hi,
I'd like to have this term reinstated please. The Comment says:
"This term was made obsolete because, although it was requested, it is not needed after all; it was not defined clearly, and does not necessarily correspond to a catalytic activity."
In bacteria DNA gyrase (a type II topoisomerase) composed of GyrA and GyrB, can in all but 1 known example introduce negative supercoils into DNA, among the very first demonstrations of this is PMID 186775. As chance would have it the E.coli enzyme is a very good supercoiler, other enzymes (for example M.tuberculosis, PMIDs 19787774 and 22457352, and S.typhimurium, PMID 17400739) cannot introduce as many negative supercoils. The corresponding enzyme from Aquifex aeolicus has an unusual A subunit and is unable to introduce negative supercoils (PMID 21076033), and for this enzyme I would actually like to be able to annotate NOT DNA supercoiling activity. 

Many bacteria have 2 type II topoisomerases; DNA gyrase and topoisomerase IV. Topoisomerase IV cannot introduce supercoils either, thus type II topoisomerase activity is not synonymous with supercoil introduction.

So I suggest a modified definition, which also hopefully warns the user about the variations in activity. This should be a child of GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity, but the synonyms 
"exact 	DNA-gyrase activity" and 
"exact 	DNA gyrase activity" 
should be moved to the reinstated term. This is my suggestion for a definition:

"Catalytic introduction of supercoils in a DNA molecule or region thereof.
In bacteria negative supercoils are only introduced by DNA gyrase, a type
II topoisomerase, but not all DNA gyrases are capable of introducing
supercoils. In bacteria the level of supercoiling varies widely between
species and has been characterized properly in only a handful of organisms.
The best characterized enzyme, from E.coli, is exceptionally proficient at
supercoiling and this ability is not representative of all bacteria."
thanks, Andrea

**Comment by tberardini** [comment]
To be discussed at GO editors call during next phone call (12/17).

**Comment by tberardini** [comment]
Reinstated.  Synonyms removed from parent term and the related regulation terms as well.
---------------
[Term]
id: GO:0034335
name: DNA supercoiling activity
namespace: molecular_function
def: "Catalytic introduction of supercoils in a DNA molecule or region thereof. In bacteria, negative supercoils are only introduced by DNA gyrase, a type II topoisomerase, but not all DNA gyrases are capable of introducing supercoils. In bacteria, the level of supercoiling varies widely between species and has been characterized properly in only a handful of organisms. The best characterized enzyme, from E.coli, is exceptionally proficient at supercoiling and this ability is not representative of all bacteria." [GOC:mah]
is_a: GO:0003918 ! DNA topoisomerase type II (ATP-hydrolyzing) activity
synonym: "DNA-gyrase activity" EXACT []
synonym: "DNA gyrase activity" EXACT []
comment: Note that this term was reinstated from obsolete.
