### ISSUE TITLE
new term request: telomerase RNA localization

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12199]
Hi,

New term request please.

Term: telomerase RNA localization

Definition: Any process in which telomerase RNA is transported to, or maintained in, a specific location.

child of:  GO:0006403 RNA localization

or better suggestions please.

GOC: BHF
GOC: BHF_telomere
GOC: nc

PMID: 25467444.
I want to annotate the TRiC components (apart from CCT1 and CCT2) to this requested term. Figure 1C & 1D. Also author states: "...., hits included four members of TRiC: CCT8, CCT4, CCT7, and CCT6A (Figure 1 D)".

Thanks

Nancy

**Comment by NancyCampbell** [comment]
Also, may i request child of this new term 
Term: telomerase RNA localization to cajal body
Definition: Any process in which telomerase RNA is transported to, or maintained in the cajal body.
same GOC please.
thanks

**Comment by tberardini** [comment]
Hi Nancy - It's the telomerase RNA that's being transported, right?  Is it possible to do the annotation using the annotation extension field for the gene product itself plus 'RNA localization'?  I'm reluctant to add a term for the localization of the RNA of a specific gene.  

I can add 'RNA localization to cajal body', without the 'telomerase bit' for you to use in a similar fashion.

**Comment by NancyCampbell** [comment]
Hi Tanya,
Please see response to ticket  #12200.
This new term would fall in line with other children of GO:0006403 RNA localization such as the distinct classes of scaRNA and snoRNA localization.

<img width="1115" alt="screen shot 2015-12-17 at 16 16 05" src="https://cloud.githubusercontent.com/assets/12081136/11874883/b5165682-a4d9-11e5-9375-44ce076999cb.png">
Thanks Tanya.

**Comment by tberardini** [comment]
Got it!  Thanks.
----------------
+[Term]
+id: GO:0090670
+name: RNA localization to Cajal body
+namespace: biological_process
+def: "A process in which an RNA is transported to, or maintained in, a Cajal body." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:25467444]
+is_a: GO:0006403 ! RNA localization
+created_by: tanyaberardini
+creation_date: 2015-12-17T14:04:40Z
+
+[Term]
+id: GO:0090671
+name: telomerase RNA localization to Cajal body
+namespace: biological_process
+def: "A process in which telomerase RNA (TERC) is transported to, or maintained in, a Cajal body." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:25467444]
+is_a: GO:0090670 ! RNA localization to Cajal body
+is_a: GO:0090672 ! telomerase RNA localization
+created_by: tanyaberardini
+creation_date: 2015-12-17T14:06:21Z
+
+[Term]
+id: GO:0090672
+name: telomerase RNA localization
+namespace: biological_process
+def: "Any process in which telomerase RNA is transported to, or maintained in, a specific location." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:25467444]
+is_a: GO:0006403 ! RNA localization
+created_by: tanyaberardini
+creation_date: 2015-12-17T14:08:01Z

**Comment by NancyCampbell** [comment]
Thank you Tanya! You are so quick!
