### ISSUE TITLE
Wrong IntEnz xref on GO:0009033 trimethylamine-N-oxide reductase activity?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12192]
Proteins manually annotated to the above MF are also annotated to EC 1.7.2.3 in UniProt but the Go terms is linked to EC 1.6.6.9. It should probably be consistent...

Complex in question is Trimethylamine-N-oxide reductase TorAC complex, participants P33225 (TORA_ECOLI) & P33226 (TORC_ECOLI), annotated to GO:0009322 trimethylamine-N-oxide reductase complex, capable_of GO:0009033 trimethylamine-N-oxide reductase activity.

The complex is not yet released.

Birgit

**Comment by tberardini** [comment]
GO definition:  "Catalysis of the reaction: NADH + H+ + trimethylamine-N-oxide = NAD+ + trimethylamine + H2O." [EC:1.6.6.9]

http://enzyme.expasy.org/EC/1.6.6.9 = Trimethylamine-N-oxide reductase. 

NADH + trimethylamine N-oxide <=> NAD(+) + trimethylamine + H(2)O
GO def: def: "Catalysis of the reaction: NADH + H+ + trimethylamine-N-oxide = NAD+ + trimethylamine + H2O." [EC:1.6.6.9]


http://enzyme.expasy.org/EC/1.7.2.3 = Trimethylamine-N-oxide reductase (cytochrome c). 

Trimethylamine + 2 (ferricytochrome c)-subunit + H(2)O <=> trimethylamine N-oxide + 2 (ferrocytochrome c)-subunit + 2 H(+)


Are you sure it's GO that needs updating and not the "Proteins manually annotated to the above MF are also annotated to EC 1.7.2.3 in UniProt"?

**Comment by bmeldal** [comment]
Ah, I missed something: It's the ANNOTATIONS that probably need to be moved! Should this ticket be moved to the other tracker?

There are 4 proteins manually annotated to GO:0009033 GO http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009033. One is a SwissProt entry (http://www.uniprot.org/uniprot/Q9KRF0) and has EC 1.7.2.3 annotation in Uniprot. The other 3 are TrEMBL entries only. All GO annotations are by sequence alignment/similarity. 

Similarly, the 2 manually annotated proteins to GO:0050626 trimethylamine-N-oxide reductase (cytochrome c) activity http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0050626 are SwissProt and also annotated to EC 1.7.2.3.

All these proteins are from the same protein family.

This leads me to believe that at least the SwissProt protein annotated to GO:0009033, and possible all 4 manually annotated protein here, should be annotated to GO:0050626. Then the 100s of inferred annotations will follow...

Apologies for the confusion!

Birgit

**Comment by tberardini** [comment]
Yes, please move the ticket to the annotation tracker and then close this one.  Thanks.
https://github.com/geneontology/go-annotation/issues

**Comment by bmeldal** [comment]
Moved to annotation tracker https://github.com/geneontology/go-annotation/issues/1340
