### ISSUE TITLE
NTR: dopaminergic neuron axon guidance

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12191]
2 new terms for me to add:

dopaminergic neuron axon guidance ; GO:NEW1
The chemotaxis process that directs the migration of an axon growth cone of a dopaminergic neuron to a specific target site in response to a combination of attractive and repulsive cues.
PMID: 23517308, GOC:PARL, GOC:bf
is_a: 
intersection_of: GO:0007411 ! axon guidance
intersection_of: occurs_in CL:0000700 ! dopaminergic neuron

chemorepulsion of dopaminergic neuron axon ; GO:NEW2
The process in which a dopaminergic neuron growth cone is directed to a specific target site in response to a repulsive chemical cue.
PMID: 23517308, GOC:PARL, GOC:bf
is_a: chemorepulsion of axon ; GO:0061643
intersection_of: GO:0061643 ! chemorepulsion of axon
intersection_of: occurs_in CL:0000700 ! dopaminergic neuron

dopaminergic neuron axon guidance ; GO:NEW1
--[partof]chemorepulsion of dopaminergic neuron axon ; GO:NEW2

Similar to existing other axon guidance terms for specific neuron subtypes.

**Comment by rebeccafoulger** [comment]
Also will add in related terms for annotation of PMID:21106844:

serotonergic axon guidance (serotonergic neuron = CL_0000850)

chemoattraction of dopaminergic neuron (for Wnt7b)
chemoattraction of serotonergic neuron (for Wnt5a)

**Comment by rebeccafoulger** [comment]
Added terms for:
dopaminergic neuron axon guidance ; GO:0036514
chemorepulsion of dopaminergic neuron axon ; GO:0036518
chemoattraction of dopaminergic neuron axon ; GO:0036516

serotonergic neuron axon guidance ; GO:0036515
chemorepulsion of serotonergic neuron axon ; GO:0036519
chemoattraction of serotonergic neuron axon ; GO:0036517

Need to add in logical defs for the serotonergic terms (serotonergic neuron = CL_0000850)
Need to add in logical refs for the chemorepulsion/attraction terms.

Logical defs of the chemoattraction/repulsion terms could follow the same pattern as the existing 'chemoattraction of axon ; GO:0061642' term. E.g:
chemoattraction of dopaminergic neuron axon ; GO:0036516
intersection_of: GO:0050918 ! positive chemotaxis
intersection_of: part_of GO:0036514 ! dopaminergic neuron axon guidance

**Comment by paolaroncaglia** [comment]
Hi Becky,

Logical defs as above look good to me...

Cheers,

Paola

**Comment by rebeccafoulger** [comment]
Added logical defs in as described above:

E.g.
chemoattraction of dopaminergic neuron axon ; GO:0036516
intersection_of: GO:0050918 ! positive chemotaxis
intersection_of: part_of GO:0036514 ! dopaminergic neuron axon guidance
