### ISSUE TITLE
parent of NEW GO:1990914 integral component of periplasmic side of plasma membrane

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12194]
I created this term in TG FF yesterday and just noticed that its parent should be 
is_a GO:0031237 intrinsic component of periplasmic side of plasma membrane.

Sorry, I missed that. I though the "intrinsic component of ~" didn't exist as the "integral component of ~" didn't exist. 

Birgit

**Comment by bmeldal** [comment]
related to issues #12196

**Comment by tberardini** [comment]
@dosumis If you can provide feedback, I can do the work.  Does this look ok?  Stanza from TG is this:

[Term]
id: GO:1990914
name: integral component of periplasmic side of plasma membrane
namespace: cellular_component
def: "The component of the plasma membrane consisting of the gene products that penetrate only the periplasmic side of the membrane." [GOC:bhm, IntAct:EBI-11297444, PMID:15919996]
comment: An example of this is hyaA in E. coli (P69739) in PMID:23260654 (inferred from direct assay).
subset: termgenie_unvetted
is_a: GO:0005887 ! integral component of plasma membrane
created_by: bhm
creation_date: 2015-12-09T14:38:57Z

**Comment by bmeldal** [comment]
It should have both parents, right?
is_a GO:0005887 integral component of plasma membrane
is_a GO:0031237 intrinsic component of periplasmic side of plasma membrane

**Comment by dosumis** [comment]
We have design patterns for creating these which automatically classifies these terms correctly (and will reclassify them correctly if we add new terms).  Unfortunately these haven't yet made it into Term Genie templates.  Tanya: can you update to add: 

intersection_of: 'integral component of membrane'
intersection_of: part_of 'periplasmic side of plasma membrane'

**Comment by bmeldal** [comment]
Thanks, David!

**Comment by tberardini** [comment]
Thanks, David.

Done.

[Term]
id: GO:1990914
name: integral component of periplasmic side of plasma membrane
namespace: cellular_component
def: "The component of the plasma membrane consisting of the gene products that penetrate only the periplasmic side of the membrane." [GOC:bhm, IntAct:EBI-11297444, PMID:15919996]
comment: An example of this is hyaA in E. coli (P69739) in PMID:23260654 (inferred from direct assay).
is_a: GO:0005887 ! integral component of plasma membrane
intersection_of: GO:0005887 ! integral component of membrane
intersection_of: part_of GO:0098567 ! periplasmic side of plasma membrane
created_by: bhm
creation_date: 2015-12-09T14:38:57Z
