### ISSUE TITLE
Axiomatize molecular function regulators

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12195]
At the LEGO meeting, it would be useful to have equivalence axioms for MF regulator, activator, inhibitor - to see the inference directly in Noctua

cc @ukemi @vanaukenk

**Comment by pgaudet** [comment]
We now have logical definitions for 
* molecular function regulator 
* enzyme regulator activity
* enzyme activator activity
* enzyme inhibitor activity
* channel regulator activity
* channel activator activity
 *channel inhibitor activity
*receptor regulator activity
*receptor activator activity
*receptor inhibitor activity

I think that cover its !
