### ISSUE TITLE
 new term request: scaRNA localization to cajal body (easy)

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12202]
Hi,

New term request please.

Term: scaRNA localization to cajal body

Definition: Any process in which scaRNA is transported to, or maintained in the cajal body.

child of: (new term) scaRNA localization definition: Any process in which scaRNA is transported to, or maintained in, a specific location. child of: GO:0006403 RNA localization

or better suggestions please.

GOC: BHF
GOC: BHF_telomere
GOC: nc

PMID: 25467444.
I want to annotate the TRiC components to this requested term. Figure 2C. Also author states: "In all cases, we found that TRiC knockdown resulted in partial mislocalization of these scaRNAs to nucleoli to a degree that phenocopied TCAB1 knockdown (Figures 2C, 2D,S2B, and S2C) (p < 0.001 by Fisher’s exact test). These data demonstrate that TRiC is required for the proper localization of TERC, as well as multiple scaRNAs, to Cajal bodies.".

Thanks

Nancy

**Comment by tberardini** [comment]
Hi Nancy - I added only one term.  From looking at the paper and one related one, (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC126017/), it looks like the scaRNAs are only localized to the Cajal body so it doesn't make sense to create the intermediate term that is more general.  

+id: GO:0090666
+name: scaRNA localization to Cajal body
+namespace: biological_process
+def: "A process in which a small Cajal body-specific RNA is transported to, or maintained in, a Cajal body." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:25467444]
+is_a: GO:0006403 ! RNA localization
+created_by: tanyaberardini
+creation_date: 2015-12-15T10:57:05Z

**Comment by NancyCampbell** [comment]
That is perfectly fine. Thanks Tanya for looking into this and for creating the new term.
Nancy
