### ISSUE TITLE
NTR:endothelial cell chemotaxis to vascular endothelial growth factor

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12203]
Hi,

I would like a new term equivalent to GO:0035768 endothelial cell chemotaxis to fibroblast growth factor but for vascular endothelial growth factor, i.e. "endothelial cell chemotaxis to vascular endothelial growth factor".
Definition: The directed movement of an endothelial cell in response to the presence of vascular endothelial growth factor (VEGF). 

I also need the regulation child terms, but I could add these in TermGenie if preferred.

Evidence for usage in PMID:21885851.

Please add references GOC:rph, GOC:BHF and GOC:BHF_miRNA

Thanks,
Rachael.

**Comment by tberardini** [comment]
+id: GO:0090667
+name: cell chemotaxis to vascular endothelial growth factor
+namespace: biological_process
+def: "The directed movement of a motile cell in response to the presence of vascular endothelial growth factor (FGF)." [GOC:BHF, GOC:BHF_miRNA, GOC:rph, PMID:21885851]
+is_a: GO:0060326 ! cell chemotaxis
+relationship: part_of GO:0035924 ! cellular response to vascular endothelial growth factor stimulus
+created_by: tanyaberardini
+creation_date: 2015-12-15T11:27:12Z
+
+[Term]
+id: GO:0090668
+name: endothelial cell chemotaxis to vascular endothelial growth factor
+namespace: biological_process
+def: "The directed movement of an endothelial cell in response to the presence of vascular endothelial growth factor (VEGF)." [GOC:BHF, GOC:BHF_miRNA, GOC:rph, PMID:21885851]
+is_a: GO:0090667 ! cell chemotaxis to vascular endothelial growth factor
+created_by: tanyaberardini
+creation_date: 2015-12-15T11:31:43Z

**Comment by tberardini** [comment]
Please add the needed regulation terms using TermGenie.
