### ISSUE TITLE
NTR: excitatory synapse assembly

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12205]
I can add this in TG, but wanted to check first whether it fits with your synapse edits @dosumis

NTR: excitatory synapse assembly
is_a: synapse assembly ; GO:0007416
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: results_in_assembly_of GO:0060076 ! excitatory synapse

The postsynaptic density terms could move under the new term, based on their current definition. E.g:
synapse assembly ; GO:0007416
--[isa]excitatory synapse assembly ; GO:NEW
----[partof]postsynaptic density assembly ; GO:0097107

Would then need to create regulation terms to annotate Wnt signaling components Wnt7a and Dvl1 in PMID:21670302.

Would also make sense to create corresponding inhibitory synapse assembly terms.

Thanks.

**Comment by paolaroncaglia** [comment]
Assigning to David for review, thanks

**Comment by dosumis** [comment]
Looks good. Please add via TG.

(BTW I've just added 'postsynaptic density' part_of excitatory synapse, so this is consistent with CC.  Would be nice to infer that part_of, but we don't have a mechanism yet.)

**Comment by rebeccafoulger** [comment]
New terms:
ID: GO:1904861 Label: excitatory synapse assembly
ID: GO:1904862 Label: inhibitory synapse assembly

Left to do on this ticket:
1. Move postsynaptic density process terms under GO:1904861
2. Add regulation terms.

**Comment by rebeccafoulger** [comment]
Added regulation terms:
regulation of excitatory synapse assembly ; GO:1904889
negative regulation of excitatory synapse assembly ; GO:1904890
positive regulation of excitatory synapse assembly ; GO:1904891

Left to do on this ticket:
 Move postsynaptic density process terms under GO:1904861
--[isa]excitatory synapse assembly ; GO:1904861 (NEW)
----[partof]postsynaptic density assembly ; GO:0097107

**Comment by rebeccafoulger** [comment]
GO:0097107 moved, so this ticket is all done.
