### ISSUE TITLE
GO:1990918 & recombination

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12206]
I've also looked at PMID:15238514 (Antonia requested phenotype terms), and it looks at double-strand break repair in the context of meiotic recombination. I therefore think the term Antonia requested for it, GO:1990918, can be made more specific, by changing to:

name: double-strand break repair involved in meiotic recombination
def: "The repair of double-strand breaks in DNA via homologous and nonhomologous mechanisms to reform a continuous DNA helix that contributes to reciprocal meiotic recombination." [PMID:15238514]
is_a: GO:0006302 ! double-strand break repair
relationship: part_of GO:0007131 ! reciprocal meiotic recombination

thanks,
m

**Comment by paolaroncaglia** [comment]
Done, thanks.
