### ISSUE TITLE
Urgent: NTR: maintenance of mitotic sister chromatid cohesion, telomeric

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12209]
Proposed definition: The process in which the association between sister chromatids of a replicated chromosome along the length of the telomeric region is maintained as chromosomes condense, attach to the spindle in a bipolar orientation, and congress to the metaphase plate during a mitotic cell cycle. 

Note there are two other terms for the other portions of the sister chromatids;
maintenance of mitotic sister chromatid cohesion, centromeric
maintenance of mitotic sister chromatid cohesion, arms

Please add GOC:rph, GOC:BHF and GOC:BHF_telomere
For annotation of PMID:26373281

Thanks,
Rachael.

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by dosumis** [comment]
label "maintenance of mitotic sister chromatid cohesion, telomeric"@en
definition "The process in which the association between sister chromatids of a replicated chromosome along the length of the telomeric region is maintained as chromosomes condense, attach to the spindle in a bipolar orientation, and congress to the metaphase plate during a mitotic cell cycle." [GOC:rph, GOC:BHF, GOC:BHF_telomere, PMID:26373281]
has_exact_synonym "maintenance of mitotic sister chromatin cohesion at telomere"^^string
has_exact_synonym "maintenance of sister chromatin cohesion at telomere at mitosis"^^string
has_exact_synonym "maintenance of telomeric mitotic sister chromatin cohesion"^^string
has_obo_namespace "biological_process"^^string
SubClassOf: 'maintenance of mitotic sister chromatid cohesion'
'part of' some 'mitotic sister chromatid cohesion, telomeric'

label "mitotic sister chromatid cohesion, telomeric"@en
definition "The cell cycle process in which telomeres of sister chromatids are joined during mitosis." [GOC:rph, GOC:BHF, GOC:BHF_telomere, PMID:26373281]
has_exact_synonym "mitotic sister chromatid cohesion at telomere"^^string
has_exact_synonym "sister chromatid cohesion at telomere at mitosis"^^string
has_exact_synonym "telomeric mitotic sister chromatin cohesion"^^string
has_obo_namespace "biological_process"^^string
SubClassOf: 'mitotic sister chromatid cohesion'
