### ISSUE TITLE
 NTR new child under Protein Complexes

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12201]
Copied from TG tracker:

I’m trying to add a new protein binding term in termgenie. Either
‘glycoprotein complex’, which I do not see how to add. Or I tried ‘by
activity’ and added the MF ‘cellulose binding’ for 'cellulose binding protein complex ' as the complex binds
that, but since it’s not an activity GO term I can’t do that.

I think ‘glycoprotein complex’ would be the term I want to add, a simple child of GO:0043234 protein
complex and parent of the specific glycoprotein terms (such as GO:0016010 dystrophin-associated glycoprotein complex). This is such a simple new term, would be strange not to use termgenie for that.

A: protein_complex_by_citation
This would allow adding this simple term and the reference(s) describing the complex should be enough.

B: protein_complex_by_protein_binding
Could ask for UniProt IDs of the complex partners, but this would probably go too far for Termgenie

PMIDs 7693675, 8662961
I added the following comment when trying termgenie: An example is the
Dictyostelium multi protein pspB complex, which is secreted from
prespore vesicles and incorporated into the spore coat.

created by @pfey03

**Comment by tberardini** [comment]
Clarification:  What is the term that you are trying to create right now?

'glycoprotein complex'

or

'glycoprotein complex binding'
?

**Comment by pfey03** [comment]
I'd like to add the complex term 'glycoprotein complex'I thought it's such a simple addition and should be possible in TermGenie, so I was surprised that I couldn't. So if you just add the term for now is fine, but and expansion of templates to add simple complex terms should be considered.

Thanks Tanya!

**Comment by tberardini** [comment]
Thanks for the clarification, Petra. I'll get to adding your term by the end of this week.
We'll discuss the possibility of a new template during the next editors' call (12/17).

**Comment by bmeldal** [comment]
Hi Petra,

I agree, 'glycoprotein complex' would be a useful grouping term and probably one we'd need anyway for the restructuring! Could you please check if there are any relevant capable_of and capable_of_part_of relationships that Tanya could add so that it's easier for the reasoner to place other children under this new term?

Btw, you can use the TG free form to create this term and add all its relationships as well as xrefs, synonyms and example comment. If you haven't got access I'm sure Tanya can help.

I also agree that 'x binding', where x=uniprot ID, is going too far. There was a discussing about adding 'protein family binding' terms via template but I think that's still under discussion.

Birgit

**Comment by pfey03** [comment]
Thanks a lot Tanya!

Im not seeing any link to the TG free form when logged in, not sure if that means I have no access.

Birgit, I'm not very familiar with the capable_of relationships. But in my cited case:
pspB complex capable_of_part_of GO:0031160:spore wall

It's this specific glycoprotein complex, is this what you are looking for?

Thanks! Petra

**Comment by bmeldal** [comment]
Hi Petra,

FF is at http://go.termgenie.org/TermGenieFreeForm.html and has the same logon credentials as the template but let Tanya advise you.

We are trying to add the MF and BP to the complexes which the reasoner picks up and uses to place other complexes with the same relationships as children.

The structure is
capable_of some MF
capable_of_part_of some BP

but it has to be applicable to all children of the complex. Spore wall would have the part_of relationship but it's restrictive to those glycoproteins found at the spore wall only. part_of relationship have to be ALWAYS true. I have that problem myself when I have subcomplexes that are part of different structures. GO requires you to use different terms or leave out the relationship.

It's different for annotations as they provide a snapshot of the molecule at a given place and time!

Any questions, just ask!

Birgit

**Comment by tberardini** [comment]
[Term]
+id: GO:0090665
+name: glycoprotein complex
+namespace: cellular_component
+def: "A protein complex containing at least one glycosylated protein, may be held together by both covalent and noncovalent bonds." [GOC:pf, PMID:7693675, PMID:8662961]
+comment: An example is the Dictyostelium multi protein pspB complex, which is secreted from prespore vesicles and incorporated into the spore coat.
+is_a: GO:0043234 ! protein complex
+created_by: tanyaberardini
+creation_date: 2015-12-11T17:45:23Z

**Comment by bmeldal** [comment]
Tanya,

The comment got truncated in QuickGo. Could you check that it went into the file ok?

Thanks,
Birgit

**Comment by tberardini** [comment]
Yes, it looks like the comment went into the file alright.  There was an included line break (\n).  Just in case that was a problem, I've removed the line break and recommitted the file.

**Comment by bmeldal** [comment]
Thanks, Tanya.
