### ISSUE TITLE
new term request: telomerase RNA stabilization

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12200]
Hi,

New term request please.

Term: telomerase RNA stabilization.

Definition: Prevention of degradation of telomerase RNA (TERC) molecules.

child of: GO:0043489 RNA stabilization

or better suggestions please.

GOC: BHF
GOC: BHF_telomere
GOC: nc

PMID: 25467444.
I want to annotate dyskerin (DKC1) to this requested term. Figures 2A & 2B. Also author states: " In contrast, depletion of dyskerin (DKC1) resulted in a global reduction in TERC signal, which is consistent with the function of dyskerin in TERC stability and assembly. Unlike depletion of dyskerin, neither TCAB1 depletion nor depletion of any TRiC subunit reduced TERC level measured by northern blot (Figure 2B)".

Thanks

Nancy

**Comment by tberardini** [comment]
Hi Nancy - again, I'm reluctant to add terms for the RNAs of specific genes.  Can you use 'RNA stabilization' plus annotation extension to refer to the telomerase gene product?

**Comment by NancyCampbell** [comment]
Hi Tanya,

TERC (aka telomerase RNA) is unique in the sense that it stands as the only one in a distinct class of RNAs. For review PMID    24679528, table 1 i.e. a class of one.

Telomerase RNA (or telomerase RNA component) is the RNA component of the telomerase enzyme, and it forms the template part that is used to add more TTAGGG repeats to the end of telomeres (repeating TTAGGG sequence is conserved in vertebrates). TERC contains an H/ACA box motif similarly to scaRNA, snoRNA and others. For review PMID 25590339 (figure 2 shown below):
<img width="930" alt="screen shot 2015-12-17 at 15 54 19" src="https://cloud.githubusercontent.com/assets/12081136/11874243/8f25c668-a4d6-11e5-8f07-d910a77c6fcb.png">

Instead of thinking about TERC as a gene product, it is more approriate to think about it as a representative of a distinct class of H/ACA box containing long non-coding RNA subtype (which happens to contain only one member TERC, so far). TERC serves a function due to its unique structure and association with the telomerase protein.

Furthermore, TERC (aka telomerase RNA) is not the transcribed RNA of the telomerase gene that then goes on to be translated into the telomerase protein which is part of the telomerase enzyme. TERC is the long non-coding RNA transcribed from a distinct gene ENSG00000270141.

Sorry for the long details. I hope it makes sense.

Thanks Tanya.

**Comment by tberardini** [comment]
Yes, this makes sense.  Thank your for the clarification.  I learned something cool today!

 [Term]
+id: GO:0090669
+name: telomerase RNA stabilization
+namespace: biological_process
+def: "Prevention of degradation of telomerase RNA (TERC) molecules." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:25467444]
+synonym: "TERC stabilization" EXACT []
+is_a: GO:0043489 ! RNA stabilization
+created_by: tanyaberardini
+creation_date: 2015-12-17T14:01:11Z

**Comment by NancyCampbell** [comment]
Thank you so much for sorting this out so quickly. Much appreciated. Enjoy the holidays! x

**Comment by tberardini** [comment]
You're very welcome.  Happy Holidays to you too.
