### ISSUE TITLE
Urgent: 2xNTR:establishment of RNA/complex localization to telomere

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12208]
Hi,
Please note this is an urgent request, I need these terms before Christmas - thanks!

Could I please have two new terms;
1. "establishment of RNA localization to telomere." Def: The directed movement of an RNA to a specific location in the telomeric region of a chromosome. 

2. "establishment of macromolecular complex localization to telomere." Def: The directed movement of a macromolecular complex to a specific location in the telomeric region of a chromosome. 

Note, there is already a term for establishment of protein localization to telomere (GO:0070200)

Please add GOC:rph, GOC:BHF and GOC:BHF_telomere
For annotation of PMID:26586433

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by paolaroncaglia** [comment]
Hi Rachael and Nancy,

Here are your new terms, full stanzas below.
Please note that the GO build currently has an error, so I'm not sure exactly when the new terms will be live effectively, but hopefully by the New Year! I'm closing this ticket now; feel free to re-open/comment if there's any problem.

Cheers,
Paola

[Term]
id: GO:0097694
name: establishment of RNA localization to telomere
namespace: biological_process
def: "The directed movement of RNA to a specific location in the telomeric region of a chromosome." [GOC:BHF, GOC:BHF_telomere, GOC:rph, PMID:26586433]
synonym: "establishment of RNA localisation to telomere" EXACT []
is_a: GO:0051236 ! establishment of RNA localization
intersection_of: GO:0051236 ! establishment of RNA localization
relationship: has_target_end_location GO:0000781 ! chromosome, telomeric region

[Term]
id: GO:0097695
name: establishment of macromolecular complex localization to telomere
namespace: biological_process
def: "The directed movement of a macromolecular complex to a specific location in the telomeric region of a chromosome." [GOC:BHF, GOC:BHF_telomere, GOC:rph, PMID:26586433]
synonym: "establishment of macromolecular complex localisation to telomere" EXACT []
is_a: GO:0051234 ! establishment of localization
relationship: part_of GO:0070727 ! cellular macromolecule localization
