### ISSUE TITLE
add synonyms to t-loop terms

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12217]
Hi 
Please add synonyms as follows:
GO:0090657 telomeric loop disassembly 
synonyms: exact: t-loop disassembly

GO:0031627 telomeric loop formation
synonyms: exact: T loop formation
exact: T loop biosynthesis

I don't think it is worth the time it will take to create all these synonyms in the regulation terms for these processes, but I had not found telomeric loop disassembly because I had used the search t-loop, and was thinking of requesting this term.

Thanks

Ruth

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by dosumis** [comment]
DONE
