### ISSUE TITLE
Proposed obsoletion: single-organism process

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12212]
This class was originally created when we thought it would be a good idea to have a set of disjoint grouping classes based on granularity at the top of the ontology.

Increasingly this has become problematic. There are many processes such as 'regulation of fluid levels' which we once assumed single-organism can now turn out to be multi-organism (e.g. when a komodo dragon bites its prey, the venom proteins induce bleeding hastening death and a meal for the dragon). Many behaviors are susceptible to cross-organism regulation.

I checked with grebe and there are no direct annotations.

If the term shows up in enrichment analyses, I believe these to be non meaningful.

Note that we can obsolete this class without immediately obsoleting the full 'single-organism-X'. That may come later, but will require more work to transfer annotations.

**Comment by paolaroncaglia** [comment]
(Added to agenda for our first editors call in 2016.)

**Comment by pgaudet** [comment]
Hello, 

I am curious to know what is planned for the children terms, for example
- GO:0044419 interspecies interaction between organisms
-  GO:0035821 modification of morphology or physiology of other organism
(etc.) 
These would be directly under 'biological process'? 

Thanks, 
Pascale

**Comment by cmungall** [comment]
the proposal is only for SOP, not MOP

**Comment by dosumis** [comment]
These terms could all be potentially removed via merge to the closest organism number agnostic parent class.

List of all single organism process terms:

GO:0098602	single organism cell adhesion
GO:0044702	single organism reproductive process
GO:0044700	single organism signaling
GO:0016337	single organismal cell-cell adhesion
GO:0044708	single-organism behavior
GO:0044711	single-organism biosynthetic process
GO:0044724	single-organism carbohydrate catabolic process
GO:0044723	single-organism carbohydrate metabolic process
GO:0044712	single-organism catabolic process
GO:1902580	single-organism cellular localization
GO:0044763	single-organism cellular process
GO:0044767	single-organism developmental process
GO:1902585	single-organism intercellular transport
GO:1902582	single-organism intracellular transport
GO:1902578	single-organism localization
GO:1902538	single-organism macropinocytosis
GO:1902591	single-organism membrane budding
GO:0044801	single-organism membrane fusion
GO:1902534	single-organism membrane invagination
GO:0044802	single-organism membrane organization
GO:0044710	single-organism metabolic process
GO:1902540	single-organism micropinocytosis
GO:1902593	single-organism nuclear import
GO:1902589	single-organism organelle organization
GO:1902536	single-organism pinocytosis
GO:1902587	single-organism plasmodesmata-mediated intercellular transport
GO:0044699	single-organism process
GO:0044704	single-organism reproductive behavior
GO:0044765	single-organism transport

Of these, only the following have been used in annotation:

GO:0016337	single organismal cell-cell adhesion    (310 times)
GO:0044702	single organism reproductive process (2 times)
GO:0044704	single-organism reproductive behavior (1 time) 
GO:0044708	single-organism behavior (2 times)

Mostly, this comes from a name change when the distinction was introduced into the cell-cell adhesion branch:
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016337#term=history
- justified by need to segregate lots of yeast cell-cell adhesion annotations with completely unrelated mechanisms.  Need to decide whether to keep this distinction, or to make the distinction clear via mechanism.

**Comment by pgaudet** [comment]
Hi @dosumis 
If I understand your previous comment, "GO:0016337 single organismal cell-cell adhesion" was created to segregate lots of yeast cell-cell adhesion annotations with completely unrelated mechanisms, ie it should only apply to unicellular organisms, is this right ? 

Right now it's not how it's used: Direct Experimental annotations by species according to AmiGO

Metazoa | (215) | + | -
-- | -- | -- | --
Vertebrata | (182) | + | -
Mammalia | (158) | + | -
Plasmodium falciparum 3D7 | (127) | + | -
Mus musculus | (63) | + | -
Fungi | (52) | + | -
Homo sapiens | (50) | + | -
Rattus norvegicus | (29) | + | -
Candida albicans | (27) | + | -
Candida albicans SC5314 | (25) | + | -
Drosophila melanogaster | (23) | + | -
Danio rerio | (21) | + | -
Dictyostelium discoideum | (16)

So whatever this term is trying to distinguish, that's not doing its goal. I'll merge the term and if needed we should use the mechanism to distinguish different types of cell-cell adhesion. 

OK with you ? 

Thanks, Pascale

**Comment by dosumis** [comment]
> If I understand your previous comment, "GO:0016337 single organismal cell-cell adhesion" was created to segregate lots of yeast cell-cell adhesion annotations with completely unrelated mechanisms, ie it should only apply to unicellular organisms, is this right ?

The yeast stuff is *not* single organismal - each yeast cell is an organism.  All the yeast annotations should be under 'adhesion between unicellular organisms'

![image](https://user-images.githubusercontent.com/112839/29074177-4792da02-7c89-11e7-8505-acf9f074b461.png)

**Comment by pgaudet** [comment]
Done all except for 'single organism process'. For some reason ‘biological process’ is ‘disjoint unioin of ‘single organism process’ & multiorganism process’. I need to remove that; I just hope there are no unintended consequences. It's the first time I would remove disjoint statements. 

Pascale

**Comment by pgaudet** [comment]
@dosumis thanks for your reply. Then it's all good WRT the changes I made.

**Comment by pgaudet** [comment]
Also merged 'single-multicellular organism process' (no direct annotations) with 'multicellular organism process' since the previous changes made these two classes equivalent.
