### ISSUE TITLE
Uberon import redundantly brings in a chunk of NCBI taxonomy

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12218]
/extensions/uberon_import.owl includes a chunk of NCBI taxonomy - this is redundant with the taxonomy directly imported. Would be better if it just included dangling references to the terms used.

CC @hdietze

**Comment by cmungall** [comment]
General issue, for CL etc. Some notes here: https://github.com/ontodev/robot/issues/38

**Comment by pgaudet** [comment]
Is this fixed ? @balhoff perhaps you know?

**Comment by ValWood** [comment]
Is this still valid @balhoff?
I'm not trying to close tickets tright now, I just spotted it while looking for something else....

**Comment by balhoff** [comment]
This looks to be still the case. We can fix this by extracting the GO `uberon_import` from the new `uberon-base.owl` published by Uberon, but I would like to first discuss with @cmungall some issues about checking transitive ontology dependencies.

**Comment by balhoff** [comment]
This should be fixed by the next Uberon release.
