### ISSUE TITLE
presynaptic membrane parentage

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12219]
'presynaptic membrane ; GO:0042734' currently has no link to 'presynapse ; GO:0098793'.

Should be a quick part_of fix.

Thanks!

**Comment by dosumis** [comment]
Fixed in synapse branch

**Comment by dosumis** [comment]
In case you're interested you can view progress in:

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/experimental/David/synapse/

see workingo.obo (or .owl) for the latest full version
see go_synapse.obo for the terms only in the synapse slim.

Hope to have it merged back into GO by the end of this week.
