### ISSUE TITLE
Move editors file to this repo on GitHub

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12211]
- [ ] move biochebi to its own repo (in progress https://github.com/cmungall/bio-chebi)
- [x] create go-ontology repo with Makefile setup
- [x] ensure all editors trained in git/github
- [ ] migrate history
- [x] change jenkins jobs

The setup would be as follows:

```
src/ontology/
  Makefile
  gene_ontology_write.obo
  imports/
     *.obo
     *.owl
src/tools/
   [perl for checking, etc]
```

This would be editors only. CI jobs would release this into svn, which in turns syncs with ftp/http. Migrating these would be a separate phase.
### File size limits

Current size is 35M, which is within GH limits. It would be good to think of a modularization strategy sooner rather than later though. This is likely to involve a switch to Protege for editing.
### CI jobs and pipeline changes
- We would set up a travis job that would be verification-only (check: enough memory?)
- A jenkins job would prepare release files (go, go-plus, go-basic), and sync these to svn
- TG would point to GH
- Currently import files are generated and committed nightly. We could change the job to commit to GH. OR we could have this controlled by users.

In general this is a good time to overhaul our workflow
### History

We would use `git svn` to mirror the history in svn

option: We could in theory go back to cvs/1999...? This would be more work.
### Versioning

This opens up the possibility of using GitHub versioning
### Timing

@dosumis is working on a long branch in svn, need to coordinate.

This will likely need a lot of prep time, and do a few dry runs first

**Comment by dosumis** [comment]
> @ <https://github.com/dosumis>dosumis <https://github.com/dosumis> is
working on a long branch in svn, need to coordinate.

Will use Emacs merge to rather than svn merge, so no dependency on svn.
Plan to do merge first thing in New Year.

**Comment by cmungall** [comment]
See also this ticket about migrating the entirety of svn:

https://github.com/geneontology/go-site/issues/189

**Comment by cmungall** [comment]
For the editors file, too hard to migrate repo.

I will likely simply replace every commit. This will make it look like every commit comes from one user. For a trial run, see: https://github.com/cmungall/go-new-ontology

**Comment by mcourtot** [comment]
I didn't quite get that. Why is it hard to migrate the editors files under a repo? What do you mean "simply replace every commit'?

Current example is:
<img width="998" alt="screen shot 2016-10-26 at 10 53 56" src="https://cloud.githubusercontent.com/assets/2214135/19721537/922e7fb8-9b6a-11e6-828d-f4e6daad3847.png">

which shows @tberardini as having committed that file somewhere in 2012. Is that because you used a specific commit from the history for that trial, or...?

**Comment by cmungall** [comment]
> Why is it hard to migrate the editors files under a repo?
https://github.com/geneontology/go-site/issues/189#issuecomment-224460518

> What do you mean "simply replace every commit'?
poorly worded, I mean the ad-hoc migrate script (see commit message) does `svn update -r` for every commit and then commits the file to git (with the same commit message)

**Comment by cmungall** [comment]
UPDATE:

I have a branch (not pushed) on go-ontology (this repo)/

So far, I have fed in cvs commits from 2008-03-21 (inception of gene_ontology_write.obo) to 2011-11-22 (when we switched from svn). I did this using a custom script (see commit above).

Note this is *only* commits on gene_ontology_write.obo. Each commit typically represents a small diff of the obo file.

My local ~/.git directory is now at 5.2G. And that's only 3.5 years. I'm not sure if it's linear, but we may be talking about >10G local footprint for anyone working on the ontology.

On the one hand, it's really useful having an unbroken chain of commits in one repo. On the other, it does exact a burden.

I'm now considering having a series of archive repos, e.g. go-ontology-2008-2011, and starting the new one relatively fresh. Thoughts?

**Comment by kltm** [comment]
* While keeping a record for future archaeologists is nice, how many studies/replications have really made use of it, versus just re-using snapshots?
* In the grand scheme of things, 10G is not a lot, and people do not need to work on the full tree
* This could, maybe, eventually exhaust GitHub's good will; however, a non-GitHub git repo could probably take a lot more
* Has anybody looked in things like "git repack" and "git gc"?

**Comment by mcourtot** [comment]
It is nice to have one unbroken history, but to me not a high enough requirement to justify the extra load/burden. As long as we have history somewhere, that should be enough IMO.

**Comment by dosumis** [comment]
I'd like to hear opinions from @paolaroncaglia, @tberardini & @ukemi on the importance of being able to see archival commits.  

I've occasionally looked at commits from a year or two ago.  I suspect we will do more of this once we can close GitHub tickets with a commit => a link from the closed ticket to the diff.

Having said that - having a multi-gigabyte sized checkout is not ideal.  Archive repos might be a good way to go.

**Comment by tberardini** [comment]
@mcourtot said: It is nice to have one unbroken history, but to me not a high enough requirement to justify the extra load/burden. As long as we have history somewhere, that should be enough IMO.
------------
I agree with that.  If we have the history somewhere _**and a relatively simple way to access it**_, even if it is broken up, that's enough for me.

**Comment by cmungall** [comment]
Note this is now on master (but still not in prod): https://github.com/geneontology/go-ontology

new job:
https://build.berkeleybop.org/job/release-go-NEW/configure

**Comment by mcourtot** [comment]
I can't see the new jenkins job - is it a simplification of the existing pipeline, or just a transposition to use GH instead of SVN, or...? Specifically I was wondering if the checks had been rewritten or were still using the 'old' scripts.

**Comment by cmungall** [comment]
See the README at the top of this repo. It's a vast improvement. The makefile is still complex, but as simple as I can make it. But crucially there is no complex interdependence of jenkins jobs, and everything is managed from the same directory.

**Comment by ukemi** [comment]
@cmungall   Is this ticket still relevant or can it be closed?
