### ISSUE TITLE
new parent for positive and neg reg of telomere maintenance

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12216]
Hi

please could GO:0032205 positive and GO:0032206 negative reg of telomere maintenance be given the is_a parent GO:0032204 reg of telomere maintenance

thanks

Ruth

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by dosumis** [comment]
Relationship are in ontology and visible in QuickGO: https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0032204#term=children

Am I missing something?

**Comment by NancyCampbell** [comment]
Hi David,

When I look at telomere maintenance, it has regulation of telomere maintenance whose children are neg and pos regulation of telomere maintenance (as it shows in your link) but when I look at telomere maintenance GO:0000723 that is when it gets a bit confusing. Here reg, neg reg and pos reg seem all to be siblings of telomere maintenance. Is that right? It just looks a bit odd. I am attaching a screenshot of what I mean. Thanks David.

<img width="5043" alt="regulation of telomere maintenance children" src="https://cloud.githubusercontent.com/assets/12081136/12091772/097c3f6e-b2f1-11e5-9136-b1180c39ae3e.png">

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/12092597/044eed7a-b2f6-11e5-8c41-86d817d05928.png)

**Comment by dosumis** [comment]
All looks fine to me:
![image](https://cloud.githubusercontent.com/assets/112839/12094749/5e7fed92-b302-11e5-9f1d-3898f02844d7.png)

(positive/negative) regulation of telomere maintenance all have regulates relationships to 'telomere maintenance' (yellow is regulates, red is +ve R, green is -ve R).  In graphy terms, via the regulates relations they they are all children rather of 'telomere maintenance'  and siblings of each other. Via is_a (in black) there is a parent-child relationship between the 'regulates telomere maintenance' and the +ve / -ve versions.

Hth,
David

**Comment by dosumis** [comment]
Not sure how you set up QuickGO visualisation so that the relations are not shown.  AFAIK it should show relationships between all terms in the basket.  Something odd about that graph - not sure how you got it to display leaf nodes that were not in the basket.  @tonysawfordebi  - any ideas?

**Comment by tonysawfordebi** [comment]
OK, I know what's going on. It's because the display option "Show children" is enabled. This shows the first level of descendant terms for those terms whose ancestor/comparison chart you're displaying. Crucially, this display only shows the relations between these child terms and their immediate parent, and not to any other terms in the graph. You can see this by following this link and setting "Show children" to "Show" in the Display options: http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000723#term=ancchart&chartTab=settings
