### ISSUE TITLE
NTR: EC 1.1.1.305, 2.6.1.87, 2.1.2.13, and 2.4.2.53 activities

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12213]
Hi all,

Could you please add MF terms for the EC numbers 1.1.1.305, 2.6.1.87, 2.1.2.13, and 2.4.2.53?  They are all in this pathway: http://www.enzyme-database.org/reaction/polysacc/UDPAra4N.html
Thanks!

As a side note, I seem to no longer be able to find anything when I search with EC numbers.  Am I missing something?

In the meantime, Happy Holidays!
Cheers,
-Ingrid

**Comment by dosumis** [comment]
Done. with classifications from Kegg e.g. see http://www.genome.jp/dbget-bin/www_bget?ec:1.1.1.305

(Thinking there has to be some way to automate this stuff!!!)
