### ISSUE TITLE
NTR: children of protein targeting and def change

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#12210]
I think it also needs a looser def for the parent: GO:0006605 protein targeting?

"The process of targeting specific proteins to particular membrane-bounded subcellular organelles. Usually requires an organelle specific protein sequence motif"

Cell walls are not organelles. In my case a protein needs another to be targeted to the spore wall (dicty spore coat). Otherwise it's found in the so-called interspore matrix, an extracellular matrix between the spores in the Dicty spore head. PMID 10564654; cotE is mis-targeted in the pspB null mutant.

If Def is amended:

GO:0006605 protein targeting
->GO: NEW  protein targeting to cell wall
->->GO: NEW  protein targeting to spore wall

Thanks!
Petra

**Comment by ValWood** [comment]
There are a number of open tickets discussing the meaning of 'targeting' and how it differs from 'transport'

I think this one is the most relevant.
https://github.com/geneontology/go-ontology/issues/10246

I still din't really understand*exactly* what we are trying to capture by 'targeting' (or  how we absolutely distinguish between transport and targeting at the annotation level)

val

**Comment by dosumis** [comment]
Updated def: 
"The process of targeting specific proteins to particular regions of the cell, typcially membrane-bounded subcellular organelles. Usually requires an organelle specific protein sequence motif."

New terms: 

![image](https://cloud.githubusercontent.com/assets/112839/13146105/0d766c1a-d64c-11e5-9d77-abbb989a422a.png)

![image](https://cloud.githubusercontent.com/assets/112839/13146120/1f9b1c10-d64c-11e5-9d33-0025aba85bae.png)
