### ISSUE TITLE
Macroautophagy: check consistency between GO and Reactome

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12214]
Version 55 of Reactome Knowledgebase (released 23/12/2015) contains an update to macroautophagy

http://www.reactome.org/PathwayBrowser/#R-HSA-1632852

This may be useful for the autophagy project. We should take a look and ensure consistency, see if we missed anything, etc.

Thanks,
Paola

**Comment by Pauldenny** [comment]
Downloaded all UniprotKB IDs (human) from this REactome pathway. Compared list with those proteins already in GO annotated with autophagy (or children / regulation / etc). Found 8 discrepancies. These 8 were mainly members of the ESCRT complex families.  Annotated these using some experimental evidence, some review papers.

**Comment by ukemi** [comment]
Looked at the pathway representation using the pathway browser with respect to what we have for the pathway and the functions that take part in it. Things look consistent.

**Comment by paolaroncaglia** [comment]
For future reference: Peter says "if you want to pursue GO – Reactome alignment further in this area, get in touch with Marc Gillespie".
