### ISSUE TITLE
Cardiac conduction: check consistency between GO and Reactome

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12215]
Version 55 of Reactome Knowledgebase (released 23/12/2015) contains an expansion of 'muscle contraction' to include 'cardiac conduction'

http://www.reactome.org/PathwayBrowser/#R-HSA-5576891

For the GO cardiac conduction project, we should probably take a closer look and see if representation is consistent, if we forgot anything in terms of processes or annotations, etc.

**Comment by paolaroncaglia** [comment]
Note for self: wrt annotations, see Paul's successful approach here https://github.com/geneontology/go-ontology/issues/12214

**Comment by paolaroncaglia** [comment]
Hi @ukemi (and FYI @RLovering),
I’m going to assign this to you David as part of the cardiac conduction work, with many thanks.

**Comment by ukemi** [comment]
The representations are different becasue GO takes a more anatomical view of the process across heart tissues while Reactome is a reaction-based view of the action potentials within the cardiac myocytes. I have compared the genes annotated in both resources and sent a report to @RLovering

**Comment by deustp01** [comment]
@ukemi , could I get a copy of the list as well? We could try to agree on the scope of the process even if we have different representations - I'd be particularly interested in genes / proteins in Ruth's annotations that are missing from Reactome's.
Thanks

**Comment by ukemi** [comment]
On its way.
