### ISSUE TITLE
Include upper level classes plus bridging axioms in go-plus import chain

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12221]
Note: this is prompted by the desire to retire go-upper.obo https://github.com/geneontology/go-site/issues/129

Including upper level classes (primarily BFO but also CARO) in the import chain is itself straightforward. Note that we may want to limit confusing annotation assertions.

However, this is not much use unless bindings are present.

An early attempt for GO:
http://purl.obolibrary.org/obo/go/extensions/go-bfo-bridge.owl

this is probably overkill and can be replaced by 3 binding/bridge axioms (MF,BP->P, CC->CARO:?)

However, we will also need to ensure that bindings are present for all imported ontologies, to prevent them hanging out at root. There are a number of issues here:
- we might need to make ontological commitments on others behalf, e.g. SO
- import dependencies are hard to manage, see issue 38 in the [robot tracker](https://github.com/ontodev/robot/issues). but this is something we need to tackle anyway

This may wait til after: 
#12211

**Comment by paolaroncaglia** [comment]
Assigning to Chris so this doesn't get lost.

**Comment by cmungall** [comment]
We decided to experiment with adding bfo to the import chain

**Comment by dosumis** [comment]
@dosumis

**Comment by dosumis** [comment]
Any progress on this?  I think we agreed to add to the import chain and slowly populate.

Needed:


* BFO:material entity
for CC? - Are we sure we have no spaces? If any ambiguity, just use independent continuant)
BFO:Process (parent for BP and MF)
BFO:Quality (For imports from PATO)
BFO:Role

**Comment by pgaudet** [comment]
@balhoff Do you know if this is still relevant?

**Comment by balhoff** [comment]
I don't think so.
