### ISSUE TITLE
presynaptic assembly terms

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12220]
Suggested new terms for annotating Wnt signaling components:

Running past @dosumis to tie-in with synapse work.

1. presynapse assembly ; GO:NEW
synonym: presynaptic terminal assembly [PMID:24449494]
The aggregation, arrangement and bonding together of a set of components to form a pre synapse.

2. postsynapse assembly ; GO:NEW
The aggregation, arrangement and bonding together of a set of components to form a post synapse.
synonym: postsynaptic assembly [PMID:24449494]

Would need to rehouse the following existing terms under the new terms:
postsynaptic density assembly ; GO:0097107
postsynaptic membrane assembly ; GO:0097104
presynaptic membrane assembly ; GO:0097105

3. protein localization to presynapse ; GO:NEW
related synonym: recruitment of presynaptic proteins [PMID:24449494]

3. positive regulation of protein localisation to presynapse ; GO:NEW

4. Synonym addition to one of your branch terms:
id: GO:0099558
name: maintenance of synapse structure
related synonym: synaptic maintenance [PMID:24449494]

5. I need a new term to annotate Dkk1, a Wnt-inhibitor that negatively affects synaptic maintenance and promotes synaptic loss (synaptic disassembly). Mostly this is assayed in disease conditions, but it's 'normal' role is to antagonise Wnt signaling and synaptic maintenance. A term for 'synapse disassembly' may be sufficient.

Thanks!
GOC:bf, GOC:PARL

**Comment by dosumis** [comment]
Looks straightforward.

**Comment by rebeccafoulger** [comment]
Hi @dosumis - is there any update on the presynaptic assembly and postsynaptic assembly terms?

**Comment by rebeccafoulger** [comment]
Hi @dosumis - is there still a plan to add in these assembly terms specific to the pre- and post-synapse? I've got several annotations to transfer to the more specific terms...

**Comment by dosumis** [comment]
Done (& committed).  Apologies for the wait.  (We really should working on automating the partonomy for cases like this.  Risky to try to keep this in sync with changes/additions to synapse CC partonomy).
