### ISSUE TITLE
Multiple unsatisfiable classes resulting from uberon import chain

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12223]
go-plus became incoherent, many explanations like this:

![screen shot 2016-01-04 at 12 47 32 pm](https://cloud.githubusercontent.com/assets/50745/12100048/5a4d7c2e-b2e1-11e5-8674-99b0ab6efdd9.png)

**Comment by cmungall** [comment]
Diagnosis: uberon assumes 'reproductive structure' is metazoan (inferred from the assumption that the root class is metazoan); GO uses this also for plants

Long term fix: EITHER uberon does not bake in metazoan assumptions (effectively taking over some of the role of CARO) or we put functional groupings like this in CARO (as @dosumis did originally in FUNCARO)

Short term fix: remove uberon taxon constraints from import module

Note: the short term fix was already queued in the Makefile. However, it the rebuild of uberon_import.owl never happened due to the unsatisfiability. Race conditions in ontologies, fun. Some of this will be fixed by a clearer separation of edit vs public artefacts with #12211

**Comment by dosumis** [comment]
The explanation above shows inconsistency because of the mesoderm thing.  I tried to fix that with an edit to uberon (it's not even true for metazoans), but looks like that didn't make it into a release yet.

If there is also inconsistency through 'reproductive structure' in Uberon, then maybe we should just remove the GO link to Uberon reproductive structure for now.  Presumably could be functionally defined using GO. As you say, this could live in CARO rather than Uberon to keep it metazoan only.

**Comment by cmungall** [comment]
On 4 Jan 2016, at 13:37, David Osumi-Sutherland wrote:

> The explanation above shows inconsistency because of the mesoderm 
> thing.

Ah yes, you're right

> I tried to fix that with an edit to uberon (it's not even true for 
> metazoans), but looks like that didn't make it into a release yet.

will be in next one

> If there is also inconsistency through 'reproductive structure' in 
> Uberon, then maybe we should just remove the GO link to Uberon 
> reproductive structure for now.  Presumably could be functionally 
> defined using GO. As you say, this could live in CARO rather than 
> Uberon to keep it metazoan only.

there is less of a commitment issue than I thought. There is no problem 
with reproductive structure with your fix.

However, I will progress with the short term fix for now until the new 
uberon release is propagated, hopefully later today

**Comment by cmungall** [comment]
short term fix committed with r30654

This eliminates the majority of unsats. Will file with remaining ones

**Comment by cmungall** [comment]
back on: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/Makefile?r1=32321&r2=32925

**Comment by dosumis** [comment]
To fix:
![image](https://cloud.githubusercontent.com/assets/112839/14914895/37c699b2-0e06-11e6-9f58-baef1c761c93.png)

Possible fixes:

1.  'cardiocyte differentiation' 'part of' some 'heart development'
->
'cardiocyte differentiation' 'part of' some 'primary circulatory organ development' (GO, TBA?)

2. Relax constraints on heart in Uberon.

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/14915140/468843d6-0e08-11e6-99fc-fd39b1ac97a5.png)

Fix: Need separate terms in Uberon for 'vertebrate trachea' and arthropod trachea - both under 'respiratory tube'

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/14915187/e7f8bbf6-0e08-11e6-8113-021552ae0d0e.png)


post-anal tail: "A tail that extends from the posterior tip of the organism to the anus, contains muscle and skeleton."

The skeleton clause excludes nematodes.  Should 'post-anal tail' be broadened, or do we need a new term?

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/14915251/5a07d15a-0e09-11e6-90db-d19b691ab12f.png)

ecotdermal placodes are common in developing arthropods.  Remove this taxon restriction from Uberon.

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/14915281/982e2e16-0e09-11e6-9ff5-c02861b0ed6a.png)


Uberon needs a term for arthropod spiracle. - perhaps 'spiracle of open tracheal system' ?

**Comment by dosumis** [comment]
[Unsatisfiable class module](https://github.com/geneontology/go-ontology/blob/master/go_unstasfiable_module_files/go-unsatisfiable-module_r32945.owl)

@cmungall  - Safe to turn import of constraints off until these are fixed.

**Comment by cmungall** [comment]
Makefile reverted with r32951

I can regenerate uberon_imports too

I recognize many of the issues above, will provide feedback shortly

**Comment by cmungall** [comment]
r32952 committed new imports module, minus TCs. GO should now be satisfiable

**Comment by tberardini** [comment]
Is GO satisfiable after changes made in r32952?  If yes, then we can close the related issues, correct?

**Comment by dosumis** [comment]
epithelial cell fate determination, open tracheal system

![image](https://cloud.githubusercontent.com/assets/112839/18199017/8184f866-70f6-11e6-9cfc-83981fe4a95a.png)

**Comment by dosumis** [comment]
Spiracles:  Fish vs Arthropods.  Needs Uberon fix.

![image](https://cloud.githubusercontent.com/assets/112839/18199501/642b53e4-70f8-11e6-8991-dc208e6ef181.png)

**Comment by dosumis** [comment]
Arthropods have ectodermal placodes too!

![image](https://cloud.githubusercontent.com/assets/112839/18204952/62854f6c-7117-11e6-93d2-13666ec1d17e.png)

**Comment by dosumis** [comment]
@cmungall: should now be all fixed. Please try turning taxon constraint import back on. Ta.

**Comment by tberardini** [comment]
@cmungall - reminder.  Thanks

**Comment by cmungall** [comment]
r35423

Let's see what happens tonight...

**Comment by dosumis** [comment]
Looks like there’s one remaining Uberon issue to fix. We missed this because this class was inconsistent for two separate reasons and we’ve only fixed one.   

![image](https://cloud.githubusercontent.com/assets/112839/18389924/0f3c8a3a-76a0-11e6-8d73-e31b636b1d26.png)

- [ ] Quick fix.  Delete this, it's wrong:  'optic lobe placode formation' part_of some 'optic placode formation'.  This fixes the inconsistency. 

Explanation: The optic placode referred to is the eye primordium in chordates. The optic lobe placode is the precurosor of the optic lobes - part of the brain in arthropods.  In holometabolous insects at least, the eye develops from an imaginal disc formed by invagination of the embryonic epithelium not an ectdermal placode.

**Comment by cmungall** [comment]
good catch, I agree with the fix.

At some point we should go through and improve the labels and the definitions in GO. Everyone interested should contribute to the review of the placode hierarchy here: https://github.com/obophenotype/uberon/issues/135

**Comment by dosumis** [comment]
FIxed.
