### ISSUE TITLE
Response to compounds used as assays

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12228]
This is something we discussed in several occasions. Opening a ticket to keep track of things.
As discussed at a recent ontology call (notes are mine):

"Stemming from TG requests for
cellular response to doxorubicin [PMID:19801496]
response to tetrachloromethane [PMID:7852267]
cellular response to tetrachloromethane [PMID:7852267]
I emailed the submitter (and the group) but there was no reply: "Doxorubicin and tetrachloromethane are artificial compounds, not found physiologically in cells. In the papers above (and in many others) they are used to elicit a specific effect - doxorubicin intercalates DNA; tetrachloromethane is powerfully toxic to the liver. My view is that these substances are used as assays, and as such, curators should not annotate to corresponding 'response to' terms. We discussed the 'assay' issue in general at a couple of recent GOC meetings (Texas and Barcelona, you may search the minutes with 'assay' e.g. here https://docs.google.com/document/d/1NonH97s8xEpDdx6DfonKPKI_RdHbbG-yft85UZtUmF0/edit#), and I think that your requested terms fall under the same category. Therefore, I'd like to obsolete them.
Note that we do have 'response to doxorubicin' and 'response to 4'-epidoxorubicin' in GO. However, these were requested by the Experimental Factor Ontology for mapping purposes. They use those terms to annotate experiments, not gene products, and as such, we believe that their presence in the GO is legitimate.
I realize that this may be confusing. Do you [Stan and editors] think curators would benefit from a reminder on annotation guidance in this case? If yes, we could spend 5' on this at an annotation call. Should we place 'response to doxorubicin', 'response to 4'-epidoxorubicin' and any similar one in the 'do not annotate' subset?

AI: In the short term, Paola to obsolete the TG FF terms above (and email Stan to point him to this discussion). DONE.

[THIS IS THE OBJECT OF THIS TICKET:]
AI: In the medium term, Paola to place 'response to doxorubicin', 'response to 4'-epidoxorubicin' and any similar one in the 'do not annotate' subset. 
(For example, search for terms requested by Dani Welter and Helen Parkinson.) 
Other editors to do the same when they come across terms of any kind (response to, binding…) that have a logical axiom to a non-physiological chemical compound. 
All to add definition comments meant as annotation guidance (e.g. for 'response to doxorubicin' something along the lines of 
“This term is not meant to be used to annotate gene products. It was created to be used for cross-referencing by other ontologies” 
in addition to the usual warning for ‘do not annotate’ terms.).

AI: In the long term, when we start using or referencing an assay ontology, we may evaluate alternative strategies with ontologies such as EFO. 
For example, they could annotate to the relevant chemical or drug by using a relation ‘exposure_to’ or similar."

(For reference, minutes are here: http://wiki.geneontology.org/index.php/Ontology_meeting_2015-11-05#Response_to_compounds_used_as_assays)

**Comment by paolaroncaglia** [comment]
A related issue was discussed even more recently, stemming from TG freeform requests:

"We thought we agreed - and made it clear to curators - that terms describing completely non-physiological stimuli, such as exposure to microwave radiation, are not in scope for GO. But similar requests continue to arrive. 
We need to make sure we all agree on guidelines."

Kimberly and David H agreed that this should be discussed at an annotation call.
Mentioning them here as a polite reminder :-)
@vanaukenk @ukemi 

(For reference, minutes are here: http://wiki.geneontology.org/index.php/Ontology_meeting_2015-12-17#Brief_refresh_on_annotation_policies)

**Comment by vanaukenk** [comment]
Hi Paola,
Just to confirm that we've added the issue regarding 'response to compounds used as assays' to the agenda for the 2016-01-12 annotation call.
I can see why, without comments, it may not be clear to curators how these terms were intended to be used.  
--Kimberly

**Comment by paolaroncaglia** [comment]
Note for self: proposal above was approved at the last annotation call 
(for reference, minutes at http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-01-12#Non-physiological_Response_Terms).

**Comment by paolaroncaglia** [comment]
Note for self: see also https://github.com/geneontology/go-ontology/issues/12067#issuecomment-188691726

**Comment by tberardini** [comment]
see also #11416

**Comment by dosumis** [comment]
#12037

**Comment by paolaroncaglia** [comment]
Note for self: for reference: re-discussed at ontology call yesterday, http://wiki.geneontology.org/index.php/Ontology_meeting_2016-04-07#More_.27response_to_non-physiological_chemical_stimulus.27_terms_coming_in_via_TG

**Comment by paolaroncaglia** [comment]
To start with, I just edited 2 TG terms requested by EFO as resolved in this ticket:

GO:1905119 response to haloperidol
Added GO:1905120 cellular response to haloperidol

I.e. placed in the do_not_manually_annotate subset,
and added def comment "Note that this term is in the subset of terms that should not be used for direct manual annotation of gene products. It was created to be used for cross-referencing by other ontologies. Direct annotations to this term may be amended during annotation QC."

**Comment by paolaroncaglia** [comment]
As resolved previously, I edited older terms requested by EFO (placed in do_not_manually_annotate subset and added def. comment).

For full reference: I searched by GOC:dw and GOC:hp. I edited the following terms:
GO:1902522	response to 4'-epidoxorubicin
GO:1902518	response to cyclophosphamide
GO:1902519	response to docetaxel trihydrate
GO:1902520	response to doxorubicin
GO:1902521	response to etoposide
GO:0036275	response to 5-fluorouracil
GO:0036277	response to anticonvulsant
GO:0036276	response to antidepressant
GO:0097366	response to bronchodilator
GO:0036270	response to diuretic
GO:0036272	response to gemcitabine
GO:0036287	response to iloperidone
GO:0036274	response to lapatinib
GO:0036271	response to methylphenidate
GO:0036273	response to statin
GO:1990054	response to temozolomide

**Comment by paolaroncaglia** [comment]
For the sake of time, I'm not going to check if manual annotations exist for the terms I modified (a few were requested by Stan and EFO simply added a synonym).
If any are flagged in the near future, they will be items for discussion when we meet with Stan.

**Comment by paolaroncaglia** [comment]
As pointed out in https://github.com/geneontology/go-ontology/issues/12067#issuecomment-188691726, I also edited 

GO:0071411	cellular response to fluoxetine
GO:0014076	response to fluoxetine

(fluoxetine is Prozac).

**Comment by paolaroncaglia** [comment]
All my tasks for this ticket are done.
What is left is a collective action item for the editorial group
“AI: In the long term, when we start using or referencing an assay ontology, we may evaluate alternative strategies with ontologies such as EFO. 
For example, they could annotate to the relevant chemical or drug by using a relation ‘exposure_to’ or similar."
Also, when we meet with Stan/RGD, we may look for viable alternatives to RGD needs, as resolved in 
http://wiki.geneontology.org/index.php/Ontology_meeting_2016-04-07#More_.27response_to_non-physiological_chemical_stimulus.27_terms_coming_in_via_TG.

Closing this ticket now.
