### ISSUE TITLE
NTR: tRNA 5-carboxymethoxyuridine methyltransferase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12225]
As a child term for GO:0016300.  Proposed definition: Catalysis of the transfer of a methyl group from S-adenosylmethionine to a 5-carboxymethoxy-modified uridine residue in a tRNA molecule.  This is a new activity discovered in PMID 26681692.

Thanks,
Ingrid

**Comment by paolaroncaglia** [comment]
Hi Ingrid,
Added GO:0097697 tRNA 5-carboxymethoxyuridine methyltransferase activity
Full ontology stanza below. Thanks,
Paola

id: GO:0097697
name: tRNA 5-carboxymethoxyuridine methyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of a methyl group from S-adenosylmethionine to a 5-carboxymethoxy-modified uridine residue in a tRNA molecule." [GOC:imk, PMID:26681692]
is_a: GO:0016300 ! tRNA (uracil) methyltransferase activity
