### ISSUE TITLE
problems with envenomation and blood coagulation in other organism

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12224]
See screenshot

![screen shot 2016-01-04 at 2 14 02 pm](https://cloud.githubusercontent.com/assets/50745/12102209/2695322a-b2ee-11e5-8936-0699e2f27617.png)

See #12212 for proposed fix

**Comment by dosumis** [comment]
Fixed (in revision 30527):

      name: regulation of body fluid levels
      def: "Any process that modulates the levels of body fluids." [GOC:ai, GOC:dph, GOC:tb]
      subset: goslim_pir
     -is_a: GO:0044707 ! single-multicellular organism process
     +is_a: GO:0065008 ! regulation of biological quality
