### ISSUE TITLE
regulates:transitive + regulates o part_of -> regulates => problems

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12226]
This one's making my head spin a bit...

POTENTIAL REDUNDANT AXIOMS: GO:0098910 'regulation of atrial cardiac muscle cell action potential' part_of 'part of' GO:0086004 'regulation of cardiac muscle cell contraction' is also a simple SubClassOf.

POTENTIAL REDUNDANT AXIOMS: GO:0098911 'regulation of ventricular cardiac muscle cell action potential' part_of 'part of' GO:0086004 'regulation of cardiac muscle cell contraction' is also a simple SubClassOf.

![image](https://cloud.githubusercontent.com/assets/112839/12120603/5946925a-b3c9-11e5-8cd0-b2ff99b775c5.png)

**Comment by dosumis** [comment]
Perhaps not a general issue after all.  Corrected this - given inconsistency with name and textual def:

![image](https://cloud.githubusercontent.com/assets/112839/12121143/b246d26e-b3cb-11e5-8c86-5dfed63e9578.png)

> 

![image](https://cloud.githubusercontent.com/assets/112839/12121264/4a4432fa-b3cc-11e5-8301-824cb89cfaf5.png)

**Comment by paolaroncaglia** [comment]
Hi David,
Assigning to you - but let's bring it up for discussion at tomorrow's editors call. Could you please add it to the agenda? Cheers!
Paola

**Comment by dosumis** [comment]
Solution (to this specific issue): change part_of to regulates in these cases.  Need to look at how this fits with related terms.  

There is also a general issue that the regulates over part of property chain is problematic, e.g. individual steps in an ST pathway function by regulating each other without regulating pathway output for a given input. Needs to be a separate ticket with examples.

**Comment by dosumis** [comment]
While this is fixed, there are still a number of issues to address.  At least some of these should be made into new tickets. Adding some notes for now.

Specific issues:

1. In terms of the biology, it may make more sense to have the AP (positively) regulating the contraction.  If so, this should be applied as a general pattern.  Although perhaps - causally upstream would be better still.

General Issues not resolved:  

1. Why did these problems only show up when transitivity was added to regulates?  
2. Are there legitimate double labelled edge combinations being flagged here?
 * Can P1 regulate some P2 when P1 part_of some P2 ?
 * Can P1 regulate some P2 when P1 SubClassOf some P2 ?
3. Do we have a general problem here, where legitimate combination of axioms lead to an illegitimate double labelled edge?
4. The regulates over part of property chain is problematic, e.g. individual steps in an ST pathway function by regulating each other without regulating pathway output for a given input. Needs to be a separate ticket with examples.

**Comment by dosumis** [comment]
Closing as nothing further obviously actionable.  Have tagged as example of questionable regulation inference.
