### ISSUE TITLE
NTR: telomere maintenance via base-excision repair

### ISSUE THREAD

**Issue by JessBuxton** [geneontology/go-ontology#12227]
Hi,

Could I please have the new term:
1. GO:NEW telomere maintenance via base-excision repair
Def: Base-excision repair of telomeric DNA. Telomeric sequences are particularly susceptible to oxidative DNA damage, due to their G-rich nature.

Also an amendment to the definition of the following term: 

GO:0043247 telomere maintenance in response to DNA damage
Biological Process
Current Def: Any process that occur in response to the presence of critically short telomeres.
New Def: Any process that occurs in response to the presence of critically short or damaged telomeres

Finally could GO:NEW telomere maintenance via base-excision repair be made a child term of these two terms:

GO:0043247 telomere maintenance in response to DNA damage
GO:0006284 base-excision repair 

Please add GOC:BHF and GOC:BHF_telomere
For annotation of PMID:24703901

**Comment by JessBuxton** [comment]
@RLovering 
@rachhuntley

**Comment by paolaroncaglia** [comment]
Hi Jess, 
All done. New term is GO:0097698 telomere maintenance via base-excision repair. Full ontology stanza below for your reference.

@RLovering I added all three dbxrefs: GOC:jeu, GOC:BHF_telomere, GOC:BHF. Wondering if in these cases GOC:BHF is redundant?

Cheers,
Paola

id: GO:0097698
name: telomere maintenance via base-excision repair
namespace: biological_process
def: "A telomere maintenance process that occurs by base-excision repair of telomeric DNA in response to DNA damage. Telomeric sequences are particularly susceptible to oxidative DNA damage, due to their G-rich nature." [GOC:BHF, GOC:BHF_telomere, GOC:jbu, PMID:24703901]
is_a: GO:0006284 ! base-excision repair
is_a: GO:0043247 ! telomere maintenance in response to DNA damage

**Comment by RLovering** [comment]
Hi Paola

sorry about all these dbxrefs. Please do keep all three,  when I collect stats on GO term numbers I don't think that GOC:BHF_telomere will be returned in a query for GOC:BHF, however it is difficult to know for sure because hopefully all GOC:BHF_telomere records have GOC:BHF too. 

Thanks

Ruth

**Comment by paolaroncaglia** [comment]
Thanks Ruth. No worries, I will continue to add all and any dbxref as requested :-)

**Comment by ValWood** [comment]
The process of telomere maintenance refers specifically to lengthening and or shortening. This  term sound like repair?

Historically I think 
"telomere maintenance in response to DNA damage"
originates from the fact that pombe telomeres recombine and circularize in response to damage or if it is a chance event which allows 'survivors'  at a very low frequency but is not truly a biological process....
(so I don't know now  if this would be correctly maintenance).

The maintenance via repair sounds odd though ?   Also doesn't excision repair only occur in  ds DNA?

**Comment by RLovering** [comment]
Hi Val

Im afraid human biology must be a bit different than yeast. If you read the definition proposed and look at the reference I think it might make more sense. Human DNA suffers a lot of DNA damage over the years, it is all the thinking we do and getting sunburnt when we are not thinking!

The terms have been requested in consultation with Jess who as been working on telomere biology for many years and also based on a number of papers we have been reading.

best

Ruth

**Comment by ValWood** [comment]
I'm still confused and I think the definitions probably need some work.  The original telomere maintenance term refers to 2 processes
i) The lengthening and shortening of telomeric DNA sequence (This was referring to the single stranded repetitive tracts)
ii) telomere capping
both of which are related to length maintenance


Perhaps the def of this term should be extended to include 'repair processes'  ?

I also have some old outstanding tickets where it seems we  are not always precise about whether we are referring to the "telomeric DNA repetitive tracts" or the  larger subtelomeric regions. Maybe Jess can also help with these...

**Comment by RLovering** [comment]
Hi Val

I think you are right that the telomere maintenance needs extending to cover the breadth of the process.
GO:0000723 telomere maintenance
Current definition:
Any process that contributes to the maintenance of proper telomeric length and structure by affecting and monitoring the activity of telomeric proteins and the length of telomeric DNA. These processes includes those that shorten and lengthen the telomeric DNA sequences.

New definition:
Any process that contributes to the maintenance of proper telomeric length and structure by affecting and monitoring the activity of telomeric proteins, the length of telomeric DNA and the replication and repair of the DNA. These processes includes those that shorten, lengthen, replicate and repair the telomeric DNA sequences.

How does that sound?

Ruth

**Comment by ValWood** [comment]
Anyway, whatever you think but it might be worth  somebody looking through the existing terms and checking that they are properly defined.

Val

**Comment by ValWood** [comment]
I meant to add I think the boroadening would be OK, but I also think it would be useful to have a term to represent
"telomere length maintenance" to group the telomerase dependent lengthening, and the capping, which seem to be slightly different processes than the repair related stuff from the reviews I scanned.
(Some DNA damage checkpoint genes seem to be involved in sensing problems at the telomeres, but these are not involved directly in the repair per se.) I'm just worried that  we might lose some of the specificity for telomere  length maintenance from the current annotations (at least for pombe)

**Comment by paolaroncaglia** [comment]
Hi Val and Ruth,
I re-opened this so it won't be forgotten, I'll look into it but it may not be immediately... thanks for your patience.
Paola

**Comment by paolaroncaglia** [comment]
Closing now, see Ruth's and Val's latest comments in https://github.com/geneontology/go-ontology/issues/12230.
