### ISSUE TITLE
TermGenie requests with wrong GOC:ref

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12239]
Hi,

I've just requested three sets of new terms via TermGenie but mistakenly added the GO:BHF_miRNA reference instead of the GOC:BHF_telomere reference.

Could you please ensure these terms get the correct telomere reference?
GO:1904907
GO:1904908
GO:1904909
GO:1904910
GO:1904911
GO:1904912
GO:1904913
GO:1904914
GO:1904915

Note: the GOC:BHF reference should also be there.

Thanks!
Rachael.

**Comment by dosumis** [comment]
DONE
