### ISSUE TITLE
New Term Request: endothelial cell-matrix adhesion

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12233]
Dear Biocurators,

I am writing to request a new GO term, which arose while I was annotating paper PMID: 19460962 (Bonauer et al., 2009).

In this paper, in Figure 1D, endothelial cell binding to fibronectin is decreased, as a result of overexpression of miR-92a.

I order to capture this information I would like to request the term: 
'endothelial cell-matrix adhesion via fibronectin'.

This term would be an is_a child to 
GO:0007160 cell-matrix adhesion

Possibly the following additional new term should also be added:
'endothelial cell-matrix adhesion' as a parent to the term requested, and an is_a child to the term above.

So the final ontology would be:
GO:0007160 cell-matrix adhesion
> is_a NTR endothelial cell-matrix adhesion
>> is_a NTR endothelial cell-matrix adhesion via fibronectin

DbxREFs: GOC:BHF, GOC:bc

I will look forward to hearing from you with regard to my request.

Thank you,
Barbara

cc: @RLovering 
cc: @rachhuntley

**Comment by BarbaraCzub** [comment]
By the way I will be using regulation terms, which I am going to request via Term Genie.

**Comment by tberardini** [comment]
Looking at the existing terms in the branch, I think it makes more sense to create the following terms:

fibronectin binding involved in cell-matrix adhesion, GO:new1
endothelial cell-matrix adhesion, GO:new2
fibronectin binding involved in endothelial cell-matrix adhesion, GO:new3

With structure like this:

fibronectin binding, GO:exists
--[i] fibronectin binding involved in cell-matrix adhesion, GO:new1

cell-matrix adhesion, GO:exists
--[p] fibronectin binding involved in cell-matrix adhesion, GO:new1

protein binding involved in cell-matrix adhesion, GO:exists
--[i] fibronectin binding involved in cell-matrix adhesion, GO:new1
----[i] fibronectin binding involved in endothelial cell-matrix adhesion, GO:new3

cell-matrix adhesion, GO:exists
--[i] endothelial cell-matrix adhesion, GO:new2
----[p] fibronectin binding involved in endothelial cell-matrix adhesion, GO:new3

I'd suggest using regulation terms created with GO:new3 as the base BP for your annotation.  Feedback welcome.

**Comment by BarbaraCzub** [comment]
Dear Tanya,

Thank you for your reply with suggestions for alternative terms.

However, your suggestion would create the is_a parent  'fibronectin binding’ which would cause problems for me when I use the negative regulation term I will be requesting later via TermGenie. Basically I would not feel confident to use the implied GO term ‘ negative regulation of fibronectin binding' due to the nature of the experiment being annotated. 

The paper is focuses on describing the effects of over-expressing or down-regulating miR-92a. In the experiment being annotated, the authors show that an increase in miR-92a levels results in adhesion of fewer cells to fibronectin in comparison to controls. 

This decrease in adhesion could happen due to a decreased affinity of the cells to fibronectin, e.g. if fibronectin-binding receptors become post-translationally modified (in which case the term 'fibronectin binding' would have been suitable), but it could also happen for instance due to down-regulation of cell surface receptors, which mediate the binding to fibronection, and thus less adhesion is observed when fewer receptors are present (in which case the 'fibronectin binding' term would not be appropriate). From the experiment presented in Figure 1D we cannot conclude what molecular mechanism underlies the decrease in cell-fibronectin adhesion, therefore I do not think that that term 'fibronectin binding' should be used here.

A term with a similar structure to the example term included below would be more suitable in this instance:
GO:0007156 homophilic cell adhesion via plasma membrane adhesion molecules
This would be: 'endothelial cell-matrix adhesion via fibronectin'
Then, when I subsequently request the regulation term, it will be the regulation term of 'adhesion’ only without regulating 'fibronectin binding'.

As an alternative I could use just the more general term: 'endothelial cell-matrix adhesion' with one of the following extensions: 1) has_agent [fibronectin], or 2) has_part [fibronectin binding].

Please let me know what you think.

Thank you,
Barbara

@RLovering 
@rachhuntley

**Comment by tberardini** [comment]
Thanks for your explanation.  That helps. 

Do you know if endothelial cells adhere to the ECM through anything else except fibronectin?  If not, then we can qualify the proposed 'more general' term to include that bit of information and we only need to add one more term.

**Comment by BarbaraCzub** [comment]
Hi Tanya,

In addition to fibronectin other ECM components that endothelial cells have been shown to bind to include (but are probably not limited to) collagen, laminin and vitronectin.

So I think the options would be either:
'endothelial cell-matrix adhesion' + 'endothelial cell-matrix adhesion via fibronectin' 
or: 'endothelial cell-matrix adhesion' with a relevant extention.

I will look forward to hearing from you.

Thanks,
Barbara

@RLovering 
@rachhuntley

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090673
+name: endothelial cell-matrix adhesion
+namespace: biological_process
+def: "The binding of an endothelial cell to the extracellular matrix via adhesion molecules." [GOC:bc, GOC:BHF, PMID:19460962]
+is_a: GO:0007160 ! cell-matrix adhesion
+intersection_of: GO:0007160 ! cell-matrix adhesion
+intersection_of: has_participant CL:0000115 ! endothelial cell
+created_by: tanyaberardini
+creation_date: 2016-01-15T15:38:11Z
+
+[Term]
+id: GO:0090674
+name: endothelial cell-matrix adhesion via fibronectin
+namespace: biological_process
+def: "The binding of an endothelial cell to the extracellular matrix via fibronectin." [GOC:bc, GOC:BHF, PMID:19460962]
+is_a: GO:0090673 ! endothelial cell-matrix adhesion
+created_by: tanyaberardini
+creation_date: 2016-01-15T15:40:58Z

**Comment by BarbaraCzub** [comment]
Thank you!
