### ISSUE TITLE
'cilium morphogenesis' and 'cilium assembly'

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12236]
From an editors' call discussion:

"Merge 'cilium morphogenesis' and 'cilium assembly'? check usage first. Currently 'cilium assembly' is part_of 'cilium morphogenesis'.  Lots of IMP annotations to CM, maybe because shape of cilia is odd.  Note that you can assemble something internally that doesn't affect the outside structure, the whole structure may keep the same shape. Be careful about mass merging unless we don't care about the distinction between the two.
AI: check whether a mass merge with a joined term morphogenesis and assembly makes sense."

Full minutes at http://wiki.geneontology.org/index.php/Ontology_meeting_2015-05-07#Follow-up:_cellular_component_is_a_anatomical_structure.3F

**Comment by paolaroncaglia** [comment]
@krchristie

Background: 

Some time ago, we decided to consider cellular components as anatomical structures. As a consequence, morphogenesis of cellular components became an instance of anatomical structure morphogenesis, and we questioned this. We resolved that “We should no longer use morphogenesis/results_in_morphogenesis to refer to assembly or generation of shape of a cellular component. But OK to make that assembly part of some anatomical structure morphogenesis - including morphogenesis of cells. Make sure that definitions and comments indicate this.” 
(For reference, details here:
http://wiki.geneontology.org/index.php/Ontology_meeting_2015-04-30#cellular_component_is_a_anatomical_structure.3F)

One of these cases is the current co-existence of 'cilium morphogenesis' and 'cilium assembly’. See first comment in this ticket. Is it appropriate to keep 'cilium morphogenesis’? Or should we merge the two terms and keep ‘cilium assembly’ as the primary name? If the latter, annotations to 'cilium morphogenesis' would be moved to ‘cilium assembly’. I’m calling upon our ciliary experts, please, to shed light on the usage of these terms in the literature and to give feedback on the best course of action. Attaching screenshot of simplified ‘cilium assembly’ placement (parents and children) for reference. Thanks!

(Note for self: I'll email John van Dam as he doesn't have a GH account yet)

**Comment by paolaroncaglia** [comment]
[cilium_assembly.pdf](https://github.com/geneontology/go-ontology/files/173637/cilium_assembly.pdf)

**Comment by paolaroncaglia** [comment]
From John (looking into making his GH account work):

"My two cents: Indeed these two terms share a lot of overlap in meaning. My personal experience says that the term "cilium assembly" is more often used than "cilium morphogenesis". Now as I understand this correctly "morphogenesis" is supposed to indicate the process  towards organising the assembly of a structure. This would mean starting the transcriptional processes to produce the necessary building blocks, maturation of the centriole into a basal body, creation and migration of the ciliary vesicle to the appointed location, etc. Which means, strictly, we have processes producing the actual building blocks, but also some processes to organise the building blocks before assembly begins, such as positioning and regulation. According to this argument, both terms are distinct and "cilium assembly" is_part_of "cilium morphogenesis". In literature though I fear that this distinction is rarely made. However for consistency with similar terms I think we should keep them separate. I've just looked at the child terms of "cilium morphogenesis" and I think we may be able to add some term to extend this rather poorly defined part of cilia GO terminology. I might want to consult some other syscilia experts before putting them forward."

**Comment by JohnvanDam** [comment]
Test

**Comment by paolaroncaglia** [comment]
Hi John,

Thanks for your thoughts. Based on what you write, I think that in the case of cilia we should stick to our resolution of no longer using morphogenesis/results_in_morphogenesis to refer to assembly or generation of shape of a cellular component. My feeling is that the processes leading to cilium assembly should be captured as ‘cilium organization’ (“A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a cilium…”), which is a parent of ‘cilium assembly’. I’d like to ask David Hill @ukemi for his opinion as he’s our reference editor for ‘developmental’ issues. Given the differences with morphogenesis and assembly of tissues, I’m a bit unsure about what would belong to regulation of assembly and what to organization.

This said, of course it would be useful to have feedback from the wider SYSCILIA group on how to expand the 'cilium organization' branch, if you'd like to consult with them.

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
And of course, we can look into how Reactome models 'assembly of the primary cilium', which at a first glance seems consistent with my comment above: 
http://www.reactome.org/PathwayBrowser/#/R-HSA-5617833

**Comment by krchristie** [comment]
I have no objection to not using morphogenesis to refer to assembly of cell components such as cilia. I have enough of a hard time distinguishing between morphogenesis and development of tissues, but at least I have a basic understanding of the difference. For the cilium, I don't understand what morphogenesis would be as distinct from assembly.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks Karen.

@JohnvanDam, mentioning you here as you may not have received notifications from this ticket.

**Comment by JohnvanDam** [comment]
Hi Paola,

I was, but waited to react because this discussion contains an internal GO discussion (morphogenesis vs. assembly). I thought to wait a bit so I could better gauge where it would go and then react :-)

The issue is very semantic in nature, but if I would approach it from how these terms would be used IRL I'd give my points to "assembly" over "morphogenesis".

I'll send a link of this discussion now to Rachel Giles so she might way in as a syscilia expert.

Cheers,
John

**Comment by paolaroncaglia** [comment]
Thanks John!

**Comment by paolaroncaglia** [comment]
So if we wanted to get rid of 'cilium morphogenesis', we'd need to assess where its annotations would belong (cilium organization or cilium assembly?). The answer would also clarify the best ontology strategy (merge vs obsolete). 

Looking at the ontology, 'cilium morphogenesis' has 2 children (both part_of): cilium assembly and intraciliary transport involved in cilium morphogenesis. The former doesn't need any work, it already has the parent 'cilium organization'. As for 'intraciliary transport involved in cilium morphogenesis', is this part of cilium organization or assembly? It’s got 24 experimental annotations, they can be retrieved here and by filtering for evidence = manual experimental only: 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0035735#term=annotation
‘cilium morphogenesis’ itself has 243 *direct* experimental annotations (i.e. to the term itself alone, not to its children), nearly half of which are to zebrafish (then MGI and UniProt). 
We may need to consult with the individual databases. To start with, I’ll ask David from MGI to comment, please, on the MGI annotations as well as on the internal debate morphogenesis vs assembly, see other comments in this thread.
@ukemi

Thanks!

**Comment by paolaroncaglia** [comment]
Note for self: this link is weird and needs double-checking as soon as the current GO release issues are fixed:
cell projection morphogenesis contains cilium organization 
presumably a mistake.

**Comment by JohnvanDam** [comment]
Note: potentially interesting review paper on cilia assembly and disassembly:

Sánchez I, Dynlacht BD. Cilium assembly and disassembly. Nat Cell Biol. 2016
Jun 28;18(7):711-7. doi: 10.1038/ncb3370. Review. PubMed PMID: 27350441.

http://www.ncbi.nlm.nih.gov/pubmed/27350441

**Comment by paolaroncaglia** [comment]
@krchristie @JohnvanDam 

Back to (the first part of) my previous comment:

“So if we wanted to get rid of 'cilium morphogenesis', we'd need to assess where its annotations would belong (cilium organization or cilium assembly?). The answer would also clarify the best ontology strategy (merge vs obsolete).

Looking at the ontology, 'cilium morphogenesis' has 2 children (both part_of): cilium assembly and intraciliary transport involved in cilium morphogenesis. The former doesn't need any work, it already has the parent 'cilium organization'. As for 'intraciliary transport involved in cilium morphogenesis', is this part of cilium organization or assembly? It’s got 24 experimental annotations, they can be retrieved here and by filtering for evidence = manual experimental only: 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0035735#term=annotation”

I looked at the abstracts of the PMIDs that support the 24 experimental annotations to 'intraciliary transport involved in cilium morphogenesis’. Here’s a summary of what I think the curators meant:
PMID:18094047 => 'intraciliary transport involved in cilium assembly’ (term doesn’t exist yet)
PMID:23990561 => 'intraciliary transport involved in cilium assembly’
PMID:24550735 => can’t say from the abstract
PMID:24843028 => ’intraciliary transport involved in cilium assembly’
PMID:24356449 => can’t say from the abstract (it mentions “formation and maintenance”… how would we represent maintenance in this context?)
PMID:22508513 => 'intraciliary transport involved in cilium assembly’
PMID:21209331 => can’t say from the abstract
PMID:19732765 => can’t say from the abstract

Question for you:
The abstract of PMID:18094047 starts with “Intraflagellar transport (IFT) is the bidirectional movement of protein complexes required for cilia and flagella formation.”. 
The abstract of PMID:24843028 starts with “The construction of cilia and flagella depends on intraflagellar transport”.
Is intraciliary transport involved in any process other than cilium assembly, e.g. cilium disassembly? Depending on the answer, (some of) the PMIDs above may simply be annotated to ‘intraciliary transport’.
The Summation of the Reactome entry for ‘Intraflagellar transport’ (http://www.reactome.org/content/detail/R-HSA-5620924) seems to refer to role in cilium assembly only (and the pathway is placed as such), but I guess that wouldn’t automatically rule out a role in other processes. Though…

Thanks!

**Comment by JohnvanDam** [comment]
Quick answer: The IFT is needed to transport stuff. For assembly this means it is indispensable for getting all the building blocks (e.g. tubulin) at the right place (tip) within a reasonable amount of time (diffusion is too slow). For disassembly it means getting rid of dissociated tubulin from the microtubules at the tip. For generic functioning and maintenance of the cilium it is required to transport new tubulin up and old tubulin down to maintain cilia length as well as drag in and out the membrane components required for signaling and such. In short the IFT is not specifically involved in assembly. Though logically with defective IFT the logical outcome is that cilium assembly is affected first, and therefore "maintenance" and "disassembly" processes become irrelevant experimentally.
There is increasingly more information of IFT components being involved in intra-cellular transport other than cilia related components as well.

**Comment by paolaroncaglia** [comment]
Wrapping up, I opt for the following strategy:

- [] start with ‘intraciliary transport involved in cilium morphogenesis’, and ask curators if annotations from ’uncertain’ PMIDs listed above would fit well under ‘intraciliary transport involved in cilium assembly’ (or organization, or disassembly, or regulation of one of these 3). That’s PMID:24550735, PMID:24356449, PMID:21209331, PMID:19732765;
- [] continue with ‘cilium morphogenesis’, and ask curators of its *direct* experimental annotations the same question; 
- [] when annotations have been looked into, merge ‘cilium assembly’ into ‘cilium morphogenesis’ (can’t do the opposite as assembly is part_of morphogenesis);
- [] keep ‘assembly’ as primary name, and ‘morphogenesis’ as related synonym;
- [] remove is_a links to ‘morphogenesis’ terms;
- rename ‘intraciliary transport involved in cilium morphogenesis’ as ‘intraciliary transport involved in cilium assembly’, and adjust logical def. and part_of link accordingly.

**Comment by paolaroncaglia** [comment]
[ciliary_annotations.xlsx](https://github.com/geneontology/go-ontology/files/471691/ciliary_annotations.xlsx)

@jimhutamu
@hdrabkin 
@ukemi
@zebrafishembryo
@RLovering (for BHF-UCL and ParkinsonsUK-UCL) 
@hattrill 
@slaulederkind
@vanaukenk
@doughowe

Dear curators,

We are looking into merging ‘cilium assembly’ and ‘cilium morphogenesis’, and keep ‘cilium assembly’ as the primary name. This is based on outcome of discussion among editors and cilia experts. ‘cilium assembly’ is currently part_of ‘cilium morphogenesis’, so, before we go ahead with the merge, we need to make sure that annotations to ‘cilium morphogenesis’ can live appropriately under ‘cilium assembly’ instead - or if they should be moved to ‘cilium organization’, ‘cilium disassembly’ or ‘regulation of cilium organization/assembly/disassembly’. I’m attaching a spreadsheet listing the experimental annotations that would be affected by the merge (except for some annotations that I’ve already checked myself), conveniently sorted and color-coded based on originating database/group. Could you please go through the list. If you evaluate that those annotations would be fine under the corresponding assembly term (as indicated in bold), then you don’t need to do anything. Otherwise, please rehouse annotations as necessary. 

Many thanks in advance for your help with this. **I will proceed with the merge on Wed Sept 21st.** If you need more time, please let me know.

(Note for self: I’ll email goa@ebi.ac.uk and GeneDB pointing them to this ticket.)

**Comment by doughowe** [comment]
Hi Paula,
    It looks like we have 109 annotations from 109 different papers that need a review.  That's going to take a little time.  Can the proceedings be delayed a bit?
Thanks,
   Doug

**Comment by paolaroncaglia** [comment]
Hi @doughowe and @sabrinatoro,
Yes, sure - ZFIN is the main contributor of those annotations. I'll check with you again next week, so we can re-assess. (Note for self: at the same time, I'll remind the other curators if necessary.)
Thank you,
Paola

**Comment by sabrinatoro** [comment]
Thank you Paola! We'll keep you updated on the progress.

**Comment by sabrinatoro** [comment]
@paolaroncaglia, I have powered through the ZFIN annotations (there was less publications than expected), and it looks like it would be fine for these annotations to be under the "cilium assembly" term. Only one annotation needed to be updated to a different term, which I have done locally in ZFIN. 
Let me know if you need anything else! Thanks!

**Comment by krchristie** [comment]
@paolaroncaglia 
@hdrabkin 

I think I'm going to check the MGI ones, but I need to work on a non-GO project next week, so not quite sure when MGI will be done. I'll keep you posted.

-Karen

**Comment by paolaroncaglia** [comment]
@sabrinatoro thanks you so much!

**Comment by paolaroncaglia** [comment]
@krchristie thanks, we can re-adjourn when I send a reminder. Sorry, it was silly of me to ask @ukemi and @hdrabkin instead of you for these MGI cilia annotations - I just went on auto-pilot!

**Comment by RLovering** [comment]
I have looked a some of the annotations, I can see why morphogenesis was used because there is a change in the shape of the cilia associated with a mutant protein, however, I can also appreciate that this could be interpreted as cilia assembly issues. Therefore, I am happy for the UCL annotations to be changed to assembly annotations.

**Comment by paolaroncaglia** [comment]
Thanks @RLovering .

**Comment by krchristie** [comment]
@paolaroncaglia 
@jimhu-tamu

Regarding the one annotation by CACAO to "GO:0035735 intraciliary transport involved in cilium morphogenesis", this happens to be to a mouse gene (I generated a spreadsheet with all annotations to mouse genes via MouseMine in order to have a list based on mouse gene names since it's an extra step to translate UniProt IDs in the MGI system.)

Based on looking at the paper, I think the figure this annotation is based on supports an annotation to "intraciliary retrograde transport" (changes in the morphology of tip of the cilium are often characteristic of defects in intraciliary retrograde transport), though it would be redundant with an existing annotation added by a different annotation group that worked on the same paper, so probably this one should just be deleted. I've put a comment to this effect into the Protein2GO annotation challenge system.

-Karen

**Comment by paolaroncaglia** [comment]
Thank you @krchristie ! I'll mark this as dealt with then, since it's recorded via P2GO.

**Comment by hattrill** [comment]
Reviewed the FlyBase set and I'm fine with the merge. Helen.

**Comment by paolaroncaglia** [comment]
Thanks @hattrill!

**Comment by doughowe** [comment]
Hi Paola,
   We have reviewed our GO annotations and our phenotype annotations that use "cilium morphogenesis".  I believe we have them all updated to "cilium assembly" or another term if appropriate.  So the zebrafish annotations that we make should be taken care of.  If there are IEA annotations that come from load processes, those will update themselves when our load runs and the source has made the update on their end.
Thanks,

 Doug

**Comment by paolaroncaglia** [comment]
Thanks @doughowe !

**Comment by vanaukenk** [comment]
@paolaroncaglia 
I'm back from vacation and will review the 11 C. elegans annotations to 'cilium morphogenesis' this week.  Thx.

**Comment by paolaroncaglia** [comment]
Thank you @vanaukenk .

**Comment by vanaukenk** [comment]
Hi @paolaroncaglia 

I've reviewed the C. elegans annotations and updated the WB annotations to 'nonmotile primary cilium assembly' (GO:0035058).

There are some C. elegans annotations from other groups that still need review.  

Also, there are three PAINT annotations for C. elegans genes that I assume will be corrected once the corresponding PANTHER families are re-annotated?  

Note that due to the WB release cycle, the revised annotations will not appear on WB and the GOC website until later this year (~late November - early December).

Here's a summary of the status of the C. elegans annotations:

WB annotations updated to 'nonmotile primary cilium assembly' (GO:0035058) for:
      osm-6|WB:WBGene00003886|UniProtKB:G5EDF6
      mksr-1|WB:WBGene00019364|UniProtKB:Q21191
      arl-13|WB:WBGene00021349|UniProtKB:H2L0N8
      mks-1|WB:WBGene00020100|UniProtKB:H2KZA7|UniProtKB:O17269
      mksr-2|WB:WBGene00021416|UniProtKB:Q9N423
      dyf-2|WB:WBGene00001118|UniProtKB:G5ECZ4

GOA annotations still needing review:
      arl-13|WB:WBGene00021349|UniProtKB:H2L0N8   -  Sylvain Poux
      odr-3|WB:WBGene00003850|UniProtKB:Q18434    -  Elena Speretta

MGI annotations still needing review:  @krchristie ?
      dyf-2|WB:WBGene00001118|UniProtKB:G5ECZ4

PAINT annotations still needing review:  @pgaudet ?
      klp-20| WB:WBGene00002230|UniProtKB:Q965T6
      T12B3.1|WB:WBGene00020444|UniProtKB:Q9UAX0
      ZK328.7|WB:WBGene00022696|UniProtKB:Q20255

**Comment by krchristie** [comment]
Hi @vanaukenk 

I will take care of the MGI annotations for dyf-2. I will also take care of these two PAINT families since they were done my either Li or myself.

before 4-Mar-15 Li      PTHR24115        FAMILY NOT NAMED 2329
29-Jul-2014     KRC     PTHR14699        STI2 PROTEIN-RELATED 76

I'll leave this one for @pgaudet 
18-Aug-2015     MAF     PTHR23339        TYROSINE SPECIFIC PROTEIN PHOSPHATASE AND DUAL SPECIFICITY PROTEIN PHOSPHATASE 340

This week, I am working on projects funded by a different grant, but I will do these first thing next week (Sept 26th).

thanks,

-Karen

**Comment by vanaukenk** [comment]
Thanks, @krchristie !

**Comment by paolaroncaglia** [comment]
Thank you @vanaukenk and @krchristie.

**Comment by krchristie** [comment]
Hi @paolaroncaglia 

I have finished checking and updating all the MGI ones. I also accidentally did a couple papers annotated by UniProt that have mouse annotations and have submitted suggestions to update via P2GO. After reviewing these annotations, I definitely think that there is no difference between these two terms and the merge is a good plan.

The remaining mouse annotations to "cilium morphogenesis" were generated by other sources:

GOA_BHF-UCL
- PMID:18299575 - Bbs1, Bbs2, Bbs4, Mkks
- PMID:18371931 - Nphp3
@RLovering - could you or someone in your gorup take a look at these?

GOA-UniProt
- PMID:9739041  - Foxj1
- PMID:11062270 - Ift88
- PMID:19000668 - Ift122
- PMID:16311594 - Ofd1
- PMID:20230748 - Ofd1
- PMID:21750036 - 2700049A03Rik

@vanaukenk 
I have fixed the C. elegans one generated by MGI.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks @krchristie !

As for the BHF-UCL annotations, @RLovering wrote previously: "I have looked at some of the annotations, I can see why morphogenesis was used because there is a change in the shape of the cilia associated with a mutant protein, however, I can also appreciate that this could be interpreted as cilia assembly issues. Therefore, I am happy for the UCL annotations to be changed to assembly annotations." So we're good.

I'm waiting to hear from UniProt, then I'll go ahead with the plan.

**Comment by paolaroncaglia** [comment]
Note for self: 
UniProt-GOA agreed to the merge (no need to rehouse annotations).
UniProt-SIB - I emailed help@uniprot.org today.

**Comment by paolaroncaglia** [comment]
Note for self: 
help at uniprot dot org replied yesterday and forwarded to the Swiss-Prot curators.
