### ISSUE TITLE
Update OBO file format version in OBO files

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12238]
from http://jira.geneontology.org/browse/GO-1070

@dosumis  said "Related issued: Our OBO files all have this tag at the top.

format-version: 1.2

Way past time to change this to 1.4."

@cmungall said "OE will save with 1.2. We should probably update the spec to make it clear the 1.4 spec can be used to parse 1.2, but not every 1.2 file is a valid 1.4 file."

Not sure whether this is something we want to update as we anticipate switch to Protege soon-ish?

cc @hdietze

**Comment by cmungall** [comment]
will need to cut a new OE release

**Comment by paolaroncaglia** [comment]
Hi @cmungall @hdietze and @mcourtot 
Not sure if there's any update on this, or if a separate GH ticket has been created on another tracker, but assigning to Chris so it doesn't get lost.
Cheers
Paola

**Comment by cmungall** [comment]
I don't think there's any action here, now worth bringing OE out of hibernation for, and possibly risk breaking downstream consuming programs that hardcode all kinds of assumptions
