### ISSUE TITLE
Telomere replication

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12230]
Hi 

Hope this is a quick fix!

please could the telomere ontology be re-arranged slightly.

Telomere maintenance via telomere lengthening should NOT be a parent to telomere maintenance via semi-conservative replication - as telomere lengthening of any sort  is always telomere maintenance - but 'normal' semi-conservative DNA replication is in fact going to lead to telomere shortening in cells with no active telomerase.

So the new ontology should be:
GO:0000723 telomere maintenance
> is_a  child GO:0032201	telomere maintenance via semi-conservative replication
> is_a child GO:0010833	telomere maintenance via telomere lengthening
These child terms are siblings not related via parent-child

not sure that you put dbxrefs for ontology rearrangements: GOC:BHF, GOC:BHF_telomere, GOC:rl

Thanks

Ruth

**Comment by ValWood** [comment]
I don't think its clear what these 2 processes are (although I think I probably requested them years ago).
How do telomeres replicate if not via telomerase?
@mah11  might remember more...

Val

**Comment by hdrabkin** [comment]
digging out some very old stuff that I had long forgotten:
. Drosph. appears different.
From Genome Biol. 2002; 3(10): reviews0007.1–reviews0007.6.
Published online 2002 Sep 27. doi:  10.1186/gb-2002-3-10-reviews0007
"First of all, telomere maintenance in Drosophila is not performed by the canonical telomerase but by a unique transposition mechanism. Two non-LTR (long terminal repeat) retrotransposable elements, HeT-A and TART telomere-associated retrotransposons, are attached specifically to the chromosome ends  (references therein).

**Comment by RLovering** [comment]
not many human cells have telomerase, (e.g. mostly stem cells and cancer cells) but they still have to replicate their DNA using polymerases, but then they get shorter at each replication cycle due to the lack of telomerase

**Comment by ValWood** [comment]
We aren't annotating cancer cells though? only normal cells? (presumably  some stem cells don't have active telomerase if their telomeres are not yet shortened?)

Pombe does some things in mutants lacking telomerase to 'trick' cells into  not perceiving ds breaks at chromosome ends using DSB machinery and recombination... but these are random/chance events giving raise to small populations  of 'survivors'. If these studies are being done in cancer cell lines perhaps don't represent  processes occurring in "normal" cells...Just a thought ......

(PS I don't think human and yeast are *so * different ;)

**Comment by RLovering** [comment]
Hi Val

All germ cells and many stem cells have telomerase as they need to protect their telomeres.

Human telomeres have TTAGGG repeated approximately 2,500 times and at each replication cycle the various different replication and repair methods may lead to the lengthening or shortening of the repeat. For example there is more replication fork stalling due to the repetitive nature of the DNA. This is not the sub-telomeric region as when the telomere shortens these repeats become the shelterin protected part of the 'telomere'.  

PMID: 26188776 has a good summary about replicating. Although the suggestion that the telomeres in differentiated cells are lengthened by telomerase when they get too short isn't something that I have read about myself and I am not totally convinced about this, mostly people seem to think that when the telomeres get too short the cell become senescent or die. Anyway hopefully this will convince you that telomere replication has additional features which are unique to telomeres (any maybe other heterochromatic regions - I haven't check this) and therefore the specific term is needed, but does not necessarily lead to lengthening of the telomere. Ill comment on the definition in the other ticket.

**Comment by paolaroncaglia** [comment]
Hi @RLovering ,

Could you please review this ticket, and summarise if/what change is requested?
(You wrote “I’ll comment on the definition in the other ticket”, but there is no link, so I’m not sure if your issue was fixed elsewhere and this ticket can be closed or not.)
I also have this other ticket about telomeres with comments from you and Val, could you please check if there is any duplication (i.e. same or similar issue(s) reported in both tickets): https://github.com/geneontology/go-ontology/issues/12227 

A revision/summary may make things quicker for all parts involved, many thanks,

Paola

**Comment by RLovering** [comment]
Hi Paola and @ValWood 

the two tickets (this one and #12227) can be closed if the following is done:

GO:0000723 telomere maintenance
new definition: 
Any process that contributes to the maintenance of proper telomeric length and structure by affecting and monitoring the activity of telomeric proteins, the length of telomeric DNA and the replication and repair of the DNA. These processes includes those that shorten, lengthen, replicate and repair the telomeric DNA sequences.
the new ontology should be:
GO:0000723 telomere maintenance
is_a child GO:0032201 telomere maintenance via semi-conservative replication
is_a child GO:0010833 telomere maintenance via telomere lengthening

Val also expressed an interest in having a term "telomere length maintenance" as a parent to telomere maintenance via telomere lengthening and telomere capping. 
I would be concerned that this will get confusing, as even DNA repair is occurring to maintain the length of the telomere (but this wouldn't be a child of the telomere length maintenance term) and this term name is very similar to it's child term telomere maintenance via telomere lengthening. 

Maybe Val can confirm whether she is still concerned about the early split in the ontology between telomere maintenance via telomere lengthening and telomere capping. 

Best
Ruth

**Comment by ValWood** [comment]
Hi Ruth,

Go ahead with your suggestions, I'm probably being overly picky. I'm also not realistically going to  be annotating telomere biology shortly so we  can make any necessary adjustments if we need to. I think you guys know best.

VAl

**Comment by paolaroncaglia** [comment]
Thanks @RLovering and @ValWood ,
All done as Ruth suggested. Closing now.
