### ISSUE TITLE
fun with regulation chains and compound terms

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12235]
label "negative regulation of neuron apoptotic process by negative regulation of transcription from RNA polymerase II promoter"

is getting the inference: SubClassOf: 'positive regulation of neuron apoptotic process'

![image](https://cloud.githubusercontent.com/assets/112839/12359323/ade60ccc-bba9-11e5-95d4-beb92933b3af.png)

Due to this axiom:
-veR o -veR -> +veR

The problem is the EC axiom, which comes from a TermGenie template gone bad

'regulation of biological process' and ('negatively regulates' some 'negative regulation of neuron apoptotic process by transcription from RNA polymerase II promoter')

Sketching this axiom out as a pathway makes the problem clear:

X -- -veR --> transcription -- -veR--> 'neuron apoptotic process'

That second step should really be +veR: if negatively regulating expression of a gene prevents apoptosis then the expression must be pro-apoptotic.

This could be written as 

'regulation of biological process' and 'negatively regulates' some ('transcription from RNA polymerase II promoter' that 'positively regulates' some 'neuron apoptotic process')

But we can' use nested class statements like this.  We instead need to reify the class:  

positive regulation of neuron apoptotic process by regulation of transcription from RNA polymerase II promoter':
EquivalentTo: 'transcription from RNA polymerase II promoter' that 'positively regulates' some 'neuron apoptotic process'

=> 
negative regulation of neuron apoptotic process by negative regulation of transcription from RNA polymerase II promoter'
EquivalentTo: 'regulation of biological process' and 'negatively regulates' some 'positive regulation of neuron apoptotic process by regulation of transcription from RNA polymerase II promoter'

Tried this, but it turns out we don't (yet) have the axiom: -veR o +veR -> -veR.

I the meantime, we could just assert the two  -ve regulation terms as is_a parents.

The wider issue is that the solution is just not obvious enough  We'll tie ourselves in knots trying to deal with single terms that pack in pathways like this.  Can we just ban this stuff until we have LEGO?

CC @cmungall

**Comment by dosumis** [comment]
Oh - and the negative and positive versions of the 'regulation by' template should be removed from TG.

CC @hdietze

**Comment by cmungall** [comment]
> Tried this, but it turns out we don't (yet) have the axiom: -veR o +veR -> -veR.

This one is on me. Maybe best make a new ticket so it doesn't get lost

> The wider issue is that the solution is just not obvious enough We'll tie ourselves in knots trying to deal with single terms that pack in pathways like this. Can we just ban this stuff until we have LEGO?

Yes, and in fact if we re-make the annotation in Noctua now it will be preserved, and will show up in a GAF export shortly. 

Although in this case it's never been used in annotation, despite being created 8 months ago
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0100069#term=history

obsolete!

**Comment by dosumis** [comment]
> obsolete!

OK.

Other examples:


 "negative regulation of filamentous growth of a population of unicellular organisms in response to starvation by negative regulation of transcription from RNA polymerase II promoter"
**EquivalentTo: **'regulation of biological process'
 and ('negatively regulates' some 'negative regulation of filamentous growth of a population of unicellular organisms in response to starvation by transcription from RNA polymerase II promoter')
**Inferred SubClassOf:**'positive regulation of filamentous growth of a population of unicellular organisms in response to starvation'


GO:1902625 'negative regulation of induction of conjugation with cellular fusion by negative regulation of transcription from RNA polymerase II promoter' 
**EquivalentTo** : 'regulation of biological process'
 and ('negatively regulates' some 'negative regulation of induction of conjugation with cellular fusion by transcription from RNA polymerase II promoter')
**inferred SubClassOf:** GO:1904788 'positive regulation of induction of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter'

This one also follows the pattern,  but with added weirdness:

![image](https://cloud.githubusercontent.com/assets/112839/12389866/936e07a6-bdd3-11e5-8fd3-cb162d7e511a.png)

@ukemi - can you comment?


List from OBO-Edit by name query for 'by negative regulation of' + is_intersection: true

GO:1900465	negative regulation of arginine catabolic process by negative regulation of transcription from RNA polymerase II promoter
GO:0038056	negative regulation of BMP signaling pathway by negative regulation of BMP secretion
GO:1900387	negative regulation of cell-cell adhesion by negative regulation of transcription from RNA polymerase II promoter
GO:1900403	negative regulation of cellular amino acid biosynthetic process by negative regulation of transcription from RNA polymerase II promoter
GO:0010678	negative regulation of cellular carbohydrate metabolic process by negative regulation of transcription, DNA-templated
GO:1900464	negative regulation of cellular hyperosmotic salinity response by negative regulation of transcription from RNA polymerase II promoter
GO:1900463	negative regulation of cellular response to alkaline pH by negative regulation of transcription from RNA polymerase II promoter
GO:0061427	negative regulation of ceramide biosynthetic process by negative regulation of transcription from RNA Polymerase II promoter
GO:0035955	negative regulation of dipeptide transport by negative regulation of transcription from RNA polymerase II promoter
GO:1902352	negative regulation of filamentous growth of a population of unicellular organisms in response to starvation by negative regulation of transcription from RNA polymerase II promoter
GO:1900477	negative regulation of G1/S transition of mitotic cell cycle by negative regulation of transcription from RNA polymerase II promoter
GO:1902625	negative regulation of induction of conjugation with cellular fusion by negative regulation of transcription from RNA polymerase II promoter
GO:1900471	negative regulation of inositol biosynthetic process by negative regulation of transcription from RNA polymerase II promoter
GO:1900460	negative regulation of invasive growth in response to glucose limitation by negative regulation of transcription from RNA polymerase II promoter
GO:1900474	negative regulation of mating type switching by negative regulation of transcription from RNA polymerase II promoter
GO:1904490	negative regulation of mitochondrial unfolded protein response by negative regulation of transcription from RNA polymerase II promoter
GO:1904089	negative regulation of neuron apoptotic process by negative regulation of transcription from RNA polymerase II promoter
GO:0035952	negative regulation of oligopeptide transport by negative regulation of transcription from RNA polymerase II promoter
GO:1900473	negative regulation of phosphatidylcholine biosynthetic process by negative regulation of transcription from RNA polymerase II promoter
GO:1900526	negative regulation of phosphatidylserine biosynthetic process by negative regulation of transcription from RNA polymerase II promoter
GO:1900462	negative regulation of pseudohyphal growth by negative regulation of transcription from RNA polymerase II promoter
GO:1901294	negative regulation of SREBP signaling pathway by negative regulation of DNA binding

**Comment by dosumis** [comment]
One more idea:

When creating 'negative regulation of X' and 'positive regulation of X', shouldn't we be creating disjointness axioms too?  This would catch cases like this without us needing to eyeball them.

Can imagine some difficult cases arising from "regulates o 'part of' -> regulates" though - what if some process X positively regulates process Y and negatively regulates process Z, where both are part of process A.  This sounds like plausible biology to me.  Although this seems like yet another reason the regulates over part of property chain may be dangerous, rather than an argument against the disjointness axioms.

**Comment by paolaroncaglia** [comment]
A bit of term archeology in case it’s useful (and may unveil other problematic terms)

Chris writes “Although in this case it's never been used in annotation, despite being created 8 months ago
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0100069#term=history
obsolete!”

This being an apoptosis term I was curious, so I looked it up. It appears Chris himself created the term :-) 

[Term]
id: GO:0100069
name: negative regulation of neuron apoptotic process by transcription from RNA polymerase II promoter
namespace: biological_process
def: "Any transcription from RNA polymerase II promoter process that negatively_regulates neuron apoptotic process" [GOC:cjm, GOC:obol]
is_a: GO:0006366 {is_inferred="true"} ! transcription from RNA polymerase II promoter
intersection_of: GO:0006366 ! transcription from RNA polymerase II promoter
intersection_of: negatively_regulates GO:0051402 ! neuron apoptotic process
created_by: cjm
creation_date: 2015-04-02T04:13:19Z

Then I remembered - this is one of a set of terms that Chris added as we were trying to deal with results_in terms
http://wiki.geneontology.org/index.php/Ontology_meeting_2015-04-02 
All terms ranging from GO:0100001 to GO:0100070 were created as part of the same work. Hopefully GO:0100069 is the only problematic one :-)

Let’s wait to solve the whole issue before sending out an obsoletion notice, in case there are others.

**Comment by dosumis** [comment]
> Hopefully GO:0100069 is the only problematic one :-)

Everything following the -ve by -ve => -ve pattern is problematic.  List in comment above. 

> Let’s wait to solve the whole issue before sending out an obsoletion notice, in case there are others.

My suggestion is that we don't obsolete until the 49 current annotations until we have lego models that => correct inferred annotations.  Might take some time. But in the meantime, we need to do something to fix all the current terms before they cause more problems.

**Comment by dosumis** [comment]
TODO: 
 - [ ] Send out obsoletion notice for all these terms where there is no annotation
 - [ ] Remove EC axioms for the remainder, adding manual assertions where possible.
 - [ ] Contact annotators who have annotated with these terms requesting re-annotation - ideally via a lego model.

**Comment by dosumis** [comment]
> Remove EC axioms for the remainder, adding manual assertions where possible.

Alternative axiomatisation:

'negative regulation of pseudohyphal growth by negative regulation of transcription from RNA polymerase II promoter'
EquivalentTo: 'regulation of biological process' and 'negatively regulates' some 'negative regulation of pseudohyphal growth by transcription from RNA polymerase II promoter'
--> 'negative regulation of transcription from RNA polymerase II promoter' and 'negatively regulates' some 'pseudohyphal growth'

Originally rejected this because it appears to reverse genus and differentium - but on further consideration, I think this is OK as there is inference to both negative reg parents.  @cmungall - do you agree?

Bit less expressive/explicit than the LEGO versions though, where you would presumably have a node for gene expression followed by another regulatory link.

**Comment by ukemi** [comment]
I thought about this strategy last week and gave it a whirl. It seemed to have worked when I looked at the inferences.

**Comment by dosumis** [comment]
Fixed all using alternative axiomatisation above.
