### ISSUE TITLE
NTR - MVB-lysosome fusion or MVB-lysosome maturation

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12234]
By analogy with GO:0097352 autophagosome maturation
Def: The process in which autophagosomes, double-membraned vacuoles containing cytoplasmic material fuse with a vacuole (yeast) or lysosome (e.g. mammals and insects). In the case of yeast, inner membrane-bounded structures (autophagic bodies) appear in the vacuole. Fusion provides an acidic environment and digestive function to the interior of the autophagosome.

I think we need a term such as: 
MVB–lysosome fusion or MVB–lysosome maturation. 
In PMID: 21118109 review states:
"MVB–lysosome fusion. The terminal compartment in the autophagy pathway is termed the auto- lysosome, whereas the result of fusion of a lysosome with an MVB leads to a terminal degradative compartment termed a hybrid organelle."

I would use this as a more specific term to annotate members of the ESCRT2 or ESCRT3 complex family (or the complexes themselves, if I get an INTACT Complex identifier for them). These protein complexes play role in the membrane fusion step right at the end of autophagy, when autophagosomes fuse with the lysosome.
GOC:pad
GOC:PARL

**Comment by Pauldenny** [comment]
Birgit - I think this is relevant to your endosome-lysosome issue and also the ESCRT complexes
@bmeldal

**Comment by bmeldal** [comment]
Thanks, Paul.
ESCRT-III is under review and will hopefully be released next week. If your requested term is created later I will add the xref subsequently and it will appear at the following release.

Working on the related VPS4 complex now...

**Comment by ukemi** [comment]
How about:

MVB–lysosome fusion
is_a: organelle membrane fusion
part_of: endosome to lysosome transport via multivesicular body sorting pathway
def: The organelle membrane fusion process in which the membrane of a multivesicular body fuses with a lysosome to create a hybrid organelle.
PMID:21118109
GOC:pad
GOC:PARL
GOC:dph

**Comment by Pauldenny** [comment]
Hi David - would you also create synonym 
"multivesicular body-lysosome fusion" [exact?]

**Comment by ukemi** [comment]
Hi Paul,
Actually, that wold be a better primary term name since that is what it is called in cellular component. I will make the term later this morning.
-D

**Comment by ukemi** [comment]
[Term]
+id: GO:0061763
+name: multivesicular body-lysosome fusion
+namespace: biological_process
+def: "The organelle membrane fusion process in which the membrane of a multivesicular body fuses with a lysosome to create a hybrid organelle." [GOC:dph, GOC:pad, GOC:PARL, PMID:21118109]
+synonym: "MVB-lysosome fusion" EXACT [GOC:dph]
+is_a: GO:0090174 {is_inferred="true"} ! organelle membrane fusion
+intersection_of: GO:0061025 ! membrane fusion
+intersection_of: results_in_fusion_of GO:0005765 ! lysosomal membrane
+intersection_of: results_in_fusion_of GO:0032585 ! multivesicular body membrane
+created_by: dph
+creation_date: 2016-04-15T07:12:40Z

**Comment by bmeldal** [comment]
@Pauldenny I have added the new term to the ESCRT-III and VSP4 complexes.
