### ISSUE TITLE
Cellular component assembly/disassembly - add missing logical definitions

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12232]
Though logical definitions (aka ‘cross-products’) have been added broadly to the ontology, a few stray terms have escaped the effort. Making a note here as my task to look at the branches under ‘cellular component assembly’ and ‘cellular component disassembly’ and add the missing defs.

(Note for self: previous work was recorded in a Jira ticket
https://www.ebi.ac.uk/panda/jira/browse/GO-178
now closed, but may wish to look into its more recent comments.)

**Comment by paolaroncaglia** [comment]
I've looked at the 'cellular component disassembly' branch and the only term that was obviously lacking a logical def was 'mitochondrion disassembly'. Now added. 

Next, face the 'cellular component assembly' branch...

**Comment by paolaroncaglia** [comment]
Opened related https://github.com/geneontology/go-ontology/issues/12711.
Added GO:0097735 ’DIM/DIP cell wall layer’; added logical def to ‘DIM/DIP cell wall layer assembly’.

**Comment by paolaroncaglia** [comment]
Left to do: see if these terms should be given logical definitions:

- [ ] intermediate filament bundle assembly - should we have a term for ‘intermediate filament bundle’, has_part ‘intermediate filament’? Similar to the existing ‘actin filament bundle’. I suppose it would be meaningful to have it, as a bundle will have added value (function) than a single filament…
- [ ] neurofilament bundle assembly - same as above
- [ ] Gram-negative-bacterium-type cell outer membrane assembly - should we have a term for ‘Gram-negative-bacterium-type cell outer membrane’? Probably not as this could be captured by ‘cell outer membrane’, and the bacterial cell outer membrane is already a characteristic of Gram-negative-bacteria.
- [ ] metallo-sulfur cluster assembly - and descendants - not looked at yet
- [ ] mycolate cell wall layer assembly - not looked at yet

Also, still to do:

- [ ] Look at descendants of ‘macromolecular complex assembly’ to see if any need logical defs
- [ ] Look at descendants of ‘organelle assembly’ to see if any need logical defs

Then close.

**Comment by paolaroncaglia** [comment]
Looking at descendants of ‘organelle assembly’, these terms may be given a logical definition, but haven’t had time to check further so just making a note here:

- [ ] NMS complex assembly involved in kinetochore assembly
- [ ] children of cardiac myofibril assembly
- [ ] muscle thin filament assembly
- [ ] children of skeletal myofibril assembly
- [ ] children of striated muscle myosin thick filament assembly
- [ ] striated muscle paramyosin thick filament assembly

**Comment by ValWood** [comment]
Hi Paola,

At the same time, can
NMS complex assembly involved in kinetochore assembly
be renamed
NMS complex assembly 
(The NMS complex is part of the kinetochore so this is a given, it is also in the def)

Thanks

Val

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
As per your request 
"can
NMS complex assembly involved in kinetochore assembly
be renamed
NMS complex assembly 
(The NMS complex is part of the kinetochore so this is a given, it is also in the def)"
that's done. Cheers.

**Comment by paolaroncaglia** [comment]
Note for self: this is low priority, but I'll leave it assigned to me for the time being, in case we decide I should (be the one to) address it.

**Comment by paolaroncaglia** [comment]
Hi @pgaudet and @cmungall 
I noticed the discussion on old tickets in the minutes of the latest ontology call. Obviously at this point I'm not going to be working on this ticket any time soon. If you think that it's still relevant, could you please assign it to someone else? Else, I guess it can be closed according to your recent discussion. Thanks.

**Comment by pgaudet** [comment]
Assigning myself - I'll have a look.

**Comment by paolaroncaglia** [comment]
Thanks @pgaudet .

**Comment by pgaudet** [comment]
I created most of the logical definitions suggested here (and a few more in the assembly/organization branches), except for the ones that required creating new terms, including:
 children of cardiac myofibril assembly
muscle thin filament assembly
children of skeletal myofibril assembly
children of striated muscle myosin thick filament assembly
striated muscle paramyosin thick filament assembly
mycolate cell wall layer assembly 
Gram-negative-bacterium-type cell outer membrane assembly
