### ISSUE TITLE
relationship between spindle checkpoint and chromosome biorientation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12241]

**Comment by ValWood** [comment]
I think there should be a relationship between 
mitotic spindle assembly checkpoint and
A cell cycle checkpoint that delays the metaphase/anaphase transition of a mitotic nuclear division until the spindle is correctly assembled and chromosomes are attached to the spindle. 

mitotic sister chromatid biorientation
The cell cycle process in which mitotic sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles.

"Thus, although Mad2 and Mad3 are required solely for the SAC, Mph1, Bub1, Bub3 and Mad1 might have additional mitotic roles in chromosome bi- orientation beyond the SAC." PMID:26256832

The SAC inhibits anaphase until all chromosomes have biorientated so it must be a part of the biorientation process?

**Comment by dosumis** [comment]
Hi Val,

'mitotic sister chromatid biorientation' (or perhaps more strictly, its parent class "attachment of spindle microtubules to kinetochore") has to happen before the checkpoint is passed. AFAIK, we don't have a relation appropriate to record that beyond the rather weak timing relations (preceded_by etc).

> "Thus, although Mad2 and Mad3 are required solely for the SAC, Mph1, Bub1, Bub3 and Mad1 might have additional mitotic roles in chromosome bi- orientation beyond the SAC." PMID:26256832

> The SAC inhibits anaphase until all chromosomes have biorientated so it must be a part of the biorientation process?

Don't think having components in common is enough reason to link the processes.  Or am I missing some important detail?

Cheers,
David

**Comment by ValWood** [comment]
When the checkpoint pathway is satisfied it is turned off. But during the period when the chromosomes are not aligned it is turned on. In this respect, although it is negatively regulating the mataphase/anaphase transition via the APC until satisfied,  it must also somehow be part of biorientation, because it is required to signal  when spindle attachment is correctly completed (via aurora kinase I think?). 

I'll continue to think about it and update the ticket once I have done a few more of the papers...I can also check with experts.

**Comment by ValWood** [comment]
I thought about this. You are right. The checkpoint is active during attachment but just sensing correct attachment. Closing this one....
