### ISSUE TITLE
incorrect parentage "sister chromatid biorientation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12243]
"mitotic sister chromatid biorientation"
should be a descendant of 

mitotic GO:0007080 mitotic metaphase plate congression

(currently  this is only a child of metaphase plate congression)

**Comment by dosumis** [comment]
By what relation?

**Comment by ValWood** [comment]
sorry part_of
same as 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0031134#term=ancchart&chartTab=settings
just needs moving down

**Comment by dosumis** [comment]
Doesn't obviously follow from definition.  Should probably extend the definition of congression to make it clear that one encompasses the other.

mitotic metaphase plate congression: "The cell cycle process in which chromosomes are aligned at the metaphase plate, a plane halfway between the poles of the mitotic spindle, during mitosis."

"mitotic sister chromatid biorientation": The cell cycle process in which mitotic sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles. 
part_of some 'mitotic metaphase plate congression'

Looks like  #12244 relevant.

**Comment by dosumis** [comment]
See #12244  for fix.
