### ISSUE TITLE
parentage spindle assembly checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12240]
Just to check, @dosumis  yesterday did you also remove

GO:0051436  and GO:01904667 as  parent of GO:0007094

These need to go too....

**Comment by dosumis** [comment]
Yep. 
![image](https://cloud.githubusercontent.com/assets/112839/12421094/61306456-beb8-11e5-9cfa-6f063c191f3f.png)

**Comment by ValWood** [comment]
Excellent. I might be able to load the graph in quickgo again tomorrow...it got too big

**Comment by mcourtot** [comment]
Hi Val - on a side note you may also be able to adjust the QuickGO limit: click "Display" on the graph and adjust "Image size limit (in megapixels)" to 20.

**Comment by ValWood** [comment]
Its beyond that limit unfortunately!

**Comment by dosumis** [comment]
> Excellent. I might be able to load the graph in quickgo again tomorrow...it got too big

Haven't committed changes yet.  Will do either today or tomorrow (once the half-baked stuff I've added for synapse proj is cleaned up).  Change should be visible by Friday.

**Comment by mcourtot** [comment]
@ValWood interesting: @tonysawfordebi and I just tried here and it went through without problem. Are you trying to visualise the ancestor graph of GO:0007904 or something else? We're interested for testing purposes.

**Comment by ValWood** [comment]
yep
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007094#term=ancchart

doesn't work for me even if I change to 20 megapixels

**Comment by tonysawfordebi** [comment]
Don't understand - works absolutely fine for me. You *sure* you're setting the limit to 20 Megapixels?
![screenshot-1](https://cloud.githubusercontent.com/assets/10084958/12422652/e9512ad0-bebf-11e5-8394-a3730a30d656.png)

**Comment by ValWood** [comment]
Durr, I needed to scroll right. I thought it was broken.....
