### ISSUE TITLE
NTR: cellular response to pulsatile (and: oscillatory) fluid shear stress

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12249]
Dear Biocurators,

I am writing to request a new GO term, which arose whilst annotating paper PMID: 21768538 (Wu et al., 2011).

It is demonstrated in Figures 3 and 4 in this paper that the type of fluid shear stress, which endothelial cells are exposed to, affects the expression of miR-92a and, consequently, its target: the transcription factor Kru¨ppel-like factor 2 (KLF2).

I was able to capture the data presented in Figure 3 using term GO:0071499: ‘cellular response to laminar fluid shear stress’.

I order to capture the information from Figure 4, I wish to request two sibling terms:
1)	‘cellular response to pulsatile fluid shear stress’
2)	‘cellular response to oscillatory fluid shear stress’

Like their existing sibling, these terms would be is_a child terms to two parents:
GO:0071498: ‘cellular response to fluid shear stress’; and
GO:0034616: ‘response to laminar fluid shear stress’.

DbxREFs: GOC:BHF, GOC:BHF_miRNA, GOC:bc

I will look forward to hearing from you with regard to my request.

Thank you,
Barbara

cc: @RLovering 
cc: @rachhuntley

**Comment by paolaroncaglia** [comment]
Hi Barbara,

I will add your terms. Just a couple of notes, for future reference in case anyone questions these terms:


1) The paper abstract says “…atheroprotective laminar flow downregulated the level of miR-92a precursor to induce KLF2, and the level of this flow-induced KLF2 was reduced by miR-92a precursor. Furthermore, miR-92a level was lower in human umbilical vein endothelial cells exposed to the atheroprotective pulsatile shear flow than under atheroprone oscillatory shear flow.”

I checked the paper Methods to see how these different flows were generated: “A parallel-plate flow system was used to impose shear stress on ECs cultured in flow channels by established methods. Laminar flow, pulsatile shear flow (PS), and oscillatory shear flow (OS) were applied to ECs with shear stress of 12, 12±4, and 0±4 dyne/cm2, respectively.”

Are these assays representative of real physiological processes, and is it fine to use the same terminology? The paper Introduction confirms: “The vascular endothelium, located at the interface between the circulating blood and the vessel wall, is exposed to shear stress resulting from blood flow. The endothelium in straight parts of the artery tree is subjected to pulsatile shear stress with a significant forward direction, which is an important physiological stimulus enhancing vessel compliance and conferring antithrombotic, antiadhesive, and anti-inflammatory effects. In contrast, disturbed flow patterns at the arterial bifurcations and curvatures can cause endothelial dysfunction, which initiates atherosclerosis.”

I checked the references listed in support of the paragraph above, and this one in particular seems to confirm that ‘oscillatory’ is ok to use instead of ‘disturbed’:  
http://atvb.ahajournals.org/content/5/3/293.abstract?ijkey=566e4eff542084b0f17b57dfd3eafde36980e656&keytype2=tf_ipsecsha


2) I am a bit wary of creating new terms for
response to pulsatile fluid shear stress
response to oscillatory fluid shear stress
because they wouldn’t be needed immediately (and GO:0034616: ‘response to laminar fluid shear stress’ has no annotations), but I guess they might be useful for placement purposes if/when we add logical axioms to ‘cellular response’ terms and/or map to a stress ontology of some sorts.


I’ll hold on to adding the new terms for a day or so, in case there are any comments. 

Thanks,

Paola

**Comment by BarbaraCzub** [comment]
Hi Paola,

Thank you very much for looking into this. I agree that these terms will probably not be used too often. In fact I was slightly surprised when I found the term GO:0071499: ‘cellular response to laminar fluid shear stress.’ 
My intention was to use this term and one of the requested term in the AE field.

For example I made the following annotation re: Figure 2D and E and Figure 3A, B and C:
Entity ID: URS00003768C5_9606 (hsa-miR-92a); GO:0035195: gene silencing by miRNA; AE1: regulates_expression_ ENSEMBL: ENSG00000127528 (KLF2); linked AE2: part_of GO:0071499 cellular response to laminar fluid shear stress.
I.e. Gene silencing by hsa-miR-92a regulates expression of KLF2 and is a part of cellular response to laminar fluid shear stress.

This is a PRIV annotation atm, which is due to be checked by Rachael, but, assuming that it is correct, my intention was to make an analogous annotation based on Figure 4, which would include oscillatory stress in AE2 rather than the laminar stress. 

However, the pulsatile fluid shear stress triggers a reduction in miR-92a expression levels, which in turn results in increased levels of KLF2, and I would not be able to capture these correlations. I admit I requested this additional term just for completeness. Perhaps I am a little overenthusiastic as a newbie (!), but I felt confident to do so because the term GO:0071499: ‘cellular response to laminar fluid shear stress’ exists. In the future, when prompted by such logic, I will first aim to check how many times a term has been used.

Re: your question whether the assays are representative of real physiological processes and whether it is fine to use the same terminology: I trusted the authors on this one. However, just by looking at abstracts that I randomly searched for now, I can tell that experimental conditions, which other groups use to create the effect of oscillatory stress, are very similar (0±4 dyne/cm2 vs. 0±5 dyne/cm2), e.g.
http://circres.ahajournals.org/content/82/5/532.long
http://circres.ahajournals.org/content/82/10/1094.full
Whereas the criteria for creating the pulsatile shear stress seem somewhat less uniform and the numbers are higher in the first two papers, which I came across:
http://www.ncbi.nlm.nih.gov/pubmed/16036314 
http://hyper.ahajournals.org/content/59/6/1232.full.pdf 

Let’s see whether anyone else has any comments or suggestions regarding this, and in the meantime I will be waiting to hear from Rachael with regard to the annotations (and AEs!), which I created for this paper so far.

Thank you once more for your notes on this, Paola!
Barbara

cc: @RLovering 
cc: @rachhuntley

**Comment by BarbaraCzub** [comment]
Dear Paola,

Rachael, Ruth, David OS and I just had a discussion about these various types of shear stresses and their role in vascular biology.

The consensus, which we reached, is that perhaps new terms, which are even more specific, should be created. Specifically, I wish to request the following terms:
1)	endothelial cell response to laminar fluid shear stress
2)	endothelial cell response to pulsatile fluid shear stress
3)	endothelial cell response to oscillatory fluid shear stress

These processes are of key importance in vascular homeostasis and they are associated with differential expression of different genes affected by them as a part of the responses to specific shear stress types.

It has also been brought to my attention that within our team we are planning to annotate these processes more widely, therefore, these terms will probably be used more frequently in the future than the related terms have been used so far.

With regard to the new parent terms, which would need to be created for the requested siblings, they would be useful for grouping and term enrichment analysis.

I will look forward to hearing from you.

Thank you,
Barbara


cc: @RLovering 
cc: @rachhuntley
cc: @dosumis

**Comment by paolaroncaglia** [comment]
Hi Barbara et al,

All done. Added:

GO:0097699 endothelial cell response to fluid shear stress
GO:0097700 endothelial cell response to laminar fluid shear stress 
GO:0097701 response to pulsatile fluid shear stress
GO:0097703 cellular response to pulsatile fluid shear stress
GO:0097705 endothelial cell response to pulsatile fluid shear stress
GO:0097702 response to oscillatory fluid shear stress
GO:0097704 cellular response to oscillatory fluid shear stress
GO:0097706 endothelial cell response to oscillatory fluid shear stress

Closing now, thanks,

Paola

**Comment by dosumis** [comment]
Looking at the new terms:

+[Term]
+id: GO:0097706
+name: endothelial cell response to oscillatory fluid shear stress
+namespace: biological_process
+def: "Any response to oscillatory fluid shear stress that occurs in an endothelial cell." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:21768538]
+is_a: GO:0097699 ! endothelial cell response to fluid shear stress
+is_a: GO:0097704 ! cellular response to oscillatory fluid shear stress
+relationship: occurs_in CL:0000115 ! endothelial cell
+created_by: paola
+creation_date: 2016-01-27T14:25:34Z

[enodothelial cell](http://www.ebi.ac.uk/ols/beta/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115) is very general.  I think ideally these terms would be defined for the process occurring in vascular endothelial cells - perhaps: http://www.ebi.ac.uk/ols/beta/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000071

**Comment by paolaroncaglia** [comment]
Barbara, please see David's comment and advise.
Thanks both,
Paola

**Comment by BarbaraCzub** [comment]
Hi Paola,

I admit I must agree with David's advise. Thank you both for pointing this out.
Could I please request that the newly-created terms are amended to include the word 'vascular'?

GO:0097699 endothelial cell response to fluid shear stress --> 
GO:0097699 vascular endothelial cell response to fluid shear stress

GO:0097700 endothelial cell response to laminar fluid shear stress -->
GO:0097700 vascular endothelial cell response to laminar fluid shear stress

GO:0097705 endothelial cell response to pulsatile fluid shear stress -->
GO:0097705 vascular endothelial cell response to pulsatile fluid shear stress

GO:0097706 endothelial cell response to oscillatory fluid shear stress -->
GO:0097706 vascular endothelial cell response to oscillatory fluid shear stress

I will look forward to hearing from you.

Thank you,
Barbara

cc: @RLovering 
cc: @rachhuntley
cc: @dosumis

**Comment by dosumis** [comment]
See obophenotype/cell-ontology/issues/420 for related CL tracker request.

**Comment by BarbaraCzub** [comment]
Thank you, David, for submitting the CL tracker request.

cc: @RLovering 
cc: @rachhuntley

**Comment by paolaroncaglia** [comment]
Ok thanks. I'll change the 4 epithelial terms as suggested above, point to CL_0000071 blood vessel endothelial cell, and keep the CL name strings as (exact) synonyms.

**Comment by BarbaraCzub** [comment]
Hi Paola, thank you for taking care of this.
You mean the four 'endothelial' (rather than 'epithelial') terms? I just thought I should check so that no further amendments will be required.

**Comment by paolaroncaglia** [comment]
Yes of course. Sorry my mistake, it's been a long day!
Cheers,
Paola

**Comment by BarbaraCzub** [comment]
It has been indeed.
Thanks again!
Barbara

**Comment by paolaroncaglia** [comment]
Hi Barbara,

There is an ongoing discussion in the CL tracker, based on which I can't rule out that the term CL_0000071 blood vessel endothelial cell will stay exactly the same. Therefore, I'd rather not modify the GO terms until I'm sure what CL term they should link to (and what their name should be). I'm monitoring the CL ticket so I'll be aware of any update promptly. In the meantime, I think you have two options - 
1) annotate to the endothelial terms now, and move your annotations to the more granular new terms later (your annotations wouldn't be wrong, just not as specific as they could)
2) make a note and hold on to annotating.
I'm not sure what procedure @RLovering or @rachhuntley would advise; I'd have a slight preference for the first one.

Thanks. I'll comment again when the CL issue is solved.

Paola

**Comment by BarbaraCzub** [comment]
Hi Paola,
Thank you for the update. 
@rachhuntley and I decided to hold on for the moment.
I hope the CL resolution will be reached soon.
Thanks again,
Barbara

@RLovering

**Comment by BarbaraCzub** [comment]
Hi Paola,

I hope you are well. I have been wondering whether the editors may have made any changes re: cell ontology term 'vascular endothelial cell'? ( obophenotype/cell-ontology#420 )

This is a term, which would be linked to an additional NTR re: paper PMID:23897866. #12276 

I will look forward to hearing from you.

Thank you,
Barbara

cc: @RLovering 
cc: @rachhuntley

**Comment by paolaroncaglia** [comment]
Hi Barbara,

As far as I can tell, no update was made in the Cell Ontology re. vascular endothelial cell. 
I commented on the CL ticket to ask if there's any news.
As I mentioned, if you wish to annotate sooner rather than (wait for updates) later, you could annotate to the existing endothelial terms now, and then move your annotations to the more granular new terms when they become available after the CL update (your annotations wouldn't be wrong, just not as specific as they could). Let me know if I may help in any way.

Thanks,

Paola

**Comment by BarbaraCzub** [comment]
Hi Paola,

Thank you for the update. I'll discuss this with Ruth and Rachael again, and we'll take it from there.

Thanks,
Barbara

@rachhuntley 
@RLovering

**Comment by dosumis** [comment]
Wondering whether we need to wait for a CL edit here.  I'd use CL:'blood vessel endothelial cell'.  If this is merged at some point, we should get a warning from Jenkins.  I don't think you need to track the CL term name precisely in the new GO term name.  Better to go with community usage (vascular endothelial cell) and have 'blood vessel endothelial cell' be part of a synonym.

**Comment by paolaroncaglia** [comment]
OK, done. Here are the revised stanzas:

[Term]
id: GO:0097699
name: vascular endothelial cell response to fluid shear stress
namespace: biological_process
def: "Any response to fluid shear stress in a vascular endothelial cell." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:21768538]
synonym: "blood vessel endothelial cell response to fluid shear stress" EXACT []
is_a: GO:0071498 ! cellular response to fluid shear stress
relationship: occurs_in CL:0000071 ! blood vessel endothelial cell

[Term]
id: GO:0097700
name: vascular endothelial cell response to laminar fluid shear stress
namespace: biological_process
def: "Any response to laminar fluid shear stress in a vascular endothelial cell." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:21768538]
synonym: "blood vessel endothelial cell response to laminar fluid shear stress" EXACT []
is_a: GO:0071499 ! cellular response to laminar fluid shear stress
is_a: GO:0097699 ! vascular endothelial cell response to fluid shear stress
relationship: occurs_in CL:0000071 ! blood vessel endothelial cell

[Term]
id: GO:0097705
name: vascular endothelial cell response to pulsatile fluid shear stress
namespace: biological_process
def: "Any response to pulsatile fluid shear stress that occurs in a vascular endothelial cell." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:21768538]
synonym: "blood vessel endothelial cell response to pulsatile fluid shear stress" EXACT []
is_a: GO:0097699 ! vascular endothelial cell response to fluid shear stress
is_a: GO:0097703 ! cellular response to pulsatile fluid shear stress
relationship: occurs_in CL:0000071 ! blood vessel endothelial cell
created_by: paola
creation_date: 2016-01-27T14:22:44Z

[Term]
id: GO:0097706
name: vascular endothelial cell response to oscillatory fluid shear stress
namespace: biological_process
def: "Any response to oscillatory fluid shear stress that occurs in a vascular endothelial cell." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:21768538]
synonym: "blood vessel endothelial cell response to oscillatory fluid shear stress" EXACT []
is_a: GO:0097699 ! vascular endothelial cell response to fluid shear stress
is_a: GO:0097704 ! cellular response to oscillatory fluid shear stress
relationship: occurs_in CL:0000071 ! blood vessel endothelial cell

Closing now, thanks, Paola

**Comment by BarbaraCzub** [comment]
Thank you, Paola, for revising these terms! 
And thank you, David, for pointing out that there is no need to wait for a consensus re: the CL term.

Thanks a lot,
Barbara
