### ISSUE TITLE
another parentage to remove related to metaphase/anaphase transition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12246]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030071#term=ancchart

GO:0032434 regulation of proteasomal ubiquitin-dependent protein catabolic process
 is_a
GO:0030071 regulation of mitotic metaphase/anaphase transition
also looks a bit odd.

More accurately the  ubiquitin mediated part is a part_of the regulation pathway.
Can this one be removed too?
(My fault!)

**Comment by dosumis** [comment]
Have removed the two axioms causing the problem (one on the regulates, the other on thing being regulated) as well as some inference that resulted from them.  

Wondering if there's a way to search/query to find if we have any more of these...
