### ISSUE TITLE
MP proteasome localization to nuclear periphery

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12245]
[Term]
id: GO:1990920
name: proteasome localization to nuclear periphery
is_a: GO:0031144 ! proteasome localization

Please add is_a: GO:1990139 ! protein localization to nuclear periphery,

**Comment by dosumis** [comment]
Added an equivalent class def.  Classification now inferred: 

![image](https://cloud.githubusercontent.com/assets/112839/12449201/82dd7592-bf73-11e5-9211-ddb2f98c6d59.png)
