### ISSUE TITLE
parentage: GO:0039702 viral budding via host ESCRT complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12254]
Should GO:0039702 viral budding via host ESCRT complex have GO:0046761 viral budding from plasma membrane as an is_a parent?

PMID:24878737

Birgit

**Comment by paolaroncaglia** [comment]
Hi Birgit,

As far as I can see from a quick read of the full paper, only the ESCRT-III complex is shown to mediate budding from plasma membrane. If that's the case then I'd be reluctant to create the link that ALL instances of viral budding mediated by (any) EXCRT complex happen via plasma membrane. Let's see if Becky or David know more about this viral process... @rebeccafoulger , @dosumis 

Thanks,
Paola

**Comment by bmeldal** [comment]
Ah, PMID:25710462 shows that Tsg101, an ESCRT-I member, and ALIX, an accessory protein, are also involved in the recruitment of ESCRT-III to the budding site. Even if ESCRT-III is the driving ESCRT for virion budding, would it be wrong to say that virion budding by ESCRT complex is virion budding from the plasma membrane? Viruses do bud from the membrane, esp when they are aided by ESCRT.

Of course, I might have missed something fundamental...

**Comment by paolaroncaglia** [comment]
Yes they do bud from the membrane, you didn't miss anything ;-) 
But ESCRT is in the endosome, so I was wondering if it can be ruled out that it (i.e. any of its sub-complexes) doesn't aid budding from other membranes than the plasma one.

**Comment by bmeldal** [comment]
Ah, ESCRTs are tricky. The classic idea is that they are involved in the vacuolar fusion processes. There are, of course, 4 different, known (!) ESCRT complexes, all shown to be involved in processes from endosome formation to fusion with lysosomes... ESCRT-III (my current target) appears to be effective in the final steps aiding actual membrane fission but I still haven't found a paper that actually shows the process, at least not in mammalian cells (there is more out there for yeast which is commonly referenced!). Now we have evidence for their involvement in MANY more fusion processes. 

Part of current (working) def for ESCRT-III:
"ESCRT-III is involved in multiple membrane fission processes: a) the final step of cell organelle fusion processes such as the biogenesis of intraluminal vesicles (ILV) in multivesicular bodies (MVB, a type of late endosomes), fusion of autophagosomes with MVB or lysosomes and amphisomes or MVB with lysosomes, thereby playing a crucial role in processes like autophagy and downregulation of cell-surface receptors, b) polarity, c) migration, d) miRNA activity, e) mRNA transport, f) repair of plasma membrane wounds, g) the final scission of cytokineses, h) nuclear envelope sealing by annular fusion and i) budding of virions (esp. HIV-1) from the plasma membrane."

The parentage of the ESCRT complexes may need to be reviewed as well in light of all this new evidence! And, the 4 types aren't subcomplexes, they have entirely different memberships.

This is, in fact a curation request from @Pauldenny. Paul, you may want to intercept here? Although, I know you where only looking at the autophagy-related processes.

I wonder if we should wait with restructuring the GO until I have finished the complex curation, then I can share everything I have and we go from there? We can give you guest access (read-only) to the editor so you could see the curation before it goes public.

**Comment by paolaroncaglia** [comment]
Then yes, worth waiting until you have a complete picture rather than doing it bit by bit.
If your curation highlights that as far as viruses are concerned, ESCRT complexes always aid budding by plasma membrane, then adding the is_a link at the start of this thread would presumably cause no TPVs.

**Comment by bmeldal** [comment]
What are TPVs?

**Comment by paolaroncaglia** [comment]
Ah, that's pure GO jargon! True path violations. When the is_a link does not always hold true. E.g. in case ESCRT aids virus budding from ER membrane, or Golgi membrane, anything other than plasma membrane.

**Comment by Pauldenny** [comment]
I have only been looking at role of these complexes in autophagy, so cannot add anything to this thread - however, thanks Birgit for drawing to my attention!

**Comment by paolaroncaglia** [comment]
@bmeldal , I'll label this ticket as 'pending' and you can update it when you have finished the complex curation. Thanks!

**Comment by paolaroncaglia** [comment]
Hi @bmeldal ,
Just wondering if there's any update for this ticket? No hurry at all for me, I'm just going through my pending tickets. Or let me know if you think we may close this.
Thanks,
Paola

**Comment by bmeldal** [comment]
Ah, yes, they are released, but all of EBI except for webmail is currently down, so I can't link to the finished products! (working from home today) Hopefully I'll have an update for you tomorrow!

I only did ESCRT-III and -IV (Vps4-Vta1 complex). They were complicated enough and there was no request for -0, -I or -II so I didn't do the (yet).

**Comment by bmeldal** [comment]
Hi Paola,

Looks like I haven't found any new info about the viral budding process. ESCRTs play a role in many processes related to cellular vesicle fission and budding. I'm not aware that viruses bud from intracellular vesicles so I think the original request in this ticket is fine. This is the review on virus budding I used: PMID:24034610, and this is the expt paper: PMID:24878737 (ESCRT-III) & PMID:16193069 (VSP4).

Here are the created complexes:
ESCRT-III:
http://www.ebi.ac.uk/intact/complex/details/EBI-11509704
ESCRT-IV/VSP complex:
http://www.ebi.ac.uk/intact/complex/details/EBI-11565638

Looking at the ontology of the ESCRTs, they are currently all part_of endosome membrane, but that doesn't always hold true if you read through the defs. Will it have to be removed?

Sandra curated all ESCRTs in yeast before, they are no so richly annotated with GO terms but it gives you a flavour of their function. Search for 'escrt' in the CP and you get all complexes mentioned above!

I leave it up to you to decide which changes are needed. I only realised that I didn't annotate ESCRT-III with the actual ESCRT GO term! And VSP4 complex doesn't seem to exists so I guess it needs creating:

GO:NEW VSP4 complex
Def: A protein complex that has AAA-ATPase activity and is probably the main energy-providing system for the membrane deformation and abscission function of the ESCRT machinery. Required for the dissociation and recycling of ESCRT-III complex subunits from vesicle and plasma membranes as well as the midbody during the final stages of cytokinesis where it causes constriction of the ESCRT-III polymer and fission of the associated membrane neck.
Refs: PMID:26775243, PMID:24456136, PMID:21925211 (reviews, I didn't find an actual experimental paper that shows the physical interaction. There is plenty of physical and functional evidence in yeast though)
Synonym: ESCRT-IV [exact]
Synonym: VSP4A/B complex [exact]
Synonym: VSP4A-VSP4B complex [exact]
Synonym: Vacuolar protein sorting-associated complex [exact]
capable_of GO:0042623 ATPase activity, coupled
capable_of GO:0005524 ATP binding
dbxref: IntAct:EBI-11565638
GOC ref: bhm

I'm not sure you want to add all the BPs, you can just copy them from
http://www.ebi.ac.uk/intact/complex/details/EBI-11565638

I'm sure I've missed something, but this is a start!

Birgit

**Comment by paolaroncaglia** [comment]
@bmeldal ,
Many thanks. I'm on leave until August 23rd, so I'll follow up after that date.

**Comment by paolaroncaglia** [comment]
Hi @bmeldal,

I’m not an expert on viruses, so I’d rather not take initiatives on making changes on existing viral budding terms (they were part of the recent ViralZone work, so I’ll assume that any glaring issue would have been notified). Similarly for the link between ‘ESCRT complex’ and ‘endosomal part’ (‘ESCRT complex’ has the ViralZone dbxref).

As for your request for GO:NEW VSP4 complex, I guess that would be VPS4 instead… we have this one:

[Term]
id: GO:1990621
name: Vps4-Vta1 complex
namespace: cellular_component
def: "A protein complex involved in ESCRT-mediated intralumenal vesicle formation. The complex catalyzes disassembly of the ESCRT-III filament around the neck of the budding vesicle in an ATP-driven reaction, resulting in membrane scission and recycling of the ESCRT-III components back to the cytosol. In yeast, it is formed by the AAA ATPase Vps4 and its cofactor Vta1." [GOC:ha, PMID:20653365, PMID:20696398, PMID:25164817]
synonym: "Vps4 complex" BROAD []
synonym: "Vta1-Vps4 complex" EXACT []
is_a: GO:0043234 ! protein complex
relationship: capable_of_part_of GO:0070676 ! intralumenal vesicle formation
relationship: part_of GO:0010008 ! endosome membrane

The definition seems to fit with your suggested one. Could you and @hattrill (who requested ‘Vps4-Vta1 complex’) please confirm if it would be biologically correct to edit/generalize the existing term as follows:

[Term]
id: GO:1990621
name: Vps4-Vta1 complex => ESCRT IV complex [for consistency with existing children of ‘ESCRT complex’]
namespace: cellular_component
def: "A protein complex involved in ESCRT-mediated intralumenal vesicle formation. The complex catalyzes disassembly of the ESCRT III filament around the neck of the budding vesicle in an ATP-driven reaction, resulting in membrane scission and recycling of the ESCRT III components back to the cytosol. In yeast, it is formed by the AAA ATPase Vps4 and its cofactor Vta1." [GOC:ha, PMID:20653365, PMID:20696398, PMID:25164817]
=> redefine as: “An ESCRT complex that has AAA-ATPase activity and is involved in ESCRT-mediated intralumenal vesicle formation. The complex catalyzes disassembly of the ESCRT III filament around the neck of the budding vesicle in an ATP-driven reaction, resulting in membrane scission and recycling of the ESCRT III components back to the cytosol. In yeast, it is formed by the AAA ATPase Vps4 and its cofactor Vta1." 
=> add dbxrefs: GOC:bhm, IntAct:EBI-11565638, PMID:26775243, PMID:24456136, PMID:21925211
synonym: "Vps4 complex" BROAD []
synonym: "Vta1-Vps4 complex" EXACT [] => NARROW
=> add synonyms: Vps4-Vta1 complex (narrow), ESCRT-IV (exact), VSP4A/B complex (? should it be VPS4A/B? and I’d say narrow), VSP4A-VSP4B (same), vacuolar protein sorting-associated complex (broad), 
is_a: GO:0043234 ! protein complex
relationship: capable_of_part_of GO:0070676 ! intralumenal vesicle formation
=> add: capable_of GO:0042623 ATPase activity, coupled; capable_of GO:0005524 ATP binding
relationship: part_of GO:0010008 ! endosome membrane

To keep the term generally applicable to different processes, I wouldn’t add links to specific BPs e.g. viral budding, autophagy etc. 

- [ ] If you and Helen agree to this proposal, I’ll edit GO:1990621 as above. Thanks.

**Comment by hattrill** [comment]
Changes fine with me.  Thanks.

**Comment by paolaroncaglia** [comment]
Done.

**Comment by bmeldal** [comment]
Update hasn't reached QuickGO. Systemic error???

**Comment by paolaroncaglia** [comment]
Hi @bmeldal ,
The update is in AmiGO though. So it's in the ontology. If you need it to be in QuickGO urgently for any reason, please check with Tony Sawford. Otherwise, please wait a couple of days and try again.

**Comment by bmeldal** [comment]
Just concerned how long it takes to come through. DOS made some changes on another ticket 11 days ago and they haven't come through in QuickGO either. I made a comment on that ticket, too.

**Comment by paolaroncaglia** [comment]
@bmeldal then perhaps it'd be good if you could email Tony...

**Comment by bmeldal** [comment]
emailed Tony.
