### ISSUE TITLE
Death, cell death, programmed cell death

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12251]
(Depressing subject, I know.)
I just realised that one apoptosis ticket didn’t make the transition from SF to GH.(*) Most edits were done but some still need wrapping up; refer to old SF tickets for (long) discussion and details:

https://sourceforge.net/p/geneontology/ontology-requests/10098/

(*) Possibly due to combination of status=open-later and running for more than 1 page, no idea - all my other old SF tickets with status different from ‘open’ did make the transition, and I checked a few tickets with different owners and they were ok.

**Comment by paolaroncaglia** [comment]
Looking at Gillian’s and Chris’ comments again in the old SF ticket above, the following seems a good solution (and easier on annotations and ontology editing too):

- reinstate the part_of links between 
‘larval midgut cell programmed cell death’ and ‘larval midgut histolysis’
‘salivary gland cell autophagic cell death’ and ’salivary gland histolysis’

- place ‘larval midgut histolysis’ and ’salivary gland histolysis’ under (is_a) ‘anatomical structure regression’

- add exact synonyms ‘larval midgut regression’ and ’salivary gland regression’

- delete links between ‘histolysis’ and ‘larval midgut histolysis’/’salivary gland histolysis’

- take care of ‘histolysis’: it only has 3 direct annotations, all FlyBase - look at them and have them moved where appropriate, then propose obsoletion of ‘histolysis’, ‘regulation of histolysis’ and ‘negative regulation of histolysis’ (the reg. terms have no annotations)

- add ‘histolysis’ and 'tissue death' as RELATED synonyms of ‘anatomical structure regression’

- obsolete ‘tissue death’ and ‘death’!! (no direct annotations)

**Comment by paolaroncaglia** [comment]
Done all of the above except for:

- take care of ‘histolysis’: it only has 3 direct annotations, all FlyBase - look at them and have them moved where appropriate, then propose obsoletion of ‘histolysis’, ‘regulation of histolysis’ and ‘negative regulation of histolysis’ (the reg. terms have no annotations)

- obsolete ‘tissue death’ and ‘death’ (no direct annotations)

**Comment by paolaroncaglia** [comment]
Emailed Helen Attrill at FlyBase about annotations to 'histolysis'.

**Comment by paolaroncaglia** [comment]
Sent obsoletion email. Proposed deadline: March 18 2016.

**Comment by paolaroncaglia** [comment]
Obsoleted:

GO:0007559 histolysis
GO:0010702 regulation of histolysis
GO:0010703 negative regulation of histolysis
GO:0016271 tissue death
GO:0016265 death

**Comment by hdrabkin** [comment]
I just noticed that MGI does actually have direct annotation to GO:0016265 death. These are old (2008) and made by same curator consistently; I have notified to see if they can change their mind!

**Comment by paolaroncaglia** [comment]
Thanks Harold.
We need to clarify why I didn't see them in QuickGO...
