### ISSUE TITLE
membrane tubulation synonym query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12258]
Membrane tubulation has the broad synonym "vesicle scission" but I can't figure out why. If anything I would say these were 'sibling' terms

**Comment by paolaroncaglia** [comment]
Quick notes for self:
- synonym added in 2012; couldn't find any record of such request in SourceForge; may want to look at PMIDs associated with term
- whatever the decision, remember that 'regulation of membrane tubulation' also has the broad synonym 'regulation of vesicle scission', so edit for consistency if needed

**Comment by paolaroncaglia** [comment]
Abstracts of associated PMIDs indicate that membrane tubulation is upstream of vesicle formation (as expected). @ValWood , I'll change the synonym scope from broad to related, for both tubulation and regulation thereof.

**Comment by bmeldal** [comment]
That is certainly true for the ESCRT-III complex activity!

**Comment by paolaroncaglia** [comment]
Done.
