### ISSUE TITLE
 ageing-related accumulation of "lipofuscin" - non-pathological BP? 

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12268]
PMID: 22982048 states
"Cellular aging in general is characterized by a progressive accumulation of nonfunctional cellular components due to oxidative damage and a decline in turnover rates..." and "...abnormal, damaged proteins usually develop aberrant intermolecular interactions resulting in the formation of aggregates. These aggregates can be further oxidized and cross-linked resulting in undegradable **lipofuscin** [24]. This process is **not considered to be pathologic**..."

Lipofuscin has been described in PMID:12208347 as "a hallmark of aging" and as "a chemically and morphologically poly- morphous waste material...".

Should we have a term for the BP of [cellular]? ageing-related accumulation of lipofuscin?

GOC:pad

**Comment by ValWood** [comment]
Even though this is described as not pathological it doesn't sound like a "process", (unless the aggregation happens via a process as a way to deal with the toxicity). 

I would only add the term if you have a pathway (i.e gene products to annotate) that actively makes the aggregates and they don't just happen as a symptom of damage....

**Comment by Pauldenny** [comment]
Thanks Val - thinking more about this, because there is no obvious pathway, I'll drop this idea.
