### ISSUE TITLE
NTR - autophagy-initiation complex?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12261]
Review PMID: 26754330 (January 2016) describes: 
“The Saccharomyces cerevisiae autophagy-initiation complex, Atg1 kinase complex, consists of Atg1, Atg13, Atg17, Atg29, and Atg31, while the corresponding complex in most other eukaryotes, including mammals, is composed of ULK1 (or ULK2), Atg13, FIP200 (also known as RB1CC1), and Atg101”

There is an existing, related GO CC protein complex called:
GO:1990316	ATG1/ULK1 kinase complex
A protein complex consisting of ATG1/ULK1 and ATG13 along with other proteins that regulate its function (e.g. ATG17 in yeast or RB1CC1(FIP200) in mammals). This complex has serine/threonine protein kinase activity and is involved in autophagosome formation.

I think that we need a new CC term called, perhaps, autophagy-initiation complex. 

This complex occupies a key controlling step in autophagy - at least based on this review - but is an oddity because one of the subunits appears to not be conserved between e.g. fission and budding yeast.  ATG101 is found in S. pombe and mammals and many other taxons, but is absent from S. cerevisiae. It seems that it's functions are replaced by a two-protein complex, consisting of (apparently unrelated to Atg101 at the primary sequence level) Atg29 and Atg31.

Or, if this a step too far, perhaps the existing   GO:1990316	ATG1/ULK1 kinase complex
should either be renamed to be the "autophagy-initiation complex" or at least have this name as a synonym? I'd be interested in Marc Feuermann's opinion...
What do you think, David, Marc? @ukemi
@marcfeuermann 
@bmeldal 
GOC:pad
GOC:PARL

**Comment by bmeldal** [comment]
Thanks, Paul.

There were multiples of the ATG1/ULK1 complexes which were combined to provide the current term that allows wiggle room wrt the precise subunits involved in different species. Edits were made last year in June and Oct.

We have EBI-2352849 ATG1 kinase complex for Saccharomyces cerevisiae, composed of ATG1 and ATG13 in the complex portal.

Birgit

**Comment by Pauldenny** [comment]
In teleconference call (Feb 17th) [https://docs.google.com/document/d/1FFL-1aEcYyvpk1Rxje2DQmGTyKV6xxVKrv2u2A9LoDo/edit#](url) Marc Feuermann @marcfeuermann
suggested adjusting definition of GO term to allow for the additional proteins in some versions of complex e.g. ATG101 in some organisms, but Atg29 and Atg31 in budding yeast.

**Comment by ukemi** [comment]
Hi Paul,
I think the definition is adequate enough to give wiggle room for the specific components. I have added the synonym.
-D
