### ISSUE TITLE
MP possible GO:0009277 fungal-type cell wall

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12266]
Should this have the parent "external side of plasma membrane"?
external side of plasma membrane; GOid=GO:0009897
?

**Comment by mah11** [comment]
No, because GO:0009897 refers only to the actual outer leaflet of the plasma membrane and proteins embedded in or  attached to it. The cell wall is separated from the membrane by the periplasmic space, and is thus "beyond" the membrane, not part of the membrane.

**Comment by ValWood** [comment]
Okay doke, I was thinking that the cell wall was "on the external side of the plasma membrane" doh
closing
