### ISSUE TITLE
missing is_a to nucleocytoplasmic transporter activity?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12265]
shouldn't  
GO:0061608 nuclear import signal receptor activity

have the parent
 GO:0005487 nucleocytoplasmic transporter activity
?

Thanks!

**Comment by mcourtot** [comment]
Sounds right to me. Presumably same for GO:0005049 nuclear export signal receptor activity?

**Comment by mcourtot** [comment]
Done. 
Note: @dosumis mentioned it'd be useful to replace 'results in transport from to or in nucleus' (and same for cytoplasm) with 'results in transport across some nuclear envelope) on the term 'nucleocytoplasmic transport'. This has been done as well.

**Comment by ValWood** [comment]
Please make sure that when this is done it doesn't result in all of the nucleocytoplasmic transporters being annotated to transmembrane transport (again, again) .
Thanks!

Val

**Comment by mcourtot** [comment]
Thanks for the warning Val. We saw the note on the parent class, and @dosumis may have mentioned  similar issues in the past ;)
As per attached all looks ok, but please let me know if you see something wrong.

![screen shot 2016-02-15 at 13 48 17](https://cloud.githubusercontent.com/assets/2214135/13050395/053d9e28-d3eb-11e5-9964-7b87f4623448.png)

**Comment by ValWood** [comment]
I can only see the transport parent , I'm sure it'll be OK if you know about it...it happens all the time...
