### ISSUE TITLE
TPV nuclear pore nuclear basket

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12269]
Has is_a "membrane protein complex".
I don't think that is correct is it?

**Comment by mcourtot** [comment]
Based on the definition, nuclear pore nuclear basket is part of the nuclear pore complex, which is itself a protein complex that crosses the nuclear membrane (see https://en.wikipedia.org/wiki/Nuclear_pore), so I would think that the is_a assertion is correct.

**Comment by ValWood** [comment]
Ah OK, but nuclear pore doesn't have "membrane protein complex" it has "membrane bounded organelle"?

**Comment by mcourtot** [comment]
Checking again, you were right. The NPC does not actually cross the membrane, but instead crosses the envelope. The figure at https://en.wikipedia.org/wiki/Nuclear_pore#/media/File:NuclearPore_crop.png shows that the membrane actually folds on each side of the NPC, which never crosses it.
I removed the wrong axioms for the subpart of the NPC. Thanks for the report!
