### ISSUE TITLE
question about immune response supression terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12260]
Yep, out of my depth here.
I am annotating a few pathogen-host interaction papers  to test some data types they may need to annotate in Canto.
As part of this I'm making some (tentative) GO annotation suggestions.

I was looking for a term to capture the supression of the host defence resonse by the pathogen
This looked correct:

 GO:0052261 suppression of defense response of other organism involved in symbiotic interaction
Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of the defense response of a second organism, where the two organisms are in a symbiotic interaction.

Then I saw the descendent
GO:0052037 negative regulation by symbiont of host defense response
Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of the defense response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

How are these not the same?
Isn't suppression equivalent to negative regulation?

GO:0052037 has additional parents, one of which is

GO:0044414 suppression of host defenses
Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of host defense(s) by active mechanisms that normally result in the shutting down of a host pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction.

Which also sounds the same?

**Comment by mah11** [comment]
The distinction is that GO:0052261 does not say which organism is suppressing the other's defense response, whereas GO:0052037 and GO:0044414 specify that it's the response in the host (i.e. the bigger organism) that is regulated. GO:0052261 doesn't exclude the host regulating a symbiont's defense response. No, I have no idea whether that actually happens in real life. Maybe it does, since the people who worked on this part of the ontology (I wasn't one of them) included it?

GO:0044414 allows for host defenses other than the one(s) called "defense response" ... again, I don't know what would fit that description, maybe something that the host always does anyway (and that therefore isn't a "response") that helps defend against Bad Stuff?

**Comment by ValWood** [comment]
I was also going to ask why these terms don't have
"interaction with host" in their ancestry.

**Comment by mah11** [comment]
GO:0044414 (and therefore also GO:0052037) does have a path to "interaction with host". GO:0052261 doesn't because it's not specific for interactions with hosts (it can also cover something that the host does).

**Comment by ValWood** [comment]
It was help if the language was the same (i.e. negative regulation vs suppression)

I wanted to describe a pathogen gene product which can suppress the immune response of the host plant (I imagined this would be quite common?) but the terms are unclear...

Is defense response= immune response

I think this is the correct term now
GO:0052309 negative regulation by organism of innate immune response in other organism involved in symbiotic interaction

Should this have "interaction with host" in its ancestry?

**Comment by mah11** [comment]
> It [would] help if the language was the same

yup

> Is defense response= immune response?

I think an immune response is a subtype of defense response, but I'm no expert.

> Should GO:0052309 have "interaction with host" in its ancestry?

The name and definition say no -- like GO:0052261, it's not restricted to something the symbiont does to a host process; it can also cover the vice-versa situation. If you're sure "innate immune response" is applicable, and you want something specific for the symbiont regulating the host response, try GO:0052170.

**Comment by ValWood** [comment]
Re:
GO:0044414 (and therefore also GO:0052037) does have a path to "interaction with host". GO:0052261 doesn't because it's not specific for interactions with hosts (it can also cover something that the host does).

I don't get why that isn't a pathogen host interaction?
and I don't get why GO:0052309  isn't either ...

**Comment by mah11** [comment]
"Interaction with host" isn't as broad as "interaction between organisms, one of which is a host to the other". GO defines "interaction with host" as something happening in the symbiont. You can't interact with the host if you *are* the host.

**Comment by ValWood** [comment]
I have another question.
If you are annotating a physical interaction between a pathogen protein, and a host protein, do you just use the protein binding term, put the host protein in the with field and both taxons in column 13 (taxon field)?

**Comment by mah11** [comment]
GO will have to tackle that question. For a BioGRID interaction annotation it's easy to see where both taxon IDs go, but I don't know how GO makes the distinction.

**Comment by ValWood** [comment]
OK, for the term I am getting closer
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0052034

The term name says
negative regulation by symbiont of microbe-associated molecular pattern-induced host innate immune response
which is *exactly what I am looking for*

However, the def  is confusing: (and wrong)
Any process that involves recognition of a microbe-associated molecular pattern, and by which an organism tops, prevents, or reduces the frequency, rate or extent of the innate immune response of the host organism; the innate immune response is the host's first line of defense against infection. The host is defined as the larger of the organisms involved in a symbiotic interaction.

(which could account for why it hasn't been used?)

How about
Any process by which a symbiont  stops, prevents, or reduces the frequency, rate or extent of the microbe-associated molecular pattern-induced host innate immune response  of the host organism; 

phew!

**Comment by ValWood** [comment]
"Interaction with host" isn't as broad as "interaction between organisms, one of which is a host to the other". GO defines "interaction with host" as something happening in the symbiont. You can't interact with the host if you are the host.

Thanks, got it!

**Comment by ValWood** [comment]
Actually I don't think its the correct term at all. These things aren't negatively regulating the immune response. They are just avoiding detection and not illiciting a response....

**Comment by paolaroncaglia** [comment]
@dosumis 
Assigning to David OS who's inherited the multiorganism topic from Jane. David, could you please comment on the current plans re. annotation, see Midori's last comment (can't remember if we have any documentation on this that you could share? I recall some slides), and on the term names/defs. Happy to do any edit, feel free to assign back to me when this is clarified. 

Thanks,

Paola

**Comment by ValWood** [comment]
We can close this, its basically a series of questions.

**Comment by pgaudet** [comment]
I'd like the input of Michelle Giglio on this. My inclination would be to remove all general terms (“in other organism”), and only kee the actions done by the symbiont. The host response is the immune response process. 

Thanks, Pascale

**Comment by pgaudet** [comment]
This is essentially done (removing all general terms (“in other organism”)).
