### ISSUE TITLE
GO:0044796 DNA polymerase processivity factor complex?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12270]
GO:0044796 DNA polymerase processivity factor complex
A protein complex which is capable of increasing the processivity of nucleotide polymerization by DNA polymerase as a part of DNA replication.

This is an odd complex term. Its a grouping term, but its only grouping  complexes based on the fact that these are doing similar processes (not even that similar because PCNA does lots of things). Seems  bit arbitrary?

**Comment by bmeldal** [comment]
Hi Val, 

Actually, it's just the complex that is capable of GO:0030337 DNA polymerase processivity factor activity. 
The complex term was requested by me for the beta clamp of the E.coli replication machinery but the MF is much older.

See:
http://www.ebi.ac.uk/intact/complex/details/EBI-6468862

If you search the CP for the GO:0044796 it will also bring up all of our PCNA complexes.

Birgit

**Comment by ValWood** [comment]
Ah ok
