### ISSUE TITLE
GO:0004843 still has parentage problem?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12275]
I can't reopen tickets, not sure if I should just make a new one?

Following on from #12182:

Should all the changes be visible in TG?

I can see the new term GO:0036459 ubiquitinyl hydrolase activity

hwever both 
GO:0004843 and
GO:0061578 Lys63-specific deubiquitinase activity

still have the parent
GO:0008234 cysteine-type peptidase activity
Catalysis of the hydrolysis of peptide bonds in a polypeptide chain by a mechanism in which the sulfhydryl group of a cysteine residue at the active center acts as a nucleophile.

**Comment by mcourtot** [comment]
Can you clarify where you see this? You mention TG above, do you mean QuickGO?

**Comment by Antonialock** [comment]
yes, quickgo :)
see screenshot for clarification
![screen shot 2016-02-10 at 12 25 35](https://cloud.githubusercontent.com/assets/12727506/12947162/6d84112c-cff1-11e5-975b-9ff12a3e13d1.png)

**Comment by mcourtot** [comment]
The changes have been made, but the pipeline needs time to load the up-to-date version. 

QuickGO picks up the files at 2.45 am and then loads until around 1 pm. So in a few minutes the new files from yesterday should be loaded. 

*However* this change won't be in yet, as the GO release including the changes was done only this morning - this one will be picked up tonight at 2.45 am, then loaded, then by mid-afternoon you should be able to see the changes in QuickGO.

@tonysawfordebi kindly loaded today's file on our test version to check all was ok, and you'll see the new hierarchy attached (again, as it will show up tomorrow mid-afternoon on QuickGO)

Cheers,
Melanie

![go_0061578](https://cloud.githubusercontent.com/assets/2214135/12947857/347f9342-cff6-11e5-9413-72ba5b91256a.png)

**Comment by Antonialock** [comment]
Ah OK! All good then!

**Comment by mcourtot** [comment]
Great, thanks again for the report, that was an interesting discussion :)
