### ISSUE TITLE
inositol many-phosphate phosphatase terms - query or NTR

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12274]
Does GO have MF terms for the two phosphatase activities attributed to Asp1/PPIP5K in Figure 1 of PMID:26422458 (full text http://pubs.acs.org/doi/full/10.1021/acs.biochem.5b00532)?

If so, what are they (and apologies for not being able to find them - all those inositol phosphate permutations make my head spin a bit)?

If not, can new terms be added? Requested by a community curator. If you have questions, let me know and I'll try to help, but I don't know much about these activities, so I hope the paper has what you need.

Thanks,
m

**Comment by mcourtot** [comment]
Hi Midori - could the curator perhaps specify which terms they request exactly? This is a convoluted highly specialised paper, so it is probably best if they can specify which activities they want to capture.

Some potentials:
1) We seem to have a bunch of inositol 'many' phosphates as per attached; are those not suitable?

2) Looking at the paper, results & discussion section
- The phosphatase domain of Asp1371–920 has a histidine acid phosphatase signature
-  Asp1 371–920 only hydrolyzes one of the two diphosphate groups in 1,5-InsP8 (whereas DIPP1 attacks both diphosphates), and (ii) Asp1 371–920 does not hydrolyze monoester phosphate from 1,5-InsP8.
- The above data demonstrate that the phosphatase domain in Asp1 is an unusual, highly specialized member of the histidine acid phosphatase family.

Wouldn't GO:0101006, protein histidine phosphatase activity be suitable?


<img width="639" alt="screen shot 2016-02-10 at 15 47 36" src="https://cloud.githubusercontent.com/assets/2214135/12952234/b1ed1e28-d00d-11e5-98dc-398726f7eaae.png">

**Comment by mah11** [comment]
1) I don't know which, if any, of these terms may be applicable. That's why I asked for help! GO:0004446 may suffice, but I suspect our user may want something more specific. I'll enquire.

In the meantime, what we got with the request was:

name: inositol pyrophosphate 1-phosphatase activity
def: "Catalysis of the reaction: myo-inositol 1-diphosphate pentakisphosphate + H2O = myo-inositol hexakisphosphate + phosphate. Or myo-inositol 1,5-diphosphate tetrakisphosphate + H2O = myo-inositol 5-diphosphate pentakisphosphate + phosphate."

But the name looks less specific than the def(s), and I'm not sure I can reconcile the inclusion of a "tetrakisphosphate" in the suggested def, because Figure 1 shows only inositols with 5 or more phosphates. I know that I did not find any GO terms that I recognized as describing the the removal of one phosphate residue from a diphosphate that is on the 1- (or 5-) position of an inositol molecule that also has 5 monophosphate groups on the other phosphorylatable positions (or 4 monophosphates and one diphosphate).

2) The observation that Asp1 does not cleave 5-linked diphosphate means that it should be annotated to one or two "1-diphosphate phosphatase" term(s), and not to any "5-diphosphate phosphatase" terms. I don't recall seeing any data in the paper using any phosphoprotein substrates, so I don't see any reason to annotate Asp1 to GO:0101006 or any other phosphoprotein phosphatase activity terms. Also, I'm pretty sure the "histidine" in "histidine acid phosphatase" refers to a His residue that is part of the enzyme, not the substrate, and is involved in catalysis.

**Comment by mcourtot** [comment]
Thanks for the follow-up Midori.
1) I suspect I'm in the same boat as you; I'm not sure which term would be suitable. let me know what you find out, and I'll ping @ukemi in case he has any idea (now that he's back ;))
2) I was checking the InterPro classification for histidine acid phosphatase, http://www.ebi.ac.uk/interpro/entry/IPR000560 as the paper mentions the 'histidine phosphatase signature': they do indicate phosphorylation on the His residue, so per the definition 'Catalysis of the reaction: protein histidine phosphate + H2O = protein histidine + phosphate' wouldn't that mean that this is a protein histidine phosphatase activity, as at some point the phosphate will be linked to the histidine and then cleaved?
InterPro also indicates a mapping to GO:0003993, acid phosphatase activity.

**Comment by mah11** [comment]
I've had another look at the structures, and I think I've figured out where the "tetrakisphosphate" that was confusing me comes from. It's the "InsP8" molecule, which has diphosphates at two positions and monophosphates at the other four. So I'm a lot more confident now that what we need are two new MF terms for these reactions:

GO:new1
name: inositol 1-diphosphate 2,3,4,5,6-pentakisphosphate 1-diphosphatase activity
def: Catalysis of the reaction: myo-inositol 1-diphosphate 2,3,4,5,6-pentakisphosphate + H2O = myo-inositol hexakisphosphate + phosphate. [PMID:26422458]
is_a: GO:0052745
synonym: inositol 1-pyrophosphate 2,3,4,5,6-pentakisphosphate 1-pyrophosphatase activity EXACT

GO:new2
name: inositol 1,5-bisdiphosphate 2,3,4,6-tetrakisphosphate 1-diphosphatase activity
def: Catalysis of the reaction: myo-inositol 1,5-bisdiphosphate 2,3,4,6-tetrakisphosphate + H2O = myo-inositol 5-diphosphate 1,2,3,4,6-pentakisphosphate + phosphate. [PMID:26422458]
is_a: GO:0052745
synonym: inositol 1,5-bispyrophosphate 2,3,4,6-tetrakisphosphate 1-pyrophosphatase activity EXACT

(I'm less sure about the names and synonyms than the defs now - change as you see fit!)

As for the histidine phosphatase term, I don't think we usually annotate anything based on what happens with reaction intermediates. for this paper specifically, I would stick to the inositol polyphosphates they actually assayed in the experiments.

**Comment by ukemi** [comment]
Hi Melanie and Midori,

I am back now. These enzymes always make my head spin, but I think based on the request, Midori's proposal seems correct. I agree we should not include the intermediates.

-D

**Comment by mah11** [comment]
Welcome back, David! I'm glad I'm not the only one with a spinning head ...

**Comment by ValWood** [comment]
Yeah welcome back and Happy New Year ;)

**Comment by mah11** [comment]
any progress?

thx,
m

**Comment by mcourtot** [comment]
Still on the TODO list, but I'm trying to catch up this week, so should be addressed soon. Thanks for the reminder.

**Comment by mcourtot** [comment]
Committed revision 32468, thanks for the patience.

**Comment by mah11** [comment]
They've reached PomBase Canto now, and I've emailed our user. Thanks!
