### ISSUE TITLE
chromatin question

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12278]
Does it seem odd to describe "chromatin" as a "macromolecular complex"
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000785#term=ancchart

(presumably if the chromatin is DNA+ protein, then this would make the chromosome a complex?)

**Comment by dosumis** [comment]
> Does it seem odd to describe "chromatin" as a "macromolecular complex"

Yep.  Any alternative suggestions?

**Comment by ValWood** [comment]
It has is_a chromosomal_part does it need anything else? (I think cases like this were why the part terms were required?)
