### ISSUE TITLE
MP? - GO:0008772 - [isocitrate dehydrogenase (NADP+)] kinase activity

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#12273]
Hi, 

I was looking at E. coli aceK while doing PAINT for PTHR39559. It is annotated with this term: 
GO:0008772 - [isocitrate dehydrogenase (NADP+)] kinase activity

This term has an is_a relationship to "protein kinase activity" (GO:0004672), which is fine.

However, this protein is known to be bifunctional and also possess "phosphoprotein phosphatase activity" (GO:0004721), as in biologically relevant ability to both phosphorylate and de-phosphorylate its  substrate, isocitrate dehydrogenase, not just a theoretical ability to reverse the reaction.

Would it be possible to give this term both relevant MF parents? and if so, perhaps we could use the alternative name "Isocitrate dehydrogenase kinase/phosphatase" as the main name (it's currently a synonym). 

If not, perhaps we should create a second term for the phosphatase activity, that parallels the kinase activity term that is specific for isocitrate dehydrogenase kinase activity.

thanks,

-Karen

Papers listed for this protein in PAINT:
PMID:20505668
PMID:6292732
PMID:8620880
PMID:3112144
PMID:8702587

2.7.11.5
http://enzyme.expasy.org/EC/2.7.11.5

**Comment by ValWood** [comment]
Hi Karen,

For bifunctional gene products don't we just annotate the 2 separate 
activities independently?
This happens a lot, but we don't usually create compound terms. We're 
annotating activities, not gene products.

Val

On 10/02/2016 01:01, Karen R Christie wrote:
>
> Hi,
>
> I was looking at E. coli aceK while doing PAINT for PTHR39559. It is 
> annotated with this term:
> GO:0008772 - [isocitrate dehydrogenase (NADP+)] kinase activity
>
> This term has an is_a relationship to "protein kinase activity" 
> (GO:0004672), which is fine.
>
> However, this protein is known to be bifunctional and also possess 
> "phosphoprotein phosphatase activity" (GO:0004721), as in biologically 
> relevant ability to both phosphorylate and de-phosphorylate its 
> substrate, isocitrate dehydrogenase, not just a theoretical ability to 
> reverse the reaction.
>
> Would it be possible to give this term both relevant MF parents? and 
> if so, perhaps we could use the alternative name "Isocitrate 
> dehydrogenase kinase/phosphatase" as the main name (it's currently a 
> synonym).
>
> If not, perhaps we should create a second term for the phosphatase 
> activity, that parallels the kinase activity term that is specific for 
> isocitrate dehydrogenase kinase activity.
>
> thanks,
>
> -Karen
>
> Papers listed for this protein in PAINT:
> PMID:20505668
> PMID:6292732
> PMID:8620880
> PMID:3112144
> PMID:8702587
>
> 2.7.11.5
> http://enzyme.expasy.org/EC/2.7.11.5
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12273>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by krchristie** [comment]
Hi Val,

I was thinking that might be an issue. That's why my alternate suggestion was to create a parallel term for the isocitrate dehydrogenase specific phosphatase activity that is parallel to the existing term for the kinase activity. 

-Karen

**Comment by mcourtot** [comment]
Hi Karen,

Can you confirm this is the term you are requesting:

GO:NEW
name: isocitrate dehydrogenase specific phosphatase activity
def: Catalysis of the reaction: [isocitrate dehydrogenase] phosphate + H2O = [isocitrate dehydrogenase] + phosphate.
is_a: GO:0016791
synonym: isocitrate dehydrogenase kinase/phosphatase activity EXACT

**Comment by krchristie** [comment]
Hi Melanie,

I think the term name you are suggesting would be fine, unless it would be better to make the name more parallel to the existing kinase term:

GO:0008772 - [isocitrate dehydrogenase (NADP+)] kinase activity

in which case maybe it should be  "isocitrate dehydrogenase (NADP+)] phosphatase activity".

In addition to the synonym you've suggested, it would be good if it was connected to the EC number, 2.7.11.5, in the standard way.

thanks,

Karen

**Comment by mcourtot** [comment]
Created
> id: GO:0101014
> name: [isocitrate dehydrogenase (NADP+)] phosphatase activity
