### ISSUE TITLE
dopamine receptors, synaptic transmission etc

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12287]
A few dopamine receptor-related ontology queries:
1. 
   There’s currently no ontology links between:
   synaptic transmission, dopaminergic ; GO:0001963
   dopamine receptor signaling pathway ; GO:0007212

Looking at the comments of ‘dopamine secretion ; GO:0014046’, it can’t be a part_of relationship since dopamine doesn’t always act as a neurotransmitter, but I think a has_part link would hold.

---
1. 
   Given the definitions (& neurotransmitter receptor parentage of the receptor terms), the following P/F links should be added:

synaptic transmission, dopaminergic ; GO:0001963
—[partof]dopamine neurotransmitter receptor activity ; GO:0004952

synaptic transmission, cholinergic ; GO:0007271
—[partof]acetylcholine receptor activity ; GO:0015464

---
1. 
   According to the review PMID:21711983, not all dopaminergic neuron signaling goes through G-proteins (see Fig. 2 for overview). Therefore, this link needs removing, or a G-protein coupled dopamine receptor activity term created:

G-protein coupled neurotransmitter receptor activity ; GO:0099528
—[isa]dopamine neurotransmitter receptor activity ; GO:0004952

Ditto for the process term: dopamine receptor signaling pathway ; GO:0007212

---
1. I partially remember the ChEBI role discussion about dopamine etc being able to act as either a hormone or neurotransmitter, but it doesn’t seem consistent with how this is applied in the ontology. The dopamine receptor is called ‘dopamine neurotransmitter receptor activity’ but the serotonin receptor (GO:0099589) isn’t, meaning that the serotonin terms don’t fall under ‘neurotransmitter receptor activity’ or synaptic transmission. At the least, comments should be added to consider the synaptic transmission/neurotransmitter receptor terms.

---
1. Additional links to add:
   cellular response to dopamine ; GO:1903351
   —dopamine receptor signaling pathway ; GO:0007212

cellular response to serotonin ; GO:1904015
—serotonin receptor signaling pathway ; GO:0007210

Thanks!

**Comment by pgaudet** [comment]
@BarbaraCzub Do you want to take this one ?

**Comment by BarbaraCzub** [comment]
Hi @pgaudet Is this urgent? I will be happy to add the relationships that Rebecca suggested; however, I won't be able to do this sooner that in mid-June. I am not sure though what to do about the ChEBI hormone vs. neurotransmitter aspect. Perhaps this point should be discussed in its own separate ticket?
cc @RLovering

**Comment by pgaudet** [comment]
> ChEBI hormone vs. neurotransmitter aspect

@ukemi will deal with that when dealing with the CheBI roles tickets. We can close this once the relations are added. 

Thanks, Pascale
