### ISSUE TITLE
GO:0036459 thiol-dependent ubiquitinyl hydrolase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12282]
GO:0036459 thiol-dependent ubiquitinyl hydrolase activity
Catalysis of the thiol-dependent hydrolysis of an ester, thioester, amide, peptide or isopeptide bond formed by the C-terminal glycine of ubiquitin.
has exact synonym
	ubiquitin C-terminal hydrolase
which I think is fine. It is exact.

But  there is a parent
 GO:0101005 ubiquitinyl hydrolase activity
Catalysis of the hydrolysis of ubiquitin from proteins and other molecules.

and I don't know what is different about his (is there another mechanism?)

and a child
GO:0004843
thiol-dependent ubiquitin-specific protease activity
Catalysis of the thiol-dependent hydrolysis of a peptide bond formed by the C-terminal glycine of ubiquitin and another protein.

which seems identical?

Also, 
GO:0004843
thiol-dependent ubiquitin-specific protease activity
used to have this relation(deleted last week)
2016-02-10	Deleted	RELATION	is a GO:0019783 (ubiquitin-like protein-specific protease activity)

This represented the term if you knew it was a ubiquitin-like hydrolase but you did not know if it acted on ubiquitin, SUMO, or any of the other ubiquitin-like modifiers, so this parent was actually correct.

**Comment by mcourtot** [comment]
Hi Val,

As per https://github.com/geneontology/go-ontology/issues/12182

>GO:0036459 thiol-dependent ubiquitinyl hydrolase activity
Catalysis of the thiol-dependent hydrolysis of an ester, thioester, amide, peptide or isopeptide bond formed by the C-terminal glycine of ubiquitin.
has exact synonym
ubiquitin C-terminal hydrolase
which I think is fine. It is exact.

>But there is a parent
GO:0101005 ubiquitinyl hydrolase activity
Catalysis of the hydrolysis of ubiquitin from proteins and other molecules.

>and I don't know what is different about his (is there another mechanism?)

There are 2 types of ubiquitinyl activity: thiol-dependent (i.e. cysteine) and metallopeptidase - so you're right, 2 mechanisms.
I had added a comment to that effect "There are two main classes of deubiquitinating enzymes: cysteine proteases (i.e., thiol dependent) and metalloproteases." but let me know if this could be made clearer.

>Also, 
GO:0004843
thiol-dependent ubiquitin-specific protease activity
used to have this relation(deleted last week)
2016-02-10 Deleted RELATION is a GO:0019783 (ubiquitin-like protein-specific protease activity)

>This represented the term if you knew it was a ubiquitin-like hydrolase but you did not know if it acted on ubiquitin, SUMO, or any of the other ubiquitin-like modifiers, so this parent was actually correct.

I think you're right in this case as they would all be thiol-dependent, and the ubiquitin-like protein-specific protease activity is_a cysteine-type peptidase activity. I'll add the relation back.

**Comment by ValWood** [comment]
Midori mentioned:
"the difference is between GO:0036459 and GO:0004843 -- it sounds like GO:0036459 is not restricted to peptide bonds, but instead covers cleaving any bond type between the C-terminal residue of ubiquitin and something else."

So, do we need both of these? do they ever not cleave peptide bonds? (they are described as peptidases  so I can't figure that one out)

**Comment by mah11** [comment]
No, GO:0036459 doesn't have a path to peptidase activity. (Sorry, I can't help with which gene products might be annotated to it but not to GO:0004843.)

**Comment by ValWood** [comment]
I'm really confused by this. It turns out that Antonia was annotating the metallopeptidase in pombe last week.

The 2  new terms were added to represent the 'metalopeptidase' mechanism
GO:0061578 Lys63-specific deubiquitinase activity
GO:1990380	Lys48-specific deubiquitinase activity

but all of the thiol dependent are also one of these specificities ?

(this is a problem when we try to put the mechanism into the MF terms... but there appears to be a problem with the differentia here....)

**Comment by ValWood** [comment]
OK I see the difference between GO:0036459 and GO:0004843
Its just the other stuff now.

**Comment by mcourtot** [comment]
Those 2 terms pre-existed. Antonia mentioned she couldn't use them as they were children of cysteine-specific (thiol dependent) activity. We agreed after discussion at https://github.com/geneontology/go-ontology/issues/12182 to create a new, non-thiol dependent parent, which is GO:0101005 ubiquitinyl hydrolase activity

>The 2 new terms were added to represent the 'metalopeptidase' mechanism
GO:0061578 Lys63-specific deubiquitinase activity
GO:1990380 Lys48-specific deubiquitinase activity

Those should represent either of the metallopeptidase or thiol-dependent, and the definition reads 'Hydrolysis of Lys63-Linked ubiquitin unit(s) from a ubiquitinated protein.'

**Comment by Antonialock** [comment]
This is really confusing, last week, GO:0004843 was called "ubiquitin specific protease activity" and I asked to have the cysteine-type peptidase activity parentage removed? Now it looks ike the parentage has been removed but the term name has changed to INCLUDE "thiol dependent" GO:0004843 thiol-dependent ubiquitin-specific protease activity?
 see #12275

**Comment by mcourtot** [comment]
Please check resolution we had agreed upon at https://github.com/geneontology/go-ontology/issues/12182#issuecomment-176088711:

>There are 0 manual annotations directly to 'ubiquitinyl hydrolase activity ; GO:0036459'- all annotations come from InterPro and HAMAP mappings. So after a chat with Melanie, we think it makes most sense to:
1. Create a new generic ubiquitinyl hydrolase activity term.
2. Rename GO:0036459 to thiol-dependent ubiquitinyl hydrolase activity.
3. Add in an EC:GO mapping to GO:0036459 for EC:3.4.19.12 (currently the EC number is just in the definition field, so doesn't make it into mapping files).

The parentage link has been erroneously removed as mentioned above and I am about to add it again. The new generic ubiquitinyl hydrolase activity term,GO:0101005 ubiquitinyl hydrolase activity, has been created.

**Comment by ValWood** [comment]
OK, I see the problem now.

Antonia could not use the thiol-dependent term and the existing terms were moved out. 
However, many  (most, all?) 
GO:0061578 Lys63-specific deubiquitinase activity
GO:1990380 Lys48-specific deubiquitinase activity
are thiol dependent.

This solution will result in annotation inconsistency, because
GO:0061578 Lys63-specific deubiquitinase activity
and 
GO:0004843
thiol-dependent ubiquitin-specific protease activity
will both often be true.

The differentia for the 
GO:0061578 Lys63-specific deubiquitinase activity terms, if they are siblings of 
thiol-dependent ubiquitin-specific protease activity should be that they are thiol-independent

and new terms would be required for the thiol-dependent and thiol independent 
Lys63-specific deubiquitinase activity

This is difficult to maintain, these sub-activity mechanistic  details are probably really out of scope for GO  discussed with Paul Thomas @thomaspd  at the LEGO meeting.
Maybe GO should consider removing these so we don't need to go:

thiol-dependent ubiquitin-specific protease activity
-- thiol-dependent ubiquitin-specific protease  Lys63-specific deubiquitinase activity
thiol-independent ubiquitin-specific protease activity
-- thiol-independent ubiquitin-specific protease  Lys63-specific deubiquitinase activity

**Comment by ValWood** [comment]
Summary:
Maybe this could be brought up on an editors call.
Question: should we have terms to represent the same activity using a different mechanism. I'd vote no, we only need what the activity is, not how. It would be much better for annotation consistency, and easier for the editors.

**Comment by mcourtot** [comment]
I'm very confused as well. Couldn't we have 2 annotations, each representing the specific activity? E.g.,  Lys63-specific deubiquitinase activity and metallopeptidase, or Lys63-specific deubiquitinase activity and cysteine-type peptidase?

**Comment by ValWood** [comment]
Do you mean 2 terms? We could, that's suggestion one. But this is more a general question now about whether we should be trying to represent these types of sub-activity things.

**Comment by ValWood** [comment]
Ah I think you are suggesting 2 annotations. This would be bad practice- if you are trying to represent a single activity, you want to use a single term otherwise its confusing for users.

**Comment by thomaspd** [comment]
I agree with Val that there's a difference between an activity (what a gene product does) and a mechanism (how it does it).  The terms "cysteine-type peptidase" and "metallopeptidase" are distinguished by the mechanism by which catalysis is accomplished, not the activity.  The activity is the same, i.e. peptidase activity.  That said, on a practical level, I could see how cysteine-type peptidase vs. metalloprotease could potentially be useful terms for users to query a database.  If we think we want to keep them, I've proposed a sub-class under MF called "molecular mechanism" where we could potentially put these kinds of classes.

**Comment by mcourtot** [comment]
Added for discussion at http://wiki.geneontology.org/index.php/Ontology_meeting_2016-02-25

**Comment by ukemi** [comment]
Have a look at this model. 

http://noctua.berkeleybop.org/editor/graph/gomodel:56cbaef000000102

I think it represents the metallopeptidase. It would be classified correctly if we defined a metallopeptidase as a peptidase that has_part metal ion binding. 

I am not sure yet how to handle cysteine proteases in a similar manner unless we really go down the route of formally defining them mechanistically. In hindsight, I think we should have had stronger arguments about not having created the substrate-specific molecular functions in the first place. It would have been better in a LEGO world to have had 'cysteine-type peptidase activity' part of 'protein K63-linked deubiquitination' and 'metallopeptidase activity' part of 'protein K63-linked deubiquitination'  to have captured the biology.

I can add this example using this strategy to a LEGO model, but I hope it is pretty straightforward.

**Comment by ValWood** [comment]
Hi David,

I think this is confusing ;).

Here the Lys-63 specific  deubiquitinase *IS* a metallopeptidase at the 
same time. This is equivalent to making a
cyclin-dependent protein kinase term and a protein kinase term to 
describe a single activity. I think this representation  is 
overcomplicated (we only need a single activity annotation to describe a 
single activity.

Although I agree we might be better to merge many of the substrate 
specific molecular functions.

The fact that its a metallopeptidase isn't critical to describe the 
reaction. I'm not sure why we want to put this in GO, its adequately 
captured by the protein family classifications. I seem to be in a 
minority on this one. I'll probably keep going on about it until  you 
change your minds ;)


Val


On 26/02/2016 14:44, ukemi wrote:
>
> Have a look at this model.
>
> http://noctua.berkeleybop.org/editor/graph/gomodel:56cbaef000000102
>
> I think it represents the metallopeptidase. It would be classified 
> correctly if we defined a metallopeptidase as a peptidase that 
> has_part metal ion binding.
>
> I am not sure yet how to handle cysteine proteases in a similar manner 
> unless we really go down the route of formally defining them 
> mechanistically. In hindsight, I think we should have had stronger 
> arguments about not having created the substrate-specific molecular 
> functions in the first place. It would have been better in a LEGO 
> world to have had 'cysteine-type peptidase activity' part of 'protein 
> K63-linked deubiquitination' and 'metallopeptidase activity' part of 
> 'protein K63-linked deubiquitination' to have captured the biology.
>
> I can add this example using this strategy to a LEGO model, but I hope 
> it is pretty straightforward.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12282#issuecomment-189309197>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ukemi** [comment]
I've now added the second option to the right of the first in the model. I think they both work, but I think the right hand one is better. 

Val, does this make sense?

**Comment by Antonialock** [comment]
Yeah I'm with Val....I only requested thesibling term because of the parentage (to cysteine-type) of the existing term..

I think having "lys63 specific DUB activity" is equivalent to having "protein serine/threonine kinase activity" = OK

It is irrelevant however whether it uses a metallo- or cysteine-type mechanism for the DUB activity. That's like caring about whether a DNA binding transcription factor binds DNA via a leucine zipper or a zinc finger motif.

**Comment by ValWood** [comment]
On 26/02/2016 15:05, Antonialock wrote:
>
> Yeah I'm with Val....I only requested thesibling term because of the 
> parentage (to cysteine-type) of the existing term..
>
> I think having "lys63 specific DUB activity" is equivalent to having 
> "protein serine/threonine kinase activity" = OK
>
> It is irrelevant however whether it uses a metallo- or cysteine-type 
> mechanism for the DUB activity. That's like caring about whether a DNA 
> binding transcription factor binds DNA via a leucine zipper or a zinc 
> finger motif.
>
That's a good analogy.

We aren't saying the information isn't useful, but anybody who is 
interested in that detail can see it if they look at the protein family 
information. Why try to repeat all this n GO?


> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12282#issuecomment-189315700>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ValWood** [comment]
Hi David,

This looks fine in LEGO. However it would not work on the MOD gene pages 
to show what we want to show.

This is ubp4 gene page
http://www.pombase.org/spombe/result/SPBC18H10.08c

You can see *instantly* which are the targets of this particular 
ubiquitin hydrolase.

You can also *instantly* access the other 23 ubiquitin hydrolases in 
pombe (link under count column).

We would lose this specificity if we gathered everything at the 
metallopeptidase level (I don't even know how many metallopeptidases we 
have but its probably hundreds- it isn't information our users depend on 
GO for).  Our users use these terms ubiquitin specific MF terms all the 
time and they would suffer if we took them away. We have a number of 
groups actively working on these (one of the labs even curated this 
enormous dataset  of specific ubiquitin hydrolase targets).

The only problem for us is that there are 2 ways of modelling *the same 
thing* in different branches, depending how you classify the ubiquitin 
hydrolase  you could use one of two GO terms. We think there should only 
be one term.
There are 2 ways to make this happen:
i) Have a metallopeptidase version of the ubiquitinase activity (with or 
without the substrate residue specificity, we don't mind*)
ii) Take the mechanism based  classification out of GO to simplify so we 
don't need to do i)
I don't mind which, option ii) would make most sense to me because i) is 
a lot of unnecessary work for ontology developers and annotators.

* This is a separate issue

Val



On 26/02/2016 15:01, ukemi wrote:
>
> I've now added the second option to the right of the first in the 
> model. I think they both work, but I think the right hand one is better.
>
> Val, does this make sense?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12282#issuecomment-189314601>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ukemi** [comment]
Hi Val,

A substrate can be easily added to the model. That is no problem. Listing all the DUBs in one model or all the substrates in one model could be done, but is not necessary. I would think we could find a way to do this with a  with a query outside the model, similar to harvesting column 16 data.

**Comment by ValWood** [comment]
Yes but our users find "ubiquitin hydrolase" useful on the gene pages. 
Its more about access to other ubiquitin hydrolases. You would no longer 
be able to do this if you annotated to "metallopeoptidase"

**Comment by ukemi** [comment]
Got it. Then the model on the left is better.

**Comment by ValWood** [comment]
Yay!
So we aren't really bothered about the "metallopeptidase". We aren't bothered about the lys63 specific bit really either. However, we always annotate as specifically as possible and the terms are there. But thy had the thiol-dependent parent, which wasn't true for the one Antonia was annotating.

Problem is, we usually don't really know if they are thiol-dependent or metallopeptidase from the experiment. We could figure it out sometimes from the protein family, but why bother? Its not the information our users are interested in via MF.

**Comment by ukemi** [comment]
I just deleted the model on the right.

**Comment by ukemi** [comment]
What you say makes perfect sense to me. Put the information in the model the users care about.

**Comment by thomaspd** [comment]
I agree that the one on the left captures the main activity.  As I’d said in my earlier comment, if we really wanted to refer to the metalloprotease mechanism, we could do this.  In LEGO, this would have a part_of relation to the deubiquitinase activity.  I’ve modified the LEGO model to show what I mean.

**Comment by ukemi** [comment]
I was wondering who that was! I think if we wrote a logical def for metallopeptidase, we wouldn't need to do this. The zinc binding would take care of it for us. The reasoner would figure it out.

**Comment by thomaspd** [comment]
Nice to have the real-time collaborative tool!  I agree— with a logical def this would be automatic.

Paul.

**Comment by ValWood** [comment]
Re the 
GO:0061578 Lys63-specific deubiquitinase activity
GO:1990380 Lys48-specific deubiquitinase activity

I think most do both, and if this is the case, this specificity is a bit meaningless? Aren't we more interested which protein the  ubiquitin is being detached from, than which  lysine of the ubiquitin  chain ?
I am not sure but we could ask about this.

**Comment by ukemi** [comment]
I suspect we care about the nature of the linkage because if I am not mistaken, different linkages tend to be involved in different processes. I have tweaked the model again though.

**Comment by ValWood** [comment]
So if the same Ub hydrolases  both linkages maybe we  will care about the linkage for the ubiquitination in a substrate specific way?

So an annotation for this ub hydrolase
http://www.pombase.org/spombe/result/SPBC1703.12

might eventually look like
ubp9, ubiquitinyl hydrolase activity 
has_target irs1 involved in  protein K11-linked deubiquitination
has_target vtc1 involved in  protein K11-linked deubiquitination
has_target cff1 involved in  protein K48-linked deubiquitination
has_target pob1 involved in protein K63-linked deubiquitination

I would do this as a F-P link

I think we should kill 
GO:0061578 Lys63-specific deubiquitinase activity
GO:1990380 Lys48-specific deubiquitinase activity
and point them to 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071108#term=ancchart
as we have most of the terms here already

but this is a different issue to the metallopeptidase/deubiqutinase problem (see * above)

**Comment by ukemi** [comment]
Want to try to model ubp9 in LEGO? You would make the F-P links as part of your annotons. I think we would want 4 annotons here, good use of the new cloning function. If you don't model it, I will next week.
-D

**Comment by thomaspd** [comment]
Re: the tweaked model, I think it’s more informative to represent it as I had it before, with catalytic mechanism as part of the ubiquitinase activity— in other words, the catalysis of a reaction is only part of the activity (it needs to bind substrate, as one additional part of its activity).

**Comment by ValWood** [comment]
Isn't it done? (although I'm confused because I thought we agreed that the ubiquitin hydrolase term was preferable to the metallopeptidase, but the existing model has metallopeptidase).

Ubp9 is a relatively simple case, as it only has one 'activity'. We can't get any further with the target/process links at present.

We could add the targets, but I don't want to do this manually, it would be too tedious, and we would never have time to scale. I want to be able to pull in existing annotation. 

Val

**Comment by pgaudet** [comment]
Hello, 

Is this solved ? Because I see it's not closed. 

This question was brought up in at least several other issues, including this one where it was decided it should be obsoleted. 

https://sourceforge.net/p/geneontology/ontology-requests/11094/
https://github.com/geneontology/go-ontology/issues/11560
https://github.com/geneontology/go-ontology/issues/10710


EC has merged the two concepts (thiol-dependent ubiquitinyl hydrolase activity, 3.4.19.12), and EC 3.1.2.15; I suggest GO does the same. 

Thanks, 

Pascale

**Comment by mcourtot** [comment]
Hi Pascale, 
The solution that was agreed on and that I detailed above https://github.com/geneontology/go-ontology/issues/12182#issuecomment-176088711 has been implemented. 

We also discussed this at the editors call http://wiki.geneontology.org/index.php/Ontology_meeting_2016-02-25#Specificity_of_activity_terms and it was decided that doing 2 annotations wa so, but that David would also try the LEGO model.

Please see attached screenshot of current hierarchy with the classes highlighted: the Lys63- and Lys48 classes were pre-existing, I created the ubiquitinyl hydrolase activity class, and renamed GO:0036459 to thiol-dependent ubiquitinyl hydrolase activity.

![screen shot 2016-04-20 at 13 16 48](https://cloud.githubusercontent.com/assets/2214135/14674133/47346824-06fa-11e6-8c82-9966e75fe184.png)

Cheers,
Melanie
