### ISSUE TITLE
MP sister chromatid biorientation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12286]
should have  "metaphase plate congression"

(follows from recent
mitotic sister chromatid biorientation is_a  mitotic metaphase plate congression)

**Comment by dosumis** [comment]
Hi Val,

Please clarify.  Not sure what it means to have "metaphase plate congression"

Ta,
David

**Comment by ValWood** [comment]
Sorry more information ;)

mitotic sister chromatid biorientation is part of mitotic metaphase plate congression
(correctly)
therefore
sister chromatid biorientation  should be part_of mitotic metaphase plate congression
--

**Comment by dosumis** [comment]
We already have: 

'mitotic sister chromatid biorientation part of mitotic metaphase plate congression
![image](https://cloud.githubusercontent.com/assets/112839/13145342/ec7a02d2-d647-11e5-87ce-9fd6871977fd.png)

![image](https://cloud.githubusercontent.com/assets/112839/13145361/073dfefc-d648-11e5-9c15-ee48e6aefa79.png)

**Comment by ValWood** [comment]
sorry, the missing one is
 sister chromatid biorientation part_of metaphase plate congression

**Comment by dosumis** [comment]
Which we have...
https://cloud.githubusercontent.com/assets/112839/13145361/073dfefc-d648-11e5-9c15-ee48e6aefa79.png

**Comment by ValWood** [comment]
Yes sorry its exctly right!
