### ISSUE TITLE
Wrong relationship for 'protein kinase inhibitor activity ; GO:0004860' 

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12283]
This should be a quick fix!

Protein2GO was suggesting some strange inferred annotations to me, and it's because of this relationship, which needs moving up:

negative regulation of cyclin-dependent protein kinase activity ; GO:1904030
--[partof]protein kinase inhibitor activity ; GO:0004860

Should be:

negative regulation of protein kinase activity ; GO:0006469
--[partof]protein kinase inhibitor activity ; GO:0004860

Thanks!

**Comment by tberardini** [comment]
Cleaned up.  Thanks.
