### ISSUE TITLE
Query re T-cell terms located under homotypic cell-cell adhesion

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12288]
Hi

please would you look at this branch of the ontology. GO:0033077 T cell differentiation in thymus should not have the is_a parent GO:0034109	homotypic cell-cell adhesion, a wide variety of cells will be in contact with the T-cell to get these cells to differentiate. The same is true for the T-cell proliferation terms etc. Just because the cells are related in the cell ontology this does not mean that the cells are homotypic cells. Not all leukocytes are CD4+CD8+ T cells therefore adhesion between 2 leukocytes does not mean homotypic cell-cell adhesion.

Also I am not sure that all of these process require cell-cell adhesion or if T cells will response to soluble factors when not adhering to another cell, probably not, but just would be good to be sure that this whole T-cell branch should definitely be under the cell adhesion domain. I think there are some cytokines, e.g. IL-2 which will stimulate T-cell proliferation and the T-cell doesn't have to be adhering to another cell for it to proliferate http://www.nature.com/nri/journal/v12/n3/full/nri3156.html however I think the cells would need to have adhered to another cell in order to respond to IL2 so perhaps it is OK to keep a cell-cell adherence parent.

Best

Ruth

**Comment by cmungall** [comment]
It seems we have a lot of isa-overloading, with a lot of built in assumptions:

```
    is_a GO:0034109 ! homotypic cell-cell adhesion
      is_a GO:0070486 ! leukocyte aggregation
       is_a GO:0071593 ! lymphocyte aggregation
        is_a GO:0070489 ! T cell aggregation
         is_a GO:0042110 ! T cell activation
          is_a GO:0030217 ! T cell differentiation
           is_a GO:0033077 ! T cell differentiation in thymus ***
  ```

**Comment by paolaroncaglia** [comment]
Perhaps Alex Diehl could comment please?
@addiehl

**Comment by addiehl** [comment]
At least two problems here with the graph:

1)  'homotypic cell-cell adhesion' should not be a parent to 'leukocyte aggregation', as the class 'leukocyte' in the Cell Ontology groups encompasses many specific cell types which are not identical to each other but which may adhere to each other.  'leukocyte cell-cell adhesion' is the appropriate parent to 'leukocyte aggregation', based on the definitions.

1A)  'T cell aggregation' and 'thymocyte aggregation' are perhaps valid types of 'homotypic cell-cell adhesion' although again this is tricky because actually there are many subtypes of both T cells and thymocytes which may adhere or aggregate to each other, but are not identical subtypes.  I recommend co-annotation of gene products rather than implementing these relationships in the ontology.

2)  'T cell activation' should not be a child of 'T cell aggregation', and 'T cell aggregation' should not be a child of 'leukocyte aggregation'.  Arguably, 'T cell aggregation' has_part 'T cell activation' although I am not advocating for that relationship at this time.  Again, co-annotation of gene products to two process terms is safer than implement the relationship in the ontology, in the absence of further study.

-- Alex

**Comment by RLovering** [comment]
Hi Alex

thanks for confirming this information. I don't understand why 'T cell aggregation' should not be a child of 'leukocyte aggregation', The definitions look ok? Also you haven't mentioned the intervening term lymphocyte aggregation. It would be good to have this term included in this discussion so that it's placement is not overlooked.

Because of the wide variety of very well classified T cells please can I suggest that it might be better to include T cell aggregation as an is_a child to GO:0016337 single organismal cell-cell adhesion (or lymphocyte aggregation if this is an acceptable parent to the T cell term) and then allow the curator to add the homotypic or heterotypic cell-cell adhesion term depending on the specificity of the types of cells adhering to each other.

Thanks

Ruth

**Comment by RLovering** [comment]
note I should have included the link to this other adhesion ticket
https://github.com/geneontology/go-ontology/issues/12276#

**Comment by tberardini** [comment]
I''ll make the changes once the subject area experts have weighed in and come to an agreement. Please summarize the requested changes at that point.

**Comment by tberardini** [comment]
@addiehl, @RLovering - any additional thoughts/recommendations?  I am happy to implement when you reach an agreement on the requested changes (please enumerate).

**Comment by bmeldal** [comment]
I've just started annotating a bunch of interleukins and they certainly activate lymphocytes via a secretion pathway, not cell adhesion. I haven't looked at a differentiation case in detail yet, but again, I'm sure there are cases where secreted cytokines play a role and they should not be annotated 'by guilt' of ontology relations to cell adhesion terms.

Conclusion:
I think cell differentiation, activation and proliferation should not have is_a relationships to cell adhesion.

My 2p...

Birgit

**Comment by RLovering** [comment]
Hi Tanya

I'm not planning to contact any experts on this. I agree with Birgit and I think the majority of child terms need to be removed i.e. 
remove
 is_a GO:0042110 ! T cell activation
          is_a GO:0030217 ! T cell differentiation
           is_a GO:0033077 ! T cell differentiation in thymus ***

from this domain.

And probably the safest way forwards is to remove the parent GO:0034109 homotypic cell-cell adhesion from  
is_a GO:0070486 ! leukocyte aggregation.

Best

Ruth

**Comment by tberardini** [comment]
@addiehl - if you have no objections, I will go ahead and implement as Ruth suggested.

**Comment by tberardini** [comment]
Will wait till Monday for last comments, then will proceed with changes as suggested.

**Comment by addiehl** [comment]
Okay with me to remove 'T cell activation' as a child of 'T cell aggregation'.  Ruth is correct that 'T cell aggregation' should remain a child to 'lymphocyte aggregation'.  My points above (1) and (1A) should also be included as changes.

Thanks, Alex

**Comment by tberardini** [comment]
(1) removed  'T cell activation' as a child of 'T cell aggregation'.
(2) removed  'homotypic cell-cell adhesion' as a parent to 'leukocyte aggregation'
(3) did not implement relationships between 'T cell aggregation' and 'thymocyte aggregation' and  'homotypic cell-cell adhesion' 

I think that addresses the underlying problems originally brought up by this ticket.  Please reopen if that is not the case.
