### ISSUE TITLE
GO:0098655 children

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12281]
The term 
GO:0098655 cation transmembrane transport
has a long slew of children that look odd

for example
Is a 	GO:0035524 	proline transmembrane transport
Is a 	GO:0089709 	L-histidine transmembrane transport
Is a 	GO:0090455 	ornithine transmembrane import into vacuole
Is a 	GO:0090456 	lysine transmembrane import into vacuole
Is a 	GO:0090457 	histidine transmembrane import into vacuole
Is a 	GO:0090514 	L-tyrosine transmembrane import into vacuole
Is a 	GO:0090516 	L-serine transmembrane import into vacuole

**Comment by dosumis** [comment]
Probably because you are expecting this to refer to inorganic cation transport?  We have a term for that.  Agree that the general terms of of dubious utility.

**Comment by ValWood** [comment]
Are they cations? (not in CHEBI)

**Comment by dosumis** [comment]
You're right.  These came in via inference some time ago, but the inference is no longer entailed.  Could be due to a change in ChEBI or a deletion of a dodgy axiom somewhere in GO. We plan to move to automatically stripping inference when  no longer entailed. Until then we'll have to delete these by hand :-( . Did you spot any more?

**Comment by dosumis** [comment]
'cation transmembrane transport' and 'transports or maintains localization of' some 'amino acid' =>

'arginine transmembrane import into vacuole'
'arginine transmembrane transport'
'asparagine transmembrane import into vacuole'
'asparagine transmembrane transport'
'cysteine transmembrane transport'
'histidine transmembrane import into vacuole'
'isoleucine transmembrane transport'
'L-alanine import across plasma membrane'
'L-alanine transmembrane transport'
'L-arginine import across plasma membrane'
'L-arginine transmembrane export from vacuole'
'L-arginine transmembrane import into vacuole'
'L-arginine transmembrane transport'
'L-histidine transmembrane export from vacuole'
'L-histidine transmembrane import into vacuole'
'L-histidine transmembrane transport'
'L-lysine import across plasma membrane'
'L-lysine transmembrane export from vacuole'
'L-lysine transmembrane import into vacuole'
'L-lysine transmembrane transport'
'L-ornithine import across plasma membrane'
'L-ornithine transmembrane export from vacuole'
'L-ornithine transmembrane transport'
'L-proline import across plasma membrane'
'L-proline transmembrane transport'
'L-serine transmembrane import into vacuole'
'L-tryptophan import across plasma membrane'
'L-tryptophan transmembrane transport'
'L-tyrosine transmembrane import into vacuole'
'L-valine transmembrane transport'
'leucine import across plasma membrane'
'lysine transmembrane import into vacuole'
'mitochondrial L-ornithine transmembrane transport'
'ornithine transmembrane import into vacuole'
'proline transmembrane transport'
'serine import across plasma membrane'
'transmembrane L-arginine transport from lysosomal lumen to cytosol'
'transmembrane L-histidine transport from lysosomal lumen to cytosol'
'transmembrane L-lysine transport from lysosomal lumen to cytosol'

**Comment by ValWood** [comment]
Antonia just spotted this because she was browsing  down the tree....so we aren't sure if there are others. It wasn't any systematic thing

**Comment by Antonialock** [comment]
yeah I was just looking at the children of 
GO:0098655 cation transmembrane transport

**Comment by mcourtot** [comment]
This has been fixed with the ETINES flush.
