### ISSUE TITLE
GO:0051124 ! synaptic growth at neuromuscular junction (and other synaptic assembly terms)

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12292]
A CACAO student is annotating PMID17021175, and wanted to use GO:0045887 ! positive regulation of synaptic growth at neuromuscular junction, which is a regulates term relative to GO:0051124 ! synaptic growth at neuromuscular junction. We were suspicious that the data supported increases in synaptogenesis but whether it was specific to growth was unclear. However, the parent relationships don't seem to distinguish between assembly and growth stages in synaptogenesis.

Under the parent term synapse assembly, there are part_of children for pre and post-synaptic assembly. But there is not a separate term for synapse maturation and growth, the last stage in  doi:1-.1038/nrm1242, which is a review on development of synapses. 

So it seems to me that 

GO:0051124 ! synaptic growth at neuromuscular junction and the related regulation terms should be GO:0051124 ! synaptic assembly at neuromuscular junction, based on synaptic assembly being an EXACT synonym of synaptogenesis

and/or 

Synaptic assembly could be not an exact synonym of Synaptogenesis, but rather a part_of a broader Synaptogenesis process term that encompasses pre- and post- assembly along with maturation and growth.

The differentia of neuromuscular vs neuron-neuron synapses would apply to each of these.

But I am not anything close to a neurobiologist, so other opinions are clearly needed!

**Comment by tberardini** [comment]
Assigning to @dosumis - synapse related.

**Comment by pgaudet** [comment]
@Pimmelorus please let me know if you agree with changing the label 

GO:0051124 ! synaptic growth at neuromuscular junction 
to GO:0051124 ! synaptic assembly at neuromuscular junction

Thanks, Pascale

**Comment by raymond91125** [comment]
Proposal:

change GO:0051124 name to "synapse assembly at neuromuscular junction" and definition to "The assembly of synapses at a neuromuscular junction."
change GO:0045887 name to "positive regulation of synapse assembly at a neuromuscular junction" and definition to "Any process that activates or increases the frequency, rate or extent of synapse assembly at a neuromuscular junction. "
and change other related terms accordingly (negative regulation, e.g.).

The observation in question is an increase in the number of functional synapses between motor neurons and muscles caused by a PI3K.

Thus the annotation could be "positive regulation of synapse assembly at a neuromuscular junction".

This proposal in essence wraps all synaptogenesis scenarios under the term synapse assembly, covering embryonic, nascent synapse formation and maturation, and post-embryonic modifications on a single synapse or making more synapses.

References [PMID14625534, brain development], [PMID18394474, LTP in Aplysia]

**Comment by pgaudet** [comment]
Looks good to me - However just one question: is the process of 'synaptic growth at neuromuscular junction' different from its parent 'GO:0007416 synapse assembly' ? If the process is exactly the same but this occurs at the neuromuscular junction rather than any other neuron, then perhaps we should merge? 

Another aspect we look at is whether there are other siblings making similar distinctions, and for this term there are none. 

Tagging @hattrill since most annotations to this term are FlyBase. 

Thanks, Pascale

**Comment by raymond91125** [comment]
That's right, the proposal would make GO:0051124 simply an anatomical location restriction to 'GO:0007416 synapse assembly' and there are no siblings (such as a CNS location). The present term name and definition are less clear, as Jim pointed out in his original post. I think merging is a good idea unless it is know that there is a substantial molecular and mechanistic difference between this anatomical location vs other locations that motivates further branching of the ontology.

**Comment by dosumis** [comment]
>  is the process of 'synaptic growth at neuromuscular junction' different from its parent 'GO:0007416 synapse assembly' ? If the process is exactly the same but this occurs at the neuromuscular junction rather than any other neuron, then perhaps we should merge?

The biology and assembly of NMJs is very different from neuron:neuron synapses.  Please don't merge.

**Comment by raymond91125** [comment]
@dosumis @ukemi Is the revised term name and definition for GO:0051124 OK?
change GO:0051124 name to "synapse assembly at neuromuscular junction" and definition to "The assembly of synapses at a neuromuscular junction."
from: synaptic growth at neuromuscular junction DEF The growth of a synapse at a neuromuscular junction, the site of apposition of a motor end plate and the subneural cleft of the skeletal muscle fiber that it innervates.

**Comment by ukemi** [comment]
@dosumis is probably more current than me, but the biology of forming mature synapses the NMJ is quite complex and includes growth and subsequent pruning and fine tuning. If I recall correctly, there are many more made than needed and then they get modified an pruned based on activity. I guess this goes down the rabbit hole of what is the extent of assembly versus growth? @dosumis

**Comment by hattrill** [comment]
Here's a current review https://neuraldevelopment.biomedcentral.com/articles/10.1186/s13064-020-00147-5 and it agrees with @ukemi 's description. "Synaptogenesis is not a singular event but rather a dynamic process......Such changes encompass not only the addition of new synapses but also their “pruning” or removal."
There are pathways that specifically act to instruct outgrowth/pathway finding, etc and then there are other processes governing how the synapses are formed, maintained and augmented/strengthened. But, I will defer to @dosumis as the absolute expert on this :-)

**Comment by dosumis** [comment]
Distinct NMJ terms definitely needed.   Might be OK to treat assembly and growth of NMJ as the same thing.

**Comment by pgaudet** [comment]
Thanks everyone ! We should update definitions as well - looks like "The assembly of synapses at a neuromuscular junction." could be clarified. 

Also, should other terms such as 'GO:0098883 synapse pruning' be added as 'part of' GO:0051124 ! synaptic growth at neuromuscular junction?

**Comment by pgaudet** [comment]
It would be nice to update the reference as well.

**Comment by raymond91125** [comment]
References:
1. PMID: 32741370 Synapse development and maturation at the drosophila neuromuscular junction (2020)
2. PMID: 14625534 Some assembly required: the development of neuronal synapses (2003)
3. PMID: 18394474 Synaptic remodeling, synaptic growth and the storage of long-term memory in Aplysia (2008)

**Comment by raymond91125** [comment]
GO:0098883 synapse pruning is synonym to "synapse disassembly". GO:0051124 is a sub class of GO:0007416 synapse assembly. They are considered opposite processes that act on the synapse, I think.

**Comment by pgaudet** [comment]
@ftwkoopmans We'd like to have SynGO's opinion on this one - 

- should we distinguish synapse assembly vs growth synaspe ? 
- should we distinguish synapse assembly/growth in NMJ versus other synapse types 

Thanks, Pascale

**Comment by ftwkoopmans** [comment]
> * should we distinguish synapse assembly vs growth synaspe ?

The scope of SynGO is mostly limited to 'canonical inhibitory and excitatory synapses' so as a rule-of-thumb; we consider child terms for an ontology if experimental evidence in brain is available for such specific child terms for more than 1 protein that can be annotated against it. Given the currently limited data on molecular mechanisms of synaptogenesis in (mammalian) neuron:neuron synapses we stick with synapse assembly and disassembly (so no distinction in assembly vs growth).

As others have commented, synaptogenesis is a dynamic process where much experimental work remains to be done to describe its molecular mechanics in detail, in comparison to for instance the commonly studied synaptic vesicle exocytosis or endocytosis pathways. 

I think you can look at synaptogenesis in two ways (ofc these are interconnected and there are layers of complexity involved, but this abstraction will do for argument's sake I hope); 
- the molecular mechanisms within a synapse 
- network organization; given network activity, decide and signal/initiate the creation of new (or pruning of existing) synapses connecting cell A to B

The current scope for SynGO is focussed on the former.

**Comment by ftwkoopmans** [comment]
> * should we distinguish synapse assembly/growth in NMJ versus other synapse types

I agree with David's earlier statement;
>The biology and assembly of NMJs is very different from neuron:neuron synapses. Please don't merge

**Comment by pgaudet** [comment]
Thanks @ftwkoopmans , that's very useful

**Comment by raymond91125** [comment]
Thanks everyone for your input. I think if we just simply change the wording from "synaptic growth" to "synaptic assembly", that would suffice.

**Comment by pgaudet** [comment]
The PR passes the checks, I think it's OK to merge. 

However - usually if you change a term label, the old label needs to be a synonym, but I dont see new synonyms and there is no error reporting this. 
@balhoff - Did we change the rules? 


Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet I haven't changed anything related to this. I looked through the SPARQL checks and didn't find anything that would check for this.

**Comment by raymond91125** [comment]
added related synonyms in the new pull request.

**Comment by pgaudet** [comment]
Looks good ! Please go ahead and merge.
