### ISSUE TITLE
GO:1990598 repair of mono-orientation defects

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12291]

**Comment by ValWood** [comment]
GO:1990598 repair of mono-orientation defects
is defined mitotically but it is under 'sister chromatid biorientation' instead of the mitotic descendent  term

**Comment by tberardini** [comment]
Solution is to move it under the mitotic descendant term?

**Comment by ValWood** [comment]
yep, may need to also change the term name as this must also happen at meiosis II
so if we rename
repair of mitotic mono-orientation defects
we can add meiotic term if/when we have genes to annotate

**Comment by tberardini** [comment]
renamed and moved
