### ISSUE TITLE
MP/TPV GO:0072766 centromere clustering at the nuclear envelope

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12293]
GO:0072766 centromere clustering at the nuclear envelope
is defined
A cellular localization process in which kinetochores/centromeres are coupled together at the nuclear periphery. This process is responsible for the Rabl-like configuration of chromosomes in the interphase nuclei. In fission yeast this occurs at a location near the old mitotic spindle pole body.

but it has no parentage to "mitotic cell cycle"

it does however have
GO:0098813 nuclear chromosome segregation
this parentage should be removed. Although defects in this process results in chromosome segregation
defects it is clearly upstream of segregatin (in mitotic interphase)

**Comment by ValWood** [comment]
It should have just 'mitotic cell cycle'

**Comment by tberardini** [comment]
Making sure:

part_of mitotic cell cycle
is_a centromere clustering

**Comment by tberardini** [comment]
Ok, done.

-relationship: part_of GO:0098813 ! nuclear chromosome segregation
+relationship: part_of GO:0000278 ! mitotic cell cycle
