### ISSUE TITLE
GO:0043148 mitotic spindle stabilization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12294]
I have a problem with this term
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0043148#term=annotation
The cell cycle process in which spindle integrity is maintained during M phase of mitosis.

I don't think we are really annotating 'stability' here, its used as a catch  all for phenotypes like 
"spindle collapse' when things go wrong with the spindle assembly or elongation. One problem with this term is that it links to 'regulation'.

Perhaps the solution would be to merge it with
GO:0007052 mitotic spindle organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the microtubule spindle during a mitotic cell cycle.

I don't see a difference? (I probably requested this term years ago...)

**Comment by tberardini** [comment]
History:

https://sourceforge.net/p/geneontology/ontology-requests/11163/

There are a bunch of IMP annotations to this term from other dbs.  Maybe revisit the other issue and see if that reasoning still holds.

**Comment by ValWood** [comment]
There is something wrong, but I can't figure out what it is. I think there is a problem with stability.
Here spindle integrity is probably maintained, but I can't see any difference  from experiments which would allow you to choose

GO:0007052 mitotic spindle organization
or
GO:0043148 mitotic spindle stabilization

the 'integrity' is the same as saying results in the assembly, arrangement of constituent parts, or disassembly of the microtubule spindle 
(it seems more like a phenotype than a process)

@Antonialock @mah11  any suggestions?

**Comment by tberardini** [comment]
Here's a shot of the EXP annotations to this term.  Ask other dbs to weigh in?  
<img width="1244" alt="screen shot 2016-02-19 at 1 51 31 pm" src="https://cloud.githubusercontent.com/assets/4998871/13190118/28eee854-d710-11e5-9da6-314dcce2da48.png">

**Comment by ValWood** [comment]
yep 

@RLovering  do you think "spindle organization" or "spindle assembly" term would be more appropriate for this cyclin?
(I'm not sure what we are trying to capture with spindle stability that is not covered by spindle organization, or assembly...stability is a consequence of correct assembly rather than a process per se. ? do you agree?)

At present this is causing problems in one of my annotation consistency exercised because spindle stability ends up being a type of "regulation of cell cycle"
(which might be true for your cyclin,  but for other reasons, but is not correct, as far as I can tell for the pombe or S. cerevisiae annotations.

Val

(I will ping SGD helpdesk for them to check)

**Comment by robnash** [comment]
Hi,

I had a quick look at the terms and the annotations at SGD. I have also read the thread. I think Val has a reasonable argument here, as the two terms appear to be very similar, and in reality spindle stabilization is just a downstream consequence of a properly assembled spindle. With respect to our annotations Ase1 is clearly involved in assembly and elongation of the spindle so I think we could re-annotate to the assembly term with no loss in information. For Fin1p, we will need to work on the annotations as its been shown to be a PP1 regulatory subunit and very recently demonstrated to be involved in recovery from the spindle assembly checkpoint (SAC) by kicking the checkpoint protein Bub1p off of the kinetochore in anaphase as part of recovery from SAC. The original annotations as Val argues are probably just a consequence of the premature localization of the mutant protein to the spindle, resulting in spindle instability ... a phenotype. 

Hope this helps.

Cheers,
Rob

**Comment by tberardini** [comment]
Emailed Helen A. at Flybase for her input.  I can't track down her github handle.

**Comment by hattrill** [comment]
As it is defined, 'The cell cycle process in which spindle integrity is maintained during M phase of mitosis', 'mitotic spindle stabilization' doesn't seem to mean so very much. 

Most FlyBase examples where 'stability' is used are better described by 'organisation'. Authors seem use 'stabilisation' to describe the outcome of various MT/spindle interactions. I would therefore be happy for a merge of 'GO:0043148 mitotic spindle stabilization' with 'GO:0007052 mitotic spindle organization'.

Helen

**Comment by ValWood** [comment]
Ah sorry, I thought it was only the 4 annotation in the panel.

**Comment by hattrill** [comment]
Yes, I am proud to say that we've beaten you in the meaningless annotation class.

**Comment by ValWood** [comment]
Well I  felt obliged to fix this because I think I requested the term in the first place, but its amazing what difference half a decade can make to your judgement....

**Comment by tberardini** [comment]
There are 16 EXP annotations, breakdown by DB on the left hand of the pic. @vanaukenk - would you mind having a look at the WB annotations?  There are only two.

**Comment by tberardini** [comment]
@vanaukenk - would you mind having a look at the WB EXP annotations (to 'mitotic spindle stabilization')? There are only two.  We're looking to merge 'GO:0043148 mitotic spindle stabilization' with 'GO:0007052 mitotic spindle organization'.

**Comment by robnash** [comment]
Hi,

Not a problem. Will put this on my list.

Cheers,
Rob

On Mar 22, 2016, at 4:05 PM, Tanya Berardini <notifications@github.com<mailto:notifications@github.com>> wrote:


@vanaukenk<https://github.com/vanaukenk> - would you mind having a look at the WB EXP annotations (to 'mitotic spindle stabilization')? There are only two. We're looking to merge 'GO:0043148 mitotic spindle stabilization' with 'GO:0007052 mitotic spindle organization'.

**Comment by tberardini** [comment]
@robnash - you're good!  You've done your part already.  If we decide to merge, though, you will probably want to reannotate, based on your earlier comment.

**Comment by tberardini** [comment]
@vanaukenk - last chance, I'll plan to merge tomorrow.  Thanks :)  I know you're busy - sorry to be such a pest.

**Comment by tberardini** [comment]
As I started to do the merge of 'mitotic spindle stabilization' into 'mitotic spindle organization', I also noticed 'meiotic spindle stabilization', 'meiotic spindle organization', 'spindle organization' and 'spindle stabilization'.

Shall I go ahead and do the merges on those sets too?

**Comment by ValWood** [comment]
I think so...

**Comment by tberardini** [comment]
Merged:

1. _spindle stabilization_ into _spindle organization_
2. _mitotic spindle stabilization_ into _mitotic spindle organization_
3. _meiotic spindle stabilization_ into _meiotic spindle organization_
