### ISSUE TITLE
NTR: generation of T-type calcium current

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12297]
We have the existing term: generation of L-type calcium current ; GO:0061577 and I'm looking to add the corresponding 'T-type calcium current' term.

[Term]
id: GO:0061577
name: generation of L-type calcium current
namespace: biological_process
def: "A process in which a calcium ion is transported from one side of a membrane to the other by means of an L-type calcium channel." [GOC:dph]
is_a: GO:0070588 ! calcium ion transmembrane transport
relationship: has_part GO:0008331 ! high voltage-gated calcium channel activity
created_by: dph
creation_date: 2013-11-15T16:20:27Z

I'm annotating a paper showing that Wnt signaling components regulate T-type calcium current (PMID:20371816) by increasing expression of the voltage-gated calcium channel (Cav3.1). Could I add the corresponding T-type current term (with the view to add in regulation terms)?

GO:NEW
name: generation of T-type calcium current
namespace: biological_process
def: "A process in which a calcium ion is transported from one side of a membrane to the other by means of a T-type calcium channel." [GOC:PARL, GOC:bf, PMID:20371816]
is_a: GO:0070588 ! calcium ion transmembrane transport
relationship: has_part GO:0008332 ! low voltage-gated calcium channel activity

Just checking because it's a bit of an unusual term.
Thanks!

**Comment by tberardini** [comment]
I don't see why not.  @ukemi, since you added the L-type term, could you have a quick look? Thanks.
@rebeccafoulger - are you editing using OE or will you request using TG Free Form?

**Comment by ukemi** [comment]
Looks ok to me.

**Comment by dosumis** [comment]
What't the difference between a calcium current and calcium transport across the membrane?

**Comment by ukemi** [comment]
According to what's in the ontology now, the generation of the current is a type of calcium ion transmembrane transport.

**Comment by dosumis** [comment]
Doesn't all transport of ions across a membrane constitute a current flowing across it? Also not sure what 'generation of' adds.

**Comment by ukemi** [comment]
'generation of' was there to make it consistent with a the old action potential term, but that has since changed so in this case it probably doesn't add anything.

**Comment by tberardini** [comment]
Becky - thoughts?  EXP annotations to the L-type term are all from BHF with one from RGD.  Is it just me or could/should these terms be:

calcium ion transmembrane transport via high voltage-gated calcium channel

and

calcium ion transmembrane transport via low voltage-gated calcium channel

?

**Comment by tberardini** [comment]
@rebeccafoulger - can you comment please?

**Comment by rebeccafoulger** [comment]
Hi all- knew this one was going to cause trouble! 

Sorry for the delay Tanya! Your suggestion @tberardini of the 'via' terms fits with the has_part relationships and sounds much less like an assay-readout. I was going to say the process terms seem a bit redundant if we already have the low- and high- channel activities, but I see all existing annotations are to 'regulation' terms so it's handy to have the process terms in place.

So I'm fine with your suggestion Tanya! (with generation names as synonyms). @RLovering and @rachhuntley - any thoughts? One annotation is one of your miRNA ones Rachael.

**Comment by rachhuntley** [comment]
Yes, I looked at the paper I curated and I think that would be fine.

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090676
+name: calcium ion transmembrane transport via low voltage-gated calcium channel
+namespace: biological_process
+def: "A process in which a calcium ion is transported from one side of a membrane to the other by means of a low voltage-gated calcium channel." [GOC:bf]
+synonym: "generation of T-type calcium current" RELATED []
+is_a: GO:0070588 ! calcium ion transmembrane transport
+relationship: has_part GO:0008332 ! low voltage-gated calcium channel activity
+created_by: tanyaberardini
+creation_date: 2016-03-23T10:15:23Z
+


also changed names as described for the L-type terms (core BP and regulation children)
