### ISSUE TITLE
FK506 binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12295]
Based on this 
https://github.com/geneontology/go-ontology/issues/11113

is FK506 binding  allowed
(in particular we are picking up mapping to this for pombe FK binding pepetidyl-prolyl ci-trans isomerases, but this isn't 'normal' for these gene products for pombe

**Comment by tberardini** [comment]
Will consult other GO eds about what to do for terms like this that are already in the ontology.
