### ISSUE TITLE
GO:0051607 defense response to virus

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12296]
has a child GO:0009616 virus induced gene silencing.

Surely, GO:0009616 could be detrimental to the cell (and advantageous to the virus) while GO:0051607 aims at cell survival.

I might be totally wrong, of course!

Birgit

**Comment by tberardini** [comment]
From reading the definitions, the placement seems alright to me.  Emphasis is mine.

defense response to virus: Reactions **triggered in response to the presence of a virus **that act to protect the cell or organism.

virus induced gene silencing: Specific posttranscriptional gene inactivation ('silencing') **both of viral gene(s), and host gene(s) homologous to the viral genes**. This silencing is **triggered by viral infection**, and occurs through a specific decrease in the level of mRNA of both host and viral genes. 

http://www.noble.org/plantbio/mysore/project5/
"Virus-induced gene silencing (VIGS) is a RNA-mediated post-transcriptional gene silencing mechanism that protects plants against foreign gene invasion."

**Comment by bmeldal** [comment]
The additional quote you found specifies that VIGS is to protect the plant. Would it be wise to add it as a comment to make it clear or am I the only one struggling to find this obvious?

**Comment by tberardini** [comment]
Sure, I can add that.  It certainly can't hurt!

**Comment by bmeldal** [comment]
Thanks :)

**Comment by tberardini** [comment]
Added.
