### ISSUE TITLE
NTR: sulfoquinovosidase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12298]
The reference is PMID 26878550.  A request has already been made to create a new EC entry, but this may take some time.
Proposed definition: hydrolysis of terminal non-reducing α-sulfoquinovoside residues in α-sulfoquinovosyl diacylglycerides and α-sulfoquinovosyl glycerol, generating α-sulfoquinovose.
Child of GO:0016798.

Thanks,
Ingrid

**Comment by tberardini** [comment]
How cool!  Something new again.

Added through TermGenie FreeForm:

[Term]
id: GO:1990929
name: sulfoquinovosidase activity
namespace: molecular_function
def: "Catalyzes the hydrolysis of terminal non-reducing alpha-sulfoquinovoside residues in alpha-sulfoquinovosyl diacylglycerides and alpha-sulfoquinovosyl glycerol, generating alpha-sulfoquinovose." [GOC:imk, PMID:26878550]
is_a: GO:0016798 ! hydrolase activity, acting on glycosyl bonds
created_by: tb
creation_date: 2016-02-19T01:18:37Z
