### ISSUE TITLE
	IPR007259 should be nucleation not 'regulation of.."

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12302]
Is a gamma tubulin subunit. Gamma tubulin complex has a direct role in nucleation

**Comment by ValWood** [comment]
wrong tracker

**Comment by EBI-Hsinyu** [comment]
Hello, 

Thank you for this. I have deleted the term 'positive regulation of microtubule nucleation' and added 'microtubule nucleation'. 

Regards,

Hsin-Yu
