### ISSUE TITLE
IPR015519 to replicative senesence

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12305]
This seems wrong for  ATM checkpoint kinase. Is there a reference? it sounds like a phenotype.

val

**Comment by ValWood** [comment]
wrong tracker

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

This is from the reference: PMID:15149599 

"While replicative senescence in normal cells appears to be mediated primarily by the ATM pathway to establish a G1 checkpoint, several studies have indicated that ATM-independent responses can also mediate cell cycle arrest in response to dysfunctional telomeres."

Hsin-Yu

**Comment by ValWood** [comment]
Ah OK. I don't think this would apply to unicellular organisms, where senescence isn't a normal process.
Checkpoint signalling would be OK.....

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

I believe the term 'senescence' has been used in some publications (PMID:26912831, PMID:26833420 for instance, PMID:23993840).  However, you are right that the term 'senescence' is mostly used on multicellular organisms; the term 'cell ageing' is more likely to be used on yeasts. I will also check with other curators to see if we want to change the term or ask UniProt to block this term for fungi taxonomy group.  

Regards, 

Hsin-Yu

**Comment by ValWood** [comment]
The annotations at the protein family level need to fit all species, so this would need to be made by individual annotations rather than a mapping that is only applicable to some kingdoms.

Replicative cell ageing isn't really a normal process either....

**Comment by EBI-Hsinyu** [comment]
Hello, 
Hello, 

Just found a paper [PMID:23672410]. It states that the budding yeast Tel1 regulates replicative senescence. 

Aging Cell. 2013 Aug;12(4):719-27. doi: 10.1111/acel.12099. Epub 2013 Jun 28.
Multiple genetic pathways regulate replicative senescence in telomerase-deficient yeast.
Ballew BJ1, Lundblad V.

Hsin-Yu

**Comment by ValWood** [comment]
This is true, but in yeast 

replicative senescence
A cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging.

is not a 'normal' process

It's  what happens cells getting old and wearing out. (I'm not even sure that this definition fits)... I need to ask others how we would annotate these. For PomBase we would make phenotype annotations to these terms. I'll speak to my colleagues at SGD and get back to you.
