### ISSUE TITLE
microtubule attachment TPV

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12308]
I thought this was in a previous ticket, but I can't find an open one.

It seems incorrect that "attachment of spindle microtubules to kinetochore"
is a descendent of "cytoskeleton organization"

(its really only attaching, not organizing...also some of the gene products involved in attachment are kinetochore proteins, so these look particularly odd)

**Comment by ukemi** [comment]
Hi Val,

I'm not sure about this. Wouldn't you consider the attachment part of the organization of the microtubule cytoskeleton? The kinetochore attachment is via a subset of microtubules and even though the kinetochore is not part of the microtubule, it seems that the attachement of that subset of microtubules is part of the organization of the spindle cytoskeleton.

-D

**Comment by ValWood** [comment]
OK chatted with David O_S. Its OK. It smelt funny to me but it's fine.

**Comment by ValWood** [comment]
I still think this is wrong.

It seems really odd that some of these kinetochore components slim to microtubule organization. They don't have anything to do with organizing the spindle. In a previous ticket  @tberardini agreed and it got removed.
https://github.com/geneontology/go-ontology/issues/11685

I'm struggling to pinpoint exactly why its wrong, but  the kinetochore doesn't 'organize' the spindle. Its more the other way around. The spindle is moving the chromosomes via kinetochore attachment.  Does that make sense?

**Comment by ukemi** [comment]
I guess what it comes down to is the definition of the microtubule cytoskeleton. I think it is more than just microtubules. Right now, kinetochore is not part of the microtubule cytoskeleton, so your concern is valid according to the current structure of the ontology and Tanya was correct to remove the link. If you don't think the kinetochore is considered part of the microtubule cytoskeleton, then I think you are correct. If you do think the kinetochore is part of the microtubule cytoskeleton, then I think the attachment is part of the organization of the cytoskeleton, not just the microtubule, but the whole microtubule cytoskeleton. Reading my old cell biology textbook suggests that they are not part of the cytoskeleton, but rather attach to it. What do you think?  You make the call and I will do the edits.

**Comment by ValWood** [comment]
I would say the kinetochore is definitely NOT part of the microtubule cytoskeleton. Its part of the chromosome.

**Comment by ukemi** [comment]
OK. I will remove the parent.

**Comment by ValWood** [comment]
reopening, some kids missed
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051455#term=ancchart

**Comment by ukemi** [comment]
I just went through all the kids, and none of them have cytoskeleton organization as a parent. If you still see it, can you let me know the specific terms?

-D

**Comment by ValWood** [comment]
The link I put above doesn't have it anymore, so closing.....
