### ISSUE TITLE
regulation of cardiac muscle cell membrane repolarization

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12301]
Hi 

Following discussion with Paola please could this new GO term be created as a parent to the more specific child term listed below
GO:0060306 regulation of membrane repolarization
> New GO term: regulation of cardiac muscle cell membrane repolarization
>> is_a Child term GO:0060372	regulation of atrial cardiac muscle cell membrane repolarization	
>> is_a Child term GO:0060307	regulation of ventricular cardiac muscle cell membrane repolarization

Definition of new term: 
Any process that modulates the establishment or extent of a membrane potential in the polarizing direction towards the resting potential in a cardiomyocyte.

synonyms
exact	regulation of cardiac muscle cell repolarization
exact	regulation of cardiomyocyte membrane repolarization
related	heart repolarization
related	regulation of cardiac muscle repolarization

with DbxRef GOC:rl, as well as those listed as labels

Many Thanks

Ruth

**Comment by dosumis** [comment]
Added, along with formalisation.

**Comment by dosumis** [comment]
label "regulation of cardiac muscle cell membrane repolarization"
definition "Any process that modulates the establishment or extent of a change in membrane potential in the polarizing direction towards the resting potential in a cardiomyocyte."
has_exact_synonym "regulation of cardiac muscle cell repolarization"
has_exact_synonym "regulation of cardiomyocyte membrane repolarization"
has_obo_namespace "biological_process"
has_related_synonym "heart repolarization"
EquivalentTo: 'biological regulation' that regulates some 'cardiac muscle cell membrane repolarization'

label "cardiac muscle cell membrane repolarization"
definition "The process in which ions are transported across the plasma membrane of a cardiac muscle cell such that the membrane potential changes in the repolarizing direction, toward the steady state potential. For example, the repolarization during an action potential is from a positive membrane potential towards a negative resting potential."
has_obo_namespace "biological_process"
EquivalentTo: 'membrane repolarization' that 'occurs in' some 'cardiac muscle cell'

label "atrial cardiac muscle cell membrane repolarization"
definition "The process in which ions are transported across the plasma membrane of a cardiac muscle cell such that the membrane potential changes in the repolarizing direction, toward the steady state potential. For example, the repolarization during an action potential is from a positive membrane potential towards a negative resting potential."
has_obo_namespace "biological_process"
EquivalentTo: 'membrane repolarization' that 'occurs in' some 'regular atrial cardiac myocyte'
SubClassOf: 'cardiac muscle cell membrane repolarization' { Inferred }

New inferred class hierarchy:

![image](https://cloud.githubusercontent.com/assets/112839/13395821/0e09dc20-dee9-11e5-9c0c-75c37ebcb4c9.png)
 
![image](https://cloud.githubusercontent.com/assets/112839/13395848/2dbb7a4c-dee9-11e5-9ac0-221e4788af73.png)
