### ISSUE TITLE
Possible term merge "cortical actin cytoskeleton stabilization"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12307]
cortical actin cytoskeleton stabilization

Same issue as:
https://github.com/geneontology/go-ontology/issues/12294

would be better just as "organization"
Only has 15 EXP annotation, PomBase, Flybase and dictybase

**Comment by ukemi** [comment]
Hi Tanya,
Assigning to you since it looks almost identical to the other one.

-D

**Comment by ValWood** [comment]
making the title more informative!

**Comment by tberardini** [comment]
@hattrill, @pfey03 - could you check your DB's annotations please to the term in the subject?  Same issue as #12294, is  xx stabilization = xx organization?

**Comment by hattrill** [comment]
Yes, I agree - merge away.

**Comment by tberardini** [comment]
@pfey03 - could you check your DB's annotations please to the term in the subject? Same issue as #12294, is xx stabilization = xx organization?

Thank you.

**Comment by pfey03** [comment]
we have two annotations to this term and IMO stabilization is part of organization. But I wouldn't be opposed to a merge; we also have one mitotic spindle... annotation https://github.com/geneontology/go-ontology/issues/12294
When you decide to merge I'll update those 3. Thanks -  and sorry I was so swamped...

**Comment by tberardini** [comment]
I've merged the stabilization term into the organization one.

**Comment by tberardini** [comment]
[Term]
id: GO:0030866
name: cortical actin cytoskeleton organization
namespace: biological_process
alt_id: GO:0033109
def: "A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of acti\
n-based cytoskeletal structures in the cell cortex, i.e. just beneath the plasma membrane." [GOC:dph, GOC:jl, GOC:mah, GOC:pf]
synonym: "actin cortex stabilization" EXACT []
synonym: "cortical actin cytoskeleton organisation" EXACT [GOC:curators]
synonym: "cortical actin cytoskeleton organization and biogenesis" RELATED [GOC:mah]
synonym: "cortical actin cytoskeleton stabilization" EXACT []
synonym: "cortical resistance" RELATED []
is_a: GO:0030036 ! actin cytoskeleton organization
is_a: GO:0030865 {is_inferred="true"} ! cortical cytoskeleton organization
intersection_of: GO:0016043 ! cellular component organization
intersection_of: results_in_organization_of GO:0030864 ! cortical actin cytoskeleton
