### ISSUE TITLE
NTR: (D)-2-hydroxyglutarate-pyruvate transhydrogenase activity

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#12300]
Hi,

The following paper describes a novel transhydrogenase activity in yeast:

Saccharomyces cerevisiae Forms D-2-Hydroxyglutarate and Couples its Degradation to D-Lactate Formation via a Cytosolic Transhydrogenase.   PMID: 26774271

I therefore would like to request the following term:

Term: (D)-2-hydroxyglutarate-pyruvate transhydrogenase activity

Definition: Catalysis of the reaction: (R)-2-hydroxyglutarate + pyruvate = alpha-ketoglutarate + D-lactate, with FAD functioning as an intermediate hydrogen acceptor

Synonyms: D-2HG-pyruvate transhydrogenase activity, R-2-hydroxyglutarate alpha-pyruvate transhydrogenase activity

Instance of GO:0016614  oxidoreductase activity, acting on CH-OH group of donors 

Definition reference: PMID: 26774271

Thanks,
Rob

**Comment by dosumis** [comment]
Hi Rob,

Looks straightforward.  I'd like to add an EC number if poss.  Do you know if there is one?

Cheers,
David

**Comment by dosumis** [comment]
Added as requested.  No changes.
Cheers,
David

**Comment by ValWood** [comment]
Is there an EC number for this yet? Oliver lab interested for metabolic map....

**Comment by robnash** [comment]
Thanks for adding this David. Much appreciated. 

I looked around on the ExPASy site and see nothing that matches this activity. According to the paper this is a new enzymatic activity so I don't think it will have a number. If someone knows where to request an EC number I can forward what I have. 

Cheers,
Rob
