### ISSUE TITLE
MP GO:1903087 mitotic spindle pole body duplication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12310]
please add
mitotic  spindle pole body organization
has ( GO:0051300 spindle pole body organization)

**Comment by ukemi** [comment]
Hi Val,

Can't you create 'mitotic spindle pole body organization' using termgenie? I'm not exactly sure what you want in this ticket.

-D

**Comment by ukemi** [comment]
Val,

Do you just want the new term in this request, or is there another issue?

-D

**Comment by ValWood** [comment]
I don't know why I opened a ticket for this one. Done via term genie.
