### ISSUE TITLE
Incorrect ETINE flagging:

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12316]
The following are flagged as ETINEs in this report:
http://build.berkeleybop.org/job/build-go-assert-inferences-report/2877/artifact/assert-report.txt

But they appear to be inferred correctly in Protege + ELK.

GO:0008333	endosome to lysosome transport	GO:0016482	cytoplasmic transport

![image](https://cloud.githubusercontent.com/assets/112839/13429820/f28f5822-dfb9-11e5-9540-f432c45e2973.png)

There are lots of other ETINES to "GO:0016482	cytoplasmic transport" that are equally suspect.

Side of membrane to organelle part": 
GO:0098538	lumenal side of transport vesicle membrane	GO:0044433	cytoplasmic vesicle part	
GO:0098539	cytoplasmic side of transport vesicle membrane	GO:0044433	cytoplasmic vesicle part	
GO:0098554	cytoplasmic side of endoplasmic reticulum membrane	GO:0044432	endoplasmic reticulum part
GO:0098565	lumenal side of endosome membrane	GO:0044440	endosomal part

![image](https://cloud.githubusercontent.com/assets/112839/13429859/24285816-dfba-11e5-86cb-419cb105ed0f.png)

Possible explanation:  In testing, it is hard to remove all inferences that might be being used.  If this is the issue, it may be easier to work through ETINEs once inferences have been split out.

Related ticket: #12315 
CC @cmungall

**Comment by dosumis** [comment]
Update:

As a crude experiment - I've created an OBO version of gene_ontology_write using egrep -v 'is_inferred="true"'.  I'm finding some interesting problems 

For example, this is not entailed:

GO:0098538 lumenal side of transport vesicle membrane GO:0044433 cytoplasmic vesicle part

because after stripping inferred axioms, side of membrane has no classification up to cellular_component.

![image](https://cloud.githubusercontent.com/assets/112839/13431676/47b8cf60-dfc2-11e5-8e30-9c199786a74d.png) 

Presumably a previous redundancy stripping removed the reason that 'membrane part' was entailed.

**Comment by dosumis** [comment]
This one is down to the intracellular clause on cytoplasmic transport

GO:0008333 endosome to lysosome transport GO:0016482 cytoplasmic transport

Simple fix for now is to assert intracellular transport as genus of all affected terms

Might want to consider changing pattern for cytoplasmic transport to 'occurs in' some cytoplasm.  But this then has the problem that we need to add many more occurs in axioms to transport classes.

**Comment by cmungall** [comment]
Whatever we do, all assumptions should be made explicit, preferably in 
the label.

the intercellular clause in 'cytoplasmic transport' prevents transport 
from the cytosol of one cell to the outside of the same cell (despite 
the fact this is allowed by the text definition).

we could have transport from the endosome of one cell to the lysosome of 
another (unlikely perhaps, but analogous situations may exist). This 
also wouldn't fit.

**Comment by dosumis** [comment]
> Whatever we do, all assumptions should be made explicit, preferably in
the label.

Agree

> the intercellular clause in 'cytoplasmic transport' prevents transport
from the cytosol of one cell to the outside of the same cell (despite
the fact this is allowed by the text definition).

I think the term itself is pretty suspect. Is it really intuitive to have cytoplasmic transport cover everything coming in and out of the cytoplasm?  I'm inclined to redefine as "transport that 'occurs in' some cytoplasm" or obsolete it (even with occurs in, it covers transport in and out of cytoplasmic organelles.  The problem with this strategy is that it requires adding an occurs_in clause to many classes to get appropriate classification.
