### ISSUE TITLE
vesicular transport

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12317]
We have many transport terms that do not mention vesicles even though they involve/are mediated by vesicles.  These terms have no classification that reflects this:

![image](https://cloud.githubusercontent.com/assets/112839/13433057/2400669a-dfc8-11e5-8fa6-e3ca1b9a4041.png)
[Source](https://www.google.co.uk/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjkvqmk8J_LAhWD1BoKHQ7ODlcQjxwIAw&url=http%3A%2F%2Findividual.utoronto.ca%2Fstudybuddies%2F%5Bbio230%5D%2520Lecture%252001%2520Membrane%2520Trafficking.html&psig=AFQjCNE5qYEkJLyrx_2dfRmKzLTxpnoUbA&ust=1456934771226976)

ER - Golgi, PM -> endosome, endosome -> lysosome.

Shouldn't we fix this?

One confounding issue for patterns:

Do we refer to the vesicle as mediating the transport  - or as the cargo?  Essentially the same process transports the soluble contents of vesicles, the membranes (membrane trafficking) and proteins embedded in membranes (protein transport?).  Can combine all these into general process terms - or do we keep separate hierarchies?

**Comment by dosumis** [comment]
Potential new patterns

'vesicle-mediated transport'
 and ('has target start location' some 'Golgi apparatus')
 and ('has target end location' some lysosome)
 and ('occurs in' some cytoplasm')  # Strictly, need to say where goes in between. Could be buried in new genus
{ and ('transports or maintains some Y') # Optional to indicate cargo
{ and ('results in transport along' some Z } # Optional to indicate transport along cytoskeletal fiber

For membrane trafficking Y - membrane region
For lipid trafficking Y = lipid (how to get link to membrane.
For protein trafficking Y = protein 

Slightly radical proposal = merge all vesicle-mediated transport & vesicle transport terms.

**Comment by ValWood** [comment]
I'm not sure about this:
> Slightly radical proposal = merge all vesicle-mediated transport & vesicle transport terms. 

vesicle mediated-transport
was intended for secretory pathway (membrane trafficking), (which I think uses actin?)

vesicle transport can also refer to
GO:0047496 vesicle transport along microtubule

I'm not completely sure  about the differences here. In pombe the tracking along a microtubule appears to be for proteins which are located to the cell tip on the internal side of the plasma membrane, polarity markers and such like (so not  for things which are released, or located in the membrane) I don't know if this is a general distinction.  Even though text books show the vesicles as cargo on microtubules, I have never seen any experimental evidence in fission yeast that the cargo transported along microtubules is actually  in vesicles....although I've wondered about this. You might need a domain expert.....





 
Term Basket: 6

**Comment by dosumis** [comment]
Hi Val, 

Don't see any issues with what you've posted. Clause to indicate transport (of vesicle) along cytoskeletal fibre is optional.   The main idea is to collapse down the rather artificial distinction between transport of a vesicle and transport by a vesicle.  Terms for transport *directly* along cytoskeletal fibers would not be affected

- David

**Comment by ValWood** [comment]
OK, I wasn't sure whether it was important.

**Comment by dosumis** [comment]
Pattern with new relation would be:

transport
and ('has target start location' some fu)
and ('has target end location' some bar)
and ('occurs in' some CC')
and (has_carrier some { vesicle or subclass of vesicle } )
and ('transports or maintains some CARGO ') 
and ('results in transport along' some { 'cytoskeletal fiber' or subclass } )

Still to be resolved:

1. Should the genus be transport or localization?  Consistency is important for complete autoclassification.
 * Transport: "The directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter or pore."
 * localization: "Any process in which a cell, a substance, or a cellular entity, such as a protein complex or organelle, is transported to or maintained in a specific location."
2. How to indicate when transport of a protein along a cytoskeletal fiber is direct - rather than via a vesicle?  With the proposed pattern - the general class is agnostic about this. May need to be some manually maintained branch.

**Comment by dosumis** [comment]
Notes from editor's call:

"A distinction needs to be made on whether or not things are inside a vesicle and the vesicle is moving, or if things are moving in and out of the vesicle. [Does mediated by cover this?] ‘mediated by’ should mean that it’s not [*sic*?] necessary and sufficient for the process to happen, but as it is now, it’s probably not enough to distinguish between cases; definition is broad enough to cover both."

DOS: this seems like a red herring to me.  
  * mediated_by has no def.  It should almost certainly be merged with ['has active participant'](http://purl.obolibrary.org/obo/RO_0002218) - which should probably be renamed (back) to 'has agent'  (But note, we also have ['has causal agent'](http://purl.obolibrary.org/obo/RO_0002608).  It doesn't really make sense to assert that a vesicle is the agent of transport in and of itself.

### TBD:
CC  @cmungall @tberardini @paolaroncaglia @ukemi @hdrabkin 
1. Are there any objections to collapsing the distinction between vesicle-mediated transport & vesicle transport terms?
2. Are there any objections to defining the following new relation for use in the new, merged terms?
   * **has_carrier**: "A relationship between a transport or localization process and a continuant that mediates that process by physically carrying its cargo."
     * SubPropertyOf: has_agent # - this needs to be merged with mediated_by
     * SubPropertyOf: 'transports of maintains localization of'
     * More formally, X has_carrier Y iff: 
         * localization(X),
         * continuant(Y), 
         * exists some Z, 
         * continuant(Z), 
         * Z part_of Y, 
         * X has agent Y, 
         * X 'transports of maintains localization of' Y, 
         * X 'transports of maintains localization of' Z.
3. Should the genus be transport (which, according to the def, shouldn't really apply to vesicles, although it does right now) or localization?

**Comment by dosumis** [comment]
Chatted with @ValWood - she seems broadly in favour of collapsing down these distinctions.  Also mentioned that membrane trafficking should be better supported - at least via synonyms.

**Comment by dosumis** [comment]
> \3. Should the genus be transport (which, according to the def, shouldn't really apply to vesicles, although it does right now) or 'establishment of localization'?

transport: "The directed movement of *substances* (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter or pore."
is_a: establishment of localization

establishment of localization "The directed movement of a cell, substance or cellular entity, such as a protein complex or organelle, to a specific location."

Is there any way to broaden transport without it becoming indistinguishable from 'establishment of localization'?  Not sure I can see one.

**Comment by ValWood** [comment]
Here are some terms which are 'establishment of localization' but which clearly involve no transport:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0070197#term=ancchart
genes annotated to this are nuclear membrane and tether the telomeres.

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071790#term=ancchart
or the spb

but this one sounds like it *should* be microtubule-mediated transport 
GO:0098863 nuclear migration by microtubule mediated pushing forces
(is currently only establishment of localization)

**Comment by ukemi** [comment]
Establishment of localization can also include selective degradation/stabilization or tethering of a diffused substance.

**Comment by dosumis** [comment]
> Establishment of localization can also include selective degradation/stabilization or tethering of a diffused substance.

Then this needs to be reflected in the definition, which not currently the case.  First clause:  "The *directed movement* of ...."

**Comment by dosumis** [comment]
New suggested def

**establishment of localization:** "Any process that localizes a substance or cellular component.  This may occur via movement, tethering or selective degredation."

**Comment by dosumis** [comment]
New suggested def

**localization:** "Any process in which a cell, a substance, or a cellular entity, such as a protein complex or organelle, is transported, tethered to or otherwise maintained in a specific location.  In the case of substances, localization may also be achieved via selective degredation."^^string

**Comment by ukemi** [comment]
This is better. We still need to figure out a way to distinguish between establishment and maintenance.

**Comment by dosumis** [comment]
No entirely happy with the selective degredation bits.  @ukemi  - do you know of any examples?  IIRC, I tried to find some some examples in annotation when working on this branch last year, but failed to find any.

**Comment by dosumis** [comment]
> This is better. We still need to figure out a way to distinguish between establishment and maintenance.

Maintenance certainly excludes movement.  Tethering feels like it is both.

**Comment by dosumis** [comment]
I think this works:
**maintenance of location:** "Any process in which a cell, substance or cellular entity, such as a protein complex or organelle, is maintained in a location and prevented from moving elsewhere."

**Comment by ukemi** [comment]
That works for me.

**Comment by ukemi** [comment]
@tberardini 
Including Tanya here because many years ago we thought a lot about this. It was not simple.

**Comment by ukemi** [comment]
I think selective degradation/stabilization has been shown quite a bit in embryos.
PMID:14588248
PMID:21035437
PMID:15186741

**Comment by dosumis** [comment]
> It was not simple.

I think there are some fundamental problems to do with glossing of effects on concentration with location/localization of individual material entities.  For example, transport of an entity changes the location of that entity, but may have not effect on the overall localization (local concentration) of entities of that type.

**Comment by tberardini** [comment]
Discussion getting v long.  Can you consolidate the latest revised defs for the affected terms please, @dosumis?

**Comment by dosumis** [comment]
Proposed new defs (needed because current defs require movement as mechanism):

*establishment of localization:* "Any process that localizes a substance or cellular component. This may occur via movement, tethering or selective degradation."

**localization:** "Any process in which a cell, a substance, or a cellular entity, such as a protein complex or organelle, is transported, tethered to or otherwise maintained in a specific location. In the case of substances, localization may also be achieved via selective degradation."

**Comment by tberardini** [comment]
Suggest revisiting in GO eds meeting for consensus.

**Comment by paolaroncaglia** [comment]
Added to agenda.

**Comment by dosumis** [comment]
General issue for vesicle-mediated protein transport:

We currently have no term for this, although isolated specific examples. @valwood mentioned she always thought this would be useful. Currently annotates to 2process terms - a vesicle mediated one and a protein transport one. Not linked. Retrofit would be pretty huge.

Need to think about what parts vesicle mediated protein transport has that plain vesicle mediated transport does not.

**Comment by ValWood** [comment]
The history of this is that,  as far as I am aware, at least for fission yeast every example  of an annotation to "vesicle-mediated transport" annotation 
http://www.pombase.org/spombe/related/GO:0016192
could also be annotated to "intracellular protein transport".

However, even though all of these gene products are involved in protein transport some of the time, we cannot be sure that they always transport proteins. So certain instances of the annotations may not be correct. I am never sure if this matters if this is always a role of the gene product.....

Anyway, this is the reason that the vesicle mediated terms are not a descendent of intracellular protein transport. I usually make a concurrent annotation, but as you know I don't like making 2 annotations to describe the same process. 

There are some 'protein specific' descendants like
GO:0007038 endocytosed protein transport to vacuole
which do have an intracellular protein transport' parent so currently the organization isn't very consistent.

**Comment by ValWood** [comment]
Wasn't Marc Feuermann adressing vesicel-meidated transport for PAINT (tagging @pgaudet as marc does not seem to have a GO git hub alias).
He might have some insight on this topic....

**Comment by paolaroncaglia** [comment]
@marcfeuermann

**Comment by ValWood** [comment]
Thanks paola
I can never work out why everyone isn't in this list?
https://github.com/orgs/geneontology/people

**Comment by paolaroncaglia** [comment]
That's a great question. I have absolutely no idea. @cmungall , @mcourtot ?

**Comment by dosumis** [comment]
They can easily be invited by anyone with admin privileges.  Looks like Marc has already been invited.

**Comment by mcourtot** [comment]
@paolaroncaglia: I upgraded you to owner as well.

**Comment by dosumis** [comment]
Changed defs as specified above, following [agreement by GO editors](http://gocwiki.geneontology.org/index.php/Ontology_meeting_2016-04-21#Follow-up:_vesicular_transport)

**Comment by pgaudet** [comment]
@dosumis @ValWood @paolaroncaglia @tberardini 
What remains to be done here?

**Comment by paolaroncaglia** [comment]
@pgaudet 
I think this is for @dosumis and @ValWood to address. Looks like @dosumis made some edits based on a consensus agreement, so perhaps this ticket can be closed? And a new one opened if there are (still) specific issues to address. Thanks.

**Comment by pgaudet** [comment]
Thanks @paolaroncaglia
I see the edits, I'll close the ticket.
