### ISSUE TITLE
Easy NTR: positive/negative terms for GO:0044537 regulation of circulating fibrinogen levels

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12313]
Please could you create the positive and negative regulation terms for GO:0044537 regulation of circulating fibrinogen levels.

For annotation of PMID:20570858

Please add the references
GOC:rph
GOC:BHF
GOC:BHF_miRNA

Thanks,
Rachael.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061754
+name: negative regulation of circulating fibrinogen levels
+namespace: biological_process
+def: "Any process that reduces the quantity of fibrinogen circulating in the bloodstream." [GOC:BHF, GOC:BHF_miRNA, GOC:rph, PMID:20570858]
+is_a: GO:0044537 ! regulation of circulating fibrinogen levels
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates OBA:0000061 ! circulating fibrinogen levels
+created_by: dph
+creation_date: 2016-02-29T16:19:09Z
+
+[Term]
+id: GO:0061755
+name: positive regulation of circulating fibrinogen levels
+namespace: biological_process
+def: "Any process that increases the quantity of fibrinogen circulating in the bloodstream." [GOC:bf, GOC:BHF, GOC:BHF_miRNA, PMID:20570858]
+is_a: GO:0044537 ! regulation of circulating fibrinogen levels
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates OBA:0000061 ! circulating fibrinogen levels
+created_by: dph
+creation_date: 2016-02-29T16:26:49Z
