### ISSUE TITLE
NTR: alpha-ketoglutarate reductase activity

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#12314]
Hi,

Here is some background for the NTR

In the following paper:

Saccharomyces cerevisiae Forms D-2-Hydroxyglutarate and Couples its Degradation to D-Lactate Formation via a Cytosolic Transhydrogenase. PMID: 26774271

the yeast gene DLD2, is demonstrated to function as an D-2-hydroxyglutarate (D-2HG) dehydrogenase, converting D-2HG to 2-oxoglutarate (aka alpha-ketoglutarate). In GO there is a term for 2-hydroxyglutarate dehydrogenase activity (GO:0047545) with synonym alpha-ketoglutarate reductase activity (important for what follows), and a term for (R)-2-hydroxyglutarate dehydrogenase activity (GO:0051990), a better fit since its specific for the R/D enantiomer. 

Later in the paper they show that in yeast both SER3 and SER33 function as alpha-ketoglutarate reductases, catalyzing the conversion of alpha-ketoglutarate to D-2HG. This is the reverse reaction to the one described above. I posted this scenario to go-discuss and was advised to request a new term “alpha-ketoglutarate reductase activity” and request the removal of this string as exact synonym for 2-hydroxyglutarate dehydrogenase activity (GO:0047545), as this is the reverse activity.  I have attached figure 13 from the paper, the proposed yeast metabolic network involving these genes, in case this helps
![becker-kettern et al 2016 26774271](https://cloud.githubusercontent.com/assets/12737663/13413466/85c1836a-deff-11e5-9942-979614440003.png)

I would therefore like to request the following new function term:

Term: alpha-ketoglutarate reductase activity

Definition: Catalysis of the reaction: alpha-ketoglutarate + NADH = D-2-hydroxyglutarate + NAD+

Synonyms: 2-oxoglutarate reductase activity, 2-ketoglutarate reductase activity; D-2HG reductase activity

Instance of GO:0016657 oxidoreductase activity, acting on NAD(P)H, nitrogenous group as acceptor

Definition reference: PMID: 26774271

E.C. number: I cannot find the appropriate EC number sign ExPASy

In addition, please remove the exact synonym “alpha-ketoglutarate reductase activity” from term GO:0047545 2-hydroxyglutarate dehydrogenase activity, as this term describes the reverse activity.

Cheers,
Rob

**Comment by ukemi** [comment]
Hi Rob,

We discussed this on a recent call and decided to keep the term representing the union of the forward and reverse reactions. So what I have done is made two separate terms for each of the forward and reverse reactions. Here are the new terms:

 [Term]
+id: GO:0061758
+name: 2-hydroxyglutarate dehydrogenase activity, forward reaction
+namespace: molecular_function
+def: "Catalysis of the reaction: (S)-2-hydroxyglutarate + acceptor -> 2-oxoglutarate + reduced acceptor." [EC:1.1.99.2, GOC:dph, MetaCyc:2-HYDROXYGLUTARATE-DEHYDROGENASE-RXN]
+synonym: "alpha-ketoglutarate reductase activity, reverse reaction" EXACT [GOC:dph]
+xref: Reactome:REACT_24926 "(S)-2-hydroxyglutarate + FAD => 2-oxoglutarate + FADH2, Homo sapiens"
+xref: RHEA:21253
+is_a: GO:0047545 ! 2-hydroxyglutarate dehydrogenase activity
+created_by: dph
+creation_date: 2016-03-07T08:28:58Z
+
+[Term]
+id: GO:0061759
+name: alpha-ketoglutarate reductase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: 2-oxoglutarate + reduced acceptor -> (S)-2-hydroxyglutarate + acceptor." [EC:1.1.99.2, GOC:dph, PMID:26774271]
+synonym: "2-hydroxyglutarate dehydrogenase activity, reverse reaction" EXACT [GOC:dph]
+synonym: "2-ketoglutarate reductase activity" RELATED [GOC:dph]
+synonym: "2-oxoglutarate reductase activity" RELATED [GOC:dph]
+synonym: "D-2HG reductase activity" RELATED [GOC:dph]
+xref: RHEA:21254
+is_a: GO:0047545 ! 2-hydroxyglutarate dehydrogenase activity
+created_by: dph
+creation_date: 2016-03-07T08:38:57Z
