### ISSUE TITLE
Add synonym to 'macroautophagy'?

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12319]
I can't remember if we discussed this already. Would everyone agree if I added 'autophagy' as a BROAD synonym of 'macroautophagy', as that seems to be a frequent generalisation in the literature? (Prompted from PMID: 25236395 "...such as macroautophagy (hereafter referred to as autophagy)".) 

Note that 'macroautophagy' already has an exact synonym 'non-specific autophagy', so we wouldn't be contradicting ourselves.

Assigning to David H for confirmation. Feel free to assign back to me to do the edit.

**Comment by ukemi** [comment]
I have seen this a lot too. I think it would be ok to add as you suggest.

**Comment by paolaroncaglia** [comment]
Done.
