### ISSUE TITLE
Request for term combining innate immune response and defense response to fungus

### ISSUE THREAD

**Issue by aholmesebi** [geneontology/go-ontology#12328]
To simplify annotation with respect to PMID:22470487 (and similar) I'd like a process term combining;

GO:0045087 - innate immune response
and the multi-organismal term
GO:0050832 - defense response to fungus

along the lines of 'innate immune response in response to fungus' so I can better capture the specific nature of the immune response to the fungus D. coniospora infection without a clumsy melding of wholly separate ontology terms. Further to this, creating regulation terms for any new term would also be useful.

-Alex Holmes

**Comment by ukemi** [comment]
In parallel to 'antifungal humoral response', how about 'antifungal innate immune response': An defense response against a fungus mediated through an innate immune response. An innate immune response is mediated by germline encoded components that directly recognize components of potential pathogens.

Let me know if this works for you I will add it. Then I can add the regulation terms via TermGenie.

-D

**Comment by aholmesebi** [comment]
Yes, that sounds good to me.

Thanks

Alex

On 07/03/2016 12:48, ukemi wrote:
>
> In parallel to 'antifungal humoral response', how about 'antifungal 
> innate immune response': An defense response against a fungus mediated 
> through an innate immune response. An innate immune response is 
> mediated by germline encoded components that directly recognize 
> components of potential pathogens.
>
> Let me know if this works for you I will add it. Then I can add the 
> regulation terms via TermGenie.
>
> -D
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12328#issuecomment-193236247>.
>

-- 
Alex Holmes
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
01223 494260

**Comment by ukemi** [comment]
[Term]
+id: GO:0061760
+name: antifungal innate immune response
+namespace: biological_process
+def: "An defense response against a fungus mediated through an innate immune response. An innate immune response is mediated by germline encoded components that directly recognize components of potential pathogens." [GOC:dph, PMID:22470487]
+is_a: GO:0045087 ! innate immune response
+is_a: GO:0050832 ! defense response to fungus
+created_by: dph
+creation_date: 2016-03-07T08:53:08Z
