### ISSUE TITLE
NTR: carcinine transport terms

### ISSUE THREAD

**Issue by magrane** [geneontology/go-ontology#12320]
Hi,

Can the following terms be created please?

Ontology: molecular_function
Name: carcinine transporter activity

Ontology: biological process: 
Name: carcinine uptake

Background: Carcinine is an inactive metabolite of histamine which is a neurotransmitter in Drosophila photoreceptor neurons. Released histamine is taken up by glia and converted to carcinine which is then transported back to the photoreceptors from the surrounding glia.

PMIDs: 26653853 & 26713872

Thanks,
Michele

**Comment by ukemi** [comment]
Hi Michele,
I don't see the chemical in ChEBI. I am having Harold double check. If it is not there, we will request it and the we can make these terms using termgenie.
-D

**Comment by hdrabkin** [comment]
Requested from CHEBI: ChEBI identifier CHEBI:131429.

**Comment by magrane** [comment]
Hi David, 

Now that Harold has got a ChEBI identifier for the chemical, do I need to make these terms myself using TermGenie?

Thanks,
Michele

**Comment by hdrabkin** [comment]
Hi Michele
For the import term, I have a bunch of options
chemical_import
 chemical_import_into
 import_across_membrane
 import_across_plasma_membrane
 import_into_cell

Which do you think better fits ?

**Comment by magrane** [comment]
Hi Harold,

I'm not sure which is most appropriate. The protein for which I requested the terms is a receptor located in the plasma membrane of photoreceptor cells and it takes up carnitine into the photoreceptor cells. Does that help?

Michele

**Comment by dosumis** [comment]
> The protein for which I requested the terms is a receptor located in the plasma membrane of photoreceptor cells and it takes up carnitine into the photoreceptor cells. 

Should be import across plasma membrane then (subclass of import into cell)

**Comment by ukemi** [comment]
Hi Michele,

Although the chemical is visible on the ChEBI browser, we still can't use in in the TG template. We assume it will be available soon. Once it does we can go ahead and make the terms. If you need them right away, we can make them by hand and add the logical def later. Let me know what works best for you. Sorry this has taken so long.

-D

**Comment by magrane** [comment]
Hi David,

No rush - I can wait until you've created the terms.

Michele

**Comment by ukemi** [comment]
Hi Michele,

They are finally in.

[Term]
id: GO:1905131
name: carcinine transmembrane transporter activity
namespace: molecular_function
def: "Catalysis of the transfer of carcinine from one side of the membrane to the other." [GO_REF:0000070, GOC:dph, GOC:TermGenie, PMID:26653853, PMID:26713872]
is_a: GO:0042887 {is_inferred="true"} ! amide transmembrane transporter activity
is_a: GO:0072349 {is_inferred="true"} ! modified amino acid transmembrane transporter activity
is_a: GO:1901474 {is_inferred="true"} ! azole transmembrane transporter activity
intersection_of: GO:0022857 ! transmembrane transporter activity
intersection_of: transports_or_maintains_localization_of CHEBI:131429 ! carcinine
relationship: transports_or_maintains_localization_of CHEBI:131429 {is_inferred="true"} ! carcinine
created_by: dph
creation_date: 2016-04-12T15:18:25Z

[Term]
id: GO:1905130
name: carcinine import across plasma membrane
namespace: biological_process
def: "The directed movement of carcinine from outside of a cell into the cytoplasmic compartment." [GO_REF:0000075, GOC:dph, GOC:TermGenie, PMID:26653853, PMID:26713872]
is_a: GO:0042886 {is_inferred="true"} ! amide transport
is_a: GO:0045117 {is_inferred="true"} ! azole transport
is_a: GO:0072337 {is_inferred="true"} ! modified amino acid transport
is_a: GO:0098739 {is_inferred="true"} ! import across plasma membrane
intersection_of: GO:0006810 ! transport
intersection_of: has_target_end_location GO:0005829 ! cytosol
intersection_of: has_target_start_location GO:0005576 ! extracellular region
intersection_of: imports CHEBI:131429 ! carcinine
intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
relationship: has_target_end_location GO:0005829 {is_inferred="true"} ! cytosol
relationship: has_target_start_location GO:0005576 {is_inferred="true"} ! extracellular region
relationship: imports CHEBI:131429 {is_inferred="true"} ! carcinine
relationship: results_in_transport_across GO:0005886 {is_inferred="true"} ! plasma membrane
created_by: dph
creation_date: 2016-04-12T15:15:18Z
