### ISSUE TITLE
regulation of metalloenzyme activity

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12322]
It looks odd to have the following 6 terms, without a 'metalloenzyme activity' term itself:

regulation of metalloenzyme activity ; GO:0048552
negative regulation of metalloenzyme activity ; GO:0048553
positive regulation of metalloenzyme activity ; GO:0048554

metalloenzyme regulator activity ; GO:0010576
metalloenzyme inhibitor activity ; GO:0048551
metalloenzyme activator activity ; GO:0010577

Presumably a metalloenzyme term is describing a mechanism, but so are lots of existing terms that describe metalloenzymes:
metallopeptidase activity ; GO:0008237
metalloexopeptidase activity ; GO:0008235 etc

The regulator terms also aren't currently linked to the regulation terms.

So this bit of the ontology needs a bit of tidying. Putting it here to keep track of.
Thanks!

**Comment by ValWood** [comment]
Ooh they are horrible terms....

https://github.com/geneontology/go-ontology/issues/12282
How would you even *know*

**Comment by ValWood** [comment]
With 26 EXP annotation 7 to the dame GP!

When in actual fact, MOST enzymes are probably metalloenzymes.... not very consistent!

**Comment by Antonialock** [comment]
> #12282 How would you even _know_

I was just about to reference that ticket!

**Comment by dosumis** [comment]
> MOST enzymes are probably metalloenzymes

Surely depends on def.  Less if def requires that the metal be a cofactor in the reaction?

**Comment by ValWood** [comment]
OK many. Not 26. I just think we are making things really hard for ourselves here...

**Comment by dosumis** [comment]
> I just think we are making things really hard for ourselves here...

You're probably right.  If its unsustainable to classify enzymes under metalloenzyme then we probably shouldn't have the terms (regulatory or otherwise). Whether it is sustainable probably depends on whether we can pull this information from elsewhere, e.g EC.

**Comment by ukemi** [comment]
I think that the def should require the metal ion be bound to the enzyme of at least be in a prosthetic group that is bound to the enzyme. But I tend to agree with Val that we are making things difficult because a generic metalloenzyme term will most likely be way under-annotated. However, I do think it is important to have the metallopeptidase/protease terms because they are so important in cancer research. How complete do we need to be with classification?

**Comment by dosumis** [comment]
Don't see a problem with having specific terms, even if the most general is not sustainable, especially where they are covered by EC.  These two look like they cover metallopeptidases:

http://www.chem.qmul.ac.uk/iubmb/enzyme/EC3/4/24/ http://www.chem.qmul.ac.uk/iubmb/enzyme/EC3/4/17/  

Qu

**Comment by RLovering** [comment]
I guess this is where the IEA data can help curators decide which 'regulation of ?? activity' to choose

**Comment by ukemi** [comment]
Does it make sense to merge the metalloenzyme terms into parents and make them narrow synonyms? Obsoleting would require re-annotation. I agree with David and Val that classifying gene products under a metalloenzyme term is unsustainable. This would make the current structure for the peptidase terms correct and meaningful.

**Comment by ukemi** [comment]
If I don't hear any objections, I will merge the metalloenzyme terms into their parents next week.

**Comment by ukemi** [comment]
Terms merged.
