### ISSUE TITLE
parentage for GO:0005971 ribonucleoside-diphosphate reductase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12325]
According to PMID:11719458 the RNR complex with RRM2B is activated under DNA damage conditions and translocated to the nucleus. Although I can't proof it carries out ribonucleoside-diphosphate reductase activity in the nucleus it's its main location under damage-induced conditions. The other version, containing RRM2, is only found cytosolically.

Therefore, the parentage may need to be amended to 'cell'.

Birgit

**Comment by deustp01** [comment]
Here's some evidence (nuclear localization of a protein overexpressed from a transfected construct) that the ribonucleotide reductase variant that feeds DNA repair is nuclear: PMID:10716435

**Comment by ukemi** [comment]
Right now the complex is capable of the activity and is a cytoplasmic part. If you think that both forms of the enzyme are capable of the activity, I think we need to relax this constraint and indeed make it a part of  'cell' instead. If you think that only the nuclear form is capable of the activity then we have to remove the capable_of relation to the activity if this complex represents both the cytoplasmic and nuclear forms.

**Comment by bmeldal** [comment]
I definitely think it should be part_of 'cell'.
I don't follow your second argument about the capable_of link, I think that's fine for both forms.

**Comment by deustp01** [comment]
Evidence quality is an issue here. There's some data to say that a form of ribonucleotide reductase can get into the interphase nucleus under some conditions in some cell types, and the substrates and cofactors needed for activity can enter the nucleus, and there's no evidence that anything additional is required for enzyme activity, so it looks like there's nothing to prevent enzyme activity in the nucleus. Is that capable_of? Peter Reichard (Peter.Reichard@ki.se) has done more work on this group of enzymes and their variants than anyone else. Perhaps ask him for an opinion?

**Comment by bmeldal** [comment]
Should David or I email Peter?

**Comment by ukemi** [comment]
Based on Peter's last post, we can just keep the capable_of. That means that if we find a complex that can't carry out the activity, it shouldn't be annotated to this term.

**Comment by bmeldal** [comment]
Thanks. We'll leave the distinguished Swedish professor in peace :)

**Comment by ukemi** [comment]
Hi Birgit,

For now, I am going to relax the restriction and make it part of intracellular as you suggest. It isn't wrong.Let me know if you need anything else.
-D

**Comment by bmeldal** [comment]
Thanks, David.
Peter emailed Peter Reichard, maybe we get additional info at some point.

**Comment by ukemi** [comment]
After expert input, I have moved this back to being a part of the cytosol.

**Comment by deustp01** [comment]
To complete the discussion, here is Peter Reichard's reply to our question about the subcellular location of eukaryotic ribonucleotide reductase:

In my opinion the situation is the following: deoxyribonucleotides are synthesized in the cytosol by a combination of the two RNR subunits (R1 + R2 or p53R2 in higher organisms or R1 + R2+R4 in yeast). In higher organisms all the subunits are localized in the cytosol whereas in yeasts R2+R4 are intranuclear outside S phase. After DNA damage the yeast small subunits (R2+R4) are transferred to the cytosol to permit synthesis of dNTPs for DNA repair.
In all Eukaryotes the nuclear envelope does not represent a barrier for the flow of dNTPs. 
We have addressed these issues in mammalian cells in a paper published in PNAS in 2008 (Pontarin et al, 105: 17801-06) where we employed three independent approaches to carefully investigate the location of RNR subunits under normal conditions or after DNA damage. Firstly, cell fractionation and quantitation of R1, R2 and p53R2 in nuclear and cytosolic fractions with specific antibodies. Secondly, we used immunofluorescence for the localization of the endogenous enzyme subunits during the cell cycle and after DNA damage. Thirdly, we used expression of fluorescently-tagged subunits to study their localization by fluorescence microscopy. With all methods we could only observe a cytosolic localization of the three RNR subunits.
In the same paper you may find a discussion of different models in the literature.

**Comment by bmeldal** [comment]
I looked at the papers cited by Peter R and changed all the complex annotations to 'cytosol'. Glad Peter d'E asked :)
