### ISSUE TITLE
'multicellular organism development' is almost childless!

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12337]
'multicellular organism development' has  only three subclasses:

'embryo sac development'
'gametophyte development'
'pollen development'

Judging from ETINES file it used to have a few more:

GO:2000797	regulation of amniotic stem cell differentiation	GO:2000026	regulation of multicellular organismal development
GO:0045682	regulation of epidermis development	GO:2000026	regulation of multicellular organismal development
GO:0048509	regulation of meristem development	GO:2000026	regulation of multicellular organismal development

Presumably should be near the top of the development hierarchy.  Do we even use development  for unicellular species?

**Comment by ukemi** [comment]
Off the top of my head, yeast mating type switching and shmoo formation would be two examples of single-cell developmental processes.

**Comment by dosumis** [comment]
Presumably not this shmoo ![shmoo](http://i1.wp.com/www.alteredego.org/wp-content/uploads/2013/12/The_Shmoo_by_zombiegoon.jpg?w=813)

**Comment by mah11** [comment]
no, but named after it

**Comment by dosumis** [comment]
ahhh - no found it in GO synonyms (was also once a GO term).


Back to the general question:

label "multicellular organism development"^^string
comment "Note that this term was 'developmental process'."^^string
definition "The biological process whose specific outcome is the progression of a multicellular organism over time from an initial condition (e.g. a zygote or a young adult) to a later condition (e.g. a multicellular animal or an aged adult)."^^string

I'm now wondering if applies only to development of a whole organism -  not its parts?  Still needs more subclasses if that'd the case.

* embryo development (currently has a part of relationship to 'multicellular organism development'); 
* entry into diapause
* metamorphosis
* moulting cycle
.... almost certainly more.

**Comment by ValWood** [comment]
1.
cell ageing  is not currently  a cellular_developmental process (although it is  a developmental process, single-organism cellular process, and single organism developmental process)

2. I don't understand the difference between
GO:0048869
Name	cellular developmental process
Definition	A biological process whose specific outcome is the progression of a cell over time from an initial condition to a later condition.
and

cell development
Definition	The process whose specific outcome is the progression of the cell over time, from its formation to the mature structure. Cell development does not include the steps involved in committing a cell to a specific fate.

or why some yeast genes are annotated to one and some to both....

**Comment by dosumis** [comment]
> cell ageing is not currently a cellular_developmental process

OK. Looks like it should be.  If not objections, (@ukemi - any comments?) I will fix.

This doesn't solve the primary issue addressed by this ticket though.  @ukemi - can you comment on whether the intention is that this term applies only to development of a whole organism. If so, it should then be possible to fix (unless we decide that relations like results_in_development_of chain over 'part of').  Still wonder how useful this class is @cmungall - any opinions?

**Comment by ukemi** [comment]
I believe it does refer to the whole organism. I have never been entirely comfortable with classes like this in the development branch. This goes for embryo etc terms.

**Comment by ukemi** [comment]
Like the metalloenzyme term, I think it is very difficult to make these comprehensive.

**Comment by ukemi** [comment]
It seems like it should be. I don't like the definition of 'cellular developmental process'. From its is_a_complete definition xref and my recollection, this term was meant to cover any developmental process that occurs at the cellular level allowing us to give otherwise is_a orphans parents.  It was not meant to be THE process of a cell progressing from an initial condition to a mature state. That is 'cell development'.

**Comment by dosumis** [comment]
Any suggestions for how to define 'at the cellular level' in this case?

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/13776875/6b854a26-eaa4-11e5-99d6-2cafba5d8d16.png)

![image](https://cloud.githubusercontent.com/assets/112839/13776941/d1d3b2d6-eaa4-11e5-9675-fc5e739fe53e.png)

**Comment by dosumis** [comment]
Also added 'cell aging' is_a 'cellular developmental process'
