### ISSUE TITLE
receptor terms incorrectly under 'receptor signaling protein activity'

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12339]
As just discussed in the office, these receptor terms shouldn't be under 'receptor signaling protein activity ; GO:0005057' :

ethylene receptor activity ; GO:0038199
neurotransmitter receptor activity involved in regulation of postsynaptic cytosolic calcium levels ; GO:0099583
neurotransmitter receptor activity involved in regulation of presynaptic cytosolic calcium levels ; GO:0099582

@dosumis is going to trace the inferences- probably stems back to cytosolic calcium signaling/homeostasis terms.

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/13676663/a49c03a0-e6de-11e5-9271-ae1dc5433745.png)

We need an OBA term for cytosolic calcium ion concentration - rather than using 'occurs in'.  In fact, we already have an OBA tissue for this: https://github.com/obophenotype/bio-attribute-ontology/issues/10

**Comment by dosumis** [comment]
Second (more general problem)  comes from part relationship of activity to sig pathway, which is defined as intracellular

![image](https://cloud.githubusercontent.com/assets/112839/13676796/29385f78-e6df-11e5-9e53-eb4512d66fe7.png)

@rebeccafoulger - Any suggestion for how to fix this?

**Comment by rebeccafoulger** [comment]
‘receptor signaling protein activity’ Equivalent to ‘signal transducer activity’ and (‘occurs in’ some intracellular) is too broad. 

Need something along lines of:
preceded_by: signaling receptor activity
or
causally_downstream_of: signaling receptor activity
or
regulated_by: signaling receptor activity (can be direct or indirect)

any of those suitable for MF classification?

NB: Note to myself to remove 'receptor agonist activity ; GO:0048018' from under 'signal transducer activity'- shouldn't be there.

**Comment by dosumis** [comment]
> ‘receptor signaling protein activity’ Equivalent to ‘signal transducer activity’ and (‘occurs in’ some intracellular) is too broad.

OK.  Can see that now - has to encompass things downstream of intracellular receptors.

'regulated by' makes sense to me, but we don't currently have any axiomatisation to support it: would require extensive addition of regulates/directly regulates relationships in this branch.  If we change, we'll need to comb through inferred subclasses and either assert or axiomatise.

**Comment by dosumis** [comment]
Thinking about this some more, we can only crudely axiomatise.  For cases where a signal transducer is downstream of different receptors under different circumstances (perhaps we should never assume otherwise?) we can only use the most general axiom 'regulated by' some 'signaling receptor activity' - not specifying which.

**Comment by dosumis** [comment]
Fixed the inference through reg cytosolic Ca2+ concentration by switching to OBA-based logical def.

**Comment by dosumis** [comment]
Have deleted logical def:

‘receptor signaling protein activity’ Equivalent to ‘signal transducer activity’ and (‘occurs in’ some intracellular)

+ cleaned up classification underneath

Holding off on adding replacement logical def.

@cmungall  - any opinion on using:

EquivalentTo: molecular_function 
that (regulated_by some 'signaling receptor activity')
and (part_of some 'signal transduction')

Not entirely confident of quantification on regulated_by in this case.
