### ISSUE TITLE
New GOCHE terms needed for molecule with androgen/estrogen role

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12330]
CHEBI has the role terms and the 'has role' axioms.  We just need the bridging classes.  Not sure on the SOP for this.

These are needed to fix many ETINEs:

GO:0061370  testosterone biosynthetic process   GO:0006702  androgen biosynthetic process   1   ?  
GO:0035936  testosterone secretion  GO:0035935  androgen secretion  1   ?  
GO:0035941  androstenedione secretion   GO:0035935  androgen secretion  1   ?  
GO:0035942  dehydroepiandrosterone secretion    GO:0035935  androgen secretion  1   ?  
GO:2000225  negative regulation of testosterone biosynthetic process    GO:2000180  negative regulation of androgen biosynthetic process    1  
GO:2000838  negative regulation of androstenedione secretion    GO:2000835  negative regulation of androgen secretion   1  
GO:2000841  negative regulation of dehydroepiandrosterone secretion GO:2000835  negative regulation of androgen secretion   1  
GO:2000844  negative regulation of testosterone secretion   GO:2000835  negative regulation of androgen secretion   1  
GO:2000180  negative regulation of androgen biosynthetic process    GO:0010894  negative regulation of steroid biosynthetic process  
GO:2000824  negative regulation of androgen receptor activity   GO:0000122  negative regulation of transcription from RNA polymerase II promoter  
GO:2000839  positive regulation of androstenedione secretion    GO:2000836  positive regulation of androgen secretion   1  
GO:2000842  positive regulation of dehydroepiandrosterone secretion GO:2000836  positive regulation of androgen secretion   1  
GO:2000845  positive regulation of testosterone secretion   GO:2000836  positive regulation of androgen secretion   1  
GO:0060520  activation of prostate induction by androgen receptor signaling pathway GO:0010455  positive regulation of cell fate commitment  
GO:2000825  positive regulation of androgen receptor activity   GO:0045944  positive regulation of transcription from RNA polymerase II promoter  
GO:2000837  regulation of androstenedione secretion GO:2000834  regulation of androgen secretion  
GO:2000840  regulation of dehydroepiandrosterone secretion  GO:2000834  regulation of androgen secretion  
GO:2000843  regulation of testosterone secretion    GO:2000834  regulation of androgen secretion  
GO:0008209  androgen metabolic process  GO:0044763  single-organism cellular process  
GO:0005497  androgen binding    GO:0005496  steroid binding ?  
GO:0006702  androgen biosynthetic process   GO:0006694  steroid biosynthetic process    ?  
GO:0006710  androgen catabolic process  GO:0006706  steroid catabolic process   ?  
GO:0008209  androgen metabolic process  GO:0008202  steroid metabolic process   ?

**Comment by cmungall** [comment]
I will rewrite this to use dosdps

**Comment by balhoff** [comment]
@cmungall this seems to be working now. Not sure it needs to use DOS-DP. Can we close?

**Comment by pgaudet** [comment]
@cmungall reopen if needed.
