### ISSUE TITLE
TPV: meiotic terms under mitotic terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12333]
see fig

![tpv](https://cloud.githubusercontent.com/assets/7359272/13610136/294e8faa-e554-11e5-8ee3-8f6472cce638.jpg)

I think it originates at GO:0044784 the metaphase anaphase/anaphase tranition term is under the  regulation of mitotic chromatid separation

**Comment by ukemi** [comment]
Yup. I think you are right. I think GO:0044784 the metaphase anaphase/anaphase transition of cell cycle should be removed and GO:0007091 metaphase/anaphase transition of mitotic cell cycle should be the child instead.

**Comment by dosumis** [comment]
Should add disjoint to detect these in future:

'meiotic cell cycle process' disjointWith 'mitotic cell cycle process'
