### ISSUE TITLE
methyladenosine dioxygenase activity

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12336]
From Sylvain Poux:

I just submitted 2 new GO terms for mRNA N1- and N6-demethylase activities (GO:1990930 and GO:1990931) and I would request a modification of definition for. GO:0043734. This remove RNA demethylase activity from its definition. The reason is that it is preferable to not mix DNA and RNA activities within the same term, since both activities have completely different biological consequences

GO:0043734; F:DNA-N1-methyladenosine dioxygenase activity
Catalysis of the oxidative demethylation of N1-methyladenosine and N3-methylcytosine in DNA, with concomitant decarboxylation of 2-oxoglutarate and releases oxidized methyl group on N1-methyladenosine and N3-methylcytosine as formaldehyde. 

cc @dosumis, @ukemi

**Comment by ukemi** [comment]
Definition restricted as suggested above.
