### ISSUE TITLE
OTR: GO:0019835 cytolysis

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12343]
The issue of ‘cytolysis’ was brought up before, and just came back again following the ETINE work: @dosumis  

GO:0042268  regulation of cytolysis GO:0010941  regulation of cell death    

In short, it is ok for the link not to be entailed any longer, and I marked it as ‘delete’. 

@addiehl
In more detail: ‘cytolysis’ used to be under ‘cell death’ but was removed from under there in 2013, as part of the viral work.
‘Cytolysis’, describing the explosion of a cell as an uncontrollable reaction to osmotic stress (https://en.wikipedia.org/wiki/Cytolysis), is a phenotype rather than a process. As such, we shouldn’t have it in GO, and its current direct experimental annotations are suspicious. The lexical problem is that often ‘cytolysis’ stands to mean ‘cell killing by cytolysis’. In fact, we have GO:0051715 ‘cytolysis in other organism’ which means exactly that (“The killing by an organism of a cell in another organism by means of the rupture of cell membranes and the loss of cytoplasm.”). The ambiguity is confirmed when I look at the first of the papers supporting  annotations to ‘cytolysis’ in QuickGO, http://europepmc.org/abstract/MED/25876762, describing features of antimicrobial peptides in fish - it’s the fish peptides that are annotated to cytolysis.

I propose to obsolete ‘cytolysis’ per se, but to keep its children. However:

‘cytolysis’ has two is_a children: ‘autolysis’ and ‘cytolysis in other organism’.

‘autolysis’ is “The spontaneous death by lysis of bacteria in response to environmental conditions.”. It has 14 manual annotations. 2 are CACAO, 4 are EcoliWiki. @jimhu-tamu , is autolysis a true process in Bacteria? Can it be considered a form of programmed cell death? If so, the term and the bacterial annotations can stay, but ‘autolysis’ should be moved under ‘programmed cell death’ and be given a taxon constraints for bacteria. 
‘autolysis’ also has 7 ASPGD annotations to fungal proteins that should presumably be moved to a ‘cell killing’ term. Should this be ‘cell killing [of bacteria] by autolysis? Is that any different than ‘cytolysis in other organism’? (I’ll email someone at ASPGD to look into this)
‘autolysis’ even has a UniProt mouse annotation, presumably same case as the fungal one? @mcourtot 

‘cytolysis in other organism’ has both parents ‘cytolysis’ and ‘killing of cells of other organism’. I suggest to remove the is_a link to ‘cytolysis’. 

We need to clarify these issues, then we can make useful suggestions to rehouse annotations to cytolysis and its regulation terms.

Thank you all,
Paola

**Comment by addiehl** [comment]
I would start by saying that the Wikipedia article on cytolysis is a bit simplistic.  The membrane attack complex (MAC) of the complement cascade seemingly can cause cytolysis, (see another Wikipedia article, https://en.wikipedia.org/wiki/Complement_membrane_attack_complex for a pretty picture of this), as can perhaps the perforin protein released by cytotoxic T cells and NK cells, though the mechanism of action of perforin in causing cell death is probably more complex and may vary depending on the target cell.  Also, the processes of complement system-driven cytolysis and perforin-driven cytolysis are often directed against cells of the same organism, "self" cells.  Thus 'cytolysis' in this instance is not a 'phenotype', but rather an active process, and it is not ‘cytolysis in other organism’ or 'autolysis' either.

The best solution might be renaming or replacing 'cytolysis' with something like 'induction of cytolysis' which can function for the MAC and its components (C9 principally) and perforin if needed.
-- Alex

**Comment by jimhu-tamu** [comment]
I think we need to reexamine the CACAO and EcoliWiki annotations. Some of those are probably based on phenotypes that are the consequence of cell remodeling activities losing their regulation. Which would make them phenotypes.

However, although those annotations may need to be changed or deleted, there are cases where cell death is programmed as part of a normal biological process. The most obvious one I can think of off the top of my head is when the mother cell lyses to release the spore in endospore formation (e.g. in Bacillus).

Here is one review: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC99002/

Here is one about autolysis in biofilm formation: http://www.ncbi.nlm.nih.gov/pubmed/26811896

So I would say it's a true process and a form of programmed cell death.

**Comment by paolaroncaglia** [comment]
@addiehl Thanks Alex for your quick feedback. I can't look into the details you provided right now, but I certainly will. One word though: I'm really not in favour of 'induction' terms; I know they have a special meaning in immunology, but generally speaking, we noticed a great deal of confusion during the apoptosis project in how 'apoptosis' and 'induction of apoptosis' were used to annotate - induction sat under regulation, but most of the annotations meant the apoptotic process itself.

**Comment by paolaroncaglia** [comment]
@jimhu-tamu Thanks Jim, that's very helpful. I'll look into better defining 'autolysis' including definition gloss or def. comment and the references you provided. Could you please make a note to revise the CACAO and EcoliWiki annotations? Is there any ticketing system where we should record this - if yes,  could you take care of that please?

Thanks.

**Comment by addiehl** [comment]
I agree that 'induction of cytolysis' is imperfect; I was trying to come up with something that sounded like an active process, if the fear is that 'cytolysis' really a phenotype.  Personally, I would be happy to stick with 'cytolysis' or perhaps 'cytolytic process' or 'cell killing by cytolysis', with an appropriate definition.

**Comment by paolaroncaglia** [comment]
For ETINEs work,
made GO:0042268 regulation of cytolysis is_a GO:0050794 regulation of cellular process (rather than existing GO:0010941 regulation of cell death)

**Comment by paolaroncaglia** [comment]
Let’s start from the bottom of the node and fix ‘autolysis’. Two parts here:

1) Ontology
Autolysis occurs in filamentous fungi as well as bacteria. Therefore, I suggest the following changes for ‘autolysis’: 
- Edit def to: “A programmed cell death process occurring in bacteria and filamentous fungi and leading to spontaneous death by lysis. Examples are lysis of the mother cell during sporulation of Bacillus subtilis and self-degradation of fungal cells in Aspergillus nidulans. Autolysis is also involved in bacterial biofilm formation.”
- Add dbxrefs: GOC:jh2, PMID:10974124, PMID:19286987, PMID:26811896
- Change placement: move away from under ‘cytolysis’ and make is_a ‘programmed cell death’
- Add taxon rule: never in Metazoa

I’ll implement unless @jimhu-tamu and/or @addiehl have any comment.

2) Annotations
- @jimhu-tamu, in view of your comment above, please reexamine the CACAO and EcoliWiki annotations to ‘autolysis’.
- @melanie, there’s a UniProt annotation to mouse p94/calpain 3(Q64691) that should be re-housed elsewhere, presumably under GO:1990092 calcium-dependent self proteolysis, as ‘autolysis’ in the annotated publication denotes self-digestion of *proteins*. (In fact, the reference for calcium-dependent self proteolysis is the same!) Could you please check who annotated that, and have it fixed, thanks.

**Comment by melanie** [comment]
I believe you're looking for @mcourtot ;)

**Comment by paolaroncaglia** [comment]
Of course, my apologies! Thanks...

**Comment by paolaroncaglia** [comment]
@mcourtot : there’s a UniProt annotation to 'autolysis' for mouse p94/calpain 3(Q64691) that should be re-housed elsewhere, presumably under GO:1990092 calcium-dependent self proteolysis, as ‘autolysis’ in the annotated publication denotes self-digestion of proteins. (In fact, the reference for calcium-dependent self proteolysis is the same!) Could you please check who annotated that, and have it fixed, thanks.

**Comment by paolaroncaglia** [comment]
Edited 'autolysis' as above.

**Comment by paolaroncaglia** [comment]
I wrapped up a description of issues and suggestions to fix the 'cytolysis' branch in a new ticket:
https://github.com/geneontology/go-ontology/issues/13041
Closing this one now.
