### ISSUE TITLE
OTR: GO:1990009 retinal cell apoptotic process

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12342]
Digging out pending apoptosis-related to-do items. Copying from an old note from @cmungall  on terms that ‘smell bad’:

“GO:1990009 ! retinal cell apoptotic process
http://amigo.geneontology.org/amigo/term/GO:1990009
The PMID in the definition xref is for pathological apoptosis: http://www.ncbi.nlm.nih.gov/pubmed/10702418
So valid as justification for having the term, but not an idea definition xref.
It seems this term is useful for IMP, so there would be resistance to adding it to the [do not annotate] subset. I'm not sure about the human BAX annotation using this PMID. Should be regulation, not part of the pathway. I'm not even sure there is a normal role for this in the retina.”

@cmungall It seems that yes, programmed cell death does occur during physiological retinal development, see 
http://www.ncbi.nlm.nih.gov/pubmed/15558487
http://www.ncbi.nlm.nih.gov/pubmed/24664675 
I’ll put these two PMIDs as dbxref for ‘retinal cell apoptotic process’ and will delete the original one.

As for the human annotation, that’s a 2009 HGNC (Q07812, IMP, based on http://www.ncbi.nlm.nih.gov/pubmed/10702418). I’ll ask @RLovering  if she could kindly comment and evaluate whether the annotation should be moved to a regulation term, or deleted altogether.

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Fixed PMIDs.

**Comment by RLovering** [comment]
sorry the BAX annotation was rubbish (March 2007 what can I say)...sorry. Annotation deleted

Ruth

**Comment by paolaroncaglia** [comment]
Thanks @RLovering for looking into this.
