### ISSUE TITLE
Remove regulates o part of -> regulates property chains

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12344]
Therese property chains are useful as heuristics as often correct, but are also dangerous. Some processes (e.g. signal transduction) consist of a series of subprocesses/activities that form a causal/regulatory chain. These activities do not regulate the overall process. 

Recent example: inference of reg synaptic vesicle exocytosis - a key step in synaptic transmission - as a modulator of synaptic transmission.

NOTE: removal needs to be done with care given that many inferences are correct.  Need to think through how fits with ETINE review.

(Ticket might be better on RO? Also suspect this is at least partly addressed in other tickets)

**Comment by ukemi** [comment]
I think this was the right move for now. Originally Tanya and I proposed that regulates would be reserved for regulatory activities that completely outside of the process being regulated. It appears now that the pendulum has swung back and even in Noctua models, activities directly activate other activities that are part of the same process. This creates problems with this property chain.

**Comment by ukemi** [comment]
One of the things Kimberly and I have been talking with Heiko about wrt annotations derived from models is the possibility of having the precedence rule that if two terms have both a regulates and an asserted part of relation between them, then the part of relation should take precedence instead of creating an annotation to regulation of the latter term. This would work for annotations derived from models.

**Comment by cmungall** [comment]
@dosumis Before going ahead, can we examine this case in more detail?

This is the hierarchy:

```
     is_a GO:0050804 ! modulation of synaptic transmission
      is_a GO:0046928 ! regulation of neurotransmitter secretion
       is_a GO:2000300 ! regulation of synaptic vesicle exocytosis ***
```

are we sure we have the logical def for GO:0050804 correct? For example, perhaps by 'modulation', we mean something like 'directly regulates'? If we defined it as such, this would block the inference, since the inference comes from the transitivity of regulates.

I suspect transitivity may be real issue here. We wouldn't expect control to be retained over long chains, but we can't really model noise in OWL. My proposed solution is to read the generic regulates in a very weak way, as saying "causally upstream of, and there is a control signal in there, which may influence the target". But this is maybe too unintuitive, and we may want to break transitivity of regulates altogether. We would keep the generic regulates as encompassing direct and indirect cases, but the indirect cases would need to be asserted.

**Comment by cmungall** [comment]
@ukemi - OWL doesn't do precedence, but your rule can be formulated in such a way that we are filtering based on redundancy rather then precedence

**Comment by ukemi** [comment]
There are still cases where transcription factor activities are going to regulate transcription that is part of some developmental process and the transcription factor activity itself is also thought to be part of the same developmental process. As you pointed out, in this case I think the transitivity comes into play.

Filtering based on redundancy would work for the annotations, but it has to be based on the primitive relations in the model, not on the derived annotations. The conventional reasoned annotations would not be reduntant. 
Gene A -> process X
Gene A ->  positive regulation of X

**Comment by dosumis** [comment]
Hi Chris,

There is a reasonable discussion to be had about whether extending indefinitely over chains => results that biologists would find intuitive.  But, as far as I can see, this is completely unconnected to the problem here.  

The problem is very clear with signalling pathways, many of which consist of a series of activities, each positively or negatively regulating the next.  e.g. in a MAPK cascade:

 * RTK activity --directly_activates--> ras activity --directly_activates--> MAPKKK activity --directly_activates--> MAPKK activity --directly_activates-> MAPK activity

It makes no sense to talk about each of these steps positively regulating the whole pathway.  That should be reserved for external factors that modulate the activity of pathway elements (e.g. if some other kinase, not in the pathway, phosphorylated one of these kinases and so modulated its activity).

For pathways with negative regulatory steps (e.g. hedgehog signalling)- the regulates o part_of chain would give even more confusing results.

### synaptic transmission & its modulation:

#### Steps in synaptic transmission:

Action Potential (AP) arrives at presynapse -> Rise in IC Ca2+ -- +ve reg --> synaptic vesicle exocytosis -> NT in cleft -> NT binding to NTR in postsynaptic membrane --- --- > excitatory postsynaptic potential (ePSP)

"+ve reg --> synaptic vesicle exocytosis" happens in every instance of synaptic transmission.  It makes no sense to say that these instances are modulation

#### Modulation refers to the following scenario:

* AP 1 arrives at presynapse of synapse X -> ePSP of magnitude M1
* Some modulatory process P occurs
* AP 2 arrives at presynapse of synapse X -> ePSP of magnitude M2
* M2 differs from M1 as a result of P

P can act in many way.  It might result in a change in the number of vesicles released for a given change in the presynaptic calcium, or a change in calcium buffering at the presynapse (we may consider these to be regulation of SV exocytosis - so this can *sometimes* be modulatory). P may result in a change in the concentration of NTRs in the postsynaptic membrane...

**Comment by cmungall** [comment]
Before going ahead, can we examine this case in more detail?

This is the hierarchy:

```
      is_a GO:0050804 ! modulation of synaptic transmission
       is_a GO:0046928 ! regulation of neurotransmitter secretion
        is_a GO:2000300 ! regulation of synaptic vesicle exocytosis ***
```

are we sure we have the logical def for GO:0050804 correct? For example, 
perhaps by 'modulation', we mean something like 'directly regulates'? If 
we defined it as such, this would block the inference, since the 
inference comes from the transitivity of regulates.

Or maybe it's the case that transitivity of the generic 'regulates' is 
an incorrect assumption?

**Comment by dosumis** [comment]
?

**Comment by dosumis** [comment]
> For example, perhaps by 'modulation', we mean something like 'directly regulates'.

In this case, indirect regulation is the more common:  Some process changes the functioning of the ST pathway and in doing so changes the output the *next time* an action potential arrives.  These are at least temporally distinct.  They can also be indirect - via changes in synaptic structure/organisation.

**Comment by cmungall** [comment]
OK, the MAPK cascade example is good. 

> That should be reserved for external factors that modulate flux through the whole pathway

So would this work:

```
x regulates y
y part-of z
x upstream-of z ### i.e. an external factor
==>
x regulates z
```

Unfortunately we can't do this in plain OWL, which causes problems with the ETINES strategy

Another tack: what if it's the case that whenever we assert `P regulates Q` in the ontology, all this time we have been meaning a stronger statement, `P regulates and is upstream/outside of Q`. If this is true, and if such a relation were named, would chaining this over part-of be valid?

**Comment by dosumis** [comment]
All feels a bit too complex. Suspect it comes down to basic definitions:

regulates: "x regulates y if and only if the x is the realization of a function to exert an effect on the frequency, rate or extent of y"

Not keen on the 'realization of a function 'bit, but I think we can say: Process X regulates process Y if a result of process X occurring is an increase in the rate, frequency or extent of Y (we might want to extend this to talk about size/extent of output).  

One thing we discussed, but decided to gloss before adding this property chain: Regulating individual steps in a process may have no effect on output/rate if the regulated step is not rate limiting.

What the new discussion adds:  Some steps in a processes may involved regulatory interactions between processes.  These are simply necessary for the process to happen - not things that regulate its output/rate/frequency.

I still say ditch the chain.  We can use it as a heuristic for finding regulatory connections to add:  Simply query for subclasses of 'regulates some (part_of some X)' to find new candidates for regulatory relationships.

**Comment by dosumis** [comment]
This is now causing multiple bad inferences for the synapse project.  Keen to have a concrete plan to get rid of these property chains.  Suggest we convert all resulting ETINES to asserted on bulk + make report to go through to look for bad classifications to delete.

**Comment by dosumis** [comment]
#  Plan


- [x] Test that filtering annotated edges works in OE (we have reason to believe this can be flaky)
   It works - It is possible to annotate an edge with a comment and not have it filtered by:

![image](https://cloud.githubusercontent.com/assets/112839/19990616/38cbf08a-a1ec-11e6-9093-250f7fb4b511.png)


- [ ] remove property chains (these are now only in GO!!!!).  Commit.  get svn diff. 
- [ ] Instantiate all the removed axioms - with an annotation recording their origin

**Comment by cmungall** [comment]
When this is done we can revisit the unsatisfactory solution to #13400 (we are currently only importing the is_a hierarchy of OBA)

**Comment by ukemi** [comment]
Just an update that these property chains are still causing issues in our more complicated GO-CAM models. Inaccurate annotations to regulation terms are being output, making it not possible to tag the models as production.

**Comment by ukemi** [comment]
See #13926
