### ISSUE TITLE
multi-symbiont biological processes

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12346]
An email discussion about phage processes stimulated me to make this issue, but I also wonder if it applies to non-viral situations.

Looking at the ontology, we have terms like 

GO:0039634 killing by virus of host cell during superinfection exclusion, 

where virus A modifies the host physiology in response to superinfection by virus B. But what if virus A does exclusion by other mechanisms, such as degrading the DNA of virus B? Is this still a modification of host physiology because the virus A gene product required host translation? What if virus A brought the gene product with it (I don't know an example of this, but I would not be surprised)?

Some cases:
1) The paradigm lambda immunity system. Lambda prophages make a repressor that is a negative regulator of transcription initiation. It is annotated to those processes:

http://www.ebi.ac.uk/QuickGO/GProtein?ac=P03034

But there are no annotations that capture the role in preventing productive superinfections.

2) P22 antirepressor. P22 ant negatively regulates its own repressor, but also negatively regulates the repressors of other phages. The IEAs for this don't capture that (and are wrong, IMO).

http://www.ebi.ac.uk/QuickGO/GProtein?ac=P03037

3) Capsid size determination by phage P4

http://www.uniprot.org/uniprot/P05461

The P4 sid protein is required to make P4-sized capsids using proteins from helper phage P2. There are no GO annotations associated with this protein.

These may all work as children of modification of host by symbiont. But the second symbiont seems to be lost in the ontology structure.

**Comment by dosumis** [comment]
killing by virus of host cell during superinfection exclusion: "The viral-killing of a host cell *by* a pre-existing virus *in response to* a subsequent infection of the host cell by second virus."

> But what if virus A does exclusion by other mechanisms, such as degrading the DNA of virus B?

Not covered by this class.  We can add an extra class to cover this scenario if you need it.  Please can you suggest a definition + reference.

> Is this still a modification of host physiology because the virus A gene product required host translation? 

Not a  modification of host physiology, so we'd need another classification.  Maybe:

modification of one symbiont by another during superinfection
.   .  modification of one virus by another during superinfection  
.   .   .   degradation of the DNA of one virus by another during superinfection

The intermediate class could cover other mechanisms of exclusion such as the repressor one you mention.

Once we have the fixes in place, please raise annotation disputes for existing problematic annotations you've identified.

CCing Beck (@rfoulger) for comment as she created the terms.

**Comment by pgaudet** [comment]
No references for the requested terms - closing, out of date
