### ISSUE TITLE
Connect neuromuscular process controlling posture/balance to musculoskeletal movement

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12349]
Can we connect these two hierarchies? See figure

![nm](https://cloud.githubusercontent.com/assets/50745/13864671/d5dc5c3a-ec60-11e5-90a8-37b936322db1.png)

Not clear what the correct relationship type is, we need starts/ends for the two processes.

From:
https://github.com/obophenotype/human-phenotype-ontology/issues/791

Prospectively assigning @dosumis as he is involved with the NBO effort

**Comment by dosumis** [comment]
Arguably, maintenance of posture is an active process that can happen without movement (?). If so, maybe we want a movement term underneath that links the two hierarchies.  

The voluntary term is very problematic.  Probably there to distinguish from reflexive. But very hard to define. I have some experts i can chat to about better terms.

**Comment by pgaudet** [comment]
See https://github.com/obophenotype/human-phenotype-ontology/wiki/Movement

**Comment by raymond91125** [comment]
In order to maintain posture and balance, one needs to make musculoskeletal movement. I think the the relationship is has_part:

neuromuscular process controlling posture has_part musculoskeletal movement

REFs
1. https://pubmed.ncbi.nlm.nih.gov/28035562/ (only abstract accessible)
2. https://www.78stepshealth.us/body-function/maintenance-of-upright-posture-and-balance.html

**Comment by pgaudet** [comment]
In ShEX we dont use 'has part' to link 2 BPs; does the same rule apply in the ontology? 
https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex

@cmungall 

Thanks, Pascale

**Comment by pgaudet** [comment]
Yes has_part is allowed for BP

**Comment by pgaudet** [comment]
- Decision: add is_a GO:0050905 neuromuscular process 
- Add in file present_in_taxon Drosophila (7215 - check): https://github.com/geneontology/go-ontology/blob/master/src/taxon_constraints/present_in_taxon.tsv
-
