### ISSUE TITLE
mitotic spindle assembly checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12348]
remove ancestors
￼ GO:0051436 negative regulation of ubiquitin-protein ligase activity involved in mitotic cell cycle
￼ GO:1904667 negative regulation of ubiquitin protein ligase activity

The MCC regulates the APC. I don't think we should try to encode this (at least yet until some other stuff is resolved). For now it would be better to delete these relations.

Its making some funny inferences-- the MCC becomes annotated to "metabolism"

**Comment by dosumis** [comment]
Inferences are coming in from the logical def of 'mitotic spindle assembly checkpoint', which references 'APC-Cdc20 complex activity':

![image](https://cloud.githubusercontent.com/assets/112839/13875057/8b16c986-ecf3-11e5-90b8-c001a5d9ae1d.png)

Explanation:

![image](https://cloud.githubusercontent.com/assets/112839/13875043/6b323f10-ecf3-11e5-8ca4-3970dcd02c1b.png)

IIRC, I deleted a bunch of similar axioms on checkpoint terms as part of work on an earlier ticket.  Assume I should delete this one too.

**Comment by dosumis** [comment]
Deleted problematic clause and inferences.

**Comment by ValWood** [comment]
yep
