### ISSUE TITLE
NTR: cochlear outer hair cell electromotility

### ISSUE THREAD

**Issue by cindyJax** [geneontology/go-ontology#12353]
NTR: cochlear outer hair cell electromotility (or perhaps 'cochlear outer hair cell electromotile response')

Suggested def: Outer hair cell electromotility is a rapid, force generating, length change in response to electrical stimulation.

PMID:2187727, PMID:12239568

**Comment by dosumis** [comment]
Sorry for the delay.  This one got buried.

![image](https://cloud.githubusercontent.com/assets/112839/21104635/37b13aa0-c07f-11e6-8ea3-e8f9f1c8ae9f.png)

(Cool biology BTW!)

**Comment by dosumis** [comment]
GO_0099129
