### ISSUE TITLE
odd relationship between CENP-S terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12350]
Is this right, it sounds odd, but maybe I didn't understand what it means

CENP-A recruiting complex
capable of part of
CENP-A containing nucleosome

linking these 2 complexes. I t doesn't seem to make sense?

**Comment by dosumis** [comment]
The link is to the 'assembly' term, which is a process.  

![image](https://cloud.githubusercontent.com/assets/112839/13874977/fa341022-ecf2-11e5-960e-ffa397c64489.png)

So correct.

**Comment by ValWood** [comment]
doh, truncated term in quickgo. I should look up the graph
