### ISSUE TITLE
GO:0042710 biofilm formation child terms

### ISSUE THREAD

**Issue by ebritain13** [geneontology/go-ontology#12358]
GO:0042710 biofilm formation is not supposed to be used for manual annotation but rather an appropriate child term should be used. Two of it's children are GO:0090604 surface biofilm formation and GO:0090605 submerged biofilm formation. If you look at the child terms of GO:0090604 surface biofilm formation it leads you to GO:0090606 single-species surface biofilm formation. However if you look at GO:0090605 submerged biofilm formation it does not have the child term GO:0090608 multi-species submerged biofilm formation listed. I think that this should be changed.

**Comment by suzialeksander** [comment]
This came out of the CACAO class, and I believe the paper they're going off is PMID:18437240, "Agr-mediated dispersal of Staphylococcus aureus biofilms".

**Comment by tberardini** [comment]
Thanks for pointing out this missing relationship.  I've added it in, as well as a couple others that I noticed also missing in this branch of the ontology.
