### ISSUE TITLE
'negative regulation of protein kinase activity by regulation or protein phosphorylation' EquivalentTO 'negative regulation of protein kinase activity''

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12351]
![image](https://cloud.githubusercontent.com/assets/112839/13887379/4254d234-ed33-11e5-9800-18ad1ce25625.png)

Seems to be down to  'protein kinase activity' part of some 'protein phosphorylation' combined with inference of regulation over partonomy.

Rather than deal with this nonsense on a Friday night, I have deleted the equivalence axiom on 'negative regulation of protein kinase activity by regulation or protein phosphorylation'.  This has fixed the build.

Do we want to fix the inference issue?  Do we want the offending term? Does this say something about problems with the inference of regulation over partonomy?

**Comment by ukemi** [comment]
I would be tempted to say that it is probably the phosphorylation that is the regulatory process, not the regulation of phosphorylation. At any rate, we have dealt with the directionality issue in the past. I believe the correct logical def based on what we have done would be:
'regulation of protein phosphorylation' results_in some 'negative regulation of protein kinase activity'. Note, I think it has to be protein kinase activity or it will not be necessary and sufficient.
I would not be sad to see this term (and any others like it) go obsolete. There is no need for them in the future of GO.

**Comment by dosumis** [comment]
> 'regulation of protein phosphorylation' results_in some 'negative regulation of protein kinase activity'. 

We got rid of results_in

**Comment by cmungall** [comment]
:scream:  Uggh, what kind of crazy person would add a term like that.

Wait a minute, what's that you say?

```
Any protein phosphorylation process that negatively_regulates protein kinase activity
Source:GOC:obol, GOC:cjm
```

:frowning:

**Comment by ukemi** [comment]
[Term]
id: GO:0006985
name: positive regulation of NF-kappaB transcription factor activity by ER overload response
namespace: biological_process
def: "The conversion of inactive NF-kappaB to the active form, thereby allowing it to activate transcription of target genes, as a result of signaling from the endoplasmic reticulum." [GOC:dph, GOC:mah, GOC:tb, PMID:10390516]
synonym: "EOR-mediated activation of NF-kappaB" EXACT [GOC:dph, GOC:tb]
synonym: "EOR-mediated NF-kappaB activation" EXACT []
synonym: "positive regulation of NF-kappaB transcription factor activity by EOR" EXACT [GOC:dph, GOC:tb]
is_a: GO:0006983 {is_inferred="true"} ! ER overload response
is_a: GO:0051092 ! positive regulation of NF-kappaB transcription factor activity
intersection_of: GO:0006983 ! ER overload response
intersection_of: results_in GO:0051092 ! positive regulation of NF-kappaB transcription factor activity

**Comment by dosumis** [comment]
We got rid of most usage and I believe we agreed to obsolete the relation. Seems we didn't obsolete &  there's some stray usage left.

AFAIK it was introduced to deal with regulation of regulation. That now makes no sense given transitivity and property chain reg algebra.  From name, it sounds like (immediately) causally upstream of. But that wouldn't work here.

**Comment by dosumis** [comment]
14 uses left:

![image](https://cloud.githubusercontent.com/assets/112839/13912421/f4830fea-ef34-11e5-8496-514d789464c9.png)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0100002 negative regulation of protein kinase activity by regulation or protein phosphorylation'. The reason for obsoletion is that this represents a molecular function. Consider annotating to 'GO:0004860 protein kinase inhibitor activity' . There are 2 EXP annotations (SGD and BHF). There are no mappings; this term is not present  in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/12351


Thanks, Pascale
