### ISSUE TITLE
NTR: vascular smooth muscle cell dedifferentiation

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12354]
Hello,

Could I please request the new term "vascular smooth muscle cell dedifferentiation"

As a child of GO:0043697 cell dedifferentiation
Potential definition: The process in which a vascular smooth muscle cell (a non-striated, elongated, spindle-shaped cell found lining the blood vessels) loses the structural or functional features that characterize it in the mature organism, or some other relatively stable phase of the organism's life history. Under certain conditions, these cells can revert back to the features of the stem cells that were their ancestors. 

Based on PMID:19088079 (Induction of microRNA-221 by platelet-derived growth factor signaling is critical for modulation of vascular smooth muscle phenotype), this appears to be a normal process for vascular repair.
"Unlike many terminally differentiated cells, smooth muscle cells (SMCs) can switch between differentiated and dedifferentiated phenotypes in response to changes in the local environment (2). In response to vascular injury, quiescent contractile vSMCs reduce the expression of SMC-specific genes such as α-smooth muscle actin (SMA), smooth muscle calponin (CNN), SM22α (SM22), and smooth muscle myosin heavy chain, increase proliferation, and synthesize collagens and matrix metalloproteinases (2, 9). Although this phenotype switch is believed to be essential for repair of vascular injury, deregulation of this process also plays a role in the pathogenesis of various human diseases, including atherosclerosis, hypertension, asthma, and cancer."

Please add the references;
GOC:rph
GOC:BHF
GOC:BHF_miRNA

Thanks,
Rachael.

**Comment by rachhuntley** [comment]
Also, we were just discussing this term in relation to phenotype switching. We thought that maybe "cell dedifferentiation" (GO:0043697) should be a child of "phenotype switching" (GO:0036166)?

**Comment by tberardini** [comment]
I think it's ok to add under 'phenotype switching' esp with current definition specifically saying that this applies to smooth muscle cells.

**Comment by tberardini** [comment]
Added:


[Term]
id: GO:1990936
name: vascular smooth muscle cell dedifferentiation
namespace: biological_process
def: "The process in which a vascular smooth muscle cell (a non-striated, elongated, spindle-shaped cell found lining the blood vessels) loses the structural or functional features that characterize it in the mature organism, or some other relatively stable phase of the organism's life history. Under certain conditions, these cells can revert back to the features of the stem cells that were their ancestors." [GOC:BHF, GOC:BHF_miRNA, GOC:rph, PMID:19088079]
subset: termgenie_unvetted
is_a: GO:0036166 ! phenotypic switching
is_a: GO:0043697 ! cell dedifferentiation
created_by: tb
creation_date: 2016-03-22T20:25:11Z

**Comment by ukemi** [comment]
Does the switching include both directions? If so, then the dedifferentiation would be part of it, right? The other direction/part would be cell development because presumably if the switch is only between two cell types, even the dedifferentiated one is committed.

**Comment by tberardini** [comment]
@rachhuntley - comment on the switching being both directions?  This affects whether dedifferentiation is _part_of_ or _is_a_ phenotypic switching.

**Comment by rachhuntley** [comment]
Hi,
It looks like it is reversible, there are a few references stating this for smooth muscle cells
This one's title says it all: "Evidence From a Novel Human Cell Clone That Adult Vascular Smooth Muscle Cells Can Convert Reversibly Between Noncontractile and Contractile Phenotypes " PMID:10455062.

Also; 
http://www.ncbi.nlm.nih.gov/pubmed/18300422 "We postulate that the latter epigenetic changes may provide a mechanism for 'cell lineage memory' during reversible phenotypic switching of vascular SMCs."

http://atvb.ahajournals.org/content/23/9/1510.long: "We have shown that FGF-2 and PDGF-BB induce a switch from the spindle-shaped to the rhomboid phenotype in pig SMCs.29 This is associated with increased proliferation and a decrease in expression of differentiation markers. A similar effect has been obtained for spindle-shaped SMC clones. In both situations, this shape change is reversible when treatment is ceased."

I haven't looked extensively in other types of phenotypic switching, but this one in Candida also talks about reversible phenotypic switching;
http://www.ncbi.nlm.nih.gov/pubmed/25481846 "After 5 days of incubation, C. guilliermondii switched spontaneously and reversibly among two phenotypes distinguishable on CuSO4 containing agar, white and dark brown."

I hope this is enough, but if you want me to look into this more I can do it on Tuesday as we're on Easter holidays now.

Happy Easter all!

**Comment by tberardini** [comment]
Looking at the 'phenotypic switching' branch again, I found this term, ' reversion of cell type to default state involved in phenotypic switching' which is a _**part_of**_ child.  What do you think about moving 'vascular smooth muscle cell dedifferentiation' to be a child of this term instead? @ukemi , @rachhuntley 
http://amigo.geneontology.org/amigo/term/GO:0044664#display-lineage-tab

**Comment by rachhuntley** [comment]
What is the default state though? I would say for smooth muscle cells, if anything it would be the "differentiated" state, since dedifferentiation occurs in order to repair injury.

(by the way, I'm really not here until Tuesday...)

**Comment by tberardini** [comment]
The parent term does refer to the same phrasing, '...ends when the morphology of a population of cells has reverted back to the default state...'  Maybe tweak def to remove that, esp. since the emphasis is on reversibility.

Yes, you're not there at all.  Just talking to myself.

**Comment by ukemi** [comment]
Not to yourself. I think default state is problematic in these cases, because it depends on viewpoint. But I agree with Rachel. If I needed to pick one, I would think the 'default' state would be the differentiated state in this case because without injury, that's what happens to the cell.

**Comment by tberardini** [comment]
How about removing reference to a 'default' state?

change:  A reversible switch of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations.  Phenotypic switching begins with changes in cell morphology and altered gene expression patterns and ends when the morphology of a population of cells has reverted back to the default state, accompanied by altered expression patterns. 

To:   A reversible switch **of the phenotype** of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations.  Phenotypic switching begins **when a cell type changes in **cell morphology and altered gene expression patterns and **ends when the morphology of a population of cells has switched to that of another cell type**, accompanied by altered expression patterns. 

I'm not quite sure how to adapt 'reversion of cell type to default state involved in phenotypic switching' to this def.  Maybe 'reversion of cell type to **initial state** involved in phenotypic switching'?  The term does not have any annotations associated to it.

**Comment by rachhuntley** [comment]
HI Tanya,

I like the change in definition. 

For the second part, 'reversion of cell type to initial state involved in phenotypic switching', I'm getting a little confused as this sounds like dedifferentiation back to the stem-like cells.
So we're saying that phenotypic switching happens in both directions; in the case of SMCs, towards differentiated cells and then back to dedifferentiated cells. So the term phenotypic switching should have two child terms, one for each direction. "cell dedifferentiation" could come under one of these terms and maybe there should be another term, e.g. "reversion of cell type to differentiated state" could come under the other (maybe called "reversion of cell type to stable state")? 

I assume phenotypic switching doesn't always involve cell differentiation?

**Comment by tberardini** [comment]
What if we just get rid of ''reversion of cell type to default state involved in phenotypic switching'?  There are no annotations?  You're more of a phenotype switching expert than I am, do you know if phenotypic switching can occur without cell differentiation?
Maybe:

phenotypic switching (PS)
--[p]cell dedifferentiation  (differentiated cell to dedifferentiated cell)
--[p]cell differentiation involved in phenotypic switching (dedifferentiated cell to differentiated cell in context of PS)

**Comment by rachhuntley** [comment]
I'm by no means an expert, I've only been reading about it since I opened this ticket!
Phenotypic switching of mammalian SMCs always seems to mention cell differentiation/dedifferentiation. As for other species, there is this paper on yeast (http://www.ncbi.nlm.nih.gov/pmc/articles/PMC196463/), it opens by saying "During the development of eukaryotic organisms, the establishment of specific cell lineages from a multipotent progenitor often involves multiple differentiation steps that are regulated, at least in part, at the level of gene transcription."..."Therefore, as cells progress along a developmental pathway, they switch from one state of differentiation to another by changing gene expression programs."

So it looks like it could be differentiation, if so I agree with your proposal.

I'm off on holiday again today (those Brits with all their vacation days!), but back on Tuesday so apologize in advance for my silence.

Maybe @ValWood could comment on whether phenotypic switching always involves cell differentiation in yeast?

**Comment by ValWood** [comment]
I've been following and so far it seems OK to me. Wild-type  Pombe doesn't do the thing defined as 'phenotype switching' (unfortunate name for a process!), but it does do mating-type switching. This is not defined as a type of phenotype switching. So as far as I can see this seems OK...the  filamentous growth described wold be a type of differentiation.

@mah11 does it sound OK to you?

**Comment by ValWood** [comment]
I'm not sure about the revised def.
I think the def should state "from one cell type or form to another"
rather than the phenotype of. I'm not sure that  the "of te phenotype of the cell" part makes sense (Midori will be able to correct me if I am wrong). Its a switching between cell types (unfortunate name as I said).

Also  it is not clear that/if the expression pattern switches back to the original expression pattern?

**Comment by ValWood** [comment]
Arggh, Wikipedia says

Phenotypic switching in C. albicans include the switch from white cells to opaque cells in need for sexual mating.

AND

A second example occurs in Melanoma, where malignantly transformed pigment cells switch back-and-forth between phenotypes of proliferation and invasion in response to changing microenvironments, driving metastatic progression.


I wonder if this should not really  be in GO as a term called "phenotype switching". This could be misused., and it seems to be used for a number of different types of switch.

I think the phenotype switching term should go completely (or be renamed as reversible differentiation with  'phenotype switching' as a synonym

The original term 'phenotype switching'  as used by CGD really means
"transition from vegetative to filamentous growth"
def transition from a unicellular form to an invasive multicellular filamentous form upon infection of host tissue' 
and should have parentage to
'regulation of filamentious growth' and 'reversible differentiation' 


GO:0045023	G0 to G1 transition
GO:0070314	G1 to G0 transition
would also belong under  a term "reversible differentiation"

**Comment by mah11** [comment]
I don't have much to add; I have only done lab work with Saccharomyces, and I don't recall people using the phrase "phenotypic switching" even though S.c. can do pseudohyphal growth. I certainly wouldn't wade in on the subject in bigger eukaryotes!

I do agree that mating type switching is not phenotypic switching. What little I've seen about phenotypic switching seems to imply that there isn't an accompanying change in genotype (and in mating type switching there is).

I'm not as bothered as Val by the suggestion to add "switch of the phenotype of a cell" to  the switching def, but I don't think it adds much. I do wonder whether a cell really has to make a full round trip from state 1 to state 2 and back to state 1 as the current def says, though. I get that if a given type/morphology/whatever change is irreversible we might not want to count it as phenotypic switching, but is a reversible change from state 1 to state 2 not a phenotype switch itself, even before it does the go-back-to-state-1 part? I genuinely don't know. The dedifferentiation def sounds like it's only one direction, though.

This question also makes the terms for parts of phenotypic switching bother me a bit (in addition to the concern about saying "default state", which I think are well founded).

I don't think of G0<->G1 as differentiation at all. Those transitions are more like cell cycle transitions than differentiation, which is a developmental phenomenon.

I think I've gone on rather too long for someone who doesn't actually know these processes in detail ...

**Comment by tberardini** [comment]
Who have we got from CGD who can help us?  I've sent an email to the email listed here and see if anyone gets back to us.
http://www.candidagenome.org/cgi-bin/suggestion

**Comment by tberardini** [comment]
Comments from CGD:

Hi Tanya,

Marek will take a look, but I read over the github page, and white opaque switching (as far as I understand it) is not to do with regulating filamentous growth.  From PMID 19853498, white opaque switching is:

"an epigenetic switch between two distinct types of cells, referred to as white and opaque. These two cell types differ in many respects, including their cell and colony morphologies, their metabolic states, their mating behaviors, their preferred niches in the host, and their interactions with the host immune system“

so I don’t think putting it under 'regulation of filamentious growth’ is a good idea.  In some sense, maybe it’s 'reversible differentiation’, but I’m not sure, so I’ll let Marek comment more.

Cheers,
Gavin


------------------
Hi Tanya,

Thanks for contacting us. I don't have much to add to what Gavin has already said. Phenotypic switching, as used in CGD, is a reversible transition between two distinct cell types (in C. albicans referred to as white and opaque) and it is an entirely separate process from filamentous growth. I am not sure why the current definition of phenotypic switching even mentions C. albicans and the transition from unicellular to filamentous form. It sounds like an off the cuff example of phenotypic switching, which it is not; this sentence should be removed. 

I am not convinced that reversible differentiation would be a suitable parent for phenotypic switching, though. It does not involve acquiring specialized structures, for one thing, and it doesn't commit cells to any particular stable phase. The current placement of phenotypic switching in the ontology, as a child of cellular process, seems appropriate, since this is a distinct process from anything else.

I hope this helps, but feel free to ask if something's unclear and you need more input.

Best regards,
Marek

**Comment by tberardini** [comment]
Checking with Marek wrt CGD annotations to the phenotypic switching terms.  I will modify the def to remove reference to 'unicellular to filamentous form' switching on his advice.

**Comment by tberardini** [comment]
His reply:

Hi Tanya,

Yes, this modified definition would work for Candida and I imagine it should also work for other cases, whatever they might be, since the only part that has been removed is about Candida and filamentous growth, which was incorrect.

On the second thought, however, I also don't like the sentence about when the phenotypic switching begins and ends. As I understand it, phenotypic switching is the transition between two states, whereas the definition seems to imply that this is an alternative state that is not default, whatever that means. I would change the text to something like this:

A reversible switch of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations. Phenotypic switching involves changes in cell morphology and altered gene expression patterns. For example, Candida albicans switches from white cells to opaque cells for sexual mating. Phenotypic switching also occurs in multicellular organisms; smooth muscle cells (SMCs) exhibit phenotypic transitions to allow rapid adaption to fluctuating environmental cues.

I hope this sounds good to you.

Thanks,
Marek

------------------
Old definition for reference:

A reversible switch of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations. Phenotypic switching begins with changes in cell morphology and altered gene expression patterns and ends when the morphology of a population of cells has reverted back to the default state, accompanied by altered expression patterns. For example, Candida albicans switches from a unicellular form to an invasive multicellular filamentous form upon infection of host tissue, and from white cells to opaque cells for sexual mating. Phenotypic switching also occurs in multicellular organisms; smooth muscle cells (SMCs) exhibit phenotypic transitions to allow rapid adaption to fluctuating environmental cues.

---------------

Comments?

**Comment by rachhuntley** [comment]
I think the new definiton sounds good. So, is it correct that the Candida example does not involve differentiation? The cells are changing between two different types. In which case, would we need a new is_a child term, as Val suggests, such as 'reversible differentiation', then we can have the structure that Tanya suggested underneath this
--[p]cell dedifferentiation (differentiated cell to dedifferentiated cell)
--[p]cell differentiation involved in phenotypic switching (dedifferentiated cell to differentiated cell in context of PS)

**Comment by tberardini** [comment]
I checked with Marek.
---------------
Hi Tanya,

I'll keep an eye on github in case something comes up and I'd like to chime in. So far, I am OK with 'reversible differentiation', as Val suggested.

Regards,
Marek

**Comment by tberardini** [comment]
Looks like we're converging on something like this.  Please review and give a thumbs up or thumbs down.

1. Change definition of 'phenotypic switching' to:
A reversible switch of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations. Phenotypic switching involves changes in cell morphology and altered gene expression patterns. For example, Candida albicans switches from white cells to opaque cells for sexual mating. Phenotypic switching also occurs in multicellular organisms; smooth muscle cells (SMCs) exhibit phenotypic transitions to allow rapid adaption to fluctuating environmental cues.

2. Current structure of terms:
<img width="838" alt="screen shot 2016-04-07 at 10 24 49 am" src="https://cloud.githubusercontent.com/assets/4998871/14360390/ff1baba0-fcaa-11e5-8bcd-3d6f8409aa1c.png">

3. Updated structure of terms:

reversion of cell type to default state involved in phenotypic switching, GO:exists **(OBSOLETE THIS,
NO ANNOTATIONS, not unambiguous, replaced by two alternatives under reversible differentiation)**

phenotypic switching, GO:exists
--[R] bunch of regulation terms stay where they are
--[p] other part_of children besides the one above stay where they are
**--[i] reversible differentiation, GO:new1**
**----[p]cell dedifferentiation involved in phenotypic switching, GO:new2**
------[i] vascular smooth muscle cell dedifferentiation, GO:exists
**----[p]cell differentiation involved in phenotypic switching, GO:new3**

cell differentiation, GO:exists
**--[i]cell differentiation involved in phenotypic switching, GO:new3**

cell dedifferentiation, GO:exists
**--[i]cell dedifferentiation involved in phenotypic switching, GO:new3**
----[i] vascular smooth muscle cell dedifferentiation, GO:exists
--[i] hepatocyte dedifferentiation, GO:exists

**Comment by ValWood** [comment]
Sounds good.

**Comment by rachhuntley** [comment]
Thumbs up from me too. Thanks Tanya.

**Comment by ukemi** [comment]
Make that three.

**Comment by tberardini** [comment]
Obsoletion email sent today.  Obsoletion and new term creation scheduled for April 26th.

Dear all,

The proposal has been made to obsolete the following term:

GO:0044664,  reversion of cell type to default state involved in phenotypic switching

The reason for obsoletion is that the term is ambiguous and two non-ambiguous terms will be created to take its place.

All details here:
https://github.com/geneontology/go-ontology/issues/12354

There are no annotations to this term.

We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete the terms above on April 26, 2016.

*** Unless objections are received by April 26, 2016, we will assume
that you agree to this change. ***

On behalf of the GO ontology editors,

Tanya Berardini

**Comment by rachhuntley** [comment]
Thanks Tanya - sorry about the quick fix label :)

**Comment by tberardini** [comment]
Finally done.

+id: GO:0090677
+name: reversible differentiation
+namespace: biological_process
+def: "A phenotypic switching process where a cell reversibly differentiates and dedifferentiates from one cell type into another." [GOC:curators]
+is_a: GO:0036166 ! phenotypic switching

+id: GO:0090678
+name: cell dedifferentiation involved in phenotypic switching
+namespace: biological_process
+def: "A cell dedifferentiation process that is a part of a reversible switch of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations." [GOC:curators]
+is_a: GO:0043697 ! cell dedifferentiation
+relationship: part_of GO:0090677 ! reversible differentiation

+id: GO:0090679
+name: cell differentiation involved in phenotypic switching
+namespace: biological_process
+def: "A cell differentiation process that is a part of a reversible switch of a cell from one cell type or form to another, at a frequency above the expected frequency for somatic mutations." [GOC:curators]
+is_a: GO:0030154 ! cell differentiation
+relationship: part_of GO:0090677 ! reversible differentiation

**Comment by tberardini** [comment]
and obsoleted id: GO:0044664

-name: reversion of cell type to default state involved in phenotypic switching
+name: obsolete reversion of cell type to default state involved in phenotypic switching

**Comment by rachhuntley** [comment]
Thanks Tanya!
