### ISSUE TITLE
New GO term: positive regulation of synaptonemal complex assembly

### ISSUE THREAD

**Issue by kaylamichbrown** [geneontology/go-ontology#12367]
Hello! I am in the CACAO class at Texas A&M University, and I am submitting a request for a new GO term: positive regulation of synaptonemal complex assembly. I am working on PMID: 24797370 to annotate to Set1 in Yeast (P38827) using Figures 5A and 5B.

**Comment by mcourtot** [comment]
Created 

[Term]
id: GO:1905088
name: positive regulation of synaptonemal complex assembly
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of synaptonemal complex assembly." [GO_REF:0000058, GOC:TermGenie, PMID:24797370]
synonym: "activation of synaptonemal complex assembly" NARROW [GOC:TermGenie]
synonym: "activation of synaptonemal complex formation" NARROW [GOC:TermGenie]
synonym: "positive regulation of synaptonemal complex formation" EXACT [GOC:TermGenie]
synonym: "up regulation of synaptonemal complex assembly" EXACT [GOC:TermGenie]
synonym: "up regulation of synaptonemal complex formation" EXACT [GOC:TermGenie]
synonym: "up-regulation of synaptonemal complex assembly" EXACT [GOC:TermGenie]
synonym: "up-regulation of synaptonemal complex formation" EXACT [GOC:TermGenie]
synonym: "upregulation of synaptonemal complex assembly" EXACT [GOC:TermGenie]
synonym: "upregulation of synaptonemal complex formation" EXACT [GOC:TermGenie]
is_a: GO:0044089 {is_inferred="true"} ! positive regulation of cellular component biogenesis
is_a: GO:0051984 {is_inferred="true"} ! positive regulation of chromosome segregation
is_a: GO:0060903 {is_inferred="true"} ! positive regulation of meiosis I
is_a: GO:0090173 {is_inferred="true"} ! regulation of synaptonemal complex assembly
is_a: GO:2001252 {is_inferred="true"} ! positive regulation of chromosome organization
intersection_of: GO:0065007 ! biological regulation
intersection_of: positively_regulates GO:0007130 ! synaptonemal complex assembly
relationship: positively_regulates GO:0007130 {is_inferred="true"} ! synaptonemal complex assembly
created_by: mec
creation_date: 2016-03-30T08:39:03Z
