### ISSUE TITLE
more spindle checkpoint relation parentage 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12366]
The mitotic spindle assembly checkpoint is
A cell cycle checkpoint that delays the metaphase/anaphase transition of a mitotic nuclear division until the spindle is correctly assembled and chromosomes are attached to the spindle.
(The MCC inhibits the APC)

However, the  regulation  child
GO:1902426 negative regulation of mitotic spindle assembly checkpoint
has  ancestry to
GO:1902101 positive regulation of metaphase/anaphase transition of cell cycle
because the active checkpoint negatively regulates this transition.

This term is used  when the   checkpoint signalling  is turned off AFTER the 
anaphase/metaphase transition is accomplished, which makes the 
ancestry to
GO:1902101 positive regulation of metaphase/anaphase transition of cell cycle

 biologically incorrect

( Should also delete the ancestry to 
GO:1904668 positive regulation of ubiquitin protein ligase activity)

(noticed because ubc11 is annotated to both +ve and -ve  regulation of the transition)

**Comment by mcourtot** [comment]
@tberardini: I believe you looked into those terms recently (#12294), would you be able to address this?

**Comment by ValWood** [comment]
tagging  @dosumis too as he has been looking at those thorny positive/negative regulation issues

**Comment by tberardini** [comment]
@mcourtot: I did work on #12294 but I don't think this is related. Those terms had to do with 'spindle organization'.

**Comment by ValWood** [comment]
This term has been renamed
deactivation of mitotic spindle assembly

There are a number of issues with the parentage.

positive regulation of the spindle assembly checkpoint 
negatively regulates  the anaphase-metaphase transition/ chromosome segregation, 

However,
negative regulation of the spindle assembly checkpoint 
DOES NOT have any effect on the regulation of the metaphase anaphase transition, OR chromosme segregation, as the spindle assembly checkpoint turns OFF  AFTER these processes have completed.

I think the solution here is to remove all of the regulation dependencies out of the ontology completely, as these will be made in LEGO annotation connections, they don't need to be in the ontology.
 Do you agree @ukemi

**Comment by ValWood** [comment]
This is a non issue.
It does turn off the checkpoint so that anaphase can occur.
David has done some def refinement.
