### ISSUE TITLE
missing parents for cardiac conduction terms

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12360]
Hi David

I have been looking at the terms with no annotations and it has made me realise that I have missed some annotations but also that there are relations missing.

I think 
GO:1902282	voltage-gated potassium channel activity involved in ventricular cardiac muscle cell action potential repolarization
Should have a part of relation to 
GO:0098915	membrane repolarization during ventricular cardiac muscle cell action potential

see relation between: 
GO:0086008 voltage-gated potassium channel activity involved in cardiac muscle cell action potential repolarization
and GO:0086013 membrane repolarization during cardiac muscle cell action potential

Thanks

Ruth

**Comment by dosumis** [comment]
Fixed.
