### ISSUE TITLE
peptide transport/ protein localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12369]
I'm not sure how we treat peptide vs. protein, but I think it might be different in different branches.

Anyway the question is, should  peptide transport have protein localization as an ancestor

(not to self, if not this will need a separate entry in AE config file)

**Comment by mcourtot** [comment]
Peptide vs. proteins: https://github.com/geneontology/go-ontology/issues/12341 or https://github.com/geneontology/go-ontology/issues/12259

I just asked other editors on the call and @ukemi explained that you can have transport without localisation, for example in case the peptide is transported but then diffuse freely, so peptide transport should not have protein localisation as an ancestor.

However, checking the hierarchy, things seem a bit more confused:
<img width="555" alt="screen shot 2016-03-31 at 17 02 19" src="https://cloud.githubusercontent.com/assets/2214135/14182266/722a3eca-f762-11e5-955f-9013e079eacf.png">

as for example single-organism transport is_a single organism localization, and transport is_a localisation (indirectly). @ukemi: what do you think?

**Comment by ValWood** [comment]
@ukemi is rarely wrong, but he is here;)
 all transport is localization. He'll agree in a minute.

**Comment by ValWood** [comment]
Diffusion isn't controlled by a gene product, so  this does not hold in GO. Although some localization is my diffusion.

**Comment by ukemi** [comment]
He is wrong more than you think. I don't think diffusion is a type of localization, but I think anchoring a diffused substance in a location is.  I guess it depends on how we define transport. If we define the purpose of transport to be localization, then I think this is ok. This assumes that nothing is transported without the purpose of localizing it. However, I still think that not all localization is accomplished by transport.

**Comment by ValWood** [comment]
That is true ;)

**Comment by mcourtot** [comment]
Actually he had made a good job of convincing me during the call; IIRC the example he used was about diffusion of proteins during embryogenesis, where a protein is transported but not localised as it diffuses freely. I was thinking at cases in which things are secreted for example, and we have 'lactation' in GO - it seems odd to say that lactation is a localisation process.
I think in general transport process can result in localisation, but they don't necessarily overlap. Now as David says, it all boils down to how we define transport. Right now, definition reads 'The directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter or pore.' which doesn't imply an end location is achieved. If we decide to go that route (and it seems we do based on the existing hierarchy) this probably deserves to be made clearer. We could either update the definition or add a comment along the lines of 'In GO, all transport proceses are types of localisation processes'.

![screen shot 2016-04-01 at 09 12 58](https://cloud.githubusercontent.com/assets/2214135/14201455/f5e4ef9e-f7e9-11e5-8c50-f7e302798f1b.png)

**Comment by ValWood** [comment]
Hmm, I don't have a problem with any secretion being transport-> localization.

I wish I could find the old tickets when this was immediately implemented. Its probably about 10 years ago and it has held up for everything so far... but there could be exceptions...I don't think this is one of them. The crux here is if a peptide is a protein.... protein transport is already is_a protein localization.

**Comment by ukemi** [comment]
Secretion is one example, excretion from the kidney is another. Would you consider transport of metabolites into a cell localization? I think these are just a bit weird. To me localization means here, but not there. I think transport can just move from here to there. What do you think? It doesn't mean that transport can't be involved in localization, I'm just not sure it always is.

**Comment by ValWood** [comment]
I think the type of localization we refer to in GO has to be performed by a gene product establishing or maintaining a specific location. This limits it to anchoring, sequestering transport etc are all localization processes.  Sure, things can localize to places in other ways that are not actively dependent on gene products, but these are not 'annotatable' by GO, because they aren't biological processes.

I would consider transport of metabolites into a cell 'localization'.
Need @mah11 (just in case I'm wrong!)

**Comment by mah11** [comment]
Sorry, I never worked on that area (in biology or in GO) and therefore can't help.

**Comment by ValWood** [comment]
I remember you initially making localization a parent of transport.

**Comment by mah11** [comment]
I did not do any of the work on that branch of GO.

**Comment by ukemi** [comment]
I agree that we shouldn't consider things that are not accomplished by the action of gene products. I guess the major question is does localization encompass more than just moving things from place to place. Does it mean that something is restricted to a specific place? I would say yes.

**Comment by ValWood** [comment]
>Does it mean that something is restricted to a specific place? I would say yes.

Yes.
But this doesn't prevent all transport being localization. It only stops all localization being transport.

**Comment by ukemi** [comment]
I think it is the other way around. You can also get localization by anchoring something (protein myristoylation can localize a protein to a membrane as an example off the top of my head) and you can get localization from selective spatial degradation, both of which are accomplished by gene products.

Does transport ever occur for a purpose other than restricting the location of something? I would say that sometimes it occurs just to move something somewhere, but not necessarily to restrict its location.

**Comment by ukemi** [comment]
PS. I'm not saying that all peptide transport is not for the purpose of peptide localization. I don't know the answer to that. I'm just suggesting that not all transport is accomplishing localization.

**Comment by ValWood** [comment]
Localization is defined:
Any process in which a cell, a substance, or a cellular entity, such as a protein complex or organelle, is transported to or maintained in a specific location
;)

**Comment by mcourtot** [comment]
I think both @ukemi and I have an issue with the part 'transported to a specific location'. To reiterate the example above, I don't think that secretion occurs in a specific location. As David says above, 
>sometimes [transport] occurs just to move something somewhere, but not necessarily to restrict its location.

Again, I think it all boils down to how we want to define transport in GO, and the current definition doesn't mention end location. Though I agree with Val that it seems implied based on the current hierarchy, it still deserves clarification. Shall we bring that up at an editor or annotation call? It would be I think helpful to have contributions from others to reach consensus. Though keeping things as is would as usual be easier :)

**Comment by ValWood** [comment]
Ugh, I see what you mean. That would be horrible to fix.....I wonder if there is always some restriction of location (for example in secretion it is outside the cell)?

**Comment by mcourtot** [comment]
That seems reasonable based on the current hierarchy. Maybe just adding a comment to that effect to the transport term and link to this ticket to leave an audit trail?

Re protein vs peptide, I believe this should be 'fixed' when the bridge described at https://github.com/geneontology/go-ontology/issues/12341 is implemented. Pinging @dosumis.

**Comment by ValWood** [comment]
I know what the secretion problem is now.
I'll migrate that part to a new ticket as its a separate issue....

**Comment by ValWood** [comment]
I still think that all transport is localization. the problems reported in this ticket as far as I can see would be fixed by sorting out this branch/ secretion
https://github.com/geneontology/go-ontology/issues/12381

**Comment by dosumis** [comment]
The general problem with this branch is the glossing the distinction between individual molecules and concentration.  GO bakes in an assumption that transport always leads to a change in localization.  This must be true on an individual molecule level, but is not necessarily true for molecular concentration.  Fixing this for the whole branch and all annotations would be hard.

**Comment by mcourtot** [comment]
Summary: the issue transport vs localisation has been submitted as a new ticket as it became a side discussion from @ValWood's original question which was more regarding peptide vs protein. We expect the latter issue to be fixed by #12341.

Nothing to do on this ticket atm, but keeping it open to not forget to check its status when #12341 gets fixed.

- [ ] fix #12341 

- [ ] check status on parentage: if peptide transport is_a protein transport -> close

**Comment by ValWood** [comment]
The distinction between individual molecules and concentration never crossed my mind before. I still can't think of any transport which does not lead to a change in localization.
 I tried to think of a few contexts. A single glucose transporter transports some molecules in a directed . It's still  changing the localization of those molecules regardless of what happens to them subsequently. I can't think of an exception where transport isn't localization.

**Comment by ValWood** [comment]
I closed this older one as duplicate:
https://github.com/geneontology/go-ontology/issues/9543

**Comment by dianeoinglis** [comment]
I am not sure if this adds any clarity but I was working with OMP https://github.com/microbialphenotypes on phenotype terms and a "protein secretion" term came up where the secreted protein is "secreted Phospholipase B1." This secreted protein interacts with host tissues and mutants that fail to secrete this normally "secreted form" of Phospholipase B1 have defects in virulence, even if this Phospholipase B family member accumulates inside the cell. In this case, the mere secretion of the protein outside of the fungal cell is required for proximity to host tissues. The function does not require additional localization beyond "outside the cell." I am in agreement with all secretion being a localization.

**Comment by ValWood** [comment]
This ticket was really about the relationship between "peptide process" and the equivalent "protein process". However it seems that now, these are not related in chebi.

**Comment by deustp01** [comment]
I think you can make an equivalence, in two steps. CHEBI:16541 (protein polypeptide chain, "A naturally occurring polypeptide synthesized at the ribosome.") has the outgoing relationship: protein polypeptide chain (CHEBI:16541) is a polypeptide (CHEBI:15841). Polypeptide ("A peptide containing ten or more amino acid residues.") in turn has the outgoing relationship: polypeptide (CHEBI:15841) is a peptide (CHEBI:16670).

Can that work?

**Comment by mcourtot** [comment]
ChEBI already states
protein polypeptide chain (CHEBI:16541) is a polypeptide (CHEBI:15841) (see [here](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16541))
and 
polypeptide (CHEBI:15841) is a peptide (CHEBI:16670)  (see [here](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15841))

The issue is on the protein term, https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:36080, which states protein (CHEBI:36080) has part protein polypeptide chain (CHEBI:16541) 

I think the issue of how to deal with protein should be discussed in https://github.com/geneontology/go-ontology/issues/12341, which deals with the bridging between Chebi and PRO and being consistent throughout to enable proper inferences.

**Comment by mcourtot** [comment]
Closing this ticket as issues have been addressed (but for peptide/protein which is dealt with in #12341). Related ticket on lactation https://github.com/geneontology/go-ontology/issues/12381 mentioned for information here.
