### ISSUE TITLE
"obsolete" in term name

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#12365]
GO:1904772 obsolete response to tetrachloromethane​

The term isn't obsolete, so the presence of the word "obsolete" in the name seems to be incorrect? Thank you

Mike GOC:MR

**Comment by cmungall** [comment]
I have added a check to the release pipeline. It also does the converse check.

currently it reports:

```
$ check-obo-for-standard-release.pl gene_ontology_write.obo 
ERROR: obsolete-class-should-have-prefixed-label: GO:0098766
ERROR: obsolete-class-should-have-prefixed-label: GO:0098767
ERROR: non-obsolete-class-has-obsolete-label: GO:1904772 -> obsolete response to tetrachloromethane
```

as expected

**Comment by cmungall** [comment]
Good, build fails as expected:

http://build.berkeleybop.org/view/GO/job/build-go/6924/console

**Comment by cmungall** [comment]
Fixed in commit 32298
