### ISSUE TITLE
TPV: GO:0006659 phosphatidylserine biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12364]
GO:0006659 phosphatidylserine biosynthetic process
has parentage to both
amino acid metabolic process and
modified amino acid metabolic process

**Comment by mcourtot** [comment]
This is part of some cleaning up we're doing at the moment, where some inferences based on older version of ChEBI will be removed. 
In the meantime I have removed the parentage phosphatidylserine metabolic process is-a alpha-amino acid metabolic process, but there are another 17 occurrences where phosphatidylserine is causing issues - the plan is to flush those automatically very soon (in a matter of weeks) so I didn't clean them up manually.
