### ISSUE TITLE
missing parent for GO:0051142 positive regulation of NK T cell proliferation

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12361]
GO:0051142 positive regulation of NK T cell proliferation should have
GO:0051135 positive regulation of NK T cell activation
as is_a parent
as all other cell proliferation terms are children of cell activation terms

Birgit

**Comment by tberardini** [comment]
The right way to fix this is to create the missing relationship for the parent terms:

NK T cell activation
--[i] NK T cell proliferation

The regulation terms will then acquire the correct relationships to each other based on the logical definitions and the automatic inference pipeline.

**Comment by bmeldal** [comment]
Thanks. Are you going to add the missing link?

Happy Easter!

**Comment by tberardini** [comment]
done.  I'll close this when the regulation links are inferred and in the ontology,

**Comment by tberardini** [comment]
Inference job added these:

ADD	GO:0051140 'regulation of NK T cell proliferation' GO:0051133 'regulation of NK T cell activation'
ADD	GO:0051141 'negative regulation of NK T cell proliferation' GO:0051134 'negative regulation of NK T cell activation'
ADD	GO:0051142 'positive regulation of NK T cell proliferation' GO:0051135 'positive regulation of NK T cell activation'
