### ISSUE TITLE
NTR DNA 3'-guanosine monophosphate hydrolase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12379]
Hi,

I'm curating PMID:26007660 in which the authors show that hnt3 has 3'-guanosine monophosphate hydrolase activity and I need a new term for this, child of 
GO:0000175 	3'-5'-exoribonuclease activity 

They also show that the enzyme can act on inosine or 6-O-methylguanosine but it is unclear if these are physiologicallty relevant. Would appreciate if you could take a look and advice on whether DNA 3'-guanosine monophosphate hydrolase activity is enough or if I need terms for these other substrates. 

Also a quick check that DNA 3'-guanosine monophosphate hydrolase activity with parent GO:0000175 is the right term to use would be appreciated -  enzyme terms are difficult to place sometimes! :-) Cheers

**Comment by paolaroncaglia** [comment]
Hi Antonia,

I took a look at the paper but don’t have exact answers to your questions. I looked at EC (http://www.chem.qmul.ac.uk/iubmb/enzyme/EC3/1/) and at Rhea (http://www.rhea-db.org/) but I couldn’t find appropriate entries. I’ll ask David Hill and Harold Drabkin at MGI to take a look on the grounds that they are looking at some enzymatic terms for another project and may be more ‘in the zone’ than me. If they can’t provide feedback, I suggest to annotate to GO:0000175 3'-5'-exoribonuclease activity, and you could, if you wish, contact the EC and/or Rhea and ask for help, and add their responses in this ticket. Alternatively, please annotate to GO:0000175 and close this ticket (or tell me if you don’t have permission and I’ll close it).

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
@ukemi @hdrabkin 
Please see my comment above and let us know if you have any suggestions, thanks.

**Comment by hdrabkin** [comment]
I am not surprised that something that would act on GM3'p (Gp) would also show activity against Inosine and , and  6-O-meG., since they are structurally related.

**Comment by paolaroncaglia** [comment]
@ukemi @hdrabkin 
Thanks Harold for your feedback. I take it then, that a specific '3'-guanosine monophosphate hydrolase activity' is not among the enzyme terms you're looking at for your 'side' project?

**Comment by paolaroncaglia** [comment]
Closing this ticket now.
