### ISSUE TITLE
def tweak, mitotic spindle elongation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12376]
GO:0000022
Name	mitotic spindle elongation
Ontology	Biological Process
Definition	The cell cycle process in which the distance is lengthened between poles of the *MITOTIC* spindle. *MITOTIC* spindle elongation begins during *MITOTIC* prophase and ends during *MITOTIC* anaphase B.

**Comment by paolaroncaglia** [comment]
Done, thanks.
