### ISSUE TITLE
MP for "ciliary basal body organization"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#12377]
Hi Paola,

I noticed that the term "ciliary basal body organization" (GO:0032053) doesn't have any relationship to the term "cilium organization" (GO:0044782).

It seems like it should since "ciliary basal body" (GO:0036064) has a relationship (via "ciliary part") to the term "cilium" (GO:0005929)

thanks,

-Karen

@paolaroncaglia

**Comment by krchristie** [comment]
Similarly, it seems that "axonemal microtubule depolymerization" (GO:0060404) should have the relationship part_of "cillium disassembly" (GO:0061523)

**Comment by paolaroncaglia** [comment]
Done.
