### ISSUE TITLE
NTR: Mechanically-modulated voltage-gated sodium ion channel activity 

### ISSUE THREAD

**Issue by abritan** [geneontology/go-ontology#12372]
Hi,
We would like this new term to be created for our annotation project.
See PMID: 21041530 and PMID: 26838316

Thank you in advance.
Best regards,

Aurore Britan.

**Comment by mcourtot** [comment]
Hi Aurore,

Thank you for the request. Could you please provide more information, as per our submission guidelines at https://github.com/geneontology/go-ontology/blob/master/CONTRIBUTING.md.

Specifically, we would need at least "For new term requests, please provide suggestions for label (name), definition, references, position in hierarchy etc."

Thanks,
Melanie

**Comment by abritan** [comment]
Hi Melanie,

Please find below the information requested concerning the new term:

- **Label/name:** Mechanically-modulated voltage-gated sodium channel activity

- **Definition:** Enables the transmembrane transfer of a sodium ion by a voltage-gated channel whose activity is modulated in response to mechanical stress. A voltage-gated channel is a channel whose open state is dependent on the voltage across the membrane in which it is embedded.

- **Parent:** GO:0005248 voltage-gated sodium channel activity

- **References:** PMID: 21041530, PMID: 26838316

Thank you in advance.

Best regards,

Aurore Britan.

**Comment by mcourtot** [comment]
Thanks for the extra information Aurore!

**Comment by dosumis** [comment]
There are some interesting synergies between mechanical and voltage gating in this paper:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3036191/
e.g. "Stretch accelerates voltage-dependent activation and stabilizes the inactivated states"

Perhaps include something about the combined effects of mechano and voltage gating being different from than the sum of each effect alone?  (allows for synergistic and antogonistic effects to be covered).  Where this is not the case, annotating to both mechano and voltage-gated activities should be sufficient.

**Comment by mcourtot** [comment]
Created
id: GO:0101013
name: mechanically-modulated voltage-gated sodium channel activity
