### ISSUE TITLE
NTR: pulmonary blood vessel remodelling re: PMID:22161164

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12371]
Dear Editors,

I wish to request a new term: ‘pulmonary blood vessel remodelling’. This would be a child term of: ‘blood vessel remodelling’ (GO:0001974).

I will subsequently request regulation terms for ‘pulmonary blood vessel remodelling’ in order to annotate findings from paper PMID:22161164.

Specifically, I wish to annotate mmu-miR-17-5p (URS00002075FA_10090) to ‘positive regulation of pulmonary blood vessel remodelling’, based on Figure 2.

Thank you,
Barbara

@rachhuntley 
@RLovering

**Comment by mcourtot** [comment]
Would it be accurate to say that pulmonary blood vessel remodelling is a blood vessel remodelling that occurs in the pulmonary vascular system?

http://purl.obolibrary.org/obo/UBERON_0008886: pulmonary vascular system, "The part of the cardiovascular system consisting of all pulmonary arteries and all pulmonary veins."

Thanks!

**Comment by dosumis** [comment]
Seems reasonable to me.

**Comment by mcourtot** [comment]
Created 
 id: GO:0101010
 name: pulmonary blood vessel remodeling

**Comment by RLovering** [comment]
sorry I should have said yes this seems right to me

**Comment by mcourtot** [comment]
Thanks Ruth :)

**Comment by BarbaraCzub** [comment]
Thank you!
