### ISSUE TITLE
new synonym for  phosphatidylinositol phosphate 4-phosphatase activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12373]
Hi

please could you add the exact synonyms 
PI(4)P-phosphatase activity
PtdIns4P-phosphatase activity
PI4P-phosphatase activity (term used in PMID: 25869668)
and narrow synonym: inositol 4-phosphatase  (term used in PMID: 25869668)

based on the ChEBI record for phosphatidylinositol 4-phosphate
https://www.ebi.ac.uk/chebi/searchId.do;jsessionid=B38F8A125804380772D3C733393BFF9F?chebiId=CHEBI:37530

Thanks
Ruth

**Comment by mcourtot** [comment]
Done rev. 32349
