### ISSUE TITLE
interleukin receptors

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12375]
Apologies, I fear this might make me unpopular:

I have started curating interleukins (ILs) and their receptors (ILRs). Started with IL12 and IL23 (they are related, sharing one ligand and one receptor subunit). Both receptors don't dimerise, they only 'come together' when the IL binds the extracellular domain. I know this is also true for other IL receptors and quite possibly for all IL receptors. Therefore, I don't think the defs for the IL receptors are correct. They should read:
"A protein complex that consists of, at a minimum, a dimeric interleukin and its two receptor subunits."

In the case of IL12R and IL23R, a TYK2 and a JAK2 kinase are attached to each receptor chain, respectively. So the defs may need to be appended by
"[...] as well as optional additional kinase subunits."

There is also no 'interleukin receptor complex' parent term. This seems a bit of an oversight. Shall I create one in TG?

Finally, all ILRs are part_of  GO:0005887 integral component of plasma membrane. This link is missing and needs adding (possibly through inferences if we create the parent term). We'll need it for the refractoring of complexes project.

PMIDs:
25516297 (review with focus of shared receptor subunit IL12RB1)
8943050 (no IP of receptor 'dimer')
11114383 (ligand-receptor interactions)
12023369 (ligand-receptor interactions)
9038232 (receptor binding to JAK2/TYK2)
16482511 (process data)
19088061 (process data)

Please let me know if you need any further info.

Thanks,
Birgit

**Comment by addiehl** [comment]
Hi Birgit,

Thanks for your curation efforts.  Before you consider making a term 'interleukin receptor complex', you ought to consider that interleukins are cytokines, and they are cytokines whose most obvious commonality is that someone decided to call them interleukins.  There was an attempt in the 1980s to provide some systematic naming for a certain set of well studied cytokines secreted by leukocytes.  However the naming scheme eventually became mostly a matter of prestige seeking and was applied quite unevenly to new cytokines as they were discovered.  Interleukins and their receptors fall into multiple families structurally and functionally, and the only real commonality is a lexical one that has been arbitrarily assigned.

If one were going to create grouping terms for cytokine receptor complexes, it would be far more useful to group things by protein superfamilies, rather than by treating all interleukins as some special subclass of cytokine irregardless of their structures or functions.  Multiple classes of cytokine receptor complexes are possible.  This of course may require more study than either you or I have time for, although I did start down this path many years ago, but never finished the GO term request.

I would encourage you to read the following for some more background on interleukin and cytokine naming issues:
http://dx.doi.org/10.1016/S1471-4906(02)02239-1
http://dx.doi.org/10.1016/S1471-4906(02)02336-0

Thanks,
Alex

**Comment by mcourtot** [comment]
Independently of the creation of a term 'interleukin receptor complex' , which @bmeldal will discuss with @addiehl, I can already do the following:

- [ ] update definition of IL receptors to say "A protein complex that consists of, at a minimum, a dimeric interleukin and its two receptor subunits."

- [ ] update definition of IL12R and IL23R to add "[...] as well as optional additional kinase subunits."

- [ ] add link ILRs part_of GO:0005887 integral component of plasma membrane.

Please let me know if this is not accurate.

**Comment by bmeldal** [comment]
@mcourtot that would be great! Then I can use the existing terms to annotate to.

**Comment by bmeldal** [comment]
@addiehl Thank you!
You are absolutely right, I do not have the time to review all interleukins just so I can create functional groups. I had not realised they were grouped so loosely and I agree, function should be the connecting characteristic if any.

However, in the light of what you said, would it make sense to create the term 'cytokine complex' (capable_of GO:0005125 cytokine activity) for the interleukins? At the moment they are children of 'protein complex', not adding any useful hierarchy.

Similarly, one could add 'cytokine receptor complex' as a parent for all the receptor complexes.

I was reviewing a whole bunch of interleukins for Reactome and as part of that was half-way there for their curation in the Complex Portal, which in turn includes the GO annotations!

Thanks for your comment, it was most helpful :)

**Comment by addiehl** [comment]
Hi Melanie,

In regards to your first point it is important to keep in mind that most interleukins (and cytokines in general) are not dimeric, but are rather single chains.  Only IL-12, IL-23, IL-27, and IL-35 are dimers.  Furthermore, not all interleukins and cytokines have receptors with two subunits.  Some have receptors with three subunits, some have soluble single-chain receptors, some have single chain receptors.

Interleukins do not represent a single structural class of proteins, and neither do their receptors.  They are cytokines, and some belong to protein superfamilies are shared among cytokines that happen to be called interleukins and cytokines that are not called interleukins.  The biology and relationships are complex.

I am amenable to the creation of the term, "cytokine receptor complex," with the understanding that no structural description is possible for this complex (it can only be a grouping term), apart from the fact that these are protein complexes which are usually found at the plasma membrane and bind cytokines (most of the soluble cytokine receptors seem to be single chain, though I haven't done an exhaustive check).

-- Alex

**Comment by bmeldal** [comment]
Thanks, Alex. I think all 4 of those ILs are on my list. Shall I request updates to the defs on a case-by-case basis? I have a long list of ILs...

@mcourtot you can definitely go ahead with IL12 and IL23 receptors :)

**Comment by mcourtot** [comment]
@bmeldal: this should actually be dealt with on the PRO side as we just import those terms - I forwarded the ticket there https://sourceforge.net/p/pro-obo/term-requests/107/ and will close this one.

**Comment by mcourtot** [comment]
Those are actually GO - reopening ticket

**Comment by mcourtot** [comment]
HI Birgit,

I did IL12R and IL23R definition updates. They already had the part_of GO:0005887 integral component of plasma membrane.
I see a few other ILRs -do you want me to update definition for those as well and check the part of link?

![screen shot 2016-08-09 at 10 50 20](https://cloud.githubusercontent.com/assets/2214135/17512330/283d2754-5e1f-11e6-87e7-11115da9759d.png)

**Comment by bmeldal** [comment]
Alex is correct in saying that many ILs and their receptors are single chains or multi-chains with >2 subunits so the originally proposed, generic structural addition to the def is wrong and should only be applied to selected IL receptor complexes. 

I don't have time to go through all of them right now as I have finished the checking for Reactome where this originally came from and no time to curate more complexes into CP but I have a set of new IL10 reactions from Steve so if I find anything there I will request updates. 

However, looking at my notes, I have the following IL's as dimers:

IL20 receptor: 
GO:0030876 interleukin-20 receptor complex
-Def: A protein complex that binds interleukin-20; comprises an alpha and a beta subunit. 
+Def: A protein complex composed of an alpha and a beta receptor subunit and an interleukin ligand. In human, Interleukin-19, -20 and -24 bind IL20RA/IL20RB receptor subunits and Interleukin-20 and -24 bind IL22RA1/IL20RB receptor subunits.
PMID:12351624

GO:0032002 interleukin-28 receptor complex:
-Def: A protein complex composed of an alpha and a beta receptor subunit (in human IFNLR1/IL28Ralpha & IL10RB) and either Interleukin-28 (IFNL2 or IFNL3) or Interleukin-29 (IFNL1). 
PMID:12469119, PMID:12483210

And these, not in GO:
IL15 receptor: IL15RA, IL2RB & IL2RG (PMID:23104097, PDB:4gs7) - not a GO CC term!
IL17: lots of isoforms and hence lots of dimeric combinations, but - not a GO CC term!
IL22 receptor: IL22RA1 & IL10RB bind IL22 (PMIB:15120653 for binaries) but - not a GO CC term!
IL31 receptor: IL31RA & OSMR or IL31RA dimer binds IL31 (PMID:15194700), but - not a GO CC term!
IL33 receptor: IL1RAP & IL1RL1 binds IL33 (PMID:17675517 & PMID:16286016), but - not a GO CC term!
IL34: is a homodimer (PMID:22483114) or possibly tetramer (PMID:22579672) but - not a GO CC term!

Birgit

**Comment by mcourtot** [comment]
Are you requesting the missing receptors, or are you ok for now not having them?

**Comment by bmeldal** [comment]
I don't need them right now but if anyone is requesting them then there's a record of those that are multimeric! (And I can check back on it when I eventually get round to doing them :) )

**Comment by mcourtot** [comment]
Thanks birgit. I updated ILR20 and 28 and will close this ticket now. Let me know if anything else is missing.
