### ISSUE TITLE
heart induction relation to heart development

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12374]
Hi David

Looking at the Notch signalling graph it looks to me like GO:0003129 heart induction should be a part_of child of heart development, as GO:0003137 Notch signaling pathway involved in heart induction is a part_of child to heart development.

Im not sure that the figure will be visible but if it isn't I'm sure you can find it yourself
![screen shot 2016-04-01 at 08 54 32](https://cloud.githubusercontent.com/assets/12080010/14201298/e99b5ff8-f7e8-11e5-829c-6dc21e37e710.png)

Best

Ruth

**Comment by RLovering** [comment]
oh it is visible that is nice!

**Comment by ukemi** [comment]
Hmmm. I think the link to the heart development term should be removed. Heart development doesn't start until the heart is specified. I think it should just be a type of Notch signaling pathway.

**Comment by mcourtot** [comment]
Hi @RLovering 

Based on the current definition of 'heart indication' = The close range interaction between mesoderm and endoderm or ectoderm that causes cells to change their fates and specify the development of the heart.

and the remark from David about induction happening before heart development starts, what would be your desired resolution?

Cheers,
Melanie

**Comment by cmungall** [comment]
here is the current path between heart induction and development

![heart](https://cloud.githubusercontent.com/assets/50745/14287293/128b3a16-fb07-11e5-80ec-534414b0b776.png)

**Comment by RLovering** [comment]
Im happy with the ontology Chris has included, Im not sure why this doesn't appear in QuikGO.

But this suggests that GO:0003137 Notch signaling pathway involved in heart induction should not have an is_a relation to GO:0003137 Notch signaling pathway involved in heart development!

Instead we need induction grouping terms 
GO:0003129 heart induction
>is_a NTR cell surface receptor signaling pathway involved in heart development
then move all the signalling specific terms under here as is_a child terms
GO:0003130 BMP signaling pathway involved in heart induction
GO:0003135 fibroblast growth factor receptor signaling pathway involved in heart induction
GO:0003137 Notch signaling pathway involved in heart induction

But note that presumably this means that all induction terms in the ontology need to revised so that they positively regulate the development (or child term) process, and all induction signalling terms need to be removed from any is_a parent development terms.

But if David doesn't like the heart induction regulating heart development then this needs to be sorted out too.

Ruth

**Comment by ukemi** [comment]
I am pretty sure that all the induction terms positively regulate the appropriate field specifications, at least they did when Tanya and I did all the original development edits a long time ago. This was all based on the decision that in GO an anatomical structure starts to develop once it exists. It gets around issues such as oogenesis in my mother being part of my development.

**Comment by cmungall** [comment]
On 5 Apr 2016, at 9:00, Ruth Lovering wrote:

> But this suggests that GO:0003137 Notch signaling pathway involved in 
> heart induction should not have an is_a relation to GO:0003137 Notch 
> signaling pathway involved in heart development!
I only showed some paths to avoid hairballs - sorry for the confusion

**Comment by mcourtot** [comment]
@RLovering: Here is the QuickGO chart (highlighting those terms used by Chris above) - it seems to match. Please confirm this is ok on your side too and I'll close the ticket.

![screen shot 2016-04-06 at 09 17 55](https://cloud.githubusercontent.com/assets/2214135/14310210/98b833d8-fbd8-11e5-8e18-ec8e0ec97951.png)

**Comment by RLovering** [comment]
Hi Melanie How do you get that QuickGO view? I still get the same as before
![screen shot 2016-04-06 at 11 49 14](https://cloud.githubusercontent.com/assets/12080010/14314199/c53bbe7e-fbed-11e5-8246-cb1b353c5609.png)

Please don't close this until the induction signalling terms have been removed from under the 'signalling involved in heart development' as this is incorrect
Thanks
Ruth

**Comment by RLovering** [comment]
Hi sorry Ive just looked again and I have the heart induction regulating heart specification in the QuickGO graph now. must have just not refreshed properly.

**Comment by mcourtot** [comment]
As per above:
GO:0003137 Notch signaling pathway involved in heart induction
should NOT be a is_a child of 
GO:0061314 Notch signaling involved in heart development

There was an error in the ontology, where GO:0003137 Notch signaling pathway involved in heart induction which is logically defined as 'Notch signaling pathway'
 and ('part of' some 'heart induction') , was additionally asserted under GO:0061314 Notch signaling involved in heart development instead of GO:0007219, Notch signaling pathway.

This should now be fixed.

**Comment by mcourtot** [comment]
Fixed GO:0003130 BMP signaling pathway involved in heart induction and
GO:0003135 fibroblast growth factor receptor signaling pathway involved in heart induction as well.
I *think* that addresses it all - or at least after reasoning the classes seem to be in the right place (i.e., not under heart development)

@ukemi: as you did extensive work on that part with Tanya, would you mind having a quick look and check that
GO:0003137 Notch signaling pathway involved in heart induction
GO:0003130 BMP signaling pathway involved in heart induction
GO:0003135 fibroblast growth factor receptor signaling pathway
look good to you as well?

**Comment by mcourtot** [comment]
Fixes were done April 6 and seem ok - closing.
