### ISSUE TITLE
membrane tubulation/curvature

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12387]
1.
GO:0097320 membrane tubulation
is defined
A modification in a plasma membrane resulting in formation of a tubular invagination. 
(check: maybe should this really be "plasma membrane curvature" to fit the definition, it sounds as though it might be describing the 'membrane curvature' process which results in invagination  ?)

2.
add new term
GO:XXXXXX membrane curvature

3.
GO:0071787 endoplasmic reticulum tubular network assembly
(probably should be renamed 'formation'?  it isn't really "assembly' as such?)
Name    endoplasmic reticulum tubular network assembly

4.
And made  a descendent  of GO:1990809
GO:1990809 endoplasmic reticulum tubular network membrane organization

5.
New term
GO:xxxxxx membrane curvature involved in  endoplasmic reticulum tubular network formation

(membrane curvature can then be used for all of the proteins like BAR domain and reticulon which introduce membrane curvature in various contexts (cytokinesis, tubulation etc)

**Comment by paolaroncaglia** [comment]
Hi Val,

Sounds good, but could you please add more details, especially for the proposed new terms. See our recent guidelines below - please understand that we have to deal with many requests and that eliminating guesswork benefits both parties, editors as well as curators. 

https://github.com/geneontology/go-ontology/blob/master/CONTRIBUTING.md

Thanks!

**Comment by ValWood** [comment]
Also
 GO:0070583	spore membrane bending pathway
(Paola I'll put this on my todo list but no hurry for me so it will probably sit for a while unless anyone needs it sooner). 
There appear to be 3 mechanisms for the introduction of membrane curvature by proteins:
https://en.wikipedia.org/wiki/Membrane_curvature

(PomBase has a number of papers in this area, but they are  not on our immediate priority lists).

**Comment by ValWood** [comment]
I can't find the ticket  or e-mail which prompted me to open this ticket as a 'placeholder'. It was a discussion about "membrane curvature/invagination/bending" the same day, or day before I opened this ticket.....
I don't suppose anyone else remembers.......

"lipid tube assembly" sounds like the same thing too.....

**Comment by paolaroncaglia** [comment]
@ValWood I found the email, I'll send it to you

**Comment by Pauldenny** [comment]
PMID: 27170174 is relevant to processes of sensing, bending, and stabilizing curved membranes, involving endophilin

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

Summarising all comments in this request:

“1.
GO:0097320 membrane tubulation
is defined
A modification in a plasma membrane resulting in formation of a tubular invagination. 
(check: maybe should this really be "plasma membrane curvature" to fit the definition, it sounds as though it might be describing the 'membrane curvature' process which results in invagination ?)”

To me, it sounds like GO:0097320 ‘membrane tubulation’ (“A modification in a plasma membrane resulting in formation of a tubular invagination.”) should be is_a GO:0099024 ‘plasma membrane invagination’ (“An infolding of the plasma membrane.”). This is confirmed by the abstracts of the PMIDs used as dbxrefs for the term (PMID: 15252009 and PMID: 20730103). Whether it should more specifically refer to the plasma membrane curvature step which eventually results in invagination, I’m not sure, would need to read the full text and see how it’s been used in annotations. It has 55 manual experimental annotations, plus 9 to regulation terms, mostly from FlyBase and UniProt. 

“2.
add new term
GO:XXXXXX membrane curvature”

To me, ‘curvature’ sounds more like a quality than a process. It’s used in GO as such (e.g. def of ‘endoplasmic reticulum tubular network’: “A subcompartment of the endoplasmic reticulum consisting of tubules having membranes with high curvature in cross-section.”). We may wish to use a different wording, but I gladly accept suggestions from native speakers ;-) Maybe ‘membrane bending’ with ‘membrane curvature’ as a related synonym? Similar to GO:0070583 ‘spore membrane bending pathway’ that you also pointed to in this ticket.
In defining this process, we could refer to https://en.wikipedia.org/wiki/Membrane_curvature#Proteins_can_Induce_Curvature (as you also suggested). I’d have to look in more detail to see if we’d need specific children too. And of course there are recent reviews on the subject. Plus, @Pauldenny  suggested that “PMID: 27170174 is relevant to processes of sensing, bending, and stabilizing curved membranes, involving endophilin.”
At a first glance, I’m not sure if or how we’d want to link ‘membrane curvature’ and ‘membrane tubulation’, if the latter becomes is_a GO:0099024 ‘plasma membrane invagination’. 

“3.
GO:0071787 endoplasmic reticulum tubular network assembly
(probably should be renamed 'formation'? it isn't really "assembly' as such?)”

‘endoplasmic reticulum tubular network formation’ is already an exact synonym, but I’m happy to swap it with the primary name if that better reflects community usage

“4.
And [GO:0071787 endoplasmic reticulum tubular network assembly] made a descendent of GO:1990809
GO:1990809 endoplasmic reticulum tubular network membrane organization”

Not really, as GO:0098826 ’endoplasmic reticulum tubular network membrane’ is bounding_layer_of GO:0071782 ’endoplasmic reticulum tubular network’. 

“5.
New term
GO:xxxxxx membrane curvature involved in endoplasmic reticulum tubular network formation
(membrane curvature can then be used for all of the proteins like BAR domain and reticulon which introduce membrane curvature in various contexts (cytokinesis, tubulation etc)”

Sounds good, pending point 2 above. 

I will now look at the related ticket https://github.com/geneontology/go-ontology/issues/12583 (opened by @BarbaraCzub.

**Comment by ValWood** [comment]
1. Agree
2. Agree, "membrane bending" is a better term name (curvature related synonyms)
Eventually as required 'membrane bending involved in x' could be added to processes which have a 'membrane bending' component.
3. Are assembly and formation equivalent in GO, if so yes I think the swap would work
4.  Ah OK its 'membrane' organization
5. Yes, see my response to 2.

That all seems to work out. That should give a framework that any of the unconnected terms can be placed under.

**Comment by ValWood** [comment]
I wonder if "membrane bending"
should be a Molecular function, rather than a biological process?
https://en.wikipedia.org/wiki/Membrane_curvature#Proteins_can_Induce_Curvature

@ukemi @thomaspd

**Comment by ukemi** [comment]
It seems like even in the cases described here, a single instance of bending is carried out by the action of more than instance of a gene product. I think that would make it a process.

**Comment by ValWood** [comment]
Of course. So  what are the individual proteins doing?
lipid binding part_of membrane bending?

**Comment by ukemi** [comment]
That is what I had in mind, but we need to be careful if there are cases where the protein is lipid modified. If the binding is being done by a lipoprotein that inserts itself into the membrane, is it still lipid binding?  I guess it is. I'm not sure if this is ever the mechanism for bending, but it is certainly the way some proteins interact with membranes.

**Comment by thomaspd** [comment]
I don’t think the number of one type of gene product is the right distinction between MF and BP.  I think the number of distinct types of activity is the right distinction.  For example, one way to increase the activity is to increase the number of gene products (of the same type) that each perform the process.  So “instance” of a gene product in general refers to a population, as is generally assumed in biochemical representations.

**Comment by dosumis** [comment]
> DPH
> It seems like even in the cases described here, a single instance of bending is carried out by the action of more than instance of a gene product. I think that would make it a process.

> PDT
> I don’t think the number of one type of gene product is the right distinction between MF and BP.  I think the number of distinct types of activity is the right distinction. 

Sorry for side track.  Just want to note that this is a general issue that it would be useful to resolve as there are big implications for the way we model regulation in LEGO.

**Comment by ValWood** [comment]
I agree. We have always had this problem. DNA polymerase is a single activity spread among a number of genes. We also have problems describing the activity of, for example a  "ribosome". It usually ends up with a mish-mash of RNA binding, structural activity molecular functions (which are sometimes also valid functions). However, the primary elemental activity of the ribosome is 
 as a "peptidyl transferase". Remarkably, this term only has 4! experimental annotations!

I guess some issues will be resolved by the ability to annotate "complex objects" in addition to "gene product objects".  Still, we need better guidelines about what constitutes an activity. Its independent of the number of genes for sure. I think of it as  an elemental part of a process which cannot be decomposed further....I'm sure there's a better way to articulate this ;)

I this case I do think "membrane bending" might be a  valid molecular function...

**Comment by krchristie** [comment]
When I was at SGD, I remember wanting a term for "membrane bending". It's been a while, so I'm a little hazy on details and no longer remember which gene this was, but I definitely thought that "membrane bending" was the accurate description of its function.   

-Karen

P.S. There's probably an old SourceForge ticket on this because I requested terms, but I think that ticket stalled.

**Comment by paolaroncaglia** [comment]
Hi @krchristie ,
You were probably thinking of this old ticket, see your comment here https://github.com/geneontology/go-ontology/issues/11280#issuecomment-124916490. I think it's fine to continue the discussion we started on 'membrane bending' here (as soon as I have a chance to do so...), but if there's anything from that old ticket that you'd like to report/summarize here, please feel free. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
I addressed point 1) in my comment https://github.com/geneontology/go-ontology/issues/12387#issuecomment-252883795 by doing the edits in https://github.com/geneontology/go-ontology/issues/12583#issuecomment-268312161. 
I'll address the other points after the holidays.

**Comment by ValWood** [comment]
Have o great break, speak to you in the New Year.
Val

**Comment by paolaroncaglia** [comment]
Hi @ValWood,
Back to point 2 in https://github.com/geneontology/go-ontology/issues/12387#issuecomment-252883795 i.e. “add new term GO:XXXXXX membrane curvature”. Summarising input from you and others in this ticket, so far we agreed on:

name: membrane bending
synonym: membrane curvature [related]

Open questions:

1) Should ‘membrane bending’ be a BP or an MF? What are the individual proteins doing? ‘lipid binding’ part_of ‘membrane bending’?
Based on the examples in https://en.wikipedia.org/wiki/Membrane_curvature#Proteins_can_Induce_Curvature, it seems to me that the mechanisms can be multiple and diverse enough that it would be difficult to say that ‘membrane bending’ has_part e.g. ‘lipid binding’. And I wouldn’t say that ‘lipid binding’ is part_of ‘membrane bending’ either - lipids may also form micelles - we probably wouldn’t capture that in GO, but it’d still be true that lipids can bend without forming membranes. Looking at the clathrin example, I’d say that clathrin-mediated membrane bending involves recruitment of clathrin to the membrane through signaling molecules (a process), assembly of clathrin molecules into larger polymeric structures that form a rigid structure which serves as a frame for the membrane (protein binding? i.e. a function), binding of clathrin to its receptors in the membrane (again protein binding, but a different event than the previous one). To me, all this makes ‘clathrin-mediated membrane bending’ a BP. It seems that the safest way to go would be to create a generic BP term for ‘membrane bending’ with specific children for the mechanisms we know (such as the clathrin one). A recent review on the subject, PMID:25774051, points in the same direction (“…it is very likely that additional mechanisms underlying membrane shaping will be uncovered in the near future…”). If we can reach agreement on this shortly, I could start on a basic structure:

- [ ] add 
GO:NEW membrane bending
is_a membrane organization
Def: A membrane organization process resulting in the bending of a membrane.
GOC:pr, GOC:vw, https://en.wikipedia.org/wiki/Membrane_curvature
synonym: membrane curvature [related]

GO:NEW membrane bending, and its regulation terms (easy to create via TG), could respond to some annotation needs e.g. @krchristie’s. 'membrane bending involved in x' terms could also be created via TG if/as needed. E.g., @ValWood could create GO:NEW ‘membrane bending involved in endoplasmic reticulum tubular network formation’ once I have done the following:

- [ ] Swap primary name and exact synonym of GO:0071787 ‘endoplasmic reticulum tubular network assembly’ so it becomes ‘endoplasmic reticulum tubular network formation’.

With these edits, I’d have addressed the key requests from @ValWood in this ticket. 

- [ ] A careful examination of PMID:25774051 could provide tips on further dissecting ‘membrane bending’ and suggest proteins to annotate to it or to its regulation. This could be done in a second stage and by others if I can’t get to it.

- [ ] I could also add
GO:NEW clathrin-mediated membrane bending
is_a GO:NEW membrane bending
has_part clathrin coat assembly
Def: A membrane bending process mediated by clathrin.
GOC:pr, https://en.wikipedia.org/wiki/Membrane_curvature

But if this topic needs more extensive discussion, I will need to leave it at that and unassign myself from this ticket. :-)

**Comment by ValWood** [comment]
I agree with all of your points above. I think these basic changes would be useful, and allow us to 
incrementally make any adjustments required. It addresses the overall problem.

**Comment by paolaroncaglia** [comment]
Done. The new terms are

 [Term]
+id: GO:0097753
+name: membrane bending
+namespace: biological_process
+def: "A membrane organization process resulting in the bending of a membrane." [GOC:krc, GOC:pr, GOC:vw, http://en.wikipedia.org/wiki/Membrane_curvature]
+synonym: "membrane curvature" RELATED []
+is_a: GO:0061024 ! membrane organization

+[Term]
+id: GO:0097754
+name: clathrin-mediated membrane bending
+namespace: biological_process
+def: "A membrane bending process mediated by clathrin." [GOC:pr, http://en.wikipedia.org/wiki/Membrane_curvature]
+is_a: GO:0097753 ! membrane bending
+relationship: has_part GO:0048268 ! clathrin coat assembly

**Comment by paolaroncaglia** [comment]
Left to do for this ticket, and not urgent:

- [ ] A careful examination of PMID:25774051 could provide tips on further dissecting ‘membrane bending’ and suggest proteins to annotate to it or to its regulation. This could be done in a second stage and by others if I can’t get to it.

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
The only task remaining for this ticket is low priority and pertains to annotation as well as ontology. I'll assign it to you since you opened the ticket originally and so it doesn't fall through the cracks. Thanks.

**Comment by ValWood** [comment]
I'll close this one (effectively un-assigning myself).

I'm going to open a new ticket though :(
