### ISSUE TITLE
TPV F-P link protein disulfide isomerase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12385]
GO:0003756	protein disulfide isomerase activity
does this always occur as part of protein folding/refolding?
(I don't think all isomerization is 'folding' is it?)

**Comment by paolaroncaglia** [comment]
This summary in Wikipedia supports Val's point, so I will remove the link:

https://en.wikipedia.org/wiki/Protein_disulfide-isomerase#Function

**Comment by paolaroncaglia** [comment]
Done.
