### ISSUE TITLE
lactation multiple issues

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12382]
lactation is defined
The secretion of milk by the mammary gland.
https://github.com/geneontology/go-ontology/issues/12381
will resolve transport parentage issue if this is  a tissue level process.

However lactation seems to include more than just secretion. I looked at the annotations and it includes milk proteins like caseins which does not seem particularly incorrect for "lactation" but does seem wrong for "The secretion of milk by the mammary gland"

Maybe lactation needs a broader definition?
Lactation  can mean the secretion of milk from the mammary glands and the period of time that a mother lactates to feed her young.

Since lactation in GO includes the ancestor "mammary gland development" it seems to be the broader 
period of time + hormones which influence this rather than secretion per se.

**Comment by paolaroncaglia** [comment]
Note for self: see also https://github.com/geneontology/go-ontology/issues/11995

**Comment by mcourtot** [comment]
Looking at Ruth's comments in #12381, I suggest:

 GO:0007595, lactation:

- [ ] update definition from “The regulated release of milk by the mammary gland.” to “The secretion of milk from the mammary glands and the period of time that a mother lactates to feed her young”
- [ ] remove is-a GO:0032941 secretion by tissue 

GO:0060156, milk ejection:

- [ ] add part_of some lactation
- [ ] add  is_a relation to GO:0032941 secretion by tissue and GO:0007589 body fluid secretion.

**Comment by mcourtot** [comment]
Done revision 38641.
