### ISSUE TITLE
weird inferred relationships: regulation of spindle organization/spindle elongation terms

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12380]
From build-go-assert-inferences-preview - Build # 88 
http://build.berkeleybop.org/job/build-go-assert-inferences-preview/88/

Added axioms (count 5) (one removed)
ADD	GO:0032932 'negative regulation of astral microtubule depolymerization' GO:0031117 'positive regulation of microtubule depolymerization'
ADD	GO:0090224 'regulation of spindle organization' GO:0031114 'regulation of microtubule depolymerization'
ADD	GO:1902120 'negative regulation of meiotic spindle elongation' GO:0031117 'positive regulation of microtubule depolymerization'
ADD	GO:1902845 'negative regulation of mitotic spindle elongation' GO:0031117 'positive regulation of microtubule depolymerization'

**Comment by tberardini** [comment]
I think these might be trickle down effects from my merge of [meiotic/mitotic] spindle stabilization terms into the [meiotic/mitotic] spindle organization terms. 

https://github.com/geneontology/go-ontology/issues/12294

**Comment by paolaroncaglia** [comment]
Hi @tberardini , 

Is it ok if I assign this to you then? In general, we tend to assign cell cycle-related tickets to @ukemi, but I see that #12294 is yours... and you made the merge above... but you'll let me know if this is not ok.

Thanks!

**Comment by paolaroncaglia** [comment]
Hi @tberardini , 

Is it ok if I assign this to you then? In general, we tend to assign cell cycle-related tickets to @ukemi, but I see that #12294 is yours... and you made the merge above... but you'll let me know if this is not ok.

Thanks!

**Comment by tberardini** [comment]
Removed three bogus relships to + reg term.  Tested in Protege, they didn't come back.

-is_a: GO:0031117 {is_inferred="true"} ! positive regulation of microtubule depolymerization
-is_a: GO:0031117 {is_inferred="true"} ! positive regulation of microtubule depolymerization
-is_a: GO:0031117 {is_inferred="true"} ! positive regulation of microtubule depolymerization

The bogus relship to reg term was already gone in the obo file.  

Closing.  Will reopen if they reappear.
