### ISSUE TITLE
fork barrier binding synonym move

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12388]
I have just put this into TermGenieFreeForm:

ID: GO:1990943 Label: mating type region replication fork barrier binding

This term should have the exact synonyms "RTS1 barrier binding" and "RTS1 element binding", but I could not include them with the TGFF submission because both are already, and erroneously, exact synonyms of GO:0043110.

Could someone please move these synonyms from GO:0043110 to GO:1990943?

Also see SO ticket https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/350

Thanks,
m

**Comment by ValWood** [comment]
I think there are RTS barrier elements in mating type region and in rDNA spacers.... will check...

**Comment by ValWood** [comment]
Ignore me. RTS1 is the mating site specific barrier

**Comment by paolaroncaglia** [comment]
Done, thanks.
