### ISSUE TITLE
Exosome assembly and secretion

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12386]
I’d like to add a new term to cover exosome assembly & secretion. The two existing terms are:
extracellular exosome assembly ; GO:0071971 
exosomal secretion ; GO:1990182  

I want to link them for 2 reasons: 
1. Assays often can’t distinguish between the formation of the vesicle and secretion of the extracellular exosome (where they assay for extracellular exosome levels). 
2. To become an extracellular exosome the exosome must, by definition, be secreted.  

Suggested new term:  
extracellular exosome biogenesis ; GO:NEW 
—[partof]extracellular exosome assembly ; GO:0071971
—[partof]exosomal secretion ; GO:1990182  

extracellular exosome biogenesis ; GO:NEW 
The assembly and secretion of an extracellular exosome, a membrane-bounded vesicle that is released into the extracellular region by fusion of the limiting endosomal membrane of a multivesicular body with the plasma membrane. 
Exact synonym: exosome biogenesis [PMID: 19442504, PMID: 25392495]
Exact synonym: exosome assembly or secretion [GOC:bf]
Exact synonym: exosome production [PMID: 25392495]
is_a: cellular component biogenesis ; GO:0044085  
PMID: 19442504 (review) 
PMID: 25392495 (assays I am curating to capture the role of PARK9/ATP13A2)
GOC:PARL, GOC:bf

I can add in myself, but adding to Github for comments in case there is a better name for the grouping term. 
Thanks!

**Comment by paolaroncaglia** [comment]
Hi Becky,

Would you like me to run this by our collaborators on the extracellular vesicles project?

Cheers,

Paola

**Comment by rebeccafoulger** [comment]
Yes please @paolaroncaglia!

**Comment by paolaroncaglia** [comment]
Emailed Kei and Louise, and cc'd Becky.
Assigning this ticket to her now, but I'll monitor it.

**Comment by rebeccafoulger** [comment]
PMID:24603074 says:
Inward budding of the MVB (multi vesicular body) outer membrane into the lumen produces multiple intraluminal vesicles (ILVs). MVBs can fuse with the plasma membrane and release ILVs extracellularly as exosomes.

PMID: 25979354 says:
exosomes are intraluminal vesicles (ILVs) contained in MVBs, which are released to the extracellular environment upon fusion of MVBs with the plasma membrane

Therefore add two related synonyms to 'extracellular exosome assembly ; GO:0071971':
ILV assembly [PMID: 24603074, 25979354]
intraluminal vesicle assembly [PMID: 24603074, 25979354]

**Comment by BarbaraCzub** [comment]
Hello, as this is Rebecca's last day at UCL, I will be following up on this ticket from now on. Paola, could you please re-assign this back to yourself?
Thanks,
Barbara

@rebeccafoulger 
@paolaroncaglia 
@RLovering

**Comment by paolaroncaglia** [comment]
Done @BarbaraCzub .

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub ,
The new term is GO:0097734 ’extracellular exosome biogenesis’.
All done as suggested by Rebecca and as validated with our two direct collaborators on the extracellular RNA/vesicle project. They had offered to run this by a wider group of experts for final confirmation, but we didn’t hear back from them. If new evidence emerges allowing to further connect or expand this branch of the ontology, we will add to it. Closing now.
