### ISSUE TITLE
protein conformation change

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12384]
Hi

Im not sure how you are going to feel about this one. Val doesn't think that changing the conformation of a mature protein is a type of protein folding, but I would like to capture that APOA2 influences the conformation of APOA1 within an HDL particle. APOA2 and APOA1 are structural proteins in HDL, although APOA1 also affects the enzyme activity of lecithin:cholesterol acyltransferase. So this seemed like an option:

GO:0009987 cellular process
>is_a New term protein conformational change
Definition:
A cellular process that results in a change in the spatial configuration of a protein molecule. A conformation change can alter the quarternary, tertiary or secondary structure of the protein. This process can occur immediately post-transcriptionally, for example by chaperones, or to a mature protein due to environmental factors or following binding to another molecule. 
exact synonym:  protein conformation change
DbxRef: GOC:BHFL, GOC:rl
http://www.ncbi.nlm.nih.gov/pubmed/14967812 and http://www.ncbi.nlm.nih.gov/pubmed/22235130. 
>is a child term: GO:0006457 protein folding

I am not sure if you would like to create the more specific term:
protein conformational change involved in plasma lipoprotein particle remodeling, rather than me including this additional information in AE field.
This would have the part of parent term:
GO:0034369 plasma lipoprotein particle remodeling 

The problem is that many protein interactions and phosphorylations etc lead to a change in the protein conformation and I don't think this is something we would we want to capture. Another option would be just to create the more specific term?

Thanks

Ruth

@ValWood

**Comment by ValWood** [comment]
I still don't think that conformational changes are protein folding.

Protein folding happens to the native protein, as it proceeds from an unfolded state to a folded state.
https://en.wikipedia.org/wiki/Protein_folding
I still think that conformational changes are probably out of scope for GO....

**Comment by Antonialock** [comment]
Presumably it is a "regulator activity"? Like cyclins that have no enzymatic activity apart from binding

**Comment by Antonialock** [comment]
(and at least we only annotate cyclins to "cyclin-dependent protein serine/threonine kinase regulator activity" not to "protein folding" even though according to wikipedia:

"The structure of human Cdk2 revealed that CDKs have a modified ATP-binding site that can be regulated by cyclin binding.[1] Phosphorylation by CDK-activating kinase (CAK) at Thr 161 on the T-loop increases the complex activity. Without cyclin, a flexible loop called the activation loop or T-loop blocks the cleft, and the position of several key amino acid residues is not optimal for ATP-binding.[1] With cyclin, two alpha helices change position to permit ATP binding. One of them, the L12 helix that comes just before the T-loop in the primary sequence, becomes a beta strand and helps rearrange the T-loop, so it no longer blocks the active site.[1] The other alpha helix called the PSTAIRE helix rearranges and helps change the position of the key amino acid residues in the active site.[1]"

= sounds like a conformational change to me?

**Comment by ValWood** [comment]
Yes that what I said in my original e-mail to Ruth. Most enzyme regulators will make cause some conformational change. That's why I thought it was probably out of scope.
v

**Comment by paolaroncaglia** [comment]
Hi @RLovering , @ValWood and @Antonialock ,

The proposed new term 'protein conformational change' sounds out of scope for GO for me, too. 
Therefore I'm closing this ticket.

Thanks,
Paola

**Comment by RLovering** [comment]
Thanks for looking at this, I think you are right, I meant to close it last week but didn't get round to it
Best
Ruth
