### ISSUE TITLE
centromere clustering

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12389]
We have a term which  we use for fission yeast

centromere clustering at the nuclear envelope
A cellular localization process in which kinetochores/centromeres are coupled together at the nuclear periphery. This process is responsible for the Rabl-like configuration of chromosomes in the interphase nuclei. In fission yeast this occurs at a location near the old mitotic spindle pole body. 

This represents the period when the centromeres are clustered together with the spindle pole body at the nuclear periphery and happens during interphase.
In metaphase the centromeres are still coupled together but they aren't clustered at the nuclear envelope near the spindle pole body, because they begin to migrate and align at the metaphase plate.

I'm therefore confused by the parent term which is:
 GO:0098653 centromere clustering
The process by which centromeres/kinetochores become localized to clusters. In Saccharomyces cerevisiae, kinetochores form a single cluster before metaphase and later in the cell cycle appear as two clusters.

Here it  isn't clear what, is clustered with what?
When the kinetochores split they are no longer in clustered with anything so they can't be described as 2 clusters  (they look like 2  spatially separated dots instead of  2 dots 'clustered' with the SPB (and this separation doesn't happen until anaphase?).

**Comment by dosumis** [comment]
> Here it isn't clear what, is clustered with what?

With each other. The gloss is just an example.   Perhaps looking at the sister term will make the grouping clearer?

**Comment by ValWood** [comment]
I looked at the yeast paper  (one annotation SLK9) and its describing a different  thing to the pombe papers.....
These seem to be different processes (or maybe they are different aspects of the same process)?

The pombe papers are describing the clustering of the centromeres/kinetochores  by linking to the nuclear envelope in interphase.
The cerevisiae paper is describing the connection  of sister chromatid kinetochores, and of different chromosome kinetochores to each other.


The cerevisiae paper is describing the attachment of

**Comment by ValWood** [comment]
http://europepmc.org/abstract/MED/10761928
and
http://europepmc.org/abstract/MED/8486732
are not the correct PMIDs for GO:0098653

**Comment by ValWood** [comment]
We shoudl obsolete this term:
GO:1990571 meiotic centromere clustering
It sin't correctly defined and it has no annotations.

**Comment by dosumis** [comment]
If both examples result in clustering together of centromeres (by whatever mechanism) then I think the general term is valid.

**Comment by ValWood** [comment]
http://europepmc.org/abstract/MED/21965289
is attached to  GO:0072766	centromere clustering at the nuclear envelope
seems to be describing  something more similar to  the parent definition.

I think we have 2 different types of centromere/kinetochore clustering here:

i) in interphase where the centromere/ kinetochores of *different chromosomes* are clustered with the SPB  at the nuclear envelope
ii) after pro-metaphase when the kinetochores of sister chromatids are still attached to each other ( but not the nuclear envelope or the SPB...)

They are quite different....but a broad grouping term will be fine.

**Comment by ValWood** [comment]
GO:0072766 centromere clustering at the nuclear envelope
has 
related	centromere-SPB clustering (should really be exact)
Probably we should rename to
GO:0072766 centromere-SPB clustering at the nuclear envelope


GO:0098653 centromere clustering
The process by which centromeres/kinetochores become localized to clusters. In Saccharomyces cerevisiae, kinetochores form a single cluster before metaphase and later in the cell cycle appear as two clusters.

could be
The process by which centromeres/kinetochores become clustered together. This includes both kinetochore-kinetochore clustering and kinetochore clustering with the nuclear envelope and spindle pole body.

**Comment by ValWood** [comment]
Details on these processes in pombe our phenotype tracker 
https://github.com/pombase/curation/issues/890

I still can't figure out which if any of these the SLK19 annotation refers to
http://europepmc.org/abstract/MED/23283988
as I don't know  how to interpret the images. Somebody from SGD would need to comment on this.

**Comment by Antonialock** [comment]
Val for the meiotic terms we also have this:
GO:0051455
attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation
http://www.ebi.ac.uk/QuickGO/GMultiTerm#a=64%240CZ]7b[h&tab=chart&c=

We have a few genes annotated to it
http://www.pombase.org/spombe/related/GO:0051455

**Comment by ValWood** [comment]
This is OK, there isn't a problem with the meiotic terms. I think the problem is that  a small number of papers (not many) refer to the events at mitotic congression as "clustering" but usually clustering refers to the really close association of the kinetochores with the SPB  and the nuclear envelope observed between anaphase B, through interphase to the following metaphase.

The part where the kinetochores are not so close (i.e not really "clustered" together), they are only together in that they are all associated with the metaphase spindle, isn't usually called 'clustering' because you can discriminate the  individual chromosome pairs for I,II and III.

I hope I managed to summarize this on our curation tracker here:
pombase/curation#890

**Comment by paolaroncaglia** [comment]
Assigning to David H as cell cycle-related. Thanks David.

**Comment by ukemi** [comment]
Hi Val. I agree with David OS. I think that the issue you are having is that the gloss of GO:0098653 gives an example that is not necessary for the term. It is just an example. The 'real' definition of the term is: 'The process by which centromeres/kinetochores become localized to clusters'. The rest of that definition describes specific contexts. I think we should simply remove the gloss and keep the generic definition.

**Comment by ukemi** [comment]
Have a look at this paper: PMID:23562326

**Comment by ValWood** [comment]
Yes I think just strip the gloss.

PMID:23562326 is what I think of as clustering. The centromeres are physically inked together.

On our phenotype  tracker pombase/curation#890 figure 1 in PMID: 17881496
One pombe paper refers to the process when the chromosomes are laterally attached to the spindle as "kinetochore clustering" but here the kinetochores are not physically con-joined, they just happen to be close together (but you can easily distinguish the independent kinetochores on the spindle). I think this isn't true 'clustering'. They are just 'proximal' 

But kinetochores might be clustered in metaphase in other species, so your solution will work fine  for this.

**Comment by ukemi** [comment]
Done.
