### ISSUE TITLE
NTR: biotin transmembrane import into cell

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12398]
NTR: biotin transmembrane import into cell
The directed movement of biotin from outside of a cell into the cytoplasmic compartment. This may occur via transport across the plasma membrane or via endocytosis.

ancestors
GO:0044756 biotin import into cell
GO:0055085 transmembrane transport
(I couldn't do this via term genie because the import terms aren't transmembrane terms)

Same for  NTR: dethiobiotin transmembrane import into cell
GO:0044757
ancestor Name	dethiobiotin import into cell

(I want a single  term to capture biotin import AND transmembrane transport (is biotin really  also transported by endocytosis)

**Comment by ukemi** [comment]
Hi Val,

Not sure what you want here? If it is transmembrane it would not be via endocytosis. Endocytosis wouldn't topologically cross the membrane. 

'import across plasma membrane' is a choice in TG.

-D

**Comment by ValWood** [comment]
Ah right I'll try that. I was confused because it wasn't under transmembrane in the TG hierarchy.

**Comment by ukemi** [comment]
OK. If you succeed, go ahead and close this.

**Comment by ValWood** [comment]
ID: GO:1905135 Label: biotin import across plasma membrane
