### ISSUE TITLE
NTR: 'modulation by virus of host NIK/NF-kappaB signaling'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12394]
Dear Editors,

I wish to request a new term: 'modulation by virus of host NIK/NF-kappaB signalling' to annotate findings presented in Figure 2E in PMID:26764146, where the expression of components of this signaling pathway is modulated by the coxsackievirus B3 in mouse cardiac muscle cells.

I will look forward to hearing from you.

Thank you,
Barbara

@rachhuntley 
@RLovering

**Comment by BarbaraCzub** [comment]
Dear Editors,

Could you please add the following GOC references to this NTR?

GOC:BHF, GOC:BHF_miRNA and GOC:bc

Thank you,
Barbara

@rachhuntley 
@RLovering

**Comment by ukemi** [comment]
Hi Barbara,

Looking at this paper, I believe that this term is not appropriate. It doesn't look like any viral gene product is directly regulating the NFkB patyway. It looks like it is an indirect effect of modulating MiRNA metabolism.

-D

**Comment by rachhuntley** [comment]
Hi David, we are going to look into this a bit more and get back to you. 
However, just to clarify, the coxsackie virus has only a single polyprotein (UniProtKB:P03313) that is cleaved into 19 peptides (http://www.ncbi.nlm.nih.gov/pubmed/3037008) and this is the entity that would be annotated.

Rachael.

**Comment by BarbaraCzub** [comment]
Hi David, we have discussed this issue with other curators within our group and we have agreed that we would annotate this paper with our NTR for 'modulation by virus of host NIK/NF-kappaB signalling'. 

As Rachael has already pointed out, the coxsackie virus B3 genome encodes just one polyprotein. And, although it is true that there is no evidence that the viral protein affects NIK/NF-kappaB signalling directly, it is shown in Figure 2 E that the virus affects the levels of protein p65, which is a component of the host NIK/NF-kappaB signalling. This effect is seen irrespective of treatment with siAGO1 and siAGO3, i.e. p65 levels are up-regulated after treatment with the virus in total, nuclear and cytoplasmic lysates treated with si-controls.

I will look forward to hearing from you.

Barbara

@rachhuntley 
@RLovering

**Comment by ukemi** [comment]
[Term]
+id: GO:0061765
+name: modulation by virus of host NIK/NF-kappaB signaling
+namespace: biological_process
+def: "Any process in which a virus effect a change in the frequency, rate or extent of NIK/NF-kappaB signaling in the host." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:26764146]
+is_a: GO:0019054 ! modulation by virus of host process
+is_a: GO:1901222 ! regulation of NIK/NF-kappaB signaling
+created_by: dph
+creation_date: 2016-04-19T10:41:22

**Comment by BarbaraCzub** [comment]
Thank you,
Barbara
