### ISSUE TITLE
MP and missing term under meiotic chromosome segregation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12397]
GO:1902102 regulation of metaphase/anaphase transition of meiotic cell cycle

has ancestor to
GO:0033045 regulation of sister chromatid segregation

but it should be "regulation of"
GO:0045144 meiotic sister chromatid segregation

Actually, more accurately is should be
ntr: regulation of  meiotic sister chromatid separation
because the  metaphase anaphase transition regulates separation, not the broader process of segregation.

so it would look like the mitotic branch where the parent is correctly,
 GO:0010965 regulation of mitotic sister chromatid separation

**Comment by ValWood** [comment]
I think we'll need this for the consistency exercise paper. Looking at some meiotic APC stuff.

**Comment by ukemi** [comment]
Hi Val,

If you can provide a literature citation I can add the new term via termgenie. Then I will check the logical definitions and move GO:1902102 to be a child of the new term.

-D

**Comment by ValWood** [comment]
I got this a bit wrong
GO:1902102 regulation of metaphase/anaphase transition of meiotic cell cycle
does not specify meiosis I or meiosis II
so its parent would need to be
GO:xxxxxxxx regulation of meiotic chromosome separation
descendant of 
GO:0051307 meiotic chromosome separation


The best ref I could find is
http://www.ncbi.nlm.nih.gov/pubmed/15620645

**Comment by ukemi** [comment]
Added regulation of meiotic chromosome separation and subtypes with TermGenie. Moved 'regulation of metaphase/anaphase transition of meiotic cell cycle' and subtypes to be a children. This is now consistent with the mitotic structure.
