### ISSUE TITLE
spindle midzone assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12395]
Is this update correct. Doesn't the spindle have a midzone in metaphase? (it must?)

2014-10-25
Deleted
DEFINITION
The formation of the spindle midzone, the area in the center of the spindle where the spindle microtubules from opposite poles overlap, as a part of the process of mitosis.
2014-10-25
Added
DEFINITION
The cell cycle process, occurring during anaphase, in which the aggregation, arrangement and bonding together of a set of components forms the spindle midzone.

**Comment by ukemi** [comment]
Hi Val,

I found a paper, PMID:24239120, that talks about the metaphase midzone. I have modified the definition and added this as a definition xref.

-D
