### ISSUE TITLE
NTR: desired GO term terminase regulator activity

### ISSUE THREAD

**Issue by jefferypowell** [geneontology/go-ontology#12392]
terminase regulator activity
•Definition- Regulates (stimulates or hinders) the rate of terminase activity.
•Aspect- Molecular Function
•Relationships- parent term: regulation of catalytic activity (GO:0050790)
•References- PMID: 24711378 (Figure 2).  Terminase activity stimulated by presence of regulatory enzyme in vitro.  
•Synonyms- terminase stimulatory activator

**Comment by paolaroncaglia** [comment]
Hi @rebeccafoulger ,

May I please ask for your feedback on a viral term.
This ticket contains a request for ‘terminase regulator activity’. There is no ‘terminase activity’ in GO. Looking at the suggested reference (PMID:24711378) and at the existing term ‘viral terminase complex’, *if* I were to create the enzyme term, I’d add it as follows:

GO:NEW terminase activity
is_a double-stranded DNA endodeoxyribonuclease activity
def: Catalysis of the cleavage of double-stranded DNA replicated concatemeric viral genomes into single genome units. Terminase enzymes mediate the packaging of these genomes into the viral prohead.
GOC:pr, PMID: 24711378

Strictly speaking, an enzymatic activity defines as above is not different from its parent. The differentia lies in the context - the target being cleaved - but this wouldn’t be a valid reason to create a new enzyme term in GO. I’m wondering if, during the viral work, you already encountered this issue and came to the same conclusion. 
(BTW, there are no ’terminase’ entries in EC or Rhea.)

If ‘terminase activity’ is out of scope for GO, I’d recommend our user to annotate instead to GO:NEW ’positive regulation of double-stranded DNA endodeoxyribonuclease activity’ (legend of fig. 2 of PMID:24711378 says “Gp74 stimulates terminase activity in vitro via an interaction with the TerL subunit”).

If ‘terminase activity’ is instead within scope for GO, I’s add it as above, and add the links
- viral terminase complex capable_of terminase activity
- viral DNA cleavage involved in viral genome maturation has_part GO:NEW terminase activity
I could then create ‘terminase regulator activity’. Though I’d first suggest to create ‘regulation of terminase activity’ and its positive child and suggest to annotate to the latter.

But I’m leaning towards not creating terminase terms.

Thanks,

Paola

**Comment by rebeccafoulger** [comment]
Hi @paolaroncaglia,

I'd be against creating the terminase term for the same reason you describe (the activity itself isn't different to the parent). Plus, I think the terminase does more than just cleave. And in some viruses the terminase is encoded by one gene product, and in other viruses it's a complex with multiple subunits- I can check with Brenley on the biology if you like as most of these terms came from her T4 phage work.

I think we created GO:0098035 (viral DNA genome packaging via site-specific sequence recognition) as a relevant process instead- it might be more accurate to create a 'regulates' term for this. 

I think perhaps GO:0098035 needs an endodeoxyribonuclease HAS_PART... I'll look into that. We could also add a related/narrow synonym 'terminase activity' to GO:0098035 to help in future searching.

Hope that helps!

**Comment by paolaroncaglia** [comment]
Thanks @rebeccafoulger ,
Glad to hear confirmation of my suspicion. Yes, if you could please look into adding a has_part between GO:0098035 and the endodeoxyribonuclease term above, and adding a related synonym for ‘terminase activity’, that’d be great. If you’d like to ask Brenley to take a look at this request, and see if anything else needs to be added to this branch, that would also be nice, but probably not strictly necessary at the moment, so your call.

@jefferypowell :
Would you like me to create 
GO:NEW regulation of viral DNA genome packaging via site-specific sequence recognition
and
GO:NEW positive regulation of viral DNA genome packaging via site-specific sequence recognition
and you could annotate to the latter?

Thanks!

**Comment by jefferypowell** [comment]
Thanks @paolaroncaglia and @rebeccafoulger,

The newly suggested terms would do very well.  I didn't know GO terms could be so specific, hence I suggested creating the general term.  It definitely makes sense why that term shouldn't be created and instead linking GO:0098035 to a (+) regulatory term.

**Comment by paolaroncaglia** [comment]
Hi @jefferypowell
I created the terms below, they’re ready to use:

ID: GO:1905137 Label: regulation of viral DNA genome packaging via site-specific sequence recognition
ID: GO:1905138 Label: positive regulation of viral DNA genome packaging via site-specific sequence recognition

@rebeccafoulger
Assigning this ticket to you now for the related edits to viral terms.
Many thanks!

**Comment by jimhu-tamu** [comment]
Hi all,

Jeffrey is a student in a phage-based CACAO we are doing this semester with Ry Young and Jason Gill. Ry was Brenley's PhD advisor. 

I agree that from a GO perspective terminase is a multifunctional protein complex. One of those activities is a DNA endonuclease, which can be site-specific for some viruses, or not site-specific for those that package by headful mechanisms. 

However, there is some precedent. It also has a GO:0015616 DNA translocase activity, and there is a term: GO:0039631 DNA translocase activity involved in viral DNA genome packaging. Personally, I hate "involved_in" terms, so it seems to me that we should either obsolete GO:0039631 or create DNA endonuclease activity involved in viral DNA genome packaging with terminase activity as a synonym

**Comment by paolaroncaglia** [comment]
Hi @jimhu-tamu ,

Thanks for your input, that's very helpful. I'd leave it to @rebeccafoulger to please look into the necessary edits, as she used to work with Brenley on the virus project. As a quick fix, a term for 'DNA endonuclease activity involved in viral DNA genome packaging' (with terminase activity as a synonym) may be easily created via the TermGenie 'involved_in' template (using GO:0004520 'endodeoxyribonuclease activity' as the is_a genus). @rebeccafoulger , let me know if you'd like me to do that to start with. (BTW, GO:0039631 'DNA translocase activity involved in viral DNA genome packaging' has no annotations.)

Thanks!

**Comment by paolaroncaglia** [comment]
Hi @jimhu-tamu ,

I just noticed this ticket - it’s still assigned to @rebeccafoulger , but she’s left the GOC now. Anyway, the terms that your CACAO student @jefferypowell needed were indeed created at the time; and if you or any of your collaborators still need a term for 'DNA endonuclease activity involved in viral DNA genome packaging' (with ‘terminase activity as a synonym’), you may easily request it via the TermGenie template called 'involved_in' (using GO:0004520 'endodeoxyribonuclease activity' as the is_a genus). 
Therefore, I’m closing this ticket. Thanks.
