### ISSUE TITLE
Question re: GO:1900229 ! negative regulation of single-species biofilm formation in or on host organism

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12399]
Does this apply to adhesion to tissue culture cells?

**Comment by dosumis** [comment]
I'd say no, as this is non-physiological. However, it may apply if this is a unicellular organism forming a bio-film on tissue culture cell and you can make a strong argument that this is a good model of a normal process in which this organism forms biofilms on host cells of ~ the same type.

**Comment by ukemi** [comment]
I agree with David.

**Comment by jimhu-tamu** [comment]
Anything done in tissue culture is non-physiological in a strict sense, right? It's a model for something in vivo (in the strict sense that I usually don't use). 

In looking at the example that caused me to create the issue, I think we are OK in terms of it being a model for something physiological.

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3410868/

A CACAO student wants to annotate from Figure 7C. The text describing the result is:

> Adhesion to host-cells is a crucial step in the infection process and for host-colonization. Upregulation of the acm and ecbA genes, encoding major MSCRAMM adhesins, in the absence of AsrR prompted us to evaluate the contribution of AsrR to E. faecium adherence to HT-29 intestinal epithelial cells (Figure 7C). A high percentage of ΔasrR bacteria attached to the HT-29 cells (median value 44%), while the parental and complemented strains showed significantly lower levels of attachment (median values 18 and 25%, respectively) (P<0.01) (Figure 7C).

However, in our discussion, we decided that this term can't be used here because even though they are looking at biofilm formation in 7A and B, they aren't actually looking at biofilms in 7C, just adhesion.  Which means I think we will need to do an NTR for regulation of GO:0044651 adhesion of symbiont to host epithelial cell.

**Comment by ukemi** [comment]
Hi Jim,

Based on the text above, I think you want the new term since they are looking at adhesion. If you don't have a TermGenie account, I will make it for you. Please let me know.
-D

**Comment by ukemi** [comment]
If needed, the new term will be requested through TermGenie.
