### ISSUE TITLE
Synonyms for GO:0030337 ! DNA polymerase processivity factor activity

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12390]
Change sliding clamp from EXACT to NARROW. There are processivity factors that are not sliding clamps. Classical example is E. coli Thioredoxin working as a processivity factor for T7 DNA polymerase. 

http://www.jbc.org/content/287/47/39732.full and references therein.

**Comment by paolaroncaglia** [comment]
Done, thanks.
