### ISSUE TITLE
MP mitotic spindle elongation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12396]
Does not have a relationship to chromosome segregation. 
I think it should
(mitotic/meiotic)

**Comment by ukemi** [comment]
Hi Val,

Doesn't the spindle begin to elongate way before chromosome segregation happens?

-D

**Comment by ValWood** [comment]
The spindle elongates way before separation, but segregation is the broader process and begins much earlier:
Segregation is defined:
......In eukaryotes, chromosome segregation begins with the condensation of chromosomes, includes chromosome separation, and ends when chromosomes have completed movement to the spindle poles....

I can't not think of elongation as part of the 'chromosome segregation process'.
The spindle pole bodies have other roles (in signalling for cytokinesis, asymmetry etc)., but as far as I'm aware the sole purpose of the spindle and its elongation is to segregate chromosomes.
However,  if we aren't sure we could split into 'metaphase elongation' where the short spindle forms and 'anaphase elongation' wether the spindle rapidly elongates after  separation of the chromsomes chromosomes (the spindle is prevented from elongating more than a certain length in metaphase because of sister chromatid cohesion).

The other grey  area  is assembly of the inner kinetochore. However this happens very early (G1 or S) so I'm inclined to think this should be excluded from the broader chromosome segregation process. It seems sensible to restrict to events occurring in M-phase...

**Comment by ukemi** [comment]
OK. You have convinced me. I have made the elongation terms part_of nuclear chromosome segregation, mitotic and meiotic....

-D

**Comment by ValWood** [comment]
Does that seem right? I've been thinking about it for ages, and in my consistency checks it seems odd not to have the genes involved spindle elongation annotated to chromosome segregation.

I think they are hard to separate:
PMID: 21936780
Mitotic motors and chromosome segregation: the mechanism of anaphase B.
"Anaphase B spindle elongation plays an important role in chromosome segregation."

PMID: 20410686 
Cell cycle control of spindle elongation.
![elong_sep](https://cloud.githubusercontent.com/assets/7359272/14469122/0af3104c-00db-11e6-9f76-d13e32c8bc15.jpg)

**Comment by ukemi** [comment]
I was originally thinking of the elongation before anaphase. But your argument above convinced me that the objective of that was to segregate chromosomes. Sometimes the spindle elongates asymmetrically in order to create two different sized cells in an embryo. Would that make this part of invalid? Let me know and I will remove the relationship.

**Comment by ValWood** [comment]
Hmm, I guess not if it is *simultaneously* segregating chromosomes?

**Comment by ukemi** [comment]
OK. To be safe I will take those relations back out. Are you ok with that?

**Comment by ValWood** [comment]
here, I mean't that the fact that it was affecting symmetry was probably OK, if it was also always segregating chromosomes (and it must be?).
I'm trying to think of an analogy...somethings are simultaneously involved in 2 processes aren't they?

**Comment by ukemi** [comment]
Actually thinking about this more, I think we should just leave them as is. The objective is to segregate the chromosomes. So this one is done.
