### ISSUE TITLE
NTR: Positive Regulation of Photosynthesis

### ISSUE THREAD

**Issue by Mmohieddin** [geneontology/go-ontology#12408]
Positive Regulation of Photosynthesis
Definition: Any process that positively modulates the frequency, rate or extent of photosynthesis.
Aspect: Biological process 
Relationship: child term of GO:0010109
Reference: PMID:7592491

**Comment by tberardini** [comment]
Added via TermGenie:

id: GO:1905157
name: positive regulation of photosynthesis
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of photosynthesis." [GO_REF:0000058, GOC:TermGenie, PMID:7592491]
synonym: "activation of photosynthesis" NARROW [GOC:TermGenie]
synonym: "up regulation of photosynthesis" EXACT [GOC:TermGenie]
synonym: "up-regulation of photosynthesis" EXACT [GOC:TermGenie]
synonym: "upregulation of photosynthesis" EXACT [GOC:TermGenie]
is_a: GO:0010109 {is_inferred="true"} ! regulation of photosynthesis
is_a: GO:0031325 {is_inferred="true"} ! positive regulation of cellular metabolic process
intersection_of: GO:0065007 ! biological regulation
intersection_of: positively_regulates GO:0015979 ! photosynthesis
relationship: positively_regulates GO:0015979 {is_inferred="true"} ! photosynthesis
