### ISSUE TITLE
MP: GO:1990505 mitotic DNA replication maintenance of fidelity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12406]
Please add parent
 GO:1902969 mitotic DNA replication

**Comment by tberardini** [comment]
Part of parent, correct?  What about 'mitotic DNA replication preinitiation complex assembly', should that also be part of 'mitotic DNA replication'?

See current structure:
<img width="517" alt="screen shot 2016-04-19 at 4 41 35 pm" src="https://cloud.githubusercontent.com/assets/4998871/14659088/a9c2536e-064d-11e6-9e8a-e2910e57d897.png">

**Comment by ValWood** [comment]
yep!

**Comment by tberardini** [comment]
Done.
