### ISSUE TITLE
GO:0052331 hemolysis in other organism involved in symbiotic interaction synonyms

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#12400]
"GO:0044179 hemolysis in other organism" has the child term 
"GO:0052331 hemolysis in other organism involved in symbiotic interaction". http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0052331 has an 'exact' synonym of "haemolysis in other organism", this should probably be appended with 'during symbiotic interaction' to avoid confusion.

Thanks
Suzi

**Comment by ukemi** [comment]
Done. Thanks for spotting this.

-D
