### ISSUE TITLE
NTR: eukaryotic translation initiation factor 2 complex assembly

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#12401]
Hi,

I would like to request the following term:

Term: eukaryotic translation initiation factor 2 complex assembly

Definition: The aggregation, arrangement and bonding together of a set of components to form the eukaryotic translation initiation factor 2 complex. 

Synonyms: eIF2 assembly, eIF-2 assembly 

Instance of GO:0043623 cellular protein complex assembly

Definition reference:  PMID: 23775072

Perzlmaier AF, et al. (2013) Translation Initiation Requires Cell Division Cycle 123 (Cdc123) to Facilitate Biogenesis of the Eukaryotic Initiation Factor 2 (eIF2). J Biol Chem 288(30):21537-46

Cheers,
Rob

**Comment by ukemi** [comment]
Created via termgenie:

[Term]
id: GO:1905143
name: eukaryotic translation initiation factor 2 complex assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of a set of components to form an eukaryotic translation initiation factor 2 complex." [GO_REF:0000079, GOC:TermGenie, PMID:23775072]
synonym: "eIF-2 assembly" EXACT [GOC:TermGenie]
synonym: "eIF-2 formation" EXACT [GOC:TermGenie]
synonym: "eIF2 assembly" EXACT [GOC:TermGenie]
synonym: "eIF2 formation" EXACT [GOC:TermGenie]
synonym: "eukaryotic translation initiation factor 2 complex formation" EXACT [GOC:TermGenie]
is_a: GO:0006461 {is_inferred="true"} ! protein complex assembly
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: results_in_assembly_of GO:0005850 ! eukaryotic translation initiation factor 2 complex
relationship: results_in_assembly_of GO:0005850 {is_inferred="true"} ! eukaryotic translation initiation factor 2 complex
created_by: dph
creation_date: 2016-04-14T00:25:51Z
