### ISSUE TITLE
parentage query: iron-sulfur cluster assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12404]
This term has parentage to
 GO:0008152 metabolic process
and
GO:0009987 cellular process

I'm not sure that metabolic process  is correct?
Is it is the parentage should be "cellular metabolic process"

**Comment by ValWood** [comment]
@AntoniaLock

**Comment by Antonialock** [comment]
Val do you mean metabolism as opposed to just 'chaperoning' toxic substances? 
hmm...
fig3 http://www.sciencedirect.com/science/article/pii/S0300908414000133
Mammalian Fe–S cluster biogenesis. 
"NFS1, the cysteine desulfurase subtracts sulfur from l-cysteine for nascent Fe–S cluster assembly."
that comes into the def of "transform chemical substances" in metbaolism?

**Comment by ValWood** [comment]
OK in that case, this process does appear to be a 'metabolic process'. yes?

**Comment by Antonialock** [comment]
I think so? 
GO:0051188 cofactor biosynthetic process ?

**Comment by ValWood** [comment]
Is it a cofactor ? Maybe it is?

**Comment by Antonialock** [comment]
https://en.wikipedia.org/wiki/Cofactor_%28biochemistry%29
"Cofactors can be divided into two broad groups: organic cofactors, such as flavin or heme, and inorganic cofactors, such as the metal ions Mg2+, Cu+, Mn2+, or iron-sulfur clusters."

**Comment by tberardini** [comment]
What's the action item?

**Comment by ValWood** [comment]
missing parent "cellular metabolic process"

**Comment by Antonialock** [comment]
missing parent GO:0051188 cofactor biosynthetic process ?

**Comment by ValWood** [comment]
yes, sorry!

**Comment by tberardini** [comment]
Added parentage to GO:0051188 cofactor biosynthetic process.  By inheritance, the term in question becomes a child of 'cellular metabolic process.'

**Comment by Antonialock** [comment]
why was 
is a GO:0051188 (cofactor biosynthetic process) 
deleted? 
for GO:0016226


2019-02-28 | Deleted | RELATION | is a GO:0051186 (cofactor metabolic process)
2018-02-16 | Deleted | RELATION | is a GO:0051188 (cofactor biosynthetic process)
2018-02-16 | Added | RELATION | is a GO:0051186 (cofactor metabolic process)

**Comment by pgaudet** [comment]
I don't know ! I could't find any tickets that correspond to this. Maybe this happened when @ukemi changed the logical definitions for the metabolic processes with the 'has primary input' relation? 

Anyway I have added it back. 

Thanks, Pascale

**Comment by Antonialock** [comment]
Thanks!
