### ISSUE TITLE
NTR: Negative Regulation of Photosynthesis

### ISSUE THREAD

**Issue by Mmohieddin** [geneontology/go-ontology#12409]
Negative Regulation of Photosynthesis
Definition: Any process that negatively modulates the frequency, rate or extent of photosynthesis.
Aspect: Biological process 
Relationship: child term of GO:0010109
Reference: PMID:7592491

**Comment by tberardini** [comment]
Added via TermGenie:

id: GO:1905156
name: negative regulation of photosynthesis
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of photosynthesis." [GO_REF:0000058, GOC:TermGenie, PMID:7592491]
synonym: "down regulation of photosynthesis" EXACT [GOC:TermGenie]
synonym: "down-regulation of photosynthesis" EXACT [GOC:TermGenie]
synonym: "downregulation of photosynthesis" EXACT [GOC:TermGenie]
synonym: "inhibition of photosynthesis" NARROW [GOC:TermGenie]
is_a: GO:0010109 {is_inferred="true"} ! regulation of photosynthesis
is_a: GO:0031324 {is_inferred="true"} ! negative regulation of cellular metabolic process
intersection_of: GO:0065007 ! biological regulation
intersection_of: negatively_regulates GO:0015979 ! photosynthesis
relationship: negatively_regulates GO:0015979 {is_inferred="true"} ! photosynthesis
