### ISSUE TITLE
NTR: FMN domain binding

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12407]
We have GO:0019904 protein domain specific binding, with a long list of children per domain specificity, https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0019904#term=children, and GO:0010181 FMN binding.

Would it make sense to create a term FMN domain binding which would be a child of both?

I am looking at this paper, http://www.sciencedirect.com/science/article/pii/S0003986105000597, which states "Taken together, the results of the pull-down assay presented in Fig. 5 suggest that SQD1 forms a complex with FdGOGAT in vitro and specifically binds to the FMN-binding and central domains of FdGOGAT."

assigning to @ukemi as our expert biochemist - I'm happy to do the edits just want to check they make sense.

**Comment by mah11** [comment]
GO:0010181 refers to interacting with flavin mononucleotide itself, not to a protein or any portion thereof, and the ancestry implies that it at least includes (and may be restricted to) interaction with free FMN.

Furthermore, while in this specific paper they show that SQD1 interacts with the FMN-binding domain of FdGOGAT, the experiments do not address whether SQD1 makes any contact with FMN or only with the protein part of the FdGOGAT domain.

So it probably does make sense to create a term for "FMN-binding domain binding", that term should not be a child of GO:0010181.

**Comment by mcourtot** [comment]
Thanks for the feedback Midori. The current definition of GO:0010181 reads 'Interacting selectively and non-covalently with FMN, flavin mononucleotide, the coenzyme or the prosthetic group of various flavoprotein oxidoreductase enzymes.' which I read as possibly interacting with prosthetic group of enzymes, which could I think be considered portion of proteins? Here is the chart with those 3 terms. 

![screen shot 2016-04-19 at 14 53 43](https://cloud.githubusercontent.com/assets/2214135/14641546/b982ac9a-063e-11e6-8d96-683806d5122f.png)

I'm happy with your proposed solution, creating the "FMN-binding domain binding" as a subclass of GO:0019904 protein domain specific binding. Do you think it would make sense to update the definition of GO:0010181 FMN binding to be a bit clearer?

**Comment by ukemi** [comment]
Hi Melanie. 
You should also probably add InterPro:IPR007329 as a definition dbxref. I don't think that binding a prosthetic group would include the protein. If you can think of a way to clarify that, it would be good.
-D

**Comment by mah11** [comment]
I think the "the coenzyme or the prosthetic group of various flavoprotein oxidoreductase enzymes" text is a gloss to explain what FMN is and does, not an assertion that the binding represented by GO:0010181 necessarily takes place only when FMN is associated with a protein that uses it as a cofactor. Note that there's no connection between "cofactor binding" (or "coenzyme binding") and the "protein binding" branch.

**Comment by mah11** [comment]
(and David's comment appeared when I was almost done typing mine)

**Comment by mcourtot** [comment]
Fantastic, thanks both for the explanation. 
+1 on adding InterPro xref
I'm still unclear on the FMN binding sorry... In the cart above, you can see it is_a coenzyme binding. Should it also be is_a prosthetic group binding? 
What do you think of updating the definition to read "'Interacting selectively and non-covalently with flavin mono nucleotide. Flavin mono nucleotide (FMN) is the coenzyme or the prosthetic group of various flavoprotein oxidoreductase enzymes.'"?

**Comment by ukemi** [comment]
I'm not sure it is always a prosthetic group. Do you know Midori?

**Comment by mah11** [comment]
Sorry, no ... not really an expert on any of this cofactor/coenzyme/prosthetic group stuff.

**Comment by mcourtot** [comment]
:( I'm lost too. Based on the definition, and given that there is already a link to coenzyme, why not add the is_a prosthetic group binding? (They both end up being types of cofactor binding). Or should the link to coenzyme binding be removed?

**Comment by mah11** [comment]
The easy part is to say it depends on whether FMN is always a coenzyme, always a prosthetic group, or always both. If it's always both, then yes, it would make sense to have the FMN binding term be both is_a coenzyme binding and is_a prosthetic group binding.

The problem is that neither David nor I know whether FMN is always a prosthetic group (and in my case, I'm taking the existing ontology's word for it that FMN is always a coenzyme; I don't have that knowledge independently). I therefore don't know which parent(s) FMN binding should actually have.

**Comment by mcourtot** [comment]
I think it's an either or. The definition itself says 'or', and the wikipedia page at https://en.wikipedia.org/wiki/Flavin_mononucleotide says" [...]  functions as prosthetic group of various oxidoreductases including NADH dehydrogenase as well as cofactor in biological blue-light photo receptors. "
I don't think it is always a coenzyme or a prosthetic group, I guess when used as food additive for example it is neither?

I'm also not sure why it is inferred as anion binding... I'll tag it as 'to look into' and will in the meantime create the other term. Thanks again for the feedback and discussion.

**Comment by ukemi** [comment]
PMID:21635694
Maybe just make it cofactor binding?

**Comment by ukemi** [comment]
Making it a cofactor is also consistent with its role in ChEBI. Maybe the anion parent is an ETINE.

**Comment by mcourtot** [comment]
+1 cofactor. I didn't see the anion binding in the ETINE file. I'll make the changes we discussed and will keep a look on it. If it doesn't self-heal I'll dig further.

**Comment by ukemi** [comment]
if you remove the anion parent and run the reasoner, you can see if it comes back.

**Comment by mcourtot** [comment]
It doesn't come back with the reasoner, by I don't know if it reflects an issue with the inference pipeline or else, as I couldn't find it in the ETINES.

Did the other changes we discussed. Looking at the thread, my 'quick fix' once again became a more involved discussion :) Thanks both for helping me work through it.

**Comment by mcourtot** [comment]
@ukemi : checking the interPro page at InterPro:IPR007329, should I ask them to remove the mapping to GO:0010181 FMN binding? We discussed above that this term was only applicable for free FMN.

**Comment by ukemi** [comment]
That domain does bind FMN, doesn't it?

**Comment by mcourtot** [comment]
it does, but Midori suggested above that 
>GO:0010181 refers to interacting with flavin mononucleotide itself, not to a protein or any portion thereof, and the ancestry implies that it at least includes (and may be restricted to) interaction with free FMN.
and therefore FMN-binding domain should not be is_a FMN binding

**Comment by ukemi** [comment]
I think she was refering to your new term not being a child of GO:0010181 because it describes binding to the binding domain, not binding the FMN itself.

**Comment by mah11** [comment]
Yes, David's got it right. It's "FMN-binding domain _binding_" that shouldn't be is_a "FMN binding".

**Comment by mcourtot** [comment]
you're entirely right. I got binding-ed out ;)
