### ISSUE TITLE
NTR: clathrin pit assembly (and other related clathrin coating edits)

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12403]
I'm annotating PMID:26589353, where Syt11 inhibits clathrin-mediated endocytosis by limiting membrane invagination and pit formation (Fig 8). 

I'd like to add a couple of new terms, and I think some revisions are needed to existing terms:
1.  I don’t think ‘clathrin coat assembly (GO:0048268)’ should be under ‘vesicle coating (GO:0006901). In the CC section, we have ‘clathrin coat of coated pit ; GO:0030132’ and ‘clathrin vesicle coat’. Since both pits and vesicles can be coated with clathrin, the vesicle parent is too specific. GO:0048268.
2. Based on its existing definition, rename ‘coated pit ; GO:0005905’ to ‘clathrin-coated pit’.
   broad synonym: coated pit
3. Create new term in TG:
   clathrin-coated pit assembly ; GO:NEW
   exact synonym: coated pit assembly
   exact synonym: coated pit formation
   HAS_PART: membrane invagination ; GO:0010324
   HAS_PART: clathrin coat assembly ; GO:0048268
4. Add relationship:
   clathrin-mediated endocytosis ; GO:0072583
   —[part_of]clathrin-coated pit assembly ; GO:NEW
5. Create regulation terms in TG for the annotation of Synaptotagmin-11, which limits the pit-formation step in clathrin-mediated endocytosis.

Any comments from anyone who knows more about this area than me? ... e.g. what other types of coated pits there are....

Thanks!

**Comment by tberardini** [comment]
@rebeccafoulger , can you make these edits or do you need me to do them for you?  I don't know more about coated pits than what's in this issue but am in charge of GH this week.  Thanks.

**Comment by rebeccafoulger** [comment]
I can do the edits @tberardini: was just hoping someone might weigh-in on clathrin coats first!

**Comment by tberardini** [comment]
From a brief survey, it looks like there aren't any other kinds of coated pits but that the history of the term was first 'bristle coated pits', then they figured out that the bristles were made of clathrin. 

http://cshperspectives.cshlp.org/content/6/5/a016725.long

**Comment by rebeccafoulger** [comment]
Thanks Tanya. Getting back to this, I've started my edits:
1. Removed ‘clathrin coat assembly (GO:0048268)’ from under ‘vesicle coating (GO:0006901)’
2. Based on its existing definition, renamed ‘coated pit ; GO:0005905’ to ‘clathrin-coated pit’.

Will create the TG term when my clathrin coat assembly name change filters through.

**Comment by rebeccafoulger** [comment]
Next step, a new term in TermGenie: GO:1905224 Label: clathrin-coated pit assembly

**Comment by ValWood** [comment]
I wonder if there should be just one term
clathrin mediated endocytosis clathrin coat assemby
instead of 
clathrin coat assembly, 
and 
clathrin coated pit assembly.
Isn't the pit just the early  membrane invagination  stage of 
clathrin mediated endocytosis clathrin coat assembly?
They don't seem to be 2 separate processes?

See
https://github.com/geneontology/go-ontology/issues/12509
and the figures in this recent review
http://www.ncbi.nlm.nih.gov/pubmed/24322426

Also "clathrin coat assembly" will occurs as part of clathrin-mediated  transport  between other compartments. Here you are referring to endocytosis

I don't think you can do:
clathrin-mediated endocytosis ; GO:0072583
—[part_of]clathrin-coated pit assembly ; GO:NEW
without specifying that it is the endocytic one (AP2 adaptor complex containing)

https://en.wikipedia.org/wiki/Clathrin_adaptor_proteins
There are different AP complexes in mammals. AP1 is responsible for the transport of lysosomal hydrolases between the TGN and endosomes.[4] AP2 adaptor complex associates with the plasma membrane and is responsible for endocytosis.[5] AP3 is responsible for protein trafficking to lysosomes and other related organelles.[6] AP4 is less well characterised.

This agrees with the reviews and the intro in  the paper I am curating now PMID:26749213.

The membrane invagination part is performed by BAR domain proteins 
https://github.com/geneontology/go-ontology/issues/12387
This process occurs in many contexts (different BAR domains proteins)
and this could be the step which is regulated here.....

I put some recommendations
https://github.com/geneontology/go-ontology/issues/12509
 before I saw this ticket.

**Comment by rebeccafoulger** [comment]
Clathrin coats don't just form on the pits though Val. In the CC node, we have terms for:
clathrin coat of coated pit ; GO:0030132
clathrin vesicle coat ; GO:0030125

Hence why I was planning to add in a HAS_PART relationship.

**Comment by ValWood** [comment]
Yeah sorry I didn't explain.
The pit becomes the vesicle though? So isn't there only one process "clathrin coat assembly"
(it starts on the pit, but  eventually becomes the coat?). Or do clathrin coats form on some pits which never become vesicles?

It sin't really clear to me what clathrin coated pit assembly involves...It sounds like the membrane invagination stage  of vesicle formation (maybe?).

**Comment by ValWood** [comment]
I have been approving a few of our community papers related to membrane trafficking/transport processes. There are quite a few terms where I'm confused based on what these recent  papers say (and I haven't opened all of the tickets yet...)

Maybe I could tag all of these  "vesicle transport" and we  could have a look with @dosumis 
when you are in the GO office (maybe with Ruth by Skype as your projects seem to use these terms frequently).

**Comment by mah11** [comment]
>> Clathrin coats don't just form on the pits though
> 
> The pit becomes the vesicle though? So isn't there only one process "clathrin coat assembly" ...

Clathrin also coats buds that form (and give rise to vesicles) on the trans-Golgi network membrane. The TGN vesicle buds aren't called coated pits. (Brief summary [here] (http://walz.med.harvard.edu/Research/Vesicular_Coat_Proteins/).)

**Comment by ValWood** [comment]
Is the term clathrin-coated pit assembly for the membrane curvature step, or the coat assembly step? The process of coat assembly is the same process on the pit and the vesicle (it doesn't appear to be 2 different processes). Does that make sense? 

![clathrin](https://cloud.githubusercontent.com/assets/7359272/16914146/ba9091fc-4ce7-11e6-9441-ada811ea1e00.jpg)

**Comment by ValWood** [comment]
This is nice, molecular mechanism:

![molecular_mechanisms](https://cloud.githubusercontent.com/assets/7359272/16914245/80491d42-4ce8-11e6-895a-0d5547dbd7c8.jpg)

**Comment by ValWood** [comment]
> Clathrin also coats buds that form on the trans-Golgi network membrane. The TGN vesicle buds do give rise to vesicles but aren't called coated pits. (Brief summary here.)

Yeah this is for clathrin-mediated endocytosis. This coat  uses AP1 complex. The Golgi ones use different AP complexes. So all terms will need to specify 'endocytosis'.


Becky I see what you are doing now. 
I would have said the steps for endocytosis are:
membrane invagination, nucleation
cargo loading,
coat assembly (the coat begins to form on the pit, but continues...where does the pit end and the vesicle begin?...It might be easier not to mention the pit here, or to say it begins as a pit and ends as a vesicle!)

This is also a great example for how annotations are propagated over has_part
What would you annotate to 
clathrin-coated pit assembly?
Which terms would you use for a proteins which was involved in the membrane curvature step of endocytosis ....I know everyone is going to say "this would work better in LEGO" but I'm also interested if this was modelled in LEGO what would be exported for display on the gene pages.

I'll flag this as an example, because we can't use LEGO until we are satisfied that we get comprehensive annotations out for the gene pages

**Comment by rebeccafoulger** [comment]
I was planning that 'clathrin-coated pit assembly' included both the membrane invagination and the clathrin-coat assembly steps. I considered having 'clathrin-coated pit assembly' is_a: 'membrane invagination'. But the fact that we have the term 'clathrin coat of coated pit ; GO:0030132' suggests that the pit includes the clathrin coat. And therefore I thought assembly of the coat is a step in pit formation/assembly.

**Comment by dosumis** [comment]
Just bumped into the same issue myself.  Parking OE screenshot here for now

![image](https://cloud.githubusercontent.com/assets/112839/17151344/3314dc3a-536b-11e6-9de3-871b1876824b.png)

.... relationship to endocytosis = ...

**Comment by dosumis** [comment]
### Plan of action:

Strategy: split clathrin-mediated endocytosis into parts based on this figure 
FIGURE 2 | The clathrin-coated vesicle cycle.
Molecular mechanism and physiological functions of clathrin-mediated endocytosis
Harvey T. McMahon & Emmanuel Boucrot [PMID:21779028](http://www.ncbi.nlm.nih.gov/pubmed/21779028)

![molecular_mechanisms](https://cloud.githubusercontent.com/assets/7359272/16914245/80491d42-4ce8-11e6-895a-0d5547dbd7c8.jpg)

Start and end and major steps should be enumerated in the definition.

 - [ ] nucleation
 - [ ] cargo selection 
 - [ ] coat assembly
   * SubClassOf clathrin coat assembly
   Question: should this be under vesicle coating - even though it happens prior vesicle formation.  OTOH, it seems reasonable to put it under vesicle coating given that the ultimate output (after scission) is coated vesicle.
 - [ ] scission
 - [ ] uncoating

**Comment by rebeccafoulger** [comment]
Added outstanding relationships:
GO:1905224 Label: clathrin-coated pit assembly:
HAS_PART: membrane invagination ; GO:0010324
HAS_PART: clathrin coat assembly ; GO:0048268

Rest of ticket will be dealt with in David's transport edits.

**Comment by ValWood** [comment]
I still have a slight problem with  "clathrin-coated pit assembly" as I can't see how it differs from "clathrin coat assembly" at the process level (or the membrane invagination, nucleation stage). The processes seem pretty well worked out here (enough to add beginnings and ends?)

in the steps of this process, membrane invagination and cargo selection precede clathrin coat assembly?

Maybe you can explain to me, are you attending Noctua meeting?
Which genes are you annotating to "clathrin-coated pit assembly"?

**Comment by Pauldenny** [comment]
I am "lurking" here, after Rebecca @rebeccafoulger leaves UCL

**Comment by BarbaraCzub** [comment]
I've also just lurked! And it seems that ticket #12583 is also partly related to this topic, as @ValWood mentioned.

**Comment by ValWood** [comment]
Maybe we could discuss this ticket on Thursday afternoon ?

**Comment by tberardini** [comment]
@ValWood : Maybe we could discuss this ticket on Thursday afternoon ?  
Do you mean during the weekly GO ontology eds meeting?  If yes, I will put on the agenda.

**Comment by ValWood** [comment]
I meant during @rebeccafoulger Becky's leaving lunch, but yes either /or ;)

**Comment by tberardini** [comment]
Oh!  Discuss away during leaving lunch if you can stand it and please update this ticket with results.

**Comment by ValWood** [comment]
well...after lunch...

**Comment by rebeccafoulger** [comment]
Okay- will dig out my original paper that started this thread off! See you tomorrow Val.

**Comment by dosumis** [comment]
This ticket ended up as a launching point for fixing lots of related stuff.  Don't think it should be too hard to finish.  I'll refamliarise myself with it.

**Comment by Pauldenny** [comment]
Hi @dosumis - still lurking ;) -  any updates?

**Comment by ValWood** [comment]
Was this one finished?

**Comment by BarbaraCzub** [comment]
Hm... 'uncoating of endocytic vesicle' is not ticked in the 28 Jul 2016 Plan of Action by @dosumis (And it does not get displayed in QuickGO, so maybe still ongoing?)

**Comment by pgaudet** [comment]
Looks like the outstanding issue here is 'uncoating of endocytic vesicle' (the term still doesn't exist), but we have 'clathrin coat disassembly'; is the sufficient ? 

If this is not needed - can we close the ticket @ValWood @BarbaraCzub @dosumis

**Comment by BarbaraCzub** [comment]
Hi @pgaudet It's been on my to-do list to add this term, but I see your point about 'clathrin coat disassembly'. In fact 'clathrin-coated vesicle uncoating' is an exact synonym of 'clathrin coat disassembly'.
The only reason why I think it may be worth adding a new term 'uncoating of endocytic vesicle' (as a child of 'vesicle uncoating' and a parent of 'clathrin coat disassembly') is to make it possible to annotate other proteins (maybe caveolin... or others?). But the words 'caveolin/caveola' and 'coat' do not seem to occur together in scientific literature, so perhaps indeed this new term is not needed (unless there are other protein coats which should be considered?). @RLovering @paolaroncaglia do you have any suggestions regarding this?

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 

First, I modify my previous suggestion: the most appropriate term might be 'GO:0072319 vesicle uncoating'. If you find protein mediating the disassembly of endocytic vesicles I would agree creating the term, but caveolin is part of the coat, as far as I understand, so it would not be appropriate. 

Also, we don't have 'endocytic vesicle coating', so are you sure the disassembly exists ? 

I would hold off creating the term until we understand the process. 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
I'll check in Protein2GO reports whether Rebecca had any Tickets Pending that would explain why she needed this term.
Thanks, 
Barbara

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
Sorry I'm busy with other tasks and can't look into this straight away, but I made a note to keep an eye on this thread. If it's still needed, I'll address your question(s) on Wed.
Thanks,
Paola

**Comment by BarbaraCzub** [comment]
Thank you @paolaroncaglia 
I reviewed Rebecca's Tickets Pending in Protein2GO and I did not find anything relating to this issue, so I will close it now.
Thanks,
Barbara
