### ISSUE TITLE
GO term specificity proposal 4 gene product specific function terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12419]
example kinases:
GO:0033868  Goodpasture-antigen-binding protein kinase activity
GO:0004711  ribosomal protein S6 kinase activity
GO:0008384  IkappaB kinase activity
GO:0004687  myosin light chain kinase activity
GO:0004694  eukaryotic translation initiation factor 2alpha kinase activity
~GO:0004697  protein kinase C activity~

example kinase activator
GO:0016534 cyclin-dependent protein kinase 5 activator activity 

example phosphatase
GO:0050115 myosin-light-chain-phosphatase activity

I realise some groups depend on some gene product specific terms (particularly for actins and histones) where the organisms of the substrate is not completely known is another species. However, maybe we should have a "mixed organism evidence code" to reflect this.

Possibly if you really don't know which actin, (actins have many roles, some actin-like proteins are transcription factors). If you can't be sure which actin, is the annotation even so useful?

For others (like ribosomal S6 kinase) the organism paralogs are so identical, if you can use an S6 protein or antibody from another species, you can probably infer that the kinase is specific for all of your S6's is valid (otherwise your original S6 kinase annotation is unsound).

@pgaudet @thomaspd @dosumis

**Comment by jimhu-tamu** [comment]
Overall, I support this.

wrt the mixed organism evidence: IMO, while there may be cases where mixed organism is part of a multi-organism process, in other cases we should remember that we are capturing an inference about the normal function of the protein. Thus, if a publication uses chicken histones to assay a human histone acetylase, we are inferring acetylation of the human ortholog.

I recall discussing this in terms of the difference between the with/from field and the annotation extension field when looking at protein binding.

**Comment by tberardini** [comment]
From internal discussion, consolidating here:

"I'm having trouble with this one. It seems to require inference form the curator and knowledge that for example S6s are almost identical across species. As I don't think our role is to support inference form experts only, I would prefer to keep the fine-grained distinction in the ontology. But I may be misunderstanding what is being talked about." - mcourtot

**Comment by ValWood** [comment]
There are two options:

1. If some of these substrates for a general in vitro kinase assay they probably shouldn't be used to infer  physiological substrate.
OR
2. If you are convinced that ribosome S6 in your species is the physiological target of the kinase, then  the target would be any/all of the ribosomal S6's? because the antibody in question will be specific for all of them?

**Comment by ValWood** [comment]
Actually the S6 kinase one isn't a big deal to fix the annotations.
There are only  12 EXP annotations to 7 proteins . One is PomBase, I can easily fix that one.
That leaves 6 to fix. 1 MGD,  3 rat, 2 flybase.
I believe this just a historical term that was imported into GO  very early on from the EC numbers. It wouldn't be added today. Its easier for us to add extensions and then merge/obsolete the term than  to dicuss ;)

**Comment by ValWood** [comment]
We had already captured the targets for pombe in AE. We added both S6's. 
Curator noted "In vitro assay using rps602 so I am inferring rps601" (these are 99% identical and all P sites conserved so I think this is safe 237/239 AAs conserved). I think the general assumption is that  this kinase would phosphorylate all S6's. Similar to the situation with histones which are also 99-100% identical, and a couple of elongation factors. I don't think it would be safe  to do this  for anything else though.....

**Comment by ValWood** [comment]
Even easier than I thought- for human mouse rat and fly  there is only a single copy of S6  so there is only a single option for the target gene. In general, ribosomal proteins are often duplicated but the paralogs are not diverged, they are either identical or almost identical.

**Comment by tberardini** [comment]
" Its easier for us to add extensions and then merge/obsolete the term than to dicuss ;)"

What are the proposed merges?  All into 'protein kinase activity'?

**Comment by ValWood** [comment]
Yep. At least up to the non gene product specific parent. If we were to implement this one people would need time to recapture targets (so maybe it would be useful to have a list of annotations per database).

This is a good example why having the existing terms hang around isn't great:
https://github.com/geneontology/go-ontology/issues/12440#issuecomment-217206490

We are also finding that community curation users request gene product specific terms, because they already exist. It also isn't clear to general end users why some things have a  product specific term, and some don't. It doesn't help users to understand GO.

**Comment by tberardini** [comment]
Oh, so that list of terms you put is not exhaustive.  Would need a complete list,  do work in stages.

**Comment by dosumis** [comment]
Given how generally important some of these activities are in signalling and control of key cell-biological processes ( 'GO:0004697 protein kinase C activity' !), I think a wider discussion within GO is merited before obsoleting or merging - at least for some cases.

**Comment by ukemi** [comment]
Hi Tanya,
If I recall correctly, you and I were never happy with the 'gene specific' terms in the ontology. I think long ago we said we would keep these terms because they were useful for people who didn't have a way to record the detailed information in any other way? Do we want to give people a heads-up that they should make the structured annotations because these terms will be merged at a certain time? Or perhaps we could just automatically 'reannotate' the exisiting annotations by unfolding them before the merge.
-D

**Comment by RLovering** [comment]
Hi 

sorry I haven't been following this. Some of these terms may refer to protein complex functions rather than single protein functions. I would appreciate knowing that this discussion had been taken to the GOC rather than rushed through

Thanks

Ruth

**Comment by tberardini** [comment]
There will be no rushing and certainly no action will be taken without consulting on a larger scale.

**Comment by dosumis** [comment]
Need to look at the ST branch carefully before getting rid of some of these.  There are unformalised terms hanging around there that could probably only be formalised with reference to some of these gene-family specific activities. 

e.g. 

![image](https://cloud.githubusercontent.com/assets/112839/15051877/b8c559e0-12f2-11e6-90ef-06fa8fb2ec2f.png)

**Comment by ValWood** [comment]
It isn't being rushed through Ruth, its a proposal. Sorry I thought I had tagged you in this one (I know you are interested in this).

I think it would be useful to  get rid of terms which refer to specific gene products with no annotations in the first instance,  and then subsequently (in stages) any that can be captured with targets (to give people time to add the extensions, which would be quick because you should not need to go back to the papers.....).

Lots of kinases are important in signalling and don't have a specific GO term (polo/wee1/aurora/NDR kinases). If this proposal were accepted, I  would also recommend the same fate for MAPK/K/K/K kinases. That said, protein kinase C,  is probably actually OK, because it has a differentia- its DAG dependent (a good reason to keep it).

My objections are multiple, but what we do is inconsistent, which is confusing for end users, and as a grouping term the flavours  MAP kinases (for example) don't tell you  anything biologically relevant other than 'signalling' or "MAP K cascade" because they all regulate different processes.  They  therefore aren't useful for enrichment purposes. If accepted this would make the scope of GO clearer (its difficult to  explain the scope of GO to new curators and to users  that we don't have gene product specific activities, when we do).

 "protein kinase" part of  x signalling   OR part of "regulation of process x" is more relevant but this critical part sometimes gets overlooked in the annotation because of all the possible options.

This group of tickets was really just  aimed to get a discussion  of the focus of the scope  and ways in which we can improve annotation consistency without losing the critical biological information which is within the scope of GO. None of the tickets are exhaustive in the terms suggested, they are just examples. Some of these terms are really, really old, and came from the original import and we should question whether our fondness for them is sometimes due to familiarity with the  gene products rather than their valid place in GO.

**Comment by tberardini** [comment]
@ukemi said: " Or perhaps we could just automatically 'reannotate' the exisiting annotations by unfolding them before the merge."



Now that sounds like a great idea.  **If** we do decide to merge some terms, we could offer the unfolded annots back to the DBs to shorten the reannotation process.

**Comment by ValWood** [comment]
> Oh, so that list of terms you put is not exhaustive. Would need a complete list, do work in stages.

Yes. If it did not happen immediately we could flag things in some way,  or have a list on a wiki.

There could be  a procedure:

i) if no EXP annotations -> merge

ii) If EXP annotations and only one possible target per organism, or the assumption is that the molecules are identical (in the S6 case) automatically unfold (nice idea!)

ii) if targets are ambiguous we need to do something cleverer.  
If a specific gene product   has an annotation for example:
GO:0008384 myosin light chain kinase activity has_target (some myosin light chain kinase)
then the argument for keeping the GP-term for the reason that you did not know which specific  molecule was assayed in the publication ( for e.g multi species in vitro EXP)  becomes moot, because the information about the target is already present.

It could happen over a number of years....its just nicer in the long term  if there is a consistent way to do things without having to say " if it's this you do this, but if if its this you do this".

(It will also help to build LEGO models  automatically if we have the IDs of the targets in the extensions)

**Comment by ValWood** [comment]
@pgaudet  you might like to roll this one in with your gene product specific list.
val

**Comment by ValWood** [comment]
Let's close this.

Of the above they are used quite a lot, except 
GO:0033868 Goodpasture-antigen-binding protein kinase activity
which has no manual annotations. Should we just obsolete that one to prevent use?

**Comment by pgaudet** [comment]
GO:0033868 Goodpasture-antigen-binding protein kinase activity -> no EXP annotations -> will propose to obsolete - (since EC  mapping: EC:2.7.11.9 )

GO:0016534 cyclin-dependent protein kinase 5 activator activity 5 EXP 

GO:0004711 ribosomal protein S6 kinase activity 12 EXP 
GO:0008384 IkappaB kinase activity 6 EXP

**Comment by pgaudet** [comment]
@ValWood @hdrabkin 
Looks like the history of those is that we entered the ones that have EC numbers: 
https://enzyme.expasy.org/EC/2.7.11.-
however that's only 33 protein kinases. Isn't that odd? 

I can go ahead with the obsoletion of unused terms, but I would prefer a clearer way to deal with those. 

Pascale

**Comment by hdrabkin** [comment]
If we are planning to obsolete terms that are "unused" in general, then this strategy impacts various projects.
Example see projects to add 'missing' EC to GO #13432
Metacyc /plant enzyme project (which btw is almost finished) #10873

**Comment by ValWood** [comment]
@hdrabkin  I don't think this is related to a general proposal for  "unused" terms it's just the fact that these are gene product specific terms. Being unused just makes them easier to deal with.

I suspect that early on protein kinase substrates commonly used in assays got EC numbers, but that this was unsustainable? so you will see things like casein kinase  etc.

Histone kinases might be useful, because of the histone code and since we have for other modifiers
(and CTD kinase for the CTD code?).

For others it isn't sustainable to add...

**Comment by pgaudet** [comment]
Hi @ValWood 

Are these useful in terms of MF or BP? Now we have the as both (pol II CTD and histone). 

@sylvainpoux any strong opinion on this ?

**Comment by ValWood** [comment]
I think for both.

For example we have 
17 GPs annotated to histone H3-K4 methylation
but  
1 annotation to histone methyltransferase activity (H3-K4 specific) (GO:0042800)

There are lots of gene products that contribute to the modification process.

v

**Comment by pgaudet** [comment]
Which suggests BP is more relevant ?

**Comment by ValWood** [comment]
but the MF annotation is  also critical. I think users like it the way it is  it's very clear...

**Comment by hdrabkin** [comment]
We would still need the activity term when it is the gp for the kinase itself that needs annotating right. But other genes could be contributing in some way.

**Comment by ValWood** [comment]
For instance I can find THE  histone methyltransferase activity (H3-K4 specific)
 or any of the others immediately with a query. I don't know how we would do this is they weren't in GO. Finding things is a major use of GO ;)

**Comment by pgaudet** [comment]
Recapping: 
* GO:0033868 Goodpasture-antigen-binding protein kinase activity -> 0 annotations -> will propose to obsolete - (since EC  mapping: EC:2.7.11.9 )
* GO:0047764  caldesmon kinase activity - 0 annotations
*  GO:0050063 low-density-lipoprotein particle receptor kinase activity - 0 annotations (EC  mapping: EC:2.7.11.9)

----

* GO:0016534 cyclin-dependent protein kinase 5 activator activity 
**Proposal to merge into parent: GO:0043539 protein serine/threonine kinase activator activity**
(2)	MGI @hdrabkin
(1)	ARUK-UCL  @RLovering 
(1)	FlyBase  @hattrill 
(1)	RGD  @slaulederkind
Some UniProt rules @pedruzzi 

----
I propose we keep the others for now. 

Please comment if you have objections. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: 

* GO:0033868 Goodpasture-antigen-binding protein kinase activity 
* GO:0047764 caldesmon kinase activity 
* GO:0050063 low-density-lipoprotein particle receptor kinase activity 

The reason for obsoletion is that these terms represent specific gene products, and not functions. There are no annotations, no InterPro2GO mappings to this term; this term is not included in any subset(s)(slims). 
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/12419

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 14th, 2018. Unless objections are received by November 14th, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
I guess it doesn't matter, but I wonder why GO:0016534 is not a child of GO:0061575

![image](https://user-images.githubusercontent.com/4782928/48123983-89780880-e27b-11e8-83d2-eb2b588db31e.png)

**Comment by pgaudet** [comment]
@hdrabkin so you agree with the merge,  I take it !

**Comment by hdrabkin** [comment]
yes yes; i'm agreeable!

**Comment by hdrabkin** [comment]
FYI "GO:0033868 Goodpasture-antigen-binding protein kinase activity" actually has an EC xref that has the activity name. "EC 2.7.11.9"  I wasn't expecting that.

**Comment by pgaudet** [comment]
Right - there are lots of specific enzymes, see 
https://enzyme.expasy.org/EC/2.7.11.-

Looks like GO terms were created for most. Do we want to keep anything with an EC ?

Pascale

**Comment by ValWood** [comment]
I thought we previously decided that we wouldn't keep gene product specific terms just because they have an EC. many gene product terms have an EC. This is historical. I'm sure this is decided on the tracker somewhere, possibly more than once. There have been a few discussions about it.

**Comment by pgaudet** [comment]
OK good.
