### ISSUE TITLE
GO term specificity proposal 1 (generic residues and regulatory subunit dependencies in term names)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12416]
We  always try to annotate as specifically as possible, and encourage our community to do the same.
This has highlighted a number of pages where  annotations  are sometimes get modelled arbitrarily slightly differently .

Take for example cdc2 MF annotations below:

![specificity](https://cloud.githubusercontent.com/assets/7359272/14742573/e1ce19f2-0894-11e6-8cd2-40be714c9405.jpg)

The "protein kinase activity" is described variously as
cyclin-dependent protein kinase activity
cylin-dependent protein serine/threonine kinase activity
protein kianse activity
protein serine/threonine kinase activity.

First, cyclin dependency can be captured by annotating the cyclin correctly.
Secondly the residues are not useful in this context. At the level of GO annotation, it isn't informative to know which general residues are phosphorylated. Its only useful information  if you know which specific residues are phosphorylated in a particular target protein. This should/could be captured on the modified protein, using PRO terms.

e.g
http://www.pombase.org/spombe/result/SPAC24B11.06c#modifications

but including this information in the function seems out of scope for GO?
(also applies to protein phosphatase activity  descendants)

There are various tickets where this has been discussed, but definite no proposal to merge.

@pgaudet @thomaspd @dosumis

**Comment by ValWood** [comment]
I'll link the older tickets with background to this if I find them....

**Comment by ValWood** [comment]
similarly peptidyl-serine phosphorylation
and
peptidyl-threonine phosphorylation
could merge to protein phosphorylation

**Comment by ValWood** [comment]
A similar issue was discussed here with respect to ubiquitin hydrolase residues:
https://github.com/geneontology/go-ontology/issues/12182

**Comment by jimhu-tamu** [comment]
Hi Val, saw this series while coming to post an unrelated issue.

You might also consider the various histone modification terms as things that would be affected by your proposal.

**Comment by ValWood** [comment]
In previous discussions (still haven't tracked down the ticket, we thought that the histones would be a special case. They are more meaningful *because* they refer to a specific residues where specific residue modifications are directly connected to specific biological processes (transcription, repair, checkpoint signalling etc. i.e we would still want to represent the processes of the histone code)

**Comment by dosumis** [comment]
Specificity of kinases for specific types of aa residues (e.g. Ser/Thr vs Tyr) is well within expressiveness that GO should capture and name terms for.  I have no major objection to having classes for cyclin dependency of that activity either - especially if users expect to see this as a named class and will find it hard make use of the decomposed version.   The names in these cases are not too long and are easy to understand.

**Comment by ValWood** [comment]
We have had a number of discussion about the residues with @pgaudet  Paulthomas (needs tagging github ID)  and within Pombase @antonialock 

They aren't  useful, because they don't tell you anything about the reaction (you don't know the specific residue, so on its own this information doesn't add anything to the function annotation).

I think there was general agreement about this at the LEGO meeting?

**Comment by tberardini** [comment]
Closing after discussion during editors' call.  Terms will be retained, new terms with specific residues will not be created as they have not been in the past.
