### ISSUE TITLE
central PC request place

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12413]
Request complexes 
AI: Birgit to create a submission template! 
AI: Birgit can also create a tracker account for you if you submit regularly.
AI: GO annotators to use templates when requesting complex IDs
by emailing intact-help@ebi.ac.uk or bmeldal@ebi.ac.uk with as much detail as possible. 

Goal was to create a centralised place to request PCs

**Comment by bmeldal** [comment]
Template is here:
https://docs.google.com/document/d/1Tip6hIWg1hIkR0zcjx3zwODTtUzGRuL3DTKhfqquwHc/edit?usp=sharing

Happy for it to be moved into the GO wiki somewhere...
I wonder if we should add a link to the complex curation guide on the wiki we put together, @paolaroncaglia?

**Comment by paolaroncaglia** [comment]
Sure @bmeldal , wherever the template ends up, please add a link to those guidelines.

**Comment by pgaudet** [comment]
Hi @bmeldal 
What do we need to do for this ticket ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
Don't know. The template is linked above and I'm happy to have the link on the GOC wiki somewhere but that's for GOC wiki admin to decide where it goes.

New complexes can now also be requested directly from the yellow tile on the new CP homepage (www.ebi.ac.uk/complexportal) but that's just a help-desk message until we get round to create a form behind that tile.

**Comment by pgaudet** [comment]
Added this to our Editor's documentation: 
https://github.com/geneontology/go-ontology/pull/13805/commits/f65cf23989df04ad50202a9df9a6c2bf519cbf8b

@ukemi @vanaukenk @monicacecilia  is this where it should be ?

**Comment by bmeldal** [comment]
Can we link to the CP homepage for requests in the GO annotation guidelines and close this?

**Comment by pgaudet** [comment]
@bmeldal Can you check whether this needs modifications ? 

http://wiki.geneontology.org/index.php/Requesting_a_New_Complex_ID_from_IntAct

Thanks, Pascale

**Comment by bmeldal** [comment]
Updates done. One thing I can't change is the title. Can you change that from "IntAct" to "Complex Portal", please?

**Comment by pgaudet** [comment]
Done (you need to move the page, not super convenient). 

Thanks !!!
