### ISSUE TITLE
taxon checks, regulation of cell migration, regulation of phagocytosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12410]
Never in fungi?
Possibly others could be added?

In fact for fungi I think the taxon restriction could be added at "locomotion"? Would that work for all?

**Comment by ValWood** [comment]
GO:0006909 phagocytosis never in fungi?

**Comment by ukemi** [comment]
What about conjugation? Don't the cells migrate towards each other?

**Comment by ValWood** [comment]
Hmm, they 'shmoo" towards each other...via a mating projection. I  never thought of this as migration as I don't  *think* that the cell movers, but I'd need to check @AntoniaLock ?

**Comment by Antonialock** [comment]
Shmooing is just growth, no locomotion.

I think most fungi are unable to 'move' as such, but there might be a few odd cases (chytrid spores?)

**Comment by ValWood** [comment]
bummer, chitrids have been 'reclassified" as fungi (because they have chitin walls)
https://en.wikipedia.org/wiki/Chytridiomycota
but they have flagella.... Lumpers!

Lets say "never in yeast"

**Comment by Antonialock** [comment]
yeah I'm also unsure of the predatory fungi. I think they just use a variation of a mechnaism with a sticky trap + growing towards their prey, but I'm not entirely sure.

**Comment by tberardini** [comment]
Summary:

phagocytosis never in yeast
cell migration never in yeast

or

phagocytosis never in fungi
locomotion never in yeast

or

some other combination

Please specify which term and which restriction.

**Comment by ValWood** [comment]
I think its this way...

phagocytosis never in fungi
locomotion never in yeast

**Comment by tberardini** [comment]
Yeast = Ascomycota?

**Comment by tberardini** [comment]
Done.

**Comment by ValWood** [comment]
yep, plus "Basidiomycota"

**Comment by tberardini** [comment]
Basidiomycota = yeast?  Fungi, yes, but I thought that all yeast were under Ascomycota (but other stuff under Ascomycota too).

Dikarya = Ascomycota + Basidiomycota, should the restriction be up at Dikarya?

**Comment by Antonialock** [comment]
I think it would be safe to say locomotion never in dikarya.

Can you do "phagocytosis never in unicellular organism?"

The phagocytosis def
An endocytosis process that results in the engulfment of external
particulate material by phagocytes. The particles are initially contained
within phagocytic vacuoles (phagosomes), which then fuse with primary
lysosomes to effect digestion of the particles.

so it wouldn't apply to anything unicellular.

A.



On Thu, Apr 21, 2016 at 4:59 PM, Tanya Berardini <notifications@github.com>
wrote:

> Basidiomycota = yeast? Fungi, yes, but I thought that all yeast were under
> Ascomycota (but other stuff under Ascomycota too).
>
> Dikarya = Ascomycota + Basidiomycota, should the restriction be up at
> Dikarya?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geneontology/go-ontology/issues/12410#issuecomment-212986419>
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
So in that case is should be a"multicellular process" and then the  correct taxon checks will be there

**Comment by ukemi** [comment]
Don't paramecium and tertrahymena phagocytose?

**Comment by tberardini** [comment]
Yes, paramecia phagocytose.

http://www.intechopen.com/books/molecular-regulation-of-endocytosis/imaging-of-endocytosis-in-paramecium-by-confocal-microscopy

I'll move the locomotion restriction up to never in Dikarya

**Comment by mah11** [comment]
>  Can you do "phagocytosis never in unicellular organism?"

Absolutely not. Amoebae are one cell apiece.

**Comment by Antonialock** [comment]
yeah I thought a 'phagocyte' was a cell-type of multicellular organisms

**Comment by mah11** [comment]
> I thought a 'phagocyte' was a cell type of multicellular organisms 

As commonly used, it is, but phagocytes aren't the only kind of cells that can do phagocytosis.

**Comment by tberardini** [comment]
-relationship: never_in_taxon NCBITaxon:4890 ! Ascomycota
+relationship: never_in_taxon NCBITaxon:451864 ! Dikarya
