### ISSUE TITLE
GO term specificity proposal 3, some places where complexes could be 'pruned' in GO

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12418]
1. Protein complexes that are not functionally relevant:
   This looks like it could be an example:
   http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0034457#term=info
   A protein complex that forms a subcomplex of the 90S preribosome. In S. cerevisiae, it is composed of Mpp10p, Imp3p and Imp4p. 
cohesin core heterodimer ( I think this is a non-functional assembly intermediate?)

2. location specific versions of complexes (where the composition is IDENTICAL)
   O:0031595   nuclear proteasome complex
   GO:0000799 nuclear condensin complex
   GO:0000777  condensed chromosome kinetochore
   GO:0000941 condensed nuclear chromosome inner kinetochore
   GO:0034990 nuclear mitotic cohesin complex  
   (maybe here we could  use extension part_of location?)
   (Not that we need to keep the mitotic and meiotic versions of these complexes because the composition is DIFFERENT)

3.  a cell-type-specific variants? (presumably these are the same composition usually with cell type specific isoforms?)

TAF4B-containing transcription factor TFIID complex
Definition
A transcription factor TFIID complex that contains the TBP-associated factor TAF4B (also known as TAFII105 in human), a cell-type-specific variant of TAF4.

More later....

**Comment by ValWood** [comment]
@pgaudet @thomaspd @dosumis

**Comment by tberardini** [comment]
From internal discussion:

"Agree that this is actually a mixed bag of proposals.   I support the removal of activity terms defined only with reference to particular protein of protein complex:

fubar activity = the activit(y/ies) of the fubar complex.  In these cases, annotation needs to be to a more generic term for the activity in question, with the protein or complex named in an extension  (see my comment on https://github.com/geneontology/go-ontology/issues/12420)

OTOH, I think specifying a target of an activity can be useful & we need to tread carefully in removing these terms."  -dos

**Comment by ValWood** [comment]
This ticket wasn't about the terms like "APC activator activity" etc. ?

**Comment by dosumis** [comment]
Pasted comment from Tanya is by me - but looks like it ended up on the wrong ticket.

Agree that location and cell-type specific variants should be canned unless their composition is distinct.

**Comment by pgaudet** [comment]
@ValWood 
What do you propose here ?

**Comment by ValWood** [comment]
I don't think 1 or 3 happen so much now.

I think it would be better to  have only one version of the same component
but it doesn't bother me so much. It's low priority.

Close?
