### ISSUE TITLE
5-carbamoylmethyluridine metabolic process - needs to be renamed and moved

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12415]
Hello, 5-carbamoylmethyluridine (GO:0080178) is an RNA modification, it is not synthesized directly. (see PMC2956550 "All nucleoside modifications except Q are made on the polynucleotide level, i.e. they are made post-transcriptionally  "

So "5-carbamoylmethyluridine metabolic process" should be moved as a child of 
GO:0001510 	RNA methylation 
and of a new term RNA carbamoylation 

The terms in that branch are named xx 'synthesis', it seems to me it would be more accurate to have something along the lines of "uracil modification to 5-carbamoylmethyluridine" (we may be able to tease out the reaction more precisely, but AFAIK what I am proposing is correct). 

Thanks, 
Pascale

**Comment by hdrabkin** [comment]
Yes, definitely not synthesized directly. 
I suggest something mentioning "residue', like uracil residue modification.... 
Note 5-caramolymethy uridine modification is multi-step 
ELP1-ELP6 and KTI11-KTI13 genes are all required for an early step in synthesis of 5-methoxycarbonylmethyl (mcm5) and 5-carbamoylmethyl (ncm5) groups present on uridines at the wobble position in tRNA."PMID:15769872

**Comment by ukemi** [comment]
So I propose:

Rename term to be '5-5-carbamoylmethyl uridine modification' with a synonym of the current name.
Move the term to be a child of RNA methylation
or
Move the term to be a child of a new child or methylation, uridine residue methylation

Which to you recommend?

**Comment by ukemi** [comment]
'5-carbamoylmethyl uridine modification' not '5-5-carbamoylmethyl uridine modification'

**Comment by hdrabkin** [comment]
former sounds fine I think

**Comment by ukemi** [comment]
@tberardini 

Since this is originally plant term, can you please check to be sure these changes are ok.

**Comment by tberardini** [comment]
Checked paper: http://bmcplantbiol.biomedcentral.com/articles/10.1186/1471-2229-10-201

I'd suggest moving to 'tRNA methylation' instead of the more general 'RNA methylation'.
I like the modified term name '5-carbamoylmethyl uridine modification' and suggest an additional synonym, 'ncm5u modification'.

The def probably needs a little sprucing up to match the new parentage to update the existing standard 'metabolic process' def.

**Comment by ukemi** [comment]
Thanks for checking. I had already modified the def, but wanted to be sure the free nucleotide wasn't part of plant secondary metabolism. My diff is below:

 [Term]
 id: GO:0080178
-name: 5-carbamoylmethyluridine metabolic process
+name: 5-carbamoylmethyl uridine residue modification
 namespace: biological_process
-def: "The chemical reactions and pathways involving 5-carbamoylmethyluridine." [GOC:tb]
-is_a: GO:0046131 {is_inferred="true"} ! pyrimidine ribonucleoside metabolic process
-intersection_of: GO:0008152 ! metabolic process
-intersection_of: has_participant CHEBI:62005 ! 5-carbamoylmethyluridine
+def: "The chemical reactions and pathways involving the addition of a  5-carbamoylmethyl group to a uridine residue in RNA." [GOC:dph, GOC:tb]
+synonym: "5-carbamoylmethyluridine metabolic process" RELATED []
+is_a: GO:0030488 ! tRNA methylation
 created_by: donghui
 creation_date: 2011-04-28T04:36:23Z
