### ISSUE TITLE
GOC to decide what is HTP data

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12412]
AI from Geneva GOC meeting
https://docs.google.com/document/d/12CDf4s8YsylPMNHM3UuPis9NyVQ9WFpBpNYTFYAH7kc/edit

@bmeldal @selewis @cmungall @tonysawfordebi 

Discussion at managers call: make sure we have an ECO to capture this

**Comment by tberardini** [comment]
@mcourtot, I think this belongs in the annotation tracker, no?  Not an ontology issue.

**Comment by mcourtot** [comment]
Discussion at annotation call:
- if hypothesis driven, no HTP even if large dataset as better quality
- non-hypothesis driven, exploratory: HTP

**Comment by mcourtot** [comment]
@tberardini: I agree, but don't know if/how to move ticket between trackers? Should I just close and open  a new one?

**Comment by tberardini** [comment]
@mcourtot: yup, just close this one, and copy/paste all the relevant stuff into the new issue in the relevant tracker.  There might be a way to move tickets between trackers but that's not an option that I have available with my privileges.

**Comment by mcourtot** [comment]
Moved to https://github.com/geneontology/go-annotation/issues/1390
