### ISSUE TITLE
taxon restrictions on nevous system processes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12411]
Hello, 

I came across 
GO:0042063 gliogenesis
The use of this term should conform to the following taxon constraints:
Ancestor GO ID 	Ancestor GO Term Name 	Relationship 	Taxon ID 	Taxon 	Reference(s)
GO:0032501 	multicellular organismal process 	never_in_taxon 	4896 	Schizosaccharomyces pombe 	
GO:0032501 	multicellular organismal process 	never_in_taxon 	4932 	Saccharomyces cerevisiae 	
GO:0032501 	multicellular organismal process 	only_in_taxon 	2759 	Eukaryota 	

I am not an expert in neurobiology, but wikipedia claims that the nervous system evolved in metazoa (https://en.wikipedia.org/wiki/Evolution_of_nervous_systems). I suggest that all descendants of 
 GO:0007399 nervous system development and GO:0050877 neurological system process be minimally limited to metazoa. 

Thanks, Pascale

**Comment by tberardini** [comment]
Leaving open for a few days for comments.  If there are none, I will add restrictions to GO:0007399 nervous system development and GO:0050877 neurological system process for only in metazoa.

**Comment by paolaroncaglia** [comment]
@cmungall 
This may be a question for UBERON.
GO ‘nervous system development’ points to UBERON ‘nervous system’. The latter doesn’t have a formal taxon constraint, but says, consistently with Pascale’s comment: 
“homology_notes: Nervous systems evolved in the ancestor of Eumetazoa.[well established][VHOG]”
see
http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_0001016
Should UBERON_0001016 ‘nervous system’ be limited to Metazoa (or Eumetazoa)?

@pgaudet @tberardini 
GO:0050877 neurological system process is already restricted to only in taxon Metazoa.

**Comment by dosumis** [comment]
Bigger question: Don't we need a plan for turning the inheritance of taxon restriction from Uberon back on ?

I believe it was turned off because of the number of things that needed fixing (I thought there was a  ticket with details of progress but can't seem to find it).   It's not a massive amount of work, we just need to schedule a time when we (myself + Chris & @ukemi ?) can commit to doing it.

**Comment by paolaroncaglia** [comment]
@dosumis , I added to the agenda for today's editors call. Not sure we'll get there, though...

**Comment by tberardini** [comment]
Didn't get to this during yesterday's call so will wait till next week.

**Comment by dosumis** [comment]
Covered in editor's call.  Suggest we add taxon constraints to Uberon, from where they will soon be imported:

'nervous system' only_in_taxon Metazoa

I don't think this will be sufficient for the constraint on gliogenesis (if it was, we couldn't have terms for phylogenetically restricted parts of nervous systems.  For that, I think we would need a taxon restriction on CL and imports from there.  @cmungall  is this possible, or should we add in GO for now?

**Comment by tberardini** [comment]
Is there an action item for this issue or can all the issues be addressed by changes to Uberon and CL?

**Comment by dosumis** [comment]
Nervous system constraint can come from Uberon. Only a few issues to fix
before we turn Uberon taxon imports back on.

**Comment by tberardini** [comment]
Ok, I will leave this issue open until Uberon taxon imports are back on and we can verify that the taxon constraints have been propagated as we hope.

**Comment by cmungall** [comment]
blocked on #12223

**Comment by dosumis** [comment]
All taxon restrictions on anatomical structures on anatomical structures are now inherited from Uberon.  This ticket therefore belongs on the [Uberon tracker](https://github.com/obophenotype/uberon/issues).

(This may be handy https://github-issue-mover.appspot.com/)

**Comment by tberardini** [comment]
@cmungall, @dosumis  - can I close this now that the linked issue #12223 has been resolved?  Do I need to open a ticket on the Uberon tracker for adding a taxon constraint to UBERON_0001016?  Thanks.

**Comment by cmungall** [comment]
we already have

```
id: UBERON:0001016
name: nervous system
...
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa
relationship: never_in_taxon NCBITaxon:6040 ! Porifera
```

this is now propagated to any GO terms that existentially depend on a nervous system over the appropriate relations. I'll close this ticket. Assuming no one thinks plants have nervous systems 

http://phenomena.nationalgeographic.com/2015/12/15/can-a-plant-remember-this-one-seems-to-heres-the-evidence/

**Comment by tberardini** [comment]
CLOSE this issue. In fact, I'll just do that.

Plants don't have nervous systems.
