### ISSUE TITLE
GO term specificity proposal 6 convoluted precomposition of functions involved in processes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12427]
I think I'm responsible for this batch, but I think its our "worst case".

![convoluted precomposition of functions involved in processes](https://cloud.githubusercontent.com/assets/7359272/14810212/a21e99ec-0b89-11e6-891a-7b7fe2a7678d.jpg)

This one will definitely be helped by a LEGO model.
At first glance most of these terms seem to be just plain unnecessary if we just link the annotated molecular function to a process?

@AntoniaLock a good one for LEGO after iron-sulfur cluster assembly?

**Comment by dosumis** [comment]
I'm happy with the signaling pathways mentioning specific protein families.  Seem unavoidable if we're going to capture the science.

**Comment by ValWood** [comment]
The problem here isn't the way the signalling pathway is named its  the "by blah blah blah"
I think these terms were mainly for  single steps (functions) in a pathway which is pretty well characterised now...

For example we have
GO:1901487 negative regulation of SREBP signaling pathway by positive regulation of transcription factor catabolic process in response to increased oxygen levels

used to annotate a ubiquitin ligase complex which degrade the transcription factor.  We wouldn't want to do this generally. I thought you wanted to get rid of these ;)

We would hopefully capture the target of the ligase, and then link the function to the process by involved in  "negative regulation of SREBP signaling pathway"?

It would be much neater.

**Comment by dosumis** [comment]
Just to confirm: 'SREBP signaling pathway' & '(+/-)ve reg SREBP signaling pathway' are OK, but the 'by' clauses are a step too far?

What about the 'in response to' clauses?  They look like they might be useful.

**Comment by ValWood** [comment]
When I look at the annotations for this, I know it isn't the way we would annotate this  now.
SPEBP signalling is defined:
A series of molecular signals from the endoplasmic reticulum to the nucleus generated as a consequence of decreased levels of one or more sterols (and in some yeast, changes in oxygen levels) and which proceeds through activation of a sterol response element binding transcription factor (SREBP) to result in up-regulation of target gene transcription. 
PMID:12923525 PMID:22017871
I even wonder if it  we have conflated 2  related pathways.

There is some TF catabolism which directly  negatively regulates the transcription factor. I now wonder if this should be part of the pathway at all (it just has the same endpoint).

I'll take the ticket and PomBase will LEGO  annotate the pathway and LEGO model, and then propose any term revisions.  I think we have enough details about the pathway to model the individual functions.

**Comment by ValWood** [comment]
(realistically  >6 months  away as we already have  larger pathways in progress)

**Comment by dosumis** [comment]
Ta

**Comment by ValWood** [comment]
over post composition of siganalling pathway terms.

Would be better served by more Noctua-esque

MF involved in BP annotations....

**Comment by pgaudet** [comment]
@ValWood what do you want to do here ?

**Comment by ValWood** [comment]
GO:0100060 has no annotations, obsolete
GO:0100062
GO:0100061
GO:1901294
GO:1901486 pombe has 3 annotations, obsolete we can post compose

v

**Comment by judyblake** [comment]
Hey all,  I object to obseleting terms unless and until those representations are available to our users.  As I read this,  1)  the GO-CAM models are not made and 2) the translation of those models for the tools our users use are not yet available.  This seems to be putting the car before the horse.  Maybe line such tickets up for quick resolution once we can serve our users better.

**Comment by ValWood** [comment]
Hi Judy,

These terms were ONLY used by PomBase and have already been replaced by post-composed annotations  (function part of process). Cam models is not the only way make these annotations-  any group who can annotate using extensions  can make  the equivalent annotations (much more quicky IMHO)  as we have done here (we did not lose any of the annotation meaning).

Obsoleting such terms once they   are no longer used will stem the propagation  of similar types of terms in the ontology (which is unsustainable for ontology development).

v

**Comment by judyblake** [comment]
ok Val got it.   I didn't see that the terms have been replaced and can be captured with post-computational terms.  ok then.  Just a 'general concern' on my part based on the post by Pascale.

**Comment by Antonialock** [comment]
pombe annotations will be gone next update

**Comment by pgaudet** [comment]
Also obsoleted 

- GO:1901489   positive regulation of SREBP signaling pathway by negative regulation of transcription factor catabolic process in response to decreased oxygen levels
0 annotations

- GO:1901488 positive regulation of SREBP signaling pathway by negative regulation of transcription factor catabolic process
0 annotations
