### ISSUE TITLE
NTR: ‘(positive/negative) regulation of right ventricular blood pressure'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12423]
Dear Editors,

I have recently been annotating a paper (PMID:22161164), which relied on the measurement of right systolic ventricular pressure (RSVP) as an indicator of the lung (pulmonary) blood pressure. 

Basic scientists as well as clinicians use the measurement of RVBP (e.g. in PMID:22161164) to estimate lung blood pressure. For instance, normal human RVBP and lung blood pressure are usually both close to 20/15 mmHg. 

However, although in normal circumstances RVBP and lung blood pressure will give the same numerical value, they are not the same pressures. 

RVBP is a function of the volume of the blood in the RV and the resistance of the ventricular walls, therefore as ventricles contract (systole), the pressure inside them will increase. However, until RVBP is sufficiently high to open the valve and allow the blood to start flowing into the pulmonary artery, the pressure in the artery will remain lower than in the RV. Whereas once the stroke of blood has been ejected into the pulmonary artery, the pressure in this artery (and then the lungs) will be higher than in the RV, which will have just emptied.

In view of the above, we have had several group discussions about whether we should request a new term: ‘(positive/negative) regulation of right ventricular blood pressure (RVBP)’ as a child term of ‘regulation of blood pressure’.

It would additionally be helpful to add a comment in QiuckGO to this ‘regulation of RVBP’ term to clarify that scientists and clinicians typically use RVSP as a measurement of the lung/pulmonary blood pressure, as the measurements of these pressures are typically the same. Nonetheless, regulation of RVSP is not synonymous with the regulation of lung/pulmonary blood pressure. The same comment could also be added to the already existing ‘regulation of lung blood pressure’ terms. 

Perhaps alternatively (or in addition), ‘regulation of RVBP’ could have a ‘part of’ relationship with ‘regulation of lung blood pressure’, as it is such a major factor influencing the latter?

The blood pressure (positive and negative) regulation terms, which currently exist in GO include:

Id: GO:0008217
Name: regulation of blood pressure

Id: GO:0003073
Name: regulation of systemic arterial blood pressure
Is_a: GO:0008217 regulation of blood pressure

Id: GO:0014916
Name: regulation of lung blood pressure
Is_a: GO:0008217 regulation of blood pressure
Synonym: regulation of pulmonary blood pressure (exact)

(Link to ancestor chart: https://www.ebi.ac.uk/QuickGO/GMultiTerm#a=64%2400m1020P03f4&tab=chart&c=&chartTab=settings)
 
Unlike the systemic circulation, the pulmonary circulation is a low-pressure system, therefore there are no distinct differences between the right ventricular blood pressure (RVBP) and the pulmonary (lung) pressure in terms of measurements (both are ~20/15 mmHg in human). However, they are not synonymous. And additional factors, which do not affect RVBP (e.g. artery elasticity), will affect the lung blood pressure.

Therefore, although the annotated paper (PMID:22161164) focused on pulmonary hypertension, we decided that ‘regulation of lung blood pressure’ was too far downstream to annotate to this term, based on the presented data and the measurements of RVBP. 

Instead, we annotated the entity rno-miR-17-5p to positive regulation of blood pressure (GO:0045777) IMP occurs_in UBERON:0002080 heart right ventricle.

However, having RVBP regulation terms for this type of annotations would have been very helpful.

I will look forward to hearing from you.

Thank you,
Barbara

GOC:BHF_miRNA
GOC:BHF
GOC:bc

@rachhuntley 
@RLovering

**Comment by tberardini** [comment]
@ukemi - could you review please?

**Comment by ukemi** [comment]
Hi Barbara,

I am a bit concerned that this term represents a phenotype (that is measured) and not the process that results in the pressure change. Since this is used as a proxy (method) to measure pulmonary pressure, wouldn't it be better to annotate to regulation of lung blood pressure? 

-D

**Comment by BarbaraCzub** [comment]
Hi David,

I agree with your concerns, and for this reason we have been discussing this issue for weeks within our group before we actually decided that I should submit this request/enquiry.

It is true that it was the intention of the authors to study the lung blood pressure and scientists typically use the measurement of right ventricular blood pressure (RVBP) as an estimate of lung blood pressure.

However, we have not annotated to regulation of lung blood pressure, because we decided that it was slightly too far downstream from regulation of the RVBP and there might have been other factors (e.g. changes in pulmonary artery elasticity due to vascular remodelling, which is known to occur in response to hypoxia and which has also been demonstrated in this paper), which could affect the actual pulmonary pressure, but not RVBP.

Are you advising we should revise the annotation "rno-miR-17-5p positive regulation of blood pressure (GO:0045777) IMP occurs_in UBERON:0002080 heart right ventricle" in view of the authors’ intent?

Or perhaps it might be more appropriate to use the experimental annotations:
"rno-miR-17-5p positive regulation of blood pressure (GO:0045777) IMP occurs_in UBERON:0002080 heart right ventricle" 
and
"rno-miR-17-5p positive regulation of pulmonary blood vessel remodelling (GO:1905111) IMP occurs_in UBERON:0002012 pulmonary artery" 

to create an IC annotation: "rno-miR-17-5p positive regulation of lung blood pressure (GO:0045777) IC ?

@rachhuntley would you like to add any other comments on this issue?

Thanks,
Barbara

@RLovering

**Comment by ukemi** [comment]
Hi Barbara,

I think you need to decide if what you are trying to annotate is a normal physiological process or whether it is the result of a pathological process and whether you are annotating a phenotype or the process. It is a similar situation to an author using a DNA ladder assay to monitor apoptosis, but we wouldn't want to annotate to DNA fragmentation or to the regulation of DNA fragmentation just because that is what they measured. Loss of elasticity leading to increased blood pressure as a result of ischemia sounds more like a pathological phenotype that a GO process to me. One thing I always ask myself when annotating is, what is the natural biological objective to which the gene product is contributing. In this case it really doesn't sound like it is the regulation of blood pressure in the ventricle, that's just where they measured it. 

-D

**Comment by BarbaraCzub** [comment]
Hi David,

Thank you for your suggestions. We have reviewed the paper again and reconsidered our NTR.

Could we please request the following two new terms instead:
- positive regulation of lung blood pressure
- negative regulation of lung blood pressure
?

Thanks,
Barbara

@rachhuntley 
@RLovering

**Comment by ukemi** [comment]
[Term]
+id: GO:0061766
+name: positive regulation of lung blood pressure
+namespace: biological_process
+def: "The process that increases the force with which blood travels through the lungs." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:22161164]
+synonym: "positive regulation of pulmonary blood pressure" EXACT [GOC:dph]
+is_a: GO:0014916 ! regulation of lung blood pressure
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates OBA:0000090 ! lung blood pressure
+created_by: dph
+creation_date: 2016-04-27T11:54:34Z
+
+[Term]
+id: GO:0061767
+name: negative regulation of lung blood pressure
+namespace: biological_process
+def: "The process that decreases the force with which blood travels through the lungs." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, GOC:dph, PMID:22161164]
+synonym: "negative regulation of pulmonary blood pressure" EXACT [GOC:dph]
+is_a: GO:0014916 ! regulation of lung blood pressure
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates OBA:0000090 ! lung blood pressure
+created_by: dph
+creation_date: 2016-04-27T11:58:55Z

**Comment by BarbaraCzub** [comment]
Thank you!
