### ISSUE TITLE
MP:  GO:0005851 - eukaryotic translation initiation factor 2B complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12428]
GO:0005851 - eukaryotic translation initiation factor 2B complex 
Definition: "A multisubunit guanine nucleotide exchange factor which catalyzes the exchange of GDP bound to initiation factor eIF2 for GTP, generating active eIF2-GTP. In humans, it is composed of five subunits, alpha, beta, delta, gamma and epsilon." [PMID:9438375]

Add parent
GO:0032045 guanyl-nucleotide exchange factor complex

?

**Comment by dosumis** [comment]
Fixed (via capable_of relationship -> inference)

**Comment by ValWood** [comment]
why not is_a?
isn't it capaable of MF?
