### ISSUE TITLE
NTR: epididymosome

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12425]
Original ticket submitted by Marion Gremse (BRENDA) on April 18th on the old SourceForge ontology tracker (https://sourceforge.net/p/geneontology/ontology-requests/11825/). Text:

"New term request: epididymosome
A small, membranous vesicle, within the epididymal lumen, in which spermatozoa acquire membrane proteins. https://en.wiktionary.org/wiki/epididymosome
With many greetings from the database BRENDA, Marion"

I'll point Marion to this tracker.

**Comment by brendamg** [comment]
The term is used in PMID:23177142.

**Comment by dosumis** [comment]
How's this:

name: epididymosome
def: "A microvesicle of the epididymal fluid from which spermatozoa acquire membrane proteins.' [PMID:26112475, PMID:23177142, GOC:mg, GOC:dos]
is_a: microvesicle

?

I will add a tracker item to the Uberon tracker requesting terms for epidymal lumen and fluid.  Once this has been added to Uberon, I'll create a part relationship between them.

**Comment by dosumis** [comment]
Added epididymosome.  See above link for related Uberon request.
