### ISSUE TITLE
GO:0005102 receptor binding receptor definition and GO:0046789_!_host_cell_surface_receptor_binding

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12421]
GO:0046789_!_host_cell_surface_receptor_binding appears to be used for viral proteins that bind host receptors in the virology sense of what a receptor is. 

However, the parent term GO:0005102 receptor binding has this definition: 
"Interacting selectively and non-covalently with one or more specific sites on a receptor molecule, a macromolecule that undergoes combination with a hormone, neurotransmitter, drug or intracellular messenger to initiate a change in cell function." [GOC:bf, GOC:ceb, ISBN:0198506732]

This seems to exclude virus binding to host receptors, especially where the receptor is thought to be passive (as opposed to initiating endocytosis) in some phage infections. But would expanding the definition of receptor here cause other problems in the ontology? There seems to be a distinction that the receptor, which is not necessarily a surface protein (e.g. estrogen receptor) is at the beginning of a signaling process vs the many binding events downstream.

In a phage infection, I could argue that the cellular receptor could be thought of as the ligand and the viral receptor binding protein is actually the receptor, because the interaction triggers a process in the virus - ejection of the genome into the host. But I don't think we can do that due to the historical usage of how the interaction is described. 

edit to add: consider the broader meaning of receptor in the process term:

GO:0046813 receptor-mediated virion attachment to host cell

**Comment by tberardini** [comment]
related discussion on the definition of receptor here #12362
@rebeccafoulger - making you aware of this issue

**Comment by pgaudet** [comment]
Hi, 

I removed the parent 'receptor binding' and added 
'part of' some 'adhesion of symbiont to host cell' 

If there is a problem please reopen the ticket. 

Thanks, Pascale
