### ISSUE TITLE
GO:1990376 negative regulation of G1/S transition of mitotic cell cycle by positive regulation of transcription from RNA polymerase II promoter in response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12437]
GO:1990376 negative regulation of G1/S transition of mitotic cell cycle by positive regulation of transcription from RNA polymerase II promoter in response to nitrogen starvation

could we obsolete this term, we wouldn't use it in annotation now(it has no exp annotations, and I don't think there is any transcriptional control of G1/S transition. I think this was probably requested in error (old annotations are deleted).

**Comment by ukemi** [comment]
The obsoletion email has been sent.

**Comment by robnash** [comment]
Hi,

Not particularly tied to this term and I am sure it will eventually be deconstructed and reconstructed wtih lego but ... the statement that there is no transcriptional control of the G1/S phase transition (aka START)  or for that matter any of the major cell cycle transitions is just plain wrong. 

Some reviews:
http://www.ncbi.nlm.nih.gov/pubmed/?term=7917338 
http://www.ncbi.nlm.nih.gov/pubmed/?term=8575215
http://www.ncbi.nlm.nih.gov/pubmed/?term=16285853
http://www.ncbi.nlm.nih.gov/pubmed/?term=12526763

A few of the thousands of primary papers:
**http://www.ncbi.nlm.nih.gov/pubmed/?term=7588610**
http://www.ncbi.nlm.nih.gov/pubmed/?term=18633409
http://www.ncbi.nlm.nih.gov/pubmed/?term=12464632
http://www.ncbi.nlm.nih.gov/pubmed/?term=23877564
http://www.ncbi.nlm.nih.gov/pubmed/?term=1832338

especially one of the first:
**http://www.ncbi.nlm.nih.gov/pubmed/?term=8372350**
with its very own perspective for those with short attention spans:
**http://www.ncbi.nlm.nih.gov/pubmed/?term=8372349**

and is not just G1/S:
http://www.ncbi.nlm.nih.gov/pubmed/?term=8402888

I could go on but I will stop here.

Rob

**Comment by ValWood** [comment]
Hi Rob,

The term in question is a negative regulation term.

When we had the cell cycle workshop the experts said that all of the 
regulation  for the transitions was post-translational. Except that in 
S. cerevisiae (not pombe) G1/S was transcriptionally regulated by a 
positive feedback loop for the trancription of cyclins which was part of 
the positive regulation of the transition.

This term  we are obsoleting doesn't make sense to me...its negative 
regulation of the transition by negative regulation of transcription, 
and I don't think that this exists does it?

This was only used (incorrectly) for fission yeast. I thought it safer 
to get rid of it because it has been transferred by the Compara pipeline 
and now generates 83 other fungal annotations.

The positive regulation term will stay.

I hope that's OK.

Val


On 04/05/2016 21:41, robnash wrote:
>
> Hi,
>
> Not particularly tied to this term and I am sure it will eventually be 
> deconstructed and reconstructed wtih lego but ... the statement that 
> there is no transcriptional control of the G1/S phase transition (aka 
> START) or for that matter any of the major cell cycle transitions is 
> just plain wrong.
>
> Some reviews:
> http://www.ncbi.nlm.nih.gov/pubmed/?term=7917338
> http://www.ncbi.nlm.nih.gov/pubmed/?term=8575215
> http://www.ncbi.nlm.nih.gov/pubmed/?term=16285853
> http://www.ncbi.nlm.nih.gov/pubmed/?term=12526763
>
> A few of the thousands of primary papers:
> *http://www.ncbi.nlm.nih.gov/pubmed/?term=7588610*
> http://www.ncbi.nlm.nih.gov/pubmed/?term=18633409
> http://www.ncbi.nlm.nih.gov/pubmed/?term=12464632
> http://www.ncbi.nlm.nih.gov/pubmed/?term=23877564
> http://www.ncbi.nlm.nih.gov/pubmed/?term=1832338
>
> especially one of the first:
> *http://www.ncbi.nlm.nih.gov/pubmed/?term=8372350*
> with its very own perspective for those with short attention spans:
> *http://www.ncbi.nlm.nih.gov/pubmed/?term=8372349*
>
> and is not just G1/S:
> http://www.ncbi.nlm.nih.gov/pubmed/?term=8402888
>
> I could go on but I will stop here.
>
> Rob
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12437#issuecomment-216996350>
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ValWood** [comment]
The other problem for the transfer was this term mentions nitrogen starvation, which was also not appropriate for transfer to other yeast.

**Comment by robnash** [comment]
Hi,

I think the experts are currently focused on one part of the regulation, the post-translational one involving PTMs like phosphorylation, ubiquitination etc. However, the reason this post struck me is there is lots of evidence that not only G1/S, but also passage through S phase, mitosis (both entry and exit) have a  large transcriptional component. Just less in vogue now as people have moved from microarrays to protien chips and fancy mass spec. So as long as the branches of the ontology remain I have no problem with this term specifically being obsoleted. I think some of these terms get too complicated and less useful as a result. I do believe lego will address much of this.

Thanks for taking another look. 

Cheers,
Rob

**Comment by ValWood** [comment]
Hi Rob,

Transcription is definitely required for passage through phases. However,  the transitions are largely  regulated by the phosphorylation state of cdc2 (I know you know this, I'm trying to describe the rationale) 

So for mitotic G2/M
GO:0000086 G2/M transition of mitotic cell cycle
The mitotic cell cycle transition by which a cell in G2 commits to M phase. The process begins when the kinase activity of M cyclin/CDK complex reaches a threshold high enough for the cell cycle to proceed. This is accomplished by activating a positive feedback loop that results in the accumulation of unphosphorylated and active M cyclin/CDK complex.
(David, the other transition defs need updating to reflect this seems to be the only one that was refined, I'll open a ticket for this).

So, the experts (who included  Rob De Bruin, who specifically works on cell cycle transcription, and Jacky Hayles from the Nurse lab), considered that the only transcription which regulated the transition  directly, was the positive feedback loop to increase cyclin levels in G1.

Obviously transcription of the other participating  gene products is required, but it wasn't considered to be regulatory.

So, for the G2/M transitions, I would only annotate these pathways:

![g2_m_regulation](https://cloud.githubusercontent.com/assets/7359272/15039003/d0458024-12a0-11e6-85e2-a3e51ea307a7.jpg)

to regulation of the transition, but not the transcription of the genes responsible.

If the activation of a pathway is directly through transcription making the gene products available (as is often the case for metabolic pathways), I would annotate transcription as regulatory.
Does that make sense?

Val

**Comment by ukemi** [comment]
Hi Val and Rob,

Thanks for your comments on this. Val, even though Rob knows this stuff, it's good for you to put it in here for me. We have a week before I plan to obsolete. Can you guys post here if you don't want me to obsolete this term in a week's time? This way you will have some time to think about it. Rob, you are correct, this is one of those terms that would be waaaaaaay better represented in a LEGO model.

-D

**Comment by ValWood** [comment]
I guess the question is, what  would we annotate to 

GO:1990376 negative regulation of G1/S transition of mitotic cell cycle by positive regulation of transcription from RNA polymerase II promoter in response to nitrogen starvation
(PomBase created the term, and then removed our annotation, they were wrong).

I don't think that there is any negative regulation of this transition by positive regulation of transcription (this is via checkpoints).

David, maybe you could clarify the statement  to the list above, my original comment should have said "no negative regulation of G1/S via transcription". and that we aren't touching the "positive regulation of G/1S via transcription" term. Or I can...

**Comment by ukemi** [comment]
Don't you think the discussion in this ticket is enough? The original notice linked to this. But, feel free to send a clarification e-mail if you think it is necessary.

**Comment by ValWood** [comment]
OK no point cluttering peoples in boxes. I'd be worried though, if people thought we were obsoleting all the  regulation of transition by transcription terms.

**Comment by robnash** [comment]
Hi,

Apologies I did not see these updates yesterday. Too much to do these days and not enough time. Yes, I agree that phosphorylation and activation of CDC2/CDC28/CDK1 are crucial for mitosis and for G1/S. Yes, the feedback loop in G1 is critical and also has an upstream component (Cdc28p/Cln3p), which is essential for this loop to amplify the transcriptional signal. We could argue that PTMs are most important or counter argue that transcription is really what drives a transition ... but in the end its just a which came first the chicken or the egg argument. Some of these posts have caught my eye as I spent years working on the G1/S phase transition in yeast so know a bit about the cell cycle, maybe too much for my own good.

I am okay with the obsoletion of this term, as I think they just get too long and complicted with A regulating B regulating C etc., and again think lego may help us in the long term to get away from these terms that take too or three breathes to utter. As long as the terms such as:

GO:0000083 regulation of transcription involved in G1/S transition of mitotic cell cycle
and child term are maintained.

Maybe the terms that go in the other direction are not explicitly needed such as:

GO:0100052 negative regulation of G1/S transition of mitotic cell cycle by transcription from RNA polymerase II promoter

As long as we can annotate activities that tie transcription to passage though specific cell cycle transitions we might be okay.

Cheers,
Rob

**Comment by ukemi** [comment]
#12438
We should probably have a look at this issue as well.

**Comment by ukemi** [comment]
Obsoleted this term.

**Comment by ukemi** [comment]
Still need to obsolete GO:0100052. Do you think we should also obsolete GO:1900477?

**Comment by ValWood** [comment]
Lets wait to do G1/S in lego for this.....too complicated

**Comment by ukemi** [comment]
Hi Val,

Show should we reclose this one?

-D

**Comment by ValWood** [comment]
Yes. G1/S is not on my list. I'm still doing G2/M and  mitotic chromsome segregation...can be dealt with later....
