### ISSUE TITLE
redundant term under "regulation of G1/S transition"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12438]
regulation of G1/S transition

GO:0031657
Name	regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

the G1/S transition is a cell cycle transition mediated by a cyclin dependent kinase. Therefore, *any* regulation of the G1/S transition must proceed through the cyclin dependent kinase.

This means that there is no difference between this term and
GO:2000045 regulation of G1/S transition of mitotic cell cycle

Although the definition of this term could be better.

Maybe
A cell cycle regulatory process that controls the commitment of a cell from G1 to S phase of the mitotic cell cycle mediated by the activation of a  cyclin dependent kinase.

and some merges?

**Comment by ukemi** [comment]
Hi Val,

This makes sense. Which way should I do the merge?

-D

**Comment by ValWood** [comment]
To my mind we only need
 GO:2000045 regulation of G1/S transition of mitotic cell cycle

**Comment by ukemi** [comment]
I started to do this today, but noticed that in the other ticket, we decided that the transition could be regulated transcriptionally. The transcription terms are all children. Do we really want to merge all of these?

**Comment by ValWood** [comment]
Hi David,

The transcriptional regulation still feeds into the  "regulation of cyclin-dependent protein serine/threonine kinase activity". There is *no* way to get through the transition without activating the CDK/cyclin. The  general transition terms should all include the phrase "mediated by the activation of a cyclin dependent kinase" (the transcription is either  i) causally upstream, or ii) part of the positive feedback loop as in the case of  the G1/S transition in S. cerevisiae.

I'm away next week but if you want to hold on we can work through each term on a Skype and check the defs are updated....

The advantage of not having this term is that if something is regulating the CDK directly, it would be better to have MF + target. If it is upstream, there is no additional information in this term.

Val

**Comment by ukemi** [comment]
Hi Val,

Let's do it on skype together. We can look at some of your other requests too.

-D

**Comment by ValWood** [comment]
OK will aim for the week I get back , so 23rd onwards

**Comment by ValWood** [comment]
![g2_m_regulation](https://cloud.githubusercontent.com/assets/7359272/15473060/06eaed4a-20f6-11e6-808b-7f38f606d782.jpg)

**Comment by ValWood** [comment]
This is similar but G2/M. There is all of this upstream regulation, check points -vely regulate.

The cdk is 'liscenced by cyclin" (required for the activity)
but the switch  is threshold phosphorylation level.

**Comment by ukemi** [comment]
Closed for now.

**Comment by ValWood** [comment]
LEGO will help......
