### ISSUE TITLE
mitotic cell cycle arrest in response to pheromone (question)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12439]
Is defined:
The cell cycle regulatory process in which the mitotic cell cycle is halted during one of the normal phases (G1, S, G2, M) as a result of a pheromone stimulus. An example of this process is found in Saccharomyces cerevisiae.

Excuse my ignorance but which stage does S. cerevisiae/Candida arrest in response to pheromone? is it  also G1?
Maybe we can be more specific here (before I request a new term)

**Comment by ValWood** [comment]
Pinged SGD.

**Comment by ukemi** [comment]
Val. Can't you use an annotation extension to specify the phase?

**Comment by ValWood** [comment]
I would if it was just  "during" a phase, but these are specific regulatory pathways to control important points in the cell cycle (like G1-S  transition).

In pombe this is a prerequisite for conjugation to exit the mitotic cell cycle, and it only occurs in G1, but the connection to conjugation isn't captured. 

we also have
GO:0071851 mitotic G1 cell cycle arrest in response to nitrogen starvation

I'd be happier to have
GO:NEW mitotic G1 cell cycle arrest 

and merge 
GO:0071851 mitotic G1 cell cycle arrest in response to nitrogen starvation
and
mitotic cell cycle arrest in response to pheromone


 and then capture "response to pheromone" and "response to nitrogen starvation" in extensions 
because the cell cycle phase when the arrest  occurs is more biologically critical.

**Comment by srengel** [comment]
signaling from mating pheromones arrests the cell cycle in G1.  a minority of authors say it's at the G1/S transition, but it's safe to call it a G1 arrest.

**Comment by robnash** [comment]
Mating pheromone arrest is in fact coincident with START, at the G1/ S phase transition. Much evidence, here is one:

http://www.yeastgenome.org/reference/S000043253/overview
PMID: 7002718

Cheers,
Rob

**Comment by ValWood** [comment]
So its OK to change this term  to
mitotic cell cycle  G1 arrest in response to pheromone?

(it must be *before* the G1/S transition point because after this  point you *can't enter the conjugation pathway?)

Val

**Comment by srengel** [comment]
seems fine to me.

**Comment by ukemi** [comment]
Modified term name and definition as suggested.
