### ISSUE TITLE
CoA-synthesizing protein complexes

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12430]
The biology of these is not entirely clear.

We know the constitution of GO:0071513 phosphopantothenoylcysteine decarboxylase complex but I would add capable_of_part_of GO:0015937 coenzyme A biosynthetic process. (PMID:26514574)

The larger complex, GO:1990143 CoA-synthesizing protein complex, is less well described. It may have up to 6 subunits in yeast but we have agreed only CAB2-5 can be confidently grouped. I think we should loosen the def so it matches the complex in the CP.

old def:
A multisubunit complex likely involved in the synthesis of coenzyme A (CoA). In S. cerevisiae, the complex is formed by Cab2, Cab3, Cab4, Cab5, Sis2 and Vhs3. 

new def:
A multisubunit complex likely involved in the synthesis of coenzyme A (CoA). In S. cerevisiae, the complex consists of at least Cab2, Cab3, Cab4 and Cab5 but may also include Sis2 and Vhs3. The latter subunits are shared by the GO:0071513 phosphopantothenoylcysteine decarboxylase complex that catalyses the third step of the coenzyme A (CoA) biosynthetic pathway.

Thanks.

**Comment by dosumis** [comment]
Fixed as requested.
