### ISSUE TITLE
query GO:1990945 - term name, difference from GO:1902441

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12445]
Something's up with GO:1990945. It looks like the term name should be 'protein localization to meiotic spindle pole body'. That would make it the same as GO:1902441, and indeed the two text definitions are identical in meaning, though not exact wording. If they get merged - which would seem sensible - I would keep GO:1902441 as the primary ID, because that term has been around longer and has a logical def.

[Term]
id: GO:1990945
name: protein location to meiotic spindle pole body
namespace: biological_process
def: "A process in which a protein is transported to, or maintained at the meiotic spindle pole body." [PMID:20833892]
is_a: GO:0034613 ! cellular protein localization
created_by: vw

[Term]
id: GO:1902441
name: protein localization to meiotic spindle pole body
namespace: biological_process
def: "A process in which a protein is transported to, or maintained in, a location within a meiotic spindle pole body." [GOC:TermGenie, PMID:22438582]
synonym: "protein localisation in meiotic spindle pole body" EXACT [GOC:TermGenie]
synonym: "protein localisation to meiotic spindle pole body" EXACT [GOC:TermGenie]
synonym: "protein localization in meiotic spindle pole body" EXACT [GOC:TermGenie]
is_a: GO:0022414 {is_inferred="true"} ! reproductive process
is_a: GO:0071988 {is_inferred="true"} ! protein localization to spindle pole body
intersection_of: GO:0008104 ! protein localization
intersection_of: has_target_end_location GO:0035974 ! meiotic spindle pole body
relationship: part_of GO:1990395 ! meiotic spindle pole body organization

**Comment by ValWood** [comment]
I don't know hwy I requested
protein localization to meiotic spindle pole body

I clearly meant
name: protein localization to meiotic spindle pole body

**Comment by ValWood** [comment]
The original annotation was to 
GO:0071990 maintenance of protein location in spindle pole body
so I think I wanted the meiotic version of this term, but I selected the wrong parent in term genie.


However it is strange because the  syntax changes from "to" to "in"
See http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071990#term=ancchart
I think "to" is better....

**Comment by ValWood** [comment]
I also got the term I needed  through term genie
ID: GO:1990954 Label: establishment of protein localization to meiotic spindle pole body
so only the fixes required

**Comment by paolaroncaglia** [comment]
Hi @mah11  and @ValWood ,

Let’s summarise the edits needed:
- Merge GO:1990945 protein location to meiotic spindle pole body into GO:1902441 protein localization to meiotic spindle pole body (GO:1990945 has no annotations so I could obsolete it too… but let’s not wait a week)
- Rename GO:0071990 maintenance of protein location in spindle pole body as maintenance of protein location to spindle pole body; keep maintenance of protein location in spindle pole body as exact synonym

@ValWood , sorry to be a nag, but please pay super extra caution when requesting terms via TG freeform, in case the term already exists under a different name. If you’d added an exact synonym ‘protein localization to meiotic spindle pole body’, TG would have prevented you from creating the term, pointing to the existing one (or at least warned you); but there’s little more we can do to instantiate automated checks - the system relies on you to make sure beforehand :-)

I’ll do the edits.

**Comment by mah11** [comment]
Hi Paola,

That summary sounds correct. Thanks!
m

**Comment by ValWood** [comment]
That would not have helped here ‘protein localization to meiotic spindle pole body’ was not the term I  wanted ;)
Will pay more attention.

**Comment by paolaroncaglia** [comment]
All done, cheers.
