### ISSUE TITLE
NTR: ribosylnicotinate kinase activity

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12441]
Background: Human enzymes NMRK1 and 2 both catalyze the phosphorylation of N-ribosylnicotinamide (CHEBI:15927) and also the phosphorylation of ribsylnicotinate (CHEBI:58527). The MF term GO:0050262 ribosylnicotinamide kinase activity "Catalysis of the reaction: N-ribosylnicotinamide + ATP = ADP + 2 H(+) + nicotinamide mononucleotide." covers the first reaction, but David H suggests that N-ribosylnicotinamide (CHEBI:15927) is not a type of ribsylnicotinate (CHEBI:58527), or vice versa, so I can't stretch GO:0050262 to cover both reactions.

Request: GO:xxxxxxx ribosylnicotinate kinase activity "Catalysis of the reaction: N-ribosylnicotinate + ATP = ADP + 2 H(+) + nicotinate mononucleotide." Same parentage as GO:0050262.

Thanks.
Peter

**Comment by ukemi** [comment]
Hi Peter,

Here is the term:

 [Term]
+id: GO:0061769
+name: ribosylnicotinate kinase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: N-ribosylnicotinate + ATP = ADP + 2 H(+) + nicotinate mononucleotide." [GOC:dph]
+is_a: GO:0016301 ! kinase activity
+intersection_of: GO:0016301 ! kinase activity
+intersection_of: has_input CHEBI:58527 ! D-ribosylnicotinate
+created_by: dph
+creation_date: 2016-05-05T14:41:44Z
I also created the logical def for GO:0050262. If you have a literature ref, let me know and I will add it.

-D

**Comment by deustp01** [comment]
Literature reference for the two enzymes and the two activities of each: PMID 17914902

**Comment by ukemi** [comment]
Added.
