### ISSUE TITLE
NTR: (positive/negative) regulation of connective tissue replacement involved in wound healing

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12442]
Dear Editors,

I would like to request new terms (Re: PMID:25590961, Figure 4C):

- regulation of connective tissue replacement involved in wound healing;

- positive regulation of connective tissue replacement involved in wound healing;

- negative regulation of connective tissue replacement involved in wound healing.

These terms would become children of the 'regulation of wound healing' family of terms and parents to the 'regulation of connective tissue replacement involved in inflammatory response wound healing' family of terms (no inflammation was evaluated in the annotated paper, hence the NTR).

The intended annotation:
Gata4 - negative regulation of connective tissue replacement involved in wound healing - part_of response to ischemia

Thank you,
Barbara

GOC:BHF, GOC:BHF_miRNA and GOC:bc

@rachhuntley 
@RLovering

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub (and @rachhuntley and @RLovering ), 

In your request, you quote an existing term that would become child of your requested term:
‘regulation of connective tissue replacement involved in inflammatory response wound healing’.
Looking at the detailed structure of ‘connective tissue replacement involved in inflammatory response wound healing’, i.e.

[Term]
id: GO:0002248
name: connective tissue replacement involved in inflammatory response wound healing
namespace: biological_process
def: "The series of events leading to growth of connective tissue when loss of tissues that are incapable of regeneration occurs, or when fibrinous exudate cannot be adequately cleared that contribute to an inflammatory response." [GOC:jal, ISBN:0721601871]
synonym: "connective tissue replacement during inflammatory response" RELATED [GOC:dph]
synonym: "fibrosis during inflammatory response" NARROW [ISBN:0721601871]
is_a: GO:0048771 ! tissue remodeling
*relationship: part_of GO:0002246 ! wound healing involved in inflammatory response*

Note that 
GO:0002246 ! wound healing involved in inflammatory response 
already contains a part_of (it’s equal to ‘wound healing’ part_of ‘inflammatory response’)

Similarly, your requested terms, if created along the same lines, would contain 2 implicit part_of… This leads me to suspect that you’re trying to put too much information into your requested terms, and that a much better option for you would be to do a LEGO model. GO:0002248 was created 10 years ago (when there were no other ways of capturing such implications), and at the moment we don’t have resources to retrofit existing old terms that may have similar issues, but we certainly wouldn’t want to create more terms like that. 

I will leave this ticket open for a few days to give you time to comment if needed, then I’ll close this ticket.

Thanks!

**Comment by BarbaraCzub** [comment]
Hi Paola,

Thank you for your comments.

The point, which you noted (that GO:0002246 ! wound healing involved in inflammatory response is a part_of both 'wound healing' and 'inflammatory response'), is exactly the reason why we cannot use the existing term 'GO:0002248: connective tissue replacement involved in inflammatory response wound healing'.

Figure 4C in PMID:25590961 shows evidence of fibrosis (connective tissue replacement in wound healing), but no evidence of inflammation. 'Wound healing' (GO:0042060) on its own is defined as 'The series of events that restore integrity to a damaged tissue, following an injury.' However, this term does not specifically refer to the connective tissue, which is key to Figure 4C in this paper. 

Therefore, we requested the simpler term, '(positive/negative) regulation of connective tissue replacement in wound healing', which does not involve inflammation, i.e. conveys less information, and would allow for creating a more accurate annotation, based on the results shown in the figure. 

Or perhaps an even simpler new term '(positive/negative) regulation of connective tissue replacement' would be more appropriate? 

Thanks,
Barbara

@rachhuntley 
@RLovering

**Comment by BarbaraCzub** [comment]
Hi Paola,

We discussed this issue in our team meeting today and we concluded that the NTR should be for
'connective tissue replacement' only.

I will look forward to hearing from you with regard to creating this new GO term.

Thanks,
Barbara

@rachhuntley 
@RLovering

**Comment by paolaroncaglia** [comment]
Hi Barbara,

Thanks for your feedback. Here is your new term:

[Term]
id: GO:0097709
name: connective tissue replacement
namespace: biological_process
def: "The series of events leading to growth of connective tissue when loss of tissues that are incapable of regeneration occurs, or when fibrinous exudate cannot be adequately cleared." [GOC:bc, GOC:BHF, GOC:BHF_miRNA, PMID:25590961]
is_a: GO:0048771 ! tissue remodeling

Also, I moved 'connective tissue replacement involved in inflammatory response wound healing' under it.

**Comment by BarbaraCzub** [comment]
Hi Paola,

Thank you very much.

Kind Regards, 
Barbara
