### ISSUE TITLE
adjustment to def of "manchette"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#12447]
Hi,

I needed some process terms related to the manchette (requested via TG) and have a suggestion to revise the definition of the CC term:

adjusted def: A tubular array of microtubules that extends from the perinuclear ring surrounding the spermatid nucleus to the flagellar axoneme. The manchette may also contain F-actin filaments.
GOC:krc, PMID:22319670, PMID:26792866, PMID:24440897

Also, it would be helpful if we could add a synonym to this term:

GO:0042073 - intraciliary transport
add additional EXACT synonym: IFT

thanks,

-Karen

**Comment by paolaroncaglia** [comment]
Hi @krchristie , thanks, will do.
Just a quick note, we'd rather not make acronyms exact synonyms; we feel that related is a more appropriate scope, as for nearly every brief acronym there is more than one meaning depending on context... and that issue can even generate errors in the ontology.
Paola

**Comment by krchristie** [comment]
OK. Thanks for the explanation Paola. I'll try to remember that for future.

-Karen

**Comment by paolaroncaglia** [comment]
Of course, there may be plenty of such exact synonyms on the loose in GO, and we're not going to retrofit actively ;-)

**Comment by paolaroncaglia** [comment]
Hi again @krchristie ,

Should GO:0002177 'manchette' be part_of CL:0000018 'spermatid'? Is that always the case i.e. could you please confirm that it has never been observed elsewhere?

Thanks.

**Comment by krchristie** [comment]
My understanding is that it is a spermatid specific structure that occurs as part of the development of the spermatid into a sperm, and it disappears such that it is not present in the mature sperm. I am not aware that this occurs anywhere else. I think it would be fine to say part_of spermatid.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks, I'll add the link then when I get to doing these edits.

**Comment by paolaroncaglia** [comment]
Hi @ukemi,

May I please double-check something about the related process terms I just committed for @krchristie , i.e. manchette assembly and manchette disassembly. Karen had initially suggested that both terms should have the part_of parent ‘spermatid development’. This may sound contradictory, but based on the knowledge that Karen summarised “My understanding is that it is a spermatid specific structure that occurs as part of the development of the spermatid into a sperm, and it disappears such that it is not present in the mature sperm”, I’d agree with adding the same development link to both terms. Would you have any objections?
(Karen had to re-submit the terms so the link wasn’t included in the final version.)

**Comment by ukemi** [comment]
I guess this is ok since the spermatid essentially represents an immature sperm. These terms should really probably be 'sperm development' to fit with the way the rest of development is represented. According to the cell ontology the spermatid is the immature cell and the sperm is the mature cell.  We usually name development terms based on the mature structure.

**Comment by paolaroncaglia** [comment]
Argh. Thanks @ukemi. We don’t have ‘sperm development’ - I could create it, sounds like ‘spermatid development’ should be merged into it, but I’m concerned about the complexity of the structure below ‘spermatid development’. Would all the part-of children be fine under ‘sperm development’, including ‘spermatid nucleus differentiation’? The entire node has >500 experimental annotations…

**Comment by paolaroncaglia** [comment]
In the meantime, @krchristie ,
revised def of GO:0002177 manchette and added link to CL:0000018 spermatid
added synonym to GO:0042073 intraciliary transport
so only thing left to do for this ticket is evaluate adding links manchette assembly and manchette disassembly part_of spermatid development, or sperm development if that's what spermatid development will become...

**Comment by ukemi** [comment]
Hi Paola,

According tho the way development is set up in GO, sperm development and spermatid development represent the same thing because the spermatid is essentially an immature sperm. So both terms would be defined as the progression of a sperm cell from its immature state as a spermatid to its mature state. This is where the identity of things becomes critical. Even though the CL has both spermatid and sperm, from the definitions it sounds like they don't really change identity, but they are simply two stages in a developmental progression.

**Comment by krchristie** [comment]
Hi,

I think the terms "manchette assembly" and "manchette disassembly" could appropriately be put under "spermatid development" or "sperm development" since as David said both terms are part of the same developmental progression that manchette assembly and disassembly is part of. Whichever way you guys think is best to represent the development term works for me.

In these new terms and changes I've requested, I think the only place that matters whether sperm or spermatid is used is the "part_of" link for the CC term "manchette" must be to "spermatid" because it is no longer present in the mature "sperm.

thanks!

-Karen

**Comment by paolaroncaglia** [comment]
Thanks both. Done - linked manchette assembly/disassembly to spermatid development.
