### ISSUE TITLE
NTRs: (positive/negative) regulation of NFAT transcription factor activity

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12440]
Dear Editors,

I would like to request new terms:
- regulation of NFAT transcription factor activity
- positive regulation of NFAT transcription factor activity
- negative) regulation of NFAT transcription factor activity

Re: PMID:24117217, Figure 4.

These (positive regulation) terms would become children of: 
GO:0051091 positive regulation of sequence-specific DNA binding transcription factor activity

And siblings of e.g.
GO:0032793 positive regulation of CREB transcription factor activity
or
GO:0051092 positive regulation of NF-kappaB transcription factor activity

Thanks,
Barbara

GOC:BHF, GOC:BHF_miRNA and GOC:bc

@rachhuntley 
@RLovering

**Comment by ukemi** [comment]
Hi Barbra,

I think this would be much better represented with an annotation to the parent term and an annotation extension. I know that historically the other terms are in the ontology, but I don't think it is sustainable to enumerate all of the types of transcription factors as instantiated terms.

-D

**Comment by rachhuntley** [comment]
Hi all,

Sorry this was my fault. The paper didn't specify the NFAT that was being used, and when I looked in UniProt there were several. However, for rat there seems to be only one (at least in UniProt; D3ZGB1), so in this case we can capture this in an extension. 

If this were human though, we wouldn't be able to add a target in the extension, so we would only be able to get as specific as annotating to "positive regulation of sequence-specific DNA binding transcription factor activity" - it would be nice not to lose this specificity as Val says in the thread she referenced and be a bit more clever about it.

**Comment by ukemi** [comment]
Couldn't you use the PRO ID for the generic, NFAT protein  	PR:000003112?

**Comment by ValWood** [comment]
Wow, I didn't know PIR created IDs for protein families represented by different genes at multiple loci (aka a protein family ID). Thats going to be confusing...

**Comment by rachhuntley** [comment]
OK, that's a thought. I've never really used PR before but we do allow them in Protein2GO.

**Comment by dosumis** [comment]
Should be straighforward to add them to local_range as necessary.

**Comment by ukemi** [comment]
Adding @vanaukenk  to this since it seems to be morphing into more of an annotation discussion.
I am also adding @hdrabkin since he is our Protein Ontology guy.  We use PR: identifiers to indicate isoforms. I don't see why this one wouldn't be valid and it is available in Noctua and AmiGO2.

**Comment by ukemi** [comment]
Seems like this one can be covered through annotation. Closing.

**Comment by ukemi** [comment]
I am going to reopen this issue for discussion on the ontology call. This to me seems to be related to other issues that we have had in the past, in particular with respect to, protein family binding. I'm not sure my idea of using an extension will work in light of the discussion on the annotation call on Tuesday. I'd like to see what others think. Basically are we going to have terms like these in the ontology or are we going to capture this type of information in at the time of annotation?

**Comment by ukemi** [comment]
We discussed this on the group call this morning and decided that these types of protein family terms were inappropriate. So I am closing this again.

**Comment by BarbaraCzub** [comment]
Hi David, is there any documentation/guidelines that state that these types of terms are not appropriate, so that we can refer to it in the future and avoid requesting similar terms?

@ukemi 
@RLovering

**Comment by ValWood** [comment]
It would be useful if there was a proposal to merge any gene product specific terms into their parent term. It is confusing for curators and community curators as it is not clear that they should not request gene product specific terms, as so many already exist.

A plan could be implemented in stages
i) Identify gene product specific terms
ii) Merge any gene product specific terms with no annotation into parent
iii) Identify terms with EXP annotation and notify groups to change to extensions
iv) If any terms cannot be represented with extensions add a comment explaining why the term exists (this would alleviate any concerns where gene products cannot be represented unambiguously)
v) Long term try to resolve  iv) by either i) contact authors for info about specific gene product assayed, or ii) Request PRO: ID to represent gene product

**Comment by ukemi** [comment]
I think we are on the same page. It seems like many term requests we are getting lately have to do with gene products and specifically modified forms. I just added a bit to the agenda for the ontology call tomorrow to add to Paola's proposal about modified forms we can then discuss all this at the GOC meeting.

**Comment by ValWood** [comment]
@ukemi  added this too

**Comment by ukemi** [comment]
Thanks. I moved it down to the appropriate section after the modified protein discussion.
