### ISSUE TITLE
query link spindle organization is_a neg reg MT depolymerization

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12444]
Is the link GO:0007051 is_a GO:0007026 intended/desirable? I'm not 100% sure it fits nicely with the disassembly is_a organization pattern.

I gather this happened when spindle stabilization (GO:0043146) was merged in.

[Term]
id: GO:0007051
name: spindle organization
namespace: biological_process
alt_id: GO:0043146
def: "A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the spindle, the array of microtubules and associated molecules that forms between opposite poles of a eukaryotic cell during DNA segregation and serves to move the duplicated chromosomes apart." [GOC:go_curators, GOC:mah]
synonym: "spindle organisation" EXACT [GOC:curators]
synonym: "spindle organization and biogenesis" RELATED [GOC:mah]
synonym: "spindle stabilization" RELATED []
is_a: GO:0000226 ! microtubule cytoskeleton organization
is_a: GO:0007026 ! negative regulation of microtubule depolymerization
is_a: GO:0022402 ! cell cycle process
is_a: GO:0071822 {is_inferred="true"} ! protein complex subunit organization
intersection_of: GO:0016043 ! cellular component organization
intersection_of: results_in_organization_of GO:0005819 ! spindle

**Comment by ukemi** [comment]
I think you are right. I have removed the link to GO:0007026 ! negative regulation of microtubule depolymerization. Thanks Midori. I also removed the one between the generic regulation terms.

**Comment by mah11** [comment]
wow, that was quick! thanks.

(I noticed because it generated some odd inferred links in FYPO. Cool, innit?)

**Comment by ValWood** [comment]
very ;)
