### ISSUE TITLE
exit from meiosis/ meiotic exit

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12448]
GO:1990947
Name	exit from meiosis
Ontology	Biological Process
Definition	Any process involved in the progression from anaphase/telophase of meiosis II to G1 of mitosis.

1. add synonym "meiotic exit"

2. correct PMID from  PMID:212917197
to?
(this isn't a real ID)

3. ...G1 of mitosis doesn't make sense (should be G1 of mitotic cell cycle)

But......
4. I may have some refinements for this term. In yeast its
meiosis II -> sporulation -> G1 (we think)  
However, we aren't trying to represent the entire progression from meiosis II  to G1, but only the transition from  "meiosis II -> sporulation"

I' also not sure if meiotic exit has exactly the same meaning in higher eukaryotes. I was googling yesterday and came across
"Fertilisation occurs when two highly specialised cells (sperm and egg) unite, causing an 'awakening' of the egg, known as meiotic exit." I'm not sure exactly what this means.

So we need to establish  the meaning  of both the fungal and the  metazoan meiotic exit, then figure out if we need to broaden/refine the existing  term to cover both, or create new terms.

I am going to ask some yeast people, but it would be useful if anyone can pitch in with any helpful info.

**Comment by ValWood** [comment]
@antonialock

**Comment by ValWood** [comment]
I have been trying to track down the PMID as assuming its one of ours, but no success. It looks like term genie, can you confirm ticket submitter/date that might help me  track down the session (although currently it has no annotations so possibly not).

**Comment by Antonialock** [comment]
> Fertilisation occurs when two highly specialised cells (sperm and egg) unite, causing an 'awakening' of the egg

"awakening of the egg" sounds down-right dodgy. It's surely the formation of a zygote that allows the cell to exit meiosis and enter G1? 

Would it not be possible to broaden the term to mean exit from meiosis II into any other following state (including the dormant state of yeasts or the actively  growing state of metazoan zygotes)...maybe child terms are needed depending on the downstream pathway?

**Comment by ValWood** [comment]
Yeah that  would make sense, so it would be either sporulation, or whatever metazoans do (just cytokinesis?)

**Comment by mah11** [comment]
> I have been trying to track down the PMID 

Val, you've outdone yourself this time. I only tracked it down because you opened two FYPO tickets at the same time, and one has the correct PMID. It's 21389117.

**Comment by Antonialock** [comment]
Interestingly, following ovulation human eggs are halted at metaphase II until some sperm comes along, so they don't actually complete meiosis before fertilization?

However, for pombe it's also at the metaphase II /anaphase II transition that spore formation starts...so maybe it will still be possible to make a term that works for both types or organism

**Comment by mah11** [comment]
> eggs are halted at metaphase II 

that's a general vertebrate phenomenon

**Comment by ValWood** [comment]
Something like:
The transition  from anaphase/telophase of meiosis II  to process for the formation of haploid gametes (sporulation or gamete generation).  Occurs via the negative regulation of a meiotic CDK by the degradation of cyclin. 
PMID: 11493649

The "exit" stages are not really like the other transitions, for example the metaphase/ anaphase transition where the events are clearer. My  knowledge about these   is sketchy but the mitotic equivalent seems to be to do with the switching off and dismantling of things which were required for the  anaphase/telophase.

**Comment by ValWood** [comment]
> I only tracked it down because you opened two FYPO tickets at the same time, and one has the correct PMID. It's 21389117.

Oh my god it isn't even remotely similar!

> However, for pombe it's also at the metaphase II /anaphase II transition that spore formation starts...so maybe it will still be possible to make a term that works for both types or organism

Does it? I thought spore formation began  after chromosome segregation

**Comment by ukemi** [comment]
The term seems a bit weird to me. I would think that no matter what, the arrest and exit are there to actually form the full-fledged gamete, not to enter G1. That really won't happen until after the sperm and egg pronucleus unite to form a zygote. So I think that Antonia is correct, the core process is the same even though sometimes female germ cells sit around in meiotic arrest for a long time. I think that is where the idea of 'awakening' come in.

**Comment by ValWood** [comment]
yep agreed...

**Comment by ukemi** [comment]
OK. I will tweak the definition to say creation of haploid end products of meiosis.

**Comment by mah11** [comment]
"Haploid" is too specific to apply to all species that do meiosis - there are a fair few plants, and even a few animals, that normally have greater than haploid/diploid ploidy. For example, common wheat cultivars are mostly hexaploid.

So how about "creation of end products of meiosis, in which ploidy is reduced by half"?

**Comment by ukemi** [comment]
Thanks Midori!

 id: GO:1990947
 name: exit from meiosis
 namespace: biological_process
-def: "Any process involved in the progression from anaphase/telophase of meiosis II to G1 of mitosis." [PMID:212917197]
+def: "Any process involved in the progression from anaphase/telophase of meiosis II to the creation of end products of meiosis, in which ploidy is reduced by half." [PMID:21389117]
+synonym: "meiotic exit" EXACT [GOC:dph]
 is_a: GO:0044771 ! meiotic cell cycle phase transition
 created_by: vw
 creation_date: 2016-04-21T14:14:15Z
