### ISSUE TITLE
GO:0016226 & GO:0006790 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12450]
Should GO:0016226 iron-sulfur cluster assembly be related to GO:0006790 sulfur compound metabolic process ?

Cheers

**Comment by tberardini** [comment]
@deustp01 : any thoughts on whether incorporation of sulfur into a metallo-sulfur cluster qualifies as sulfur metabolism?  I'm leaning towards 'no.'  Thanks.

**Comment by Antonialock** [comment]
the sulfur is derived from cysteine (this seems to be conserved across different organisms)

**Comment by deustp01** [comment]
Piling on here, the abstract of PMID:15952888 says, "Formation of intracellular [Fe-S] clusters does not occur spontaneously but requires a complex biosynthetic machinery. Three different types of [Fe-S] cluster biosynthetic systems have been discovered, and all of them are mechanistically unified by the requirement for a cysteine desulfurase and the participation of an [Fe-S] cluster scaffolding protein." And cysteine desulfurase activity is an aspect of cysteine metabolism and ChEBI:17561 L-cysteine is-a CHEBI:33261 - organosulfur compound

**Comment by tberardini** [comment]
Thanks, both of you!  I am now more educated on this process and will make a link between the two terms.

**Comment by tberardini** [comment]
+is_a: GO:0006790 ! sulfur compound metabolic process
