### ISSUE TITLE
OTR: typo in definition of 60988 lipid tube assembly

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#12459]
Gene Ontology Term: lipid tube assembly
GO:0060988
Aspect: Biological Process

current definition: The aggregation, arrangement and bonding together of a set of macromolecules to form a macromolecular complex that contains a tube of lipid surrounded by a protein coat involved in membrane shaping of vesicle membranes as the fuse or undergo fission.

typo: near the end of the definition, 'as the fuse' should be 'as they fuse'.

**Comment by ValWood** [comment]
see also,
https://github.com/geneontology/go-ontology/issues/12387
I opened this one following a discussion in another ticket highlighting some problems with the current organization.
I'll try to find the original ticket.

**Comment by ValWood** [comment]
ignore. I thought it was a new term request. It is related though...

**Comment by dosumis** [comment]
Ta.  Fixed.
