### ISSUE TITLE
small def update GO:0007062 sister chromatid cohesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12457]
GO:0007062 sister chromatid cohesion
currently
The cell cycle process in which the sister chromatids of a replicated chromosome are associated with each other.

change to
The cell cycle process in which the sister chromatids of a replicated chromosome are tethered (or connected?) to each other.

synonym "cohesin-mediated DNA tethering"

**Comment by dosumis** [comment]
Done.

Added this as EXACT:
synonym "cohesin-mediated DNA tethering"

is this correct?

**Comment by ValWood** [comment]
yep, thanks.
