### ISSUE TITLE
NTR: binding to host receptor

### ISSUE THREAD

**Issue by janelomax** [geneontology/go-ontology#12456]
Hi - I need a new term:

'binding to host receptor'

There doesn't seem to be anywhere obvious to put it (shoddy workmanship) so you will probably need to add a few new terms e.g.:

binding to other organism protein
---[i] binding to host protein
------[i] binding to host receptor
---[i] binding to symbiont protein

Where the definitions would be 'interacting selectively with a host/symbiont molecule...' 

Could give has_parts to 'receptor binding', 'protein binding'.

It's actually for binding to human IL10R but I'll add that bit as the extension.

thanks!

Jane

**Comment by dosumis** [comment]
The genus implied by the names ('protein binding, 'receptor binding') and the def pattern ("nteracting selectively with a") suggest an MF term, but the host/symbiont thing suggests the multi-org branch of BP.  

Could these perhaps be recast using the involved in pattern?  

Maybe: 

receptor binding involved in interaction with host?

**Comment by janelomax** [comment]
I'm sure that's fine, although I'm not sure there's anyone at WormBase to make the annotation now!

**Comment by janelomax** [comment]
In fact, don't worry about it you can close this.
