### ISSUE TITLE
Taxon Constraint for His-Purkinje system in fish

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#12451]
Request review for taxon constraint for HIs-Purkinje GO terms
GO:0060933 
GO:0060934 
GO:0060933 
GO:0003168 
GO:0086054
GO:0086055
GO:0086028
GO:0086073
GO:0086078
never_in_taxon  Actinopterygii  7898, Coelacanthiformes  7894, Dipnoi  7878

PMID: 12626327  PMID: 21234997

Thank you
GOC:MR

**Comment by tberardini** [comment]
You want to add these constraints, correct?

**Comment by michaelerice** [comment]
?Yes Tanya,


Thank you


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by tberardini** [comment]
Your list:

- [ ] GO:0060933, His-Purkinje system cell development
- [ ] GO:0060934, His-Purkinje system cell fate commitment
- [ ] GO:0060932, His-Purkinje system cell differentiation
- [ ] GO:0003168, Purkinje myocyte differentiation
- [ ] GO:0086054, bundle of His cell to Purkinje myocyte communication by electrical coupling
- [ ] GO:0086055, Purkinje myocyte to ventricular cardiac muscle cell communication by electrical coupling
- [ ] GO:0086028, bundle of His cell to Purkinje myocyte signaling
- [ ] GO:0086073, bundle of His cell-Purkinje myocyte adhesion involved in cell communication
- [ ] GO:0086078, gap junction channel activity involved in bundle of His cell-Purkinje myocyte electrical coupling

----------
 What about GO:0003164, His-Purkinje system development ?  There are 34 terms that contain the word 'Purkinje', 20 that contain 'bundle of His'.   Do you mean to add the taxon restrictions to all of these (some will inherit the restriction by parentage) or just the specific subset that you put in your original request?

**Comment by michaelerice** [comment]
Tanya,


all of the terms containing His and Purkinje should be covered by the restriction. sorry, when I saw how many there are I did not finish the list thinking it would be covered by the review process. Thanks for working on this.


Mike


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by tberardini** [comment]
Hi Mike - With the giant number of open Github tickets and the relatively small amount of ontology editors' time, the best chance for getting things done quickly is to provide as much detail in the request as possible.  :)    Thanks for the clarification.

**Comment by michaelerice** [comment]
?

ok, thanks


sorry for the incompleteness.

________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________

**Comment by tberardini** [comment]
Looked into this issue a little further:

1. We need to import Coelacanthiformes 7894, Dipnoi 7878 into taxa used for GO. 
2. It's probably cleaner to place the restriction on the UBERON terms instead and have the related GO terms inherit those taxon restrictions.

@michaelerice: Can you figure out which terms in UBERON are the most appropriate to restrict to the taxa that you requested?

Here's a search I did for His-Purkinje using AmiGO

http://amigo.geneontology.org/amigo/search/ontology?q=his-purkinje&fq=source:%22uberon%22&sfq=document_category:%22ontology_class%22

I was thinking this one:

http://amigo.geneontology.org/amigo/term/UBERON:0004146

@cmungall - you might be interested in this ticket

blocked on #12223

**Comment by cmungall** [comment]
I am very interested

We have grouped the teleost (and thus Actinopterygii) distal conduction system in with His-Purkinje system

The evidence may have been weak. E.g. ZFA uses "His-Purkinji network" as an exact syn. This was an early merge in uberon

What is the relationship between these structures? Haven't had time to read the references.

Summoning homology and comparative fish anatomy people: @ANiknejad @mellybelly @ybradford @cerivs

**Comment by cmungall** [comment]
Ah OK, so the original ZFA entry was a mistake, it has been obsoleted:

```
[Term]
id: ZFA:0005071
name: distal conduction system
namespace: zebrafish_anatomy
is_obsolete: true
consider: ZFA:0005059  ! trabecular layer
comment: Appears to be mammalian due to exact synonym His-Perkinje system, which doesn't have an exact analog in fish (or frogs). PMID:22984480 PLoS One. 2012;7(9):e44231.
synonym: "HPS" EXACT []
synonym: "His-Purkinje system" EXACT []
synonym: "His-Purkinji network" EXACT []
xref: TAO:0005071
```

From a skim of the refs it seems that lower vertebrates have a functional analog but is histologically different; the functional analog is the [trabecular layer](http://purl.obolibrary.org/obo/UBERON_0036015)

**Comment by cmungall** [comment]
OK, I think the representation of the analogous tissue in uberon has a lot of gaps I'd like to fill, but we should take that over to the uberon tracker

For now I will add the required TC, and we'll call this ticket closed

btw, I am going be bold and rewrite the TC as only-in tetrapoda (the 3 negative constraints as originally stated leaves open the possibility of the HPS being in Chondrichthyes, or even in cyclostomes, but this seems biologically unlikely based on the 3 papers here)
