### ISSUE TITLE
Embedded tab in definition of GO:0102585

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#12452]
There's a tab character in the middle of the definition of this term which shouldn't be there - can you excise it, please?

"cyanidin 3-O-[2''	-O-(xylosyl)-6'" is the relevant bit.

[Term]
id: GO:0102585
name: cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-glucoside malonyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-glucoside + malonyl-CoA + H+ <=> cyanidin 3-O-[2''	-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-malonylglucoside + coenzyme A." [EC:2.3.1-]
xref: MetaCyc:RXN-15331
is_a: GO:0016747 ! transferase activity, transferring acyl groups other than amino-acyl groups

**Comment by mcourtot** [comment]
Committed revision 33354.
