### ISSUE TITLE
NTR: vascular smooth muscle cell differentiation involved in phenotypic switching

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12455]
Is it possible to have the new term "vascular smooth muscle cell differentiation involved in phenotypic switching" as a child of  GO:0090679 cell differentiation involved in phenotypic switching?
(It would complement the term GO:1990936 vascular smooth muscle cell **de**differentiation). 

Possible def: A cell differentiation process that is a part of a reversible switch of a vascular smooth muscle cell (a non-striated, elongated, spindle-shaped cell found lining the blood vessels) from de-differentiated state to a differentiated state, at a frequency above the expected frequency for somatic mutations. 

I don't think it should have as parent "vascular smooth muscle cell differentiation" as the new term would be part of "reversible differentiation" which I'm not positive is the same as de novo differentiation. (see discussion of related terms here https://github.com/geneontology/go-ontology/issues/12354).

For annotation of PMID:25089138

If created please add the following GOC references;
GOC:rph
GOC:BHF
GOC:BHF_miRNA

Thanks.

**Comment by dosumis** [comment]
We have 'vascular smooth muscle cell differentiation' and 'phenotypic switching'.  The new term can be added by combining these via the BP-BP involved in template.   You should be able to add the new def and xref during this process.  Please let me know if any problems.
Cheers,
David
