### ISSUE TITLE
NTR: negative regulation by symbiont of host receptor binding

### ISSUE THREAD

**Issue by janelomax** [geneontology/go-ontology#12458]
New term:

'negative regulation by symbiont of host receptor binding'

as is_a:

negative regulation by symbiont of host molecular function ; GO:0052056

I can add an extension to the end of this specifying the receptor being regulated, right?

**Comment by pgaudet** [comment]
This request is not clear. The symbiont would regulate the receptor binding to what ? 
Not enough information, no reference. Closing the ticket.
