### ISSUE TITLE
NTR: prokaryotic flagellum

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12453]
@krchristie , @JohnvanDam,

Background: GO:0019861 ‘flagellum’ was obsoleted 3 years ago, as a first step in the effort to better represent ciliary components in GO. Obsoletion comment for reference: “This term was made obsolete because it was an unnecessary grouping term. Eukaryotic flagella were deemed to be equivalent to cilia and merged, so the only remaining child to this term was 'bacterial-type flagellum ; GO:0009288’.”

InterPro suggests to create a grouping term for ‘prokaryotic flagellum’ to group the existing 'bacterial-type flagellum' and 'archaeal-type flagellum’. This stems from their work to update a metagenomics GO slim. I’m copying below relevant bits of correspondence between Alex Mitchell and myself, and further below my suggestions for the new terms. Toby, John, Karen, please let me know if you disagree. Thanks!

[Alex] Quick question on reinstating obsolete GO terms... We had ‘flagellum’ (GO:0019861) in the old slim. Looking at the GONUTS
page, this was made obsolete since it was felt that eukaryotic flagella were covered by the term ‘cilia’. Fair enough, but there
now exists in the GO ‘bacterial flagellum’ and ‘archaeal flagellum. Would flagellum not be considered a good ‘parent’ in the
GO hierarchy for these terms?

[Paola] Yes, ‘flagellum’ (GO:0019861) was obsoleted 3 years ago by Jane, and since then I've been working with cilia researchers to better represent ciliary components in GO. I'm afraid I'd be against reinstating 'flagellum' as such because it is dangerously ambiguous - part of the community uses 'flagellum' to indicate eukaryotic cilium in some contexts e.g. sperm flagellum and this is accepted use. (We have definition comments on most eukaryotic cilia/flagellum terms to note this. E.g. for GO:0036126 'sperm flagellum' the comment reads "Note that cilia and eukaryotic flagella are deemed to be equivalent. In this case community usage is always 'flagellum', hence the primary term name, but the cilium parentage is deliberate.".)
If you feel that it would be useful for InterPro-GO mappings [or GO slims] to have a grouping term for 'bacterial-type flagellum' and 'archaeal-type flagellum', I could create 'prokaryotic flagellum' or similar and mark it so it's not used for direct manual annotations. (Because I presume that curators annotating experiments would know if it's Archaea or Bacteria. Not as easy with metagenomic samples I guess.) In GO we usually try to stay away from indicating species in term names, but this is much broader and would probably be acceptable

[A] That would probably be useful for us. I had a look at the InterPro entries that are annotated with 'bacterial flagellum' and they are
by and large bacterial-specific. It may be that the bacterial and archaeal flagellar proteins are so different that InterPro’s entries don’t cover both type of protein. Nevertheless, it could be a useful fall back annotation option for us: we have some entries that match a bunch of characterised archaeal flagellar proteins and 2 uncharacterised bacterial TrEMBL entries from WGS sequencing experiments. 
Usually this kind of thing gives curators headaches (do they assign the term or not?). A ‘prokaryotic flagellum’ term would allow us to
be less specific and therefore more confident in our annotation.

Proposed new term:

GO:NEW prokaryotic flagellum
is_a cell projection
is_a non-membrane-bounded organelle
only in taxon Prokaryota
def: “A non-membrane-bounded organelle found in prokaryotes. It consist of filaments extending outside the cell, and it rotates to propel the cell. It differs between Archaea and Bacteria in that it lacks a central channel in the former.”
def. comment: Note that this term was added as a grouping class for mapping purposes, and is in the subset of terms that should not be used for direct gene product annotation. Instead, please select a child term. Direct annotations to this term may be amended during annotation QC.
dbxref: GOC:pr
subset: gocheck_do_not_manually_annotate
subset: goslim_metagenomics

This would become parent of 'bacterial-type flagellum' and 'archaeal-type flagellum’.

**Comment by JohnvanDam** [comment]
I can see how this would be a useful grouping, especially for metagenomics.

**Comment by paolaroncaglia** [comment]
Thanks @JohnvanDam .
Toby says this sounds like a good idea to him too, and adds that he’d just make it clearer in the term that the flagella are not considered to be homologous, see http://evolutionwiki.org/wiki/Flagella. So the def could read instead
"A non-membrane-bounded organelle found in prokaryotes. It consist of filaments extending outside the cell, and it rotates to propel the cell. Although the prokaryotic flagellum looks similar in Archaea and Bacteria, it is in fact not homologous between the two (see http://evolutionwiki.org/wiki/Flagella for a list of differences)."
I will implement next week.

**Comment by paolaroncaglia** [comment]
P.S. I'll add the wiki link as a dbxref.

**Comment by krchristie** [comment]
I actually have a hard time seeing how a grouping term for Bacterial flagella and Archaeal flagella could be useful for any level of annotation considering that they are not evolutionarily or structurally related. I had come across the same info in the wiki page cited above, which is why we created a new term specifically for Archaeal flagella.

Alex suggested this scenario:
"Nevertheless, it could be a useful fall back annotation option for us: we have some entries that match a bunch of characterised archaeal flagellar proteins and 2 uncharacterised bacterial TrEMBL entries from WGS sequencing experiments. Usually this kind of thing gives curators headaches (do they assign the term or not?). A ‘prokaryotic flagellum’ term would allow us to be less specific and therefore more confident in our annotation."

However, if there are bacterial and archaeal proteins in the same InterPro grouping, it seems unlikely that they would be flagellar in both the bacterial and archaeal domains of life. 

So, for my 2p, I'm against this grouping term.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks @krchristie .
I know that Alex is monitoring this ticket, so I'd ask him to comment please.
A good weekend to you all,
Paola

**Comment by almitchell** [comment]
I am not really sufficiently knowledgable on the origins of bacterial and archaeal flagella. If they are not evolutionarily or structurally related, then we are unlikely to have an InterPro entry that really matches both (and should consider such matches to be false positive). In which case, perhaps it is more sensible not to group the terms.
- Alex

**Comment by krchristie** [comment]
The homology might be real, as (quoted from wiki linked above) "some components of archaeal flagella share sequence similarity with Type IV secretion systems, also known as Type IV pili.". However, the usage in flagella would be limited to the archaeal members of such a group.

-Karen

**Comment by almitchell** [comment]
So in those cases, we could not want to assign a GO term automatically (since the function would be different depending on taxonomic source, and we dont have that info for metagenomics), meaning a more general term probably wouldnt help.

-Alex

**Comment by paolaroncaglia** [comment]
Great, thanks all for your feedback. I will not create the term then, as it could potentially be mis-used. 
Closing now.
