### ISSUE TITLE
GO:1990814 DNA/DNA annealing activity vs. GO:0036310 annealing helicase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12465]
A 
GO:1990814 DNA/DNA annealing activity
A nucleic acid binding activity that brings together complementary sequences of ssDNA so that they pair by hydrogen bonds to form a double-stranded DNA.
(only PomBase has used in experimental annotation)

B 
GO:0036310 annealing helicase activity
Catalysis of the ATP-dependent rewinding of single-stranded DNA (ssDNA) to reform base pairs between strands. Often acts on ssDNA bubbles bound by replication protein A (RPA). 

1. B (Annealing helicase) is a descendant of DNA strand renaturation
2. A.  GO:1990814 DNA/DNA annealing activity SHOULD also be a descendant of DNA strand renaturation
3. I can't see a difference between A and B *except * that 
B is defined as a helicase and A isn't, However, isn't all annealing activity helicases?
4.  The  term name for B says that it is a helicase, but this is not reflected in the definition, or the parentage.....

Suggest a merge and rehash of def and parents....

**Comment by ValWood** [comment]
Alos add synonyms
DNA annealing...
GO:0000733 DNA strand renaturation
GO:0061306 DNA strand renaturation involved in double-strand break repair

(wouldn't that be a better primary name with a definitions tweak? current term sounds more like the assay than the BP)

**Comment by ValWood** [comment]
Also isn't renaturation a geometric change rather than metabolic process?  as is only base-pairing?

**Comment by ValWood** [comment]
Whatever the outcome, we need an ATP-dependent and ATP-independent version of the DNA/DNA annealing activity term

RecA, for example is ATP-dependent, condensin is ATP-independent

**Comment by ukemi** [comment]
B (Annealing helicase) is a descendant of DNA strand renaturation
    A. GO:1990814 DNA/DNA annealing activity SHOULD also be a descendant of DNA strand renaturation

Not necessarily. What if it is strand invasion? Then is is not renaturation. It is de novo annealing.

    I can't see a difference between A and B *except * that B is defined as a helicase and A isn't, However, isn't all annealing activity helicases?

I don't think recombinases are helicases are they?

    The term name for B says that it is a helicase, but this is not reflected in the definition, or the parentage.....

A helicase is defined as driving the unwinding of DNA, so despite the name, this does the opposite.

So you want DNA/DNA annealing ATPase activity?

**Comment by ValWood** [comment]
>Not necessarily. What if it is strand invasion? Then is is not renaturation. It is de novo annealing.

OK good point!

> OK, that's the sibling, it makes sense now.

So GO:0000150 should be a descendant of GO:0097617?

![parent](https://cloud.githubusercontent.com/assets/7359272/18408642/fb94a232-772c-11e6-9b7e-e25c41d5602f.jpg)

**Comment by ValWood** [comment]
The annealing helicase should probably have some existing terms as descendants too... and some of those kids will also be under DNA/DNA annealing....

**Comment by ukemi** [comment]
I'm not sure they should be descendants. Maybe they should have has_part relations. I think they do more than just strand invasion. Let me know if you know mechanisms of the specific enzymes. Otherwise I think we can close this and add them as we come across them.

**Comment by ValWood** [comment]
The rad51 recombinase doe shave other MF's  but recombinase activity is defined as

Catalysis of the identification and base-pairing of homologous sequences between single-stranded DNA and double-stranded DNA.
(although it has the comment "Note that this term represents activities that do not break or form phosphodiester bonds," which seems that it should be part of the definition?

So for example pombe rad51 is annotated to both "recombinase" and "protein loading ATPase"

**Comment by ValWood** [comment]
Hmm, is recombinase is a collection of activities/gene product name?

**Comment by ukemi** [comment]
Val,
What would you like for me to do with this? 
-D

**Comment by ValWood** [comment]
I think you can close it. I think there are some problems in the recombination part of the GO graph, but I don't understand recombination well enough to know  exactly what they are. Thye will probably become resolved as a  LEGO model is built (there is clearly enough functional data to model this process).
val

**Comment by ukemi** [comment]
OK. I am making a list of areas of the ontology that need refinement. I will add it to that. So far in this area, I've got both repair and recombination.
