### ISSUE TITLE
fibroblast chemotaxis

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12464]
I tried to request "fibroblast chemotaxis" in TermGenie, but got this result: "Could not commit, a term with the same label already exists: GO:TEMP-1 fibroblast chemotaxis.  It looks like the term is waiting for some decision."

**Comment by ValWood** [comment]
see also, https://github.com/geneontology/go-ontology/issues/12463

**Comment by paolaroncaglia** [comment]
Hi @slaulederkind ,

Thanks for reporting this. Yes, there's a bug in TermGenie. I opened a ticket for @hdietze in the TG tracker: https://github.com/geneontology/termgenie/issues/92

I'll close this, thanks.

**Comment by paolaroncaglia** [comment]
(Sorry, too quick.) 
@slaulederkind ,
I asked Heiko to alert curators as soon as the bug is fixed. Could you wait until then to resubmit your term please, or is it urgent?

**Comment by ukemi** [comment]
Added with fixed TG FF.
