### ISSUE TITLE
 metaphase/anaphase transition of mitotic cell cycle, regulation terms, revise defs

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12468]
metaphase/anaphase transition of mitotic cell cycle
The cell cycle process in which a cell progresses from metaphase to anaphase during mitosis, triggered by the activation of the anaphase promoting complex by Cdc20/Sleepy homolog which results in the degradation of Securin. Source: PMID:10465783, GOC:mtg_cell_cycle

Could this full def appear in the regulation terms (which are often used inappropriately for  chromosome segregation issues which  occur for other reasons, before the  spindle checkpoint is satisfied and the APC is activated).

**Comment by ukemi** [comment]
done
