### ISSUE TITLE
Query  term "DNA protection" what does it mean? (matrix intersection issue)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12461]
This term is defined
"Any process in which DNA is protected from damage by, for example, oxidative stress"

What does 'protection' mean exactly. To me 'protection implies that the damage does not happen?
But this term 
is_a DNA metabolic process. which implies DNA is repaired?

so is the term referring to an event  which occurs pre or post damage?

It has been used with experimental annotation for the following gene products:

wormbase hda-3 and hda-2 (histone deacetylase?)
Flybase  Stwl  (3 annotations)
SGD TSA1 (thioredoxin)
Human CBS cystathionine beta-synthase activity
UniProt NUDT1
MTBBASE  lsr1,hup,GroEL
CACAO  dps1,DR_0282
GeneDB Tps1 (thioredoxin)

It sounds slight;y 'phonotype-y' but its very vague, I'm not really sure what it means. It clearly hasn't been used in any way consistently.

**Comment by paolaroncaglia** [comment]
'DNA protection' probably refers to an assay rather than a real process. We obsoleted 'neuroprotection' for the same reason. Note there are a few more terms where the label contains 'protection', some sound legit but others may need looking at (e.g. 'anoxia protection').

**Comment by ukemi** [comment]
Hi Val,

If you have a look at some of the pubs associated with the annotations, they fit the term definition. According to the abstract, Dps1 binds to DNA and protects it from hydroxyl radical damage. The TSA1 paper also implies that the DNA is protected from oxidation. I think the term is ok, but as you point out, I don't think it should be a child of DNA metabolic process because these gene products should prevent the damage. Instead it should maybe be a child of 'cellular response to DNA damage stimulus'. What do you think?

**Comment by vanaukenk** [comment]
Hi @ValWood and @ukemi,

I've had a look at our original annotations for the two HDACs, hda-2 and hda-3, as well as one follow-up paper for those two genes:

Original reference: http://www.ncbi.nlm.nih.gov/pubmed/12600937
Newer paper: http://www.ncbi.nlm.nih.gov/pubmed/20463888

Looking at those two papers, I think the more appropriate annotation for the C. elegans HDACs is GO:0006974, 'cellular response to DNA damage stimulus'.

The exact mechanism for how hda-2 and hda-3 affect DNA damage response is not worked out, but I think this term is a better fit than 'DNA protection'.

As for the 'DNA protection' term itself, I do wonder if it really provides any more information than an annotation to 'cellular response to DNA damage stimulus'?

--Kimberly

**Comment by ValWood** [comment]
It seems in this case cellular response to DNA damage stimulus is better.

But as David mentioned, some appear to be pre-damage, so they really do appear to be 'protective'

It is well established that Dps proteins confer resistance to reactive
oxygen species. This is achieved by removal of Fe2 from the
cytoplasm and storing this metal in the oxidized form inside the
protein cage, thereby reducing Fenton chemistry (4)

so its a type of
GO:0098869 cellular oxidant detoxification (to prevnt DNA damage)

not DNA metabolism.
So 2  different types of things appear to be annotated to this term....

**Comment by ukemi** [comment]
I think we should remove the metabolism parents from the protection term. But is is a response to a stress? I guess if the response can be preemptive then that's ok. It's an evolutionary response. What do you think?

**Comment by ValWood** [comment]
Hmm,
Remove metabolism, yes

Re "response to"  this sounds incorrect to me. The definition of response to is clearly
 "......as a result of a stimulus. The process begins with detection of the stimulus and ends with a change in state or activity"

This is clearly different....it seems that a high level parent is required along the lines of 
"protection against toxicity"

but then it would be useful somehow to link the concepts of  "protection from toxicity" and
"cellular detoxification"

but then I guess the above  example 'protective' process could also be described as

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990461#term=ancchart
 GO:1990461 detoxification of iron ion

and maybe this is a more direct way to describe these processes than what is 'protected' downstream?

(thinking aloud)

**Comment by ukemi** [comment]
I am tempted to make it simple a response to stress. Presumably the reason why it evolved was to protect the DNA from stress and it doesn't do it until the stress exists. The seat belts in my car keep me safe in response to an accident even though they are always there. They are there because we know accidents happen. Buy it?

**Comment by ValWood** [comment]
OK, i think its wrong, but I have no idea what or how it should be described. I'll close it for now, can revisit if it causes problems later....
