### ISSUE TITLE
NTR: ASC-1 complex

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#12460]
Dear editors,
this paper PMID:12077347 describes a protein complex composed of 4 proteins in namely TRIP4, ASCC1, ASCC2 and ASCC3 and has been described by other publications since then (PubMed=26924529). Would it be possible to create a term for that complex?
Thanks,
Lionel

**Comment by ValWood** [comment]
Hi Lionel /Go editors

I'm interested in this  complex and the eventual process annotations because these 4 proteins are conserved in pombe and currently in our 'unknowns' list.

As this complex is clearly conserved  from human to yeast, can you keep the definition suitably broad (maybe the function, but not mention the regulated substrates).

Cheers

Val

**Comment by dosumis** [comment]
Hi Lionel,

Presumably name should be:
Activating Signal Cointegrator 1 Complex

Can you suggest a definition, referencing core biochemical/cell biological function?

Cheers,
David

(BTW - I may not get around to adding this until the week after next.  On holiday next week.)

**Comment by lbreuza** [comment]
Hi David,

I am not sure there are clear evidences for the function of the complex as a whole but the complex has been described in at least 3 papers in mammals. Maybe Val could point to other reports in pombe. Here is a definition you might want to improve:

A nuclear protein complex that may function in the regulation of transcription. In mammals it is composed of ASCC1, ASCC2, ASCC3 and TRIP4.

Hope it helps,
Thanks.
Lionel

**Comment by ValWood** [comment]
I agree, there isn't much known (these 4 proteins are in my 'unknown process list')....I have been looking at them occasionally as part of a 'function prediction' project as they clearly interact, and is complex appears to be conserved from pombe to human. They don't have any strong phenotypes and they have vague connections to all sorts of processes....Nothing strong enough to  annotate.

I think it is worth creating the complex even though we don't know the exact role (I know we don't usually). I'm sure there will be papers on this complex soon, and I'll revise the def.
I think Lionel's def will suffice as a placeholder.

**Comment by lbreuza** [comment]
Hi David,
any news about this term request I posted in May?
Thanks,
Lionel

**Comment by dosumis** [comment]
Hi @lbreuza,  On holiday right now.  Back Wed.  I'll put this on my list of urgent requests to complete this week.  Cheers,
David

**Comment by dosumis** [comment]
@ValWood: Can you let me know the yeast components?

**Comment by dosumis** [comment]
> the complex has been described in at least 3 papers in mammals. 

Do you have the other refs handy?  Do they cover > 1 species?

**Comment by lbreuza** [comment]
This is a job I finished in May and unfortunately do not remember much about the details. I had mentioned at least 2 papers in my initial request. As far as I remember, the complex was described in human and mouse.
Sorry.

**Comment by ValWood** [comment]
It is not yet studied in yeast but I'm 99% sure that its a conserved  complex as the subunits are conserved 1:1. I think its safe to assume that the complex is conserved across eukaryotes and has a  conserved role.
 I will use this term with ISO to the human orthologs, but we don't have any references.

**Comment by dosumis** [comment]
Might still be worth listing the yeast components.

**Comment by ValWood** [comment]
The pombe components would be
1.  human thyroid receptor interacting protein homolog, transcription coactivator (predicted)
2. human ASCC1 ortholog
3. CUE domain protein Cue3, human ASCC2 ortholog (predicted)
4. ATP-dependent RNA helicase Slh1, human ASCC3 ortholog (predicted)
(all are currently in out 'unknown' list http://www.pombase.org/status/priority-unstudied-genes, I would feel safe to ISO the complex, but not the biological processes.... human ASCC3 is a helicase so it is likely that the  real cellular role is somewhat obscured at present. I don't think its a problem to go with Lionel's original suggestion and we revise as more functional information becomes available.

Val

**Comment by dosumis** [comment]
How's this:

![image](https://cloud.githubusercontent.com/assets/112839/17737330/95708580-6484-11e6-8834-65ceb4c080b3.png)

**Comment by ValWood** [comment]
Sounds good, can be refined when we know more.

Val

**Comment by ValWood** [comment]
Do you have a GO ID, I can add my ISS's now...

**Comment by lbreuza** [comment]
Hi,
this sounds good. 2 minor suggestions:
TRIP4 is the official gene name therefore I would suggest to write TRIP4 (ASC1)

and acts transcriptional coactivator-> and acts AS A transcriptional coactivator 
Thanks,
Lionel

**Comment by dosumis** [comment]
Done.  ID: GO:0099053

**Comment by ValWood** [comment]
Hi Dav,

Activating Signal Cointegrator 1 Complex

->
Activating Signal Cointegrator 1 complex  (I used this case)

Val
