### ISSUE TITLE
pombe GO slim updates

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12467]
1. remove iron sulfur cluster assembly  GO:0016226
( is now is_a cofactor metabolic process which is already in slim)

2.  Add GO:1901135 - carbohydrate derivative metabolic process
(will capture some non slimmed GPs)

3. GO:0007346 - regulation of mitotic cell cycle 
replace by
GO:1901990 regulation of mitotic cell cycle transition 
(regulation of all other mitotic cell cycle processes are covered  by 'DNA replication, chromosome. segregation, cytokinesis etc).....less redundancy/overlap, smaller bins, no change in number of gene slimmed

4.  Delete GO:0007059 chromosome segregation
replace by GO:0000070 mitotic chromosome segregation 
(meiotic chromosome segregation is fully  covered by GO:0007126 meiotic nuclear division) ....less redundancy/overlap, smaller bins, no change in number of gene slimmed.

5. Delete GO:0007010	cytoskeleton organization
Add GO:0030036	actin cytoskeleton organization
Add GO:0000226	microtubule cytoskeleton organization
(Better biological grouping for PomBase users)

Thanks!

Val

**Comment by ukemi** [comment]
Val,

Is this on the right tracker?

-D

**Comment by ValWood** [comment]
I usually put it on this tracker and one of the editors does the changes (I don't know how to use obo edit!)

**Comment by ukemi** [comment]
OK. My bad. I didn't realize you wanted me to modify the slims.

I can teach you how to use obo-edit and protege.

**Comment by ukemi** [comment]
Edits done.

**Comment by ValWood** [comment]
Thank you! I don't really want to lean to use obo edit.... but I know people at PomBase who can ;)

**Comment by ukemi** [comment]
And very well I might add!

**Comment by ValWood** [comment]
Hi David,

Sorry to be a pain. 

Our current slim has
 GO:0098974	postsynaptic actin cytoskeleton organization
instead of GO:0030036 actin cytoskeleton organization

could you switch it?

Thanks

Val

**Comment by mcourtot** [comment]
Hi Val, I just removed GO:0098974 postsynaptic actin cytoskeleton organization from the pombe slim (GO:0030036 was already in).

**Comment by ValWood** [comment]
thanks!
