### ISSUE TITLE
revise def  mitotic cytokinesis checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12469]
This is the only checkpoint which does not have ancestry to the transition that it blocks. 

mitotic cytokinesis checkpoint
Definition	A mitotic cell cycle checkpoint that detects a defect in cytokinesis and negatively regulates mitosis in the following cell cycle.
Comment	These cells display defects in cytokinetic ring formation and fail to assemble a septum, but nevertheless enter a new cell cycle, go through one round of DNA replication, and then arrest in G2 of the following cell cycle.

Revise def to 
Definition	A mitotic cell cycle checkpoint that detects a defect in cytokinesis and negatively regulates G2/M transition  in the following cell cycle.

and add negative regulation of this transition as a parent.

Thanks

**Comment by mah11** [comment]
also delete the comment, which appears to have been mistakenly copied over from a FYPO term!

**Comment by ukemi** [comment]
Hi Val and Midori,

I did this:

id: GO:0044878
 name: mitotic cytokinesis checkpoint
 namespace: biological_process
-def: "A mitotic cell cycle checkpoint that detects a defect in cytokinesis and negatively regulates mitosis in the following cell cycle." [GOC:jl, GOC:mtg_cell_cycle]
-comment: These cells display defects in cytokinetic ring formation and fail to assemble a septum, but nevertheless enter a new cell cycle, go through one round of DNA replication, and then arrest in G2 of the following cell cycle.
+def: "A mitotic cell cycle checkpoint that detects a defect in cytokinesis and negatively regulates G2/M transition in the following cell cycle." [GOC:jl, GOC:mtg_cell_cycle]
 synonym: "cytokinesis after mitosis checkpoint" RELATED [GOC:dph, GOC:vw]
 synonym: "defective cytokinesis checkpoint" RELATED [GOC:dph, GOC:vw]
 is_a: GO:0007093 ! mitotic cell cycle checkpoint
+is_a: GO:0010972 ! negative regulation of G2/M transition of mitotic cell cycle
 created_by: janelomax
 creation_date: 2015-01-13T15:30:23Z

but this part of the graph still looks strange to me. Shouldn't this become a 'mitotic G2/M transition checkpoint'? 

Right now we have:
negative regulation of G2/M transition of mitotic cell cycle
% G2 cell size control checkpoint
% mitotic cytokinesis checkpoint
% mitotic DNA replication checkpoint
% mitotic G2/M transition checkpoint
      % G2 cell size control checkpoint
      % mitotic DNA replication checkpoint

The structure seems redundant.

**Comment by ukemi** [comment]
Sorry, the structure wasn't represented well in the last post:

negative regulation of G2/M transition of mitotic cell cycle
% G2 cell size control checkpoint
% mitotic cytokinesis checkpoint
% mitotic DNA replication checkpoint
% mitotic G2/M transition checkpoint
% %G2 cell size control checkpoint
% %mitotic DNA replication checkpoint

**Comment by ValWood** [comment]
I don't think this is a classical  'checkpoint'  pathway. The other checkpoints are a single pathway feeding int cdc2.

Here, a problem in cytokinesis.  causes multiple  problems in the next G2. The genes involved  sometimes come through the G2 checkpoint pathway, but it also appears to feed in to  other non-checkpoint pathways  upstream of the  central control system (the brakes are on and the accelerator is off!)

So I think it might be correct. 

I now plan to model all of the  G2/M control system (I postponed chromosome segregation!)
I started this week
https://github.com/pombase/curation/issues/1047
(Its more relevant to cell cycle work...)

Should I take this ticket....I can see how it fits into the model in https://github.com/pombase/curation/issues/1047  ticket...

**Comment by ukemi** [comment]
I think the ticket is done. My question was specifically about the G2 cell size checkpoint and the DNA replication checkpoint being both children and grandchildren of negative regulation of G2/M transition of mitotic cell cycle. I think they correctly fit under the checkpoint, right?

**Comment by ukemi** [comment]
I removed the terms under the grandparent. They are now just types of checkpoints.
