### ISSUE TITLE
Term genie free form issue

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12463]
trying to create

negative regulation of mitotic chromosome condensation
PMID:23219725

got
Could not commit, a term with the same label already exists: GO:TEMP-0 negative regulation of mitotic chromosome condensation

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
I reported the same issue last Friday, here's the link to the ticket in the TG tracker:
https://github.com/geneontology/termgenie/issues/92
Hopefully @hdietze will look into it soon :-)
In the meantime, I'll close this. Thanks.

**Comment by paolaroncaglia** [comment]
Sorry @ValWood , I may have been too fast. I asked Heiko to alert curators when he's fixed the TG freeform bug. Would it be ok for you to wait until then, to resubmit your term, or is it urgent?

**Comment by ValWood** [comment]
Yep..

**Comment by paolaroncaglia** [comment]
Assigning to @ukemi then :-} he's on duty this week. Thanks!

**Comment by hdietze** [comment]
@ukemi could you try using the free form, please?

**Comment by ukemi** [comment]
Heiko and Val,

The term Val wants above is available via a template. I tried Stan's and got this:

The requested label is equal to the term: GO:TEMP-1 'fibroblast chemotaxis'

-D

**Comment by ValWood** [comment]
I was using the main tg (not ff), should I try again?

**Comment by hdietze** [comment]
Yes please. I have deployed an updated version, which appears to be stable (and functional again).

**Comment by ukemi** [comment]
I just put Stan's fibroblast chemotaxis term in successfully.

**Comment by ValWood** [comment]
Yay, thanks Heiko, all good.
