### ISSUE TITLE
mesenchymal cell differentiation from epithelial cell

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12477]
Hi David

Given that signaling processes regulate cell development and the signaling molecules should not be annotated to cell development and cell morphogenesis processes directly we need a term to annotate signaling molecules for their involvement in differentiating a mesenchymal cell from a epithelial cell. 

The current definition for GO:0048762 mesenchymal cell differentiation is: The process in which a relatively unspecialized cell acquires specialized features of a mesenchymal cell. A mesenchymal cell is a loosely associated cell that is part of the connective tissue in an organism. Mesenchymal cells give rise to more mature connective tissue cell types. For EMT this doesn't seem right as the epithelial cell is not an unspecialised cell

I think it might be easier to revise the definition for GO:0048762 mesenchymal cell differentiation to 
The process in which a cell acquires specialized features of a mesenchymal cell. A mesenchymal cell is a loosely associated cell that is part of the connective tissue in an organism. Mesenchymal cells give rise to more mature connective tissue cell types.
Then for the ontology I suggest:
GO:0048762 mesenchymal cell differentiation
>is_a new child mesenchymal cell differentiation from epithelial cell
GO:0060485 mesenchyme development
>part_of new child mesenchymal cell differentiation from epithelial cell
Definition: 
The process in which an epithelial cell acquires specialized features of a mesenchymal cell. A mesenchymal cell is a loosely associated cell that is part of the connective tissue in an organism. 
And the new term would get the part_of child term
GO:0001837 epithelial to mesenchymal transition
DbxRefs: GOC:rl, GOC:BHF

Thanks

Ruth

**Comment by ukemi** [comment]
Hi Ruth,

In the case of cell differentiation, all that we mean by 'unspecialized' cell is a different cell type that doesn't have the specialized features of the differentiated cell. Being a different cell is important. The adjective 'unspecialized' doesn't require that the cell be a stem cell, for example. Since the case of the mesenchymal to epithelial transition and the epithelial to mesenchymal describe one cell type turning into the respective 'more specialized' cell type, then I think they describe the differentiation term that you are requesting and they should become children of  epithelial cell differentiation and mesenchymal cell differentiation respectively. We can add the strings you use above as synonyms. I think the changes in morphology etc are parts of the differentiation process, so we will have to tidy that up as well.

I am pinging @tberardini to see if she agrees.

-D

**Comment by tberardini** [comment]
Does a mesenchymal cell always develop from an epithelial one?  If so, then the definition of the existing 'mesenchymal cell differentiation' could be clarified to read like this:

The process in which **an epithelial cell** acquires specialized features of a mesenchymal cell. A mesenchymal cell is a loosely associated cell that is part of the connective tissue in an organism. Mesenchymal cells give rise to more mature connective tissue cell types. 

If mesenchymal cells don't always come from epithelial cells, then a child term ' mesenchymal cell differentiation from epithelial cell' makes sense.  The parent term definition tweaking depends on whether we consider an epithelial cell a 'relatively unspecialized' one or not.  If not, then Ruth's suggestion of dropping that phrasing is good.

My 2 cents.

**Comment by ukemi** [comment]
I don't think that epithelial cells always differentiate from mesenchymal cells, so I do think that we need a separate term. But based on how we defined differentiation I think that 'mesenchymal to epithelial transition' is equal to ' mesenchymal cell differentiation from epithelial cell'. It is just currently in the wrong place in the ontology.

**Comment by RLovering** [comment]
sounds right to me

**Comment by ukemi** [comment]
I think this will work. Let me know if you think it doesn't.

name:epithelial to mesenchymal transition
 def: "A transition where an epithelial cell loses apical/basolateral polarity, severs intercellular adhesive junctions, degrades basement membrane components and becomes a migratory mesenchymal cell." [GOC:dph, PMID:14701881]
 synonym: "EMT" EXACT []
 synonym: "epithelial-mesenchymal transition" EXACT []
-is_a: GO:0000904 ! cell morphogenesis involved in differentiation
+synonym: "mesenchymal cell differentiation from epithelial cell" EXACT [GOC:BHF, GOC:dph, GOC:rl]
+is_a: GO:0048762 ! mesenchymal cell differentiation
+intersection_of: GO:0030154 ! cell differentiation
+intersection_of: has_input CL:0000066 ! epithelial cell
+intersection_of: results_in_acquisition_of_features_of CL:0008019 ! mesenchymal cell
 relationship: has_input CL:0000066 ! epithelial cell
 relationship: part_of GO:0014031 ! mesenchymal cell development
 
@@ -386488,8 +386492,12 @@
 name: mesenchymal to epithelial transition
 namespace: biological_process
 def: "A transition where a mesenchymal cell establishes apical/basolateral polarity, forms intercellular adhesive junctions, synthesizes basement membrane components and becomes an epithelial cell." [GOC:ascb_2009, GOC:dph, GOC:tb]
+synonym: "epithelial cell differentiation from mesenchymal cell" EXACT [GOC:BHF, GOC:dph, GOC:rl]
 synonym: "mesenchymal-epithelial transition" EXACT [GOC:dph]
-is_a: GO:0003382 ! epithelial cell morphogenesis
+is_a: GO:0030855 ! epithelial cell differentiation
+intersection_of: GO:0030154 ! cell differentiation
+intersection_of: has_input CL:0008019 ! mesenchymal cell
+intersection_of: results_in_acquisition_of_features_of CL:0000066 ! epithelial cell
 relationship: has_input CL:0008019 ! mesenchymal cell
