### ISSUE TITLE
TAR (trans-activation response element) binding

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12471]
Suggested new GO term for annotating HIV Tat protein:

trans-activation response element binding ; GO:NEW
is_a: pre-miRNA binding ; GO:0070883
synonym: TAR binding (PMID:25116364)
Interacting selectively and non-covalently with an trans-activation response (TAR) element, a hairpin RNA structure located at the 5’ end of all HIV-1 transcripts, and which is required for trans-activation of a viral promoter.
Wikipedia: Trans-activation_response_element_(TAR)
RFam: RF00250
PMID:25116364, GOC:PARL, GOC:bf

Is this the level of specificity we want to capture in GO? Will add in as a narrow synonym to 'pre-miRNA binding ; GO:0070883' if not.

Thanks!

**Comment by paolaroncaglia** [comment]
Hi @rebeccafoulger ,

I think the level of specificity would be fine; there are several other ‘x response element binding’ terms in GO.
It would be nice if we could logically define the new term using an SO term (via has_input), similarly to GO:0035198 ‘miRNA binding’, but SO doesn’t seem to have a class for TAR, and most terms in the ‘RNA binding’ note don’t have logical defs anyway. 
Note there’s a tiny typo in your suggested def (“Interacting … with *an* trans-activation response …”).
Assigning to you, thanks.

**Comment by rebeccafoulger** [comment]
Created in TG Free-from (with typo corrected in definition- thanks Paola!):
GO:1990970 Label: trans-activation response element binding
