### ISSUE TITLE
eosinophilic homeostasis

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12474]
I just made a TermGenie request that wasn't quite ready for the submit button:

[Term]
id: GO:1990959
name: eosinophil proliferation
namespace: biological_process
def: "The process of regulating the proliferation and elimination of eosinophils such that the total number of neutrophils within a whole or part of an organism is stable over time in the absence of an outside stimulus." [PMID:10606160]
subset: termgenie_unvetted
synonym: "eosinocyte homeostasis" EXACT []
synonym: "eosinophilic granulocyte homeostasis" EXACT []
synonym: "eosinophilic leucocyte homeostasis" EXACT []
synonym: "eosinophilic leukocyte homeostasis" EXACT []
is_a: GO:0001776 ! leukocyte homeostasis
is_a: GO:0002262 ! myeloid cell homeostasis
created_by: sl
creation_date: 2016-06-06T22:34:31Z

The name should be "esosinophil homeostasis" and the def should be: "The process of regulating the proliferation and elimination of eosinophils such that the total number of eosinophils within a whole or part of an organism is stable over time in the absence of an outside stimulus."

**Comment by paolaroncaglia** [comment]
Done.
