### ISSUE TITLE
incorrect parent child regulates in cell cycle node

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12479]
@rachhuntley  spotted:

The term is GO:1900477 negative regulation of G1/S transition of
mitotic cell cycle by negative regulation of transcription from RNA
polymerase II promoter and it is an is_a child of  GO:1900087 positive
regulation of G1/S transition of mitotic cell cycle.

**Comment by ukemi** [comment]
Hi Val,

I see this as an is_a child of 'negative regulation of G1/S transition of mitotic cell cycle' and an is_a child of 'negative regulation of transcription from RNA polymerase II promoter'. What am I missing?

-D

**Comment by ValWood** [comment]
QuickGo change log shows it was fixed:

2016-06-22	Deleted	RELATION	is a GO:1900087 (positive regulation of G1/S transition of mitotic cell cycle)
