### ISSUE TITLE
NTR: modulation by host of viral transcription factor

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12470]
For annotation of PMID:25116364, I need a way of expressing that human NUCKS1 enhances the transcriptional activity of Tat. I can currently capture the process but not that Tat is the target of NUCKS1’s regulation.

Suggested new term:
modulation by host of viral RNA-binding transcription factor activity ; GO:NEW
is_a: modulation by host of viral molecular function ; GO:0044868
is_a: modulation by host of viral transcription ; GO:0043921
is_a: regulation of RNA binding transcription factor activity (NEW, also)
A process in which a host organism modulates the frequency, rate or extent of the activity of a viral RNA-binding transcription factor.
PMID:25116364, GOC:PARL, GOC:bf

Any comments before I commit @dosumis?

**Comment by paolaroncaglia** [comment]
Hi @rebeccafoulger ,
I added a couple of labels to this ticket (just for ease of making stats), and assigned it to you, while we wait for @dosumis to comment. Looks ok to me.

**Comment by rebeccafoulger** [comment]
TG used to create intermediate terms:
ID: GO:1905255 Label: regulation of RNA binding transcription factor activity
ID: GO:1905256 Label: negative regulation of RNA binding transcription factor activity
ID: GO:1905257 Label: positive regulation of RNA binding transcription factor activity

**Comment by rebeccafoulger** [comment]
Also note to myself:
While I'm editing this node, need to remove the erroneous relationship:
**negative** regulation by symbiont of host molecular function
--[isa]**positive** regulation by symbiont of host catalytic activity ; GO:0043948

**Comment by rebeccafoulger** [comment]
New term added in TG freeform: GO:1990969 Label: modulation by host of viral RNA-binding transcription factor activity

Just the relationship fix (see above) to complete on this ticket.

**Comment by rebeccafoulger** [comment]
Deleted the following relationship, so this ticket is done.

negative regulation by symbiont of host molecular function
--[isa]positive regulation by symbiont of host catalytic activity ; GO:0043948
