### ISSUE TITLE
modulation by host of viral RNA binding

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12472]
Another new term request for PMID: 25116364 to capture that human NUCKS1 alters the binding of viral Tat protein to the TAR (trans-activating response) RNA element:

modulation by host of viral RNA binding ; GO:NEW
is_a: modulation by host of viral molecular function ; GO:0044868
is_a: regulation of RNA binding ; GO:1905214
A process in which a host organism modulates the frequency, rate or extent of a viral protein binding to RNA.
PMID:25116364, GOC:PARL, GOC:bf

Will add in, if no objections by @dosumis or anyone else.

**Comment by paolaroncaglia** [comment]
Looks fine to me, thanks.

**Comment by rebeccafoulger** [comment]
Added in TG Freeform: ID: GO:1990968 Label: modulation by host of viral RNA binding
