### ISSUE TITLE
Edits to term: suppression by virus of host protein binding ; GO:0036472

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12482]
This term name is confusing:
suppression by virus of host protein binding ; GO:0036472
Exact synonym: suppression by virus of host protein interaction
Any process in which a virus stops, prevents, or reduces the frequency, rate or extent of interaction between host proteins.

It has my initials on it, and the only annotation is by me to PMID:17297443 (also cited in Definition DBXref). This paper shows that viral protein vIRF1 inhibits interaction between the two host proteins, HtrA2 and GRIM-19. The term name though sounds like it could be a virus suppressing a viral protein binding to a host protein.

A better name would be:
suppression by virus of host protein-protein interaction
synonym: suppression by virus of host protein:protein binding
synonym: suppression by virus of host protein:protein interaction
synonym: suppression by virus of host protein binding

Any better name suggestions before I rename?
Thanks!

**Comment by paolaroncaglia** [comment]
Hi @rebeccafoulger ,

Your suggested name change sounds good to me! Same for synonyms.

Thanks.

**Comment by rebeccafoulger** [comment]
Renamed GO:0036472 as suggested to: suppression by virus of host protein-protein interaction' and added synonyms.
