### ISSUE TITLE
Terms missing classification

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12485]
Following the move to the new inference system, a number of terms have ended up with no classification.  At least one reason for this is that the existing is_a completeness check has been suspended and some classes will have had stale inferred = True tags that have been filtered out by the new system.  This old is_a completeness check needs to be replaced by a check that can look for genus via intersections (a purely logical check for whether a class is a subclass of one of the three GO roots would work too).

Looking at the terms with no classification (see list below), it seems like many of them have lost their logical (EC) definitions.  This is unlikely to be anything to do with the move to the new inference system.  It may be worth investigating how this has happened, but it looks straightforward to fix.

TODO: 

- [x] Implement new 'is_a' complete Jenkins check that can use intersections.  @cmungall 

Fix classification/logical defs for the following terms:

- [x] 'extracellular exosome'
- [x] 'negative regulation of aspartic-type endopeptidase activity involved in amyloid precursor protein catabolic process'
- [x] 'negative regulation of cardiac cell fate specification'
- [x] 'negative regulation of cardiac muscle cell differentiation'
- [x] 'negative regulation of cardiac vascular smooth muscle cell differentiation'
- [x] 'negative regulation of cardioblast differentiation'
- [x] 'negative regulation of mRNA binding'
- [x] 'positive regulation of aspartic-type endopeptidase activity involved in amyloid precursor protein catabolic process'
- [x] 'positive regulation of cardiac muscle cell differentiation'
- [x] 'positive regulation of cardiac vascular smooth muscle cell differentiation'
- [x] 'positive regulation of cardioblast differentiation'
- [x] 'positive regulation of mRNA binding'
- [x] 'receptor diffusion trapping'
- [x] 'regulation of aspartic-type endopeptidase activity involved in amyloid precursor protein catabolic process'
- [x] 'regulation of cardiac cell fate specification'
- [x] 'regulation of cardiac muscle cell differentiation'
- [x] 'regulation of cardiac vascular smooth muscle cell differentiation'
- [x] 'regulation of cardioblast differentiation'
- [x] 'regulation of mRNA binding'

**Comment by dosumis** [comment]
#12484 will be fixed by fixing 

 'regulation of cardiac cell fate specification'
 'regulation of cardiac muscle cell differentiation'
 'regulation of cardiac vascular smooth muscle cell differentiation'

**Comment by cmungall** [comment]
That's very disturbing that these have lost their logical defs

Looking at negative regulation of mRNA binding - it was lost sometime between 2016-06-01 and 2016-06-15

**Comment by cmungall** [comment]
The build-go job has been modified, as well as the check-obo script.

There are now two options, on by default

 1 `isa-incomplete-strict` - must have is_a tag
 2 `isa-incomplete` - must have is_a tag, unless it has intersection_of tag

1 is disabled in the build-go job when checking the editors file

Gives what looks like the same as the above

```
 :: ERROR: isa-incomplete: GO:0051890
  :: ERROR: isa-incomplete: GO:0051891
  :: ERROR: isa-incomplete: GO:0051892
  :: ERROR: isa-incomplete: GO:0070062
  :: ERROR: isa-incomplete: GO:0071914
  :: ERROR: isa-incomplete: GO:0098953
  :: ERROR: isa-incomplete: GO:1902415
  :: ERROR: isa-incomplete: GO:1902416
  :: ERROR: isa-incomplete: GO:1902959
  :: ERROR: isa-incomplete: GO:1902960
  :: ERROR: isa-incomplete: GO:1902961
  :: ERROR: isa-incomplete: GO:1904572
  :: ERROR: isa-incomplete: GO:2000043
  :: ERROR: isa-incomplete: GO:2000044
  :: ERROR: isa-incomplete: GO:2000722
  :: ERROR: isa-incomplete: GO:2000723
  :: ERROR: isa-incomplete: GO:2000724
  :: ERROR: isa-incomplete: GO:2000725
  :: ERROR: isa-incomplete: GO:2000726
  :: ERROR: isa-incomplete: GO:2000727
```

And we have a red ball as expected
https://build.berkeleybop.org/job/build-go/7216/

**Comment by dosumis** [comment]
Issues in this ticket fixed, but build still failing: https://build.berkeleybop.org/job/build-go/7217/console
