### ISSUE TITLE
redundant is_a link under localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12489]
GO:1990852 is_a GO:0071988 link isn't necessary because GO:1990852 has a path to GO:0071988 via the part_of step

Can this be deleted? It will help our  curation extension configuration
https://github.com/pombase/canto/issues/1148#issuecomment-227142175

**Comment by cmungall** [comment]
There are no immediate plans to remove this inferred link as part of the release pipeline. It's not actually redundant, and extension checks shouldn't treat it this way

There is a good argument for doing more extreme filtering for go-basic and basic visualizations.

I don't understand the curation extension use case and this raises red flags

For discussion on different kinds of redundancy filtering using the standard release pipeline tool ROBOT:
https://github.com/ontodev/robot/issues/16

**Comment by ValWood** [comment]
OK maybe I got this wrong. 
I can work around it anyways, will close.

We have a new feature for Canto, where it present the user with  sensible  annotation extension options. This goes beyond domain and range, we  configure  specific  ontology terms and their children  to  only present an extension option if it is valid. For example you are prompted for  kinase substrates when you  annotate protein kinases.
Sometimes we are getting both "transports" and "localizes"  but we have a way of working around this in the config files (we can negate a subset of terms for a particular relation).  When they mature a bit more I was going  to let you and @tonysawfordebi  know...they might be useful for LEGO or protein2GO at some point....(or the principle....)

config files are here
https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/annotation_ex_config/

**Comment by ValWood** [comment]
Actually something seems a bit odd with the logic of the relationships.

If 
 GO:1990852 protein transport along microtubule to spindle pole body
is_a 
 GO:0071989 establishment of protein localization to spindle pole body

AND  GO:0071989 is part_of
 GO:0071988 protein localization to spindle pole body

Can GO:1990852 be  is_a
GO:0071988 protein localization to spindle pole body

**Comment by dosumis** [comment]
You're right.  Fixed  - hierarchy now all is_a. There is a more general job to cleanup in this branch where we have both is_a and part_of.  We agreed to switch to all is_a at the College Station meeting.  This has only been partially implemented to now.  The good news is that the new pipeline makes fixing these things much more straightforward, so we should have less of this in future.
