### ISSUE TITLE
NTR: Factor VII - TF complex (EBI-9026112)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12488]
Dear Editors,

I would like to request a new protein complex term: Factor VII - TF complex (EBI-9026112).

Re: Figure 6, PMID-24998411.

Based on Figure 6 and methods described in this paper I would like to create cellular component annotations to this complex for Factors F3 (P13726) and F7 (P08709).

Thank you,
Barbara

Thank you,
Barbara

GOC:BHF, GOC:BHF_miRNA and GOC:bc

@RLovering 
@rachhuntley

**Comment by tberardini** [comment]
Definition and parentage please.  Thanks.

**Comment by bmeldal** [comment]
See also Complex Portal EBI-9026112:
http://www.ebi.ac.uk/intact/complex/details/EBI-9026112

I didn't request the GO CC term at the time as we were waiting for clarification on the pruning of complexes in GO (which doesn't seem to go ahead in the radical way originally proposed).

Please add the MFs and BPs form the complex annotation as capable_of(_part_of).

Thanks,
Birgit

**Comment by mcourtot** [comment]
I was a bit surprised to see this request coming through as I thought we wouldn't be duplicating complexes between GO and CP anymore, as it seems really redundant. Maybe worth discussing (again) during an editor call? @dosumis

**Comment by bmeldal** [comment]
Well, the problem was that unless we use the GO CC term software packages overlook the complex terms as they don't 'see' the CP ACs. Val had some examples. In practice it means the analysis doesn't group the proteins together as present in the same complex unless you have them annotated to the same GO term.

**Comment by ValWood** [comment]
I don't think that's how the discussion ended :) I'm still under the impression that the 'generic' complexes will be in GO but not species specific variants......

**Comment by bmeldal** [comment]
I agree with Val, that's what I thought, and the TF is generic. I was about to add a new generic leaf term via TG FF as it has no defined function to make such a parent but groups several complexes.

**Comment by BarbaraCzub** [comment]
In response to Tanya's question:

The Factor VII - TF complex (EBI-9026112) has the molecular function 'GO:0008236	serine-type peptidase activity', therefore, I would suggest creating a parent term 'serine peptidase complex'. E.g. 'GO:0097180 serine protease inhibitor complex' exists, so 'serine peptidase complex' would become its sibling. Without adding in this parent to the ontology, I think 'Factor VII - TF complex' would have to be a child of 'GO:0043234 protein complex'.

The GO definition for this complex could be: 	'A heterodimeric protein complex that contains coagulation Factors F3 and F7;  the complex activates factors IX or X by specific limited proteolysis.'

But if it's decided that we do not want complexes as specific, then maybe just the grouping term 'serine peptidase complex' could be created, as at the moment the most specific cellular component, to which we can annotate Factors F3 (P13726) and F7 (P08709), is 'GO:0043234 protein complex'.

**Comment by bmeldal** [comment]
I can create the functional parent in TG template. I should have done that for the TF complex in the CP already, not sure actually why I didn't...

**Comment by BarbaraCzub** [comment]
Brilliant, thank you. Could you please let me know what the complex ID is once you've created it?

**Comment by bmeldal** [comment]
Barbara, I have created

ID: GO:1905286 Label: serine-type peptidase complex

It should trickle through the release system in a couple of days.

I can also make the TF complex (in TG free form) if we agree to go back to that level.

Birgit

**Comment by tberardini** [comment]
Shall we leave this issue open or can you @BarbaraCzub use the term that Birgit created for annotation?

[Term]
id: GO:1905286
name: serine-type peptidase complex
namespace: cellular_component
def: "A protein complex which is capable of serine-type peptidase activity." [GO_REF:0000088, GOC:bhm, GOC:TermGenie, PMID:18640965]
comment: An example of this is F7 in human (P08709) in PMID:18640965 (inferred from direct assay).
synonym: "Factor VII - TF complex" NARROW []
intersection_of: GO:0043234 ! protein complex
intersection_of: capable_of GO:0008236 ! serine-type peptidase activity
created_by: bhm
creation_date: 2016-06-21T14:20:20Z

**Comment by BarbaraCzub** [comment]
Thank you, Birgit, for creating this term.

Tanya, I am happy to use this new term, if it is preferable not to create terms, which are more specific.

**Comment by tberardini** [comment]
Barbara - great! I will close this issue and should the decision to add the more specific term be made, we can add it in the future.
