### ISSUE TITLE
minor adjustments to fork processing terms GO:1903211, GO:1990426

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12481]
At present, GO:1903211 and GO:1990426 appear as siblings. From the text definitions and existing links, it looks like GO:1903221 should be part_of GO:1903211. Also, because both refer to GO:0006312, it would make sense for their names to match; I suggest renaming GO:1990426.

or, in partial-stanza form,

change from:
id: GO:1990426
name: homologous recombination-dependent replication fork processing
is_a: GO:0031297 ! replication fork processing
relationship: has_part GO:0006312 ! mitotic recombination

and
id: GO:1903211
name: mitotic recombination involved in replication fork processing
is_a: GO:0006312 {is_inferred="true"} ! mitotic recombination
intersection_of: GO:0006312 ! mitotic recombination
intersection_of: part_of GO:0031297 ! replication fork processing
relationship: part_of GO:0031297 {is_inferred="true"} ! replication fork processing

to:
id: GO:1990426
name: mitotic recombination-dependent replication fork processing
synonym: "homologous recombination-dependent replication fork processing" EXACT []
is_a: GO:0031297 ! replication fork processing
relationship: has_part GO:0006312 ! mitotic recombination

and
id: GO:1903211
name: mitotic recombination involved in replication fork processing
is_a: GO:0006312 {is_inferred="true"} ! mitotic recombination
intersection_of: GO:0006312 ! mitotic recombination
intersection_of: part_of GO:1990426 ! mitotic recombination-dependent replication fork processing
relationship: part_of GO:1990426 {is_inferred="true"} ! mitotic recombination-dependent replication fork processing

**Comment by paolaroncaglia** [comment]
Done.
