### ISSUE TITLE
small def edit , telosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12483]
Definition: "A nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. The complex contains TRF1, TRF2, POT1, RAP1, TIN2 and TPP1 in mammalian cells, and Pot1, Tpz1, Ccq1, Poz1, Rap1, Rif1, Rif2and Rap1 in Schizosaccharomyces. Taz1 and Rap1 (or their mammalian equivalents) form a dsDNA-binding subcomplex, Pot1 and Tpz1 form an ssDNA-binding subcomplex, and the two subcomplexes are bridged by Poz1." [GOC:expert_mf, GOC:mah, GOC:vw, PMID:18828880]

Pombe Rap1 is mentioned twice
Rif2and missing space
Schizosaccharomyces. Taz1  is mentioned, but this is not in the list of subunits

MAybe we should review the compositions anyway (or  only mention any subunit differences?)

@RLovering ?

**Comment by ValWood** [comment]
Hu TRF1  (should be TERF1?)  ??  pombe
Hu TRF2, ( should be TERF2?)  ??  pombe
Hu POT1 =   pombe Pot1
Hu RAP1 =   pombe Rap1 
Hu TIN2   (I should be TINF2?) = ??  pombe
Hu TPP1 =  (should be ACD?)   pombe Tpz1

Poz1 I have never detected orthologs outside of  Schizos, nut it may be one of the above
Rif1, Rif2 have Human orthologs which are telomere associated...
Ccq1 currently only identified in fungi....

OK< i'm now convinced they are analogogous.

Need to  use the HGNC names for human...

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

I edited the def of ‘telosome’ as follows:

"A nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. The complex is known to contain TERF1, TERF2, POT1, RAP1, TINF2 and ACD in mammalian cells, and Pot1, Tpz1, Rap1, Rif1, Rif2 and Taz1 in Schizosaccharomyces. Taz1 and Rap1 (or their mammalian equivalents) form a dsDNA-binding subcomplex, Pot1 and Tpz1 form an ssDNA-binding subcomplex, and the two subcomplexes are bridged by Poz1, which acts as an effector molecule along with Ccq1.”

I’m closing this ticket now, but if you or @RLovering  have any comments, feel free to re-open.
