### ISSUE TITLE
Missing parent for GO:2000725 regulation of cardiac muscle cell differentiation

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#12484]
Hello,
GO:2000725 "regulation of cardiac muscle cell differentiation" does not have the parent GO:0055007 "cardiac muscle cell differentiation". The relation appears to have been removed on 4th June 2016 and a relation added to GO:1905207 "regulation of cardiocyte differentiation". Cardiocyte is a less specific type than cardiac muscle cell.

It looks like this has also happened for other cardiocyte types, e.g. GO:0060947 "cardiac vascular smooth muscle cell differentiation" is a GO:1905207 "regulation of cardiocyte differentiation" but no longer regulates GO:0060947 "cardiac vascular smooth muscle cell differentiation". 

Is there a reason for this?

Thanks,
Rachael.

**Comment by paolaroncaglia** [comment]
Hi @rachhuntley ,

Hm. I'm going to ask @cmungall if he can help with this one please. GO:1905207 "regulation of cardiocyte differentiation" was created as part of this commit:

r33577 | termgenie | 2016-06-02 20:58:39 +0100 (Thu, 02 Jun 2016) | 4 lines

TermGenie commit for user: bc reviewed by dph
Added GO:1905207 regulation of cardiocyte differentiation
Added GO:1905208 negative regulation of cardiocyte differentiation
Added GO:1905209 positive regulation of cardiocyte differentiation

We've been doing some work on inferences, but that shouldn't have deleted good granular inferences...?

**Comment by dosumis** [comment]
Rather worrying: It looks like around 20 terms have lost their logical definitions completely in the master file including some of the cardiac terms mentioned here.  I can easily add them back, but  we need to look carefully through recent diffs to see if anything else has been lost.

**Comment by dosumis** [comment]
Fixed

**Comment by paolaroncaglia** [comment]
Thanks @dosumis .
