### ISSUE TITLE
OTR:definition change for SCAR complex GO:0031209

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12480]
Current definition: "A heterotetrameric complex that includes orthologues of human PIR121, Nap125 and HSPC300 and regulates actin polymerization and/or depolymerization through small GTPase mediated signal transduction."

It is now known to be a pentameric complex. Suggested new definition:
"A pentameric complex that includes orthologues of human PIR121, Nap1, Abi, SCAR, and HSPC300 and regulates actin polymerization and/or depolymerization through small GTPase mediated signal transduction."

Refs: PMID:24036345, PMID:24630101

Additional synonyms: WAVE regulatory complex, WRC

**Comment by paolaroncaglia** [comment]
Done.

**Comment by hattrill** [comment]
You are sooo speedy! thanks.
