### ISSUE TITLE
New parent for phosphatidylcholine-translocating ATPase activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12486]
Hi

I think the ontology needs rearranging in this area:

GO:0042626 ATPase activity, coupled to transmembrane movement of substances 
Definition: Catalysis of the reaction: ATP + H2O = ADP + phosphate, to directly drive the active transport of a substance across a membrane.
should have the following is_a child term:
> GO:0004012 phospholipid-translocating ATPase activity
definition: Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, driven by the hydrolysis of ATP.

Currently both terms have the parent:  GO:0043492 ATPase activity, coupled to movement of substances, and both terms relate to the hydrolysis of ATP to transport a molecule across a membrane.

Unless I have missed something here?

Best

Ruth

**Comment by ValWood** [comment]
Hi Ruth,

IIRC ,  the first one describes "transmembrane transporter ATPases" movement of substances through the bilayer (across both membranes)

GO:0004012 phospholipid-translocating ATPase activity 
is just about transferring phospholipids from one leaflet to the other

Could be clearer though always catches me....

**Comment by RLovering** [comment]
Hi Val

That is so helpful, what happens if it translocates across both lipid leaflets do you then annotate as a transporter and not a translocating ATPase? The authors are talking about this as a translocator but the phospholipid ends up outside the cell: PMID:8898203 
the short-chain lipids must have been translocated by the Pgps across the plasma membrane before extraction into the medium by the lipid-acceptor albumin. Then in the intro they state: One model for its mechanism of action proposes that MDR1 Pgp binds an amphipathic molecule in the cytoplasmic leaflet of the plasma membrane and flips its polar group across the plasma membrane to deliver the molecule to the exoplasmic leaflet of the plasma membrane (Higgins and Gottesman 1992). 

sorry to put this on you but your thoughts would be much appreciated on this

Best
Ruth

**Comment by ValWood** [comment]
I can't remember  the whole history of this, I searched github and this seems to be the most related ticket:

https://github.com/geneontology/go-ontology/issues?utf8=%E2%9C%93&q=is%3Aissue+translocating

**Comment by ValWood** [comment]
Although this seems to imply otherwise.....
https://en.wikipedia.org/wiki/Phospholipid-translocating_ATPase

**Comment by ValWood** [comment]
based on this def
phospholipid-translocating ATPase activity
Ontology	Molecular Function
Definition	Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, driven by the hydrolysis of ATP. 

It sound as though what you are describing are 'transporters' not 'translocases' I don't  know the  origins of this though. I'm sure there was a really good wiki page explaining translocases (in the GO def context), but I can't find it now.....

Who would know more? @mah11  any memories? I remember long discussions with Dianna Fisk, but I can't find them....

**Comment by tberardini** [comment]
From the definition and the EC number and papers in the definition, it looks like this term is meant for the annotation of gene products involved in moving PL from one membrane leaflet to the other (remaining attached to that leaflet), but NOT to the 'outside' of a membrane (and no longer attached). 

@RLovering  - From reading the paper you referenced, I think your protein does the 'flipping' activity and using this term would be correct for use in annotation.

"Translocation across the plasma membrane to its exoplasmic leaflet, the cell surface, can be measured by extracting short-chain lipids from the cell surface into medium containing excess albumin, a protein that binds short-chain lipids and in this case acts as a sink."

The extraction process removes the short-chain lipids from the cell surface.  The lipids do not appear to be released into the outside of the cell without the extraction assay.  If you look at the Materials and Methods section, Transport Incubations, you'll see that BSA was used to extract lipids from the cell surface. "During the incubation, short-chain lipid products appearing on the cell surface were depleted into the medium by the BSA."

**Comment by RLovering** [comment]
Thank you both for helping me with this, this now makes sense. 

Best

Ruth

**Comment by ValWood** [comment]
been there  and confused by, many times ;) I thought I had  better details but  we have Tanya's explanation for next time ;)

**Comment by tberardini** [comment]
You're welcome!  :)
