### ISSUE TITLE
trying to locate terms for reactions in phospholipid biosynthsis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12499]
I am looking for reactions to describe

PA (phosphatidate) -> CDP-diacylglycerol (CDP-DG) CDP-diacylglycerol synthase (CDP-DGS)
is this GO:0050520?

CDP-diacylglycerol (CDP-DG) ->   phosphatidyl inositol (PI)   phosphatidylinositol synthase (PIS)
(I can’t find anything for this one, but I’m sure it  must be in GO somewhere?)

**Comment by ValWood** [comment]
![phospholipid_biosynthesis](https://cloud.githubusercontent.com/assets/7359272/16418775/311978ca-3d43-11e6-97ba-0ad3cfda7fb4.jpg)

**Comment by mah11** [comment]
maybe these? (rafts of other synonyms not shown)

id: GO:0004605
name: phosphatidate cytidylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: CTP + phosphatidate = diphosphate + CDP-diacylglycerol." [EC:2.7.7.41]
...
synonym: "CDP-diacylglycerol synthase activity" EXACT []

id: GO:0003881
name: CDP-diacylglycerol-inositol 3-phosphatidyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: myo-inositol + CDP-diacylglycerol = 1-phosphatidyl-1D-myo-inositol + CMP + H(+)." [EC:2.7.8.11, RHEA:11583]
...
synonym: "phosphatidylinositol synthase activity" EXACT []

**Comment by ValWood** [comment]
Will check those out. I'm also looking for

phosphatidylserine (PS) ->  phosphatidylethanolamine (PE)

phosphatidylglycerolphosphate PGP-> phosphatidylglycerol PG
GO:0008444?

phosphatidylglycerol PG-> cardiolipin CL
if  GO:0008444 is correct, I am looking for a reaction with
 3-(3-sn-phosphatidyl)-sn-glycerol 1-phosphate  as input and ceramide as output. I can’t find another GO term containing  3-(3-sn-phosphatidyl)-s 3-(3-sn-phosphatidyl)-sn-glycerol 1-phosphate?

I think its probably GO:0008808
but it would be good if the inputs and outputs were consistent...

**Comment by ValWood** [comment]
OK sorted. I don't know why I couldn't find them.
The only one I am still looking for is
phosphatidylserine (PS) -> phosphatidylethanolamine (PE)

**Comment by mah11** [comment]
might be 

id: GO:0004609
name: phosphatidylserine decarboxylase activity
def: "Catalysis of the reaction: H(+) + phosphatidyl-L-serine = CO(2) + phosphatidylethanolamine." [EC:4.1.1.65, RHEA:20831]

**Comment by ValWood** [comment]
yep thats what I got...
