### ISSUE TITLE
synonyms for R-SMADs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12493]
Hi

please could the following synonyms be added to make our terms more consistent. I believe that R-SMADs are known by several names: 

In the abstract of PMID: 15253713 is this statement:Induction of VEGF-A and TSP-1 by TGF-beta1 in NRK52E cells was associated with activation of pathway-restricted R-Smads (Smad2 and 3) and blocking these Smads by overexpression of Smad7 blocked their induction.
And in Wikipedia: R-SMADs are receptor-regulated SMADs
So R-SMADs synonyms are:
receptor-regulated SMADs
pathway-restricted SMADs
However in GO this information isn't included. Plus the terms are not consistent.

Please add synonyms to:

- [x] GO:0070412
 R-SMAD binding

exact synonym: pathway restricted SMAD binding
pathway-restricted SMAD binding
receptor-regulated SMAD binding
receptor regulated SMAD binding

Then to 

- [x] GO:0060389
 pathway-restricted SMAD protein phosphorylation

exact synonym: pathway restricted SMAD protein phosphorylation
R-SMAD protein phosphorylation
receptor-regulated SMAD protein phosphorylation
receptor regulated SMAD protein phosphorylation

It would also be nice if these synonyms were added to the regulation terms for GO:0060389 pathway-restricted SMAD protein phosphorylation but you may not have time for this.

Then to:

- [x] GO:0030618
 transforming growth factor beta receptor, pathway-specific cytoplasmic mediator activity

Add narrow synonyms:
pathway-restricted SMAD protein
pathway restricted SMAD protein
receptor-regulated SMAD protein 
receptor regulated SMAD protein 
R-SMAD

And I guess we should look at the synonyms for co-SMADs too

add synonyms:

- [x] GO:0070410
 co-SMAD binding

exact synonyms:
common mediator SMAD binding
common-mediator SMAD binding
common-partner SMAD binding
common partner SMAD binding

- [x] GO:0007182
 common-partner SMAD protein phosphorylation

add exact synonyms:
common-mediator SMAD protein phosphorylation
co-SMAD protein phosphorylation
common partner SMAD protein phosphorylation

- [x] GO:0030616
 transforming growth factor beta receptor, common-partner cytoplasmic mediator activity

add narrow (related?) synonyms:
common-mediator SMAD protein
common mediator SMAD protein
co-SMAD protein
common partner SMAD protein

Thanks

Ruth

**Comment by tberardini** [comment]
Done.
