### ISSUE TITLE
Making regulate relationship transitive

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-ontology#12491]
Perhaps because this was out of sight on JIRA, it never received a response. 
@cmungall I am resurrecting for your reading and discussing pleasure.  :bowtie: 
The original issue and comments can be found at http://jira.geneontology.org/browse/GO-904
If there is no urgency or need to address at this time, please comment and close. 

=====
_Submitted on Sunday, July 26, 2015 - 13:25
Submitted by anonymous user: --IP goes here--
Submitted values are:
Name: E. Tapia
E-mail: --email-goes-here--
Subject: Ontology (e.g. structure, relations, subsets/slims...)
Comment or query:
Dear all,
I have a doubt with the regulate (R) relationship. May it be possible that a
chain R.R exist within the BP ontology or any other?
In such a case, being R non transitive, may it be correct to transverse de
DAG to the root node and propagate annotations using the True Path Rule?
If not, does it mean that DAGs in GO never contain non-transitive paths to
the root?
Best regards,
--signature--
The results of this submission may be viewed at:
http://geneontology.org/node/899/submission/635_

**Comment by cmungall** [comment]
* The regulates relation is transitive. The characteristics of different relations can be determined unambiguously by looking at the OWL edition of GO. See http://geneontology.org/page/download-ontology
 * To find all genes that are involved in or regulate a process P or function F, you can traverse over any number of or combination of part-of, regulates (incl pos and negative) relations

**Comment by monicacecilia** [comment]
Brilliant! Thanks for adding a response here. :bowtie:

**Comment by ValWood** [comment]
Hi Chris,
Is that true? I thought it was transitive over BP, but not MF

For example you could not propagate  annotations to 
"protein kinase regulator activity" to "protein kinase activity"
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0019887#term=ancchart

?

**Comment by dosumis** [comment]
Nothing to do with annotation propagation.  A relation is transitive if you can collapse down a chain and still get a true statement  In this case. 

A regulates B regulates C regulates D  => A regulates D

 There are no limits to the length of a chain.

**Comment by ValWood** [comment]
OK, I always get confused between this and "transitivity".  Ignore.

**Comment by ValWood** [comment]
Actually though, in the original ticket, the user is talking about "propagating annotation",
http://jira.geneontology.org/browse/GO-904
and Chris seems to be referring to this above?

**Comment by dosumis** [comment]
There are two separate issue:

1. When is it safe to propagate annotations over regulates relationships (the answer should be the same whether or not regulates is transitive).
2. Is regulates transitive?  The relation in RO never used to be set to transitive, but it is now.

Perhaps the confusion comes from assuming that it is safe to propagate annotations over all relationships in GO.  This is definitely not the case, although by convention we've tended to keep the relationship types it definitely is not safe to propagate over in go-plus.owl.  I've never been entirely comfortable with propagation over regulates, but it seems to have become standard practise (at least for BP?).  Strictly, it breaks the declared relationship between Gene product and GO term:  

* GP-X involved in BP-Y  = GP enables an MF that is part_of (some) BP-Y
* If we propagate over regulates then the relationship for propagated annotations becomes:
   * GP enables an MF  that regulates (some) BP-Y
