### ISSUE TITLE
obsolete terms (non existent process) under histone acetylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12490]
These terms (not used for any EXP annotation)
Look  the wrong way around to me?
Histone acetylation regulates transcription, not transcription regulates histone acetylation.
Did

Process
 GO:0100030
regulation of histone acetylation by transcription from RNA polymerase II promoter

Process
 GO:1900411
regulation of histone acetylation by regulation of transcription from RNA polymerase II promoter

I checked the history and I can't see a ref. Apologies if it was  me... I don't recall it.....

**Comment by RLovering** [comment]
yes see also #11583

**Comment by RLovering** [comment]
this change was requested in the ticket listed above Best Ruth

**Comment by srengel** [comment]
i read these terms as regulating the transcription of proteins involved in DOING the histone modification/methylation/acetylation, etc.  

is that what they are supposed to mean?

**Comment by ukemi** [comment]
Scanning the original reference (PMID:15218150) that is in the xref for GO:1900411, it looks like the process actually exists.

**Comment by tberardini** [comment]
There are two sets of terms:

regulation of histone modification by **regulation of** transcription...
and
regulation of histone modification by transcription...

Is there a case for retention of one set (the regulation by regulation one)  and not the other?  Or should we keep both?

**Comment by ValWood** [comment]
Re PMID:15218150

ATF1 *is* a transcription factor, but I think this could be a moonlighting function where atf1 can nucleate heterochromatin assembly  in the mating type region (it also has another role binding to recombination hotspots). This paper is not describing transcriptional regulation of histone modification....

**Comment by tberardini** [comment]
Resending comment from a month ago.  I was getting ready to send obsoletion notice when we hit a snag.  Please comment on the preferred course of action.

----------------

There are two sets of terms:

regulation of histone modification by regulation of transcription...
and
regulation of histone modification by transcription...

Is there a case for retention of one set (the regulation by regulation one) and not the other? Or should we keep both?

**Comment by ValWood** [comment]
For pombe, all examples of  histone modification are regulated post-transcriptionally regulated. I still think they should go.
The original ref used by us pointed out by David seems to be another role of Atf1, unrelated to its role in transcription  (and, it could be an indirect effect at that...)

**Comment by tberardini** [comment]
@ValWood : " I still think they should go."

Which terms are 'they'?  All of the ones I listed in the checklist above?

**Comment by ValWood** [comment]
anything or descendants
regulation of histone acetylation by transcription

(I don't think any of these terms have experimental annotations?)

**Comment by tberardini** [comment]
Unless there are objections, I will send out an obsoletion notice for all SIX terms in the checklist above on Tuesday, 7/26.

**Comment by tberardini** [comment]
Obsoletion email sent out today:

Dear all,

The proposal has been made to obsolete the following terms:


GO:1900410, regulation of histone modification by regulation of transcription from RNA polymerase II promoter
GO:1900411, regulation of histone acetylation by regulation of transcription from RNA polymerase II promoter
GO:1900412, regulation of histone methylation by regulation of transcription from RNA polymerase II promoter
GO:0100030, regulation of histone acetylation by transcription from RNA polymerase II promoter
GO:0100029, regulation of histone modification by transcription from RNA polymerase II promoter
GO:0100031, regulation of histone methylation by transcription from RNA polymerase II promoter

The reason for obsoletion is that the terms represent processes that do not exist, the histone modification regulates transcription not the other way around.  The longer discussion on this issue can be reviewed and added to here:

https://github.com/geneontology/go-ontology/issues/12490

None of the terms have any annotations.

*** Unless objections are received by August 9, 2016, we will assume that you agree to this change. ***

On behalf of the GO ontology editors,

Tanya

**Comment by tberardini** [comment]
Whoops. Forgot about obsoleting these terms.  Done now.
