### ISSUE TITLE
NTR: Long-chain Base Transport

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#12498]
Hi,

I need to request a generic term for long-chain base transport, as described in the following paper:

Narita T, Naganuma T, Sase Y, Kihara A. Long-chain bases of sphingolipids are 
transported into cells via the acyl-CoA synthetases. Sci Rep. 2016 May 3;6:25469.
doi: 10.1038/srep25469. PubMed PMID: 27136724; PubMed Central PMCID: PMC4853782.

Term: long-chain base transport

Definition: The directed movement of long-chain bases, also known as sphingoid bases, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. A long-chain bases are long-chain aliphatic amines that are the fundamental building blocks of sphingolipids.The main mammalian sphingoid bases are dihydrosphingosine and sphingosine, while dihydrosphingosine and phytosphingosine are the main sphingoid bases in yeast

Synonyms: sphingoid base transport, sphingoid transport, dihydrosphingosine transport, sphingosine transport, phytosphingosine transport

Possible instance of: GO:0015837 amine transport

Definition reference: PMID: 27136724

Cheers,
Rob

**Comment by robnash** [comment]
Sorry I just saw a grammerical error in my defintion so I corrected it here:

Definition: The directed movement of long-chain bases, also known as sphingoid bases, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Long-chain bases are long-chain aliphatic amines that are the fundamental building blocks of sphingolipids.The main mammalian sphingoid bases are dihydrosphingosine and sphingosine, while dihydrosphingosine and phytosphingosine are the main sphingoid bases in yeast

Cheers,
Rob

**Comment by tberardini** [comment]
Hi Rob,

Sorry for the delay.  Could the long-chain base/sphingoid base you are referring to be the same as this sphingoid base (1+) in ChEBI?

http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:84410

If yes, the term can be added using TermGenie and the chemical_transport template and it will be placed properly in the GO structure using the ChEBI hierarchy.  If not, do you think that creating the more specific terms for dihydrosphingosine (CHEBI:46968) and phytosphingosine (CHEBI:46961) transport would be more appropriate?

http://www.sigmaaldrich.com/catalog/product/sigma/d6783?lang=en&region=US
http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:46968

http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:46961

Thanks,

Tanya

**Comment by robnash** [comment]
Hi Tanya,

No worries about the delay :) I took a look and it appears that "long-chain bases" are synonomous with "sphingoids" at least based on looking at these sites:

http://lipidlibrary.aocs.org/Primer/content.cfm?ItemNumber=39337
https://en.wikipedia.org/wiki/Sphingolipid 

I was worried that this might include short chain bases as well but it looks like they refer to long-chain bases and sphingoids interchangeably.

In addition, from what I can tell, the paper is not differentiating between the transport of the specific sphingoids other than to say that the main yeast and mammalian bases are subtly different. So in answer to your question I think at least for now one term should be sufficient using the chemical transport template and the CheBI entry you listed, until someone desribes differences in how these enter.

That being said, I have had a history of no luck using Term Genie even when Rama was here. Just leaves me frustrated. Not intuitive and think I would need a proper primer to guide me. So if it's not asking too much I wonder if you would consider adding this for me?  

Cheers,
Rob

**Comment by tberardini** [comment]
Hi Rob,

No problem.  I'm happy to add the term for you.  Can you please confirm which CHEBI id you'd like to use?

Thanks,

Tanya

**Comment by robnash** [comment]
Hi Tanya,

I decided to consult with our resident lipid expert and here is what he shared including a proposed change to the actual string for the term name, as well as confirmation of the CheBI term to use:

"The actual term for all these compounds is "sphingoid long-chain bases". This includes sphingosine, dihydrosphingosine, phytosphingosine (only in yeast, and perhaps other fungi), as well as multiple other derivatives. When I was in the lab, the term was usually truncated to just "long-chain bases" and everybody in the lab knew what it was. But since then, the truncated form has somehow escaped into the wild and it now must sound terribly generic to anybody who is not familiar with biochemistry of sphingolipids (which means most of the people). That's why I would prefer "sphingoid long-chain base transport" as a GO term, or "sphingoid base transport" to be in agreement with ChEBI (see below). The term definition sounds good, but I would include the terminology I mentioned above, by substituting "long-chain bases" with "sphingoid long-chain bases".

As for the CHEBI terms, it all seems pretty confusing there, but the most suitable term seems to be "sphingoid base(1+)" CHEBI:84410, since it covers the entire range of derivatives, including the ones with different length of their aliphatic chains. CHEBI:16566 ("sphinganine") is another name for dihydrosphingosine (even though ChEBI doesn't say that) and, biochemically, it is a precursor for sphingosine or phytosphingosine (besides having a life of its own), but that's different from "a parent" in the ontology sense. So, yes, CHEBI:84410 seems to be the best."

If we incorporate these ideas then the modified information would be as follows:

GO Term name: sphingoid long-chain base transport

Definition: The directed movement of sphingoid long-chain bases, sometimes referred to as long-chain bases, or sphingoid bases, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Sphingoid long-chain bases are long-chain aliphatic amines that are the fundamental building blocks of sphingolipids. The main mammalian sphingoid long-chain bases are dihydrosphingosine and sphingosine, while dihydrosphingosine and phytosphingosine are the main sphingoid long-chain bases in yeast

Synonyms: sphingoid long-chain base transport, sphingoid transport, long-chain base transport, dihydrosphingosine transport, sphingosine transport, phytosphingosine transport

Cheers,
Rob

**Comment by tberardini** [comment]
Added:

[Term]
id: GO:1905329
name: sphingoid long-chain base transport
namespace: biological_process
def: "The directed movement of a sphingoid long-chain base, sometimes referred to as long-chain base, or sphingoid base, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Sphingoid long-chain bases are long-chain aliphatic amines that are the fundamental building blocks of sphingolipids. The main mammalian sphingoid long-chain bases are dihydrosphingosine and sphingosine, while dihydrosphingosine and phytosphingosine are the main sphingoid long-chain bases in yeast." [GO_REF:0000065, GOC:rn, GOC:TermGenie, PMID:27136724]
synonym: "dihydrosphingosine transport" NARROW []
synonym: "long-chain base transport" RELATED []
synonym: "phytosphingosine transport" NARROW []
synonym: "sphingoid base(1+) transport" EXACT []
synonym: "sphingoid transport" RELATED []
synonym: "sphingosine transport" NARROW []
intersection_of: GO:0006810 ! transport
intersection_of: transports_or_maintains_localization_of CHEBI:84410 ! sphingoid base(1+)
created_by: tb
creation_date: 2016-07-22T01:40:59Z
