### ISSUE TITLE
Update definition of GO:0043204, perikaryon

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12494]
Current def reads	"The portion of the cell soma (cell body) that excludes the nucleus." while axioms clearly indicate it is part of the neuronal cell body.

Suggested update: "The portion of the neuronal cell body that excludes the nucleus."

[Reported by Hema Bye-A-Jee]

**Comment by dosumis** [comment]
I'm pretty sure perikaryon should just be a synonym of neuronal cell body https://en.wikipedia.org/wiki/Soma_(biology).  I don't know what the source is for excluding the nucleus.  WIkipedia includes it.

**Comment by mcourtot** [comment]
A google search shows both. @dosumis: is there an authoritative source in the domain? Hema mentioned that UniProt uses perikaryon as excluding nucleus too.

![screen shot 2016-06-23 at 15 16 00](https://cloud.githubusercontent.com/assets/2214135/16306430/914ee9a6-3955-11e6-93f4-b8aa8c21ddeb.png)

**Comment by mcourtot** [comment]
Hi @dosumis: is there perhaps a way to have both terms and use more descriptive labels?

**Comment by dosumis** [comment]
Could be useful to have both I guess, given that there are multiple precedents for perikaryon excluding nucleus.  We actually already do  have both terms (neuron cell body with nucleus = 'neuronal cell body', has_exact_synonym "neuronal cell soma").    

Looking again, I don't see any problem with the partonomy.  perikaryon is, and should be part_of neuronal cell body.  All I'd change is to add a ref for perikaryon that supports absence of a nucleus, and refine the definition a bit to: "The portion of the neuronal cell body (neuronal cell soma) that excludes the nucleus."

**Comment by mcourtot** [comment]
+ 1 - no change was suggested to partonomy, only the slight update to definition.

**Comment by mcourtot** [comment]
Done revision 36281.
