### ISSUE TITLE
multi-organism cellular localization ; GO:1902581

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12492]
multi-organism cellular localization ; GO:1902581 has no descendants. It was a TG-added term when we were creating single-organism and multi-organism grouping terms to avoid multi-organism terms appearing under single-organism processes. 

It should at least have the following children.... possibly part-of, looking at the children of the 'normal' cellular localisation term (GO:0051641):
multi-organism intracellular transport ; GO:1902583
transport of virus ; GO:0046794

The following parentage is also missing for GO:1902581 and GO:1902583:
multi-organism cellular process ; GO:0044764
—[isa]multi-organism cellular localization ; GO:1902581
—[isa]multi-organism intracellular transport ; GO:1902583

Thanks!

**Comment by dosumis** [comment]
Fixed: 

![image](https://cloud.githubusercontent.com/assets/112839/16312483/ef7598d0-3942-11e6-9cd1-d2b7ffd069d9.png)

Adding 'intracellular transport' is_a 'cellular localization' was sufficient for inference.
