### ISSUE TITLE
obsolete: multicellular structure septum development

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12496]
This is a weird term

```
id: GO:0080125
name: multicellular structure septum development
namespace: biological_process
def: "The process whose specific outcome is the progression of the multicellular structure septum over time, from its formation to the mature structure. The multicellular structure septum is the thin partition or membrane that divides a cavity or a mass of tissue." [GOC:dhl]
is_a: GO:0009888 ! tissue development
relationship: part_of GO:0048513 ! animal organ development
```

doesn't seem like a useful grouping. Perhaps septum *formation* may share mechanisms, but development.

Not sure how this one escaped taxon constraints:

```
   po GO:0048513 ! animal organ development
       po GO:0080125 ! multicellular structure septum development
        is_a GO:0080127 ! fruit septum development ***
```

!!!

Only one direct experimental annotation:

http://amigo.geneontology.org/amigo/term/GO:0080125

From this paper
http://www.ncbi.nlm.nih.gov/pubmed/9731532

It seems the desired term is *tracheoesophageal septum formation* (from the tracheoesophageal folds or ridges)?

See also [MP:0003321](http://purl.obolibrary.org/obo/MP_0003321) ! tracheoesophageal fistula

**Comment by tberardini** [comment]
Very odd. the children terms are ALL plant terms.  The term is one made by Donghui, GOC:dhl, but the relationship to animal organ development was added later in time, most likely not by him.

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0080125#term=history

@ukemi - could you look at the mouse annotation referenced above, please?

**Comment by cmungall** [comment]
I think we should

 1. [ ] make a new class `tracheoesophageal septum formation`
 2. [ ] Move the annotation here
 3. [ ] create a new plant grouping class and move the plant children here
 4. [ ] obsolete GO:0080125

**Comment by tberardini** [comment]
Ok, good plan.  I'll wait for the new UBERON term to show up, then can delegate moving the annotation to @ukemi and will proceed with the other steps.  New term will likely be 'plant septum development' with xp using PO:0000030, septum.

**Comment by tberardini** [comment]
Added:

[Term]
id: GO:1905327
name: tracheoesophageal septum formation
namespace: biological_process
def: "The process that gives rise to the tracheoesophageal septum. This process pertains to the initial formation of a structure from unspecified parts." [GO_REF:0000081, GOC:TermGenie, PMID:9731532]
synonym: "esophagotracheal septum formation" EXACT [GOC:TermGenie]
synonym: "tracheoesophageal ridges formation" RELATED [GOC:TermGenie]
intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: results_in_formation_of UBERON:0036070 ! tracheoesophageal septum
created_by: tb
creation_date: 2016-07-21T18:18:57Z

**Comment by tberardini** [comment]
Also created:

[Term]
id: GO:1905328
name: plant septum development
namespace: biological_process
def: "The process whose specific outcome is the progression of a septum over time, from its formation to the mature structure." [GO_REF:0000080, GOC:tb, GOC:TermGenie, PMID:4562349]
synonym: "dissepiment development" BROAD [GOC:TermGenie]
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of PO:0000030 ! septum
created_by: tb
creation_date: 2016-07-21T18:25:49Z

The inference pipeline will automatically move the children terms (fruit septum, ovary septum, anther septum development) under this term.

**Comment by tberardini** [comment]
@ukemi - can you please move the mouse annotation that is currently to http://amigo.geneontology.org/amigo/term/GO:0080125 to the new GO:1905327?  Then reassign to me and I'll take care of the obsoletion email and obsoletion itself.  Thanks.

**Comment by tberardini** [comment]
Following up on the moving of the mouse annotation in previous comment.  I think you should have the new term in MGI by now.  Thanks.

**Comment by ukemi** [comment]
Hi Tanya,

The annotation is moved.

-D

**Comment by tberardini** [comment]
Obsoletion email sent:

Dear all,

The proposal has been made to obsolete the following term:

 GO:0080125, multicellular structure septum development

The reason for obsoletion is that it is not a useful grouping term.

All details here:

https://github.com/geneontology/go-ontology/issues/12496

The last experimental annotation to this term was removed by MGI today.  Only 1 ISO (RGD) and 6 IEA (Ensembl) annotations remain.

We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete the term above on September 8, 2016.

*** Unless objections are received by September 16, 2016, we will assume
that you agree to this change. ***

On behalf of the GO ontology editors,

Tanya Berardini
TAIR Curator
www.arabidopsis.org

**Comment by tberardini** [comment]
Term made obsolete.
