### ISSUE TITLE
NTR: glycine betaine-activated nonselective monovalent cation channel activity

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12497]
Hi,
I am trying to annotate the C. elegans acr-23 gene described in 
http://www.ncbi.nlm.nih.gov/pubmed/24212673
and would like to request a new MF term,

GO:new glycine betaine-activated nonselective monovalent cation channel activity

The channel looks to be nonselective, i.e., it transports both Na+ and K+, so should it be housed under two parents?

GO:0005267  potassium channel activity
GO:0005272 sodium channel activity

I initially looked at the TermGenie templates for this, but didn't see how to create the term there.  Please let me know if a template already exists, though.

Thanks,
--Kimberly

**Comment by tberardini** [comment]
I would put the term under 'cation channel activity.'

**Comment by tberardini** [comment]
Added this way:

**Comment by pgaudet** [comment]
To match changes in https://github.com/geneontology/go-ontology/issues/24455

I will change the term label to ' glycine betaine-activated nonselective monoatomic cation channel activity', and the definition

**Comment by pgaudet** [comment]
Also, add LD: 

'ligand-gated ion channel activity'
and 'has primary input' some 'glycine betaine'
and 'has primary input' some 'monoatomic cation'
