### ISSUE TITLE
NTR: positive regulation of morphogenesis of an epithelium

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12507]
as child of GO:0002009 morphogenesis of an epithelium

TG doesn't load up after login in. If this is a short-term issue and TG is up and running again soon, I can add the term myself. 

Birgit

**Comment by dosumis** [comment]
Short term TG issue. Should now be working.  Please use the regulates template to add.   Let me know if any problems.  Cheers, David

**Comment by bmeldal** [comment]
Thanks, all done!
