### ISSUE TITLE
NTR : BORC complex - BLOC-1-related complex

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#12504]
Dear GO editors,
could you please create a term describing the complex identified in PubMed:25898167, which is composed of BLOC1S1, BLOC1S2, BORCS5, BORCS6, BORCS7, BORCS8, KXD1 and SNAPIN. This complex plays a role in lysosomes movement and localization at the periphery of cells. The BORC complex recruits ARL8 at the cytosolic face of lysosomes and couple them to microtubule plus-end-directed kinesin motors.

I am not sure it is a child of  GO:0031082 BLOC complex. I let you check if it makes sense.
Thanks for your help,
Lionel

Th

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/17966662/95a431aa-6aba-11e6-9bf8-ff61b6c9b112.png)
