### ISSUE TITLE
maintenance of protein location at cell tip

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12502]
We'd like a couple of new terms to use in phenotype logical definitions:

id: GO:new1
name: maintenance of protein location at cell tip
def: A process in which a protein is maintained in a location at the cell tip. [GOC:mah, PMID:?]
is_a: GO:0032507 ! maintenance of protein location in cell
relationship: part_of GO:1990151 ! protein localization to cell tip (based on existing ontology structure)
synonym: "maintenance of protein localization to cell end" EXACT [GOC:mah]
synonym: "maintenance of protein location at cell end" EXACT [GOC:mah]
synonym: "protein anchoring at cell end" RELATED [GOC:vw]

id: GO:new2
name: maintenance of protein location at growing cell tip
def: A process in which a protein is maintained in a location at the growing cell tip. [GOC:mah, PMID:24146635]
is_a: GO:0032507 ! maintenance of protein location in cell
relationship: part_of GO:1902486 ! protein localization to growing cell tip
synonym: "maintenance of protein localization to growing cell end" EXACT [GOC:mah]
synonym: "maintenance of protein location at growing cell end" EXACT [GOC:mah]
synonym: "protein anchoring at growing cell end" RELATED [GOC:vw]

I'll ask @ValWood for a PMID for the first one.

(I checked TermGenie, but the template only offers protein localization and establishment of protein localization.)

One other thing: the terms under maintenance of protein location (GO:0045185) use a mix of "location" and "localization". I don't have a preference between them, but making them consistent one way or the other might be nice.

**Comment by mah11** [comment]
from Val, for GO:new1 - PMID:12894167

**Comment by dosumis** [comment]
Added.  Forgot to close ticket:

GO:0099017 ; maintenance of protein localization at cell tip
GO:0099019 ; maintenance of protein localization at growing cell tip
