### ISSUE TITLE
gluconate pathway terms, question

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12500]
I am trying to annotate S.p gluconate pathway enzymes.
The best term I can find is
"gluconate catabolic process', but really this pathway  seems to be an alternative way to catabolise glucose (isn't gluconate  just an intermediate?).

Would it be better to call this 
"glucose catabolism via gluconate" synonym "gluconate pathway"?

**Comment by dosumis** [comment]
Hi Val, Do you have some references I can look at on this?

CC @ukemi - Any opinion on this one?  Looks like your area of expertise.

**Comment by ValWood** [comment]
I was annotating
http://www.ncbi.nlm.nih.gov/pubmed/7840612

I wonder if it is OK  as it is because  gluconate can support growth so it isn't only a pathway intermediate. I can't remember what the decision was wen annotating pathways. It seems this could be
glucose catabolism via gluconate
and
gluconate catabolism

**Comment by ValWood** [comment]
@ukemi  need your input

**Comment by deustp01** [comment]
[Term]
id: GO:0061688
name: glycolytic process via Entner-Doudoroff Pathway
namespace: biological_process
def: "A glycolytic process in which the glucose is catabolized to pyruvate by first entering the Entner-Doudoroff pathway to yield pyruvate and glyceraldehyde-3-phosphate. The glyceraldehyde-3-phosphate is subsequently converted to pyruvate by the core glycolytic enzymes." [GOC:dph, PMID:9657988]
is_a: GO:0006096 ! glycolytic process
intersection_of: GO:0006096 ! glycolytic process
intersection_of: starts_with GO:0061678 ! Entner-Doudoroff pathway
created_by: dph
creation_date: 2015-03-12T14:39:00Z

**Comment by ValWood** [comment]
Thankyou!
would 
"gluconate pathway" be a suitable synonym?

**Comment by ukemi** [comment]
synonym added
