### ISSUE TITLE
GOGAT activity [EC:1.4.1.13]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12503]
GOGAT activity 
is a synonym of
GOGAT activity [EC:1.4.1.13]
GO:0004355 - glutamate synthase (NADPH) activity 

but I think it should also be a  synonym of
(GOGAT: EC 1.4.1.14--gluta- mine-oxoglutarate aminotransferase PMID:7773104) 

glutamate synthase (NADH) activity GO:0016040 

?

**Comment by mah11** [comment]
EC has "GOGAT" as an "other name" for 1.4.1.13 and  "NADH: GOGAT" for 1.4.1.14.

GO:0016040 has 

    synonym: "NADH: GOGAT" RELATED [EC:1.4.1.14]

i.e. without "activity" appended, and the scopes aren't consistent between GO:0016040 and GO:0004355.

**Comment by dosumis** [comment]
As the string GOGAT is already in the synonyms for both - any decent search system should be able to find both term if a user searches with GOGAT +  the existing synonyms follow EC. I see no reason to tinker.

**Comment by ValWood** [comment]
Isn't only one of them GOGAT? I really struggled figuring out which one was the correct one to use her. I think something needs fixing somewhere...

**Comment by dosumis** [comment]
> Isn't only one of them GOGAT? I really struggled figuring out which one was the correct one to use here.

![image](https://cloud.githubusercontent.com/assets/112839/17967067/22301542-6abd-11e6-8b9b-2dea440591d4.png)
![image](https://cloud.githubusercontent.com/assets/112839/17967077/3086774e-6abd-11e6-86e9-2a3ab0735100.png)

>  I think something needs fixing somewhere...

PomBase search?

**Comment by ValWood** [comment]
I was searching QuickGo.

I think I know what the fixes are needed
1)  GO:0004355 remove "activity" from  exact	GOGAT activity
2) GO:0016040 has related	NADH: GOGAT (why not exact?)
3)  The relationship types are inconsistent.
Probably it should be more accurately

GO:0004355  exact	NADPH: GOGAT   broad GOGAT
GO:0016040 exact	NADH: GOGAT broad GOGAT

**Comment by dosumis** [comment]
They both show up in QuickGO:

![image](https://cloud.githubusercontent.com/assets/112839/17968427/b511cd9a-6ac4-11e6-9dab-a8eb8523befb.png)

Have upted:
GO:0004355 exact NADPH: GOGAT
GO:0016040 exact NADH: GOGAT

+ general term as broad synonym for both

**Comment by mah11** [comment]
I don't think Val's point was about showing up in any give search; it's that the synonym strings and scopes looked inconsistent.

Your most recent synonym edits are a big improvement.

**Comment by ValWood** [comment]
Yep I remember I was confused because I didn't  know there were 2 GOGATs, it was a pre-sequence paper and they just called it GOGAT, 
I checked the first one and it was 'exact' so I did not look at the other one initially. The synonym scopes are important.

**Comment by dosumis** [comment]
OK. Got it.  So long as everybody's happy...
