### ISSUE TITLE
question about ammonia assimilation/ nitrogen utilization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12501]
should
 GO:0019676 - ammonia assimilation cycle
Definition: "The pathway by which ammonia is processed and incorporated into a cell. In an energy-rich (glucose-containing), nitrogen-poor environment, glutamine synthetase and glutamate synthase form an ammonia assimilatory cycle, in which ammonia is incorporated into L-glutamate to form L-glutamine, which then combines with alpha-ketoglutarate to regenerate L-glutamate. This ATP-dependent cycle is essential for nitrogen-limited growth and for steady-state growth with some sources of nitrogen." [

be a descendant of

Ontology term: GO:0019740 - nitrogen utilization 
Definition: "A series of processes that forms an integrated mechanism by which a cell or an organism detects the depletion of primary nitrogen source, usually ammonia, and then activates genes to scavenge the last traces of the primary nitrogen source and to transport and metabolize alternative nitrogen sources. The utilization process begins when the cell or organism detects nitrogen levels, includes the activation of genes whose products detect, transport or metabolize nitrogen-containing substances, and ends when nitrogen is incorporated into the cell or organism's metabolism.

?

**Comment by dosumis** [comment]
Agree.  Have added.  (Nitrogen utilization now has one subclass!  I suspect many missing.  No logical def so will have to be populated by hand (unsustainable, but so it goes).  Any other obvious missing subclasses ?)

**Comment by ValWood** [comment]
This as the only one I spotted  (I think from memory this was from gene products not being slimmed), so if I spot any others after our next update I'll request...
