### ISSUE TITLE
NTR: histone-dependent DNA binding?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12506]
I am wondering if it was justified to add the above term for PMID:11691835 (F3)?

The RSF complex only binds to DNA IF it first binds to the histone octomer. For the time being we annotate to GO:0003677 DNA binding.

If you think this warrants a new term I will add a def and relationships!

Thanks, 
Birgit

**Comment by dosumis** [comment]
> I am wondering if it was justified to add the above term for PMID:11691835 (F3)?

Seems reasonable to me.  I've added:

![image](https://cloud.githubusercontent.com/assets/112839/17966060/97634b0a-6ab7-11e6-8535-8493e0a9a8b2.png)

**Comment by bmeldal** [comment]
Thanks, what's the ID?

**Comment by bmeldal** [comment]
And: is it also is_a GO:0042393 histone binding?

**Comment by dosumis** [comment]
GO:0099077

> And: is it also is_a GO:0042393 histone binding?

Could use 'causally downstream of' ?

**Comment by bmeldal** [comment]
Thanks. 

I don't have the full list or the RO - I have to trust your judgement but I guess it won't propagate...
