### ISSUE TITLE
endoplasmic reticulum queries (and NTR for lumen terms)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12505]
There are some terms around here  that I don't really understand....

There is a term
"endoplasmic reticulum subcompartment"
" descendant of "endoplasmic reticulum part"

then there are quite a few terms like
"perinuclear endoplasmic reticulum membrane"
which sound as though they belong here, but are not...

There are also terms like "membrane stack"  (no annotations)
A configuration of endoplasmic reticulum (ER) found in Purkinje cells in the cerebellum and in axons in the lateral vestibular nucleus, consisting of parallel and interconnecting tubules whose outer surfaces are covered by particles or ringlike structures. Source: NIF_Subcellular:sao2114874506, ISBN:01950657191

Isn't this just 'rough ER' in a specific cell-type? (the definition seems to be this ...the ER is defined as tubules and cisternae). There are a few terms like this too....

**Comment by ValWood** [comment]
Also for the paper I am annotating I need 2 new term

perinuclear endoplasmic reticulum lumen
cortical endoplasmic reticulum lumen
I can  do these in term genie, but 

it is defined:
A cortical network of highly dynamic tubules that are juxtaposed to the plasma membrane and undergo ring closure and tubule-branching movements. Source: GOC:se, PMID:10931860, PMID:17686782


Probably, this should just be defined as an ER with a  cortical location  (I don't know what the second part  "undergo ring closure and tubule-branching movements" means, but it sounds as though it could be an organism, or even cell type specific  differentia......

**Comment by dosumis** [comment]
> There is a term
> "endoplasmic reticulum subcompartment"
> " descendant of "endoplasmic reticulum part"

> then there are quite a few terms like
> "perinuclear endoplasmic reticulum membrane"
> which sound as though they belong here, but are not...

The definition of 'endoplasmic reticulum subcompartment' needs improving.  It is intended to refer to subdivisions ER having most of the structure of the full ER.  It is not a superclass of membranes.

I can add the lumen terms (No TG template available as pattern is not always safe).

**Comment by ValWood** [comment]
OK, thanks

**Comment by ValWood** [comment]
I can add these via free-form, I'd like to get this session through (or is that not safe?)

**Comment by ValWood** [comment]
Note to self, I put this session through, waiting for the lumen terms
curs/3aac4505bb3ec2e8

**Comment by dosumis** [comment]
Lumen terms added: 

GO:0099020 ; perinuclear endoplasmic reticulum lumen
GO:0099021 ; cortical endoplasmic reticulum lumen

**Comment by dosumis** [comment]
The membrane stack term seems to come from a classic neuron ultrastructure book https://books.google.co.uk/books/about/The_fine_structure_of_the_nervous_system.html?id=eapqAAAAMAAJ&redir_esc=y

The term originally came from NIF/SAO http://neurolex.org/wiki/Category:Membrane_Stack

Wondering whether it corresponds to the cisternal stack described here:  http://www.ncbi.nlm.nih.gov/pubmed/8386750
But this is described as smooth.

Will keep for now.

**Comment by dosumis** [comment]
"The yeast ER consists of a cortical network juxtaposed to the PM (cortical ER) with tubular connections to the nuclear envelope (nuclear ER)."  PMID:17686782 

"a dynamic network of interconnecting membrane tubules" PMID:10931860 
"Video microscopy of mammalian cells revealed three types of movement of the ER: tubule branching, ring closure (the contraction of a loop of ER to a single tubule), and tubule sliding (the movement of a junction of ER tubules along a tubule; Lee and Chen 1988). Similar movements occur in S. cerevisiae." PMID:10931860 

So - looks like the more detailed def is justified as dynamic nature and types of movements conserved.  I'll add a comment recording the evidence for this.

**Comment by dosumis** [comment]
Fixed
