### ISSUE TITLE
OTR:extracellular matrix relationship with extracellular region part

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12508]
Would it be possible to make extracellular matrix a child (is a) of  extracellular region part?

**Comment by ValWood** [comment]
"Note that this term is intended to annotate gene products that are not attached to the cell surface. "

This has often caused confusion. It would be better if this comment could be included in the definition

**Comment by hattrill** [comment]
It is included in the comment for extracellular region GO:0005576, but not 'extracellular region part' GO:0044421
- proteinaceous extracellular matrix GO:0005578 is a child of extracellular region part GO:0044421- so is this incorrect?

**Comment by ValWood** [comment]
Well one is ;)

**Comment by dosumis** [comment]
Old issue around the use of ECM to refer to plant ECM which includes cell walls + definition of cell in GO to include material outside the PM (cell walls etc).  Pretty sure we agreed to stop use OF ECM for plants some time ago.  Will look into it.

But - for Drosophila, you should be using proteinaceous ECM anyway.

**Comment by hattrill** [comment]
I was just poking around a slim, trying to work out how to get all the extracellular stuff under one heading when I came across the ECM issue!
yes - plant ECM GO:0048196 was made obsolete.

**Comment by dosumis** [comment]
Given that we no longer have to account for plants, I've moved the part relationship to extracellular region up to the general ECM class.  For Drosophila, you should still use the more specific term 'proteinaceous ECM'.

**Comment by hattrill** [comment]
Yay! This will solve my slimming issues! I shall endeavour to use proteinaceous ECM in curation!
Thanks.
