### ISSUE TITLE
 difference between clatrin-mediated and receptor mediated

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12509]
receptor-mediated endocytosis
An endocytosis process in which cell surface receptors ensure specificity of transport. A specific receptor on the cell surface binds tightly to the extracellular macromolecule (the ligand) that it recognizes; the plasma-membrane region containing the receptor-ligand complex then undergoes endocytosis, forming a transport vesicle containing the receptor-ligand complex and excluding most other plasma-membrane proteins. Receptor-mediated endocytosis generally occurs via clathrin-coated pits and vesicles.

has descendant
—clathrin-mediated endocytosis
An endocytosis process that begins when material is taken up into clathrin-coated pits, which then pinch off to form clathrin-coated endocytic vesicles.

This arrangement looks a little odd.

The paper I am approving says:
Many proteins participate in the different aspects of CME including endocytosis site selection, cargo recruitment, coat assembly, membrane curvature, actin polymerization and vesicle scission (Doherty and McMahon, 2009).
So it seems that there should be child terms 

clathrin mediated endocytosis
—clathrin mediated endocytosis site selection
—clathrin mediated endocytosis cargo recruitment
—clathrin mediated endocytosis clathrin coat assemby
—clathrin mediated endocytosis membrane curvature
—clathrin mediated endocytosis actin polymerization
—clathrin mediated endocytosis vesicle scission

However, receptor-mediated endocytosis  is defined as the “cargo recruitment” step which is a part of the process.

I’m going to TG the specific clathrin mediated terms if I need them here, but I wanted to point out the logical inconsistency in the parentage. 

Probably  the clathrin mediated endocytosis def could be improved too.....

**Comment by ValWood** [comment]
They seem to be the same thing?
https://en.wikipedia.org/wiki/Receptor-mediated_endocytosis

the other type is
 receptor-independent endocytosis
calveolin-mediated endocytosis
https://en.wikipedia.org/wiki/Caveolin

(calveolin is not present in fungi and so should have taxon restrictions)

**Comment by ValWood** [comment]
and....
calveolin mediated endocytosis is under 
receptor mediated endocytosis
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0072583

**Comment by ValWood** [comment]
ooh this is a big mess.....

**Comment by dosumis** [comment]
So the questions seem to be:

(a) Is clathrin-mediated endocytosis always receptor mediated?  Wikipedia says yes, but I wouldn't expect it to capture odd exceptions.
(b) Is Caveolin-mediated endocytosis also receptor mediated?
(c) What constitutes the start/end/parts of (receptor/clathrin mediated endocytosis).  While defs could be clearer, I don't think it is justified to say that the current def of receptor-mediated endocytosis refers fo the 'cargo recruitment step'  It's just that this is one of its major differentia.  The genus *endocytosis* is clearly stated at the start of the def, it is defined as: "A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a small region of the plasma membrane to form a new membrane-bounded vesicle."  I agree that the partonomy needs some tidying up though.  There's a distinct absence of general terms for the steps in endocytosis.

**Comment by dosumis** [comment]
> I’m going to TG the specific clathrin mediated terms if I need them here

Via Involved in?

**Comment by ValWood** [comment]
yep part_of.

clathrin-mediated is always receptor mediated. 
All of the reviews above agree (the mechanism isn't fully elucidated, there are a number of proposed models)

(Hirst et al., 2011; http://www.ncbi.nlm.nih.gov/pubmed/22022230

Godlee and Kaksonen, 2013 http://www.ncbi.nlm.nih.gov/pubmed/24322426 the figures in this recent review are the most useful)

They have to be receptor mediated as the clathrin is linked to a receptor via the adaptor complex. Thats the same in all the models.

**Comment by ValWood** [comment]
see also 
https://github.com/geneontology/go-ontology/issues/12510

**Comment by ValWood** [comment]
The membrane invagination part should also pull in this ticket. There are lots of processes which use similar mechanisms for membrane invagination... with slightly different names...tubulation,  spore membrane bending pathway, curvature etc .but they are not connected in the graph.
https://github.com/geneontology/go-ontology/issues/12387
A parent membrane invagination could be a useful grouping term for all of these.

**Comment by ValWood** [comment]
PMID:26749213 has a nice summary of the steps in the intro

we should also consider this term.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000147
  This probably needs to be revisited. The 'actin cortical patch' is a  'low resolution' structure'
and represents 'an actin structure at the endocytic sites' It is now clear that ALL of the annotations to this  term represent  sub parts of the endocytic process.

For example SYP1 an early arriving protein, is annotated to "actin cortical patch assembly"
http://www.yeastgenome.org/locus/YCR030C/overview
at SGD (and ISS'd  to by PomBAse).  But the description is
Negative regulator of WASP-Arp23 complex; involved in endocytic site formation; 

It might be a time to lose all of the 'actin cortical patch' related   terms from GO (only used by fungi), and remap to the endocytic sub processes and more appropriate component terms.

**Comment by ValWood** [comment]
I have feedback from the author/curator of this paper 
https://curation.pombase.org/pombe/curs/d5e1616053c30a60/ro/
that 

Henar:
Yes, clathrin-mediated endocytosis and receptor-mediated endocytosis are the same thing, so the terms can be merged.

**Comment by RLovering** [comment]
I am a bit concerned about this. I really don't have time to look at this today, or for a couple of weeks. I realise this book is a bit old but https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&ved=0ahUKEwizqc_-3_PNAhXjAsAKHWsaB6EQFgg9MAM&url=http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fbooks%2FNBK21639%2F&usg=AFQjCNEXuTyxdZh0meuAZzBUq-V-IuJXKQ&sig2=xaXABQpL_mbR8dCLVuXDVQ suggests: Small invaginations of the plasma membrane termed caveolae, lined with the membrane protein caveolin, contain some receptor proteins and are used for certain types of receptor-mediated endocytosis. However, receptor-mediated endocytosis generally occurs via clathrin-coated pits and vesicles (Figure 17-44). 

And http://www.jbc.org/content/286/10/8231.long (again a bit old 2011) states: two main pathways have been identified for receptor-mediated endocytosis: the clathrin-dependent and the caveolae/lipid raft-dependent endocytic pathways (1, 2). Clathrin-dependent endocytosis is the most well characterized mechanism for mediating the internalization of membrane receptors into cells. It is also important for intracellular trafficking at the trans-Golgi network and endosomes (3). Caveolae/raft-dependent endocytosis is involved in multiple biological processes, including mediating virus entry into host cells, internalizing glycophosphatidylinositol-anchored proteins and regulating certain signaling cascades. Caveola are cholesterol and sphingolipid-rich plasma membrane invaginations of a diameter of 60–80 nm, of which caveolin-1 is the main protein component required for caveola biogenesis (4). 

Also supported by wikipedia (fab) endocytosis page: Uptake of extracellular molecules is also believed to be specifically mediated via receptors in caveolae.

Please DON'T merge clathrin-mediated endocytosis and receptor-mediated endocytosis

happy holidays for me.....

Ruth

**Comment by ValWood** [comment]
OK, no hurry.
I think the first thing is to figure out what is meant by receptor-mediated in this context...
My understanding is that the receptor is an integral part of the mechanism, and is used to assembly the  clathrin apparatus in clathrin-mediated endocytosis:
https://en.wikipedia.org/wiki/Receptor-mediated_endocytosis

For calveolin mediated, the mechanism seems less clear,  there are probably more recent reviews
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2723140/

But the receptor-mediated seems less useful as a classifier than what the actual mechanism is
(clathrin-mediated, calveolin mediated etc)....

Note, caveolin-mediated endocytisis is currently a child of receptor mediated endocytosis, and this seems to be  definitely not always true?


VAl

**Comment by mcourtot** [comment]
I also found this http://www.nature.com/nrm/journal/v16/n5/full/nrm3968.html

They seem to indicate (figure 3) that receptor-mediated endocytosis can also occur without clathrin: "Model for Shiga toxin-driven membrane bending is shown. Shiga toxin binds to its cellular receptor, the glycosphingolipid (GSL) globotriaosylceramide (Gb3), and reorganizes membrane lipids to favour membrane bending without the need for cytosolic clathrin"

I like the idea of dividing using the mechanism. 

Maybe @paolaroncaglia knows more? (tagging even though she's on vacation atm)

**Comment by dosumis** [comment]
> But the receptor-mediated seems less useful as a classifier than what the actual mechanism is (clathrin-mediated, calveolin mediated etc)....

I'm pretty sure we need both. Still reading around this, but seems pretty clear that caveolin-mediated endocytosis is not always triggered by receptors, so we should probably split this class into receptor-mediated and a more general class.  We should also make the receptor-mediated (triggered?) nature of clathrin-mediated endocytosis clearer in the definition.

**Comment by ValWood** [comment]
OK sounds good.

**Comment by dosumis** [comment]
I have moved 'caveloin-mediated endocytosis' up to be a direct subclass of endocytosis.  @RLovering  - happy to add a more specific subclass 'receptor/caveolin mediated endocytosis' if you think that is warranted.

Cheers,
David
