### ISSUE TITLE
TPV: protein localization to endosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12519]
Is a child of
protein localization to vacuole !!!!?

**Comment by ValWood** [comment]
and endosome is a child of vacuole.

It seems that the def was changed quite recently.....
Timestamp	Action	Category	Detail
2016-04-17	Deleted	DEFINITION	A membrane-bounded organelle to which materials ingested by endocytosis are delivered.
2016-04-17	Added	DEFINITION	A vacuole to which materials ingested by endocytosis are delivered.
2016-04-17	Added	RELATION	is a GO:0005773 (vacuole)

Please fix.....

**Comment by ValWood** [comment]
terms like this no longer make sense
late endosome to vacuole transport via multivesicular body sorting pathway

**Comment by ukemi** [comment]
HI Val. 

I am reopening #12264. Can you please comment on that?

-D

**Comment by ValWood** [comment]
Hi,

I don't think an endosome is a lysosome?
An endosome is a transport vesicle https://en.wikipedia.org/wiki/Endosome
A lysosome is lytic.
See #12264

maybe confusing with GO:0036019 endolysosome?  (which I only knew existed about 10 seconds ago!)

Val
