### ISSUE TITLE
polynucleotide adenylyltransferase activity relations and def

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12516]
polynucleotide adenylyltransferase activity
Catalysis of the template-independent extension of the 3'- end of an RNA or DNA strand by addition of one adenosine molecule at a time. Cannot initiate a chain 'de novo'. The primer, depending on the source of the enzyme, may be an RNA or DNA fragment, or oligo(A) bearing a 3'-OH terminal group.

GO:0004654 polyribonucleotide nucleotidyltransferase activity
Catalysis of the reaction: ATP + RNA(n) = diphosphate + RNA(n+1).

and both are true for the activity of my gene product.
Do I need polyribonucleotide adenylyltransferaseactivity?

 maybe there should be a general  nucelodide/ribonucleotide term with specific terms for RNA or DNA?

**Comment by mah11** [comment]
GO:0004654 is named as though it's not specific for any particular nucleotide, but the reaction in the definition specifies ATP. I don't know whether the name or text def should change (the def could use NTP to be generic).

**Comment by ValWood** [comment]
oh yeah....name and def don't match....

**Comment by ukemi** [comment]
Looks like there was an error in the definition. The EC entry that is used as a crossref says that the reaction uses a nucleotide diphosphate. If I correct the def, will that work for you?

**Comment by ValWood** [comment]
I'm still confused!
These are the options:

![still confused](https://cloud.githubusercontent.com/assets/7359272/16591115/5d3d388a-42d2-11e6-9cc5-aa9cc91c0ccc.jpg)

**Comment by ValWood** [comment]
OK I get it now. we  use polynucleotide to refer  to both  ribonucleotide/deoxyribonucleotide

polyribonucleotide to refer to RNA nucleotide

some of the synonyms are mixed up

exact	RNA adenylating enzyme activity isn't exact for GO:0004652
it's exact for the descendant  GO:1990817 RNA adenylyltransferase activity

GO:1990817 RNA adenylyltransferase activity
should be a descendant of GO:0004654 too?

-

**Comment by ValWood** [comment]
This isn't all...
Once that part is resolved, Now I'm back to where I started looking.

tRNA adenylyltransferase activity
is defined
Catalysis of the reaction: ATP + tRNA(n) = diphosphate + tRNA(n+1).

it should be a descendant of 
GO:1990817 RNA adenylyltransferase activity

GO:0004810 tRNA adenylyltransferase activity
has a descendant
GO:0052929	ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity


GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity
is not a descendant of 
GO:0009022 tRNA nucleotidyltransferase activity

in fact this term has NO children

Probably logical definitions are the only way forward here......
its really, really confusing!

**Comment by ValWood** [comment]
GO:0004654 is wrong in many ways. The EC 2.7.7.19 it appears to be derived from refers to 
RNA(n+1) + phosphate <=> RNA(n) + a nucleoside diphosphate

GO is
ATP + RNA(n) = diphosphate + RNA(n+1). 

One uses ATP and one uses ADP

In addition to the above.

Solution fix definition?
Has 4 EXP annotations. Check the EC is what you meant 
@tberardini 
@jimhu-tamu

**Comment by tberardini** [comment]
Thanks for the heads up, Val, but the Arabidopsis annotations are from UniProt so I cannot change them.  @mcourtot, who do we contact for UniProt annotation checking?  Thanks.

**Comment by ValWood** [comment]
We suspect that  these all meant  	2.7.7.8 which is the EC number 
If this is the case the def can be changed.

**Comment by mcourtot** [comment]
Those were made by SIB curators - easiest way is to raise a question/dispute via P2GO. Maybe just ask them to check they indeed meant EC 2.7.7.8. (I suspect yes)?
@ValWood do you want to do this via P2GO? Otherwise I'll do it tomorrow.

**Comment by ValWood** [comment]
Could you raise the UniProt ones? I was hoping to get to it but I'm heading north tomorrow for a funeral and this one didn't make it...I didn't record the accession numbers so there is a bit of back-tracking.

Cheers,

Val

**Comment by mcourtot** [comment]
Done - I emailed them via P2GO.

**Comment by mcourtot** [comment]
Andre Stutz from SIB confirmed that
 "The definition of the catalytic reaction given in the GO term
should be changed to :
RNA(n+1) + phosphate <=> RNA(n) + a nucleoside diphosphate   (EC=2.7.7.8) 

Once you will update the GO term catalytic reaction definition, my GO annotation will be correct.
Cheers,
Andre stutz"

**Comment by ukemi** [comment]
I fixed the definition as described above.
