### ISSUE TITLE
NTR:translation elongation factor binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12513]
Could I request:
translation elongation factor binding
child of GO:0005515 protein binding

def: Interacting selectively and non-covalently with a translation elongation factor, any polypeptide factor involved in the peptide elongation in ribosome-mediated translation. 

Thanks

**Comment by ukemi** [comment]
[Term]
+id: GO:0061770
+name: translation elongation factor binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a translation elongation factor, any polypeptide factor involved in the peptide elongation in ribosome-mediated translation." [GOC:dph]
+is_a: GO:0005515 ! protein binding
+created_by: dph
+creation_date: 2016-07-09T09:31:11Z
