### ISSUE TITLE
Golgi stack/ Golgi cisternae, what is the difference?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12514]
GO:0005795
Name	Golgi stack
Definition	The set of thin, flattened membrane-bounded compartments, called cisternae, that form the central portion of the Golgi complex. The stack usually comprises cis, medial, and trans cisternae; the cis- and trans-Golgi networks are not considered part of the stack.

and
Golgi cisterna
Definition	Any of the thin, flattened membrane-bounded compartments that form the central portion of the Golgi complex.

are the the same thing?
I prefer “Golgi cisterna” as the term name

**Comment by mah11** [comment]
The text definitions and the part_of link say what the difference is: each cisterna is part of the stack. The stack is made of more than one cisterna (usually three).

**Comment by ValWood** [comment]
OK, I was reading it as the stack is  "cis, medial, and trans cisternae", therefore the stack *is* cisternae.....

A stack is multiple 'cisterna'...got it....
