### ISSUE TITLE
multi-organism process term tweaks

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12517]
I've been using the MOP terms a bit recently in annotation, and have a few suggested minor edits:
1. multi-organism cellular localization ; GO:1902581 is missing the parent: multi-organism cellular process ; GO:0044764
2. Definition of 'modulation by host of viral exo-alpha-sialidase activity ; GO:0044866' needs tweaking so it refers to 'a change in VIRAL exo-alpha-sialidase activity' not 'a change in SYMBIONT exo-alpha-sialidase activity'.
3. New synonyms for ‘symbiont-containing vacuole ; GO:0020003
   pathogen-occupied vacuole [PMID:24034612]
   narrow synonym: Salmonella-containing vacuole [PMID:24034612, PMID:10449405 ]
   SCV [PMID:24034612, PMID:10449405]
   bacterium-containing vacuole [PMID:22042847]
4. Not sure I understand these two terms:
   movement in symbiont environment ; GO:0052193
   movement on or near symbiont ; GO:0052194
   I wonder if they were just created to have complete host-symbiont pairs, and should in fact be obsoleted. They have 0 annotations.

Thanks!

**Comment by pgaudet** [comment]
These were all done except two synonyms missing: pathogen-occupied vacuole [PMID:24034612]
and bacterium-containing vacuole [PMID:22042847]

I added the synonyms, closing the issue. 

Pascale
