### ISSUE TITLE
NTR:response to microsporidia

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12511]
Hi,
I'd like to request a new child term of response to other organism, response to microsporidia, to annotate genes involved in C. elegans' response to these intracellular pathogens.

GO:0051707 response to other organism
-GO:new response to microsporidia

Suggested def: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus from microsporidia, a large class of eukaryotic intracellular parasites.

References: PMID:19071962, PMID:24945527

Thanks,
--Kimberly

**Comment by dosumis** [comment]
Done.
