### ISSUE TITLE
update def GO:0030122 - AP-2 adaptor complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12510]
Definition: "A heterotetrameric AP-type membrane coat adaptor complex that consists of alpha, beta2, mu2 and sigma2 subunits, and links clathrin to the membrane surface of a vesicle; vesicles with AP-2-containing coats are normally found primarily near the plasma membrane, on endocytic vesicles. In at least humans, the AP-2 complex can be heterogeneric due to the existence of multiple subunit isoforms encoded by different alpha genes (alphaA and alphaC)." [GOC:mah, PMID:10611976, PMID:21097499]

change to
and links clathrin to the membrane surface of a vesicle, and the cargo receptors during receptor/clathrin mediated endocytosis

(Hirst et al., 2011;  http://www.ncbi.nlm.nih.gov/pubmed/22022230

Godlee and Kaksonen, 2013 http://www.ncbi.nlm.nih.gov/pubmed/24322426)

Later papers

**Comment by dosumis** [comment]
Fixed
