### ISSUE TITLE
drug transport across blood-nerve barrier

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12524]
I would like to see "drug transport across blood-nerve barrier" added to the GO ontology under the parent term "drug transport" (GO:0015893).  The definition could be "The directed movement of drugs passing through the blood-nerve barrier."  An example can be found in PMID:22733753. A synonym would be "drug transport across perineurial barrier".

**Comment by ukemi** [comment]
[Term]
+id: GO:0061772
+name: drug transport across blood-nerve barrier
+namespace: biological_process
+def: "The directed movement of drugs passing through the blood-nerve barrier." [GOC:dph, PMID:22733753]
+synonym: "drug transport across perineurial barrier" EXACT [PMID:22733753]
+is_a: GO:0015893 ! drug transport
+created_by: dph
+creation_date: 2016-07-09T09:59:59Z
