### ISSUE TITLE
GO:0010970 establishment of localization by movement along microtubule

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12521]
can this be renamed
transport by movement along mictotubule?
It is transport, (i.e directed movement)

All transport is part of "establishment of localization"
BUT
Not ALL "establishment of localization" is transport

(I think I got that right...)

Val

**Comment by ukemi** [comment]
Hi Val,

It has the exact synonym 'microtubule-based transport'.  I can switch that with the primary name. Do you want me to add your suggestion as a synonym?

-D

**Comment by ValWood** [comment]
NOoooo! 
It should be "microtubule-based transport" I have been moving between phenotypes and GO all day, I got confused ;)
Just a  name switch.
The current name is really a 'broad' synonym.....

**Comment by ValWood** [comment]
Scrub the synonym type comment. In this instance they  are exact if transport is the only way to establish localization my microtubules....?

**Comment by ukemi** [comment]
I think they are exact, but that means I should probably make this an is_a intracellular transport too.

**Comment by dosumis** [comment]
Note Microtubule-based transport is not necessarily movement along a microtubule.  microtubule formation on one side of an organelle can push it (from memory - don't have time right now to look up examples).

**Comment by ValWood** [comment]
You are right. I forgot what the  original term was here.

GO:0010970 establishment of localization by movement along microtubule == transport along microtubule

microtubule-based transport should be a parent. 

The question should be, is there a difference between 'microtubule-based movement' and 'microtubule-based transport'?

So are both movement along a microtubule, and movement by microtubule pushing forces are transport (?)
(I'm a bit hazy on the distinction between transport and movement, I understand the difference between transport and localization, all I know for sure is that movement along the microtubule is 'transport')

**Comment by dosumis** [comment]
> I'm a bit hazy on the distinction between transport and movement

Me too.

**Comment by ValWood** [comment]
If movement is any change in position,
and
transport is directed movement.

Q Is there any movement which is controlled by a mechanism/gene product  which would not be classed are transport ?

a) cell level
i) Movement like search and capture to locate missing chromosomes, this isn't transport. 
ii) There are also things like the  acyl carrier proteins which  can move to bring pathway intermediates into proximity, this movement is a type of localization, but it isn't transport.
So yes...

b) organism level
i) flailing limbs ?

So there is a distinction.
I'm just not clear whether "movement by microtubule based pushing forces" fits the transport def, to be transport, it needs to be 'directional'  ( which seems to be 'having a particular direction of motion).

When you push a nucleus along by microtubule based forces, the directionality is due to constraints (cell wall etc), rather than some being controlled by the microtubule pushing.

Not sure...

**Comment by ukemi** [comment]
Microtubule based movement can simply be sliding of microtubules as in a cilium. Nothing gets transported. I think this terms was really meant to capture the movement of things along the mictotublule by motors.

Def: The movement of organelles or other particles from one location in the cell to another along microtubules.

I think the primary term name can be 'transport along microtubule'

**Comment by ValWood** [comment]
Better.

**Comment by ukemi** [comment]
[Term]
 id: GO:0010970
-name: establishment of localization by movement along microtubule
+name: transport along microtubule
 namespace: biological_process
 def: "The movement of organelles or other particles from one location in the cell to another along microtubules." [GOC:dph, GOC:mah, GOC:tb]
-synonym: "microtubule-based transport" EXACT []
+synonym: "establishment of localization by movement along microtubule" EXACT [GOC:dph]
+synonym: "microtubule-based transport" BROAD []
 synonym: "movement along microtubule" EXACT []
 is_a: GO:0007018 ! microtubule-based movement
+is_a: GO:0046907 ! intracellular transport
 intersection_of: GO:0051234 ! establishment of localization
 intersection_of: results_in_transport_along GO:0005874 ! microtubule
 created_by: tanyaberardini

**Comment by dosumis** [comment]
Should probably switch intersection_of genus to transport.

**Comment by ukemi** [comment]
done
