### ISSUE TITLE
response to caloric restriction

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12523]
I would like to see "response to caloric restriction" added to the GO ontology under the parent term "response to starvation" (GO:0042594).  The new term should also be an additional parent to "cellular response to caloric restriction" (GO:0061433). The definition could be "A change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a caloric restriction, insufficient food energy intake.".  An example can be found in PMID:15520862.

**Comment by cmungall** [comment]
Surely CR is a sibling of starvation:

https://en.wikipedia.org/wiki/Calorie_restriction

> "...without incurring malnutrition..."

The grouping class could have a name that clearly signposts it's generality.

The GO classes should be axiomatized using an external experimental/environmental conditions ontology. I started one for this purpose: https://github.com/cmungall/environmental-conditions/

**Comment by slaulederkind** [comment]
That sounds good. The new parents would be "response to nutrient levels"
and "response to stress".  "cellular response to caloric restriction" would also need a similar move to the new parents "cellular response to nutrient levels" and "cellular response to stress".

**Comment by cmungall** [comment]
OK

I suggest asserting in GO for now and going back and axiomatizing. See https://github.com/cmungall/environmental-conditions/issues/1

**Comment by ukemi** [comment]
name: cellular response to caloric restriction
 namespace: biological_process
 def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a of caloric restriction, insufficient food energy intake." [GOC:dph, PMID:17914901]
-is_a: GO:0009267 ! cellular response to starvation
+is_a: GO:0033554 ! cellular response to stress
+is_a: GO:0061771 ! response to caloric restriction
 created_by: dph
 creation_date: 2012-02-09T09:03:15Z
 
@@ -403246,6 +403247,16 @@
 creation_date: 2016-07-09T09:31:11Z
 
 [Term]
+id: GO:0061771
+name: response to caloric restriction
+namespace: biological_process
+def: "A change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a caloric restriction, insufficient food energy intake." [GOC:dph, PMID:15520862]
+is_a: GO:0006950 ! response to stress
+is_a: GO:0031667 ! response to nutrient levels
+created_by: dph
+creation_date: 2016-07-09T09:40:32Z
