### ISSUE TITLE
NTR: eNoSc complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12525]
(This complex is ready for the next IntAct release)

PMID:18485871

Def: A chromatin silencing complex that recruits histone-modifying enzymes and upregulates silencing of rDNA in response to glucose starvation.

Synonym: energy dependent nucleolar silencing complex - EXACT

References:
IntAct:EBI-11789632
IntAct:EBI-11790279
GOC: BHM

Relationships:
is_a GO:0005677 chromatin silencing complex
part_of: GO:0005730 nucleolus

capable_of:
GO:0000182 rDNA binding
GO:0035064 methylated histone binding
GO:0031493 nucleosomal histone binding
GO:0031492 nucleosomal DNA binding

capable_of_part_of:
GO:0000183 chromatin silencing at rDNA
GO:0031062 positive regulation of histone methylation
GO:0031065 positive regulation of histone deacetylation
GO:0042149 cellular response to glucose starvation
GO:0045892 negative regulation of transcription, DNA-templated
GO:0046015 regulation of transcription by glucose
GO:0071158 positive regulation of cell cycle arrest
GO:2000505 regulation of energy homeostasis

Thanks,
Birgit

**Comment by ukemi** [comment]
[Term]
+id: GO:0061773
+name: eNoSc complex
+namespace: cellular_component
+def: "A chromatin silencing complex that recruits histone-modifying enzymes and upregulates silencing of rDNA in response to glucose starvation." [GOC:BHM, Intact:EBI-11789632, Intact:EBI-11790279, PMID:18485871]
+synonym: "energy dependent nucleolar silencing complex" EXACT []
+is_a: GO:0005677 ! chromatin silencing complex
+relationship: capable_of GO:0000182 ! rDNA binding
+relationship: capable_of GO:0031492 ! nucleosomal DNA binding
+relationship: capable_of GO:0031493 ! nucleosomal histone binding
+relationship: capable_of GO:0035064 ! methylated histone binding
+relationship: capable_of_part_of GO:0000183 ! chromatin silencing at rDNA
+relationship: capable_of_part_of GO:0031062 ! positive regulation of histone methylation
+relationship: capable_of_part_of GO:0031065 ! positive regulation of histone deacetylation
+relationship: capable_of_part_of GO:0042149 ! cellular response to glucose starvation
+relationship: capable_of_part_of GO:0045892 ! negative regulation of transcription, DNA-templated
+relationship: capable_of_part_of GO:0046015 ! regulation of transcription by glucose
+relationship: capable_of_part_of GO:0071158 ! positive regulation of cell cycle arrest
+relationship: capable_of_part_of GO:2000505 ! regulation of energy homeostasis
+relationship: part_of GO:0005730 ! nucleolus
+created_by: dph
+creation_date: 2016-07-09T10:12:30Z

**Comment by bmeldal** [comment]
Thanks, David.
