### ISSUE TITLE
NTRs: chromatin compaction (BP), chromatin looping (BP) & L3MBTL1 complex (CC)

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12526]
(Complexes are ready for next release)

For all terms:

PMID:17540172

References:
IntAct:EBI-11790939
IntAct:EBI-11792170
GOC:bhm

1) Def Chromatin compaction (GO:NEW1):
A process that leads to a very dense packaging of chromatin and ultimately to chromatin silencing. Aided by chromatin remodelling complexes such as the L3MBTL1 complex that recognise specific chromatin methylation sites.

2) Def Chromatin looping (GO:NEW2):
The joining up of sparsely spaced nucleosomes along otherwise naked chromatin. This process is aided by chromatin remodelling complexes such as the L3MBTL1 complex that recognise specific chromatin methylation sites.

Relationship (for both):
is_a GO:0006338 chromatin remodeling

3) Def L3MBTL1 complex:
A chromatin silencing complex involved in chromatin compaction and chromatin looping.

Relationship: 
is_a GO:0005677 chromatin silencing complex
part_of: GO:0005634 nucleus

capable_of: 

GO:0031493 nucleosomal histone binding
GO:0035064 methylated histone binding
GO:0000975 regulatory region DNA binding

capable_of_part_of: 
GO:0006342 chromatin silencing
GO:0045892 negative regulation of transcription, DNA-templated
GO:NEW1 chromatin compaction
GO:NEW2 chromatin looping

Thanks,
Birgit

**Comment by ValWood** [comment]
Hi Birgit

for "Chromatin compaction"  I think you might want 
GO:0031507 heterochromatin assembly
(or a parent or child)

Val

**Comment by ValWood** [comment]
Also
GO:0090579 dsDNA loop formation
exists.

**Comment by bmeldal** [comment]
Thanks, Val.
Didn't see the loop-formation, probably because I was looking for 'looping'...
Birgit

**Comment by bmeldal** [comment]
Still need the complexes term, please :)

with additional:
capable_of_part_of:
GO:0031507 heterochromatin assembly
GO:0090579 dsDNA loop formation

**Comment by ValWood** [comment]
Yeah I think it might be better described as "chromatin looping" than "dsDNA loop formation"! I had trouble finding it at first, but I was sure I had seen something....

**Comment by bmeldal** [comment]
@ukemi, can we add the EXACT synonym 'chromatin looping' to GO:0090579 dsDNA loop formation, please? Or even swapping at term name and the new synonym as per Val's suggestion?

**Comment by ValWood** [comment]
After seeing the paper, this looks like it might be a level of compaction which occurs after "heterochromatin assembly". I don't know much about  this as yeast don't need to compact their DNA quite  so much. I don't know what the correct term would be but it could be one of the others under DNA packaging....

**Comment by bmeldal** [comment]
Just to keep the tickets links:
https://github.com/geneontology/go-ontology/issues/12522

**Comment by ukemi** [comment]
Hi Birgit,

>>can we add the EXACT synonym 'chromatin looping' to GO:0090579 dsDNA loop formation, >>please? Or even swapping at term name and the new synonym as per Val's suggestion?

I think an exact synonym would be an error since according to the referenced publication this process can happen in both prokaryotes and eukaryotes. Maybe a related synonym?

For the L3MBTL1 complex, is this definition necessary and sufficient?
A chromatin silencing complex involved in heterochromatin assembly and chromatin looping.
Are there no other complexes that are involved in compaction and looping? If there are, then they would be annotated to this term. 

I wonder if a more generic name like 'nucleosome bridging complex' or 'chromatin lock complex' and a definition of:
A chromatin silencing complex that binds and bridges separate nucleosomal histones at gene regulatory regions resulting in heterochromatin assembly and chromatin looping.

The definition reference would be the above paper. I also wonder if the purpose of this complex is not really to loop the chromatin but rather to compact the chromatin and form heterochromatin, silencing transcription. Is the looping just something that is observed because of the way the complex works? I think this might be what Val is trying to get at above.

-D

**Comment by ValWood** [comment]
Yes, I wondered if it was an experimental artifact and how much could be inferred at this stage. Then I remember looking at the paper, and thinking that I didn't know enough about the processes required for compaction in higher euks to comment further.

**Comment by bmeldal** [comment]
Thanks, David,

>>can we add the EXACT synonym 'chromatin looping' to GO:0090579 dsDNA loop formation, please? Or even swapping at term name and the new synonym as per Val's suggestion?

>I think an exact synonym would be an error since according to the referenced publication this process can happen in both prokaryotes and eukaryotes. Maybe a related synonym?

Good point. Shall we add "dsDNA looping" [exact] and "chromatin looping" [related] or [narrow]?

As for the def of the complex, I don't know more about the biology either. I'm happy to err on the side of caution with regards to experimental artefact vs true compaction. 

What about:
Name: chromatin lock complex
synonym: nucleosome bridging complex [exact]
Def: A chromatin silencing complex that binds and bridges separate nucleosomal histones [at gene regulatory regions]* resulting in heterochromatin assembly and chromatin looping.

*do they have to be at regulatory regions? Could this occur anywhere? If we are keeping it a bit vague I wouldn't want to restrict it here.

Birgit

**Comment by ukemi** [comment]
Hi Birgit,

[Term]
+id: GO:0061793
+name: chromatin lock complex
+namespace: cellular_component
+def: "A chromatin silencing complex that binds and bridges separate nucleosomal histones resulting in heterochromatin assembly and chromatin looping." [GOC:bhm, GOC:dph, IntAct:EBI-11790939, IntAct:EBI-11792170, PMID:17540172]
+synonym: "nucleosome bridging complex" RELATED [GOC:dph]
+is_a: GO:0005677 ! chromatin silencing complex
+relationship: capable_of GO:0000975 ! regulatory region DNA binding
+relationship: capable_of GO:0031493 ! nucleosomal histone binding
+relationship: capable_of GO:0035064 ! methylated histone binding
+relationship: capable_of_part_of GO:0070869 ! heterochromatin assembly involved in chromatin silencing
+relationship: capable_of_part_of GO:0090579 ! dsDNA loop formation
+relationship: part_of GO:0005634 ! nucleus
+created_by: dph
+creation_date: 2016-09-09T13:47:27Z

It gets the other capable relations from its parents.

-D
