### ISSUE TITLE
refine definition of "cohesin loading" PMID:26687354

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12527]
cohesin loading
is defined
Definition	A process in which a cohesin complex is transported to, or maintained at, a part of a chromosome that is organized into chromatin. 

Redefine to
The process whereby  the *cohesin ring activity* https://github.com/geneontology/go-ontology/issues/12529 of the cohesin complex is enabled  to establish or maintain its localization to chromatin. This process uses ATP hydrolysis to drive the opening of the protein ring structure.

The new def is better because 
i) the loading does not involve transport, just establishment/maintenance of localization
ii) the complex which is loaded is a non-canonical  type of "DNA binding" activity 

I will request new terms for 
DNA encircling activity/DNA entrapment shortly, once I have checked with a cohesin expert....

**Comment by ValWood** [comment]
From  Frank, the author of PMID:26687354
DNA Entry into and Exit out of the Cohesin Ring by an Interlocking Gate Mechanism
Cell. 2015 Dec 17;163(7):1628-40.

For PCNA the term Œclamp¹ is very good, as it binds tightly around DNA.
Correspondingly, RFC is suitably called a 'clamp loader' ATPase

For cohesin, the term 'ring' might be better, as it is a very loose
fitting ring (there will be eventually 2 or more DNAs inside the ring,
which can never happen to PCNA). As mentioned, importantly, this ring
itself includes the ATPase.

**Comment by ukemi** [comment]
id: GO:0071921
 name: cohesin loading
 namespace: biological_process
-def: "A process in which a cohesin complex is transported to, or maintained at, a part of a chromosome that is organized into chromatin." [GOC:mah, PMID:10882066, PMID:17113138]
+def: "The process by which the cohesin ring activity of the cohesin complex is enabled to establish or maintain its localization to chromatin. This process uses ATP hydrolysis to drive the opening of the protein ring structure." [GOC:mah, PMID:10882066, PMID:17113138, PMID:26687354]
 synonym: "cohesin association with chromatin" EXACT [GOC:lb]
 synonym: "cohesin localisation to chromatin" EXACT [GOC:mah]
 synonym: "cohesin localization to chromatin" EXACT [GOC:vw]

**Comment by ValWood** [comment]
The eventual definition was changed.
Add to this ticket.

**Comment by ValWood** [comment]
The protein localization to chromatin process by which a cohesin ring complex is topologically linked to chromatin.
