### ISSUE TITLE
NTRs: cohesin ring activity / DNA clamp activity PMID:26687354 (types of DNA binding)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12529]
GONEW: DNA clamp activity
A DNA binding activity  in which a multimeric protein complex  interacts selectively and non-covalently with single  DNA duplex  to tightly entrap the DNA

GONEW: DNA ring activity
A DNA binding activity  in which a multimeric protein complex  interacts selectively and non-covalently with > 1 DNA duplex  to entrap the DNA molecules in a loose fitting ring
narrow: cohesin ring activity

These should both be both children of DNA binding and represent non-canonical DNA binding activities

**Comment by ValWood** [comment]
I started trying to  define cohesin as a clamp, but it clearly isn't. This is how I arrived at these 2 terms:

Hmm, I can see that it is at first sight appealing to compare PCNA and
cohesin, both are ring-shaped assemblies that encircle DNA. However, the
PCNA ring is about 1/10th the molecular weight of cohesin, it¹s diameter
is less than 1/15th that of cohesin. PCNA is a passive ring, which needs a
clamp loader ATPase to be loaded onto DNA. Cohesin, in contrast, is itself
the ATPase, while the cohesin loader passively facilitates a
conformational change. There is no sequence nor any other similarity
between the two. Even the ATPases are from different families and the
mechanisms for getting on and off DNA are unrelated. So all in all, I
think it would be better to treat the two systems separately.

For PCNA the term Œclamp¹ is very good, as it binds tightly around DNA.
Correspondingly, RFC is suitably called a Œclamp loader¹ ATPase

For cohesin, the term Œring¹ might be better, as it is a very loose
fitting ring (there will be eventually 2 or more DNAs inside the ring,
which can never happen to PCNA). As mentioned, importantly, this ring
itself includes the ATPase.

As far as unifying GO terms goes, it is now clear that also condensin
(Cut3, Cut14, Cnd1, Cnd2, Cnd3) and the Smc5/Smc6 complex (Smc5, Smc6,
Nse1, Nse2, .. Nse6) are rings that encircle DNA. So maybe the DNA ring GO
term can be applied to these?

**Comment by ValWood** [comment]
or 'ringing?'

We need MF terms for these  SMC complexes for LEGO, at the moment their molecular functions  are 
not indicating their roles in the processes.

**Comment by ValWood** [comment]
ring seems to be the correct terminology http://www.sciencedirect.com/science/article/pii/S0092867405007488

**Comment by ValWood** [comment]
I'm not sure whether this terms should be
DNA ring activity (it sounds odd) as a general term for the SMC-type ring DNA binding activities.
They are usually called "cohesin ring" etc

If we go for a general term to represent this class of DNA binding, is there a better name?

**Comment by ValWood** [comment]
SMC ring-type DNA binding?
(this sounds better than DNA ring, because its the protein complex which forms the ring which encircles the DNA)
narrow synonym cohesin ring

**Comment by ValWood** [comment]
This is to confirm that these should be classified as DNA binding activities:

frank:
yes, I would say 'DNA binding’ is still a correct term. It’s loose but
very stable, with a turnover in many minutes/hours, much more stable than
most other DNA binding proteins (transcription factors, heterochromatin
proteins, etc., ) that all turn over much more rapidly.

**Comment by ValWood** [comment]
Final def
The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring.

**Comment by ValWood** [comment]
Fron Frank Uhlmann:

GO molecular function
GO:0061776 ŒDNA ring activity¹, would ŒDNA topological embrace¹ be a
better description? Otherwise it remains unclear what the 'ring activity'
is about?

If Frank finds this name confusing, it isn't good!
can we work with his new suggestion

Maybe 
"DNA topological encircling activity"
any other suggestions?
I can run these by him...

**Comment by ValWood** [comment]
Frank did not get back to me on this yet.
Can we go with 
DNA encircing, which is better than DNA ring, and  closer to Frank's suggestion so we can close.  If a better suggestion materialises easy to update.

**Comment by ValWood** [comment]
Hi David.  
I didn't hear back from Frank yet on this particular question. However, from the title of this paper
An In Vitro Assay for Monitoring Topological DNA Entrapment by the Chromosomal Cohesin Complex. Murayama Y, Uhlmann F.
Methods Mol Biol. 2017;1515:23-35.
PMID: 27797071

I vote we go with  "topological DNA entrapment activity"  for now as this is used in a few papers already.

**Comment by ukemi** [comment]
Val,

You originally requested two terms in this ticket. Do you want the clamp activity as originally stated and the ring activity to be the  "topological DNA entrapment activity"?

-D

**Comment by ValWood** [comment]
Oh I forgot about that.
Well I don't need it right now, so it could wait....will need it at some point  when can probably do a better job with defs.

**Comment by ukemi** [comment]
Hi Val,

What do you want me to do with this request? Do you want:

GONEW:topological DNA entrapment activity
The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring.
PMID: 27797071

GONEW: DNA clamp activity
A DNA binding activity in which a multimeric protein complex interacts selectively and non-covalently with single DNA duplex to tightly entrap the DNA.
PMID:26687354

-D

**Comment by ValWood** [comment]
That will do it!
I thought I had updated this ticket to this effect. I mustn't have hit the comment button!

**Comment by ukemi** [comment]
Actually, it looks like we already made the clamp activity and the ring activity. 

http://amigo.geneontology.org/amigo/term/GO:0061777
http://amigo.geneontology.org/amigo/term/GO:0061776

but I never recorded it in this ticket. Should I just change the name of the ring activity to 'topological DNA entrapment activity'?

**Comment by ValWood** [comment]
Yes that's the only problem...the name...

The comment I thought I had posted was,  that we should use this name

based on this:
https://www.ncbi.nlm.nih.gov/pubmed/27797071
An In Vitro Assay for Monitoring Topological DNA Entrapment by the Chromosomal Cohesin Complex.

It seems  to be the correct name....

**Comment by ukemi** [comment]
[Term]
 id: GO:0061776
-name: DNA ring activity
+name: topological DNA entrapment activity
 namespace: molecular_function
-def: "The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring." [GOC:dph, GOC:vw, PMID:16179255, PMID:26687354]
+def: "The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring." [GOC:dph, GOC:vw, PMID:16179255, PMID:26687354, PMID:27797071]
 is_a: GO:0003677 ! DNA binding
 created_by: dph
 creation_date: 2016-07-13T13:10:15Z
