### ISSUE TITLE
process term for  GO:0008479 queuine tRNA-ribosyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12536]
I think we have discussed this before, but I can't find a process term for this MF...anyone know what it should be?

**Comment by ukemi** [comment]
tRNA modification?

**Comment by ukemi** [comment]
@hdrabkin

**Comment by ValWood** [comment]
This is a bit suboptimal because we have in pombe 3 genes  so far in the queuine modification pathway, but you can’t distinguish these easily from the other tRNA modifiers at the process level

**Comment by ValWood** [comment]
I now remember that I asked about this before:

https://github.com/geneontology/go-ontology/issues/11905
tRNA-guanine transglycosylation 
for organims which only utilize the dietary queuosine to modify tRNA's

The reaction is
tRNA guanine + queuine = tRNA queuine + guanine.
so it seems that its guanine that is salvaged?

from
PMID: 24911101 abstract
Queuosine (Q) is a modification found at the wobble position of tRNAs with GUN anticodons. Although Q is present in most eukaryotes and bacteria, only bacteria can synthesize Q de novo. Eukaryotes acquire queuine (q), the free base of Q, from diet and/or microflora, making q an important but under-recognized micronutrient for plants, animals, and fungi.

I think we should add a term for this, I just had a problem (again) tracking down the genes in the pathway.

Also, the metabolism term still doesn't have taxon restrictions
so we are still picking up mappings to GO:0008616	queuosine biosynthetic process
http://www.pombase.org/spombe/result/SPAC1687.19c#go-biological_process

**Comment by ValWood** [comment]
note to self
http://www.pombase.org/spombe/result/SPAC589.05c
and Anne's session
https://curation.pombase.org/pombe/curs/466ed4e946c15c3f/ro/

**Comment by ValWood** [comment]
queuosine biosynthestic process
add taxon check
never in  eukaryotes (correct?)
I won't bother to  raise a ticket to correct the erroneous mapping for UniProtKB-KW:KW-0671
because it will be removed via the taxon restriction.

**Comment by mcourtot** [comment]
Hi @ValWood - sorry I'm confused between this ticket and the other one, #11905, referenced above. Could you summarise what are the needed changes? Just want to make sure I get this right and don't undo previous work.

**Comment by ValWood** [comment]
Essentially, I need a more specific term then 'tRNA modification' to describe the modification of a tRNA anticodon loop by replacing  guanine with queuonine . The other  linjked ticket is where I asked previously. I settled for tRNA modification, but a more specific term would be useful to group the pathway, so I would still like it.

I'm not sure exactly what it should be called, Harold's @hdrabkin input would be useful here.


GO:0008616 queuosine biosynthetic process needs the taxon restriction never in eukaryotes. Eukaryotes obtain queuosine from dietary sources, but many are annotated to this term.....

**Comment by ValWood** [comment]
Hi,

Can we get this one (looks quick and will enable me to approve a community curated session)
https://curation.pombase.org/pombe/curs/466ed4e946c15c3f/ro
Thanks

Val

**Comment by ValWood** [comment]
note to self curs/466ed4e946c15c3f

**Comment by mcourtot** [comment]
Hi @hdrabkin: can you help with this?

**Comment by hdrabkin** [comment]
" to describe the modification of a tRNA anticodon loop by replacing guanine with queuonine" .
DO you mean something like a class of tRNA modifications based on location of the modification? 
like: tRNA anticodon loop modification.
or do you mean to separate the synthesis from scratch  vs the swapping mechanism (euk)

**Comment by ValWood** [comment]
Hi Harold,

Yes I want to describe the *modification* in Eukaryotes at the process level to be able to differentiate from other types of tRNA modification

so exactly this
" to describe the modification of a tRNA anticodon loop by replacing guanine with queuonine" .

earlier I suggested 

tRNA-guanine transglycosylation 
for organism which only utilize the dietary queuosine to modify tRNA's

Reaction
tRNA guanine + queuine = tRNA queuine + guanine.

Is this correct?

Thanks

Val

**Comment by mcourtot** [comment]
Hi @hdrabkin - if you can confirm which changes need to be made I can implement. Thanks!

**Comment by ValWood** [comment]
Hi @hdrabkin  can you confirm?

I'm trying to close PomBase tracker tickets!
Val

**Comment by mcourtot** [comment]
Pinging @hdrabkin for help please!

**Comment by ValWood** [comment]
@hdrabkin I am going to follow you around today until you answer my question ;)

**Comment by hdrabkin** [comment]
Val
tell me what terms you want; I've commented several times

**Comment by ValWood** [comment]
tRNA-guanine transglycosylation will do fine. Done!
Melanie can you implement ? Thanks!

**Comment by mcourtot** [comment]
tRNA-guanine transglycosylation
The modification of a tRNA anticodon loop by replacing guanine with queuonine. Reaction is tRNA guanine + queuine = tRNA queuine + guanine.
PMID: 24911101
is_a GO:0006400 tRNA modification
never in eukaryotes

Please approve or make changes.

**Comment by ValWood** [comment]
Hi Melanie,

That all sounds perfect to me, except it should not have the taxon restriction. 

GO:0008616 queuosine biosynthetic process should have "never in eukaryotes". 
But this term  is a modification using dietary queuosine (not biosynthesis) and as far as I'm aware is universal.

Val

**Comment by mcourtot** [comment]
Ok, so

NTR: tRNA-guanine transglycosylation
The modification of a tRNA anticodon loop by replacing guanine with queuonine. Reaction is tRNA guanine + queuine = tRNA queuine + guanine.
PMID: 24911101
is_a GO:0006400 tRNA modification


And add taxon restriction to GO:0008616 queuosine biosynthetic process: never in eukaryotes

I'll try and get to it tomorrow, thanks for checking!

**Comment by mcourtot** [comment]
Done revision 36932.
