### ISSUE TITLE
negative regulation of mitotic DNA replication initiation from late origin

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12533]
Hi,

I haven't seen a message about TG FF being back up. It seemed to work to submit an NTR via TG FF but in case the term goes missing this is my submission:

Label   negative regulation of mitotic DNA replication initiation from late origin
Definition  Any process that stops, prevents or reduces the frequency, rate or extent of firing from a late origin of replication involved in mitotic DNA replication.
Xrefs   PMID:26436827
Relations  
    is_a: GO:0061487 ! DNA replication initiation from late origin
    is_a: GO:1903467 ! negative regulation of mitotic DNA replication initiation
Meta-Data  
    namespace: biological_process
    subset: termgenie_unvetted
    created_by: TermGenie
    creation_date: 2016-07-11T14:56:38Z 

Submitted for Review
Your commit has been stored and awaits review by the ontology editors.
The following terms have been created:

```
ID: GO:1990977 Label: negative regulation of mitotic DNA replication initiation from late origin
```

Thanks

**Comment by dosumis** [comment]
Hi Antonia, I believe TGFF is still officially suspended.  Shouldn't matter here though as this term should be created via the regulation template.

**Comment by Antonialock** [comment]
Hi David, Thanks but I don't think I can use the regulation template for this because of the 
is_a: GO:0061487 ! DNA replication initiation from late origin
is_a: GO:1903467 ! negative regulation of mitotic DNA replication initiation

**Comment by ValWood** [comment]
I often wonder with terms like this, if there is no difference between the process
DNA replication initiation
and
DNA replication initiation from late origin
except via regulation

should the term 
DNA replication initiation from late origin
exist, or  should we only have the regulation terms in GO?
(if the terms  *need* to exist the should be in our 'do not annotate' subset?)

**Comment by Antonialock** [comment]
Hmm, I thought we might want to distinguish
-negative regulation of replication inititiation from late origins
-negative regulation of **any** replication initiation

**Comment by ValWood** [comment]
I think the regulation terms are fine, but I wondered if ALL regulation terms needed the none regulation equivalent? (I don't know...I think we do this for regulation of a quality)

**Comment by Antonialock** [comment]
I'm not following what you mean?

**Comment by Antonialock** [comment]
> Hmm, I thought we might want to distinguish
> -negative regulation of replication inititiation from late origins
> -negative regulation of any replication initiation

What I meant was that surely "intrinsic" regulation of what replication origins to fire from is different from (for example) preventing DNA replication initiation to happen altogether?

**Comment by dosumis** [comment]
Request this first:

name: mitotic DNA replication initiation from late origin
is_a: GO:0061487 ! DNA replication initiation from late origin

Assuming this term request is excepted, then you can use the template to make the term you want and you should get the inferred classifications you need.  If there are inference problems, this can be revisited.

**Comment by mah11** [comment]
> Request this first:
> 
> name: mitotic DNA replication initiation from late origin

No, I don't think that's a biologically sound approach. Val's point above is correct, that initiation is initiation is initiation. The mechanism and involved gene products are the same at early origins and at late origins, so there is no differentium to distinguish "initiation at late origin" from "initiation".

What is different is the regulation of whether an origin fires in a given S phase, and if so, whether it fires early or late. That's what Antonia wants to capture, and she's right to propose doing so at the level of regulation. 

As for GO:0061487, Val queried its existence in #10597, and I now think she was right to do so. It should be either recast as a regulation term or made obsolete and replaced with a new regulation term.

**Comment by ValWood** [comment]
Yeah but my reasoning in the old ticket was flawed...There I was questioning whether initiation early vs. origins were regulated  spatially at all....It seems that they are...

**Comment by mah11** [comment]
Yeah, I didn't go into the details about rationale then versus now. You happened to spot a term that deserved to be looked at funny, though, even if it was for the wrong reasons back then ;)

**Comment by mcourtot** [comment]
Looking back at the original request:

Label negative regulation of mitotic DNA replication initiation from late origin
Definition Any process that stops, prevents or reduces the frequency, rate or extent of firing from a late origin of replication involved in mitotic DNA replication.
Xrefs PMID:26436827
Relations
is_a: GO:0061487 ! DNA replication initiation from late origin
is_a: GO:1903467 ! negative regulation of mitotic DNA replication initiation

I don't think it should be is_a GO:0061487, I would expect a regulation term there. If you agree I would suggest first creating NTR negative regulation of DNA replication initiation from late origin (which can be created from the TG template)

**Comment by dosumis** [comment]
Got it.  So the issue is when the regulation happens.  In that case we need to either extend the regulation pattern to account for timing (but this would require a process/phase term), or the new term should be structured as:

is_a: biological process reguation
relationship: regulates mitotic DNA replication initiation

-> reasoner will then dynamically place in the correct part of the class hierarchy.  (Assuming GO:0061487 will be obsoleted).

**Comment by mah11** [comment]
This looks (biologically) right:

> is_a: biological process regulation
> relationship: regulates mitotic DNA replication initiation

Specifically, mitotic DNA replication is regulated with respect to whether and when it happens at a given origin. Antonia has a case where mitotic DNA replication is negatively regulated at origins that normally fire late in S phase (by implication, the negative regulation isn't occurring at origins that fire early). I don't know whether that can be put in a reasoner-friendly way.

**Comment by mcourtot** [comment]
@Antonialock: can you please confirm what is requested and which relations need to be created?

**Comment by Antonialock** [comment]
I do not know! 
I want a term that applies to a gene product that suppresses firing from specific replication origins. These specific origins are typically only used late in S phase, or never.

**Comment by ValWood** [comment]
I think

obsolete GO:0061487 (we know enough about the biology to know that there should *only* be regulation terms for this process)

instead create 
GO:NEW regulation of DNA replication initiation from late origin
GO:NEW positive regulation of DNA replication initiation from late origin

which are is_a 
GO:0030174 regulation of DNA-dependent DNA replication initiation

but editors would need to confirm if this is possible/correct?

**Comment by mcourtot** [comment]
Thanks for the summary @ValWood - should this be 
GO:NEW regulation of **mitotic** DNA replication initiation from late origin 
and 
GO:NEW **negative** regulation of **mitotic** DNA replication initiation from late origin

and obsolete GO:0061487.

Could you clarify what you foresee could be an issue for editors? Everything is possible ;) Our next editors call is on the 21st so I could bring whatever is needed up.

**Comment by ValWood** [comment]
Hi Melanie,

If its OK to add those without the non-regulatory  root term, all should be fine.

Val

**Comment by mcourtot** [comment]
I see. I don't think I can add this without creating 'mitotic DNA replication initiation from late origin' - to create the regulation term I need to say 'biological process and (regulates some mitotic DNA replication initiation from late origin)". If I don't have the non-regulatory root term then I could say  'biological process and (regulates some mitotic DNA replication initiation)" but this would make it equivalent to GO_1903466, regulation of mitotic DNA replication initiation.

I'll bring this up with other editors indeed. Thanks for clarifying, and solving my 'lost in regulation terms' issue :)

**Comment by ValWood** [comment]
I have a feeling we have done this before in the 'regulation of a quality' branch @ukemi ?

**Comment by mah11** [comment]
In this case it's not really a quality that's being regulated, though; it is a process.

The reason we don't want 'DNA replication initiation from late origin' (or a 'mitotic' version) to exist is that the initiation process itself is the same at all origins that fire in a given S phase. At early versus late origins, the process is identical, but the regulation is different.

I don't know if I've got the nesting or the second relation exactly right, but it's more like:

biological process and (regulates some mitotic DNA replication) and (occurs at some late-firing origin)

where the features that make an origin "early" or "late" include its genomic context (e.g. telomeres tend to replicate late, at least in yeasts) and other things such as chromatin structure and location within the nucleus.

This is a real, well-studied biological phenomenon, and it probably isn't the only case where timing, rather than distinct regulated processes, differentiates regulatory processes from each other.

**Comment by dosumis** [comment]
> I see. I don't think I can add this without creating 'mitotic DNA replication initiation from late origin' - to create the regulation term I need to say 'biological process and (regulates some mitotic DNA replication initiation from late origin)". If I don't have the non-regulatory root term then I could say 'biological process and (regulates some mitotic DNA replication initiation)" but this would make it equivalent to GO_1903466, regulation of mitotic DNA replication initiation.

Just use relationships (OWL SubClassOf) rather than intersections (EquivalentTo), that way you won't have the problem of making named classes equivalent.  (To use EquivalentTo you'd need some way to record the timing of regulation.  For that you'd need some process with appropriate timing to point to.  Don't think this exists.)

**Comment by mcourtot** [comment]
Summary: (@antonialock, @ValWood, @mah11 please check/confirm this is what you need)

(1) ADD:
GO:NEW regulation of mitotic DNA replication initiation from late origin 
Definition Any process that modulates the frequency, rate or extent of firing from a late origin of replication involved in mitotic DNA replication.
Xrefs PMID:26436827
is_a: GO_1903466 ! regulation of mitotic DNA replication initiation

GO:NEW negative regulation of mitotic DNA replication initiation from late origin
Definition Any process that stops, prevents or reduces the frequency, rate or extent of firing from a late origin of replication involved in mitotic DNA replication.
Xrefs PMID:26436827
Relations
is_a: GO:NEW ! regulation of mitotic DNA replication initiation from late origin
is_a: GO:1903467 ! negative regulation of mitotic DNA replication initiation

(2) Proposal to obsolete GO:0061487
Added to agenda for next editors call: http://wiki.geneontology.org/index.php/Ontology_meeting_2016-07-21

**Comment by mah11** [comment]
That looks good to me. Thanks

**Comment by mcourtot** [comment]
added GO:0101017, regulation of mitotic DNA replication initiation from late origin 
and 
GO:0101018, negative regulation of mitotic DNA replication initiation from late origin

**Comment by mcourtot** [comment]
Obsoletion request discussed during editor call on July 21. Proposal to ask SO for a 'late origin' term, and then add restriction 'has participant some late origin'.

@ValWood, @mah11: could you suggest a suitable definition for 'late origin'?

**Comment by mah11** [comment]
id: SO:new1
name: early_origin_of_replication
def: "An origin of replication that initiates early in S phase." []
synonym: "early origin" EXACT []
synonym: "early origin of replication" EXACT []
is_a: SO:0000296 ! origin_of_replication

id: SO:new2
name: late_origin_of_replication
def: "An origin of replication that initiates late in S phase." []
synonym: "late origin" EXACT []
synonym: "late origin of replication" EXACT []
is_a: SO:0000296 ! origin_of_replication

**Comment by mcourtot** [comment]
Note to self: still awaiting SO terms. Main request (adding negative regulation of mitotic DNA replication initiation from late origin) has been dealt with, therefore removing the high priority tag. 

 TODO:
- [ ] get the SO terms

- [ ] redefine GO:0061487, DNA replication initiation from late origin, logically adding a restriction  'has participant some late origin'.

**Comment by mcourtot** [comment]
SO terms have been added:
SO:0002140 early_origin_of_replication
SO:0002141 late_origin_of_replication

**Comment by mcourtot** [comment]
Note to self: requested import of SO terms

**Comment by ValWood** [comment]
Can we move this on through?
val

**Comment by mcourtot** [comment]
Waiting for SO to repair their file: https://github.com/geneontology/go-ontology/issues/12775

**Comment by mcourtot** [comment]
Terms from SO have been imported:

[Term]
id: SO:0002140
name: early_origin_of_replication
is_a: SO:0000296 ! origin_of_replication

[Term]
id: SO:0002141
name: late_origin_of_replication
is_a: SO:0000296 ! origin_of_replication


TODO:  
- [ ] redefine GO:0061487, DNA replication initiation from late origin, logically adding a restriction 'has participant some late origin'.

**Comment by mcourtot** [comment]
Done revision 38598.
