### ISSUE TITLE
add synonym to GO:1990814 DNA/DNA annealing activity PMID:22645654

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12538]
I'm assuming that they are exact? are there any obvious cases where not? 

DNA reannealing activity

**Comment by mcourtot** [comment]
I would think reannealing imply there was a double stranded state, then single stranded, then double stranded - equivalent to renaturation. But I agree that in term of the function there should be the same - same mechanism is involved in both. 
I'll leave open until tomorrow in case someone else wants to comment and if not will add the synonym then. Thanks @ValWood!

**Comment by ValWood** [comment]
I was trying to think of a situation where annealing happened in a physiological context where the DNA did not begin in a double stranded state (i.e post replication DNA is double stranded).
There probably are some though.....

**Comment by mcourtot** [comment]
Committed revision 34440.
