### ISSUE TITLE
Adding labels

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12534]
I'm not sure where to ask this but I would like to be able to add the Pombase label to my tickets, but it doesn't seem like I'm allowed to. Can you give me permission to? Cheers

**Comment by mcourtot** [comment]
I have added you to the team - you should receive an invitation and this should allow you to add labels. Please try and confirm once invitation is accepted.

Cheers,
Melanie

**Comment by Antonialock** [comment]
Super, thanks!
