### ISSUE TITLE
Molecular Functions for kinetochore complexes/components

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12537]
Not required urgently, but will need something for these when I begin to build chromosome segregation model in LEGO

NMS complex (aka KMN complex) (outer kinetochore)
The KMN complex functions as a molecular mechanical sensor that monitors microtubule-kinetochore attachment (Rago and Cheeseman, 2013).

So although it could be described as a kinetochore spindle adaptor, it is more than that

I'll collect the functions here, can also be used in the complex definitions

**Comment by ValWood** [comment]
This will be useful:
http://jcs.biologists.org/content/125/24/5927

**Comment by mcourtot** [comment]
Hi @ValWood: did I understand correctly that this is an umbrella ticket to collect functions that will be required at a later stage, and that no action are needed right now? Cheers.

**Comment by ValWood** [comment]
Yep, I'll need it before I proceed with the LEGO model. I just want people to know we need MF terms for this (presumably I'm not the only person trying to annotate kinetochore/spindle protein activities). There are some very well characterised and important molecular functions here which currently get lumped as "protein binding".

For now you can assign the ticket to me.

**Comment by ValWood** [comment]
Closing this one. 
I will request the appropriate sensor term when I am back curating chromosome segregation.
ANy other MFs  I needed I realised independent tickets.
