### ISSUE TITLE
difference between  GO:0036292 DNA rewinding & GO:0000733 DNA strand renaturation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12539]
GO:0036292 DNA rewinding
The process in which interchain hydrogen bonds between two single-stranded DNA (ssDNA) are reformed to regenerate double-stranded DNA (dsDNA). ssDNA is often bound and stabilized by proteins such as replication protein A (RPA) to form ssDNA bubbles. The bubbles can be rewound by ATP-dependent motors to reform base pairs between strands and thus dsDNA.

and
GO:0000733  DNA strand renaturation
The identification and annealing of complementary base pairs in single-strand DNA.

And why does 'rewinding' require ATP once  RPA is removed ???? ;) Surely dsDNA will reform spontaneously.... I'm lost here...help needed

**Comment by ValWood** [comment]
They couldn't be more distant....

![diff](https://cloud.githubusercontent.com/assets/7359272/16780177/6f18e694-486d-11e6-81a9-66dcd21352bb.jpg)

**Comment by ValWood** [comment]
I'm asking because one of our community requested the following:

![query](https://cloud.githubusercontent.com/assets/7359272/16780302/ff332ba4-486d-11e6-847f-cb8a76a060e4.jpg)


Basically
PMID:22645654
Title	Opposing role of condensin hinge against replication protein A in mitosis and interphase through promoting DNA annealing.
Authors	Akai Y, Kurokawa Y, Nakazawa N, Tonami-Murakami Y, Suzuki Y, Yoshimura SH, Iwasaki H, Shiroiwa Y, Nakamura T, Shibata E, Yanagida M


I'm not sure if the condensin displaces the ssb and the DNA renatures spontaneously, or is the condensin drives renaturation which displaces ssb...

Maybe this is the difference between renaturation and rewinding?

DNA strand renaturation (preumably NOT a metabolic process, but is_a geometric change?)
-- DNA rewinding  (performed by helicases?)

**Comment by mah11** [comment]
They are linked, actually, by has_part - 

    id: GO:0036292
    name: DNA rewinding
    ...
    is_a: GO:0032392 ! DNA geometric change
    relationship: has_part GO:0000733 ! DNA strand renaturation

I found some background in comments on #9815.

**Comment by mah11** [comment]
Oh, and it's not at all surprising that a reaction that's energetically favorable enough to happen spontaneously nevertheless has an enzyme to speed it up. From the late great Arthur Kornberg:

![screen-capture](https://cloud.githubusercontent.com/assets/5196259/16870912/f7864eda-4a7b-11e6-990c-5427dfd978b3.png)

(found at [google books] (https://books.google.co.uk/books?id=gKyiLGWBUAUC&pg=PA298&lpg=PA298&dq=arthur+kornberg+carbonic+anhydrase&source=bl&ots=okfc03TYPp&sig=H8nOW9kn2m5CtCOU6OAxCTVJfCM&hl=en&sa=X&ved=0ahUKEwiGq_H4mvXNAhWFcRQKHbh8BzQQ6AEIHDAA#v=onepage&q&f=false))

**Comment by ValWood** [comment]
:)

**Comment by ValWood** [comment]
This could be closed, but its a great example where we will have  inconsistent annotation because some will annotate to 'rewinding' and some to 'renaturation'. Its a BIG problem, I think... for consistency and enrichment, although it does not seem to bother most as much as me.

I'm going to tag this with a has_part label and look at the annotation inconsistencies at some point to demonstrate....

**Comment by ValWood** [comment]
Q isn't strand renaturation a geometric change? or is it a metabolic process? Sorry....

**Comment by mcourtot** [comment]
Maybe adding a detailed comment would help?

**Comment by mcourtot** [comment]
Hi @ValWood can you confirm whether this can be closed or if you would prefer to add a comment, and if yes what?

Thanks!

**Comment by ValWood** [comment]
I don't know what the comment should be,  but I think that "DNA strand renaturation" is a geometric change, not a "metabolic process"? Can anyone confirm? @mah11 ?
This would also make these terms siblings which  would be better.....people are more likely to find both terms when drilling  down and then select the correct one.

**Comment by mah11** [comment]
> I think that "DNA strand renaturation" is a geometric change, not a "metabolic process"? Can anyone confirm? @mah11 ?

Sorry, I don't know anything enlightening. (I don't have any specific reason to oppose the changes Val proposes; I just also don't have specific support either.)

**Comment by ValWood** [comment]
I thought that changes which only involved base pairing, and no covalent changes to the DNA structure, were not classed metabolic?

**Comment by mcourtot** [comment]
Pinging @ukemi in case he has any idea? Do we otherwise know someone who could help?

**Comment by ValWood** [comment]
I was looking fro some history, the closest I found is 
https://github.com/geneontology/go-ontology/issues/6576
but I am sure there are more.
 
So if metabolism involved the forming or breaking of bonds, does this include base-pairing. I thought that it  *only* referred to covalent bonds.... in which case annealing would not be metabolic?

**Comment by mcourtot** [comment]
Hi @ValWood - I'm still unsure what needs to be done for this ticket. If you could clarify I'm happy to implement.

**Comment by ValWood** [comment]
OK.
 A DNA metabolic process is
GO:0006259
Definition	Any cellular metabolic process involving deoxyribonucleic acid. This is one of the two main types of nucleic acid, consisting of a long, unbranched macromolecule formed from one, or more commonly, two, strands of linked deoxyribonucleotides.
Secondary IDs	GO:0055132
GONUTS	GO:0006259 Wiki Page


But a metabolic process is
GO:0008152 metabolic process
The chemical reactions and pathways, including anabolism and catabolism, by which living organisms transform chemical substances. Metabolic processes typically transform small molecules, but also include macromolecular processes such as DNA repair and replication, and protein synthesis and degradation.

I don't think that GO:0000733 DNA strand renaturation
fits the definition of a metabolic process.

No DNA is "metabolised" in this process. Like "DNA rewinding" I think that "renaturation" is only a "geometric change".

If everyone agrees, the fix here is to change the parentage of  
GO:0000733 DNA strand renaturation

to
Name	DNA geometric change


and then at least  winding, unwinding, annealing will be siblings.

Does that work or does anyone disagree?

**Comment by mcourtot** [comment]
DNA geometric change:
<img width="373" alt="screen shot 2016-11-08 at 09 09 38" src="https://cloud.githubusercontent.com/assets/2214135/20093088/2c90f900-a593-11e6-8cb0-ec26fd41f194.png">
DNA metabolic process:
<img width="360" alt="screen shot 2016-11-08 at 09 11 12" src="https://cloud.githubusercontent.com/assets/2214135/20093126/57f9f7e0-a593-11e6-96e8-ca1deacdb7e9.png">

Based on those, would it make sense to add 'DNA geometric change' as parent to 'DNA strand renaturation' and not remove the existing parent 'DNA metabolic process'? The definition of metabolic process does include 'macromolecular processes such as DNA repair and replication', so it may make sense to keep it (and it would be consistent with existing siblings).

@ValWood, what do you think?

**Comment by ValWood** [comment]
Oh dear. You will wish that you hadn't asked.

This might be a bigger issue involving the wholsale placement of "DNA replication" "DNA elongation" etc directly under metabolism.

Although some aspects of DNA replication  are metabolism,  it is really only the parts which  ...well..metabolise DNA.
At the GO meeting, someone mentioned that DNA replication needed some refactoring. MAybe this is one of the known issues (I have not really seen anything related to DNA replication on git-hub). Anyway, if this is the case, I suggest labelling this to be addressed as part of any future refactoring of DNA replication.

**Comment by mcourtot** [comment]
Done revision 37010.

@ValWood: to remain consistent with the whole branch (and even though I think your points are very valid) I kept the original parent 'DNA metabolic process'. As you indicate, this is probably in need of clean up, but at least right now things are consistent with other terms, which will probably make it easier to 1) find the relevant terms 2) clean up when the time comes.
