### ISSUE TITLE
Add sparql check for inappropriate capitalization of "Type"

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12540]
See https://github.com/cmungall/capital-offence/issues/1

We should always use "type" not "Type"
- [GO:0004909](http://purl.obolibrary.org/obo/GO_0004909) ! interleukin-1,  **Type**  I, activating receptor activity [SYNONYM: "IL-1 type I, activating binding" (exact)] [SYNONYM: "IL-1 type I, activating receptor" (exact)] [SYNONYM: "interleukin-1 activating receptor activity" (exact)] [SYNONYM: "interleukin-1  **Type**  I receptor activity" (exact)] [SYNONYM: "interleukin-1,  **Type**  I, activating binding" (related)]
- [GO:0004910](http://purl.obolibrary.org/obo/GO_0004910) ! interleukin-1,  **Type**  II, blocking receptor activity [SYNONYM: "IL-1 type II, blocking binding" (exact)] [SYNONYM: "IL-1 type II, blocking receptor" (exact)] [SYNONYM: "interleukin-1 blocking receptor activity" (exact)] [SYNONYM: "interleukin-1  **Type**  II receptor activity" (exact)] [SYNONYM: "interleukin-1,  **Type**  II, blocking binding" (related)]
- [GO:0005150](http://purl.obolibrary.org/obo/GO_0005150) ! interleukin-1,  **Type**  I receptor binding [SYNONYM: "IL-1 type I" (narrow)] [SYNONYM: "interleukin-1,  **Type**  I receptor ligand" (narrow)]
- [GO:0005151](http://purl.obolibrary.org/obo/GO_0005151) ! interleukin-1,  **Type**  II receptor binding [SYNONYM: "IL-1 type II" (narrow)] [SYNONYM: "interleukin-1,  **Type**  II receptor ligand" (narrow)]
- [GO:0009008](http://purl.obolibrary.org/obo/GO_0009008) ! DNA-methyltransferase activity [SYNONYM: "deoxyribonucleate methylase activity" (exact)] [SYNONYM: "deoxyribonucleate methyltransferase activity" (exact)] [SYNONYM: "deoxyribonucleic acid methylase activity" (exact)] [SYNONYM: "deoxyribonucleic acid methyltransferase activity" (exact)] [SYNONYM: "deoxyribonucleic acid modification methylase activity" (related)] [SYNONYM: "DNA methylase" (broad)] [SYNONYM: "DNA methyltransferase activity" (exact)] [SYNONYM: "DNA transmethylase activity" (exact)] [SYNONYM: " **Type**  II DNA methylase" (related)]
- [GO:0009035](http://purl.obolibrary.org/obo/GO_0009035) !  **Type**  I site-specific deoxyribonuclease activity [SYNONYM: "adenosine triphosphate-dependent deoxyribonuclease activity" (exact)] [SYNONYM: "ATP-dependent DNase activity" (exact)] [SYNONYM: "deoxyribonuclease (adenosine triphosphate-hydrolyzing)" (exact)] [SYNONYM: "deoxyribonuclease (ATP- and S-adenosyl-L-methionine-dependent)" (exact)] [SYNONYM: " **Type**  I restriction enzyme activity" (exact)] [SYNONYM: "type I site-specific deoxyribonuclease activity" (exact)]
- [GO:0009036](http://purl.obolibrary.org/obo/GO_0009036) !  **Type**  II site-specific deoxyribonuclease activity [SYNONYM: " **Type**  II restriction enzyme activity" (exact)]
- [GO:0009359](http://purl.obolibrary.org/obo/GO_0009359) !  **Type**  II site-specific deoxyribonuclease complex [SYNONYM: " **Type**  II restriction enzyme complex" (exact)]
- [GO:0015668](http://purl.obolibrary.org/obo/GO_0015668) !  **Type**  III site-specific deoxyribonuclease activity [SYNONYM: " **Type**  III restriction enzyme activity" (exact)]
- [GO:0019812](http://purl.obolibrary.org/obo/GO_0019812) !  **Type**  I site-specific deoxyribonuclease complex [SYNONYM: " **Type**  I restriction enzyme complex" (exact)]
- [GO:0019813](http://purl.obolibrary.org/obo/GO_0019813) !  **Type**  III site-specific deoxyribonuclease complex [SYNONYM: " **Type**  III restriction enzyme complex" (exact)]
- [GO:0032067](http://purl.obolibrary.org/obo/GO_0032067) !  **Type**  IV site-specific deoxyribonuclease activity [SYNONYM: " **Type**  IV restriction enzyme activity" (exact)]
- [GO:0032068](http://purl.obolibrary.org/obo/GO_0032068) !  **Type**  IV site-specific deoxyribonuclease complex [SYNONYM: " **Type**  IV restriction enzyme complex" (exact)]
- [GO:0032080](http://purl.obolibrary.org/obo/GO_0032080) ! negative regulation of  **Type**  I site-specific deoxyribonuclease activity [SYNONYM: "down regulation of  **Type**  I restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "down-regulation of  **Type**  I restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "downregulation of  **Type**  I restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "inhibition of  **Type**  I restriction endodeoxyribonuclease activity" (narrow)] [SYNONYM: "negative regulation of  **Type**  I restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  I restriction endodeoxyribonuclease inhibitor" (related)] [SYNONYM: " **Type**  I restriction enzyme inhibitor" (related)]
- [GO:0032081](http://purl.obolibrary.org/obo/GO_0032081) ! negative regulation of  **Type**  II site-specific deoxyribonuclease activity [SYNONYM: "down regulation of  **Type**  II restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "down-regulation of  **Type**  II restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "downregulation of  **Type**  II restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "inhibition of  **Type**  II restriction endodeoxyribonuclease activity" (narrow)] [SYNONYM: "negative regulation of  **Type**  II restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  II restriction endodeoxyribonuclease inhibitor" (related)] [SYNONYM: " **Type**  II restriction enzyme inhibitor" (related)]
- [GO:0032082](http://purl.obolibrary.org/obo/GO_0032082) ! negative regulation of  **Type**  III site-specific deoxyribonuclease activity [SYNONYM: "down regulation of  **Type**  III restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "down-regulation of  **Type**  III restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "downregulation of  **Type**  III restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "inhibition of  **Type**  III restriction endodeoxyribonuclease activity" (narrow)] [SYNONYM: "negative regulation of  **Type**  III restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  III restriction endodeoxyribonuclease inhibitor" (related)] [SYNONYM: " **Type**  III restriction enzyme inhibitor" (related)]
- [GO:0032083](http://purl.obolibrary.org/obo/GO_0032083) ! negative regulation of  **Type**  IV site-specific deoxyribonuclease activity [SYNONYM: "down regulation of  **Type**  IV restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "down-regulation of  **Type**  IV restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "downregulation of  **Type**  IV restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: "inhibition of  **Type**  IV restriction endodeoxyribonuclease activity" (narrow)] [SYNONYM: "negative regulation of  **Type**  IV restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  IV restriction endodeoxyribonuclease inhibitor" (related)] [SYNONYM: " **Type**  IV restriction enzyme inhibitor" (related)]
- [GO:0032084](http://purl.obolibrary.org/obo/GO_0032084) ! regulation of  **Type**  I site-specific deoxyribonuclease activity [SYNONYM: "regulation of  **Type**  I restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  I restriction endodeoxyribonuclease regulator" (related)] [SYNONYM: " **Type**  I restriction enzyme regulator" (related)]
- [GO:0032085](http://purl.obolibrary.org/obo/GO_0032085) ! regulation of  **Type**  II site-specific deoxyribonuclease activity [SYNONYM: "regulation of  **Type**  II restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  II restriction endodeoxyribonuclease regulator" (related)] [SYNONYM: " **Type**  II restriction enzyme regulator" (related)]
- [GO:0032086](http://purl.obolibrary.org/obo/GO_0032086) ! regulation of  **Type**  III site-specific deoxyribonuclease activity [SYNONYM: "regulation of  **Type**  III restriction endoribonuclease activity" (exact)] [SYNONYM: " **Type**  III restriction endodeoxyribonuclease regulator" (related)] [SYNONYM: " **Type**  III restriction enzyme regulator" (related)]
- [GO:0032087](http://purl.obolibrary.org/obo/GO_0032087) ! regulation of  **Type**  IV site-specific deoxyribonuclease activity [SYNONYM: "regulation of  **Type**  IV restriction endodeoxyribonuclease activity" (exact)] [SYNONYM: " **Type**  IV restriction endodeoxyribonuclease regulator" (related)] [SYNONYM: " **Type**  IV restriction enzyme regulator" (related)]
- [GO:0045352](http://purl.obolibrary.org/obo/GO_0045352) ! interleukin-1  **Type**  I receptor antagonist activity [SYNONYM: "IL-1ra type I" (exact)]
- [GO:0045353](http://purl.obolibrary.org/obo/GO_0045353) ! interleukin-1  **Type**  II receptor antagonist activity [SYNONYM: "IL-1ra type II" (exact)]
- [GO:0052000](http://purl.obolibrary.org/obo/GO_0052000) !  **Type**  IV pili-dependent aggregation [SYNONYM: "auto-aggregation" (broad)] [SYNONYM: "bfp-dependent aggregation" (exact)] [SYNONYM: "bundle-forming fimbriae-dependent aggregation" (exact)] [SYNONYM: "bundle-forming pili-dependent aggregation" (exact)] [SYNONYM: "tfp-dependent aggregation" (exact)]
- [GO:0052001](http://purl.obolibrary.org/obo/GO_0052001) !  **Type**  IV pili-dependent localized adherence to host
- [GO:0060509](http://purl.obolibrary.org/obo/GO_0060509) !  **Type**  I pneumocyte differentiation [SYNONYM: "membranous pneumocyte differentiation" (exact)] [SYNONYM: "small alveolar cell differentiation" (related)] [SYNONYM: "squamous alveolar cell differentiation" (related)]
- [GO:0060510](http://purl.obolibrary.org/obo/GO_0060510) !  **Type**  II pneumocyte differentiation [SYNONYM: "granular pneumocyte differentiation" (related)] [SYNONYM: "great alveolar cell differentiation" (exact)] [SYNONYM: "large alveolar cell differentiation" (related)]
- [GO:1990308](http://purl.obolibrary.org/obo/GO_1990308) !  **Type** -I dockerin domain binding
- [GO:1990309](http://purl.obolibrary.org/obo/GO_1990309) !  **Type** -II dockerin domain binding
- [GO:1990310](http://purl.obolibrary.org/obo/GO_1990310) !  **Type** -III dockerin domain binding
- [GO:1990311](http://purl.obolibrary.org/obo/GO_1990311) !  **Type** -I cohesin domain binding
- [GO:1990312](http://purl.obolibrary.org/obo/GO_1990312) !  **Type** -II cohesin domain binding
- [GO:1990313](http://purl.obolibrary.org/obo/GO_1990313) !  **Type** -III cohesin domain binding

**Comment by mcourtot** [comment]
@cmungall Those will be automatically fixed by script and are mentioned here just for tracking, correct?

**Comment by pgaudet** [comment]
I fixed the ones mentioned above - @dougli1sqrd we need to add a check for this.

**Comment by pgaudet** [comment]
This can be handled by  #12541
