### ISSUE TITLE
Query “endosomal secretion” 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12548]
Question, 
are  yeast  exosomes contained within a MVB?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990182
the term “exosomal secretion” is defined in terms of the MVB/multivesicular body fusion

There are only 16 EXP annotations, 9 are from a fly paper which says this in the abstract:

 ...In this paper, we show that SCs secrete exosomes, membrane-bound vesicles generated inside late endosomal multivesicular bodies (MVBs).
This doesn’t sound as thought the MVB itself fuses this the PM, but MVB derived vesicles.

Although this paper implies that it is MVB fusion:
http://europepmc.org/abstract/MED/26459596

Could this term be more clearly defined/named to indicate exosomal fusion via MVB? Has the  direct fusion been demonstrated ? lots of the models seem to  depict it in this way...

The  definition and placement will depend 
i) whether the MVB fuses with the membrane and releases exosomal
or 
ii)  whether the exosomal vesicles leave the MVB before fusion with the membrane

I will try to find out what happens in yeast. I thought that  exosomal vesicles left the endosome,  without MVB  but I'm not sure.....

**Comment by ValWood** [comment]
The outstanding question I mentioned  here
https://github.com/geneontology/go-ontology/issues/12547  is covered by this ticket.

**Comment by ValWood** [comment]
Maybe the issue here is simple. Perhaps just the term name needs to be changed (all exocytosis is 'exosomal secretion' right, not only when an MVB  fuses with the PM?)

**Comment by ValWood** [comment]
For the record, our community expert says that  it is not yet  if 
the exocytosis in fission yeast always via exocytic vesicles directly fusing with the PM or is sometimes via MVB's.....

**Comment by dosumis** [comment]
> This doesn’t sound as thought the MVB itself fuses this the PM, but MVB derived vesicles.

The budding is from outside to in.

Exosomes are membrane bound vesicles outside of cells: http://purl.obolibrary.org/obo/GO_0070062  If they fused with the plasma membrane then they'd cease to exist as vesicles, ejecting their contents.

Here's a review discussing fusion of MVB with PM:
"Using electron microscopy, these authors observed fusion profiles of multivesicular endosomes with the plasma membrane, leading to the secretion of the internal vesicles into the extracellular environment." "http://www.nature.com/nri/journal/v2/n8/full/nri855.html"


The only potential controversy I can see here is over whether MVB fusion with the PM is a type of exocytosis.  This paper calls it exocytosis though: http://www.ncbi.nlm.nih.gov/pubmed/10572093

**Comment by ValWood** [comment]
OK, we think we have it:

1.  In the context of exocytosis, endosome refers only to the vesicles within the MVB hence “exosomal secretion”  
2. excytosis which does not occur via an MVB does not use exosomes,  but "exocytic vesicles" 

Is that correct?

(So far, we don't know if pombe does 1, and we should have no annotations which refer to exosomes)

**Comment by ValWood** [comment]
confirm for us and I'll close, if not I may have questions on this one tomorrow...

**Comment by dosumis** [comment]
> In the context of exocytosis, exosome refers only to the vesicles within the MVB hence “exosomal secretion”
> excytosis which does not occur via an MVB does not use exosomes, but "exocytic vesicles"
Is that correct?

Yep.  Although not sure whether vesicles within MVB, prior to release, are referred to as exosomes.  Maybe only post-release...  One reason this seems sensible is that vesicles in MVB are not always secreted.

**Comment by ValWood** [comment]
After chatting with David, now I know what it is, we are adding a taxon restriction for this "never in yeast". This way we will be able to re evaluate if we find any biology which this applies to. We think unlikely....
