### ISSUE TITLE
Query def GO:0010324 membrane invagination

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12546]
Biological Process
Definition	The infolding of a membrane, resulting in formation of a vesicle.

not always true.
See children....phagocytosis.

Also formation of the cleavage furrow during cytokinesis is a type of membrane invagination.....

**Comment by dosumis** [comment]
Agree.

**Comment by tberardini** [comment]
So, just strip the def down to: The infolding of a membrane. ?

**Comment by ValWood** [comment]
Hi Tanya, 

That would work, but it might be good to look at children etc  
it might also be useful to consider any membrane bending processes in the context of this ticket
https://github.com/geneontology/go-ontology/issues/12387
There is quite a lot of work coming up in this area ....

I think there could be more duplication and redundancy here to describe different types of membrane bending....

I   added D-O-S and we can have look with the other  vesicle transport tickets on Thursday...

**Comment by tberardini** [comment]
Thanks for taking the vesicle transport/invagination/formation task on en masse.
