### ISSUE TITLE
NTR: Transcription factor inhibitor complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12544]
I need a complex term to group transcription factor inhibitors that have 
capable_of_part_of GO:1903507 negative regulation of nucleic acid-templated transcription.

Names:
transcription factor inhibitor complex
negative regulator of transcription complex (exact synonym)
...
Any better ideas?

example is Menin-JunD in PMID:22327296.

is_a protein complex
part_of: I can't be sure they are all nuclear so better leave it blank.
GOC ref: bhm

Thanks,
Birgit

**Comment by tberardini** [comment]
Sorry, but how would this term be different from 'transcriptional repressor complex',

http://amigo.geneontology.org/amigo/term/GO:0017053#display-lineage-tab

[Term]
id: GO:0017053
name: transcriptional repressor complex
namespace: cellular_component
def: "A protein complex that possesses activity that prevents or downregulates transcription." [GOC:mah]
subset: goslim_pir
is_a: GO:0043234 ! protein complex

**Comment by bmeldal** [comment]
Thank you! I didn't search for the right keywords!

Please close, my bad...

**Comment by bmeldal** [comment]
However, I wonder if we should add
synonym: transcription factor inhibitor complex [exact]
capable_of_part_of GO:1903507 negative regulation of nucleic acid-templated transcription.

**Comment by tberardini** [comment]
Good idea.  Done.

[Term]
id: GO:0017053
name: transcriptional repressor complex
namespace: cellular_component
def: "A protein complex that possesses activity that prevents or downregulates transcription." [GOC:mah]
subset: goslim_pir
synonym: "transcription factor inhibitor complex" RELATED [GOC:bhm]
is_a: GO:0043234 ! protein complex
intersection_of: GO:0043234 ! protein complex
intersection_of: capable_of_part_of GO:1903507 ! negative regulation of nucleic acid-templated transcription
