### ISSUE TITLE
Query: exocytosis include the Golgi to plasma membrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12547]
Should exocytosis include the Golgi to plasma membrane transport step?
Currently it doesn’t and the definition is not clear about start of process.
If it should , is all Golgi to plasma membrane transport
part of exocytosis? This article implies that it is, even if the protein ends up as a resident PM protein
https://en.wikipedia.org/wiki/Exocytosis#Vesicle_trafficking

Also exocytosis has children which includes this step (defined more broadly than the parent)
see
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0045054

Possible Solutions
1. Make Golgi to plasma membrane transport a descendant of exocytosis
2. Create a new term Golgi to plasma membrane transport involved in exocytosis if not all G-PM transport is  classed as part of exocytosis
add synonym vesicle trafficking involved in exocytosis

**Comment by ValWood** [comment]
![exocytosis _query sf](https://cloud.githubusercontent.com/assets/7359272/16948471/b5a0e14a-4dac-11e6-8779-c539816b4b9e.jpg)

**Comment by dosumis** [comment]
> Should exocytosis include the Golgi to plasma membrane transport step?

The opposite

(All) "Golgi to plasma membrane transport" has_part some exocytosis

**Comment by dosumis** [comment]
If you want a specific term for grouping, we can add 'exocytosis involved in Golgi to plasma membrane transport'.

**Comment by ValWood** [comment]
not the other way?
Golgi to plasma membrane transport involved in exocytosis?

**Comment by dosumis** [comment]
As you say, we need to be clear about the start and end points of exocytosis.  The def should then be revised accordingly.  

'Golgi to plasma membrane transport' begins with budding of a vesicle from the Golgi.  It feels like a big stretch to include this budding process in exocytosis.  While Wikipedia treats transport to the PM as the first step, this is hard to justify for some types of exocytosis such as synaptic vesicle exocytosis: SVs are transported for very long distances in there immature state via mechanisms that no-one would consider part of exocytosis.  So I think it should only encompass steps that prepare vesicles for fusion, fusion and any steps which follow that until secretion and integration of the vesicle membrane to the PM is complete.

old_def: A process of secretion by a cell that results in the release of intracellular molecules (e.g. hormones, matrix proteins) contained within a membrane-bounded vesicle by fusion of the vesicle with the plasma membrane of a cell. Steps that prepare vesicles for fusion with the membrane (e.g. docking and priming) are included in this process. This is the process in which most molecules are secreted from eukaryotic cells.

> 

new def: A process of secretion by a cell that results in the release of intracellular molecules (e.g. hormones, matrix proteins) contained within a membrane-bounded vesicle by fusion of the vesicle with the plasma membrane of a cell. This process begins with steps that prepare vesicles for fusion with the membrane (tethering and docking) and ends after vesicle contents have been ejected and the vesicle is fully integrated into the plasma membrane. This is the process by which most molecules are secreted from eukaryotic cells.

I may be able to add starts with and ends with formally to this process, but I'm a but worried about whether, for example, tethering occurs in all cases.

**Comment by dosumis** [comment]
I've changed the def.  You can add terms like 'exocytosis involved in Golgi to plasma membrane transport'  via TG if you need them.  Closing now.  Please feel free to re-open if there are still issues to resolve.

**Comment by ValWood** [comment]
That's OK, 
based on what you said above and if exocytosis begins with the preparation for fusion then I don't think these terms need to be linked.
I still have outstanding questions from above (existng endocytosis children), but I'll open a new ticket for this.
