### ISSUE TITLE
RNA localization to nucleus

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12549]
[Term]
id: GO:new
name: RNA localization to nucleus
namespace: biological_process
def: "A process in which RNA is transported to and maintained in a location within the nucleus." [GOC:mah, PMID:26305931]
synonym: "RNA localisation to nucleus" EXACT []
is_a: GO:0006403 ! RNA localization
intersection_of: GO:0006403 ! RNA localization
intersection_of: has_target_end_location GO:0005634 ! nucleus

**Comment by tberardini** [comment]
Done.

 [Term]
+id: GO:0090685
+name: RNA localization to nucleus
+namespace: biological_process
+def: "A macromolecular localization process in which RNA is transported to and maintained in a location within the nucleus." [GOD:mah, PMID:26305931]
+synonym: "RNA localisation to nucleus" EXACT [GOC:mah]
+is_a: GO:0006403 ! RNA localization
+intersection_of: GO:0006403 ! RNA localization
+intersection_of: has_target_end_location GO:0005634 ! nucleus
+created_by: tanyaberardini
+creation_date: 2016-07-19T17:00:49Z
