### ISSUE TITLE
NTR: maintenance of differentiated cell state

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12543]
Hello,

I recently annotated paper PMID:24804980, in which Figure 5 showed that the silencing of the BDNF gene by miR-1 and miR-206 was required for maintenance of the differentiated state of myotubes (however, this gene silencing was not required for induction of the differentiation).

There is a myotube differentiation term (GO:0014902) in gene ontology, however, the definition does not really fit what the paper/Figure 5 describes. And there seems to be no GO terms in the ontology for cell type differentiation maintenance at all.

After I shared this enquiry among the UCL curators, @rebeccafoulger has suggested referring to this review http://www.ncbi.nlm.nih.gov/pubmed/22596319 for other examples of similar processes.

The new term could be: ‘maintenance of differentiated cell state' and the definition would need to specify that this maintenance of differentiation/cell identity occurs once the cell has reached 'maturity'.

@ukemi would you mind looking at this issue? Rebecca mentioned that you were originally involved in  work on the differentiation/development hierarchy.

Thanks,
Barbara

DbxREFs: GOC:BHF, GOC:BHF_miRNA, GOC:bc

cc: @RLovering 
cc: @rachhuntley

**Comment by ukemi** [comment]
Adding @tberardini because she recently worked on this. It seems to me that this would be related to the dedifferentiation discussion. #12354

**Comment by tberardini** [comment]
Also @rachhuntley who initiated the dedifferentiation discussion, #12354.  Rereading that discussion, this request seems related but I don't think enough that we would link a new term like 'maintenance of differentiated cell state' to that branch.  I'm not quite sure how Fig. 5 shows that "the silencing of the BDNF gene by miR-1 and miR-206 was required for maintenance of the differentiated state of myotubes" but this is not a typical figure that I look at.  Sorry, but I can't contribute much more than that.

**Comment by tberardini** [comment]
If we add the new term, maybe it should be a child of 'cellular developmental process' instead of shoehorning it into one of the existing children of that term where it doesn't quite fit.
<img width="703" alt="screen shot 2016-07-18 at 3 43 47 pm" src="https://cloud.githubusercontent.com/assets/4998871/16932890/71317d48-4cfe-11e6-9d6c-9d0ee943fd6c.png">

**Comment by ukemi** [comment]
I agree. I'm just wondering if maybe we can even be more specific. Do you think it would be part of cell development or cell differentiation? It gets back to the tricky business of fate specification and determination that we thought long and hard about back when we did this part of the graph.

**Comment by rachhuntley** [comment]
I'm wondering now if this is just positive regulation of myotube differentiation?

In the paper they say "reduction in BDNF levels is believed to be required to allow myotube generation from undifferentiated myoblasts", and the miR is reducing BDNF thus allowing the myoblasts to differentiate.
The thing that put me off this term before was that they conclude: "This suggests that interaction between BDNF 3′UTR and miR-1/206 family miRs is utilized in C2C12 myotubes to maintain differentiation by BDNF repression but not to induce myogenic differentiation."

If it's true that induction of differentiation is not the same as positive regulation of differentiation, then would this be OK?

**Comment by dosumis** [comment]
> myotube generation from undifferentiated myoblasts

Doesn't this also include a fusion step?  So not simply differentiation.

**Comment by tberardini** [comment]
> If it's true that induction of differentiation is not the same as positive regulation of differentiation, then would this be OK?

http://geneontology.org/page/regulation

See the description of the various 'subtypes' of positive regulation: activation (starts the inactive process), maintenance (maintains frequency, rate, extent), upregulation (increases frequence, rate, extent).  

Are you talking about induction as the same as activation in that sense?  If so, then we can create 'activation of myogenic differentiation' as a child of 'pos reg of myogenic diff' and you can use that.

**Comment by BarbaraCzub** [comment]
Based on these guidelines http://geneontology.org/page/regulation it seems ok to annotate to positive regulation of [process] to indicate 'maintenance' of this [process].

I originally intended to annotate 'GO:0010831 positive regulation of myotube differentiation' which seems ok in view of the guidelines cited above.

However, the definition of GO:0014902 myotube differentiation is: 'The process in which a relatively unspecialized cell acquires specialized features of a myotube cell. Myotube differentiation starts with myoblast fusion and the appearance of specific cell markers (this is the cell development step). Then individual myotubes can fuse to form bigger myotubes and start to contract. Myotubes are multinucleated cells that are formed when proliferating myoblasts exit the cell cycle, differentiate and fuse.'

The above definition seems to suggest that in this case the positive regulation GO term GO:0014902 myotube differentiation refers specifically to activation/induction of the differentiated state, as it states that an undifferentiated cell is becoming more specialised. Therefore, we thought that this positive regulation term would not be suitable to describe the findings from this paper/Figure 5. 

Or perhaps it is the definition of GO:0014902 myotube differentiation, which should be modified to fit the guidelines: http://geneontology.org/page/regulation i.e. to account for [i] activation of [GO:0014902 myotube differentiation], [ii] maintenance of [GO:0014902 myotube differentiation] and [iii] upregulation of [GO:0014902 myotube differentiation]?

Then, as @rachhuntley suggests, the 'GO:0010831 positive regulation of myotube differentiation' could be the correct term after all?

**Comment by ukemi** [comment]
Isn't the function of the miRNA just a part of the development of the cell? It makes sense to me that suppression of the BDNF activity is simply part of the developmental program.

**Comment by BarbaraCzub** [comment]
hm... we don't really know what are the roles of the family of miRNAs miR-1/miR-206, because this miRNA family has been annotated only sparsely so far. The existing annotations suggest that other than being involved in development, they also have roles in regulation of cardiac hypertrophy, or the electrical activity of the heart (http://amigo.geneontology.org/amigo/search/annotation?q=URS000034B6F5). 
So, I could (should?) annotate simply to GO:0050793 regulation of developmental process has_regulation_target(myotube)? But based on the evidence from paper PMID:24804980, the annotation could be made more specific. We just wanted to ensure that it would not be incorrect, if we make it more specific, hence the request.

**Comment by tberardini** [comment]
Maybe this is something better tackled in an annotation call or annotation GH ticket. All I'm getting from Figure 5 is that miRNAs suppress (to varying degrees) BDNF-L expression in myotubes and myoblasts because expression of BDNF-L goes up in reporter assays of mutated vs. non mutated BDNF-L mi-R sites.

**Comment by BarbaraCzub** [comment]
We really need to focus only on Figure 5A. Firstly, wt BDNF repression in significantly stronger in the myotubes than in myoblasts. Secondly, there are no significant differences in suppression of the wt and mu BDNF in myoblasts, but there are significant differences in suppression of the wt and mu BNDF in myotubes. Hence, the authors concluded that the suppression is required to maintain the differentiated cell state, but not to induce it.
I will be happy to discuss this during an annotation call, however, I will not be available until after 5/08, as today is my last day at work before I'm on holiday for the next two weeks.

**Comment by tberardini** [comment]
I will ask @vanaukenk for a slot in an annotation call after August 5th.  Thanks.

**Comment by BarbaraCzub** [comment]
Hi Ruth and Rachael,


I have not heard from Tanya yet with regard to this NTR discussion and I would like to reply to this GitHub ticket and suggest that we could discuss this issue in an annotation call on the 6th of September, if possible. I initially wanted to suggest the next annotation call on the 23rd of August, but I see, Rachael, that you will be on holiday then, and I thought you would probably like to participate in this discussion, esp. that it is partly related to your dedifferentiation issue.


Could you please let me know whether you are happy for me to suggest the 6th of September?


Thanks,

Barbara

________________________________

**Comment by vanaukenk** [comment]
Hi Barbara,
@tberardini had asked me about slotting this into an annotation call, and I think that would be okay, but was also wondering what you think about working on this paper as part of the Noctua workshop at the EBI later this month?
Since we have the SGD annotation consistency exercise on the 23rd of this month, we couldn't do this paper then, and it might be nice to try to work through a LEGO model before we talk about it on the next annotation call, which would be the 12th of September.
Thx.
--Kimberly

**Comment by tberardini** [comment]
Thanks, @vanaukenk.  The 12th of Sept would work for me. I'll be a little late though. School is back in session so I'll be able to join at 8:30 am (instead of 8 am).

**Comment by BarbaraCzub** [comment]
Hi Kimberly,
Thank you for your suggestion. I'll bring this paper to the Noctua workshop, although I have a feeling it is probably not 'elaborate enough' for the purposes of the LEGO exercise (except for the cell differentiation, the only other possible annotations from this paper are GO:0035195	gene silencing by miRNA (or its children) and GO:1903231 mRNA binding involved in posttranscriptional gene silencing). So, I'll bring some 'back-up' papers too. I'll get back to you re 12th Sept (btw. this is a Monday, is this correct?), as this day very busy on the UCL calendar already.
Thank you,
Barbara

@RLovering 
@rachhuntley

**Comment by vanaukenk** [comment]
Hi @BarbaraCzub 
Sorry, the date of the annotation call would be the September 13th - our regular Tuesday call.
For the LEGO exercise, are there any reviews or additional background papers that would help with creating a LEGO model for this process?  
Thanks,
--Kimberly

**Comment by BarbaraCzub** [comment]
Hi Kimberly,
Tuesday the 13th would be a good day. Let's discuss this NTR then. 
There is this review http://www.ncbi.nlm.nih.gov/pubmed/22596319 , which @rebeccafoulger  suggested. I will look into it to see whether I can identify relevant papers for creating this LEGO model.
Thanks,
Barbara

@RLovering 
@rachhuntley 
@vanaukenk

**Comment by BarbaraCzub** [comment]
Hi Kimberly,

Could you please confirm whether this discussion is still scheduled for tomorrow's annotation call? 

I noticed that you included the recent fibril GitHub ticket (#12640) in the agenda, but not this one.
( http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-09-13 )

Thanks,
Barbara

@vanaukenk 
@RLovering 
@rachhuntley 
@rebeccafoulger 
@tberardini

**Comment by ukemi** [comment]
Hi Barbara,

Kimberly is out for this call, so I think it would be best to postpone.

-David

**Comment by BarbaraCzub** [comment]
Hi David,

Thank you for letting me know. She might have mentioned this, when we had a brief chat at the EBI, but I was not sure.

Thanks,
Barbara

**Comment by tberardini** [comment]
Can this go on the agenda for the October 11 call please? I hope everyone with a stake in this will be able to attend.

**Comment by BarbaraCzub** [comment]
Hi Tanya, thank you for bringing this up. I'm afraid I will not be able to attend the call next week, but Tue, 25 October, would be possible for me.
Barbara
 
@rachhuntley 
@RLovering

**Comment by rachhuntley** [comment]
Hi Tanya,
I won't be available on the 11th either I'm afraid. On the 25th I'm teaching but I'm sure Barbara can cover it. I think the issue has changed slightly from differentiation focused to what regulation covers, e.g. induction and/or maintenance, and maybe this can be fixed by amending the definition of the regulation of myotube differentiation term? At least that is what got from the discussion above.

**Comment by tberardini** [comment]
@rachhuntley  said: "I think the issue has changed slightly from differentiation focused to what regulation covers, e.g. induction and/or maintenance, and maybe this can be fixed by amending the definition of the regulation of myotube differentiation term? At least that is what got from the discussion above."

@BarbaraCzub @ukemi : Do you think we can address this issue by just amending the def of 'regulation of myotube differentiation'?   Or we can create 'activation of myogenic differentiation' as a child of 'pos reg of myogenic diff' and you can use that. (previously suggested)

**Comment by rachhuntley** [comment]
Hi Tanya,
Just to clarify, I think the term Barbara wants to use is the positive regulation term, not a new activation term - BDNF suppression is required to maintain the differentiated myotube cell state, but not to induce it, see Barbara's previous comment:

"However, the definition of GO:0014902 myotube differentiation is: 'The process in which a relatively unspecialized cell acquires specialized features of a myotube cell. Myotube differentiation starts with myoblast fusion and the appearance of specific cell markers (this is the cell development step). Then individual myotubes can fuse to form bigger myotubes and start to contract. Myotubes are multinucleated cells that are formed when proliferating myoblasts exit the cell cycle, differentiate and fuse.'

The above definition seems to suggest that in this case the positive regulation GO term GO:0014902 myotube differentiation refers specifically to activation/induction of the differentiated state, as it states that an undifferentiated cell is becoming more specialised. Therefore, we thought that this positive regulation term would not be suitable to describe the findings from this paper/Figure 5.

Or perhaps it is the definition of GO:0014902 myotube differentiation, which should be modified to fit the guidelines: http://geneontology.org/page/regulation i.e. to account for [i] activation of [GO:0014902 myotube differentiation], [ii] maintenance of [GO:0014902 myotube differentiation] and [iii] upregulation of [GO:0014902 myotube differentiation]?

Then, as @rachhuntley suggests, the 'GO:0010831 positive regulation of myotube differentiation' could be the correct term after all?'

**Comment by tberardini** [comment]
@rachhuntley, thanks for the clarification.

I think bringing Figure 5 up in an annotation call and then discussing the proper term to use to annotate the gene products involved is the way to go.  @vanaukenk - can this go on the 10/25 call agenda please with @BarbaraCzub to present?

**Comment by BarbaraCzub** [comment]
Thank you, @rachhuntley, for clarifying this. Yes, I think that in this specific case modifying the definition of the GO term to fit the guidelines for regulation terms would be the most suitable solution.  @tberardini, I have made a note in my calendar to present this on the 25th.

**Comment by vanaukenk** [comment]
Hi,
We have an annotation consistency exercise scheduled for the 25th, but I think we could put this item on the agenda to talk about before we get into the exercise.  I would still be in favor of trying to construct a LEGO model of the process described in the paper as part of this discussion.  Even if the paper doesn't provide direct experimental evidence for everything in the model, it can still be helpful to think about the biology in the context of LEGO models.

**Comment by tberardini** [comment]
@vanaukenk , @ukemi : can one of you work with @BarbaraCzub to create a LEGO model for this purpose?

**Comment by BarbaraCzub** [comment]
Hello, yes, I think you are right, Kimberly, that it would be helpful to have a LEGO model to aid the discussion, I'll create it for tomorrow.
@ukemi @tberardini @vanaukenk

**Comment by vanaukenk** [comment]
Hi, @BarbaraCzub,

Yes, if you want to try to create a LEGO model for tomorrow, I will try to take a look before the call.

Thanks,
--Kimberly

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk ,

I have created the LEGO model. It is called "GitHub#12543: maintenance of differentiated cell state" and the annotations are based predominantly on Figures 2 and 5a as well as Online Resource 4. (The other figures contain human data, whereas the maintenance of differentiated cell state is inferred from work in mouse cells, therefore I focused only on these figures for the model).

I used "biological_process" in the annoton, for which the "maintenance of differentiated cell state" is intended.

Please note: 

1) Atm, no option exists to differentiate between a Bdnf 3'UTR with a long UTR (BDNF-L), or a short UTR (BDNF-SH), therefore I have made annotations from Figure 2 only for miRs, which silence both: BDNF-L and BDNF-SH. Subsequently, only BDNF-L is studied in context of maintenance on the myotube differentiated state (Figure 5a).

2) The mRNA target constructs (BDNF-L and its mutant: miR1m) in this paper (PMID:24804980) are from mouse, therefore I attempted to use mouse IDs for the miRs. 
Thus, unfortunately, the miR IDs in this model are not correct, as I had no option to use the RNAcentral IDs - I had to use the MGI IDs, which represent genes, which encode precursors of the miRs being annotated, not the miRs themselves. 

--> a) Using gene IDs instead of miR IDs limits the information you can include in the model, as, when you use the gene IDs, you cannot specify whether mmu-miR-[number]-5p, or mmu-miR-[number]-3p, is involved in the silencing. And it is important to specify whether the -5p or -3p strand of the miR precursors is involved, as they will have different target genes (and specific IDs in the RNAcentral and miRBase databases), and so they will be involved in different processes.

--> b) Furthermore, the lack of option to used specific RNAcentral IDs has coerced me into making a potential mistake, as I have no way of knowing whether I used the correct gene ID for mmu-miR1a-1a-3p (URS00001DC04F_10090), as it could be a product of both: Mir1a-1 (MGI:2676869), or Mir1a-2 (MGI:3618746), as recorded in RNAcentral: http://rnacentral.org/rna/URS00001DC04F/10090 (or screen shot below).
Perhaps I should have created this annotation for both genes? But then still, I would have no way of capturing the information about the -5p or the 3p strand, i.e. the identity of the mature miR involved in the silencing.

![screen shot 2016-10-24 at 11 38 43](https://cloud.githubusercontent.com/assets/16541096/19648022/a330ec56-99f8-11e6-849e-902952633e3b.png)

Irrespective of the ID issue, could you please let me know whether I should make any changes to the model in context of the paper?

Thanks,
Barbara

**Comment by vanaukenk** [comment]
Hi @BarbaraCzub 

Thanks for the link to the model.  Here are a few initial suggestions:

1) Since LEGO models are representations of the activity flows of a process, you will want to represent Bdnf using its corresponding molecular function, rather than just Bdnf by itself.  You would then relate the activity of Bdnf, and the mirs, to the larger biological process of myotube differentiation.

2) If you represent Bdnf with its activity, then I would use the has_input relation within each of the mir annotons to show the target of the binding, rather than the has_input relation between Bdnf and the process of 'gene silencing by miRNA'.

I'll take another look later today.

**Comment by BarbaraCzub** [comment]
Thanks @vanaukenk ,

Could you please have a look at the model and check whether I've understood correctly what you meant based on the changes I made?

Thanks,
Barbara

**Comment by vanaukenk** [comment]
Hi @BarbaraCzub 

I'm looking at the model again, and wondering about the miRNA binding by mir-206 and mir-1a-1.  Is that binding enabled by a complex containing both miRNAs or is each one believed to act separately?  If separately, then we'd need to split out that activity into two separate activities enabled by each mir independently.

Thanks,
--Kimberly

**Comment by vanaukenk** [comment]
Also, have you taken a look at this paper for annotation?

https://www.ncbi.nlm.nih.gov/pubmed/22081998 - Brain-derived neurotrophic factor expression is repressed during myogenic differentiation by miR-206.

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 

Both miRs belong to the same miR family, i.e. the contain the same seed sequence and are both expected to bind to the target miR in Figure 5a. So in traditional annotation I would probably use the IGI evidence code.

Barbara

**Comment by BarbaraCzub** [comment]
This was discussed in the 25 10 2016 annotation call: http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-10-25
Paper: https://www.ncbi.nlm.nih.gov/pubmed/24804980 (Figure 5a)
Related review: http://www.ncbi.nlm.nih.gov/pubmed/22596319 suggested by @rebeccafoulger 

Based on these guidelines http://geneontology.org/page/regulation it seems ok to annotate to positive regulation of [process] to indicate 'maintenance' of this [process].
process
[r] regulation of [process]
[i] negative regulation of [process]
[i] downregulation of [process]
[i] inhibition of [process]
[i] termination of [process]
i] positive regulation of [process]
[i] activation of [process]
[i] maintenance of [process]
[i] upregulation of [process]

I originally intended to annotate 'GO:0010831 positive regulation of myotube differentiation' which seems ok in view of the guidelines cited above.

However, the definition of GO:0014902 myotube differentiation is: 'The process in which a relatively unspecialized cell acquires specialized features of a myotube cell. Myotube differentiation starts with myoblast fusion and the appearance of specific cell markers (this is the cell development step). Then individual myotubes can fuse to form bigger myotubes and start to contract. Myotubes are multinucleated cells that are formed when proliferating myoblasts exit the cell cycle, differentiate and fuse.'

The above definition seems to suggest that in this case the positive regulation GO term GO:0014902 myotube differentiation refers specifically to activation/induction of the differentiated state, as it states that an undifferentiated cell is becoming more specialised. Therefore, I thought that this positive regulation term would not be suitable to describe the findings from this paper/Figure 5a.

As mentioned in the annotation call, I will be happy to use the 'GO:0010831 positive regulation of myotube differentiation', as @rachhuntley suggests, however, only if its definition gets modified to fit the overall process regulation definition guidelines: http://geneontology.org/page/regulation 
(atm the definition of this GO:0010831 term seems to go against these guidelines, which clearly state that 'positive regulation' can mean 'maintenance' (as well as, but not only, 'activation/induction').

@tberardini could you please advise how I should proceed with this?
@RLovering 

Thanks,
Barbara

**Comment by tberardini** [comment]
I updated the definition:

-def: "Any process that increases the frequency, rate or extent of myotube differentiation. 

+def: "Any process that **activates, maintains or** increases the frequency, rate or extent of myotube differentiation. 

Can we close?

**Comment by BarbaraCzub** [comment]
I am happy with this solution @tberardini 
I'll update my annotations, when the updated definition shows up in QuickGO. (How much time should I expect this will take?)
Thank you,
Barbara

@RLovering 
@rachhuntley

**Comment by tberardini** [comment]
I'm not sure how quickly ;-) QuickGO is updated.  I would say a week at the most.  

Thanks, @BarbaraCzub, will close this now.  Whew.
