### ISSUE TITLE
NTR: general term for vesicle tethering

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12542]
we have
GO:0090522	vesicle tethering involved in exocytosis
but no general vesicle tethering term
(the parent of this is targeting which doesn't seem quite right)?

we have a general terms for fusion and docking 
GO:0006906	vesicle fusion
GO:0048278	vesicle docking

**Comment by ValWood** [comment]
The paper I am reading implies that 'tethering' is the first step of fusion for endocytosis. I don't know if this is general bit this isn't how it is currently modelled for endocytosis.

**Comment by ValWood** [comment]
tehtering complexes:
TRAPP complex
Exosome
HOPS/CORVET

**Comment by mcourtot** [comment]
Tagging @paolaroncaglia and will discuss with her when she's back.

**Comment by dosumis** [comment]
Need to make sure any changes in definitions are co-ordinated with the definitions of subclasses for synaptic vesicle tethering, docking, priming fusion etc.

**Comment by ValWood** [comment]
useful recent review on tethers
http://www.ncbi.nlm.nih.gov/pubmed/27243008
![tether](https://cloud.githubusercontent.com/assets/7359272/17002436/2ca6d79c-4ec3-11e6-8c61-7e0deeb3f75b.jpg)

review also includes model of mechanisms for some tehters

**Comment by hattrill** [comment]
Hi Val,

A quite while back I looked at the D.mel tethering complexes for our Gene Group pages. I am attaching a text doc with the way we structured the tethering complexes and the definitions associated with the groups. This is done from an evoluntionary and functional point of veiw, so may not represent the structure you want in the GO, but it may help.
[tethering.txt](https://github.com/geneontology/go-ontology/files/377609/tethering.txt)

**Comment by ValWood** [comment]
tethering.txt

cool, I'm sure that will be useful

**Comment by dosumis** [comment]
> GO:0090522 vesicle tethering involved in exocytosis
> but no general vesicle tethering term
> (the parent of this is targeting which doesn't seem quite right)?

vesicle tethering involved in exocytosis:  "The initial long-distance interaction between secretory vesicles and exocytotic sites on target membranes resulting in the capture and stabilization of vesicles prior to SNARE-mediated docking and fusion."

Can you suggest a definition that is independent of exocytosis?
(Agree that targeting is not a good parent class)

**Comment by ValWood** [comment]
Hi David,

Vesicle tethering occurs at multiple steps... the best summary I have seen is 
https://cloud.githubusercontent.com/assets/7359272/17002436/2ca6d79c-4ec3-11e6-8c61-7e0deeb3f75b.jpg
also in
https://github.com/geneontology/go-ontology/issues/12542

Val

**Comment by dosumis** [comment]
How about this:

'vesicle tethering': "The initial interaction between a vesicle membrane and a membrane to which it is targeted for fusion.  This interaction is mediated by tethering factors (or complexes), which bind phosopholipids or proteins in or associated with both membranes. This process is distinct from and prior to interaction between factors involved in fusion."   [PMID:27243008]

**Comment by ValWood** [comment]
that sounds great to me!

**Comment by dosumis** [comment]
label "vesicle tethering"
definition "The initial, indirect interaction between a vesicle membrane and a membrane to which it is targeted for fusion. This interaction is mediated by tethering factors (or complexes), which interact with both membranes.  Interaction can occur via direct binding  to membrane phospholipids or membrane proteins, or via binding to vesicle coat proteins. This process is distinct from and prior to interaction between factors involved in fusion." [PMID:27243008]

SubClassOf:
- 'cellular component organization'
- 'part of' some 'vesicle targeting'

Note 'vesicle targeting' part_of (some) 'vesicle-mediated transport'

Question:  Should I be adding the various sub-types of tethering (to different membrane bound organelles) based on PMID:27243008 ?

**Comment by ValWood** [comment]
I think its OK if any existing descendants are under here, and we request as we  require if the correct structure is in place...

GO:0090522 vesicle tethering involved in exocytosis
def needs reworking.

**Comment by dosumis** [comment]
> I think its OK if any existing descendants are under here, and we request as we require if the correct structure is in place...

Yep.  Only one I'm aware of is: 

> GO:0090522 vesicle tethering involved in exocytosis
> def needs reworking.

New def:

The initial, indirect interaction between a secretory vesicle membrane and a site of exocytosis in the plasma membrane. This interaction is mediated by tethering factors (or complexes), which interact with both membranes.  Interaction can occur via direct binding  to membrane phospholipids or membrane proteins, or via binding to vesicle coat proteins. This process is distinct from and prior to docking and fusion.
