### ISSUE TITLE
part_of link for new term GO:1905324

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12545]
I have just added these in TermGenie:

    ID: GO:1905323 Label: telomerase holoenzyme complex assembly
    ID: GO:1905324 Label: telomere-telomerase complex assembly

I think the second term, GO:1905324, can be part_of GO:0032200 ! telomere organization. I can't imagine the complex forming in any context that isn't connected with telomere organization.

Two has_part links may also work, but I'm less sure: 

    GO:0032203 telomere formation via telomerase
    has_part GO:1905324

    GO:0007004 telomere maintenance via telomerase
    has_part GO:1905324

I think the complex would need to form for either process.

**Comment by tberardini** [comment]
I'll add this and wait for additional input on the has_part suggestions.

GO:1905324,  part_of GO:0032200 ! telomere organization

**Comment by mah11** [comment]
OK, thanks. I'll ask a couple of experts (who have just sent in community curation, which prompted all this and some FYPO work) about the has_parts.

**Comment by mah11** [comment]
Last week I heard back from one of the experts I asked (Forgot to update this ticket) …

me:
We have a somewhat general question about telomere biology: is formation of the complex of telomere and telomerase involved in both the initial formation of a telomere and in any subsequent extension by telomerase? The answer will help the GO curators represent this accurately in the ontology.

Feng Qiao:
YES

so it looks like the has_part links would be OK.

**Comment by tberardini** [comment]
Ok done!
