### ISSUE TITLE
Changes to slim generation

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12554]
- [ ] Ensure versionIRI/data-version present for both obo and owl
- [ ] Ensure purls resolve - use new style versionIRI format with `/go/releases/`
- [ ] Only use limited relationship set in slims, remove has_part

**Comment by ValWood** [comment]
still valid?

**Comment by cmungall** [comment]
Can move to #14276

**Comment by cmungall** [comment]
looks like some slims still have has_part so leave open for now

**Comment by pgaudet** [comment]
I think this is no longer relevant
