### ISSUE TITLE
ceramide-translocating ATPase activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12559]
Hi
this term is being requested for a student project which finishes in Mid August so if this could be created asap that would be great. Obviously if there are complications this will get delayed.

This request follows the established ontology relations for GO:0004012 phospholipid-translocating ATPase activity and will enable the annotation of human ABCB1, P08183, based on the paper PMID: 8898203. There are 3 new term requests below

1. New GO term: sphingolipid translocation
Definition: The translocation, or flipping, of sphingolipid molecules from one monolayer of a membrane bilayer to the opposite monolayer.
DBXref: GOC:rl
DBXref: GOC:BHF 

2. New GO term: ceramide translocation
Definition: The translocation, or flipping, of ceramide molecules from one monolayer of a membrane bilayer to the opposite monolayer. 
DBXref: GOC:rl
DBXref: GOC:BHF

With the ontology structure: 
GO:0034204 lipid translocation 
> is_a New GO term (1) sphingolipid translocation
> > is_a New GO term (2) ceramide translocation

3 New GO term: ceramide-translocating ATPase activity
Definition: Catalysis of the movement of ceramide from one membrane face to the other ('flippase' activity), driven by the hydrolysis of ATP. 
Exact Synonyms:
ceramide flippase activity
ceramide translocating ATPase activity
DBXref: GOC:rl
DBXref: GOC:BHF

This term would have three parents:
GO:0035620:ceramide transporter activity
> is_a: ceramide-translocating ATPase activity

GO:0046623:sphingolipid-translocating ATPase activity (please add exact synonym sphingolipid translocating ATPase activity and part_of relation to New GO term (1) sphingolipid translocation)
> is_a: ceramide-translocating ATPase activity

New GO term (2) ceramide translocation
> part_of: ceramide-translocating ATPase activity

Thanks

Ruth

**Comment by dosumis** [comment]
Done.

**Comment by RLovering** [comment]
thank you so much
Ruth
