### ISSUE TITLE
TG request for regulation of cohesin unloading

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12558]
I tried to TG this , I got the +ve and -ve terms but not the 'regulation of', could this be added too?

Thanks

Val

**Comment by ValWood** [comment]
[Term]
id: GO:1905338
name: negative regulation of cohesin unloading
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of cohesin unloading." [GO_REF:0000058, GOC:TermGenie, PMID:26687354]
synonym: "down regulation of cohesin unloading" EXACT [GOC:TermGenie]
synonym: "down-regulation of cohesin unloading" EXACT [GOC:TermGenie]
synonym: "downregulation of cohesin unloading" EXACT [GOC:TermGenie]
synonym: "inhibition of cohesin unloading" NARROW [GOC:TermGenie]
intersection_of: GO:0065007 ! biological regulation
intersection_of: negatively_regulates GO:0061774 ! cohesin unloading
created_by: vw
creation_date: 2016-07-26T16:23:58Z


[Term]
id: GO:1905339
name: positive regulation of cohesin unloading
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of cohesin unloading." [GO_REF:0000058, GOC:TermGenie, PMID:26687354]
synonym: "activation of cohesin unloading" NARROW [GOC:TermGenie]
synonym: "up regulation of cohesin unloading" EXACT [GOC:TermGenie]
synonym: "up-regulation of cohesin unloading" EXACT [GOC:TermGenie]
synonym: "upregulation of cohesin unloading" EXACT [GOC:TermGenie]
intersection_of: GO:0065007 ! biological regulation
intersection_of: positively_regulates GO:0061774 ! cohesin unloading
created_by: vw
creation_date: 2016-07-26T16:24:06Z

**Comment by dosumis** [comment]
TG terms passed.  Can you try again to add the regulation one alone via TG template?

**Comment by ValWood** [comment]
- [x] done
