### ISSUE TITLE
activation of meiosis I spindle assembly checkpoint

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12551]
id: GO:new
name: activation of meiosis I spindle assembly checkpoint
def: Any process that starts the inactive process of a meiosis I cell cycle spindle assembly checkpoint.
is_a: GO:1905326 ! positive regulation of meiosis I spindle assembly checkpoint

I modeled this on GO:0090268, and have just added GO:1905326 in TermGenie.

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090687
+name: activation of meiosis I spindle assembly checkpoint
+namespace: biological_process
+def: "Any process that starts the inactive process of a meiosis I cell cycle spindle assembly checkpoint." [GOC:mah]
+is_a: GO:1905326 ! positive regulation of meiosis I spindle assembly checkpoint
+created_by: tanyaberardini
+creation_date: 2016-07-20T16:49:17Z
