### ISSUE TITLE
Dsl1p complex update (and other tethering complex tweaks)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12552]
Later papers by the same author PMID: 20005800 call this “Dsl1 complex”  and a review PMID: 22486903. 
In human it is called NZR complex

also CATCHR family...maybe this could be the term name but I don't know if this covers  other related complexes.
If it does, Dsl1/NZR complex would be clearer, with all other names as synonyms.

NRZ complex comprises NAG, RINT1, and ZW10
members of this complex  appear to have moonlighting function in human PMID: 25364732
and possibly in pombe too (I was puzzliing about this recently but it seems that the moonlighting function are probably conserved, will look into this further as it might be useful for a comment)

**Comment by tberardini** [comment]
Ok, so proposal is this:  Please confirm.

- [ ] rename 'Dsl1p complex' term as ' Dsl1/NZR complex'
- [ ] add related synonym, Dsl1p complex
- [ ] add related synonym, NZR complex
- [ ] add related synonym, CATCHR family complex

**Comment by hattrill** [comment]
Here's my understanding of the CATCHR complexes:
The CATCHR family are/include four complexes: Dsl1, COG, GARP, exocyst (also known as the DCGE group). They are multi-subunit tethering complexes which share low sequence identity but conserved helical bundle structures.

**Comment by ValWood** [comment]
That makes sense. So should CATCHR family complex be broad?
I have been listing the tethering complexes here. I wasn't sure which ones were CATCHR
https://github.com/geneontology/go-ontology/issues/12542

So not HOPS/CORVET or TRAPP complex? (also tethering complexes, but maybe different mechanism?)

Note that in GO COG is called
GO:0017119 - Golgi transport complex 
COG seems better here (its a synonym)
Also the def says 
"In yeast, this complex is called the Sec34/35 complex"
maybe this would be better as a synonym than part of the definitions ( yeast people generally call it COG nowadays?) In fact in pombe and cerevisiae we call the subunits cog1 -cog 8 now....

**Comment by ValWood** [comment]
Hi Tanya,
I'm not sure if 
Dsl1p complex and NZR complex are related or exact? ...they are supposedly describing exactly  the same complex, just in different species ?  but in that case should they be exact?

**Comment by tberardini** [comment]
If they are exactly the same complex, same components, just a different species, then Dsl1p and NZR should be exact synonyms.  I'm not sure what you're getting at by adding in information about other complexes.  Do they relate to this term?  If not, please split that out to another ticket for clarity.  Thanks.

**Comment by ValWood** [comment]
I just satisfied myself that these were identical:

So,
Add comment:
Dsl1/NZR complex comprises Hu ZW10 (Sc Dsl1) , Hu RINT1 (Sc Tip20), Hu NBAS (Sc Sec39)

(this comment is useful because the ZW10/Dsl1 orthology won't be picked up between metazoa to fungi by any of the ortholog predictors... I still cant find the pombe subunit....)

current term has this comment:
See also the molecular function term 'acetolactate synthase activity ; GO:0003984'.
(I'm not sure why...is this a cut and past error, or is it correct?)

**Comment by tberardini** [comment]
@dosumis , reassigning this to you - handle as part of the what looks like a bunch of related vesicle transport/complex issues.

**Comment by dosumis** [comment]
- [x] rename 'Dsl1p complex' term as ' Dsl1/NZR complex'
- [x] add exact synonym, Dsl1p complex
- [x] add exact synonym, NZR complex
- [x] add broad synonym, CATCHR family complex

Also added 'capable_of_part_of 'vesicle tethering'  => classification under 'vesicle tethering complex'

**Comment by hattrill** [comment]
Could I check if all the CATCHR family complexes going to get the "add broad synonym, CATCHR family complex"? (re:vesicle tethering complexes #12555)
