### ISSUE TITLE
vesicle tethering complexes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12555]
Grouping term for vesicle tethering complexes, with links to 'tethering' 
(note this term does not exist yet
https://github.com/geneontology/go-ontology/issues/12542)

GO NEW vesicle tethering complex (related CATCHR complex)
- Dsl1/NZR complex
- COG complex
- GARP complex
- exocyst
- HOPS
- CORVET
- TRAPP 

Note CATCHR is related, it is broader, but it probably only applies to 
Dsl1, COG, GARP, exocyst
see
https://github.com/geneontology/go-ontology/issues/12552
although a recent paper shows 
new publication this week: CATCHR, HOPS and CORVET tethering complexes share a similar architecture.http://www.ncbi.nlm.nih.gov/pubmed/27428774?dopt=Abstract

Update
GO:0017119 - Golgi transport complex 
COG seems better  primary  name here (its  currently a synonym)
Also the def says :
"In yeast, this complex is called the Sec34/35 complex"
Sec34/35 complex would be better as a synonym than part of the definitions ( yeast people generally call it COG nowadays?) In pombe and cerevisiae we call the subunits cog1 -cog 8 now....

**Comment by dosumis** [comment]
Define as 'protein complex' that capable_of_part_of some 'vesicle tethering involved in exocytosis' ?

**Comment by ValWood** [comment]
It isn't just exocytosis. Should it be 

 'protein complex' that capable_of_part_of some 'vesicle tethering involved in vesicle-mediated transport'

**Comment by dosumis** [comment]
Hi Val,

Can you reply to this comment: https://github.com/geneontology/go-ontology/issues/12542#issuecomment-234489783

Cheers,
David

**Comment by dosumis** [comment]
Dsl1/NZR - What is the relationship to Dsl1p complex (GO:0070939).  The definition also mentions tethering.

**Comment by dosumis** [comment]
label "tethring complex"
definition "Any protein complex that plays a role in vesicle tethering."
![image](https://cloud.githubusercontent.com/assets/112839/17141041/999cd012-5342-11e6-8111-684975a2b3c4.png)

**Comment by ValWood** [comment]
> Dsl1/NZR - What is the relationship to Dsl1p complex (GO:0070939)

Dsl1/NZR is the new name for GO:0070939
https://github.com/geneontology/go-ontology/issues/12552
v

**Comment by dosumis** [comment]
GO:0070939 - name changed.  Now classified under tethering complex.

 - [x] Dsl1/NZR GO:0070939 - name changed.  Now classified under tethering complex.
 - [ ] COG complex NEW - add. Need ref that n
 - [ ] GARP complex EXISTS - GO_0000938 Has refs & def mentions tethering.  Now classified under tethering complex
 - [ ] exocyst EXISTS - Need ref for role in tethering
 - [x] HOPS EXISTS - GO_0030897. Has refs & def mentions tethering.  Now classified under tethering complex 
 - [ ] CORVET - GO_0033263 Has refs & def mentions tethering.  Now classified under tethering complex 
 - [ ] TRAPP - GO_0030008 Has refs & def mentions tethering.  Now classified under tethering complex

**Comment by ValWood** [comment]
Characterization of a mammalian Golgi-localized protein complex, COG, that is required for normal Golgi morphology and function.
PMID: 11980916

**Comment by ValWood** [comment]
"exocyst" AND "tethering" 143 refs in PUBMED
This is the earliest PMID: 11703943 (but says 'putative'

This is the earliers review  supporting a tethering role
PMID: 12575943

here's early EXP data
PMID: 16525015

**Comment by dosumis** [comment]
Ta.  Finishing this up now.
