### ISSUE TITLE
NTR: deglycation terms

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12550]
I need to add some new terms to annotate the role of DJ-1/PARK7 in deglycation, as described in PMID:25416785. Note that terms for glycation are not needed because this is a spontaneous process.

All: PMID: 25416785, GOC: PARL, GOC:BF

protein deglycation
The removal of a sugar or dicarbonyl from a glycated protein [PMID:14568004]
is_a: cellular protein modification process ; GO:0006464
Comment: Glycation is a non enzymatic covalent addition of a sugar or dicarbonyl (methylglyoxal, glyoxal) to a protein. Deglycation repairs the glycated amino acids to release repaired proteins.
related synonym: glycated protein repair [PMID: 25416785]

peptidyl-cysteine deglycation
The removal of a sugar or dicarbonyl from a cysteine residue of a glycated protein.
is_a: protein deglycation
is_a: peptidyl-cysteine modification ; GO:0018198
exact synonym: deglycation of N-acetylcysteine [PMID:25416785]

peptidyl-arginine deglycation
The removal of a sugar or dicarbonyl from an arginine residue of a glycated protein.
is_a: protein deglycation
is_a: peptidyl-arginine modification ; GO:0018195
exact synonym: deglycation of N-acetylarginine [PMID:25416785]

peptidyl-lysine deglycation
The removal of a sugar or dicarbonyl from a lysine residue of a glycated protein.
is_a: protein deglycation
is_a: peptidyl-lysine modification ; GO:0018205
exact synonym: deglycation of N-acetyllysine [PMID:25416785]

protein deglycation, methylglyoxal removal
The removal of methylglyoxal from a glycated protein, to form lactate and a deglycated protein.
exact synonym: protein deglycation of methylglyoxal-glycated protein [PMID: 25416785]
is_a: protein deglycation
is_a: methylglyoxal metabolic process ; GO:0009438
is_a: lactate biosynthetic process ; GO:0019249

protein deglycation, glyoxal removal
The removal of glyoxal from a glycated protein, to form glycolate and a deglycated protein.
exact synonym: protein deglycation of glyoxal-glycated protein [PMID: 25416785]
is_a: protein deglycation
is_a: glyoxal metabolic process ; GO:1903189
is_a: glycolate biosynthetic process ; GO:0046295

glutathione deglycation 
The removal of a sugar or dicarbonyl from glycated glutathione. Glutathione is the tripeptide glutamylcysteinylglycine.
is_a: glutathione metabolic process ; GO:0006749

The amino acid specificity is important to capture because some other deglycases only act on lysines, so it’s an important feature of the DJ-1 protein I’m annotating.

Any comments welcome..
Thank you.

**Comment by tberardini** [comment]
Looks good, Becky.  Cool biology.  Can you do the edits or do you need me to do them?  OE is good to use, provided you have the right save filters in place. 

Filter is this one:

https://github.com/geneontology/go-ontology/issues/12315
(comment from DOS on March 3)

**Comment by ValWood** [comment]
Hi Becky,

Will this also be a child of protein repair? GO:0030091
and are there MF terms for these modification process terms ?
Interested as pombe has a PARK7 ortholog,  I'll ISS to these annotations at some point.

Val

**Comment by rebeccafoulger** [comment]
Hi Val,
I hadn't spotted the 'protein repair' term but it looks like a good parent (The process of restoring a protein to its original state after damage by such things as oxidation or spontaneous decomposition of residues) so will add that in- thanks.

I decided against adding a 'protein deglycase' MF term because the deglycation enzyme mechanism seems to vary between proteins (see PMID:14568004) so I don't think it would add any information.

On the annotation side, I'll be updating the annotations to (at least) human PARK7 once I've added in these new deglycation terms- PMID:25416785 suggests that the glyoxalase activity previously assigned to PARK7 actually reflects the deglycation reaction, and therefore I'll check and most likely remove the glyoxalase terms.

**Comment by ValWood** [comment]
Sounds good, I'll just do my ISS to GO:0006464 for SPAC22E12.03c

**Comment by ValWood** [comment]
Isn't it better to do the MF term if possible, than the BP (which could come from an F-P link) - it doesn't matter if the mechanism is different if the  activity is the same? (it would be better for LEGO  modelling later)

**Comment by rebeccafoulger** [comment]
Okay, I will add (in addition to the BP terms) a molecular function term based on:
http://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-4.2.1.bm

protein deglycase activity ; GO:NEW
Catalysis of the removal of a sugar or dicarbonyl from a lysine residue of a glycated protein.
is_a: hydro-lyase activity ; GO:0016836 (EC:4.2.1.-)
synonym: protein deglycating enzyme [PMID:26873906]

There are more specific RHEA reactions I could map too, but I think we tried to get a 1:1 mapping between GO MFs and RHEA so these would require individual more specific MF terms:
RHEA:49548, MetaCyc:RXN-17630 (arginine substrate)
RHEA:49556, MetaCyc:RXN-17634 (cysteine substrate)
RHEA:49552, MetaCyc:RXN-17632  (lysine substrate)
Note that the RHEA reactions are (I think) describing the removal of MGO from the protein so are more specific than my suggested process terms (which can be MGO, GO or another glycation residue). For completeness therefore, I could add GO terms for the 3 reactions and they wouldn't be completely redundant with the BP terms.

**Comment by ValWood** [comment]
I think that makes sense...getting MF will help later.

**Comment by rebeccafoulger** [comment]
Added the following terms:
protein degylcase activity ; GO:0036524
protein deglycation ; GO:0036525
peptidyl-cysteine deglycation ; GO:0036526
peptidyl-arginine deglycation ; GO:0036527
peptidyl-lysine deglycation ; GO:0036528
protein deglycation, glyoxal removal ; GO:0036529
protein deglycation, methylglyoxal removal ; GO:0036530
glutathione deglycation ; GO:0036531

For now I've just added the generic MF term, and added the RHEA and MetaCyc references into the definition references for GO:0036524 so they can be easily found. Will see how I get on with these as I re-curate.
