### ISSUE TITLE
GO:0052193- movement in symbiont environment

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12553]
The following term doesn't have any annotations or mappings. I can't think of any use cases for it (it was possibly created just to be a pair to the 'movement in host' terms). So after discussion with Jane I'm proposing its obsoletion:

movement in symbiont environment ; GO:0052193
The directed movement of an organism or motile cell on, within or near its symbiont organism. The symbiont is defined as the smaller of the organisms involved in a symbiotic interaction.

Thanks!

**Comment by dosumis** [comment]
Sent request.  Proposed obsoletion data = 8th Sept.
