### ISSUE TITLE
update def cleavage furrow

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12556]
Current def:
In animal cells, the first sign of cleavage, or cytokinesis, is the appearance of a shallow groove in the cell surface near the old metaphase plate. A contractile ring containing actin and myosin is located just inside the plasma membrane at the location of the furrow. Ring contraction is associated with centripetal growth of the membrane that deepens the cleavage furrow and divides the cytoplasm of the two daughter cells. While the term 'cleavage furrow' was initially associated with animal cells, such a structure occurs in many other types of cells, including unicellular protists. Source: ISBN:0805319409

Does not really say what the "cleavage furrow" is ;)

The cleavage furrow is a membrane invagination that.....etc?
https://github.com/geneontology/go-ontology/issues/12546

**Comment by tberardini** [comment]
From its parentage, "A cell surface furrow that appears in animal cells as a first sign of cleavage, or cytokinesis.  It is a shallow groove in the cell surface near the old metaphase plate. ........."

**Comment by ValWood** [comment]
Cleavage furrow is currently defined.
In animal cells, the first sign of cleavage, or cytokinesis, is the appearance of a shallow groove in the cell surface near the old metaphase plate. A contractile ring containing actin and myosin is located just inside the plasma membrane at the location of the furrow. Ring contraction is associated with centripetal growth of the membrane that deepens the cleavage furrow and divides the cytoplasm of the two daughter cells. While the term 'cleavage furrow' was initially associated with animal cells, such a structure occurs in many other types of cells, including unicellular protists.

 Suggest:
The cleavage furrow is a plasma membrane invagination at the cell division site. The cleavage furrow begins as a shallow  groove and eventually deepens to divide the cytoplasm.

NTR: Cleavage furrow rim PMID:27082518
The part of the cleavage furrow closest to the  cell surface.

NTR: Cleavage furrow leading edge PMID:27082518
The 'trough' of the cleavage furrow. This is the part of the cleavage furrow closest to the contractile ring.

(I checked these proposed  defs with the authors of this paper PMID:27082518, and they have been approved by them)

**Comment by tberardini** [comment]
Changed def for 'cleavage furrow', moved one section of old def to comment.

-def: "In animal cells, the first sign of cleavage, or cytokinesis, is the appearance of a shallow groove in the cell surface near the old metaphase plate. A contractile ring containing actin and myosin is located just inside the plasma membrane at the location of the furrow. Ring contraction is associated with centripetal growth of the membrane that deepens the cleavage furrow and divides the cytoplasm of the two daughter cells. While the term 'cleavage furrow' was initially associated with animal cells, such a structure occurs in many other types of cells, including unicellular protists." [ISBN:0805319409]
+def: "The cleavage furrow is a plasma membrane invagination at the cell division site. The cleavage furrow begins as a shallow groove and eventually deepens to divide the cytoplasm." [GOC:vw, ISBN:0805319409]
+comment: While the term 'cleavage furrow' was initially associated with animal cells, such a structure occurs in many other types of cells, including unicellular protists.

Added terms:

 [Term]
+id: GO:0090688
+name: cleavage furrow rim
+namespace: cellular_component
+def: "The 'trough' of the cleavage furrow. This is the part of the cleavage furrow closest to the contractile ring." [GOC:vw, PMID:27082518]
+is_a: GO:0044464 ! cell part
+relationship: part_of GO:0032154 ! cleavage furrow

+[Term]
+id: GO:0090689
+name: cleavage furrow leading edge
+namespace: cellular_component
+def: "The part of the cleavage furrow closest to the cell surface." [GOC:vw, PMID:27082518]
+is_a: GO:0044464 ! cell part
+relationship: part_of GO:0032154 ! cleavage furrow

**Comment by ValWood** [comment]
Thanks Tanya!
