### ISSUE TITLE
NTR:intracellular chloride channel activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12564]
(now featuring in the correct place, thanks to Paola)

Could I have " intracellular chloride channel activity" as a child of "GO:0005254 chloride channel activity" and a parent of "GO:0005229 intracellular calcium activated chloride channel activity"?

-GO:0005254 chloride channel activity
-New Term: intracellular chloride channel activity
-GO:0005229 intracellular calcium activated chloride channel activity

intracellular chloride channel activity:
“Enables the transmembrane transfer of chloride across the membrane of an intracellular compartment. Transport by a channel involves catalysis of facilitated diffusion of a solute (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel, without evidence for a carrier-mediated mechanism.” PMID:23092411

Thanks

**Comment by ukemi** [comment]
[Term]
+id: GO:0061778
+name: intracellular chloride channel activity
+namespace: molecular_function
+def: "Enables the transmembrane transfer of chloride across the membrane of an intracellular compartment. Transport by a channel involves catalysis of facilitated diffusion of a solute (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel, without evidence for a carrier-mediated mechanism." [GOC:dph, PMID:23092411]
+is_a: GO:0005254 ! chloride channel activity
+created_by: dph
+creation_date: 2016-08-02T09:37:15Z
+
