### ISSUE TITLE
Please add relationships to new endonuclease complex terms

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12569]
GO:1905347 endodeoxyribonuclease complex (NEW in TG)
is_a GO:1905348 endonuclease complex (NEW in TG)

and:
GO:1902555 endoribonuclease complex (exisiting term)
is_a GO:1905348 endonuclease complex (NEW in TG)

I had to create is_a GO:1905348 endonuclease complex to provide the hierarchy for the two child terms.

Can you also please add 
synonym: Mus81-Eme1 complex [related]
synonym: Mus81-Eme2 complex [related]
to GO:1905347 endodeoxyribonuclease complex
(I forgot as the template doesn't prompt you nicely to add synonyms like the FF would)

Thanks,
Birgit

**Comment by ValWood** [comment]
Hi Birgit
This is the term we have  already been using for mus81-eme1 complex:

GO:0048476
Name	Holliday junction resolvase complex
Ontology	Cellular Component
Definition	A protein complex that mediates the conversion of a Holliday junction into two separate duplex DNA molecules; the complex includes a single- or multisubunit helicase that catalyzes the extension of heteroduplex DNA by branch migration and a nuclease that resolves the junction by nucleolytic cleavage. 
PMID:11207366 PMID:12374758

This is going to e one of the problems of grouping complex by function, as most have numerous MF's
(mus81-Eme1 is currently narrow synonym),  but if there are others I'd favour a  child term to represent this particular complex.

This is also (one of many reasons) why I like specific terms for conserved complexes...its better for  comparisons if we all annotate to exactly the same complex rather than  a "MF complex" grouping term (which could apply to many unrelated complexes) 
v

**Comment by ukemi** [comment]
Hi Val and Birgit,

I already approved the "MF complex" terms. On the one hand, I see Val's concern but on the other hand, they make for a very nice way of automatically classifying complexes. It seems that the Holliday junction resolvase complex is capable of both helicase activity and endodeoxyribonuclease activity. Since we already have Holliday junction helicase complex part_of Holliday junction resolvase complex, perhaps we should also add Holliday junction resolvase complex has_part endodeoxyribonuclease complex.

**Comment by ValWood** [comment]
That would work,  but I think "holiday resolvase complex" is an alternative name for 
Mus81 complex ...would need to check @mah11  would probably know.

This complex
http://www.ncbi.nlm.nih.gov/pubmed?term=11719193

its often called the "mus81-eme1 holiday resolvase complex" (in many species). 

look at this list:
http://www.ncbi.nlm.nih.gov/pubmed?cmd=Search&term=(SPCC4G3.05c+OR+mus81+OR+slx3)+AND+(pombe+OR+fission+yeast)

I think we used holiday resolvase complex originally to avoid gene names in complex terms  (which editors often object to). Now we have another term for the exact same complex?

If we do this, term would we use  for mus81 complex to inherit all of the relevant parents? We'd need to annotate  a single complex to multiple complex terms describing  different activities of the same complex...?????

**Comment by ValWood** [comment]
actually the existing term
GO:0048476
Name Holliday junction resolvase complex

might not be correct. I don't think the mus81-eme1 comlpex has helicase activity...where does this part come from?

**Comment by ValWood** [comment]
I'm a bit confused now :)
I asked Paul Russell.

It would be nice if there was a term which people could use to retrieve the mus81-eme1complex in any organism (conserved from yeast to human).

**Comment by bmeldal** [comment]
Hi Val,

exactly, I didn't think MUS81-EME1/2 have helicase activity but are also found at non-HL-type stalled folks, so Holliday junction resolvase complex was too narrow for me. I should have pointed that out in my original ticket. 

This is what I'm currently using for the complex Def in CP (not released yet, of course):
"Structure-specific endonuclease that plays an important role in rescuing stalled replication forks and resolving the mitotic recombination intermediates in eukaryotes. The complex recognizes the branched DNA intermediates and typically cleaves 3-6 base pairs of the 5-prime regions of the junction crossover point. Preferentially cleaves four-way DNA junctions, such as nicked Halliday Junctions (nHJs), D-loops, 3-prime flap DNA substrates that contain an exposed 5-prime DNA strand end at or close to the junction crossover point and replication forks, via the “nick and counternick” mechanism. DNA binding induces conformational changes in the linkers connecting the nuclease and HhH2 domains of MUS81 and EME1, which transforms the complex from a compact to an open state. These changes unmask the hydrophobic wedge that separates pre‐ and post‐nick duplex and create the 5-prime end binding pocket facilitating the DNA substrate bending by the complex, ultimately placing the incision strand at the active site of MUS81."

>perhaps we should also add Holliday junction resolvase complex has_part endodeoxyribonuclease complex.

Yes, that might work.

I agree with Val, we need to rearrange the ontology so all instances of MUS81-EME1/2 are annotated to the same term.

Thanks,
Birgit

**Comment by ValWood** [comment]
I think maybe the bacterial equivalent (or bacterial resolvase), and another human complex might have branch migration activity, gleaned from this abstract 

http://europepmc.org/abstract/MED/12374758
but this does not apply to the Mus81 containing complex...

**Comment by ukemi** [comment]
Is there any consensus here?  I'm not sure what I should do.

**Comment by ValWood** [comment]
I'm waiting to hear back from Paul Russell.....

**Comment by ukemi** [comment]
Any update on this?

**Comment by bmeldal** [comment]
Have you heard back from Paul, @ValWood ?

These complexes are now released:
Search for mus81 AND eme*
http://www.ebi.ac.uk/intact/complex/?q=mus81+AND+eme*

**Comment by pgaudet** [comment]
@ValWood have you ever heard back from Paul Russell ? 
If not - what do we do ?

**Comment by ValWood** [comment]
I didn't but I can't trace the e-mail so I am not now sure if I contacted him about this particular issue.

However, I think we can solve the problem simply.
Resolvase is not a helicase as far as I can tell, but sometimes "branch-migration associated". "Resolvase" is referring to the specific endodeoxyribonuclease activity that resolves 4-way DNA intermediates. Do you agree?

I'd be inclined to obsolete the original 
GO:0048476    Holliday junction resolvase complex
because it is misdefined, it only has 19 EXP annotations (3 are PomBase, we can migrate)

I guess a new term for the conserved complex along the lines

GO:1905347 endodeoxyribonuclease complex
--NEW  Mus81-Eme1/2 Holliday junction resolvase complex 
An endodeoxyribonuclease complex, with minimally two ERCC4 family  members (Mus81 and Eme1 or 2) which resolves 4-way DNA intermediates (GO:0008821 crossover junction endodeoxyribonuclease activity)

would work? @bmeldal ?

**Comment by bmeldal** [comment]
Val's complex def sounds good.

BUT - looking at my def for the specific complex I think the activity is a little too focused on HJs:

>GO:0008821 crossover junction endodeoxyribonuclease activity
Catalysis of the endonucleolytic cleavage at a junction such as a reciprocal single-stranded crossover between two homologous DNA duplexes (Holliday junction).
Synonym | Type
Holliday junction resolvase activity | narrow
Holliday junction-cleaving endonuclease activity | **exact**
Holliday junction-resolving endoribonuclease activity | narrow
RusA Holliday junction resolvase activity | narrow
RusA endonuclease activity | narrow
RuvC endonuclease activity | narrow
SpCCe1 Holliday junction resolvase activity | narrow
cruciform-cutting endonuclease activity | exact
endonuclease RuvC activity | narrow
endonuclease VII activity | narrow

as the complex "Preferentially cleaves four-way DNA junctions, such as nicked Halliday Junctions (nHJs), D-loops, 3-prime flap DNA substrates that contain an exposed 5-prime DNA strand end at or close to the junction crossover point and replication forks, via the “nick and counternick” mechanism."

If we link the complex to this activity we'd have to loosen the activity def. Or create a new activity... [I'd go for the former]

**Comment by ValWood** [comment]
OK  loosen the def.

It might also be useful to slot the existing term in here, with the new definition

GO:1905347 endodeoxyribonuclease complex
--GO:0048476 OLD Holliday junction resolvase complex (with revised def)
----NEW Mus81-Eme1/2 Holliday junction resolvase complex

rather than obsolete. That way the existing E.coli annotations would not require reannotation.

**Comment by bmeldal** [comment]
I was suggesting to relax the defs so they don't restrict to Holliday Junction...

**Comment by ValWood** [comment]
Ah ok that makes sense.

**Comment by bmeldal** [comment]
Shall I suggest new defs? Or do you want to do it, @ValWood ?

**Comment by ValWood** [comment]
Could you?

**Comment by bmeldal** [comment]
I’ve tried to link the action points with the relevant comments from above that led to these decisions.

- [ ] **add synonyms to GO:1905347 endodeoxyribonuclease complex**

> from original request (was overlooked)

Mus81-Eme1 complex [narrow]
Mus81-Eme2 complex [narrow]

- [ ] **fix GO:0048476 Holliday junction resolvase complex**

From Val:

>I don't think the mus81-eme1 complex has helicase activity...where does this part come from?
>Resolvase is not a helicase as far as I can tell, but sometimes "branch-migration associated". "Resolvase" is referring to the specific endodeoxyribonuclease activity that resolves 4-way DNA intermediates. Do you agree?
>it’s often called the "mus81-eme1 holiday resolvase complex" (in many species).
>An endodeoxyribonuclease complex, with minimally two ERCC4 family members (Mus81 and Eme1 or 2) which resolves 4-way DNA intermediates (GO:0008821 crossover junction endodeoxyribonuclease activity)

Def:
-A protein complex that mediates the conversion of a Holliday junction into two separate duplex DNA molecules; the complex **includes a single- or multisubunit helicase that catalyzes the extension of heteroduplex DNA by branch migration** *[to be removed!]* and a nuclease that resolves the junction by nucleolytic cleavage. PMID:11207366 PMID:12374758
+An endodeoxyribonuclease complex that resolves the 4-way DNA intermediates of a Holliday junction into two separate duplex DNA molecules. Can be branch-migration associated. PMID:11207366 PMID:12374758 [PMIDs still relevant?]
+is_a GO:1905347 endodeoxyribonuclease complex
+capable_of GO:0008821 crossover junction endodeoxyribonuclease activity
Synonym | Type
resolvasome | exact
Mus81-Eme1 complex | **related**
+Mus81-Eme2 complex | related
+Mus81-Eme1 holliday resolvase complex | narrow
+Mus81-Eme2 holliday resolvase complex | narrow


- [ ] **create a new term for GO:NEW Mus81-Eme complex**

from Val:
>It might also be useful to slot the existing term in here, with the new definition
>GO:1905347 endodeoxyribonuclease complex
--GO:0048476 OLD Holliday junction resolvase complex (with revised def)
----NEW Mus81-Eme1/2 Holliday junction resolvase complex
>rather than obsolete. That way the existing E.coli annotations would not require reannotation.

I have an issue with making a specific Mus81-Eme1/2 Holliday junction resolvase complex. This is akin to the issue of GO:1990328 RNA polymerase II, RPB4-RPB7 subcomplex (https://github.com/geneontology/go-ontology/issues/10931)
If we want a term for the Mus81-Eme1/2 complex it should be agnostic to the specific location it’s found at as it acts on various types of DNA break sites:

Def: 
Structure-specific endodeoxyribonuclease complex that plays an important role in rescuing stalled replication forks and resolving the mitotic recombination intermediates in eukaryotes. Recognizes the branched DNA intermediates and typically cleaves 3-6 base pairs of the 5-prime regions of the junction crossover point. Preferentially cleaves four-way DNA junctions, such as nicked Halliday Junctions (nHJs), D-loops, 3-prime flap DNA substrates that contain an exposed 5-prime DNA strand end at or close to the junction crossover point and replication forks, via the “nick and counternick” mechanism. 
is_a GO:1905347 endodeoxyribonuclease complex
Synonyms:
Mus81-Eme1 complex [exact]
Mus81-Eme2 complex [exact]
Mus81-Eme1 holliday resolvase complex [related]
Mus81-Eme2 holliday resolvase complex [related]

Of course, this looses the link to GO:0048476 Holliday junction resolvase complex but Mus81-Eme complex has more functions than the resolvase complex.

**fix GO:0009379 Holliday junction helicase complex**

from Val:
>I don't think the mus81-eme1 complex has helicase activity...where does this part come from?

- [ ] remove part_of link from GO:0009379 Holliday junction helicase complex to GO:0048476 Holliday junction resolvase complex
-part_of GO:0048476 Holliday junction resolvase complex

- [ ] fix def of GO:0009379 Holliday junction helicase complex

-A DNA helicase complex that forms part of a Holliday junction resolvase complex, where the helicase activity is involved in the migration of the junction branch point. The best-characterized example is the E. coli RuvAB complex, in which a hexamer of RuvB subunits possesses helicase activity that is modulated by association with RuvA. PMID:16935884 PMID:9442895
+A DNA helicase complex found **at Holliday junctions** where the helicase activity is involved in the migration of the junction branch point. The best-characterized example is the E. coli RuvAB complex, in which a hexamer of RuvB subunits possesses helicase activity that is modulated by association with RuvA. PMID:16935884 PMID:9442895

I hope I covered everything!

**Comment by pgaudet** [comment]
Hi @bmeldal @ValWood 
Do we need the new term 'Mus81-Eme complex' ? This one really does sound like an instance. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Well, according to our discussions in the intervening 18 months Mus81-Eme doesn't differ from endodeoxyribonuclease complex apart from its specific substrates. 

If we cull the term request, can we add the related synonyms? I think they are on the action list above already.

**Comment by ValWood** [comment]
I'm confused. I don't see this term. I am using

GO:0048476    Holliday junction resolvase complex
which has  "Mus81-Eme complex" as a narrow synonym?

this seems fine?

**Comment by ValWood** [comment]
Ah OK I just read the old thread.

**Comment by ValWood** [comment]
Not that the resolvase complex is both a helicase and an endonuclease  so it could have these parents?

**Comment by bmeldal** [comment]
Val, in the summary above I quoted you:

> - I don't think the mus81-eme1 complex has helicase activity...where does this part come from?
Resolvase is not a helicase as far as I can tell, but sometimes "branch-migration associated". 
> - "Resolvase" is referring to the specific endodeoxyribonuclease activity that resolves 4-way DNA intermediates. Do you agree?

So the suggestion was to remove the link from resolvase to helicase.

**Comment by pgaudet** [comment]
Changes are here: 
https://github.com/geneontology/go-ontology/commit/1f1388b19643c7b8d1d343e03471120d46222fb3

Let me know if I should fix anything else. 

Thanks, Pascale

**Comment by ValWood** [comment]
The definition is:

Definition | 
-- | --
A protein complex that mediates the conversion of a Holliday junction into two separate duplex DNA molecules; the complex includes a single- or multisubunit helicase that catalyzes the extensio

**Comment by pgaudet** [comment]
Seems truncated - can you write the full definition you want ?

**Comment by ValWood** [comment]
This is the existing definiton. I looked around and I think Birgit is correct this complex does not have helicase activity The associated helicase is Rqh1. This part of the existing  def needs to be removed.

v

**Comment by ValWood** [comment]
GO:0048476    JSON
Holliday junction resolvase complex
Cellular Component

Definition (GO:0048476 GONUTS page)
A protein complex that mediates the conversion of a Holliday junction into two separate duplex DNA molecules; the complex includes a single- or multisubunit helicase that catalyzes the extension of heteroduplex DNA by branch migration and a nuclease that resolves the junction by nucleolytic cleavage. PMID:11207366 PMID:12374758

suggest

GO:0048476    JSON
Holliday junction resolvase complex
Cellular Component

Definition (GO:0048476 GONUTS page)
A protein complex that mediates the conversion of a Holliday junction into two separate duplex DNA molecules; the complex ~includes a single- or multisubunit helicase that~ catalyzes the extension of heteroduplex DNA by branch migration and *has* nuclease that resolves the junction by nucleolytic cleavage. PMID:11207366 PMID:12374758

**Comment by bmeldal** [comment]
@ValWood 

This is the new def, from the merge branch (and taken from the above discussion from 2017):

id: GO:0048476
name: Holliday junction resolvase complex
namespace: cellular_component
-def: "A protein complex that mediates the conversion of a Holliday junction into two separate duplex DNA molecules; the complex includes a single- or multisubunit helicase that catalyzes the extension of heteroduplex DNA by branch migration and a nuclease that resolves the junction by nucleolytic cleavage." [PMID:11207366, PMID:12374758]
+def: "An endodeoxyribonuclease complex that resolves the 4-way DNA intermediates of a Holliday junction into two separate duplex DNA molecules. Can be branch-migration associated." [PMID:11207366, PMID:12374758]
subset: goslim_pir
synonym: "Mus81-Eme1 complex" NARROW []
+synonym: "Mus81-Eme1 holliday resolvase complex" NARROW []
+synonym: "Mus81-Eme2 complex" RELATED []
+synonym: "Mus81-Eme2 holliday resolvase complex" NARROW []
synonym: "resolvasome" EXACT [PMID:11207366]
-is_a: GO:0032991 ! protein-containing complex
-is_a: GO:0044424 ! intracellular part
+intersection_of: GO:1905347 ! endodeoxyribonuclease complex
+intersection_of: capable_of GO:0008821 ! crossover junction endodeoxyribonuclease activity

@pgaudet 
>synonym: "Mus81-Eme1 complex" NARROW []
should be RELATED synonym, please.

>-is_a: GO:0044424 ! intracellular part
Why remove this rather than making it an intersection? Or do we inherit it from the complex parent anyway?

**Comment by ValWood** [comment]
OK!

but I think  
"Mus81-Eme1 complex" NARROW
is correct?

**Comment by bmeldal** [comment]
Either both, Mus81-Eme1 complex and Mus81-Eme2 complex, need to be NARROW or RELATED.
We had RELATED above but I can't remember why.

**Comment by pgaudet** [comment]
Definition was already OK. 
Changed all synonyms to NARROW. 

Thanks !
