### ISSUE TITLE
Add taxon restrictions for GO:0009787 regulation of abscisic acid-activated signaling pathway

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#12567]
I noticed that there were some IEA annotations for rat, chicken, cow and other non-plant organisms to children of this term. Unless there is some interesting biology that I am unaware of it seems that this term and its children should exclude non plants

relationship: only_in_taxon NCBITaxon:33090 {id="GOTAX:0000023"} ! Viridiplantae

**Comment by ukemi** [comment]
Looks like it might be interesting biology. Here is the reference to the original annotation, PMID:19667068.

-D

**Comment by lreiser** [comment]
Wow... that is awesome..and freaky.
guess we can close this .
