### ISSUE TITLE
NTR: actin body PMID:26124291

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12562]
A large cytoplasmic actin containing structure observed in quiescent cells in S pombe and S. cerevisiae.  They contain a subset of  actn cytoskeletal proteins and are resistant to latrunculin.

also
Actin bodies in yeast quiescent cells: an immediately available actin reserve?
PMID: 16914523

**Comment by dosumis** [comment]
GO:0099079
![image](https://cloud.githubusercontent.com/assets/112839/17969650/10146ecc-6acb-11e6-8bcb-b0f9e091895b.png)
