### ISSUE TITLE
Add taxon restiction for "regulation of cell migration"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12566]
regulation of cell migration GO:0030334
regulation of phagocytosis GO:0050764
https://github.com/geneontology/go-annotation/issues/1421

never in  yeast? exceptions?

**Comment by ukemi** [comment]
PMID:27072657?

**Comment by ValWood** [comment]
I think we discussed this in another ticket, this  growing towards another cell during mating isn't really migration (which is a type of  'movement'). The cell doesn't move from one place to another, it just grows a projection towards a mating partner.

**Comment by ValWood** [comment]
this says its done?
https://github.com/geneontology/go-ontology/issues/12410

**Comment by ukemi** [comment]
I see locomotion never in Dikarya.

**Comment by ValWood** [comment]
OK that shpuld do it...this is probably a time issue, although I thought the taxon offending annotations were dropped in-between proper updates @mah11 ? maybe  not

**Comment by ukemi** [comment]
There is also a phagocytosis never in Fungi restriction. Should I close this or leave it open for you to investigate further?

**Comment by mah11** [comment]
> I thought the taxon offending annotations were dropped in-between proper updates

I don't understand exactly what you mean by "dropped in-between proper updates", but there is a Jenkins check that uses taxon constraints:

http://geneontology.org/page/annotation-quality-control-checks#0000013

**Comment by ValWood** [comment]
so it there a warning on our file right now? I forget where I can see this...

**Comment by ValWood** [comment]
Found it. 
http://build.berkeleybop.org/view/GAF/

So I don't understand:
 
The taxon check is implemented.
Our GAF is passing jenkins chacks.
The taxon restricted  annotation is in the GO database

**Comment by ukemi** [comment]
I think the issue is that in this ticket you want the restriction on the regulation terms. Do they also never regulate these processes, even when the process is occurring in another organism?

**Comment by ValWood** [comment]
Doesn't restriction on the regulation term happen automatically (I thought all descendants were  restricted).

> even when the process is occurring in another organism?

Er wouldn't that be a multi organism process if it occurs? I think for fission yeast we wouldn't expect to see this node annotated at all....not sure if other yeast want to keep the option open....

**Comment by ukemi** [comment]
Doesn't restriction on the regulation term happen automatically (I thought all descendants were restricted).

It doesn't seem like that would always be true for regulates. What about parasites that control process in their hosts, but don't carry out those processes themselves?

    even when the process is occurring in another organism?

Er wouldn't that be a multi organism process if it occurs? I think for fission yeast we wouldn't expect to see this node annotated at all....not sure if other yeast want to keep the option open....

Yes, but not all regulation would be. Let's keep this open for a few more days. If no one complains, I will add the restriction.

**Comment by ValWood** [comment]
I guess they could regulate migration.... I forgot about this change. We no longer have parasite specific terms do we.... this will be very confusing to distinguish parasite  sprecific process from  host-parasite interactions.

All I know is we would not expect pombe to be annotated to "cell migration" terms...
and based on this ticket yesterday
https://github.com/geneontology/go-annotation/issues/1424
I don't think SGD would expect saccharomyces to be annotated to these terms either....

**Comment by ValWood** [comment]
We might later need cleverer taxon restrictions, where you can only use certain terms with a certain species if you specify a host......

**Comment by dosumis** [comment]
> Doesn't restriction on the regulation term happen automatically (I thought all descendants were restricted).

Not how OWL works.  Inheritance only works down the class (is_a) hierarchy. A property chain is needed for restrictions to carry over relationships - but this is probably not possible for never_in_taxon as it needs expansion (to a GCI) to work.

**Comment by ukemi** [comment]
Hi Val,

I will go ahead and add these restrictions can you look at the taxon hierarchy and tell me exactly where to make them?

-D

**Comment by ValWood** [comment]
Go with 
regulation of cell migration GO:0030334
regulation of phagocytosis GO:0050764

never in yeast
for now, can refine later....

**Comment by ukemi** [comment]
Done.

**Comment by selewis** [comment]
Do you know which families are affected? We should update these to make sure all the taxon constraints are still satisfied. 

Looks okay when jenkins runs the validator, so I will assume we're clear.

**Comment by dianeoinglis** [comment]
Sorry to not have commented sooner.  

This taxon restriction should not apply to all Fungi. Fungal pathogens are able to alter neutrophil and macrophage cell migration and chemotaxis during infection.

Diane

**Comment by dianeoinglis** [comment]
Hi Susanna,

I added a late stage comment about fungal pathogens altering immune cell
chemotaxis and cell migration but I am not sure if the ticket has to be
reopened for the comment to be seen.

Best,

Diane

**Comment by selewis** [comment]
@ValWood 

We need you to chime in on this issue which arose in PAINT. 
https://github.com/geneontology/paint/issues/25

Perhaps you could start watching the PAINT list, your expertise would be appreciated.

**Comment by ukemi** [comment]
Hi Diana,

I made the restriction never in Saccharomycotina. Is that ok?

-D

**Comment by dianeoinglis** [comment]
Hi David,

No, that will not work because Candida is included in the Saccharomycotina
> Saccharomycetes > Saccharomycetales > Debaromycaceae.

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1535326

Basically, any effective pathogen of animals will encounter host immune
cells that migrate to either phagocytose the invading fungus or will
migrate to the lymphatic tissues with an engulfed fungus. Intracellular
fungal pathogens, such as Histoplasma love riding inside macrophages as
vehicles for dissemination. Extracellularly, pathogenic fungi can alter
chemotaxis, whether they alter the migration as intracellular passengers is
less certain.

Perhaps this taxon restriction should be specific to yeast and S. pombe. It
would be preferable to apply phylogenetically but the animal pathogens seem
to dispersed among phyla.

I do have some important comments to contribute to the ticket on
PAINT/yeast annotations.

Diane

**Comment by ukemi** [comment]
Thanks Diane.
 If you read above, you can see that I was originally concerned about this possibility. I have removed the taxon constraint.

-D

**Comment by ValWood** [comment]
OK, we can deal with this
http://www.pombase.org/spombe/result/SPAC2F7.16c
by getting the mapping updated.
val

**Comment by ValWood** [comment]
It was already done
https://github.com/geneontology/go-annotation/issues/1421

**Comment by ValWood** [comment]
@cmungall  should this link work,
I get  access denied:

http://geneontology.org/page/annotation-quality-control-checks#0000013

**Comment by ValWood** [comment]
ignore

**Comment by cmungall** [comment]
Rules are here: https://github.com/geneontology/go-site/tree/master/metadata/rules
