### ISSUE TITLE
NTR:  static microtubule bundle 	PMID:26124291

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12561]
is_a GO:0097427 microtubule bundle

Term name “static microtubule bundle”
synonym quiescent cell microtubule bundle
synonym quiescent cell MT bundle
synonym Q-MT bundle

Proposed def
A microtubule bundle which has constant length and does not display microtubule sliding

(Note in fission yeast this is  called a  quiescent cell microtubule bundle but I tried to genericize)

We might need terms for static and non-static microtubule bundles?....All of our (PomBase) other annotations are to non-static...to my knowledge this is the first time the  MT cytoskeleton has been studied in pombe quiescent cells, I don't know if this phenomena occurs more generally....).

**Comment by mah11** [comment]
We had a chat about this and I recommended adding both static and dynamic, so minor adjustments and a second stanza:

id: GO:new1
name: static microtubule bundle
def: A microtubule bundle that has a constant length, and in which microtubule sliding does not take place. [GOC:vw, PMID:26124291]
comment: In fission yeast, quiescent cells contain only static microtubule bundles.
synonym: quiescent cell microtubule bundle NARROW
synonym: quiescent cell MT bundle NARROW
synonym: Q-MT bundle NARROW
is_a: GO:0097427 ! microtubule bundle

id: GO:new2
name: dynamic microtubule bundle
def: A microtubule bundle that undergoes changes in length, and in which microtubule sliding takes place. [GOC:mah, PMID:26124291]
is_a: GO:0097427 ! microtubule bundle

**Comment by dosumis** [comment]
Added as requested
