### ISSUE TITLE
NTR: ciliary vesicle

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12563]
@JohnvanDam @krchristie
(John is away at the moment, but I’ll open this ticket now anyway as I’m looking at this term.)

John suggested to add the following CC term (initial communication was done by email on 27/7/16, so copying here):

+[Term]
+id: ID:0000012
+name: ciliary vesicle
+namespace: cellular_component
+def: "A Golgi derived vesicle to which the ciliary basal body docks via its transitional fibers. The membrane composition is distinct and will become the ciliary membrane once it is fused to the plasma membrane. The ciliary vesicle is thought to be formed by multiple smaller vesicles that attach to the transitional fibers and then fuse to form a larger vesicle." []
+synonym: "primary vesicle" EXACT []
+xref: PMID:13978319
+xref: PMID:25805133
+is_a: GO:0097708 ! intracellular vesicle
+created_by: jvandam
+creation_date: 2016-07-18T11:51:26Z

The formation/assembly term will then be added for this CC. This is all relevant for the cilium assembly BP branch.

I agree, and suggest to add the CC term as follows (i.e. with a few changes in definition, synonyms and parentage):

+name: ciliary vesicle
+namespace: cellular_component
+def: "A Golgi-derived vesicle to which the ciliary basal body docks via its transitional fibers. Its membrane is compositionally distinct from Golgi membranes, and will become the ciliary membrane once the ciliary vesicle is fused to the plasma membrane. The ciliary vesicle is thought to be formed by multiple smaller vesicles that attach to the transitional fibers and then fuse to form a larger vesicle." [GOC:cilia, PMID:13978319, PMID:25686250]
+synonym: “CV” RELATED [PMID:2568625]
+synonym: "primary ciliary vesicle" EXACT [PMID:20427320]
+is_a: GO:0031410 ! cytoplasmic vesicle

(Note for self: NOT is_a GO:0016023 ! cytoplasmic, membrane-bounded vesicle because... see https://github.com/geneontology/go-ontology/issues/11504, my comment from March 29)

John, Karen, please double-check for correctness. Also, a question for you: PMID:20427320 suggests that ‘ciliary vesicle’ should be related to the existing term GO:0020016 ‘ciliary pocket’ (“Invagination of the plasma membrane from which a cilium (also called flagellum) protrudes.”). Is this correct and if yes, how should we accomplish this?

Note for self: 
When working on the ‘cilium assembly’ branch, consider adding the link ‘cilium assembly’ starts_with ‘ciliary vesicle formation/assembly’? (See e.g. PMID:25686250 “Membrane association with mother centriole (M-centriole) distal appendages is critical for ciliogenesis initiation”.)

**Comment by paolaroncaglia** [comment]
In terms of taxon constraints for 'ciliary vesicle' and associated BP terms, John also wrote:

"I've also added one more CC term "ciliary vesicle" because while reading I found out that, even though it is often neglected in literature, basal body docking is preceded by docking to a specialized vesicle, which will then fuse to the plasma membrane. The vesicle functions as a pre-made ciliary membrane. (...) it is pretty difficult to find out how common this process is in other organisms. I've been able to track some components back to the jawed vertebrates, but I do not know how or if this process occurs in lower animals as well, or non-animals for that matter. I am pretty sure it does not occur in Chlamydomonas and Giardia species, but I could not find any references that actually say so."

In the absence of references, I'd lean towards not applying taxon restrictions. We can always revise if/when published evidences can be provided.

**Comment by krchristie** [comment]
I've come across the "ciliary vesicle" in mouse literature, but I haven't focused on it and don't have anything to add to this discussion at the moment. Your current proposal sounds fine to me.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks @krchristie !

**Comment by JohnvanDam** [comment]
The term as you defined it looks excellent Paola. On the relationship with the ciliary pocket, the Sorokin paper has some very nice EM pictures showing all the stages of vesicle-BB docking and subsequent merging with the plasma membrane (1). The ciliary pocket is formed by first extending the axoneme into the vesicle forming some sort of "vesicle cap". This is then followed by the membrane fusion event, and so creating the ciliary pocket. So, indeed, the CV and pocket are related to each other as some of the membrane that lines the ciliary pocket initially is derived from the vesicle. Though I suspect that the pocket membrane composition will rapidly change due to mixing with plasma membrane. I do not know how to capture this in GO other than via the definition of both terms in CC or via biological processes.

1. Check figures 11 through 17 in the Sorokin paper at http://jcb.rupress.org/content/15/2/363.long page 369

**Comment by JohnvanDam** [comment]
Hi Paola,
Excellent! I wonder to which extent (or if) we should limit the biological process taxonomically (is that a word?). I've only found references to vesicle docking and ciliary pockets in mammalian systems. I am not sure if it occurs in Chlamy and protists for instance.

**Comment by paolaroncaglia** [comment]
Hi @JohnvanDam,

I think the best course of action would be

- [ ] Once the revised GO ‘cilium assembly’ branch is in place, we should ask Karen to check with her colleague from the Chlamydomonas community to please take a look and let us know if we should restrict any terms beneath ‘cilium assembly’ to specific taxonomic groups. Currently, ‘cilium assembly’ is labelled as occurring only in eukaryotes but never in Ascomycetes; we could certainly add more constraints if needed, to it and/or to any of its children. I’ll move this note to the appropriate GH ticket too.

**Comment by paolaroncaglia** [comment]
Added 

 [Term]
+id: GO:0097721
+name: ciliary vesicle
+namespace: cellular_component
+def: "A Golgi-derived vesicle to which the ciliary basal body docks via its transitional fibers. Its membrane is compositionally distinct from Golgi membranes, and will become the ciliary membrane once the ciliary vesicle is fused to the plasma membrane. The ciliary vesicle is thought to be formed by multiple smaller vesicles that attach to the transitional fibers and then fuse to form a larger vesicle." [GOC:cilia, PMID:13978319, PMID:25686250]
+synonym: "CV" RELATED [PMID:2568625]
+synonym: "primary ciliary vesicle" EXACT [PMID:20427320]
+is_a: GO:0031410 ! cytoplasmic vesicle
