### ISSUE TITLE
primosome - GO:1990077 & GO:0005658

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12575]
A while ago in #11165, Val asked whether GO:0005658 ! alpha DNA polymerase:primase complex should be GO:1990077 ! primosome complex. That ticket went off in a different direction, and the link wasn't added.

Now I'm looking at the GO:1990077 definition again, and I think both the text and logical defs still contain elements that apply only in prokaryotes. To make GO:0005658 is_a GO:1990077 work, GO:1990077 would have to lose:

- intersection_of: capable_of_part_of GO:0031297 ! replication fork processing (other stuff takes care of fork processing in euks)
- "Early complexes initiate double-stranded DNA unwinding.  The core unit consists of a replicative helicase and a primase. The helicase further unwinds the DNA and recruits the polymerase machinery." (in euks "primosome" is rarely used, and when it is, it means the polymerase alpha/primase complex, i.e. GO:0005648, which doesn't have anything other than polymerase and primase activities; the helicase is separate)
- "The primosome contains a number of associated proteins and protein complexes" (as above, "primosome" = GO:0005658 in euks)

Or, we could just add a taxon restriction for GO:1990077 - I think "only in prokaryotes" is true for the current defs, but I don't know whether it's specific for Bacteria or also applies to Archaea (I kind of suspect the former, since archaea have some MCM proteins, but am not sure).

I don't really have a strong preference which approach we take, but the taxon restriction on GO:1990077 looks simpler.

@valwood @bmeldal

**Comment by bmeldal** [comment]
I'm pretty sure I asked for this term when I was creating E.coli complexes some 3 years ago so yes, the def was probably modelled on prokaryotes. We did introduce a few eukaryotic vs prokaryotic terms at the time because the mechanisms were so different. I haven't worked on the eukaryotic equivalents yet!

**Comment by mcourtot** [comment]
Proposal to add 
relationship: only_in_taxon NCBITaxon_Union:0000004 ! Prokaryota
to GO:1990077, primosome complex

I'll wait a day or two to allow other to pitch in and I'll make the change.

**Comment by mcourtot** [comment]
Done revision 34884.
