### ISSUE TITLE
complement receptor merges ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12579]
Hello, 

It seems to me these pairs of terms are synonymous: 
1.  GO:0004878 complement component C5a receptor activity 
&  GO:0004944 	C5a anaphylatoxin receptor activity 

2. GO:0004876 	complement component C3a receptor activity 
&  GO:0004943 	C3a anaphylatoxin receptor activity 

And the correct parentage is under complement receptor activity (ie GO:0004878 and GO:0004876. See https://en.wikipedia.org/wiki/Anaphylatoxin

Also, these should be linked to the BP 'GO:0002430 complement receptor mediated signaling pathway ' 
Thanks, Pascale

**Comment by pgaudet** [comment]
Note to self: saw during curation of PTHR24225. If terms are merged, touchup should handle the changes.

**Comment by paolaroncaglia** [comment]
Thanks @pgaudet .
Sounds like the most appropriate strategy would be to 
- merge GO:0004944 ‘C5a anaphylatoxin receptor activity’ into GO:0004878 ‘complement component C5a receptor activity’ (the original name should be automatically kept as synonym, but I’ll check)
- merge GO:0004943 ‘C3a anaphylatoxin receptor activity’ into GO:0004876 ‘complement component C3a receptor activity’ (same as above re. synonym)  
- merge ‘anaphylatoxin receptor activity’ into ‘complement receptor activity’ (same as above re. synonym) (has no direct manual annotation)

GO:0004878 ‘complement component C5a receptor activity’ already is a descendant of GO:0002430 ‘complement receptor mediated signaling pathway' (via part_of ’complement component C5a signaling pathway’). 

I will add the link GO:0004876 ‘complement component C3a receptor activity’ part_of GO:0002430 ‘complement receptor mediated signaling pathway’.

Any objections please let me know, thanks.

**Comment by paolaroncaglia** [comment]
Hi @pgaudet , all done. Closing now.
