### ISSUE TITLE
NTRs/OTRs: New cilium assembly terms and references to Reactome IDs

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12572]
Scarily long ticket needed to keep track of ciliary BP edits.

@JohnvanDam @krchristie

John provided a list of suggestions for new GO BP terms, and additions to existing terms, for the cilium assembly branch.
(He also suggested a CC term, ciliary vesicle - that’s in a separate ticket https://github.com/geneontology/go-ontology/issues/12563)
Some of this work will require previous agreement on cilia type nomenclature 
(see these two related issues which I haven’t worked on yet as I was on leave:
https://github.com/geneontology/go-ontology/issues/12462
https://github.com/geneontology/go-ontology/issues/12487).
In the meantime, I will copy here the BP stanzas that John proposed, preceded by some of John’s notes:

“Here are the promised lemmas I've made with new terms for cilium assembly. I've also added some additional connections to existing terms.
The file attached is a plain text file in which I've put all the lemmas that have been added or changed. Added information is preceded by a + at the beginning of the line, and if information is changed the original line is preceded by a "-" followed by the changed line preceded by a "+". Much in the "diff" style that is used in software development.

The top lemmas are existing ones to which I added new relationships or REACTOME pathway identifiers. Mostly the new relationships have to do with new terms that I devised for the assembly of specific axonemes (e.g. 9+2 motile axoneme assembly, 9+2 immotile axoneme assembly etc.). I put them forward, but I think they may be worth discussing before they get implemented, especially because we haven't settled yet on the CC related terms for the different axonemal configurations yet.

I've added multiple references where possible (I only found one specific publication on the transitional fibers), though I may not have used the right tag (xref). and I've tried to find the most appropriate parent terms for the is_a relationships. Also I've attempted to add references to the Reactome pathways as much as possible, though many a term in Reactome I think is too narrow in scope for Gene Ontology.

There may be more finetuning possible, specifically for the relationships, but I'll leave that for when we decided on the new terms.”
(Once the terms are in place, we can evaluate addition of has_parts, starts_with, ends_with…)

Below are John’s proposed stanzas (minus ‘ciliary vesicle’), each stanza followed by my brief comment in square brackets. 
Notes for self: 
- remember to add dbxref GOC:cilia to new terms (and to edited terms if they don’t have it already);
- PMIDs should be entered as dbxrefs, not xrefs. I’ve already checked them;
- once all changes and additions are implemented, ask Reactome (Karen C and Peter) to review the GO structure;
- ideally, all PMIDs used as dbxrefs for GOC:cilia terms should be annotated, if they’re not review papers and if they contain info appropriate for gene product curation…

[THIS IS DEALT WITH - AS DISCUSSED IN LATER COMMENT]
 [Term]
 id: GO:0036158
 name: outer dynein arm assembly
 namespace: biological_process
 def: "The aggregation, arrangement and bonding together of a set of components to form an axonemal dynein outer arm, an outer arm structure present on the outer doublet microtubules of ciliary and flagellar axonemes." [GOC:BHF, GOC:vk, PMID:19944400]
 synonym: "ODA assembly" EXACT [PMID:19944400]
 is_a: GO:0070286 ! axonemal dynein complex assembly
+relationship: part_of ID:0000008 ! 9+2 motile axoneme assembly
+relationship: part_of ID:0000009 ! 9+2 immotile axoneme assembly
+relationship: part_of ID:0000011 ! 9+0 motile axoneme assembly
 created_by: rfoulger
 creation_date: 2012-03-21T02:25:01Z
[must wait]
 
[THIS IS DEALT WITH - AS DISCUSSED IN LATER COMMENT]
 [Term]
 id: GO:0036159
 name: inner dynein arm assembly
 namespace: biological_process
 def: "The aggregation, arrangement and bonding together of a set of components to form an axonemal dynein inner arm, an inner arm structure present on the outer doublet microtubules of ciliary and flagellar axonemes." [GOC:BHF, GOC:vk, PMID:19944400]
 synonym: "IDA assembly" EXACT [PMID:19944400]
 is_a: GO:0070286 ! axonemal dynein complex assembly
+relationship: part_of ID:0000008 ! 9+2 motile axoneme assembly
+relationship: part_of ID:0000011 ! 9+0 motile axoneme assembly
 created_by: rfoulger
 creation_date: 2012-03-21T02:25:01Z
[must wait]
 
[THE EDIT BELOW IS DONE] 
[Term]
 id: GO:0042073
 name: intraciliary transport
 namespace: biological_process
 alt_id: GO:0035734
-def: "The bidirectional movement of large protein complexes along microtubules within a cilium, mediated by motor proteins." [GOC:cilia, GOC:kmv, PMID:17981739, PMID:18180368, PMID:22869374]
+def: "The bidirectional movement of large protein complexes along microtubules within a cilium, mediated by motor proteins." [GOC:cilia, GOC:kmv, PMID:17981739, PMID:18180368, PMID:22869374, REACTOME:R-HSA-5620924.2]
 comment: Note that we deem cilium and microtubule-based flagellum to be equivalent.
 synonym: "IFT" RELATED []
 synonym: "intraflagellar transport" EXACT []
 synonym: "intraflagellar transport involved in cilium organization" EXACT []
 synonym: "intraflagellar transport involved in microtubule-based flagellum organisation" EXACT []
 xref: Wikipedia:Intraflagellar_transport
 is_a: GO:0010970 ! establishment of localization by movement along microtubule
 is_a: GO:0015031 ! protein transport
 is_a: GO:0031503 ! protein complex localization
 is_a: GO:0044765 ! single-organism transport
 is_a: GO:0051649 ! establishment of localization in cell
 relationship: occurs_in GO:0005929 ! cilium
 relationship: part_of GO:0044782 ! cilium organization
[Reactome ID can be added as dbxref. NOW DONE]
  
[THIS IS DEALT WITH - AS DISCUSSED IN LATER COMMENT]
 [Term]
 id: GO:1904158
 name: axonemal central apparatus assembly
 namespace: biological_process
 def: "The aggregation, arrangement and bonding together of a set of components to form an axonemal central apparatus." [GO_REF:0000079, GOC:krc, GOC:TermGenie, PMID:9295136]
 synonym: "axonemal central apparatus formation" EXACT [GOC:TermGenie]
 is_a: GO:0010927 ! cellular component assembly involved in morphogenesis
 relationship: part_of GO:0035082 ! axoneme assembly
+relationship: part_of ID:0000008 ! 9+2 motile axoneme assembly
+relationship: part_of ID:0000009 ! 9+2 immotile axoneme assembly
 created_by: krc
 creation_date: 2015-04-16T18:46:11Z
[must wait]

[THE EDITS BELOW ARE DONE] 
+[Term]
+id: ID:0000000
+name: transition zone assembly
+namespace: biological_process
+def: "The assembly and organization of the ciliary transition zone. The transition zone is a proximal part of the cilium located at the start of the axoneme and functions as a molecular gate seperating the cytosol from the ciliary plasma. Several distinct components make up this region: the ciliary necklace, y-shaped linkers, and, depending on the species, may have a distinctly geometrically shaped electron dense structures within the axonemal lumen visible in electron microscopy images. Most animals have no such inner structure in the transition zone. The axoneme extends through this specialised region, but only consists of the outer doublets. The central pair, axonemal spokes, and dynein complexes are not found in this part of the ciliary shaft.\n\nNote: The connecting cilium of the photoreceptor cells is thought to be equivalent to the transition zone and thus \"connecting cilium assembly\" is a special synonym." []
+xref: PMID:21725307
+xref: PMID:23644468
+xref: PMID:24448408
+xref: PMID:26595381
+xref: PMID:26982032
+is_a: GO:0010927 ! cellular component assembly involved in morphogenesis
+relationship: part_of GO:0042384 ! cilium assembly
+created_by: jvandam
+creation_date: 2016-07-13T09:48:42Z
[Can be added via TG template as ‘ciliary transition zone assembly’. As such, it will get a standard definition. NOW DONE, GO:1905349 ciliary transition zone assembly.
Much of the information that John put into his proposed def for ‘transition zone assembly’ will be better placed in the stanza of the corresponding CC term, i.e. ‘ciliary transition zone’, which I will edit as follows:
- revise def to: “A region of the cilium between the basal body and proximal segment that is characterized by Y-shaped assemblages that connect axonemal microtubules to the ciliary membrane. The ciliary transition zone appears to function as a gate that controls ciliary membrane composition and separates the cytosol from the ciliary plasm.”
- add def comment: “Depending on the species, this region may have a distinct geometrically-shaped electron-dense structure within the axonemal lumen visible in electron microscopy images; most animals don’t display this inner structure. The axoneme extends through the ciliary transition zone, but only consists of the outer doublets. The central pair, axonemal spokes, and dynein complexes are not found in this part of the ciliary shaft. Note that the connecting cilium of the photoreceptor cells is thought to be equivalent to the transition zone." 
- add related synonym: ‘connecting cilium’
NOW DONE]

[THE EDITS BELOW ARE DONE]
+[Term]
+id: ID:0000002
+name: #y-shaped linker assembly
+namespace: biological_process
+def: "Assembly of a large protein structure in the ciliary transition zone that has the form of the letter Y and connects the axoneme (specifically the a-microtubule of each doublet) to the membrane. Whether the two extensions of the y-shaped linker also forms the ciliary necklace, or connects to the necklace is unclear. Two distinct complexes are known to be involved in proper linker assembly: the mks complex and the nphp complex. Improper assembly of Y-shaped linkers is linked to improper functioning of the transition zone as a molecular gate." []
+xref: PMID:23728985
+xref: PMID:24664739
+xref: PMID:26595381
+xref: PMID:4554367
+is_a: GO:0010927 ! cellular component assembly involved in morphogenesis
+relationship: part_of ID:0000000 ! transition zone assembly
+created_by: jvandam
+creation_date: 2016-07-13T10:09:56Z
[Can be added via TG template as ‘Y-shaped link assembly’. As such, it will get a standard definition, to which I will add: 
“Two distinct protein complexes are known to be involved in proper linker assembly: the MKS complex and the NPHP complex. Improper assembly of Y-shaped links may cause improper functioning of the transition zone as a molecular gate.” NOW DONE, GO:1905350 Y-shaped link assembly.
I will also add links ‘MKS complex’ and ‘NPHP complex’ capable_of_part_of ‘Y-shaped link assembly’. NOW DONE]
 
[THE EDIT BELOW IS DONE]
+[Term]
+id: ID:0000003
+name: ciliary necklace assembly
+namespace: biological_process
+def: "Assembly of the ciliary necklace, which consists of regularly spaced protein structures protruding the ciliary membrane in a spiral for the entire length of the transition zone." []
+xref: PMID:20399632
+xref: PMID:6409906
+is_a: GO:0010927 ! cellular component assembly involved in morphogenesis
+relationship: part_of ID:0000000 ! transition zone assembly
+created_by: jvandam
+creation_date: 2016-07-13T10:34:02Z
[Can be added via TG template and will get standard definition. NOW DONE, GO:1905352 ciliary necklace assembly]
 
[THE EDIT BELOW IS DONE]
+[Term]
+id: ID:0000004
+name: transition fiber assembly
+namespace: biological_process
+def: "Assembly of transition fibers that connect the basal body to the plasma membrane. These structures are required for the docking of the cytosolic centriole/basal body to the plasma membrane before the assembly of the cilium." []
+xref: PMID:24189274
+is_a: GO:0010927 ! cellular component assembly involved in morphogenesis
+relationship: part_of GO:0042384 ! cilium assembly
+created_by: jvandam
+creation_date: 2016-07-13T11:34:31Z
[Can be added via TG template and will get standard definition. NOW DONE, GO:1905353 ciliary transition fiber assembly]
 
[THE EDIT BELOW IS DONE]
+[Term]
+id: ID:0000005
+name: ciliary basal body docking
+namespace: biological_process
+def: "The docking of the cytosolic centriole/basal body to the plasma membrane via the transitional fibers. In some species this may happen via an intermediate step by first docking to the ciliary vesicle via the transitional fibers. The basal body-ciliary vesicle then relocates to the plasma membrane followed by the ciliary vesicle fusing with the plasma membrane, effectively attaching the basal body to the plasma membrane.\n\nNote: Some species like Giardia intestinalis do not relocate their basal bodies to the membrane but have their axonemes extend through the cytosol to then protrude out of the cell to form flagella. \n\nNote 2: Basal bodies in jawed vertebrates appear to first attach to a ciliary vesicle. It is unclear how specific this is to jawed vertebrates or if other organisms also employ this sequence." [REACTOME:R-HSA-5620912.1]
+xref: PMID:13978319
+xref: PMID:23348840
+xref: PMID:23530209
+xref: PMID:25686250
+xref: PMID:26981235
+is_a: GO:0022615 ! protein to membrane docking
+relationship: part_of GO:0042384 ! cilium assembly
+relationship: part_of GO:0060271 ! cilium morphogenesis
+created_by: jvandam
+creation_date: 2016-07-13T11:44:00Z
[I will add this manually as follows:
name: ciliary basal body docking
is_a membrane docking (to allow for both mechanisms described in definition)
part_of cilium assembly (not ‘cilium morphogenesis’, see https://github.com/geneontology/go-ontology/issues/12236)
def: "The docking of a cytosolic centriole/basal body to the plasma membrane via the ciliary transition fibers. In some species this may happen via an intermediate step, by first docking to the ciliary vesicle via the ciliary transition fibers. The basal body-ciliary vesicle then relocates to the plasma membrane, followed by the ciliary vesicle fusing with the plasma membrane, effectively attaching the basal body to the plasma membrane." [GOC:cilia, PMID:13978319, PMID:23348840, PMID:23530209, PMID:25686250, PMID:26981235, REACTOME:R-HSA-5620912.1]
def comment: “Basal bodies in jawed vertebrates appear to first attach to a ciliary vesicle. It is unclear how specific this is to jawed vertebrates or if other organisms also employ this sequence. Some species like Giardia intestinalis do not relocate their basal bodies to the plasma membrane, but have their axonemes extend through the cytosol to then protrude out of the cell to form flagella.” NOW DONE, GO:0097711 ‘ciliary basal body docking’]

[THE EDIT BELOW IS DONE]
+[Term]
+id: ID:0000006
+name: vesicle targeting, golgi to periciliary membrane
+namespace: biological_process
+def: "The process in which vesicles formed at the trans Golgi network are directed to the plasma membrane surrounding the base of the cilium, including the ciliary pocket, mediated by molecules at the vesicle membrane and target membrane surfaces." [REACTOME:R-HSA-5620920.1]
+xref: PMID:20106869
+xref: PMID:23351793
+xref: PMID:24814148
+xref: PMID:26485645
+is_a: GO:0006903 ! vesicle targeting
+relationship: part_of GO:0042384 ! cilium assembly
+relationship: part_of GO:0060271 ! cilium morphogenesis
+created_by: jvandam
+creation_date: 2016-07-13T14:06:13Z
[I will add this manually as follows:
name: vesicle targeting, trans-Golgi to periciliary membrane compartment
is_a vesicle targeting, to, from or within Golgi
part_of cilium assembly
def: "The process in which vesicles formed at the trans-Golgi network are directed to the plasma membrane surrounding the base of the cilium, including the ciliary pocket, mediated by molecules at the vesicle membrane and target membrane surfaces." [GOC:cilia, PMID:20106869, PMID:23351793, PMID:24814148, PMID:26485645, REACTOME:R-HSA-5620920.1] NOW DONE, GO:0097712 ’vesicle targeting, trans-Golgi to periciliary membrane compartment’]
 
+[Term]
+id: ID:0000007
+name: ciliary vesicle formation
+namespace: biological_process
+def: "Process by which a vesicle is produced to which the ciliary basal body will dock to form the ciliary membrane after fusion to the plasma membrane. Multiple smaller vesicles dock to the transitional fibers on the mature basal body and then fuse together to form a larger single vesicle." []
+xref: PMID:13978319
+xref: PMID:25313408
+xref: PMID:25805133
+xref: PMID:25812525
+is_a: GO:0010927 ! cellular component assembly involved in morphogenesis
+relationship: part_of GO:0042384 ! cilium assembly
+created_by: jvandam
+creation_date: 2016-07-18T11:03:17Z
[Can be added via TG template, as ‘ciliary vesicle assembly’, once the corresponding CC term has been created. It will get a standard definition.]
 
+[Term]
+id: ID:0000008
+name: 9+2 motile axoneme assembly
+namespace: biological_process
+def: "Process by which a motile 9+2 axoneme is constructed including inner and outer dynein complexes and central apparatus." []
+xref: PMID:22118931
+is_a: GO:0035082 ! axoneme assembly
+created_by: jvandam
+creation_date: 2016-07-18T11:20:48Z
[Must wait. May then be added via TG template, if the corresponding CC term is approved]

+[Term]
+id: ID:0000009
+name: 9+2 immotile axoneme assembly
+namespace: biological_process
+def: "Process by which an immotile 9+2 axoneme is constructed. An example of nonmotile 9+2 cilia are the kinocilia. These axonemes lack inner dynein complexes and appear to lack the nexin filaments that connect the outer microtubule doublets to each other." []
+xref: PMID:22118931
+is_a: GO:0035082 ! axoneme assembly
+created_by: jvandam
+creation_date: 2016-07-18T11:22:55Z
[Must wait. May then be added via TG template, if the corresponding CC term is approved]
 
+[Term]
+id: ID:0000010
+name: 9+0 immotile axoneme assembly
+namespace: biological_process
+def: "Process by which an immotile 9+0 axoneme is constructed. This type of axoneme lacks many of the components found in the 9+2 types. It is distinct from the 9+2 axonemes in that it lacks the central apparatus and motile machinery." []
+xref: PMID:22118931
+is_a: GO:0035082 ! axoneme assembly
+created_by: jvandam
+creation_date: 2016-07-18T11:27:29Z
[Must wait. May then be added via TG template, if the corresponding CC term is approved]

+[Term]
+id: ID:0000011
+name: 9+0 motile axoneme assembly
+namespace: biological_process
+def: "Process by which a motile 9+0 axoneme is constructed including inner and outer dynein complexes. An example of a motile 9+0 cilium are the nodal cilia involved in left-right patterning in the early embryonic stages of most vertebrate animals.\n9+0 motile axonemes contain both inner and outer dynein arms, but lack the central apparatus including the central pair microtubules." []
+xref: PMID:22118931
+is_a: GO:0035082 ! axoneme assembly
+created_by: jvandam
+creation_date: 2016-07-18T11:30:36Z
[Must wait. May then be added via TG template, if the corresponding CC term is approved]

**Comment by paolaroncaglia** [comment]
Hi @JohnvanDam and @krchristie,

The following questions stem from some of John’s suggested changes:

- [ ] Outer dynein arms are found in 9+2 motile, 9+2 non-motile and 9+0 motile cilia. They are NOT found in 9+0 non-motile cilia. Correct?
If so, I’ll add the links
9+2 motile cilium has_part outer dynein arm
9+2 non-motile cilia has_part outer dynein arm
9+0 motile cilia has_part outer dynein arm
(NOT outer dynein arm part_of 9+2 motile cilium etc, because part_of means necessarily part_of ONE thing only - if it can be part_of more than one thing, it’s not necessary for one thing alone)

- [ ] Inner dynein arms are found in 9+2 motile and 9+0 motile cilia only. Correct?
If so, I’ll add the links
9+2 motile cilium has_part inner dynein arm
9+0 motile cilia has_part inner dynein arm

**Comment by paolaroncaglia** [comment]
Note, the experts reminded us that some types of cilia have an axonemal configuration that is 9+0 or 9+2. Regardless, they may still contain (and presumably do!) inner and/or outer dynein arms and/or an axonemal central apparatus. For this reason, it would be ontologically incorrect to add part_of links between e.g. ‘outer dynein arm assembly’ and ‘9+2 motile axoneme [or cilium] assembly’, ‘inner dynein arm assembly’ and ‘9+2 motile axoneme [or cilium] assembly’, ‘axonemal central apparatus assembly’ and ‘9+2 motile axoneme [or cilium] assembly’. 

- [ ] The only links we could add, if we created very specific terms such as ‘9+2 motile cilium assembly’, would be e.g. ‘9+2 motile cilium assembly’ has_part ‘outer dynein arm assembly’. But do we really need/want to have such granularity? @krchristie, during your annotation effort, did you ever feel the need for assembly terms for the _specific_ class of cilia, or would ‘motile cilium assembly’ and ‘non-motile cilium assembly’ suffice? 
Note, if the answer to the latter is yes, the more specific terms could still be created in the future if literature annotation requires it. 
Also note, if the answer to the latter question is no, I’d rather create terms for e.g. ‘9+2 motile cilium assembly’ than ‘9+2 motile axoneme assembly’, as they’d mean the same and in the end we resolved to classify by that wording.

**Comment by paolaroncaglia** [comment]
Hi @krchristie and @JohnvanDam,

Just a friendly reminder, when you have a chance, if you could please comment on my questions here
https://github.com/geneontology/go-ontology/issues/12572#issuecomment-251916031
and here
https://github.com/geneontology/go-ontology/issues/12572#issuecomment-251921077
so I can proceed with the remaining edits for this cilia ticket. Thanks!

Paola

**Comment by JohnvanDam** [comment]
Hi Paola,

Answer to first question: outer dynein arms are found in 
- 9+2 motile 
- 9+0 motile (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2133177/)
- 9+2 immotile cilia (http://jeb.biologists.org/content/214/5/862) however see below*

Inner dynein arms are found in
- 9+2 motile 
- 9+0 motile (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2133177/)

* Now...this article makes this statement, but does not reference anything. While digging deeper I find al kinds of literature talking about 9+0 kinocilia or 9+2 kinocilia, or a mixture. But never a reference to a paper with a proper EM image showing the actual axonemal arrangement and/or dynein arrangement. This abstract (https://www.ncbi.nlm.nih.gov/pubmed/2527457) describes kinocilia as 9+0 with only outer dynein arms and radial spokes, but no central pair. I do not have access to the full paper and I can not find the PDF. I will dig deeper into this tomorrow.

**Comment by paolaroncaglia** [comment]
Hi @JohnvanDam,

Thanks for your feedback. It confirms that addition of has_part links as outlined here https://github.com/geneontology/go-ontology/issues/12572#issuecomment-251916031 is correct to the best of our knowledge. So, I went ahead and added them. If further evidence emerges from the literature, we may add new links, or revise existing ones as needed.

**Comment by paolaroncaglia** [comment]
With regards to edits outlined here https://github.com/geneontology/go-ontology/issues/12572#issuecomment-251921077, I’m quite convinced I’ll leave things as they are for now, and only add new terms and/or links in the future if there is a real need for them. This takes care of all remaining edits from John’s original request here https://github.com/geneontology/go-ontology/issues/12572#issue-169363982, except for this one which I’ll do next:

- [ ] add ‘ciliary vesicle formation’ via TG as outlined in that same comment

**Comment by paolaroncaglia** [comment]
Done: added GO:1905556 ciliary vesicle assembly
