### ISSUE TITLE
multi-organism process triads

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12577]
This triad-structure of the MOP terms (e.g. the split into interaction with host vs interaction with symbiont) means that the virus terms (which are largely agnostic for host vs symbiont) are under ‘interaction with host’ which looks weird when annotating a host protein to e.g. virus receptor activity ; GO:0001618.

I've discussed this briefly with Jane, and we agree that it might make more sense to move most of the terms out of the triad structure, and rename them so they're agnostic from the symbiont/host view (this can be captured at the annotation stage). For the more specific cases, the triad structure could be maintained:
e.g:
----[isa]interspecies interaction between organisms
------[isa]acquisition of nutrients from other organism during symbiotic interaction 
--------[isa]acquisition of nutrients from host
--------[isa]acquisition of nutrients from symbiont

and renaming terms to e.g. 
exit from host > exit of symbiont from host
movement in host > movement of symbiont from host
etc..

The current structure is a problem for me when annotating host Rab proteins that are purposed for transporting a symbiont around the cell. It reflects the problem of annotating the 'canonical' vs 'evolved' role of the host protein but I believe is biology we want to capture. 

Assigning to David because I know you've been editing some viral terms recently.

**Comment by pgaudet** [comment]
We are doing this in multiple newer tickets. This is redundant.
