### ISSUE TITLE
OTR: autophagy vs. autophagic cell death again

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12573]
Hi @ukemi @Pauldenny @marcfeuermann @RLovering (autophagy working group)
@tberardini (for plant expertise)
@hattrill (for Drosophila expertise)

I was doing a sanity check for the apoptosis paper and I ran across 3 IMP annotations to ‘autophagic cell death’ for Arabidopsis proteins. We discussed ‘autophagic cell death’ within the autophagy project some time ago, and my recollection is that we always had Drosophila in mind. As we said, the link between autophagy and cell death is still unclear, so we suggested caution in using ‘autophagic cell death’. My feeling is that those 3 Arabidopsis annotations should go to ‘autophagy’, which is currently restricted to eukaryotes so plants should be fine, but I wanted to check with you all. Also, I’m wondering if we should narrow the current taxon rule for ‘autophagic cell death’ from eukaryotes to insects. 

Thanks,

Paola

**Comment by tberardini** [comment]
Paola,  could you have a look at this paper?

https://www.ncbi.nlm.nih.gov/pubmed/20659276

It's one of the Arabidopsis ones.  The authors state at the end of the section titled  **RabG3bCA cells accumulate numerous autophagic structures during TE differentiation**, "These results together suggest that RabG3b is a positive regulator in autophagy and that RabG3b-activated autophagy contributes to TE differentiation, possibly by stimulating the cell death process."

I can move this annotation (and the other TAIR one) to (pos reg of) autophagy but I won't be able to edit the one from UniProt.  That has to be done by raising a dispute through Protein2GO.

**Comment by paolaroncaglia** [comment]
Hi @tberardini ,

Sorry for the delayed reply. Based on the paper above, I think those Arabidopsis annotations should be moved as you suggest (the cells *differentiate* into TEs, rather than die and be eliminated from the organism). If you could please take care of the TAIR ones, that'd be great, thanks.  

@ukemi @Pauldenny @marcfeuermann @RLovering
Could you please raise a dispute via P2GO for the UniProt annotation? Thanks in advance.

**Comment by paolaroncaglia** [comment]
@hattrill

Please see my opening comment in this thread (the one dated Aug 5)
Do you think we should restrict ‘autophagic cell death’ to insects?

Many thanks,

Paola

**Comment by paolaroncaglia** [comment]
@ukemi notes that autophagic cell death may exist in other species, just not been well studied yet. 
Paul and Marc agree. So maybe let's not limit it to insects after all.
However, we agree that the plant annotations should still be moved.

**Comment by tberardini** [comment]
I've moved the two TAIR annotations.  I can't access protein2go right now so can't raise the dispute on the remaining annotation. Can someone else do this please?  This record:
http://www.uniprot.org/uniprot/Q93VB2

**Comment by paolaroncaglia** [comment]
Thanks @tberardini !
Yes afraid P2GO is still unavailable, hopefully back up soon...

**Comment by hattrill** [comment]
I agree that autophagic cell death should not be restricted to Drosophila. It is somewhat fuzzy/controversial in terms of mechanism and context. PMID:22052193 gives some guidance.

**Comment by paolaroncaglia** [comment]
Thanks @hattrill . So we shall *not* further restrict 'autophagic cell death'.

**Comment by paolaroncaglia** [comment]
I emailed goa with this request:

"...When Protein2GO is back up, could you please move the following UniProt annotation

UniProtKB
Q93VB2
ATG18A
GO:0048102
autophagic cell death
P
IMP
PMID:21395886
3702
20130207
UniProt

from ‘autophagic cell death’ to ‘autophagy’ (or regulation thereof as appropriate)?"

Closing this ticket now. Thank you all.
