### ISSUE TITLE
Parentage of glycoprotein binding

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12580]
I noticed that 'glycoprotein binding ; GO:0001948' no longer has 'protein binding' parentage (flagged up because Protein2GO is no longer recognising the reciprocal protein binding annotations).

In ChEBI, 'glycoprotein ; CHEBI:17089' is_a: conjugated protein is_a: protein

Is this an inference issue, or a manual change? And can the 'protein binding' parentage be restored please?
Thank you!

**Comment by paolaroncaglia** [comment]
Hi @rebeccafoulger ,

Yes, the link glycoprotein binding is_a protein binding was removed as part of the recent ETINEs work
(for internal reference, see https://docs.google.com/spreadsheets/d/1bSkgMxMHm5Aqw6UuTzTNXuTbjVZ7Uvuyos4VrLk5y4c/edit#gid=0).
The bigger issue is outlined in a ticket owned by @dosumis , https://github.com/geneontology/go-ontology/issues/12341
@dosumis , shall I just add the link above manually for the time being?

Thanks,
Paola

**Comment by dosumis** [comment]
You could argue that this is a poor inference:  If binding is to the the glyco bit then it seems a bit odd to call it protein binding.  If you disagree - no harm in adding the is_a link by hand.

**Comment by paolaroncaglia** [comment]
Same as @dosumis , I do not fully approve of the glycoprotein binding is a protein binding link. It's the old issue, glycoprotein should not be is_a protein in ChEBI but rather has_part...

**Comment by cmungall** [comment]
> Same as @dosumis , I do not fully approve of the glycoprotein binding is a protein binding link. It's the old issue, glycoprotein should not be is_a protein in ChEBI but rather has_part... 

May be solved by #12341

**Comment by rebeccafoulger** [comment]
Okay- will wait for the ChEBI/PRO edits, thanks. I agree about the biology!

**Comment by ValWood** [comment]
Er..... it seems that I'm the only person who disagrees here. I would say that a glycoprotein is_a protein and glycoprotein_binding is_protein binding. Many proteins are glycoproteins and we don't even know.  
When we use 'glycoprotein binding' we are saying nothing about the region of the  glycoprotein which is bound. I think we would need a more specific term for that scenario?

What are the objections? To me the previously existing link made total sense?

**Comment by paolaroncaglia** [comment]
Tricky: a glycoprotein is *derived* from a protein by addition of glyco-stuff. It *is* a protein but with something else on. 

How do people use ‘glycoprotein binding’ in annotations? If the binding is to the glyco-bit of the protein, that may be relevant to know. But if the binding is somewhere else or if the site is not known, is the annotation informative? See the request for ‘modified protein binding’ and comments here (including @ValWood 's) https://github.com/geneontology/go-ontology/issues/12582

**Comment by srengel** [comment]
i agree with Val.
- a glycoprotein is_a protein and glycoprotein_binding is_protein binding.
- if we use 'glycoprotein binding' we are saying nothing about the region of the glycoprotein which is bound.
- the previously existing parentage under protein_binding made total sense

**Comment by mcourtot** [comment]
I agree with Val and Stacia. A glycoprotein is a protein with some sugar chain.When we annotate using 'glycoprotein binding' we don't say to which region of the protein the binding occurs, rather that we know that the binding partner is a glycoprotein. If we wanted to say something like "binds to the glycol of a glycoprotein" we would request a use a protein domain specific binding child, like for https://github.com/geneontology/go-ontology/issues/12585

**Comment by dosumis** [comment]
> What are the objections? To me the previously existing link made total sense?

Say protein X binds a particular polysaccharide and this polysaccharide is sometimes part of a glycoprotein, are you happy to say that protein X has protein binding activity?  The same could be said for any other major modification.  In that case, protein-binding no longer has much meaning. 

> When we use 'glycoprotein binding' we are saying nothing about the region of the glycoprotein which is bound. I think we would need a more specific term for that scenario?

True, but when you use 'glycoprotein binding' the possibility that the binding is not to the protein part of the glycoprotein remains open.  If, by inheritance, you have group all glycoprotein binding under protein binding, then you group the ones that do bind only to the polysaccharide component under protein binding.

Not massively committed to doing this one way or the other: just pointing out that there is a legitimate objection.

**Comment by ukemi** [comment]
I think we should discuss this at the meeting at USC. It seems that there are quite a few modified protein items coming up once again, particularly in the context of binding. For the record, when we did the ChEBI alignment, we decided that a glycoprotein had parts that were sugar and protein, specifically for the reasons that David describes. Doing that we could specify whether a particular entity like a lectin bound the protein portion or the sugar portion.

**Comment by ValWood** [comment]
Good plan. I notice there are not many  experimental annotations to  the exisiting glycoprotein binging  term 191 for 162 proteins , and I agree with D-O-S about its usefulness. 

At PomBase we have only used this term twice, for ngl1 and  yos9 which seem to bind/ be sensors for misfolded glycoproteins....even though we have 126 proteins annotated as glycosylated, and 24 of these have 'protein binding' annotations, so all of these could be to "glycoprotein binding".

I think we could definitely be more consistent and convey better what we mean if we used column 17  and request a PRO ID for the modified protein. These can be general, the protein is modified, or specific for the exact residue(s), which allows much more detail to be captured.

This is a related ticket
https://github.com/geneontology/go-ontology/issues/12582

This would tell you if the residue was a pre-requisite for the binding to occur.  
This works if  glycoprotein has_part protein and sugar. Has_part and annotation propagation still concerns me though.....

**Comment by pgaudet** [comment]
I added this to the USC agenda. We should have clearer policies about this. Either we annotate modified proteins binding or we dont. The current solution does not produce consistent annotations.

**Comment by paolaroncaglia** [comment]
To be discussed at today's editors call if we have time: http://wiki.geneontology.org/index.php/Ontology_meeting_2016-08-25#Modified_proteins

**Comment by paolaroncaglia** [comment]
The GO Editors are discussing this topic, and will then formulate a proposal to present to the wider group.
In the meantime, I'm labelling this ticket as pending. Thanks.

**Comment by mcourtot** [comment]
Note that while we discussed the modified protein proposal, we haven't addressed the original question about parentage of glycoprotein. In the ontology currently, glycoprotein is a chebi:protein, while protein binding is defined using pro. So it seems the intent is clear here to have glycoprotein be a protein and glycoprotein be a protein binding, but the use of 2 different protein classes causes issues, such as https://github.com/geneontology/go-annotation/issues/1462

If the link removed as part of the ETINES is not compensated by the correct inference it should be manually restored.

**Comment by paolaroncaglia** [comment]
Thanks @mcourtot . Added link 'glycoprotein binding' is_a 'protein binding'.
Closing this now as the 'modified protein binding' proposal is being discussed elsewhere.
