### ISSUE TITLE
NTR: ubiquitinated protein binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12582]
Hello, 

I'd like to request a new term, 'ubiquitinated protein binding', as a child of 'protein binding (GO:0005515). You might also want to create 'modified peotein binding'? 

The existing term 'ubiquitinated histone binding' (GO:0061649) should be added as a child. 

I ran into this while curating PTHR21220: Human SPRTN (Q9H040) is annotated to ubiquitin binding, but it should be 'ubiquitinated protein binding' 

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
Hi @pgaudet,

While I fully agree that if a gene product is annotated to ‘ubiquitin binding’ but it doesn’t bind ubiquitin the annotation should be (re)moved, I’m unsure about adding 'ubiquitinated protein binding’, and about the informative-ness of an annotation stating that a gene product binds a protein somewhere and that the same protein is ubiquitinated somewhere else. (If the ubiquitination affects the binding, that should be captured via LEGO, right?) You suggest we might also want to create 'modified protein binding' - but I’m not sure if that would really add much value - so many gene products would be annotated to it. @ukemi may I ask for your feedback here please, as you added 'ubiquitinated histone binding' (GO:0061649) fairly recently. Though we do tend to treat histones differently for biological reasons.

Thanks,

Paola

**Comment by ValWood** [comment]
Hi Pascale,
At PomBase we request a PRO ID for the modified form
https://sourceforge.net/p/pro-obo/term-requests/
and then  we use the PRO ID  of the modified  form in column 17 
So we would have  x protein binding y(phosphorylated form).
It seems more scalable and fits the scope of the column 17 (Gene Product Form ID)
http://geneontology.org/page/go-annotation-file-gaf-format-21
Val

Val

**Comment by ukemi** [comment]
Hi Paola,

I added the term because we already have other modified histone binding terms. However, I agree with Val that in general, this is probably not globally sustainable (similar to many many other protein binding discussions we have had)  and her solution to capture this in column 16 or column 17 depending on whether the modified form is the target or the agent seems like a good one. It also fits well with the LEGO modeling. 

-D

**Comment by ValWood** [comment]
Well, not my solution....Midori's really IIRC.....

**Comment by pgaudet** [comment]
I added this to the USC agenda. We should have clearer policies about this. Either we annotate modified proteins binding or we dont. The current solution does not produce consistent annotations.

**Comment by paolaroncaglia** [comment]
To be discussed at today's editors call if we have time: http://wiki.geneontology.org/index.php/Ontology_meeting_2016-08-25#Modified_proteins

**Comment by paolaroncaglia** [comment]
The GO Editors are discussing this topic, and will then formulate a proposal to present to the wider group.
In the meantime, I'm labelling this ticket as pending. Thanks.

**Comment by paolaroncaglia** [comment]
This request is now superseded by the umbrella ticket linked above, i.e. https://github.com/geneontology/go-ontology/issues/12787, so I’ll close this one.
