### ISSUE TITLE
NTR: disordered protein domain specific binding

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#12585]
Hello,

I am currently annotating paper PMID:11746698 and have been unable to capture the information about binding specifically to a disordered domain of a protein.

I would like to request a new term: disordered protein domain specific binding, which would be a child of protein domain specific binding (GO:0019904). The definition could be: Interacting selectively and non-covalently with a specific disordered domain of a protein. 

Thanks in advance!

Best,

George Georghiou

**Comment by mcourtot** [comment]
I would maybe change the label to "disordered domain specific binding", to (1) make it a bit clearer that the binding occurs at the disordered domain and not anywhere on the disordered protein (2) make it more homogenous with sibling terms. Maybe also change the definition slightly to remove "specific" and become "Interacting selectively and non-covalently with a disordered domain of a protein".

![screen shot 2016-08-18 at 17 29 18](https://cloud.githubusercontent.com/assets/2214135/17781965/56b035f8-6569-11e6-9bf5-e463503cd8ff.png)

**Comment by paolaroncaglia** [comment]
Hi @ggeorghiou and @zebrafishembryo 
I added the term as follows (thanks @mcourtot for your suggestions):

 [Term]
+id: GO:0097718
+name: disordered domain specific binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a disordered domain of a protein." [PMID:11746698]
+synonym: "disordered protein domain specific binding" RELATED []
+is_a: GO:0019904 ! protein domain specific binding

The term is ready to use. However,
NOTE FOR SELF 
I need to add GOC: initials for George to the new term,
and before that I need to submit an entry for him in https://github.com/geneontology/go-site/blob/master/metadata/users.yaml
@ggeorghiou, do you have an ORCID id? If not please request one at http://orcid.org, thanks.

**Comment by ggeorghiou** [comment]
Hi Paola,
My Orcid ID is: orcid.org/0000-0001-5067-3199

**Comment by mcourtot** [comment]
Done revision 35118

**Comment by paolaroncaglia** [comment]
Thanks @mcourtot  and @ggeorghiou .
