### ISSUE TITLE
NTRs: "mitochondria-derived vesicle" & "mitochondrion to lysosome transport"

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12586]
Hello,

I am currently annotating a paper on Parkinson's Disease-associated VPS35 (PMID-26618722) and have not been able to capture the information from Figure 6.

Earlier figures (e.g. Figure 4) in this paper showed that VPS35 positively regulates the turnover of mitochondrial DLP1 complexes. I have not yet been able to capture this information, as I have not found an appropriate term, but I will come back to this after having discussed it at UCL first.

Figure 6 shows that VPS35 over-expression increases the localisation of DLP1 to mitochondria-derived vesicles, whereas VPS35 knock-down has the opposite effect. It also shows that VPS35 is required for transport of the mitochondria-derived vesicles from mitochondria to lysosomes.

I would like to request two new terms:
1) "mitochondria-derived vesicle"
2) "mitochondrion to lysosome transport" 

The definition for "mitochondrion to lysosome transport" would need to indicate that this term describes the transport of mitochondria-derived vesicles, or an alternative term could be "mitochondria-derived vesicle transport to lysosome"

To create the following annotations:
O00429 DLP1      GO:mitochondria-derived vesicle
Q96QK1 VPS35   GO:mitochondrion to lysosome transport   AE transports_or_maintains_localisation_of O00429 DLP1, causally_upstream_of GO:1905146 lysosomal protein catabolic process

Thanks,
Barbara

DbxREFs: GOC:PARL, GOC:bc

cc: @RLovering 
cc: @rebeccafoulger 
cc: @Pauldenny

**Comment by dosumis** [comment]
This can follow standard patterns for vesicle mediated transport. Transport
term can have have 'mediated by' relationship to vesicle term.

**Comment by Pauldenny** [comment]
Just realised these terms are mechanistically identical to [https://github.com/geneontology/go-ontology/issues/12193](url)
#12193 
@ukemi

**Comment by dosumis** [comment]
Pattern example:

![image](https://cloud.githubusercontent.com/assets/112839/17775992/b5264c1a-6552-11e6-8d2b-027f570a3cd1.png)

If you need a general term for transport from mitochondrion then the ' has target end location' clause can just be omitted from the pattern.

**Comment by paolaroncaglia** [comment]
As @Pauldenny pointed out, this request is a duplicate of https://github.com/geneontology/go-ontology/issues/12193 which is assigned to @ukemi. So I'll close this. @BarbaraCzub , I see you already subscribed to https://github.com/geneontology/go-ontology/issues/12193, so you'll be notified when that's done. Thank you all.
