### ISSUE TITLE
add neuroregeneration (synonym or NTR?)

### ISSUE THREAD

**Issue by nlwashington** [geneontology/go-ontology#12589]
I'd like to see "neuroregeneration" a term to be found in go.  The closest term to this currently is "neuron projection regeneration" [GO:0031102](http://purl.obolibrary.org/obo/GO_0031102), but this class is defined only to represent the regrowth part, not the repair part as defined in the [neuroregeneration wiki](https://en.wikipedia.org/wiki/Neuroregeneration) article.  I would argue that regrowth != repair in all cases.

Can you add this as a synonym, if appropriate, or add in this as a parent process to the existing class?  If indeed you add it as a new class, I wonder if there should also be added some kind of grouping class for generic "cellular repair" for which all the repair processes are part_of?

**Comment by paolaroncaglia** [comment]
Hi @nlwashington ,

GO:0031099 ’regeneration’ is defined as “The regrowth of a lost or destroyed body part, such as an organ or tissue.”. The definition doesn’t specifically mention ‘repair’, but the term xref points to this useful Wikipedia entry:

https://en.wikipedia.org/wiki/Regeneration_(biology)

“In biology, regeneration is the process of renewal, restoration, and growth that makes genomes, cells, organisms, and ecosystems resilient to natural fluctuations or events that cause disturbance or damage.”

where restoration = repair
So here’s what I did

1) I expanded the def. of ‘regeneration’ from old “The regrowth of a lost or destroyed body part, such as an organ or tissue.” to new “The regrowth of a lost or destroyed body part, such as an organ or tissue. This process may occur via renewal, repair, and/or growth alone (i.e. increase in size or mass).” (From GO:0040007 growth “The increase in size or mass of an entire organism, a part of an organism or a cell.”) Children and descendants of ‘regeneration’ don’t need to be added this definition gloss - curators can and should refer to the ancestor if in doubt.

2) I added a new term:
GO:0097719 neural tissue regeneration
logical def: is_a GO:0031099 ’regeneration’, results_in_maturation_of UBERON:0003714 ‘neural tissue’
[where UBERON:0003714 ‘neural tissue’ = “Portion of tissue in the nervous system which consists of neurons and glial cells, and may also contain parts of the vasculature.” Synonyms: nervous tissue, nerve tissue, portion of neural tissue]
Textual def (standard): The regrowth of neural tissue following its loss or destruction.
Dbxref: https://en.wikipedia.org/wiki/Neuroregeneration
synonym (related): neuroregeneration

(Note - the ‘maturation’ bit in the logical def doesn’t sound quite right to me. I opened a separate ticket about that, https://github.com/geneontology/go-ontology/issues/12618.)

As for your question
“If indeed you add it [neuroregeneration] as a new class, I wonder if there should also be added some kind of grouping class for generic "cellular repair" for which all the repair processes are part_of?”

GO has terms to indicate the repair of specific molecular components inside a cell, e.g. ‘DNA repair’ and ‘protein repair’ which fall under the metabolism branch. Generic ‘cellular repair’ sounds ambiguous to me and quite broad. I presume you’re referring to e.g. the existing ‘neuron projection regeneration’. This term is currently (distantly) linked to ‘nervous system’ (parent of ’neural tissue’), via CL:0002319 ‘neural cell’ part_of UBERON:0001016 ’nervous system’.  

In order for ‘neuron projection regeneration’ to be automatically classified under ‘neural tissue regeneration’, you’d need to ask CL and UBERON to make CL:0002319 ‘neural cell’ part_of UBERON:0003714 ‘neural tissue’. Which would sound more specific and appropriate to me. But I’ll leave it to you :-)

Closing this ticket now. **Readers, please direct any comment on the ‘maturation’ relationship here https://github.com/geneontology/go-ontology/issues/12618, and on the CL/UBERON trackers for the neural cell/tissue issue.** Thanks.
