### ISSUE TITLE
Add taxon checks for signaling pathways

### ISSUE THREAD

**Issue by selewis** [geneontology/go-ontology#12581]
These were found from a "PAINT" issue (https://github.com/geneontology/paint/issues/25)

The annotation of RCN1 (aka P36054) to GO:0070884 regulation of calcineurin-NFAT signaling cascade is valid. This is in PTHR10300. Someone needs to say whether or not it should pass the taxon checks or not. (and fix accordingly) Use this to test (Taxon 559292 is yeast) http://owlservices.berkeleybop.org/isClassApplicableForTaxon?format=txt&idstyle=obo&id=GO:0070884&taxid=NCBITaxon:559292

The same is true for the annotation of YCK1 (aka P23291) to GO:0016055 (Wnt signaling pathway) in family PTHR11909. Taxon checks are showing this as valid, so, if it is not possible biologically, then the fix has to be there.

**Comment by dianeoinglis** [comment]
This issue seems to span more than one ticket. 

The calcineurin pathway is conserved from yeast to humans. In humans, calcineurin acts with NFAT in the immune system. In yeast and other fungi, calcineurin functions in stress responses but NFAT does not exist in yeast nor does an immune cell function.  It is the conjugation of calcineurin and NFAT as a signalling pathway that creates a problem for propagation to yeast. Calcineurin is fine, it is NFAT that does not apply to an organism without an immune system.

**Comment by paolaroncaglia** [comment]
Thanks @dianeoinglis .
Based on your feedback, I’d restrict ‘calcineurin-NFAT signaling cascade’ to ‘only in Metazoa’.
Do we need to add a separate term for ’calcineurin pathway’? If yes, could you please suggest a definition, placement and references.

As for GO:0016055 (Wnt signaling pathway), I’d also restrict it to ‘only in Metazoa’ (see https://en.wikipedia.org/wiki/Wnt_signaling_pathway). Though, I’m wondering if the taxon rule should be applied to its parent ‘cell-cell signaling by wnt’ instead. Asking @dosumis as he added ‘cell-cell signaling by wnt’.

Thanks,

Paola

**Comment by cmungall** [comment]
The long term solution should be to axiomatize the pathways based on the ancestral proteins involved and inherit the taxon constraints from those. This may seem a bit circular but I think that's OK, we just end up coordinating the engineering of the signaling part of GO with curating the families.

@rebeccafoulger and I started on this a while ago, x-signaling.owl in the extensions directory

**Comment by dianeoinglis** [comment]
Yes, I do think a separate term for ’calcineurin pathway' or possibly a better term is "calcineurin signalling." Calcineurin regulates quite a few responses in yeast and mammals and the singular "pathway" seems restrictive. "Calcineurin signalling" allows for multiple responses to calcineurin. I can definitely suggest a definition, suggest placement and include references.

**Comment by dianeoinglis** [comment]
Opened new ticket for NTR, 
https://github.com/geneontology/go-ontology/issues/12591

**Comment by paolaroncaglia** [comment]
Note for self: the new term from https://github.com/geneontology/go-ontology/issues/12591 is
GO:0097720 calcineurin-mediated signaling

**Comment by paolaroncaglia** [comment]
Hi @selewis,

As a quick fix, I restricted ‘calcineurin-NFAT signaling cascade’ and ‘Wnt signaling pathway’ to ‘only in Metazoa’.
I’ll now assign to @cmungall for him to strategize the long-term solution.

**Comment by pgaudet** [comment]
@selewis Do we have a systematic solution for this ? Perhaps we need to create new tickets for each pathway ? 

(if that's the case we could close this ticket) 

Thanks, Pascale
