### ISSUE TITLE
NTR (from TG): endopeptidase complexes - please add relationships

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12584]
I have just created these terms in TG to build the hierarchy for the serine-type endopeptidase complex. Please add the following relationships:

GO:1905369 (NEW) endopeptidase complex 
is_a GO:1905368 (NEW) peptidase complex 

GO:1905370 (NEW) serine-type endopeptidase complex 
is_a GO:1905369 (NEW) endopeptidase complex 
is_a GO:1905286 serine-type peptidase complex

Thanks,
Birgit

**Comment by paolaroncaglia** [comment]
Note for self: the requested relationships may be added automatically once the GO build goes back to normal; will check (there's an error at the moment, plus TG is down)

**Comment by ValWood** [comment]
Note that if you add this, LOTs of existing complexes will need to move underneath the new terms.
For example
COP9 signalosome
proteasome
signal peptidase complex
m-AAA complex
any complex which has a ubiquitin hydrolase e.g.	SAGA complex (there will be many of these), another example is poly(A)-specific ribonuclease complex 
separase-securin complex

even the nuclear pore appears to have  peptidase activity (although I don't know if this is active)

Will the reasoner pick up all of these?

**Comment by bmeldal** [comment]
Val, that's always the issue which adding new terms. Unless the existing terms already have the capable_of (endo)-peptidase activity relationship the reasoner won't pick them up. But who's got the time to trawl through >400 complexes sat as direct children of 'protein complex' and check if they need to be moved, too. 

As you have listed some, they could be moved by hand once the new relationships are in the file.

**Comment by dosumis** [comment]
>  Note for self: the requested relationships may be added automatically once the GO build goes back to normal; will check (there's an error at the moment, plus TG is down)

Yep - is_a links should be added automatically as long as terms added as TG template and not freeform.  Based on existing axioms, the new terms will have a few automatically added subclasses:

'caspase complex'
'glutathione hydrolase complex'
'H-gal-GP complex'
'serine-type peptidase complex'

If simple axioms declaring the function of complexes are added when new complex terms are added  (e.g. relationship: capable_of peptidase activity), then we'll get lots more of this.   

There are some cases where this would have been trivial:

![image](https://cloud.githubusercontent.com/assets/112839/17742363/a46e144a-6497-11e6-9b22-046fd4b758ba.png)

Note: proteasome complex has:

'capable of part of' some 'protein catabolic process'.  Presumably needs to be just tightened up to MF.

**Comment by bmeldal** [comment]
>as long as terms added as TG template

Yes, that's what I used. [And I thought the FF is not available at the moment anyway even if I wanted to sue it?]

>If simple axioms declaring the function of complexes are added when new complex terms are added (e.g. relationship: capable_of peptidase activity), then we'll get lots more of this. 
There are some cases where this would have been trivial

Yes, I do add the axioms for new terms but the above examples are historic.

**Comment by paolaroncaglia** [comment]
These terms are now live and will get the appropriate parentage automatically:

GO:1905368 Label: peptidase complex
GO:1905369 Label: endopeptidase complex
GO:1905370 Label: serine-type endopeptidase complex

As for placing old, existing protein complex terms manually under the new terms above, I’m afraid resources are quite limited at this stage, and we’d rather not go through long lists manually (and yes we should add axioms rather than simply add is_a parents, as @dosumis pointed out.) Probably not a top priority at this stage, so I’ll close this ticket I’m afraid…  

@bmeldal, in answer to your question
“I thought the [TG] FF is not available at the moment anyway even if I wanted to use it?”
TG FF hasn’t been turned off, but shouldn’t be used. Please use this tracker instead, for non-templateable requests.

Thanks,

Paola

**Comment by bmeldal** [comment]
Thanks, Paula. I wasn't suggesting that we'll go back manually to re-position historic complexes, just as and when we fall over them because we are actually using them :)

As for TG FF - it's as good as 'n/a' if we shouldn't use it ;-) I have used this tracker already for a couple of requests that would have normally gone into FF.

**Comment by paolaroncaglia** [comment]
Thanks @bmeldal . At the time, we couldn't fully disable TG FF, but we'll be looking into it again.

**Comment by ValWood** [comment]
> just as and when we fall over them because we are actually using them :)

Yes if they can't be inferred we should add them  as we spot them.
I  will open a ticket for the ones above...

**Comment by bmeldal** [comment]
Thanks, Val.
