### ISSUE TITLE
protein glycation parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12596]
https://github.com/geneontology/go-ontology/issues/12550
Could this also have
"cellular detoxification" 
as a parent?

(I'm trying to pull together the detoxification terms in our slim...many of the remaining unstudied proteins seem to be 'cellular detoxification' of some sort.)
http://www.pombase.org/spombe/result/SPAC22E12.03c

@rebeccafoulger ?

**Comment by paolaroncaglia** [comment]
I'll assign this to @rebeccafoulger for her to comment when she's back from summer leave. 
Becky, feel free to assign back to me for edits then, thank you.

**Comment by rebeccafoulger** [comment]
The degylcation enzymes I've been curating are involved in the early steps, removing MGO or GO from glycated proteins to stop them forming AGEs (advanced glycation end products). I don't think the early glycated products themselves are always toxic, but rather go on to form toxic end-products. If this still fits with 'cellular detoxification' then I'm fine with this additional parentage.

Note that it's currently 'protein deglycation ; GO:0036525' is_a: 'protein repair ; GO:0030091'.

**Comment by ValWood** [comment]
OK, I guess it should be a broader question,  should protein  repair, DNA repair and RNA surveillance be considered 'cellular detoxification'.  Will continue to think about this, and ask some experts.
