### ISSUE TITLE
NTRs: response to viscosity + copper ion transport across BBB/BCB

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12594]
Stan requested the following terms via TermGenie freeform. The tool is broken, so I will add them manually: (for reference see http://wiki.geneontology.org/index.php/Ontology_meeting_2016-08-18#TG_freeform)

name: response to viscosity
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a viscosity stimulus." [PMID:7061416]
is_a: GO:0006950 ! response to stress

name: copper ion transport across blood-brain barrier
namespace: biological_process
def: "The directed movement of copper ions passing through the blood-brain barrier." [PMID:24614235]
synonym: "copper ion transport across BBB" RELATED []
is_a: GO:0035434 ! copper ion transmembrane transport

name: copper ion transport across blood-CSF barrier
namespace: biological_process
def: "The directed movement of copper ions passing through the blood-cerebrospinal fluid barrier." [PMID:24614235]
synonym: "copper ion transport across BCB" EXACT []
synonym: "copper ion transport across blood-cerebrospinal fluid barrier" EXACT []
is_a: GO:0035434 ! copper ion transmembrane transport

**Comment by slaulederkind** [comment]
Hi Paolo, Could you also add:

name: cellular response to viscosity
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a viscosity stimulus." [PMID:7061416]
is_a: response to viscosity

**Comment by paolaroncaglia** [comment]
Hi @slaulederkind,
Done. The new term stanzas are below. Note that viscosity is a quality, not a stress 
(see http://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000992)
so I added ‘response to viscosity’ as is_a ‘response to abiotic stimulus’. 
Also, the blood–brain barrier and the blood-CSF barrier are formed by cells, so I added ‘copper ion transport across blood-brain/CSF barrier’ as is_a copper ion transport, rather than is_a copper ion *transmembrane* transport.

 [Term]
+id: GO:0097714
+name: response to viscosity
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a viscosity stimulus." [GOC:sl, PMID:7061416]
+is_a: GO:0009628 ! response to abiotic stimulus

+[Term]
+id: GO:0097715
+name: cellular response to viscosity
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a viscosity stimulus." [GOC:sl, PMID:7061416]
+is_a: GO:0071214 ! cellular response to abiotic stimulus
+is_a: GO:0097714 ! response to viscosity

+[Term]
+id: GO:0097716
+name: copper ion transport across blood-brain barrier
+namespace: biological_process
+def: "The directed movement of copper (Cu) ions passing through the blood-brain barrier." [GOC:sl, PMID:24614235]
+synonym: "copper ion transport across BBB" RELATED []
+is_a: GO:0006825 ! copper ion transport

+[Term]
+id: GO:0097717
+name: copper ion transport across blood-cerebrospinal fluid barrier
+namespace: biological_process
+def: "The directed movement of copper (Cu) ions passing through the blood-cerebrospinal fluid barrier." [GOC:sl, PMID:24614235]
+synonym: "copper ion transport across BCB" RELATED []
+synonym: "copper ion transport across blood-CSF barrier" EXACT []
+is_a: GO:0006825 ! copper ion transport

**Comment by dosumis** [comment]
HI Paola,

Given relevant Uberon terms, the following these two could be formally defined using 'results in transport across':
 
[Term]
id: GO:0097716
name: copper ion transport across blood-brain barrier
namespace: biological_process
def: "The directed movement of copper (Cu) ions passing through the blood-brain barrier." [GOC:sl, PMID:24614235]
synonym: "copper ion transport across BBB" RELATED []

- is_a: GO:0006825 ! copper ion transport

+intersection_of: transport
+intersection_of: transports_or_maintains_localization_of copper ion (Chebi)
+intersection_of: results_in_transport_across blood brain barrier (Uberon)


[Term]
id: GO:0097717
name: copper ion transport across blood-cerebrospinal fluid barrier
namespace: biological_process
def: "The directed movement of copper (Cu) ions passing through the blood-cerebrospinal fluid barrier." [GOC:sl, PMID:24614235]
synonym: "copper ion transport across BCB" RELATED []
synonym: "copper ion transport across blood-CSF barrier" EXACT []

…



- David

**Comment by paolaroncaglia** [comment]
Thanks @dosumis . Found the Uberon terms:
UBERON_0000120 blood brain barrier
UBERON_0003210 blood-cerebrospinal fluid barrier
Will do - not an immediate priority though ;-)

**Comment by paolaroncaglia** [comment]
Added logical defs to BBB and BCB terms.
