### ISSUE TITLE
AP-1 complex - yup, which one!?!?!

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12592]
Hi, 

There are two commonly named "AP-1 complexes" (with and without hyphen), both of which are in our release pipeline right now:
GO:0035976 AP1 complex
and
GO:0030121 AP-1 adaptor complex

GO:0035976 also has exact synonyms "transcription factor AP1 complex" and "transcription factor AP-1 complex".
Could we swap the current name of "AP1 complex" to its synonym "transcription factor AP-1 complex", please? That will match what we are doing in the CP now.

Thanks,
Birgit

**Comment by mcourtot** [comment]
Done rev 35093.
