### ISSUE TITLE
NTR: Calcineurin signaling

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12591]
From #12580 
NTR: calcineurin signaling ->  prefer  "calcineurin-mediated signaling"
The new term should be a parent to GO: 0033173 "Calcineurin-NFAT signaling cascade" and a child of  GO:0019722 "calcium-mediated signaling."

Def: Calcineurin is a calcium and calmodulin dependent serine/threonine protein phosphatase with a conserved function in eukaryotic species from yeast to humans. In yeast and fungi, calcineurin regulates stress signaling, the cell cycle and sporulation and virulence in pathogenic fungi. In metazoans, calcineurin is involved in cell commitment, organogenesis and organ development and immune function of T-ymphocytes. Inhibitors of calcineurin activity include the immunosuppressive agents cyclosporin A, pimecrolimus and tacrolimus (rapamycin) and complexes of CsA–cyclophilin and FK506-FKB12. By a conserved mechasism, calcineurin phophatase activates fungal Crz1 and mammalian NFATc by dephosphorylation and translocation of these transcription factors to the nucleus to regulate gene expression.

PMID 25878052
PMID 26851544
PMID 25655284 

'

**Comment by paolaroncaglia** [comment]
@dianeoinglis , this is done:

[Term]
id: GO:0097720
name: calcineurin-mediated signaling
namespace: biological_process
def: "Any intracellular signal transduction in which the signal is passed on within the cell by activation of a transcription factor as a consequence of dephosphorylation by Ca(2+)-activated calcineurin. The process begins with calcium-dependent activation of the phosphatase calcineurin. Calcineurin is a calcium- and calmodulin-dependent serine/threonine protein phosphatase with a conserved function in eukaryotic species from yeast to humans. In yeast and fungi, calcineurin regulates stress signaling and cell cycle, and sporulation and virulence in pathogenic fungi. In metazoans, calcineurin is involved in cell commitment, organogenesis and organ development and immune function of T-lymphocytes. By a conserved mechanism, calcineurin phosphatase activates fungal Crz1 and mammalian NFATc by dephosphorylation and translocation of these transcription factors to the nucleus to regulate gene expression." [GOC:di, PMID:25655284, PMID:25878052, PMID:26851544]
synonym: "calcineurin signaling" RELATED []
synonym: "calcineurin-mediated signalling" EXACT []
is_a: GO:0019722 ! calcium-mediated signaling

Note I did not include this bit in the def as it’s not really within the scope of GO: “Inhibitors of calcineurin activity include the immunosuppressive agents cyclosporin A, pimecrolimus and tacrolimus (rapamycin) and complexes of CsA–cyclophilin and FK506-FKB12.”

I also made GO:0033173 calcineurin-NFAT signaling cascade is_a GO:NEW calcineurin-mediated signaling, and fixed a typo in the def of calcineurin-NFAT signaling cascade. Closing now.
