### ISSUE TITLE
Add relationships to appropriate 'peptidase complex'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12597]
Follow on from
https://github.com/geneontology/go-ontology/issues/12584#issuecomment-240750848

COP9 signalosome
proteasome
signal peptidase complex
m-AAA complex
any complex which has a ubiquitin hydrolase e.g. SAGA complex (there will be many of these), another example is poly(A)-specific ribonuclease complex 
separase-securin complex

**Comment by dosumis** [comment]
Hi Val,

Please could you suggest an appropriate MF term for the activities of each of these complexes (should peptidase activity be used for all, or should a more specific type of peptidase be specified?)

Cheers,
David

**Comment by ValWood** [comment]
proteasome
separase-securin complex are endopeptidases the others, just peptidase I guess

**Comment by dosumis** [comment]
DONE:  
 - [x] proteasome
 - [x] signal peptidase complex
 - [x] m-AAA complex
 - [x] separase-securin complex


Each needs supporting ref for peptidase activity (or at least a comment to explain reason for believing complex has this activity).  Suggested rephrasing def to take this into account would also be useful:

 - [ ] COP9 signalosome
 - [ ] PAN complex <-- needs supporting ref for peptidase activity
 - [ ] SAGA complex <-- needs supporting ref for peptidase activity

**Comment by ValWood** [comment]
SAGA complex 
ubp8 has	thiol-dependent ubiquitin-specific protease activity	IDA		Kouranti I et al. (2010)

**Comment by ValWood** [comment]
PAN complex, COP9 signalosome can leave these one, evidence only from sequence similarity at present

**Comment by dosumis** [comment]
> SAGA complex 
> ubp8 has thiol-dependent ubiquitin-specific protease activity IDA Kouranti I et al. (2010)

Ta.  Will add, but... no mention of ubp-8 in def:

SAGA complex: 'A SAGA-type histone acetyltransferase complex that contains Spt8 (in budding yeast) or a homolog thereof; additional polypeptides include Spt group, consisting of Spt7, Spt3, and Spt20/Ada5, which interact with the TATA-binding protein (TBP); the Ada group, consisting of Ada1, Ada2, Ada3, Ada4/Gcn5, and Ada5/Spt20, which is functionally linked to the nucleosomal HAT activity; Tra1, an ATM/PI-3 kinase-related protein that targets DNA-bound activators for recruitment to promoters; the TBP-associated factor (TAF) proteins, consisting of Taf5, Taf6, Taf9, Taf10, and Taf12, which mediate nucleosomal HAT activity and are thought to help recruit the basal transcription machinery.'

How should I modify to make clear which component has the activity?  Would like to make this easy to trace for future editors.

**Comment by ValWood** [comment]
The def excludes a number of subunits (it only says *includes*)
sgf11
sgf29
sgf73
spt8
sus1
ubp8


Also mentioned twice Spt20/Ada5 Ada5/Spt20

**Comment by dosumis** [comment]
So I could add: "It also contains a ubp8, a peptidase."  and add the ref PMID:20838651  ( Kouranti I et al. (2010))

But looking at this paper: "we identified known interactions of Ubp8 with the SAGA complex"  So is it part of the complex or does it interact with it?  How can we ever distinguish these things... (This seems to me to be part of the general nightmare of GO dealing with complexes.  Ho hum....)

**Comment by ValWood** [comment]
Yes Ubp8 is a prior known bona fida  subunit of the SAGA complex

http://www.yeastgenome.org/locus/S000004836/overview#go
http://www.pombase.org/spombe/result/SPAC13A11.04c#go-cellular_component

I'm only using the above ref to support  the protease activity.

**Comment by dosumis** [comment]
Fixed.
