### ISSUE TITLE
ntr: dolichol-phosphate-mannose synthase regulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12599]
dolichol-phosphate-mannose synthase complex PMID: 10835346
is_a
GO:0030234	enzyme regulator activity
standard regulator def

**Comment by paolaroncaglia** [comment]
Done:

 [Term]
+id: GO:0097713
+name: dolichol-phosphate-mannose synthase regulator activity
+namespace: molecular_function
+def: "Binds to and modulates the activity of dolichol-phosphate-mannose synthase." [GOC:vw, PMID:10835346]
+is_a: GO:0030234 ! enzyme regulator activity
