### ISSUE TITLE
cohesin kleisin exit gate opening MF

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12608]
Hi David,

On the recent  Skype we discussed this as a MF and you thought that we did not know the mechanism, so it could not be included. 

I still think there is enough for a molecular function term here...

It has been suggested that Wapl facilitates cohesin dissocia- tion from chromosomes by opening a DNA exit gate between the kleisin N terminus and Smc3 (Chan et al., 2012; Huis in ’t Veld et al., 2014). We therefore tested whether Wapl indeed causes dissociation of the Rad21 N terminus from fission yeast Psm3. We used purified cohesin tetramers in which one of the two separase cleavage sites in Rad21 was changed for the recognition sequence of TEV protease (Murayama and Uhlmann, 2014; Tomonaga et al., 2000). Following TEV cleavage, both the N- and C-terminal cleavage products (Rad21N and Rad21C, respectively) remained associated with the cohesin tetramer, which was immunopurified from the reaction via an epitope tag on Psm3. Addition of Pds5-Wapl resulted in loss of Rad21N, but not Rad21C, from the cohesin complex, demonstrating that Pds5-Wapl indeed displaces the kleisin N terminus (Figures 4B and S4A). Rad21N displacement occurred in the presence of ATP or ATP-g-S, but not in the presence of ADP or in the absence of nucleotide. In contrast, Mis4-Ssl3 in the presence or absence of ATP and DNA did not achieve Rad21N displace- ment (Figure S4B). These results confirm that Pds5-Wapl opens the cohesin ring interface between Rad21N and Psm3. The requirement for ATP, but not its hydrolysis, further suggests that the Rad21N-Psm3 interface only opens if the SMC head dimer is occupied by ATP and therefore closed.

![exit gate](https://cloud.githubusercontent.com/assets/7359272/17887674/73cd3b54-691f-11e6-8d37-6f45aab80543.jpg)

A tentative definition

ATP-dependent catalysis of the dissociation of a kleisin molecule  from cohesin to enable cohesin unloading from DNA.

If you still think unsuitable can we capture this as a process so it is a subpart of 'unloading'.Its a shame not to capture this specific detachment of Kleisin as its such an elegant experiment, and the MF almost certainly occurs.....I don't want to lose the info....

**Comment by ValWood** [comment]
I just noticed I have an older ticket for this. I think this one is clearer so  I'll close the other one:

https://github.com/geneontology/go-ontology/issues/12531

**Comment by ValWood** [comment]
So the 2 steps of unloading are
1. SMC head disengagement
2. Kleisin (Rad21N) disengagement (this would be a synonym for  cohesin kleisin exit gate opening)

" SMC head disengagement. After this, DNA exit remains dependent on the presence of ATP, but not its hydrolysis, consistent with the characteristics of Rad21N disengagement."

**Comment by ukemi** [comment]
But what is the molecular function really? It seems like what we really want is something like the opposite of protein binding. Protein dissociation activity??? I think we should make a model and bring this up on an annotation call. It seems like we should be able to come up with a generic molecular function for this type of dissociation since I suspect we will encounter it over and over again. A term like cohesin exit gate opening seems like a bit of a fudge to me because it isn't classifiable in the current structure. It's just a descriptive way of describing what is happening in this special case.

**Comment by ValWood** [comment]
Don't worry about this one David, it predated this one which was opened when I made the LEGO model! http://noctua.berkeleybop.org/editor/graph/gomodel:57c4867e00000026?barista_token=wr9rgbigvb5dlcbmnral

I have this ticket, pending reading future papers
https://github.com/geneontology/go-ontology/issues/12623

This will be a while, I have put my mitotic chromosome segregation project on hold to tackle G/2 M transition  because it is more directly relevant to cell cycle project.
