### ISSUE TITLE
estrogen 2-hydroxylase activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12601]
NTR: estrogen 2-hydroxylase activity
Is_a child of GO:0008395 steroid hydroxylase activity (sibling to GO:0101020 estrogen 16-alpha-hydroxylase activity)

For annotation of PMID:14559847. Table 1 shows estrogen 2-hydroxylation for human CYP isoforms.

Note I wonder if instead these term should be less specific estrogen hydroxylase activity and therefore rename the GO:0101020 estrogen 16-alpha-hydroxylase activity)?

Please remember to add the DbxREFs: GOC:rl and GOC:BHF

Thanks,
Ruth.

Note to self: for Fiona's annotation.

@rachhuntley

**Comment by tberardini** [comment]
Melanie - assigning to you as you created GO:0101020, estrogen 16-alpha-hydroxylase activity with this def:

    Catalysis of the reaction: estrogen + donor-H2 + O2 = 6-alpha-hydroxyestrogen + H2O. Source: GOC:mec

**Comment by mcourtot** [comment]
Done.
[Term]
id: GO:0101021
name: estrogen 2-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: estrogen + donor-H2 + O2 = 2-hydroxyestrogen + H2O." [GOC:BHF, GOC:rl, PMID:14559847]
synonym: "oestrogen 2-hydroxylase activity" EXACT []
is_a: GO:0008395 ! steroid hydroxylase activity
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

@RLovering: I think estrogen 2-hydroxylase activity is ok and consistent with what we already have, but please open another ticket if you disagree.
 
![screen shot 2016-08-23 at 11 40 08](https://cloud.githubusercontent.com/assets/2214135/17889338/9a72525a-6927-11e6-8eaf-fd5e18f2a8e6.png)
