### ISSUE TITLE
GO:0031988 membrane-bounded vesicle CC - odd hierarchy / naming

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12604]
Hi David
GO:0031988 membrane-bounded vesicle
ancestry looks odd.
![image](https://cloud.githubusercontent.com/assets/12345463/17855709/038dfffc-6872-11e6-9ab8-382d5a175720.png)
GO:0031988 membrane-bounded vesicle
Definition	Any small, fluid-filled, spherical organelle enclosed by a lipid bilayer.
is_a
GO:0031982 vesicle
Definition	Any small, fluid-filled, spherical organelle enclosed by membrane.
is_a
GO:0043227 membrane-bounded organelle 
Def. Organized structure of distinctive morphology and function, bounded by a single or double lipid bilayer membrane. Includes the nucleus, mitochondria, plastids, vacuoles, and vesicles. Excludes the plasma membrane.

Why is 
GO:0031988 membrane-bounded vesicle 
not called "lipid bilayer-bounded vesicle" 
(or similar)? NB it's parent (GO:0031982) has "membrane" in its definition, whereas
GO:0031988
has membrane in its name, but NOT in its definition? 
@RLovering 
@BarbaraCzub

**Comment by mah11** [comment]
This looks like some incomplete tidying up after a change in how GO CC classifies GO:0031411 ! gas vesicle -- back when GO:0031411 was requested and added, we also added GO:0031988 so GO:0031982 could have GO:0031988 and GO:0031411 as subclasses. Subsequently, GO:0031411 was moved out of the "vesicle" branch, leaving no real difference between GO:0031982 and GO:0031988 (i.e. they could be merged).

ancient history in #2423, #3421, #4075

**Comment by Pauldenny** [comment]
What would be implications of merge? - it looks odd, especially to people outside GOC? 
NB GO:0031982 vesicle is used to annotate 219 proteins (experimental evidence only, exact match - not including annotations using child terms) whereas,
GO:0031982 vesicle is used to annotate only 30 proteins (same criteria)

**Comment by Pauldenny** [comment]
**Thanks for noticing my mistake, Ruth; what I *meant* was:**
What would be implications of merge? - it looks odd, especially to people outside GOC? 
NB GO:0031982 vesicle is used to annotate 219 proteins (experimental evidence only, exact match - not including annotations using child terms) whereas,
GO:0031988 membrane-bounded vesicle is used to annotate only 30 proteins (same criteria)

**Comment by mah11** [comment]
In general, terms get merged when we realize they've meant the same thing all along (it's happened hundreds of times over GO's history). The GO editors make an informed decision which name and ID to keep as primary, and ensure that the other name, text def, synonyms, etc. are accounted for. All annotations end up attached to the single primary ID that results. The second ID becomes a secondary ID (aka alt_id) for the primary ID.

p.s. you can edit comments in GitHub to correct errors (and if you want, you can include a note saying what you changed, so as not to seem too sneaky ;) )

**Comment by paolaroncaglia** [comment]
Hi all,

I'll take this - as Midori guessed correctly, it's due to an incomplete tidying up. It's on my to-do list, see the very end of this ticket: https://github.com/geneontology/go-ontology/issues/11504

**Comment by paolaroncaglia** [comment]
Hi @Pauldenny , @ukemi and @mah11 ,
All done now - cleaned up the 'vesicle' branch. All vesicles have membranes, and there are no more 'membrane-bounded vesicle' terms. Thanks,
Paola
