### ISSUE TITLE
GO:0032116 SMC loading complex name change

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12609]
could we tweak this slightly
rename to "cohesin loading complex" currently narrow synonym
make "SMC loading complex" a broad synonym (can be made a parent if there are other SMC loading complexes)

add 
Mis4-Ssl3 cohesin loading complex (fission yeast name , exact)
Scc2-Scc4 cohesin loading complex ( budding yeast name , exact)

refine def
A protein complex (conserved from yeast to human) required for the loading of a  cohesin, complex onto DNA. 
(all experimental annotations so far are to this term)

Refs are the same. This will allow us to retrieve the subunits of this specific conserved complex from any organism.

**Comment by ValWood** [comment]
Additional ref
PMID:24291789
Title	Biochemical reconstitution of topological DNA binding by the cohesin ring.

Relationships
has DNA binding activity PMID:24291789
part_of GO:0071921 cohesin loading 

(@ukemi I think we could have a specific MF term for this complex to describe its role in loading, but this is one of the 'activities' I am stuck on...
https://curation.pombase.org/pombe/curs/74dade3ace393390/ro/)

**Comment by ValWood** [comment]
I just remembered there is another conserved chromatin loading complex Wpl/Pds5

So as above  names would be
term name Scc2-Scc4 cohesin loading complex ( budding yeast name , exact, probably most used )
synonym Mis4-Ssl3 cohesin loading complex ( fission yeast name , exact)

and 
NTR Wpl/Pds5 cohesin loading complex PMID:26687354

**Comment by tberardini** [comment]
For my sanity check, shouldn't the organism-specific complex names be 'narrow' synonyms instead of 'exact'?

**Comment by ValWood** [comment]
> For my sanity check, shouldn't the organism-specific complex names be 'narrow' synonyms instead of 'exact'?
I'm not sure.They aren't narrow in the sense that they are an *exact* name for that definition, (even if they are generally used for one organism). However, these names are a bit fluid, and I  think both are used sometimes in other species too.....

For instance you see things like this:
human Scc2-Scc4 loader complex
http://www.nature.com/nature/journal/v505/n7483/abs/nature12867.html#corres-auth

**Comment by tberardini** [comment]
Val, please clarify:

EITHER:

- [ ] rename GO:0032116 SMC loading complex as cohesin loading complex

- [ ] add synonyms
Mis4-Ssl3 cohesin loading complex (fission yeast name , exact)
Scc2-Scc4 cohesin loading complex ( budding yeast name , exact)
SMC loading complex (broad)

- [ ] refine definition of GO:0032116

- [ ] add relationships for GO:0032116,
has DNA binding activity PMID:24291789
part_of GO:0071921 cohesin loading 

- [ ] add reference for GO:0032116, PMID:24291789

- [ ] add new term, 'Wpl/Pds5 cohesin loading complex' with reference PMID:26687354 

OR

- [ ] keep GO:0032116 SMC loading complex as is (?), add relationships?

- [ ] add a new term, Scc2-Scc4 cohesin loading complex  with synonym Mis4-Ssl3 cohesin loading complex as child of GO:0032116, with reference PMID:24291789 

- [ ] add new term, 'Wpl/Pds5 cohesin loading complex' as child of GO:0032116 with reference PMID:26687354 

If the latter, please provide definitions for both.  

OR maybe something else?

**Comment by ValWood** [comment]
I love - [ ] feature ;)

I was thinking about this some more after I posted. 
Let's keep the SMC complex grouping term. I'm not sure how useful this will be in the long term because the cohesin loader  Scc2-Scc4 cohesin loading complex 
is also suspected to be a loader for other complexes in addition to cohesin/SMC complexes ( based on phenotypes), so having the individual complex terms for these will be quite critical for modelling.

Def for 'Scc2-Scc4 cohesin loading complex' 
A eukaryotically conserved heterodimeric protein complex (comprising adherin and the chromatid cohesion factor MAU2/Scc4/Ssl3) required for the loading of a cohesin, complex onto DNA. 

Def for 'Wpl1/Pds5 cohesin loading/unloading complex'
A eukaryotically conserved heterodimeric protein complex  (comprising Wings apart-like protein and the Pds5 Armadillo repeat cohesin associated protein) involved in  the loading and unloading of a cohesin complex onto DNA.

**Comment by tberardini** [comment]
Added relationships to GO:0032116 SMC loading complex
+relationship: capable_of GO:0003677 ! DNA binding
+relationship: capable_of_part_of GO:0071921 ! cohesin loading

Added terms:
 
+id: GO:0090694
+name: Scc2-Scc4 cohesin loading complex
+namespace: cellular_component
+def: "A eukaryotically conserved heterodimeric protein complex (comprising adherin and the chromatid cohesion factor MAU2/Scc4/Ssl3) required for the loading of a cohesin, complex onto DNA." [GOC:vw, PMID:24291789]
+synonym: "Mis4-Ssl3 cohesin loading complex" EXACT [GOC:vw]
+is_a: GO:0032116 ! SMC loading complex

+id: GO:0090695
+name: Wpl/Pds5 cohesin loading complex
+namespace: cellular_component
+def: "A eukaryotically conserved heterodimeric protein complex (comprising Wings apart-like protein and the Pds5 Armadillo repeat cohesin associated protein) involved in the loading and unloading of a cohesin complex onto DNA." [GOC:vw, PMID:26687354]
+is_a: GO:0032116 ! SMC loading complex
