### ISSUE TITLE
GOC reference for PomBase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12602]
For our metrics Could we have a GOC:PomBase reference to add to PomBase curator activities for our metrics? I don't know how to arrange this..... Also could this ref be added retrospectively 
to PomBase curator terms from 2010?

**Comment by tberardini** [comment]
We could possibly look for any terms that have GOC:vw, GOC:mah (since when?) or GOC:al in the dbxrefs and then add in GOC:PomBase.  Will need to create a new entry in the GO dbxrefs file, here: https://github.com/geneontology/go-site/blob/master/metadata/users.yaml.  

This should be done programmatically.  @cmungall - ideas?

**Comment by mcourtot** [comment]
I created an entry in the users.yam:
  uri: 'GOC:PomBase'
  xref: 'GOC:PomBase'
  nickname: 'dbxref created to allow easy counting of terms added by pomBase curators'
  organization: 'PomBase'

Not all terms have a creation date, so I'm not sure it would be feasible to restrict by date. Suggestions?

**Comment by ValWood** [comment]
Ah thanks for this. I guess a good start would be anything which does have a date post 2010, and take it from there?
 Are the ones without dates older, or are they a mixture (I guess you can't really tell).
We might also be able to do some by ID range once we know. It isn't urgent ....we don't have any funding applications pending for a while !

**Comment by mcourtot** [comment]
Can you please remind us to use the new GOC:PomBase when requesting terms?

@cmungall: any idea how to proceed for the bulk update? I guess first step would be if def has ref GOC:vw, may or al and creation_date > 2010, then add xref GOC:PomBase. I'd probably try and use Brain, but you may have something ready to go?

**Comment by pgaudet** [comment]
@ValWood Can we close this ? 
(I dont think we much used 'GOC:PomBase' - if you want these to be added when you request new terms you should include it in the term request. )

Thanks, Pascale

**Comment by ValWood** [comment]
OK!
