### ISSUE TITLE
Obsolete GO:0075301 cell differentiation involved in spore germination

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12606]
Please obsolete this term. 

Definition: The process in which a relatively unspecialized cell acquires specialized features of a specific cell type occurring during spore germination, the physiological and developmental changes that occur in a spore following release from dormancy up to the earliest signs of growth.

A spore is a "specialized"  If changes occur, they are not any type of differentiation. Any change from the dormant or resting state is activation toward a non-differentiated state. I don't think there are any annotations to this, thank goodness.

**Comment by tberardini** [comment]
Obsoletion email sent:

**Comment by tberardini** [comment]
term made obsolete
