### ISSUE TITLE
NTR component term: heteroreceptor complex

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12610]
PMID:24157794
describes allosteric interactions between two different receptor homodimers - it's best explained by this figure:
![image](https://cloud.githubusercontent.com/assets/12345463/17898378/77c7a688-694f-11e6-855d-94da30b584c9.png)
So the authors show evidence that FGFR1 (Fibroblast growth factor receptor 1) homodimers interact with HT1RA (5-hydroxytryptamine receptor 1A) homodimers in the membrane. Furthermore, the presence of the ligands, natural (FGF2) or drug-based (CHEBI:73364 - 8-OH-DPAT) alter the binding affinity between the receptors depending on whether they are both present. So, I'd like the term: 
heteroreceptor complex
This phrase is used in about 20 PMIDs, for other types of receptor pairs, e.g. erythropoietin/CD131 heteroreceptor complex, EphA4 / fibroblast growth factor receptor 1, etc, so would be re-used many times. 
Parent would probably be
GO:0043234 protein complex
Thanks!
GOC:pad
GOC:PARL

**Comment by tberardini** [comment]
Please suggest a definition.  Thanks.

**Comment by Pauldenny** [comment]
Sorry, Tanya!
Looking again, I this should be a child of
GO:0043235 receptor complex
and the new term might be:
Name: heteroreceptor complex
definition might be:
A receptor complex that consists of multiple protein complexes that undergo combination with two or more types of hormones, neurotransmitters, drugs or intracellular messengers to initiate a change in cell function.

**Comment by tberardini** [comment]
Can we tweak to make clear the 'hetero' nature?

"A receptor complex that consists of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger.  The formation of the higher level complex initiates a change in cell function."

Would that be accurate?

**Comment by Pauldenny** [comment]
Yes, I think so, based on PMID: 22035699. Thanks

**Comment by tberardini** [comment]
Added:

+id: GO:0090690
+name: heteroreceptor complex
+namespace: cellular_component
+def: "A receptor complex that consists of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger. The formation of the higher level complex initiates a change in cell function." [GOC:pad, GOC:PARL, PMID:22035699, PMID:24157794]
+is_a: GO:0043235 ! receptor complex

**Comment by dosumis** [comment]
Perhaps rather than having a complex, this could be better represented as a process for interaction or binding between the two receptors? This could be extended using the 'involved in' pattern where there is some effect on signaling. 

receptor complex heterodimerization?
receptor complex heterodimerization involved in regulation of signal transduction?

I wouldn't want to commit to adding subclasses for every different combination of receptors anyone finds, but adding the complex term seems to set a precedent for that.  It's clearly important to record the complexes involved in the interaction, but that could be done in extensions with has_input.

**Comment by Pauldenny** [comment]
I think those sound like good solutions and using AE has_input for specific complexes also good. Thanks, David.

**Comment by tberardini** [comment]
What is the next step, @dosumis?  Obsoletion of the original terms is clear but are we adding new terms, 'receptor complex heterodimerization' and 'receptor complex heterodimerization involved in regulation of signal transduction'?

**Comment by dosumis** [comment]
> On Oct 3, 2016, at 5:03 PM, Tanya Berardini <notifications@github.com> wrote:
> 
> What is the next step, @dosumis <https://github.com/dosumis>? Obsoletion of the original terms is clear but are we adding new terms, 'receptor complex heterodimerization' and 'receptor complex heterodimerization involved in regulation of signal transduction'?
> 
> 

That’s my suggestion.  We might do better with the naming though.  

Would it be odd to also add a note about extensions?

**Comment by tberardini** [comment]
How about this?

protein binding
--[i] protein complex binding
----[i] **heterocomplex receptor formation** (GO:new1)
------[i]  _heterocomplex receptor formation involved in regulation of signal transduction_ (GO:new2, add through TG)

regulation of signal transduction
--[p] _heterocomplex receptor formation involved in regulation of signal transduction_ (GO:new2, add through TG)


**heterocomplex receptor formation**: The aggregation, arrangement and bonding together of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger to form a higher level receptor complex. The formation of the higher level complex initiates a change in cell function.

**Comment by Pauldenny** [comment]
Hi @tberardini @dosumis I'd be happy with these - but what is our next step? Can you create these Tanya? Or do I need to do this using termgenie? If so, how?

**Comment by tberardini** [comment]
@dosumis : are you ok with my proposal?  If yes, I'll go ahead and make the edits and proceed with the obsoletion.

**Comment by tberardini** [comment]
LEGO suggestion: 'complex 1' annotate to 'receptor binding' has_input 'complex 2' with annotation extension regulates 'appropriate signal transduction'

@dosumis  and @Pauldenny to look at this next Tuesday when DavidOS is at UCL.

**Comment by RLovering** [comment]
How does this fit in with the signaling annotation guidance? The annotation guidance for annotating ligands is that they are 'PART_OF' the signaling pathway, not regulating it. And certainly I would expect a receptor to be part of the signaling pathway not regulating it.

see http://geneontology.org/page/go-annotation-conventions#general 

**Stimulus**
regulation of signaling pathway
**Ligand**
signaling pathway
regulation of other cellular processes
**Receptor**
signaling pathway
regulation of other cellular processes

Ruth

**Comment by dosumis** [comment]
Hi Ruth - This is an not ligand-receptor binding, but interaction between receptors in *different* pathways => regulation.  Looking through examples, this mostly seems to regulate ligand/receptor affinity e.g. see http://journal.frontiersin.org/article/10.3389/fendo.2014.00071/full

**Comment by RLovering** [comment]
Thanks David

sorry didn't have time to read it properly

Best

Ruth

**Comment by dosumis** [comment]
To annotate this:

> FGFR1 (Fibroblast growth factor receptor 1) homodimers interact with HT1RA (5-hydroxytryptamine receptor 1A) homodimers in the membrane. Furthermore, the presence of the ligands, natural (FGF2) or drug-based (CHEBI:73364 - 8-OH-DPAT) alter the binding affinity between the receptors depending on whether they are both present.

NTR: receptor-receptor interaction
synonym:  hetero-receptor complex formation
subClassOf: receptor binding

Annotation should (probably) be to complexes or use contributes_to - as it is not clear what the contribution of individual subunits is to binding. 

Intact: '5HTR1 complex': enables receptor-receptor interaction (has_input  'INTACT:FGF-R1 receptor complex)

Intact: '5HTR1 complex' enables serotonin binding (directly_positively_regulates receptor-receptor interaction)

+ reciprocals with FGF_R1 complex as subject.

This is slightly unsatisfactory as we can't link the binding of ligand to the regulation of heteroreceptor complex formation.  However, attempting to do so would make for overly complicated GO terms with confusing extensions.  Recording this information is straightforward in LEGO:

http://noctua.berkeleybop.org/editor/graph/gomodel:580fe05a00000125

**Comment by tberardini** [comment]
I'm going to obsolete the term that was originally created, 'heteroreceptor complex'.  @dosumis - will you add the new term if @Pauldenny agrees to this course of action?

**Comment by tberardini** [comment]
[Term]
 id: GO:0090690
-name: heteroreceptor complex
+name: obsolete heteroreceptor complex
 namespace: cellular_component
-def: "A receptor complex that consists of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger. The formation of the higher level complex initiates a change in cell function." [GOC:pad, GOC:PARL, PMID:22035699, PMID:24157794]
-is_a: GO:0043235 ! receptor complex
+def: "OBSOLETE. A receptor complex that consists of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger. The formation of the higher level complex initiates a change in cell function." [GOC:pad, GOC:PARL, PMID:22035699, PMID:24157794]
+comment: This term was obsoleted as it was created in error.
+is_obsolete: true
 created_by: tanyaberardini
 creation_date: 2016-08-24T09:47:15Z

**Comment by Pauldenny** [comment]
David and I talked about this today and I am very happy with his suggestions.
Paul


-

**Comment by tberardini** [comment]
Ok. Modifying my initial proposal (10/4) to limit to just one new term:

--[i] receptor binding
----[i] receptor-receptor interaction (GO: new1)

GO:new1:  receptor-receptor interaction
synonym: hetero-receptor complex formation
subClassOf: receptor binding

Definition: The aggregation, arrangement and bonding together of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger to form a higher level receptor complex. The formation of the higher level complex initiates a change in cell function.

**Comment by tberardini** [comment]
@Pauldenny, @dosumis : Unless there are objections, I will add this term on Wednesday.

**Comment by tberardini** [comment]
[Term]
+id: GO:0090722
+name:  receptor-receptor interaction
**+namespace: molecular_function**
+def: "The aggregation, arrangement and bonding together of two or more different receptor complexes that individually undergo combination with a hormone, neurotransmitter, drug or intracellular messenger to form a higher level receptor complex. The formation of the higher level complex initiates a change in cell function." [GOC:dox, GOC:pad, GOC:PARL, PMID:22035699, PMID:24157794]
+synonym: "hetero-receptor complex formation" EXACT []
+is_a: GO:0005102 ! receptor binding
+created_by: tanyaberardini
+creation_date: 2016-11-11T17:41:56Z
