### ISSUE TITLE
difference between GO:0000406 GO:0000403 DNA binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12615]
GO:0000406
Name	double-strand/single-strand DNA junction binding

Interacting selectively and non-covalently with a region of DNA that contains double-stranded DNA flanked by a region of single-stranded DNA. 
PMID:16781730

has only 2 EXP annotations, and sounds the same as
GO:0000403 
Y-form DNA binding
	Interacting selectively and non-covalently with segment of DNA shaped like a Y. This shape occurs when DNA contains a region of paired double-stranded DNA on one end and a region of unpaired DNA strands on the opposite end. 
PMID:16781730

**Comment by ValWood** [comment]
Looking at figure 2, these  are probably different types of Y-form?

**Comment by mah11** [comment]
I had nothing to do with either term historically, but from the definitions it looks like GO:0000406 is broader - Y-form DNA contains a ds/ss junction, but so do some of the other structures shown in the paper.

**Comment by tberardini** [comment]
Figure 4C from here: http://www.sciencedirect.com/science/article/pii/S0022283606006140 shows many different ds/ss structures, the Y-form being one of them.  The two terms were created by Eurie based on this paper PMID:16781730 (link to full article above) so I think they are separate processes.
