### ISSUE TITLE
Relationship ‘results in maturation of’ may not be optimal for regeneration terms

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12618]
Hi @cmungall ,

The relationship ‘results in maturation of’ is currently used to define regeneration terms. 
Regeneration can occur via renewal, restoration, and/or growth. See https://github.com/geneontology/go-ontology/issues/12589. To me, ‘maturation’ doesn’t quite nail down this complexity. Wouldn’t it be less ambiguous if we re-labeled the relationship as (duh…) ‘results in regeneration of’?
The same relationship is currently used to define real cell and tissue maturation (e.g. seed maturation, hindbrain maturation, oocyte maturation). We probably want to differentiate those processes from the regeneration that occurs say after a spinal injury.

Thanks!

**Comment by pgaudet** [comment]
@ukemi What would be a better relation? 
The parent is 'results in developmental progression of' 
 definition

p results in the developmental progression of s iff p is a developmental process and s is an anatomical structure and p causes s to undergo a change in state at some point along its natural developmental cycle (this cycle starts with its formation, through the mature structure, and ends with its loss).


Would this be better ? 

Thanks, Pascale
