### ISSUE TITLE
sysonym for GO:1990501 exon-exon junction subcomplex mago-y14

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12617]
please add:
Exon junction subcomplex MAGOH-Y14 [exact]

Note, different spelling of mago(h) in non-insect spp. I first requested it for drome and failed to check what it's called in other spp.

Birgit

**Comment by tberardini** [comment]
+synonym: "exon junction subcomplex MAGOH-Y14" EXACT [GOC:bm]

**Comment by bmeldal** [comment]
Tanya,

small error, my GOC ID is bhm, I think BM is someone else.

Birgit

**Comment by tberardini** [comment]
Cleaned up.

**Comment by bmeldal** [comment]
Thanks, Tanya :)
