### ISSUE TITLE
Synonym request for GO:0090149 mitochondrial membrane fission

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12612]
Hello, 

I would like to request a synonym for 'GO:0090149 mitochondrial membrane fission' (a child of 'GO:0090148 membrane fission' and 'GO:0000266 mitochondrial fission').

The synonym would be 'mitochondrial membrane scission'.

This would then be analogous in nature to 'GO:0099050 vesicle scission', which is a child of 'GO:0090148 membrane fission'.

Thanks,
Barbara

@RLovering 
@Pauldenny 
@rebeccafoulger

**Comment by BarbaraCzub** [comment]
This is related to #12479.

**Comment by BarbaraCzub** [comment]
This is related to #12611 .

**Comment by tberardini** [comment]
Hi Barbara, 

Should there also be a synonym of membrane fission that is 'membrane scission'?

Tanya

**Comment by BarbaraCzub** [comment]
Hi Tanya,

Yes, this is precisely how I understand these terms. I have just had a chat with @dosumis about this and he also agreed with this logic.

Barbara

**Comment by tberardini** [comment]
Synonyms added as requested.
