### ISSUE TITLE
NTR: mitochondrial membrane scission site

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12611]
Hello,

I would like to request a new term:  mitochondrial membrane scission site
re: PMID:26618722, Figure 6.

Intended annotation:
DNM1L  IDA  mitochondrial membrane scission site

This term would become a child of: GO:0044455 mitochondrial membrane part

Thanks,
Barbara

Thanks,
Barbara

DbxREFs: GOC:PARL, GOC:bc

cc: @RLovering 
cc: @rebeccafoulger 
cc: @Pauldenny

**Comment by BarbaraCzub** [comment]
This is related to #12612.

**Comment by tberardini** [comment]
Definition please.  Thanks.

**Comment by BarbaraCzub** [comment]
Hi @tberardini 

Here is a possible definition. Please edit as required:

"A site on the mitochondrial membrane where the separation of a single continuous mitochondrial membrane into two membranes occurs as a final step in mitochondrial fission."

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
It crossed my mind to perhaps mention the site where budding of mitochondrion-derived vesicles (MDVs) would occur, but I don't know whether any biological data has been published that would show where on the mitochondrial membrane these would bud off. Whereas during mitochondrial fission the site of the scission would be very much dependent on how the genetic material and other components of the organelle have been divided and on polarisaition, etc. So I suppose that if in the future anyone requests a term 'site of budding of MDVs' it would fall under the process of 'mitochondrial membrane fission/scission', but it would be a different site to 'mitochondrial membrane scission site' as I defined it above.

**Comment by tberardini** [comment]
Created with tiny tweak in def:

+id: GO:0090692
+name: mitochondrial membrane scission site
+namespace: cellular_component
+def: "The site on the mitochondrial membrane where the separation of a single continuous mitochondrial membrane into two membranes occurs as a final step in mitochondrial fission." [GOC:bc, GOC:PARL, PMID:26618722]
+is_a: GO:0044455 ! mitochondrial membrane part
