### ISSUE TITLE
NTR: population of unicellular-organism process terms

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12614]
From a discussion on the subject of removing "multicellular" fungi from the class of "multicellular organisms" as used for metazoans, the term "population of unicellular organisms" is closer to the biology of multicellular fungal species.
https://github.com/geneontology/paint/issues/25#issuecomment-239810609

"Population of unicellular organisms" has been used directly in term names but is a lot of extra words to add to each term.  I am proposing the following terms for consideration, comment, adjustment, etc

1) single-population of unicellular organism process
2) multi-population of unicellular organism process (such as in mixed-species biofilms)
3) single-population of unicellular organism reproductive process
4) multi-population of unicellular organism reproductive process
5) single-population of unicellular organism developmental process
6) multi-population of unicellular organism developmental process

Note that reproduction by budding occurs at the single cell level under "GO:0032505 reproduction of a single-celled organism." Sexual or asexual sporulation always requires a population. Asexual sporulation requires a population of a single mating type as in 3 and 5. Sexual sporulation requires two mating types so 4 and 6 above address those situations.

**Comment by tberardini** [comment]
Will take to GO eds meeting tomorrow morning for wider discussion.

**Comment by paolaroncaglia** [comment]
@dosumis and I think we may want to include Petra and Jim in this discussion

**Comment by ValWood** [comment]
Would this result in any yeast reproduction being described as a 'population level process'?
I'm not sure that we would want that?  @mah11  @Antonialock

**Comment by mah11** [comment]
It looks like vegetative-phase cell division would be handled the same way as budding, described above - occurs at the single cell level under "GO:0032505 reproduction of a single-celled organism." - i.e. no problem.

For sporulation, the "requires a population" feels a little odd because a single diploid (budding or fission) yeast cell can sporulate. But to get that diploid there must have been a population of two at some point, so maybe that's what it refers to.

**Comment by ValWood** [comment]
I would just call any reproduction a
 GO:0051703 intraspecies interaction between organisms

Otherwise, any species mating is a population level process.

I'm  always suspicious of  the "population level " description  in  GO ...It seems out of scope, and it isn't clear to me why we need it to describe the processes.  Couldn't we just describe  these using the species interaction terms? (A comment could be added to the things like flocculation, which are  *observed* at the population level, but at the end of the day, we are describing cell level processes... expression of a flocculin in a single cell can result in the flocculation of a population).

**Comment by ukemi** [comment]
Worms can be self-fertilizing hermaphrodites.

**Comment by dianeoinglis** [comment]
| Would this result in any yeast reproduction being described as a 'population level process'?
I'm not sure that we would want that? @mah11 @Antonialock |
I can't think of any case. Pseudohyphal growth can result in a population of attached cells but does not require them for the process.

Yeast are world's apart from truly filamentous species. Aspergillus will never make conidiophores unless there is both a sufficient population to form a robust mycelium and the mycelium must grow for a while to become developmentally competent before any cells of a conidiphore begin to develop. For filamentous and some dimorphic fungi (non-yeast), a population of cells is absolutely required for asexual and sexual sporulation. The yeast-type mating process represents a minority among fungal species. Perhaps yeast mating as single cells and filamentous-type reproduction can be distinguished the way "reproduction by budding" and "filamentous growth" describe very different modes of reproductionj

**Comment by ValWood** [comment]
Even though filamentous growth  *requires* a population to *occur* I still think of it essentially as a single organism process in that it is happening to a single organism.
(I.e one organism is growing in a filamentous  mode *within* a population).

Even though it might not *occur* in some species unless a certain population level is achieved, it is still essentially an interaction between 2 members of the same species. To me there is something orthogonal about the population level.... required for these processes to happen, and how many species perform the actual process.

I'm just thinking that every aspect of reproduction  will need to be separately replicated in a different branch is some need this high level "population level" parentage.  I can't quite visualise the knock on effects of this  on existing terms.....

**Comment by tberardini** [comment]
After GO editors' meeting, we need more input from experts in the fungal and microbial community.  @pfey03 and @jimhu-tamu, can you please catch up with this discussion?  We would like to discuss whether these higher level terms are indeed necessary and useful for grouping. We do want to address the concern that (some) fungal processes are improperly classified under 'multicellular organismal process' right now and want to do that in the best way.

**Comment by ValWood** [comment]
I now understand what you mean about the population level process (thinking about dicty). I guess the mycelium type 'mating' is analogous to this? In which case, I guess the terms you will use  will be completely different so  it wont be such an issue. I guess we just add the taxon restriction for yeast and then we will spot any terms which need  taxon specific instances.

**Comment by pfey03** [comment]
Hard to wrap my head around with all the yeast terminology.  First, are the suggested terms additional, new terms? 
In Dicty, reproduction and development are strictly devided. Noticed some problems there in the ontology and will add a new issue. 

What we call 'vegetative growth' in Dicty, we currently annotate to 'asexual reproduction' in GO, a direct child of reproduction that bypasses currently all the organismal processes and goes directly to BP root. How does 'asexual reproduction' compare to 'single-population of unicellular organism reproductive process'?  The latter is somewhat more specific, but is it clearer?

These seem the long GO terms that are much harder to understand on a first read. For our users it's already unusual to see Dicty 'vegetative growth' annotated as asexual reproduction', but it's at least easy to understand they are fine with that. 

I do think we need some better structure on top to find clear lines for taxon restrictions. I have already problems with some taxon restrictions, and dividing what Diane called 'facultative multicellularity' from obligate multicellularity (to reproduce) seems necessary from the top down. In Dicty multicellularity is purely a matter for survival, in that sense not facultative, but a very different purpose. During the early stages of development, up to the slug stage, cells can become single again when disrupted and food is provided. Once stalk differentiates, they cannot go back.

**Comment by tberardini** [comment]
Splitting @pfey03's questions out:

1. First, are the suggested terms additional, new terms? 

Yes.

2.  How does 'asexual reproduction' compare to 'single-population of unicellular organism reproductive process'? The latter is somewhat more specific, but is it clearer?

Perhaps @dianeoinglis, you are thinking that _single-population of unicellular organism reproductive process_ and  _multi-population of unicellular organism reproductive process_ will be children of 'asexual reproduction?'

-----------
Stepping back a lot, it sounds to me that this issue is about dividing biological processes at the organism level into

1. unicellular organisms
2. populations of unicellular organisms (could be of populations of two or more species)
3. 'true' multicellular organisms

There's the issue of what to call the processes for (2) so that this is easily understood.  There's also the issue of reviewing everything that's under the current multicellular organism process terms to make sure that appropriate parentage is established.  Have you given any thought as to whether these top level processes should be disjoint?  If yes, that restriction can help in the editing/rehousing process.

**Comment by dosumis** [comment]
> Have you given any thought as to whether these top level processes should be disjoint? 

I would say not. I suspect this will force us to separate out processes that share mechanisms.

**Comment by pfey03** [comment]
@tberardini
> 
1. unicellular organisms
2. populations of unicellular organisms (could be of populations of two or more species)
3. 'true' multicellular organisms

Dicty would be all 3 in different stages of life.
http://dictybase.org/Multimedia/DdLifeCycles/index.html

**Comment by dianeoinglis** [comment]
Filamentous growth does not require a population to occur. It results in a population of attached cells and occurs more rapidly at a higher concentration of cells but a single yeast-form cell can convert from yeast-phase to filamentous phase regardless of cell number.

Sexual reproduction varies between species. Yeast can fuse with a mating partner without alarge population. Fungi that mate in the filamentous phase must have sufficient cell numbers and must mature to become competent for sporulation. The filamentous require a population to form a mycelium that is capable of sporophore development and sporulation.

Regarding the 3 groups listed above, the tricky group is the dimorphic species that can grow as unicellular but are considered multicellular when they convert to the filamentous form. Typically mating occurs in the filamentous form except for Candida albicans that converts from growth as white cells go growth as a mating competent opaque cell.

**Comment by tberardini** [comment]
I'm not sure where to go with this issue now.  There are pros and cons to creating the new terms and moving the children terms around.  Perhaps this is something to tackle in person at the GO meeting in LA in November?

**Comment by tberardini** [comment]
I just noticed #12212 = Proposed obsoletion: single-organism process.  I'm mentioning it here in case there are effects that obsoletion of that term (and children)  might have on this one.

**Comment by dianeoinglis** [comment]
The species that require a significant population density before they are capable of reproduction are few. Microbes are the only organisms I can think of at the moment. Specific Intra-organismal signalling processes are involved in regulating the requirement. 

These terms are reasonable. I like them.
unicellular organisms
populations of unicellular organisms (could be of populations of two or more species)
'true' multicellular organisms

**Comment by dianeoinglis** [comment]
I think the use of "fungal-type process x" is needed and will subdivide children without much diruption in current positions in the ontology. 

The  term "single-organism" can easily be interpreted as one individual organism and that is not whta the term means, correct? Terms with more than one common or reasonable interpretation allow them to be applied differently. The obsoletion of "single-organism process" gets my vote.

Fungal-type morphogenesis" and "fungal-type cell morphogenesis" are topics for another ticket.

**Comment by tberardini** [comment]
@dianeoinglis, @pfey03, @ValWood : Would any/all of you be able to join us at the next GO ontology editors call next Thursday, 9/22, at 8:30 am Pacific to discuss the issue? The live discussion will hopefully spur action on this issue along faster than typing in multiple time zones alone.  Thanks.

**Comment by ValWood** [comment]
I will probably around although I doubt I will be much use, other than to say don't let any  pombe terms/annotations have this parentage (or let us know so that we can discuss)

**Comment by dianeoinglis** [comment]
I should be able join you Thursday morning.

**Comment by paolaroncaglia** [comment]
@dianeoinglis , could you please email me with your address, so I can send you the invite for the GO editors call? Thanks.

**Comment by paolaroncaglia** [comment]
@dianeoinglis , I sent a GoToMeeting invite to a Gmail address of yours that I retrieved on LinkedIn, I hope you receive it!

**Comment by tberardini** [comment]
After GO editors meeting and discussion (thanks @pfey03 and @dianeoinglis for joining us), we decided that we would

1. not add the new terms as suggested in the initial ticket comment - avoid another layer of complexity and maintenance
2. address individual problems with terms that are currently under a 'multicellular organism x' process parent by reviewing and editing parentage and/or editing the primary term name.  

@dianeoinglis and @pfey03 : please open individual GH tickets (if there aren't ones already) for each term/set of closely related terms in (2)?  This will make discussions more focused.  I will close this ticket.
