### ISSUE TITLE
Term clarification: mycelium development

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12613]
GO:0043581 mycelium development
PMID:12832397
Definition: The process whose specific outcome is the progression of the mycelium over time, from its formation to the mature structure. A mycelium consists of a mass of branching, thread-like hyphae. 

This term and definition do not make sense. It's not clear what "mature structure" results from "the progression of the mycelium over time." The way this definition is worded, it better describes a mycelium that acquires "developmental competence" for sporulation than the process the reference describes which is "aerial mycelium formation,""aerial mycelium development" or "aerial hyphal growth." A filamentous fungus that cannot make aerial mycelia still grows as a mycelium but cannot overcome surface tension to extend its hyphae vertically and has a noticeably different colony appearance

PAMGO has made a lot of primary annotations to this term and likely just knows what it means when applied to the strictly filamentous fungal plant pathogens they annotate. If the term is inferred across other fungal species though, the term and its definition become confusing. I can contact PAMGO and clarify how they use the term and if the definition could be made more clear/specific across the broad range of fungal species. Is Ralph Dean the main contact at PAMGO?

Diane

**Comment by tberardini** [comment]
Hi Diane,

It looks like the 'standard' x development definition was applied when creating this term.  We should certainly improve the definition or change the primary term name to better reflect its intended use. Yes, please contact PAMGO for clarification.  I don't know who the main contact at PAMGO - Candace Collmer and Trudy Torto-Alalibo were the main persons working on this project.  Perhaps try them first.

ccollmer@wells.edu
trudy@vbi.vt.edu

**Comment by dianeoinglis** [comment]
Candace responded that she is retired and the email to Trudy failed. Candace suggested Brett Tyler be contacted and our PAMGO info updated. I just got an out of town until 8/26 autoresponse from Brett's email address. 
Brett.Tyler@oregonstate.edu.

**Comment by tberardini** [comment]
Time to follow up with Brett?

**Comment by dianeoinglis** [comment]
I emailed him and received out-of-office reply. I emailed him again about 2 days after the return date. I will email again shortly and include a cc to another contact mentioned in the o-o-o reply.

**Comment by tberardini** [comment]
Thanks for the update.

**Comment by dianeoinglis** [comment]
While I am waiting for a response from Brett Tyler or someone with PAMGO, I am going to request the specific term "aerial mycelium formation" and let them know that this term has been created and that I would like to request the ambiguous term "mycelium development" be obsoleted because it has another meaning in other fungal species. I will create a new ticket the NTR and re-send the email.

**Comment by tberardini** [comment]
Good idea, Diane!  Is there another term (or maybe more than one additional term) that could be requested at the same time as 'aerial mycelium formation' that would cover other instances where 'mycelium development' has been used for annotation?  If you can think of such a term or terms, then that will make reannotation easier for other curator.  If you can't think of alternative terms, we'll wait for feedback to come back on the 'mycelium development' obsoletion proposal. 

Thank you.

**Comment by dianeoinglis** [comment]
See NTR #12659

**Comment by dianeoinglis** [comment]
An additional comment on "aerial mycelium formation" is that this is a pre-sporulation process and is also referred to as a "fertile mycelium." The term should probably have "asexual reproduction" as a parent. This process is not exclusive to fungi. The bacterium Streptomyces coelicolor and Streptomyces africanus sp.also do this before sporulating. The species that form an aerial mycelium develop conidiophores at the ends of the aerial hyphae. 

The other type of "mycelium development" is also a pre-sporulation process but is called "developmental competence" in other fungi. This means that upon germination, an immuture mycelium formas and must grow for a period of time in order to become suffiently mature before the developmental process conidiophore formation and conidia develpment can occur. With "developmental competence" ther is no obvious change in the direction of growth. I think the term "developmental competence" is appropriate for the types of fungi that do not make aerial hyphae before they sporulate. The fungi that acquire developmental competence would grow continuously as vegetative hyphae/mycelia.

"Aerial mycelium development" should also get the synonym "aerial hyphal growth."

**Comment by dianeoinglis** [comment]
See  #12660 for NTR: "mycelium reproductive competence"

**Comment by dianeoinglis** [comment]
Martin Urban from Phi-Base asks:" "Do you know if there is a way to obtain a list of all PAMGO terms that were already obsoleted from GO?"

**Comment by mah11** [comment]
As I recall, everyone was pretty conscientious about crediting the PAMGO term definitions to "GOC:pamgo_curators", so it should work to load GO into OBO-Edit and query for terms that have "any text field contains 'pamgo'" AND "has 'is_obsolete'".

**Comment by tberardini** [comment]
There are 117 terms that I get when I follow Midori's instructions.  

GO:0033665	obsolete regulation of growth or development of symbiont in host
GO:0033666	obsolete positive regulation of growth or development of symbiont in host
GO:0033667	obsolete negative regulation of growth or development of symbiont in host
GO:0052108	obsolete growth or development of symbiont during interaction with host
GO:0052113	obsolete adaptation to host osmotic environment
GO:0052114	obsolete adaptation to host pH environment
GO:0052171	obsolete growth or development during symbiotic interaction
GO:0052184	obsolete modulation by organism of symbiont hormone or growth regulator levels
GO:0052326	obsolete interaction with symbiont via protein secreted by type IV secretion system
GO:0052327	obsolete interaction with symbiont via protein secreted by type II secretion system
GO:0052328	obsolete interaction with symbiont via protein secreted by type III secretion system
GO:0052343	obsolete positive regulation by organism of symbiont phytoalexin production
GO:0052346	obsolete positive regulation by organism of defense-related symbiont nitric oxide production
GO:0052349	obsolete positive regulation by organism of defense-related symbiont reactive oxygen species production
GO:0052350	obsolete induction by organism of induced systemic resistance in symbiont
GO:0052351	obsolete induction by organism of systemic acquired resistance in symbiont
GO:0052375	obsolete evasion or tolerance by organism of symbiont-produced nitric oxide
GO:0052377	obsolete evasion or tolerance by organism of symbiont-produced phytoalexins
GO:0052383	obsolete induction by organism of symbiont innate immunity
GO:0052384	obsolete evasion or tolerance by organism of symbiont-produced reactive oxygen species
GO:0052387	obsolete induction by organism of symbiont apoptosis
GO:0052392	obsolete induction by organism of defense-related symbiont calcium ion flux
GO:0052394	obsolete induction by organism of defense-related symbiont cell wall thickening
GO:0052395	obsolete induction by organism of defense-related symbiont nitric oxide production
GO:0052396	obsolete induction by organism of symbiont non-apoptotic programmed cell death
GO:0052398	obsolete induction by organism of symbiont phytoalexin production
GO:0052399	obsolete induction by organism of symbiont programmed cell death
GO:0052401	obsolete induction by organism of defense-related symbiont reactive oxygen species production
GO:0052402	obsolete induction by organism of symbiont resistance gene-dependent defense response
GO:0052424	obsolete modification by organism of symbiont morphology or physiology via protein secreted by type III secretion system
GO:0052425	obsolete modification by organism of symbiont morphology or physiology via protein secreted by type II secretion system
GO:0052426	obsolete modification by organism of symbiont morphology or physiology via substance secreted by type IV secretion system
GO:0052429	obsolete modulation by organism of symbiont B-cell mediated immune response
GO:0052431	obsolete modulation by organism of symbiont T-cell mediated immune response
GO:0052432	obsolete modulation by organism of symbiont apoptosis
GO:0052434	obsolete modulation by organism of symbiont cell-mediated immune response
GO:0052436	obsolete modulation by organism of defense-related symbiont calcium-dependent protein kinase pathway
GO:0052437	obsolete modulation by organism of defense-related symbiont calcium ion flux
GO:0052438	obsolete modulation by organism of defense-related symbiont callose deposition
GO:0052439	obsolete modulation by organism of defense-related symbiont cell wall callose deposition
GO:0052440	obsolete modulation by organism of defense-related symbiont ethylene-mediated signal transduction pathway
GO:0052442	obsolete modulation by organism of defense-related symbiont jasmonic acid-mediated signal transduction pathway
GO:0052444	obsolete modulation by organism of defense-related symbiont salicylic acid-mediated signal transduction pathway
GO:0052446	obsolete modulation by organism of defense-related symbiont cell wall thickening
GO:0052447	obsolete modulation by organism of symbiont ethylene-mediated defense response
GO:0052448	obsolete modulation by organism of ethylene levels in symbiont
GO:0052450	obsolete modulation by organism of induced systemic resistance in symbiont
GO:0052451	obsolete modulation by organism of symbiont inflammatory response
GO:0052452	obsolete modulation by organism of symbiont innate immunity
GO:0052453	obsolete modulation by organism of symbiont intracellular transport
GO:0052454	obsolete modulation by organism of symbiont jasmonic acid-mediated defense response
GO:0052455	obsolete modulation by organism of jasmonic acid levels in symbiont
GO:0052457	obsolete modulation by organism of defense-related symbiont nitric oxide production
GO:0052458	obsolete modulation by organism of symbiont non-apoptotic programmed cell death
GO:0052461	obsolete modulation by organism of pathogen-associated molecular pattern-induced symbiont innate immunity
GO:0052463	obsolete modulation by organism of symbiont phytoalexin production
GO:0052464	obsolete modulation by organism of symbiont programmed cell death
GO:0052465	obsolete modulation by organism of defense-related symbiont reactive oxygen species production
GO:0052466	obsolete modulation by organism of symbiont resistance gene-dependent defense response
GO:0052467	obsolete modulation by organism of symbiont salicylic acid-mediated defense response
GO:0052468	obsolete modulation by organism of salicylic acid levels in symbiont
GO:0052471	obsolete modulation by organism of systemic acquired resistance in symbiont
GO:0052473	obsolete negative regulation by organism of symbiont B-cell mediated immune response
GO:0052474	obsolete negative regulation by organism of symbiont T-cell mediated immune response
GO:0052475	obsolete negative regulation by organism of symbiont cell-mediated immune response
GO:0052476	obsolete negative regulation by organism of defense-related symbiont MAP kinase-mediated signal transduction pathway
GO:0052477	obsolete negative regulation by organism of defense-related symbiont callose deposition
GO:0052478	obsolete negative regulation by organism of defense-related symbiont cell wall callose deposition
GO:0052479	obsolete negative regulation by organism of defense-related symbiont ethylene-mediated signal transduction pathway
GO:0052480	obsolete negative regulation by organism of defense-related symbiont jasmonic acid-mediated signal transduction pathway
GO:0052481	obsolete negative regulation by organism of defense-related symbiont salicylic acid-mediated signal transduction pathway
GO:0052484	obsolete negative regulation by organism of symbiont ethylene-mediated defense response
GO:0052485	obsolete negative regulation by organism of symbiont inflammatory response
GO:0052486	obsolete negative regulation by organism of symbiont innate immunity
GO:0052487	obsolete negative regulation by organism of symbiont jasmonic acid-mediated defense response
GO:0052488	obsolete negative regulation by organism of pathogen-associated molecular pattern-induced symbiont innate immunity
GO:0052491	obsolete negative regulation by organism of symbiont salicylic acid-mediated defense response
GO:0052498	obsolete pathogen-associated molecular pattern dependent induction by organism of symbiont innate immunity
GO:0052499	obsolete pathogen-associated molecular pattern dependent modulation by organism of symbiont innate immunity
GO:0052500	obsolete positive regulation by organism of symbiont apoptosis
GO:0052503	obsolete positive regulation by organism of defense-related symbiont calcium-dependent protein kinase pathway
GO:0052504	obsolete positive regulation by organism of defense-related symbiont callose deposition
GO:0052505	obsolete positive regulation by organism of defense-related symbiont cell wall callose deposition
GO:0052506	obsolete positive regulation by organism of defense-related symbiont ethylene-mediated signal transduction pathway
GO:0052507	obsolete positive regulation by organism of defense-related symbiont jasmonic acid-mediated signal transduction pathway
GO:0052508	obsolete positive regulation by organism of defense-related symbiont salicylic acid-mediated signal transduction pathway
GO:0052511	obsolete positive regulation by organism of symbiont ethylene-mediated defense response
GO:0052512	obsolete positive regulation by organism of hormone or growth regulator levels in symbiont
GO:0052514	obsolete positive regulation by organism of symbiont inflammatory response
GO:0052515	obsolete positive regulation by organism of symbiont innate immunity
GO:0052516	obsolete positive regulation by organism of symbiont jasmonic acid-mediated defense response
GO:0052517	obsolete positive regulation by organism of symbiont non-apoptotic programmed cell death
GO:0052523	obsolete positive regulation by organism of symbiont programmed cell death
GO:0052524	obsolete positive regulation by organism of symbiont salicylic acid-mediated defense response
GO:0052528	obsolete upregulation by organism of symbiont programmed cell death
GO:0052530	obsolete positive regulation by organism of symbiont resistance gene-dependent defense response
GO:0052531	obsolete positive regulation by organism of defense-related symbiont calcium ion flux
GO:0052534	obsolete positive regulation by organism of induced systemic resistance in symbiont
GO:0052536	obsolete positive regulation by organism of systemic acquired resistance in symbiont
GO:0052540	obsolete positive regulation by organism of defense-related symbiont cell wall thickening
GO:0052554	obsolete modulation by organism of symbiont immune response
GO:0052557	obsolete positive regulation by organism of symbiont immune response
GO:0052560	obsolete induction by organism of symbiont immune response
GO:0052563	obsolete negative regulation by organism of symbiont immune response
GO:0052568	obsolete response to symbiont phytoalexin production
GO:0052569	obsolete response to defense-related symbiont nitric oxide production
GO:0052570	obsolete response to defense-related symbiont reactive oxygen species production
GO:0052571	obsolete response to symbiont immune response
GO:0075013	obsolete growth or development of symbiont on or near host phyllosphere
GO:0075014	obsolete growth or development of symbiont on or near host rhizosphere
GO:0075065	obsolete growth or development of symbiont in host cell
GO:0075066	obsolete growth or development of symbiont in host organelle
GO:0075067	obsolete growth or development of symbiont in host intercellular space
GO:0075068	obsolete growth or development of symbiont in host vascular tissue
GO:0075305	obsolete modulation of growth or development of symbiont on or near host
GO:0075309	obsolete negative regulation of growth or development of symbiont on or near host surface
GO:0075337	obsolete positive regulation of growth or development of symbiont on or near host surface

**Comment by dianeoinglis** [comment]
Excellent. Thank you for the list. 

There does not appear to be any objection to obsoleting the term "mycelium development" and replacing this ambiguous term with more specific terms. Another mycelium development term is is needed as well. I'm working on it. I'll ask Martin Urban for his specific email address as a contact as he responded via contact@phi-base.org.

Hi Diane,
‘Mycelium development’ can also occur within substrate (i.e. within an agar plate or wood). Could you help with a term for this as well?
Martin

**Comment by tberardini** [comment]
@dianeoinglis : shall I send out an obsoletion alert for the current 'mycelium development' term then? 
http://amigo.geneontology.org/amigo/term/GO:0043581

**Comment by dianeoinglis** [comment]
Yes. The replacements are:

"aerial mycelium formation"
substrate mycelium formation"
"acquisition of mycelium reproductive competence"

**Comment by tberardini** [comment]
Summary:  Replacement terms in these issues: "aerial mycelium formation"  #12659,  "(acquisition of ) mycelium reproductive competence"#12660, I can't find the one for 'substrate mycelium formation'.  @paolaroncaglia , I will not send out the obsoletion email until the new terms have been added.

**Comment by fusarium** [comment]
@tberardini: Hello, could you please let me know how you filtered the 117 obsoleted PAMGO terms? Just starting to learn Obo-edit 2 software. Beneath my attempt in a screenshot. Search for 'all_text_fields contains "pamgo" ' only gives 992 matches using go-basic.

Many thanks.
martin.urban AT rothamsted.ac.uk

![image](https://cloud.githubusercontent.com/assets/2812591/19386535/af69a966-920c-11e6-92b2-68bcee3ac5f9.png)

**Comment by dosumis** [comment]
That's a link filter/search.  You need a term filter/search panel.

**Comment by paolaroncaglia** [comment]
Hi @tberardini ,
I added GO:0097736 'aerial mycelium formation' to start with.

**Comment by paolaroncaglia** [comment]
Hi again @tberardini ,
I also added GO:0097737 'acquisition of mycelium reproductive competence'. 
@dianeoinglis hasn't requested 'substrate mycelium formation' yet, but I think she will soon (see https://github.com/geneontology/go-ontology/issues/12659#issuecomment-253458272).

**Comment by paolaroncaglia** [comment]
Hi @tberardini ,
FYI, I just added GO:0097738 'substrate mycelium formation'.

**Comment by tberardini** [comment]
@dianeoinglis : were you able to sort out the filtering issue you had with OE?  As David OS said, you should be using the term filter, not the link filter.

**Comment by tberardini** [comment]
Consider terms for 'mycelium development:

GO:0097736,  aerial mycelium formation
GO:0097738, substrate mycelium formation
GO:0097737, acquisition of mycelium reproductive competence

I'll compose the obsoletion email and send it today.

**Comment by fusarium** [comment]
@tberadini and @dosumis : I can now confirm that there are 117 obsoleted PAMGO terms when using the term filter.
Many thanks!

![image](https://cloud.githubusercontent.com/assets/2812591/19485272/89e6485e-9552-11e6-98ce-561eafe41ccf.png)

**Comment by tberardini** [comment]
@fusarium : ok, great

**Comment by tberardini** [comment]
Sent today:

Dear all,

The proposal has been made to obsolete the following term:

 GO:0043581 mycelium development

The reason for obsoletion is that the term is ambiguous.  Three more clearly defined terms have been created that should be considered in its place:

GO:0097736, aerial mycelium formation
GO:0097737, acquisition of mycelium reproductive competence
GO:0097738, substrate mycelium formation

All details here:

https://github.com/geneontology/go-ontology/issues/12613

Experimental annotations to this term come from the PAMGO group and CGD.

We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete the term above on November 1, 2016.

*** Unless objections are received by November 1, 2016, we will assume
that you agree to this change. ***

On behalf of the GO ontology editors,

Tanya Berardini
TAIR Curator
www.arabidopsis.org

**Comment by tberardini** [comment]
Annotation counts (all): @fusarium and @dianeoinglis, these will need to be updated.

<img width="283" alt="screen shot 2016-10-18 at 1 03 19 pm" src="https://cloud.githubusercontent.com/assets/4998871/19494304/57326e48-9533-11e6-9584-890cadffac92.png">
<img width="273" alt="screen shot 2016-10-18 at 1 04 12 pm" src="https://cloud.githubusercontent.com/assets/4998871/19494316/62bd40a8-9533-11e6-9125-9baaee6fd641.png">

):

**Comment by tberardini** [comment]
Ontology edits are done.

 [Term]
 id: GO:0043581
-name: mycelium development
+name: obsolete mycelium development
 namespace: biological_process
-def: "The process whose specific outcome is the progression of the mycelium over time, from its formation to the mature structure. A mycelium consists of a mass of branching, thread-like hyphae." [GOC:jl, ISBN:1580085792, PMID:12832397]
-is_a: GO:0044767 ! single-organism developmental process
-is_a: GO:0048856 ! anatomical structure development
-intersection_of: GO:0048856 ! anatomical structure development
-intersection_of: results_in_development_of FAO:0000011 ! mycelium
-relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria
-relationship: part_of GO:0007275 ! multicellular organism development
+def: "OBSOLETE. The process whose specific outcome is the progression of the mycelium over time, from its formation to the mature structure. A mycelium consists of a mass of branching, thread-like hyphae." [GOC:jl, ISBN:1580085792, PMID:12832397]
+comment: The reason for obsoletion is that the term is ambiguous. Three more clearly defined terms have been created that should be considered in its place.
+is_obsolete: true
+consider: GO:0097736
+consider: GO:0097737
+consider: GO:0097738
 
 [Term]
 id: GO:0043582
@@ -574595,7 +574594,8 @@
 name: sclerotium development
 namespace: biological_process
 def: "The process whose specific outcome is the progression of the sclerotium over time, from its formation to the mature structure. A sclerotium is a mycelial resting body, resistant to adverse environmental conditions." [GOC:di, PMID:21148914]
-is_a: GO:0043581 ! mycelium development
+is_a: GO:0044767 ! single-organism developmental process
+is_a: GO:0048856 ! anatomical structure development
