### ISSUE TITLE
Wpl/Pds5 cohesin loading complex, small update

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12622]
I made a mistake here. I should have said that this was

GO:0090695	Wpl/Pds5 cohesin loading/unloading complex

(can the term name and def be updated accordingly. current ref covers both)

**Comment by tberardini** [comment]
Val - I changed the term name. Now I wonder about the relationship

capable_of_part_of cohesin loading

should it also have

capable_of_part_of cohesin unloading, GO:0061774?

**Comment by ValWood** [comment]
yes I should have mentioned that too..... sorry for so many changes, this is all so new !

**Comment by tberardini** [comment]
Added:

+relationship: capable_of_part_of GO:0061774 ! cohesin unloading
