### ISSUE TITLE
add relationship between terms? (protein export related)

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12629]
should 
GO:0046826 negative regulation of protein export from nucleus

be a child of 
GO:0051457 maintenance of protein location in nucleus
?
http://www.ebi.ac.uk/QuickGO/GMultiTerm#a=64%240BRg0Ca1&tab=chart&c=

**Comment by Antonialock** [comment]
note to self: 7b30a1cc7d87ace2

**Comment by ValWood** [comment]
@Antonialock
