### ISSUE TITLE
cohesin loading/unloading def tweak

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12624]
GO:0071921 cohesin unloading
Negative regulation of sister chromatid cohesion by the topological unlinking of a cohesin ring to chromatin. 

should be
Negative regulation of sister chromatid cohesion by the topological unlinking of a cohesin ring to DNA.

ditto
GO:0071921 cohesin loading

and mitotic descendants
(sorry I didn't spot this earlier!)

**Comment by ukemi** [comment]
Done
