### ISSUE TITLE
MF term required for 'protein dissociation'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12623]
Wpl/Pds5 cohesin loading/unloading complex binds to the cohesin complex and dissociates the binding of the rad21 kleisin  gate from the psm3 ring subunit  as part of cohesin unloading.

PMID:26687354
Title   DNA Entry into and Exit out of the Cohesin Ring by an Interlocking Gate Mechanism.

All I have so far is  
protein dissociation activity

Directly inhibits the non-covalent interaction between two gene products, or complexes?
(this is poor, but its all I have!)

**Comment by ValWood** [comment]
narrow synonym would be
"DNA exit gate opening"
"Kleisin exit gate opening"
Comment: An example of this term is the dissociation of the Rad21 kleisin N terminus from the ATPase head region of  Smc3/Psm3 subunit of mitotic cohesin
See model fig 7D PMID:26687354

**Comment by Antonialock** [comment]
are activating GPCR peptide hormones also "dissociation factors" (for example glucagon, or yeast mating factors)? 
(peptide hormone binds receptor -> conformational change in the receptor & GTP for GDP exchange -> G protein dissociates)

**Comment by ValWood** [comment]
I guess lots of proteins are "dissociation factors" in that one protein binds and releases another one. I wonder if this phenomena is too general for a GO term.
What I am trying to capture exactly  here is a more specific thing.

One end of the rad21 complex dissociates from the cohesin complex,  where rad21 is acting as a 'gate' or 'latch'. The function of rad21 here (klesin), is as a gate, or latch.
It is acting like the safety chain on one of these bracelets

Imagine if the safety chain also had a latch, like the main bracelt. The pds5/wpl1 loading complex is a direct regulator of the latch of the safety gate.

![rad31](https://cloud.githubusercontent.com/assets/7359272/18164246/c1d19750-7036-11e6-9451-91c14e21bd8d.jpg)

**Comment by ValWood** [comment]
I will also need a molecular function to describe rad21, the exit gate itself....

**Comment by ValWood** [comment]
Maybe we need to be specific
"DNA exit gate"
and
"Dna exit gate opening"
unambiguous and match the authors description.

**Comment by ukemi** [comment]
Hi Val. I thought yesterday we had decided that until we know the mechanism, we would leave this as a generic function in the models for now. If you still agree with this, let's close this ticket.

**Comment by ValWood** [comment]
Yup, I submitted this earlier in the day.
I'll take the ticket and if none of the papers make this clear I'll close.

**Comment by ValWood** [comment]
If we do have such an activity, consider  narrow synonyms:

1. SMC head disengagement
2. Kleisin (Rad21N) disengagement (this would be a synonym for cohesin kleisin exit gate opening)

" SMC head disengagement. After this, DNA exit remains dependent on the presence of ATP, but not its hydrolysis, consistent with the characteristics of Rad21N disengagement."

**Comment by ValWood** [comment]
not required yet

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/28220956?dopt=Abstract
Releasing the cohesin ring: A rigid scaffold model for opening the DNA exit gate by Pds5 and Wapl.
review
