### ISSUE TITLE
synonym for presynaptic active zone

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12627]
Hi

would it be appropriate to add the exact synonym presynaptic specialization to the GO term GO:0048786 presynaptic active zone?

Thanks

Ruth

**Comment by dosumis** [comment]
@Pimmelorus @ftwkoopmans Any comment?

**Comment by ftwkoopmans** [comment]
Within the SynGO project we use 'postsynaptic specialization' as a grouping term but have no equivalent term for the presynapse. Assuming every presynapse (within our model/project scope) has an active zone but no other 'specializations', no grouping is needed so we use active zone (terminology used in the field).

The 'presynaptic specialization' term is sometimes used as a synonym of active zone in literature, but I have seen cases where they use it synonymous with presynapse. I would be fine with the former, not the latter.

**Comment by dosumis** [comment]
I'll take that as a yes.

**Comment by dosumis** [comment]
Done.  Closing now, but would like to add a ref to the synonym if you have one.
