### ISSUE TITLE
erroneous parent GO:0031297 (and def typo)

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12626]
This link looks suspect:

GO:0031297 replication fork processing
is_a: GO:0006974 ! cellular response to DNA damage stimulus

The text definition of GO:0031297 - which is accurate, as far as I know - says that forks may need to be processed under circumstances that do not include DNA damage.

The def is also missing a word, probably "restored", from its first sentence: "The process in which a DNA replication fork that has stalled is [***] to a functional state and replication is restarted."

(This is somewhat related to #12570, in that it cites the same reason not to connect fork processing with repair.)

**Comment by dosumis** [comment]
Fixed as requested.
