### ISSUE TITLE
cohesin loading unloading ancestry

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12625]
I now think the regulation descendants  should be a descendent of positive/and or negative regulation of DNA binding?
See also

@ukemi #12624

"cohesin DNA binding Wapl did not stimulate ATP hydrolysis (Figure S1A), suggesting that it facilitates DNA binding in a different way."
PMID:26687354

**Comment by ukemi** [comment]
So should I make 'cohesin loading' a subclass of DNA binding rather than a subclass of 'protein localization to chromatin'. Or perhaps it should be both? 

Based on the new definition, wouldn't 'cohesin unloading' itself be a negative regulation of DNA binding?

**Comment by ValWood** [comment]
Both seems correct to me....

**Comment by ukemi** [comment]
OK. I added DNA binding as an is_a parent of 'cohesin loading'. The regulation children should sort when the reasoner runs.

It seems that 'cohesin unloading' itself should be a negative regulation of DNA binding. Don't you think?

**Comment by ukemi** [comment]
I made it that for now. It makes sense based on how the term is placed. Let me know if you think I should change it.

**Comment by ValWood** [comment]
> It seems that 'cohesin unloading' itself should be a negative regulation of DNA binding. Don't you think?

yep, I agree  see first comment

**Comment by ukemi** [comment]
Oops. I can't make cohesin loading a child of DNA binding because DNA binding is a molecular function and cohesin loading is a biological process. I can make cohesin loading has_part DNA binding.

**Comment by ValWood** [comment]
Its the process "GO:0051101 regulation of DNA binding" that we need "cohesin loading" to be related to

**Comment by ukemi** [comment]
So cohesin loading is_a positive regulation of DNA binding. That makes sense to me.

**Comment by ValWood** [comment]
yep and -ve for the unloading

**Comment by ukemi** [comment]
Done
