### ISSUE TITLE
NTR: somatodendritic dopamine secretion

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12637]
I could do with some new GO terms to annotate the role of Synaptobrevins in PMID:21576241:

somatodendritic dopamine secretion ; GO:NEW
is_a: dopamine secretion ; GO:0014046
_suggested_ intersection: dopamine secretion ; GO:0014046 that occurs_in: somatodendritic compartment ; GO:0036477
The regulated release of dopamine from the somatodendritic compartment (cell body or dendrites) of a neuron [GOC:bf, GOC:PARL, PMID: 21576241]
synonym: somatodendritic dopamine release [PMID: 21576241]
synonym: STD dopamine release [PMID: 21576241]
synonym: STD DA release [PMID: 21576241]

axonal dopamine secretion ; GO:NEW
is_a: dopamine secretion ; GO:0014046
_suggested_ intersection: dopamine secretion ; GO:0014046 which occurs_in axon ; GO:0030424
The regulated release of dopamine from the axon of a neuron [[GOC:bf, GOC:PARL, PMID: 21576241]
synonym: axonal dopamine release [PMID: 21576241]
synonym: axonal DA release [PMID: 21576241]

I'll need to add 'regulation' terms in through TG for both.

Given that the end of the process ends with the protein being extracellular, would 'has_target_start_location/has_start_location' be better relations for the intersections?

Thanks!

**Comment by rebeccafoulger** [comment]
Hi @dosumis - any comments on these?

**Comment by Pauldenny** [comment]
I am "lurking" here, after Rebecca @rebeccafoulger leaves UCL

**Comment by Pauldenny** [comment]
Hi @dosumis - any update on these?

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21049482/fab94558-be0c-11e6-97f3-bebbf617fc1b.png)

GO_0099123
![image](https://cloud.githubusercontent.com/assets/112839/21049460/d938f8ba-be0c-11e6-8f38-d4122adb1aed.png)

GO_0099124

![image](https://cloud.githubusercontent.com/assets/112839/21049468/e44beda2-be0c-11e6-86f5-3f6a5f71684e.png)

Decided to stick with 'occurs in' as this is used for neurotransmission secretion terms.  This at least reflects the location of the secretory machinery.
