### ISSUE TITLE
GO:0005471 parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12631]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005471#term=ancchart

the parent "purine ribonucleotide... looks incorrect.

**Comment by ValWood** [comment]
Also ATP and ADP  transmembrane transporters have both 
nucleotide and nucleotide parentage. Should it be only  nucleotide (with phosphate)? 

(note to self, to prevent redundant inferred annotation  request ATP and ADP transmembrane transport)

**Comment by dosumis** [comment]
This is a ChEBI issue: 

![image](https://cloud.githubusercontent.com/assets/112839/18958295/13720aac-865a-11e6-9359-3abc2ce6aa7a.png)

Needs to be fixed there https://github.com/ebi-chebi/ChEBI/issues
  Can you submit a ticket?

CC @hdrabkin

**Comment by ValWood** [comment]
Just checking that you did not mean me to submit the ticket here (as I'm not sure what the Chebi issue is).

**Comment by dosumis** [comment]
https://github.com/ebi-chebi/ChEBI/issues/3224

If ChEBI is fixed, the fix will propagate automatically to all affected GO terms.  Until then, there's not really anything that GO can do to fix.
