### ISSUE TITLE
Revision request re GO:0003374 dynamin polymerization involved in mitochondrial fission

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12639]
Hello,

I have recently been annotating the roles of dynamin-related protein 1 / dynamin-like protein 1 (DRP1/DLP1; O00429), involved in mitochondrial and peroxisomal division, and I have come across the term 'GO:0003374 dynamin polymerization involved in mitochondrial fission'. 

This term, and its definition, suggest that dynamin is involved in mitochondrial fission. Based on findings published to date, there is no evidence in the literature for involvement of dynamin (Q05193) in mitochondrial fission. 

In contrast, there is evidence that DRP1/DLP1 (O00429), which belongs to the _dynamin superfamily_ (IPR022812: http://www.ebi.ac.uk/interpro/entry/IPR022812), mediates mitochondrial fission.

Relevant sources:
- PMID-9472031 - This paper shows that Dynamin-1 and DRP1/DLP1 do not colocalise and are enriched in different cellular fractions (plasma membrane vs. cytoplasm and intracellular membranes).
- PMID-21170049 - This paper evaluates the structural and functional differences between Dynamin-1 and DRP1/DLP1; it discusses the mechanistic aspects of how both proteins work and why these mechanisms of action fit with the role of dynamin in scission of budding vesicles (but not membranous structures of greater diameters); whereas DRP1/DLP1 forms _larger helices of much greater plasticity_ than dynamin-1, supporting the role of DRP1/DLP1 (but not dynamin!) in mitochondrial fission. Furthermore, dynamin is integral to membranes, whereas, as this study shows, DRP1/DLP1 forms extrinsic membrane components, which additionally demonstrates that these two proteins would be involved in different types of scission.
- PMID-22233676 - Figure 1 in this review summarises the involvement of both proteins in different cellular processes. None of the sources cited in this (relatively recent) review suggest that dynamin is involved in mitochondrial fission. 

Therefore, the GO term 'GO:0003374 dynamin polymerization involved in mitochondrial fission' is misleading. I believe this term needs to be changed to one of the following terms:
- dynamin family protein polymerization involved in mitochondrial fission
- DLP1/DRP1 polymerization involved in mitochondrial fission

Only two manual annotations have been created using this term (both for DLP1/DRP1!), so this should be a 'quick fix' indeed :)

Thanks,
Barbara

@RLovering 
@rebeccafoulger 
@Pauldenny

**Comment by ValWood** [comment]
Is this even a 'real' process?....  don't the polymers form autonomously? Of course if you don't have the polymer components you don't form the polymer, but are these really involved in a 'process'

A better way to annotate these would be 

GO:1990606 membrane scission GTPase motor activity part_of mitochondrial membrane fission

**Comment by ValWood** [comment]
In fact, the abstract of the first paper states
"We find that purified human Drp1 can self-assemble into multimeric ring-like structures with dimensions similar to those of dynamin multimers. "
I think this term should be obsoleted.....

**Comment by ukemi** [comment]
Any thoughts on this? If there are molecules that regulate the process, then it might be worth keeping.

**Comment by Pauldenny** [comment]
From a cursory glance at abstract, this (PMID: 27559132 ) is evidence that actin filaments regulate, in turn, polymerisation of DRP1 (=dynamin) "The ability of Drp1 to bind actin filaments in a highly dynamic manner provides potential for actin filaments to serve as reservoirs of oligomerization-competent Drp1 that can be accessed for mitochondrial fission" 

and also this title:

"Actin filaments target the oligomeric maturation of the dynamin GTPase Drp1 to mitochondrial fission sites." PMID: 26609810

**Comment by ukemi** [comment]
I vote to keep it then. I have changed the name and associated strings to dynamin family protein.

**Comment by ValWood** [comment]
Sounds good,  the human annotation on DRP1 should be fixed though.... @mcourtot

**Comment by BarbaraCzub** [comment]
Thank you!
