### ISSUE TITLE
add taxon check to all miRNA related terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12634]
Never in fungi (as far as I'm aware, we have siNRAs but not miRNAs)
Interacting selectively and non-covalently with a microRNA, a 21-23 nucleotide RNA that is processed from a stem-loop RNA precursor (pre-miRNA) that is encoded within plant and animal genomes. 
PMID:15066283

Can we add  this taxon restriction to this, as we are picking up  automated mappings?

**Comment by ukemi** [comment]
PMID:24173579  suggest they or something really similar are found in fungi.

**Comment by ValWood** [comment]
Oh yes, we have RNAi in fungi (S. cerevisiae doesn't), but we don't, (as far as I'm aware) have micro RNAs (processed from a stem-loop RNA precursor), we have siRNA's (processed from double stranded RNA).

But see Rachel's paper...https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4836642/
anomil and plant pathways. We have the machinery in fungi  but in different kingdoms the type of regulation is quite different.

I think this is assumed enough to add a taxon restriction. RNAi is pretty well studied in fungi so if this taxon restricted was lifted it o would be a big event....

**Comment by ValWood** [comment]
Hmmmph, DAvid pointed out:

 miRNAs have been extensively studied in animals, plants, and algae, but fungi were assumed to lack this pathway. However, miRNA-like small RNAs (milRNAs) have been found in N. crassa, and four different classes have been described so far that are distinguished by the mechanism of their biogenesis (Lee et al., 2010b). Different combinations of RNAi proteins are implicated in the production of the four different milRNAs classes, but none is precisely the same mechanism as for conventional miRNAs. milR-2 is Dicer-independent but QDE-2-dependent; milR-3 and milR-4 are completely or partially dependent on Dicer but not QDE-2; milR-1, the most abundant, is dependent on Dicer, the presence of QDE-2, but not its slicer activity, and the exonuclease QIP (Lee et al., 2010b). The maturation of milR-1 is also dependent on the RNA exosome (Xue et al., 2012), which may explain why the QDE-2 nuclease activity is not required. Despite their differences in biogenesis, milRNAs also seem to silence endogenous transcripts with partial complementarity, similar to animal miRNAs (Lee et al., 2010b).

MAybe leave this one for now without a taxon restriction. I  can filter mappings and ask for them to be deleted where appropriate.
