### ISSUE TITLE
confusing term: GO:1990296 scaffoldin complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12632]
Looks like it was created for bacterial structures (taxon restraint: prokaryota) but has no annotations. I stumbled over it looking for "scaffold complex" or "scaffolding complex" akin to MF GO:0032947 protein complex scaffold.

1) Can we fix the existing term so it's clear what it's for?

2) Would it be reasonable to create a CC term akin to GO:0032947 protein complex scaffold? Looks like I may be able to use the TG template for this.

PMID: 23219485 - Atg17-Atg31-Atg29 complex is a scaffold for the larger ATG1 complex (GO:1990316 ATG1/ULK1 kinase complex)

Thanks,
Birgit

Note to self: complex EBI-11686111

**Comment by ValWood** [comment]
I don't think we should do that. The MF term  "protein complex scaffold" (could probably be named better, is used to describe the activity of a protein  (often a WD repeat) which  provides a platform onto which c complex assembles. For example

For example, cdc11 for the septation iniitiation signalling complex
http://www.pombase.org/spombe/result/SPCC1739.11c
(note to self, we do not have this complex annotated)

or git5 in one of the fission yeast heterotrimeric G-protein complexes

its not the purpose of the complex per se.

**Comment by bmeldal** [comment]
Thanks, Val.

ATG17 (one of the members of my complex) in pombe and S. cerevesiae is annotated to GO:0032947 protein complex scaffold. The other 2 members have no MF annotation (so far) but ATG17 is the big member that dimerises and ATG31 binds to (ATF29 binds to ATG31).

**Comment by ValWood** [comment]
Hi Birgit,

This appears to be a complex involved in membrane curvature, like the F-Bar proteins?
I'm not sure that its a scaffold in the sense of the MF GO term, but you are correct this  term is not  very clear.

Val

**Comment by dosumis** [comment]
* Any suggestions for clarifying the def of 'scaffoldin complex'? 

> Would it be reasonable to create a CC term akin to GO:0032947 protein complex scaffold? 

Surely we wouldn't want both.  And you can use capable_of to link existing MF term to complexes.

**Comment by bmeldal** [comment]
> Any suggestions for clarifying the def of 'scaffoldin complex'?

Can't help with that, not my term, just something I stumbled over. Sorry :(

>    Would it be reasonable to create a CC term akin to GO:0032947 protein complex scaffold?
Surely we wouldn't want both. And you can use capable_of to link existing MF term to complexes.

I think this complex initiates the assembly of the preautophagosomal structure (PAS), the first step of autophagosome formation. I haven't seen anything that it is actually involved in membrane curvature (but it might, given its characteristic crescent shape!).

So, I would still argue we might need a CC term that can group scaffolding complexes. Otherwise, they all remain annotated to 'protein complex' or I have to request specific, composition-based complexes for these terms.

In this case, the released complex is annotated to 'protein complex' for now but I could request 
Name: Atg17-Atg31-Atg29 complex
Def: Scaffolding complex required for the assembly of the preautophagosomal structure (PAS), the first step of autophagosome formation. Constructively present under both growing and starvation conditions. Under conditions of nutrient starvation, it forms a complex with ATG1 and ATG13 to enhance the kinase activity of ATG1.

**Comment by pgaudet** [comment]
Hello @bmeldal 
Should we obsolete 'GO:1990296 scaffoldin complex'? It was created in 2014 and never used yet. 
Also the cited papers refer to another term, 'Cellulosome', which is a parent and has 3 annotations. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Happy with the obsoletion but better check with the DB that requested it. I've never used the term, it was a chance find that caused confusion.

**Comment by pgaudet** [comment]
The terms (the complex and the complex binding terms) were requested by MENGO for plant papers. @tberardini do you know anything about this ? 

Thanks, Pascale

**Comment by tberardini** [comment]
@pgaudet I don't know any more about this than what can be found with PubMed searches.  

The term does have these relationships
> is_a: GO:0043234 ! protein complex
relationship: part_of GO:0043263 ! cellulosome

The parent term 'cellulosome' is defined as:
> An extracellular multi-enzyme complex containing up to 11 different enzymes aligned on a non-catalytic scaffolding glycoprotein. Functions to hydrolyze cellulose. Source: PMID:11601609, GOC:jl

I found this:

http://www.sciencedirect.com/topics/agricultural-and-biological-sciences/cellulosome

>In general, the cellulosome can be divided into three modular protein components: (1) cell-surface proteins, (2) scaffold proteins, and (3) enzymes (Fig. 7A). 

My guess is that the 'scaffoldin complex' = (2) scaffold proteins above.

I hope this information helps in deciding whether or not to keep the term.  Just because the term hasn't been used yet doesn't mean we should get rid of it.

One more point:

>First discovered in the thermophilic anaerobe Clostridium thermocellum, cellulosomes have since been identified in a variety of other anaerobic bacteria, ruminal bacteria, and anaerobic fungi (Bayer et al., 2004). 

Based on the identification in anaerobic fungi (above), the taxon restriction on 'cellulosome' needs to be broadened beyond Prokaryota.

**Comment by pgaudet** [comment]
Summary: I will merge the two terms: 
the papers cited in the term (PMID:20373916, PMID:15197390) are actually annotated to the parent GO:0043263 cellulosome, indicating that the term is not really useful for annotation. Moreoverm the titles of these two papers mention “cellulosome”. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@bmeldal 

Just checking one last time: the scaffoldin seems to be a subcomplex of the cellulosome. Is this a legit complex ? I can keep both terms and change the definition as suggested by Tanya, or merge. 

Thanks, Pascale

**Comment by bmeldal** [comment]
If the subcomplex has a function on it's own then it would be legit, if it's **only** a pre-assembly construct I would say not. 

From the thread above it looks like the latter and as it has no annotations I'd merge with the parent term and make it a NARROW synonym so at the the term is findable.
