### ISSUE TITLE
NTR: mitochondrial iron-sulfur cluster assembly complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12630]
Hello I'd like a sibling term to the cytoplasmic iron-sulfur cluster assembly complex term GO:1990229 so that I can ISS the pombe genes to this term.

Name: mitochondrial iron-sulfur cluster assembly complex
Def: A protein complex consisting of frataxin, cysteine desulfurase, an accessory protein and a Fe-S scaffold protein. In human these genes correspond to FXN, NFS1, ISD11 and ISCU respectively. This complex assembles Fe-S clusters onto the scaffolding protein using the substrates ferrous iron, electrons, and sulfur from l-cysteine. 

PMID:27519411

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21103918/66bc6f20-c07c-11e6-9057-b9010e173956.png)
