### ISSUE TITLE
CVT pathway taxon restriction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12636]
CVT pathway is

A constitutive biosynthetic process that occurs under nutrient-rich conditions, in which two resident vacuolar hydrolases, aminopeptidase I and alpha-mannosidase, are sequestered into vesicles; these vesicles are transported to, and then fuse with, the vacuole. This pathway is mostly observed in yeast. 

This is a specific pathway obeserved in S. cerevisiae. I don't know how broad it is, but it isn't present in fission yeast where  cytoplasmic to vacuole targeting does not occur in nutrient rich conditions.

(most cytoplasm to vacuole transport in via secretory pathway)

**Comment by ukemi** [comment]
So never in Pombe?

**Comment by ukemi** [comment]
I have the choice:
S. pombe
Schizosaccharomyces
Schizosaccharomycetaceae
Schizosaccharomycetales
Schizosaccharomycetes
Taphrinomycotina

If I don't hear back, I will just make it S. pombe.

**Comment by ValWood** [comment]
From my understanding, this pathway has only been observed in yeast. The name of this pathway does not only imply cytoplasm to vacuole targeting, its  is also
i) constitutive in notrogen rich conditions
ii) it is about the transport of 2 specific hydrolases

It is defined thus:
A constitutive biosynthetic process that occurs under nutrient-rich conditions, in which two resident vacuolar hydrolases, aminopeptidase I and alpha-mannosidase, are sequestered into vesicles; these vesicles are transported to, and then fuse with, the vacuole. This pathway is mostly observed in yeast. 
PMID:12865942 PMID:15659643

and this is what it means when used. I don't think it can be used appropiatly by many other organisms. Perhaps we want this term to mean something else? (just protein targeting to vacuole?, the parent). It only has experimental annotations from yeast...

So the question is which other species is it observed in.
I would probably say a good filter is "only in saccharomyces" and relax it if any other species requires it...

(this will  force the Ensembl IEA mappings to be more conservative)

**Comment by ValWood** [comment]
This is a review for CVT pathway 
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2843786/
which is a type of 'selective autophagy'

It used to have autophagy as a parent, but it no longer does, I'm not sure why?
2009-12-11	Deleted	RELATION	is a GO:0071211 (protein targeting to vacuole involved in autophagy)

**Comment by ValWood** [comment]
Maybe it isn't 'proper' autophagy?

**Comment by ukemi** [comment]
It doesn't have autophagy as a parent because although it share things with autophagy, it is not a type of autophagy. That was a long discussion in the autophagy group.

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/12289

**Comment by ValWood** [comment]
you can probably close https://github.com/geneontology/go-ontology/issues/12289
now too?

**Comment by ukemi** [comment]
Yup. The taxon restriction is already there.
