### ISSUE TITLE
bipolar growth synonyms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12645]
NETO and
new end take off
should not be synonyms of 
GO:0051519 activation of bipolar cell growth
because this term is describing 'growth'.

NETO is about the *direction* of growth. In the absence of NETO cells will grow just the same, but monopolarly

The term 
GO:0051523 cell growth mode switching, monopolar to bipolar
is describing NETO. It is  currently a child of 
GO:0051519 activation of bipolar cell growth, but it needs to move.
(it has only been used by PomBase)

I'm not sure where it should go but  we often use

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071963
and descendants for "polarity of growth"

I'm not sure that this is *quite right* because shape is not always affected (a monopolarly growing cell  cylindrical  is the same shape as a bipolarly growing cell)

so under here
GO:0061245 establishment or maintenance of bipolar cell polarity
or one of its descendants?

(The problem arrises because people call this process  'polarized growth' but its really about establishing growth zones and not the size increase per se)

**Comment by ukemi** [comment]
'activation of bipolar cell growth' is not describing growth. It is describing the activation of growth. It is a child of positive regulation of bipolar cell growth. Is this still not correct? 

Based on what you say above, it looks like the current structure is correct and we should move the synonyms to the more specific 'cell growth mode switching, monopolar to bipolar'. That term essentially means stopping monopolar growth and starting bipolar growth.

**Comment by ValWood** [comment]
I don't think so. I'm not sure what is wrong, but these genes for NETO we are annotating have *nothing* to do with a size increase.  They are only regulating "where" the growth occurs. The cell size increase is *totally independent* and requires bzillions of processes (doubling of cytoplasmic contents, energy  etc)

**Comment by ValWood** [comment]
This term can stay where it is, it's just not NETO.

This term is describing NETO more closely, and it doesn't mention size, 
GO:0051523 cell growth mode switching, monopolar to bipolar

It could be refined 
The process in which a cell switches from monopolar cell growth to bipolar cell growth.

to
The process in which a cell switches *the direction of growth* from monopolar cell  to bipolar.

which should prevent it from ever being placed under 'growth'.

**Comment by ukemi** [comment]
OK, then it sounds like all it is doing is establishing cell polarity. I have removed the NETO and 'new end take off' synonyms from 'activation of bipolar cell growth' and moved them as narrow synonyms of 'cell growth mode switching, monopolar to bipolar'.

**Comment by ValWood** [comment]
OK, but now 
'cell growth mode switching, monopolar to bipolar'.
needs to move  to under the 'establishment of polarity terms'

currently it is under the bipolar growth term. I think it was just added in the wrong place.

**Comment by ukemi** [comment]
Right now 'cell growth mode switching, monopolar to bipolar' is_a 'regulation of direction of cell growth' and is_a 'activation of bipolar cell growth'. Should I also add the establishment of polarity terms? I can see how the regulatory mechanism is by establishing cell polarity, but since the term refers to cell growth mode switching, it makes sense that it would regulate the growth. I think in this case it is regulating how the cell is growing, not the rate at which it is growing.

**Comment by ValWood** [comment]
But it isn't regulating growth at all (as in a size increase).

All that the "NETO switch" does is  changes the position of the growth zones so that they are at 2 ends instead of one.  If the switch doesn't happen the cell still grows to the same size, but only from one end..... (i.e  the cell isn't any smaller).

**Comment by ukemi** [comment]
So what about the 'regulation of direction of cell growth parent'?

**Comment by ValWood** [comment]
I think "regulation of direction of cell growth" as a parent is fine.

However, I don't think that
 "regulation of direction of cell growth" should be a child of "regulation of growth"

They are 2 different things aren't they?

Also, not all regulation of the direction of growth is regulating cell shape (some is, but not all)
so, I think it can only go under
 GO:0065008 regulation of biological quality

**Comment by ukemi** [comment]
OK. It is not a biological quality according to the OBA parent. I'm not convinced it is not a type of regulation of growth, but I have made the change.

**Comment by ValWood** [comment]
Here is my logic. 

Cell growth
The process in which a cell irreversibly increases in size over time by accretion and biosynthetic production of matter similar to that already present.

So, growth is very specifically an increase in cell size.
This includes increasing all cell matter. For example  a doubling of cytoplasmic components before division. This includes all cytoplasmic components, and cell wall expansion etc.

The processes we are annotating the mutants affect the direction or growth. The cell size is not affected _at all_ even though these gene products are dictating where the  new cell wall material and membrane is deposited.

Firstly NETO. This is a switch in fission yeast which established "bipolar growth". This is not referring to growth at all, but  only the direction of growth.
Cells grow monopolarly until a point in G2 when they begin to grow from both ends. Experiments can demonstrate when this switch is broken, because new cell material is added only at one end. However, the cells are the same size as wild type. This implies that the cells deposit the cell wall material where instructed, and this is independent of growth.
So in fission yeast abolished NETO does not affect size OR morphology.
One consequence of NETO is that the septum is not centrally positioned (because the cell is growing asymmetrically). 
I wasn't sure this was true, but when I do the query

FYPO_ID(FYPO:0001018 - abolished activation of bipolar cell growth)   13
FYPO_ID(FYPO:0004293 - mislocalized septum)   44
FYPO_ID(FYPO:0001018 - abolished activation of bipolar cell growth) for All Alleles ) AND ( FYPO_ID(FYPO:0004293 - mislocalized septum)  13

Which is pretty cool!  (although this might be due to a relationship between these terms in FYPO).

These are 'genes' rather than alleles  (we can't query on alleles at present), so it is difficult  to 
check if they are all normal size, but a spot check  for the same allele
showed that abolished activation of bipolar cell growth
 they also have 
	viable vegetative cell, abnormal cell shape, normal cell size
(see kap111 or ash2  deletion phenotypes).

So I would argue that what we are trying to capture here is parallel to growth, but often gets tangled with it  because of historical semantics. 

Second, we have another situation where cells lose polarity (cylindrical shape) totally. Again 
these cells are (as far as we know), normal size/volume.  For these we are using

"establishment or maintenance of cell polarity regulating cell shape"

So in summary it appears that, in the absence of instructions where to deposit the cell wall material, the amount which needs to be deposited gets put somewhere to parallel the increase in size. Imagine if this did not happen? In fungi II guess the cell would lyse. I don't know what would happen in animal cells  but the cells *must* increase in size in accordance with an increase in cell contents.  Exactly where the growth occurs appears to be completely independent of the size increase. 

What regulates "cell size" is still a very open question 
https://www.crick.ac.uk/research/a-z-researchers/researchers-k-o/paul-nurse/
"but it is not clear how cells monitor their volume or mass and integrate this information with cell cycle progression."

This is why I like to make sure that things annotated "regulation of cell size" are kept in check. It isn't helpful to those addressing this question if we annotate the things involved in "position of the growth zone" to "cell size regulation". 

Convinced?

**Comment by mah11** [comment]
> Convinced?

Broadly, no.

I'm with David. Something that affects growth direction does affect the _process_ in which cells add matter. Regulating how much matter increases is not the only way to regulate a growth process.

I do agree that the NETO term should not have a path to "regulation of cell size", "regulation of extent of cell growth", or "regulation of rate of cell growth" - but it doesn't. Regulation of direction, extent, and rate are siblings under regulation of cell growth.

Everything you've said in the latest comment makes an excellent case that "regulation of direction of cell growth" should stay where it is, and NOT move under regulation of extent or rate, but it doesn't make any case that there's anything wrong with what GO has now. It's also completely consistent with NETO having a path to regulation of growth direction.


small thing:

> FYPO_ID(FYPO:0001018 - abolished activation of bipolar cell growth) 13
> FYPO_ID(FYPO:0004293 - mislocalized septum) 44
> FYPO_ID(FYPO:0001018 - abolished activation of bipolar cell growth) for All Alleles ) AND ( FYPO_ID(FYPO:0004293 -
mislocalized septum) 13
> 
> Which is pretty cool! (although this might be due to a relationship between these terms in FYPO).

The terms are linked:

id: FYPO:0001018
name: abolished activation of bipolar cell growth
[snip]
relationship: has_output FYPO:0001391 ! mislocalized septum, near new end

**Comment by ValWood** [comment]
OK, I am confusing growth and size.
Maybe this def of cell growth could be better, because it could be clearer what cell growth includes other than a size increase?

The process in which a cell irreversibly increases in size over time by accretion and biosynthetic production of matter similar to that already present.

So, yes the original parent was OK, but  this existing ancestor

 GO:0060560 developmental growth involved in morphogenesis

would is not always true.


> The terms are linked:
Its still cool though!

**Comment by ukemi** [comment]
OK. I added the relation back. 'Regulation of direction of cell growth' is now a subclass of 'regulation of cell growth' again.
