### ISSUE TITLE
protein serine/threonine kinase binding

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12646]
I would like to see "protein serine/threonine kinase binding" added to the GO ontology under the parent term "protein kinase binding" (GO:0019901).  The definition could be "Interacting selectively and non-covalently with a protein serine/threonine kinase".  An example can be found in PMID:25456499.

**Comment by ukemi** [comment]
Hi Stan. A while back we decided we were not going to add specific terms for binding based on functional classification of a protein.

-D
