### ISSUE TITLE
NTR: dense core vesicle (DCV) docking and priming

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12647]
A suggestion for two new vesicle priming & docking terms needed for annotation of PMID: 26575293:

dense core granule priming ; GO:NEW
synonym: LDCV priming [PMID:26575293]
synonym: dense core vesicle priming [PMID:26575293]
synonym: large dense-core vesicle priming [PMID:10899113]
A process that converts unprimed dense core granules (DCVs) to a pool of primed vesicles that are capable of fusing with the plasma membrane (fusion-competent) and thereby releasing their contents. Priming typically occurs after docking.
is_a: cellular protein complex assembly ; GO:0043623
part_of: dense core granule exocytosis ; GO:1990504
GOC:bf, GOC:PARL, PMID:10899113, PMID:26575293

(similar to: synaptic vesicle priming ; GO:0016082)

dense core granule docking ; GO:NEW
part_of: dense core granule exocytosis ; GO:1990504
is_a: vesicle docking involved in exocytosis
The initial attachment of a dense core granule membrane to the plasma membrane.
intersection: is_a: vesicle docking ; GO:0048278 
intersection: part_of: dense core granule exocytosis ; GO:1990504
GOC:bf, GOC:PARL, PMID:26575293

Thank you!

**Comment by dosumis** [comment]
@Pimmelorus @ftwkoopmans Any comments?  These look potentially useful for Synapse project.

**Comment by ftwkoopmans** [comment]
The terms seem fine to me. DCV processes and this paper from our colleagues are definitely on the SynGO radar

**Comment by ukemi** [comment]
[Term]
+id: GO:0061789
+name: dense core granule priming
+namespace: biological_process
+def: "A process that converts unprimed dense core granules (DCVs) to a pool of primed vesicles that are capable of fusing with the plasma membrane (fusion-competent) and thereby releasing their contents. Priming typically occurs after docking." [GOC:bf, GOC:PARL, PMID:10899113, PMID:26575293]
+synonym: "dense core vesicle priming" EXACT [PMID:26575293]
+synonym: "large dense-core vesicle priming" EXACT [PMID:10899113]
+synonym: "LDCV priming" EXACT [PMID:26575293]
+is_a: GO:0043623 ! cellular protein complex assembly
+relationship: part_of GO:1990504 ! dense core granule exocytosis
+created_by: dph
+creation_date: 2016-09-08T15:41:30Z
+
+[Term]
+id: GO:0061790
+name: dense core granule docking
+namespace: biological_process
+def: "The initial attachment of a dense core granule membrane to the plasma membrane." [GOC:bf, GOC:PARL, PMID:26575293]
+is_a: GO:0006904 ! vesicle docking involved in exocytosis
+intersection_of: GO:0048278 ! vesicle docking
+intersection_of: part_of GO:1990504 ! dense core granule exocytosis
+relationship: part_of GO:1990504 ! dense core granule exocytosis
+created_by: dph
+creation_date: 2016-09-08T15:51:49Z
