### ISSUE TITLE
NTR intracellular signal transduction involved in positive regulation of cell growth 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12643]
NTR intracellular signal transduction involved in positive regulation of cell growth 
ref PMID:15917811
Any intracellular signal transduction that is involved in positive regulation of cell growth

**Comment by ukemi** [comment]
Is it part of the positive regulation of cell growth, or is it the mechanism of the positive regulation?

**Comment by Antonialock** [comment]
I don't understand your question David.

**Comment by Antonialock** [comment]
Val wanted to wait with these

**Comment by ukemi** [comment]
If the signaling is the mechanism by which the growth is being regulated, then you would use the 'regulation of x by y' template in termgenie. If the signaling contributes to a larger regulatory process then you would use the 'x involved in y' template.

**Comment by ValWood** [comment]
This one is probably OK, I have no idea whether all 'regulation of growth' is by signalling....
probably not.....

**Comment by ukemi** [comment]
In this case the important distinction is:
If the signaling is the mechanism by which the growth is being regulated, then you would want 'regulation of x by y' (positive regulation of cell growth by intracellular signal transduction). If the signaling contributes to a larger regulatory process then you would want the 'x involved in y'  (intracellular signal transduction involved in positive regulation of cell growth).

**Comment by Antonialock** [comment]
Hmm, it is definitely controlled by a larger regulatory process. I don't know if it is part of it or not. 

In pombe, cells cease to grow in response to certain stresses, sensed by a stress response mechanism. Cells can resume growth again once they have acclimatized or dealt with the stress damage. According to GO, s this part of the mechanism or downstream?

here is the diagram from the figure. Sty1 represents the stress response pathway

![screen shot 2016-09-07 at 13 14 56](https://cloud.githubusercontent.com/assets/12727506/18316398/585604ba-7512-11e6-9185-6c27759bc739.png)

**Comment by ValWood** [comment]
It seems as thought this is regulating cell cycle re entry and the localization of actin to restablish normal  'growth". This is why I dislike using the 'growth terms' unless they are really referring to a cell size increase... growth and division are separable  but intimitly connected....

during the cell cycle there is a size increase, but are they really showing that plo1 is regulating the size increase? isn't it just regulating polarity/ directionality of growth....

**Comment by Antonialock** [comment]
plo1 mutants are defective in restarting growth following arrest.

plo1 does NOT regulate polarity (I can't see anything about that in the reference at least - are you thinking of pom1? - I also don't think I would make anything as specific as "regulation of actin cytoskeleton" based on the figures in this paper). I think they demonstrate intracellular signal transduction between the stress response and resuming growth, and traversing G2M

**Comment by ValWood** [comment]
> are you thinking of pom1?

yes ;)

ok then this term sounds ok to me...

**Comment by ukemi** [comment]
Which term? It seems to me that it would be 'positive regulation of cell growth by intracellular signal transduction'.

**Comment by Antonialock** [comment]
or should it be positive regulation of re-entry into mitotic cell cycle (surely this term should have signal transduction as a parent?)

**Comment by ukemi** [comment]
Is this the growth request or the G2/M request? Now I am confused.

**Comment by Antonialock** [comment]
growth

**Comment by Antonialock** [comment]
I suppose growth might just be a readout for re-entering the cell cycle. I guess that these mutants must have properly exited the cell cycle because they do not grow at all - compare to mutants defective in traversing G2/M that will still keep on growing (stuck in G2)

**Comment by ValWood** [comment]
The cell cycle and the growth are separate pathways.

It could be positive regulation of
 GO:0000320 re-entry into mitotic cell cycle
but that is more related to the other ticket ....

**Comment by ukemi** [comment]
'positive regulation of cell growth by intracellular signal transduction'?

**Comment by ValWood** [comment]
> I suppose growth might just be a readout for re-entering the cell cycle.

Oh I see what you mean.
That would make sense.

**Comment by Antonialock** [comment]
This is the legend to the diagram. Does this help? 

A Cartoon showing the two functions executed  by Plo1 S402 phosphorylation. (A)  SRP promotes phosphorylation of Plo1 on serine 402 in unperturbed cell cycles this phosphorylation promotes Plo1 recruitment to SPBs and thereafter commitment to mitosis. The exact mechanism by which Plo1 recruitment mediates commitment to mitosis awaits clarification.  (B) A second role for serine 402 phosphorylation follows the Spc1/Sty1 stimulated response to heat shock or centrifugation. While stress mediated stimulation of Spc1/Sty1 arrests nuclear division and de-polarises the actin cytoskeleton, Plo1 S402 phosphorylation promotes the resumption of the cell cycle and actin mediated cell tip growth once the stimulation of Spc1/Sty1 has receded.

**Comment by ukemi** [comment]
'positive regulation of cell growth by intracellular signal transduction'?

**Comment by ValWood** [comment]
I looked at the paper and it does appear to be regulation of growth

) analysis supported this view: at least 60% of the
plo1.S402A population had failed to show any increase in size 5 h after
shift (Fig. 4d).

although I havedidn't get  how it is known that this isn't just  a consequence of other regulation  feedback loops  to growth signalling if the cell cycle is  cannot restablish....

Its probably the best annotation for now.

**Comment by Antonialock** [comment]
how do you know it is growth and not cell cycle re-entry?

**Comment by ValWood** [comment]
Its both....

**Comment by ukemi** [comment]
Could either one of you please sum this up and let me know which term/s to add?

**Comment by ValWood** [comment]
I think Antonia's first request was correct.

Its signal transduction involved in +ve regulation of growth (and also cell cycle re-entry - forked pathway, but we'll do that one later)

I haven't been requesting these 'signal transduction involved in' , 
but its good to have them....

**Comment by ukemi** [comment]
Created via TermGenie.

**Comment by Antonialock** [comment]
intracellular signal transduction involved in positive regulation of G2/M transition of mitotic cell cycle
intracellular signal transduction involved in positive regulation of re-entry into mitotic cell cycle

**Comment by ukemi** [comment]
Shouldn't these go with the other ticket that Val is still thinking about?
#12644

**Comment by dianeoinglis** [comment]
Would this not be considered as a derepression of cell growth arrest?

**Comment by ValWood** [comment]
I think you need 2 terms Antonia

1. intracellular signal transduction involved in positive regulation of re-entry into mitotic cell cycle
(BUT I think if the process
GO:0000320
Name	re-entry into mitotic cell cycle
Ontology	Biological Process
Definition	The resumption of the mitotic cell division cycle by cells that were in a quiescent or other non-dividing state.

should be defines as a signalling pathway, which would remove the need for the new term.

Although maybe you need to specify the point of re-entry is G2 

2. intracellular signal transduction involved in positive regulation of G2/M transition of mitotic cell 
again, regulation of G2/M is a signalling pathway.....
I will have a proposal to fix this shortly. 

all of this should go in the other ticket.....










2.


BUT, I think that the regulation of G2/M transition, if defined correctly *is * a signalling pathway.
