### ISSUE TITLE
Term revision request GO:0043205 fibril

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12640]
Hello,

Could I please request that the term 'GO:0043205 fibril', which is defined as: 'Extracellular matrix material consisting of polysaccharides and protein,' is changed to 'extracellular fibril' for clarity?

'Fibrils' can also be intracellular, as is shown in PMID:27385586, Figure 6A (arrows in the lowest panel), and described: “These aggregates are also thioflavin-S positive indicating that some of the aggregated alpha-synuclein is in a fibrillary form (Fig 6A).”

Atm, two PARL alpha-synuclein annotations to 'GO:0043205 fibril' exist, which we will revise to confirm whether the fibrils were found in intracellular inclusions, or extracellularly (if there is CC evidence in the annotated papers at all).

Therefore, it would be very helpful, to have a way of differentiating between 'extracellular fibrils' and 'intracellular fibrils' in GO.

Could you please change the current 'GO:0043205 fibril', as it is now positioned in GO as a child of 'GO:0044420 extracellular matrix component', to 'extracellular fibril'? 

And could you please create a new term 'intracellular fibril', which would be a child of 'GO:0044424 intracellular part'? (If it is physiological, rather than only pathological...? @rebeccafoulger or @Pauldenny - do you have any comments or suggestions regarding this? Also, I am not sure how it should be related to 'GO:0097408 fibrillary inclusion'? ). If 'intracellular fibril' is normal, and the term becomes created, it could perhaps be defined as 'intracellular thioflavin-S-positive protein oligomers'. Please use DefX_Ref GOC:PARL.

Thanks,
Barbara

@RLovering 
@rebeccafoulger 
@Pauldenny

**Comment by ukemi** [comment]
@paolaroncaglia,

Can you have a look at this please? It seems we have fibril organization and extracellular fibril orgainzation, but we only have fibril. Do you think we should change the existing term to extracellular fibril based on its definition and then create the new generic fibril parent? From there we can fix the logical definitions of the organization terms.

-D

**Comment by dosumis** [comment]
Extracellular fibrils include naturally occurring collagen-based structures. I was skeptical of adding 'fibril' when Stan asked for it a few months back - partly because the structures he wanted it for were probably pathological.   It looks like these intracellular fibrils may be too.  Is this correct? Am I fighting a losing battle trying to keep pathological structures out of the GO?   If we are explicitly allowing them, shouldn't they at least be flagged in some way?  I think we should at least try to keep pathological and physiological structures and processes separable.

**Comment by dosumis** [comment]
If we do have an IC fibril, presumably it should exclude regular cytoskeletal fibers, but would include myofibril?  It may be hard to come up with a good definition that encompasses one but not the other, so we should at least have a guidance comment with the term.

**Comment by ukemi** [comment]
I agree with you completely and this is consistent with our policy since the beginning. But, we have organization terms for both fibril and extracellular fibril. The fibril organization term doesn't parallel the definition of fibril because it does not require the fibril to be extracellular. It seems to me that the extracellular fibril organization term should refer to our current component called fibril because those definitions align. I see the same issues with intracellular fibril as you point out above. It would need to be defined very carefully. I think that the example from this publication is indeed pathological.

**Comment by paolaroncaglia** [comment]
Yes, the example from @BarbaraCzub’s paper is pathological (the protein has a mutation known to be associated with Parkinson’s disease). So I’d recommend that it is not annotated to GO terms.

This said, there are 2 issues here:

1) Should we allow fibrils at all in GO?
In short: yes but with warnings.
In more detail: as @dosumis notes, “Extracellular fibrils include naturally occurring collagen-based structures”. Intracellular fibrils can occur naturally too, see e.g. the def of GO:1990000 ‘amyloid fibril formation’ “The generation of amyloid fibrils, insoluble fibrous protein aggregates exhibiting beta sheet structure, from proteins. An example of this is seen when human RIP1 and RIP3 kinases form a heterodimeric functional amyloid signaling complex (PMID:22817896).” (ok, I’ll admit I added that term ;-)). Also, “fragments of Pmel17 form a functional amyloid in vertebrate melanosomes [so, intracellularly] essential for melanin synthesis and deposition” (PMID:21148556). Plus, small fibrils may be ok in humans and only become pathological when they are too large; and some bacteria use amyloid fibrils physiologically (https://en.wikipedia.org/wiki/Amyloid). So fibrils can be physiological, and as such, they’d be fine in GO. However, the temptation to annotate pathological instances to fibril terms may be too real. I’d suggest adding curation guidance (as definition comments) to the parent fibril terms, ‘fibril organization’ and ‘fibril’, to warn curators against annotating pathological instances.

2) How should we rectify existing ‘fibril’ terms so they refer consistently and correctly to intra- or -extracellular environment?
Because yes I agree that the current situation is unsatisfactory.
I agree with @ukemi’s proposal (“…change the existing term to extracellular fibril based on its definition and then create the new generic fibril parent? From there we can fix the logical definitions of the organization terms.”). However, to play devil’s advocate, do we really need to differentiate between intra- and extracellular fibrils and their organization? Weren’t we discussing the same issue recently - that such a strategy is not sustainable and that we should use co-annotation/annotation extensions to specify the location? Is the (broad) process of organising fibrils radically different depending on their location? If we don’t know enough to accommodate all instances, we’d still be fine with generic terms that do not refer to location.

**Comment by dosumis** [comment]
Should we have the general terms at all (fibral, IC fibral, EC fibril) given how hard they are to define and that the various things that people call fibrils have very different compositions and structures?   I also suspect there is a random element in the terminology in the choice of filament, fiber (fibre) or fibril.  Can we just get by with specific fibril terms (myofibril, collagen fibril, amyloid fibril etc).

**Comment by dosumis** [comment]
An alternative: we have a general term 'supramolecular fiber':  Covering any fiber-shaped cellular component with an indeterminate number of components? 

This would cover cytoskeletal filaments; ECM fibrils such as collagen fibrils microfibrils; amyloid fibrils; myofibrils.

Note almost [everything annotated directly or indirectly to the current fibril term (with experimental evidence)](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0043205&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal) is a microfibril component.

**Comment by paolaroncaglia** [comment]
Placing all fibers/fibrils/you name them under 'supramolecular fiber' as @dosumis suggests (and creating the relevant organization term) would work for me. Wow, that'd be a really nice clean-up :-)

**Comment by ukemi** [comment]
@vanaukenk

I think we have a nice solution here. I propose that for now we move the current fiber term under supramolecular fiber. Then, we create a new supramolecular fiber organization term: 'cellular process' and results_in_organization_of some 'supramolecular fiber'. I'm not sure why the other cellular component organization terms have a genus of 'cellular component organization' seems that the more generic 'cellular process' should give all the correct inferences based on the definition of the parent (cellular component organization='cellular process' and results_in_organization_of some 'cellular component'). 

I will then move the current fibril term to be a child of supramolecular fiber. At the next annotation call, I will ask the gene annotators to please move all of their annotations to 'fibril', 'fibril organization' and 'extracellular fibril organization' to a more specific terms. We can then merge all these terms into the parent and make them narrow synonyms. I think that's legit. Once that is done, I will search for all of the various fibers and fibrils that are scattered about the ontology and move them all to be children of supramolecular fiber. How does this sound? Here is a quick list culled from a basic AMIGO search. What about chromatin or chromosomes?

GO:0071808	satellite fibril
GO:0005583	fibrillar collagen trimer
GO:0005726	perichromatin fibrils
GO:0097408	fibrillary inclusion
GO:0098652	collagen type VII anchoring fibril
GO:0098648	collagen anchoring fibril
GO:0098643	banded collagen fibril
GO:0001651	dense fibrillar component
GO:0001650	fibrillar center
GO:0043205	fibril
GO:0097426	glial filament
GO:0097419	Pick body
GO:0097416	Lewy body-like hyaline inclusion
GO:0097415	cortical Lewy body
GO:0097414	classical Lewy body
GO:0097409	glial cytoplasmic inclusion
GO:0001527	microfibril
GO:0016363	nuclear matrix
GO:0005706	polytene chromosome ectopic fiber
GO:0001725	stress fiber
GO:0099513	polymeric cytoskeletal fiber
GO:0099512	supramolecular fiber
GO:0071953	elastic fiber
GO:0030485	smooth muscle contractile fiber
GO:1990031	pinceau fiber
GO:1990032	parallel fiber
GO:0001520	outer dense fiber
GO:0098522	neuromuscular junction of skeletal muscle fiber
GO:0097539	ciliary transition fiber
GO:0097471	mossy fiber rosette
GO:0097457	hippocampal mossy fiber
GO:0070852	cell body fiber
GO:0098033	icosahedral viral capsid, neck fiber
GO:0098032	icosahedral viral capsid, collar fiber
GO:0098024	virus tail, fiber
GO:0098022	viral capsid, fiber
GO:0044449	contractile fiber part
GO:0044299	C-fiber
GO:0032123	deep fiber
GO:0044302	dentate gyrus mossy fiber
GO:0044301	climbing fiber
GO:0044300	cerebellar mossy fiber
GO:0043292	contractile fiber
GO:0035686	sperm fibrous sheath
GO:0031594	neuromuscular junction
GO:0071808	satellite fibril
GO:0030016	myofibril
GO:0036379	myofilament
GO:0000242	pericentriolar material
GO:0030486	smooth muscle dense body
GO:0042383	sarcolemma
GO:0061618	sublamina densa
GO:0098521	inhibitory neuromuscular junction
GO:0098520	excitatory neuromuscular junction
GO:0097721	ciliary vesicle
GO:0097546	ciliary base
GO:0097537	Y-shaped link
GO:0097482	muscle cell postsynaptic density
GO:0097228	sperm principal piece
GO:0097225	sperm midpiece
GO:0098025	virus tail, baseplate
GO:0098774	curli
GO:0098723	skeletal muscle myofibril
GO:0098643	banded collagen fibril
GO:0044614	nuclear pore cytoplasmic filaments
GO:0020031	polar ring of apical complex
GO:0020010	conoid
GO:0031673	H zone

**Comment by RLovering** [comment]
Hi

from QuickGO it looks like you might only need to write a couple of emails:
fibril: 7 AgBase, 2 Parkinsons, 8 MGI, 2 UniProt, rest GOC or Ensembl
fibril organization: 2 CACOA, 1 MGI (plus Ensembl)
extracellular fibril organization: 3 AgBase, 5 BHF, 21 MGI, 2 RGD, 10 UniProt, 4 Zfin, rest GOC or Ensembl

however some of the terms you have pulled out don't look like they should be fibrils e.g. muscle cell postsynaptic density?

Ruth

**Comment by paolaroncaglia** [comment]
Thanks @ukemi. Just a quick note, some of the terms from the AmiGO search are false positives (e.g. ciliary vesicle), but I’m sure you noticed already.
I see that @RLovering  just wrote to the same extent…

**Comment by paolaroncaglia** [comment]
As for chromatin and chromosomes: definitely not the latter, they don't resemble fibres to me ;-)
Chromatin is proteins + DNA (not nucleotides) while supramolecular fiber, atm, is proteins and/or protein complexes. Yes, I know we might change that, but possibly not...

**Comment by ukemi** [comment]
Yup. This was just a basic AmiGO search with the strings fibril and fiber. I will check each one.

**Comment by ukemi** [comment]
The outlined plan above was agreed upon during the annotation call.

**Comment by dosumis** [comment]
Patterns:
supramolecular fiber
EquiavalentTo: 'supramolecular complex' that bearer_of some [fiber shaped](http://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002309)

For auto-classification rely on the differentium: 
SubClassOf: bearer_of some [fiber shaped](http://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002309)
+ a class path up to  'supramolecular complex'

**Comment by ukemi** [comment]
I moved fibril to be an is_a child of supramolecular fiber. I made mircrofibril a child of both fibril and extracellular matrix component. The next step is to request the reannotation:

fibril: 7 AgBase, 2 Parkinsons, 8 MGI, 2 UniProt, rest GOC or Ensembl
fibril organization: 2 CACOA, 1 MGI (plus Ensembl)
extracellular fibril organization: 3 AgBase, 5 BHF, 21 MGI, 2 RGD, 10 UniProt, 4 Zfin, rest GOC or Ensembl

**Comment by ukemi** [comment]
I have fixed the MGI annotations. I have looked at some of the others and it seems reasonable that we should add a term called 'fibronectin fibril' and its organization term. It is gene-product centric, but is distinct in the literature.
@RLovering can you have someone check the BHF and Parkinson annotations? They seemed quite pathological to me.

**Comment by ukemi** [comment]
Added:

 [Term]
+id: GO:0061800
+name: fibronectin fibril
+namespace: cellular_component
+def: "A supramolecular fiber formed from fibronectin molecules. The fibrils are 5 to 25nm in diameter and can form branched meshworks." [GOC:dph, PMID:20690820]
+is_a: GO:0044420 ! extracellular matrix component
+is_a: GO:0099512 ! supramolecular fiber
+created_by: dph
+creation_date: 2016-10-24T14:04:21Z

**Comment by BarbaraCzub** [comment]
I have reviewed the two GO:0043205 fibril annotations created by ParkinsonsUK-UCL. 
![screen shot 2016-11-25 at 12 20 14](https://cloud.githubusercontent.com/assets/16541096/20625218/c82ec56c-b309-11e6-9765-136691e9b821.png)

Re: PMID:23507046
I am not going to delete the annotation created from PMID:23507046, as this paper suggests that the role of SNCA in fibrils in physiological, not pathological, as it has a role in anti-oxidant protective processes. The authors conclude:

"Taken together, the physiological function of α-synuclein and its amyloidogenesis can be understood with respect to the anti-oxidative GPX-1 system including glutathione turnover. Therefore, it can be considered that the mutual effects between α-synuclein and GPX-1 would contribute to strengthen the cellular defense against toxic insults; as an activator of cellular GPX-1, α-synuclein improves the enzyme's antioxidant activity by removing toxic H2O2 with concomitant formation of GSSG, and the resulting α-synuclein-GPX-1 complex along with GSSG eradicates the toxic oligomers of α-synuclein by facilitating the _innocuous_ amyloid fibril formation [1]."


PMID:17222866
I am also tempted not to remove the GO:0043205 fibril annotation created from PMID:17222866. Although the authors test several SNCA mutants (in addition to wild type), their findings provide evidence _against_ their hypothesis 'that fibrillized synuclein is necessary for yeast toxicity.' The authors conclude:

"In conclusion, it seems simplest and most consistent with the data to proceed with the hypothesis that non-fibrillar synuclein mediates toxicity. However, if fibrillization is necessary for toxicity then it is not sufficient because proteins with similar fibrillization rates had very different toxicities (Fig. 4). We also conclude that the non-toxic nature of A30P cannot be explained by its slow fibrillization; other sequences (e.g., V49E/Q79R, β-synuclein) that are much slower fibrillizers were more toxic (Fig. 4)."


Therefore, I think it is reasonable to keep both these GO:0043205 fibril annotations, even though they had been created for SNCA.

@RLovering would you agree?

**Comment by RLovering** [comment]
Hi
I think that these annotations should be kept. It seems to me that a decision about when a fibril is toxic is still under debate and it is not clear to me whether multimeric α-synuclein can be considered a fibril. certainly according to PMID: 25246573 α-synuclein promotes SNARE complex assembly at the presynaptic plasma membrane in its multimeric membrane-bound state (not in the monomer state).
But I would suggest adding an alert that should evidence come to light confirming that fibrils are always toxic abnormal structures then these annotations would need to be removed

**Comment by BarbaraCzub** [comment]
Thanks @RLovering , I've added the alerts, as you suggested.

**Comment by ukemi** [comment]
OK, but be aware that the term will still be merged as outlined above.

**Comment by ukemi** [comment]
One modification of the above plan. It makes more sense to just change the current fibril organization term to supramolecular fiber organization, rather than to create a new term and then merge the existing term into the new term. The extracellular term will still require a merge I think.

**Comment by ukemi** [comment]
As a first step. I removed the extracellular relationships and the logical definitions of fibril organization and extracellular fibril organization because they will become inconsistent when the merge happens.

**Comment by ukemi** [comment]
Merged extracellular fibril organization into fibril organization.

**Comment by ukemi** [comment]
Step 2.

Renamed and modified the definitions of fibril organization and regulation of fibril organization terms to be supramolecular fiber organization and regulation of supramolecular fiber organization terms.

**Comment by ukemi** [comment]
Merged fibril into supramolecular fiber and moved contractile fiber as a type. That was the only one that I was reasonably sure fit the definition and wasn't already a child. For the viral capsid fiber, I wasn't sure if it fit the definition of a supramolecular fiber, but I moved a couple of the capsid fibers under the general capsid fiber parent.
