### ISSUE TITLE
ntr: GTPase motor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12641]
I can say that something is a motor activity, or a GTPase motor activity, but I can't  say

"GTPase motor activity" (even though various types of GTPase motor terms exist)

Can this be added. Standard def and parents.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061791
+name: GTPase motor activity
+namespace: molecular_function
+def: "Catalysis of the generation of force resulting either in movement along a microfilament or microtubule, or in torque resulting in membrane scission, coupled to the hydrolysis of GTP." [GOC:dph, GOC:vw]
+is_a: GO:0003774 ! motor activity
+is_a: GO:0003924 ! GTPase activity
+created_by: dph
+creation_date: 2016-09-09T13:17:29Z
