### ISSUE TITLE
NTR:EGF repeat binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12648]
Could I request:
"EGF repeat binding"
-child of: GO:0005515 protein domain specific binding 

Def:
"Interacting selectively and non-covalently with Epidermal Growth Factor (EGF) repeats"
Synonyms: 
Epidermal growth factor domain binding, Epidermal Growth Factor repeat binding
Examples:
PMID: 25155514 
PMID:25700513

**Comment by ukemi** [comment]
[Term]
+id: GO:0061788
+name: EGF repeat binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with Epidermal Growth Factor (EGF) repeats." [GOC:25700513, GOC:dph, PMID:25155514]
+synonym: "Epidermal growth factor domain binding" BROAD [GOC:dph]
+synonym: "Epidermal Growth Factor repeat binding" RELATED [GOC:dph]
+is_a: GO:0019904 ! protein domain specific binding
+created_by: dph
+creation_date: 2016-09-08T15:22:28Z
