### ISSUE TITLE
OTR: logical definitions for autophagy terms

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12642]
(This is a placeholder)
Stemming from our discussion https://docs.google.com/document/d/1gtICfH3YQpnKbWqx2XI4JP5wlfp-6HxzWIQ1xFa8l9g/edit?ts=57cd86e9#
We will record our proposal here
NOTE: we'll need to run our proposal by some experts. Paul could take care of this when we're ready.
@ukemi @Pauldenny @marcfeuermann @RLovering

**Comment by Pauldenny** [comment]
Attempt at definition of beginning of autophagy?

A process that begins with the selection of excess, damaged or redundant cytoplasmic parts; allows for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure for cell differentiation and ends with the disassembly and digestion of the constituents.

Clumsy perhaps? But somewhere to start.

**Comment by paolaroncaglia** [comment]
As added to agenda for tomorrow's call:
‘selection’ is a bit vague in GO speak, what could we replace it with? Also, should we quote ‘cell differentiation’ as an example in the def? “A process that begins with the [selection] of excess, damaged or redundant cytoplasmic parts; allows for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure (including towards cell differentiation); and ends with the disassembly and digestion of constituents.”

**Comment by ukemi** [comment]
I agree that the vagueness makes me uncomfortable. I think we need to have a mechanism for all of the steps. Speak tomorrow.

**Comment by ukemi** [comment]
Added logical defs to a few terms. Reviewed all terms with Marc and Ruth.
