### ISSUE TITLE
NTR: conidium development

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12653]
"Development" term related to GO:0048315 conidium formation. 

"conidium development"
Proposed definition: "The process in which the specific outcome is the formation of a fully mature, normal, viable conidium."
xref: FAO:0000024 conidium

If it is okay to have both a development and a formation term for fungal structures, then I'll proceed with additional NTRs.

Thanks,
Diane

**Comment by ukemi** [comment]
Hi Diane,

We currently have 'conidium formation' defined as: Formation of asexual, nonmotile spores in fungi, by conversion of hyphal elements or arising from specialized sporogenous cells.

I'm not sure how this differs from the term you are suggesting. The current term is logically defined as an anatomical structure formation that results in the formation of some conidium, where conidium is cross-referenced to CL0000599. 

It would be more consistent with the current ontology to define the development terms as:

The biological process whose specific outcome is the progression of a conidium from its formation to its mature state.

Then conidium formation would be part of conidium development. 

This differs quite a bit from how we usually handle cells. The normal representation of cells is to have a differentiation term where one cell becomes committed to becoming a different kind of cell and then that cell develops (very reminiscent of the definition of the formation term above). I assume these cells are very different?

-David

**Comment by dianeoinglis** [comment]
Right! The "formation" term does imply that form of a conidium is produced. A "development" term would specify that the conidium develops into its fully mature and viable state. Mutants that do not properly assemble the spore cell wall would be considered defective in "conidium development."

The term "differentiation" is applied to two different processes, unfortunately. I have been wanting to clarify this issue. I wonder if "differentiated cell formation" would be more accurate for differentiated fungal cells. More often, the differentiated cell is formed from another cell-type, unlike B-cells that actually do start out as a pre-B cell and change over time. A conidium is produced as a conidium by sporogenous cells. Conidia are formed as conidia. "Differentiation" is very often applied to fungi but does not meet the current definition of "differentiation" and is a different process, in my opinion. If you agree, I'll request "differentiated cell formation" or similar.

**Comment by ukemi** [comment]
Hi Diane,

'Differentiated cell formation' is really confusing to me.

Will this work? 

conidium development- The process whose specific outcome is the progression of conidium over time, from its formation to the mature structure. A conidium is an asexual, nonmotile spore formed by higher fungi; conidia are usually made from the side or tip of specialized sporogenous cells and do not form by progressive cleavage of the cytoplasm.

conidium formation- Formation of asexual, nonmotile spores in fungi, by conversion of hyphal elements or arising from specialized sporogenous cells. (This would be part of conidium development via the morphogenesis term). 

Then you could add the other parts of the developmental program such as spore cell wall organization as other parts of conidium development. You could also subclassify those with other intermediates such as other morphogenesis terms or maturation terms as you see fit. 

If in the future, you decide to describe the steps that somehow instruct the conidium to be different from the sporogenous cell as it is formed, we can add a differentiation term and a fate commitment term.

-D

**Comment by dianeoinglis** [comment]
These term definitions look great to me..

**Comment by ukemi** [comment]
[Term]
+id: GO:0061794
+name: conidium development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of conidium over time, from its formation to the mature structure. A conidium is an asexual, nonmotile spore formed by higher fungi; conidia are usually made from the side or tip of specialized sporogenous cells and do not form by progressive cleavage of the cytoplasm." [GOC:dph]
+is_a: GO:0048468 ! cell development
+intersection_of: GO:0008150 ! biological_process
+intersection_of: results_in_development_of CL:0000599 ! conidium
+intersection_of: results_in_development_of FAO:0000024 ! conidium
+created_by: dph
+creation_date: 2016-09-17T09:53:51Z
