### ISSUE TITLE
Can we use "directly inhibits" and "directly activates" in extensions?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12657]
Can we use "directly inhibits" and "directly activates" in extensions to describe the relationship between molecular functions?.
I know it has been discussed and we can use them in LEGO. I'm not sure if they have been "ratified" for use as annotation extensions in GAFS...

Thanks

VAl

**Comment by paolaroncaglia** [comment]
@cmungall , @dosumis 
Could you comment on Val's question please? Thanks.

**Comment by dosumis** [comment]
Hi Val,

This is documented in the [annotation extensions repo doc folder](https://github.com/geneontology/annotation_extensions/tree/master/doc) - auto-generated from gorel.owl

 regulates, directly_regulates  + +ve & -ve versions of each are currently allowed, but directly_activates and directly_inhibits are not (yet).  

I can easily add them, but would like to improve documentation a bit too.

The definitions for these in RO suck - e.g. see [directly activates](http://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002406)

For now, I can add a GO usage statement (in gorel.owl).  Does this sound reasonable:

directly_activates: "Use this to relate two molecular functions, A & B, where function A positively regulates function B via direct binding or modification of the gene product or complex carrying out function B."

Val: does this fit your intention?  @cmungall, @ukemi - are you happy with this?  I think it is OK to be narrower than the RO def as it is meant as guidance for GO and so doesn't cover all possible uses.  If both you're all happy, I'll go ahead and add. (BTW - does CANTO consume gorel.owl for relations?  If not it probably should).

Chris: It would be nice to tighten up the RO def too.  I've been sketching common logic defs but struggling.

**Comment by mah11** [comment]
just noticed that this should go on the annotation extensions tracker - https://github.com/geneontology/annotation_extensions/issues

**Comment by dosumis** [comment]
This issue was moved to geneontology/annotation_extensions#70
