### ISSUE TITLE
NTR: retrograde trans-synaptic signaling by neuropeptide (and regulation term)

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12656]
Suggestion of new terms for PMID:19448629.

Summary: Synaptotagmin-IV (Syt4) inhibits BDNF release at the postsynapse, which then acts as a retrograde signal to alter presynaptic vesicle release. 

**For annotation of BDNF:**
retrograde trans-synaptic signaling by neuropeptide ; GO:NEW
is_a: trans-synaptic signaling by neuropeptide ; GO:0099540
is_a: retrograde trans-synaptic signaling ; GO:0098917
Cell-cell signaling from postsynapse to presynapse, mediated by a peptide ligand crossing the synaptic cleft. [GOC:bf, GOC:PARL, PMID:19448629]
intersection: trans-synaptic signaling by neuropeptide ; GO:0099540
has_end_location: pre synapse (GO:0098793)
has_start_location: postsynapse (GO:0098794)
NB: The intersections in this part aren't fully consistent (some have a broader genus and include a 'mediated_by' statement) but all get to the same point.

**For annotation of Syt4:**
regulation of retrograde trans-synaptic signaling ; GO:NEW
regulation of retrograde trans-synaptic signaling by neuropeptide ; GO:NEW
[GOC:bf, GOC:PARL, PMID:19448629]

Would like the input of @Pimmelorus @ftwkoopmans @BarbaraCzub since Pim had been annotating this paper too, and terms would be useful for Synapse work.

Thank you!

**Comment by dosumis** [comment]
Added: 'retrograde trans-synaptic signaling by neuropeptide' ; GO:0099082 as requested.  The regulation terms can be added using TG.

(Note the difference in patterns is deliberate.  There is no available grouping term for soluble gas in ChEBI and so a more precise genus has to be asserted)

**Comment by rebeccafoulger** [comment]
Thanks,

Could I have the 'modulating synaptic transmission' variation too please David:
retrograde trans-synaptic signaling by neuropeptide, modulating synaptic transmission

So I can get the full picture- thank you!!

**Comment by BarbaraCzub** [comment]
Thank you, Rebecca, for creating these new terms. I am sure we will use them in future Synapse annotations (or at least the non-regulation term, as Noctua is to be the primary tool for capturing the annotations, so 'regulation' relations rather than 'regulation' GO terms will be used).
Thanks!

**Comment by dosumis** [comment]
> Could I have the 'modulating synaptic transmission' variation too please David:
retrograde trans-synaptic signaling by neuropeptide, modulating synaptic transmission

Done.  (although may not commit until tomorrow as not ready to release other edits in branch).

> I am sure we will use them in future Synapse annotations (or at least the non-regulation term, as Noctua is to be the primary tool for capturing the annotations, so 'regulation' relations rather than 'regulation' GO terms will be used).

I think it will still be useful to have the regulation terms in the ontology even if you don't annotate to them directly.  Annotations these will be automatically generated from LEGO by inference and released as GAF files.

**Comment by BarbaraCzub** [comment]
Thank you, David, for clarifying this!

**Comment by dosumis** [comment]
Waiting to hear from Birgit on https://github.com/geneontology/go-ontology/issues/12620.  Have just given her a nudge.

**Comment by bmeldal** [comment]
@dosumis I'm not clear about what you are asking me in relation to this ticket.

**Comment by dosumis** [comment]
Just needed to clear up #12620 before doing commits related to this ticket (#12656). You answer on #12620 is perfect.  No comment needed here.   I'll go ahead an commit.

**Comment by BarbaraCzub** [comment]
Hi @dosumis 
I was going to update Rebecca's annotations, but I don't think the term GO:0099083 (retrograde trans-synaptic signaling by neuropeptide, modulating synaptic transmission) has been committed yet? I can only find the parent: GO:0099082 (retrograde trans-synaptic signaling by neuropeptide) and its only currently existing children are the regulation terms.
Barbara

**Comment by dosumis** [comment]
Sorry.  Still stuck in my branch edit file.  I’ll get to it either today or tomorrow.

**Comment by BarbaraCzub** [comment]
Thanks, David. This is not urgent. Just needed to make sure that I was searching for the right GO term/ID!
