### ISSUE TITLE
optic lobe placode formation

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12652]
The definition of this term looks like a confused mix of vertebrate optic placode and insect optic _lobe_ placode.

"optic lobe placode formation"
definition "Establishment of the optic placode, a thickened area of densely packed ectoderm cells directly overlying the optic vesicle in the early embryo. In Drosophila, for example, the placode appears in the dorsolateral region of the head in late stage 11 embryos and is the precursor to the larval visual system."^^xsd:string

First sentence  is vertebrate (it even says optic placode) - optic vesicle is not an insect struc.  

Should probably be split, but this will require some related work in Uberon see obophenotype/uberon#135

**Comment by ukemi** [comment]
It looks like it was historically meant to be the fly structure because it had a sensu. It only has four fly annotations. Just tighten up the definition to make it unambiguous?

**Comment by dosumis** [comment]
FBbt has evolved since the original term was made.  See: ['visual primordium'](http://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00001059).   Might be best to simplify representation in GO - we at least need general terms for optic/visual primordium formation and development linked to a general primordium term in Uberon.    The workflow for these things should really be to get stuff right in Uberon and then define they GO terms logically using the Uberon terms.

**Comment by ukemi** [comment]
--The workflow for these things should really be to get stuff right in Uberon and then define they --GO terms logically using the Uberon terms. 

Yup. Note we do have 'optic placode formation' (GO:0001743):  anatomical structure formation involved in morphogenesis AND results_in_formation_of SOME 'eye primordium'. Seems like that is not necessary and sufficient.

**Comment by cmungall** [comment]
Here is the relevant part of uberon. The ones marked yellow are insect-specific (and are easier to edit, they are managed in a separate repo: https://github.com/obophenotype/insect-anatomy-ontology)

![Uploading olp.png…]()

it all goes up to a generic primordium, but at the moment is disconnected from the placode hierarchy.

it may be an idea to give some of the insect-specific ones less generic sounding labels, eg

```
[Term]
id: UBERON:6001059
name: visual primordium
xref: FBbt:00001059
synonym: "P2 VisSys" RELATED [FBC:DOS]
synonym: "optic lobe placode" RELATED []
synonym: "optic lobe primordium" RELATED []
is_a: UBERON:0001048 ! primordium
is_a: UBERON:6025991 ! anterior ectoderm derivative
relationship: develops_from UBERON:6005434 ! visual anlage
relationship: part_of UBERON:0000922 ! embryo
```

**Comment by paolaroncaglia** [comment]
Hi @dosumis , I'm assigning this to you if that's ok, thanks.

**Comment by dosumis** [comment]
Not too hard to come up with some abstract classes for ectodermal placodes &  primordia of some generic structure types.  But juggling GO and Uberon in their current states is making my head spin...  What I though was a simple definition issue is turning into a mini-project...

**Comment by raymond91125** [comment]
GO:0001748 ! optic lobe placode development 7 annotations, all drosophila
GO:0001744 ! optic lobe placode formation 4 annotations, all drosophila
GO:0001743 ! optic placode formation 14 experimental annotations, all vertebrate
GO:0046619 ! optic placode formation involved in camera-type eye formation 13 experimental annotations, all vertebrate

However, Drosophila literature seems to use both "optic lobe placode" and "optic placode" interchangeably. [https://pubmed.ncbi.nlm.nih.gov/26970623/; https://pubmed.ncbi.nlm.nih.gov/31213980/; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6554424/; https://pubmed.ncbi.nlm.nih.gov/26970623/; https://pubmed.ncbi.nlm.nih.gov/31213980; https://pubmed.ncbi.nlm.nih.gov/10357938/]

We can merge "optic lobe placode formation" with "optic placode formation" and make the term more generic. Or we can fix the definition of "optic lobe placode formation/development" to make them truly arthropod specific.

In Uberon import, I cannot find "visual primordium" or terms that represent both camera and compound developing eye.

**Comment by pgaudet** [comment]
@hattrill 

Are you OK with the proposal: 
>We can merge "optic lobe placode formation" with "optic placode formation" and make the term more generic
? 

Thanks, Pascale

**Comment by hattrill** [comment]
Yes, I am ok with that, I don't see any issues with the parentage. The thing that is a bit jarring is that we have this GO:0001748 ! optic lobe placode development term hanging on a limb, when I think that really formation is part of development.

(Definition for the dev term begins with 'The process whose specific outcome is the progression of the optic placode over time, from its formation to the mature structure...'

![Screenshot 2021-04-29 at 12 22 47](https://user-images.githubusercontent.com/11865746/116543351-ad18e880-a8e5-11eb-8bf4-14151a9de1f1.png)

So, the alternative: "Or we can fix the definition of "optic lobe placode formation/development" to make them truly arthropod specific" might be a better fix.

I think that I will have to revisit the papers to have a look at the original intentions and look over a few papers to see how the conservation of processes works over species. 

I am going to tag @Clare72 on this one, as she is our ontologist.

**Comment by raymond91125** [comment]
For Drosophila, optic lobe placode / optic placode (not in FBbt, but in literature) are all synonyms of visual primordium FBbt:00001059 / UBERON:6001059.
For vertebrates, lens placode UBERON:0003073 is synonymous with optic placode
I suggest GO uses these distinct names to disambiguate such that:
GO:0001748 ! optic lobe placode development 7 annotations, all drosophila ->visual primordium development
GO:0001744 ! optic lobe placode formation 4 annotations, all drosophila ->visual primordium formation
GO:0001743 ! optic placode formation 14 experimental annotations, all vertebrate ->lens placode formation
GO:0046619 ! optic placode formation involved in camera-type eye formation 13 experimental annotations, all vertebrate ->lens placode formation
And add taxon restrictions and logical definitions accordingly.
