### ISSUE TITLE
Regulation terms for GO:0042775

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12651]
Hello,

I have just attempted to request regulation terms for 'GO:0042775 mitochondrial ATP synthesis coupled electron transport' via TermGenie, but the tool seems to be unresponsive.

I tried logging in using two different browsers: Safari (which I normally use) and Chrome, and I am able to log in, but then everything freezes on the first page (screenshot attached), and I am not able to select any templates.
![screen shot 2016-09-09 at 13 16 02](https://cloud.githubusercontent.com/assets/16541096/18386529/9b4ced64-768f-11e6-99e6-7d99ac6f483e.png)

I need the positive regulation term to annotate Figure 3 from PMID:23707074.

Could you please look into this issue and let me know, when TermGenie is back in action, or, if the new regulation terms become created independently of TermGenie in the meantime, could you please assign the DefX_Refs: GOC:PARL-UCL and GOC:BC?

Thank you,
Barbara

@RLovering

**Comment by ukemi** [comment]
Hi Barbara,

I made all the regulation terms via TermGenie.

-David
