### ISSUE TITLE
MP GO:0071851 mitotic G1 cell cycle arrest in response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12666]
Needs negative regulation of mitotic cell cycle

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071851#term=ancchart

**Comment by tberardini** [comment]
"Needs negative regulation of mitotic cell cycle"

Needs **link to** negative regulation of mitotic cell cycle?  Is_a or part_of?

Is it this term that needs the parentage or the parent term, 'mitotic G1 cell cycle arrest'?

**Comment by ValWood** [comment]
Looking at the ancestor chart,

cell cycle arrest is_a negative regulation of cell cycle.

so, the missing link is

mitotic cell cycle arrest is_a negative regulation of mitotic cell cycle

Does that work?

**Comment by tberardini** [comment]
Yes, that should do it.  I'll fix later today.

**Comment by tberardini** [comment]
+is_a: GO:0045930 ! negative regulation of mitotic cell cycle

Done!
