### ISSUE TITLE
New term for LEM domain

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#12664]
Dear All,
Would it be possible to create a new child term for a binding domain called LEM domain (parent will be GO:0019904 protein domain specific binding)?

The LEM domain (for lamina-associated polypeptide, emerin, MAN1 domain) is present in a group of nuclear proteins that bind chromatin through interaction of the LEM motif with the conserved DNA crosslinking protein, barrier-to-autointegration factor (BAF).

PMID:22399800 is one of the publication where they showed its involvement in protein interaction. There is also a description of this domain in InterPro (https://www.ebi.ac.uk/interpro/entry/IPR003887).

Please let me know if you need more information.

Thank you for your help,

Rossana

**Comment by paolaroncaglia** [comment]
Hi @rozaru ,
I added GO:0097726 LEM domain binding, it's ready to use. The full ontology stanza is below for reference. Thanks,
Paola

 [Term]
+id: GO:0097726
+name: LEM domain binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a LEM domain. The LEM domain (for lamina-associated polypeptide, emerin, MAN1 domain) is present in a group of nuclear proteins that bind chromatin through interaction of the LEM motif with the conserved DNA crosslinking protein, barrier-to-autointegration factor (BAF)." [GOC:rz, InterPro:IPR003887, PMID:22399800]
+synonym: "lamina-associated polypeptide, emerin, MAN1 domain binding" EXACT []
+synonym: "LAP2, emerin, MAN1 domain binding" EXACT []
+is_a: GO:0019904 ! protein domain specific binding
