### ISSUE TITLE
Rename "thrombin receptor activity" to "thrombin-activated receptor activity" and change def

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12669]
Hello, 
Two things: 
1. The term "thrombin receptor activity (GO:0015057)" should be renamed "thrombin-activated receptor activity": 

In fact these receptors are *cleaved* by thrombin, which exposes a hexameric sequence on the receptor itself, and the receptor is self-activated. See
   https://en.wikipedia.org/wiki/Thrombin_receptor
   http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2874842/

2. The definition should be changed to 
"G-protein-coupled receptor that is activated by cleavage by thrombin, which exposes a tethered ligand corresponding to the new N-terminus, which binds to the receptor and activates it."

 This only affects two entries (zebra fish f2r (ZDB-GENE-060526-30) and human F2R (P25116)), which were annotated correctly according to the new proposed definition and names. 

Thanks, Pascale

**Comment by tberardini** [comment]
Edits done as requested.  I also edited the related terms, 'thrombin receptor signaling pathway' and all of its regulation children.
