### ISSUE TITLE
New term autophagic cellular component disassembly

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12662]
Hi

I was thinking about the proteins that are present in the lysosome and are responsible for protein, lipid etc catabolism and I think that these proteins should be annotated to the GO term 'autophagy' and it's more specific types of autophagy child terms (e.g. mitophagy).

However, the term autophagy doesn't really capture the fact that the enzymes are responsible in a way for the 'execution' phase of autophagy. Looking at the apoptosis domain I think it would be good to be able to identify these proteins as different from those proteins involved in targeting an organelle for autophagy (I don't think we have a term for this?). I guess this would be equivalent to the signalling aspect of apoptosis. So perhaps a term is needed for this?

Anyway in the meantime, if the destruction of an organelle by the lysosome is considered to be part of the autophagic process then I think this new terms would be helpful: autophagic cellular component disassembly. 

GO:0006914 autophagy
part_of new term autophagic cellular component disassembly
Definition: A process that results in the breakdown of a cellular componentthat takes place in a autophagosome.

GO:0022411 cellular component disassembly
is_a new term autophagic cellular component disassembly

I am assuming that the specific types of autophagy would not need specific disassembly terms because using the AE field we would create 
Protein 1: mitophagy
Protein 1: autophagic cellular component disassembly AE part_of mitophagy

I also think some of the specific autophagy terms should be child terms of:
GO:1903008 organelle disassembly
is_a GO:0034517 ribophagy
is_a GO:0000425 macropexophagh
is_a GO:0000423 macromitophagy
is_a GO:0000422 mitophagy
although maybe some of these are appropriate if the whole organelle isn't disassembled.

Thanks

Ruth

@ukemi @paolaroncaglia @BarbaraCzub @Pauldenny

**Comment by marcfeuermann** [comment]
Hi Ruth,
It's true that we focused our work on the formation of the autophagosomes and the targeting of molecules and organelles to autophagosomes and lysosomes, but not on the degradation by lysosomal enzymes itself. Again it is a question of where we think is the end of the process. The degradation is clearly part of the process...  it's indeed the "execution" phase. My concern is that the lysosomal enzymes are not autophagy-specific, but as they are also involved in autophagic degradation... so... yes I think it's a good idea to create the term "autophagic cellular component disassembly". I agree not to create a specific term for every type of cellular component. Could this term also be used for proteins ?
There is one precision I would like to add to the definition of the new term: degradation occurs in lysosomes after maturation of autophagosome via fusion with lysosomes, not in autophagosomes as they are defined in GO.
The hierarchy of the related terms seems okay for me.
I hope this will be helpful
Best regards,
Marc.

**Comment by RLovering** [comment]
Thanks Marc

as some of the autophagic child terms do not involve the autophagosome (e.g. mitophagy by induced vacuole formation) I guess we need to be careful how this is defined. 
Possible new term:
autophagic cellular component disassembly
Definition: A execution phase of autophagy involves the breakdown of the membrane-bound macromolecular constituent targeted for degradation. This process may occur in a lysosome following the fusion of the membrane-bound macromolecular target with the lysosome. 

Feels a bit clumsy, improvements welcome

Best

Ruth

**Comment by paolaroncaglia** [comment]
Hi @RLovering, @marcfeuermann and all,

Thanks for your thoughts on this.
I like the idea of autophagy having an execution phase similarly to apoptosis. I haven’t had a chance yet to reflect on how exactly to break down the autophagic process - but this is in fact the aim of a ticket on logical definitions for autophagy terms that we opened during the last autophagy call https://github.com/geneontology/go-ontology/issues/12642 and that is assigned to @ukemi. I’m assigning him this one too.
Two quick suggestions though, if we do go ahead with creating ‘autophagic cellular component disassembly’ (something I’m not entirely comfortable with, but as I said I haven’t had time to ponder well):
1) Reciprocal links should be in place, i.e.
autophagic cellular component disassembly part_of autophagy
as well as
autophagy has_part autophagic cellular component disassembly (or even ends_with…)
2) We’d need to be very careful with the logical def. for ‘autophagic cellular component disassembly’ itself.

Thanks,

Paola

**Comment by ukemi** [comment]
Paola will make has part relations between the specific types of autophagy and the disassembly terms. On the conference call this morning we decided that this is the best way to proceed since it would account for a necessary step in the autophagy process, but would also account for cases where cellular components are recycled.
