### ISSUE TITLE
NTR: regulation of cytosolic cAMP concentration

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#12667]
Hello, 

I would like to request a new term: regulation of cytosolic cAMP concentration. 

I am asking for this because I have a paper which addition of a hormone to cells alters the levels of cAMP, however it is not clear if it is an increase in production of cAMP or a decrease in cAMP metabolism. 

We have an equivalent term in the ontology for cytosolic calcium (GO:0051480 regulation of cytosolic calcium ion concentration) and I would like a new term similar to this for cAMP.

Best,

George Georghiou
EMBL-EBI UniProt-GOA

**Comment by tberardini** [comment]
Please consider annotating to the term 'regulation of cAMP metabolic process', http://amigo.geneontology.org/amigo/term/GO:0030814.  This term encompasses the regulation of both cAMP biosynthesis as well as cAMP catabolism.  

The calcium term that you cite is a child of 'cellular calcium ion homeostasis'.  
http://amigo.geneontology.org/amigo/term/GO:0051480
Definition: Any process involved in the maintenance of an internal steady state of calcium ions within the cytosol of a cell or between the cytosol and its surroundings.
If the process in your paper has to do with the homeostasis of cAMP, we will consider adding the new term.

**Comment by ValWood** [comment]
Also, I'm not sure but I *think* the concentration terms might be  specifically for when  there is a different level/concentration maintained  in different cellular compartments...
if this was not mis- remembered it might be worth adding a comment to the terms...
v

**Comment by dosumis** [comment]
The cellular homeostasis terms are very odd and should probably go.   The important thing here is that Ca2+ and cAMP are second messengers - regulation of their cytosolic concentration is a critical step in signal transduction and its regulation.  Annotating to regulation of cAMP metabolism would miss that point.

@ggeorghiou - can you post a PMID for the paper?

**Comment by tberardini** [comment]
@dosumis : are you suggesting adding the term, named as requested but with different parentage, and reviewing/updating/removing all of the terms falling under 'cellular ion homeostasis' or perhaps even higher up, 'cellular homeostasis'?  That's a rather big chunk of work.

**Comment by ggeorghiou** [comment]
@dosumis Not a problem. The PMID is 3131169. Specifically I was looking to capture the effect of GHRH stimulation of pituitary cells and the increase in cAMP levels. The paper does not clearly define a mechanism by which this occurs, whether there is increased cAMP production or if cAMP catabolism has decreased.

**Comment by dosumis** [comment]
> @dosumis : are you suggesting adding the term, named as requested but with different parentage, and reviewing/updating/removing all of the terms falling under 'cellular ion homeostasis' or perhaps even higher up, 'cellular homeostasis'? That's a rather big chunk of work.

This branch is broken:  all regulation of cytosolic concentration is treated as homeostasis, which is clearly wrong.  Look at the children of 'regulation of cytosolic calcium ion concentration' for examples.   Fixing this for the whole branch is clearly hard, but I don't think this should stop us adding any regulation of levels term that are not homeostasis - given that we have lots of cases of this already.

> @dosumis Not a problem. The PMID is 3131169. Specifically I was looking to capture the effect of GHRH stimulation of pituitary cells and the increase in cAMP levels. The paper does not clearly define a mechanism by which this occurs, whether there is increased cAMP production or if cAMP catabolism has decreased.

Thanks.  Odd to be doing such an old paper:  we now know the mechanism to be via GPCR\->adenyl cyclase: ttps://en.wikipedia.org/wiki/Growth_hormone%E2%80%93releasing_hormone#Receptor

What's important is that more detailed annotations are compatible with this annotation.  In this case we have ['adenylate cyclase-activating G-protein coupled receptor signaling pathway'](http://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007189).  I think we need a route from this to the new positive regulation of cytoplasmic cAMP levels term.  This is a general issue for sig trans pathways acting via second messengers.  Note - I also think these regulation of levels terms will be important to have for LEGO.

**Comment by ValWood** [comment]
homeostasis terms have always been a problem....

**Comment by deustp01** [comment]
Jumping in with two sort of gratuitous comments.
First, practically, this thread raises the issue of how much effort can be afforded to salvage the annotation of an old experimental result that apparently has been superseded by more recent work that has provided the missing mechanical details.
Second, abstractly, my hunch (could probably be fleshed out) is that "homeostasis" is useful when applied to processes that maintain a steady state in the face of environmental perturbations, like "blood glucose homeostasis" in a mammal. But when a property of a system, like the local concentration of a second messenger, is sharply altered to transmit a signal, "second messenger homeostasis" doesn't really work.

**Comment by dosumis** [comment]
> On Sep 20, 2016, at 2:51 PM, deustp01 <notifications@github.com> wrote:
> 
> Jumping in with two sort of gratuitous comments.
> First, practically, this thread raises the issue of how much effort can be afforded to salvage the annotation of an old experimental result that apparently has been superseded by more recent work that has provided the missing mechanical details.
> 

Yep.
> Second, abstractly, my hunch (could probably be fleshed out) is that "homeostasis" is useful when applied to processes that maintain a steady state in the face of environmental perturbations, like "blood glucose homeostasis" in a mammal. But when a property of a system, like the local concentration of a second messenger, is sharply altered to transmit a signal, "second messenger homeostasis" doesn't really work
> 
Strongly agree.

**Comment by tberardini** [comment]
In light of the discussion that has followed the provision of the paper to be used for annotation, I propose that we not add the term requested as a more specific term has been suggested.  If there is a strong desire to overhaul 'homeostasis' and children, we should open a separate github ticket to specifically address that topic. Alternatively, if there are glaring issues with specific 'homeostasis' child terms, we could address only those for now (also in a separate GH ticket) and leave a larger overhaul for another time.

Thoughts on that proposal?

**Comment by ValWood** [comment]
I think that's  what the decision has been in the past ;)
https://github.com/geneontology/go-ontology/issues/10140

**Comment by ValWood** [comment]
https://sourceforge.net/p/geneontology/ontology-requests/9902/

**Comment by tberardini** [comment]
Holy smokes!  That's some ancient history.

**Comment by ValWood** [comment]
Always the same outcome.  Uggh, leave till later ;)

**Comment by tberardini** [comment]
@ggeorghiou : Please let us know if you need clarification on the alternative terms to use for annotation or the reasoning behind the push to NOT use 'regulation of cytosolic cAMP concentration'.  I am going to close this issue now.
