### ISSUE TITLE
NTR (then obsolete): triplex DNA unwinding

### ISSUE THREAD

**Issue by Andrestutz** [geneontology/go-ontology#12668]
Hello,

I would like to propose the creation of a new term: 

For DDX11 (Q96FC9):

NTR: triplex DNA unwinding:
The process by which a three-stranded D-loop DNA is unwound or 'melted'.

...As a child of "GO:0032392 DNA geometric change", i.e. sibling of GO:0044806 G-quadruplex DNA unwinding, with a similar definition , "The process by which a three-stranded D-loop DNA is unwound or 'melted'". 
 
This structure correspond to an early intermediate of homologous 
recombination that is formed when a DNA strand from one chromatid invades the 
sister chromatid DNA duplex to anneal with its complementary strand.

See in PubMed=26503245, Figure 3 C

Add more:
See in PubMed=26503245, in Figure 4 B
NTR: regulation of triplex DNA unwinding
NTR: positive regulation of triplex  DNA unwinding
NTR: negative regulation of triplex  DNA unwinding

Thanks a lot,

Andre Stutz

**Comment by pgaudet** [comment]
Hello, 

Is the triplex a 'model', or a real structure in vivo ? If it's a model, you should annotate to what the triplet is modeling. 

Pascale

**Comment by tberardini** [comment]
[Term]
+id: GO:0090703
+name: triplex DNA unwinding
+namespace: biological_process
+def: "The process by which a three-stranded D-loop DNA is unwound or 'melted'." [PMID:26503245]
+is_a: GO:0032392 ! DNA geometric change
+created_by: tanyaberardini
+creation_date: 2016-09-20T16:37:15Z

**Comment by tberardini** [comment]
I'll create the regulation terms after the core term has been propagated to the file that TermGenie uses.

**Comment by ValWood** [comment]
Hi,

Does this term differ from"strand displacement" ?
(plus it isn't really unwinding of a triplex is it? its unwinding of the Duplex part of the D loop?)

Strand dislplacement could probably be better defined!

Val

**Comment by tberardini** [comment]
@Andrestutz, please respond to @ValWood's comment.  I guess I'll hold off on creating the regulation terms.

**Comment by Andrestutz** [comment]
Hi Val,

I agree that "triplex DNA unwinding" is confusing, suggesting that
DDX11 acts to unwind a triple DNA helix which is apparently not the
case. This term should therefore be removed, sorry for that. 

In fact I missed the term "strand displacement" which effectively describes
more precisely author's aim, that is the displacement of an invading 
single-stranded DNA (represented in figure 3C by the 5'-single-stranded tail 
oligo) complementary to one strand of a DNA duplex molecule 
(represented in figure 3C by oligos DL1 and DL2). 
This experiment reproduces what happen during homologous recombination.

I hope I'm correct as I'm not an expert in this field.

best regards

**Comment by tberardini** [comment]
Term made obsolete.

**Comment by ValWood** [comment]
I'm not sure ;)
strand displacement is defined

Perhaps 
GO:0000733 DNA strand renaturation
The identification and annealing of complementary base pairs in single-strand DNA.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0036310#term=ancchart
is more correct?

strand invasion
Is defined:
The process in which the nucleoprotein complex (composed of the broken single-strand DNA and the recombinase)....
So it is specifically referring to  a recombinase...

I'm also not an expert, but I think the ontology is quite confusing around the area of "annealing" 

https://github.com/geneontology/go-ontology/issues/12539

and it is likely that the 'activity' being referred to in the "stand in invasion term" is the helicase  activity of the recombinase
https://github.com/geneontology/go-ontology/issues/12465
