### ISSUE TITLE
NTR: mycelium reproductive competence

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12660]
NTR: "mycelium reproductive competence"
Def: A maturation process when an organism acquires the ability to reproduce. In fungi, reproductive competence only occurs in a population of filamentous cells that form a mycelium.
Synonym: "mycelium developmental competence"
PMID: 23864594 

This process is referred to as both "reproductive competence" and "developmental competence." I lean towards using "reproductive competence" with "developmental competence" to distinguish it from "development" which is ambiguous and can be interpreted in different ways.

**Comment by dianeoinglis** [comment]
You know, reproductive competence is a trait or requirement for all organisms that I can think of. Perhaps that suggests that creation of the parent term "reproductive competence" seems appropriate.

**Comment by paolaroncaglia** [comment]
Note for self: also see http://wiki.geneontology.org/index.php/Ontology_meeting_2016-09-22#FAO_update and https://github.com/obophenotype/cell-ontology/issues/447

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis ,

As @tberardini suggested in https://github.com/geneontology/go-ontology/issues/12613#issuecomment-252768617, 'acquisition of mycelium reproductive competence' or similar would be more appropriate. 'competence' per se is a trait, not a process. I'll come back to this ticket.

**Comment by paolaroncaglia** [comment]
@tberardini
I see that we already have GO:0010049 ‘acquisition of reproductive competence’ defined as “The process in which a plant acquires the ability to respond to a floral inductive signal.” (dbxref: GOC:tair_curators). No taxon rules applied to the term itself, but inherits the following from its ancestor ‘multicellular organismal process’:
only in Eukaryota
never in Saccharomyces cerevisiae 
never in Schizosaccharomyces pombe
No children, no annotation whatsoever. No mappings either, but used by NBO (weird). 
Do we need this term for plants at all? 
If yes, or if we’re not sure, I’ll edit it so it refers to plants in the label ('acquisition of plant reproductive competence’) and in taxon rules, then add a generic parent 'acquisition of reproductive competence', and a sibling for 'acquisition of mycelium reproductive competence' restricted to Fungi. 
If not, I could make the existing term the generic one (and remove the never in Fungi rules), and add a mycelium-related child restricted to Fungi.
Although I’m not sure what processes the generic parent should encompass. With such broad terms, ideally we’d like to add starts_with and ends_with.
Maybe I could just fix GO:0010049 so it refers to plants, and add a sibling for Fungi…

**Comment by tberardini** [comment]
_Maybe I could just fix GO:0010049 so it refers to plants, and add a sibling for Fungi…_
This one.  +1

**Comment by dianeoinglis** [comment]
I saw the term GO: 0010049. that uses a general term for a specific organism. I agree with creating the plant-specific term "acquisition of plant reproductive competence" as a sibling to "acquisition of mycelium reproductive competence." The definition of the existing term GO:0010049 "acquisition of reproductive competence" is the perfect parental term to the plant and fungal/bacterial terms. Maybe this change in definition to be more generic is ok since the term has not been used for annotation. Note that mycelium formation occurs in some bacterial species so it a microbial-specific term, not fungal-specific. While"competence" may be a trait, the process here is "acquisition" that involves changes in physiology, metabolism, etc in young vegetatively growing cells that acquire the ability to reproduce in a non-vegetative manner.

**Comment by paolaroncaglia** [comment]
To start with, I edited GO:0010049 ‘acquisition of reproductive competence’ to refer to plants.

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis,

To keep things simple, I added this term, so it’s ready to use as necessary:

 [Term]
+id: GO:0097737
+name: acquisition of mycelium reproductive competence
+namespace: biological_process
+def: "A maturation process by which an organism acquires the ability to reproduce. In fungi, reproductive competence only occurs in a population of filamentous cells that form a mycelium." [GOC:di, PMID:23864594]
+synonym: "mycelium developmental competence" RELATED []
+is_a: GO:0032502 ! developmental process
+relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria

The is_a parent could probably be made more specific, but I’m not sure what the correct one would be. The ‘sibling’ term GO:0010049 ‘acquisition of plant reproductive competence’ is_a ‘post-embryonic development’, which would not go well for asexual reproduction of Bacteria or Fungi. Possibly, this case falls among the problematic ones here https://github.com/geneontology/go-ontology/issues/12614. I’ll close this ticket for now; if you’d like to suggest a different parent, please re-open it, or make a new one. Thanks.
