### ISSUE TITLE
NTR: histone H3-K79 dimethylation 

### ISSUE THREAD

**Issue by hbye** [geneontology/go-ontology#12661]
Hello,

Please may I request the new term "histone H3-K79 dimethylation"? It will be the child term of "histone H3-K79 methylation" (GO:0034729). The new definition will be the following:

"The modification of histone H3 by addition of two methyl groups to lysine at position 79 of the histone."

This term is based on PMID: 27541139, figure 7. The regulation term for this process would be more appropriate, so this can be generated subsequently in Term Genie. This new term is similar to existing child terms for the GO terms Histone H3-K4 methylation (GO:0051568) and Histone H3-K9 methylation (GO:0051567).

Thanks you very much,
Hema

**Comment by paolaroncaglia** [comment]
Hi @hbye ,

Your new term is ready to use as GO:0097725 histone H3-K79 dimethylation. The full ontology stanza is below for your reference. Cheers,

Paola

 [Term]
+id: GO:0097725
+name: histone H3-K79 dimethylation
+namespace: biological_process
+def: "The modification of histone H3 by addition of two methyl groups to lysine at position 79 of the histone." [GOC:hbye, PMID:27541139]
+synonym: "histone H3 K79 dimethylation" EXACT []
+synonym: "histone lysine H3 K79 dimethylation" EXACT []
+is_a: GO:0018027 ! peptidyl-lysine dimethylation
+is_a: GO:0034729 ! histone H3-K79 methylation
