### ISSUE TITLE
gerontoplast stroma as new term request

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#12673]
What do you think about the term "gerontoplast stroma". There is a "chloroplast stroma" and gerontoplast. It is the location of 1.3.7.12. Thanks, Marion

**Comment by tberardini** [comment]
Hi Marion, 

We can add this.  Please provide a reference (PMID) for this term.

**Comment by brendamg** [comment]
Hi Tanya, this term is used in PMID11212360. Chlorophyll breakdown in higher plants and algae.
Thank you.

**Comment by tberardini** [comment]
Added through TermGenie:

[Term]
id: GO:1905506
name: gerontoplast stroma
namespace: cellular_component
def: "Any plastid stroma that is part of a gerontoplast." [GO_REF:0000064, GOC:mag, GOC:TermGenie, PMID:11212360]
intersection_of: GO:0009532 ! plastid stroma
intersection_of: part_of GO:0034400 ! gerontoplast
created_by: tb
creation_date: 2016-09-27T20:01:34Z
