### ISSUE TITLE
relationships between receptor signalling activities

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12677]
Why is 
GO:0004675 transmembrane receptor protein serine/threonine kinase activity 
Def: Combining with a signal and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity by catalysis of the reaction: ATP protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate.

not a child of 
GO:0004702 receptor signaling protein serine/threonine kinase activity?
Def: Conveys a signal from an upstream receptor or intracellular signal transducer by catalysis of the reaction: ATP protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate.

Birgit

**Comment by dosumis** [comment]
Ugghh - what a horrible branch!

'receptor signaling protein serine/threonine kinase activity' is a subclass of:

rdfs:label "receptor signaling protein activity"
id "GO:0005057"
definition "Conveys a signal from an upstream receptor or intracellular signal transducer, converting the signal into a form where it can ultimately trigger a change in the state or activity of a cell."^^xsd:string
**comment "This term is intended for annotation of signal transducers that act directly or indirectly downstream of a receptor. For receptors themselves, consider annotating to the term 'receptor activity ; GO:0004872'."**

Note the comment.  

1. I agree this is a very confusingly named class (and branch).  Do you have any suggestions for a better name?   

'signaling protein activity, downstream of receptor'?
'signal transducer activity, downstream of receptor'?

2. It seems that everything in an signal transduction pathway that is not a receptor should be under this class, but this is not the case right now.  This is not a very sustainable situation.  

I can rename the classes and tidy up for now, but it might be worth considering making the hierarchy flatter here. e.g. It's probably enough to classify MAPK under signal transducer activity and kinase activity

**Comment by bmeldal** [comment]
Ah, thanks for the clarification! I definitely need the first one as my complex is a TM receptor!

Maybe that comment on the parent term needs to be propagated to the children as I didn't see it. As for renaming the signal transducer terms I have to refer that to someone who's more knowledgeable about this and knows what the community call it!

Birgit

**Comment by dosumis** [comment]
> As for renaming the signal transducer terms I have to refer that to someone who's more knowledgeable about this and knows what the community call it!

I'm sure they don't use the term 'receptor signaling protein activity'!  So my renames won't make things worse - and I should make meanings much clearer.  I'll go ahead and change.

Proposed formalization from #12339 : 

EquivalentTo: molecular_function 
that (regulated_by some 'signaling receptor activity')
and (part_of some 'signal transduction')

 @cmungall - any comments?

Not entirely confident in this.  Don't some receptors regulate their own activity

**Comment by bmeldal** [comment]
> Not entirely confident in this. Don't some receptors regulate their own activity

Not sure that matters for this ticket but yes, plenty of receptor autophosphorylate (usually in response to some trigger, physiological or through a ligand) which then activates them, or they phosphorylate another receptor subunit that activates the whole receptor complex.

**Comment by dosumis** [comment]
Matters for the formal def.  There's a danger that receptors in LEGO models would end up automatically annotated to this term.   

(Note: very little [direct annotation to 'receptor signaling protein activity' and its immediate subclasses](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=64%24019U019i019u01F102Iu&termUse=ancestor&relType=%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2CoriginalTermID%2CoriginalGOName%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal)

**Comment by dosumis** [comment]
Renamed classes in branch using pattern

signal transducer, downstream of receptor, with X activity
