### ISSUE TITLE
adaptive immune response

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#12671]
Dear GO annotators,
I am annotating the immune genes and would like to solicit your help to better define the adaptive immune response in GO.
Specifically:
1. I would suggest updating the definition of GO:0002250 adaptive immune response so that it encompasses both the primary and the secondary immune responses of adaptive immunity. I’d suggest quoting Roitt’s textbook of immunology (http://www.roitt.com/) for the definition: “Adaptive immune response is immunity mediated by lymphocytes and characterized by antigen specificity and memory. The first encounter with antigen elicits a primary immune response that is rather slow and not of great magnitude. T and B lymphocytes selected by antigen become activated and undergo clonal expansion. A fraction of antigen-reactive lymphocytes become memory cells, whereas others differentiate into effector cells. The memory cells generated during the primary response enable a much faster and stronger secondary immune response upon antigen rechallenge’’.
2. I feel there is a need to create two GO terms that would distinguish effector functions and immune memory, which as mentioned above are two distinct elements of the adaptive immune response. This is a request from immunologists involved in our project.
May I suggest creating the following GO terms:
GO:1990982: adaptive immune memory response (previously submitted by Sylvain)
definition: The immune response against a previously encountered antigen, being quicker and quantitatively better compared with the primary response. Quoting Zinkernagel in PMID:26831526
GO:xxx: adaptive immune effector response
definition: Cellular and humoral immune response that takes place during the effector phase of the adaptive immune response. In the case of B lymphocytes, the effector cells are the antibody-secreting plasma cells whereas for T-lymphocytes the effector cells may be T-helper cells, cytotoxic T-cells or regulatory T cells. Quoting Roitt’s textbook of immunology (http://www.roitt.com/)

Thank you in advance for your help,

Nevila Hyka-Nouspikel

**Comment by tberardini** [comment]
@paolaroncaglia @dosumis @ukemi @mcourtot : who is our go-to immunology person?  Please help.

**Comment by tberardini** [comment]
@addiehl - Thank for you taking a look next week when you have time.

**Comment by mcourtot** [comment]
See also https://github.com/geneontology/go-ontology/issues/12650

**Comment by tberardini** [comment]
@addiehl : could you look into this please?

**Comment by nnouspikel** [comment]
Hello,

Did you have a chance to review my request? We would like to implement these terms in our database now, so let me know please if there is anything you need from me to complete the process.

Many thanks for your help,

Nevila Hyka-Nouspikel


p.s. I wold suggest to refine the definition of the adaptive immune memory response as follows: 
definition: The immune response mediated by memory lymphocytes and directed against a previously encountered antigen, being quicker and quantitatively better compared with the primary response. Quoting Zinkernagel in PMID:26831526

**Comment by addiehl** [comment]
I will have a proposal by tomorrow based on recent reading I have been doing.
-- Alex

**Comment by nnouspikel** [comment]
Sounds very good. Thank you Alex.

**Comment by nnouspikel** [comment]
Hello Alex,
We have to implement the new terms in our database and need your help to finish the process as soon as possible. I believe creating these terms would benefit other immune-oriented projects. Also, please could you create the negative and positive regulation children for the new terms? Drop me an email if you need help with the definitions.
All the best,
Nevila

**Comment by tberardini** [comment]
@addiehl : Can you comment please or just let me know if you are too busy and I will find someone else to assist.

**Comment by nnouspikel** [comment]
Sure, please let me know. Thanks!

**Comment by addiehl** [comment]
I really am working on this.  Sorry for the delay.  This is a necessarily complex topic, and GO needs to be careful to represent immune processes properly across all species.

I will post something this afternoon or evening.
-- Alex

**Comment by addiehl** [comment]
My suggestions regarding this request are below, and in the attached term hierarchy.  I am happy to have further discussions regarding this branch of GO.  All references to cell types have been standardized to the labels used in the Cell Ontology.

1) GO:0002250 adaptive immune response has its current definition to accomodate the fact that adaptive immune responses appear to exist in species that do not possess lymphocytes, nor T cell receptors or immunoglobulins, but avail themselves of other types of immune receptors based on somatic diversification of germline elements.  See PMID:21084634, PMID:16979938, PMID:22907038, PMID:24727482, PMID:22224775, for some examples.

The current definition of GO:0002250 reads "An immune response based on directed amplification of specific receptors for antigen produced through a somatic diversification process, and allowing for enhanced response to subsequent exposures to the same antigen (immunological memory)."

The proposed new definition for GO:0002250 (from earlier in thread): "Adaptive immune response is immunity mediated by lymphocytes and characterized by antigen specificity and memory. The first encounter with antigen elicits a primary immune response that is rather slow and not of great magnitude. T and B lymphocytes selected by antigen become activated and undergo clonal expansion. A fraction of antigen-reactive lymphocytes become memory cells, whereas others differentiate into effector cells. The memory cells generated during the primary response enable a much faster and stronger secondary immune response upon antigen rechallenge"

The proposed definition is very specific for vertebrate adaptive immune responses, and does not take into account the lamprey and the non-vertebrate systems of adaptive immunity referenced above. The original definition includes as a defining element the role of somatic diversification of immune receptors which is central to all these systems of adaptive immunity, as well as the possibility of an enhanced secondary response. The proposed definition is too specific in mentioning T and B cells, and even memory cells.

Consequently, I would prefer to stick with something closer to the original definition, which I believe contains the key elements of what an adaptive immune response is.  The Gene Ontology is meant for annotation of all species, not just those that are most well studied.

However, probably a rewording of the definition for GO:0002250 is needed to emphasize the cellular nature of the adaptive immune response:  "An immune response mediated by cells expressing specific receptors for antigen produced through a somatic diversification process, and allowing for an enhanced secondary response to subsequent exposures to the same antigen (immunological memory)." GOC:mtg_15nov05, GO_REF:0000022, GOC:add, ISBN:0781735149

As a further compromise, I would propose modifying the definition of GO:0002460, 'adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains'.

Current definition of GO:0002460, "An immune response based on directed amplification of specific receptors for antigen produced through a somatic diversification process that includes somatic recombination of germline gene segments encoding immunoglobulin superfamily domains, and allowing for enhanced responses upon subsequent exposures to the same antigen (immunological memory). Recombined receptors for antigen encoded by immunoglobulin superfamily domains include T cell receptors and immunoglobulins (antibodies). An example of this is the adaptive immune response found in Mus musculus."

Suggested new definition for GO:0002460, "An immune response mediated by lymphocytes expressing specific receptors for antigen produced through a somatic diversification process that includes somatic recombination of germline gene segments encoding immunoglobulin superfamily domains. Recombined receptors for antigen encoded by immunoglobulin superfamily domains include T cell receptors and immunoglobulins (antibodies) produced by B cells. The first encounter with antigen elicits a primary immune response that is slow and not of great magnitude. T and B cells selected by antigen become activated and undergo clonal expansion. A fraction of antigen-reactive T and B cells become memory cells, whereas others differentiate into effector cells. The memory cells generated during the primary response enable a much faster and stronger secondary immune response upon subsequent exposures to the same antigen (immunological memory). An example of this is the adaptive immune response found in Mus musculus." GOC:add, ISBN:0781735149,
GOC:mtg_sensu, ISBN:1405196831

In line with this new definition for GO:0002460, the analogous term GO:0002459 'adaptive immune response based on somatic recombination of immune receptors built from leucine-rich repeat domains' should probably have its definition adjusted.

Current definition: "An immune response based on directed amplification of specific receptors for antigen produced through a somatic diversification process that includes somatic recombination of variable lymphocyte receptors (VLR) incorporating leucine-rich repeat (LRR) domains, and allowing for enhanced responses upon subsequent exposures to the same antigen (immunological memory). Examples of this process are found in jawless fish, including the lampreys (Petromyzontidae) and hagfishes (Myxinidae)."

Suggested definition: "An immune response mediated by lymphocytes expressing specific receptors for antigen produced through a somatic diversification process that includes somatic recombination of variable lymphocyte receptors (VLR) incorporating leucine-rich repeat (LRR) domains, and allowing for enhanced responses upon subsequent exposures to the same antigen (immunological memory). Examples of this process are found in jawless fish, including the lampreys (Petromyzontidae) and hagfishes (Myxinidae)." PMID:16373579, GOC:add, GOC:mtg_sensu


2) See attached hierarchy for placement of the following terms:

GO:NewTerm adaptive immune memory response
def: An immune response directed against a previously encountered antigen, being quicker and quantitatively better compared with the primary response. PMID:26831526, GOC:add

GO:NewTerm adaptive immune memory response involving T cells and B cells
def: An immune response mediated by reactivated memory T cells and B cells and directed against a previously encountered antigen, being quicker and quantitatively better compared with the primary response.  PMID:26831526, GOC:add

GO:NewTerm adaptive immune effector response
def: An adaptive immune response that involves one or more immune effector processes and takes place during the effector phase of the adaptive immune response. ISBN:1405196831, GOC:add

GO:NewTerm adaptive immune effector response involving T cells and B lineage cells
def: An adaptive immune effector response involving T cells and B lineage cells.  In the case of
B lineage cells, the effector cells are the antibody secreting plasma cells whereas for T cells the effector cells may be helper T cells or cytotoxic T cells. ISBN:1405196831, GOC:add

Note: Per the Cell Ontology, plasma cells are not a type of B cell per se, but are a type of B lineage cell that develops from a B cell.  This has been discussed in depth with Dr. Richard Scheuermann, noted B cell biologist, bioinformatician, and ontology expert, who insisted upon this distinction.

GO:NewTerm primary adaptive immune response
def: An adaptive immune response against an antigen not previously encountered by immune system. PMID:26831526, GOC:add

GO:NewTerm primary adaptive immune response involving T cells and B cells
def: An adaptive immune response mediated by naive T or B cells against an antigen not previously encountered by immune system. PMID:26831526, GOC:add


3) Other new terms related to memory

GO:NewTerm immunological memory process
Any process of the immune system that can contribute to the formation  of immunological memory or an
immune response based upon activation of immunological memory. PMID:26086132, PMID:26831526, GOC:add

GO:NewTerm innate immunity memory response
def: An immune response mediated by the innate immune system and directed against a previously encountered immunologic stimulus, being quicker and quantitatively better compared with the initial response to that stimulus. PMID:26086132, GOC:add

GO:NewTerm immunological memory formation process
def: Any immunological memory process that can contribute to the formation of immunological memory. PMID:26086132, PMID:26831526, GOC:add

-- Alex
[GO adaptive immune response and  memory.pdf](https://github.com/geneontology/go-ontology/files/580062/GO.adaptive.immune.response.and.memory.pdf)

**Comment by tberardini** [comment]
Thank you very much @addiehl .  @nnouspikel, please review.  If this is acceptable, I will implement the suggested changes.

**Comment by nnouspikel** [comment]
Hello, Thank you very much for carefully reviewing my request. I know it's a complex issue, but you did a great job. I agree with the new terms. I am happy that you are adding a new term for innate memory response as well. The immunology field is evolving fast and dogma are challenged, and it's good that GO terms get updated accordingly. Thank you again!
Please, could you add as child terms the positive and negative relations for each of them?
Have a good day,
Nevila

**Comment by nnouspikel** [comment]
One more comment: On second thought, I would suggest to remove 'involving T cells and B cells' in the adaptive terms. Although correct, it is probably not necessary to have them in the term itself, the definition is quite clear. 
Cheers,
Nevila

**Comment by addiehl** [comment]
Hi Nevila,
The reason I added the involving T cell and B cells for the terms 'adaptive immune memory response involving T cells and B cells', 'adaptive immune effector response involving T cells and B lineage cells', and 'primary adaptive immune response involving T cells and B cells', is because these are children of the more general terms 'adaptive immune memory response', 'adaptive immune effector response', and 'primary adaptive immune response', respectively.  While from a mainstream immunologist perspective, the general terms are perhaps unnecessary, I would like to have this layer of general terms to allow for annotation of gene products of non-canonical adaptive immune responses, such as those in invertebrates or lampreys.  I realize that this does make the graph even more complex, but these general terms will be needed at some point.

I chose to add '...involving T cells and B [lineage] cells' phrase to the labels of the more specific terms to make it clear these terms are about the specific involved in immune responses in highly-studied higher vertebrate immune systems such as those in humans or mice.

The alternative is to dispense with the more specific terms entirely, keeping only the general terms  'adaptive immune memory response', 'adaptive immune effector response', and 'primary adaptive immune response', with their definitions that specifically do not reference the cell types involved, and thus can be applied more broadly.  This alternative is okay by me, but I would prefer keeping the specific terms, because of their linkage to 'adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains' GO:0002460, which is the existing term for conventional adaptive immune responses involved T cells and B cells.

If you would like to suggest a different phrase than '...involving T cells and B [lineage] cells' or 'based on somatic recombination of immune receptors built from immunoglobulin superfamily domains' that makes it clear the terms refer to canonical higher vertebrate immune systems that rely upon T and B cells, that would be great, but I haven't come up with one myself.

Let me know what you think,
Alex

**Comment by nnouspikel** [comment]
Hi Alex,

Thank you for the clear explanation. I understand your concern and I 
agree to keep both the parent/generic terms: 'adaptive immune memory 
response', 'adaptive immune effector response' and 'primary adaptive 
immune response' and the specific terms  'involving T cells and B 
cells'. Our annotations are human centric, organized in three main 
modules: gene (Uniprot ID) – Function (GO ID) – Cell (CL ID). So, we 
don't need to have cells in the GO term. We will use the generic terms 
and the corresponding positive/negative relation terms 
(positive/negative regulation of the adaptive immune effector response).

Thank you very much for your help.

All the best,

Nevila

**Comment by addiehl** [comment]
I am in favor of having regulation terms, of course, but it's a bit boring to write them all out since they can  be created in an automated way.

**Comment by nnouspikel** [comment]
Thanks! Automated option sounds good.

**Comment by tberardini** [comment]
To do list:
- [ ] modify definition of GO:0002250
- [ ] modify definition of GO:0002260
- [ ] modify definition of GO:0002459
- [ ] GO:NewTerm adaptive immune memory response
- [ ] GO:NewTerm adaptive immune memory response involving T cells and B cells
- [ ] GO:NewTerm adaptive immune effector response
- [ ] GO:NewTerm adaptive immune effector response involving T cells and B lineage cells
- [ ] GO:NewTerm primary adaptive immune response
- [ ] GO:NewTerm primary adaptive immune response involving T cells and B cells
- [ ] GO:NewTerm immunological memory process
- [ ] GO:NewTerm innate immunity memory response
- [ ] GO:NewTerm immunological memory formation process

@nnouspikel : please clarify which of the terms should have regulation children.  All of the ones that don't have 'involving T cells and B cells'?

**Comment by nnouspikel** [comment]
Hello Tania,

At the moment, I would need the regulation children for the following terms:
GO:NewTerm adaptive immune memory response
GO:NewTerm adaptive immune effector response
GO:NewTerm innate immune memory response 

Many thanks for your help,

Nevila

**Comment by tberardini** [comment]
[Term]
+id: GO:0090713
+name: immunological memory process
+namespace: biological_process
+def: "Any process of the immune system that can contribute to the formation of immunological memory or an immune response based upon activation of immunological memory." [GOC:add, PMID:26086132, PMID:26831526]
+is_a: GO:0002376 ! immune system process
+relationship: part_of GO:0006955 ! immune response
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:20:30Z
+
+[Term]
+id: GO:0090714
+name: innate immunity memory response
+namespace: biological_process
+def: "An immune response mediated by the innate immune system and directed against a previously encountered immunologic stimulus, being quicker and quantitatively better compared with the initial response to that stimulus." [GOC:add, PMID:26086132]
+is_a: GO:0045087 ! innate immune response
+is_a: GO:0090713 ! immunological memory process
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:23:03Z
+
+[Term]
+id: GO:0090715
+name: immunological memory formation process
+namespace: biological_process
+def: "Any immunological memory process that can contribute to the formation of immunological memory." [GOC:add, PMID:26086132, PMID:26831526]
+is_a: GO:0090713 ! immunological memory process
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:25:47Z

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090716
+name: adaptive immune memory response
+namespace: biological_process
+def: "An immune response directed against a previously encountered antigen, being quicker and quantitatively better compared with the primary response." [GOC:add, PMID:26831526]
+is_a: GO:0002250 ! adaptive immune response
+is_a: GO:0090713 ! immunological memory process
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:32:42Z
+
+[Term]
+id: GO:0090717
+name: adaptive immune memory response involving T cells and B cells
+namespace: biological_process
+def: "An immune response mediated by reactivated memory T cells and B cells and directed against a previously encountered antigen, being quicker and quantitatively better compared with the primary response." [GOC:add, PMID:26831526]
+is_a: GO:0002460 ! adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains
+is_a: GO:0090716 ! adaptive immune memory response
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:35:19Z
+
+[Term]
+id: GO:0090718
+name: adaptive immune effector response
+namespace: biological_process
+def: "An adaptive immune response that involves one or more immune effector processes and takes place during the effector phase of the adaptive immune response." [GOC:add, ISBN:1405196831]
+is_a: GO:0002250 ! adaptive immune response
+relationship: has_part GO:0002252 ! immune effector process
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:37:26Z

@addiehl : is the has_part relationship above correct?  Or should it be the other way around
immune effector process has_part adaptive immune effector response ?

**Comment by tberardini** [comment]
[Term]
+id: GO:0090719
+name: adaptive immune effector response involving T cells and B lineage cells
+namespace: biological_process
+def: "An adaptive immune effector response involving T cells and B lineage cells. In the case of B lineage cells, the effector cells are the antibody secreting plasma cells whereas for T cells the effector cells may be helper T cells or cytotoxic T cells." [GOC:add, ISBN:1405196831]
+is_a: GO:0002460 ! adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains
+is_a: GO:0090718 ! adaptive immune effector response
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:43:26Z
+
+[Term]
+id: GO:0090720
+name: primary adaptive immune response
+namespace: biological_process
+def: "An adaptive immune response against an antigen not previously encountered by immune system." [GOC:add, PMID:26831526]
+is_a: GO:0002250 ! adaptive immune response
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:44:55Z
+
+[Term]
+id: GO:0090721
+name: primary adaptive immune response involving T cells and B cells
+namespace: biological_process
+def: "An adaptive immune response mediated by naive T or B cells against an antigen not previously encountered by immune system." [GOC:add, PMID:26831526]
+is_a: GO:0002460 ! adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains
+is_a: GO:0090720 ! primary adaptive immune response
+created_by: tanyaberardini
+creation_date: 2016-11-11T12:46:29Z

**Comment by tberardini** [comment]
ID: GO:1905674 Label: regulation of adaptive immune memory response
    ID: GO:1905675 Label: negative regulation of adaptive immune memory response
    ID: GO:1905676 Label: positive regulation of adaptive immune memory response
    ID: GO:1905677 Label: regulation of adaptive immune effector response
    ID: GO:1905678 Label: negative regulation of adaptive immune effector response
    ID: GO:1905679 Label: positive regulation of adaptive immune effector response
    ID: GO:1905680 Label: regulation of innate immunity memory response
    ID: GO:1905681 Label: negative regulation of innate immunity memory response
    ID: GO:1905682 Label: positive regulation of innate immunity memory response

**Comment by tberardini** [comment]
leaving ticket open until clarification by @addiehl:

>+id: GO:0090718
+name: adaptive immune effector response
+relationship: has_part GO:0002252 ! immune effector process
@addiehl : is the has_part relationship above correct? Or should it be the other way around
immune effector process has_part adaptive immune effector response ?

**Comment by nnouspikel** [comment]
Thank you so much! 
All the best,
Nevila

**Comment by tberardini** [comment]
I think the has_part relationship is correct.  Please reopen if I need to edit it.

**Comment by addiehl** [comment]
I think the has_part relationship is correct.

Thanks Tanya for putting these terms in.
-- Alex

**Comment by tberardini** [comment]
Sure thing, Alex.  Thanks very much for your thoughtful input on the terms and their relationships.
