### ISSUE TITLE
Query about "chromatin-templated microtubule nucleation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12678]
I am annotations some microtubule nucleation papers.
I have some suggestions to  correct some missing relationships (to follow)

but first, can anyone enlighten me on this term?

GO:0090223
Name    chromatin-templated microtubule nucleation
Ontology    Biological Process
Definition  The 'de novo' formation of a microtubule, in which tubulin heterodimers form metastable oligomeric aggregates from chromatin.

Is this really "a thing"?
It has i) no reference and II) no annotations. I can't find anything with a google search which indicates that chromatin can nucleate microtubules.

**Comment by ValWood** [comment]
David provided PMID:27145846

I had a scan and I'm still confused by this.
I don't think that the chromatin "templates" the microtubule. These are still MTOC's aren't they? This appear to be describing 'satellite" MTOC's to the SPB or centrosome?
These are still MTOCs, and by definition will still have a gamma tubulin complex at their core, and this  gamma tubulin is really providing the template for nucleation (not the chromatin per se)? Isn't it only that these satellite MTOCs are localized to the chromosome?

**Comment by dosumis** [comment]
Seems to have been added by Tanya based on a talk: https://github.com/geneontology/go-ontology/issues/6846#issuecomment-124779540  CC @tberardini

**Comment by tberardini** [comment]
My notes (!) from that meeting say that that talk was about:

Spindle-templated MT nucleation (mitotic spindle-templated MT nucleation)
(vs. centrosome-templated and chromatin-templated MT nucleation)

This recent paper might shed light:

**Comment by ValWood** [comment]
I'm not sure...I could only access the second paper immediately, but this seems like a phenotype (is this  what happens only after ablating gamma tubulin?)
Gamma tubulin is eukaryotically conserved and essential in fission yeast and budding yeast  and fly.

"Here, we performed live-cell microscopy of GFP-tubulin to examine spindle formation in Drosophila S2 cells after RNAi depletion of either γ-tubulin, a microtubule nucleating protein [8, or centrosomin, a protein that recruits γ-tubulin to the centrosome [7, 9]. In these RNAi-treated cells, we show that poorly focused bipolar spindles form through the self-organization of microtubules nucleated from chromosomes (a process involving γ-tubulin), as well as from other potential sites, and through the incorporation of microtubules from the preceding interphase network."

This doesn't appear to be a normal process?

**Comment by tberardini** [comment]
Paper looks free to me.  This might be the passage:

"To better understand the mechanism of spindle formation after γ-tubulin depletion, we performed live-cell imaging of GFP-tubulin-expressing cells. In cases where NEB was observed, microtubule formation from the chromosomal region was dramatically reduced or significantly delayed in comparison with wild-type and Cnn-RNAi-treated cells (Movie 4). This result, combined with our observation of spindle localization of γ-tubulin in Cnn-depleted cells, **suggests that γ-tubulin functions as a microtubule nucleator in the chromosome-mediated microtubule assembly pathway**. This finding indicates that γ-tubulin need not be anchored at the centrosome to stimulate microtubule nucleation. While this paper was in review, a similar conclusion was reached in mammalian cells on the basis of RNAi of a γ-tubulin-associated subunit [18."

**Comment by ValWood** [comment]
This seems to agree that all microtubule nucleation is gamma tubulin mediated?
Maybe the "templating" in the  term names is a bit misleading.
Perhaps the terms should just be
i) microtubule nucleation from X MTOC?

This similar in fission yeast, some  nuclear microtubules  are not nucleated by the SPB largely the past-anaphase array, but can possibly substitute when other MTOC's compromised, these chromosomal MTOCs seem to be similar (or even equivalent) to the eMTOC's. But they are all nucleated by gamma tubulin complex.

The gamma tubulin forms a template (nucleator) because it has a "tubulin like" component 
https://www.ncbi.nlm.nih.gov/pubmed/10854328 
(gamma tubulin). This was why I wondered about the term.....I was wondering how can the microtubule be templated from the chromosome, there must be some tubulin-like component to as as the template.

What do you think? It isn't used so it could stay as it is, but I suspect it won't be used as is because its a bit confusing at present.....

**Comment by tberardini** [comment]
@ValWood - all I know about this area comes from the brief read of a few papers.  I defer to your greater knowledge and experience.  Please suggest a course of action for the terms (merge all into one uber-class called ??? or something else and we'll edit to suit.

**Comment by ValWood** [comment]
I have done many papers on this recently, but I'll double check with a couple of experts about the situation in higher eukaryotes (or if anyone else might know can they pitch in?). From a brief scout around yesterday I couldn't find anything to suggest things were mechanistically different, and these refs didn't seem to diverge from that.

I'll do this in the next couple of days and then suggest revisions.

thanks!
val

**Comment by pfey03** [comment]
I asked a friend and MTOC/Spindle/tubulin expert Ralph Gräf and he said:
"yes there is MT nucleation at chromatin. It is dependent on RanGTP and requires several spindle assembly factors, e.g. aurora A, TPX2, Eg5, XMAP215..., many of which have orthologues in Dicty. MT nucleation at chromatin happens during spindle formation, which is not only initated at the centrosomes but also at chromosomes. There are many papers on acentrosomal spindle formation dealing about this issue. There are no data whether this also takes place in Dicty, but I would surprise me, if it were not the case."

**Comment by ValWood** [comment]
Hi Petra,

The question is not about where (... MTOC's  are known to exist in many places), but if any are not nucleated/templated by the gamma tubulin complex.
I think the existing terms conflate the "template" for nucleation with the "location of the MTOC"

Val

**Comment by pfey03** [comment]
Ah ok sorry Val, probably didn't read the whole thread carefully enough!

**Comment by ValWood** [comment]
Paper I was reading this week:

Inside of cells, the spatial and temporal organization of microtubules is governed by a diverse group of structures known as microtubule-organizing centers (MTOCs). **The common feature of all MTOCs is their ability to recruit γ-tubulin complexes (γ-TCs), which form a template for microtubule growth (Kollman et al., 2011).**
During mitosis, centrosomes (metazoans) or spindle pole bodies (SPBs; fungi) function as MTOCs, forming the poles of the mitotic spindle.

**Comment by ValWood** [comment]
see also

"mitotic spindle templated" and "chromatin templated" microtubule these appear to be "de novo"  without a MTOC machinery so it is not clear if separate terms are required to  "microtubule nucleation"...neither of these terms are used in annotation, even though the papers reporting them have been curated.

https://github.com/geneontology/go-ontology/issues/12680

**Comment by ValWood** [comment]
so closing
