### ISSUE TITLE
transforming growth factor beta (TGFbeta): cytokines and their receptors - missing terms

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12676]
1) 
We have 
GO:0070021 transforming growth factor beta1-type II receptor-type I receptor complex
but
TGFbetaR-1 and -2 (the receptors) also combine with TGFbeta2 and TGFbeta3 cytokines. I'm currently curating the whole set. Should we relax the above term or make a new parent and the -beta2 and -beta3 specific child terms? I'm happy with either but would prefer the least-explosive (in terms of terms) option.

2) 
There are a bunch of homotypic TGFbeta receptor dimers in GO and
GO:0038045 large latent transforming growth factor-beta complex (=the inactive cytokine dimer)
but the active TGFbeta cytokine dimers are missing (as far as I can see).
Unless I have missed them, can I request the cytokine dimer terms as well? (I'll supply the extra info!)

refs:
TGFbeta1 complexes:
PMID:20207738
PMID:8679613
TGFbeta3 complexes:
PMID:18243111 (also TGFbeta2 complexes)
PMID:11850637

Birgit

**Comment by pgaudet** [comment]
HI @bmeldal 
Can this proposal be more specific about which terms you want (and don't want)? 

Thanks, Pascale

**Comment by bmeldal** [comment]
According to annotations in UniProt and CP, the TGFbeta receptors do not exist as complexes unless they are bound by their ligands, the TGFbeta dimers.

e.g.
http://www.uniprot.org/uniprot/P36897
TGF-beta receptor type-1 (TGFBR1)
Transmembrane serine/threonine kinase forming with the TGF-beta type II serine/threonine kinase receptor, TGFBR2, the non-promiscuous receptor for the TGF-beta cytokines TGFB1, TGFB2 and TGFB3. Transduces the TGFB1, TGFB2 and TGFB3 signal from the cell surface to the cytoplasm and is thus regulating a plethora of physiological and pathological processes including cell cycle arrest in epithelial and hematopoietic cells, control of mesenchymal cell proliferation and differentiation, wound healing, extracellular matrix production, immunosuppression and carcinogenesis. The formation of the receptor complex composed of 2 TGFBR1 and 2 TGFBR2 molecules symmetrically bound to the cytokine dimer results in the phosphorylation and the activation of TGFBR1 by the constitutively active TGFBR2.

and
https://www.ebi.ac.uk/complexportal/complex/EBI-11896191
TGF-beta-1-TGFR complex (human)
Cytokine-receptor complex that plays an important role in embryogenesis, tissue development, cell proliferation, differentiation and maturation, immune regulation and carcinogenesis. Binding of TGFB1 (EBI-12501958) to its receptor subunits results in the phosphorylation of TGFBR1 on Thr185 & Thr186 by the constitutively active TGFBR2.

Altogether (in human) there are **3 types of TGFbeta ligands**, TGFB1, TGFB2 and TGFB3, that most likely form respective **homodimers**.
They are represented in GO by GO:0099126 transforming growth factor beta complex. I must have missed them in GO when I asked part 2 of the original ticket.
This bit is fine :)

Now to Part 1 of the original ticket:
There are **3 types of TFGbeta receptor proteins**, TGFBR1, TGFBR2 and TGFBR3. TGFBR1 & TGFBR2 are well described as **forming a 2:2:2 complex with the dimeric ligand** while little seems to be known about TGFBR3. It's barely annotated in UniProt and I didn't add it to the CP - I guess I didn't find any clear evidence.

In GO, they are represented by 

1. GO:0070020 | transforming growth factor beta1-type II receptor complex
A protein complex that consists of a dimeric transforming growth factor beta (TGF-beta) type II receptor bound to a TGF-beta1 dimer. 
So, this is 2xTGFBR2 : 2xTGFB1, which is incomplete according to the above UP and CP definitions.
- [ ] I would obsolete GO:0070020 and merge annotations to GO:0070021 (further comments below).

2. GO:0070021 | transforming growth factor beta1-type II receptor-type I receptor complex
A protein complex that is formed by the association of a ligand-bound TGF-beta type II receptor dimer with a TGF-beta type I receptor dimer. 
This is the complex described by UP and CP: 2xTGFB1 : 2xTGFBR1 : 2xTGFBR2. The name and def are a little tricky to understand. I think it is restricted to TGFB1 only, excluding binding with TGFB2 or TGFB3. But the def does not specify which ligand is included.
- [ ] I would rename: GO:0070021 | **transforming growth factor beta ligand-receptor complex**
"A protein complex that is formed by the association of a TGF-beta dimeric ligand with 2 molecules of each receptor molecule, TGF-beta type I receptor and TGF-beta type II receptor. The receptor molecules may form homo- or heterodimers but only once bound by the ligand." This will make it agnostic to whichever of the 3 ligands are binding.
- [ ] Synonyms:
TGF-beta ligand-receptor complex [EXACT]
TGFbeta ligand-receptor complex [EXACT]
TGFb ligand-receptor complex [EXACT]
and variant synonyms with beta1, beta-1, beta2, beta3 ... [narrow]

3. The following 3 terms describe the receptors as dimers but as mentioned above, I don't think they exist physiologically even though that's what the def says. I think they need obsoleting and annotations possibly merging into GO:0070021 | transforming growth factor beta1-type II receptor-type I receptor complex. 

- GO:0070022 | transforming growth factor beta receptor complex |  
A homodimeric receptor complex that consists of two TGF-beta receptor monomers. 
- GO:0070018 | transforming growth factor beta type I receptor homodimeric complex |  
A receptor complex that consists of two transforming growth factor beta (TGF-beta) type I receptor monomers. TGF-beta type I receptor dimers form in the presence or absence of ligand, and can associate with ligand-bound TGF-beta type II receptor dimers. 
- GO:0070019 | transforming growth factor beta type II receptor homodimeric complex
A receptor complex that consists of two transforming growth factor beta (TGF-beta) type II receptor monomers. TGF-beta type II receptor dimers form in the presence or absence of ligand, and upon ligand binding can associate with TGF-beta type I receptor dimers. 

I hope that makes sense.
Birgit

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 


   GO:0070022 | transforming growth factor beta receptor complex
   GO:0070020 | transforming growth factor beta1-type II receptor complex 
   GO:0070018 | transforming growth factor beta type I receptor homodimeric complex 
   GO:0070019 | transforming growth factor beta type II receptor homodimeric complex

The reason for obsoletion is that according to annotations in UniProt and ComplexPortal, the TGFbeta receptors do not exist as complexes unless they are bound by their ligands, the TGFbeta dimers. 

The term "GO:0070021 | transforming growth factor beta1-type II receptor-type I receptor complex” will be renamed "transforming growth factor beta ligand-receptor complex", and redefined as "A protein complex that is formed by the association of a TGF-beta dimeric ligand with 2 molecules of each receptor molecule, TGF-beta type I receptor and TGF-beta type II receptor. The receptor molecules may form homo- or heterodimers but only once bound by the ligand." This will make it agnostic to whichever of the 3 ligands are binding.


There are no annotations, no InterPro2GO mappings to this term; this term is not included in any subset(s)(slims). 
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/12676

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 24th, 2018. Unless objections are received by September 24th, 2018, we will assume that you agree to this change.

Thanks, Pascale
