### ISSUE TITLE
NTR: 3-demethylubiquinone-8 3-O-methyltransferase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12675]
Proposed definition: Catalysis of the reaction: S-adenosyl-L-methionine + 3-demethylubiquinone-8 = S-adenosyl-L-homocysteine + ubiquinone-8. 
Proposed parent: GO:0061542 - this one is the generic reaction with no prenyl tail length defined.  The term has three other children for the defined tail lengths, but the E. coli-specific term ( tail length of 8) is missing.

Thanks,
Ingrid

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/20815760/1e048f64-b817-11e6-9964-cf0046139de7.png)

**Comment by dosumis** [comment]
Sorry for the delay.

**Comment by keseler** [comment]
I still don't see the new term on the AmiGO site.  What is the GO ID?
Thanks,
Ingrid

**Comment by dosumis** [comment]
GO:0099119

Should be visible any day now.  Release pipelines are a bit slow at the moment.
