### ISSUE TITLE
parentage issues under microtubule nucleation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12679]
Current arrangement

GO:0007020 microtubule nucleation
has descendants
- GO:0051418 microtubule nucleation by microtubule organizing center
- GO:0030954 astral microtubule nucleation
- GO:0090221 mitotic spindle-templated microtubule nucleation
- GO:0090222 centrosome-templated microtubule nucleation
- GO:0090223 chromatin-templated microtubule nucleation
- [ ] 1). Astral microtubules  (cellular component)
  Astral microtubules are defined as  microtubules from the spindle poles
  (I am guessing that centrosomes also have astral microtubules?  so this probably needs fixing)
  When this is fixed could we have SPB specific terms too.
- [ ] 2) either way 
- GO:0030954 astral microtubules nucleation
- GO:0090221 mitotic spindle-templated microtubule nucleation
  GO:0090222 centrosome-templated microtubule nucleation
  are all is_a 
  GO:0051418 microtubule nucleation by microtubule organizing center

(in fact, do we know of any microtubule nucleation does not occur via a MTOC? I can't find one 
unless this is it...https://github.com/geneontology/go-ontology/issues/12678 )

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21682494/c4122b82-d34c-11e6-9679-d95b46e6a262.png)

Classification automated from classification under MOTC using pattern:

![image](https://cloud.githubusercontent.com/assets/112839/21682508/dc8c5a98-d34c-11e6-8ae1-68e647c87610.png)
