### ISSUE TITLE
taxon restriction problem and question

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12683]
We are  implementing various things using "ontology subsets" into Canto.

Firstly we only want to present terms to our users which don't have taxon restrictions.

This raised a question.

We have annotations to "lateral element" which is a descendent of "synaptonemal complex"
Synaptonemal complex is  GO:0000795	synaptonemal complex	never_in_taxon	4896	Schizosaccharomyces pombe

Shouldn't we get a Jenkins warning for this?

**Comment by dosumis** [comment]
Fixed the immediate cause of the problem.  Assigning to Chris for Jenkins question.

**Comment by ValWood** [comment]
we had no annotations to "lateral elelment" they are to "linear element"
so I'll close this.
