### ISSUE TITLE
GO term GO:0031297 (replication fork processing) Definition Issue

### ISSUE THREAD

**Issue by ethanclary143** [geneontology/go-ontology#12682]
When I look on QuickGO and AmiGO, the definition for the term GO:0031297 (replication fork processing) is "The process in which a DNA replication fork that has stalled is to a functional state and replication is restarted..." I believe that there is an error in this definition and it should read "The process in which a DNA replication fork that has stalled is **RESTORED** to a functional state and replication is restarted..."

**Comment by mah11** [comment]
also reported in #12626

**Comment by dosumis** [comment]
Fixed
