### ISSUE TITLE
small change / new term GO:1905482 child

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12686]
I recently requested
GO:1905482	cytoplasmic sequestering of protein involved in G2 DNA damage checkpoint

but I meant to request
cytoplasmic sequestering of protein involved in  mitotic G2 DNA damage checkpoint

I don't think I can do the child with templates (only with free-form which is unavaiable).

Can it be added?

Thanks

Val

**Comment by mah11** [comment]
The TG "involved in" template will work for this - put "cytoplasmic sequestering of protein" in the first text box, and "mitotic G2 DNA damage checkpoint" in the second.

**Comment by ValWood** [comment]
Oh yes, I though I couldn't do this for more children one I had created this involved in term.

Anyway, I added, but upin submission I got a message saying the 
 this but upon submission (very final step) I got  a message saying the service is unavailable. So...I'm not sure whether that   get in or not. Will wait to hear before I resubmit if necessary.

**Comment by ValWood** [comment]
Done
GO:1905507 Label: cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint
