### ISSUE TITLE
TPV URGENT GO:0044236 multicellular organism metabolic process is a single....

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12689]
Currently 
GO:0044236 multicellular organism metabolic process
is a descendant of
 GO:0044710 single-organism metabolic process

see:

![tpv](https://cloud.githubusercontent.com/assets/7359272/18989495/39358e1c-8704-11e6-8cd9-e7d300b0dacb.jpg)

**Comment by mah11** [comment]
Why is this a TPV? I am a single organism, and I'm multicellular ...

**Comment by ValWood** [comment]
ignore!
