### ISSUE TITLE
true path violation lateral element/ synaptonemal complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12684]
Pombe does not have (canonical) synaptonemal complex, but it does have lateral elements.
Lateral element should not be part_of synaptonemal complex (If anything it's the other way around?.. synaptonemal complex is part_of the 'lateral elements', or there should be some grouping term).

**Comment by dosumis** [comment]
Hi Val,  I've deleted the part relationship.  Can you suggest a Pombe reference for lateral elements?

**Comment by dosumis** [comment]
Added comment rdfs:comment "In species that have a synaptonemal complex, the lateral elements are part of this complex.  S.pombe is an example of a species that lacks a  (canonical) synaptonemal complex, but still has lateral elements."

Closing ticket.  Still interested to add ref though.

**Comment by ValWood** [comment]
Sorry I made a mistake.
Pombe does  not form synaptonemal complex 

The fission yeast Schizosaccharomyces pombe does not form tripartite synaptonemal complexes during meiotic prophase, but axial core-like structures (linear elements).
https://www.ncbi.nlm.nih.gov/pubmed/8536990

and
Fission yeast does not form synaptonemal complexes in meiotic prophase. Instead, linear elements appear that resemble the axial cores of other eukaryotes. They have been proposed to be minimal structures necessary for proper meiotic chromosome functions
https://www.ncbi.nlm.nih.gov/pubmed/12665553

Probably GO needs a "general" term to describe "linear element involved in synapsis" and "synaptonemal complex" which pombe does not have can be a descendant of this.....?

val

**Comment by ValWood** [comment]
Sorry meant to say I was confusing "lateral element GO:0000800" and "linear element  GO:0030998

**Comment by ValWood** [comment]
I think we need to convince the pombe community that it is OK to call these "synaptonemal complexes" .....working on it.....

**Comment by dosumis** [comment]
Fixed.  See  #12693.
