### ISSUE TITLE
NTR: Transforming growth factor beta complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12685]
Name: Transforming growth factor beta complex
Def: A protein complex acting as ligand of the transforming growth factor beta receptor complex. Activates the canonical SMAD-dependent TGF-beta signaling cascade. Typically a homodimer of any of the TFGbeta isoforms. The precursor of TGFB proteins is cleaved into mature TGFB and the latency-associated peptide (LAP), which remains non-covalently linked to mature TGFB rendering it inactive. TGFB is activated by dimerisation and dissociation of the LAP.
Synonyms: 
TGFbeta complex [exact]
TGFB complex [exact]
TGF-beta complex [exact]
TGFbeta dimer [exact]
TGFB dimer [exact]
TGF-beta dimer [exact]
TGFbeta1 complex [narrow]
TGFB1 complex [narrow]
TGF-beta-1 complex [narrow]
TGFbeta2 complex [narrow]
TGFB2 complex [narrow]
TGF-beta-2 complex [narrow]
TGFbeta3 complex [narrow]
TGFB3 complex [narrow]
TGF-beta-3 complex [narrow]
Relationships:
capable_of GO:0005160 transforming growth factor beta receptor binding
capable_of_part_of GO:0007179 transforming growth factor beta receptor signaling pathway
capable_of_part_of GO:0010862 positive regulation of pathway-restricted SMAD protein phosphorylation
part_of GO:0031012 extracellular matrix
DBxrefs:
GOC:bhm
IntAct:EBI-12501958
IntAct:EBI-12502251
IntAct:EBI-12502440
PMIDs: 
PMID:8679613 (TGFB1 complex)
PMID:18243111 (TGFB2 complex)
PMID:8819159 (TGFB3 complex)
PMID:20207738 (GO MF evidence for TGFB1)
PMID:1333888 (GO BP evidence for TGFB1)
PMID:12065756 (GO BP evidence for TGFB1)
PMID:22943793 (review)
Comment: An example is TGFB1 (P01137) in human, PMID:8679613 (by IPI). [I can't remember the syntax of the sentence by heart!]

Thanks,
Birgit

**Comment by pgaudet** [comment]
Hi Brigit, 

What's the difference between this term and "GO:0070022 transforming growth factor beta receptor homodimeric complex" ?

**Comment by bmeldal** [comment]
The existing term is for the receptor dimer which is a subcomplex of the whole receptor-ligand complex (2x ligand-2x receptors alpha subunit-2x receptor beta subunit). I'm also curating the ligands themselves and they dimerise before they reach the membrane and bind the receptor subunits. There is currently no term for the TGFbeta dimers.

It's akin to the various interleukin dimers and we have terms for those. (I'm also curating the ILs!)

**Comment by pgaudet** [comment]
Yes sorry ! 

What threw me off is the 'dimeric' complex - I thought that was the difference. I suggest this should be either removed from the receptor or be added everywhere. 
Thanks, 
Pascale

**Comment by bmeldal** [comment]
Do you mean the "homodimeric" in the receptor term? Yes, we agreed that shouldn't be in term names but there are many legacy terms... ;-)

**Comment by dosumis** [comment]
Added: GO_0099126

As requested except:

1. just going with review for ref.
2. Have left of narrow synonyms as too specific

**Comment by bmeldal** [comment]
GO:0070022 still needs "homodimeric" removing from the name and def. Do you need a new ticket for that?

**Comment by dosumis** [comment]
> GO:0070022 still needs "homodimeric" removing from the name and def. Do you need a new ticket for that?

Done

**Comment by bmeldal** [comment]
Thanks :)
