### ISSUE TITLE
New term requests for microtubule nucleation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12680]
After minor rearrangements
https://github.com/geneontology/go-ontology/issues/12679

mictotubule nucleation from eMTOC PMID:19001497

**Comment by mah11** [comment]
I think the new term above would be 'microtubule nucleation from eMTOC'.

We can also use 'cytoplasmic microtubule nucleation'.

**Comment by ValWood** [comment]
yes "from' (typo)

**Comment by ValWood** [comment]
GO:0051415	interphase microtubule nucleation by interphase microtubule organizing center	

would become a descendant of
GO:0051415	interphase microtubule nucleation by interphase microtubule organizing center	

(in case this is confusing rename this term to 
GO:0051415 cytoplasmic microtubule nucleation by interphase microtubule organizing center)

But we do require the new parent term because cytoplasmic microtubules can be nucleated  i) in other ways, and ii) during M-phase)

**Comment by ValWood** [comment]
Hi @dosumis  this one looks straight forward. could you do, or let us know  if you require any more info from us?

Val

**Comment by ValWood** [comment]
1. rename
GO:0051415 interphase microtubule nucleation by interphase microtubule organizing center
to
GO:0051415  microtubule nucleation by interphase microtubule organizing center

**Comment by ValWood** [comment]
we aren't sure what this ticket means so closing

**Comment by ValWood** [comment]
grouped MTOC terms under  the existing common parent.

This leaves
"mitotic spindle templated" and "chromatin templated" microtubule these appear to be "de novo"  without a MTOC machinery so it is not clear if separate terms are required to  "microtubule nucleation"...neiterh of these terms are used in annotation, even though the papers reporting them have been curated.
