### ISSUE TITLE
MP: multicellular processes  

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12688]
GO:0044274 multicellular organism biosynthetic process
is missing parent
 GO:0032501 multicellular organismal process

GO:0044266 multicellular organismal macromolecule catabolic process
is missing parent
GO:0044266 multicellular organismal macromolecule catabolic process

@cmungall  shouldn't the reasoner pick these up?

from
https://github.com/pombase/canto/issues/28#issuecomment-250712901

**Comment by dosumis** [comment]
Fixed
