### ISSUE TITLE
process taxon restrictions 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12699]
Only in metazoa? (possibly) never in fungi (definitely)

Note, some of these might be better fixed by having a “multicellular organismal process” parent which would automatically pull in the metazoan taxon restriction

GO:0002376 immune system process
GO:0007610 behavior
GO:0031128 developmental induction
GO:0042445 hormone metabolic process
GO:0010166 wax metabolic process
GO:0010191 mucilage metabolic process
GO:0042133 neurotransmitter metabolic process
GO:0001508 action potential
GO:0032501 multicellular organismal process
GO:0099536 synaptic signaling
GO:0031128 developmental induction
GO:0007258 JUN phosphorylation
GO:0007257 activation of JUN kinase activity
GO:0043506 regulation of JUN kinase activity
GO:0042470 melanosome
GO:0043700 pterinosome
GO:0043698 iridosome
GO:0043701 cyanosome
GO:1990257 piccolo-bassoon transport vesicle

Only in
GO:0015979 photosynthesis (only in plant/ cyanobacteria?)

**Comment by ValWood** [comment]
Never in Scizosaccharomyces
GO:0051702	interaction with symbiont
GO:0044403	symbiosis, encompassing mutualism through parasitism
GO:0052047	interaction with other organism via secreted substance involved in symbiotic interaction

**Comment by dosumis** [comment]
Action potentials in Paramecium: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4640487/

**Comment by dosumis** [comment]
May be some issues with the hormone and NT metabolic process terms.  It's hard to formalize these to mean metabolism of the molecule in a system where it acts as a hormone or neurotransmitter.

**Comment by ValWood** [comment]
This got in my list based on the definition:
The chemical reactions and pathways involving any hormone, naturally occurring substances secreted by specialized cells that affects the metabolism or behavior of other cells possessing functional receptors for the hormone.

If hormones are produced by specialised cells, then presumably  has to be "multicellular organisms).
In that case we could have "never in ascomycete" (unicellular fungi)

**Comment by ValWood** [comment]
Ah you mean just problems with the terms, generally?

**Comment by ValWood** [comment]
Extension to taxon restrictions:
any term with "neurotransmitter" can have only_in (animals with nervous system)
and term with "hormone" can have only_in (multicellular)

**Comment by dosumis** [comment]
The potential problem is that the various chemicals we have classified as hormones and neurotransmitters often have other roles.  glutamate and glycine and ATP can all act as neurotransmitters - but are metabolised by all(?) living things. 

We only have a rather small set of specific chemical terms under neurotransmitter metabolism:

http://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0042133

 But that's just incompleteness.

**Comment by ValWood** [comment]
oh I see the problem....

**Comment by ukemi** [comment]
Maybe just leave these without taxon restrictions for now?

**Comment by ValWood** [comment]
yep leave those two....

**Comment by ukemi** [comment]
Hi Val,

I am concerned about some of these. I just looked up wax metabolism and it looks like some bacteria can metabolize wax esters. If you search on immune response in AmiGO2 and filter on the kinds of organisms annotated with that term, you will see a wide spectrum. 
-D

**Comment by ValWood** [comment]
OK wax, I was only thinking of biosynthesis for fungi, but probably lots of things can metabolize.

For immune system I  guess pathogens regulate the host immune system, is that where they come from?
If so we can add _never in Schizosacchoromyces....
Possibly this could be added later, Chris mentioned making some things propagate over regulates and some not....

**Comment by ukemi** [comment]
So can you have another look here and see if you can refine this request a bit? It seems like there have been a lot of issues with the original list above.

**Comment by ValWood** [comment]
I guess the fact that these processes can be regulated by pathogens could be true of almost nay process...in which case it makes any process  taxon restriction difficult. If they seem that they will be a problem, could we add "never in Schizosaccharomyces", and  broader restrictions can be applied later as requested.

One reason I am keen to get these restriction  is that we now have the ability only show terms which are not taxon restricted in our community curation tool which can make searching much more relevant. It is also  a useful sanity check  for automated mappings (for everyone).

**Comment by ukemi** [comment]
Summary of what I did:

GO:0002376 immune system process  added never_in Schizosaccharomyces
GO:0007610 behavior already has only in metazoa, no edits
GO:0031128 developmental induction added never_in Schizosaccharomyces
GO:0042445 hormone metabolic process added never_in Schizosaccharomyces
GO:0010166 wax metabolic process added never_in Schizosaccharomyces
GO:0010191 mucilage metabolic process added never_in Schizosaccharomyces
GO:0042133 neurotransmitter metabolic process added never_in Schizosaccharomyces
GO:0001508 action potential added never_in Schizosaccharomyces
GO:0032501 multicellular organismal process  already never in S. pombe and S. cerevisiae
GO:0099536 synaptic signaling added never_in Schizosaccharomyces
GO:0031128 developmental induction  repeat of above
GO:0007258 JUN phosphorylation added never_in Schizosaccharomyces
GO:0007257 activation of JUN kinase activity added never_in Schizosaccharomyces
GO:0043506 regulation of JUN kinase activity added never_in Schizosaccharomyces
GO:0042470 melanosome added never_in Schizosaccharomyces
GO:0043700 pterinosome added never_in Schizosaccharomyces
GO:0043698 iridosome added never_in Schizosaccharomyces
GO:0043701 cyanosome added never_in Schizosaccharomyces
GO:1990257 piccolo-bassoon transport vesicle added never_in Schizosaccharomyces

Only in
GO:0015979 photosynthesis added never_in Schizosaccharomyces

**Comment by ValWood** [comment]
thanks David!

**Comment by vanaukenk** [comment]
Hi,

Can we revise the taxon restrictions for GO:0042470 melanosome (and any melanosome-related BP terms, like GO:0032402 melanosome transport) to also include never_in Caenorhabditis?   Could we also add this restriction to terms that refer to melanocytes?

We are inheriting annotations to some melanosome-containing terms via PAINT, and C. elegans does not have melanosomes or melanocytes.

Thx.
--Kimberly

**Comment by cmungall** [comment]
I suggest we go ahead and add

 * [ ] GO:melanosome never-in NCBITaxon:Caenorhabditis

I will do this.

But we should move towards this:

 * [ ] GO:melanosome ?? CL:melanocyte
 * [ ] CL:melanocyte never-in NCBITaxon:Caenorhabditis (here: https://github.com/obophenotype/cell-ontology/issues/459)

For ??, can we use part_of? Do melanosomes ever get secreted and end up in different cells? If safer, we can use a derivational relationship (we haven't done this for any cell components so far).

Once these two are done the first can be removed as redundant

**Comment by cmungall** [comment]
Added GO tc with r37887

```
$ svn diff gene_ontology_write.obo
Index: gene_ontology_write.obo
===================================================================
--- gene_ontology_write.obo     (revision 37886)
+++ gene_ontology_write.obo     (working copy)
@@ -270782,6 +270782,7 @@
 xref: Wikipedia:Melanosome
 is_a: GO:0048770 ! pigment granule
 relationship: never_in_taxon NCBITaxon:4895 ! Schizosaccharomyces
+relationship: never_in_taxon NCBITaxon:6237 {source="GOC:kmv"} ! Caenorhabditis
 relationship: only_in_taxon NCBITaxon:33208 ! Metazoa
 
 [Term]
```

**Comment by cmungall** [comment]
Currently in_taxon doesn't chain with the transport relations. Are there symbiotic relationships involving the symbiont transporting within a host cell?

It's annoying having to account for the multi-species cases, we need a general rule for being less conservative in non-symbiotic species such as the humans and model organisms.

**Comment by vanaukenk** [comment]
Thx, @cmungall !

**Comment by dosumis** [comment]
>  Are there symbiotic relationships involving the symbiont transporting within a host cell?

Viral entry/exit/packaging processes ?

**Comment by ukemi** [comment]
@cmungall 

> For ??, can we use part_of? Do melanosomes ever get secreted and end up in different cells? If safer, we can use a derivational relationship (we haven't done this for any cell components so far).

A quick search:
PMID:22189785

Can we close this one given that you did step 1 above?

**Comment by cmungall** [comment]
I did melanosome part-of melanocyte, r 38403

**Comment by cmungall** [comment]
btw, I checked extensions for any melanosomes outside cells, there weren't any. The relation may still be strong but we can revisit.

**Comment by ukemi** [comment]
OK, so the transfer of them to fibroblasts in the above paper doesn't count?

**Comment by cmungall** [comment]
I don't think so
