### ISSUE TITLE
MP GO:0039679 viral occlusion body 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12691]
GO:0039679 viral occlusion body 

should have relation to
GO:0019012 virion

**Comment by dosumis** [comment]
It does: 

![image](https://cloud.githubusercontent.com/assets/112839/19041951/105aaa10-8982-11e6-97b9-1de072fde391.png)

**Comment by ValWood** [comment]
Ah OK, has_part
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0039679#term=ancchart
I don't see this in QuickGO.
I expected part_of...
