### ISSUE TITLE
MP   GO:0034638 phosphatidylcholine catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12696]
GO:0034638 phosphatidylcholine catabolic process
The chemical reactions and pathways resulting in the breakdown of phosphatidylcholines, any of a class of glycerophospholipids in which the phosphatidyl group is esterified to the hydroxyl group of choline.

has no parentage to 
glycerophospholipid metabolic process

2016-06-22	Deleted	RELATION	is a GO:0046475 (glycerophospholipid catabolic process)

**Comment by dosumis** [comment]
Fixed.  But some odd things about ChEBI.  Closing ticket but recording details here in case we need some follow-up.

All GO axioms referring to phosphatidylcholine  [CHEBI:49183 ! phosphatidylcholine(1+)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A49183), the only classification for which is:

phosphatidylcholine(1+) (CHEBI:49183) is a quaternary ammonium ion (CHEBI:35267) 

ChEBI [phosphatidylcholine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:64482) has the classifications we need:

phosphatidylcholine (CHEBI:64482) is a glycerophosphocholine (CHEBI:36313) 

So I've switched all  GO terms to use this one.

@ukemi @hdrabkin : CC'ing you to check if this is the right thing to do and to get some comments on whether we should submit a ticket to ChEBI.

Given that phosphatidylcholine (CHEBI:64482) is conjugate base of phosphatidylcholine(1+) (CHEBI:49183) 

I would have expected a GO equivalence axioms to make it irrelevant whether we choose acid or base in this case.  Do we need to investigate why we don't have one?

But it also feels like ChEBI classification is very incomplete so we should request they fill in the gaps.  Do yo agree.

Finally, this seems weird to me

![image](https://cloud.githubusercontent.com/assets/112839/19040323/7e722336-897b-11e6-95ef-615935ea4b25.png)

It all comes from ChEBI classifications. But @hdrabkin IIRC we discussed this before (for at least some of the examples) and you said it was OK.  Can you confirm?

**Comment by dosumis** [comment]
Diff here: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/gene_ontology_write.obo?r1=r35973&r2=35975
