### ISSUE TITLE
New term request for DIF dechlorinase activity

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#12692]
Hi:

I would like to request a new GO molecular function term for the enzyme activity DIF dechlorinase. Specifically:

Name: DIF dechlorinase activity

Ontology: molecular function

Synonyms: DIF-1 dechlorinase activity, DIF-1 3(5)-dechlorinase activity, differentiation-inducing factor dechlorinase activity, differentiation-inducing factor 1 dechlorinase activity, 1-[(3,5-dichloro-2,6-dihydroxy-4-methoxy)phenyl]hexan-1-one 3(5)-dechlorinase activity, 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one 3(5)-dechlorinase activity

Definition: Catalysis of the reaction: 1-[(3,5-dichloro-2,6-dihydroxy-4-methoxy)phenyl]hexan-1-one = 1-[(3-chloro-2,6-dihydroxy-4-methoxy)phenyl]hexan-1-one + Cl-

The position of this term in the GO hierarchy should be as a child of:

GO:0016848   carbon-halide lyase activity

This activity is also the first step in the pathway: 

GO:0031147	1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one metabolic process

References: 
PMID:1521542, Differentiation-inducing-factor dechlorinase, a novel cytosolic dechlorinating enzyme from Dictyostelium discoideum.
PMID:22035794, Identification of a eukaryotic reductive dechlorinase and characterization of its mechanism of action on its natural substrate.

Please let me know if you have any questions. 
Thanks,
Bob

**Comment by dosumis** [comment]
Hi Bob,

Many thanks for such a detailed request.  It should be straightforward to add.  One quick question:  Is there an EC number available for this activity?

Cheers,
David

**Comment by rjdodson** [comment]
Hi David:

No, the authors do not provide an EC number, and I did not find any mention in IUBMB Enzyme Nomenclature. Based on my understanding, I think this should be a new enzyme within 4.5.1.- 

But as noted before, the authors did not provide an EC number.

Let me know of further questions.
Thanks,
Bob

**Comment by dosumis** [comment]
Added as requested.

**Comment by rjdodson** [comment]
Hi David:

I circled back around to add this term, but don't see it in either AMIGO or Protein2GO. Is there a lag time between adding the term and when it's available? Or am I missing something? 

Thanks,
Bob

**Comment by dosumis** [comment]
Hi Bob,

Apologies for the delay.  The GO build is currently broken.  This is holding up the release of edits including this term addition. We hope to have it fixed in the next day or two.  There will then be a delay of 2-3 days before it shows up in QuickGO and AmiGO.  Please check again next week.

Thanks for you patience,
David
