### ISSUE TITLE
updates, synaptonemal structures

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12693]
Follow on from
https://github.com/geneontology/go-ontology/issues/12683
https://github.com/geneontology/go-ontology/issues/12684

I have spoken to Jurg Bahler who co-authored some of the original "linear element" papers in pombe.

Summary of the discussion:
- I would be confising if linear elelment was a type of "synaptonemal complex
 as pombe famously has no synaptonemal complex.

Current defs

GO:0030998 linear element
A proteinaceous scaffold associated with S. pombe chromosomes during meiotic prophase. Linear elements have a structure related to but not equivalent to the synaptonemal complex.

GO:0000795 synaptonemal complex
"A proteinaceous scaffold found between homologous chromosomes during meiosis."

These are not differentiated.

The synaptonemal complex definition needs revising
https://en.wikipedia.org/wiki/Synaptonemal_complex
The synaptonemal complex is a tripartite structure consisting of two parallel lateral regions and a central element.

The linear element has a single “lateral region”

Jurg has agreed that this would be OK:

GO NEW synaptonemal structure 
"A proteinaceous scaffold found between homologous chromosomes during meiosis."

GO NEW synaptonemal structure
— GO:0000795 synaptonemal complex 
——- GO:0000800	lateral element -> synaptonemal complex lateral element
——- GO:0000801	central element -> synaptonemal complex central element
——- GO:0000802	transverse filament -> synaptonemal complex traverse elelment
—- GO:0030998 linear element

**Comment by ValWood** [comment]
pombe linear elelment refs 
PMID: 8536990
PMID: 12665553

**Comment by dosumis** [comment]
Perfect.  Thanks!  Adding now.

**Comment by dosumis** [comment]
Done

Synaptonemal complex: A proteinaceous scaffold found between homologous chromosomes during meiosis. It consists of 2 lateral elements and a central element, all running parallel to each other. Transverse filaments connect the lateral elements to the central element.

**Comment by ValWood** [comment]
Did you make the new grouping term
GO NEW synaptonemal structure
for synaptonemal complex and linear elelment?

(this would have the old def of "synaptonemal complex"

**Comment by dosumis** [comment]
Yep.
