### ISSUE TITLE
OTR: add logical definition for 'regulation of fertilization'

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12695]
As highlighted by a UniProt curator
'negative regulation of fertilization' didn't appear as a child of 'regulation of fertilization'
(shown in QuickGO as of today: http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0080154#term=children)
because the former is logically defined but the latter isn't .
I'll fix.

**Comment by paolaroncaglia** [comment]
Done.

**Comment by cmungall** [comment]
Does this strike anyone else as an odd term for GO?

Experimental annotations in mouse (direct) and arabidopsis (child)

Mouse annotations here:
http://amigo.geneontology.org/amigo/reference/PMID:18951373

I think this is a case of trying to cram a phenotype into GO. AFAICT tektin3 is required for male fertility. The paper uses language like "maintain normal fertility". We should not be acting like NLP engines and matching this to the nearest string in GO. It seems to be involved in sperm motility which is required for / causally upstream of fertilization

**Comment by ValWood** [comment]
It sounds an odd GO term to me, but I have a strict interpretation of regulation.
Also as you know, I'm leary of "causally upstream" for very indirectly upstream processes (still need to compile examples of why..). But this seems to be appropriate use.

I have been meaning to ask about this. Do you envisage  that, since "sperm motility" is causally upstream of "fertilization" the link  between these processes would be in the ontology, rather than the annotation?

v

**Comment by ukemi** [comment]
I would think that any block to polyspermy would be a negative regulation of fertilization. This can be a complex process modulated physically, electrically and chemically.

**Comment by ValWood** [comment]
Actually "polyspermy" seems to be is_a negative regulation of fertilization....if  fertilization is aborted...

**Comment by ukemi** [comment]
No, polyspermy is more than one sperm fertilizing a single egg, then bad things happen. Organisms try hard to prevent it.

**Comment by cmungall** [comment]
In any case, I don't think the tektin3 case is to do with polyspermy? At least consider adding a do-not-manually-annotate to this term and force people to annotate to a term that shows a specific mechanism.

> I have been meaning to ask about this. Do you envisage that, since "sperm motility" is causally upstream of "fertilization" the link between these processes would be in the ontology, rather than the annotation?

Makes sense. Of course, not every instance of sperm motility is upstream of a fertilization event. But clearly the motility is there to get the sperm where it needs to be. @dosumis is currently improving some of the causal definitions, we should take this use case into account.

**Comment by krchristie** [comment]
I agree that not every instance of sperm motility is upstream of a fertilization event. Also note that some sperm are non-motile, e.g. those of angiosperms, which are moved by pollen tubes but are not themselves motile cells.

However, I also see that currently, there is no relationship between “flagellated sperm motility”
and “sperm axoneme assembly”. However, now that there is a term specifically for “flagellated sperm motility” specifically distinguished from any other types of “sperm motility” including “amoeboid sperm motility”, I think there actually could be connections between these. It seems to me that “sperm axoneme assembly” could be part_of “flagellated sperm motility”, and that a reciprocal has_part relationship would also be valid. @paolaroncaglia, does this seem true to you too?

-Karen

**Comment by ValWood** [comment]
ah OK, what mechanisms do they use to prevent?
I thought normal fertilization would  act to prevent polyspermy, because polyspemy is lethal  but is this regulation of fertilization? 

I'm trying to think of an analogy with a process I know something about.

**Comment by ValWood** [comment]
OK got one.  Re-replication.  we don't want this to happen (normally, ignoring drosophilla salivary glands etc). and yes, we annotate mechanisms which prevent re-replication to "negative regulation of  DNA replication"

I still think Chris is correct about the sperm motility annotations though. This isn't 'mechanistic" for regulation of fertilization is it?

**Comment by ukemi** [comment]
Yup. I agree about the annotations. In the Noctua world, the assembly of the flagellum would be causally upstream of the motility. You need the to make the oars if you want to row the boat. Onward to Noctua modeling!

**Comment by krchristie** [comment]
I agree that sperm motility isn't part of regulation of fertilization either, just required for fertilization. As per David H's request, I have suggested deletion of the "regulation of fertilization" annotations for the mouse gene via P2GO. I think that the annotations for "flagellated sperm motility" and "cilium morphogenesis" (which I have suggested changing to "sperm axoneme assembly" due to the impending merge of "cilium morphogenesis" into "cilium assembly".

**Comment by ukemi** [comment]
If I remember correctly, flowering plants also have double fertilization. Isn't embryology cool?

**Comment by paolaroncaglia** [comment]
@krchristie , in response to your question:

“It seems to me that “sperm axoneme assembly” could be part_of “flagellated sperm motility”, and that a reciprocal has_part relationship would also be valid. @paolaroncaglia, does this seem true to you too?”

I’m not sure, it sounds vaguely odd. If the sperm axoneme wasn’t assembled, would the sperm be flagellated at all? It certainly wouldn’t be motile, but that sounds way more upstream than has_part (or even starts_with) to me.
But if you feel strongly about this, please open a separate ticket and assign to me, because this one is getting a bit crowded ;-) Thanks!

**Comment by paolaroncaglia** [comment]
Hi everyone,
I'll close this ticket now. If there's any issue you'd like to look into any further, please open separate tickets or similar where appropriate (annotation tracker, GOC meeting agenda, etc. :-)). Thanks.
