### ISSUE TITLE
query GO:0061387 	regulation of extent of cell growth

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12707]
GO:0061387
Name	regulation of extent of cell growth

is defined
Any process that modulates the frequency, rate, extent or direction of cell growth.

can this definition be improved?
I  guess it has something to do with eventual cell size ?  (how does it differ from regulation of cell size?)

@Antonialock I think this is probably the term you require for plo1? (the pathways which determine whether a cell divides at small or large size?)

**Comment by ukemi** [comment]
Size can result in getting smaller too. Growth is getting bigger.

**Comment by ValWood** [comment]
Doh thanks!
