### ISSUE TITLE
please add ref for taxon restiction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12702]
GO:0009008 never in S. pombe PMID: 7862522

**Comment by ukemi** [comment]
id: GO:0009008
 name: DNA-methyltransferase activity
 namespace: molecular_function
-def: "Catalysis of the transfer of a methyl group to a DNA molecule." [GOC:jl, ISBN:0198506732]
+def: "Catalysis of the transfer of a methyl group to a DNA molecule." [GOC:jl, ISBN:0198506732, PMID:7862522]
 subset: gosubset_prok
 synonym: "deoxyribonucleate methylase activity" EXACT [EC:2.1.1.-]
 synonym: "deoxyribonucleate methyltransferase activity" EXACT [EC:2.1.1.-]
 synonym: "Type II DNA methylase" RELATED [EC:2.1.1.37]
 xref: EC:2.1.1
 is_a: GO:0008168 ! methyltransferase activity
+relationship: never_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
 relationship: part_of GO:0006306 ! DNA methylation
