### ISSUE TITLE
question about protein complex scaffold

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12704]
GO:0032947
Name	protein complex scaffold
is defined
Functions to provide a physical support for the assembly of a multiprotein complex.

and is a descendant of
GO:0005198 structural molecule activity
The action of a molecule that contributes to the structural integrity of a complex or assembly within or outside a cell.

I have therefore always used this for a "protein complex scaffold" which forms an integral part of the final protein complex when assembled. Like, for instance

SIN component scaffold protein, centriolin ortholog Cdc11
onto which the other complex subunits assemble

like this:

![sin](https://cloud.githubusercontent.com/assets/7359272/19067024/21bcb4fa-8a14-11e6-9184-eb8ab18ec0a5.jpg)

However, I see it is also used for ecm29
http://www.pombase.org/spombe/result/SPAC1782.01

which is a "chaperone" it is used as a scaffold "during assembl" but is not part of the final complex.

These are quite functionally different.

Should "protein scaffold" be used for both (in which case the parentage is not really correct)?
Do we need a term to represent an assembly chaperone ?

**Comment by ukemi** [comment]
It seems to me that the assembly chaperone's function is just protein complex assembly. It is not a stable scaffold.

**Comment by ValWood** [comment]
So you would say it should not be used for ecm29 ? I can see how it could be based on the current def...

**Comment by ukemi** [comment]
Maybe ecm29 should be annotated to both assembly and scaffold.

**Comment by ValWood** [comment]
But it isn't a scaffold in the sense  of a structural molecule. I think the term "protein complex scaffold" is ambiguous....
It isn't part of the final complex.

**Comment by ukemi** [comment]
Is it a structural molecule during assembly? It seems to me that a scaffold encompasses both of these.

**Comment by ValWood** [comment]
but the parent term is

The action of a molecule that contributes to the structural integrity of a complex or assembly within or outside a cell.
(assembly is a noun here not a verb!)

The definition changes in the "protein scaffold term" and it could be interpreted as being a structural molecule "during" the assembly process.

But what does this mean? Isn't this what an assembly chaperone does?

**Comment by ukemi** [comment]
How about:

The action of a molecule that contributes to the structural integrity of a complex or its assembly within or outside a cell.

Then the child:

A structural molecule activity that provides a physical support for the assembly of a multiprotein complex.

**Comment by ValWood** [comment]
Should make it clear that the structural molecule may or may not be part of the final complex. This is the part which flummoxed me.....

**Comment by ukemi** [comment]
name: structural molecule activity
 namespace: molecular_function
-def: "The action of a molecule that contributes to the structural integrity of a complex or assembly within or outside a cell." [GOC:mah]
+def: "The action of a molecule that contributes to the structural integrity of a complex or its assembly within or outside a cell." [GOC:mah, GOC:vw]
 subset: goslim_aspergillus
 subset: goslim_candida
 subset: goslim_chembl


 id: GO:0032947
 name: protein complex scaffold
 namespace: molecular_function
-def: "Functions to provide a physical support for the assembly of a multiprotein complex." [GOC:mah]
+def: "A structural molecule activity that provides a physical support for the assembly of a multiprotein complex. The scaffold may or may not be part of the final complex." [GOC:mah, GOC:vw]
 is_a: GO:0005198 ! structural molecule activity
 is_a: GO:0005515 ! protein binding

**Comment by vanaukenk** [comment]
Hi @ukemi and @ValWood 

This seems like an ontology issue that we should at least alert curators to on the next annotation call, as the meaning may have slightly changed.  I think I also usually interpreted the term def the same way as Val, i.e., the scaffold stuck around as part of the final complex.  Perhaps others did as well?

**Comment by ukemi** [comment]
OK. Let's put it on the agenda. We can change back if necessary.
