### ISSUE TITLE
philosophical question about "causally upstream of"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12708]
Follow on from
https://github.com/geneontology/go-ontology/issues/12695#issuecomment-250817982

So, I was thinking about this.
I asked if the relationship
"sperm mobilization" causally_upstream_of "fertilization"
should be in the ontology

Chris
Makes sense. Of course, not every instance of sperm motility is upstream of a fertilization event. But clearly the motility is there to get the sperm where it needs to be. @dosumis is currently improving some of the causal definitions, we should take this use case into account.

So does this mean that the relationship can't be in the ontology? Does every instance need to be upstream of the event to allow a relationship to be added?
I was wondering since I don't know how you could infer this at annotation time in this case
(how would you demonstrate the causal relationship experimentally?).
I was assuming the relationship could exist (or is that what you mean ?)

**Comment by ukemi** [comment]
In every instance of fertilization, sperm motility is causally upstream of it. Although your question points out something we need to consider if we add these to the ontology, which is the difference between the instances that we describe when we annotate genes in a LEGO model and the classes in the ontology.

**Comment by dosumis** [comment]
> On Oct 5, 2016, at 12:27 PM, David Hill <notifications@github.com> wrote:
> 
> In every instance of fertilization, sperm motility is causally upstream of it.
> 

Probably true

But adding this in the ontology: sperm motility causally_upstream_of (some) fertilization

Would be asserting that 

ALL sperm motility is causally upstream of (some instance of) fertilization.

If we were to add this to the ontology we’d need the reverse:

fertilization causally_downstream_of sperm motility

**Comment by cmungall** [comment]
On 5 Oct 2016, at 4:39, David Osumi-Sutherland wrote:

> > On Oct 5, 2016, at 12:27 PM, David Hill <notifications@github.com> 
> wrote:
>>
>> In every instance of fertilization, sperm motility is causally 
>> upstream of it.
>>
>
> Probably true

http://www.dictionary.com/browse/spermatium

**Comment by ukemi** [comment]
There is always an exception. Even more reason why we need to be cautious about putting causal chains in the class representation.

**Comment by ukemi** [comment]
Closing this as there is no action other than to take care when adding relations.
