### ISSUE TITLE
Query about NFAT signalling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12701]
One of our community has used this term, because this seems to be the name of the pathway 
which is a conserved signalling pathway 

"In many cellular events, calcineurin functions
by dephosphorylating a zinc finger transcription factor,
Crz1 in budding yeast and Prz1 in fission yeast (17). In an
analogous manner, calcineurin regulates the mammalian
NFAT transcription factors which contain a Rel-homology
region (RHR) to bind to DNA."
. ......."When an increase in Ca2+ is prevented
or calcineurin is inhibited in budding yeast and human cells,
Crz1 and NFAT, respectively, are rephosphorylated by kinases,
such as: casein kinase I (CK1, Hrr25) (20,21); the
cyclic AMP-dependent protein kinase A (PKA) (22–24);
the CDK, Pho85 (25); glycogen synthase kinase 3 (GSK3)
(26); dual specificity tyrosine-phosphorylation-regulated
kinase (DYRK) (27); MAPK p38 and JNK (28,29). Crz1
and NFAT are then rapidly exported to the nucleus and
calcineurin-dependent gene expression is terminated. Thus,
many protein kinases interact with calcineurin-dependent
transcription factors to inactivate transcriptional activity."

so it seems  that the difference is the specific TF.
However the term is  described as "only in metazoa" and
Should "NFAT signalling" be merged into  general term if they are analogous?
GO:0097720 calcineurin-mediated signaling

Or will there be a separate term for the same pathway regulating different calcinurin dependent TFs?

**Comment by ValWood** [comment]
Hi
@cmungall  I notice the
GO:0070885 annotation is in our current GO data...any idea why this wasn't reported by taxon checks?

**Comment by ValWood** [comment]
and GO:0033173

**Comment by cmungall** [comment]
doesn't propagate over regulates.

we need to implement a rule that it should propagate for non-pathogenic 
organisms

**Comment by ukemi** [comment]
The term is 'calcineurin-NFAT signaling cascade' and it specifically describes the linking of the calcineurin signaling with an NFAT transcription factor.  Is this what is happening in yeast? 

I don't think it is a good idea to go the route of delineating every single transcription factor family that can be activated in cases like this. That is why LEGO models will come in very handy for ontology developers. Similar to the Dicty chemotaxis example that we discussed on the call this week, we will be able to specify the biology in the model and precisely delineate the signaling steps that are contributing to the biology and where they start and end. 

If you think the taxon restriction should be removed, et me know and I will remove it. Otherwise, pleas advise me about what I need to do to close this item.

**Comment by dianeoinglis** [comment]
While calcineurin is conserved from yeast to man, NFAT is found in organisms with an immune system and is not found in yeast/fungi.

**Comment by ValWood** [comment]
Hi,

Yes my question is more a general question about how we describe signalling pathways, and if we will have a separate term for every transcription  factor even if the upstream pathway is identical.

It would be better if there was a generalised way to describe signalling pathways.  We already have many  identical pathways which are described in different ways (GTPase mediated/MAPK cascade/pheromone dependent etc etc.).

Are there any guidelines about this? I always find it a bit confusing.....

Anyway happy to close this, it has the appropriate taxon constraint for the current definition...

**Comment by dosumis** [comment]
(General comment  - not relevant to ticket status)

> Yes my question is more a general question about how we describe signalling pathways, and if we will have a separate term for every transcription factor even if the upstream pathway is identical.

This is probably a part of the ontology where LEGO will help use reconsider the balance of what goes into the ontology and what goes into annotation.  We currently allow class terms for every pathway & pathway fragment, which can't possibly scale. 

We do have some formalization, but it is limited to cases where we can specify a particular activity that the ST pathway must start with, end with or include.  There is some arbitrariness here though - as we have some activity terms which are tied to quite specific gene families.

**Comment by dianeoinglis** [comment]
NFAT1-4 are regulated by Ca2+ and calcineurin. NFAT5, however, is not regulated by calcineurin. This seems like a reason to specify calcineurin-NFAT signalling to distinguish calcineurin-independent NFAT activity. What taxon restriction was decided upon? It was not obvious on the QuickGO or AmiGO sites for the term.
