### ISSUE TITLE
add relationships for GO:0019676 ammonia assimilation cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12703]
GO:0019676 ammonia assimilation cycle
defined
The pathway by which ammonia is processed and incorporated into a cell. In an energy-rich (glucose-containing), nitrogen-poor environment, glutamine synthetase and glutamate synthase form an ammonia assimilatory cycle, in which ammonia is incorporated into L-glutamate to form L-glutamine, which then combines with alpha-ketoglutarate to regenerate L-glutamate. This ATP-dependent cycle is essential for nitrogen-limited growth and for steady-state growth with some sources of nitrogen.

- [ ] please add parent:
GO:0006995	cellular response to nitrogen starvation

**Comment by ValWood** [comment]
as GO:0019676 ammonia assimilation cycle
is glutamine synthetase and glutamate synthase 
and these are the 2 genes involved in 
"glutamine biosynthetic process"

- [ ] GO:0006542  glutamine biosynthetic process part_of GO:0019676 ammonia assimilation cycle ?

**Comment by ValWood** [comment]
add F-P links
GO:0004356 - glutamate-ammonia ligase activity part of GO:0006542 - glutamine biosynthetic process

**Comment by ukemi** [comment]
Is this always a response to starvation? The last sentence implies that sometimes it occurs just to use ammonia as a nitrogen source.

**Comment by ValWood** [comment]
Oh possibly not....
