### ISSUE TITLE
NTR 	membrane addition at site of mitotic cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12705]
descendent of
GO:0007107	membrane addition at site of cytokinesis

standard def (parent)
ref PMID:27082518

**Comment by ukemi** [comment]
[Term]
+id: GO:0061796
+name: membrane addition at site of mitotic cytokinesis
+namespace: biological_process
+def: "A mitotic cell cycle process involved in the net addition of membrane at the site of cytokinesis; includes vesicle recruitment and fusion, local lipid synthesis and insertion." [GOC:dph, GOC:vw]
+is_a: GO:0007107 ! membrane addition at site of cytokinesis
+intersection_of: GO:0007107 ! membrane addition at site of cytokinesis
+intersection_of: part_of GO:0000278 ! mitotic cell cycle
+created_by: dph
+creation_date: 2016-10-05T12:06:11Z
+
