### ISSUE TITLE
NTR:pH gated chloride channel activity term

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12706]
I would like a term to describe pH-gated chloride channel activity. The channel in question, pHCl-2, is "closed" at acidic pH and "open" at alkaline pH (PMID:27358471 ). The mechanism is not known, so I am not too keen on encoding the this in the description (such as alkaline-activated, acid-senstive) and a general term such as "pH gated chloride channel activity" seems the best fit.

Definition:"Enables the transmembrane transfer of a chloride ion by a channel that opens at a particular pH range".

child of:
GO:0005254 chloride channel activity 
&
GO:0022836 gated channel activity

**Comment by ukemi** [comment]
To keep it similar to the parent, how about:

Enables the transmembrane transfer of a chloride ion by a channel that opens in response to a change in pH.

**Comment by hattrill** [comment]
Oh yes, that's much more poetic!

**Comment by ukemi** [comment]
Just trying to make it consistent with the parents. The chloride parent will be added by the reasoner.

 [Term]
+id: GO:0061797
+name: pH-gated chloride channel activity
+namespace: molecular_function
+def: "A gated channel activity that enables the transmembrane transfer of a chloride ion by a channel that opens in response to a change in pH." [GOC:dph, PMID:27358471]
+is_a: GO:0022836 ! gated channel activity
+intersection_of: GO:0022836 ! gated channel activity
+intersection_of: transports_or_maintains_localization_of CHEBI:17996 ! chloride
+created_by: dph
+creation_date: 2016-10-06T07:11:14Z
