### ISSUE TITLE
revise def GO:0044878 - mitotic cytokinesis checkpoint 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12715]
revise def
Definition: "A mitotic cell cycle checkpoint that detects a defect in cytokinesis and negatively regulates mitosis in the following cell cycle." [GOC:jl, GOC:mtg_cell_cycle]

I've never been very happy with this one.
I'm doing a cytokinesis checkpoint paper  now  so I thought I'd makes it a bit clearer

A mitotic cell cycle checkpoint that detects a defect in cytokinesis and prevents further rounds of  nuclear division until cytokinesis is completed. 
refs (PMID:17538026)

.

**Comment by ukemi** [comment]
I like it. Done.
