### ISSUE TITLE
def fix GO:0051519 - activation of bipolar cell growth 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12713]
GO:0051519 - activation of bipolar cell growth (biological_process) [QuickGO, AmiGO, BioPortal]

Definition: "Any process that initiates the inactive process of bipolar cell growth, polarized growth from both ends of a cell." [GOC:ai]

???
the activation?

**Comment by ukemi** [comment]
Hi Val,

This is a standard def that distinguishes it from simple positive regulation. What are you suggesting?

"Any process that activates the process of bipolar cell growth, polarized growth from both ends of a cell." 

??

-D

**Comment by ValWood** [comment]
I thought  this was a typo?
"the inactive process "??
is it isn't I don't know what this bit means...

(I'm suggesting
*any process that initiates the activation* 
which might be what you are reading ;)

**Comment by ukemi** [comment]
How about:
"Any process that initiates the start of the process of bipolar cell growth, polarized growth from both ends of a cell."

**Comment by ValWood** [comment]
Sounds OK, (I don't understand the current def, so this is an improvement!)

**Comment by ukemi** [comment]
So what we are trying to get at in the activation definitions is that they are specific for a process that isn't yet happening and then begins to happen. This is in contrast to speeding up a process that is already happening. 

Amelia wrote very nice documentation on this way back when:

http://geneontology.org/page/regulation

If I change the def to the one above, does that make it clearer?

**Comment by ValWood** [comment]
Oh I see what it meant now. I think "initiates the start" is much better than "initiates the inactive process" !

**Comment by ukemi** [comment]
The definition has been modified to the above.

**Comment by mah11** [comment]
I beg to differ - "initiates the start" sounds nonsensical, or at least redundant. The old "initiates the inactive process" wording was clunky, but did at least make the point that David correctly flagged as important: that "activation" is slightly more specific than other kinds of "positive regulation" in that activation starts up something that previously wasn't happening at all.

Other "activation of process" terms use "starts the inactive process". That sounds OK to me, and using it for GO:0051519 would have the added advantage of consistency ;)

Tiny picky thing: the GO:0051522 def still uses the "initiates the inactive process" wording.

**Comment by ValWood** [comment]
OK!

**Comment by ukemi** [comment]
Changed back. Thanks Midori.
