### ISSUE TITLE
laminin term nomenclature

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12717]
All the laminin terms (those that include "laminin-#") should include synonyms that use a newer nomenclature.  For example "laminin-1" is now "laminin-111" and "laminin-4" is now "laminin-221".  The newer nomenclature comes from this publication:

 Aumailley M, et al. (2005). "A simplified laminin nomenclature". Matrix Biol. 24 (5): 326–32. (PMID:15979864)

    Nomenclature of 16 laminins
    Standard	Abbreviated	Previous
    α1β1γ1	111	                     1
    α2β1γ1	211	                     2
    α1β2γ1	121	                     3
    α2β2γ1	221	                     4
    α3Aβ3γ2	332, or 3A32	     5, or 5A
    α3Bβ3γ2	3B32	             5B
    α3Aβ1γ1	311, or 3A11	     6, or 6A
    α3Aβ2γ1	321, or 3A21	     7, or 7A
    α4β1γ1	411	                     8
    α4β2γ1	421	                     9
    α5β1γ1	511	                     10
    α5β2γ1	521	                     11
    α2β1γ3	213	                     12
    α4β2γ3	423	                     14
    α5β2γ2	522	                     –
    α5β2γ3	523	                     15

**Comment by ukemi** [comment]
@bmeldal  could you double check 13 and 14 in the ontology compared with what is listed here? I think you requested them, but I can't get to the reference. I added all the others. Thanks!

-David

**Comment by bmeldal** [comment]
I have:

1)
Laminin-423
http://www.ebi.ac.uk/intact/complex/details/EBI-2530020
Synonym: laminin-14
But annotated with GO:1990338 laminin-13 complex as that one has laminin-423 [exact] synonym

and
2)
Laminin-522
http://www.ebi.ac.uk/intact/complex/details/EBI-2530020
no 'old' name synonym
But annotated with GO:1990339 laminin-14 complex as that one has laminin-522 [exact] synonym

That concurs with Stan's picture above. I don't have access to the paper either but got the table (in 2 versions from the Paez paper and another one, ppt file attached) from Sylvie Ricard-Blum at Univ Lyon who runs MatrixDB and is an expert in ECM. She requested the complexes for the CP and I may have requested the missing GO terms to go along with them. I know that I changed the complex names after she advised me of the new nomenclature but I must have forgotten to pass on these changes to GO.

[Ontology_Laminins_SRB_July_2014.pptx](https://github.com/geneontology/go-ontology/files/515872/Ontology_Laminins_SRB_July_2014.pptx)

I would go with the tables above and the CP entries and change the GO terms accordingly.

I hope that helps,
Birgit

**Comment by ukemi** [comment]
Thanks Birgit. I have modified the terms and synonyms to be in accordance with the table. Please double-check your annotations.

-D

**Comment by bmeldal** [comment]
Thanks, David. I'll them in a few days time when the commits filter through :)

**Comment by bmeldal** [comment]
Ok, that looks fine now, unless the community prefers the new names as term names and old names as synonyms...

**Comment by vanaukenk** [comment]
Hi,

This related request stems from a go-help ticket (http://jira.geneontology.org/browse/GO-1374).

The CC ontology seems to be missing a term for the laminin 5B variant.  It looks like this variant was in the list @slaulederkind  initially submitted for this ticket.

I checked in with @bmeldal about IntAct's curation for these laminin complexes and here was her reply:

We have the curated in the CP:
http://www.ebi.ac.uk/intact/complex/details/EBI-2529819
Laminin-332 complex variant A
synonyms: LM-5A, Laminin-5 complex

http://www.ebi.ac.uk/intact/complex/details/EBI-9663928
Laminin-332 complex variant B
synonyms: LM-5B, Laminin-5B complex

But both annotated to GO:0005610 laminin-5 complex, probably for lack of a
5B variant term. It was curated before my time.

Can we add a CC term for the laminin-5B complex?

Thanks,
--Kimberly

**Comment by ukemi** [comment]
[Term]
+id: GO:0061801
+name: laminin-5B complex
+namespace: cellular_component
+def: "A laminin complex composed of alpha3B, beta3 and gamma2 polypeptide chains." [GOC:dph, PMID:15979864]
+synonym: "laminin 3B32 complex" EXACT [PMID:15979864]
+is_a: GO:0043256 ! laminin complex
+created_by: dph
+creation_date: 2016-10-26T15:05:15Z

**Comment by slaulederkind** [comment]
laminin-5 complex (GO:0005610) needs exact synonyms "laminin-5A complex" and "laminin-3A32 complex". The 6 and 7 complexes need the respective "A" synonyms also.  Are the "αβγ" versions of the laminin complexes left out because of display font issues?  Thanks.

**Comment by ukemi** [comment]
Synonyms added. I don't know of any cases where we have Greek letter fonts in the ontology.
