### ISSUE TITLE
OTR: actomyosin terms

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12711]
Hi @ValWood ,

I’m working on cellular component assembly terms that need a logical definition. I ran across GO:0000912 ’assembly of actomyosin apparatus involved in cytokinesis’ (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000912). Could you please confirm that ‘actomyosin apparatus’ there is the same as GO:0042641 ’actomyosin’ (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0042641)? And that ’actomyosin’ should be is_a ‘protein complex’? I’ll do the edits. Thanks.

**Comment by ValWood** [comment]
I was wondering why this term existed, but it seems from inspecting the children that ‘actomyosin apparatus’  is a grouping term.

The actinomyosin apparatus which forms the cytokinetic machinery is different in  metazoa and yeast to plants.

In animals and yeast the actinomyosin apparatus is the contractile ring.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0070938

in plants it is a phragmoplast
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009524

I think in both cases ‘actomyosin apparatus’ is more than just ’actomyosin’

**Comment by paolaroncaglia** [comment]
Note to self: based on Val’s comments, GO:0000912 ’assembly of actomyosin apparatus involved in cytokinesis’ is fine as is (or doesn’t need any urgent work anyway), and should not be given a logical def using ’actomyosin’. So I can close this ticket.
