### ISSUE TITLE
obsolete: positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12716]
Can we obsolete?

positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation

i) no annotations
ii) G2/M isn't positively regulated by nitrogen starvation
iii) we would capture this another way (the nutrition regulatory pathway could be named more  generically)

**Comment by ukemi** [comment]
Hmmm. Had a quick look at the paper used in the def. Could you double-check ppk18, page 322 end of the first paragraph?

**Comment by ValWood** [comment]
Oh crikey I thought that was one of the old terms hanging around that was requested in error. Its a new one. I have that paper on my checking list...so this pathway both +vely and -vely regulates G2/M depending on nutrient status...
