### ISSUE TITLE
term merge GO:0044810 Dma1-dependent checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12714]
please merge
GO:0044810 Dma1-dependent checkpoint
into
GO:0007094
Name	mitotic spindle assembly checkpoint

( There isn't any difference)

Thanks

Val

**Comment by ukemi** [comment]
OK. This is a bit more complicated because we also have these:

signal transduction involved in Dma1-dependent checkpoint
response to Dma1-dependent checkpoint signaling
detection of stimulus involved in Dma1-dependent checkpoint

Should those be merged or renamed, or is there something that differentiates those from the sibling target (mitotic spindle assembly checkpoint terms)? If so, we should retain the more specific term and not merge.

**Comment by ValWood** [comment]
no we should get rid of them all.
I remember asking the authors at the time and them telling me it was different. Now I see in subsequent papers that they use the term "mitotic spindle assembly checkpoint"

but it also appears to have a role in the cytokinesis checkpoint
![sin](https://cloud.githubusercontent.com/assets/7359272/19155919/1155e968-8bd8-11e6-9a37-e3c4e5806995.jpg)

which might account for the previous confusion....

**Comment by ValWood** [comment]
Ah hang on stop.....thats what it is. I need to check if it has a role in the spindle checkpoint. Perhaps when the authors originally said dma-dependant checkpoint they meant the "cytokinesis checkpoint"

(pombe dma1 is the only  gene annotated to this term)

**Comment by ValWood** [comment]
OK it is a different checkpoint
https://www.ncbi.nlm.nih.gov/pubmed?term=21131906

 Dma1, delays cytokinesis by inhibiting the septation initiation network (SIN) when chromosomes are not attached to the mitotic spindle.

or at least a diffent branch.
It isn't the cytokinesis checkpoint because that detects abnormal cytokinesis
It isn'tthe spindle assembly checkpoint per. se becasue that negatively regulated  *chromosome segregation* until all of the chromosomes are attached.

Lets keep it as it is. I think its OK. It might turn out to be a branch of another checkpoint but it looks as though it warrants a term....

**Comment by ValWood** [comment]
Oh I don't know....
https://www.ncbi.nlm.nih.gov/pubmed?term=8978687

**Comment by ukemi** [comment]
Safest would be to leave it for now then, right?

**Comment by ValWood** [comment]
yep it might be a resonse to the spindle checkpoint...will all become obvious soon will close
