### ISSUE TITLE
NTR: regulation of Golgi lumen acidification

### ISSUE THREAD

**Issue by connsears** [geneontology/go-ontology#12710]
Regulation of Golgi lumen acidification

Definition: Any process that modulates the frequency, rate, or extent of a process that reduces the internal pH of the Golgi lumen.

Aspect: cellular process

Relationships: Parent term - GO:0032847 regulation of cellular pH reductions; sibling term to GO:1901546 regulation of synaptic vesicle lumen acidification

Reference: PMID:23447592, particularly figure 5

**Comment by ukemi** [comment]
I added the root term. I will use TG to add the regulation term.  Do you want all three, regulates, positively regulates, negatively regulates?

[Term]
+id: GO:0061795
+name: Golgi lumen acidification
+namespace: biological_process
+def: "Any process that reduces the pH of the Golgi lumen, measured by the concentration of the hydrogen ion." [GOC:dph, PMID:23447592]
+is_a: GO:0051452 ! intracellular pH reduction
+created_by: dph
+creation_date: 2016-10-05T08:42:40Z

**Comment by ukemi** [comment]
I added all three:

Term]
id: GO:1905526
name: regulation of Golgi lumen acidification
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of Golgi lumen acidification." [GO_REF:0000058, GOC:dph, GOC:TermGenie, PMID:23447592]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0061795 ! Golgi lumen acidification
created_by: dph
creation_date: 2016-10-05T13:16:25Z


[Term]
id: GO:1905527
name: negative regulation of Golgi lumen acidification
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of Golgi lumen acidification." [GO_REF:0000058, GOC:dph, GOC:TermGenie, PMID:23447592]
synonym: "down regulation of Golgi lumen acidification" EXACT [GOC:TermGenie]
synonym: "down-regulation of Golgi lumen acidification" EXACT [GOC:TermGenie]
synonym: "downregulation of Golgi lumen acidification" EXACT [GOC:TermGenie]
synonym: "inhibition of Golgi lumen acidification" NARROW [GOC:TermGenie]
intersection_of: GO:0065007 ! biological regulation
intersection_of: negatively_regulates GO:0061795 ! Golgi lumen acidification
created_by: dph
creation_date: 2016-10-05T13:16:33Z


[Term]
id: GO:1905528
name: positive regulation of Golgi lumen acidification
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of Golgi lumen acidification." [GO_REF:0000058, GOC:dph, GOC:TermGenie, PMID:23447592]
synonym: "activation of Golgi lumen acidification" NARROW [GOC:TermGenie]
synonym: "up regulation of Golgi lumen acidification" EXACT [GOC:TermGenie]
synonym: "up-regulation of Golgi lumen acidification" EXACT [GOC:TermGenie]
synonym: "upregulation of Golgi lumen acidification" EXACT [GOC:TermGenie]
intersection_of: GO:0065007 ! biological regulation
intersection_of: positively_regulates GO:0061795 ! Golgi lumen acidification
created_by: dph
creation_date: 2016-10-05T13:16:41Z
