### ISSUE TITLE
add synonym to  GO:0032195

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#12712]
Hi:

The cellular component GO term, GO:0032195 "post-lysosomal vacuole" is typically referred to, in the dicty literature at least, as a "post-lysosome". So please add this as a synonym for this GO term. 

Please let me know of any questions. 
Thanks,
Bob

**Comment by ukemi** [comment]
Hi Bob,

I added it as an exact synonym.

-David
