### ISSUE TITLE
adding synonym Telomere Position Effect to existing term GO:0006348 chromatin silencing at telomere

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12725]
Hi,

Please add synonym to existing term.

Existing term: GO:0006348 chromatin silencing at telomere
Synonym to add: Telomere Position Effect, TPE (or better suggestion thanks.)
Evidence: PMID:     21847107
The authors state: "In Saccharomyces cerevisiae, the NAD+-dependent histone deacetylase Sir2 (silent information regulator 2) has a key role in generating and maintaining silent chromatin near telomeres. This epigenetic silencing of telomere-proximal genes—a phenomenon termed telomere position effect (TPE)1,2,3,4—is lost with replicative yeast ageing, concomitant with aberrant hyperacetylation of sub-telomeric histones".

GOC: BHF
GOC: BHF_telomere
GOC: nc 

Thanks.
Nancy

**Comment by mcourtot** [comment]
Done revision 36209
