### ISSUE TITLE
MP: GO:0008574 ATP-dependent microtubule motor activity, plus-end-directed

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12726]
should be a descendant of
GO:0060002 plus-end directed microfilament motor activity

**Comment by ValWood** [comment]
I need, I don't know about the ATP requirement...
microtubule motor activity, plus-end-directed

**Comment by dosumis** [comment]
microfilament is actin

**Comment by ValWood** [comment]
Ah OK. Doh. 
I need a term for 
microtubule motor activity, plus-end-directed
without ATP dependency.....

**Comment by ValWood** [comment]
Actually, I don't think I need this term. I was wondering how a motor activity could be ATP-independent (presumably  could perhaps used GTP, but I knew I hadn't seen that).
Anyway double checked and they say:

PMID:19037096
We concluded that this kinetochore-associated motor enzyme is capable of tubulin depolymerization-dependent, ATP-independent motion in the minus direction, an interesting addition to its ATP-dependent motion toward the plus end.

BUT, the ATP-independent movement is performed by the *kinesin*, but in this capacity the kinesin is not acting as a motor, its just an adaptor between the cargo and the microtubule. The microtubule  depolymerization is doing the movement in this case. 

So its a non-motor activity of kinesin.
