### ISSUE TITLE
"GO:0034290 holin activity" AND  "GO:0044660 cytolysis by virus via pore formation in host cell membrane", etc. ancestry

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#12727]
"GO:0034290 holin activity" is part_of and 
"GO:0044660 cytolysis by virus via pore formation in host cell membrane" is_a child of 

"GO:0040011 locomotion", DEF: Self-propelled movement of a cell or organism from one location to another.

We're thinking somewhere right below "GO:0040011 locomotion" the is_a relationship isn't quite right, as lysis seems to be a passive activity than "self-propelled movement".

**Comment by mcourtot** [comment]
Looking at the tree, I would say that "cytolysis by virus of host cell" should not be is_a "viral release from host cell", but rather part_of.

What do you think?
![screen shot 2016-10-12 at 12 27 54](https://cloud.githubusercontent.com/assets/2214135/19308416/574095c4-9077-11e6-8992-d75a9588b881.png)

**Comment by dosumis** [comment]
I'd break the link between 'exit from host' and 'movement in host environment' (v. odd term!).  Exit from host can live under 'interaction with host'.  None of this is pretty, but I think that's a reasonable fix for the basic issue.

**Comment by mcourtot** [comment]
GO:0035890 exit from host
The directed movement of an organism out of the body, tissues or cells of the host organism.  [...]

and

GO:0052126 movement in host environment
The directed movement of an organism or motile cell on, within or near its host organism. [...]

Based on the definitions the link seems justified. Do you think breaking the is_a between "cytolysis by virus of host cell" and "viral release from host cell" wouldn't be enough? This link seems really odd to me in any case, cytolysis from virus is not a viral release, it is part of it.

**Comment by dosumis** [comment]
I think 'exit from host' should probably not be defined as directed movement.   If it is just defined as any process that leads to release of a virus from its host, then my suggested fix works.

There needs to be a link between cytolysis by virus of host cell" and "viral release from host cell" as the former results in the latter.  I'm happy to keep this as is_a.

**Comment by jimhu-tamu** [comment]
Note that there are cases of directed movement of a symbiont to exit from a host, as in Listeria using "actin rockets" to move between host cells. That is very different than host cells blow up and viruses diffuse away. That's the basis for Suzi's original post. Am I reading the replies correctly to mean that there is agreement on that part?

The is_a vs part_of relationship for "cytolysis by virus of host cell" and "viral release from host cell" may come up in another term request we are still working on with a CACAO student. Should we do that separately or add to this issue?

**Comment by mcourtot** [comment]
Would you mind creating a separate issue and linking to this one? Saying something like "see also #12727" in the other ticket should work.

**Comment by cmungall** [comment]
@jimhu-tamu has all the cool organisms

**Comment by dosumis** [comment]
> Note that there are cases of directed movement of a symbiont to exit from a host

Should just be a new subclass of 'exit from host' which is also subclass of 'movement in host environment'

**Comment by mcourtot** [comment]
I still don't think this is the right solution, even more so based on @jimhu-tamu's comment. @jimhu-tamu can you point to the other issue you mention above? I'd lean towards updating the is_a link to a part-of, but more background would be useful.

**Comment by mcourtot** [comment]
Done revision 38387.
