### ISSUE TITLE
ntr: nuclear membrane organization during closed mitosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12728]
ntr: nuclear membrane organization involved in  mitotic nuclear division
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the nuclear inner or outer membrane during  GO:0007067.
comment: this process only occurs in organisms which undergo 'closed mitosis' without nuclear breakdown.
taxon restriction : Only in fungi?
ref: PMID:15147872

ntr: nuclear membrane biogenesis
standard def (other organelles exist)

ntr: nuclear membrane biogenesis  involved in mitotic nuclear division
standard def
taxon restriction : Only in fungi?
child of ntr: nuclear membrane biogenesis and
ntr: nuclear membrane organization during  mitotic nuclear division
ref: 	PMID:26869222

**Comment by mcourtot** [comment]
HI Val,

Can you clarify whether I should add the taxon restrictions or not?

Thanks,
Melanie

**Comment by mcourtot** [comment]
Added 
GO_0101024, nuclear membrane organization involved in mitotic nuclear division
GO_0101025, nuclear membrane biogenesis
GO_0101026, nuclear membrane biogenesis involved in mitotic nuclear division

**Comment by ValWood** [comment]
I don't know exactly  what the taxon restrictions should be. I'm assuming only in fungi but I don't know if there are really any other phyla which do open mitosis.

I'll ask a couple of people who work on this specifically.....

**Comment by ValWood** [comment]
OK, apparently  closed mitosis also in other taxa excavates, dicty, etc, so "never in metazoa"  is probably best we can do.

**Comment by mcourtot** [comment]
Thanks for the quick confirmation! 
All done revision 36285.
