### ISSUE TITLE
pexophagy parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12720]
pexophagy is a descendant of peroxisome organization. That doesn't seem quite right? It seems odd to have some of these proteins annoted to "peroxisime organization"

Delivery to the vacuole for degradation doesn't seem like disaasembly?

(note nucleophagy and ribophagy don't have this organization parent).

**Comment by ukemi** [comment]
Yup. instead we will make the disassembly part of the autophagic processes as discussed on this morning's autophagy call.
