### ISSUE TITLE
MP: (recently removed ) parentage in amino acid metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12721]
Tyrosine metabolic process no longer has "amino acid metabolic process"
 parentage.

GO:0000096 sulfur amino acid metabolic process no longer has "amino acid metabolic process"
 parentage.

neither has
GO:0006520 cellular amino acid metabolic process

GO:0009072 aromatic amino acid family metabolic process
is not a descendant of
GO:0006520 cellular amino acid metabolic process

The problem might be to do with when a grouping term included amino-acid derivatives, but this isn't always clear.....

**Comment by ukemi** [comment]
All of these are generated through ChEBI. I will have a look.

**Comment by ukemi** [comment]
It looks like the logical defs are using the acids rather than the conjugate bases and therefore they are not getting the amino-acid parents. We need to discuss this on an ontology call.

**Comment by dosumis** [comment]
@ukemi aren't we meant to have bridging axioms to map between these?

**Comment by ukemi** [comment]
That's what I thought. That's why I wanted to bring it up on the call.

**Comment by dosumis** [comment]
@cmungall  - where do ChEBI bridging axioms live? Have we dropped an import statement from the editors' file?

**Comment by ukemi** [comment]
Don't we build a separate file from ChEBI?

**Comment by dosumis** [comment]
gene_ontology_write.obo imports cheb_import.owl.  This lacks the equivalence axioms (GCIs).  But we have a file called bio_chebi.owl which has them.  bio_chebi.owl was last updated 19 months ago: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/bio-chebi.owl?view=log

**Comment by ukemi** [comment]
The GCIs for tyrosine and conjugate acids/bases are in bio_chebi. Is bio_chebi supposed to be used in chebi_import? It lists it as a source.

**Comment by dosumis** [comment]
We have no plain 'amino acid metabolic process' (!).  

& 'cellular amino acid metabolic process' has a rather odd def:

![image](https://cloud.githubusercontent.com/assets/112839/19234221/131edaea-8ee2-11e6-8f6a-97cc6a268ea3.png)  !!!
Not clear to me what makes it cellular.

**Comment by cmungall** [comment]
sounds like that's the issue but file a ticket for bio-chebi updates if that's an issue

**Comment by deustp01** [comment]
But at the near-neutral pH of mammalian cytosol, most amino acids are not anions but zwitterions - one dissociated carboxyl group (COO-) and one protonated amino group (NH3+) - electrically neutral but very polar. Exceptions are lysine and argine (an additional protonated group in their side chains, giving the whole molecules a net positive charge), and aspartate and glutamate (an additional COO- group in their side chains for a net negative charge).

The situation in an acidified vesicle like a lysosome (and what else in fungi?) or in unicellular organisms living in environments that are very acid or alkaline, or in the human stomach (acidic) will be different.

There's also an annotation problem here because biologist authors don't necessarily worry about these ionization states.

**Comment by ukemi** [comment]
Hi Peter,

"There's also an annotation problem here because biologist authors don't necessarily worry about these ionization states."

Exactly, that's why we made the equivalence axioms in bio-chebi. This way we can maintain the fuzziness about the ionization states as reported in the literature.

-D

**Comment by ukemi** [comment]
#12732

**Comment by ValWood** [comment]
> Not clear to me what makes it cellular.

Hi @dosumis , 
I know *vaguely* the history of this.
So historically, when  a decision was taken to place metabolic processes under "cellular metabolic process" and "amino acid metabolism" was placed under this term on the assumption (which sounds incorrect now) that all amino acid metabolism was cellular.

I guess we need  a non-cellular term too if this is not the case? Are  amino acids metabolised before import into the cell? I think at the time we mustn't have had any examples...

**Comment by ukemi** [comment]
Val's memory is correct. At one point we moved a large group of metabolic processes from generic to cellular.

**Comment by deustp01** [comment]
In humans, there are some processes that normally involve several cells. For example, catabolism of branched chain amino acids in muscle and other non-liver tissues generates glutamine and alanine among other things. Those two amino acids leave the muscle cells and travel to the kidney (glutamine, in stress states) or liver (alanine, in fasting states) where they are catabolized further, so the whole process combines events within each of two different cells and a transport event to get intermediates from place to place. Don't know how that fits with the constraints of "cellular metabolic process".

**Comment by ukemi** [comment]
Then we should probably move it back to the non-cellular parent.

**Comment by ValWood** [comment]
I think this is high priority because a lot of gene products which *should * map to amino acid metabolism no longer do. Will affect a lot of annotations.

**Comment by mcourtot** [comment]
Am I right that there are 2 outstanding items:
- [ ] bio-chebi import/update (see #12735)
- [ ] moving cellular metabolic process back under generic parent 

The latter should be discussed by editors (the former is being dealt with separately)

**Comment by mcourtot** [comment]
Hi @ValWood, we would like to discuss this on the upcoming editors call. Could you please help us by describing why it is important to have the distinction between cellular and non cellular amino acid processes? If you have a simple example/use case that would really be helpful for us to have an informed discussion, and make sure any resolution matches your application needs.

**Comment by mcourtot** [comment]
Thanks for the insights @ValWood - the corollary question is, taking into account only your own resource/curation, does it make a difference to be able to say 'cellular metabolic process' vs 'non-cellular'? Based on what you describe above 
> from a fungal perspective, everything is cellular, and so far all of the metabolism terms we use are cellular. 
it doesn't?

**Comment by ValWood** [comment]
We *could* ditch the  "cellular process (cell level)" split in GO, but it *is* a very sensible  and a useful axis of classification  for multicellular species. There are things that gene products do in cells which have consequences at greater levels of complexity (systems level processes).

 Note that this isn't about the "location where functions and processes occur" https://github.com/geneontology/go-ontology/issues/12796 mentioned here
which can be captured during  LEGO modelling (Or traditional annotation). It is about  the 'level' that the process occurs cell/tissue/system/organ/whole organism. 

Removing this could have potentially  on effects for GO users in multicellular species  who are interested in "cell level" biological phenomena.

This could also be a useful grouping for inference and for making connections between GO and phenotypes longer term, as annotation sets mature. It might be already a class  that is used to make judgement calls in PAINT annotation propagation (you should check with @pgaudet ). 

For fission yeast you are correct, if you take this axis of classification out of GO it won't affect a single celled eukaryote, but more generally I would  feel uncomfortable about this disappearing without broader consultation.

**Comment by deustp01** [comment]
Even some "single-cell" eukaryotes have multicellular organizations under some circumstances, that have some properties distinct from those of the component cells. Filamentous organization of S. cerevisiae is an example (though I don't remember what the filaments can do that single cells can't).

And in multicellular organisms with specialized tissues the distinction between processes that every cell carries out for itself (e.g., DNA replication) and ones that require cooperation among multiple cells or cell types is unavoidable, though certainly hard to handle consistently.

**Comment by dosumis** [comment]
> "Note that this isn't about the "location where functions and processes occur...   It is about the 'level' that the process occurs cell/tissue/system/organ/whole organism." 

It seems to me that location must at least be a large component of the distinction you would like to make. If we can capture the majority of your intended meaning by a definition in terms of location, wouldn't that be a good compromise?  

Extending the suggestion in #12796, how about:

A process occurring in exactly one cell.  Cell in this context includes cell surface and encapsulating structures belonging to the cell in question, such as a cell wall. 

This would exclude some classes currently under cellular (e.g. cell-cell communication; organization of ECM components), but it gets rid of some of much of the ambiguity. The cell surface clause is meant to allow for processes that start on or occur at the cell surface, e.g. signal transduction).

**Comment by dosumis** [comment]
@ValWood would I be correct in saying that the way you use 'cellular process' is to assume that all Pombe processes should be under this node?  We could try starting from there and working back?  Which processes in Pombe would not fall under cellular if we used a location-based definition?

**Comment by deustp01** [comment]
Looking at David OS's next-to-last comment, my earlier comment about interactions between cells when organized into filaments (or prokaryotic cells in biofilms) could mean that there are actually two processes, one carried out by single, self-reliant cells that gets the cellular metabolism tag (all of S. pombe under lab conditions) and one carried out by a collection of interdependent cells that is similar to the first but has some distinguishing feature that requires participation of more than one cell or cell type, that gets the metabolism tag.

**Comment by ValWood** [comment]
> Would I be correct in saying that the way you use 'cellular process' is to assume that all Pombe BPs should be under this class? If so, we could try starting from there and working back. 

Kind of.  As I said, it doesn't affect us a lot. However I believe it is  useful term to identify 
all of the  processes that "cell biology" is concerned with, and my sphere of interest is largely  the terms under this branch, so I am possibly biased.

So, all of the pombe proteins will be  back under the "cellular process" branch if the parentages in this ticket, and  https://github.com/geneontology/go-ontology/issues/12796 are addressed:

> Which processes in Pombe would not fall under cellular if we used a location-based definition

Except...
cell adhesion and flocculation (which clearly require more than one cell, so this is OK)

We also have a large number of proteases which are annotated only to "proteolysis". Proteolysis is not defined as "cellular" because of, for example, proteins  processed by proteases in the blood or the digestive system.  Proteolysis could not be defined as cellular based on location, but  the individual event performed by the protease is not  necessarily a "systems level process". One cell can produce a functional protease, (or metabolise an amino acid). I wonder if this can be part of the criteria?
I would expect all fission yeast proteases to eventually be classed as cellular  because  even though the protease may be excreted and exert its function extracellularly,  it  is still a process which occurs at the cell level (can be executed by a single cell- this might be the differentia?).


I guess we need to think about which gene products would be annotated to the "non cellular metabolism" terms. I can only think of the things which control the  process, maybe hormones etc. You could annotate the gene products responsible for the transport of the intermediates between cells,  (but these would be non-cellular transport, not non-cellular metabolism).

Aside from the terms mentioned above only 27 gene products are non-cellular process. I will inspect these now, but I suspect  most are annotation specificity issues at our end.

**Comment by ValWood** [comment]
>  it is still a process which occurs at the cell level (can be executed by a single cell- this might be the differentia?).

Which is what Peter said  a non cellular process "requires cooperation among multiple cells".

I wonder if all basic metabolism could be cellular, and if you really are annotating a gene product that only operates  at the tissue level (wouldn't this only apply to regulation anyway?), you could request a tissue level term, which would then require the insertion of a non cellular parent.
