### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12729]
The error is "2016-10-10 01:02:34,300 ERROR (CommandRunner:5077) Missing alternate ID: GO:0044458"

Root of the error:
- Paola was trying to make GO:1903887 an alternative ID of GO:0044458. Somehow, the opposite happened in the committed file (Primary:GO:1903887 , secondary:GO:0044458 )
- The following day, Helen Attrill mentioned this was causing an error in their pipeline, so Paola inverted the IDs, making GO:0044458 primary and GO:1903887secondary.

=> this broke the build, with the error mentioned above. We suspect there is a script that checks whether alt_ids disappear, and for the check GO:0044458 used to be an alt_id which "disappeared" from the file by being resurrected as primary.

**Comment by cmungall** [comment]
your hypothesis is correct,

owltools `--verify-changes` is executed against validated.obo

So it sounds like the changes are already out there in the release?

The options are to hack validated.obo, or to obsolete

**Comment by ukemi** [comment]
How about if Paola just creates a new term and then merges the current term into it? Then both identifiers will become alt identifiers and the annotations will be retained. It's a bit of a hack, but will it work?

**Comment by mcourtot** [comment]
Attempted hack revision 36221

**Comment by mcourtot** [comment]
Seemed to have worked - thanks for the help Chris!

**Comment by paolaroncaglia** [comment]
Hello again :-(
I broke the build again by merging those vesicle terms (2 couples of them). I *think* what I'm seeing is, the ID of the merged term 1) becomes secondary to the 'mergee' term, but also 2) stays there as a solitary ID with no information whatsoever attached. I'm fixing the other smaller errors derived from the merges (missing intersections), but until we get to the root of the problem, this won't go away... really don't know why this is happening, I paid super-extra-caution to those merges.

**Comment by paolaroncaglia** [comment]
@mcourtot , could you try your black magic again please? (I.e. hack validated.obo)

**Comment by paolaroncaglia** [comment]
For reference, this time the error is
GO:0016023 :: ERROR: has-definition: missing definition for id
  :: ERROR: ID-mentioned-twice:: GO:0016023
  :: ERROR: namespace-different-from-is_a-parent: GO:0016023 in file:/Users/paola/trunk/ontology/editors/go_inferences.obo, GO:0031982 in cellular_component

**Comment by paolaroncaglia** [comment]
Note, that error refers to the first merge only.
I'm sure there'll be another one for the merge of 'membrane-bounded vesicle' into 'vesicle'.
Original GO IDs:
GO:0031988 membrane-bounded vesicle
GO:0031982 vesicle

**Comment by mcourtot** [comment]
Hi @paolaroncaglia - interestingly perhaps, errors seem to stem from the go_inferences.obo file (which is what cause issues for @ukemi too)

I was able to fix by removing ghost stanzas that were created in gene_ontology_write.obo based on declarations in the go_inferences.obo. I don't know if you and @ukemi having the same issue editing means there is a problem with our inference pipeline or with OBO edit.

**Comment by mcourtot** [comment]
Build is fixed for now, but leaving ticket open to review inference issue if any?

**Comment by ukemi** [comment]
I just did a test merge in obo-edit and the resulting obo stanza looks fine. I suspect that the build problems arise in the pipeline downstream. No ghost terms after the merge and save.

**Comment by ukemi** [comment]
I think that whenever we merge, we need to check the inferences file for references to the merged terms. If they exist, they should be deleted. Then when the terms are merged, the cross-products need to be checked and edited as appropriate. Presumably then when the write file is committed, the ghost inferences will not exist in the inference file and the ghost terms won't be created.

**Comment by paolaroncaglia** [comment]
@mcourtot ,@ukemi
Added to agenda for today's editors call:
http://wiki.geneontology.org/index.php/Ontology_meeting_2016-10-13#SOP_when_merging_terms

**Comment by cmungall** [comment]
I think @ukemi's hypothesis is correct. Yet another unintended consequence of staying working in OE

**Comment by paolaroncaglia** [comment]
Discussed on editors call yesterday:
http://wiki.geneontology.org/index.php/Ontology_meeting_2016-10-13#SOP_when_merging_terms
*ACTION*: Paola will run through the steps with the next merge she needs to do (using OBO-Edit) - by next week. Will write up an SOP.
Closing now.
