### ISSUE TITLE
 ntr L-methionine import across plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12724]
PMID: 17556368 

descendent of
GO:1903813 L-methionine import into cell

(so it has a transmembrane transport parent)

Also need regulation but can do that with term genie

**Comment by mcourtot** [comment]
Hi @ValWood - can't this be created via TG, using the 'import across plasma membrane' template?

**Comment by ValWood** [comment]
Yep, I didn't know there was a plasma membrane template, will do...

**Comment by ValWood** [comment]
I missed it because it wasn't under "transmembrane transport"
it would be useful if terms which applied to more than one parent were mirrored under all relevant. Otherwise you need to search in the branched randomly until you locate....

@cmungall

**Comment by ValWood** [comment]
I can open a software ticket for this...
