### ISSUE TITLE
create vascular endothelial cell proliferation child of GO:0001935 endothelial cell proliferation

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12730]
Hi,

is it possible to create a child of GO:0001935 endothelial cell proliferation and call it vascular endothelial cell proliferation. This would follow the current pattern of GO:0001935 endothelial cell proliferation being a child of  GO:0050673 epithelial cell proliferation.

PMID: 23201774

GOC: BHF
GOC: BHF_telomere
GOC: nc 

Thanks

Nancy

**Comment by mcourtot** [comment]
Done revision 36269.

**Comment by NancyCampbell** [comment]
Hi Melanie,
May I have the GO ID for the new term please. Thanks.

**Comment by NancyCampbell** [comment]
found it via termgenie. please ignore request!
