### ISSUE TITLE
chebi_import no longer has bio-chebi GCIs

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12735]
chebi_import is a module constructed from bio-chebi.owl

previously, creation of the module would bring in all the relevant GCIs from bio-chebi. From the Makefile:

```
# see go/ontology/docs/ for full details
# we need to bring in axioms from both bio-chebi (conjugate base axioms) as well as substance-by-role
CHEBIRELS = RO:0000057 RO:0002233 RO:0002234 RO:0002313 RO:0002233 RO:0002332 RO:0002340  RO:0002345 BFO:0000051 RO:0000087 GOCHEREL:0000000 GOCHEREL:0000001 GOCHEREL:0000002  GOCHEREL:0000003 GOCHEREL:0000004
chebi_import.owl: $(IMPORT_SEED)
    owltools --use-catalog $< bio-chebi.owl --add-imports-from-supports --extract-module -s $(OBO)/go/extensions/bio-chebi.owl -c  --make-subset-by-properties -f $(CHEBIRELS) // --remove-annotation-assertions -r -l  --set-ontology-id $(OBO)/go/extensions/$@ -o $@
```

This seems to have stopped working. On plane wifi, can't investigate much further. One hypothesis is that SLME behavior changed between owlapi3 and 4. We really eed better documentation on the SLME as it is so central.

**Comment by ukemi** [comment]
MP: (recently removed ) parentage in amino acid metabolism #12721

**Comment by mcourtot** [comment]
@cmungall, @kltm Any news on the status of this?

**Comment by cmungall** [comment]
Should be fixed with r37060 and r37061

It turns out none of our hypotheses were correct. The SLME was working fine. The issue was a post-processing owltools step was being too aggressive in filtering out object properties, and ended up removing the GCIs

I changed this:

```
owltools --use-catalog $< bio-chebi.owl --add-imports-from-supports --extract-module -s (OBO)/go/extensions/bio-chebi.owl -c  --make-subset-by-properties -f $(CHEBIRELS) // -remove-annotation-assertions -r -l  --set-ontology-id $(OBO)/go/extensions/$@ -o $@
```

So `-n` is used instead of `-f` after the `--make-subset-by-properties` command. The former forces any axioms with dangling refs to be deleted. Not entirely clear why this worked at some point, it may well have been some time ago and it was only when we switched to dynamic imports we saw this

**Comment by cmungall** [comment]
Lots of changed inferences:

http://build.berkeleybop.org/job/build-go/7736/artifact/ontology/editors/go_inferences.diff/*view*/

**Comment by mcourtot** [comment]
For my own learning: could you give an example of such an axiom with dangling ref that would have been removed with the -f option? What does -n do instead?

**Comment by ukemi** [comment]
Me too!

**Comment by cmungall** [comment]
This is an obscure corner case to do with OPs. Better defined 
functioality should be added to robot
