### ISSUE TITLE
Obsolete terms in slims

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#12731]
I've just discovered that a number of GO slims refer to obsolete terms.

The offending entries are:

goslim_aspergillus	GO:0005624	obsolete membrane fraction

goslim_candida	GO:0005624	obsolete membrane fraction

goslim_pir	GO:0000267	obsolete cell fraction
goslim_pir	GO:0016585	obsolete chromatin remodeling complex
goslim_pir	GO:0019861	obsolete flagellum
goslim_pir	GO:0030528	obsolete transcription regulator activity
goslim_pir	GO:0043498	obsolete cell surface binding
goslim_pir	GO:0048196	obsolete plant extracellular matrix

goslim_plant	GO:0030528	obsolete transcription regulator activity

goslim_yeast	GO:0005624	obsolete membrane fraction

Plus:

gocheck_do_not_annotate	GO:0044460	obsolete flagellum part
gocheck_do_not_manually_annotate	GO:0097285	obsolete cell-type specific apoptotic process

**Comment by mcourtot** [comment]
Hi @tonysawfordebi,
I did report the issue a few months ago, and it was discussed at a recent ontology call, http://wiki.geneontology.org/index.php/Ontology_meeting_2016-03-10. As per the minutes, editors didn't consider that having obsolete terms in slim was an issue per se, however annotations should be filtered out.

**Comment by mcourtot** [comment]
Moved to the annotation tracker at https://github.com/geneontology/go-annotation/issues/1452
