### ISSUE TITLE
NTRs for ciliary CC terms: paraflagellar rod and mastigoneme

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12733]
Following up on a meeting with @JohnvanDam and Toby Gibson, we propose to add the following new terms for specific ciliary components, as a use case of classes useful to researchers annotating ciliary images:

GO:NEW1 paraflagellar rod  
is_a supramolecular complex, part_of 9+2 motile cilium
only_in Euglenozoa (NCBITaxon:33682)
def: A large lattice-like axial structure found in some flagellated protists which extends alongside the axoneme. Protein components of the paraflagellar rod are likely implicated, among other, in adenine nucleotide signalling and metabolism, and in calcium signalling.
GOC:cilia, PMID:19879876, PMID:26688619, PMID:26199333 
related synonym: PFR 

GO:NEW2 mastigoneme 
is_a supramolecular complex, part_of motile cilium
only_in [union class of Stramenopiles (NCBITaxon:33634) + Cryptophyta (NCBITaxon:3027)]
def: A hair-like structure covering the flagella found in some algae (heterokonts and cryptophytes). It is approximately 15 nm in diameter, and usually consist of a tubular shaft that itself terminates in smaller hairs. It is composed of glycoproteins and, likely, carbohydrates. Mastigonemes may assist in locomotion by increasing the surface area of a flagellum.
GOC:cilia, https://en.wikipedia.org/wiki/Mastigoneme, PMID: 943397

**Comment by paolaroncaglia** [comment]
Added as follows:

 [Term]
+id: GO:0097740
+name: paraflagellar rod
+namespace: cellular_component
+def: "A large lattice-like axial structure found in some flagellated protists which extends alongside the axoneme. Protein components of the paraflagellar rod are likely implicated, among other, in adenine nucleotide signalling and metabolism, and in calcium signalling." [GOC:cilia, PMID:19879876, PMID:26199333, PMID:26688619]
+synonym: "PFR" RELATED []
+is_a: GO:0099080 ! supramolecular complex
+relationship: only_in_taxon NCBITaxon:33682 ! Euglenozoa
+relationship: part_of GO:0097729 ! 9+2 motile cilium

+[Term]
+id: GO:0097741
+name: mastigoneme
+namespace: cellular_component
+def: "A hair-like structure covering the flagella found in some algae (heterokonts and cryptophytes). It is approximately 15 nm in diameter, and usually consist of a tubular shaft that itself terminates in smaller hairs. It is composed of glycoproteins and, likely, carbohydrates. Mastigonemes may assist in locomotion by increasing the surface area of a flagellum." [GOC:cilia, http://en.wikipedia.org/wiki/Mastigoneme, PMID:943397]
+is_a: GO:0099080 ! supramolecular complex
+relationship: part_of GO:0031514 ! motile cilium

**Comment by paolaroncaglia** [comment]
Requested Cryptophyta in imports_requests.obo

**Comment by paolaroncaglia** [comment]
Left to do: when Cryptophyta is available,
- [ ] create union class of Stramenopiles (NCBITaxon:33634) + Cryptophyta (NCBITaxon:3027)
- [ ] add link: GO:0097741 'mastigoneme' only_in [union class of Stramenopiles (NCBITaxon:33634) + Cryptophyta (NCBITaxon:3027)]
Then close.

**Comment by paolaroncaglia** [comment]
Hi @cmungall ,

GO:0097741 'mastigoneme' is found only_in [union class of Stramenopiles (NCBITaxon:33634) + Cryptophyta (NCBITaxon:3027)].
I’ve never created an NCBITaxon_Union, so may I please double-check the procedure: is it correct to add it in ncbitaxon_import.obo? As

[Term]
id: NCBITaxon_Union:0000031
name: Stramenopiles or Cryptophyta
is_a: NCBITaxon:2759 ! Eukaryota
union_of: NCBITaxon:33634 ! Stramenopiles
union_of: NCBITaxon:3027 ! Cryptophyta

Thanks.

**Comment by paolaroncaglia** [comment]
@cmungall ,

GO:0097741 'mastigoneme' is found only_in [union class of Stramenopiles (NCBITaxon:33634) + Cryptophyta (NCBITaxon:3027)].
I’ve never created an NCBITaxon_Union, so may I please double-check the procedure: is it correct to add it in ncbitaxon_import.obo? As

[Term]
id: NCBITaxon_Union:0000031
name: Stramenopiles or Cryptophyta
is_a: NCBITaxon:2759 ! Eukaryota
union_of: NCBITaxon:33634 ! Stramenopiles
union_of: NCBITaxon:3027 ! Cryptophyta

Or otherwise? Many thanks.

**Comment by paolaroncaglia** [comment]
I'll set to 'pending' while I wait to hear from @cmungall .

**Comment by cmungall** [comment]
This has to be added to go-taxon-groupings-edit.owl

**Comment by cmungall** [comment]
I did this. r37045

**Comment by cmungall** [comment]
Yes, go ahead and create, but don't use it yet. I want to make sure the 
rest of the downstream pipeline works, including using full DL reasoning 
to materialize the hierarchy

**Comment by paolaroncaglia** [comment]
Thanks @cmungall .
