### ISSUE TITLE
Update bio-chebi and chebi-import

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12732]
It looks as if the pipeline that generates bio-chebi.owl and chebi-import.owl has broken. We should update bio-chebi and check to make sure that the GCIs that are expressed in it are being incorporated into the chebi import. My understanding is that chebi-import is the subset of bio-chebi that contains chebi terms used in gene_ontology_write.

As an example, terms like tyrosine metabolic process are not being inferred to be amino acid metabolic process because it looks like there is no GCI declaring equivalence between tyrosine and tyrosinate. If I manually switch the equivalence axiom of tyrosine metabolic process to use tyrosinate instead of tyrosine, then the inference to amino acid is made.

**Comment by cmungall** [comment]
https://build.berkeleybop.org/job/build-bio-chebi
is triggered by
https://build.berkeleybop.org/job/build-chebi/
which is triggered by changes to the source chebi.obo

here is the polling log:
https://build.berkeleybop.org/job/build-chebi/scripttriggerPollLog/

but we're getting a strange jenkins error about the workspace folder not being there

@kltm any ideas?

I'm going to force a build now (note many of the ontology group have permission to do this)

But it would be good to simplify the pipeline here, the polling method seems complex.

**Comment by kltm** [comment]
@cmungall can you give me a reference for the errors? Both appear to be blue recently...

**Comment by cmungall** [comment]
There is no problem with the build itself, which is why it's all blue. See above, the problem is that it isn't being triggered (with the exception of the one I just manually triggered).

The polling is not working. See https://build.berkeleybop.org/job/build-chebi/scripttriggerPollLog/

**Comment by kltm** [comment]
Is that a space after "dicer"?
```
Looking nodes where the poll can be run.
Looking for a node to the restricted label dicer .
Can't find any eligible slave nodes.
Trying to poll on master node.
```

**Comment by kltm** [comment]
The job is to be serviced by label "arbitrary_pin_01", which is only serviced by grinder. In spite of that, it is apparently first trying dicer (or "dicer ", which might be weird) and then apparently falling back to mill/master.

**Comment by cmungall** [comment]
OK, this is a false alarm in any case.

The downstream job does not commit the changed file:
https://build.berkeleybop.org/job/build-bio-chebi/configure

It looks like Heiko manually committed this file, until March 2015:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/bio-chebi.owl?view=log

**Comment by kltm** [comment]
Actually, I'm a little surprised here--I didn't know we had or used ScriptTrigger stuff. I had thought that we avoided it...

Looking at the script, I could see that failing if it tried to run on mill--mill is not like the others.
The dicer thing I don't get though...

**Comment by cmungall** [comment]
@kltm Thanks for checking, the pin behavior is odd. But we can call off the bughunt for now. I will disable these jobs, seems like the only function they every fulfilled was as an early validation. But fairly pointless if the commit was manual.

Leaving ticket open while I come up with what we do next

**Comment by cmungall** [comment]
I assume that we attempted to get this working, and then abandoned the attempt.

Yes we should avoid this in future. A straightforward wget/curl plus check for difference in file content as part of the normal build process seems the way we should go

**Comment by cmungall** [comment]
general FYI

we have to keep this running
https://build.berkeleybop.org/job/build-chebi/

until these resolved
https://github.com/OBOFoundry/purl.obolibrary.org/issues/250
https://github.com/ebi-chebi/ChEBI/issues/3202

**Comment by dosumis** [comment]
Confused.  Isn't the main issue the absence of imports pulling in equivalence GCIs into the editor's file?  Broken build seems like a secondary issue.

**Comment by cmungall** [comment]
@dosumis  - you are right. I created a new ticket: #12735
