### ISSUE TITLE
repair of mono-orientation defects

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12736]
We have 2 terms

GO:0098783 correction of merotelic kinetochore attachment, mitotic
Definition
The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles (otherwise known as merotelic attachment to the spindle). 
PMID:21306900

GO:1990598 repair of mitotic mono-orientation defects
The mitotic cell cycle process where mono-orientation defects are corrected in order to ensure sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles. 
PMID:15525536

currently the ontology looks like this:

![correct parents](https://cloud.githubusercontent.com/assets/7359272/19434588/3917d900-945e-11e6-8d94-df89499f661e.jpg)

These should be related more closely.

This is the biology:
![syntelic monotelic merotelic ampitelic](https://cloud.githubusercontent.com/assets/7359272/19434604/5624fa28-945e-11e6-9f09-9e0733150b2c.jpg)

**Comment by ValWood** [comment]
So,

If merotelic,monotelic and syntelic attachements are all monoorientation defects,
GO:0098783 should be is_a  GO:1990598 

GO:1990598  should move to be a descendant of GO:0007080 (mitotic metaphase plate congression)

We should use the same primary term name for both (correction or repair) and make the other names synonyms.

(Or, I don't really know if its 2 processes or the same process, so maybe a single term would be sufficient for all corrections?)

Assigning to  @dosumis  as I think you added these terms for me originally?

**Comment by mah11** [comment]
I suspect it would help if the GO:1990598 def included some gloss to explain what mono-orientation defects are. If I understand correctly, mono-orientation means that both sister kinetochores are attached to MTs from one spindle pole (good in meiosis I; bad in mitosis and meiosis II).

> If merotelic,monotelic and syntelic attachements are all monoorientation defects ...

Monotelic isn't (that's where only one kinetochore is attached at all), and I'm not sure about merotelic - it depends on whether "mono-orientation" means both kinetochores are ONLY attached to MTs from one pole or not (iow, does mono-orientation subsume merotelic and syntelic, or is it a synonym for syntelic? I don't know.). The text def of GO:0098783 also doesn't exclude a situation where one kinetochore connects to both poles while the other is unattached, but the illustration doesn't show that and I don't know if it ever happens.

There's probably room for a generic "repair/correction of attachment defects" term in between GO:0007080 ! mitotic metaphase plate congression and the terms for fixing specific types of problem.

I do agree that more consistent term names would be nice ("mitotic ... attachment" vs. "attachment, mitotic" as well as repair vs. correction).

**Comment by ValWood** [comment]
OK so it seems
i) monotelic is mono-orientated )bad in mitosis and meiosis II

How about
- [ ] Add new terms
- GONEW1 repair/correction of kinetochore microtubule attachment defects
- GONEW 2 repair/correction of mitotic kinetochore microtubule attachment defects

- [ ] improve def of
GO:1990598 repair of mitotic mono-orientation defects

to  include some gloss to explain what mono-orientation defects are. If I understand correctly, mono-orientation means that both sister kinetochores are attached to MTs from one spindle pole (good in meiosis I; bad in mitosis and meiosis II).

- [ ]  Move  GO:1990598 under  GONEW2

- [ ]  rename GO:0098783 correction of merotelic kinetochore attachment, mitotic
consistently

- [ ] Add correction/repair synonyns to all

**Comment by ValWood** [comment]
This one was ready to go when @dosumis  finished.
Stealing  for @pgaudet  jamboree

**Comment by ValWood** [comment]
GO:0090699    correction of merotelic kinetochore attachment, meiosis I
rename to 
repair  of merotelic kinetochore attachment, meiosis I
