### ISSUE TITLE
term name consistency, kinetochore attachment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12738]
Can
"regulates" term and "negatively regulates" term
have the term name constructed in the same way as the parent
(attachment of mitotic spindle microtubules to kinetochore)

![match](https://cloud.githubusercontent.com/assets/7359272/19435972/893b7296-9465-11e6-9b53-1d325f40e104.jpg)

**Comment by paolaroncaglia** [comment]
Done.
