### ISSUE TITLE
NTR: Positive regulation of replication fork progression

### ISSUE THREAD

**Issue by ethanclary143** [geneontology/go-ontology#12748]
I am a CACAO student trying to annotate the paper PMID: 27611590 and the Schizosaccharomyces pombe protein (pfh1) that I am trying to annotate decreases the amount of pausing experienced by the replication fork at hard to replicate areas. I tried to use the GO term GO:0031297 (replication fork processing) but nowhere in the paper does it say that the protein restarts the act of replication, only that replication fork pausing is decreased. I was hoping that a term could be created to accommodate this issue. Perhaps something along the lines of positive regulation of replication fork progression, DEFINITION: Any process that activates or increases the frequency, rate or extent of replication fork progression. 

GO:0097046 (replication fork progression beyond termination site) exists however the term that I need should be a parent of this term.

**Comment by mcourtot** [comment]
Hi @ValWood : do you know of cases where the replication fork processing does *not* result in replication restarting? I would have thought decreasing pausing would fall under 'restarting', but I can see how this is a bit ambiguous and you're the expert :) 
Current definition for replication fork processing reads 'The process in which a DNA replication fork that has stalled is restored to a functional state and replication is restarted. The stalling may be due to DNA damage, DNA secondary structure, bound proteins, dNTP shortage, or other causes.", and @ethanclary143 mentions issues with the "replication is restarted" part of this definition.

**Comment by ValWood** [comment]
Well I'm not the expert here @mah11  is ;)

But I can tell you that the author has curated this paper (not yet approved)

https://curation.pombase.org/pombe/curs/c131e5fc09dccabc/ro

and used the term "replication fork processing"

Val

**Comment by mah11** [comment]
> do you know of cases where the replication fork processing does _not_ result in replication restarting?

No; I would say that replication fork processing does always include restarting, as the GO:0031297 definition says.

> I would have thought decreasing pausing would fall under 'restarting'

I think an observation of decreased pausing could result from either quicker clearance of paused forks (i.e. quicker "replication fork processing") or from forks not pausing as often in the first place. If a fork doesn't pause it won't need to be restarted.

I haven't (yet) read the paper carefully, but from a quick glance it seems that the actual observation was the converse - depleting Pfh1 causes _increased_ pausing, which suggests that Pfh1 may contribute to fork processing, or help forks avoid having to pause in the first place, or both. I don't yet know if other data in the paper form part of the author's willingness to use the fork processing term.

If we want to use a term that isn't specific to processing forks that have already paused, a term for regulation of DNA strand elongation might work (choose one at the appropriate level of specificity, most likely regulation of GO:1902983). I'm not sure it's worthwhile for GO to try to capture anydistinction between strand elongation and fork progression. (I know nothing of the history of GO:0097046 including why its name uses "fork progression".)

**Comment by ValWood** [comment]
GO:0097046 replication fork progression beyond termination site
sounds like a process which has gone wrong? is it  just a mutant phenotype?

**Comment by paolaroncaglia** [comment]
Hi @ethanclary143 ,
Apologies, I haven’t had a chance to work on this ticket (and on 2 more from you) until now, and I’ll be on leave next week. If they can't wait until then, please comment here. Thanks for your patience.

**Comment by paolaroncaglia** [comment]
Dear @ethanclary143 ,

Based on earlier comments in this ticket, it seems that you could annotate to the existing term GO:0031297 ‘replication fork processing’, or to a regulation term for GO:0022616 ‘DNA strand elongation’ or one of its specific children. If you choose the latter option, and there is no existing regulation term at the level you require, one should be requested via TermGenie (TG, http://go.termgenie.org). I presume you don’t have a TG account. Routine curators usually have one, but for CACAO competitions this is not strictly required, so I can create one for you if you let me know which one you need. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @ValWood and @srengel ,
Wrt Val's comment 
"GO:0097046 replication fork progression beyond termination site
sounds like a process which has gone wrong? is it just a mutant phenotype?"
That might be the case, based on its supporting PMID (https://www.ncbi.nlm.nih.gov/pubmed/?term=20797631). I added that term early on (https://github.com/geneontology/go-ontology/issues/8557); it was requested by Maria Costanzo who is no longer at SGD, so I'm asking @srengel to take a look and comment here please.

**Comment by srengel** [comment]
re the question that perhaps the GO:0097046 term itself is just a mutant phenotype, i would say not.  looking at PMID: 20797631, there is a section 'Rrm3 Is Required for Fork Progression across TERs', and figure 3 indicates that knocking out RRM3 ablates this.  that is, fork progression through the tough areas stops without Rrm3. previous papers have reported similar findings.

**Comment by ValWood** [comment]
The GO term still sounds slightly strange. If the process is really enabling replication through difficult regions "replication fork progression beyond termination site"  seems an odd way to describe it. I am sure we have equivalent, but I'm not sure what terms we have used for this..I'll see if I can find anything....

**Comment by ValWood** [comment]
i.e it sounds as thought he process is "slowing replication"...(maybe we used maintenance of GO:1902298	cell cycle DNA replication maintenance of fidelity?)

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
Thanks for your feedback. I propose that if you’d like to suggest a different name for GO:0097046 ‘replication fork progression beyond termination site’, or any other course of action for that term, please open a new ticket with all necessary details. BTW, I think we’ve highlighted the 'replication' branch as in need of work and experts'  help before - maybe something to keep in mind for future ontology development, if others feel the same.

**Comment by paolaroncaglia** [comment]
Hi @ethanclary143 ,
I’ll close this ticket now. Should you need a new ‘regulation’ term, please request/have someone request it via TermGenie, or open a new ticket, as detailed in my previous comment to you. Thanks.
