### ISSUE TITLE
GO:0043936 asexual sporulation resulting in the formation of a cellular spore

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12744]
There are two issues with this term. First, it contains two redundant parts. "sporulation" by definition is the process of producing spores. Perhaps this term could be modified and would be improved by specifying "asexual sporulation resulting in the formation of a viable spore" or "asexual reproduction resulting in the formation of a cellular spore." The latter does not change the meaning and likely would not involve any reannotation.

The second issue is that Candida species does not reproduce by sporulation. The annotations from CGD are by homology with Aspergillus or other fungal species without taxon constraints for process. Candida albicans does make a form of non-reproductive chlamydospores but these are terminal spores and have never been observed to germinate. For historical reasons, the terms "blastoconidia" and "blastospore" are used because early studies of morphology were visual and C. albicans yeast when subject to certain stimuli produce a dramatic elongated hypha that resembles germ tube formation of proper spores. Again, these terms are based on visual observations and similarity. C. albicans and other Candida species are non-sporulating yeasts. 

At CGD, the goal is to relate the functions of orthologs without regard to the existence of the process in the recipient species. In the case of orthologs involved in mating, this information is useful even in Candida strains that have not been observed to mate, such as C. glabrata. Prior to 2000, C. albicans had not been observed to mate and was considered a non-mating obligate diploid species until it was discovered that opaque cells from W-O switching were the mating competent form of C. albicans. So for this purpose, knowing what genes are involved in mating in S. cerevisiae or C. albicans are of interest to those searching for conditions under which other Candida could mate. I am under under the impression that the goal of inferring annotations is not the same as the manner in which CGD applies IEA to orthologs. We should consider whether taxon constraints should be applied. Filamentous growth is another process that is present in C. albicans but not C. glabrata and others. The same issue holds true for GO:0043935 'sexual sporulation resulting in the formation of a cellular spore' and the regulation terms.

Should this second issue be added to the GO Annotation Tracker?

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis,

Wrt your first point:
“There are two issues with this term. First, it contains two redundant parts. "sporulation" by definition is the process of producing spores. Perhaps this term could be modified and would be improved by specifying "asexual sporulation resulting in the formation of a viable spore" or "asexual reproduction resulting in the formation of a cellular spore." The latter does not change the meaning and likely would not involve any reannotation.”
The current wording is nicely consistent with the hierarchy:

asexual sporulation
[is_a child] asexual sporulation resulting in formation of a cellular spore
[is_a child] asexual sporulation resulting in formation of a multicellular or syncytial spore

Therefore I’d rather not rename the term, but I’ve added an exact synonyms "asexual reproduction resulting in the formation of a cellular spore" and a broad synonym ”asexual sporulation resulting in the formation of a viable spore”.
I’ll address your other points next. Thanks.

**Comment by dianeoinglis** [comment]
That works for me. Thanks

**Comment by pfey03** [comment]
Hi @dianeoinglis and @paolaroncaglia,

Just to ask, even though we usually annotate to the parent 'GO:0030435 sporulation resulting in formation of a cellular spore'. Is 'asexual sporulation' synonym to 'asexual reproduction'? For example Dicty's sporulation, I would think could be annotated to 'asexual sporulation', but it's not reproductive.

It's not a problem as we annotate to the parent to be on the safe side, just wanted to chip in, sorry it's a bit late.

**Comment by paolaroncaglia** [comment]
Hi @pfey03 ,
‘sporulation resulting in formation of a cellular spore’, and its parent ‘sporulation’, are not linked to reproduction (sexual or asexual), so those indeed look like the best term to use for Dicty. ‘asexual sporulation’ instead is both is_a ‘sporulation’ and is_a ‘asexual reproduction’. So it’s not a synonym, it’s a child. ‘sporulation’ is not linked to reproduction exactly so that it can cover non-reproductive instances as well as reproductive ones. I added the exact synonym ‘asexual reproductive sporulation’ to ’asexual sporulation’ to make that more explicit.
I’ll close now, but feel free to re-open if you still have concerns. Thanks.
