### ISSUE TITLE
missing link between regulation of plasma lipoprotein particle levels & catabolic process (?)

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12747]
Hi,

Should there be a link at some level between  GO:0097006 regulation of plasma lipoprotein particle levels (or its children) and  GO:0009056 catabolic process (or its children)? I am attaching an image of what I can see on QuickGO.

@RLovering 

GOC: BHF
GOC: nc 

<img width="1364" alt="link" src="https://cloud.githubusercontent.com/assets/12081136/19479346/28ab5ffc-953e-11e6-9260-389573697691.png">

**Comment by cmungall** [comment]
Hi Nancy - not sure why this would be the case?

We do traverse to plasma lipoprotein particle disassembly, via has-part - but disassembly is not necessarily a catabolic process

Think of it this way - if there was a link involving isa or partof, then queries for genes involved in catabolic processes may return genes associated with plasma lipoprotein particle clearance, are all of those genes catabolic?

**Comment by NancyCampbell** [comment]
Hi Chris,
I see what you mean. The former does not involve breaking down a bond and releasing energy in the chemical sense. I misunderstood that bit.
Thanks for the clarification.
