### ISSUE TITLE
OTR: capturing targets of endocytosis

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12746]
@tberardini, @ukemi , @dosumis (re. ontology)
@sabrinatoro, @doughowe, @ukemi, @hdrabkin, @NancyCampbell, @RLovering  (re. annotations)

I’m looking at this TG request by @NancyCampbell:

[Term]
id: GO:1905565
name: regulation of receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport." [GO_REF:0000058, GOC:BHF, GOC:nc, GOC:TermGenie, PMID:22848640]
synonym: "regulation of receptor-mediated endocytosis of LDL" EXACT [GOC:TermGenie]
synonym: "regulation of receptor-mediated endocytosis of low-density lipoprotein involved in cholesterol transport" RELATED [GOC:TermGenie]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0090118 ! receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport

Its parent GO:0090118 was added by Tanya in 2009 following the ASCB conference:

[Term]
id: GO:0090118
name: receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport
namespace: biological_process
def: "A receptor-mediated endocytosis process that results in the uptake of low-density lipoprotein by cells." [GOC:ascb_2009, GOC:dph, GOC:tb]
synonym: "receptor-mediated endocytosis of LDL" EXACT [GOC:ascb_2009, GOC:dph, GOC:tb]
synonym: "receptor-mediated endocytosis of low-density lipoprotein involved in cholesterol transport" RELATED [GOC:dph]
is_a: GO:0006898 ! receptor-mediated endocytosis
is_a: GO:0044765 ! single-organism transport
relationship: part_of GO:0032367 ! intracellular cholesterol transport
relationship: part_of GO:0034383 ! low-density lipoprotein particle clearance
created_by: tanyaberardini
creation_date: 2009-12-07T12:06:05Z

Years later, we’d probably want to capture the targets of endocytosis via annotation extensions rather than embedding them in the term name. Correct? (If yes, in this case, GO:0034362 ‘low-density lipoprotein particle’ should probably be used.) Unless the mechanisms of receptor-mediated endocytosis are different depending on what material is engulfed, which is probably not the case, but I’m not 100% sure. Should GO:0090118 ‘receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport’ be renamed ‘receptor-mediated endocytosis involved in cholesterol transport’, and its existing annotations be added AEs accordingly? The term currently has 7 manual experimental annotations (ZFIN, MGI, BHF-UCL). 

I’ll leave the TG requests for regulation terms as they are for now, pending decision on GO:0090118.

**Comment by NancyCampbell** [comment]
Hi Paola,
Thanks for the valid points you are making.
I think in this case the LDL aspect of this process doesn’t need to be stated because the key thing is to have a sensible sized gene group that can be seen in an enrichment, and I think this will be the case here.
 
To revise the existing annotations, to the more general new term (receptor-mediated endocytosis involved in cholesterol transport): this would mean adding the CC term low-density lipoprotein particle in the AE field AND adding part_of GO:0034383 ! low-density lipoprotein particle clearance to the AE field and also making sure that this term is directly associated with the protein currently annotated to this term (in theory the GOC would create the annotation if it is added in the AE field.)
 
In theory the term could be reduced further to receptor-mediated endocytosis with AE part_of to GO:0032367 ! intracellular cholesterol transport, but it would be nice to have the term receptor-mediated endocytosis involved in cholesterol transport.

What do you think?

thanks

Nancy

**Comment by sabrinatoro** [comment]
Hello Paola, 
I agree with your proposal. 
However, ZFIN does not curate annotation extension. Therefore, we would lose some specificity by updating our annotation to “receptor-mediated endocytosis involved in cholesterol transport”.
Note that ZFIN has only 1 annotation.
Thanks
Sabrina

**Comment by paolaroncaglia** [comment]
Thank you @NancyCampbell  and @sabrinatoro ,

I’ll go ahead with my plan to 

- [ ] rename ‘receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport’ as ‘receptor-mediated endocytosis involved in cholesterol transport’ (I’ll leave the original name as a synonym). Annotations wouldn’t need to be moved, but
- [ ] @NancyCampbell  or @RLovering would have to update the BHF-UCL ones please as Nancy outlined above
- [ ] @ukemi or @hdrabkin would have to update MGI annotations similarly please
- [ ] @sabrinatoro , is there any existing low-density lipoprotein particle-related term that you could use for co-annotation perhaps?

@NancyCampbell , wrt the regulation terms you requested via TG: 
- [ ] I will obsolete them because they contain many synonyms that would have to be edited to reflect the re-naming of GO:009011, and I will then
- [ ] request new ones and commit them myself, and paste their IDs here for you to use.

**Comment by NancyCampbell** [comment]
Thanks Paola.

**Comment by paolaroncaglia** [comment]
Hi @NancyCampbell ,
I just renamed ‘receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport’ as ‘receptor-mediated endocytosis involved in cholesterol transport’. I was going to add regulation terms, but I'm having second thoughts and would like to double-check - would you use them, or could you capture the info from PMID:22848640 with a Noctua model instead? The reg. terms would be a bit clunky (regulation of process x involved in process y). Thanks.

**Comment by paolaroncaglia** [comment]
Also, @NancyCampbell , could you please confirm that you updated/will update the BHF-UCL annotations to GO:0090118 as you outlined here: https://github.com/geneontology/go-ontology/issues/12746#issuecomment-254848438

**Comment by NancyCampbell** [comment]
Hi. Paola. Yes I will update the terms with new pattern. Thanks.

**Comment by NancyCampbell** [comment]
I don't use Noctual I am afraid. Just P2G! :-)
it would be preferrable to create the regulation terms if possible. What do you think?
thanks.

**Comment by paolaroncaglia** [comment]
Added:
ID: GO:1905600 Label: regulation of receptor-mediated endocytosis involved in cholesterol transport
ID: GO:1905601 Label: negative regulation of receptor-mediated endocytosis involved in cholesterol transport
ID: GO:1905602 Label: positive regulation of receptor-mediated endocytosis involved in cholesterol transport

**Comment by paolaroncaglia** [comment]
@hdrabkin or @krchristie
Please consider if you'd like to add annotation extensions to the MGI annotations to GO:0090118 following its rebranding from old ‘receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport’ to new ‘receptor-mediated endocytosis involved in cholesterol transport’. See Nancy's example here https://github.com/geneontology/go-ontology/issues/12746#issuecomment-254848438. Thanks.

**Comment by paolaroncaglia** [comment]
@sabrinatoro , 
Please consider if you'd like to co-annotate the single ZFIN GP associated with GO:0090118 to any of the existing 'low-density lipoprotein particle'-related terms, following the renaming of GO:0090118 from old ‘receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport’ to new ‘receptor-mediated endocytosis involved in cholesterol transport’. See Nancy's example here #12746 (comment). Thanks.

**Comment by paolaroncaglia** [comment]
Note for self: once MGI and ZFIN reply, I can close this ticket.

**Comment by sabrinatoro** [comment]
@paolaroncaglia 
I have co-annotate the existing ZFIN annotation for GO:0090118.

[I couldn't add this comment here last week when Github was down, and forgot to do it later. Thank you for checking!]

**Comment by paolaroncaglia** [comment]
Thanks @sabrinatoro !

**Comment by NancyCampbell** [comment]
Hi Paola.
We have fixed ours.

**Comment by paolaroncaglia** [comment]
@hdrabkin or @krchristie
Please consider if you'd like to add annotation extensions to the MGI annotations to GO:0090118 following its rebranding from old ‘receptor-mediated endocytosis of low-density lipoprotein particle involved in cholesterol transport’ to new ‘receptor-mediated endocytosis involved in cholesterol transport’. See Nancy's example here https://github.com/geneontology/go-ontology/issues/12746#issuecomment-254848438. Or, please let me know if you've done that already, so I can close this ticket. Thanks!

**Comment by paolaroncaglia** [comment]
@ukemi @krchristie @hdrabkin (for MGI)
Could you please take a look at my comment above, with many thanks in advance.

**Comment by paolaroncaglia** [comment]
Note for self: I will assume that MGI curators have looked into adding AEs as suggested by now. If not, this is not a blocker (there are only 2 MGI annotations to GO:0090118). The ontology work for this ticket has been completed, so I will close it.
