### ISSUE TITLE
NTR negative regulation of ferrichrome biosynthetic process, in response to iron

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12740]
negative regulation of ferrichrome biosynthetic process, in response to iron

@mcourtot 
discussed with Melanie for the TG obsoletion GO:1905545 but she said she was travelling this week so I should put my new request here.

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,
 
Yes @mcourtot mentioned something, but I'm afraid I don't know all the details of that conversation, so let's see: 

id: GO:1905525
name: regulation of ferrichrome biosynthetic process by negative regulation of transcription from RNA polymerase II promoter in response to iron

was added recently, by @ukemi I think. Is that going to stay? Do we need a term for 'ferrichrome biosynthetic process in response to iron' and then its regulation children? If so, should the supporting PMID be the same as in the original TG request (PMID:20435771)? Thanks.

**Comment by ukemi** [comment]
Hi @paolaroncaglia 

I thought that @mcourtot was going to obsolete the term that I had approved. But maybe she changed her mind. 

-D

**Comment by ValWood** [comment]
I would rather we didn't have these types of terms, can do much more neatly like this:
https://github.com/geneontology/go-ontology/issues/12739

at the moment  sometimes they are in and sometimes they are out, nobody knows whether to request or not, and all the annotations are done differently (which makes training a community to annotate very difficult!).

**Comment by paolaroncaglia** [comment]
Hi @ukemi ,
@mcourtot is at a conference this week, so she may not have changed her mind, but rather not have had the time to obsolete. I'll ask her when she's back.

**Comment by Antonialock** [comment]
Hi Paola,
GO:1905525 can be obsoleted
The new term is:
negative regulation of ferrichrome biosynthetic process in response to iron

The new term does not specify that it is "by negative regulation of transcription" - I don't need to specify this bit since I annotate the TF to the MF "transcriptional repressor activity"  + part_of GONEW: negative regulation of ferrichrome biosynthetic process in response to iron

**Comment by Antonialock** [comment]
I don't think the term request needs the pending label?

**Comment by paolaroncaglia** [comment]
That was in waiting to hear back from @mcourtot if she was planning to do the obsoletion herself or not :-)

**Comment by Antonialock** [comment]
I'm sure she just missed it..

**Comment by paolaroncaglia** [comment]
@Antonialock ,
OK. Could you please confirm what term you need exactly:

is it
(negative regulation of ferrichrome biosynthetic process) (in response to iron)
which would itself be is_a (regulation of ferrichrome biosynthetic process) (in response to iron)

or is it
(negative regulation of) (ferrichrome biosynthetic process in response to iron)?
I presume it’s the former,

Thanks,
Paola

**Comment by Antonialock** [comment]
Yep this looks correct :
(negative regulation of ferrichrome biosynthetic process) (in response to iron)
which would itself be is_a (regulation of ferrichrome biosynthetic process) (in response to iron)

**Comment by paolaroncaglia** [comment]
Added 
ID: GO:1905568 Label: regulation of ferrichrome biosynthetic process
ID: GO:1905569 Label: negative regulation of ferrichrome biosynthetic process
ID: GO:1905570 Label: positive regulation of ferrichrome biosynthetic process

**Comment by paolaroncaglia** [comment]
Added: 
 [Term]
+id: GO:0097739
+name: negative regulation of ferrichrome biosynthetic process in response to iron
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the rate of ferrichrome biosynthetic process in response to an iron stimulus." [GOC:al]
+is_a: GO:1905569 ! negative regulation of ferrichrome biosynthetic process
+relationship: part_of GO:0071281 ! cellular response to iron ion

**Comment by Antonialock** [comment]
Super! Thanks Paola

**Comment by paolaroncaglia** [comment]
Now back to the obsoletion of:

id: GO:1905525
name: regulation of ferrichrome biosynthetic process by negative regulation of transcription from RNA polymerase II promoter in response to iron
created_by: al
creation_date: 2016-10-04T15:46:03Z

i.e. requested by @Antonialock  2 weeks ago
@Antonialock , I’ll give it for granted that any annotation you may have made to that term, you will move to the new one. 
No annotations in QuickGO or AmiGO, nor would I expect any. No mappings. Not picked up by other ontologies. 
@ukemi… can I make an exception in this case, and obsolete without going through the usual email warning procedure?

**Comment by Antonialock** [comment]
yes I won't use the old term, it's not how we annotate I just got confused with the existing terms.

**Comment by ukemi** [comment]
Sorry Paola, but since it went into the ontology and was not obsoleted at the TG stage, I think we should follow protocol and give it a week.
-D

**Comment by paolaroncaglia** [comment]
I thought so too @ukemi , just wondering if I was being overly formal. OK will send email.

**Comment by paolaroncaglia** [comment]
Sent obsoletion email. Copying text here for recording purposes:

Dear all,

The proposal has been made to obsolete

GO:1905525 regulation of ferrichrome biosynthetic process by negative regulation of transcription from RNA polymerase II promoter in response to iron

because it was added in error. Full discussion here: https://github.com/geneontology/go-ontology/issues/12740

It hasn't been used in annotations or slims or mappings to other databases or ontologies.

***Unless I hear of any objection, I'll obsolete the term in a week, on Oct. 25th 2016.***

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Obsoleted GO:1905525 regulation of ferrichrome biosynthetic process by negative regulation of transcription from RNA polymerase II promoter in response to iron.
