### ISSUE TITLE
ntr: mitotic spindle assembly checkpoint silencing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12741]
ntr: mitotic spindle assembly checkpoint silencing
def:  Any process that deactivates of a previously activated mitotic spindle assembly checkpoint
synonyms: mitotic spindle assembly deactivation
parents:  GO:1902426 negative regulation of mitotic spindle assembly checkpoint

(I don't know if any negative regulation is NOT silencing of a previously activated checkpoint, possibly not, its likely the checkpoint is active until deactivated.)
PMID: 19592249

**Comment by mah11** [comment]
Would it be better to swap the proposed name and synonym? "Deactivation" sounds more descriptive, and avoids any possible confusion with "silencing" in the transcriptional regulation sense.

Also, stray "of" in the suggested def (should be " deactivates a previously activated ..").

**Comment by ValWood** [comment]
Yep.

As I read more I do think that this is the ONLY type of "negative regulation of a spindle assembly checkpoint" ...its starts "ON" and its "ON" until its switched off.

**Comment by paolaroncaglia** [comment]
Hi @ValWood and @mah11 ,

GO:1902426 ‘negative regulation of mitotic spindle assembly checkpoint’ is currently defined as “Any process that stops, prevents or reduces the frequency, rate or extent of mitotic spindle assembly checkpoint.”
Rather than creating a child term, should we leave GO:1902426 as currently named, placed and logically defined (so it’s clear that it’s a type of regulation), re-define it as “Any process that deactivates a previously activated mitotic spindle assembly checkpoint”, add a def. comment “A mitotic spindle assembly checkpoint is either activated or switched off; no other means of reducing the frequency, rate or extent of this process are currently known.”, and add EXACT synonyms ‘mitotic spindle assembly checkpoint silencing’ and ‘mitotic spindle assembly deactivation’?

If so, I’ll also add PMID:19592249, GOC:vw, GOC:mah.

**Comment by ValWood** [comment]
That would work best, but I should confirm that this is the case.... will check

**Comment by mah11** [comment]
I have no objection to adjusting GO:1902426 (and I agree that no child term is required if there's only one way to negatively regulate the checkpoint). I don't think I need to be listed among the def dbxrefs, since I only commented on how to word the name/synonyms.

**Comment by ValWood** [comment]
I am trying to find out from spindle checkpoint people if there is any other negative regulation of  SAC in addition to "stopping/switching off"

**Comment by ValWood** [comment]
I checked with a spindle assembly checkpoint (Silke Hauf).

=======

I agree with you. I would not be aware of any specific process that prevents checkpoint signaling from beginning. 
I don’t think another term is required. 

Thank you for all your work on this! 
Best, 
Silke

======

So, I thin we are safe to make the existing term
"deactivation of the mitotic spindle assembly checkpoint"
But I will check the existing annotations

**Comment by ValWood** [comment]
- [ ]  PomBase ubc11 (looks incorrect?)
- [ ]  SGC CDH1 "antagonist of the spindle assembly checkpoint"
- [ ]  SGD FIN1 
- [ ] MGI Trappc12 (by ISS and ISO?)
- [ ] human fba (but the entry Q8WVT3 has TRAPPc12? and does not have fba as a synonym, this one is confusing)

**Comment by ValWood** [comment]
Works for all existing annotations. Known biology indicates that negative regulation of spindle assembly checkpoint is only via deactivation.....

**Comment by ValWood** [comment]
I am querying the human trapp complex annotation (it's new).
As far as I am aware, the only way  to turn off the SAC is by a signalling pathway centred on the spindle poly body which turns off the SAC when  kinetochore tension is  sensed.
There is no connection  that I know of to Golgi transport processes....

**Comment by ValWood** [comment]
I found the paper.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4411272/
This isn't really negative regulation of the SAC.
It is some process causally upstream of kinetochore assembly. In mutants where the kinetochore is not correctly assembled, the SAC  sometimes cannot be established correctly. This is a pathological problem - the spindle checkpoint is abolished (phenotype) and not a mechanism whereby the spindle assembly checkpoint is normally negatively regulated. In a normal cell, the checkpoint would  always be activated until the chromosomes are correctly attached.

**Comment by ValWood** [comment]
shyamala  at Unirprot  agrees and has corrected the human annotation.

I think we should go ahead and make this change
negative regulation ->deactivation
for  negative regulation of both mitotic and meiotic spindle checkpoints. 
It will  prevent more annotation where the checkpoint is  never activated but to some pathological upstream mutation (not normal regulation)

**Comment by paolaroncaglia** [comment]
Hi @ValWood,
Based on your comments, I checked the boxes for MGI and UniProt too in https://github.com/geneontology/go-ontology/issues/12741#issuecomment-255701891.
I renamed GO:1902426 as ‘deactivation of mitotic spindle assembly checkpoint’.
There’s no existing regulation term for ‘*meiotic* spindle assembly checkpoint’, so no further edit seems needed. Thanks.
