### ISSUE TITLE
urate excretion

### ISSUE THREAD

**Issue by janelomax** [geneontology/go-ontology#12759]
is_a 'GO:0007588 excretion'

"The elimination by an organism of urate or uric acid" 

urate = CHEBI_46819

There's no template for this - if you restore my TG FF access I can go ahead and add :-)

**Comment by paolaroncaglia** [comment]
Hi @janelomax ,
Nice to hear from you :-) 
We disabled the use of TG FF. I'll add manually for you next week. Thanks for offering though!

**Comment by mcourtot** [comment]
uric acid: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27226
urate salt: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:46819

where urate salt (CHEBI:46819) has functional parent uric acid (CHEBI:27226) - I guess we need to add both as the relation is not is_a?

**Comment by janelomax** [comment]
It used to be that BioCHEBI had a hack that stated equivalence between the salt and the acid, in which case you would only need to add one of these. Not sure if that is still the case?

**Comment by dosumis** [comment]
Pipeline broken so these axioms are going astray. Chris working on fixing it

**Comment by paolaroncaglia** [comment]
Hi @janelomax ,
I can add both terms for you as that might be safer at the moment? I.e. 
uric acid excretion
urate salt excretion (synonym: urate excretion)

**Comment by janelomax** [comment]
Fine by me!

**Comment by dosumis** [comment]
> I can add both terms

Not a good idea.  Once Chris fixes the bioChEBI import, the two terms will become equivalent.  This will break the build.

**Comment by paolaroncaglia** [comment]
Right. Sounds like 
urate salt excretion (synonym: urate excretion)
would do then. @janelomax , any PMID or ISBN or wikipedia link please?

**Comment by janelomax** [comment]
Sorry I didn't make a note of PMID :-(

**Comment by paolaroncaglia** [comment]
Added as:

 [Term]
+id: GO:0097744
+name: urate salt excretion
+namespace: biological_process
+def: "The elimination by an organism of urate salt or uric acid." [CHEBI:46819, GOC:jl, http://en.wikipedia.org/wiki/Uric_acid#Biology]
+synonym: "urate excretion" BROAD []
+is_a: GO:0007588 ! excretion
+created_by: paola
+creation_date: 2016-10-27T11:35:59Z

Afraid we don't define excretion terms logically anyway, so I added the ChEBI ID as a dbxref. Cheers.
