### ISSUE TITLE
open mitosis vs closed mitosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12751]
I think I made a pig's ear of this
https://github.com/geneontology/go-ontology/issues/12728

so the new terms are
ntr: nuclear membrane organization involved in mitotic nuclear division
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the nuclear inner or outer membrane during GO:0007067.
comment: this process only occurs in organisms which undergo 'closed mitosis' without nuclear breakdown.
taxon restriction : Only in fungi?
ref: PMID:15147872

ntr: nuclear membrane biogenesis
standard def (other organelles exist)

ntr: nuclear membrane biogenesis involved in mitotic nuclear division
standard def
taxon restriction : Only in fungi?
child of ntr: nuclear membrane biogenesis and
ntr: nuclear membrane organization during mitotic nuclear division
ref: PMID:26869222

I have the term I required, but  Prof. Shelly Sazer our nuclear envelope closed mitosis expert is confused  by the parent term.

Val,
# 

 Part of this does not make sense to me:

> So for this I have created a term
> "nuclear membrane organization involved in closed mitosis"

 (do you mean to say open mitosis here, since there is no disassembly in closed mitosis??)  

> A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the nuclear inner or outer membrane during GO:0007067.
> comment: this process only occurs 

 (do you mean to say does not occur)  

> in organisms which undergo 'closed mitosis' without nuclear breakdown.

Shelley
# 

I think the problem is that I requested a parent "organization" term 
for the term that I needed for annotation
ntr: nuclear membrane biogenesis involved in mitotic nuclear division

but this is confusing because the other "parts" don't exist during closed mitosis.

Also, it seems that this term could be misinterpreted to cover the nuclear  events  which occur during open mitosis (breakdown and reassembly)...I don't know when these events happen with respect to 

"mitotic nuclear division"
Definition  A mitotic cell cycle process comprising the steps by which the nucleus of a eukaryotic cell divides; the process involves condensation of chromosomal DNA into a highly compacted form. Canonically, mitosis produces two daughter nuclei whose chromosome complement is identical to that of the mother cell.

but I suspect we need  the grouping  term to cover the nuclear membrane events of both open and closed mitotic division, and THEN  sub branches for the different events  open and closed mitosis.

So in closed mitosis the membrane needs to expand, but in closed mitosis  it needs to disassemble/reassemble.

@ukemi  do you know how it works for open mitosis?

Another alternative is just to keep the terms I added, but remove all mention of closed mitosis? That would probably work too?

**Comment by ukemi** [comment]
According to PMID:24529240 in open mitosis, the nuclear membrane disassembles by breakdown of the nuclear lamina and tearing by microtubules. 

From this review, it might not be a good idea to distinguish the two types because it looks like the distinction might be fuzzy in some cases.

**Comment by ValWood** [comment]
OK, we can remove the references to "closed mitosis".

The only term I need is one to be used for the "membrane addition to the nuclear membrane during division"
maybe that would be a better term name. The appears to be a precedent

"GO:0007107 membrane addition at site of cytokinesis"

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
FYI, I haven’t had a chance to work on this ticket until now, and I’ll be on leave next week. Thanks for your patience.

**Comment by ValWood** [comment]
note to self
5bd37a86db70f418/ro/

**Comment by paolaroncaglia** [comment]
Hi @ValWood,

Following up on your note that “The only term I need is one to be used for the "membrane addition to the nuclear membrane during division””

Sounds like this existing term may fit your needs:

[Term]
id: GO:0101026
name: nuclear membrane biogenesis involved in mitotic nuclear division
namespace: biological_process
def: "A process in which the nuclear inner or outer membrane is synthesized, aggregates, and bonds together during mitotic nuclear division." [GOC:vw, PMID:26869222]
is_a: GO:0044802 ! single-organism membrane organization
is_a: GO:0101024 ! nuclear membrane organization involved in mitotic nuclear division
is_a: GO:0101025 ! nuclear membrane biogenesis
relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000039"} ! Metazoa
relationship: part_of GO:0007067 ! mitotic nuclear division

But if not, please let me know where you’d need your new term to differ from the above.
Thanks!

**Comment by ValWood** [comment]
that all looks fine. I thought I had stuffed this up  but the parents look fine, the tax restrictions are OK, so yep close....
