### ISSUE TITLE
positive-negative regulation of liquid surface tension

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12758]
I would like to see "positive regulation of liquid surface tension” and “negative regulation of liquid surface tension” added to the GO ontology under the parent term "regulation of liquid surface tension” (GO:0050828).  The definitions could be "Any process that activates or increases the surface tension of a liquid” and “Any process that prevents or reduces the surface tension of a liquid".  An example can be found in PMID:20949060. Synonyms could be “positive regulation of surface tension of a liquid” and “negative regulation of surface tension of a liquid”.

**Comment by cmungall** [comment]
Define using 

[OBA:0000088](http://purl.obolibrary.org/obo/OBA_0000088) ! liquid surface tension

**Comment by mcourtot** [comment]
Added 
GO:0101029, negative regulation of liquid surface tension
GO:0101028, positive regulation of liquid surface tension
revision 36500.
