### ISSUE TITLE
OTR: add has_part links between autophagy and organelle disassembly

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12754]
As discussed at autophagy call today. See https://github.com/geneontology/go-ontology/issues/12662: "Paola will make has part relations between the specific types of autophagy and the disassembly terms. On the conference call this morning we decided that this is the best way to proceed since it would account for a necessary step in the autophagy process, but would also account for cases where cellular components are recycled.".

**Comment by paolaroncaglia** [comment]
@ukemi @marcfeuermann @RLovering @Pauldenny
I propose to add the following links, please review and let me know if you have any concern. In all cases below, I think we should use ends_with specifically, rather than the broader has_part, but let me know if you disagree:

- [ ] ‘mitophagy’ (“The autophagic process in which mitochondria are delivered to the vacuole and degraded in response to changing cellular conditions.”) ends_with ‘mitochondrion disassembly’
- [ ] ‘macromitophagy’ (“Degradation of a mitochondrion by macroautophagy.”) ends_with ‘mitochondrion disassembly’
- [ ] ‘microautophagy of mitochondrion’ (“Degradation of a mitochondrion by lysosomal microautophagy.”) ends_with ‘mitochondrion disassembly’ (“The disaggregation of a mitochondrion into its constituent components.”)

- [ ] ‘pexophagy’ (“The process in which peroxisomes are delivered to the vacuole and degraded in response to changing nutrient conditions.”) ends_with ‘peroxisome disassembly’
- [ ] ‘macropexophagy’ (“Degradation of a peroxisome by macroautophagy.”) ends_with ‘peroxisome disassembly’ 
- [ ] ‘micropexophagy’ (“Degradation of a peroxisome by lysosomal microautophagy.”) ends_with ‘peroxisome disassembly’ 
- [ ] require creation of ‘peroxisome disassembly’ 

- [ ] ‘nucleophagy’ (“A selective form of autophagy, by which damaged or non-essential parts of the nucleus, or even an entire nucleus is degraded.”) => can’t really add ends_with ‘nuclear part disassembly’, but we could do
- [ ] ‘piecemeal microautophagy of nucleus’ (“Degradation of a cell nucleus by lysosomal microautophagy.”) ends_with ‘nucleus disassembly’
- [ ] requires creation of ‘nucleus disassembly’

- [ ] ‘glycophagy’ (“The autophagic process in which cellular glycogen is delivered to the vacuole and degraded in response to changing cellular conditions.”) ends_with ‘glycogen catabolic process’

- [ ] ‘lipophagy’ (“The autophagic process in which lipid droplets are delivered to the vacuole and degraded in response to changing cellular conditions.”) ends_with ‘lipid particle disassembly’
- [ ] requires creation of ‘lipid particle disassembly’

- [ ] ‘reticulophagy’ (“The autophagic process in which parts of the endoplasmic reticulum are loaded into autophagosomes, delivered to the vacuole, and degraded in response to changing cellular conditions.”) ends_with ‘endoplasmic reticulum disassembly’
- [ ] requires creation of ‘endoplasmic reticulum disassembly’

- [ ] ‘ribophagy’ (“The process in which cells degrade mature ribosomes under conditions of starvation”) ends_with ‘ribosome disassembly’

Thanks.

**Comment by ukemi** [comment]
I don't think ends with is the correct relation because after disassembly, the components are catabolized. I think it is safer to go with has_part.

**Comment by paolaroncaglia** [comment]
@ukemi 
Sure, has_part then. I'll implement - just leaving it open for a bit in case @marcfeuermann or @Pauldenny have any comment. (I think Ruth is on leave this week.)

**Comment by RLovering** [comment]
I'm happy to leave these decisions to David and Paola

**Comment by Pauldenny** [comment]
I agree with David - I think has_part makes more sense.

**Comment by paolaroncaglia** [comment]
@ukemi 
(and @marcfeuermann @RLovering @Pauldenny)
FYI, this is all done. The only case where I opted for ends_with, instead of has_part, was
‘glycophagy’ (“The autophagic process in which cellular glycogen is delivered to the vacuole and degraded in response to changing cellular conditions.”) ends_with ‘glycogen catabolic process’.

**Comment by ukemi** [comment]
Awesome. This makes perfect sense.
