### ISSUE TITLE
Typo in definition: voltage-gated potassium channel activity.........GO:0086041

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12755]
Hi 

please change sodium to potassium in this term definition

GO:0086041 voltage-gated potassium channel activity involved in SA node cell action potential depolarization:
Enables the transmembrane transfer of a sodium ion by a voltage-gated channel through the plasma membrane of an SA node cardiac muscle cell contributing to the depolarization phase of an action potential. A voltage-gated channel is a channel whose open state is dependent on the voltage across the membrane in which it is embedded.

Thanks

Ruth

**Comment by ukemi** [comment]
Had to have been a cut and paste error made by me. Fixed now.
