### ISSUE TITLE
http://geneontology.org/ontology/go-basic.obo is out of date

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12753]
How often is this file updated?  This is the file that:

http://purl.obolibrary.org/obo/go/go-basic.obo

from the GO downloads page redirects to from http://geneontology.org/page/download-ontology.

@cmungall - can you look into or reassign to someone who can check on this?

format-version: 1.2
data-version: releases/2016-10-13
date: 13:10:2016 02:38
saved-by: pr

This seems out of date, esp since there are three more recent go-basic.obo versions in SVN.

**Comment by cmungall** [comment]
Looks like sync between svn and http is failing

svn go/ontology has `data-version: releases/2016-10-20`

however, http://geneontology.org/ontology/go-basic.obo is `data-version: releases/2016-10-13`

**Comment by stuartmiyasato** [comment]
There was an SVN lock that needed to be removed.  I think I've taken care of this.  We'll see when tonight's sync job runs.

**Comment by cmungall** [comment]
@stuartmiyasato - still not fixed

**Comment by stuartmiyasato** [comment]
@cmungall Is it better now?  I had to change permissions on a temporary directory on the SVN server -- looks like it was deleted and re-created with incorrect permissions.  Anyway, http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/go-basic.obo?revision=36468 and http://geneontology.org/ontology/go-basic.obo appear to be showing the save version of the file now.  How does it look to you?

**Comment by tberardini** [comment]
@stuartmiyasato : It looks better now to me and our pipeline that uses the URL to retrieve the ontology for our TAIR updates is bringing in new data again.

**Comment by cmungall** [comment]
Thanks @stuartmiyasato !
