### ISSUE TITLE
Disulfide oxidoreductase activity (GO:0015036) should be a parent of thioredoxin disulfide reductase activity (GO:0004791)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12752]
(Note to self: seen when annotated Thioredoxin family, PTHR10438)

Thanks, Pascale

**Comment by mcourtot** [comment]
Hi @pgaudet: shouldn't all the "[xx]-disulfide reductase activity" classes fall under the disulfide oxidoreductase activity?

This includes:
CoA-disulfide reductase activity
protein-disulfide reductase activity
slenodiglutathione-disulfide reductase activity
thioredoxin-disulfide reductase activity
trypanothion-disulfide reductase activity

**Comment by pgaudet** [comment]
Yes !! I was only focused on the problem at hand ;) 

Thanks, 
Pascale

**Comment by mcourtot** [comment]
Great, thanks for confirming! Just wanted to update it all at once ;)

**Comment by mcourtot** [comment]
Done revision 36523.
