### ISSUE TITLE
NTR: Optical nerve regeneration

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#12760]
Hi,
Could I please request a new term "Optical nerve regeneration" with a potential definition of "The regrowth of axons of the optical nerve following an injury". This is based of figure 2 of PMID:16699509.

 GO:0031103 axon regeneration, could be the  parent on the new term.

Thank you very much.

Penelope

**Comment by mcourtot** [comment]
added GO_0101027, optical nerve axon regeneration, revision 36489
