### ISSUE TITLE
maintenance of blood-brain barrier and regulation terms

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12767]
TG requests:

[Term]
id: GO:1905603
name: regulation of maintenance of blood-brain barrier
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of maintenance of blood-brain barrier." [GO_REF:0000058, GOC:als, GOC:TermGenie, PMID:22524708]
synonym: "regulation of maintenance of BBB" EXACT [GOC:TermGenie]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0035633 ! maintenance of blood-brain barrier
created_by: als
creation_date: 2016-10-26T13:18:16Z

(and pos and neg children)

Review of the parent term, its definition, and discussion during the editors' meeting resulted in the suggestion to move the core term from is_a single-organism cellular process to is_a regulation of biological quality.  In addition, the core term will be renamed 'maintenance of permeability of blood-brain barrier'  in accordance with the definition.

I will not implement this until next week, after Aleks will have had a chance to review this ticket.

**Comment by tberardini** [comment]
Obviously, with the renaming of the core term, the regulation terms will change as well, to reflect the new primary term name.

**Comment by zebrafishembryo** [comment]
Dear Tanya, 

Thank you very much for letting me know and for taking care about this ticket.

I think all the proposed changes make perfect sense and, moreover, the new term much better reflects the experimental data provided in the paper I was curating. 

Best wishes

**Comment by tberardini** [comment]
id: GO:0035633
-name: maintenance of blood-brain barrier
+name: maintenance of permeability of blood-brain barrier
-synonym: "maintenance of BBB" EXACT [PMID:20080302]
+synonym: "maintenance of BBB" RELATED [PMID:20080302]
+synonym: "maintenance of blood-brain barrier" RELATED []
-is_a: GO:0044763 ! single-organism cellular process
+is_a: GO:0065008 ! regulation of biological quality

**Comment by tberardini** [comment]
Committed the regulation terms after editing them to reflect the core term's new primary term string.


Status for commit #87004: Success

    ID: GO:1905603 Label: regulation of maintenance of permeability of blood-brain barrier
    ID: GO:1905604 Label: negative regulation of maintenance of permeability of blood-brain barrier
    ID: GO:1905605 Label: positive regulation of maintenance of permeability of blood-brain barrier
