### ISSUE TITLE
basal pole of outer hair cell

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12764]
I would like to see "basal pole of outer hair cell” added to the GO ontology under the parent term "cell pole" (GO:0060187).  The definition could be "The end of the outer hair cell which receives and transmits neural signals".  An example can be found in PMID:12845523.

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090712
+name: basal pole of outer hair cell
+namespace: cellular_component
+def: "The end of the outer hair cell which receives and transmits neural signals." [GOC:sl, PMID:12845523]
+is_a: GO:0060187 ! cell pole
+created_by: tanyaberardini
+creation_date: 2016-11-01T12:57:03Z
