### ISSUE TITLE
ntr: prospore membrane biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12769]
descendant of 
GO:0005628
GO:0044091

A cellular process that results in the biosynthesis of constituent macromolecules, assembly, and arrangement of constituent parts of a prospore membrane.

**Comment by dosumis** [comment]
Added.  
![image](https://cloud.githubusercontent.com/assets/112839/19963319/163515c4-a179-11e6-8869-b1f5fa6d0fc8.png)
Can you suggest a ref?

**Comment by ValWood** [comment]
PMID:27630265

**Comment by dosumis** [comment]
Ta.  Added.
