### ISSUE TITLE
Making so_import broken due to issue with SO URIs

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12775]
Header of the SO file (excerpt)
```
     xmlns:so-xp="http://purl.obolibrary.org/obo/so-xp.obo#">
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/so-xp.obo.owl">
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/so-xp.obo/so-xp/releases/2015-11-24/so-xp.owl/so-xp.obo.owl"/>
```

The so-xp based URIs create an issue for our import of SO terms.

**Comment by cmungall** [comment]
I have a PR open with SO: https://github.com/The-Sequence-Ontology/SO-Ontologies/pull/377

In meantime to fix the release pipeline we have to undo the change to the Makefile that adds SO

**Comment by mcourtot** [comment]
No problem - this is not an emergency. Can you update the Makefile?

**Comment by mcourtot** [comment]
Removed the SO import from Makefile to allow release to go through as per #12777

**Comment by dosumis** [comment]
Is this going to effect inferences using SO?  We have quite a lot of those.

**Comment by mcourtot** [comment]
This only deactivates import of new SO terms, shouldn't affect existing ones. (This is the Makefile in the extensions directory)

SO ticket/PR at https://github.com/The-Sequence-Ontology/SO-Ontologies/pull/377

Release is running right now, see http://build.berkeleybop.org/job/release-go/132/

**Comment by dosumis** [comment]
OK.  Just checking.

**Comment by mcourtot** [comment]
If you have a specific example in mind, would you mind having a look once the release is done?

**Comment by mcourtot** [comment]
Discussed at editors call 2016-11-17
AI: Melanie to email Karen

**Comment by mcourtot** [comment]
I have added the SO import in the Makefile, http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/Makefile?r1=37060&r2=37068

Let's see if the release makes it through. If it does:
- [ ] address ticket https://github.com/geneontology/go-ontology/issues/12533
- [ ] remove SO import from Makefile again until stable solution found

**Comment by mcourtot** [comment]
issue with SO versionIRI: https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/387

Trying to add the SO import to the Makefile nonetheless.

**Comment by mcourtot** [comment]
SO import made it through:
[Term]
id: SO:0002140
name: early_origin_of_replication
is_a: SO:0000296 ! origin_of_replication

[Term]
id: SO:0002141
name: late_origin_of_replication
is_a: SO:0000296 ! origin_of_replication

Closing this ticket in favour of #12533
