### ISSUE TITLE
MP under tRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12772]
tRNA 3' trailer cleavage should be a descendant of

GO:1905267 endonucleolytic cleavage involved in tRNA processing

I would question the need for 
GO:1905267 endonucleolytic cleavage involved in tRNA processing

because it  is really  a grouping term for an activity rather than a process. tRNA splicing (intron removal) OR 3' end cleavage could both involved endonucleoitic cleavage.

It does not have any annotations so it could just be removed perhaps?

**Comment by dosumis** [comment]
> tRNA 3' trailer cleavage should be a descendant of
> GO:1905267 endonucleolytic cleavage involved in tRNA processing

Not according to the def:

rdfs:label "tRNA 3'-trailer cleavage"
definition "Cleavage of the 3'-end of the pre-tRNA as part of the process of generating the mature 3'-end of the tRNA; may involve ***endonucleolytic or exonucleolytic*** cleavage, or both."^

**Comment by ValWood** [comment]
But isn't "cleavage" always endonucleolytic?
If you nibble away at the ends, that isn't cleavage is it?

**Comment by deustp01** [comment]
According to Google, it is:

Exonucleases are enzymes that work by cleaving nucleotides one at a time from the end (exo) of a polynucleotide chain. A hydrolyzing reaction that breaks phosphodiester bonds at either the 3' or the 5' end occurs.

And I think I remember biochemist colleagues happily using "cleavage" to describe the activities of both endo- and exo-nucleases.

**Comment by ValWood** [comment]
OK!
