### ISSUE TITLE
MP: GO:0090615 mitochondrial mRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12770]
GO:0090615 mitochondrial mRNA processing
is defined
Steps involved in processing precursor RNAs arising from transcription of operons in the mitochondrial genome into mature mRNAs.

should it be a descendent of
GO:0031426 polycistronic mRNA processing
The conversion of a primary mRNA transcript containing more than one complete protein-coding region into individual mature mRNA molecules.
?

**Comment by krchristie** [comment]
Note that the polycistronic transcripts in mitochondria are generally not all mRNAs, but are a mix of rRNA, tRNA, and mRNA. That might be an issue for making this parentage.

-Karen

**Comment by ValWood** [comment]
GO:0090615 mitochondrial mRNA processing
might be a problematic term then?
It is defined as mRNA, maybe it should only be
GO:0090615 mitochondrial RNA processing for the operon processing.

I see there is a need for individual processing events which have  specialised processes post operon processing (like 3' tRNA end processing which is a descendant).

It that this would be better 
i) the processing of the "mitochondrial operon" into individual RNA's (RNA type independent),

ii)   sibling terms for  individual end processing events which only take place for specific RNA types *after* cleavage (tRNA 3' end processing mRNA polyadenylation, any others?)

iii) All grouped under a general mitochondrial RNA processing term

**Comment by ValWood** [comment]
nice schema here:
http://www.mrc-mbu.cam.ac.uk/projects/2302/regulation-mitochondrial-gene-expression

**Comment by ValWood** [comment]
no hurry for me I annotated the paper I was doing....its not too bad right now...

**Comment by krchristie** [comment]
That's a great diagram you've linked to Val.

I agree that there seems to be a use for individual processing events which have specialised post  processing after the endonucleolytic cleavage events to separate the individual RNAs from each other, like 3' tRNA end processing, as you mentioned. 

That diagram also shows that the mRNA's are individually polyadenylated post-endonucleolytic cleavage, so there may be a need for mitochondrial mRNA processing, but it should be clear that this is processing that occurs after the processing of the polycistronic primary transcript into separate RNAs. If the only post-cleavage processing of the mitochondrial mRNAs is polyadenylation, then perhaps only a more specific term is warranted. It would be interesting to know if there is any processing/capping of the 5'-end as occurs for mRNAs generated in the nucleus.

**Comment by dosumis** [comment]
To summarise we agree that this is not correct:

> GO:0090615 mitochondrial mRNA processing
> should  be a descendent of GO:0031426 polycistronic mRNA processing

becuase 
> polycistronic transcripts in mitochondria are generally not all mRNAs, but are a mix of rRNA, tRNA, and mRNA. That might be an issue for making this parentage.

But the def is potentially problematic:

'mitochondrial mRNA processing': "Steps involved in processing precursor RNAs arising from transcription of operons in the mitochondrial genome into mature mRNAs."

If it covers all steps post-transcription then the first step is common to processing of rRNA, & tRNA.

Options:  

1. Leave definition and add a clarifying comment.
2. Modify the definition so that it only applies to steps after cleavage from polycistronic RNA.

Any preference?

**Comment by krchristie** [comment]
Currently the term "mitochondrial mRNA processing" is a parent for two terms that cover the 3'-end or 5'-end processing of mitochondrial mRNAs. This kind of grouping term seems consistent with what we've done in other places, so if we're going to need a term with this name anyway, it might be better to just adjust the definition of the existing term.

AmiGO only shows two A.thaliana genes annotated directly to this term with experimental evidence, so it might not be too hard to check these two annotations and see if a definition change would require them to be moved to a more general term. Thoughts? @tberardini 

**mitochondrial mRNA processing**   (TAIR    _Arabidopsis thaliana_)
* RFL2    AT1G12300       IMP     PMID:27122350   20160707
* GRS1    AT4G32430      IMP     PMID:27670716   20161005

-Karen

**Comment by tberardini** [comment]
RFL2 = endonucleolytic cleavage of mitochondrial transcript orf291 is aberrant in mutant - should be reannotated to 'positive regulation of mitochondrial mRNA catabolic process' - need to create that term and move the annotation

GRS1 = several unedited sites in the mitochondrial RNA of mutant plants - edited annotation to be   GO:0080156 instead, mitochondrial mRNA modification (not processing)

**Comment by tberardini** [comment]
Ok. Both annotations taken care of.

**Comment by krchristie** [comment]
Thanks @tberardini

**Comment by ValWood** [comment]
This seems quite subtle and out of scope considering more active areas of research. will close, can be revisited when  people are more actively publishing/curating in this area.
