### ISSUE TITLE
merge 'regulation of phosphatase' terms

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12771]
For #12184, several overly-specific protein phosphatase regulator terms were merged into the parent, but a few corresponding regulation terms are still "active". Should they also be merged with the non-type-specific "regulation of protein phosphatase activity" terms?

id: GO:0034047
name: regulation of protein phosphatase type 2A activity

id: GO:0034048
name: negative regulation of protein phosphatase type 2A activity

id: GO:0034049
name: positive regulation of protein phosphatase type 2A activity

id: GO:0032512
name: regulation of protein phosphatase type 2B activity

id: GO:0032513
name: negative regulation of protein phosphatase type 2B activity

id: GO:0032514
name: positive regulation of protein phosphatase type 2B activity

**Comment by dosumis** [comment]
Hmmmm.  This should not have been possible.  Either these terms never had logical defs, or they someone stripped their logical defs as part of the merge. 

![image](https://cloud.githubusercontent.com/assets/112839/19963469/caded7f8-a179-11e6-93cf-3289a5f117ea.png)

(They'd have 3 little bars on the nodes if they had logical defs)

What should happen during a merge is that all axioms stay, but the IDs (URIs) are switched.  If that had happened, then the result would have been a set of terms that the reasoner flags as logically equivalent, breaking the build and indicating what terms remained to be merged.

Melanie, can you fill us in on how you did the merge?

**Comment by mcourtot** [comment]
Regulation terms were not touched, only the phosphatase terms as described in https://github.com/geneontology/go-ontology/issues/12184

Note that there is (nor was) no term 'protein phosphatase type 2A activity' which would have been required for logical definition of the corresponding regulation terms. Based on there IDs, those terms were also not created via TG, so possible they had no logical definition.

Merge was done as usual in Protege, switching URIs, as per https://docs.google.com/document/d/18epAEpii6tJVBW0hLxANjl2fUujgJ61Ksz7THrGL70Y/edit#heading=h.titspsetpwd8. Some logical axioms were removed on phosphatase terms (after merge, the superclass became subclass of itself for example due to axioms being kept)

**Comment by mah11** [comment]
Oh yeah, it was MF 'regulator' terms that were merged rather than kinase activity terms (I've edited my original summary, which omitted that). The 'regulation' BP terms do still need attention for consistency.

**Comment by dosumis** [comment]
> Note that there is (nor was) no term 'protein phosphatase type 2A activity' which would have been required for logical definition of the corresponding regulation terms. Based on there IDs, those terms were also not created via TG, so possible they had no logical definition.

Weird.  @mah11 Do you know the history of these?  The defs have your initials.

> Some logical axioms were removed on phosphatase terms (after merge, the superclass became subclass of itself for example due to axioms being kept)

Isn't that a sign that the two terms should be merged rather than the axioms removed?  (Bit hard to know for sure without seeing examples).

**Comment by mcourtot** [comment]
Note *after merge* in the above. So for example, the term GO:1990681 protein phosphatase type 2A inhibitor activity was merged into into protein phosphatase inhibitor. As the axioms are initially kept, I had to manually remove the axiom 'subclassOf protein phosphatase inhibitor' on the resulting merged class 'protein phosphatase inhibitor.'

**Comment by mah11** [comment]
>  @mah11 Do you know the history of these?

If by "these" you mean the BP regulation terms I'm now querying, they are old enough that I no longer have anything relevant in my head. I did find the GitHub copies of tickets in which they were requested - #4365 and #4639 - and the text implies that at the time, there were MF terms for the type 2A and type 2B phosphatase activities. IIRC, that probably predated GO's deployment of logical definitions.

From the alt_ids and narrow on GO:0004722 it appears that the type 2A and type 2B phosphatase activity terms were merged in, again probably before logical defs.

**Comment by mcourtot** [comment]
I think we should 

![screen shot 2017-01-25 at 14 00 27](https://cloud.githubusercontent.com/assets/2214135/22293209/aa42fbf4-e306-11e6-9205-70b6ac40d20d.png)


- [ ] create positive regulation of phosphoprotein phosphatase activity as subclass of regulation of phosphoprotein phosphatase activity
- [ ] create negative regulation of phosphoprotein phosphatase activity as subclass of regulation of phosphoprotein phosphatase activity
- [ ] merge negative regulation of protein phosphatase  type 2A activity and negative regulation of protein phosphatase  type 2B activity into negative regulation of phosphoprotein phosphatase activity
- [ ] merge positive regulation of protein phosphatase  type 2A activity and posiive regulation of protein phosphatase  type 2B activity into positive regulation of phosphoprotein phosphatase activity

Comments?

**Comment by mah11** [comment]
fine with me

**Comment by ValWood** [comment]
me too!

**Comment by mcourtot** [comment]
Those terms already exist:
positive regulation of phosphoprotein phosphatase activity: GO:0032516
negative regulation of phosphoprotein phosphatase activity: GO:0032515

**Comment by mcourtot** [comment]
positive terms merged revision 38393.

**Comment by mcourtot** [comment]
negative terms merged revision 38395.

**Comment by mcourtot** [comment]
regulation terms merged revision 38397.
