### ISSUE TITLE
signal transduction and cellular process

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12778]
Atm, signal transduction,  is a regulation of cellular process. However, definition matches the one of a cellular process 
`The cellular process in which a signal is conveyed to trigger a change in the activity or state of a cell. Signal transduction begins with reception of a signal (e.g. a ligand binding to a receptor or receptor activation by a stimulus such as light), or for signal transduction in the absence of ligand, signal-withdrawal or the activity of a constitutively active receptor. Signal transduction ends with regulation of a downstream cellular process, e.g. regulation of transcription or regulation of a metabolic process. Signal transduction covers signaling from receptors located on the surface of the cell and signaling via molecules located within the cell. For signaling between cells, signal transduction is restricted to events at and within the receiving cell.`

Changes to definition were made in 2011.
![screen shot 2016-11-03 at 12 24 39](https://cloud.githubusercontent.com/assets/2214135/19965837/c882d198-a1c0-11e6-8623-9256c886ff59.png)

db-xrefs indicate go_curators and signalling meeting in feb 2011. 

Question raised by @jpinero

**Comment by dosumis** [comment]
Seems like both to me:  A cellular process that regulates other cellular processes.  All seems a bit abstract to me to be particularly important though especially given how vague the GO def of 'cellular' is.

**Comment by ValWood** [comment]
Yep I would also say its both.

**Comment by dosumis** [comment]
Fixed.
