### ISSUE TITLE
Remove "Cellular" from the Component root

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12779]
Cellular is not appropriate for viruses, and probably for other extracellular nodes in the existing ontology

**Comment by dosumis** [comment]
There's a danger this will cause too much churn for consumers of the GO.  Also 'cellular' in GO  term names generally means something vague like - at the cellular level (of granularity?).  So many more terms affected. 

I'll bring it up with the editors/

**Comment by mcourtot** [comment]
Thinking out loud before the editors call: if updating the label is too much of an issue, would one solution be to add a comment specifying that "this label is there for historical reasons, but with the evolution of the GO it also encompass other components such as viral ones"?

**Comment by dosumis** [comment]
At editor's meeting:  we all agreed that the name should not be changed, but that the def should be teaked.  How's this:

definition "The part of a cell or the extracellular environment or a virus in which a gene product is located. A gene product may be located in one or more parts of a cell and its location may be as specific as a particular macromolecular complex, that is, a stable, persistent association of macromolecules that function together."
