### ISSUE TITLE
jenkins autorelease of ontology files stuck?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12777]
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/

The last autorelease of jenkins was 10/29.

Log of /trunk/ontology/go-basic.obo
Revision 36633 - (view) (download) (annotate) - [select for diffs]
Modified Sat Oct 29 12:56:21 2016 UTC (4 days, 3 hours ago) by jenkins
File length: 32906077 byte(s)
Diff to previous 36605

auto-release

There have been successful commits to the editors version since then.  How come no public releases since 10/29?

http://geneontology.org/ontology/go-basic.obo

Can someone please check?

**Comment by tberardini** [comment]
@cmungall @kltm : please read

**Comment by mcourtot** [comment]
Hi @tberardini - there was an issue with the build which @cmungall is fixing. See https://github.com/geneontology/go-ontology/issues/12775

**Comment by tberardini** [comment]
Ok, I noticed that our import reports of the GO file has showed no changes in the past few days when I know that we've been editing successfully.

**Comment by mcourtot** [comment]
Release made it through, http://build.berkeleybop.org/job/release-go/132/
