### ISSUE TITLE
calyx

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12773]
I would like to see "calyx” added to the GO ontology under the parent term "axon terminus” (GO:0043679).    The definition could be "The cup-shaped terminal of a vestibular afferent nerve serving as a post-synaptic contact to type I hair cells.  The calyx may contact the hair cell singly or accompanied by terminal boutons.”  An example can be found in PMID:1601088. Synonyms could be “vestibular calyx terminal”, “calyx afferent terminal”, and “afferent nerve calyx”.

**Comment by cmungall** [comment]
I recommend prefixing, 'calyx' is ambiguous (flower part, fly brain part, kidney part)

**Comment by dosumis** [comment]
Added
![image](https://cloud.githubusercontent.com/assets/112839/19904759/e69ecb2e-a06b-11e6-9791-f91c6e558680.png)
