### ISSUE TITLE
Contact required for UniProt annotations for ontology change alerts

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12788]
We asked Sylvain whether we could create a GH user for use a shortcut to help@uniprot email. He responded that he would discuss this at the GOC meeting. 

AI from last call was "Sylvain will discuss with Chris and David H at the GOC meeting".

**Comment by mcourtot** [comment]
@thomaspd will follow up on this

**Comment by ValWood** [comment]
@pgaudet  out of date?

**Comment by pgaudet** [comment]
yes, thanks
