### ISSUE TITLE
NTR / convert related synonym for GO:0003953 NAD+ nucleosidase activity into new term 

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12784]
Currently GO:0003953 NAD+ nucleosidase activity has a "related" synonym:	
ADP-ribosyl cyclase activity
But based on two papers - PMID: 7805847 and PMID: 11866528 I think that 'ADP-ribosyl cyclase activity' deserves upgrading into it's own term. Fig 1 in the second paper (PMID: 11866528) shows the reactions catalysed by BST1/ CD157 (UniprotKB ID: Q10588)
![image](https://cloud.githubusercontent.com/assets/12345463/20117361/1f8b8c60-a5f8-11e6-9f31-67cccfb297a6.png) to support this contention.
So, I am requesting two new terms, because BST1 has both activities, converting NAD into cADPR (cyclic ADP-ribose) and then converting cyclic ADP-ribose into ADP-ribose:

ADP-ribosyl cyclase activity
Def: cyclization of NAD to yield cyclic ADP-ribose

cADPR hydrolase
Def: catalysis of the hydrolysis reaction: cyclic ADP-ribose (cADPR) + H20  to yield ADP-ribose (ADPR).

There are at least three enzymes known to have these activities: BST1, CD38 (both human but of course, by inference mammals will have homologs) and Aplysia californica ADP-ribosyl cyclase, so new terms would be applied widely.  

Opinions?

GOC:PARL
GOC:pad

**Comment by ukemi** [comment]
Another alternative would be to make two children of the existing term to represent EC3.2.2.5 and EC3.2.2.6 respectively. @deustp01 any advice?

**Comment by deustp01** [comment]
The alternative sounds good, following this ExPSY comment for EC 3.2.2.5: "This enzyme catalyzes the hydrolysis of NAD(+), without associated ADP-ribosyl cyclase activity (unlike the metazoan enzyme EC 3.2.2.6, bifunctional ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase)."

So it looks like the enzymologists see these two functions / activities as distinct (so GO MF, following activity, could have two terms?) and, per the comment, note the existence of some proteins that have only one of the activities even though most have both. (Indeed, figure 2 of  PMID: 11866528, above, which describes the two functions, shows that both are mediated by a single active site in which the two distinct substrates dock.)

**Comment by ukemi** [comment]
Looking closer at PMID:11866528 and thinking about this a bit more, it seems that we should have the two terms that Paul suggests. It appears that the intermediate cADPR is a stable intermediate that is used in signaling. So even though the gene product has the two molecular functions, ADP-ribosyl cyclase and cADPR hydrolase, only one of them is executed to generate cADPR. I propose that we make two children of GO:0003953 NAD+ nucleosidase activity as follows:

NAD+ nucleotidase (GO:0003953)
% NAD glycohydrolase (GO:new)
% NAD+ nucleotidase, cyclic-ADP ribose generating (GO:new)
--has_part ADP-ribosyl cyclase activity (GO:new)
--has_part cyclic-ADP ribose hydrolase activity (GO:new)

EC 3.2.2.5  and many synonyms will need to be removed from GO:0003953. The new NAD glycohydrolase term will get EC3.2.2.5 as an xref and the new NAD+ nucleotidase, cyclic-ADP ribose generating term will get EC3.2.2.6 as an xref. 

There are 6 annotations to the existing term with experimental evidence:

UniProtKB	P9WGG3	cobB		GO:0003953	PMID:19747094	IDA		F	NAD-dependent protein deacylase	NPD_MYCTU|sir2|Rv1151c|MTCI65.18c	protein	NCBITaxon:83332	20110613	MTBBASE		
RGD	2303	Cd38		GO:0003953	RGD:1299847|PMID:11733184	IDA		F	CD38 molecule		gene	NCBITaxon:10116	20050217	RGD		
UniProtKB	Q9MZ03	CD38		GO:0003953	PMID:10477767	IDA		F	ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase 1	CD38_RABIT	protein	NCBITaxon:9986	20020118	UniProt		
UniProtKB	Q9MZ03	CD38		GO:0003953	PMID:10891341	IDA		F	ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase 1	CD38_RABIT	protein	NCBITaxon:9986	20020118	UniProt		
MGI	MGI:107948	Art5		GO:0003953	MGI:MGI:82887|PMID:8703012	IDA		F	ADP-ribosyltransferase 5	Yac-2	protein	NCBITaxon:10090	20090327	MGI		EMBL:U60881
MGI	MGI:107948	Art5		GO:0003953	MGI:MGI:2152479|PMID:11587854	IDA		F	ADP-ribosyltransferase 5	Yac-2	protein	NCBITaxon:10090	20090327	MGI		UniProtKB:O54739

Those can be deepened to the new terms.

Does this make sense to you guys?

**Comment by deustp01** [comment]
Works for me.

**Comment by Pauldenny** [comment]
Sounds good - thanks! NB I knew about the signalling but neglected to mention - e.g. we have GO:0072346	cADPR-sensitive calcium-release channel activity

**Comment by ukemi** [comment]
OK. Hopefully this is all sorted out now.

id: GO:0003953
 name: NAD+ nucleosidase activity
 namespace: molecular_function
-def: "Catalysis of the reaction: NAD+ + H2O = nicotinamide + ADP-ribose." [EC:3.2.2.5]
+def: "Catalysis of the reaction: NAD+ + H2O = nicotinamide + ADP-ribose." [GOC:dph, GOC:pad, GOC:PARL, GOC:pde, PMID:11866528, PMID:7805847]
 subset: gosubset_prok
-synonym: "ADP-ribosyl cyclase activity" RELATED [EC:3.2.2.5]
-synonym: "diphosphopyridine nucleosidase activity" EXACT [EC:3.2.2.5]
-synonym: "DPN hydrolase activity" EXACT [EC:3.2.2.5]
-synonym: "DPNase activity" EXACT [EC:3.2.2.5]
-synonym: "NAD glycohydrolase activity" EXACT [EC:3.2.2.5]
-synonym: "NAD hydrolase activity" EXACT [EC:3.2.2.5]
 synonym: "NAD nucleosidase activity" EXACT []
-synonym: "NAD+ glycohydrolase activity" EXACT [EC:3.2.2.5]
-synonym: "NADase activity" EXACT [EC:3.2.2.5]
-synonym: "nicotinamide adenine dinucleotide glycohydrolase activity" EXACT [EC:3.2.2.5]
-synonym: "nicotinamide adenine dinucleotide nucleosidase activity" EXACT [EC:3.2.2.5]
-xref: EC:3.2.2.5
-xref: MetaCyc:NADNUCLEOSID-RXN
 xref: RHEA:16304
 is_a: GO:0016799 ! hydrolase activity, hydrolyzing N-glycosyl compounds

 [Term]
+id: GO:0061809
+name: NAD+ nucleotidase, cyclic ADP-ribose generating
+namespace: molecular_function
+def: "Catalysis of the reaction: NAD+ + H2O = nicotinamide + ADP-ribose that proceeds in a stepwise fashion by ADP-ribosyl cyclase activity followed by cyclic ADP-ribose hydrolase activity." [GOC:dph, GOC:pad, GOC:PARL, GOC:pde, PMID:11866528]
+xref: EC:3.2.2.6
+xref: MetaCyc:NADNUCLEOSID-RXN
+is_a: GO:0003953 ! NAD+ nucleosidase activity
+relationship: has_part GO:0061811 ! ADP-ribosyl cyclase activity
+relationship: has_part GO:0061812 ! cyclic ADP-ribose hydrolase
+created_by: dph
+creation_date: 2016-11-11T13:14:13Z
+
+[Term]
+id: GO:0061810
+name: NAD glycohydrolase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: NAD+ + H2O = nicotinamide + ADP-ribose without proceeding through a cyclic ADP-ribose intermediate." [GOC:dph, GOC:pad, GOC:PARL, GOC:pde, PMID:11866528]
+xref: EC:3.2.2.5
+is_a: GO:0003953 ! NAD+ nucleosidase activity
+created_by: dph
+creation_date: 2016-11-11T13:18:54Z
+
+[Term]
+id: GO:0061811
+name: ADP-ribosyl cyclase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: NAD = cyclic ADP-ribose + nicotinamide." [GOC:dph, GOC:pad, GOC:PARL, PMID:11866528]
+is_a: GO:0009975 ! cyclase activity
+created_by: dph
+creation_date: 2016-11-11T13:25:18Z
+
+[Term]
+id: GO:0061812
+name: cyclic ADP-ribose hydrolase
+namespace: molecular_function
+def: "Catalysis of the reaction: cyclic ADP-ribose + H20 = ADP-ribose (ADPR)." [GOC:dph, GOC:pad, GOC:PARL, PMID:11866528]
+is_a: GO:0016799 ! hydrolase activity, hydrolyzing N-glycosyl compounds
+created_by: dph
+creation_date: 2016-11-11T13:32:43Z
+
