### ISSUE TITLE
NTRs: anterior cell cortex and posterior cell cortex

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12781]
Hi,

I'm working on a model for polarity establishment in the early C. elegans embryo and it would be very helpful to have CC terms for anterior and posterior cell cortex to accurately convey the localization of different PAR proteins.

Here is suggested placement, term definitions, and references:

GO:0099738 cell cortex region
-is_a GO:new anterior cell cortex
-is_a GO:new posterior cell cortex

anterior cell cortex
Definition:  The region that lies just beneath the plasma membrane in the part of a cell that is closest to the anterior as defined by the developing, or existing, anterior/posterior axis.

posterior cell cortex
Definition:  The region that lies just beneath the plasma membrane in the part of a cell that is closest to the posterior as defined by the developing, or existing, anterior/posterior axis.

References: PMID:17981131
                   PMID:15666355

Thanks,
--Kimberly

**Comment by ukemi** [comment]
[Term]
+id: GO:0061802
+name: anterior cell cortex
+namespace: cellular_component
+def: "The region that lies just beneath the plasma membrane in the part of a cell that is closest to the anterior as defined by the developing, or existing, anterior/posterior axis." [GOC:15666355, GOC:17981131, GOC:dph, GOC:kmv]
+is_a: GO:0005938 ! cell cortex
+created_by: dph
+creation_date: 2016-11-06T22:54:21Z
+
+[Term]
+id: GO:0061803
+name: posterior cell cortex
+namespace: cellular_component
+def: "The region that lies just beneath the plasma membrane in the part of a cell that is closest to the posterior as defined by the developing, or existing, anterior/posterior axis." [GOC:dph, GOC:kmv, PMID:15666355, PMID:17981131]
+is_a: GO:0005938 ! cell cortex
+created_by: dph
+creation_date: 2016-11-06T22:55:45Z
