### ISSUE TITLE
Discussion of 'positive regulation' and 'maintenance'

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12786]
We discussed two issues surrounding an ontology request for a new term maintenance of differentiated cell state, https://github.com/geneontology/go-ontology/issues/12543

The first involved what is generally meant by 'maintenance of differentiation'
Would this term refer to a developmental process or program that specifically controls de-differentiation after a cell has fully differentiated and a change in its environment results in reversion to an undifferentiated state? Or, does this refer to a process that is simply part of differentiation?
What experiments would adequately demonstrate a distinction between these two?
The second involved what is meant by 'positive regulation of a process' and whether that includes the concept of maintenance of that process
The website guidelines on regulation specifically include 'maintenance', along with 'activation' and 'upregulation', of a process as positive regulation of that process - see http://geneontology.org/page/regulation
However, the existing term definitions for 'positive regulation of biological process' do not specifically state that this includes maintenance; they only refer to 'Any process that activates or increases the frequency, rate or extent of a biological process.' - see http://amigo.geneontology.org/amigo/term/GO:0048518
Should the definition of 'positive regulation of biological process' term (and its children) explicitly refer to maintenance as well as activation and induction?
Do we have examples of process maintenance that is considered regulation of that process?
Requested that this issue be added to an ontology editors call

**Comment by mcourtot** [comment]
Discussed at call 2016-11-17:
Historically, maintains part of positive regulation as per http://geneontology.org/page/regulation. However maintenance has disappeared from the positive regulation of biological process - which was an issue for curation.
Note this is the maintenance of the process, not the end state. Eg maintaining something by keeping it localised somewhere wouldn't be encompassed as the localisation process itself is already over, and we only maintain the end state of being localised.

**Comment by dosumis** [comment]
Some notes on the example in #12543:

miRNA binding to BDNF mRNA 3'UTR represses BDNF levels in differentiated myotubes.  In the absence of the miRNA binding sites, BDNF levels rise and myotubes de-differentiate (this is not shown in the paper but is apparently a well known affect).

This is evidence that one role of these miRNAs is to maintain the differentiation state of myotubes.  Is this a regulatory process or not?

If it is, then I'm not sure the distinction between a process that maintains some state a maintenance of a quality (the terminal differentiation state) makes much sense in this case.  The differentiation state of a cell depends on many regulatory interactions (processes) that maintain the expression of genes that => differentation state.

**Comment by ValWood** [comment]
I was trying to look at  all the places where PomBase has used terms for *maintenance*.

we have things like this
GO:1902406 - mitotic actomyosin contractile ring maintenance
with regulation children

GO:0000723 telomere maintenance
with regulation children

GO:0070829 - heterochromatin maintenance
does not have regulation children

 GO:0000002 - mitochondrial genome maintenance


to be honest in 2016 these all sound a bit phenotype-y, but none are defined as a type of regulation.....

**Comment by tberardini** [comment]
>AI for Tanya: figure out how many positive regulation terms do not have 'maintains' in the definition

OE query: Name starts with 'positive regulation of' AND definition NOT contains 'maintains'
**3141 terms**

>AI for Tanya: figure out if any maintenance terms exist that are children of pos reg??

OE query: Name starts with 'maintenance of'
**121 terms**

I'm having trouble running the query that includes the parentage to positive regulation as the reasoner is crashing OE.

OE query: Name starts with 'maintenance of' AND ancestor(OBO REL:is_a) Name starts with 'positive regulation of'

@mcourtot : can you give the second query a go in Protege?  Thanks very much.

**Comment by mcourtot** [comment]
Sorry not sure how to do that via DL query - maybe @dosumis knows?

**Comment by dosumis** [comment]
> On Nov 23, 2016, at 10:00 AM, Melanie Courtot <notifications@github.com> wrote:
> 
> Sorry not sure how to do that via DL query - maybe @dosumis <https://github.com/dosumis> knows?
> 
> 

Not possible.  Could be done with a script that runs a DL query for sucblasses of postive regulation of biological process and then does regex against names/definitions .

**Comment by mcourtot** [comment]
@dosumis : do you know if Brain supports regex in class labels?

**Comment by dosumis** [comment]
This should work:

1. run DL query via brain -> list of IDs
2. Use brain to retrieve labels and definitions by ID
3. Use Python regex to check labels and definitions.

**Comment by tberardini** [comment]
OE search: term name starts with 'positive regulation', definition contains 'maintains':

**214 terms**

**Comment by tberardini** [comment]
@dosumis - were you able to do this DL + brain +python  combo analysis?

**Comment by hattrill** [comment]
As this issue seems to have started with maintenance of differentiation, could I point to 2 papers to this that concern "maintenance of neuronal differentiation" and "dedifferentiation" that we are not sure how to annotate and leave you with some open questions?

Prevention of medulla neuron dedifferentiation by Nerfin-1 requires inhibition of Notch activity. PMID:28242614
Conclusion:"Nerfin-1 represses Notch activity in medulla neurons and prevents them from dedifferentiation"
&
Dedifferentiation of Neurons Precedes Tumor Formation in lola Mutants. PMID:24631403.
Conclusion: "whereas Prospero acts to block self-renewal and initiates neuronal differentiation, Lola is required to maintain the differentiated state."

In these cases is "maintenance of differentiation" or "negative regulation of cell dedifferentiation" (note: we have GO:0043697 cell dedifferentiation) or (if the definition of regulation is changed to include maintenance) "positive regulation of differentiation"?

In both cases the factors preventing dedifferentiation are only expressed in the differentiated cells, so where does the process of differentiation "end" - when the cells pass a point when they cannot dedifferentiate or at the moment when they become recognisable as different from the progenitor?

**Comment by ValWood** [comment]
I think we can close as out of date.
