### ISSUE TITLE
MP: GO:0007288 - sperm axoneme assembly

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#12790]
Note: This issue came up as part of this ticket:
https://github.com/geneontology/go-ontology/issues/12695#issuecomment-250826199 
but it was requested it be entered as a separate new ticket.

Currently, there is no relationship between “flagellated sperm motility” and “sperm axoneme assembly”. However, now that there is a term specifically for “flagellated sperm motility” specifically distinguished from any other types of “sperm motility” including “amoeboid sperm motility”, I think there actually could be connections between these. It seems to me that “sperm axoneme assembly” could be part_of “flagellated sperm motility”, and that a reciprocal has_part relationship would also be valid. 

@paolaroncaglia previously commented:
I’m not sure, it sounds vaguely odd. If the sperm axoneme wasn’t assembled, would the sperm be flagellated at all? It certainly wouldn’t be motile, but that sounds way more upstream than has_part (or even starts_with) to me.

I agree that '''sperm axoneme assembly''' is upstream, but it is definitely a required part of '''flagellated sperm motility'''. As an annotator, it would be nice to be able to make an annotation 
to '''sperm axoneme assembly''' and have it map up to '''flagellated sperm motility''' without having to double annotate, so I would like to have this part_of relationship.

I still think the reciprocal "has_part" relationship is also true, but I don't care as much whether it is added or not since it doesn't affect my current annotation practice.

thanks,

Karen

**Comment by paolaroncaglia** [comment]
Hi @krchristie ,

I certainly agree that we should add links in the ontology when 2 annotations would co-occur necessarily. My lexical dilemma about this one is - 
a) you agree that ‘sperm axoneme assembly’ is upstream of ‘flagellated sperm motility’
b) ‘flagellated sperm motility’ is defined as “Any process involved in the controlled movement of a flagellated sperm cell.” so it’s referring to a cell that already has a flagellum - the axoneme must have been assembled already, i.e., one process is upstream of the other, as you agreed
c) therefore, to me the correct ontology link would be ‘sperm axoneme assembly’ causally_upstream_of ‘flagellated sperm motility’. In that sense it *is* indeed a required part of the motility, but not in the strict GO meaning of part_of.  
I’m quite sure that annotations are not propagated via causally_upstream though. 

Would you mind if I asked @ukemi to comment please? I might be over-analysing things here, but the stubborn editor in me needs to be convinced before adding that part_of :-)

Thanks for your patience… and apologies for my bad mood today...

**Comment by krchristie** [comment]
HI @paolaroncaglia 

Of course I don't mind if you ask @ukemi to comment. 



From an annotator's perspective though, I have seen many, many papers where they show that

**Comment by krchristie** [comment]
@paolaroncaglia 

Of course I don't mind if you ask @ukemi  to comment.

From an annotator's perspective, I have seen many papers where they show loss of sperm motility and then show that the reason for the loss of motility is a defect in '''sperm axoneme assembly'''. Defects in '''sperm axoneme assembly''', both ones that completely prevent assembly of the axoneme, or ones that allow assembly, but the resulting axoneme is defective in motility, whether completely immotile or with some more subtle defect, all cause defects in '''flagellar sperm motility'''.

I do realize that GO has become more sophisticated with the logical relationships used and I don't fully follow all of that discussion. So, if there is a better relationship to use than "part_of", that's fine with me.

**Comment by ukemi** [comment]
Hmm. I think this distinction is subtle. As far as I know, we are not yet capturing the causally upstream relations in the ontology, but I think Paola has a good point. It would be nice if we could co-annotate these for now and capture the causal relation. But that is in the future. Maybe put a comment on the assembly term and suggest annotating to the motility term to co-annotate. How can we keep a note to remind us that we want to use the causally_upstream qualifier when it becomes available? This is a great case for LEGO. 

So unless you think the assembly of the axoneme is process that is a required component of the motility, I think it is upstream. My 2 cents.

**Comment by krchristie** [comment]
That's exactly what I think, that the assembly of the axoneme is a required component of the motility.

-Karen

**Comment by paolaroncaglia** [comment]
@krchristie and @ukemi
OK, thanks for your feedback. I added the link
sperm axoneme assembly part_of flagellated sperm motility
and I’ll leave it to @ukemi to make a note (whether on a noctua GH tracker or in his head ;-)) as a reminder to use the causally_upstream qualifier when it becomes available. Closing now, thanks.
