### ISSUE TITLE
def of cellular localization, odd

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12797]
is defined?
GO:0051641
Name	cellular localization
Ontology	Biological Process
Definition	A localization process that takes place at the cellular level; as a result of a cellular localization process, a substance or cellular entity, such as a protein complex or organelle, is transported to, and/or maintained in, a specific location within or in the membrane of a cell.

(not sure why membrane)

Also should have cellular process parent based on "that takes place at the cellular level; "

**Comment by tberardini** [comment]
@mah11 : your initials are on this - any memories at all about this term?

[Term]
id: GO:0051641
name: cellular localization
namespace: biological_process
def: "A localization process that takes place at the cellular level; as a result of a cellular localization process, a substance or cellular entity, such as a protein comple\
x or organelle, is transported to, and/or maintained in, a specific location within or in the membrane of a cell." [GOC:ai, GOC:mah]
subset: goslim_pir
subset: gosubset_prok
synonym: "cellular localisation" EXACT [GOC:mah]
synonym: "establishment and maintenance of cellular localization" EXACT []
synonym: "establishment and maintenance of localization in cell or cell membrane" EXACT []
synonym: "intracellular localization" NARROW []
synonym: "localization within cell" NARROW []
is_a: GO:0051179 ! localization

**Comment by mah11** [comment]
Nothing specific after this long ...

**Comment by tberardini** [comment]
> within or in the membrane of a cell.

I'm parsing this as 

'within a cell' OR 'in the membrane of a cell' 

instead of 

'within the membrane of a cell' OR 'in the membrane of a cell'

So anything inside the cell or in (part of) the (outermost?) membrane of a cell.

**Comment by ValWood** [comment]
OK,

so just "within a cell"  works ?

**Comment by tberardini** [comment]
I think the extra wording referring to the membrane is in there to make explicit that the gene product can be inserted the membrane itself.  I can update the definition to make that clear and remove the ambiguity.

**Comment by ukemi** [comment]
Maybe change to plasma membrane?

**Comment by ValWood** [comment]
I sill don't really understand why this term mentions  any kind of membrane.

The term is "cellular localization" It could apply to anything in the cell. A membrane is part of a cell.

This def should just say
"a specific location within  a cell"

then it would no longer be confusing ?

**Comment by mah11** [comment]
Why is it _inherently_ confusing to point out that potential end locations include the membrane?

(The pre-change wording is perhaps sub-optimal, but that problem can be remedied while still mentioning the membrane, to guard against the term being mistaken for excluding membrane localization.)

**Comment by ValWood** [comment]
Well clearly its just me, but I thought it was a cut and past error, because I can't think of any reason why anyone would think it might exclude the localization to a membrane. 

"a specific location within a cell" seems more accurate to me.
To me, the current definition  implies that all of the location is membrane, however I read it.

**Comment by mah11** [comment]
so that "OR" in front of "in the membrane" doesn't register?

anyway, Tanya said she'd improve that wording, so it'll be even less confusing

**Comment by ValWood** [comment]
Oh I get it.
I was reading
 (within or in) the membrane of a cell
not
(within) or (in the membrane of a cell)

**Comment by mah11** [comment]
ah ... it never occurred to me that "within or in" wouldn't be recognized as redundant, and therefore not the intended reading. But Tanya's planned edit will sort that.

**Comment by tberardini** [comment]
>OLD: A localization process that takes place at the cellular level; as a result of a cellular localization process, a substance or cellular entity, such as a protein complex or organelle, is transported to, and/or maintained in, a specific location within or in the membrane of a cell.

NEW:  A cellular localization process whereby a substance or cellular entity, such as a protein complex or organelle, is transported to, and/or maintained in, a specific location within a cell including the localization of substances or cellular entities to the cell [plasma?] membrane.

Not quite ideal but better. Edits welcome.

**Comment by ValWood** [comment]
Lets say that's OK, this one has been rather long for one word. Sorry!

**Comment by tberardini** [comment]
UPDATED DEFINITION: A cellular localization process whereby a substance or cellular entity, such as a protein complex or organelle, is transported to, and/or maintained in, a specific location within a cell including the localization of substances or cellular entities to the cell membrane.
