### ISSUE TITLE
NTR: negative regulation of inhibitory synapse assembly 

### ISSUE THREAD

**Issue by paolostefano28** [geneontology/go-ontology#12798]
Hi,

I'm annotating PMID:27779093, which is on mouse MEF2C. I need a child term for GO: 0051964 negative regulation of synapse assembly. This term would be "negative regulation of inhibitory synapse assembly" because GO:1904890 negative regulation of excitatory synapse assembly, a child term of negative regulation of synapse assembly only applies to excitatory synapses. 

Definition: Any process that stops, prevents or reduces the frequency, rate or extent of inhibitory synapse assembly.

Mi name is Paolo Giovanelli and i'm a CACAO student.

**Comment by paolostefano28** [comment]
Also the new Go term for positive regulation of inhibitory synapse assembly should be created as a child of GO:0051965 positive regulation of synapse assembly.

**Comment by tberardini** [comment]
Added using TermGenie:

    ID: GO:1905702 Label: regulation of inhibitory synapse assembly
    ID: GO:1905703 Label: negative regulation of inhibitory synapse assembly
    ID: GO:1905704 Label: positive regulation of inhibitory synapse assembly
