### ISSUE TITLE
cellular processes missing cellular process parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12796]
I spotted

GO:0071840 cellular component organization or biogenesis
GO:0055085 transmembrane transport]have both had "cellular process" parent deleted. 
GO:0016192 vesicle-mediated transport
GO:0006913 nucleocytoplasmic transport
GO:0007034 vacuolar transport

lost "cellular process parent"
Any reason for that?

GO:0097428 protein maturation by iron-sulfur cluster transfer
(but this never had it)

val

**Comment by ValWood** [comment]
Also GO:0016192 vesicle-mediated transport

**Comment by ValWood** [comment]
Note that the definition of cellular process is:

Any process that is carried out at the cellular level, but not necessarily restricted to a single cell. For example, cell communication occurs among more than one cell, but occurs at the cellular level.

**Comment by ValWood** [comment]
and GO:0006913 "nucleocytoplasmic transport"

**Comment by tberardini** [comment]
@paolaroncaglia , @dosumis, @ukemi , @mcourtot:
Before addressing the terms one by one, I'm going to leave this ticket open for a bit to see if anyone remembers dealing with their parentage.  I haven't touched them but possibly others have in their work.

**Comment by ValWood** [comment]
GO:0097428 protein maturation by iron-sulfur cluster transfer
(although this never had the parent)

**Comment by ValWood** [comment]
GO:0007034 vacuolar transport
(used to have intracellular transport which would give it a cellular process parent, maybe there is a  violation here, an't think of one...)

**Comment by ukemi** [comment]
Is it really worth distinguishing things 'at the cellular level' in GO?

**Comment by ValWood** [comment]
It might not be but we always have. Its probably *more* useful for multicellular eukaryotes?
In yeast everything is at the cellular level...

**Comment by ValWood** [comment]
It is in the pir and plant slims, so might be worth checking there (I thought it was in the generic slim, but it isn't....)

**Comment by ukemi** [comment]
With LEGO, we can capture the location of where functions and processes are occurring in a much better way. It doesn't have to be fuzzy 'at the level of'.

**Comment by tberardini** [comment]
>It is in the pir and plant slims, so might be worth checking there (I thought it was in the generic slim, but it isn't....)

What is 'it'?

**Comment by ValWood** [comment]
> What is 'it'?
"cellular process"

 > It doesn't have to be fuzzy 'at the level of'.
true....

Is there an easy way at present to distinguish all cell level things from the tissue level/behaviour/homeostasis of number of cells/ system process etc?
(it will be  a long time before you can do that with LEGO derived annotation if there is not another way...)

**Comment by paolaroncaglia** [comment]
@tberardini 
FYI, I don't remember dealing with those "cellular process" parents...

**Comment by mcourtot** [comment]
@tberardini: sorry, I don't remember with dealing with any of those parents either.

**Comment by ukemi** [comment]
Nor do I.

**Comment by dosumis** [comment]
The transport one might have been my edits while cleaning up to improve inference.  The ideal way to fix it would be to have a term for 'cellular transport' to use as the genus.  Unfortunately we don't have this term.  We could assert 'cellular process' as a parent, but the logical definition:

transport
 and (mediated_by some vesicle)

may result in classifications that contradict that in future.  For example, transport in exosomes between cells is vesicle mediated, but is this cellular (?)

> Is there an easy way at present to distinguish all cell level things from the tissue level/behaviour/homeostasis of number of cells/ system process etc?

How about: A process occurring in or involving exactly one cell?

But note:  cellular component organization includes organization of extracellular structures, which doesn't fit this def.

**Comment by ValWood** [comment]
Cell level processes  shouldn't exclude "organization of extracellular structures".

> For example, transport in exosomes between cells is vesicle mediated, but is this cellular (?)

We (pombase curators), are thinking that all things *mediated* by a single cell are cellular . However, we are now tripping up over "conjugation" in fungi, which is mediated by more than one cell, but we still think of as cellular, so this is not "sufficient". Unless of course we accept that conjugation is not cellular....?

**Comment by ValWood** [comment]
Some parts of conjugation are mediated by a single cell (shmooing), and some parts (cytogamy) are not cellular...so perhaps that would be fine. The parts which *are* cellular would have *cellular process* parents.

**Comment by dosumis** [comment]
"Cell level processes shouldn't exclude "organization of extracellular structures."

Then I think we're stuck with the existing def (and lots of tickets arguing over it...)

If we agree that everything that occurs in a cell is cellular, we could at least automate some of this by adding the axiom:

biological_process that occurs_in some cell SubClassOf: 'cellular process'

@cmungall  Do we have a place where GCIs like this can live?

**Comment by cmungall** [comment]
In this case, it wouldn't go to the header, it would look like this:

```
id: GO:0008150
name: biological_process
is_a: GO:0009987 {gci_relation="occurs_in", gci_filler="GO:0005623"} ! cellular process
```

http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.2.2

This will look confusing in OE, as OE doesn't take into account qualifiers in making the hierarchy

We'd want to filter this axiom from the public obo releases

**Comment by cmungall** [comment]
So as not to divert this ticket I started a document with some thoughts about problems with cellular-X terms: https://docs.google.com/document/d/1QpfUY_LgeIryMj6EEAE05FXLE_894GalkerBU8dMuVU/edit

**Comment by tberardini** [comment]
Is there any action that I could/should take on the particular terms that Val has brought to our attention? 

Two suggestions from @dosumis:

1.  The ideal way to fix it would be to have a term for 'cellular transport' to use as the genus. Unfortunately we don't have this term. We could assert 'cellular process' as a parent, but the logical definition [of 'vesicle transport']:
>transport
>and (mediated_by some vesicle)

may result in classifications that contradict that in future. For example, transport in exosomes between cells is vesicle mediated, but is this cellular (?)

2.  If we agree that everything that occurs in a cell is cellular, we could at least automate some of this by adding the axiom:

biological_process that occurs_in some cell SubClassOf: 'cellular process'

(see Chris' response above to why that might be problematic)

**Comment by tberardini** [comment]
Linking to the bigger issue #12849

**Comment by ValWood** [comment]
Even though this might be a "bigger issue" it  looks very odd to a biologist that none of these terms are is_a "cellular process"

<img width="401" alt="Screen Shot 2020-03-09 at 21 00 49" src="https://user-images.githubusercontent.com/7359272/76257223-37693d80-6249-11ea-8690-08c1ffa8d016.png">

Could  these links be instantiated and this ticket closed pending the "bigger issue" #12849 ticket?

Note, this ticket was opened in 2016  so the "longer-term solution" does not seem to be imminent.

**Comment by ValWood** [comment]
Don't the logical definitions sort situations  like this? It's quite 'high-level"  stuff.

**Comment by pgaudet** [comment]
Changed subclasses: 

* GO:0071840 cellular component organization or biogenesis
from biological_process to 'cellular process' 

* GO:0055085 transmembrane transport]have both had "cellular process" parent deleted.
Added subclass 'cellular process' 

* GO:0016192 vesicle-mediated transport
Added subclass 'cellular process' 

* GO:0006913 nucleocytoplasmic transport
Added subclass 'cellular process'  to (great-grand) parent 'cellular localization'
GO:0007034 vacuolar transport

**Comment by pgaudet** [comment]
Also added 'cellular process' subclass to: 

* GO:0007155 cell adhesion 
* GO:0098743 cell aggregation *
* GO:0001906 cell killing *
* GO:0008283 cell population proliferation  *
* GO:0051674 localization of cell
* GO:0061842 microtubule organizing center localization


* *were direct children of biological_process
