### ISSUE TITLE
regulation of DNA recombination at centromere

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12791]
This is modeled on GO:0072695, which doesn't have a logical def (there are no separate terms for 'DNA recombination at telomere' or 'DNA recombination at centromere', which is probably OK because different regulatory processes act but the regulated recombination process is itself the same at the different locations; hence not done in TG).

name: regulation of DNA recombination at centromere
def: "Any process that modulates the frequency, rate or extent of DNA recombination within centromeric DNA." [GOC:mah, PMID:27697832]
synonym: "regulation of centromeric recombination" EXACT [GOC:mah]
is_a: GO:0000018 ! regulation of DNA recombination

I only need the generic 'regulation' term, but I don't have any reason not to add the positive and negative regulation terms as well. I plan to use it to annotate pombe rad51 and rad54, which regulate whether recombination at centromeres goes via crossover or non-crossover pathways.

**Comment by ukemi** [comment]
All makes perfect sense to me. Added three terms and corrected what appears to have been a cut and paste error on the telomere term.

 [Term]
+id: GO:0061806
+name: regulation of DNA recombination at centromere
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of DNA recombination within centromeric DNA." [GOC:dph, GOC:mah, PMID:27697832]
+synonym: "regulation of centromeric recombination" EXACT [GOC:mah]
+is_a: GO:0000018 ! regulation of DNA recombination
+created_by: dph
+creation_date: 2016-11-10T15:17:11Z
+
+[Term]
+id: GO:0061807
+name: positive regulation of DNA recombination at centromere
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of DNA recombination at the centromere." [GOC:dph, GOC:mah]
+synonym: "positive regulation of centromeric recombination" EXACT [GOC:mah]
+is_a: GO:0045911 ! positive regulation of DNA recombination
+is_a: GO:0061806 ! regulation of DNA recombination at centromere
+created_by: dph
+creation_date: 2016-11-10T15:20:04Z
+
+[Term]
+id: GO:0061808
+name: negative regulation of DNA recombination at centromere
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of genetic recombination at the centromere." [GOC:dph, GOC:mah]
+synonym: "regulation of centromeric recombination" EXACT [GOC:dph]
+is_a: GO:0045910 ! negative regulation of DNA recombination
+is_a: GO:0061806 ! regulation of DNA recombination at centromere
+created_by: dph
+creation_date: 2016-11-10T15:24:50Z

name: positive regulation of DNA recombination at telomere
 namespace: biological_process
-def: "Any process that stops, prevents, or reduces the frequency, rate or extent of genetic recombination within the telomere." [GOC:mah]
+def: "Any process that activates or increases the frequency, rate or extent of DNA recombination within the telomere." [GOC:mah]
 synonym: "activation of telomeric recombination at telomere" NARROW [GOC:mah]
 synonym: "positive regulation of telomeric recombination" EXACT [GOC:mah]
 synonym: "up regulation of telomeric recombination at telomere" EXACT [GOC:mah]

**Comment by mah11** [comment]
Thanks! I hadn't even spotted the mistake in the telomere def ...

**Comment by ValWood** [comment]
re> I plan to use it to annotate pombe rad51 and rad54, which regulate whether recombination at centromeres goes via crossover or non-crossover pathways.

I haven't read the papers, but is this process really different at non-centromeric regions? Or is there just more recombination here because of the number of repeats?

If we don't know that it is  a different process, I would not put it in GO (we might have centromere specific recombination phenotypes, but these could be logically defined using GO +SO?

If it really is a special centromere specific pathway, thats fine...
but maybe its more a general pathway to suppress recombination by x pathway between inverted repeats, of which there happen to be a lot at the centromere?
