### ISSUE TITLE
autophagy molecular functions

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12793]
There are several molecular functions that specifically describe enzymes used for autophagosome organization. Those enzymes need to have has_part relations to the autophagosome process. For now we cannot make part_of relations because at least some of them are also used for the cvt pathway.

GO:0061660	Catalysis of the transfer of Atg12 to a substrate protein via the reaction X-Atg12 + S --> X + S-Atg12, where X is either an E2 or E3 enzyme, the X-Atg12 linkage is a thioester bond, and the S-Atg12 linkage is an isopeptide bond between the C-terminal amino acid of Atg12 and the epsilon-amino group of lysine residues in the substrate.	Atg12 ligase activity
GO:0061651	Isoenergetic transfer of Atg12 from one protein to another via the reaction X-Atg12 + Y -> Y-Atg12 + X, where both the X-Atg12 and Y-Atg12 linkages are thioester bonds between the C-terminal amino acid of Atg12 and a sulfhydryl side group of a cysteine residue.	Atg12 conjugating enzyme activity
GO:0019776	Catalysis of the covalent attachment of the ubiquitin-like protein Atg8 to substrate molecules; phosphatidylethanolamine is a known substrate.	Atg8 ligase activity
GO:0019786	Catalysis of the hydrolysis of APG8, a small ubiquitin-related modifier.	Atg8-specific protease activity
GO:0019779	Catalysis of the activation of the small ubiquitin-related modifier APG8, through the formation of an ATP-dependent high-energy thiolester bond.	Atg8 activating enzyme activity
GO:0019778	Catalysis of the activation of the small ubiquitin-related modifier APG12, through the formation of an ATP-dependent high-energy thiolester bond.	Atg12 activating enzyme activity
GO:0019777	Catalysis of the transfer of ATG12 from one protein to another via the reaction X-ATG12 + Y --> Y-ATG12 + X, where both X-ATG12 and Y-ATG12 are covalent linkages.	Atg12 transferase activity

**Comment by ukemi** [comment]
The Atg8 transferase molecular functions were already a part of 'protein lipidation involved in autophagosome formation. I added the Atg12 functions as parts of the assembly term.

term: autophagosome assembly
 is_a: GO:0070925 ! organelle assembly
 intersection_of: GO:0022607 ! cellular component assembly
 intersection_of: results_in_assembly_of GO:0005776 ! autophagosome
+relationship: has_input GO:0000407 ! pre-autophagosomal structure
+relationship: has_part GO:0019778 ! Atg12 activating enzyme activity
+relationship: has_part GO:0019786 ! Atg8-specific protease activity
+relationship: has_part GO:0061651 ! Atg12 conjugating enzyme activity
+relationship: has_part GO:0061660 ! Atg12 ligase activity
+relationship: has_participant GO:1990462 ! omegasome

From looking at current annotations and the structure of the ontology, it looks like Atg1/Ulk1 is a regulator of autophagy. That is involved in the formation of the PAS. However, in the ontology the ATG1/ULK1 complex has a capable_of_part_of relationship to 'autophagosome assembly'. This is inconsistent. Do we want to change the definition of autophagosome assembly to include the function of the ULK1 complex, or do we want to change the relationship of the complex to capable_of_part_of 'positive regulation of autophagosome assembly'?

@Pauldenny @paolaroncaglia @RLovering @marcfeuermann

**Comment by ukemi** [comment]
Note I have removed the component participants for now.

**Comment by ukemi** [comment]
In mouse: Ulk1 is annotated to autophagy, macroautophagy and 'autophagosome assembly.
In human: ULK1 is annotated to autophagy, macroautophagy, 'positive regulation of macroautophagy', 'mitohagy in response to mitochondrial depolarization' and 'positive regulation of autophagy'.
In S. cerevisiaea: Atg1 is annotated to 'autophagosome assembly', mitophagy, autophagy, 'piecemeal autophagy of the nucleus', 'late nucleophagy', and reticulophagy.
in S. pombe: Atg1 is annotated to autophagy and macroautophagy.

According to PMID:26431564 the Atg1 kinase is required for the initiation of macroautophagy and is sufficient to make macroautophagy happen.

According to PMID:21311563 mTOR negatively regulates the formation of the ULK1/2 complexes. When this inhibition is removed, macroautophagy proceeds. 

From this I propose that we make GO:1904745 (ATG1/ULK1 kinase complex assembly) the initial step in 'autophagosome assembly'. This means that the relationship between the complex and the process is correct, but the human annotations to the regulation terms should be revisited. I think I remember that we had discussed this before and came to the same conclusion, but the human annotations make me unsure of that.

**Comment by marcfeuermann** [comment]
Hi David, 
Yes we had discussed this before and I agree that GO:1904745 is the initial step in autophagy assembly. I think that the ATG1/ULK1 complex defines a clear border between regulation (upsteam) and the process itself (ATG1/ULK1 and downstream). So the "regulation" term for human ULK1 has to be removed. 
All the other annotations seem correct to me, including the regulation by mTOR :-)
Marc.

**Comment by ukemi** [comment]
Hi Marc,
Thanks! I'm glad we remember this the same way. I will make macroautophagy start with autophagosome assembly and I will make autophagosome assembly start with GO:1904745. I agree, that this nicely distinguishes the regulation by mTOR. According to PMID:21311563 macroautophagy is also regulated at the Beclin1/Atg6 step, but I think the Beclin1has a direct function in the process and it is acted upon by regulatory mechanisms. I have asked that the mouse annotation of Becn1 to the regulation term be reconsidered. 
-D

**Comment by marcfeuermann** [comment]
I like it like that. It's true that, despite the numerous articles about ATG6/BECN1, it is difficult to define its precise function. It is a subunit of  PI3K complexes involved in initiation ( PI3KC3-C1) and maturation (PI3KC3-C2) of autophagosomes though mediating formation of phosphatidylinositol 3-phosphate.
In my opinion, it's clearly part of the process, not of the regulation.

**Comment by ukemi** [comment]
OK. The structure is now in place where macroautophagy is defined as an autophagy that starts with autophgaosome assembly and autophagosome assembly has a starts with relationship with ATG1/ULK1 kinase complex assembly. I'm going to close this one. I might open another with respect to cellular components, but that doesn't fit with this ticket.

**Comment by ValWood** [comment]
this all agrees with what Rama  and Maria told me back in 04/12/2009  when I asked why ATG1 wasn't annotated to regulation ;)

==
Hi all,

It seems to me that ATG1 plays an integral part in autophagy, and I wouldn't call this a regulatory role. In the autophagy figure, I think it's TOR and nutrients that are the regulatory factors.

Maria 

==
Hey Val,

I see that the figure says 'Regulation of Induction' in that first box.
Regulation of macroautophagy is defined as- Any process that modulates the frequency, rate or extent of macroautophagy.
Why I am uncomfortable to make this annotation- In nutrient starved conditions, ATG13 activates ATG1 and that is what gets the whole thing going. It is a signal that starts the next step. There is no change in frequency/rate of the process caused by ATG1 activation. So that part of the definition doesn't apply. The only part that is left to curator intrepratation is tthe word 'extent'.
Unlike other processes there is no base line autophagy that happens all the time and ATG13/ATG1 upregulates it. Either it happens or it doesn't (1 or 0 switch).
In light of all these thoughts, I don't know if this regulation term is correct here.

Let me know your thoughts.

Thanks for listening.

**Comment by Pauldenny** [comment]
Reviewing Human annotations - ULK1 is annotated to autophagy, macroautophagy, 'positive regulation of macroautophagy', 'mitophagy in response to mitochondrial depolarization' and 'positive regulation of autophagy'.
1. Ruth updated 'positive regulation of macroautophagy' to 'macroautophagy'
2. Paul contacted SWISS curators asking them to review 2 annotations ULK1 'positive regulation of autophagy' November 14th 2016.

**Comment by marcfeuermann** [comment]
The 2 annotations to "regulation of autophagy" for human ULK1 have just been updated to "autophagy".
