### ISSUE TITLE
Persona shutdown 

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12795]
"Persona is no longer actively developed by Mozilla. Mozilla has committed to operational and security support of the persona.org services until November 30th, 2016. On November 30th, 2016, Mozilla will shut down the persona.org services. Persona.org and related domains will be taken offline. If you run a website that relies on Persona, you need to implement an alternative login solution for your users before this date. For more information, see this guide to migrating your site away from Persona: https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers"

Minutes from call, http://wiki.geneontology.org/index.php/Ontology_meeting_2016-10-27#persona.org

Chris: you’ll see this reflected first in Noctua; will be able to log in via GH or Google; that’ll happen before the GOC mtg. For TG, we’ll probably use the same mechanism we use for Noctua. TG may have to be down for a week or so during that change.

**Comment by kltm** [comment]
Now dupe of geneontology/termgenie#98
