### ISSUE TITLE
NTR: Regulation of synapse disassembly 

### ISSUE THREAD

**Issue by paolostefano28** [geneontology/go-ontology#12799]
Hi,

I am a CACAO student and I am annotating PMID: 27779093 for mouse MEFC2. I need several child terms for the existing term **GO: 0098883 Synapse disassembly**. 

First, I need the term "**Regulation of Synapse disassembly"**. The proposed definition is:  _Any process that modulates the frequency, rate or extent of synapse disassembly_ , which is opposite to the definition of the existing term GO:0051963 regulation of synapse assembly. 

Under **Regulation of synapse disassembly**, there should be child terms **positive regulation of synapse disassembly** as well as **negative regulation of synapse disassembly**.

Moreover, under **positive regulation of synapse disassembly** there should be both **positive regulation of excitatory synapse disassembly**  and **positive regulation of inhibitory synapse dissasembly**.

Similarly, under **negative regulation of synapse disassembly**, there should be child terms **negative regulation of excitatory synapse disassembly** and **negative regulation of inhibitory synapse dissasembly**.

A total of 7 terms are being requested. 

Thank you

**Comment by tberardini** [comment]
The first three terms [positive/negative]regulation of synapse disassembly can be created easily through TermGenie.  I'll do that.  For the other four, we first need to create the terms for 'excitatory synapse disassembly' and 'inhibitory synapse disassembly' and then can create the regulation terms for them.

Can the same PMID be used for ALL of the suggested new terms? Not just the regulation ones?  If yes, I will go ahead and create all of them.

**Comment by suzialeksander** [comment]
We're not overly confident on what exactly should be annotated to this paper.  Most of these terms are because there are holes in the ontology.  We usually use GitHub instead of using TermGenie ourselves to ensure the terms we're requesting are reasonable.

The short answer is probably not.  

Thanks

**Comment by tberardini** [comment]
@suzialeksander @paolostefano28 :  Which ones are the terms that you think you need for annotation?  Please list.  Those are the ones that I'll add.  

If you have references to support the creation of the terms 'inhibitory synapse disassembly' and 'excitatory synapse disassembly', those can be added as well.  Thanks.

**Comment by suzialeksander** [comment]
*We definitely need:
Neg. reg. of excitatory synapse disassembly 

*We want something to reflect:
Neg. reg. of inhibitory synapse formation and/or stability (I think this falls under "organization")
possibly Negative GO:0050807 regulation of synapse organization (if the inhibitory/excitatory is too much detail for GO).



PMID:27779093 states "These results suggest that endogenous MEF2C functions predominantly as a transcriptional repressor to inhibit target genes that promote excitatory synapse elimination and inhibitory synapse formation and/or stability."
We'll ask the neurobiology department for a review for the other terms.

**Comment by tberardini** [comment]
@suzialeksander : need a reference for 'excitatory synapse disassembly' - can I use PMID:27779093? I can use the standard template definition to create it.  Thanks.

**Comment by tberardini** [comment]
Status for commit #90804: Success

    ID: GO:1905805 Label: excitatory synapse disassembly
    ID: GO:1905806 Label: regulation of synapse disassembly
    ID: GO:1905807 Label: negative regulation of synapse disassembly
    ID: GO:1905808 Label: positive regulation of synapse disassembly
    ID: GO:1905809 Label: negative regulation of synapse organization

**Comment by tberardini** [comment]
Status for commit #90901: Success

    ID: GO:1905810 Label: regulation of excitatory synapse disassembly
    ID: GO:1905811 Label: negative regulation of excitatory synapse disassembly

@suzialeksander: I've added terms as you requested. If you need any more, please open a new issue.

Thanks.
