### ISSUE TITLE
NTR: ARID domain binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#12792]
Hi,

I am currently annotating PMID:  18270511 and in Fig 2 , they show that RBP2 ARID (AT-rich interaction domain) specifically binds to the CCGCCC motif in the BRD2  promoter.
Could you please add the new term "ARID domain binding" to capture that?
The domain is identified in interpro under ARID DNA-binding domain (IPR001606) (https://www.ebi.ac.uk/interpro/entry/IPR001606).
It can be a child of GO:0019904 protein domain specific binding.

A possible definition could be : Interacting selectively and non-covalently with a ARID domain.  The AT-rich interaction domain (ARID) is an ~100-amino acid DNA-binding module found in a large number of eukaryotic transcription factors.

Best regards,

Penelope

**Comment by ukemi** [comment]
[Term]
+id: GO:0061813
+name: ARID domain binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a ARID domain. The AT-rich interaction domain (ARID) is an ~100-amino acid DNA-binding module found in a large number of eukaryotic transcription factors." [GOC:dph, InterPro:IPR001606, PMID:18270511]
+is_a: GO:0019904 ! protein domain specific binding
+created_by: dph
+creation_date: 2016-11-11T13:57:55Z

**Comment by ValWood** [comment]
I don't understand this one.
The ARID domain is interacting with the promoter (Its a DNA binding domain).  So which protein will be annotated with "ARID domain binding"?

Not itself....

**Comment by ukemi** [comment]
I assume this term will be used for something that binds the ARID domain in a protein that contains it.

**Comment by ValWood** [comment]
Does ARID domnain bind proteins too?
I thought it was only DNA binding...

http://planttfdb_v1.cbi.pku.edu.cn:9010/web/family_structure/ARID_structure.php

**Comment by ukemi** [comment]
I don't know, but if there is something that binds an ARID domain, we now have a term for it. If you think it should be obsoleted, let me know.

**Comment by ValWood** [comment]
to work for the statement in the term request, you would need to be annotating "the BRD2 promoter"

**Comment by ukemi** [comment]
Yup, but the term and it's definition are valid as long as it is used to annotate something that is binding the protein domain. Should it stay or go?

**Comment by ValWood** [comment]
Let's wait for Penelope.
If there isn't a known example of a Protein that binds (functionally) to the ARID domain, I think it should go..

**Comment by ukemi** [comment]
I just did a quick search and couldn't find one easily, but that doesn't mean one won't show up.

**Comment by ValWood** [comment]
I still vote for removal as it could potentially be used erroneously. It's unlikely to bind to proteins.
The fewer protein binding terms the better.

**Comment by ukemi** [comment]
OK. We will wait to be sure that Penelope wasn't going to use it to annotate a gene product. If not, I will send an obsoletion notice.

**Comment by pgarmiri** [comment]
Apologies for the delayed reply; I was on annual leave until today. Going back to it, I totally see the point made.  I wanted to capture the interaction point but it wouldn't make a lot of sense. The term was requested in error and I agree with its obsoletion.
Thanks

**Comment by ValWood** [comment]
Hi Penelope,

You can capture this information as follows:

GO MF DNA binding 
annotation extension 
relation "occurs at"
and request a SO term for the RBP2 ARID promoter

Like the DNA binding annotation for ace2 here: http://www.pombase.org/spombe/result/SPAC6G10.12c#go-molecular_functionace2

(This should be possible if you are using QuickGO)

Best, 

Val

**Comment by pgarmiri** [comment]
Thank you Val!

That would be a nice way around it. I will try this now.

Best,

Penelope

**Comment by ukemi** [comment]
Dear all,

The proposal has been made to obsolete the following term:

GO:0061813 ARID domain binding

The reason for obsoletion is that the term was requested in error.

All details here:
https://github.com/geneontology/go-ontology/issues/12792


We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete the terms above on November 22, 2016.

*** Unless objections are received by November 22, 2016, we will assume that you agree to this change. ***

Best,

-David Hill

**Comment by ukemi** [comment]
Obsoleted term.
