### ISSUE TITLE
 Free Form Term Genie submission: DNA recombinase disassembly

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12809]
[Term]
id: GO:1990986
name: DNA recombinase disassembly
namespace: biological_process
def: "The disaggregation of a DNA recombinase complex into its constituent components." [GOC:pg, PMID:19540122]
subset: termgenie_unvetted
synonym: "Rad51 nucleoprotein filament disassembly" RELATED []
is_a: GO:0043624 ! cellular protein complex disassembly
created_by: pg
creation_date: 2016-11-18T13:13:56Z

@pgaudet: the TermGenie Free Form submission is not meant to be in active use (email 6/23/16) because not all inferences/parents are saved/created which could lead to loss of information and screwed up parentage. Unfortunately, there is no speedy way to deactivate this functionality otherwise we would have done so. (@cmungall) I'm moving the term request to GH for checking. 

**Please request all non-templatable terms through GH in the future.**

**Comment by tberardini** [comment]
Definition of 'DNA recombinase assembly': The aggregation, arrangement and bonding together of strand exchange proteins (recombinases) into higher order oligomers on single-stranded DNA. 

@pgaudet:Would 'DNA recombinase disassembly' be better defined as:  'The disaggregation of a DNA recombinase complex into its constituent strand exchange proteins (recombinases).'?

**Comment by pgaudet** [comment]
Yes !!!!Sorry about the copy/paste.

Thanks, Pascale

**Comment by tberardini** [comment]
Status for commit #88703: Success

ID: GO:1990986 Label: DNA recombinase disassembly

**Please request all non-templatable terms through GH in the future.**
