### ISSUE TITLE
growth cone regions

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12801]
I would like to see "central region of growth cone” and "peripheral region of growth cone” added to the GO ontology under the parent term "growth cone” (GO:0030426).  The definitions could be "The center of the migrating motile tip of a growing nerve cell axon or dendrite.” and “The non-central region or periphery of the migrating motile tip of a growing nerve cell axon or dendrite."  An example can be found in PMID: 16260607.

**Comment by tberardini** [comment]
I can see these as part_of children of 'growth cone'.  What would you suggest as the is_a parent/s?

    GO:0044463, cell projection part ?

**Comment by slaulederkind** [comment]
If "growth cone" is_a "cell projection part", why would you prefer "x region of growth cone" to be an is_a child of "cell projection part" instead of "growth cone"?

**Comment by slaulederkind** [comment]
Maybe another term "growth cone part" is needed as a part_of child of "growth cone".

**Comment by tberardini** [comment]
@slaulederkind : From the definitions you provided, it read like the two terms you requested described parts of the growth cone.  That would mean that the two terms would be part_of children of growth cone.

cell projection part
--[i] growth cone
----**[p]** central region of growth cone
----**[p]** peripheral region of growth cone

However, each GO term **must** have an is_a parent.  Given the terms in the current ontology, the most appropriate one that I could identify is 'cell projection part'.  

cell projection part
--[i] growth cone
----[p] central region of growth cone
----[p] peripheral region of growth cone
--**[i]** central region of growth cone
--**[i]** peripheral region of growth cone

Yes, we can create 'growth cone part', which would expand the ontology in this way:

cell projection part
--[i] growth cone
----[p] growth cone part
------[i] central region of growth cone
------[i] peripheral region of growth cone
--[i] growth cone part

If it is important to you to be able to group the growth cone parts together as instances under 'growth cone part' as opposed to grouping them together as parts under 'growth cone', then we can create the latter scenario. If not, then I would suggest the former.

**Comment by slaulederkind** [comment]
I like the "growth cone part" grouping.  growth cone filopodium, growth cone lamellipodium, and growth cone membrane could also be moved under "growth cone part".

**Comment by tberardini** [comment]
Ok, that sounds good.  I will create the three terms then in the second structure suggested above and adjust the appropriate relationships for the existing terms you brought up.

Thanks for your feedback.

**Comment by tberardini** [comment]
Added:
 [Term]
+id: GO:0090723
+name: growth cone part
+namespace: cellular_component
+def: "Any constituent part of a growth cone, the migrating motile tip of a growing nerve cell axon or dendrite." [GOC:sl, GOC:tb]
+is_a: GO:0044463 ! cell projection part
+is_a: GO:0097458 ! neuron part
+relationship: part_of GO:0030426 ! growth cone
+created_by: tanyaberardini
+creation_date: 2016-11-18T09:36:19Z
+
+[Term]
+id: GO:0090724
+name: central region of growth cone
+namespace: cellular_component
+def: "The center of the migrating motile tip of a growing nerve cell axon or dendrite." [GOC:sl, PMID:16260607]
+is_a: GO:0090723 ! growth cone part
+created_by: tanyaberardini
+creation_date: 2016-11-18T12:44:25Z
+
+[Term]
+id: GO:0090725
+name: peripheral region of growth cone
+namespace: cellular_component
+def: "The non-central region or periphery of the migrating motile tip of a growing nerve cell axon or dendrite." [GOC:sl, PMID:16260607]
+is_a: GO:0090723 ! growth cone part
+created_by: tanyaberardini
+creation_date: 2016-11-18T12:44:25Z

and adjusted relationships of existing terms to suit the new structure.
