### ISSUE TITLE
cortical dynamic polarity	patch

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12803]
Hi,

We've had a request for a new CC term for part of the cell cortex, for community curation of PMID:23200991 (the synonym below is the originally suggested wording):

name: cortical dynamic polarity patch
def: "A region of the cell cortex that contains a higher concentration of growth polarity factors than the surrounding cortex and that changes position over time. An example is found in fission yeast cells during early mating, in which the GTPase Cdc42 dynamically to discrete zones within the cortex prior to shmoo formation." [GOC:mah, PMID:23200991]
synonym: "dynamic polarity patch at the cell cortex" EXACT []
is_a: GO:0044448 ! cell cortex part

we could also credit Sophie Martin for def and synonym

thanks
m

**Comment by tberardini** [comment]
Does Sophie Martin have a GOC reference (like GOC:mah) ? If not, we need to create one.

**Comment by mah11** [comment]
> Does Sophie Martin have a GOC reference ...?

Um, I don't know; probably not. Where do I look that up these days?

Her full initials are SGM, in case we need to do the creating.

**Comment by tberardini** [comment]
Still figuring out how to create a new curator xref...Since the transition to using a YAML file, I haven't done this. Stay tuned.

**Comment by tberardini** [comment]
Does Sophie Martin have an ORCID?  I will add that into the record.  Highly recommended.

**Comment by tberardini** [comment]
Note to self:

https://github.com/geneontology/go-site/blob/master/metadata/users.yaml
the pull request

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090726
+name: cortical dynamic polarity patch
+namespace: cellular_component
+def: "A region of the cell cortex that contains a higher concentration of growth polarity factors than the surrounding cortex and that changes position over time. An example is found in fission yeast cells during early mating, in which the GTPase Cdc42 dynamically to discrete zones within the cortex prior to shmoo formation." [GOC:mah, PMID:23200991]
+synonym: "dynamic polarity patch at the cell cortex" EXACT [GOC:mah]
+is_a: GO:0044448 ! cell cortex part
+created_by: tanyaberardini
+creation_date: 2016-11-22T16:17:02Z

If you really want to credit Sophie, please reopen and add the requested info and I'll take care of it.

**Comment by mah11** [comment]
Thanks!

I don't think it's critical to add Sophie to the def credits, especially if it's a pain for you - she should get plenty of recognition in PomBase for the annotations she's doing for this and other papers. But she does have an ORCID listed in Canto - 0000-0002-5317-2557 - in case you feel extra motivated, or we have a use for it later.

**Comment by tberardini** [comment]
In that case, I think I'll give it a pass and move on to other issues.  Thanks.
