### ISSUE TITLE
Free Form Term Genie submission: apoptosis in response to oxidative stress

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12806]
[Term]
id: GO:1990985
name: apoptosis in response to oxidative stress
namespace: biological_process
def: "Any biological process that results in permanent cessation of all vital functions of a cell upon exposure to oxidative stress." [GOC:pg, PMID:25950479]
subset: termgenie_unvetted
is_a: GO:0036473 ! cell death in response to oxidative stress
created_by: pg
creation_date: 2016-11-17T14:12:17Z

**Comment by tberardini** [comment]
@pgaudet: the TermGenie Free Form submission is not meant to be in active use (email 6/23/16)  because not all inferences/parents are saved/created which could lead to loss of information and screwed up parentage.  Unfortunately, there is no speedy way to deactivate this functionality otherwise we would have done so.  (@cmungall) I'm moving the term request to GH for checking.  Please request all non-templatable terms through GH in the future. 

@paolaroncaglia: does this term seem ok to you? (apoptosis-related)

Thank you both.

**Comment by paolaroncaglia** [comment]
Hi @pgaudet and @tberardini
apoptosis in response to oxidative stress occurs via the intrinsic pathway (see the def of ‘intrinsic apoptotic signaling pathway’). Also, see the curation manual here: http://wiki.geneontology.org/index.php/Apoptosis_Curation_Manual#GO:0097193_intrinsic_apoptotic_signaling_pathway
So, I’d annotate to the existing term 

id: GO:0008631
name: intrinsic apoptotic signaling pathway in response to oxidative stress
def: "A series of molecular signals in which an intracellular signal is conveyed to trigger the apoptotic death of a cell. The pathway is induced in response to oxidative stress, a state often resulting from exposure to high levels of reactive oxygen species, and ends when the execution phase of apoptosis is triggered." [GOC:ai, GOC:mtg_apoptosis]
synonym: "induction of apoptosis by oxidative stress" RELATED []
synonym: "oxidative stress-induced intrinsic apoptotic signaling pathway" EXACT [GOC:bf]
is_a: GO:0097193 ! intrinsic apoptotic signaling pathway
relationship: part_of GO:0036473 ! cell death in response to oxidative stress

**Comment by tberardini** [comment]
Thank you, @paolaroncaglia .  I will obsolete the term in the TG queue.
