### ISSUE TITLE
biological question re: oxidative stress

### ISSUE THREAD

**Issue by selewis** [geneontology/go-ontology#12807]
As near as I can tell there is no relationship in the ontology between
GO:0034599 cellular response to oxidative stress
and
GO:0006801 superoxide metabolic process

This seems somewhat odd, since metabolizing superoxide is the response to oxidative stress (perhaps I'm wrong, correct me if so)

Is this lack of connection generally the case? That is, no connection between saying there is a response and what the response is?

**Comment by selewis** [comment]
Likewise there is another class that stands alone: 
GO:0072593 reactive oxygen species metabolic process
which bears no relation to 
GO:0006801 superoxide metabolic process

The respective definitions are:
-- The chemical reactions and pathways involving a reactive oxygen species, any molecules or ions formed by the incomplete one-electron reduction of oxygen. They contribute to the microbicidal activity of phagocytes, regulation of signal transduction and gene expression, and the oxidative damage to biopolymers.
-- The chemical reactions and pathways involving superoxide, the superoxide anion O2- (superoxide free radical), or any compound containing this species.

Isn't superoxide a reactive oxygen species?

**Comment by ValWood** [comment]
I think I questioned this one before, and  IIRC,  the answer was that not all superoxide metabolism was necessarily a stress response (or it might not be know). Although if we have no biological examples where it isn't, I prefer the  relationships are added, and then removed if they are disproved.....

**Comment by ValWood** [comment]
scrub previous comment. The relation  sounds correct to me.

**Comment by deustp01** [comment]
From http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18421, superoxide (CHEBI:18421) is_a reactive oxygen species (CHEBI:26523)

**Comment by ValWood** [comment]
for editors, this looks odd:
The chemical reactions and pathways involving superoxide, the superoxide anion O2- (superoxide free radical), or any compound containing this species.

Doesn't being a free radical exclude this "any compound containing this species"?

**Comment by ukemi** [comment]
Superoxide and peroxide are naturally occurring metabolites. So Val's initial thought was correct. I am pretty sure that sometimes ROSs are used in the immune system, which is why we didn't make those relations in the ontology..
PMID:14726604

**Comment by ukemi** [comment]
In my current version of the ontology, superoxide metabolic process is_a ROS metabolic process. So the ontology is following the ChEBI hierarchy correctly. In ChEBI there is no definition for superoxide, but wikipedia implies that it can exist as a compound. Since ChEBI is the authority on chemicals in GO, I think we should leave the definition as is for now. If ChEBI creates a textual definition, we should follow that.

Can I close this one?

**Comment by pgaudet** [comment]
@selewis can we close this ?

**Comment by ValWood** [comment]
Removing myself and closing, I don't think Suzi is going to object.
