### ISSUE TITLE
Update of EC mappings

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12802]
from @hattrill:

> Not sure what your update pipeline for EC mappings is in the GO….. but just to let you know that EC:2.1.1.125 and EC:2.1.1.126 have been deprecated.

**Comment by tberardini** [comment]
@mcourtot , @ukemi, @paolaroncaglia , @dosumis , @cmungall : What does deprecation of an EC number mean?  Is there an established procedure on how to handle terms that have a deprecated EC number in either a definition xref or a synonym xref?  If we don't have one, let's develop an SOP.  When we've done that, I will implement for this set of EC numbers. 

There are several terms that contain these EC numbers.

**Comment by ukemi** [comment]
In the past we have just removed them.

**Comment by hdrabkin** [comment]
Will we get alerts emailed to us so we can remove them from the ontology? I assume "depreciation" means its gone and needs to be removed so we don't get EC2GO that don't really map to anything?
--
Harold

**Comment by tberardini** [comment]
>In the past we have just removed them.

"them" = the dxrefs or the terms themselves?

**Comment by hdrabkin** [comment]
The xrefs: this is like what Chris just did for the EC. X.Y.- xrefs.
Then the EC2GO file will not have a mapping to the GO term
--
Harold

**Comment by ukemi** [comment]
Sorry. I was on my way out. If the activity is thought to no longer exist then we should obsolete the term. I think I remember doing that in the past. If for some reason we still think the activity is a valid molecular function, then we should just remove the cross-reference. You are correct though. If everyone agrees that this is the correct procedure, then we should write up an SOP and put it in the editor's guide. We can either make that as part of this ticket or you can make an new one and assign it to me.

**Comment by tberardini** [comment]
For these particular EC numbers:

**GO:0008469, histone-arginine N-methyltransferase activity** (and children)
>EC 2.1.1.125 - histone-arginine N-methyltransferase
deleted. Now covered by EC 2.1.1.319, type I protein arginine methyltransferase, EC 2.1.1.320, type II protein arginine methyltransferase, EC 2.1.1.321, type III protein arginine methyltransferase and EC 2.1.1.322, type IV protein arginine methyltransferase 

<img width="517" alt="screen shot 2016-11-17 at 5 28 21 pm" src="https://cloud.githubusercontent.com/assets/4998871/20415144/51c0345c-aceb-11e6-84cd-8882e46cc682.png">

**GO:001627, [myelin basic protein]-arginine N-methyltransferase activity**
>EC 2.1.1.126 - [myelin basic protein]-arginine N-methyltransferase
http://www.brenda-enzymes.org/enzyme.php?ecno=2.1.1.125
deleted. Now covered by EC 2.1.1.319, type I protein arginine methyltransferase, EC 2.1.1.320, type II protein arginine methyltransferase, EC 2.1.1.321, type III protein arginine methyltransferase and EC 2.1.1.322, type IV protein arginine methyltransferase 

<img width="624" alt="screen shot 2016-11-17 at 5 29 26 pm" src="https://cloud.githubusercontent.com/assets/4998871/20415166/6d30640a-aceb-11e6-8b8b-913b41a3f4df.png">

There are four different mechanisms for protein arginine methyltransferase.  Looks like we'll need to 
(1) create the four new MF terms (check other existing children of 'protein-arginine N-methyltransferase activity' to be sure)
(2) obsolete the two existing MF terms with the new ones as consider terms

What to do with the children of GO:0008469, histone-arginine N-methyltransferase activity? (see pic)  They've got residue specificity.  Obsolete and recapture the detail in AE? Retain but as direct children of 'protein-arginine N-methyltransferase activity'?

**Comment by mcourtot** [comment]
I had tagged as 'infrastructure' because I wanted to ask (which I subsequently forgot to do ;)) whether there could be an option to deal with those like we do imports? So at least when they get depreciated we could get an alert or remove them automatically?

**Comment by tberardini** [comment]
@hdrabkin @mcourtot @ukemi @paolaroncaglia 

Reiterating the plan above:
(1) create the four new MF terms (check other existing children of 'protein-arginine N-methyltransferase activity' to be sure)
(2) obsolete the two existing MF terms with the new ones as consider terms

This is the part I need help with - please comment.

**What to do with the children of GO:0008469, histone-arginine N-methyltransferase activity? (see pic) They've got residue specificity. Obsolete and recapture the detail in AE? Retain but as direct children of 'protein-arginine N-methyltransferase activity'?**

**Comment by ukemi** [comment]
Coming back to this now and having second thoughts. Although it would be ideal to capture the histone terms with annotation extensions or in Noctua, I'm not sure we are ready for that yet. I remember that there was some discussion when we created these terms and the curator argument was similar to the one for the retention of the modified protein terms, they are too important not to have as instantiated terms in the ontology. So I would vote that for now we keep them, perhaps under GO:0016274, which we would retain. 

So this might be a case where we keep the terms for the time being and we simply remove that EC xrefs as Harold originally suggested.

**Comment by tberardini** [comment]
I could keep all the existing terms, remove the deprecated EC xrefs **AND** add these four new MF terms:

EC 2.1.1.319, type I protein arginine methyltransferase
EC 2.1.1.320, type II protein arginine methyltransferase
EC 2.1.1.321, type III protein arginine methyltransferase
EC 2.1.1.322, type IV protein arginine methyltransferase 

How does that sound?

**Comment by ukemi** [comment]
Works for me.

**Comment by paolaroncaglia** [comment]
Me too, thanks @tberardini

**Comment by hdrabkin** [comment]
Yes;

**Comment by tberardini** [comment]
Turns out that all the individual types of protein arginine methyltransferases were already in GO.
![protein_methyltransferases](https://cloud.githubusercontent.com/assets/4998871/20577813/ee0bd26c-b178-11e6-9865-47e2bc7896bf.png)

I updated EC crossreferences, added synonyms and comments where appropriate, and removed the deprecated EC xrefs from the terms that had them.
