### ISSUE TITLE
Ghost relations in the obo-file

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12808]
@tberardini Since you are on duty, you should be aware.
@cmungall 

It looks like the problem of having ghost relations in the obo file when saving from obo-edit is back. 
Things still work fine using protege.
 [Typedef]
+id: RO:0000057
+namespace: external
+xref: RO:0000057
+
+[Typedef]
+id: RO:0002233
+namespace: external
+xref: RO:0002233
+
+[Typedef]
+id: RO:0002234
+namespace: external
+xref: RO:0002234
+
+[Typedef]
+id: RO:0002313
+namespace: external
+xref: RO:0002313
+
+[Typedef]
+id: RO:0002332
+namespace: external
+xref: RO:0002332
+
+[Typedef]
+id: RO:0002340
+namespace: external
+xref: RO:0002340
+
+[Typedef]
+id: RO:0002345
+namespace: external
+xref: RO:0002345
+
+[Typedef]

**Comment by cmungall** [comment]
I think this is to do with my chevi import changes

**Comment by tberardini** [comment]
Thanks for the heads up.  I cleaned them out before my commit.

**Comment by paolaroncaglia** [comment]
Yes - I had the same problem and deleted RO stanzas by hand. (r37117)

**Comment by paolaroncaglia** [comment]
@mcourtot , @ukemi 
Added editors-discussion label as I'm hoping this would be quick to agree on and fix similarly to the previous instance of ghost RO stanzas. That is, if it isn't already fixed by Thu. Thanks.

**Comment by mcourtot** [comment]
Wasn't the fix to just delete them as they show up? 
Unfortunately I think the bigger issue is continuing editing in OBO edit which is not supported/maintained anymore.

**Comment by paolaroncaglia** [comment]
As discussed in person with @mcourtot , she was referring to post-merge inferences that we need to delete. These RO stanzas are a different issue and I kind of remember they should be easy to fix, but I couldn't find details among my emails, so I'll rely on others' memory on how to do that.

**Comment by mcourtot** [comment]
I think it was the same fix: they show up in the header of the OBO file and we had manually deleted them from there. I found an email from David Hill on November 11 2015 with subject 'redundant relation' if that helps.

**Comment by ukemi** [comment]
I think somehow they are sneaking in via biochebi. See the comment above. Obo edit is still far easier to use for some editing tasks. Although not a perfect solution because it is error-prone, for now just go in and delete them from the file using a text editor once you have saved from obo edit.

**Comment by mcourtot** [comment]
AI: editors who use OBO edit need to remove those relations manually

**Comment by ukemi** [comment]
Just as a heads-up, it looks like there are more than just relations being added to the file now. Yesterday there were several relationships also appearing as asserted when saving out of OBO-Edit. All but one were good. To get rid of the bad ones that you spot, you can simply delete them in OBO-edit before the save. Should we just make it SOP to delete any of these as well?

**Comment by ukemi** [comment]
Now even more are being added:

 [Typedef]
+id: directly_inhibits
+name: directly inhibits
+namespace: external
+xref: RO:0002408
+is_a: directly_negatively_regulates ! directly negatively regulates

 [Typedef]
+id: directly_activates
+name: directly activates
+namespace: external
+xref: RO:0002406
+is_a: directly_positively_regulates ! directly positively regulates

**Comment by dosumis** [comment]
This is fallout from my recent edits.  Fine to keep them in.  The’re not wrong and shouldn’t cause any trouble.

**Comment by cmungall** [comment]
```
$ svn commit -m 'Add shorthand to chebi imports. See https://github.com/geneontology/go-ontology/issues/12808' Makefile 
Sending        Makefile
Transmitting file data .
Committed revision 37773.
```

diff:

```
 chebi_import.owl: $(IMPORT_SEED)
-       owltools --use-catalog $< bio-chebi.owl --add-imports-from-supports --extract-module -s $(OBO)/go/extensions/bio-chebi.owl -c  --make-subset-by-properties -n $(CHEBIRELS) // --remove-annotation-assertions -r -l  --set-ontology-id $(OBO)/go/extensions/$@ -o $@
+       owltools --use-catalog $< bio-chebi.owl --add-imports-from-supports --extract-module -s $(OBO)/go/extensions/bio-chebi.owl -c  --make-subset-by-properties -n $(CHEBIRELS) // --remove-annotation-assertions -r -l --add-obo-shorthand-to-properties --set-ontology-id $(OBO)/go/extensions/$@ -o $@
```

hopefully this fixes it

**Comment by ukemi** [comment]
#12896

**Comment by ukemi** [comment]
This ticket is no longer relevant.
