### ISSUE TITLE
some synonyms for "epithelial cilium movement" terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#12804]
Hi @paolaroncaglia & @JohnVanDam

I was cleaning out my inbox and realized I had one last lingering cilia issue. I think it should be pretty simple though.

**Part 1.**
We have previously discussed the idea of having a term for something like "cilium movement involved in fluid flow", to be parallel to the term "cilium movement involved in cell motility". However, I recently realized that we already have a term that means "cilium movement involved in fluid flow":

epithelial cilium movement (GO:0003351)
Def: The directed, self-propelled movement of a cilium of an epithelial cell. This movement is usually coordinated between many epithelial cells, and serves to move fluid.

**=> Solution:** Could add "cilium movement involved in fluid flow" as a synonym for this existing term.

**Part 2.**
Below this term is a child term called "epithelial cilium movement involved in determination of left/right asymmetry" (GO:0060287). 

I was concerned about this term since I wasn't sure if the ciliated node cells (in mouse/mammals) are epithelial, so I asked David Hill this question: 

<pre>
From: Karen Christie <Karen.Christie@jax.org>
Date: Thursday, October 20, 2016 at 1:48 PM
To: David Hill <david.hill@jax.org>
Subject: question about node

Hi David,

I have a question for you. Would you consider the cells of the node to be epithelial?

Basically, there is a GO term that has been bothering me for a while, and while Paola is finishing
 the ciliary work up seems like the time to see if this is OK or something that needs to be fixed.

The term is "epithelial cilium movement involved in determination of left/right asymmetry”
Def: The movement of cilia of epithelial cells resulting in the transport of signals which determine 
asymmetry in an organism's body plan with respect to the left and right halves.

The cilia that I think of as being associated with "determination of left/right asymmetry” are the 
ones in the node (in mouse; in zebrafish the corresponding structure is called the Kuipfer’s 
vesicle). So, I was wondering if the cells of the node are considered epithelial. If not, this term 
is clearly not right.
</pre>

Here is his response:
<pre>
Interesting question that I just discussed with Terry for a while. We think not all node cells are, 
but the ciliated ones that cause the leftward flow are:

PMID:18629866

-David
</pre>

A quick search to see if Kuppfer's vesicle cilia in zebrafish are also epithelial finds Essner et al. 
2005  PMID: 15716348, which refers to the ciliated epithelium within the Kuppfer's vesicle, so this 
seems to be pretty general.

So, I think the term is fine, but I'd like to propose some additional synonyms since I didn't feel 
comfortable using this term before, not realizing that ciliated node cells are epithelial.

**=> Proposed new synonyms:**
* nodal cilium movement involved in determination of left/right asymmetry
* Kuppfer's vesicle cilium movement involved in determination of left/right asymmetry

thanks,

Karen

**Comment by paolaroncaglia** [comment]
Hi @krchristie ,
Thanks, all done now.
