### ISSUE TITLE
microtubule tip terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12816]
Community curation
https://curation.pombase.org/pombe/curs/8fb498d6aad39666/ro

mitotic spindle astral microtubule tip/end
post-anaphase microtubule tip/end

parents

![post compose](https://cloud.githubusercontent.com/assets/7359272/20533150/7c0f6592-b0d4-11e6-979d-0f1edcc292d4.jpg)

Ref PMID:11007487
Def standard

Happy to post compose if there is a way...

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

Looks like you could use the TG template “part_of_cell_component” (Description: cell components part of other cell components):

mitotic spindle astral microtubule tip/end = is_a microtubule end, part_of mitotic spindle astral microtubule

post-anaphase microtubule tip/end = is_a microtubule end, part_of post-anaphase microtubule array

You may want to refine the term names and synonyms to your liking (just make sure you leave the default name as an exact synonym please). But let me know if I’m missing anything.

**Comment by ValWood** [comment]
I think there is something wrong with this template

I specified 
part mitotic spindle astral microtubule 
whole microtubule end
(which seemsed correct to me)

but the def was munged to

Any mitotic spindle astral microtubule that is part of a microtubule end.

i fixed it to
Any microtubule end that is part of a mitotic spindle astral microtubule.

**Comment by ValWood** [comment]
I just realised I misunderstood the instructions.

I thought this was to do with whether the parent term was is_a or part_of

you will need to  obsolete this term sorry!

**Comment by paolaroncaglia** [comment]
@ValWood 
Done: (obsolete) ID: GO:1905718 Label: obsolete mitotic spindle astral microtubule end

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
May I close this one, please? Let me know if you need any help with the TG template (BTW I noticed that @mah11 used the same template yesterday, so maybe you could ask her if it's urgent and I'm not around). Thanks.

**Comment by ValWood** [comment]
I requested it again, correctly this time I think!
