### ISSUE TITLE
Proposed pattern for pigment accumulation

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12810]
currently no DP:

```
[Term]
id: GO:0043476
name: pigment accumulation
namespace: biological_process
def: "The aggregation of coloring matter in a particular location in an organism, tissue or cell, occurring in response to some external stimulus." [GOC:jl]
synonym: "pigment accumulation in response to external stimulus" EXACT []
is_a: GO:0009605  ! response to external stimulus
is_a: GO:0043473  ! pigmentation
```

some child terms:

```
    is_a GO:0043476 ! pigment accumulation
     is_a GO:0043478 ! pigment accumulation in response to UV light
      is_a GO:0043479 ! pigment accumulation in tissues in response to UV light 
       is_a GO:0043481 ! anthocyanin accumulation in tissues in response to UV light
```

We may want to add more, e.g. for bacterial 'sunscreens' like Scytonemin; see http://www.nature.com/articles/ncomms10373

I think for this we first need a generic chemical accumulation DP. Would this be identical to positive regulation of X levels?

To capture the context, we may could either use the CHEBI role (see comments here https://github.com/ebi-chebi/ChEBI/issues/3209), or, as would be my preference, capture the process directly with GO.

We currently have light absorption, but this is for a cell:

```
[Term]
id: GO:0016037
name: light absorption
namespace: biological_process
def: "The reception of a photon by a cell." [GOC:go_curators]
subset: gosubset_prok  ! Prokaryotic GO subset
synonym: "absorption of light" EXACT [GOC:curators]
is_a: GO:0044763  ! single-organism cellular process
relationship: part_of GO:0009583 ! detection of light stimulus
```

**Comment by pgaudet** [comment]
@krchristie I think you were working on something similar, can you take this one?

**Comment by pgaudet** [comment]
Seems like there are too few terms to be worth it to create a DP
