### ISSUE TITLE
GO:0043946; opposite definition

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#12814]
Hi,

I just came across this term that has a definition for negative regulation while it is supposed to be a positive one.

GO:0043946
Name 	positive regulation of catalytic activity in other organism involved in symbiotic interaction
Ontology 	Biological Process
Definition 	Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of enzyme activity in a second organism, where the two organisms are in a symbiotic interaction. 

Could you please look into updating it?

Thanks,

Penelope

**Comment by paolaroncaglia** [comment]
Hi @pgarmiri ,
Thanks for reporting that. Now fixed.
