### ISSUE TITLE
Merge directly_activates/inhibits relations into directly_positively/negatively_regulates.

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12811]
Following discussion in LA: given the amount of confusion and discussion there was around distinction between directly_activates and directly_positively_regulates, I think we should collapse the distinction in both positive and negative branches.

![image](https://cloud.githubusercontent.com/assets/112839/20486519/fd092814-aff7-11e6-9960-e955d4e889aa.png)

As there are some circumstances where activation/inhibition just sounds wrong, I suggest we stick with the more neutral directly_positively/negatively regulates in all all situations in GO (ontology, LEGO, AE).    We can make directly_activates/inhibits into narrow synonyms. 

CC  @vanaukenk - can you join an editor's meeting discussion of this?  

(See https://github.com/geneontology/annotation_extensions/issues/70#issuecomment-261958905)

**Comment by dosumis** [comment]
Editor's meeting discussion: All agreed that we should go ahead with the merge.

- [ ] Change in Noctua (currently hard coded!)  
- [ ] Make separate ticket for updating existing noctua models
- [ ] Change in annotation extensions: DOS  # 
- [ ] Change all usage in GO - ontology
- [ ] Merge relations in RO.

CC @thomaspd @vanaukenk .

**Comment by kltm** [comment]
I'm not clear on the action desired here. Go ahead and make a separate ticket in the noctua tracker.

**Comment by dosumis** [comment]
> I'm not clear on the action desired here. Go ahead and make a separate ticket in the noctua tracker.

Done: https://github.com/geneontology/noctua/issues/392

**Comment by dosumis** [comment]
>  Make separate ticket for updating existing noctua models @ukemi

@ukemi - where should this ticket live?

**Comment by ukemi** [comment]
Minerva? This is a general issue as the ontologies change; terms go obsolete etc.

**Comment by dosumis** [comment]
I guess we need something the flags when a relation or class used in a model becomes obsolete.  Perhaps make a ticket for this general issue first, and then test by making these relations obsolete in RO?

**Comment by kltm** [comment]
@ukemi You might actually want to think about the noctua-models repo itself--it's not an issue in the software, but rather a policy change that affects the models.

**Comment by ukemi** [comment]
@kltm 
Yes. I see what you mean. What we want is something that would check the models and then let curators know that there are secondary identifiers, obsolete terms etc in their models. But what would happen for example if we have an obsolete term or relation in a model and then tried to load the model. Would it work?

**Comment by ukemi** [comment]
So maybe @dosumis work is the test case. I know that I have used directly_activates in a lot of my models.

**Comment by ukemi** [comment]
@thomaspd @vanaukenk are you both ok with this plan, particularly the choice of relation names for the merged terms?

**Comment by ukemi** [comment]
Hi @balhoff. Just making sure that you are looped in on this discussion.

**Comment by kltm** [comment]
Let me paint a picture of the future. In the worst case, an ID that is obsoleted or falls out of the GPI files should revert to basically just an unknown floating ID in Noctua--one shouldn't be able to input them, but it shouldn't cause a panic either. However, there should be periodic sweeps of the models done in Jenkins that will create reports for the curators about what models they've worked on that contain obsolete or bad ids, including relations and the like.
For things like an obsoleted relation, that may have an effect on the reasoning (I'm not sure if they're turned into singetons or if they maintain their connections), but there should be able warning.
If Noctua/Minerva is not able to support this, that's a bug.

**Comment by ukemi** [comment]
Thanks @kltm. This all makes sense to me. From our (annotators) perspective, I think we would like to see this all roll in to a QC-type report similar to our gaf validation reports. In fact at some point all the checks should just be done on the models.

**Comment by vanaukenk** [comment]
@dosumis and @ukemi 
I am okay with this change.  I've also used the directly_activates and directly_inhibits relation in a lot of my models, so yes, having models and specific issues like this flagged in some kind of regular QC report would be very helpful.

**Comment by cmungall** [comment]
+1 to @kltm's comments

**Comment by dosumis** [comment]
So I should make these obsolete in RO before noctua models are fixed and this will trigger flagging for update?

**Comment by kltm** [comment]
At some point in the future, yes. As of right now, it would require a manual query and fix to models.

**Comment by dosumis** [comment]
Note from editor's call discussion: Delay merge in RO until we have a plan to update LEGO models.  That way existing models will still work.

**Comment by dosumis** [comment]
From editor's meeting discussion:  plan to update via SPARQL update.  But needs to be when models not open.

**Comment by pgaudet** [comment]
@cmungall Should this be moved to the Relations Ontology tracker ? 

@lpalbou Can you find out if 'directly_activates' and 'directly_inhibits' are being used in GO-CAM models ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@cmungall Should this be moved to the Relations Ontology tracker ?

@lpalbou Can you find out if 'directly_activates' and 'directly_inhibits' are being used in GO-CAM models ?

Thanks, Pascale

**Comment by cmungall** [comment]
yes

**Comment by pgaudet** [comment]
@vanaukenk I think this is resolved and this ticket can be closed ?
