### ISSUE TITLE
Duplicated definitions for post-spliceosomal complexes

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12819]
Hi @mah11 - same duplication for the terms below. Can you help?

[Term]
id: GO:0071020
name: post-spliceosomal complex
namespace: cellular_component
def: "A spliceosomal complex that is formed following the second splicing event and contains the spliced product, the excised intron, and three snRNPs, including U5." [GOC:krc, GOC:mah, ISBN:0879695897, ISBN:0879697393]

[Term]
id: GO:0071021
name: U2-type post-spliceosomal complex

[Term]
id: GO:0071022
name: U12-type post-spliceosomal complex

**Comment by mah11** [comment]
Back when I worked on these terms, I pretty much followed advice from @krchristie, so it won't be a bad idea to have her take a look at the defs too. That said, it does seem as though adding to the text defs based on the has_part links should work:

GO:0071021 "A spliceosomal complex that is formed following the second splicing event and contains the spliced product, the excised intron, and three snRNPs, U5, U2 and U6."

GO:0071022 "A spliceosomal complex that is formed following the second splicing event and contains the spliced product, the excised intron, and three snRNPs, U5, U12 and U6atac."

**Comment by krchristie** [comment]
@mah11 

Your proposed expanded definitions for the two child terms sounds perfect to me.

**Comment by mcourtot** [comment]
Committed revision 37219.
