### ISSUE TITLE
Duplicated definitions for terms

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12818]
Hi @mah11,

We have 2 terms with duplicated definitions - could you suggest suitable modification? I'd tend to say in the second one the part "found in the walls of ascospores" should be replaced by "found in the walls of fungi" but thought I'd check with you.

id: GO:0034413
name: ascospore wall (1->3)-beta-D-glucan biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of (1->3)-beta-D-glucans, compounds composed of glucose residues linked by (1->3)-beta-D-glucosidic bonds, found in the walls of ascospores." [GOC:mah]

and 

[Term]
id: GO:0071970
name: fungal-type cell wall (1->3)-beta-D-glucan biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of (1->3)-beta-D-glucans, compounds composed of glucose residues linked by (1->3)-beta-D-glucosidic bonds, found in the walls of ascospores." [GOC:mah]

**Comment by mah11** [comment]
yes, changing the GO:0071970 def to end with "found in fungal cell walls" or similar will do nicely

**Comment by mcourtot** [comment]
Done revision 37198.
