### ISSUE TITLE
SGD duplicated definitions

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12817]
Hi @krchristie,

We have 2 SGD terms with duplicated definitions in the file - could you take a look and suggest changes? They both seem correct though under specified.

[Term]
id: GO:1990526
name: Ste12p-Dig1p-Dig2p complex
namespace: cellular_component
def: "A multiprotein complex that is involved in the transcription regulation of mating genes in the yeast S. cerevisiae." [GOC:rb, PMID:16782869]
is_a: GO:0043234 ! protein complex
relationship: capable_of_part_of GO:0007532 ! regulation of mating-type specific transcription, DNA-templated
created_by: rb
creation_date: 2014-11-05T22:49:32Z

[Term]
id: GO:1990527
name: Tec1p-Ste12p-Dig1p complex
namespace: cellular_component
def: "A multiprotein complex that is involved in the transcription regulation of mating genes in the yeast S. cerevisiae." [GOC:rb, PMID:16782869]
is_a: GO:0043234 ! protein complex
relationship: capable_of_part_of GO:0007532 ! regulation of mating-type specific transcription, DNA-templated
created_by: rb
creation_date: 2014-11-05T22:55:17Z

**Comment by mcourtot** [comment]
Sorry - @paolaroncaglia just mentioned @krchristie is not at SGD anymore (I updated the users.yaml file accordingly) - @srengel can you help?

**Comment by srengel** [comment]
yep will take a look...

**Comment by srengel** [comment]
ok, from the PMID listed in the definition 16782869, we can change the def for 

id: GO:1990527
name: Tec1p-Ste12p-Dig1p complex

to this:
A multiprotein complex that is involved in the transcriptional regulation of primarily filamentation genes, but also mating genes, in the yeast S. cerevisiae.

**Comment by srengel** [comment]
p.s., and just leave the def for GO:1990526 as is.  that will solve the duplicated def issue.

**Comment by mcourtot** [comment]
Committed revision 37220.
