### ISSUE TITLE
Duplicated definitions/terms? transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12821]
Hi @krchristie 

Can you help update the definitions below so they're not identical? I am wondering if those 2 terms should actually exist as separate entities, as they both seem to pertain to recruitment of TFIIIB to promoter.

Thanks!

[Term]
id: GO:0001005
name: transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting
namespace: molecular_function
def: "The function of binding to a specific DNA sequence motif in a type 1 RNA polymerase III (Pol III) promoter in order to recruit the Pol III recruiting factor TFIIIB to the promoter. For type 1 Pol III promoters, this requires both TFIIIA and TFIIIC." [GOC:txnOH, PMID:12381659]
comment: This represents TFIIIA.
synonym: "RNA polymerase III type 1 promoter sequence-specific DNA binding TFIIIB recruiting transcription factor activity" EXACT []
synonym: "TFIIIA activity" RELATED []
synonym: "TFIIIC-type activity" RELATED []
is_a: GO:0001004 ! transcription factor activity, RNA polymerase III promoter sequence-specific binding, TFIIIB recruiting
relationship: has_part GO:0001002 ! RNA polymerase III type 1 promoter sequence-specific DNA binding
relationship: part_of GO:0000999 ! RNA polymerase III type 1 promoter transcriptional preinitiation complex assembly
created_by: kchris
creation_date: 2010-08-18T05:57:29Z

and 

[Term]
id: GO:0001157
name: transcription factor activity, RNA polymerase III type 1 promoter TFIIIB
namespace: molecular_function
def: "The function of binding to a specific DNA sequence motif in a type 1 RNA polymerase III (Pol III) promoter in order to recruit the Pol III recruiting factor TFIIIB to the promoter. For type 1 Pol III promoters, this requires both TFIIIA and TFIIIC." [GOC:txnOH, PMID:12381659]
comment: This represents TFIIIA.
synonym: "RNA polymerase III type 1 promoter TFIIIB recruiting transcription factor activity" EXACT []
synonym: "TFIIIC-type activity" RELATED []
is_a: GO:0001153 ! transcription factor activity, RNA polymerase III transcription factor recruiting
relationship: has_part GO:0001154 ! TFIIIB-class transcription factor binding
relationship: has_part GO:0001155 ! TFIIIA-class transcription factor binding
relationship: part_of GO:0000999 ! RNA polymerase III type 1 promoter transcriptional preinitiation complex assembly
created_by: kchris
creation_date: 2011-01-27T05:27:28Z

**Comment by krchristie** [comment]
Hi Melanie,

It looks to me like GO:0001157 is a mistake. It doesn't have any annotations either.

Possibly it could just be obsoleted.

-Karen

**Comment by mcourtot** [comment]
Thanks for the feedback @krchristie ! Would it work to merge the terms? It is a bit easier than obsoleting if the 2 terms represent the same thing.

**Comment by krchristie** [comment]
It isn't really clear what GO:0001157 was intended to represent, but I don't see how it would be a problem to merge the terms since there aren't any annotations to GO:0001157.

**Comment by mcourtot** [comment]
Committed revision 37246.
