### ISSUE TITLE
Duplicated definition: sphingolipid biosynthetic process

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12823]
Hi @mah11 
Can you check proposed update. I'd like to update the definition of GO:0090159, sphingolipid biosynthesis involved in endoplasmic reticulum membrane organization, to "The chemical reactions and pathways resulting in the formation of sphingolipids during endoplasmic reticulum membrane organization" I'm not quite sure about the "during" - what do you think?

Term below have same definition:

[Term]
id: GO:0030148
name: sphingolipid biosynthetic process
def: "The chemical reactions and pathways resulting in the formation of sphingolipids, any of a class of lipids containing the long-chain amine diol sphingosine or a closely related base (a sphingoid)." [GOC:mah, ISBN:0198506732]
is_a: GO:0046467 ! membrane lipid biosynthetic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_output CHEBI:26739 ! sphingolipid

[Term]
id: GO:0090159
name: sphingolipid biosynthesis involved in endoplasmic reticulum membrane organization
def: "The chemical reactions and pathways resulting in the formation of sphingolipids, any of a class of lipids containing the long-chain amine diol sphingosine or a closely related base (a sphingoid)." [GOC:ascb_2009, GOC:dph, GOC:tb]
intersection_of: GO:0030148 ! sphingolipid biosynthetic process
intersection_of: part_of GO:0090158 ! endoplasmic reticulum membrane organization
relationship: part_of GO:0090158 ! endoplasmic reticulum membrane organization

**Comment by mah11** [comment]
I suspect @ukemi would plump for using "that contributes to" instead of "during" in the GO:0090159 revised def. I don't really have anything else to contribute; I only did GO:0030138, and that one was essentially a scruffy manual imitation of what we now do via the TG metabolism template. I don't know anything about the ER-specific term other than what it says.

**Comment by mcourtot** [comment]
Committed revision 37218.
