### ISSUE TITLE
mitochondrion distribution - always intracellular?

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12828]
![image](https://cloud.githubusercontent.com/assets/112839/20608994/2b8c20cc-b27f-11e6-98ff-401204f1d88f.png)

Due to newly added property chain:

![image](https://cloud.githubusercontent.com/assets/112839/20609018/648eff7a-b27f-11e6-9253-40e63b54ea87.png)

temp fix: deleted equivalentClass axiom on ‘intracellular distribution of mitochondria'

Question: is this class structure really necessary

![image](https://cloud.githubusercontent.com/assets/112839/20608984/15b34f82-b27f-11e6-9507-921f8836bcfe.png)

rdfs:label "mitochondrion distribution"^^xsd:string
definition "Any process that establishes the spatial arrangement of mitochondria between and within cells."^^xsd:string

rdfs:label "intracellular distribution of mitochondria"^^xsd:string
definition "Any process that establishes the spatial arrangement of mitochondria within the cell."^^xsd:string

rdfs:label "mitochondrion inheritance"^^xsd:string
definition "The distribution of mitochondria, including the mitochondrial genome, into daughter cells after mitosis or meiosis, mediated by interactions between mitochondria and the cytoskeleton."^^xsd:string

The definition of mitochondrial inheritance seems odd.  As the distribution happens before cytokinesis, it seems fair to say it is also intracellular. 

Do we need both terms then?

Looking at direct annotations:

![image](https://cloud.githubusercontent.com/assets/112839/20609064/fc9f27c2-b27f-11e6-8656-f0cbc9127ecb.png)

The only convincing multicellular case I've come up with is for distribution to the oocyte from nurse cells in Drosophila.  Maybe OK to fudge this one in order to get an extremely useful property chain?

Suggested solution = merge intracellular & generic mitochondrial distrib, + make inheritance term a subclass.

**Comment by ValWood** [comment]
I have long had a problem with this:
Some historical tickets:

https://github.com/geneontology/go-ontology/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22mitochondrion%20distribution%22%20is%3Aclosed%20

Maybe this one is the most relevant?
https://github.com/geneontology/go-ontology/issues/6030

but now this doesn't make sense to me. If mitochondrial inheritance is  not intracellular distribution, then logically chromosome segregation is not an intracellular process either....

I think the problem  arises fundamentally  from classifying "inheritance" as "organization".
https://github.com/geneontology/go-ontology/issues/11387

To me "organization" is  an intrinsic to the structure not its location.

Even though mitochondrial are  "complicated tubular networks"  https://github.com/geneontology/go-ontology/issues/11387
I believe that when cell division occurs it does not just divide some  big amorphous mitochondrial structure, the mitochondria have already undergone fission (which is organisation).

![mitochondrial fission](https://cloud.githubusercontent.com/assets/7359272/20617417/f480dbb0-b2e0-11e6-84bb-e5ca5bda9dc1.jpg)

**Comment by dosumis** [comment]
Hi Val,

Apologies if my initial post was unclear

>  If mitochondrial inheritance is not intracellular distribution, then logically chromosome segregation is not an intracellular process either....

I think we’re agreeing - I’m saying that mitochondrial inheritance *is* (a special case of) intracellular distribution: the intracellular distribution prior to cytokinesis.  It’s just not classified that way right now.  

> I think the problem arises fundamentally from classifying "inheritance" as "organization".

Agree that could be dodgy.  Think this is outside the scope of the ticket though.

Proposal is to change this:

![image](https://cloud.githubusercontent.com/assets/112839/20608984/15b34f82-b27f-11e6-9507-921f8836bcfe.png)

To 
label "mitochondrion distribution"
definition "Any process that establishes the spatial arrangement of mitochondria within a cell."

label "mitochondrion inheritance"
definition "The distribution of mitochondria, including the mitochondrial genome, into daughter cells immediately prior to cytokinesis, mediated by interactions between mitochondria and the cytoskeleton.  This determines the distribution in daughter cells."
is_a: mitochondrion distribution

The Drosophila nurse-cell -> oocyte case is a bigger problem for this proposal though.

**Comment by ValWood** [comment]
OK, what you say here sounds correct anyway, however we got there....I think I misunderstood the  problem, but I was agreeing.

**Comment by ValWood** [comment]
So the action here is just to merge 
mitochondrion distribution
and 
intracellular distribution of mitochondria
@dosumis  agreed.

If so this seems quick? @pgaudet

**Comment by ValWood** [comment]
Was meant  to be
@dosumis  Agreed?

**Comment by ukemi** [comment]
What about in a syncitium, like a muscle?

**Comment by ValWood** [comment]
Good point. can probably close then?

**Comment by ukemi** [comment]
I think so. IIRC the mitochondria in cardiac and striated muscle are highly organized in the syncitium to allow for a good supply of ATP used in contraction. PMID:22899654

**Comment by ValWood** [comment]
I still think this is odd
GO:0048312    JSON
intracellular distribution of mitochondria
Definition (GO:0048312 GONUTS page)
Any process that establishes the spatial arrangement of mitochondria within the cell.

seems the same as
GO:0048311    JSON
mitochondrion distribution
Biological Process

Definition (GO:0048311 GONUTS page)
Any process that establishes the spatial arrangement of mitochondria between and within cells.

and 
GO:0051646    JSON
mitochondrion localization
Biological Process

Definition (GO:0051646 GONUTS page)
Any process in which a mitochondrion or mitochondria are transported to, and/or maintained in, a specific location within the cell.

(Is spatial distribution different from localization).

Anyway will close as there is a newer ticket related to this.
