### ISSUE TITLE
merge GO:0090450 and GO:1990003 ?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12825]
They have duplicate definitions.

[Term]
id: GO:1990003
name: IDP phosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: IDP + H2O = IMP + phosphate." [PMID:20385596]
xref: EC:3.1.3
is_a: GO:0098519 ! nucleotide phosphatase activity, acting on free nucleotides
created_by: jl
creation_date: 2012-12-05T16:46:52Z

[Term]
id: GO:0090450
name: inosine-diphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: IDP + H2O = IMP + phosphate." [PMID:22849572]
synonym: "IDPase activity" EXACT []
synonym: "inosine diphosphatase activity" EXACT []
is_a: GO:0017110 ! nucleoside-diphosphatase activity
created_by: tanyaberardini
creation_date: 2012-09-12T08:30:52Z

**Comment by mcourtot** [comment]
They look the same to me too. Is there a difference due to the restriction? One is a "is_a: GO:0098519 ! nucleotide phosphatase activity, **acting on free nucleotides**" whereas the other one is the general case.
GO:1990003 has no annotations.

**Comment by ValWood** [comment]
Hi Melanie,

They should both be "free nucleotides". This clause is host to prevent people using catalytic activities like this from being used to annotate nucleotides/sides in polymers 
(these can also have F-P links to the appropriate small-molecule metabolic process).

But, they might be intended to be different (at least they have different parentage


![both](https://cloud.githubusercontent.com/assets/7359272/20593542/c5f09cb0-b22a-11e6-8a99-81918c8d7579.jpg)

perhaps Jane's term was meant to  refer to a nucleoside?

**Comment by paolaroncaglia** [comment]
Hi @tberardini , @mcourtot and @ValWood 
Regardless of whether Jane's term might have been intended for nucleosides or nucleotides, since her term has no annotations and the other term should also be for free nucleotides, I'd say they should be merged accordingly. GO:0090450 doesn't have any mappings and only 2 annotations, one of which is TAIR, so @tberardini you could check if adding the 'free nucleotide' clause would break anything. Therefore I'm assigning this ticket to you :-)

**Comment by ukemi** [comment]
According to the assay in PMID:22849572 it is the free nucleotide.

**Comment by tberardini** [comment]
Ok, the plan is to merge GO:0090450 (Tanya) into GO:1990003 (Jane), retaining the 'free nucleotide' parentage. Barring objections, I'll do this tomorrow.

**Comment by tberardini** [comment]
Merged the terms but upon svn diff got a HUGE diff so I'm going to back the changes out and try again from a fresh copy of GO.

**Comment by ukemi** [comment]
Hmm. I wonder if this has anything to do with the release failure. Lots of inferred relations were stripped out of the file when I did a commit yesterday. I have looked at my diff and I didn't see anything weird, but it seemed to have downstream effects. All I did was change a definition.

**Comment by tberardini** [comment]
OK, same result.  TONS of relations are being added.  From this morning's [go-ontology] Inference Changes Report:

Report for: 2016-11-29
37305 dph ADD: 24 DEL: 1607 terms: 1277

I think I will go ahead and commit my file, which should restore the inferred relations that were somehow stripped with David's commit yesterday.

**Comment by tberardini** [comment]
>Committed revision 37407.

Fingers crossed.  Let's see if there's any fallout.

**Comment by tberardini** [comment]
No Jenkins check failure.  Closing.
