### ISSUE TITLE
Allow named equivalent classes when those one or both of those classes is outside GO

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12827]
It would be very useful to be able to locally assert equivalence between terms from imported ontologies, e.g: ChEBI:protein equivalentTo PRO:Protein.  It may also occasionally be useful to assert equivalence between an imported term and a GO term (cell?).  AFAIK, doing this now would break the Jenkins build.  But I see no reason not to restrict the check for named equivalent classes to checking for equivalence between GO terms.

**Comment by ukemi** [comment]
I thought we had done this with 'cell' long ago at a meeting in Berkeley.

**Comment by cmungall** [comment]
We actually don't have an equivalence check at the moment, so you can go ahead and add these (although I prefer the 2 ontologies come to an agreement and one should obsolete)

**Comment by balhoff** [comment]
It seems we can close this.
