### ISSUE TITLE
NTR: GO:1990896 protein localization to cell cortex of cell tip

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12824]
should have "intracellular protein transport" parent

**Comment by ValWood** [comment]
actually, this one.....
GO:0072697 protein localization to cell cortex

**Comment by paolaroncaglia** [comment]
Hi @ValWood,
Trying to get this straight:
Are you asking to add the link
GO:0072697 protein localization to cell cortex is_a intracellular protein transport?
Looks weird to me as protein transport is_a protein localization.

**Comment by ValWood** [comment]
You are quite right!
I need
 protein localization to cell cortex
protein localization to cell cortex tip

which I think I requested yesterday

**Comment by paolaroncaglia** [comment]
Thanks @ValWood . Yes those terms are already in GO.

**Comment by ValWood** [comment]
I mean transport... but I think this is in another ticket....

**Comment by paolaroncaglia** [comment]
@ValWood 
Is it this ticket you are referring to? https://github.com/geneontology/go-ontology/issues/12822
If so, it's assigned to @dosumis .
