### ISSUE TITLE
TPV  telomeric DNA binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12826]
telomeric DNA binding
is a descendant of 
sequence specific DNA binding.

However, lots of proteins can bind telomeric DNA, and other regions  (replication and repair proteins), in a non-sequence specific manner.

**Comment by paolaroncaglia** [comment]
Hi @ValWood,

This is a tricky one.
The definition of ‘sequence-specific DNA binding’ is “Interacting selectively and non-covalently with DNA of a specific nucleotide composition, e.g. GC-rich DNA binding, or *with a specific sequence motif* or type of DNA e.g. promotor binding or rDNA binding.”. Telomeric DNA contains repetitions of TTAGGG, and I’d consider that a sequence motif. Telomeric DNA may also contain elements with added specificity e.g. X element (see http://www.ontobee.org/ontology/SO?iri=http://purl.obolibrary.org/obo/SO_0000624), so I’d consider binding to those elements as sequence-specific binding. I’d suggest to

- [ ] add a clarification to the def of ‘sequence-specific DNA binding’:
“Interacting selectively and non-covalently with DNA of a specific nucleotide composition, e.g. GC-rich DNA binding, or with a specific sequence motif, *e.g. telomeric DNA repeats*, or type of DNA e.g. promotor binding or rDNA binding.”

and

- [ ] We could also add some annotation guidance to the effect that some proteins may bind telomeric DNA, and other regions (replication and repair proteins), in a non-sequence specific manner and that in those cases the proteins should be annotated differently. Could you please provide some text, annotation examples if you have any, and indicate whet terms should be added this guidance and what alternative terms you’d suggest. I hope this makes sense. Thanks!

**Comment by ValWood** [comment]
Don't worry its a non issue. The telomere binding term has indeed only been used for repeat tract binding.

Origin binding as "sequence-specific" is a bit suspect (they are AT rich, but there isn't a recognisable sequence motif), but it isn't a huge problem
