### ISSUE TITLE
'Happens_during' relation request for UBERON_0000105 'life cycle stage' and child terms

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12820]
Hello,

I would like to request the use of the 'happens_during' relations in P2GO (as well as Noctua, if not yet possible) with UBERON_0000105 'life cycle stage' term and its child terms.

Thank you,
Barbara

@rachhuntley 
@RLovering

**Comment by dosumis** [comment]
@tonysawfordebi  I've added UBERON:0000105 to the local range.   Will this be sufficient or are edits needed to go-upper.obo  

Cheers,
David

**Comment by paolaroncaglia** [comment]
Thanks @dosumis .
@BarbaraCzub , Tony is away this week so we'll need to wait a few days. I'm assigning this ticket to myself as a reminder to follow up with him if necessary (and with anyone else as appropriate).

**Comment by BarbaraCzub** [comment]
Thank you @paolaroncaglia

**Comment by tonysawfordebi** [comment]
@dosumis I think that further edits are needed, either to go-upper.obo or db-xrefs.yaml. As far as life cycle stages are concerned, P2G currently only allows WBls IDs to be used with happens_during because WBls is the only database in db-xrefs.yaml that is defined as minting identifiers that represent life cycle stages (WBls:0000075 is_a UBERON:0000105)

**Comment by dosumis** [comment]
CC @cmungall: Does this edit look OK?

- database: WBls
  name: C. elegans development
  generic_urls:
    - http://www.wormbase.org/
  entity_types:
    - type_name: nematoda life stage
      type_id: WBls:0000075
      id_syntax: '[0-9]{7}'
      example_id: WBls:0000010

-->

- database: WBls
  name: C. elegans development
  generic_urls:
    - http://www.wormbase.org/
  entity_types:
    - type_name: life cycle stage
      type_id: UBERON:0000105 
      id_syntax: '[0-9]{7}'
      example_id: WBls:0000010

- database: UBERON
  name: Uber-anatomy ontology
  description: A multi-species anatomy ontology
  generic_urls:
    - http://uberon.org
  entity_types:
    - type_name: anatomical entity
      type_id: CARO:0000000
      id_syntax: '[0-9]{7}'
      url_syntax: http://purl.obolibrary.org/obo/UBERON_[example_id]
      example_id: URBERON:0002398
      example_url: http://purl.obolibrary.org/obo/UBERON_0002398

ADD
    - type_name: life cycle stage
      type_id: UBERON:0000105 
      id_syntax: '[0-9]{7}'
      url_syntax: http://purl.obolibrary.org/obo/UBERON_[example_id]
      example_id: URBERON:0000069


Or could keep the stricter typing here for WBls and rely on go-upper for mapping up to Uberon?

**Comment by ukemi** [comment]
We would also like to be able to use Theiler stages in Noctua for mouse annotations.

**Comment by paolaroncaglia** [comment]
Hi @dosumis ,
I'm assigning this to you to reflect that you're doing work on this, thanks.

**Comment by dosumis** [comment]
We would also like to be able to use Theiler stages in Noctua for mouse annotations.I believe that all the mappings to species specific stage ontologies are in Uberon, at least as xrefs.  @cmungall - should we be replicating these mappings in db-refs.yaml or can we leverage Uberon for this?

**Comment by dosumis** [comment]
After discussion with Tony S., I've decided to drop the proposed edit to the WBls entry and just add this to Uberon.

~~~~~~.yaml
    - type_name: life cycle stage
      type_id: UBERON:0000105 
      id_syntax: '[0-9]{7}'
      url_syntax: http://purl.obolibrary.org/obo/UBERON_[example_id]
      example_id: UBERON:0000069
~~~~~

The following are in go-upper:

[Term]
id: WBls:0000075 ! nematoda Life Stage
name: nematoda life stage
is_a: UBERON:0000105 ! life cycle stage

[Term]
id: PO:0009012 ! plant structure development stage
name: plant structure development stage
is_a: UBERON:0000105 ! life cycle stage

This allows life cycle stages for both of these ontologies to be specified as valid for AE using
 "UBERON:0000105" 

@ukemi For Theiler stages should I be specifying children of this  [EMAPA term](http://www.ebi.ac.uk/ols/ontologies/emapa/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FTS_0)?

**Comment by dosumis** [comment]
https://github.com/geneontology/go-site/commit/c672a6fba80e30469922a1de6865e1948aee2294

**Comment by ukemi** [comment]
Hi David. I think this is the right EMAPA term, but just to double-check with our anatomy expert:
@tfhayamizu

**Comment by tfhayamizu** [comment]
Mouse Theiler Stages do not have EMAPA ids, but can be represented by MmusDv identifiers from the Developmental Stage Ontology: https://github.com/obophenotype/developmental-stage-ontologies/wiki

**Comment by tfhayamizu** [comment]
Better link: https://github.com/obophenotype/developmental-stage-ontologies/wiki/MmusDv

**Comment by cmungall** [comment]
There's also the OBO page

http://obofoundry.org/ontology/mmusdv.html

In general the OBO page should have link to the owl, obo, tracker, general project description etc.

(if it doesn't you can just click edit and make a pull request)
