### ISSUE TITLE
NTR:linear ubiquitin protein ligase activity?

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12829]
Hi,

I'd like to request a term to capture the synthesis of linear ubiquitin chains. This is activity has been described for the LUBAC complex. The LUBAC complex contains a RING-inbetween-RING (RBR) E3 ubiquitin ligase. The mechanism of action for RBR ligases is described as RING/HECT-like, with the RING1 domain facilitating E2-transfer (E3 RING-like) to form a thioester intermediate with a cysteine in RING2 which then modifies the substrate protein (HECT-like). In the case of LUBAC, the enzyme can accept a Ub from an E1 or E2, forming a thioester covalent intermediate, then transfers the Ub to a substrate-Ub forming a conventional peptide bond.

I came up with a definition that describes the net reaction: i.e. transfer of the Ub from E1-Ub or E2-Ub (ie Y-Ub) to substrate-Ub (X-Ub) to make substrate-Ub (i.e. X-Ub-Ub), but does not describe the mechanism (which goes via a covalent enzyme intermediate reaction).

"The transfer of ubiquitin to an existing ubiquitin chain via the reaction X-ubiquitin + Y-ubiquitin -> Y-ubiquitin-ubiquitin + X, where the X-ubiquitin linkage is a thioester bond between the C-terminal glycine of ubiquitin and a sulfhydryl side group of a cysteine residue of an E1 or E2 enzyme and the ubiquitin-ubiquitin linkage is a peptide bond between the N-terminal ubiquitin methionine of Y-ubiquitin and the C-terminal glycine alpha-carboxyl group of the conjugating ubiquitin."

PMID:22863777 has a good description of the machanism.

Looking at the descriptions for both Ub ligases and conjugating enzymes, I am not sure if it sits well under either. So, perhaps it need to sit under " GO:0004842 ubiquitin-protein transferase activity"

Synonyms: linear ubiquitin ligase activity

As far as I know, the LUBAC complex (GO:0071797) only catalyses linear Ub chain formation. It is a child of " GO:0000151 ubiquitin ligase complex" which has a "capable of" relationship to  GO:0061630 ubiquitin protein ligase activity. 

As it is defined currently "Catalysis of the transfer of ubiquitin to a substrate protein via the reaction X-ubiquitin + S --> X + S-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the S-ubiquitin linkage is an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate. Note that this may include the extension of ubiquitin chains."

-and so is incorrect, as this linkage is to an N-terminal rather than a epsilon-amino group of lysine.

I'll stop now before my head explodes!

Thanks

**Comment by paolaroncaglia** [comment]
Hi @hattrill ,
I’ll hand your request over to @ukemi, as he worked on ubiquitin-related terms recently, so he’s the expert. 
@ukemi, let me know if you’d like me to do any edits.
I do see these terms in GO

[Term]
id: GO:1990450
name: linear polyubiquitin binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with a linear polymer of ubiquitin. Linear ubiquitin polymers are formed by linking the amino-terminal methionine (M1) of one ubiquitin molecule to the carboxy-terminal glycine (G76) of the next." [GOC:bf, GOC:PARL, PMID:23453807]
synonym: "M1-linked ubiquitin chain binding" EXACT [PMID:23453807]
is_a: GO:0031593 ! polyubiquitin binding
created_by: bf
creation_date: 2014-08-06T11:10:26Z

[Term]
id: GO:0097039
name: protein linear polyubiquitination
namespace: biological_process
def: "A protein ubiquitination process in which a linear polymer of ubiquitin, formed by the amino-terminal methionine (M1) of one ubiquitin molecule and by the carboxy-terminal glycine (G76) of the next, is added to a protein." [GOC:jsg, GOC:sp, PMID:21455173, PMID:21455180, PMID:21455181]
synonym: "M1 linkage" NARROW []
is_a: GO:0000209 ! protein polyubiquitination
created_by: paola
creation_date: 2011-04-13T01:52:51Z

so it feels like we could/should indeed host a term to capture the synthesis of linear ubiquitin chains as helen asks.

**Comment by ukemi** [comment]
Hi Helen,

Isn't this the enzyme activity you want, GO:0034450 ubiquitin-ubiquitin ligase activity?

-D

**Comment by hattrill** [comment]
This sits under "ubiquitin protein ligase activity" which is directed towards building branching Ub chains where the link is an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine.

**Comment by ukemi** [comment]
Actually, that doesn't look correct either and looks like it should be moved out and become a child of the transferase term. 
As for your term, I think we have two choices: 1) modify the existing definition to include the terminal methionine since the definition already specifies that the enzyme can extend the chains. We should add this reference as a definition xref.
2) Add the new linear activity if we think it is different enough to warrant its own term. I'm not sure it is if we modify the definition of the existing ligase term and then annotate to the process (or make a model in Noctua). The new def would be:

"Catalysis of the transfer of ubiquitin to a substrate protein via the reaction X-ubiquitin + S --> X + S-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the S-ubiquitin linkage is an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate or the terminal methionine in the case of the extension of ubiquitin chains."

What do you think?

**Comment by hattrill** [comment]
Have to run just now. Let me mull this over: This is a fairly rarefied activity, most E3 ligases do branching.

**Comment by hattrill** [comment]
Yes, that looks right. So, in essence Ub ligases catalyze of X-Ub (thioester bond) --> S-Ub (amide bond). 
So, how about a slight modification to your suggestion:
GO:0061630
ubiquitin protein ligase activity
"Catalysis of the transfer of ubiquitin to a substrate protein via the reaction X-ubiquitin + S --> X + S-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the S-ubiquitin linkage is an amide bond: an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate or, in the linear extension of ubiquitin chains, a peptide bond the between the C-terminal glycine and N-terminal methionine of ubiquitin residues."

**Comment by ukemi** [comment]
Modified as suggested.
