### ISSUE TITLE
ntr  protein transport along microtubule to cell cortex of tip/end

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12822]
Term: protein transport along microtubule to cell tip/end

Def: The directed movement of a protein along a microtubule to a cell end, mediated by motor proteins. 

Parents
GO:0098840 protein transport along microtubule

GO:1990896
Name	protein localization to cell cortex of cell tip

(logical def design pattern: It is possible that, as this is transport, the parent should be establishment of localization, but this term does not currently exist)

Rationale: different pathways involve different kinesins for different locations

Ref: PMID:11018050

**Comment by ValWood** [comment]
I don't need this term. The GP is a kinesin, and it is required for the localization of the protein in question at the cell tip, but the protein is actually transported  by the growing microtubule, and the kinesin isn't required for this step.

**Comment by ValWood** [comment]
reopening because process does exist and now need term to create a logical XP in FYPO to describe a normal phenotype.

**Comment by ValWood** [comment]
Actually his will be incorrect because this paper 
	PMID:12034771 and the earlier paper above PMID:11018050
demonstrate that although kinesin (tea2) is involved in the localization of tea1 at the cell tip, it isn't required for the movement.

Tea1 is not transported  along the microtubule, it is transported at the tip of the microtubule by  polymerization. 

So I think we need a term form movement by microtubules which isn't movement along them.

Assigning to @dosumis ...I though you did something similar for chromosome movement, but I can't find the terms...

**Comment by ValWood** [comment]
and I do need the original term 
Term: protein transport along microtubule to cell tip/end

for this community session
https://curation.pombase.org/pombe/curs/ce1fc9c90e999884

**Comment by ValWood** [comment]
Its the same protein, and partially same authors so obviously earlier findings overturned...
PMID:12034771

**Comment by dosumis** [comment]
Added

![image](https://cloud.githubusercontent.com/assets/112839/20605039/3addc756-b261-11e6-89ad-3407cd496f79.png)

OK?  (bit of a hack with the design patterns as movement and transport don't match up well)

**Comment by ValWood** [comment]
perfect!

**Comment by dosumis** [comment]
Protege crashed before saving.  I've added it again.  Done it slightly differently this time + cleaned up a bunch of related terms.

![image](https://cloud.githubusercontent.com/assets/112839/20607758/cb2c9542-b272-11e6-957e-258851b202cf.png)

**Comment by mah11** [comment]
One very finicky thing: in the term name, "microtubule polymerization based" should be hyphenated, i.e. "microtubule polymerization-based protein transport to cell tip cortex'".

**Comment by dosumis** [comment]
Agreed.   Done.

**Comment by dosumis** [comment]
Alternatively, I could rephrase to avoid stacking.  How about.

protein transport to the cell tip cortex, via microtubule polymerization

**Comment by mah11** [comment]
Either works for me - can put one wording as the name and the other as an exact synonym.

**Comment by ValWood** [comment]
I'm not convinced that this happens....I'm checking with the authors

**Comment by dosumis** [comment]
> I'm not convinced that this happens..

Seems to be what the paper says.  Is there something more recent?

**Comment by ValWood** [comment]
Want to double check....
https://github.com/pombase/fypo/issues/2896
