### ISSUE TITLE
protein transport along microtubule to cell tip/end

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12836]
Whatever the outcome of this
https://github.com/geneontology/go-ontology/issues/12822

I suggest a generic

GONEW microtubule-based protein transport
GONEW --protein transport along microtubule to cell tip/end

because even if transport on the tip exists tea2 does transport other proteins *along* the microtubule (tip1)

see
https://curation.pombase.org/pombe/curs/ce1fc9c90e999884/ro/

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/20809912/6d83db5c-b7ff-11e6-95da-1fc8b3a4a57b.png)

![image](https://cloud.githubusercontent.com/assets/112839/20809937/8871b484-b7ff-11e6-93c2-c0986b371862.png)

![image](https://cloud.githubusercontent.com/assets/112839/20809963/9aca607c-b7ff-11e6-80b5-e8676c81a371.png)

**Comment by mah11** [comment]
Did "protein transport along microtubule to cell tip" get committed? I don't see it ...

**Comment by dosumis** [comment]
>  Did "protein transport along microtubule to cell tip" get committed? I don't see it ...

Yep. There have been ongoing problems with the GO release though, most recently because of svn permissions issues.  Assuming this is what has held it up.

**Comment by mah11** [comment]
OK, thanks

**Comment by mah11** [comment]
p.s. for a FYPO logical def ... what's the ID?

**Comment by dosumis** [comment]
GO:0099117

**Comment by mah11** [comment]
ta muchly :)

**Comment by dosumis** [comment]
Hmmm...  seems like some of my edits got deleted last week!   (Probably happened due to roll back of commits with large diffs that turned out to be due to pipeline errors).   Edits not lost locally, so will be in next commit later today.

**Comment by mah11** [comment]
That makes me feel substanially less mad ;)
Thanks again.
