### ISSUE TITLE
NTR: linear ubiquitin-specific deubiquitinase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12830]
Could I request: linear ubiquitin-specific deubiquitinase activity?

child of: GO:0101005 ubiquitinyl hydrolase activity
Def:
"Hydrolysis of ubiquitin unit(s) linked by a peptide bond (linear ubiquitin) from a ubiquitinated protein."
PMID:27702987
PMID:26503766

Synonym: Met1 linkage‐specific DUB

**Comment by paolaroncaglia** [comment]
Hi @hattrill ,
Again I'm going to refer this to @ukemi , but @ukemi let me know if you'd like me to do any edit. Thanks.

**Comment by ukemi** [comment]
Hi Helen,

I added as described below. I tried to make it more consistent with other terms. Let me know if this is not ok.

-D

[Term]
+id: GO:0061815
+name: ubiquitinyl hydrolase activity, acting on linear ubiquitin
+namespace: molecular_function
+def: "Ubiquitinyl hydrolase activity acting on linear ubiquitin." [GOC:dph, PMID:26503766, PMID:27702987]
+synonym: "linear ubiquitin specific deubiquitinase activity" EXACT []
+synonym: "Met1 linkage specific DUB" EXACT []
+is_a: GO:0101005 ! ubiquitinyl hydrolase activity
+created_by: dph
+creation_date: 2016-11-28T13:58:44Z

**Comment by paolaroncaglia** [comment]
Thanks @ukemi .

**Comment by ukemi** [comment]
Note I tweaked the def:

"Catalysis of the hydrolysis of ubiquitin units from linear ubiquitin chains."

**Comment by hattrill** [comment]
Lovely! Thank you.
