### ISSUE TITLE
go-termgenie-check fails

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12834]
http://build.berkeleybop.org/job/go-termgenie-check/

embryo sac egg cell differentiation is unsatisfiable: it is asserted as 'only_in_taxon some Magnoliophyta', but it also also subclass of 'female gamete generation' which is (indirect) subclass of oogenesis, which occurs 'only_in_taxon some Metazoa'.

Magnoliophyta subclass of Viridiplantae, Metazoa subclass of Opisthokonta - Viridiplantae and Opisthokonta are disjoint.

![screen shot 2016-11-29 at 13 49 16](https://cloud.githubusercontent.com/assets/2214135/20712407/c769cdb8-b63b-11e6-8d2f-1c96cfa7946c.png)

**Comment by mcourtot** [comment]
@tberardini, @ukemi: I'm not sure what would be correct in term of fix here: removing embryo sac egg cell differentiation part of some female gamete generation would I believe fix this, but whether it is the correct fix or not..
@cmungall, @kltm: tagging as infrastructure because I don't know why the TG check fails and not the build (well I suspect because only TG checks for taxon constraints, but not sure why the 2 builds are different)

**Comment by mcourtot** [comment]
Note that as long as this is not fixed termGenie is unavailable for users "The first step is to check the ontology status. If there are issue, such as missing imports or unsatisfiable classes, TermGenie won't/cannot create safely new classes."

**Comment by ukemi** [comment]
Tanya is the expert here, but it makes perfect sense to me that we need to represent the male and female aspect of plants.

**Comment by tberardini** [comment]
>removing embryo sac egg cell differentiation part of some female gamete generation would I believe fix this, but whether it is the correct fix or not..

I don't think this is the correct fix.  The embryo sac egg cell IS the plant female gamete. 

Seems to me that the 'female gamete generation' term  links out to CL which does not include plants.  Correct?  

intersection_of: GO:0008150 ! biological_process
intersection_of: results_in_formation_of CL:0000675 ! female gamete

Options: (mix and match)

1. remove logical def to CL for the GO term 'female gamete generation' 
2. where do we have a superclass for animal and plant female (and male) gametes?  use that instead
3. get rid of 'female germ cell' capable of oogenesis relationship (definitely need to do this - that's what's mucking things up)

@ukemi - what do you think?

**Comment by ukemi** [comment]
This makes sense to me. It seems to me that oogenesis should encompass more than just what a female gamete can do.

**Comment by mcourtot** [comment]
I don't quite understand why we should get rid of 'female germ cell' capable of oogenesis. A female germ cell is a  cell that gives rise to the female gametes of an organism that reproduces, and oogenesis is the production of an ovum (egg cell), developed from the primary oocyte by maturation (paraphrased from wikipedia). It seems that it is true that a female germ cell is capable of oogenesis? I don't think using this restriction means that this is all that oogenesis encompasses?
It seems that the taxon restriction on oogenesis is causing issues - it is limited to only in Metazoa. Wikipedia tells me that oogenesis occurs also in plants "In plants, oogenesis occurs inside the female gametophyte via mitosis." (and this is the ref used on the oogenesis class), so perhaps that taxon restriction should be removed?

**Comment by dosumis** [comment]
> It seems that the taxon restriction on oogenesis is causing issues - it is limited to only in Metazoa. Wikipedia tells me that oogenesis occurs also in plants "In plants, oogenesis occurs inside the female gametophyte via mitosis." (and this is the ref used on the oogenesis class), so perhaps that taxon restriction should be removed?

I agree (was half way through writing the same thing when I saw your post.

**Comment by ukemi** [comment]
I think both the taxon restriction and the capable_of relationship are problematic, at least with respect to my interpretation of the definition of capable_of.

**Comment by cmungall** [comment]
> I think both the taxon restriction and the capable_of relationship are 
> problematic, at least with respect to my interpretation of the 
> definition of capable_of.

Do you have couterexamples?

**Comment by cmungall** [comment]
> [@cmungall](<https://github.com/cmungall>), [@kltm](<https://github.com/kltm>): 
> tagging as infrastructure because I don't know why the TG check fails 
> and not the build (well I suspect because only TG checks for taxon 
> constraints, but not sure why the 2 builds are different)

there is no separate taxon check as such, it's just a generic coherency 
test.

TG uses complete ontologies rather than modules, which is one reason for 
different results. This could be due to additional axioms in the 
complete ontology. Or it could be because the module was built from an 
earlier version of the ontology, and the latest version has incompatible 
axioms.

Either way it's unintuitive for editors to have to check this additional 
jenkins job. Should be folded in more elegantly.

**Comment by ukemi** [comment]
>  I think both the taxon restriction and the capable_of relationship are
 problematic, at least with respect to my interpretation of the
 definition of capable_of.
Do you have couterexamples?


PMID:26697222
Seems like lots more goes into oogenesis than just a process carried out by a female germ cell.

**Comment by tberardini** [comment]
IIRC, oogenesis = ovum development and the terms ovum and oogenesis are **not** generally used for plants and that is why the taxon restriction was placed on this term.  It's also why the separate term, 'embryo sac egg cell differentiation' exists, to be used for plant processes.  I would prefer that we keep that taxon restriction for oogenesis in place, despite what Wikipedia says.

**Comment by ukemi** [comment]
I think you are correct.

**Comment by mcourtot** [comment]
Ok - let's add a comment then on the oogenesis class to that effect. Would something like "The terms oogenesis and ovum are not generally used for plants and a taxon restriction was therefore place on this class" work? Shamelessly copied from @tberardini :)

That leaves us with the 'female gamete' - based on comments above: 
(1) it is imported from CL which doesn't accommodate plants
(2) it is capable of oogenesis in the current GO file, therefore restricted to Metazoa. I'm still unsure whether 'capable of' is wrong her. Looking at the definition of 'capable of', it reads "Definition: A relation between a material entity (such as a cell) and a process, in which the material entity has the ability to carry out the process." It doesn't say that it has to carry the process on its own, only that it has the ability to carry out the process. It would be good to specify this, which would then allow to decide whether this relationship is appropriate or not.

Overall, it seems that the term 'female gamete' is not appropriate here. There is an 'embryo sac egg cell" imported from PO which may be better suited? It is a subclass of plant egg cell (PO_0020094) That would be option (2) in @tberardini's proposal above.

**Comment by dosumis** [comment]
> Looking at the definition of 'capable of', it reads "Definition: A relation between a material entity (such as a cell) and a process, in which the material entity has the ability to carry out the process." It doesn't say that it has to carry out the process on its own, only that it has the ability to carry out the process. It would be good to specify this, which would then allow to decide whether this relationship is appropriate or not.

The intent is, I believe, to use this when an entity can carry out the whole process, given the appropriate conditions (environmental;  regulatory).  If it can only carry out part of it, you should use 'capable of part of'.  I can't speak for the process in plants, but in metazoans, the development of an egg typically involves the active participation of somatic follicle cells which contribute material.  In insects, the follicle cells also provide instructive signals required for a correctly patterned egg.  So, I'd use 'capable of part of' in this case.

**Comment by dosumis** [comment]
Minimal fix for now (to fix TG): have deleted logical def on 'female gamete generation'.  Seems like there are a few cases where we need a general term that will work for plants and metazoans.  @cmungall  - where should these live?

Bit surprised this not also causing problem given that 'egg cell' is_a 'female gamete':

![image](https://cloud.githubusercontent.com/assets/112839/20757754/729d1fcc-b70f-11e6-9b00-cc6bc88615af.png)

**Comment by dosumis** [comment]
Build fixed.  https://build.berkeleybop.org/view/GO/job/go-termgenie-check/606/

Based on previous experience, it may take some time for this fix to filter through to TG.

**Comment by dosumis** [comment]
- [x] remove logical def to CL for the GO term 'female gamete generation'
 - [x] Request CL get rid of 'female germ cell' capable of oogenesis relationship

https://github.com/obophenotype/cell-ontology/issues/457

**Comment by cmungall** [comment]
> there are a few cases where we need a general term that will work for plants and metazoans. @cmungall - where should these live?

well for gamete it can live happily in CL, just not below 'animal cell'

these are the CARO-level uberon classes we reference in GO (note inconsistencies around 'organ')

 * [UBERON:0000015](http://purl.obolibrary.org/obo/UBERON_0000015) ! non-material anatomical boundary
    * [GO:0048859](http://purl.obolibrary.org/obo/GO_0048859) ! formation of anatomical boundary
 * [UBERON:0000061](http://purl.obolibrary.org/obo/UBERON_0000061) ! anatomical structure
    * [GO:0048856](http://purl.obolibrary.org/obo/GO_0048856) ! anatomical structure development
    * [GO:0071695](http://purl.obolibrary.org/obo/GO_0071695) ! anatomical structure maturation
 * [UBERON:0000062](http://purl.obolibrary.org/obo/UBERON_0000062) ! organ
    * [GO:0009887](http://purl.obolibrary.org/obo/GO_0009887) ! animal organ morphogenesis
    * [GO:0010092](http://purl.obolibrary.org/obo/GO_0010092) ! specification of animal organ identity
    * [GO:0010160](http://purl.obolibrary.org/obo/GO_0010160) ! formation of animal organ boundary
    * [GO:0031100](http://purl.obolibrary.org/obo/GO_0031100) ! animal organ regeneration
    * [GO:0035265](http://purl.obolibrary.org/obo/GO_0035265) ! organ growth
    * [GO:0048513](http://purl.obolibrary.org/obo/GO_0048513) ! animal organ development
    * [GO:0048568](http://purl.obolibrary.org/obo/GO_0048568) ! embryonic organ development
    * [GO:0048799](http://purl.obolibrary.org/obo/GO_0048799) ! animal organ maturation
 * [UBERON:0000467](http://purl.obolibrary.org/obo/UBERON_0000467) ! anatomical system
    * [GO:0048731](http://purl.obolibrary.org/obo/GO_0048731) ! system development
 * [UBERON:0000468](http://purl.obolibrary.org/obo/UBERON_0000468) ! multicellular organism
    * [GO:0007275](http://purl.obolibrary.org/obo/GO_0007275) ! multicellular organism development
    * [GO:0010171](http://purl.obolibrary.org/obo/GO_0010171) ! body morphogenesis
    * [GO:0035264](http://purl.obolibrary.org/obo/GO_0035264) ! multicellular organism growth
 * [UBERON:0000479](http://purl.obolibrary.org/obo/UBERON_0000479) ! tissue
    * [GO:0009888](http://purl.obolibrary.org/obo/GO_0009888) ! tissue development
    * [GO:0042246](http://purl.obolibrary.org/obo/GO_0042246) ! tissue regeneration
    * [GO:0048729](http://purl.obolibrary.org/obo/GO_0048729) ! tissue morphogenesis
 * [UBERON:0003103](http://purl.obolibrary.org/obo/UBERON_0003103) ! compound organ
    * [GO:0048645](http://purl.obolibrary.org/obo/GO_0048645) ! animal organ formation
