### ISSUE TITLE
MF protein tag rename

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12837]
everyone dislikes the name of this term. Why don't we just call it what it is, "ubiquitin-like modifier"
(this would cover ubiquitin, SUMO, Nedd8 Urm1 atg12 etc)

**Comment by dosumis** [comment]
Should certainly at least be a synonym.  But don't you think it will be useful to keep this open for protein 'tags' that are not related to ubiquitin?

**Comment by ValWood** [comment]
are there any which  are not related to ubiquitin?
In the rest of the ontology, (for conjugation, ligation, deconjugation etc) all of the modifiers are modelled as ubiquitin-related....

If there are non-ubiquitin related ones other areas of the ontology will need changing too @ukemi

**Comment by ValWood** [comment]
Maybe a more precise def would help too....

**Comment by dosumis** [comment]
> are there any which are not related to ubiquitin?

Looks like [all so far are referred to as ubiqtuin-like](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0031386&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal)

Although for Prokaryotes/Archea the term ubiquitin-like may refer to structural similarity (beta-grasp) plus a small terminal motif rather than overall sequence similarity.  

see http://europepmc.org/articles/PMC2872088 & http://europepmc.org/articles/PMC2631945

I'd usually be reluctant to give a name/def for an MF that pins it to sequence similarity in some way. Perhaps we could extend the def here to include something functional about the mechanism of conjugation?  This could be done on the current term or on a new subclass.

**Comment by ValWood** [comment]
I think it should be defined in terms of conjugation anyway.

**Comment by dosumis** [comment]
Current def: "Acting as an indicator or marker to facilitate recognition by other molecules in the cell. Recognition of the tag, which can be covalently attached to the target molecule, may result in modification, sequestration, transport or degradation of the molecule in question."

It's easy enough to describe what it takes for a gene product to be a tag, but the result is not a standard MF definition:

"A protein is a tag if it can be conjugated (tagged) to a protein and then act as as a marker, recognized by the cellular apparatus to target it the tagged protein for some cellular process such as modification, sequestration, transport or degradation.  

For a standard MF definition we should try to phrase this as a molecular level process, when really it is two.  How about:

"A molecular function consisting of becoming covalently attached (AKA tagged or conjugated) to a protein and then acting as a marker, recognized by the cellular apparatus to target the tagged protein for some cellular process such as modification, sequestration, transport or degradation."
comment: Use this term to annotate conjugated tags, not for conjugating enzymes. At the time of writing, all known examples gene products with this activity are ubiquitin-like, either based on overall sequence similarity or the presence of common motifs and structures.
narrow_synonym: ubiquitin-like modifier activity  # Perhaps make this exact unless/until some new family fitting this def is found?

**Comment by ukemi** [comment]
But I think this function is not the tagging, it is trying to describe the activity of the tag itself once it is attached. So for example, the attached ubiquitin serves as a tag.

**Comment by dosumis** [comment]
But the capability of being conjugated to a protein is a pre-requisite, so shouldn't this be included somewhere in the def?

Maybe 

"A molecular function exhibited by a protein that is covalently attached (AKA tagged or conjugated) to another protein where it acts as a marker, recognized by the cellular apparatus... { rest of def as above } "

**Comment by ukemi** [comment]
I see what you are getting at, but I don't think we want people annotating the transferases to this term. I like the phrasing above.

**Comment by dosumis** [comment]
> I don't think we want people annotating the transferases to this term. 

Agreed.  I put that in the suggested comment: "Use this term to annotate conjugated tags, not for conjugating enzymes."

> I like the phrasing above.

Which one?

**Comment by ukemi** [comment]
"A molecular function exhibited by a protein that is covalently attached (AKA tagged or conjugated) to another protein where it acts as a marker, recognized by the cellular apparatus... { rest of def as above }

**Comment by dosumis** [comment]
OK. Thanks!  Will add, unless further objections from Val...

**Comment by ValWood** [comment]
That sounds  as though you are expecting me to object ;)

I like the new def.
I still think that "ubiquitin-like modifier"  should be the primary  name for this. 

a) We already have

Function	 GO:0061659	ubiquitin-like protein ligase activity	
Function	 GO:0019787	ubiquitin-like protein transferase activity	
Function	 GO:0019783	ubiquitin-like protein-specific protease activity	
Function	 GO:0044390	ubiquitin-like protein conjugating enzyme binding	
Function	 GO:0061650	ubiquitin-like protein conjugating enzyme activity	
Function	 GO:0070138	ubiquitin-like protein-specific isopeptidase activity	
Function	 GO:0070137	ubiquitin-like protein-specific endopeptidase activity	

for all the other terms....

b) this is what biologists call them

c) Ubiquitin-like does not necessarily mean similarity (it could be functioning like ubiquitin, i.e conjugating), so if there are  conjugators which are not ubiquitin related, if they still have the same mechanism I would not have a problem with that.

**Comment by ValWood** [comment]
actually "ubiquitin-like *protein*modifier"

Worst case sceanrio, this term doesn't work for something and we learn about some new biology.... Either way, its useful to have a grouping term for all "ubiquitin-like protein modifiers"

**Comment by deustp01** [comment]
If ubiquitin-like is too close to smuggling a specific protein or protein family into GO instead of a function, then perhaps it should be kept as some kind of a synonym, and more important as a really strident comment (derived from the discussion above) that all known modifiers that qualify for this annotation and that, if o=modifiers unrelated to the ubiquitin family are to be annotated, new terms will be needed to avoid breaking other parts of GO. (I.e., it looks like this is critical information, but it doesn't all need to be loaded into the name or a one-phrase definition.)

**Comment by dosumis** [comment]
Still reluctant to change name as requested, but will if other Eds happy to change.  @ukemi @thomaspd  - any strong opinions for or against changing 'protein tag' to 'ubiquitin-like protein modifier' ?

In the meantime, I've made all the other changes requested.
label "protein tag"
definition "A molecular function exhibited by a protein that is covalently attached (AKA tagged or conjugated) to another protein where it acts as a marker, recognized by the cellular apparatus to target the tagged protein for some cellular process such as modification, sequestration, transport or degradation."
comment "Use this term to annotate conjugated tags, not for conjugating enzymes. At the time of writing, all known gene products with this activity are ubiquitin-like, either based on overall sequence similarity or the presence of common motifs and structures."
has_exact_synonym "ubiquitin-like protein modifier"

**Comment by ukemi** [comment]
I'm also reluctant to have the name changed as suggested, mostly because I still have concerns that is will be used to annotate the transferases despite the note.

**Comment by ValWood** [comment]
Well at the moment it isn't being used  by curators for *anything*, so if a user came to GO to find all of the ubiquitin-like modifiers (the name that biologist use) they would only find 20 proteins with manual annotation  to this term.

Curators should be trained to read definition IMHO :)

Although this is a battle I am prepared to continue to lose:
https://github.com/geneontology/go-ontology/issues/2456
https://github.com/geneontology/go-ontology/issues/7419

**Comment by dosumis** [comment]
At least "ubiquitin-like protein modifier" is now a synonym, so should be easier for curators to find.  And it [is being used ](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0031386&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal) even if not as widely as it should be.
