### ISSUE TITLE
distinguishing ubiquitin-modifier "demodifying proteases" from  "processing proteases"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12838]
Nedd8 (ubiquitin- like modifier)  conjugation is reversed by Nedd8 isopeptidases in a process known as deneddylation. We have a term for this:

NEDD8-specific protease activity etc
Catalysis of the hydrolysis of NEDD8, a small ubiquitin-related modifier, from previously neddylated substrates.

BUT the precursor of nedd8 is processed into active form by a cleavage event .
which is also a  "NEDD8-specific protease activity" although not fitting this def.

So, could we 

- [ ] rename  GO:0019784 NEDD8-specific deconjugating protease activity (or similar)
and the other "ub-like deconjugating proteases" terms for the ubiquitin-like proteases to

 - [ ] Add a new term for 
GONEW NEDD8-specific processing protease activity 
The cleavage of a peptide bond  within a non-conjugatable NEDD8 ubiquitin-like modifier precursor  to create a diglycine motif in the mature Nedd8 C-terminus
original ref for activity PMID: 9353319

- [ ]  with Function process link to GO:0016485 protein processing

**Comment by ValWood** [comment]
NEDD8-specific deconjugating protease activity (or similar)

original refs for the nedd8 proteases are

Cope GA, Deshaies RJ: COP9 signalosome: a multifunctional regulator of SCF and other cullin-based ubiquitin ligases. Cell 2003, 114:663–671.
(for the signalosome)


and
Gan-Erdene T, Nagamalleswari K, Yin L, Wu K, Pan ZQ, Wilkinson KD:
Identification and characterization of DEN1, a deneddylase of the ULP
family. J Biol Chem 2003, 278:28892–28900
for the ulp family one

**Comment by ValWood** [comment]
or, we could call this
NEDD8-specific deconjugating protease activity

deneddylase activity (currently exact synonym). 
(the current term name is really a broad synonym)

**Comment by ValWood** [comment]
I guess  the new term would be is_a
GO:0004175
endopeptidase activity

**Comment by ukemi** [comment]
It looks like the parent of the existing term covers both:

Catalysis of the hydrolysis of peptide or isopeptide bonds within small proteins such as ubiquitin or ubiquitin-like proteins (e.g. APG8, ISG15, NEDD8, SUMO), or between the small protein and a larger protein to which it has been conjugated. Source: GOC:mah, GOC:ma

**Comment by ValWood** [comment]
OK I will use 

 NEDD8-specific protease activity

because the assay does not distinguish anyway, and the  processing and deneddylation enzymes appear to be partially redundant with each other. This is OK for now....

**Comment by ValWood** [comment]
However for future ref there is a little bit of inconsistency remaining here:

The parent term
GO:0019783 ubiquitin-like protein-specific protease activity
Catalysis of the hydrolysis of peptide or isopeptide bonds within small proteins such as ubiquitin or ubiquitin-like proteins (e.g. APG8, ISG15, NEDD8, SUMO), or between the small protein and a larger protein to which it has been conjugated.

is presumably referring to thiol dept hydrolase.
But only one descendent (the ubiquitin one) has this parent:
![parentage](https://cloud.githubusercontent.com/assets/7359272/20747118/ca679e46-b6e0-11e6-91b4-b486774a3f02.jpg)

**Comment by ValWood** [comment]
GO:0036459  has only one descendant
GO:0004843	thiol-dependent ubiquitin-specific protease activity

not sure how these differ?

but all of these terms are referring to the same reaction
peptide bond formed by the C-terminal glycine of ubiquitin(or other modifier) and another protein.

**Comment by ValWood** [comment]
I spotted this because I was looking for the Nedd8 protease via the thiol dependent lineage

**Comment by ukemi** [comment]
According to the note, ubiquitinyl hydrolase activity comes in two flavors, a metalloprotease flavor and a thiolprotease flavor. So I think the above structure is ok, isn't it?

**Comment by ValWood** [comment]
OK
