### ISSUE TITLE
cell ontology request: innate lymphoid cells

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#12835]
Dear CL biocurators,

I am annotating the innate immune response and would need new CL terms for innate lymphoid cells as following:
- Parent term: innate lymphoid cells as a child of lymphocyte CL_0000542
Definition:
Innate lymphocytes that are relatively rare in comparison to adaptive lymphocytes in lymphoid tissues, but they are enriched at barrier surfaces of the mammalian body, such as the skin, lung and intestine, as well as in adipose and some mucosal-associated lymphoid tissues; can be identified by expression of the common gamma chain (γc, CD132), IL-7Rα (CD127), IL-2Rα (CD25), and Thy1 (CD90) markers; respond to cytokine and microbial signals and are potent innate cellular sources of multiple pro-inflammatory and immunoregulatory cytokines
develops from: common lymphoid progenitors; development of ILCs from common lymphoid progenitors occurs independently of somatic recombination

- Children terms:
Child term 1: Group 1 innate lymphoid cell (NK cell is a child of Group 1 innate lymphoid cell)
Child term 2: Group 2 innate lymphoid cell
Child term 3: Group 3 innate lymphoid cell

Definition: Group 1 ILCs (ILC1s) respond to IL-12, constitutively express T-bet, and produce effector cytokines including interferon (IFN)-γ and tumor necrosis factor (TNF); conventional NK cells are a subset of ILC1
Definition: Group 2 ILCs (ILC2s) respond to the cytokines IL-25, IL-33 and TSLP; constitutively express high levels of GATA3; and produce the effector cytokines IL-4, IL-5, IL-9, IL-13 and amphiregulin2
Definition: Group 3 ILCs (ILC3s) respond to IL-1β, IL-6 and IL-23; constitutively express RORγt; and produce the effector cytokines IL-17 and/or IL-22

These names and definitions are based on review PMID:26121198. If you have other suggestions, please feel free to let me know.

Many thanks for your help,
Nevila Hyka-Nouspikel

**Comment by mcourtot** [comment]
Hi @nnouspikel - this is the tracker for GO, the tracker for the CL is at https://github.com/obophenotype/cell-ontology/issues. Could you please copy your ticket over there? If I do it you won't get the notifications.

Thanks,
Melanie

**Comment by nnouspikel** [comment]
Thanks Melanie for clarifying this. The ticket is in /cell-ontology/issues now. 

Best regards,
Nevila

**Comment by mcourtot** [comment]
Thanks @nnouspikel!
