### ISSUE TITLE
term merge? GO:0033108 mitochondrial respiratory chain complex assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12846]
hes descendants
 Term	Child Term Name
Is a	 GO:0032981	mitochondrial respiratory chain complex I assembly
Is a	 GO:0033617	mitochondrial respiratory chain complex IV assembly
Is a	 GO:0034551	mitochondrial respiratory chain complex III assembly
Is a	 GO:0034553	mitochondrial respiratory chain complex II assembly

and another term recently appeared? (2012)
GO:0097250 mitochondrial respiratory chain supercomplex assembly

which has 6 exp annotations.
These all appear to fit the other term, or one of its descendants?

**Comment by dosumis** [comment]
The classification is automatically derived from the classification of complexes, which is quite flat:

![image](https://cloud.githubusercontent.com/assets/112839/20833234/919dfe00-b886-11e6-955d-4cf05e10675c.png)

The supercomplex term has this def:

definition "A set of respiratory enzyme complexes of the mitochondrial inner membrane (including, for example, Complex II, Complex III, Complex IV, or F1-F0 ATPase) arranged to form a large supercomplex."^^xsd:string

So this seems to be a term for a complex of complexes.  The other complexes should probably have part_of relationship to it (has part would be safer if that's too strong.  We could then reflect the part hierarchy in the assembly terms (we typically do this).  Does this make sense to you?

The important question is whether all the individual complexes are always found as part of a supercomplex (at least when active).

**Comment by ValWood** [comment]
I'm still not sure that the term should exist based on the annotations. The annotations are to  gene products which are involved in the assembly of individual complexes. Even some of these are a bit odd because they are  mainly individual complex members...you mutate them, the complex does not assembly correctly. These aren't processes, they are only phenotypes...In the normal cell these   don;t appear to have a role in assembly per se, they are an integral part of the complex.

Have we really really got any concrete evidence that there is a pathway involved in the assembly of this "supercomplex". I don't see any.....

**Comment by dosumis** [comment]
> Have we really really got any concrete evidence that there is a pathway involved in the assembly of this "supercomplex". I don't see any.....

No idea.  Seems we really should have a general class for these complexes 

They are all part of the ['mitochondrial respiratory chain'](http://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0005746). I wonder if this is equivalent to the supercomplex?)

![image](https://cloud.githubusercontent.com/assets/112839/20836488/7543a4a6-b897-11e6-9946-06b2d93858ad.png)

so we could define simply as 'protein complex' that 'part of' some 'mitochondrial respiratory chain'

The assembly term would follow the usual pattern and the reasoner will place it correctly.

**Comment by ValWood** [comment]
Yes, I think they are equivalent.

The super complex term mentions ATPase subunits too, but there are  no experimental data showing that there are any gene products required  specifically for the assembly of  such a  "supercomplex" (or if it is even a bona fida complex, rather than complexes which localize together)....there is only data in the current annotations for the  assembly of the specific sub complexes....

**Comment by dosumis** [comment]
CC @bmeldal @hdrabkin: Proposal to merge 

'mitochondrial respiratory chain: "The protein complexes that form the mitochondrial electron transport system (the respiratory chain), associated with the inner mitochondrial membrane..."

 with

 'mitochondrial respiratory chain supercomplex':  "A set of respiratory enzyme complexes of the mitochondrial inner membrane (including, for example, Complex II, Complex III, Complex IV, or F1-F0 ATPase) arranged to form a large supercomplex."

 Do you agree?

**Comment by ValWood** [comment]
I don't object to the supercomplex term per se. 

http://www.sciencedirect.com/science/article/pii/S0005272808000947

I just don't think that the assembly term should exist (maybe organization would be better).

But this is probably more of an annotation issue.

The assembly of the supercomplex (if it is indeed a process) , isn't really a parent of the assembly of the individual subcomplexes?

The GPs currently directly annotated are either required for "stability" of the supercomplex, or sometimes for the assembly of one of the sub complexes. None appear to be really involved in assembly of a "supercomplex" per se.

Maybe I'm being a bit picky....

**Comment by ukemi** [comment]
I agree with Val that this is also an annotation issue which is separate from this ticket. I have always been hesitant to annotate members of a complex to assembly of a complex based on a phenotype. To me if a gene product was annotated to assembly, it should be part of the machinery that assembles the complex. That is why the chaperone synonym makes sense for the parent term 'protein complex assembly'.

Maybe we should have a general discussion on an annotation call. @vanaukenk

**Comment by ValWood** [comment]
Yes, there are loads of these annotations particularly around the respiratory chain members. Many of these subunits only have  an assembly annotation, and nothing to related to their role in electron transport....

Matrix QC will be a good way to weed these out so I can do intersections with protein complex assembly on the same call if you like.

**Comment by dosumis** [comment]
Potential fix

-  [ ] Send obsoltion notice for supercomplex assembly + make suggestions for re-annotation of [existing annotations](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0097250&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal)
- [ ] Merge supercomplex CC term with respiratory chain

BUT - l'm having doubts.  Looking through existing annotations, I find mention of various supercomplexes consisting of some subset of the repiratory chain complex, and some references to roles in assembly of these.  These may be dubious/ambiguous as the proteins in question seems also to be components, e.g see  [Rcf1](http://www.uniprot.org/uniprot/Q03713) & this ref:

"Rcf1 mediates cytochrome oxidase assembly and respirasome formation, revealing heterogeneity of the enzyme complex."
Vukotic M., Oeljeklaus S., Wiese S., Vogtle F.N., Meisinger C., Meyer H.E., Zieseniss A., Katschinski D.M., Jans D.C., Jakobs S., Warscheid B., Rehling P., Deckers M.
Cell Metab. 15:336-347(2012) PMID:22342701

Lots of reviews on supercomplexes too, e.g. http://www.sciencedirect.com/science/article/pii/S0005272808000947

So - perhaps we should tighten/clarify the supercomplex term to make it clear it can refer to a variety of combinations.  Also need to carefully review papers that talk about assembly to decide if it should really apply.

**Comment by bmeldal** [comment]
I haven't got more to add. I have worked on Complex I but not anything to do with supercomplexes of the rep chain.

But, just to throw it in the room, all those complexes are missing their links to redox complex terms and the related activities...

**Comment by ValWood** [comment]
mitochondrial respiratory chain
def
The protein complexes that form the mitochondrial electron transport system (the respiratory chain), associated with the inner mitochondrial membrane. The respiratory chain complexes transfer electrons from an electron donor to an electron acceptor and are associated with a proton pump to create a transmembrane electrochemical gradient.


GO:0097249    mitochondrial respiratory chain supercomplex
Cellular Component
Definition (GO:0097249 GONUTS page)
A set of respiratory enzyme complexes of the mitochondrial inner membrane (including, for example, Complex II, Complex III, Complex IV, or F1-F0 ATPase) arranged to form a large supercomplex. PMID:21909073 PMID:22342701

is really equivalent to the respiratory chain.
Merge?

**Comment by pgaudet** [comment]
**Assembly terms:** 

* Changed label 'mitochondrial respiratory chain supercomplex assembly' to 'mitochondrial respirasome assembly'. 
* Removed F1-F0 ATPase from the definition, which is not a component of the complex
