### ISSUE TITLE
chromatin silencing at subtelomere

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12841]
I based all of this on GO:0006348. GO doesn't have a CC term for subtelomeric region, but SO has a subtelomere term (pasted below). Not urgent, but will make the set of 'silencing at X' - and our phenotypes reflecting same - more complete.

id: GO:new
name: chromatin silencing at subtelomere
namespace: biological_process
def: "Repression of transcription of subtelomeric DNA by altering the structure of chromatin." [PMID:22771823, PMID:26205977]
synonym: "heterochromatic silencing at subtelomere" EXACT []
synonym: "subtelomere chromatin silencing" EXACT []
synonym: "subtelomeric silencing" EXACT []
is_a: GO:0006342 ! chromatin silencing

[Term]
id: SO:0001997
name: subtelomere
def: "A heterochromatic region of the chromosome,  adjacent to the telomere (on the centromeric side) that contains repetitive DNA and sometimes genes and it is transcribed." [POMBE:al]
is_a: SO:0000628 ! chromosomal_structural_element

**Comment by srengel** [comment]
do we really need this new term?  can't this be chromatin silencing occurs_at subtelomere in col16?

**Comment by mah11** [comment]
In principle, almost anything that can have a logical definition can be done either way.

In practice, it makes sense to handle the subtelomere the same way as other chromosome parts, genomic regions, and sequence features. These existing GO terms provide precedent (and if this new term is not added, there'd be a strong case for making them obsolete):

GO:0000183 chromatin silencing at rDNA
GO:0006348 chromatin silencing at telomere
GO:0030466 chromatin silencing at silent mating-type cassette
GO:0030702 chromatin silencing at centromere
GO:1990141 chromatin silencing at centromere outer repeat region

**Comment by dosumis** [comment]
@mah11 - agreed

In fact we already have logical defs for these:

GO:1990141 chromatin silencing at centromere outer repeat region
'chromatin silencing'
 and ('occurs in' some 'chromosome, centromeric outer repeat region')  # Note - we've never allowed occurs_at in the ontology.

I'll add the new term following this pattern.

**Comment by srengel** [comment]
ok, but just because precedent has been set years ago doesn't mean it's the way to move forward at this point in time.

**Comment by mah11** [comment]
But whichever approach we deem better now should be deployed consistently, not just to new term requests (i.e. older terms may need to be retrofitted).

I don't actually have a strong preference for precomposed GO terms for silencing at X (I can adapt FYPO terms to either); I only want them handled consistently for all values of X.

**Comment by srengel** [comment]
agreed.

**Comment by dosumis** [comment]
In this case the pattern does a small amount of useful work in the ontology that you wouldn't get from an extension:

**Comment by dosumis** [comment]
Added the new GO process term.  We should probably also add subtelomere to CC.  Need to look into how we should link this and similar terms to SO.

**Comment by dosumis** [comment]
Addes subtelomere to GO.  Opened ticket on resolving GO-SO issues: #12845
