### ISSUE TITLE
NTR tRNA 5'-end processing

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#12842]
I forgot to request this term that is missing and has the corresponding 3' sibling:

NEW tRNA 5'-end processing
GO:0042780 tRNA 3'-end processing
is_a GO:0008033 tRNA processing

Def: Any process involved in forming the mature 5' end of a tRNA molecule
PMID: 27484477

I would like to annotate the Dicty thg1 that edits cytosolic tRNAhis and not in mitochondria, to this more precise process. Also, all other similar terms have the 5' equivalent, e.g 'ncRNA 5'-end processing'

Thanks!
Petra

**Comment by dosumis** [comment]
Added.

**Comment by pfey03** [comment]
reopened this until term is available for annotation

**Comment by pfey03** [comment]
@dosumis, also, if you could please paste the new GO term id here would help to search from time to time. 5' and 3' names area bit messy in search output (at least in AmiGO)

Thanks!

**Comment by dosumis** [comment]
GO:0099116

**Comment by ukemi** [comment]
Shouldn't mitochondrial tRNA 5'-end processing GO:0097745 be made a child of the new term?

tRNA 5'-end processing occurs in some mitochondrion

**Comment by dosumis** [comment]
> Shouldn't mitochondrial tRNA 5'-end processing GO:0097745 be made a child of the new term?

Yep.  Missed that term.  Fixed by adding logical defs to all relevant terms.

**Comment by pfey03** [comment]
Thanks, yes. Thought Paola would take this ticket as she added the other terms but you caught it:-)
