### ISSUE TITLE
part of in GO

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12840]
Probably a question rooted in GO history. 

I was looking at kinase activity part of phosphorylation process. However part of, http://purl.obolibrary.org/obo/BFO_0000050, states that it relates **only** compatible classes, and further adds 'only a process can be part of a process' etc. Here we have a function part_of a process. Is there an official explanation/document? Is this an historic artefact, or the actual desired behaviour?

**Comment by dosumis** [comment]
GO MFs are processes (occurrents) that can be carried out by a single gene product or complex.  They are not functions in the BFO sense (or in the common linguistic sense).  So 'part of' is the correct relation.

(This interpretation is required for capable of to be used between complexes and MFs. 
"e capable_of p" is a shortcut for:
"Material entity(e) 'bearer of' Function(f) 'realized by' Process(p)")

**Comment by mcourtot** [comment]
Could we add this s a comment on the molecular_function class?

**Comment by dosumis** [comment]
Happy to.  How about:

"A molecular function is a process that can be carried out by a single gene product or complex. It is  not a function in the sense typically defined by upper ontologies such as Basic Formal Ontology (BFO)."

@ukemi : Is this too ontology geek focussed for a general comment?  If no veto, I'll add now.

Adding upper level classification would also help.    See proposal here: https://github.com/geneontology/go-ontology/issues/12221#issuecomment-195401632

Very simple to specify.  Only challenge is fitting this into the release pipeline.  I'd favor keeping these in place in GO-plus but removing from all other releases.

We could start by testing the effects of adding a go-upper.obo/owl file with this axiom alone to the import chain and seeing whether anything breaks.

**Comment by ukemi** [comment]
This sounds ok to me, @cmungall ?

**Comment by dosumis** [comment]
Added this to comment.
"Despite its name, this is not a type of 'function' in the sense typically defined by upper ontologies such as Basic Formal Ontology (BFO).  It is instead a  BFO:process carried out by a single gene product or complex."
