### ISSUE TITLE
Check all TG users have an associated GH account in users.yaml

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12844]
As per https://github.com/geneontology/go-ontology/issues/12789#issuecomment-264138835, some existing TG don't have a GH account in the users.yaml file which prevents them from using TG after the migration to the new login system.

**Comment by mcourtot** [comment]
List of users that have TG access but no associated GH account in users.yaml

nickname: 'Heiko Dietze'
nickname: 'Michael Rice'
  nickname: 'Elena Speretta'
  nickname: 'George Georghiou'
nickname: 'Hema Bye-A-Jee'
  nickname: 'Alex Holmes'
 nickname: 'Prudence Mutowo'
nickname: 'Yasmin Alam-Faruque'
  nickname: 'Ingrid Keseler'
  nickname: 'Trish Whetzel'
  nickname: 'Antonia Lock'
  nickname: "Peter D'Eustachio"


BHF-UCL (some indicated formerly or students): nickname: 'Anna Melidoni’, 'Sejal Patel',  nickname: 'Hadil Alrohaif’,  nickname: 'Klaus Mitchell', nickname: 'Paul Denny', nickname: 'Nancy Campbell'

MGI:  nickname: 'Cynthia Smith'

EBI Microme project:   nickname: 'Claudia Rato da Silva'

PAMGO:  nickname: 'Magdalen Lindeberg' 

RGD:  nickname: 'Shur-Jen Wang’,   nickname: 'Stan Laulederkind' ,  nickname: 'Dianna Fisk'

SGD: nickname: 'Jodi Hirschman’,   nickname: 'Maria Costanzo’,  nickname: 'Rama Balakrishnan’, nickname: 'Rob Nash’,   nickname: 'Stacia Engel'

SPOT:   nickname: 'Helen Parkinson', nickname: 'Dani Welter'

TAIR:   nickname: 'Leonore Reiser' 

UniProt  nickname: 'Anne Estreicher’,nickname: 'Alan Bridge’,  nickname: 'Andre Stutz’,   nickname: 'Duncan Legge’,   nickname: 'Elena Cibrian-Uhalte’,  nickname: 'Guillaume Keller’, nickname: 'Klemens Pichler’, nickname: 'Michel Schneider’,   nickname: 'Michele Magrane’,   nickname: 'Penelope Garmiri’,   nickname: 'Shyamala Sundaram’,   nickname: 'Ursula Hinz’,   nickname: 'Lionel Breuza'

nextprot:   nickname: 'Nevila Hyka-Nouspikel'

Intact:   nickname: 'Pablo Porras Millan'

ZFIN:  nickname: 'David Fashena'

VBI: nickname: 'Trudy Torto'

Ronin insitutue:   nickname: 'Anne Thessen'

EBI: nickname: 'Rossana Zaru'

**Comment by paolaroncaglia** [comment]
I've fixed a few, and added notes in the spreadsheet for some users that I'm sure no longer need TG.

**Comment by mcourtot** [comment]
Would it be worth having a status reflecting whether users are still active or not? We want to keep everybody in the file as it stores their GOC xref, but having something indicating users are inactive would be useful in not chasing up outdated info.

**Comment by ukemi** [comment]
Perhaps the easiest thing to do would be to have a way from the tool home page that they can request registration with a note saying if they were registered with the old system, they need to re-register with Github. That way we won't spend time tracking down people who might never use it again.

**Comment by tberardini** [comment]
I added info for @dhldhl and @lreiser.

**Comment by kltm** [comment]
@mcourtot You can use the comment field for now or marking activity.

**Comment by paolaroncaglia** [comment]
Trying to summarise and wrap up, I see that some of us have edited the spreadsheet and there's probably no more information we can add to that. So for all the users left blank on the spreadsheet, we should add a comment in the yaml file to indicate inactive status as suggested by @kltm and as previously implemented for some BHF users. We could always update if/when needed. The syntax should be

  organization: [blah]
  comment: 'status inactive'

Any volunteer to do this, or shall we just close this ticket now? :-)

**Comment by cmungall** [comment]
Closing. More can always be added on request
