### ISSUE TITLE
MP: nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12847]
term: nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts
def: The chemical reactions and pathways resulting in the selective degradation of meiosis-specific transcripts during vegetative growth, by a mechanism that requires determinant of selective removal (DSR) sequences in the targeted mRNAs and involves a YTH family protein.

should definitely be a descendant of

GO:0071028
Name	nuclear mRNA surveillance
Definition	The set of processes involved in identifying and degrading defective or aberrant mRNAs within the nucleus. 
PMID:18644474

Probably other things in other branches. I wasn't aware of the existence  "surveillance" terms until  yesterday. Most (possibly all?)
"nuclear RNA catabolism" should be under  "nuclear RNA surveillance", but currently only 28 proteins are manually annotated to the "nuclear RNA surveillance" term.

However, some of the terms under the  "surveillance" branch appear to be phenotypes:
e.g. this term does not seem to be a real  biological process: 
GO:0071033 nuclear retention of pre-mRNA at the site of transcription
but  rather a phenotype/consequence of aberrant transcription?

**Comment by ValWood** [comment]
also
nuclear surveillance of RNA export

This is defined as "nuclear surveillance" + site of the process occurring and "prior to export", so it doesn't really appear to be any different from "nuclear surveillance",  which occurs prior to export and is associated with the actively transcribed regions which are located close to the nuclear pore....

**Comment by dosumis** [comment]
> "nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts" should definitely be a descendant of "GO:0071028 nuclear mRNA surveillance"

Disagree.  This is not degradation of defective transcripts. 

Re: 'nuclear retention of pre-mRNA at the site of transcription' (has a part relationship up to surveillance) - It looks like this is a normal physiological mechanism so I think this term is fine, not a phenotype.

> Probably other things in other branches. I wasn't aware of the existence "surveillance" terms until yesterday. Most (possibly all?)

I doubt all - only those where defective transcripts are targeted.   If there are obvious examples of these that are misplaced, please can you open a new ticket for them?   Cheers

**Comment by ValWood** [comment]
def is "defective or aberrant"
I'm taking aberrant here to mean "abnormal"
the meiosis specific transcripts are aberrant during mitosis when they are degraded?

**Comment by ValWood** [comment]
Ignore that. The meiosis specific transcript stuff is cytoplasmic so it doesn't fit the def...

**Comment by ValWood** [comment]
I still think that any "nuclear RNA catabolism" belongs under here ( Only abnormal or aberrant transcripts are degraded in the nucleus). Other catabolism of transcripts (for regulatory pruposes), occurs in the cytoplasm?

**Comment by dosumis** [comment]
>  still think that any "nuclear RNA catabolism" belongs under here ( Only abnormal or aberrant transcripts are degraded in the nucleus). Other catabolism of transcripts (for regulatory pruposes), occurs in the cytoplasm?

Pretty strong generalization.  Maybe add a comment to 'nuclear RNA catabolism' to remind curators of the existence of the more specific term?

**Comment by ValWood** [comment]
Here is a basic summary

![mrna degradation pathways](https://cloud.githubusercontent.com/assets/7359272/20867928/411fd378-ba47-11e6-9f76-cf92d9e6b644.jpg)

I know that the cytoplasmic pathways are the
non-stop decay (defective)
nonsense mediated decay (defective)
deadenylation dependent  (turnover)
ARE-mediated (turnover)

Less clear about the nuclear pathways.
They appear to involve a YTH family protein and TRAMP complex  (and possibly CCR4 NOT complex)

and we don't appear to have terms for these particular   mRNA catabolic processes in GO
for me the surveillance terms will do for now.

**Comment by ValWood** [comment]
I think its all OK !   the terms under surveillance do represent these processes. I have some tidying to do....

**Comment by ValWood** [comment]
After my review of the mRNA catabolic processes at the weekend,
I still believe this is part of  "nuclear mRNA surveillance"
"nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts" should definitely be a descendant of "GO:0071028 nuclear mRNA surveillance"

Hopefully the paper @Antonialock  is checking will shed more light...
I also asked the author of another paper.
But it fits with my review of the pathways here:
mRNA catabolism #1204
and the figure above.

If this is the case we'll open a new ticket.
