### ISSUE TITLE
nrt: intramembrane serine-type protease activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12848]
Catalysis of the hydrolysis of internal, alpha-peptide bonds within the transmembrane domain of a polypeptide chain by a catalytic mechanism that involves a catalytic triad consisting of a serine nucleophile that is activated by a proton relay involving an acidic residue (e.g. aspartate or glutamate) and a basic residue (usually histidine).

synonym narrow "Rhomboid protease"
parent GO:0004252
ref: PMID:27655872

**Comment by mah11** [comment]
I'll leave the final decision to the current GO editors, but this sounds like the sort of substrate-specific thing that we were actively encouraged by MEROPS experts to remove (obsolete) and not use as the basis for distinguishing peptidase activities back when we did the big peptidase activity overhaul.

The localization specificity doesn't really fit the ways GO usually distinguishes activities from each other in MF (with the exception of a few kinase activity terms whose validity is queried occasionally, and the horrible, untenable "structural constituent of x" terms).

**Comment by ValWood** [comment]
I would have thought that cleaving a transmembrane region, within the membrane is exactly the type of functional distinction we would want to capture in GO....this is less about the "location" of the protease per se and more about the "type" of protein which is being cleaved.... 
(I will capture the substrate as an extension).

This  is very informative to the end user, and I can't think of another way to capture it. The author made the term suggestion, and so clearly thinks it is important...

But I can easily use the parent and the extension and lose this detail and the ability to group other such proteases.....

**Comment by mah11** [comment]
>  more about the "type" of protein which is being cleaved

Yes - that's substrate specificity. We were strongly advised to use _only_ mechanism, not substrate, to differentiate peptidase activities in MF.

**Comment by dosumis** [comment]
Perhaps a good compromise would be to make a BP term for cleavage of a protein within the transmembrane domain.  We can then make an MF term following an involved in pattern.

?

**Comment by ValWood** [comment]
Its an activity though and it makes the annotations quite convoluted linking the functions to the processes. I can leave it if its out of scope....

**Comment by ValWood** [comment]
OK can close. Its a shame  as they do assay for this "intra membrane" cleavage  using a model substrate, which is sort of "mechanism"

![assayed](https://cloud.githubusercontent.com/assets/7359272/20859314/1e792a94-b953-11e6-821d-a6934c33ff2d.jpg)
