### ISSUE TITLE
Equivalent classes in GO and SO for chromosome regions

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12845]
SO and GOCC both have classes for chromosome regions:

GOCC:
![image](https://cloud.githubusercontent.com/assets/112839/20798204/efa1d3e8-b7d5-11e6-97d5-608d9840b1f7.png)

SO:

![image](https://cloud.githubusercontent.com/assets/112839/20798232/121408b0-b7d6-11e6-8a03-b7b3bcc2c2ca.png)

These appear to be semantically equivalent.  I guess ideally, these would be removed from one of the ontologies (probably SO), leaving only one authoritative source.  But until then we at least need mappings.  Should these be handled as xrefs of OWL equivalentTo ?

**Comment by ValWood** [comment]
I believe there are fundamentally different entities. The SO terms are referring to the "sequence". The GO chromosome region terms are referring to   DNA+proteins  so, For example in GO the telomere would refer to the telomeric repeat tract plus the telomere end binding complex/cap.

**Comment by dosumis** [comment]
I've gone back and forth on this.  I was assuming semantic equivalence based on SO defs + immediate parents.  But looking into it some more, there is a path up to the sequence feature root that supports your description of the difference.  (TL;DR: I agree.) 

This suggests an obvious pattern, consistent with extensions, for bringing in SO terms:

name: chromosome, centromeric region
intersection_of: chromosomal region
intersection_of: coincident_with SO:centromere.

if no objection, I'll add these logical defs + write up a design pattern.

**Comment by cmungall** [comment]
+1

could also consider a more explicit has_sequence relation. But basic 
pattern good.

**Comment by ukemi** [comment]
Does that really work?

coincident with: A relation that holds between two linear structures that are approximately parallel to each other for their entire length and where either the two structures are adjacent to each other or one is part of the other.

As Val points out in GO, these represent nucleic acid/protein complexes. It is not the same as for example gene being coincident with a sequence is it?
Maybe an inverse relation? The SO:centromere is coincident with the GO region, but what is meant by linear?

**Comment by ukemi** [comment]
Actually would coincident with be symmetric? I think so. But is still seems funny based on the def.

**Comment by dosumis** [comment]
>  these represent nucleic acid/protein complexes. It is not the same as for example gene being coincident with a sequence is it?

One reason I defined this relation so that curators could refer to regions of chromosome by sequence region in extensions (e.g. region of chromosome that coincides with a particular gene).   In gorel, the local range is SO:sequence region.  There's a long discussion of this with Midori on a ticket somewhere (having trouble tracking it down). We also agreed on this in an editor's call.

All logical defs now added.  Note - this is yet another case where it would be useful to infer partonomy from an ontology used for differentia.





Don't follow.  Focus on the clause: 'that are approximately parallel to each other for their entire length'

**Comment by mah11** [comment]
> There's a long discussion of this with Midori on a ticket somewhere (having trouble tracking it down).

I had a bit of a look - seems to be in a lo-o-o-o-ng email exchange, some but not all of which was cc'd to the go-discuss list, as opposed to a tracker ticket.

**Comment by dosumis** [comment]
https://github.com/geneontology/design_patterns/blob/master/validated_patterns/chromosomal_region.yaml
