### ISSUE TITLE
issues RNA cap binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12852]
GO:0000339 RNA cap binding
is defined
Interacting selectively and non-covalently with a 7-methylguanosine (m7G) group or derivative located at the 5' end of an RNA molecule.

has a child
RNA 7-methylguanosine cap binding
Interacting selectively and non-covalently with the 7-methylguanosine group added cotranscriptionally to the 5' end of RNA molecules transcribed by polymerase II

**Comment by dosumis** [comment]
I guess the (subtle) difference is "or derivative", so the parent class is broader.  

Looking at the [wikipedia entry for 5'cap](https://en.wikipedia.org/wiki/Five-prime_cap): 

"In eukaryotes, the 5′ cap (cap-0), found on the 5′ end of an mRNA molecule, consists of a guanine nucleotide connected to mRNA via an unusual 5′ to 5′ triphosphate linkage... referred to as a 7-methylguanylate cap, abbreviated m7G.

In multicellular eukaryotes and some viruses [[7](https://en.wikipedia.org/wiki/Five-prime_cap#cite_note-fechter2005-7)], further modifications exist, including the methylation of the 2′ hydroxy-groups of the first 2 ribose sugars of the 5′ end of the mRNA. cap-1 has a methylated 2'-hydroxy group on the first ribose sugar, while cap-2 has methylated 2'-hydroxy groups on the first two ribose sugars, shown on the right."

So the parent class would cover binding to modified versions like cap-2, while the child class only covers binding to m7G. 

I could add this comment:

RNA 7-methylguanosine cap binding: Interacting selectively and non-covalently with the 7-methylguanosine group added cotranscriptionally to the 5' end of RNA molecules transcribed by polymerase II
comment: "Only use this term for binding to 7-mG caps.  For binding to caps consisting of modified 7-mG, please use the parent class RNA cap binding (GO:0000339).

**Comment by ValWood** [comment]
Ah yes you are right... I missed the "or derivative". There is a sibling term for the derivative (Possibly?), so this is OK...
