### ISSUE TITLE
issues with cap binding complexes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12853]
current arrangement
RNA cap binding complex
--mRNA cap binding complex
----GO:0098745	Dcp1-Dcp2 complex
----GO:0034519	cytoplasmic RNA cap binding complex
--nuclear cap binding complex

However there don't appear to be any cap binding complexes specific for mRNAs ..the  nuclear cap binding complex members could also be annotated to the  sibling term mRNA cap binding complex.
In fact nuclear cap binding complex has
narrow	mRNA cap binding complex

 - [x]   obsolete  "mRNA cap binding complex"
- [x]  GO:0098745	Dcp1-Dcp2 complex is_a GO:0034519
- [x]  nuclear cap binding complex is defined to use for a very specific complex (CBC), 
rename CBC cap binding complex (it isn't restricted to the nucleus, so the name is confusing)

**Comment by ValWood** [comment]
Finally this def needs updating
A conserved heterodimeric protein complex that binds to the 5' terminal cap structure m7G(5')ppp(5')N of nascent eukaryotic RNA polymerase II transcripts such as pre-mRNA and U snRNA. The consists of proteins known as CBP20 and CBP80, binds to cap structures in the nucleus, and is involved in pre-mRNA splicing, 3'-end formation, and RNA nuclear export.

A conserved heterotrimeric protein
Scrub: The consists of proteins known as CBP20 and CBP80
Replace with Human members are NCBP1-3

**Comment by ValWood** [comment]
There are 2 versions of the "nuclear" cap complex
NCBP1 and  NCBP2
or
NCBP1 and  NCBP3 (a new variant, which also appear to be conserved)

**Comment by ValWood** [comment]
- [ ] rename GO:0098745	Dcp1-Dcp2 complex "mRNA decapping complex"  
(it would be better if the others could be named functionally too)

**Comment by krchristie** [comment]
@pgaudet - I have worked on cap structure terms, but not recently. My recollection is that I would tend to agree with @ValWood that the kind of cap on eukaryotic mRNAs is not specific to mRNA. However, I was also under the impression that there a couple different kinds of RNA caps in eukaryotes, so it might be worth checking if there is any need to distinguish between cap binding complexes that distinguish between the two kinds of caps.

Also, interestingly, it seems that NAD+ based caps have been found on some RNAs in E. coli:
https://academic.oup.com/nar/article/45/14/8282/3844760
Considering that the structure of these caps is really different than the 7MeG based caps of eukaryotes, it might be undesirable to have the genes of cap binding complexes from E. coli and from eukaryotes annotated to the same term.

**Comment by bmeldal** [comment]
I have recently curated the CBCs. Yes, they are specific to RNAs but not mRNAs and I had to annotate to both terms, mRNA and nuclear CBC. And yes, the CBC is - among a host of other functions - involved in RNA export from the nucleus and functional in the cytoplasm, e.g. during pioneering round of translation.

https://www.ebi.ac.uk/complexportal/complex/search?query=cbc&page=1

I haven't yet curated the cytoplasmic cap-binding complex eIF4F that replaces CBC during translation.

**Comment by pgaudet** [comment]
@bmeldal we also have 'eukaryotic translation initiation factor 4F complex' for eIF4F; do we really need     GO:0034519 cytoplasmic RNA cap binding complex ? I would propose to also obsolete that.

**Comment by pgaudet** [comment]
With @valwood's proposed changes, this is what this part of the ontology now looks like 

![Uploading image.png…]()

I propose to also get rid of GO:0034519 cytoplasmic RNA cap binding complex  (0 annotations). 
Thanks, Pascale

**Comment by pgaudet** [comment]
(In case we decide to obsolete GO:0005845 mRNA cap binding complex 
- There are mappings to IPR031456 and IPR028271 
- + 61 manual annotations (EXP + ISS)

**Comment by ValWood** [comment]
sounds sensible
- happy for
Dcp2-Dcp1 mRNA-decapping complex not to be a "cap binding complex"

- We have already discussed (lots) removing location specific versions of the same complex, so this part would also be in agreement with existing proposals.

**Comment by ValWood** [comment]
I wondered which was my oldest ticket. This one by a long way.
I think we could just close this. Its mainly now about nuclear vs. cytoplasmic versions of the same complex. Note- for these mRNA cap  complexes I. think there *are* nuclear and cytoplasmic versions. Anyway I have not noticed any issues recently and I'm sure there have been subsequent tickets.
Closing..... yay!

**Comment by ValWood** [comment]
Actually there probably are some actions.

merge 
GO:0034519    cytoplasmic RNA cap binding complex
and GO:0005845    mRNA cap binding complex
and
GO:0005846    nuclear cap binding complex
into
GO:0034518    RNA cap binding complex

The specific complexes appear to be present and well defined?

**Comment by pgaudet** [comment]
Should I not merge into mRNA cap binding complex ?

**Comment by pgaudet** [comment]
(1) pre-mRNA cap binding complex; components:  CBP20 and CBP80
(2) mRNA cap binding complex ; components: cap-binding protein eIF4E, the adaptor protein eIF4G, and a multi-factor complex comprising eIF1, eIF2, eIF3 and eIF5.

**Comment by pgaudet** [comment]
GO:0034519 cytoplasmic RNA cap binding complex > no annotations. Merge into GO:0005846 (renamed CBC cap binding complex)

**Comment by pgaudet** [comment]
- [x] GO:0106095 m7G(5')pppN diphosphatase complex (no annotations) > merge into GO:0098745  Dcp1-Dcp2 complex
GO:0106095 corresponds to a paper describing the human version of Dcp1-Dcp2 complex. 

NOTE that Dcp1-Dcp2 complex is inactive; Dcp2 is the inhibitory subunit. 

Similarly, "DcpS is an 80 kDa homo-dimeric enzyme. In PMID:26258763 the human complex has been crystallized in its ligand free form and in the presence of minimal cap substrates (e.g. m7GpppG) as well as in complex with pharmaceutically relevant inhibitors". 

 - [x] Removed ''capable of part of' some 'deadenylation-independent decapping of nuclear-transcribed mRNA'' - since the complex is inactive; this is the activity of Dcp1 (yeast)/DcpS (human) alone.

**Comment by pgaudet** [comment]
@bmeldal 
GO:0106095 m7G(5')pppN diphosphatase complex did not exist when that ticket was created; do you agree this is the same complex as Dcp1-Dcp2 complex?

**Comment by pgaudet** [comment]
- [x] GO:0016281 eukaryotic translation initiation factor 4F complex
add 'capable of GO:0098808 mRNA cap binding'

**Comment by pgaudet** [comment]
I propose to merge 'mRNA cap binding complex' (17 EXP) into 'RNA cap binding complex' (3 EXP). Both have been used to mean either 'CBC cap binding complex' or 'eukaryotic translation initiation factor 4F complex'

That would leave the 2 children 
- 'CBC cap binding complex'
- 'eukaryotic translation initiation factor 4F complex'

OK @bmeldal @ValWood ?

**Comment by pgaudet** [comment]
Should I also add capable of part of some translation initiation ?

**Comment by pgaudet** [comment]
I also dont like the very generic definition for 'RNA cap binding complex': 'Any protein complex that binds to a specialized RNA cap structure at any time in the lifetime of the RNA.' - this sounds like the MF definition, while in the CC we should be referring to specific complexes. This term should be to group the 2 children (and maybe have a 'do not annotate' flag). 

How about 'A protein complex that binds to an RNA cap structure to mediate RNA processing and/or translation initiation. ? 
(not sure it's that much better). 

Thanks, Pascale

**Comment by ValWood** [comment]
seems OK. 
What is the fate of  'nuclear cap binding complex'? Isn't that also describing CBC?

**Comment by bmeldal** [comment]
Hi @pgaudet 

Ok, I read back through this ticket and looked at what we've already curated, mainly in yeast but some in human/mouse as well.

My take:

**nuclear cap-binding complex** 

= CBC; typical members: CBP20 and CBP80 

-> "CBC cap-binding complex" makes no sense as you are saying " cap-binding complex cap-binding complex" ;-) 

=> stick to `GO:0005846 nuclear cap binding complex`

- no action required unless you want to add any synonyms, maybe 'nuclear CBC' [EXACT]

**cytoplasmic cap-binding complex** 

has 2 terms in GO which were already discussed above:

 1. GO:0016281 eukaryotic translation initiation factor 4F complex = eIF4F = typical members: eIF4A1/A2, eIF4E, eIF4G1/G2 

and

 2. GO:0034519 cytoplasmic RNA cap binding complex - which has no annotations and is a supercomplex/assembly step for the 43S ribosomal particle made up of (see above)

- GO:0016281 eukaryotic translation initiation factor 4F complex
- GO:0005852 eukaryotic translation initiation factor 3 complex
- 40S ribosomal subunit

Suggestions:

- obsolete GO:0034519 cytoplasmic RNA cap binding complex

- `GO:0016281 eukaryotic translation initiation factor 4F complex`: add parent is_a `GO:0034518 RNA cap binding complex`

**NB:**

>GO:0034519 cytoplasmic RNA cap binding complex > no annotations. Merge into GO:0005846 (renamed CBC cap binding complex)

No, cytoplasmic CBC =  eIF4F - NOT = GO:0005846 nuclear cap binding complex = CBP20-CBP80

**GO:0098745 Dcp1-Dcp2 complex (= CPX-1628) and GO:0106095 m7G(5')pppN diphosphatase complex (= CPX-1179, DCS1 dimer)** 

- match with our CP curation and I think are different complexes: 

- Dcp1-Dcp2 decaps the mRNA while 

- DCS1 degrades the cap once removed from the mRNA (but the CP name is misleading!).

>rename GO:0098745 Dcp1-Dcp2 complex "RNA decapping complex"

- I agree.

**GO:0005845 mRNA cap binding complex**

- I think this one can be merged with GO:0034518 RNA cap binding complex (grouping term for all the above!), at least by definition.

I think that's it!

**Comment by bmeldal** [comment]
>     * [ ] Should I also add capable of part of some translation initiation ?

Yes, sounds fair. I would put it on the parent term GO:0034518 RNA cap binding complex

**Comment by bmeldal** [comment]
> I also dont like the very generic definition for 'RNA cap binding complex': 'Any protein complex that binds to a specialized RNA cap structure at any time in the lifetime of the RNA.' - this sounds like the MF definition, while in the CC we should be referring to specific complexes. This term should be to group the 2 children (and maybe have a 'do not annotate' flag).
> 
>     * [ ]   How about 'A protein complex that binds to an RNA cap structure to mediate RNA processing and/or translation initiation. ?
>       (not sure it's that much better).
> 
> 
> Thanks, Pascale

Happy with that.

**Comment by bmeldal** [comment]
Apologies, @pgaudet I think I proposed some of your already proposed merges while getting my head around it all so I think on many things we agree. But a few things not (yet ;-) ).

**Comment by krchristie** [comment]
Since the two RNA cap structures I know of have different structures, should we specify which type of cap structure is being bound?

**Comment by ValWood** [comment]
My oldest ticket, so close to closure (a few times!)

**Comment by ValWood** [comment]
@sjm41 @pgaudet you have been looking at these activities recently. Maybe can get this ticket over the line. I'm not sure what is outstanding.

**Comment by pgaudet** [comment]
Making changes suggested by Brigit : https://github.com/geneontology/go-ontology/issues/12853#issuecomment-734850916

- [x] GO:0005846 nuclear cap binding complex : Added synonym, maybe 'nuclear CBC' [EXACT]
- [x] GO:0016281 eukaryotic translation initiation factor 4F complex:  add parent is_a GO:0034518 RNA cap binding complex
- [x]  add synonym "cytoplasmic cap-binding complex"
- [x] rename GO:0098745 Dcp1-Dcp2 complex "RNA decapping complex"
- [ ] Update definition RNA cap binding complex': 'A protein complex that binds to an RNA cap structure to mediate RNA processing and/or translation initiation. 
- [ ] Obsolete GO:0034519 cytoplasmic RNA cap binding complex (no annotations) & replace by GO:0016281 eukaryotic translation initiation factor 4F complex
- [ ] Obsolete GO:0005845 mRNA cap binding complex & replace by GO:0034518 RNA cap binding complex (grouping term for all the above!), at least by definition.

**Comment by pgaudet** [comment]
I will not do 
> Obsolete GO:0005845 mRNA cap binding complex & replace by GO:0034518 RNA cap binding complex (grouping term for all the above!), at least by definition.

because there are annotations to other enzymes, such as decapping enzymes (https://amigo.geneontology.org/amigo/reference/PMID:28533364 - PomBase @ValWood ) 

Maybe this will need more clean up later

**Comment by ValWood** [comment]
OK
