### ISSUE TITLE
improve name and definition: Mmi1 nuclear focus complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12850]
This isn't really a complex, although over time it has morphed into one.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990251#term=history

Originally it was a "nuclear body"

now we have much  more precise/correct complex terms to use, so this can go.

Only pombe has used it for manual annotation.

**Comment by mah11** [comment]
Presumably GO:1902666 'protein localization to Mmi1 nuclear focus complex' should also get the ax.

**Comment by ValWood** [comment]
yep, 0 annotations...

**Comment by mah11** [comment]
used in FYPO logical defs - see https://github.com/pombase/fypo/issues/2913

**Comment by ValWood** [comment]
@dosumis  can we hang fire on this one.
It might be best to move so it isn't a complex.
@Antonialock  has a community curation session which uses this term. We might be able to define better....

**Comment by pgaudet** [comment]
@ValWood did you decide what you want to do about this one ? Pombase is the only group with EXP annotations. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think we want to keep it because it seems to be a pretty important  region.
@Antonialock  could you check the papers you did, and suggest a better def , it shouldn't be a complex.

Something like: A nuclear focus where the complexes involved in nuclear mRNA surveillance  including exosome, NURS complex, various poly(A) polymerases, and RNA binding proteins concentrate.

Parent would be "nuclear body"
In pombe we cal it mmi1 focus, but maybe it has a more generic name?

**Comment by Antonialock** [comment]
Yes it doesn't seem like it should be a complex, but a nuclear body..from PMID:26804377

"Moreover, we found that Erh1 colocalized with foci formed by known nuclear factors involved in meiotic mRNA decay, including Red1, Mtl1 and Rrp6, as well as with Pcf11, a cleavage and polyadenylation specificity factor (Figure 1B). Thus, we find that Erh1 colocalizes with RNA elimination factors to cleavage bodies in vegetative cells."

- Also, we need a new term for EMC complex
"we find Erh1 and Mmi1 form a tight complex, which we term EMC (Erh1-Mmi1 complex)." 
"Therefore, we propose that EMC, like MTREC and the nuclear exosome, is another complex essential for meiotic mRNA degradation, and that these complexes cooperate to degrade meiotic mRNAs."

But this complex interacts with multiple other complexes
"This complex promotes meiotic mRNA decay and heterochromatin assembly via separate mechanisms"
"In addition to directing MTREC-mediated mRNA decay and the formation of heterochromatin islands at meiotic genes silenced by the exosome, EMC engages CCR4-NOT for RNAi-dependent assembly of HOODs (HOODs silence meiotic genes). CCR4-NOT also promotes rDNA silencing and integrity, and triggers RNAi-mediated heterochromatin assembly at genes and retrotransposons containing cryptic introns."

**Comment by ValWood** [comment]
rename back to 
mmi1 nuclear focus

add parent
"nuclear body" GO:0016604

remove parent "protein complex"

**Comment by ValWood** [comment]
It seems it got changes at some point, not sure why... see log

Def should be reverted too...
