### ISSUE TITLE
ntr: ER-plasma membrane tethering

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12855]
Def: The attachment of a  the endoplasmic reticulum to the plasma membrane
is_a GO:0051643 endoplasmic reticulum localization
Ref PMID:23237950 PMID:26877082

**Comment by ukemi** [comment]
Do you think this is also a membrane to membrane docking?

**Comment by ValWood** [comment]
sounds like it. I was copying this term name
 GO:1990456	mitochondrion-ER tethering

**Comment by ValWood** [comment]
Is there a ref for the docking term? I have only heard docking used in the context of vesicles...I can check if we know where the docking terminology came from...

**Comment by ukemi** [comment]
Nah. It's one of those old terms without a reference. It looks like the most generic parent was made during the is_a complete project. I've heard docking used for vesicles and for proteins and membranes. But it seems to always be in the context of the first interaction that takes place. Thinking about it more, I don't think this fits docking any more than cell adhesion does. 

 [Term]
+id: GO:0061817
+name: endoplasmic reticulum-plasma membrane tethering
+namespace: biological_process
+def: "The attachment of a the endoplasmic reticulum to the plasma membrane." [GOC:dph, GOC:vw, PMID:23237950, PMID:26877082]
+synonym: "ER-plasma membrane tethering" EXACT [GOC:dph]
+is_a: GO:0051643 ! endoplasmic reticulum localization
+created_by: dph
+creation_date: 2016-12-05T14:43:58Z
