### ISSUE TITLE
ntr: regulation of mRNA splicing efficiency  PMID:26730850

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12857]
child of 
GO:1905744 Label: regulation of mRNA cis splicing, via spliceosome
ntr: regulation of mRNA splicing efficiency (at weak splice sites?)
def: The process which regulates the timing of mRNA cis-splicing of introns with weak  splice donor signals.

Nice paper shows pretty conclusively that many introns which do not have the canonical GT at 3' end of the 5'branch do not pair efficiently with U1 snRNA. These "prp4 dependent" introns require the prp4 kinase to alleviate the various arrest phenotypes associated with delayed splicing.

various EXPs to show  efficient splicing of many introns requires ppr4 kinase
plus:
Prp4-dependent and -independent introns can be interconverted by mutating the exon1/5’ SS region

The author called it "decreased splicing efficiency at weak splice sites"

I think it only needs to be a regulation term, because all "efficiency" would be regulation. There might be a better way to name the term?

PMID:26730850

**Comment by ukemi** [comment]
I think 'regulation of mRNA splicing efficiency' is way too general. We need to think of a better name.

**Comment by ValWood** [comment]
ntr: regulation of mRNA splicing efficiency at weak splice  donor sites 

then?

**Comment by ukemi** [comment]
That's better. @krchristie  any suggestions?

**Comment by ukemi** [comment]
PS. I already approved this in TG:
GO:1905744 Label: regulation of mRNA cis splicing, via spliceosome

**Comment by krchristie** [comment]
I'm just wondering how "regulation of mRNA splicing efficiency at weak splice donor sites" would be different from the existing term:

"GO:0000381 - regulation of alternative mRNA splicing, via spliceosome"

since regulation of usage of weak splice donor sites is definitely a component of regulation of alternative splicing.

**Comment by ValWood** [comment]
Its not alternative splicing in pombe. Its always the same splice site, it's just that some donor sequences are not efficiently spliced. Maybe regulation will do though...can capture the rest with phenotypes. I'll  use that...
