### ISSUE TITLE
issues around mRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12851]
In GO RNA processing is defined
Any process involved in the conversion of one or more primary RNA transcripts into one or more ****mature RNA molecules***.

BUT "processing" is also used to describe

cytoplasmic mRNA processing body
A focus in the cytoplasm where mRNAs may become inactivated by decapping or some other mechanism. mRNA processing and binding proteins are localized to these foci. 

which is related to degradation? The enzymes here are  involved in deneddylation and decapping, not processing as defined above.

How to resolve?

**Comment by dosumis** [comment]
It looks like this is a terminological issue rather than an issue with ontology structure.   Would it be sufficient to rename this CC to P-body (which is what most people seem to call it), keeping the current name as an exact synonym?

**Comment by ValWood** [comment]
Maybe.....(more used name anyway...) and also change "mRNA processing" to mRNA degradation, nonsense-mediated mRNA decay (NMD), translational repression, and RNA-mediated gene silencing.

**Comment by dosumis** [comment]
Done.
