### ISSUE TITLE
Jenkins Documentation for Ontology editors

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12861]
We need to write documentation for ontology editors that describes the Jenkins jobs and how to handle build failures.

**Comment by kltm** [comment]
We'll be in flux over the next few months. I'd like to move away from anybody non-technical having to get near Jenkins and interpret what's going on, if at all possible. Ideally, reports and status can be handled by more user-friendly means (cachet.io, etc.)

On the side, given the readme here says that his tracker is "Repo and issue tracking for ontology edits", this should probably be moved to go-site.

**Comment by pgaudet** [comment]
Out of date
