### ISSUE TITLE
Should conidium formation/development be part of sorocarp development?

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12862]
We currently have:

![image](https://cloud.githubusercontent.com/assets/112839/21025895/3252ceac-bd82-11e6-897e-c0fd1ef88a94.png)

This appears to be wrong.

conidium formation: "The process of producing non-motile spores, called conidia, via mitotic asexual reproduction in higher fungi. Conidia are haploid cells genetically identical to their haploid parent. They are produced by conversion of hyphal elements, or are borne on sporogenous cells on or within specialized structures termed conidiophores, and participate in dispersal of the fungus."

A sorocarp is a non-reproductive fruiting body of social amoebae.

To problem seems to be the general term 'sorus'  

![image](https://cloud.githubusercontent.com/assets/112839/21025979/8f9a353c-bd82-11e6-94f1-8e78f354abbf.png)
https://en.wikipedia.org/wiki/Sorus

Suggested fix: add new term sorocarp sorus development as a subclass of sorus development.  Move part relationship down to this term.

CC @pfey03

**Comment by dosumis** [comment]
Fix:

![image](https://cloud.githubusercontent.com/assets/112839/21026300/e53dbdfa-bd83-11e6-94c2-758286265117.png)


But note problematic inference to 'multi-organism reproductive process'.  The reproductive bit comes from  classification of the parent class under 'reproductive structure development':

![image](https://cloud.githubusercontent.com/assets/112839/21026410/525e69f2-bd84-11e6-8920-2f0e9d0ab1cb.png)

Note also that spore is defined as fungal structure:

![image](https://cloud.githubusercontent.com/assets/112839/21026433/729a02b2-bd84-11e6-97fa-9d9c2867160e.png)

This obviously doesn't work for Dicty.

Solution: make new subclass of sorus development to cover fungi?

Alternatively we could change this term 'fungal sorus development' and make it a sibling of 'sorocarp sorus development'

**Comment by dosumis** [comment]
CC @dsiegele

**Comment by dosumis** [comment]
Fixed:  There are now 2 sorus development terms.  The existing term -> sorocarp sorus development (there are only 3 direct annotations with exptl evidence.  All these are dicty).  New term - fungal sorus development.  Logical def references DDANAT sorus.

**Comment by pfey03** [comment]
Thanks for identifying  and putting the house in order!

**Comment by pgaudet** [comment]
Is this correct ? Dicty is not a fungus, so we have removed the logical definition in which the fungal sorus development refers to DDANAT sorus, and added it to sorocarp development. Is this OK?

**Comment by dosumis** [comment]
> Is this correct ? Dicty is not a fungus, so we have removed the logical definition in which the fungal sorus development refers to DDANAT sorus, and added it to sorocarp development. Is this OK?

Should be on "GO:0048837 ; sorocarp sorus development"

(Can you link to this ticket from relevant pull request or commit?)

**Comment by pgaudet** [comment]
Hi @dosumis 

The commit is: 
https://github.com/geneontology/go-ontology/commit/f5791041a49708a50b8292184239f7855686768a

Pascale

**Comment by dosumis** [comment]
OK.  Looks good.  Thanks for spotting.

**Comment by pgaudet** [comment]
Great :)
