### ISSUE TITLE
NTR: tRNA folding

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12860]
I just read a new paper, PMID 27849601, that shows tRNA chaperone activity for an E. coli enzyme, TruB.  Given the clear importance of proper tRNA folding, I think it would be useful to have a GO term for it.  Proposed parent: GO:0034337.  Proposed definition: The process of assisting in the folding of tRNAs into the correct tertiary structure.

Thanks,
Ingrid

**Comment by ukemi** [comment]
[Term]
+id: GO:0061818
+name: tRNA folding
+namespace: biological_process
+def: "The process of assisting in the folding of tRNAs into the correct tertiary structure." [GOC:dph, PMID:27849601]
+is_a: GO:0034337 ! RNA folding
+intersection_of: GO:0034337 ! RNA folding
+intersection_of: has_input CHEBI:17843 ! transfer RNA
+created_by: dph
+creation_date: 2016-12-13T15:54:40Z
