### ISSUE TITLE
remove regulates relations between symbiont->host processes and "normal" host processes

### ISSUE THREAD

**Issue by thomaspd** [geneontology/go-ontology#12865]
There are several relations this covers, e.g.

GO:0052552 modulation by organism of immune response of other organism involved in symbiotic interaction
is_a
GO:0050776 regulation of immune response

and

GO:0052255 modulation by organism of defense response of other organism involved in symbiotic interaction
is_a
GO:0031347 regulation of defense response

Though these seem at first to be obvious logical relations, they are semantically incorrect.  The child terms are used to describe the FUNCTION OF THE SYMBIONT GENE, i.e. what is the function for the symbiont?  But the relations link them to the FUNCTION OF HOST GENES instead, which leads to the incorrect logical inference that the function of the symbiont gene is in the immune response of the symbiont. 

These relations are trying to capture the effect on the host, but it cannot be done this way.  Suggest we remove these relations for now.

**Comment by ukemi** [comment]
Doesn't the inference say that the function of the symbiont gene regulates the function of the host gene? I think that is how these were originally intended.

**Comment by ukemi** [comment]
@thomaspd   Does this make sense, or would you still like these removed?

**Comment by thomaspd** [comment]
Unfortunately the current usage doesn't specify whether it is the symbiont's or the host's immune system, so it has ambiguous semantics.  More importantly, the term "regulation of immune system process" is far more commonly used to refer to the immune system of the organism that encodes the gene that is being annotated.  So until we can distinguish these cases, it's best to keep with our more commonly used semantics, in this case that regulation of immune system process means regulation of one's own immune system.

We'll be able to make proper statements LEGO.

**Comment by ukemi** [comment]
OK. I removed those parents.
