### ISSUE TITLE
OTR: Revise definition of Elg1 RFC-like complex

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12863]
GO:0031391 Elg1 RFC-like complex

Can I suggest an update to the definition of this complex as it has now been demonstrated to unload PCNA from chromatin.

"A pentameric replication factor C (RLC) complex, which unloads the DNA polymerase processivity factor proliferating cell nuclear antigen (PCNA) from chromatin and has roles in telomere length regulation and other aspects of genome stability. In Saccharomyces the subunits are known as Elg1p, Rfc2p, Rfc3p, Rfc4p, and Rfc5p."

Refs:PMID:27664980 & PMID:23499004

**Comment by ukemi** [comment]
Modified definition as suggested and added references.

**Comment by ValWood** [comment]
I was just about to IC the unloading process, but I don't see the definition revision?

**Comment by mah11** [comment]
Where are you looking? The current obo files have Helen's text.

**Comment by ValWood** [comment]
ignore me.
