### ISSUE TITLE
NTR:SCF ubiquitin ligase complex binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12864]
Could I have:
"SCF ubiquitin ligase complex binding"
"Interacting selectively and non-covalently with a SCF (Skp, Cullin, F-box-containing) ubiquitin ligase complex."

This could either sit under GO:0032403 (protein complex binding) or a new intermediate term: ubiquitin ligase complex binding (with children: SCF ubiquitin ligase complex binding & GO:0010997, anaphase-promoting complex binding)

**Comment by ukemi** [comment]
Hi Helen,

If you can supply a PMID, I will request this in TermGenie.

-D

**Comment by hattrill** [comment]
Hi David,

PMID:19723762 <http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=AbstractPlus&tool=FlyBase&list_uids=19723762>

doi: 10.1101/gad.1822409 <http://dx.doi.org/10.1101/gad.1822409>


Thanks!

Helen

**Comment by ukemi** [comment]
[Term]
id: GO:1905761
name: SCF ubiquitin ligase complex binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with a SCF ubiquitin ligase complex." [GO_REF:000102, GOC:dph, GOC:ha, GOC:TermGenie, PMID:19723762]
synonym: "CDL1 complex binding" EXACT [GOC:TermGenie]
synonym: "CRL1 complex binding" EXACT [GOC:TermGenie]
synonym: "Cul1-RING ubiquitin ligase complex binding" EXACT [GOC:TermGenie]
synonym: "cullin-RING ligase 1 binding" EXACT [GOC:TermGenie]
synonym: "SCF complex binding" EXACT [GOC:TermGenie]
synonym: "SCF complex substrate recognition subunit binding" NARROW [GOC:TermGenie]
synonym: "Skp1/Cul1/F-box protein complex binding" EXACT [GOC:TermGenie]
intersection_of: GO:0005488 ! binding
intersection_of: has_input GO:0019005 ! SCF ubiquitin ligase complex
created_by: ukemi
creation_date: 2016-12-14T15:08:12Z
