### ISSUE TITLE
TPV: transporters classified as both active and passive

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12866]
### Channel conductance controlling ATPase activity

"Channel conductance controlling ATPase activity" GO:0005260 is classified as both active an passive transporter (channel):

![image](https://cloud.githubusercontent.com/assets/112839/21143381/644c6c32-c13e-11e6-93df-563cd7613eed.png)

This seems to be a term for Cystic fibrosis transmembrane conductance regulator (CFTR)   (narrow synonym). 

-  https://en.wikipedia.org/wiki/Cystic_fibrosis_transmembrane_conductance_regulator
 - http://physrev.physiology.org/content/79/1/S23.long
As far as I can gather, this has ATPase activity, but is gated by ATP (or by phosphorylation?)

So, it probably shouldn't live under:  'ATPase activity, coupled to transmembrane movement of substances'

Def is a bit odd:

definition "Catalysis of the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O = ADP + phosphate. An animal enzyme that is active in forming a chloride channel, the absence of which brings about cystic fibrosis. It is also involved in the functioning of other transmembrane channels."^^xsd:string

### 'oligogalacturonide-transporting ATPase activity'

![image](https://cloud.githubusercontent.com/assets/112839/21143580/28eab850-c13f-11e6-8e1d-beaf3e0ed3ec.png)

**Comment by ukemi** [comment]
I agree, this is weirdly represented. It looks like the def came from the EC and Metacyc descriptions, but is misinterpreted. From the EC number, this looks like it should just be an ATPase activity. Perhaps then add a comment that the gene product also has chloride channel activity?

**Comment by dosumis** [comment]
This is one of those cases where we're almost defining a function for a single gene product so may want to consider how much we pack into a single MF term.  In this case we've done this remarkably poorly though - probably because EC has too.

As far as I can gather, CFTR is a chloride channel gated by intracellular ATP. Gating is also dependent on phosphorylation and (probably) on ATPase activity (there is a long and interesting discussion of the role of ATPase activity in  http://physrev.physiology.org/content/79/1/S23.long under "III. REGULATION BY ADENOSINE 5′-TRIPHOSPHATE HYDROLYSIS: THE NUCLEOTIDE-BINDING DOMAINS")

This suggests it belongs under, 'ATP-gated ion channel activity' but also that it may be equivalent to:

"ATP-binding and phosphorylation-dependent chloride channel activity' (a child of intracellular-ligand gated ion channel activity).

The phrases 'transmembrane conductance regulator' and 'Channel conductance controlling' refer to the broader process context - it's effect on membrane conductance. [See WP](https://en.wikipedia.org/wiki/Cystic_fibrosis_transmembrane_conductance_regulator#Location_and_function).

I've done enough work on this that I decided to fix:

I merged 'ATP-binding and phosphorylation-dependent chloride channel activity' with 'channel conductance activity', renamed and reclassified:

rdfs:label "intracellular ATPase-gated chloride channel activity"
id "GO:0005260"^^xsd:string
has_alternative_id "GO:0005224"^^xsd:string
has_obo_namespace "molecular_function"^^xsd:string
definition "Enables passage of a chloride ion through a transmembrane channel that opens when intracellular ATP is bound and hyrdolysed.  Passage is via passive diffusion once the channel is open."^^xsd:string [PMID: 9922375] 
has_exact_synonym "ATP phosphohydrolase (channel-conductance-controlling)"^^xsd:string
has_exact_synonym "ATP-binding and phosphorylation-dependent chloride channel activity"^^xsd:string
has_exact_synonym "channel-conductance-controlling ATPase activity"^^xsd:string
has_narrow_synonym "cystic fibrosis transmembrane conductance regulator"^^xsd:string
has_narrow_synonym "cystic-fibrosis membrane-conductance-regulating protein activity"^^xsd:string
database_cross_reference "EC:3.6.3.49"^^xsd:string
database_cross_reference "MetaCyc:3.6.3.49-RXN"^^xsd:string

![image](https://cloud.githubusercontent.com/assets/112839/21354964/0ed4b81e-c6c4-11e6-89d4-6c7f7c9bb6b7.png)

![image](https://cloud.githubusercontent.com/assets/112839/21354985/20db1d96-c6c4-11e6-8024-2363b582152d.png)

Do you think this fix looks reasonable?

**Comment by ukemi** [comment]
Yes. This looks reasonable and certainly seems more correct than it was.  I agree we are trying to pack a lot into a single function here (and elsewhere)!
