### ISSUE TITLE
Using both ChEBI and SO in axioms

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12867]
Yesterday I made a term 'tRNA folding' fully assuming that its logical definition would classify it as a tRNA metabolic process. To my surprise this didn't happen. The reason is that for some terms in the ontology, we create axioms using the ChEBI term 'transfer RNA' and for some terms we use the SO term 'tRNA'. I suspect that we want the ChEBI term since it refers to the molecule whereas the SO term is a sequence feature. We need to go through and clean this up one way or the other.

**Comment by ValWood** [comment]
Hi David,

I don't think tRNA foldng is metabolic is it?  (protein folding isn't metabolic either)

**Comment by hdrabkin** [comment]
If folding is a part of trna biosynthesis (term doesn't exit; should it ? If so, would it not have something in it that says ... resulting in a fuctional/mature tRNA). I would think the same might need to be true of protein... ?

**Comment by ukemi** [comment]
RNA folding is_a RNA metabolic process in GO.

**Comment by ValWood** [comment]
I don't think they should be based on previous discussions. The tRNA isn't "metabolised" during folding?
So chromosome condensation isn't DNA metabolism.....

**Comment by ukemi** [comment]
Hi Val,

If you think this is an issue, please open a separate ticket. This ticket should stick to the use of SO and ChEBI in the axioms. It would be simple enough to just put RNA folding under cellular process.

-D

**Comment by dosumis** [comment]
Draft bridging ontology with relevant axioms is here:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/go_bridge.owl?view=log
(see also #12341).

Try importing this into a Protege session and checking for inferences.

TODO
 - [ ] Add appropriate import statements to main GO files + redirects to catalog xml files. 
 - [ ] Set up BFO minimal import generation

Warning - file has some equivalence axioms between named classes.  May cause Jenkins build to fail.  If this is the case, we could potentially be relaxed to subclassing axioms until build issues are fixed.

**Comment by dosumis** [comment]
See discussions on #12341.  Minimal BFO import is duplicated with item on #12341.
