### ISSUE TITLE
RNA folding parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12868]
RNA folding is a RNA metabolic process, should it be

Note protein folding is not a protein metabolic process
Chromosome condensation is not a DNA metabolic process

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/12867#

**Comment by ukemi** [comment]
We could move it to 'cellular process' as has been done with protein folding.

**Comment by ukemi** [comment]
Moved to cellular process.
