### ISSUE TITLE
Incorrect is_a relationship "photoreceptor cell cilium" GO:0097733

### ISSUE THREAD

**Issue by JohnvanDam** [geneontology/go-ontology#12871]
Dear GO developers, @paolaroncaglia,

I observed the following error in the ontology:
"photoreceptor cell cilium" GO:0097733 is currently a child term of "9+2 non-motile cilium" GO:0097732, but this should be "9+0 non-motile cilium" GO:0097731.

Best wishes,
John

**Comment by paolaroncaglia** [comment]
Hi @JohnvanDam ,
Thanks for spotting this! Fixed now.
