### ISSUE TITLE
eco-mapping for IMP

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12872]
Recent changes to IMP-> ECO mapping are causing problems for EBI consumption of annotations.  May cause problems elsewhere too.  This was an attempt to fix problems with evidence types we would consider to be IMP not having the correct classification in ECO.  Editor's should check these and see if they agree that ECO should change classification of terms rather than changing the IMP-ECO mapping.
https://github.com/evidenceontology/evidenceontology/issues/125

**Comment by tberardini** [comment]
Does this belong on the annotation tracker instead of the ontology tracker?

**Comment by ukemi** [comment]
Looks like this was fixed, so I won't move it.
