### ISSUE TITLE
synonyms GO:1903394 - protein localization to kinetochore involved in kinetochore assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12875]
can we delete these?

protein localisation to kinetochore involved in kinetochore biogenesis [GOC:TermGenie]
protein localisation to kinetochore involved in kinetochore biosynthesis [GOC:TermGenie]
protein localization to kinetochore involved in kinetochore biogenesis [GOC:TermGenie]
protein localization to kinetochore involved in kinetochore biosynthesis [GOC:TermGenie]

and b)  people don't really use biogenesis/biosynthesis in this context

Actually now I look in QuickGO, I think we sometimes have the same synonyms for  different scopes

**Comment by mah11** [comment]
The localization term inherited those synonyms from GO:0051382 'kinetochore assembly'. The positive and negative regulation terms also have corresponding synonyms, but the parent regulation term doesn't. I don't have a preference regarding whether they terms have or don't have the synonyms, but they ought to be consistent (i.e. all have them or none).

**Comment by ukemi** [comment]
As usual, I agree with Midori. They are all gone.
