### ISSUE TITLE
ER membrane targeting

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12878]
I want to annotate a GP which is involved in post translational targetting to ER membrane.

There are 2 applicable terms, in different branches

protein targeting to ER; GOid=GO:0045047
posttranslational protein targeting to membrane

Is it possible to have a term which captures all features of both?

Thanks

**Comment by deustp01** [comment]
But carefully. We need to be able to distinguish proteins destined to be associated with the plasma membrane that remain inserted into the ER membrane, and one destined for secretion that pass through the ER membrane as they are synthesized and end up free in the ER lumen. And also to distinguish stages in the life of a membrane-associated one which initially is associated with the ER membrane, then the Golgi, then a vesicle or the plasma membrane, at least in textbook descriptions of mammalian ones.

**Comment by ukemi** [comment]
I agree with Peter. This one is tricky, but it seems that you want this process to be specifically post-translational. So I think that rules out the passing through during translation and the serial membrane transfer. So I think we could create 'posttranslational protein targeting to ER membran', but how do we keep annotators from using it incorrectly for the processes described above?

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/19956640
https://www.ncbi.nlm.nih.gov/pubmed/18724936

Can we make it clear that the targeting process is only for delivery/insertion to the ER (cytoplasmic side) ?

This is the pathway for GPs which can't be localized by the SRP because the localization signal  for the GP's which are  attached to the external side of the membrane are in  C-term rather than the N-term. I assume the separation of the signal sequences is an evolutionary mechanism to ensure that resident/integral to ER side, or inserted  into cytoplasmic side go via the correct route.

"post-translational targeting to ER membrane" would appear to cover ?

I'm not sure of the GET complex targets but I am assuming it is things like the Sre1 cleavage activating protein and sterol regulatory element binding protein, transcription factor Sre1
which are external to the ER membrane. The trafficked proteins are internal aren't they (lumen or membrane)? or is that not always the case

**Comment by ValWood** [comment]
I was annotating the orthologs of this
https://www.ncbi.nlm.nih.gov/pubmed/27905431?dopt=Abstract
It seems that there is redundancy in the pathways (this pathway can act as a backup for loss of SRP or GET.


We need a term
post-translational targeting to ER
exact synonym  SRP-independent targeting to ER

The targeting of proteins to the ER membrane that occurs post-translationally. This can target proteins which do not  have an terminal signal sequence SRP is a cytosolic particle that transiently binds to the endoplasmic reticulum (ER) signal sequence in a nascent protein, to the large ribosomal unit, and to the SRP receptor in the ER membrane.


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3721280/figure/A013334F1/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3721280/

but I can stick with "protein targeting to ER" until the primary papers are curated, and I'll update the orthologs then....
