### ISSUE TITLE
GO annotations being "projected" by Ensembl back onto same species?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12870]
Should IEA GO annotations be "projected" by Ensembl back onto same species? e.g.  Q4VAE3	
Tmem65 (mouse) GO:0003231	
cardiac ventricle development IEA	
GO_REF:0000107	
with/from field: UniProtKB:Q4VAE3|ensembl:ENSMUSP00000071984
Which appears to be the same gene in the same species, apparently inferred from an IMP annotation of the same gene?
Shouldn't these projections only be inferred for homologs in a different species? Or am I missing something?

**Comment by tberardini** [comment]
Please move this to the annotation tracker.
https://github.com/geneontology/go-annotation

**Comment by tberardini** [comment]
@Pauldenny - you can close this one when you've opened the item in the annotation tracker.  Thanks.

**Comment by tberardini** [comment]
Moved to the annotation tracker. https://github.com/geneontology/go-annotation/issues/1488
