### ISSUE TITLE
antifreeze activity term

### ISSUE THREAD

**Issue by happy-lorna** [geneontology/go-ontology#12877]
We have a need for a term something like the obsoleted "antifreeze activity" (GO:0016172), as we have a number of proteins for which we do not currently have an appropriate term.

In the case of ice structuring protein A in the winter flounder (P04002), the protein (which binds to ice-crystal surfaces, thus lowering the freezing point) is expressed seasonally, and prevents freezing in the fish. It is therefor not a "response to freezing", but more a property the protein has innately. The term "homoiothermy" was also disputed by a user for this protein as the protein lowers the freezing point non-colligatively (by binding to ice-crystals), and so cannot be described as being involved in temperature regulation as described for homoiothermy.

I can see that the original term was obsoleted as it was considered to be a biological process, rather than a molecular function. Is it possible to have this term reinstated as a biological process term?

PMID:6952188
PMID:3769927

**Comment by ukemi** [comment]
Will 'response to freezing' GO:0050826 work? It's synonyms suggest it was meant as a replacement to the function term.

**Comment by ukemi** [comment]
It looks like 'ice binding' might be an appropriate molecular function as well, see synonyms.

**Comment by ukemi** [comment]
I'm not sure I follow, even though the protein exists seasonally, that is expression data. Doesn't the protein still function in the process of responding to freezing?

**Comment by ukemi** [comment]
Closing this one assuming that the annotations were made to the other terms.
