### ISSUE TITLE
create new term request Telomeric DNA-containing Double Minutes (TDMs) formation (or suggestion)

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12879]
suggested definition: A telomere maintenance process that results in the formation of small fragments of circular extrachromosomal DNA elements which contain telomeric DNA. It is speculated that TDMs are formed through a recombination event between the telomere and chromosome-internal TTAGGG-like sequences. TDMs appear as two closely positioned dots in metaphase.

child of: GO:0000722 telomere maintenance via recombination (or suggestion)

PMID: 14690602
PMID: 2397458

GOC:nc
GOG:BHF
GOC:BHF_telomere

**Comment by ukemi** [comment]
[Term]
+id: GO:0061819
+name: telomeric DNA-containing double minutes formation
+namespace: biological_process
+def: "A telomere maintenance process that results in the formation of small fragments of circular extrachromosomal DNA elements which contain telomeric DNA. It is speculated that telomeric DNA-containing double minutes are formed through a recombination event between the telomere and chromosome-internal TTAGGG-like sequences. Telomeric DNA-containing double minutes appear as two closely positioned dots in metaphase." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:14690602, PMID:2397458]
+synonym: "TDMs formation" EXACT []
+is_a: GO:0000722 ! telomere maintenance via recombination
+created_by: dph
+creation_date: 2016-12-20T09:49:03Z
