### ISSUE TITLE
create new term request D-loop (disassembly?) or (resolution?)

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12881]
suggested definition: A telomere maintenance process that results in the resolution (or disassembly?) of D-loops. A D-loop is a three-stranded DNA displacement loop that forms at the site where the telomeric 3' single-stranded DNA overhang (formed of the repeat sequence TTAGGG in mammals) is tucked back inside the double-stranded component of telomeric DNA molecule, thus forming a t-loop or telomeric-loop and protecting the chromosome terminus.

child of: GO:0090657 telomeric loop disassembly (or suggestions). Note: D-loop is part of the telomeric loop - or t-loop - so the D-loop needs to be resolved first for the telomeric loop resolution to follow see reference review 10338204.

or,

child of: GO:0000723 telomere maintenance (??)

synonyms: 
Displacement loop disassembly (or resolution?)
Displacement-loop disassembly (or resolution?)

PMID: 24012755
PMID: 10338204 (review)

GOC:nc
GOG:BHF
GOC:BHF_telomere

**Comment by srengel** [comment]
D-loops are not specific to telomeric DNA.  they can occur on mitochondrial DNA also.  just something to keep in mind for correct naming and definition of this term.  some clarification at the outset (when creating the term) is probably good.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061820
+name: telomeric D-loop disassembly
+def: "A telomere loop disassembly process that results in the disassembly of telomeric D-loops. A telomeric D-loop is a three-stranded DNA displacement loop that forms at the site where the telomeric 3' single-stranded DNA overhang (formed of the repeat sequence TTAGGG in mammals) is tucked back inside the double-stranded component of telomeric DNA molecule, thus forming a t-loop or telomeric-loop and protecting the chromosome terminus." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:10338204, PMID:24012755]
+is_a: GO:0090657 ! telomeric loop disassembly
+created_by: dph
