### ISSUE TITLE
create new terms request oxidised deoxyguanosine DNA binding and more specific child

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12884]
1. oxidised deoxyguanosine DNA binding 
suggested definition: Interacting selectively and non-covalently with oxidized deoxyguanosine residues in DNA. 

child of: GO:0032357 oxidized purine DNA binding (? or better)

synonyms:
oxidised dG DNA binding
 
2. single-stranded oxidised deoxyguanosine-rich DNA binding
suggested definition: Interacting selectively and non-covalently with single-stranded oxidized deoxyguanosine-rich DNA sequences. 

child of: above new term 1
and,
GO:1990955 G-rich single-stranded DNA binding

(or better)

synonyms:
single-stranded oxidised dG-rich DNA binding

PMID: 19734539

GOC:nc
GOG:BHF
GOC:BHF_telomere

**Comment by ukemi** [comment]
If we are going to create these, we need to see if they are in CHEBI and we should create them with TermGenie.

**Comment by NancyCampbell** [comment]
CHEBI:40304 - 8-hydroxy-2'-deoxyguanosine
Guanosine substituted at the purine 8-position by a hydroxy group. It is used as a biomarker of oxidative DNA damage.

synonym 8-Oxo-2'-deoxyguanine 

Created on TG but the reasoner put as child of  GO:0032550 purine ribonucleoside binding
**not**  GO:0032357 oxidized purine DNA binding child of GO:0003684 damaged DNA binding. 8-hydroxy-2'-deoxyguanosine is 'damaged DNA'.

**Comment by ukemi** [comment]
I have commited the term as you created it and I am going to try to modify it once it is committed. It certainly is a child of GO:0032550, but I think if I play around with changing the genus to a specific damaged DNA binding term, we can get the reasoner to classify it correctly. If not, I will remove the logical def and assert its place in the ontology by hand.

**Comment by ukemi** [comment]
Ended up hand placing the term.

[Term]
id: GO:1905773
name: 8-hydroxy-2'-deoxyguanosine DNA binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with 8-hydroxy-2'-deoxyguanosine an oxidized purine residue found in damaged DNA." [GO_REF:0000067, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:19734539]
is_a: GO:0032357 ! oxidized purine DNA binding
is_a: GO:0032550 ! purine ribonucleoside binding
created_by: NancyCampbell
creation_date: 2016-12-21T15:57:27Z

**Comment by dosumis** [comment]
ChEBI error allegedly fixed - https://github.com/ebi-chebi/ChEBI/issues/3224

but still not showing up here:

https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_15422

(May need to wait for monthly release).

**Comment by cmungall** [comment]
Correct, we don't take the snapshots

**Comment by ukemi** [comment]
made request for CHEBI:40304 in imports_requests.obo

Will make the logical def once this CHEBI term is available again.

**Comment by cmungall** [comment]
was in the chebi jan release, so we now have it:

```
$ obo-grep.pl -r CHEBI:40304 chebi_import.obo
format-version: 1.2
default-namespace: external
ontology: go/extensions/chebi_import

[Term]
id: CHEBI:40304
name: 8-hydroxy-2'-deoxyguanosine
is_a: CHEBI:24458 ! guanosines
relationship: has_role CHEBI:59163 ! biomarker
```
