### ISSUE TITLE
MP GO:0004665	prephenate dehydrogenase (NADP+) activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12882]
child of

GO:0008977	prephenate dehydrogenase activity?

**Comment by ukemi** [comment]
According to the definition, GO:0008977 uses NAD+. GO:0004665 uses NADP+

**Comment by ValWood** [comment]
OK I didn't read the def ;( rule 1

Can the term name be altered....I am picking up a mapping to the "NAD" term on my NADP
(or my annotation is incorrect....)

**Comment by ukemi** [comment]
id: GO:0008977
-name: prephenate dehydrogenase activity
+name: prephenate dehydrogenase (NAD+) activity
