### ISSUE TITLE
create new terms request telomeric D-loop binding

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12885]
suggested definition: Interacting selectively and non-covalently with a telomeric D-loop. A telomeric D-loop is a three-stranded DNA displacement loop that forms at the site where the telomeric 3' single-stranded DNA overhang (formed of the repeat sequence TTAGGG in mammals) is tucked back inside the double-stranded component of telomeric DNA molecule, thus forming a t-loop or telomeric-loop and protecting the chromosome terminus

child of: GO:0000217 DNA secondary structure binding (? or better)

synonyms:
telomeric Displacement-loop binding

PMID: 19734539

GOC:nc
GOG:BHF
GOC:BHF_telomere

**Comment by ukemi** [comment]
[Term]
+id: GO:0061821
+name: telomeric D-loop binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a telomeric D-loop. A telomeric D-loop is a three-stranded DNA displacement loop that forms at the site where the telomeric 3' single-stranded DNA overhang (formed of the repeat sequence TTAGGG in mammals) is tucked back inside the double-stranded component of telomeric DNA molecule, thus forming a t-loop or telomeric-loop and protecting the chromosome terminus." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:19734539]
+synonym: "telomeric Displacement-loop binding" EXACT []
+is_a: GO:0000217 ! DNA secondary structure binding
+created_by: dph
