### ISSUE TITLE
L-methionine biosynthetic process from methionine sulphoxide -> methionine salvage?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12888]
O:1990355
Name	L-methionine biosynthetic process from methionine sulphoxide

should this be renamed 

	L-methionine salvage from methionine sulphoxide

and the biosynthesis parent removed?

**Comment by deustp01** [comment]
Tangential question: Is there a good definition to distinguish biosynthesis from salvage, something that could be worked into the computable logic? Or do we need to rely on the conventional usages of enzymologists?

**Comment by ValWood** [comment]
Currently its
Any process which produces a x, from derivatives of it without de novo synthesis.

but that rides on how de novo synthesis is defined

Biosynthesis is
The chemical reactions and pathways resulting in the formation of substances; typically the energy-requiring part of metabolism in which simpler substances are transformed into more complex ones.

Would salvage always involve "The chemical reactions resulting in the formation of substances via the breakdown or transformation of compounds obtained dietarily or as intermediates  from catabolic pathways.

Note I am not exactly sure if the above reaction is salvage, but it has the salvage term as an exact synonym.

**Comment by tberardini** [comment]
@hdrabkin : can you weigh in on this one please?

**Comment by hdrabkin** [comment]
Looking at some diagrams for "methionine salvage pathways"; cycles are pretty complex. I guess one could argue it depends on where you enter the cycle.
Do we need to specify: methionine biosynthesis via aspartate? methionine biosynthesis via methyl-thio-adenosine. In those organisms that have the MTA salvage, do they also synthesis via aspartate. 
From what I can see, the treatment of methionine sulfoxide seems to occur at the residue level while it is in a protein (via MSRA and MSRB)? Peter?

**Comment by ukemi** [comment]
#11890

**Comment by ukemi** [comment]
This issue looks more fundamental. All salvage in GO is a type of biosynthesis. GO:0043094 (cellular metabolic compound salvage) is a type of GO:0044249 (cellular biosynthetic process). This seems wrong to me. I think if we simply make salvage a metabolic process, then it will solve this issue. Looking through my old biochemistry textbooks, it doesn't look like salvage is considered to be biosynthesis (whew).  This may also be impacted by a general cleanup of the high-level metabolism terms where any output of a biosynthetic process is classified as a type of 'x biosynthetic process'. This causes problems when describing pathways. It's a very old problem, but one that would be really nice to solve.

**Comment by ukemi** [comment]
PS. The term that Val mentions above is a child of L-methionine salvage, so I think her rename is perfectly sensible.

**Comment by ValWood** [comment]
Yep..and it is an exact synonym (although probably biosynthesis and salvage should not ever be exact synonyms?)

**Comment by ukemi** [comment]
OK. I renamed all of the children of the salvage term to be salvage instead of biosynthesis and removed the synonyms. I still think we should move GO:0043094 (cellular metabolic compound salvage) out from under biosynthesis and just make it a metabolic process. Tanya agrees. Is this the general consensus of the biochemistry group @hdrabkin @deustp01 ?

**Comment by hdrabkin** [comment]
I think that would help in avoiding confusion to move it out from biosynthesis as you suggest.

**Comment by ValWood** [comment]
+1

**Comment by ukemi** [comment]
OK. I made all salvage a type of metabolic process rather than a type of biosynthetic process.
