### ISSUE TITLE
Protege documentation needs updating and ID issue

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12880]
I was creating a new term in Protege this morning and noticed that there is still the issue of Protege trying to use secondary identifiers to create new terms. This is a stopper for anyone who has worked on GO for a long time, because it requires a very error-prone hand edit to the new term. How do others solve this problem?

I also noticed that the documentation on the wiki seems to be out of date. When creating a new term, the dc:creator and dc:date properties seem to be incorrect for creating an obo stanza after conversion. I believe those properties should be created_by and creation_date.

**Comment by dosumis** [comment]
> I was creating a new term in Protege this morning and noticed that there is still the issue of Protege trying to use secondary identifiers to create new terms. This is a stopper for anyone who has worked on GO for a long time, because it requires a very error-prone hand edit to the new term. How do others solve this problem?

This is meant to be fixed by the generation of obsolete entities from all alt_ids.  

> I also noticed that the documentation on the wiki seems to be out of date. When creating a new term, the dc:creator and dc:date properties seem to be incorrect for creating an obo stanza after conversion. I believe those properties should be created_by and created_by

This is meant to be configurable (see new entity metadata in preferences).  In 5.0 this is prevented by a bug.  This seems to be fixed in 5.1

**Comment by ukemi** [comment]
I have added this for discussion on tomorrow's editors' call.

**Comment by dosumis** [comment]
alt_id -> obs stanza generation appears to be working:

![image](https://cloud.githubusercontent.com/assets/112839/21357471/0f39fc70-c6cd-11e6-83d2-7823a385b427.png)

![image](https://cloud.githubusercontent.com/assets/112839/21357453/fb675aee-c6cc-11e6-97f5-f3b7e7b88e27.png)

I tested new entity addition by setting the start number to 80086.  80087 was not stomped on.

This new term was created - with correct APs for created by and creation date - so both functionalities appears to be working in Protege 5.1

![image](https://cloud.githubusercontent.com/assets/112839/21357715/2494a812-c6ce-11e6-972c-b94a1ad31ede.png)

**Comment by ukemi** [comment]
Should we all update to 5.1? I thought there were still some issues with it.

**Comment by dosumis** [comment]
There are issues with every Protege 5 release.  None of them are quite as stable as 4 was.  I feel like we've reached a steady-state of bugs.   Still, I'm managing to use it.
I have setup details on the wiki.

**Comment by dosumis** [comment]
@ukemi: If you had a re-used alt_id, I suspect the problem is with your setup, rather than Protege version.  Protege hasn't stomped on existing URIs since before Protege 4.3.

One idea: can you check you're seeing obsolete stanzas for alt_ids?  If not, check whether your catalog xml is modified.   Alternatively, is your base URI set correctly for new terms?

**Comment by ukemi** [comment]
My base URI looks ok based on the documentation. 

In my OWL file I am not seeing an obsolete stanza for the alt id (GO:0060181). It is only there as a annotation of the term into which it was subsumed. Could there be a problem with my OBO->OWL conversion?
Let's look at this on the call on Thursday.

**Comment by dosumis** [comment]
> Could there be a problem with my OBO->OWL conversion?

You should be loading the OBO file directly into Protege.  If using an old owltools for conversion, alt_ids will not be properly handled.

**Comment by ukemi** [comment]
That would explain it!

**Comment by ukemi** [comment]
Just created and committed a new term loading and saving the OBO file. Wow does that make life easier.

**Comment by ukemi** [comment]
OK. Maybe not so straightforward. No namespace added in save from Protege.

**Comment by cmungall** [comment]
> Just created and committed a new term loading and saving the OBO file. Wow does that make life easier.

Sorry, thought we were all doing this!

> OK. Maybe not so straightforward. No namespace added in save from Protege.

This has nothing to do with saving. The oboInOwl:hasOBONamespace property has no special meaning in Protege. If you want a class to have this property, you have to add it yourself. This has been true for all versions of Protege. 

We could easily do this as a post-processing step, as there is a deterministic rule for this in GO. No reason to force editors to do unneccessary work.

**Comment by ukemi** [comment]
Still need to clean up the documentation. The new documentation by David OS is nice, but there is still a lot of outdated stuff on the wiki. We should all being doing things in a consistent way.

**Comment by ukemi** [comment]
Closing this as the documentation is now available to ontology developers.
