### ISSUE TITLE
ntr: Las1 Complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12889]
suggested def, may need tweaking to match design pattern?
A  four  subunit complex, that comprises all the necessary RNA processing enzymes  (endonuclease, polynucleotide kinase, and exonuclease) to mediate  'cistronic rRNA transcript ITS2 (internal transcribed spacer) cleavage' (GO:0000448).

dbxref PMID: 26638174

synonym Las1-Grc3-Rat1-Rai1

GO:0000448 has rather a long name which seems very detailed, more like a def?

**Comment by tberardini** [comment]
@bmeldal - can you check please, o protein complex guru?  Thanks.

**Comment by bmeldal** [comment]
Thanks, Tanya. That's a nice paper, Val!
We'll get this curated asap in IntAct and CP as we are trying to complete the S.c complexes this year!

Happy New Year!

Birgit

**Comment by bmeldal** [comment]
Relationships:
is_a GO:1902555 endoribonuclease complex
is_a GO:1902911 protein kinase complex (or appropriate child)
part_of GO:0005829 cytosol
capable_of GO:0004521 endoribonuclease activity (unless it inherits that from its parent)

It also needs the MF term for the phosphorylation of the 5-prime end of 26S (by Grc3) but the kinase hierarchy is rather flat and I don't know what I'm looking for without reading more...

capable_of_part_of BPs (one or more of these):
GO:0006364 rRNA processing
GO:0000478 endonucleolytic cleavage involved in rRNA processing or one of its children (this one is part_of GO:0006364 above)

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090730
+name: Las1 complex
+namespace: cellular_component
+def: "A four subunit complex, that comprises all the necessary RNA processing enzymes (endonuclease, polynucleotide kinase, and exonuclease) to mediate 'cistronic rRNA transcript ITS2 (internal transcribed spacer) cleavage' (GO:0000448)." [GOC:vw, PMID:26638174]
+synonym: "Las1-Grc3-Rat1-Rai1" NARROW [GOC:vw]
+is_a: GO:1902555 ! endoribonuclease complex
+is_a: GO:1902911 ! protein kinase complex
+relationship: capable_of_part_of GO:0000478 ! endonucleolytic cleavage involved in rRNA processing
+relationship: part_of GO:0005829 ! cytosol
+created_by: tanyaberardini
+creation_date: 2017-01-05T16:51:46Z

**Comment by bmeldal** [comment]
@ValWood 

Do you have the correct MF term to describe this phosphorylation? It would be nice to add it in the ontology and I will need it for the complex annotation anyway. I'm just not overly familiar with these activities and the hierarchy is difficult to read when I don't know that sort of term I'm looking for ;-)

**Comment by ValWood** [comment]
It isn't well-characterised in pombe so mainly from SGD

las1 endonuclease activity
grc3 polynucleotide 5'-hydroxyl-kinase activity
rat1 5'-3' exoribonuclease activity
rai1 RNA pyrophosphohydrolase activity

**Comment by bmeldal** [comment]
@tberardini 
Can we add the following relationships, please:
is_a GO:1905354 exoribonuclease complex
capable_of GO:0004521 endoribonuclease activity
capable_of GO:0051731 polynucleotide 5'-hydroxyl-kinase activity
capable_of GO:0004534 5'-3' exoribonuclease activity

Thanks,
Birgit

**Comment by tberardini** [comment]
+is_a GO:1905354 exoribonuclease complex
+relationship: capable_of GO:0051731 polynucleotide 5'-hydroxyl-kinase activity
+relationship: capable_of GO:0004534 5'-3' exoribonuclease activity


The term inherits the 
capable_of GO:0004521 endoribonuclease activity
relationship through the  is_a: GO:1902555 ! endoribonuclease complex parent.

**Comment by bmeldal** [comment]
Thanks :)
