### ISSUE TITLE
GO:0005952 cAMP-dependent protein kinase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12898]
Def: An enzyme complex, composed of regulatory and catalytic subunits, that catalyzes protein phosphorylation. Inactive forms of the enzyme have two regulatory chains and two catalytic chains; activation by cAMP produces two active catalytic monomers and a regulatory dimer.

I have a slight problem with the term name referring to a kinase but the complex description is the inactive form of the kinase that it is bound to its regulator which inhibits the kinase function.

Birgit

Note to self: CP complexes are ready for release (e.g. EBI-11963349).

**Comment by ukemi** [comment]
But isn't that what the complex is called?

**Comment by ukemi** [comment]
Can you think of a better name? Adding supercomplex just seems weird. But your point is completely valid. In the ontology, this complex is defined as a 'macromolecular complex capable of some cAMP-dependent protein kinase activity'. Based on the textual definition, this is incorrect if the complex always has the inhibitors associated with it. It is one of the reasons why we need to be very careful about logical definitions. So how do we distinguish this complex from the active monomers in the label?

**Comment by bmeldal** [comment]
What about 'cAMP-dependent protein kinase **regulatory** complex'?

Good spot on the dependencies, I hadn't even noticed that (and I'm normally quite vigilant...)!

**Comment by bmeldal** [comment]
We could have capable_of GO:0019887 protein kinase regulator activity

There isn't a suitable complex parent but We can make the equivalent CC term from the above MF term. I think you have to create the term through, TG is still (?) down... (what the story now with TG???)

**Comment by ukemi** [comment]
But according to the def above, it is the dimer that is the regulatory complex isn't it? So the complex containing the two active monomers and the regulatory dimer isn't really regulatory. 

How about 'cAMP-dependent protein kinase holoenzyme'?  PMID:10922298

**Comment by bmeldal** [comment]
'holoenzyme' still implies it's active, at least to me. We have a bunch of holoenzymes in GO and the ones I have seen are catalytically active. It often denotes that it contains additional subunits compared to its core complex. It may also distinguish them from a core complex that might be a stable but inactive assembly intermediate.

Or, even worse/confusing, a bucket term for cyclin-dependent CDKs: GO:0000307 cyclin-dependent protein kinase holoenzyme complex! It's child terms are the specific enzyme complexes...

The regulatory dimer on it's own doesn't do anything. It inhibits the kinase activity of the enzyme under low cAMP conditions when it binds 2 enzyme units per regulatory dimer. So the the actual regulatory complex is the tetramer. But that's just the way I interpret it.

Not sure what to do but in any case, I would remove the relationship to the kinase activity and replace it with a relationship to the regulatory activity :)

**Comment by ukemi** [comment]
OK. I left the name as it is and made these edits:

+is_a: GO:0032991 ! macromolecular complex
 is_a: GO:0044424 ! intracellular part
-intersection_of: GO:0032991 ! macromolecular complex
-intersection_of: capable_of GO:0004691 ! cAMP-dependent protein kinase activity
+relationship: capable_of GO:0004862 ! cAMP-dependent protein kinase inhibitor activity

**Comment by bmeldal** [comment]
Thanks :)
