### ISSUE TITLE
ntr  CENP-A containing nucleosome disassembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12893]
CENP-A nucleosome disassembly
The eviction of the the histone H3 variant CENP-A from centromeric chromatin at the end of mitosis, or from non-centromeric heterochromatin 
PMID:27666591

"How the particular CENP-A/H3 ratio at cen- tromeres is precisely maintained is unknown. It also remains unclear how CENP-A is excluded from non-centromeric chromatin. Here, we identify Ccp1, an uncharacterized NAP family protein in fission yeast that antagonizes CENP-A loading at both centromeric and non-centromeric regions. Like the CENP-A loading factor HJURP, Ccp1 interacts with CENP-A and is recruited to centromeres at the end of mitosis in a Mis16-dependent manner. These data indicate that factors with opposing CENP-A loading activities are recruited to centromeres. Furthermore, Ccp1 also cooperates with H2A.Z to evict CENP-A assembled in euchromatin."

@vanaukenk  will this need tweaking for your funny  worm centromeres?

**Comment by tberardini** [comment]
Is there any reason not to go with the TG template?

cc_assembly_disassembly 

GO:0043505 ! CENP-A containing nucleosome is a cellular component term

**Comment by ValWood** [comment]
no, can do

**Comment by ValWood** [comment]
ID: GO:1905783 Label: CENP-A containing nucleosome disassembly

**Comment by tberardini** [comment]
Thanks, Val.  I wasn't sure if there was a specific reason you didn't want to use the template.  I've just approved your TG request.  You should get the acknowledgement email in a few minutes.

**Comment by ValWood** [comment]
No I always forget which templates are available.

Happy New Year to you!
