### ISSUE TITLE
protein localization to pericentriolar material

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12899]
Please could I have:
protein localization to pericentriolar material 
Def: A process in which a protein is transported to, or maintained at, the pericentriolar material of the centrosome.
Is_a  relation to GO:0071539 protein localization to centrosome
Ref:PMID:24385583/DOI:10.1073/pnas.1317535111
PMID:21694707/DOI:10.1038/ncomms1367

[to describe a actions of a protein that interacts with cytoplasmic (pre)-pericentriolar complexes and recruits/tethers them to centrioles.]

(or perhaps this should be "pericentriolar material assembly: A process that results in the recruitment, assembly or stabilization of constituent parts of the pericentriolar material of the centrosome.", but I think the former is more accurate for the papers I am looking at).

And, could we add a relation between these two terms:
GO:0071539 protein localization to centrosome and GO:0051297 centrosome organization ?

Thanks,
Helen

**Comment by ukemi** [comment]
Hi Helen,

Either of these can be made in TermGenie. Let me know if you want me to create them. 

As for this:

> And, could we add a relation between these two terms:
>GO:0071539 protein localization to centrosome and GO:0051297 centrosome organization ?

I'm not sure that we can make this because all of the localization would not necessarily be part of the organization. Can't there be separate proteins that are localized there independent of organization?

-D

**Comment by hattrill** [comment]
Hi David,
Ok - I'll have a go with TermGenie and let you know how I get on!

And, hmmm - yes, I guess that localization and organisation are separable - probably best captured as an extension. So leave as is.

**Comment by hattrill** [comment]
Added via  TG: GO:1905793 Label: protein localization to pericentriolar material
