### ISSUE TITLE
gene_ontology_write includes incorrect SubPropertyOf axioms causing incoherency

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12896]
* immediate-transformation-of SubPropertyOf immediately_preceded_by
 * transformation-of SubPropertyOf preceded_by

This introduces an incoherency, since the domain/range of the former is continuant and occurrent for the latter.

This ends up breaking everyone's GAF inferences, as mentioned here:
https://github.com/geneontology/go-annotation/issues/1487

The source of this issue is an old version of RO, @balhoff pointed this out here: https://github.com/oborel/obo-relations/issues/126 -- fixed in RO, but there is a zombie relation kicking around.

We need to

 1. [x] Remove the incorrect axioms
 2. [ ] Avoid zombie relations
 3. [x] Better detect incoherencies upstream

I will do 1, trivial.

For 2, I suspect this came from an old version of RO that was itself MIREOTed into an ontology that GO imports. Due to our hack to support OE, we end up injecting these into the editors file until they are manually cleared. Long term fix is to switch to Protege.

For 3, the problem here is that technically the ontology is not incoherent until these relations are actually *used*. This means we end up not catching them as part of the normal ontology development cycle, and they show up in everyone's GAF inferences, which is confusing for everyone.

What we need is a check of "unsatisfiable Object Properties". This is noted in this robot ticket: https://github.com/ontodev/robot/issues/104

**Comment by tberardini** [comment]
Here's what I did with today's save (Committed revision 37915.)

immediate-transformation-of 
-is_a: immediately_preceded_by ! immediately_preceded_by

transformation-of 
-is_a: preceded_by ! preceded by

**Comment by mcourtot** [comment]
For 2, should we just strip non desired URIs? Eg if mireoting SO, strip out all non SO IDs - that should remove zombie RO terms.

**Comment by cmungall** [comment]
We'd need a new robot ticket for the unmireot operation. It's not ideal as it hardcodes assumptions about ID and ownership.

I'll close this for now, we already have an open ticket about the new github pipeline

(btw, 3 is done, https://github.com/ontodev/robot/issues/104)
