### ISSUE TITLE
def change and NTR: GO:0045251 electron transfer flavoprotein complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12895]
GO:0045251 electron transfer flavoprotein complex
Def: A protein complex containing flavin adenine dinucleotide (FAD) and acyl-CoA dehydrogenase, which form a system that oxidizes an acyl-CoA molecule and reduces ubiquinone and other acceptors in the mitochondrial electron transport system. 

2 problems:
a) This complex occurs in both, mitochondria and the cytosol (esp in bacs!). "mitochondrial" should therefore be removed from the Def. In fact, the term has the 2 specific child terms anyway :)

b) acyl-CoA dehydrogenase is not part of the ETF complex, it docks to it (and a variety of other dehydrogenases that act as electron acceptors). BUT, many of the proteins annotated to this term are these acceptor dehydrogenases. There are 2 options:

i) broaden the term to include both, the core ETF complexes and those containing dehydrogenases, or
ii) broaden this term to include the dehydrogenases (= electron transfer flavoprotein-ubiquinone oxidoreductase complex) and create a new term for the core ETF complex.

Nice review: PMID:17941859
Experimental paper: PMID:25416781

IntAct xrefs: EBI-9024420 (human), EBI-12592282 (mouse) - both ready-for-release [so I can find the entries again once this ticket is resolved!]

Birgit

**Comment by tberardini** [comment]
I've done step one, removing the reference to 'mitochondrial' in the definition of the term.  

Do you have a preference for either of the two options, @bmeldal ? I think that the existing annotations to GO:0045251 will be correct regardless of the course of action.  I leave the choice to you.  Please provide the updated definition for the existing term if you choose option 1 or an updated definition for the existing term AND a new term proposal for the core ETF complex if you select option 2.

Thanks very much for your help.

**Comment by bmeldal** [comment]
Hi Tanya,

I had another look at the GPs annotated to this term and it's been an enlightening journey even though it has taken the best part of today! 

There are no manual, experimental annotations at all to the parent term or the two children (mitochondrial and cytosolic). Neither are there any electronic annotations...

GO:0045247 cytosolic electron transfer flavoprotein complex has no annotations at all! But has been created in 2002 specifically for bacteria... (when its sibling GO:0017133 mitochondrial electron transfer flavoprotein complex was restricted to mitochondria)

The manual annotations to the parent term GO:0045251 electron transfer flavoprotein complex appear to be the same as those on the mitochondrial child GO:0017133 mitochondrial electron transfer flavoprotein complex. A few are ISS and TAS, most are IBAs from Panther (a DB I don't use but I assume it's a bulk-annotation thing done in Paint on one branch of the tree). 

The biochemistry, in a nutshell:
1. acyl-CoA dehydrogenase binds to the ETF complex reducing FAD(3-) to FADH2(2-) while beta-oxidizing a fatty acyl-CoA. See EC 1.3.8.7, Reactome R-HSA-169260, e.g. P11310 (human)

2. electron transfer flavoprotein-ubiquinone oxidoreductase / electron-transferring-flavoprotein dehydrogenase (lots of names...) oxidizes FADH2(2-) of ETF complex to FAD(3-) while reducing ubiquinone to ubiquinol. See EC 1.5.5.1, Reactome R-HSA-169270, e.g. Q16134 (human)

It appears all the proteins that are annotated to GO:0045251 & GO:0017133 are from Trembl, most are the ETF-ubiquinone oxidoreductases from reaction 2 and some ETF core subunits. The ETF subunits could belong to either reaction.

So, here's the rub: 
1. The ETF-ubiquinone oxidoreductases are single proteins so shouldn't be annotated to a complex term!
2. The Def of GO:0045251 refers to the acyl-CoA dehydrogenase-ETF super-complex of reaction 1 but I haven't found any acyl-CoA dehydrogenases among the annotated protein (I opened a fair few but not all 134).
3. The ETF subunits fit the bill as they form a complex and are involved in the general pathway. They could bind the acyl-CoA dehydrogenases as described in the current Def but I'm intrigued why none of those proteins are annotated to this term.

Simplest solution
1. Change the Def to refer to the ETF complex.
2. Remove the annotations for ETF-ubiquinone oxidoreductases (and acyl-CoA dehydrogenase if there should be any).

GO:0045251 
Name: electron transfer flavoprotein complex
-Def: A protein complex containing flavin adenine dinucleotide (FAD) and acyl-CoA dehydrogenase, which form a system that oxidizes an acyl-CoA molecule and reduces ubiquinone and other acceptors in the mitochondrial electron transport system.
+Def: A protein complex facilitating the electron transfer from an acyl-CoA molecule to ubiquinone via its flavin adenine dinucleotide (FAD) cofactor. Usually contains an alpha and a beta subunit and the structural cofactor adenosine monophosphate (AMP). Part of a system that oxidizes an acyl-CoA molecule and reduces ubiquinone and other acceptors in the electron transport system.
+Synonym: ETF complex
+possibly: capable_of GO:0009055 electron carrier activity???

Enjoy your weekend!

Birgit

**Comment by tberardini** [comment]
> Remove the annotations for ETF-ubiquinone oxidoreductases (and acyl-CoA dehydrogenase if there should be any).

 Should we just alert all dbs and the PAINT team that have/created annotations to GO:0045251?

I'll edit the definition of GO:0045251 as you suggested and add the new capable_of relationship.

**Comment by tberardini** [comment]
-def: "A protein complex containing flavin adenine dinucleotide (FAD) and acyl-CoA dehydrogenase, which form a system that oxidizes an acyl-CoA molecule and reduces ubiquinone and other acceptors in an electron transport system." [ISBN:0198506732]
+def: "A protein complex facilitating the electron transfer from an acyl-CoA molecule to ubiquinone via its flavin adenine dinucleotide (FAD) cofactor. Usually contains an alpha and a beta subunit and the structural cofactor adenosine monophosphate (AMP). Part of a system that oxidizes an acyl-CoA molecule and reduces ubiquinone and other acceptors in the electron transport system." [GOC:bm, ISBN:0198506732]
+synonym: "ETF complex" EXACT [GOC:bm]
+relationship: capable_of GO:0009055 ! electron carrier activity

**Comment by tberardini** [comment]
Ontology work done.  I've opened an annotation ticket to track the related work.

https://github.com/geneontology/go-annotation/issues/1501

**Comment by bmeldal** [comment]
Thanks, Tanya. I'm following the new ticket :)
