### ISSUE TITLE
Transcription occurs_in nuclear chromatin 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12892]
Hi

at the LA GOC meeting it was agreed that GO editors would create occurs_in relation between RNA polymerase II GO terms and nuclear chromatin (as all RNA pol II transcription occurs in nucleus)

I think this is only relevant for the molecular function RNA polymerase II GO terms

Thanks

Ruth

@rachhuntley @BarbaraCzub

**Comment by krchristie** [comment]
It might be equally relevant for RNAP I, RNAP III, and also the plant-only RNAP IV and RNAP V as all of these RNA polymerases, like RNAP II, are nuclear.

**Comment by tberardini** [comment]
I can add the occurs_in relationship to nuclear chromatin for RNAP I, II, III, IV, and V and leave the other children under DNA-directed 5'-3' RNA polymerase activity as is.  Does that sound reasonable?

<img width="585" alt="screen shot 2017-01-04 at 9 16 55 am" src="https://cloud.githubusercontent.com/assets/4998871/21651743/b1259af2-d25e-11e6-9737-11a93176fdb4.png">

**Comment by krchristie** [comment]
Seems reasonable to me. I'm not sure I've ever seen any work on chromatin transcription for the the nuclear RNAP's other than II, but seems they would have to be dealing with chromatin since they are nuclear.

**Comment by tberardini** [comment]
- [ ]  add the occurs_in relationship to nuclear chromatin for RNAP I, II, III, IV, and V

**Comment by rachhuntley** [comment]
Hi Tanya,

I think the original intention for this ticket was to add occurs_in relationships between nuclear chromatin and "RNA polymerase II transcription factor activity, sequence-specific DNA binding" term, as it was discussed in the context of how to annotate transcription factors (presumably you can make the connection to the RNA pol I and II TF activity terms as well?).

On a related note, could you add the occurs_in relationship between "mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding" and "mitochondrial nucleoid"?

Thanks,
Rachael.

**Comment by tberardini** [comment]
Reopening.  Will leave open for a bit so @krchristie or others to comment, if desired.  I did not know about the desire to link 'nuclear chromatin' and the RNA pol II TF activity term as that was not explicitly mentioned in the ticket.

**Comment by rachhuntley** [comment]
Thanks Tanya, Yes I had to clarify with Ruth that this is what was agreed as we had been discussing this in the context of TF all along!

**Comment by krchristie** [comment]
I have no objection to also adding occurs_in relationships between nuclear chromatin and the "RNA polymerase ____ transcription factor activity, DNA binding" terms for any transcription factor terms for the nuclear RNA polymerases I, II, III, IV, and V, since all of these are in the nucleus.

Where both general DNA binding and sequence-specific DNA binding terms exist, I think the links should be made at the most general level since all the DNA binding by the transcription factors of the nuclear RNA polymerases in vivo is happening in the context of nuclear chromatin, even if the binding that is to the DNA backbone and thus not sequence specific.

**Comment by tberardini** [comment]
@krchristie : I don't see any general DNA binding terms of this pattern.  There are only these:

RNA polymerase I transcription factor activity, sequence-specific DNA binding
RNA polymerase II transcription factor activity, sequence-specific DNA binding
RNA polymerase III transcription factor activity, sequence-specific DNA binding

I will link all three to nuclear chromatin using occurs_in.

**Comment by tberardini** [comment]
+relationship: occurs_in GO:0000790 ! nuclear chromatin for all three
