### ISSUE TITLE
sperm head

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12909]
I would like to see "sperm head” added to the GO ontology under the parent term "sperm part” (GO:0097223). The definition could be "The part of the late spermatid or spermatozoon that contains the nucleus and acrosome.” Examples can be found in PMID:22797892, PMID:24665388.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061827
+name: sperm head
+namespace: cellular_component
+def: "The part of the late spermatid or spermatozoon that contains the nucleus and acrosome." [PMID:22797892, PMID:24665388]
+is_a: GO:0097223 ! sperm part
+created_by: dph
+creation_date: 2017-01-15T10:39:00Z
