### ISSUE TITLE
TPV T-cell differentiation  in thymus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12904]
I was doing some annotation intersections last night  some condensin complex  become annotated to the slim term adhesion.

This seemed  odd, and it appears they are generated by this parentage:

![adhesion](https://cloud.githubusercontent.com/assets/7359272/21810990/d1b9fbb4-d745-11e6-9e9a-a84c9bd88274.jpg)

 Is all T-cell differentiation part of adhesion (or indeed any at all?). I know nothing about this but it seems wrong for t-cell differentiation to be part of aggregation?

**Comment by ukemi** [comment]
This seems odd to me too. @addiehl can you give us a quick sanity check please?

**Comment by ukemi** [comment]
It seems that 'T cell aggregation' has the logical def; leukocyte activation and has_participant some T cell. I think this was a typo. It should be leukocyte aggregation and has_participant some T cell.

**Comment by addiehl** [comment]
I agree with David's diagnosis of the problem and agree with his suggested fix.

**Comment by ukemi** [comment]
Fix committed. Thanks Alex and Val.
