### ISSUE TITLE
New insect spermatid ciliary terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12903]
Could I have these terms related to insect spermatid ciliary structures? I've run these by Bénédicte Durand, http://www.inmg.fr/en/eq_durand.php and she is happy with them.

Cellular Component Terms: 

NTR:Ciliary cap
Def:An intracellular compartmentalized cilium structure found in insect spermatids which is bounded by a membrane derived from the invagination of the cell membrane that remains associated with the primary cilium as it is internalized. The ciliary cap is maintained at the end of the axoneme distal to the centriole and is separated from the cytosolic axoneme/cytoplasm by a putative transition zone, which may extend into the ciliary cap, and include a structure at the base of the ciliary cap termed the ring centriole.
Exact Synonym:Spermatid Ciliary Cap
Ref:PMID:27646273, PMID:25447994
Is_a: GO:0044441 ciliary part
taxon restriction: only_in Insecta NCBI Taxonomy ID:50557

NTR:Ring centriole
A ring-like structure observed at the base of the ciliary cap of insect spermatids. This structure may anchor the axomene to the ciliary cap membrane and/or act as a diffusion barrier, proposed to be analogous to the annulus of mammalian sperm flagellum.
Ref:PMID:4903810
    PMID:25447994
Is_a: GO:0044441 ciliary part
taxon restriction: only_in Insecta NCBI Taxonomy ID:50557
(BTW: just to note that this is not a centriole-like thing)

Cellular Process Term:
Cytosolic ciliogenesis
The process in which an axoneme is exposed entirely or partially to the cytoplasm or by which the cytoplasmic portion is assembled or extended. Cytosolic ciliogenesis can occur following compartmentalized ciliogenesis.
Synonym:Intracellular ciliogenesis
Ref:PMID:26654377
Notes:Cytosolic ciliogenesis occurs in Giardia flagella, Plasmodium microgametes and during mammalian & Drosophila spermatocytogensis
Is_a: GO:0060271 cilium assembly

**Comment by ukemi** [comment]
@krchristie @paolaroncaglia 

Adding you both to this thread for comments.

**Comment by krchristie** [comment]
Thanks @ukemi  

I have no issues with these terms. They seem consistent with the paper Helen asked me about at the GOC meeting in November.

**Comment by paolaroncaglia** [comment]
Hi @ukemi and @hattrill,

Those terms are fine with me too. My only suggestion would be to expand a little on the suggested def of ‘cytosolic ciliogenesis’: where it says 
“Cytosolic ciliogenesis can occur following compartmentalized ciliogenesis”, maybe clarify that “In most cells, the cilium is formed within a compartment separated from the cytoplasm” (see abstract of PMID: 25447994), as the meaning of compartmentalized ciliogenesis, and the differentia with ‘classic’ cilium assembly,  may not be immediately clear otherwise. Thanks.

**Comment by hattrill** [comment]
Hi Paola,

That seems like a sensible addition. Thanks!

**Comment by ukemi** [comment]
[Term]
+id: GO:0061822
+name: ciliary cap
+namespace: cellular_component
+def: "An intracellular compartmentalized cilium structure found in insect spermatids which is bounded by a membrane derived from the invagination of the cell membrane that remains associated with the primary cilium as it is internalized. The ciliary cap is maintained at the end of the axoneme distal to the centriole and is separated from the cytosolic axoneme/cytoplasm by a putative transition zone, which may extend into the ciliary cap, and include a structure at the base of the ciliary cap termed the ring centriole." [PMID:25447994, PMID:27646273]
+synonym: "spermatid ciliary cap" EXACT []
+is_a: GO:0044441 ! ciliary part
+relationship: only_in_taxon NCBITaxon:50557 ! Insecta
+created_by: dph
+creation_date: 2017-01-14T14:14:11Z
+
+[Term]
+id: GO:0061823
+name: ring centriole
+namespace: cellular_component
+def: "A ring-like structure observed at the base of the ciliary cap of insect spermatids. This structure may anchor the axoneme to the ciliary cap membrane and/or act as a diffusion barrier, proposed to be analogous to the annulus of mammalian sperm flagellum." [PMID:25447994, PMID:4903810]
+is_a: GO:0044441 ! ciliary part
+relationship: only_in_taxon NCBITaxon:50557 ! Insecta
+created_by: dph
+creation_date: 2017-01-14T14:18:29Z
+
+[Term]
+id: GO:0061824
+name: cytosolic ciliogenesis
+namespace: biological_process
+def: "The process in which an axoneme is exposed entirely or partially to the cytoplasm or by which the cytoplasmic portion is assembled or extended. Cytosolic ciliogenesis can occur following compartmentalized ciliogenesis, in which the cilium is formed within a compartment separated from the cytoplasm." [PMID:25447994, PMID:26654377]
+synonym: "intracellular ciliogenesis" RELATED []
+is_a: GO:0060271 ! cilium assembly
+created_by: dph
+creation_date: 2017-01-14T14:24:17Z
