### ISSUE TITLE
parentage of GO:0018094 protein polyglycylation and GO:0018095 protein polyglutamylation

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12907]
GO:0018094 protein polyglycylation and GO:0018095 protein polyglutamylation are both posttranslational modifications in which a chain of peptide-bonded amino acids is attached to the side-chain carboxyl group of a glutamate residue on a target protein. The most famous examples involve modification of tubulins (PMID: 25957412)

GO:0018095 protein polyglutamylation is connected to  GO:0006464 cellular protein modification process via two intervening is_a parentage steps, while GO:0018094 protein polyglycylation is connected with no intervening steps. The first longer path seems better.

**Comment by ukemi** [comment]
Easy fix! Thanks Peter.

 def: "The addition of glycyl units covalently bound to the gamma carboxyl group peptidyl-glutamic acid." [RESID:AA0201]
 subset: gosubset_prok
 xref: RESID:AA0201
-is_a: GO:0006464 ! cellular protein modification process
+is_a: GO:0018200 ! peptidyl-glutamic acid modification

**Comment by deustp01** [comment]
+is_a: GO:0018200 ! peptidyl-glutamic acid modification
Shouldn't this be GO:new ! peptidyl-glycine modification?

**Comment by ukemi** [comment]
The definition of peptidyl polyglycation is: The addition of glycyl units covalently bound to the gamma carboxyl group peptidyl-glutamic acid.

The definition of peptidyl-glutamic acid modification is: The modification of peptidyl-glutamic acid.

so isn't that correct, or am I still in hazy vacation mode?

The definition of peptidyl-glycine modification is: The modification of peptidyl-glycine.
The definition of peptidyl-amino acid modification is: The alteration of an amino acid residue in a peptide.

**Comment by deustp01** [comment]
That all looks good.
Thanks.
Peter
