### ISSUE TITLE
TPV: "GO:0005040 decoy death receptor activity" is not a receptor activity

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12901]
GO:0005040 decoy death receptor activity: Combining with an extracellular messenger (death ligand) *without transmission of the signal*. Decoy death receptors compete with death receptors for ligand binding, and do not initiate apoptosis. 
is_a: receptor activity

"GO:0004872 receptor activity": "Combining with an extracellular or intracellular messenger to initiate a change in cell activity."

**Comment by ukemi** [comment]
Probably this should be just binding (are all death ligands proteins?). Perhaps this should also have some kind of relationship that expresses the regulation of the true death receptors.

**Comment by deustp01** [comment]
Yes - binding sounds completely solid, and the effect is to sequester an entity needed for signaling and thus directly prevent signal transmission, which sounds like negative regulation of signaling to me.

**Comment by ukemi** [comment]
@paolaroncaglia do you know if these are always proteins?

**Comment by deustp01** [comment]
As long as some of the decoys are proteins, would that be OK? And even when they are not, a receptor that is a protein and that has a signaling function binds a ligand of whatever sort, whereupon that function is blocked or modulated? I can see some mechanical awkwardness if some decoy ligands are proteins and thus in scope for GO while others are not.

**Comment by paolaroncaglia** [comment]
@ukemi as far as I know, yes, death ligands are all proteins.

**Comment by ukemi** [comment]
Then we should make it a child of protein binding.

**Comment by ukemi** [comment]
name: decoy death receptor activity
 namespace: molecular_function
 def: "Combining with an extracellular messenger (death ligand) without transmission of the signal. Decoy death receptors compete with death receptors for ligand binding, and do not initiate apoptosis." [GOC:bf, GOC:ecd, PMID:10209153]
-is_a: GO:0004872 ! receptor activity
+is_a: GO:0005515 ! protein binding
+relationship: directly_negatively_regulates GO:0005035 ! death receptor activity

**Comment by ukemi** [comment]
Changed this:
+relationship: directly_negatively_regulates GO:0005035 ! death receptor activity
to this:
+relationship: negatively_regulates GO:0005035 ! death receptor activity
because I thought the former would create problems.
