### ISSUE TITLE
podosome core and ring

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12908]
I would like to see "podosome core” and "podosome ring” added to the GO ontology under the parent term "podosome” (GO:0002102).  The definitions could be "The F-actin-rich core of an adhesion structure characterized by formation upon cell substrate contact and localization at the substrate-attached part of the cell.” and “The ring structure surrounding the podosome core, containing proteins such as vinculin and talin."  Examples can be found in PMID:23158496.

**Comment by ukemi** [comment]
Hi Stan,

Presumably these are parts. What do you suggest as is_a parents?

-D

**Comment by slaulederkind** [comment]
You could use something high level like "intracellular part" (GO:0044424) or "cytoplasmic part" (GO:0044444) or create a "podosome part" parent.

**Comment by ukemi** [comment]
It would get those from being part of the podosome. The podosome is a protein complex. Maybe these should be protein complexes too.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061825
+name: podosome core
+namespace: cellular_component
+def: "The F-actin-rich core of an adhesion structure characterized by formation upon cell substrate contact and localization at the substrate-attached part of the cell." [PMID:23158496]
+is_a: GO:0044430 ! cytoskeletal part
+relationship: part_of GO:0002102 ! podosome
+created_by: dph
+creation_date: 2017-01-14T14:42:45Z
+
+[Term]
+id: GO:0061826
+name: podosome ring
+namespace: cellular_component
+def: "The ring structure surrounding the podosome core, containing proteins such as vinculin and talin." [PMID:23158496]
+is_a: GO:0044430 ! cytoskeletal part
+relationship: part_of GO:0002102 ! podosome
+created_by: dph
+creation_date: 2017-01-14T14:44:53Z
