### ISSUE TITLE
Add dc:title to ontology file

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12902]
as per https://github.com/geneontology/go-ontology/issues/12900: some external tools rely on this for their display of GO metadata

**Comment by mcourtot** [comment]
is it just a question to add the line in at some point, or are there other issues I'm not considering?

**Comment by mcourtot** [comment]
Hi @ukemi - was this discussed during the last call?

**Comment by ukemi** [comment]
Yes. I though @cmungall  had already done it.

**Comment by mcourtot** [comment]
added revision 38621.

**Comment by mcourtot** [comment]
looking at the owl file the dc namespace definition is still there, but the dc:title AP itself is missing. Lost in some round tripping?

**Comment by balhoff** [comment]
Done for #18251.
