### ISSUE TITLE
mitochondrial translation -mitochondrial organization TPV

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12919]
This is similar to

https://github.com/geneontology/go-ontology/issues/11677

Rationale:
- If transcription is not organization , translation should not be.
- It may affect organization but mostly cytochrome oxidase, ATPase subunits and  endonucleases....
seems indirect...

**Comment by ukemi** [comment]
I removed the organization parent.

**Comment by ValWood** [comment]
Yay, I got one past you.

**Comment by ukemi** [comment]
Two actually! I was reopening the chromatin one as you reopened it.
