### ISSUE TITLE
GO:0006486 protein glycosylation vs GO:0009101 glycoprotein biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12915]
GO:0006486 protein glycosylation
A protein modification process that results in the addition of a carbohydrate or carbohydrate derivative unit to a protein amino acid, e.g. the addition of glycan chains to proteins.

vs.
GO:0009101 glycoprotein biosynthetic process
Definition	The chemical reactions and pathways resulting in the formation of glycoproteins, any protein that contains covalently bound glycose (i.e. monosaccharide) residues; the glycose occurs most commonly as oligosaccharide or fairly small polysaccharide but occasionally as monosaccharide.

Is there a difference?

**Comment by ukemi** [comment]
Glycoprotein biosynthesis includes the steps to make the glycan. Protein glycosylation is the attachment of the glycan to the protein.

**Comment by ValWood** [comment]
ah got it
