### ISSUE TITLE
ntr: process to annotate 	aminoacyl-tRNA editing activity and other aminoacylation proofreading MF terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12917]
aminoacyl-tRNA editing activity

e.g. MGI:Dtd1 D-tyrosyl-tRNA deacylase 1

https://github.com/geneontology/go-annotation/issues/1493#issuecomment-272425800

Harold @hdrabkin  the tRNA oracle said:
I would not think de-acylation is a tRNA modification; certainly aminoacylation is not.
The "editing" is not tRNA editing (post transcriptional changes of the sequence), it's a term used for the check by the synthetase for the correct amino acid. Some synthetases check at the first step (aa + ATP -> aa-AMP+ PPi) . Some check at the second step, aa-AMP +tRNA -> aa-tRNA + AMP.
It is a type of translational fidelity assurance.

Harold suggested:
" aminoacyl-tRNA metabolism involved in translational fidelity”

**Comment by ValWood** [comment]
synonyms
aminoacyl-tRNA proofreading
aminoacyl-tRNA correction
aminoacyl-tRNA editing

child of "tRNA metabolism" child of "translational fidelity"

Any process which detects an amino-acid acetylated tRNA is charged with the  correct amino acid, or removes incorrect amino acids from a charged tRNA. This process can be performed by tRNA synthases, or by subsequent reactions  after tRNA aminoacylation. 


(I could be a part of translational fidelity, but I don't think it is necessary to say that in the term name)

**Comment by ukemi** [comment]
@hdrabkin comments?

**Comment by hdrabkin** [comment]
Concern: for the D-aa-tRNA case, an enzyme other than the synthetase fixes the mistake.
BUT,  some synthetases fix the mistake themselves by hydrolysis (water being used to displace the amino acid, either at the aa-AMP or the aa-TRNA step depending on the enzyme. The enzymes that can do this usually have additional domains compared to those that don't. (editing domains).

Trying to think if these will get confused with each other; 
The editing by the synthetases are not reversals, but allowing water to act as the amino acid acceptor at either step.

**Comment by hdrabkin** [comment]
I would think all of these activities are part of " regulation of translational fidelity"; probabily could go out on a limb and say POSITIVE regulation of translational fidelity

**Comment by hdrabkin** [comment]
ah, did not see " ukemi assigned hdrabkin and unassigned ukemi on Jan 20" 
Ok

**Comment by hdrabkin** [comment]
So in summary
1.make process "aminoacyl-tRNA metabolism involved in translational fidelity” NTR1)
subclass of 'regulation of translational fidelity.
2. link aminoacyl-tRNA editing activity and Gly-tRNA(Ala) hydrolase activity
to NTR1

**Comment by hdrabkin** [comment]
done
