### ISSUE TITLE
remove glycoprotein trimming terms representing molecular functions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12914]
GO:0036511	trimming of first mannose on A branch
GO:0036512	trimming of second mannose on A branch
GO:0036509	trimming of terminal mannose on B branch
GO:0036510	trimming of terminal mannose on C branch

GO:1904382	mannose trimming involved in glycoprotein ERAD pathway (this one is an MF and a process. A n annotation to the correct molecular function term
i.e. 
mannosyl-oligosaccharide 1,2-alpha-mannosidase activity involved in
GO:1904382	glycoprotein ERAD pathway

the actual moiety which is trimmed is actually *more  specific* info than we have on current MF terms, but if we want them, they should move to the MF ontology

**Comment by ukemi** [comment]
Looks like this was done on purpose based on the complexity of the biology:

#11888

**Comment by ValWood** [comment]
OK
