### ISSUE TITLE
synonym for  glycoprotein maturation  for glycoprotein trimming

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12913]
Any process leading to the attainment of the full functional capacity of a glycoprotein.

Could we add this term as a sibling of glycoprotein biosynethsis and "glycoprotein catabolism"

narrow synonym
"glycoprotein trimming"

**Comment by ValWood** [comment]
There is already a term more specific than this, 
GO:1904381 Golgi apparatus mannose trimming


but it does not get the parentage  to "glycoprotein metabolic process"


GO:0006517
Name	protein deglycosylation
needs to go under "glycoprotein metabolism"

**Comment by ValWood** [comment]
maybe this is the same?
GO:0006491 N-glycan processing

**Comment by ukemi** [comment]
We could add it, but I'm not sure we could add the other terms as children without creating possible TPVs. DO we know that the other processes are always in the context of maturation? Clearly if you look at the children of the Golgi mannose trimming term, this isn't the case.

**Comment by ValWood** [comment]
I think the issue changed after I found the  GO:0006491 N-glycan processing term.

It is now a TPV already because:
GO:0006491 N-glycan processing   is the maturation term I was looking for:

it is defined defined
The conversion of N-linked glycan (N = nitrogen) structures from the initially transferred oligosaccharide to a ****mature form****, by the actions of glycosidases and glycosyltransferases. The early processing steps are conserved and play roles in glycoprotein folding and trafficking. 

So now, a TPV to biosynthesis (assuming maturation follows biosynthesis).
The parentage should be "metabolism", not "biosynthesis?"  (At least protein maturation is only metabolism, and this seems correct)

So  need to
 - [ ]  Fix parentage GO:0006491 N-glycan processing 
- [ ]  Add synonyms   "glycoprotein trimming involved in glycoprotein maturation"
- [ ] Move any other "maturation" trimming terms to be under here (or make a more general parent to house them)
- [ ] Maybe we need  genernal "glycoprotein trimming" to group the maturation and the catabolic (they do seem to be separable at least some functions

from PMID:24519966 used for the def of 
GO:1904382 mannose trimming involved in glycoprotein ERAD pathway"

"ERManI removes the &alpha;1,2-linked mannose of the B-chain from properly folded ER glycoproteins, whereas two or more &alpha;1,2-linked mannose residues are sequentially trimmed from improperly folded glycoproteins so they are recognized by a complex that mediates ER-associated degradation (ERAD). "

It seems that logical defs would help a lot around here if they don't already have them?

**Comment by ukemi** [comment]
I agree N-glycan processing as it is defined should go under glycoprotein metabolic process to be consistent with other processing terms. 

I agree that we should add the  "glycoprotein trimming involved in glycoprotein maturation" synonym.

Don't you think we should remove the  'N-glycan catabolism' and  'N-glycan degradation' synonyms based on the definition?

The only other trimming term that always fits with respect to maturation is the Golgi one. I think the ER one is not always maturation. Do you agree? 

I don't think a general trimming term is really that useful because the hydrolysis would be covered by the function. It seems to me that the use of the process terms is to put them in a bigger contect of maturation or degradation.

**Comment by ValWood** [comment]
> Don't you think we should remove the 'N-glycan catabolism' and 'N-glycan degradation' synonyms based on the definition?

Yes

> the ER one is not always maturation. Do you agree?

Yes

> I don't think a general trimming term is really that useful because the hydrolysis would be covered by the function. It seems to me that the use of the process terms is to put them in a bigger contect of maturation or degradation.

OK,  agreed.
I think these "trimming" terms are hard to find though. These are definitely missing a parent to  "glycoprotein metabolism" too

v

**Comment by ukemi** [comment]
Moved Golgi apparatus mannose trimming to be a subclass of N-glycan processing.
Made protein deglycosylation a glycoprotein metabolic process. This should cover all the trimming terms and others. It makes sense to me to have all these grouped under glycoprotein metabolism even though they are also children of protein modification.
Let me know if you spot any weirdness.
