### ISSUE TITLE
MP chromatin organization > chromosome organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12918]
2016-09-04	Deleted	RELATION	part of GO:0051276 (chromosome organization)

Why is that?

v

**Comment by ukemi** [comment]
Because not all chromatin is found as part of a chromosome.

PMID:12799349

**Comment by ValWood** [comment]
Does this paper say this is "heterochromatin". I don't see that on a search of the paper, I only see that there are "centomeric heterochromatin sequence" 

In fact, centromeric sequence does not form "heterochromatin"  it forms "CENP-A containing chromatin" which is distinct from heterochromatin.

I think this provides us an easy way to get around this problem (which would be VERY detrimental to the chromatin community, who use GO A LOT, because they are always doing enrichments for genes in different chromosomal regions). We can tighten the definition of heterochromatin to be chromosomal, and call the other stuff something else (heterochromatin-like, if you like).

Certainly this paper does not allow us to distinguish between "heterochromatin" and "CENP-A containing chromatin" , so it can't be used  to annotate heterochromatin. Only chromatin, maybe....

**Comment by ukemi** [comment]
Reopening because chromatin is part_of chromosome in the ontology and each of these are defined axiomatically. So even though the above is true, it looks like we mean chromosomal chromatin.

**Comment by ValWood** [comment]
Exactly, so far, I think we always all mean "chromosomal chromatin" until you just showed me that paper!

**Comment by ukemi** [comment]
Hi Val,

I have been trying to think about why this was removed. I can't think of a good reason. It's possible that it was automatic due to the reasoner. I'm adding it back.
