### ISSUE TITLE
TPV protein citrullination

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12911]
Has ancestry to amino acid metabolism
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0036414#term=ancchart

**Comment by dosumis** [comment]
[The organic compound citrulline is an α-amino acid.](https://en.wikipedia.org/wiki/Citrulline)

**Comment by dosumis** [comment]
Possibly controversial link is "GO:0018101 protein citrullination" is_a citrulline biosynthetic process

"protein citrullination":  The hydrolysis of peptidyl-arginine to form peptidyl-citrulline.

It's definitely a biosynth step, but should we say to peptidyl-citrulline, not citrulline ?

**Comment by ValWood** [comment]
Yep thats the issue.
Its similar to the old https://github.com/geneontology/go-ontology/issues/11905
issue....

**Comment by ukemi** [comment]
Perhaps just keep is as a peptidyl-arginine modification?

**Comment by ukemi** [comment]
I removed the biosynthesis parent.
