### ISSUE TITLE
tubulobulbar complexes

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12910]
I would like to see "apical tubulobulbar complex” and “basal tubulobulbar complex” added to the GO ontology under the parent term "tubulobulbar complex” (GO:0036284). The definitions could be "Actin-based structures involved in establishing close contact between mature spermatids and Sertoli cells at the luminal end of the Sertoli cell.” and "Actin-based structures involved in establishing the blood-testis barrier of the Sertoli cell.”, respectively.  Synonyms: apical TBC, basal TBC.  Examples can be found in PMID:22510523, PMID:20403871 .

**Comment by ukemi** [comment]
+[Term]
+id: GO:0061828
+name: apical tubulobulbar complex
+namespace: cellular_component
+def: "Actin-based structures involved in establishing close contact between mature spermatids and Sertoli cells at the luminal end of the Sertoli cell." [PMID:20403871, PMID:22510523]
+synonym: "apical TBC" EXACT []
+is_a: GO:0036284 ! tubulobulbar complex
+created_by: dph
+creation_date: 2017-01-15T10:41:00Z
+
+[Term]
+id: GO:0061829
+name: basal tubulobulbar complex
+namespace: cellular_component
+def: "Actin-based structures involved in establishing the blood-testis barrier of the Sertoli cell." [PMID:20403871, PMID:22510523]
+synonym: "basal TBC" EXACT []
+is_a: GO:0036284 ! tubulobulbar complex
+created_by: dph
+creation_date: 2017-01-15T10:42:31Z
