### ISSUE TITLE
TVP chromatin -> macromolecular complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12916]
This doesn't look right does it?

**Comment by ValWood** [comment]
includes terms like "heterochromatin island"
and "telomeric heterochromatin"

**Comment by ukemi** [comment]
Looks right to me. Macromolecular complex will become protein-containing complex once I do the edits in #12782.

**Comment by ValWood** [comment]
I don't think many biologists would  call a  "heterochromatin island" a "macromolecular complex". I think because its a "chromosome part" which cannot exist independently of a chromosome.

We  would end up calling everything in a cell a "macromolecular complex".....

**Comment by ValWood** [comment]
I have another problem with this. It is really just a different structural representation of a chromosomal region due to histone modifications.....and it could never be defined in terms of subunit composition (its too variable in its  formation and extent).

**Comment by bmeldal** [comment]
I'm with Val on the problem of where to draw the line but I also can't see the term in the ontology so can't see the def.

**Comment by ukemi** [comment]
chromatin- The ordered and organized complex of DNA, protein, and sometimes RNA, that forms the chromosome. (should probably be renamed 'chromosomal chromatin').

macromolecular complex- A stable assembly of two or more macromolecules, i.e. proteins, nucleic acids, carbohydrates or lipids, in which at least one component is a protein and the constituent parts function together.

**Comment by ukemi** [comment]
I removed the macromolecular complex parent and now chromatin is just a chromosomal part.

**Comment by bmeldal** [comment]
What does TVP stand for? - Just for future ref. Or was it supposed to be TPV - true path violation?

**Comment by ValWood** [comment]
corrected!
