### ISSUE TITLE
mp magnesium ion export from mitochondrion

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12921]
Hello, 

GO:1990616	magnesium ion export from mitochondrion
is missing the parent 
GO:0015693	magnesium ion transport

Thanks, 
Pascale

**Comment by dosumis** [comment]
Cause by different ChEBI terms used in logical defs:

![image](https://cloud.githubusercontent.com/assets/112839/21984370/772fc0b4-dbed-11e6-955f-9c438c51034d.png)

![image](https://cloud.githubusercontent.com/assets/112839/21984384/81bbd86a-dbed-11e6-838d-db0c27e0044c.png)

Should probably standardize on the cation version.

**Comment by ukemi** [comment]
Changed them all to the cation.

**Comment by pgaudet** [comment]
thanks !
