### ISSUE TITLE
TPV S-adenosyl homocysteine metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12925]
has alpha-amino acid metabolic process.
but is an  amino acid derivative

Only has 25 EXP annotations......

**Comment by ukemi** [comment]
S-adenosyl homocysteine is a type of alpha-amino acid in CHEBI. If we want to change that, a CHEBI ticket should be opened.

**Comment by ValWood** [comment]
Logically it must be a derivative, it has an additional parent?
GO:0046128 purine ribonucleoside metabolic process

**Comment by ValWood** [comment]
Hi David,
Could you do this?
I eventually tracked down my SF username, but I don't have access to create issues on this tracker even when logged in.

Cheers,

Val

**Comment by ukemi** [comment]
Hi Val,

I can do it when I'm in the office, but their tracker is on Github now. There is a link to it from their contact page.

-D

**Comment by ValWood** [comment]
https://github.com/ebi-chebi/ChEBI/issues/3249

**Comment by ukemi** [comment]
Thanks. Assuming this will be sorted out when ChEBI is updated.
