### ISSUE TITLE
TPV: protein localization to membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12929]
This causes TPV's because its parent is "membrane organization". Not all protein localization to membrane is membrane organization; for example
GO:0006614 SRP-dependent cotranslational protein targeting to membrane

for delivery of luminal and membrane ER proteins to the ER membrane.
Lots of  other violators.

v

**Comment by ukemi** [comment]
If you are targeting the protein to a membrane, then isn't that part of membrane organization?

**Comment by ValWood** [comment]
I don't think it necessarily is. All of the proteins which end up in the ER lumen are first targeted to the ER membrane.
Or do we just say they are targeted to the ER....I need to find the violators....

**Comment by ValWood** [comment]
Its OK. The violators will be fixed in other ways. Maybe this is a none issue.
Will close for now.

**Comment by deustp01** [comment]
Isn't the textbook view that all translation products destined for the ER get there by possessing an amino-terminal sequence that is recognized by by the SRP, setting off the association of the ribosome - mRNA - nascent polypeptide with the ER membrane, oriented so that the nascent polypeptide is extruded into the ER lumen. Depending on other sequence features the nascent polypeptide may remain associated with the ER membrane or may be released entirely into the ER lumen. So everything has to traverse the membrane as part of its synthesis, but does that count as localization?

**Comment by ValWood** [comment]
I think this needs fixing.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006616#term=ancchart

Its in another ticket ;) I forgot
https://github.com/geneontology/go-ontology/issues/11908
I think the proposed solution  here will make the problem go away.....

**Comment by hdrabkin** [comment]
Asked for my 2c: a protein could be  bind to a membrane without altering the membrane organization.

**Comment by ukemi** [comment]
Harold and I talked about this on our walk.  I am removing the link.

 synonym: "protein localisation in membrane" EXACT [GOC:mah]
 synonym: "protein localization in membrane" EXACT [GOC:curators]
 is_a: GO:0034613 ! cellular protein localization
-is_a: GO:0044802 ! single-organism membrane organization
 intersection_of: GO:0008104 ! protein localization
 intersection_of: has_target_end_location GO:0016020 ! membrane

**Comment by ValWood** [comment]
> Harold and I talked about this on our walk.

;) 

I think I agree. If a protein is targeted to and anchored to the membrane cortex (like a GTPase), it isn't really organizing the membrane at all.

**Comment by ValWood** [comment]
The link came back ;)
v

**Comment by pgaudet** [comment]
See also #13758 
and #13754

**Comment by pgaudet** [comment]
Hi @ValWood Can you check again ? It seems like this link is gone now. 

Thanks, Pascale

**Comment by ValWood** [comment]
It's gone at my end.
v

**Comment by ValWood** [comment]
The link is back...


protein localization to plasma membrane
 is a deescendent of plasma membrane organization
