### ISSUE TITLE
new taxon restriction queuosine biosynthetic process never in metazoa, never in fungi

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12920]
probably protozoa too, not sure about these...

Lots of annotations including 
	UniProtKB-KW:KW-0671 keyword mapping
	PANTHER:PTN00023904 (350 annotations) @pgaudet 
UniPathway:UPA00392

which should be 
tRNA-guanine transglycosylation
if they are
queuine tRNA-ribosyltransferase activity

**Comment by ValWood** [comment]
Metazoa and Fungi don't make queuosine

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0671 keyword mapping
UniPathway:UPA00392
appear to be fixed in AiGO

**Comment by pedruzzi** [comment]
corrected this (KW, pathway and GO) in the 2 Unirules concerned.
Should fix 1249 mappings in UniProtKB.

**Comment by ukemi** [comment]
It is already never_in_eukaryota.

**Comment by ValWood** [comment]
I don't understand the taxon checks. Why do we see annotations?  Are they a hard check?

**Comment by ValWood** [comment]
@pedruzzi  thanks ivo!
