### ISSUE TITLE
ectoplasmic specialization

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12928]
I would like to see "apical ectoplasmic specialization” and “basal ectoplasmic specialization” added to the GO ontology under the parent term "cell-cell adherens junction” (GO:0005913).  The definitions could be "Testis-specific adherens junction between mature spermatids and Sertoli cells at the luminal end of the Sertoli cell.” and " Testis-specific adherens junction between mature Sertoli cells involved in establishing the blood-testis barrier of the Sertoli cell.”, respectively.  Synonyms: apical ES, basal ES.  Examples can be found in PMID:23546604, PMID:22332112.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061831
+name: apical ectoplasmic specialization
+namespace: cellular_component
+def: "Testis-specific adherens junction between mature spermatids and Sertoli cells at the luminal end of the Sertoli cell." [GOC:dph, PMID:22332112, PMID:23546604]
+synonym: "apical ES" EXACT []
+is_a: GO:0005913 ! cell-cell adherens junction
+
+[Term]
+id: GO:0061832
+name: basal ectoplasmic specialization
+namespace: cellular_component
+def: "Testis-specific adherens junction between mature Sertoli cells involved in establishing the blood-testis barrier of the Sertoli cell." [GOC:dph, PMID:22332112, PMID:23546604]
+synonym: "basal ES" EXACT []
+is_a: GO:0005913 ! cell-cell adherens junction
