### ISSUE TITLE
Phosphate versus phophate ion

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12922]
Hello, 

1. Is there a difference between Phosphate versus and phosphate ion ? See 'sister terms' 
GO:0015114	phosphate ion transmembrane transporter activity
GO:1901677	phosphate transmembrane transporter activity

2. Also, is there any 'organic phosphate' ? Ie we have " GO:1901677 phosphate transmembrane transporter activity", that has a child " GO:0005315 inorganic phosphate transmembrane transporter activity" It seems these pairs of terms could be merged. 

3. We also have "GO:0015320 phosphate ion carrier activity", a child of "GO:0015114	phosphate ion transmembrane transporter activity". The distinction seems to be mitochondrial transport versus any other transmembrane transport - is this right ? I am not sure the term "carrier" makes that clear (but I may not know the nomenclatures used). 

Thanks, Pascale

**Comment by ValWood** [comment]
I think these would be safe to merge.

I never really understood what the differentia is for a carrier.  To me it seems to be only a family descignation and not mechaism based.

It isn't mitochondria
(although you are correct that GO:0015320 phosphate ion carrier activity is defined as mitochondrial, an  the carrier designation is used most frequently for mitochondrial solute transporters)
https://en.wikipedia.org/wiki/Solute_carrier_family

**Comment by deustp01** [comment]
Phosphate exists in various charge states from 0 to -4 depending on pH - https://en.wikipedia.org/wiki/Phosphate. For ChEBI the different charge states are different entities. "Organic phosphate" is any compound that includes a phosphate group though it's mostly used, I think, for entities like methyl phosphate and not for AMP. The carriers and transporters I'm familiar with distinguish among these various entities and only act on one or a few. Meanwhile, data in papers often isn't sufficient to establish clearly exactly which charge state of phosphate is really active in an experiment (especially where the system likely contains a mixture of two), so on the one hand one can build an ontology of terms that precisely distinguish all these molecules and the distinctions are surely important for things like maintaining the correct ion and charge states of active mitochondria, but then have to go up in the hierarchy to grouping terms to annotate what's actually known from an experiment. We do not yet have a good, consistent way of doing this.

**Comment by ukemi** [comment]
It looks like we use the CHEBI class 'phosphate' in the logical definition of 'phosphate transmembrane transporter activity' but perhaps we should use 'phosphoric acids' instead, since we really mean the grouping class. 
CHEBI has both inorganic phosphate (CHEBI:24838) and organic phopshate (CHEBI:25703).  I will mark this for discussion.

We do not distinguish among charge states for the reason Peter mentions above. Based on the defintion of the carrier, it looks like the distinction is as you mention. The carrier is specific to the mitochonrdrion. Looks like we need to make the name more specific and add some synonyms.

**Comment by pgaudet** [comment]
For the phosphate ion versus non-ionized (charge =0), it seems implausible physiologically to have the non-ionized form, so that one should be removed from the ontology. 

For the carrier versus transporter, there would be a lot of terms to add and rename if the distinction is mitochondrial versus other type of transport;. We have very few 'carrier activities' but many more metabolites transported into the mitochondria: 

Function 	GO:0005472 	FAD carrier activity 	
Function 	GO:0097163 	sulfur carrier activity 	
Function 	GO:0009055 	electron carrier activity 	
Function 	GO:0036370 	D-alanyl carrier activity 	
Function 	GO:0022809 	mobile ion carrier activity 	
Function 	GO:0015320 	phosphate ion carrier activity 	
Function 	GO:0008518 	reduced folate carrier activity 

The pragmatic solution would be to merge 'carrier' and 'transporter' activities and use the CC aspect of the annotation to describe in which organelle the transport takes place. 

Thanks, Pascale

**Comment by ValWood** [comment]
+1

**Comment by ukemi** [comment]
Looking at most of these, it looks like it would not hurt to merge or rename, but what about the ones where there is contextual info in the term (eg CC info?). As for the phosphate, I agree, that is why I suggest we move the logical definition to the grouping term. The non-ionized form of phosphate is very physiologically implausible (see the CHEBI dovetailing paper), but the grouping term phosphoric acids makes sense.

**Comment by cmungall** [comment]
CHEBI: phosphate ion conjugate-base-of phosphoric acid

This means transport of these two is equivalent (see Hill et al for details). So if you make the suggested change the two GO terms will be equivalent.

![image](https://cloud.githubusercontent.com/assets/50745/22029334/11b1fee4-dc8f-11e6-8b6e-7c407801b00a.png)

**Comment by ukemi** [comment]
Suggested change is not to 'phosphoric acid' it is to 'phosphoric acids' not 'phosphoric acid'. I think that will work.

**Comment by cmungall** [comment]
ohh, right of course. Not confusing at all to distinguish two classes based on a plural!

**Comment by dosumis** [comment]
GO:0022809
mobile ion carrier activity
Synonyms: ionophore
Definition: This is a type of carrier produced by bacteria. It enables passive transport by shielding the ion that is being transported from the lipid membrane. *It carries an ion across the membrane by enclosing the ion and travelling across the membrane. It does not form a fully open pore across the membrane.*

This is very different from a transporter that has a pore.  I think this deserves a specific term.

**Comment by ukemi** [comment]
Changed the logical definition as proposed above. The ontology editors were generally uncomfortable with merging all carrier terms into the respective transporter terms because as illustrated above, they often have more specific mechanisms that what is included in a generic transporter.
