### ISSUE TITLE
obsolete GO:0042964 thioredoxin biosynthetic process & GO:0042965 Glutaredoxin biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12923]
How would we use this?
Thioredoxins are single gene products right? (translated)

Has no annotations. Probably shouldn't....

**Comment by ValWood** [comment]
Glutaredoxin biosynthetic process
same question

**Comment by ValWood** [comment]
and ferredoxin biosynthetic process

**Comment by ukemi** [comment]
Obsoletion notice sent on January 20, 2017

**Comment by dianeoinglis** [comment]
These terms are not precisely defined as intended which is why they don't make sense. Glutaredoxin and thioredoxin (the translated gene products) exist in an oxidized state. The functional glutaredoxins and thioredoxins must be reduced in order to serve their functions.

**Comment by dianeoinglis** [comment]
The proposed obsoleted terms could be specified as (1) "reduced thioredoxin biosynthetic process" and (2) "reduced glutaredoxin biosynthetic process." The enzyme thioredoxin reductase reduces oxidized thioredoxin to produce active thioredoxin (reduced) and glutaredoxins are reduced by glutathione (not a gene product) which are reduced by glutathione reductase enzyme. So thioredoxin reductase should be annotated to (1) and glutathione reductase could be annotated to (2). There are 2 annotations to 'thioredoxin biosynthetic process' in Amigo (NTRA and NTRB) that are not shown in QuickGo, both are thioredoxin reductases that would be more correctly described as involved in (1). The SlGRX1 is the glutaredoxin gene and should not be annotated to 'glhtare

**Comment by dianeoinglis** [comment]
...(smart phone typo)...Should not be annotated to "glutaredoxin biosynthetic process" as it is in Amigo2. 

Ferridoxin also undergoes oxidization-reduction and the reduced form carries out its function. 

I agree with the obsoletions but propose that a new term "reduced thioredoxin biosynthetic process" be created. The other two are either indirect or unclear so I will leave requests for glutarexoxin and ferridoxin to others.
Diane

**Comment by ValWood** [comment]
Hi Diane,

What you are describing here are molecular functions and these terms already exist.

We have:

thioredoxin-disulfide reductase activity
and can use "has_direct_input" "thioredoxin x"

to describe what  you describe above. Its a single-step so it doesn't warrant a biological process term.

I don't think that describing the  oxidation/reduction  of thioredoxin was what was intended by he obsoleted terms.

**Comment by tberardini** [comment]
Arabidopsis genes NTRA and NTRB are annotated to 'thioredoxin biosynthetic process' using IGI (double mutant analysis).  "Nevertheless, in the double mutant, the cytosolic thioredoxin h3 is only partially oxidized, suggesting an alternative mechanism for thioredoxin reduction. "  Other papers show the 'thioredoxin-disulfide reductase activity' of both gene products by direct assay and those annotations exist.   

Digging into the more recent literature a little bit more, it looks like thioredoxin reduction can be catalyzed at least two ways in plants:  one using NADPH as a reductant (example, NADPH-dependent TRX reductase (NTR) ), and the other using ferredoxin as a reductant (example, Fd:TRX reductase (FTR)).

The current "thioredoxin-disulfide reductase activity" is defined as:

"Catalysis of the reaction: NADP(+) + thioredoxin = H(+) + NADPH + thioredoxin disulfide.	molecular_function"

and represents the former mechanism.

There's probably room to rename that one to refer to NADPH

**Comment by ukemi** [comment]
@tberardini are you ok with the proposed obsoletion of the biosynthesis terms? They are slated to go on Friday. I can rename the current function term.

**Comment by tberardini** [comment]
I'm ok with obsoletion of Glutaredoxin biosynthetic process and ferredoxin biosynthetic process but wonder about converting thioredoxin biosynthetic process to thioredoxin reduction.  See edited comment above.

**Comment by ukemi** [comment]
Thanks. I can change the term and make it an oxido-reduction process. Does that make sense?

**Comment by tberardini** [comment]
Yes, that makes sense with change in parentage.

>  resulting in the formation...

change to 

 resulting in the reduction...

**Comment by ValWood** [comment]
do we need to? I thought we were trying to avoid single step processes in MF

check out the parentage (MF-links have oxidation reduction process, 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004791#term=ancchart
and substrate would be thioredoxin

which is semantically equivalent?

**Comment by tberardini** [comment]
That's why I asked this:

> If there are (at least) two different ways to reduce thioredoxin, does it make sense to have a process term called 'thioredoxin reduction'?

One way uses NADPH and the other uses ferredoxin.  Would one add 'cofactor' = either of those to the process annotation of 'oxido-reductase process' to make the difference clear?  Or is that not necessary?  Maybe there's no need for a process annotation at all.

**Comment by dianeoinglis** [comment]
Important fungal pathogens do not have experimental evidence that is sufficient for an Evidence Code for MF. Insistng on solely MF terms will result in zero annotations for an important trait in Cryptococcus. I strongly propose that a BP term be available for use in species for which few experiments warrant MF annotations. I don't believe Val's comments consider this important fact. Diane

**Comment by ukemi** [comment]
Current proposal:
Obsolete glutaredoxin biosynthetic process and ferredoxin biosynthetic process
Rename thioredoxin biosynthetic process to become thioredoxin reduction. New def- The chemical reactions resulting in the reduction of thioredoxin, a small disulfide-containing redox protein that serves as a general protein disulfide oxidoreductase. New parent of thioredoxin reduction will be oxidation-reduction process.

**Comment by tberardini** [comment]
Works for me.  @dianeoinglis , would it be helpful if the glutaredoxin term was also converted into a 'glutaredoxin reduction' term with similar parentage?

**Comment by dianeoinglis** [comment]
Yes. The proposed reduction terms and parentage and the obsoletions work for me. Thanks!
