### ISSUE TITLE
Obsolete GO:0042967 acyl-carrier-protein biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12924]
GO:0042967 acyl-carrier-protein biosynthetic process
has no annotations, but it would if the F-P link 

GO:0008897 holo-[acyl-carrier-protein] synthase activity -> GO:0042967 acyl-carrier-protein biosynthetic process

was added.

**Comment by ukemi** [comment]
The enzyme activity is defined as the bidirectional in the ontology. Does it ever go in both directions? If we don't know, we would make a has_part and it would still require co-annotation. Otherwise we would have to change the definition to make it only one direction.

**Comment by ValWood** [comment]
Hi David,

This one isn't urgent for me (not matrix). I just saw it as I spotted other stuff, and thought it would be a quick way  to improve annotation.

However, at the moment it wouldn't because at least PomBase and SGD have the fatty acid synthase annotated to the "acyl carrier synthase" terms.

I'll take this ticket and come back to it later when the primary annotations have been checked.

**Comment by ValWood** [comment]
I don't think the process term means what I thought it did.

I'm not sure that
GO:0042967 acyl-carrier-protein biosynthetic process
should exist. 

AN ACP is a gene product so I'm not sure why there is a formation term for it?

**Comment by pgaudet** [comment]
Hi @ValWood I agree - GO:0042967 acyl-carrier-protein biosynthetic process should not be in the ontology.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0042967 acyl-carrier-protein biosynthetic process. The reason for obsoletion is that acyl-carrier-protein is synthesized by the ribosome like any other protein. 

There are no annotations or mappings to this term. 

Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/12924 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 7, 2018. Unless objections are received by Feb 7, 2018, we will assume that you agree to this change. 


Thanks, Pascale
