### ISSUE TITLE
sperm head concavity

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12927]
I would like to see "concave side of sperm head” added to the GO ontology under the parent term "sperm head” (GO:0061827).  The definition could be "The concave part of the late spermatid head or spermatozoon head that forms the ventral portion of the head, particularly in some rodent species.” Examples can be found in PMID:22332112, PMID:26990065, PMID:23403943.

**Comment by ukemi** [comment]
Used the OBO editor in Protege. Looks like it worked fine.

 [Term]
+id: GO:0061830
+name: concave side of sperm head
+namespace: cellular_component
+def: "The concave part of the late spermatid head or spermatozoon head that forms the ventral portion of the head, particularly in some rodent species." [PMID:22332112, PMID:23403943, PMID:26990065]
+is_a: GO:0097223 ! sperm part
+relationship: part_of GO:0061827 ! sperm head
