### ISSUE TITLE
actin filament branch point

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12932]
I would like to see "actin filament branch point” added to the GO ontology under the part_of parent term "actin filament” (GO:0005884) and the is_a parent “cytoskeletal part” (GO:0044430).  The definition could be "The part of an actin filament where the structure forks.” An example can be found in PMID:18256280.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061834
+name: actin filament branch point
+namespace: cellular_component
+def: "The part of an actin filament where the structure forks." [PMID:18256280]
+synonym: "microfilament branch point" EXACT [GOC:dph]
+is_a: GO:0044430 ! cytoskeletal part
+relationship: part_of GO:0005884 ! actin filament
