### ISSUE TITLE
Obsolete storage protein import into fat body GO:0015032 (was: NTR: protein import into cell)

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12935]
We appear to have no term for protein import into cell - despite having a hierarchy of terms under 'import into cell' covering all sorts of other imported things.  

I stumbled across this while looking for a new home for "storage protein import into fat body GO:0015032", which is currently incorrectly under GO:0044743 - which covers intracellular protein import into organelles.

**Comment by ukemi** [comment]
TG-templatable.

**Comment by ukemi** [comment]
Before I do this, GO:0015032 will be a child of this. What do you think about terms like receptor internalization and ubiquitin-dependent endocytosis?

**Comment by pgaudet** [comment]
The papers annotated seem to describe endocytosis - PMID:10231363 and PMID:19305132

Maybe 'protein import into cell' is not specific enough. To check.

**Comment by pgaudet** [comment]
HI @hattrill 
Can you have a look at these two papers? PMID:10231363 and PMID:19305132
I have doubts about the term "storage protein import into fat body GO:0015032" - fat body is a tissue, so I don't know where this term should go in the hierarchy. 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi Pascale,
I am going to remove these annotations and re-curate these papers. You can obsolete this term.

**Comment by dosumis** [comment]
> fat body is a tissue, so I don't know where this term should go in the hierarchy.

Perhaps import into [fat body cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000565) ?

**Comment by hattrill** [comment]
Could be, but the two annotations we had didn't warrent a special term all of their own. So I would just obsolete this.

**Comment by pgaudet** [comment]
Hi Helen,

For the obsoletion notice: what term did you annotate to instead?

Thanks, Pascale

Le 13 févr. 2018 9:34 AM, "Helen Attrill" <notifications@github.com> a
écrit :

**Comment by hattrill** [comment]
One, I just removed rather than replaced.
The other was "receptor-mediated endocytosis"

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete "GO:0015032 storage protein import into fat body". The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using "receptor-mediated endocytosis”. 

Existing annotations have been removed. There are no mappings to this term. 

Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/12935


We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 20, 2018. Unless objections are received by Feb 20, 2018, we will assume that you agree to this change. 


Thanks, Pascale

**Comment by pgaudet** [comment]
Is there still a reason to create 'protein import into cell' - since there are no potential children, I would prefer not to create the term. 

Thanks, Pascale
