### ISSUE TITLE
TPV: glycerol metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12934]
is_a carbohydrate metabolic process

(probably alditol that is incorrect?)

(@ukemi David, this will fix some of the mouse queries..... will revise the list)

**Comment by ukemi** [comment]
I think this is correct. @deustp01 @hdrabkin

**Comment by ValWood** [comment]
Wikepedia says,
As used in foods, glycerol is categorized by the Academy of Nutrition and Dietetics as a carbohydrate. The U.S. Food and Drug Administration (FDA) carbohydrate designation includes all caloric macronutrients excluding protein and fat. 

So, maybe for you, but I don't think that is technically true is it?

**Comment by deustp01** [comment]
CHEBI:5445 - glyceraldehyde is_a aldotriose is_a triose is_a monosaccharide is_a carbohydrate
CHEBI:17754 - glycerol is_a alditol is_ carbohydrate

So metabolism of either looks like it should qualify as a kind of carbohydrate metabolism, even outside US Government jurisdiction.

**Comment by deustp01** [comment]
(Sorry - I clicked the wrong button.)

**Comment by ValWood** [comment]
OK, thanks, back to the drawing board with that  outlier then.....
