### ISSUE TITLE
NTR: protein localization to tricellular tight junction

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/go-ontology#12930]
PMID:24889144
New term:
protein localization to tricellular tight junction
GO:XXXXXX
A process in which a protein is transported to, or maintained in, a location within a tricellular tight junction.
 
As a child of :
protein localization to cell junction
GO:1902414
 
In the mean time modify the definition of:
protein localization to bicellular tight junction
GO:1902396
old definition: A process in which a protein is transported to, or maintained in, a location within a tight junction.
new definition: A process in which a protein is transported to, or maintained in, a location within a bicellular tight junction.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061833
+name: protein localization to tricellular tight junction
+namespace: biological_process
+def: "A process in which a protein is transported to, or maintained in, a location within a tricellular tight junction." [PMID:24889144]
+intersection_of: GO:0008104 ! protein localization
+intersection_of: has_target_end_location GO:0061689 ! tricellular tight junction
+
+[Term]
 id: GO:0065001
 name: specification of axis polarity
 namespace: biological_process
@@ -517380,7 +517388,7 @@
 id: GO:1902396
 name: protein localization to bicellular tight junction
 namespace: biological_process
-def: "A process in which a protein is transported to, or maintained in, a location within a tight junction." [GOC:TermGenie, PMID:18332111]
+def: "A process in which a protein is transported to, or maintained in, a location within a bicellular tight junction." [GOC:TermGenie, PMID:18332111]
 synonym: "protein localisation in tight junction" EXACT [GOC:TermGenie]
 synonym: "protein localisation to tight junction" EXACT [GOC:TermGenie]
 synonym: "protein localization in tight junction" EXACT [GOC:TermGenie]
