### ISSUE TITLE
restructuring of Sertoli cell barrier

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12931]
I would like to see "restructuring of Sertoli cell barrier” added to the GO ontology under the parent term "establishment of Sertoli cell barrier” (GO:0097368). The definition could be "The temporary disruption and reorganization of the Sertoli cell barrier to accommodate the transit of preleptotene spermatocytes at stage VIII of the epithelial cycle.” Synonyms: restructuring of BTB; restructuring of SCB; restructuring of blood-testis barrier.  Examples can be found in PMID: 24467744, PMID: 20534520.

**Comment by ukemi** [comment]
Hi Stan,

Trying to figure out an is_a parent for this one, what do you think of regulation of cell-cell adhesion?

-D

**Comment by slaulederkind** [comment]
Yes, that sounds good.  Will "establishment of Sertoli cell barrier” be a part_of parent?

**Comment by ukemi** [comment]
Looking at the current structure I was thinking 'establishement of Sertoli cell barrier' should be a positive regulation of cell-cell adhesion and I would change it to be a part_of Sertoli cell development. But maybe the second isn't always true because if the barrier forms and breaks down then the establishment might not always be a part of development. I will create a logical definition to include the Sertoli cells.

**Comment by cmungall** [comment]
is the SCB a cell component or larger anatomical structure? If the former, I don't think we would have development, it would be assembly. If the latter, do you need an uberon class?

**Comment by ukemi** [comment]
This is a good question. I think the barrier is actually the 'epithelium' itself and it is described by its role. I think the blood brain barrier is similar. So the 'barrier' is actually the result of creating the contacts between the Sertoli cells in this case and the endothelial or glial cells in the case of the BBB. The establishment is the creation of the junctions between the cells that results in its ability to play the role of a 'barrier'. So I don't think we necessarily need and anatomical structure for the establishment. I think we need to talk about positively regulating the cell-cell contacts. Stan has probably looked at this more closely than me, so I'd like to get his input.

**Comment by dosumis** [comment]
But we have an anatomical term for blood-brain barrier...

**Comment by ukemi** [comment]
Then maybe worth having blood testis barrier.
Stan?

**Comment by cmungall** [comment]
ah of course, we have that already

[UBERON:0014914](http://purl.obolibrary.org/obo/UBERON_0014914) ! blood-testis barrier

But this is quite generic and includes haemolymph testis barries. We probably need a subclass that is explicitly sertoli cells

**Comment by slaulederkind** [comment]
Maybe just beef-up the definition of UBERON:0014914 ! blood-testis barrier, because the Sertoli cell barrier is the blood testis barrier.

**Comment by ukemi** [comment]
So this leads to an interesting point. In GO, I really think it is worthwhile to have Stan's term defined by what is going on with the Sertoli cell junctions.

**Comment by dosumis** [comment]
> Meanwhile in GO, the process would be defined in terms of the cell-component junctions. I don't know if you want a pre-composed term for this junction or not, but either way it would link up to the anatomical barrier

Or you could make a part_of children.  something like: 

regulation of cell-cell adhesion involved in restructuring of Sertoli cell barrier

regulation of cell-cell adhesion involved in establishment of Sertoli cell barrier

This would allow for other proceses involved Sertoli cells important to formation/restructuring of barrier.

**Comment by ukemi** [comment]
I was just typing something very similar when this came through. So the existing establishment term should become equivalent to the formation of the Sertoli cell barrier (new UBERON or increased specification of existing term?). 
I would create a new Sertoli cell barrier organization term and then add the Sertoli cell barrier restructuring term as a child of it.
Cell-cell adhesion would be a part of the formation if we wanted to go to that specificity.
Regulation of cell-cell adhesion would be a part of the restructuring term.

Stan?

**Comment by slaulederkind** [comment]
I think a term like "regulation of cell-cell adhesion involved in restructuring of Sertoli cell barrier" would be good.

**Comment by cmungall** [comment]
Paper on testicular permeability barriers in an insect: https://www.ncbi.nlm.nih.gov/pubmed/18620169

**Comment by ukemi** [comment]
New term in Uberon to import into GO then?

**Comment by cmungall** [comment]
Will be in next release:

```
[Term]
id: UBERON:0036185
name: Sertoli cell barrier
def: "The blood-testis barrier (abbreviated as BTB) is a physical barrier between the blood vessels and the seminiferous tubules of the animal testes. The barrier is formed by tight connections between the Sertoli cells, which are sustentacular cells (supporting cells) of the seminiferous tubules, and nourish the spermatogonia. The barrier prevents passage of cytotoxic agents (bodies or substances that are toxic to cells) into the seminiferous tubules." [Wikipedia:Blood-testis_barrier, Wikipedia:Blood-testis_barrier]
synonym: "blood testis barrier" RELATED [Wikipedia:Blood-testis_barrier]
synonym: "blood-testes barrier" RELATED [Wikipedia:Blood-testis_barrier]
xref: Wikipedia:Blood-testis_barrier ! blood-testis barrier
xref: MESH:G06.535.166.330.100 ! blood-testis barrier
intersection_of: UBERON:0014914 ! haemolymphatic fluid-testis barrier
intersection_of: composed_primarily_of CL:0000216 ! Sertoli cell
```

But you can keep using the generic one for now

**Comment by ukemi** [comment]
Thanks Chris. I will add the correct axioms once the term is available. It turns out we will make it a child of tissue remodeling because it is an iterative process that occurs again and again in the mature tissue. Seems like a lot of the terms under tissue remodeling could have axioms added.

**Comment by ukemi** [comment]
Actually, maybe not if there are external anatomical structures that take part in the remodeling processes.

**Comment by ukemi** [comment]
Part 1

 [Term]
+id: GO:0061843
+name: Sertoli cell barrier remodeling
+namespace: biological_process
+def: "The tissue remodeling process by which the Sertoli cell barrier is temporarily disrupted and reorganized to accommodate the transit of preleptotene spermatocytes at stage VIII of the epithelial cycle." [PMID:20534520, PMID:24467744]
+synonym: "blood testis barrier restructuring" BROAD []
+synonym: "restructuring of blood-testis barrier" BROAD []
+synonym: "restructuring of BTB" BROAD []
+synonym: "restructuring of SCB" EXACT []
+synonym: "SCB remodeling" EXACT []
+synonym: "Sertoli cell barrier restructuring" EXACT []
+is_a: GO:0048771 ! tissue remodeling

**Comment by ukemi** [comment]
@cmungall is it ok to ask for this in import requests or do I need to wait until the release?

**Comment by cmungall** [comment]
You can add it to the file. This will have no effect until the term becomes public
