### ISSUE TITLE
clarify meaning of term "protein maturation by protein folding"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12936]
The process of assisting in the covalent and noncovalent assembly of single chain polypeptides or multisubunit complexes into the correct tertiary structure that results in the attainment of the full functional capacity of a protein.

This has 23 EXP annotations (mainly mouse and fly)
Can anyone clarify its meaning?

 How does it differ from "GO:0006458 'de novo' protein folding"
Although I must admit the current def of "protein maturation" does not exclude protein folding, I never considered it part of maturation. I  thought maturation only referred to metabolic change.

**Comment by ukemi** [comment]
Based on the structure of the ontology 'de novo protein folding' isn't necessarily occurring to attain the full functional state of a protein, for example a preprotein could be made and folded. Then it could be refolded after a proteolytic maturation step. If the folding is required for the full functional state of the protein either to make it catalytically active or put it in the right place, I would use this term.

**Comment by ValWood** [comment]
OK. It's a bit confusing. We have a term "protein refolding" but that is restricted to misfolded proteins.....

**Comment by ukemi** [comment]
Yup.
