### ISSUE TITLE
NTR: intranuclear rod

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#12937]
Name: intranuclear rod
Ontology: cellular_component
Synonyms: intranuclear actin rod
Definition: Intranuclear rods are aggregates consisting of actin and cofilin that are formed in the nucleus as a consequence of chemical or mechanical stress conditions. The formation of rods is implicated in a variety of pathological conditions, such as certain myopathies and some neurological disorders. 

A part_of: nucleus (GO:0044428 nuclear part)

References:
PMID:28074884  Actin-Interacting Protein 1 Contributes to Intranuclear Rod Assembly in Dictyostelium discoideum

**Comment by ukemi** [comment]
Cool! I wonder what they do.

[Term]
+id: GO:0061836
+name: intranuclear rod
+namespace: cellular_component
+def: "A macromolecular fiber consisting of actin and cofilin that is formed in the nucleus as a consequence of chemical or mechanical stress conditions." [PMID:28074884]
+synonym: "intranuclear actin rod" EXACT []
+is_a: GO:0099512 ! supramolecular fiber
