### ISSUE TITLE
ventral surface of cell

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12933]
I would like to see "ventral surface of cell” added to the GO ontology under parent term "cell surface” (GO:0009986). The definition could be "The surface of a migrating cell that is in contact with the substratum or cell layer.” An example can be found in PMID: 11598004.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061835
+name: ventral surface of cell
+namespace: cellular_component
+def: "The surface of a migrating cell that is in contact with the substratum or cell layer." [PMID: 11598004]
+is_a: GO:0044464 ! cell part
+relationship: part_of GO:0009986 ! cell surface
