### ISSUE TITLE
telosome and shelterin: swap main name and synonym

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12939]
Pubmed search for shelterin = 427 entries
Pubmed search for telosome = 55 entries

Shelterin used in vertebrates
Telosome used in yeast (mainly? others too likely?!)

currently these terms exist on QuickGO 

Component 	GO:0070187 	telosome 	
Process 	GO:0071573 	telosome assembly 	
Process 	GO:1904790 	regulation of telosome assembly 	
Process 	GO:1904791 	negative regulation of telosome assembly 	
Process 	GO:1904792 	positive regulation of telosome assembly

**Comment by ukemi** [comment]
I think I got them all.

 [Term]
 id: GO:0070187
-name: telosome
+name: shelterin complex
 namespace: cellular_component
 def: "A nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. The complex is known to contain TERF1, TERF2, POT1, RAP1, TINF2 and ACD in mammalian cells, and Pot1, Tpz1, Rap1, Rif1, Rif2 and Taz1 in Schizosaccharomyces. Taz1 and Rap1 (or their mammalian equivalents) form a dsDNA-binding subcomplex, Pot1 and Tpz1 form an ssDNA-binding subcomplex, and the two subcomplexes are bridged by Poz1, which acts as an effector molecule along with Ccq1." [GOC:expert_mf, GOC:mah, GOC:vw, PMID:18828880]
 synonym: "Pot1 complex" EXACT [GOC:vw]
 synonym: "Pot1-Tpz1 complex" EXACT [GOC:vw]
-synonym: "shelterin complex" EXACT [GOC:mah, GOC:vw]
+synonym: "telosome" EXACT [GOC:mah, GOC:vw]
 is_a: GO:0000783 ! nuclear telomere cap complex
 
 [Term]
@@ -423232,15 +423232,16 @@
 
 [Term]
 id: GO:0071573
-name: telosome assembly
+name: shelterin complex assembly
 namespace: biological_process
-def: "The aggregation, arrangement and bonding together of a set of components to form a telosome. A telosome is a nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase." [GOC:mah, GOC:vw]
+def: "The aggregation, arrangement and bonding together of a set of components to form a shelterin complex. A shelterin complex is a nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase." [GOC:mah, GOC:vw]
 synonym: "Pot1 complex assembly" RELATED [GOC:mah, GOC:vw]
 synonym: "Pot1-Tpz1 complex assembly" RELATED [GIOC:vw, GOC:mah]
 synonym: "shelterin complex formation" RELATED [GOC:mah, GOC:vw]
+synonym: "telosome assembly" EXACT []
 is_a: GO:0065004 ! protein-DNA complex assembly
 intersection_of: GO:0022607 ! cellular component assembly
-intersection_of: results_in_assembly_of GO:0070187 ! telosome
+intersection_of: results_in_assembly_of GO:0070187 ! shelterin complex
 relationship: part_of GO:0032200 ! telomere organization
 created_by: midori
 creation_date: 2010-01-26T01:45:20Z
@@ -561733,22 +561734,23 @@
 
 [Term]
 id: GO:1904790
-name: regulation of telosome assembly
+name: regulation of shelterin complex assembly
 namespace: biological_process
-def: "Any process that modulates the frequency, rate or extent of telosome assembly." [GO_REF:0000058, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:24270157]
+def: "Any process that modulates the frequency, rate or extent of shelterin complex assembly." [GO_REF:0000058, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:24270157]
 synonym: "regulation of Pot1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "regulation of Pot1-Tpz1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "regulation of shelterin complex formation" EXACT [GOC:TermGenie]
+synonym: "regulation of telosome assembly" EXACT []
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: regulates GO:0071573 ! telosome assembly
+intersection_of: regulates GO:0071573 ! shelterin complex assembly
 created_by: nc
 creation_date: 2015-11-06T16:13:03Z
 
 [Term]
 id: GO:1904791
-name: negative regulation of telosome assembly
+name: negative regulation of shelterin complex assembly
 namespace: biological_process
-def: "Any process that stops, prevents or reduces the frequency, rate or extent of telosome assembly." [GO_REF:0000058, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:24270157]
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of shelterin complex assembly." [GO_REF:0000058, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:24270157]
 synonym: "down regulation of Pot1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "down regulation of Pot1-Tpz1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "down regulation of shelterin complex formation" EXACT [GOC:TermGenie]
@@ -561768,16 +561770,17 @@
 synonym: "negative regulation of Pot1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "negative regulation of Pot1-Tpz1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "negative regulation of shelterin complex formation" EXACT [GOC:TermGenie]
+synonym: "negative regulation of telosome assembly" EXACT []
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: negatively_regulates GO:0071573 ! telosome assembly
+intersection_of: negatively_regulates GO:0071573 ! shelterin complex assembly
 created_by: nc
 creation_date: 2015-11-06T16:13:11Z
 
 [Term]
 id: GO:1904792
-name: positive regulation of telosome assembly
+name: positive regulation of shelterin complex assembly
 namespace: biological_process
-def: "Any process that activates or increases the frequency, rate or extent of telosome assembly." [GO_REF:0000058, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:24270157]
+def: "Any process that activates or increases the frequency, rate or extent of shelterin complex assembly." [GO_REF:0000058, GOC:BHF, GOC:BHF_telomere, GOC:nc, GOC:TermGenie, PMID:24270157]
 synonym: "activation of Pot1 complex assembly" NARROW [GOC:TermGenie]
 synonym: "activation of Pot1-Tpz1 complex assembly" NARROW [GOC:TermGenie]
 synonym: "activation of shelterin complex formation" NARROW [GOC:TermGenie]
@@ -561785,6 +561788,7 @@
 synonym: "positive regulation of Pot1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "positive regulation of Pot1-Tpz1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "positive regulation of shelterin complex formation" EXACT [GOC:TermGenie]
+synonym: "positive regulation of telosome assembly" EXACT []
 synonym: "up regulation of Pot1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "up regulation of Pot1-Tpz1 complex assembly" EXACT [GOC:TermGenie]
 synonym: "up regulation of shelterin complex formation" EXACT [GOC:TermGenie]
@@ -561798,7 +561802,7 @@
 synonym: "upregulation of shelterin complex formation" EXACT [GOC:TermGenie]
 synonym: "upregulation of telosome assembly" EXACT [GOC:TermGenie]
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: positively_regulates GO:0071573 ! telosome assembly
+intersection_of: positively_regulates GO:0071573 ! shelterin complex assembly
 created_by: nc
 creation_date: 2015-11-06T16:13:18Z
