### ISSUE TITLE
GO:0030399 autophagosome membrane disassembly - changed synonyms’ scope

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12943]
FYI @ukemi  @RLovering @Pauldenny @marcfeuermann

As discussed at our autophagy call yesterday, I changed the scope of the following synonyms of ‘autophagosome membrane disassembly’ from exact to narrow (because the autophagosome membrane being disassembled into its constituent components doesn’t necessarily mean that the membrane lipids etc. will be fully catabolised - they could be recycled to make new membranes instead).
Note that this is not meant to be a comprehensive discussion of what catabolism should mean in GO, that’s a much broader issue that @ukemi plans to bring up on a higher-level call in the future; but we ran into this particular case while reviewing autophagy terms and wished to fix it.

 namespace: biological_process
 def: "The controlled breakdown of the membranes of autophagosomes." [GOC:autophagy, GOC:mah]
 synonym: "autophagic membrane breakdown" EXACT []
-synonym: "autophagic membrane catabolism" EXACT []
-synonym: "autophagic membrane degradation" EXACT []
+synonym: "autophagic membrane catabolism" NARROW [GOC:autophagy]
+synonym: "autophagic membrane degradation" NARROW [GOC:autophagy]
 synonym: "autophagic vacuole membrane disassembly" EXACT [GOC:autophagy]
 is_a: GO:0030397 ! membrane disassembly
 is_a: GO:1905037 ! autophagosome organization

I left the ‘breakdown’ synonym scope as was because that’s the same wording used in the def.

**Comment by marcfeuermann** [comment]
I've just found some information about the fate of autophagosomes after fusion with vacuole/lysosomes.
This in yeast:
"After the cargo is delivered inside the vacuole, the autophagic body membrane is degraded by a putative lipase, Atg15, followed by cargo degradation by resident hydrolases. Once degraded, the resulting macromolecules are released back into the cytosol through various permeases including Atg22.
This means that: 
- The outer membrane of the autophagosome fuses with the vacuolar membrane.
- The inner membrane is delivered in the vacuole and is degraded (by ATG15) to release its content for further degradation
- The degraded stuff is transfered to the cytosol by specific permeases including ATG22

Conclusions:
- It is no so obvious that autophagy ends with catabolism (but we still can decide that catabolism is the end).
- Yeast ATG15 would be a good candidate for annotation to "autophagic membrane disassembly" which is indeed a degradation/catabolic process.
- I have to modify again the figure to fit closer to the reality.

**Comment by ukemi** [comment]
So an alternative would be to make autophagy a cellular catabolic process again, which is consistent with the way we have currently represented ERAD and ubiquitin-mediated protein catabolism. 
According to PMID:22999865 the whole process ends with autophagic lysosome reformation. Is this a special structure or just a lysosome that will fuse again with an autophagosome? 

At any rate, I think maybe we should make autophagy itself a cellular catabolic process again.

**Comment by ukemi** [comment]
So autophagy is_a catabolic process and we remove the ends with catabolic process.
Macroautophagy ends with the permease activity or autophagic lysosome reformation. It could be considered that autophagic lysosome reformation, although linked is actually a type of lysosome organization PMID:24369758.
So we don't have an ends_with for general autophagy unless all autophagy ends with a permease/transporter that delivers the digested products back to the cytosol.

**Comment by ValWood** [comment]
Hi,

Why would autophagy not be a "cellular catabolic process"?

+1 to add back.

v

**Comment by paolaroncaglia** [comment]
Hi @ukemi ,
I'm assigning this to you as you've been leading discussion on this and on related items. Of course, we can add to the agenda for our next call if we haven't resolved sooner. I can see the reasons behind your suggested edits and @ValWood 's approval. Perhaps we could check with @Pauldenny's contact Helene Poin-Favreau? It'd be good to have input from an external expert on this high-level autophagy ontology issue.

**Comment by ukemi** [comment]
We should talk about it on the call. It is consistent with the literature in that autophagy is often called a catabolic process. So the proposal would be to make autophagy is_a catabolic process, chaperone-mediated autophagy is_a protein catabolic process, late endosomal microautophagy is_a protein catabolic process, glycophagy is_a glycogen ctabolic process. Lipophagy already is_a lipid catabolic process. Currently all of these types of autophagy except lipophagy end with the catabolic processes. If we define them as being global catbolic processes, can we define end points for each one? I think you are right, we should get the input of an expert.

**Comment by paolaroncaglia** [comment]
Hi @Pauldenny,
Do you think it would be possible to ask Helene for her feedback on how to best represent the biology here?
(All: I already made a note to add this to the agenda for our next call if still needed by then.)

**Comment by ukemi** [comment]
I made autophagy a type of cellular catabolic process. I was able to remove several asserted is_a parents because now they are inferred by the reasoner due to the has_input relationships in the logical definitions. I think that is it for the autophagy edits. Let me know if you spot anything weird.

-D
