### ISSUE TITLE
Creation of new GO term for neuropeptide processing

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#12949]
Hello,

I would like to create a GO term for "neuropeptide processing" to describe the activity of 2 enzymes that cleave sequentially neuropeptide precursor proteins into multiple active peptides.
References are: PMIDs: 12657671 and 17564681.

Thank you

Rossana

**Comment by ukemi** [comment]
[Term]
+id: GO:0061837
+name: neuropeptide processing
+namespace: biological_process
+def: "Any protein maturation process achieved by the cleavage of a peptide bond or bonds within a neuropeptide precursor. Processing leads to the attainment of the full functional capacity of the neuropeptide." [PMID:12657671, PMID:17564681]
+is_a: GO:0016485 ! protein processing
