### ISSUE TITLE
mitophagy in response to mitochondrial depolarization

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12941]
Autophagy is defined as beginning with the assembly of the ULK1 complex. Therefore the upstream processes that trigger autophagy are not part of the process.
This term and 'autophagy in response to ER overload' are not suptypes of autophagy because the autophagy that occurs is the same as the parent class. The differences lie upstream. Therefore, these terms should actually regulate autophagy. 
mitophagy in response to mitochondrial depolarization will become positive regulation of mitophagy in response to mitochondrial depolarization
autophagy in response to ER overload will become positive regulation of autophagy in response to ER overload.

**Comment by ukemi** [comment]
@paolaroncaglia @RLovering @Pauldenny @marcfeuermann 
I made the parkin-mediated terms 'stimulation' to avoid regulation of regulation, but I think they are ok. If you think they viloate the regulation of regulation rules, then I can obsolete them, but it seems in this case, they are regulating specific pathways that stimulate autophagy, so I think they are ok as a one-off.
 
 [Term]
 id: GO:0034263
-name: autophagy in response to ER overload
+name: positive regulation of autophagy in response to ER overload
 namespace: biological_process
-def: "The process in which cells digest parts of their own cytoplasm in response to the accumulation of misfolded proteins in the endoplasmic reticulum." [GOC:mah]
+def: "The process in which the accumulation of misfolded proteins in the endoplasmic reticulum triggers a response that positively regulates autophagy." [GOC:mah]
 synonym: "autophagy in response to endoplasmic reticulum overload" EXACT []
 synonym: "autophagy in response to ER stress" EXACT []
-is_a: GO:0006914 ! autophagy
-is_a: GO:0006983 ! ER overload response
+intersection_of: GO:0006983 ! ER overload response
+intersection_of: positively_regulates GO:0006914 ! autophagy
 
 [Term]
 id: GO:0034264
@@ -404206,19 +404206,19 @@
 
 [Term]
 id: GO:0061734
-name: parkin-mediated mitophagy in response to mitochondrial depolarization
+name: parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
-def: "The macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a parkin-family molecule." [GOC:autophagy, GOC:dph, GOC:pad, GOC:PARL, PMID:25349190]
-is_a: GO:0098779 ! mitophagy in response to mitochondrial depolarization
+def: "A positive regulation of the macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a parkin-family molecule." [GOC:autophagy, GOC:dph, GOC:pad, GOC:PARL, PMID:25349190]
+is_a: GO:0098779 ! positive regulation of mitophagy in response to mitochondrial depolarization
 created_by: dph
 creation_date: 2015-09-14T13:48:57Z
 
 [Term]
 id: GO:0061735
-name: dynamin-like protein-mediated mitophagy in response to mitochondrial depolarization
+name: dynamin-like protein-mediated stimulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
-def: "The macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a dynamin-like molecule." [GOC:autophagy, GOC:dph, GOC:pad, GOC:PARL, PMID:25349190]
-is_a: GO:0098779 ! mitophagy in response to mitochondrial depolarization
+def: "A positive regulation of  the macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a dynamin-like molecule." [GOC:autophagy, GOC:dph, GOC:pad, GOC:PARL, PMID:25349190]
+is_a: GO:0098779 ! positive regulation of mitophagy in response to mitochondrial depolarization
 created_by: dph
 creation_date: 2015-09-14T14:00:43Z
 
@@ -464232,11 +464232,11 @@
 
 [Term]
 id: GO:0098779
-name: mitophagy in response to mitochondrial depolarization
+name: positive regulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
 def: "The macromitophagy process that is triggered by a detection of the loss of mitochondrial membrane potential." [GOC:PARL, PMID:18200046, PMID:23985961]
-is_a: GO:0000423 ! macromitophagy
-relationship: part_of GO:0098780 ! response to mitochondrial depolarisation
+intersection_of: GO:0098780 ! response to mitochondrial depolarisation
+intersection_of: positively_regulates GO:0000423 ! macromitophagy
 
 [Term]
 id: GO:0098780
@@ -564170,8 +564170,8 @@
 name: regulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
 def: "Any process that modulates the frequency, rate or extent of mitophagy in response to mitochondrial depolarization." [GO_REF:0000058, GOC:pad, GOC:PARL, GOC:TermGenie, PMID:22020285]
-intersection_of: GO:0065007 ! biological regulation
-intersection_of: regulates GO:0098779 ! mitophagy in response to mitochondrial depolarization
+intersection_of: GO:0098780 ! response to mitochondrial depolarisation
+intersection_of: regulates GO:0000422 ! mitophagy
 created_by: pad
 creation_date: 2016-01-26T11:23:50Z
 
@@ -564185,7 +564185,7 @@
 synonym: "downregulation of mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
 synonym: "inhibition of mitophagy in response to mitochondrial depolarization" NARROW [GOC:TermGenie]
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: negatively_regulates GO:0098779 ! mitophagy in response to mitochondrial depolarization
+intersection_of: negatively_regulates GO:0098779 ! positive regulation of mitophagy in response to mitochondrial depolarization
 created_by: pad
 creation_date: 2016-01-26T11:23:58Z
 
@@ -564199,7 +564199,7 @@
 synonym: "up-regulation of mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
 synonym: "upregulation of mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: positively_regulates GO:0098779 ! mitophagy in response to mitochondrial depolarization
+intersection_of: positively_regulates GO:0098779 ! positive regulation of mitophagy in response to mitochondrial depolarization
 created_by: pad
 creation_date: 2016-01-26T11:24:05Z
 
@@ -567575,17 +567575,17 @@
 
 [Term]
 id: GO:1905089
-name: regulation of parkin-mediated mitophagy in response to mitochondrial depolarization
+name: regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
-def: "Any process that modulates the frequency, rate or extent of parkin-mediated mitophagy in response to mitochondrial depolarization." [GO_REF:0000058, GOC:pad, GOC:PARL, GOC:TermGenie, PMID:26942284]
+def: "Any process that modulates the frequency, rate or extent of a parkin-mediated process that positively regulates mitophagy in response to mitochondrial depolarization." [GO_REF:0000058, GOC:pad, GOC:PARL, GOC:TermGenie, PMID:26942284]
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: regulates GO:0061734 ! parkin-mediated mitophagy in response to mitochondrial depolarization
+intersection_of: regulates GO:0061734 ! parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 created_by: pad
 creation_date: 2016-03-30T15:34:29Z
 
 [Term]
 id: GO:1905090
-name: negative regulation of parkin-mediated mitophagy in response to mitochondrial depolarization
+name: negative regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
 def: "Any process that stops, prevents or reduces the frequency, rate or extent of parkin-mediated mitophagy in response to mitochondrial depolarization." [GO_REF:0000058, GOC:pad, GOC:PARL, GOC:TermGenie, PMID:26942284]
 synonym: "down regulation of parkin-mediated mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
@@ -567593,13 +567593,13 @@
 synonym: "downregulation of parkin-mediated mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
 synonym: "inhibition of parkin-mediated mitophagy in response to mitochondrial depolarization" NARROW [GOC:TermGenie]
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: negatively_regulates GO:0061734 ! parkin-mediated mitophagy in response to mitochondrial depolarization
+intersection_of: negatively_regulates GO:0061734 ! parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 created_by: pad
 creation_date: 2016-03-30T15:34:38Z
 
 [Term]
 id: GO:1905091
-name: positive regulation of parkin-mediated mitophagy in response to mitochondrial depolarization
+name: positive regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 namespace: biological_process
 def: "Any process that activates or increases the frequency, rate or extent of parkin-mediated mitophagy in response to mitochondrial depolarization." [GO_REF:0000058, GOC:pad, GOC:PARL, GOC:TermGenie, PMID:26942284]
 synonym: "activation of parkin-mediated mitophagy in response to mitochondrial depolarization" NARROW [GOC:TermGenie]
@@ -567607,7 +567607,7 @@
 synonym: "up-regulation of parkin-mediated mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
 synonym: "upregulation of parkin-mediated mitophagy in response to mitochondrial depolarization" EXACT [GOC:TermGenie]
 intersection_of: GO:0065007 ! biological regulation
-intersection_of: positively_regulates GO:0061734 ! parkin-mediated mitophagy in response to mitochondrial depolarization
+intersection_of: positively_regulates GO:0061734 ! parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
 created_by: pad
 creation_date: 2016-03-30T15:34:47Z

**Comment by RLovering** [comment]
thanks David, this is very helpful

**Comment by paolaroncaglia** [comment]
Hi @ukemi ,
Thanks for doing those edits. I am not entirely at ease with the phrasing and positioning of GO:1905089 'regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization', but if you and @marcfeuermann think that the parkin-mediated stimulation is indeed downstream of a distinct process that positively regulates it, then I can live with that. Sounds like the kind of observation we should capture via LEGO annotation rather than ontology terms, but I do trust your judgment on what's best, so happy to go with it. :-)

**Comment by ukemi** [comment]
Hi @paolaroncaglia ,

I also had the same concerns as you, but tried to fit the exisitng terms in as best I could. My assumption was exactly as you say, that there was a process that regulates the parkin-mediated process. I also agree that these would be much better represented in LEGO modles.

-D
