### ISSUE TITLE
urgent - missing relation telosome assembly child of telomere organization??

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12940]
urgent due to writing paper.

Is there a missing relationship between these two terms?

 GO:0071573 telosome assembly
The aggregation, arrangement and bonding together of a set of components to form a telosome. A telosome is a nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase.

GO:0032200 telomere organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of telomeres, terminal regions of a linear chromosome that include the telomeric DNA repeats and associated proteins.

**Comment by ukemi** [comment]
Hi Nancy,

I made it a part_of telomere organization, but could make it a part of telomere assembly if you would like. You're the expert.

-David

**Comment by NancyCampbell** [comment]
Should I put in a new ticket?

In summary: 

telomere refers to a larger structure which includes a lot of things (such as histones and conditionally associating DNA repair factors and shelterin complex PMID 26785477 review), however, at its very distal ends, the shelterin complex is found. The consensus is that Shelterin complex includes ds and ss DNA plus the associated six shelterin proteins (in vertebrates) POT1, TRF1, TRF2, RAP1, TIN2, TPP1. PMID 28078514 (review) Fig2 

The distinction between a Telomere and the shelterin complex (syn telosome) can be clearer and the relationship reflected correctly in the ontology by:

Suggestion to make GO:0071573 Shelterin complex assembly (syn telosome assembly) child of GO:0032202 telomere assembly and tweak definitions (note telomere assembly is already child of telomere organisation so the relationship between telosome assembly and telomere organisation will be maintained albeit via telomere assembly) (or better)

current annotations stats and defintions plus tweaks:

GO:0032202 telomere assembly
**Current**: A cellular process that results in the aggregation, arrangement and bonding together of a set of components to form a telomere at a non-telomeric double-stranded DNA end. A telomere is a terminal region of a linear chromosome that includes telomeric DNA repeats and associated proteins.
**New**: A cellular process that results in the aggregation, arrangement and bonding together of a set of components to form a telomere. A telomere is a terminal region at the ends of linear chromosomes that includes telomeric dsDNA and ssDNA tandem repeats (formed of the repetitive sequence TTAGGG in vertebrates), nucleosomal histones, shelterin complex and other conditionally associated proteins. 
Total: 120 annotations for 116 proteins (of which 106 annotations are IEA)
 
and its only child 

GO:0032203
Name 	telomere formation via telomerase
Ontology 	Biological Process
Definition 	A cellular process that results in the formation of a telomere at a non-telomeric double-stranded DNA end that involves the activity of a telomerase enzyme. 
**35 annotations for 32 proteins (of which 27 are IEA)**


GO:0071573 telosome (now shelterin complex) assembly 
**Current**: The aggregation, arrangement and bonding together of a set of components to form a telosome. A telosome is a nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase.
**No annotations**

**New**: The aggregation, arrangement and bonding together of a set of components to form a telosome. A telosome is a nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. In vertebrates, the shelterin complex (or telosome) comprises telomeric DNA (formed of the repetitive sequence TTAGGG) and the six proteins: TRF1, TRF2, TIN2, TPP1, RAP1 and POT1.

Three children of GO:0071573 Telosome assembly (now Shelterin complex assembly) (created by BHF-UCL - me).
1. GO:1904790 
Name              regulation of telosome assembly child of GO:0071573 telosome assembly
Ontology 	Biological Process
Definition 	Any process that modulates the frequency, rate or extent of telosome (now shelterin) assembly. 
**No annotations**

2. child of GO:0071573 telosome (now shelterin complex) assembly
GO:1904791 
Name 	        negative regulation of telosome assembly
Ontology 	Biological Process
Definition 	Any process that stops, prevents or reduces the frequency, rate or extent of telosome (now shelterin) assembly. 
**No annotations**

3. child of GO:0071573 telosome assembly
GO:1904792 
Name 	        positive regulation of telosome (now shelterim complex) assembly
Ontology 	Biological Process
Definition 	Any process that activates or increases the frequency, rate or extent of telosome assembly. 
**1 IMP by BHF-UCL (me!)
1 ISO by MGI
24 IEA by Ensembl**
