### ISSUE TITLE
missing relationships btw serotonin receptor complexes, activities and pathways

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12942]
related to #12029

1. 
GO:0004993 G-protein coupled serotonin receptor activity
currently: 
part_of GO:0007210 serotonin receptor signaling pathway
SHOULD BE
part_of GO:0098664 G-protein coupled serotonin receptor signaling pathway (its child which is more specific)

2.
GO:0098666 G-protein coupled serotonin receptor complex
capable_of_part_of (or part_of?) GO:0098664 G-protein coupled serotonin receptor signaling pathway
(the current relationship is via capable_of [...activity] part_of [...pathway] so I don't think this would propagate down sufficiently for inferences...)

3.
GO:0022850 serotonin-gated cation-selective channel activity
part_of GO:0007210 serotonin receptor signaling pathway

4.
GO:1904602 serotonin-activated cation-selective channel complex
capable_of_part_of (or part_of?) GO:0007210 serotonin receptor signaling pathway

5.
I'm trying to figure out if we can have equivalent pathway terms for the LGIC-type receptors as we have for the G-protein coupled receptor pathways, e.g.:
GO:NEW serotonin-gated cation-selective signaling pathway
equivalent to 
GO:0098664 G-protein coupled serotonin receptor signaling pathway

I'm struggling with the def and looks like maybe it shouldn't exists, see:
GO:1990806 **obsolete** ligand-gated ion channel signaling pathway
But it's missing a comment why we shouldn't have LGIC-type pathway terms.

Birgit

Assigning to David OS as he worked on the original serotonin ticket :)

**Comment by dosumis** [comment]
> 1.  
> GO:0004993 G-protein coupled serotonin receptor activity
> currently: 
> part_of GO:0007210 serotonin receptor signaling pathway
> SHOULD BE
> part_of GO:0098664 G-protein coupled serotonin receptor signaling pathway (its child which is more specific)

Fixed

> 2.
> GO:0098666 G-protein coupled serotonin receptor complex
> capable_of_part_of (or part_of?) GO:0098664 G-protein coupled serotonin receptor signaling pathway
(> the current relationship is via capable_of [...activity] part_of [...pathway] so I don't think this would propagate down sufficiently for inferences...)

Won't add. The relationship capable_of_part_of is semantically equivalent to the chain "capable_of [...activity] part_of [...pathway]"

**Comment by bmeldal** [comment]
Are you still working on this?
No 1 hasn't trickled through to QuickGO yet. 
No.s 3&4 are relationships that need adding, in case it was unclear what I asked for. 
No 5: I'm after some advice if we can create this ion-channel specific pathway term since "ligand-gated ion channel signaling pathway" had been obsoleted. I don't know why the latter term wasn't permissible.

**Comment by pgaudet** [comment]
1. was already done 
2. David thought we shouln't do 
3. GO:1904602 serotonin-activated cation-selective channel complex
capable_of_part_of (or part_of?) GO:0007210 serotonin receptor signaling pathway
Added
4. Is similar to 2, so I will not add. 

5. This would be some sort of grouping terms for all "ligand-gated ion channel signaling pathways"? Do you have a reference? (The cited paper seems to refer to a specific pathway, PMID:25869137)
Personally I dont have a problem restoring that term as a 'do not annotate' tag - I don't know who objected to this and why ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
Add 5:

GO:NEW serotonin-gated cation-selective signaling pathway
Def:
A series of molecular signals initiated by serotonin binding to a seratonin receptor on the surface of the target cell, followed by the movement of ions through a channel in the receptor complex. Ends with regulation of a downstream cellular process, e.g. transcription. 

Synonyms:
5-hydroxytryptamine-gated cation-selective signaling pathway [EXACT]
5-HT-gated cation-selective signaling pathway [EXACT]
serotonin-gated cation-selective signalling pathway [EXACT]
5-hydroxytryptamine-gated cation-selective signalling pathway [EXACT]
5-HT-gated cation-selective signalling pathway [EXACT]

Relationship:
is_a GO:0007210 serotonin receptor signaling pathway

GOC ID: bhm
PMID:27764665, 25392484

dbxref: [please check syntax as I haven't made a request with the new DB and ACs!]
complexportal:CPX-2175 [no typo, autogeneration of new IDs made some jump here...]
complexportal:CPX-271
complexportal:CPX-272
complexportal:CPX-273
complexportal:CPX-274
complexportal:CPX-275
complexportal:CPX-276
complexportal:CPX-277
complexportal:CPX-278

--
Also:
re-instate
GO:1990806 obsolete ligand-gated ion channel signaling pathway
and move all ion channels as children. Can you find them by inference or do I have to look for them???

**Comment by bmeldal** [comment]
GO:1990806 obsolete ligand-gated ion channel signaling pathway

I found 8 complexes already annotated to this term from before the obsoletion. Do I delete these annotation (or move to a parent) or will be re-instate as discussed above?

**Comment by pgaudet** [comment]
@ukemi 
I have made the changes requested here - but before I restore
GO:1990806 obsolete ligand-gated ion channel signaling pathway
I was curious to know what it had not passed the termgenie vetting ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@bmeldal can you tell me which children should be moved under 
GO:1990806 ligand-gated ion channel signaling pathway

I cannot find other terms that have 'gated' and 'pathway'. 

Thanks, Pascale

**Comment by ukemi** [comment]
@bmeldal, it looks like you requested the original term. Do you remember if you withdrew the request or if there was discussion about why it was not vetted?

**Comment by bmeldal** [comment]
Ok, now I'm utterly confused:

@ukemi and I decided to delete the request at the TG stage because the acetylcholine receptor signaling effect was apparently independent of the ion channel activity. But it's the ion transmembrane transfer that affects the membrane polarisation and subsequent signal activation so without the ion transfer no intracellular signal would be activated. So, the ligand binding and subsequent ion transfer are the start of the signaling pathway. 
This applies to other ligand-gated ion channels, such as serotonin receptors, amiloride-sensitive sodium channel complex, I(KACh) inward rectifier potassium channel complex or GABA-A receptors (those are the families I found in CP). Beware, there are also voltage-gates ion channels that are NOT part of this group!


**Email trail:**

I think you can obsolete the term. I was going to put it in SF yesterday and when it was down with no timeline given by SF I decided to make it anyway - what a blunder!

But is it depolarisation of regulation of ~?

Thanks for picking up on it! Now I have to change the annotation in 12 complexes that I have created in the meantime!

Birgit

**Comment by pgaudet** [comment]
Hi @bmeldal 
At the top you wrote 
> GO:1990806 obsolete ligand-gated ion channel signaling pathway
But it's missing a comment why we shouldn't have LGIC-type pathway terms.


Anyway I can remove it and add some notes from the email exchange above. Is this what you want ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
No, I can't follow mine and David's argument from 4 years ago. Without the ion transport there wouldn't be a signal so I think the pathway exists. Change in membrane polarisation is just one step along the cascade, preceded by ion transport. I think the term should stand.

When I commented that there is no comment on the obsoletion note I didn't remember that I originally requested it. When David pointed that out (cos he could see my GOC ID in the system), I went back to my emails and found our conversation. As TG didn't have a commenting system it was done by email but I keep them all :)

**Comment by ukemi** [comment]
Hi @bmeldal. It's good you keep all the emails, I looked and couldn't find it in mine. I thought a bit about this yesterday. I think if we make signaling terms like this, how will they fit with things like synaptic transmission? Are they completely separate? Clearly the voltage gated channels that are downstream of the ligand-gated channels are part of synaptic transmission. Would we consider that a type of signaling pathway?

**Comment by bmeldal** [comment]
Not being an expert in signalling I would think a signalling pathway starts with the activation of the first receptor (whether it's ligand- or voltage-gated) and finishes with the signal arriving at its destination, often transcriptional activation of a target gene or something a neurotransmitter eventually activates. What does the signalling WG say? Or the synapse group? I have not gotten involved in it (there are only so many things one can follow ;-) ) 

I guess, if you want to be pedantic, a signal never stops as one action triggers another action and so forth and only really stops when the host is dead ;-) And that triggers a saprophytic reaction :0

Remember the question of how big a complex could be and where to stop???

Oh, the beauty of biology (=life), nothing is ever clear-cut or easy!

**Comment by pgaudet** [comment]
Hi  	@Pimmelorus
Can you please have a look at this ticket and let us know if you think relations are missing between these terms ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Looks like everything was done that was requested here.
