### ISSUE TITLE
missing relation GO:0061821 telomeric D-loop binding child of GO:0061820 telomeric D-loop disassembly?

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12944]
or better suggestions

**Comment by ukemi** [comment]
Is this always true? Do things bind that are not involved in disassemby? What about just things that localize there or are involved in assembly?

**Comment by ukemi** [comment]
@NancyCampbell 

A quick search of the literature suggests that there might be binding proteins that stabilize the loop, do you agree?

**Comment by NancyCampbell** [comment]
yes you are right.

**Comment by ukemi** [comment]
OK. I will close this one then.
