### ISSUE TITLE
EC:2.3.2.2 > GO:gamma-glutamyltransferase activity mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12956]
Hi,

Could you check this mapping against this ticket?

https://github.com/geneontology/go-annotation/issues/1514#issuecomment-274910478

thanks

val

**Comment by ukemi** [comment]
This mapping looks ok based on the definition.

**Comment by ValWood** [comment]
I think the problem is that the EC number is applied to the incorrect proteins, so that is still a UniPROT problem?

**Comment by ValWood** [comment]
Oh this is wrong tracker though... closing

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-annotation/issues/1519
