### ISSUE TITLE
add a parent for estrogen and androgen biosynthetic processes?

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12953]
GO:0006702 androgen biosynthetic process is "the chemical reactions and pathways resulting in the formation of **_androgens, C19 steroid hormones_** that can stimulate the development of male sexual characteristics, and GO:0006703 estrogen biosynthetic process is "The chemical reactions and pathways resulting in the formation of **_estrogens, C18 steroid hormones_** that can stimulate the development of female sexual characteristics", but neither term has  GO:0006694 steroid biosynthetic process as an is_a parent or other ancestor. (Meanwhile, GO:0006694 steroid biosynthetic process does have GO:0006700 C21-steroid hormone biosynthetic process as an is_a child, so it looks like this kind of parent - child relationship ought to be OK.

Without the added parentage, grouping androgen and estrogen synthetic pathways with ones for other steroid pathways conflicts with GO.

Thanks

**Comment by ukemi** [comment]
https://github.com/ebi-chebi/ChEBI/issues/3257

**Comment by ukemi** [comment]
I went ahead and asserted all the steroid parents for metabolism, biosynthesis and catabolism. At some point hopefully they will be inferred.
