### ISSUE TITLE
TPV: box H/ACA RNP complex (causes 2,866 erroneous telomerase annotations)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12951]
box H/ACA RNP complex

is part of
 GO:0005697 telomerase holoenzyme complex

I think this is a mistake? It should only be
 GO:0090661	box H/ACA telomerase RNP complex

This is causing ALL  "box H/ACA RNP complex" to be erroneously annotated to "telomerase complex"
GOA 2,866 for 2,376 proteins 

I'm not even sure that this term  should be part of telomerase:
  GO:0090661	box H/ACA telomerase RNP complex
 is it describing a complex which is involved in telomerase assembly, not the final  telomerase complex  isn't it? 
Does the telomerase version even warrant a complex term? Isn't telomerase a substrate of  a variant of the canonical H/ACA RNP complex ?

**Comment by ukemi** [comment]
Could it be because this term is the holoenzyme? This is not at all my field of expertise.
@bmeldal @NancyCampbell  ?

**Comment by ukemi** [comment]
But you are correct, we do have the telomerase-specific subtype. So from the telomerase experts, is it a part of the holoenzyme?

**Comment by NancyCampbell** [comment]
Agree with David. I am fairly sure that the relationship between GO:0072588 box H/ACA RNP complex and GO:0005697 telomerase holoenzyme complex should not be there. This relationship should be between  GO:0090661 box H/ACA telomerase RNP complex and GO:0005697 telomerase holoenzyme complex. or better suggestions?

**Comment by bmeldal** [comment]
I think these are @NancyCampbell 's term. 

From what I can see in QuickGO:
GO:0090661 box H/ACA telomerase RNP complex is part_of GO:0005697 telomerase holoenzyme complex via its is_a parent GO:0072588 box H/ACA RNP complex. But I don't think this holds true. From the Def GO:0090661 appears to have the RNA component in common with GO:0005697 but GO:0090661 does not necessarily contain a subset of proteins that are all part_of GO:0005697. 
Hence, I concur with @ValWood here.

We have the Telomerase catalytic core complex in the CP (from Nancy):
http://www.ebi.ac.uk/intact/complex/details/EBI-10045577
I think Nancy is working on other telomerase complexes at the moment.

I don't really like the use of 'holoenzyme' unless it clearly defines the super-complex that has constituent sub-complexes that may have their own roles in the cell. Here, it looks like it's ok, as the is_a child GO:0000333 telomerase catalytic **core** complex is clearly defined as the sub-complex containing only the telomerase and RNA (which is the one curated in CP).

**Comment by bmeldal** [comment]
Posted just after Nancy!

**Comment by ukemi** [comment]
So is the action to remove the part_of relationship between 'box H/ACA RNP complex' and 'telomerase holoenzyme complex' and add a part_of relationship between 'box H/ACA telomerase RNP complex' and 'telomerase holoenzyme complex'?

**Comment by ValWood** [comment]
The isn't part of the telomerase complex
GO:0090661	box H/ACA telomerase RNP complex

I still don't think  it should exist. Telomerase is a substrate.

**Comment by dosumis** [comment]
As far as I can gather, the telomerase complex has a different RNA to its two sibling classes- making it a different complex.   The parent class if neutral about which RNA is present (although the def should be made clearer.

**Comment by bmeldal** [comment]
I'm with Val, remove the erroneous part_of relationship altogether. I don't think the H box/ACA complexes are children of any telomerase complex.

**Comment by ukemi** [comment]
@NancyCampbell are you ok with this?

**Comment by NancyCampbell** [comment]
Yes and no.

dyskerin, NOP10, NHP2, and GAR1 plus RNA=H box/ACA complexes which has nothing to do with telomerase i agree.

however,

dyskerin, NOP10, NHP2, and GAR1 plus TERC=H box/ACA telomerase RNA complex which is part of the telomerase. This complex has a unique component and a unique funciton which is different to other H box/ACA complexes which constitute two parts: sca and sno.

PubMed
In vitro assembly of human H/ACA small nucleolar RNPs reveals unique features of U17 and telomerase RNAs.
PMID:10757788

There is a review here:

Nat Rev Genet. 2012 Oct;13(10):693-704. doi: 10.1038/nrg3246. Epub 2012 Sep 11.
The telomere syndromes.
Armanios M1, Blackburn EH.

![image](https://cloud.githubusercontent.com/assets/12081136/22253894/0f622cba-e24b-11e6-94bb-c9395c8b177d.png)

**Comment by ukemi** [comment]
But if there is a part_of relationship, it needs to be true always, for every instance of the complex.

**Comment by NancyCampbell** [comment]
would this not be true if the relationship is between H box/ACA telomerase RNA complex and telomerase holoenzyme complex? (i.e. not its parent which what it looks like now and it was agreed to remove it).

**Comment by ukemi** [comment]
So would this:
dyskerin, NOP10, NHP2, and GAR1 plus RNA=H box/ACA complexes which has nothing to do with telomerase i agree.

be annotated to the parent and this:

dyskerin, NOP10, NHP2, and GAR1 plus TERC=H box/ACA telomerase RNA complex which is part of the telomerase. 

be annotated to the telomerase-specific complex and always be a part_of telomerase?

**Comment by NancyCampbell** [comment]
yes

**Comment by ValWood** [comment]
Ah OK, do yeast have this too? any ideas. We have all of the subunits except I can't find  dyskerin

**Comment by bmeldal** [comment]
That sounds ok - with the extra explanation. 

@NancyCampbell could you suggest a better def for GO:0090661 box H/ACA telomerase RNP complex, please? At the moment it doesn't sound as if it's a sub-complex of the telomerase holoenzyme. 

I also think, given that GO:0090661 box H/ACA telomerase RNP complex has a different composition and quite definitely a different function from GO:0072588 box H/ACA RNP complex, it might have to lose that is_a relationship. If we go for that change we'll also have to change the def of GO:0072588 to restrict it to its pseudouridylation activity.

It's rather trick, the two H box/ACA type-complexes are structurally similar but differ in composition and function and we decided to group complexes in GO by 
1. function (activity)
2. composition

**Comment by ValWood** [comment]
I found the pombe dyskerin, this is the pseudouridylate synthase Cbf5

isn't that absent from the telomerase, is that correct?

**Comment by NancyCampbell** [comment]
current 

GO:0090661 box H/ACA telomerase RNP complex
A box H/ACA ribonucleoprotein complex that contains the RNA component of vertebrate telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell.

suggestion or better
GO:0090661 box H/ACA telomerase RNP complex
A box H/ACA ribonucleoprotein complex that contains TERC (the RNA component of vertebrate telomerase TERT), dyskerin, NOP10, NHP2, and GAR1. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell. This complex together with TERT form the telomerase holoenzyme complex which is essential for the replication of chromosome termini in most eukaryotes.

**Comment by NancyCampbell** [comment]
@bmeldal 

"I also think, given that GO:0090661 box H/ACA telomerase RNP complex has a different composition and quite definitely a different function from GO:0072588 box H/ACA RNP complex, it might have to lose that is_a relationship. "

I disagree unless there is a better suggestion on how to show the common aspects in content and structure between the two? After all, they share 4 out of 5 components!! 

currently the definition of GO:0072588 contains a reference to the two functions: "... Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity......".

but I do see your point in context of this ... " ....we decided to group complexes in GO by 1. function (activity) 2. composition".

**Comment by krchristie** [comment]
Perhaps the definition of "GO:0072588 - box H/ACA RNP complex" is too specific. It seems useful and normal in GO to have a parent class that would group various different types of box H/ACA RNPs, but this definition seems too specific right now.

**Comment by ukemi** [comment]
OK. I did not change the def. I we want to change it, please suggest a new one. I think based on what Nancy has added, I have moved the part of and capable relations from the parent term to the telomerase-specific term.The definition of the parent term seems to cover all of the processes to which these complexes contribute functions. The children now each are connected to what I think are the right processes.   I hope this is ok.

name:box H/ACA RNP complex
synonym: "box H/ACA snoRNP pseudouridylase complex" RELATED [GOC:mah]
 synonym: "sRNP complex" NARROW [GOC:mah, PMID:17284456, PMID:20227365]
 is_a: GO:0005732 ! small nucleolar ribonucleoprotein complex
-relationship: capable_of_part_of GO:0032212 ! positive regulation of telomere maintenance via telomerase
-relationship: part_of GO:0005697 ! telomerase holoenzyme complex
 created_by: midori
 creation_date: 2011-02-10T01:43:37Z
 
@@ -452039,6 +452037,8 @@
name:box H/ACA telomerase RNP complex
 namespace: cellular_component
 def: "A box H/ACA ribonucleoprotein complex that contains the RNA component of vertebrate telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell." [GOC:BHF, GOC:BHF_telomere, GOC:jbu, PMID:22527283]
 is_a: GO:0072588 ! box H/ACA RNP complex
+relationship: capable_of_part_of GO:0032212 ! positive regulation of telomere maintenance via telomerase
+relationship: part_of GO:0005697 ! telomerase holoenzyme complex
 created_by: tanyaberardini
 creation_date: 2015-09-21T14:46:16Z
