### ISSUE TITLE
cell projection leading edges

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12959]
I would like to see "leading edge of growth cone” added to the GO ontology under the parent term "peripheral region of growth cone” (GO:0090725). The definition could be "That part of the growth cone which represents the distal part of the structure.” Examples can be found in PMID:10797548.

I would also like to see "leading edge of lamellipodium” added to the GO ontology under the parent terms "cell projection part” (GO:0044463) (is_a) and “lamellipodium (GO:0030027) (part_of). The definition could be "That part of the lamellipodium which represents the distal part of the structure.” Examples can be found in PMID: 22339865.

**Comment by ukemi** [comment]
Hi Stan,

We currently have 'cell leading edge'-The area of a motile cell closest to the direction of movement.

Does it make more sense to have two children of this: 'growth cone leading edge' and 'lamellipodium leading edge' and simple define them as a cell leading edge that is part of a growth cone and lamellipodium respectively? We could make the former part_of "peripheral region of growth cone”.

**Comment by slaulederkind** [comment]
Yes, that sounds good.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061850
+name: growth cone leading edge
+namespace: cellular_component
+def: "That part of the growth cone which represents the distal part of the structure." [PMID:10797548]
+intersection_of: GO:0031252 ! cell leading edge
+intersection_of: part_of GO:0090725 ! peripheral region of growth cone
+
+[Term]
+id: GO:0061851
+name: leading edge of lamellipodium
+namespace: cellular_component
+def: "That part of the lamellipodium which represents the distal part of the structure." [PMID: 22339865]
+intersection_of: GO:0031252 ! cell leading edge
+intersection_of: part_of GO:0030027 ! lamellipodium
