### ISSUE TITLE
NTR: CENP-T-W-S-X  complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12952]
refs
https://www.ncbi.nlm.nih.gov/pubmed/22304917 original Cell paper
https://www.ncbi.nlm.nih.gov/pubmed/22304909 opinion

follow ups:
https://www.ncbi.nlm.nih.gov/pubmed/24234442
https://www.ncbi.nlm.nih.gov/pubmed/24522885

Def:
A histone-variant containing protein complex which forms a centromere specific nucleosomal structure, involved in centromeric chromatin organization.

Can probably be improved:

Parent "chromatin assembly complex" but this is obsolete. I missed that- can't find the obsoletion on git hub either.....
What do we use instead? (no recommendations in old terms)

**Comment by mah11** [comment]
> Parent "chromatin assembly complex" but this is obsolete. I missed that- can't find the obsoletion on git hub either.....

You didn't miss it - you "absolutely support[ed]" it ;)

#10098 & GO list thread starting with https://mailman.stanford.edu/pipermail/go-consortium/2013-January/019588.html

**Comment by ValWood** [comment]
Well I had totally forgotten about this. I guess really the complex I am requesting is a type of nucleosome?

**Comment by ukemi** [comment]
is_a 'nucleosome' or just 'protein complex'?
part_of 'chromosome, centromeric region'?
capable_of_part_of 'CENP-A containing chromatin organization' or just 'chromatin organization'?

**Comment by ValWood** [comment]
For capable_of I'm not sure
http://rsob.royalsocietypublishing.org/content/4/2/130229

Reactome call it 
CENP-A containing chromatin assembly 

The different types of chromatin have a role in switching centromeric heterochromatin in between different functional states (replication competent and kinetochore assembly competent). Probably the nomenclature will need to be revised in the future....

I'm only requesting this term because there was some confusion about the different complexes that the human  Fanconia Anemia proteins were annotated to. This complex is referred to in the entry but not annotated

http://www.uniprot.org/uniprot/A8MT69
I said I would request it.

**Comment by ukemi** [comment]
but in your suggested definition you say involved in 'centromeric chromatin organization'.

**Comment by ValWood** [comment]
Yep I was being conservative...probably organization is better for now...

**Comment by ukemi** [comment]
[Term]
+id: GO:0061838
+name: CENP-T-W-S-X complex
+namespace: cellular_component
+def: "A histone-variant containing protein complex which forms a centromere specific nucleosomal structure, involved in centromeric chromatin organization." [PMID:22304909, PMID:22304917]
+is_a: GO:0032991 ! macromolecular complex
+relationship: capable_of_part_of GO:0061641 ! CENP-A containing chromatin organization
+relationship: part_of GO:0000775 ! chromosome, centromeric region
