### ISSUE TITLE
dendritic spine cytoplasm

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12965]
I would like to see "dendritic spine cytoplasm” added to the GO ontology under the part_of parent term "dendritic spine” (GO:0043197) and the is_a parent term “cytoplasm” (GO:0005737).  The definition could be "The region of the neuronal cytoplasm located in dendritic spines.” Example can be found in PMID:15673667.

**Comment by ukemi** [comment]
Also changed the logical definition of dendrite cytoplasm to give more automated inferences.

name: dendrite cytoplasm
namespace: cellular_component
 def: "All of the contents of a dendrite, excluding the surrounding plasma membrane." [GOC:mah]
 synonym: "dendritic cytoplasm" EXACT []
-is_a: GO:0032838 ! cell projection cytoplasm
-is_a: GO:0097458 ! neuron part
-intersection_of: GO:0032838 ! cell projection cytoplasm
+intersection_of: GO:0005737 ! cytoplasm
 intersection_of: part_of GO:0030425 ! dendrite
-relationship: part_of GO:0030425 ! dendrite
 
 [Term]
 id: GO:0032840
@@ -405335,6 +405332,14 @@
 relationship: part_of GO:0043005 ! neuron projection
 
 [Term]
+id: GO:0061846
+name: dendritic spine cytoplasm
+namespace: cellular_component
+def: "The region of the neuronal cytoplasm located in dendritic spines." [PMID:15673667]
+intersection_of: GO:0005737 ! cytoplasm
+intersection_of: part_of GO:0043197 ! dendritic spine
