### ISSUE TITLE
chromosome, centromeric core domain logical definition

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#12966]
I recently removed the logical definition of 'chromosome, centromeric core domain', which was 'chromosomal region' and ('coincident with' some regional_centromere) because it was not specific enough.
It might be correct if we changed it to 'chromosomal region' and ('coincident with' some regional_centromere_central_core).

**Comment by mah11** [comment]
That sounds sensible for pombe, which has that kind of centromere.

**Comment by ukemi** [comment]
Requested SO term import in imports_requests.obo

+[Term]
+id: GO:0000000 ! fake
+relationship: needs SO:0001796

**Comment by ukemi** [comment]
Added to gene_ontology_write

 def: "The innermost portion of the centromeric region of a chromosome, encompassing the core region of a chromosome centromere and the proteins that bind to it." [GOC:mah, GOC:vw]
 synonym: "chromosome, centric core region" RELATED []
 synonym: "chromosome, centromeric core region" EXACT [GOC:vw]
-is_a: GO:0044427 ! chromosomal part
+intersection_of: GO:0098687 ! chromosomal region
+intersection_of: coincident_with SO:0001796 ! regional_centromere_central_core
 relationship: part_of GO:0000775 ! chromosome, centromeric region

**Comment by ukemi** [comment]
I cannot find any documentation of requesting import of terms from external ontologies, so I am tagging this with documentation.

**Comment by ukemi** [comment]
Duplicate of #13433
