### ISSUE TITLE
more children for GO:1901568 fatty acid derivative metabolic process

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12968]
GO:1901568 fatty acid derivative metabolic process ("The chemical reactions and pathways involving fatty acid derivative") has GO:0006690 icosanoid metabolic process as a child, consistent with using the term to mean a process that converts a fatty acid to a related molecule. That logic would allow  GO:0035337 fatty-acyl-CoA metabolic process,  GO:0010166 wax metabolic process, and perhaps GO:1902224 ketone body metabolic process also to become children of GO:1901568. (At least in humans, ketone bodies are synthesized from acetyl CoA largely derived from fatty acid breakdown, so it may be a stretch.)

That would be useful because all of these processes are often grouped with lipid metabolism and the requested is_a links would give this grouping a basis in GO.

**Comment by ukemi** [comment]
It would be nice if we could get all of these through the reasoning with ChEBI. I think the right way to do this would be to expand on the formal representation of the pathways in the ontology similar to what we did for glycolysis. This way, we could make participants that are fatty acid derivatives in each of the pathwyas and they should be grouped correctly. Lipid metabolism has been on the horizon for some time now.

**Comment by ukemi** [comment]
@deustp01  I requested the chemicals to be classified as fatty acid derivatives on the ChEBI tracker. Once that happens, they will be automatically classified in GO.
