### ISSUE TITLE
neuron projection branch point

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12964]
I would like to see "neuron projection branch point” added to the GO ontology under the parent term "neuron projection” (GO:0043005).  It would also be a new parent of “dendritic branch point” (GO:1990033).  The definition could be "The location where a secondary projection arises from a neuron projection.” Example can be found in PMID:25586189.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061845
+name: neuron projection branch point
+namespace: cellular_component
+def: "The location where a secondary projection arises from a neuron projection." [PMID:25586189]
+is_a: GO:0044463 ! cell projection part
+relationship: part_of GO:0043005 ! neuron projection
