### ISSUE TITLE
	InterPro:IPR018767 mapping to nuclear export GO:0006406 GO:0006611

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12963]
Hi,

work in pombe and cerevisiae indicates that Brr6 has a role in nuclear morphology affecting nuclear pore biogenesis, insertion of spb into nuclear membrane.
The observed mRNA export defect is a phenotype only (brr6 has no identified direct role in nucleocytoplasmic transport in a normal cell)

thanks

Val

**Comment by ukemi** [comment]
Wrong tracker?

**Comment by ValWood** [comment]
yep!
