### ISSUE TITLE
parent of glycolytic process, query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12967]
glycolytic process has the parent 
"nucleotide phosphorylation"
which make is a child of "phosphorylation"

Is that correct? It  seems  the wrong way around, that phosphorlation events are part of glycolysis?

**Comment by deustp01** [comment]
ADP gets phosphorylated at two points. Does that count?

**Comment by ukemi** [comment]
Yes. That is why. The phosphorylation of ADP to ATP is considered a nucleotide phosphorylation. This makes sense because from the overall view of glycolysis, one of the 'objectives' is to make ATP.
