### ISSUE TITLE
establishment of microtubule organizing center localization

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12960]
I would like to see "establishment of microtubule organizing center localization” added to the GO ontology under the parent terms "microtubule organizing center organization” (GO:0031023) and “establishment of localization in cell” (GO:0051649). The definition could be "The process that determines the position of microtubule organizing centers in a cell.” Synonyms: microtubule organizing center polarity; MTOC polarity.  Example can be found in PMID:21281821.

**Comment by slaulederkind** [comment]
I would like to see "establishment of microtubule organizing center localization” added to the GO ontology under the parent terms "microtubule organizing center organization” (GO:0031023) and “establishment of localization in cell” (GO:0051649). The definition could be "The process that determines the position of microtubule organizing centers in a cell.” Synonyms: establishment of  microtubule organizing center polarity; establishment of MTOC polarity. Example can be found in PMID:21281821.

**Comment by ukemi** [comment]
Hi Stan,

Would it make more sense to just create a term 'microtubule organizing center localization' in termgenie so that the reasoner can sort out all the correct relations?

-D

**Comment by slaulederkind** [comment]
Hi David, That sounds good, but I didn’t see a “localization” template.  Stan

Stanley J. F. Laulederkind, Ph.D.
Rat Genome Database
Human Molecular Genetics Center
Medical College of Wisconsin
8701 Watertown Plank Rd
Milwaukee WI 53226
(Phone) 414-955-7513
(Fax) 414-456-6516

**Comment by ukemi** [comment]
Ooops. You're right! The one we have is for chemicals.  I will make the term.

MTOC localization- Any process in which the microtubule organizing center is transported to, and/or maintained in, a specific location within the cell.

**Comment by ValWood** [comment]
Could it go  as the parent of
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0070631#term=ancchart
GO:0070631 spindle pole body localization

(note that  localization isn't a type of organization)

**Comment by ukemi** [comment]
The reasoner puts it as a type of localization and a parent of 'spindle pole body localization' and 'centrosome localization'.

**Comment by ukemi** [comment]
You are correct, it is not a type of organization. But the polarization of the structure itself would be a type of organization. Which one do we want?

**Comment by ukemi** [comment]
Looking at the abstract of the paper, it looks like the localization of the MTOC is an indication of the polarity of the cell. So I think we want the localization term.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061842
+name: microtubule organizing center localization
+namespace: biological_process
+def: "Any process in which the microtubule organizing center is transported to, and/or maintained in, a specific location within the cell." [PMID:21281821]
+synonym: "microtubule organizing center polarity" NARROW []
+synonym: "MTOC localization" EXACT []
+synonym: "MTOC polarity" NARROW []
+intersection_of: GO:0051179 ! localization
+intersection_of: transports_or_maintains_localization_of GO:0005815 ! microtubule organizing center

**Comment by ValWood** [comment]
perfect ;)
