### ISSUE TITLE
telomere capping and TIFs: add to definition or synonym to neg. reg. child or better advice please

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12974]
In PMID     27500188
Bio Protoc. 2015 Nov 20;5(22). pii: e1656.
Telomere Dysfunction Induced Foci (TIF) Analysis.
Mender I1, Shay JW2.

author states: 'DNA damage foci at uncapped telomeres are referred to as Telomere dysfunction Induced Foci (TIFs) (de Lange, 2005  ; Takai et al., 2003'

de Lange, 2005 PubMed: 16166375
Genes Dev. 2005 Sep 15;19(18):2100-10.
Shelterin: the protein complex that shapes and safeguards human telomeres.
de Lange T1.

Takai et al., 2003 PubMed 1295695
Curr Biol. 2003 Sep 2;13(17):1549-56.
DNA damage foci at dysfunctional telomeres.
Takai H1, Smogorzewska A, de Lange T.

Telomere dysfunction Induced Foci (TIFs) comes up a lot in human/mammal papers **as a term** in experiments describing uncapped telomeres and it would be useful to refer somewhere in the ontology to Telomere dysfunction Induced Foci (TIFs) to show the close connection between telomere uncapping and TIFs, though not sure what the best way to do this is:

option 1:
edit the definition of GO:0016233 telomere capping by adding maybe this or better: '....DNA damage foci at uncapped telomeres are referred to as Telomere dysfunction Induced Foci (TIFs)'

option 2:
add Telomere dysfunction Induced Foci (TIFs) as a synonym to GO:1904354 negative regulation of telomere capping child_of telomere capping  

can synonyms be added to regulation terms?! Please advise. Thanks.

Please let me know if you need any more info. Thanks.

GO:0016233
Name 	telomere capping
Ontology 	Biological Process
Definition 	A process in which telomeres are protected from degradation and fusion, thereby ensuring chromosome stability by protecting the ends from both degradation and from being recognized as damaged DNA. May be mediated by specific single- or double-stranded telomeric DNA binding proteins. 

GO:1904354
Name 	negative regulation of telomere capping child_of telomere capping
Ontology 	Biological Process
Definition 	Any process that stops, prevents or reduces the frequency, rate or extent of telomere capping.

**Comment by tberardini** [comment]
I don't think it's appropriate to add information about TIFs in the terms about normal telomore capping processes.  How might this aid in annotation or data retrieval?  Why would someone be searching GO terms or annotations with 'Telomere dysfunction Induced Foci'?  Perhaps this would be better captured as a phenotype term (not sure which ontology though).

**Comment by NancyCampbell** [comment]
and as a syonym as outlined in above:

option 2:
add Telomere dysfunction Induced Foci (TIFs) formation as a synonym to GO:1904354 negative regulation of telomere capping child_of telomere capping

**Comment by ValWood** [comment]
I think we should keep abnormal processes and descriptions out of GO as far as possible  in line with Michael's original vision. GO represents normal processes/ biological objective, not pathological situations.

We should also consider that  vast majority of the experiments on  telomere function in mammals are conducted on cell lines which are orders of magnitude beyond their normal replicative lifespan, and so  lots of the effects at telomeres observed (which are very informative about the normal processes), are not normal, but are consequences of and responses to  unregulated division and severe ageing. 

Curation is complicated.....

**Comment by ukemi** [comment]
I agree with Tanya and Val (and Michael).

**Comment by NancyCampbell** [comment]
Thanks for the advice.
