### ISSUE TITLE
MP GO:0071840 cellular component organization or biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12970]
Is there a reason why
 GO:0071840 cellular component organization or biogenesis
is not a cellular process?

**Comment by ukemi** [comment]
Probably because there are examples of this that are not carried out 'at a cellular level'.  Hopefully 'cellular process' is due for a makeover.
#12849

**Comment by ukemi** [comment]
Example, plasma lipoproteins.
