### ISSUE TITLE
Add taxon restriction for carotenoid/ pombe and S. cerevisae

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12972]
After speaking to metabolomics experts, we don't think that either pombe or cerevisiae  naturally produce carotenoids

	Please add never_in taxon restriction to these 2 yeast (am picking up mappings which I'll deal with separately).

Component GO:0043702	carotenoid vesicle
Process	 GO:0016116	carotenoid metabolic process	
Process	 GO:0016118	carotenoid catabolic process	
Function	 GO:0046608	carotenoid isomerase activity	
Function	 GO:0010436	carotenoid dioxygenase activity	
Process	 GO:0016117	carotenoid biosynthetic process

Note: Some fungi do produce carotenoids
Rhodotorula and Rhosporidium spp.  are fed to farmed salmon to ensure pink flesh

**Comment by tberardini** [comment]
Added restrictions for 
Component GO:0043702 carotenoid vesicle
Process GO:0016116 carotenoid metabolic process
Function GO:0046608 carotenoid isomerase activity
Function GO:0010436 carotenoid dioxygenase activity

+relationship: never_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
+relationship: never_in_taxon NCBITaxon:4932 ! Saccharomyces cerevisiae


Process GO:0016117 carotenoid biosynthetic process
Process GO:0016118 carotenoid catabolic process

Will inherit the restriction from carotenoid metabolic process
