### ISSUE TITLE
definition of  GO:0071704 organic substance metabolic process

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12973]
It's now "the chemical reactions and pathways involving an organic substance, any molecular entity containing carbon" which would appear to include classic intermediary metabolism, which it does, as is_a children, but also metabolism of carbon-containing macromolecules like proteins, RNA, and DNA, which it does not. That distinction seems fine, so could something be added to the organic substance definition to make it explicit, something like Michael Ashburner's distinction between directly or indirectly encoded molecules and unencoded ones. That may not exactly conform to ChEBI, but neither does a silent decision to treat RNA, DNA, and proteins as not containing carbon atoms. If a revised definition would break things, could a comment be added?

**Comment by tberardini** [comment]
@deustp01 : DNA, RNA, and protein metabolism trace their parentage to 'organic substance metabolic process'.  Where's the missing link?

<img width="627" alt="screen shot 2017-01-30 at 3 06 54 pm" src="https://cloud.githubusercontent.com/assets/4998871/22445754/c44a5e34-e6fd-11e6-865f-1a966b11ebb7.png">
<img width="236" alt="screen shot 2017-01-30 at 3 06 29 pm" src="https://cloud.githubusercontent.com/assets/4998871/22445755/c44b078a-e6fd-11e6-9da5-c16ada1f164c.png">
<img width="643" alt="screen shot 2017-01-30 at 3 07 41 pm" src="https://cloud.githubusercontent.com/assets/4998871/22445779/e00e056c-e6fd-11e6-944e-233c80fde72c.png">
