### ISSUE TITLE
NTR: cellular response to very-low-density lipoprotein particle stimulus

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12977]
Re: PMID:7592957, Figure 1.
Results: "...incubation of the cells in N2 medium containing b-VLDL resulted in a markedly different pattern in the outgrowth of neurites from these cells. Apolipoprotein E3-secreting cells incubated with b-VLDL developed long neurites (Fig. 1A), whereas in apoE4-secreting cells, neurite outgrowth was suppressed (Fig. 1B)."

I would like to request a new term  'cellular response to very-low-density lipoprotein particle stimulus'.
It would be a child of 'cellular response to lipoprotein particle stimulus', and a sibling of: 'cellular response to low-density lipoprotein particle stimulus' as well as 'cellular response to high-density lipoprotein particle stimulus'.

![screen shot 2017-01-31 at 15 13 41](https://cloud.githubusercontent.com/assets/16541096/22470932/bbf0c4c8-e7c8-11e6-94d8-3f206e8b0d3a.png)

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090731
+name: cellular response to very-low-density lipoprotein particle stimulus
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a very-low-density lipoprotein particle stimulus." [GOC:bc, GOC:BHF]
+synonym: "cellular response to VLDL particle stimulus" EXACT []
+is_a: GO:0071402 ! cellular response to lipoprotein particle stimulus
+created_by: tanyaberardini
+creation_date: 2017-01-31T17:10:08Z

**Comment by BarbaraCzub** [comment]
Thanks @tberardini 
Would it be possible to change the attribution from [GOC:bc, GOC:BHF] to [GOC:bc, GOC:ARUK]? 
I am currently working on a project funded by Alzheimer's Research UK (ARUK). I should have specified this in my original request. My apologies!
Barbara

**Comment by tberardini** [comment]
Ok, changed.

**Comment by BarbaraCzub** [comment]
Thank you!
