### ISSUE TITLE
response to other organism

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12975]
Alice (@zebrafishembryo ) notes that 'response to other organism' (GO:0051707) is [no longer a subclass of multi-organism process](http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051707#term=history).  This is causing problems for annotators as the need to be able to record the taxon of the 'other' organism in these cases, but this is only allowed for multi-organism processes.

The change may have come from me (although I haven't manage to track it down).  

The might potentially be justified by saying that it covers the process in the responding organism only, but I wouldn't want to be dogmatic about this. 

So, I propose to change back - but this leaves at least one class as a child of both single an multi-organism process: viral induced premature senescence (GO:0090401)

There is (currently) no axiom declaring disjointness between single and multi-organism processes, so this will not cause the build to fail.  But the disjointness probably should be declared.

After discussion with Alice (@zebrafishembryo) I came up with a possible fix:

Rename -> viral-induction of premature senescence
Add logical def: 'modulation by virus of host process' and 'positively regulates' some 'cellular senescence'

But on reflection, I'm not sure this works as it may be an endogenous response to viral infection, rather than something the virus has evolved to induce:

definition "A cellular senescence process associated with the dismantling of a cell as a response to viral infection."^^xsd:string

Not sure of solution.

**Comment by dosumis** [comment]
- [x] Add back classification of 'response to other organism' under 'multi-organism process' @dosumis

**Comment by mcourtot** [comment]
@dosumis: this seems to have been done - close?

**Comment by cmungall** [comment]
I think it should be response is_a single-org process, part-of a 
multi-org process

**Comment by dosumis** [comment]
@tonysawfordebi Is it necessary that a term be a subclassOf multi-organism process in order to specify a second taxon in protein2GO, or can it be a descendant via part\_of ?

**Comment by mcourtot** [comment]
was looking at "killing by virus of host cell during superinfection exclusion" which is a subclass of "response to virus", itself a subclass of "response to other organism". It is defined as "The viral-killing of a host cell by a pre-existing virus in response to a subsequent infection of the host cell by second virus." - if we keep this classification then response to other organism would have to remain a multi-organism process (though I like Chris' proposal better, just pointing out if we go this route there may be a bit of clean-up associated)

**Comment by tonysawfordebi** [comment]
@dosumis P2G checks that a term is either a subclass of multi-organism process or a descendant via part_of.

**Comment by pgaudet** [comment]
@cmungall can this be merged and closed ? Thanks, Pascale

**Comment by pgaudet** [comment]
Oups I didn't check correctly - the relation between  'response to other organism' (GO:0051707) is_a subclass of multi-organism process.

Chnaged relation  @cmungall suggested:  part-of a multi-org process (I cannot find single-organism process). 

Thanks, Pascale

**Comment by pgaudet** [comment]
* When I change 'response to other organism' (GO:0051707) from **is_a** to **part_of** subclass of multi-organism process, we loose 'bearer of some multi-organismal process quality'.
* If we have bearer of some multi-organismal process quality, then automatically we get 'is_a' multiorganism process. 

So I dont think we can make part_of based on the current design patterns. 

@cmungall @ukemi  I propose to keep is_a and close this; ok ?

**Comment by ValWood** [comment]
close?

**Comment by pgaudet** [comment]
Not yet.

**Comment by pgaudet** [comment]
I changed the parent class for 'response to other organism' to 'interspecies interactions between organisms. 

This should fix the rule violation, for example here

http://snapshot.geneontology.org/reports/goa_dog-report.html#gorule-0000015

WARNING - Violates GO Rule: GORULE:0000015: Dual species taxon check -- UniProtKB E2R560 HYAL2 GO:0009615 GO_REF:0000024 ISS UniProtKB:Q12891 P Hyaluronidase HYAL2 protein taxon:9615|taxon:11746 20120222 UniProt

Thanks, Pascale
