### ISSUE TITLE
Two contradictory meanings for "lipoprotein" in GO

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12971]
The first meaning is illustrated by GO:0042157 lipoprotein metabolic process, "the chemical reactions and pathways involving any conjugated, water-soluble protein in which the nonprotein group consists of a lipid or lipids", where "conjugation" means covalent attachment. This term is a child of protein metabolic process.

The second meaning is illustrated by GO:0034377 plasma lipoprotein particle assembly, "the aggregation and arrangement of proteins and lipids to form a plasma lipoprotein particle," where assembly is non-covalent. This term is a child of protein-lipid complex assembly, and thus has no ancestors in common with GO:0042157 until biological_process

The textbook meaning of "lipoprotein" (e.g., Stryer 4th edition pp697-8) is the second one, a close but non-covalent aggregation or complex. Wikipedia (https://en.wikipedia.org/wiki/Lipoprotein) seems confused, following the textbook until the last sentence in this summary paragraph, which appears to encompass proteins covalently modified with lipid moieties:
"A lipoprotein is a biochemical assembly whose purpose is to transport hydrophobic lipid (a.k.a. fat) molecules in water, as in blood or ECF. They have a single-layer phospholipid and cholesterol outer shell, with the hydrophilic portions oriented outward toward the surrounding water and lipophilic portions of each molecule oriented inwards toward the lipids molecules within the particles. Apolipoproteins are embedded in the membrane, both stabilising the complex and giving it functional identity determining its fate. Thus the complex serves to emulsify the fats. Many enzymes, transporters, structural proteins, antigens, adhesins, and toxins are lipoproteins."

At least for humans, the second meaning of lipoprotein is the widely-used one, Could the first one be re-named? Or merged with GO:0006497 protein lipidation "the covalent attachment of lipid groups to an amino acid in a protein"

@RLovering , any thoughts?

**Comment by tberardini** [comment]
Hi Peter,  IIRC, the current term names reflect the attempt to distinguish between 'lipoprotein particle' (think LDL and HDL - even though these are named 'lipoprotein') and 'lipoprotein' (protein with lipid attached).  

One could possibly merge 'lipoprotein biosynthetic process' and 'protein lipidation' but not 'lipoprotein *metabolic* process' with 'protein lipidation'.

**Comment by paolaroncaglia** [comment]
Hi @deustp01,
I confirm what @tberardini wrote about the distinction. I worked on 'lipoprotein _particle_' terms some time ago as related to the extracellular vesicle project, and more recently to fix a few stray inconsistencies, but always as pertinent to lipid particles which we've tried to keep well separate from lipids. (I have a few left to fix which I'll do soon, see https://github.com/geneontology/go-ontology/issues/11504#issuecomment-275157252.)

**Comment by ukemi** [comment]
This is what I remember as well.

**Comment by deustp01** [comment]
That all makes sense. I will try to come up with some synonyms for the lipoprotein protein-covalently-linked-to-lipid term, or a comment to emphasize the distinction.

**Comment by deustp01** [comment]
Maybe add a few words to the definitions (unless these look redundant to everyone else):
GO:0042157 lipoprotein metabolic process, "the chemical reactions and pathways involving any conjugated, water-soluble protein in which the **_covalently attached_** nonprotein group consists of a lipid or lipids."
GO:0034377 plasma lipoprotein particle assembly, "the **_non-covalent_** aggregation and arrangement of proteins and lipids to form a plasma lipoprotein particle."

**Comment by tberardini** [comment]
Added covalently attached to the lipoprotein metabolic/biosynthetic/catabolic process terms.

Added non-covalent to the relevant %lipoprotein assembly' terms.
