### ISSUE TITLE
cofilin-actin rod

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12979]
I would like to see "cofilin-actin rod” added to the GO ontology under the parent term “actin rod” (GO:0031002).  The definition could be "A cellular structure consisting of parallel, hexagonally arranged actin tubules, comprising filamentous actin and disulfide cross-linked cofilin multimers.” Examples can be found in PMID:24760020, PMID:22573689.

**Comment by tberardini** [comment]
Added:

+id: GO:0090732
+name: cofilin-actin rod
+namespace: cellular_component
+def: "A cellular structure consisting of parallel, hexagonally arranged actin tubules, comprising filamentous actin and disulfide cross-linked cofilin multimers." [GOC:sl, PMID:22573689, PMID:24760020]
+is_a: GO:0031002 ! actin rod
+created_by: tanyaberardini
+creation_date: 2017-01-31T17:44:04Z
