### ISSUE TITLE
cell elongation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#12978]
I would like to see “cell elongation” added as a synonym of “unidimensional cell growth” (GO:0009826) and also the following synonyms added: “negative regulation of cell elongation” for “negative regulation of unidimensional cell growth” (GO:0051511),  “positive regulation of cell elongation” for “positive regulation of unidimensional cell growth” (GO:0051512), and  “regulation of cell elongation” for “regulation of unidimensional cell growth” (GO:0051510).  Example in PMID:24093776.

**Comment by ukemi** [comment]
How do these terms differ? Isn't unidimensional cell growth the same as cell elongation?

**Comment by dosumis** [comment]
Looks like Stan's saying they are the same - as this is request for synonym.  If they are the same, I prefer 'cell elongation' as the primary name.

**Comment by ValWood** [comment]
I don't think these are exact? I call can elongate and be growing bipolarly.

I have a bit of a mental block with the "growth" terms though...

Is this about an increase in size? or the direction of growth?

**Comment by mah11** [comment]
Unidimesional means in one dimension, and is not the same as monopolar.

As far as I know, all normal vegetative growth in pombe is unidimensional (the cell diameter doesn't normally change, only the length), both when it's monopolar and when it's bipolar.

**Comment by slaulederkind** [comment]
In the example PMID:24093776, the cells gain length and lose width, such that the total surface area of the cells decrease as elongation occurs.

**Comment by ValWood** [comment]
OK got it....(I still get confused)

So Stan is your observation growth if the cell surface areas decreases?
Or is it morphogenesis?

**Comment by ValWood** [comment]
Ignore me...

**Comment by ukemi** [comment]
Sorry, I didn't notice this was a synonym request. Cell elongation is already listed as a narrow synonym.

**Comment by slaulederkind** [comment]
Requesting for the other three terms.

**Comment by tberardini** [comment]
Added:

+synonym: "regulation of cell elongation" NARROW []

+synonym: "negative regulation of cell elongation" NARROW []

+synonym: "positive regulation of cell elongation" NARROW []
