### ISSUE TITLE
NTR: Tenascin complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12983]
Name: Tenascin complex
Def:
A extracellular matrix complex involved in cell adhesion and cell migration. Typically homotrimeric or homohexameric. In mammals, four complexes exist: Tenascin-C, Tenascin-N (also known as Tenascin-W), Tenascin-X and Tenascin-R.

Comment: An example is Tenascin-N (Q9UQP3) in PMID:17909022 (IDA).

Synonyms:
Tenascin-C [NARROW]
Tenascin-N [NARROW]
Tenascin-W [NARROW]
Tenascin-X [NARROW]
Tenascin-R [NARROW]

Refs:
IntAct:EBI-11789587
IntAct:EBI-13640819
PMID:11731446
PMID:12845616
PMID:23658023
PMID:17909022

Relationships:
is_a GO:0098636 protein complex involved in cell adhesion
part_of GO:0031012 extracellular matrix
capable_of_part_of GO:0030155 regulation of cell adhesion
capable_of_part_of GO:0030334 regulation of cell migration

Thanks,
Birgit

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090733
+name: tenascin complex
+namespace: cellular_component
+def: "A extracellular matrix complex involved in cell adhesion and cell migration. Typically homotrimeric or homohexameric. In mammals, four complexes exist: Tenascin-C, Tenascin-N (also known as Tenascin-W), Tenascin-X and Tenascin-R." [GOC:bm, IntAct:EBI-11789587, IntAct:EBI-13640819, PMID:11731446, PMID:12845616, PMID:17909022, PMID:23658023]
+comment: An example is Tenascin-N (Q9UQP3) in PMID:17909022 (IDA).
+synonym: "Tenascin-C" NARROW []
+synonym: "Tenascin-N" NARROW []
+synonym: "Tenascin-R" NARROW []
+synonym: "Tenascin-W" NARROW []
+synonym: "Tenascin-X" NARROW []
+is_a: GO:0098636 ! protein complex involved in cell adhesion
+relationship: capable_of_part_of GO:0030155 ! regulation of cell adhesion
+relationship: capable_of_part_of GO:0030334 ! regulation of cell migration
+relationship: part_of GO:0031012 ! extracellular matrix
+created_by: tanyaberardini
+creation_date: 2017-02-01T16:29:55Z

**Comment by bmeldal** [comment]
Thanks, Tanya!
