### ISSUE TITLE
xref to EC for GO:0099620, GO:0099621

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12981]
There is a typo and a mistake in the xrefs to EC for a couple of GO terms; I think they should be:
GO:0099620 > EC 2.6.1.87
GO:0099621 > EC 2.4.2.53
Also, GO:0099621 and GO:0103019 seem to be almost identical, just using different synonyms for the name/compounds.

Thanks,
Ingrid

**Comment by tberardini** [comment]
Fixed the typos, thanks @keseler.

@hdrabkin : Can you please check if GO:0099621 and GO:0103019  should be merged?  GO:0103019  is in the range of the set of MetaCyc-based terms you're adding.

**Comment by hdrabkin** [comment]
The two  you cite appear to use a different EC number;
GO:0099621:  EC:2.6.1.87
GO:0103019:  EC:2.4.2.53
I don't vet during addition of these terms other than check if EC is already used, name is the same, metacyc xrefs are the same.  The 0103019 passed the tests.  If there are any problems I will pass them on to Peifeng, who can make a decision. However, one of the things she did to determine if she needed a term was to search for the EC number. The EC for 0103019 was apparently NOT in GO.

**Comment by tberardini** [comment]
@hdrabkin :  Ingrid's initial comment stated (correctly) that the EC number for GO:0099621 was incorrect (it was EC:2.6.1.87).  I updated it to be the correct one (after checking) to EC:2.4.2.53.  Which puts us at this state:

[Term]
id: GO:0099621
name: undecaprenyl-phosphate 4-deoxy-4-formamido-L-arabinose transferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-4-deoxy-4-formamido-beta-L-arabinopyranose + ditrans,octacis-undecaprenyl phosphate = UDP + 4-deoxy-4-form\
amido-alpha-L-arabinopyranosyl ditrans,octacis-undecaprenyl phosphate." [GOC:al, GOC:dos, PMID:11706007, PMID:15695810]
synonym: "Ara4FN transferase activity" EXACT []
synonym: "undecaprenyl-phosphate Ara4FN transferase activity" EXACT []
xref: EC:2.4.2.53
is_a: GO:0016763 ! transferase activity, transferring pentosyl groups

[Term]
id: GO:0103019
name: undecaprenyl phosphate-L-Ara4FN transferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-4-deoxy-4-formamido-beta-L-arabinopyranose + ditrans,polycis-undecaprenyl phosphate <=> 4-deoxy-4-formamid\
o-alpha-L-arabinopyranosyl ditrans,polycis-undecaprenyl phosphate + UDP" [EC:2.4.2.53]
xref: EC:2.4.2.53
xref: MetaCyc:RXN0-3521
is_a: GO:0016763 ! transferase activity, transferring pentosyl groups

Does that change your opinion?  Yes, we should consult with Peifen, if necessary.

**Comment by hdrabkin** [comment]
If it had that I would have not put it in to begin with; I would have merely added the metacyc ref.
I would merge them, which I do NOT feel comfortable with using Protege or OE at this time,
Actually, if she had found EC:2.4.2.53 to begin with should wouldn't have requested the new term.

**Comment by tberardini** [comment]
I'll do the merge, Harold, no worries.  I'm sure Peifen would have found the term had the correct EC number been associated with it in the first place.  But the correction didn't happen till yesterday.  In any case, thanks for the confirmation that the merge should take place.

**Comment by hdrabkin** [comment]
thanks much;

**Comment by tberardini** [comment]
Merged the two terms (GO:0103019 into GO:0099621).
