### ISSUE TITLE
new term Telomere maintenance via telomere trimming

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12984]
PMID     27918544
Nat Struct Mol Biol. 2017 Jan
**A balance between elongation and trimming regulates telomere stability in stem cells.**
Rivera T1, Haggblom C1, Cosconati S2, Karlseder J1.

This very recent paper describes **active trimming of telomeres which contributes to telomere maintenance** i.e. actively making telomeres shorter, 

Author states: "Telomere length maintenance ensures self-renewal of human embryonic stem cells (hESCs) and induced pluripotent stem cells (hiPSCs); however, the mechanisms governing telomere length homeostasis in these cell types are unclear. Here, we report that **telomere length is determined by the balance between telomere elongation, which is mediated by telomerase, and telomere trimming, which is controlled by XRCC3 and Nbs1, homologous recombination proteins that generate single-stranded C-rich telomeric DNA and double-stranded telomeric circular DNA (T-circles), respectively**."

Author states: "We found that reprogramming of differentiated cells induces T-circle and single-stranded C-rich telomeric DNA accumulation, indicating the activation of telomere trimming pathways that compensate telomerase-dependent telomere elongation in hiPSCs". 

Historically, T-circle formation has been mostly associated with ALT cells which are not normal cells (ALT mechanism occurs in 15% of cancer cells). 

However, more recently, evidence emerged which indicates that T-circle formation is part of a normal process which actively shortens telomeres in normal cells. Please note that there are many papers related to T-circle formation but in context of ALT cells which are not normal so are not relevant here. Evidence in normal cells includes:

1. the publication outlined above PMID 27918544: Nat Struct Mol Biol. 2017 Jan
**A balance between elongation and trimming regulates telomere stability in stem cells.**

2. PMID: 21903669 Hum Mol Genet. 2011 **Normal mammalian cells negatively regulate telomere length by telomere trimming.** 

I have not looked outside mammals but there might be more evidence? (or not)? in other organisms (not sure if there is a model for ALT and non-ALT)?

In contrast, telomere lengthening - via telomerase - has long been **the** active process. Hence, I would like advice please. 

Is it approriate to create a

Telomere maintenance via telomere trimming placed between GO:0000723 telomere maintenance and GO:0090656 t-circle formation (or better suggestions).

Please advise. Thanks.

**Comment by tberardini** [comment]
I'm not sure what you mean by " between GO:0000723 telomere maintenance and GO:0090656 t-circle formation (or better suggestions)." but I think we could add 'telomere maintenance via telomere trimming' as a sibling of those two terms and a direct child of 'telomere maintenance'.

The snippet of text you pasted, **"telomere trimming, which is controlled by XRCC3 and Nbs1, homologous recombination proteins that generate single-stranded C-rich telomeric DNA and double-stranded telomeric circular DNA (T-circles), respectively."** suggests that t-circle formation could be part of telomere trimming. Or am I taking this phrase out of context and those two processes (telomere trimming and t-circle formation) are distinctly different?

**Comment by NancyCampbell** [comment]
"but I think we could add 'telomere maintenance via telomere trimming' as ...... a direct child of 'telomere maintenance'."

Yes

"suggests that t-circle formation could be part of telomere trimming." 

Yes

**Comment by tberardini** [comment]
Current arrangement:

<img width="514" alt="screen shot 2017-02-06 at 2 10 57 pm" src="https://cloud.githubusercontent.com/assets/4998871/22668785/e2af442e-ec76-11e6-8e3a-53c5ff86d657.png">

Would this work?

telomere maintenance
--[i] telomere maintenance via base-excision repair
--[i] telomere maintenance via recombination
--[i] telomere maintenance via semi-conservative replication
--[i] telomere maintenance via telomerase
--[i] telomere maintenance via telomere lengthening
**--[i] telomere maintenance via telomere trimming (NEW)**
----**[p]** t-circle formation

formation of extrachromosomal circular DNA
--**[i] t-circle formation**

Can you propose a definition for your term please?

**Comment by NancyCampbell** [comment]
Perfect. Thanks.

can you please add:
GOC:BHF, GOC:BHF_telomere, GOC:nc

How about this:
telomere maintenance via telomere trimming: A process that contributes to the maintenance of proper telomeric length and structure via the activation of telomere shortening pathways that compensate telomerase-dependent excessive telomere elongation. Telomere attrition is mediated by a mechanism which involves the generation of single-stranded C-rich telomeric DNA, and the formation and removal of double-stranded telomeric circular DNA (T-circles). Telomere trimming is an independent pathway to recombination-mediated telomere elongation and the well-documented gradual telomere attrition that accompanies cellular replication.

**Comment by tberardini** [comment]
[Term]
+id: GO:0090737
+name: telomere maintenance via telomere trimming
+namespace: biological_process
+def: "A process that contributes to the maintenance of proper telomeric length and structure via the activation of telomere shortening pathways that compensate telomerase-dependent excessive telomere elongation. Telomere attrition is mediated by a mechanism which involves the generation of single-stranded C-rich telomeric DNA, and the formation and removal of double-stranded telomeric circular DNA (T-circles). Telomere trimming is an independent pathway to recombination-mediated telomere elongation and the well-documented gradual telomere attrition that accompanies cellular replication." [GOC:BHF, GOC:BHF_telomere, GOC:nc]
+is_a: GO:0000723 ! telomere maintenance
+created_by: tanyaberardini
+creation_date: 2017-02-07T16:51:24Z


-is_a: GO:0000723 ! telomere maintenance
+is_a: GO:0001325 ! formation of extrachromosomal circular DNA
+relationship: part_of GO:0090737 ! telomere maintenance via telomere trimming

**Comment by NancyCampbell** [comment]
can you please add the reference PMID:27918544. Sorry I had not noticed it was missing earlier.

In the future, is it better to start a new ticket for this or do as I have done now? (I am not sure what to do when the ticket is closed). or maybe add at the beginning to say no need to re-open ticket just minor correction etc. Thanks.

**Comment by tberardini** [comment]
Better to reopen the ticket.  That way all the related comments stay together and we can see that there's still something left to be done.

**Comment by tberardini** [comment]
Done.
- [GOC:BHF, GOC:BHF_telomere, GOC:nc]
+[GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:27918544]
