### ISSUE TITLE
TG request "other organism cell wall"

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12982]
[Term]
id: GO:1905882
name: other organism cell wall
namespace: cellular_component
def: "Any cell wall that is part of a other organism." [GO_REF:0000064, GOC:TermGenie, PMID:12438152]
intersection_of: GO:0005618 ! cell wall
intersection_of: part_of GO:0044215 ! other organism
created_by: pgarmiri
creation_date: 2017-01-31T10:57:28Z

**Comment by tberardini** [comment]
Approve?

**Comment by paolaroncaglia** [comment]
Uhm... Not sure where we stand with that, but there was a plan to nuke 'other organism' terms. See the comment to GO:0044215 ! other organism: "We plan to obsolete this branch of GO and replace its usage in annotation with a system for multi-organism annotation."
@dosumis would you have any comment please?

**Comment by mcourtot** [comment]
I don't like the term "other organism" very much, so would prefer not to create more of the same.

Looking at the PMID, https://www.ncbi.nlm.nih.gov/pubmed/?term=12438152 (abstract only, I don't seem to have fully-text access from home): 
The mechanism implicated in the interaction of chromofungin with fungi and yeast cells was studied by penetration of monolayers and confocal laser microscopy. Chromofungin is able to interact with the cell wall [...]

Maybe something like GO:0009277, fungal-type cell wall or GO:0030445, yeast-form cell wall would work?

cc @pgarmiri

**Comment by pgarmiri** [comment]
Hi, yes, I agree with you and the term you suggested, Melanie, was my first choice. However, I am getting the error below and it's not accepted by Protein2GO. That's why I thought to create this term. Especially since the "host cell wall" exists. 
"Annotation failed taxon constraint GO:0009277 (fungal-type cell wall) and its descendants should ONLY be used with gene products from the taxonomic group Fungi"
Is there any change that could be changed?
Thanks!

**Comment by mcourtot** [comment]
It seems chromofungin (derived from chromogranin A) is a bovine peptide, http://www.uniprot.org/uniprot/P05059. That would then imply that this paper is more about a defense mechanism against pathogens - maybe "defense response to fungus"? If possible maybe add the cell wall as AE?

**Comment by pgarmiri** [comment]
I have actually added GO:0052338: disruption by host of symbiont cell wall. They saw an accumulation of chromofungin at the symbiont cell wall and I wanted to capture this with a colocalize_with qualifier. I am happy to leave it out if it seems redundant and causes trouble.
Thanks,
Penelope

**Comment by tberardini** [comment]
Sounds like I can obsolete this term in the TG queue before approval and close this issue.  Please reopen if further action is necessary.

Status for commit #92002: Success

    (obsolete) ID: GO:1905882 Label: obsolete other organism cell wall
