### ISSUE TITLE
NTR  "DNA repair complex assembly"

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12987]
Hello, 

Can we create a new term,  "DNA repair complex assembly" as parent of "DNA recombinase assembly"? 

I am not sure what the guidelines are regarding this; most other complexes are specific and not described by their function, with a few exceptions, such as "dosage compensation complex assembly" , "mitochondrial respiratory chain complex assembly", etc. 

Thanks, Pascale

**Comment by tberardini** [comment]
@bmeldal - Could you weigh in please?

@pgaudet - Which of the existing '% complex assembly' terms should become children of the new one?  Besides 'DNA recombinase assembly' of course.

**Comment by tberardini** [comment]
Also, reference please.  Thanks.

**Comment by pgaudet** [comment]
Hi Tanya, 

We could add as a child "GO:1903871 DNA recombinase mediator complex assembly" (definition of th e complex itself makes it clear it belongs there: GO:0033061 DNA recombinase mediator complex, def = A protein complex containing accessory proteins which bind a recombinase (e.g. Rad51) and bind single-stranded DNA (ssDNA), and promote nucleation of the recombinase onto ssDNA. ") This is all I could find in the assembly process. Other complexes exist under GO:1990391 DNA repair complex in CC, but I don't think we should create the assembly for each of them until it's needed. 

We wanted to more general term to describe the assembly of complexes containing the RAD51 recombinase, as well as other members (not necessarily fully defined). Example of papers are: 
27233470 Fig 1C + 1D
27113759 Fig 3A. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Complexes should be defined by their function as much as possible.

I don't really deal with the assembly terms, just the finished, functional products.

**Comment by tberardini** [comment]
I was about to add this term and then ran into a snag.

**DNA repair complex** (the cc term) and **DNA recombinase mediator complex** (cc term) are both _is_a_ **protein complex**.

**DNA recombinase complex assembly** (the existing bp term) _is_a_ **protein-DNA complex assembly**.

Should the _is_a_ parent of the proposed term, **DNA repair complex assembly** be  **protein complex assembly** OR **protein-DNA complex assembly**.

Do you see the discrepancy? Please clarify.

**Comment by pgaudet** [comment]
Hi Tanya, 

The more new term should be is_a protein complex assembly. 

Thanks, Pascale

**Comment by tberardini** [comment]
**Existing CC hierarchy:**

protein complex (exists)
--[i] DNA repair complex (exists)
--[i] DNA recombinase mediator complex (exists)

protein-DNA complex (exists)
--[i] DNA recombinase complex (exists)

**Proposal:** 

protein complex assembly (exists)
--[i] **DNA repair complex assembly (NEW: requested placement, consistent with cc parentage)**
----[i] **DNA recombinase mediator complex assembly (exists, new parent requested, consistent with cc parentage)**
----[i] **_DNA recombinase assembly (exists, new parent requested - inconsistent with cc parentage)_**

protein-DNA complex assembly (exists)
--[i] DNA recombinase assembly (exists)

Do you see the problem?  With your proposal, the CC hierarchy would be inconsistent with the BP hierarchy.  They should be in agreement.

**Comment by ukemi** [comment]
Keep in mind that protein complex and all associated terms will be merged into macromolecular complex, which in turn will become protein-containing complex. I was thinking of doing this merge at the workshop as an example and having everyone try merging some of the necessary terms as practice. This might help here because protein complex will become much less specific and after the merge will be equivalent to protein-containing complex.

**Comment by tberardini** [comment]
Oh yes, good.  So I can do this, which is what I wanted to propose but didn't cause I forgot about that impending merge. Will leave CC alone.

macromolecular complex assembly (exists)
--[i] DNA repair complex assembly (NEW)
----[i] DNA recombinase mediator complex assembly (exists, new parent)
----[i] DNA recombinase assembly (exists, new parent)

**Comment by tberardini** [comment]
[Term]
+id: GO:0090735
+name: DNA repair complex assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a DNA repair complex." [GOC:pg, PMID:27113759, PMID:27233470]
+is_a: GO:0065003 ! macromolecular complex assembly
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:1990391 ! DNA repair complex
+created_by: tanyaberardini
+creation_date: 2017-02-06T16:42:27Z

and added parentage for existing terms as suggested.
