### ISSUE TITLE
Check F-P link for "GO:0001026 TFIIIB-type transcription factor activity"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12985]
GO:0001026 TFIIIB-type transcription factor activity
currently is linked to
GO:0006359 regulation of transcription from RNA polymerase III promoter
but many of the core transcription factors are directly involved in , not regulating....
maybe a logical definition issue?

https://github.com/geneontology/go-annotation/issues/1522
https://github.com/geneontology/go-annotation/issues/1523

**Comment by ukemi** [comment]
@krchristie can you look at this?

**Comment by krchristie** [comment]
@ukemi - When we asked the RNA pol III researchers whether transcription factors such as TFIIIC were regulatory or part of the process, we got a bit of a mixed response, but slightly over half of the RNAP III researchers we contacted felt that transcription factors such as TFIIIC, and thus similarly TFIIIB, were both regulatory and part of the process. Yes, they are required for transcription to occur at all, but they are also regulating when that transcription occurs. Thus, we chose to make links saying that these types of transcription factors are both regulatory and part of the process. 

That's the original logic.

**Comment by ValWood** [comment]
Was this referring to when general transcription occurs? or gene specific transcription? or both?

I would have thought that some signal transduction would regulate when transcription occurs, in which case would these  be considered the termination of a signalling pathway? Or are they another molecular function regulator?

It might be useful to have this level of knowledge if we add regulatory links into the ontology  between a function and a process. 

If not its fine as is, (although it might be best to omit these links if this is at all unclear) -  I only queried it because these were some of the very  few essential genes which were  both "involved directly in a process", and "regulating a process", and the mechanism regulation was not clear (usually they are within process molecular function regulators).

**Comment by krchristie** [comment]
Both. While transcription factors are part of the mechanism of building the complex to get the RNAP (whichever one) to the right place, they are also regulating when transcription occurs.

**Comment by tberardini** [comment]
Any ontology edits necessary?

**Comment by ValWood** [comment]
I think the F-P  relationship should be removed:

transcription factor activity, core RNA polymerase III binding	
for some annotations:

**Comment by ValWood** [comment]
I don't understand my comments from 18 hours ago (maybe meant for a different ticket?)

I still think we probably shouldn't add F-P links based  only on author statements. I'd prefer it if I could see some experiments demonstrating that TFIIIB was also regulating transcription. I don't see any in GO at present...

**Comment by tberardini** [comment]
Awaiting further clarification/approval of necessary ontology edits.

**Comment by ValWood** [comment]
Yep can close. There are IDA annotations to the regulation term, not sure why I didn't see them. I checked paper and is required for activation, so is regulation

**Comment by tberardini** [comment]
Thank you Val!
