### ISSUE TITLE
NTR "site of DNA damage"

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#12986]
Hello, 

We'd like to request a new term, "site of DNA damage", as a parent of "GO:0035861 site of double-strand break"

Proposed definition: "A region of a chromosome at which DNA damage has occurred. DNA damage signaling and repair proteins accumulate at the lesion to respond to the damage and repair the DNA to form a continuous DNA helix. "

Thanks, Pascale

**Comment by tberardini** [comment]
Are there any additional existing terms that should also become children of this newly requested term?  Would the new term be is_a chromosomal part?  Finally, reference please.  Thanks.

**Comment by pgaudet** [comment]
Hi Tanya, 
 
It would indeed be is_a chromosomal part. 

For a reference I suggest
https://en.wikipedia.org/wiki/DNA_repair

There are proteins that recognize and repair the different types of DNA damage 
https://en.wikipedia.org/wiki/DNA_repair#Types_of_damage

For example, oxidized base, apurinic site, etc. If you want we can create all these terms; however for our purposes it would be sufficient to have the more general term "site of DNA damage" (rather than the specific double strand break). 

Thanks, Pascale

**Comment by tberardini** [comment]
+id: GO:0090734
+name: site of DNA damage
+namespace: cellular_component
+def: "A region of a chromosome at which DNA damage has occurred. DNA damage signaling and repair proteins accumulate at the lesion to respond to the damage and repair the DNA to form a continuous DNA helix." [GOC:pg]
+xref: Wikipedia:DNA_repair
+is_a: GO:0044427 ! chromosomal part
+created_by: tanyaberardini
+creation_date: 2017-02-03T17:24:08Z


-is_a: GO:0044427 ! chromosomal part
+is_a: GO:0090734 ! site of DNA damage

**Comment by pgaudet** [comment]
Thanks!
