### ISSUE TITLE
Creation of MATH domain binding and addition of synonym

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#12990]
Hello,

1) Would it be possible to create  a GO term for MATH domain binding? 
    Reference: PMID 22621901
    InterPro: https://www.ebi.ac.uk/interpro/entry/IPR002083?q=math%20domain

2) Would it be possible to add BTB domain as a synonym for GO term GO:0031208?
    Reference: PMID 22621901
    InterPro: http://www.ebi.ac.uk/interpro/entry/IPR000210

Thank you

Rossana

**Comment by tberardini** [comment]
Re:2 (for reference) http://amigo.geneontology.org/amigo/term/GO:0031208 

@ukemi , @paolaroncaglia , @dosumis , @mcourtot : I remember that we are not adding new 'protein family **X** binding terms' but are we continuing to add '**x** domain binding' terms? Or are such annotations better served by using the parent 'GO:0019904 protein domain specific binding' and adding the INTERPRO domain into the annotation extension field?

**Comment by tberardini** [comment]
I checked and a '%domain binding' term was added in Sept. 2016.  So going ahead and adding this one:

 [Term]
+id: GO:0090736
+name: MATH domain binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a meprin and TRAF homology (MATH) domain." [InterPro:IPR002083, PMID:22621901]
+is_a: GO:0019904 ! protein domain specific binding
+created_by: tanyaberardini
+creation_date: 2017-02-06T17:08:28Z


Added synonym as requested:

+synonym: "Broad-Complex, Tramtrack and Bric a brac domain binding" EXACT []
+synonym: "BTB domain" EXACT [PMID:22621901]
