### ISSUE TITLE
NTR: manganese ion transmembrane transporter activity

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12992]
To annotate the manganese-efflux reaction described in PMID:25319704 could we have a new GO term, GO:new manganese ion transmembrane transporter activity, with definition "Enables the transfer of manganese (Mn) ions from one side of a membrane to the other." The new term would be a sibling of GO:0015095 magnesium ion transmembrane transporter activity and have the same is_a molecular_function parents,  GO:0072509 divalent inorganic cation transmembrane transporter activity and  GO:0046873 metal ion transmembrane transporter activity, and would have  GO:0071421 manganese ion transmembrane transport as a part_of biological_process parent.

**Comment by tberardini** [comment]
Did you miss this term?  It links to CHEBI:25155 ! manganese cation.  Perhaps you need something more specific to manganese (2+), (3+), or (4+)?

http://amigo.geneontology.org/amigo/term/GO:0005384

[Term]
id: GO:0005384
name: manganese ion transmembrane transporter activity
namespace: molecular_function
def: "Catalysis of the transfer of manganese (Mn) ions from one side of a membrane to the other." [GOC:dgf]
subset: gosubset_prok
is_a: GO:0046915 ! transition metal ion transmembrane transporter activity
intersection_of: GO:0015075 ! ion transmembrane transporter activity
intersection_of: transports_or_maintains_localization_of CHEBI:25155 ! manganese cation
relationship: part_of GO:0071421 ! manganese ion transmembrane transport

**Comment by deustp01** [comment]
I did miss it - that works for me.
Thanks.
