### ISSUE TITLE
signal transducer, downstream of receptor, with serine/threonine kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12999]
I just spotted this term (Never noticed it before).

It worries me that PomBase have only 8 annotations to this term, 
http://www.pombase.org/spombe/result/SPAPB18E9.02c
As many of our protein kinases will fit this definition.

**Comment by ValWood** [comment]
I see its name changed recently from
receptor signaling protein serine/threonine kinase activity
Is there a SF ticket about this? The new names seems quite a clunky name  for a protein kinase.

Can it not be
signal transducing protein kinase activity (that would fit the def)
...the existing name makes the kinase activity appear  not to be the primary activity.

And a question. When annotating protein kinases, is the terminal kinase considered to be a "signal transducer" too? (I'm never sure about this)

**Comment by ValWood** [comment]
@Antonialock

**Comment by dosumis** [comment]
The term is old, but the name is new-ish.  The terms in this branch were originally called 'receptor signaling protein ...' which sounds like it might refer to a receptor,  but confusingly this class *excludes* receptors. 

The new names are my fault.  This sounds nicer:

> signal transducing protein kinase activity

Following the GO definition of signal transducer, this could cover receptors too, but my guess is that most biologists would assume this was downstream.   So I think this name could work (although I'd add a clarifying comment for future editors.

> It worries me that PomBase have only 8 annotations to this term,

23 annotations for 8 protein?
http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0004702&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=4895&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal

Mostly to subclasses, so if some are missing then there must be missing classifications in GO.  Can you list?

**Comment by ValWood** [comment]
Currently they are annotated to plain old 
protein/serine protein kinase activity type terms....
protein tyrosine kinase activity

things like, 
wee1 http://www.pombase.org/spombe/result/SPCC18B5.03
cdr2 http://www.pombase.org/spombe/result/SPAC57A10.02
cdrr1 http://www.pombase.org/spombe/result/SPAC644.06c

but the  "signal transducing protein kinase activity" is another orthogonal classification. It combines function with process (signal transduction)... we should probably decide how we and to do this consistently.

**Comment by ValWood** [comment]
The number depends on the answer to:
"And a question. When annotating protein kinases, is the terminal kinase considered to be a "signal transducer" too? (I'm never sure about this)""

because if the terminal kinase is also a signal transducer, then it is probably all 116 of our protein kinases.......

**Comment by ValWood** [comment]
So for this one, I'd be happy if the name was changed to 
signal transducing protein kinase activity

as we annotate our pathways we will need to make sure that other "signal transducing kinases" are under this term. Bear in ming that this will necessitate lots of new terms like

signal transducing protein serine/threonine protein kinase

etc

**Comment by dosumis** [comment]
> Bear in ming that this will necessitate lots of new terms like:
> signal transducing protein serine/threonine protein kinase

The branch already has:

![image](https://cloud.githubusercontent.com/assets/112839/22927350/97f2c2e8-f2a8-11e6-8031-b586e5292d61.png)

**Comment by ValWood** [comment]
OK.
We will need to migrate our protein kinases to these terms to collect a "signalling parent"

However Ithe term names seem unnecessarily long.

Could they be shortened from:

signal transducer, downstream of receptor, with serine/threonine kinase activity
Definition	Conveys a signal from an upstream receptor or intracellular signal transducer by catalysis of the reaction: ATP protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate.
GONUTS	GO:0004702 Wiki Page

To
signal transducing serine/threonine kinase activity
Conveys a signal from a receptor or intracellular signal transducer by catalysis of the reaction: ATP protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate.



Reasons
1. It seems odd to have "downstream of receptor" in the  term name because not ALL signalling protein kinases are downstream of "receptors" they may be downstream of 'sensors' sensing  abnormal events, like the replication checkpoint signalling...
2. This def would  hold for any signal transducing protein kinase (but presumably a receptor/protein kinase requires 2 independent MF annotations?). If a separate term really is required for a "receptor kinase" it would be a descendant of this term...

What do you think?

Val

**Comment by dosumis** [comment]
Hi Val,

All good points and very timely given current discussions with @thomaspd on MF refactoring.

ST in GO is already broader than signaling from receptors, but as a developmental biologist my instinct when talking about signal transduction is to assume we're talking about signaling downstream of receptors detecting an extracellular signal.  We could divide signal transduction up into 

signal transduction:
    signal transduction involved in cell communication
    signal transduction from intracellular signal  <-- Not sure what to call this, but we clearly have classes that belong under here (e.g. mitochondria to nucleus signaling pathway)

We don't typically capture the regulated_by aspect of signal transducers, but maybe we should - after all, a signal transducer must have an input as well as an output.  For MAPK activity should we encode regulation by phosphorylation in the MF?  @thomaspd - please comment.

> This def would hold for any signal transducing protein kinase (but presumably a receptor/protein kinase requires 2 independent MF annotations?). If a separate term really is required for a "receptor kinase" it would be a descendant of this term...

The point of this branch was to *exclude* receptors.  Refactoring of cell-communication / cell-cell signaling and its relation to ST will help us formalise this (see #13020).

**Comment by ValWood** [comment]
I don't think this split would help. Often we annotate protein kinases which are known to be part of signalling pathways, but we can't be sure if they are downstream of receptors or intracellular signals. The pathway information is still very fragmentary.
We know they are a signal transducer, and we know they are a protein kinase.
So, if you can't remove the "downstream of receptor" part from the term, we would need terms like:
signal transducer, protein kinase activity etc...

However, I do think it would look odd to see all of our protein kinases annotated as:
signal transducer, downstream of receptor, with serine/threonine kinase activity
(even if we do know that they are downstream of a receptor).

Whether a kinase  is downstream of a receptor will only become known once the pathway is worked back to it's root so we will need to constantly change existing annotations  to kinases downstream of receptor/ downstream of intracellular signal  as we get more info (and many seem to be  downstream of both receptors and intracellular signals).

Is this critical? Why is it necessary to  exclude receptor kinases  from signal transducing kinases? 

This makes things much more complicated for curators...

**Comment by dosumis** [comment]
I agreed to change the names to `signal transducer, protein kinase activity` etc in [my first comment on this ticket](https://github.com/geneontology/go-ontology/issues/12999#issuecomment-277666559) :).  These terms will be part of signal transduction (general class). Sorry if not clear. 

> Whether a kinase is downstream of a receptor will only become known once the pathway is worked back to it's root so we will need to constantly change existing annotations to kinases downstream of receptor/ downstream of intracellular signal as we get more info (and many seem to be downstream of both receptors and intracellular signals).

In as far as we capture this, we should do so using inference.  That's the plan for LEGO.  Some of the same inference will work with extensions.  We're still working out the details, but it should be enough to extend an annotation to the MF with `part_of {insert sig transduction term here}`.

**Comment by pgaudet** [comment]
@ValWood @dosumis @thomaspd 
Is this a process ?

**Comment by dosumis** [comment]
> @ValWood @dosumis @thomaspd
> Is this a process ?

No

**Comment by ValWood** [comment]
but this is?
https://github.com/geneontology/go-ontology/issues/13250

**Comment by ValWood** [comment]
I  would merge directly with their cognate  kinase term "protein tyrosine kinase activity"

I think it is  confusing too....

**Comment by pgaudet** [comment]
OK I can do that too, although the term labels are so confusing that obsoletion could be better ?

**Comment by ValWood** [comment]
I always prefer obsoletion, it's cleaner.
Are there many direct annotations? We haven't used it at PomBase, we only used child terms like SAP kinase activity and MAP kinase activity

**Comment by pgaudet** [comment]
GO:0005057 signal transducer activity, downstream of receptor : about 20 EXP
GO:0004716 signal transducer, downstream of receptor, with protein tyrosine kinase activity: 2 EXP
GO:0004702 signal transducer, downstream of receptor, with serine/threonine kinase activity : 7 EXP 
GO:0004728 signal transducer, downstream of receptor, with protein tyrosine phosphatase activity 2 EXP
GO:0009400 signal transducer, downstream of receptor, with serine/threonine phosphatase activity

Most have been removed  geneontology/go-annotation#1899

Pascale

**Comment by pgaudet** [comment]
@ValWood I'm closing this, the is covered in #14232

Thanks, Pascale
