### ISSUE TITLE
add F-P link for  molecular function regulator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12994]
should there be an F-P link between these 2 terms?

![f-p link](https://cloud.githubusercontent.com/assets/7359272/22609077/9e9a1f6e-ea57-11e6-869e-af2e0bc92191.jpg)

I expected the MF to be a subset of the BP...

**Comment by tberardini** [comment]
+relationship: part_of GO:0065009 ! regulation of molecular function

**That,** I can do. :)
