### ISSUE TITLE
NTRs: urothelial plaque and related

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#12996]
I am annotating PMID:22323295 and need a couple new terms to deal with urothelial plaques.

**term name:** apical plasma membrane urothelial plaque
=> the plaques also occur in fusiform vesicles in biologically relevant ways, so I thought it might be best to specify the location as well as the parentage I have here is only true when when the	plaque is in the apical membrane
**Def:** A scallop-shaped plaque, also referred to as an asymmetric unit membrane (AUM), found in the apical plasma membrane of urothelial superficial (umbrella) cells which form a a barrier to the passage of water and soluble toxic compounds found in urine. The plaques are thickened regions of membrane composed of uroplakin transmembrane proteins which form a crystalline array.
**def dbxref:** GOC:krc, PMID:21468280, PMID:21887288
**is_a:** GO:0005887 integral component of plasma membrane
=> could be more specific if we also create term for "integral component of apical plasma membrane", might be better for logical def?
**part_of:** GO:0016324 apical plasma membrane
exact synonym: asymmetric unit membrane
related synonym: AUM

**term name:** fusiform vesicle
**Def:** A cytoplasmic vesicle which contains two urothelial plaques and can deliver these plaques to the apical plasma membrane of urothelial superficial (umbrella) cells. It can also be formed by endocytosis of apical plasma membrane during contractions of the urinary bladder.
**def dbxref:** GOC:krc, PMID:21468280, PMID:21887288
**is_a:** GO:0031410 cytoplasmic vesicle

@ukemi - I am willing to do these, pending discussion. I have a couple questions to run by you first.

1: Lee G. Uroplakins in the lower urinary tract. Int Neurourol J. 2011 Mar;15(1):4-12. doi: 10.5213/inj.2011.15.1.4. PubMed PMID: 21468280

2: Hudoklin S, Jezernik K, Neumüller J, Pavelka M, Romih R. Urothelial plaque formation in post-Golgi compartments. PLoS One. 2011;6(8):e23636. doi:10.1371/journal.pone.0023636. PubMed PMID: 21887288

**Comment by krchristie** [comment]
Almost forgot, I also think it would be useful to have another term related to these two.

**term name:** hinge region between urothelial plaques of apical plasma membrane 
**Def:** A narrow rim of non-thickened membrane in between urothelial plaques in apical plasma membrane. 
**def dbxref:** GOC:krc, PMID:21468280, PMID:21887288
**is_a:** GO:0098590 plasma membrane region
**part_of:** GO:0016324 apical plasma membrane

**Comment by ukemi** [comment]
@krchristie I'd be happy to chat about these. They seem reasonable to me, but I think we can improve on the definitions a bit to make them more compliant with the way we create standard genus-differentia defs. For example something like this:

term name: hinge region between urothelial plaques of apical plasma membrane
Def: A region of the apical plasma membrane consisting of a narrow rim of non-thickened membrane between urothelial plaques.
def dbxref: GOC:krc, PMID:21468280, PMID:21887288
is_a: GO:0098590 plasma membrane region
part_of: GO:0016324 apical plasma membrane

Is it worth it to create a generic urothelial plaque, a fusiform vesicle urothelial plaque and an apical membrane urothelial plaque? Putting on a LEGO hat, do the gene products function in the vesicle or is it a mechanism to get them to the cell surface. This would be an interesting example to model.

**Comment by krchristie** [comment]
1 term added:
+[Term]
+id: GO_0120001
+name: apical plasma membrane urothelial plaque
+namespace: cellular_component
+def: "A scallop-shaped plaque, also referred to as an asymmetric unit membrane (AUM), found in the apical plasma membrane of urothelial superficial (umbrella) cells which form a a barrier to the passage of water and soluble toxic compounds found in urine. The plaques are thickened regions of membrane composed of uroplakin transmembrane proteins which form a crystalline array." [PMID:21468280, PMID:21887288]
+synonym: "asymmetric unit membrane" EXACT []
+synonym: "AUM" RELATED []
+is_a: GO:0005887 ! integral component of plasma membrane
+relationship: part_of GO:0016324 ! apical plasma membrane
+created_by: kchris
+

**Comment by krchristie** [comment]
Added two additional terms and also a def dbxref to previous term:

 id: GO_0120001
 name: apical plasma membrane urothelial plaque
 namespace: cellular_component
+def: "A scallop-shaped plaque, also referred to as an asymmetric unit membrane (AUM), found in the apical plasma membrane of urothelial superficial (umbrella) cells which form a a barrier to the passage of water and soluble toxic compounds found in urine. The plaques are thickened regions of membrane composed of uroplakin transmembrane proteins which form a crystalline array." [**GOC:krc**, PMID:21468280, PMID:21887288]
 synonym: "asymmetric unit membrane" EXACT []
 synonym: "AUM" RELATED []
 is_a: GO:0005887 ! integral component of plasma membrane
 relationship: part_of GO:0016324 ! apical plasma membrane
 created_by: kchris
 
+[Term]
+id: GO_0120002
+name: fusiform vesicle
+namespace: cellular_component
+def: "A cytoplasmic vesicle which contains two urothelial plaques and can deliver these plaques to the apical plasma membrane of urothelial superficial (umbrella) cells. It can also be formed by endocytosis of apical plasma membrane during contractions of the urinary bladder." [GOC:krc, PMID:21468280, PMID:21887288]
+is_a: GO:0031410 ! cytoplasmic vesicle
+created_by: kchris
+
+[Term]
+id: GO_0120003
+name: hinge region between urothelial plaques of apical plasma membrane
+namespace: cellular_component
+def: "A narrow rim of non-thickened membrane in between urothelial plaques in apical plasma membrane." [GOC:krc, PMID:21468280, PMID:21887288]
+is_a: GO:0098590 ! plasma membrane region
+relationship: part_of GO:0016324 ! apical plasma membrane
+created_by: kchris
+
