### ISSUE TITLE
GO:0022602 ovulation cycle process taxon constraints

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#12997]
GO:0022602 ovulation cycle process is restricted to vertebrates and is causing downstream taxon clashes with "GO:0001541 ovarian follicle development" for D.mel. Could the taxon restriction for GO:0022602 be relaxed (to metazoa?) to include other animals that ovulate?

**Comment by ukemi** [comment]
Even though the children are vertebrate specific, it makes sense to relax this one.

 is_a: GO:0048511 ! rhythmic process
 intersection_of: GO:0044699 ! single-organism process
 intersection_of: part_of GO:0042698 ! ovulation cycle
-relationship: only_in_taxon NCBITaxon:7742 {id="GOTAX:0000245"} ! Vertebrata <Metazoa>
+relationship: only_in_taxon NCBITaxon:33208 {id="GOTAX:0000245"} ! Metazoa
 relationship: part_of GO:0042698 ! ovulation cycle
