### ISSUE TITLE
parentage check: phospholipid translocation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12993]
phopholipid translocation
has the parent
"regulation of membrane lipid distribution"
but isn't  "phopholipid translocation" part of membrane lipid distribution (if that is a process)

It seems that the  process term would be "membrane lipid localization"?

**Comment by tberardini** [comment]
"regulation of membrane lipid distribution"
is an is_a child of regulation of a biological quality - the quality being 'membrane lipid distribution'
and an is_a child of single-organism membrane organization

I think everything is in order.

**Comment by ValWood** [comment]
Yeah, it seems a little odd that this as "regulatory". The translocation is causing the distribution, but not necessarily regulating it? (Unless the flippases actually sense the lipid distribution and regulate accordingly?)

**Comment by tberardini** [comment]
The definition of ROBQ (regulation of biological quality), the parent term:

"Any process that modulates a qualitative or quantitative trait of a biological quality. A biological quality is a measurable attribute of an organism or part of an organism, such as size, mass, shape, color, etc."

In this case, the measurable attribute is 'membrane lipid distribution' and the regulatory process is modulating where the lipids are distributed. In my understanding,  **phospholipid translocation** is a process that modulates where lipids are distributed within a membrane, therefore it is a 'regulation of membrane lipid distribution'.  Note the existence of a second is_a parent, single-organism membrane organization, which also adds information to this term.

**Comment by ValWood** [comment]
ok,
