### ISSUE TITLE
mRNA metabolism parent?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12991]
Should mRNA metabolism have the parent  GO:0010467 gene expression?

(It seems like it should ?)

**Comment by tberardini** [comment]
First off, I looked at the definition of gene expression:  
>"The process in which a gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA (for protein-coding genes) and the translation of that mRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form. "

By that definition, "production of the RNA" or RNA transcription and RNA processing should be children of this term. They are.

gene expression
--[i] transcription, DNA-templated
----[i] mRNA transcription
--[i] RNA processing
----[i] mRNA processing

We could consider moving other children of (m)RNA metabolism (think (m)RNA cleavage and (m)RNA modification under gene expression but I wouldn't want to move mRNA _catabolic_ process.  This means not moving mRNA *metabolic* process under gene expression.

HOWEVER...while I was looking around I ran across something that likely needs fixing. mRNA transcription (aka mRNA biosynthesis) is NOT a child of mRNA metabolic process.  ??!!  (RNA biosynthesis *is* a child of RNA metabolic process)

mRNA transcription
http://amigo.geneontology.org/amigo/term/GO:0009299

mRNA metabolic process
http://amigo.geneontology.org/amigo/term/GO:0016071

@ukemi, @paolaroncaglia : am I forgetting something essential about why that link is not present?

**Comment by ValWood** [comment]
Also, I wondered about " mRNA catabolism" at first.

But then because gene expression is

"The process in which a gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA (for protein-coding genes) and the translation of that mRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form."

This made me think that "mRNA catabolism" is also always negatively regulating gene expression?.....because you only degrade an mRNA to prevent a protein being produced (that would appear to hold true whether to directly regulate gene expression, or to remove aberrant transcripts? I'm still trying to think of any exception....

**Comment by ukemi** [comment]
What if the catabolism is just part of the steady state process?

**Comment by tberardini** [comment]
Thanks, @ukemi and @ValWood for your comments.  With those in mind, I'm still inclined to do this:

"We could consider moving other children of (m)RNA metabolism (think (m)RNA cleavage and (m)RNA modification under gene expression but I wouldn't want to move mRNA catabolic process. This means not moving mRNA metabolic process under gene expression."

PLEASE comment on the bigger issue I raised of 'mRNA transcription (biosynthesis)' NOT being a child of 'mRNA metabolism'.  Deliberate?

**Comment by krchristie** [comment]
Hi,

I do think that 'mRNA (transcription)' seems like it should be an is_a child of 'mRNA metabolic process'. That seems parallel to the fact that 'RNA biosynthetic process' is already an is_a child of 'RNA metabolic process'.

I'm not so sure that we would want to make all of 'mRNA metabolism' a child of 'gene expression'. In addition to David's comment about the possibility of some mRNA catabolism possibly just being steady state, I'm not sure that all mRNA modification affects gene expression either. 

-Karen

**Comment by ukemi** [comment]
@tberardini  and @krchristie 

I think the problem with the bigger issue is that mRNA in the logical definition of mRNA metabolism refers to the mature mRNA (mRNA and messenger RNA are now equivalent). messenger-RNA is an inferred subclass of 'mature_transcript'.  So is transcription equivalent to mRNA biosynthetic process, or is it part of it? I guess we could consider the things after the transcription, including polyA addtion where appropriate,to be maturation. Either way, I agree with @krchristie, I think it should be a metabolic process.

**Comment by tberardini** [comment]
Modified plan:

- [ ] move mRNA transcription to be is_a mRNA metabolic process
 
Leave all else as is.

**Comment by krchristie** [comment]
@tberardini Do you mean **ADD** is_a parentage of 'mRNA metabolic process' for  'mRNA transcription'?

I think the existing is_a parentage of 'transcription, DNA-templated' is still true and should remain.

**Comment by tberardini** [comment]
@krchristie - yes, **ADD**.

**Comment by krchristie** [comment]
great

**Comment by tberardini** [comment]
+is_a: GO:0016071 ! mRNA metabolic process

**Comment by ValWood** [comment]
OK, all sounds good.
val

**Comment by ValWood** [comment]
I think we should reconsider this.

Whilst triaging today I spotted a paper
https://www.ncbi.nlm.nih.gov/pubmed/28143396
abstract:
The regulation of all gene expression steps (e.g., Transcription, RNA processing, Translation, and mRNA Degradation) is 


so I asked my co-PI Jurg Bahler who has published over 100 papers on many aspects of gene expression
http://www.bahlerlab.info/publications/


I asked Jurg:
Would you consider all, or some mRNA degradation to be part of "gene expression"
A: yes
and
Every type of mRNA degradation? even "steady state"


A:
Yes. RNA levels determine protein levels, and these RNA levels are affected by both RNA production (transcription) and RNA turnover/half-life (degradation). Transcription and degradation together determine steady state RNA levels which ultimately determines gene expression.
Degradation seems to be as much controlled as transcription.

**Comment by tberardini** [comment]
Fair enough.  

Back to the definition of 'gene expression' in GO, right now:

> "The process in which a gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA (for protein-coding genes) and the translation of that mRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form."

With that in mind, let's step back and  look at the big picture and review ALL of the children of gene expression:
<img width="544" alt="screen shot 2017-02-07 at 4 23 59 pm" src="https://cloud.githubusercontent.com/assets/4998871/22717789/e7bff3e2-ed51-11e6-947b-b42bffa24f5c.png">

Are all appropriate?  Val suggests adding 'mRNA metabolic process' as a direct is_a child.

**Comment by ukemi** [comment]
I've never been fond of the term gene expression because it seems like a quality to me, at least the way people interpret it from papers. Wouldn't the catabolism be regulation if the process is the positive process of converting the gene's sequence to a product?

**Comment by ValWood** [comment]
Wikepedia defines as a process and it's a useful grouping term for the sub processes that make contribute to overall gene expression, very useful for super slims and enrichments.

I think you are right, catabolism would be negative regulation of gene expression.

If you think there might be exceptions and that not all mRNA decay is -ve regulating gene expression,  you could just link up the major mRNA decay pathways  instead.

**Comment by ukemi** [comment]
I think based on the way we have defined gene expression, all mRNA catabolism would be negative regulation because it always takes away the product.

**Comment by tberardini** [comment]
Action item:

- [ ] add **mRNA catabolism** as an _is_a_ child of **negative regulation of gene expression**

Any objections?

**Comment by krchristie** [comment]
none here

**Comment by ukemi** [comment]
none here

**Comment by tberardini** [comment]
+is_a: GO:0010629 ! negative regulation of gene expression
