### ISSUE TITLE
regulation of biological process pattern

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13006]
regulation of biological process: the general pattern in this branch should be

biological_process that regulates some BP(X)

This has been changed on the root:

![image](https://cloud.githubusercontent.com/assets/112839/22744690/f91f0a3c-ee15-11e6-8f5a-a9bb5580305c.png)

but not on most subclasses.

This is mostly a problem for inference from LEGO.  Many correct inferences will be missed if this is not changed.

 - [x] change for subclasses:
------------------------------------------------------------------------
r38651 | davidos | 2017-02-08 08:24:29 -0800 (Wed, 08 Feb 2017) | 1 line
& 
------------------------------------------------------------------------
r38653 | davidos | 2017-02-08 08:54:09 -0800 (Wed, 08 Feb 2017) | 1 line
(amazingly there is no change in inference(!)

- [ ] change in termgenie templates

**Comment by dosumis** [comment]
This needs to be changes in TermGenie too.

**Comment by dosumis** [comment]
Hi Chris - assigning to you to update TermGenie template.

**Comment by cmungall** [comment]
I will look into changing, but surely this has no effect on entailment ?

**Comment by dosumis** [comment]
In LEGO if BP1 regulates BP2, we want the BP1 node to be an inferred instance of regulation of BP2 (if such a term exists). This will fail if we require the BP1 to already be a subclass of biological regulation.

**Comment by dosumis** [comment]
Hmmm - but maybe the hidden GCI on the root is sufficient.    Need to investigate further why deepening to reg failing in some LEGO models.

**Comment by pgaudet** [comment]
This should be handled with the checks that @balhoff has implemented for LDs
