### ISSUE TITLE
no TermGenie emails

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13009]
I might have missed something but there are no longer email confirmations from TG term creations. This means if I have created a term one day but it take a a few days for it to get into the ontology, how do I find that term in the meantime? Last time I created it again until the reasoner said 'I found an identical term, would you like to use that one?' but it's a bit convoluted.

Thanks,
Birgit

**Comment by ukemi** [comment]
Hi Birgit,

You must have missed this email:

Everyone, please note that TermGenie no longer sends out email
notifications when your terms are committed. Apologies for this
inconvenience.

We hope to have something working again when we switch to using GitHub
to manage the ontologies.

-D

**Comment by ukemi** [comment]
@cmungall  do we have a time estimate on when these emails will start being sent again?

**Comment by bmeldal** [comment]
That's the one! I knew I saw something but couldn't find a GitHub ticket and didn't think about checking through the emails but might have been difficult to find the right one...

**Comment by ukemi** [comment]
Hi @bmeldal 

I'm going to close this one as it is a known issue that will hopefully be resolved once the switch is made.

-D
