### ISSUE TITLE
NTR: EC 3.1.3.89, 5'-deoxynucleotidase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#13008]
Hi,
Could someone create a GO term for this EC reaction?  Proposed definition: Catalysis of the reaction a 2′-deoxyribonucleoside 5′-monophosphate + H2O = a 2′-deoxyribonucleoside + phosphate.  Parent should be GO:0016791.
Thanks,
Ingrid

**Comment by hdrabkin** [comment]
Done
