### ISSUE TITLE
Obsolete virus receptor activity ?

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13004]
'virus receptor activity' is a non-cannonical function.  CD4 did not evolved to bind HIV, HIV evolved to bind CD4.

Shouldn't we instead have a term for the binding event that allows a virus to enter a cell ('virus receptor binding'?  which can be used to annotate viral proteins - with the receptor being in an extension?

From these annotations, it would be simple to derive a list virus receptors.

The number of [annotations with experimental evidence](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0001618&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal
) is relatively small.

CC @pdthomas @SIBvirus

**Comment by ukemi** [comment]
Dear all,

The proposal has been made to obsolete the following terms:

GO:0001618 virus receptor activity

The reason for obsoletion is that it is a non-cannonical function. For
example, CD4 did not evolved to bind HIV, HIV evolved to bind CD4.

All details here:
https://github.com/geneontology/go-ontology/issues/13004

There are 32 annotations to this term with experimental evidence
supporting the annotation.
18 UniProt (5 NOT annotations)
5 CACAO
4 MGI (2 NOT annotations)
1 AgBase
1 BHF-UCL
1 HGNC
1 RGD
1 ZFIN

It is also used in the neuro behavior ontology.


We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete the term above on February 24th, 2017.

*** Unless objections are received by February 24th, we will assume
that you agree to this change. ***

Please comment on the GH ticket.

Thanks,

David

**Comment by dosumis** [comment]
- [ ] Consider adding reciprocal MFs -  e.g. 'binding to viral entry receptor' - to use in annotating viral proteins
- [ ] TODO check whether existing annotations have extensions referencing bound viral protein

**Comment by SIBvirus** [comment]
Hi David,

I see your point. I agree that binding viruses is not the primary molecular function of these host cell receptors and that this GO term should be deleted. The host cell receptor is "hijacked" by the virus (which could be described as a biological process).

However I am not sure to understand what you mean by adding "binding to viral entry receptor". This term is a bit confusing... There are host cell entry receptors, but no viral entry receptors.  It should rather be "binding to host entry receptor by virus". 
But... If you use "binding to host entry receptor by virus" in annotating viral proteins, wouldn't it be identical to "entry receptor-mediated virion attachment to host cell"? I don't see how you can create such a term without overlapping the existing four terms which already cover the annotation of viral proteins: 

1. virion attachment to host cell
1.1 receptor-mediated virion attachment to host cell
1.1.1 entry receptor-mediated virion attachment to host cell
1.1.2 adhesion receptor-mediated virion attachment to host cell

Or would you consider using these four terms for both the viral attachment proteins and the host entry receptors?
Cheers,
Chantal

**Comment by plemercier** [comment]
This function although not organism-evolved is essential for annotation.
In Uniprot we have a KW designed for this function "http://www.uniprot.org/keywords/KW-1183" which is linked via uniprot2go to "virus receptor activity [ GO:0001618 ]".
All annotations made on this are under (microbial infection) indicating that this function is microbe dependent and did not evolve by the organism itself. Example: http://www.uniprot.org/uniprot/Q9BYF1 as receptor for sars virus

**Comment by plemercier** [comment]
I noticed there are a bunch of dubious annotations for "virus receptor activity [ GO:0001618 ]".

 The status of host receptor for virus shall never be propagated. Its an event that is much complex and involves only one host and one virus. In Uniprot anything under (microbial infection) is prohibited to be propagated to orthologs. 
In other word IEA, ISS ISO.. should not be seen for this GO term. I guess that this supports making the old GO term obsolete, before creating a special "branch* of GO term for highjacking with appropriate rules.

cheers

Philippe Le Mercier

**Comment by pgaudet** [comment]
Is there a way to put a rule that forbids a term to be propagated by IEA, ISS ISO... ?

**Comment by pgaudet** [comment]
Hello, 

This ticket has been resolved by moving 'virus receptor activity' under 'GO:0104005 hijacked molecular function'. What needs to be done now is to create a rule to prevent propagation of 'virus receptor activity' (ie forbid ISS, ISO, etc). 

Thanks, Pascale
