### ISSUE TITLE
ntr: G2 M size control

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13000]
I think we need a new term to group processes involved in G2/M size control.

G2/M size control is_a GO:0008361 regulation of cell size

with these existing terms added as part_of

GO:1905287 positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation
and  GO:0031569 G2 cell size control checkpoint

Refs:
PMID: 872891 Seminal paper (Peter Fantes)
ref: recent review David Glover
https://www.ncbi.nlm.nih.gov/pubmed/22754657

Pombe paper
https://www.ncbi.nlm.nih.gov/pubmed/26776736

**Comment by ukemi** [comment]
This request seems incomplete. Can you supply definitions, then it would be easier to classify as is_a or part_of children? Wouldn't one of them be a checkpoint based on the name?

-D

**Comment by ValWood** [comment]
![cell size](https://cloud.githubusercontent.com/assets/7359272/22650643/0885a08e-ec78-11e6-80c9-1aeacdfda52e.jpg)
G2/M size control
def
Any process that modulates the size of a cell as part of the G/M cell cycle transition


GO:1905287	positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation
isn't a checkpoint
but is part_of
"negative regulation of cell size" at the cell cycle transition


"G2 cell size control checkpoint" is a checkpoint (already exists)

Its only that related terms exist in different parts of the ontology.


![cell size](https://cloud.githubusercontent.com/assets/7359272/22650658/182c4d76-ec78-11e6-855c-02b716ae5497.jpg)

**Comment by ValWood** [comment]
there are only 2 places where size is controlled, G1/S and G/2 M.

via  this conserved pathway:

![endosulphine](https://cloud.githubusercontent.com/assets/7359272/22650716/51d17d26-ec78-11e6-9a7e-a89d9b0479cc.jpg)

**Comment by ValWood** [comment]
a checkpoint can operate at this point, but not necessarily if cell size is adequate for division in different nutritional conditions.

**Comment by ValWood** [comment]
GO:1905287 positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation, 

is lacking some critical detail "initiating mitosis at a reduced cell size"


from  PMID26776736
"nutrient poor conditions, wild-type cells initiate mitosis at a reduced cell size"

(this is conserved in fly and human)

**Comment by mah11** [comment]
> there are only 2 places where size is controlled, G1/S and G2/M.

Hmm, I thought those were both control of whether the next transition takes place, based on whether the cell is big enough - i.e. cell size is a quality that the control system measures, rather than what's being controlled.

**Comment by ValWood** [comment]
I deleted that comment because I don't know that they are the only 2 places in  other organisms.

However, Isn't this this pathway somehow doing both (regulating size and transition in response to nutrients)?

But you are correct that  the checkpoint  doesn't go  under  the size control. I'm doing this in too much of a hurry because I wanted to have gone through the paper before sergio's talk tonight....

I'll write a new ticket for this tomorrow....I think I got it now ...more later...

**Comment by ukemi** [comment]
So does this one get closed, or are you going to add to it tomorrow?

**Comment by ValWood** [comment]
I think the best option for now is to

i) add
the parent
GO:0010972 negative regulation of G2/M transition of mitotic cell cycle

to
GO:0031569 G2 cell size control checkpoint


this will at least place  "G2 cell size control checkpoint"  correctly underneath the transition it regulates.


I'm not confident about the relationship between the size that division occurs and  "regulation of cell size".  We can revisit this part in the future....

**Comment by ValWood** [comment]
@Antonialock  unless you got any insight last night? Currently we have this part of the pathway annotated to "positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation" AND "negative regulation of cell size"

**Comment by Antonialock** [comment]
I don't know if this is regulation of size? 

Maybe the cells just "want" to quickly skip through G2 & M to maximise their survival chances (it is only when in G1 that they can find a mating partner or become stress resistant). In that case smaller size is just an effect of that....it is not regulation of size per se.

I'm sure regulation of size is a thing for other purposes - human fat cells can both shrink and enlarge right depening on the amount of resources that are around (and something must be regulating plasma membrane remodelling?) I'm just not sure that the advancing the cell cycle in order to prepare for mating is "regulation of size"

**Comment by ValWood** [comment]
Yep, I'm not sure.  

i) The TOR pathway regulates growth
ii) There is definitely a "required size for division" (but this required size is different in different nutrient conditions). 
iii) Tor pathway allows cells to enter mitosis at a small size in  nutrient poor conditions.

We also have the "cell size sensor" pom1 cell geometry network which  measures a concentration gradient to  determine cell size 
https://www.ncbi.nlm.nih.gov/pubmed?term=19474792
but again, are these "cell size is a quality that the control system measures, rather than what's being controlled." (Midori's comment on the size checkpoint above).

From the ontology anything which is
GO:0061387	regulation of extent of cell growth
(which suerly covers TOR), is by definition regulating cell size (it is a descendant of GO:0008361).

- [ ]  If so, possible action:

GO:1905287 positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation
Any positive regulation of G2/M transition of mitotic cell cycle that is involved in cellular response to nitrogen starvation. 
PMID:26776736

This term is trying to describe 2 things. i) entry into mitosis and ii) The fact that mitotic entry occurs at a smaller size than normal. This part is not captured by this term definition.
So maybe the term def needs to be extended?

e.g.
Any positive regulation of G2/M transition of mitotic cell cycle that is involved in cellular response to nitrogen starvation. ADD NEW  Nitrogen starvation leads to decreased growth and entry into mitosis at a smaller size.

If logical definitions were added to  fit this definition, would this naturally be is_a 
GO:0030308 negative regulation of cell growth
Any process that stops, prevents, or reduces the frequency, rate, extent or direction of cell growth.

**Comment by mah11** [comment]
> Nitrogen starvation leads to decreased growth and entry into mitosis at a smaller size.

Would that apply to all species in which the G2/M transition is positively regulated at all in response to nitrogen starvation? (I have no idea; I just worry about keeping terms species-neutral.)

After Sergio's talk I'm also not sure whether size is a "goal" or just a coincidental outcome of cell cycle regulation, but I am still convinced that the cycle transitions are being regulated.

I also think cell size regulation in multicellular organisms isn't restricted to the cell cycle transitions. For example, I'm pretty sure the fat cells Antonia mentioned would be terminally differentiated, having gone from G1 to G0.

**Comment by ValWood** [comment]
First part easy: This is a conserved eukaryotic mechanism  which determines the size at division in somatic/vegetative cells in response to nitrogen limitation. 

See the above review by David Glover. Precedes the fission yeast work, covers Xenopus and fly.
The overlooked greatwall: a new perspective on mitotic control.

Presumably cell size regulation isn't limited to cell cycle transitions in any species. We have annotations to cell volume homeostasis during  hypertonic response , and in GO "cell volume homeostasis" and this is a descendant of regulation of cell size.

It strikes me that these are completely different types of size regulation, only the size at G2/M transition  is related to  cell growth. I'm still unsure whether its a goal or a coincidental outcome ;)

**Comment by ValWood** [comment]
Actually the review doesn't support that, it only speculates.

The pathway is the same though. If the term is defined to fit the current biology it would prevent any alternative usage without revision anyway....

**Comment by ValWood** [comment]
Note we are the only people to use the term so far. Antonia requested it for Sergio's paper....

**Comment by ukemi** [comment]
- [ ] add the parent GO:0010972 negative regulation of G2/M transition of mitotic cell cycle to
GO:0031569 G2 cell size control checkpoint

- [ ] Change the definition of GO:1905287 positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation from 'Any positive regulation of G2/M transition of mitotic cell cycle that is involved in cellular response to nitrogen starvation' to 'Any positive regulation of G2/M transition of mitotic cell cycle that is involved in cellular response to nitrogen starvation. ADD NEW Nitrogen starvation leads to decreased growth and entry into mitosis at a smaller size.'

Is that it?

**Comment by ValWood** [comment]
Yep. The first one is just missing from earlier work.

Re def change, can this have a logical def? I think this would place it under "regulation of  cell growth"

If not, can leave and hopefully it will happen naturally when logical defs are added.

**Comment by ukemi** [comment]
If I define 'G2 cell size control checkpoint' as:
'mitotic cell size control checkpoint' and ('happens during' some 'G2 phase') and 'negatively regulates' some 'G2/M transition of mitotic cell cycle'
It gets classified as both a 'mitotic cell size control checkpoint' and a 'G2/M transition checkpoint'. A 'G2/M transition checkpoint' is a 'mitotic cell cycle checkpoint' and a 'negative regulation of G2/M transition of mitotic cell cycle'. 

It does not get classified as a 'regulation of cell growth'. But, if I define 'mitotic cell size control checkpoint' as:
'mitotic cell cycle checkpoint' and regulates some 'cell growth'
it gets classified as a 'mitotic cell cycle checkpoint' and 'regulation of cell growth'. 

But I'm not sure I agree with this. I think I agree with @mah11  comment above, doesn't the checkpoint get triggered when the cell reaches a certain size? Is it really controlling the process of the cell growing? Happy to add it if you guys all agree.

**Comment by ValWood** [comment]
Hi David,

Sorry if this thread got confused. 
The 2 actions in my final comment are  totally independent. It would have been clearer if I put the missing parent in a new ticket.

We don't  exepect 'G2 cell size control checkpoint' to be defined as 'regulation of growth' (in line with Midori's comment)

The part related to 'G2 cell size control checkpoint' is done when the missing parent is added.

For the other part, this term
positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation
should end up defined as "negative regulation of growth". 

I'm confident that if used as defined the changes will not cause any violations across species. This would only be used to annotate the greatwall/endosulphine pathway based on current biology. It is expected that the nitrogen starvation part will be conserved, but I haven't been able to find any publications on this pathway since the review above. In the unlikely event that the nitrogen starvation part is not conserved then other organism would not be able to use the existing term anyway. 

For what its worth the G2/M control network (58 gene products) 
 is  eukaryotically conserved so far except for some factors very upstream

**Comment by ukemi** [comment]
So does what I have below work? I'm still not sure exactly what you want. This will make the G2 size control checkpoint a type of G2/M transition checkpoint, which makes sense to me.

If I define 'G2 cell size control checkpoint' as:
'mitotic cell size control checkpoint' and ('happens during' some 'G2 phase') and 'negatively regulates' some 'G2/M transition of mitotic cell cycle'
It gets classified as both a 'mitotic cell size control checkpoint' and a 'G2/M transition checkpoint'. A 'G2/M transition checkpoint' is a 'mitotic cell cycle checkpoint' and a 'negative regulation of G2/M transition of mitotic cell cycle'.

**Comment by ValWood** [comment]
Yes.
That covers one item. I'm sorry this ticket got so confused. I will try not to do this again;)
Should I open a new ticket for the outstanding part ;)

**Comment by ukemi** [comment]
Yes. Please open it and assign it to me.

**Comment by ukemi** [comment]
First part done. Val will open a new ticket for the rest.
