### ISSUE TITLE
missing relation between GO:0051880 G-quadruplex DNA binding &  GO:0042162 telomeric DNA binding

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#13005]
The two papers listed when creating the term look at proteins binding to G-quadruplex structures formed in telomeric DNA. 
PMID:16142245 
PMID:9512530

Is there a missing relation is_a between the two terms above?

GO:0051880 G-quadruplex DNA binding is_a GO:0042162 telomeric DNA binding

and delete the relation GO:0051880 G-quadruplex DNA binding is_a  GO:0003677 DNA binding

note: the G-rich telomeric sequences in vertebrates form G-quadruplex DNA structures.

**Comment by mah11** [comment]
No, because G-quadruplexes are not found exclusively in telomeres. Recent review:  https://doi.org/10.1093/nar/gkv862

**Comment by NancyCampbell** [comment]
does is_a signify a subtype?
is GO:0051880 G-quadruplex DNA binding a subtype of GO:0042162 telomeric DNA binding?

**Comment by mah11** [comment]
> does is_a signify a subtype?

yes

> is GO:0051880 G-quadruplex DNA binding a subtype of GO:0042162 telomeric DNA binding?

No, because not all G-quadruplex DNA is found in telomeres. We would be implying that it is if we said that GO:0051880 G-quadruplex DNA binding was a subtype of GO:0042162 telomeric DNA binding.

**Comment by ukemi** [comment]
So do you want 'telomeric G-quadruplex DNA binding' or can you co-annotate?

**Comment by NancyCampbell** [comment]
that would be the solution

**Comment by NancyCampbell** [comment]
can you please add:
GOC:BHF, GOC:BHF_telomere, GOC:nc
thanks

**Comment by ukemi** [comment]
[Term]
+id: GO:0061849
+name: telomeric G-quadruplex DNA binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with telomeric G-quadruplex DNA structures, in which groups of four guanines adopt a flat, cyclic Hoogsteen hydrogen-bonding arrangement known as a guanine tetrad. The stacking of guanine tetrads results in G-quadruplex DNA structures in telomeres." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:16142245, PMID:9512530]
+is_a: GO:0042162 ! telomeric DNA binding
+is_a: GO:0051880 ! G-quadruplex DNA binding
