### ISSUE TITLE
GO:0000506, GPI-GnT complex is an ER membrane protein complex

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13003]
GO:0000506 glycosylphosphatidylinositol-N-acetylglucosaminyltransferase (GPI-GnT) complex
is currently a child of  GO:0044432 endoplasmic reticulum part and  GO:0043234 protein complex
Could it shifted under: GO:0072546 ER membrane protein complex?

PMID:16162815

**Comment by ukemi** [comment]
synonym: "GPI-GlcNAc transferase complex" EXACT []
 synonym: "GPI-GnT complex" EXACT []
 synonym: "GPI-N-acetylglucosaminyltransferase complex" EXACT []
-is_a: GO:0043234 ! protein complex
-is_a: GO:0044432 ! endoplasmic reticulum part
+is_a: GO:0072546 ! ER membrane protein complex
