### ISSUE TITLE
NTR: (4S)-4-hydroxy-5-phosphonooxypentane-2,3-dione isomerase activity, EC 5.3.1.32

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#13001]
Hi,
Could someone please create a GO term for EC 5.3.1.32, (4S)-4-hydroxy-5-phosphonooxypentane-2,3-dione isomerase activity?  Proposed definition: Catalysis of the reaction (4S)-4-hydroxy-5-phosphonooxypentane-2,3-dione = 3-hydroxy-5-phosphonooxypentane-2,4-dione.  Synonym: phospho-AI-2 isomerase activity.

Thanks,
Ingrid

**Comment by ukemi** [comment]
@hdrabkin  is this in your list?

**Comment by hdrabkin** [comment]
No, this is new.

**Comment by hdrabkin** [comment]
I would think this will be an is_a
isomerase activity
GO id:	GO:0016853
Definition:	Catalysis of the geometric or structural changes within one molecule. Isomerase is the systematic name for any enzyme of EC class 5.
Comments	Note that enzymes of class EC:5.99.-.- should also be annotated to this term.

**Comment by hdrabkin** [comment]
done
