### ISSUE TITLE
UNSAT in Uberon

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#13011]
![screen shot 2017-02-10 at 14 29 22](https://cloud.githubusercontent.com/assets/2214135/22830175/6b064498-ef9d-11e6-88e8-f6949a701126.png)

causing the build and TG to fail

cc @hattrill

**Comment by mcourtot** [comment]
There seems to have been changes made in Oberon that are not yet reflected in GO, e.g.:

In GO; reproductive structure is equivalent to 'anatomical structure'
 and ('part of' some 'reproductive system')
In Uberon,  reproductive structure is equivalent to 'multicellular anatomical structure'
 and ('part of' some 'reproductive system')

**Comment by cmungall** [comment]
Fixed in r38696

**Comment by mcourtot** [comment]
Thanks Chris!
