### ISSUE TITLE
Slim needed for AGR ribbon view

### ISSUE THREAD

**Issue by selewis** [geneontology/go-ontology#13013]
Consisting of these terms (will be using closure)
GO:0003824 catalysis  OK
GO:0004872 receptor OK
GO:0005102 receptor binding OK
GO:0005215 transporter OK
GO:0005198 structural molecule OK
GO:0008092 cytoskeleton binding OK
GO:0003677 DNA binding OK
GO:0003723 RNA binding OK
GO:0008134 transcription factor -> This is tx factor *binding*
-> used "GO:0001071 nucleic acid binding transcription factor activity" instead OK
GO:0036094 small molecule binding OK
GO:0046872 metal ion binding OK
GO:0030246 carbohydrate binding OK

GO:0008283 cell proliferation OK
GO:0071840 cellular organization/biogenesis OK
GO:0051179 cellular transport/localization OK
GO:0032502 development OK
GO:0000003 reproduction OK
GO:0002376 immune system OK
GO:0050877 neurological OK
GO:0007610 behavior OK
GO:0050896 response to stimulus OK
GO:0023052 signaling OK
GO:0010467 gene expression OK
GO:0019538 protein metabolism OK
GO:0006259 DNA metabolism OK
GO:0044281 small molecule metabolism OK
GO:0050789 regulation OK

GO:0005576 extracellular OK
GO:0005829 cytosol OK
GO:0005856 cytoskeleton OK
GO:0005739 mitochondrion OK
GO:0005634 nucleus OK
GO:0005694 chromosome OK
GO:0016020 membrane OK
GO:0071944 cell periphery OK
GO:0030054 cell junction OK
GO:0042995 cell projection OK
GO:0032991 macromolecular complex OK

**Comment by ukemi** [comment]
This will provide a nice example of creating slims for next week's workshop.

**Comment by pgaudet** [comment]
Merge request is here: https://github.com/geneontology/go-ontology/pull/13117

**Comment by judyblake** [comment]
I would like to have us do analysis of all 5 major model organism groups as to distribution of annotations.  I post a slide deck that shows how we developed this approach at MGI.  Mary Dolan is working on the analysis now.

**Comment by judyblake** [comment]
I had left comments on AGR UI site, but understanding this working group didn't see

**Comment by ukemi** [comment]
@mdolanme  can you do this?

**Comment by mdolanme** [comment]
Here is a graphical comparison of the MGI slim and the AGR slim and the analysis of MGI annotations using the two slims:
[compareGOslims.pdf](https://github.com/geneontology/go-ontology/files/1045704/compareGOslims.pdf)

**Comment by pgaudet** [comment]
hello, 

This is still assigned to me, let me know if I need to do anything (and what!) 

Thanks, Pascale
