### ISSUE TITLE
OTR: vascular smooth muscle cell differentiation involved in phenotypic switching

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13010]
Discussed with @ukemi and @tberardini 

GO:1905420 'vascular smooth muscle cell differentiation involved in phenotypic switching' was created in TermGenie, however its placement in the ontology and the logical definition is not quite right.
It's currently part_of 'phenotypic switching' and is_a 'vascular smooth muscle cell differentiation'.
The term should be a direct child of 'cell differentiation involved in phenotypic switching’ and I would be hesistant to put it as a child of 'vascular smooth muscle cell differentiation’.
A comment should be added to the term linking to the discussion in GitHub tickets #12455 and #12354, so this relation is not added in future.

Original term request and links to further discussions here;
https://github.com/geneontology/go-ontology/issues/12455

**Comment by ukemi** [comment]
Thanks @rachhuntley 
I'm not sure how to link a comment to the tickets, but how about I add something like this to this term and its parent?

Note that although this term uses the phrasing of cell differentiation, it differs from differentiation in the sense of differentiation that occurs as a developmental progression of an organism. Therefore this term is not classified as a type of canonical cell differentiation.

**Comment by ukemi** [comment]
I'm not sure either. I think regeneration is certainly considered a developmental process. Maybe it is similar enough to canonical differentiation that it should be included.  @tberardini ?
In that case then all we need to do is add a parent and keep it classified to both.

**Comment by rachhuntley** [comment]
I was just going to say that it couldn't be the same as cell differentiation because you're not starting from an unspecialised cell, but looking at the definition of cell differentiation it says "The process in which relatively unspecialized cells, e.g. embryonic or regenerative cells, acquire specialized structural and/or functional features that characterize the cells, tissues, or organs of the mature organism or some other relatively stable phase of the organism's life history."

So I suppose the dedifferentiated cell could be classed as regenerative?

**Comment by ukemi** [comment]
Or even more directly I think it could be considered unspecialized. We kept that purposefully vague because often times the 'specialization' that occurs in development is progressive as lineages differentiate.

**Comment by tberardini** [comment]
> Yes, that sounds good, but maybe extend it to say "...this term is not classified as a type of canonical cell differentiation, but as a part of reversible differentiation"

+1

Based on the definition of 'cell differentiation' (...relatively unspecialized cells...),  I agree that we can  keep 'cell differentiation involved in phenotypic switching' as a child of 'cell differentiation'.  I'm not sure which terms were involved in this statement, "In that case then all we need to do is add a parent and keep it classified to both."

**Comment by ukemi** [comment]
Sorry @tberardini 

vascular smooth muscle cell differentiation involved in phenotypic switching
would become both is_a vascular smooth muscle cell differentiation and is_a cell differentiation involved in phenotypic switching. I can probably do this through the magic of the reasoner.

**Comment by tberardini** [comment]
Got it.  All clear now.  Thanks.

**Comment by ukemi** [comment]
OK. These were already part of reversible differentiation, which I think disambiguates them from regular differentiation. I added logical defs and it all looks good. Let me know if you spot any oddities.
