### ISSUE TITLE
missing parent to GO:0090539 peptide pheromone export by transmembrane transport

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13019]
Hello,

I guess 
GO:0090539 peptide pheromone export by transmembrane transport

should be a child of
GO:0035672 	oligopeptide transmembrane transport ?

Thanks
Antonia

**Comment by tberardini** [comment]
Added:

 is_a: GO:0000770 ! peptide pheromone export
+is_a: GO:0035672 ! oligopeptide transmembrane transport
 is_a: GO:0055085 ! transmembrane transport

**Comment by Antonialock** [comment]
Thanks Tanya!
