### ISSUE TITLE
scope of causally upstream of

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13015]
I'm still a bit confused about how  we should use this relation.

To start, the definition/usage appears to be inconsistent with the descendants.

Definition
p is causally upstream of q if and only if p precedes q and p and q are linked in a causal chain

Usage
Process A is causally_upstream of process B if process A occurs first, and process A causes process B to happen. Processes A and B do not overlap.

However, this relation has "directly regulates" "directly positively regulates" and "directly negatively regulates".

"directly regulates" and descendants are  used within annotation for describing the regulation of one molecular function by another molecular function  and these  are often "within process regulation"

which does not fit  the described usage...

**Comment by ValWood** [comment]
Although the "directly regulates" etc  the scope says they can be used for MF, but the usage does not...

**Comment by dosumis** [comment]
I agree that the definitions need to be improved and guidance added, but I don't see a contradiction here.  

Process is used in the general sense (both MF and BP in GO are processes - MF is a process carried out by a single gene product or complex).  If MF1 directly regulates MF2, MF1 is causally upstream of MF2: It precedes MF2 and causes MF2 to happen.

**Comment by ValWood** [comment]
Ah OK,  so it doesn't not mean process in the BP sense?

I was thinking that
A phosphorylates and directly activates B  and that both A and B are involved in the same process C

**Comment by dosumis** [comment]
> Ah OK, so it doesn't not mean process in the BP sense?

Correct.
