### ISSUE TITLE
Prepare for Berkeley Protege/OWL 2017 workshop

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13018]
First:

 - [ ] #13017 organize docs
 - [x] #12211  migrate to gh

Proposed agenda is here:

 * http://wiki.geneontology.org/index.php/Protege-OWL_Berkeley_Training_2017_Logistics
 * http://wiki.geneontology.org/index.php/Protege-OWL_Berkeley_Training_2017_Agenda

Some good ideas from @ukemi 
 * @cmungall to present the theory and the nuts and bolts of setting up protégé and commiting to GH (if we are ready by then).
 * Additional discussion of how to handle the various build failures that we see (GO, Jenkins, Release).
 * We should also include a discussion of how the annotation pipelines work.
 * @ukemi  go through some examples of common editing tasks that curators do, add a new term, merge terms, obsolete terms.
 * All: take a few GH tickets and work through them with you and I in the room to make sure that everything is going ok.
 *  @vanaukenk take notes so while the new people work on tickets, we can make some solid documentation. <-- note from cjm: should try and do this in advance, #13017

**Comment by ukemi** [comment]
We will report on the workshop at the next ontology call.

- New organization of GH ticket distribution

- Migrated to GH for the ontology repository

- Documentation underway

**Comment by ukemi** [comment]
Closing this and linking to other documentation ticket.
#13100
