### ISSUE TITLE
ntr metal ion transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13028]
I tried to do this by TG, but there is no chebi  term for metal ion

(current term metal ion transport uses "metal cation" in logical def)

**Comment by ukemi** [comment]
Do you know of any metal anions that occur in a physiological system? I'm not sure they do.

**Comment by ValWood** [comment]
good point. So should  "metal ion transport" really be "metal cation transport"

**Comment by ukemi** [comment]
I don't think so, because it wouldn't be the term most commonly used.

**Comment by dosumis** [comment]
Just call the term as 'metal ion transport' and use the cation term from ChEBI in the logical def.  I've done this elsewhere.

**Comment by ValWood** [comment]
yes ignore me. that is what the term is called. I was confused!
