### ISSUE TITLE
NTR:integral component of pigment granule membrane

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13025]
Could I have this term please?
integral component of pigment granule membrane
part_of GO:0048770 pigment granule
Def:The component of the pigment granule membrane consisting of the gene products and protein complexes having at least some part of their peptide sequence embedded in the hydrophobic region of the membrane. 
PMID:11294610

**Comment by tberardini** [comment]
+id: GO:0090740
+name: integral component of pigment granule membrane
+namespace: cellular_component
+def: "The component of the pigment granule membrane consisting of the gene products and protein complexes having at least some part of their peptide sequence embedded in the hydrophobic region of the membrane." [PMID:11294610]
+intersection_of: GO:0016021 ! integral component of membrane
+intersection_of: part_of GO:0090741 ! pigment granule membrane
+property_value: creation_date 2017-05-16T17:48:35Z xsd:dateTime
+property_value: http://purl.org/dc/elements/1.1/creator "tanyaberardini" xsd:string
+
+[Term]
+id: GO:0090741
+name: pigment granule membrane
+namespace: cellular_component
+def: "Any membrane that is part of a pigment granule." [PMID:11294610]
+is_a: GO:0098588 ! bounding membrane of organelle
+intersection_of: GO:0016020 ! membrane
+intersection_of: bounding_layer_of GO:0048770 ! pigment granule
+property_value: created_by "tanyaberardini" xsd:string
+property_value: creation_date 2017-05-16T22:33:39Z xsd:dateTime
