### ISSUE TITLE
Activities of chaperone complex

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#13021]
A general chaperone complex term was created as requested by @bmeldal. However, [in the ticket](https://github.com/geneontology/go-ontology/issues/11529), @ValWood [commented](https://github.com/geneontology/go-ontology/issues/11529#issuecomment-279723614) that there are other activities (in addition to "capable of GO:0044183 protein binding involved in protein folding") that chaperone complexes have.
We should review those and add them as needed, to ensure that other types of chaperone such as metallochaperones are inferred in the right place.

**Comment by tberardini** [comment]
Who has the necessary expertise to address this missing info issue?  Or do we need someone to dive into the chaperone literature?

**Comment by mcourtot** [comment]
I'll tag this as mini-project. At the moment things are not wrong, but they are I believe incomplete. In the [original ticket](https://github.com/geneontology/go-ontology/issues/11529), @paolaroncaglia mentioned that there has been a WG on chaperone in 2008-2009, and I'm hoping that people that were involved in those discussions ( @ValWood, @ukemi at least I suspect?) as well as @bmeldal who requested the chaperone complex term could have a look and comment/suggest updates.

**Comment by ValWood** [comment]
Agree this is none urgent. These chaperone flavour activities   will be required  eventually for LEGO modelling...maybe best to ignore until absolutely needed by an actual biological example...

**Comment by bmeldal** [comment]
Thanks, and sorry for not commenting yesterday, I was on childcare duty in the afternoon and without wifi... (in the centre of Cambridge as well!)

@mcourtot can you please paste the stanza for chaperone complex as it's not in the ontology yet so I can't see it.

Chaperones are often involved in the transport of proteins or complexes to their functional site as well (effectively acting as guides). That would be a different activity altogether.
e.g. Mis18 complex:
http://www.ebi.ac.uk/intact/complex/details/EBI-9872194
A search for "chaperone" in the CP already comes up with 345 complexes, 121 of them human.

Birgit

**Comment by mcourtot** [comment]
Here is the current stanza:
[Term]
id: GO:0101031
name: chaperone complex
namespace: cellular_component
def: "A protein complex required for the non-covalent folding or unfolding, maturation, stabilization or assembly or disassembly of macromolecular structures. Usually active during or immediately after completion of translation. Many chaperone complexes contain heat shock proteins." [GOC:bhm, PMID:21855797]
comment: An example of this is HSP90AB1 in human (P08238) in PMID:21855797 (inferred from direct assay).
is_a: GO:0043234 ! protein complex
relationship: capable_of GO:0044183 ! protein binding involved in protein folding

**Comment by bmeldal** [comment]
Thanks, Melanie.
Yes, not incorrect but probably incomplete.

**Comment by ukemi** [comment]
I'm going to close this one. Although it is true that the relations are probably incomplete, I think making models in Noctua will specify which other processes we need to link to this complex. The problem with chaperones is just as was described here. Things called chaperones can execute their function in many different biological contexts. That is why we originally had issues with the term as a molecular function. We cleaned this up by stating the activity explicitly.   If we can think of specific processes to add, we can open tickets with those specific requests.
