### ISSUE TITLE
MP:  GO:0034637 cellular carbohydrate biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13027]
is_a

GO:0034645 cellular macromolecule biosynthetic process

Needed for analysis (I'm helping a user with a  'super-slim')

was deleted, not sure why...
2009-02-25	Deleted	RELATION	is a GO:0044249 (cellular biosynthetic process)

**Comment by mah11** [comment]
Carbohydrates are not all macromolecules, so deleting the link was correct.

**Comment by mah11** [comment]
That said, the change log snippet says "deleted is_a GO:0044249 (cellular biosynthetic process)", but the ontology now has both GO:0034637 is_a GO:0044249 and GO:0034645 is_a GO:0044249, which looks right. It's still correct not to have GO:0034637 is_a GO:0034645.

**Comment by ValWood** [comment]
Yup, and I was looking at a disaccharide anyway, which isn't classed as a macromolecule anyway.
