### ISSUE TITLE
membrane curvature/membrane bending follow up

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13024]
https://github.com/geneontology/go-ontology/issues/12387

There still seem to be some connections missing:
![membrane bending terms](https://cloud.githubusercontent.com/assets/7359272/23076407/3b6b93be-f538-11e6-8a57-87376da20aba.jpg)

 - [ ]   spore membrane bending pathway -> rename spore membrane bending?
-  [ ]  spore membrane bending pathwa,  add membrane bending parent?
-  [ ]  lipid tube assembly appears to be describing some sort of "membrane tubulation"?
- [ ]  endoplasmic reticulum tubular network assembly appears to be describing some sort of "membrane tubulation"?

**Comment by ValWood** [comment]
- [ ]  lipid tube assembly -> maybe "lipid tube formation" would work better

**Comment by ValWood** [comment]
New Nature paper reconstituting membrane curvature with purified components:

Nature. 2017 Feb 22. doi: 10.1038/nature21387. [Epub ahead of print]
Reconstitution of the tubular endoplasmic reticulum network with purified components.
Powers RE1,2, Wang S1,2, Liu TY1,2, Rapoport TA1,2.
Author information
Abstract
Organelles display characteristic morphologies that are intimately tied to their cellular function, but how organelles are shaped is poorly understood. The endoplasmic reticulum is particularly intriguing, as it comprises morphologically distinct domains, including a dynamic network of interconnected membrane tubules. Several membrane proteins have been implicated in network formation, but how exactly they mediate network formation and whether they are all required are unclear. Here we reconstitute a dynamic tubular membrane network with purified endoplasmic reticulum proteins. Proteoliposomes containing the membrane-fusing GTPase Sey1p (refs 6, 7) and the curvature-stabilizing protein Yop1p (refs 8, 9) from Saccharomyces cerevisiae form a tubular network upon addition of GTP. The tubules rapidly fragment when GTP hydrolysis of Sey1p is inhibited, indicating that network maintenance requires continuous membrane fusion and that Yop1p favours the generation of highly curved membrane structures. Sey1p also forms networks with other curvature-stabilizing proteins, including reticulon and receptor expression-enhancing proteins (REEPs) from different species. Atlastin, the vertebrate orthologue of Sey1p, forms a GTP-hydrolysis-dependent network on its own, serving as both a fusion and curvature-stabilizing protein. Our results show that organelle shape can be generated by a surprisingly small set of proteins and represents an energy-dependent steady state between formation and disassembly.

**Comment by ValWood** [comment]
- [ ]   membrane bending  is a probably really molecular function, not a process

The MICOS component Mic60 displays a conserved membrane-bending activity that is necessary for normal cristae morphology.
J Cell Biol. 2017 Mar 2;. [Epub ahead of print]
PMID: 28254827

**Comment by ValWood** [comment]
See also this comment in older closed ticket:
geneontology/go-ontology#12387

I wonder if "membrane bending"
should be a Molecular function, rather than a biological process?
https://en.wikipedia.org/wiki/Membrane_curvature#Proteins_can_Induce_Curvature

@ukemi @thomaspd

It feels like a function

**Comment by hattrill** [comment]
Can I add a vote for membrane bending being an MF - this is the activity of BAR domain proteins.

PMID:27720484, EndoA: "Helix H1 inserts deep into the lipid bilayer, causing shallow membrane curvature and the formation of tubules on in vitro membranes. By contrast, when EndoA is phosphorylated, the protein inserts less deeply into the lipid bilayer, causing increased curvature by wedging Helix H1 into the lipid head group region"

**Comment by ValWood** [comment]
https://www.google.co.uk/imgres?imgurl=http://jcs.biologists.org/content/joces/128/16/2957/F1.large.jpg&imgrefurl=http://jcs.biologists.org/content/128/16/2957&h=974&w=1280&tbnid=eHxKi1qkku37vM:&tbnh=152&tbnw=200&usg=__5DgpKtPgwy2lq6ShW35jWBSW2bQ=&vet=10ahUKEwj_ooqUgdvVAhXIK8AKHZTBAUMQ_B0IezAK..i&docid=Kw2z6KJP9OzPRM&itg=1&sa=X&ved=0ahUKEwj_ooqUgdvVAhXIK8AKHZTBAUMQ_B0IezAK&ei=a9aTWb_BAcjXgAaUg4eYBA#h=974&imgdii=bG3i0kogFAvRlM:&tbnh=152&tbnw=200&vet=10ahUKEwj_ooqUgdvVAhXIK8AKHZTBAUMQ_B0IezAK..i&w=1280

**Comment by krchristie** [comment]
@pgaudet - This ticket seems overlapping with a new one @ValWood just made that is assigned to me (#14593). For efficiency, I think it would be better if one of us did both of these. I have a long standing interest in this since trying to get a MF term to annotate a yeast protein in SGD, so I'd be happy to take this one too.

**Comment by pgaudet** [comment]
reassigned, thanks for pointing it out. 

Pascale

**Comment by ValWood** [comment]
duplicate of  https://github.com/geneontology/go-ontology/issues/14593
