### ISSUE TITLE
Refactor cell-communication / cell-cell signaling to move start point for signal transduction

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13020]
_From @dosumis on February 13, 2017 12:8_

Motivation:  We need a partonomy for cell-communication and cell-cell signaling that is suitable for providing differentia to define MFs for *signaling* receptors and their ligands.  The current partonomy does not work for this.

cell communication (covers signaling between ECM and cell as well as cell-cell signaling)
.    <-po- signal transduction (starts with binding of ligand to receptor)
.    <-is_a- cell-cell signaling (includes ST; release of ligand; IC ligand transport & presentation)
.    .   <-po- signal release

A signaling receptor is a molecular transducer with an effector activity that is regulated via the binding of a ligand during in cell communication.  This binding event may happen at the cell surface or intracellularly (steroid receptors; signaling from internalized receptors in vesicles (?)).    We currently have no process covering intracellular ligand transport & presentation and binding to the receptor.  Binding to the receptor is covered under signal transduction - but part_of ST is not an adequate differentium for signaling receptors: transducers regulated by binding are common in signal transduction downstream of receptors (e.g. cAMP activating PKA; DAG activating PKC).  

Proposal: 
  * Move the beginning of signal transduction downstream of ligand binding either 
     * TBD: start with effector function or first step downstream from that (former would require nested class expressions). 
  * Add a new class covering transmission and reception of signal. This new class provides a differentium that we can use to define signaling receptors and their [ligands](https://github.com/geneontology/molecular_function_refactoring/issues/30#issuecomment-278632967)

_Copied from original issue: geneontology/molecular_function_refactoring#37_

**Comment by pgaudet** [comment]
@ukemi @vanauken

Is this something we should discuss RE. the signaling work ? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet - yes, we should discuss this, probably on an ontology call.

I think part of the issue was exactly how to define the beginning and end of the signal _transduction_ as opposed to the signaling pathway, i.e. perhaps the transduction of the signal should start downstream of the ligand binding function of a signaling receptor rather than with the binding.

P.S.  I think the mention above went to the wrong VanAuken, I'm @vanaukenk

**Comment by pgaudet** [comment]
Discussing with @thomaspd 
@vanaukenk is correct that this touches upon the difference between signal transduction as opposed to the signaling pathway - however we don't want to take the route of making that distinction. For a long time, the GO has stated that the ligand is part of the pathway. We believe that this is also what users expect.
