### ISSUE TITLE
snoRNP binding children

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13023]
I would like to see " box C/D snoRNP complex binding” and “box H/ACA snoRNP complex binding” added to the GO ontology under the parent term “snoRNP binding” (GO:0030519).  The definitions could be “Interacting selectively and non-covalently with any part of a box C/D small nucleolar ribonucleoprotein particle.” and “Interacting selectively and non-covalently with any part of a box H/ACA small nucleolar ribonucleoprotein particle”.  Synonyms could be “box C/D small nucleolar ribonucleoprotein complex binding”, “box C/D snoRNP ribose 2'-O methylase complex binding”, “box C/D snoRNP ribose-2'-O-methyltransferase complex binding” and  “box H/ACA small nucleolar ribonucleoprotein complex binding”, “box H/ACA snoRNP pseudouridylase complex binding.”  Examples can be found in PMID:10679015.

**Comment by pgaudet** [comment]
@krchristie Assigning you since you just did something similar

**Comment by krchristie** [comment]
@slaulederkind 

"box C/D snoRNP complex” is NOT synonymous with "box C/D snoRNP ribose 2'-O methylase complex" as there are several other kinds of box C/D snoRNP complexes that are NOT methylation guide complexes. I believe the same is true of the box H/ACA complexes, though I have not yet read some reviews I have just obtained.

I am guessing that what you probably want are binding terms for the  methylation guide complex and the pseuridylation complex, though let me throw in another issue that in eukaryotes, or at least in higher eukaryotes, there are two forms of these complexes, the snoRNP forms in the nucleolus that modify rRNAs and the scaRNP forms that modify snRNAs and other RNAs.

Do you need terms for binding to any form of these complexes or do you want binding terms specific to the nucleolar complexes?

For more info, see this ticket:  
NTR & issues with GO:0031428 "box C/D snoRNP complex" #11686

**Comment by slaulederkind** [comment]
Binding terms specific to the nucleolar complexes will work.  Thanks.

**Comment by edwong57** [comment]
This was created already in 2018 (GO:0062064). I am changing the label and definition to be consistent with the change for GO:0031428.
