### ISSUE TITLE
biotin transport parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13026]
is biotin both a vitamin and a cofactor?
![biotin](https://cloud.githubusercontent.com/assets/7359272/23095435/c1f87e78-f601-11e6-8042-77588386679f.jpg)

**Comment by ValWood** [comment]
There is some inconsistency anyway... metabolism has only vitamin parentage:

![biotin2](https://cloud.githubusercontent.com/assets/7359272/23095462/07e71872-f602-11e6-9e3f-05d64ce636d1.jpg)

**Comment by ukemi** [comment]
When I look at the above diagrams, I see both parentage in both diagrams.

**Comment by ValWood** [comment]
ok its fine. It seems biotin is both a vitamin and a cofactor?
