### ISSUE TITLE
Cleaning up the ‘STAT cascade’ branch

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#13038]
Stemming from https://github.com/geneontology/go-ontology/issues/11773

To broaden the range of species that can be annotated to STAT cascade terms, ‘STAT cascade’ and its regulation terms were created, and the existing ‘JAK-STAT cascade’ was placed under it. To complete the clean-up, 
- [ ] part_of children of the general ‘STAT cascade’, referring to the phosphorylation and import steps, would need to be added; 
- [ ] and corresponding, existing terms currently under ‘JAK-STAT cascade’, and their descendants, would have to be renamed (and given logical definitions). 

This proposal was approved by Rebecca Foulger (who worked on existing JAK-STAT terms).

**Comment by ukemi** [comment]
Since this ticket is superceeded by the discussions of the workshop, we are closing this ticket.
