### ISSUE TITLE
MP endosome transport via multivesicular body sorting pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13035]
GO:0032509	endosome transport via multivesicular body sorting pathway

is a?

GO:0071985 multivesicular body sorting pathway

I was wondering why all endosomal transport is not under vesicle-mediated transport? I think I asked  @dosumis that before but I can't remember the reason....

**Comment by dosumis** [comment]
'endosomal transport' has a weirdly broad definition:

![image](https://cloud.githubusercontent.com/assets/112839/23168381/df80ebe8-f83f-11e6-84fb-8ea342b12a6e.png)

This covers various transport processes that are not vesicular (e.g. transport into ot out of endosome).  

Most or all subclasses look vesicular though:

![image](https://cloud.githubusercontent.com/assets/112839/23168492/41d9d1ba-f840-11e6-9143-b7d1e1d8e5de.png)

**Comment by ValWood** [comment]
OK, thats OK if all the subclasses have vmt-parent.

**Comment by ValWood** [comment]
this parent is now present so closing...
