### ISSUE TITLE
add "mitochondrial translation" to fission yeast slim

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13031]
Since we removed "mitochondrial translation" as a descendant of "mitochondrial organization", these annotations are no longer included  in the slim.
Can we therefore add "mitochondrial translation" to the fission yeast slim.

(Rationale: We have "cytoplasmic translation" but because of the phenotypic and other differences between 
cytoplasmic and mitochondrial translation, it is between not to merge them  in the default for most analyses/slim applications)

**Comment by ukemi** [comment]
It is in goslim_ yeast. I assume you also want it in goslim_pombe? This will be a good example to use at the workshop.

**Comment by ValWood** [comment]
yes please!

**Comment by pgaudet** [comment]
Fixed.
