### ISSUE TITLE
NTR : Endoplasmic reticulum stress induced pre-emptive quality control

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#13039]
Dear GO editors,

I was wondering which term I should use to describe the process "ER-stress-induced pre-emptive quality control" described in PubMed=26565908 and PubMed=17129784. Should we create a new term or would suggest the use of an existing one? This is different from ERAD, since proteins do not really enter the endoplasmic reticulum and not retrotranslocated.
If we create it, it could be a child of : GO:0030968 endoplasmic reticulum unfolded protein response
Definition:
ER-stress-induced pre-emptive quality control (ER pQC) selectively degrades ER proteins via translocational attenuation during ER stress. Most newly synthesized endogenous proteins are rerouted to the cytosol without cleavage of the signal peptide, resulting in proteasomal degradation. 

Thanks for your help.

**Comment by ukemi** [comment]
Hi,

Sorry I have taken a while to look at this, but I have been trying to figure out how to place the term. I do think it deserves its own process term, but I would be more comfortable making it a direct child of 'response to endoplasmic reticulum stress'. than as a child of the unfolded protein response. It seems that the unfolded protein response is its own defined pathway. Is this ok?

term name: Endoplasmic reticulum stress induced pre-emptive quality control
synonym: ER stress-indiced pre-emptive quality control
synonym: ER pQC
definition: The response to endoplasimic reticulum stress in which nascent proteins are degraded by attenuation of their translocation into the ER followed by rerouting to the cytosol without cleavage of the signal peptide, and subsequent degradation by the proteasome.
is_a:response to endoplasmic reticulum stress
ends_with: proteasome-mediated ubiquitin-dependent protein catabolic process


-David

**Comment by lbreuza** [comment]
Hi David,
that's fine with me.
Thanks,
Lionel
