### ISSUE TITLE
MP GO:1990426 mitotic recombination-dependent replication fork processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13033]
GO:1990426 mitotic recombination-dependent replication fork processing

has the parent 
GO:0006261 DNA-dependent DNA replication

could this move down to 
Name	mitotic DNA replication

to bring under nuclear replication terms, and separate it from mitochondrial

**Comment by ukemi** [comment]
It is part of DNA-dependent DNA replication. I could assert it is part_of 'mitotic DNA replication'.  Is that what you are requesting?

**Comment by ValWood** [comment]
yep (instead)
val

**Comment by ukemi** [comment]
It will still have the part-of parentage to the DNA-dependent DNA replication term because of its placement in the graph. I'm not sure what you mean by instead? Both paths will be correct.

**Comment by ValWood** [comment]
Yep I see the other part_of will still exist because of the "replication fork processing parent"
No prob.

This only came up because annotations were not getting scooped into mitotic cell cycle  with the rest.
