### ISSUE TITLE
presynaptic terminal 

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13047]
Consider adding "presynaptic terminal" to "axon terminus" (GO:0043679) as a synonym.  Thanks.

**Comment by dosumis** [comment]
Synonym should be on parent class 'presynapse' (this is more general, covering synapses where there the presynapse is not axonal - e.g. dendrodendritic synapses)

**Comment by slaulederkind** [comment]
Alright, that sounds reasonable.
