### ISSUE TITLE
protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13040]
add vesicle-mediate transport parent?

**Comment by ukemi** [comment]
This is the targeting of the protein to the vacuole, not transport of it by the vacuole.

**Comment by ValWood** [comment]
Isn't all
multivesicular body sorting vesicular transport though?

There seems to be a contradiction in this term.

"Targeting" refers to moving proteins to their resident/normal location/organalle usually via a resident signal sequence (or by binding to a partner molecule which has a sorting signal).

Modification based transport to an organelle for degradation isn't targeting? Its just transport (its modification dependent trafficking, which is vesicle mediated?)

So I don't think this term should mention targeting strictly.

https://en.wikipedia.org/wiki/Protein_targeting

**Comment by ukemi** [comment]
Protein targeting to vacuole is:
The process of directing proteins towards the vacuole, usually using signals contained within the protein.

vesicle-mediated transport is:
A cellular transport process in which transported substances are moved in membrane-bounded vesicles; transported substances are enclosed in the vesicle lumen or located in the vesicle membrane. The process begins with a step that directs a substance to the forming vesicle, and includes vesicle budding and coating. Vesicles are then targeted to, and fuse with, an acceptor membrane.

It seems to me that based on these defs, the term isn't a type of vesicle-mediated transport.

**Comment by krchristie** [comment]
Why would this not be vesicle-mediated transport? I think that the signals within the protein segregate it into specific kinds of vesicles which then go to the intended destination via vesicle-mediated transport. This is based on vague memories, rather than any recent research, but I don't think this is necessarily contradictory. [guess you're not sleeping @ukemi]

**Comment by ValWood** [comment]
I think the problem is deeper in GO.....

Protein targeting to vacuole exists (it is the targeting of *resident* proteins to the vacuole
based on *signals in the sequence*

protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway 


Is not strictly a type of targeting. I believe it should be renamed to

protein ttransport to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway 

(it isn't getting a resident protein to its normal destination via an "internal postcode", or via a "chaperone" which has an "internal postcode" which happens for some organellar targeting.

This is tagging a protein for destruction. I'm not sure how this process works completely but it isn't targeting. Somehow the ubiquitin signals release from its normal location for catabolism.


For the particular term I am questioning
protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

this *must* be vesicular, because MVB transport is vesicuar.

I think 3 changes would correct the problems.

1. rename GO:0043328 protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
to
protein transport to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

2. Remove protein targeting parent

3. GO:0032509 endosome transport via multivesicular body sorting pathway is a parent of GO:0043328, but it does not itself have
GO:0071985 multivesicular body sorting pathway
as a parent.
This will bring in "vesicle-mediated transport" for GO:0043328

**Comment by ukemi** [comment]
Protein targeting to vacuole exists (it is the targeting of resident proteins to the vacuole
based on signals in the sequence

The actual definition says usually based on signals in the sequence, that is not a necessity. The process that is being described by this term is the process that directs the protein to the right place, not necessarily the process that moves the protein. I went back and looked at the the paper that was used for the definition of this term and it looks like it would be used for things like the ESCRT complex proteins. It looks like those proteins are the ones that recognize the tagged proteins that are going to be degraded. In this case, the ubiquitination and the ESCRT complexes are directing the tagged proteins to the correct place and then the MVBs form and the rest of the catabolic process occurs. I think the MVB pathway is downstream from this step and is used to transport the proteins to the lysosome.

**Comment by ValWood** [comment]
targeting is about transporting to the correct location after synthesis
http://www.biologyreference.com/Po-Re/Protein-Targeting.html
https://en.wikipedia.org/wiki/Protein_targeting
https://www.ohio.edu/plantbio/staff/showalte/mcb%20720/protein%20targeting%20notes.pdf

Not all proteins contain signals. This is true. 
But this is because
i) not all targeting signals are identified
ii) Historically for detonations like ER signals were searched for at the N-term, but some proteins were later to have signals at other locations
iii) some proteins  “hitchhike” with other proteins (for example in nuclear targeting).
This is what the clause “Usually requires an organelle specific protein sequence motif”…it just covers the observation that not all targeted sequences have a detectable motif.

Our definition of protein targeting is missing the crucial  part that 
targeting is about  “directing to the correct location after synthesis”.

If this is included it becomes clear that MVB pathway, and other pathways 
which mark proteins for catabolism are not targeting, they are  only transport….

**Comment by ValWood** [comment]
This is a good example of vacuolar targeting from arabidopsis
https://www.ncbi.nlm.nih.gov/pubmed/25351491
its a resident protein...I would annotate  the AP1 gamma adaptin to the "protein targeting to vacuole" term

In pombe I can't find any real examples of vacuolar targeting, because all of our annotations are derived from the "transporting proteins to the vacuole for degradation"

**Comment by pgaudet** [comment]
1. rename GO:0043328 protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
to
protein transport to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
DONE in #13747
FIXED DEFINITION #13867

2. Remove protein targeting parent
DONE in #13747

3. GO:0032509 endosome transport via multivesicular body sorting pathway is a parent of GO:0043328, but it does not itself have
GO:0071985 multivesicular body sorting pathway
as a parent.
This will bring in "vesicle-mediated transport" for GO:0043328

**Comment by pgaudet** [comment]
@ValWood please close this if your queries are addressed. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think it's OK.
