### ISSUE TITLE
Add an import module for dicty

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13073]
We need to add an dicty_import file to define dicty GO terms

Blocked on: https://github.com/dictyBase/migration-data/issues/6

**Comment by pgaudet** [comment]
Hello @cmungall 
Is there anything you need me to do to complete this ? I might unassign myself if not! 

Pascale

**Comment by pgaudet** [comment]
@cmungall I don't know what I need to do here. Unassigning myself.

**Comment by vanaukenk** [comment]
@cmungall - does this pull request need to be merged (looks like it has conflicts now), or should I just re-do the changes?
