### ISSUE TITLE
query protein targeting to membrane involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13070]
See also 
https://github.com/geneontology/go-ontology/issues/13040

Should this term exist at all?

GO:0043329 protein targeting to membrane involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

The MVB sorting pathway transports to vacuole/lysosome. How would this term be used (has no annotations)

**Comment by ukemi** [comment]
Hmm. I think you are correct. I think this pathway catabolizes membrane bound proteins. So unless this term refers to the membrane localization of downstream complexes, it doesn't really make sense. The localization of the target proteins should be upstream of the process. I think we should propose obsoleteion, don't you?

**Comment by ValWood** [comment]
I think probably....and it still isn't targetting but I'll follow up on that with details next week :)

**Comment by ukemi** [comment]
Let's make a model in Noctua. There are some really nice reviews of the whole pathway available. Membrane proteins are ubiquitinated, they target to vesicles via ESCRT, then the MVB is formed, then it fused with lysosomes and the proteins are degraded.

**Comment by ukemi** [comment]
Don't worry @pgaudet  As I assign these, I am checking off your spots in the rota. You are way ahead of everyone now!

**Comment by pgaudet** [comment]
@ukemi thanks ;)

**Comment by ValWood** [comment]
I think the term can go...

**Comment by pgaudet** [comment]
Obsoletion notice sent:

Dear all, 

the proposal has been made to obsolete 
GO:0043329 'protein targeting to membrane involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway’ 

The reason for obsoleting is that the term is not cleary defined, in that it’s not specified to which membrane proteins are being targeted, and there is no reference. 

There are no annotations and the term is not part of any slim. 

Comments can be made here: 
https://github.com/geneontology/go-ontology/issues/13070
https://github.com/geneontology/go-ontology/issues/13040


We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on July 12, 2017. 

*** Unless objections are received by July 12, 2017 , we will assume that you agree to this change. ***

Thanks,

Pascale
