### ISSUE TITLE
Investigate why saving from Protege in obo format sometimes loses label after bang

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13074]
For example, this diff: https://github.com/geneontology/go-ontology/commit/f5791041a49708a50b8292184239f7855686768a

I suspect it is to do with references to terms not in the import module?

**Comment by pgaudet** [comment]
@cmungall Is this still a problem ? I dont think I ever saw it. Have you @ukemi ?

**Comment by ukemi** [comment]
Nope.

**Comment by pgaudet** [comment]
@cmungall can we close ?
