### ISSUE TITLE
 GO:0000963 mitochondrial RNA processing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13071]
based on this
https://github.com/geneontology/go-ontology/issues/11677

presumably 
 GO:0000963 mitochondrial RNA processing
should also not be 
part_of
 GO:0007005 mitochondrion organization

**Comment by pgaudet** [comment]
@ValWood I think this was resolved here: #13664 
please close if it was dealt with. 

Thanks, Pascale

**Comment by ValWood** [comment]
Yep!
