### ISSUE TITLE
NTR: retrograte transporter complex, Golgi to ER

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13082]
Complex that affects GO:0006890 retrograde vesicle-mediated transport, Golgi to ER:

Name: NTR: retrograte transporter complex, Golgi to ER

Def: Transporter complex that recognises, binds and returns endoplasmic reticulum (ER) resident proteins that have trafficked to Golgi compartments. Targets proteins lacking the HDEL motif recognised by COPI-coated vesicles. 

Comment: An example of this is ERV41 in Saccharomyces cerevisiae (Q04651) in PMID:16093310 (inferred from direct assay).

Synonyms:
ERV41-ERV46 retrograde receptor complex [NARROW]
retrograte transporter complex, Golgi to endoplasmic reticulum [EXACT]
retrograte receptor complex, Golgi to ER [EXACT]
retrograte receptor complex, Golgi to endoplasmic reticulum [EXACT]

Relationships:
is_a GO:1990351 transporter complex
part_of GO:0030173 integral component of Golgi membrane
part_of GO:0030176 integral component of endoplasmic reticulum membrane
part_of GO:0030126 COPI vesicle coat
part_of GO:0030127 COPII vesicle coat
capable_of(_part_of?) GO:0006890 retrograde vesicle-mediated transport, Golgi to ER (it carries out this process directly)

Interaction evidence: PMID:16093310

Thanks,
Birgit

Note to self: complex: EBI-13917353 (ready for release), add PMID:16093310 and IPI.

**Comment by ukemi** [comment]
Hi Birgit,

The complex cannot always be part of the ER membrane and always part of the Golgi membrane unless it is simultaneously bound to both. Is this true?

-D

**Comment by bmeldal** [comment]
Oh, damn, I hate these situations! It shuttles between ER and Golgi. I guess we can't annotate location beyond 'cell'.

**Comment by ukemi** [comment]
You can annotate, but it wouldn't go in the ontology.

**Comment by bmeldal** [comment]
Yes. Can you create the term then while ignoring the 2 compartments?

**Comment by bmeldal** [comment]
Thanks :)

**Comment by ukemi** [comment]
You're welcome. Note that I was unable to do any of the part_of parents because of the 'always part_of' rule.
