### ISSUE TITLE
TPV GO:0035337 fatty-acyl-CoA metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13097]
GO:0035337 fatty-acyl-CoA metabolic process
The chemical reactions and pathways involving a fatty-acyl-CoA, any derivative of coenzyme A in which the sulfhydryl group is in thiolester linkage with a fatty-acyl group.

this has ancestry to
GO:0006637 acyl-CoA metabolic process
The chemical reactions and pathways involving acyl-CoA, any derivative of coenzyme A in which the sulfhydryl group is in thiolester linkage with an acyl group.

and hence to
coenzyme metabolic process,

but it seems that "fatty-acyl-CoA metabolic process"

should be a "fatty acid metabolic process" rather than a "coenzyme metabolic process"

**Comment by ukemi** [comment]
This term is placed based on the logical definition with the ChEBI term. In ChEBI it is a fatty acid derivative. Therefore, it is derived from a fatty acid, but is not itself a fatty acid.

**Comment by ValWood** [comment]
My problem here was that


GO:0035337 fatty-acyl-CoA metabolic process
should not be (at least always) GO:0006637 acyl-CoA metabolic process

Although my suggested solution did not work...
instead should be
 GO:1901568	fatty acid derivative metabolic process ?

**Comment by ValWood** [comment]
ignore1
