### ISSUE TITLE
TPV: various TPV to small molecule metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13098]
fatty acid metabolic process (via organic acid biosynthetic process, not all small  molecule)
ergosterol metabolic process (via alcohol metabolic process, not all small  molecule))

**Comment by deustp01** [comment]
Missing something here. Are there fatty acids that are not small molecules? And ergosterol? Or is the problem something else?
Thanks

**Comment by ValWood** [comment]
Good point!
I think the distinction in GO is a bit arbitrary sometimes.

The chemical reactions and pathways involving small molecules, any low molecular weight, monomeric, non-encoded molecule.
Comment	Small molecules in GO include monosaccharides but exclude disaccharides and polysaccharides.


So we exclude disaccharides, but maybe we shouldn't....
We also exclude "cofactor metabolism" and again maybe we shouldn't...

**Comment by dosumis** [comment]
New proposal for what counts as small molecule here https://github.com/geneontology/molecular_function_refactoring/issues/35 leveraging ChEBI
(CC @thomaspd)

**Comment by ValWood** [comment]
cam be closed (cofactor  should be fixed via another ticket)
