### ISSUE TITLE
ntr: -ve regulation of mitotic G1 cell cycle arrest in response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13095]
cam do in term genie when back,
this to remind me

for
PMID:10921876
cdc2

**Comment by ValWood** [comment]
This one is tricky too.

In most cases we use response to when an pathway responds to multiple chemical onslaughts (we would use as an extension). We don't use plain "response to" terms for direct annotation, or at least we are purging them.


Here I think we need a precomposed term to describe the actual signalling pathway- to differentiate a very specific role regulating G2/M  in response to nitrogen.
see 
https://github.com/pombase/curation/issues/1638
(it's the endosulphine Greatwall pathway)

This would be a bit like the "stress activated MAP kinase pathway", or specific DNA damage responses being coupled to "response to DNA damage".

I'll cane come back to this one (after the GO meeting). No hurry...

**Comment by ValWood** [comment]
(note this is a specific signaling pathway, needs signalling parent)

**Comment by pgaudet** [comment]
@ValWood Should I create this as 'endosulphine Greatwall pathway'?

**Comment by ValWood** [comment]
Yes please that make more sense as a term name!

**Comment by pgaudet** [comment]
Great ! Can you provide a definition - including a start and end to the pathway ?

**Comment by pgaudet** [comment]
And what is the parent ?

**Comment by ValWood** [comment]
I think its very short.
The pathway itself  is only endosulphine -> greatwall
http://www.mdpi.com/2218-273X/7/3/59

**Comment by ValWood** [comment]
Sorry I didn't finish my comment.

I need to go back to this, because we already have
https://www.pombase.org/term/GO:1905287
leave it with me. won't be soon...

**Comment by ValWood** [comment]
will be covered by 
https://github.com/geneontology/go-ontology/issues/15399
