### ISSUE TITLE
astral microtubule/astral spindle assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13108]
Follow on from
https://github.com/geneontology/go-ontology/issues/13106

Could astral microtubule be a descendent of "spindle pole"

There is a strange term
astral spindle assembly
The aggregation, arrangement and bonding together of a set of components to form the spindle, the array of microtubules and associated molecules that serves to move duplicated chromosomes apart, in the presence of centrosomes.

This sounds like  just "spindle assembly" ?

**Comment by ukemi** [comment]
Plants are different. That is why this term exists.

**Comment by ValWood** [comment]
But the term 
astral spindle assembly
is a descendant of 
mitotic spindle assembly
and it is only used once by FlyBase @hattrill could you have a look?

so it does not seem to have been requested for plant (even though Tanya added it)

Also,  based on Tanya's response that still does not explain this terms meaning...

Astral microtubules are defined as part of the SPB centrosome, so there can't be a logical difference between  a "mitotic spindle" and an "mitotic astral spindle"

**Comment by ValWood** [comment]
- [ ]  make astral microtuble a decendent of spindle pole (this should fit all logical defs)

- [ ]  @hattrill  investigate what "astral spindle assembly" really means, if it is different from "spindle assembly" (astral microtubules are microtubules which  emenate from the SPB or centrosome)

 Depending on Helen's reponse, possible merge  (or obsolete) 
 "astral spindle assembly"  -> spindle assembly
and
"astral spindle assembly involved in male meiosis" -> "mieotic spindle assembly involved in male meiosis"

**Comment by mah11** [comment]
I claim no specialist knowledge whatsoever, but from existing terms I infer that "astral spindle assembly" is the assembly of an astral spindle, as opposed to an anastral spindle. The latter form without centrosomes/spindle pole bodies, or so I gather from the definitions of the relevant terms:

    GO:0051225 spindle assembly
    -- is_a GO:0055048 anastral spindle assembly
    -- is_a GO:0055049 astral spindle assembly

Note that the parent (GO:0051225) def does not mention centrosomes or SPBs, suggesting that the snippet above is basically correct.

Corresponding CC terms are not present, as far as I can tell; perhaps they should be added. Then astral MT could be part_of astral spindle pole.

**Comment by ValWood** [comment]
Sorry the question should be what is the difference between

mitotic spindle assembly/meiotic   and  sibling
astral spindle assembly (both of these would be astral  spindles, are there others?)

**Comment by mah11** [comment]
The existence of GO:0055048 implies that there are others, namely anastral spindles. I don't know whether they come in mitotic, meiotic or both flavors, but at least one of 'mitotic spindle' and/or 'meiotic spindle' can't be a subclass of astral spindle (maybe both, depending on when the anastral spindles form).

**Comment by ValWood** [comment]
OK, we can close. If some organisms "main mitotic spindle"  in anastral,  we would need astral and anastral flavours of everything and that isn't really necessary.
 Will ignore...

**Comment by mah11** [comment]
OK, there are definitely anastral meiotic spindles in oocytes, e.g.:

http://www.cell.com/biophysj/pdf/S0006-3495(09)01362-9.pdf
http://bmccellbiol.biomedcentral.com/articles/10.1186/1471-2121-12-1

Tanya's comment on #13106 suggests that plants have anastral mitotic spindles, but double-check with her.  @tberardini

**Comment by hattrill** [comment]
Glad you sorted this out before I lifted a finger - I had three papers set aside for some bedtime reading on the astral/anastral question, but I'll go back to my Mills and Boon now!
