### ISSUE TITLE
regulation of glutamatergic neuron differentiation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13107]
I would like to see “positive…”, “negative…”, and “regulation of glutamatergic neuron differentiation” added to GO under the parent term “glutamatergic neuron differentiation” (GO:1905962).  The definitions would be “Any process that modulates (activates or increases/stops, prevents, or reduces) the frequency, rate or extent of neuron differentiation.”  Example: PMID:24030726
P.S.: Where's TermGenie?

**Comment by krchristie** [comment]
Hi Stan,

Hopefully TermGenie will be back soon! Doing this by hand was way slower than using TG!!

Here are your terms.

-Karen

[Term]
id: GO:0120006
name: regulation of glutamatergic neuron differentiation
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of glutamatergic neuron differentiation." [PMID:24030726]
intersection_of: GO:0008150 ! biological_process
intersection_of: regulates GO:1905962 ! glutamatergic neuron differentiation
created_by: kchris
creation_date: 2017-03-01T16:10:27Z

[Term]
id: GO:0120007
name: negative regulation of glutamatergic neuron differentiation
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of glutamatergic neuron differentiation." [PMID:24030726]
intersection_of: GO:0008150 ! biological_process
intersection_of: negatively_regulates GO:1905962 ! glutamatergic neuron differentiation
created_by: kchris
creation_date: 2017-03-01T16:25:50Z

[Term]
id: GO:0120008
name: positive  regulation of glutamatergic neuron differentiation
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of glutamatergic neuron differentiation." [PMID:24030726]
intersection_of: GO:0008150 ! biological_process
intersection_of: positively_regulates GO:1905962 ! glutamatergic neuron differentiation
created_by: kchris
creation_date: 2017-03-01T16:35:45Z
