### ISSUE TITLE
Add 'DO NOT ANNOTATE' to cell cycle terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13113]
- GO:0022402 cell cycle process -> change 'do not manually annotate' to 'do not annotate' (no  annotations) 
- GO:1903046 meiotic cell cycle process (no manual annotation)
- GO:1903047 mitotic cell cycle process (5 EXP annotations) 

Note: 
- GO:1903046 meiotic cell cycle process  -> Annotate to GO:0051321 meiotic cell cycle
- GO:1903047 mitotic cell cycle process ->  Annotate to GO:0000278 mitotic cell cycle
On annotation tracker: https://github.com/geneontology/go-annotation/issues/1538

Pascale

**Comment by ukemi** [comment]
+1

**Comment by ukemi** [comment]
I'm going to assign this to me since you already did a subset property for another ticket. We need to give annotators and pipeline folks a heads-up at the next annotation call. Maybe the best way to organize that is to open a ticket on the annotation tracker and link it here?

**Comment by pgaudet** [comment]
Sure. If we could use the 'replace by' tag would this be automatically taken care of ? Or is this reserved for obsolete terms ?

**Comment by ukemi** [comment]
Reserved for obsolete terms.

**Comment by pgaudet** [comment]
Does 'Consider' work ?

**Comment by ukemi** [comment]
No. Those are both reserved for tags on obsolete terms. The first when there is a direct replacement for annotation and the second when the replacement is not direct, but likely.

**Comment by pgaudet** [comment]
Is there another tag available ?

**Comment by ukemi** [comment]
Thanks for creating the other ticket. At the moment there is not another tag, it just goes in the slim/subset. For some of these terms there are comments explaining why it they are in the subset. See GO:0031572. I will add a comment for these.

**Comment by ValWood** [comment]
Good move. We block these for annotation at PomBase, because deeper annotation should be possible if it really is a cell cycle gene...(along with 1247 other terms, mainly because annotation could be deeper, but sometimes they duplicate taxon checks, or processes redundant with MF terms).

See
https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/GO_terms_excluded_from_pombase.txt

for the complete list....

**Comment by ValWood** [comment]
Ah I misunderstood, "mitotic cell cycle" is still allowed. We 'disallowed' this because it should always be possible to make a more specific annotation. If you can really say its mitotic cell cycle, you must be able to say more....

This is for another day ;)
