### ISSUE TITLE
Taxon restraint for queuosine biosynthetic process?

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#13121]
Hi all, 

I came across a case in UniProt entries Q9BXR0 and Q9JMA2 where BP term GO:0008616 (queuosine biosynthetic process) has a taxon restraint preventing it from being used for any eurkaryotic entries, however the parent BP term (GO:0046116) and MF term GO:0008479 do not have the same restraint, suggesting that this process is exclusive to prokaryotes. 

After reading the literature, it would seem that eurkaryotes are capable of producing quenosines (PMID:19414587 and PMID:20354154 are two good examples). Can we look at potentially removing the taxon restraint for GO:0008616?

**Comment by ValWood** [comment]
Hi,

The term you need for eukaryotes is tRNA-guanine transglycosylation

History here and other linked tickets
https://github.com/geneontology/go-ontology/issues/12536

Essentially eukaryotes use dietary queuosine for tRNA modification.

Val
