### ISSUE TITLE
ntr: intestinal hexose absorption

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#13122]
(This would be a generalization of the existing term GO:0001951 intestinal D-glucose absorption.)

GO:new intestinal hexose absorption. Uptake of hexoses, notably D-glucose, fructose, and galactose, into the blood by absorption from the small intestine.
Is_a child of  GO:0008645 hexose transport. and of  GO:0050892 intestinal absorption.
I guess GO:0001951 would become an is_a child of GO:new.

GO:new would have the same taxon constraints as GO:0001951 (at least - never in yeasts and only in eukaryotes looks like annotations to plants, protozoa, and multicellular invertebrates with no intestines would be permitted.)

**Comment by ukemi** [comment]
We should make all kinds of intestinal absorbtion be the whole process from the intestinal lumen into the blood. Let's standardize the terms as part of this ticket.
Maybe even play around with logical defs specifying the substance and target start and end locations. Could become a design pattern if we think there will be enough of them.

**Comment by dosumis** [comment]
The pattern we use for transport across membrane should work just fine if you can use Uberon or CL to specify the anatomical structure or cell type transported across.

'transports or maintains localization of' some {chemical}
and 'has target start location' some 'intestinal lumen'
and 'has target end location' some  blood??
and 'results in transport across' some ??

**Comment by ukemi** [comment]
On second thought, I don't think this specification will work for all organisms. It depends on what GO means by intestine and blood. In UBERON:0000160 intestine is quite specific, but there are annotations to fly and worm. This doesn't affect the addition of the new subclasses.

**Comment by deustp01** [comment]
Three comments.

Comment on David O-S pattern: absorption here means moving an entity across two membranes and one cytosol: from the gut lumen into the cytosol of a cell lining the gut, and from that cell into the organism's circulatory system.

Comment on David H's second thought: if sorting out the kinds of gut and whether they are equivalent for the purpose of amall-molecule absorption is tricky, can we start by using a taxon restriction - only in chordates? only in vertebrates? - to generate terms that are workable for the guts we're familiar with.

Finally, the "hexose" I have in mind is CHEBI:18133 - hexose "Any six-carbon monosaccharide which in its linear form contains either an aldehyde group at position 1 (aldohexose) or a ketone group at position 2 (ketohexose)." Note that this "hexose" is more general than the one described in a relevant current GO definition: GO:0008645 hexose transport "... Hexoses are any aldoses with a chain of six carbon atoms in the molecule." Excluding ketose sugars leaves out molecules including fructose, which definitely are substrates for mammalian intestinal absorption.

**Comment by ukemi** [comment]
Hi Peter,
I don't think we need to add additional taxon constraints. I think the addition of the logical def would inadvertently add one if we are not careful about anatomical structures that are chosen and what they mean. I don't see any problem with simply having the term mean exactly what you suggest above, intesine (in its broadest sense) lumen to the circulatory system.

The equivalence axiom of the hexose transport term uses CHEBI:18133, so that is in fact what the term means and it is automatically characterized according to it. The textual def should be updated.

**Comment by dosumis** [comment]
On Mar 4, 2017, at 9:45 AM, David Hill <notifications@github.com> wrote:
> 
> On second thought, I don't think this specification will work for all organisms. It depends on what GO means by intestine and blood. In UBERON:0000160 intestine is quite specific, but there are annotations to fly and worm. This doesn't affect the addition of the new subclasses.

Uberon has more general classes to deal with this:

hemolymphatic fluid (UBERON_0000179)
lumen of intestine (UBERON_0018543) @cmungall - is this general enough? - if not we need a new term in Uberon.

**Comment by cmungall** [comment]
intestine is intended to be generic

```
def: "Segment of the alimentary canal extending from the stomach to the anus and, in humans and other mammals, consists of two segments, the small intestine and the large intestine." [GOC:GO, Wikipedia:Intestine]
```

Comments welcome on the definition. It doesn't work well for species like zebrafish that lack a true stomach, but the intent is to represent the terminal portion.

The mammal part should really be gloss as it's of the form "an example is found in..."

I'm partially in favor of relabeling the class "last half of digestive tract" or similar, and having a mammal specific 'true intestine' that is part of this.

**Comment by cmungall** [comment]
Maybe of relevance
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4458075/

**Comment by hdrabkin** [comment]
Add term per request and altered def as requested.

**Comment by deustp01** [comment]
But the new term  GO:0106001 intestinal hexose absorption is shown at quickGO as an is_a child of  GO:0001951 intestinal D-glucose absorption. SHould be the other way around.

**Comment by hdrabkin** [comment]
fixed
