### ISSUE TITLE
NTR: negative regulation of GO:0007611 learning or memory

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13127]
I need:
negative regulation of GO:0007611 learning or memory
Happy to have the full set of regs.
Reference: PMID:18568035

Thanks,
Birgit

**Comment by ukemi** [comment]
discussion here: #12512

**Comment by pgaudet** [comment]
Is this a duplicate of #12512 ? 
@ukemi @bmeldal

**Comment by bmeldal** [comment]
Yes, we can carry on discussing this in David and Helen's original ticket :)
