### ISSUE TITLE
NTR : GATOR1 complex

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#13135]
Dear editors,
within the TOR signaling pathway, we have a term describing the GATOR2 complex, but I could not find one for the GATOR1 complex described here PubMed=23723238, which existence is now well admitted PubMed=28199306. This complex is composed in mammals of DEPDC5, NPRL2 and NPRL3 and it functions as an inhibitor of the amino acid-sensing branch of the TORC1 pathway. Maybe it would also be nice to add to the definitions of both terms that both constitute GATOR subcomplexes. I wonder if we should add the GATOR complex as a parent?
Thanks in advance for your help,
Lionel

**Comment by robnash** [comment]
Hi Lionel,

I believe GATOR1 is equivalent to the IML1 complex (see the synonyms) first described in yeast:

http://amigo.geneontology.org/amigo/term/GO:1990130

with parent = GATOR

http://amigo.geneontology.org/amigo/term/GO:0035859

Cheers,
Rob

**Comment by ValWood** [comment]
Would GATOR1 be a more universal name? I have noticed that pombe people are calling it GATOR1  probably as its a bit more memorable than a gene name...
(or do people also use IML1 in other species?)

**Comment by hdrabkin** [comment]
Could add GATOR1 as a synonym for IML1 complex;

**Comment by hdrabkin** [comment]
Collectiing usage stats:
Pubmed search on title for "IML1 complex" 0
"GATOR1 complex", 3
In title/abstract, 10 GATOR1 complex, 2 for "IML1 complex"

**Comment by robnash** [comment]
Hi,

Catchier name will probably prevail. GATOR is currently a synonym for GO:0035859 Seh1-associated complex and GATOR1 a synonym for GO:1990130 Iml1 complex. If GATOR1 becomes the term name than the parent term GATOR should also me made the term name.

Cheers,
Rob

**Comment by ValWood** [comment]
No pombe publications yet, but I have seen that they will be using GATOR ....

**Comment by lbreuza** [comment]
Thanks for your help.
I have used GO:1990130 and let you change to GATOR1 if you think it is better. To me it makes more sense to harmonize to GATOR1, GATOR2 and GATOR complexes. Please note that we have several TOR-related complexes eg Ragulator and Kicstor.
Regards,
Lionel

**Comment by hdrabkin** [comment]
Complex renamed to GATOR1 complex; old name added as exact synonym.
