### ISSUE TITLE
inconsistencies in taxon constraints on cilia terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13131]
I was just annotating Panther family PTHR10779 (DYNEIN LIGHT CHAIN ROADBLOCK) in PAINT and propagated some terms specific to cilia and ciliary movement. For some terms PAINT marked a loss for fungal taxa, but it marked the losses for the three different ciliary terms in different places, or not at all, so I think we need to check if the taxon constraints are done correctly.

**Relevant fungal species in the family:**

- two Ascomycota species
-- Neurospora crassa 
-- Phaeospaeria nodorum
- two Basidiomycota species 
-- Ustilago maydis 
-- Puccinia graminis (3 sequences)

**GO Terms**

**outer dynein arm (GO:0036157)** 
- blocked for the two Ascomycota species, but not for the two Basidiomycota species

**cilium movement (GO:0003341)**
- not blocked at all, so this term is propagated to the the two Ascomycota species as well as to the Basidiomycota species. I thought Ascomycota had lost cilia entirely, so this seems like it might be wrong.

**cilium movement involved in cell motility (GO:0060294)**
- blocked for both the Ascomycota and the Basidiomycota species

@ukemi - I'll need help to know how to check the taxon constraints

**Comment by krchristie** [comment]
Added never_in_taxon constraints to term "cilium movement" to match the constraints present on "cilium assembly" since organisms that don't assembly cilia can never have "cilium movement".

These are new and pre-existing taxon constraints on the term "cilium movement" now.

+relationship: never_in_taxon NCBITaxon:3176
+relationship: never_in_taxon NCBITaxon:3312
+relationship: never_in_taxon NCBITaxon:3378
+relationship: never_in_taxon NCBITaxon:3398 ! Magnoliophyta
+relationship: never_in_taxon NCBITaxon:4890 ! Ascomycota
+relationship: never_in_taxon NCBITaxon:5782
 relationship: only_in_taxon NCBITaxon:2759 {id="GOTAX:0010017"} ! Eukaryota

**Comment by cmungall** [comment]
Do we encode this dependency? If we did we could automatically propagate TCs. Would also be useful for phenotype inference.

**Comment by krchristie** [comment]
I agree that it would be nice if "cilium movement" could inherit the taxon constraints from "cilium assembly", but I don't currently see any kind of relationship between "cilium movement" and "cilium assembly".

Biologically, "cilium movement" depends on or requires "cilium assembly", i.e. you can't have any ciliary movement if you don't have a cilium at all. Do we use any relationships in GO to encode that type of relationship?
