### ISSUE TITLE
NTR : GATOR1 complex binding

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#13136]
Dear editors,
could you please consider creating this term that I could annotate to SZT2 which mediates the interaction between the KICSTOR complex and the GATOR1 complex as shown here : PubMed=28199306.
Thanks in advance.
Lionel

**Comment by ukemi** [comment]
It might be better to capture this kind of information in an annotation and an annotation extension. Simply annotate to 'protein complex binding' (which will become 'protein-containing complex binding') and has_input the complex.

**Comment by hdrabkin** [comment]
yes, I agree; otherwise we will need binding terms for every complex no doubt

**Comment by lbreuza** [comment]
I fully agree with you, but I was asking this term because I could find for instance TORC2 complex binding
GO:1904841 and many others. Kind of inconsistency?

**Comment by hdrabkin** [comment]
Did we agree to go ahead and make anyways??? I'd like to close this ticket.

**Comment by pgaudet** [comment]
I think we agreed to create those terms. 

Pascale

**Comment by hdrabkin** [comment]
GO:0106080  GATOR1 complex binding
