### ISSUE TITLE
ntr: sister chromatid decatenation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13144]
Could I request a term:
mitotic sister chromatid decatenation
Separation of the physical linkage between two DNA strands during mitotic chromosome segregation, resulting in the correct resolution of sister chromatids at anaphase.

I'm not *quite* sure how it should be defined, as I haven't read any papers describing it.
review here:
https://www.ncbi.nlm.nih.gov/pubmed/26266709
a nice in vitro assay from Frank Uhlmann showing condensin involvement:
https://www.ncbi.nlm.nih.gov/pubmed/24062159

this is to replace an existing annotation to
"DNA unwinding involved in DNA replication" 
for
S. cerevisiae MCD1

From Rob:
"I agree this is not the correct term. However, I do not see the replacement term "sister chromatid decatenation" that you are refering to. For now I am deleting the annotations from this paper. If there is a term in the ontology please let me know. If not, please request one and I would be happy to add back the annotations."

**Comment by ukemi** [comment]
Wouldn't this be covered by 'mitotic sister chromatid separation' GO:0051306 or one of its children?

**Comment by ValWood** [comment]
I wondered if it should be a child of separation, and probably it should. It's possible I misunderstood the type of linkage being discussed here. I thought the catenation referred to 2 interlinked DNA molecules, that required resolving, not to two molecules linked by cohesin. Will close because the immediate issue (annotation to "DNA winding involved in DNA replication") is resolved.

**Comment by ValWood** [comment]
meant to close this one
