### ISSUE TITLE
Usage of 'x complex binding' terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13148]
As a follow up on https://github.com/geneontology/go-ontology/issues/13136
If the policy is to use the extensions for x complex binding, we should remove some terms in the ontology that are inconsistent with that proposed rule. First to evaluate what annotations we'd need to change, here are the different 'x complex binding terms' used for manual annotation: 

GO ID	GO Name
GO:0051015	actin filament binding
GO:0048185	activin binding
GO:0010997	anaphase-promoting complex binding
GO:0035650	AP-1 adaptor complex binding
GO:0035612	AP-2 adaptor complex binding
GO:0035651	AP-3 adaptor complex binding
GO:0071933	Arp2/3 complex binding
GO:1904288	BAT3 complex binding
GO:1904713	beta-catenin destruction complex binding
GO:0036461	BLOC-2 complex binding
GO:0005518	collagen binding
GO:0098639	collagen binding involved in cell-matrix adhesion
GO:0098633	collagen fibril binding
GO:0070052	collagen V binding
GO:0070840	dynein complex binding
GO:1990448	exon-exon junction complex binding
GO:0034988	Fc-gamma receptor I complex binding
GO:0070051	fibrinogen binding
GO:0031683	G-protein beta/gamma-subunit complex binding
GO:0032795	heterotrimeric G-protein binding
GO:0019862	IgA binding
GO:0019863	IgE binding
GO:0019864	IgG binding
GO:0001791	IgM binding
GO:0019865	immunoglobulin binding
GO:0005158	insulin receptor binding
GO:0005178	integrin binding
GO:0098640	integrin binding involved in cell-matrix adhesion
GO:0019215	intermediate filament binding
GO:1990254	keratin filament binding
GO:0043515	kinetochore binding
GO:1904931	MCM complex binding
GO:0036033	mediator complex binding
GO:0023027	MHC class I protein binding, via antigen binding groove
GO:0023024	MHC class I protein complex binding
GO:0023030	MHC class Ib protein binding, via antigen binding groove
GO:0042658	MHC class II protein binding, via antigen binding groove
GO:0023026	MHC class II protein complex binding
GO:0032405	MutLalpha complex binding
GO:0032406	MutLbeta complex binding
GO:0032407	MutSalpha complex binding
GO:0032408	MutSbeta complex binding
GO:1990593	nascent polypeptide-associated complex binding
GO:0070628	proteasome binding
GO:1904854	proteasome core complex binding
GO:0032403	protein complex binding
GO:1905394	retromer complex binding
GO:0099122	RNA polymerase II C-terminal domain binding
GO:1990269	RNA polymerase II C-terminal domain phosphoserine binding
GO:0000993	RNA polymerase II core binding
GO:1905334	Swi5-Sfr1 complex binding
GO:0042608	T cell receptor binding
GO:1904841	TORC2 complex binding
GO:0005132	type I interferon receptor binding

**Comment by RLovering** [comment]
is this really the way we are going? I think that some of these more specific statements are of use to the user community and unless the complex information will be available/visible in existing tools (DAVID, g:Profiler) and knowledgebases eg NCBIGene, UniProt etc then this feels like the loss of a lot of information. 

Also some of these terms have additional parents, eg GO:0023030 MHC class Ib protein binding, via antigen binding groove is a child of receptor binding and antigen binding. Having said that I think antigen binding is wrong will add a ticket for that.

Does this mean all specific receptor binding terms will be reduced to receptor binding with AE specificity?

When the AE field was introduced we were told if the AE was used a lot the term would be created, now we are being told the opposite. 

For human this means loosing 1400 specific annotations, these will not be manually converted to protein complex : AE specificity (there are 1700 protein complex annotations and 300 are to the parent term)

Ruth

@rachhuntley

**Comment by rachhuntley** [comment]
I get the impression from the original ticket that no new complex binding terms will be made if it can be captured in AE. It doesn't say that the existing ones should be removed. I think we have discussed this many times at GOC meetings and I recall there was agreement that we would not get rid of existing terms, which I agree with Ruth, are very useful in analyses. I'd have to look back to find meeting minutes though.

Can someone please clarify if this is actually a new proposal and if so, where the agreement to do this is documented?

**Comment by pgaudet** [comment]
Hello Ruth, Rachael, 

The issue here is that it's not possible to create an infinite number of 'x complex binding' terms, so I am trying to see how much they are used and look for possible alternatives to capture this information. This is not yet a proposal, I am only looking at usage. 

Thanks, Pascale

**Comment by hattrill** [comment]
I am adding a pointer to the annotation consistency excercise from last April (http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-04-26), where there was a general agreement that different things interacting with complexes should be annotated with x complex binding to avoid over-proliferation of specific complexes.

"I believe that the consensus from the GO meeting is that we don't need these [specific complex] terms, and we use "x complex binding" to represent these specific inhibitor/activator-complex interactions (the logic being that only the functional complex is represented in GO)?"

**Comment by pgaudet** [comment]
I think this can be closed. The editors decided to create these terms. Right @ukemi ?
