### ISSUE TITLE
add taxon restriction  to "nitrogen fixation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13156]
Only bacteria and plants?
not sure.
Currently has a human annotation...

**Comment by hdrabkin** [comment]
I'm hesitating because I don't think I can say
ONLY in bacteria and then say ONLY in plants; this requires some extra futzying around once I get some documentaion.

**Comment by hdrabkin** [comment]
Actually, the plants don't do it; their symbiont bacteria are responsible.

**Comment by hdrabkin** [comment]
we need to make a new NCBITaxon_Union for Bacteria or Archaea

**Comment by hdrabkin** [comment]
AHAH
[Term]
id: NCBITaxon_Union:0000004
name: Prokaryota
namespace: union_terms
union_of: NCBITaxon:2 ! Bacteria
union_of: NCBITaxon:2157 ! Archaea
created_by: jdeegan
creation_date: 2008-07-24T11:56:07Z

AND we have this in Protege  already!

**Comment by hdrabkin** [comment]
done
