### ISSUE TITLE
Possible restrictions for strictly filamentous fungal species

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#13158]
Can we implement taxon restrictions for strictly filamentous species and Dimorphic fungi and true yeast? I can go down a list and pretty easily define each type.

The ability to mate also has the same issue. C. albicans mates but mating has never been observed in C. glabrata though the annotations from Ca are inferred for Cg. 

It seems like there should be restrictions on inferred annotations between some fungal species with directionality also considered.

Diane

**Comment by krchristie** [comment]
Hi Diane,

Again, seems sensible, but I'll need more details about which GO terms need taxon restrictions, and which taxa should receive "never_in_taxon" restrictions. If there are entire groups that should be restricted, it would be nice to make these restrictions at higher level grouping terms, rather than each specific species.

thanks,

-Karen

**Comment by krchristie** [comment]
@dianeoinglis - If this is still an issue you want to pursue, I need the specific GO terms on which you think taxon restrictions should be applied.

**Comment by dianeoinglis** [comment]
I agree it would be nice to use high level taxons for restrictions but that is quite impossible because it is exactly the case that species within a group have significant differences in biology that many process terms are irrelevant in related species. For example, Candida glabrata does not make or undergo filamentous growth as Candida albicans and other Candida species. C. glabrata does, however have orthologs of C. albicans mating genes but without the process. Aspergillus fumigatus has a number  of 'patjogenesis' annotations  other Aspergillus species  are not pathogens. The exceptions in BP among fungal species are so numerous that it's hard to know where to begin. A good rule of thumb might be to transfer only the most conserved BP such as cell cycle, DNA replication, etc and restrictthe transger of BP: 'mating,' 'filamentous growth,' 'hyphal growth'',' and 'pathogenesis.'

**Comment by krchristie** [comment]
Hi @dianeoinglis - So, what I'm gathering from your most recent comment is that it is not possible to implement reasonable taxon constraints, meaning that this is not an ontology issue. Therefore, I am going to close this ticket. If I have misunderstood, please reopen the ticket and indicate the specific taxon constraints you think should be implemented.

If you have issues with specific annotations, it might be appropriate to open a ticket(s) in the Annotations tracker: https://github.com/geneontology/go-annotation/issues
