### ISSUE TITLE
NTR: L-aspartate import & D-aspartate transmembrane transporter activity

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13150]
Re: Noctua model SynGO #1.
I would like to request new terms to annotate Figure 4 from PMID:7914198.

NTR1: L-aspartate import
This would be a child of: GO:0043092 L-amino acid import 
and GO:0070778 L-aspartate transport

NTR2: D-aspartate transmembrane transporter activity
This would be a child of: GO:0015172 acidic amino acid transmembrane transporter activity 
and GO:0005310 dicarboxylic acid transmembrane transporter activity
and GO:0070777 D-aspartate transport (perhaps D-aspartate transmembrane transport should be created too)
and GO:0042943 D-amino acid transmembrane transporter activity

Thanks,
Barbara

@RLovering 
@thomaspd 

GOC:bc
GOC:SynGO-UCL

**Comment by BarbaraCzub** [comment]
Thank you @pgaudet for having created the GO:0140010 D-aspartate transmembrane transporter activity MF term. 

However, I don't think the 'L-aspartate import' BP term has been created yet? Or is it being processed?

I imagine it should fit into its ontology branch similarly to how the 'D-asparte import' and 'L-glutamate import' terms do. Atm, a more specific GO term 'L-aspartate import across plasma membrane' exists, but there seems to be no 'L-aspartate import' on its own.

![screen shot 2017-03-21 at 10 15 16](https://cloud.githubusercontent.com/assets/16541096/24142984/25bb6840-0e20-11e7-959e-a3b6c5e2db6d.png)

**Comment by BarbaraCzub** [comment]
Actually, could I please request '[specific amino acid] transmembrane import' terms (which would become children of GO:0044745) for L-aspartate, D-aspartate and L-glutamate? @dosumis has just pointed out that these would be more relevant to the experiment being annotated, as the 'import' terms on their own are not children of 'transmembrane transport', which is what the experiment is showing.

**Comment by pgaudet** [comment]
Hi Barbara, 

I didn't create 'L-aspartate import' because I thought you meant  'L-aspartate import across the plasma membrane). Can you please specify across which membranes the amino acids re being transported ? 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi Pascale,

All three amino acids L-aspartate, D-aspartate and L-glutamate, evaluated in the annotated experiments, are imported into Xenopus oocytes across their plasma membrane, which is enabled by human SLC1A1 (Figure 4 from PMID:7914198).

I did not annotate using the term 'L-aspartate import across the plasma membrane', because I wanted to be consistent with use of the three amino acid transport terms, and atm I have no such option, because (unlike 'L-aspartate import across the plasma membrane'), 'D-aspartate import' and 'L-glutamate import' are not children of 'amino acid transmembrane import'.

Therefore, I requested '[specific amino acid] transmembrane import' terms, as 
'D-aspartate transmembrane import' is more specific than 'D-aspartate import', and similarly 'L-glutamate transmembrane import' is more specific than 'L-glutamate import'. Whereas 'L-aspartate transmembrane import' could become a parent of 'L-aspartate import across the plasma membrane'. But if we need to specify the membrane type for 'D-aspartate import' and 'L-glutamate import', then let's use the template: '[amino acid] import across the plasma membrane', and leave the ontology branch of 'L-aspartate import across the plasma membrane' as it is.

Thanks,
Barbara

**Comment by pgaudet** [comment]
Hi Barbara, 

Thanks for the clarification. This part of the ontology is probably more complicated than it should be. As far as I know, all import of specific molecules such as amino acids occurs across the plasma membrane, and is a transmembrane transport. So I would like to merge the terms 'x import into cell'/ with 'x import across plasma membrane', and make the parents more consistent. Would that address your request ? 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi Pascale,

I suppose it is a good idea to merge 'amino acid import into cell' with 'amino acid import across plasma membrane', but 'L-glutamate import' and 'D-aspartate import' are not children of this branch (screenshot below), and they probably should be, so further rearrangements in the ontology would be needed to ensure that they become siblings with 'L-aspartate import...' rather than (slightly distant) cousins.

Thanks,
Barbara

![25bb6840-0e20-11e7-959e-a3b6c5e2db6d](https://cloud.githubusercontent.com/assets/16541096/24399199/e6e11e56-13a3-11e7-9834-6a89aa97ff3e.png)

**Comment by pgaudet** [comment]
Yep ! agreed.

**Comment by pgaudet** [comment]
<img width="527" alt="image" src="https://cloud.githubusercontent.com/assets/4782928/24399510/4714af50-13ad-11e7-8fca-f120df086397.png">

**Comment by BarbaraCzub** [comment]
I'm assuming 'D-aspartate import...' is further down?

**Comment by dosumis** [comment]
Few notes:

* Any attempt to re-arrange this needs to be done using patterns and inference of classification - it's way too complicated to maintain by hand. 

* Be careful not to confuse the generic import terms with 'import into cell'.  Note -  there is a known issue with the patterns used for import and export - specifically the imports and exports relations are dubious.

* The distinction between import into cell and import across the PM needs to be maintained for macromolecules (see receptor-mediated endocytosis & transcytosis).

**Comment by BarbaraCzub** [comment]
I suppose for macromolecules the distinction between import into cell and import across the PM would be maintained as macromolecules are higher up in the ontology than amino acids?

**Comment by BarbaraCzub** [comment]
Ok, actually, I cannot find a macromolecule import term at all.

**Comment by pgaudet** [comment]
Thanks @dosumis 
In fact there were a few subclasses, and some discrepancies in the logical definitions I came across. I used this pattern everywhere: 
transport
 and ('has target start location' some 'extracellular region')
 and ('has target end location' some cytosol)
 and (imports some amino acid)
 and ('results in transport across' some 'plasma membrane')

The correct subclasses seem to have been inferred. 

- Pascale

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 

I hasn't created the new term yet. How does that look ? 
<img width="451" alt="image" src="https://cloud.githubusercontent.com/assets/4782928/24404871/1e0192c0-13c3-11e7-9c0d-4cdd1f6be7a1.png">

**Comment by BarbaraCzub** [comment]
Looks good to me!

**Comment by pgaudet** [comment]
Hello @dosumis 
When you have some time would you please check this - and let me know if I can merge? 

Thanks, 
Pascale

**Comment by ValWood** [comment]
I agree that the intermediate terms are not useful. We have no evidence that amino acid transport occurs via any mechanism than TM transport. It is unlikely to occur via endocytosis/exocytosis. This is the mechnaism to deal with the PM transporters themselves.
(and if some  other mechanism does turn up we can deal with that property later).


My only request is that we keep the "transmembrane" term names for consistency
http://pombase2.aska.gen.nz/term/GO%3A0055085
(and because it is good to know at a glance, there are some molecule transporters which are not transmembrane)

**Comment by pgaudet** [comment]
Hi Val, 

I'll fix all these, the goal is that there won't be any orphans when this is done.  

Pascale

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 

The terms you need should now be in the ontology. Please let me know if you see any issues. 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi @pgaudet 

Thanks for the update.

I have found:
- [GO:0098712] L-glutamate import across plasma membrane; and
- [GO:0140009] L-aspartate import across plasma membrane.

But I have not been able to find 'D-aspartate import across plasma membrane'. Perhaps this has not updated yet? (It is on your latest screenshot).

Thanks,
Barbara

**Comment by pgaudet** [comment]
Hi Barbara, 

I don't see it in Protein2GO/QuickGO, but the term is in AmiGO. 
@tonysawfordebi : can you remind me when the EBI tools are updated? 

Thanks, 

Pascale

**Comment by RLovering** [comment]
You should be able to use these terms in QuickGO even if it doesn't display the GO term name

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet 
This is useful to know. However, something is still not right, as the term is not searchable in Noctua. I would have thought that Noctua would pick it up, if it has been indexed in Amigo? Is this something we should check with Seth? (@RLovering it was a different term that I contacted QuickGO helpdesk about, which did not have the name displayed, even though the GO term number was visible in the ontology).
Barbara

**Comment by dosumis** [comment]
All of these pipelines take time.  QuickGO usually 2-3 days at least in my experience.

**Comment by BarbaraCzub** [comment]
Hi @dosumis I agree these pipelines take time, but I would imagine that all of the new terms would become available at the same time. Why two of them became available immediately in several resources (including Noctua), and one only appears in Amigo but nowhere else? But perhaps these terms 'take different routes'. Let's wait and see!

**Comment by pgaudet** [comment]
Looks like D-aspartate import across plasma membrane is now in P2GO.

**Comment by kltm** [comment]
Okay, to follow up on the availability of GO:0140010 and GO:0140016 in various GO resources.
Both are available in AmiGO, which makes sense as it was last refreshed a few days ago.

However, the development loads of "AmiGO", including the one that drives Noctua, were in suspension for the last week plus due to them being made ready to act as failover for a spotty machine at the production site.

It looks like production is on an even keel again, so I will trigger these builds tonight.

**Comment by BarbaraCzub** [comment]
Hi @kltm 

Something has certainly happened, as now the GO term names completely disappeared from my model for: 
GO:0140009 L-aspartate import across plasma membrane; and
GO:0140010 D-aspartate transmembrane transporter activity.
The GO term IDs appear to be displayed instead...
![screen shot 2017-04-11 at 13 14 42](https://cloud.githubusercontent.com/assets/16541096/24908780/4c4f0a76-1eb9-11e7-98b7-b0ced9aa3ec8.png)

However, the term 'GO:0140009 L-aspartate import across plasma membrane' is still not searchable in Noctua.

But perhaps whatever you triggered is still in progress?

**Comment by BarbaraCzub** [comment]
Hi @kltm 

Similarly to the model which I mentioned above (this actually was: SynGO no. 1a)
I have just noticed a similar problem in this model: SynGO no. 1c

Here the 'GO:0099054 presynapse assembly' term is displayed as only the GO term ID, whereas the term name is displayed for all other terms.

**Comment by dosumis** [comment]
I’ve been noticing general flakiness in GO term autocomplete this afternoon.  Was halfway through writing a bug report when it fixed itself.  Autocomplete on all other OBO terms seems to be working fine.

**Comment by BarbaraCzub** [comment]
Thanks for the info @dosumis 
Unfortunately my autocomplete issues have not resolved themselves. In fact new ones (which can be seen in the same Nactua model 'SynGO no. 1c') have emerged since I sent the last message.

**Comment by kltm** [comment]
@cmungall 
nakama and NEO GOlrs had successful loads last night. Please compare:
http://amigo.geneontology.org/amigo/search/ontology
and:
http://amigo2.berkeleybop.org/amigo/search/ontology

**Comment by cmungall** [comment]
Noctua issued moved here: https://github.com/geneontology/noctua/issues/411
