### ISSUE TITLE
Possible restrictions for conidial and nonconidial yeast

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#13159]
Annotations for conidial phenotypes are currently transferred to nonconidial yeast such as N. crassa and Aspergillus to Candida species which do not make contidia. Perhaps species restrictions should be applied for the contidiation process.

Diane

**Comment by krchristie** [comment]
Hi Diane,

Seems sensible in principle. Could you indicate the specific terms that are being transferred inappropriately. 

Could you also indicate which taxa are non-conidial that you would like to prevent from receiving conidial annotations. Here's a link to the NCBI taxonomy browser: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi 

thanks,

-Karen

**Comment by pgaudet** [comment]
I am guessing: 
'conidiophore development' <http://purl.obolibrary.org/obo/GO_0070787>
'conidiophore stalk development' <http://purl.obolibrary.org/obo/GO_0070788>
'conidium development' <http://purl.obolibrary.org/obo/GO_0061794>
'conidium formation' <http://purl.obolibrary.org/obo/GO_0048315>
'conidium germination' <http://purl.obolibrary.org/obo/GO_0120164>
'conidiophore development' <http://purl.obolibrary.org/obo/GO_0070787>
'conidiophore stalk development' <http://purl.obolibrary.org/obo/GO_0070788>
'conidiophore stalk' <http://purl.obolibrary.org/obo/FAO_0000050>
'conidium development' <http://purl.obolibrary.org/obo/GO_0061794>
'conidium formation' <http://purl.obolibrary.org/obo/GO_0048315>
'conidium germination' <http://purl.obolibrary.org/obo/GO_0120164>

However the definition 'conidium germination' <http://purl.obolibrary.org/obo/GO_0120164>
mention Colletotrichum, Ustilago -> are these Ascomycota? 

@dianeoinglis please let us know how to proceed.

**Comment by ValWood** [comment]
@mah11  is it correct that 
'conidiophore' is never in yeast ?

**Comment by ValWood** [comment]
I think this is restricted to filamentous fungi?

So maybe we can say "never in Saccharomycotina"
and
never in "never in Taphrinomycotina"

**Comment by mah11** [comment]
Short answer: I don't know.

There are certainly fungi that have a yeast form and make conidia, and I don't know which fungal taxa entirely lack conidia. I don't know off the top of my head of any in Saccharomycotina or Taphrinomycotina that do form conidia, but I can't claim to know enough to make a definitive statement. That said, you could always add the taxon constraints for now and remove them if biology turns up exceptions.

**Comment by ValWood** [comment]
OK let's add

So maybe we can say "never in Saccharomycotina"
and
never in "never in Taphrinomycotina"

and refine later

**Comment by pgaudet** [comment]
I cannot put only in Fungi, and 'never in' some children.

We need to do 'only in' the relevant taxa - I dont know what they are.

**Comment by pgaudet** [comment]
relationship: never_in_taxon NCBITaxon:147554 ! Schizosaccharomycetes
relationship: never_in_taxon NCBITaxon:2 ! Bacteria
relationship: never_in_taxon NCBITaxon:2157 ! Archaea
relationship: never_in_taxon NCBITaxon:241407 ! Saccharomycetales incertae sedis
relationship: never_in_taxon NCBITaxon:33208 ! Metazoa
relationship: never_in_taxon NCBITaxon:451866 ! Taphrinomycotina
relationship: never_in_taxon NCBITaxon:4930 ! Saccharomyces
