### ISSUE TITLE
Query "Regulation of X process by regulation of transcription from RNA polymerase II promoter" pattern

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13166]
Hello, 

As a follow up on this issue: https://github.com/geneontology/go-ontology/issues/13137
It seems like the formulation "Regulation of X process by regulation of transcription from RNA polymerase II promoter" is incorrect, ie that the regulation of gene expression is always upstream from the process. I propose to reformulate the terms to 
"Regulation of transcription from RNA polymerase II promoter involved in process X" (I think this is really what was meant when these terms were created). This affects the following terms: 

GO:1900401 	regulation of meiosis by regulation of transcription from RNA polymerase II promoter 	
GO:1900414 	regulation of cytokinesis by regulation of transcription from RNA polymerase II promoter 	
GO:0035968 	regulation of sterol import by regulation of transcription from RNA polymerase II promoter 	
GO:1900389 	regulation of glucose import by regulation of transcription from RNA polymerase II promoter 	
GO:0035947 	regulation of gluconeogenesis by regulation of transcription from RNA polymerase II promoter 	
GO:0072367 	regulation of lipid transport by regulation of transcription from RNA polymerase II promoter 	
GO:1900400 	regulation of iron ion import by regulation of transcription from RNA polymerase II promoter 	
GO:0035958 	regulation of glyoxylate cycle by regulation of transcription from RNA polymerase II promoter 	
GO:0072361 	regulation of glycolytic process by regulation of transcription from RNA polymerase II promoter 	
GO:1900393 	regulation of iron ion transport by regulation of transcription from RNA polymerase II promoter 	
GO:0035953 	regulation of dipeptide transport by regulation of transcription from RNA polymerase II promoter 	
GO:1900545 	regulation of phenotypic switching by regulation of transcription from RNA polymerase II promoter 	
GO:0035950 	regulation of oligopeptide transport by regulation of transcription from RNA polymerase II promoter 	
GO:1900391 	regulation of cAMP-mediated signaling by regulation of transcription from RNA polymerase II promoter 	
GO:1902574 	negative regulation of leucine import by regulation of transcription from RNA polymerase II promoter 	
GO:0035956 	regulation of starch catabolic process by regulation of transcription from RNA polymerase II promoter 	
GO:1900382 	regulation of thiamine biosynthetic process by regulation of transcription from RNA polymerase II promoter 	
	
GO:1900546 	positive regulation of phenotypic switching by regulation of transcription from RNA polymerase II promoter 	
GO:1900547 	negative regulation of phenotypic switching by regulation of transcription from RNA polymerase II promoter 	
GO:0098679 	regulation of carbohydrate catabolic process by regulation of transcription from RNA polymerase II promoter 	
GO:1900374 	positive regulation of mating type switching by regulation of transcription from RNA polymerase II promoter 	
GO:1900402 	regulation of carbohydrate metabolic process by regulation of transcription from RNA polymerase II promoter 	
GO:0035960 	regulation of ergosterol biosynthetic process by regulation of transcription from RNA polymerase II promoter 	
GO:2000531 	regulation of fatty acid biosynthetic process by regulation of transcription from RNA polymerase II promoter 	
GO:1900406 	regulation of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter 	
GO:1900415 	regulation of fungal-type cell wall biogenesis by regulation of transcription from RNA polymerase II promoter 	
GO:0072364 	regulation of cellular ketone metabolic process by regulation of transcription from RNA polymerase II promoter 	
GO:1900405 	regulation of cell separation after cytokinesis by regulation of transcription from RNA polymerase II promoter 	
GO:1901718 	regulation of dipeptide transmembrane transport by regulation of transcription from RNA polymerase II promoter 	
GO:1900427 	regulation of cellular response to oxidative stress by regulation of transcription from RNA polymerase II promoter 	
GO:1900416 	regulation of 4,6-pyruvylated galactose residue biosynthetic process by regulation of transcription from RNA polymerase II promoter 	
GO:1904788 	positive regulation of induction of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter 	
GO:0061434 	regulation of replicative cell aging by regulation of transcription from RNA polymerase II promoter in response to caloric restriction 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale,

As an aside, I'm pretty sure that some of these terms should not exist.

fungal-type cell wall biogenesis and cytokinesis for example aren't regulated transcriptionally. So maybe we should get rid of these 2 terms? These are indirect effects. Clearly the transcription needs to happen but the processes are regulated post-transcriptionally.

These days, for these we would just capture the target genes for transcription (unless we know that the transcription is activating the process).

Some of these are fine, for example ergosterol metabolism and carbohydrate catabolic process appear to be directly regulated by transcription (would probably be better to do them with extensions though).

**Comment by dianeoinglis** [comment]
This list shows only the primary "regulation of x" terms and not the "positive/negative regulation of x by regulation from RNA polymerase II promoter" but would these not get the same transformation? If so, please add to the list:

GO:1900461 'positive regulation of pseudohyphal growth by positive regulation of transcription from RNA polymerase II promoter'
GO:1900462 'negative regulation of pseudohyphal growth by negative regulation of transcription from RNA polymerase II promoter'

And these two with odd/incorrect syntax/missing part may have slipped through the query:

GO:0100041 'positive regulation of pseudohyphal growth by transcription from RNA polymerase II promoter'
GO:0100042 'negative regulation of pseudohyphal growth by transcription from RNA polymerase II promoter'

Pseudohyphal growth terms are being discussed for other reasons in #13157 and #13164 that may warrant coordination.

**Comment by dianeoinglis** [comment]
Also #13167 reports a definition issue with GO:1900462

**Comment by pgaudet** [comment]
Hi @dianeoinglis 

There were a few positive and negative in the list I had, but you are right, I missed a lot of terms because I had search on 'by regulation of transcription from RNA polymerase II promoter". Now I added positive and negative in there, and here are the other terms retrieved: 


GO:0072369 	regulation of lipid transport by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900476 	positive regulation of meiosis by positive regulation of transcription from RNA polymerase II promoter 	
GO:0072363 	regulation of glycolytic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900404 	positive regulation of DNA repair by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035969 	positive regulation of sterol import by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035948 	positive regulation of gluconeogenesis by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035959 	positive regulation of glyoxylate cycle by positive regulation of transcription from RNA polymerase II promoter 	
GO:0061426 	positive regulation of sulfite transport by positive regulation of transcription from RNA polymerase II promoter 	
GO:0097301 	regulation of potassium ion concentration by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035954 	positive regulation of dipeptide transport by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900461 	positive regulation of pseudohyphal growth by positive regulation of transcription from RNA polymerase II promoter 	
GO:0061423 	positive regulation of sodium ion transport by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900478 	positive regulation of sulfate assimilation by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900423 	positive regulation of mating type switching by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035951 	positive regulation of oligopeptide transport by positive regulation of transcription from RNA polymerase II promoter 	
GO:0061424 	positive regulation of peroxisome organization by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035957 	positive regulation of starch catabolic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:0072366 	regulation of cellular ketone metabolic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:0061425 	positive regulation of ethanol catabolic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:0097235 	positive regulation of fatty acid beta-oxidation by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900375 	positive regulation of inositol biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900466 	positive regulation of arginine biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:0035961 	positive regulation of ergosterol biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1904488 	regulation of reactive oxygen species metabolic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900413 	positive regulation of phospholipid biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900448 	regulation of pyrimidine nucleotide biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900422 	positive regulation of cellular alcohol catabolic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900418 	positive regulation of purine nucleotide biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1904001 	positive regulation of pyrimidine-containing compound salvage by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900525 	positive regulation of phosphatidylserine biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:1900472 	positive regulation of phosphatidylcholine biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 	
GO:0036083 	positive regulation of unsaturated fatty acid biosynthetic process by positive regulation of transcription from RNA polymerase II promoter 


GO:1900392 	regulation of transport by negative regulation of transcription from RNA polymerase II promoter 	
GO:0072368 	regulation of lipid transport by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900475 	positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter 	
GO:0072362 	regulation of glycolytic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1990872 	negative regulation of sterol import by negative regulation of transcription from RNA polymerase II promoter 	
GO:0035949 	positive regulation of gluconeogenesis by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900387 	negative regulation of cell-cell adhesion by negative regulation of transcription from RNA polymerase II promoter 	
GO:0035955 	negative regulation of dipeptide transport by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900462 	negative regulation of pseudohyphal growth by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900474 	negative regulation of mating type switching by negative regulation of transcription from RNA polymerase II promoter 	
GO:0035952 	negative regulation of oligopeptide transport by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900417 	negative regulation of transmembrane transport by negative regulation of transcription from RNA polymerase II promoter 	
GO:0072365 	regulation of cellular ketone metabolic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1904089 	negative regulation of neuron apoptotic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900465 	negative regulation of arginine catabolic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:0061427 	negative regulation of ceramide biosynthetic process by negative regulation of transcription from RNA Polymerase II promoter 	
GO:1900471 	negative regulation of inositol biosynthetic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900463 	negative regulation of cellular response to alkaline pH by negative regulation of transcription from RNA polymerase II promoter 	
GO:1904489 	regulation of reactive oxygen species metabolic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900477 	negative regulation of G1/S transition of mitotic cell cycle by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900464 	negative regulation of cellular hyperosmotic salinity response by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900526 	negative regulation of phosphatidylserine biosynthetic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1904490 	negative regulation of mitochondrial unfolded protein response by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900403 	negative regulation of cellular amino acid biosynthetic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900473 	negative regulation of phosphatidylcholine biosynthetic process by negative regulation of transcription from RNA polymerase II promoter 	
GO:1902625 	negative regulation of induction of conjugation with cellular fusion by negative regulation of transcription from RNA polymerase II promoter 	
GO:1900460 	negative regulation of invasive growth in response to glucose limitation by negative regulation of transcription from RNA polymerase II promoter 	
GO:1902353 	positive regulation of induction of conjugation with cellular fusion by negative regulation of transcription from RNA polymerase II promoter by pheromones 

---
Pascale

**Comment by dosumis** [comment]
These two things seem to contradict each other:

> the regulation of gene expression is always upstream from the process. I propose to reformulate the terms to
> "Regulation of transcription from RNA polymerase II promoter involved in process X"

'involved in' gets translated to part_of.  Parts are **not** upstream.

**Comment by dianeoinglis** [comment]
@pgaudet, @dosumi
I disagree that regulation of gene expression is always downstream of a process as the regulated genes could occur during the course of a process or as a result of initiating a process. The term "upstream" reminds me of linear pathways with arrows drawn on a chalkboard by a college Molecular Bio professor...arcane. To say that regulation of gene expression is either "part_of" or "involved_in" process x seems appropriate and is easier to determine experimentally than upstream or downstream that may not definitively be known

**Comment by pgaudet** [comment]
Hi @dianeoinglis 
You are right, for those terms we don't always know whether the transcription occurs as *part of* the pathway or *upstream* from the pathway. I am looking at some annotations to see if they are used consistently. 

Pascale

**Comment by pgaudet** [comment]
Hello again, 

I looked at the annotations for about 30 of those terms, and they are all IMP and the greatest part were annotated by SGD. The few abstracts I looked at seemed to cover cases where either transcription factors or regulators of transcription factors are 'causally upstream or involved in' the process, but the role of the annotated protein is very indirect. 

I would be inclined to obsolete these terms because while they cover conserved processes, they are not consistently used by all groups (in fact they are NOT used by most groups). Or can anyone (SGD?) come up with rules for creating and using those terms ? 

Thanks, Pascale
[Git-13166_regulation by transcription.xlsx](https://github.com/geneontology/go-ontology/files/841948/Git-13166_regulation.by.transcription.xlsx)

**Comment by ukemi** [comment]
I just looked at my annotations. I think it would be way better to annotate in a Noctua model. The mechanism is nicely spelled out in the paper, but is lost in these single annotations that try to capture everything. Without the extended representation of the mechanism, I don't think it would hurt at all to have the gene products re-annotated to the transcription term and the regulation of glycolysis/gluconeogenesis terms separately.

**Comment by edwong57** [comment]
I have been taking a look at some of the annotations that SGD made with these terms. I agree with @ukemi. The ones that I have looked at would be better annotated in a Noctua model. I've brought this to the attention of other SGD curators, so I'll add any additional comments if there are any dissenters.

**Comment by dosumis** [comment]
Diane wrote:
> @pgaudet <https://github.com/pgaudet>, @dosumi
> I disagree that regulation of gene expression is always downstream of a process as the regulated genes could occur during the course of a process or as a result of initiating a process. The term "upstream" reminds me of linear pathways with arrows drawn on a chalkboard by a college Molecular Bio professor...arcane. To say that regulation of gene expression is either "part_of" or "involved_in" process x seems appropriate and is easier to determine experimentally than upstream or downstream that may not definitively be known

Surely that depends on the specific gene expression in question.  

David wrote:
> I just looked at my annotations. I think it would be way better to annotate in a Noctua model. The mechanism is nicely spelled out in the paper, but is lost in these single annotations that try to capture everything. Without the extended representation of the mechanism, I don't think it would hurt at all to have the gene products re-annotated to the transcription term and the regulation of glycolysis/gluconeogenesis terms separately.

If you want to say that gene expression is upstream of or within a process then, realistically, this can only be recorded in noctua or with an extended annotation, rather than with a single term.   However, there are cases of regulation which are more linear e.g. in many well-known cases in development and immunology.  In this case, the regulation of regulation pattern is correct (and inferable from the equivalent regulation chain in LEGO/noctua).  For either case, the ‘involved in’ pattern (which translates to 'part of' on the logical side) is simpy wrong.

**Comment by pgaudet** [comment]
related issue: 11583

**Comment by pgaudet** [comment]
Obsoletion notice for : "GO:0100035 negative regulation of transmembrane transport by transcription from RNA polymerase II promoter" sent June 28th 2017.

**Comment by pgaudet** [comment]
Hi all, 

I am removing 
 id: GO:1901718
-name: regulation of dipeptide transmembrane transport by regulation of transcription from RNA polymerase II promoter

 id: GO:1900417
-name: negative regulation of transmembrane transport by negative regulation of transcription from RNA polymerase II promoter

 id: GO:0100063
-name: regulation of dipeptide transmembrane transport by transcription from RNA polymerase II promoter

Does anyone want to keep any of the terms remaining in the above list ? 
@edwong57 
@ValWood 
@dianeoinglis 
? 

Thanks, Pascale

**Comment by ValWood** [comment]
nope, we'll rehouse

**Comment by pgaudet** [comment]
Closing - Redundant with #12739
