### ISSUE TITLE
Add comment to all MF regulators

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13179]
Can we add this comment, or equivalent to all terms
under GO:0098772 molecular function regulator

GO:0030234 is reserved for cases when the regulator directly interacts with the enzyme. When regulation of enzyme activity is achieved without enzyme binding, or when the mechanism of regulation is unknown, instead annotate to 'regulation of catalytic activity ; GO:0050790'.

See confusion in
https://github.com/geneontology/go-ontology/issues/12859#issuecomment-286970668

**Comment by ukemi** [comment]
@cmungall can we do this by script?

**Comment by cmungall** [comment]
I'd like to start using annotation properties other than rdfs:comment 
for this. Would that be OK?

**Comment by dosumis** [comment]
The new definition pattern should make this clear for the whole branch.

**Comment by cmungall** [comment]
@dosumis - ah yes, we should just fold directly into the design pattern. Should we do it as definition gloss?

**Comment by dosumis** [comment]
Relevant pattern:

https://github.com/geneontology/design_patterns/blob/master/validated_patterns/activator_activity.yaml#L26

**Comment by pgaudet** [comment]
@ValWood can you please have a look at the suggestion ?

**Comment by ValWood** [comment]
Sorry missed this. I think that sounds good.  Pattern should be positive/negative depending on flavour.

**Comment by pgaudet** [comment]
Can we implement this ?

**Comment by ValWood** [comment]
Is this out of date?

**Comment by pgaudet** [comment]
Yes, the updated definitions deal with this. 

Thanks, Pascale
