### ISSUE TITLE
parentage of GO:0004799 - thymidylate synthase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13174]
has parentage to 
	5,10-methylenetetrahydrofolate-dependent methyltransferase activity
that looks incorrect?

**Comment by hdrabkin** [comment]
the result of ts is a methyl group on dUMP
5,10-methylenetetrahydrofolate + dUMP ⇌ {\displaystyle \rightleftharpoons } \rightleftharpoons dihydrofolate + dTMP
so isn't ts a 5,10-methylenetetrahydrofolate dependent methyl transferase?

**Comment by hdrabkin** [comment]
It's not the only one;  Although most tRNAs have the U at position 54 methylated to ribo T with SAM, but some use THF.

**Comment by ValWood** [comment]
OK! yep
