### ISSUE TITLE
missing parent:  D-aminoacyl-tRNA deacylase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13175]
see image
![amino acid editing](https://cloud.githubusercontent.com/assets/7359272/23925575/c05a1716-0907-11e7-8e8b-d3fb5d5a5b28.jpg)

D- aminoacyl-tRNA deacylase activity is_a aminoacyl-tRNA editing activity

@hdrabkin  do these need to merge?

V

**Comment by mah11** [comment]
I can see how adding the link GO:0051499 is_a GO:0002161 would make sense, but I don't see why any terms would merge. GO:0051499 is specific for D-amino acids, whereas GO:0002161 is not.

**Comment by ValWood** [comment]
OK also there might be other mechanisms..
so just add parent...

**Comment by ValWood** [comment]
So action is

 D-aminoacyl-tRNA deacylase activity
add parent
is_a aminoacyl-tRNA editing activity

@hdrabkin

**Comment by hdrabkin** [comment]
done
