### ISSUE TITLE
mp  GO:0000451 rRNA 2'-O-methylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13176]
Add parent?

rRNA base methylation
Definition	The addition of a methyl group to an atom in the nucleoside base portion of a nucleotide residue in an rRNA molecule.

**Comment by ValWood** [comment]
GO:0000456
Name	dimethylation involved in SSU-rRNA maturation

should also have this parent

**Comment by ValWood** [comment]
and GO:0000452 - snoRNA guided rRNA 2'-O-methylation

**Comment by mah11** [comment]
Looks like GO:0000456 is_a GO:0070475 would be correct, but GO:0000451 and GO:0000452 should not have the additional parent. 2'-O-methylation modifies the sugar portion of the nucleotide residue, not the base.

**Comment by ValWood** [comment]
OK I was reading nucleotide and processing as 'base'. Maybe these could be grouped under  an appropriate "rRNA sugar methylation" term. It seems  odd to have one grouping and not the other...

**Comment by ValWood** [comment]
OK

**Comment by ValWood** [comment]
I'm still a bit confused. So is this modifying the sugar, but only when uridine is the base?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008650#term=ancchart

If  there is specificity for the sugar based on the base thats why the grouping is useful....i'm trying to figure what we have missing...
http://pombase2.aska.gen.nz/term/GO%3A0008173

**Comment by hdrabkin** [comment]
Looking through the pubs used for IDA annotations sen in quickgo:
 " named Mrm2, which is required for methylating U(2791) (PMID:11867542 

"Reverse transcriptase primer extension indicated that AviRa is an N-methyltransferase that targets G2535 within helix 91 of the rRNA, whereas  AviRb modified the 2'-O-ribose position of nucleotide U2479 within helix 89" PMID:12828631) (at least this suggests a specificity for each protein)

FtsJ is active on ribosomes and on the 50 S ribosomal subunit, but is inactive on free rRNA, suggesting that its natural substrate is ribosomes or a pre-ribosomal ribonucleoprotein particle. We identified the methylated nucleotide as 2'-O-methyluridine 2552,  PMID:10748051

I have not looked beyond the abstract, however, I don't think it's clear at all how much the secondary and tertiary structures of the RNA or in one case the RNP (ribosome) contribute to the specificity

**Comment by ValWood** [comment]
OK what I was *actually* looking for was a term for tRNA 2'-O-methyltransferase 
so I'll open a ticket for that...
We can ignore this for now...
(I'll assign it to you Harold;)
