### ISSUE TITLE
ntr 	tRNA 2'-O-methyltransferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13185]
I could only find
tRNA (guanosine-2'-O-)-methyltransferase activity

child of
GO:0008171 O-methyltransferase activity
GO:0008175 tRNA methyltransferase activity

http://www.yeastgenome.org/reference/S000120470/overview
(I'm annotating the ortholog)

**Comment by ValWood** [comment]
would use for Trm7 too, 
http://www.yeastgenome.org/locus/S000000265/overview

**Comment by hdrabkin** [comment]
I know there is 2'-O-methylcytidine  (Cm), as well as Um, and Am, but not sure at the moment if there are individual proteins responsible.  Hope to find what I'm looking for here: Front. Genet., 23 May 2014 | https://doi.org/10.3389/fgene.2014.00144

**Comment by hdrabkin** [comment]
Done

**Comment by ValWood** [comment]
Thanks Harold.

tRNA (guanosine-2'-O-)-methyltransferase activity  
should be a descendant?

**Comment by hdrabkin** [comment]
yes, that's what I intend.
I will also request an EC number from EC to be issued for it.

**Comment by ukemi** [comment]
tRNA 2\'-O-methyltransferase should work.

**Comment by ukemi** [comment]
Argh add a backslash before the prime.

**Comment by hdrabkin** [comment]
keeping this PG
done
