### ISSUE TITLE
OTR: intercellular bridge - extracellular region?

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13181]
GO:0045171 intercellular bridge Is_a  GO:0044421 extracellular region part

Should intercellular bridge be classed as part of the extracellular region? The plasma membrane and cytosol is continuous between adjacent cells, so it's not really extracellular as defined. I think it would sit better under:  GO:0044464 cell part

**Comment by krchristie** [comment]
@hattrill I agree it doesn't seem like it should be extracellular. I was wondering if you think it would be appropriate to consider this a type of 'cell projection'

**Comment by dosumis** [comment]
> I was wondering if you think it would be appropriate to consider this a type of 'cell projection'

cell projections are extensions of cell enclosed in PM (e.g. axon; cilium). Don't think this fits.

**Comment by krchristie** [comment]
There should NOT be a requirement for a cell project to be enclosed in PM. Bacterial and archaeal flagella are not enclosed in PM.

**Comment by hattrill** [comment]
I can't see any specific requirement for a PM component for projection and I can see how the would fit under this. However, I think that most/all intercellular bridges arise from incomplete cytokinesis rather than growing out from the cell itself as the other projections. 
Similarly, I guess they could be classed as a type of cell junction - although they lack specific TM bridging proteins and they are quite a bit larger than the classic cellular junction, so I'm not so sure about this either.

**Comment by dosumis** [comment]
I stand corrected.  I can see that this class does cover bacterial flagella. However, this makes the grouping rather uselessly abstract: Grouping gene products to “thing sticking out of cell” is not likely to be biologically informative, so I’d suggest we do need a class for PM enclosed cell projections.  

Anyway I think it would be stretching the definition of cell projection even further to put intracellular bridge under it.  Perhaps we should have a general class for structures that have parts in two cells?  Could cover gap junctions, tight junctions & things like ‘trans-synaptic complexes’ as well as intercellular bridges.

Maybe 'Intercellular component’?  The relationship to each of the cells involved is ‘overlaps’.

**Comment by dosumis** [comment]
intercellular component
.    <- is_a cell-cell junction
.    <- is_a intercellular bridge

**Comment by hattrill** [comment]
Yes, I like that solution!

**Comment by krchristie** [comment]
I like this solution too and we already have some terms for this too:
<pre>
- cell junction
-- anchoring junction
-- cell-cell junction
-- cell-substrate junction</pre>

However, here are the defs for two of them:

**cell junction**
Def: A cellular component that forms a specialized region of connection between two or more cells or between a cell and the extracellular matrix. At a cell junction, anchoring proteins extend through the plasma membrane to link cytoskeletal proteins in one cell to cytoskeletal proteins in neighboring cells or to proteins in the extracellular matrix.

**cell-cell junction**
Def: A cell junction that forms a connection between two or more cells in a multicellular organism; excludes direct cytoplasmic junctions such as ring canals.

However, these defs lead to some other problems, specifically that the 'cell-cell junction' term that seems like it should be the appropriate parent specifically excludes ring canals, though I don't understand why. @mah11 Do you have any recollection of why ring canals are excluded here?  

The paper that is used for the def dbxref for 'intercellular bridge' calls them 'ring canals' (**PMID:9635420**):
<pre>One of the many ways cells can communicate with one another is through intercellular 
bridges that directly link the cytoplasms of sister cells (Robinson and Cooley, 1996). The 
occurrence of intercellular cytoplasmic bridges is best documented in the germline of both males 
and females in species ranging from fruit flies to humans.  Germline intercellular bridges facilitate 
the passage of cytoplasmic components between cells during development. Intercellular 
bridges have also been found con- necting somatic cells; however, the function of somatic 
bridges is not known, nor is the prevalence of somatic bridges established.

During egg development in Drosophila, the maternal contribution to each oocyte is supplied 
largely by 15 nurse cells that are connected to each other and the oocyte by intercellular bridges 
called ring canals.</pre>

I also wonder if the term 'cell junction' needs to be broad enough to cover the connections between bacterial cells when they conjugate... (can't remember Jim Hu's github ID to tag him)

**Comment by mah11** [comment]
> @mah11 Do you have any recollection of why ring canals are excluded here?

It was a LONG time ago that I worked on any of the cell junction terms. With that caveat, I don't remember any specific reasons for excluding ring canals. I think we were concentrating on the types of junctions that are associated with cytoskeletal structures, but if there were reasons to limit the most general "cell junction" term to them they're not in my head any more. (I don't even know enough about ring canals to be sure they lack "anchoring proteins [that] plasma membrane to link cytoskeletal proteins in one cell to cytoskeletal proteins in neighboring cells".)

**Comment by hattrill** [comment]
@pgaudet can we bump this up the issues to get it resolved?

Thanks!

**Comment by pgaudet** [comment]
HI @krchristie 

It looks like the decision has been made here to create a new term 'intercellular component' and move 'intercellular bridge' under it. 
I dont think the definition of the sibling terms matter for this to be implemented. Or is there another unresolved issue? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Removed the part_of extracellular. 

Intercellular bridge is now is_a 'cellular anatomical entity'


Thanks, Pascale
