### ISSUE TITLE
GO:0070937 CRD-mediated mRNA stability complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13180]
Please add the following amendments:

- Def:
A protein complex that binds to, and promotes stabilization of, mRNA molecules containing the coding region instability determinant (CRD). In human, IGF2BP1 and at least four additional proteins: HNRNPU, SYNCRIP, YBX1, and DHX9. 
+ Def:
A protein complex that binds to, and promotes stabilization of, mRNA molecules containing the coding region instability determinant (CRD). In human, it may consist of IGF2BP1, HNRNPU, SYNCRIP/HNRNPQ, YBX1, and DHX9. 

Rational: many mRNA transcripts have a CRD but the binding complexes have not been identified for all so may differ. See #13170 for an alternative complex on a the related **major** CRD.

Synonyms:
coding-region determinant of instability-mediated mRNA stability complex [EXACT]
coding-region instability determinant -mediated mRNA stability complex [EXACT]

Rational: They can't decide whether they call it "determinant of instability" or "instability determinant"!

Thanks,
Birgit

**Comment by hdrabkin** [comment]
oops; @pgaudet,  I did this with another related ticket. Sorry

**Comment by hdrabkin** [comment]
I added the syns but changed the def back because there are 22 non IEA annotations in quickgo that may need to be looked at to see if proposed def renders any of them incorrect.

**Comment by bmeldal** [comment]
I would have thought the new def makes it more generic, not narrower.

**Comment by hdrabkin** [comment]
Still, we need to check when changing a def. Many are ISS based on a GO_Ref, ; 5 are IDAs; 
 I am attaching the file if you want to look; But they are to the proteins you mention, so most likely this will be fine. I'll push this tomorrow when I feel more comfortable. 
[gene_association.goa.txt](https://github.com/geneontology/go-ontology/files/848928/gene_association.goa.txt)

**Comment by hdrabkin** [comment]
CSDE1 is the one I will check, as it's not one of  IGF2BP1, HNRNPU, SYNCRIP/HNRNPQ, YBX1, or DHX9.

**Comment by hdrabkin** [comment]
I thinking that the annotation for CSDE1 using PMID:15314026 might actually be a binding annotation to mCRD GO:0106002, and not suggesting it is a member with a cc annotation. It's more likely a complex binding annotation with mCRD (GO term) as input. The def change will not effect my concerns about that. So I will go ahead and change the wording of the def as you suggest.

**Comment by bmeldal** [comment]
Thanks, Harold.

**Comment by hdrabkin** [comment]
Done; closed

**Comment by bmeldal** [comment]
NB: CSDE1 is part of the related mCRD~ complex so yes, it probably is just an interactor with the CRD dep on circumstances :)
