### ISSUE TITLE
Automate generation of import modules

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13205]
See #13187 

Currently this has to be manually executed. Previously we did this via jenkins, and has jenkins configured to svn commit the results back. This is a bit more complicated now - first we have to configure jenkins to authenticate with github, then we have to decide if we want to do this on a branch, etc.

The actual steps are simple:

```
cd src/ontology
make all_imports
```

one workflow would be the one-time creation of a branch

```
git checkout -b import-regen
```

```
git pull
git checkout import-regen
git merge master
cd src/ontology
make all_imports
git commit -m 'regenerated' imports/
git push origin import-regen
```

This can be run by anyone with owltools and robot on the command line

**Comment by cmungall** [comment]
OK - this is probably simplest: We have a regular jenkins job, but it doesn't commit. An editor will grab the import_foo.owl from jenkins and commit. While the manual step is not ideal, it does give the editors control over when to bring in new versions of external ontologies.

**Comment by dosumis** [comment]
Is it possible to specify a new imported by just declaring the bare URI as a class in go-edit.obo ? (easy to do in Protege).

**Comment by cmungall** [comment]
You can do this, or you can put the term in imports/FOO_terms.txt, either way works.

**Comment by cmungall** [comment]
OK, the existing build-go-ontology job will regenerate import modules and place them here:

https://build.berkeleybop.org/job/build-go-ontology/lastSuccessfulBuild/artifact/target/imports/

So a procedure that would work right now is:

 * add to imports/FOO_terms.txt
 * commit, merge to master
 * wait ~20 mins for job to finish
 * start a new branch for the actual work you want to do
 * copy the import_foo.owl file on top of the old one
 * add your axiom referencing the new class
 * commit and proceed as normal

This does not require setup of tools on command line. If this is frequent then editors will want to be able to regenerate themselves

TBD tomorrow

**Comment by pgaudet** [comment]
@cmungall Can we make this high priority ?

**Comment by cmungall** [comment]
@dougli1sqrd will show how to do this. It should be under editor control. Easy to do with docker installed

**Comment by ukemi** [comment]
But last I checked, the docker pull request had failed the checks and was tagged as do not merge. See #15266. If this is going to be the responsibility of the editors, we need complete documentation on how it's done, what to install etc.

**Comment by ukemi** [comment]
I also think this one is out of date. @balhoff?

**Comment by balhoff** [comment]
Yes!
