### ISSUE TITLE
NTR: host cell uropod

### ISSUE THREAD

**Issue by sarahkcouv** [geneontology/go-ontology#13201]
Name: Host cell uropod
Definition: A membrane projection of the host cell with related cytoskeletal components at the trailing edge of a cell in the process of migrating or being activated, found on the opposite side of the cell from the leading edge or immunological synapse, respectively.
Aspect: 
Cellular component
Relationships: 
is_a  GO:0044157 host cell projection
Reference: 
PMID: 24965475
Synonyms:
exact: host cell uropodium 
Notes: 
I am a CACAO student and I based this off of GO:0001931 uropod

**Comment by krchristie** [comment]
@ukemi - I wanted to check on this request with you.

Currently we have 

<pre>
- host cell projection
-- host cell filopodium</pre>

<pre>
- cell projection
-- plasma membrane bounded cell projection
--- actin-based cell projection
---- filopodium
--- uropod
.... (only selected terms shown)
</pre>

where 
- 'host cell filopodium' is currently the only child term of 'host cell projection.
- the 'host cell projection' terms have no connection to the 'cell projection' branch that is not part of host cell'. 
-- **Should there be a connection?** It seems like a 'host cell projection' would be a type of 'cell projection' (nevermind the fact that the specific host cell projections currently present (filopodium) or proposed (uropod) have been moved to the new PM bounded cell projection term).

Also, if CACAO is able to do extensions, would there be some way to annotate to the existing term 'host cell projection' and use the existing term 'uropod' in the extension?

**Comment by ukemi** [comment]
If you look at all the host cell terms you will not see relations to the separate individual structures. If I recall correctly, this is because it creates issues as we follow annotations in the graph, confusing from which organism the gene product is derived. You should follow the patterns that are currently in place.

**Comment by krchristie** [comment]
so it's OK to create this term?

**Comment by krchristie** [comment]
Oh, another question. Now that we've made "plasma membrane bounded cell projection', should I duplicate that structure under 'host cell projection' since both the existing and proposed child terms are PM bound cell projections?

**Comment by ukemi** [comment]
For now since we have gone this route, I guess it is ok to make the term. I don't think we want to add in all the possible terms. It would result in the entire recapitulation of the cellular component graph under host cell. There has got to be a better way to do this in Noctua.

**Comment by krchristie** [comment]
OK, I'll add it.

I agree. It seems like indicating that the relevant cell is a host cell, rather than a cell that produced the gene product, should be handled at the annotation level, not at the ontology level.

**Comment by krchristie** [comment]
New term:

 [Term]
+id: GO:0120026
+name: host cell uropod
+namespace: cellular_component
+def: "A host cell membrane projection with related cytoskeletal components at the trailing edge of a cell in the process of migrating or being activated, found on the opposite side of the cell from the leading edge or immunological synapse, respectively." []
+synonym: "host cell uropodium" EXACT []
+is_a: GO:0044157 ! host cell projection
+created_by: kchris
+creation_date: 2017-03-22T21:33:31Z
+

**Comment by dosumis** [comment]
> For now since we have gone this route, I guess it is ok to make the term. I don't think we want to add in all the possible terms. It would result in the entire recapitulation of the cellular component graph under host cell. There has got to be a better way to do this in Noctua.

I agree this is completely unsustainable.  I have a long standing proposal for how to do this compositionally in extensions / LEGO.  It involves explicitly referring to different organisms involved and their relationships to each other and uses a different qualifier (GP-CC relation) for the annotations, allowing them to be filtered and so getting round the problem if grouping under canonical cell anatomy.   Ultimately this branch should be obsoleted and replaced by the compositional approach. I'll dig the proposal and we can discuss on an editor's call.
