### ISSUE TITLE
MP: regulation of G2/M transition of mitotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13218]
GO:0010389 regulation of G2/M transition of mitotic cell cycle

I spotted recently that this has no relationship to "regulation of mitosis (proper), a.k.a "regulation of mitotic nuclear division"

Was waiting for @pgaudet  to finish edits in this area so the parentage could be added to the NEW term.

**Comment by ValWood** [comment]
also add "regulation of mitotic entry" as a synonym of  GO:0010389 regulation of G2/M transition of mitotic cell cycle, will be helpful for "ordering"

**Comment by pgaudet** [comment]
Hi Val, 

Shouldn't we rather say that 'G2/M transition of mitotic cell cycle' regulates 'mitotic nuclear division'? Instead of the regulation regulates the downstream process ? 

Thanks, Pascale

**Comment by ValWood** [comment]
> Shouldn't we rather say that 'G2/M transition of mitotic cell cycle' regulates 'mitotic nuclear division'? Instead of the regulation regulates the downstream process ?

Yes I think you are right.

**Comment by pgaudet** [comment]
Hi @ukemi ! 

So I think I am asking to add a subclass 
regulates some 'mitotic nuclear division'

Is this allowed? 

Thanks, Pascale
(note to self: local branch issue-13218-2)

**Comment by ukemi** [comment]
This makes sense and it is allowed. So when the reasoner runs, this will become a subtype of 'regulation of mitotic nuclear division'.  But does it really regulate it, or is it just required upstream?

**Comment by ValWood** [comment]
It regulates entry into. G2/M (phase) transition is  often called "entry into mitosis" .

**Comment by ukemi** [comment]
So in that case, is it positive regulation?

**Comment by pgaudet** [comment]
I would think so. @ValWood ?

**Comment by ValWood** [comment]
yep.

**Comment by ValWood** [comment]
Hi,

I don't think this is quite right.

Currently we have
positive regulation of mitotic cell cycle
--G2/M transition of mitotic cell cycle

but the G2/M transition includes positive and negative regulation.

negative regulation og the G2/M transition= mitotic delay.

Therefore I think it should be

regulation of mitotic nuclear division
--regulation of G2/M transition

positive regulation of mitotic nuclear division
--positive regulation of G2/M transition

negative regulation of mitotic nuclear division
--negative regulation of G2/M transition

**Comment by pgaudet** [comment]
Hi @ValWood 

One question: The 'G2/M transition of mitotic cell cycle' should not be part of any regulation of the cell cycle then? Or should it be part of 'regulation of mitotic cell cycle' rather than of 'positive regulation of mitotic cell cycle'?

**Comment by ValWood** [comment]
I have never been convinced that  "G2/M transition of mitotic cell cycle" should be a term.
The transition itself is a "point"...like a mini phase... It doesn't actually do anything. I have them flagged locally as not for direct annotation, and have never needed them for anything... I don't know what we would annotate to it directly. the cell cycle control network is a regulatory network. The only thing which could be annotated to the transition itself is cdk1 which is the "switch", but this is more like a molecular function.
We talked about it a lot at the cell cycle workshop and its one of the parts I'm still not happy with the resolution.

I'm working on this area at the moment preparing my presentation for the pombe meeting, and have been chatting a lot with Jacky Hayles, our cell cycle expert shortly about how they think about this regulation... they had a discussion about it at the recent Nurse lab retreat. I will know more when I have this feedback. So yes, this is an outstanding issue.

In the meantime the above fixes will be useful as the the TPVs misannotations 
one  the pages I want to display (where  checkpoint proteins appear unexpectedly as positive regulators of mitosis).

**Comment by ValWood** [comment]
closing because, unsure of the effects from the positve and negative regulators. Revisit later
