### ISSUE TITLE
Travis checks failing

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#13213]
The Travis checks appear to be failing for reasons other than ontology editing errors. Should we continue to edit and merge? I fear that mistakes will trickle through if we do. We can have a look together at tomorrow's meeting.

**Comment by krchristie** [comment]
@ukemi - Shouldn't this be put on the call for the 24th, rather than last week's one?

**Comment by ukemi** [comment]
Forgot to change the column name.
