### ISSUE TITLE
Specific gene products

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13219]
Hello,

The following terms should be obsoleted or merged into their parent because they refer to specific gene products: 

GO ID	Term
GO:0010531	activation of JAK1 kinase activity 
GO:0010532	regulation of activation of JAK1 kinase activity
GO:0010534	regulation of activation of JAK2 kinase activity
GO:0010535	positive regulation of activation of JAK2 kinase activity
GO:0010537	positive regulation of activation of JAK1 kinase activity
GO:0039565	suppression by virus of host STAT1 activity by positive regulation of STAT1 catabolic process
GO:0039568	suppression by virus of host STAT1 activity by inhibition of DNA binding
GO:0039571	suppression by virus of host STAT1 activity by negative regulation of STAT1 tyrosine phosphorylation
GO:0039572	suppression by virus of host STAT2 activity by negative regulation of STAT2 tyrosine phosphorylation  
GO:0039577	suppression by virus of host JAK1 activity by negative regulation of JAK1 phosphorylation
GO:0042502	tyrosine phosphorylation of Stat2 protein
GO:0042503	tyrosine phosphorylation of Stat3 protein
GO:0042504	tyrosine phosphorylation of Stat4 protein
GO:0042505	tyrosine phosphorylation of Stat6 protein
GO:0042506	tyrosine phosphorylation of Stat5 protein
GO:0042507	tyrosine phosphorylation of Stat7 protein
GO:0042508	tyrosine phosphorylation of Stat1 protein
GO:0042510	regulation of tyrosine phosphorylation of Stat1 protein 
GO:0042511	positive regulation of tyrosine phosphorylation of Stat1 protein
GO:0042512	negative regulation of tyrosine phosphorylation of Stat1 protein
GO:0042513	regulation of tyrosine phosphorylation of Stat2 protein 
GO:0042514	negative regulation of tyrosine phosphorylation of Stat2 protein
GO:0042515	positive regulation of tyrosine phosphorylation of Stat2 protein
GO:0042516	regulation of tyrosine phosphorylation of Stat3 protein 
GO:0042517	positive regulation of tyrosine phosphorylation of Stat3 protein
GO:0042518	negative regulation of tyrosine phosphorylation of Stat3 protein
GO:0042519	regulation of tyrosine phosphorylation of Stat4 protein 
GO:0042520	positive regulation of tyrosine phosphorylation of Stat4 protein
GO:0042521	negative regulation of tyrosine phosphorylation of Stat4 protein
GO:0042522	regulation of tyrosine phosphorylation of Stat5 protein 
GO:0042523	positive regulation of tyrosine phosphorylation of Stat5 protein
GO:0042524	negative regulation of tyrosine phosphorylation of Stat5 protein
GO:0042525	regulation of tyrosine phosphorylation of Stat6 protein 
GO:0042526	positive regulation of tyrosine phosphorylation of Stat6 protein
GO:0042527	negative regulation of tyrosine phosphorylation of Stat6 protein
GO:0042528	regulation of tyrosine phosphorylation of Stat7 protein 
GO:0042529	positive regulation of tyrosine phosphorylation of Stat7 protein
GO:0042530	negative regulation of tyrosine phosphorylation of Stat7 protein
GO:0042977	activation of JAK2 kinase activity   
GO:1902569	negative regulation of activation of JAK2 kinase activity 

see also https://github.com/geneontology/go-ontology/issues/12419

**Comment by ukemi** [comment]
Agreed. We need to remind people of the policy not to request terms that refer to specific gene products. In this case the gene products are the objects of the terms, but I think it is a good idea that we follow the 'no gene product' rule consistently.

**Comment by pgaudet** [comment]
See attached document for list of replacements for these terms, and all individual annotations if people want to go back and add 'has_input' information. 

Thanks, 
Pascale
[stats_annotations.xlsx](https://github.com/geneontology/go-ontology/files/872134/stats_annotations.xlsx)

**Comment by pgaudet** [comment]
sent email to go-discuss

**Comment by ValWood** [comment]
+1 would be really great to get rid of these. It confuses curators when to request terms (especially community curators)
