### ISSUE TITLE
GO:0000991 - transcription factor activity, core RNA polymerase II binding F-P link

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13222]
This term has F-P link to 
GO:0006357 - regulation of transcription from RNA polymerase II promoter

I think this link is relatively new, and I'm not sure that it is always true?

(associations include TFIIA, TFIID, TFIIH, TFIIS)

Is everything which binds PolII as part of initiation of transcription a  regulator, even if it is required for transcription?

**Comment by krchristie** [comment]
I doubt this relationship is new. During the transcription overhaul, @ukemi and I discussed this extensively and requested input specifically on this type of question using TFIIIC as our test case.

We decided that all of these transcription factors are both a part_of the mechanism of transcription and also intrinsically regulating the process of transcription, so to explicitly answer your question, Yes.

**Comment by ValWood** [comment]
2015-05-19	Deleted	RELATION	part of GO:0006366 (transcription from RNA polymerase II promoter)
2014-08-20	Added	RELATION	part of GO:0006357 (regulation of transcription from RNA polymerase II promoter)

but based on what you say above, it should have both?

**Comment by krchristie** [comment]
My memory is that the original intention was for these types of MF terms for txn factors to have part_of links both the the 'transcription' terms and to the 'regulation of transcription' terms, so yes, I think it should have both of these relationships.

Where have you gotten the history info regarding the dates of addition and deletion of these relationships?

**Comment by ValWood** [comment]
there is a "change log" quickGO tab:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000991#term=history

**Comment by ValWood** [comment]
Out of date. The "regulation" link I was objecting to is no longer there.
