### ISSUE TITLE
'response to virus' is_a 'viral process' is incorrect

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#13233]
This is being inferred because viral process is defined as a 'multi-organism process' that has_participant some virus. 'Response to virus' is asserted to be a 'response to other organism' and 'response to stimulus' that has_input some virus. I don't think the logical definition of 'viral process' is necessary and sufficient. If we make it 'symbiosis, encompassing mutualism through parasitism' that has_participant some virus, I think that will work.

**Comment by ukemi** [comment]
Hmm. Looking at the textual definition of viral process: A multi-organism process in which a virus is a participant. The other participant is the host. Includes infection of a host cell, replication of the viral genome, and assembly of progeny virus particles. In some cases the viral genetic material may integrate into the host genome and only subsequently, under particular circumstances, 'complete' its life cycle. 

It looks as though 'response to virus' would fit this definition.

**Comment by pgaudet** [comment]
Fixed when I fixed https://github.com/geneontology/go-ontology/issues/13467
