### ISSUE TITLE
Meiosis /mitosis issues - place holder

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13232]
Leftover issues from Val from 
https://github.com/geneontology/go-ontology/issues/11709

(from @ValWood )

I  had a look, and I think there is a fairly simple strategy to fix these:
- [ ] 1. Rename
  “meiosis I” to
  “meiosis I nuclear division”
  to clarify
** ADDED SYNONYMS** 

- [x] 2.  meiotic G2/MI transition
replaced by
https://github.com/geneontology/go-ontology/issues/13246

  Definition  The cell cycle process in which a cell progresses from meiotic prophase to metaphase I. 
**EMAILED CURATORS ABOUT THESE ANNOTATIONS** 
This appears to be incorrectly defined?
G2/M is not equivalent to prophase/metaphase i
If it does refer to G2/M it should not have the “meiosis I parent  but only the meiotic cell cycle which was added  24-4-2015
(Moving this would not be a problem as the new parent is broader, but the  because of incorrect def may require absolution)

- [ ] 3. Male meiosis I and female meiosis 1 should be OK to move to the correct parent
  GO:1903046 meiotic cell cycle process
  (this is broader, so all annotations here will be OK)
  and rename to 
  male meiotic cell cycle
  and
  female meiotic cell cycle
**THESE LOOK OK***

- [ ] 4. “regulation of meiosis I”
  Is defined as “regulation of meiotic cell cycle process”
  It has only 42 EXP annotations, and most of these are to regulation kids which would live correctly under 
  “regulation of meiosis I (nuclear division)” if it was defined to match  its parent
  So, really the only the small number of  annotations directly to the existing regulation terms need to be addressed.

**ADDED SYNONYMS** 

 “regulation meiosis I” ->     “regulation of meiosis I nuclear division” 
 “positive regulation meiosis I” ->     “positive regulation of meiosis I nuclear division” 

I can run through these with you if you like. Some might even be in open tickets...

**Comment by ValWood** [comment]
- [ ]  also meiosis II cytokinesis

**Comment by pgaudet** [comment]
Added synonyms
“meiosis I” ->     “meiosis I nuclear division” 
"meiosis II" ->  “meiosis II nuclear division”
male meiosis -> meiotic nuclear division (male meiosis = related synonym)
"female meiosis I" -> "female meiosis I nuclear division” *11 EXP*
"male meiosis I" -> "male meiosis I nuclear division”
"achiasmate meiosis I" -> "achiasmate meiosis I nuclear division”
"female meiosis II" -> "female meiosis II nuclear division”
"male meiosis II" -> "male meiosis II nuclear division”
