### ISSUE TITLE
Typo - GO:0120008

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#13238]
There's a superfluous space in the label of GO:0120008:
"positive  regulation of glutamatergic neuron differentiation"

Should be:
"positive regulation of glutamatergic neuron differentiation"

**Comment by ukemi** [comment]
Fixed. Thanks @tonysawfordebi

**Comment by cmungall** [comment]
Huh, the latest checks we added should be flagging these. Need to investigate.
