### ISSUE TITLE
adding GOC db xrefs to 4 terms - easy

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#13231]
Hi,
Can you please add the GOC:BHF_telomere to these terms:

GO:1904356 regulation of telomere maintenance via telomere lengthening
GO:1904357 negative regulation of telomere maintenance via telomere lengthening
GO:1904358 positive regulation of telomere maintenance via telomere lengthening
GO:1990572 TERT-RMRP complex

I forgot to add when the terms were first created. Thanks

**Comment by hdrabkin** [comment]
Done
