### ISSUE TITLE
male and female meiosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13248]
As part of the work to differentiate correctly between the different usage of meiosis  (meiotic nuclear division vs meiotic cell cycle)

we were unsure which terse terms refer to:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007140#term=children
and descendants

GO:0007143 female meiotic division

The female term is already placed under  "meiotic nuclear division"

Most of the annotated genes   are general meiosis or meiotic cell cycle terms and we   
wondered if they would be more appropriate annotated to the parent term (i.e merged)
with a " sperm cell" extension?
I guess it depends if you have annotations which really are spexific for the male or female meiosis.

I'm tagging @hattrill  for a first input as ~170 of the >200  EXP annotations are FlyBase.

So the questions:
1) are these terms required?
2) if so do they refer to the nuclear division, of the meiotic cell cycle generally?

**Comment by ValWood** [comment]
Alternatively if you can let us know  if you still require the term, if this term refers to meiotic nuclear division, or the meiotic cell cycle generally

note that the female term name was changed from "female meiosis" to
	female meiotic division 2014-05-10
but the male term was not. Both terms probably require some review.

**Comment by pgaudet** [comment]
Hello, 

Can flybase @hattrill 
TAIR @tberardini 
wormbase @vanaukenk 
UniProt @ ? 
MGI @ukemi 

Check their direct annotations to 'GO:0007143 female meiotic division' to see if we can rename 'female meiotic *nuclear* division'? I checked the annotations of CACAO and GR (and a few others), it seems OK. 

I'd like to do this this week. Let me know if you need more time. 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
I agree for consistency with mitosis
Although we should wondering whether it is still nuclear when the nuclear envelope has disappeared
Apart form that, the change is fine

**Comment by hattrill** [comment]
I am fine with the change.

**Comment by vanaukenk** [comment]
@pgaudet -  I am fine with the change, as well, but am updating some of the annotations we had to the term.  Thx.

**Comment by ukemi** [comment]
@pgaudet - I just went through the annotations made by the MGI curators. We are good to go.

**Comment by tberardini** [comment]
@pgaudet : The Arabidopsis annotations to 'female meiotic division' will still be correct if the term is renamed to 'female meiotic nuclear division'.

**Comment by pgaudet** [comment]
Also added logical definitions: 
*female meiotic nuclear division*
'nuclear division'
 and ('part of' some 'meiotic cell cycle')
 and ('part of' some 'female gamete generation')

*male meiotic nuclear division*
'nuclear division'
 and ('part of' some 'meiotic cell cycle')
 and ('part of' some 'male gamete generation')
