### ISSUE TITLE
Merge  GO:0007098 	centrosome cycle  and GO:0051297 	centrosome organization 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13247]
These two terms have similar definitions and essentially the same children; however GO:0007098 	centrosome cycle is a child of GO:0051297 	centrosome organization. The former should be merged into the latter. 

 GO:0051298 	centrosome duplication
 GO:0010457 	centriole-centriole cohesion
 GO:0051299 	centrosome separation
 GO:0007099 	centriole replication
 GO:0061511 	centriole elongation

See also 
https://en.wikipedia.org/wiki/Centrosome_cycle

Thanks, Pascale

**Comment by krchristie** [comment]
Hi @pgaudet 

I'd like to take a look at this before you do anything since centrosomes also cycle into a role as the basal body in ciliated cells, but I won't have time until later in the week when Biocuration is over.  

@paolaroncaglia - wanted to alert you to this, though I realize you might not have any bandwidth for ontology stuff right now.

thanks,

Karen

**Comment by ValWood** [comment]
I don't think merging these terms changes anything.
the term used  for "spindle pole body cycle" term is "spindle pole body organization"
The organization of these macromolecules happens to be sell cycle dependent but this can be accommodated by the definition.

To corroborate,  centrosome cycle, is a child of centrosome organization, but these 2 terms have identical children (there is no additional sibling to indicate the need for a separate term)

The equivalent spindle term appears to have been obsoleted back in 2015
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030471

**Comment by paolaroncaglia** [comment]
@krchristie 
Thanks - as you said, no bandwidth for ontology tickets at the moment I'm afraid.

**Comment by krchristie** [comment]
I don't have any objection to merging 'centrosome cycle' into 'centrosome organization'. 

Thanks for giving me the time to check that this would not affect any of the terms for de novo centriole assembly that occur when new centrioles are assembled in order to build multiple cilia in a cell.

**Comment by pgaudet** [comment]
Hello, 

The merge is easy but I am unsure about the subclasses. Right now all the steps (centrosome duplication, centrosome separation) are is_a centrosome cycle. I moved all these to 'cell cycle process'. No objections ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Sounds OK...mirrors SPB organization.
v

**Comment by krchristie** [comment]
No objection to having these terms in cell cycle. Even though these centrioles are also sometimes ciliary basal bodies; while cells are cycling in this way, the production of cilia is also coordinated by the cell cycle using basal bodies generated in this way.
