### ISSUE TITLE
problem with GO:0008315 meiotic G2/MI transition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13246]
GO:0008315 meiotic G2/MI transition
The cell cycle process in which a cell progresses from meiotic prophase to metaphase I. 

After discussion, we think that this term should have def revised to
The cell cycle process in which a cell progresses from meiotic G2 phase to ~~prophase~~ M phase of meiosis I. 

The PMID has a typo, it should be
PMID:15084480

@pgaudet 
@mah11 
@Antonialock 

Please could you check your annotations if you used this term to see if this is what you mean?

@hattrill  (2)
@srengel  (2)
@mcourtot UniProt (4), or assign to appropriate person.

Thanks

Val

**Comment by ValWood** [comment]
Note, I should add that the term was created in 2001, but the (incorrect) def was not added until 2004.

**Comment by mah11** [comment]
corrected recommendation for def ... er, correction

**Comment by hattrill** [comment]
Removed my two - phenotypic.

**Comment by robnash** [comment]
Hi,

We were asked to comment at SGD. I most commonly see the phases of meiosis I refered to as Prophase I, Metaphase I, Anaphase I, and Telophase I. However, in the article that you include they refer to "meiotic prophase to metaphase I (G2/MI)" so it looks like they synonymize prophase I and G2. So as long as there are appropriate synonyms I think it is okay.

Cheers,
Rob

**Comment by pgaudet** [comment]
For info: The annotations to this term are: 
DB	ID	Symbol	Qualifier	GO ID	GO Name	Aspect	Evidence	Reference	With	Taxon	Date	Source	Splice
* UniProtKB	P24868	CLB1	-	GO:0008315	meiotic G2/MI transition	Process	IEP	PMID:8455600	-	559292	20010118	SGD	-
* UniProtKB	P24868	CLB1	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:8455600	-	559292	20010118	SGD	-
* UniProtKB	Q24207	bol	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:8657280	-	7227	20070910	UniProt	-
* UniProtKB	Q9PU13	spdya-a	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:10465793	-	8355	20060424	UniProt	-
* UniProtKB	Q9YGL1	spdya-b	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:10202150	-	8355	20060424	UniProt	-
* UniProtKB	Q9YGL1	spdya-b	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:10465793	-	8355	20060424	UniProt	-
* UniProtKB	Q8T4F9	eIF4G2	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:17611222	-	7227	20081204	FlyBase	-> DELETED 03.2017
* UniProtKB	Q9VCH1	eIF4G2	-	GO:0008315	meiotic G2/MI transition	Process	IMP	PMID:17611222	-	7227	20081204	FlyBase	-> DELETED 03.2017

**Comment by pgaudet** [comment]
See https://johnnydissidence.wordpress.com/tag/mitosis/ for a nice diagram

**Comment by mah11** [comment]
> in the article that you include they refer to "meiotic prophase to metaphase I (G2/MI)" so it looks like they synonymize prophase I and G2

Yes, but I think this is a mistake on their part, and so not a good basis for GO synonyms - prophase I is part of M phase of meiosis I, not the preceding G2.
