### ISSUE TITLE
GO:1902593 single-organism nuclear import

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13255]
"GO:1902593 single-organism nuclear import"
The process of nucleocytoplasmic transport is always a single organism process.

This seems to be to handle
GO:0075732 viral penetration into host nucleus 
This isn't nucleocytoplasmic transport ?

There is  a single annotation to this term 
http://www.uniprot.org/uniprot/Q9PZT0 but it is propagated to
 63,387 proteins 

I'm not sure how this annotation came from this paper, becasue this is a viral capsid protein. The paper doesn't appear to be about the transport process.

This paper talks about "disruption of the nuclear envelope".
and even says "Moreover, the mechanisms by which parvoviruses enter the nucleus remain unclear"
This isn't "nucleocytoplasmic transport".

Maybe we should extend the defintion of nucleocytoplasmic transport

from
The directed movement of molecules between the nucleus and the cytoplasm.

to
The directed movement of molecules between the nucleus and the cytoplasm via the nuclear pore.
http://www.nature.com/nature/journal/v386/n6627/abs/386779a0.html
https://www.ncbi.nlm.nih.gov/pubmed/18282135
http://www2.mrc-lmb.cam.ac.uk/understanding-the-mechanism-of-the-nucleocytoplasmic-transport-cycle/

etc, etc

**Comment by ValWood** [comment]
Probably even the addition  of nuclear pore might not be enough to define nucleocytoplamic transport fully? Maybe should mention dependency on karyopherins too? Or some additional differentia.

**Comment by krchristie** [comment]
Hi @ValWood

While it's a fair point that we may not want to have viral processes placed here under things that are normal for the host cell, I'm not sure that the definition of the term 'nucleocytoplasmic transport' is the place to solve this issue. 

 @ukemi & @pgaudet - Related to the viral issues we were discussing earlier (https://github.com/geneontology/go-ontology/issues/13233), here are some more viral terms where we may need to consider the relationship of viral processes to things that are normal for a non-virus infected cell:
- GO:0039674 exit of virus from host cell nucleus (& 3 child terms)
- GO:1902594 multi-organism nuclear import 
-- GO:0075732 viral penetration into host nucleus (& 4 child terms)

Also, it seems inconsistent that we've got the multi-organism vs single-organism distinction under 'nuclear import' but not under 'nuclear export', and also that if we are going to have the distinction by multi- vs single- organism process, that 'RNA import into nucleus' is a sibling of these terms. We have this basic structure:
<pre>
- 'nucleocytoplasmic transport'
-- 'nuclear export'
--- 'exit of virus from host cell nucleus'
--- 'protein export from nucleus'
--- 'RNA export from nucleus'
-- 'nuclear import'
--- 'multi-organism nuclear import'
---- 'viral penetration into host nucleus'
--- 'RNA import into nucleus'
--- 'single-organism nuclear import'</pre>

**Comment by ValWood** [comment]
I still think that "nucleocytoplasmic transport" should be defined as a eukaryote specific transport mechanism.  But you are correct, there are larger issues with viral process merging into normal eukaryotic processes..

**Comment by krchristie** [comment]
I don't object to defining 'nucleocytoplasmic transport' as a eukaryote specific process, though I think that adding a taxon constraint rather than changing the definition might be the way to go. 

However,  your previous suggestions to modify the definition was narrowing it to transport through the nuclear pore, and I'm hesitant to assume that all 'nucleocytoplasmic transport' is via the nuclear pore, which might not be the only way things are transported between the nucleus and the cytoplasm. I also don't mind having a term specifically for transport through the nuclear pore, but think it should be named in such a way that this is clear in the name as well as the definition.

@ukemi - In light of the comment on this term 'nucleocytoplasmic transport', do you think this logical definition is OK. It looks to me like this definition is defining exactly what the comment says that transport through the nuclear pore is not.

**Equivalent to:**
<pre>transport
 and ('occurs in' some intracellular)
 and ('results in transport across' some 'nuclear envelope')</pre>

**Comment:**
<pre>Note that transport through the nuclear pore complex is not transmembrane because the nuclear membrane is a double membrane, and is not traversed.</pre>

**Comment by ValWood** [comment]
Hi Karen,

Yes a taxon check would work too.
As far as I'm aware there are  no known other way to transport things from the nucleus to the cytoplasm. There are  nuclear membrane transmembrane transporters, but they transport from the cytoplasm into the lumen. I don't know if there are lumen to nucleus  TM transporters. Either way transmembrane transport isn't nucleocytoplasmic transport and this issue is a long standing issue for GO annotation.

 nucleocytoplasmic transport has to go via the nuclear pore. That is how this process is defined by the community (see the 4 papers I  randomly selected linked in the original comment). All  describe nucleocytoplasmic transport as being a process which occurs visa the nuclear pore... I think the name is fine because as far as I'm aware its the only name biologists use  to describe it.  Our def could be made a little more specific.

**Comment by krchristie** [comment]
Is this also true for small molecules, which sometimes have more transport mechanisms than large things?

**Comment by ValWood** [comment]
As far as Im aware these travel into the nucleus  largely by diffusion.

The npc is  120 nm in diameter
the diameter of the pore/channel itself is 5- 10 nm

**Comment by ValWood** [comment]
Just found"
Each nuclear pore is a large complex of proteins that allows small molecules and ions to freely pass, or diffuse, into or out of the nucleus. "

**Comment by jimhu-tamu** [comment]
Does this also run into the classic problem in usage for protein localization terms? i.e. is the thing being imported have process function of import? Or is it a passive participant that should not be annotated to the term. We've been telling CACAO students not to annotate cargoes/substrates to protein localization to terms.

**Comment by ValWood** [comment]
I was thinking the same Jim. It seems the mechism is unknown, but if it is transported by the nucleocytoplasmic mechanism, it's a cargo. If it's by some other type of "insertion mechanism" it isn't nucleocytoplasmic transport.

**Comment by krchristie** [comment]
While it wouldn't surprise me if there are annotations to this term inappropriately made for cargo genes, the intent of the term is for things involved in the mechanism of the transport, not the things being transported.

**Comment by ValWood** [comment]
Out of date. @pgaudet you already fixed this by merging.
v
