### ISSUE TITLE
rename GO:0002926 tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridine biosynthesis.

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13256]
GO:0002926 tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridine biosynthesis.
The process whereby a wobble base uridine residue in a tRNA is modified to 5-methoxycarbonylmethyl-2-thiouridine.

Harold, would this be more consistent and less confusing if called

GO:0002926 tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridine modification?

add synonym "mcm5 modification"

val

**Comment by hdrabkin** [comment]
I haven't done an extensive check but I don't think we have been consistent here (biosynthesis vs modification).  
If the name is changed to modification, does then the title imply that the 5-methoxycarbonylmethyl-2 thiouridine is modified. No. It's the wobble base that is modified to mcm5. 
mcm5 modification implies that the mcm5 is modified; no.; same problem.
So it seems biosynthesis may be more clear?

**Comment by ValWood** [comment]
tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridinylation ;) ?

We seem to be fairly consistent otherwise:
http://pombase2.aska.gen.nz/term/GO%3A0006400

**Comment by hdrabkin** [comment]
tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridinylation
done
