### ISSUE TITLE
GO:0007227  signal transduction downstream of smoothened

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13250]
Is this a 'valid' GO term for a signalling pathway?

It seems odd to have a  process term like this?
Should it be merged into the general signalling pathway term?

**Comment by hdrabkin** [comment]
Looking at some tickets I didn't know I had open: so what exactly is wrong? Why is it odd; why should it be merged?

**Comment by hdrabkin** [comment]
Should this ticket be merged into #12999?

**Comment by ValWood** [comment]
I think it's a duplicate, can close.
