### ISSUE TITLE
which is the correct transporter term to use for TIM complex and Tom complex?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13251]
mitochondrial protein-transporting ATPase activity
Definition	Catalysis of the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O = ADP + phosphate; drives the transport of proteins into the mitochondrion via the mitochondrial inner membrane translocase complex.
Comment	See also the cellular component term 'mitochondrial inner membrane presequence translocase complex ; GO:0005744'.
seems to be the correct term for
tim23 translocase.

However,  despite 6,273 for 5,376 proteins only 
85 proteins are annotated to  GO:0008566  mitochondrial protein-transporting ATPase activity
and very few of these appear to be tim complex.

Also,  Tim complex is also a protein channel, so if   GO:0008566  is the correct term, I would expect it to have  a "protein channel activity" parent.

If this is the correct term,  which would be the correct term for
"mitochondrial outer membrane translocase complex"

Also before I proceed cleaning these up at PomBase, was there recently some discussion about splitting the ATPase and transport functions in terms like this?

**Comment by ValWood** [comment]
well primarily ontology first I think, at least most of the questions are ontology related. 

I'm not sure when the comment got added and if it is correct for the complex it refers to, if it is an ATPase, why it doesn't have channel parent,   or if GO are going to change  compound functions....

why  there isn't an equivalent term for TIM (the term name fits both), but the def says
 "drives the transport of proteins into the mitochondrion via the mitochondrial inner membrane translocase complex"

I thought that TIM was for transfer of proteins into the inner membrane and TOM we for import into the mitochondria so even this part is confusing....
This term fits  TOM better than TIM....

**Comment by ValWood** [comment]
GO:0005744
Name	mitochondrial inner membrane presequence translocase complex
The protein transport machinery of the mitochondrial inner membrane that contains three essential Tim proteins: Tim17 and Tim23 are thought to build a preprotein translocation channel while Tim44 interacts transiently with the matrix heat-shock protein Hsp70 to form an ATP-driven import motor. 

so it seems this is two parts, a channel and an ATPase.

**Comment by ValWood** [comment]
I'll label as low priority, no hurry for me. I thought I could do a quick  10 minute tidy but it can wait.

**Comment by vanaukenk** [comment]
Hi @ValWood 
I will start working on this ticket.  Will check in with you if I have any questions.  Thx.

**Comment by ValWood** [comment]
There was recently a discussion about whether compound function terms  like ATPase and transporter should exist. Unfortunately I cant find it, and I don't know the outcome of the discussion. @dosumis  may know which one I mean...

**Comment by mah11** [comment]
Re compound functions, it looks like there are some relevant tickets in the molecular_function_refactoring tracker, including:
transporters - https://github.com/geneontology/molecular_function_refactoring/issues/26
ATPase, energy, etc. - https://github.com/geneontology/molecular_function_refactoring/issues/32
topmost terms - https://github.com/geneontology/molecular_function_refactoring/issues/25
compound functions generally - https://github.com/geneontology/molecular_function_refactoring/issues/27
motors - https://github.com/geneontology/molecular_function_refactoring/issues/48

**Comment by ValWood** [comment]
Hmm, I dont think it was any of those. Actually was it about the dynein? you two modelled in Noctua (ATPase + motor activity?)

**Comment by mah11** [comment]
That is the "motors" ticket (48) I linked above.

**Comment by mah11** [comment]
For that one the likeliest solution is not to obsolete the NTPase motor terms, but to change the link to NTPase activity from is_a to has_part.

**Comment by vanaukenk** [comment]
Hi @ValWood 

Looking at the ontology and the annotations, it seems like groups have annotated subunits of both TOM and TIM complexes to GO:0015266 'protein channel activity' (with and without the contributes_to qualifier), but the only annotations to GO:0008566 'mitochondrial protein-transporting ATPase activity' are IEA annotations coming from EC mappings:
 http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008566#term=annotation

The TOM complex seems to only have channel activity, but as you point out, the TIM complex seems to work via a two-step mechanism of channel activity to import the presequence, and then ATPase activity to transport the entire protein, into the matrix.

I'd like some input from @dosumis about whether it makes sense at this point to add more specific child terms to GO:0015266 'protein channel activity' for the TOM and TIM complexes, but also keep the ATPase term for the TIM complex.

And then it'd be worth it, I think, to review the existing annotations for the different complex subunits to see if we think they accurately describe the biology or if we'd want to consider revising some of the annotations that currently use the contributes_to qualifier to instead have more specific regulatory-type activities.

There is a nice review here:

http://www.sciencedirect.com/science/article/pii/S0005273610002452

**Comment by ValWood** [comment]
OK, once we know what should be annotated to which terms I can make  Term Matrix rules for the complex like we did with 
https://github.com/geneontology/go-annotation/issues/1490

We can do rules for functions, processes and locations for these...

**Comment by ValWood** [comment]
I opened this ticket for annotation IEA check, https://github.com/geneontology/go-annotation/issues/1582

I had forgotten about  this exisitng one

**Comment by pgaudet** [comment]
Fixed in #20669
