### ISSUE TITLE
create new process term and negative regulation of it

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#13253]
Hi,
I would like to request the following two terms please:

1. telomerase RNA polyadenylation involved in polyadenylation-dependent child of existing term ncRNA catabolic processncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process
suggested definition or better: the enzymatic addition of a sequence of adenylyl residues (polyadenylation) at the 3' end of a telomerase RNA (also known as TERC), occurring as part of the process of polyadenylation-dependent telomerase RNA catabolism.

2. negative regulation of telomerase RNA polyadenylation involved in polyadenylation-dependent
suggested definition or better: Any process that stops, prevents, or reduces the frequency, rate or extent of the enzymatic addition of a sequence of adenylyl residues (polyadenylation) at the 3' end of a telomerase RNA (also known as TERC), occurring as part of the process of polyadenylation-dependent telomerase RNA catabolism.

GOC: nc
GOC: BHF
GOC: BHF_telomere

PMID 26950371

Thanks.

**Comment by NancyCampbell** [comment]
missed part of the name. apologies. it should have been:

telomerase RNA polyadenylation involved in polyadenylation-dependent telomerase RNA catabolic process

negative regulation of telomerase RNA polyadenylation involved in polyadenylation-dependent telomerase RNA catabolic process

**Comment by ValWood** [comment]
Hi Nancy, 


Wouldn't you do this with an extension as its gene product specific?

polyadenylation-dependent RNA catabolic process has_input "telomerase ID"

?

v

**Comment by vanaukenk** [comment]
Hi @NancyCampbell 

We are trying to avoid creating and/or using gene product-specific terms, so I agree with @ValWood that the preferred annotation would be to the parent term you cite:

GO:0043630  ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process

with an annotation extension has_input (human telomerase RNA ID)

For the second term, which of the gene products in the paper were you thinking of annotating to that term?  I'm looking at the nice summary in Figure 6 of PMID:26950371 and just want to make sure we get that term right.  

Figure 6 would be a great starting point for a Noctua model!

Thx.

**Comment by NancyCampbell** [comment]
Hi,
Thank you for the clarification. I understand.
The second term (but now without the telomerase RNA bit): PARN negative regulation of ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process
Thanks

**Comment by vanaukenk** [comment]
Hi @NancyCampbell 

For the PARN annotation, do you mean to say that PARN regulates the polyadenylation process or that it regulates the polyadenylation-dependent ncRNA catabolic process?

If the latter, then I think another way of making that annotation would be to annotate PARN to:

ncRNA deadenylation (new GO term - we should probably have this term anyway)

with annotation extensions

negatively_regulates(polyadenylation-dependent ncRNA catabolic process), has_input(human telomerase RNA)

What do you think?

**Comment by vanaukenk** [comment]
Added:

+id: GO:0110008
+name: ncRNA deadenylation
+namespace: biological_process
+def: "Shortening of the poly(A) tail of a nuclear-transcribed ncRNA." [GOC:BHF, GOC:BHF_telomere, GOC:nc, PMID:26950371]
+is_a: GO:0034660 ! ncRNA metabolic process
+created_by: kmv

**Comment by NancyCampbell** [comment]
Hi Kimberley,
First, thank you for the suggestion and creating the term. 
I was just wondering if you know how long it will take for the term to become available on P2G? I checked today and it is not available yet.
Thanks
Nancy

**Comment by vanaukenk** [comment]
Hi Nancy,
Thanks for checking on this.  It looks like this new term got caught up in github merge limbo, but it's now been added and should be available with the next ontology file release.
Apologies for the hold up.

**Comment by NancyCampbell** [comment]
Perfect. Sorry about reviving the thread. Thank you Kimberly! (sorry for the earlier spelling)- I think I got it right this time! Nancy :-)

**Comment by NancyCampbell** [comment]
can you please add GOC listed in my original request. Thanks.

**Comment by NancyCampbell** [comment]
apologies. was looking at the wrong term.
