### ISSUE TITLE
obsolete GO:1901619 tRNA methylation in response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13263]
only used by PomBase:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1901619#term=annotation

It doesn't really make sense to do this with a precomposed term, not sustainable.
I removed the annotation as it is already captured with an extension.

**Comment by ValWood** [comment]
also
GO:1901644
positive regulation of tRNA methylation in response to nitrogen starvation


but here I need a  couple of terms
positive regulation of tRNA methylation
positive regulation of  tRNA C5-cytosine methylation

**Comment by vanaukenk** [comment]
Hi @ValWood 
We're almost done with this, but I was wondering if you have a reference for these terms.  If so, I'll add the PMID(s) to the definition xrefs.
Thx.

**Comment by ValWood** [comment]
can use the ref on the old term: PMID: 23074192

**Comment by vanaukenk** [comment]
Okay, thanks @ValWood

**Comment by vanaukenk** [comment]
New terms added:

GO:0110004 positive regulation of tRNA methylation
GO:0110005 positive regulation of tRNA C5-cytosine methylation
