### ISSUE TITLE
ntr: DNA clamp unloader

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13261]
I think I need a new term to describe

GO:0031391 - Elg1 RFC-like complex
A pentameric replication factor C (RLC) complex, which unloads the DNA polymerase processivity factor proliferating cell nuclear antigen (PCNA) from chromatin and has roles in telomere length regulation and other aspects of genome stability. In Saccharomyces the subunits are known as Elg1p, Rfc2p, Rfc3p, Rfc4p, and Rfc5p.

previosly I used

GO:0003689 DNA clamp loader activity
Definition	Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the opening of the ring structure of the PCNA complex, or any of the related sliding clamp complexes, and their closing around the DNA duplex. 

as it was originally thought to be a clamp loader  like RFC...

Complex definition was recently revised to be an unloader:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0031391#term=history

So I guess the definition would be the opposite reaction?

Definition	Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the opening of the ring structure of the PCNA complex, or any of the related sliding clamp complexes, and their removal from the DNA duplex. 
?

(Not that existing annotations will be correct for all but the elg1 subunit, because the other members are also part of the loader)

**Comment by ukemi** [comment]
The definition is reversible (=). Do you want me to make it directional? Didn't you and I already discuss a ticket just like this some time ago?

**Comment by ukemi** [comment]
Ah, I see. The reaction is the same, but one activity puts it on and the other takes it off, right?

**Comment by ValWood** [comment]
Yep.

We didn't discuss this exact one (In fact I think we were discussing cohesin loading and unloading, not PCNA). IIRC we  could not always create MF terms there, because we didn't know the mechanism....waiting for the biology...

**Comment by ukemi** [comment]
Yes. You are correct. Can you give me a PMID for the new term?

**Comment by ValWood** [comment]
PMID:27664980 is the one supporting the complex  term:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0031391

**Comment by ValWood** [comment]
PMID:23499004 seems to be the original paper
