### ISSUE TITLE
parentage query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13262]
It seems odd that "protein transporter activity" is a descendant of "peptide transporter activity"

Is that via CHEBI?

**Comment by ValWood** [comment]
was added very recently
2017-02-23	Added	RELATION	is a GO:0015197 (peptide transporter activity)

**Comment by ukemi** [comment]
I don't see it in the current editors' version of the ontology. Let's see if it is already corrected.

**Comment by ValWood** [comment]
Yep @kltm  says is fixed. closing.

**Comment by ukemi** [comment]
I love it when things fix themselves.

**Comment by kltm** [comment]
I just want to double check what a *fix* is defined to be in this case: existence in a particular file, understanding of interaction between the ontologies?

**Comment by ValWood** [comment]
Quoting @kltm "It seems like it may have been an error that got into the pipeline and will "recover" tomorrow"
Isn't that a fix ;)

**Comment by ukemi** [comment]
In the editors' version of the ontology, it is asserted to be a 'substrate-specific transporter activity' and is not asserted or inferred to be a 'peptide transporter activity'. I assumed the fix is that this is now consistent across the different release versions.
