### ISSUE TITLE
taxon imports incomplete?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#13269]
The editor's file appears to only be importing a subset of taxa that are used in taxon restrictions. For example if you open 'blapheroplast' (GO:00197727), you will see that it has several never_in_taxon restrictions to Taxa (3176, 3312, 3378), but these taxa does not seem to be loaded as part of the imports.

**Comment by pgaudet** [comment]
@ukemi 
Now that we have changed the process for loading taxon constraints, is this still a problem? 

Thanks, Pascale

**Comment by ukemi** [comment]
At least for this term, this seems to be fixed.
