### ISSUE TITLE
MP late endosome to vacuole transport via multivesicular body sorting pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13265]
~some~ could this term have the parent  "vesicle-mediated transport"

some participants in v-m-t are not correctly slimmed because this parent is missing.

**Comment by krchristie** [comment]
Hi @ValWood 

Please let me know which specific terms are missing appropriate parentage.

thanks!

**Comment by ValWood** [comment]
whoops corrected request.
val

**Comment by krchristie** [comment]
So, looking at the MVB sorting terms, this ancestor term  
**'endosome transport via multivesicular body sorting pathway' (GO:0032509)**

has these SubClass relationships:
- **'endosomal transport'**
- **has_part** some **'multivesicular body sorting pathway'**

Looking at the Nickerson et al. review, cited in the def of **'multivesicular body sorting pathway'**, they refer to **MVB vesicles** and discuss the MVB sorting pathway as a type of 'vesicle-mediated transport'. For the term 'multivesicular body sorting pathway', we do have an asserted subclass that it is_a 'vesicle-mediated transport'. In addtion, with most other terms under 'vesicle-mediated transport', we say that they are SubClasses of v-m-t. However, we don't have subclass relationships to v-m-t for the terms referring to sorting specific cargoes to/from specific locations via the MVB sorting pathway. 

Based on this review, I agree with Val, that we should make the SubClass relationships for the types of MVB sorting to v-m-t, and remove this has_part relationship, to treat MVB sorting consistently with how we do other types of v-m-t.

@ukemi - Any objections to this line of thinking?


Nickerson DP, Russell MR, Odorizzi G. A concentric circle model of
multivesicular body cargo sorting. EMBO Rep. 2007 Jul;8(7):644-50. Review. PubMed
PMID: 17603537

**Comment by krchristie** [comment]
For this term: 'endosome transport via multivesicular body sorting pathway' (GO:0032509),
I changed the has_part 'multivesicular body sorting pathway' to just the SubClass relationship.

Here's the diff (which doesn't include the term name or ID, but is the correct def):
<pre> def: "The directed movement of substances from endosomes to lysosomes or vacuoles by a pathway in which molecules are sorted into multivesicular bodies, which then fuse with the target compartment." [GOC:mah, PMID:12461556, PMID:16689637]
 synonym: "endosome transport via MVB sorting pathway" EXACT []
 is_a: GO:0016197 ! endosomal transport
-relationship: has_part GO:0071985 ! multivesicular body sorting pathway
+is_a: GO:0071985 ! multivesicular body sorting pathway</pre>

This seems to take care of the specific child term you indicated @ValWood
