### ISSUE TITLE
ntr: regulation of cytoplasmic translational fidelity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13260]
child of
 GO:0006450 regulation of translational fidelity
Any process that modulates the ability of the translational apparatus to interpret the genetic code.

I think this is the term I need to allow efficient translation of  specific codon usage?

PMID:22768388
Title	Translational control of cell division by Elongator.

**Comment by hdrabkin** [comment]
Hi Val
Just looking at this now, but I'm not sure fidelity = efficiency.
So fidelity is making sure the codon is properly translated (ie, making sure a GUG is not translated as an AUG
Efficiency is more a question of rate:
Example: adjusting the tRNA pool to better match a codon bias/usage; I would not annotate this to fidelity.

**Comment by hdrabkin** [comment]
Codon usage bias refers to differences in the frequency of occurrence of synonymous codons in coding DNA. 
How about something like
codon optimization
Def: One or more processes resulting in  maximizing  translation of mRNAs with a specific set of codons
I would not make it a child of fidelity, but maybe a sib?

**Comment by ValWood** [comment]
Hi Harold,

I thought fidelity because:
"In the present study, we show that the inactivation of Elongator in fission yeast leads to the
loss of the double modification mcm5s2. The resulting phenotypes include mitosis and
cytokinesis defects. Using a proteome-wide approach, we have identified target mRNAs that
require Elongator for efficient translation"

 The translation rate  difference is due to  differential tRNA reusage rate for different codons and can be altered by changing the codon usage of the transcript. Elongator is required for efficient translation of these particular split codons  but is not itself  directly controlling the different  translation rate for different codon usage/ tRNA pool?

To be more precise it could be:

regulation of cytoplasmic translational fidelity of split codon boxes

(not this would be  a descendent of regulation of translational elongation anyway)


v

**Comment by hdrabkin** [comment]
I was going to do a quick put in but it appears Pacale already put this in
GO:0140018 but left this ticket open. Closing now
