### ISSUE TITLE
NTR: microtubule plus end polymerase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13285]
suggested def
Catalyses the addition of tubulin  dimers to the plus end of a microtubule

parents
transferase activity

F-P link
microtubule polymerization GO:0046785

Do we also need  generic term which covers minus end too?

This seems to be the original paper for plus end polymerase activity:
XMAP215 Is a Processive Microtubule Polymerase
Cell. 2008 Jan 11;132(1):79-88.

"processive polymerase that directly catalyzes the addition of up to 25 tubulin dimers to the growing plus end. Under some circumstances XMAP215 can also catalyze the reverse reaction, namely microtubule shrinkage"

A pombe paper PMID:27872152

**Comment by ValWood** [comment]
so this is  a "protein transferase" (like ubiquitin transferase), but it is also processive.

**Comment by ukemi** [comment]
Hi @ValWood ,
If this reaction represents the bidirectional activity, then it can't have a part_of link to microtubule polymerization. It looks like in the presence of free tubulin, it catalyzes the polymerase reaction and in the absence of free tubulin, it catalyzes the depolymerization. This makes sense. Is there any evidence that it catalyzes both directions physiologically?

**Comment by ValWood** [comment]
Yes it seems to be both directions physiologically.

**Comment by ukemi** [comment]
[Term]
+id: GO:0061863
+name: microtubule plus end polymerase
+namespace: molecular_function
+def: "Catalysis of the transfer of tubulin dimers to the plus end of a microtubule. The reaction is reversable depending on the availability of dimers." [PMID:27872152]
+is_a: GO:0016740 ! transferase activity
+relationship: part_of GO:0000226 ! microtubule cytoskeleton organization
+created_by: dph
+creation_date: 2017-04-07T17:36:57Z
+
+[Term]
