### ISSUE TITLE
Travis checks should include recent Jenkins failures

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#13282]
There have been a couple cases recently where the Jenkins jobs have failed, but it would be easier if the checks were done at the time of a pull requset.

1. Equivalent class check.
2. Cycle check.
3. Synonym check for merged terms.

**Comment by pgaudet** [comment]
@dougli1sqrd Is this something you can do ?

**Comment by dougli1sqrd** [comment]
Yeah, we can put more of these as part of the travis checks. This should be balanced with time to execute the check though.

**Comment by cmungall** [comment]
1. This done already. By default robot complains if new inferred equivalencies are found
 2. subclass cycle checks are actually a special case of the above (recall if A<=B and B<=A then A=B)
 3. Not sure what test you mean, but the new robot report will have extensive synonym checks. Currently we have a check to see if any exact matches a label.

I think this can be closed?
