### ISSUE TITLE
parentage of 'oral apparatus'

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13283]
I think perhaps this term **'oral apparatus'** does not belong under 'cell projection.

From the review quoted below, it seems that the 'oral apparatus' is a complex structure which contains cell projections, but the oral apparatus as a whole is not a cell projection. 

**Lee & Kugrens.** (Relationship between the flagellates and the ciliates. Microbiol Rev. 1992   (PMID:1480107): 
<pre>
Most ciliates are phagotrophic, taking food particles or organisms in through a mouth (cytosome, 
cytopharynx) that is commonly surrounded by rows of cilia (oral kinetids) (Fig. 2). The mouth and 
the oral cilia make up the oral apparatus, which can be on the cell surface or in a depression of 
the cell surface.</pre>

**Comment by krchristie** [comment]
Looking at this review again, it is pretty clear that the 'oral apparatus' is composed of both the 'mouth' (called a cytosome or cytopharynx) and surrounding motile cilia. The mouth is not a cell projection. So, I think this term needs to be moved up. I guess it can just be a direct child of 'cell part'.

If we were focused on annotation of ciliates, I think there would be a case to make additional terms to represent the two parts of the ciliate oral apparatus. However, there is currently only one annotation to 'oral apparatus' in AmiGO and leaving that annotation directly to the term 'oral apparatus' seems fine.

Thus, I propose to move this term up a level to be a direct child of 'cell part' and leaving making of any more specific terms to a later date when there is a need. Sound OK to you @ukemi ?

**Comment by krchristie** [comment]
Also seems like this term should get a taxon constraint only in Ciliophora:

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=5878

**Comment by krchristie** [comment]
As an FYI @ukemi & @cmungall , it does not seem possible to create new class expression in Protege that involve the GO term for 'cell part' (GO:0044464) since there is an Uberon term with the same name and Protege seems to always choose the Uberon term rather than the GO term when you type 'cell part' in. To get around this, I did that edit in emacs, but then loaded into Protege and did the taxon restriction in Protege and saved, so formatting should be fine, but thought I'd mention that issue with edits trying to use the GO term for 'cell part'.

**Comment by cmungall** [comment]
cell part was obsolete a while back, I'll refresh our uberon import

**Comment by cmungall** [comment]
make a new ticket for taxon constraint?

I might tend towards disambiguating the name, I think 'oral apparatus' is used for some insects to describe the sum of mandible/maxilla/labrum

**Comment by krchristie** [comment]
The 'oral apparatus' of insects, being an anatomical structure, seems out of scope for GO. In addition, I'm not sure I see a need for disambiguation as I'm also not sure I've ever heard that term applied to the insect structure, with the term 'mouthparts' being what I've generally heard: https://en.wikipedia.org/wiki/Insect_mouthparts

The existing term we have for cellular structure of the 'oral apparatus' is clearly specific to ciliates so I have already added the taxon constraint.
**Def:** Complex basket- or funnel-like structure used by the cell to collect food and channel it to the cytostome; includes specialized sub-structures made up of closely-spaced cilia and underlying basal bodies and fibrillar systems.
PMID:10503189  (https://www.ncbi.nlm.nih.gov/pubmed/?term=10503189)
