### ISSUE TITLE
single term for 'haustorium' for two quite different structures

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13284]
This arose in https://github.com/geneontology/go-ontology/issues/13193 when I was trying to determine if 'haustorium' should be moved down to 'plasma membrane bound cell projection'.

However there are at least two kinds of haustoria:
- one in plant parasites of other plants roots. From what I have gleaned so far, these may be more appropriate as a cellular bridge. @tberardini do you know more about these?
From PMID:26322059 
<pre>Parasitic plants form a haustorium, a unique multicellular invasion organ common to all 
parasitic plants. In the Orobanchaceae root parasites, globular-shaped haustoria invade host 
roots and form direct vascular connections with host plants, which likely enables nutrient transfer 
(Hibberd and Jeschke, 2001; Yoshida and Shirasu, 2012). </pre>
- one in fungal parasites of plants @dianeoinglis, do you know anything about these in fungi?
From PMID:25699068
<pre>On the leaf surface rust spores produce germ tubes which grow on the plant surface. Over 
a stoma an appressorium is formed, a special structure from which the infection hypha is invading 
the leaf tissue (Hoch and Staples, 1987). Within the substomatal vesicle intercellular hyphae 
spread the plant tissue and haustorial mother cells are formed adjacent to mesophyll cells. 
Haustoria are formed after penetrating the plant cell wall without vulnerating the plant plasma 
membrane. The haustoria grow within the living plant cells and constitute an intimate contact to 
the plant cells cytoplasm. As a result the cytoplasm of host and fungus remain separated by the 
host plasma membrane, the fungal plasma membrane and between the so-called extrahaustorial 
matrix (Voegele et al., 2009).</pre>

**Comment by tberardini** [comment]
@krchristie I don't know more about parasitic plant haustoria than what you've stated.  Wish I could be more helpful but I'd be digging in the same literature that you currently are exploring and starting from the same base level of knowledge.

**Comment by krchristie** [comment]
from: https://en.wikipedia.org/wiki/Haustorium
> In botany and mycology, a haustorium (plural haustoria) is a structure that grows into or around another structure to absorb water or nutrients. In botany, this may refer to a cotyledon,[1] or to the root of a parasitic plant (such as the broomrape family or mistletoe) that penetrates the host's tissue and draws nutrients from it. In mycology, it refers to the appendage or portion of a parasitic fungus (the hyphal tip), which performs a similar function.

In light of the fact that the same word is used to describe structures from multiple taxa that perform a similar function, and that haustorium are not formed by humans so this is not a high priority term for mammalian annotation, I am going to leave this as is. If there becomes a need for more specific terms, they can be created with any additional specific parentage that is appropriate.
