### ISSUE TITLE
ntr: mitochondrial ADP transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13294]
ntr: mitochondrial ADP transmembrane transport
(with Pascale's changes this could probably be called  "mitochondrial ADP  transport"

Def 
The directed movement of ADP from one side of a membrane to the other into, out of or within a mitochondrion. 

see
GO:1990544 mitochondrial ATP transmembrane transport

**Comment by pgaudet** [comment]
Hi Val, 

I can create a term similar to 'mitochondrial ATP transmembrane transport'. Is it important to capture import versus export, because this terms encompases both. Ist his right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi Val, Can you provide a reference ? 
Thanks, Pascale

**Comment by ValWood** [comment]
hmph, I posted a follow up for this the other day but I mustn't have pressed submit.

So for the record, I was annotating 
anc1 http://pombase2.aska.gen.nz/gene/SPBC530.10c
single member ortholog of cerevisiae  AAC1-3
So basically I was trying to get the correct process for ADP to 
go with
ATP:ADP antiporter activity
mitochondrial ATP transmembrane transport
 
This is the paper used to describe the  ATP:ADP antiporter activity at SGD
Gawaz M, et al. (1990) PMID:2167309
I looked and as it was reconstitution I could not figure out the direction of transport.

**Comment by ValWood** [comment]
This might be a better ref, via Interpro family
Adenine nucleotide translocator 1 (IPR002113)
http://www.ebi.ac.uk/interpro/entry/IPR002113	

Mitochondrial ADP/ATP translocase, an abundant component of the inner membrane, carries ATP from the matrix into the inter-membrane space and transports ADP back [PMID: 2541251]. The protein is an integral membrane protein that functions as a homodimer.

PMID: 2541251 DNA sequences of two expressed nuclear genes for human mitochondrial ADP/ATP translocase.
