### ISSUE TITLE
MP for 'centriole assembly'

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13295]
While looking at this issue: https://github.com/geneontology/go-ontology/issues/13247, 
I noticed that the term 'centriole assembly' has no relationship to 'microtubule organizing center organization', even though in GO we say that a 'centriole' is a 'microtubule organizing center part'.

It seems to me that 'centriole assembly' should be a subclass of 'microtubule organizing center organization', though I don't think we can go farther and say that it is a subclass of 'centrosome organization' since centrioles are generated de novo in order to become ciliary basal bodies in terminally differentiated multiciliated cells where they will never become a part of a centrosome.

Also, I see that 'centriole' has the subclass relationship:
**'part of'** some **centrosome**

I think we have to remove this for the reasons I gave above where some centrioles are never part of centrosomes. We could make the opposite relationship that a centrosome
**'has_part'** some **centriole**

**Comment by pgaudet** [comment]
Hi Karen,

you might want to wait for #13247  to be closed so that there are no conflicts (the terms seem very close in the ontology). 

Pascale

**Comment by pgaudet** [comment]
Karen, should I do this while I am working on this part of the ontology ?

**Comment by krchristie** [comment]
Pascale, if you're still working today and want to do this, go ahead.

**Comment by krchristie** [comment]
closing since @pgaudet took care of this along with https://github.com/geneontology/go-ontology/issues/13247
