### ISSUE TITLE
poly(A) tail shortening vs deadenylation

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#13291]
Hi,

I'd like to create a new ontology term for ncRNA poly(A) deadenylation, but noticed that the analogous term names for mRNAs refer to poly(A) tail shortening with deadenylation terms as related synonyms.  See, for example, GO:0000289, nuclear transcribed mRNA, poly(A) tail shortening.

Note that GO:0000289 also has an is_a child term of:
GO:0098806 deadenylation involved in gene silencing by miRNA

I think it might be easier for curators and users to search for and find a 'deadenylation' term, similar to what we have, say, for things like acetylation/deacetyltation or methylation/demethylation, but wanted to make sure the original meaning of GO:0000289 was not meant to include processes other than deadenylation.  If so, maybe we should make separate BP terms?

@krchristie what do you think?

Thanks,
--Kimberly

**Comment by krchristie** [comment]
Hi @vanaukenk 

I think that the shortening names might be a little better than the deadenylation names since it better describes what is happening, i.e. that the tail is shortened, while deadenylation might imply that it is completely gone. So, I'd probably go with the shortening names with the deadenylation names as some sort of synonym.

-Karen

**Comment by vanaukenk** [comment]
Thanks, @krchristie 
For the new term that I'm adding, I think I will go with the deadenylation term, though, as I believe it describes the process for the PARN enzyme (for which the term is needed) most accurately.  
I still find this a confusing area of the literature/ontology, though, as sometimes it seems that authors use deadenylation synonymously with shortening and/or trimming.

**Comment by rachhuntley** [comment]
"Deadenylation" appears to be the more common nomenclature: 844 hits in PubMed versus 189 for "poly(A) tail shortening", so I think curators are more likely to search for deadenylation terms.

I don't think shortening includes anything other than deadenylation, e.g. http://genesdev.cshlp.org/content/21/23/3135.full states "The poly(A) tail-shortening process, referred to as deadenylation, is the first and rate-limiting step, and is also the most efficient step in controlling mRNA decay (Decker and Parker 1993)." and PMID:21957022 says "average tail length results from the balance between polyadenylation and deadenylation."

As long as all terms relating to this have the synonyms, then either should be fine. I created the miRNA related one and chose to use deadenylation as this was how it's referred to in the literature.

Rachael.

**Comment by rachhuntley** [comment]
Sorry Kimberly @vanaukenk, didn't see you had closed this as have had the tab open for a day!

**Comment by vanaukenk** [comment]
@rachhuntley - no worries; I appreciate your comments.

One possibility might be to create parent RNA deadenylation terms and then make specific child terms to refer to the different contexts of deadenylation, for example the trimming catalyzed by the Pan2/Pan3 complex or the complete, or nearly complete, deadenylation catalyzed by the CCR4-Not complex.  These terms might then be siblings to the miRNA-related term that you created, GO:0098806, deadenylation involved in gene silencing by miRNA.

**Comment by ValWood** [comment]
I also think "deadenylation" would be better in the primary term names as the most common biological usage. Issue came up for PomBase this week too.

https://github.com/pombase/fypo/issues/2996#issuecomment-293919255

Its odd that the current synonyms are related rather than exact.

**Comment by ValWood** [comment]
I don't think we should create this term bow.
We would annotate to 

deadenylase + specific process

**Comment by ValWood** [comment]
checnged 'closed type'
