### ISSUE TITLE
cell projection assembly issues

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13298]
I noticed today that 'axoneme assembly' has an asserted SubClass saying that it is a 'cell projection assembly', which seems incorrect since an axoneme by itself is not a cell projection, but part of a cilium. This term already has an asserted is_a parent for 'microtubule bundle formation' which seems fine, so I think we can just remove this incorrect is_a parent.

Looking at this, I realized I should make the parallel term for 'plasma membrane bounded cell projection assembly' and move things appropriately. Any objections @ukemi ?

**Comment by krchristie** [comment]
there are also regulation of cell projection assembly terms so I'll need to do a better job propagating that change all the way through...

**Comment by krchristie** [comment]
diff --git a/src/ontology/go-edit.obo b/src/ontology/go-edit.obo
index b108b2a..fe85870 100644
--- a/src/ontology/go-edit.obo
+++ b/src/ontology/go-edit.obo
@@ -234161,7 +234161,6 @@ name: uropod assembly
 namespace: biological_process
 def: "The assembly of a uropod by rearrangement of the cytoskeleton and overlying membrane." [GOC:mah]
 synonym: "uropod formation" EXACT [GOC:mah]
-is_a: GO:0030031 ! cell projection assembly
 is_a: GO:0032796 ! uropod organization
 intersection_of: GO:0022607 ! cellular component assembly
 intersection_of: results_in_assembly_of GO:0001931 ! uropod
@@ -239986,7 +239985,6 @@ synonym: "cilium axoneme biogenesis" RELATED [GOC:mah]
 synonym: "flagellar axoneme assembly" EXACT []
 synonym: "flagellum axoneme assembly" EXACT []
 is_a: GO:0001578 ! microtubule bundle formation
-is_a: GO:0030031 ! cell projection assembly
 intersection_of: GO:0022607 ! cellular component assembly
 intersection_of: results_in_assembly_of GO:0005930 ! axoneme
 relationship: part_of GO:0060271 ! cilium assembly
@@ -447724,7 +447722,6 @@ namespace: biological_process
 def: "Formation of dendrites, branched cellular projections (or cytoplasmic extension) that are extended from the surface of a dendritic immune cell, and which enable the cell to sample luminal pathogens and increase the surface area for antigen presentation to T cells." [CL:0000451, GOC:BHF, PMID:12200351]
 comment: Note that dendrites of dendritic cells should not be confused with neuronal cell dendrites, which process electrical signals.
 synonym: "dendritic extension" BROAD []
-is_a: GO:0030031 ! cell projection assembly
 intersection_of: GO:0022607 ! cellular component assembly
 intersection_of: results_in_assembly_of GO:0097511 ! dendritic cell dendrite
 created_by: paola
@@ -449424,7 +449421,6 @@ namespace: biological_process
 def: "The aggregation, arrangement and bonding together of a set of components to form a ruffle, a projection at the leading edge of a crawling cell; the protrusions are supported by a microfilament meshwork. The formation of ruffles (also called membrane ruffling) is thought to be controlled by a group of enzymes known as Rho GTPases, specifically RhoA, Rac1 and cdc42." [GOC:yaf, http:en.wikipedia.org/wiki/Membrane_ruffling, PMID:12556481]
 synonym: "membrane ruffle formation" EXACT []
 synonym: "membrane ruffling" EXACT []
-is_a: GO:0030031 ! cell projection assembly
 is_a: GO:0031529 ! ruffle organization
 intersection_of: GO:0022607 ! cellular component assembly
 intersection_of: results_in_assembly_of GO:0001726 ! ruffle
@@ -472011,6 +472007,16 @@ created_by: kchris
 creation_date: 2017-04-19T14:32:16Z
 
 [Term]
+id: GO:0120031
+name: plasma membrane bounded cell projection assembly
+namespace: biological_process
+def: "Formation of a prolongation or process extending and that is bounded by plasma membrane, e.g. a cilium, lamellipodium, or axon." [GOC:krc]
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0120025 ! plasma membrane bounded cell projection
+created_by: kchris
+creation_date: 2017-04-24T23:56:08Z

Delightfully, creating this new term (GO:0120031) with an equivalence axiom correctly classified a whole bunch of assembly terms for numerous plasma membrane bounded cell projections, more than were directly asserted under the term 'cell projection assembly'. I have removed directly asserted 'cell projection assembly' relationships for terms which now have an inferred relationship to 'plasma membrane bounded cell projection assembly'

**Comment by krchristie** [comment]
**Note**: The term 'substrate-dependent cell migration, cell extension' has this definition: "The formation of a cell surface protrusion, such as a lamellipodium or filopodium, at the leading edge of a migrating cell."  I am wondering if it should be
- a subclass of 'plasma membrane bounded cell projection assembly' (unless there are types of this that involve non-PM bound projections
- if there should be some relationship to indicate that 'filopodium assembly' and 'lamellipodioum assembly' are subclasses of this term. @ukemi - thoughts on if these subclass relationships should be made?

**Comment by ukemi** [comment]
I think the former is ok, but am unsure about the latter. Are they always assembled in the context of migration? One of the old distinction between migration and motility was that migration required a direction. So there are many cells that have lamellopodium- or filopodium- based motility that we wouldn't have considered migratory.

**Comment by krchristie** [comment]
I have manually asserted that 'substrate-dependent cell migration, cell extension' is a type of 'plasma membrane bounded cell projection assembly' since there isn't a specific term for the type of projection it refers to to make a logical definition with.

I have not made relationships between this term and the other terms 'filopodium assembly' and 'lamellipodioum assembly' 

name: substrate-dependent cell migration, cell extension
 namespace: biological_process
 def: "The formation of a cell surface protrusion, such as a lamellipodium or filopodium, at the leading edge of a migrating cell." [ISBN:0815316194, PMID:11944043, PMID:14657486]
 synonym: "substrate-bound cell migration, cell extension" EXACT [GOC:curators]
-is_a: GO:0030031 ! cell projection assembly
+is_a: GO:0120031 ! plasma membrane bounded cell projection assembly
 relationship: part_of GO:0006929 ! substrate-dependent cell migration

**Comment by krchristie** [comment]
@ukemi, I have another question for you. This term 'pial surface process extension' is currently classified under 'cell projection assembly', but it's pretty clear that this is occurring in brain and thus is a PM bounded cell projection assembly, so I have asserted that relationship.

- May I also rename it? It seems like it is named backwards. Reading this term name, I would have thought that this was an extension coming from the pial surface. However, looking at the existing definition and also the cited review, it is actually exactly the opposite. Something like 'Extension of leading cell process to pial surface' seems like a more accurate name.

<pre>[Term]
id: GO:0021803
name: pial surface process extension
namespace: biological_process
def: "The extension of a long process to the pial surface as a cell leaves the ventricular zone." [GO_REF:0000021, GOC:cls, GOC:dgh, GOC:dph, GOC:jid, GOC:mtg_15jun06, PMID:12626695]
comment: This term was added by GO_REF:0000021.
is_a: GO:0030031 ! cell projection assembly
relationship: part_of GO:0021802 ! somal translocation</pre>

**Comment by krchristie** [comment]
Added these three new regulation terms:

[Term]
+id: GO:0120032
+name: regulation of plasma membrane bounded cell projection assembly
+namespace: biological_process
+def: "Any process that modulates the rate, frequency, or extent of plasma membrane bounded cell projection assembly." [GOC:krc]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: regulates GO:0120031 ! plasma membrane bounded cell projection assembly
+created_by: kchris
+creation_date: 2017-04-26T04:27:04Z
+
+[Term]
+id: GO:0120033
+name: negative regulation of plasma membrane bounded cell projection assembly
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of plasma membrane bounded cell projection assembly." [GOC:krc]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: negatively_regulates GO:0120031 ! plasma membrane bounded cell projection assembly
+created_by: kchris
+creation_date: 2017-04-26T04:34:31Z
+
+[Term]
+id: GO:0120034
+name: positive regulation of plasma membrane bounded cell projection assembly
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of plasma membrane bounded cell projection assembly." [GOC:krc]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: positively_regulates GO:0120031 ! plasma membrane bounded cell projection assembly
+created_by: kchris
+creation_date: 2017-04-26T04:34:45Z

**Comment by krchristie** [comment]
still need to propagate the PM bounded cell projection terms to:

- [ ] cell projection organization
- [ ] cell projection size

**Comment by ukemi** [comment]
Hi @krchristie . The general rule I use for term names is to use the one that you think most people in the field would use. I usually determine this by looking in this order: at the original paper for the term if there is a reference, at papers that were used to annotate gene products with the term and through literature and web searches.

**Comment by krchristie** [comment]
Hi @ukemi . Having read the paper that is cited for this term, I am confident that my proposed name is an improvement over the existing one. I was actually trying to see if I could come up with a name for a CC term for the cell projection, so I could use a logical definition. I think we could call it 'leading cell process terminating at pial surface', but then I wasn't sure if it's really worth it since neither 'pial surface process extension' or the process that it's a part of: 'somal translocation', are used in any annotations. So, for the moment, I'm going to change the name of 'pial surface process extension' since it seems actively misleading, but won't create a CC term for the process, though if you think I should create the CC term in order to make a logical def, let me know and I will.

**Comment by krchristie** [comment]
two new terms:

 [Term]
+id: GO:0120035
+name: regulation of plasma membrane bounded cell projection organization
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of a process involved in the formation, arrangement of constituent parts, or disassembly of plasma membrane bounded cell projections." [GOC:krc]
+is_a: GO:0031344 ! regulation of cell projection organization
+intersection_of: GO:0008150 ! biological_process
+intersection_of: regulates GO:0120036 ! plasma membrane bounded cell projection organization
+created_by: kchris
+creation_date: 2017-04-26T16:02:06Z
+
+[Term]
+id: GO:0120036
+name: plasma membrane bounded cell projection organization
+namespace: biological_process
+def: "A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a plasma membrane bounded prolongation or process extending from a cell, e.g. a cilium or axon." [GOC:krc]
+is_a: GO:0030030 ! cell projection organization
+intersection_of: GO:0016043 ! cellular component organization
+intersection_of: results_in_organization_of GO:0120036 ! plasma membrane bounded cell projection organization
+created_by: kchris
+creation_date: 2017-04-26T16:07:02Z

**Comment by krchristie** [comment]
added a term for 'plasma membrane bounded cell projection part' and am waiting to see what child terms of 'cell projection part' are logically propagated to be under the new more specific term, at least in AmiGO, if not visible in Protege. Here are the changes:

https://github.com/geneontology/go-ontology/pull/13441/files

**Comment by krchristie** [comment]
fixing some more child terms under 'cell projection organization' to be under 'plasma membrane bound cell projection organization'

Also added new term for 'plasma membrane bounded cell morphogenesis'

changes here:
https://github.com/geneontology/go-ontology/pull/13444/files

**Comment by krchristie** [comment]
While checking to see if this is finished, I noticed that 'deep fiber' is still listed as a 'cell projection part', but it is part of the 'oral apparatus' which I have moved to not be a type of 'cell projection' since only part of the 'oral apparatus' is a cell projection. I am going to remove the 'cell projection part' parentage from 'deep fiber', but it will still have is_a parentage under 'cytoskeletal part' so this is a simple change.
