### ISSUE TITLE
TPV GO:0000506	glycosylphosphatidylinositol-N-acetylglucosaminyltransferase (GPI-GnT) complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13292]
GO:0000506	glycosylphosphatidylinositol-N-acetylglucosaminyltransferase (GPI-GnT) complex
An enzyme complex that catalyzes the transfer of GlcNAc from UDP-GlcNAc to an acceptor phosphatidylinositol, the first step in the production of GPI anchors for cell surface proteins. The complex contains PIG-A, PIG-C, PIG-H, PIG-Q, PIG-P, and DPM2 in human, and Eri1p, Gpi1p, Gpi2p, Gpi15p, Gpi19p, and Spt14p in budding yeast. 

has been made a child of
GO:0072546 ER membrane protein complex

this is a specific ER membrane protin complex  *called*   ER membrane protein complex
not a general ER membrane protein complex term.

A transmembrane protein complex that is involved in protein folding in the endoplasmic reticulum. In S. cerevisiae, it has six members: EMC1, EMC2, AIM27, EMC4, KRE27, and EMC6.

**Comment by ukemi** [comment]
Added an activity and made it part of the ER membrane. Let me know if this is not ok:

 synonym: "GPI-GlcNAc transferase complex" EXACT []
 synonym: "GPI-GnT complex" EXACT []
 synonym: "GPI-N-acetylglucosaminyltransferase complex" EXACT []
-is_a: GO:0072546 ! ER membrane protein complex
+relationship: capable_of GO:0008194 ! UDP-glycosyltransferase activity
+relationship: part_of GO:0005789 ! endoplasmic reticulum membrane

**Comment by ValWood** [comment]
looks good.
v
