### ISSUE TITLE
NTR: Extrasynaptic Membrane

### ISSUE THREAD

**Issue by cross12tamu** [geneontology/go-ontology#13306]
**Potential GO term name:** Extrasynaptic Membrane

**Definition:** An area of the dendritic or somatic membrane that is perisynaptic or distal to the synapse in which presynaptic release of neurotransmitters do not significantly affect signaling.

**Aspect:** Cellular Component

**Relationships:** Parent term would be Plasma Membrane Region

**References:**
17023503
16162835
15542076 
9464994
14627650

**Comment by jimhu-tamu** [comment]
I suspect this is a CACAO request.

**Comment by ukemi** [comment]
@dosumis  Any comments, since this is is in the synapse realm?

**Comment by ukemi** [comment]
These kinds of terms are generally hard to maintain. They are equivalent to creating classes like nucleus and then a term like 'the rest of the cell'. Then any time you want to add another component it would need to be a child of 'the rest of the cell'. So although this request doesn't mean exactly (anything that is not in the synaptic membrane), it is along the same vein.

**Comment by jimhu-tamu** [comment]
I understand the problem @ukemi raises, but with my limited knowledge of neurobiology plus scanning a few abstracts, it appears that various cells in neurons do have distinct classes of receptors that evolved to act either in the synaptic membrane (GO:0097060) or outside the synaptic region. It seems to me that this is a place where NOT would be useful, but can't be used under our current model for what a NOT annotation is.

Note also that plasma membrane region (GO:0098590) is a do not annotate term. 

I don't like Curtis' definition, though. Can this be modeled on GO:0005576 extracellular region?

**Comment by dosumis** [comment]
IIRC the terms 'extrasynaptic membrane' and 'perisynaptic membrane' are generally used to refer to parts of the presynapse that are not involved in release - not to the whole PM apart from the synaptic membrane.

After discussion, the synapse group decided not to add these but I don't recall the reasons.   We probably have the discussion on some tickets.  @pimmelorus may remember details.

**Comment by dosumis** [comment]
BTW - don't like the NOT solution here. Very hard to do anything useful with the resulting annotation.

**Comment by pgaudet** [comment]
Nobody could find a good definition. Closing.
