### ISSUE TITLE
NTR: Extrasynaptic transmission, GABAergic

### ISSUE THREAD

**Issue by cross12tamu** [geneontology/go-ontology#13307]
**Potential GO Term Name:** Extrasynaptic transmission, GABAergic

**Definition:** The tonic, non-desensitizing activation of extrasynaptic GABA(A)  receptors through binding of ambient gamma-aminobutyric acid present in the extracellular fluid.

**Aspect:** Biological Process

**Relationships:** Parent Term: GABA receptor activity

**References:**
17023503
16162835
15542076 
9464994
14627650

**Comment by jimhu-tamu** [comment]
Looks like a possible CACAO request.

**Comment by ukemi** [comment]
@dosumis  another synapse-related term.

**Comment by raymond91125** [comment]
Proposal
Term name: Extrasynaptic GABA receptor activity
Definition: GABA receptor activity that occurs remotely from a synapse.
is_a GABA receptor activity
References: PMID 23038269, PMID 9364051
Note: I don't believe SynGO covers this particular aspect. It can be mediated by both GABA-A and GABA-B receptors.

**Comment by pgaudet** [comment]
Although there are exceptions, our guidelines state that we should no add cellular component information in MF terms, see 
http://wiki.geneontology.org/index.php/Guidelines_for_new_Molecular_Functions. 

Based on the definition you propose, it doesn't seem to be a different *activity* compared to the parent 'GABA receptor activity'.

@cross12tamu was asking for a BP term, but the proposed definition looks like a MF, since it's describing a binding event. 
Unless we have a reply from @cross12tamu we can probably close this one - the CACAO annotations are done by students, 4 years later they probably moved on. 

Thanks, Pascale

**Comment by dosumis** [comment]
Agree should not be MF.  We should have the process term though (Extrasynaptic transmission, GABAergic) if not already added.

**Comment by pgaudet** [comment]
This is what we currently have: 

<img width="302" alt="image" src="https://user-images.githubusercontent.com/4782928/108977129-855c9880-7688-11eb-956a-a72acc4db645.png">

- I assume 'extrasynaptic transmission' should not go under 'synaptic transmission'; the next level parent is 'cell-cell signaling'
- how do you define 'extrasynaptic transmission',  'signaling that occurs outside a synapse?' it would be nice ot have a 'positive' definition, if possible. 
- We dont have a general term for 'GABA signaling'; would it be needed? 

Thanks, Pascale

**Comment by dosumis** [comment]
I think cell-cel signalling is fine as parent.  

How about this as a def:

"Activation of extrasynaptic GABA receptors in neurons through binding of ambient gamma-aminobutyric acid present in the extracellular fluid."

@raymond91125 does this work for your use cases?

**Comment by raymond91125** [comment]
@dosumis I think it works. It is not always clear what the 'signalling' cell is but I guess there has to be some cell that makes the GABA.

**Comment by dosumis** [comment]
Yeh - think reasonable to keep vague what the signalling cell is - e.g. leakage from synapses vs extrasynaptic secretion.  Assume this will vary..

**Comment by raymond91125** [comment]
How about
Term name: Extrasynaptic signalling via GABA
Definition: Activation of extrasynaptic GABA receptors in neurons through binding of ambient gamma-aminobutyric acid present in the extracellular fluid.
is_a cell-cell signalling
References: PMID 23038269, PMID 9364051

**Comment by pgaudet** [comment]
The definition sounds like a MF. Maybe we can base the definition on that of the sibling 'synaptic signaling' = "Cell-cell signaling to, from or within a synapse." ; maybe "Cell-cell signaling that starts with the activation of extrasynaptic GABA receptors in neurons through binding of ambient gamma-aminobutyric acid present in the extracellular fluid.

What do you think ?

**Comment by raymond91125** [comment]
Is this logical definition correct?
'cell-cell signaling' and ('process has causal agent' some 'gamma-aminobutyric acid zwitterion') and ('occurs in' some 'perisynaptic space')
@pgaudet @dosumis

**Comment by pgaudet** [comment]
GO ontology call - do not use 'process has causal agent'  - or 'occurs in' as a way to distinguish a pathway

Can you also LD to 'GO:0007214 gamma-aminobutyric acid signaling pathway' (GABA signaling pathway)
'cell-cell signaling' and 'starts with' some GABA receptor activity 

Right now we cannot have a LD for the extrasynaptic child.

**Comment by raymond91125** [comment]
GO:0007214 is presently a child of G protein-coupled receptor signaling pathway and that is incorrect. Only GABAb is G protein-coupled.
PMID:18790874 "γ-Aminobutyric acid (GABA1), the major inhibitory neurotransmitter in the brain, exerts its action via ionotropic GABAA and metabotropic GABAB receptors."

Thus I propose that we remove this relationship but add extrasynaptic signaling via GABA is_a gamma-aminobutyric acid signaling pathway
