### ISSUE TITLE
incorrect owldef for noradrenergic synapse

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13309]
currently equiv to 

```
[Term]
id: GO:0098691
name: dopaminergic synapse
namespace: cellular_component
def: "A synapse that uses dopamine as a neurotransmitter." [GOC:dos]
subset: goslim_synapse
is_a: GO:0045202 ! synapse
intersection_of: GO:0045202 ! synapse
intersection_of: capable_of GO:0001963 ! synaptic transmission, dopaminergic
created_by: dos
creation_date: 2017-03-07T14:51:52Z
```

**Comment by ukemi** [comment]
We removed the incorrect logical def. To make a logical def for this term, it requires the addition of the corresponding process.

**Comment by pgaudet** [comment]
Hi @ukemi The logical definition for GO:0098691 is 

synapse
 and ('capable of' some 'synaptic transmission, dopaminergic')

What process needed to be added ' Can this be closed ? 

Thanks, Pascale

**Comment by dosumis** [comment]
> GO:0098691 is
> synapse and ('capable of' some 'synaptic transmission, dopaminergic')

That's correct
> What process needed to be added ' Can this be closed ?

'synaptic transmission, noradrenergic'  for logical def for 'noradrenergic synapse'

**Comment by pgaudet** [comment]
'synaptic transmission, noradrenergic'
has logical definition: 

synapse
 and ('capable of' some 'synaptic transmission, noradrenergic')

Close ? 

Thanks, Pascale

**Comment by dosumis** [comment]
Yeh.  Guess I fixed it & forgot to close.  Sorry.
