### ISSUE TITLE
 regulation of cytoplasmic translational fidelity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13304]
standard def 

child of
GO:0006450 regulation of translational fidelity

for
PMID:22768388

**Comment by pgaudet** [comment]
Hello, 

I added the term and kept the same logic as its parent, ie 
 GO:0006450 regulation of translational fidelity
is_a  GO:0006448 regulation of translational elongation

so I have done: 
regulation of cytoplasmic translational fidelity
is_a GO:1900247 regulation of cytoplasmic translational elongation

Thanks, Pascale
