### ISSUE TITLE
NTR: DNA methyltransferase complex

### ISSUE THREAD

**Issue by vhinard** [geneontology/go-ontology#13314]
Could I have this concept?

DNA methyltransferase complex
Child_of: GO:0034708 methyltransferase complex
Def: A multimeric protein complex involved in the methylation of specific nucleotides in DNA.

Thanks

**Comment by pgaudet** [comment]
Hello @vhinard 

I added this as a definition (based on the parent term:) "A protein complex that possesses DNA methyltransferase activity." Does that work ? 

Thanks, Pascale

**Comment by vhinard** [comment]
Hi @pgaudet,

That sounds perfect.
Thanks, Valérie
