### ISSUE TITLE
Is "GO:0045171 intercellular bridge" really extracellular? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13317]
"intercellular bridge" is defined as "A direct connection between the cytoplasm of two cells that is formed following the completion of cleavage furrow ingression during cell division. They are usually present only briefly prior to completion of cytokinesis. However, in some cases, such as the bridges between germ cells during their development, they become stabilised. "

Proteins annotated to "intercellular bridge" are otherwise found in the cytoplasm. I suggest making "intercellular bridge" a cell part. 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi Pascale -  there is already a discuss open this in OTR: intercellular bridge - extracellular region? #13181.

**Comment by pgaudet** [comment]
Thanks @hattrill  !
