### ISSUE TITLE
TPV GO:0032065 cortical protein anchoring

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13339]
Is a descendent of "cytoplasmic sequestering of protein"

This isn't always (or even usually? ) true. A cytoplasmic protein which is no longer cortically anchored can still remain in the cytoplasm, and does not necessarily go to another compartment.

suggest "maintenence of protein localization"?

v

**Comment by ValWood** [comment]
Also
	maintenance of protein location in cell cortex of cell tip
is not "sequestering"

**Comment by ValWood** [comment]
"protein retention in ER lumen"
also seems odd. This likely comes about because ER is part of cytoplasm. However  it is strange to call 
"protein retention in ER lumen"   "cytoplasmic sequestering" because the process is stopping protein moving to the Golgi (which is still part of cytpoplasm).

No idea how you would  resolve that...

**Comment by ValWood** [comment]
Probably for starters the definition of sequestering should be  extended. Sequestering is really only used for "temporary isolation" to prevent a process. The other terms are referring to the location  of action...

**Comment by mah11** [comment]
> cortical protein anchoring is_a cytoplasmic sequestering of protein .. isn't always true

I think the link is OK (except for possible caveat about sequestering def), because it says that a protein that is anchored is sequestered, i.e. stays in the cytoplasm.

> A cytoplasmic protein which is no longer cortically anchored can still remain in the cytoplasm, and does not necessarily go to another compartment.

This is true but not relevant to the is_a link. The link does not say anything about what happens to proteins that are not anchored.

I think the rest of your points do depend on whether the definition of "sequestering" is accurate and complete. Both the cell cortex of cell tip and ER retention cases seem to fit the current def. What should be changed?

**Comment by ValWood** [comment]
Whenever I have seen sequester used in cell biology it always used in the context "to remove from action". For example the 14-3-3 proteins sequester cdc25 in the cytoplasm when the DNA integrity checkpoints are activated.


Other examples:
...to bind, so as to make [a metal ion] unavailable in its normal form ...thereby lowering their effective concentration in solution. Compounds employed particularly for this purpose are called sequestering agents, or chelating agents.
.....The most likely explanation is that cytosolic proteins sequester actin, holding it in a form that is unable to polymerize.
....In biochemistry, sequestration is one means of reversibly inhibiting enzymes which depend on divalent metal cations (such as magnesium) for their activity.

The cortical anchoring is usually to attach proteins to the cell cortex as part of their normal activity (to  anchor microtubules etc).  I can't find an example where cortical anchoring is "sequestering".

So there are probably 2 issues:
1. The definition of "sequestering"
2. The use of "sequestering" in non-sequestering terms

**Comment by pgaudet** [comment]
Hello, 

As far as I can tell, the problem arises from the logical definition of 

cytoplasmic sequestering of protein: 
'maintenance of protein location'
 and ('occurs in' some cytoplasm)

Hence, any term that is a child of 'maintenance of protein location' and that occurs in a location that is a child of 'cytoplasm' has an inference that it is-a type 'cytoplasmic sequestering of protein'. 

@cmungall @dosumis 
Can I remove that logical definition ? 

Thanks, 

Pascale

**Comment by dosumis** [comment]
> Can I remove that logical definition ?

Yep. I agree it is too strong for the reason Val outlines (sequester = remove from action).  This might be a good logical definition pattern to use for 'anchoring'.

**Comment by ValWood** [comment]
above good logical definition pattern to use for 'sequestering' , not 'anchoring'

v

**Comment by pgaudet** [comment]
@ValWood 
It's not really a good definition because all maintenance becomes sequestering. Or is that what you wanted ? 

Pascale

**Comment by ValWood** [comment]
@dosumis  suggested to use
"Val outlines (sequester = remove from action). This might be a good logical definition pattern to use for 'anchoring'."

I think David meant that we use "remove from action" in the definition for sequestering.

Anchoring should not be a descendent of sequestering anywhere as it does not fit this definition.

v

**Comment by dosumis** [comment]
Think we're agreeing.    Removing the logical def should remove the problematic inferred classification.

**Comment by ValWood** [comment]
To clarify,  we have a new logical def for sequestering  which includes the clause"remove from action" ?

**Comment by pgaudet** [comment]
Hi Val,

Right now there is no new definition. I don't know if the clause "remove from action" is in the relations
@dosumis is there another way we could formulate the logical definition? 

Thanks, Pascale
