### ISSUE TITLE
Regulation terms for GO:0090594

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13336]
Could I please have regulation and positive and negative regulation for GO:0090594 inflammatory response to wounding.

Please add GOC references GOC:rph, GOC:BHF and GOC:BHF_miRNA.
Thanks,
Rachael.

**Comment by hdrabkin** [comment]
Hi Rachael;  any PMID's that could be used?

**Comment by rachhuntley** [comment]
Hi Harold,

Yes, sorry about that, I did it in a rush. I need positive regulation term for PMID:26022821.

Thanks,
Rachael.

**Comment by hdrabkin** [comment]
done
