### ISSUE TITLE
Ontology imports into Protege cause undesirable side effects

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13338]
Hi @cmungall 

@ukemi figured out that when RO is being imported into GO, and somehow also imports the relation between 'membrane' and 'cell part' which causes the taxon violation in viruses. 
We have seen this in other cases, but this being so high level, it has a lot of undesirable consequences. 

This is a big deal - how all viral component terms are being flagged. Is there something we can do so that the external ontologies don't change GO ? 

Thanks, Pascale

**Comment by ukemi** [comment]
A couple particulars:
membrane is asserted to be a 'cell part' in RO_import.owl. This incorrect relationship is being loaded.
protein complex is asserted to be a macromolecular complex in both GO and pr_import.owl. In this case the assertion is correct in both ontologies, but shows up as a duplicate.
