### ISSUE TITLE
formin-nucleated actin cable organization

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#13335]
a new term we could use, modeled on GO:0061572:

[Term]
id: GO:new
name: formin-nucleated actin cable organization
namespace: biological_process
def: "A process that results in the assembly, arrangement of constituent parts, or disassembly of a formin-nucleated actin cable." [GOC:mah]
is_a: GO:0061572 ! actin filament bundle organization
intersection_of: GO:0016043 ! cellular component organization
intersection_of: results_in_organization_of GO:0070648! formin-nucleated actin cable

and add link GO:0070649 ! formin-nucleated actin cable assembly is_a GO:new (manually or by reasoning)

**Comment by vanaukenk** [comment]
Hi @mah11 

Just to confirm, this is how the resulting term addition will look.  Is that correct?

GO:0061572 actin filament bundle organization
  is_a GO:new formin-nucleated actin cable organization
    is_a GO:0070649 formin-nucleated actin cable assembly

Thx.

**Comment by mah11** [comment]
yes, that looks fine

thanks :)
