### ISSUE TITLE
NTR: Reproduction of symbiont in host

### ISSUE THREAD

**Issue by connsears** [geneontology/go-ontology#13342]
Aspect: Biological process.
Definition: The production of new individuals that contain some portion of genetic material inherited from one or more parent organisms, occurring within the cells or tissues of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

Growth terms (such as GO:0044110, growth involved in symbiotic interaction) are defined as only the increase in size or mass of an organism, while development terms (such as GO:0044111, development involved in symbiotic interaction) encompass progression from one condition to another. Especially in bacterial pathogenesis, reproduction and reproductive processes are important aspects of the symbiotic interaction.

One (of many) possible references is PMID:23460907, as well as PMID:25713147.

@jimhu-tamu

**Comment by ukemi** [comment]
In general, I think a term like reproduction is at such a high level, it is not very useful for annotation. Almost everything can be considered a reproductive process if you go far enough. Is there a more specific process you can use?  @vanaukenk

**Comment by jimhu-tamu** [comment]
The choice of a high level term reproduction was deliberate based on parallel construction of other high level terms in the multi-organism branch, specifically 

GO:0044110 ! growth involved in symbiotic interaction and
GO:0044111 ! development involved in symbiotic interaction

based on the comment on those terms related to prior term obsoletion for GO:0052171

What we want is a substitute for GO:0044117 ! growth of symbiont in host where "growth" has the meaning used by microbiologists for increase in number of symbionts. But it seemed like there might be host-symbiont processes where non-microbiologists would also need to distinguish growth and reproduction in the broad sense. For example, [Trypanosomes](https://en.wikipedia.org/wiki/Trypanosoma_brucei) reproduce both sexually and asexually in their hosts, which can be either an insect vector or a mammalian host that gets a disease. In the insect vector we would not call this a pathogenic process (I think). 

It might be appropriate to make reproduction of symbiont in host a parent for both asexual and sexual reproduction in host child terms.

This may also be something that should be post-composed via LEGO/Noctua, but we don't support that for CACAO. I'm going to open a separate issue related to that as it could be a summer project for us.
