### ISSUE TITLE
ro_import has stale GO axioms

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13340]
E.g. membrane SubClassOf cell part

@dosumis and I put a small subset of GO in RO many years ago in order to provide domain and range constraints for synaptic relations, but this preceded when we had good import mechanisms. This is obviously problematic

May be related to #13332

**Comment by cmungall** [comment]
Note: debugging this is confusing due to CARO and UBERON 'cell part' classes, Protege gets confused if classes have the same label

https://github.com/obophenotype/uberon/issues/1314

**Comment by ukemi** [comment]
#13338 
This issue is not restricted to ro_import.owl. It is why we see changes to ontologies other that go_edit.obo after some work in protege.

**Comment by dosumis** [comment]
> Note: debugging this is confusing due to CARO and UBERON 'cell part' classes, Protege gets confused if classes have the same label

GO:'cellular component' is broader than 'cell part' - e.g. includes cellular scale ECM components.  So, should be more general class in Uberon/CARO.
