### ISSUE TITLE
Taxon constraint for GO:0001944

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#13343]
I came across some annotations in TAIR to vasculature development
http://amigo.geneontology.org/amigo/term/GO:0001944
As a result these genes are also mapped to cardiovascular development.

@tberardini  found that  the term is linked by logical def to the uberon term for vasculature, which effectively restricts it to animals
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of UBERON:0002049 ! vasculature

this suggests that there should be a taxon restriction placed on the term itself.

The proper term for these annotations is
GO:0010087 and I will fix those in TAIR but I want to be sure that other annotations of plants to these terms are caught.

**Comment by tberardini** [comment]
These plant annotations didn't come up in any of the GO QC reports from jenkins.  I think they should have appeared as taxon violations.  Which makes me wonder how taxon constraints are applied to terms linked to external ontologies.  Can someone clarify? @ukemi?  @cmungall?

**Comment by jimhu-tamu** [comment]
related to #13338?

**Comment by tberardini** [comment]
@jimhu-tamu - I don't think it's related to #13338. This issue is more related to the lack of reported taxon violations rather than too many inappropriate ones.

**Comment by cmungall** [comment]
looks like we're not importing the uberon taxon axioms. This all comes down to imports being hard to manage,

**Comment by tberardini** [comment]
> looks like we're not importing the uberon taxon axioms. 

Which means we're not taking full advantage of the info in the external ontologies, no?  Do you think that this is something that will be addressed fairly soon or should we think about adding taxon restrictions manually into GO for situations like this?

**Comment by cmungall** [comment]
Working on a fix...

**Comment by vanaukenk** [comment]
@lreiser @tberardini @cmungall 

Just checking on this ticket, since it was assigned to me.  It sounds like between the TAIR annotation updates and the fix to Uberon taxon imports, this issue will be addressed.

Please let me know if there's anything that still needs to be done manually in the ontology.

**Comment by tberardini** [comment]
Seems to me like there's no need to do anything manually after the fix that Chris implemented.

**Comment by lreiser** [comment]
Think its all good. I cleaned up our annotations. Checking AmiGO ours were the only annotations extant for the Viridiplantae...
