### ISSUE TITLE
tpv dynactin complex -> actin cytoskeleton

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13347]
dynactin complex  part_of "actin cytoskeleton"
this isn't always true.

![tpv](https://cloud.githubusercontent.com/assets/7359272/24954713/57f4b6cc-1f78-11e7-8ef3-2539ecd2ed3c.jpg)

**Comment by ValWood** [comment]
sometimes dynactin is actin cytoskeleton associated:
![actin](https://cloud.githubusercontent.com/assets/7359272/24954741/816e3fa0-1f78-11e7-800d-cc3d659e606b.jpg)


but sometimes not:
![not actin](https://cloud.githubusercontent.com/assets/7359272/24954769/9d29ae14-1f78-11e7-833f-9d9b02806d12.jpg)

**Comment by ValWood** [comment]
Revised def suggestion:

Dynactin or "Dynein activator complex" is a multi-subunit protein found in eukaryotic cells that aids in bidirectional intracellular transport by binding to microtubules and dynein (or/and kinesin-2????) and linking them to an organelle or vesicle to be transported (derived from https://en.wikipedia.org/wiki/Dynactin). Also has a role in anchoring cytoplasmic microtubules to the cell cortex  during meiosis (C. elegans PMID: 26133383 fission yeast PMID:25736293 ), and in the orientation of the mitotic spindle in higher eukaryotes (PMID: 25669897).

**Comment by ukemi** [comment]
But how do you define the complex? Isn't the bottom figure a different complex?

**Comment by ValWood** [comment]
Well that one *could* be different, I was just trying to find a representation which interacted with microtubules.

The pombe dynactin (which does not interact with actin in this context) comprises
ssm4 p150-Glued
mug1 Dynamitin 
arp1 (actin-like protein, which forms that little  arp1 actin-filament)
(these appear to be the core conserved components, because these are all present in the s. cerevisiae dynactin used to define the term)

So the actin related protein, is still present in the core complex which doesn't interact with the actin cytoskeleton...

**Comment by ValWood** [comment]
Oh unless the connection to the cell cortex  in pombe is also via actin.... that  would be possible...

**Comment by ValWood** [comment]
There are a few papers on this now and no actin in the model so far...


![model](https://cloud.githubusercontent.com/assets/7359272/24957665/5544ea1c-1f84-11e7-9e79-228a3c72d739.jpg)


they seem to think that num1/mcp5 directly connects to the cortex...

**Comment by ValWood** [comment]
I'll close this. I can't find any info about actin involvement, but I can't rule  that it connects to actin. I guess this is the most likely scenario!
