### ISSUE TITLE
Questions transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13356]
Hello, 

I have done a few transport issues lately and I noticed a few inconsistencies. I'd like to have @dosumis ' opinion on these. 

1. Inconsistencies between logical/ textual definitions and term names: 
Eg: mitochondrial citrate transmembrane transport
Textual def: The directed movement of citrate, 2-hydroxy-1,2,3-propanetricarboyxlate, from one side of a membrane to the other into, out of or within a mitochondrion.
Logical def: 
transport
 and ('transports or maintains localization of' some 'citrate(3-)')
 and ('results in transport across' some membrane)
 and ('results in transport to from or in' some mitochondrion)

 therefore, not *within*

2. "Import" is not specifically defined, but is sounds like it's transmembrane by the definition of some terms. For example: 
GO:0043090 amino acid import: The directed movement of amino acids into a cell or organelle.

Eg: 'protein import into mitochondrial outer membrane' has the following equivalence axiom: 

'protein import'
 and ('occurs in' some cytoplasm)
 and ('has target end location' some 'mitochondrial outer membrane')

From the textual definition, I would think 'import' should not 'occur' in an organelle, but have 'has target start location' and 'has target end location', is this right ?  

3. Inconsistent oxidation states in logical definitions: 
see https://en.wikipedia.org/wiki/List_of_oxidation_states_of_the_elements 
D-aspartate import across plasma membrane -> (imports some 'D-aspartate(2-)') 
malate import across plasma membrane ->  (imports some 'malate(2-)')
malonic acid import across plasma membrane  (imports some 'malonic acid')
calcium ion import across plasma membrane ->  (imports some 'calcium cation') OK  (generic 'calcium cation)')
sodium ion import across plasma membrane ->  (imports some 'sodium(1+)') 
potassium ion import across plasma membrane -> ('transports or maintains localization of' some 'potassium(1+

4. Should "import of 'x'" be marked as 'do not annotate'? ie if you don't know the 'from' and 'to' localizations of the transported substance, the annotation should be to 'x transmembrane transport', shouldn't it? (note that x transmembrane transport does not always exist)

This affects the follwoing terms, that could be renamed x transmembrane transport: 
 
GO:0034226 	lysine import 	
GO:0035376 	sterol import 	
GO:0090468 	valine import 	
GO:0090478 	serine import 	
GO:1901689 	biotin import 	
GO:0017038 	protein import 	
GO:0036233 	glycine import 	
GO:0046323 	glucose import 	
GO:0051170 	nuclear import 	
GO:0060356 	leucine import 	
GO:1902025 	nitrate import 	
GO:0032445 	fructose import 	
GO:0061461 	L-lysine import 	
GO:0090467 	arginine import 	
GO:0090479 	L-serine import 	
GO:0097286 	iron ion import 	
GO:0071939 	vitamin A import 	
GO:0090466 	histidine import 	
GO:0098657 	import into cell 	
GO:1905122 	polyamine import 	
GO:0015677 	copper ion import 	
GO:0020028 	hemoglobin import 	
GO:0036232 	L-tyrosine import 	
GO:0043090 	amino acid import 	
GO:0043091 	L-arginine import 	
GO:0044690 	methionine import 	
GO:0090469 	asparagine import 	
GO:0090476 	isoleucine import 	
GO:0097369 	sodium ion import 	
GO:0033216 	ferric iron import 	
GO:0036229 	L-glutamine import 	
GO:0036231 	L-threonine import 	
GO:0051938 	L-glutamate import 	
GO:0061460 	L-histidine import 	
GO:0070508 	cholesterol import 	
GO:0070509 	calcium ion import 	
GO:0070779 	D-aspartate import 	
GO:0090452 	lithium ion import 	
GO:0043092 	L-amino acid import 	
GO:0070627 	ferrous iron import 	
GO:0090477 	L-isoleucine import 	
GO:1901688 	pantothenate import 	
GO:1901690 	dethiobiotin import 	
GO:1902067 	silicic acid import 	
GO:0010107 	potassium ion import 

5. Inconsistencies in the axes of classification of transport. In different areas of the ontology these classifications differ. We have
- by organelle 
- by direction
- by type of molecule (protein, RNA, carbohydrate, amino acid, ion, cation, etc)

Examples of inconsistencies: 
For plasma membrane transport we have 
- amino acid import across plasma membrane
-- each aa

But no generic nucleotide import: these are directly under plasma membrane transport 
- adenine import across plasma membrane
- guanine, etc

For mitochondrial import we have 
- mitochondrial pyrimidine nucleotide import (no children) 

- inorganic anion import across plasma membrane exists, but for mitochondrial transport all ions are directly under mitochondrial transport

How do we want to classify to classify transport ? 

6. Inconsistent term names: 
- transmembrane glycine transport from cytosol to mitochondrion (=import into mitochondrion?) 
- mitochondrial pyrimidine nucleotide import
- histidine transmembrane import into vacuole 
- calcium ion transport from cytosol to endoplasmic reticulum (=import into ER?) 

Is there a convention we'd like to use in the order of the words and in the use if import versus transmembrane transport? 

Thanks, 

Pascale

**Comment by pgaudet** [comment]
Another issue I cam across is that 'import_across_plasma_membrane.yaml' and 'transmembrane_import_into_cell.yaml' have the same logical definition: 

https://github.com/geneontology/design_patterns/blob/master/validated_patterns/import_across_plasma_membrane.yaml
equivalentTo: 
  text: "'transport' 
  	and ('has target start location' some 'extracellular region') 
  	and ('has target end location' some 'cytosol') 
  	and ('results in transport across' some 'plasma membrane') 
  	and ('imports' some %s)"


https://github.com/geneontology/design_patterns/blob/master/validated_patterns/transmembrane_import_into_cell.yaml

equivalentTo: 
  text: "'transport' 
  and ('has target start location' some 'extracellular region') 
  and ('has target end location' some 'cytosol') 
  and ('results in transport across' some 'plasma membrane') 
  and ('imports' some %s)"

Since I merged most of the terms into 'import across plasma membrane', we can probably obsolete the '/transmembrane_import_into_cell.yaml' pattern ? 
@dosumis 

Thanks, Pascale

**Comment by pgaudet** [comment]
no, the x import' terms are still there.

**Comment by RLovering** [comment]
did you consider that not all import occurs via transmembrane? ie endocytosis leads to import but not transmembrane import?

Sorry if you had covered this

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 

Thanks for the comment. My plan is to try to divide transport into transmembrane and endocytosis. I don't know of other mechanisms (well, except perhaps 'carriers' we we have defined as a function). 

Does that sound correct? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+ transepithelial transport

**Comment by RLovering** [comment]
OK this sounds like a very good idea, sorry it took me a long time to write a response on the other ticket.

**Comment by ukemi** [comment]
We als need to keep in mind import into the nucleus. Technically there is no membrane crossed.

**Comment by pgaudet** [comment]
Closing - this is now divided into several tickets: 
https://github.com/geneontology/go-ontology/issues/13679
https://github.com/geneontology/go-ontology/issues/15022
https://github.com/geneontology/go-ontology/issues/14492 (MF)
