### ISSUE TITLE
ntr:basolateral protein secretion

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13350]
Could I have:

basolateral protein secretion
def:The controlled release of proteins from a cell at the sides which interface adjacent cells and near the base.
PMID:27404358

Is_a GO:0009306 protein secretion

And:

regulation of basement membrane organization
def:Any process that modulates the frequency, rate or extent of the assembly, disassembly or arrangement of constituent parts of the basement membrane.
PMID:27404358

regulates GO:0071711 basement membrane organization

**Comment by vanaukenk** [comment]
@hattrill 
These two terms have now been added to the ontology:

id: GO:0110010
name: basolateral protein secretion

id: GO:0110011
name: regulation of basement membrane organization
