### ISSUE TITLE
MP: actomyosin contractile ring organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13379]
"actomyosin contractile ring organization"
is not a descendant of cytokinesis?  is there another context?

**Comment by mah11** [comment]
Maybe check with @hattrill about whether the actomyosin rings in insect oocyte ring canals count as "contractile", and whether their formation is or isn't "cytokinesis" (since it doesn't go on to completely separate cells). I remember just enough to ask the question, but not to answer it.

**Comment by ValWood** [comment]
Actually I see we haven't actually used this term, only descendants (I thought we had).
If it isn't always cytokinetic it might be a good term to "add not for direct annotation".
I will block it locally for PomBase.

**Comment by pgaudet** [comment]
Waiting for @hattrill to comment. I really don' know much about this area. 

But if 'actomyosin contractile ring organization' is part of cytokinesis, then we should have a look at the following terms: 
- GO:2000708 myosin filament organization involved in cytokinetic actomyosin contractile ring assembly
- GO:1903475	 mitotic actomyosin contractile ring assembly; 
presumably the 'mitotic' term refers to the cytokinesis part of mitosis ? 

There are also a few others that are hard for me to tell apart: 
- GO:1903117	regulation of actin filament organization involved in cytokinetic actomyosin contractile ring assembly
- GO:1903480 regulation of actin filament organization involved in mitotic actomyosin contractile ring assembly

Pascale

**Comment by ValWood** [comment]
Most (for pombe all)  annotation currently is mitotic cytokinesis. I don't know much about the process of cytokinesis during gamete formation or sporulation, but it seems to be quite different (at least for yeast).  It seems that in yeast cytokinesis  (i.e. cytoplasmic division) is actually "prospore membrane closure", which is quite different from the cytokinetic ring based closure and septation (there does not even seem to be anything for prospore membrane closure in GO so its probably quite unstudied generally). 
I don't think we have any info for "meiotic cytokinesis" at all in pombe, and I'm not sure  how much if any, of the same mechanisms are involved, it seems  quite divergent. It would be useful if there was a mitotic version of every existing cytokinesis term, because for pombe that is what we mean.

**Comment by ValWood** [comment]
I found this for budding yeast:

https://sites.google.com/a/stonybrook.edu/aneiman/a-sporulation-primer-models-and-micrographs/how-to-make-a-spore

It says
"After closure the prospore is now an autonomous cell, thus prospore membrane closure is equivalent to cytokinesis."

A previous step is

Prospore membrane expansion is driven by the continued delivery and fusion of secretory vesicles. Growth in the proper shape and direction is maintained by two multiprotein complexes; one that contains intermediate filament proteins called Septins (3), and a second termed the leading edge complex (4).

There is no mention of a  cytokinetic ring in this process, it involves a septin ring. All of the cytoplasmic separation seems to occur after meiosis II.
It would be useful if higher eukaryotic people could comment on cytokinesis during gamete formation. I don't know how similar or different this is...

This might  be mini-project territory.....

One thing  which might help would be to check that  we have mitotic versions of the existing terms. This might prevent mix up and necessary reannotation later on.

**Comment by pgaudet** [comment]
Do you mean *meiotic* versions of the terms ?

**Comment by hattrill** [comment]
The current model is that ring canals are a product of incomplete cytokinesis and are derived from arrested contractile rings.

So, the actomyosin rings in insect oocyte ring canals are not contractile but are derived from a contractile ring. These contractile rings are not part of cytokinesis as defined.

(...although "incomplete cytokinesis" seems to be a P term that needs to be added, I haven't got my head around where to locate a "when cell division isn't a division" term. Save that one for the morning ......)

**Comment by ValWood** [comment]
I mean mitotic here. As far as I know the context they have been used is  usually mitotic (and  for PomBase we would want mitotic terms). I don't think we should instantiate meiotic terms unless requested, because we don't know how similar or different  meiotic cytokinesis is, and if parallel terms will be required at all...

I will have a quick check  if  PomBase has used any terms which  do not specify mitotic.

**Comment by ValWood** [comment]
- [ ]  I think most terms have a mitotic counterpart, except
GO:1901901 regulation of protein localization to cell division site involved in cytokinesis
Could this be added?

- [ ]  This term could probably be obsoleted. Cytokinesis is not regulated transcriptionally, it is post transcriptionally regulated.

GO:1900414 regulation of cytokinesis by regulation of transcription from RNA polymerase II promoter

(It has no annotations)

**Comment by pgaudet** [comment]
Hi @ValWood 

If cytokinesis is not regulated transcriptionally, they should we also obsolete
- GO:1900405 	regulation of cell separation after cytokinesis by regulation of transcription from RNA polymerase II promoter 	
- GO:0100027 	regulation of cell separation after cytokinesis by transcription from RNA polymerase II promoter 

(0 annotations) 

Thanks, Pascale

**Comment by ValWood** [comment]
Yep, I think so...

**Comment by ukemi** [comment]
What about pseudocleavage in worms? Would this be via the contractile ring? @vanaukenk

**Comment by vanaukenk** [comment]
The pseudocleavage furrow in C. elegans is an actomyosin-based contractile ring, but a recent in-depth study of its organization/assembly highlights some mechanistic differences from formation of the cytokinetic ring.  

https://www.ncbi.nlm.nih.gov/pubmed/27719759

So, you can have actomyosin contractile ring formation outside of cytokinesis, and it looks like in the case of pseudocleavage this is a mechanistically different process from what happens during cytokinesis.  This would suggest, I think, that we need to have distinct terms for these BPs so we can be clear about which process we mean, i.e. make the distinction between those processes that are part_of cytokinesis vs part_of pseudocleavage or some other process.

**Comment by pgaudet** [comment]
@vanaukenk 
What would the other term be called ? "pseudocleavage furrow actomyosin contractile ring assembly/organization?

@vanaukenk @ValWood 
Do we need both assembly and organization ? (perhaps this is dictated by the structure of the GO?) 

Thanks, 

Pascale

**Comment by ValWood** [comment]
I think we need both
organization = assembly, arrangement, and disassembly
v

**Comment by ValWood** [comment]
No action required
