### ISSUE TITLE
microtubule anchoring at cell cortex of cell tip

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#13371]
[Term]
id: GO:new
name: microtubule anchoring at cell cortex of cell tip
namespace: biological_process
def: "Any process in which a microtubule is maintained in a specific location at the cell tip by attachment to the cell cortex." [GOC:mah, PMID:25736293]
is_a: GO:0034453 ! microtubule anchoring

(meant to request this in #13348 but forgot)

**Comment by hdrabkin** [comment]
Added GO:0106007
Closed
