### ISSUE TITLE
NTR: positive regulation of cilium beat frequency involved in ciliary motility

### ISSUE THREAD

**Issue by loganmccurry** [geneontology/go-ontology#13375]
GO: positive regulation of cilium beat frequency involved in ciliary motility
Definition: Any process that positively modulates the frequency of cilium beating involved in ciliary motility.
Aspect: Biological Process
Child term of GO:0060296 regulation of cilium beat frequency involved in ciliary motility
PMID:28035044 "A role for Gle1, a regulator of DEAD-box RNA helicases, at centrosomes and basal bodies" specifically Figure 4 in the organism Zebrafish.

I am a CACAO student, and our system does not allow for annotation extensions.

**Comment by krchristie** [comment]
Here's the new term:

[Term]
+id: GO:0120030
+name: positive regulation of cilium beat frequency involved in ciliary motility
+namespace: biological_process
+def: "Any process that activates or increases the frequency of cilium beating involved in ciliary motility." [PMID:28035044]
+is_a: GO:0060296 ! regulation of cilium beat frequency involved in ciliary motility
+created_by: kchris
+creation_date: 2017-04-19T14:32:16Z
