### ISSUE TITLE
mp  basic amino acid transmembrane export from vacuole

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13377]
GO:0034488	basic amino acid transmembrane export from vacuole
GO:0034490	basic amino acid transmembrane import into vacuole

should be is_a
GO:1990822 basic amino acid transmembrane transport

**Comment by pgaudet** [comment]
Hi @ValWood 

I opened another issue related to this: https://github.com/geneontology/go-ontology/issues/13356
I was wondering how transport should be classified, because this structure is not consistent throughout the ontology. 

When that's clarified I'll work on this. 

Thanks, Pascale

**Comment by ValWood** [comment]
yeah i realise there are issues. Just thought I would mention it because i couldn't remember what was covered by the existing tickets.
Correct logical defs will presumably sort these out.

**Comment by pgaudet** [comment]
I added the basic amino acid parent as an asserted class because the concept of acidic and basic amino acids is not in ChEBI. (I also did the same for acidic). 

Pascale
