### ISSUE TITLE
Generic phosphatase activity on specific phosphatidylinositol bisphosphates

### ISSUE THREAD

**Issue by lenov** [geneontology/go-ontology#13380]
Hello,

There is a term describing the dephosphorylation of generic PIP2:

GO:0034593 phosphatidylinositol bisphosphate phosphatase activity

Its children are all specific of a given PIP2 and specific of a given phosphatase activity, e.g.

GO:0016316 	phosphatidylinositol-3,4-bisphosphate 4-phosphatase activity
GO:0051800 	phosphatidylinositol-3,4-bisphosphate 3-phosphatase activity
etc.

In one of our projects, we identified an unknown phosphatidylinositol-3,4-bisphosphate activity. We do not know if it is a 4-phosphatase or a 3-phosphatase. I suggest the creation of the following terms

[Term]
id: GO:new
name: phosphatidylinositol-3,4-bisphosphate phosphatase activity
namespace: molecular function
def: "Catalysis of the reaction: 1-phosphatidyl-myo-inositol 3,4-bisphosphate + H2O = 1-phosphatidyl-1D-myo-inositol phosphate + phosphate"
is_a: GO:0034593 ! phosphatidylinositol bisphosphate phosphatase activity

And to move the following as children
GO:0016316 ! phosphatidylinositol-3,4-bisphosphate 4-phosphatase activity
GO:0051800 ! phosphatidylinositol-3,4-bisphosphate 3-phosphatase activity

[Term]
id: GO:new
name: phosphatidylinositol-3,5-bisphosphate phosphatase activity
namespace: molecular function
def: "Catalysis of the reaction: 1-phosphatidyl-myo-inositol 3,5-bisphosphate + H2O = 1-phosphatidyl-1D-myo-inositol phosphate + phosphate"
is_a: GO:0034593 ! phosphatidylinositol bisphosphate phosphatase activity

And to move the following as children
GO:0052629 ! phosphatidylinositol-3,5-bisphosphate 3-phosphatase activity
GO:0043813 ! phosphatidylinositol-3,5-bisphosphate 5-phosphatase activity

[Term]
id: GO:new
name: phosphatidylinositol-4,5-bisphosphate phosphatase activity
namespace: molecular function
def: "Catalysis of the reaction: 1-phosphatidyl-myo-inositol 4,5-bisphosphate + H2O = 1-phosphatidyl-1D-myo-inositol phosphate + phosphate"
is_a: GO:0034593 ! phosphatidylinositol bisphosphate phosphatase activity

And to move the following as children
GO:0004439 ! phosphatidylinositol-4,5-bisphosphate 5-phosphatase activity
GO:0034597 ! phosphatidylinositol-4,5-bisphosphate 4-phosphatase activity

**Comment by hdrabkin** [comment]
Hi, I'm preparing to work on this. It is customary that when requesting new terms, to supply  PMIDs supplied for the definitions.

**Comment by hdrabkin** [comment]
Have added these; done
