### ISSUE TITLE
Mitotic cell cycle - alt id for mitotic nuclear division

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13387]
GO:0000278 'mitotic cell cycle' [corrected this from original as copy-paste error]
has 
alt_id: GO:0007067

But this was the old id for 

GO:0140014 'mitotic nuclear division'

So, GO:0007067 should be made secondary for GO:0140014 'mitotic nuclear division'

and removed from 
GO:0007067 'mitotic nuclear division' 

We need to do a GO update tomorrow, so can you make this high priority.

**Comment by pgaudet** [comment]
Hi @hattrill 
GO:0007067 is the alt_id for GO:0000278 (mitotic cell cycle)
and I did create a new term that represents GO:0140014 'mitotic nuclear division'
The explanation is here: https://github.com/geneontology/go-ontology/issues/11709

So indeed some annotations were mapped 'up'. Is this not OK for you ? 

Thanks, Pascale

**Comment by hattrill** [comment]
The problem is that "mitotic nuclear division" was GO:0007067. Which means that we have to resolve the conflict in the database that we have the same name space with a different id and the same id as an alternative to something else.
I'll have to see if we can get round this somehow.

**Comment by hattrill** [comment]
Hi Pascale,
Leave it for now - I'm going to check with our developer - we've run into a couple of similar issues with complex edits like this before (mistakes and intentional). Hopefully she can make a work around now we know the lay-of-the-land.

Thanks, Helen

**Comment by krchristie** [comment]
A similar thing happened in in the merge of 'cilium assembly' and 'cilium morphogenesis' where the IDs got swapped in the sense that the ID that was kept as primary originally had the term name that became a synonym, and the new primary term name was originally associated with what became the alt_id. It would be really good to have some documentation for what is desired practice, and how to avoid the unintentional situations since @ukemi said it is trickier to do merges in Protege than it was in OBI-Edit.

**Comment by hattrill** [comment]
‘chromatin modification' was another one.

**Comment by pgaudet** [comment]
Hi @hattrill 

How did the release go? Should I close this ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi Pascale,

Leave it open for now. Our dev is currently running checks on the file and then we will work through the problems by some process - I hope.

It takes us a long time to do the update of the GO in chado - usually takes about a week as we check it, load it into a test instance and review the impact on existing data. If all goes well, we will load it into production chado on Thursday and I should know the outcome by Friday.

**Comment by pgaudet** [comment]
Hello @hattrill 
I am reassigning this to you - you can decide when it should be closed or let me know if I need to do something. 

Thanks, 
Pascale

**Comment by hattrill** [comment]
That's fine - think we're almost there!
Thanks,
Helen

**Comment by hattrill** [comment]
All fixed and fine!

**Comment by pgaudet** [comment]
:)
