### ISSUE TITLE
MP:  GO:0072453 signal transduction involved in G2 cell size control checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13381]
is not a descendant of "GO:0008361 regulation of cell size"

**Comment by ValWood** [comment]
These checkpoint  terms are places and  used mitotically

i.e
mitotic cell size control checkpoint
-signal transduction involved in cell size control
-- GO:0072453 signal transduction involved in G2 cell size control checkpoint


Could the defs make the "mitotic" part explicit? (I don't know if these checkpoints exist in mieosis, but we should be clear).

**Comment by pgaudet** [comment]
Hi @ValWood 

I added the relation you requested, and fixed the definitions on that model: 
"A signal transduction process that contributes to a cell size control checkpoint during mitosis." 

All changes are here: 
https://github.com/geneontology/go-ontology/compare/issue-13381?expand=1

If that works for you I'll complete the merge. 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale,

 I can't interpret the diffs very well, as I can't figure out which term they refer to so I am guessing. It would be useful if the term name showed up also.

I can't figure , for example why some of these terms have changed:

 def: "A signal transduction process that contributes to a DNA integrity checkpoint." [GOC:mah]
 intersection_of: GO:0035556 ! intracellular signal transduction
 intersection_of: part_of GO:0031570 ! DNA integrity checkpoint
-relationship: part_of GO:0031570 ! DNA integrity checkpoint

because these changes only refer to "cell size control checkpoints", not DNA integrity checkpoints or parent terms.

Could you double check  that this is correct?

Thanks

Val

**Comment by pgaudet** [comment]
Hi Val, 

I did some edits on the relations of the neighboring terms. The one you are looking at is ' signal transduction involved in DNA integrity checkpoint ' (I can tell by the definition). You are right, the diff truncates the file at inconvenient places for human readability. 

In any case, this change is removing a line that was already there in the logical definition, so there should be no impact on the ontology. 

I assume the rest was OK ? 
Thanks 
Pascale

**Comment by ValWood** [comment]
I'm sure it is. I wish I could read the diffs better ;).

**Comment by pgaudet** [comment]
me too !
