### ISSUE TITLE
NTR / ontology improvements: amyloid-beta complex hierarchy

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13388]
Bare with me, this is long...

In collaboration with @BarbaraCzub and Nigel Hooper (Uni Manchester - I don't know if he has a GH account to chime in, I will send him the link in an email anyway.)

We are trying to address the complicated nature of the different amyloid-beta complexes that result in the altered synaptic functions in Alzheimer's disease patients. I have curated the distinct dimers in the CP and they have been released (see xrefs for suggested GO:NEW1 below). The oligomers are combined in one CP entry (see xrefs for suggested GO:NEW2 below [human and mouse entries], ready for next IntAct release, ETA mid/end of May) as I cannot distinguish different tertiary structures based on an unknown stoichiometric increase and complexity of the structures. We are hoping to use the GO hierarchy to allow Barbara to annotate these different forms to more than the generic GO:0106003 amyloid-beta complex term.

I will copy our email conversation into a comment on this ticket to keep all info together. 
Also related is the previous ticket for the creation of the generic GO:0106003 amyloid-beta complex term:
https://github.com/geneontology/go-ontology/issues/13128
which was edited by @hdrabkin 

Best papers for getting an idea are:
PMID:18568035 (experimental evidence for dimers and tentative for oligomers)
PMID:26719327 (mini-review from Nigel and colleagues)

Suggested hierarchy:

GO:0106003 amyloid-beta complex
  --> is_a GO:NEW1 low-n Aβ oligomer complex
[no children, specific dimers in CP (not sure if the trimers are physiological)]

  --> is_a GO:NEW2 high-n Aβ oligomer complex
    --> is_a GO:NEW3 Type 1 amyloid-beta oligomer
    --> is_a GO:NEW4 Type 2 amyloid-beta oligomer
    --> is_a GO:NEW5 amylospheroid complex
    --> is_a GO:NEW6 amyloid-beta globulomer

NTRs:

1. 
GO:NEW1 low-n amyloid-beta oligomer complex
Def: An amyloid-beta complex consisting of small, typically dimeric, homo- or hetero-oligomers of peptide 40 and peptide 42 of the APP protein. Involved in modulation of signaling and synaptic function in the brain, predominantly in the cerebral cortex and hippocampus. Mostly found in the extracellular space with a proportion occurring as membrane-bound species. Influences synaptic plasticity through various receptors, mediates dendritic spine loss leading to decreased synapse density, inhibits long-term potentiation (LTP), enhances long-term depression (LTD), excessive calcium influx, mitochondrial impairment, endoplasmic reticulum stress and activation of apoptotic processes. Soluble dimers are the smallest synaptotoxic complexes of the amyloid-beta family of complexes and are causally linked to Alzheimer's disease.
Comment: An example is Protein 40 of APP (P05067-PRO_0000000093) in PMID:18568035 (inferred by direct assay).
References:
PMID:18568035
PMID:26719327
IntAct: EBI-13942506
IntAct: EBI-13943327
IntAct: EBI-13943368
IntAct: EBI-14022186
IntAct: EBI-14022241
IntAct: EBI-14022290
IntAct: EBI-14022837
IntAct: EBI-14022891
IntAct: EBI-14022935
GOC:bhm
DbxRef: ARUK-UCL
GOC:bc
Relationships:
is_a GO:0106003 amyloid-beta complex
all other relationships same as parent.
Synonyms:
amyloid-beta dimer complex [NARROW]
amyloid-beta heterodimer complex [NARROW]
amyloid-beta homodimer complex [NARROW]
[NB: I'm not sure if the trimers are physiological so not inclined to add them as synonyms...)

2. 
GO:NEW2 high-n amyloid-beta oligomer complex
Def: An oligomeric amyloid-beta complex consisting of increasingly large accumulations of amyloid beta peptides forming homo- or hetero-oligomers of peptide 40 and peptide 42 of the APP protein. Involved in modulation of signaling and synaptic function in the brain, predominantly in the cerebral cortex and hippocampus. Mostly found in the extracellular space with a proportion occurring as membrane-bound species. Influences synaptic plasticity through various receptors, mediates dendritic spine loss leading to decreased synapse density, inhibits long-term potentiation (LTP), enhances long-term depression (LTD), excessive calcium influx, mitochondrial impairment, endoplasmic reticulum stress and activation of apoptotic processes. Amyloid-beta structures build up over time from soluble dimers eventually forming large, inert fibrils or plaques. Soluble oligomers are thermodynamically more stable than dimers and are implicated in synaptic toxicity as the causative agent for Alzheimer's disease while inert fibrils appear to have no function.
Comment: An example is Protein 40 of APP (P05067-PRO_0000000093) in PMID:22179788 (inferred by direct assay).
References:
IntAct:EBI-14032700
IntAct:EBI-14032574
PMID:18568035
PMID:22179788
PMID:26719327
GOC:bhm
DbxRef: ARUK-UCL
GOC:bc
Relationships:
is_a GO:0106003 amyloid-beta complex
all other relationships as parent.
Synonyms:
amyloid-beta oligomer complex [NARROW]
amyloid-beta heterooligomer complex [NARROW]
amyloid-beta homooligodimer complex [NARROW]

3. 
GO:NEW3 Type 1 amyloid-beta oligomeric complex
Def: A high-n oligomeric amyloid-beta complex affecting signaling and synaptic function in Alzheimer's disease. Forms anti-parallel beta-sheets, random coils and beta-turns. May be broken down into dimers. May be broken down into dimers. Distinguished from Type 2, amylospheroid and globular amyloid-beta complexes by their tertiary structure and immunereactivity.
References:
PMID:22179788
PMID:26719327
GOC:bhm
DbxRef: ARUK-UCL
GOC:bc
Relationships:
is_a GO:NEW2 high-n amyloid-beta oligomer complex
all other relationships as parent.
Synonyms:
ADDL complex [EXACT]
pre-fibrillar amyloid-beta oligomer [EXACT]

4.
GO:NEW4 Type 2 amyloid-beta oligomeric complex
Def: A high-n oligomeric amyloid-beta complex affecting signaling and synaptic function in the advanced stages of Alzheimer's disease. Often contained within functionally innocuous fibrils or plaques. Forms anti-parallel beta-sheets. May be broken down into dimers. Distinguished from Type 1, amylospheroid and globular amyloid-beta complexes by their tertiary structure and immunereactivity.
References:
PMID:22179788
PMID:26719327
GOC:bhm
DbxRef: ARUK-UCL
GOC:bc
Relationships:
is_a GO:NEW2 high-n amyloid-beta oligomer complex
all other relationships as parent.
Synonyms:
ADDL complex [EXACT]
fibrillar amyloid-beta oligomer [EXACT]

5.
GO:NEW5 amylospheroid complex
Def: Spheroidical amyloid-beta complex affecting signaling and synaptic function in the advanced stages of Alzheimer's disease. Distinguished from Type 1 and Type 2 and globular amyloid-beta oligomeric complexes by their tertiary structure and immunereactivity.
References:
PMID:26224839
PMID:26719327
GOC:bhm
DbxRef: ARUK-UCL
GOC:bc
Relationships:
is_a GO:NEW2 high-n amyloid-beta oligomer complex
all other relationships as parent.
Synonyms: 
annular protofibril complex [EXACT]
ASPD [EXACT]

6.
GO:NEW6 amyloid-beta globulomer
Def: Globular amyloid-beta complex affecting signaling and synaptic function in the advanced stages of Alzheimer's disease. Distinguished from Type 1 and Type 2 amyloid-beta and amylospheroid complexes by their tertiary structure and immunereactivity.
References:
PMID:18216187
PMID:26719327
GOC:bhm
DbxRef: ARUK-UCL
GOC:bc
Relationships:
is_a GO:NEW2 high-n amyloid-beta oligomer complex
all other relationships as parent.

Probably also need to add relevant ARUK-UCL GOC refs.

Thanks for reading, thinking and apologies for getting you confused! I hope we can untangle these strands :) [pun intended!]

Birgit

PS: to follow shortly: email conversations leading to this ticket request.

**Comment by bmeldal** [comment]
Email conversations (I hope I didn't miss anything). I'll try to annotate to correct speakers as the ticket is loosing the mark-up and I answered Barbara's emails in-line... You kind of have to read backwards. And I have edited out all the 'hellos' and good-byes'!

BK:
We have agreed that your suggestion to use the relations capable_of or capable_of_part_of with CC GO terms representing specific Abeta oligomer types is probably the best solution for the moment. So I am now looking for other usage examples (in Noctua) that would additionally support the request for relations to become available in P2GO. In the meantime please do go ahead and create the Abeta oligomer CP entry.
========

NH:
Barbara is correct about the distinction between prefibrillar oligomers and fibrils – they have distinct biological properties.
========

BK:
Thank you for your emails and for bringing the 'capable of' annotation extension relations to my attention. Unfortunately, this relation is not available for annotation in P2GO... But if we could request it, this would certainly help to capture some of the information (non-comprehensively).

I'll have to think a bit more about how to address the lack of structural information in CP and our need to be able to annotate these different types of Abeta oligomers as unique entities. The use of the 'capable of' annotation extension relations would solve the problem only partly.

Re "fibrillar amyloid-beta complex" it is important to distinguish between soluble fibrillar Abeta oligomers (i.e. Type 2 oligomer reactive with the OC antibody), and non-soluble Abeta fibrils that form as the fibrillar oligomers expand and deposit as plaques (these non-soluble fibrils are also reactive with the OC antibody). We do not need CP identifiers for the Abeta fibrils that deposit in plaques, as they are generally inert. (Nigel, please correct me, if I'm wrong about anything in this paragraph). 
========== 
BM:
Btw, do we also need the GO term "fibrillar amyloid-beta complex"?
as a child of GO:0106003 amyloid-beta complex?

Fibrils were on the list in Barbara's attachment but not on the list in the body of the original email below.
========== 

>BK:
>        Thank you very much for explaining this and for having created the Complex Portal (CP) entries for the dimers for all 3 species, including rat. I admit I did not fully appreciate the distinctions between the Cellular Component GO terms and the CP entries.

BM:
    Think of complexes and their ACs as gene products and use them the same way you would use a UniProt AC or RNAcentral AC.
    Therefore, e.g.
    EBI-13942506 Amyloid-beta protein 40/42 complex (human)
    is_a GO:0106003 amyloid-beta complex
    part_of GO:0005615 extracellular space
    capable_of GO:0046872 metal ion binding
    capable_of_part_of GO:1900454 positive regulation of long term synaptic depression
    to just pick a few of the annotations I have done.
    You wouldn't annotate the UniProt chain to these terms as the monomers don't have those roles.

>BK:
>    I think the GO hierarchy, which you suggest for child GO terms of 'GO:0106003 amyloid-beta complex' makes sense. I think these terms should get created.

BM:
    I can do that. I'll tag you in the ticket.

>BK:
>    I also agree that it should work out fine to annotate CP amyloid-beta dimer and trimer terms to the GO term: "low-n Aβ oligomer complex" (rather than annotate "low-n Aβ oligomer complex" as a CP entity)

BM:
    The CP cannot hold grouping terms anyway, that's GO's remit. We can only create entries that are fully defined. More below.

>BK:
>    , as so far I have come across only a few papers, in which the amyloid-beta entity, which I was annotating, was referred to only as a "low-n Aβ oligomer complex" rather than a dimer or a trimer. However, this means that I will not be able to accurately capture the information from these few papers, as my only option will be to use the UniProt identifier for a monomeric amyloid-beta peptide for the entity being annotated (unless I'll notice that I would have captured the information from other papers, based on which I was able to annotate directly to either a dimer, or a trimer, and not annotate the papers describing generally "low-n Aβ oligomer complex" at all - the latter would probably be the better solution, as a lot of studies show that monomeric Aβ peptides appear to have no active roles at all, or they have very different roles to the oligomers). So this will be a limitation, but I am willing to go with this in context of the evidence, which I have come across so far.

BM:
    We have similar problems in IntAct when the entities aren't clearly described. Blame the authors for not being precise enough ;-)

>BK:
>    However, I will (strongly) argue against creating only one hetero-oligomer CP entry. I agree that functional differences between the different species of amyloid-beta hetero-oligomers are not obvious, or immediately apparent, but this is why we need to annotate these oligomers using GO. As the Jarosz-Griffiths et al. review shows, different types of amlyloid-beta oligomers bind to a number of different receptors (although there are certainly overlaps), thus modulating diverse downstream processes. And so a major objective, which we attempt to fulfil by annotating these oligomers using GO, is to be able to identify functional differences between them. I think the GO annotations need to be created for each specific oligomer investigated in each paper (that can be classed as one of the four types: Type 1, Type 2, amylospheroid, globulomer), and in my opinion it is essential that these oligomers have unique CP identifiers, or else their expected/putative unique functions/roles will not ever become apparent. I do not believe that GO annotation of different species of amlyloid-beta oligomers can be helpful to the Alzheimer's scientific community unless we can differentiate between them. Otherwise the scientists who do the work would not have made attempts to differentiate between them.

BM:
    The CP has no data structure to capture the structural differences. The entries for the 4 types of oligomers would have the same participants, same systematic name, same species and same (unknown) stoichiometry (we can't express >1, stoichiometry has to be an integer) so the data model would throw up an error as it looks like I'm creating an identical entry - which I am doing except for the functional annotations which are optional fields.
    The equivalent of you thought process would be to ask UniProt to create a different protein AC for each instance where the protein has a different function or is a member of a different complex.

    However, you can capture the different functions in GO by annotating to the 4 different oligomer types.

    E.g. you could have, from one paper,
    EBI-xxxxxxxx Amyloid-beta protein 40/42 hetero-oligomer complex (human)
    is_a GO:NEW Amyloid-beta protein 40/42 Type 1 oligomer complex
    part_of GO:0005615 extracellular space
    capable_of GO:0046872 metal ion binding
    capable_of_part_of GO:1900454 positive regulation of long term synaptic depression

    From another paper it might be:
    EBI-xxxxxxxx Amyloid-beta protein 40/42 hetero-oligomer complex (human)
    is_a GO:NEW Amylospheroids complex
    part_of GO:0005886 plasma membrane
    capable_of GO:0046872 metal ion binding
    capable_of_part_of GO:0010469 regulation of receptor activity

    I've made up the combination as I haven't read everything yet, just copied examples from the heterodimer.

    Then you analyse it by looking at co-annotated terms.
===========

BM:
    Thank you very much for deciphering the different Abeta complexes. Let me de-tangle what we can curate in the CP and what we can request in terms of GO terms. I think between the 2 resources we'll be able to satisfy all requirements.
 
>BK:
>        I discussed Aβ oligomer classification-related issues with experts at the ARUK conference, and I am attaching a summary classification from Professor Hooper, our collaborator from the University of Manchester.

>        Professor Hooper listed five categories of oligomers based on his research and on literature review of this field (PMID: 26719327, PMCID: PMC4751366, DOI: 10.1074/jbc.R115.702704). This classification system is based predominantly on conformation (in conjunction with molecular weights, which however will overlap between categories and should not be of our primary concern) of the oligomers.

>        Below I summarise what we've been working on so far, my suggestions following discussions at the ARUK conference, and related challenges/issues.

>        Aβ complex identifiers requests to date:

>        In contrast to the conformation-based classification, the Aβ oligomer protein complex requests that I sent to you previously had been based primarily on the identity of the monomeric Aβ subunit, which oligomers used in a specific experiment consisted of. In summary , the Aβ complexes that I requested identifiers for so far are listed below (numbers 1-5):

>        1) Aβ1-40 homodimer

[BM] curated: EBI-13943327 (human) & EBI-14022241 (mouse) & EBI-14022891 (rat)

>    2) Aβ1-42 homodimer

[BM] curated: EBI-13943368 (human) & EBI-14022290 (mouse) & EBI-14022935 (rat)

>    3) Aβ1-40/Aβ1-42 heterodimer

[BM] curated: EBI-13943327 (human) & EBI-14022186 (mouse) & EBI-14022837 (rat)
    I made all dimers in rat to be consistent in the Complex Portal, rather than only the one you requested, Barbara.

>    4) Aβ1-40 homooligomer

>    5) Aβ1-42 homooligomer

>    Suggestions for more Aβ complex identifiers:

>    Following Professor Hooper's advice and having just discussed the above with Ruth, I have the following suggestions regarding the need for further identifiers for the Aβ oligomeric species (listed below: letters A-E).

>    A) To create a parent protein complex category called 'low-n Aβ oligomer complex'. This would encompass complexes 1-3 from the list above, and trimers (as a separate, fourth entity sub-type).

>    B) To create a protein complex category called 'Type 1 Aβ oligomer/ADDL complex'. This would encompass all pre-fibrillar Aβ oligomers (reactive with A11 antibody).

>    C) To create a protein complex category called 'Type 2 Aβ oligomer/ADDL complex'. This would encompass all fibrillar Aβ oligomers (reactive with OC antibody).

>    D) To create a protein complex identifier for Amylospheroids/annular protofibrils, characterised as "neurotoxic Aβ oligomers, termed amylospheroids (ASPD), from the brains of AD patient (18⇓–20). ASPD appear in transmission electron microscopic (TEM) images as spheres of diameter ∼11.9 ± 1.7 nm (19). ASPD appear to be unique Aβ assemblies, as determined immunochemically. These structures are recognized strongly by ASPD-specific antibodies (Kd ∼ pM range), but not with the oligomer-specific polyclonal antiserum A11 (19). ASPD are distinct from Aβ dimers, ADDLs, dodecamers, and other A11-reactive entities (19)." (Fragment from: PMID:26224839, PMCID:PMC4538662, DOI:10.1073/pnas.1421182112).

>    E) To create a protein complex identifier Globulomers "a highly stable oligomeric Aβ complex called “Aβ1–42 globulomer”(Barghorn et al., 2005), which mimics binding properties and pathology of other described oligomeric Aβ forms. For example, Aβ1–42 globulomer binds to primary hippocampal neurons and blocks long-term potentiation (LTP) in hippocampal slices. The pathological relevance of Aβ1–42 globulomer is supported by the observation that specific antibodies detect globulomer epitopes in brains of AD patients and Aβ-overproducing transgenic mice (Barghorn et al., 2005). These data suggest that a naturally occurring form of Aβ1–42 globulomer causes a defective information storage of hippocampal synapses and thus contributes to the cognitive deficits in brains of AD patients." (Fragment from: PMID:18216187, DOI:10.1523/JNEUROSCI.4771-07.2008).

>      Issues:

BM:
    We need to distinguish between the creation of GO term that have a hierarchy and CP terms that are simply entities, like UniProt entries.
    So far we created GO:0106003 amyloid-beta complex as very generic term.
    Def: Protein complex involved in modulation of signaling and synaptic function in the brain, predominantly in the cerebral cortex and hippocampus. Forms dimers and multimers of amyloid beta peptide 40 and peptide 42 (proteolytic cleavage products of amyloid beta A4 protein, also known as amyloid beta precursor protein). Mostly found in the extracellular space with a proportion occurring as membrane-bound species. Influences synaptic plasticity through various receptors, mediates dendritic spine loss leading to decreased synapse density, inhibits long-term potentiation (LTP) and enhances long-term depression (LTD). Soluble multimeric form is the main pathogenic species linked to Alzheimer's disease.

>BK:
>    Re: Re: A) If a curator annotates specifically e.g. Aβ1-42 homodimer, this annotation will not automatically be transferred to the 'parent' 'low-n Aβ oligomer complex', will it? (Ruth and I think it should be). In order to overcome this, could the dimer and trimer subclasses of low-n Aβ oligomer complex actually exist as its variants (rather than child terms), similarly to monomeric protein variants in UniProt (a curator can annotate directly to APP using the P05067 UniProt ID, or they can annotate more specifically to Aβ1-42 monomer, using the P05067:PRO_0000000092 UniProt peptide/variant ID). Analogously, for the protein complexes, if the protein complex identifier EBI-00XXXX corresponds 'low-n Aβ oligomer complex', could e.g. EBI-00XXXX:var1 and EBI-00XXXX:var2 correspond to Aβ1-40/Aβ1-42 heterodimer and Aβ1-40 homodimer, respectively. Would it be possible to introduce this type of notation for protein/peptide complexes? In this way the annotations created to the more specific variants/types of low-n Aβ oligomers will also exist/be displayed in databases for the overall 'parent' 'low-n Aβ oligomer complex' without the need to create separate (duplicate!) annotations.

BM:
    For pt A) we'll have to create a "low-n Aβ oligomer complex" in GO and then annotate the dimers and trimers (not created yet) from the CP to this term. We could also request separate GO children for dimers and trimers but I don't think they will be created because we decided to not create variants based purely on stoichiometry, that the remit of the CP.
     
>BK:
>    Re: B) and C) These oligomers would typically comprise both: Aβ1-40 as well as Aβ1-42 monomers, so I am not certain how to 'relate' these complexes to 'Aβ1-40 homooligomer' and 'Aβ1-42 homooligomer'. I do not think that 'Type 1 (or Type 2) Aβ oligomer/ADDL complex' can be a parent(s) of  'Aβ1-40 homooligomer' and 'Aβ1-42 homooligomer' because 'Type 1 (or Type 2) Aβ oligomer/ADDL complex' as these typically (when obtained from brain tissue) comprise a mixture of 'Aβ1-40 and Aβ1-42. 'Aβ1-40 homooligomer' and 'Aβ1-42 homooligomer' will most often be complexes formed from synthetic homogenous peptides, yet, depending on the conformation, which they take on, they may be recognised either by the A11 antibody, or the OC antibody. So for biologists the distinction between Type 1 and Type 2 Aβ oligomer/ADDL complexes is more useful for classification purposes, as these complexes would occur naturally and will have distinct roles. On the other hand, from the Gene Ontology viewpoint, if an experiment involved the use of Aβ oligomer aggregated from an Aβ1-40 synthetic peptide only (without Aβ1-42), curators will want to be able to capture this precise information too. 

>    Re: D) To the best of my knowledge this structure has only been isolated from Alzheimer's brain. So could we assign an identifier to it, if it is not known to have been found in 'normal' aged brains? But I suppose this question is also relevant to the various synthetic forms of Aβ oligomers that are not known to have been found in 'normal' aged brains (or any human brains at all)...

BM:
    B-E): These are all oligomers that only differ by their antibody recognition activity and slightly by function but there is no distinguishing feature in the participant list or stoichiometry. We will create one entry in the CP but as there are some functional distinctions we can ask if we can get several GO terms. Shall I raise a ticket for that?

    I will only create the hetero-oligomer as the homo-oligomers appear to be synthetic only and we need to stick to in vivo complexes. Synthetic homo-oligomers need to be annotated to the parent term.

    Suggested GO hierarchy:
    GO:0106003 amyloid-beta complex

      --> is_a low-n Aβ oligomer complex
            --> no children, specific dimers and trimers in CP

      --> is_a high-n Aβ oligomer complex
        --> is_a Type 1 Aβ oligomer/ADDL complex/pre-fibrillar Aβ oligomer (term name vs synonyms to be decided)
        --> is_a Type 2 Aβ oligomer/ADDL complex/fibrillar Aβ oligomer (term name vs synonyms to be decided)
        --> is_a amylospheroid/annular protofibril complex (term name vs synonyms to be decided)
        --> is_a Aβ globulomer (term name vs synonyms to be decided)

    The hetero-oligomer in the CP would be annotated to all 4 of the above children.

>BK:
>    Could you please share your thoughts on these suggestions and classification options? Especially, could you please comment on the issues, i.e. the idea about protein complex variants (re: A)) and links (if any) between Aβ homooligomers and the Type 1 (or Type 2) Aβ oligomer/ADDL complexes, which would virtually always exist as heterooligomers (re B) and C))?

**Comment by bmeldal** [comment]
Apologies for the editing above, I tried to get to grips with the right mark-ups!

Attaching the summary sheet from Nigel.

[Classification of amyloid-beta oligomers.docx](https://github.com/geneontology/go-ontology/files/943245/Classification.of.amyloid-beta.oligomers.docx)

**Comment by BarbaraCzub** [comment]
Thank you @bmeldal for creating the IntAct and GO term entries for the different types of amyloid-beta complexes.

Wrt capable_of relationships, mentioned in the email exchange, which you pasted in here, I had a brief email discussion with @vanaukenk and @ukemi regarding this and currently there appear to be no examples of GO annotations which use the 'capable_of' or 'capable_of_part_of' relation in the annotation extension (Kimberly and David were aware of only one such use in the past, but the annotation had since then been updated anyway).

Therefore, rather than to request these relations to become available for use in P2GO, during our last team meeting at UCL we discussed alternative ways of capturing the biological information related to the various amyloid-beta complexes, and we identified the relationship 'occurs_at' as the most appropriate one. 
@RLovering 

Occurs_at: "Identifies the Cellular Component or sequence feature adjacent to or in the vicinity of which the Molecular Function or Biological Process is executed"  https://github.com/geneontology/annotation_extensions/blob/master/doc/occurs_at.md 
This relation will be appropriate for use with GO annotations such as 'GO:1900271 regulation of long-term synaptic potentiation', whereas it would not be logically correct to use 'occurs_in' ("Identifies the cell, tissue, cellular component or anatomical entity within which all parts of the molecular function or biological process occurs" https://github.com/geneontology/annotation_extensions/blob/master/doc/occurs_in.md ), which we had considered initially.

With this relation being available for use in P2GO, we can make MF (with contributes_to qualifier) and/or BP annotations to the APP gene product, and then with can use the annotation extension field to say that the MF/BP occurs_at GO:0106003 amyloid-beta complex (or one of the more specific child terms). 

Barbara

**Comment by bmeldal** [comment]
@pgaudet I saw you added the ticket to the Editors' call today. I just emailed Barbara and Nigel and invited them to comment on here with regards to the question of at which point these complexes become pathogenic-only. 

I guess the issue is that there is no synaptic impairment until the oligomers form and eventually cause it. In a normal brain oligomers get caught and broken down by various proteins preventing their accumulation so they do exist to some degree in normal brains but act as causative agents of AD. We already agreed that the large fibrils or plagues are not functional and therefore don't get a term. They are certainly the last stage in the accumulation process at which point AD is in full swing.

As I'm writing this I realise I didn't explicitly point out in the defs that they exist in normal brains, may have some normal function (monomer certainly have normal synaptic functions) and that potentially pathogenic oligomers can either be broken down or accumulated by chaperones preventing them from becoming pathogenic. There is a finely balanced equilibrium going on that seems to shift towards pathogenicity only in some people who then, as a result of this shift, develop AD. The whole balance issue is not fully understood - which is why Barbara is annotating the information that is out there!

We need to clear up:

- [ ] which forms are found in the normal brain
- [ ] amend defs to make it clear these terms (as decided in pt above) exist in normal brain but act as causative agents for AD in certain people.

[I will also have to make some tweeks to the CP defs but they are already more wordy anyway. I was trying to keep the GO defs shorter...

**Comment by bmeldal** [comment]
Add @BarbaraCzub 's comment:
>With this relation being available for use in P2GO, we can make MF (with contributes_to qualifier) and/or BP annotations to the APP gene product, and then with can use the annotation extension field to say that the MF/BP occurs_at GO:0106003 amyloid-beta complex (or one of the more specific child terms).

I don't do AE or Col16 annotations so I'm leaving the RO issue to those who know better!

Would you also still annotate the CP oligomer to the specific GO oligomer term in the CC class?

**Comment by BarbaraCzub** [comment]
Hi @bmeldal 

Yes, in order to get the full picture I would still annotate the CP oligomer to the specific CC GO oligomer term. And in addition to annotating the gene product to the relevant BP and/or MF terms (with the occurs_at [specific amyloid-beta complex] annotation extension), I would also annotate the CP oligomer to these BP and/or MF terms directly. I just need a way of capturing the more specific amyloid-beta complex types as well, hence the annotation extension relation issue.

**Comment by BarbaraCzub** [comment]
Please see issue #13418

Should the GO term complex names contain "amyloid-beta" or "beta-amyloid"?

Atm, all the relevant MF and BP terms in GO, use "beta-amyloid" whereas the only currently existing CC GO term uses the reverse notation: "amyloid-beta".

It would be ideal to keep the primary GO terms consistent, but of course still include the alternative spelling among the synonyms.

Thanks,
Barbara

**Comment by bmeldal** [comment]
Barbara, you decide and I fix the terms in the CP :) It's the same to me and happy to go with whatever the community uses preferentially.

**Comment by BarbaraCzub** [comment]
Thanks @bmeldal :) Let's hold on for the moment and see whether the editors decide to make any changes, and which ones. (My personal preference is "amyloid-beta" or "Abeta" but most of the existing GO terms use "beta-amyloid", whereas the research community seems to preferentially use "Aβ", and we cannot use "β" in a GO term anyway).

**Comment by vanaukenk** [comment]
Thanks @bmeldal and @BarbaraCzub for your input on this issue.  I will try to address what I think are the three main points, so far:

1. Wrt the use of "amyloid beta" vs "beta amyloid", I do not have a personal preference, but a quick PubMed search using each form returns nearly three-fold more records for "amyloid beta" than for "beta amyloid", so unless anyone strongly objects, I am fine with using "amyloid beta" as the primary representation in GO with "beta amyloid" in synonyms, if that's appropriate.

2. I am still concerned about whether the higher order oligomers, i.e. anything other than the dimers, represent complexes with normal physiological functions.  Can we be certain of this?  If not, I think we are likely outside the realm of traditional GO annotation here.  

3. For the example of using the 'occurs at' extension, would the annotation be something along the lines of:

APP involved in regulation of long term synaptic potentiation occurs at amyloid-beta complex

and is that meant to say that the actual regulatory process occurs adjacent to or in the vicinity of the amyloid-beta complex?

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 

1. I agree re: "amyloid-beta" as the primary representation and "beta-amyloid" as a synonym. However, I would probably advocate spelling both with a dash / "-", as it appears to be the preferred spelling in literature.

2. No, we cannot be certain that amyloid-beta oligomers have normal physiological roles. Having looked through my notes, the only evidence that I found in favour of this argument, comes from Puzzo et al. who show that it is plausible, when the amyloid-beta oligomers are present at low concentrations (doi:  10.1523/JNEUROSCI.2692-08.2008). The authors conclude: "We have found that picomolar concentrations of an aged Aβ42 preparation containing both monomers and oligomers enhance synaptic plasticity and memory. However, it is impossible to know the molarities of different oligomers and monomers to which slices and hippocampi were actually exposed because Aβ can easily change its conformation by the time it reaches the brain tissue after its initial preparation. (...). Finally, there is uncertainty on the molarities of monomers and different oligomeric forms of Aβ existing at synapses.". Yet, I admit, it is not clear from these findings, which of the amyloid-beta species within the mixture actually cause(s) the positive effect on memory.

3. Yes, the annotation example, which you provided, precisely reflects how I intended to capture the information. However, technically this would not be correct anyway, because published findings have repeatedly demonstrated that only the amyloid-beta oligomers (but not the amyloid precursor protein/APP, or not the amyloid-beta monomers) are involved in regulation of synaptic plasticity. So ideally the oligomer should be the entity being annotated, or these annotations should not get created at all. 

In view of the above I am going to delete all of the PRIV annotations, which I have made to capture the roles of amyloid-beta oligomers, unless you (or @RLovering ?) advise otherwise. (It would not be factually correct to capture this information using the identifier for APP (P05067), or for either of the amyloid-beta peptides (P05067:PRO_0000000093 or P05067:PRO_0000000092)).

**Comment by bmeldal** [comment]
Thank, @BarbaraCzub 
Phuh, I used 'amyloid-beta' in the complexes so no need to change the spelling :)
For now, all the CP terms are annotated to GO:0106003 amyloid-beta complex.

**Comment by bmeldal** [comment]
Barbara, if the specific multimers can't be created in GO are you able to use HP ontology to annotate the disease stages?

**Comment by vanaukenk** [comment]
Hi @BarbaraCzub 
Thanks very much for your thoughtful reply.  We had also discussed this ticket on the ontology editors' call last Friday, and your comments are consistent with how we felt.  Without more definitive evidence to support a normal physiological role for these amyloid-beta (with the dash!) oligomers, it is difficult to justify their annotation in GO.  Hopefully, you will be able to find another way to annotate them, though, as clearly understanding their role in the disease mechanism is important.
I will review and update, where appropriate, the existing amyloid-beta references in the ontology and let you know if I have any other questions along the way,
Thanks also @bmeldal for your thoughts and input on this ticket.

**Comment by bmeldal** [comment]
Thank you, @vanaukenk

**Comment by BarbaraCzub** [comment]
Thanks @bmeldal for the HP ontology suggestion. I'll check with @RLovering but I believe this would be outside of the scope of this project.
Thanks @vanaukenk for the amyloid-beta reference review and updates. Please let me know, of you need and further information.

**Comment by BarbaraCzub** [comment]
For the record: PMID:15190117 shows that aggregated (oligomeric) amyloid-beta 1-42 stimulates neurogenesis in neural stem cell cultures from rodent striatum and hippocampus.

**Comment by bmeldal** [comment]
Just read the paper and I agree, it shows a physiological effect for Abeta1-42 oligomers. Unfortunately, they don't show whether the oligomers are just the dimers described in other papers or higher order oligomers but given the time they allow for aggregation it should be possible to form higher order oligomers.

**Comment by bmeldal** [comment]
Uniprot P05067 is "Amyloid beta A4 protein" - no hyphen. Should all get aligned...

**Comment by vanaukenk** [comment]
@BarbaraCzub and @bmeldal 
Just checking - do we need to do anything more wrt this ticket?
If not, I will close.  Thx.

**Comment by bmeldal** [comment]
@vanaukenk I think we are done with this as the naming issue is dealt with in another ticket.

Oligomers were released in the CP this week.

(Still up watching UK election results coming in, should really go to bed...)

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk, unless any new conclusions were reached during the ontology meeting managers' discussions (moved last month by @ukemi), then yes, I agree with @bmeldal that this ticket can now be closed.
