### ISSUE TITLE
Fix go-inferences report

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13396]
Migrate this from svn

**Comment by cmungall** [comment]
Here is the diff of the current ontology https://build.berkeleybop.org/job/build-go-ontology-inferences/18/artifact/target/go_inferences.diff/*view*/

**Comment by cmungall** [comment]
Some things perhaps requiring attention:

```
 id: GO:0002213 ! defense response to insect
-is_a: GO:0098542 {is_inferred="true"} ! defense response to other organism **CHECK ME**
+is_a: GO:0006952 {is_inferred="true"} ! defense response

 id: GO:0002215 ! defense response to nematode
-is_a: GO:0098542 {is_inferred="true"} ! defense response to other organism  **CHECK ME**
+is_a: GO:0006952 {is_inferred="true"} ! defense response

 id: GO:0009600 ! detection of nematode
-is_a: GO:0098543 {is_inferred="true"} ! detection of other organism  **CHECK ME**
+is_a: GO:0098581 {is_inferred="true"} ! detection of external biotic stimulus
 
 id: GO:0009601 ! detection of insect
-is_a: GO:0098543 {is_inferred="true"} ! detection of other organism  **CHECK ME**
+is_a: GO:0098581 {is_inferred="true"} ! detection of external biotic stimulus

...


 id: GO:2000068 ! regulation of defense response to insect
-is_a: GO:0002831 {is_inferred="true"} ! regulation of response to biotic stimulus
 is_a: GO:0031347 {is_inferred="true"} ! regulation of defense response
-is_a: GO:0032101 {is_inferred="true"} ! regulation of response to external stimulus
-is_a: GO:0043900 {is_inferred="true"} ! regulation of multi-organism process
```

**Comment by cmungall** [comment]
The technical part is done. If someone can check the differences that were introduced during the no-report interregnum (see job above) we can close this

**Comment by ValWood** [comment]
fixed my issue in todays load..

**Comment by dosumis** [comment]
Partial fix in #13489

But full fix requires this BFO import to be setup, as requested in #12946

This will pull the BFO hierarchy, removing redundant inferences.  It should also pull disjointness axioms so that we get basic error checking.   @cmungall  - can this be made a priority?

**Comment by cmungall** [comment]
@ukemi - ignore the non-GO ones

@dosumis - I will do this next week.

**Comment by ukemi** [comment]
@dosumis 
Is this done?

**Comment by dosumis** [comment]
> @dosumis
> Is this done?

Looks like it.  Both dependent tickets fixed.  Do you still see inferences to BFO?
