### ISSUE TITLE
NTR: GO terms for EC 4.1.3.42, 3.5.1.111

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#13392]
Hi,

Could you create new GO terms for these two EC reactions?  (I know you'll be getting a long list of EC reactions that don't have GO terms from Ron Caspi someday soon; these two are of immediate interest to me, though.)

Thanks,
Ingrid

**Comment by hdrabkin** [comment]
Hi Ingrid
Please suggest is_a parents?
PMIDS ?

**Comment by keseler** [comment]
Sorry for not including this initially; I thought these would be evident given the EC number.  

For 3.5.1.111, specifically for E. coli, there is a recent publication, PMID 28373563.  However, for general reference, you should probably use the paper cited in the EC, PMID 21288482.  Parent could be GO:0016811 (or perhaps even GO:0050152; I'm not sure).

For 4.1.3.42, the parent should be GO:0016833.  Possible citations are PMIDs 1339418, 1098660, 4560498, 4894280.

**Comment by hdrabkin** [comment]
done
