### ISSUE TITLE
MP GO:0002100	tRNA wobble adenosine to inosine editing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13391]
add  parent
GO:0006382	adenosine to inosine editing

**Comment by ValWood** [comment]
ntr tRNA adenosine to inosine editing
(can also be modified at position 37 adjacent to anticodon)

**Comment by ValWood** [comment]
not to self, fix tad1 to  ntr tRNA adenosine to inosine editing

**Comment by pgaudet** [comment]
Hi Val, 

Does modification at position 37 not count as a wobble modification ? It seems to be included: http://www.sciencedirect.com/science/article/pii/S0022283606015865

wobble just means 'atypical base pairing', as far as I know. So I suggest changing the definition of the existing term rather than adding a new term. What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm not sure I thought  the wobble position was  only the split codon.
https://www.mun.ca/biology/scarr/MGA2_03-22.html

Could just make the existing term

tRNA adenosine to inosine editing
and say in the def that it is usually associated with the anticodon loop?

So that a single term can be used for all of this type of modification independent of the position.

**Comment by pgaudet** [comment]
Hi Val, 

I read about this process and you are right, the wooble position is the position 34 (37 is not part of the anticodon, as you correctly pointed out). 

I found this term: "2-methylthio-N-6-(cis-hydroxy)isopentenyl adenosine-tRNA biosynthesis" , with definition "The chemical reactions and pathways involved in the biosynthesis of 2-methylthio-N-6-(cis-hydroxy)isopentenyl adenosine (ms2io6A), a modified nucleoside present in position 37 (adjacent to and 3' of the anticodon) of tRNAs."
could it be what you are looking for? 

The name and definitions should probably be rephrased for clarity. 

What do you think ? 

Pascale

**Comment by pgaudet** [comment]
Never mind- that's yet another modification at position 37.

**Comment by pgaudet** [comment]
Adding review  PMID: 27974624  as a reference.
