### ISSUE TITLE
NTR:Golgi transport complex binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13394]
Could I have: Golgi transport complex binding

Def: Interacting selectively and non-covalently with the Golgi transport complex, a multisubunit tethering complex of the CATCHR family. 
Ref: PMID:28100664
Is_a GO:0032403 protein complex binding

Exact synonym: COG complex binding

(note: used term consistent with GO:0017119 Golgi transport complex)

**Comment by pgaudet** [comment]
Hello, 

This depends on the decision here: 
https://github.com/geneontology/go-ontology/issues/13148

Ontology editors do not want to create an unlimited number of x protein complex binding terms, but when to create new one has not been defined. 

I'll add this to ontology-editor's discussions. Fell free to comment the other issue. 

Thanks Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140164
+name: Golgi transport complex binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with the Golgi transport complex, a multisubunit tethering complex of the CATCHR family." [GOC:ha, PMID:28100664]
+synonym: "COG complex binding" EXACT []
+is_a: GO:0032403 ! protein complex binding
+created_by: pg
+creation_date: 2018-02-08T11:49:38Z
