### ISSUE TITLE
Q:Header change in go-basic.obo

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13393]
The latest go-basic.obo is missing the date stamp in the header:

First 3 lines of an older version example:
format-version: 1.2
data-version: releases/2016-11-08
date: 08:11:2016 10:56

First 3 lines of latest version:
format-version: 1.2
data-version: releases/2017-04-19
subsetdef: goantislim_grouping "Grouping classes that can be excluded"

Is this intentional and to be carried forward in the future?

**Comment by cmungall** [comment]
This is intentional, use data-version (versionIRI in OWL)
