### ISSUE TITLE
TPV: alert, numerous problem annotations generated  under "regulation of cell size"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13400]
regulation of actin nucleation has a parentage to regulation of cell size (via regulation of actin filament length).

Not sure why (possibly should be "cellular component size"...(in fact  regulation cell size has been placed as a child of cellular component size which is also incorrect).

Anyway its making my "regulation of cell size" annotations look a bit crazy.

**Comment by ukemi** [comment]
It looks like this is coming from the OBA import. Actin filament length is part_of some cell size. This seems incorrect. It needs to be fixed in oba. @cmungall  do you know who we contact? 

As for the second part of this ticket. I think it is ok. A cell is a cellular component.

**Comment by krchristie** [comment]
@ukemi How did you look up where Actin filament length is part_of some cell size is coming from?

thanks, Karen

**Comment by ukemi** [comment]
You can follow the parents in Protege.

**Comment by cmungall** [comment]
OBA has a general design pattern in which the quality hierarchy shadows the partonomy of the entities.

So for example:

 - plasma membrane morphology is part-of cell morphology
 - bone mass part-of organism mass
 - leaf shape part-of plant shape

Note that is_a is not the correct relationship type to use here. We're following a general idea of qualities being made up of other qualities.

I think we need to break this up for different qualities. Mass is additive over all parts of a cell. However, length is not.

This may take a bit of time. In the interim, I suggest importing only the subclass hierarchy from OBA. This may mean that we will need to manually add some links in GO, but it seems better than the false positives.

**Comment by cmungall** [comment]
I'm going to do #13396 first so we can see the diff
