### ISSUE TITLE
GO:0043121 neurotrophin binding synonyms

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13406]
Hello,

Should the term: 'GO:0043121 neurotrophin binding' have a synonym: 'neurotrophic factor binding'?

Or was this term supposed to be specific to NTF3 (P20783) and NTF4 (P34130) (and/or other) gene products?

Thanks,
Barbara

**Comment by vanaukenk** [comment]
@BarbaraCzub 

I was just looking at the Change Log for GO:0043121 in QuickGO:
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0043121#term=history

It looks like there used to be more specific terms for NTF3 and NTF4 binding, but they were merged into GO:0043121 about five years ago.

However, there are also two child terms of GO:0043121 that refer specifically to BDNF and NGF, which I thought were also in the neurotrophin family, so I'm not sure why there are specific terms for just those two factors.

We've been trying to move away towards gene product-specific terms, so let me discuss this one with the other GO editors and I will get back to you.  Thx.

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 
Thank you for looking into this. Just to clarify: I am not looking to use a gene product-specific term. I just was not sure whether 'GO:0043121 neurotrophin binding' was general enough, hence I wondered whether it should have had the synonym 'neurotrophic factor binding'.

**Comment by BarbaraCzub** [comment]
Hello, looking again at this, I am going to add the _exact synonym_ 'neurotrophic factor binding', as I originally suggested. I will also change the current exact synonym to narrow.
