### ISSUE TITLE
NTR for contractile vacuole processes

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#13407]
I would like to add some terms involving the processes of contractile vacuoles, which occur in Dicty and many other microorganisms as well as in algae. 

PMID:22323285 looks at what they call the ‘kiss and run’ discharge, and that seems the difference to some other vesicle processes, the membranes do not completely merge in the discharge process. They dissect what tethers and detethers the CV to the PM.

**GO:NEW:** contractile vacuole tethering involved in discharge  
EXACT synonym: contractile vacuole tethering to plasma membrane
DEF: The initial, indirect interaction between a contractile vacuole membrane and a site of discharge in the plasma membrane. This interaction is mediated by tethering factors (or complexes), which interact with both membranes. Interaction can occur via direct binding to membrane phospholipids or membrane proteins, or via binding to vesicle coat proteins. This process is distinct from and prior to docking and fusion. 
is_a
— GO:0090522: vesicle tethering vesicle tethering involved in exocytosis

However, I also need a term for the detethering, or dissociation of the emptied vacuole after discharge.

**GO:NEW:** contractile vacuole detethering from plasma membrane

DEF: The dissociation of the contractile vacuole after discharge, from the plasma membrane.  This interaction is mediated by detethering factors that initiate the process of tubulation and fragmentation of the empty CV bladder, which is then reincorporated into the CV network.

What structure? Maybe a direct child of GO:0051650: establishment of vesicle localization?

Also,should both terms above be children of GO:003329: contractile vacuole organization? This term has currently no children. 

_Comments:_
- Detethering was used in the paper but dissociation would do if preferred, otherwise could be added as synonym
- CV is a ubiquitous acronym for contractile vacuole, used it in def but spell out if desired.

Finally, looking at another paper (PMID:19687255), They identified a class V myosin (myoJ) responsible for the transport of the CV to the cortex (near PM) and back. To annotate that, I would like to add another child to GO:0051650 establishment of vesicle localization

**GO:NEW:** contractile vacuole localization OR establishment of contractile vacuole localization
The directed movement of the contractile vacuole to a specific location.

Thanks,
Petra

**Comment by pgaudet** [comment]
Hi Petra, 

For GO:NEW: contractile vacuole tethering involved in discharge, I put the proposed synonym "contractile vacuole tethering to plasma membrane" as NARROW, since it's missing the discharge aspect; ok?

**Comment by pgaudet** [comment]
Here are the 3 new terms: 
 [Term]
+id: GO:0140025
+name: contractile vacuole tethering involved in discharge
+namespace: biological_process
+def: "The initial, indirect interaction between a contractile vacuole membrane and a site of discharge in the plasma membrane. This interaction is mediated by tethering factors (or complexes), which interact with both membranes. Interaction can occur via direct binding to membrane phospholipids or membrane proteins, or via binding to vesicle coat proteins. This process is distinct from and prior to docking and fusion." [PMID:22323285]
+synonym: "contractile vacuole tethering to plasma membrane" NARROW []
+is_a: GO:0090522 ! vesicle tethering involved in exocytosis
+intersection_of: GO:0006903 ! vesicle targeting
+intersection_of: part_of GO:0070177 ! contractile vacuole discharge
+created_by: pg
+creation_date: 2017-05-02T09:50:10Z
+
+[Term]
+id: GO:0140026
+name: contractile vacuole dissociation from plasma membrane
+namespace: biological_process
+def: "The dissociation of the contractile vacuole after discharge, from the plasma membrane. This interaction is mediated by detethering factors that initiate the process of tubulation and fragmentation of the empty contractile vacuole bladder, which is then reincorporated into the CV network." [PMID:22323285]
+synonym: "contractile vacuole detethering from plasma membrane" EXACT []
+is_a: GO:0016192 ! vesicle-mediated transport
+created_by: pg
+creation_date: 2017-05-02T10:16:12Z
+
+[Term]
+id: GO:0140027
+name: establishment of contractile vacuole localization
+namespace: biological_process
+def: "The directed movement of the contractile vacuole to a specific location." [PMID:19687255]
+is_a: GO:0051656 ! establishment of organelle localization
+created_by: pg
+creation_date: 2017-05-02T10:23:26Z


Thanks, Pascale

**Comment by pfey03** [comment]
Hello Pascale, I finally looked more into your questions that you seemed to have answered yourself. Here my (late) comments:

1) GO:0090522: vesicle tethering vesicle tethering involved in exocytosis has the EXACT synonym: vesicle tethering to plasma membrane. Maybe you should make this a NARROW synonym too? I kind of did it in analogy to this.

2) Yes! I think the CV discharge is_a exocytosis

Many thanks,
Petra

**Comment by pgaudet** [comment]
Thanks Petra for the feedback. I fixed the synonym scope of 'GO:0090522: vesicle tethering involved in exocytosis'. 

Cheers, Pascale
