### ISSUE TITLE
'Amyloid-beta' vs. 'Beta-amyloid' in GO term names

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13418]
Hello,

I have noticed a lack of consistency in nomenclature of some related terms, which makes it easy to miss a term during a search, if somebody is not aware of the different term 'template'.

Specifically:
'Amyloid-beta / Beta-amyloid' function and process terms use the spelling: 'Beta-amyloid', e.g. "response to beta-amyloid" or "beta-amyloid binding"; whereas the complex term is called "amyloid-beta complex".
Would it be possible to change "amyloid-beta complex" to "beta-amyloid complex" to keep it consistent with the other beta-amyloid terms?

Another subtle discrepancy, which I noticed, is the difference in spelling between:
- "long term synaptic depression";
- "long-term synaptic potentiation";
- "short-term synaptic potentiation".
I am not sure whether the correct spelling should be with a dash / "-", or without it, but I suppose it makes sense to keep this consistent.

Thanks,
Barbara

**Comment by bmeldal** [comment]
Barbara, you decide and I fix the terms in the CP :) It's the same to me and happy to go with whatever the community uses preferentially.

**Comment by vanaukenk** [comment]
Hi @BarbaraCzub 
I'm working through the mentions of beta-amyloid in the ontology and for at least one term, there is an equivalence axiom that refers to the ChEBI entry which has the name beta-amyloid:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:64645
Since ultimately the equivalence axiom refers to a ChEBI id, the difference will not affect that part of GO, but we do like to be in agreement with ChEBI wherever possible, so I was wondering if you could open a ticket with ChEBI to ask if they could update the name entry, and synonyms, as well.  Thank you!

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk , thank you for working through these. I've submitted the ChEBI ticket as you suggested: https://github.com/ebi-chebi/ChEBI/issues/3318

**Comment by bmeldal** [comment]
I subscribed to the ticket but unfortunately, ChEBI seem to be rather slow working though their tickets. They never seem to have enough hands to deal with them.

**Comment by bmeldal** [comment]
Uniprot P05067 is "Amyloid beta A4 protein" - no hyphen. Should all get aligned...

Most discussion in #13388

**Comment by vanaukenk** [comment]
Hi @bmeldal and @BarbaraCzub 
Could one of you contact UniProt to ask if they are willing to update their entries, as well?
I made all of the changes to GO last Friday, but the merge request got hung up with a failed Travis check, so I need to try that again.

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk , I've emailed the UniProt helpdesk. I'll post again when they reply.

**Comment by vanaukenk** [comment]
The Travis build was successful this morning, so the amyloid-beta changes are now committed.  I will keep this ticket open to also address the 'depression' and 'potentiation' issues.

**Comment by BarbaraCzub** [comment]
Great. Thank you @vanaukenk.

**Comment by bmeldal** [comment]
So we are going for "amyloid-beta"?

**Comment by BarbaraCzub** [comment]
Hi @bmeldal, yes,  @vanaukenk has edited the GO terms to contain 'amyloid-beta' (rather than beta-amyloid'). But as you've pointed out the ChEBI ticket has not been picked up by anyone yet, and I am also waiting to hear from UniProt. Hopefully, they'll be able to align the nomenclature with GO.

**Comment by BarbaraCzub** [comment]
#13538

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 
I have received a reply from Anne at Swiss-Prot:
"Thank you for drawing our attention to the changes occurring in the GO nomenclature. I'll look for the inconsistencies in UniProtKB/Swiss-Prot and let you know. Please be patient, as it may take a little time." 
I am aware that the next UniProt release is due out on the 5th of July, so I'll set a reminder to check the amyloid-precuror protein entries after this date, and only follow up on this, if the updates won't have happened by then.

**Comment by BarbaraCzub** [comment]
Followed up today.

**Comment by BarbaraCzub** [comment]
Swiss-Prot have now updated their entries and the changes should be live on September 27th (release 2017_09).

**Comment by BarbaraCzub** [comment]
Anne wrote: "In the vast majority of entries, we were using "amyloid-beta", but we found close to 160 entries which contained the term "beta-amyloid". I made the corrections as you suggested and it should be consistent now."

**Comment by BarbaraCzub** [comment]
The names have been updated in CHEBI as well:
https://github.com/ebi-chebi/ChEBI/issues/3318

**Comment by bmeldal** [comment]
this looks ready to close :)

**Comment by BarbaraCzub** [comment]
Yes, SwissProt and ChEBI have both updated the terminology, as we requested.
