### ISSUE TITLE
GO:0045161 ! neuronal ion channel clustering - process implies component?

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#13412]
Created in response to #5487?

As this is a process term, I am advising students to use it based on logic similar to how we treat protein localization terms. Use it to annotate things like the scaffold that brings the channels together, but not for the channels in the cluster.

The paper we're looking at is PMID:27693258 
http://www.sciencedirect.com/science/article/pii/S0896627316305736

In this paper, if I am reading it correctly, AKAP5 acts as a scaffold to cluster channels and GPCRs and who knows what else. It seems to me that there should be related component terms that are the result of the process. But we clearly don't want every possible combination of membrane channels/receptors to be a different term. Not sure what kind of NTR this would create or where it would go in GO.

cc @RLovering

**Comment by bmeldal** [comment]
Could you use the Complex Portal AC in an extension or in with column to indicate what the resulting complex is? I recently curated the AKAP5-calcineurin complexes* and could do the same with the ion channel ones. We probably have a bunch of the ion channel in already, just not with the AKAP5 yet.

*Only one is released and it is missing the Calmodulin subunit. The fix plus the other variants will go out with our next release:
http://www.ebi.ac.uk/intact/complex/details/EBI-12512138

Birgit

**Comment by RLovering** [comment]
Hi Jim

there are function terms: GO:0030159 receptor signaling complex scaffold activity you should consider (which also has the child term GO:0030160 GKAP/Homer scaffold activity) so potentially additional terms could be created here. Although, this might be a term that is going to be deleted with all these revisions going on.

But I agree that a complex term would be good. How about:

GO:0043234 protein complex
>NTR: is_a child scaffold-receptor complex
>>NTR: is_a child postsynaptic density scaffold-receptor complex

GO:0014069 postsynaptic density
>>NTR: is_a child postsynaptic density scaffold-receptor complex

Although, experts might not want to have the postsynaptic density specified in the term. Or it might be felt that GO:0014069 postsynaptic density is sufficiently specific and that you should just use this term.

NTR: is_a child scaffold-transmembrane signaling receptor complex
Definition: A complex of a transmembrane signaling receptor and the anchoring and scaffolding molecules that spatially and functionally organize them. 

NTR: is_a child postsynaptic density scaffold-receptor complex
Definition:  A complex of a neurotransmitter receptor and the anchoring and scaffolding molecules that spatially and functionally organize them. 

Ruth

@dosumis

**Comment by krchristie** [comment]
This might be another ticket that would be good for Barbara (@BarbaraCzub @ukemi). I certainly wouldn't mind relinquishing it as I don't feel very comfortable getting into this.

**Comment by BarbaraCzub** [comment]
@ukemi how many tickets should I aim to 'collect' for the training? Atm I do not have a very good understanding of how much time I should allocate per ticket (that is after agreements have been reached with regard to the new terms). In case of this ticket, it seems that it still requires a discussion about whether the term 'postsynaptic density scaffold-receptor complex' should be created, or not, as @RLovering suggested? 

And wrt the 'scaffold(-transmembrane signaling) receptor complex', it seems that Ruth has suggested two different names, so a decision also needs to be made about whether the shorter or longer version of the name should be used, as Ruth used one in the ontology outline and another one in the definition.

Anyhow, if there are no objections to the new terms that Ruth proposed, I'll be happy to add these to my 'collection', although this will be the third NTR in the compilation. I don't know whether we'll have a chance to go though all of these during the training? So it might get delayed even more.

**Comment by RLovering** [comment]
sorry to be inconsistant, I would be happy with which ever term name seems most appropriate
Ruth

**Comment by raymond91125** [comment]
Should we still consider instantiating a new protein complex in this case? Or perhaps annotate (with GOCAM) as something like "signalling adaptor activity" enabled_by AKAP5 has_input (multiple gene products) calcium channel, potassium channel, and GPCR?

**Comment by raymond91125** [comment]
I propose we close this ticket if no one needs the new term now. @pgaudet

**Comment by pgaudet** [comment]
Right, we do have 'GO:0072578 neurotransmitter-gated ion channel clustering' - that's close enough, isn't it ?

**Comment by raymond91125** [comment]
The request was for a cellular component protein complex but I'm not understanding why that is needed.

**Comment by pgaudet** [comment]
I dont think we can add a CC, unless the composition of the complex is clear. 
In this case a 'scaffold' protein would probably not be considered an integral part of the complex, so this should be annotated as MF 'protein-macromolecule adaptor activity' or a new child and/or BP  'GO:0072578 neurotransmitter-gated ion channel clustering'. 

I dont think there is any action needed. 

Thanks, Pascale
