### ISSUE TITLE
impove name, def for G2 cell size control checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13420]
G2 cell size control checkpoint
current
Definition	A cell cycle checkpoint that monitors cell size, and negatively regulates cell cycle progression between G2 and M phase until a critical size is reached.

rename to 
mitotic G2 cell size control checkpoint
(currently exact synonym)

Def
A *mitotic* cell cycle checkpoint (signaling network) that monitors cell size, and negatively regulates cell cycle progression between G2 and M phase until a critical size is reached.

A DYRK family protein kinase (Pom1  in pombe) forms a spatial gradient and acts as an inhibitor of mitotic entry. As cells increase in size, DYRK kinase levels decrease at the cell division site, leading to mitotic entry. The DYRK spatial gradient and the medial cortical nodes generate information about cell size and coordinate this with mitotic entry by regulating Cdk1 through other mitotic inducer kinases and Wee1.

(I made this def as generic as possible, but so far there is no annotation from other species, I presume the mechanism is conserved when a G2 cell size control checkpoint exists, can be revised if not, but should prevent inappropriate use)

Original papers for the mechanism co published in Nature back in 2009:

PMID:19474789 A spatial gradient coordinates cell size and mitotic entry in fission yeast.
Moseley JB, Mayeux A, Paoletti A, Nurse P

PMID:19474792 Polar gradients of the DYRK-family kinase Pom1 couple cell length with the cell cycle.
Martin SG, Berthelot-Grosjean M

**Comment by ukemi** [comment]
Since it is defined between G2 and M, isn't it necessarily mitotic? I don't think it occurs before meiosis does it?

**Comment by ValWood** [comment]
It is necessarily mitotic from the position, 

but meiosis has G2 and M (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051327)  
can mean meiotic phase as well as "mitotic phase" it seems?

I have no idea yet if there is a cell size checkpoint in during meiotic  G2 before meiotic M-phase 
but if there is, this would also fit the term name G2 cell size control checkpoint. I think it would be better to clarify ...
