### ISSUE TITLE
ntr:sara endosome

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13421]
Could I have the cc term:

sara endosome
Def: A subset of early endosomes characterized by the presence of the membrane-associated adaptor protein, Sara (Smad anchor for receptor activation).
Refs: PMID:25706234, PMID:17110576, PMID:26659188
Synonyms:
Exact: Sara positive early endosomes
Exact: Sara signalling endosome
Exact: Smad anchor for receptor activation signalling endosomes

Is_a 
GO:0005769 early endosome

Thanks

**Comment by bmeldal** [comment]
Without reading the paper (!), could it be a narrow synonym of GO:0005769 early endosome? That's what I've done with many new complex terms were we have variants based on composition only.

If the Sara endosome has a particular function that differentiates it form the 'regular' early endosome it would warrant a new term but would have to go into the def as well.

**Comment by pgaudet** [comment]
Hello, 

I agree with @bmeldal 
From curating endosome/vesicle papers back in my Dicty days, it seems like everyone wants to identify a new type of endosome, so they test new proteins but do not do the extra step of comparing with all known markers, so it's always really hard to tell if you have a different vesicle or just a newly identified protein on a known structure. 

It seems like this is the work of a single group; is this the case ? If it is I would also recommend annotating to an existing term until there is more evidence for the existence of a different functional endosome. 

Thanks, Pascale

**Comment by hattrill** [comment]
Yes, I agree in that I see a lot of different flavoured endosomes, it just that I came across quite a few papers that decribe them going back some time. 

They seem to have a specific function - the partitioning of certain pools of endocytosed signaling factors during cell division.
e.g. Notch ligand and Delta in asymmetric cell division.
PMID:25706234
PMID:24803650
They seem to be distinct in that early Sara -ve endosomes containing Notch ligand and Delta partition equally, but sara +ve partitition asymmetrically.

And symmetric partitioning for decapentaplegic/TGF-beta receptor
PMID:17110576

Now - whether there are different flavours of sara endosomes ....I don't think I could go that far.

**Comment by bmeldal** [comment]
But is the mode of action different? I'd argue different targets don't warrant a new term, only if they actually do something rather different with the the targets.

**Comment by hattrill** [comment]
Difficult to qualify the mode of action of a vesicle. 
Do you think it would be better to capture the BP of the factors that interact with this subset? Something like 'targeting/recruitment of sara endosomes to xxx'? (obsv need to think this through!)

**Comment by hattrill** [comment]
How about this process term? 
"plus-end-directed sara endosome transport along mitotic spindle midzone microtubule"

Or is it specifying the exact target too much? and it should be 
"plus-end-directed endosome transport along mitotic spindle midzone microtubule"

**Comment by pgaudet** [comment]
Hi @hattrill 
Reading the other issue, I agree that the process seems to be what you are trying to capture. Are you OK with '"plus-end-directed endosome transport along mitotic spindle midzone microtubule"? I don't like the parent because the process may occur in the absence of Sara, which would require yet another term. 

If that's OK I will create "plus-end-directed endosome transport along mitotic spindle midzone microtubule". 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi Pascale,

Yes - you're right. Let's go with "plus-end-directed endosome transport along mitotic spindle midzone microtubule".

Thank you!
