### ISSUE TITLE
mp: GO:1901962 S-adenosyl-L-methionine transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13429]
GO:0000095 S-adenosyl-L-methionine transmembrane transporter activity
is a descendant of
GO:0072349 modified amino acid transmembrane transporter activity

but GO:1901962 S-adenosyl-L-methionine transmembrane transport (or more accurately S-adenosyl-L-methionine  transport, though isn't it all transmembrane?)
is not a descendant of
GO:0072337 modified amino acid transport

![parent](https://cloud.githubusercontent.com/assets/7359272/25480512/e84ce9aa-2b40-11e7-9a2c-f219cc8b68d5.jpg)

spotted because in our summary view redundant terms would be hidden, and this is not redundant:
![pet](https://cloud.githubusercontent.com/assets/7359272/25480469/c635c29c-2b40-11e7-9b53-cbf7ad1f4374.jpg)

**Comment by pgaudet** [comment]
Hi @ValWood 
It seems to me that the 'modified amino acid' bit is the one that is out of place; what do you think? There are 6 terms using the string: 
Function 	GO:0072341 	modified amino acid binding 	
Process 	GO:0072337 	modified amino acid transport 	
Process 	GO:0006575 	cellular modified amino acid metabolic process 	
Process 	GO:0042219 	cellular modified amino acid catabolic process 	
Process 	GO:0042398 	cellular modified amino acid biosynthetic process 	
Function 	GO:0072349 	modified amino acid transmembrane transporter activity 

The children of these terms are biologically unrelated, for instance: 
'3-sulfino-L-alanine binding'
'dihydrofolic acid binding'
'folic acid binding'
'glutathione binding'
'L-DOPA binding'
'phosphatidylserine binding'
'phosphopantetheine binding'

Is the grouping these terms necessary ? It seems to recapitulate their biosynthetic mechanism more than anything else. 

I could not find 'modified amino acid' in CheBI, so I assume that this is not the source of this term? I see @hdrabkin has requested 'CHEBI:63472 - modified amino acid anion' but I cannot tell when that was. The entry is under review. 

My inclination would be to obsolete these 6 terms and rehouse their children. 

Thoughts ? 

Pascale

**Comment by ValWood** [comment]
I agree, I don't think it is a particularly useful term.I never saw it before until today... I suspect it means "amino acid derivative". .....

**Comment by hdrabkin** [comment]
I think they might be under residue, like modified amino acid residue, especially if its in a protein

**Comment by pgaudet** [comment]
@hdrabkin  Within a peptide/protein that makes sense biologically. But 'folic acid is_a' modified amino acid ?

**Comment by hdrabkin** [comment]
Yes, CHEBI: An N-acyl-amino acid that is a form of the water-soluble vitamin B

**Comment by pgaudet** [comment]
Hi @hdrabkin 
Sorry I didnt mean to imply that this was no true, I was wondering whether this was interesting to GO. 
What I see is that folic acid is a N-acyl amino acid. Why is it a 'modified aa'? relative to what ? It seems like it's either (a) relative to the standard 20 aa, or (b) relative to the previous amino acid in the synthesis pathway. 
If it's (a), then it's biologically relevant when the modification occurs within a protein. 
If it's (b), then all aa are modified from the previous amino acid in the synthesis pathway. 

I hope I am formulating this more clearly now. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
They don't classify based on how it is made; It's just classified as a chemical, and folic acid is an acyl amino acid.

**Comment by pgaudet** [comment]
Makes sense. Would you agree to move it under 'amino acid transport' rather than 'modified amino acid transport'? 

It's the modified that seems extraneous to me.

**Comment by hdrabkin** [comment]
still a modified amino acid, not necessarily still an amino acid; I'd leave it there.
From CHEBI:
folic acid (CHEBI:27470) is a N-acyl-amino acid (CHEBI:51569)
N-acyl-amino acid (CHEBI:51569) is a amino acid derivative (CHEBI:83821)

**Comment by pgaudet** [comment]
Hello @hdrabkin 

In ChEBI amino acid derivative is defined as "Any derivative of an amino acid resulting from reaction at an amino group, carboxy group, side-chain functional group, or from the replacement of any hydrogen by a heteroatom. The definition normally excludes peptides containing amino acid residues." 

In the go-edit version there is a term named "modified amino-acid residue" (I don't know via which source), that is defined as "An organic group that results from covalent modification or chemical alteration to the side chain or backbone atoms of an amino acid residue or derivative thereof, where such alteration maintains the integrity of the amino acid chain containing the residue."

So a derivative would *not* necessarily be an amino acid. 

Maybe we can talk about that at today's call ? 

Pascale

**Comment by hdrabkin** [comment]
I think CHEBI keeps the amino acid and the amino acid derivate separate because if you define an amino acid has having a NH3+ and a COO- attached directly to the same carbon (alpha carbon). then any adduct involving the NH3 or COO- no longer has the NH3_ and COO-, 
Note not ALL amino acid derivatives would involve the alpha amino and carboxy groups (like any modification of the R groups, in which case they could technically still be classified as amino acids.

Once incorporated into a polypeptide chain, they are now residues (no longer the free amino acid).

**Comment by pgaudet** [comment]
Hello,

One more question: It looks like the reasoner is not transitive over the relation 'transports or maintains localization of', is this right ? 
The logical definition of 'S-adenosyl-L-methionine transmembrane transport' 
is 
"transport
 and  ('results in transport across' some membrane)
 and  ('transports or maintains localization of' some S-adenosyl-L-methionine)"
but that does not make the term an inferred subclass of ''modified amino acid transport''. Is this the expected behavior? 

Thanks again, 
Pascale

**Comment by ukemi** [comment]
S-adenosyl-L-methionine is not classified as an amino-acid derivative in ChEBI. If you want the above classification, that relation needs to be requested in ChEBI.

**Comment by pgaudet** [comment]
Oh. Well, the definition is "A sulfonium compound that is the S-adenosyl derivative of L-methionine. It is an intermediate in the metabolic pathway of methionine." 

So the textual def and the parents are inconsistent. 
http://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:15414

So I will remove the parent 'modified amino acid' from terms containing "S-adenosyl-L-methionine". 

I hope that's right ! 

Pascale

**Comment by ValWood** [comment]
Sounds OK...
