### ISSUE TITLE
ntr: positive regulation of protein localization to medial cortex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13422]
descendant of
GO:1904778	positive regulation of protein localization to cell cortex	

standard def

Ref: PMID:19474789

**Comment by ValWood** [comment]
was going to add cell division site as an additional parent, but I found the term under here:

GO:0071574 Name	protein localization to medial cortex

and the term I want more precisely
GO:1902577
Name	protein localization to medial cortical node
so just a "positive regulation" term for this please

**Comment by ValWood** [comment]
Hi Harold,

Could you add this one for me quite soon? I'm preparing some examples for the pombe meeting and I need the update to filter through for my slides ;)

Thanks

Val

**Comment by hdrabkin** [comment]
Sorry now I'm confused; are you requesting one terms?
positive regulation of protein localization to medial cortex, child of GO:1904778 positive regulation of protein localization to cell cortex?  (so a postive regulation child of another positive regulation term)
OR,
positive regulation of protein localization to medial cortex, child of protein localization to medial cortical node
??

**Comment by ValWood** [comment]
the term I want is
positive regulation of protein localization to medial cortex


a descendant of both
GO:1904778	positive regulation of protein localization to cell cortex
and
GO:0071574  protein localization to medial cortex


I guess you might bee to add  the intermediate term
regulation of protein localization to medial cortex
too?

**Comment by hdrabkin** [comment]
made "positive regulation of protein localization to medial cortex" subclass of e new term "regulation of protein localization to medial cortex" instead of protein localization to medial cortex", as well as also subclass of positive regulation of protein localization to cell cortex

**Comment by hdrabkin** [comment]
done

**Comment by ValWood** [comment]
thanks harold....

**Comment by hdrabkin** [comment]
buy me a pint in October!

**Comment by ValWood** [comment]
OK. I might need to buy you another pint in a minute....

**Comment by ValWood** [comment]
Two Nature papers were co-publised and it struck me when I was curating the second paper, that I might have this the wrong way around

PMID:19474792
Polar gradients of the DYRK-family kinase Pom1 couple cell length with the cell cycle.
Martin SG, Berthelot-Grosjean M

So I contacted the author 
…the prevalent model is that direct phosphorylation of Cdr2 by Pom1 in its membrane-binding region weakens Cdr2’s affinity to the membrane. So, the idea is that in the WT, Cdr2 is prevented to localise at cell poles because of Pom1 phosphorylating it. Cdr2 then localises where it is not (or less) phosphorylated by Pom1 - i.e in the cell middle. I would thus stick with Pom1 negatively regulating Cdr2 localisation to cell poles, rather than positively promoting its medial retention. 

So ....... cdr2 would localise to the medal region anyway. Pom1 is not positively regulating this. Instead it is negatively regulating its localisation towards the cell tips…

I need 
negative regulation of protein localization to cell cortex of cell tip
descendant of

GO:1990895 regulation of protein localization to cell cortex of cell tip

v

**Comment by hdrabkin** [comment]
done
