### ISSUE TITLE
TPV: GO:1905144 response to acetylcholine

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13430]
Is a child of 

response to ammonium ion.
I can't figure why....

**Comment by ValWood** [comment]
response to morphine too?

**Comment by ValWood** [comment]
Lots....

**Comment by ukemi** [comment]
Because they are:
ChEBI:58097 is the conjugate acid of morphine, which is a ammonium ion.
acetylcholine is_a acylcholine is_a quaternary ammonium compound.

**Comment by ValWood** [comment]
wow ok....
