### ISSUE TITLE
Need SOP for adding new imported terms

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#13433]
The file 
http://www.geneontology.org/quality_control/annotation_checks/taxon_checks/taxon_union_terms.obo

We need a new union that isn't in the above file; 
Bacteria or Archaea
We also note that several of items in the above file are not imported into protege.

**Comment by ukemi** [comment]
NCBITAXON_Union:0000004?

**Comment by hdrabkin** [comment]
That one will do. But we still need SOP for the ones that aren't available.

**Comment by ukemi** [comment]
Yes. this is a more general issue of how to request new imports.

**Comment by cmungall** [comment]
I gave a quick demo of how to do this on the last call when you were away, the goal would be to get others able to do this.

But there are extra steps with the NCBITaxon union. We run a DL-reasoner (UnionOf is outside EL) to materialize a subClassOf hierarchy (so for example, HumanOrYeast SubClassOf Opisthokonte).

**Comment by ukemi** [comment]
OK. We need to get this into the ontology developers' SOP documentation.

**Comment by ukemi** [comment]
I have added a section to the ontology editors' documentation about adding import requests to the respective .txt files.
