### ISSUE TITLE
Should multiply labeled edges be caught by Travis?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#13445]
https://build.berkeleybop.org/job/release-go-ontology-daily-snapshot/133/

Removed: 2187 links
 :: ERROR: multiply-labeled-edge: GO:0035278 GO:0006412 --> regulates negatively_regulates
 Makefile:188: recipe for target 'go-basic.obo' failed
make: *** [go-basic.obo] Error 1
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

I think the changing the logical def of GO:0035278 from:

'regulation of biological process'
 and (mediated_by some miRNA)
 and ('directly negatively regulates' some translation)

to

biological_process
 and (mediated_by some miRNA)
 and ('directly negatively regulates' some translation)

might fix this, but I am not sure that this is invalid in the non-filtered file. If you think this is the correct fix, I will make the simple edit.

**Comment by hdrabkin** [comment]
I've looked at some other terms and 
'biological regulation '
and ('positively/negatively regulates' some 'blah") also appears to work
eg: GO:0061767, negative regulation of lung blood pressure

**Comment by cmungall** [comment]
Travis config is correct, but really this should be filtered as a redundancy.

Your fix above corresponds to the DP for regulation, so it's good to do it anyway.

**Comment by hdrabkin** [comment]
I have fixed this so that the jenkins builds proceed.

**Comment by hdrabkin** [comment]
I made the change but Jenkins still redballed with SAME issue

**Comment by hdrabkin** [comment]
I looked and my fix seems to be reset to what it was, and not biological_process. Will try again.

**Comment by hdrabkin** [comment]
SUCCESS! Blue Ball!!
