### ISSUE TITLE
term to obsolete? - bacterial-type flagellar cytoplasm

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13440]
Hi,

I'm working on propagating 'plasma membrane bounded cell projection' as a subtype of 'cell projection' and I have come across this term: **bacterial-type flagellar cytoplasm**
 
This term seems to be based on a misconception. However, the bacterial flagellum is not plasma membrane bounded so the definition is erroneous.

There are no annotations, so I think I should just delete this term.

@jimhu-tamu  is there any need to talk about bacterial flagellar cytoplasm? It seems to me that although the hook and the motor are located within the cytoplasm, that there is no bacterial flagellar cytoplasm to talk about, as the bacterial flagellum just isn't a membrane bounded cell projection anyway.
 

ID: GO:0097015
Name: bacterial-type flagellar cytoplasm
Ontology: cellular_component
Synonyms: bacterial-type flagellum cytoplasm
Definition: All of the contents of a bacterial-type flagellum, excluding the plasma membrane surrounding the flagellum. Source: GOC:BHF 
http://amigo.geneontology.org/amigo/term/GO:0097015

**Comment by jimhu-tamu** [comment]
I agree that it doesn't make sense.  It appears that there already the children I would expect for GO:0044461 bacterial-type flagellum part.

It looks like it was added in 2011 as part of an effort to add parts to the microtubule-based flagella from eukaryotes. I found this imported tracker item: #8434

It looks like @RLovering and @paolaroncaglia might recall the history.

**Comment by krchristie** [comment]
Thanks for finding that ticket @jimhu-tamu 

It looks to me like it was just a case of we should make the parallel term for the bacterial type flagellum term that we are making for the eukaryotic type flagellum.

Since you agree that it doesn't make sense, I'm going to propose its obsoletion.

thanks!

**Comment by krchristie** [comment]
obsoletion email sent out on June 6th, with deadline for comments on June 13, and plan to obsolete on June 14
