### ISSUE TITLE
merge GO:0080039 and GO:0016762

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#13463]
While trying to annotate from PMID:28443615, I came across these two seemingly identical terms which I think should be merged.

[Term]
id: GO:0016762
name: xyloglucan:xyloglucosyl transferase activity
namespace: molecular_function
def: "Catalysis of the cleavage of a beta-(1->4) bond in the backbone of a xyloglucan and transfers the xyloglucanyl segment on to O-4 of the non-reducing terminal glucose residue of an acceptor, which can be a xyloglucan or an oligosaccharide of xyloglucan." [EC:2.4.1.207]
synonym: "endo-xyloglucan transferase activity" EXACT [EC:2.4.1.207]
synonym: "endoxyloglucan transferase activity" EXACT []
synonym: "xyloglucan endotransglycosylase activity" EXACT [EC:2.4.1.207]
synonym: "xyloglucan:xyloglucan xyloglucanotransferase activity" EXACT [EC:2.4.1.207]
xref: EC:2.4.1.207
xref: MetaCyc:2.4.1.207-RXN
is_a: GO:0016758 ! transferase activity, transferring hexosyl groups

and 

[Term]
id: GO:0080039
name: xyloglucan endotransglucosylase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of a beta-(1,4) bond in the backbone of a xyloglucan and transfers the xyloglucanyl segment on to O-4 of the non-reducing terminal glucose residue of a xyloglucan or an oligosaccharide of xyloglucan." [EC:2.4.1.207, GOC:ask, PMID:1400418, PMID:1554366]
is_a: GO:0046527 ! glucosyltransferase activity

**Comment by hdrabkin** [comment]
I decided to keep the primary id: GO:0016762, name: xyloglucan:xyloglucosyl transferase activity because that is the name the EC number refers to.

**Comment by hdrabkin** [comment]
done

**Comment by tberardini** [comment]
Thanks @hdrabkin
