### ISSUE TITLE
OTR: GO:0019054 modulation by virus of host process - remove parent 'normal cellular process': GO:0050794 regulation of cellular process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13468]
After discussion with the ViralZone group, we propose to remove the  'normal cellular process' parent GO:0050794 regulation of cellular process from the term 'GO:0019054 modulation by virus of host process', and similarly for children, we propose to remove links to normal *cellular* processes. This affects for example: 

GO:0044863 	modulation by virus of host cell division
GO:0019055 	modification by virus of host cell cycle regulation
GO:0060141 	positive regulation of syncytium formation by virus
GO:0039514 	suppression by virus of host JAK-STAT cascade
GO:0060153 	modulation by virus of host cell cycle
GO:0075528 	modulation by virus of host immune response
GO:0044833 	modulation by virus of host protein transport
GO:0006948 	induction by virus of host cell-cell fusion
GO:0060139 	positive regulation of apoptotic process by virus
GO:0039595 	induction by virus of catabolism of host mRNA
GO:0039596 	modulation by virus of host protein dephosphorylation
GO:0039612 	modulation by virus of host protein phosphorylation
GO:0039519 	modulation by virus of host autophagy
GO:0039522 	suppression by virus of host mRNA export from nucleus
GO:0039525 	modulation by virus of host chromatin organization
GO:0039526 	modulation by virus of host apoptotic process
GO:0039527 	suppression by virus of host TRAF-mediated signal transduction
GO:0044828 	negative regulation by host of viral genome replication
GO:0039648 	modulation by virus of host protein ubiquitination
GO:0039636 	suppression by virus of host cell wall biogenesis
GO:1903652 	modulation by virus of host cytoplasmic transport
GO:0039656 	modulation by virus of host gene expression
GO:0098673 	inhibition of host DNA replication by virus
GO:0061765 	modulation by virus of host NIK/NF-kappaB signaling

Pascale

**Comment by hdrabkin** [comment]
Jenkins fails: appears that GO:0039692 has no is_a parent; should it have viral RNA genome replication as the parent?
Has only part_of  links;
Would have thought Travis would catch this?

**Comment by plemercier** [comment]
Dear all,

I agree this term  is_a "RNA genome replication"

cheers


*Philippe Le Mercier*, PhD
Head of Swiss-Prot virus program
*SIB| Swiss Institute of Bioinformatics
*Geneva, Switzerland
viralzone.expasy.org
Tel: +41 22 379 58 70

**Comment by pgaudet** [comment]
I used 'viral RNA genome replication' - I guess we mean the same thing sine 'RNA genome replication' doesn't exist as far as I can tell. 
Thanks, 
Pascale
