### ISSUE TITLE
OTR: Comment on GO:0019060 intracellular transport of viral protein in host cell 

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#13478]
The stanza for GO:0019060 intracellular transport of viral protein in host cell includes the following comment:

> This term is for annotation of the movement of individual viral proteins, rather than the whole viral particle.

It seems like this comment is misleading in that it can be read to suggest that viral protein cargoes should be annotated to GO:0019060. But the existing experimental annotations are more consistent with our practice for use of protein localization terms. The annotations are to cellular proteins involved in the movement of viral cargoes, not viral proteins being moved.

**Comment by pgaudet** [comment]
Hi @jimhu-tamu 

You are right, this term is not very clear. The synonyms are confusing and the usage is very inconsistent. 

pmasson55 your suggestions are welcome ! 

Pascale

**Comment by pmasson55** [comment]
I agree this term is very misleading and should be improved. It seems that Interpro used it to annotate the adenovirus shutoff protein that acts as a chaperone to the hexon protein and directs it to the host nucleus. However this term has also been assigned to mammalian proteins. In addition, the synonym terms are also misleading: viral capsid transport in host cell nucleus, intracellular viral protein transport, intracellular viral capsid transport and viral capsid transport in host cell cytoplasm are complete different concepts and shouldn't be used as exact synonyms. So I suggest to remove this misleading GO term or change it to be more accurate.

**Comment by pgaudet** [comment]
Hi @pmasson55 , 

Thanks for the input.Do you have suggestions for re-housing the existing annotations? 

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
I agree that the comment and synonyms are confusing. But it seems to me that being used for proteins encoded by both the host and the virus is not a problem if we agree that this is not about annotating cargoes. Perhaps it's reviewing the practice for the parent term GO:0006886 intracellular protein transport more thoroughly,  but a cursory look at that is consistent with my understanding of how protein localization terms have been annotated. Machinery, not cargoes.

But I suspect that this touches on the other issue @pgaudet and I have been discussing about what constitutes a cellular vs host cellular process.

**Comment by pgaudet** [comment]
We may propose to obsolete. Currently reviewing existing annotations: 
F1SF88	-
P09914	IFIT1
P63172	DYNLT1
Q03518	TAP1
Q03519	TAP2
Q9BUN8	DERL1
InterPro:IPR003381

Thanks, Pascale

**Comment by RLovering** [comment]
The GO editors usually provide the source of these annotations as it is not efficient having 13 groups all checking to see if they created these annotations

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

Indeed ! Sorry I omitted the 'I' in the previous comment "Currently reviewing existing annotations with @pmasson55"; if there are questions/suggestions for changes we will contact the appropriate groups. 

Pascale

**Comment by pgaudet** [comment]
Changed the comment to "This term is for annotation of proteins responsible for the movement of individual viral proteins, rather than the whole viral particle. "

**Comment by pgaudet** [comment]
- [ ]  Fixed axioms referring to 'cell', 'nucleus' etc rather than 'host cell', host cell nucleus', etc
- [ ]  Must fix (remove?) synonyms: 
viral capsid transport in host cell nucleus, 
 intracellular viral protein transport, 
 intracellular viral capsid transport and 
 viral capsid transport in host cell cytoplasm
