### ISSUE TITLE
loading http://purl.obolibrary.org/obo/go/extensions/go-plus.owl in protege shows many missing imports

### ISSUE THREAD

**Issue by alanruttenberg** [geneontology/go-ontology#13474]
Captured screenshot. Elements in imported ontology pane with location noted are missing.

![screen shot 2017-05-07 at 8 45 18 pm](https://cloud.githubusercontent.com/assets/241934/25786595/1df515f0-3366-11e7-8681-228a6f7acc36.PNG)

**Comment by cmungall** [comment]
I can't replicate this with the OWLAPI. What does the magenta block mean in Protege? I don't follow what is being shown with the Location info in Protege. What's the underlying semantics? Is the import not available from it's URL? Or does the declared URI not match the URI in the import declaration?

Could have been a temporary network glitch. Things will be switched to S3/cloudfront soon

**Comment by alanruttenberg** [comment]
Magenta block is just what I happened to have highlighted. The location information says what the ontology IRI is and where it was loaded from. If off the web it is the same as the ontology IRI, if a catalog is used it notes where it loaded the ontology from according to the catalog. 

Just tried it again and it worked this time, so yeah, guess it was a network glitch. Closing.

**Comment by cmungall** [comment]
OK, looks like mismatch between 

```
2017-05-08 08:59:03,164 INFO  (ParserWrapper:75) Start loading ontology: http://purl.obolibrary.org/obo/go/imports/oba_import.owl from: http://purl.obolibrary.org/obo/go/imports
/oba_import.owl
2017-05-08 08:59:03,563 INFO  (ParserWrapper:82) Finished loading ontology: http://purl.obolibrary.org/obo/go/extensions/oba_import.owl from: http://purl.obolibrary.org/obo/go/i
mports/oba_import.owl
```
