### ISSUE TITLE
NTR: regulation terms for GO:0061517 macrophage proliferation

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13470]
Could I please have regulation (and +ve, -ve) for GO:0061517 macrophage proliferation.

Needed for annotation of PMID:27756793.
Please add GOC references GOC:rph, GOC:BHF and GOC:BHF_miRNA.

Thanks,
Rachael.

**Comment by krchristie** [comment]
Here are your terms.

+id: GO:0120040
+name: regulation of macrophage proliferation
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of macrophage proliferation." [GOC:BHF, GOC:BHF_miRNA, GOC:rph]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: regulates GO:0061517 ! macrophage proliferation
+created_by: kchris
+creation_date: 2017-05-10T20:38:19Z
+
+[Term]
+id: GO:0120041
+name: positive regulation of macrophage proliferation
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of macrophage proliferation." [GOC:BHF, GOC:BHF_miRNA, GOC:rph]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: positively_regulates GO:0061517 ! macrophage proliferation
+created_by: kchris
+creation_date: 2017-05-10T20:45:01Z
+
+[Term]
+id: GO:0120042
+name: negative regulation of macrophage proliferation
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of macrophage proliferation." [GOC:BHF, GOC:BHF_miRNA, GOC:rph]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: negatively_regulates GO:0061517 ! macrophage proliferation
+created_by: kchris
+creation_date: 2017-05-10T20:51:40Z
