### ISSUE TITLE
Put up prototype of TG replacement before Corvalis meeting

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13472]
We will use table-edit/taboggan as TG replacement. Essentially same operation as adding a row.

 * [x] move repo containing DOSDP yamls #13273 
 * [ ] configure to use the relevant autocomplete: GO, Uberon, CL, PO, OBA, PATO, CHEBI
 * [ ] seed a csv from the ontology plus a given DP using @balhoff's https://github.com/balhoff/dosdp-scala, place in repo
 * [ ] configure a table-edit page (preferably with a 'badge' ([see](https://github.com/INCATools/table-editor/issues/6) )
 * [ ] demonstrate a cycle of adding a new row, saving, run reasoner

**Comment by jmcmurry** [comment]
cc: @doctorbud, @dougli1sqrd

**Comment by ValWood** [comment]
Yay... we miss TG....

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/13486 for the first point

**Comment by cmungall** [comment]
For @DoctorBud's demo, we will use this tsv that we re-engineered from the OWL using @balhoff's dosdp-tools: [src/design_patterns/validated_patterns/activator_activity.tsv](https://github.com/geneontology/go-ontology/blob/tg-demo/src/design_patterns/validated_patterns/activator_activity.tsv_

(this is on the tg-demo branch in Pr #13566)

The corresponding yaml is [src/design_patterns/validated_patterns/activator_activity.yaml]
(https://github.com/geneontology/go-ontology/blob/tg-demo/src/design_patterns/validated_patterns/activator_activity.yaml)

(also on master)

**Comment by dosumis** [comment]
I already built that tsv. See pattern implementation tsv dir.

**Comment by DoctorBud** [comment]
Closing this ticket because the goal has been achieved, the demo is over, and the time has passed. Even though there is rich reference material here, the ticket should not be on the active list.

**Comment by dosumis** [comment]
#13692 New umbrella ticket covering steps needed to get the TG replacement up and running.
