### ISSUE TITLE
NTR: pore formation during contractile vacuole discharge

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#13475]
This process is unique to CV discharge as the membranes do not fuse like in exocytosis. Crossed my mind before, maybe none of the CV discharge terms should be exocytosis??

DEF exocytosis: A process of secretion by a cell that results in the release of intracellular molecules (e.g. hormones, matrix proteins) contained within a membrane-bounded vesicle by fusion of the vesicle with the plasma membrane of a cell..."

Could be moved up to 'secretion' ... Or relax what exocytosis is. Of course the CV research in Dicty sees a LOT of analogy between the processes except the actual discharge. The conserved exocyst is involved like in exocytosis and many other proteins, like draining, disgorging are very conserved. 

Nature was probably just economical and uses same components as Dicty has both, CV discharge and regular exocytosis. And the processes might be different enough (CV recycling might also be different) that we can separate them as two siblings of secretion? I could ask Thierry, but like always, the researchers are baffled with the details we want to nail!

GO:0070177 contractile vacuole discharge
part_of GO:NEW pore formation during contractile vacuole discharge

DEF: The formation of a transient pore in the plasma membrane and the attached contractile vacuolar membrane, to release water from the cell. This process does not involve fusion of the two membranes.

From the paper PMID 22323285: the exocyst bound to activated rab8A and disgorging form the pore 'complex', regulated by drainin.

Should this term then also be a child of GO:0046931 pore complex assembly?

Thanks!!
Petra

**Comment by pgaudet** [comment]
Hi Petra, 

I am not sure how to deal with our question 'is CV discharge a type of exocytosis? '. Can you check with Thierry? That seems high level enough to ask a scientist! 

Thanks, Pascale

**Comment by pfey03** [comment]
Ok, will send an email to Thierry, let you know what he says - thanks!

**Comment by pfey03** [comment]
Hi Petra,

Kiss and run is the accepted scientific term !!
Cheers,

Thierry



On 13 May 2017, at 16:24, Petra Fey <pfey@northwestern.edu> wrote:

Hello Thierry,

Thank you for this nice info. I discuss with GO folks and I think the definition of exocytosis needs rephrasing so all different kinds have that one umbrella term. 

Is there another word for ‘kiss and run’ exocytosis that is more scientific? It might warrant a new branch under exocytosis and then CV discharge would be a child of that.

Thanks again and enjoy your weekend,

Petra

On 13. May 2017, at 16:09, Thierry Soldati <Thierry.Soldati@unige.ch> wrote:

Dear Petra,

Thanks for your message and for the deep thoughts about CV discharge.
I have the impression that it indeed requires clarification. I understand your argument “Since the CV discharge does not involve the fusion between the CV and plasma membrane, this definition is not true for CV discharge.” But be aware that there are different cases of exocytosis. Many exocytic events do involve full and irreversible fusion of the exocytic vesicle or compartment with the plasma membrane, followed by recycling of the components that have thus reached the surface, by compensatory endocytosis. But there is a well studied case of so-called “kiss and run” exocytosis, which involves the formation of a transient contact, a pore, between a granule (for exemple of chromaffin cells) and the plasma membrane. This most of the time leads only to partial secretion of the granule content. The granule can undergo series of partial, kiss and run exocytosis, until it finally fuses with the plasma membrane (or not).
Therefore, the discharge is EXACTLY like that (hence our title). The machinery used, the Rab GTPases, the participation of actin, or BEACH-domain containing proteins, and of the exocyst is extremely well conserved.
Therefore, please, leave discharge and exocytosis in the same basket !
With kind wishes,

Thierry


On 12 May 2017, at 16:40, Petra Fey <pfey@northwestern.edu> wrote:

Dear Thierry,

I’m curating your 2012 Paper "Rab8a regulates the exocyst-mediated kiss-and-run discharge of the Dictyostelium contractile vacuole” and need a few more GO terms for that. I already got some new terms:
 - contractile vacuole tethering involved in discharge GO:0140025
- contractile vacuole dissociation from plasma membrane GO:0140026
- pore formation during contractile vacuole discharge - in process

Adding these terms I noticed that all CV discharge terms are children of GO:0006887 exocytosis, which is defined:
"A process of secretion by a cell that results in the release of intracellular molecules (e.g. hormones, matrix proteins) contained within a membrane-bounded vesicle by fusion of the vesicle with the plasma membrane of a cell…"

Since the CV discharge does not involve the fusion between the CV and plasma membrane, this definition is not true for CV discharge.

So I wonder, if 

A) CV discharge is considered a form of exocytosis as many of the steps are similar and involve the same players, then the definition of ‘exocytosis’ needs to be widened and less restrictive.
or
B) CV discharge is not strict exocytosis but another form of secretion, then the whole CV discharge terms will be moved up to be children of GO:0032940 secretion by cell.

Let me know what you, as a phago/exocytosis/CV expert think about the distinction that we need to draw for correct GO representation.

Many thanks and greetings from Madrid,

Petra
