### ISSUE TITLE
cellular_component -> BFO mapping, switch to material entity

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13489]
cellular_component is currently mapped to BFO continuant.  It should actually be mapped to BFO material entity. This is justified because, while we have terms for things that sound immaterial in CC, they actually refer to the contents of these spaces (vesicle lumen = content of vesicle).  Fixing this removes a bunch of confusing high-level inferences coming from relation domain and ranges. e.g.

![image](https://cloud.githubusercontent.com/assets/112839/25994470/da644826-3705-11e7-9342-825a426219ee.png)

**Comment by ukemi** [comment]
+1

**Comment by dosumis** [comment]
Fixed - Complete fix for overzealous BFO inference requires #13396 too.
