### ISSUE TITLE
Extracellular exosome parentage

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13497]
Hi,

I think GO:0070062 extracellular exosome should be a direct child of GO:0005615 extracellular space, as they are present in the interstitial fluid and blood (see 
https://en.wikipedia.org/wiki/Exosome_(vesicle)). Currently this term is a descendant of extracellular region.

Rachael.

**Comment by ukemi** [comment]
Yes. If you click on the link in the above closed message, you will see the diff. I trusted you were correct.

**Comment by rachhuntley** [comment]
Ah OK, thanks!
