### ISSUE TITLE
NTRs for stereocilia 

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13495]
I need a new term for 'stereocilium maintenance'

with relationships to these two terms, possibly as logical def.

GO:0071956 - cellular component maintenance (BP)
GO:0032420 - stereocilium (CC)

for annotation of mouse Tprn from PMID-27693694

**Comment by krchristie** [comment]
Looking at this review, PMID:27565685, I would also like to have terms for two more parts of the stereocilium, specifically the shaft and the base. We already have a term for the tip.

**term**: stereocilium base
**Def**: The tapered base of the stereocilium adjacent to where it joins the hair cell body. This region contains a rootlet comprised of bundled actin filaments which spans the joint and stabilizes the stereocilium.
synonym: stereocilium taper
* Annotation comment: It would be good to update the annotation of mouse Tprn to 'stereocililum' from PMID:20170899 to this term for the base.

**term**: stereocilium shaft
**Def**: The shaft comprises the majority of the length of the stereocilium. This region is notable for the extreme stability of actin filaments, which are highly crosslinked into a parallel bundle. 

Based on this review, I would like to add a little more to the def of the 'stereocilium tip'
**from:** A distinct compartment at the tip of a stereocilium, distal to the site of attachment to the apical cell surface. It consists of a dense matrix bridging the barbed ends of the stereocilium actin filaments with the overlying plasma membrane.
**to:** A distinct compartment at the tip of a stereocilium, distal to the site of attachment to the apical cell surface. It consists of a dense matrix bridging the barbed ends of the stereocilium actin filaments with the overlying plasma membrane, is dynamic compared to the shaft, and is required for stereocilium elongation.

**Comment by krchristie** [comment]
@ukemi  Let me know if you have any comments or objections to what I'd like to do on this ticket.

**Comment by ukemi** [comment]
This looks ok, but there are currently no logical defs for these kinds of terms.

**Comment by krchristie** [comment]
The term 'maintenance of synapse structure', which is one of the current child terms of 'cellular component maintenance', has a logical def: 

<pre>'cellular process'
 and (results_in_maintenance_of some synapse)</pre>

 so I was thinking it might be possible to make one parallel to that for stereocilium maintenance.

**Comment by krchristie** [comment]
I didn't bother with a logical def for 'stereocilium maintenance'.

Here is what I put in: 

id: GO:0032426
 name: stereocilium tip
 namespace: cellular_component
-def: "A distinct compartment at the tip of a stereocilium, distal to the site of attachment to the apical cell surface. It consists of a dense matrix bridging the barbed ends of the stereocilium actin filaments with the overlying plasma membrane." [GOC:ecd, PMID:17021180]
+def: "A distinct compartment at the tip of a stereocilium, distal to the site of attachment to the apical cell surface. It consists of a dense matrix bridging the barbed ends of the stereocilium actin filaments with the overlying plasma membrane, is dynamic compared to the shaft, and is required for stereocilium elongation." [GOC:ecd, GOC:krc, PMID:17021180, PMID:27565685]
 is_a: GO:0005575 ! cellular_component
 relationship: part_of GO:0032420 ! stereocilium
 
@@ -472232,6 +472232,37 @@ created_by: kchris
 creation_date: 2017-05-10T20:51:40Z
 
 [Term]
+id: GO:0120043
+name: stereocilium shaft
+namespace: cellular_component
+def: "The shaft comprises the majority of the length of the stereocilium. This region is notable for the extreme stability of actin filaments, which are highly crosslinked into a parallel bundle." [GOC:krc, PMID:20170899]
+is_a: GO:0005575 ! cellular_component
+relationship: part_of GO:0032420 ! stereocilium
+created_by: kchris
+creation_date: 2017-05-15T20:38:32Z
+
+[Term]
+id: GO:0120044
+name: stereocilium base
+namespace: cellular_component
+def: "The tapered base of the stereocilium adjacent to where it joins the hair cell body. This region contains a rootlet comprised of bundled actin filaments which spans the joint and stabilizes the stereocilium." [GOC:krc, PMID:20170899]
+synonym: "stereocilium taper" EXACT []
+is_a: GO:0005575 ! cellular_component
+relationship: part_of GO:0032420 ! stereocilium
+created_by: kchris
+creation_date: 2017-05-15T20:45:06Z
+
+[Term]
+id: GO:0120045
+name: stereocilium maintenance
+namespace: biological_process
+def: "The organization process that preserves a stereocilium in a stable functional or structural state." [GOC:krc, PMID:27693694]
+is_a: GO:0043954 ! cellular component maintenance
+is_a: GO:0060122 ! inner ear receptor stereocilium organization
+created_by: kchris
+creation_date: 2017-05-15T20:55:13Z

**Comment by ukemi** [comment]
OK. Sounds good.
