### ISSUE TITLE
Retrofit all molecular function regulators to follow latest pattern

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13492]
* [DOSDP - activator activity](https://github.com/geneontology/design_patterns/blob/master/validated_patterns/activator_activity.yaml)
* [tsv of existing terms + python code used to generate](https://gist.github.com/dosumis/4d899727896367c9b432e733e120b675)
* Use [dosdp-scala](https://github.com/balhoff/dosdp-scala)

Needs to support keeping references.  This should work, given pattern spec.  

To be determined: 
- How do we flush and replace old terms?
- Should we move this whole branch to autogeneration?

TODO:
  - [x] Edit script so that tsv conforms to spec for dosdp-scala
  - [ ] Generate terms
  - [ ] ...

(Ticket split off from #12995)  CC @cmungall @balhoff  - This is a good branch for implementing generation with dosdp-scala. It'd be great if we could have this working before the Corvalis meeting.

**Comment by dosumis** [comment]
TSVs here: https://github.com/geneontology/go-ontology/tree/master/src/pattern_implementation_tsv

**Comment by cmungall** [comment]
Ignore the hash-mention above, wrong ticket

**Comment by dosumis** [comment]
This partly works


`dosdp-scala generate --obo-prefixes=true --template=design_patterns/validated_patterns/activator_activity.yaml --infile=pattern_implementation_tsv/activator_activity.tsv --outfile=activator_activity.ofn --ontology=../go-simple.obo`

But only after changing IDs in pattern to OBO style to fit with --obo-prefixes (should be discussed).

BUG: def_dbxrefs end up like this:

GOC:BHF,GOC:dph,GOC:tb

>

![image](https://cloud.githubusercontent.com/assets/112839/26500295/4af14f6c-422d-11e7-8b85-b636dc78336d.png)

Looks like string gets cast to a uniq'd list of characters.

But report here: https://github.com/balhoff/dosdp-scala/issues/14

**Comment by balhoff** [comment]
New release: https://github.com/balhoff/dosdp-tools/releases/tag/v0.3.2

**Comment by dosumis** [comment]
Progress:  

- Latest design pattern docs: https://github.com/geneontology/go-ontology/tree/master/src/design_patterns/validated_patterns
- Latest TSVs: https://github.com/geneontology/go-ontology/tree/master/src/pattern_implementation_tsv

Also see #13692

**Comment by pgaudet** [comment]
@balhoff Do you know what's the status on this one ? 

Thanks, Pascale

**Comment by dosumis** [comment]
It should be possible to run dosdp-tools with tsv + pattern doc to generate a set of terms following the patterns.

TSV is here: https://gist.github.com/dosumis/4d899727896367c9b432e733e120b675.  Will need to be split into regulator, activator, inhibitor.  Separate patterns for these are:

https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/activator_activity.yaml
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/inhibitor_activity.yaml
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/regulator_activity.yaml

**Comment by pgaudet** [comment]
Hi @dosumis Thanks for your response ! This is a little cryptic to me - who might be able to do this ? 

Thanks, Pascale

**Comment by dosumis** [comment]
Just realised I already split out activator, inhibitor and regulator terms to separate TSVs already.  I have moved the files into the design_patterns folder

dosdp_tools is here: https://github.com/INCATools/dosdp-tools

It's easy to install.

This command from the design_patterns folder generates an OWL file of regulator activity terms following the pattern:

dosdp-tools --obo-prefixes --ontology=../ontology/go-edit.obo --outfile=regulator_activity.owl --template=regulator_activity.yaml generate --infile=regulator_activity.tsv

This was all meant to have been hooked up to the INCA tools table editor as a replacement for TermGenie.  I guess that still hasn't happened?

**Comment by dosumis** [comment]
Looks like the TermGenie replacement plan wasl tantalisingly close: https://github.com/geneontology/go-ontology/issues/13692

**Comment by balhoff** [comment]
I'll need to have a conversation with @cmungall and maybe @dosumis to see how I can help here.

**Comment by pgaudet** [comment]
Yes - these term all have logical definitions 
and design patterns
https://github.com/geneontology/go-ontology/blob/master/docs/patterns/activator_activity.md
https://github.com/geneontology/go-ontology/blob/master/docs/patterns/inhibitor_activity.md
https://github.com/geneontology/go-ontology/blob/master/docs/patterns/regulator_activity.md

Thanks!
