### ISSUE TITLE
regulation of vesicle docking

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13494]
I would like to see “positive…”, “negative…”, and “regulation of vesicle docking” added to GO under the parent term “vesicle docking” (GO:0048278).  The definitions would be “Any process that modulates (activates or increases/stops, prevents, or reduces) the frequency, rate or extent of vesicle docking.”  Synonyms would be “positive…”, “negative…”, and “regulation of vesicle to membrane docking”.  Example: PMID:22810233

**Comment by hdrabkin** [comment]
done
