### ISSUE TITLE
OTR GO:0030436, problem with the definition

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13501]
@pgaudet moved from annotation tracker

 AndreaAuchincloss commented 22 hours ago

Hi,
For GO:0030436, Asexual sporulation, the definition is "The formation of spores derived from the products of mitosis. Examples of this process are found in Bacterial species."

Bacteria do not undergo mitosis, although they do make spores. The paper that is cited in the definition is a fungal paper, which is fine, but not relevant to bacteria. I can't find another term that is appropriate for bacterial sporulation. Therefore for this term you might want to drop mention of mitosis from the definition so it can be used for bacteria without the annotator asking him/herself the question I'm posing here.

Thanks, Andrea
@pgaudet
Member
pgaudet commented 20 hours ago

Hi Andrea,

Does bacterial sporulation always occur after cell division ? If that's the case we could replace 'mitosis' by 'cell division'.

Thanks, Pascale
@AndreaAuchincloss
AndreaAuchincloss commented 19 hours ago
Hi Pascale,

That sounds like a good solution to me; upon thinking about it you might
also want to alter the second sentence to say "Examples of this process
are found in bacteria and fungi.". That way the term can clearly be used
in both taxonomic branches.

In Bacillus subtilis, which is the best studied bacterial sporulator,
asymmetric cell division is the beginning of the process of sporulation.
I don't know about any other bacteria, what we want here is a fairly
generic term that can be applied to all bacteria that sporulate (not all
of them do).

For Bacsu see Higgins and Dworkin, (2012) FEMS Microbiol Rev
36(1):131-148    PMID 22091839

Andrea

**Comment by pgaudet** [comment]
New definition: "The formation of spores derived from the products of an asexual cell division. Examples of this process are found in bacteria and fungi."

Does this work for you @jimhu-tamu @pfey03 ? 

Thanks, Pascale

**Comment by pfey03** [comment]
Could it say: "The formation of spores derived from the products of an asexual cell division. Examples of this process are found in bacteria, fungi and protozoa." ?

A bit more inclusive. Thanks!

**Comment by pgaudet** [comment]
@ValWood perhaps you want to weigh in on this one as well ?

**Comment by ValWood** [comment]
We have only used  ascospore formation, which is  after conjugation.

These changes sound right though...

From the history this is the old "sporulation (sensu Bacteria)" term

**Comment by jimhu-tamu** [comment]
@dsiegele reviewed the different spore forming processes at some point in the past and was involved in creating the children of this term, so she might want to comment.

I don't think of cell division as being part of the sporulation process in the formation of myxospores. @pfey03, is Dicty undergoing cell division during spore development? I thought it was like myxo. It seems to me that the fundamental differentia between sexual and asexual spores is the relationship of the spore genome to the vegetative genome, i.e. sexual sporulation involves meiosis, and asexual sporulation is everything else. 

@ValWood: not sure I understand what you mean by "after conjugation" for ascomycetes. Did you mean after meiosis and therefore not asexual? But I thought the conjugation to form diploids could be many generations prior to meiosis sporulation.

**Comment by mah11** [comment]
As far as I know, Saccharomyces and Schizosaccharomyces both do sexual sporulation only, so we don't need to use GO:0030436 and therefore have no objection to any of the changes.

> But I thought the conjugation to form diploids could be many generations prior to meiosis [and] sporulation.

This is the case for Saccharomyces (and I think for other budding yeasts). Fission yeast happens not to be the same in this respect - it usually exists and divides as a haploid, conjugates under conditions of nutrient starvation, and proceeds directly to meiosis and sporulation. Diploids can be propagated in the lab, but only with experimental manipulation that sounds a bit fiddly to me, ex-budding-yeast-lab person that I am.

But it is true that a diploid must have been formed by conjugation at some point, so spore formation does come "after" conjugation, whether it's immediately after or n generations after.

I don't know of any yeasts that undergo meiosis without directly forming spores containing the nuclei produced by meiotic divisions.

**Comment by pgaudet** [comment]
I am unsure whether the comment about 'protozoa' was appropriate. Waiting for @pfey03 to comment.

**Comment by pgaudet** [comment]
After discussion with @pfey03  this term's new definition seems OK so I will close this.

**Comment by jimhu-tamu** [comment]
What about sporulation not coupled to cell division?

**Comment by mah11** [comment]
> What about sporulation not coupled to cell division?

Well, it's not something I can help with! I can say I know of neither budding nor fission yeasts doing anything I'd describe that way.

**Comment by pgaudet** [comment]
Reverted the definition change that included fungi, based on the discussion in 
https://github.com/geneontology/go-ontology/issues/13506
