### ISSUE TITLE
NTR: sporulation resulting from sorocarp development

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#13506]
GO NEW sporulation resulting from sorocarp development
part_of
GO:0030587 sorocarp development

Def: The formation of cellular spores in response to adverse conditions such as starvation, during final culmination of the sorocarp. The spore head in a mature sorocarp consists of numerous spores.

@rjdodson I will move all Dicty sporulation annotations to this term once implemented.

Should be fairly straightforward, thanks!

**Comment by pgaudet** [comment]
@pfey03 and I agrees that  ‘sporulation resulting in formation of a cellular spore’ is suitable for the annotation of Dicty sporulation. 
I will add taxon restrictions on other similar terms.

**Comment by pgaudet** [comment]
Never in Dictyosteliida: 

GO:0034293 sexual sporulation
GO:0030436 asexual sporulation
GO:0075283 sporulation resulting in formation of a multicellular or syncytial spore

The only term allowed is therefore: 
GO:0030435 sporulation resulting in formation of a cellular spore

Pascale
