### ISSUE TITLE
OTR fix histone binding definition

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13514]
Hello, 

The definition of 'histone binding' is "Interacting selectively and non-covalently with a histone, any of a group of water-soluble proteins found in association with the DNA of plant and animal chromosomes. They are involved in the condensation and coiling of chromosomes during cell division and have also been implicated in nonspecific suppression of gene activity."
I suggest we replace "the DNA of plant and animal chromosomes" with "the DNA of eukaroytic chromosomes". 

Same for 'ubiquitin modification-dependent histone binding' (check all terms containing 'histone'. 

Does that sounds OK @ValWood @pfey03 ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't see why not.

The definition of Histone  (if even required?) is not great.

wikipedia def is much closer.
highly alkaline proteins found in eukaryotic cell nuclei that package and order the DNA into structural units called nucleosomes. They are the chief protein components of chromatin, acting as spools around which DNA winds, and playing a role in gene regulation.
