### ISSUE TITLE
ontology file on website up to date?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#13512]
Looking at:

http://geneontology.org/ontology/go-basic.obo

format-version: 1.2
data-version: releases/2017-05-10

I'm pretty sure that there have been new terms added since then.

Report for: 2017-05-15
08c00e01d11f89ba0318e779204668f9b64b6e52 krchristie ADD: 6 DEL: 0 terms: 3
de43010c7a35fb47cd27bcdfd57296ba5eca7e1c vanaukenk ADD: 0 DEL: 0 terms: 0
adeb81a6d3b8d811a27b88e42ce25d9d57655ff8 Pascale Gaudet ADD: 18 DEL: 0 terms: 30

Thanks for checking @cmungall , @kltm

**Comment by ukemi** [comment]
May be related to #13493?

**Comment by cmungall** [comment]
Need to track down why https://build.berkeleybop.org/job/build-go-ontology is failing, and why the isa completeness  not checked by travis

**Comment by cmungall** [comment]
Yes this is effectively dupe of  #13493

**Comment by tberardini** [comment]
Ok, closing this one to minimize cruft.
