### ISSUE TITLE
ntr:(negative) regulation of pupariation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13528]
Could I have:
-regulation of pupariation
Def:Any process that modulates the onset of pupariation. 
Ref:PMID:26510564
		--negative regulation of pupariation
Def:Any process that stops, prevents or reduces the rate of onset of pupariation. 
Ref:PMID:26510564

Regulates relation to GO:0035073 pupariation

Thanks

**Comment by hdrabkin** [comment]
I may as well also put in positive regulation while I'm at it

**Comment by hattrill** [comment]
Good idea, Harold (and I'll go digging around to find something to attach it to).

Thanks

**Comment by hdrabkin** [comment]
I created all of the terms; I used GOC:hjd for temporary reference for the positive reg terms until you come up with a reference. Thanks
