### ISSUE TITLE
ntr: calcium ion import across plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13525]
descendent of
 GO:0070509calcium ion import;
GO:0098739 import across plasma membrane

standard def

supporting ref PMID:15537393

**Comment by ValWood** [comment]
GO:0098703 calcium ion import across plasma membrane

exists,
missing GO:0098739 import across plasma membrane
parent

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/26500858/7b91327a-422f-11e7-9716-1dfa96e3b190.png)

- couple of hops up the class hierarchy to get to GO:0098739 import across plasma membrane

**Comment by ValWood** [comment]
OK!
