### ISSUE TITLE
Relationship of membrane depolarization to membrane

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13527]
From this [LEGO Model](http://noctua.berkeleybop.org/editor/graph/gomodel:580685bd00000071) + reasoning

we get: ![image](https://cloud.githubusercontent.com/assets/112839/26345210/13a8f3e2-3f9a-11e7-8a3c-23d85f07d84c.png)

This comes from:

![image](https://cloud.githubusercontent.com/assets/112839/26344327/2708b6c8-3f97-11e7-92a4-08f9b53f8b39.png)
(This axiomatization is correct and does useful work in the ontology). 

\+ 'sodium ion transport across membrane' part_of 'membrane deploarization' occurs in  'postsynaptic density membrane'

\+ occurs_in o part_of -> occurs_in (Which is correct)

This issue is analogous to our use of 'results in transport across' for transport across a membrane.  We will need a new relation for relating depolarization to a membrane.  Ideally this would be generic.  Perhaps 'occurs across'.  This could be used for the transport case too (where the current relation has no link to occurs in).

**Comment by pgaudet** [comment]
This is a single term. I will assume we dont need a DP for this.
