### ISSUE TITLE
NTR: cell-cell adhesion in response to extracellular stimulus

### ISSUE THREAD

**Issue by vhinard** [geneontology/go-ontology#13529]
Hi, 

would it be possible to create the following new term?

**Cell-cell adhesion in response to extracellular stimulus**

Def:  The attachment of one cell to another cell via adhesion molecules as a result of an extracellular stimulus.

child of GO:0009991 "response to extracellular stimulus"
and 
child of GO:0098609 "cell-cell adhesion"

Ref: EGFR signaling to p120-catenin through phosphorylation at Y228. PMID: 14996911

Thanks,
Valérie

**Comment by pgaudet** [comment]
Hello Valérie, 

Can you please provide a reference? 

Thanks, Pascale
