### ISSUE TITLE
general query about "factor " terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13536]
I notice that 
GO:0003716 obsolete RNA polymerase I transcription termination factor activity
is obsoleted with the comment

This term is obsolete.
This term was obsoleted because it is essentially identical to a Process term (specifically the Biological Process term which has been selected as a term to consider for reannotation), i.e. it is defined only in terms of the process it acts in and it does NOT convey any information about the molecular nature of the function or whether the function is based on binding DNA, on interacting with other proteins, or some other mechanism. To transfer all annotations without review, the BP term indicated is considered to be equivalent and thus the only appropriate destination for all annotations. To reannotate to a MF term, you will probably need to revisit the original literature or other primary data because this "MF" term was not defined in terms of mechanism of action and there are multiple possibilities in the revised MF structure. In reannotation, please also consider descendent terms of the suggested MF terms as a more specific term may be more appropriate than the MF terms indicated. Please be aware that you may wish to request a new term if the mechanism of action of this gene product is not yet represented or if you are annotating for an RNAP different than one for which there is a specific suggested term. Also note that if there is no information about how the gene product acts, it may be appropriate to annotate to the root term for molecular_function.

but we do not apply this rule consistently because we still have terms

GO:0003746
Name	translation elongation factor activity
Definition	Functions in chain elongation during polypeptide synthesis at the ribosome.

GO:0003743 translation initiation factor activity
Functions in the initiation of ribosome-mediated translation of mRNA into a polypeptide

transcription factor activity, protein binding
nteracting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules), in order to modulate transcription. A protein binding transcription factor may or may not also interact with the template nucleic acid (either DNA or RNA) as well.

transcription factor activity , RNA polymerase II core promoter sequence-specific binding involved in preinitiation complex assembly

GO:0045183 translation factor activity, non-nucleic acid binding

etc, etc

which are exactly the same, a "factor" involved in a process

**Comment by pgaudet** [comment]
Hi Val, 

I agree that the 'factor' argument is not completely convincing. 

Do you suggest we merge those MF into their respective BP ? for example 'translation initiator factor activity -> translation initiation', etc (although I am not sure we can do a Function/process merge). 

Thanks, Pascale

**Comment by ValWood** [comment]
Actually a "factor" term which is precisely positioned as an "RNA binding" term for example, might be OK. In this case it might be representing more accurately how the community refer to these functions.   Maybe it is better to leave it be for the time being and just deal with the ones which do not say anything about the molecular function at all?

**Comment by krchristie** [comment]
The lack of a specific, well-defined GO molecular function, i.e. the inability to define the MF term for "transcription factor activity" more specifically than somehow involved in the BP of "transcription" was exactly why some of the transcription factor terms were obsoleted. The idea at the time was that the MF term should include some description of HOW the BP is accomplished. It was also hoped that this would satisfy a complaint I received from a researcher at a transcription meeting that she could never remember whether she should use the MF term or the BP term for enrichment analyses since they seemed indistinguishable.

However, there was never any follow through to treat other preexisting "factor" terms similarly and there has been discussion about bringing "transcription factor activity" back...

**Comment by pgaudet** [comment]
Hi @krchristie 
I think the main issue with transcription is that the process is way overused, in such a way that it's not possible to get all transcription factors by using the BP terms. (That being said, I think the ontology is designed to allow this - just the annotations are not strict enough for this). 

What do you think ? 

Pascale

**Comment by ValWood** [comment]
close?
