### ISSUE TITLE
NTR: amyloid-beta protein complex binding

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13538]
Hello,

I am currently annotating PMID: 20395454 which shows that ADRB2 (P07550) binds Amyloid-beta protein 42 (homodimer) complex (EBI-13943368).

https://www.ncbi.nlm.nih.gov/pubmed/20395454
http://www.uniprot.org/uniprot/P07550
https://www.ebi.ac.uk/intact/complex/details/EBI-13943368

I tried to create a reciprocal annotation using the GO term 'GO:0001540 beta-amyloid binding' but P2GO won't let me, because this term 'is not suitable for use with protein complexes'.

Importantly, ADRB2 was shown to bind only the amyloid-beta protein 42 homodimer complex and not the monomeric amyloid-beta protein 42 (P05067).

So I would like to request a new term:
_GO NTR1: 'amyloid-beta protein complex binding'_

This should probably be a child of both: 'GO:0001540 beta-amyloid binding' and 'GO:0032403 protein complex binding'.

Similarly, could I please request a new term:

_GO NTR2: 'cellular response to amyloid-beta protein complex'_

This would be a child of 'GO:1904646 cellular response to beta-amyloid'

Please use the DbxRef: GOC:aruk and GOC:bc.

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
#13418

**Comment by BarbaraCzub** [comment]
Similarly, could I please request a new term:

GO NTR: "cellular response to amyloid-beta protein 42 homodimer complex"

This would be a child of "GO:1904646 cellular response to beta-amyloid"

Please use the DbxRef: ARUK-UCL and GOC:bc.

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Hello,

Could I please request two more general terms instead: 

'amyloid-beta protein complex binding'?

As well as: 'cellular response to amyloid-beta protein complex'?

GOC:aruk and GOC:bc

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Hello,
Following our discussions I would like to renew my request for these new terms:
GO NTR1: 'amyloid-beta protein complex binding' (is_a 'protein-containing complex binding' GO:0044877)
GO NTR2: 'cellular response to amyloid-beta protein complex' (is_a 'cellular response to biotic stimulus' GO:0071216)
Thanks,
Barbara

**Comment by bmeldal** [comment]
Also see https://github.com/geneontology/go-ontology/issues/16833

**Comment by BarbaraCzub** [comment]
Complexes Working Group advise from 17 Jan call: do not generate binding terms for specific complexes. Therefore, I will:

- [ ] _not_ add the new term 'amyloid-beta protein complex binding';

- [ ] add a new term 'cellular response to protein-containing complex' (and then specify the complex in the annotation extension) instead of adding the initially suggested term 'cellular response to amyloid-beta protein complex'. 

cc @RLovering @bmeldal

**Comment by ValWood** [comment]
Sorry to pitch in late, I was ill yesterday.

'cellular response to amyloid-beta protein complex'  sounds a very strange term to me. I thought we were thinking about removing these terms longer term, not adding new ones. 

My question would be what is the actual biological process, is it a stress response? signalling? Something else?

**Comment by ValWood** [comment]
OK!
