### ISSUE TITLE
NTRs: child terms of GO:1903440 amylin receptor complex

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13533]
Hello, 

I am currently annotating PMID:22500019, which investigates signalling pathways that 'amylin receptor complex 3 (AMY3)' is involved in. 'Amylin receptor complex 1 (AMY1)' and 'amylin receptor complex 2 (AMY2)' are studied as controls.

I would like to request new GO terms for these three cellular components:
GO NTR1: Amylin receptor complex 1 (AMY1);
GO NTR2: Amylin receptor complex 2 (AMY2);
GO NTR3: Amylin receptor complex 3 (AMY3).
All three will be child terms of GO:1903440 amylin receptor complex.

Please use the DbxRef: ARUK-UCL and GOC:bc.

The Complex Portal entries provide further details:
AMY1: https://www.ebi.ac.uk/intact/complex/details/EBI-9008682
AMY2: https://www.ebi.ac.uk/intact/complex/details/EBI-9685417
AMY3: https://www.ebi.ac.uk/intact/complex/details/EBI-9685439

Thank you,
Barbara

**Comment by BarbaraCzub** [comment]
Similarly, since the paper shows that the different amylin receptor complexes are regulated by different ligands (e.g. supplementary figure 2), could I also please request the following
child terms of GO:0097647 amylin receptor signaling pathway:

GO NTR4: amylin receptor 1 (AMY1) signaling pathway;
GO NTR5: amylin receptor 2 (AMY2) signaling pathway;
GO NTR6: amylin receptor 3 (AMY3) signaling pathway.

Please use the DbxRef: ARUK-UCL and GOC:bc.

Thanks.

**Comment by bmeldal** [comment]
Barbara, we have all of these in the CP already. Unless you can identify specific functions that differ between the 3 forms of the amylin complex we shouldn't create new GO terms for these compositional variants. At least that was the last decision we made.

**Comment by BarbaraCzub** [comment]
Thanks @bmeldal, PMID:22500019 shows that the 3 complexes (AMY1, AMY2, and AMY3) are bound by different ligands (main figures re AMY3 and Supplementary Figure 2 re AMY1 and AMY2). The downstream signalling events are investigated in detail only for AMY3, as this is the receptor, which is shown in this paper to be regulated by amyloid-beta oligomers (AMY1 and AMY2 are not affected by amyloid-beta oligomers according to this paper). 

Generally, all three receptors have been shown to regulate cytosolic cAMP levels, but due to activation by different ligands (unlike for AMY3, no other effects of AMY1 or AMY2 are studied in this paper). The definition of 'signal transduction' states that "Signal transduction begins with reception of a signal (e.g. a ligand binding to a receptor...)..." (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0097647#term=ancchart), which supports the argument to create more specific signalling terms for these three complexes.

With regard to the CC terms, it would be worth having the more specific complex terms to select in order to be able to annotate each specific RAMP protein to its corresponding AMY receptor.

**Comment by vanaukenk** [comment]
Hi @BarbaraCzub and @bmeldal 

From the data in Fig. 1 and Supplementary Fig. 2, and some other references (see PMID: 26895962) it looks like the AMY1, 2, and 3 receptor complexes are pharmacologically distinct, so it would be okay to create the new complex and signaling pathway terms in GO.

One question I had, though, was about the parentage of the complex terms.

Right now, GO:1903440 amylin receptor complex has an is_a parent to GO:0038037 G-protein coupled receptor dimeric complex.  The definition of GO:0038037 G-protein coupled receptor dimeric complex is:

A protein complex that contains two G-protein coupled receptors.

But do the amylin receptor complexes contain two G-protein coupled receptors, are just one G-protein coupled recepter and a single-pass transmembrane RAMP?

If just one GPCR and a RAMP, then we should move the parentage to GO:0097648 A protein complex that contains G-protein coupled receptors. 

Do you agree?

Thx.

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk, I think you are right and the parentage should be moved to GO:0097648 G-protein coupled receptor complex. Perhaps previously it had been placed under GO:0038037 G-protein coupled receptor dimeric complex by mistake, because it is a dimer. But within this dimer only the calcitonin receptor (P30988) appears to have the GPCR function, and RAMP does not. @bmeldal do you agree?

**Comment by bmeldal** [comment]
Yes, you are right, only the calcitronin is a GPCR. I remember trying to sort out the parentage when I curated the original entries but I must have missed the caveat of "two GPCRs" or it was added later.

As a side note, this is why defining complexes by stoichiometry is not a good idea. They are dimers, so if the stoichiometry is a dimer who would expect this to be restricted to catalytic units only?

**Comment by vanaukenk** [comment]
Okay, thanks @BarbaraCzub and @bmeldal 
Yes, @bmeldal I see your point about defining complexes by stoichiometry.  
So, for now, I propose to just move the amylin receptor terms to be direct children of G-protein coupled receptor complex.
Then we could possibly address the stoichiometry-based term names as part of a larger discussion?

**Comment by bmeldal** [comment]
agree :)

And I leave the 'larger discussion' to the GO Editors :)

**Comment by vanaukenk** [comment]
@BarbaraCzub 
Here are proposed draft definitions for the complex and signaling terms for AMY1 (the others would just be modified to include the specific RAMP).  Please let me know if you want any changes.  Also, if you have any additional references that describe the formation or action of the complexes, let me know and I'll add them to the entries.

GO NTR1: Amylin receptor complex 1 (AMY1)
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 1.

GO NTR4: amylin receptor 1 (AMY1) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin combining with an amylin receptor 1 on the surface of the target cell. 

For the signaling pathway terms, I noticed that the parent term, GO:0097647 amylin receptor signaling pathway is a child of GO:0038042 dimeric G-protein coupled receptor signaling pathway, but as noted for the complex terms, this parentage no longer seems correct, so I will move GO:0097647  to instead be a direct child of GO:0007186 G-protein coupled receptor signaling pathway.

**Comment by bmeldal** [comment]
The def for the Amy1 receptor complex doesn't really differ from the parent (which has the automatic def as I created it from the activity term). Shouldn't the functional difference be highlighted in the def so that it's clear why we create the child terms?

When you made the terms, please post the stanza here so I can update the ACs on the CP entries.

Thanks, @vanaukenk !

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 

I agree with @bmeldal that perhaps the definitions require some further details to differentiate the three complexes from one another and not to give the impression that amylin polypeptide is the only ligand that binds to these complexes. Atm I am not aware of other relevant references, but based on PMID:22500019 I propose the following revisions (_in italics_):

GO NTR1: Amylin receptor complex 1 (AMY1)
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 1. _AMY1 also serves as a receptor for the calcitonin related peptide (CGRP) and adrenomedullin (AM/ADM)._

GO NTR2: Amylin receptor complex 2 (AMY2)
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 2. _AMY2 also serves as a receptor for adrenomedullin (AM/ADM)._

GO NTR3: Amylin receptor complex 3 (AMY3).
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 3. _AMY3 also serves as a receptor for the amyloid-beta complex. Ligand binding to AMY3 results in increased cytosolic calcium ion levels and in activation on multiple intracellular signalling pathways._

GO NTR4: amylin receptor 1 (AMY1) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin, _or another ligand_, combining with an amylin receptor 1, _a G protein-coupled receptor complex_, on the surface of the target cell. _Other ligands that have been shown to initiate the AMY1 signaling pathway include the calcitonin related peptide (CGRP) and adrenomedullin (AM/ADM)._

GO NTR5: amylin receptor 2 (AMY2) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin, _or another ligand_, combining with an amylin receptor 2, _a G protein-coupled receptor complex_, on the surface of the target cell. _The AMY2 signaling pathway can also be initiated by adrenomedullin (AM/ADM)._

GO NTR6: amylin receptor 3 (AMY3) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin, _or another ligand_, combining with an amylin receptor 3, _a G protein-coupled receptor complex_, on the surface of the target cell. _The AMY3 signaling pathway can also be initiated by the amyloid-beta complex. AMY3 signaling results in increased import of calcium ions into the cytosol across plasma membrane, increased phosphorylation of ERK1/2, Act, and a PKA regulatory subunit II, as well as increased expression of cFos._

Re: NTR4-6: I do not know whether we need to specify the other ligands, but I think we should make sure we're not suggesting that amylin is the only ligand that activates these signalling pathways (then indeed it would not be clear at all why the child terms have been created). I am also not sure in how much details the downstream effects of ligand binding to AMY receptors need to be indicated. Anyhow, in the future if/when more specific roles of the individual AMY complexes are revealed, the definitions can be revised to include further details.

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Thank you for your comments on this @bmeldal 

@vanaukenk I am going to re-assign this to myself and make these edits, when the Travis checks issue has been resolved, unless you have any further comments wrt other ligands?

> Re: NTR4-6: I do not know whether we need to specify the other ligands, but I think we should make sure we're not suggesting that amylin is the only ligand that activates these signalling pathways (then indeed it would not be clear at all why the child terms have been created). I am also not sure in how much details the downstream effects of ligand binding to AMY receptors need to be indicated. Anyhow, in the future if/when more specific roles of the individual AMY complexes are revealed, the definitions can be revised to include further details.

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
To do:

### Re: 'GO:1903440 amylin receptor complex'

- [ ] Correct the parentage of 'GO:1903440 amylin receptor complex'. This should be a child term of: 'GO:0097648 G-protein coupled receptor complex', and _not_ 'GO:0038037 G-protein coupled receptor dimeric complex' (see a 26 May 2017 comment by @vanaukenk above);

- Add new child terms:

- [ ] GO NTR1: Amylin receptor complex 1 (AMY1)
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 1. AMY1 also serves as a receptor for the calcitonin related peptide (CGRP) and adrenomedullin (AM/ADM). [DbxRefs.: PMID:22500019, GOC:aruk, GOC:bc].

- [ ] GO NTR2: Amylin receptor complex 2 (AMY2)
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 2. AMY2 also serves as a receptor for adrenomedullin (AM/ADM). [DbxRefs.: PMID:22500019, GOC:aruk, GOC:bc].

- [ ] GO NTR3: Amylin receptor complex 3 (AMY3).
Definition: A G protein-coupled receptor complex that serves as a receptor for amylin polypeptide (Amy) and consists of a calcitonin receptor (CTR/CALCR) and a receptor activity-modifying protein (RAMP) 3. AMY3 also serves as a receptor for the amyloid-beta complex. Ligand binding to AMY3 results in increased cytosolic calcium ion levels and in activation on multiple intracellular signalling pathways. [DbxRefs.: PMID:22500019, GOC:aruk, GOC:bc].


### Re: 'GO:0097647 amylin receptor signaling pathway'

- Add new child terms:

- [ ] GO NTR4: amylin receptor 1 (AMY1) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin, or another ligand, combining with an amylin receptor 1, a G protein-coupled receptor complex, on the surface of the target cell. Other ligands that have been shown to initiate the AMY1 signaling pathway include the calcitonin related peptide (CGRP) and adrenomedullin (AM/ADM). [DbxRefs.: PMID:22500019, GOC:aruk, GOC:bc].

- [ ] GO NTR5: amylin receptor 2 (AMY2) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin, or another ligand, combining with an amylin receptor 2, a G protein-coupled receptor complex, on the surface of the target cell. The AMY2 signaling pathway can also be initiated by adrenomedullin (AM/ADM). [DbxRefs.: PMID:22500019, GOC:aruk, GOC:bc].

- [ ] GO NTR6: amylin receptor 3 (AMY3) signaling pathway
Definition: A series of molecular signals initiated by an extracellular amylin, or another ligand, combining with an amylin receptor 3, a G protein-coupled receptor complex, on the surface of the target cell. The AMY3 signaling pathway can also be initiated by the amyloid-beta complex. AMY3 signaling results in increased import of calcium ions into the cytosol across plasma membrane, increased phosphorylation of ERK1/2, Act, and a PKA regulatory subunit II, as well as increased expression of cFos. [DbxRefs.: PMID:22500019, GOC:aruk, GOC:bc].


### Other
@vanaukenk previously suggested (see a 26 May 2017 comment by @vanaukenk above) that 'GO:0097647 amylin receptor signaling pathway' should be a child term of: 'GO:0007186 G-protein coupled receptor signaling pathway', and _not_ 'GO:0038042 dimeric G-protein coupled receptor signaling pathway'. This incorrect parentage was removed on 4 June 2018 (QuickGO screenshot below), and 'GO:0097647 amylin receptor signaling pathway' is now an is_a child term of: 'GO:0097646 calcitonin family receptor signaling pathway'. This is correct, so I will not be making any changes here.
![screen shot 2018-06-19 at 15 12 46](https://user-images.githubusercontent.com/16541096/41602667-47d2ff82-73d3-11e8-9409-23fc15723f8e.png)


cc
@vanaukenk 
@bmeldal 
@RLovering 
@paolaroncaglia
