### ISSUE TITLE
ntr: lipid particle formation and localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13534]
ntr: lipid particle formation
child of lipid storage
child of lipid particle organization

(note lipid droplet appears to be much the prefered term)

standard def

ref PMID:28011631
Lipid droplet dynamics during Schizosaccharomyces pombe sporulation and their role in spore survival
Hui-Ju Yang1, Hiroko Osakada2, Tomoko Kojidani2,3, Tokuko Haraguchi1,2 and Yasushi Hiraoka1,2,

**Comment by cerivs** [comment]
Lipid droplet is the preferred term in zebrafish too.  PMID:27655916 Endoplasmic reticulum lipid flux influences enterocyte nuclear morphology and lipid-dependent transcriptional responses

**Comment by ValWood** [comment]
I googled and its
lipid droplet 406,000 
lipid particle 63,100  (mainly GO)
wikipedia is "lipid droplet"
I have never seen lipid particle used....

**Comment by ValWood** [comment]
also 


"lipid particle/droplet  localization to (ascospore type prospore GO:0042764)"
lipid particle/droplet  localization to  (prospore membrane  GO:0005628)

**Comment by mah11** [comment]
For formation, the precedent-following wording would be "lipid particle/droplet assembly". I would not try to mash assembly and localization together into a single term.

**Comment by ValWood** [comment]
> I would not try to mash assembly and localization together into a single term.

I wasn't. I just made things confusing by  tagging my localization term onto the formation ticket instead of opening a separate ticket....

**Comment by mah11** [comment]
Note: for the linked phenotype ticket, we could also use:

GO:new
lipid droplet localization to prospore membrane leading edge
(synonyms lipid particle etc.; forespore membrane etc.)
could perhaps use has_target_end_location GO:0070056 ! prospore membrane leading edge

**Comment by ValWood** [comment]
Hi Pascale,

Do  you need any more information to add
ntr: lipid particle formation
am waiting to complete one of our community curation sessions, 
seems quick.

**Comment by pgaudet** [comment]
Sorry I got distracted by the GOC meeting. 

Slould I rename all other terms containing 'lipid particle' to 'lipid droplet'? 

Component 	GO:0005811 	lipid particle 	
Component 	GO:0005633 	ascus lipid particle 	
Component 	GO:0044186 	host cell lipid particle 	
Process 	GO:1905691 	lipid particle disassembly 	
Process 	GO:0034389 	lipid particle organization 	
Process 	GO:1990044 	protein localization to lipid particle 	
Process 	GO:0031887 	lipid particle transport along microtubule 


as well as: 
Component 	GO:1990777 	lipoprotein particle
Component 	GO:0034358 	plasma lipoprotein particle
Function 	GO:0071813 	lipoprotein particle binding
Component 	GO:0034364 	high-density lipoprotein particle
Process 	GO:0034377 	plasma lipoprotein particle assembly
Function 	GO:0030228 	lipoprotein particle receptor activity
Process 	GO:0034369 	plasma lipoprotein particle remodeling
Process 	GO:0034380 	high-density lipoprotein particle assembly
Component 	GO:0034365 	discoidal high-density lipoprotein particle
Process 	GO:0034374 	low-density lipoprotein particle remodeling
Process 	GO:0034375 	high-density lipoprotein particle remodeling
Component 	GO:0034385 	triglyceride-rich plasma lipoprotein particle
Process 	GO:0034379 	very-low-density lipoprotein particle assembly
Process 	GO:0034372 	very-low-density lipoprotein particle remodeling
Process 	GO:0034370 	triglyceride-rich lipoprotein particle remodeling
Process 	GO:0034373 	intermediate-density lipoprotein particle remodeling
Process 	GO:0090107 	regulation of high-density lipoprotein particle assembly
Process 	GO:0010901 	regulation of very-low-density lipoprotein particle remodeling
Process 	GO:0090108 	positive regulation of high-density lipoprotein particle assembly
Process 	GO:0010902 	positive regulation of very-low-density lipoprotein particle remodeling
Process 	GO:0010903 	negative regulation of very-low-density lipoprotein particle remodeling
Process 	GO:0034376 	conversion of discoidal high-density lipoprotein particle to spherical high-density lipoprotein particle 

? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think the lipoprotein thingy is  something different. I think this is always referred to as "lipoprotein particle" not droplet. Although I'm not actually sure what it is...yeast don't have it, but we do have lipid droplets.

The only child of lipoprotoen particle is:
GO:0034358
Name	plasma lipoprotein particle

Lipid droplets are intracellular.

anyway no huge hurry for this if it is more complicated than expected. I put my curation session through with the parent annotations for now.

**Comment by RLovering** [comment]
Hi All
please do not rename these terms. BTW you should know what low-density lipoprotein particle is as this is what people are talking about when they measure your LDL levels and decide whether to put you on statins or not ;)

Pascale it would have been good to have added someone from BHF team to this as many of the above terms are created by us. I had stopped looking at this because I thought you were just discussing lipid droplets.

Thanks

Ruth

@NancyCampbell

**Comment by pgaudet** [comment]
Hi @RLovering @NancyCampbell

I got a little carried away here (well, I just wanted to be sure we looked at every term possibly impacted by this). 

Based on Val's comment I propose to rename the following terms: 
Component GO:0005811 lipid particle
Component GO:0005633 ascus lipid particle
Component GO:0044186 host cell lipid particle
Process GO:1905691 lipid particle disassembly
Process GO:0034389 lipid particle organization
Process GO:1990044 protein localization to lipid particle
Process GO:0031887 lipid particle transport along microtubule

I agree that the lipoprotein is something else- it just came up in my search for 'lipid particle'. 

Dos that work for you ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Ruth don't worry  its clear they are different things. I would have CC'd you  for sure if it moved  properly into lipid particle territory ;)

**Comment by ValWood** [comment]
@pgaudet  sounds good to me.

**Comment by pgaudet** [comment]
Hi Val, 

Can you just confirm which localization terms you need ? I created
- lipid droplet localization to prospore membrane leading edge
Do you also want 
-lipid particle/droplet localization to (ascospore type prospore GO:0042764)
- lipid particle/droplet localization to (prospore membrane GO:0005628)

Thanks, Pascale

**Comment by ValWood** [comment]
lipid droplet localization to prospore membrane leading edge
will do...

**Comment by pgaudet** [comment]
ok !

**Comment by RLovering** [comment]
thanks for unworrying me ;)
