### ISSUE TITLE
ntr glycerophosphodiester transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13549]
descendant of 
glycerophosphodiester transport (or make this a transmembrane term, not sure there is another way?)

(need a term with a 'transmembrane' parentage)

**Comment by pgaudet** [comment]
Hi Val, 

Looking at the annotations to this term, all proteins seem to be 'glycerophosphodiester import across the plasma membrane'. Would this be also OK for the bacterial annotations @jimhu-tamu ? 

Thanks, Pascale
