### ISSUE TITLE
learning or memory  GO:0007611

### ISSUE THREAD

**Issue by icampia** [geneontology/go-ontology#13545]
Hello, 
I noticed the change log “learning or memory” GO:0007611 http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007611#term=history&info=2 and also https://github.com/geneontology/go-ontology/issues/335
Could you please give me more information about the change from the previous term “ learning _and/or_ memory” to the current “learning _or_ memory”? Also considering the definition ” The acquisition and processing of information _and/or_ the storage and retrieval of this information over time.”  
Thank you in advance!
Ivana

**Comment by ukemi** [comment]
Hi Ivana,

I'm not sure what you are asking, but I suspect that this term name was changed as part of a clean-up to eliminate the and/or terms in the ontology. The term is used for any process that is either a type of learning or a type of memory. Sometimes experiments do not cleanly discriminate between these two and they are closely related. If a more precise process is identified, then a child term should be used.

-D

**Comment by ukemi** [comment]
Is this info sufficient that I can close this ticket?

**Comment by icampia** [comment]
Hi David, yes it is. Thank you! Ivana
Il 02/giu/2017 18:03 "David Hill" <notifications@github.com> ha scritto:
