### ISSUE TITLE
MP mRNA 3'-UTR AU-rich region binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13548]
add parent
sequence-specific mRNA binding?

**Comment by ukemi** [comment]
Is it really sequence-specific just because it it AU-rich?

**Comment by ValWood** [comment]
Ah I was thinking that this referred to the "AAUAAA" consensus element in the 3'UTR polyadenylation site...
I think this is a larger less conserved AU rich region, but it has a definite consensus.
 
I think that might be what it means but it isn't clear....

**Comment by ukemi** [comment]
Hmmm. I think the consensus element is part of the AU rich region, but I think it encompasses more. See PMID:3488815. It is your term, so if you still think this region means sequence-specific, I will add it.

**Comment by ValWood** [comment]
I'll check back and get back to you soon....might not be today ;)

**Comment by mah11** [comment]
To me "AU-rich" doesn't indicate sequence specificity; it's just composition.

**Comment by ValWood** [comment]
will close...
