### ISSUE TITLE
question about GO:0016149 - translation release factor activity, codon specific

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13555]
GO:0016149 - translation release factor activity, codon specific

def
Definition: "A translation release factor that is specific for one or more particular termination codons; acts at the ribosomal A-site and require polypeptidyl-tRNA at the P-site." 

I don't understand this term. We are picking up a mapping to it. I only used the parent
GO:0016149 - translation release factor activity

GO:0003747 - translation release factor activity

but if a translation factor can act at ore than one codon, it isn't codon specific. I.e. I'm struggling to see the difference between 
GO:0016149 and GO:0003747 

do some  release factors only act at specific stop codons.
I can't figure out if the mapping it incorrect until I know what it means.

**Comment by hdrabkin** [comment]
Hi Val; yes, there are codon specific release factors
See 
RNA. 2010 Aug; 16(8): 1623–1633. doi:  10.1261/rna.2117010 PMCID: PMC2905760
The codon specificity of eubacterial release factors is determined by the sequence and size of the recognition loop
David J. Young, Christina D. Edgar, Elizabeth S. Poole, and Warren P. Tate

The two codon-specific eubacterial release factors (RF1: UAA/UAG and RF2: UAA/UGA) ....

**Comment by ValWood** [comment]
OK,
so far as I can figure out pombe has  2 class 1 
dom34/Poleto and erf1
and one class II, confusingly called erf3

So  it seems that all of our cytoplasmic translation initiation factors are codon specific. Does that sound right? Is that true for all  or do some have non-specific?

You can close this ;)

**Comment by hdrabkin** [comment]
A quick wiki check
Prokaryotic translation termination is mediated by three prokaryotic release factors: RF1, RF2, and RF3.[3]
    RF1 recognizes the termination codons UAA and UAG
    RF2 recognizes UAA and UGA
    RF3 is a GTP-binding protein that leads to the dissociation of RF1/RF2 after peptide release

Likewise, eukaryotic translation termination involves two eukaryotic release factors: eRF1 and eRF3.[3]

    eRF1 recognizes all three termination codons  <<<<<<<<<<
      eRF3 is a ribosome-dependent GTPase that helps eRF1 release the completed polypeptide

But:
Eukaryotic translation termination factor 1 (eRF1), also known asTB3-1, is a protein that in humans is encoded by the ETF1 gene.[3][4][5]
**In eukaryotes, this is the only release factor (eRF) which recognizes all three stop codons. ***The overall process of termination is similar in prokaryotes, but in the latter 3 separate release factors exist, RF1, RF2 and RF3.[6]

**Comment by ValWood** [comment]
OK the human ETF1 has an InterPro mapping to 
translation release factor activity, codon specific

so this should be removed, do you agree ? It was the mappings that I wanted to check....

**Comment by hdrabkin** [comment]
Yes I would agree. Do you know who to contact?

**Comment by ValWood** [comment]
done
https://github.com/geneontology/go-annotation/issues/1561

**Comment by asangrador** [comment]
Thanks for this information. I have reviewed the entries we had in InterPro with the term 'GO:0016149 - translation release factor activity, codon specific'.  I have  substituted this term with the parent in two entries that were matching eukaryotic RFs.
Amaia
