### ISSUE TITLE
MP GO:0045324 late endosome to vacuole transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13556]
Hi,

Can this have the parentage 
"vesicle-mediated transport"
its ommission means that a large number of gene products remain un-slimmed by a number of defined GO slim sets

thanks
val

**Comment by ValWood** [comment]
probably the def should specify via vesicles, unless anyone knows of another way...

**Comment by ukemi** [comment]
Hi Val,

I'm tweaking the logical defs of this and the endosome to lysosome transport terms to add the axioms 'mediated_by some vesicle'. This makes them necessary and sufficient to classify them as vesicle-mediated transport. I also tweaked the genus of this term to make it an intracellular transport. This make is also classify as an endosomal transport and a vacuolar transport. These also seem reasonable to me.

-D

**Comment by ValWood** [comment]
thanks!
