### ISSUE TITLE
Problem with the name of GO:0033942; F:4-alpha-D-(1->4)-alpha-D-glucano}trehalose trehalohydrolase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#13558]
Hi,

there is an issue with the name of GO:0033942; F:4-alpha-D-(1->4)-alpha-D-glucano}trehalose trehalohydrolase activity

The presence of a mismatched curly bracket '}' creates a fatal error in UniProt. Would it be possible to rename it as:

4-alpha-D-((1->4)-alpha-D-glucano)trehalose trehalohydrolase

Thanks

Sylvain

**Comment by hdrabkin** [comment]
4-alpha-D-(1->4)-alpha-D-glucanotrehalose trehalohydrolase
