### ISSUE TITLE
revisiting Taxon constraint for X, Y chromosome in birds #12108

### ISSUE THREAD

**Issue by michaelerice** [geneontology/go-ontology#13564]
We have spent some time thinking about this and it appears that it would be appropriate to use the term GO:0007549 dosage compensation for birds and reptiles,  and after some discussion it seems that the easiest approach would be to change the definition from "Compensating for the two-fold variation in X:autosome chromosome ratios between sexes by a global activation or inactivation of all, or most of, genes on one or both of the X chromosomes." to something like "Compensating for the two-fold variation in the unpaired sex chromosome:autosome chromosome ratios between sexes by a global or partial activation or inactivation of all, or most of, genes on one or both of the sex chromosomes." Then the child terms could reflect the specific mechanisms occurring with the X or Z chromosomes.  

the following are a few of the most recent publications

PMID: 26616198​
Sex chromosomes evolved independently in many animal groups and are defined by different genes that acquired either a male-determining or a female-determining function. In different lineages different mechanisms compensate, to a greater or lesser extent, for the 2:1 gene dosage difference created between the sexes4. These mechanisms are best known in mammals, in which one entire X chromosome is epigenetically silenced in the somatic cells of females. However, in other vertebrates, whole-X chromosome inactivation is the exception; in monotreme mammals, birds, reptiles and fish, dosage compensation seems to be gene-specific and partial at best.

dosage compensation in birds does occur86, but it is partial and gene-by-gene91​

PMID: 28469017 
Dosage compensation is a common phenomenon taxonomically, but varies in its extent; it is almost complete in mammals, but is partial in birds and some snakes [12].

PMID: 27044516​
expression data from the chicken (Gallus gallus) shows that ohnologs, duplicated genes known to be dosage-sensitive, are preferentially dosage-compensated on the chicken Z chromosome

Thank you

**Comment by ukemi** [comment]
How about:

Compensating for the variation in the unpaired sex chromosome:autosome chromosome ratios between sexes by activation or inactivation of genes on one or both of the sex chromosomes.

?

-D

**Comment by michaelerice** [comment]
?

David,


that definition looks good. Do you need me to do anything else? Thanks


Mike



________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________
