### ISSUE TITLE
What is cellular?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#13584]
Hi

Please could agree what is cellular component and what is cellular. Extracellular space (ie plasma) is_a cellular component and yet viruses are not cellular. This is just one of the inconsistencies (apparently).

Thanks

Ruth

@cmungall 
@pgaudet 
@rebeccafoulger (haha)
@dosumis

**Comment by cmungall** [comment]
Not sure what the action is here. Adjectives are inherently ambiguous and context dependent so we can't standardize these.

However, all of us agree that "cellular_component" is a confusing label. But all proposals to change this have been doomed because changing root labels can possibly break tools. Would we also change the obo namespace (which is currently always the same as the root label)?

If someone wants to propose this again I'm not against it

**Comment by ukemi** [comment]
Since there is no tangible action here, I suggest that we close this item. The cellular process discussion is already open in another issue.

**Comment by ValWood** [comment]
even dictionaries have problems define "cell" without an exception clause.

cell definition. The basic unit of all living things except viruses.

so why not just say it as it is

“cellular or virion component”

Even if a rename breaks tools it shouldn't be such a difficult fix (if it is maybe the tools are well rid)

**Comment by RLovering** [comment]
Val's comment sounds like a good option - what does Pascale think of this?

**Comment by pgaudet** [comment]
@ValWood 
> "even dictionaries have problems define "cell" without an exception clause."
did you mean with or without an exception clause?

**Comment by pgaudet** [comment]
Hi Ruth, 

The definition of 'cellular component' is consistent with this ("The part of a cell, extracellular environment or virus in which a gene product is located. A gene product may be located in one or more parts of a cell and its location may be as specific as a particular macromolecular complex, that is, a stable, persistent association of macromolecules that function together." 

We just (just ;)) need to use the same definition when thinking about cellular processes; what do you think ? 

Pascale

**Comment by ukemi** [comment]
I think any action here is related to the cellular process ticket. So I'm closing this one.
