### ISSUE TITLE
nuclear transport defined with reference to host cell!

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13583]
![image](https://cloud.githubusercontent.com/assets/112839/26735482/f80338d4-4776-11e7-8603-5e076cebc69d.png)

This is causing problems:

![image](https://cloud.githubusercontent.com/assets/112839/26735426/c8750dc2-4776-11e7-86d0-7d5bedfcf672.png)

![image](https://cloud.githubusercontent.com/assets/112839/26735466/e80165e6-4776-11e7-80df-4b2eaa3fac9e.png)

**Comment by pgaudet** [comment]
Hello, 

The same problem is also in 'nucleocytoplasmic transport'. Looks like I did this, sorry ! 

Pascale

**Comment by pgaudet** [comment]
and many viral transport are missing 'host parts', such as 'exit of virus from host cell nucleus through nuclear pore' - and probably others. 
Pascale

**Comment by dosumis** [comment]
> The same problem is also in 'nucleocytoplasmic transport'. Looks like I did this, sorry !

Should show up in nightly inference report.

**Comment by dosumis** [comment]
See Report for: 2017-05-18

**Comment by pgaudet** [comment]
Pull request: https://github.com/geneontology/go-ontology/pull/13587

**Comment by pgaudet** [comment]
Fixed https://github.com/geneontology/go-ontology/pull/13587
