### ISSUE TITLE
hypusinylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13582]
This is similar to
https://github.com/geneontology/go-ontology/issues/13565

Since 
Cytosolic eukaryotic translation initiation factor 5A (eIF5A) undergoes a unique two-step post-translational modification at Lys 50 via deoxyhypusine (Dhp) to hypusine (Hyp). In the first step deoxyhypusine synthase transfers the aminobutyl group of spermidine to the epsilon-amino group of lysine 50, using NAD+ as a cofactor. Hydroxylation of the C2 of the newly added moiety in the second step is catalyzed by deoxyhypusine hydroxylase/monooxygenase with molecular oxygen as the source. The molecular function of eIF5A is unknown, but the protein is required for viability in eukaryotic cells and its normal function requires hypusinylation. eIF5A is the only protein known to undergo hypusinylation (Park 2006).

from
http://www.reactome.org/content/detail/204626

(will slim to  cytoplasmic translation)

Also add  hypusinylation as exact synonym of
http://amigo.geneontology.org/amigo/term/GO:0008612

**Comment by hdrabkin** [comment]
Sorry; not enough info
Do you want GO:0008612 to have an  is_a to regulation of cytoplasmic translation?

**Comment by ValWood** [comment]
yes please.

**Comment by hdrabkin** [comment]
done
