### ISSUE TITLE
Consider pre-composing postsynaptic density of dendrite

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13595]
See the inferred types here:

![image](https://cloud.githubusercontent.com/assets/50745/26765604/02f782a4-4934-11e7-847d-5b370322900b.png)

in http://noctua.berkeleybop.org/editor/graph/gomodel:593423e000000473

When GPAD is exported we get additional inferences to 'neuron part'. This is correct. However, it may be cleaner if there is a precomposed term (this would already be classified as 'neuron part' in the release version of the ontology, so we would not get the additional 'helpful' inferences).

From discussion with @RLovering at Noctua workshop

**Comment by RLovering** [comment]
http://noctua.berkeleybop.org/editor/graph/gomodel:593423e000000473?barista_token=ywkfhlfkobzi1yzwoqaw#

**Comment by ukemi** [comment]
In the future, I hope that this becomes a part of the normal workflow. That is, models will direct the addition of instantiated terms in the ontology and will initially serve as a template for new terms and eventual new term templates. This is an efficient mechanism for ontology development because evidence and provenance for the existence of a term is automatically captured from the original annotations.

**Comment by pgaudet** [comment]
Hello, 

Thank you for giving me the opportunity to learn about neurons ! This is not an area I know much about so I have a few naive questions. 
My understanding is that the dendrite is the part of the neuron that receives the signal; so the post-synaptic density must anyway be located at the dendrite; is this right ? 
In this case I could just create the missing parent ('part of' some dendrite). Does this sound right ? 

Thanks, Pascale

**Comment by dosumis** [comment]
> My understanding is that the dendrite is the part of the neuron that receives the signal; so the post-synaptic density must anyway be located at the dendrite; is this right ?

Except when it's not.  Axo-axonic and Axo-somatic synapses also exist. Axo-axonic are common in arthropods, but are also found in vertebrates.  Not sure whether these have clear PSDs though.

**Comment by pgaudet** [comment]
Hi @dosumis 

If we are not sure whether the Axo-axonic and Axo-somatic synapses have PSD, I propose to rename the existing term 'postsynaptic density of dendrite' and we'll wait to need to other terms before creating them. 

OK? 

Thanks, Pascale

**Comment by dosumis** [comment]
Sorry - should have kept track of this fix.  If the aim is to avoid the annoying neuron-part inference, then we just need a part relationship to neuron - then we don't have to worry about whether PSDs exist in axo-axonic and axo-somatic synapses, or what do in cases where neuron projection identify is unclear.  

I'll change the name back, adding neuronal postsynaptic density as an exact synonym and adding subClassOf part_of some neuron.

Note - we need to distinguish this from 'muscle cell postsynaptic density', but this term itself is a bit dubious. In almost all cases the term PSD is used to refer to the structure in neurons; IIRC the use for muscle is in a few Drosophila papers and is not really standard.  For this reason, keeping the name post synaptic density for the 'neuronal' variety makes sense I think. We might even want to change 'muscle cell postsynaptic density' into 'muscle cell postsynaptic specialization.
