### ISSUE TITLE
NTR: 4 terms for specific retinoid 3,4-desaturase activity

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#13608]
Hi,

Could I please ask for 4 new terms to be created based on PMID: 27059013 for Cytochrome P450 27C1 (Q4G0S4)?

The authors showed that "the human CYP27C1 gene encodes a retinoid 3,4-desaturase, hP450 27C1, with selectivity for all-trans retinol"

"The LC–UV analyses were used to obtain steady-state kinetic parameters for the desaturation of all-trans retinol, retinal, and retinoic acid as well as 11-cis-retinal"

New terms:
all-trans retinol 3,4-desaturase activity

all-trans retinal 3,4-desaturase activity

all-trans retinoic acid 3,4-desaturase activity

11-cis-retinal 3,4-desaturase activity

The new terms would be under GO:0016705 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen.

Kristian Axelsen of SIB has been contacted (there was a discrepancy on the name used by the authors on two different papers) and verified the name of the enzyme. He is requesting a new EC number for this protein based on this paper that will belong to EC 1.14.19. 
There is already a RHEA reaction available. It has the ID RHEA:50292 for the reaction without the defined direction. For the defined reactions the IDs are RHEA:50293-50295.

Thanks,

Penelope

**Comment by ukemi** [comment]
Hi Penelope,

The RHEA references above appear to only be for the all-trans retinol reactions. Can you please provide references or definitions for the other activities?

-D

**Comment by pgarmiri** [comment]
Hi David,

Thank you very much for your email and for looking into my request. As far as I understand this, the other compounds are substrates of the same reaction.
So, it would be the same as described in RHEA 
(all-trans-retinol + 2 H(+) + O2 + 2 reduced [adrenodoxin] <=> all-trans-3,4-didehydro retinol + 2 H2O + 2 oxidized [adrenodoxin] )

but instead of 'all-trans-retinol' and 'all-trans-3,4-didehydro retinol', it will have the pairs below:

all-trans retinal --> all-trans-3,4-didehydroretinal 
all-trans-retinoic acid  --> all-trans-3,4-didehydroretinoic acid 
11-cis-retinal --> 11-cis-3,4-didehydro retinal

Please, let me know if you need any more details.

Kind regards,

Penelope

**Comment by pgarmiri** [comment]
Thank you, David!

Penelope
