### ISSUE TITLE
NTR: cardiac muscle myoblast proliferation and regulation terms

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13609]
Hi,

Could I please have four new terms under parent: GO:0051450 myoblast proliferation

cardiac muscle myoblast proliferation
-regulation of cardiac muscle myoblast proliferation
--positive regulation of cardiac muscle myoblast proliferation
--negative regulation of cardiac muscle myoblast proliferation

For annotation of PMID:26512644.

Please add GOC:rph, GOC:BHF and GOC:BHF_miRNA as references.

Thanks,
Rachael.

**Comment by rachhuntley** [comment]
Hi Kimberly,
Could you please take a look at this soon? The terms are for my student who wants to do some analysis on her annotations in the next couple of weeks so she needs to get the annotations in as soon as possible to include the analysis in her thesis.

Thanks!
Rachael.

**Comment by vanaukenk** [comment]
@rachhuntley 
Here is a proposed definition for the new cardiac muscle myoblast proliferation term:

The multiplication or reproduction of cardiac muscle myoblasts, resulting in the expansion of a cardiac muscle myoblast cell population. 

Is that enough or would you like to add more to it?  Thx.

**Comment by vanaukenk** [comment]
@rachhuntley 
I've added the terms so your student can have them for annotation, but leaving the ticket open just in case you want to tweak the definition a bit.

**Comment by rachhuntley** [comment]
Hi Kimberly, 
Thanks very much for doing this so quickly. 
Could you please add this to the definition, to match the equivalent term for differentiation of this cell type (and the definition from Cell Ontology):
A cardiac myoblast is a precursor cell that has been committed to a cardiac muscle cell fate but retains the ability to divide and proliferate throughout life.

Rachael.
