### ISSUE TITLE
confusing term in slims "nitrogen compound metabolic process"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13615]
GO:0006807
nitrogen compound metabolic process

Definition
The chemical reactions and pathways involving organic or inorganic compounds that contain nitrogen, including (but not limited to) nitrogen fixation, nitrification, denitrification, assimilatory/dissimilatory nitrate reduction and the interconversion of nitrogenous organic matter and ammonium. Source: GOC:go_curators, CHEBI:51143, GOC:jl, ISBN:0198506732

Comment
Note that amino acid and derivative metabolism should not be annotated here. Instead use the 'amino acid and derivative metabolism' node.

What do we actually mean by this term?
The definition  and comment looks as though it is trying to describe another term where nitrogene is acted upon directly

GO:0071941 - nitrogen cycle metabolic process
Definition	Parents
A nitrogen compound metabolic process that contributes to the nitrogen cycle. The nitrogen cycle is a series of metabolic pathways by which nitrogen is converted between various forms and redox states; it encompasses pathways in which nitrogen is acted upon directly, such as nitrification, denitrification, nitrogen fixation, and mineralization.

To illustrate the problem, "nitrogen compound metabolic process" encompasses pretty much *every* annotated process (translation, DNA metabolism, etc etc)

http://amigo.geneontology.org/amigo/term/GO:0006807
S. cerevisiae has 22684 annotations to 3645 gene products annotated to this term.

If it  is required for grouping I suggest it be made "not for direct annotation" it just isn't useful... and probably people should reconsider its inclusion in slims. It is not needed for annotation coverage. 
PomBase slim uses GO:0071941 - nitrogen cycle metabolic process
which covers the things which are not covered by other processes (provided of course that annotation is  as specific as it can be).

**Comment by ukemi** [comment]
This term and its children are determined by the ChEBI cross-products (nitrogen molecular entity). So the structure is reflective of the ChEBI ontology. This includes a lot of biological compounds. In the context of the chemical structure, it is correct. Maybe it is not so useful as a slim term?

**Comment by ValWood** [comment]
That's my point!  It should not be a slim term ;)

I think sometimes it is used instead of 
GO:0071941 - nitrogen cycle metabolic process
because of  the wording

So the suggestions are
-[ ] clarify meaning 
(the comment does not make sense because this term DOES include
amino acid and derivative metabolism- its an ancestor)

- [ ]  remove this clause  
" including (but not limited to) nitrogen fixation, nitrification, denitrification, assimilatory/dissimilatory nitrate reduction and the interconversion of nitrogenous organic matter and ammonium" because it is making people think that this term is for this 
"GO:0071941 - nitrogen cycle metabolic process"

-[ ] Make this term not for direct annotation, its too broad to be useful since most  biolofgical compounds contain nitrogen

- [ ] suggest that people swap their slim term  from
GO:0006807nitrogen compound metabolic process
to
GO:0071941 - nitrogen cycle metabolic process

(You need  GO:0071941 - nitrogen cycle metabolic process in the  slim to capture some gene products which invoved in nitrification/denitrification etc)

**Comment by ukemi** [comment]
Do we have contact information for GO-Slims? We need a documented SOP for making changes to subsets.

**Comment by cmungall** [comment]
We could add metadata directly in the OWL, or have a separate yaml file - @dosumis ?

**Comment by ValWood** [comment]
Actually the term is only used in only used in 2 slims
goslim_pir	456
goslim_metagenomics	116

It is probably a redundant term in these slims, but they are quite extensive slims anyway so it isn't really a problem as such. Many slims contain terms like this.
I'd like to write some guidelines for creating and testing slims  for different purposes 
For example for  biological relevance, for non-redundant coverage, for comparisons, for QC  at some point.....

Although how well a species gene products slim non-redundantly  (or even at all) is ultimately  dependant on the depth of a species annotation.

I'm using them a lot at tpresent to asses core conserved unknown proteins and there are a lot of well -studied proteins which do not slim at all for some species.

**Comment by dosumis** [comment]
> We could add metadata directly in the OWL, or have a separate yaml file - @dosumis ?

If in the ontology we could annotate subsetdef axioms with orcids - but that's a bit obscure and would need extensions to OBO-OWL translation. It would be much easier as a separate YAML.  Then easy for anyone to edit.
