### ISSUE TITLE
ubiquitin homeostasis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13618]
Should we really have this term?
It has only 8 EXP annotations, and all seem to be things involved in ubiquitination to sme extent. This term only seems to provide a mechanism for inconsistent annotation.

The first one I looked at, describing
An inhibitor of a deubiquitinating enzyme regulates ubiquitin homeostasis.
(PMID:19410548)

would be better described as a  MF  "ubiquitin specific protease inhibitor" or similar with target molecules.

This term seems reminiscent of the old obsoleted term http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006512

**Comment by pgaudet** [comment]
Hi Val, 

Don't you think that the regulation of the 'intracellular concentrations of monomeric ubiquitins and free ubiquitin chains ' is a legitimate biological process ? I am concerned that the MF only doesn't capture what Rfu1 does in the paper you quote (PMID:19410548). 

However 'homeostasis' doesn't seem to capture clearly what is happening. Perhaps 'polyubiquitin recycling' would be more appropriate ? (PMID:19410534). 

Thanks, Pascale

**Comment by ValWood** [comment]
The "homeostasis" terms are always tricky. I'm never really sure about them. Isn't this one really just a consequence of everything  that regulates the addition or removal of ubiquitin?

The term was added in 2010 and clearly it isn't used consistently if it only has 8 EXP annotations.

**Comment by pgaudet** [comment]
There are annotations by MGI, SGD and Flybase: 
@ukemi 
@hattrill 
Would you be OK with an obsoletion? 

P0CG49	Ubb		GO:0010992	PMID:18070917	IMP	MGI
P0CG49	Ubb		GO:0010992	PMID:18299572	IMP	MGI
P0CG49	Ubb		GO:0010992	PMID:22285186	IGI	MGI
P0CG49	Ubb		GO:0010992	PMID:22285186	IMP	MGI
P0CG50	Ubc		GO:0010992	PMID:22285186	IGI	MGI
P0CG69	Ubi-p63E		GO:0010992	PMID:23884444	IMP	FlyBase
P14735	IDE		GO:0010992	PMID:21185309	IDA	UniProt
P32571	DOA4		GO:0010992	PMID:19410548	IMP	SGD
P36037	DOA1		GO:0010992	PMID:18508771	IMP	SGD
Q01476	UBP2		GO:0010992	PMID:25622294	IMP	SGD


Thanks,

Pascale

**Comment by hattrill** [comment]
I've removed ours. Have no objection to obsoletion.

**Comment by srengel** [comment]
Hi Pascale,
when annotations involve SGD, please ping me @srengel like you did David and Helen above.

**Comment by srengel** [comment]
SGD doesn't object.  we'll remove these annotations.

**Comment by ukemi** [comment]
I removed ours.

**Comment by pgaudet** [comment]
Related to this, I will also obsolete 'GO:0010993 regulation of ubiquitin homeostasis' and rehouse its children 
- GO:1904542 regulation of free ubiquitin chain polymerization
-  GO:1904544 positive regulation of free ubiquitin chain polymerization 
-  GO:1904543 negative regulation of free ubiquitin chain polymerization
-  GO:1904544 positive regulation of free ubiquitin chain polymerization 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete: 'GO:0010992 ubiquitin homeostasis' and its regulation 'GO:0010993 regulation of ubiquitin homeostasis' (no direct annotations). 

The reason for obsoletion is that the term is not clearly defined and annotations were inconsistent. All groups have now removed their annotations. 

Any comments can be added to the issue:
https://github.com/geneontology/go-ontology/issues/13618

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on June 26, 2017

*** Unless objections are received by June 26, 2017 , we will assume that you agree to this change. ***

Thanks,

Pascale

**Comment by srengel** [comment]
SGD is fine with this change.

**Comment by ValWood** [comment]
I think a 'polyubiquitin recycling'  @pgaudet you suggested would be more apt.
It's more about recycling then homeostasis. Do you want a tickets for this? Or use this one?

**Comment by pgaudet** [comment]
Hi @ValWood 
Do you suggest I rename the term, or obsolete and create a new one? 

Pascale

**Comment by ValWood** [comment]
If all of the annotations are related to recycling I don't see a problem to rename.

This would be a more robust way to capture what was intended by this old term
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006512
and "ubiquitin homeostasis" which is much too vague.
