### ISSUE TITLE
 formaldehyde catabolic process add parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13616]
cellular detoxification

(formaldehyde cross-links/forms adducts in protein and DNA)

This will allow us to  pull more annotations into slims.

**Comment by hdrabkin** [comment]
To be clear: you want:
"formaldehyde catabolic process"  is_a "cellular detoxification" ?

**Comment by ValWood** [comment]
That is correct, clarified this point

**Comment by ValWood** [comment]
There are 6 EXP ANNOTATIONS

2 E. coli and the SFA1 are detoxification. I presume the mouse  and the candida one also but did not check.

Probably a better suggestion is to do what @pgaudet  suggests here:
https://github.com/geneontology/go-ontology/issues/13611

and rename the term to 
"detoxification of formaldehyde"

**Comment by hdrabkin** [comment]
One IEA, the other an IMP, "Formaldehyde toxicity in Adh null mutants compared
with wild-type mice"  ; mice more sensitive  (lower LD50) when Adh5 KO'd .

**Comment by ValWood** [comment]
So here  https://github.com/geneontology/go-ontology/issues/13611
@pgaudet  suggested making a similar  term

cellular detoxification of x

Maybe that would also work here?

**Comment by hdrabkin** [comment]
already added parentage; will consider other part in a bit

**Comment by ValWood** [comment]
formaldehyde catabolic process
is part of cellular detoxification which works for me,
