### ISSUE TITLE
query "protein deglycation, methylglyoxal removal"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13612]
isn't this
GO:0036530
protein deglycation, methylglyoxal removal

rally the same as this?

GO:0019243
Name	methylglyoxal catabolic process to D-lactate via S-lactoyl-glutathione

(I.e isn't the protein here just an intermediate in the catabolic process?)

**Comment by hdrabkin** [comment]
Based on a ticket just opened, not all deglycation is protein specific, so I don't think we should merge these. See #13827
guanine deglycation
The removal of a sugar or dicarbonyl from a glycated guanine.

**Comment by hdrabkin** [comment]
However, now in looking at a couple of references for deglycation of proteins, these name of terms above might be confusing (at least I am confused).
see
http://www.sciencedirect.com/science/article/pii/S0003986103004247
Protein deglycation: not via  D-lactate via S-lactoyl-glutathione

"Two types of enzymes, fructosyl lysine oxidase and fructose lysine 3-phosphokinase, catalyze the deglycation reaction and generate free amine groups."

**Comment by hdrabkin** [comment]
I added glycation terms per #13827;
