### ISSUE TITLE
adhesion vs aggregation (affects slims)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13610]
I've never fully understood the difference between the 2 terms aggregation and adhesion

![aggregation vs adhesion](https://user-images.githubusercontent.com/7359272/26930351-0b354d92-4c55-11e7-9458-db7372b416e6.jpg)

cell aggregation is defined:
The clustering together and adhesion of initially separate cells to form an aggregate. Examples include the clustering of unicellular organisms or blood cells in suspension and the condensation of mesenchymal cells during cartilage formation.

flocculation is a type of cell-cell adhesion

I was trying to figure why flocculins (an adhesion molecule) do not always slim to adhesion

**Comment by ukemi** [comment]
Flocculation is a population phenomenon and is at the level of many cells. Cell-cell adhesion is the adhesion between two cells. So flocculation is not a type of cell-cell adhesion. Cell-cell adhesion is not always a part_of flocculation. It also does not look as if flocculation has cell cell adhesion as a necessary part since there is a child called 'flocculation via extracellular polymer'.

**Comment by ValWood** [comment]
Hmm, this is very mixed up.

term: flocculation via extracellular polymer
def: Non-sexual aggregation of single-celled organisms mediated by polymers (polysaccharides, proteins, and/or nucleic acids) secreted into the extracellular environment. 

GO:0032128 flocculation via extracellular polymer has no annotations
this is supported by a reference to PMID:14538073
which describes  extracellular biopolymeric flocculants (EBFs)  

The way flocculants  are described in this paper, they encompass cell surface glycoproteins.
Note:  this paper doesn't mention "nucleic acids" as mediators of flocculation?

In yeast, flocculation occurs by one known  single mechanism, the  expression of adhesion molecules on the cell surface. The adhesion molecules are fairly typical glycoproteins.

This is biological floculation in yeast:
![flocculation](https://user-images.githubusercontent.com/7359272/27009710-197503cc-4e8d-11e7-906c-f5dcabec7116.jpg)

Flocculation IS  cell-cell adhesion, so it fits this def:
GO:0098609 cell-cell adhesion
"The attachment of one cell to another cell via adhesion molecules'

i.e. The flocculins  are cell-surface molecules which  adhere to each other, or other components of the yeast cell surface 


From PMID:14538073
"The biopolymer flocculants cause aggregation of particles and cells by bridging and charge neutralization. Bridging occurs if the biopolymeric flocculant extends from the particle’s surface into the solution for a distance greater than the distance over which the interparticle repulsion acts. In this case, the biopolymer can adsorb to other particles to form flocs. This mechanism explains flocculation by neutral or like-charged bioflocculants (Levy et al., 1992; Hantula and Bamford, 1991b). Charge neutralization occurs when the biopolymer flocculant is oppositely charged compared to the particles. In this case, the particle surface charge density is reduced by adsorption of the bioflocculant and the particles can approach sufficiently close to each other so that attractive forces become effective (Levy et al., 1992; Hantula and Bamford, 1991b).

This paper is from a biophysical/biotechnological  perspective, also the papers referred to in the review are VERY old and predate knowledge of the  flocculation gene products in yeast.

You can probably induce  flocculation by adding other polymers to  to a liquid culture, but  this isn't a known  mechanism for  any yeast.  I wonder if bacteria can flocculate  using nucleic acids ?

**Comment by ukemi** [comment]
In any case, it is still a process described at the level of a population.

**Comment by ValWood** [comment]
So I think I should use the  term 

GO:0043690 cell-cell adhesion involved in flocculation via cell wall protein-carbohydrate interaction

This gives all the parents. I'm sure some of this is a bit strange because I can only find any reference to this single mechanism of flocculation (via cell surface adhesion molecules, which are glycoproteins). There soon to be a lot of terms to describe a single process/mechanism.

Will close anyway...
