### ISSUE TITLE
degradation of Argonaute-bound small RNAs

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13620]
Hello,
I would like to request the following terms:

- small RNA (sRNA) catabolism involved in regulation of RNA interference 
This term is for a mechanism involving the adenylase cid14 and uridylase cid16 and the ribonuclease rrp6. cid14/cid16 adds nontemplated As and Us to small RNAs bound by Argonaute. The addition of these nt's targets the sRNA for degradation by rrp6. Triman can trim As to 'detag' the degradation signal. This process is important in order to protect the genome from uncontrolled RNAi.

- RNA 3'-end adenylation 

PMID:28541282

Cheers

**Comment by vanaukenk** [comment]
Hi @Antonialock 
Can you provide definitions and suggested ontology placement for each of these terms?  Thx.

**Comment by Antonialock** [comment]
GO:1900368
NTR: small RNA catabolic process

small RNA (sRNA) catabolism involved in regulation of RNA interference
The degradation of small RNA (sRNA) to regulate silencing by RNAi.

"Eukaryotes have evolved various surveillance mechanism to monitor the quality of RNAs. Addition of non-templated nucleotides to the 3′ end of sRNAs is conserved in most organisms and promotes their degradation commonly before loading onto Argonaute. In Drosophila, however, Wispy was shown to adenylate Argonaute-bound maternally deposited mature miRNA which are then eliminated by a yet unknown nuclease(s)19. This suggested that mature sRNAs could be actively removed from Argonaute. We show here, that the non-canonical nucleotidyl-transferase Cid14 adenylates and Cid16 uridylates Argonaute-bound sRNAs. Both Cid14 and Cid16 are able to recruit Rrp6 in vitro to degrade Argonaute-bound sRNAs"

"In this study, we show that Cid14 and Cid16 add non-templated nucleotides to Argonaute-bound sRNAs and promote their degradation by the exosome in vitro. Our data suggest that tailing and degradation of Argonaute-bound sRNAs protect the genome from uncontrolled RNAi. miRNAs are essential in regulating gene expression in multicellular organisms44. Degradation of Argonaute-bound miRNAs may be necessary to exchange miRNAs from Argonaute during cell differentiation and development. A defect in turnover of Argonaute-bound sRNAs might also lead to uncontrolled silencing and tumorigenesis in mammalian cells. It will be interesting in the future to investigate tailing and degradation of Argonaute-bound sRNAs in various mammalian cell types and during cell differentiation, development and tumorigenesis."

**Comment by Antonialock** [comment]
Actually, maybe I want a more specific term name...
small RNA catabolic process involved in regulation of rna interference
"The degradation of sRNAs through the addition of non-templated nucleotides to Argonaute bound sRNAs (small RNAs), that promote their degradation by the exosome." 

is_a  GO:0006401 RNA catabolic process
is_a  GO:1900368 regulation of RNA interference

I requested a SO term for small RNA
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/401

**Comment by Antonialock** [comment]
I hope that RNA 3'-end adenylation is straight-forward?
The enzymatic addition of a sequence of adenylyl residues at the 3' end of an RNA molecule. 
is_a  GO:0031123 RNA 3'-end processing

**Comment by ValWood** [comment]
Am removing "more info needed" as Antonia responded. Please let us know if more info still needed.

**Comment by Antonialock** [comment]
Hi, is it possible for someone to have a look at this soonish? It is a community curated session and it would be great to tell the PI that his annotations are in.

**Comment by Antonialock** [comment]
So has modified the definition of SO:0000370 small_regulatory_ncRNA to fit with this

**Comment by ValWood** [comment]
For the deadenylation one can't you use existing:

polynucleotide adenylyltransferase activity   has substrate SO:0001035
part of
GO:0043630 - ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process  

In fact  "GO:0043630 - ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process " is one of those daft terms where the process replicates the function

so more simply
polynucleotide adenylyltransferase activity   has substrate SO:0001035
part of
 GO:0071046    nuclear polyadenylation-dependent ncRNA catabolic process
(I'm guessing it's the nuclear pathway)


You could also do

polynucleotide adenylyltransferase activity   has substrate SO:0001035
part of
 GO:0071046    nuclear polyadenylation-dependent ncRNA catabolic process
involved_in negative regulation of RNAi

**Comment by Antonialock** [comment]
well if RNA 3' adenylation isn't a good term to create then perhaps it doesn't make sense for RNA 3' uridylation to exist?..

**Comment by ValWood** [comment]
Yes you are correct, it is inconsistent and maybe the  " RNA 3' adenylation" should be there.

... if not  3' uridylation should probably go but we only have


RNA uridylyltransferase activity
really we need  3' RNA uridylyltransferase activity

**Comment by vanaukenk** [comment]
@ValWood - what is the GO ID for 'RNA 3' adenylation' ?

Thx.

**Comment by ValWood** [comment]
corrected comment.
v

**Comment by vanaukenk** [comment]
Okay, how about this.

Create two new MF terms:

GO:1990817 RNA adenylyltransferase activity
-is_s GO:new 3' RNA adenylyltransferase activity

GO:0050265 RNA uridylyltransferase activity
is_a GO:new 3' RNA uridylyltransferase activity

Then propose a merger of GO:0071076 RNA 3' uridylation into GO:new 3' RNA uridylyltransferase activity.

**Comment by ValWood** [comment]
yep, but I thought merging  process into functions was problematic?

**Comment by vanaukenk** [comment]
@ValWood @Antonialock 
I was going to add the new MF terms, but looking at the parent definitions, I have a few more questions.

GO:1990817 RNA adenylyltransferase activity 
Defintion: Catalysis of the template-independent extension of the 3'- end of an RNA strand by addition of one adenosine molecule at a time. Cannot initiate a chain 'de novo'. The primer, depending on the source of the enzyme, may be an RNA, or oligo(A) bearing a 3'-OH terminal group. Source: GOC:vw

From the definition, it looks like this term is already referring to adding adenosines to the 3' end. 

I could make this definition more general like that of GO:0050265:

GO:0050265 RNA uridylyltransferase activity
Catalysis of the reaction: UTP + RNA(n) = diphosphate + RNA(n+1). Source: EC:2.7.7.52, MetaCyc:RNA-URIDYLYLTRANSFERASE-RXN

but do adenosines and uridines get added anywhere other than the 3' end with these activities, i.e. should the parent terms both refer to adding to the 3' end and any child terms refer to further classification based on the types of RNA molecules they act upon?

**Comment by Antonialock** [comment]
I think these activities all refer to "tailing" (i.e. adding to 3'end - I could be wrong, I'm not an expert, but it makes sense...)

I think substrate specificity can be added using extensions? (using SO terms or IDs). 

I would be happy to annotate to the MFs RNA adenylyltransferase activity **&** RNA uridylyltransferase activity

What I do not like is the ambiguity in allowing one process term to exist (RNA 3' adenylation) but not  another (RNA 3' uridylation). There should be one "consensus".

As a tangent - personally I do not think that "RNA 3' adenylation" is a very useful term - in this case I do not know of any proteins that contribute to this process that do not also perform the molecular function,  so feel free to obsolete. I would prefer to annotate to something like "MF: 3' adenylation, involved_in BP: regulation of gene silencing, has_substrate gene:X" etc

**Comment by vanaukenk** [comment]
@Antonialock 
I agree that there is ambiguity and inconsistency here about what we are representing in MF vs BP.
I've been looking carefully at how curators annotate these enzymes with respect to each aspect and hope to have a more concrete proposal about exactly what we should do here by early next week.  There is a lot of inconsistency in the annotation wrt the BP terms that curators pick for these enzymes.

**Comment by pgaudet** [comment]
@ValWood Is this still relevant ?

**Comment by ValWood** [comment]
I think the last few comments are still relevant.


particularly @Antonialock 
What I do not like is the ambiguity in allowing one process term to exist (RNA 3' adenylation) but not another (RNA 3' uridylation). There should be one "consensus".

As a tangent - personally I do not think that the BP "RNA 3' adenylation" is a very useful term - in this case I do not know of any proteins that contribute to this process that do not also perform the molecular function, so feel free to obsolete. I would prefer to annotate to something like "MF: 3' adenylyltransferase activity, involved_in BP: regulation of gene silencing, has_substrate gene:X" etc


@vanaukenk  was going to propose a solution.

**Comment by pgaudet** [comment]
I guess the immediate solution is to obsolete GO:0071076 RNA 3' uridylation, but how about all other modifications? 

'rRNA methylation'
'rRNA acetylation involved in maturation of SSU-rRNA'
'rRNA acetylation'
'rRNA 2'-O-methylation'
'miRNA 2'-O-methylation'
'mRNA methylation'
'primary miRNA methylation'
'RNA (guanine-N7)-methylation'
'rRNA methylation'
'snRNA methylation'
'tRNA methylation'
'rRNA methylation'
'rRNA 2'-O-methylation'
'rRNA base methylation'

etc ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I would close this particular ticket and deal with RNA modification as a block close protein modification is done ;)
