### ISSUE TITLE
OTR viral induced premature senescence (GO:0090401)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13626]
Hello, 

Looking at #12975 - the term 'viral induced premature senescence' should be clarified. 

Right now the definition ("A cellular senescence process associated with the dismantling of a cell as a response to viral infection") is very similar to that of "killing by symbiont of host cells" or at least "disruption by symbiont of host cell" (def: "A process by which a virus has a negative effect on the functioning of the host's cell."). 
Also, the 'dismantling' of cell as described in 'viral induced premature senescence' appears much more lethal compared to how cellular senescence is described ("A cell aging process stimulated in response to cellular stress, whereby normal cells lose the ability to divide through irreversible cell cycle arrest.")

 @RLovering : BHF created this term: There are no papers cited in the definition and no annotations. Usage examples would be very useful to decide if it's a host defense process or a disease process. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Is this a possible paper you were trying to annotate ? 
http://genesdev.cshlp.org/content/14/16/2015.short

**Comment by pgaudet** [comment]
@pmasson55 Do you have any comment to make on this term ? What do you recommend we do with it ?

**Comment by RLovering** [comment]
Please do what is needed - sorry not more helpful

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0090401 viral induced premature senescence. 

The reason for obsoletion is that it’s not clear what the term is meant to be used for; there are no annotations and no references. There is nothing in the literature that mentions this process; there are papers that mention viral proteins overcoming premature senescence, for example: PMID:22326283.


Please add any comments to the issue: https://github.com/geneontology/go-ontology/issues/13626

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Dec 11, 2017. Unless objections are received by Dec 11, 2017, we will assume that you agree to this change.

Thanks, Pascale

**Comment by plemercier** [comment]
Dear all,
I agree to obsolete this term. I don't know any virus using this process to its advantage.

Cheers

Philippe Le Mercier
