### ISSUE TITLE
Suggestion to review taxon restraints on GO:1990077

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#13633]
Hi all,

The team working on UniRule noticed a taxon restraint on the term GO:1990077 primosome complex limiting it to prokaryotes. I think based on the definition of the term that it is incorrect to restrain it to just prokaryotes at this level in the ontology since it is defined as:

Any of a family of protein complexes that form at the origin of replication or stalled replication forks and function in replication primer synthesis in all organisms. Early complexes initiate double-stranded DNA unwinding. The core unit consists of a replicative helicase and a primase. The helicase further unwinds the DNA and recruits the polymerase machinery. The primase synthesizes RNA primers that act as templates for complementary stand replication by the polymerase machinery. The primosome contains a number of associated proteins and protein complexes and contributes to the processes of replication initiation, lagging strand elongation, and replication restart.

Now granted the PMID that is listed for the defintion on the QuickGO page (http://www.ebi.ac.uk/QuickGO-Beta/term/GO:1990077) links to a paper about bacteria but eukaryotes also have a primosome complex, including humans (PMID:26975377). 

I would like to suggest that we remove the taxon restraint for GO:1990077, as well as for two of it's child terms (GO:1990099 - pre-primosome complex and GO:1990098 - core primosome complex). 

Best,

George

**Comment by bmeldal** [comment]
Please revisit the following tickets as this discussion goes back 4 years! And the taxon restriction was put in only 10 months ago: it caused wrongs defs for euks as their primosome has different functions to proks
#12575
#11165
#10488

Birgit

@ValWood @mah11

**Comment by ValWood** [comment]
Thanks Birgit! I knew there was some history to this but I couldn't find it and @mah11  is on holiday!

I did check last nigh though and there are  eukaryotic annotations to the taxon restricted term... @cmungall  are taxon restrictions being reported and dealt with routinely?
I though annotations were filtered and reported?

**Comment by bmeldal** [comment]
Ha ha! One of these was your own ticket, Val! I filtered by "is:closed primosome"

Over to the editors for some fun :)

**Comment by ukemi** [comment]
So is the action here to revert these edits?

**Comment by ggeorghiou** [comment]
Hi David,

After reviewing the older tickets, it seems that the eurkaryotic version of the primosome is GO:0005658  (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005658#term=ancchart). I see the point that Birgit made that the eukaryotic and prokaryotic primosome are different in regards to their function since the prokaryotic primosome seems to be capable of multiple functions besides initiating the replication of the lagging strand. Please revert the edits (sorry for making you work on this again!) and I will discuss with the UniRule team about how to proceed.

**Comment by ValWood** [comment]
this part of the def should be revised to make it clear this is a prokaryote specific complex


"Any of a family of protein complexes that form at the origin of replication or stalled replication forks and function in replication primer synthesis in all organisms."

**Comment by bmeldal** [comment]
should it just be "...in prokaryotes." instead of "in all organisms."?
