### ISSUE TITLE
Error in GO 0097710 viral terminase, small subunit 

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#13636]
_From @mirandajarnot on June 12, 2017 11:23_

The PT for this concept specifies the small subunit, but it also has an SY that is the large subunit.  Perhaps this is a typo and should read "small" for the SY as well:

viral terminase, small subunit [GO2017_04_28/PT/GO:0097710]
virus terminase, large subunit [GO2017_04_28/SY/GO:0097710]

There is another existing concept for the large subunit:

viral terminase, large subunit [GO2017_04_28/PT/GO:0098009]
virus terminase, large subunit [GO2017_04_28/SY/GO:0098009]

Thanks,
Miranda Jarnot
UMLS, NLM

_Copied from original issue: geneontology/helpdesk#25_

**Comment by kltm** [comment]
@ukemi I guess I will randomly choose you as the rep for https://github.com/geneontology/go-ontology for this.
Should this be ported over to that tracker?

**Comment by kltm** [comment]
_From @ukemi on June 12, 2017 16:45_

@ktlm Yes, port this over to the ontology tracker and I will assign it to an appropriate editor.

**Comment by pgaudet** [comment]
Inadvertently removed is_a parent ! added back.
