### ISSUE TITLE
NTR: microglial cell (CL:0000129) activation (and maybe: glial cell (CL:0000243) activation)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13642]
Hello,

I am annotating PMID: 18723082, which demonstrates activation of astrocytes as well as microglial cells in response to amyloid-beta. https://www.ncbi.nlm.nih.gov/pubmed/18723082

We currently have the GO term: 'GO:0048143 astrocyte activation' https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0048143
However, there appears to be no term for 'microglial cell activation'.

In the CL ontology 'CL:0000129 microglial cell' and 'CL:0000127 astrocyte' are both descendants of 'CL:0000243 glial cell (sensu Vertebrata)'. So in GO, the new term 'microglial cell activation' could be positioned as a child of 'GO:0001775 cell activation' (as is currently the case for 'GO:0048143 astrocyte activation'), or an additional term 'glial cell (CL:0000243) activation' can be included as a child of 'GO:0001775 cell activation', and a parent of both' GO:0048143 astrocyte activation' and NEW GO term 'microglial cell activation'.

> 'GO:0001775 cell activation'
>> NEW GO term 'glial cell (CL:0000243) activation'
>>> 'GO:0048143 astrocyte activation'
>>> NEW GO term 'microglial cell (CL:0000129) activation'

This issue is loosely related to a previous NTR #13574. 

DbxRef: ARUK-UCL and GOC:bc.

Thanks,
Barbara

**Comment by ukemi** [comment]
Hi Barbara,

We already have microglial cell activation GO:0001774. I have added glial cell activation. Both the astrocyte and the microglial terms are correctly classified under this.

**Comment by BarbaraCzub** [comment]
Thanks @ukemi 
Not sure how I missed this.
