### ISSUE TITLE
Ribitol beta1,4-xylosyltransferase

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#13641]
Hi,
I would need a new GO term for this enzyme

Thanks

Sylvain

Category: Function
Description: Ribitol beta1,4-xylosyltransferase
Definition: Catalysis of the reaction: UDP-D-xylose + D-ribitol 5-phosphate-R = UDP + beta1,4-xylosyl-D-ribitol 5-phosphate-R
child of GO:0035252 UDP-xylosyltransferase activity
PMID:27733679

**Comment by krchristie** [comment]
Hi Sylvain,

I've added your new term. You can see it here: 
https://github.com/geneontology/go-ontology/pull/13649/files 

[ignore the +/- "subset: goslim_synapse" lines probably due to someone else's edits getting reordered on save from Protege].

-Karen
