### ISSUE TITLE
ntr: detoxification of furfural

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13648]
standard def
parentage "cellular detoxification"
PMID: 25656103

**Comment by deustp01** [comment]
furfural?

**Comment by ValWood** [comment]
yep

**Comment by cmungall** [comment]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=34768

I think fufural sounds delightful though

**Comment by vanaukenk** [comment]
@ValWood 
It looks like there are already some annotations from this paper to GO:1901426 'response to furfural'.
http://amigo.geneontology.org/amigo/reference/PMID:25656103
As well as annotations from another paper:
migo.geneontology.org/amigo/reference/PMID:25656244
We could make the detoxification term a part_of the response to furfural and then check with SGD about what term they would prefer to use for their annotations?

**Comment by ValWood** [comment]
Yes make the detoxification part_of the response to term. Then I'll contact SGD. I'm trying to normalize the unknowns between the 2 yeasts with a biologically relevant slim (and this doesn't include "response to" which could be cellular role....

cheers

val

**Comment by ValWood** [comment]
Hi @vanaukenk  could we add this one. I'll ask SGD to migrate down when it's in place.

**Comment by ValWood** [comment]
I'm trying to group the set of enzymes involved in detoxification so that we can  use as a "test set" for machine learning type processes to align the unknowns with exisiting bins. I think most of the pombe unknowns are detoxification but I don't have a good  "positive test set" to look for correlations with.

**Comment by ValWood** [comment]
Maybe there should be a general
 "detoxification of cellular aldehydes" term?

I have another "unknown" where the yeast ortholog is recently characterised
https://github.com/pombase/curation/issues/1721


"YKL071W from Saccharomyces cerevisiae encodes a novel aldehyde reductase for detoxification of glycolaldehyde and furfural derived from lignocellulose."
PMID: 29034432

so if we had
detoxification of  cellular aldehyde
-- GONEW detoxification of  furfural
-- GONEW detoxification glycolaldehyde
-- GO:0046294  formaldehyde catabolic process (which is under cellular detoxification)

**Comment by ValWood** [comment]
also PMID:28265724

There might be a better way to do "detoxification"?

MF part of "cellular detoxification"? (ignoring specific compound in process)
or a general compound-type process grouping  (cellular aldehyde) rather than every chemical.

Happy for any solution....

**Comment by ValWood** [comment]
Is it possible to get this  one? I can use  
" detoxification of cellular aldehyde" for 3 pombe  orthologs.
I'm trying to tidy the unknows as part of a publication.

SGD have not annotated YKL071W yet, I pinged their helpdesk.

Let me know if there is an issue,

thanks

Val

**Comment by ValWood** [comment]
Hi @vanaukenk ,

is it possible to add 
 "detoxification of cellular aldehyde" 
I wan't to use for an analysis...

thanks 

val

**Comment by ValWood** [comment]
Hi @vanaukenk  

is it possible to add this term (should be quick?), it's a blocker for my "unknowns" project and I'd like to get this wrapped up over the holidays so that I can move back to finishing the matrix paper in the new year.)
cheers,

val

**Comment by ValWood** [comment]
note to self,
also "old yellow enzyme"

**Comment by vanaukenk** [comment]
@ValWood - sorry for the delay with this one.

Shall I add:

GO:1990748 cellular detoxification
-is_a GO:new cellular detoxification of aldehyde

GO:1901701 cellular response to oxygen-containing compound
-is_a GO:new cellular response to aldehyde
-_part_of GO:new cellular detoxification of aldehyde

**Comment by vanaukenk** [comment]
@ValWood - when you get a chance, just let me know if the proposal above makes sense and works for you.  Thx.

**Comment by ValWood** [comment]
looks great! thanks.
v
