### ISSUE TITLE
OTR Should 'GO:0031146 SCF-dependent proteasomal ubiquitin-dependent protein catabolic process' be a child of 'GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13646]
Hello, 

I was wondering why  'GO:0031146 SCF-dependent proteasomal ubiquitin-dependent protein catabolic process' is not a child of 'GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process'. 

Unless there are objections I will create the relation between these two terms. 

Thanks, Pascale

**Comment by ValWood** [comment]
I see the parent in QuickGO?

val

**Comment by pgaudet** [comment]
Really ? 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/4782928/27091562-7ee4fdd2-502e-11e7-96cc-63bdee9a4886.png">

**Comment by ValWood** [comment]
oh yeah I was reading 
GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process

I don't know why we need "protein ubiquitination" or any of the children

we would use
MF "protein ubiquitin ligase"  (or one of the other MFs)  involved in
"GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process"

I wonder if the SCF term is broader then the "ubiquitination" though?
It is describing the entire pathway, ubiquitination to proteolysis....

**Comment by pgaudet** [comment]
Val is right - the 2 terms I mentioned were actually children of each other.
