### ISSUE TITLE
Convert TermGenie templates to DOSDPs

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13643]
This probably needs to be done by hand.

List of GO TG templates (review - do we really want all of them?):

(How do we generate this given that TG is down?

Location of GO TG template javascript:

https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go

**Comment by cmungall** [comment]
I think by hand. Should we just split this up amongst us? I think this would be really good pre-meeting training in DPs. Note that you don't need to be a programmer to do this, for the phenotype project a curator wrote all the YAML.

I suggest people make  PRs and these are reviewed by @dosumis and myself.

**Comment by dosumis** [comment]
Munged together a table to track progress:

| category | pattern_file | to keep? | claimed_by | status |
| --- | --- | --- | --- | --- |
|  | [all_regulation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///all_regulation.js) | ? | ? | TODO |
|  | [all_regulation_mf.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///all_regulation_mf.js) | ? | ? | TODO |
|  | [cc_assembly_disassembly.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///cc_assembly_disassembly.js) | ? | ? | TODO |
|  | [cc_organization.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///cc_organization.js) | ? | ? | TODO |
|  | [cc_transport.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///cc_transport.js) | ? | ? | TODO |
|  | [cc_transport_from_to.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///cc_transport_from_to.js) | ? | ? | TODO |
|  | [envenomation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///envenomation.js) | ? | ? | TODO |
|  | [involved_in.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///involved_in.js) | ? | ? | TODO |
|  | [involved_in_mf_bp.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///involved_in_mf_bp.js) | ? | ? | TODO |
|  | [involved_in_x_y.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///involved_in_x_y.js) | ? | ? | TODO |
|  | [macromolecular_complex_binding.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///macromolecular_complex_binding.js) | ? | ? | TODO |
|  | [occurs_in.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///occurs_in.js) | ? | ? | TODO |
|  | [part_of_cell_component.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///part_of_cell_component.js) | ? | ? | TODO |
|  | [protein_complex_by_activity.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///protein_complex_by_activity.js) | ? | ? | TODO |
|  | [protein_localization_to.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///protein_localization_to.js) | ? | ? | TODO |
|  | [regulation_by.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///regulation_by.js) | ? | ? | TODO |
|  | [single_multi_organism_process.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///single_multi_organism_process.js) | ? | ? | TODO |
|  | [x_development.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///x_development.js) | ? | ? | TODO |
|  | [x_formation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///x_formation.js) | ? | ? | TODO |
|  | [x_maturation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///x_maturation.js) | ? | ? | TODO |
|  | [x_morphogenesis.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///x_morphogenesis.js) | ? | ? | TODO |
|  | [x_regulation_triad.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///x_regulation_triad.js) | ? | ? | TODO |
|  | [x_structural_organization.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go///x_structural_organization.js) | ? | ? | TODO |
| chebi | [biosynthesis_from.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/biosynthesis_from.js) | ? | ? | TODO |
| chebi | [biosynthesis_via.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/biosynthesis_via.js) | ? | ? | TODO |
| chebi | [catabolism_to.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/catabolism_to.js) | ? | ? | TODO |
| chebi | [catabolism_via.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/catabolism_via.js) | ? | ? | TODO |
| chebi | [chemical_binding.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_binding.js) | ? | ? | TODO |
| chebi | [chemical_export.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_export.js) | ? | ? | TODO |
| chebi | [chemical_homeostasis.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_homeostasis.js) | ? | ? | TODO |
| chebi | [chemical_import.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_import.js) | ? | ? | TODO |
| chebi | [chemical_import_into.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_import_into.js) | ? | ? | TODO |
| chebi | [chemical_response_to.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_response_to.js) | ? | ? | TODO |
| chebi | [chemical_transport.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_transport.js) | ? | ? | TODO |
| chebi | [chemical_transport_from_to.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_transport_from_to.js) | ? | ? | TODO |
| chebi | [chemical_transporter_activity.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/chemical_transporter_activity.js) | ? | ? | TODO |
| chebi | [metabolism_catabolism_biosynthesis.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/metabolism_catabolism_biosynthesis.js) | ? | ? | TODO |
| chebi | [transmembrane_transport_bp.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/transmembrane_transport_bp.js) | ? | ? | TODO |
| chebi | [transmembrane_transport_mf.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//chebi/transmembrane_transport_mf.js) | ? | ? | TODO |
| cl | [cell_apoptosis.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//cl/cell_apoptosis.js) | ? | ? | TODO |
| cl | [cell_differentiation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//cl/cell_differentiation.js) | ? | ? | TODO |
| cl | [cell_migration.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//cl/cell_migration.js) | ? | ? | TODO |
| uberon | [metazoan_development.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//uberon/metazoan_development.js) | ? | ? | TODO |
| uberon | [metazoan_formation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//uberon/metazoan_formation.js) | ? | ? | TODO |
| uberon | [metazoan_maturation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//uberon/metazoan_maturation.js) | ? | ? | TODO |
| uberon | [metazoan_morphogenesis.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//uberon/metazoan_morphogenesis.js) | ? | ? | TODO |
| uberon | [metazoan_structural_organization.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//uberon/metazoan_structural_organization.js) | ? | ? | TODO |
| pro | [protein_binding.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//pro/protein_binding.js) | ? | ? | TODO |
| pro | [structural_protein_complex.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//pro/structural_protein_complex.js) | ? | ? | TODO |
| plant | [plant_development.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//plant/plant_development.js) | ? | ? | TODO |
| plant | [plant_formation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//plant/plant_formation.js) | ? | ? | TODO |
| plant | [plant_maturation.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//plant/plant_maturation.js) | ? | ? | TODO |
| plant | [plant_morphogenesis.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//plant/plant_morphogenesis.js) | ? | ? | TODO |
| plant | [plant_structural_organization.js](https://github.com/geneontology/termgenie/tree/master/TermGenie/TermGenieRulesDynamic/src/main/resources/rules/go//plant/plant_structural_organization.js) | ? | ? | TODO |

**Comment by dosumis** [comment]
I'll do a few as examples.  Note - I now have a way to spec synonym combinations (actually turns out to be possible with the basic DOSDP spec).

**Comment by dosumis** [comment]
Added draft regulation patterns (see above)

**Comment by pgaudet** [comment]
This is now a Project: https://github.com/geneontology/go-ontology/projects/16
