### ISSUE TITLE
NTR: regulation terms for GO:0016303 1-phosphatidylinositol-3-kinase activity

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13647]
Hello,

Figures 5-7 in PMID: 18723082 show that amyloid-beta protein 42 interaction with FRP2 positively regulates 'GO:0016303 1-phosphatidylinositol-3-kinase activity' which in turn positively regulates 'GO:0070371 ERK1 and ERK2 cascade' (Figures 5-7).

Could I please request regulation terms for 'GO:0016303 1-phosphatidylinositol-3-kinase activity' ?
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016303 

GO NTR1: 'regulation of 1-phosphatidylinositol-3-kinase activity'
GO NTR2: 'positive regulation of 1-phosphatidylinositol-3-kinase activity'
GO NTR3: 'negative regulation of 1-phosphatidylinositol-3-kinase activity'

DbxRef: ARUK-UCL and GOC:bc.

Thanks,
Barbara

**Comment by ukemi** [comment]
Hi @BarbaraCzub 
I meant to ask this before. I think the xref that you want is-- GOC:aruk. That's what I have been using for your other requests.

**Comment by BarbaraCzub** [comment]
Hi @ukemi yes, I think it is in fact 'GOC:aruk' in code even though it is displayed in browsers as 'ARUK-UCL'. I'll make a mental note to refer to it as 'GOC:aruk' in the future, thanks.
