### ISSUE TITLE
GO:0009399 nitrogen fixation taxon restrictions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13658]
never in fungi
never in metazoa

will resolve Q9H1K1 etc

**Comment by ukemi** [comment]
It already has the only in prokaryotes restriction.

**Comment by ValWood** [comment]
not showing in QuickGO ?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009399

Also is alerting working @cmungall  ?

**Comment by hdrabkin** [comment]
I would have thought that if I put only in prokaryotes, it should not be necessary also specify never in fungi, etc.

**Comment by ValWood** [comment]
Yes but I don't see *any* taxon restrictions  right now in QUickGO?

**Comment by hdrabkin** [comment]
While I'm poking around on my end, do you see any taxon restrictions for any terms or do you mean just for this term?
Can you tell me one where you can see the restrictions so I can compare how they were specificed? 
Thanks

**Comment by ValWood** [comment]
I don't see any. I think its a known issue...

**Comment by ValWood** [comment]
We can close this, as the taxon restriction is present but not displayed and there is another ticket for this.
