### ISSUE TITLE
EMC complex update

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13657]
is defined
A transmembrane protein complex that is involved in protein folding in the endoplasmic reticulum. In S. cerevisiae, it has six members: EMC1, EMC2, AIM27, EMC4, KRE27, and EMC6. 
PMID:19325107

referencing a paper from a screen.
This seems quite out of date? It doesn't appear to have a role in folding?

The ubiquitous and ancient ER membrane protein complex (EMC): tether or not?
Wideman JG.
Version 2. F1000Res. 2015 Aug 25 [revised 2015 Oct 5];4:624. doi: 10.12688/f1000research.6944.2. eCollection 2015.
PMID: 26512320 

A conserved endoplasmic reticulum membrane protein complex (EMC) facilitates phospholipid transfer from the ER to mitochondria.
Lahiri S, Chao JT, Tavassoli S, Wong AK, Choudhary V, Young BP, Loewen CJ, Prinz WA.
PLoS Biol. 2014 Oct 14;12(10):e1001969. doi: 10.1371/journal.pbio.1001969. eCollection 2014 Oct.
PMID: 25313861 

ER membrane protein complex required for nuclear fusion.
Ng DT, Walter P.
J Cell Biol. 1996 Feb;132(4):499-509.
PMID: 8647883

**Comment by ValWood** [comment]
Note I only came across this because I was preparing
PMID: 27708008
A global genetic interaction network maps a wiring diagram of cellular function.
for journal club.
I wasn't annotating.  I sent a list of potential GO and phenotype annotations  to SGD with a link to this ticket.

Lots of nice use of GO.....

**Comment by krchristie** [comment]
HI Val,

Do you just think the definition needs updating? and do you have a proposal for a new definition?

-Karen

**Comment by ValWood** [comment]
Our findings indicate that
the EMC mediates lipid transfer from the ER to mitochondria by
facilitating tethering between these organelles.

I guess the primary role is "membrane tethering"

How about:
A transmembrane protein complex that is involved in  ER-mitochondrial membrane tethering to facilitate phospholipid transfer. In S. cerevisiae, it has six members: EMC1, EMC2, AIM27, EMC4, KRE27, and EMC6.
PMID:19325107

**Comment by krchristie** [comment]
Interesting that intermembrane lipid transfer proteins I've recently been annotating might be part of the "as yet unknown" non-vesicular mechanism by which the lipids are actually transferred...

I took a quick look at PMID:25313861, which showed the complex is in the ER, so if I add that tidbit, and change the wording a little to try to make it clear that it's the tethering that is facilitating the lipid transfer. I also made it more general, on the suspicion that it's probably not specific to phospholipids, but is true for any of the lipids transferred by intermembrane transfer. How does this sound to you?:

A transmembrane protein complex located in the ER that is involved in ER-mitochondrial membrane tethering, which is required to facilitate lipid transfer. In S. cerevisiae, it has six members: EMC1, EMC2, AIM27, EMC4, KRE27, and EMC6.
PMID:19325107, PMID:25313861, GOC:vw, GOC:krc

**Comment by ValWood** [comment]
Yes, that sounds good. There seem to a lot of new biology in 2 areas of membrane organization, organelle tethering and membrane curvature....Interesting stuff.

**Comment by krchristie** [comment]
Lovely. I don't know if I'll have time to put that in Friday since I'm getting ready to go to Bar Harbor for a week, but if not, I'll put it in next week.

-K

**Comment by krchristie** [comment]
When I went to do it, I had another thought, so I put in the def with this addition to what I suggested previously:

A transmembrane protein complex located in the ER that is involved in ER-mitochondrial membrane tethering, which is required to facilitate lipid transfer **from the ER to the mitochondrial membrane**. In S. cerevisiae, it has six members: EMC1, EMC2, AIM27, EMC4, KRE27, and EMC6.

This link shows a really good colorized diff between the original definition and what I put in:
https://github.com/geneontology/go-ontology/commit/83a4b55cd824c5c4fa3006bfbcfc51be6cde18af

**Comment by ValWood** [comment]
sounds good...
