### ISSUE TITLE
Request for new GO terms

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#13659]
Hello,
Would it be possible to create the following GO terms:
1) Regulation term (positive and negative) for GO:0045138 (nematode male tail tip morphogenesis), PMID:28068334
2) A GO term for "pharynx morphogenesis" and its associated regulatory terms (positive and negative), PMID:20805556.
Thank you
Rossana

**Comment by vanaukenk** [comment]
Hi @rozaru 
I can add these terms, but am wondering if the activities of the genes described in this paper regulate the actual morphogenetic processes or if they regulate the activities of members of the BMP signaling pathway that, in turn, regulates the morphogenetic processes?  What do you think?

**Comment by vanaukenk** [comment]
@dosumis - I was going to add the pharynx morphogenesis term as part_of pharynx development (GO:0060465).  
I noticed, however, that the logical def of pharynx development is:

'anatomical structure development'
 and ('results in development of' some 'chordate pharynx')

There are a large number of C. elegans gene products annotated to 'pharynx development', though, so would it be okay to make the logical def more general by changing 'chordate pharynx' to the parent 'pharynx' term? 

Thx.

**Comment by cmungall** [comment]
I think this is logically valid.

It is somewhat unsatisfying though. The uberon grouping 'pharynx' is not a well defined grouping. The definition comes from GO "the part of the digestive system immediately posterior to the mouth" (terminating where?)

Related:
https://github.com/obophenotype/uberon/issues/1212

This is really cool:
https://github.com/BgeeDB/anatomical-similarity-annotations/issues/18

**Comment by dosumis** [comment]
> I think this is logically valid.

Me too.  Perhaps a loose grouping is all we can manage here.  Wondering if this can be tightened up by specifying ectodermal origin?  Works for chordates (pharyngeal arches/neural crest) and arthropods (foregut is ectdoermal).  Don't know about worms though.

**Comment by vanaukenk** [comment]
Okay, I will update the logical def here to use the more general 'pharynx' term.  
In C. elegans, the pharynx contains cells of both ectodermal and mesodermal origin, though, so we can't tighten up by specifying ectodermal origin.
http://www.wormatlas.org/hermaphrodite/pharynx/mainframe.htm
