### ISSUE TITLE
change term name protein localization to actomyosin contractile ring involved in mitotic cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13654]
can this term
protein localization to actomyosin contractile ring involved in mitotic cytokinesis

be changed to

protein localization to mitotic actomyosin contractile ring 

will match other terms like:
positive regulation of mitotic actomyosin contractile ring contraction

our community curator missed this specificity even though they got it for the other terms. I suspect they thought the experiment needed to show involvement of the localization in cytokinesis...the wording is slightly misleading)

(and NTR:mitotic actomyosin contractile ring , I don't know why we don't have this, we have one for the prospore actomyosin contractile ring)

**Comment by ukemi** [comment]
Can you provide a definition and reference for the NTR?

**Comment by ValWood** [comment]
I put the new term in another ticket It turned out to be a bit more  complicated when I looked at the existing term.

**Comment by ukemi** [comment]
Thanks. I'm not sure the existing term is defined as mitotic. The gloss on the definition is just an example. I think we should leave it as the generic structure, whether meiotic or mitotic.
