### ISSUE TITLE
contractile ring revisions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13655]
actomyosin contractile ring
Ontology	Cellular Component
Definition	A cytoskeletal structure composed of actin filaments and myosin that forms beneath the plasma membrane of many cells, including animal cells and yeast cells, in a plane perpendicular to the axis of the spindle, i.e. the cell division plane. Ring contraction is associated with centripetal growth of the membrane that divides the cytoplasm of the two daughter cells. In animal cells, the contractile ring is located inside the plasma membrane at the location of the cleavage furrow. In budding fungal cells, e.g. mitotic S. cerevisiae cells, the contractile ring forms beneath the plasma membrane at the mother-bud neck before mitosis.
Secondary IDs	GO:0030480

rename to
mitotic actomyosin contractile ring
as it is defined mitotically

make 
	prospore contractile ring (the fungal mieotic ring) a sibling (currently it is a descendant

contractile ring 
can be a parent of both

A cytoskeletal structure composed of filamentous protein that forms beneath the membrane of many cells or organelles, in the plane of cell or organelle division. Ring contraction is associated with centripetal growth of the membrane that divides the cytoplasm of the two daughter cells or organelles.

but the def needs extending slightly  to cover meiotic rings  (in fungi these are quite different  from mitotic rings...I have no idea about metazoa though)

perhaps "two daughter cells in mitosis or   four cells or spores during sporulation of gamete formation.."

It still might not fit the fungal meitoic rings exactly  (i.e the perpendicular to the angle of the spindle part) but re can refine once we know more about them.

**Comment by ukemi** [comment]
Note: The last part of the current definition is just an example. It doesn't restrict the term t being mitotic. I suggest we leave this term as mitotic and create the appropriate mitotic and meiotic children. Is there a good reference/review we can use for these terms?

**Comment by ukemi** [comment]
Sorry, re-reading, I don't make sense here. We should leave this term generic. @vanaukenk I have assigned you because I am thinking about how the pseudocleavage furrow would also fit in here.

**Comment by ValWood** [comment]
meiotic
Meiotic actin rings are essential for proper sporulation in fission yeast.
https://www.ncbi.nlm.nih.gov/pubmed/22526418


This is a very cool paper (not yet curated), in vitro  assay of mitotic  contractile  ring constriction
https://www.ncbi.nlm.nih.gov/pubmed/23770677
In vitro contraction of cytokinetic ring depends on myosin II but not on actin dynamics.
more than 130 proteins!

and
Isolation of Cytokinetic Actomyosin Rings from Saccharomyces cerevisiae and Schizosaccharomyces pombe
PMID: 26519310

**Comment by vanaukenk** [comment]
@ValWood - Would something like this structure in the ontology work for you, with appropriately granular definitions for each?

GO:0070938 contractile ring
--is_a GO:0005826 actomyosin contractile ring
----is_a GO:new pseudocleavage actomyosin contractile ring
----is_a GO:new mitotic actomyosin contractile ring
------is_a GO:0000142 cellular bud neck contractile ring
----is_a GO:new meiotic actomyosin contractile ring
------is_a GO:0032157 prospore contractile ring

Also, let me know if you think there are terms in the BP branch of the ontology that may need updating.  I took a quick look and it seems that there are some mitosis-specific terms already there, e.g. regulation of mitotic actomyosin contractile ring assembly.  Perhaps the proposal above would then better align CC and BP wrt these terms?

**Comment by ValWood** [comment]
Looks good to me. I don't know what a "pseudocleavage actomyosin contractile ring" is but if it isn't  involved in mitotic or meiotic cell division one that's all good!  

I think the BP ontology already  has  correctly defined mitotic  terms (we  revised all of  our annotations to the mitotic terms because we have only annotated mitotic papers so far and we knew meiotic was going to be different). So I think all the terms already  and are correctly defined. This request was to bring CC into alignment with BP terms.
Did I answer the question? I'm not sure ;)
