### ISSUE TITLE
Remove parent 'mitochondrial organisation' from 'mitochondrial RNA processing'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13664]
Hello @ukemi (and anyone else!) 

is there a reason why 'mitochondrial organisation' is a parent of 'mitochondrial RNA processing'? Seems odd. 

Thanks, Pascale

**Comment by ValWood** [comment]
Hmm was added here
https://github.com/geneontology/go-ontology/issues/8878

but the translation and others subsequently removed!
https://github.com/geneontology/go-ontology/issues/12919
https://github.com/geneontology/go-ontology/issues/11677

I think this should be removed too.

**Comment by ukemi** [comment]
I would remove and let the reasoner do the work.
