### ISSUE TITLE
NTR: Gly-tRNA(Ala) hydrolase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#13662]
Parent: GO:0002161
Proposed definition: Catalysis of the hydrolysis of misacylated Gly-tRNA(Ala).
Reference: PMID 28362257

Thanks,
Ingrid

**Comment by hdrabkin** [comment]
The paper apperars to be talking about this:

Term: 	D-aminoacyl-tRNA deacylase activity
Definition: 	Catalysis of the reaction: D-aminoacyl-tRNA = D-amino acid + tRNA. Hydrolysis of the removal of D-amino acids from residues in charged tRNA.
Parent Terms: 	is-a aminoacyl-tRNA editing activity
Category: 	Molecular Function
ID: 	GO:0051499

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/12917

**Comment by hdrabkin** [comment]
Proposed definition: Catalysis of the hydrolysis of misacylated Gly-tRNA(Ala).
maybe 
Catalysis of the reaction: gly-tRNA(ala) + H20 = glycine + tRNA(ala)

**Comment by hdrabkin** [comment]
Thinking some more (smell the smoke):
Concerned that this may invoke a need for additional terms for every case where a non-D-amino acid is removed from a non-cognate tRNA. 
Should we instead make a term like
name:misacylated-tRNA hydrolysis
Def: Catalysis of the hydrolysis of misacylated  aminoacyl-tRNA (non-cognate).

**Comment by keseler** [comment]
I think that's pretty much what the proposed parent, GO:0002161, is.  Maybe its definition should be expanded a bit?
I was in fact wondering about a term explosion, one term for each possible misacylated tRNA; three specific terms already exist (for Ala-tRNA(Pro), Cys-tRNA(Pro) and Ser-tRNA(Ala)).  But I think those editing activities are specific enough that maybe they deserve their own term.

**Comment by hdrabkin** [comment]
Right; I see the other terms now;  since there is precedence with the other three. I'll also use your suggested def to make it consistent.
