### ISSUE TITLE
IPR034586 mitotic spindle orientation checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13663]
This checkpoint is not present in fission yeast. It is required in budding yeast because the spindle has to be orientated to get though the bud neck. I'm not sure if it is present in any medially dividing cells?

**Comment by ValWood** [comment]
wrong tracker

**Comment by ValWood** [comment]
never in Schizosaccharomyces for starters.

An "only in" might be better, but I'm not sure  which organisms have this particular checkpoint.

https://github.com/geneontology/go-annotation/issues/1569

**Comment by pgaudet** [comment]
Hi Val, 

For reference here are a couple review that confirm that these checkpoints are not known outside cerevisiae
http://www.sciencedirect.com/science/article/pii/S001448271200167X
https://celldiv.biomedcentral.com/articles/10.1186/1747-1028-5-28

I added 'only in taxon' some saccharomyceta for now. All EXP are to cerevisiae genes; we'll see if anything breaks ;) 

Thanks, Pascale
