### ISSUE TITLE
MP GO:0044744 protein targeting to nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13675]
should be a decendent of nucleocytoplasmic transport

**Comment by ukemi** [comment]
I'm not sure this is true. I think this term is meant to be out of the nucleus to the cytoplasm.

**Comment by pgaudet** [comment]
@ukemi nucleocytoplasmic transport is to or from the nucleus, so this request seems OK to me. 

Pascale

**Comment by ukemi** [comment]
OK. If that is the case, then this makes sense.

**Comment by krchristie** [comment]
I have added the relationship 
'protein targeting to nucleus' part of 'protein import into nucleus'
