### ISSUE TITLE
go.json

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13677]
Please could we have

http://purl.obolibrary.org/obo/go/go-simple.json
http://purl.obolibrary.org/obo/go/go.json

?

Seems odd that the json format is meant to make GO more accessible for scripting but we only make it for our least well advertised file: http://purl.obolibrary.org/obo/go/extensions/go-plus.json

**Comment by cmungall** [comment]
As soon as we're off svn, cc @kltm @dougli1sqrd

**Comment by pgaudet** [comment]
Looks like this can be closed @kltm ? 
http://release.geneontology.org/2018-05-20/ontology/index.html

Thanks, Pascale
