### ISSUE TITLE
NTR: 'neuron projection retraction' 

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13687]
PMID: 11585923 shows that Ephrin type-B receptor 2 induces neurite retraction by down-regulation of Ras signalling (Figure 7 + online video).

Intended annotation: 
Ephrin type-B receptor 2, IDA, 'negative regulation of neuron projection maintenance'

GO NTR1: 'regulation of neuron projection maintenance'
GO NTR2: 'positive regulation of neuron projection maintenance'
GO NTR3: 'negative regulation of neuron projection maintenance'
Parent term: GO:1990535 neuron projection maintenance
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990535#term=info

DbxRef: GOC:aruk and GOC:bc.

Thanks,
Barbara

**Comment by ukemi** [comment]
Can maintenance really be regulated?

**Comment by BarbaraCzub** [comment]
Well, I wondered that as well. But in this case should we perhaps have a term for 'neuron projection retraction'?

**Comment by BarbaraCzub** [comment]
Although the definition of 'GO:1990535 neuron projection maintenance' is:
"The organization process that preserves a neuron projection in a stable functional or structural state. A neuron projection is a prolongation or process extending from a nerve cell, e.g. an axon or dendrite."

What is shown in the paper is a disruption of the 'stable functional or structural state' of the neuron projections. And disruption is after all a 'negative regulation'.

**Comment by BarbaraCzub** [comment]
Hi @ukemi 
We discussed this during our UCL team meeting today, and decided that 'neuron projection retraction' would be the more suitable term.
Thanks,
Barbara

**Comment by hdrabkin** [comment]
For clarification:
Still as child of GO:1990535 neuron projection maintenance?
Suggested def: 
Still PMID:11585923 ?

**Comment by BarbaraCzub** [comment]
Hi @hdrabkin 
@RLovering , @dosumis and I discussed this earlier this week we concluded that this term should be a child of 'neuron projection organisation'. 

Now I'm thinking that 'GO:1990535 neuron projection maintenance' will probably also then become a child of 'neuron projection organisation'. 

Here is what I propose:

> GO:0030030 cell projection organization
Def.: A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a prolongation or process extending from a cell, e.g. a flagellum or axon.

>> GO:NTR1 neuron projection organization
_Proposed_ Def.: A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a prolongation or process extending from a neuron, e.g. an axon, or a dendrite.

>>> GO:1990535 neuron projection maintenance
Def.: The organization process that preserves a neuron projection in a stable functional or structural state. A neuron projection is a prolongation or process extending from a nerve cell, e.g. an axon or dendrite. 

>>> GO:NTR2 neuron projection retraction
_Proposed_ Def.: The organization process which results in the disassembly (either partial or complete) of constituent parts of a neuron projection. A neuron projection is a prolongation or process extending from a nerve cell, e.g. an axon or dendrite. 
_Proposed_ Synonym: neuron projection disassembly

Yes, still the same reference: PMID: 11585923.

And could you please assign the following GOC references to the new terms: 
GOC:aruk and GOC:bc

Thank you,
Barbara

**Comment by hdrabkin** [comment]
done

**Comment by BarbaraCzub** [comment]
Thank you!
