### ISSUE TITLE
Obsolete/merge terms referring to specific cargos for nuclear import/export

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13686]
@ValWood you usually spot these - do you agree that nuclear import and nuclear export should be children of nuclear transport?

**Comment by ValWood** [comment]
I think so.

1. Anything which refers to nuclear transport should be a child of this term, but

2. Most things get into  or out of the nucleus through the nuclear pore = nucleocytoplasmic transport (one of the children of nuclear transport)
 
3. Another child is 
GO:0032066 nucleolus to nucleoplasm transport 
The nucleolus is not a separate compartment as such

nucleolus
Ontology	Cellular Component
Definition	A small, dense body one or more of which are present in the nucleus of eukaryotic cells. It is rich in RNA and protein, is not bounded by a limiting membrane, and is not seen during mitosis. Its prime function is the transcription of the nucleolar DNA into 45S ribosomal-precursor RNA, the processing of this RNA into 5.8S, 18S, and 28S components of ribosomal RNA, and the association of these components with 5S RNA and proteins synthesized outside the nucleolus. This association results in the formation of ribonucleoprotein precursors; these pass into the cytoplasm and mature into the 40S and 60S subunits of the ribosome.

...and I'm not aware of a transport mechanism between the two ... This has only 3 EXP annotations
UniProtKB Q14191 WRN IDA PMID:11420665 MGI
UniProtKB Q3YBR2 TBRG1 IDA PMID:17110379 HGNC
UniProtKB Q9Y3T9 NOC2L IDA PMID:20123734 UniProt

I checked the abstracts and therese do refer to "translocation from the nucleolus tot he cytoplasm" but this is possibly another way of saying "localization" (i.e.  could be induced via a release from nucleolar chromatin.

I'm pretty sure this term should not exist.

4. So,  is there any other mechanism for nuclear import/export for moving things into or out of the nucleoplasm but not via the nuclear pore ? I am not aware of one, seems unlikely? However there  do appear to be ways to get small molecules  from organelles into the nuclear lumen via   organeller membrane contact sites. The nucleus lumen is part of the nucleus so this is a rationale for keeping the  parent term "nucleus transport" even though  there would be no sibling term at present.

5. All known export/export  of RNA  protein is via the nuclear pore, so all of these, if present should be descendants of nucleocytoplasmic transport 

v

**Comment by ValWood** [comment]
All of these children of nuclear import refer to "nucleocytoplasmic transport"

Is a	 GO:0035719	tRNA import into nucleus
Is a	 GO:0061015	snRNA import into nucleus
Is a	 GO:0051531	NFAT protein import into nucleus
Is a	 GO:1990236	proteasome core complex import into nucleus
Is a	 GO:0044376	RNA polymerase II complex import to nucleus

(i.e into the nucleus via the the nuclear pore)

**Comment by ValWood** [comment]
We block nuclear import and nuclear export for direct  annotation, it should always be possible to be more specific about the type of transport....

**Comment by pgaudet** [comment]
Hi Val, 

- I moved nuclear import and export under nucleocytoplasmic transport
- I created an issue in the annotation tracker for GO:0032066 nucleolus to nucleoplasm transport

Thanks, Pascale

**Comment by pgaudet** [comment]
Note that the terms below are already children of "nucleocytoplasmic transport"

Is a GO:0035719 tRNA import into nucleus
Is a GO:0061015 snRNA import into nucleus
Is a GO:0051531 NFAT protein import into nucleus
Is a GO:1990236 proteasome core complex import into nucleus
Is a GO:0044376 RNA polymerase II complex import to nucleus

**Comment by ValWood** [comment]
Hi Pascale,

I think you can only move
nuclear import and export under nucleocytoplasmic transport under nuclear transport.
(this  also covers small molecules which can move into the lumen). UNLESS, the "nuclear transport" is defined very specifically to exclude transport into the lumen (see point 4 above), in which case I think it is safe.

You can move any term which specifies protein/RNA under nucleocytoplasmic.

**Comment by ValWood** [comment]
I was going to mention the terms below. I think these are only valid if the mechanism is different.
For example RNA polymerase I  import involves a specific set of GPS.

Not sure that 
GO:0051531 NFAT protein import into nucleus
 is valid!

**Comment by pgaudet** [comment]
Hi Val, 

- I created an annotation ticket for the NFAT and  the nucleolus to nucleoplasm transport issues. 
- For your point 4, "Is there any other mechanism for nuclear import/export for moving things into or out of the nucleoplasm but not via the nuclear pore ? " the answer is, not according to GO. 
I suppose there is a mechanism to localize proteins to the nuclear outer and inner membranes but there are not many annotations describing this. 
There are several protein-specific nuclear import terms; I dont know which ones truly are different mechanisms. 

For eg: 
GO:0000189 	MAPK import into nucleus 	
GO:0035411 	catenin import into nucleus 	
GO:0042348 	NF-kappaB import into nucleus 	
GO:0007184 	SMAD protein import into nucleus 	
GO:0007262 	STAT protein import into nucleus 	
GO:0051531 	NFAT protein import into nucleus 	
GO:0006608 	snRNP protein import into nucleus 	
GO:0006610 	ribosomal protein import into nucleus 	
GO:0042991 	transcription factor import into nucleus 	
GO:0002147 	glucocorticoid receptor import into nucleus 	
GO:0035048 	splicing factor protein import into nucleus 

Any idea if any of these have a special mechanism? I suspect several of those represent signaling pathway readouts. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Val
sorry I don't understand why you don't think 	NFAT protein import into nucleus is valid. What is the difference between this import and the others that make it not an appropriate term. sorry for not working this out myself but if you know the answer it would save me the time.
best

Ruth

**Comment by ValWood** [comment]
> Any idea if any of these have a special mechanism? I suspect several of those represent signaling pathway readouts.

Not that I'm aware of, other than they may use different import factors (where a specific substrate can be added). Like so:
http://preview.pombase.org/gene/SPBC21H7.06c

**Comment by ValWood** [comment]
I checked EXP annotations to 2 terms
GO:0000189 MAPK import into nucleus   (signalling pathway regulated import of specific gene product, unsustainable)
GO:0006610 ribosomal protein import into nucleus (annotation of karyopherins, same mechanism as parent term, gene product specific example)

**Comment by pgaudet** [comment]
... and ? all readouts as well ?

**Comment by ValWood** [comment]
Hi Ruth,
See comments in
https://github.com/geneontology/go-annotation/issues/1573
Does that explain?
v

**Comment by pgaudet** [comment]
GOC meeting Oct 2017 Cambridge: people seem in favor of obsoleting/merging these terms
See https://docs.google.com/document/d/1wCzCkPL9ft20ZP5XnTn8IQAcxoFEduaBmzVWKN0hbU0/edit#

**Comment by pgaudet** [comment]
Dear all, 

At the Cambridge Signaling workshop we have decided to obsolete terms that mentions specific protein import into the nucleus. The reason for obsoletion is that all proteins are imported via the same mechanism, so import of individual proteins should be captured with extensions or by GO-CAM models. 

Affected terms and number of annotations are listed in the ticket 
https://github.com/geneontology/go-annotation/issues/1700

Please review your annotations and comment if there are problems moving them up to 'protein import in the nucleus'. 

**Remember** that we annotate the proteins that **_mediate_** import in the nucleus. I think I saw a few targets of the import itself. 

Thanks, Pascale

**Comment by ValWood** [comment]
@pgaudet  did you also mention merging 
NLS-bearing protein import into nucleus into parent? or did I imagine this

(was about to use it but if merging I will use the parent)
v

**Comment by pgaudet** [comment]
Hello, 

I will leave another week for annotation review and then obsolete 

'MAPK import into nucleus'
'NF-kappaB import into nucleus'
'NFAT protein import into nucleus'
'NLS-bearing protein import into nucleus'
'SMAD protein import into nucleus'
'STAT protein import into nucleus'
'catenin import into nucleus'
'glucocorticoid receptor import into nucleus'
'mRNA-binding (hnRNP) protein import into nucleus'
'ribonucleoprotein complex import into nucleus'
'snRNP protein import into nucleus'
'splicing factor protein import into nucleus'
'steroid hormone receptor import into nucleus'
'sterol regulatory element binding protein import into nucleus'
'transcription factor import into nucleus'

@hdrabkin noted that 'ribosomal protein import into nucleus' has a distinct nuclear import pathway mediated by importin 11, so we will keep this term and change the definition to describe this. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

Following up on the signaling workshop in Cambridge last October, the proposal has been made to obsolete terms that refer to specific cargos for nuclear import: 

'GO:0000189 MAPK import into nucleus'
'GO:0042348 NF-kappaB import into nucleus'
'GO:0051531NFAT protein import into nucleus'
'GO:0007184 SMAD protein import into nucleus'
'GO:0007262 STAT protein import into nucleus'
'GO:0035411 catenin import into nucleus'
'GO:0002147 glucocorticoid receptor import into nucleus'
'GO:0006609 mRNA-binding (hnRNP) protein import into nucleus'
'GO:0071167 ribonucleoprotein complex import into nucleus'
'GO:0006608 snRNP protein import into nucleus'
'GO:0035048 splicing factor protein import into nucleus'
'GO:0002146 steroid hormone receptor import into nucleus'
'GO:0035105 sterol regulatory element binding protein import into nucleus'
'GO:0042991 transcription factor import into nucleus’

The reason for obsoletion is that the same mechanism is used for all these cargos, so these are no different processes. Most annotations have already been reviewed; remining annotations can be moved to 'GO:0006606 protein import into nucleus’ or 'GO:0042306 regulation of protein import into nucleus’. 

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/13686

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on March 5, 2018. Unless objections are received by March 5, 2018 we will assume that you agree to this change.

============

On a related note, all ‘regulation’ terms of the above terms will be merged into their respectve regulation parent. Details are here: https://github.com/geneontology/go-ontology/issues/15268


Thanks, Pascale



Thanks, Pascale

**Comment by RLovering** [comment]
Hi
see my comments in ticket #15268

The following taken from my comment in ticket #15268: before these are all merged into these very unspecific parents please could we consider what will be lost with these merges.
For example, there are lots of different signaling pathways that converge on the NF-kappaB import into the nucleus (and in theory some annotations to this term, which regulate the activity of NF-kappaB, and the regulation of transcription by this TF. However there are 41 GO BP terms that include NF-kappaB in their name or description. Rather than doing this merge and leaving people to work out how to reannotate this information to check that this information isn't lost, would it be possible to review these terms, work out how to capture this information appropriately and non-redundantly, and then provide a similar set of terms for the other regulation of 'specific TF' import into nucleus.
Please could you consider if there are better options than deleting these terms. 

Note that there are no direct annotations to the GO term NF-kappaB import into the nucleus. so this is not a good example, however, please could a spreadsheet listing the direct annotations to these 'protein import to nucleus' terms so that we can consider if actually these terms could just be merged with the parent term, (protein import to nucleus'; which would reduce curator time by preventing the need to re-annotate) or whether the terms are being used when the regulation terms should have been used and therefore the proteins perhaps need to be associated with a signaling pathway.

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

Thanks for the feedback, that's a very good point. I made a revised proposal:


Regulation | Merge into |  
-- | -- | --
regulation of catenin import into nucleus' | GO:0030111 regulation of Wnt signaling pathway |  
regulation of SMAD protein import into nucleus' | ?? No regulation of SMAD protein signaling; change label ?
regulation of STAT protein import into nucleus' | GO:1904892 regulation of STAT cascade or GO:0046425 regulation of JAK-STAT cascade
regulation of transcription factor import into nucleus' | needs to be mapped manually to each pathway
regulation of NF-kappaB import into nucleus' | GO:1901222 regulation of NIK/NF-kappaB signaling
regulation of NFAT protein import into nucleus' | GO:0070884 regulation of calcineurin-NFAT signaling cascade


Positive regulation  | Merge into |  
-- | -- | --
positive regulation of catenin import into nucleus' | GO:0030177 positive regulation of Wnt signaling pathway |  
positive regulation of SMAD protein import into nucleus' | ?? No positive regulation of SMAD protein signaling; change label ?
positive regulation of STAT protein import into nucleus' | GO:1904894 positive regulation of STAT cascade or GO:0046427 positive regulation of JAK-STAT cascade ?
positive regulation of transcription factor import into nucleus' | needs to be mapped manually to each pathway
positive regulation of NF-kappaB import into nucleus' | GO:1901224 positive regulation of NIK/NF-kappaB signaling
positive regulation of NFAT protein import into nucleus' | GO:0070886 positive regulation of calcineurin-NFAT signaling cascade

Negative regulation  | Merge into |  
-- | -- | --
negative regulation of catenin import into nucleus' | GO:0030178 negative regulation of Wnt signaling pathway |  
negative regulation of NF-kappaB import into nucleus' | GO:1901223 negative regulation of NIK/NF-kappaB signaling
negative regulation of NFAT protein import into nucleus' | GO:0070885 negative regulation of calcineurin-NFAT signaling cascade
negative regulation of STAT protein import into nucleus' | GO:1904893 negative regulation of STAT cascade or GO:0046427 positive regulation of JAK-STAT cascade ?
negative regulation of SMAD protein import into nucleus' | ?? No negative regulation of SMAD protein signaling; change label ?
negative regulation of transcription factor import into nucleus' | needs to be mapped manually to each pathway

**Comment by pgaudet** [comment]
Hi @RLovering 
I made a proposal for regulation of import into nucleus in ticket #15268

I could make the x import merge into the corresponding terms (for eg: 'catenin import into nucleus' -> regulation of Wnt signaling pathway'); does that work ? 

I still need to obsolete 'transcription factor import into nucleus' and its regulation children since there is no specific pathway for this. 

Does that work ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

I think this is great, and I am sorry that I didn't help you more by looking systematically look at all options. Obviously there are a lot of annotations that will need revisions so the spreadsheet system would be very helpful again. I think this is something else to add to a signaling paper, should we ever get to the point where we have completed the signaling project.

I was wondering if this was appropriate for child terms like GO:0007253    cytoplasmic sequestering of NF-kappaB

But I think this is right

Ruth

**Comment by pgaudet** [comment]
I left out the sequestering for now - but this will also need to be addressed. 

Thanks, Pascale

**Comment by pgaudet** [comment]
'MAPK import into nucleus'
'glucocorticoid receptor import into nucleus'
'mRNA-binding (hnRNP) protein import into nucleus'
'ribonucleoprotein complex import into nucleus'
'snRNP protein import into nucleus'
'splicing factor protein import into nucleus'
'steroid hormone receptor import into nucleus'
'sterol regulatory element binding protein import into nucleus'
'transcription factor import into nucleus'

GO:0006610 ribosomal protein import into nucleus

'NF-kappaB import into nucleus' -> merged into regulation https://github.com/geneontology/go-ontology/pull/15285/commits/88142be820b7f59cf7a7af61daaca67fc2b8f69a
'NFAT protein import into nucleus' -> merged into regulation https://github.com/geneontology/go-ontology/pull/15285/commits/88142be820b7f59cf7a7af61daaca67fc2b8f69a
'SMAD protein import into nucleus' -> merged into regulation https://github.com/geneontology/go-ontology/pull/15285/commits/88142be820b7f59cf7a7af61daaca67fc2b8f69a
'STAT protein import into nucleus' -> merged into regulation https://github.com/geneontology/go-ontology/pull/15285/commits/88142be820b7f59cf7a7af61daaca67fc2b8f69a
'catenin import into nucleus' -> merged into regulation https://github.com/geneontology/go-ontology/pull/15285/commits/88142be820b7f59cf7a7af61daaca67fc2b8f69a

**Comment by pgaudet** [comment]
* obsoleted MAPK import into nucleus and children (1 EXP to Nucleoprotein TPR P12270)
* merged SMAD import into nucleus -> merge into GO_0060390 regulation (ideally annotations would be reviewed)
* obsolete 'mRNA-binding (hnRNP) protein import into nucleus' 0 EXP
* obsolete splicing factor protein import into nucleus 0 EXP
* obsolete 'steroid hormone receptor import into nucleus' 0 EXP
* obsolete 'sterol regulatory element binding protein import into nucleus' 0 EXP
* obsolete glucocorticoid receptor import into nucleus 0 EXP
