### ISSUE TITLE
NTR mannose-ethanolamine phosphate phosphodiesterase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13699]
I'm looking for a term to describe this MF
mannose-ethanolamine phosphate phosphodiesterase
def?

GPI glycan remodeling by PGAP5 regulates transport of GPI-anchored proteins from the ER to the Golgi.

We subsequently used the GPI intermediate H8 as a substrate. H8 has structure EtNP-Man-(EtNP)Man-(EtNP)Man-GlcN-(acyl)PI, which is a complete precursor just before GPI attachment (Hirose et al., 1992). When [14C]Man-labeled H8 was incubated with HF-PGAP5, it was efficiently converted into H7 lacking the side-chain EtNP on Man2 (Figure 6B),

from
Cell. 2009 Oct 16;139(2):352-65
PMID: 19837036

Cdc1 removes the ethanolamine phosphate of the first mannose of GPI anchors and thereby facilitates the integration of GPI proteins into the yeast cell wall.
PMID: 25165136 

I’m trying to annotate the human MPPE1 ortholog and S. cerevisiae CDC1  in pombe but I can't find an appropriate term in GO or an EC number for this. Maybe it has another name?

**Comment by ukemi** [comment]
@deustp01 

Let's look at this next week. I think we should work on this in the context of both GO and Reactome. It looks like there is no specific enzyme activity to describe MPPE1.

**Comment by deustp01** [comment]
What I've found out so far: MPPE1 (human - Q53F39; mouse Q80XL7) - is also known as PGAP5, and that enzyme mediates step 14, Figure 4, in the process described in the Kinoshita & Fujita review. UniProt assigns GO:0008081 phosphoric diester hydrolase activity as its molecular function (both species) by inference from sequence or structural similarity (probably, the inference is from data from the mutant hamster cell line PMID:19837036).

So far, I've looked only at the earlier steps, 1-12 or thereabout, shown in Kinoshita & Fujita Figure 2. The latter get the PGI block synthesized and transferred onto a target protein; the former is one of several steps in which the block is modified further as the modified target protein moves through the Golgin apparatus towards the cell membrane.

**Comment by ukemi** [comment]
@deustp01 @thomaspd @judyblake @vanaukenk
We should look at this on Monday when we meet. The authors who describe this enzyme give it a generic designation. Should we request the specific enzyme from EC? In the era of GO-CAM models, will it suffice to use the generic activity and then add specificity by extension?

**Comment by ukemi** [comment]
It looks like this enzyme was characterized in PMID:19837036. That paper has been annotated as GO:0008081 and manganese ion binding. I think the best thing for us to do is to add this with the name 'GPI-mannose ethanolamine phosphate phosphodiesterase activity'. The authors demonstrate its substrate specificity. 

Definition: A phosphoric diester hydrolase activity that removes the ethanolamine phosphate from mannose 2 of a GPI anchor.
