### ISSUE TITLE
NTR: neuron projection fasciculation

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13695]
PMID: 12761826 shows that Ephrin type-A receptor 4 is involved in inducing neurite fasciculation (Figure 6). 

There currently is a GO term 'GO:0007413 axonal fasciculation'; however, this study uses neurons originating from UBERON:0000395 cochlear ganglion (called here sprial ganglion/SG cells), and the authors state: "It should be noted that SG cells  are bipolar neurons and that we could not distinguish between peripheral and central processes. If both dendritic and axonal neurites were present, they appeared to respond similarly to the substrates used, as the behavior of neurites was homogeneous in each condition." 

Hence the new term request: 'neuron projection fasciculation'

Atm 'GO:0007413 axonal fasciculation' is an indirect descendant of 'GO:0031175 neuron projection development' (screenshot below). I suppose the new term would fit right in between:
> 'GO:0031175 neuron projection development' 
>> NEW GO:'neuron projection fasciculation'
>>> 'GO:0007413 axonal fasciculation'

![screen shot 2017-06-21 at 15 00 54](https://user-images.githubusercontent.com/16541096/27388421-564d558e-5693-11e7-82b0-4a42dc5c3205.png)

DbxRef: GOC:aruk and GOC:bc.

Thanks,
Barbara

**Comment by dosumis** [comment]
This term would be very useful for arthropods, where the axon/dendrite distinction is often unclear.

CC @hattrill

**Comment by hattrill** [comment]
Thanks for the pointer, David.

**Comment by hdrabkin** [comment]
Just noticed this.
Does this definition seem ok? 
The collection of neuronal projections into a bundle of rods, known as a fascicle.

**Comment by BarbaraCzub** [comment]
Hi @hdrabkin 
Based on the definition of 'GO:0007413 axonal fasciculation' (The collection of axons into a bundle of rods, known as a fascicle), I think this is fine. @hattrill do you agree?
Barbara

**Comment by hattrill** [comment]
That sounds ok, but I will defer to @dosumis on such matters!

**Comment by dosumis** [comment]
Looks good to me.

**Comment by hdrabkin** [comment]
done

**Comment by BarbaraCzub** [comment]
Thank you!
