### ISSUE TITLE
NTR: COPII-coated vesicle

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#13698]
Dear GO editors, 

we have a term to describe COPI-coated vesicles but none to describe COPII-coated vesicle that bud from the endoplasmic reticulum and which coat are well characterized from yeast PubMed=8004676 to human PubMed=17499046.

Thanks for your help,
Lionel

**Comment by pgaudet** [comment]
I wonder if I didn't create this too fast. @lbreuza , do you think that the term 'ER to Golgi transport vesicle' was appropriate? Definition is 'A vesicle that mediates transport from the endoplasmic reticulum to the Golgi complex; bears a coat formed of the COPII coat complex proteins; such vesicles found associated with endoplasmic reticulum (ER) membranes at steady state, and are involved in ER to Golgi (anterograde) vesicle transport.'

I think this should be merged with the new term you requested. 

Similarly, 'COPI-coated vesicle' should probably be merged with its child 'Golgi to ER transport vesicle'. The paper cited for this term refers to COPI and COPII vesicles (http://europepmc.org/abstract/MED/11252894). 

@mah11 I think you created these terms; can you help clarify the distinction ?

Thanks, Pascale

**Comment by pgaudet** [comment]
For clarity, I renamed the following terms: 
- inter-Golgi transport vesicle -> COPI-coated inter-Golgi transport vesicle
- Golgi to ER transport vesicle -> COPI-coated Golgi to ER transport vesicle
(Fig 2 in https://link.springer.com/article/10.1007%2Fs00709-011-0361-7 indicated that both are COPI-coated vesicles). 

Thanks, Pascale

**Comment by lbreuza** [comment]
Thanks Pascale,
just a detail: is it "COPII-associated ER to Golgi transport vesicle" or coated? For consistency I would suggest the later.
Lionel

**Comment by pgaudet** [comment]
Hi @lbreuza 
The name is indeed 'COPII-coated ER to Golgi transport vesicle'; I corrected the comment above. 

Thanks, Pascale
