### ISSUE TITLE
response to luteinizing hormone

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13693]
I would like to see "response to luteinizing hormone” and “cellular response to luteinizing hormone” added to the GO ontology under the parent terms “response to peptide hormone” (GO:0043434) and “cellular response to peptide hormone stimulus (GO:0071375), respectively.  The definitions could be “Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a luteinizing hormone stimulus.” and "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a luteinizing hormone stimulus.” An example can be found in PMID:17344471.

**Comment by ukemi** [comment]
Oops. looks like those terms already exist. I have deleted my pull request and will add the additional parents in a separate commit.
