### ISSUE TITLE
Replace TermGenie with dosdp yaml design patterns and editing in INCA Forms

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13692]
This is an umbrella ticket for releasing a fully functional TermGenie replacement covering a limited number of patterns.  (This may not be the right repo, but wasn't sure where else to put it).

- [ ] Finalise specs for TSVs.
  Draft here: (https://github.com/dosumis/dead_simple_owl_design_patterns/issues/38) @dosumis
   -  [x] This should include a description of how cycle should function in the case of manual over-ride
- [x] [DOSDP tools](https://github.com/balhoff/dosdp-tools) support for DOSDP regex and generated synonym extensions @balhoff 
- [ ] Pattern validation via Travis in place @dougli1sqrd #13547 
   - AFAIK, dosdp-tools doesn't currently use a standard JSON schema checker and does not give a complete set of parsing errors.  A more lightweight alternative that is complete for JSON schema checks but incomplete for checks of content is to use the python-based [simple_pattern_tester](https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/src/simple_pattern_tester.py) built with jsonschema + jsonpath_rw.
- [ ] Complete, validated pattern specs for: 
    - [x] BP regulation @dosumis  DONE - but validation still needed.
        - [BP_negative_regulation.yaml](https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/draft_patterns/BP_negative_regulation.yaml)
       - [BP_positive_regulation](https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/draft_patterns/BP_positive_regulation.yaml)
       - [BP_regulation.yaml](https://github.com/geneontology/go-
       ontology/blob/master/src/design_patterns/draft_patterns/BP_regulation.yaml)
    - [x] regulator/activator/inhibitor activity @dosumis DONE - but validation still needed.
- [ ] Complete TSVs for:
    - [x] regulator/activator/inhibitor activity @dosumis draft here: https://github.com/geneontology/go-ontology/blob/master/src/pattern_implementation_tsv
- [x] configure a table-edit page @DoctorBud - https://github.com/INCATools/table-editor/issues/35 https://github.com/INCATools/tetool/pull/1#event-1159133621
 - [ ] Make yaml templates
     - [x] from old TG https://github.com/INCATools/tetool/pull/1#event-1159133621
     - [ ] any new ones

**Comment by cmungall** [comment]
@DoctorBud will release tetool on npm, then I will run over this repo to test it and make the first instance of the form

**Comment by tberardini** [comment]
Any progress with this?

**Comment by dosumis** [comment]
Looks to me like all the pieces are in place but someone needs to find the time to wire them up.

**Comment by tberardini** [comment]
Would be great to get at least the straightforward (regulation!) templates out there.

**Comment by dosumis** [comment]
@cmungall do you have a plan for this? Presumably there are other examples up and running we could crib from?  I've been working on some patterns for FBbt/VFB and would like to implement table editor there too.

**Comment by pgaudet** [comment]
Duplicate of #13643
