### ISSUE TITLE
cyclase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13702]
shouldn't
GO:0009975 cyclase activity
be a descendent of lyase activity (it's currently a sibling and I can'y work out why)

**Comment by ukemi** [comment]
I think some cyclases are types of lyases, but not all.
@deustp01 , @hdrabkin

**Comment by hdrabkin** [comment]
https://en.wikipedia.org/wiki/Cyclase
Note: but not always, 

A cyclase is an enzyme, almost always a lyase, that catalyzes a chemical reaction to form a cyclic compound.

**Comment by ukemi** [comment]
Actually other way around. I don't think all cyclases are lyases, not all that all lyases are cyclases.

**Comment by deustp01** [comment]
I just went to http://enzyme.expasy.org/ and launched a search by putting the word cyclase in the "description" slot on that page. That returned hits on all 6 branches of the EC classification, though the largest number was on enzymes with a 4.-.-.- classification (lyases). So this looks like another place where the EC hierarchy may not be a good fit to GO's needs for a classification scheme? And the GO sibling relationship between lyase and cyclase is not wrong, but it loses the information that some cyclases are lyases, while others are members of other broad EC classes. This looks messy; does it break anything?

**Comment by ukemi** [comment]
I doesn't break anything. For specific activities that are both lyases and cyclases, they should have both parents.

**Comment by ValWood** [comment]
yes I see. I am analysing our "unknowns" (Process), but trying to group by MF/location etc. I had one with presumed cyclase catalytic activity and I wondered why it didn't group with lyases (I was trying to group to traditional EC high level.
For now I can't be any more specific than "cyclase", but I know it is a "lyase type cyclase" from family membership. For now, I can co-annotate to both terms and remove when I can be more specific...

**Comment by ukemi** [comment]
Or if we have the specific activity in the ontology and it is both a lyase and a cyclase, we can make it a child  of both.
