### ISSUE TITLE
NTR: regulation terms for endocardial cushion to mesenchymal transition

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13700]
Could I please have regulation and +/- regulation of GO:0090500 endocardial cushion to mesenchymal transition for annotation of PMID:21778427.

Can you please add GOC references:
GOC:rph
GOC:BHF
GOC:BHF_miRNA

Thanks,
Rachael.

**Comment by pgaudet** [comment]
Hi @rachhuntley 

Here are the new terms: 

 [Term]
+id: GO:0140049
+name: regulation of endocardial cushion to mesenchymal transition
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of endocardial cushion to mesenchymal transition." [PMID:21778427]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: regulates GO:0090500 ! endocardial cushion to mesenchymal transition
+created_by: pg
+creation_date: 2017-06-23T15:57:00Z
+
+[Term]
+id: GO:0140050
+name: negative regulation of endocardial cushion to mesenchymal transition
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of endocardial cushion to mesenchymal transition." [PMID:21778427]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: negatively_regulates GO:0090500 ! endocardial cushion to mesenchymal transition
+created_by: pg
+creation_date: 2017-06-26T09:02:27Z
+
+[Term]
+id: GO:0140051
+name: positive regulation of endocardial cushion to mesenchymal transition
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of endocardial cushion to mesenchymal transition." [PMID:21778427]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: positively_regulates GO:0090500 ! endocardial cushion to mesenchymal transition
+created_by: pg
+creation_date: 2017-06-26T09:11:03Z

Thanks, Pascale
