### ISSUE TITLE
NTR:glial cell projection extension/ensheathment terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13708]
(editted now I've had some expert advice)

From:
PMID:27131624 "Borderless regulates glial extension and axon ensheathment"

Could I have:

new term:
"glial cell projection extension involved in axon ensheathment"
Def: The extension of a glial cell process or projection to wrap around an axon.
Ref:PMID:27131624

Is_a
new term: "glial cell projection extension"
and
GO:0008366 "axon ensheathment"

For the new parent term "glial cell projection extension"
part_of GO:0021782 "glial cell development"
and
Is_a GO:0048858 "cell projection morphogenesis"

Thanks,
Helen

**Comment by hattrill** [comment]
@ukemi  can you assign this to someone.
(I had originally assigned this to David OS, but unassigned that as not sure what he was up to and got some input from another neuro expert. Think it just fell out of the list because of my messing about).

**Comment by hdrabkin** [comment]
Hi Helen
the term  'glial cell projection extension' confused me because I first thought it was a cc term (ie, an extension), which then made the process parentages look  odd.
maybe change to 
""glial cell projection elongation  involved in axon ensheathment"?
and then  
glial cell projection extension -> glial cell projection elongation
  The process of creating an elongation or projection from a glial cell?

**Comment by dosumis** [comment]
> the term 'glial cell projection extension' confused me because I first thought it was a cc term (ie, an extension), which then made the process parentages look odd

Agree that this is very confusing.  I assumed CC too.  I like Harold's suggestions.

**Comment by hattrill** [comment]
Yes, that seems a reasonable solution. Thanks.

**Comment by hdrabkin** [comment]
So sorry I didn't realize this was stil open

GO:0106091  glial cell projection elongation
GO:0106092 glial cell projection elongation involved in axon ensheathment

**Comment by hattrill** [comment]
I forgot too! Thanks!
