### ISSUE TITLE
missing parentage for exon-exon junction complex disassembly/assembly?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13718]
GO:1903259 exon-exon junction complex disassembly
GO:1903040 exon-exon junction complex assembly
are not part of

mRNA processing

exon-exon junction complex
Ontology	Cellular Component
Definition	A multi-subunit complex deposited by the spliceosome upstream of messenger RNA exon-exon junctions. The exon-exon junction complex provides a binding platform for factors involved in mRNA export and nonsense-mediated mRNA decay.

**Comment by mah11** [comment]
> GO:1903259 exon-exon junction complex disassembly
> GO:1903040 exon-exon junction complex assembly
> are not part of
> exon-exon junction complex

Of course not. No BP term should have a part_of link to CC term (in either direction).

> Could these 2 terms have mRNA processing parentage?

The part of the CC term definition that says "... binding platform for factors involved in mRNA export and nonsense-mediated mRNA decay" makes me wonder: can we be sure that proteins in the complex are always involved in processing (export isn't processing)? And even for decay, does "providing a platform for factors" count as involved in the process?

**Comment by ValWood** [comment]
I updated the original comment. I intended to paste in the def of exon-exon junction complex, but I parted it above the suggested parentage.

I still think it should be possible to place these process terms under a general parent.
https://en.wikipedia.org/wiki/Exon_junction_complex

It does seem to have a general role in the regulation of NMD....
This page says it is required for binding to the export receptor, but a definite role in export is not clear (...influences export).

**Comment by krchristie** [comment]
It's worth being aware that not all spliceosomal splicing is part of 'mRNA splicing' as the spliceosome also splices other types of intron containing RNAs including snoRNAs, e.g. SNR17A (http://www.yeastgenome.org/locus/snR17a/overview#sequence) & SNR17B in cerevisiae.

**Comment by ValWood** [comment]
Maybe I should just find an appropriate existing annotation, and make concurrent ISS statements for now rather than trying to  slim these via parentage  to the assembly term. I suggested here because I thought the  assembly was an integral part of the  process. However it seems that  I need different terms to describe what the complex is actually doing.

Can close this one!
