### ISSUE TITLE
Autophagy - Review

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#13710]
FYI @ukemi @RLovering @Pauldenny @paolaroncaglia

Following the feedback from the autophagy experts I propose:

1) To separate pre-autophagosomal structure and phagophore (just removing phagophore of the synonyms and creating a specific term). In some papers they kept the PAS before the phagophore, that's why I would keep it. PAS might be related to mammalian omegasomes. As phagophores are membranes, I'm not sure we need to create the phagophore membrane term.

GO:0000407: preautophagosomal structure
Cellular Component
Def: Punctate structures proximal to the endoplasmic reticulum which are the sites where the Atg machinery assembles upon autophagy induction.
Synonyms: 
exact 	PAS
related 	phagophore assembly site
narrow 	perivacuolar space
PMID:11675395, 11689437, PMID:11689437

GO:xxxxxxx: phagophore
Cellular Component
Def: A disk-like structure that expands, rounds up into a cup-shaped structure, and eventually closes around its cargo to become an autophagosome .
Synonyms: 
related 	isolation membrane
PMID:22664348, PMID:24201109

2) To separate "autophagosome maturation", "autophagosome fusion" and "amphisome fusion". Maturation seems to be a distinct step. Create also a term for autophagosome-endosome fusion ?

GO:0097352: autophagosome maturation
Biological Process
part_of: macroautophagy
Def: Removal of PI3P and Atg8/LC3 after the closure of the phagophore and before the fusion with the endosome/lysosome (e.g. mammals and insects) or vacuole (yeast), and that very likely destabilizes other Atg proteins and thus enables their efficient dissociation and recycling.
PMID:28077293

GO:xxxxxxx: autophagosome-lysosome fusion
Biological Process
part_of: macroautophagy
Def: The process in which autophagosomes, double-membraned vesicles containing cytoplasmic material, fuse with a vacuole (yeast) or lysosome (e.g. mammals and insects). In the case of yeast, inner membrane-bounded structures (autophagic bodies) appear in the vacuole. Fusion provides an acidic environment and digestive function to the interior of the autophagosome.
Synonyms: 
exact 	autophagosome fusion
exact 	autophagosome-vacuole fusion
PMID:28077293

GO:xxxxxxx: amphisome-lysosome fusion
Biological Process
part_of: macroautophagy
Def: The process in which amphisomes fuse with a vacuole (yeast) or lysosome (e.g. mammals and insects). In the case of yeast, inner membrane-bounded structures (autophagic bodies) appear in the vacuole. Fusion provides an acidic environment and digestive function to the interior of the amphisome.
PMID:24219988

GO:xxxxxxx: autophagosome-endosome fusion
Biological Process
part_of: macroautophagy
Def: The process in which an autophagosome fuses with an endosome to create an intermediate autophagic organelle called amphisome.
PMID:24219988

3) To create a new term for "autophagic body". This is a "passive"structure, not sure that there will be any specific proteins to be associated with.

GO:xxxxxxx: autophagic body
Cellular Component
Def:  Inner membrane-bounded structure that appears in the vacuole after the fusion of the autophagosomes with the vacuole in yeast. The autophagic body contains cytoplasmic material engulfed by the autophasome which is targeted for degradation in the vacuole.

4) Finally, I would also modify the definition of amphisomes:

GO:0044753: amphisome
Cellular Component
Def:	Intermediate organelles formed during macroautophagy through the fusion between autophagosomes and endosomes. 

Best regards,
Marc.

**Comment by ukemi** [comment]
If there are no comments on these, I will add all but 'autophagic body' by Monday of next week.

**Comment by paolaroncaglia** [comment]
@ukemi fine with me, thanks!

**Comment by ukemi** [comment]
The first commit is here: #13778

**Comment by ukemi** [comment]
The second commit is here. #13816. I added amphisome-lysosome fusion and deleted some synonyms from autophagosome maturation. The diff can be viewed in the commit.

**Comment by ukemi** [comment]
This ticket is now complete.
