### ISSUE TITLE
protein lipoylation is_a  is a protein maturation 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13719]
This enzyme participates in lipoate salvage, and is responsible for lipoylation in the presence of exogenous lipoic acid [7]. The enzyme attaches lipoic acid to the lipoyl domains of certain key enzymes involved in oxidative metabolism, including pyruvate dehydrogenase (E2 domain), 2-oxoglutarate dehydrogenase (E2 domain), the branched-chain 2-oxoacid dehydrogenases and the glycine cleavage system (H protein) [6]. **Lipoylation is essential for the function of these enzymes. The enzyme can also use octanoate instead of lipoate.**

In fact, maybe the parent "protein-cofactor linkage" should be is_a "protein maturation" ?

**Comment by ValWood** [comment]
It's difficult to find a general reference for this, but if a cofactor is a non-protein chemical compound or metallic ion that is required for a protein's biological activity to happen, then  logically protein-cofactor linkage should be  is_a protein maturation?

**Comment by ValWood** [comment]
I had a look I can't find a ref specifically, but isn't a  non-reversible modification required for full activity  maturation by definition?
@deustp01

**Comment by pgaudet** [comment]
I added the new parent hoping this one was going to be easy. However I have a few more questions:

1. There is a child term, 'peptidyl-lysine lipoylation'. As far as I can tell all lipoylation is on lysine residues; should these terms be merged ? 
2. The corresponding function seems too specific: ' GO:0102315 lipoate-protein ligase activity (lipoylation of glycine cleavage complex)': 
I don't think 'glycine cleavage complex' is the only target; I propose removing the information in the parenthesis and changing the definition to match that of EC:
**OLD:** Catalysis of the lipoylation of the glycine cleavage protein complex in two steps:
1) (R)-lipoate + ATP + H+= lipoyl-AMP + diphosphate
2) lipoyl-AMP + [glycine cleavage system lipoyl-carrier protein]-L-lysine= AMP + 2 H+ + a [glycine-cleavage complex H protein] N6-lipoyl-L-lysine

**NEW:**  Catalysis of the lipoylation of a protein in two steps:
ATP + (R)-lipoate + a [lipoyl-carrier protein]-L-lysine = a [lipoyl-carrier protein]-N6-(lipoyl)lysine + AMP + diphosphate (overall reaction)  
(1a) ATP + (R)-lipoate = lipoyl-AMP + diphosphate 
(1b) lipoyl-AMP + a [lipoyl-carrier protein]-L-lysine = a [lipoyl-carrier protein]-N6-(lipoyl)lysine + AMP 


@ValWood @deustp01 your input is more than welcome ! 

Pascale

**Comment by ValWood** [comment]
1. There is a child term, 'peptidyl-lysine lipoylation'. As far as I can tell all lipoylation is on lysine residues; should these terms be merged ?

I think so. I just checkedMOD in Canto and the only available option is:
Term name
N6-lipoyl-L-lysine
Matching synonym	N-Lipoyl- (on Lysine)
Definition
A protein modification that effectively converts an L-lysine residue to N6-lipoyl-L-lysine.


2. this is probably a specific term to annotate the role of glycine cleavage complex which is itself required for some lipoylation
see https://github.com/geneontology/go-annotation/issues/1575
It seems that glycine cleavage complex acts as some sort of participant in the process. But I agree it seems an unecessary term to me. It is diffuclt to tell as the defition looks truncated?
-No experimental annotations?

**Comment by pgaudet** [comment]
Hi
@deustp01 @hdrabkin 
Do you have any comment on the above proposal ? 

Thanks, Pascale
