### ISSUE TITLE
NTR: ‘cellular response to oxidised low-density lipoprotein particle stimulus’

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13712]
Several studies have been published, which investigate responses of cells to oxLDL (CHEBI_60151) in context of inflammation. Typically, LDL in these studies shows no effect.

E.g. PMID:27607416:
“To determine the effect of ox-LDL accumulation on NLRP3 inflammasome activation, NLRP3 mRNA levels were measured in RPE cells with LDL or ox-LDL treatment. In both hf-RPE and ARPE-19 cells, ox-LDL–treated cells exhibited a nearly 6-fold increase in NLRP3 mRNA level relative to control and LDL treated cells (Figs. 5B, 5C).”

There is currently a term in GO for: ‘GO:0071404 cellular response to low-density lipoprotein particle stimulus’ but there is no GO term: ‘cellular response to _oxidised_ low-density lipoprotein particle stimulus’.

I think this term should become a child of 'GO:0071402 cellular response to lipoprotein particle stimulus', and not ‘GO:0071404 cellular response to low-density lipoprotein particle stimulus’, because studies show that in certain contexts cells respond to oxLDL, but not LDL. This way when the annotation is propagated to the parent term, it will not suggest that response to LDL also occurs, when the cells in fact respond only to oxLDL.

> 'GO:0071402 cellular response to lipoprotein particle stimulus'
>> ‘GO:0071404 cellular response to low-density lipoprotein particle stimulus’

> 'GO:0071402 cellular response to lipoprotein particle stimulus'
>> ‘GO:NEW cellular response to oxidised low-density lipoprotein particle stimulus’

This will be in agreement with ChEBI, where LDL and oxLDL are siblings and do not have a parent-child relationship (screenshot below):

![screen shot 2017-06-23 at 16 11 42](https://user-images.githubusercontent.com/16541096/27488412-e34921b0-582e-11e7-8fbe-6249aac17358.png)

Please use GOC:aruk and GOC:bc

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Another reference re: effects of oxidised LDL: Figure 1 in PMID:20037584.

**Comment by pgaudet** [comment]
New term: 
 [Term]
+id: GO:0140052
+name: cellular response to oxidised low-density lipoprotein particle stimulus
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an oxidized lipoprotein particle stimulus." [PMID:20037584, PMID:27607416]
+is_a: GO:0071402 ! cellular response to lipoprotein particle stimulus
+created_by: pg
+creation_date: 2017-06-26T09:40:00Z
+

We need to integrate oxLDL (CHEBI_60151) for me to create the logical definition.

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 
I forgot to credit the term, what label do you want ? 
Thanks, Pascale

**Comment by BarbaraCzub** [comment]
GOC:aruk and GOC:bc please.
Thanks,
Barbara

**Comment by vanaukenk** [comment]
@pgaudet - do you want to re-assign this issue to you?  Are you still waiting for the ChEBI import?

**Comment by pgaudet** [comment]
Hi @vanaukenk 
I'll finish this, thanks for the reminder !
