### ISSUE TITLE
MP: GO:0120048	U6 snRNA (adenine-(43)-N(6))-methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13716]
Missing parent

![missing parent](https://user-images.githubusercontent.com/7359272/27516847-8ae214be-59b9-11e7-8d8d-4e79237d30bc.jpg)

should't the reasoner find these easily?

**Comment by ValWood** [comment]
ah OK I was misreading the 2nd one as  RNA, it's rRNA.

But the part that should be aligned  in the ontology is the activity rather than the substrate (these activities seem to be performed by the same enzyme)

"adenine-N(6))-methyltransferase" seems to be the critical part ontologically?

**Comment by hdrabkin** [comment]
H Val
What exactly are you proposing to be done.

**Comment by ValWood** [comment]
Don't worry,   should have closed when I realised the parent wasn't missing. It isn't critical. I'm just 'observing" that a  "adenine-N(6))-methyltransferase"  grouping classification would make more sense than molecule type (for many reasons),  but it isn't incorrect.
