### ISSUE TITLE
 protein quality control and elimination/ proteostasis 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13717]
There seem to be a lot of ways to describe this pathway in different places?

![misfolded protein](https://user-images.githubusercontent.com/7359272/27517054-eae955fe-59bc-11e7-8835-d5c631b8b524.jpg)

**Comment by ValWood** [comment]
A useful review
http://www.sciencedirect.com/science/article/pii/S0167488913002656

Maybe a high level  grouping term would be useful in the first instance.
to group:
chaperone  assisted proteasome degradation (CAP)
and 
autophagy

Something like "protein recycling" synonym "protein quality control"

Isn't always clear which processes some of the "response to unfolded protein" mean, i.e a direct response to the stress in terms of dealing with the unfolded proteins, or other things which occur   as a consequence of the presence of unfolded proteins.
IMHO we should purge many of the response to terms...

**Comment by ValWood** [comment]
I flagged this as low priority, I came across it as I was looking at something else, but it clearly needs some work.

**Comment by ValWood** [comment]
A LOT of the annotation to
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030968#term=annotation

appears not to fit the definition
The series of molecular signals generated as a consequence of the presence of unfolded proteins in the endoplasmic reticulum (ER) or other ER-related stress; results in changes in the regulation of transcription and translation. 
PMID:12042763

but appears to be describing processes which are part of the  degradation pathway itself...

**Comment by ValWood** [comment]
I think  there are numerous ontology issues to address, but it seems more like a mini project.
I'll take the ticket for now and see if I can break it down into a sensible proposal once I am annotating in this area.

Val

**Comment by ValWood** [comment]
BMC biology recent issues has a set of reviews on Protein Quality Control


https://www.biomedcentral.com/collections/pqcm/?utm_source=BMC_mailing&utm_medium=Email_Internal&utm_content=NyoAnd-BMC-BMC_Biology-Cell_Biology-Global&utm_campaign=BMCF_USG_PQCM_CFP3&sap-outbound-id=04E53DF3BAC8A8A2A82F94C827A11280010D5FFB

**Comment by ValWood** [comment]
derived from:

https://github.com/geneontology/go-ontology/issues/14384
https://github.com/geneontology/go-ontology/issues/13944
https://github.com/geneontology/go-ontology/issues/13861
https://github.com/geneontology/go-ontology/issues/13717

**Comment by vanaukenk** [comment]
@ValWood - shall we create a formal project for this?  Seems a good way to organize what needs to be done.

**Comment by ValWood** [comment]
Seems to be a plan. One for the future....

**Comment by ValWood** [comment]
This looks like an important paper:

Nature. 2018 Nov;563(7731):407-411. 
Distinct proteostasis circuits cooperate in nuclear and cytoplasmic protein quality control.
Samant RS1, Livingston CM2,3, Sontag EM4, Frydman J5,6.

Abstract
Protein misfolding is linked to a wide array of human disorders, including Alzheimer's disease, Parkinson's disease and type II diabetes1,2. Protective cellular protein quality control (PQC) mechanisms have evolved to selectively recognize misfolded proteins and limit their toxic effects3-9, thus contributing to the maintenance of the proteome (proteostasis). Here we examine how molecular chaperones and the ubiquitin-proteasome system cooperate to recognize and promote the clearance of soluble misfolded proteins. Using a panel of PQC substrates with distinct characteristics and localizations, we define distinct chaperone and ubiquitination circuitries that execute quality control in the cytoplasm and nucleus. In the cytoplasm, proteasomal degradation of misfolded proteins requires tagging with mixed lysine 48 (K48)- and lysine 11 (K11)-linked ubiquitin chains. A distinct combination of E3 ubiquitin ligases and specific chaperones is required to achieve each type of linkage-specific ubiquitination. In the nucleus, however, proteasomal degradation of misfolded proteins requires only K48-linked ubiquitin chains, and is thus independent of K11-specific ligases and chaperones. The distinct ubiquitin codes for nuclear and cytoplasmic PQC appear to be linked to the function of the ubiquilin protein Dsk2, which is specifically required to clear nuclear misfolded proteins. Our work defines the principles of cytoplasmic and nuclear PQC as distinct, involving combinatorial recognition by defined sets of cooperating chaperones and E3 ligases. A better understanding of how these organelle-specific PQC requirements implement proteome integrity has implications for our understanding of diseases linked to impaired protein clearance and proteostasis dysfunction.
PMID: 30429547

**Comment by ValWood** [comment]
see https://github.com/geneontology/go-ontology/issues/20914
for a plan.
