### ISSUE TITLE
ntr :mitochondrial gene expression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13714]
parent for 
GO:0032543	mitochondrial translation
GO:0042792 rRNA transcription from mitochondrial promoter
GO:0000963  mitochondrial RNA processing

Will help to group/slim these now no longer under organization

**Comment by pgaudet** [comment]
Hi Val, 

I am copying the definition from the 'gene expression parent; should I remove some stuff ? I dont think there are ncRNAs in th emitochondrion, for example: 

The process in which a mitochondrial gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form.

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale,

I think that's fine. There are ncRNA -tRNA and rRNA ;)

val

**Comment by pgaudet** [comment]
OK. 

Should  mitochondrial tRNA processing also be a child of mitochondrial gene expression ?

**Comment by ValWood** [comment]
yep, would mirror  parent arrangement:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0090646#term=ancchart

**Comment by pgaudet** [comment]
new term: 
 [Term]
+id: GO:0140053
+name: mitochondrial gene expression
+namespace: biological_process
+def: "The process in which a mitochondrial gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form." []
+intersection_of: GO:0010467 ! gene expression
+intersection_of: occurs_in GO:0005739 ! mitochondrion
+created_by: pg
+creation_date: 2017-06-26T10:57:45Z
+
