### ISSUE TITLE
Check for trailing (and leading) spaces in term definitions and other quoted attributes

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#13711]
Can a check be put in place to remove leading and trailing spaces in the definitions and other quoted attributes of terms.

For example, the definition of GO:0032002 in go.owl is:
`<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A protein complex that binds interleukin-28 and interleukin-29. It is composed of an alpha and a beta receptor subunit (in human IFNLR1/IL28Ralpha &amp; IL10RB) and either Interleukin-28 (IFNL2 or IFNL3) or Interleukin-29 (IFNL1). </obo:IAO_0000115>`

and in go.obo is:
`def: "A protein complex that binds interleukin-28 and interleukin-29. It is composed of an alpha and a beta receptor subunit (in human IFNLR1/IL28Ralpha & IL10RB) and either Interleukin-28 (IFNL2 or IFNL3) or Interleukin-29 (IFNL1). " [GOC:rph]`

The translation from the OWL representation to OBOGRAPH appears to have changed recently so that extraneous spaces are now stripped (which is how I spotted this issue in the first place).

**Comment by dosumis** [comment]
May be fixed by : https://github.com/geneontology/go-ontology/blob/master/src/sparql/trailing-whitespace-violation.sparql ?

**Comment by pgaudet** [comment]
@dougli1sqrd Do you know if this is fixed ? 
Can we add this to GO RULES (if it's not already there)?

**Comment by dougli1sqrd** [comment]
I'm not sure if this type of thing belongs in "Go Rules" per se. My understanding is that go rules are more for annotation rules. Also this sparql check looks like it will correctly identify trailing and leading spaces in any object. As written it's maybe a little agressive (maybe `?x` should be filtered by only Literals, and/or restricting `?c` to be classes) but I think will report those errors correctly.

**Comment by ukemi** [comment]
These kinds of checks used to be done upon saving in obo-edit.

**Comment by cmungall** [comment]
These are OBO-wide rules. I agree, let's not duplicate them in go-rules. For documentation purposes we can have an over-arching rule that is "ontology should conform to OBO style guidelines" and this would point to the robot documentation.

@dougli1sqrd is coordinating with Becky on this.

**Comment by cmungall** [comment]
Alll of the checks are encoded as sparql here:
https://github.com/rctauber/robot/tree/reporting/robot-core/src/main/resources/queries

This checks for leading or trailing ws:
https://github.com/rctauber/robot/blob/reporting/robot-core/src/main/resources/queries/annotation_whitespace.rq

**Comment by pgaudet** [comment]
Thanks @cmungall 
So this can be closed ?

**Comment by pgaudet** [comment]
@dougli1sqrd writes 

> Yeah, this is covered by https://github.com/geneontology/go-ontology/blob/master/src/sparql/trailing-whitespace-violation.sparql. This is run on the makefile rule `sparql_test` which is run during travis, and during release

So this is resolved.
