### ISSUE TITLE
Relations reference unknown terms

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#13723]
Our ontology update pipeline has been failing over the weekend because the version of go.owl that we're consuming contains these relations, which refer to terms that are not defined in the ontology (GO:0061901, GO:0061902, GO:0061903):

GO:0061901 regulates GO:0016303
GO:0061902 negatively_regulates GO:0016303
GO:0061903 positively_regulates GO:0016303

**Comment by ukemi** [comment]
GO:0016303 is 1-phosphatidylinositol-3-kinase activity. I see it in the editors' version of the ontology.

**Comment by tonysawfordebi** [comment]
Yes, and that one has been around for ages; it's the other three (presumably new) terms that don't appear to have found their way into the released go.owl.

**Comment by ukemi** [comment]
Ah. I see them in my copy as well. @cmungall

**Comment by ukemi** [comment]
By the way, I added these last Friday. HJD also sees them in the editors' copy.

**Comment by cmungall** [comment]
very unusual - what is the versionIRI?

**Comment by tonysawfordebi** [comment]
They're not in purl.obolibrary.org/obo/go/go.owl, which has this version IRI:
<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/go/releases/2017-06-20/go.owl"/>

Looks like something's gone awry with the release pipeline...?

**Comment by tonysawfordebi** [comment]
They are, however, in go-plus.owl, which has the version IRI:
<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/go/releases/2017-06-23/extensions/go-plus.owl"/>

This explains the problem that we're seeing, because our current ontology update pipeline consumes a mixture of go.owl and go-plus.owl; when we're able to make the switch to consuming everything from go-plus.json, inconsistencies like this should be a thing of the past.

**Comment by tonysawfordebi** [comment]
I have a (quite possibly incorrect) theory about what might be causing this...

I've just tried grabbing the latest version of go-plus.json and running that through my new OBOGraph parser. When I compared the output of that with the output of my current production parser, I noticed a number of terms that were in the JSON file but not in the OWL file, including the three mentioned in my original post.

In addition, there is also this one:

`{
      "id" : "http://purl.obolibrary.org/obo/GO_0140048",
      "meta" : {
        "definition" : {
          "val" : "The directed movement of manganese ions out of a cell.",
          "xrefs" : [ "PMID:25319704" ]
        },
        "basicPropertyValues" : [ {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#creation_date",
          "val" : "2017-06-23T14:25:00Z"
        }, {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasOBONamespace",
          "val" : "gene_ontology"
        }, {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#created_by",
          "val" : "pg"
        } ]
      },
}`

This has its namespace (GO aspect) set to "gene_ontology", and this is also the case in go-plus.owl:

`<oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">gene_ontology</oboInOwl:hasOBONamespace>
`
Could this be causing the process that releases go-plus.owl to go.owl to fail?

**Comment by tonysawfordebi** [comment]
I think that that was a red herring, and that something else is preventing go.owl from being updated.
If you look at http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/ you'll see that go.owl (and go.obo) haven't been updated for almost a week.

**Comment by tonysawfordebi** [comment]
I see that go.owl & go.obo have both been updated, which has eliminated the original problem that I reported, but we now have a different one...

A cycle has been introduced into the ontology:
GO:0006606 part_of GO:0044744
GO:0044744 part_of GO:0006606

`<owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0006606">
    
    <rdfs:subClassOf>
        <owl:Restriction>
            <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
            <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0044744"/>
        </owl:Restriction>
    </rdfs:subClassOf>
    
</owl:Class>


<owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0044744">
    
    <rdfs:subClassOf>
        <owl:Restriction>
            <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
            <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0006606"/>
        </owl:Restriction>
    </rdfs:subClassOf>
    
</owl:Class>
`

**Comment by pgaudet** [comment]
This would be due to this: 
https://github.com/geneontology/go-ontology/issues/13675

**Comment by ukemi** [comment]
Yup. Travis should have caught this I would think. @cmungall any idea why it didn't? We need to do one of two things. 1) Remove the import part of targeting relationship and get rid of the logical defs of all of the targeting terms. They are not correct with respect to the original intended meaning. 2) Merge the targeting terms into the localization terms as suggested in #13754. 

Since the targeting terms have been problematic in the past and it seems like they have been used inconsistently, it seems like the merge would be the best route.

**Comment by pgaudet** [comment]
@tonysawfordebi let me know if the latest fixes resolve this problem. 

Pascale

**Comment by tonysawfordebi** [comment]
Will do, @pgaudet - just need to wait until the changes have made their way through the release pipeline  into go.owl.

**Comment by cmungall** [comment]
we're about to switch off from svn for releases, cc @kltm

**Comment by cmungall** [comment]
@tonysawfordebi you can start using our snapshot PURLs

E.g
http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json.gz

You'll want to use these moving forward after we switch to monthly releases

**Comment by tonysawfordebi** [comment]
@cmungall OK, I've updated our pipeline to consume go-plus.owl and go.owl via the snapshot PURLs, and that has fixed our immediate problem. However, we also get the following files from SVN, and I haven't found the equivalent PURLs for them; can you advise?

${SVNROOT}/ontology/extensions/go-plus.obo
${SVNROOT}/ontology/extensions/gorel.obo
${SVNROOT}/experimental/upper/go-upper.obo
${SVNROOT}/quality_control/annotation_checks/taxon_checks/taxon_union_terms.obo

**Comment by cmungall** [comment]
I have a slight reluctance to add go-plus.obo as what we add here will be what we commit to moving forward, and it's not clear the mix of axioms of go-plus + obo is a useful combo. But if you need it we'll add it.

**Comment by cmungall** [comment]
Once the above PR is merged, give up to 24hrs for snapshot release to run.

**Comment by cmungall** [comment]
* http://purl.obolibrary.org/obo/go/snapshot/extensions/gorel.obo
 * http://purl.obolibrary.org/obo/go/snapshot/extensions/go-upper.obo
 * http://purl.obolibrary.org/obo/go/snapshot/imports/go-taxon-groupings.obo

**Comment by tonysawfordebi** [comment]
BTW, we only use go-plus.obo in order to extract taxon constraints.

**Comment by ukemi** [comment]
Hi @tonysawfordebi 

Is this resolved now?

**Comment by tonysawfordebi** [comment]
Sorry, @ukemi - your question completely passed me by...

I'm now consuming the OBOGraph JSON form of the ontology (and have been for a couple of weeks now), and everything is fine. I'm still using go-plus.obo for extracting taxon constraints, because go-plus.json is lacking some information compared to what's in go-plus.obo (at least, it was when I last looked).

I'll close this ticket, as the original problem is now fixed.
