### ISSUE TITLE
EC 2.7.7.63/  EC 2.7.7.63

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13721]
EC 2.8.1.8
lipoate synthase activity 
Catalysis of the reaction: protein N6-(octanoyl)lysine + 2 sulfur + 2 S-adenosyl-L-methionine = protein N6-(lipoyl)lysine + 2 L-methionine + 2 5'-deoxyadenosyl.

has parent

EC 2.7.7.63
lipoate-protein ligase activity EC 2.7.7.63
Catalysis of the formation of carbon-nitrogen bonds between lipoate (5-(1,2-dithiolan-3-yl)pentanoate) and a protein.

Is that correct?

Looks odd based on def and EC numbers, but I  can't figure out the difference.

**Comment by hdrabkin** [comment]
I am assuming Peifend suggestion in ticket  #13720  will help and ai can close this one also.

**Comment by hdrabkin** [comment]
Fixed closed
