### ISSUE TITLE
missing parent GO:0140021 mitochondrial ADP transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13731]
and
	GO:1990544	mitochondrial ATP transmembrane transport

do not have the parent "mitochondrial transport"

**Comment by ukemi** [comment]
We need to have 'occurs in'  some intracellular added to these logical defs, since that is a necessary condition of mitochondrial transport.

**Comment by pgaudet** [comment]
Hi @ukemi 

I am happy to add the axiom; however I don't understand. If you look at 'mitochondrial citrate transmembrane transport', the logical definition is constructed the same way, and it does inherit mitochondrial citrate transport. 

Perhaps the difference is that there is no class 'mitochondrial ATP transport', so the reasoner cannot finish the reasoning ? 

If you do a DL query 
transport
 and 'results in transport across' some membrane
 and ('occurs in' some intracellular)
-> there are only 29 results. So this is not a common pattern. 

Thanks, Pascale

**Comment by ukemi** [comment]
Hi @pgaudet 

The logical definition of mitochondrial transport is 'transport
 and ('occurs in' some intracellular)
 and ('results in transport to from or in' some mitochondrion)'. So any type of mitochondrial transport necessarily has to occur intracellularly. 

The logical definition of mitochondrial ADP transport is 'transport
 and ('transports or maintains localization of' some ADP)
 and ('results in transport across' some membrane)
 and ('results in transport to from or in' some mitochondrion)'. 

There is nothing in this definition that says that the ADP
 transport is necessarily intracellular. 

-D

**Comment by pgaudet** [comment]
I've added the Subclass 'mitochondrial transport' because all other sibling terms have the direct parent. I am tagging this for editors discussion (perhaps that could be at the August Protege workshop).

Thanks, Pascale

**Comment by pgaudet** [comment]
Added to the Protege agenda (Aug 2017)
