### ISSUE TITLE
MP? for angiogenesis?

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13734]
Prompted by looking into this ticket on NTR vascular anastomosis (https://github.com/geneontology/go-ontology/issues/13690), I was wondering if "**angiogenesis (GO:0001525)**"

should be considered a type of "**tube morphogenesis (GO:0035239)**"

**Comment by krchristie** [comment]
and if so, then it seems like the new term for 'blood vessel fusion' (aka vessel anastomosis) from https://github.com/geneontology/go-ontology/issues/13690 should be a type of 'tube fusion'

**Comment by krchristie** [comment]
@ukemi - I could use some input from you on this. 

It seemed odd to me that angiogenesis, a term for formation of more blood vessels from existing ones, did not have a relationship with 'tube morphogenesis'. I've looked into briefly this morning, and also found these two terms:

vasculogenesis (GO:0001570)
Def: The differentiation of endothelial cells from progenitor cells during blood vessel development, and the de novo formation of blood vessels and tubes. [PMID:8999798]

blood vessel morphogenesis (GO:0048514)
Def: The process in which the anatomical structures of blood vessels are generated and organized. The blood vessel is the vasculature carrying blood.[GOC:jid]

and the three terms are related to each other like this:

- blood vessel morphogenesis
-- part_of angiogenesis
-- part_of vasculogenesis

So, now I'm wondering if 'blood vessel morphogenesis' should be an is_a child of 'tube morphogenesis', either as well as existing is_a parents or instead of is_a 'anatomical structure development' (already an is_a parent of 'tube morphogenesis'). I've attached a picture from OBO-Edit:

![tubevsbloodvesselmorph](https://user-images.githubusercontent.com/10533218/27597804-58291bd4-5b18-11e7-849f-6d1795615ed5.jpg)

but I feel I'm in over my head in development stuff and I think it would be really good to get your input. Let's skype if that's easier.

**Comment by ukemi** [comment]
Weird. I must have left a note on the wrong ticket. I think this would all fall out correctly if UBERON made blood vessel a tube. @cmungall

**Comment by krchristie** [comment]
After discussion with @ukemi in Denver, where we noted that **angiogenesis** is part_of **blood vessel morphogenesis**, we decided to go ahead and instantiate this relationship:

**blood vessel morphogenesis** (GO:0048514) is_a **tube morphogenesis** (GO:0035239)

David has also submitted this Uberon ticket:
https://github.com/obophenotype/uberon/issues/1402
