### ISSUE TITLE
DNA strand resection involved in replication fork processing

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#13739]
In brief:

id: GO:new1
name: DNA strand resection involved in replication fork processing
def: The 5' to 3' exonucleolytic resection of DNA at the site of a stalled replication fork that contributes to replication fork processing.
is_a: GO:0006259 ! DNA metabolic process
relationship: has_part GO:0035312 ! 5'-3' exodeoxyribonuclease activity
relationship: part_of GO:0031297 ! replication fork processing

id: GO:new2
name: negative regulation of DNA strand resection involved in replication fork processing
def: [standard wording]
intersection_of: GO:0008150 ! biological_process
intersection_of: negatively_regulates GO:new1 ! DNA strand resection involved in replication fork processing

Details:

We've had a request from a community curator for a GO BP term for a role S. pombe Rad51 and Rad52 play in replication fork processing. As received, the request is:

term: fork protection from resection
def: A process that prevents extensive resection of newly replicated strands at arrested replication forks.

What appears to be going on, however, is that Rad51 and Rad52 negatively regulate resection - in either deletion mutant, extensive resection takes place, probably mediated by Exo1. I'm not sure the forks collapse, so I think the new term should be part of replication fork processing, instead of a type of replication fork protection.

There isn't a process term for strand resection involved in replication fork processing, but perhaps there should be (Figure 3 suggests that ~100 bp of ssDNA normally forms). If so, we could also add a negative regulation term to use for Rad51 and Rad52.

I'm happy to consider alternative suggestions for these annotations.

The paper is PMID:28475874, and you can see the Canto curation session at https://curation.pombase.org/pombe/curs/92141eb3ba63c234/ro/

**Comment by vanaukenk** [comment]
@mah11 - these two terms seem reasonable to me.  I will add them today.
