### ISSUE TITLE
snRNA pseudouridylate synthase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13743]
I thought I requested this one in the same ticket as the the tRNA term
PMID:28432181
Title	Dual nature of pseudouridylation in U2 snRNA: Pus1p-dependent and Pus1p-independent activities in yeasts and higher eukaryotes.
Authors	Deryusheva S, Gall JG

(I'll add snu2 as an extension)

paper also has data for fly @hattrill worm @vanaukenk  mouse @hdrabkin

**Comment by hdrabkin** [comment]
done closed
