### ISSUE TITLE
refine name and parent GO:0043328 protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13747]
This term

GO:0043328 protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

is not targeting, its sorting.
Targeting is based on sequences intrinsic to the protein (or proretins that they bind to). Its's a process involved in localizing resident proteins to the vacuole (via a post code).

This process is modification dependant. It's part of sorting/trafficking and can occur for any protein which can be ubiquitinated (most!). Its not a signal sequence  in the same way, its just a speficity conferred by a particular residue+tag.

It's an easy fix.

1. rename 
GO:0043328 protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
to
GO:0043328 protein transport to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

2. remove parent
GO:0006623 protein targeting to vacuole
add back
GO:0072666 establishment of protein localization to vacuole

(there is a similar issue for
	
 GO:0032258 CVT pathway
	
 GO:0071211 protein targeting to vacuole involved in autophagy

)

3. tidy synonyms of  GO:0006623 protein targeting to vacuole (def needs refining, maybe include *resident proteins* in the term (i.e it excludes proteins moved to vacuole for catabolism)

**Comment by ValWood** [comment]
@pgaudet 
I want to tag Marc, but I can't find him in the list or by autocomplete?
https://github.com/geneontology/go-ontology/blob/master/curator_group_contacts.tsv

Marc, do you agree? Otherwise there is no difference between "vacuolar targeting" and "vacuolar transport"? and no way to separate things localized by an actual signal sequence (or indirectly via a signal sequence dependency)

**Comment by ValWood** [comment]
The problem is bigger.


The MVB pathway is 
A vesicle-mediated transport process in which transmembrane proteins are ubiquitylated to facilitate their entry into luminal vesicles of multivesicular bodies (MVBs); upon subsequent fusion of MVBs with lysosomes or vacuoles, the cargo proteins are degraded.

GO:0043328
Name	protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
is the first time a link to 
GO:0043162 ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
appears, way down the graph.

Shouldn't the pathway itself be defined as a "ubiquitin-dependent protein catabolic  protein catabolic process"? analogous to autophagy?
The transport/trafficking is a part of the process, following recruiutment, cargo recognition, ESCRT assembly etc. etc.

**Comment by ValWood** [comment]
too difficult..until sorted. Not really sure what the terms mean

**Comment by marcfeuermann** [comment]
Hi Val,
I think you are right. The aim is the degradation of proteins through targeting them to the lysosome/vacuole (indeed like autophagy), not the transport itself.

**Comment by pgaudet** [comment]
Hi Val, 
GO:0043328
Name protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
is part of  'ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway'. Isn't this addressing your point ? 

Pascale

**Comment by pgaudet** [comment]
Changes: 

[Term]
 id: GO:0043328
-name: protein targeting to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
+name: protein transport to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
 namespace: biological_process
 def: "The process of directing proteins towards the vacuole using signals contained within the protein, occurring that contributes to protein catabolism via the multivesicular body (MVB) pathway." [GOC:jl, PMID:11511343]
 synonym: "protein targeting to vacuole during ubiquitin-dependent protein breakdown via the MVB pathway" EXACT []
@@ -277308,7 +277308,7 @@ synonym: "protein-vacuolar targeting during ubiquitin-dependent protein degradat
 synonym: "protein-vacuole targeting during ubiquitin-dependent protein catabolic process via the MVB pathway" EXACT []
 synonym: "protein-vacuole targeting during ubiquitin-dependent protein catabolism via the MVB pathway" EXACT []
 is_a: GO:0032511 ! late endosome to vacuole transport via multivesicular body sorting pathway
-intersection_of: GO:0006623 ! protein targeting to vacuole
+intersection_of: GO:0072666 ! establishment of protein localization to vacuole
 intersection_of: part_of GO:0043162 ! ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway
 
Pascale

**Comment by ValWood** [comment]
Yeah I think its OK.  It seems slightly odd as the entire process is ubiquitin dependent not just the transport (i.e also the degradation)

The def of GO:0043328 is incorrect too
The process of directing proteins towards the vacuole using signals contained within the protein, occurring that contributes to protein catabolism via the multivesicular body (MVB) pathway. 
PMID:11511343
because it doesn't depend on signals within the protein.....

**Comment by ValWood** [comment]
I'll put this in a new ticket, I see this one is done.
