### ISSUE TITLE
How is GO:0006888 ER to Golgi vesicle-mediated transport different from 'protein targeting to Golgi'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13756]
To split this issue:
https://github.com/geneontology/go-ontology/issues/10246

@ValWood do you suggest merging these two terms ? 

Thanks, Pascale

**Comment by ValWood** [comment]
This one for sure. This is  clearly trafficking not targeting. There is no signal/sorting mechanism here.  Proteins move on to the Golgi if not retained in the ER.

only 20  EXP for 17 proteins
FlyBase @hattrill 
SGD @srengel 
MGI @ukemi 
Ruth @RLovering 
might want to confirm.

Seems so to me...

**Comment by hattrill** [comment]
There are other cases when proteins might be targeted from another compartment to the Golgi.
Retrograde transport, for example. 
GO:0006888 ER to Golgi vesicle-mediated transport is important in wnt ligand biogenesis, where certain export proteins/modifications are required for this step to occur.

**Comment by pgaudet** [comment]
Hello, 

To me these are different but the definition perhaps not clear enough: 
- 'ER to Golgi vesicle-mediated transport' is vesicle-mediated transport
- 'protein targeting to Golgi' is the process of localizing proteins to the Golgi. I suggest merging this with 'GO:0034067 protein localization to Golgi apparatus', consistent with the suggestion in #13754. 

What do you think ? 

Pascale

**Comment by ValWood** [comment]
I think that is OK

also
GO:0048207	vesicle targeting, rough ER to cis-Golgi
should be
GO:0048207	vesicle transport, rough ER to cis-Golgi

(vesicles aren't 'targeted', they are 'trafficked by the secretory pathway' but we have always used the term "transport"  for this process.

**Comment by srengel** [comment]
All fine with me.

**Comment by pgaudet** [comment]
These 'establishment of localization' terms seem very confusing to the annotators. Out of 7 annotations to ' GO:0072600 establishment of protein localization to Golgi, 4 capture the protein itself being localized to the Golgi. I disputed these, we'll see if I missed something in the papers, but all the proteins are certainly the target of a Golgi localization process. 
Two other annotations are to bacterial proteins and how these affect Golgi trafficking to avoid the bacteria being sent to the lysozyme, so I think these are questionable as well. 

I will proceed with the merge since it doesn't break anything. 

Pascale

**Comment by pgaudet** [comment]
Targeting to Golgi is also confusing: see 
https://github.com/geneontology/go-annotation/issues/1587

**Comment by ValWood** [comment]
One problem is that most  curators  use this branch
to capture transport to Golgi
GO:0006888 ER to Golgi vesicle-mediated transport
Which is the main (only way I'm aware of) localizing proteins to the Golgi.

Apparently this can't have a link to  "protein localization to Golgi" because other things apart from  proteins are localized by this process.
I have always found this a bit sub-optimal as you would need to make concurrent annotations in different branches to  fully describe the same process.

**Comment by pgaudet** [comment]
I am also struggling with the parent of 'protein targeting to Golgi' , 'retrograde transport, vesicle recycling within Golgi', ie via COPI-coated vesicles. Why would 'targeting' only be in that direction? 

@ValWood I agree that GO:0006888 ER to Golgi vesicle-mediated transport
Which is the main (only way I'm aware of) localizing proteins to the Golgi, although other proteins do 'come back' via retrograde transport. 

The fact that targeting refer to retrograde seems likely to cause confusion in term usage. I am tempted to obsolete to encourage people to rehouse their annotations under either 
 GO:0006888 ER to Golgi vesicle-mediated transport 
or 
GO:0000301 retrograde transport, vesicle recycling within Golgi

These groups have annotations, your input is welcome.
FlyBase @hattrill 
UniProt @sylvainpoux
SGD @srengel 
MGI @ukemi 
Alzheimers_University_of_Toronto contact person= ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Having a quick sweep over our annotations to "protein targeting to Golgi", I can see that it has been used very inconsistently. So happy to do some rehousing under more appropriate terms.

Have you looked at how protein retention in Golgi fits into all this, because I think that that is the process by which things are "localized" rather than transitted through the golgi.

**Comment by hattrill** [comment]
Rehoused Dmel protein targeting to Golgi -of the 4 proteins, all very different - er chaperone-type, recruitment of transport complexes, and an ER to Golgi vesicle-mediated transport.

@pgaudet - came across a PAINT annotation:
http://www.pantree.org/node/annotationNode.jsp?id=PTN000310658

**Comment by pgaudet** [comment]
[ ] Merge 'GO:0000042 protein targeting to Golgi' and 'GO:0072600 establishment of protein localization to Golgi' into 
id "GO:0034067" protein localization to Golgi apparatus
