### ISSUE TITLE
Query CVT pathway - protein targeting parent incorrect

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13757]
To split this issue: https://github.com/geneontology/go-ontology/issues/10246

@ValWood 
CVT pathway
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0032258#term=ancchart
is a child of protein targeting, but this seems as though it should be just "protein transport to vacuole"

I think we should indeed make some cleaning in these terms. Most curators do not distinguish between them (even if sometimes there are some subtle differences) and orthologous proteins from different species are annotated differently which gives a lot of headaches to PAINT curators.
However, the CVT pathway is a really specific "protein transport to vacuole" pathway in yeast. The CVT pathway delivers hydrolases to the vacuole and specifically uses the machinery of autophagy. So I would keep it as a separate term (but modify the definition).
Regards,
Marc.

Hi Marc,
I agree that we should keep CVT pathway as a separate term. However I think it should be described as a type of 'protein transport', rather than 'protein targeting'
Val

Hi Val,
Okay, I totally agree. Sorry, I misunderstood the point. I think 'protein transport' and 'protein targeting' are (almost?) the same, so if we obsolete one (or merge them), the problem would be solved.

Original comment by: marcfeuermann

**Comment by ukemi** [comment]
Currently the textual definition of the CVT pathway suggests that it is a type of biosynthesis. This was done to distinguish it from the catabolic processes that occur by autophagic mechanisms. We should make the textual definition match its placement in the ontology.

**Comment by pgaudet** [comment]
Hi @ukemi 
We could add this reference: PMID:20146925 

It should probably have 
[] has_part autophagy 
[] remove parent protein targeting to vacuole
[] add parent protein localization to vacuole

I am not sure about the biosynthesis part, it seems downstream of localizing the two vacuolar proteins. 
I am happy to make the changes if you agree but since this touches on autophagy I'd rather you did it. 

Pascale

**Comment by ukemi** [comment]
We made the concious decision that it was not a type of autophagy and didn't have the part autophagy because it is not catabolic. That is a bit unclear, but much of the literature says itis an autophagy-like process. So we have it as being distinct.

**Comment by ValWood** [comment]
[ ] add parent protein localization to vacuole 
I think that should be transport to vacuole (uses vesicle-mediated system)...at least based on the annotation

[ ]  I thought that is was catabolic even if not autophagy
Unless this is the pathway for resident  vacuole proteins? perhaps it sis I know it is constitutive. 
Otherwise, If its transporting cargo to the vacuole, that is for catabolism?

Probably needs input from SGD...not  studied in pombe, we are all ISS

**Comment by pgaudet** [comment]
@srengel Do you want to comment ?

**Comment by ukemi** [comment]
I agree with protein localization to vacuole as the parent. Suggest that we tweak the def to be:

A constitutive process that occurs under nutrient-rich conditions, in which two resident vacuolar hydrolases, aminopeptidase I and alpha-mannosidase, are sequestered into vesicles; these vesicles are transported to, and then fuse with, the vacuole. This pathway is mostly observed in yeast.

**Comment by ukemi** [comment]
Are the hydrolases processed in the pathway as well?

**Comment by pgaudet** [comment]
The propeptide is cleaved in the vacuole (from http://onlinelibrary.wiley.com/doi/10.1016/j.febslet.2010.02.013/full, citing a 1992 paper (http://jcb.rupress.org/content/119/2/287)). 

Would you say that this is part of the pathway ?

**Comment by ukemi** [comment]
Considering the similarity to autophagy, I would. But in this case rather than catabolizing the protein it results in maturation, which is why we didn't make it a type of autophagy. Yeast people???

**Comment by pgaudet** [comment]
How about this as a definition: 
"Cytoplasm to vacuole targeting pathway that uses machinery common with autophagy. The CVT vesicle is formed when the receptor protein, Atg19, binds to the complees of the target protein (aminopeptidase or alpha-mannosidase homododecamers), forming the Cvt complex. Atg11 binds to Atg9 and transports the Cvt complex to the pre-autophagosome (PAS). The phagophore membrane expands around the Cvt complex (excluding bulk cytoplasm) forming the Cvt vesicle. "

Source: PMID: 20146925 (Fig3 and thereabouts). 

Fig 3 really helps understand the process. The protein is coated with the proteins responsible for making the autophagosome and delivers the proteins to the vacuole. 

The processing that takes place after sound like it's just normal enzyme processing. 

What do you think ? 

Pascale

**Comment by srengel** [comment]
trying to follow this thread and hit all the points...let me know if i missed anything...

in yeast, the CVT pathway is considered a 'biosynthetic pathway'. 
from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1430730/pdf/mol9p065.pdf
"Ape1 is synthesized as a precursor form (prApe1) in the cytosol, forms a large oligomeric complex, and is transported directly to the vacuole without transiting through the secretory pathway (1). The trans- port pathway requires the formation of a 150 nm double-mem- brane Cvt vesicle that specifically sequesters the prApe1 complex before it fuses with the vacuole. Subsequent breakdown of the single-membrane Cvt body within the vacuole lumen allows mat- uration of prApe1 through proteolytic removal of its propeptide."

in that same pdf, fig 3 distinguishes autophagy and CVT.

as far as targeting being removed as a parent, i'm not sure i fully appreciate the differences between targeting and localization.  targeting to me implies specificity, and CVT is selective whereas autophagy is not selective.  are you guys getting rid of 'protein targeting', or just moving CVT?

that's all i have for now, but i feel like i didn't answer everything...

**Comment by pgaudet** [comment]
Hi @srengel 
Thanks for the feedback. Somehow in this CVT literature they consider localization of the protein to its final destination 'biosynthesis'. I don't think this is the case elsewhere in GO, so I will leave that relation out (unless someone suggests otherwise). 

I am edition the definition to a mix of my suggestion and @ukemi 's ; let me know if it's not clear or not accurate. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Here are the changes: 
 id: GO:0032258
-name: CVT pathway
+name: protein localization by the CVT pathway
 namespace: biological_process
-def: "A constitutive biosynthetic process that occurs under nutrient-rich conditions, in which two resident vacuolar hydrolases, aminopeptidase I and alpha-mannosidase, are sequestered into vesicles; these vesicles are transported to, and then fuse with, the vacuole. This pathway is mostly observed in yeast." [PMID:12865942, PMID:15659643]
+def: "Cytoplasm to vacuole targeting pathway that uses machinery common with autophagy. The CVT vesicle is formed when the receptor protein, Atg19, binds to the complees of the target protein (aminopeptidase or alpha-mannosidase homododecamers), forming the Cvt complex. Atg11 binds to Atg9 and transports the Cvt complex to the pre-autophagosome (PAS). The phagophore membrane expands around the Cvt complex (excluding bulk cytoplasm) forming the Cvt vesicle. This pathway is mostly observed in yeast." [PMID:12865942, PMID:15659643]
 synonym: "cytoplasm to vacuole targeting" EXACT []
 synonym: "cytoplasm-to-vacuole targeting" EXACT []
-is_a: GO:0006623 ! protein targeting to vacuole
+is_a: GO:0072665 ! protein localization to vacuole
 relationship: has_part GO:0006624 ! vacuolar protein processing
 relationship: only_in_taxon NCBITaxon:147537 ! Saccharomycotina

I am closing the issue but I can re-open if these changes were not correct. 

Thanks ! 

Pascale
