### ISSUE TITLE
TVP GO:0071562 nucleus-vacuole junction assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13753]
Hi,

@pgaudet  has parent
 GO:0071562 nucleus-vacuole junction assembly
but that is not always true?

Maybe need to ask the autophagy group?

v

**Comment by pgaudet** [comment]
@ValWood 

GO:0071562 nucleus-vacuole junction assembly has been a child of 
 GO:0034727 piecemeal microautophagy of nucleus for a while. 
@marcfeuermann can you please comment - should this link be removed ? 
Thanks, Pascale

**Comment by ValWood** [comment]
If the use of the junctions is broader, as it seems to be, it should be has_part?

**Comment by marcfeuermann** [comment]
I would indeed follow Val's suggestion and make a has_part. @ukemi what do you think ?

**Comment by ukemi** [comment]
If the junction assembly is not always part of the autophagic process, but always happens when the autophagic process happens, then yes.

**Comment by ValWood** [comment]
actually, as it only appears during stationary phase? is that correct? Maybe it is confined to autophagy?
ignore.
