### ISSUE TITLE
Merge or obsolete protein targeting to plasma membrane and  protein targeting to prospore membrane

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13758]
To split the issue: https://github.com/geneontology/go-ontology/issues/10246

@ValWood  suggests:  
protein targeting to plasma membrane
should probably be merged obsoleted (unless there are bacterial exceptions in which case it needs a taxon restriction)
(there are only 31 experimental annotations).

also this one
GO:0072693 protein targeting to prospore membrane
isn’t transport via targeting, there is another open SF ticket about this (this term could be obsoleted as it has only IEA annotations, the pombe and cerevisiae annotations have already been cleaned up)

**Comment by pgaudet** [comment]
Hello, 

I will send out the obsoletion proposal. 'Targeting' in this case does not seem relevant. If there is a mutant that does not localize to the plasma/prospore membrane it can be annotated to the corresponding 'localization' terms. As far as I can find out the mechanism for localization is via the constitutive secretory pathway (GO:0045054). 

The respective parents 'establishment of localization to  plasma/prospore membrane should also go. 

OK @ValWood ? 

Thanks Pascale

**Comment by ValWood** [comment]
yep.

**Comment by pgaudet** [comment]
'Protein targeting to plasma membrane 'was created here: #8358 
to deal with "The gene product I want to annotate are involved in the palmotiylation of ras etc so they are anchored to the plasma membrane." 
but looking at the annotations this is not what is annotated. 
We could create more specific terms that describe this process; I don't think is exists. This is likely to come up during the signaling work we are starting for the Oct GOC meeting.
