### ISSUE TITLE
Rename GO:0036228 protein targeting to nuclear inner membrane -> protein *localization* to nuclear inner membrane 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13759]
Hello, 

I am working on #13754 trying to make smaller issues whenever possible. 
@ValWood writes

> For nucleocytoplasmic transport this one is a localization,
GO:0036228 protein targeting to nuclear inner membrane
because things are not "targeted" to the inner membrane. They are only targeted to the nuclear pore.

I also propose to change the definition: 
OLD: The process of targeting a protein to, and inserting it into, the nuclear inner membrane; usually uses signals contained within the protein. 
NEW:  The process of transporting or maintaining the localization of another protein into the nuclear inner membrane.

Manual annotations are only by SGD and Flybase; @srengel  @hattrill would you be OK these changes ?

**Comment by hattrill** [comment]
I am fine with this. But the new definition doesn't scan for me. Suggest something like:

"The process of transporting a protein to, or maintaining its localization in, the nuclear inner membrane."

**Comment by pgaudet** [comment]
Thanks @hattrill 
I used a slightly different definition from other terms in the neighborhood: 

 [Term]
 id: GO:0036228
-name: protein targeting to nuclear inner membrane
+name: protein localization to nuclear inner membrane
 namespace: biological_process
-def: "The process of targeting a protein to, and inserting it into, the nuclear inner membrane; usually uses signals contained within the protein." [GOC:dgf, PMID:16929305]
-synonym: "protein targeting to INM" EXACT [PMID:16929305]
-is_a: GO:0006612 ! protein targeting to membrane
-intersection_of: GO:0006605 ! protein targeting
+def: "A process in which a protein is transported to, or maintained in, a location within the nuclear inner membrane." [GOC:dgf, PMID:16929305]
+synonym: "protein targeting to INM" RELATED [PMID:16929305]
+synonym: "protein targeting to nuclear inner membrane" RELATED []
+intersection_of: GO:0008104 ! protein localization
 intersection_of: has_target_end_location GO:0005637 ! nuclear inner membrane

Thanks, Pascale

**Comment by ValWood** [comment]
I looked at the paper  used to support the original term, and this does appear to be describing  a transport process not  just any localization process.

https://www.ncbi.nlm.nih.gov/pubmed/16929305

So should it be  something like
The process of transporting a protein into the nucleus to a location on the nucleus inner membrane ?
(this really is proper targeting actually)

**Comment by srengel** [comment]
Joining late, but I think I'm fine with this.  I like Helen's proposed definition.

**Comment by pgaudet** [comment]
Hi @ValWood 
There is at least one protein annotated to this process that seems involved in localization rather than transport, NUP155, see http://europepmc.org/abstract/MED/22718353

Should I create a new term for the transport ? Unless you think NUP155 would be OK annotated to 'protein **transport** to nuclear inner membrane? (this is also a question for @hattrill since this is a fly annotation. 

Thanks, Pascale

**Comment by hattrill** [comment]
For NUP155, I would think that from the evidence in the paper it would be a localization thing (although there isn't much mechanistic data). Certainly not transport.

**Comment by pgaudet** [comment]
Right, so I am leaving this as 'localization. We can add transport if needed - if someone wants it. please create a new issue. 

Thanks ! 

Pascale
