### ISSUE TITLE
protein tyrosine phosphatase binding

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13767]
I would like to see "protein tyrosine phosphatase binding" added under "protein phosphatase binding” (GO:0019903).  Definition could be “Interacting selectively and non-covalently with a protein tyrosine phosphatase”.   PMID:12959980

**Comment by hdrabkin** [comment]
Hi Stan
Questions: are ALL protein tyrosine phosphatases similar OTHER than one of their substrates (ATP)? Does this mean that the PTP activity is essential for a protein to bind? 
I really don't like these terms at all (enzyme binding and children) because it is classifying by a protein's activity rather than a structure.

**Comment by vanaukenk** [comment]
Hi @hdrabkin

I'm not quite sure what you mean by your first question:
Are ALL protein tyrosine phosphatases similar OTHER than one of their substrates (ATP)? 

Do you mean that we should just annotate to the parent term, 'protein phosphatase binding', or not annotate to these types of terms, in general?

There are *lots* of annotations to enzyme binding or one of its children, and I'm not clear on what we would like curators to do wrt the use of these terms.

**Comment by hdrabkin** [comment]
Don't even like protein tyrosine phosphatase binding either. 
Is a protein binding because the target protein has this activity? Or is this a protein that happens to be known to have PTP. 
(First question was : yes they all might have an ATP binding site). 
Are these on your radar @pgaudet?

**Comment by slaulederkind** [comment]
This request was made on the basis of the function of the target, not a structural consideration of the target.  Alternatively, the annotation in question could be made with "enzyme binding" (IPI) and the target in the "with info" field.

**Comment by hdrabkin** [comment]
Yes, but if the activity were inhibited, would the other protein still bind. This is a major problem with the entire enzyme binding node. 
I( noticed at MGI there are a few annotations directly to enzyme binding with an ISO evidence code (so with field is not to the target. argh!)

**Comment by vanaukenk** [comment]
Okay, I've added the editors-discussion label to this so we can talk about this tomorrow on the editors call.  I think we need to be much clearer to curators about the status of 'binding' terms in the MF ontology.

**Comment by hdrabkin** [comment]
I was just about to do this myself; thanks.

**Comment by hdrabkin** [comment]
Hi @slaulederkind 
A decision was made on the most recent ontology call (6-30-17) that we would like to no longer support adding these types of terms. A suggestion was made to use ‘protein binding’ and an entry in the with field.  If the binding event leads to modulation of the activity of the PTP, then a regulation term should be used to express that directly, and the use of extensions to specify the target

**Comment by slaulederkind** [comment]
Okay, sounds good.
