### ISSUE TITLE
cell maturation - cell differentiation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13766]
Considering the definition for “cell differentiation” (GO:0030154) (…Differentiation includes the processes involved in commitment of a cell to a specific fate and its subsequent development to the mature state.), I suggest moving “cell maturation” (GO:0048469) to be a child of “cell differentiation” (GO:0030154).

**Comment by ukemi** [comment]
Hi @slaulederkind 

Cell maturation is already a child of cell differentiation via a part of relationship. Cell maturation is part of cell development and cell development is part of cell differentiation.

-D

**Comment by slaulederkind** [comment]
Oy, I was only looking at the parent terms.
