### ISSUE TITLE
NTR: regulation of protein localization to dendrite plasma membrane (and related)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13760]
Figures 2 and 3 in PMID:19188609 demonstrate regulation of insulin receptor and NMDA receptor localisation within plasma membrane, specifically the receptors become relocalised from dendrite membrane to neuron cell body membrane due to a genetic interaction between CK2, CaMKII and amyloid-beta (Figure 2). This change in localisation in prevented by insulin (Figure 3).

I wish to request the following new terms:
>protein localization to dendrite plasma membrane
>>regulation of protein localization to dendrite plasma membrane
>>positive regulation of protein localization to dendrite plasma membrane
>>negative regulation of protein localization to dendrite plasma membrane
>protein localization to neuronal cell body plasma membrane
>>regulation of protein localization to neuronal cell body plasma membrane
>>positive regulation of protein localization to neuronal cell body plasma membrane
>>negative regulation of protein localization to neuronal cell body plasma membrane

Parent terms:
GO:0032590 dendrite membrane
GO:0032809 neuronal cell body membrane
GO:0072657 protein localization to membrane
GO:1903076 regulation of protein localization to plasma membrane
Maybe _NEW TERM regulation of_ GO:0099632 protein transport within plasma membrane

Refs: GOC:aruk and GOC:bc

Thanks,
Barbara

**Comment by krchristie** [comment]
@ukemi - Do you want to keep this ticket for Barbara?

**Comment by ukemi** [comment]
@BarbaraCzub , since you opened it, you can make the call. If there are tickets you wouldn't mind doing yourself, then feel free to claim them. The downside is the timing. Although October is not that far away.

**Comment by BarbaraCzub** [comment]
I do not mind waiting till October. I'll add this ticket to the list.

**Comment by BarbaraCzub** [comment]
AI: Use annotation extension relations has_target_start/end_location instead of adding new terms.
