### ISSUE TITLE
Change parentage of  "GO:0008612 peptidyl-lysine modification to peptidyl-hypusine " 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13773]
Hi,

There are 2 known enzymes involved in protein hypusination. The only known hypusinated protein is the eukaryotic translation initiation factor 5A (eIF5A )

The term for hypusination is
GO:0008612 peptidyl-lysine modification to peptidyl-hypusine 

this term has the parent
is_a regulation of cytoplasmic translation

However, I don't think this process is regulatory - according to PMID:25029904:
"The hypusine modification in eIF5A appears to occur shortly after eIF5A synthesis with no pools of unmodified eIF5A". "Moreover, hypusine formation in eIF5A appears to be constitutive with no evidence of turnover or reversion of the protein to the unmodified state".

It looks like this term should instead have the parent:
GO:0051604 - protein maturation 
Any process leading to the attainment of the full functional capacity of a protein.

Cheers.

**Comment by hdrabkin** [comment]
@ValWood do you want to comment?

**Comment by ValWood** [comment]
Yes, I think Antonia is correct, protein maturation sounds like the  appropriate parent.
Cytoplasmic translation would be a downstream process.

Val

**Comment by ValWood** [comment]
Sorry ... my bad suggestion!

**Comment by hdrabkin** [comment]
will fix today

**Comment by hdrabkin** [comment]
done did
