### ISSUE TITLE
dendrite terms

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13785]
I would like to see "primary dendrite" and “secondary dendrite” added under "dendritic tree” (GO:0097447).  Definitions could be “The main trunk of a dendrite whose proximal end arises from the neuronal cell body.” and “Any section of a dendrite that branches off of the primary dendrite.”  Examples can be found in PMID:25431552.  I would also like to see “distal dendrite” added under “dendrite” (GO:0030425). Definition could be “That part of the dendrite that is farthest away from the neuronal cell body.”  Example can be found in PMID:20629984

**Comment by ukemi** [comment]
Hi @slaulederkind 

I'm a bit confused by what you want as is_a and what you want as part of relations in this request. Are primary and secondary dendrites types of dendrites and part of the dendritic tree? Is the distal dendrite part of the dendritic tree?

-D

**Comment by slaulederkind** [comment]
I think the "primary..." and "secondary..." are appropriately is_a "dendrite" children and part_of "dendritic tree" children.  Now that I look at the dendritic terms again, it looks like "secondary..." is interchangeble with "dendritic branch" (GO:0044307), so "dendritic branch" should probably be moved from under "neuron part" to under "dendritic tree" (GO:0097447). 
The "distal dendrite" is probably just part_of "dendrite".

**Comment by ukemi** [comment]
I will need is_a parents for everything, so should I just make them all neuron parts if I don't have a good is_a parent? Should I make secondary dendrite a synonym of dendritic branch? Isn't dendritic branch part_of a dendritic tree? So the is_a parent would stay?

**Comment by slaulederkind** [comment]
Is_a "neuron part" sounds good for all.  I think it would be better to switch "dendritic branch" to synonym, so "secondary dendrite" is more visible as a sibling term of "primary dendrite".  In my browser "dendritic branch" is_a "neuron part" and part_of "dendrite", not "dendritic tree".

**Comment by ukemi** [comment]
Looking at the definitions of dendritic tree and dendrite, it looks like they are meant to represent the same structure. 

dendritic tree (is_a neuron part): The entire complement of dendrites for a neuron, consisting of each primary dendrite and all its branches.

dendrite (is_a neuron projection): A neuron projection that has a short, tapering, often branched, morphology, receives and integrates signals from other neurons or from sensory stimuli, and conducts a nerve impulse towards the axon or the cell body. In most neurons, the impulse is conveyed from dendrites to axon via the cell body, but in some types of unipolar neuron, the impulse does not travel via the cell body.

@dosumis  can you shed any light on these terms?

**Comment by BarbaraCzub** [comment]
And also could we have 'dendritic arbor' added in as a synonym of 'GO:0097447 dendritic tree'? Relevant references could be:
https://www.ncbi.nlm.nih.gov/pubmed/18216855
https://www.ncbi.nlm.nih.gov/pubmed/10774724
https://www.ncbi.nlm.nih.gov/pubmed/2400931

**Comment by dosumis** [comment]
> Looking at the definitions of dendritic tree and dendrite, it looks like they are meant to represent the same structure.

Disagree.  I'll try to respond tomorrow.  Please ping me if I forget.

**Comment by ukemi** [comment]
Thanks @dosumis 
It's the branching bit of the dendrite definition that I find puzzling. It seems to me that dendrite should be a part of the dendritic tree?

**Comment by dosumis** [comment]
> Thanks @dosumis
> It's the branching bit of the dendrite definition that I find puzzling. It seems to me that dendrite should be a part of the dendritic tree?

Sorry. You're right.  The 'often branched' bit of the current def does make them equivalent.  I think we should have a tree/arbor term and an unbranched (segment of) projection term for 'neuron projection', axon and dendrite.  

Using dendrite as an example, I think this could work (and seems to agree with other suggestions here):

 dendritic tree
.    <-po- dendrite
.     .    <-is_a- primary dendrite
.     .    <-is_a- dendritic branch (synonym 'secondary dendrite')
.   <-po- dendritic branch point

**Comment by ukemi** [comment]
This looks perfectly reasonable to me, but I think we would then need to tweak the definition of dendrite to remove the branching. Then dendritic tree would be a neuron part and a dendrite would be a neuron projection?

**Comment by dosumis** [comment]
> This looks perfectly reasonable to me, but I think we would then need to tweak the definition of dendrite to remove the branching. Then dendritic tree would be a neuron part and a dendrite would be a neuron projection?

Yep - except that I think this needs doing for neuron projection and axon too

=> 
neuron part
.   .   neuron projection tree  (syn: neuron projection arbor)
.   .   .   dendritic tree  (syn: dendritic arbor)
.   .   .   axonal arbor

But...  I've just been discussing this with Barbara.  It feels like there's two ways we could do this:

(i) arbor/tree refers to the entire branched projection structure from the soma to the tips.
(ii) arbor/tree refers excludes the primary projection and refers only to the structures distal to the first branch point.

I feel like quite a lot of usage follows the second case, but the first might be easier to support given the diversity of neuronal morphologies.  For example, arthropod neurons are mostly pseduo-bipolar: they have a short primary neurite which splits in two.  Often one half of the split is dendritic, the other is axonal.  In this case would we have to go to the second split before calling it a tree/arbor.  Arthropods also have trees with a mix of axonal and dendritic branches.  Given this I think we should go with (i) above.  But given that usage sometimes follows (ii), this should be made very clear in the definition.

Hope this helps,
David

**Comment by ukemi** [comment]
@slaulederkind  how urgent is this request. Maybe this can be set aside as one of @BarbaraCzub 's first editing projects.

**Comment by slaulederkind** [comment]
There's no need to rush this.  Thanks.

**Comment by ukemi** [comment]
Hi @BarbaraCzub 

I have coassigned this one to us. I think it is within the scope of your work, right?

-D

**Comment by BarbaraCzub** [comment]
Hi @ukemi 
I look forward to it!
Barbara
