### ISSUE TITLE
zrt2 name

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13783]
Could you take a loo at this? I think from waht Amanda is saying, the authors of this paper did not assign
SPAP8A3.03 - zrt2?

Hi Val
I just reread the paper "Loss of Zhf and the tightly regulated zinc-uptake system SpZrt1 in Schizosaccharomyces pombe reveals the delicacy of cellular zinc balance” which named SPAP8A3.03 - zrt2 and I think there is quite an easy fix

In the first paragraph of the results they have the following sentence 
"We, therefore, named SPBC16D10.06 SpZrt1. SPCC126.09 (SpZip2) belongs to the gufA subfamily and SPAP8A3.03 (SpZip3) to the LIV-1 subfamily”

Would it therefore be possible to rename zrt2 on pombase to zip3?  This would be consistent with their published work, and would not also cause any confusion with the nomenclature S. cerevisiae.

Many thanks
Amanda

**Comment by Antonialock** [comment]
the name is confusing because  its a different family and non-orthologous to
http://www.yeastgenome.org/locus/S000004120/overview

**Comment by Antonialock** [comment]
it's in artemis but not on preview yet

**Comment by ValWood** [comment]
I ' not follwing this.

I made the name zip3 last week based on Amanda's request?

**Comment by ValWood** [comment]
its there:
http://pombase2.aska.gen.nz/gene/SPAP8A3.03

**Comment by ValWood** [comment]
wrong tracker ;)

**Comment by Antonialock** [comment]
looks like we had an update on the first :-)
