### ISSUE TITLE
GO:0009249 - protein lipoylation and GO:0009305 protein biotinylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13796]
Should the pathways involved in transfer of the lipoate
GO:0009249 - protein lipoylation

or biotin
GO:0009305 protein biotinylation

be part_of protein maturation?

**Comment by pgaudet** [comment]
Hi Val, 

I think this is a duplicate of #13719 

I had stated on it; I was looking for references describing the process. 

So: 

1. Can you close the current issue? 
2. If you can provide references that would help ! 

Thanks, Pascale

**Comment by ValWood** [comment]
yep duplicate

**Comment by ValWood** [comment]
reopened this because was only a partial duplicate.
The GO:0009249 - protein lipoylation now has "protein maturation" parent, but "biotinyation" doesn't.

I think the link could actually be from "protein-cofactor linkage" which would cover both (and possibly more that I did not come across).

**Comment by ValWood** [comment]
ACTION:
GO:0009305   protein biotinylation
add parent  
GO:0051604  protein maturation

**Comment by ValWood** [comment]
closing becasue histone also appears to be biotinylated, and this isn't maturation...
