### ISSUE TITLE
NTR: meiosis I, negative regulation of

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13798]
- [ ] NTR 1: negative regulation of  G2/MI transition of meiotic cell cycle,
standard def 
PMID:25492408

Add  GO:0033315 meiotic DNA replication checkpoint
as a descendant of - [ ] NTR 1

- [ ] As far as we know the DNA replication checkpoint in meiosis  GO:0033315 prevents the G/M transition prior to meiosis I. This should be  made clear by changing the name to
GO:0033315 meiotic G2/M1 DNA replication checkpoint
(There is only one pomBase and one mouse annotation to the existing term. I don't think the mouse one is about the DNA replication checkpoint. Its about preventing DNA replication. The DNA replication checkpoint is about  preventing the next transition if there are problems with replication- I will open an annotation tracker ticket for this).
Also revise GO:0033315 def from:
A cell cycle checkpoint that acts during a meiotic cell cycle and prevents the initiation of cell division until DNA replication is complete, thereby ensuring that progeny inherit a full complement of the haploid genome.
To:
A DNA integrity  checkpoint that acts  to inhibit the G2/M1 transition of the meiotic cell cycle and prevents the initiation of nuclear division until DNA replication is complete.

- [ ]  NTR 2 also needs parent
NTR	negative regulation of meiosis I 
standard def (see GO:0060903 positive regulation of meiosis I)
- [ ]  Note that any term which refers specifically to meiosis I or meiosis II is unambiguous and could have the exact synonym "negative regulation of meiotic nuclear division" (for example)

- [ ]  NTR	2 negative regulation of meiosis I  would be a child of
GO:0045835	negative regulation of meiotic nuclear division
for completion (this is a non specific term that you need only need to use if you don't know if it is meiosis I or meiosis II, I'm not sure if you ever would not know? perhaps one to flag for no direct annotation?)

note to self, this is to fix these annotation inconsistencies
https://github.com/pombase/curation/issues/1410

**Comment by ValWood** [comment]
+ve regulation of GO:0008315 G2/MI transition of meiotic cell cycle
-ve regulation of GO:0008315 G2/MI transition of meiotic cell cycle

PMID:25492408

**Comment by vanaukenk** [comment]
@ValWood 

Before I add the terms, can you just double-check that I have all the parentage correct?  Also, what should the relationship be between GO:0033315, meiotic G2/M1 DNA replication checkpoint, and GO:new, negative regulation of G2/M1 transition of meiotic cell cycle?

GO:0008315 G2/M1 transition of meiotic cell cycle
-GO:new regulation of G2/M1 transition of meiotic cell cycle
--GO:new negative regulation of G2/M1 transition of meiotic cell cycle
---GO:0033315 meiotic G2/M1 DNA replication checkpoint
--GO:new positive regulation of G2/M1 transition of meiotic cell cycle

GO:0060631 regulation of meiosis I
-GO:new negative regulation of meiosis I

GO:0045835 negative regulation of meiotic nuclear division
-GO:new negative regulation of meiosis I

Thx.

**Comment by ValWood** [comment]
GO:0033315, meiotic G2/M1 DNA replication checkpoint
is
part_of
GO:new, negative regulation of G2/M1 transition of meiotic cell cycle?

also
GO:0008315 G2/M1 transition of meiotic cell cycle
should  be is_a  GO:new negative regulation of meiosis I


All looks correct , go for it!

Val

**Comment by vanaukenk** [comment]
@ValWood 

Just so I'm clear on this, the 'G2/MI transition of meiotic cell cycle' (GO:0008315) is_a 'negative regulation of meiosis I' (GO:new) ?

GO:new negative regulation of meiosis I
-GO:0008315 G2/M1 transition of meiotic cell cycle 

The G2/MI transition is a negative regulation of meiosis I?

**Comment by vanaukenk** [comment]
The definition of GO:0008315 is:

The cell cycle process in which a cell progresses from meiotic G2 phase to M phase of meiosis I.

**Comment by vanaukenk** [comment]
Okay, thanks @ValWood 
Looking at #13218 helps me understand a bit better what you're getting at here.
I've made all of the other edits, but will leave this connection out for now until we figure out exactly how we want to represent it.
