### ISSUE TITLE
Add SPARQL check to ensure that no classes reference obsolete classes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13793]
To prevent this: https://github.com/geneontology/go-ontology/issues/13685#issuecomment-312710378

**Comment by pgaudet** [comment]
Hi @dougli1sqrd 

Please check if this is a duplicate of #14605 - perhaps the query is already done; the next step would be an update mechanism. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi ! So, how will error show up--- is there a report we need to look at ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Hello!
Yeah there's an error report. It'll be in `src/ontology/reports`

The name of the file will be the same as the name of the sparql query file, but with csv. For example, in src/sparql/ there is the `obsolete-reference-violation.sparql`, this will create a `obsolete-reference-violation.csv` in the report directory.

**Comment by cmungall** [comment]
most of the time this will cause a travis fail and people will just see this at the end of their travis report
