### ISSUE TITLE
Cross-ontology error for GO:0006595 polyamine metabolic process?

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#13809]
This term has CHEBI:51349 - polyamine macromolecule as its cross-ontology reference. That term's definition is "A macromolecule composed of units connected by imino (‒NR‒) linkages." However, GO:0006595 has as children metabolism of molecules like spermine, spermidine, and putrescine, which fit the imino part of the definitoon but are not macro. It looks like a better cross-ontology reference would be CHEBI:88061 - polyamine "Any organic amino compound that contains two or more amino groups."

**Comment by deustp01** [comment]
The child terms  GO:0006598 polyamine catabolic process and  GO:0006596 polyamine biosynthetic process have the same wrong cross-ontology reference as the parent.

Sorry, Harold

**Comment by hdrabkin** [comment]
done
