### ISSUE TITLE
Improve definition 'behavior'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13806]
Following up on #12357 

The definition of behavior should be improved. 

Current = The internally coordinated responses (actions or inactions) of whole living organisms (individuals or groups) to internal or external stimuli. 

Suggested = ??

**Comment by dosumis** [comment]
> This sounds very difficult, especially based on the paper cited ( Behavioural biologists don't agree on what constitutes behaviour.(PMID:20160973 PMCID:PMC2760923)

I think we'd be justified in choosing a tight definition of behavior for GO - one that is likely to group things with similar mechanisms (isn't that what we try to do in GO?) and not encompass whole other branches of GO in a species dependent manner.  To do that I think we should add clause that restricts mechanisms to those involving nervous systems.  Without this, big chunks of plant development belong under behavior + all interactions of single organisms with each other and with their environment - even when these are likely to be mechanistically very similar to interactions of cells in multicellular organisms with each other and with their environment.  
 
How about:

def: The internally coordinated responses (actions or inactions) of whole living organisms (individuals or groups) to internal or external stimuli.
>
def: The internally coordinated responses (actions or inactions) of animals (individuals or groups) to internal or external stimuli, via a mechanism that involves nervous system activity.

comment: While a broader definition of behavior encompassing plants and single cell organisms would be justified on the basis of some usage (see PMID:20160973 for discussion), GO uses a tight definition that limits behavior to animals and to responses involving the nervous system, excluding plant responses that GO classifies under development, and responses of unicellular organisms that has general classifications for covering the responses of cells in multicellular organisms (e.g. cell chemotaxis).

**Comment by pgaudet** [comment]
Hi @dosumis 
Sounds good to me, although it's not at all my area. 

I wonder, should we refer to 'neurological system', since this is how it's described in GO (AFAIK). (I always wondered why we didn't have 'nervous system process', but this may be a whole different issue). 

Thanks, Pascale

**Comment by dosumis** [comment]
> I wonder, should we refer to 'neurological system', since this is how it's described in GO

I think nervous system is fine.  People are more likely to understand it.  We could add a formal clause 
linking behavior to Uberon nervous system:

 SubClassOf 'has participant' some 'nervous system'


'neurological system process' looks like it might be broader.  Should be aligned with Uberon and ideally get some kind of logical def that improves the weirdly spotty classification under it.  But that should be another ticket.

**Comment by pgaudet** [comment]
Changes: 

id: GO:0007610
 name: behavior
 namespace: biological_process
-def: "The internally coordinated responses (actions or inactions) of whole living organisms (individuals or groups) to internal or external stimuli." [GOC:ems, GOC:jl, ISBN:0395448956, PMID:20160973]
-comment: Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.
+def: "The internally coordinated responses (actions or inactions) of animals (individuals or groups) to internal or external stimuli, via a mechanism that involves nervous system activity." [GOC:ems, GOC:jl, ISBN:0395448956, PMID:20160973]
+comment: 1. Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation reviews.\n2. While a broader definition of behavior encompassing plants and single cell organisms would be justified on the basis of some usage (see PMID:20160973 for discussion), GO uses a tight definition that limits behavior to animals and to responses involving the nervous system, excluding plant responses that GO classifies under development, and responses of unicellular organisms that has general classifications for covering the responses of cells in multicellular organisms (e.g. cell chemotaxis).
 subset: gocheck_do_not_manually_annotate
 subset: goslim_agr
 subset: goslim_plant


(other changes you see in the pull request will be because the order of the x-references somehow get changed in my version of protégé. )

**Comment by pgaudet** [comment]
What I didn't like about using 'nervous system' for the definition of behavior is that this is not defined in GO, so we don't know exactly what we are adding as a restriction.

**Comment by dosumis** [comment]
> What I didn't like about using 'nervous system' for the definition of behavior is that this is not defined in GO, so we don't know exactly what we are adding as a restriction.

It is defined in Uberon - which should be our reference for these things. If you want a formal link to the Uberon term, we could have this axiom on behavior:

SubClassOf 'has participant' some 'nervous system'

Or (stronger):

SubClassOf 'mediated_by' some 'nervous system'

I think the latter is OK, as a process can be mediated by multiple agents.

**Comment by cmungall** [comment]
+1 to all the above.

A while ago we discussed offloading behavior, e.g onto NBO, but we are 
likely to retain evolved behaviors in GO.

**Comment by pgaudet** [comment]
No further comments have been posted, so I am closing this one.

**Comment by cmungall** [comment]
It looks like no one added the relationship to nervous system?

**Comment by cmungall** [comment]
I note also we have a TC to metazoa, but a lot of dicty annotations...

**Comment by cmungall** [comment]
Also some plant annotations; all ISS (no with, tsk!), apart from one IMP to mechanosensory behavior:

http://amigo.geneontology.org/amigo/term/GO:0007610

![image](https://user-images.githubusercontent.com/50745/37191566-545346ea-2315-11e8-9c3e-e710d3a44e9a.png)

**Comment by pgaudet** [comment]
@pfey03 
Is there some other place where Dicty annotations could be rehoused ?

**Comment by pfey03** [comment]
Hi All, 
The annotations have all be cleaned up quite a while back (with David OS, got new terms). but our pipeline (QuickGO - dictyBase - GO consortium is broken for a while, and we have to wait for new database when it gets all fixed Sidd checked it but couldn't identify the problem in a reasonable time.

The only accurate and updated annotations are in QuickGO at the moment and there it's 0.
https://www.ebi.ac.uk/QuickGO/annotations?goId=GO:0007610&goUsageRelationships=is_a,part_of,occurs_in&goUsage=descendants&taxonId=44689&taxonUsage=descendants

Sorry about that and that it screws the annotations out there! I also can't wait for our update...

**Comment by pgaudet** [comment]
@cmungall 
what relation should I use ? 
'mediated by' some 'nervous system'?
