### ISSUE TITLE
Request a new term 'glutamate dehydrogenase activity'

### ISSUE THREAD

**Issue by EBI-Hsinyu** [geneontology/go-ontology#13808]
Hi, 

We have an entry (IPR033922) that matches both NAD(+)-dependent and NADP-dependent glutamate dehydrogenases. At the moment we can only give the term "GO:0016639 oxidoreductase activity, acting on the CH-NH2 group of donors, NAD or NADP as acceptor" which is not specific enough. Therefore, we think it would be nice to have a term like 'glutamate dehydrogenase activity' created to give to this entry. 

p.s.This is the ticket of the discussion between Val and I (https://github.com/geneontology/go-annotation/issues/1588#issuecomment-313089800).

Thank you. 
Hsin-Yu

**Comment by ukemi** [comment]
I think the term you want is GO:0004353 'glutamate dehydrogenase [NAD(P)+] activity'. @ValWood

**Comment by ValWood** [comment]
Hi David, so if this term encompasses both activities it should be a parent of  GO:0004352/4?
![parent](https://user-images.githubusercontent.com/7359272/27894956-5a13e794-6207-11e7-9a85-d0bfaee768d0.jpg)
