### ISSUE TITLE
document how to add new relations from RO

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13804]
I've been adding stanzas by hand like this:

[Typedef]
id: has_regulatory_component_activity
name: has regulatory component activity
namespace: external
xref: RO:0002013

And adding in some usage in the hope that this will be sufficient for a seed for import update.
( e.g. 'nucleic acid binding transcription factor activity' SubClassOf 'has necessary component activity' some 'nucleic acid binding')

But this ss not sufficient for imports to pull the hierarchy defs, axiomatization etc from RO.  In fact there's no sign of any change to ro imports (waited overnight in case this requires some nightly Jenkins process.)

Would help enormously if this could be improved/better documented.

**Comment by dosumis** [comment]
Should really have read the latest doc (sorry).  Attempting to follow new SOP here: https://github.com/geneontology/go-ontology/commit/a746b01c46829277cdd12fe17e05bfbeae7841af

**Comment by cmungall** [comment]
What the docs don't say is that the make needs to be manually executed afterwards (by someone with robot installed)

**Comment by dosumis** [comment]
> What the docs don't say is that the make needs to be manually executed afterwards (by someone with robot installed)

I actually tried that but ran into problems.

Presumably could be set to run overnight.

**Comment by cmungall** [comment]
On 5 Jul 2017, at 9:28, David Osumi-Sutherland wrote:

> Presumably could be set to run overnight.

Could be, but details would need to be worked out about branches etc.

There is some merit in having go-editors manually do this, check 
results. But we need to make it easier for people.

**Comment by ukemi** [comment]
I think this is now out of date with the new procedures and ontobot. @balhoff can you confirm?

**Comment by balhoff** [comment]
@ukemi it should be sufficient to add the term to https://github.com/geneontology/go-ontology/blob/master/src/ontology/imports/ro_terms.txt

then wait for @ontobot to run.
