### ISSUE TITLE
regulation of microfilament motor activity

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#13800]
I need terms for regulation of GO:0000146 -  PMID:20705471 describes effect of tropomyosin on various myosin motor activities using an in vitro actin filament gliding assay that doesn't indicate whether the motor activity is plus- or minus-end directed, so I can't use existing terms.

id: GO:new1
name: regulation of microfilament motor activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of microfilament motor activity." [GOC:mah, PMID:20705471]
synonym: "regulation of actin filament motor activity" EXACT [GOC:dph]
synonym: "regulation of actin-filament motor activity" EXACT []
synonym: "regulation of muscle motor activity" NARROW []
synonym: "regulation of myosin ATPase activity" RELATED []
is_a: GO:0051336 ! regulation of hydrolase activity
intersection_of: GO:0008150 ! biological_process
intersection_of: regulates GO:0000146 ! microfilament motor activity
relationship: regulates GO:0000146 ! microfilament motor activity

id: GO:new2
name: negative regulation of microfilament motor activity
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of microfilament motor activity." [GOC:mah, PMID:20705471]
(all the usual synonyms)
is_a: GO:0051346 ! negative regulation of hydrolase activity
is_a: GO:new1 ! regulation of microfilament motor activity
intersection_of: GO:0008150 ! biological_process
intersection_of: negatively_regulates GO:0000146 ! microfilament motor activity
relationship: negatively_regulates GO:0000146 ! microfilament motor activity

id: GO:new3
name: positive regulation of microfilament motor activity
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of microfilament motor activity." [GOC:mah, PMID:20705471]
(all the usual synonyms)
is_a: GO:0051345 ! positive regulation of hydrolase activity
is_a: GO:new1 ! regulation of microfilament motor activity
intersection_of: GO:0008150 ! biological_process
intersection_of: positively_regulates GO:0000146 ! microfilament motor activity
relationship: positively_regulates GO:0000146 ! microfilament motor activity

**Comment by krchristie** [comment]
Thanks for the very complete info in these NTR's. Very easy to add :) You can see the new terms with IDs in the link for '3 new terms.' above.

**Comment by mah11** [comment]
> Thanks for the very complete info in these NTR's. Very easy to add

I haven't forgotten the view from the other side of these tickets ;)

Thanks for the terms!
m
