### ISSUE TITLE
Need SOP for avoiding ID clashes when 1 editor has multiple branches awaiting merge

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13812]
Branches that are expected to be long require their own ID range.  But what should we do in the case of branches with new terms that stick around for a couple of days awaiting review?  In these  cases, starting a new branch and adding new terms will => ID clashes.  Easiest way to avoid this is to check the highest new ID in the old branch and set ID counter to start from this ID + 1.

**Comment by ukemi** [comment]
If you are using your ID range, doesn't asking Protege to remember identifiers between sessions circumvent this?

**Comment by krchristie** [comment]
I also thought Protege remembers this. I encountered something that looked odd a few weeks ago and ended up remaking a term several terms without committing any except the last time. Protege gave it a new & different ID every time even though the earlier terms were never committed.

**Comment by dosumis** [comment]
I had an ID clash from twin branches quite recently.  But now I see that I don't have the 'remember ID between sessions' option clicked.  Wonder if this works when switching ID setup (something I also do quite a bit, e.g. if editing CL or RO)?

**Comment by cmungall** [comment]
Either way we probably need better checks in place to detect collisions 
before merging into master; in theory the obo format checks should stop 
this (e.g. >1 label for an ID) but better to be robust with a sparql.

**Comment by ukemi** [comment]
And if we have a collision, what do we do, hand-edit the file. It seems better if we try very hard to catch this upstream. If I recall correctly, it remembers even when you switch ID setup, but I think I tried that ages ago on a much earlier version. You should try testing that again.

**Comment by pgaudet** [comment]
@balhoff Can a check be added for this ?

**Comment by balhoff** [comment]
I have a proposal for managing this in https://github.com/ontodev/robot/issues/763

**Comment by dosumis** [comment]
I'm pretty sure that the 'remember ID' option is sufficient to avoid clashes of this type - as long as you do all your edits on one machine.

**Comment by pgaudet** [comment]
I dont think this is a problem anymore
