### ISSUE TITLE
+/-ve reg GO:0008315 G2/MI transition of meiotic cell cycle

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13822]
Hi, I'd like to request 
+ve regulation of GO:0008315 G2/MI transition of meiotic cell cycle
-ve regulation of GO:0008315 G2/MI transition of meiotic cell cycle

PMID:25492408
Thanks.

**Comment by ValWood** [comment]
Hi Antonia,

See https://github.com/geneontology/go-ontology/issues/13798
I did for one of mine.

Val

**Comment by ValWood** [comment]
closed duplicate

**Comment by ValWood** [comment]
It's even the same paper :) Maybe we have 2 tickets on our tracker for this?
