### ISSUE TITLE
NTR: deglycation terms

### ISSUE THREAD

**Issue by ccasalsc** [geneontology/go-ontology#13827]
I need to create some new terms to annotate the role of DJ-1/PARK7 in guanine deglycation in addition to its role in protein deglycation ( #12550) , as described in PMID:28596309. Note that terms for glycation are not needed because this is a spontaneous process.
Following the example of Rebecca Foulger ( #12550), I suggest the following terms:

guanine deglycation
The removal of a sugar or dicarbonyl from a glycated guanine.

guanine deglycation, methylglyoxal removal
The removal of methylglyoxal from a glycated guanine, to form lactate and a deglycated guanine.
exact synonym: protein deglycation of methylglyoxal-glycated protein [PMID: 28596309]

guanine deglycation, glyoxal removal
The removal of glyoxal from a glycated guanine, to form glycolate and a deglycated guanine.
exact synonym: guanine deglycation of glyoxal-glycated protein [PMID: 28596309]

Thank you 

Cristina

**Comment by hdrabkin** [comment]
I thought protein deglycation of methylglyoxal-glycated protein is the way glycated protein products were dealt with? So not exact synonym to guanine deglycation, methyglyoxal removal?
Apparently, proteins might get deglycated differently:
http://www.sciencedirect.com/science/article/pii/S0003986103004247

Two types of enzymes, fructosyl lysine oxidase and fructose lysine 3-phosphokinase, catalyze the deglycation reaction and generate free amine groups.

**Comment by hdrabkin** [comment]
a guanine deglycosylaton is NOT a protein deglycosylation
Neither is guanine deglycation, a glyoxal removal guanine deglycation of glyoxal-glycated protein

The same enzyme might have both activities (protein deglyocosylation and guanine glycosylation) but the two activies are separate yes? 
"guanine deglycation of glyoxal-glycated protein" ? confused here.

**Comment by hdrabkin** [comment]
So seems we need a parent term for protein degylcation and guanine deglycation

**Comment by hdrabkin** [comment]
I think here the use of "glyoxal-glycated..." is not important to the process: it, how the guanine got glycated is not the issue, its the removal of the glycation once there correct?
(otherwise, for proteins, for example, we'd need terms to specifiy the  glycation by glucose in the terms for the glycation being removed?

**Comment by ccasalsc** [comment]
Sorry... I did a copy paste to do a parallel definition to protein deglycation and I forgot to delete the 'exact synonims' to the text... I agree it doesn't make any sense and "glyoxal-glycated..." is not important.
NO, guanine deglycation in NOT a protein deglycation, this is the reason why I'm asking for new GO terms. And, yes, I agree with you that we would need a parent term. 

guanine deglycation
The removal of a sugar or dicarbonyl from a glycated guanine.

guanine deglycation, methylglyoxal removal
The removal of methylglyoxal from a glycated guanine, to form lactate and a deglycated guanine.

guanine deglycation, glyoxal removal
The removal of glyoxal from a glycated guanine, to form glycolate and a deglycated guanine.

Honestly, I am not an expert in biochesmitry, but as I understood the article I am curating, PARK7 is using the same mechanism to deglycate guanine it is doing it from arginine and Lysines in proteins:
Maillard deglycase which deglycates Maillard adducts formed between amino groups of proteins and nucleotides (arginine, lysine and guanine) and reactive carbonyl groups of glyoxal and methylglyoxal. 
[PMID: 28596309]
So te definitions above should be correct.

We are planning to ask for a common EC number for proteins and nucleic acids deglycase, so maybe it would be good to create a common GO term too...

**Comment by hdrabkin** [comment]
Hm, for some reason I did not get alert that you had commented on this ticket.
 Yes, and if an enzyme does both, we normally then make two annotations, which is fine because the enzyme is not doing both at the same time.
Based on how protein deglycation is structured, your terms best fit under nucleic acid metabolic process;
nucleic acid metabolic process GO:0090304
.. Guanine deglycation NTR1, 
.......guanine deglycation, methylglyoxal removal NTR2
.......guanine deglycation, glyoxal removal NTR3
I will proceed

**Comment by hdrabkin** [comment]
done; closed
