### ISSUE TITLE
NTR protein maturation by iron-sulfur cluster transfer

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13839]
Hi,
I would like to request two new terms, children of 
GO:0097428 protein maturation by iron-sulfur cluster transfer

1. protein maturation by [2Fe-2S] cluster transfer
2. protein maturation by [4Fe-4S] cluster transfer
The transfer of an assembled [XFe-XS] cluster from a scaffold protein to an acceptor protein that contributes to the attainment of the full functional capacity of a protein. 

PMID:23615440

**Comment by hdrabkin** [comment]
@pgaudet , just wondering why is a translation tag this?

**Comment by pgaudet** [comment]
I was trying to assign tags to everything, without creating too many. In this case I thought either translation or metabolism. You can remove it.

**Comment by hdrabkin** [comment]
done
