### ISSUE TITLE
minor ER term issues

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13848]
Hey @ukemi

In https://github.com/geneontology/go-ontology/issues/13781, I added the term Stan requested, 'smooth endoplasmic reticulum cisterna', and the parallel term he also suggested 'rough endoplasmic reticulum cisterna'.

Question 1: In the course of figuring out an appropriate is_a parent, I noticed that we have a term for 'smooth endoplasmic reticulum part (GO:0097425)', but not a parallel term for rough endoplasmic reticulum part. Thus, for the new term for 'rough endoplasmic reticulum cisterna', I have currently given it the is_a parent of 'endoplasmic reticulum part', as you can see here: d9abcdf. Do you think it's worth having a term for 'rough endoplasmic reticulum part'?

Question 2: I also noticed that the term 'smooth endoplasmic reticulum part (GO:0097425) has two terms under it: 'hypolemmal cisterna' and 'subrhabdomeral cisterna'. It seems like that these should be moved under the new term 'smooth endoplasmic reticulum cisterna' as each is a more specific type of smooth ER cisterna. Any objections to moving these two terms under this new parent term?

**Comment by ukemi** [comment]
Question 1: If you can find a suitable is_a parent and there are no other terms that would be grouped under a new 'part' term, I would not make one. 

Question 2: If they are more correctly placed as children of the new term, then they should be moved.

**Comment by krchristie** [comment]
Q1 - I'll just leave the term where it is since I don't want to investigate if there should be anything else under a term for 'rough ER part'

Q2 - I think it's best to move these.
