### ISSUE TITLE
NTR:apicomedial cortex & assembly of apicomedial cortex actomyosin

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13857]
Could I have:

apicomedial cortex
DEF: The region that lies just beneath the plasma membrane in the middle of the apical edge of a cell. 
Ref:PMID:23831726 & PMID:28263180
synonym: medioapical cortex

part_of GO:0045179 apical cortex

AND

assembly of apicomedial cortex actomyosin
DEF: A process which results in the assembly or arrangement of constituent parts apicomedial cortex actomyosin.
Ref: PMID:28263180

Is_a GO:0030866 cortical actin cytoskeleton organization 
Is_a GO:0031032 actomyosin structure organization

Thanks

**Comment by hdrabkin** [comment]
done

**Comment by hattrill** [comment]
Thanks!
