### ISSUE TITLE
Definition revision GO:0043328 protein transport to vacuole involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13867]
The def of GO:0043328 is incorrect 

The process of directing proteins towards the vacuole using signals contained within the protein, occurring that contributes to protein catabolism via the multivesicular body (MVB) pathway.
PMID:11511343

because it doesn't depend on signals within the protein.....

**Comment by pgaudet** [comment]
Hi Val, 

Updated the definition: 
OLD def: "The process of directing proteins towards the vacuole using signals contained within the protein, occurring that contributes to protein catabolism via the multivesicular body (MVB) pathway." [GOC:jl, PMID:11511343]
NEW def: "The process of directing proteins towards the vacuole that contributes to protein catabolism via the multivesicular body (MVB) pathway." [GOC:jl, PMID:11511343]
