### ISSUE TITLE
GO:0072344 - rescue of stalled ribosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13861]
A process of translational elongation that takes place when a ribosome has stalled during translation, and results in freeing the ribosome from the stalled translation complex.

Could we have a "cytoplasmic" version of this term so that it can have a "cytoplasmic translation" parent for slimming, enrichment etc.

One of the existing refs PMID:20185543 can be used
and the ubiquitin mediated system described here:
PubMed:28065601, PubMed:28132843

Add synonym 
ribosome quality control (RQC)

(I don't actually know if there is a similar system for organellar translation, probably not in which case maybe the existing term can be renamed?)

**Comment by hdrabkin** [comment]
I am looking at 
 Joazeiro CAP. Ribosomal Stalling During Translation: Providing Substrates for 
Ribosome-Associated Protein Quality Control. Annu Rev Cell Dev Biol. 2017 Jul 17.
doi: 10.1146/annurev-cellbio-111315-125249. [Epub ahead of print] PubMed PMID:
28715909.

**Comment by hdrabkin** [comment]
Just noticed: Although translation is required for this process (because you need detection of a stalled ribosome), it's not a type of translation. The "stall" is treated as an aberrant situation. So I'm not thrilled that this appears to be a subtype of translation elongation. Best as a regulation of translation (ie, promotes recycling of translational componenets.

**Comment by hdrabkin** [comment]
Have found at least two papers on mitochondrial stituations:
Ribosome rescue and translation termination at non-standard stop codons by ICT1 in mammalian mitochondria.  PMID: 25233460
Overcoming stalled translation in human mitochondria. PMID:25101074
So might need to add a term for this also.

**Comment by ValWood** [comment]
Yes I was wondering if it was downstream of translation.
@vanaukenk  It seems to be a good candidate for my "protein quality control" term proposal....

See https://github.com/geneontology/go-ontology/issues/13944

(Lots of proteins involved in 'protein quality control' do not slim easily  (unless you use something too general to be useful, at least to cell biologists...)

**Comment by hdrabkin** [comment]
Although, as PMID 25101074 points out, binding of SRP to nascent polypeptides is a form of translation arrest, although temporary. Subsequent docking to the receptor in the ER could be considered a type of stall rescue... so I can see where it might get confusing.....

**Comment by ValWood** [comment]
So there  is translational stalling when you are going to subsequently translocate your protein which occurs during translation  (this would seem to be regulation of the translation process),
then, there is stalling that occurs during the aberrant situation, which is part of "protein quality control" and the ribosome is "disassembled". Is that correct?

**Comment by hdrabkin** [comment]
Right, and the "aberrant" can be something as simple as low amino acid concentration which leads to a low availability of an amino-acyl-tRNA. 
We should look at where the use of tmRNA mediated process (the bacterial equivalent of what to do with a stalled ribosome) sits in the ontology also.

**Comment by ValWood** [comment]
So do  you think  this is a type of "recycling" process that is "downstream" of "negative regulation of translation in response to nutrient  stress"?

That would come under some sort of "protein quality control" term possibly....

**Comment by hdrabkin** [comment]
After a good night's sleep
 I see GO:0072344 - rescue of stalled ribosome, as an is_a regulation of translation (which has a regulates relationship to translation)  so not actually part of translation per se, so 
I suppose this is ok if  you think of it as a release of a block on translation. 
So I think the current term needs two children: cytoplasmic and mitochondrial. 
latter is child of reg. of mito trans (GO:0070129), and the former a child of reg. of cyto trans (GO:2000765).

**Comment by ValWood** [comment]
Can this be done? seems the actions are clear?
Also, note that this ticket
https://github.com/geneontology/go-ontology/issues/18610
is related

**Comment by ValWood** [comment]
this can close, is redundant with #18610
