### ISSUE TITLE
MAP phosphatase 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13868]
I think MAP phosphatases  is dual specificity 
(i.e
GO:1990439	MAP kinase threonine phosphatase activity

->MAP kinases serine/threonine phosphatase activity

i.e the terms which dephosphorylate threonine also dephosphorylate ~threonine~ serine.

Can this term be changed? Or can we have a new term?

Note that I still don't think its necessary to capture residue combinations in terms in general , but this proposal was overturned
https://github.com/geneontology/go-ontology/issues/12416

So if we are doing it we need to do consistently.

**Comment by ValWood** [comment]
Also  MAP phophatases are Mg dependent, but they don't have this parent

GO:0004724	
magnesium-dependent protein serine/threonine phosphatase activity

**Comment by ukemi** [comment]
I'm not exactly sure what you want in this ticket, but it looks like this term is problematic. I think the issue is that it is supposed to describe a threonine phosphatase, but it's placement in the graph and its definition confuse it with a tyrosine phosphatase. I think what you want is to:

Change the def of 'MAP kinase threonine phosphatase activity' from:
Catalysis of the reaction: MAP kinase threonine phosphate + H2O = MAP kinase tyrosine + phosphate.

to:
Catalysis of the reaction: MAP kinase threonine phosphate + H2O = MAP kinase threonine + phosphate.

and make it a child of 'protein serine/threonine phosphatase activity', correct? 
Are you sure they are ALL magnesium-dependent?

**Comment by ValWood** [comment]
But that term exists already?

GO:1990439 | MAP kinase threonine phosphatase activity

I think it should be 
MAP kinase serine/threonine phosphatase activity

But  the one I am annotating is dual specificity  so I can use:
GO:0017017 MAP kinase tyrosine/serine/threonine phosphatase activity


re the magnesiun I think they are all mg/mn so maybe the parent can not be added.

Its a bit sub-optimal as you can end up annotating the same function in different branches.
GO:0033549 MAP kinase phosphatase activity
or
GO:0004724 | magnesium-dependent protein serine/threonine phosphatase activity

which makes it appear to be multifunctional, but its a single activity.

I didn't really want to request 
mg/mn-dependent MAP kinase tyrosine/serine/threonine phosphatase activity
because it's a given.

https://en.wikipedia.org/wiki/Protein_phosphatase
MAP kinase phosphatases are
"the protein phosphatase Mg2+- or Mn2+-dependent (PPM) family"

don't worry about the mg part....

**Comment by ukemi** [comment]
Yes, you should probably use the dual specificity. But I still think there is an issue with GO:1990439. Take a look at it's definition and it's placement in the ontology. 

So here is the big question. As far as I know all threonine phosphatases are serine/threonine phosphatase. But in the case of these types of MAPK phosphatases, it appears that they only ever work on phosphothreonine. So is it ok to still classify them as serine/threonine phosphatases? I think with the new views of the MF overhaul, this would be ok.

**Comment by ValWood** [comment]
Ah OK, I didn't know that. I thought all serine/threonine had interchangable specificity.

but I can only find Threonine phosphorylations from MAP kinases in our data...

**Comment by ValWood** [comment]
No I found a serine phosphorylation by Sty1.

**Comment by ValWood** [comment]
ignore that.

**Comment by mah11** [comment]
DPH asked me to look at this ticket, so ... I don't know these kinases and phosphatases very well, but it doesn't take any specialist knowledge to see that GO:1990439 is a mess at present. I didn't know whether it was intended to be a threonine phosphatase (with or without including serine) or a tyrosine phosphatase, but right now it's got bits of both clashing in an entertainingly awkward way.

A quick look through the ontology finds GO:0033550 ! MAP kinase tyrosine phosphatase activity, so I guess GO:1990439 was meant to be the threonine term, matching its name, and it should be moved and have its definition corrected accordingly.

I'll gladly defer to anyone better informed on the question of whether serine phosphatase and threonine phosphatase need to be separate terms; I don't know whether any phosphatase that can dephosphorylate phospho-threonine will also dephosphorylate phospho-serine on a MAP kinase or any other substrate.

**Comment by ukemi** [comment]
OK. So the bottom line here is to rename and redefine GO:1990439 to be a serine/threonine phosphatase?

**Comment by mah11** [comment]
I've got no objection to that (not-an-expert caveats still apply)

**Comment by ukemi** [comment]
Thanks for the sanity check!

**Comment by ValWood** [comment]
You might be correct David in the MAP kinases always phosphorylate Tyrosines. Do you have any examples of  serine/threonine phosphorylation by MAP kinases?
@Antonialock  might know....

We have examples of serine phosphorylations of MAP kinases.
I have no idea if MAP kinases can only be phosphorylated by MAP kinase kinase family, or if they have other direct kinase targets which phosphorylate on serines...

I could also ask some of our community experts.

**Comment by ukemi** [comment]
Now I'm really confused. This ticket is about the phosphatases. I think the plan to correct the threonine phosphatase as follows makes sense, even if it only normally dephosphorylates phosphothreonine.

new name for GO:1990439--MAP kinase serine/threonine phosphatase activity
New def: Catalysis of the reaction: MAP kinase threonine phosphate + H2O = MAP kinase threonine + phosphate and MAP kinase serine phosphate + H2O = MAP kinase serine + phosphate.
is_a: protein serine/threonine phosphatase activity

**Comment by ValWood** [comment]
I was looking at phosphorylations  events on MAP kinase in general because they would need to be present to be able to remove them...I  see examples of MAP kinases being phosphorylated on all 3 residue types (with a preference for tyrosine). Where the  MAP kinase/ phosphatase doing the addition/removal is known, it is always Tyrosine though...

**Comment by ukemi** [comment]
The reference cited in the definition of GO:1990439 shows threonine.
