### ISSUE TITLE
GO:0036503 - ERAD pathway missing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13860]
ERAD is defined
The protein catabolic pathway which targets endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. It begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, protein modifications necessary for correct substrate transfer (e.g. ubiquitination), transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome. 

should it have
 GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process

as a parent (it is also ubiquitin dept)

**Comment by krchristie** [comment]
As the definition of **"ERAD pathway" (GO:0036503)** says this:

The protein catabolic pathway which targets endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. It begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, **protein modifications necessary for correct substrate transfer (e.g. ubiquitination)**, transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome.

I was wondering if **ALL** ERAD required ubiquitination. Examining one of the papers (PMID: 21969857) cited in the definition of this term, it seems clear that there are forms of ERAD that are ubiquitin-independent. Below I've quoted some relevant text from the abstract.

> **PMID:21969857:** Liu Y, et al. A ubiquitin independent degradation pathway utilized by a hepatitis B virus envelope protein to limit antigen presentation. PLoS One. 2011;6(9):e24477.  
> 
> Hepatitis B virus envelope glycoproteins Large (L), Middle (M) and Small (S) are 
> targets of the host cellular immune system. [snip] We have used M as a
> model to study this process and determine how ER quality control monitors these
> foreign polymeric proteins and disposes of them through the ER-associated
> degradation (ERAD) pathway. Using both wild type and mutant HBV M protein, we
> found that unlike most ERAD substrates, which require ubiquitination for
> retrotranslocation and degradation, the HBV M protein, which only contains two
> lysine residues, can undergo rapid and complete, **ubiquitin independent,
> proteasome dependent degradation**.  [snip]



Note that there is also a term for **"ubiquitin-dependent ERAD pathway" (GO:0030433)**

Thus, I think the term "ERAD pathway" should not have the parentage you suggest.

**Comment by ValWood** [comment]
Hi Karen, 
That makes total sense.
Instead ERAD should have "proteasomal catabolic process" parent.
The term you mentioned "ubiquitin dependent ERAD" already has the ub-dept and proteasomal parent.
val

![erad](https://user-images.githubusercontent.com/7359272/28237125-d87852ee-692f-11e7-88a5-acdb04495b88.jpg)

**Comment by krchristie** [comment]
Hi Val,

I agree with you. I've changed the parentage of 'ERAD pathway' from:
**-is_a: GO:0030163 ! protein catabolic process**

to:
**+is_a: GO:0010498 ! proteasomal protein catabolic process**

-Karen
