### ISSUE TITLE
GO:0099738	cell cortex region - GO:0005938 cell cortex RELATIONs

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13875]
I just noticed that 2 relations currently exist between GO:0099738 cell cortex region and GO:0005938 cell cortex.

![screen shot 2017-07-11 at 13 15 33](https://user-images.githubusercontent.com/16541096/28067952-5a4053e6-663b-11e7-825a-34c5ff265a6c.png)

**Comment by ukemi** [comment]
@dosumis 
Based on the logical def of the region term, it looks like this is correct. Although it does seem a bit weird.

**Comment by dosumis** [comment]
It comes from the logical def for cases where a part fulfills a general definition.  See also 'membrane region'  and 'plasma membrane region'. Biologists talk about the postsynaptic membrane and classify it as a type of membrane.  I think classifying it as a 'plasma membrane region' is clear and intuitive - a big improvement on the former classification directly under 'membrane part', which is also used for  things like 'integral component of a membrane.  Cell cortex region is just another example of this:  the whole of the cell cortex that resides in some region of the cell. 

@cmungall hates these.  I think its a useful pattern.

**Comment by BarbaraCzub** [comment]
ok, thanks for clarifying this!

**Comment by cmungall** [comment]
@dosumis, the pattern here seems slightly different from that of membrane region. I think I might dislike it less if it followed this pattern:

```
name: membrane region
intersection_of: GO:0016020 ! membrane
intersection_of: part_of GO:0098805 ! whole membrane
```

this is ultra-peculiar

```
name: cell cortex region
intersection_of: GO:0005938 ! cell cortex
intersection_of: part_of GO:0005938 ! cell cortex
```

**Comment by ukemi** [comment]
+1  This gets around my concern that part_of should be reflexive, shouldn't it? So the pattern just asserts a characteristic of the relation.

**Comment by cmungall** [comment]
Yes, if part_of is reflexive, then XR = R, so the pattern depends on part_of being interpreted as proper part of

See also https://github.com/oborel/obo-relations/issues/78

**Comment by dosumis** [comment]
> this is ultra-peculiar

> name: cell cortex region
> intersection_of: GO:0005938 ! cell cortex
> intersection_of: part_of GO:0005938 ! cell cortex

Rather a strong way to put it.  It just follows a generic pattern for types where some parts fulfill the definition of the general type.  It does depend on the assumption of proper parthood, which I thought until recently we were following.   I'm happy to experiment with switching to reflexive parthood - but I think this should be done carefully as It will add inferences that cause similar confusions to the one above.  For example for all X-part terms, X will become a subclass.  (membrane is_a 'membrane part')

After previous discussions about double-labelled edges, I switched to doing the 'whole X' pattern for membrane.  I don't see any major problem with switching to this pattern bit it is quite a bit more work and complicates some derivative patterns eg. organelle membrane.  I'm not sure I've caught every case where membrane should be whole.  Also got a bit confusing with bits of the ER, Golgi & endosome where can be hard to know which terms refer to whole membranes.

**Comment by hdrabkin** [comment]
This same thing just happened to me
name: apicomedial cortex
is_a cell cortex region
part_of apical cortex
but then get an inference to is_a apical cortex.

**Comment by ukemi** [comment]
>  For example for all X-part terms, X will become a subclass. (membrane is_a 'membrane part')

Yes. This would be a problem!

**Comment by cmungall** [comment]
Let's not get too distracted by the X-part terms, no one would miss them if they went away

**Comment by dosumis** [comment]
> Let's not get too distracted by the X-part terms, no one would miss them if they went away

Possibly not. But if you'll end up with a very flattened CC if you get rid of them.

**Comment by dosumis** [comment]
Another side effect of the changing to reflexive:

![image](https://user-images.githubusercontent.com/112839/28133987-897335c6-6739-11e7-838b-722b68fd3dc7.png)
![image](https://user-images.githubusercontent.com/112839/28133943-66da6db8-6739-11e7-83bf-d60b8a3ff092.png)
![image](https://user-images.githubusercontent.com/112839/28133954-7064d288-6739-11e7-84e4-c0dcb190e54c.png)

Presumably will => quite a lot of new inferences.
