### ISSUE TITLE
NTR: 'neuron projection arborization' and children

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13877]
Figure 7 in PMID: 23270857 shows that Chrna7 ko mice are characterised by less dendritic branching relative to controls. I would like to annotate this using a new term: 'dendrite arborization'. Below is my suggestion of how this could fit into the ontology.

_NEW GO term1_: neuron projection arborization
Definition: The process in which the anatomical structures of a neuron projection are generated and organized into branches. A neuron projection is any process extending from a neural cell, such as axons or dendrites.
_NEW synonym_: branching morphogenesis of a neuron projection 
_NEW synonym_: branching morphogenesis of a neurite

_NEW GO term2_ : dendrite arborization
The process in which the anatomical structures of a dendrite are generated and organized into branches.

Having discussed this with @RLovering we think that an analogous term should exist for axons (see e.g. http://www.lsi.umich.edu/ye-lab/axonal-arbor-development). Below are suggestions of relevant terms and meanings:

_NEW GO term3_ : axon morphogenesis
The process in which the anatomical structures of an axon are generated and organized. An axon is the long process of a neuron that conducts nerve impulses, usually away from the cell body to the terminal branches.
(Please note, I think this term should be created as a parent of 'axon arborization', as I do not think 'axon arborization' can be a child of 'axonogenesis', which is defined as: "De novo generation of a **_long_** process of a neuron...").

_NEW GO term4_ : axon arborization
The process in which the _terminal_ anatomical structures of an axon are generated and organized into branches of specialised projections, or boutons. An axon is the long process of a neuron that conducts nerve impulses, usually away from the cell body to the terminal branches.

Relationships:
> GO:0048812 neuron projection morphogenesis
>> _NEW GO term1_ : neuron projection arborization
>>> _NEW GO term2_ : dendrite arborization

> GO:0048812 neuron projection morphogenesis
>> GO:0048813 dendrite morphogenesis
>>> _NEW GO term2_ : dendrite arborization

> GO:0048812 neuron projection morphogenesis
>> GO:0007409 axonogenesis
>> _NEW GO term3_ : axon morphogenesis
>>> _NEW GO term4_ : axon arborization

Refs: GOC:aruk and GOC:bc

Thanks,
Barbara

**Comment by ukemi** [comment]
I think axonogenesis is meant to be equivalent to axon morphogenesis. Please also consider how these terms fit into the branching hierarchy and how they fit in with terms like dendritic tree. #13785

**Comment by BarbaraCzub** [comment]
Thanks @ukemi for pointing this out. It is in fact an exact synonym. In this case I wonder whether the definition of 'axonogenesis' should be modified to make it clear that this morphogenesis process refers not only to the elongated portion of an axon but also to other parts? The current definition is:
"De novo generation of a long process of a neuron, that carries efferent (outgoing) action potentials from the cell body towards target cells. Refers to the morphogenesis or creation of shape or form of the developing axon."
Maybe it could be modified as follows:
"De novo generation of a long process of a neuron, including the terminal branched region. Refers to the morphogenesis or creation of shape or form of the developing axon, which carries efferent (outgoing) action potentials from the cell body towards target cells."

**Comment by pgaudet** [comment]
Hello @BarbaraCzub 
I changed the definition for axogenesis as you proposed. I noticed it's a child of 'anatomical structure morphogenesis and of 'neuron projection morphogenesis'; shouldn't it be only a child of 'neuron projection morphogenesis'? Perhaps this is a question for @ukemi

**Comment by ukemi** [comment]
I thought all cellular components were considered to be anatomical structures. So this seems ok to me.

**Comment by pgaudet** [comment]
ok thanks @ukemi

**Comment by pgaudet** [comment]
Hello again @BarbaraCzub 
Can you provide references for the new terms, and to whom the attributions should be given ?

**Comment by BarbaraCzub** [comment]
Hi @pgaudet please attribute the new terms to GOC:aruk and GOC:bc.

References:
Dendrite arborization: PMID: 23270857.
Axon arborization: PMID: 23764288.
Both references can be used for the new parent term: 'neuron projection arborization'.

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Re: 'anatomical structure morphogenesis'. 

Since 'axon development' and descendants are child terms of 'anatomical structure morphogenesis', perhaps they should also be child terms of 'GO:0048755 branching morphogenesis of a nerve'? 

'GO:0048755 branching morphogenesis of a nerve' 
Definition: 'The process in which the anatomical structures of branches in a nerve are generated and organized. This term refers to an anatomical structure (nerve) not a cell (neuron).'

'UBERON:0001021 nerve' 
Definition: 'An enclosed, cable-like bundle of axons in the peripheral nervous system originating in a nerve root in the central nervous system (or a condensed nervous structure) connecting with peripheral structures.'

**Comment by pgaudet** [comment]
New terms: 

[Term]
+id: GO:0140058
+name: neuron projection arborization
+namespace: biological_process
+def: "The process in which the anatomical structures of a neuron projection are generated and organized into branches. A neuron projection is any process extending from a neural cell, such as axons or dendrites." [GOC:aruk, GOC:bc, PMID:23270857, PMID:23764288]
+synonym: "branching morphogenesis of a neurite" RELATED []
+synonym: "branching morphogenesis of a neuron projection" RELATED []
+is_a: GO:0048812 ! neuron projection morphogenesis
+created_by: pg
+creation_date: 2017-07-12T12:25:31Z
+
+[Term]
+id: GO:0140059
+name: dendrite arborization
+namespace: biological_process
+def: "The process in which the anatomical structures of a dendrite are generated and organized into branches." [PMID:23270857]
+is_a: GO:0048813 ! dendrite morphogenesis
+is_a: GO:0140058 ! neuron projection arborization
+created_by: pg
+creation_date: 2017-07-12T15:12:07Z
+
+[Term]
+id: GO:0140060
+name: axon arborization
+namespace: biological_process
+def: "The process in which the terminal anatomical structures of an axon are generated and organized into branches of specialised projections, or boutons. An axon is the long process of a neuron that conducts nerve impulses, usually away from the cell body to the terminal branches." [GOC:aruk, GOC:bc, PMID:23764288]
+is_a: GO:0007409 ! axonogenesis
+created_by: pg
+creation_date: 2017-07-12T15:17:22Z
+


Modified definition for axonogenesis

OLD def: "De novo generation of a long process of a neuron, that carries efferent (outgoing) action potentials from the cell body towards target cells. Refers to the morphogenesis or creation of shape or form of the developing axon." [GOC:dph, GOC:jid, GOC:pg, GOC:pr, ISBN:0198506732]
NEW def: "De novo generation of a long process of a neuron, including the terminal branched region. Refers to the morphogenesis or creation of shape or form of the developing axon, which carries efferent (outgoing) action potentials from the cell body towards target cells." [GOC:dph, GOC:jid, GOC:pg, GOC:pr, ISBN:0198506732]
 comment: Note that 'axonogenesis' differs from 'axon development' in that the latter also covers other processes, such as axon regeneration (regrowth after loss or damage, not necessarily of the whole axon).
 synonym: "axon growth" NARROW []
 synonym: "axon morphogenesis" EXACT [GOC:bf, PMID:23517308]


Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet 

I'm not sure whether this makes a difference in practical terms, but perhaps we should add one more synonym to 'neuron projection arborization', specifically 'neurite arborization'?
