### ISSUE TITLE
relax def for GO:0036452 ESCRT complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13883]
Having just seen #13879 I noticed that the def for GO:0036452 ESCRT complex should be relaxed:

Current def: An endosomal sorting complex required for transport.

But it does an awful lot more, see 
http://www.ebi.ac.uk/complexportal/complex/search?query=escrt&page=1
e.g. ESCRT-III:
http://www.ebi.ac.uk/complexportal/complex/EBI-11509704

which is also involved in membrane fission processes for vial budding and cytokinesis which are not transport processes.

Suggested def: An endosomal sorting complex involved in membrane fission processes related to sorting of multivesicular bodies (MVB) in the endocytic pathway, cytokinesis and viral budding among other processes.

Birgit

**Comment by ukemi** [comment]
So was it intentional that GO:1990621 was not a subclass of ESCRT complex? The definition says that it is. 
Happy to change the def if you think that is best.

**Comment by bmeldal** [comment]
Ah, I forgot to check the ESCRT-IV entry!

Yes, I think it's safe to make it is_a child of ESCRT complex. I must have missed that that parent was missing when I curated the complex.

If you could update the def for ESCRT complex that would be great.

Birgit
