### ISSUE TITLE
cAMP receptor activity not a child of G-protein coupled receptor activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#13881]
Hello,
After the GO call today I looked at all annotations I get from AmiGO when looking at GO:0007186 G-protein coupled receptor signaling pathway

Once I inspected the annotations, I first looked at ours and noticed we have so many processes and no corresponding functions. But I suspected that for example the car receptors (cAMP receptors) do have functional annotations. E.g, annotated to GO:0001646 cAMP receptor activity.

When I looked, at the graph, and then compared with an activity from my table GO:0004995 tachykinin receptor activity, I saw that this is a child of G-protein coupled receptor activity, but cAMP receptor activity is not. 

Thus, please move  GO:0001646 cAMP receptor activity under GO:0004930 G-protein coupled receptor activity, that should fix that. The definition should also be changed to reflect that in this case, these receptors are G-protein coupled receptors, at least in Dicty.

Current def: Combining with cAMP (cyclic AMP, adenosine 3',5'-cyclophosphate) and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity.

New suggested:  Combining with cAMP (cyclic AMP, adenosine 3',5'-cyclophosphate) and transmitting the signal across the membrane by activating an associated G-protein.

Thanks!
Petra

**Comment by ukemi** [comment]
Hi @pfey03 

It looks like the cAMP receptors can act both as GPCRs and in a G-protein independent manner, See PMID:11832418 Fig 5. Am I interpreting this correctly that all cAMP receptors don't have to act as GPCRs?

Your group is the only one that has used this term for annotation. I suppose we could rename it G-protein coupled cAMP receptor activity and define it as you suggest if there are cAMP receptors that don't act as GPCRs. 
-D

**Comment by pfey03** [comment]
Hi @ukemi,
The review above is quite old and focuses more on why there haven't been any cAMP receptors discovered in higher organisms. I remember that for some activations downstream they found that different receptors use different G-proteins, that the different Car1-4 account for some what was thought to be independent.
I have to read much more recent lit now with this GO project, but your suggestion seems sensitive, if nobody else has ever used this term, to update the existing. For sure, these 4 Dicty cAMP receptors are G-protein coupled and essential processes are downstream of that G-protein interaction.

Thanks!
p

**Comment by ukemi** [comment]
Thanks @pfey03 

I thought you would be way more up to date on this than I was, but thought I would check. 

-D

**Comment by pgaudet** [comment]
Hello , 

I have the same problem reported by @vanaukenk : the apostrophe in " '3',5'-cyclic AMP' " is interpreted as a end of string by Protégé. 
@ukemi @cmungall  is there a way to put some escape character ? 

Thanks, 
Pascale

**Comment by ukemi** [comment]
The only way I have found to get around this is to use the object restriction creator for a relationship-term pair or the class hierarchy for a subclass so you can choose the term by navigating to it. It's not ideal, but it works. They can be found in the tabs at the top of the pop-up window.

**Comment by ukemi** [comment]
We should add this to the documentation.

**Comment by ukemi** [comment]
@pgaudet is correct, it looks like this can't be done while editing logical defs, only for subclasses. We need to discuss it on a call. 

For now I guess you should just make the correct asserted links.

**Comment by deustp01** [comment]
Meanwhile, on the question of whether all cAMP receptors are G-protein-coupled receptors, the answer is "no" for at least some prokaryotes: https://en.wikipedia.org/wiki/CAMP_receptor_protein; and see http://www.uniprot.org/uniprot/P0ACJ8 for multiple pMIDs

**Comment by ukemi** [comment]
But those don't convey the signal across the membrane, so this term wouldn't fit, would it?

Combining with cAMP (cyclic AMP, adenosine 3',5'-cyclophosphate) and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity.

**Comment by pfey03** [comment]
The bacterial protein seems an intracellular cAMP receptor protein that regulates transcription so it is something different. Thus even more reason to make the current term more specific.

**Comment by ukemi** [comment]
By the way @pgaudet. I have solved the problem with the single quotes in logical defs. I can show you how I did it and we can add it to the documentation.

**Comment by pgaudet** [comment]
Hi @deustp01 
I see no annotations to 'cAMP receptor' for this protein; all annotations are to transcription factor activity. So the functions of these two proteins seems to be described very differently.

**Comment by cmungall** [comment]
Did we write up the solution with the apostrophe?

**Comment by cmungall** [comment]
And did we file a bug in the Protege tracker?

**Comment by pgaudet** [comment]
Hi Chris, 

We figured it out but I dont think it's documented. @ukemi did you write that up ? 
I filed a Protege ticket
https://github.com/protegeproject/protege/issues/668

Pascale

**Comment by ukemi** [comment]
As far as I know it is not in our SOPs yet. At least I haven't done it.

**Comment by pgaudet** [comment]
Hi @cmungall @ukemi 

In fact the easy workaround is to use a backslash as an escape character (\). 
Where would this go in our documentation ? Do we need a 'Protégé tips' page @monicacecilia @vanaukenk ? 

Thanks, Pascale

**Comment by ukemi** [comment]
I could have sworn I had tried that first and it didn't work. It should go in the editing documentation in the part about general editing of a term.

**Comment by ukemi** [comment]
PS. I did try it again and it does work.
