### ISSUE TITLE
Use of uberon classes for generic anatomical structures means taxon restrictions are too strict

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13898]
From
https://github.com/geneontology/go-site/issues/403

```
[Term]
id: GO:0048856
name: anatomical structure development
namespace: biological_process
def: "The biological process whose specific outcome is the progression of an anatomical structure from an initial condition to its mature state. This process begins with the formation of the structure and ends with the mature structure, whatever form that may be including its natural destruction. An anatomical structure is any biological entity that occupies space and is distinguished from its surroundings. Anatomical structures can be macroscopic such as a carpel, or microscopic such as an acrosome." [GO_REF:0000021, GOC:mtg_15jun06]
comment: This term was added by GO_REF:0000021.
subset: goslim_chembl
subset: goslim_generic
synonym: "development of an anatomical structure" EXACT []
is_a: GO:0032502 ! developmental process
intersection_of: GO:0032502 ! developmental process
intersection_of: results_in_development_of UBERON:0000061 ! anatomical structure
```

```
[Term]
id: UBERON:0000061
name: anatomical structure
relationship: existence_starts_during_or_after UBERON:0000106 ! zygote stage
```

this introduces an existential dependence between ASs and zygotes, causing problems for use of terms like cell morphogenesis in yeast

We should either

 - [ ] weaken uberon to be inclusive of non-metazoa
 - [x] use CARO in the GO definition for very generic structures

**Comment by ukemi** [comment]
Chris will work out importing the CARO term.

**Comment by cmungall** [comment]
interesting, this is revealing previously cryptic inconsistencies in GO:
![image](https://user-images.githubusercontent.com/50745/28225355-3fd943ca-6887-11e7-8e28-ce250e4a62fb.png)

This was not revealed before; we already had an axiom classifying CL cell under CARO anatomical structure, but because we weren't using CARO in GO there was no linkage and hence this problem went unnoticed.

Good choice to go with CARO everyone!

I'll remove the disjoints in this PR

cc @dosumis

**Comment by cmungall** [comment]
Ahh, we even annotated this disjointness axiom with a comment:

       <rdfs:comment>We examined all the child terms of &apos;anatomical structure maturation&apos; and found them all to be gross anatomical structures, so we are safe in declaring this to be disjoint from cell maturation. We may rename &apos;anatomical structure&apos; to &apos;gross anatomical structure&apos; in future (GOC:mtg_OBO2OWL_2013)</rdfs:comment>
 
It seems we have reverted from this, and now consider 'anatomical structure P' in GO to be consistently about generic anatomical structures.

We could bring in a gross AS later but not clear if this worth it

**Comment by cmungall** [comment]
I have done my bit

See the linked PR. Merging this will result in a few new classifications under 'anatomical structure maturation', since cells are now anatomical structures

**Comment by tberardini** [comment]
I think I found another problem.  'zygote asymmetric cell division' is linked to 'animal zygote' (CL term for zygote) but has a child 'zygote asymmetric cell division in embryo sac'.  The latter is a plant term.

http://amigo.geneontology.org/amigo/term/GO:0010070#display-lineage-tab

Is there a CARO term for 'zygote'? @cmungall, how to fix this one?

**Comment by cmungall** [comment]
Arose from this: https://github.com/obophenotype/cell-ontology/issues/454

"We will not add a new generic class now, though we can explore this in future if a use case arises (note we would need an inter-ontology subclass with PO)"

guess we have the use case now
