### ISSUE TITLE
cAMP GO:0043950 & GO:0007190

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13901]
Should there not be a connection between the two terms GO:0043950 positive regulation of cAMP-mediated signaling & GO:0007190 activation of adenylate cyclase activity? cheers

**Comment by ukemi** [comment]
Is the connection always true? Is cAMP only made in the context of signaling?

**Comment by Antonialock** [comment]
I do not know but wikipedia seems to suggest so:
https://en.wikipedia.org/wiki/Cyclic_adenosine_monophosphate

**Comment by ValWood** [comment]
So this causes us  this problem:
http://pombase2.aska.gen.nz/term/GO%3A0010619

http://pombase2.aska.gen.nz/term/GO%3A0019933

same pathway, annotated in different branches

Background & figure of the pathway we are modelling
https://github.com/pombase/curation/issues/1582

**Comment by ValWood** [comment]
So really, don't we want to annotate the G-protein complex with MF
GO:0010856 adenylate cyclase activator activity
This is one step in the pathway.

**Comment by ValWood** [comment]
I think the  missing relationship here is
GO:0010619 - adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway

The series of molecular signals generated as a consequence of glucose binding to a G-protein coupled receptor, where the pathway proceeds with activation of adenylyl cyclase and a subsequent increase in the concentration of cyclic AMP (cAMP).

is_a

cAMP-mediated signaling


GO:0007190 activation of adenylate cyclase activity is a regulation of MF process term that we should not need to use.
It would only used for the previous step, the GPCR, and this should be
"MF adenylate cyclase activator activity"

make sense?

**Comment by ukemi** [comment]
See #13903. It looks like the current representation is that the CAMP signaling is downstream and positively regulated by the pathway.

**Comment by ValWood** [comment]
This pathway is interchangeably described as "cAMP-signalling"
it isn't another pathway.
We  get an expert  to corroborate this  for you if you like. ...

**Comment by ukemi** [comment]
We need a group to claim this for the signaling workshop.

**Comment by ValWood** [comment]
This pathway is interchangeably described as "cAMP-signalling"
it isn't another pathway.
We get an expert to corroborate this for you if you like. ...

was in wrong ticket, was supposed to be in
https://github.com/geneontology/go-ontology/issues/13903

**Comment by ukemi** [comment]
See changes in #13903. Removed the positive regulation of cAMP signaling and made it a child.

**Comment by ValWood** [comment]
I can present Antonia's git pathway at the signalling workshop.
Antonia can't attend.
