### ISSUE TITLE
add synonym to GO:0007517 muscle organ development

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13904]
Please add "myogenesis" as EXACT synonym.
Also to it's children.
Thanks, Birgit

**Comment by hdrabkin** [comment]
I thought myogenesis is a cellular process? Although the WIKI def implies a tissue level (Myogenesis is the formation of muscular tissue,), other resources suggest otherwise: 
Myogenesis ... developmental process in embryo where the myoblast differentiates into a muscle cell. 

1. fusion of myoblasts to form myotubes
2 formation of myofibrils within their cytoplasm

Myogenesis might be part of muscle organ development, but not the entire process. 
And organs are a group of different tissues working together.

And can't have an EXACT synonym to the children because then the children are implied to be the exact same thing as the parent?

**Comment by bmeldal** [comment]
Yes, I stumble across this issue again yesterday when looking for myogenesis is the sense of muscle CELL differentiation.

I think it's a bit of a tricky one and I also looked at the Wiki entry.

GO has the following terms:

![image](https://user-images.githubusercontent.com/10517124/28708067-a9062962-7372-11e7-95d6-c58e4e867f1c.png)

The one bit I am confused about is, is the difference between muscle cell differentiation and myoblast differentiation as 'differentiation' appears to be the process that commits a cell to it's fate. And as myoblasts are the progenitors of mature muscle cells there should only be one term for this.

It also makes it difficult to decide which term is exactly myogenesis. My original choice of muscle organ development is wrong, it should be one of the cell differentiation terms as the organ development follows the cell differentiation.

This probably still doesn't make it particularly clear!

**Comment by hdrabkin** [comment]
@ukemi , can you comment on this last point, about the difference?

**Comment by ukemi** [comment]
Similar to the cross-references to ChEBI, GO cross references the cell ontology for cell types. 

myoblast: A cell that is commited to differentiating into a muscle cell. Embryonic myoblasts develop
  from the mesoderm. They undergo proliferation, migrate to their various sites, and then differentiate into the appropriate form of myocytes. Myoblasts also occur as transient populations of cells in muscles undergoing repair.

muscle cell:  A mature contractile cell, commonly known as a myocyte. This cell has as part of its cytoplasm myofibrils organized in various patterns.

According to CL a myoblast is not a type of muscle cell. This asserted link should be removed and we should let the reasoner do the work. However, I would assert that myoblast differentiation is a part of muscle structure development. 

Differentiation includes both the commitment of a cell to a fate and the development of that cell. For the subtleties and complexities of expressing this in the ontology, see PMID:19921742 and look at the paragraph "What about cell differentiation?"

**Comment by bmeldal** [comment]
Thanks, David @ukemi, very nicely written explanation of cell differentiation in that paper!

Action points:
- [ ] add RELATED synonym "myogenesis" to muscle cell differentiation. Reasoning: genesis = development but I can't be sure users will use myogenesis only for development and not for fate commitment as well. It's the process that changes the myoblast to become a myocyte (=muscle cell) so can't a synonym for myoblast differentiation.
- [ ] remove myoblast differentiation is_a muscle cell differentiation.
- [ ] add myoblast differentiation part_of muscle structure development

Birgit
PS: late reply due to summer holidays :)
