### ISSUE TITLE
detection of glucose

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13909]
We have  a term "detection of glucose"
13 EXP for 11 proteins

This is used to annotate "glucose receptors"

These should probably all be
G-protein coupled glucose receptor activity
(or some other receptor term)

My preference would be to obsolete as it is an activity, but if this is not possible for any reason F-P link needs adding from
G-protein coupled glucose receptor activity

**Comment by ValWood** [comment]
curation.pombase.org/pombe/curs/ffbebba84aad52e5/ro

**Comment by pgaudet** [comment]
Hi @ValWood 

How about merging with 'glucose mediated signaling pathway', 'The process in which a change in the level of mono- and disaccharide glucose trigger the expression of genes controlling metabolic and developmental processes. ' 

(I propose to do the same with the parent 'GO:0009732 detection of hexose stimulus' )

The children can probably also be merged into regulation glucose signaling: 
GO:2000970 | regulation of detection of glucose
 GO:2000971 | negative regulation of detection of glucose (single annotation by BHF - @RLovering  do you want to comment?) 
 GO:2000972 | positive regulation of detection of glucose


What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Well the annotations wouldn't be incorrect from this merge, but maybe a heads up to the annotating groups as they could definitely improve the annotation by changing to MF.

**Comment by pgaudet** [comment]
Some of the 'detection of glucose' could also have a 'glucose receptor activity' annotation: 


ID | Symbol | Evidence | Reference | With | Taxon | Date | Source
O94744 | git3 | IMP | PMID:24297439 | - | 284812 | 20140805 | PomBase
P10870 | SNF3 | IGI | PMID:8901598 | SGD:S000002297 | 559292 | 20100104 | SGD
P10870 | SNF3 | IMP | PMID:8901598 | - | 559292 | 20100104 | SGD
P17712 | Gck | IDA | PMID:17470517 | - | 10116 | 20100929 | BHF-UCL
P17712 | Gck | IMP | PMID:16443775 | - | 10116 | 20081107 | RGD
P35557 | GCK | IMP | PMID:12941786 | - | 9606 | 20061219 | UniProt
P52947 | Pdx1 | IDA | PMID:21108535 | - | 10116 | 20110228 | BHF-UCL
P83293 | Gr64a | IMP | PMID:17715294 | - | 7227 | 20081113 | FlyBase
Q04665 | gpa2 | IMP | PMID:24297439 | - | 284812 | 20140805 | PomBase
Q12300 | RGT2 | IMP | PMID:8901598 | - | 559292 | 20100104 | SGD
Q12361 | GPR1 | IMP | PMID:15494315 | - | 559292 | 20071130 | SGD
Q60554 | NKX6-1 | IDA | PMID:21108535 | - | 10036 | 20110228 | BHF-UCL
Q6FNU3 | SNF3 | IMP | PMID:26648919 | - | 284593 | 20160330 | CGD





P35583 | Foxa2 |   | GO:2000971 | negative regulation of detection of glucose
-> certainly does not have MF G-protein coupled glucose receptor activity

**Comment by pgaudet** [comment]
note: 
another set of similar terms: 
 GO:0046015 regulation of transcription by glucose (and + and - children)
Annotations are a mix of signalling in response to glucose and glucose-responsive transcription factors.

**Comment by ValWood** [comment]
closing, out of date
https://github.com/geneontology/go-ontology/issues/18097

**Comment by ValWood** [comment]
proposed action (quick fix)
how about obsolete 
GO:0051594   detection of glucose
with consider

GO:1990576 G-protein coupled glucose receptor activity
or
GO:0010255   glucose mediated signaling pathway (or a descendant)

and open a new ticket for anything left over.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0051594 detection of glucose and its regulation children, 
GO:2000970 regulation of detection of glucose
GO:2000971 negative regulation of detection of glucose
GO:2000972 positive regulation of detection of glucose
 

The reason for obsoletion is that this term is redundant with other terms in the ontology: GO:1990576 G-protein coupled glucose receptor activity and GO:0010255 glucose mediated signaling pathway. 

There are 12 annotations to these terms, by BHF-UCL, CGD, FlyBase, RGD and SGD, see https://github.com/geneontology/go-annotation/issues/4404. There are no mappings to these terms, these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/13909

Thanks, Pascale

**Comment by pgaudet** [comment]
We'd like to proceed with the obsoletion on January 18th, 2023.

**Comment by jlewsmith** [comment]
CGD done

**Comment by RLovering** [comment]
Hi
The enzyme Glucokinase (GK) appears to be a glucose sensing. See https://pubmed.ncbi.nlm.nih.gov/32229720/ and https://pubmed.ncbi.nlm.nih.gov/17179917/ and many other refs 

can I keep this with the detection of glucose term?
Thanks
Ruth

**Comment by deustp01** [comment]
The outcome is sensing, but the mechanism, at least in humans and mice, is that an enzyme with textbook glucokinase activity has evolved to have a Km higher than fasting blood glucose levels and a bit lower than postprandial levels, so pancreatic beta cells and hepatocytes, where the enzyme is expressed, are enabled to take up glucose and retain it as glucose 6-phosphate particularly efficiently in the postprandial state. The elevated glucose 6-phosphate levels feed into a mechanism for insulin granule release in the beta cells and provide substrate by mass action for glucose utilization pathways in hepatocytes. Is "detection" the best word to describe this? (That's a question, not an opinion.)

**Comment by pgaudet** [comment]
Thanks @deustp01 

This was also how I understood the issue - ie we end up describing the same pathway using two different aspects. 

> PMID:17179917 GLUT-2, and glucose phosphorylating enzyme, glucokinase, are key for glucose sensing of the pancreatic beta-cell, the initial event in the pathway for glucose-stimulated insulin secretion.

This can also be read as GO:0010255 glucose mediated signaling pathway

> GK in the PVN acts as part of a glucose-sensing mechanism within the PVN that regulates glucose homeostasis by controlling glucagon-like peptide 1 (GLP-1) release

So, GK seems to activate signal transduction that leads to insulin and glucagon secretion (I dont know whether these are describing the same pathway).

**Comment by pgaudet** [comment]
@RLovering 'detection of glucose', which is_a 'response to glucose', fails to describe that this really is signaling. 

 I could create 'glucose sensor activity' as a child of 'GO:0140299 small molecule sensor activity' - would that address the issue?

**Comment by RLovering** [comment]
Sorry my github ticket hadn't updated with Pascale's comments.
 'glucose sensor activity' is a good idea. 
and you would like the term  GO:0010255 glucose mediated signaling pathway added to perhaps both Glucokinase and its regulator?
and are you also suggesting keeping the detection term with Glucokinase or not?

**Comment by ValWood** [comment]
GO:0051594   detection of glucose
has no annotations. I will proceed with the obsoletion.

**Comment by ValWood** [comment]
Also
GO:0034287  detection of monosaccharide stimulus
GO:0009732  detection of hexose stimulus
GO:0009730   detection of carbohydrate stimulus (3 EXP)

but then we get to "detection of chemical stimulus" has 545,012 annotations 647 EXP.
Presumable all should be "sensors"
@hattrill  any thoughts, 307 are drosophila

**Comment by hattrill** [comment]
So, most to these are receptors of some type, but there are also co-receptors and other partners. Some are gustatory, some are olfactory, not always able to classifiy them. 

Because of the nature of the experiments - generally signaling in groups of neurones we cannot often say give a MF (as no binding data) - but can say that it is needed to detect that chemical class.

**Comment by ValWood** [comment]
Maybe we keep detection of stimulus and remove the specific children where is is known what is being sensed? @pgaudet ?

**Comment by pgaudet** [comment]
Maybe we can leave this for now? Seems low priority. We can revisit later. What do you think ?

**Comment by ValWood** [comment]
OK I'll close, but of we get predictions to these terms from the function prediction brigade, I'll  open a new ticket.
I'm also  happy to process the unannotated children now...

**Comment by ValWood** [comment]
For the future
