### ISSUE TITLE
Definition of 'vesicle scission (GO:0099050)'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13915]
I have just discussed vesicle scission (GO:0099050) with @RLovering and we thought that the definition of vesicle scission needs to be updated.

Atm the definition is:
"The membrane scission process that is the final step in the formation of a vesicle: separation from its parent membrane."

However, the vesicle membranes need to fuse together after the scission, therefore,could we please modify the definition as follows:
"The membrane scission process that is the necessary step in the formation of a vesicle: leading to separation from its parent membrane."

This is related to #13907

Thanks,
Barbara

**Comment by dosumis** [comment]
Do you have example annotations where this distinction is important?  IRRC from synapse examples, these happen simultaneously and involve the same gene products.

**Comment by BarbaraCzub** [comment]
Good point. No, we do not have examples. This just occurred to us, as we were discussing 'vesicle assembly' #13907. If the vesicle scission and its closure/fusion happen simultaneously, then perhaps the definition of 'vesicle scission (GO:0099050)' needs to be updated to clarify this?
E.g. "The membrane scission process that is the necessary step in the formation of a vesicle: leading to separation from its parent membrane. Vesicle closure (vesicle membrane fusion) forms an inseparable part of vesicle scission."

**Comment by dosumis** [comment]
We should try to find examples from GO-CAM to use as refs/examples.

**Comment by BarbaraCzub** [comment]
I just had another chat with @RLovering about this, and if 'vesicle scission' does in fact always involve the vesicle membrane fusion step, then it should be linked to 'fusion' in the ontology, and it should include synonyms, such as 'vesicle fusion involved in vesicle assembly'? (This is a new term, which I requested in #13907 ). Additionally, this term should become a child of 'vesicle assembly'.

**Comment by dosumis** [comment]
Nope.   

Fusion: two (connected) membranes ->  one
Fission (of which scission is the final step): One (connected) membrane  -> two.

**Comment by dosumis** [comment]
First paper I found by googling has a nice figure:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2743992/figure/F6/

They do use the term 'fusion', but I still think it's useful to keep the two meanings distinct - not least because the have different mechanisms.

**Comment by BarbaraCzub** [comment]
Ok, in this case 'fusion' is not the right word here. Presumably the membrane closes spontaneously due to physicochemical (or other) interactions. Whatever it is, there needs to be a sentence in the definition stating that this happens. Perhaps we should simply call it 'membrane vesicle closure'? Although the reason why we felt 'fusion' was more appropriate was that most 'closure' terms in the ontology seem to refer to development of anatomical structures.

**Comment by dosumis** [comment]
> Ok, in this case 'fusion' is not the right word here. Presumably the membrane closes spontaneously due to physicochemical (or other) interactions. 

That's the impression I have.

> Whatever it is, there needs to be a sentence in the definition stating that this happens. 

Agree.   Not to bothered if we use the term 'fusion', closure or connection within the def.  Was objecting to adding relationship.

**Comment by ValWood** [comment]
Don't the vesicles always from from preexisting membranes like this:
(i don't know of another way?).
If not I don't think there is any difference between "membrane vesicle closure" and "scission"

**Comment by dosumis** [comment]
> Don't the vesicles always from from preexisting membranes like this:

Yep.  That's what I'm saying.  We should only have one term.

**Comment by BarbaraCzub** [comment]
Ok, so maybe the definition could be updated to include these details. E.g.:

"The membrane scission process that is the final step in the formation of a vesicle, leading to separation from its parent membrane. Vesicle scission involves the constriction of a neck-forming protein complex, consisting e.g. of dynamin, around the budded membrane, leading to vesicle closure during its separation from the parent membrane."

Or something along these lines?

**Comment by dosumis** [comment]
> "The membrane scission process that is the final step in the formation of a vesicle, leading to separation from its parent membrane. Vesicle scission involves the constriction of a neck-forming protein complex, consisting e.g. of dynamin, around the budded membrane, leading to vesicle closure during its separation from the parent membrane."

Perfect

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 

I updated the definition, I am sure we'll find plenty of similar tickets by October! 

Cheers, Pascale

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet
