### ISSUE TITLE
postive regulation of cAMP biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13910]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030819#term=annotation

Lots of things related to adenylate cyclase regulation via GPCR signalling are annotated to "cAMP biosynthetic process"

I wonder if they should not be (this process/pathway doesn't *synthesise*  cAMP as such, its just an isomerization of ATP.

Should these terms exist?

**Comment by ValWood** [comment]
@pgaudet  would this fit your def of metabolism?

**Comment by ValWood** [comment]
ignore this one

**Comment by pgaudet** [comment]
Hi @ValWood 

Why ignore this ? I agree that adenylate cyclase regulation via GPCR signalling should not be lined to cAMP biosynthetic process. It just doesn't sound correct. Is this being discussed in the signaling work @pfey03 ? 

Thanks, Pascale

**Comment by ukemi** [comment]
@pgaudet, @ValWood

adenylate cyclase activity GO:0004016
part_of cAMP biosynthetic process GO:0006171

AC catalyses the conversion of adenosine triphosphate (ATP) to 3',5'-cyclic AMP (cAMP) and pyrophosphate. In that sense YES, it is involved in the biosynthesis of cAMP

**Comment by ValWood** [comment]
Yes I discussed with Antonia. Came to the conclusion that "cAMP metabolism" was OK, but "biosynthesis" wasn't  (because its just an interconversion)...yes I'd still like to discuss this then...
It will be a very full day!

**Comment by pfey03** [comment]
Hmm, it does get rid of the pyrophosphate, so a true reaction not just interconversion in my mind
![ac reaction](https://user-images.githubusercontent.com/1349602/28378550-285ad66c-6c76-11e7-9387-5994d9efcb1c.png)

**Comment by pgaudet** [comment]
Hi @pfey03 

If you consider this reaction metabolism, then the logical conclusion would be that any enzymatic activity should be metabolism (which if I understand correctly is more or less how GO is organized). I would prefer it if we stuck to primary and secondary metabolism for 'metabolism' but I that would probably involve a lot of changes in the ontology. 

@ukemi @hdrabkin anyone else have input about this ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
I too think that this is NOT an interconversion. It's a biosynthesis of cAMP.

**Comment by ValWood** [comment]
Yes it is. This is different from the other examples we discussed about metabolism.
