### ISSUE TITLE
synonym for Cvt vesicle assembly

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#13914]
Hi David

please could you add the following synonyms. Sorry about this, Barbara was looking at one of these terms and didn't know what Cvt was.

Thanks

Ruth

GO:0071255 Cvt vesicle assembly
exact: cytoplasm to vacuole vesicle assembly
exact: cytoplasm-to-vacuole vesicle assembly

GO:0033107 Cvt vesicle
exact: cytoplasm to vacuole vesicle 
exact: cytoplasm-to-vacuole vesicle

GO:0034270 Cvt complex
exact: cytoplasm to vacuole complex 
exact: cytoplasm-to-vacuole complex

GO:0033110 Cvt vesicle membrane
exact: cytoplasm to vacuole vesicle membrane
exact: cytoplasm-to-vacuole vesicle membrane

**Comment by RLovering** [comment]
@BarbaraCzub

**Comment by ukemi** [comment]
cytoplasm to vacuole targeting vesicle assembly etc?

**Comment by BarbaraCzub** [comment]
I just didn't know what the acronym referred to (without having to look at the references), so I suppose it would be helpful if it got spelt out fully in the definition at least once.
