### ISSUE TITLE
NTR:  interspecies electron transfer and Direct interspecies electron transfer (DIET)

### ISSUE THREAD

**Issue by mkoert1** [geneontology/go-ontology#13911]
In the abstract and throughout the body of PMID: 28287150 there are multiple references to the process of Direct interspecies electron transfer and interspecies electron transfer and I believe that these terms should be captured.

I am still new at dealing with Gene Ontology so there may be a more fitting spot but if I had to find a place to put this new term I would place it somewhere under GO:0044033 multi-organism metabolic process. Anything more specific and  I thought the terms not longer meet the requirements.

As for the definitions Interspecies electron transfer can be defined as something akin to:  a process by which different species couple metabolic energy balances through the transfer of electrons. While Direct interspecies electron transfer (DIET) can be defined as: a process by which different species couple metabolic energy balances through the transfer of electrons through physical contact.

I'm not entirely familiar with how to generate a new GO:ID number so I will leave this section blank for the time being.

Lastly the names of the GO terms should be interspecies electron transfer and Direct interspecies electron transfer (DIET) in case I didn't make that clear.

Thanks for your consideration.

Matthew Koert

**Comment by hdrabkin** [comment]
Hi @mkoert1 ; 
May also need a relationship to electron transport process
Def of interspecies electron transfer seems a little vague.  If it's not through direct contact, 
I

**Comment by hdrabkin** [comment]
I guess the def of NTR1 should mention diffusion of intermediates as per their example, but then NTR2 couldn't be a proper child. So I'm thinking NTR1 would be a parent class which doesn't specify the way it happens and NTR3 and NTR2 would be children, where NTR3 would specifically invoke diffusion of intermediates between different species in a mixed culture.

**Comment by ValWood** [comment]
This paper describes a process, but it does not describe any genes which may be involved. Maybe this is just something that occurs but there is no mechanism (the numbers are tiny), and 
 may not even be an evolved process. 

Considering we have so many  papers to curate and so many papers with information to attach to genes,  and we are waiting for so many terms to curate these paper, I would like to make a proposal:

We should not add terms to GO *until* we have  known genes to annotate to them. I think we should be working towards path of annotating only when we have a mechanism, but that is probably a step to far for most.

Harold could you bring this up at the editors discussion?

**Comment by hdrabkin** [comment]
Geobacter metallireducens/sulfurreducens  genes involved in the making contacts (nanowire pili "produced by iron-reducing bacteria".

**Comment by ValWood** [comment]
Ah so the genes are known. I  didn't see any mention when I scanned the paper...apologies...

**Comment by hdrabkin** [comment]
Not sure but since the Geobacter produce the pili, I assume so.
Also, for the non-direct one, I am thinking that the process might need to involve some transports (one for getting the intermediate out of one cell and one to get it into the other? 
I haven't had time to look up any of the references. I've just blown away that this occurs!

**Comment by pgaudet** [comment]
Hello, 

If the decision ids to create the term, I don't think 'electron transport' should be linked. In GO we have 'electron transport chain' which is unlikely to be multi species. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
@mkoert1 
Are you going to use these for annotations of specific genes? The paper itself does not as @ValWood  points out, but are you planing to use other papers describing these genes If not we think this shouldn't be an actionable issue at this time.

**Comment by hdrabkin** [comment]
@mkoet1 has not responded. I will close this next week

**Comment by hdrabkin** [comment]
No response; closing if suggested terms would not be used.
