### ISSUE TITLE
NTR: membrane curvature sensing

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13916]
Figure 4 and Supplementary Figure 4 in PMID: 25898166 demonstrate that PICALM is involved in sensing of membrane curvature. 

In order to annotate this I would like to request a new term: 'membrane curvature sensing'.

_Suggested_ definition: "A process involving (1) the insertion (aka wedging) of the hydrophobic residue side chains of the amphipathic helix (AH) of a membrane curvature sensing (MCS) protein into lipids in a curved membrane and (2) the interactions between the hydrophilic residue side chains of the AH and membrane phospholipid headgroups. Membrane curvature sensing is a part of 'GO:0061024 membrane organization' and 'GO:0016050 vesicle organization'."
Refs: PMID: 21953452 and PMID: 25898166.

_Suggested_ synonyms:
_Exact synonym_: membrane amphipathic lipid packaging sensing (PMID: 25898166 and references within)
_Related synonym_: membrane curvature-sensitive protein-membrane binding (PMID: 21953452).
_Related synonym_: membrane curvature-depending protein-membrane binding
_Related synonym_: membrane curvature-sensitive protein-membrane interaction
_Related synonym_: membrane curvature-depending protein-membrane interaction

> GO:0061024 membrane organization
>> NTR membrane curvature sensing (part_of)

> GO:0016050 vesicle organization
>> NTR membrane curvature sensing (part_of)

Please use refs: GOC:aruk and GOC:bc.

Thanks,
Barbara

**Comment by pgaudet** [comment]
@BarbaraCzub 
Shouldn't the term refer to the vesicle ? ie something like 'clathrin-coated vesicle membrane curvature sensing'?

**Comment by BarbaraCzub** [comment]
Hi @pgaudet 

(re: 1) I am not convinced. There are membranes that are not vesicle membranes, which are certainly curved. The two papers, which I have referenced involved studies done on liposomes, so we should not create organelle-specific terms, based on them.

(re: 2) For 'is_a' parent I would be reluctant to choose anything more specific than 'GO:0051128 regulation of cellular component organization' before we can find references with relevant evidence. However, we could create a more specific new parent 'regulation of membrane organization'.

Thanks,
Barbara

**Comment by ValWood** [comment]
I'm a bit unsure about the term request. what is the process of "membrane curvature sensing"
 If it is a single gene product that can monitor membrane curvature in some way it sounds more like a molecular function. 

Then you would annotate 
MF "membrane curvature sensor"  involved in "clathrin coated pit assembly" or a more specific process term.

**Comment by pgaudet** [comment]
Hi @ValWood 

I agree a MF would make sense. What would be the parent 'lipid binding'? 

Thanks, 
Pascale

**Comment by ValWood** [comment]
I think so...I guess it is analogous to 
GO:0008301 DNA binding, bending ?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008301

**Comment by BarbaraCzub** [comment]
Thanks for the suggestions @ValWood . I agree. It does make more sense for this to be an MF, not a BP. I also think that 'lipid binding' will be a suitable parent. This is also in good agreement with the synonyms, which I suggested above, e.g. the _Related synonym_: 'membrane curvature-sensitive protein-membrane binding', based on PMID: 21953452.

**Comment by pgaudet** [comment]
This one is done, it's a pull request that failed. We were planning to discuss this at the Protege workshop last week but didn't get to it.

**Comment by pgaudet** [comment]
Created new term again
+id: GO:0140090
+name: membrane curvature sensor activity
+namespace: molecular_function
+def: "Preferential binding of proteins on curved membranes. The binding to curved membranes by insertion (aka wedging) to curved membranes is mediated by both the hydrophobic and hydrophilic faces of the helix of membrane curvature sensing (MCS) proteins." [PMID:25898166]
+is_a: GO:0008289 ! lipid binding
+created_by: pg
+creation_date: 2017-08-19T20:37:54Z
