### ISSUE TITLE
dendritic spine origin

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13927]
I would like to see “dendritic spine origin” added as a child term of dendritic spine (GO:0043197).  Definition could be “The part of the proximal dendritic spine where the spine arises from the dendritic shaft.”  PMID:9030614

**Comment by BarbaraCzub** [comment]
I suppose this should ultimately also be a child term of 'GO:1990033 dendritic branch point' (part_of)? However, I believe we also need to establish whether a 'dendrite' refers to a single neuron projection (arising either from the cell body, or from another neuron projection), or to a branch of dendritic projections, as the current definition of 'GO:1990033 dendritic branch point' suggests (def.: 'The part of a dendrite where the cell projection branches, giving rise to a dendritic branch.').

**Comment by ukemi** [comment]
Thanks @BarbaraCzub . Can you come up with concrete plans for both of the dendrite terms as a preparation for us doing the actual edits during your training in early October? It would be nice to see which tasks these issues require.

**Comment by BarbaraCzub** [comment]
Ok @ukemi , I will do. 

I think that the term 'dendrite' should refer to a single neuron projection (rather than a branch of projections), so unless anyone vetoes this proposal, our first objective will be to re-define 'dendrite'. 

I'll allocate some time in August to review the dendrite and related terms and draft a plan for making the edits.

**Comment by dosumis** [comment]
dendritic branch points are the points where a dendrite branches in two.  A dendritic spine is not a branch of a dendrite - it is a small, highly dynamic postsynaptic structure that arises from a dendrite.

**Comment by BarbaraCzub** [comment]
We currently have the term 'GO:0044326 dendritic spine neck', which is defined as: 'Part of the dendritic spine that connects the dendritic shaft to the head of the dendritic spine.'

Should we:
1) make “dendritic spine origin” a narrow synonym of 'GO:0044326 dendritic spine neck'? or:
2) create new term “dendritic spine origin” as a part_of child of 'dendritic spine (GO:0043197)' or 'dendritic spine neck (GO:0044326)'? But then what should be the is_a parent? Should these be: 'GO:0120038 plasma membrane bounded cell projection part' and 'GO:0044456 synapse part' as for 'GO:0044326 dendritic spine neck'?

**Comment by slaulederkind** [comment]
I like "create new term “dendritic spine origin” as a part_of child of  'dendritic spine neck (GO:0044326)' and is_a parents 'GO:0120038 plasma membrane bounded cell projection part' and 'GO:0044456 synapse part'.
