### ISSUE TITLE
New taxon constraint: membrane-bound organelles only in eukaryotes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#13925]
currently no TC:

```
[Term]
id: GO:0043227
name: membrane-bounded organelle
namespace: cellular_component
def: "Organized structure of distinctive morphology and function, bounded by a single or double lipid bilayer membrane. Includes the nucleus, mitochondria, plastids, vacuoles, and vesicles. Excludes the plasma membrane." [GOC:go_curators]
subset: gosubset_prok
synonym: "membrane-enclosed organelle" EXACT []
xref: NIF_Subcellular:sao414196390
is_a: GO:0043226 ! organelle
```

Here is an example of an IBA from PAINT to E coli that I think is wrong:
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P00722

(While we're at it, is there any reason why we would annotate directly to an abstract grouping like intracellular-membrane bound organelle?)

Evidence breakdown:

![image](https://user-images.githubusercontent.com/50745/28282337-ee2f29d6-6ade-11e7-852b-34e17fb12b2b.png)

with experimental broken down by species:

![image](https://user-images.githubusercontent.com/50745/28282372-10ace6d8-6adf-11e7-9f46-298f535d8b7d.png)

**Comment by krchristie** [comment]
Hi Chris,

I agree that it makes sense to add the "only in Eukaryota" taxon constraint to the term 'membrane bounded organelle'. As it says in the Wikipedia page for Archaea (https://en.wikipedia.org/wiki/Archaea):

> These microbes (archaea; singular archaeon) are prokaryotes, meaning that they have no cell nucleus or any other membrane-bound organelles in their cells.

I was most of the way through this, when I noticed that this term is currently part of the prokaryotic subset:

> [Term]
> id: GO:0043227
> name: membrane-bounded organelle
> namespace: cellular_component
> def: "Organized structure of distinctive morphology and function, bounded by a single or double lipid bilayer membrane. Includes the nucleus, mitochondria, plastids, vacuoles, and vesicles. Excludes the plasma membrane." [GOC:go_curators]
> **subset: gosubset_prok**
> synonym: "membrane-enclosed organelle" EXACT []
> xref: NIF_Subcellular:sao414196390
> is_a: GO:0043226 ! organelle

so I'd like to include @jimhu-tamu in this discussion since it seems inconsistent to have a taxon constraint that excludes prokaryotes on a term that is in the prokaryotic subset. Jim, any objections to removing this term from the 'membrane bounded organelle' form the prokaryotic subset? It seems like a mistake.

**Comment by krchristie** [comment]
@cmungall - I was also wondering why the annotation to the 'membrane bounded organelle' even shows up in AmiGO. When I look at the current GAF for this family, either in PAINT or directly at the GAF in the SVN repository, I don't see this term at all. Here is what is propagated to the top of the clade that includes beta-galactosidase:

![pthr10066-bgal-propagations](https://user-images.githubusercontent.com/10533218/28376968-5514f6da-6c60-11e7-9354-06e3fc3cd8a1.jpg)

and grepping the GAF directly doesn't find the GO ID for this term (GO:0043227) at all

~/Documents/PAINTcuration/GO-paint/PTHR10066 $ cut -f 5 PTHR10066.gaf | sort -u
!gaf-version: 2.0
GO:0004553
GO:0004565
GO:0004566
GO:0004567
GO:0005764
GO:0005829
GO:0005990
GO:0006027
GO:0006516
GO:0009341
GO:0019391
GO:0046355

**Comment by pgaudet** [comment]
Hi @cmungall 

I sometimes annotate to 'membrane-enclosed organelle' when there are plants in the clade and annotations to both chloroplast and mitochondrion. I find this informative but I agree it's not the most informative term. 

- Pascale

**Comment by cmungall** [comment]
@krchristie - it was in ftp://ftp.pantherdb.org/paint/presubmission/gene_association.paint_ecocyc.gaf.gz until recently. It's gone now (and I also note that this has switched from UniProt IDs to EcoGene IDs). Should be fixed in the next amigo load within a week.

**Comment by krchristie** [comment]
Kind of odd that this has recently changed. The curation on this family isn't new.

**Comment by cmungall** [comment]
My mistake. this is actually do to the switch in source from svn to panther

**Comment by cmungall** [comment]
```
$ curl -L http://www.geneontology.org/gene-associations/gene_association.ecocyc.gz | gzip -dc | grep lacZ | grep  GO:0043231 
UniProtKB       P00722  lacZ            GO:0043231      GO_REF:0000033  IBA     PANTHER:PTN000007197    C       beta-galactosidase      lacZ|b0344|ECK0341      protein taxon:83333     20141113        GO_CENTRAL                PR:P00722
```

So EcoCyc slurped this in from PAINT, don't know when, and we get it from them (PAINTs are not loaded in amigo other than paint_other, we get annotations from MODs etc)

**Comment by pgaudet** [comment]
@krchristie 
I reannotated the tree (but I forgot to update the date in the Google doc). The delay from curation to integration has been very long, it's hard to know where we are at !

**Comment by krchristie** [comment]
@pgaudet I was looking at the SVN log for dates, so it didn't matter what the date in the Google doc was. Leaving out all the touch up and rollbacks of touchback, that just leaves these two commits below.

```
------------------------------------------------------------------------
r28032 | pgaudet | 2015-08-19 05:07:38 -0700 (Wed, 19 Aug 2015) | 1 line

new PAINT annotations
------------------------------------------------------------------------
```

```
------------------------------------------------------------------------
r21583 | huaiyumi | 2014-11-14 10:57:46 -0800 (Fri, 14 Nov 2014) | 1 line

New annotation PTHR10066
------------------------------------------------------------------------
```

**Comment by jimhu-tamu** [comment]
The GO definition of organelle from GO:0043226

> Organized structure of distinctive morphology and function. Includes the nucleus, mitochondria, plastids, vacuoles, vesicles, ribosomes and the cytoskeleton, and prokaryotic structures such as anammoxosomes and pirellulosomes. Excludes the plasma membrane

Based on that, I would consider bacterial thylakoids to be organelles, but interestingly, GO:0009579 ! thylakoid specifically excludes them from being considered organelles. Others include:

- Magnetosomes PMID: 26884433
- Gas vacuoles/vesicles

Looking for more literature and other examples (posted a question on twitter!), but I would hesitate on adding this constraint. Despite wikipedia, to me the fundamental divide is whether the genome is in a nucleus, which is the linguistic root of the "kary" part of prokaryote and eukaryote.

**Comment by jimhu-tamu** [comment]
@krchristie the examples I gave are membrane-bound. The point of going back to the organelle definition is to ask when a membrane-bound compartment with a specialized function is or is not an organelle.

There are a few more here: https://www.ncbi.nlm.nih.gov/pubmed/23615191/

**Comment by cmungall** [comment]
"The traditional view of biology divides living organisms into two major groups, the eukaryotes and the prokaryotes, the former having membrane-bound organelles, the latter lacking them. However, recent research has revealed that this view **is blatantly in error**"

thats me told!

Discussion here, but it doesn't really add anything to the Saier paper:
https://biology.stackexchange.com/questions/54872/why-is-it-said-that-bacteria-have-no-membrane-bound-organelles-when-they-often

OK, so clearly my original request is too strict (though I'm sure we could contort definitions to make it such that we exclude proks). But it's interesting that the only MBO in proks in GO is one that is in error (albeit an error that was fixed at source yet is sticking around). It shows the gaps we would have to fill to improve GO for microbial biology.

Poor microbes are not served well by any biological terminology:
http://bioportal.bioontology.org/search?utf8=%E2%9C%93&query=ammoxosome&button=

Although we don't have a use case for adding these right now, I'm still keen to add them. If someone can send me the Saier paper I may try and make a start on a PR if I get a chance (I don't seem to have institutional access)

**Comment by krchristie** [comment]
@jimhu-tamu - Thanks for the clarification. You had cited the definition of the organelle term, so I misunderstood what you were checking on.

**thylakoids** - I see the comment you refer to on the top level term:

> A thylakoid is not considered an organelle, but some thylakoids are part of organelles.

However, I also see that we have a term for '**bacterial thylakoid**', which is a type of
'**intracellular non-membrane-bounded organelle**'. 
- Is this the correct classification of a bacterial thylakoid? 
- This comment may been to be deleted or revised to be accurate.

**gas vesicle** - We have a term for this. It is also classified as a '**intracellular non-membrane-bounded organelle**', but that seems fine based on the definition.

**magnetosome** - I don't see a term for this. If needed, you can request it.


@cmungall 
> Discussion here, but it doesn't really add anything to the Saier paper:
> https://biology.stackexchange.com/questions/54872/why-is-it-said-that-bacteria-have-no-membrane-bound-organelles-when-they-often

This discussion doesn't add anything new for me, so I'm pretty sure we're handling eubacterial, archaeal, and eukaryotic flagella appropriately in GO, both with respect to the fact that they have completely different structures from each other, and also with respect to the fact that only the eukaryotic flagella (aka cilia) have a membrane bounded portion, though the organelle itself is not considered to be membrane bound as it is not fully enclosed by membrane. With input from Jim to confirm, I've already removed a term that got inappropriately added to GO referring to the cytosolic compartment of the bacterial flagellum.

> OK, so clearly my original request is too strict (though I'm sure we could contort definitions to make it such that we exclude proks). But it's interesting that the only MBO in proks in GO is one that is in error (albeit an error that was fixed at source yet is sticking around). It shows the gaps we would have to fill to improve GO for microbial biology.

By "the only MBO in proks in GO is one that is in error", are you referring to flagella? Paola and I have fixed many errors with the way GO handled these. Please let me know if you see any more.

However, this isn't the only MBO in proks that is handled in GO. We already have these:
- acidocalsisome - conserved from bacteria to humans (https://www.ncbi.nlm.nih.gov/pubmed/15738951)
- pirellulosome - a bacterial specific MBO **(could possibly add a taxon constraint to this term, though it is indicated to be in two phyla, and I haven't looked to see if there is an appropriate grouping term)**


It seems that we already have information that contradicts the idea that it is appropriate to add the 'only in Eukaryota" taxon constraint to the term "membrane-bounded organelle" (GO:0043227).

The only two action items I see still active in this ticket are:

- [ ] possible corrections related to 'thylakoid'
- [ ] possible addition of a taxon constraint to 'pirellulosome'

**Comment by cmungall** [comment]
me:

> But it's interesting that the only MBO in proks in GO is one that is in error

sorry, my mistake, we have other prok MBOs already that appear to be fine, sorry for confusion caused.

> acidocalsisome - conserved from bacteria to humans (https://www.ncbi.nlm.nih.gov/pubmed/15738951)

interesting. We only have bacterial annotation on this so far: http://amigo.geneontology.org/amigo/term/GO:0020022

the paper talks about similarity to GO:0042827 ! platelet dense granule. 


Ruiz, F. A., Lea, C. R., Oldfield, E. & Docampo, R. Human platelet dense granules contain polyphosphate and are similar to acidocalcisomes of bacteria and unicellular eukaryotes. J. Biol. Chem. 279, 44250–44267 (2004).
Shows that human platelet dense granules have morphological and structural similarities to acidocalcisomes, and contain polyphosphate that was released on thrombin stimulation.

I think we should be clear in GO about distinctions between identity, evolutionary relationships and mere structural or functional relationships. Would we use the term "acidocalcisome" for human gene products? It seems not, we'd use the existing dense granule term. It seems some kind of  TC is warranted for acidocalcisome.

Anyway, I think the ticket can be closed. We can open new tickets for new TRs or TCs

**Comment by krchristie** [comment]
From both the acidocalcisome paper I mentioned earlier, and this newer one:

Docampo R, Huang G. Acidocalcisomes of eukaryotes. Curr Opin Cell Biol. 2016
Aug;41:66-72. doi: 10.1016/j.ceb.2016.04.007. Epub 2016 Apr 25. Review. PubMed
PMID: 27125677

it is pretty clear that people do refer to acidocalcisomes of eukaryotes, so I don't think any TC is warranted here. It might even be that 'platelet dense granules' could be considered a specialized type of acidocalcisome, but I don't feel the need to read enough to be sure. I'll just leave it as is.

I will close this ticket and open new ones for the couple bacterial issues I mentioned earlier.
