### ISSUE TITLE
GO:0097754 Name	clathrin-mediated membrane bending

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13922]
missing parent
GO:0048268 clathrin coat assembly

>

or at least there is no link between the membrane bending part and the broader pathway

**Comment by ukemi** [comment]
There is:

'clathrin-mediated membrane bending' has_part 'clatrhin coat assembly'

and

'clathrin coated pit assembly' has_part 'clathrin coat assembly'
'clathrin coated pit assembly' has_part 'membrane invagination'

should probably change to:
'clathrin coated pit assembly' has_part 'clathrin-mediated membrane bending'

That would bring in both the membrane bending and coat assembly parts.

**Comment by ValWood** [comment]
I think this is probably wrong.

bending is part_of assembly
the bending part is really a Molecular Function, I'm convinced:
https://github.com/geneontology/go-ontology/issues/13024#issuecomment-316634820

**Comment by pgaudet** [comment]
See also #13916 
These are very related - @ukemi : perhaps the same person should deal with all 3 ? 

Thanks, Pascale

**Comment by ukemi** [comment]
OK. Assigning all to you. I will mark you off on the rota.

**Comment by pgaudet** [comment]
@ValWood there are no annotations to 'clathrin-mediated membrane bending' - I can obsolete or merge into the parent ('membrane bending'). The 'clathrin-mediated' part is just an annotation, isn't it ? 

Pascale

**Comment by ValWood** [comment]
Probablhy.

I think we could tidy "membrane bending" stuff on Monday
should be considered with:

https://github.com/geneontology/go-ontology/issues/13024
and
https://github.com/geneontology/go-ontology/issues/14593

I daren't say it, but I think this should be relativly easy to sort ;)

but the outcome of these tickets would affect  whether we even keep this term in process.

**Comment by ValWood** [comment]
Not sure that this is correcct, but there are open tickets for a larger review of membrane bending, so closing
