### ISSUE TITLE
GO:1905224 clathrin-coated pit assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13923]
Is described as a "membrane assembly", that doesn't seem right? it happens to a membrane but the membrane is already there?

**Comment by ValWood** [comment]
Thats why curators use the "Quick fix label" its a "hey look I'm quick to fix" , we just use it as a way of shouting....So you can stop us by removing it, and we don't need to preserve any historical usage.... it has no real  administrative use.

**Comment by pgaudet** [comment]
The problem seems to be this: 
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4782928/37354128-33c47af0-26e1-11e8-8729-435312aaa76c.png">

But probably 'membrane region' shoud be 'part of' membrane', not 'is a membrane'??? 
@ukemi

**Comment by pgaudet** [comment]
membrane region is a membrane AND a membrane part 
<img width="703" alt="image" src="https://user-images.githubusercontent.com/4782928/37354345-bb19ebca-26e1-11e8-803f-a7184ded71fa.png">


Is this OK ?

**Comment by pgaudet** [comment]
If I make 'clathrin-caoted pit' 
is_a membrane part, rather than is_a membrane region, then we loose the incorrect inference: 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/4782928/37354601-52f3b692-26e2-11e8-9bda-f773d56bbf3f.png">
