### ISSUE TITLE
Collect tickets for Barbara's training

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#13931]
We need to have an example of at least a new term request, an existing term edit, a term merge and a term obsoletion. 

1. #13927  New Term
2. #13785 Term Edits
3. #13760 New Term
5. #13886   #14218  Addition of a term to a subset
6. #14021 Obsoletion
7. #14270 New Regulation Term

**Comment by BarbaraCzub** [comment]
Hi @ukemi there is this ticket #13907 with terms, which I requested, both of which will have to be obsoleted, as one is a synonym of an existing term 'membrane bussing', and the other happens inseparably from 'vesicle scission' (I have already requested a definition update to clarify this #13915, but I see this ticket is still open, so it could become another one of my Term Edits). 

@hdrabkin suggested he would deal with the obsoletions asap (although a discussion is still ongoing about changing the name of the term 'membrane budding', so perhaps this could be another Term Edit for my training?), but if the obsoletion could wait, then these could be my terms to practice on. However, the risk is that someone will use these terms for making annotations in the meantime... What would we do then? 'Move' the annotations to the pre-existing synonymous term(s)? Or would this become a Term Merge task?

**Comment by hdrabkin** [comment]
Due to the complex discussion, I have been holding off. If the terms do get used, then an email will need to get sent out, etc.  
However, if the terms get used, we will then need to issue standard email, etc. But we could use your training dates as the obsoletion date.

**Comment by ukemi** [comment]
So is the obsoletion still under discussion? If so then you can continue. If the terms are ready to be obsoleted, from now until the meeting is a long time to wait. How will we keep people from using them for annotation, we can add a 'do not annotate' tag? Does that generally work?

**Comment by BarbaraCzub** [comment]
There is no question about obsoleting 'NTR2 vesicle fusion involved in vesicle assembly', as apparently this happens spontaneously during 'vesicle scission' by default, which is supposed to be reflected in the updated definition #13915 .

Based on where the discussion is heading, I think 'NTR1 vesicle assembly/formation' will also have to be obsoleted, as apparently, it is an exact synonym of 'membrane budding'. If the term name gets changed from 'membrane budding' to 'vesicle budding from membrane', as @dosumis and @RLovering proposed, then the ontology will become clearer.

**Comment by hdrabkin** [comment]
So I think then the best thing going forward here is that I get rid of both now; Waiting for almost two months is risky.
I could effect the name change of membrane budding also. 
I'd at least like the get the obsoleting done by today.
