### ISSUE TITLE
"protein anchor" is restricted to membrane anchoring

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13933]
spotted this outstanding part of  this closed ticket:
https://github.com/geneontology/go-ontology/issues/13348#issuecomment-294179238

It seems strange that we have a MF term for "protein anchor" which is restricted to "anchoring to membrane" but we have "anchoring" process terms which apply to the cortex. It seems that we could use the MF term "protein anchor" to apply to gene products that function as protein anchors in contexts other than "anchoring to membrane".

Suggest that the term name of "protein anchor" is revised to "extrinsic membrane protein anchor" or something else specific to this particular context ?

**Comment by hdrabkin** [comment]
has it been used only for membrane protein contexts?

**Comment by ValWood** [comment]
actually it' a mixture of problems

we have process terms for cortical anchoring
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0032065

but function terms for membrane anchoring....
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0043495

 we need to decide if it's a process of a function and bring together different types of "anchor protein". This probably comes under "MF refactoring" umberalla?

**Comment by hdrabkin** [comment]
Not sure if it will come under MF refactoring. I am hesitant to change any term name without first knowing if the term has been used only in the context of the name it will be changed to. Otherwise, annotations have to be re-considered.

**Comment by hdrabkin** [comment]
I would think the function term '"membrane protein anchor" would have a relationship to 

maintenance of protein location in membrane
Any process in which a protein is maintained in a specific location in a membrane, and is prevented from moving elsewhere.
is-a 	 maintenance of protein location in cell  			     			      
part of  protein localization to membrane
Biological Process
GO:0072658

**Comment by hdrabkin** [comment]
Perusing  the current annotations in Amigo, one will need to look at the papers to confirm these are used in the context of anchoring to a membrane;
Excluding the IEA annotation, there are around 319 coming from the PAINT pipeline, and about 41 with some sort of experiment based annotation; a few TAS, and some orthology based.

If we change the name, do we need a "cortex anchor" function term (or maybe 'non-membrane protein anchor; 
A problem is "cell cortex" sounds very very close to the plasma membrane: 'The region of a cell that lies just beneath the plasma membrane and often, but not always, contains a network of actin filaments and associated proteins'

**Comment by ValWood** [comment]
GO:0043495
--
Name | protein anchor
Ontology | Molecular Function
Definition | Interacting selectively and non-covalently with both a protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location.

Because this is defined  as anchring to a membrane, I think we have to assume that it has been used correctly for "anchoring to membrane"

However this is not the ONLY type of protein anchor.
I think the best thing to do right now is  just to  rename
"protein anchor" to "protein membrane anchor"

This means that the term name matches the definition more closely and it will be less likely to be used incorrectly.

This also frees up "protein anchor" for if we want a grouping term later for "anchors"
like "coritical anchors".

Then you could close this one and we could revisit later  in the context of "is anchoring a function or a process" !

**Comment by hdrabkin** [comment]
done
