### ISSUE TITLE
regulation of GABA-A receptor activity

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13930]
I would like to see “regulation of GABA-A receptor activity” added as a child term of “regulation of anion channel activity (GO:0010359).  Definition could be “Any process that modulates the frequency, rate or extent of GABA-A receptor activity.” “positive…” and “negative…” children of “regulation of GABA-A receptor activity” are also needed. Synonyms: regulation of ionotropic GABA receptor activity, positive…, negative…  PMID:24044036

**Comment by hdrabkin** [comment]
done
