### ISSUE TITLE
unsatisfiable ontology classes causing Jenkins GAF build failure

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#13935]
I just committed an updated GAF for PomBase, and its build has failed in Jenkins because of unsatisfiable classes in the ontology. I hope it's obvious that this isn't something we can fix at the GAF level ;)

I'm attaching a list of the errors (copied from the console output for PomBase GAF build 121 at http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/). The offending terms aren't even ones we would ever use for fission yeast.

**Comment by ukemi** [comment]
I don't see this in the editor's version of the ontology. When I load go-edit.obo into Protege and run the reasoner, there are no 'nothing' classes. 
I spot checked some of the terms on the list in the Jenkin's report and they seem fine. Could this be related to the switch to the CARO anatomical structure?
@cmungall any ideas?

**Comment by mah11** [comment]
Oh goody, a sneaky one! On the off-chance that it helps any: I also get similar results if I run owltools locally, but it doesn't flag all of the same terms (misses a handful, perhaps because of an update lag somewhere?).

oh, and here's the file I meant to attach earlier ...
[pb_gaf_build_121_errors.txt](https://github.com/geneontology/go-ontology/files/1159312/pb_gaf_build_121_errors.txt)

**Comment by ukemi** [comment]
From the GO build console output (build-go-ontology/733):

go-edit.obo-check.tmp go-edit.obo-check
 :: ERROR: Undeclared relation: RO:0002015
  :: ERROR: Undeclared relation: RO:0002013
 Makefile:133: recipe for target 'go-edit.obo-check' failed
make: *** [go-edit.obo-check] Error 2
Build step 'Execute shell' marked build as failure

**Comment by ukemi** [comment]
RO:0002013= 'has regulatory component activity'
RO:0002015= 'has positive regulatory component activity'

This might be unrelated to the above error.

**Comment by cmungall** [comment]
We don't do a full integration test with the travis checks, just against the local cl module, which may be out of sync. We should probably do both.

Currently this job tests go-gaf, which is the importer ontology that uses all of cl and is used by owltools for gaf checks. It is consistently passing so need to explore more what is happening here

**Comment by cmungall** [comment]
I debugged using the unsat module core dump that gets created:

![image](https://user-images.githubusercontent.com/50745/28385334-9658e018-6c7c-11e7-9bfa-3cf0cab0e2d6.png)

Same as noted here and subsequently fixed: https://github.com/geneontology/go-ontology/issues/13898

So this is a file sync issue, investigating...

**Comment by ukemi** [comment]
Can/should we put this kind of debugging on the agenda for August? Where is the unsat core dump file that you loaded into Protege?

**Comment by cmungall** [comment]
Can certainly do that but this particular issue is caused by the fact

https://github.com/geneontology/go-site/issues/414

**Comment by cmungall** [comment]
OK, turned out the cause was really dumb

The correct PURL is
http://purl.obolibrary.org/obo/go/imports/x-disjoint.owl


go-gaf was importing

http://purl.obolibrary.org/obo/go/extensions/x-disjoint.owl

which was the old PURL. There was a stale copy there.

The snapshot ontology should be fixed tonight. Then the subsequent gaf build should succeed.
