### ISSUE TITLE
Protein crotonylation and protein butyrylation

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#13937]
Hi, 
I would need a series of terms for a number of protein acyltransferase activities. It looks like protein acetylation is not the only protein acylation and that other acylation modifications are present on lysines

I have a mixed feeling concerning creating specific terms for histones. We did that in the past, but on the other hand, histones are proteins and most enzymes have non-histone substrates

Thanks

Sylvain

1)

Name: Protein crotonyltransferase activity
Category: Function
Definition: Catalysis of the reaction: crotonyl-CoA + lysine in peptide = CoA + N-crotonyl-lysine-peptide.
Child of GO:0016410 N-acyltransferase activity
PMID:25818647

2)
Name: Protein butyryltransferase activity
Category: Function
Definition: Catalysis of the reaction: butyryl-CoA + lysine in peptide = CoA + N-butyryl-lysine-peptide.
Child of GO:0016410 N-acyltransferase activity
PMID:27105113

3) 
Name: peptidyl-lysine crotonylation
Category: Process
Definition: The crotonylation of peptidyl-lysine. 
child of GO:0043543 protein acylation 
PMID:25818647

4) 
Name: peptidyl-lysine butyrylation
Category: Process
Definition: The butyrylation of peptidyl-lysine. 
child of GO:0043543 protein acylation 
PMID:27105113

We migh also create specific terms for histone crotonyltransferase activity and histone butyryltransferase activity, but I am unsure that we should systematically create specific terms for histone modifications since in most cases, enzymes also modify non-histone proteins 

5)
Name: histone crotonyltransferase activity
Definition: Catalysis of the reaction: crotonyl-CoA + histone = CoA + crotonyl-histone. 
child of Protein crotonyltransferase activity
PMID:25818647

6)
Name: histone butyryltransferase activity
Definition: Catalysis of the reaction: butyryl-CoA + histone = CoA + butyryl-histone. 
child of Protein butyryltransferase activity
PMID:27105113

**Comment by pgaudet** [comment]
Hello @sylvainpoux 

I created the following terms: 
[Term]
+id: GO:0140064
+name: peptide crotonyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: crotonyl-CoA + lysine in peptide = CoA + N-crotonyl-lysine-peptide." [PMID:25818647]
+synonym: "protein crotonyltransferase activity" RELATED []
+is_a: GO:0008080 ! N-acetyltransferase activity
+created_by: pg
+creation_date: 2017-07-20T16:40:57Z
+
+[Term]
+id: GO:0140065
+name: peptide butyryltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: butyryl-CoA + lysine in peptide = CoA + N-butyryl-lysine-peptide." [PMID:27105113]
+synonym: "protein butyryltransferase activity" RELATED []
+is_a: GO:0008080 ! N-acetyltransferase activity
+created_by: pg
+creation_date: 2017-07-20T16:46:49Z
+
+[Term]
+id: GO:0140066
+name: peptidyl-lysine crotonylation
+namespace: biological_process
+def: "The crotonylation of a lysine residue in a protein. Crotonyl is the univalent radical CH3-CH=CH-CO- derived from crotonic acid." [PMID:25818647, Wikipedia:crotonyl]
+is_a: GO:0043543 ! protein acylation
+created_by: pg
+creation_date: 2017-07-20T16:48:58Z
+
+[Term]
+id: GO:0140067
+name: peptidyl-lysine butyrylation
+def: "The butyrylation of a lysine residue in a protein. Butyryl is the univalent radical C3H7COO- derived from butyric acid." [PMID:27105113, Wikipedia:butyryl]
+is_a: GO:0043543 ! protein acylation
+created_by: pg
+creation_date: 2017-07-20T16:52:19Z
+
+[Term]
+id: GO:0140068
+name: histone crotonyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: crotonyl-CoA + histone = CoA + crotonyl-histone." [PMID:25818647]
+is_a: GO:0140064 ! peptide crotonyltransferase activity
+created_by: pg
+creation_date: 2017-07-20T16:55:16Z
+
+[Term]
+id: GO:0140069
+name: histone butyryltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: butyryl-CoA + histone = CoA + butyryl-histone." [PMID:27105113]
+is_a: GO:0140065 ! peptide butyryltransferase activity
+created_by: pg
+creation_date: 2017-07-20T16:56:33Z
+


A few comments: 
1. I modified the name of 'protein crotonyltransferase activity' and 'protein butyryltransferase activity' to peptide to match the neighboring terms. I added your term names as synonyms. 

2. Do you think we should create a general parent 'peptide N-acyltransferase activity' to group all these related modifications ? 

Thanks, Pascale
