### ISSUE TITLE
Add parent GO:0008047 enzyme activator activity to "adenylate cyclase activator activity"

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13947]
Add parent GO:0008047 enzyme activator activity to "adenylate cyclase activator activity"

**Comment by Antonialock** [comment]
@ValWood maybe this is already in one of the million other github tickets about this pathway...it is late...

gpa2 currently only has "protein binding" with adenylate cyclase 

I was going to use this term + extensions:
has_substrate cyr1
involved_in adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway

the "adenylate cyclase-activating" part of the GO term seems ridiculously redundant if adenylate cyclase is already annotated to the pathway?

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/1630
you need to use the MF term "adenylate cyclase activator activity" 

>the "adenylate cyclase-activating" part of the GO term seems ridiculously redundant if adenylate cyclase is already annotated to the pathway?

I am so glad you said that. I am just writing a GO ticket about it!

**Comment by ValWood** [comment]
Oh this is the GO tracker!

but the term you want already exists
GO:0010856 | adenylate cyclase activator activity
-- | --

**Comment by Antonialock** [comment]
oh, I really couldn't find that last night...nevermind me

**Comment by ValWood** [comment]
Well nobody else did, as it has never been used for annotation of any adenylate-cyclase activating GPCR!

**Comment by Antonialock** [comment]
It needs the parent GO:0008047 enzyme activator activity
