### ISSUE TITLE
inconsistency in handling thylakoid terms wrt being organelles or not

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#13958]
As discussed in https://github.com/geneontology/go-ontology/issues/13925, there is an inconsistency in how GO refers to thylakoids. @jimhu-tamu please comment on this ticket instead of the previous one where we've rejected the proposal to add a taxon constraint to the term 'membrane bounded organelle'.

In one place, we say that thylakoids are NOT organelles:
**thylakoid (GO:0009579)**
**Comment**: A thylakoid is not considered an organelle, but some thylakoids are part of organelles.

but in another place, we say that this type is an organelle:
**'intracellular non-membrane-bounded organelle'**
is_a **'bacterial thylakoid'**

- Is this the correct classification of a bacterial thylakoid?
- If yes, then the on the term 'thylakoid' should be deleted or revised to be accurate.

**Comment by krchristie** [comment]
This review (PMID:20739411 : https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2944366/) supports the classification of 'bacterial thylakoid' as an 'organelle', but we have 'bacterial thylakoid' as a subclass of 'intracellular non-membrane-bounded organelle'. It describes 'photosynthetic membranes' as  `perhaps the most thoroughly studied of all prokaryotic organelles`, and then lists three types of them in prokaryotes:
- **chromatophores**, contains the various intracytoplasmic membrane (ICM) structures that house the photosynthetic protein complexes of the purple photosynthetic bacteria. 
- **thylakoid membrane compartments** found in cyanobacteria. 
- **chlorosome compartments** of green photosynthetic bacteria 

What we have is a little bit confusing, but does not seem to be consistent with the idea that 'bacterial thylakoids' are considered to be organelles, so it looks to me like some reorganization is needed. 

@jimhu-tamu - please comment if you have any input on this. I also might seek input from the authors of the review cited above.

**Comment by pgaudet** [comment]
Made 'thylakoid' is_a 'intracellular non-membrane-bounded organelle'
