### ISSUE TITLE
term additions to pombe slim

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13970]
GO:0140056 organelle localization by membrane tethering
GO:0006915 apoptotic process
GO:0006797 polyphosphate metabolic process
GO:0006790 sulfur compound metabolic process
GO:0016073 snRNA metabolic process
GO:0055065 metal ion homeostasis

Hi,

Could these be added to the PomBase slim set?
Thanks

Val

**Comment by ukemi** [comment]
@ValWood 

How soon do you need this? If you can wait until the GOC meeting, we can put it as a training task for @BarbaraCzub. We are looking for examples of the various editing tasks that she will need to accomplish.

**Comment by ValWood** [comment]
I'm doing some analysis for a paper on unknown (unstudied) genes.
I need to crosscheck with non-slimmed. So  I need it as soon as possible.
I'm sure I can find some more for @BarbaraCzub by October :)

**Comment by ValWood** [comment]
Thanks!
