### ISSUE TITLE
G-protein complex cycle / G-protein complex assembly / G-protein disassembly

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#13978]
Reading up a bit more about GPCR signaling, I noticed that there are two GO terms that are not directly related:
* GO:0031684 heterotrimeric G-protein complex cycle (*now obsolete*)
"The series of molecular events that generate a signal through the activation of G-protein subunits and recycling of these subunits"
6 EXP annotations. The def seems very vague what it means
* GO:1902605 heterotrimeric G-protein complex assembly
"The aggregation, arrangement and bonding together of a set of components to form a heterotrimeric G-protein complex."
1 EXP annotation. Def also very vague
* There is no term like ' heterotrimeric G-protein complex disassembly (or disassociation)

* GO:1902605 heterotrimeric G-protein complex assembly is not a child of GO:0031684 heterotrimeric G-protein complex cycle. Shouldn't is be?
* At least from the GPCR perspective, the disassembly of G-proteins is separation into Galpha/GTP from Gbeta/gamma upon the agonist binding to the GPCR. The reassembly of the two depends on RGS (regulators of G-protein signaling) so Galpha/GDP can reassociate with Gbeta/gamma. 
* Not sure this is too specific to capture each individual step, but the low number of annotations to the above terms let's me think that GPCR signalling is the most studied in Dicty and human neutrophils, and we might need to refigure this part of the GO. 
I annotated Dicty carA yesterday with GO:0031684 heterotrimeric G-protein complex cycle as it's the only term available, but the definition is disappointing. CAR1 functions, aside from being the receptor for cAMP as a GEF to convert the Galpha from GDP to GTP so it disassociate

**Comment by ValWood** [comment]
GO:0031684 heterotrimeric G-protein complex cycle

I think this term should be obsoleted and we just curate the individual steps. This seems to be a slightly arbitrary grouping.

Val

**Comment by pgaudet** [comment]
Obsoletion notice for GO:0031684 'heterotrimeric G-protein complex cycle' sent.

**Comment by RLovering** [comment]
Hi Pascale

I have raised this concern before and I  thought you had agreed to list the databases affected by obsoletion of terms, as has been done previously. If you don't do this then all groups are wasting time checking to see if their annotations are included. In this instance there are 8 annotations, not 6. I don't know the handle for the people at AspGD and IntAct responsible for checking changes in GO.

3 SGD @srengel 
2 DictyBase @pfey03 
1 AspGD
2 IntAct 

@ukemi 

Thanks

Ruth

**Comment by dosumis** [comment]
Isn't this a fundamental part of the GPCR signaling pathway?

**Comment by pgaudet** [comment]
Hi @RLovering 

Apologies, I updated the documentation, hopefully next time I'll remember to include the information !

Cheers, 

Pascale

**Comment by pgaudet** [comment]
@dosumis 
The definition of this term is vague. For the recycling part of the definition, that's a spontaneous reaction (GTP on the Galpha subnit eventually gets hydrolyzed). The other part of the definition, "The series of molecular events that generate a signal through the activation of G-protein subunits", overlaps with the more general term "G protein-coupled receptor signaling pathway". 

What do you think ?

**Comment by ValWood** [comment]
Also a lots f things are "cycles" but we don't represent them this way.

CCing @Antonialock  who has a more in depth understanding of GPCR signalling than me, but the term seems redundant with existing F-P combinations to me.

**Comment by pgaudet** [comment]
@ValWood 
I agree
For example the mismatch repair proteins work the same way, and we don't have these types of terms. 

Pascale

**Comment by pgaudet** [comment]
@pfey03 
- 'GO:1902605  heterotrimeric G-protein complex assembly ' should not be part of G protein coupled signaling pathway. If you look at the cited reference what is being described really is a chaperone that contributes to the assembly of the complex, independent of the signaling. 

- We may want to add 'G protein complex disassembly' - I have put the parent class 'protein complex assembly' in my model (http://noctua.berkeleybop.org/editor/graph/gomodel:5970219a00000486). To discuss.

Thanks, Pascale

**Comment by pgaudet** [comment]
HI @pfey03 
If it's ok with you I'll close this one. The mouse paper showing the role of a chaperone in  heterotrimeric G-protein complex assembly justified the term (PMID:23637185). 

I think the disassembly occurs without a protein mediating it, when the ligand binds the receptor, so I dont think disassembly is needed. 

OK ? 

Thanks, Pascale

**Comment by pfey03** [comment]
Hi @pgaudet,

Yeah, I think that's fine. It's also with carA they did FRET and stuff but how exactly it disassembles it's not known but the car receptor is part of it. I guess it's ok closing it. Thanks!
