### ISSUE TITLE
GO:0019538 protein metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13988]
is defined as
The chemical reactions and pathways involving a specific protein, rather than of proteins in general. Includes protein modification.

What does the phrase "involving a specific protein, rather than of proteins in general" mean?
What is excluded by this clause, it isn't clear to me.

(comes via a collaborator question how to describe protein related processes)

**Comment by hdrabkin** [comment]
We THINK that the term and its children iwas meant to be used to describe things that happen to a specific protein rather than "things that can happen to any/all proteins".

**Comment by ValWood** [comment]
What does that mean though- I don't understand? Everything protein related is underneath it (translation etc).

Can you provide an example of something that happens to a single protein vs. something that happens to many proteins? Please explain to me in small words :)

**Comment by hdrabkin** [comment]
@ukemi , to you want to take a crack at this? It comes from the mind of MA!

**Comment by ukemi** [comment]
I suspect that the clause was added to the definition back when were were thinking a lot about instances of the terms in the ontology. If you think about this term with respect to a single process that is made up of molecular functions, you should think about it with respect to a process that happens to a single type of protein, not a process that happens to a population of different proteins.

**Comment by pgaudet** [comment]
Hi, 

So does that mean that this part of the definition should be removed ? Otherwise some clarification would be nice !

**Comment by hdrabkin** [comment]
Changed def to
The chemical reactions and pathways involving a protein. Includes protein modification

**Comment by pgaudet** [comment]
Hi @hdrabkin , 

I wonder if this definition may not be mistakenly taken to also include the enzymatic activities of proteins themselves.

How about: The chemical reactions in which a protein is the substrate, including synthesis, degradation, maturation and modification. 

What do you think ? @ukemi @ValWood

**Comment by hdrabkin** [comment]
I don't think a  protein is a substrate of its synthesis; it's a product. 
It's a substrate  for maturationand modification and a substrate for its degradation?

**Comment by ValWood** [comment]
That sounds much clearer to me!

Maybe based on H. comment

 The chemical reactions in which a protein is synthesized,  or is the substrate.
