### ISSUE TITLE
TPV autophagosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13982]
Is part_of vacuole?

**Comment by ukemi** [comment]
It is_a vacuole. I certainly don't think part_of. That doesn't make sense. 

@marcfeuermann @Pauldenny  ?

**Comment by ValWood** [comment]
OK I didn't realise it was a vacuole. I thought it fused with a vacuole. Ignore...

**Comment by ukemi** [comment]
It does fuse with a vacuole, but I think it was decided that it was a type of vacuole as well. The others will remember better than me.

**Comment by ukemi** [comment]
In fact if I am not mistaken it is also called an autophagic vacuole.

**Comment by ValWood** [comment]
It might cause problems...
It will make it difficult to separate "autophagosome"  annotations from "vacuole proper"

**Comment by ValWood** [comment]
So autophagosome fits the definition of vacuole.

but autophagosome is defined
A double-membrane-bounded compartment that engulfs endogenous cellular material as well as invading microorganisms to target them to the vacuole/lysosome for degradation as part of macroautophagy. 

So I think you need to clarify/differentiate  the term for the "main vacuole" in some way?
that the autophgosome is fusing with in some way?

**Comment by ValWood** [comment]
OK, we already have such a term

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000323
lytic vacuole.

and I need to make sure all our annotations are to "fungal-type vacuole" which is under "lytic vacuole" and then all will be fine.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000324

Could you change the autophagosome def to say that it fuses with a "lytic vacuole"?

**Comment by marcfeuermann** [comment]
I do not remember what was decided about this. Following the definition of a vacuole in GO, it could indeed correspond to a vacuole.
But I think 2 "little" concerns to make the story more complicated :
- It has a double membrane, so it is not a "classical" vacuole, 
- In fungi and plants, the vacuole is considered as the same as the animal lysosome. In this sens it is not a vacuole, but fuses with the lysosome/vacuole to deliver it's content.

**Comment by marcfeuermann** [comment]
Oups, Val you were quicker than me.

**Comment by ukemi** [comment]
I think the definition tweak,  fuses with a lytic vacuole, will solve all of this.
