### ISSUE TITLE
NTR cell cycle switching terms

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13989]
Hi, 

I would like to request the term
1. negative regulation of cell cycle switching, mitotic to meiotic cell cycle (GO:0051728 )
for pombe pat1(aka ran1) 
2. signal transduction (GO:0007165) involved in cell cycle switching, mitotic to meiotic cell cycle

standard defs...

e.g. see PMID:17674143

cheers
Antonia.

**Comment by vanaukenk** [comment]
@Antonialock   Quick question: 

Would it be correct to make 'signal transduction involved in cell cycle switching, mitotic to meiotic cell cycle' a child of 'intracellular signal transduction' (GO:0035556), or do you just want it to be a direct child of 'signal transduction ' (GO:0007165)?

**Comment by Antonialock** [comment]
yes cheers, intracellular

**Comment by vanaukenk** [comment]
Still need to add signal transduction terms.  Will do that tomorrow.

**Comment by vanaukenk** [comment]
Signal transduction term now added.
