### ISSUE TITLE
Create and display a GO slim on the GO site based on the AGR slim

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13996]
1. PIs need to define the requirements and the priority. 
2. We need Mary D to dedicate some time
3. We need to involve other groups to ensure that the slim represents all species (TAIR, dictyBase, Gramene, etc).

**Comment by mdolanme** [comment]
Following the annotation call at which I presented our GO slim generation method, I was in touch with Kimberly about 'orphan' WormBase genes. As part of out exchanges I sent her a graph comparing the experimental annotations of those genes with the proposed AGR-GO slim. I also generated graphs for TAIR 'orphan' annotations so I think that might be a good starting point for #3.

**Comment by ValWood** [comment]
For coverage of cellular phenotypes check out 
http://pombase2.aska.gen.nz/browse-curation/fission-yeast-go-slim-terms
(its easy to see where you need to go up the graph to lump (eg. RNA metabolism/ transport terms). I think this is probably very close to what you have in AGR slim. 
I introduced a couple of things recently  like "detoxification" (which has a number of genes which do not slim any other way).
The pombe process slim now covers 99.4% of  all non- root node process annotations (with very specific, biologically relevant terms. For example, we have excluded  "protein modification" terms which are really molecular functions in the process ontology.

A  GO  term for  "protein quality control" would help further.
https://github.com/geneontology/go-ontology/issues/13944

**Comment by ValWood** [comment]
Where can I get the AGR slim terms from again?

**Comment by ukemi** [comment]
Try this ticket. #13791

**Comment by selewis** [comment]
Hi Val,

Here is the link to the current active AGR slim. The one Mary produced was
too long to be practical (needs to fit within the width of a typical
browser page).  https://github.com/geneontology/ribbon/tree/master/src/data

The original one from Mary is also there ("jax.js") and the one currently
in use by FlyBase (fly.js). etc...

**Comment by ValWood** [comment]
OK thanks, I see there are a few different ones.

I think the AGR ribbon slim and the generic slim have different purposes. I'm thinking more about the generic slim, just trying to illustrate some consequences of very broad terms which aren't so  biologically meaningful  (but does not affect AGR use of high level terms).

**Comment by ValWood** [comment]
Is this ticket in date?
If so who should it be assigned to?

**Comment by thomaspd** [comment]
The AGR slim is available for download at http://geneontology.org/docs/download-ontology/#subsets, and we're having ongoing discussions about how to integrate the GO ribbon on the GO site, so I think this ticket can be closed. Any objections?

**Comment by pgaudet** [comment]
OK to close, and open in a different tracker - this is not an ontology ticket anymore.
