### ISSUE TITLE
N-terminal acetylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13990]
Up until now this modification is considered to be irreversible.
Should we therefore, for GO purposes, classify as a type of "protein maturation"?

I ask because at present  Pombe N-acetyl transferases are unslimmed because of pleiotropic effects it is difficult to assign to a process other then "N-terminal acetylation". We purposely exclude "modification" terms from our slim (as they are not informative about the actual biological role)

A recent review

http://www.cell.com/trends/biochemical-sciences/fulltext/S0968-0004(12)00018-7?_returnURL=http%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0968000412000187%3Fshowall%3Dtrue

N-acetylation is hitherto considered irreversible....

and

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4140192/

Thus, N-terminal acetylation, like initiator methionine removal, is a component of the basal maturation pathway for nascent polypeptides.3
Despite this widespread, constitutive and seemingly irreversible transfer pathway, loss of N-terminal acetylation induces an array of distinct phenotypes.

Many sources seem to refer to n-terminal acetylation as a type of "protein-maturation"

**Comment by ukemi** [comment]
It seems like this review implies that the acetylation is often adding a signal to the protein for further downstream processes like degradation. I'm not sure this would be considered maturation.

**Comment by pgaudet** [comment]
Hi @ukemi  @ValWood 
Looking at the papers Val mentioned, wikipedia and pubmed (24555563), based on current knowledge I agree N-term acetylation could be viewed as  protein maturation. The known roles are: 
1. It's non-reversible
2. It may be the basis of the N-terminal stability rule
3. Degradation could be a QC or regulatory process
All these could be considered protein maturation; couldn't they? 

Pascale

**Comment by pgaudet** [comment]
@ukemi @ValWood (+ anyone else) if you can comment - my inclination would be do do what Val suggests and add the parent 'protein maturation'.

**Comment by ukemi** [comment]
If it serves as a degradation signal, is that really maturation?

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/20110468

implies that to function as a degron it needs to be ubiquitinated, so this is like any other intrinsic sequence acting as a ubiquitination site. 

I still think its maturation if its added to form the functional protein, and never removed....

**Comment by ukemi** [comment]
OK
