### ISSUE TITLE
positive regulation of induction of conjugation with cellular fusion by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13995]
Hello, 
Can I please request

positive regulation of induction of conjugation with cellular fusion by positive regulation of transcription from RNA polymerase II promoter

(child of 
positive regulation of induction of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter)
PMID:22144909
cheers

**Comment by pgaudet** [comment]
I thought we were not creating those terms anymore ?

**Comment by ukemi** [comment]
This term is a GO-CAM model in a single term.

**Comment by ValWood** [comment]
Yes we can post compose this....

**Comment by vanaukenk** [comment]
@Antonialock @ValWood 

Should I close this ticket? 

I did see that the corresponding negative regulation term exists already in the ontology:

http://amigo.geneontology.org/amigo/term/GO:1902625

Did you want to post-compose that term, as well?

Thx.

**Comment by ValWood** [comment]
We can do....Historically we used to request terms for  regulatory processes  if they were regulated transcriptionally (rather than post-transcriptionally). Is there  a plan to obsolete existing terms like this?

**Comment by pgaudet** [comment]
Not really but there is a related issue: #13166

**Comment by vanaukenk** [comment]
Okay, I am closing this ticket for now.  If we need to re-visit, just let me know.  Thx.
