### ISSUE TITLE
polyamine deacetylation NTRs

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#13997]
Synonyms:   acetylpolyamine deacetylation
Def:The modification of acetylpolyamine by the removal of acetyl groups. 
is_a   macromolecule deacylation GO:0098732
is_a polyamine metabolic process GO:0006595 
PMID: 28516954

NTR spermidine deacetylation
synonym:N^8-acetylspermidine  deacetylation 
Def:The modification of acetylspermadine by the removal of acetyl groups. 
is_a polyamine deacetylation 
is_a spermidine metabolic process GO:0008216
PMID:28516954

From the literature I can find the N^1-acetylspermidine is converted to putriscine
PMID:    3955076 and PMID:28516954

**Comment by hdrabkin** [comment]
done
