### ISSUE TITLE
NTR: (3S)-(+)-asterisca-2(9),6-diene synthase activity

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#14003]
Hello:

I would like to submit a NTR for the molecular function (3S)-(+)-asterisca-2(9),6-diene synthase activity. Please let me know if you have any questions. 

Bob Dodson

Name: (3S)-(+)-asterisca-2(9),6-diene synthase activity
Ontology: function
Synonyms: asterisca-2(9),6-diene synthase activity
Definition: Catalysis of the reaction: 2-trans,6-trans-farnesyl diphosphate = diphosphate + (3S)-(+)-asterisca-2(9),6-diene
CHEBI:137531
Child of: GO:0010334 sesquiterpene synthase activity

References:
PMID:27862766 Terpene Cyclases from Social Amoebae.

**Comment by krchristie** [comment]
I've put this in pretty much as requested.

I've chosen "BROAD" as the synonym type, rather than "EXACT", as this synonym would be equally appropriate if there is ever an enzyme that acts on the other chirality.
