### ISSUE TITLE
NTR: (2S,3R,6S,9S)-(-)-protoillud-7-ene synthase activity

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#14002]
Hello:
I would like to submit a NTR for the molecular function (2S,3R,6S,9S)-(-)-protoillud-7-ene synthase activity. Please let me know if you have any questions. 

Bob Dodson

Name: (2S,3R,6S,9S)-(-)-protoillud-7-ene synthase activity
Ontology: function
Synonyms: protoillud-7-ene synthase activity
Definition: Catalysis of the reaction: 2-trans,6-trans-farnesyl diphosphate = diphosphate + (2S,3R,6S,9S)-(-)-protoillud-7-ene
CHEBI:137530
Child of: GO:0010334 sesquiterpene synthase activity

References:
PMID:27862766 Terpene Cyclases from Social Amoebae.

**Comment by ukemi** [comment]
Added term as requested.
