### ISSUE TITLE
parent terms for sphingolipid-translocating ATPase activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14019]
Hi

I was surprised to see this term GO:0046623 sphingolipid-translocating ATPase activity as a child of GO:0004012 phospholipid-translocating ATPase activity. In theory  not all sphingolipid are phosphorylated. 

I don't know if any unphosphorylated sphingolipid are transported, and therefore I don't want to say that this is not appropriate. But it would be good to make more constancy in this part of the ontology. In general the sphingolipid and phospholipid terms are siblings rather than having a parent child relationship (which is also how this appears in ChEBI).

GO:0004012 phospholipid-translocating ATPase activity
>is a GO:0046623 sphingolipid-translocating ATPase activity

Whereas there are sibling relationships for:
GO:0045332 phospholipid translocation and GO:0099039 sphingolipid translocation 
GO:0005548 phospholipid transporter activity and GO:0046624 sphingolipid transporter activity 

so I would have thought GO:0004012 phospholipid-translocating ATPase activity should not be a parent for GO:0046623 sphingolipid-translocating ATPase activity (or should phospholipid be added as a parent  for the other sphingolipid terms?)

Also see https://github.com/geneontology/go-ontology/issues/12559, Note I did not request the addition of this relationship.

Thanks

Ruth

**Comment by ukemi** [comment]
Hi Ruth.  I just confirmed your check of ChEBI. I agree that the sphingolipid term should not be a child of the phospholipid term. It looks like this is the result of a bad logical definition. At the moment I do not see a way to make a N&S logical definition, so I am removing it and asserting the parents.
