### ISSUE TITLE
polyphosphate metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14017]
Do you think that 
"polyphosphate metabolic process" could have the parent 

generation of precursor metabolites and energy
http://www.ebi.ac.uk/QuickGO/term/GO:0006091

(this  term is in most slims, and would allow polyphosphate metabolism to be included in slims which do not include the very general term
"phosphorus metabolic process" as this relates to absolutely any phosphate containing compound.

A review here:
https://microbialcellfactories.biomedcentral.com/articles/10.1186/1475-2859-10-63

**Comment by ukemi** [comment]
PMID:25589044

**Comment by ValWood** [comment]
OK so no...
