### ISSUE TITLE
GO subsets on geneontology.org

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#14028]
We have links to each of the current GO slims on geneontology.org:

http://geneontology.org/page/download-ontology#Subsets

It'd be nice to also include the AGR slim, so curators can always see the latest version.

There is a folder for GO subsets in ontology/src:

https://github.com/geneontology/go-ontology/tree/master/src/ontology/subsets

but it looks like maybe it isn't being populated yet?

What is the preferred pipeline for getting the AGR subset included on the website?

**Comment by cmungall** [comment]
We avoid checking derived products into github

Subsets can be found at URLs like:
http://purl.obolibrary.org/obo/go/subsets/goslim_virus.obo

After the PR I am about to make is merged, we will have id-pair tsvs at

http://purl.obolibrary.org/obo/go/subsets/goslim_virus.tsv

These will look ugly until we implement this:
https://github.com/ontodev/robot/issues/176

**Comment by pgaudet** [comment]
Done for new website
