### ISSUE TITLE
Carbohydrate metabolic process is a primary metabolic process - is this always true ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14022]
Some children, for example, 'oligosaccharide metabolic process' are not primary metabolic process, AFAIK.

**Comment by hdrabkin** [comment]
can you give me an example of ones that would not be.
 "primary metabolic process" def seems pretty broad: "The chemical reactions and pathways involving those compounds which are formed as a part of the normal anabolic and catabolic processes. These processes take place in most, if not all, cells of the organism."
Do you mean ones where they occur in only some organisms? So, for example, photosynthesis would not fall into child of PNP because it doesn't occur in animals cells?

**Comment by pgaudet** [comment]
Hi @hdrabkin 
Some children that dont seem to fit the definition: 
- glycolytic fermentation
- enterobacterial common antigen biosynthetic process
- slime layer polysaccharide biosynthetic process

These seem to be indeed carbohydrate biosynthetic process but I don't think the fit the definition of primary metabolism. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Sorry, maybe I need more coffee; or it's Friday; or both
 why do you think "glycolytic fermentation" not fit into a set of chemical reactions and pathway involving ..... etc.
glycolytic fermentation
The fermentation that includes the anaerobic conversion of glucose to pyruvate....
    This is the common part of glycolysis; Is this not a primary metabolic process?

**Comment by pgaudet** [comment]
Hi @hdrabkin 
I typed too fast, assuming fermentation was only in microorganisms. But what about the other two terms I listed there ? do they also 'take place in most, if not all, cells of the organism.'? 

Pascale

**Comment by deustp01** [comment]
The primary - secondary distinction is really fuzzy. Here's Wikipedia (which aligns well with standard textbooks on this):

A primary metabolite is a kind of metabolite that is directly involved in normal growth, development, and reproduction. It usually performs a physiological function in the organism (i.e. an intrinsic function).

Secondary metabolism (also called specialized metabolism) is a term for pathways and small molecule products of metabolism that are not absolutely required for the survival of the organism. Examples of the products include antibiotics and pigments.

So anything required for reproduction is primary. If the organism in question is a yeast in an environment full of rapidly growing bacteria, that certainly includes antibiotics. I may think that one of your features is primarily decorative, but how do I really know that? And we can play other games. Per the definitions and general usage, "energy metabolism" (the processes used to convert reduced molecules from the environment into energy in the form of ATP) is a primary metabolic process and indeed, when glycolytic fermentation is underway that is one of its roles, so it looks primary even if in a large multicellular organism there are some differentiated cell types that never do it.

**Comment by pgaudet** [comment]
Thanks for your answer @deustp01 
My point was that I didn't think primary (and secondary metabolism) were relevant at such high level in the ontology. 

The alternative solution would probably to be to add the 'primary metabolism' parent to individual pathways but that seems like an awful lot of work. 

But I dont think the current structure is correct. 

Pascale

**Comment by pgaudet** [comment]
Not sure what to do about this. Let's close
