### ISSUE TITLE
GO:0031149 sorocarp stalk cell differentiation STILL is_a reproductive process

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#14034]
Hello,

When looking into how the AGR would work for Dicty I came across something I thought long fixed from this issue:
https://github.com/geneontology/go-ontology/issues/12619

But: GO:0031149 sorocarp stalk cell differentiation still is_a GO:0022414 reproductive process.

Can those links be severed?

Thanks!
petra

![0031149_tree](https://user-images.githubusercontent.com/1349602/29095476-8531b3e8-7c56-11e7-8998-12e6508b3987.png)

**Comment by pfey03** [comment]
the same is true for GO:0044671 sorocarp spore cell differentiation

**Comment by pgaudet** [comment]
Fixed
https://github.com/geneontology/go-ontology/pull/14036/commits/589eb4f41773dbfe20de7b7de065a9422fb8aa12
