### ISSUE TITLE
OTR  regulation of ubiquitin-dependant protein catabolic process 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14030]
Following up on #13992 

A term was requested, NTR: negative regulation of ubiquitin-dependant protein catabolic process (GO:0006511)
I suggested to use 'GO:2000059 | negative regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process'? 
but then there was a discussion that the 'involved in' part was not desirable, and a suggestion by @ValWood that the relationship to ubiquitination is better captured with a MF term (which seems reasonable to me). 

So we suggested to merge 'negative regulation of ubiquitin-dependant protein catabolic process'
and 'GO:2000059 | negative regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process', and revise the term names to the simpler version.

Looking at the subclasses of GO:0006511 ubiquitin-dependent protein catabolic process , there are two children of 'ubiquitin-dependent  protein catabolic process' 
that seem to represent different types of that process: 

- GO:0042787 protein  ubiquitination involved in ubiquitin-dependent protein catabolic process
and
- GO:1902376 protein denaturation involved in proteasomal ubiquitin-dependent protein catabolic process
If both subclasses are relevant, then we cannot merge into 'ubiquitin-dependent  protein catabolic process'. The second term (protein denaturation involved in proteasomal ubiquitin-dependent protein catabolic process) has only been used once by pombase (txl1 from PMID:21091378)

@ValWood @mah11 : would it make sense to replace GO:1902376 by an annotation to a MF + GO:0006511 ?

**Comment by ValWood** [comment]
Yes we are the only EXP annotation
http://www.ebi.ac.uk/QuickGO-Old/GTerm?id=GO:1902376#term=annotation
Sorry, I missed this.

protein disulfide oxidoreductase activity part_of proteasomal ubiquitin-dependent protein catabolic process

will do the job
I'll fix this now,,,

**Comment by pgaudet** [comment]
Obsoletion notice sent: 
Dear all,

The proposal has been made to obsolete:' GO:1902376 protein denaturation involved in proteasomal ubiquitin-dependent protein catabolic process’. The reason for obsoletion is that the term would be better captured by a CAM model. There is 1 experimental annotation to this term and 0 InterPro2GO mappings. Any comments can be added to the issue: 

https://github.com/geneontology/go-ontology/issues/14030. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on August 21, 2017.

*** Unless objections are received by August 21, 2017, we will assume that you agree to this change. ***

Best regards,

Pascale

**Comment by pgaudet** [comment]
Here you go: 

 id: GO:2000059
MOVED NAME TO SYNONYM: negative regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process
NEW NAME: negative regulation of ubiquitin-dependant protein catabolic process

I will merge the changes after the obsoletion notice expires. 

- Pascale

**Comment by pgaudet** [comment]
Hi @Antonialock @ValWood 
Following up on the request to create 'negative regulation of ubiquitin-dependent protein catabolic process' : We do have 'regulation of proteasomal ubiquitin-dependent protein catabolic process'  (as well as + and - versions); is this suitable ? 

A little bit of background: in the ontology under 'ubiquitin-dependent protein catabolic process', there are two types: 
- 'proteasomal ubiquitin-dependent protein catabolic process' , and
-'ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway' 

it seems useful to express which type of ubiquitin-dependent protein catabolic process the protein is regulating. What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
already annotated to that term for this paper, so we are good
http://preview.pombase.org/reference/PMID:28552615

I think it got a bit convoluted as we wanted to condense the "protein ubiquitination involved in"

can close.

**Comment by ValWood** [comment]
This is how it looks:

![protein ubiquitination](https://user-images.githubusercontent.com/7359272/30854717-696d8202-a2aa-11e7-82ce-cbb1ff033bf1.jpg)

I would:
1. Delete "protein ubiquitination" parentage of existing terms of type "protein ubiquitination involved in yada yada"
2. Merge existing "protein ubiquitination involved in.." into the "ubiquitin dependent catabolic process parent"
3. Don't keep "protein ubiquitination..." synonyms, that would be confusing

If things are annotated correctly, they should already have the MF term which gives the "protein ubiquitination" parentage. 
"Protein ubiquitination" is really  an instance of  MF in the BP ontology (like protein phosphorylation).  

We might need to use them in some instances (regulation or protein ubiquitination/phosphorylation), but a  good move would be to flag as " not for direct annotation" OR before using this term, please check that it is not redundant by a 
MF involved in BP annotation.

MF ubiquitin protein ligase activity involved_in   BP ubiquitin-dependent protein catabolic process

would say the same thing as

BP GO:0042787 protein ubiquitination involved in ubiquitin-dependent protein catabolic process

breaking the connection between the current "protein ubiquitination" children and "ubiquitin-dependent protein catabolic process" will help us to be more consistent and do MF involved in BP annotation instead.


It's the same as my suggestion here:
https://github.com/geneontology/go-ontology/issues/14138

and it's  a compromise (or baby step towards)  
https://github.com/geneontology/go-ontology/issues/12859

**Comment by ValWood** [comment]
For the record

GO:0042787    protein ubiquitination involved in ubiquitin-dependent protein catabolic process	8,397 annotations (192 EXP)
GO:2000060    positive regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process	755 annotations (27 EXP)
GO:2000058    regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process	1,313 annotations (53 EXP)
GO:2000059    negative regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process 437 annotations (21 EXP)

**Comment by ValWood** [comment]
we can close this one, it's essentially  the same suggestion as
https://github.com/geneontology/go-ontology/issues/14137
