### ISSUE TITLE
Q 	pyrimidine-5'-nucleotide nucleosidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14046]
Is this activity a nucleotidase?

I am looking to annotate  the ortholog of
http://www.yeastgenome.org/locus/YGL224C/overview

described in the paper as a 
pyrimidine 5'-nucleotidase
http://www.yeastgenome.org/reference/S000070009/overview

I can only find 
pyrimidine-5'-nucleotide nucleosidase activity
which sounds  right if it acts on a nucleotide, or is this something else?

**Comment by ValWood** [comment]
Perhaps it is just named incorrectly?

**Comment by ukemi** [comment]
According to EC, this is the official name for the enzyme that catalyzes the defined reaction.

**Comment by ValWood** [comment]
and is it the  nucleotidase I'm looking for then?
Or do we need a new term for that?

I know a man who will know @deustp01

**Comment by ukemi** [comment]
I don't think GO:0047405 is the enzymatic activity you want. In mammals uridine 5' monophosphate hydrolase dephosphorylates to leave a nucleoside. GO:0047405 cleaves off the sugar phosphate to leave a free pyrimidine. I think you want GO:0008253 or a new child of it. It appears EC does not go to further specify a pyrimidine. Most papers I see also leave the classification at this level. See PMID:    15604219 for example. Note that the specific enzymes are also listed as synonyms of this term.

**Comment by ukemi** [comment]
Doing a little more reading, it appears that these enzymes do have broad specifity, which is consistent with the modification of the nomenclature of _Nt5c3_, which was previously called _Umph1_.

**Comment by ValWood** [comment]
I'll go with GO:0008253

**Comment by ukemi** [comment]
I think this is best unless we find an enzyme that is discriminating. Otherwise if we create the children, it will require co-annotation of all the enzymes that aren't.
