### ISSUE TITLE
ribosome biogenesis and gene expression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14048]
Gene expression includes transcription , RNA processing (All), translation, protein maturation, mRNA export from the nucleus.
I wonder if it should therefore include all of ribosome biogenesis?
(RNA processing is a part of it, other parts are ribosome export etc)

**Comment by ukemi** [comment]
To me that would be very misleading.

**Comment by ValWood** [comment]
Pombe gene expression Guru, Jürg Bahler:

"
That's a tough one. Of course, ribosome biogenesis is ultimately required for gene expression via translation. But is quite indirect and removed from actual gene expression steps. So I probably would not have it as a child term of gene expression."

So I'll close this.
