### ISSUE TITLE
NTR:sexual macrocyst formation

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#14040]
Hello:

I would like to request a new GO term to describe the sexual reproductive phase of the Dictyostelium life cycle. This term is most commonly associated with D. discoideum, but applies to at least 3 additional species of Dictyostelids: D. giganteum, D. purpureum, and P. palladium. Please let me know if you have additional questions. 

Thanks,
Bob Dodson

Name: sexual macrocyst formation
Ontology: process
Synonyms: macrocyst formation, sexual fusion
Definition: The fusion of haploid amoebae cells with matching mating types to form a larger cell, which ingests additional amoebae and forms a cellulose wall. The resulting macrocyst undergoes recombination and meiosis followed by release of haploid amoebae. An example of this process can be found in Dictyostelium discoideum.
Child of: GO:0019953 sexual reproduction
References:
PMID:16592095 Mating Types and Macrocyst Formation in Dictyostelium discoideum
PMID: 20089169 Phylogeography and sexual macrocyst formation in the social amoeba Dictyostelium giganteum.

**Comment by pgaudet** [comment]
Hi Bob !! 
Here's the new term: 
 [Term]
+id: GO:0140084
+name: sexual macrocyst formation
+namespace: biological_process
+def: "The fusion of haploid amoebae cells with matching mating types to form a larger cell, which ingests additional amoebae and forms a cellulose wall. The resulting macrocyst undergoes recombination and meiosis followed by release of haploid amoebae. An example of this process can be found in Dictyostelium discoideum." [PMID:16592095, PMID:20089169]
+synonym: "macrocyst formation" RELATED []
+synonym: "sexual fusion" RELATED []
+is_a: GO:0019953 ! sexual reproduction
+created_by: pg
+creation_date: 2017-08-14T20:11:03Z


Thanks, Pascale

**Comment by rjdodson** [comment]
Thanks Pascale!
