### ISSUE TITLE
exocyst complex parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14057]
exocyst has parent "cell cortex part"

but should it be "plasma membrane part"
(the sec3 exo70 subunits bind to interact with phosphatidylinositol (4,5)-bisphosphate at the plasma membrane)

**Comment by pgaudet** [comment]
Hi @ValWood 

According to the definition, exocyst is _associated_ with the plasma membrane, I don't think it's part of it. Cell cortex seems ok  (the region of a cell that lies just beneath the plasma membrane and often, but not always, contains a network of actin filaments and associated proteins.)

Pascale

**Comment by ValWood** [comment]
OK I am never sure about this. So a protein that binds to the membrane but is extrinsic is part of the cortex...OK.

**Comment by ValWood** [comment]
OK I asked  this before. I should annotate to both.

https://github.com/geneontology/go-ontology/issues/9152
