### ISSUE TITLE
question about mRNA stabilization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14054]
Should "RNA stabilization" be part of
"negative regulation of RNA catabolic process" ?

**Comment by ValWood** [comment]
the parent is defined


 GO:0043487 regulation of RNA stability
Any process that modulates the propensity of RNA molecules to degradation. Includes processes that both stabilize and destabilize mRNAs.

**Comment by ukemi** [comment]
Makes sense to me. I can't think of an exception, so I will tidy up this whole area. Looks like we have a couple of logical defs that are insufficient.

**Comment by ukemi** [comment]
Me too, but I couldn't remember what it was.
