### ISSUE TITLE
new term request: jasmonic acid hydrolase

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#14065]
Two recent publications describe the molecular activity of 2-oxoglutarate dioxygenase family members in plants. 

The activity (definition)  is: Catalyzes the hydroxylation of jasmonic acid to 12OH-jasmonic acid.

Parentage:is a GO:0016810 

References are 
PMID:28559313
PMID:28559313

**Comment by krchristie** [comment]
Hey Leonore,

Did you mean to have two different PMIDs here? You've listed the same one twice.

Thanks, 

-K

**Comment by lreiser** [comment]
You are correct. I did mean to reference two separate PMIDs.... thank you for checking

PMID:28760569
PMID:28559313

**Comment by krchristie** [comment]
I'm adding your term with the info you indicated Leonore, as shown here: https://github.com/geneontology/go-ontology/pull/14100/files. 

I also wondered if "2-oxoglutarate dioxygenase" should be added as some form of synonym. If it should be added, let me know what kind it should be: EXACT, RELATED, NARROW, or BROAD. 

thanks,

-Karen

**Comment by lreiser** [comment]
Yes and I'd think Broad.
Thank you Karen

Leonore Reiser, Ph.D.

lreiser@arabidopsis.org

**Comment by krchristie** [comment]
Thanks Leonore. I added the synonym as BROAD.
