### ISSUE TITLE
microtubule nucleation is_a protein complex assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14078]
microtubule nucleation is_a protein complex assembly
which looks a bit odd.

Especially since  microtubule is not defined as a protein complex:
http://www.ebi.ac.uk/QuickGO-Old/GTerm?id=GO:0005874#term=ancchart

**Comment by ukemi** [comment]
Intuitively this makes sense to me because what we are talking about here is the original nucleation product (seed), not the entire microtubule. I'm not sure we need a named class for all of these.

**Comment by ValWood** [comment]
Hmm, its a bit weird. I wouldn't call this a "protein complex" because it isn't separate from the MTOC. But it isn't a big deal so close if its a hassle.

**Comment by vanaukenk** [comment]
@ukemi @ValWood 

What would you like to do with this one? 

If I'm understanding correctly, the protein complex referred to in the 'microtubule nucleation' term is the multimer of alpha and beta tubulin dimers that forms the nucleus required for subsequent MT filament growth.  It is this nucleus, or seed, that does not have a named class in GO.  

Nucleation does appear to occur through both MTOC-dependent and -independent pathways, though, so in some cases the seed may exists independently of the MTOC.

**Comment by ValWood** [comment]
I'm happy for it to be closed. 
v
