### ISSUE TITLE
possible merges "actin filament REorganization"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14087]
There are  a bunch of terms

Process	 GO:0090527	actin filament reorganization	
Process	 GO:0031532	actin cytoskeleton reorganization	
Process	 GO:2000249	regulation of actin cytoskeleton reorganization	
Process	 GO:0030037	actin filament reorganization involved in cell cycle	
Process	 GO:2000250	negative regulation of actin cytoskeleton reorganization	
Process	 GO:2000251	positive regulation of actin cytoskeleton reorganization

which  are an ontology "stub" and have only 23 experimental annotations.

These are problematic on a number of levels

1. how does "reorganization" differ from "regulation of organisation?"
(these are the only terms with "reorganization" in the name
i.e how do you "re-organize" an actin filament?
2. How is the reorganization "involved in the cell cycle", presumably via cytokinesis?
3. Mixed bag of annotation… regulation of cytokinesis , some appear to be microtubule organization (definitely inconsistent annotation)

 suggest "obsoletion" of the cell cycle one.
Possible merge of the others into   the "actin cytoskeleton organization terms"

What do you think?

@pgaudet

**Comment by pgaudet** [comment]
Hi agree this branch has many problems. 

First of all I dont think 'actin filament' should contain 'associated proteins' (current def= "A filamentous structure formed of a two-stranded helical polymer of the protein actin and associated proteins. (... )" As far as I can tell the paper cited does not support that (PMID: 10666339). 

Some of the actin filament organization terms look like they should belong under 'actin filament network formation' (like branching for instance).

As far as I know for actin filaments you should only have 'polymerization' and 'depolymerization'. 

(I am writing this very fast, all this needs to be checked). I can find an expert to help with this branch, we just need to prioritize. 

Meanwhile I am happy to obsolete any term containing 'involved in x' ;) ("actin filament reorganization involved in cell cycle"; 0 annotations). 

Pascale

**Comment by ValWood** [comment]
>First of all I dont think 'actin filament' should contain 'associated proteins' (current def= "A filamentous structure formed of a two-stranded helical polymer of the protein actin and associated proteins. (... )" As far as I can tell the paper cited does not support that (PMID: 10666339).

For this, I think we need to specify exactly *which* proteins are part of the filament (tropomyosin or  some cofilin family) is a necessary part of the filament. I think that is probably what the  "associated proteins" here refers to.

**Comment by pgaudet** [comment]
OK - I can ask a Dicty person about the actin filaments versus network and cytoskeleton. 

What's the action point right now: check if we can obsolete 'actin filament reorganization' and regulation of actin filament reorganization'?

**Comment by ValWood** [comment]
I think that is a good plan....

**Comment by ValWood** [comment]
Maybe this is OK?
It has more annotations than I thought if you move up to actin cytoskeleton organization (148).

I guess that "reorganizing" is organizing a structure that already exists.

I'll close, maybe one for another day.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0090527 actin filament reorganization
GO:0031532 actin cytoskeleton reorganization
GO:2000249 regulation of actin cytoskeleton reorganization
GO:0030037 actin filament reorganization involved in cell cycle
GO:2000250 negative regulation of actin cytoskeleton reorganization
GO:2000251 positive regulation of actin cytoskeleton reorganization

The reason for obsoletion is that the process of actin filament and cytoskeleton REorganization is not different from actin filament organization. 

There are 84 EXP annotations to these terms: 

BHF-UCL	16
CACAO	2
dictyBase	4
FlyBase	8
MGI	4
PomBase	1
RGD	3
SGD	17
UniProt	28
WB	1

(There is 1 InterPro mapping to a deleted entry,  InterPro:IPR030610).

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by pfey03** [comment]
The 4 dicty annotations have been changed - done
