### ISSUE TITLE
OTR: GO:0036396 MIS complex synonym/rename

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14080]
Would it be possible to rename the GO:0036396 MIS complex to a more generic term name: "RNA N6-methyladenosine methyltransferase complex"?
[ref PMID:24407421]

As far as I know that MIS complex name isn't really used outside of S. cerevisiae. m6A methyltransferase complex seems to be broadly used to describe these complexes, but is slightly ambiguous so prefixing with RNA should hopefully solve that.

synonyms:
METTL3–METTL14–WTAP methyltransferase complex
m(6)A writer complex
m6A methyltransferase complex

**Comment by hdrabkin** [comment]
I also added "MIS complex" as a synonym in case a yeast person is trying to find it. Also added your ref to the rest of the def references

**Comment by hattrill** [comment]
Thanks, Harold.
