### ISSUE TITLE
Add new subclass relation to social behavior.

### ISSUE THREAD

**Issue by ramonawalls** [geneontology/go-ontology#14099]
http://purl.obolibrary.org/obo/GO_0035176 (social behavior) is defined as "Behavior directed towards society, or taking place between members of the same species. Occurs predominantly, or only, in individuals that are part of a group." 

It would be helpful to PCO if GO could add an axiom subClassOf 'has participant' only 'single-species collection of organisms' (http://purl.obolibrary.org/obo/PCO_0000018). We are defining some subclasses of this, see PopulationAndCommunityOntology/pco#46

**Comment by cmungall** [comment]
This would lead to unsatisfiable classes. If we look at the property chains for http://purl.obolibrary.org/obo/RO_0000057

we see the 'only' would not work.

In general you should be very careful with only restrictions. You never have them for transitive properties, and they are frequently invalid for chains.

A some axiom would be valid

**Comment by pgaudet** [comment]
What's the action here ?

**Comment by cmungall** [comment]
on reflection I think changing the only restriction to some still has problems. I don't think a population is a participant in the process.

**Comment by ramonawalls** [comment]
So is the idea here that this is a behavior that an individual participates in, but it is toward one or more members of the same species (using the word toward loosely, not in the RO sense)?

Is there a class for a behavior in which a group participates, like a swarm or a migrating flock? Or are group behaviors considered simply aggregates of individual behaviors?

**Comment by cmungall** [comment]
> So is the idea here that this is a behavior that an individual participates in
yes

> Or are group behaviors considered simply aggregates of individual behaviors?
AFAIK behaviorists will argue over this, I can't find the list discussion right now but in the early days of NBO we discussed this.

But certainly out of scope for GO - maybe look to NBO for your class. We still don't have a good solution for NBO-GO integration, so the current situation of lots of equivalent classes will likely persist for a while.

**Comment by ramonawalls** [comment]
Thanks Chris. It's clear now.
