### ISSUE TITLE
 Crotonyl-CoA hydratase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#14109]
Hi,

I would need 3 terms to describe a 1) new enzyme activity that 2) regulates peptidyl-lysine crotonylation

Thanks

Sylvain

GO:xxxxxxx Crotonyl-CoA hydratase activity
Category: Function
Definition: Catalysis of the reaction: Acetyl-CoA + [protein]-L-lysine = CoA + [protein]-N(6)-acetyl-L-lysine.
Xref: RHEA:45587

child of GO:0016836 hydro-lyase activity

PMID:28803779
----------------------------------------------------------------------------
GO:xxxxxxx regulation of peptidyl-lysine crotonylation
Category: Process
Definition: Any process that modulates the frequency, rate or extent of crotonylation of a lysine residue in a protein.

PMID:28803779
----------------------------------------------------------------------------
GO:xxxxxxx negative regulation of peptidyl-lysine crotonylation
Category: Process
Definition: Any process that stops or reduces the rate of crotonylation of a lysine residue in a protein

child of GO:0140066 peptidyl-lysine crotonylation

PMID:28803779

**Comment by krchristie** [comment]
These are added Sylvain. Let me know if I missed anything.
