### ISSUE TITLE
travis checks for design patterns

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#14114]
For Python check - use https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/src/simple_pattern_tester.py

This requires python3 and libs: jsonschema; requests; jsonpath_rw 

It takes one arg - a path to the directly with YAML files.

This uses the latest release of the DOSDP spec and does this directly via a standard JSON schema checker.  This is not currently the case for DOSDP tools.  It checks internal cross referencing and balancing of single quotes.  It does not (currently) test the validity of referenced terms or Manchester Syntax expressions.  

For now at least, checking with both DOSDP tools and the python checker should be most informative for editors.

Note - this script assume all .yaml or .yml files in the target directory are DOSDPs,  this not currently true for the design patterns folder, which has `design_patterns/prefixes.yaml`.  It would be useful if this could be moved to a subdirectory.

**Comment by balhoff** [comment]
We're now automatic pattern docs generation weekly, which tests readability of design pattern templates.
