### ISSUE TITLE
Accession number for GO_molecular function

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#14118]
_From @guptapa on August 24, 2017 23:22_

Hi,
I'm looking for the accession number for 4-aminobutyrate-pyruvate transaminase enzyme (EC: 2.6.1.96). I did not find it on GO live site. Following link is for more information about enzyme:
http://www.brenda-enzymes.org/enzyme.php?ecno=2.6.1.96&Suchword=&reference=&UniProtAcc=&organism%5B%5D=Oryza+sativa&show_tm=0 
Thanks.

_Copied from original issue: geneontology/go-annotation#1622_

**Comment by krchristie** [comment]
It looks like we do NOT have this EC number, though we do have a term with nearly that name, but a different EC#:

4-aminobutyrate:pyruvate transaminase activity (GO:0034387)
Def: Catalysis of the reaction: 4-aminobutanoate + pyruvate = succinate semialdehyde + alanine.
  EC:2.6.1.19
  GOC:mah

This looks like a mistake as the definition for this GO term looks like it matches the definition for EC:2.6.1.96, and not for EC:2.6.1.19, which is supposed to be "4-aminobutyrate—2-oxoglutarate transaminase".  @hdrabkin Do you agree?

The only annotation to that term is a plant gene (http://amigo.geneontology.org/amigo/term/GO:0034387), so probably worth checking which EC number this gene actually has.

Here is info from the EC pages for these two EC numbers:

**EC 2.6.1.19** (http://www.chem.qmul.ac.uk/iubmb/enzyme/EC2/6/1/19.html)
**Accepted name**: **4-aminobutyrate—2-oxoglutarate transaminase**
**Reaction**: 4-aminobutanoate + 2-oxoglutarate = succinate semialdehyde + L-glutamate
**Glossary**: 4-aminobutanoate = γ-aminobutyrate = GABA

**EC 2.6.1.96** (http://www.chem.qmul.ac.uk/iubmb/enzyme/EC2/6/1/96.html)
**Accepted name**: **4-aminobutyrate—pyruvate transaminase**
**Reaction**: (1) 4-aminobutanoate + pyruvate = succinate semialdehyde + L-alanine
  (2) 4-aminobutanoate + glyoxylate = succinate semialdehyde + glycine
**Systematic name**: 4-aminobutanoate:pyruvate aminotransferase

This ticket should probably be transferred to the ontology tracker, but I don't know how to do that. Maybe @ukemi or @vanaukenk can move it.

**Comment by krchristie** [comment]
_From @hdrabkin on August 25, 2017 15:56_

Yep, this is not right.
These are two different critters.
H

**Comment by krchristie** [comment]
@ukemi - I'll just take this ticket since I already started looking into it.

@tberardini - Could you help me look into the single annotation to the term "4-aminobutyrate:pyruvate transaminase activity" (GO:0034387) (http://amigo.geneontology.org/amigo/term/GO:0034387).

The cited paper is in a plant journal I don't have access to: http://www.arabidopsis.org/servlets/TairObject?accession=Publication:501706563

From the abstract, it looks to me like this annotation is meant to be to the 4-aminobutyrate—pyruvate transaminase activity, which corresponds to the name of the term and NOT to the associated EC number for this term. Could you check the paper and see if you agree with that assessment? Thanks!

**Comment by krchristie** [comment]
@jaiswalp @deustp01 Note that it looks like the existing term 4-aminobutyrate:pyruvate transaminase activity (GO:0034387) is already defined with the definition of EC: 2.6.1.96 though it is associated with EC:2.6.1.19, and the sole existing annotation of an A. thaliana gene looks to me (from the abstract only) like it is probably meant to be to the pyruvate term (the .96 EC number), NOT to the .19 EC number that is actually associated with this GO term.

@ukemi - In a case like this, would it be OK to just change the EC number reference to the one that matches the term name and definition (assuming Tanya confirms my thought that the existing TAIR annotation is meant to be to the .96 EC#), or would we need would we need to obsolete this term and make a new term for the .96 EC#?

**Comment by tberardini** [comment]
Hi Karen,

@krchristie : I looked at the full text of the paper:

"The expression of GABA-T was corroborated by the presence  of  GABA:pyruvate-T  activity  in  a  crude  extract  from the GABAT :pTrcHis cell  line (specific activity was 2.6  nmol·mg  protein–1·min–1),  whereas  no  activity  was  detected  in  the  no-insert:pTrcHisB  line. ...{snip} ..These data indicate that the GABA:pyruvate-T activity only could  be  attributed  to  the  expression  of  the
Arabidopsis GABA-T cDNA  insert."  

The experiments used GABA (4-aminobutyrate) and pyruvate as substrates and the amount of succinic semialdehyde produced was assessed.

It looks like the annotation to the term name + def is correct but the EC number is not.

**Comment by krchristie** [comment]
Thanks Tanya!

**Comment by jaiswalp** [comment]
Great. Changing the EC# would work.

**Comment by krchristie** [comment]
@ukemi - Any objection to just changing the EC number on the existing term "4-aminobutyrate:pyruvate transaminase activity" (GO:0034387), since the current usage of the term is consistent with the name/def and not with the EC number?

There doesn't seem to be any need to create a term for the EC number incorrectly referred to in the current GO term as there are no annotations for that activity, nor a request for it.

**Comment by ukemi** [comment]
No objection if the definitions match.

**Comment by guptapa** [comment]
Assigning new EC # (2.6.1.96) with the existing term "4-aminobutyrate:pyruvate transaminase activity" (GO:0034387) would work for plants but not for animal folks. Go term for "4-aminobutyrate:alpha-ketoglutarate transaminase activity" (EC: 2.6.1.19) is required for animal enzyme as Human Reactome guys use this term.

**Comment by krchristie** [comment]
Definitely interested in opinion of @deustp01 . However, if we cannot correct this GO term (GO:0034387) that has a mismatch between its name/def (which matches EC:2.6.1.96) and its actual cross reference (to EC:2.6.1.19), then we would probably have to obsolete this term and make a new one, which could mean there is no difference in work for Reactome.

There is currently only 1 annotation in AmiGO to the existing GO term GO:0034387, and it should be to the EC:2.6.1.96.

Also, just searched for "EC:2.6.1.19" string and it is associated with three GO terms:
- "4-aminobutyrate transaminase activity" (GO:0003867)
-- "4-aminobutyrate:pyruvate transaminase activity" (GO:0034387)
-- "4-aminobutyrate:2-oxoglutarate transaminase activity" (GO:0034386)

So, I propose fixing usage of EC:2.6.1.19 by:
- removing the incorrect usage (to GO:0034387) & replacing it with correct EC#
- removing the overly general usage to the parent term ( @hdrabkin Is there any correct EC reference that should be added back to the parent term?)

The existing term "4-aminobutyrate:2-oxoglutarate transaminase activity" (GO:0034386) already has a correct reference to EC:2.6.1.19 and thus requires no edits in GO.

**Comment by hdrabkin** [comment]
at ec
Search in ENZYME for: 4-aminobutyrate transaminase
Release of 05-Jul-17
Please choose one of the following entries:

2.6.1.19     4-aminobutyrate--2-oxoglutarate transaminase. 
             (AN: 4-aminobutyrate aminotransferase.
                  Beta-alanine--oxoglutarate aminotransferase.
                  GABA transaminase.
                  Gamma-amino-N-butyrate transaminase.)

2.6.1.96     4-aminobutyrate--pyruvate transaminase. 
             (AN: 4-aminobutyrate aminotransferase.
                  GABA transaminase.
                  Gamma-aminobutyrate aminotransaminase.
                  Gamma-aminobutyric acid pyruvate transaminase.)
Nothing above
2.6.1 : way too broad
So I recommend removing the ec from the parent term,;

**Comment by deustp01** [comment]
This term is not used to annotate any catalyst activities in human Reactome so the proposed changes will have no effect on us. In fact, if I'm reading the QuickGO entry for GO:0034387 correctly, it hasn't been used by anyone to annotate anything yet, so the proposed change looks safe.

**Comment by tberardini** [comment]
@deustp01 TAIR has one annotation to GO:0034387 and I reviewed it, see above for my comments.

http://amigo.geneontology.org/amigo/term/GO:0034387

I think removing the false EC from GO:0034387 and replacing with the correct one is the way to go.  Fix of the more general term as suggested by Karen is also good.

My 2 cents.

**Comment by jaiswalp** [comment]
It works.

**Comment by krchristie** [comment]
I have removed all references to EC:2.6.1.19 from both "4-aminobutyrate transaminase activity" (GO:0003867) and "4-aminobutyrate:pyruvate transaminase activity" (GO:0034387), including synonym dbxrefs.

**Comment by ukemi** [comment]
But the GO term is connected to its definition, not the assigned EC number. The EC number association is a cross reference. So if the definition doesn't match the EC number, then the EC number should not be associated with the term.

**Comment by krchristie** [comment]
Yes, I have removed EC:2.6.1.19 from the two terms that it should not have been associated with: 
- "4-aminobutyrate transaminase activity" (GO:0003867) because this is a grouping term for  2.6.1.19 and 2.6.1.96 => 2.6.1.- is too broad so no EC # replacement
- "4-aminobutyrate:pyruvate transaminase activity" (GO:0034387)  => replaced with correct EC# 2.6.1.96 that matches existing name/def of the term

I have left 2.6.1.19 on the term it belonged on: "4-aminobutyrate:2-oxoglutarate transaminase activity" (GO:0034386)
