### ISSUE TITLE
New term request: deaminated glutathione amidase activity

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#14116]
Hi,

I would like to have this new term created.
The definition is:
N-(4-oxoglutarate)-L-cysteinylglycine + H(2)O = 2-oxoglutarate + L-cysteinylglycine
Glossary: N-(4-oxoglutarate)-L-cysteinylglycine = deaminated glutathione
The activity has been submitted to the IUBMB, where it has received the internal working number EC 3.5.1.ag.
Relevant for NIT1 (e.g. Q8VDK1)
Ref: 28373563

The enzyme is involved in what the authors dubbed: Metabolite repair.
Definition: A "repair" process that destroys or reconverts useless and potentially harmful compounds -  formed by the promiscuous activity of some abundant enzymes of primary metabolism - into a useful metabolite.
The relevance is NIT1 but also wider since the NIT1 activity is certainly not the only example of such activity.

Cheers,
Kristian

**Comment by ValWood** [comment]
Should be a child of "cellular detoxification".  A number of the existing terms under here would fit this definition if a grouping term is created for "metabolite repair".

**Comment by vanaukenk** [comment]
I've added the MF term as GO:0110050.
Will work on the accompanying BP branch to see what can/should be grouped under 'metabolite repair'.

**Comment by ValWood** [comment]
This is an interesting area. I'm looking at the fission yeast  "unknowns" wrt a review we are writing and I have a gut feeling that a lot of the unknown catalytic are in this area (makes sense as these processes are less studied than  biosynthesis....).Many of those those orphan enzymes  are likely to be doing something like this....

**Comment by vanaukenk** [comment]
Here is a proposal for adding 'metabolite repair' as a grouping term under 'cellular detoxification'.  

I agree, @ValWood , that this is an interesting area and one that is probably under-annotated (see https://www.ncbi.nlm.nih.gov/pubmed/23334546).  Given the list of metabolites and detoxification/repair enzymes in Table 1 of that paper, I think a more general grouping term is justified and then we could add more specific child terms as they are needed. 

GO:1990748 cellular detoxification
-GO:new metabolite repair
--GO:0140041 cellular detoxification of methylglyoxal
---GO:0106045 guanine deglycation, methylglyoxal removal

I modified the initial, suggested term definition a bit to account for the fact that not all deleterious metabolites are produced by enzymatic reactions.  @kaxelsen , please let me know if this still look okay to you:

GO:new metabolite repair
A cellular process that, through single- or multi-step enzymatic reactions, repairs useless and potentially harmful endogenous compounds, formed as by-products of primary metabolism, by converting them into useful metabolites.
PMID: 23334546, PMID:28373563, GOC:ka

Do you think any of the other existing child terms of 'cellular detoxification' should be moved to be children of 'metabolite repair'?  

Thx for the input and suggestions on this term!

**Comment by ValWood** [comment]
Nice!

I'll have a quick scan of the cellular detoxification terms.

Do you think 
protein repair   http://www.ebi.ac.uk/QuickGO/term/GO:0030091
should also be is_a  GO:1990748 cellular detoxification ?

**Comment by vanaukenk** [comment]
That's a good question, and actually now has me wondering if we need to make a clearer distinction in the ontology between dealing with 'useless' compounds vs 'toxic' compounds, if that distinction can even always be made.
If a compound is just useless, is it's elimination detoxification?
Maybe the methylglyoxal terms should really have both parents, i.e. cellular detoxification and metabolite repair?

**Comment by vanaukenk** [comment]
In other words, cellular detoxification and metabolite repair would not have a parent-child relation.

**Comment by ValWood** [comment]
Hmm, yes you are right. metabolite repair might only be useless not toxic

Could we have

metabolite repair
--toxic metabolite repair
cellular detoxification
--toxic metabolite repair

( and put the things we know are toxic under here, otherwise things are likely to get annotated in one branch or the other)

I had assumed protein repair to be toxic because the instances I have annotated are, but this may not always be the case either?

**Comment by ValWood** [comment]
I don't think its catabolic (is a bit like the salvage pathways are not biosynthesis) , probably just 'cellular metabolic process' ?

**Comment by vanaukenk** [comment]
Okay, here's a suggested new organization and definitions:

GO:0044237 cellular metabolic process
-GO:new metabolite repair
—GO:new toxic metabolite repair
GO:1990748 cellular detoxification
—GO:new toxic metabolite repair

Definitions:
GO:new
Name: metabolite repair
Definition:  A cellular process that, through single- or multi-step enzymatic reactions, repairs useless or toxic endogenous compounds, formed as by-products of primary metabolism, by converting them into useful metabolites.
PMID:23334546, PMID:28373563, GOC:ka

GO:new
Name: toxic metabolite repair
Definition:  A cellular process that, through single- or multi-step enzymatic reactions, repairs toxic endogenous compounds, formed as by-products of primary metabolism, by converting them into useful metabolites.
PMID:23334546, GOC:ka, GOC:vw

@kaxelsen if this all looks okay to you, I will add it to the BP branch.  Thx.

**Comment by kaxelsen** [comment]
I think it looks fine. Thank you for your work on this.

**Comment by vanaukenk** [comment]
Added BP terms and closing.
