### ISSUE TITLE
GO:0106045   guanine deglycation, methylglyoxal removal

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14126]
GO:0140041    cellular detoxification of methylglyoxal

note the parent of this term should probably be 
GO:0009438  methylglyoxal metabolic process
rather than  "catabolic process".
Some  of the detoxification is interconversion rather than catabolism

**Comment by hdrabkin** [comment]
Changed to methylglyoxal metabolic process; also added GO:0140041 as parent of GO:0106045
