### ISSUE TITLE
receptor ligand activity

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#14120]
Following discussion on the 25th August editor's call, we agreed to change the name of 'receptor agonist activity' to 'receptor ligand activity' and also to tweak the definition.

*Rationale:* ligand activity was previously rejected as a term (see discussion on #7909 ), largely because of different usage of the term 'ligand' by biochemists (who use it more broadly to refer to
substances that bind and activate some protein or complex) and signaling biologists who use it only in the context of receptors.

Instead of 'ligand activity', GO uses terms with names and definitions from pharmacology:

* **'receptor agonist activity':** "Interacts with receptors such that the proportion of receptors in the active form is increased."
* **'receptor antagonist activity':** "Interacts with receptors to reduce the action of another ligand, the agonist."

These terms have a number of issues:

* Their meaning in pharmacology is much broader - encompassing drugs which are outside of the scope of GO.  Agonist, in some uses at least, covers a broader range of receptor activity modulators than ligand (glycine is considered an agonist (or co-agonist)  of the NMDA receptor, but glutamate is considered the ligand).
* These terms are not widely known or understood by curators and are not widely used in curation. 

A term with the word 'ligand' in would be much clearer and likely to be much more widely used. To avoid confusion with the more generic meaning of 'ligand activity' we suggest 'ligand receptor activity'.  The definition of this term has to encompass cases where binding inhibits as well as
activates the effector function of a receptor: Hedgehog is a ligand for the Patched receptor, but it inhibits the activity of Patched, which in turn is required to inhibit Smoothened activity.  All ligands
bind to and modulate the effector activity of receptors, but this description is not sufficient to define a ligand.  For example: glutamate, glycine, zinc and magnesium both bind and modulate the activity of the NMDA specific glutamate receptor but only glutamate is considered the ligand.  The reason is that only glutamate is believed to carry signaling information to the receptor (in this case, as part of
synaptic transmission).  Signaling is also crucial to the definition of Hedgehog as a ligand for Patched for another reason: Hedgehog inhibition of patched activity results, via releasing inhibition of Smoothened activity, in activation of the HH signaling pathway.

### Suggested definition:

**'ligand receptor activity':** "Binding to a signaling receptor as part of signaling and modulating the effector activity of that receptor to initiate a change in cell activity. Signaling in this context may
refer to cell-cell or matrix-cell signaling, eg. where an extracellular ligand released by one cell binds to a receptor on or in another cell.  It may also refer to intracellular signaling -  the IP3 receptor is activated by a second messenger (IP3) and some nuclear receptors respond to intracellular signals."
* *subclassOf:* receptor binding activity
* *subclassOf:* part_of some 'cell communication'*  # Might be too narrow.

While this differs significantly from the definition of 'receptor agonist activity', we believe that everything annotated with this term is considered a ligand (this needs to be checked).  By this
definition, receptor antagonists are not considered ligands.  They typically compete for binding with a ligand, preventing their modulation of effector function. We therefore propose to rename and redefine 'receptor agonist activity' using the proposed new name and definition and keeping 'receptor antagonist activity' in place.

Note that this definition does not encompass the cargos bound by cargo receptors (which are sometimes referred to as ligands).  In GO, we should refer to these as cargo, not ligands.

The definition and formalization of 'receptor ligand activity' needs to be co-ordinated with the definition and formalization of 'signaling receptor activity' as a part of molecular function refactoring.

In order to reliably classify receptors by their ligands, the MF refactoring introduces a **has_ligand** relation (a subproperty of **has_input**).  We could take advantage of this to infer 'receptor ligand activity' via a rule:

has_ligand(x,y) ^ enables(y,z) ->  'receptor ligand activity'(z)  # May need more discussion

We may also want to distinguish ligands involved in cell-cell signaling from those involved in intracellular signaling:

'cell-cell signaling ligand activity' EquivalentTo 'receptor ligand activity' that 'part of' some 'cell-cell
signaling'*

intracellular signaling ligand activity: EquivalentTo 'receptor ligand activity' that 'part of' some 'signal transduction'*  ???

\* Some work on the partonomy of cell communication. cell-cell signaling & ST is likely to be required.

- [x] TODO - check usage of receptor agonist activity in curation corresponds to ligand as defined above.
- [x] TODO - Rename receptor agonist activity, adding new definition.
- [ ] TODO - Add rule for inferring 'ligand receptor activity' from has_ligand
- [ ] TODO - Work on partonomy of cell communication to ensure that terms are available for part relations => reliable formal definition of 'receptor ligand activity', signaling receptor activity etc.  This should be a separate ticket.

CC @vanaukenk

**Comment by vanaukenk** [comment]
Checked usage of 'receptor agonist activity' in experimentally supported annotations.  

Nearly all annotated entities correspond to secreted polypeptide ligands.  

Other annotated entities include a transmembrane ligand, an Sfrp (Secreted frizzled-related protein), a bacterial lipoprotein, and tau.  Most of these annotations would be fine if 'receptor agonist activity' became 'receptor ligand activity'.  

We may want to review the Sfrp (enough evidence to annotate to 'receptor ligand activity'), bacterial lipoprotein (receptor is a host protein), and tau (normal physiological function?)  annotations.

**Comment by dosumis** [comment]
Draft edit with new def here: 
https://github.com/geneontology/go-ontology/commit/230c041365d44fee5b8d6c55e1e623a6b9cd9336

**Comment by pgaudet** [comment]
Looks good!!

**Comment by vanaukenk** [comment]
Note: revise logical def of 'receptor ligand activity' to make sure we don't get parentage to 'signal transducer activity', since this term is not meant to be used for annotation of signaling ligands.

**Comment by dosumis** [comment]
> Update: revise logical def of 'signal transducer activity', so that we don't get an inference that 'receptor ligand activity' is a child of 'signal transducer activity':

> 'molecular_function' and (part_of some 'signal transduction')

I think the best solution is to simply remove 

'receptor ligand activity' SubClassof: part_of some 'signal transduction'

This change is already in place. 

![image](https://user-images.githubusercontent.com/112839/30207086-38f362a4-9486-11e7-849f-5dc9187b4acd.png)

No inference to signal transducer as superclass:

![image](https://user-images.githubusercontent.com/112839/30207189-90a65e0c-9486-11e7-96c0-71535fa527a6.png)

**Comment by dosumis** [comment]
One more small change:  As outlined in MF refactoring doc, not all ligands activate receptor effector functions:  The best known example is the hedgehog receptor patched, which actively inhibits smoothened activity when not bound by hedgehog.

In place of 'is_a: receptor activator activity', we now have:

![image](https://user-images.githubusercontent.com/112839/30207395-50852c12-9487-11e7-8ecf-040f51cfc274.png)
