### ISSUE TITLE
adapt definition of GO:0007342 so it fits not only mammals

### ISSUE THREAD

**Issue by uhinz** [geneontology/go-ontology#14123]
Fusion of sperm to egg plasma membranes occurs in many taxons, in plants, plasmodium (see e.g. PubMed=21209845), mammalia, etc, and it would be good to have an appropriate GO term for this.
Would it be possible to simplify the definition of the term "GO:0007342 fusion of sperm to egg plasma membrane" so it can be used for a wide range of organisms?
The new definition might simply read "The binding and fusion of a sperm with the plasma membrane of the oocyte. "
The present version applies only to mammals - a pity!
Many thanks in advance, Ursula

**Comment by uhinz** [comment]
Please note, the simplified definition should then be directly linked to  "GO:0009566 fertilization", since plants have "GO:0009567 double fertilization forming a zygote and endosperm" vs " GO:0007338 single fertilization" for mammals.

**Comment by uhinz** [comment]
Please note, the simplified definition should then be directly linked to  "GO:0009566 fertilization", since plants have "GO:0009567 double fertilization forming a zygote and endosperm" vs " GO:0007338 single fertilization" for mammals.

**Comment by ukemi** [comment]
In plants, is the pollen considered sperm? @tberardini @lreiser ?
However, the definition does need to be changed since it doesn't account for ameboid sperm in nematodes.

**Comment by uhinz** [comment]
yes, pollen is considered sperm (see https://www.ncbi.nlm.nih.gov/pubmed/?term=arabidopsis+sperm)
Generally speaking, when a sexual species has one small, motile gamete, and a large, non-motile gamete, people use the terms sperm and egg/ovule.

**Comment by tberardini** [comment]
"GO:0007342 fusion of sperm to egg plasma membrane"  is a child of 'single fertilization'.  

 http://amigo.geneontology.org/amigo/term/GO:0007342

 I think if a term/s that is similar to this one that is desired for plants with double fertilization (either forming two zygotes or forming a zygote and endosperm), specific terms that describe those processes should be created instead of modifying the existing term definition and term relationships which are already quite clear. 

The existing definition of GO:0007342 fusion of sperm to egg plasma membrane"  could be modified to include the phrase, "...in the process of single fertilization" to make that more explicit.

**Comment by uhinz** [comment]
Getting the hierarchy right is definitely an issue. 
- I'd be perfectly fine with a new term that fits plants (fusion of sperm to egg plasma membrane during double fertilization), 
- plus a change of the current definition of "fusion of sperm to egg plasma membrane during single fertilization", so that it fits also non-mammalian species.
- please note, there is an orphan (unused) GO term (http://www.ebi.ac.uk/QuickGO-Old/GTerm?id=GO:0009677#term=info) that maybe should be obsoleted - I found double fertilization only in the context of plants, but that may simply be due to my ignorance

**Comment by ukemi** [comment]
It looks to me like GO:0009677 is a legitimate term:
PMID:25667083 

If you would like the additional term for double-fertilization, could one of you supply an appropriate definition and parentage?

**Comment by uhinz** [comment]
- Thanks for PMID:25667083, I retract my suggestion to obsolete http://www.ebi.ac.uk/QuickGO-Old/GTerm?id=GO:0009677#term=info

-  I'd be glad about a new term equivalent to "GO:0007342 fusion of sperm to egg plasma membrane", but unlike GO:0007342 = a child of 'single fertilization', the new term should be a child of GO:0009567 'double fertilization forming a zygote and endosperm'.

Proposal for the definition: "The binding and fusion of a sperm with the plasma membrane of the oocyte in the process of double fertilization. "

**Comment by tberardini** [comment]
Revised definition proposal:  "The binding and fusion of a sperm with the plasma membrane of the **egg cell** in the process of double fertilization. "

Rabbit hole:  There are several cell fusion events in double fertilization forming a zygote and endosperm: the fusion of one sperm with the egg cell and the fusion of another sperm with the central cell.   "...the central cell likely promotes its own fertilization by a yet unknown signaling mechanism."  There's a mutant where the second fertilization event  (central cell) doesn't occur.

Also: "Recently, even a third cell fusion event was reported in Arabidopsis[88], occurring between the fertilized central cell and the persisting synergid cell, thereby preventing the attraction of multiple pollen tubes"  

!!!

http://www.sciencedirect.com/science/article/pii/S0960982215015584
PMID:26859271

**Comment by lreiser** [comment]
Coming in a little late...
Regarding pollen. Pollen is synonymous with male gametophyte. In higher plants this represents the very reduce haploid stage. Pollen grains are more than sperm cells, the contain vegetative nuclei that are important during pollen tube germination and growth. Pollen are multicellular. Therefore pollen!=sperm.

**Comment by ukemi** [comment]
So do we want an additional term, and if so what should it be? I will modify the current term to be restricted to single fertilization and will tweak the def to include sperm without a flagellum. But you are far more qualified to come up with the terms for plants.

**Comment by pgaudet** [comment]
Hello, 

Not that I know anything about this but it seems like in this case the same term may me used to represent analogous structures rather than homologous structures. To avoid TPV two terms seem more appropriate. 

Pascale

**Comment by uhinz** [comment]
thanks, so could you please create a separate term for "The binding and fusion of a sperm with the plasma membrane of the egg cell in the process of double fertilization." ?  

Target of this annotation: the fusogen HAP2/GCS1  (see e.g. https://www.ncbi.nlm.nih.gov/pubmed/28137780 and other recent papers about this protein: https://www.ncbi.nlm.nih.gov/pubmed/?term=hap2+gcs1).

.

**Comment by ukemi** [comment]
We currently have two terms to describe double fertilization. Do we need terms for both?

I have modified the name and definition of the existing term.

**Comment by lreiser** [comment]
@ukemi weren't there two instances. One double fertilization that produces a 2n embryo and endosperm (3n, GO:0009567) and one that produces two 2n structures (embryo and rudimentary embryo, GO:0009677). So not the same.

**Comment by ukemi** [comment]
There are two classes. So do I need to make both:
'fusion of sperm to egg plasma membrane involved in double fertilization forming a zygote and endosperm'
and
'fusion of sperm to egg plasma membrane involved in double fertilization forming two zygotes'
?

**Comment by lreiser** [comment]
At the moment I think one term could suffice and be true for both types of double fertilization as they both refer to the fusion of a sperm cell with an 'egg cell' membrane.
In other words- this term would be  a part of both types of double fertilization.

But not all types of double fertilization would have  sperm- central cell fusion or sperm-synergid fusion. should those terms need to be added.

**Comment by ukemi** [comment]
We can't have the one term be part of both of the types because making the part_of relationship between two terms means that in every instance of the fusion, it would be part of an instance of the process, in this case every fusion would be part of both processes.

**Comment by lreiser** [comment]
OK so then we need to have the two new terms in order to avoid violating the rules....;)

**Comment by ukemi** [comment]
OK. Then I will add both terms and sort out existing terms to fit the new structure. Let me know if you spot anything amiss.
