### ISSUE TITLE
Obsolete MF-type process term involved  in process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14137]
Chatting with Pascale about
https://github.com/geneontology/go-ontology/issues/14030
resolution

GO:0042787 protein ubiquitination involved in ubiquitin-dependent protein catabolic process which is really the same as 
protein ubiquitin ligase part_ of ubiquitin-dependent protein catabolic process

Might be a good time to deal with all terms  of this type:

These are the "phosphorylation" ones, for example:

![involved_in](https://user-images.githubusercontent.com/7359272/29935688-8cd0291c-8e77-11e7-81ee-f88c1f78857b.jpg)

Especially if we do decide eventually to  remove single cell process from BP
https://github.com/geneontology/go-ontology/issues/12859
This could be a "fist step" in this direction. It would be a good way to focus people  to see if the terms are required (and remove many of the EXP annotations, so we can see what is left)

**Comment by pgaudet** [comment]
Hi @ValWood 
Is there anything to do here?

**Comment by ValWood** [comment]
I thought we were going to try to get rid of "protein modification involved in blah"
in favour of  
MF ubiquitin ligase part_of  BP  ubiquitin-dependent catabolic process.

I even thought we had already don the "protein ubiquition involved in " ones but  PomBase still has quite a lot....

**Comment by ValWood** [comment]
This is a baby step towards
https://github.com/geneontology/go-ontology/issues/12859

can discuss next week.

**Comment by ValWood** [comment]
There is very little  EXP annotation to the "protein phosphorylation involved in"

1 CDC28	involved_in	GO:1990801    protein phosphorylation involved in mitotic spindle assembly
could be CDC28	 protein serine/threonine kinase involved_in involved in mitotic spindle assembly

GO:1902002    protein phosphorylation involved in cellular protein catabolic process
6 annotations SGD 
only  CDC2 and MCk1


GO:1990803    protein phosphorylation involved in DNA double-strand break processing
1 annotation SGD CDC28

GO:1990802    protein phosphorylation involved in DNA double-strand break processing
1 annotation SGD CDC28


all could be 
protein kinase part of  DNA double-strand break processing etc if SGD @srengel  agree.

This would allow us to  stem any proliferation of this branch.

PomBase already have  lots of "protein kinase, substrate, involved in process"
of this type for CDC28 ortholog Cdc2

https://www.pombase.org/gene/SPBC11B10.09

**Comment by srengel** [comment]
these suggested changes sound fine to me.  i'll take a closer look, will update annotations, then will post here what i did...

**Comment by srengel** [comment]
CDC28 had 6 annotations to terms like 'protein phosphorylation involved in blah'.  i changed them all to the equivalent 'blah' term:

protein phosphorylation involved in cellular protein catabolic process |   | IMP | SGD | 2015-07-14 | has direct input P34233 | Liu Q, et al. (2011)PMID:21098119
protein phosphorylation involved in cellular protein catabolic process |   | IGI with P38634 | SGD | 2015-07-14 | has direct input P38634 | Kõivomägi M, et al. (2011)PMID:21993622
protein phosphorylation involved in mitotic spindle assembly |   | IGI with P30283 | SGD | 2015-08-11 | has direct input P50275 | Juanes MA, et al. (2011)PMID:21558801
protein phosphorylation involved in DNA double-strand break processing |   | IMP | SGD | 2015-08-11 | has direct input P38859 | Chen X, et al. (2011)PMID:21841787
protein phosphorylation involved in protein localization to spindle microtubule |   | IMP | SGD | 2015-08-11 | has direct input P38991 | Zimniak T, et al. (2012)PMID:22521784
protein phosphorylation involved in double-strand break repair via nonhomologous end joining

**Comment by srengel** [comment]
updated the 4 MCK1 annotations to cellular protein catabolic process GO:0044257.

i didn't see any annotations like 'protein phosphorylation involved in blah' to budding yeast CDC2 (aka POL3). maybe that was a typo and it was only CDC28 and MCK1?

anyway, i think my action is done.  if i missed something please let me know.

**Comment by ValWood** [comment]
Obsolete the following
GO:1990801   protein phosphorylation involved in mitotic spindle assembly
GO:1990802   protein phosphorylation involved in DNA double-strand break processing
GO:1990804   protein phosphorylation involved in double-strand break repair via nonhomologous end joining
GO:1990803   protein phosphorylation involved in protein localization to spindle microtubule
GO:1902002   protein phosphorylation involved in cellular protein catabolic process
(now have no annotations)

Good to get rid now SGD and PomBase have migrated annotations before others use....

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 
GO:1990801 protein phosphorylation involved in mitotic spindle assembly
GO:1990802 protein phosphorylation involved in DNA double-strand break processing
GO:1990804 protein phosphorylation involved in double-strand break repair via nonhomologous end joining
GO:1990803 protein phosphorylation involved in protein localization to spindle microtubule
GO:1902002 protein phosphorylation involved in cellular protein catabolic process

The reason for obsoletion is that they should be captured with a GO-CAM model. All existing manual annotations have been removed. There are no InterPro2GO mappings to this term. Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/14137. 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on April 11, 2018. Unless objections are received by April 11, 2018, we will assume that you agree to this change.

Thanks, 


Pascale
