### ISSUE TITLE
definition check?? for GTP-dependent protein binding - GO:0030742

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#14133]
I am reading PMID:26582389 which characterizes "GTP-dependent interactions of Arl13b with exocyst subunits:

> We also tested for the interaction between Arl13b and exocyst subunits in another ciliated cell type, NIH-3T3 mouse embryonic fibroblasts, and were able to confirm that Sec8, Exo70, and  Sec5 exhibit a GTP-dependent interaction with Arl13b (Figure 1C). Furthermore, we immunoprecipitated Arl13b from nonciliated HeLa cells and found that Sec8 and Sec5 are also enriched in the precipitates in a GTPγS-sensitive manner

So, I was going to annotate to this term:
**GTP-dependent protein binding - GO:0030742**
**Def:** Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) using energy from the hydrolysis of GTP.

However, this definition seems the opposite of what I would expect. Rather than the binding "**using energy from the hydrolysis of GTP**", as the definition above states, I always thought it was the opposite, that they bind when the have NOT hydrolyzed the GTP, as explained perfectly in this quote from the same paper:

> Because small G proteins preferentially bind their effectors when in the GTP-bound, active state, we incubated protein extracts with GTPγS, a nonhydrolyzable form of GTP, before performing the immunoprecipitations. For comparison, we used samples preincubated with GDP. We found that preincubation with GTPγS dramatically increases the coimmunoprecipitation of Sec8 with Arl13b compared with the GDP control

Looking for confirmation that others agree that the current definition is in error before I spend any time coming up with a proposal for a revision. @ValWood @ukemi @pgaudet can you help confirm/deny that this definition is in error?

thanks,

-Karen

**Comment by ValWood** [comment]
@mah11 will probably know this.

**Comment by mah11** [comment]
> @mah11 will probably know this.

Sorry, I do not.

I also do not recall/know of any reason to argue against changing the definition, nor do I remember what the term was requested for (despite having added it some years ago, according to its ID).

**Comment by ValWood** [comment]
Hmm, it only has 37 EXP annotations too.  


http://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0030742&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

**Comment by pgaudet** [comment]
Hi @krchristie 
Looking at some annotations, it seems like it has been used to mean 'GO:0031267 small GTPase binding'.  It seems like your example is one of the few cases where the binding really is GTP-dependent. Here at the annotations: 

(15)	ParkinsonsUK-UCL @RLovering 
(13)	UniProt @sylvainpoux
(8)	MGI @hdrabkin 
(3)	TAIR @tberardini 
(2)	RGD @slaulederkind 

The safest solution may be to obsolete and create a new term where there definition really states that the binding only occurs in the presence of GTP. 

What do you think ? 

Thanks,
Pascale

**Comment by hdrabkin** [comment]
I t appears most of ours (18 genes total annotated directly to GO:0031267; not sure where the 8 MGI annotations come from; I'm looking in our db directly) ) are ISO from loads, 3 from PAINT One IPI from mouse_go load (GOA_ParkinsonsUK-UCL). Bottom line for us: whatever happens to sources will 'fix' what we have

**Comment by krchristie** [comment]
@pgaudet I am not sure that the fact that the annotations are to GTPases is necessarily a problem. Arl13b, the protein in the paper I cited is also a GTPase. However, the GTP-dependent binding to Arl13b is specifically things that bind to Arl13b when it is in the GTP bound state, and once the GTP is hydrolyzed, those proteins don't bind. My understanding is that this is very common for the small GTPases, and this usage is what I would have expected the term "GTP-dependent protein binding" to mean, which is why I was asking about the definition.

Did you look more closely at whether the papers actually indicate GTP-dependent binding, or did you just look at the fact that a lot of the annotated proteins are GTPases?

We should also consider whether this (or a replacement) term for "GTP-dependent protein binding" covers both directions of the interaction or not. While the quote that I included in the original question indicated that "**Sec8, Exo70, and Sec5 exhibit a GTP-dependent interaction with Arl13b**", i.e. non GTPase proteins bound to a GTPase when in the GTP bound state, it also seems that the binding of the GTPase Arl13b to the non-GTPase proteins is also GTP-dependent and thus it would be equally appropriate to use the same term for both partners of the interaction, i.e. for GTP-dependent protein binding both BY and TO the protein that is actually binding the GTP. This seems fine to me, especially since it seems tricky to come up with terms that would be clear to curators trying to pick the right term, but worth thinking it through.

**Comment by pgaudet** [comment]
@hdrabkin I was only talking about experimental, using the filters in AmiGO. (I usually ignore ISS, ISO, IBA - all non manual except InterPro2GO, which need to be changed manually).

**Comment by hdrabkin** [comment]
Ah, I think I misunderstood the grouping;
The 8 are for GO:0030742 , right, not  GO:0031267?
We DO have 8 IPI annotations go GO:0030742, of which 5 come from GOA_mouse load imports.

**Comment by tberardini** [comment]
Arabidopsis annotations from PMID:1699102

"...both recombinant AtRab proteins had an
ability to bind to the MYA2 tail 1 in **a GTP-dependent
manner** ..."  (more protein bound in the presence of GTP than without it)

**Comment by pgaudet** [comment]
Right, I was looking at GO:0030742.

**Comment by pgaudet** [comment]
Thanks @hdrabkin @tberardini 
I'll spot check a few others more closely and if they also describe GTP-dependent binding I'll update the definition to 
"Interacting selectively and non-covalently with a protein upon GTP binding by at least one of the interacting proteins."

Does that capture the function better @krchristie ? 

Thanks, Pascale

**Comment by krchristie** [comment]
Hi Pascale,

Since this is my ticket, no need for you to spot check the others, I'm doing that now actually. Your proposed def is definitely an improvement. :)

-Karen

**Comment by pgaudet** [comment]
Oh great :) 

thanks Karen !

**Comment by krchristie** [comment]
All of the experimental annotations have been made to indicate binding when one of the interactors is in the GTP-bound state. Thus it is clear that this term has been used in the way I thought it should be, and that the definition is not correct.

In the majority of cases, annotators have annotated BOTH interacting partners with the "GTP-dependent protein binding" term, regardless of which partner was bound to GTP, though for a few cases only the non-GTP bound protein was annotated with this term (3 fairly old UniProt annotations from PMID:9312003, PMID:11524421, & PMID:11880369, and 1 more recent paper annotated by ParkinsonsUK-UCL: PMID:25767741). Other papers annotated by both of those groups have annotated BOTH interacting partners with this term.

Since the interaction is GTP-dependent, it seems fine to me to that annotating both partners is fine, and this is consistent with the majority usage to date. Thus, I definitely plan to:

**Update the definition**, combining Pascale's suggestion with the current def: 
 **GO:0030742** - GTP-dependent protein binding
 **Def**: Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) when at least one of the  interacting partners is in the GTP-bound state.

Perhaps also add a comment regarding annotation usage, something like:
**Comment:** This term may be used to annotate both partners in a GTP-dependent binding interaction, both the GTP-bound protein and the protein(s) which interact with it.

**Comment by krchristie** [comment]
fixed here: https://github.com/geneontology/go-ontology/pull/14155/files
