### ISSUE TITLE
remove owl:Nothing axiom in go-plus

### ISSUE THREAD

**Issue by kshefchek** [geneontology/go-ontology#14142]
go-plus.owl contains the axiom:

    Class: owl:Nothing SubClassOf: owl:Nothing

Which is logically accurate, but seems to cause issues when reasoning with ELK.  Would it be possible to remove this axiom?

**Comment by cmungall** [comment]
@dougli1sqrd can you look at this? Is it being inserted by robot reasoning? If so can we update robot? Alternatively we may need to use robot to do a sparql update to delete the axiom

**Comment by cmungall** [comment]
It looks like it's coming from uberon_import

@balhoff reported this: https://github.com/obophenotype/uberon/issues/1374

**Comment by kshefchek** [comment]
Thanks!
