### ISSUE TITLE
IPR029523 & UniProtKB-KWs

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14141]
pombe ino80 complex subunits have IEAs to regulation of transcription from RNA polymerase II promoter &  regulation of transcription, DNA-templated
e.g. IPR029523 & UniProtKB-KW:KW-0805 & UniProtKB-KW:KW-0804  

the ino80 complex moves nucleosomes around thereby regulating nucleosome density.

It seems to me like ino80 function is upstream of regulation of transcription? Unless ino80 is directly involved in the recruitment of factors (which I don't think it is?) it "just" makes the chromatin accessible to other factors (which could be involved in repair, transcription, replication....anything where proteins need access?)
@ValWood  thoughts?

**Comment by ValWood** [comment]
yep it seems indirect. Should it be nucleosome positioning?
http://www.ebi.ac.uk/QuickGO/term/GO:0016584

**Comment by Antonialock** [comment]
I thought the definition didn't exactly apply
"Ordering of successions of nucleosomes into regular arrays so that nucleosomes are positioned at defined distances from one another."

I annotated to

regulation of nucleosome density
--
Definition | Any process that modulates the number of nucleosomes in a given region of a chromosome.

**Comment by ValWood** [comment]
Oh yes positioning doesn't seem quite right.

**Comment by ValWood** [comment]
wrong tracker. Will move to annotation tracker.
