### ISSUE TITLE
New children of GO:0090544 BAF-type complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14143]
Please create:

1.
Name: mBAF complex
Def: "A muscle cell-specific SWI/SNF-type complex that contains eight to fourteen proteins, including both conserved (core) and nonconserved components; contains the ATPase product of either the SMARCA4/BAF190A/BRG1 gene, the mammalian ortholog of the yeast SNF2 gene, or the  SMARCA2/BAF190B/BRM gene, the mammalian ortholog of the Drosophila brm (brahma) gene, or an ortholog of either of these genes, and the muscle-specific product of the DPF3/BAF45C gene or an ortholog thereof."
Relationship:
is_a GO:0090544 BAF-type complex
Synonyms:
muscle-type BAF complex [exact]
muscle-type SWI/SNF complex [exact]
muscle-specific BAF complex [exact]
muscle-specific SWI/SNF complex [exact]
GOC ID:bhm 

2.
Name: bBAF complex
Def: "A brain-specific SWI/SNF-type complex that contains eight or nine proteins, including both conserved (core) and nonconserved components; contains the ATPase product of either the SMARCA4/BAF190A/BRG1 gene, the mammalian ortholog of the yeast SNF2 gene, or the  SMARCA2/BAF190B/BRM gene, the mammalian ortholog of the Drosophila brm (brahma) gene, or an ortholog of either of these genes. Compared to the neuron-specific nBAF complex (GO:0071565) it does not contain DPF1, DPF3 or SMARCC1 or their orthologs. May contain PB1/BAF180."
Relationship:
is_a GO:0090544 BAF-type complex
Synonyms:
brain-specific BAF complex [exact]
brain-specific SWI/SNF complex [exact]
GOC ID:bhm 

Name: esBAF complex
Def: "An embryonic stem cell-specific SWI/SNF-type complex that contains eight or nine proteins, including both conserved (core) and nonconserved components; contains the ATPase product of either the SMARCA4/BAF190A/BRG1 gene, the mammalian ortholog of the yeast SNF2 gene, or an ortholog thereof. Compared to many other BAF complexes never contains ACTL6B/BAF53B, ARID1B/BAF250B, SMARCA2/BRM, SMARCC2/BAF170 or SMARCD3/BAF60C but contains PHF10/BAF45A, DPF2/BAF45D and possibly one of BCL7A/B/C."
Relationship:
is_a GO:0090544 BAF-type complex
Synonyms:
embryonic stem cell-specific BAF complex [exact]
embryonic stem cell-specific SWI/SNF complex [exact]
GOC ID:bhm 

Thanks, Birgit

**Comment by ValWood** [comment]
Can we avoid gene names in these and use  functions/families?
It's much easier for curators to establish if they can tick off all of the required components.
This would make it much easier to establish if we are talking about the same complex in different species.
it isn't clear to me which species the names above are from (is it one species with synonyms? or different species names?)
We should avoid defining by  absent components if possible and just say which components are necessary (this should be possible unless a complex is an exact sub complex of another complex, in which case more usually this would be  a descendant described as a "core complex").

Otherwise it becomes very difficult for curators  to recognise the correct complex when annotating different species, hence the current proliferation.

**Comment by bmeldal** [comment]
> Can we avoid gene names in these and use functions/families?
It's much easier for curators to establish if they can tick off all of the required components.
This would make it much easier to establish if we are talking about the same complex in different species.

function/family is fine until we have to distinguish the type of Snf2 ortholog: is it actual SNF2 or the drome Brahma-type ortholog, both of which are of the same family.

> it isn't clear to me which species the names above are from (is it one species with synonyms? or different species names?)

I have referred to yeast Snf2, drome Brahma, mammalian xyz etc.

> We should avoid defining by absent components if possible and just say which components are necessary (this should be possible unless a complex is an exact sub complex of another complex, in which case more usually this would be a descendant described as a "core complex").

I added them here as otherwise the question will come constantly why this is a separate term and not the same as the canonical. nBAf =! bBAF and esBAF =! canonical SWI/SNF complex.

**Comment by pgaudet** [comment]
Created new terms
 [Term]
+id: GO:0140091
+name: mBAF complex
+namespace: molecular_function
+def: "A muscle cell-specific SWI/SNF-type complex that contains eight to fourteen proteins, including both conserved (core) and nonconserved components; contains the ATPase product of either the SMARCA4/BAF190A/BRG1 gene, the mammalian ortholog of the yeast SNF2 gene, or the SMARCA2/BAF190B/BRM gene, the mammalian ortholog of the Drosophila brm (brahma) gene, or an ortholog of either of these genes, and the muscle-specific product of the DPF3/BAF45C gene or an ortholog thereof." [GOC:bhm]
+synonym: "muscle-specific BAF complex" EXACT []
+synonym: "muscle-specific SWI/SNF complex" EXACT []
+synonym: "muscle-type BAF complex" EXACT []
+synonym: "muscle-type SWI/SNF complex" EXACT []
+is_a: GO:0090544 ! BAF-type complex
+relationship: part_of CL:0000187 ! muscle cell
+created_by: pg
+creation_date: 2017-09-05T09:20:45Z
+
+[Term]
+id: GO:0140092
+name: bBAF complex
+namespace: molecular_function
+def: "A brain-specific SWI/SNF-type complex that contains eight or nine proteins, including both conserved (core) and nonconserved components; contains the ATPase product of either the SMARCA4/BAF190A/BRG1 gene, the mammalian ortholog of the yeast SNF2 gene, or the SMARCA2/BAF190B/BRM gene, the mammalian ortholog of the Drosophila brm (brahma) gene, or an ortholog of either of these genes. Compared to the neuron-specific nBAF complex (GO:0071565) it does not contain DPF1, DPF3 or SMARCC1 or their orthologs. May contain PB1/BAF180." [GOC:bhm]
+synonym: "brain-specific BAF complex" EXACT []
+synonym: "brain-specific SWI/SNF complex" EXACT []
+is_a: GO:0090544 ! BAF-type complex
+relationship: part_of UBERON:0000955 ! brain
+created_by: pg
+creation_date: 2017-09-05T09:22:41Z
+
+[Term]
+id: GO:0140093
+name: esBAF complex
+namespace: molecular_function
+def: "An embryonic stem cell-specific SWI/SNF-type complex that contains eight or nine proteins, including both conserved (core) and nonconserved components; contains the ATPase product of either the SMARCA4/BAF190A/BRG1 gene, the mammalian ortholog of the yeast SNF2 gene, or an ortholog thereof. Compared to many other BAF complexes never contains ACTL6B/BAF53B, ARID1B/BAF250B, SMARCA2/BRM, SMARCC2/BAF170 or SMARCD3/BAF60C but contains PHF10/BAF45A, DPF2/BAF45D and possibly one of BCL7A/B/C." [GOC:bhm]
+synonym: "embryonic stem cell-specific BAF complex" EXACT []
+synonym: "embryonic stem cell-specific SWI/SNF complex" EXACT []
+is_a: GO:0090544 ! BAF-type complex
+created_by: pg
+creation_date: 2017-09-05T09:23:51Z


@bmeldal do you have any PIMIDs you'd like to refer to ?
@ValWood last call for further comments ! 

Thanks, Pascale

**Comment by bmeldal** [comment]
Sorry, Pascal, forgot PMIDs.

mBAF: 8804307, 8895581, 15525990, 11175787, 12620226
bBAF: 8804307, 8895581, 12368262, 17640523, 17920018, 15525990, 12620226
esBAF: 8804307, 8895581, 19279220, 19279218, 12620226
