### ISSUE TITLE
what do we mean when we annotate to growth and cell growth

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14157]
For yeast we tend to ignore these terms, because at the end of the day everything is involved in growth, or proliferation, or both.

We would only use descendant  "regulation of growth terms" for the signalling which   regulates  cell size  (i.e controls growth)  which we still know not too much about. 

However I notice that  CAFA annotated some  pombe gene product involved in  "translation" to "growth". Now I would like to query this, but first I'd like to understand what the policy is because  
it isn't  incorrect, translation is an integral part of growth.

If we think this would be a valid annotation, then "cytoplasmic translation" and "energy generation" etc  would be a descendant of growth.

"Growth" actually has only 13,000 annotations which isn't many as I could immediately annotated a few  thousand  pombe gene products to it in one fell swoop in its loosest  meaning (a gene required for viability/proliferation).

Is there anyway we can restrict  the use of these terms?

**Comment by ValWood** [comment]
I'm filtering any external annotations from these 2 terms
GO:0040007
GO:0016049

**Comment by ValWood** [comment]
(we capture things related to growth with phenotype annotations, and concentrate on physiological functiona for GO)

**Comment by pfey03** [comment]
Just a comment: While all Dicty researchers talk about growth when they look at 'growth rates' in Dicty, we annotate to 'cell proliferation' when applicable. As 'cell growth' is "The process in which a cell irreversibly increases in size over time..." and that doesn't apply.

Changes in cell size we also just annotate in phenotypes and are rather rare.

**Comment by bmeldal** [comment]
We are starting to annotate plants (arath) and the first complex, the evening complex (EC), represses a set of gene that affect hypocotyl elongation (the first bit of the stem that germinates out of the seed). Now, it affects growth (negatively!) by acting as a neg reg transcription factor. Do we just annotate to GO:0000122 negative regulation of transcription from RNA polymerase II promoter or also to GO:0045926 negative regulation of growth?

Just putting it out there...

**Comment by pgaudet** [comment]
Hello, 

I personally don't mind these annotations. It's true that most genes are involved in growth and cell growth somehow or other, but these terms are high enough in the hierarchy  as no to cause false inferences. 

If translation is annotated to growth/cell growth, everything should eventually be, and in that case this class would never be enriched. 

@ValWood do you have suggestions to restrict usage ? 

Thanks, Pascale

**Comment by ValWood** [comment]
The problem is that we would pick up a few, or a few 100  annotations,  and people would think these really were the set of genes involved in growth. Our users would likely ask why have you annotated gene x to growth but not gene y.

If we used these term we would want to do so consistently, but we could literally annotate everything to one or both term. 

In fact  if the ontology was correct "mitotic cell cycle" would be a child of proliferation?
The ontology does not really model the processes which contribute to growth (i.e translation), or proliferation well. If it did, I would be more inclined to use them, but it would be impractical, and almost impossible to model well.

But it isn't a problem, because we will just filter these annotations. We capture effects on viability (which most people mean when they say "required for growth")  consistently with phenotypes already.

"Multicellular organismal growth"  as in Birgit's example is a bit more specific than "cell growth" This might be:  http://www.ebi.ac.uk/QuickGO/term/GO:0080189 ?

Interestingly, in AmiGO there is not a single Experimental annotation directly to cell-growth (only ISO and IEA), so it clearly isn't a term that curators generally feel  is useful.

**Comment by bmeldal** [comment]
I suppose it's GO:0008283 cell proliferation I'm looking for, or an appropriate child "hypocotyl proliferation". There are lots of tissue-specific proliferation terms. Should I request a new one???

**Comment by tberardini** [comment]
@bmeldal : hmmmm, do you really want to annotate the difference in hypocotyl elongation phenotype?  That's frequently due to changes in cell elongation (more = longer hypocotyl, less = shorter hypocotyl) and people often look at cell sizes and compare to wt in these types of experiments.  We (TAIR) tend to capture that more as phenotype OR as pos/neg regulation of unidimensional cell growth.   So, I'd say no to a new term called 'hypocotyl proliferation'.  
http://browser.planteome.org/amigo/term/PO:0020100#display-lineage-tab
My 2 cents.

**Comment by bmeldal** [comment]
Thanks, @tberardini that makes sense. 

PS: I've not done anything on plants since my seaweed ecology module(s) 20 years ago! We've just started arath curation thanks to an intern who'll be with us for a year from now. Some scope for learning for me while checking the entries.

**Comment by pgaudet** [comment]
@ValWood @bmeldal 
is there an action point here ?

**Comment by bmeldal** [comment]
@ValWood 's original question was:

> Is there anyway we can restrict the use of these terms?

**Comment by ValWood** [comment]
here is a suggestion.

These are ALL EXP annotations to "cell growth"
Clearly not used consistently at all.

(31) | UniProt
 (29) | TAIR
 (21) | AgBase
 (19) | GeneDB
 (15) | FlyBase
 (13) | dictyBase
 (10) | MGI
 (8) | RGD
 (3) | UniProtKB
(2) | AspGD
 (2) | CACAO
 (2) | HGNC
 (2) | MTBBASE
 (1) | BHF-UCL
 (1) | PAMGO_MGG
 (1) | SGD
(1) | WB

 We could add "not for direct annotation".
if people are only observing "no growth" or "cell death", maybe this is not providing anything useful about the process.

**Comment by pfey03** [comment]
I found 12 for Dicty and either deleted or updated to 'asexual reproduction' (this is the term we use as cell proliferation is also 'forbidden' for single cell population expansion - made mistake above).

I had to dispute one annotation in P2GO that is external.

There are still 3 NOT annotations where people made it a point to look at cell mass. But maybe not so important if term will be dropped I can recheck those.

Note I made these updates in P2GO but our pipeline is currently broken and they will only update in QuickGO eventually.

Thanks Val!

**Comment by ValWood** [comment]
Thanks @pfey03  In that case it sounds as though these are worth a few others checking out.

if there is a consensus between active curatoion groups  we can add "do not annotate"?

@slaulederkind 
@srengel 
@vanaukenk 
@ukemi

**Comment by ValWood** [comment]
@hattrill 
@RLovering

**Comment by hattrill** [comment]
I am happy with slapping a "do not manually annotate to" on it. I don't want the FB lot using it and will stop any rogue curators.

**Comment by pfey03** [comment]
I'm also happy with not manually annotating it that will also deter external annotators not using because in Dicty literature everyone calls it cell growth.

Will then also take care of the 3 NOT annotations remaining for now.

**Comment by RLovering** [comment]
ok thanks for spotting these. annotations removed
Ruth

**Comment by tberardini** [comment]
okay, I will look at the TAIR ones.  Can't promise as quick a turnaround as the others but I will get there in the next week.

**Comment by vanaukenk** [comment]
I've looked at two WB annotations (one IGI and one ISS) and deleted them both.  

It might be worthwhile to also look at some of the child terms, e.g. cell growth involved in cardiac muscle cell development http://amigo.geneontology.org/amigo/term/GO:0061049

Would any of these gene products instead be involved in regulation?
@slaulederkind 
@RLovering 

We could add a 'not for manual annotation' flag if everyone agrees that is appropriate.

**Comment by srengel** [comment]
there was one IPI annotation to cell growth in SGD.  i deleted it just now in P2GO.

**Comment by ukemi** [comment]
Someone here will have a look at the mouse ones. I suspect that if they are warranted we really should have annotated to a regulation term. There are certainly cases where stimuli cause cells to get bigger and it is true cell growth, not proliferation.

**Comment by tberardini** [comment]
TAIR annotations: 28 papers to look at, annotations mostly from the years 2004-2010.

**Comment by slaulederkind** [comment]
I'ved removed all of the manual rat annotations to "cell growth" at RGD, except one which comes from BHF-UCL.

**Comment by tberardini** [comment]
I've revisited and reannotated all TAIR annotations from those 28 papers.  The remaining _A. thaliana_  'cell growth' annotations are from InterPro (IEA) and UniProtKB (IMP) and I cannot edit those.

**Comment by pgaudet** [comment]
@ggeorghiou Can you please look at direct EXP annotations to "cell growth" by UniProt and see if they can be moved? 

@LiNiMGI Perhaps you can have a look on behalf of MGI ?

I will put a do_not_annotate label on this term. 

Thanks, Pascale
