### ISSUE TITLE
logical defs for photoreceptor activity suclasses

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#14151]
based on this logical def:

![image](https://user-images.githubusercontent.com/112839/30065080-aac0bf22-924b-11e7-9f0d-f57101c883b1.png)  (this is currently in a branch)

We can define 'blue light photoreceptor activity' etc using the same pattern, but adding new classes under 'detection of light stimulus'

But note: we also have 'blue light signaling pathway'  & 'cellular response to blue light'.

**Comment by vanaukenk** [comment]
Need to discuss what the design pattern will be for receptor activity.  There is a draft here:

https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/draft_patterns/membrane_receptor_activity_draft.yaml

**Comment by pgaudet** [comment]
LD has been removed - this will come up in the DP project if we need to fix it 
https://github.com/geneontology/go-ontology/projects/16
