### ISSUE TITLE
NTR: nucleotide repair terms

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#14163]
A recent Science paper (PMID 28596309) described the repair of glycated nucleotides/DNA/RNA by the DJ-1 family of enzymes.  I think there could be a number of new terms under DNA repair analogous to protein deglycation, GO:0036525.  Perhaps there should also be a new parent term for nucleotide repair.  In addition, there should be a number of MF terms for DNA/RNA/nucleotide deglycase activities.

Thanks,
Ingrid

**Comment by krchristie** [comment]
Hi Ingrid,

This seems reasonable, but could you provide more details for the BP and MF terms you want. I'm also not sure what mean by "a new parent term for nucleotide repair". There are a lot of terms for "nucleotide-excision repair", but what you're talking about, repair of nucleotides seems a lot different than nucleotide-excision repair.

This isn't an area I'm familiar with, so please suggest term names, definitions, and parentage for the specific terms that would be useful to you.

Also, what initials do you use to credit term definitions to you?

thanks,

-Karen

**Comment by krchristie** [comment]
@keseler - Could you please provide more specifics of what new terms you would like, specifically, at least a proposal for what you need, with this type of info for each term:

- Term name
- Definition
- Definition dbxrefs - [include both PMIDs and curators who contribute, e.g. GOC:krc]
- Other dbxrefs - IDs for similar or equivalent entities in other databases, e.g. EC #'s, IntAct IDs, etc.
- Parentage

I can help make sure everything conforms to GO practice, but I really need a proposal from you for what terms you need before I can do anything for this.

thanks, Karen

**Comment by keseler** [comment]
Hi Karen,

Sorry I dropped the ball here.  After I submitted the NTR, I found out that a SwissProt curator had already requested a few new terms based on the same paper and got these three:
GO:0106044 guanine deglycation
GO:0106045 guanine deglycation, methylglyoxal removal
GO:0106046 guanine deglycation, glyoxal removal
In addition to those, I am wondering whether it would be useful to have a parent "nucleotide repair" term; i.e. just like the protein deglycation term is a child of both cellular protein modification process and protein repair, these three terms could have a new "nucleotide repair" parent.  A proposed definition, analogous to "protein repair", would be "The process or restoring a nucleotide to its original state after damage." In addition, one could argue that "DNA repair" and "RNA repair" should also be parents of the deglycation terms.

I was also thinking of a new MF term "nucleotide deglycase activity" analogous to "protein deglycase activity" with definition "Catalysis of removal of a carbonyl group from a glycated nucleotide".  It looks like this might also require a new parent term "catalytic activity, acting on nucleotides", because the enzyme apparently can act on free nucleotides as well as nucleotides in the context of DNA and RNA; it should also have GO:0016836 as a parent.

Is this sufficient information?  I also think it would be prudent to double-check with others (maybe the person from SwissProt who requested the original BP terms).

Thanks, and Happy Turkey Day! :-)
-Ingrid

**Comment by krchristie** [comment]
Hi Ingrid,

Sorry so slow to get back to you on this. I was swamped with major revisions on a manuscript for much of December.

Regarding the idea of adding a new MF term "nucleotide deglycase activity", this doesn't currently seem merited considering that the only child terms would be specific to guanine. I just talked to @hdrabkin who worked on the previous ticket to put in the three guanine deglycalation terms:  NTR: deglycation terms #13827 

We are both thinking that there is no need for additional terms in either MF or BP until there are more children in this area which would benefit from the grouping terms.

I'm going to close this since I think no further action is required, but if you disagree Ingrid, reopen it with the specific actions you think are needed.

thanks,

Karen
