### ISSUE TITLE
IPR010684

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14162]
pombe pof4 has an IEA to regulation of transcription, DNA-templated via IPR010684

pof4 is elongator A so presumably this IEA could be refined to "regulation of transcription from RNA Pol II promoter"?

**Comment by ukemi** [comment]
wrong tracker?

**Comment by Antonialock** [comment]
cheers

**Comment by ValWood** [comment]
and "elongin" not elongator (the wobble tRNA modifier)
