### ISSUE TITLE
JAK/STAT related term: positive regulation of TF dimerization activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14164]
Hi

from JAK/STAT pathway - Signaling Project #1628 

The term "JAK-induced STAT protein dimerization" (GO:0007261) is obsolete, and the suggested alternatives are "tyrosine phosphorylation of STAT protein" (GO:0007260) and "protein dimerization activity" (GO:0046983).

However, if we want to annotate a JAK protein and describe that it regulates the dimerization of STATs it would be good to have a term for this, which can include additional information about the proteins dimerized in the AE field.

Would it be possible for any of the following terms to be created:

GO:0046983 protein dimerization activity
> regulation NTR: regulation of protein dimerization activity
>> is_a NTR: positive regulation of protein dimerization activity
>>> is_a NTR: positive regulation of transcription factor dimerization activity
>>>> is_a NTR positive regulation of STAT family dimerization activity
>>>> is_a NTR: positive regulation of transcription factor homodimerization activity
>>>> is_a NTR: positive regulation of transcription factor heterodimerization activity

>GO:0042803 protein homodimerization activity
>> GO:0043496 regulation of protein homodimerization activity
>>>GO:0090073 positive regulation of protein homodimerization activity
>>>> is_a NTR: positive regulation of transcription factor homodimerization activity
>>>>> is_a NTR positive regulation of STAT family dimerization activity

GO:0097677 STAT family protein binding
> positive regulation NTR: positive regulation of STAT family dimerization activity

I have included the STAT specific terms, but appreciate that these might not be acceptable. They do however provide a useful description.

I will also request positive regulation of STAT transcription factor activity, which in many ways is the equivalent statement and perhaps this would be the preferred term, if only one was available.

Please add the following DbxRefs to any of the terms created:
DbxRef: GOC:BHF
DbxRef: GOC:rl
DbxRef: GOC:ga
PMID:28637459

Thanks 

Ruth

@gantonazzo

**Comment by ukemi** [comment]
We should discuss this as part of the signaling project report on an annotation call.

**Comment by vanaukenk** [comment]
@ukemi and I made a draft JAK-STAT signaling model based on a recent review.  We should look at this model on a call to see how we want to proceed with JAK-STAT BP terms.

http://noctua.geneontology.org/editor/graph/gomodel:5a7e68a100000016
https://www.ncbi.nlm.nih.gov/pubmed/28323260

See also:
#14165
#14166

**Comment by pgaudet** [comment]
We decided to annotate to 'regulation of protein complex assembly', so we close this. 

Thanks, Pascale
