### ISSUE TITLE
Lewy body formation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#14160]
I would like to see “Lewy body assembly” added as a child term of “inclusion body assembly (GO:0070841). Definition could be “The aggregation, arrangement and bonding together of a set of components to form a Lewy body.” “regulation of”, “positive…” and “negative…” children are also needed. Synonyms: Lewy body formation, positive…, negative…, and regulation of Lewy body formation.  PMID: 15158159

**Comment by pgaudet** [comment]
Hi @slaulederkind 
This does not seem like a normal process; I wonder if it's withing the scope of GO. 
@ukemi @vanaukenk what do you think ? 

Thanks, Pascale

**Comment by ukemi** [comment]
We have debated this in the past when we added Lewy Body terms as a cellular components. The argument was that they were found in tissues frequently in the absence of pathogenesis and might play a normal physiological role.

**Comment by pgaudet** [comment]
OK good !
