### ISSUE TITLE
Signaling project NTR: positive regulation of STAT transcription factor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14165]
Hi

from JAK/STAT pathway - Signaling Project #1628 

Please could the following new term be created:

GO:0051091 positive regulation of sequence-specific DNA binding transcription factor activity
>is_a NTR: positive regulation of STAT transcription factor activity
Definition: Any process that activates or increases the frequency, rate or extent of activity of the transcription factor STAT. 
see sibling term: GO:0051092 positive regulation of NF-kappaB transcription factor activity

DbxRef: GOC:BHF
DbxRef: GOC:rl
DbxRef: GOC:ga
PMID:28637459

Thanks

Ruth

@gantonazzo

**Comment by ukemi** [comment]
Would a molecular function be more appropriate?

**Comment by pgaudet** [comment]
Hi @ukemi 
A MF might be a good idea here. If we say that we remove sub-steps of the cascade as biological processes (such as STAT import in the nucleus), then the activation of the transcription factor should also be a MF. 

We could have a MF term, 'transcription factor regulator activity' and you could use that with an extension to describe that STAT is the target. 

@RLovering what do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@RLovering did you have a chance to look at this ?

**Comment by RLovering** [comment]
Your suggestion sounds good to me. Although I think we are still waiting for the JAK-STAT cascade #15395 term to be revised. Then I will try to sort out a table of annotations that need revision

Thanks

Ruth

@hattrill @gantonazzo

**Comment by pgaudet** [comment]
@RLovering Can you use the new term we created GO:0140537 transcription regulator activator activity ?

**Comment by RLovering** [comment]
Yes I agree this term looks like the right term, and better than the term I suggested - However:

Currently this term has the parent term: GO:0006355 regulation of transcription, DNA-templated. Would you recommend that the curator considered including more specific GO terms if appropriate: eg  GO:0006357 regulation of transcription by RNA polymerase II?

Looking at the ontology it looks like decisions need to be made about the relationship between regulation of gene expression or regulation of transcription for these functions. 

Currently GO:0140537 transcription regulator activator activity and GO:0140416 transcription regulator inhibitor activity have direct part of relations to regulation of gene expression. 

Whereas GO:0051090 regulation of DNA-binding transcription factor activity has the is_a parent GO:0006355 regulation of transcription, DNA-templated.

Would you expect the proteins associated with the MF GO:0140537 transcription regulator activator activity (that bind to a dbTFs) to also be annotated with BP GO:0051090 regulation of DNA-binding transcription factor activity? 

I know that we are now looking at proteins with a role in signaling pathways as being curated as regulating gene expression (rather than regulating transcription). Many of the proteins at the end of the signaling pathways, ie between the signaling pathway and the regulation of transcription, ie the proteins that bind the dbTF and coTFs and regulate their function will be annotated with the GO term GO:0140537 transcription regulator activator activity or GO:0140416 transcription regulator inhibitor activity. Should these be curated as regulating transcription or regulating gene expression, or both?

Or has the decision about the annotation of signaling proteins to regulating gene expression not yet been made?

Thanks
Ruth

**Comment by pgaudet** [comment]
We wont be creating this term - as per decision from the tickets jamboree Feb 2021. 

Please use a BP term such as GO:0097696 receptor signaling pathway via STAT or a regulation child. 

Or - maybe you can use
 GO:0140537 transcription regulator activator activity
or  GO:0140416 transcription regulator inhibitor activity 

Please reopen if this doesn't work for you. 

Thanks, Pascale
