### ISSUE TITLE
MP: Missing Parent DNA clamp unloader activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14161]
DNA clamp unloader activity
should have parent 
ATPase activity?

Definition
Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the opening of the ring structure of the PCNA complex, or any of the related sliding clamp complexes, and their removal from the DNA duplex. Source: PMID:23499004, 

@cmungall logical def should identify this parent ?

**Comment by ukemi** [comment]
I think that this should be a has_part ATPase activity.

**Comment by ValWood** [comment]
ah OK.
So, I need to make that annotation explicitly in addition to DNA clamp unloader activity currently.

**Comment by ValWood** [comment]
So I was just wondering, what is the other part then ? This  term is  specifically describing the ATPase activity  to open  PCNA?

**Comment by ukemi** [comment]
Interesting question that I also had. Presumably it would be the conformational change, which we don't capture.

**Comment by ValWood** [comment]
I think most biologists would consider this to be a single activity.

I will seem a bit odd because now we need to make 2 annotations
to   cover one observation.
 
DNA clamp unloader activity
and 
ATPase activity

It seems a bit wrong?

So why did you decide it couldn't be 'is_a' again?

**Comment by ukemi** [comment]
Because it is doing something more than just cleaving ATP isn't it? So it is really a compound function. But then aren't all ATPases?  I think that the right way to do this is to propagate annotations over has_part for molecular functions. We talked about doing that a while ago, but it seemed to fall by the wayside and if I remember correctly, there were examples where it didn't always hold true. Maybe we should bring it up again on at the GOC meeting. We would need to test how it would work with complexes. That could get tricky.

**Comment by ValWood** [comment]
OK, I now realise that I'm  confused about how we represent ATPase coupled activities more generally.

Do not confuse the following:

In the molecular function guidelines it is clearly stated:

Two things that happen at the same time or that are done by the same molecule.
Two things that are dependent on each other and cannot occur independently.
For example, the proposed term actin binding with sliding actually includes the two functions binding and motor activity, so it is not appropriate as a function term. However, calcium-transporting ATPase activity represents two activities that are dependent on each other and cannot occur independently; thus calcium-transporting ATPase activity is appropriate as a GO molecular function.

Historically, we always represented ATPase couples activities as a single term. I think this is *Much* easier for curators to deal with, and represents how biologists think of these molecular functions. They aren't separable.

Most ATPases continue to be represented in this way:

helicases are all under NTPase
http://www.ebi.ac.uk/QuickGO/term/GO:0004003

microtubule motors are all under  NTPase
http://www.ebi.ac.uk/QuickGO/term/GO:0003777

protein-DNA loading ATPases
http://www.ebi.ac.uk/QuickGO/term/GO:0033170

microtubule-severing ATPase activity
http://www.ebi.ac.uk/QuickGO/term/GO:0008568

It would be much less complicated to continue as we are. Or to get rid of the specific "types " of ATPase and annotate as


ATPase activity involved_in microtubule severing
ATPase activity involved in DNA unwinding

but I don't see the advantage in decomposing the compound ATPase activities, into the ATPase and the  activity that the ATPase provides the energy for. it seems a lot of work and a lot of reannotation. Is there one?

There terms are *defined* as  types of ATPase too, which makes it even weirder...
Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the opening of the ring structure of the PCNA complex.

**Comment by ukemi** [comment]
I'm going to reassign this because it looks like it will fall under the MF refactoring.

**Comment by pgaudet** [comment]
We came across a similar issue with the ATP-dependent transporters with @thomaspd 
I'll add this to the ontology editors discussion.

**Comment by ValWood** [comment]
relation used in
https://github.com/geneontology/go-ontology/issues/14012#issuecomment-330501399
will resolve the inheritance issue.

**Comment by pgaudet** [comment]
Discussion at editor's call: 
all ATPases should be moved under ATPase-coupled, except for the uncoupled ATPase (GO:0042624)

**Comment by ukemi** [comment]
Note that the move above makes things consistent, but still doesn't solve that main issue with this type of compound function. It will still be the case that anything that regulates one of these activities will still regulate 'ATPase activity'. @vanaukenk gave us an example of this on the call and it is referenced in the link above.

**Comment by pgaudet** [comment]
Hello, 

For the inferences: isn't is the case that we have: 
* for MF:
- ATP-dependent helicase activity
-- is_a helicase activity
-- is_a ATPase activity

* for Regulation (BP): 
- negative regulation of ATP-dependent helicase activity
-- is_ a regulation of 

* For BP o MF: 
- regulation of ATP-dependent helicase activity
-- is_NOT_ a regulation of helicase activity
-- is_NOT_ a ATPase activity
But instead, it's simply a regulation of enzymatic activity. 

Is this correct ? 

Thanks, Pascale
