### ISSUE TITLE
Signaling project Change of term: JAK/STAT pathway

### ISSUE THREAD

**Issue by gantonazzo** [geneontology/go-ontology#14167]
Hi

from JAK/STAT pathway - Signaling Project #1628

The current term for JAK/STAT is GO:0007259 JAK-STAT cascade. However, considering the few steps involved in the pathway, and the way most papers refer to it, it would be more appropriated to change this term to 

>JAK/STAT pathway 

This change should be reflected in all the relative child terms and definitions.

@RLovering

**Comment by RLovering** [comment]
GO:0097696 receptor signaling pathway via STAT needs to be renamed as

If the Jak/STAT is an internal pathway can we move it to:

GO:0007166 cell surface receptor signaling pathway
>part of GO:0097696 receptor signaling pathway via STAT

GO:0035556 intracellular signal transduction
>is a GO:0097696 receptor signaling pathway via STAT

**Comment by hattrill** [comment]
@RLovering @gantonazzo  
I think that we changed the term name to receptor signaling pathway via JAK-STAT so that we could include the ligands/receptors in the pathway, rather than just the JAK/STAT intracellular bit.

**Comment by RLovering** [comment]
But why are we including the ligands and receptors?

**Comment by hattrill** [comment]
So, we changed the name of this because in some cases  like Dmel, we only have one pathway "domeless" that acts via JAK/STAT, but as other species e.g. humans have many of receptors that and we wanted a term that encompassed the pathway as a whole. 
Perhaps, having the term 'JAK-STAT intracelluar signaling cascette' would capture that particular aspect and we could keep 'receptor signaling pathway via STAT'; alternatively, we would need 'Domeless signaling' to provide a term that captures the ligand-TF/effector pathway in the pattern similar to other pathways.

**Comment by pgaudet** [comment]
Yeah this seems a bit odd to me too - so say TGF would be annotated to both 'TGF signaling' and 'JAK/STAT signaling'? 

It seems we want either: TGF signaling is upstram of JAK/STAT signaling', or create the full pathway 'JAK/STAT-activating  TGF signaling', a bit like we have for the GPCRs; what do you think?

**Comment by hattrill** [comment]
Looking at the emails from the orignal discussion, I think the fact that it was just a two-components with no downstream part was the deciding factor was the reason for making it a pathway and removing it from IC signaling, as it would be just 4 components for the pathway as it was: ligand-receptor-Jak-Stat

In favour of the a "whole pathway" term plus casette would be how we handle RTK pathways. @gantonazzo should be back at the end of the week, as she was involved in the orignal working group, best wait for her.

**Comment by RLovering** [comment]
Based on the agreement for SMAD intracellular signaling ideally TGF would be annotated to 
'TGF signaling' AND
positive regulation of 'JAK/STAT signaling' AE part of 'TGF signaling' 

And JAK and STATs in the TGF pathway will be annotated to:
'TGF signaling' 
'JAK/STAT signaling' AE part of 'TGF signaling' 

Why not create a GO term unpaired signaling. Then you can have 
GO:0007166 cell surface receptor signaling pathway
> unpaired signaling pathway
Then unpaired (1,2,and 3) and dome would be annotated with 
'unpaired signaling pathway' AND
positive regulation of 'JAK/STAT signaling' AE part of 'unpaired signaling pathway' 

And JAK and STAT equivalents would be annotated with
'unpaired signaling pathway' 
'JAK/STAT signaling' AE part of 'unpaired signaling pathway'

Then if we create the new relationships:
GO:0035556 intracellular signal transduction
> is a GO:0097696 renamed JAK-STAT intracellular signal transduction

This would also mean that JAK and STAT equivalents would be associated with 'intracellular signal transduction' term which would be better for these proteins in non-insect species and would not be wrong for Dros JAK and STAT.

Plus currently unpaired and dome are not associated with positive regulation of intracellular signal transduction, but if we do create this consistent annotation approach then hopefully all other ligands and receptors will be associated with a positive/negative regulation of intracellular signal transduction term as well as to the term that describes the ligand/receptor pathway.

Thus if we do not create the JAK/STAT intracellular signal transduction term, we will have to create different guidelines for unpaired and dome than for the other receptors and ligands

**Comment by hattrill** [comment]
Hi @RLovering - we would definitely need a direct replacement for this pathway, as it makes no sense to just label this distinct pathway with just  "unpaired receptor  signaling" - probably could go under 'cytokine-mediated signaling pathway'. However, we've have push back on terms that are said to be too specific in the past and we need a specific term for our pathway pages.

We probably need to discuss where regulation begins and ends in pathways - that's not an issue with what you propose - I am fine with the 'closeness' of the R-L to the IC pathway - but should this be where we draw the line - for example, things involved in cytokine secretion shouldn't be +ve reg of jak-stat.

**Comment by gantonazzo** [comment]
Hi all,

As Helen said, we decided to change the original term since in certain organisms, like Dmel, the pathway doesn't have any downstream section. It just requires 4 components: ligand-receptor-Jak-Stat, so it made sense to include the ligand and the receptors in the pathway itself.

I don't think I am comfortable with the idea of having an "unpaired signaling pathway" term instead of what we currently have. In my opinion, either we go through a "Domeless signalling pathway" term route (but that would probably be too specific), or we keep the current term and add a cassette term to be used in those cases where you want to refer just to the intracellular signalling (which would be my preferred solution).

It all goes back to defining pathway boundaries, which is always tricky!

**Comment by pgaudet** [comment]
Discussion with @hattrill 
In fact JAK is linked to the receptor, as far as we can tell: (image from wikipedia): https://en.wikipedia.org/wiki/JAK-STAT_signaling_pathway

<img width="316" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/209f035f-0c1c-4d14-8990-3216ee82dab6">

so, it seems weird to de-couple the JAK/STAT from the receptor itself. 
So, 'cell surface receptor signaling via JAK/STAT' seems most appropriate

**Comment by pgaudet** [comment]
Fixed label and definition: 
GO:0007259
-old name: receptor signaling pathway via JAK-STAT
+new name: cell surface receptor signaling pathway via JAK-STAT

-old def: "Any process in which STAT proteins (Signal Transducers and Activators of Transcription) a
nd JAK (Janus Activated Kinase) proteins convey a signal to trigger a change in the activity or 
state of a cell. The receptor signaling pathway via JAK-STAT begins with activation of a recepto
r and proceeeds through STAT protein activation by members of the JAK family of tyrosine kinases
. STAT proteins dimerize and subsequently translocate to the nucleus. The pathway ends with regu
lation of target gene expression by STAT proteins." [GOC:bf, GOC:jl, GOC:signaling, PMID:1203902
8]
+new def: "A cell surface receptor signaling pathway in which ligand binding causes the receptor to 
dimerize, bringing the receptor-associated JAKs into close proximity. The JAKs then phosphorylat
e and activate each other on tyrosine residues.This leads to the activation of associated STAT p
rotein, causing the STATs to dissociate from the receptor, translocate to the nucleus. The pathw
ay ends with regulation of target gene expression by STAT proteins.
