### ISSUE TITLE
Signaling project NTR: tyrosine dephosphorylation of STAT protein

### ISSUE THREAD

**Issue by gantonazzo** [geneontology/go-ontology#14166]
Hi

from JAK/STAT pathway - Signaling Project #1628 

Please could the following new term be created:

GO:0035335 peptidyl-tyrosine dephosphorylation

> is_a NTR tyrosine dephosphorylation of STAT protein
Suggested definition: The process of removing a phosphate group from a tyrosine residue of a STAT (Signal Transducer and Activator of Transcription) protein.

If created, please add the following DbxRefs to the term:

DbxRef: GOC:ga
DbxRef: GOC:BHF
DbxRef: GOC:rl

PMID:28637459

Thanks,
Giulia

@RLovering

**Comment by ukemi** [comment]
Perhaps better represented as 'STAT protein tyrosine phosphatase activity'?

**Comment by pgaudet** [comment]
@gantonazzo @RLovering 
Can you use the generic term 'GO:0004725  protein tyrosine phosphatase activity' with the specific protein in the 'has input' field ?

**Comment by gantonazzo** [comment]
Hi @pgaudet ,
That would be fine for me.
