### ISSUE TITLE
NTR: response to c-di-GMP

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#14175]
Hello:

I would like to submit a NTR for two new GO terms:

response to c-di-GMP
cellular response to c-di-GMP

Here is my suggestion for response to c-di-GMP and please also create the companion cellular response term as well. 

Please let me know of any questions.
Thanks,
Bob Dodson

Name: response to c-di-GMP
Ontology: biological_process
Synonyms: response to cyclic diguanylate; response to 3',5'-cyclic di-GMP;  response to cyclic di-(3':5')-guanosine monophosphate
CHEBI ID: CHEBI:49537
Alternate IDs: None
Child of: GO:0014074	response to purine-containing compound	
Definition: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a c-di-GMP stimulus

References: 
PMID: 23471616	Cyclic di-GMP: the first 25 years of a universal bacterial second messenger.

PMID: 22864416	The prokaryote messenger c-di-GMP triggers stalk cell differentiation in Dictyostelium.

**Comment by rjdodson** [comment]
Please add an additional synonym to the previous:

response to cyclic di-GMP

**Comment by ukemi** [comment]
Hi Rob,

Rather than having the response terms, would it make more sense to just create the signaling terms that you requested in #14180? I'm thinking that if we know the mechanism of the signaling pathway, then may it would be best just to create those terms. Response in general is kind of vague.

**Comment by rjdodson** [comment]
Hi David:

In principle I'm OK with your suggestion. But researchers have identified several genes whose expression is upregulated as a result of c-di-GMP signaling. And I thought this, that is the "response to c-di-GMP"  GO term would be more appropriate for such genes. 

But maybe I'm wrong? I don't typically think of them as part of the signaling pathway, but would "c-di-GMP-mediated signaling" also be an appropriate GO term to use for them? Or, is there a better way to curate such genes? 

Thanks,
Bob

**Comment by ukemi** [comment]
Hi Bob,

This is an age-old question and is the reason why I think the response terms are rather vague. Does upregulation mean that a gene products function is to respond to a stimulus, or could it be a downstream effect? In the GO-CAM world, we might be able to model this better than to annotate upregulated genes to 'response to x'. I'm going to ping @vanaukenk and @pgaudet on this to get their thoughts.

-D

**Comment by rjdodson** [comment]
Hi David:

Thanks for your response. As I'm interpreting it, the up (and also down) regulation here is a downstream effect. That is, the genes I'm referring to are not specifically responding to the c-di-GMP stimulus, but rather they are being up, or down regulated by a protein kinase which is itself a downstream mediator in the signal transduction pathway. The protein kinase is at least two genes downstream of the gene in dicty (dgcA) which synthesizes c-di-GMP. So again, I think this is a downstream effect.

In case you want to verify, I'm referring here to PMID:28057864, and the genes such as staC, abcG18, staC, etc. shown in Fig. 1 as genes I was planning to curate with "response to c-di-GMP".
I was planning to curate the genes: dgcA, ACA, and PKA, shown in Fig. 7 with "c-di-GMP-mediated signaling" as I interpret these as being the genes actively involved in signaling. Fig. 7 also includes "stalk genes" and these are the genes mentioned in the previous paragraph (staC, etc.) which I interpret as being a downstream effect of the signaling process. 

This last bit may be TMI, but just wanted to include as background in case you wanted to see how I was thinking about this. Please critique if warranted. 

Thanks,
Bob

**Comment by ukemi** [comment]
Hi Bob,

Bear with me. I'm going to try a GO-CAM model for this. My first inclination is to make the signaling regulate the MFs that are carried out by abcG18, staC etc. So those gene products aren't functioning in the response itself. But let's see what I come up with.

-D

**Comment by rjdodson** [comment]
Hi David:

OK, sounds good with me. Please let me know if you have any questions or if I can be of help in any way. I don't know exactly what a GO-CAM model is-is it similar to a LEGO model? I was thinking I might try and build a LEGO model for this after getting the GO terms, but if that's similar to what you're doing, then by all means go for it. I'll be interested to see the resulting model.  

Thanks,
Bob

**Comment by ukemi** [comment]
Hi Rob,

Same thing, updated name. Have a look at this model and let me know if it makes sense to you:
http://noctua.berkeleybop.org/editor/graph/gomodel:59b38c1100000331
I don't think we need the response term. The new signaling term, c-di-GMP signaling, would replace the 'cell surface receptor signaling pathway involved in cell-cell signaling'  in the lower left corner. Maybe it would be a child of it, but I don't think a receptor has been shown. Can we assume? This would be a great model to discuss.

I'd love to get input from @pgaudet too.

**Comment by rjdodson** [comment]
Hi David: See my response on the other ticket.

**Comment by ukemi** [comment]
Hi Bob,

Is it ok if we close this one and keep all the discussion in one place on the other one?
-D

**Comment by pgaudet** [comment]
Hi @ukemi @rjdodson 

One question to make sure I am following: there is a  single Noctua model for both issues, right ? 

In any case, I do agree that the response to is not really useful in this case, and any annotations to it would be redundant (also since 'response to x' is a parent of 'x signaling') and probably in many cases. But I am concerned that we are being inconsistent; are we planning to deal with 'response to' terms more generally? 

Thanks, Pascale

**Comment by rjdodson** [comment]
Hi David, Pascale:

David, yes, I am OK with closing this thread and having all further discussion occur on the other issue: https://github.com/geneontology/go-ontology/issues/14180#issuecomment-329258698

Pascale, at the moment there is only one Noctua model from David: 

http://noctua.berkeleybop.org/editor/graph/gomodel:59b38c1100000331

However he and I have agreed that I should create a new, more basic model for this process-partly to simplify his model and also to give me a bit of Noctua practice, so mine will be more of a training version.  I haven't started yet, but once I do I'll provide a link to it on the NTR: c-di-GMP-mediated signaling and related others #14180

Bob
