### ISSUE TITLE
docs: replace obsoleting and merging sections with plugin guide

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14185]
@matthewhorridge is porting @balhoff's obsoletion plugin into core Protege and also adding merge functionality. When this is done we can replace the instructions in RTD on how to do this manually with instructions on how to do it via the plugin.

github repo here:
https://github.com/owlcollab/protege-obo-plugin/

releases:
https://github.com/owlcollab/protege-obo-plugin/releases

**Comment by tberardini** [comment]
That's really great news!  Thanks, @matthewhorridge!

**Comment by matthewhorridge** [comment]
You're welcome! I should have a snapshot build for you all to have a look at some time next week.

**Comment by pgaudet** [comment]
@ukemi are you using those plugins ? If you do perhaps you can update the documentation? 

Thanks, Pascale

**Comment by ukemi** [comment]
I have used @balhoff 's obsoletion plugin without any problems. I have not tested the merge plugin.

**Comment by matthewhorridge** [comment]
Just a heads up.  We've just released Protege 5.5.0-beta-4.  It's got the obsoletion workflow support in it (as did beta-2 and beta-3).  I'd be happy to have any feedback on this (and other relevant wrinkles actually).

**Comment by pgaudet** [comment]
@matthewhorridge

Will there be a new Protege version with the merge plugin? The last I heard about this it was still in beta. 

Thanks, Pascale
