### ISSUE TITLE
NTR:  GO:0004571 mannosyl-oligosaccharide 1,2-alpha-mannosidase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14189]
Can we please have the complex to go with 
GO:0004571 mannosyl-oligosaccharide 1,2-alpha-mannosidase activity?

Def: A protein complex capable of catalysing the hydrolysis of the terminal (1->2)-linked alpha-D-mannose residues in an oligo-mannose oligosaccharide.

Comment: An example is MNL1 (P38888) in Saccharomyces cerevisiae. PMID:19124653 (by physical interaction evidence). [I can't remember the correct syntax of the comment.]

Relationships:
is_a GO:0043234 protein complex
part_of GO:0005788 endoplasmic reticulum lumen
capable_of GO:0004571 mannosyl-oligosaccharide 1,2-alpha-mannosidase activity
capable_of GO:0043394 proteoglycan binding
capable_of_part_of GO:1900103 positive regulation of endoplasmic reticulum unfolded protein response
capable_of_part_of GO:1904380 endoplasmic reticulum mannose trimming
capable_of_part_of GO:1904382 mannose trimming involved in glycoprotein ERAD pathway

xrefs:
GOC:bhm
PMID:21700223
IntAct:EBI-16411902

Thanks, Birgit

**Comment by hdrabkin** [comment]
done

**Comment by bmeldal** [comment]
thanks, Harold. Can you please paste the ID here as I won't be able to see it until it trickles through the releases. Or link the merge ticket.

**Comment by hdrabkin** [comment]
GO:0106055 Mannoysl-oligosaccharide 1,2-aplha-mannosidase complex
