### ISSUE TITLE
NTR - GOBP term for Interleukin-10 signaling

### ISSUE THREAD

**Issue by scjupe** [geneontology/go-ontology#14186]
Could you please create a term Interleukin-10-mediated signaling pathway, as child of GO:0019221 cytokine-mediated signaling pathway.  IL10 has a well-established receptor and associated signaling mechanism, see PMID:11244051

**Comment by pgaudet** [comment]
Hi @scjupe 

Here's the new term: 

+id: GO:0140105
+name: interleukin-10-mediated signaling pathway
+namespace: biological_process
+def: "A series of molecular signals initiated by the binding of interleukin-10 to a receptor on the surface of a cell, and ending with regulation of a downstream cellular process, e.g. transcription." [PMID:11244051]
+synonym: "IL-10-mediated signaling pathway" EXACT []
+synonym: "interleukin-10-mediated signalling pathway" EXACT []
+is_a: GO:0019221 ! cytokine-mediated signaling pathway
+created_by: pg
+creation_date: 2017-09-22T16:04:42Z

Thanks, Pascale
