### ISSUE TITLE
phosphatidylinositol phosphate biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14184]
I would like   to annotate pombe stt4 to  a term 
phosphatidylinositol phosphate biosynthesis

https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=PATHWAY&object=PWY3O-242&detail-level=2
(with ISS to the yeast protein)

Stt4 phosphorylates PM PI to produce PI-4-phosphate (PI4P), which can be further modified to PI(4,5)P2. Therefore, disruption of PI4 kinases results in a reduction of both PI4P and PI(4,5)P2 (Audhya and Emr, 2002; Baird et al., 2008; Nakatsu et al., 2012). The PI(4,5)P2 sensor GFP-2×PH(PLCδ) (Stefan et al., 2002) was reduced at the cell cortex and the division site in efr3Δ compared with WT (Fig. 1 D),

The paper I am annotating is about  anchoring of the cytokinetic ring to the plasma membane and this depends on plasma membrane  phosphatidylinositol phosphate.

The current term in GO is

phosphatidylinositol phosphorylation
GO:0046854

Description
The process of introducing one or more phosphate groups into a phosphatidylinositol, any glycerophosphoinositol having one phosphatidyl group esterified to one of the hydroxy groups of inositol.
Synonyms
phosphatidylinositol phosphate biosynthetic process, phosphatidylinositol phosphate phosphorylation, phosphoinositide phosphorylation, 
NARROW PIP biosynthesis, 
NARROW PtdInsP biosynthesis

Isn't  PtdInsP biosynthesis
 broader? 
Can we have a term for  phosphatidylinositol phosphate biosynthesis

phosphatidylinositol phosphorylation seems to describe a single step?

**Comment by hdrabkin** [comment]
Hi Val
What else besides the phosphorylation would be included under the proposed biosynthesis term?
The term phosphatidylinositol phosphorylation def appears to include addition of one, two, or more already.

**Comment by ValWood** [comment]
hmm

https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=PATHWAY&object=PWY3O-242&detail-level=2

so its only the various kinases? You don't really need to know that its "phosphorylation"the kinase term tells you that.  The important part is that PIPs are made.

Maybe we could make
phosphatidylinositol phosphate biosynthesis
the primary term name?

(I wonder why it is narrow?)

**Comment by hdrabkin** [comment]
Or maybe just change to related synonym?

**Comment by deustp01** [comment]
Can this be handled at the level of logical definitions, that the process involved kinases and generates various PIPs as output, analogous to the use of these in the various kinds of glycolysis? @ukemi ?

**Comment by hdrabkin** [comment]
The logical def would need to be unique. But there several that may or may not be involved at any one time?

**Comment by ValWood** [comment]
So, the reason I want to change this is that it isn't a very informative term name.

If I am annotating
http://preview.pombase.org/gene/SPBC577.06c

1-phosphatidylinositol 4-kinase activity

phosphatidylinositol phosphorylation is just a process-y way of describing the function.

"phosphatidylinositol phosphate biosynthesis" better describes the process.

Such a term could have a parent to "lipid biosynthesis" or even "membrane lipid biosynthesis?" if this is always true? I have no clue though.... I only know of  it in this context?

**Comment by hdrabkin** [comment]
I think I have lost the point here. 
But if you want "Can we have a term for phosphatidylinositol phosphate biosynthesis"
I need.
1. def
2. PMID.
3. suggested parentage.
I assume you would include not only the phosphorylation of the phosphatidylinositol, but also synthesis of the phosphatidylinositol itself?

**Comment by hdrabkin** [comment]
@ValWood  can you comment?

**Comment by ValWood** [comment]
whoops forgot to answer.
PMID: 28784611

As a precedent we have

GO:0036092    phosphatidylinositol-3-phosphate biosynthetic process
GO:1904563    phosphatidylinositol 5-phosphate biosynthetic process


should be descendants of the proposed term?

**Comment by ValWood** [comment]
@hdrabkin  did my final comment make sense?

**Comment by pgaudet** [comment]
Changed label and definition of 
GO:0046854 phosphatidylinositol phosphorylation
to phosphatidylinositol phosphate biosynthetic process 

Thanks, Pascale
