### ISSUE TITLE
GO:0007302 nurse cell nucleus anchoring is not 'adhesion' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14188]
'nurse cell nucleus anchoring' should be moved under 'nucleus localization'. 
Definition: 'Attachment of the nurse cell nucleus to the plasma membrane.' The current parents are not consistent with this.

**Comment by pgaudet** [comment]
Hi @hattrill 

Do you have any objection to the removal of the 'biological adhesion' parent here: 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/4782928/30468953-6e5306bc-99ee-11e7-926e-600e15eb6dd7.png">



Thanks, Pascale

**Comment by hattrill** [comment]
That's fine with me.
