### ISSUE TITLE
Fix term label, definition and cross references for 'cytochrome P450 fatty acid omega-hydroxylase activity' with 'acyl-[acp] hydrolase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14194]
'cytochrome P450 fatty acid omega-hydroxylase activity' has no annotations. 
In addition it has as db cross reference EC:3.1.2.-, which is the EC of the parent thiolester hydrolase activity. 
Also, there is nothing EC or the metcyc reaction that refers to cytochrome P450. 
'acyl-[acp] hydrolase activity' has exact synonym 'acyl-CoA thiolesterase activity', so it seems like these two are equivalent. 

@tberardini do you want to comment ? 

Thanks, 
Pascale

**Comment by pgaudet** [comment]
Digging a little further, I found in UniProt entry Q02928 (from PMID:18433732) that cytochrome P450 gene 4 family catalyzes omega- and (omega-1)-hydroxylation of various fatty acids such as laurate, myristate and palmitate. 

I also found 
https://en.wikipedia.org/wiki/Linoleoyl-CoA_desaturase 
that catalyzes 'linoleoyl-CoA + AH2 + O2 <=> gamma-linolenoyl-CoA + A + 2 H2O' 
and has EC 1.14.19.3. 

However in GO EC 1.14.19.3 is linoleoyl-CoA desaturase activity: 
Catalysis of the reaction: linoleoyl-CoA + reduced acceptor + O2 = gamma-linolenoyl-CoA + acceptor + 2 H2O.

@hdrabkin do you know anything about these enzymes? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
No, not really.. One is specifying "reduced acceptor", which I believe is what "AH2" is used as an abbreviation for.

**Comment by deustp01** [comment]
Hmmm. A hydrolase catalyzes the cleavage of a covalent bond with the introduction of the elements of a water molecule. Proteases are hydrolases. A hydroxylase introduces an -OH group into a substrate. Many textbook cytochrome P450 enzymes are hydroxlases. I don't know of any that are  hydrolases, so a priori the proposed merger sounds wrong.

**Comment by tberardini** [comment]
Nothing to add, @pgaudet.  This is not my area of expertise.  However, I see quite a few papers describing this activity:

http://www.jbc.org/content/267/27/19051.short
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2423664/

It looks like the parentage and EC reference need updating but how and to what, we'd need some input from people with more biochemical background than I have.  I would not recommend merging or obsoletion of this term given the current information I've seen.

**Comment by pgaudet** [comment]
Thanks for the feedback, I'll look further. 

Pascale

**Comment by pgaudet** [comment]
Hi Ingrid, 

How are you doing ? I need some help to understand a MetaCyc reaction that we have as a cross-link to GO:0102033 cytochrome P450 fatty acid omega-hydroxylase activity
https://github.com/geneontology/go-ontology/issues/14194

The link we have, MetaCyc:LINOLEOYL-RXN, take me to 
https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=1.14.19.3-RXN

which has a different EC from what GO has. Can you help me understand what I am looking at? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi Pascale,

First, for me the link on the GO site, http://amigo.geneontology.org/amigo/term/GO:0102033
actually goes to
https://biocyc.org/META/NEW-IMAGE?type=NIL&object=LINOLEOYL-RXN
and not to the 1.14.19.3 reaction.

The big disconnect seems to be between the name of the term, cytochrome P450 fatty acid omega-hydroxylase activity, and the definition/activity, which is a CoA hydrolase, very different from what is suggested by the name.  The current location of GO:0102033 in the hierarchy fits with the definition, but not the term name. So if you decide to keep it, at least the term name needs to be fixed.

As for the term/enzyme/reaction itself, I don't know what, if anything, the evidence for it is.  The reaction in MetaCyc doesn't have an enzyme catalyzing it, and from my reading of the pathway summary at https://biocyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-6917, it may have been included because the pathway needed an input of linoleate without a CoA group.  At one point in prehistory, there seems to have been an enzyme catalyzing the reaction in a different pathway, but both seem to have disappeared.

So, if you decide to keep the term, I'd fix the name and actually move it under GO:0016289, the CoA hydrolases.  In the GIT ticket, you wrote that 'acyl-[acp] hydrolase activity' has exact synonym 'acyl-CoA thiolesterase activity', but I actually don't see that synonym for GO:0016297.  Which is good, because ACP is definitely not the same as CoA.  (Are we looking at different versions of GO? I'm using AmiGO at the geneontology web site.)

As for EC 1.14.19.3, there is actually already GO:0016213.

Does this help?  I can ask Ron Caspi more about the history of the LINOLEOYL-RXN if needed.

Cheers,
Ingrid

**Comment by pgaudet** [comment]
Thanks for the input @keseler 
In the end I kept the concept of the term name, and changed the definition and cross references (including MetaCyc and EC). If we ever need the reaction represented by MetaCyc:LINOLEOYL-RXN someone can request it. 

Changes: 
 id: GO:0102033
-name: cytochrome P450 fatty acid omega-hydroxylase activity
+name: fatty acid omega-hydroxylase activity
 namespace: molecular_function
-def: "Catalysis of the reaction: linoleoyl-CoA(4-) + H2O <=> H+ + linoleate + coenzyme A" [EC:3.1.2.-, MetaCyc:LINOLEOYL-RXN]
-xref: MetaCyc:LINOLEOYL-RXN
-is_a: GO:0016790 ! thiolester hydrolase activity
+def: "Catalysis of the reaction: long-chain fatty acid + NADPH + H+ + O2 = an omega-hydroxy-long-chain fatty acid + NADP+ + H2O." [EC:1.14.13.205]
+synonym: "cytochrome P450 fatty acid omega-hydroxylase activity" RELATED []
+xref: MetaCyc:RXN-16394
+xref: PMID:18544608


Thanks, Pascale
