### ISSUE TITLE
Merge 'phosphohistidine phosphatase activity' with 'protein histidine phosphatase activity'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14193]
'phosphohistidine phosphatase activity' should be to 'protein histidine phosphatase activity' 

@thomaspd and I find no evidence that free histidine is phosphorylated. 

https://www.ncbi.nlm.nih.gov/pubmed/?term=%22phosphohistidine+phosphatase%22

Pascale

**Comment by ValWood** [comment]
agreed.

**Comment by pgaudet** [comment]
Right I noticed that's consistent with the discussion in #12183
but the decision was implemented a little differently than described. 

- Pascale
