### ISSUE TITLE
add taxon restrictions  L-dopa & orcinol  O-methyltransferase activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14192]
To 
Scizosaccharomyces

and
Saccharomyces (I think) @srengel ?

We are picking up a couple of mappings .

thanks

Val

**Comment by ValWood** [comment]
I don't think L-dopa is part of normal biology of any fungi, as far as I can tell?

**Comment by ValWood** [comment]
no we don't have this 
http://amigo.geneontology.org/amigo/term/GO:0004510

and orcinol appears to be associated with lichens

**Comment by srengel** [comment]
Agreed.  It's not a normal part of fungal biology.  We don't have any annotations to any l-dopa terms.  The few papers about it in yeast discuss it as an externally-applied experimental insult, or using yeast as a factory to produce it: https://www.yeastgenome.org/search?q=L-dopa&category=reference

Totally fine with me to taxon-restrict these terms for fungi.

**Comment by ValWood** [comment]
Oh yes I see only pombe has the mappings for a gene product conserved in human but absent from S. c.

http://preview.pombase.org/gene/SPBC119.03
http://preview.pombase.org/gene/SPBPB21E7.04c

So good to restrict, thanks

**Comment by ukemi** [comment]
L-dopa O-methyltransferase and orcinol O-methyltransferase activities already have never_in Ascomycota restrictions. That should suffice shouldn't it?

**Comment by ValWood** [comment]
Weird, I wonder why we are getting terms mapped via EC to GO, they should be blocked?

**Comment by ukemi** [comment]
@cmungall could this be a problem with the taxon import? I don't see the full tree under Ascomycota when I load the editors' GO into Protege.

**Comment by ukemi** [comment]
@cmungall and @ValWood , I don't think there is anything more to do here with respect to ontology development. Is this pipeline working now? It seems the restrictions are in place in the ontology.

**Comment by ukemi** [comment]
Looking in the ontology, I see pombe is imported, so I am closing this one.

**Comment by dianeoinglis** [comment]
Actually, some Ascomyvota have enzymes that convert L-dopa into melanin. Cryptococcus, a Basidiomycetes, does this quite well. This taxon restriction would be best used for Sac and S. Pombe.
Diane
