### ISSUE TITLE
question about term name change for GO:0006515

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#14199]
We noticed that the term name for GO:0006515 was changed from "misfolded or imcompletely synthesized protein catabolism" to "protein quality control by the ubiquitin-proteasome system".  This seems to be a substantial eukaryotization of the term name (there is no ubiquitin-proteasome system in bacteria), even though it is still in the gosubset_prok.  What was the reasoning for the name change, and how should prokaryotic proteins now be annotated?  Do we need to move our annotations to the parent term?

Thanks,
Ingrid

**Comment by pgaudet** [comment]
Hi @keseler 

Thanks for bringing that up ! Looks like I updated the incorrect term from #14059

**Comment by pgaudet** [comment]
Hi @keseler @ValWood 
Would it be OK to rename (again) 'protein quality control by the ubiquitin-proteasome system' to 
'protein quality control system for misfolded or imcompletely synthesized proteins' ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Whoops.
I'll check back to the ticket. I'm not sure it was intended anyway.

**Comment by pgaudet** [comment]
@ValWood 
I probably went a little too far: 

I renamed: 
GO:0006515
-name: misfolded or incompletely synthesized protein catabolic process
+name: protein quality control by the ubiquitin-proteasome system

 id: GO:0071629
-name: ubiquitin-dependent catabolism of misfolded proteins by cytoplasm-associated proteasome
+name: cytoplasm protein quality control by the ubiquitin-proteasome system

 id: GO:0071630
-name: ubiquitin-dependent catabolism of misfolded proteins by nucleus-associated proteasome
+name: nuclear protein quality control by the ubiquitin-proteasome system

The first was too much (GO:0006515). My latest changes here revert that. 

Thanks, Pascale

**Comment by keseler** [comment]
Thanks, Pascale!  Glad to know it was only a mistake; "protein quality control for misfolded or incompletely synthesized proteins" sounds fine to me.

-Ingrid

**Comment by ValWood** [comment]
Great!
