### ISSUE TITLE
Molecular Refactoring: catalytic activity branch

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14208]
@thomaspd  and I have added 3 new grouping classes: 
- catalytic activity, acting on a protein
- catalytic activity, acting on DNA
- catalytic activity, acting on RNA

And we have added the appropriate children to these 3 classes.

**Comment by ValWood** [comment]
I just noticed 
61b567b fixed Atg8 parents for #14208
...I  think you are adding "ubiquitin-like protein ligase parentage" to some of the ubiquitin modifiers, but these are not necessarily   protein modifiers.

Catalysis of the covalent attachment of the ubiquitin-like protein Atg8 to substrate molecules; phosphatidylethanolamine is a known substrate. PMID:12826404

David @ukemi  just spent *ages* fixing all these ;)


Also make sure you don't add the "ligase activity" parent back to any of these, they are transferases, despite being called ligases.

Could you provide a bit more information  about the changes in the tracker ticket in case we miss something?


v

**Comment by ValWood** [comment]
some background
https://github.com/geneontology/go-ontology/issues/11723
https://github.com/geneontology/go-ontology/issues/10821
https://github.com/geneontology/go-ontology/issues/11209

and about a bzillion other related tickets.

(we probably don't want to go through this again, its one part that *is* correct!, many contributors agreed)
Val

**Comment by pgaudet** [comment]
thanks for pointing it out ! I was unsure, I asked David and I undid it. 

Pascale

**Comment by ValWood** [comment]
;)) It took *ages* to sort those out. Then I reannotated  108 pombe ubiquitin-like ligases  as a consequence of the changes, so I'm hoping everything is correct as we currently have  it.

**Comment by pgaudet** [comment]
Hi @ValWood 
-'Atg8 ligase activity' is still directly under under transferase activity, so that seems OK
- 'Atg8 activating enzyme activity' is also still under the same parent, 'small protein activating enzyme activity', which @thomaspd and I renamed 'ubiquitin-like modifier activating enzyme activity'. 

If you think that new name is misleading I can change it back. I must say at first when I saw 'small protein activating enzyme activity' I thought it was describing a ras GAP. 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/14214

**Comment by ValWood** [comment]
@ukemi  shouldn't this term be named
small-conjugating protein activating enzyme activity
rather than "small protein activating" 

?

**Comment by ValWood** [comment]
Oh I see you called 'ubiquitin-like modifier activating enzyme activity'
either works but I think we should be consistent.

I think I marginally prefer 
small-conjugating protein because it stops people being focussed on ubiquitin only.
but whatever everyone thinks is best...

**Comment by pgaudet** [comment]
I am closing this. @ValWood (and everyone !) please open a separate issue if there is something wrong with the Atg8 terms (or any other class). 

Thanks, Pascale

**Comment by pgaudet** [comment]
@thomaspd @ukemi 
Any preference: 
**small-conjugating protein activating enzyme activity**
or 
**ubiquitin-like modifier activating enzyme activity**


Thanks, Pascale

**Comment by pgaudet** [comment]
Add logical definitions: 

GO:0140096
 name: catalytic activity, acting on a protein
+intersection_of: GO:0003824 ! catalytic activity
+intersection_of: has_input PR:000000001 ! protein


GO:0140103
 name: catalytic activity, acting on a glycoprotein
+intersection_of: GO:0003824 ! catalytic activity
+intersection_of: has_input CHEBI:17089 ! glycoprotein

GO:0140097
 name: catalytic activity, acting on DNA
+intersection_of: GO:0003824 ! catalytic activity
+intersection_of: has_input CHEBI:16991 ! deoxyribonucleic acid


GO:0140098
 name: catalytic activity, acting on RNA
+intersection_of: GO:0003824 ! catalytic activity
+intersection_of: has_input CHEBI:33697 ! ribonucleic acid

GO:0140102
 name: catalytic activity, acting on a rRNA
+intersection_of: GO:0003824 ! catalytic activity
+intersection_of: has_input CHEBI:18111 ! ribosomal RNA

GO:0140101
 name: catalytic activity, acting on a tRNA
+intersection_of: GO:0003824 ! catalytic activity
+intersection_of: has_input CHEBI:17843 ! transfer RNA

Thanks, Pascale

**Comment by pgaudet** [comment]
Added missing parent: 
- GO:0034353 RNA pyrophosphohydrolase activity -> is_a catalytic activity, acting on RNA
- GO:0110152 RNA NAD-cap (NAD-forming) hydrolase activity -> is_a catalytic activity, acting on RNA
- GO:0110153 RNA NAD-cap (NMN-forming) hydrolase activity  -> is_a catalytic activity, acting on RNA
