### ISSUE TITLE
negative regulation of calcineurin mediated signaling

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14206]
Hi, 
Id like to request negative regulation of calcineurin mediated signaling (GO:0097720 )
Standard def

ref PMID:25081204

**Comment by hdrabkin** [comment]
Hi Antonia; I added all three
GO:0106056 regulation of calcineurin-mediated signaling
GO:0106057 negative regulation of calcineurin-mediated signaling
GO:0106058 positive regulation of calcineurin-mediated signaling
DO you have a GOC:xxx for yourself?

**Comment by Antonialock** [comment]
I think I'm goc:al
