### ISSUE TITLE
SUMO-specific protease activity: do not manually annotate

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14203]
SUMO-specific protease activity GO:0016929 has been tagged as a gocheck_do_not_manually_annotate.

I see there is a lot of chat about it here #13941. But I can't seem to find the decision for it not to be allowed in manual annotation.

Is this a mistake? If not, please add some extra notes/guidance on why/how we should be able to chose better terms.

**Comment by ValWood** [comment]
Hi Helen,

SUMO specific protease has 2 children:


If you have experiemtnal evidence you should be able to distinguish. They are quite different activities. One is about  processing SUMO (maturation). The other one is removing SUMO itself from a modified protein.

GO:0070140    SUMO-specific isopeptidase activity 
GO:0070139    SUMO-specific endopeptidase activity

A comment   to this effect would be useful though.


Also,
GO:0070137    ubiquitin-like protein-specific endopeptidase activity

should have a "protein maturation" parent.

(Note the same enzyme often performs both activities)

**Comment by hattrill** [comment]
OK, that's sounds fine.

>Please can editor can add a comment to the term to reflect this.
