### ISSUE TITLE
NTR: glycosylphosphatidylinositol-mannosyltransferase **II** complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14204]
We have: GO:1990529 glycosylphosphatidylinositol-mannosyltransferase I complex
Def: A protein complex that is involved in the transfer of the four mannoses in the GPI-anchor precursor. In yeast S. cerevisiae this complex consists of Pbn1p and Gpi14p and in rat this complex consists of PIG-X and PIG-M. 

We also need the type II complex as well:
Name: glycosylphosphatidylinositol-mannosyltransferase **II** complex
Def: A protein complex that is involved in the transfer of the second mannose to the glycosylphosphatidylinositol (GPI) during GPI precursor assembly. In yeast S. cerevisiae this complex consists of GPI18p and PGA1p.

All relationships as per type I complex and add
capable_of_part_of GO:0035268 protein mannosylation 
to both complexes.

Refs:
GOC:bhm
PMID:17615295
IntAct:EBI-16398134

Thanks, Birgit

**Comment by ValWood** [comment]
Hi,
The parentage here looks a bit odd
https://www.ebi.ac.uk/QuickGO/term/GO:1990529

Isn't this glycosylphosphatidylinositol-mannosyltransferase I complex
manosylating the GPI anchor pre attachment to the protein?

v

**Comment by bmeldal** [comment]
Yes, well spotted, Val.

capable_of_part_of should be to GO:0097502 mannosylation

Birgit

**Comment by ValWood** [comment]
check out
https://github.com/geneontology/go-ontology/issues/14578#issuecomment-344969552

v

**Comment by ValWood** [comment]
ignore, not the right ones....

**Comment by bmeldal** [comment]
Yes, ticket #14578 refers to a different child of mannosyltransferease activity.
But above mentioned parentage for these complexes is still incorrect.

**Comment by ValWood** [comment]
yep.

**Comment by krchristie** [comment]
For both the type I and II complexes, Ichanged the relationship 
**from**: `capable_of_part_of GO:0035268 protein mannosylation`
**to**: `capable_of_part_of GO:0097502 mannosylation`
