### ISSUE TITLE
NTR high-affinity potassium ion import across plasma membrane 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14210]
Hi,
I'd like to request the term
high-affinity potassium ion import across plasma membrane 
child of

GO:0010163  high-affinity potassium ion import
GO:1990573 potassium ion import across plasma membrane

standard def, ref PMID:10629185

**Comment by pgaudet** [comment]
Hello, 

I was going to propose to merge the 'high affinity' -types of transport in the biological processes to their corresponding 'x transport' parent. It seems to me having MF "high affinity transporter activity" is sufficient. The BP 'x transport' should be applicable to both. 

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I was going to suggest the same, I think we only need to capture the "high-affinity' in one place.

So 
MF high-affinity potassium ion transporter part_of   potassium ion import across plasma membrane
would be fine.

@Antonialock  we should check that we have the  high affinity  MF annotated before these merges or we may lose the info.

**Comment by Antonialock** [comment]
Sounds great to streamline.

Can I then request
High affinity potassium ion transmembrane transporter activity
instead? child of
potassium ion transmembrane transporter activity

**Comment by pgaudet** [comment]
@Antonialock  sounds good, let's do this as MF

**Comment by Antonialock** [comment]
So I will need 
MF: High affinity potassium ion transmembrane transporter activity
BP: potassium ion import across plasma membrane

right? @pgaudet @ValWood

**Comment by ValWood** [comment]
I forgot we had already discussed high-affinity in this ticket!
https://github.com/geneontology/go-ontology/issues/14322

and yes I think so...

**Comment by pgaudet** [comment]
- Created new term: 
+[Term]
+id: GO:0140107
+name: high-affinity potassium ion transmembrane transporter activity
+namespace: molecular_function
+def: "Enables the transfer of potassium ions from one side of a membrane to the other. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [PMID:10629185]
+is_a: GO:0015079 ! potassium ion transmembrane transporter activity
+created_by: pg
+creation_date: 2017-10-12T09:54:39Z

- potassium ion import across plasma membrane already exists (GO:1990573) 

Thanks, Pascale
