### ISSUE TITLE
NTR high affinity glucose transmembrane transporter activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14212]
From #14210 We would like to request high affinity glucose transmembrane transporter activity thanks.

**Comment by Antonialock** [comment]
whups, edited the NTR to reflext the MF not the BP

**Comment by Antonialock** [comment]
This can probably be done together with #14210

**Comment by pgaudet** [comment]
Hi @Antonialock 
Is the reference also PMID:10629185? I dont see the mention of high affinity glucose transport there. 

Thanks, Pascale

**Comment by Antonialock** [comment]
Sorry it is PMID:25411338

**Comment by pgaudet** [comment]
thanks !
