### ISSUE TITLE
NTR: vacuole-isolation membrane contact site

### ISSUE THREAD

**Issue by Jackson73** [geneontology/go-ontology#14213]
Hello, 

I would like to request the following new term be added to the component ontology as an instance of 'organelle membrane contact site' (GO:44232):

Definition: An organelle membrane contact site formed at the junction of the vacuolar membrane and the isolation membrane or phagophore in response to starvation or other stresses, leading to the formation of the autophagosome 

definition_reference: PMID: 23549786

exact synonyms: VICS; vacuole-IM contact site; vacuole-phagophore contact site

placement:

organelle membrane contact site; GO:44232
---<vacuole-isolation membrane contact site; GO:new
---<nucleus-vacuole junction; GO:0071561
---<vacuole-mitochondrion membrane contact site; GO:1990816
---<ER-vacuole membrane contact site; GO:0098853
---<ER-mitochondrion membrane contact site; GO:0044233

Thank you very much for your time,

Terry

**Comment by krchristie** [comment]
Added as you requested, except that we have a practice of not adding acronyms as "EXACT" synonyms, but rather as "RELATED", to avoid any problems if the same acronym is used for another meaning.
