### ISSUE TITLE
MF refactor - receptor ligand activity

### ISSUE THREAD

**Issue by thomaspd** [geneontology/go-ontology#14220]
This class should be given a new parent (molecular role), a new definition, and some new children. Definition:
A gene product from one cell, that interacts with a receptor on another cell.  The molecule generally diffuses from one cell to another, though some types of receptor ligands (such as Notch ligands) are attached to the cell surface.
Synonym: signaling molecule

Children, see image below:
![screen shot 2017-09-17 at 4 25 39 am](https://user-images.githubusercontent.com/11966328/30520453-de6ff6ce-9b62-11e7-930e-b9f8ac5a0336.png)

This term has a sibling called "receptor activator activity" that should mean the same thing, but has numerous issues itself so I suggest we do not merge these terms but deal with "receptor activator activity" as a separate issue.

**Comment by pgaudet** [comment]
For reference: the current definition is: "Binding to a signaling receptor as part of signaling and modulating the effector activity of that receptor to initiate a change in cell activity. Signaling in this context may refer to cell-cell or matrix-cell signaling, eg. where an extracellular ligand released by one cell binds to a receptor on or in another cell. It may also refer to intracellular signaling - the IP3 receptor is activated by a second messenger (IP3) and some nuclear receptors respond to intracellular signals."

@thomaspd your new definition does not explicitely intracellular receptors; it may be useful to do so ? 

Pascale

**Comment by pgaudet** [comment]
I also propose to move the following terms under receptor ligand activity: 
- hormone activity
- growth factor activity
- cytokine activity
-opoid peptide activity

**Comment by pgaudet** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/4782928/30536956-309cbaee-9c68-11e7-8232-732ed5dec9a3.png">

**Comment by RLovering** [comment]
I have a feeling that potentially a cell could release a ligand that then binds the cell that it was released from. So I just wonder if the definition needs to be slightly broader?

**Comment by deustp01** [comment]
Following on Ruth's comment, yes, indeed, that's classic autocrine signaling with eicosanoids as a prominent example. I can't figure out whether this case is already covered by the discussion of nuclear hormone receptors that can bind ligands generated in the same cell that houses the receptor.

**Comment by vanaukenk** [comment]
I was also wondering about classic autocrine signaling wrt the definition.

Another question I had about the def is whether we want to make it clear in the def that the interaction directly regulates the activity of the receptor.  The inferred regulates relation is in the ontology, but I think we may want to make that clear in the def, as well, no?

How about something like this:

The activity of a gene product that interacts with a receptor to effect a change in the activity of the receptor.  Ligands may be produced by the same, or different, cell that expresses the receptor.  Ligands may diffuse extracellularly from their point of origin to the receiving cell, or remain attached to an adjacent cell surface (e.g. Notch ligands).
Synonym: signaling molecule

**Comment by bmeldal** [comment]
Your definitions clearly exclude any intracellular receptor ligand activities (can't think of one right now but they must exists for nuclear receptors at least) or non-self ligands (e.g. toxins or pathogens) that may activate an extracellular receptor.
Shouldn't that be made clearer in the term name? And could you add a comment to point users to the correct terms for the above mentioned cases?

Birgit

**Comment by bmeldal** [comment]
Reopened so new comments/suggestions don't fall through the cracks.

**Comment by pgaudet** [comment]
Hi, 

I have changed the definition to the one suggested by @vanaukenk with a very small modification: 
"to effect a change in the activity of **its** receptor." 

@bmeldal @RLovering @deustp01 @thomaspd @vanaukenk 
does that address the feedback ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
NEW def: "The activity of a gene product that interacts with a receptor to effect a change in the activity of its receptor. Ligands may be produced by the same, or different, cell that expresses the receptor. Ligands may diffuse extracellularly from their point of origin to the receiving cell, or remain attached to an adjacent cell surface (e.g. Notch ligands)." [GOC:kv, GOC:molecular_function_refactoring, GOC:pdt]
 subset: goslim_chembl
 synonym: "receptor agonist activity" BROAD [GOC:molecular_function_refactoring]
+synonym: "signaling molecule" EXACT []

**Comment by bmeldal** [comment]
I preferred "the" receptor as "its" receptor could be yet another molecule (I may be spitting hairs though...). 

"from the point of origin": does that point of origin include foreign bodies, i.e. pathogens, and their products activating a receptor?

**Comment by pgaudet** [comment]
waiting for a final definition - anyone else has comments ?

**Comment by pgaudet** [comment]
Updated the "its" abck to "the" in the definition. 

For the "point of origin" issue, the general GO practice is that the scope of annotation covers normal processes, so the point of origin can be anywhere as long as the response is 'normal' - hence I left this part in. OK ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
I know GO normally only captures normal processes so maybe my question was irrelevant!

**Comment by pgaudet** [comment]
;) I'm closing this.
