### ISSUE TITLE
MP: mitotic spindle related

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14231]
Probably
- [x]  GO:0000022    mitotic spindle elongation (already has)
GO:0090307    mitotic spindle assembly
GO:1990810    microtubule anchoring at mitotic spindle pole body

should be part of 
mitotic chromosome segregation

(I don't think  all of GO:0007052    
mitotic spindle organization can go under this term because disassembly occurs after chromosome segregation is complete).

**Comment by ValWood** [comment]
also
GO:1990810 microtubule anchoring at mitotic spindle pole body

should be part of
GO:0090307 mitotic spindle assembly

**Comment by ukemi** [comment]
Are the spindle formation terms really part of the segregation or do they happen before it and are required for it? Doe the process begin with the formation of the spindle or does it begin with the condensation of the chromosomes, alignment at the metaphase plate and then subsequent movement by translocation and spindle elongation? If we add spindle assembly, then it's gene products will be associated with chromosome segregation. Are they really involved in the segregation, or do cell display a segregation phenotype when they are mutated?

**Comment by ValWood** [comment]
Maybe it shouldn't be.
I have been   unsure about these for years.

Although chromosomes begin condensation in interphase and through pro-metaphase? , and spindle assembly occurs in prophase and pro-metaphase.
I think it's easier to see them as separate in mammals where the spindle forms in the cytoplasm.

OK  convinced. Instead can we add just
GO:1990810 microtubule anchoring at mitotic spindle pole body
 part of
GO:0090307 mitotic spindle assembly

**Comment by ukemi** [comment]
I am on the same page as you with these, but I think from an annotation perspective the formation of the spindle is necessary, but separate. I will certainly add the last bit.

**Comment by ValWood** [comment]
yep I agree. I think we have been her before.
And it's consistent with what I said here last week ;)
https://github.com/geneontology/go-ontology/issues/13461
