### ISSUE TITLE
Proposal to obsolete 'transmembrane electron transfer carrier' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14234]
Hello, 

The term 'transmembrane electron transfer carrier' has only been used once for EXP annotation (P36655) by EcoCyc @keseler
'Electron carrier activity' would be more accurate to describe the function. 

We can create a better BP to express what the protein is doing- any suggestions? 

I also propose to obsolete the two children (no annotations): 
-  GO:0022866 transmembrane 1-electron transfer carrier
-  GO:0022867 transmembrane 2-electron transfer carrier

Thanks, 

Pascale

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete:’GO:0022865 transmembrane electron transfer carrier'

and its two children 
-  GO:0022866 transmembrane 1-electron transfer carrier
-  GO:0022867 transmembrane 2-electron transfer carrier
The reason for obsoletion is that the term does not represent a molecular function but rather a process: "The transmembrane electron transfer carriers in the membrane include two-electron carriers, such as the disulfide bond oxidoreductases (DsbB and DsbD in E. coli) as well as one-electron carriers such as NADPH oxidase.” (https://en.wikipedia.org/wiki/Membrane_transport_protein) 

There is 1 experimental annotation to this term and 2 NAS. 

Comments can be added to the issue: 

https://github.com/geneontology/go-ontology/issues/14234

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on August 26, 2017.

*** Unless objections are received by August 26, 2017, we will assume that you agree to this change. ***

Best regards,

Pascale

**Comment by amandamackie** [comment]
Regarding a BP term for the P36655 (DsbD)

Suggested name: protein disulfide bond formation via L-cysteine oxidation
New term would be a child of GO:0018171 peptidyl-cysteine oxidation and the definition for this latter term should be expanded to indicate that peptidyl cysteines can be modified to form inter and intra disulfide bonds (amongst other things - PMID 16716890 Eaton 2006 has a nice diagram of protein thiol oxidation products)

GO:0055114 oxidation-reduction process has a child term for protein oxidation (GO:0018158) but no term for protein reduction and more specifically protein disulfide reduction - suggested def: the modification of a protein by reduction of one or more disulfide bonds (PMID 11544348 Ritz 2001)

E. coli DsbD functions as part of an electron transport chain whereby electrons are transferred from thioredoxin in the cytoplasm via DsbD in the membrane to reduce periplasmic proteins. Would a new child of GO:0022900 electron transport chain be appropriate? I'm unsure about this because the definition of electron transport chain refers specifically to the generation of a transmembrane electrochemical gradient. 

Amanda (EcoCyc curator)

**Comment by amandamackie** [comment]
Regarding the proposal to obsolete GO:0022865 transmembrane electron transfer carrier'

It was suggested that electron carrier activity (GO:0009055) is a better MF term for DsbD function. I agree but I would like to suggest a new term which would be child of electron carrier activity:
Suggested name: electron transporter, transferring electrons within the cellular protein thiol-disulfide redox pathways

**Comment by ValWood** [comment]
isn't that a molecular function?
protein-disulfide reductase activity

**Comment by amandamackie** [comment]
Yes and we use that term for DsbD and others in EcoCyc - I think I misunderstood Pascale's post to suggest that we should also use an electron carrier MF term for P36655 but perhaps that's not what he meant.  Sorry - not very experienced with using the ontology.

**Comment by pgaudet** [comment]
Hi @amandamackie 

Thanks for your input. It sounds like you will not miss the annotation to 'transmembrane electron transfer carrier'  and that the current annotation to 'protein disulfide oxidoreductase activity' correctly captures the function of P36655. I'll go ahead with the obsoletion in this case. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsoletions: 
 [Term]
 id: GO:0022865
-name: transmembrane electron transfer carrier
+name: obsolete transmembrane electron transfer carrier
 namespace: molecular_function
-def: "Enables electron flow across a biological membrane, from donors localized on one side of the membrane to acceptors localized on the other side. These systems contribute to or subtract from the membrane potential, depending on the direction of electron flow. They are therefore important to cellular energetics." [GOC:mtg_transport, ISBN:0815340729, TC:5]
+def: "OBSOLETE. Enables electron flow across a biological membrane, from donors localized on one side of the membrane to acceptors localized on the other side. These systems contribute to or subtract from the membrane potential, depending on the direction of electron flow. They are therefore important to cellular energetics." [GOC:mtg_transport, ISBN:0815340729, TC:5]
+comment: The reason for obsoletion is that the term does not represent a molecular function but rather a process: "The transmembrane electron transfer carriers in the membrane include two-electron carriers, such as the disulfide bond oxidoreductases (DsbB and DsbD in E. coli) as well as one-electron carriers such as NADPH oxidase.” (https://en.wikipedia.org/wiki/Membrane_transport_protein)
 xref: TC:5
-is_a: GO:0022857 ! transmembrane transporter activity
+is_obsolete: true
 
 [Term]
 id: GO:0022866
-name: transmembrane 1-electron transfer carrier
+name: obsolete transmembrane 1-electron transfer carrier
 namespace: molecular_function
-def: "Enables transfer of one electron across a membrane." [GOC:mtg_transport, ISBN:0815340729, TC:5.B]
+def: "OBSOLETE. Enables transfer of one electron across a membrane." [GOC:mtg_transport, ISBN:0815340729, TC:5.B]
+comment: The reason for obsoletion is that the term does not represent a molecular function but rather a process: "The transmembrane electron transfer carriers in the membrane include two-electron carriers, such as the disulfide bond oxidoreductases (DsbB and DsbD in E. coli) as well as one-electron carriers such as NADPH oxidase.” (https://en.wikipedia.org/wiki/Membrane_transport_protein)
 synonym: "transmembrane one-electron transfer carrier" EXACT [GOC:mah]
-is_a: GO:0022865 ! transmembrane electron transfer carrier
+is_obsolete: true
 
 [Term]
 id: GO:0022867
-name: transmembrane 2-electron transfer carrier
+name: obsolete transmembrane 2-electron transfer carrier
 namespace: molecular_function
-def: "Enables transfer of two electrons across a membrane." [GOC:mtg_transport, ISBN:0815340729, TC:5.A]
+def: "OBSOLETE. Enables transfer of two electrons across a membrane." [GOC:mtg_transport, ISBN:0815340729, TC:5.A]
+comment: The reason for obsoletion is that the term does not represent a molecular function but rather a process: "The transmembrane electron transfer carriers in the membrane include two-electron carriers, such as the disulfide bond oxidoreductases (DsbB and DsbD in E. coli) as well as one-electron carriers such as NADPH oxidase.” (https://en.wikipedia.org/wiki/Membrane_transport_protein)
 synonym: "transmembrane two-electron transfer carrier" EXACT [GOC:mah]
-is_a: GO:0022865 ! transmembrane electron transfer carrier
+is_obsolete: true
