### ISSUE TITLE
Merge ' GO:0036370 D-alanyl carrier activity' with ' GO:0047473  D-alanine-poly(phosphoribitol) ligase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14237]
Hello, 

From the annotations (all from InterPro), it seems clear that 'D-alanyl carrier activity' is part of the D-alanine-poly(phosphoribitol) ligase activity. 

@asangrador  Can you please confirm and I will merge the two terms. 

Thanks, Pascale

**Comment by asangrador** [comment]
Hi Pascale,
Are you referring to the annotation coming from entry IPR003230, for DltC? 
We have given this entry the Uniprot name D-alanine--poly(phosphoribitol) ligase subunit 2, but it is a  D-alanyl carrier protein, whereas DltA (IPR010072) is the proper D-alanine--poly(phosphoribitol) ligase that catayses the D-alanylation of the carrier protein DltC. That is why they have been given the terms 'D-alanyl carrier activity' and D-alanine-poly(phosphoribitol) ligase activity’ respectively. According to UniProt they catalyse both the reaction EC:6.1.1.13, but DltC is a carrier protein.

Please let me know if I have misunderstood you,
Amaia

**Comment by pgaudet** [comment]
Hi Amaia

Thanks for the clarification. It would help if the InterPro entry explained the reaction of dcp; right now it's generic about biosynthesis of D-alanyl-lipoteichoic acid, and the reaction catalyzed by IPR003230 is not described. 
In fact IPR010072 seem to imply that this family catalyzes both reaction, and UniProt has the same reaction for both dltA and dltC: 

IPR010072 DltA  
It activates D-alanine as an adenylate via the reaction D-ala + ATP to D-ala-AMP + PPi, and further catalyses the condensation of the amino acid adenylate with the D-alanyl carrier protein (D-ala-ACP). 


Q88VM6 dltA
Catalyzes an ATP-dependent two-step reaction where it forms a high energy D-alanyl AMP intermediate and transfers the alanyl residues from AMP to Dcp.UniRule annotation
Catalytic activityi
ATP + D-alanine + poly(ribitol phosphate) = AMP + diphosphate + O-D-alanyl-poly(ribitol phosphate).


-----
IPR003230. DltC. 
No description of reaction


P39579 dltC
Activated D-alanyl-Dcp donates its D-alanyl substituent to membrane-associated LTA.UniRule annotation
Catalytic activity
ATP + D-alanine + poly(ribitol phosphate) = AMP + diphosphate + O-D-alanyl-poly(ribitol phosphate).


I am happy to keep both GO terms but please can you be more specific about the reactions in the respective entries? 

Thanks, 

Pascale

**Comment by pgaudet** [comment]
@pedruzzi please comment for UniRule annotations :)

**Comment by asangrador** [comment]
Hi Pascale,

I will add the description of the role of DltC. You are right, it is a bit confusing at the moment. I don't understand the naming given by Uniprot or why they have the same reaction for both, I can't find any basis for this in the literature.
Cheers,
Amaia

**Comment by pedruzzi** [comment]
Hi all,

to the UniProt annotations:
I agree with both of you that the 2 proteins have a completely different role in this pathway. DltA is the ligase that, in a 2 step reaction, adenylates the substrate D-alanine with the release of PPi and then transfers the whole bunch onto the phosphopantheinyl prosthetic group of DltC, which is the carrier protein (also just called Dcp). From there, the D-alanyl group is then further transferred by DltD to the poly(glycerol phosphate).
The problem in the current UniProt annotations I can see stems from the EC definition. The EC 6.1.1.13 (and its associated catalytic acitivity) actually does not describe the enzymatic activity of the ligase DltA alone, but of the whole process described above. That's why the EC had been assigned to both DltA and DltC (and should have been to DltD as well), and the rest went on automatically.
A common problem with EC numbers as they describe reactions and not the enzymes that carry them out. Luckily, it seems that the enzyme commission is on the way of splitting this particular case up:
https://biocyc.org/META/substring-search?type=REACTION&object=6.1.1.13
DltA will be 6.2.1.M5, DltC will have no EC no more, and DltD will be 2.3.1.M31

To fix this already until the ECs are sorted out I propose to update the UniProt (&UniRule) annotations with clearer descriptions and keeping EC 6.1.1.13 in DltA, while removing it from DltC, for a better distinction of the ligase from the carrier protein.

-ivo

**Comment by pedruzzi** [comment]
to the GO terms:

in principle, Pascale was right in the beginning that
> 'D-alanyl carrier activity' is part of the D-alanine-poly(phosphoribitol) ligase activity
because the current term describes the entire process (e.g. ligase, carrier protein intermediate, transfer to acceptor of the D-alanyl group) similar to the EC definition in my opinion.

It may make sense to update this GO term as well and use the current synonym "D-alanine-D-alanyl carrier protein ligase activity", which describes only the DltA ligase, as master term?
I don't know the implications of this on the hierarchy and the assignment of this term on the proteins though as I haven't checked yet where it is all used

Best
-ivo

**Comment by pgaudet** [comment]
Hi @pedruzzi 
Thanks for looking into this. There are little implications in merging the two terms, since they don't have children and they are not used a part of other terms/term definitions. 

It sounds like the two reactions 'D-alanyl carrier activity' and 'D-alanine-poly(phosphoribitol) ligase activity' always occur together (ie, there is no D-alanyl carrier activity in any other context), then it sounds to me like a single reaction with two steps, catalyzed by an enzyme complex, ie just like it's described in UniProt "Catalyzes an ATP-dependent two-step reaction where it forms a high energy D-alanyl AMP intermediate and transfers the alanyl residues from AMP to Dcp." To me that would be  OK to make that a single reaction. I'll check with the GO editors. (but anyone else's input is welcome!!)

(still the annotations could be clarified to explain which subunit is the alanyl carrier and which is the ligase - in UniProt dltA sounds like it has both activities). 

Thanks, Pascale

**Comment by pedruzzi** [comment]
ok, this seems still a bit confusing.

- My advice is NOT merging the terms. 'D-alanyl carrier activity' is only a part of 'D-alanine-poly(phosphoribitol) ligase activity'. 'D-alanine-poly(phosphoribitol) ligase activity' is (in its current state, which is what I propose to change, see below) true for both DltA and DltC. 'D-alanyl carrier activity' is only true for DltC, but not for DltA. So I guess merging is not the way to go.

- The 2 steps mentioned in DltA are not 'D-alanine-poly(phosphoribitol) ligase activity' and 'D-alanyl carrier activity', they are both part of the ligase reaction D-alanine-D-alanyl carrier protein ligase. Neither of these 2 steps does apply to DltC, which is only the carrier.

- my proposal is to rebrand 'D-alanine-poly(phosphoribitol) ligase activity', which is a multienzyme reaction including DltA, DltB, DltC and DltD and is too broad, to 'D-alanine-D-alanyl carrier protein ligase activity', which is a single enzyme (2-step) reaction that would only apply to DltA (the future 6.2.1.M5).
A definition would be similar to the current UniProt DltA annotation "Catalysis of an ATP-dependent two-step reaction that forms a high energy D-alanyl AMP intermediate and transfers the alanyl residues from AMP to a D-alaninyl carrier protein" or something more similar to the current: "Catalysis of the reaction: D-alanine + ATP + a [D-alaninyl carrier protein]=  a D-alanyl-[D-alanyl carrier protein] + diphosphate + AMP."

- the multienzyme reaction 'D-alanine-poly(phosphoribitol) ligase activity' function term is itself better represented by the  GO:0070400 'teichoic acid D-alanylation' process term.

- and yes, I will update the annotations of both DltA and DltC to make the role of these 2 proteins in this process clearer ;-) (I was a bit fast with DltD, while clearly involved, there are currently multiple models of which part this protein and DltB play in the process and it is not yet clear which is true)

Hope this helps :-)
-ivo

**Comment by pedruzzi** [comment]
...or in short:
EC 6.1.1.13 has been a very bad description for a process and has unfortunately found its way into GO as 'D-alanine-poly(phosphoribitol) ligase activity'. I think this is what we should correct.

and yes I will also propose new recommended names for the 2 proteins in UniProt, as the current ones only add to the confusion

Cheers
-ivo

**Comment by asangrador** [comment]
I agree with Ivo,  giving the GO term 'D-alanine-poly(phosphoribitol) ligase activity' to DltC would be misleading, as it seems to imply that the protein is a ligase -or part of a complex that acts as a ligase- when that is not the case. 'D-alanine-poly(phosphoribitol) ligase' as stand now encompasses the activities of 4 enzymes with different roles.
Amaia

**Comment by pgaudet** [comment]
Thanks for the feedback, I will no merge. @pedruzzi can you please provide improved definitions and class labels to avoid confusion in the future ? 

Thanks, Pascale

**Comment by pedruzzi** [comment]
done so far:
- updated annotations for dltA in SP and rule MF_00593 (for TrEMBL), specifically replacing EC 6.1.1.13 by EC 6.2.1.- and describing only the ligase reaction that is actually catalyzed by this protein. MF_00593 will propagate  GO:0047473 (the ligase activity) for which I will propose an updated definition below.
- updated annotations for dltC in SP and rule MF_00565 (for TrEMBL), specifically removing EC 6.1.1.13, as this protein is not itself catalytically active, but functions as a coenzyme covalently binding a substrate, thereby keeping it in an activated state and presenting it to other enzymes for further modification, analogous to acyl carrier protein (ACP), peptidyl carrier protein (PCP) or (nonprotein) coenzyme CoA. This will remove EC 6.1.1.13-associated GO terms/KWs like ATP-binding, Ligase activity etc from all protein family members. Additionally, MF_00565 will propagate GO:0036370 (the carrier activity) to these proteins.

This should solve the issue with overlapping annotations and will obviate the need to merge these 2 GO terms.

Annotations not public before UniProt release 2017_11 (around 22 Nov 2017)

**Comment by pedruzzi** [comment]
proposal for GO:0047473:

I propose to narrow down this GO term to describe only the activity of the first ligase reaction. This would also imply to move the term from the "ligase activity, forming carbon-oxygen bonds" branch to the "ligase activity, forming carbon-sulphur bonds" branch as a direct child of GO:0016878 "acid-thiol ligase activity"

id: GO:0047473

name: D-alanine [D-alanyl carrier protein] ligase activity
namespace: molecular_function
def: "Catalysis of the ATP-dependent activation of D-alanine and its transfer as a thiol ester to the phosphopantheinyl prosthetic group of the D-alanyl carrier protein (Dcp)" [MetaCyc: 6.2.1.M5 -RXN]
subset: gosubset_prok
synonym: "D-alanine-activating enzyme activity" RELATED []
synonym: "D-alanine-D-alanyl carrier protein ligase activity" EXACT [EC:6.2.1]
synonym: "D-alanine:poly(phosphoribitol) ligase (AMP-forming)" BROAD []
synonym: "D-alanine-poly(phosphoribitol) ligase activity" BROAD []
xref: EC:6.2.1
xref: MetaCyc: 6.2.1.M5 -RXN
is_a: GO:0016878 ! acid-thiol ligase activity

Kristian is currently checking whether IUBMB will create a new EC as well as proposed by MetaCyc, and as soon as I have confirmation I will have it added to this term

**Comment by pedruzzi** [comment]
and by moving GO:0047473, we would remove the only non aminoacyl-tRNA substrate child term from GO:0016876 "ligase activity, forming aminoacyl-tRNA and related compounds", meaning GO:0016876 should then be merged into (its only remaining child) GO:0004812 "aminoacyl-tRNA ligase activity", which becomes a direct child of GO:0016875 "ligase activity, forming carbon-oxygen bonds" then.

Should I create a separate issue for this?

**Comment by pgaudet** [comment]
All good, I also did the merge as part of this ticket. Thanks @pedruzzi ! 

Pascale

**Comment by pgaudet** [comment]
Added missing xrefs: 
+xref: EC:6.2.1.54
+xref: RHEA:55132
