### ISSUE TITLE
Children of 'cell'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14235]
Hello, 

It as pointed out to me by Swiss-Prot that cell has a small number of direct children: 

[Current term] GO:0005623 cell
         [part_of relation] GO:0044464 cell part
         [occurs_in relation] GO:0019725 cellular homeostasis
         [part_of relation] GO:1990722 DAPK1-calmodulin complex
         [part_of relation] GO:1990065 Dxr protein complex
         [occurs_in relation] GO:0051649 establishment of localization in cell
         [occurs_in relation] GO:0032507 maintenance of protein location in cell
         [part_of relation] GO:1990204 oxidoreductase complex
         [part_of relation] GO:1990455 PTEN phosphatase complex 

This seems to result from an inconsistency in our relations. @ukemi do you know what this is caused by ? 

Thanks, Pascale

**Comment by ukemi** [comment]
The occurs_in relationships make sense to me based on the generic nature of the terms. The part_ofs are asserted. I think you are correct that in these cases, we have represented parts of a cell differently than we do in most other cases.
