### ISSUE TITLE
Term merge: basolateral protein localization and protein localization to basolateral plasma membrane

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14233]
Following up on #14168 14168

These two terms seem synonymous and should be merged: 
- GO:0061467    basolateral protein localization
-  GO:1903361   protein localization to basolateral plasma membrane
should be merged under GO:0061467    basolateral protein localization, since this term is correctly placed under asymetrical localization. 

Thanks, Pascale

**Comment by ukemi** [comment]
Is basolateral loacalization always to the plasma membrane? Can't it just be to the region of the cell?

**Comment by deustp01** [comment]
The dictionary definition of basolateral allows it to refer to the region, but in my anecdotal sample of cell biology talks and papers I've never encountered the word except as an adjective modifying "membrane".

**Comment by ukemi** [comment]
I thought sometimes there were elements of the cytoskeleton that were considered to be basolateral, but I may be mistaken. Just want to be sure we check before we merge.

**Comment by pgaudet** [comment]
It seems like a grammatical problem: 
'Unqualified' basolateral means "situated below and toward the side" https://www.merriam-webster.com/medical/basolateral
so we need to have a noun to express 'basolateral to what'. 

Does that sound right to native speakers ? 

Pascale

**Comment by lbreuza** [comment]
So far I had only heard about basolateral plasma membrane but authors can use basolateral when talking about the basolateral domain of the plasma membrane by opposition to the apical domain. However, I noticed that in the ontology we have basolateral cytoplasm and basolateral part of cell which indicate we once assumed it could also correspond to a region of the cell.

**Comment by pgaudet** [comment]
Thanks @lbreuza this is helpful. 

- in the reference cited for GO:0090652 basolateral cytoplasm (PMID:17494872), they explicitely mention plasma membrane: "The plasma membranes of epithelial cells plasma membranes contain distinct apical and basolateral domains that are critical for their polarized functions" 
So I think these terms should be renamed as well.

**Comment by krchristie** [comment]
@pgaudet - Based on the number of annotations to each term, it would be easier for annotating groups if you did the merge the other way around and kept the GO:1903361 term: 

- GO:0061467 basolateral protein localization - 7 annotations (2 exp, 5 ISS)
- GO:1903361 protein localization to basolateral plasma membrane - 165 annotations (148 IBA, 16 exp, 1 ISS)

Both of the two experimental annotations to 'basolateral protein localization' are discussing localization to basolateral plasma membrane, so I agree that this term has been used to mean the same thing as 'protein localization to basolateral plasma membrane'.

**Comment by pgaudet** [comment]
Hi @krchristie 
I wanted to merge into GO:0061467 to keep its parents. I thought that the direction of the merge dis not matter and that all annotations would be moved over regardless - isn't this the case @cmungall ? 

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet - In my experience, moving experimental annotations is dependent on the procedures in place at the MOD that made them, and is often manual. This is still true at MGI.

In the past, my recollection is that we have often taken into consideration which action will have the least impact on annotating groups. Considering that it is quite simple to change the parentage of the term, and that once the two terms are merged no one will care what the original parentage was, I don't really see how the parentage should be a major factor in deciding which term to make primary.

However, another factor to take into consideration is to make sure that we do NOT create a situation where we keep one the exact string of the term names, but switch it to the other ID. This is very difficult for some of the MODs to deal with.
