### ISSUE TITLE
new term request cellular component division septum

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#14241]
I need a new term **division septum** als location for 2.7.13.3 in bacteria. PMID:21219466 Definition: Division septum (Science: cell biology) The cell wall that forms between daughter cells at the end of mitosis in plant cells or just before separation in bacteria. http://www.biology-online.org/dictionary/Division_septum
**is a** cell wall... Thank you, with best wishes from brenda-enzymes, Marion

**Comment by brendamg** [comment]
Could it be a synonym of cell septum?

**Comment by hdrabkin** [comment]
So, is it a synonym of cell septum or a child (not familiar with the biology. 
It seems to be it would be a part of a cell wall, not a type of cell wall?

**Comment by ValWood** [comment]
I think the required term exists.

http://www.ebi.ac.uk/QuickGO/term/GO:0000935

(It is called barrier septum, to differentiate from other  uses of septum in biology, but it is for a bacterial/fungal type division septum.

**Comment by ValWood** [comment]
Hmm where have it's children gone? I'm sure it has "primary septum, secondary septum etc, but nothing in QuickGO right now?

http://www.ebi.ac.uk/QuickGO/term/GO:0000935

**Comment by hdrabkin** [comment]
ExceptGO:0000935 does not indicate being generated during division?

**Comment by ValWood** [comment]
but the parent does. So this must be?

Ignore the part about childen above, there aren't any.

**Comment by ValWood** [comment]
The barrier septum term is used for septa which entirely cross the cell. These are division septa. I seem to remember this was to distinguish from a type of sept that did not form a barrier. I don't know anything about these (i.e which organisms they are in).

Primary septum and secondary septum should be under  "barrier septum" though.

**Comment by hdrabkin** [comment]
There, there is nothing in the def for barrier septum that indicates it has anything to do with division. I guess it does, at the least, a synonym is in order.

**Comment by ValWood** [comment]
change def to

A *cell *septum which spans a cell and does not allow exchange of organelles or cytoplasm between compartments.

"cell septum" = 
A structure composed of peptidoglycan and often chitin in addition to other materials. It usually forms perpendicular to the long axis of a cell or hypha and grows centripetally from the cell wall to the center of the cell and often functions in the compartmentalization of a cell into two daughter cells.

**Comment by ValWood** [comment]
Actually cell septum only says 
*often* functions in the compartmentalization of a cell into two daughter cells.
not always

so instead
barrier septum=
A *cell *septum which functions in the compartmentalization of a cell into two daughter cells at division. A barrier septum spans a cell and does not allow exchange of organelles or cytoplasm between compartments.

**Comment by hdrabkin** [comment]
You mean change the def of "barrier septum to "a cell septum which spans a cell etc.?
And move primary and secondary to chldren of barrier septum?

**Comment by hdrabkin** [comment]
ah, I like that one better

**Comment by ValWood** [comment]
yep, and yep.

Maybe division septum is a better primary name. I always disliked barrier septum. Nobody uses that. I wonder why we never didi that.

**Comment by hdrabkin** [comment]
who was/is "clt" (GOC:clt)?

**Comment by ValWood** [comment]
Chandra Theesfeld.
Now there's a blast from the past!

**Comment by hdrabkin** [comment]
Checking on annotations now before altering

**Comment by hdrabkin** [comment]
ah... many other term name will need to be changed, that refer to "barrier septum" if we change the name:
barrier septum assembly
barrier septum site selection
regulation of barrier septum assembly
positive and negative regulation of barrier septum assembly
protein localization to barrier septum
and also text in the defs to the regulation and localization terms to switch it to division septum. 
argh!

**Comment by hdrabkin** [comment]
Part 1: Implimented everything except term name changes

**Comment by brendamg** [comment]
Hmm, so can I use the term "division septum" for our next update, or should I use the term "barrier septum" instead?

**Comment by hdrabkin** [comment]
Once renamed, it will have the same GO id as the current barrier septum; but I need to go over all of the current terms that barrier septum is referenced to/by.

**Comment by hdrabkin** [comment]
After looking at the terms and some of their references which use "division septum', I have renamed all instances of barrier septum to division septum, which include changing the instances in the definitions. Blame it on Val!
@brendamg  can use 'division septum'

**Comment by ValWood** [comment]
Thanks Harold.  Blame me if any problems. I think "division septum" is a more obvious term name.
