### ISSUE TITLE
review defs of 'sexual reproduction' and 'asexual reproduction'

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#14251]
The current def of 'sexual reproduction' begins with 'A reproduction process that creates a new organism by combining the genetic material of **two organisms**.' The current def of 'asexual reproduction' states 'The biological process in which new individuals are produced by either a single cell or a group of cells, in the absence of any sexual process.'

Should sexual reproduction really be about 'combining the genetic material of *two gametes*' rather than *two organisms*?  Thinking about self-fertilizing worms here.

**Comment by ukemi** [comment]
Correct, the existing definition does not fit for self-fertilizing hermaphrodites. If I recall correctly we struggled with the reproduction terms before. Does it just refer to overall fitness?

**Comment by tberardini** [comment]
Added to meeting list for 9/22/17.  May be faster to resolve on the call rather than by emailing back and forth.

**Comment by ukemi** [comment]
Thanks @tberardini

**Comment by krchristie** [comment]
@tberardini - If I understand this correctly, you are questioning if the definition of 'sexual reproduction' should be changed from its current wording of 'two organisms' to say instead 'two gametes' in order to accomodate self-fertilizing nematode worms. 

So, the question boils down to whether or not this type of self fertilization is 'sexual reproduction'. I don't have a good answer, but interestingly, I came across this story about these worms losing lots of genes once they switched to this mode of self-fertilization instead of mating:
https://phys.org/news/2012-11-self-fertilizing-worms-thousands-genes-reproduction.html 

Do we still need to discuss this at an editors meeting?

**Comment by tberardini** [comment]
> So, the question boils down to whether or not this type of self fertilization is 'sexual reproduction'.

Correct.  Also, many plants self-fertilize.  We could create a couple of new terms, 'allogamy' (gametes from two different individuals) and 'autogamy' (gametes from same individual) as children of 'sexual reproduction'.  @vanaukenk, would that work?

> Do we still need to discuss this at an editors meeting?

Yes.  Unless it can be resolved by discussion on this ticket, which is possible.

**Comment by krchristie** [comment]
At our meeting on November 13th, 2017, Kimberly and Tanya both agreed that both or their organisms have a form of sexual reproduction that occurs in a single individual organism. Thus we agreed to modify the definition of 'sexual reproduction' to accomodate this.

Here is the current definition:
> **Term**: sexual reproduction
> **Definition**: A reproduction process that creates a new organism by combining the genetic material of two **organisms**. It occurs both in eukaryotes and prokaryotes: in multicellular eukaryotic organisms, an individual is created anew; in prokaryotes, the initial cell has additional or transformed genetic material. In a process called genetic recombination, genetic material (DNA) originating from two different individuals (parents) join up so that homologous sequences are aligned with each other, and this is followed by exchange of genetic information. After the new recombinant chromosome is formed, it is passed on to progeny.

Here is a proposal to modify the definition, where the change is shown in bold:
> **Term**: sexual reproduction
> **Definition**: A reproduction process that creates a new organism by combining the genetic material of two **gametes, which may come from two organisms or from a single organism, in the case of self-fertilizing hermaphrodites, e.g. C. elegans, or self-fertilization in plants.** It occurs both in eukaryotes and prokaryotes: in multicellular eukaryotic organisms, an individual is created anew; in prokaryotes, the initial cell has additional or transformed genetic material. In a process called genetic recombination, genetic material (DNA) originating from two different individuals (parents) join up so that homologous sequences are aligned with each other, and this is followed by exchange of genetic information. After the new recombinant chromosome is formed, it is passed on to progeny.

@tberardini @vanaukenk Let me know if you think I missed anything.

**Comment by tberardini** [comment]
This latter part of the definition:

> genetic material (DNA) originating **from two different individuals (parents)** join up so that...

should probably be

> genetic material (DNA) originating **from the two gametes** join up so that...

**Comment by krchristie** [comment]
@tberardini - good catch, I'll make that change too

**Comment by vanaukenk** [comment]
@krchristie - the revised definition looks good to me.  Thanks!
