### ISSUE TITLE
NTR: Extracellular vesicle biogenesis

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#14256]
Hi,
these 2 papers, PubMed=22315426 and PubMed=27462458 describe the function of ARRDC1 in the biogenesis or at least the incorporation of proteins into extracellular vesicles which differ from the extracellular exosomes (a specific type of extracellular vesicle).  Could you please consider create that parent term (Extracellular vesicle biogenesis)?
This recent review, PubMed=28736435,  highlights the importance and the difference between exosomes and other extracellular vesicles.
Should we also consider a new term to describe processes that localize proteins to exosomes and other extracellular vesicles.
Thanks in advance.
Lionel

**Comment by vanaukenk** [comment]
@lbreuza 
Have you looked at the term 'vesicle budding from membrane' (GO:0006900)? 
https://www.ebi.ac.uk/QuickGO/term/GO:0006900
Would it work to create a new child, 'vesicle budding from plasma membrane' and then create an additional child term for 'extracellular vesicle budding from plasma membrane'?
One thing I want to be check on, though, is why 'vesicle budding from membrane' is a child of 'vesicle organization' and we don't have a term for 'vesicle biogenesis'.

For the localization terms, would you like new children of 'protein localization' (GO:0008104), or are there more specific BP terms you'd like to add?
Term definitions and suggested placement in the ontology are always welcome :-)

**Comment by lbreuza** [comment]
>
>
> @lbreuza
> Have you looked at the term 'vesicle budding from membrane' (GO:0006900)?
> https://www.ebi.ac.uk/QuickGO/term/GO:0006900
> Would it work to create a new child, 'vesicle budding from plasma membrane' and then create an additional child term for 'extracellular vesicle budding from plasma membrane'?
> One thing I want to be check on, though, is why 'vesicle budding from membrane' is a child of 'vesicle organization' and we don't have a term for 'vesicle biogenesis'.
That's fine with me.
>
> For the localization terms, would you like new children of 'protein localization' (GO:0008104), or are there more specific BP terms you'd like to add?
Yes I would if you think it makes sense regarding the ontology.
>
> Term definitions and suggested placement in the ontology are always welcome :-)
I though several terms could be required to properly describe in the ontology these process of extracellular vesicles production and therefore it was not making sense to ask for a single term.

Thanks,
Lionel

**Comment by pgaudet** [comment]
I am also merging 'exosome biogenesis' into 'exosome assembly' - the former is not being used and the definitions are very similar. 

Pascale
