### ISSUE TITLE
Make AGR and MGI slims accessible 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14261]
From
geneontology/go-ontology#13791

Providing the obo file here would do
http://www.geneontology.org/ontology/subsets/

I just need a way to access the up to date list of terms, (anywhere)

Note this is the last one provided
[AGRslim-from-GO.txt](https://github.com/geneontology/go-ontology/files/1329743/AGRslim-from-GO.txt)

But it does not seem to reflect all of the changes requested in
geneontology/go-ontology#13791

**Comment by cmungall** [comment]
you can get it here for now:

http://purl.obolibrary.org/obo/go/subsets/goslim_agr.obo

the two URLs will resolve to the same thing soon, @dougli1sqrd working on pipeline with @kltm 

The SOP for a new slim is that someone from the editors team still needs to edit the go website to say what it is

**Comment by ValWood** [comment]
Fab thanks.

**Comment by pgaudet** [comment]
The link doesnt work for me. 

In any case - looks like there is nothing to do here ? If that's the case, please close the ticket ( @ValWood or @cmungall  ) 

Thanks, Pascale

**Comment by cmungall** [comment]
> The link doesnt work for me.

This one?

http://purl.obolibrary.org/obo/go/subsets/goslim_agr.obo

That's odd. What is the error - 404?

> looks like there is nothing to do here

someone from the editors team still needs to edit the go website to add a description of the slim and a link

**Comment by ValWood** [comment]
got it anyway.

**Comment by pgaudet** [comment]
Hi @cmungall 
this is what I see when I follow the link: 
<img width="832" alt="image" src="https://user-images.githubusercontent.com/4782928/30897184-2fe1231c-a355-11e7-9ed0-163c99803e0b.png">

**Comment by pgaudet** [comment]
TO DO: someone from the editors team still needs to edit the go website to add a description of the slim and a link

**Comment by cmungall** [comment]
@pgaudet - just click download link in your browser.

Your browser is expecting XML due to this issue:
https://github.com/geneontology/pipeline/issues/8

**Comment by pgaudet** [comment]
Hi @cmungall 
What needs to be done to put the AGR slim here: 
http://www.geneontology.org/ontology/subsets/

Thanks, Pascale

**Comment by pgaudet** [comment]
@cmungall to provide the link

**Comment by pgaudet** [comment]
@dougli1sqrd perhaps you know how to find these links ?

**Comment by pgaudet** [comment]
@dougli1sqrd @cmungall Can you help with this ? 

Thanks

**Comment by dougli1sqrd** [comment]
The AGR goslim link works: http://snapshot.geneontology.org/ontology/subsets/goslim_agr.obo, but I can't find an MGI goslim. I'll look into it.

**Comment by dougli1sqrd** [comment]
Also, all subsets exist here from our daily build (called snapshot): http://snapshot.geneontology.org/ontology/subsets/.

I think for MGI, you could be looking for the mouse subset: http://snapshot.geneontology.org/ontology/subsets/goslim_mouse.obo

**Comment by pgaudet** [comment]
Are these for public consumption?

**Comment by cmungall** [comment]
@dougli1sqrd remember we always use PURLs for ontologies

This is the PURL we give to users:

 * http://purl.obolibrary.org/obo/go/subsets/goslim_agr.obo

This is the PURL we give to members of the GOC who require access more frequent than the monthly releases

 * http://purl.obolibrary.org/obo/go/snapshot/subsets/goslim_agr.obo

While anyone is welcome to use the snapshot, we only guarantee version preservation for the non-snapshot PURLs

cc @kltm

**Comment by pgaudet** [comment]
Done in new website

**Comment by pgaudet** [comment]
Done on GH pages and in Drupal.
