### ISSUE TITLE
parentage problem for "conversion of ds siRNA to ss siRNA"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14263]
This term has parentage to some "response to " terms that it shouldn't have.

I think this is due to  the parentage of "dsRNA fragmentation" and hence "cellular response to ds RNA"

"conversion of ds siRNA to ss siRNA"
can be used to  describe RNAi type processes which are regulating  gene expression, rather than the processing of exogenous dsRNA (which seems to be what this term might be appropriate for?)

The term  "conversion of ds siRNA to ss siRNA"   ends up with "response to organic cyclic compound" and "response to nitrogen" but it isn't any of these things?

**Comment by ValWood** [comment]
see

![problems](https://user-images.githubusercontent.com/7359272/30833621-b0a39f98-a247-11e7-88f6-f34965b4adba.jpg)

**Comment by rachhuntley** [comment]
I find the term name and definition a bit vague as well. It's not clear what the "conversion" involves.

Current: "The process in which double-stranded small interfering RNA (ds siRNA) molecules are converted to single-stranded small interfering RNA (ss siRNA). "

As the process actually involves cleavage, shouldn't the definition be based around the parent definition (dsRNA fragmentation)?

Proposed: "The process in which double-stranded small interfering RNA (ds siRNA) molecules are cleaved by an RNaseIII-family enzyme to produce single-stranded small interfering RNA (ss siRNA)." 

And the term name could be "Cleavage of ds siRNA to ss siRNA"? If appropriate, we would also need to update the other terms that include conversion of ds siRNA to ss siRNA.

**Comment by ValWood** [comment]
I think there are a lot of unnecessary terms!

A lot of terms look like activities?
"conversion of ds siRNA to ss siRNA" involved_in ..... 


I don't think "cleavage" should be described as "fragmentation"? fragmentation implies "uncontrolled breakage". It should be "processing" (which is also present). The "fragmentation" parentage seems superfluous?

**Comment by ValWood** [comment]
Has always been a bit of a mess under gene silencing.....

**Comment by rachhuntley** [comment]
Yes, that's true. Fragmentation is the wrong word, all of the child terms involve cleavage, and dsRNA cleavage is a function. All of the child terms of dsRNA fragmentation should be described as "production of small RNA" 

Would this work?
"dsRNA fragmentation" change to "production of small RNA"
--> production of ss siRNA (formerly "conversion of ds siRNA to ss siRNA")
--> production of small RNA involved in gene silencing by RNA
--> production of scnRNA 

This is obviously not complete, just deals with the existing direct terms under the fragmentation term, but these are hardly used in comparison with the deeper terms under gene silencing.

**Comment by rachhuntley** [comment]
We haven't even reached gene silencing yet!

**Comment by ValWood** [comment]
I can't even annotate our gene silencing by RNA silencing papers I'm so confused by this part of the ontology (pombe use the RNAi machinery but are not RNAi in the GO sense, although I now see these terms are under RNAi, which cause TPVs).

This might be a miniproject.....

**Comment by mah11** [comment]
re

> As the process actually involves cleavage ...

and

> And the term name could be "Cleavage of ds siRNA to ss siRNA"?

If the RNA is changing from double- to single-stranded, then the conversion process must include unwinding, at least in addition to any nuclease activity, perhaps instead of. I don't know this area well, but from a quick look at the paper cited for the def (PMID:17310250) and a couple of reviews, it's clear that a large dsRNA molecule is cleaved into smaller, but still double-stranded, RNAs, before the small ds RNAs are unwound. I can't easily tell whether the RNAs undergo any further endo- or exonucleolytic cleavage upon being unwound.

I'm therefore worried that renaming GO:0033168 to "cleavage ..." would obscure the more important part of the ds-to-ss conversion process. "dnRNA fragmentation" seems like a better candidate to change to a "cleavage" term.

For the same reason, the link GO:0036404 ! conversion of ds siRNA to ss siRNA part_of GO:0031050 dsRNA fragmentation looks a little odd, and I won't argue to keep it.

**Comment by mah11** [comment]
> Would this work?
> "dsRNA fragmentation" change to "production of small RNA"
> --> production of ss siRNA (formerly "conversion of ds siRNA to ss siRNA")
> --> production of small RNA involved in gene silencing by RNA
> --> production of scnRNA

I don't know enough to have biology-based reasons to oppose renaming various terms to "production", but GO has historically used "production" a bit differently, as exemplified by the "cytokine production" (GO:0001816) branch. My limited understanding is that it follows a usage common among immunologists. 

The suggestions also seem somehow less specific than the various current names - "conversion of ds siRNA to ss siRNA" isn't pretty but it does say what happens as a result of the process, albeit not how. (I'm aware that I'm ignoring the question of which of the terms in this branch really represent multi-activity processes, but I really _really_ don't know enough to comment on that!)

**Comment by rachhuntley** [comment]
Regarding production, there are already terms such as "production of small RNA involved in gene silencing by RNA" and "production of miRNAs involved in gene silencing by miRNA", which are under the dsRNA fragmentation term, so I suggested a name to be consistent with this.

You can ignore my first comments on cleavage as my second comment suggests the alternative "production" name instead of cleavage.

**Comment by ValWood** [comment]
Yeah probably need to identify the steps involved in the "conversion". I had a quick look earlier and I couldn't work it out immediately based on out annotations.
Can have a closer look after the meeting.

**Comment by ukemi** [comment]
I'm wondering if the original dsRNA terms were created to deal with response to dsRNA viruses and not really related to RNAi at all.

**Comment by ValWood** [comment]
Yes I was thinking that.
Although the RNAi machinery does deal with these in some species. but not all siRNA formation is involved in this process, its only one pathway. It's a big mix up....

**Comment by ukemi** [comment]
So I think the key to the issue in this ticket is the links to to dsRNA fragmentation. I suspect this term was meant to be a response to dsRNA but not to represent anything to to with siRNA. However, it looks like the two might in fact be related. PMID:17698400

**Comment by rachhuntley** [comment]
So there are other terms related to silencing viral genes under GO:0009616 virus induced gene silencing (which is under multi-organism process).

If we are keeping the dsRNA fragmentation term, we could put a comment on that it should only be used for describing processing of endogenous dsRNA, even though the same machinery is used for processing foreign dsRNA.

**Comment by pgaudet** [comment]
Hello, 

What's the action here ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Looks like 'dsRNA fragmentation' shouldn't have parent 'part of' some 'cellular response to dsRNA'

Can I just remove that ? 

Pascale

**Comment by ValWood** [comment]
Yes that would help.
At the same time maybe you could change the name of 
'cellular response to dsRNA' to 'cellular response to exogenous dsRNA'
this would alleviate the reported issue.

One day, the entire branch of chromatin remodelling and RNAi needs a thorough and comprehensive review. Not yet though. .....

**Comment by pgaudet** [comment]
Changed a number of labels to improve consistency: 

 id: GO:0031051 scnRNA production
NEW name: scnRNA processing

 id: GO:0031050  dsRNA fragmentation
NEW name: dsRNA processing (+ removed parent  'cellular response to dsRNA') 

GO:0031051 scnRNA production
NEW name: scnRNA processing

GO:0031050 dsRNA fragmentation
NEW name: dsRNA processing

Pascale
