### ISSUE TITLE
term merge sodium ion export from cell?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14265]
is there a difference between this and  (only) child
GO:0098667    sodium ion export across plasma membrane
?

**Comment by pgaudet** [comment]
I had done that for import, I am not sure I checked export. 

Thanks for pointing it out,

Pascale

**Comment by ukemi** [comment]
If we only think it ever happens by movement across the membrane and never by another mechanism such as exocytosis. I did a quick search and couldn't find evidence to the contrary.

**Comment by ValWood** [comment]
The parent of the current export term is transmembrane transport.

**Comment by ukemi** [comment]
Then I think it makes sense to merge as long as the parent wasn't added incorrectly. Have you done a sanity check on the existing annotations? Are they all transporters/channels?

**Comment by ValWood** [comment]
I think we  established this when Pascale did the import terms. Only known 'directed movement' is transmembrane.

**Comment by pgaudet** [comment]
- Also merged 'potassium ion export from cell' (no annotations) into 'potassium ion export across plasma membrane'
