### ISSUE TITLE
Obsolete GO:0100019 regulation of cAMP-mediated signaling by transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14279]
cAMP mediated signalling
has only 2 children

adenylate cyclase-activating G-protein coupled receptor signaling pathway

and
GO:0100019 
regulation of cAMP-mediated signaling by transcription from RNA polymerase II promoter
Any transcription from RNA polymerase II promoter process that regulates cAMP-mediated signaling

GO:0100019  should be obsoleted:
Its about transcription regulating cAMP.
Does this even occur? It has no annotations.

Matrix isn't very useful here because 
adenylate cyclase-activating G-protein coupled receptor signaling pathway
is an exact subset of
regulation of cAMP-mediated signaling by transcription from RNA polymerase II promoter

![parent](https://user-images.githubusercontent.com/7359272/31055204-ab3c6110-a6b7-11e7-9aee-d2c6c69e5c3b.jpg)

but most annotations to cAMP mediated signalling are also to
adenylate cyclase-activating G-protein coupled receptor signaling pathway
1013/1293

**Comment by ukemi** [comment]
PMID:15448137

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/curs/65ee22c229c3e125/ro

has


atf1 | GO:0110034 | negative regulation of adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway | IMP | part_of positive regulation of mitotic G1 cell cycle arrest in respo  ..
pcr1 | GO:0110034 | negative regulation of adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway | IMP | part_of positive regulation of mitotic G1 cell cycle arrest in respo  .
cgs2 | GO:0110034 | negative regulation of adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway | IMP | part_of positive regulation of mitotic G1 cell cycle arrest in respo  ...

I think Spc1 is not annotated though because the integration occurs at the  transcription factor (which is downstream of the MAPK pathway we decided on sunday).

I should see what this looks like  but cgs2 is *transcriptionally regulated* by the MAPK pathway, so  I  think we would link these by causally uptream?

**Comment by ukemi** [comment]
I think this last comment is an annotation issue. The PMID above was noted because it is the source of this ontology term. Please look at the paper and decide if this paper supports the existence of this term. If there are annotation issues, please open a ticket on the annotation tracker.

**Comment by ValWood** [comment]
we no longer use  GO:0100019

**Comment by pgaudet** [comment]
GO:0100019 has no EXP annotations, only IEAs. I will send the obsoletion notice.

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete 'GO:0100019
regulation of cAMP-mediated signaling by transcription from RNA polymerase II promoter’

The reason for obsoletion is that 'cAMP-mediated signaling’ is not mediated by transcription from RNA polII promoter. Consistent with this, there are no annotations to the term. Please add any comments to the issue: https://github.com/geneontology/go-ontology/issues/14279

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Nov 7, 2017. Unless objections are received by Nov 7,2017, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Must also obsolete child 
GO:1900391 regulation of cAMP-mediated signaling by regulation of transcription from RNA polymerase II promoter
