### ISSUE TITLE
Create yaml metadata for subsets

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14276]
Spinning out a distinct ticket for @dosumis' idea in #13615 

For background see slides:
https://docs.google.com/presentation/d/1NdOSZa3Y1h229dvX20pkGlbEnjAeVPmeo5NVZcyd10s/edit?usp=sharing

**Comment by pgaudet** [comment]
STATUS: 
I created all the yaml files. I contacted several groups to find out what the status of their slim was: 


Subset | Number of terms | Contact | contacted? | Active / obsolete/ pending contact | Comment
-- | -- | -- | -- | -- | --
goantislim_grouping.yaml |   | go-ontology? |   |   |  
goslim_agr.yaml |   | go-ontology? |   | active |  
goslim_aspergillus.yaml |   | Marek Skrzypek | yes |   |  
goslim_candida.yaml |   | Marek Skrzypek | yes |   |  
goslim_chembl.yaml |   | ? |   |   |  
goslim_generic.yaml |   | go-ontology? |   |   |  
goslim_goa.yaml | 0 | tony/george | yes | obsolete | OK to delete
goslim_metagenomics.yaml |   |   |   |   |  
goslim_mouse.yaml |   | Mary Dolan | yes |   |  
goslim_pir.yaml |   | Darren Natale and Ceci Arighi | yes |   |  
goslim_plant.yaml | 89 | Tanya, Pankaj | yes |   |  
goslim_pombe.yaml |   |   |   | active |  
goslim_synapse.yaml |   |   |   | active |  
goslim_virus.yaml |   | ? |   |   |  
goslim_yeast.yaml |   | Stacia, Suzi | yes |   |  
gosubset_prok.yaml |   | go-ontology? |   | obsolete |  
mf_needs_review.yaml |   | Harold ?? |   |   | enzymes; some have the comment "This term represents a deleted EC   activity and is scheduled for obsoletion."
termgenie_unvetted.yaml |   | ? |   |   | all terms in the subset are obsolete - delete ?
virus_checked.yaml |   | go-ontology? |   |   |

**Comment by pgaudet** [comment]
Created the two yaml files for do_not_annotate and do_not_manually_annotate

PR: https://github.com/geneontology/go-ontology/pull/16082
