### ISSUE TITLE
Function involved in process to OBSOLETE (all zero annotations)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14278]
MAP kinase kinase activity involved in conjugation with cellular fusion
http://amigo.geneontology.org/amigo/term/GO:0038072
IEA ONLY 

MAPK activity involved in conjugation with cellular fusion (6) SGD 
http://amigo.geneontology.org/amigo/term/GO:0038071

MAP kinase kinase kinase activity involved in conjugation with cellular fusion (0)
http://amigo.geneontology.org/amigo/term/GO:0038073
IEA only

**Comment by pgaudet** [comment]
related to https://github.com/geneontology/go-ontology/issues/14138

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete: 

MAP kinase kinase activity involved in conjugation with cellular fusion
http://amigo.geneontology.org/amigo/term/GO:0038072
No annotations

MAPK activity involved in conjugation with cellular fusion 
http://amigo.geneontology.org/amigo/term/GO:0038071
6 EXP SGD

MAP kinase kinase kinase activity involved in conjugation with cellular fusion 
http://amigo.geneontology.org/amigo/term/GO:0038073
IEA only AspGD+cGD (‘parent’ annotation from pombase has been deleted)

There are no InterPro2GO mappings to this term. 

The reason for obsoletion is that this represents a Noctua model. 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/14278. We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Oct  7, 2017. Unless objections are received by Oct  7, 2017 , we will assume that you agree to this change.

**Comment by ValWood** [comment]
GO:0038074    MAP kinase phosphatase activity involved in regulation of conjugation with cellular fusion
zero

GO:0038077    MAP kinase kinase kinase activity involved in innate immune response
zero

GO:0038076    MAP kinase kinase activity involved in innate immune response
zero

O:0038079    MAP kinase activity involved in osmosensory signaling pathway
zero

**Comment by ValWood** [comment]
GO:0099582    neurotransmitter receptor activity involved in regulation of presynaptic cytosolic calcium ion concentration
zero

GO:0099626    voltage-gated calcium channel activity involved in regulation of presynaptic cytosolic calcium levels
zero

GO:1903264    nitrate reductase activity involved in anaerobic electron transport chain
zero


GO:0038067    MAP kinase activity involved in cell wall organization or biogenesis |  
zero

GO:0038080    MAP kinase kinase activity involved in osmosensory signaling pathway 
zero
 
GO:0038081    MAP kinase kinase kinase activity involved in osmosensory signaling pathway 
zero

 
GO:0098663    transmembrane transporter activity involved in import into cell
zero

**Comment by ValWood** [comment]
zero:
GO:0039632    RNA translocase activity involved in viral RNA genome packaging |  
GO:0039631    DNA translocase activity involved in viral DNA genome packaging
GO:1902945    metalloendopeptidase activity involved in amyloid precursor protein catabolic process
GO:0038070    MAP kinase kinase kinase activity involved in cell wall organization or biogenesis |  
GO:0038069    MAP kinase phosphatase activity involved in regulation of cell wall biogenesis |  GO:0038068    MAP kinase kinase activity involved in cell wall organization or biogenesis |  
GO:0038082    MAP kinase phosphatase activity involved in regulation of osmosensory signaling pathway


GO:0098697    ryanodine-sensitive calcium-release channel activity involved in regulation of postsynaptic cytosolic calcium levels
GO:1905057    voltage-gated calcium channel activity involved in regulation of postsynaptic cytosolic calcium levels 
GO:1905056    calcium-transporting ATPase activity involved in regulation of presynaptic cytosolic calcium ion concentration |  
GO:1905059    calcium-transporting ATPase activity involved in regulation of postsynaptic cytosolic calcium ion concentration

GO:0099507    ligand-gated ion channel activity involved in regulation of presynaptic membrane potential |  
-- | --
GO:0099508    voltage-gated ion channel activity involved in regulation of presynaptic membrane potential
GO:0099581    ATPase coupled ion transmembrane transporter activity involved in regulation of postsynaptic membrane potential
GO:0099579    G-protein coupled neurotransmitter receptor activity involved in regulation of postsynaptic membrane potential
GO:0099102    G-protein gated potassium channel activity involved in regulation of postsynaptic membrane potential 
GO:0099107    ion channel regulator activity involved in G-protein coupled receptor signaling pathway 
GO:0099108    potassium channel activator activity involved in G-protein coupled receptor signaling pathway 
GO:0097364    stretch-activated, cation-selective, calcium channel activity involved in regulation of action potential  
GO:0097365    stretch-activated, cation-selective, calcium channel activity involved in regulation of cardiac muscle cell action potential
GO:0086086    voltage-gated potassium channel activity involved in AV node cell action potential repolarization
GO:0086058    voltage-gated calcium channel activity involved in Purkinje myocyte cell action potential
GO:0086088    voltage-gated potassium channel activity involved in Purkinje myocyte action potential repolarization

**Comment by ValWood** [comment]
For the time being I ignored binding involved in
and those in the transcription branch, these are probably a separate issue.

After these are gone I'll look at those with low numbers of annotations.

**Comment by RLovering** [comment]
Please note the term:
GO:0015563 uptake transmembrane transporter activity
Definition: Enables the transfer of a specific substance or related group of substances from the outside of a cell to the inside across a membrane.
seems to be equivalent to:
GO:0098663 transmembrane transporter activity involved in import into cell
But GO:0015563 does not have the parent term: GO:0098657 import into cell
It looks to me like it should. And then the phrase 'transmembrane transporter activity involved in import into cell' should be added as a synonym to GO:0015563 uptake transmembrane transporter activity

Ruth

**Comment by dosumis** [comment]
> GO:0099582    neurotransmitter receptor activity involved in regulation of presynaptic cytosolic calcium ion concentration
zero

> GO:0099626 voltage-gated calcium channel activity involved in regulation of presynaptic cytosolic calcium levels
zero

Please don't obsolete these.  The first one is a fundamental step in synaptic transmission and so I think deserves to be a named term.  The second one was requested with specific cases in mind.  These terms  are part of the SynGO slim. The absence of annotations is more a matter of whether the syngo curators and experts have got around to annotating these yet.    There are lots more terms in this slim following the involved_in pattern.  I think you should be conservative in obsoleting as this will cause needless churn in a curation project that is now making good progress.

**Comment by pgaudet** [comment]
Dear all, 

Since the issue has been created many "xx involved in yy” terms have been added. I will obsolete all terms in which MAP kinases are involved in a specific process, since this is not possibly sustaininable in GO. I will make separate issues for other types of terms. 





GO:0038074 MAP kinase phosphatase activity involved in regulation of conjugation with cellular fusion
GO:0038077 MAP kinase kinase kinase activity involved in innate immune response
GO:0038076 MAP kinase kinase activity involved in innate immune response
GO:0038079 MAP kinase activity involved in osmosensory signaling pathway
GO:0038067 MAP kinase activity involved in cell wall organization or biogenesis |
GO:0038080 MAP kinase kinase activity involved in osmosensory signaling pathway
GO:0038081 MAP kinase kinase kinase activity involved in osmosensory signaling pathway
GO:0038070 MAP kinase kinase kinase activity involved in cell wall organization or biogenesis |
GO:0038069 MAP kinase phosphatase activity involved in regulation of cell wall biogenesis |
GO:0038068 MAP kinase kinase activity involved in cell wall organization or biogenesis |
GO:0038082 MAP kinase phosphatase activity involved in regulation of osmosensory signaling pathway
GO:0038072: MAP kinase kinase activity involved in conjugation with cellular fusion
GO:0038071 MAPK activity involved in conjugation with cellular fusion - 6 EXP SGD
---
Pascale
