### ISSUE TITLE
Add a relation between MAPK scaffold activity and MAPK cascade

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#14286]
Create a positively regulates link between MAPK scaffold activity and the MAPK cascade.

**Comment by ValWood** [comment]
The SGD MAPK scaffold 
https://www.yeastgenome.org/locus/YDL073W#go
Is annotated as a negative regulator of MAPK?

Need to check that the scaffold can always be classed as a positive regulator...

**Comment by ValWood** [comment]
Perhaps that isn't really a MAPK scaffold?  @srengel 
This one clearly is:
MAPK http://pfam.xfam.org/family/PF11610
This family of proteins represents the Fus3 binding region of Ste5. Ste5 functions in the yeast mating pathway and is required for signalling through the mating response MAPK pathway. Ste5 has separate binding sites for each member of the MAPK cascade. This region of Ste5 allosterically activates autophosphroylation of Fus3, a mitogen-activated protein kinase. Auto-activated Fus3 has a negative regulatory role, and promotes Ste5 phosphorylation which leads to a decrease in pathway transcriptional output [1].

Perhaps MAPK scaffold needs a better definition that mentions that it provides a binding site for the for each member of the MAPK signalling modul?

**Comment by ukemi** [comment]
Actually I think the same molecule can bind the three members of the cascade and activate them, but the same molecule can act in a different way as a negative regulator. I found an example of this too, but I would not consider the latter MAPK scaffold activity. If you think they are both scaffold activity, I will remove the link to positive regulation.

**Comment by pgaudet** [comment]
Discussion with @hattrill and @gantonazzo 

The MAPK scaffold is part of the MAPK cascade, not regulating it. 

Changed parent to 'part of' some 'MAPK cascade'

**Comment by ValWood** [comment]
Agreed!
That will get rid of F-P inferences like
GO:0043410 | positive regulation of MAPK cascade | ISO with S000002231
