### ISSUE TITLE
articular cartilage development

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#14284]
I would like to see “articular cartilage development” added as a child term of “cartilage development” (GO:0051216). Definition could be “The process whose specific outcome is the progression of articular cartilage over time, from its formation to the mature structure. Synonyms: “articular cartilage of joint development”.  PMID: 20679519, 20097540
I would like to see “temporomandibular joint articular cartilage development” and “hip joint articular cartilage” added as child terms of “articular cartilage development” (new term). Definition(s) could be “The process whose specific outcome is the progression of temporomandibular joint (hip joint) articular cartilage over time, from its formation to the mature structure. PMIDs:20679519, 20097540
I would like to see “mandibular condyle articular cartilage development” and “femoral head articular cartilage” added as child terms of “temporomandibular joint articular cartilage development” (new term) and “hip joint articular cartilage” (new term), respectively. Definition(s) could be “The process whose specific outcome is the progression of mandibular joint condyle articular cartilage (femoral head articular cartilage) over time, from its formation to the mature structure. PMIDs:20679519, 20097540

**Comment by slaulederkind** [comment]
Typo corrections in sections 2 & 3:
I would like to see “temporomandibular joint articular cartilage development” and “hip joint articular cartilage development” added as child terms of “articular cartilage development” (new term). Definition(s) could be “The process whose specific outcome is the progression of temporomandibular joint (hip joint) articular cartilage over time, from its formation to the mature structure. PMIDs:20679519, 20097540
I would like to see “mandibular condyle articular cartilage development” and “femoral head articular cartilage development” added as child terms of “temporomandibular joint articular cartilage development” (new term) and “hip joint articular cartilage development” (new term), respectively. Definition(s) could be “The process whose specific outcome is the progression of mandibular joint condyle articular cartilage (femoral head articular cartilage) over time, from its formation to the mature structure. PMIDs:20679519, 20097540

**Comment by ukemi** [comment]
Hi @slauderkind,

Can you please check UBERON and align or request missing terms to be sure that we can refer to them in logical definitions?
https://github.com/obophenotype/uberon/issues
Once we have all the correct terms available, we can create the development terms in GO.

**Comment by slaulederkind** [comment]
A few new UBERON terms have been requested (https://github.com/obophenotype/uberon/issues/1371).  Also for the requested BP terms, it might help to add one more:
Add "hyaline cartilage development" as child of “cartilage development” (GO:0051216) and parent of “articular cartilage development" (new term). Definition: Translucent bluish white cartilage consisting of cells embedded in an apparently homogeneous matrix, present in joints and respiratory passages, and forming most of the fetal skeleton. (Merriam-Webster) PMID:7591987 

“cartilage development” (GO:0051216) - "hyaline cartilage development" (new term) - “articular cartilage development" (new term) -“temporomandibular joint articular cartilage development” (new term) - “mandibular condyle articular cartilage development” (new term)

“cartilage development” (GO:0051216) -"hyaline cartilage development" (new term) - “articular cartilage development" (new term) - "synovial joint of pelvic girdle development" (new term) - “hip joint articular cartilage development” (new term) - “femoral head articular cartilage development” (new term)

**Comment by ukemi** [comment]
Hi @slauderkind,

The terms will be defined and placed in the ontology based on their definitions and placement in UBERON. Can you add a link to the UBERON term requests, so I can easily see when they are available?

-D

**Comment by ukemi** [comment]
Never mind, I see the link above. Sorry.
