### ISSUE TITLE
make ro import broken

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#14288]
```sh
$ make imports/ro_import.owl
ls: subsets/*.owl: No such file or directory
owltools http://purl.obolibrary.org/obo/ro.owl --merge-imports-closure -o mirror/ro-download.owl
robot query -i go-edit.obo --construct ../sparql/constructDisjointInTaxon.sparql disjoint_in_taxon.owl -f ttl
make: robot: No such file or directory
make: *** [disjoint_in_taxon.owl] Error 1
```

**Comment by dosumis** [comment]
I found a workaround for this before by running a few of the prior make steps manually but no-longer have a record of how I did this (lost in a data transfer screw-up last week).

**Comment by cmungall** [comment]
I think a workaround is to `touch subsets/foo.owl`, but am trying to figure out why this is necessary, some odd circularity in make dependencies

**Comment by cmungall** [comment]
scratch that, this part is annoying but actually harmless:

```
ls: subsets/*.owl: No such file or directory
```

**Comment by cmungall** [comment]
It's in this line:

```
robot query -i go-edit.obo --construct ../sparql/constructDisjointInTaxon.sparql disjoint_in_taxon.owl -f ttl
```

What is the output of
`which robot`?

**Comment by cmungall** [comment]
Yep, I'm pretty sure you just need to install robot.

fastest way may be to:

```
wget http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot -O bin/robot
wget http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar -O bin/robot.jar
```

**Comment by dosumis** [comment]
It's not robot that's missing.  It's  disjoint_in_taxon.owl.

**Comment by cmungall** [comment]
the second argument in `--construct` is the name of the file to be generated from the construct, so you expect disjoint_in_taxon.owl to be there after.

```
make: robot: No such file or directory
make: *** [disjoint_in_taxon.owl] Error 1
```

this is consistent with robot not being on your path. There could be something weird where the path in make is different...?

**Comment by dosumis** [comment]
robot installed fine and being used in other make jobs (I used it just prior to this for an ro release).

**Comment by dosumis** [comment]
Could it be that the GO Makefile is screwing with robot path assignment?

**Comment by cmungall** [comment]
The Makefile doesn't mess with the path, but it's possible somehow your environment isn't inherited

for sanity can you try directly typing

```
robot query -i go-edit.obo --construct ../sparql/constructDisjointInTaxon.sparql disjoint_in_taxon.owl -f ttl
```

and 

```
which robot
```

**Comment by dosumis** [comment]
which robot is blank, but the robot command works from the command line (I use it all the time).

Just checked and this works fine:
 robot query -i go-edit.obo --construct ../sparql/constructDisjointInTaxon.sparql disjoint_in_taxon.owl -f ttl

 robot query -i go-edit.obo --construct ../sparql/constructDisjointInTaxon.sparql disjoint_in_taxon.owl -f ttl

$PATH has
~/sync/bin/
$ ls ~/sync/bin/robot
/Users/davidos/sync/bin/robot

Maybe its the ~/ in the path that's causing the problem?

**Comment by dosumis** [comment]
Changed path to be absolute.  Job now gets further but snags on:

ROBOT_JAVA_ARGS=-Xmx8G robot extract -i mirror/ro.owl -T imports/ro_terms_combined.txt --method BOT -O http://purl.obolibrary.org/obo/go/imports/ro_import.owl annotate -V http://purl.obolibrary.org/obo/go/releases/`date +%Y-%m-%d`/imports/ro_import.owl -o imports/ro_import.owl
/bin/sh: robot: command not found
make: *** [imports/ro_import.owl] Error 127

**Comment by cmungall** [comment]
weird...

@kltm thinks it's something to do with the `robot` script

it has:

`DIR="$( cd "$( dirname "$0" )" && pwd )"`

For me the value of this is 

`/Users/cjm/repos/robot/bin`

Which is where both the shell script and `robot.jar` lives

I'm not so sure it's to do with the wrapper, seems to be failing before.

the idiom

`ENVVAR=VAL command`

may be shell dependent.

Can you try 

```
ROBOT_JAVA_ARGS=-Xmx8G robot extract -i mirror/ro.owl -T imports/ro_terms_combined.txt --method BOT -O http://purl.obolibrary.org/obo/go/imports/ro_import.owl annotate -V http://purl.obolibrary.org/obo/go/releases/`date +%Y-%m-%d`/imports/ro_import.owl -o imports/ro_import.owl
```

directly without running make?

or just

`WIBBLE=hi echo test`

**Comment by cmungall** [comment]
any luck?

**Comment by dosumis** [comment]
Yep. Seemed to fix itself after I ran into time outside of make.  Want to
test with a fresh clone before closing ticket though.

**Comment by pgaudet** [comment]
@balhoff Do you know if this is fixed?
