### ISSUE TITLE
NTR: urease activator complex & parent

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14287]
- Term 1:
Name: enzyme activator complex
Def: A protein complex capable of activating an enzyme. Activating subunits may dissociate from the catalytic unit before the enzyme is active.

References:
GOC:bhm
IntAct: EBI-16417801
PMID:16244137, 28710280

Relationships:
is_a GO:0032991 macromolecular complex
capable_of GO:0008047 enzyme activator activity
capable_of_part_of GO:0044237 cellular metabolic process

NB: There are lots of term that have "activator [some complex]" in the term name. Will these get pulled in? 

- Term 2: 
Name: urease activator complex
Def: A protein complex required for the activation of urease. Activator subunits dissociate before urease has catalytic function.

References:
GOC:bhm
IntAct: EBI-16417801
PMID:16244137, 28710280

Relationships:
is_a GO:NEW enzyme activator complex [Term 1]
capable_of GO:0018237 urease activator activity
capable_of_part_of GO:0043419 urea catabolic process

Thanks,
Birgit

**Comment by ukemi** [comment]
Hi @bmeldal 

If the existing terms have logical defs, they should get automatically classified. It looks like most if not all of them have logical defs.

-D

**Comment by ukemi** [comment]
PS. They will only get pulled in if the 'something in  [something] activator complex is an enzyme.

**Comment by bmeldal** [comment]
Fixed the DBxrefs. Do you need anything else from me?

**Comment by ukemi** [comment]
Nope. We will do this ticket tomorrow with Barbara.

**Comment by bmeldal** [comment]
This complex is going out with the next CP release planned for next week. Do you think we'll have a term ID by then @ukemi @BarbaraCzub? I've got the entry on hold at the moment but can release without link if necessary.

**Comment by BarbaraCzub** [comment]
Hi @bmeldal , I am so sorry about this delay, I was on holiday. I have the next editing training session scheduled with @ukemi on Wednesday next week (1st November) and I will set a reminder about this ticket for then. As far as I know there is no term ID (unless David worked on this by himself).

**Comment by bmeldal** [comment]
No worries, I chased it as @ukemi posted you'd be looking at it as part of your training in London after the GOC mtg. I'll release the complex and add the annotation once the ID is there.

**Comment by BarbaraCzub** [comment]
Hi @bmeldal 

@ukemi has just helped me create these new term.

We've done everything as you requested, except that we did not add the: 
'capable_of_part_of GO:0044237 cellular metabolic process'
because not all enzyme activator complexes will be capable of part of cellular metabolic process. E.g. the 'GTPase activator complex', a child inferred from the logical definition, is not capable of part of cellular metabolic process. (ATPase, or GTPase, activity is not a part of cellular metabolic process).
