### ISSUE TITLE
go-plus asserts 'part of' to be a functional property

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#14294]
Version http://purl.obolibrary.org/obo/go/releases/2017-10-04/extensions/go-plus.owl has 'part of' marked as `Functional`. As you might expect this is having terrible reasoning effects in Noctua.

**Comment by balhoff** [comment]
Crept in here: 4131ff90cfd6ebacb1b1005c40711da515c70529

**Comment by ukemi** [comment]
Not sure how this happened. @pgaudet? @cmungall?

**Comment by ukemi** [comment]
Looks like it is an issue with RO or BFO.

**Comment by balhoff** [comment]
It was added to go-edit.obo in 4131ff90cfd6ebacb1b1005c40711da515c70529. I'm guessing it was an inadvertent click in Protégé. I opened a PR: #14295.

**Comment by pgaudet** [comment]
Hi @ukemi 
I dont know how this happened. I have been committing only go-edit.obo, so it's a little odd. Thanks @cmungall for the additional check ! 

Pascale
