### ISSUE TITLE
EC xrefs associated with GO:0016791 (phosphatase activity)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#14306]
This term is currently associated with 2 EC xrefs:
EC:3.1.3.- (= "Hydrolases -> Acting on ester bonds -> Phosphoric monoester hydrolases")
EC:3.1.3.41 (= "4-nitrophenylphosphatase")

The second xref seems too specific, though I'm certainly no expert...can someone knowledgeable check whether this is really appropriate?

(26 D. melanogaster genes are annotated with EC:3.1.3.41 in GenBank/NCBI etc as a result of this association in GO, while only 3 entries within the whole of SwissProt have this EC number....)

**Comment by hattrill** [comment]
Tagging myself @hattrill

**Comment by hdrabkin** [comment]
3.1.3.41 is not appropriate for such a general term and I will remove. 
I'm trying to do a quick and dirty search about whether 4-nitrophenylphosphate is a natural substrate, OR if this is a 'pseudo substrate' used in assays for phosphatases in general 
(https://en.wikipedia.org/wiki/Para-Nitrophenylphosphate).  Also trying to get PMID:18198990

**Comment by sjm41** [comment]
Thanks Harold.
Have you removed 3.1.3.41 both as an xref and from the definition?
Looks like the Rhea and MetaCyc xrefs may also need to be revised.

**Comment by hdrabkin** [comment]
Not yet, because of all of the synonyms that refer to 3.1.3.41. It also appears there are gene names that reference 3.1.3.41 as a name.  I have a feeling that one or both of the two secondary ids
GO:0003869, and GO:0016302, MIGHT have used 3.1.3.41 and perhaps it's activity name. It may have been merged because someone mad the term using the substrate that was being used to assay the enzyme (4-nitrophenylphosphate). What worries me is that EC actually has an entry for that activity (can any phosphatase use 4-nitrophenylphosphate? I'm not sure). I need more info before I proceed.
@deustp01 do you have any idea? 
Can anyone get me the pdf for PMID:18198990; the site keeps timing out (it's suppose to be free).

**Comment by sjm41** [comment]
Hi @hdrabkin.  I just stumbled across this issue (last updated Oct 2017!) again.
Still seems to be several problems here.

1. GO:0016791 (phosphatase activity) appears to have many inappropriate synonyms linked to EC:3.1.3.41 (probably based on previous merge) - those should be removed.

2. The Rhea and MetaCyc (and maybe Reactome?) xrefs on GO:0016791 (phosphatase activity) are still for the more specific EC:3.1.3.41, so I think should be removed.

3. I see several other specific GO terms currently have the partial EC xref of 3.1.3 (listed below) - these should be removed, or changed where possible (I found 2 cases where the correct Rhea/EC xrefs exist)

id: GO:0008330
name: protein tyrosine/threonine phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0017161
name: inositol-1,3,4-trisphosphate 4-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0019198
name: transmembrane receptor protein phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0030351
name: inositol-1,3,4,5,6-pentakisphosphate 3-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0030352
name: inositol-1,4,5,6-tetrakisphosphate 6-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0043726
name: 5-amino-6-(5-phosphoribitylamino)uracil phosphatase activity
xref: EC:3.1.3
=> change to 3.1.3.104
=> add RHEA:25197

id: GO:0043812
name: phosphatidylinositol-4-phosphate phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0043813
name: phosphatidylinositol-3,5-bisphosphate 5-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0052629
name: phosphatidylinositol-3,5-bisphosphate 3-phosphatase activity
xref: EC:3.1.3
=> change to 3.1.3.95
RHEA:39019

id: GO:0052825
name: inositol-1,3,4,5,6-pentakisphosphate 1-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0052829
name: inositol-1,3,4-trisphosphate 1-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0052830
name: inositol-1,3,4,6-tetrakisphosphate 6-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0052831
name: inositol-1,3,4,6-tetrakisphosphate 1-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:0052867
name: phosphatidylinositol-1,4,5-trisphosphate 5-phosphatase activity
xref: EC:3.1.3
=> remove

id: GO:1990003
name: IDP phosphatase activity
xref: EC:3.1.3
=> remove


tagging @phanivg

**Comment by sjm41** [comment]
P.S. I have the pdf of PMID:18198990, so let me know if you still can't access that!

**Comment by hdrabkin** [comment]
I'll have time to deal with the 3 digit ones today; don't know how this slipped through.

**Comment by hdrabkin** [comment]
Note: we are preparing for bulk upload of RHEA predicted assignments to GO terms

**Comment by sjm41** [comment]
_we are preparing for bulk upload of RHEA predicted assignments to GO terms_

That would be nice! Will that include updates/checks to the EC xrefs too?

**Comment by hdrabkin** [comment]
We are hoping that EC assignments will be automatic through RHEA; 
Removing these 3 digit ecs leave some term with no xrefs, but we hope that will be supplied by the upload.

**Comment by hdrabkin** [comment]
Done all and closing

**Comment by sjm41** [comment]
Great, thanks!
Can I just check you also saw these two points above the list of 3-digit ECs to fix:

_1. GO:0016791 (phosphatase activity) appears to have many inappropriate synonyms linked to EC:3.1.3.41 (probably based on previous merge) - those should be removed._

_2. The Rhea and MetaCyc (and maybe Reactome?) xrefs on GO:0016791 (phosphatase activity) are still for the more specific EC:3.1.3.41, so I think should be removed._

**Comment by hdrabkin** [comment]
yes those are in also. waiting to clear travis; now at GO meeting
This set will be interesting to see how much gets filled in by RHEA upload.

**Comment by sjm41** [comment]
Great, thanks again!

_This set will be interesting to see how much gets filled in by RHEA upload._
As far as I could see (by searching directly on the Rhea website), only two of the GO terms I listed (with the 3-digit ECs) are currently present in their db....
