### ISSUE TITLE
Imports still have relationships

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#14300]
Today during @BarbaraCzub 's training we tried out the new obsoletion plug-in. The plug in seemed to work fine, but the Travis checks failed sue to an asserted is_a relation between the obsoleted term and signaling in the CHEBI import. I thought we were not importing any relationships from external ontologies any more. 
Here is the pull request:  #14297

**Comment by cmungall** [comment]
Another problem:

![image](https://user-images.githubusercontent.com/50745/31344626-0e5726ac-acc8-11e7-8edb-52357e984ab1.png)

Uberon is using this class. I missed the obsoletion announcement, would it be possible to make requests on the uberon tracker if you're obsoleting a term used in uberon? This shouldn't happen too often, we use mostly stable terms.

Note you can also check external ontology usage in ontobee, there may be other ontologies using terms.

We don't have very good mechanisms for broadcasting obsoletion beyond core GO curators.

**Comment by cmungall** [comment]
Not sure when I will be able to address the imports issue. If this is urgent we can hack the import module for now.

**Comment by pgaudet** [comment]
Hi @cmungall 
As much as I would love to obsolete 'multi-organism signaling', it looks to me like it's still in the ontology. (in fact in Protégé I see two labels, like the bug we used to have for imported terms). 

Pascale

**Comment by BarbaraCzub** [comment]
Hi @cmungall 

Here are details of the issue relating to ChEBI imports, which we encountered last week:

![issue - asserted in chebi](https://user-images.githubusercontent.com/16541096/31346296-843a4a50-ad10-11e7-9fa1-55aeda4cb215.png)

~/repos/go-ontology/src/ontology(issue-14021) $ git diff
diff --git a/src/ontology/imports/chebi_import.owl b/src/ontology/imports/chebi_import.owl
index 289b820..2e8f8d0 100644
--- a/src/ontology/imports/chebi_import.owl
+++ b/src/ontology/imports/chebi_import.owl
@@ -87492,7 +87492,6 @@
     
 
     <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0035636">
-        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GO_0023052"/>
         <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">multi-organism signaling</rdfs:label>
     </owl:Class>
     
@@ -165961,5 +165960,5 @@
 
 
 
-
+
 
~/repos/go-ontology/src/ontology(issue-14021) $

**Comment by ukemi** [comment]
Yes. It used to be in our SOP to check for usage in other ontologies and then cc the contact in the obsoletion email. I still do that, but somehow it slipped through the cracks of our SOPs.

**Comment by pgaudet** [comment]
Ha ! We should put it back. How many ontologies are you checking ?

**Comment by ukemi** [comment]
I look on ontobee at the bottom of the page for the GO term.
