### ISSUE TITLE
query term: regulation of mitochondrial membrane permeability

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14308]
I don't know what that term means, is there any such thing?

Exact def is

regulation of transport across mitochondrial membrane | exact

but this is not exactly the same thing. I think "regulation of small molecule transport is probably the intended meaning but it is difficult to tell?

**Comment by ValWood** [comment]
OK many annotations are from
GO:0097345    mitochondrial outer membrane permeabilization
--
http://europepmc.org/abstract/MED/21041309

this does not seem to be equivalent to transport. Isn't the membrane ruptured during apoptosis?
"regulation of permeability" doesn't seem to be the correct way to describe this process?

**Comment by ukemi** [comment]
I believe that biologists that study apoptosis use this term to refer to the disruption in mitochondrial membrane integrity that occurs as part of the apoptotic process. I think a pore is formed. Someone should double-check this.

**Comment by ValWood** [comment]
I think the early steps are caused by an influx of solutes. the process is usually called "membrane permeablization" and to me this is different from "regulation of permeability" but I guess the apoptosis group will have looked into this branch and assume its OK so will close.

**Comment by pgaudet** [comment]
It smells like a readout to me... When I quickly scan the annotations I see a lot of apoptotic signaling molecules.

**Comment by ValWood** [comment]
Aren't they are actually regulating "membrane permeablization"  though?
https://www.researchgate.net/publication/44596864_Targeting_mitochondria_for_cancer_therapy/figures?lo=1

(I would't call this 'regulation of membrane permeability", though? I think permeablization and permeability are slightly different).

**Comment by pgaudet** [comment]
Right, as far as I can tell what is being measured is the change in membrane permeability, and the definition of 'regulation'  in GO is 'any change in rate, extent... etc' , which causes a lot of confusion. 

Pascale

**Comment by ValWood** [comment]
Yes our definition of regulation is much to weak to describe biological regulation.
Bax probably regulates the "solute import" step? which is transport, but the eventual  rupture (permeablization)  seems to be a consequence  of the solute import? so in that case it probably is a "readout"?
