### ISSUE TITLE
Format of EC numbers in GO xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#14305]
Partial EC numbers in xrefs are often written like this:
"1.1.1"
The standard way of writing this is:
"1.1.1.-"

The standard way appears to be used when EC numbers appear in the definition line, but the alternative is often/always used in the xref line.  E.g. GO:0016616

This is cumbersome for any third-party using the xref EC entry, and also means the hyperlinks from Amigo EC xrefs to http://enzyme.expasy.org don't work.

Can the standardized format (using hyphens to denote missing numbers) be implemented throughout the GO file?

**Comment by hdrabkin** [comment]
We actually need to remove all uses of 3 digit ecs as xrefs to anything other than grouping terms.

**Comment by sjm41** [comment]
hi Harold. Yes, that makes sense.  But wherever 'partial' EC xrefs remain, they ought to have the hypens.
Another high-level example:  hydrolase activity (GO:0016787)
This has an EC xref of "3", but it should be "3.-.-.-"

**Comment by hdrabkin** [comment]
This is a bigger project than just putting the - back. We use the xrefs to generate the ec2go file. However, we need to make sure that more granular terms do not have them. Currently we have checks in place so that ec's with - do NOT get into the xrefs because of that. It was a stop-gap measure to prevent passing on all children of a class into the file. This will take time.

**Comment by sjm41** [comment]
OK, understood.
In case it's helpful, I just came across an example of the type mentioned in your first comment:
MAP kinase kinase kinase activity (GO:0004709) has EC xrefs of 2.7.11.25 and 2.7.11.  It should only have the former.

**Comment by hdrabkin** [comment]
yes, there are numerous ones, most likely resulting from various term merges from the past. There are a couple of git tickets pertaining to this cleanup. It will be easier to 1rst remove the ones where the 3 digit ecs should not be

**Comment by hdrabkin** [comment]
Just removed the one from GO:0004709, as that one had no other problems.

**Comment by sjm41** [comment]
Thanks.  Let me know whether it would be useful for me to list other similar cases here (or in a separate ticket), or if you've already got such a list to work through.

**Comment by hdrabkin** [comment]
Thanks; I have a report list 
https://github.com/geneontology/go-xref-analysis/blob/master/redundant-xrefs-ec.tsv
of things to work on.

**Comment by hdrabkin** [comment]
These have also been misused as defs for for granular terms which is also not useful.

**Comment by pgaudet** [comment]
TO DO: Check that the .-'s are restored in the http://snapshot.geneontology.org/ontology/external2go/ec2go file.

**Comment by pgaudet** [comment]
> TO DO: Check that the .-'s are restored in the http://snapshot.geneontology.org/ontology/external2go/ec2go file.

Yes ! This can close.

**Comment by sjm41** [comment]
Hooray! Thanks all.
