### ISSUE TITLE
EC number for "phospholipase C activity" (GO:0004629)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#14314]
This term has EC:3.1.4.3 and EC:3.1.4.4 in the def line, but no EC xrefs.
EC:3.1.4.3 is "Phospholipase C" but EC:3.1.4.4 is "Phospholipase D".

So, looks like EC:3.1.4.4 needs removing from the def line, and EC:3.1.4.3 needs adding as an xref.

**Comment by hdrabkin** [comment]
fixed.
