### ISSUE TITLE
GO:0015563 uptake transmembrane transporter activity vs. GO:0098663 transmembrane transporter activity involved in import into cell

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14322]
moved from #14278 

Please note the term:
GO:0015563 uptake transmembrane transporter activity
Definition: Enables the transfer of a specific substance or related group of substances from the outside of a cell to the inside across a membrane.
seems to be equivalent to:
GO:0098663 transmembrane transporter activity involved in import into cell
But GO:0015563 does not have the parent term: GO:0098657 import into cell
It looks to me like it should. And then the phrase 'transmembrane transporter activity involved in import into cell' should be added as a synonym to GO:0015563 uptake transmembrane transporter activity

Ruth

**Comment by pgaudet** [comment]
Hi all, 

1) I will propose to obsolete 'GO:0098663 transmembrane transporter activity involved in import into cell'; there are no annotations, and I dont think the specific location of the transport is relevant in the MF. 

2) Does anyone know about 'uptake transmembrane transporter activity'? I am tempted to rename the terms with this string to remove the "uptake". It seems like the terms were created to also capture the process of import into cell, but really that needs to be a BP annotation to be consistent across all types of transporters.

**Comment by pgaudet** [comment]
Moreover about point 2 above: the textual definitions and the logical definition of children of 'uptake transmembrane transporter activity' is not consistent with the 'uptake' textual definition "Enables the transfer of a specific substance or related group of substances from the outside of a cell to the inside across a membrane." 

For example: 

**allantoin uptake transmembrane transporter activity**
**textual definition:** Enables the transfer of a specific substance or related group of substances from the outside of a cell to the inside across a membrane.
**logical definition:** 
'uptake transmembrane transporter activity'
 and ('transports or maintains localization of' some allantoin)

So I will make the 'uptake' terms synonyms.

**Comment by pgaudet** [comment]
For reference: EXP annotations:

GENE PRODUCT DB	GENE PRODUCT ID	SYMBOL	QUALIFIER	GO TERM	GO NAME	ECO_ID	GO EVIDENCE CODE	REFERENCE	WITH/FROM	TAXON ID	ASSIGNED BY	ANNOTATION EXTENSION
UniProtKB	G5EB18	ANIA_00399	enables	GO:0015513	nitrite uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:18024100		227321	AspGD	
UniProtKB	O60779	SLC19A2	enables	GO:0015403	thiamine uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:21836059		9606	UniProt	
UniProtKB	P0AFJ7	pitA	enables	GO:0015654	tellurite uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:23189244		83333	EcoCyc	
UniProtKB	P22152	crnA	enables	GO:0015513	nitrite uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:18024100		227321	AspGD	
UniProtKB	P23849	trkG	enables	GO:0015388	potassium uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:1987159		83333	CACAO	
UniProtKB	P32705	actP	enables	GO:0015654	tellurite uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:26211961		83333	EcoCyc	
UniProtKB	P46133	abgT	enables	GO:0015558	p-aminobenzoyl-glutamate uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:17307853		83333	EcoCyc	
UniProtKB	P46133	abgT	enables	GO:0015558	p-aminobenzoyl-glutamate uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:9829935		83333	EcoCyc	
UniProtKB	P47946	trk1	enables	GO:0015388	potassium uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:9139127		284812	PomBase	
UniProtKB	P50537	mae1	enables	GO:1901549	malonic acid uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:8750236		284812	PomBase	
UniProtKB	Q04895	DAL4	enables	GO:0005274	allantoin uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:385448		559292	SGD	
UniProtKB	Q5AST3	ANIA_08647	enables	GO:0015513	nitrite uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:18024100		227321	AspGD	
UniProtKB	Q5AST3	ANIA_08647	enables	GO:0015513	nitrite uptake transmembrane transporter activity	ECO:0000316	IGI	PMID:18024100	AspGD:ASPL0000056693|AspGD:ASPL0000060467	227321	AspGD	
UniProtKB	Q8CIW6	Slc26a6	enables	GO:0015659	formate uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:12119287		10090	UniProt	
UniProtKB	Q93Z75	UPS5	enables	GO:0005274	allantoin uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:16738859		3702	TAIR	
UniProtKB	Q99PL8	Slc19a3	enables	GO:0015403	thiamine uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:19879271		10090	BHF-UCL	
UniProtKB	Q9EQN9	Slc19a2	enables	GO:0015403	thiamine uptake transmembrane transporter activity	ECO:0000315	IMP	PMID:19879271		10090	BHF-UCL	
UniProtKB	Q9SV84	NIP5-1	enables	GO:0080138	borate uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:16679457		3702	TAIR	
UniProtKB	Q9ZPR7	UPS1	enables	GO:0005274	allantoin uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:11971139		3702	TAIR	
UniProtKB	Q9ZQ89	UPS2	enables	GO:0005274	allantoin uptake transmembrane transporter activity	ECO:0000314	IDA	PMID:15308648		3702	UniProt

**Comment by ValWood** [comment]
Happy for the merge. PomBase annotations have appropriate "x import across plasma membrane" 
annotation.

**Comment by ValWood** [comment]
also spotted

high-affinity ferrous iron uptake transmembrane transporter activity
high-affinity zinc uptake transmembrane transporter activity
used by PomBAse

**Comment by ValWood** [comment]
need a term for plasma membrane import  term for
"high-affinity zinc II ion transmembrane import"

There is a similar issue with high and low affinity, it is sometimes doubly encoded in  MF and BP
I don't think we need it in BP too do we ?

**Comment by RLovering** [comment]
Can I assume that I don't need to do anything because you will just be renaming?
Thanks
Ruth

**Comment by ValWood** [comment]
Hi  Ruth. I double checked the pombe ones that  the corresponding "import across plasma membrane " term had been used for the process annotation.
You might want to do this too?

v

**Comment by RLovering** [comment]
Good point
Processes added, but there is no process term thiamine import (across plasma membrane), but are you going to create new terms for all molecules imported? Or would you be planning on a general term, such as vitamin import? 
I used AEs to specify extracellular space to cytosol, as extensions to the transmembrane transport term; but not sure this is the best approach to take?

Ruth
