### ISSUE TITLE
GO:0005487 - nucleocytoplasmic transporter activity parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14336]
GO:0005487    nucleocytoplasmic transporter activity
is a 
"molecular  carrier activity"

not "protein transporter activity"

see
https://github.com/geneontology/go-ontology/issues/14331
https://github.com/geneontology/go-ontology/issues/14221

**Comment by pgaudet** [comment]
Hi Val, 

Are you requesting the parent to be changed  ?

**Comment by ValWood** [comment]
yes this branch (GO:0005487 - nucleocytoplasmic transporter activity and children)  belongs under carrier.

As you pointed out 
GO:0005487 - nucleocytoplasmic transporter activity
is not a good name.

The children are called import receptors and export receptors.

I think you could rename it "nulceocytoplasmic carrier"


GO:0090631    pre-miRNA transporter activity 
and
GO:0061717    miRNA transporter activity

will also need to be addressed.

but I don't think the terms should be created yet  (at least from these papers). They do not indicate whether miRNAs use the same karyopherins as other RNAs in which case 
I'm not sure these specific terms are required.

All the papers says is that Exportin-t  mutant does not affect miRNA export?

**Comment by ValWood** [comment]
nucleocytoplasmic carrier
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3536896/
https://www.ncbi.nlm.nih.gov/pubmed/?term=%22nucleocytoplasmic+carrier%22

would be a good name...

**Comment by pgaudet** [comment]
great, thanks !

**Comment by ValWood** [comment]
Hmm a problem. In addition to kayopherins, nucleocytoplasmic transporter has been used quite a lot for "nuclear pore " proteins by SGD.

I would not call the nuclear pore a transporter....  but I don't know what it's function would be. It  *enables* transport, but it isn't a transporter itself is it?

**Comment by pgaudet** [comment]
TCDB puts the nuclear pore with other pores. So maybe these are OK under transporter activity, and the kayopherins are carriers ?

**Comment by ValWood** [comment]
OK, people do refer to the pore itself as a "transporter" sometimes. I found 2 egs
http://www.ks.uiuc.edu/Research/npc/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2944363/

So, transporter and transmembrane transporter can't be merged...
The nuclear pore isn't a transmembrane transporter.

**Comment by pgaudet** [comment]
HI @ValWood 
I am closing this one. Nucleocytoplasmic transporter activity is now directly under transporter activity, with sibling transmembrane transporter activity. I think this resolves the issue; reopen if not.

**Comment by ValWood** [comment]
I still think this is a problem. This is the term that we use for nuclear import receptors. I think in the refactoring these are a type of "carrier". However, I'm sure this is covered by other tickets. If I can find one I'll link to this and re-close.

**Comment by ValWood** [comment]
I can't see another ticket, we can discuss Tues.

**Comment by pgaudet** [comment]
@thomaspd suggests this clarification: 
A transporter does not move with its cargo
A carrier moves something by moving itself. 

Would that clarify the issue ?

**Comment by ValWood** [comment]
It would, if you make it clear that the "carrier moves" but does not "self-propel" .

**Comment by ValWood** [comment]
Also this is not completely true for the Acyl-carrier proteins. Here, only the swinging arm moves.

or possibly for the things  that "insert" things into membranes. I don't know if all of these move, but they are classed as carriers.

**Comment by ValWood** [comment]
GO:0140132    iron-sulfur cluster carrier activity

does this "move" things @Antonialock ?

or just transfer them? (acts as a chaperone)

**Comment by pgaudet** [comment]
Suggestion following discussion with @ValWood 

'miRNA transporter activity'
'nuclear export signal receptor activity'
'nuclear import signal receptor activity'
'pre-miRNA transporter activity'
-> move under molecular carrier activity. Redefine t make it clear that they represent the karyopherin-like activities

- 'nucleocytoplasmic transporter activity' -> redefine to make it clear that it represents the pore.

**Comment by ValWood** [comment]
I'm but I'm a bit worried about changing the existing term, and I'm not convinced about an activity for the nuclear pore...it's really only structural and binds to things being moved through it.

I would probably only annotate to "structural component of nuclear pore"
GO:0017056    structural constituent of nuclear pore

or "protein binding" part_of "nucleocytoplasmic transport" for  components of the pore which are "docking sites"

**Comment by Antonialock** [comment]
> GO:0140132 iron-sulfur cluster carrier activity
> does this "move" things @Antonialock ?

Hmm, good question, we haven't annotated to that term. I annotated to transferase when I should have annotated to carrier. I'll sort this out today. The carriers move with the clusters. You also have transferases that transfer clusters between carriers -> final acceptor, or carrier -> carrier

**Comment by ValWood** [comment]
so  can you describe what the specific "carrier activity" is here? is it moving  with something?

v

**Comment by pgaudet** [comment]
yes - carriers move with their cargo. 

- [] nucleocytoplasmic transporter activity -> move under 'molecular carrier activity'
- [] change definition from 'Enables the directed movement of substances between the nucleus and the cytoplasm of a cell.'  to 'Carries substances between the nucleus and the cytoplasm of a cell by moving along with the target protein.'

@ValWood @thomaspd does that look to you ?

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/14702

**Comment by ValWood** [comment]
It looks OK to me as that was the original intent of the  import and export carrier grouping term
nucleocytoplasmic transporter activity 
but because it wasn't well defined, it has been used for nuclear pore proteins, will need annotation review.

I suggest 
nucleocytoplasmic transporter activity rename  nucleocytoplasmic importin/exportin activity
or similar

**Comment by pgaudet** [comment]
@rachhuntley 
I would like to merge 
GO:0061717 miRNA transporter activity
GO:0090631 pre-miRNA transporter activity
since the only EXP annotation on these two terms is EXPORTIN5, ie the 'normal' export receptor.

Is this OK for you ? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
Hi Pascale,

So we originally (https://github.com/geneontology/go-ontology/issues/11939) created two terms here because in plants most of the miRNA processing occurs in the nucleus, therefore plants do not transport pre-miRNA but they transport the miRNA duplex (see http://wiki.geneontology.org/index.php/MicroRNA_GO_annotation_manual#Plant_miRNA_biogenesis_and_action). 

I would expect the Hasty protein to be annotated to miRNA transporter activity.

I guess the terms could be merged with the primary name as miRNA transporter activity and pre-miRNA transporter activity as a synonym, but I'm not sure if Hasty has the same mechanism as Exportin-5. Both Hasty and XPO5 bind Ran, so it probably does.

Copying @tberardini for her input.

Thanks,
Rachael.

**Comment by pgaudet** [comment]
Hi @rachhuntley @tberardini 
This seems to be the same molecular function; I suggest that the difference be captured at the BP level, for eg: GO:0061716 miRNA export from nucleus

Would that work ? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
It seems fine to me.
Thanks,
Rachael.

**Comment by pgaudet** [comment]
Hello, 

Here's the latest proposal on this: 
1. nucleocytoplasmic transporter activity
is_a 'transporter activity'
Definition: Enables the transfer of a substance from one side of the nuclear envelope to the other.
Comment: Note that this term is meant to be used for nuclear pore proteins. For importins and exportins, consider 'nuclear import signal receptor activity' or 'nuclear export signal receptor activity'.

2. Change definition of 'transporter activity': Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells. **A transporter is in a fixed location in the cell and allows molecules to pass via a channel or a pore in its structure.** (text in bold is new) 

3. new term: 'nucleocytoplasmic carrier activity' 
is_a molecular carrier activity
Definition: Carries substances between the nucleus and the cytoplasm of a cell by moving along with the target protein.
do_not-annotate

4. Added two children: 
- nuclear export signal receptor activity; related synonym: importin
- nuclear import signal receptor activity; related synonym: importin

----
@ValWood @thomaspd 
+ anyone else 
does that seem OK ? 

Thanks, Pascale

**Comment by tberardini** [comment]
Note that there is an IMP annotation to 'pre-miRNA export from nucleus' for HST from UniProt. I agree with @rachhuntley that this should be 'miRNA export from nucleus' but I cannot edit that annotation.  I have removed the TAS annotation made by TAIR to the 'pre-miRNA' term and replaced it with an IMP annotation to 'miRNA export from nucleus' from a different paper.

**Comment by rachhuntley** [comment]
Thanks Tanya, I'll send an update request to UniProt about the HST annotation.

**Comment by ValWood** [comment]
I think this works. I'm still a bit leery of annotating all nuclear pore proteins as "nucleocytoplasmic transporter activity" , but the arrangement does work and is much clearer than it was.
Even though  the term was used incorrectly based in it's intended meaning as a grouping term for importins and exportins,  now it is moved out as a parent term, its remaining direct annotations appear to be correct  for the new meaning. So, somehow it seemed to work OK!

**Comment by bmeldal** [comment]
Still to fix:

1. 

- [ ]  GO:0005215 transporter activity has NARROW synonym "carrier" - should that be removed?

2. 

- [ ] "protein import into nucleus" vs "nuclear import" 
These 2 terms need a tightening of the definition. It suggests that 
"protein import into nucleus" is_a "nuclear import" 
when the former refers to the nuclear pore and the latter includes importins.
They also have very similar children, some are the same.

- GO:0051170 nuclear import
Definition: The directed movement of substances into the nucleus. 
Synonyms:
substance nuclear import | exact
single organism nuclear import | exact
single-organism nuclear import | related
import into nucleus | exact
nucleus import | exact
is_a GO:0006913 nucleocytoplasmic transport
Definition: The directed movement of molecules between the nucleus and the cytoplasm. 

- [ ] Suggested Comment: "Use this term to annotate proteins/substances that move through the nuclear pore, such as importins. For nuclear pore proteins consider GO:0015031 protein transport and its children." [or something in that direction]

- GO:0006606 protein import into nucleus
Definition: The directed movement of a protein from the cytoplasm to the nucleus. 
Synonyms:
protein nucleus import | exact
protein **transport** from cytoplasm to nucleus | exact
protein import into cell nucleus | exact
establishment of protein localization to nucleus | exact
is_a GO:0015031 protein **transport**
Definition: The directed movement of proteins into, out of or within a cell, or between cells, **by means of some agent such as a transporter or pore**. 

- [ ] Suggested Comment: "This term is mean to be used to annotate nuclear pore protein. For importins/exporting consider GO:0006913 nucleocytoplasmic transport and its children." [or something in that direction]
- [ ] I think most of the children need to be moved to GO:0051170 nuclear import.

The only real clue is on the activity term:
GO:0005487 nucleocytoplasmic **transporter** activity
Definition: Enables the transfer of a substance from one side of the nuclear envelope to the other. PMID:25802992
Comments: Note that this term is meant to be used for **nuclear pore proteins**. For importins and exportins, consider 'nuclear import signal receptor activity' or 'nuclear export signal receptor activity'.

Same applies to
- [ ] GO:0051168 nuclear export
Definition: The directed movement of substances out of the nucleus. 
and
- [ ] GO:0006611 protein export from nucleus
Definition: The directed movement of a protein from the nucleus into the cytoplasm. 

- [ ] There are also many equivalent relationships for the export and import terms that are missing in the respective opposite term. See figure:
![image](https://user-images.githubusercontent.com/10517124/33930693-a5ab938a-dfe5-11e7-8aac-9aabca622aee.png)

3.

- [ ] obsolete GO:0042564 NLS-dependent protein nuclear import complex and GO:0006607 NLS-bearing protein import into nucleus?

In https://github.com/geneontology/go-annotation/issues/1700 
I asked:
"Should GO:0042564 NLS-dependent protein nuclear import complex (A dimer consisting of an alpha and a beta-subunit that imports proteins with an NLS into the nucleus through a nuclear pore.) have "importin" as a narrow synonym?"
Val says 
"Personally I don't think it's a different process....Some things might not have NLS but they are imported with something that has.... I don't think "NLS-dependent" needs to be a term....Isn't all nucleocytoplasmic transport NLS dependent, its just that only sometimes is the NLS identified...."

Of course, I might be completely wrong here!

**Comment by ValWood** [comment]
Re
"protein import into nucleus" vs "nuclear import"
These 2 terms need a tightening of the definition. It suggests that
"protein import into nucleus" is_a "nuclear import"
when the former refers to the nuclear pore and the latter includes importins.
They also have very similar children, some are the same.

"protein import into nucleus" vs "nuclear import" should be a parent child relationship.
I  don't know if separate terms are needed. This was to historically distinguish between protein and non protein cargo.
Both terms can refer to importins, or the nuclear pore (some nuclear pore proteins appear to be  required for import specificity)



2017-12-08 | Deleted | RELATION | is a GO:0051170 (nuclear import)
-- | -- | -- | --

should be added back

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-ontology/issues/14748

**Comment by pgaudet** [comment]
@ValWood  Is this fixed ?

**Comment by ValWood** [comment]
I think it is OK.
I'm still not completely comfortable with the classification of the nuclear pore as a "transporter". I still think it only "enables" transport, and is not a transporter per se. However,  it is clear that this term is only for nuclear pore proteins,  and how to annotate importins and exportins, which are in the carrier branch so can be closed.

**Comment by bmeldal** [comment]
Don't we have to fix the defs? As it is now it's not clear what applies to NP proteins and what's for importins and exportins - without reading this thread.

**Comment by ValWood** [comment]
nucleocytoplasmic carrier activity
Definition (GO:0140142)
Carries substances between the nucleus and the cytoplasm of a cell by moving along with the target protein.
Restrictions
This term should not be used for direct annotation. 

1. I'm not sure we always know if an importin is for import or export if from sequence similarty?

2. The children are defined
Combining with a nuclear import signal (NIS) to mediate transport of a NIS-containing protein through the nuclear pore, from the cytoplasm to the nucleus. PMID:25802992


perhaps the definition of the parent could be

Combining with a nuclear import signal (NIS) or (NES) to mediate transport of a  protein through the nuclear pore, by moving with the target protein. PMID:25802992

I still think the name of
GO:0005487    JSON
nucleocytoplasmic transporter activity
for nuclear pore proteins should be changed.

The community refer to karyopherins as "nucleocytoplasmic transporters" not the nuclear pore itself. i.e. "importin family of nucleocytoplasmic transporters". I have never heard this term used to describe the nuclear pore....

I don't know what I would name it to though....

**Comment by bmeldal** [comment]
I don't have more insight than what I said above or what Val said. 

Although one point: the NIS is very often called a NLS = nuclear localisation signal, so this should at least be a synonym for the relevant terms.

**Comment by pgaudet** [comment]
@bmeldal 

>  1. GO:0005215 transporter activity has NARROW synonym "carrier" - should that be removed?
I think that should stay, because some transmembrane transporters (such as the SCL*) are named carriers.

**Comment by ValWood** [comment]
Should it be related in that case?

**Comment by bmeldal** [comment]
ok, "carrier" term as RELATED and add some comment to explain to the user how to distinguish btw carrier and transporter.

**Comment by pgaudet** [comment]
- Renamed 'nucleaocytoplasmic transporter activity' to 'nuclear pore activity' and added to the definiton, "Enables the transfer of a substance across the nuclear envelope **by providing a protein-lined channel in the nuclear envelope.**"
- add 'part of' some 'nucleocytoplasmic transport' to 'nucleocytoplasmic carrier activity'

**Comment by bmeldal** [comment]
GO:0005215 transporter activity:
- I think we should make "carrier" RELATED synonym as suggested above.
- Can you refer to the parent term for carriers in the comment? E.g. GO:0140104 molecular carrier activity?

Thanks, Birgit

**Comment by pgaudet** [comment]
Thanks @bmeldal 

- the synonym is 'related', indeed
- fixed the comment as follows: 'Some transporters, such as certain members of the SLC family, are referred to as 'carriers'; however GO uses carrier with a different meaning: a carrier binds to and transports the substance (**see GO:0140104 molecular carrier activity**), whereas a transporter forms some pore that allows the passing of molecules.' 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note to self: look for a better term label. Structural component of the nuclear pore ?

**Comment by rachhuntley** [comment]
Hi,
I'm just looking at correcting annotations with the do_not_annotate term 'nucleocytoplasmic carrier activity' and it looks like there are no suitable replacement terms. I want to indicate that RAN and XPO5 are exporting pre-miRNAs from the nucleus. I have made the distinction for pre-miRNA with a process term, as we agreed above, but there is no suitable function term. 

The term has the narrow synonyms miRNA and pre-miRNA transporter activity, but is do_not_annotate and its definition refers to moving target proteins. 
The child terms are not suitable either as there is no nuclear export signal, as traditionally defined (short amino acid sequence of 4 hydrophobic residues in a protein). The pre-miRNAs bind exportin-5 through small RNA hairpins bearing 2-nt 3′ overhangs. Should I be using the less specific term 'molecular carrier activity' and indicating the miRNA in the extension, or should we have a new, more specific term as a sibling to the NES terms that describes the pre-miRNA export mechanism?

I also don't think the comment associated with 'nucleocytoplasmic carrier activity' is sufficient - it refers to the (long) GitHub issue where the changes were made, so it's not easy to see what other terms you should be using instead.

**Comment by ValWood** [comment]
Term defs should be relaxed to include ncRNAs.
GO:0140142  nucleocytoplasmic carrier activity
GO:0061608   nuclear import signal receptor activity
GO:0005049    nuclear export signal receptor activity

**Comment by rachhuntley** [comment]
But it should also be made clear that a nuclear export signal can include a short amino acid sequence of 4 hydrophobic residues in a protein (for protein export) or small RNA hairpins bearing 2-nt 3′ overhangs (for pre-miRNA export). I'm not sure if there are other types of NES?

**Comment by deustp01** [comment]
Trying to remember from a long time ago, it looks like two distinct processes may be getting lumped together in the discussion here. One is the assembly of a cargo package for movement from the cytosol into the nuclear or vice versa. The other is the process of moving that cargo through the nuclear pore, and the term that started this discussion, GO:0005487 "nucleocytoplasmic transporter activity" (now a secondary term under GO:0017056 "structural constituent of nuclear pore" applies only to the second process. And, if I understand GO usage correctly, GO:0005487 / GO:0017056 should only be used to annotate the proteins involved in mediating cargo movement, not proteins in the cargo (where that includes adapters like exportins as well as cargo proper). @ukemi ?

**Comment by ValWood** [comment]
@deustp01  following up

GO:0005487 / GO:0017056 are both IDs for "structural constituent of nuclear pore"

For importins and exportins, we would use 'GO:0061608 nuclear import signal receptor activity' or 'GO:0005049 nuclear export signal receptor activity', respectively (now classed as "molecular carrier/ nucleocytoplasmic carrier activity"

we don't annotate the cargo  to these terms. 

val

**Comment by pgaudet** [comment]
* To be clear: GO:0005487 has been merged into GO:0017056 "structural constituent of nuclear pore"

* @deustp01 : "the assembly of a cargo package for movement from the cytosol into the nuclear or vice versa" is binding to the  nuclear import signal receptor (GO:0061608) or nuclear export signal receptor activity (GO:0005049)

* to address @rachhuntley 's point, how about updating the definitions as follows: 
GO:0061608: nuclear import signal receptor activity: "Combining with a nuclear import signal (NIS) on a cargo to be transported, to mediate transport of the cargo through the nuclear pore, from the cytoplasm to the nucleus. The cargo can be either a RNA or a protein." 

GO:0005049 nuclear export signal receptor activity: "Combining with a nuclear export signal (NES) on a cargo to be transported, to mediate transport of a the cargo through the nuclear pore, from the nuclear to the cytoplasm. The cargo can be either a RNA or a protein."

@rachhuntley Can you provide some reference for RNA import and export ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
> @rachhuntley Can you provide some reference for RNA import and export ?
Actually the current reference for export described RNA !!!

**Comment by pgaudet** [comment]
Also updated x references: 
* nuclear export: PMID:11743003, PMID:25802992, PMID:28713609, Wikipedia:Nuclear_transport
* nuclear import: PMID:28713609, Wikipedia:Nuclear_transport

**Comment by pgaudet** [comment]
@rachhuntley let me know if this addresses the point you raised. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Typo:
>GO:0005049 : ...to mediate transport of a the cargo through the nuclear pore, from the nuclear to the cytoplasm.

should be nucleUS

(Sorry, I'm late to the part due to time off)

**Comment by pgaudet** [comment]
Hi @bmeldal Thanks for reporting this ! In fact I meant 'nuclear lumen'; is that OK ? 

I also added logical definitions as follows: 
* GO:0140142 nucleocytoplasmic carrier activity
   molecular carrier activity
      part_of some nucleocytoplasmic transport


* GO:0061608 nuclear import signal receptor activity
 nucleocytoplasmic carrier activity
     part_of some import into nucleus

* GO:0005049 nuclear export signal receptor activity
   nucleocytoplasmic carrier activity
       part_of some  nuclear export

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale, it should be nucleus, not nuclear lumen.  The cargo is moving from the nucleus to the cytoplasm or vice versa but it isn't crossing the  "nuclear envelope lumen"

This seems "unimportant" but if you think of the nuclear lumen as continuous with the ER it makes more sense why we need to keep these separate.
The nuclear lumen is continuous with the ER and the cytoplasm is continuous with the nucleus.

There are very precise ways to get into the lumen. I think this makes it clearer than my previous explanations as it shows the broader context, not only  the nuclear pore:

![lumen](https://user-images.githubusercontent.com/7359272/38805481-dec1faee-416d-11e8-99ce-dc9a7c9bdd37.jpg)

**Comment by mah11** [comment]
Nuclear lumen =/= nuclear _envelope_ lumen, and I don't see a problem with using nuclear lumen in this def.

**Comment by ValWood** [comment]
Ah OK, I never see the use of this phrase only "nuclear envelope  lumen"
ignore.

**Comment by pgaudet** [comment]
Thanks for the clarification @mah11 
I was trying to say this the cargo does *inside* the nucleus, and not to the envelope, for example. 


All good ? 

Thanks, Pascale

**Comment by ValWood** [comment]
It would be good to find an example of it's use  in this context if we keep it.

**Comment by ValWood** [comment]
Note that last week "nucleocytoplasmic transporter" reverted to being a transporter not a carrier. Although people call it a carrier, it isn't a carrier in the GO sense, it's a transporter.

@pgaudet  can you link this to the ticket documenting the change, I can't find it. I'm still a little confused by exactly what classifies as "carrier" do it would be good to have a trail for this.

**Comment by pgaudet** [comment]
There was no ticket yet - thanks for the reminder ! Here: 
https://github.com/geneontology/go-ontology/issues/17399
