### ISSUE TITLE
GO:0005215 transporter activity change logical definition

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14331]
GO:0005215 transporter activity change logical definition from 
molecular_function
 and ('part of' some  transport)

to : 
molecular_function
 and ('part of' some 'transmembrane transport')

**Comment by mah11** [comment]
Really? I thought the reason for having GO:0022857 (name: transmembrane transporter activity, is_a: GO:0005215) was that there are transporter activities that don't move their substrates across membranes. But I have no specific knowledge; I only remember the case being made, not any examples.

If there is no distinction, then the two should be merged. If they're different, and therefore should be kept separate, then the logical definition fits GO:0022857.

**Comment by pgaudet** [comment]
Hi Midori, 

Good point. The one exception in the MF is 'nucleocytoplasmic transporter activity'. This one is not transmembrane. The other classes that are **not** under TM transporter activity (but htta should perhaps be are: 
'alkane transporter activity'
'carbohydrate derivative transporter activity'
'carbohydrate transporter activity'
'cofactor transporter activity'
'drug transporter activity'
'fatty-acyl-CoA transporter activity'
'L-serine transporter activity'
'neurotransmitter transporter activity'
'odorant transporter activity'
'siderophore transporter activity'
'substrate-specific transporter activity'
'toxin transporter activity'
'transmembrane transporter activity'
'vitamin transporter activity'
'xenobiotic transporter activity'

I need to look at the annotations but if you know anything about these it would be useful. 

I am checking the  'nucleocytoplasmic transporter activity' - I will not merge yet. 

Thanks, 
Pascale

**Comment by mah11** [comment]
Hmm, I've kind of already said as much as I know, having never studied transporters directly ;)
I just happened to spot that the term and proposed logical def didn't quite match ...

**Comment by pgaudet** [comment]
Well in any case there is something odd about 'nucleocytoplasmic transporter activity: two of its is-a children are
- nuclear export signal receptor activity
- nuclear import signal receptor activity
Clearly those are NOT transporters (although they are involved in transport). 

Pascale

**Comment by mah11** [comment]
Well, I don't know of any reason _not_ to change that branch. It does look odd!

**Comment by ValWood** [comment]
I think 
'nucleocytoplasmic transporter activity'
is really a "carrier" not a "transporter"

see comment in
https://github.com/geneontology/go-ontology/issues/14221

So would this also include
GO:0005049 nuclear export signal receptor activity etc?
Fits this def.

BUT we do have other types of transporter.
The microtubule motors have "transporter activity"

**Comment by ValWood** [comment]
These should be related to transporter activity by has_part.

https://www.ebi.ac.uk/QuickGO/term/GO:1990939

Unless there is a reason not to call them transporters?

**Comment by ValWood** [comment]
maybe we just annotate as "motors" involved in "transport" and they are not really "transporters".

**Comment by ValWood** [comment]
GO:0017128 - phospholipid scramblase activity
Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, by an ATP-independent mechanism.

is positioned as a transporter. but it isn't a transmembrane transporter.
Maybe this is not a "transporter" either.

The transport performed by  both scramblases and microtubule motors is described as "movement", and I never see them referred to as "transporters".

**Comment by pgaudet** [comment]
right - I dont think those are transporters. 

Carriers for nucleocytoplasmic transport makes sense.

**Comment by ValWood** [comment]
also a lot of other "protein type transporters"
http://pombase-dev.bioinformatics.nz/gene/SPBC2G2.06c
The shouldn't be transporter, I'm sure

GO:0008565 | protein transporter activity | IEA with IPR016342
-- | -- | --

but it fits the protein transport definintion:

Definition | Parents
-- | --
Enables the directed movement of proteins into, out of or within a cell, or between cells.

I wonder what "directed movement" really means. I don't think endocytosis is "directed"  in the same way that  "transmembrane transport is"

These are "adaptors" aren't they?

Can we make it clearer what directed movement means?

**Comment by ValWood** [comment]
Directed movement is "movement with a purpose" as opposed to diffusion.
I don't think clathrin adaptors are "protein transporter activity" but they do fit this definition.

This is the definition of transport
Definition GO:0006810 
The directed movement of substances (such as macromolecules, small molecules, ions) or cellular components (such as complexes and organelles) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter, pore or motor protein.

So really the current definition of MF  "transporter" is  almost indistinguishable from the definition of "transporter".

I think your proposed change will fix things:

This would make "transporter" and "transmembrane transporter" equivalent though.

**Comment by pgaudet** [comment]
The issue that brought up this ticket was that 'endocytosis' ended up inferring transporter activity. 
Directed movement is much wider than transport (IMO!); it's worth indeed distinguishing. Your examples are very useful. 

I am looking at other sibling classes to see what other types of MF we could have under 'transport'. We have already decided that carriers are not transporter. 

I don't know where the scramblase should go yet... 
GO:0017128 - phospholipid scramblase activity (and its sibling glycolipid-translocating activity) 

Pascale

**Comment by ValWood** [comment]
also consider
GO:0004012 - phospholipid-translocating ATPase activity
Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, driven by the hydrolysis of ATP.

with the scramblases (I'm not sure if they are different but they are separate terms)

**Comment by pgaudet** [comment]
thanks...

**Comment by mah11** [comment]
I think the difference between GO:0004012 and scramblase is that scramblase activities don't use ATP hydrolysis ...

**Comment by ValWood** [comment]
The other problem that there are general oarent terms for
GO:0005548 - phospholipid transporter activity
which might need to go as they combine translocases, transporters and carriers....
(sometimes it isn't really clear which thery refer to).

Look here for e.g.
http://pombase-dev.bioinformatics.nz/term/GO:0005319

I haven't really looked in detail as most are ISS'd from SGD, but some seem to move things  between membranes Mt OMM and mt IMM (possibly new-type carriers). 
Others are translocase type. Some I don't know what type....

**Comment by pgaudet** [comment]
Right now the only solution I can think of it to remove the logical definition of 'transporter activity', which is currently: 
molecular_function
and ('part of' some transport)

As discussed above, many MF play a role in transport, but that are not transporter activities. 

My plan is to: 
1. remove the logical definition of 'transporter activity', 
2. Try to fix the branch further
3. See if after that we can add back another logical definition. 

Feedback is welcome! 
@mah11 @ValWood @ukemi @dosumis @thomaspd

**Comment by pgaudet** [comment]
Good point. So that seems to support the suggestion to remove the logical definition because for MF we are not talking about a single type of activity.

**Comment by pgaudet** [comment]
Removed the logical definition of transport for now, as it's bringing in endocytosis, carriers, etc.
