### ISSUE TITLE
 "GO:0007343  egg activation" should a 'causally_upstream' event of Fertilization not  'part_of ' it in the ontology

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#14338]
Hi,
During the Fertilization Signalling Pathway analysis it was agreed with Kimberly ( @vthat) and David H (@da ) that "GO:0007343  egg activation" is a 'causally_upstream' event of Fertilization but in the ontology it seem to be 'part_of' single fertilization.

Perhaps it could be a child of "oocyte development" or "oocyte maturation".  "GO:0048240 Sperm capacitation" that is also a 'causally_upstream' event of Fertilization is 'part_of' "spermatid development" (https://www.ebi.ac.uk/QuickGO/term/GO:0048240).  Could that work?

Thanks,

Penelope

**Comment by ukemi** [comment]
Hmmm. I don't remember that decision. I think egg activation is generally though of as being a part of fertilization. It is triggered by the sperm.

**Comment by pgarmiri** [comment]
oups you are totally right! My wrong! Not quite sure how I got confused.. It is one of the last steps actually. No issues here. I will close it.
