### ISSUE TITLE
kinocilium tip

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#14332]
I would like to see “kinocilium tip” added as a part_of child term of “kinocilium (GO:0060091). Definition could be “The tip of a nonmotile primary cilium that is found at the apical surface of auditory receptor cells”. Synonym: tip of kinocilium PMID:25601850

**Comment by krchristie** [comment]
We already have a term for 'ciliary tip' that is a part_of child of the term 'cilium'. I'm not sure we want to start going down the route of duplicating the part_of children of the term 'cilium' under 'kinocilium'.  

You could already co-annotate with 'kinocilium' and 'ciliary tip'. In a GO-CAM model, you would be able to indicate 'ciliary tip' part_of 'kinocilium'.

thoughts? @ukemi @paolaroncaglia

**Comment by ukemi** [comment]
Unless there is something special about the kinocilium tip, I would go with your suggestion.

**Comment by krchristie** [comment]
The term 'ciliary tip' is already a sort of non-specific term that lets you annote the general region of the 'tip' without being very specific about a particular substructure of the cilium. 

It seems to me that the combination of the two existing terms is sufficient so I'm going to close this, but if you have more comments @slaulederkind, you can add them here and reopen.

**Comment by paolaroncaglia** [comment]
Hi @krchristie and @ukemi, I agree with your resolution.
