### ISSUE TITLE
basal dendrite

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#14333]
I would like to see “basal dendrite” added as an exact synonym of “basilar dendrite” (GO:0097441). PMID:17046728

**Comment by BarbaraCzub** [comment]
I wonder whether the 'basal dendrite' should even be the primary term, whereas the 'basilar dendrite' should be the synonym?

**Comment by BarbaraCzub** [comment]
Another ref.: PMID:22683681

**Comment by ukemi** [comment]
The primary term should be the most common unambiguous name used in the field. Quick searches suggest 'basal dendrite' as the winner.

**Comment by slaulederkind** [comment]
I think David is correct.
