### ISSUE TITLE
 DNA-3′-diphospho-5′-guanosine diphosphatase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14348]
Hi,

I would like to request a term for DNA-3′-diphospho-5′-guanosine diphosphatase activity
EC  3.1.12.2
ref PMID:26007660

Initially requested in #12379 but it took a while to get the EC term.

**Comment by krchristie** [comment]
Term: DNA-3'-diphospho-5'-guanosine diphosphatase.
synonym [EXACT]: DNA-3'pp5'G guanylate hydrolase.
Def: Catalysis of the reaction: (DNA)-3'-diphospho-5'-guanosine + H(2)O <=> (DNA)-3'-phosphate + GMP.
def xref PMID:26007660
Xref: EC 3.1.12.2
