### ISSUE TITLE
regulation terms for  GO:1990947

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14347]
Hi, I would like to request positive and negative regulation terms for 
GO:1990947 name: exit from meiosis

PMID:11493649. 

Thanks

**Comment by hdrabkin** [comment]
Done.

+id: GO:0106060
+name: regulation of exit from meiosis
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of exit from mitosis." [GOC:al, PMID:11493649]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: regulates GO:1990947 ! exit from meiosis
+created_by: hjd
+creation_date: 2017-10-18T16:48:01Z
+
+[Term]
+id: GO:0106061
+name: negative regulation of exit from meiosis
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of exit from meiosis." [GOC:al, PMID:11493649]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: negatively_regulates GO:1990947 ! exit from meiosis
+created_by: hjd
+creation_date: 2017-10-18T16:51:15Z
+
+[Term]
+id: GO:0106062
+name: positive regulation of exit from meiosis
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of exit from meiosis." [GOC:al, PMID:11493649]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: positively_regulates GO:1990947 ! exit from meiosis
+created_by: hjd
+creation_date: 2017-10-18T16:57:01Z
