### ISSUE TITLE
NTRs: premature acrosome loss and regulation terms of it

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#14345]
Hi,

I would l like to ask for some new terms as discussed at the resent Signalling Workshop.

 - **NTR:** Regulation of premature acrosome loss

**Synonym** : Regulation of spontaneous acrosome loss

**Suggested definition:** Any process that modulates the frequency, rate or extent of premature acrosome loss.

**Note:**  If the release of the acrosome content occurs at the zona pellucida, consider using  GO:0060046 regulation of acrosome reaction.

It could be a child of regulation of fertilization.

- In particular, the negative regulation of this term is the one that is more physiologically relevant.
**NTR:** Negative regulation of premature acrosome loss
**Synonym :** Negative regulation of spontaneous acrosome loss

**Suggested definition:** Any process that stops, prevents or reduces the frequency, rate or extent of premature acrosome loss.

**Note:** That occurs before the sperm reaches the zona pellucida.

That could be a child of "positive regulation of fertilization".

It might sounds a bit oxymoron but, physiologically, this is what is does. It prevents the premature acrosome loss, thus allows the reaction to happen at the right time and place, so positively regulates the fertilization process.
**Question:** Should that be specified in the definition to facilitate understanding and correct usage of the term?

Supporting publications for the existence of such regulators:

- PMID:22228629; SPINK3

- PMID:23430248; Spink13 (this publication has been used for creating  GO:1902225 negative regulation of acrosome reaction. But it's clearly referring to the premature acrosome loss. I would suggest obsoleting this term. I will create a different ticket for this, as there are some annotations that will need to be updated to the new term after it's created.)

- I suppose the parent term should also be added to aid the building of the tree in the ontology.

**NTR:** premature acrosome loss

**Synonym :** Spontaneous acrosome loss

**Suggested definition:** The discharge, by sperm, of a single, anterior secretory granule before the sperm reaches to the zona pellucida of the oocyte. The process begins with the fusion of the outer acrosomal membrane with the sperm plasma membrane and ends with the exocytosis of the acrosomal contents.

**Note:**  If the release of the acrosome content occurs at the zona pellucida, consider using GO:0007340 acrosome reaction.

It could be a sibling of "acrosome reaction".

Thanks,

Penelope

**Comment by ukemi** [comment]
Hi @pgarmari

I am still torn about creating the term 'premature acrosome loss' because I'm still not convinced it is a normal process. Can you remind me if there is a physiological relevance to the spontaneous release. If there isn't, maybe just a regulation term can be created. The term would not be a regulation of acrosome reaction, but would be a negative regulation of exocytosis.

**Comment by pgarmiri** [comment]
Hi @ukemi ,

The 'premature acrosome loss' has been reported to facilitate the dispersal of the cumulus mass. It can be initiated by particular sperm factors or by progesterone released by the cumulus cells. Although there is still some discussion about this, most authors consider it normal.


- There was a recent review about this..

"it is clear that the ZP may not be the only site of AR and that the cumulus mass may also be a physiological site of AR. We thus propose that some sperm initiate their AR when contacting with the cumulus cells, while some of them remain acrosome intact until they reach the ZP and bind to ZP3.

They say that "AR initiated at the site of the cumulus is for meaningful purposes that we are not entirely sure at the moment. Obviously, these acrosome reacted sperm may disperse the cumulus mass for other sperm population and it is the sacrifice of the acrosome-reacted sperm at the site of cumulus that paves the way for other sperm to follow through without undergoing AR until they reach ZP."

They attribute this to "..a sperm-released factor, NYD-SP8, that initiates AR upon sperm interaction with cumulus cells."

https://www.ncbi.nlm.nih.gov/pubmed/19153666

https://www.ncbi.nlm.nih.gov/pubmed/21380641 


- Other authors found that AR is induced by progesterone released by the cumulus cells.

https://www.ncbi.nlm.nih.gov/pubmed/26655718

In all case, when the AR  occurs, it allows the release of several types of sperm enzymes. "The release of these enzymes leads to a partial hydrolysis of the layers surrounding the oocyte, allowing the sperm to reach the oolema where the fusion between the two gametes occurs."
