### ISSUE TITLE
Definition Revision:  GO:0007340 'acrosome reaction' 

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#14358]
Hi,

I would like ask for the definition of GO:0007340 'acrosome reaction' to be revised as discussed during the Signalling workshop.

**Current Definition:**
The discharge, by sperm, of a single, anterior secretory granule following the sperm's attachment to the zona pellucida surrounding the oocyte. The process begins with the fusion of the outer acrosomal membrane with the sperm plasma membrane and ends with the exocytosis of the acrosomal contents into the egg. 

The suggested definition below is to clarify where the acrosome reaction takes places with a note to direct the curator to the right term if the reaction is happening at an earlier stage. (some reviews on that PMID: 21042299 and 11175768)

**Suggested Definition:**
The discharge, by sperm, of a single, anterior secretory granule following the sperm's attachment to the zona pellucida of the oocyte. The process begins with the fusion of the outer acrosomal membrane with the sperm plasma membrane and ends with the exocytosis of the acrosomal contents into the zona pellucida.

**Note:**  If the release of the acrosome content occurs before the sperm reaches to the zona pellucida, consider using GO:xxxxxxxx  premature acrosome loss.

Thanks,

Penelope

**Comment by ukemi** [comment]
How about just this for the new def?

The discharge, by sperm, of a single, anterior secretory granule following the sperm's attachment to the zona pellucida of the oocyte. The process begins with the fusion of the outer acrosomal membrane with the sperm plasma membrane and ends with the exocytosis of the acrosomal contents.

**Comment by pgarmiri** [comment]
I think, in order to capture what is happening in nature, we need to make the distinction between the acrosome reaction occurring at the right time and place for fertilization to happen and the one that occur before that. If the definition is more general, we will keep current logical mistakes and we wouldn't be able to prevent new ones. 

For example, SPINK3, is currently annotated to"negative regulation of acrosome reaction". Logically we could infer from that annotation that SPINK3 has a negative effect on fertilization, since acrosome reaction is necessary for fertilization to happen. However, what it's actually happening is the opposite. SPINK3 negatively regulated the "premature" acrosome reaction, enabling more sperm cells to have the reaction at the right time and place.  That would enhance the chances of successful fertilization.

This is linked to https://github.com/geneontology/go-ontology/issues/14345

Does that make sense?

**Comment by ukemi** [comment]
Yup. Makes perfect sense.
