### ISSUE TITLE
Term Revision:  GO:0060475 'positive regulation of actin filament polymerization involved in acrosome reaction' and NTR

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#14350]
Hi,

I would like request a term revision and a new term in the same ticket as they are related.

The **term to be revised** is: GO:0060475 positive regulation of actin filament polymerization involved in acrosome reaction

In several publications is reported that the actin polymerization occurs **during sperm capacitation** which prevents the occurrence of sAR (spontaneous acrosome reaction).

(PMID: 27178669, PMID: 26514336, PMID: 25966627 and reviewed in PMID: 15749953)

It should then be part_of "sperm capacitation" and not "acrosome reaction".

The new term I would like to request is:
    **NTR: positive regulation of actin filament depolymerization involved in acrosome reaction**

In PMID:20937821, the authors report that just before the acrosome reaction fast actin depolymerization  occurs that facilitated the reaction. 

Also, from the review above ( PMID: 15749953), "Prior to the occurrence of the acrosome reaction, the F-actin should undergo depolymerization, a necessary process which enables the outer acrosomal membrane and the overlying plasma membrane to come into close proximity and fuse."

This new term would be a child of 'GO:0030836 positive regulation of actin filament depolymerization' and  linked as part_ of to "acrosome reaction".

Thanks,

Penelope

**Comment by ukemi** [comment]
Hi @pgarmiri,

I think that rather than modify the existing 'positive regulation of actin filament polymerization involved in acrosome reaction' term, we should keep it and add a new capacitation-specific term. In organisms like echinoderms, actin polymerization is part of the acrosome reaction. PMID:28462533

**Comment by pgarmiri** [comment]
Hi @ukemi ,
I think that this is a good way around it. Perhaps, it should be mentioned that this term is more relevant to organisms like echinoderms. The new capacitation-specific term and the depolymerization one would be suitable for the for the mammalian process. What do you think?

**Comment by ukemi** [comment]
If I were certain about the taxon restrictions, I would think that is ok, but I am not. So I think I will just let the definitions guide annotators for now.

**Comment by pgarmiri** [comment]
Thank you @ukemi for creating the new terms!

As for GO:0060475, I would only suggest to add the PMID that you pointed out to me earlier in the conversation (PMID:28462533) to help annotation as there are currently no annotations to the term and it's not linked to any publication.
