### ISSUE TITLE
Definition revision of GO:0002077 ,acrosome matrix dispersal and addition of a new parent

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#14355]
Hi,

I would like ask for a term definition to be revised as discussed during the Signalling workshop.

GO:0002077 ,acrosome matrix dispersal

**Current definition:**
The proteolytic digestion of components in the acrosomal matrix that allows for their release into the egg. The dispersal of the components allows for the inner acrosomal membrane to interact with the egg.

**Suggested definition:** 
The proteolytic digestion of components in the acrosomal matrix that allows for their release from the sperm. That can occur either before the sperm reaches the zona pellucida or at it. If the release occurs before it, penetration of the cumulus oophorus is facilitated.  The dispersal of the components at the zona pellucida allows the sperm to penetrate it and reach to the plasma membrane of the egg where the inner acrosomal membrane of the sperm can interact with it.

This is in line with the work discussed in a recent review (PMID: 21380641).

Accordingly, this term should be linked with a part_ of relationship to both 'acrosome reaction' and the new term 'premature acrosome loss'.

Thanks,

Penelope

**Comment by pgarmiri** [comment]
Hi,
I was going to create a new ticket for revising the definition of  GO:0060478, 'acrosomal vesicle exocytosis' as it needed update below.  

Current definition for GO:0060478, 'acrosomal vesicle exocytosis':

The release of intracellular molecules contained within the acrosomal granule by fusion of the vesicle with the plasma membrane of the oocyte, requiring calcium ions. 
This definition would have to be corrected as the fusion is occurring with the plasma membrane of the sperm, not of the oocyte.

But after reading a bit more about it, it seems that GO:0060478, 'acrosomal vesicle exocytosis' should be merged with GO:0002077 , 'acrosome matrix dispersal' as they basically occur at the same time.

In a recent review (PMID:27194348) they refer to both terms in a way that clarify their association  "As acrosomal exocytosis proceeds and acrosomal matrix proteins are released..."

The term 'acrosomal vesicle exocytosis' is used more by curators and its name used in more often in publications, so I would suggest this to be the main name. The term 'acrosome matrix dispersal' could be added perhaps as a narrow synonym.

This is an attempt to combine the two definitions.

**Suggested definition:** The release of intracellular molecules contained within the acrosomal granule after fusion of the outer acrosomal membrane with the plasma membrane of the sperm, requiring calcium ions. The acrosomal vesicles are released either before the sperm reaches the zona pellucida or at it .


I would actually leave out the "proteolytic digestion" as it looks to me that it describes the mechanism /molecular function that facilitates the release.

The note below could be added or not...

**Note:** If the release occurs before it, penetration of the cumulus oophorus is facilitated.  The dispersal of the components at the zona pellucida allows the sperm to penetrate it and reach to the plasma membrane of the egg where the inner acrosomal membrane of the sperm can interact with it.

Please, let me know if this is fine here or if I should create a new ticket.

Thanks,

Penelope

**Comment by ukemi** [comment]
Hi @pgarmiri ,

I have two issues here. 
1) In the first request, the part_of relations cannot be created because the process does not always happen in the context of both parents. In GO the part_of relation is a necessary part_of, so when a process that is part_of another process occurs, it is always part of the parent process. The exocytosis cannot **always** be a part of both acrosome reaction and premature acrosome loss.

2) I'm a bit concerned by your request in the second part of this request. The two processes are distinguishable even though they happen at the same time. If I understand the way this works correctly, the matrix dispersal is the digestive process that takes the gel-like contents of the acrosomal matrix and converts it to a more soluble form. The exocytosis is a type of exocytosis where the acrosomal vesicle (secretory vesicle) fuses with the plasma membrane to release the contents. If the dispersal didn't take place, the contents would just be released as a blob. Please see PMID:12398221 for an account of the role of acrosin. I think the proteolytic steps that are accomplished by more than one protease should be a separate process.

**Comment by pgarmiri** [comment]
Hi @ukemi ,

I had a look at the issues you found.

1. This issue made me go back and read more about what is the current opinions of what is actually happening. It seems that the model has changed and the the cumulus zone is now considered as a normal site for AR (http://www.pnas.org/content/108/12/4892.full.pdf). That covers the cases that would go under the new term you created (premature acrosome reaction). So, it seems that what you had initially suggested for the "acrosome reaction" would have worked perfectly. Just not include the location of the release and it would cover both.

No need for the "premature acrosome reaction" terms in this case, as this is "premature" only if we consider the ZP as the only functional location.

What is under " negative regulation of acrosome reaction" would just need to changed to  GO:0045920
"negative regulation of exocytosis". That is an annotation issue.

The suggested definition for GO:0002077 ,acrosome matrix dispersal is still valid but no need to change anything with the part_of relation.

I am sorry I didn't spotted this paper earlier. It seems to be a very fast evolving area.

2. I found a review that helped me clarify where I got confused.  Buffone et al (2008) http://www.ijdb.ehu.es/web/paper.php?doi=072532mb
"In the mouse there is a temporal relationship among four stages of acrosomal exocytosis :
plasma membrane intact over the acrosome (Class 1), plasma membrane initiating fusion with outer acrosomal membrane with soluble components retained within the acrosome (Class 2), soluble acrosomal proteins lost but acrosomal matrix materials still present (Class 3), and most acrosomal components lost (Class 4) (Fig. 5). We conclude that these patterns  represent successive transitional stages leading to the complete release of acrosomal components (Kim and Gerton, 2003)."

So, what we call as  'acrosome matrix dispersal'  is the what is described as Class 3 above and 'acrosomal vesicle exocytosis' the Class 4. They are part of the same process but they occur at a particular order.  This is what you were saying as well, right?
Authors use different terminology and can be confusing...Thanks for the clarification. 

So, only the definition is to be revised to say that the plasma membrane is of the sperm not the oocyte.

**Comment by pgarmiri** [comment]
Hi @ukemi ,
Thanks @ukemi for updating the definitions!

I would really appreciate your opinion on the first point in my reply above. Would you agree to include the cumulus zone as a physiologically relevant location for the acrosome reaction?  

This is important as it is affecting the edits done for tickets
Definition Revision: GO:0007340 'acrosome reaction' #14358 and NTRs: premature acrosome loss and regulation terms of it #14345 that have been already closed.

Kind regards,
Penelope

**Comment by ukemi** [comment]
Hi @pgarmiri ,
Although the cumulus zone is relevant in some cases, I don't think it is universal. So we cannot make this restriction on the exocytosis term. Does this answer your question?
-D

**Comment by pgarmiri** [comment]
Hi @ukemi ,

Thank you very much for your reply. 

The point I was trying to figure out is if we have the right terms to capture the two different types of premature acrosome loss.

- The acrosome loss occurring at the cumulus zone that has a positive effect on fertilization.

- The acrosome loss occurring earlier than that location has a negative effect on fertilization. This loss seems to be random and the organism doesn't want it to happen and negatively regulates it to aid fertilization.

Will it be correct to use the 'regulation of premature acrosome reaction' and children for both cases?

Would the 'regulation of exocytosis' be more suitable for the second case?

Can curators can be guided to see the difference and chose the right term?

Penelope

**Comment by ukemi** [comment]
I thought we had decided that 'premature acrosome loss' was a physiological process that happens as part of normal biology in the cumulus. I would think that the latter process would be just a general negative regulation of exocytosis unless there is a special mechanism for the acrosomal vesicle.

**Comment by pgarmiri** [comment]
Yes, we did decide that but authors used the same terms for both types of premature acrosome loss. As I mentioned in a different thread (#14345), proteins that are involved in the regulation of the second type of acrosome loss has been annotated with GO:1902225 negative regulation of acrosome reaction, as the authors speak about regulation of acrosomal exocytosis.
We have the term  GO:0060478 'acrosomal vesicle exocytosis' but this part_of the physiological acrosome reaction.
It can be confusing for someone that is not very familiar with the all the details.
