### ISSUE TITLE
NTRs: distal and proximal apical dendrites

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14353]
Re: PMID:8725894, Figure 1.
Re: #13785 

Should 'GO:0097440 apical dendrite' and 'GO:0150002 distal dendrite' be synonyms?
Or should these terms be related in the ontology?

'GO:0097440 apical dendrite' has no references.

**Comment by BarbaraCzub** [comment]
The apical dendrite appears to be found predominantly in pyramidal cells and it can be either distal or proximal:
https://www.ncbi.nlm.nih.gov/books/NBK11524/
https://en.wikipedia.org/wiki/Apical_dendrite 
[PMID: 9214543](http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1096-9861(19970721)384:1%3C109::AID-CNE7%3E3.0.CO;2-5/epdf)

However, in the retina the term 'apical dendrite' is also used to describe dendrites of amacrine cells...
https://www.ncbi.nlm.nih.gov/books/NBK11539/
[PMID: 1720142](http://onlinelibrary.wiley.com/doi/10.1002/cne.903100210/epdf)

**Comment by BarbaraCzub** [comment]
IA:
Collect relevant references, and create new terms 'proximal apical dendrite' (e.g. PMID:8725894, Figure 1) and 'distal apical dendrite' (reference needed). Make these new terms children of 'apical dendrite', as well as 'proximal dendrite' and 'distal dendrite,' respectively.

**Comment by BarbaraCzub** [comment]
NTR1: apical distal dendrite
Def.: The dendrite of the dendritic tree, which emerges near the apical pole of a neuron, and which is farthest away from the neuronal cell body (the soma). PMID: 9214543, PMID: 1720142, PMID:20629984
is_a GO:0097440 apical dendrite
Is_a GO:0150002 distal dendrite

NTR2: apical proximal dendrite
Def.: The dendrite of the dendritic tree, which emerges near the apical pole of a neuron, and which is the closest to the cell body of the neuron (the soma). PMID: 9214543, PMID: 1720142, PMID:16899232
is_a GO:0097440 apical dendrite
Is_a GO:1990635 proximal dendrite

NTR3: basal distal dendrite
The dendrite of the dendritic tree, which emerges near the basal pole of a neuron (e.g. in bipolar neurons, basal dendrites are either on the same side of the soma as the axon, or project toward the axon), and which is farthest away from the neuronal cell body (the soma).
PMID: 9214543, PMID: 1720142, PMID:17046728, PMID:22683681, PMID:20629984
is_a GO:0097441 basal dendrite
Is_a GO:0150002 distal dendrite

NTR4: basal proximal dendrite
The dendrite of the dendritic tree, which emerges near the basal pole of a neuron (e.g. in bipolar neurons, basal dendrites are either on the same side of the soma as the axon, or project toward the axon), and which is the closest to the cell body of the neuron (the soma).
PMID: 9214543, PMID: 1720142, PMID:17046728, PMID:22683681, PMID:16899232
is_a GO:0097441 basal dendrite
Is_a GO:1990635 proximal dendrite

**Comment by BarbaraCzub** [comment]
cc
@RLovering 
@paolaroncaglia

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
Your suggestions all look good to me. Just a minor point, I find the comma confusing in “The dendrite of the dendritic tree, which emerges…”. If ‘emerges’ refers to dendrite, then the comma should be removed. If instead ‘emerges’ refers to dendritic tree, perhaps the sentence would read better “Any dendrite in a dendritic tree near…”.
Also, in the last two terms, the “e.g.” in parentheses may not be needed.
Thanks for your patience :-)

**Comment by BarbaraCzub** [comment]
Thanks @paolaroncaglia 
I edited the definitions to remove the confusing comma:
“Any dendrite in a dendritic tree that emerges near…”.
However, I am going to keep the "e.g." not to suggest that the term applies only to bipolar neurons (this is intended only as an example, hence the "e.g.").
