### ISSUE TITLE
Merge 'high affinity transport' (BP) into respective parents

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14354]
Hello, 

We have decided that the high/low affinity transport should not be a type of transport in the Process ontology. High/low affinity transporters should be captured in the MF with the terms 'high-affinity x transmembrane transporter activity'. 

Here are the merges to be done: 

GO ID | term label | term to be merged with  |    
-- | -- | -- | --
GO_1990821 | high affinity glucose import | Merge into  GO:0098708 glucose import across plasma   membrane | DONE
GO_0015678 | high-affinity copper ion   transport | Merge into GO:0098705 copper ion import across plasma membrane | DONE
GO_0008646 | high-affinity hexose   transport | Merge into GO:0035428 hexose transmembrane   transport |  DONE
GO:0008647 | low-affinity hexose   transport | Merge into GO:0035428 hexose transmembrane   transport | DONE
GO_0010163 | high-affinity potassium ion   import | Merge into GO:0071805 potassium   ion transmembrane transport | DONE
GO_0044749 | high-affinity zinc II ion   transmembrane import | Merge into GO:0071578  zinc II ion transmembrane import | DONE
GO_0006830 | high-affinity zinc II ion   transport | Merge into GO:0071578  zinc II ion transmembrane import | DONE
GO:0006831 | low-affinity zinc II ion   transport | Merge into GO:0071578  zinc II ion transmembrane import | DONE
GO:0080055 | low-affinity nitrate transport | Merge into GO:0015706 nitrate   transport  | DONE
GO_0006827 | high-affinity iron ion   transmembrane transport | Merge into  GO:0034755 iron ion transmembrane transport |  DONE
GO_0000040 | low-affinity iron ion   transmembrane transport | Merge into  GO:0034755 iron ion transmembrane transport |  DONE
GO_0015683 | high-affinity ferric iron transmembrane transport | Rename ferric iron   transmembrane transport | DONE
GO_0061839 | high-affinity ferrous ion transmembrane transport | Rename ferrous ion   transmembrane transport | DONE

Thanks, Pascale

**Comment by RLovering** [comment]
Please could high-affinity ferric iron transmembrane transport be renamed ferric iron transmembrane transport

And high-affinity ferrous iron transmembrane transport be merged into GO:1903874 ferrous iron transmembrane transport

Note we currently have the terms
 ferric iron transport and ferrous iron transport although unfortunately GO:0061839 high-affinity ferrous ion transmembrane transport did not have ferrous iron transmembrane transport  as a parent.

The transport of the ferric and ferrous ions is by different systems and it would be good to keep this distinction.

Thanks

Ruth
