### ISSUE TITLE
Obsoletions: translation regulator activity and children

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#1435]
There are some horrible terms under 'translation regulator 
activity', and I don't believe any of them are true functions. 
Many are defined to sound like proteins and are defined by 
being involved in a certain process.

If you have any comments or other suggestions for 
alternatives, please add them; otherwise I will obsolete 
these terms after returning from the GO meeting.

Those terms in full:
translation regulator activity ; GO:0045182
Any substance involved in the initiation, activation, 
perpetuation, repression or termination of polypeptide 
synthesis at the ribosome.
--&gt;translation ; GO:0043037

translation factor activity, non-nucleic acid binding ; GO:
0045183
Any of a group of soluble proteins involved in polypeptide 
synthesis at the ribosome which do not bind to nucleic 
acids.
--&gt;translation ; GO:0043037

translation factor activity, nucleic acid binding ; GO:
0008135
Functions during translation by binding nucleic acids during 
polypeptide synthesis at the ribosome.
--&gt;translation ; GO:0043037, nucleic acid binding ; GO:
0003676

translation activator activity ; GO:0008494
Any of a group of soluble proteins functioning in the 
activation of ribosome-mediated translation of mRNA into a 
polypeptide.
--&gt;positive regulation of translation ; GO:0045946

translation elongation factor activity ; GO:0003746
Functions in chain elongation during polypeptide synthesis 
at the ribosome.
--&gt;translational elongation ; GO:0006414

translation initiation factor activity ; GO:0003743
Functions in the initiation of ribosome-mediated translation 
of mRNA into a polypeptide.
--&gt;translational initiation ; GO:0006413

translation termination factor activity ; GO:0008079
Functions in the termination of translation.
--&gt;translational termination ; GO:0006415

translation release factor activity ; GO:0003747
Involved in catalyzing the release of a nascent polypeptide 
chain from a ribosome.
--&gt;translational termination ; GO:0006415

translation release factor activity, codon nonspecific ; GO:
0016150
A translation release factor that is not specific to particular 
codons; binds to guanine nucleotides.
--&gt;translational termination ; GO:0006415, guanine 
binding ; GO:0050NEW

translation release factor activity, codon specific ; GO:
0016149
A translation release factor that is specific for one or more 
particular termination codons; acts at the ribosomal A-site 
and require polypeptidyl-tRNA at the P-site.
--&gt;translational termination ; GO:0006415, ribosome 
binding ; GO:0043022

translation repressor activity ; GO:0030371
Antagonizes ribosome-mediated translation of mRNA into a 
polypeptide.
--&gt;negative regulation of translation ; GO:0016478

translation repressor activity, non-nucleic acid binding ; GO:
0000901
Antagonizes the ribosome-mediated translation of mRNA 
into a polypeptide but does not bind directly to nucleic acid.
--&gt;negative regulation of translation ; GO:0016478

translation repressor activity, nucleic acid binding ; GO:
0000900
Antagonizes the ribosome-mediated translation of mRNA 
into a polypeptide via direct binding to nucleic acid.
--&gt;negative regulation of translation ; GO:0016478, 
nucleic acid binding ; GO:0003676

Reported by: girlwithglasses

Original Ticket: "geneontology/ontology-requests/1438":https://sourceforge.net/p/geneontology/ontology-requests/1438

**Comment by linuxlovell** [comment]
thanks www.movied.org

**Comment by pgaudet** [comment]
As of today, there are only 111 manual annotations.

**Comment by ValWood** [comment]
We have 4 annotations and would be very happy for this to go away.
In fact I will reannotate now to:

byr4 MF mRNA binding involved_in  BP positive regulation of cytoplasmic translation
ppr4 MF mRNA binding involved_in  BP positive regulation of mitochondrial  translation
puf6  mRNA 3'-UTR binding   BP negative regulation of cytoplasmic translation
mss51 MF none  BP positive regulation of mitochondrial  translation
and block this internally. It has no meaning other than "regulation of translation"

**Comment by ValWood** [comment]
Actually PAscale that isn't everything.

Although we only have 4 annotations to "translation regulator" we have 7 to "translation release factor" so there must be some "missing parents"

Probably need to reevaluate annotation numbers before proceeding.

**Comment by ValWood** [comment]
This one is housed under 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003747
"translation factor activity RNA binding"

so would need to count these.
Anything with "factor" in the term name.
https://github.com/geneontology/go-ontology/issues/13536

**Comment by pgaudet** [comment]
Nice review here: PMID:28363112
We'll wait to have done more progress on transcription to make sure these two branches are consistent with each other.

**Comment by ValWood** [comment]
This has been delt with by recent tickets @pgaudet reopen if you disagree
