### ISSUE TITLE
NTR: positive regulation of GO:0045505 dynein intermediate chain binding

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14361]
Figure 6a in PMID:17139249 demonstrates that GSK3beta (P49841) is required for binding of BICD1 (Q96G01) to dynein intermediate chains.

NTR: positive regulation of GO:0045505 dynein intermediate chain binding

Refs:
PMID:17139249
GOC:aruk
GOC:bc

**Comment by pgaudet** [comment]
Hello, 

Can we discuss about creating these types of terms ? 
There is already some debate as to whether protein binding is really useful; regulation of protein binding seems even more dubious. 

Figure 6a seems to indicate a role as a molecular adaptor for GSK3 beta in this case. Would the term 'protein binding, bridging' be suitable ? 

Thanks, Pascale

**Comment by ukemi** [comment]
I have put it as a discussion point for an ontology call, but I tend to agree that these terms are isolated with respect to the greater biological context.

**Comment by ValWood** [comment]
essentially
Phosphorylation of BICD1 by GSK-3β is essential for the radial array formation of microtubules

We annotate a lot of this scenario as:

protein A has_substrate protein B part_of  "regulation of process x"
protein B (phosphorylated form ID) binds protein C part_of  "process x"

in this case 
protein kinase GSK3beta phosphorylates  BICD1 involved in...
 BICD1 (phosphorylated form ID) binds dynein  involved in...

(not sure if its bridging here , unlikely to bind simultaneously?)

**Comment by BarbaraCzub** [comment]
The experiment does not show that GSK3beta phosphorylates BICD1 directly, therefore, rather than saying it regulates it, this should be captured in a GO-CAM model using the causally_upstream_of_or_within relation.

**Comment by BarbaraCzub** [comment]
Actually Figure 7 then shows that GSK3beta phosphorylates BICD1 directly, therefore, this should probably be 'regulates' after all.

**Comment by BarbaraCzub** [comment]
#14360
