### ISSUE TITLE
Do we have to hard-code CC [complex terms] to MF and BP relationships in the ontology? 

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14375]
Follow-up from GOC meeting in Cambridge 2017:

Rational: We use these as logical extensions for automatic grouping.

Related:
https://github.com/geneontology/go-ontology/issues/14374

**Comment by bmeldal** [comment]
We need to answer:

Would we hard-code protein X binding terms? https://github.com/geneontology/go-ontology/issues/11989

**Comment by bmeldal** [comment]
We discussed this for a while yesterday (30/11/17) and the overwhelming opinion was that it's useful to hard-code the relationships as long as we are sure they are always true.

There might be some issues with propagation to GPs* but there's a workaround in Protege (@tberardini).
* for GPs that are members of more than one complex

hard-coded relationships are:
is_a [x complex]
part_of [cellular location]
capable_of [molecular function] *
capable_of_part_of [biological process]

*
- we agreed that capable_of [activity] was no problem
- we discussed for a while the pros and cos of adding binding relationships. Some, like DNA binding terms would definitely be helpful (e/g/ for transcription factors) but the benefit of adding thinks like ATP binding, proton binding etc was clear to us. I, Birgit, know that people search for interactions with small molecules in IntAct as i always get the questions in training courses. But we can capture this with annotations as well.

Action:
 - [ ] Birgit to check with @RLovering and @ValWood to see if they know if users search for complexes that are annotated to "binding [small molecules]". Val and Ruth, please comment below :)

**Comment by pgaudet** [comment]
@thomaspd and I would like to discuss this on an ontology call.

**Comment by krchristie** [comment]
**4/23/18 ontology developers call** - We mentioned this briefly, primarily to indicate that this is a topic for the protein complexes WG, and that interested parties should attend that call immediately after this one.

**4/23/18 protein complexes WG call** - Karen agreed to present some idea about how keeping these relationships in the ontology is useful and could help us put existing "old school" annotations into models.

**Comment by bmeldal** [comment]
23/4/18: briefly discussed.
@krchristie and Birgit to present use cases on the next call

**Comment by ValWood** [comment]
At present in PomBase we don't enable retrieval of list of complexes as such (although we generate a file with this data). 

In our query tool, you can only query on genes which are members of complexes, of genes that bind specific small molecules (both of these are useful).

You could not then get a list of "complexes which bound to ATP" from PomBase. You could only get a list of gene products which "bind ATP" and are "members of complexes". This is because we do not currently have "complex objects" where we can hang every annotation that  refers to a complex.

In the future we plan to do that, but it isn't high up our list  because users have not asked for it. It would certainly be useful to be able to see a page with all the annotations for a complex (especially  to  easily see where complex members  phenocopy each other, or when annotated processes agree). This is possible, but  
only by querying on individual complexes and phenotypes.

That isn't really what you asked, but I don't see a huge benefit in Intact doing much at the GO level with these binding terms, because it's an area that is well covered and the gene product level annotation. SPKW and InterPro are good for these terms because they tend to be amenable to annotation transfer based on sequence similarity.

**Comment by hdrabkin** [comment]
If there is a meeting of the WG now will someone please send the link to Karen and myself???

**Comment by deustp01** [comment]
And me?
Peter

**Comment by vanaukenk** [comment]
Hi,


On the GO's Google calendar, this link is listed for today's meeting at 3pm EDT:


https://stanford.zoom.us/j/976175422


--Kimberly


________________________________

**Comment by bmeldal** [comment]
Yes, Kimberly, that’s the one.
Speak shortly.

**Comment by bmeldal** [comment]
Summary from call on 9th May 2018:

@vanaukenk @deustp01 @sandraorchard @pgaudet @hdrabkin @krchristie @ValWood @tberardini 

1. Karen - small nucleolar RNP complexes

The LDs helped her find the right complex especially where the text def was insufficient:

![image](https://user-images.githubusercontent.com/10517124/39857801-8c59d7f0-542c-11e8-9be3-5cc1188ac201.png)

- Box H/ACA snoRNP complex was generic term until box H/ACA RNP complex parent term was created: LDs where added for new and existing terms but def of old term was not updated.

![image](https://user-images.githubusercontent.com/10517124/39857759-73bfc59c-542c-11e8-9a10-c7965d755dba.png)

- Processes provide the best distinction between these 3 sibling terms because subunits are shared to some extend --> MF annotations are inconclusive and CC incomplete but BP show a clear pattern.

2. Harold:

- 3 examples of increasingly specific LDs that match the text def.
- found one example where text def has more info which showed where LD could be improved

![image](https://user-images.githubusercontent.com/10517124/39858298-0b59b650-542e-11e8-9770-934d466583be.png)

3. Birgit

- uses the LDs to find correct complex
- utilises exisisting LDs to bring in child terms for new intermediate grouping terms in the ontology, e.g. added "catalytic complex" and all complexes that had "capable_of catalytic activity" as LD were brought in automatically. TG complex-from-activity- template used to show this beautifully.

Summary:

We have good use cases for keeping the LDs in the ontology for now.

Hard-coded logical defs are helpful to:
- classify annotations
- identify which one of related complexes is appropriate
- if the logical defs are the same Travis will flag this up - indication that the complex might already exist
- Mining tools stumble over free text but could utilised the LDs.

To make it even more usable:
- text defs should match logical defs with extra info in text that can't be captured by logical defs
- could we add the LD lines to the top box in AMIGO2 (Karen says yes) and QuickGO (@tonysawfordebi ?)
- should the taxon-specific comments (E.g. In mammals blah blah blah [composition or specific location etc] and in yeast blah blah blah [composition or specific location etc]) be moved to the comments field? Not all viewers show that field.
- Could we autocreate text defs from LDs? Mary has a script that she used for a different project and it works except for some funny grammar.

**Comment by pgaudet** [comment]
* **ACTION ITEM from NYC 208 GOC:** Review the CC ontology to determine if there are new terms needed, e.g., especially wrt specialized domains in the plasma membrane, that would allow more accurate annotation of important functional locations in CCs.

**Comment by bmeldal** [comment]
Timeline needed. I suggest April 2019 mtg in CB as I probably won't be at the autumn mtg.

**Comment by pgaudet** [comment]
@bmeldal I changed the milestone. Feel free to change all other tickets for this project. 

Thanks, Pascale

**Comment by bmeldal** [comment]
From call on 13/2/19:

Discussion on use of subclasses vs logical definitions. Several curators make use of them (see examples above) but it's not clear if SCs or LDs are more appropriate for our use cases. We think relationships requested via TG (old!) and GitHub are going in as SCs.

**Actions:**

- [ ] clarify ontology history of usage. @ukemi can you help?
- [ ] where/how in the ontology are these relationships used? Some examples above in my comment from 9th May 2018.
- [ ] what are the objections to having such relationships in the ontology altogether? @thomaspd

**Comment by cmungall** [comment]
The general rule throughout the ontology is that we should have a logical def if the text def can clearly be axiomatized

```
id: GO:0000118
name: histone deacetylase complex
def: "A protein complex that possesses histone deacetylase activity." [GOC:mah]
```

The text def here predated the logical def, yet it is virtually a logical def. Insofar as we have this term in the ontology with this text def, it should have a logical def that reflects it. We can discuss whether we really need HDAC complex as a grouping at all, or whether there is maybe an alternate text def that is structural or phylogenetic, but that's orthogonal.

**Comment by bmeldal** [comment]
25/2/19 Call action: Decide if we want to keep subclasses and/or logical defs and how do we standardise them.

**Comment by bmeldal** [comment]
From call on 25th Feb 2019:

Present: Birgit, Harold, Ruth, Thomas Hayman, Kimberly, Darren, Peter, Suzie, Judy, Edith, Helen, Val

1. We feel that logical defs (LDs) are useful for automatically inferred intra-ontology links. These are used by several people for various purposes (see examples above, 10th May 2018) and we are not clear about the strong objections voiced by a few people at previous meetings.

NB: LDs must be **necessary and sufficient** to define a term as a unique term/class. Subclasses don't have that definition.

Questions: 
- Can we convert the existing subclasses to LDs to make them truly useful?
- What do we do with complexes that cannot be uniquely defined? They are potentially placed in the ontology as direct child of *GO:0032991 protein-containing complex*.

e.g. STING complex:
*is_a* GO:0098796 membrane protein complex
*part_of* GO:0030659 cytoplasmic vesicle membrane
*capable_of* GO:0098546 2',5-3',5'-cyclic GMP-AMP binding
*capable_of* GO:0060340 positive regulation of type I interferon-mediated signaling pathway [should it be capable_of_part_of as it's a BP ???]
*capable_of_part_of* GO:0045087 innate immune response 

These relationships probably aren't unique to the STING complex so wouldn't hold true for a LD. But people need the term to annotate the GP [Q86WV6](https://www.uniprot.org/uniprot/Q86WV6) TMEM173 (STING) to it.

Judy and Darren suggested to use PRO as it can provide LDs based on components and species but it has no integration with GO for analysis tools...

**Action:**
- continue discussion on next call.

See also https://github.com/geneontology/go-ontology/issues/15875

**Comment by bmeldal** [comment]
From @hattrill 
If we make a 'unique logical definition set' rule, we need to discuss what happens to well-defined complexes that have the same logical definition - chromatin remodeling complexes spring to mind (e.g. Brahma complexes, Ino80 complex, ISWI-type complexes - all nuclear, ATPase, chromatin remodeling.

**Comment by bmeldal** [comment]
Cambridge GOC meeting, 11/4/19:
Keep complexes in GO.

Closing this ticket as any further discussion has moved to https://github.com/geneontology/go-ontology/issues/15875
