### ISSUE TITLE
incomplete def GO:0043039 and descendants

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#14373]
The definition of tRNA aminoacylation (GO:0043039) looks incomplete. It contains

"... by the formation of an ester bond between the 3'-hydroxyl group of the most 3' adenosine of the tRNA ..." 

but does not mention the part of the amino acid involved in forming the bond.

Two of the is_a GO:0043039 terms, GO:0006418 and GO:0043040, have the same definition problem.

**Comment by pgaudet** [comment]
Hi @mah11 

The definitions of all the terms in that part of the GO look very similar to me. Can you include the information you think is missing and give an example of a term where you think the definition is correct ? 

Thanks, Pascale

**Comment by mah11** [comment]
I have not found a term where the definition looks complete. I have already included a general description of the missing information. Off the top of my head I do not remember the specific bond chemistry that would be required to complete the definitions, and I am not more (nor, admittedly, less) capable of looking it up than any active GO editor.

Before I spend time doing so, perhaps first ask @hdrabkin if he knows without having to look it up.

**Comment by hdrabkin** [comment]
I can add the info.

**Comment by mah11** [comment]
Thanks, Harold - I was hoping I wouldn't have to dredge up undergrad biochemistry!

**Comment by hdrabkin** [comment]
I've added "and the alpha carboxylic acid  group of an amino acid" to a couple terms, and will alter the def of the amino acid specific children. This bit: "to either the 2'- or the 3'-hydroxyl group of the 3'-adenosine residue of the tRNA is NOT true for all of them. It's either one or the other and I need to look up which ones are which.

**Comment by hdrabkin** [comment]
So I need to edit these based on enzyme class:
    Class I synthetases aminoacylate at the 2'-OH of a terminal adenosine nucleotide on tRNA, and it is usually monomeric or dimeric (one or two subunits, respectively).
    Class II aminoacylates at the 3'-OH of a terminal adenosine on tRNA, and is usually dimeric or tetrameric (two or four subunits, respectively). 
But phenylalanine-tRNA synthetase is class II, yet aminoacylates at the 2'-OH.

Regardless of where the aminoacyl is initially attached to the nucleotide, the 2'-O-aminoacyl-tRNA will ultimately migrate to the 3' position via transesterification.

**Comment by hdrabkin** [comment]
arginine, cysteine, glutamic acid, glutamine, isoleucine, leucine, methionine, tyrosine, tryptophan and valine belong to class I synthetase: all to 2'OH preferentially 
 alanine, asparagine, aspartic acid, glycine, histidine, lysine, phenylalanine, proline, serine, and threonine belong to class-II synthetases, get put on 3'OH except phe gets put on 2'OH

**Comment by hdrabkin** [comment]
Tweaked defs; closing
