### ISSUE TITLE
Rename or merge GO:0015563 uptake transmembrane transporter activity and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14372]
Following up on #14322 

GO ID | Term | Action
-- | -- | --
GO:0015563 |  uptake transmembrane transporter activity |  Merge into GO:0022857 transmembrane transporter activity (**No annotations, no InterPro mappings**) 
GO:0005274 | allantoin uptake transmembrane   transporter activity  | rename allantoin secondary transmembrane   transporter activity
GO:0080138 | borate uptake transmembrane   transporter activity  |  merge into GO:0046715 borate   transmembrane transporter activity (since **protein annotated by TAIR**   @tberardini - annotated to both terms)
GO:0015088 | copper uptake transmembrane   transporter activity | merge into GO:0005375 copper ion transmembrane transporter activity - **EXP annotations**: SGD:S000006328; SGD:S000004403; SGD:S000001218; TAIR	TAIR:locus:2049113; CGD	UniProtKB:Q59NP1; TAIR	TAIR:locus:2133965; SGD	SGD:S000000855; RGD	RGD:620059; MGI	MGI:MGI:1333843; FlyBase	FB:FBgn0062413; FlyBase	FB:FBgn0062412; EcoCyc	UniProtKB:P0A8H3; CGD	CGD:CAL0000196962
GO:0015639 | ferrous iron uptake transmembrane   transporter activity | merge into  GO:0015093 ferrous iron transmembrane transporter activity - **single EXP annotation** P49281 (Swiss-Prot) 
GO:0015659 | formate uptake transmembrane   transporter activity | merge into GO:0015499 formate transmembrane transporter activity Single annotation Slc26a6 MGI
GO:0015092 | high-affinity ferric iron uptake   transmembrane transporter activity | Renamed high-affinity ferric iron transmembrane transporter activity - Removed x-reference to http://www.tcdb.org/search/result.php?tc=9.A.10.1.1 as this entry does not mention iron transport - **No annotations**
GO:0061840 | high-affinity ferrous iron uptake   transmembrane transporter activity | Renamed remove uptake - **Single annotation** Pombase fip1, also annotated to BP iron import 
GO:0000006 | high-affinity zinc uptake   transmembrane transporter activity | Renamed remove uptake - **3 EXP annotations** ZRT1 SGD:S000003224, Zrt1 PomBase:SPBC16D10.06, ZnuB UniProtKB:P39832	 EcoCyc
GO:0015318 | inorganic solute uptake   transmembrane transporter activity **TO DO**: request to obsolete | There were no objection to obsoletion; however I found the ChEBI term 'inorganic molecular entity' that seemed a better description. Renamed term. // Add DO NOT ANNOTATE flag
GO:1901549 | malonic acid uptake transmembrane   transporter activity | merge into GO:1901239 malonate(1-) transmembrane transporter activity - **Single annotation** Pombase mae1 
GO:0015638 | microcin uptake transporter activity |  Rename microcin transmembrane transporter activity & fix definition - Single annotation sbmA P0AFY6 EcoCyc
GO:0015513 | nitrite uptake transmembrane   transporter activity | Renamed high-affinity secondary active nitrite transmembrane transporter activity based on existing parent (secondary active) and annotations (to proteins named high-affinity transporter) & Fixed logical definition - **EXP annotations** to 8 proteins: AspGD:ASPL0000073089 (AspGD), AspGD:ASPL0000056693 (AspGD), AspGD:ASPL0000060467(AspGD), AspGD:ASPL0000056693   (AspGD),  UniProtKB:Q5AST3 (AspGD), UniProtKB:P22152 (AspGD), UniProtKB:G5EB18  (AspGD), UniProtKB:P10903 (EcoCyc), UniProtKB:P0AC26 (EcoCyc).
GO:0015558 | p-aminobenzoyl-glutamate uptake transmembrane transporter activity | Merge *parent*     GO:0015569   p-aminobenzoyl-glutamate transmembrane transporter activity (no annotation) into GO:0015558 **Single annotation** P46133 EcoCyc - See https://github.com/geneontology/go-annotation/issues/1672, renamed secondary active p-aminobenzoyl-glutamate transmembrane transporter activity, added missing parent and updated definition
GO:0015544 | phenyl propionate uptake uniporter   activity| No annotations, rename phenyl propionate uniporter activity
GO:0015388 | potassium uptake transmembrane   transporter activity | Merge into GO:0015079 potassium ion transmembrane transporter activity - **4 EXP annotations:**  PomBase:SPAC3F10.02c, UniProtKB:P0AFZ7 EcoCyc,  UniProtKB:P23849	(CACAO + EcoCyc). **Consider annotating** to the BP     GO:1990573  potassium ion import across plasma membrane
GO:0015541 | secondary active cyanate uptake   transmembrane transporter activity | No annotations. Renamed remove uptake
GO:0015636 | short-chain fatty acid uptake   transporter activity | 1 EXP annotation Q8IVM8 Swiss-Prot Merge  *parent*     GO:0015635   short-chain fatty acid transporter activity (No annotations) into GO:0015636 &   rename TM transporter activity
GO:0015344 | siderophore uptake transmembrane   transporter activity | **TO DO** Merge into parent GO:0015343 siderophore transmembrane transporter activity 15 EXP annotations: SGD:S000000791	SGD, PseudoCAP:PA2466	PseudoCAP, PseudoCAP:PA0931	PseudoCAP, PseudoCAP:PA4156	PseudoCAP, PseudoCAP:PA2688	PseudoCAP, PseudoCAP:PA4675	PseudoCAP, PseudoCAP:PA1912	PseudoCAP, UniProtKB:Q9HVC0	PseudoCAP, UniProtKB:Q9I527	PseudoCAP, UniProtKB:Q9HWM5	PseudoCAP, UniProtKB:Q9I116	PseudoCAP, UniProtKB:Q9I2J2	PseudoCAP, UniProtKB:Q05098	PseudoCAP, UniProtKB:P06972	EcoCyc, #UniProtKB:P07821	EcoCyc
GO:0015654 | tellurite uptake transmembrane   transporter activity | Merge *parent* GO:0015118  (No annotations) into GO:0015654 - 2 EXP annotations: P32705 and P0AFJ7 (both EcoCyc)
GO:0015403 | thiamine uptake transmembrane  transporter activity |  Merge into parent     GO:0015234  thiamine transmembrane transporter activity (8 EXP)  **3 EXP** MGI:MGI:1931307	(BHF), MGI:MGI:1928761	 (BHF), and UniProtKB:O60779 (GOA)

When appropriate, changed definitions as recommended here: http://wiki.geneontology.org/index.php/Transporter_terms_standard_definitions#Other_standard_definitions

**Comment by ValWood** [comment]
Fine with the merge.  Anything with uptake has a process describing import.

**Comment by pgaudet** [comment]
Obsoletion notice sent 
Dear all, 


The proposal has been made to obsolete 'GO:0015318 inorganic solute uptake transmembrane transporter activity’

The reason for obsoletion is that is a grouping term that does not correspond to any ChEBI class, so that it currently has no children. Moreover, 'inorganic solute’ is probably not that useful as a grouping class for transporters. Please add any comments to the issue: https://github.com/geneontology/go-ontology/issues/14372

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Nov 6, 2017. Unless objections are received by Nov 6,2017, we will assume that you agree to this change.


Thanks, Pascale
