### ISSUE TITLE
At what level do we want to include complexes in the ontology?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14374]
Follow-up from GOC meeting in Cambridge 2017:

1. We need complex classes for grouping
2. We used to make compositionally specific terms but have stopped. We make only functional grouping terms related to ACTIVITIES not BINDING (although that can sometimes be rather tricky to elucidate!) or general SUBCELLULAR LOCATIONS (e.g. plasma membrane complex). 

related: 
Relations to describe gene product - component annotation
https://github.com/geneontology/go-annotation/issues/1639
inferring MFs from annotations to complex portal IDs to individual complex participants
https://github.com/geneontology/go-annotation/issues/1662

**Comment by bmeldal** [comment]
@thomaspd this is the ticket to discuss the function vs composition for complex defs from https://github.com/geneontology/go-ontology/issues/14411

Can we have a working group call on this subject soon, @vanaukenk @ukemi @pgaudet? I'm sending an email to the GOC in a moment.

**Comment by pgaudet** [comment]
Can we plan a call in December ? (after Thanksgiving). @bmeldal would you please set up a Doodle ? 

Thanks! Pascale

**Comment by bmeldal** [comment]
Here's the doodle, sent via GOC-consortium email a couple of days ago:
https://doodle.com/poll/aq62ktyd4xyngae2#table
but with dates in Nov, next Thu looking good already.

**Comment by bmeldal** [comment]
We agreed yesterday (30/11/17) to stick to our current rules as described above and in the wiki:
http://wiki.geneontology.org/index.php/Guidelines_on_%27protein_complex%27_terms

There will always be exceptions, like the above quoted case of RPB4/7 complex (#10931) that require specific terms.
