### ISSUE TITLE
imports/ncbitaxon_import.owl is incomplete, lacks pombe

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14378]
It looks like the module is only being made for only_in closure, not never_in

**Comment by ukemi** [comment]
There may be another ticket about this that I opened a while ago, but I can't seem to locate it at the moment. I thought it was one that had resulted from a query by @ValWood .

**Comment by ukemi** [comment]
Should fix this one #14192 too??

**Comment by balhoff** [comment]
This has been fixed.
