### ISSUE TITLE
add  'thiamine import across plasma membrane.

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14371]
Hello, 

For issue 
https://github.com/geneontology/go-ontology/issues/14322

I would like to rename 'GO:0071934 thiamine transmembrane transport' to 'thiamine import across plasma membrane. 

As far as I can see it's consistent with existing EXP annotations (2 different proteiny by pombase, @ValWood ):  bsu1 and thi9. 

@RLovering You can then use this term to annotate the following proteins
UniProtKB Q99PL8 Slc19a3 enables GO:0015403 thiamine uptake transmembrane transporter activity 
UniProtKB Q9EQN9 Slc19a2 enables GO:0015403 thiamine uptake transmembrane transporter activity 
UniProtKB O60779 SLC19A2 enables GO:0015403 thiamine uptake transmembrane transporter activity 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale,

I think you should keep this term as transmembrane transport, to cover movement between other compartments e.g:
http://preview.pombase.org/gene/SPBC1604.04

If you create a new term for plasma transmembrane import, I will move our EXPs to the new term.

Val

**Comment by ValWood** [comment]
This is where I got the mitochondrial one, it does exist but it is not specifically annotated...
http://www.uniprot.org/uniprot/P53257

**Comment by pgaudet** [comment]
SPBC1604.04 is already annotated to 'mitochondrial thiamine pyrophosphate transmembrane transport'; what do you want to annotate this to then ?

**Comment by ValWood** [comment]
I want to keep it...ignore.

as long as 
'GO:0071934 thiamine transmembrane transport'  doe not merge to 'thiamine import across plasma membrane.

(it was only an explanation why there is no other EXP to GO:0071934 thiamine transmembrane transport)

**Comment by ValWood** [comment]
I.e my source
http://www.uniprot.org/uniprot/P53257

should be annotated to 
 'mitochondrial thiamine pyrophosphate transmembrane transport';

mitochondrial transport Source: GO_Central
thiamine pyrophosphate transport Source: SGD

(PomBase ISS is correct, but  unsupported)

**Comment by ValWood** [comment]
action 
create
thiamine import across plasma membrane

**Comment by ValWood** [comment]
GO:1990545 | mitochondrial thiamine pyrophosphate transmembrane transport
-- | --
