### ISSUE TITLE
problem def GO:0097466 - ubiquitin-dependent glycoprotein ERAD pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14384]
GO:0097466 - ubiquitin-dependent glycoprotein ERAD pathway

Definition | Parents
-- | --
An ERAD pathway whereby endoplasmic reticulum (ER)-resident glycoproteins are targeted for degradation. Includes differential processing of the glycoprotein sugar chains, retrotranslocation to the cytosol and degradation by the ubiquitin-proteasome pathway. A glycoprotein is a compound in which a carbohydrate component is covalently bound to a protein component.

2 things
1. I don't think this only applies to resident ER proteins does it? maybe it does...
2. Shouldn't this say 

An ERAD pathway whereby *terminally misfolded* endoplasmic reticulum (ER)-resident glycoproteins

is a child of
response to glycoprotein
should that be misfolded glycoprotein?

**Comment by vanaukenk** [comment]
@ValWood  

How about this for a new definition:

An ERAD pathway whereby terminally misfolded glycoproteins are targeted for degradation.  In this pathway, terminally misfolded glycoproteins undergo removal, or trimming, of sugar chains, retrotranslocation from the endoplasmic reticulum to the cytosol, and degradation by the ubiquitin-proteasome pathway.  A glycoprotein is a compound in which a carbohydrate component is covalently bound to a protein component.

I can also reate a new 'response to misfolded glycoprotein' term as a parent for GO:0097466.

How important, though, do you think the 'terminally misfolded' aspect is?  Should the new term instead be named 'response to terminally misfolded glycoprotein'?

For the gene products that are currently annotated to this term, it seems the 'terminally misfolded' part is critical, i.e. these gene products are only active once there's no longer any potential for re-entry of the glycoprotein into the productive folding pathway,

**Comment by ValWood** [comment]
Completely coincidentally we got a curation session related to this today.

The author would like a new term

endoplasmic reticulum quality control of glycoprotein folding

The endoplasmic reticulum quality control of glycoprotein folding is a process that ensures that only corrected folded proteins stay in the ER and pursue their way in the secretory pathway (for a review see D'Alessio et al 2010 Semin Cell Dev Biol. 21, 491-9) . This process is related with N-glycosylation and N-glycan processing in the ER and involves a number of genes including calnexin, UGGT, glucosidase  and glucosidase II, among others. 

The ERAD pathway (Endoplasmic reticulum glycoprotein associated degradation) is a process that occurs when the previous mechanism has failed: irreversibly misfolded glycoproteins are retrotranslocated to the cytosol and degraded in proteasomes. So "endoplasmic reticulum quality control of glycoprotein folding" could include ERAD but not the other way around

So....it seems we have conflated endoplasmic reticulum quality control of glycoprotein folding
and ERAD!

**Comment by vanaukenk** [comment]
Hi @ValWood --

For the new term request, what do you think of adding:

GO: protein folding in endoplasmic reticulum
-GO:new glycoprotein folding in endoplasmic reticulum

and annotating gene products like calnexin, UGGT, and the glucosidases to that new term.

The mannosidase and gene products acting downstream of that, such as the EDEMs, would then be annotated to the ERAD term. 

Here's another attempt at refining the ERAD definition:

An ERAD pathway whereby terminally misfolded glycoproteins are targeted for degradation. In this pathway, terminally misfolded glycoproteins undergo demannosylation, retrotranslocation from the endoplasmic reticulum to the cytosol, and degradation by the ubiquitin-proteasome pathway. A glycoprotein is a compound in which a carbohydrate component is covalently bound to a protein component.

**Comment by ValWood** [comment]
I think we should capture that this is a "quality control" pathway.

The pathway is particularly sensing whether the proteins are folded correctly? 
and refolding if necessary.

"The endoplasmic reticulum quality control of glycoprotein folding is a process that ensures that only corrected folded proteins stay in the ER"

Can we use the term name the author suggested
"endoplasmic reticulum quality control of glycoprotein folding"

makes this clearer.
v

**Comment by ValWood** [comment]
ER glycoprotein folding and quality control 
Glycoprotein folding, detection and refolding of  misfolded glycoprotein

(the folding and the quality control are not really separable  processes because they happen cyclically until the folding is correct, or the glycoprotein terminally misfolded)

See
https://www.ncbi.nlm.nih.gov/books/NBK1958/

**Comment by vanaukenk** [comment]
@ValWood 

Okay, so I will add the term with the following parentage:

GO:0034975 protein folding in endoplasmic reticulum
-GO:new endoplasmic reticulum quality control of glycoprotein folding

For a definition, can we use this variation on your earlier post:

"A process that ensures that only corrected folded proteins stay in the ER and pursue their way in the secretory pathway . This process is related with N-glycosylation and N-glycan processing in the ER and involves a number of genes including calnexin, UGGT, glucosidase and glucosidase II, among others."

One reference could be this review: D'Alessio et al 2010 Semin Cell Dev Biol. 21, 491-9
What is the PMID for the paper that your user is curating?  I can add that as a reference, as well.

I will also update the ERAD definition.

Note that we also have this term in the ontology:

GO:0006515  protein quality control for misfolded or incompletely synthesized proteins
Definition: The chemical reactions and pathways resulting in the breakdown of misfolded or attenuated proteins. Source: GOC:jl

In this case, it seems that 'protein quality control' is strictly referring to the breakdown of misfolded proteins, which is consistent with the parentage for this term that includes 'proteolysis'.

Perhaps GO:0006515 should be renamed to more accurately reflect its definition.

I think we are now again touching on some of the issues in #13717 .......

**Comment by ValWood** [comment]
sounds good.

other paper is PMID:27587357

**Comment by ValWood** [comment]
Re
GO:0006515 protein quality control for misfolded or incompletely synthesized proteins
Definition: The chemical reactions and pathways resulting in the breakdown of misfolded or attenuated proteins. Source: GOC:jl

Aren't all of the descendant terms protein quality control pathways though?

The part which needed splitting out was the "quality control of folding" which  precedes identification clearance of terminally misfolded (ERAD). These are all still protein quality control mechanisms though?.

Note that this term only has 27 direct annotation and some of these seem a little odd. I would make this term "not for direct annotation", to clean these up....

**Comment by ValWood** [comment]
I just spotted
https://www.ebi.ac.uk/QuickGO/term/GO:0044322
might be useful here.

**Comment by ValWood** [comment]
Hi Kimberley,

Would it be possible to push these fixes  through fairly soon? I just had an expert in this area  send to our helpdesk that there were no terms for quality control of glycoprotein folding:

I think these suggestions will fix this issue and  I really want to get this one curated
https://github.com/pombase/website/issues/1127


Val

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-ontology/issues/20914
