### ISSUE TITLE
sterol transport incorrectly defined

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14382]
sterol transport is defined

The directed movement of sterols into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Sterols are steroids with one or more hydroxyl groups and a hydrocarbon side-chain in the molecule.

However I think transport of sterols is largely vesicle-mediated-  (i.e trafficking?)

See for example description of NPC2 at SGD
https://www.yeastgenome.org/locus/YDL046W
Sterol transport protein and functional homolog of human NPC2/He1; human NPC2 is a cholesterol-binding protein whose deficiency causes Niemann-Pick type C2 disease involving retention of cholesterol in lysosomes; yeast NPC2 can complement mutations in human NPC2 1

is annotated as
intracellular sterol transport 
(descendant of sterol transport)

**Comment by pgaudet** [comment]
Right - standardizing the terms and definitions here did not always serve us very well....

**Comment by pgaudet** [comment]
How about this ? PMID:16585271 "Nonvesicular sterol movement from plasma membrane to ER requires oxysterol-binding protein-related proteins and phosphoinositides. "

We need to review annotations first. I'll assign this to you @ValWood

**Comment by ValWood** [comment]
One type
https://en.wikipedia.org/wiki/Sterol_carrier_protein
Not sure what kind of "transport" this is but we need a "type" for this https://github.com/geneontology/go-annotation/issues/1659 to work

**Comment by pgaudet** [comment]
Right ! We show that this transport requires oxysterol-binding protein (OSBP)-related proteins (ORPs) (PMID:16585271) 

It seem sort of similar to this 'odorant carrier' 
https://github.com/geneontology/go-annotation/issues/1660

**Comment by ValWood** [comment]
Not you though, definition happened in 2010 for this term ;)

I'll have a dig around for this later. I wanted to look at this as these have been causing me slimming problems....

Have to head now....

**Comment by pgaudet** [comment]
There seem to be ABC transporters involved in sterol transport: 
PMID: 14618236
PMID:11452359

However it seems like these ABC transporters move 'lipid-protein conjugates', see a useful review here: 
http://essays.biochemistry.org/content/50/265.long

Several proteins annotated to 'sterol transporter activity' are not TM transporters
PMID 20008566 @srengel 
again- the term "carrier" may be useful to distinguish. 

Thanks, Pascale

**Comment by uhinz** [comment]
Yes, there are ABC transporters involved in sterol transport, there's plenty of biochemical and genetic data, even a 3D-structure (example: PubMed:18402465 and   for the 3D-structure  PubMed:27144356)
Best regards,
Ursula

**Comment by pgaudet** [comment]
Thanks @uhinz, this is very useful. 

We need to decide what is a process and what isn't here. It may be useful to specify 'transmembrane sterol transport' versus 'vesicle-dependent sterol transport'. In this case we should probably make 'GO:0015918 sterol transport' a 'do not annotate'. 

Thoughts ? 

Thanks, Pascale

**Comment by uhinz** [comment]
The heterodimeric ABC transporter composed of ABCG5 and ABCG8 mediates transmembrane sterol transport (no vesicles anywhere, the proteins sit in the cell membrane), so that is fine by me. 
I've just started an update of these proteins, so I have a lively interest in these GO terms.

**Comment by ValWood** [comment]
There are too many annotations to check...263 experimental.

I think your suggestion of making "do not annotatate" and creating children is best.

There is already a child  term

GO:0030299    intestinal cholesterol absorption
but this is also a bit unclear.

In addition there is
 GO:0090118    receptor-mediated endocytosis involved in cholesterol transport

Maybe for now add 
sterol and cholesterol transmembrane transport terms for now

and recommend that people use children, if anything is not covered they can request a new transport type?

remember that the original problem is that this term is defined as a transmembrane transport, and would not cover endocytosis (even though that is a child), so the def would need to be fixed.

**Comment by pgaudet** [comment]
I wonder if transmembrane transport belongs in BP; what matters is that molecules get moved around, doesn't it ? 'How' should be kept to BP, shouldn't it ? 

@marcfeuermann @thomaspd

**Comment by marcfeuermann** [comment]
I think that transmembrane transport is a function. We have many examples of "duplicated" MF-BP such as MF - ' X transmembrane transporter activity' linked to BP -  'X transmembrane transport'. 
The actual process is the import or the export into or out of a cell or an organelle. The BP is what the activity is needed for. Transmembrane transport is not needed for transmembrane transport, but for import or export.
Such kinds of duplications are not relevant to me. This is even more true since we make GO-CAM annotations.
Regards
Marc.

**Comment by ValWood** [comment]
"transmembrane transport" in process is really, really important for enrichment and slimming. 

Users generally enrich over processes, and genes involved in "transmembrane transport" are in very differnet biological  modules from those involved in other transport processes (nucleocytopasmic/intermembrane/vesicle-mediated) . 

We also need the grouping terms to be able to link the sum of the different transport activities for specific substrates  (high affinity, low affinity, different compartemnts, and their regulation).

These terms are still required even though we use GO-CAM syntax.

We have discussed this many times and come to the same conclusion. Once very recently. I will try to locate and link to this ticket.

**Comment by ValWood** [comment]
we discussed this very recently in another ticket @ukemi  can you remember which? I can't locate. I think it was related to glucose transport.

**Comment by ValWood** [comment]
we can probably close this. It actually looks OK
