### ISSUE TITLE
definition & equivalence axion of the term "RNA polymerase II transcription factor complex"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#14394]
Two issues with this term:

1. I noticed that the definition of the term "**RNA polymerase II transcription factor complex**" seems too narrow. My recollection is that people also refer to the complexes that bind to enhancer sequences as "transcription factors", so this current def is too narrow. To reflect usage in the literature, is should include enhancers as well.
**Term**: "RNA polymerase II transcription factor complex"
**Def**: A transcription factor complex that acts at promoters of genes transcribed by RNA polymerase II.

2. Also, this equivalence axiom seems overly ambitious.

```
'macromolecular complex'
 and ('capable of' some 'transcription from RNA polymerase II promoter')
```

I thought 'capable of' meant you were saying that the thing you were describing has the named ability, but TFs are not capable of transcription without an RNAP and often additional TFs.

Should this be 'capable of part of'?

This comment applies to all five parallel terms for "RNA polymerase _ transcription factor complex", where the blank is filled by I, II, III, IV, or V.

**Comment by krchristie** [comment]
In contrast, the equivalence axiom of this term: "transcription factor TFIIIB complex" is this:

```
'macromolecular complex'
 and ('capable of' some 'TFIIIB-type transcription factor activity')
```

**Comment by pgaudet** [comment]
Hi @krchristie 
This should be consistent with the new tx factor branch. 

Thanks, Pascale¨

**Comment by pgaudet** [comment]
Hi @krchristie 

How would that be for an equivalence axiom: 

'protein-containing complex'
 and ('capable of' some 'regulation of transcription by RNA polymerase II')


And the definition could be changed to "A transcription factor complex that acts at at cis-regulatory regions of genes transcribed by RNA polymerase II."

(Same for the other polymerases). Would that address the issue? 

Thanks, Pascale

**Comment by krchristie** [comment]
This equivalence axiom seems fine:
```'protein-containing complex'``` 
```and ('capable of' some 'regulation of transcription by RNA polymerase II')```

However, I am wondering if "cis-regulatory" is sufficiently broad to encompass the distant enhancer sequences which regulate transcription. Maybe just leave out the "cis-" and only say "regulatory regions"

**Comment by pgaudet** [comment]
Voila: 

'protein-containing complex'
and ('capable of' some 'regulation of transcription by RNA polymerase II')

Definition could be changed to "A transcription factor complex that acts at regulatory regions of genes transcribed by RNA polymerase II."

For all except Pol IV which doesn't have a regulation term. I prefer not to create term that we don' yet need. 

Pascale

**Comment by krchristie** [comment]
thanks @pgaudet !

**Comment by pgaudet** [comment]
I edited the def slightly "A transcription factor complex that acts at a regulatory region of a gene transcribed by xx' - I hope that's ok

**Comment by krchristie** [comment]
works for me
