### ISSUE TITLE
MP  GO:1904983 - transmembrane glycine transport from cytosol to mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14393]
GO:1904983 - transmembrane glycine transport from cytosol to mitochondrion

MP 

GO:0006839 | mitochondrial transport

**Comment by pgaudet** [comment]
Hi @ValWood 
ideally the logical definitions would handle this. Question: Do you consider both import and export into/from the mitochondrion, mitochondrial transport'? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes, that would make sense. Some things are shuttles and transfer in and out I think.....

**Comment by ValWood** [comment]
mitochondrial transport=
Transport of substances into, out of or within a mitochondrion.
