### ISSUE TITLE
ntr:  fluoride transmembrane export across plasma membrane

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14390]
_From @ValWood on October 20, 2017 10:13_

- [x] ntr: fluoride transmembrane export across plasma membrane
standard def 
ref PMID:27327046

don't seem to have 

- [x] ntr : export across plasma membrane  either?

- [ ] although we do have
GO:1903764    regulation of potassium ion export across plasma membrane
???
add parents

_Copied from original issue: geneontology/go-annotation#1667_

**Comment by ValWood** [comment]
fluoride transmembrane export across plasma 
doe not show as a child of 

GO:1903424 | fluoride transmembrane transport
-- | --

**Comment by ValWood** [comment]
I  wonder if this relation can be added and committed  it was part of our workshop session tomorrow to annotate this paper... it might catch the canto update  if it goes in today?

**Comment by pgaudet** [comment]
Sorry I missed that, now fixed. The third point in your original ticket has been moved to a new issue. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood please close if this is OK for you.

**Comment by ValWood** [comment]
All good.
