### ISSUE TITLE
MP cellular detoxification

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14392]
_From @ValWood on October 20, 2017 9:33_

https://www.ebi.ac.uk/QuickGO/term/GO:1990748

does not have parent
"response to cellular detoxification"

_Copied from original issue: geneontology/go-annotation#1664_

**Comment by pgaudet** [comment]
Really ? 

Why would x be a child of response to x ?

**Comment by ValWood** [comment]
I was following current:

GO:0009636    response to toxic substance
--GO:0098754   detoxification

but that sounds right? No?
