### ISSUE TITLE
taxon restriction  alpha-heterochromatin bete-heterochromatin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14395]
GO:0005723 alpha-heterochromatin
A small, compact region of heterochromatin located in the middle of the polytene chromosome chromocenter, which undergoes little or no replication during polytenization. PMID:8878678

GO:0005722    beta-heterochromatin
Definition 
A diffusely banded region of heterochromatin located between euchromatin and alpha-heterochromatin in the polytene chromosome chromocenter; normally replicated during polytenization. PMID:11404334 PMID:8878678

I don't  know what the taxon restriction would be for this  but only organisms which have polytene chromosomes.

Add never in fungi?
or only in multicellular?

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Polytene_chromosome

They are known to occur in secretory tissues of other dipteran insects such as the Malpighian tubules of Sciara and also in protists, plants, mammals, or in cells from other insects. Some of the largest polytene chromosomes described thus far (see scale bar in figure below) occur in larval salivary gland cells of the Chironomid genus Axarus.

**Comment by vanaukenk** [comment]
@ValWood 
Given the wiki entry, it seems the safest restriction at this point would be 'never in fungi'.
Shall I go ahead and add that?

**Comment by ValWood** [comment]
yep, I didn't know which or had polytene ...
