### ISSUE TITLE
Add missing parent mitochondrial transmembrane transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14400]
The following terms are direct children of 'mitochondrial transport' but could be moved to 'mitochondrial transmembrane transport': 

* GO:1990544 mitochondrial ATP transmembrane transport
* GO:0045016 mitochondrial magnesium ion transport -> merge with  GO:1990614 mitochondrial magnesium ion transmembrane transport
* GO:0006850 mitochondrial pyruvate transport -> merge with GO:1902361 mitochondrial pyruvate transmembrane transport

**Comment by pgaudet** [comment]
I am unsure about 

* GO:0043490 malate-aspartate shuttle (5 EXP annotations by UniProt, MGI, RDG, all SLC proteins)
* GO:0042776 mitochondrial ATP synthesis coupled proton transport

Probable 'carriers': 
* GO:0019090 mitochondrial rRNA export from mitochondrion
* GO:0035927 RNA import into mitochondrion 

If someone knows about these  and they need to be moved, please create a new issue.  

Thanks, Pascale

**Comment by ValWood** [comment]
Maybe we should do 
GO:0043490 malate-aspartate shuttle
as 
aspartate transport  and
malate transport
(we don't usually combine when transporters  import one thing and export another).


I think this one is probably OK?
GO:0042776 mitochondrial ATP synthesis coupled proton transport

GO:0019090 mitochondrial rRNA export from mitochondrion
This term does not seem to be describing export, but transport from mitochondria to the polar granules (1 FlyBase annotation)  in which case it would probably  be a carrier? @hattrill 

GO:0035927 RNA import into mitochondrion
It seems that TOM complex  (a transmembrane transporter) is used to import tRNAs
http://www.uniprot.org/uniprot/P35180
but I also see  annotations for repurposing of amino acid transporters - I think the terms are valid as there are likely lots of steps in between getting a nuclear encoded tRNA  across both membranes into the  mitochondrial matrix.... so is probably OK for now. 
Processes are not well studied....

**Comment by pgaudet** [comment]
What I dont understand about the malate-aspartate shuffle is that it seems to be an electron transfer process: 
https://en.wikipedia.org/wiki/Malate-aspartate_shuttle
ie catalyzed by enzymes: 

    malate dehydrogenase in the mitochondrial matrix and intermembrane space.
    aspartate aminotransferase in the mitochondrial matrix and intermembrane space.
    malate-alpha-ketoglutarate antiporter in the inner membrane.
    glutamate-aspartate antiporter in the inner membrane.


However the annotations are to SCL type proteins; so I think the annotations are incorrect; right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Reponening for the extra questions - but the work on the ontology is done.

**Comment by ValWood** [comment]
Oh yes sorry, I was thinking this was just a mitochondrial carrier (the transmembrane transporter type) .

Its a pathway with 2 transporters and two enzymes.

You are correct, the annotated carriers do not appear to be correct.
they are the aspartate/glutamate carrier ?

**Comment by ValWood** [comment]
I remember now...this critical  the TCA cycle.

**Comment by ValWood** [comment]
this is useful:
http://www.sciencedirect.com/science/article/pii/S0005272806001630#sec3

**Comment by hattrill** [comment]
I'll remove this annotation (to GO:0019090 mitochondrial rRNA export from mitochondrion), as it certainly isn't correct. I suspect that the observation in this paper can be attributed to the role of tudor in RNA/granule organisation.

**Comment by pgaudet** [comment]
(note to self:) For GO:0019090 mitochondrial rRNA export from mitochondrion 
see PMC5437960
looks like this is a real process.
