### ISSUE TITLE
Fix regulation of import/export

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14418]
Following up on #14390 
- [ ] We are missing a general parent for terms such as 
'GO:1903764 regulation of potassium ion export across plasma membrane' 
- [x]  whenever possible we should specify if t he import/import is across the membrane  (must first check annotations)

Thanks, Pascale

**Comment by ValWood** [comment]
potassium ion export across plasma membrane
and
regulation of potassium ion export
exist
is this still current?

Is this done now?

**Comment by ValWood** [comment]
I think here you are saying there is no general import term, but I think you alter decided it ws unnecessary?

**Comment by pgaudet** [comment]
I thought you wanted 'regulation of import across plasma membrane' - is this right ?

**Comment by ValWood** [comment]
I don't remember wanting the specific regulation terms (we don't annotate much to regulation of transport), however we do have some transporters which we know import, but we don't know the substrate, so we would require " import across plasma membrane" and that exists.

You can close this for me, if we need anything else we will request.

**Comment by ValWood** [comment]
we checked all of the direct to import and export for potassium and all were plasma membrane.

Terms will be merged....

**Comment by pgaudet** [comment]
I will merge 
- 'potassium import' into 'potassium import into plasma membrane'
- 'potassium export' into 'potassium import into plasma membrane'
