### ISSUE TITLE
NTR: positive regulation of GO:0000290 deadenylation-dependent decapping of nuclear-transcribed mRNA

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14410]
PMID:23221597 only describes the effect of mutating LSM1 on the decapping of the mRNA so we can't be sure that it's actually actioning the decapping.

I need the "positive regulation of" term, I don't know if the "negative regulation of" term is required.

Thanks,
Birgit

**Comment by pgaudet** [comment]
Hi @bmeldal 
Is this a phenotype, or is this a direct role of LSM1? From the paper (I am looking at Fig 6, I am not sure this is what you want to annotate) I wasn't able to tell. 

Thanks, Pascale

**Comment by bmeldal** [comment]
F6e and F8d show the retention of capped mRNAs for the double mutant of lsm1a and lsm1b but not WT or single mutants. But, as we don't know exactly HOW the LSM complex actions the decapping I would like to annotate to regulation of ~.

**Comment by ValWood** [comment]
If we don't  know the exact role we shouldn't annotate as regulating.....you should annotate directly to  decapping.

(incidentally lsm1 is involved directly in decapping via membership of
GO:0005845 | mRNA cap binding complex)

**Comment by bmeldal** [comment]
So, if I'm not sure it the direct process even if it might be upstream of it? I can't use relations in the CP tool for now so it just goes out as a simple BP annotation. I would have thought a direct annotation to the BP means it's absolutely part of the process.

However, after discussing the complex activity in the related post (cited above) I guess we can say it's directly part of the process albeit it needs the snRNA and accessory proteins.

So, maybe not needed the reg term after all here, @krchristie ?

**Comment by ValWood** [comment]
aren't  LSm1-7  established to be part of  decapping? 
http://www.cell.com/cell-reports/abstract/S2211-1247(17)30941-5
They may also be regulatory? I'm not sure (more difficult  to establish). 
It depends if the decapping process includes the assembly of the decapping complex (it seems that it should be the starts and ends of the process are not clear in the definition).


BTW, How does this complex fit in here? 
This is the "decapping" version of the lsm complex used by SGD?
https://www.yeastgenome.org/go/GO:1990726

**Comment by krchristie** [comment]
My understanding is consistent with @ValWood, that Lsm1-7 are established to be required for deadenylation-dependent decapping. I agree that it's also possible that they are regulatory, but more difficult to establish. However, I don't think I would annotated to the positive regulation term based on a mutation in LSM1 that decreases this process, as it is known that the Lsm1-7-Pat1 complex is required for this process, so mutating LSM1 disrupts this process.

**Comment by bmeldal** [comment]
Ok, so no need for the reg term.

@ValWood LSM1-7 is the assembly product that then combines with PAT1 to form the functional complex. Looks like from all this reading that we should actually create the LSM1-7-Pat1 complex in the CP! But there are several isoforms of PAT1 (a and b) as well as some of the LSM proteins so will make for lots of variant entries!

**Comment by ValWood** [comment]
Won't the single complex 
Lsm1-7-Pat1 complex GO:1990726 cover it for GO?
and no need for NTR: LSM1-7
(presumably the pat1 differences are tissue specific variants)

**Comment by bmeldal** [comment]
Yes, @ValWood as my mum always said when I got stuck with homework "Explain it to me so you understand what you are supposed to be doing!" I think the long discussion in #14411 and above has resolved this ticket now and I shall close it :)

**Comment by ValWood** [comment]
;)
