### ISSUE TITLE
Standardize textual definition transmembrane transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14436]
Hello, 

Looking at the noted from the transport group http://wiki.geneontology.org/index.php/Transmembrane_transporters
We should update all definitions to 'The process in which [x] is transported from one side of a membrane to the other.'' Now it's a mix of that and what the groups had decided on for the top level class transport,  

> The definition of transport ; GO:0006810 is: The directed movement of substances (such as macromolecules, small molecules, ions) into, out of, within or between cells, or within a multicellular organism by means of some external agent such as a transporter or pore. 

I suppose that this also needs to match the DOS design patterns. The incorrect definitions seem to all come from TG. 

Thanks, Pascale

**Comment by ukemi** [comment]
Hi @pgaudet ,

These definitions are for different granularities of transport. The first one is for transmembrane transport, the second is for general transport. I would go with the experts definitions whenever possible. We need to have the more general transport terms to describe the complexities of transport in anatomical structures like kidneys and digestive systems.

**Comment by pgaudet** [comment]
Hi all, 

I standardizing the definitions and equivalence axioms of transmembrane transport as indicated in 
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/transmembrane_transport.yaml 

ie: 
**Equivalence axiom:** 
transport
 and ('transports or maintains localization of' some %s)
 and ('results in transport across' some membrane)

Textual definition: "The process in which a x is transported across a membrane."

If anyone has feedback on this please let me know soon. 
@ValWood maybe ?

**Comment by ValWood** [comment]
I think that's OK.
I did wonder why it was "transports or maintains localization of" rather than just "transports"
but  it might not  need to be so specific because if it "results in transport across a membrane" it must be transport rather than localization?

**Comment by pgaudet** [comment]
right... that's a while different issue. I had asked for that relation but I cannot see it yet. At the same time we'd have 
transport
and transports some x 

which sounds OK. I thought 'has input' might also be appropriate. Anyway for now I just want to standardize. 

Thanks, Pascale

**Comment by ValWood** [comment]
OK sounds good. Easy to restandardize if  necessary if  they are already standardized ;)

**Comment by pgaudet** [comment]
That's what I thought !
