### ISSUE TITLE
go-plus.json appears to be out of sync with go-plus.owl/obo

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#14432]
In the latest version of http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json (which claims to be derived from http://purl.obolibrary.org/obo/go/releases/2017-10-25/extensions/go-plus.owl, according to its "version" tag) GO:0001071 is shown as deprecated (secondary to GO:0003700), while in go-plus.owl and go-plus.obo (the releases/2017-10-25 versions) it isn't.

Our ontology update pipeline is failing because GO:0001071 is referenced as a "consider" in the obsoleted terms GO:0016563, GO:0016564, GO:0016986, and GO:0030528, which is not consistent with its apparent deprecated status.

**Comment by tonysawfordebi** [comment]
We're still seeing this problem, and the same sanity check is also flagging a problem with GO:0015563.

Any idea when this might be fixed?

**Comment by pgaudet** [comment]
Hi @tonysawfordebi 
What is the problem with GO:0015563? I merged this last week; it looks OK to me in Protegé but I might not know what to look for.

Thanks, 
Pascale

**Comment by cmungall** [comment]
@pgaudet - you're looking at the editor's version, @tonysawfordebi is seeing a discrepancy between different formats in the release version.

**Comment by cmungall** [comment]
@tonysawfordebi - I'm having a hard time replicating the issue of synchrony between go-plus.owl and go-plus.json. I'm not seeing anything in your ticket that indicates these are out of sync.

However, we do have this issue of `consider` tags pointing to obsolete classes. This is true regardless of which format is downloaded. I just checked our pipeline, and I'm surprised to discover we have absolutely zero checks for this scenario (we check if logical axioms reference an obsolete class). I'm surprised this hasn't come up before.

As I see it there are two action items here: I will implement the checks and a go editor will remove all violations.

Also, if you do see any evidence of asynchrony file a ticket on go-site and email Seth Eric and myself, but I believe these issues should not happen now we have switched to the new ontology pipeline.

**Comment by tonysawfordebi** [comment]
@cmungall When I raised the ticket I was looking at the version of http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json whose "version" meta tag was "http://purl.obolibrary.org/obo/go/releases/2017-10-25/extensions/go-plus.owl", and the entry for GO:0001071 was:

 {
      "id" : "http://purl.obolibrary.org/obo/GO_0001071",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "http://purl.obolibrary.org/obo/IAO_0000231",
          "val" : "http://purl.obolibrary.org/obo/IAO_0000227"
        }, {
          "pred" : "http://purl.obolibrary.org/obo/IAO_0100001",
          "val" : "http://purl.obolibrary.org/obo/GO_0003700"
        } ],
        "deprecated" : true
      },
      "type" : "CLASS"
    },

When I looked at http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/2017-10-25/extensions/go-plus.obo I found that that stanza for GO:0001071 was this:

[Term]
id: GO:0001071
name: nucleic acid binding transcription factor activity
namespace: molecular_function
def: "Interacting selectively and non-covalently with a DNA or RNA sequence in order to modulate transcription. The transcription factor may or may not also interact selectively with a protein or macromolecular complex." [GOC:txnOH]
comment: Note that this term is in the subset of terms that should not be used for direct gene product annotation. This term does not provide specificity with respect to the type of nucleic acid binding, e.g. RNA or DNA. Please use a child term that provides that specificity or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.
subset: gocheck_do_not_manually_annotate
subset: goslim_agr
subset: goslim_chembl
subset: goslim_generic
subset: goslim_mouse
subset: goslim_yeast
synonym: "transcription factor activity" BROAD []
is_a: GO:0003674 ! molecular_function
relationship: has_part GO:0003676 ! nucleic acid binding
relationship: part_of GO:2001141 ! regulation of RNA biosynthetic process
created_by: kchris
creation_date: 2010-10-21T04:37:54Z

And in http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/2017-10-25/extensions/go-plus.owl it was:

    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0001071">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GO_0140110"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_2001141"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0002016"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0003676"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Interacting selectively and non-covalently with a DNA or RNA sequence in order to modulate transcription. The transcription factor may or may not also interact selectively with a protein or macromolecular complex.</obo:IAO_0000115>
        <oboInOwl:created_by rdf:datatype="http://www.w3.org/2001/XMLSchema#string">kchris</oboInOwl:created_by>
        <oboInOwl:creation_date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2010-10-21T04:37:54Z</oboInOwl:creation_date>
        <oboInOwl:hasBroadSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">transcription factor activity</oboInOwl:hasBroadSynonym>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">molecular_function</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GO:0001071</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#gocheck_do_not_manually_annotate"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_agr"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_chembl"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_generic"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_mouse"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_yeast"/>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Note that this term is in the subset of terms that should not be used for direct gene product annotation. This term does not provide specificity with respect to the type of nucleic acid binding, e.g. RNA or DNA. Please use a child term that provides that specificity or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.</rdfs:comment>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">nucleic acid binding transcription factor activity</rdfs:label>
    </owl:Class>

In other words, out of the three files, the only one in which it appears as deprecated is the JSON flavour.

http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json now has "http://purl.obolibrary.org/obo/go/releases/2017-10-28/extensions/go-plus.owl" as its "version" meta tag, but the entry for GO:0001071 has not changed. Nor has it changed in http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/2017-10-28/extensions/go-plus.obo, However, in http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/2017-10-28/extensions/go-plus.owl it is now showing as:

    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0001071">
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/GO_0003700"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>

So it would appear that go-plus.owl and go-plus.json are in sync, but go-plus.obo is lagging behind.

**Comment by cmungall** [comment]
OK, something up with svn. Related ticket: https://github.com/geneontology/pipeline/issues/9

Note that for getting the live snapshot, there is no dependency on svn, the 3 versions of go-plus (and anything else) should be in sync. svn is only used for serving versionIRIs (in future we will not support permanent versionIRIs for snapshots, only monthly).

**Comment by ukemi** [comment]
@cmungall, is this resolved?

**Comment by balhoff** [comment]
This should all be resolved at this point.
