### ISSUE TITLE
thiamine pyrophosphate transmembrane transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14433]
From SGD:
You are correct that TPC1 was misannotated to “thiamine transmembrane transporter activity” and should have been annotated to “thiamine pyrophosphate transmembrane transporter”. However, this term does not currently exist in the ontology. Although, not as granular, there is a term “thiamine pyrophosphate transporter activity” (GO:0090422) and we could transfer the annotation to this term. Of course, if you would prefer the more granular term you could request it and then let us know when it has been created and we could transfer the annotation to this more granular term. 

Action, please move
“thiamine pyrophosphate transporter activity” (GO:0090422)
to
thiamine pyrophosphate transmembrane transporter”

thanks

Val

**Comment by pgaudet** [comment]
Renamed 'GO:0090422 thiamine pyrophosphate transporter activity' (checked all EXP annotations; all are TM transporters).
