### ISSUE TITLE
nuclear-transcribed lncRNA catabolic process 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14438]
Hello,

I'd like to request
nuclear-transcribed lncRNA catabolic process 
is_a           ncRNA catabolic process
ref PMID:24493644

**Comment by vanaukenk** [comment]
Hi @Antonialock 

I just want to confirm the parent term here.  Did you want the new term to be a child of GO:0006402 'mRNA catabolic process' or GO:0034661 'ncRNA catabolic process'?

Also, it seems we have a lot of catabolic terms that are specific to the type of ncRNA.  Based on the abstract of the paper, do you want to make a more specific term referring to a lncRNA catabolic process?

Thx.

**Comment by krchristie** [comment]
Seems unlikely that it is appropriate to have "mRNA catabolic process", a term specific to coding RNAs" be an is_a parent of a term that is explicitly for non-coding transcripts: "nuclear-transcribed ncRNA catabolic process"

**Comment by vanaukenk** [comment]
@Antonialock 
I added 'lncRNA catabolic process' to be consistent with the other children that we have under 'ncRNA catabolic process'. 
Let me know, though, if at any point you feel the 'nuclear-transcribed' part is critical to the classification of this process, and I will add a child term for that.  Thx.
