### ISSUE TITLE
NTR: folate receptor activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#14437]
I'd like to add the term folate receptor activity as a sibling to GO:0001646 cAMP receptor activity and a child of G-protein coupled receptor activity (GO:0004930). 
PMID:26906738

NEW: folate receptor activity
is_a GO:0004930 G-protein coupled receptor activity

Def: Combining with folate and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity.

Exact Synonym: folic acid receptor activity

Thanks! Once this is accepted and I read a bit moreI will also ask for some Bp(s)

**Comment by ukemi** [comment]
Be sure to disambiguate this with the ones that are not GPCRs.

**Comment by hdrabkin** [comment]
may need also to use a relation to GO:0005542  folic acid binding

**Comment by hdrabkin** [comment]
So there are other folate receptors that are not GPCRs?
In which case may name of ntr should be more specific (ie, folate-binding dependent GPCR?)

**Comment by pfey03** [comment]
Thanks guys, sorry for my Dicty tunnel view. Looked into human folate receptors and of course, they operate very differently. So I suggest, similar to other specific children of G-protein coupled receptors to name the term:

NEW: G-protein coupled folate receptor activity
is_a GO:0004930 G-protein coupled receptor activity

Updated  Def:
Combining with folate and transmitting the signal from one side of the membrane to the other by activating an associated G-protein, initiating a change in cell activity

SYN: G-protein coupled folic acid receptor activity

I hope this works. Thanks again!

**Comment by hdrabkin** [comment]
no problems; it prompted me to look at the other folic acid receptor term and it looks more like a transporter of folate into the cell. Haven't looked at your paper, but want to make sure that in your case the folate itself is not transported into the cell?

**Comment by pfey03** [comment]
Here is a summary so you don't need to read the paper:

There is no folate as such transported into the Dicty cell. The G-protein coupled signalling via ERK2 phosphorylation,  PIP3 response and subsequent actin polymerization then leads to migration towards the folate source and phagocytosis of the bacterium.
There is a second receptor (far2) that has very little activity.

- They show all the signaling responses are very strongly reduces in the far1 mutant. 
- When plated on bacterial lawn, the far1 mutant cells form tiny plaques, compared to wt.
- They show folate binding of the fAR1 receptor, and that is already annotated.
- They show that binding of the bacteria itself on the cell surface is not part of the receptor activity.
- The far1 mutant does not form efficient phagocytic cups to engulf bacteria


So once I have the MF term, I will carefully check if I should add a new BP term as well, checking what's there already and not adding bulk.

**Comment by hdrabkin** [comment]
ok; looks good; I'll add this in the afternoon, then off to florida!

**Comment by hdrabkin** [comment]
added GO:0106063 G-protein coupled folate receptor activity
