### ISSUE TITLE
Regulation of cobalamin metabolic process

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#14442]
Hi, I would need Regulation of cobalamin metabolic process term creation

Thanks

Sylvain

Definition:  Any process that modulates the frequency, rate or extent of the chemical reactions and pathways involving cobalamin (vitamin B12), a water-soluble vitamin characterized by possession of a corrin nucleus containing a cobalt atom. 

Category: Process
Child of GO:0009235 cobalamin metabolic process

I need this term because of PubMed=29056341 that shows that this enzyme is part of the C5-dicarboxylate catabolism pathway, which is required to detoxify itaconate, a vitamin B12-poisoning metabolite.

In this case, the protein is clearly not directly involved the metabolism of cobalamin

In my opinion, we should wait a moment before creating a term for the C5-dicarboxylate catabolism pathway

**Comment by hdrabkin** [comment]
GO:0106064 'regulation of cobalamin metabolic process' created.
