### ISSUE TITLE
Merge 'phosphate transmembrane transporter activity' into 'phosphate ion transmembrane transporter activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14452]
Hello, 

The term GO:1901677 'phosphate transmembrane transporter activity' has a single child: GO:0015114 'phosphate ion transmembrane transporter activity'. 

Shouldn't these two terms be merged ? (GO:1901677 ' has no annotations). 

Thanks, Pascale

**Comment by ValWood** [comment]
Would seem so...
