### ISSUE TITLE
MP 18S rRNA (adenine(1779)-N(6)/adenine(1780)-N(6))-dimethyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14459]
GO:0052909	
18S rRNA (adenine(1779)-N(6)/adenine(1780)-N(6))-dimethyltransferase activity

should be a descendant of
GO:0000179	
rRNA (adenine-N6,N6-)-dimethyltransferase activity

?

**Comment by vanaukenk** [comment]
@ValWood 

It looks like maybe both

GO:0052909 
18S rRNA (adenine(1779)-N(6)/adenine(1780)-N(6))-dimethyltransferase activity

and

GO:0052908 
16S rRNA (adenine(1518)-N(6)/adenine(1519)-N(6))-dimethyltransferase activity

should be re-housed under 

GO:0000179
rRNA (adenine-N6,N6-)-dimethyltransferase activity

If that's the case, though, we'll need a new, more generic definition for GO:0000179.  How about:

Catalysis of the dimethylation of two adjacent adenine residues in a rRNA, using S-adenosyl-L-methionine as a methyl donor.

Does that look right to you?

**Comment by ValWood** [comment]
yep!

**Comment by vanaukenk** [comment]
There are direct experimental annotations to GO:0000179, so I think we need to have curators review those annotations to see if they can be re-assigned to one of the more specific children.

@ukemi - if I change the definition of GO:0000179 from:

Catalysis of the dimethylation two adjacent A residues in the loop closing the 3'-terminal stem of the 18S rRNA, using S-adenosyl-L-methionine as a methyl donor.

to:

Catalysis of the dimethylation of two adjacent adenine residues in a rRNA, using S-adenosyl-L-methionine as a methyl donor.

should I obsolete this term, i.e. is that enough of a change in meaning?

GO:0052909 and GO:0052908 should both be children of GO:0000179, but then GO:0000179 needs a more generic definition to cover both 18S and 16S rRNAs.

**Comment by ukemi** [comment]
Although the paper cited in the definition of GO:0000179 does specify the 18S rRNA, looking at the annotations suggests that the term was used for both. I think it would be ok to relax the definition. How conserved are the residues in these molecules? Do we need to relax the 16S and 18S terms? Do we even need those?  Looking at the annotated papers, it might have been better to differentiate on the kind of small ribosomal subunit (cytosolic, plastid, mitochondrial) than 16S versus 18S.  @tberardini what do you think, since you've got them all?

**Comment by vanaukenk** [comment]
Okay, I looked at all of the papers and annotations to GO:0000179 and if we relax the definition for this term, all of the existing annotations will still be correct and would not need to be re-housed to a more specific term, or at least not one that currently exists in GO.  

The more specific terms we do have, like GO:0052909, are following the EC nomenclature wrt 16S, 18S, etc.

**Comment by ukemi** [comment]
Yes, they are following the EC classification, but I question the distinction for GO. The terms seem very specific with respect to residues etc.

**Comment by tberardini** [comment]
@vanaukenk @ukemi  Do you still need me to look at stuff or was your investigation sufficient?  I don't know this area at all but will dig in if still needed.
