### ISSUE TITLE
UDP-glucose transmembrane transport into Endoplasmic Reticulum

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14450]
child of
GO:0015786 | UDP-glucose transport

standard def

(GO:0015786  can be renamed transmembrane?)

PMID:27587357
Title | THE CONUNDRUM OF UDP-Glc ENTRANCE INTO THE YEAST ER LUMEN.

PMID:27587357
--
Title | THE CONUNDRUM OF UDP-Glc ENTRANCE INTO THE YEAST ER LUMEN.

UDP-Glc entrance into the endoplasmic reticulum (ER) of eukaryotic cells is a key step in the quality control of glycoprotein folding, a mechanism requiring transfer of a Glc residue from the nucleotide sugar (NS) to glycoprotein folding intermediates by the UDP-Glc:glycoprotein glucosyltransferase (UGGT)........ We conclude that the hut1+ gene product is involved in UDP-Glc entrance into the ER, but that at least another as yet unknown NST displaying an unconventional sequence operates in the yeast secretory pathway.

**Comment by krchristie** [comment]
@ValWood - So, mostly this is a new term request?

Regarding: 
> GO:0015786 can be renamed transmembrane?

The definition is not that specific. Perhaps you should direct this to @pgaudet since she's working on transport generally.

**Comment by pgaudet** [comment]
Hi @krchristie 
I checked the annotations and it's OK to rename 
GO:0015786 | UDP-glucose transport -> UDP-glucose transmembrane transport. 

The definition should be changed to 'The process in which a UDP-glucose is transported across a lipid bilayer, from one side of a membrane to the other.' 

Thanks, Pascale
