### ISSUE TITLE
Transcription factor refactor - Merge core promoter proximal region DNA binding promoter proximal region sequence-specific DNA binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14463]
Merge
GO:0001159 core promoter proximal region DNA binding 
into GO:0000987 promoter proximal region sequence-specific DNA binding

The word "core" is confusing. 

Rename: 
GO:0000978
-name: RNA polymerase II core promoter proximal region sequence-specific DNA binding
+name: RNA polymerase II promoter proximal region sequence-specific DNA binding

GO:0000987
-name: core promoter proximal region sequence-specific DNA binding
+name: promoter proximal region sequence-specific DNA binding

GO:0044377
-name: RNA polymerase II core promoter proximal region sequence-specific DNA binding, bending
+name: RNA polymerase II promoter proximal region sequence-specific DNA binding, bending

Thanks, Pascale

**Comment by RLovering** [comment]
this seems sensible
Ruth

**Comment by pgaudet** [comment]
OK if there are no more comments I'll merge this one tomorrow. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Astrid proposes renaming to 

>  
From my side, I would then prefer that the terms were phrased
“proximal promoter sequence-specific DNA binding”
 
instead of
 “promoter proximal region sequence-specific DNA binding”
 (and, I guess by analogy: “core promoter sequence-specific DNA binding” for e.g. TBP)

**Comment by pgaudet** [comment]
Definitions from https://en.wikiversity.org/wiki/Gene_transcriptions/Promoters
**Core promoter**: The core promoter is the minimal portion of the promoter required to properly initiate gene transcription.[9]"[1] It contains a binding site for RNA polymerase (RNA polymerase I, RNA polymerase II, or RNA polymerase III). A vast network of regulatory factors that contribute to the initiation of transcription by RNA polymerase ultimately target any specific gene’s core promoter. The core promoter includes the transcription start site(s) (TSS). That portion of the core
promoter that is upstream of the TSS is also part of the proximal promoter.

**Proximal promoter:** A nucleotide sequence upstream of the gene that tends to contain primary regulatory elements is called a proximal promoter.

**Comment by pgaudet** [comment]
Updated definitions according to Astrid's feedback: 
NEW name: proximal promoter sequence-specific DNA binding

OLD def: "Interacting selectively and non-covalently with a sequence of DNA that is in cis with and relatively close to the core promoter. The transcribed region might be described as a gene, cistron, or operon." [GOC:txnOH]

NEW def: "Interacting selectively and non-covalently with a specific upstream regulatory DNA sequence (transcription factor recognition sequence or binding site) located in the proximal promoter. The proximal promoter is in cis with and relatively close to the core promoter."
