### ISSUE TITLE
Bacterial enhancer ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14466]
Hello, 

It looks like 'enhancer' is sometimes used to mean cis-acting region and not necessarily 'distal' region. 

So I wonder if there is a difference between 'GO:0000986 bacterial-type RNA polymerase core promoter proximal region sequence-specific DNA binding' and 'GO:0001150 bacterial-type RNA polymerase enhancer sequence-specific DNA binding' 

Can groups who have used these terms please let me know what the distinction is ? 
PseudoCAP  @brinkmanlab 
EcoCyc @keseler 
CAFA @ggeorghiou

**Comment by pgaudet** [comment]
PseudoCAP @brinkmanlab
EcoCyc @keseler
CAFA @ggeorghiou
If you don't have objections I will merge these two terms. 

Thanks, Pascale

**Comment by ggeorghiou** [comment]
Hi Pascale, 

Do you mean to tag CACAO in this? CAFA has no annotations to either term.

Best,
George

**Comment by pgaudet** [comment]
Now I only see EcoCyc and PseudoCAP. 

Thanks for checking ! 

Pascale

**Comment by keseler** [comment]
Sorry for the late comment - I had some trouble fishing out the few emails that were actually meant for me from the deluge of GO-related email notifications from git.
The probably intended difference between the two terms is to be able to distinguish the activators that enable transcription for sigma54-RNAP holoenzymes versus the sigma70-type holoenzymes.  Sigma54 and sigma70-type sigma factors function in a fundamentally different way; sigma54 holoenzymes absolutely require an activator that usually binds further upstream of the polymerase binding site than any activators for sigma70 types.

Here's a little quote from a review, PMID 18331472:

"The activator ATPase belongs to the ATPases
Associated with various cellular Activities (AAA+) protein
family. In response to regulatory cues from upstream signalling
cascades, OC formation is driven by the activator
ATPase that binds s54 and induces conformational rearrangements
in the Es54-CC. The activator ATPase binds
as higher-order oligomers (usually hexamers) to, and acts
from, DNA sites called ‘enhancers’ located ~100–150 bp
either upstream or sometimes downstream of s54
promoters."

So binding of these particular kinds of transcription factors enables open complex formation by sigma54 RNAP, while binding of "regular" TFs is not required for open complex formation of sigma70-type RNAP.  In other words, binding of these special TFs to "enhancers" has a fundamentally different function in terms of activating RNAP than binding of "regular" TFs to the "promotor proximal region".  

Does that make sense?

-Ingrid

**Comment by keseler** [comment]
A more recent review is PMID 27789741.

**Comment by pgaudet** [comment]
Hi @keseler 

Yes, that makes sense. Thanks !
