### ISSUE TITLE
mitochondrial  promoters

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14462]
After chat with @pgaudet 
Since these 4 terms have the comment

Comment
Note that as agreed during the transcription overhaul, terms specifying binding to specific transcription regulatory motifs are no longer being created. The level of specificity GO has decided to go to is the "core promoter", "core promoter proximal region" and "enhancer". To capture more detail, please consider using column 16.

and few, conflicting EXP annotations:

GO:0070364 mitochondrial heavy strand promoter sense binding 
ANNOTATIONS 4 ALL NOT

GO:0070363 mitochondrial light strand promoter sense binding 
ANNOTATIONS 4 ALL NOT 1 experimental (2 NOT)
TFAM human http://www.uniprot.org/citations/19304746

GO:0070362 mitochondrial heavy strand promoter anti-sense binding
ANNOTATIONS has only one EXP annotation  a protease. The same protein also has a NOT annotation

GO:0070361 mitochondrial light strand promoter anti-sense binding
ANNOTATIONS Has 2 EXP annotations to LON protease

Propose to obsolete, and use instead the general term

Suggest instead to use:
GO:0000997   
mitochondrial RNA polymerase core promoter sequence-specific DNA binding

**Comment by pgaudet** [comment]
how about this: 
http://www.uniprot.org/uniprot/Q00059

**Comment by ValWood** [comment]
Yes that is the only thing I saw. It is currently annotated to

GO:0070363 mitochondrial light strand promoter sense binding
ANNOTATIONS 4 ALL NOT 1 experimental (2 NOT)
TFAM human http://www.uniprot.org/citations/19304746

so I thought all could use
GO:0000997
mitochondrial RNA polymerase core promoter sequence-specific DNA binding

(Unless there is really  a separate regulatory region identified???)

**Comment by ValWood** [comment]
binds site-specifically to the mitochondrial genome and demarcates the promoters for recruitment of h-mtTFB1, h-mtTFB2 and the mitochondrial RNA polymerase. 

If people want to capture the specific promoters  they can use SO  terms in extensions?

**Comment by pgaudet** [comment]
The paper cited for those terms is 'PMID: 20670382'. The paper states that "Unlike nuclear genes, each of which often has multiple dedicated promoters, all mitochondrial genes are expressed together from only three promoters encoded in the regulatory D-loop region, which are recognized by the mitochondrial basal transcriptional machinery: the mitochondrial RNA polymerase (Polrmt), and the mitochondrial transcription factors Tfam and Tfb2m " 

So I will merge all terms into the parent "GO:0001018 mitochondrial RNA polymerase regulatory region DNA binding" (renaming: mitochondrial promoter DNA binding): 
GO:0000976 transcription regulatory region sequence-specific DNA binding
GO:0001044 mitochondrial RNA polymerase regulatory region sequence-specific DNA binding
 GO:0001045 mitochondrial RNA polymerase core promoter proximal region sequence-specific DNA binding
 GO:0000997 mitochondrial RNA polymerase core promoter sequence-specific DNA binding 
GO:0070364 mitochondrial heavy strand promoter sense binding
GO:0070363 mitochondrial light strand promoter sense binding
GO:0070362 mitochondrial heavy strand promoter anti-sense binding
GO:0070361 mitochondrial light strand promoter anti-sense binding

Thanks, Pascale

**Comment by pgaudet** [comment]
Note that there were only 3 annotations to the the list of terms above: 

rpo41 PomBase:SPAC26H5.12	GO:0001044	PomBase
rpo41 PomBase:SPAC26H5.12	GO:0000997	PomBase
mtf1  PomBase:SPAC1002.08c	GO:0000997	PomBase

Thanks, Pascale

**Comment by ValWood** [comment]
Happy to use a single term!
