### ISSUE TITLE
MP : 	GO:0097525	spliceosomal snRNP complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14460]
GO:0097525	spliceosomal snRNP complex
as defined should be a child of

GO:0005681	spliceosomal complex?

**Comment by ValWood** [comment]
spliceosomal complex
--
Ontology | Cellular Component
Definition | Any of a series of ribonucleoprotein complexes that contain snRNA(s) and small nuclear ribonucleoproteins (snRNPs), and are formed sequentially during the spliceosomal splicing of one or more substrate RNAs, and which also contain the RNA substrate(s) from the initial target RNAs of splicing, the splicing intermediate RNA(s), to the final RNA products. During cis-splicing, the initial target RNA is a single, contiguous RNA transcript, whether mRNA, snoRNA, etc., and the released products are a spliced RNA and an excised intron, generally as a lariat structure. During trans-splicing, there are two initial substrate RNAs, the spliced leader RNA and a pre-mRNA.

**Comment by krchristie** [comment]
No, spliceosomal snRNP complex (GO:0097525) should not be a child of spliceosomal complex (GO:0005681).

spliceosomal complex (GO:0005681) - refers to the formation of "the" splicesosome, aka spliceosomal complex, that forms on the RNA transcript that is the substrate of the splicing reaction. As you can see, it's child terms are the various different complexes, with varying compositions, that exist as "the" spliceosome changes in composition from step to step in splicing.

spliceosomal snRNP complex (GO:0097525) - refers to the various different snRNP complexes that contain 1 or more of the snRNAs and associated proteins, and which are **SOMETIMES** part of "the" splicesosome, aka spliceosomal complex, but which are also often found in a "free" form that is NOT associated with "the" spliceosome. Thus, these snRNP complexes are neither a type of "spliceosomal complex" or ALWAYS part_of a "spliceosomal complex"

**Comment by ValWood** [comment]
Ah right, I misunderstood, I thought the spliceosomal complex was any complex involved in splicing ..
