### ISSUE TITLE
Add part-of GO:0004843 ! thiol-dependent ubiquitin-specific protease activity to protein deubiquitination

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14479]
Currently no link between  GO:0004843 ! thiol-dependent ubiquitin-specific protease activity 

and protein deubiquitination

Note to self:

FA pathway GOCAM http://noctua.berkeleybop.org/editor/graph/gomodel:59dc728000000205

Adding USP1 to the model, this gene product deubiquitinates monoubiquitinated FANCD2, no suitably specific MF annotation was found. Seems odd to do a dual annotation here.

**Comment by ukemi** [comment]
This link seems safe since the definitions specifies the link between ubiquitin and another protein.

**Comment by ukemi** [comment]
I'm adding this now. This is a nice example of how I think the models can drive ontology development.

**Comment by ValWood** [comment]
This is only safe if there is no situation like this for ubiquitin (processing)
 http://pombase-dev.bioinformatics.nz/gene/SPBC19G7.09
and I think there must be, because ubiquitin is translated as a polyprotein that is cleaved?
This is likely also done by thiol-dependent ubiquitin-specific protease activity.....

**Comment by ukemi** [comment]
I thought about this. I'm not sure it is safe in general, but looking at the definition of this term, it seems safe. I'm just about to push the button to merge this, so let me know if you think I shouldn't. 

Catalysis of the thiol-dependent hydrolysis of a peptide bond formed by the C-terminal glycine of ubiquitin **and another protein**.

**Comment by ukemi** [comment]
I guess the 'other protein' could be ubiquitin.

**Comment by ValWood** [comment]
I think it would be weird to have the parent for  deubiquitination, but not for desumoylation.
and it could not be added for ubiquitin-like....

**Comment by ukemi** [comment]
OK. I won't merge the request. But is this really an all or none situation? Do the sumo terms have similar defs?

**Comment by ukemi** [comment]
We can't do it for all terms because for example, other molecules than proteins get ubiquitinated. But the def of this term is very specific.

**Comment by ValWood** [comment]
GO:0016929 - SUMO-specific protease activity

Definition | Parents
-- | --
Catalysis of the hydrolysis of peptide or isopeptide bonds within SUMO, or between the SUMO and a larger protein to which it has been conjugated.

def was fixed recently when we realised the activity applied to both


2017-08-23 | Added
-- | --

**Comment by ukemi** [comment]
Yes. But that would align with the more generic term:

ubiquitin-like protein-specific protease activity:
Catalysis of the hydrolysis of peptide or isopeptide bonds within small proteins such as ubiquitin or ubiquitin-like proteins (e.g. APG8, ISG15, NEDD8, SUMO), or between the small protein and a larger protein to which it has been conjugated.

The term under discussion in this ticket is more specific. Happy to close this and not merge if you have serious concerns. We can always co-annotate.

**Comment by ValWood** [comment]
Presumably we know what cleaves ubiquitin? If it is a GO:0004843 ! thiol-dependent ubiquitin-specific protease (most likely), then adding the parent will be incorrect and need unpicking later?

GO:0016929 - SUMO-specific protease activity
has 2 children "SUMO specific endopeptidase" and "SUMO specific isopeptidase". The  SUMO specific isopeptidase  can have an F-P link to desumoylation.

I will see if I can find out if ubiquitin is cleaved similarly....

**Comment by ValWood** [comment]
typed 
"what cleaves the ubiquitin pro protein" into Google.

Answer
Deubiquitinating enzymes (DUBs) are proteases that cleave ubiquitin or ubiquitin-like proteins from pro-proteins or target proteins. 

So the parent should not be added. You could create child terms mirroring SUMO, then the deubiquitination parent can be added to the  The GO:new ubiquitin specific isopeptidase 

(although I don't know about the thiol dependency and if that applies to all, presume so...)

**Comment by ukemi** [comment]
Yup. I did some digging last night and came to the same conclusion. I will close this and the related pull request. Thanks @ValWood
