### ISSUE TITLE
Documentation for Travis checks failures

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14474]
Hello, 

We will produce documentation that explains the causes of Travis checks failures

**Comment by ukemi** [comment]
I'm thinking this is now out of date. The editors understand the Travis checks.

**Comment by ukemi** [comment]
@dougli1sqrd, I'm excavating old tickets to see if I can close them. Is it possible to get a list of all the error messages that Travis gives us when the build fails? If so, I can put them all in a table with a little explanation of how to handle them and cross this ticket off my list.
