### ISSUE TITLE
NTR: Type I pilus 

### ISSUE THREAD

**Issue by cross12tamu** [geneontology/go-ontology#14470]
Potential GO term name:
Type I pilus

Definition:
Type 1 pili, which are expressed by many strains of pathogenic as well as nonpathogenic E. coli, are characterized
by their D-mannose-sensitive agglutinatination of erythrocytes.

Aspect:
Cellular Component

Relationships:
Parent terms → Pilus

References:
PMID: 28800709 
PMID: 17293518 
PMID: 11171011
PMID: 1683764 

Synonyms:
type I fimbriae
type 1 pilus
Type I pili

**Comment by cross12tamu** [comment]
@suzialeksander

**Comment by vanaukenk** [comment]
@cross12tamu @suzialeksander

I have a few questions about the term definition.  

- Are Type I pili only found in E. coli?  

- Is the agglutination of erythrocytes the main role of Type I pili, or is this one of several types of assays that can be used to characterize their function?  

Can we perhaps come up with a more general definition?

Would something like this work:

A proteinaceous hair-like appendage present on the surface of bacteria that functions in adherence of bacteria to substrates, e.g. host cells or tissues, via binding to carbohydrate-containing molecules.  Type 1 pili are expressed by many strains of pathogenic as well as nonpathogenic bacteria.

**Comment by vanaukenk** [comment]
Note for definition reference:

http://textbookofbacteriology.net/pathogenesis_3.html

**Comment by vanaukenk** [comment]
@cross12tamu @suzialeksander

Are you both okay with the more general definition suggested above?  If so, I will go ahead and add this new term.  

Thx.

**Comment by suzialeksander** [comment]
Hi,

I much prefer the updated definition.  Just mentioning @jimhu-tamu and @dsiegele  in case they want to add anything

**Comment by dsiegele** [comment]
> Can we perhaps come up with a more general definition?
> 
> Would something like this work:
> 
> A proteinaceous hair-like appendage present on the surface of bacteria that functions in adherence of bacteria to substrates, e.g. host cells or tissues, via binding to carbohydrate-containing molecules. Type 1 pili are expressed by many strains of pathogenic as well as nonpathogenic bacteria.
> 

I think the definition above is too general--it now is more like a definition for pili in general not a type of pili.  Type I pili are characterized by "their D-mannose-sensitive agglutinatination of erythrocytes," which is a widely used assay for how they are identified. Saying that type I pili are expressed by "many strains of pathogenic as well as nonpathogenic bacteria" is too broad. The mannose-sensitive type I pili are found in multiple genera among the gamma-proteobacteria (see 
GenBank entry for [FimH](https://www.ncbi.nlm.nih.gov/protein/757780849?report=genbank&log$=protalign&blast_rank=92&RID=0W535K1U015), which is the mannose binding adhesin.

I have to go give a lecture, but I will continue after class.

**Comment by jimhu-tamu** [comment]
I agree with Debby. Seems to me we should either we should capture the pilus types or get rid of the separate classification of Types within GO for the Type IV terms. Or use a different subtype classification scheme that better captures the biological distinctions, such as what is described in this recent review:

https://www.nature.com/articles/nrmicro.2017.40

In that paper, Type 1 would be subsumed in a larger class of chaperone-usher pili. Type IV would be split, and a couple of other types would be added.

**Comment by vanaukenk** [comment]
@dsiegele and @jimhu-tamu   Thanks for your feedback.

If you think it'd be useful to have more distinct pilus types. as described in that review, in GO, I'm fine with adding them.  I'd just need additional term names and defs.  Let me know.  Thx.

**Comment by vanaukenk** [comment]
@dsiegele @jimhu-tamu 

Just checking on this ticket.  Let me know if you'd still like to work on adding terms for the distinct types of pili.

Thx.

**Comment by pgaudet** [comment]
It seems strange that we only have Type IV.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140621
+name: type I pilus
+namespace: cellular_component
+def: "A short filamentous structure on the surface of a bacterial cell distinguished from other pili by their D-mannose-sensitive agglutinatination of erythrocytes. In E. coli, type I pili consist of a short tip fibrillum made up of the adhesin protein (FimH) and two minor subunits (FimG and FimF) that is joined to the pilus rod, a homopolymer of ~1000 FimA subunits." [PMID:28496159, PMID:29345620]
+synonym: "type 1 pilus" EXACT []
+synonym: "type I fimbriae" EXACT []
+synonym: "type I pili" EXACT []
+is_a: GO:0009289 ! pilus
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/14470 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-10T10:24:04Z
+
