### ISSUE TITLE
grouping under phosphatase children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14471]
Not very urgent but would improve annotation specificity under
https://www.ebi.ac.uk/QuickGO/term/GO:0016791

I have seen users stop at "phosphatase". Because there are so many child terms they don't spot "phosphoprotein phosphatase". This means they they miss  the option to specify the protein substrate (in our tool they are prompted for the protein substrate if they use this term).

I wondered if there could be some "chemical grouping" like "sugar phosphatase"  or "sugar-derivative phosphatase" so that the list size is reduced?

Also, some terms should be moved under phosphoprotein phosphatase.
 myosin-light-chain-phosphatase activity
GO:0004647    phosphoserine phosphatase activity ? (I think this is a protein specific term?)

**Comment by ukemi** [comment]
I'm not sure about the phosphoamino-acid phosphatase terms. Are there phosphatases that work on the free phosphoamino acids? I'll check the other children.
