### ISSUE TITLE
mRNA (adenine-N1-)-methyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#14486]
Hi, I would need the following term for this new methyltransferase activity.

Thanks

Sylvain

Name: mRNA (adenine-N1-)-methyltransferase activity

Category: Molecular function

Definition: Catalysis of the reaction: S-adenosyl-L-methionine + adenine in mRNA = S-adenosyl-L-homocysteine + N(1)-methyladenine in mRNA.

Child of: GO:0008174 mRNA methyltransferase activity
Reaction in Rhea: Rhea:55392
PMID:29072297;
RA Safra M., Sas-Chen A., Nir R., Winkler R., Nachshon A., Bar-Yaacov D., Erlacher M., Rossmanith W., Stern-Ginossar N., Schwartz S.
RT The m(1)A landscape on cytosolic and mitochondrial mRNA at single-base resolution.
RL journal article: Nature 0:0-0 (2017)

**Comment by ukemi** [comment]
Hi Sylvain,

Is the Rhea cross-ref pending. I don't see it? I am adding the term without it for now.

-D
