### ISSUE TITLE
Check if transporters can be moved as transmembrane transporters

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14492]
These are the direct children of transporter activity; they sound like they might be transmembrane transporters: 

- Rename, merge or obsolete as appropriate
- Fix textual definitions according to http://wiki.geneontology.org/index.php/Transporter_terms_standard_definitions ("Enables the transfer of X from one side of a membrane to the other. X is [insert description]. ")

GO ID  - Label | Annotations | Action
---|---|---
GO:0015231 5-formyltetrahydrofolate transporter activity | 2 TAIR protein annotated OK TM proteins |Rename TM and move
GO:0090440 abscisic acid transporter activity | 2 TAIR protein annotated OK TM proteins |Rename TM and move
GO:0008521 acetyl-CoA transporter activity | 4 manual annotations (no EXP) OK TM proteins  |Rename TM and move
GO:0015240 amiloride transporter activity | No annotations |Rename TM and move
GO:0015247 aminophospholipid transporter activity | 5 EXP annotations- OK TM proteins  |Rename TM and move
GO:0015241 aminotriazole transporter activity | No annotations |Merge with TM child
GO:0042895 antibiotic transporter activity | 12 EXP annotations- OK TM proteins  |Rename TM and move
GO:1903962 arachidonate transporter activity  | No annotations |Rename TM and move
GO:0045118 azole transporter activity | 5 EXP annotations- OK TM proteins  |Move into TM (GO:1901474) no direct annotations
GO:0015545 bicyclomycin transporter activity  | No annotations |Rename TM and move
GO:0015224 biopterin transporter activity  | 8 ISS (no with) |Rename TM and move
GO:0015225 biotin transporter activity | 5 EXP | Rename TM and move
GO:0015549 carbonyl cyanide m-chlorophenylhydrazone transporter activity | No annotations |Rename TM and move
GO:0038024 cargo receptor activity | NOT TM | **To review**
GO:1902388 ceramide 1-phosphate transporter activity  |  NOT TM  - intramembrane|  **Transfer** 
GO:0035620 ceramide transporter activity | **Must review annotations - mix transporter/carrier 8 EXP** | No action yet
GO:0042896 chloramphenicol transporter activity | No annotations |Rename TM and move
GO:0017127 cholesterol transporter activity |**Must review annotations - mix transporter/carrier 22 EXP** | No action yet
GO:1990833 clathrin-uncoating ATPase activity | OK not a transporter | No action needed
GO:0015235 cobalamin transporter activity | OK 1 ABC transporter, 1 endocytic transporter (challenged here:https://github.com/geneontology/go-annotation/issues/1685); other annotation is to an ABC transporter   | Merge into GO:0015420 cobalamin-transporting ATPase activity
GO:0051185 coenzyme transporter activity  | No direct annotations |Rename TM and move
GO:0051184 cofactor transporter activity  | No direct annotations |Rename TM and move
GO:0015243 cycloheximide transporter activity  | No annotations |Rename TM and move
GO:0033300 dehydroascorbic acid transporter activity | 12 EXP all SLC | Rename TM and move
GO:0042936 dipeptide transporter activity | **Must review annotations**  | No action yet
GO:0090484 drug transporter activity | 1 EXP annotation, multidrug resistance protein | Merge into TM child GO:0015238 
GO:0098748 endocytic adaptor activity  | OK not a transporter |  No action needed
GO:0015245 fatty acid transporter activity | OK all TM except  A0A1D5NW85 (disputed in P2GO) |Rename TM and move
GO:0015246 fatty-acyl group transporter activity | No annotation. This term is not useful | merge with GO:0015246 
GO:0015244 fluconazole transporter activity  | 7 EXP | Rename TM and move
GO:0008517 folic acid transporter activity | All TM, except for proteins belonging to pthr10517; disputed annotation (3 EXP) | Rename TM and move
GO:0042898 fosmidomycin transporter activity | 1 ISS (no with) |Rename TM and move
GO:0017089 glycolipid transporter activity | more chaperone | ? 
GO:0034202 glycolipid-translocating activity | 3 NOT; 1 EXP |  **Flippases**
GO:0034437 glycoprotein transporter activity | 2 EXP annotations: one indirect, one possibly endocytosis | ? 
GO:0015232 heme transporter activity
GO:0005319 lipid transporter activity
GO:0015648 lipid-linked peptidoglycan transporter activity | 3 EXP annotations to 2 proteins, flippases | *Move to some flippase term*
GO:0042954 lipoprotein transporter activity | rather **cargo**  | 
GO:0005324 long-chain fatty acid transporter activity
GO:0015350 methotrexate transporter activity  | 7 EXP  - all TM| Rename TM and move
GO:0061717 miRNA transporter activity  | OK not a TM transporter (nucleocytoplasmic) |  No action needed
GO:0090417 N-methylnicotinate transporter activity  | 1 EXP  -  TM| Rename TM and move
GO:0051724 NAD transporter activity   | 8 EXP  -  TM|  Merge with GO:1901368 TM transporter (1 annot ISO Pombase yea6) ; add 'carrier' as synonym
GO:0005326 neurotransmitter transporter activity | Some exocytosis see PMID:15911881  |  No action yet
GO:0090416 nicotinate transporter activity | 3 EXP  -  TM | Rename TM and move
GO:0005487 nucleocytoplasmic transporter activity |  |  No action yet- see #14336
GO:1901480 oleate transporter activity | No annotation - xref to http://www.rhea-db.org/reaction.xhtml?id=33658 -Added reference PMID:  19493158  | Rename TM and move
GO:0015198 oligopeptide transporter activity | 17 EXP | merge into TM child GO:0035673 - 59  #EXP
GO:0015548 organomercurial transporter activity | No annotation | added a reference and renamed TM
GO:0005344 oxygen carrier activity | OK not transporter | No action needed
GO:0015197 peptide transporter activity | 13 direct EXP - all TM **except MGI:1916147** which may be exocytosis  **Review annotations** | 
GO:1990050 phosphatidic acid transporter activity | transfer rather than transport ? See PMID:26235513, PMID:23931759, PMID:9132017, PMID:26203165
GO:0008525 phosphatidylcholine transporter activity | Mix transport - flippase | **To review** 
GO:1904121 phosphatidylethanolamine transporter activity | Mix transport - flippase | **To review** 
GO:0008526 phosphatidylinositol transporter activity |  all **transfer**  
GO:0005548 phospholipid transporter activity
GO:0071991 phytochelatin transporter activity | No direct annotations; two children: GO:0071992 phytochelatin transmembrane transporter activity and GO:0044604 phytochelatin transmembrane transporter ATPase activity; all annotated proteins are ABC transporters, so do a 3-way merge into GO:0044604  | Merge into child TM transporter
GO:0042897 polymyxin transporter activity | No annotations |Rename TM and move
GO:0008565 protein transporter activity | **To review** for ex importins, karyopherins are annotated 
GO:0034632 retinol transporter activity | 4 EXP - STRA6 OK; other annotations under review https://github.com/geneontology/go-annotation/issues/1684 | Rename TM and move
GO:0032217 riboflavin transporter activity | 17 EXP - TM transporters, see PMID:    20463145 | Rename and fix def
GO:0015306 sialate:cation symporter activity |  already a child of TM transport | added 'symporter activity' in equi axiom like neighboring terms' | 
GO:0046624 sphingolipid transporter activity | Mix transport - flippase | **To review** 
GO:0015248 sterol transporter activity | Many TM, but others such as P22059 (chaperone?) 
GO:0022892 substrate-specific transporter activity | | Merged with parent see  ##14491
GO:0008493 tetracycline transporter activity | No annotations |Rename TM and move
GO:0090422 thiamine pyrophosphate transmembrane transporter activity | Already TM  | Fix logical definition
GO:0042937 tripeptide transporter activity
GO:0031924 vitamin B6 transporter activity | Single InterPro | Rename TM and fix def
GO:0051183 vitamin transporter activity  | No direct annotations; all children are now TM; merge with TM transporter GO:0090482

**Comment by ValWood** [comment]
GO:0098748 endocytic adaptor activity shouldn't be under transporter?
GO:0005344 oxygen carrier activity shouldn't be under transporter (I thought you removed that parent already?)

**Comment by ValWood** [comment]
Hmm, the term "transmembrane transporter activity" seems to have  disappeared?
At least I can't find it?

**Comment by pgaudet** [comment]
http://amigo.geneontology.org/amigo/term/GO:0022857

**Comment by ValWood** [comment]
Got it!

**Comment by ValWood** [comment]
these are things I have annotated to "transporter activity"

1
GO:0030121 - AP-1 adaptor complex (I don't think this is, IEA from Interpro)
GO:0030122 - AP-2 adaptor complex (I don't think this is, IEA from Interpro)
GO:0030123 - AP-3 adaptor complex ((I don't think this is, IEA from Interpro)

2. Nuclear import and export receptors:
http://pombase-dev.bioinformatics.nz/term/GO:0005487
I think you were going to rehouse as "carriers"?

3.GO:0031207 - Sec62/Sec63 complex
All from InterPRo mappings (I don't think this is a transporter, it seems like a "carrier"?
..the translocon is the transporter?


4. GO:0042719 - mitochondrial intermembrane space protein transporter complex
seems OK

5. GO:0005742 - mitochondrial outer membrane translocase complex
seems ok

6. Sec61 translocon complex (GO:0005784)
seems OK


7. GO:0004012 - phospholipid-translocating ATPase activity
Is not *trans* membrane, does not traverse the bi layer, moves lipids from one bilayer to the other. I don't know  how these should be classified (membrane lipid translocator?), but not transmembrane

8. This one is tricky...
There is a domian  http://pfam.xfam.org/family/PF03765
called CRAL/TRIO
 We have routinely annotated these as
phosphatidylcholine transporter activity
 phosphatidylinositol transporter activity
based on similarity. They aren't TM transporters but I have never been able to establish exactly what they do. (They might be translocators?, or carriers?)


I have a couple more, they might be annotation errors..... checking now

**Comment by pgaudet** [comment]
So you seem to be using this term for
- vesicle-mediate transport 
- protein sorting to mitochondrion
- flippase or whatever 
Yes these will be the terms left when I finish this batch. We'll open a new ticket to deal with them. 

Thanks, Pascale

**Comment by ValWood** [comment]
All of the "vesicle-mediated transport" ones appear to come from misapplied  InterPro mappings. I am opening tickets to remove them now....

**Comment by ValWood** [comment]
9.
long-chain fatty acid transporter activity
This one seems to be equivalent  to

https://www.ebi.ac.uk/QuickGO/term/GO:0000036
at least as used here
https://www.yeastgenome.org/locus/S000003269

Acyl-CoA-binding protein; transports newly synthesized acyl-CoA esters from fatty acid synthetase (Fas1p-Fas2p) to acyl-CoA-consuming processes

**Comment by ValWood** [comment]
Could you rehouse

GO:0098748 endocytic adaptor activity shouldn't be under transporter?
GO:0005344 oxygen carrier activity shouldn't be under transporter (I thought you removed that parent already?)
GO:0038024 cargo receptor activity

nucleocytoplasmic transport import and export receptor terms (carrier?)
GO:0061608    nuclear import signal receptor activity
GO:0005049    nuclear export signal receptor activity

as detailed in other tickets?
That would help to see what is left...

**Comment by ValWood** [comment]
More on 8. above. I dug around some more and CRAL-TRIO appear to be involved in the transfer * between different*  intracellular membranes....
The other thing I found involved in "intermembrane transfer" "ERMES complex" 

We already have terms in GO:
GO:0120009    intermembrane lipid transfer
GO:0120013    intermembrane lipid transfer activity

Cak trio:
https://en.wikipedia.org/wiki/CRAL-TRIO_domain
Ermes:
lipid transfer between membranes by Mmm1-Mdm12 of ERMES.PMID: 29279306

**Comment by pgaudet** [comment]
Left to do: 

* GO:0015232 heme   transporter activity  - see    #14892

* lipid transporters - see 14892

GO:1902388 ceramide   1-phosphate transporter activity | NOT   TM  - intramembrane | **Transfer**
-- | -- | --
GO:0035620 ceramide transporter   activity | **Must review annotations - mix   transporter/carrier 8 EXP** | No action yet
GO:0017127 cholesterol transporter   activity | **Must review annotations - mix transporter/carrier 22 EXP** | No action yet
GO:0017089 glycolipid transporter   activity | more chaperone | ? |  
GO:0034202 glycolipid-translocating   activity | 3 NOT; 1 EXP | **Flippases**
GO:0034437 glycoprotein transporter   activity | 2 EXP annotations: one indirect,   one possibly endocytosis | ? |  
GO:0015648 lipid-linked peptidoglycan   transporter activity | 3 EXP annotations to 2 proteins,   flippases | *Move to some flippase term*
GO:0005319 lipid transporter activity |   |   |  
GO:0042954 lipoprotein transporter   activity | rather **cargo** |   |  
GO:0005324 long-chain fatty acid   transporter activity |   |   |  
GO:0008525 phosphatidylcholine   transporter activity | Mix transport - flippase | **To review**
GO:1904121 phosphatidylethanolamine   transporter activity | Mix transport - flippase | **To review**
GO:0008526 phosphatidylinositol   transporter activity | all **transfer** |   |  
GO:0005548 phospholipid transporter   activity |   |   |  
GO:0008565 protein transporter   activity |   | **To review** for ex importins, karyopherins   are annotated
GO:0046624 sphingolipid transporter   activity | Mix transport - flippase | **To review**
GO:0015248 sterol transporter   activity | Many TM, but others such as P22059   (chaperone?) |
