### ISSUE TITLE
update equivalence axiom for GO:0015165 - pyrimidine nucleotide-sugar transmembrane transporter activity

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#14494]
This term seems like it needs an update to its equivalence axion 
`'transmembrane transporter activity'`
` and ('transports or maintains localization of' some 'pyrimidine nucleotide-sugar')`

to be consistent with its name and definition to indicate:
`     and ('results in transport across' some membrane)`

**Comment by pgaudet** [comment]
Hi @cmungall 

I would like to know what is the difference bewteen 

'transmembrane transporter activity'
and ('transports or maintains localization of' some 'pyrimidine nucleotide-sugar')


and 
'transporter activity'
and ('transports or maintains localization of' some 'pyrimidine nucleotide-sugar')
and ('results in transport across' some membrane)

I don't think that there is difference in the logic; but should we favor one over the other ?

**Comment by RLovering** [comment]
Hi
I think you have got the wrong definition for transporter activity, this is: Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells.
But not sure how this fits with the discussion above
sorry
Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 
I am not sure how this fits either. But the definition for transmembrane transporters is now 'Enables the transfer of a pyrimidine nucleotide-sugar from one side of a membrane to the other. '; does that not seem OK to you ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
see #14436

**Comment by RLovering** [comment]
yes, that definition looks like it follows other similar definitions
Thanks
Ruth

**Comment by ValWood** [comment]
1. Is this about "transporter activity/transmembrane transporter activity

OR
2. pyrimidine nucleotide-sugar transporter activity/pyrimidine nucleotide-sugar transmembrane transporter activity

I would be concerned if 1, but if 2 I can ignore ;)

**Comment by pgaudet** [comment]
I (try to) will create a design pattern based on 
'transporter activity'
and ('transports or maintains localization of' x')
and ('results in transport across' some membrane)

**Comment by pgaudet** [comment]
I have created the design pattern (https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/mf_transmembrane_transporter_activity.yaml) using 
'transmembrane transporter activity'
and ('transports or maintains localization of' some 'pyrimidine nucleotide-sugar')

... otherwise it's not possible to create logical definitions for other types of transmembrane transporters such as antiporters, synporters and channels. 

I am going to standardize the logical axioms as much as I can. 

Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/issues/14580

**Comment by pgaudet** [comment]
I think I fixed all TM transporters, using the pattern 

'transmembrane transporter activity'
and ('transports or maintains localization of' some 'xxx')

Thanks, Pascale

**Comment by pgaudet** [comment]
See also https://github.com/geneontology/go-ontology/tree/master/src/design_patterns
