### ISSUE TITLE
'existence ends during' some 'fully formed stage, in go-plus

### ISSUE THREAD

**Issue by alanruttenberg** [geneontology/go-ontology#14501]
The results of this query didn't make sense to me. Are they intended?

existence ends during: Relation between continuant c and occurrent s, such that every instance of c ceases to exist during some s, if it does not die prematurely.

fully formed stage: The stage of development at which the animal is fully formed, including immaturity and maturity. Includes both sexually immature stage, and adult stage. 
Axiom: precedes some 'death stage'

among the results: arm, brain, skeletal system, respiratory system.
(they seem pretty essential if you are in the fully formed stage, given you are not dead yet) 

I know getting old sucks, but didn't know it sucked this bad...

**Comment by ValWood** [comment]
@cmungall  this is quite old. Is it fixed?

**Comment by pgaudet** [comment]
Looks like this is still the case

**Comment by pgaudet** [comment]
Maybe these relations are so general that this query isn't expected to provide useful results. 

@alanruttenberg this query should be addressed to Uberon, GO gets these relations from Uberon.
