### ISSUE TITLE
Ontology Issues

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#14508]
_From @nstickney on September 22, 2017 16:35_

The latest go.obo file available from `purl` today has some errors. If this is the wrong place to post this, please let me know!
- There is overlap between two namespaces:
    - GO:0038071 (`molecular_function`) `part_of` GO:0071507 (`biological_process`)
- There is cycle in the `molecular_function` namespace:
    - **GO:0042623** `is_a` GO:0016887 `part_of` GO:0061860 `is_a` GO:0003677 `part_of` GO:0015616 `is_a` GO:0008094 `is_a` **GO:0042623**

_Copied from original issue: geneontology/helpdesk#58_

**Comment by kltm** [comment]
@nstickney While this may not be a final home, this is a fine place to start.
@cmungall Would you have any ideas about this?

**Comment by pgaudet** [comment]
Should we fix these manually ?

**Comment by ukemi** [comment]
Seems like this is a pipeline issue. In the full ontology, it should be ok for functions to be part_of processes. In fact, there should be lots of them.

**Comment by nstickney** [comment]
@ukemi
> In the full ontology, it should be ok for functions to be part_of processes. In fact, there should be lots of them.

Well, I've listed the only one that exists. I believe the idea of them being different ontologies is that they are separate (though that sounds like a tautology). If the intent was overlap, I would expect to find many more than just this one.

There is an entirely different question though of looping; by definition, an ontology is a directed _acyclic_ graph, right?

**Comment by ukemi** [comment]
Ah yes. We need to investigate the second point further. @pgaudet this looks like it might be due to the recent ATPase edits????

**Comment by ukemi** [comment]
I still think this might be a pipeline issue. Looking at the editor's version of the ontology, I don't see these as being asserted. For the cycle, it looks like in the pipeline we might be using has_part inverse of part_of at the class level. @cmungall any ideas?
@pgaudet , this part of the graph does look like it needs some close investigation in any case.

**Comment by pgaudet** [comment]
Hi @ValWood 
Can you please check whether 'GO:0061860 DNA clamp unloader activity' should have 'has_part' ATPase activity? I dont see evidence of that either in the genes annotated (PMID:16040599) or in the paper cited for the term (PMID:23499004). 

@cmungall @ukemi 
I dont see the cycle there. One innacurate statement above is that 
GO:0061860 -DNA clamp unloader activity (HAS_PART GO:0016887 ATPase activity (no part_of). 

I am removing that relation, hopefully that fill fix the problem.

**Comment by ValWood** [comment]
I don't know if both loading an unloading require ATP...I did the annotation from complex membership (IC), because unloading is the function of this particular complex.

**Comment by pgaudet** [comment]
Well this is a bit complicated - if we don't know perhaps we shouldn't make these statements ? 

What I now did is to replace  _has_part GO:0016887 ! ATPase activity_
by _is_a: GO:0042623 ! ATPase activity, coupled_

to match the clamp loader parent (and taking into account that some role for ATP hydrolysis was already present). Hopefully that seems OK to you @ValWood 

Thanks, Pascale

**Comment by ValWood** [comment]
well 
GO:0008094   DNA-dependent ATPase activity
is_a 
GO:0042623  ATPase activity, coupled

and loats of other  coupled ATPases have already had this parent

For example there is a precedent for a similar arrangement under helicases:
https://www.ebi.ac.uk/QuickGO/term/GO:0004003

 But I'm not sure what the exact issue is?

**Comment by pgaudet** [comment]
@kltm @nstickney 

- I replaced has_part GO:0016887 ! ATPase activity
by is_a: GO:0042623 ! ATPase activity, coupled
- GO:0038071 is obsolete; I am not sure what is creating the problem. 

Please let me know if that resolved the issue. 

Thanks, Pascale

**Comment by nstickney** [comment]
@pgaudet The loop issue is resolved, given the assumption that `has_part` and `is_part` are not meant to be inverses.

GO:0015616 >is_a> GO:0008094 >is_a> GO:0042623 >is_a> GO:0016887 <has_part< GO:0061860 >is_a> GO:0003677 <has_part<  GO:0015616

**Comment by pgaudet** [comment]
@cmungall - can you answer that ? I though has_part and is_part were reciprocal but then I don't understand why not all terms in that branch don't cause the same problem. 

Pascale

**Comment by nstickney** [comment]
> I thought has_part and is_part were reciprocal
It seems logical, and tools such as [pronto](https://pypi.python.org/pypi/pronto) work from that assumption.

**Comment by cmungall** [comment]
Hi @nstickney - part_and has_part are indeed mutually inverses, but this applies to individuals. the ontology makes class-level assertions. We should have a FAQ entry about this.

If pronto is making an incorrect assumption we should file a bug in their tracker.

Note for your purposes you may want go-basic.obo

http://geneontology.org/page/download-ontology

**Comment by nstickney** [comment]
@cmungall Thanks!
