### ISSUE TITLE
RO part of not reflexive in GO plus

### ISSUE THREAD

**Issue by alanruttenberg** [geneontology/go-ontology#14502]
There are two relations "part of" in GO-Plus. Neither is reflexive.

**Comment by alanruttenberg** [comment]
There are also 3 has part relations. It's rather confusing in protege. I'd suggest either unifying them (with equivalentProperties), or naming them distinctly.

**Comment by cmungall** [comment]
Thanks. As to the first part, looks like we need to do more tidying of our import chain (though really some of this needs to be pushed upstream, e.g. to SO). 

For the reflexivity axiom (which must be local reflexivity) see https://github.com/oborel/obo-relations/issues/151

**Comment by balhoff** [comment]
With the import pipeline we have now, GO will reflect whatever property characteristics are defined in RO. I only find one 'has part' now. There does seem to be rogue 'part of' defined by DDANAT; I opened a ticket there (https://github.com/dictyBase/migration-data/pull/12).
