### ISSUE TITLE
Dynamin-like name revision

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14511]
Hi David

following the Autophagy editor suggestions I think it would be best to change the name of this one. I think Dynamin-like may get confused with Dynamin family.

So revise the name and definition of:

GO:0061735: dynamin-like protein-mediated stimulation of mitophagy in response to mitochondrial depolarization

To 
GO:0061735: DNM1L-mediated stimulation of mitophagy in response to mitochondrial depolarization
The definition is: A positive regulation of the macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a DNM1L-family molecule.

exact synonym:
dynamin-like protein-mediated stimulation of mitophagy in response to mitochondrial depolarization

Note I have added 'family' at the end of the definition, to align this with the equivalent parkin term, where I am assuming 'family' refers to orthologs rather than paralogs? But I don't think 'family' has to be included so ignore if not required.

Please confirm if you agree with the change name and I will update Table S1. If you don't agree let me know and I will inform the editor.

Thanks

Ruth

**Comment by ukemi** [comment]
This looks fine to me. @paolaroncaglia  ?

**Comment by paolaroncaglia** [comment]
Yes, fine with me too, thanks.
