### ISSUE TITLE
name modification: piecemeal microautophagy of the nucleus

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14512]
Hi David

Following from the Autophagy editors comments. In the phrase 'ATG1/ULK1 ', ULK1 is the human gene symbol, but Atg1 is the symbol used in other species. As all other Atgs listed in GO term names are in the format Atg# I think it would be sensible to revise the names of all the 5 terms which have ATG1/ULK1 and instead use Atg1/ULK1. AND revise the definitions (edits not listed here)

 GO:1904745 ATG1/ULK1 kinase complex assembly
change to  GO:1904745 Atg1/ULK1 kinase complex assembly

 GO:1905864 regulation of ATG1/ULK1 kinase complex assembly
 change to: regulation of Atg1/ULK1 kinase complex assembly

GO:1905865 negative regulation of ATG1/ULK1 kinase complex assembly
 change to: negative regulation of Atg1/ULK1 kinase complex assembly

GO:1905866 positive regulation of ATG1/ULK1 kinase complex assembly
 change to: positive regulation of Atg1/ULK1 kinase complex assembly

 GO:1990316 ATG1/ULK1 kinase complex
change to:  Atg1/ULK1 kinase complex

Please confirm if you agree and I will revise Table S1

Thanks 

Ruth

**Comment by paolaroncaglia** [comment]
I do not disagree with having 'Atg1' instead of 'ATG1' if this is used to refer to a broader range of species (i.e. not just human, where the correct format is ATG1). So ok with me. Thanks.
