### ISSUE TITLE
rename   ATG1/ULK1 kinase complex

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14525]
Hi 

Continuation of requests following review of Autophagy paper

I think that GO:1990316 ATG1/ULK1 kinase complex should be renamed 'Atg1/ULK kinase complex'.  ie 'ULK1' replaced with 'ULK'

Several papers describe the ULK1/2 complex as the mammalian ortholog of the yeast Atg1 complex.
eg: PMID: 28976798: The ULK1/2 complex is the mammalian ortholog of the yeast Atg1 complex.
PMID:27765496:  The ULK complex is composed of protein kinases ULK1 and ULK2 in association with....
PMID: 26921696: calls the complex the ULK1 complex but also points out that: ULK1 and ULK2 show high functional redundancy; both must be knocked out in mouse embryonic fibroblasts to robustly inhibit nutrient-dependent autophagy [17].

Also the other GO terms with 'ATG' use the format 'Atg'

Then the definition would need revising too
A protein complex consisting of **Atg1/ULK** and **Atg13** along with other proteins that regulate its function (e.g. **Atg17** in yeast or RB1CC1(FIP200) in mammals). This complex has serine/threonine protein kinase activity and is involved in autophagosome formation.

Unfortunately if you agree there are 4 other terms name to rename, and term definitions. 
 GO:1904745 ATG1/ULK1 kinase complex assembly
 GO:1905864 regulation of ATG1/ULK1 kinase complex assembly
 GO:1905866 positive regulation of ATG1/ULK1 kinase complex assembly
 GO:1905865 negative regulation of ATG1/ULK1 kinase complex assembly

What do you think?

Ruth

**Comment by ukemi** [comment]
We should use the name that is most commonly used in the community as the primary name, as long as it does not conflate terms. We can add the others as exact synonyms. This is standard GO policy.

**Comment by RLovering** [comment]
Thanks David

Looking at this 
ATG1/ULK1 kinase complex 34 papers
ATG1/ULK kinase complex 8 papers (at least on using term above too)
ATG1/ULK1 complex 38 papers
ULK1 complex 209 papers
ULK1 kinase complex 22 papers
ULK complex 39 papers
There are also lots of other variations on this ;(

Let's leave the ULK part of the name as it is, but I think the ATGs need to change to Atg as this is definately being used more in both GO and literature. 
And add aliases:
ULK1 complex
ULK complex

Will you have time to do this before your holiday?

Best

Ruth

**Comment by RLovering** [comment]
new definition:
A protein complex consisting of Atg1 (or Atg1 homologs e.g. ULK1, ULK2 in mammals) and Atg13 along with other proteins that regulate its function (e.g. Atg17 in yeast or RB1CC1(FIP200) in mammals). This complex has serine/threonine protein kinase activity and is involved in autophagosome formation.

It isn't clear to me that all complexes have ULK2 or ULK1, as there is functional redundancy. So I have left the definition rather vague. Will that be ok?

**Comment by ukemi** [comment]
I actually thought I got all of the ATG-->Atg changes yesterday, but I will double-check. I will add the aliases as you suggest. I think the suggested definition is fine. I will do these edits this afternoon.

**Comment by RLovering** [comment]
excellent
I hadn't realise you had done the Atgs, I was looking at QuickGO which is probably out of sync with you

Ruth
