### ISSUE TITLE
Merge GO:0033170 protein-DNA loading ATPase activity and GO:0003689 DNA clamp loader activity? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14535]
Hello, 

Is there a difference between (1) GO:0033170 protein-DNA loading ATPase activity and (2) GO:0003689 DNA clamp loader activity? 

(1) GO:0033170 protein-DNA loading ATPase activity 
Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the assembly of a protein or protein complex onto a DNA molecule. Source: GOC:vw, GOC:mah

(2) GO:0003689 DNA clamp loader activity? 
Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the opening of the ring structure of the PCNA complex, or any of the related sliding clamp complexes, and their closing around the DNA duplex. Source: PMID:16082778, GOC:vw, GOC:mah

(2) is the single descendant of (1) and has no annotations. 

@ValWood @mah11 

Thanks, Pascale

**Comment by ValWood** [comment]
yep.... there are different mechanisms  for the ATPase which results in  topological entrapment

https://www.ebi.ac.uk/QuickGO/term/GO:0061776

We did not create a term for this yet because we could not yet describe the mechanism. Its clearly quite a different activity though.... the clamp holds the DNA tightly but the topological entrapment encircles the DNA loosely...

**Comment by ValWood** [comment]
We have 10 annotations to DNA clamp loader activity?

**Comment by pgaudet** [comment]
Right, it's 'protein-DNA loading ATPase activity' that has no annotations. 

Seems to me you need extra children for 'DNA clamp loader activity', but the phrase 'protein-DNA loading ATPase activity' seems obscure to me. I don't mind leaving it in if it's needed though.

**Comment by mah11** [comment]
In addition to what Val says, merging these terms would imply that only sliding clamps are loaded onto DNA by other proteins that have ATPase activity. I'm not sure that's true.

The potential for other terms to be is_a GO:0033170 was acknowledged when GO:0033170 was added (old SF ticket, represented by #4085 here), but none could be defined at that time.

**Comment by ValWood** [comment]
We did this "GO:0003689 DNA clamp loader activity"
 so that we could distinguish between "clamp loaders" and "clamp  unloaders"

but there are various types of "protein DNA loading ATPase" ...eventually there will be children to describe these I guess because they have different biochemical activities? Some might also  include topological or geometric changes to the DNA.

Some  ATPases catalyse  both load and unload depending on context.....

**Comment by pgaudet** [comment]
It looked like all clamp loaders were ATPases, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2691718/

But OK, I'm happy to leave this as-is. 

Thanks, Pascale

**Comment by mah11** [comment]
> It looked like all clamp loaders were ATPases

They could well be, but that's not the point. GO:0033170 is for proteins that have ATPase activity, and load some protein(s) onto DNA, but are _not_ clamp loaders (they load something other than a sliding clamp).

**Comment by pgaudet** [comment]
Ah ! Got it. Would this be an another example? http://www.uniprot.org/uniprot/P09119 "Interacts with the origin recognition complex (ORC) and MCM2-7 helicase complex leading to the linking of those complexes and loading of the replicative helicase MCM2-7 onto the pre-replicative complexes. "?

**Comment by ukemi** [comment]
I think this is also an example. #14205

**Comment by ukemi** [comment]
Note also that the clamp loader has a topological linking constraint in the differentia. The generic term does not.

**Comment by ValWood** [comment]
This might not be totally the best way to represent these, but I think it enables us to annotate quite well with current knowledge. It may turn  out that unloading and loading part are better in process only once the molecular details are figured out more fully.

**Comment by ValWood** [comment]
yes #14205 is a great example of this. I tried (and failed) to do this one in a CAM model at the workshop in Hinxton. We just don't quite have the details we need to  figure out  whether things are MF or BP even with a nice in vitro assay of the components loading and unloading onto the DNA!

**Comment by pgaudet** [comment]
OK. I came across this while looking at #14508 - Ill try to concentrate on that one ;) 

Thanks, Pascale
