### ISSUE TITLE
NTR: iron-sulfur cluster carrier activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#14539]
As a child of GO:0140104 molecular carrier activity.  Possible definition: Assists in the delivery of iron-sulfur clusters to target proteins.

Example: NfuA in E. coli is an iron-sulfur cluster carrier (PMID 22966982) that was just recently shown to transfer its Fe-S cluster to lipoate synthase, whose own cluster is used as the source of sulfur in the lipoate biosynthesis reaction (PMID 29051382).

Thanks,
Ingrid

**Comment by pgaudet** [comment]
Hi @keseler 
Would it be OK for you if I used the same definition as that of 'sulfur carrier activity 'Covalently binding to sulfur and delivering it to an acceptor molecule.' , ie Covalently binding to an iron-sulfur cluster and delivering it to an acceptor molecule.'? 

Thanks, Pascale

**Comment by keseler** [comment]
Sorry I didn't comment sooner - PTO on Friday...  Obviously you noticed the problem with "covalent binding" yourself. :-)  Thanks!
