### ISSUE TITLE
obsolete GO:1901487

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14544]
only used by pombe..

GO:1901487   
negative regulation of SREBP signaling pathway by positive regulation of transcription factor catabolic process in response to increased oxygen levels

.I did the response to hyperoxia with an extension (more consistent with our other annotation instead), so this one can go...

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete  'GO:1901487 negative regulation of SREBP signaling pathway by positive regulation of transcription factor catabolic process in response to increased oxygen levels’. 

The reason for obsoletion is that this is better captured in a GO-CAM model. Please add any comments to the issue: https://github.com/geneontology/go-ontology/issues/14544

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Nov 16, 2017. Unless objections are received by Nov 16,2017, we will assume that you agree to this change.


Thanks, Pascale
