### ISSUE TITLE
NTR:syncytial embryo cellularization terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14543]
Could I please have these terms:

BP:
syncytial embryo cellularization
Def:The separation of the syncytial embryo into individual cells.
Ref:PMID:27226317
Is_a cellularization GO:0007349
part_of embryo developmentGO:0009790

CC:
cellularization cleavage furrow 
Def:Plasma membrane invagination at the site of separation of a multi-nucleate cell or syncytium into individual cells.
Ref:PMID:27226317
Is_a cleavage furrow GO:0032154

cellularization cleavage furrow invagination front
Def:The base of the cellularization invagination or cleave furrow most distal to the original multi-nucleate cell or syncytium plasma membrane.
Ref:PMID:27226317
Is_a cellularization cleavage furrow

**Comment by vanaukenk** [comment]
@hattrill - just wanted to double-check the relationship between the last term, 'cellularization cleavage furrow invagination front', and 'cellularization cleavage furrow'.  
It says 'is_a cellularization cleavage furrow', but the definition sounds more like a 'part_of' relation.  If 'part_of', then we'll need an is_a parent.  Thx.
I'm looking at the relation betweeen 'cleavage furrow' and 'cleavage furrow leading edge' as an analogous situation.  Thx.

**Comment by hattrill** [comment]
Yes - you are right. It should be a part_of - I think that's what I meant to do but messe it up somehow.

**Comment by vanaukenk** [comment]
Okay, no worries.  
One other question, though, as I was looking at the parentage for the CC and BP terms.
Do you think that GO:0007349 'cellularization' should also have is_a parentage to GO:0051301 'cell division'?  Given the definition of 'cell division', that parentage seems appropriate.
Having that additional parentage would then make for better correspondence in the BP and CC branches of the ontology where GO:0032154 'cleavage furrow' is defined as a GO:0032155 'cell division site part'.

**Comment by hattrill** [comment]
Yes, I agree. The definition seems to think. 
And, wrt the syncytium, it's just a big, multinucleated cell, so doesn't break anything there.
