### ISSUE TITLE
Voltage gated sodium channel activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14558]
Hi @dosumis 
I just noticed that 'GO:0005248 voltage-gated sodium channel activity' 
is_a ''voltage-gated ion channel activity involved in regulation of postsynaptic membrane potential'' 

Is this right ? I thought some sodium channels were involved in many other processes. 

![image](https://user-images.githubusercontent.com/4782928/32727491-0093685c-c87d-11e7-8ad8-ef92a34396fc.png)

Thanks, Pascale

**Comment by pgaudet** [comment]
Also: many of the ion channels have as a Subclass: 
'part of regulation of x transmembrane transport', 

while transmembrane transporters are 'part of some transmembrane transport'. 

Is the _regulation_ correct? 

Thanks, 

Pascale

**Comment by dosumis** [comment]
> I just noticed that 'GO:0005248 voltage-gated sodium channel activity'
> is_a ''voltage-gated ion channel activity involved in regulation of postsynaptic membrane potential''

Definitely wrong.  Don't know where this came from.  Thanks for fixing.

**Comment by pgaudet** [comment]
Moved the logical definition issue to #14563
