### ISSUE TITLE
NTR: negative regulation of host cytokine secretion

### ISSUE THREAD

**Issue by jonmarcias** [geneontology/go-ontology#14553]
negative regulation of host cytokine secretion
Definition: The process in which a virus decreases the frequency, rate or extent of cytokine production in its host organism.
Aspect: Biological process
parent term: modulation by virus of host cytokine (GO: 0044831)
sibling term:positive regulation by virus of host cytokine production (GO: 0044832)
Reference: PMID: 23083102
Organism: Shigella flexneri 
Protein (uniprot): P18009
Evidence type: IMP (Inferred from Mutant Phenotype     
Fig 2C: Wild type IPA4 shows a lower cytokine production when compared to delta IPA4 and the mutated IPA4

**Comment by pgaudet** [comment]
Hi @jonmarcias 

Since the figure shows " lower cytokine production ", would the term 'suppression by virus of host cytokine production' (GO:0046775) be ok for you ? 

Thanks, Pascale

**Comment by jonmarcias** [comment]
Hello @pgaudet 
Thanks for taking the time to look at the issue. 
That term is not appropriate in this instance because the organism is a bacterium, not a virus. 

Thanks in advance,
jonathan

**Comment by pgaudet** [comment]
OK. Then you probably don't want the parent to be 'modulation by virus of host cytokine (GO: 0044831)' 

How about a 'negative regulation' sibling to 'positive regulation by symbiont of host cytokine secretion', would that work ? 

Thanks, 
Pascale

**Comment by jonmarcias** [comment]
Yes. i think the 'negative regulation by symbiont of host cytokine secretion' would be appropriate. i must have put the wrong parent term in my initial issue. My apologies. 
Thanks,
Jonathan

**Comment by pgaudet** [comment]
New term: 
+[Term]
+id: GO:0140133
+name: negative regulation by symbiont of host cytokine secretion
+namespace: biological
+def: "Any process in which an organism stops, prevents, or reduces the rate or extent of cytokine secretion in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:23083102]
+is_a: GO:0052170 ! negative regulation by symbiont of host innate immune response
+created_by: pg
+creation_date: 2017-11-14T07:07:04Z
