### ISSUE TITLE
pre-autophagosomal structure name revision?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14552]
Hi David

Following another email from Daniel Klionsky <klionsky@umich.edu>, editor of Autophagy. I think we need to consider revision of the name pre-autophagosomal structure.

Daniel has stated: The terms phagophore assembly site and pre-autophagosomal structure mean the same thing. The journal Autophagy does not use the term pre-autophagosomal structure because this site is used to form all sequestering structures not just autophagosomes (e.g., Cvt vesicles). The phagophore assembly site (PAS) is where the phagophore forms.

I now understand why Daniel wants the name changed, because phagophore assembly site 
If you agree then the following edits need to be made:

**Change name pre-autophagosomal structure to phagophore assembly site**

GO:0000407 | pre-autophagosomal structure |  

**Change name and in definition pre-autophagosomal structure to phagophore assembly site**

GO:0034045 | pre-autophagosomal structure membrane |  
GO:0034497 | protein localization to pre-autophagosomal structure |  
GO:0097634 | integral component of pre-autophagosomal structure membrane |  
GO:0097632 | extrinsic component of pre-autophagosomal structure membrane |  
GO:0097633 | intrinsic component of pre-autophagosomal structure membrane

**Change in definition: pre-autophagosomal structure to phagophore assembly site**

GO:1990462 omegasome
GO:1990071 TRAPPII protein complex

Although Daniel's comments do make me wonder if the definition for GO:0061908    phagophore needs to be revised. Currently it is: A disk-like structure that expands, rounds up into a cup-shaped structure, and eventually closes around its cargo to become an autophagosome.

I think it should change to A disk-like structure that expands, rounds up into a cup-shaped structure, and eventually closes around its cargo (for example cytoplasmic components) to become an autophagosome or Cvt vesicle. 

I think I will have to change the name in the paper from pre-autophagosomal structure to phagophore assembly site.

unless any of the authors object

Ruth

**Comment by paolaroncaglia** [comment]
@marcfeuermann please

**Comment by Pauldenny** [comment]
This all sounds fine to me, but one detail - I assume you will use "pre-autophagosomal structure" as a synonym for "phagophore assembly site"? After all, Klionsky says that that they are the same.
Paul

**Comment by paolaroncaglia** [comment]
In GO speak, it would have to be a narrow synonym, but yes, I'd have it.

**Comment by marcfeuermann** [comment]
In the literature, PAS is used for pre-autophagosomal structure as well as for phagophore assembly site. In general, researchers do not make the difference. The "pre-autophagosomal structure" is the term used in the majority of papers, but it seems that the "autophagy community" prefers the "phagophore assembly site" term. So I would indeed change all the terms to "phagophore assembly site", and make "pre-autophagosomal structure" a synonym of "phagophore assembly site".

**Comment by paolaroncaglia** [comment]
@marcfeuermann thanks for confirming. Do you also think that the definition of GO:0061908 'phagophore' should be updated? From:
"A disk-like structure that expands, rounds up into a cup-shaped structure, and eventually closes around its cargo to become an autophagosome."
to:
"A disk-like structure that expands, rounds up into a cup-shaped structure, and eventually closes around its cargo (for example cytoplasmic components) to become an autophagosome or Cvt vesicle."
or else?
Thanks!

**Comment by marcfeuermann** [comment]
Oups, sorry, I've forgot to mention this. Yes we can modify the definition.

**Comment by paolaroncaglia** [comment]
@marcfeuermann thanks!

**Comment by paolaroncaglia** [comment]
Here's the detailed list of changes required:

GO:0000407 pre-autophagosomal structure:
Change name to ‘phagophore assembly site’;
Delete synonym ‘phagophore assembly site’;
Add narrow synonym ‘pre-autophagosomal structure’.

GO:0034045 pre-autophagosomal structure membrane:
Change name to ‘phagophore assembly site membrane’;
Change definition to “A cellular membrane associated with the phagophore assembly site.”;
Add narrow synonym ‘pre-autophagosomal structure membrane’.

GO:0097632 extrinsic component of pre-autophagosomal structure membrane:
Change name to ‘extrinsic component of phagophore assembly site membrane’;
Change definition to “The component of the phagophore assembly site membrane consisting of gene products and protein complexes that are loosely bound to one of its surfaces, but not integrated into the hydrophobic region.”;
Change synonym ‘extrinsic to pre-autophagosomal structure membrane’ to ‘extrinsic to phagophore assembly site membrane’;
Change synonym ‘pre-autophagosomal structure peripheral membrane’ to ‘phagophore assembly site peripheral membrane’;
Add narrow synonym ‘extrinsic component of pre-autophagosomal structure membrane’.
 
GO:0097633 intrinsic component of pre-autophagosomal structure membrane:
Same changes as for GO:0097632 (except that GO:0097633 has only 1 synonym).

GO:0097634 integral component of pre-autophagosomal structure membrane:
Same changes as for GO:0097632.

GO:0034497 protein localization to pre-autophagosomal structure:
Change name to ‘protein localization to phagophore assembly site’;
Change definition to “Any process in which a protein is transported to, or maintained at, the phagophore assembly site (PAS).”;
Change synonym ‘protein localisation to pre-autophagosomal structure’ to ‘protein localisation to phagophore assembly site’;
Add narrow synonym ‘protein localization to pre-autophagosomal structure’.

GO:1990462 omegasome:
Change definition to: “Omega-shaped (as in the Greek capital letter) intracellular membrane-bounded organelle enriched in phosphatidylinositol 3-phosphate and dynamically connected to the endoplasmic reticulum. Omegasomes are the first step of the formation of autophagosomes via the phagophore assembly sites.”

GO:1990071 TRAPPII protein complex:
Change definition to: “A complex that mediates intra-Golgi traffic, Golgi exit, endosome-to-Golgi traffic, and the trafficking of autophagy proteins from Golgi to the phagophore assembly site. Binds to a component of the COPI coat. In yeast it includes the following subunits: Bet3 (as homodimer), Bet5, Tca17, Trs20, Trs23, Trs31, Trs33, Trs65, Trs120, Trs130. The whole complex is thought to dimerize with itself.”

GO:0061908 phagophore:
Change definition to: "A disk-like structure that expands, rounds up into a cup-shaped structure, and eventually closes around its cargo (for example cytoplasmic components) to become an autophagosome or Cvt vesicle."

**Comment by paolaroncaglia** [comment]
@hdrabkin very kindly accepted to do the necessary ontology changes, as David is away. Many thanks. These edits are needed for prompt re-submission of the autophagy GO paper (they are the response to the single last question from the editor).

**Comment by hdrabkin** [comment]
Will do this after PRO and GO editors calls

**Comment by hdrabkin** [comment]
Ok; all done; closing

**Comment by paolaroncaglia** [comment]
@hdrabkin thanks a million!!

**Comment by RLovering** [comment]
Hi Harold
many thanks for this
Ruth
