### ISSUE TITLE
eisosome related

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14562]
eisosome  assembly def was updated here:
https://github.com/geneontology/go-ontology/issues/10052
 so 
eisosome assembly has

Definition | Parents
-- | --
The aggregation, arrangement and bonding together of a set of components to form an eisosome, a cell part that is composed of the eisosome membrane or MCC domain, a furrow-like plasma membrane sub-domain and associated integral transmembrane proteins, and the proteins (eisosome filaments) that form a scaffolding lattice on the cytoplasmic face.

i) ( I think a furrow-like plasma membrane sub-domain ) should be bracketed?
applies to  "a cell part that is composed of the eisosome membrane or MCC domain"

since eisosome is defined
A cell part that is composed of the eisosome membrane or MCC domain, a furrow-like plasma membrane sub-domain and associated integral transmembrane proteins, and the proteins (eisosome filaments) that form a scaffolding lattice on the cytoplasmic face. Eisosomes broadly affect overall plasma membrane organization.

can 
eisosome assembly
have the parent "plasma membrane organization"

**Comment by krchristie** [comment]
@ValWood 

1. I don't see any issue with the definition. It seems perfectly clear to me the way it is.

2. It seems odd to put an 'assembly' term under an 'organization' term. I realize that the term 'plasma membrane organization' does say `A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the plasma membrane.` However, we don't have any 'assembly' terms under 'plasma membrane organization' and all of the 'assembly' terms I see are under 'cellular component assembly'. Perhaps moving 'eisosome assembly' to be is_a 'membrane assembly' (a direct child of 'cellular component assembly') would work for you. @ukemi - Do you have thoughts on this?

**Comment by ValWood** [comment]
The aggregation, arrangement and bonding together of a set of components to form an eisosome, a cell part that is composed of the eisosome membrane or MCC domain, a furrow-like plasma membrane sub-domain and associated integral transmembrane proteins, and the proteins (eisosome filaments) that form a scaffolding lattice on the cytoplasmic face.


should be

The aggregation, arrangement and bonding together of a set of components to form an eisosome, a cell part that is composed of the eisosome membrane or MCC domain (a furrow-like plasma membrane sub-domain) and associated integral transmembrane proteins, and the proteins (eisosome filaments) that form a scaffolding lattice on the cytoplasmic face.


i.e the MCC domain *is* the  a furrow-like plasma membrane sub-domain) I think?
 (when I read it I though the def was referring to 2 separate things at first).

2. I think the assembly of the  eisosome is what causes the membrane furrowing (organization) so I don't think the assembly can be separated from the "membrane organization" here.


![like so](https://user-images.githubusercontent.com/7359272/32807694-a0087eb6-c988-11e7-8bc0-3883935ce62e.jpg)

**Comment by ValWood** [comment]
Actually, even better "membrane bending"
https://www.ebi.ac.uk/QuickGO/term/GO:0097753

The assembly of the "eisosome" is what causes the membrane bending

**Comment by krchristie** [comment]
I'm still not comfortable breaking with what appears to be a clear cut practice on put an 'assembly' term under an 'organization' term. I would be fine putting it under 'membrane assembly'.

**Comment by ValWood** [comment]
The membrane is already assembled so "eisosome assembly" isn't membrane assembly.

Maybe the term would be better called "eisosome formation" would that help at all?

I  just  found membrane invagination
https://www.ebi.ac.uk/QuickGO/term/GO:0010324

 which would be even better  parent for "eisosome assembly or formation" (oddly this isn't related to membrane bending though?)

**Comment by krchristie** [comment]
Regarding the suggestion of 'membrane bending' as a parent, I'm not sure that is consistent with current GO practice either. Note the structure of these existing terms:

-- 'membrane organization'
--- 'clathrin-coated pit assembly'

-- 'membrane bending'
--- 'clathrin-mediated membrane bending'

**Comment by ValWood** [comment]
I always had a problem with this. 

'clathrin-coated pit assembly' results in 'clathrin-mediated membrane bending'

The assembly actually causes the bending. These are different ways of looking at the same process IMHO. That is the function of the clathrin coat.  Its assembly mecahnically bends the membrane.

![clathrin](https://user-images.githubusercontent.com/7359272/32808457-fa6cf196-c98a-11e7-8409-8a68d04304ce.jpg)

**Comment by krchristie** [comment]
and I've thought for years that 'membrane bending' should be a function. There are proteins that do exactly this...

**Comment by ValWood** [comment]
clathrin coat assembly is_a membrane bending
eisosome assembly/formation is_a membrane bending

**Comment by ValWood** [comment]
> and I've thought for years that 'membrane bending' should be a function. There are proteins that do exactly this...

Actually I think you are right ,  we had a similar discussion in previous tickets. There are clearly individual proteins like clathrin and the F-BAR domains (pil1 is a BAR domain), and cdc15 (cleavage furrow)  that  can bend membranes, but  then there is the broader process of forming a "furrow" or a "vesicle" which depend on a plethora of other proteins . So maybe  we should treat the "membrane bending" as a function, and the type of bending (which depends in the "tessalation" of  various individual  proteins  to determine the shape of the invagination at the particular site), is the broader process.

This might work 
i.e

cdc15
MF membrane bending involved in BP  cleavage furrow formation
 
pil1
MF  membrane bending involved in BP  eisosome formation


cleavage furrow is_a membrane invagination
https://www.ebi.ac.uk/QuickGO/term/GO:0036089
membrane invagination is_a membrane organization

A problem is that  the component terms
“cleavage furrow” and “eisosome” are describes as  "membrane invaginations" in their defs membrane invagination is a process term. Need to distinguish the component term use from the process.

**Comment by ValWood** [comment]
I came to the same conclusion as you here:
https://github.com/geneontology/go-ontology/issues/13922

**Comment by ValWood** [comment]
and here
https://github.com/geneontology/go-ontology/issues/13024#issuecomment-316634820

**Comment by mah11** [comment]
Re:
>  a cell part that is composed of the eisosome membrane or MCC domain, a furrow-like plasma membrane sub-domain and associated integral transmembrane proteins, and the proteins (eisosome filaments) that ...

vs. 

> ... a cell part that is composed of the eisosome membrane or MCC domain (a furrow-like plasma membrane sub-domain) and associated integral transmembrane proteins, and the proteins (eisosome filaments) that ... 
I think it's meant to parse as 

"the eisosome membrane or MCC domain (a furrow-like plasma membrane sub-domain and associated integral transmembrane proteins)"

i.e. eisosome membrane = MCC domain = (furrow-like plasma membrane sub-domain AND associated integral transmembrane proteins)

and I think it's reasonably clear, but it could be recast to be at least as clear, maybe clearer. I wouldn't put as much in parentheses as Val suggested, though. The explanation of what the eisosome membrane is isn't parenthetical. This would be consistent with the current wording and with the diagram:

"a cell part that is composed of the eisosome membrane (also called the MCC domain), a furrow-like plasma membrane sub-domain with associated integral transmembrane proteins, and proteins (eisosome filaments) that form a scaffolding lattice on the cytoplasmic face."

But it you really want spend words to avoid the slightest possibility of confusion, this would work:

"a cell part that is composed of the eisosome membrane and eisosome filaments. The eisosome membrane, also called the MCC domain, is a furrow-like plasma membrane sub-domain with associated integral transmembrane proteins. The eisosome filaments form a scaffolding lattice on the cytoplasmic face of the membrane."

**Comment by ValWood** [comment]
Now I understand that one completely @mah11 ...you are really very very good at this, did you know?

**Comment by Antonialock** [comment]
How to get others to explain what you want to communicate ;-)

**Comment by krchristie** [comment]
@mah11 has solved part 1 with her lovely revision to the definition.

I am still not inclined to put an 'assembly' term directly under an 'organization' term. Looking at a variety of things, it looks like it goes against current practice. Seems that to give 'eisosome assembly' an organization parent, we would also need to create the term 'plasma membrane organization', but I think I'd want to discuss that at the editors' meeting first.

Then there's the larger issue of how to better deal with 'membrane bending'. However, I think if you want to deal with that, please create a new ticket, and we'll just deal with the simpler eisosome specific issues here.

**Comment by ValWood** [comment]
There is a already  term
GO:0007009 plasma membrane organization exists

Don’t you think that all induction of membrane curvature is part of membrane organisation?

Here the assembly of the complex is the process that is bending the membrane. It's quite different from   "Complex assembles. Assembled complex   participates in process".

I'm guessing there must be other cases like this. Isn't assembly of a spliceosome on a mRNA part of the splicing process?

Inducing  curvature happens to be the process  here.

I'll open a new ticket to propose that the process term is "curvature" and "membrane bending" is a function.

**Comment by krchristie** [comment]
Sorry, I meant that we might need to add a new term for 'plasma membrane **assembly**'. Looking at the structure of the ontology, I think it is a problem to but an 'assembly' term directly under an 'organization' term. While we did not discuss this issue at the editors call on 11/21/17, we have discussed similar issues of consistency.

I am willing to make the change in the definition of 'eisosome assembly' based on the proposal of @mah11. However, perhaps everything else needs to be part of the new ticket you made: #14593

**Comment by ValWood** [comment]
Didi you update the def from this one?

Also note: I don't think the curvature is part of "plasma membrane assembly"
The membrane is already there, only the shape is changing?

I'm not even sure why we have a "membrane assembly" term in addition to "biogenesis" or "formation"
(biogenesis seems more appropriate here)

**Comment by krchristie** [comment]
Yes, I updated the definition. For the rest, I think it is a bigger issue that is better handled in the other issue focused on the larger issue, so I'd like to just this ticket and just have the ticket with the larger issue open.
