### ISSUE TITLE
NTR:  'peroxisome localization, ER pathway'

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#14577]
Hi,

I would like to ask for the new term  'peroxisome localization, ER pathway' based on PMID:19479899 as discussed with @pgaudet .

**Suggested Definition**:
'A process in which a protein is transported to, or maintained at, a location in a peroxisome via the endoplasmic reticulum. '

It could be a child of  GO:0072662 'protein localization to peroxisome' or a sibling of it, if it is better to state the other route (via the cytoplasm) in the name. In the second case, both could be children of  GO:0007031 'peroxisome organization'. 

 
In PMID:19479899, the authors find that Pex3p is able to drive peroxisome biogenesis from the ER and that the Pex3 localisation to ER depends on the presence of Pex16.  The authors state that" ...GM6231 cells transfected to express Pex3p-GFP distributed this protein only to mitochondria (Fig. 7E,F), indicating that Pex16p is required for Pex3p incorporation into the ER."

Also, in PMID:26408931, it seems there are at least 2 paths by which proteins go to the peroxisome: via the ER, or via the cytoplasm.

Thanks,

Penelope

**Comment by hdrabkin** [comment]
how about ER dependent peroxisome localization?

**Comment by pgarmiri** [comment]
Yes, that's sounds clear to me. plus, it will keep the same syntax as other similar terms, like GO:0032581 'ER-dependent peroxisome organization'.

**Comment by pgaudet** [comment]
Is 'peroxisome localization' necessarily a peroxisome organisation?

**Comment by hdrabkin** [comment]
@pgaudet good point: does organization include the location in the cell or organization of the organelle. 
In all of the x organization terms, do we mean to include how the X is 'organized' in the cell (arrangement, location)?

**Comment by pgarmiri** [comment]
Hi,
I just wondering if there are any further thoughts on this...
Thanks,
Penelope

**Comment by hdrabkin** [comment]
@pgaudet can you comment on my question of 10/2017;

**Comment by pgaudet** [comment]
@hdrabkin are you asking me the same q I asked you ? 
perhaps this is for a group discussion next week? 
(I think the answer is yes in terms of the GO structure)

**Comment by hdrabkin** [comment]
@pgaudet ; ok; was trying of clearing it; @pgarmiri , we will address this during our GIT-aThon next week

**Comment by pgarmiri** [comment]
Thanks for looking into it!

**Comment by hdrabkin** [comment]
As an aside, when I quickly look at "peroxisome localization" I think; is this about localization of the peroxisome to some place in the cell OR localization of a protein TO a peroxisome.

**Comment by hdrabkin** [comment]
Never mind, I see by the proposed def that this is loc of a protein TO the peroxisome.

**Comment by hdrabkin** [comment]
I'm going with option 1.

**Comment by hdrabkin** [comment]
GO:0106101

**Comment by hdrabkin** [comment]
done

**Comment by pgarmiri** [comment]
Thank you, Harold!
