### ISSUE TITLE
GO:0043683 type IV pilus biogenesis parentage

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#14579]
Currently, GO:0043683 type IV pilus biogenesis is_a GO:0009297 pilus assembly. https://www.ebi.ac.uk/QuickGO-Old/GTerm?id=GO:0043683#term=ancchart

However, GO:0043683 type IV pilus biogenesis is defined as "A cellular process that results in the biosynthesis of constituent  macromolecules, assembly, and arrangement of constituent parts of a type  IV pilus..." ; GO:0009297 pilus assembly is only defined as "The assembly of a pilus, a short filamentous structure on a bacterial cell...".  I don't think GO:0043683 type IV pilus biogenesis should be this deep in the ontology, maybe move it up to be a child of GO:0043711 pilus organization (def: "...assembly, arrangement of constituent parts, or disassembly...")?

Would that mean the definition for  GO:0043711 pilus organization (def:A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a pilus, a short filamentous structure on a bacterial cell, flagella-like in structure and generally present in many copies) needs to include biosynthesis, or is there a better place to insert the "pilus biogenesis" term(s)?

This might affect the NTR at https://github.com/geneontology/go-ontology/issues/14469 for 'type I pilus biogenesis'.

Thanks

@jimhu-tamu

**Comment by vanaukenk** [comment]
@suzialeksander 

Thanks, I think there is an issue with the parentage of GO:0043683 type IV pilus biogenesis.

The overall structure of these types of terms in the ontology is:

-cellular component organization and biogenesis
--is_a cellular component biogenesis
---part_of cellular component assembly
--is_a cellular component organization
---is_a cellular component assembly
---is_a cellular component disassembly
---is_a cellular component maintenance
---Is_a cellular component morphogenesis

What I would propose we do is this:

-cellular component organization and biogenesis
--is_a cellular component biogenesis
---is_a GO:new cell projection biogenesis
----is_a GO:new pilus biogenesis
-----is_a GO:new type I pilus biogenesis
-----is_a GO:new type IV pilus biogenesis
-----part_of pilus assembly

This would also address #14469 

@krchristie and @paolaroncaglia - from your work on the cilia project, is there any reason not to create a new term for 'cell projection biogenesis'?  We have 'cell projection organization' and 'cell projection assembly', but not 'cell projection biogenesis' (at least not that I can find), and I can see that terms like 'cilia biogenesis' are actually related synonyms of 'cilia assembly'.  Thx.

**Comment by suzialeksander** [comment]
That looks better to me. Thanks.

**Comment by krchristie** [comment]
I think we would need to think very carefully about what would be the difference between the 'assembly' and the 'biogenesis' of a cell projection. 

Prior to the cilia project, there was a term for 'cilium morphogenesis' and we merged it into 'cilium assembly' because, even after examining the existing annotations to the two terms, we could not distinguish a different process for 'cilium morphogenesis' versus 'cilium assembly'. In the literature, these two phrase appeared to be used equivalently. Here's the ticket: https://github.com/geneontology/go-ontology/issues/12236

It seems to me that distinguishing 'cell projection assembly' and 'cell projection biogenesis' could suffer from a similar lack of clarity, so I'd like to have a discussion about exactly what each would cover to determine if this would really be useful.

Then, IF we do decide that having 'cell projection biogenesis' terms is useful, please be aware that there is a subdivision for 'plasma membrane bounded cell projection', that is used throughout the CC cell projection terms and the BP terms for their assembly and organization:
- https://github.com/geneontology/go-ontology/issues/13193
- https://github.com/geneontology/go-ontology/issues/13298

so the corresponding term for 'plasma membrane bounded cell projection biogenesis' might also need to be created.

**Comment by paolaroncaglia** [comment]
@vanaukenk @suzialeksander
As @krchristie summarised, during the cilia work, after a careful review and feedback from experts, we came to the conclusion that ‘biogenesis’ is not a meaningful term when it comes to cilia. I think that the same applies to other cell projections. I haven’t had time to look into this carefully, but perhaps you may want to consider if the plus biogenesis term should be merged with its assembly parent. And the definition of the assembly term made broader.
Have a nice weekend!

**Comment by krchristie** [comment]
@paolaroncaglia - My recollection is that we came to the conclusion that '**morphogenesis**' is not a meaningful term when it comes to cilia, as per https://github.com/geneontology/go-ontology/issues/12236. I do not recall having a discussion of '**biogenesis**' with respect to cilia, though I feel that we should be proceed with due diligence to determine if '**biogenesis**' with respect to cell projections, or if we should just have '**assembly**' terms.

Perhaps also worth noting, I do not see any other '**biogenesis**' terms under '**cell projection organization**', even looking at the Inferred view with the reasoner on.

**Comment by krchristie** [comment]
Looking at the top level biogenesis term, it seems that the main difference between 'assembly' and 'biogenesis' terms is that the 'biogenesis' terms include synthesis and modification of the components:
**Term**: cellular component biogenesis
**Def**: A process that results in the biosynthesis of constituent macromolecules, assembly, and arrangement of constituent parts of a cellular component. **Includes biosynthesis of constituent macromolecules**, and those macromolecular modifications that are involved in synthesis or assembly of the cellular component.

Unless there is really a desire/need to include the biosynthesis of components in the 'type IV pilus biogenesis' term, perhaps it would make sense to change it to 'type IV pilus assembly', which would be more consistent with how all the other cell projections are represented in GO.

**Comment by vanaukenk** [comment]
Thanks @krchristie and @paolaroncaglia   I've put this on the agenda for the editors call on Monday.

I agree that the distinction between 'biosynthesis' and 'assembly' in the literature can be murky.  As you point out, though, in GO we do seem to make the distinction that biogenesis additionally includes the biosynthesis of constituent macromolecules, along with macromolecular modifications.

I just want to make sure that we're being consistent in GO such that cellular component biogenesis and cellular component assembly have clear meanings that don't necessarily depend on what component we're describing.

I find it confusing to have terms in the ontology with synonyms that mirror distinct parent terms, e.g. 'cell projection assembly' has the synonym 'cell projection biogenesis' but more generally
'cellular component assembly' is part_of 'cellular component biogenesis'.

**Comment by paolaroncaglia** [comment]
@krchristie yes sorry I meant morphogenesis, but I feel the same way about biogenesis terms applied to cell projections: I'm afraid they're not very meaningful. Thanks for clarifying and expanding on this.

**Comment by vanaukenk** [comment]
Just an update on this ticket.

The GO editors are discussing the use of biogenesis, assembly, organization, formation, etc. of cellular component x terms in the ontology.

It seems that these terms are often used interchangeably in the literature and that the distinctions in GO are not always clear, leading to inconsistent use in annotation.

The specific issue noted in this ticket will be addressed as part of a larger proposal on what to do with these types of terms.

**Comment by pgaudet** [comment]
Hi @vanaukenk 
I create a label 'assembly and biogenesis' to group these tickets. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
Thanks, @pgaudet - this will likely be a project.

**Comment by pgaudet** [comment]
Also, removed 
never on taxon 
GO:0009297 pilus assembly NCBITaxon:4751 Fungi

added 
only in taxon 
GO:0009289	pilus	NCBITaxon:2	Bacteria
GO:0043711	pilus organization	NCBITaxon:2	Bacteria
