### ISSUE TITLE
dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity (obsoletion query)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14578]
GO:0004584 - dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity

has the note
This term represents a deleted EC activity and is scheduled for obsoletion.

when will it go and does it have a replacement term?

**Comment by hdrabkin** [comment]
Good question;

**Comment by hdrabkin** [comment]
Hi @ValWood 
So here is what ec said:
Four  EC numbers that have replaced EC 2.4.1.130.

Now covered by
EC 2.4.1.258 (Dol-P-Man:Man5GlcNAc2-PP-Dol α-1,3-mannosyltransferase),
EC 2.4.1.259 (Dol-P-Man:Man6GlcNAc2-PP-Dol α-1,2-mannosyltransferase),
EC 2.4.1.260 (Dol-P-Man:Man7GlcNAc2-PP-Dol α-1,6-mannosyltransferase) and
EC 2.4.1.261 (Dol-P-Man:Man8GlcNAc2-PP-Dol α-1,2-mannosyltransferase).

EC 2.4.1.130 was too unspecific and covered several different enzymes with
non-overlapping catalytic activities.

So, I will
1. see if these ecs are in already
2. add any that aren't. 
Then it's up to you to choose which one relevant for your use.

**Comment by hdrabkin** [comment]
All 4 of these are in the GO already. 
EC 2.4.1.258 is GO:0052925
EC 2.4.1.259 is GO:0052926
EC 2.4.1.2560 is GO:0052917
EC 2.4.1.2561 is GO:0052918
I will add this info to EC 2.4.1.130 and send out the obsoletion notice in a bit

**Comment by ValWood** [comment]
Oh brilliant, I think that must be the 4 mannosyltransferases in
https://github.com/geneontology/go-ontology/issues/14204
That is what I was looking for yesterday.
Now, how do I know which one is which??????

**Comment by hdrabkin** [comment]
Looks like you need to figure out the substrate

**Comment by hdrabkin** [comment]
There are over 500 annotations using the term. wah

**Comment by ValWood** [comment]
Hmm, I don't think it's these ones. These are (SGD) ALG2, ALG9, ALG12, ALG9

I was looking for  
PIGX/PBN1
PIGM/GPI14
GPI18

**Comment by hdrabkin** [comment]
Pombase has 3; not so much.
gip18, gip10, and alg3, via iso, and ic
You're lucky!

**Comment by ValWood** [comment]
we have 28 mannosyltransferases, but I was trying to specify the activity for

glycosylphosphatidylinositol-mannosyltransferase I complex
and
glycosylphosphatidylinositol-mannosyltransferase II complex

It seemed that this might be it at first ....

(in GPI biosynthesis every eukaryote pretty much has the same 1:1  with a few extra for mammalian?)

**Comment by ValWood** [comment]
Actually  the pathway is pretty much identical

GPI biosynthesis
mouse 31
human 32
pombe 31
cerevisae 30

Not "lucky" Harold, just "picky"
