### ISSUE TITLE
MP GO0009225 - nucleotide-sugar metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14587]
Should 
GO0009225 - nucleotide-sugar metabolic process
 be is_a
nucleobase-containing small molecule metabolic process

**Comment by pgaudet** [comment]
This is what's inferred by CheBI, indeed. You don't think it should be? 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/4782928/32919286-89258a4c-cb25-11e7-9a93-b0e22b02d6d4.png">

**Comment by pgaudet** [comment]
Hi @ValWood - I read too fast; I missed the small molecule part. 

In fact there are only 8 terms with the string 'small molecule' in GO. This is not defined in ChEBI. I propose to merge them with their respective parent; what do you think? 

GO_0036094 | 'small molecule binding'
-- | --
GO_0044283 | 'small molecule biosynthetic process'
GO_0044282 | 'small molecule catabolic process'
GO_0044281 | 'small molecule metabolic process'
GO_0034404 | 'nucleobase-containing small molecule biosynthetic process'
GO_0034656 | 'nucleobase-containing small molecule catabolic process'
GO_0015949 | 'nucleobase-containing small molecule interconversion'
GO_0055086 | 'nucleobase-containing small molecule metabolic process'



Thanks, Pascale

**Comment by ValWood** [comment]
see discussion in
https://github.com/geneontology/go-ontology/issues/14047
https://github.com/geneontology/go-ontology/issues/5410
https://github.com/geneontology/go-ontology/issues/10400

Its a clunky term but it is an important terms for general metabolism,  and modularity, and its the best name we have some up with so far.

**Comment by pgaudet** [comment]
Right... 
I think there are many terms missing then. For example ions (I mean selenium, etc) would be small molecules? xenon, water... 

also pheromone
pigment
nicotine

... this class is missing many children. 
Would it work if any term in Chebi (ie children of 'CHEBI:23367 molecular entity') would be included here ? (somehow I doubt such a simple solution would work...) 

Pascale

**Comment by ValWood** [comment]
we need to exclude polymers (protein, nucleic acids, long chain carbohydrates) all are molecular entities.....

I don't think chebi has a concept of  "small molecule" either.....
