### ISSUE TITLE
NTR/intermediate term: mechanically-gated cation channel activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14588]
Could I request a term intermediate to mechanically-gated ion channel activity and the cation-specific terms to describe mechanically-gated channels that are not selective for a specific cation (or at least have not had their specific permeabilities characterised).

Term request: mechanically-gated cation channel activity
Definition:Enables the transmembrane transfer of a cation by a channel that opens in response to a mechanical stress. 
Ref:PMID:22343900
xref:GOC:ha

Is_a 
GO:0005261 | cation channel activity
Is_a 
GO:0008381 mechanically-gated ion channel activity

child terms (to be moved from under GO:0008381 mechanically-gated ion channel activity)
GO:0098782 mechanically-gated potassium channel activity
GO:0101013 mechanically-modulated voltage-gated sodium channel activity
GO:0015275 stretch-activated, cation-selective, calcium channel activity

**Comment by pgaudet** [comment]
Hi @hattrill 

I have two questions: 
1. Looking at the children you suggest, and reading on wikipedia https://en.wikipedia.org/wiki/Mechanosensitive_channels, it seems 'mechanosensitive channel activity' would be a better term name, as it would then clearly cover  'mechanically-modulated' channels as well. 

2. It looks like all mechanosensitive channels/mechanically-gated channels are *ion* channels. Should I merge 
GO:0022833 mechanically gated channel activity (4 annotations, could be annotated to GO:0008381)
into GO:0008381 mechanically-gated ion channel activity ? (almost 600 annotations). 
What do you think ? 

Thanks,

**Comment by hattrill** [comment]
Yes, merge GO:0022833 mechanically gated channel activity into GO:0008381 mechanically-gated ion channel activity. I don't know of any other kind.

And I prefer "mechanosensitive channel activity" as it is the coverall used in the literature.

Thanks.
