### ISSUE TITLE
Revise definitions of  'neuron projection arborization' and child terms to align with corresponding CC terms

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14582]
### Background

The cellular_component (CC) dendrite terms #13785 were edited after the biological_process (BP) 'neuron projection arborization' (and child terms) had been created #13877.

The definitions and relations of the BP terms need to be revised to ensure they are in agreement 
with the corresponding CC terms. 

### Example

For instance the current definition of 'GO:0140059 dendrite arborization' is:
"The process in which the anatomical structures of a dendrite are generated and organized into branches."  

However, based on the CC definitions, _a dendrite is **one of the branches**_. Therefore, this definition should be re-phrased as follows: 
"The process in which the anatomical structures of a **dendritic tree** are generated and organized into (dendritic) branches." Ontology relations should be revised accordingly.

Relevant CC terms:
GO:0097447 dendritic tree
GO:0044307 dendritic branch
GO:0030425 dendrite

### Required action

All BP 'neuron projection arborization' terms and the corresponding CC terms should be compared for discrepancies in wording, as shown in the above example. If required, the (definitions of) BP terms should be modified to fit the (definitions of) CC terms. Synonyms and ontology relations between these BP and CC terms should also be revised.

cc
@pgaudet 
@vanaukenk 
@RLovering 
@paolaroncaglia 
@ukemi

**Comment by BarbaraCzub** [comment]
+ NTR: 'basal dendritic arborization' (is_a GO:0140059 dendrite arborization). PMID:22683681 shows that TAOK2 affects basal but not apical dendritic arborization, and cites previous studies, e.g. "Previous studies have shown that the Sema3A–Nrp1/PlexinA4 signaling cascade controls basal dendritic arborization (14–16)." Then, update relevant PMID:22683681 annotations with this new term, when ready.

**Comment by BarbaraCzub** [comment]
+ 'GO:0030426 growth cone' - this term lacks references. Revise relevant references cited in PMID:22683681 (start with citation examples below), edit definition to include information about actin in growth cones, and add PMID references to the GO term.

"The growth cone is a region where actin, but not microtubules, accumulates (Fig. 1b) and where the actin cytoskeleton is the most dynamic (18)." 
"The remodeling of the actin-based cytoskeleton is an important regulatory step in axon and dendrite formation (20–22)."

**Comment by BarbaraCzub** [comment]
Also: check definitions in the most recent regulation terms #14747

**Comment by pgaudet** [comment]
HI @BarbaraCzub 
I see you have tagged me on this one. Your proposal seems OK to me (I will not object to increased consistency!) but really I am no expert in neurobiology so I will not comment on the best formulation for the definition. 

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
Your suggestions above look good to me. Thanks.

**Comment by BarbaraCzub** [comment]
### GO:0043005 neuron projection vs GO:0140058 neuron projection arborization (and child regulation terms #14747)
Definition (GO:0043005 GONUTS page)
A prolongation or process extending from a nerve cell, e.g. an axon or dendrite.
Definition (GO:0140058 GONUTS page)
The process in which the anatomical structures of a neuron projection are generated and organized into branches. A neuron projection is any process extending from a neural cell, such as axons or dendrites. PMID:23270857 PMID:23764288
- No changes required.

### GO:0030425 dendrite vs GO:0140059 dendrite arborization
Definition (GO:0030425 GONUTS page)
A neuron projection that has a short, tapering, morphology. Dendrites receive and integrate signals from other neurons or from sensory stimuli, and conducts a nerve impulse towards the axon or the cell body. In most neurons, the impulse is conveyed from dendrites to axon via the cell body, but in some types of unipolar neuron, the impulse does not travel via the cell body.
Definition (GO:0140059 GONUTS page)
The process in which the anatomical structures of a dendrite are generated and organized into branches. PMID:23270857
(Compare to: GO:0097447 dendritic tree; Definition (GO:0097447 GONUTS page); The entire complement of dendrites for a neuron, consisting of each primary dendrite and all its branches.)

- [ ] GO:0140059 definition should be updated as follows: "The process in which the anatomical structures of a dendritic tree are generated and organized into (dendritic) branches."

- [ ] make GO:0030425 dendrite a part_of child of GO:0097447 dendritic tree

- [ ] GO:0030425 - correct typo in 2nd sentence of GO:0030425 dendrite def.

### GO:0030424 axon vs. GO:0140060 axon arborization
Definition (GO:0030424 GONUTS page)
The long process of a neuron that conducts nerve impulses, usually away from the cell body to the terminals and varicosities, which are sites of storage and release of neurotransmitter.
Definition (GO:0140060 GONUTS page)
The process in which the terminal anatomical structures of an axon are generated and organized into branches of specialised projections, or boutons. An axon is the long process of a neuron that conducts nerve impulses, usually away from the cell body to the terminal branches. PMID:23764288

- [ ] make GO:0140060 axon arborization a child of GO:0140058 GO:0140058 neuron projection arborization 
- (definitions are fine)

### GO:0030426 growth cone

- [ ] update definition
From: Definition (GO:0030426 GONUTS page) 
The migrating motile tip of a growing nerve cell axon or dendrite.
To: Definition (GO:0030426 GONUTS page)
The migrating motile tip of a growing neuron projection, where actin accumulates, and the actin cytoskeleton is the most dynamic. PMID:10082468.

### NTR: basal/apical dendritic arborization (First address: NTRs: distal and proximal apical dendrites #14353)

- [ ] NTR: parent terms 'basal dendrite morphogenesis/development' (is_a GO:0048813/GO:0016358 dendrite morphogenesis/development). PMID:22683681

- [ ] NTR: 'basal dendritic arborization' (is_a GO:0140059 dendrite arborization). PMID:22683681

- [ ] NTR: corresponding 'apical dendrite [BP]' terms. 

- [ ] update relevant PMID:22683681 annotations with this new term, when ready. see 17 Nov comment above for details.

**Comment by paolaroncaglia** [comment]
@BarbaraCzub looks good to me, thanks.
