### ISSUE TITLE
The term "viral integration complex" cannot be assigned to viral proteins

### ISSUE THREAD

**Issue by SIBvirus** [geneontology/go-ontology#14595]
The term "viral integration complex" (GO:0019035) is restricted to eukaryota/cellular organisms. This should not be the case since the viral integration complex is composed of both cellular and viral proteins (cf. GO definition: A nucleoprotein complex containing viral genetic material and associated **viral** and host proteins, which is capable of inserting a viral genome into a host genome).

**Comment by pgaudet** [comment]
Hello, 

Is this term relevant to bacteriophages? I think the problem comes from the fact that the term is under 'nuclear part'; I can move it to 'host cell nuclear part' if this only applies to eukaryotic viruses. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Same for 'viral transcriptional complex'; I presume bacteriophages get transcribed as well.

**Comment by SIBvirus** [comment]
Hello,

The "viral integration complex" is specific to eukaryotic viruses (retroviruses). 

Bacterioviruses get transcribed for sure! I have never seen the term  "viral transcriptional complex" used for bacteriophages though...

**Comment by pgaudet** [comment]
OK. I had put both directly under protein complex. If you want I'll add 'host cell nuclear part'. 

Thanks, Pascale

**Comment by SIBvirus** [comment]
No, it's OK like that, thanks!

**Comment by pgaudet** [comment]
OK perfect, thanks.
