### ISSUE TITLE
OTR: link between aminoacyl-tRNA ligase activity and ligase activity missing

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14594]
id: GO:0004812
name: aminoacyl-tRNA ligase activity
is_a: GO:0140101 ! catalytic activity, acting on a tRNA

Seems to be missing link to parent:
id: GO:0016874
name: ligase activity

Definition of def of ligase activity: "Catalysis of the joining of two substances, or two groups within a single molecule, with the concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate." seems to be consistent with the defintion of aminoacyl-tRNA ligase activity "Catalysis of the formation of aminoacyl-tRNA from ATP, amino acid, and tRNA with the release of diphosphate and AMP."

Looks like this happened when ligase activity, forming aminoacyl-tRNA and related compounds, GO:0016876 merged into GO:0004812 aminoacyl-tRNA ligase activity.

Assume something has happened during this edit:https://github.com/geneontology/go-ontology/commit/62857f32df21f1ecdf591b20634653d71faf6a86
or refactoring:https://github.com/geneontology/go-ontology/pull/14214

**Comment by hdrabkin** [comment]
I will make the link to the proper child, GO:0016875, EC:6.1, which include aminoacyl-trnas (EC:6.1.1)
https://en.wikipedia.org/wiki/Category:EC_6.1.1

**Comment by hattrill** [comment]
Lovely, thanks!

**Comment by hdrabkin** [comment]
done
