### ISSUE TITLE
membrane bending vs membrane curvature

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14593]
membrane bending
https://www.ebi.ac.uk/QuickGO/term/GO:0097753
A membrane organization process resulting in the bending of a membrane.

synonym membrane curvature | related

 A number of us think that membrane bending should be a function term
@krchristie  https://github.com/geneontology/go-ontology/issues/14562#issuecomment-345393895
@hattrill https://github.com/geneontology/go-ontology/issues/13024#issuecomment-316634820

It seems that different proteins in different modification states can cause different degrees of curvature. 
Different types of assemblies (clathrin coats,eisosomes etc form different "tessellation patterns"
for example clathrin forms the tessellated polygonal scaffold.

So the assemblies of different proteins in different contexts can form different types of  membrane protrusions and invaginations (curvatures).

It would seem better to call the processes membrane curvature, to group the different types of invagination.

"membrane bending" can then be the gene product specific activity for the proteins that can intrinsiclly bend the membrane?

**Comment by hattrill** [comment]
Hi @ValWood , @krchristie ,

Would be nice to get the bending into MF. What are the barriers to getting this sorted?

Is it something we should get together and discuss in May or sort via github?

**Comment by ValWood** [comment]
membrane curvature related processes:

spore membrane bending pathway -> rename spore membrane bending?
 spore membrane bending pathway, add membrane bending parent?
 lipid tube assembly appears to be describing some sort of "membrane tubulation"?
 endoplasmic reticulum tubular network assembly appears to be describing some sort of "membrane tubulation"?

**Comment by ValWood** [comment]
I will add a term "membrane bending activity" because a number of proteins (e.g. reticulon, calveolin, clathrin, bar domain) have intrinsic membrane bending activities

Review
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3490495

Once the term is added we should review whether

membrane bending and children are required.

There are 11 EXP annotations

(the actual processes would be ER membrane tubulation, endocytosis etc)

**Comment by hattrill** [comment]
Ace! You must have read my mind - was just looking at a paper a couple of days a go thinking about this activity!

**Comment by krchristie** [comment]
Excellent!

**Comment by ValWood** [comment]
I will add
The activity of bending or deforming a membrane. This activity can occur by multiple mechanisms including the insertion amphipathic domains into one or both leaflets.
PMID:19780639
synonym "membrane curving" 

We should probably then obsolete "membrane beding" as a process term (11 EXP annotations, including 
3 fission yeast and 4 fly). I'll open a separate tickt for  that once we are sure we don't require it (for the  fission yeast annotations we don't)

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180020
+name: membrane bending activity
+namespace: molecular_function
+def: "The activity of bending or deforming a membrane. This activity can occur by multiple mechanisms including the insertion amphipathic domains into one or both leaflets." [PMID:19780639]
+synonym: "membrane curving" RELATED []
+is_a: GO:0003674 ! molecular_function
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/14593" xsd:anyURI
+created_by: vw
+creation_date: 2023-06-16T10:44:29Z
+
