### ISSUE TITLE
MP GO:0009898    cytoplasmic side of plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14603]
GO:0009898    cytoplasmic side of plasma membrane

can this term have a part_of relationship to cytoplasm?

v

**Comment by krchristie** [comment]
The definition of cytoplasm  (which I agree with) contradicts this suggestion:

Def: All of the contents of a cell **excluding the plasma membrane** and nucleus, but including other subcellular structures.

I think the existing logical definition of 'cytoplasmic side of plasma membrane' already includes the correct relationship to 'cytoplasm'

> 'side of membrane'
 and ('part of' some 'plasma membrane')
 and ('adjacent to' some cytoplasm)

**Comment by ValWood** [comment]
In this case there is a logic issue encoded in the GO here.

cytoplasmic side of the plasma membrane
has the descendant

GO:0098753    anchored component of the cytoplasmic side of the plasma membrane
The component of the plasma membrane consisting of gene products and protein complexes with covalently attached hydrophobic anchors products that penetrate only the cytoplasmic side of the membrane.


we have used this to annotate many gene products that are anchored to the cytoplasmic dide of the plasma membrane (for example palmitolated proteins like Rho1, or SH3 domain proteins like cdc15), 


extrinsic component of cytoplasmic side of plasma membrane
  | mod5, pom1, rho1

anchored component of the cytoplasmic side of the plasma membrane
  | cdc15, imp2, rga7

I don't think biologists would consider these to be part of the plasma membrane, but they are part of the cytoplasm...or more specifically  cortex

I don't know the solution though!

**Comment by krchristie** [comment]
@ValWood - Personally, I'm not sure I agree that there is a logical problem here. It seems to me that things that are anchored to the plasma membrane are part_of the plasma membrane, not the cytoplasm, which I think of as the stuff that is inside the plasma membrane and not anchored to it.

Regarding the cortex, perhaps the definition of the cortex needs to be expanded to include that it anchors to the PM?

I am tagging @ukemi to see if he has thoughts on this.

**Comment by deustp01** [comment]
Okay. A mammalian tyrosine kinase receptor spans the plasma membrane, so it's part of the membrane. It binds a ligand, so while it's associated the ligand is part of the membrane as well. The ligand-receptor complex changes conformation and binds an adapter protein that was previously free in the cytosol, so the adapter becomes part of the membrane while it's bound. No argument from here with the logic - only the practical question of how to define the boundaries that separate cytoplasmic and extracellular from plasma membrane in a way that doesn't damage too many existing annotations and that can be applied consistently going forward. (We struggle with this one, hence the lack of useful suggestions about where to put the boundaries.)

**Comment by ValWood** [comment]
I agree in this instance because the protein is attached to a protein which is integral  it seems OK.

But does it seem OK for proteins which are "loosely attached" like "

cdc15, 1mp1, rga7 here:
https://www.pombase.org/reference/PMID:28914606
in the proximal layer. These are membrane anchored, but they are really cytoplamic aren't they?

![proximal layrer](https://user-images.githubusercontent.com/7359272/33578059-19c044fa-d93d-11e7-8710-9a22e7edd903.jpg)

**Comment by krchristie** [comment]
It seems like a hard path to go to start making decisions about which "loosely attached" proteins are "really" cytoplasmic and which are "really" part_of the PM. It seems like this could be based on our personal biases about how we perceive those things. If you came up with more examples of "loosely attached" proteins, would you think they are all cytoplasmic?

As I said before, I think it might be better to think about our definition of the cortex. From the figure you linked, it also does not look like authors are trying to say that the cortex proteins are cytoplasmic. They seem to show the contractile ring as being in between the plasma membrane and the cytoplasm.

**Comment by ValWood** [comment]
The cell cortex is a cytoplasmic region
https://www.ebi.ac.uk/QuickGO/term/GO:0005938

I think I came across this because it seemed odd that some  peripherally attached proteins (mainly those which attach loosely via a  modification like prenylation  or some other phospholipid attachment site), are annotated to "plasma membrane".

I could check with some  experts about whether they consider these to be "plasma membrane" proteins.....

**Comment by krchristie** [comment]
In grad school, where I heard many talks from Jasper Rine's lab , both during my rotation and throughout grad school, my understanding was that modifications like prenylation are a way to confer membrane localization on a protein that would otherwise not localize there, but that when the protein was prenylated it was localized to the membrane. Seems to me that what we really need are the PRO terms to be able to say that the prenylated form is part_of the membrane while the un-prenylated form is found in the cytoplasm.

**Comment by ValWood** [comment]
OK maybe then it is OK.... can close...

**Comment by krchristie** [comment]
OK, thanks @ValWood
