### ISSUE TITLE
Check for obsolete/merged external ontology IDs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14605]
Hello, 

Can we add a rule to flag or replace obsolete classes from external ontologies ? For eg in  
GO:0019694 alkanesulfonate metabolic process
we have a link to CHEBI:22318 in the equivalence axiom, which now a secondary ID of CHEBI:134249. 

@cmungall what is our process for dealing with these changes? 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/4782928/33063031-8168c466-cea1-11e7-8e8c-df58781d2237.png">

Thanks, Pascale

**Comment by tberardini** [comment]
Related (possibly duplicate) #13793

**Comment by cmungall** [comment]
@dougli1sqrd is investigating why this didn't appear in the travis report

**Comment by dougli1sqrd** [comment]
So robot is not doing the imports closure during a sparql query it looks like. This would explain why we get no results. On rdf.geneontology.org, I ran a query to find violations (keeping in mind the data there is a little old at this point) and these are the results I found [attached](https://github.com/geneontology/go-ontology/files/1533494/classes_linking_to_deprecated_terms.csv.txt).

Go to the following link to see and try the query I used to get these results: http://yasgui.org/short/BJu_bqN-M

If robot is supposed to do the imports closure, but isn't we should fix that. Hope this helps.

**Comment by cmungall** [comment]
You cab run merge first

**Comment by pgaudet** [comment]
To add to import file: 
CHEBI:28297  hydantoin-5-propionic acid
CHEBI:69404 pestalamide A
ChEBI ID | CHEBI:69403 carbonarone A
CHEBI:77506 1-pentadecene


To remove/replace: 
CHEBI_:22582 antibiotic replaced by CHEBI:33281 antimicrobial agent
CHEBI:26619 secndary metabolite
--

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/14769 Should help.

**Comment by pgaudet** [comment]
@cmungall @dougli1sqrd 
Can this be closed ?

**Comment by dougli1sqrd** [comment]
No not yet. @cmungall still has to tell us how to fix GOCHE. My PR won't pass until we fix GOCHE (also fixing this issue), and then once my PR is in, we'll in the future detect more obsolete references like this.

**Comment by pgaudet** [comment]
@dougli1sqrd Chris will help you :)

**Comment by cmungall** [comment]
@dougli1sqrd I moved the substance by role building to the main go-ontology Makefile and rebuilt chebi_import - does it look OK now?

**Comment by dougli1sqrd** [comment]
Apparently not? I'm not totally sure what happened, but there seem to be more obsolete references? https://travis-ci.org/geneontology/go-ontology/builds/340666568?utm_source=github_status&utm_medium=notification

**Comment by cmungall** [comment]
We next need to run `robot repair`. @pgaudet is that something we should do a quick 10 min intro to the ontology group for.

That will fix at least some, at least the first one, where GO references GOCHE_26619

```
   <owl:Class rdf:about="http://purl.obolibrary.org/obo/GOCHE_26619">
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/GOCHE_25212"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

robot repair should be able to migrate the GO axiom to GOCHE_25212 based on the info above

This case is due to the fact that CHEBI obsoleted their original metabolite, see http://www.ebi.ac.uk/chebi/searchId.do?chebiId=26619

Aside: it's not clear why CHEBI did this, it creates churn for us, and it seems https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_25212 was only created recently, grumble..

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/14769
