### ISSUE TITLE
NTR: synapsis initiation complex and SUMO ligase complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#14608]
Hi,

I'm Livia Perfetto. I have just started as a curator in IntAct/ComplexPortal. @bmeldal helped me with this first request I hope I haven't done too much confusion!

I need a GOC id, can someone please create this before you commit these terms?

Term requests below.

Thanks,

Livia

Term 1:
Name: synapsis initiation complex
Def: A SUMO ligase complex capable of promoting synapsis, the meiotic cell cycle process where side by side pairing and physical juxtaposition of homologous chromosomes is created during meiotic prophase.
References:
GOC:to be created (Livia Perfetto)
PMID:16847351
Relationships:
is_a GO:NEW SUMO ligase complex [see term 2]
part_of GO:0000794 condensed nuclear chromosome
capable_of GO:0019789 SUMO transferase activity
capable_of_part_of GO:0035825 homologous recombination
capable_of_part_of GO:0090173 regulation of synaptonemal complex assembly
capable_of_part_of GO:0007129 synapsis
DB xref:
IntAct:EBI-16586568

Term 2:
Name: SUMO ligase complex
Def: A protein ligase complex that enables protein sumoylation. Consists of a SUMO-protein transferase and other proteins that may confer substrate specificity of the complex.
Synonyms:
Sumoylation complex [EXACT]
SUMO transferase complex [EXACT]
SUMO-protein ligase complex [EXACT]
References:
GOC:to be created (Livia Perfetto)
PMID:16847351

Relationships:
is_a GO:1990234 transferase complex
capable_of GO:0019789 SUMO transferase activity
capable_of_part_of GO:0016925 protein sumoylation

**Comment by hdrabkin** [comment]
Hi Livia
Can you comment on any relationship to
 GO:1990354  activated SUMO-E1 ligase complex/ SUMO-SAE1/2 complex

**Comment by liviap** [comment]
Hi,
we suggest to make GO:1990354 a child of term 2.
we should change the def of term1 accordingly: Def: A SUMO-**E3** ligase complex capable of promoting synapsis, the meiotic cell cycle process where side by side pairing and physical juxtaposition of homologous chromosomes is created during meiotic prophase

**Comment by hdrabkin** [comment]
GO:0106068  SUMO ligase complex
GO:0106069 synapsis initiation complex
did not add your GOC:x until I know for sure what it is; can easily add once you figure it out.
Also changed parentage of GO:1990354  as suggested

**Comment by vanaukenk** [comment]
@hdrabkin - I will follow up with Livia and Birgit wrt getting Livia an xref and also entering her information into the users.yaml

**Comment by hdrabkin** [comment]
thanks Kimberly!
