### ISSUE TITLE
NTR: glucosylglycerate phosphorylase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#14604]
Proposed definition: Catalysis of the reaction: glucosylglycerate + phosphate = glucose-1-phosphate + D-glycerate
Parent: GO:0004645
There will be an EC reaction as soon as someone reviews the preliminary reaction in the EC; a MetaCyc reaction also exists, but so far only in our beta version.
The reaction is based on PMID 28754708.

Thanks!

**Comment by vanaukenk** [comment]
@keseler 
I added the new MF term.  When the EC xref becomes available, please feel free to re-open this ticket and I will add that to the term info.  Thx.
