### ISSUE TITLE
NTR: mitochondrial transmembrane transport terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14619]
NTR: mitochondrial guanine nucleotide transport
def: standard
ref: PMID:14998997
is_a parent: GO:0001408 guanine nucleotide transport
for this and orthologs http://www.uniprot.org/uniprot/P38988

NTR: mitochondrial potassium ion transmembrane transport
def: standard
is_a parent GO:0071805  potassium ion transmembrane transport
ref: PMID: 20197279

**Comment by pgaudet** [comment]
Hi @ValWood 
I assumed both terms were meant to be transmembrane. Here they are: 
 
+[Term]
+id: GO:0140140
+name: mitochondrial guanine nucleotide transmembrane transport
+namespace: biological_process
+def: "The process in which a guanine nucleotide is transported across a mitochondrial membrane." [GOC:vw, PMID:14998997]
+intersection_of: GO:1990542 ! mitochondrial transmembrane transport
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+intersection_of: results_in_transport_to_from_or_in GO:0005739 ! mitochondrion
+intersection_of: transports_or_maintains_localization_of CHEBI:16235 ! guanine
+created_by: pg
+creation_date: 2017-11-24T13:26:17Z
+
+[Term]
+id: GO:0140141
+name: mitochondrial potassium ion transmembrane transport
+namespace: biological_process
+def: "The process in which a potassium ion is transported across a mitochondrial membrane." [GOC:vw, PMID:20197279]
+intersection_of: GO:1990542 ! mitochondrial transmembrane transport
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+intersection_of: results_in_transport_to_from_or_in GO:0005739 ! mitochondrion
+intersection_of: transports_or_maintains_localization_of CHEBI:29103 ! potassium(1+)
+created_by: pg
+creation_date: 2017-11-24T13:26:42Z

Pascale
