### ISSUE TITLE
OTR: Missing parent? ligand-dependent nuclear receptor binding/TF binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14628]
Ligand-bound nuclear receptors are transcription factors https://en.wikipedia.org/wiki/Nuclear_receptor. Currently GO:0016922 ligand-dependent nuclear receptor binding is a child of receptor binding. 

Could you add an Is_a relationship to: transcription factor binding GO:0008134
ligand-dependent nuclear receptor binding  GO:0016922

**Comment by pgaudet** [comment]
Hi @hattrill 
I added the parent 'nuclear hormone receptor binding'. The term you mention 'GO:0016922 ligand-dependent nuclear receptor binding', refers to a binding that is 'ligand-dependent'; so it's in fact 'ligand binding-dependent nuclear receptor binding'. I am not sure this is how the term has been used. Is this something important for nuclear receptors (ie are there many protein bindings that are dependent on the ligand binding? 
Thanks, Pascale

**Comment by hattrill** [comment]
Ok, but we should review this term as part of the signaling project when we do these pathways.

**Comment by pgaudet** [comment]
I checked a few annotations and they were OK, so I will not create a ticket for this just yet. 

Thanks, Pascale
