### ISSUE TITLE
MP  GO:0090374   oligopeptide export from mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14620]
This appears to be a mitochondrial transmembrane transport term

but it is missing 
"mitochondrial transmembrane transport" parent

EXP from 
http://amigo.geneontology.org/amigo/term/GO:0090374
http://amigo.geneontology.org/amigo/gene_product/SGD:S000004178

everything else inferred

**Comment by pgaudet** [comment]
Hi @ValWood 
What do you mean 'everything else inferred'? For eg 'mitochondrial phosphate ion transmembrane transport' is not inferred to be mitochondrial transport.

**Comment by ValWood** [comment]
I think I must have meant that it has the "transmembrane transport" parent, but this needs to move down to "mitochondrial transmembrane transport"

**Comment by pgaudet** [comment]
Changed the genus for equivalence axiom from transport to 'GO:1990542 ! mitochondrial transmembrane transport' 
to 
- oligopeptide export from mitochondrion
- folic acid import into mitochondrion
- mitochondrial calcium ion transmembrane transport
- mitochondrial FAD transmembrane transport

**Comment by pgaudet** [comment]
Proposed solution at ontology call is to remove intracellular from ...

**Comment by ValWood** [comment]
why can't mitochondrial transmembrane Transport have "intracellular " in its logical def?

**Comment by pgaudet** [comment]
The logical definitions are still a little mysterious to me. But this is working !
