### ISSUE TITLE
Merge 'hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances' into child 'ATPase activity, coupled to transmembrane movement of substances'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14642]
Hello, 

I will merge 'GO:0016820 hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances' 
into the child 'GO:0042626 ATPase activity, coupled to transmembrane movement of substances'

* GO:0016820 has no EXP annotations
but has many InterPro annotations to the family IPR005897 ; @asangrador can you let me know if the merge will cause a problem ? 
all direct children should actually be children of 'GO:0042626 ATPase activity, coupled to transmembrane movement of substances'

Thanks, Pascale

**Comment by pgaudet** [comment]
Also merged 
-id: GO:0032146
-name: ATPase-coupled thiosulfate transmembrane transporter activity

into GO:0102025
+name: ATPase-coupled thiosulfate transmembrane transporter activity

as the logical definitions indicated that these two terms were equivalent. The merged term (GO:0032146) has no annotations.

**Comment by asangrador** [comment]
Hi,
There is no problem merging 'GO:0016820 hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances' into the child. Our annotations can easily be changed to the child or another more appropriate term.
Cheers,
Amaia
