### ISSUE TITLE
Facilitated diffusion is not a function - it's a process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14656]
@thomaspd "because a channel can do it"
Is synonym of 'uniporter activity' should be merged and moved. 
(no annotations)

**Comment by deustp01** [comment]
That may be, but classifying it as such will create a lot of single-step processes, so we may be stuck choosing which rule to break.

**Comment by pgaudet** [comment]
Hi @deustp01 
Right, we don't want to move it to process. However I think it can safely be merged into 'passive transmembrane transporter activity'. OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
We need to be able to annotate mitochondrial carriers (not the GO type of molecular carrier) to "transporter activity". They are transporters that  mediate "facilitated diffusion".
https://en.wikipedia.org/wiki/Passive_transport#Facilitated_diffusion

 I think all biologists would say the function of these carriers was 
as a type of "transmembrane transporter activity" ?

GO:0022803    passive transmembrane transporter activity 
 is the correct term for this  (although I admit we have not always used it  when we could).
The transporters which are transmembrane -type mitochondrial carriers, which function by this mechanism, should live under here.

I think the existing term "facilitated diffusion" should be obsoleted, it is confusing and misplaced.  I'm not sure that a process is needed, its more of a mechanism of transporter activity IMHO

**Comment by ValWood** [comment]
@pgaudet  I just saw you comment. Merging into  
GO:0022803 passive transmembrane transporter activity
 would work...

**Comment by ValWood** [comment]
But I think the child is wrong?

**Comment by ValWood** [comment]
Anyway it has no annotation...

**Comment by pgaudet** [comment]
I moved the children under uniporter (still to be reviewed):
- membrane potential driven uniporter activity
-- + sodium 
-- + potassium children

Pascale
