### ISSUE TITLE
process grouping term for nucleotide sugar TM transporters

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14650]
No nucleotide transmembrane -sugar grouping terms  for similar purine and pyrimidine transporters.

see
![missing tm transport paretn](https://user-images.githubusercontent.com/7359272/33233940-5572b6e6-d216-11e7-9fc9-622556ac64ab.jpg)

In fact, I don't think we need transmembrane and non-transmembrane versions of these AFAIK should all be under TM transport.
v

assigned to you @pgaudet

**Comment by pgaudet** [comment]
Hi, 

How about grouping like in Saier 2000 (PMID:10839820)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC98997/table/T4/ 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/4782928/33311561-7499bfcc-d425-11e7-82fe-7e913b2bbaaf.png">

**Comment by ValWood** [comment]
I think we largely have these groupings (via CHEBI)?.

It wouldn't help here though.

To logically group "purine-nucleotide sugar transmembrane transport" and
"pyrimidine nucleotide sugar transmembrane transport"  (which are closely related transporters, and we need a parent term as may not always know the specificity) we need the term
"nucleotide-sugar transmembrane transport"

In reality can probably rename 
"nucleotide-sugar transport"
to
"nucleotide-sugar transmembrane transport"

which would work just as well....would need to check annotations but I these should only be TM transport AFAIK

**Comment by pgaudet** [comment]
Decision: merge all 'nucleotide-sugar transport' terms (ie GO:0015780 and children) into the corresponding 'transmembrane transport. If the tm transport does not exist, then rename.

**Comment by ValWood** [comment]
GO:0015782 CMP-N-acetylneuraminate transport
has only NOT EXP (all are TM transporters)

GO:0015785
all EXP are TM transporter

GO:0015787
all EXP are TM transporter

GO:0015789
all EXP are TM transporter

GO:0015788
all EXP are TM transporter

GO:0015790
all EXP are TM transporter

**Comment by ValWood** [comment]
GO:0015783
protein also annotated to GDP-fucose transmembrane transporter activity

**Comment by ValWood** [comment]
GO:0036079
Single direct EXP annotation - OK SLC transporter
