### ISSUE TITLE
NTR:dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14655]
New Term Request: dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity

Is_a 
GO:0046527 | glucosyltransferase activity

Definition: 
Catalysis of the addition of the third glucose residue to the lipid-linked oligosaccharide precursor for N-linked glycosylation; the transfer of glucose from dolichyl phosphate glucose (Dol-P-Glc) on to the lipid-linked oligosaccharide Glc(2)Man(9)GlcNAc(2)-PP-Dol.

(note:description adapted from GO:0042283)

Ref: PMID: 9597543
xref:EC:2.4.1.256
GOC:ha
(http://www.enzyme-database.org/query.php?ec=2.4.1.256)

**Comment by hdrabkin** [comment]
done

**Comment by ValWood** [comment]
SGD, (and lots of  others via ISS/IEA) use
dolichyl-phosphate-glucose-glycolipid alpha-glucosyltransferase activity
Catalysis of the transfer of an alpha-D-glucosyl residue from dolichyl-phosphate D-glucose into a membrane lipid-linked oligosaccharide.


to describe this activity (from this very paper!). I think this should probably merge into the new, more complete term (it is only used for alg10 and its orthologs)

**Comment by hattrill** [comment]
Do you mean merge this and other terms like dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity under a more generic term 

or  make a dolichyl-phosphate-glucose-glycolipid alpha-glucosyltransferase activity parent term?

I will have to check with the FB curator who asked for this term, how many enzymes it covers in flies.

**Comment by ValWood** [comment]
I think 
dolichyl-phosphate-glucose-glycolipid alpha-glucosyltransferase

*only* refers to the alg10 step, if I understood correctly (It only seems to be used by ATG10)

If it is broader, your term  should be a child and existing annotations should move down to the new term.

**Comment by hdrabkin** [comment]
@hattrill ; Hi, Helen; anything on this? Can I close?

**Comment by hdrabkin** [comment]
@hattrill  and @ValWood : can you sort this out?

**Comment by pgaudet** [comment]
Let me know if you need help on these terms; I know someone in this field.

**Comment by ValWood** [comment]
I'm pretty sure the new term is the more correct description.

The term I am suggesting to merge with has 2.4.1
and its parent is also 2.4.1. 

I don't think we  need
GO:0004583, but  we only need if it is needed as a grouping term for other 
lipid-linked oligosaccharide pathway proteins?

At present it has no children....

**Comment by hattrill** [comment]
Looking at this:
GO:0004583	dolichyl-phosphate-glucose-glycolipid alpha-glucosyltransferase activity

Could be used as the parent term for:

GO:0106073	dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity
GO:0042281	dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity
GO:0042283	dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase activity
*GO:0033556	 dolichyl pyrophosphate Man7GlcNAc2 alpha-1,3-glucosyltransferase activity* I am not super-sure that this exists, the ref given - PMID:10336995 seems to suggest that this activity only occurs in alg2 deficient yeast. There are no annotations to this term.

**Comment by ValWood** [comment]
@hdrabkin ping

**Comment by sjm41** [comment]
Looks like the originally requested term was made (see below) and has since been used in annotations. So I'll close this ticket.

[Term]
id: GO:0106073
name: dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity
namespace: molecular_function
def: "Catalysis of the addition of the third glucose residue to the lipid-linked oligosaccharide precursor for N-linked glycosylation; the transfer of glucose from dolichyl phosphate glucose (Dol-P-Glc) on to the lipid-linked oligosaccharide Glc(2)Man(9)GlcNAc(2)-PP-Dol." [GOC:ha, PMID:9597543]
xref: EC:2.4.1.256
xref: RHEA:29543
is_a: GO:0046527 ! glucosyltransferase activity
created_by: hjd
creation_date: 2017-11-28T19:16:37Z
