### ISSUE TITLE
OTR: Missing parent:heparan sulfate proteoglycan biosynthetic process

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14669]
To mirror the structure for chondroitin sulfate biosynthetic process:

heparan sulfate proteoglycan biosynthetic process GO:0015012 should be a child of glycosaminoglycan biosynthetic process GO:0006024

![screen shot 2017-11-29 at 12 00 15](https://user-images.githubusercontent.com/11865746/33374273-5fd59a06-d4fd-11e7-8924-09e100ebd43e.png)

Thanks

**Comment by vanaukenk** [comment]
Hi @hattrill 

Looking at this branch of the BP ontology, it seems we make a distinction between the GAG biosynthetic process and the GAG proteoglycan biosynthetic process, so I think that the parentage as shown in the graph view above is okay.

However, I did see that GO:0050650 'chondroitin sulfate proteoglycan biosynthetic process' is the only GAG proteoglycan biosynthetic process term that has an is_a relation to GAG biosynthetic process.  The other GAG proteoglycan terms, e.g. GO:0015012 'heparan sulfate proteoglycan biosynthetic process', do not.

It seems, then, that the parent of GO:0050650 may not be correct and the is_a link to GO:0006024 'glycosaminoglycan biosynthetic process' should actually be removed.

**Comment by hattrill** [comment]
Hi @vanaukenk,

Yes, I see what you mean.  Makes sense to remove the is-a between GO:0050650 and GO:0006024.

**Comment by vanaukenk** [comment]
@hattrill 

It looks like the is_a parentage between GO:0050650 and GO:0006024 is coming in via the logical definition for 'chondroitin sulfate proteoglycan biosynthetic process' that references a preliminary ChEBI entry (CHEBI:26349) that classifies 'proteochondroitin sulfate' as a sulfated glycosaminoglycan. 

This is in contrast to other proteoglycans represented in ChEBI, e.g. heparan sulfate proteoglycan and dermatan sulfate proteoglycan, that are not classified as a sulfated glycosaminoglycans (although heparan sulfte proteoglycan is also classified as a polysaccharide sulfate).

So, to fix this in GO, I will temporarily remove the logical def for GO:0050650 and GO:0050654, assert the correct/consistent parentage in GO, and file a request with ChEBI to ask them to review the classification of the proteoglycan child terms.

Note that I'm also going to temporarily remove the logical defs for the equivalent heparan sulfate terms.

I'll leave this ticket open until we hear back from ChEBI and can re-enter logical defs for these terms.

**Comment by vanaukenk** [comment]
For reference:

https://github.com/ebi-chebi/ChEBI/issues/3400

**Comment by hattrill** [comment]
Thanks, Kimberly!

**Comment by vanaukenk** [comment]
Still waiting on ChEBI for a new term for logical defs, but I am going to close this ticket for now since the parentage in GO is now correct.
