### ISSUE TITLE
NTR 'regulation of adenylate cyclase-activating G protein coupled receptor signaling pathway 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14664]
Hello, 

For the GPCR project: we need 

'regulation of adenylate cyclase-activating G protein coupled receptor signaling pathway'
'positive regulation adenylate cyclase-activating G protein coupled receptor signaling pathway'
'negative regulation adenylate cyclase-activating G protein coupled receptor signaling pathway'
see https://github.com/geneontology/go-annotation/issues/1691

Thanks, Pascale

**Comment by hdrabkin** [comment]
done did
