### ISSUE TITLE
GO:0000733	DNA strand renaturation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14671]
_From @ValWood on November 25, 2017 12:59_

I was working with a collaborator yesterday  to refine some phenotypes based on GO and we think this term looks odd.

Should it be called "annealing" (renaturation isn't a process,  it will occur in a test tube with any complementary DNA?)

It also has the child
GO:0061306    DNA strand renaturation involved in double-strand break repair
(one experimental annotation)
This  gene also has

GO:0010709    
heteroduplex formation involved in double-strand break repair via synthesis-dependent strand annealing

which is probably describing the same process?
@hattrill  http://www.uniprot.org/uniprot/Q9VMX6

the children of
https://www.ebi.ac.uk/QuickGO/term/GO:0000733
imply it is describing the activity of a helicase

PomBase have used for  2 condensin units, which seems *completely* wrong?
https://www.pombase.org/term/GO:0000733

_Copied from original issue: geneontology/go-annotation#1709_

**Comment by pgaudet** [comment]
_From @ValWood on November 25, 2017 13:7_

hmm may be it's OK, I'm not sure....
I'm still confused by the differences between annealing, renaturation and rewinding....

**Comment by pgaudet** [comment]
_From @hattrill on November 27, 2017 7:41_

Seems like one is recombination driven and one isn't. I don't understand why renaturation is used instead of annealing. 
I guess the rewinding can be separable from annealing.....this could probably do with an expert eye, as it is not immediately obvious if these terms would mean the same to them.

**Comment by pgaudet** [comment]
_From @mah11 on November 27, 2017 11:49_

I didn't have answers then and I don't now, but this stuff came up a while back on the ontology tracker - 

https://github.com/geneontology/go-ontology/issues/12539

and the older ticket linked there.

**Comment by pgaudet** [comment]
_From @ValWood on November 27, 2017 13:52_

This isn't urgent as not many annotations would be affected. It seems like an issue that might be addressed during  some later stage MF refactoring .....

**Comment by vanaukenk** [comment]
@pgaudet - should I assign this to you (part of the MF refactor) or the next editor on the rota?

**Comment by pgaudet** [comment]
Sure

**Comment by pgaudet** [comment]
Looking at EXP annotations, I would propose to obsolete  
 GO:0000733 DNA strand renaturation
and GO:0061306 DNA strand renaturation involved in double-strand break repair 
with 'consider GO:0036310 annealing helicase activity'. 


Opened an annotation review ticket: https://github.com/geneontology/go-annotation/issues/3621

**Comment by pgaudet** [comment]
We should also look at 'DNA duplex unwinding' - this also seems to be a MF
