### ISSUE TITLE
F-P link GO:0019888	protein phosphatase regulator activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14673]
_From @gocentral on November 14, 2014 14:30_

Could it go to

part_of
GO:0043666  regulation of phosphoprotein phosphatase activity

and
GO:0004864 - protein phosphatase inhibitor activity
to
negative regulation of phosphoprotein phosphatase activity

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1251](https://sourceforge.net/p/geneontology/annotation-issues/1251)

_Copied from original issue: geneontology/go-annotation#1232_

**Comment by ValWood** [comment]
It isn't clear to me why this isn't inferred by  existing logical relationships.
Let me know  why not and I'm happy to delve.

@kltm 
@cmungall 

cheers

Val

**Comment by pgaudet** [comment]
Val, 
It's not reasonning because the relation was not there. The logical definitions are really incomplete (and still quite inconsistent), so please send requests if you see an assertion missing.  

Thanks, Pascale
