### ISSUE TITLE
query about F-P links

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14674]
_From @gocentral on November 11, 2014 16:49_

GO:0004129 - cytochrome-c oxidase activity has an FP link to hydrogen ion transmembrane transport. I have 11 gene products ~annoyed~ annotated to GO:0004129
but only 4 are ~pricking~ picking up this mapping. cox1,2,3,5 Why is that?

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1249](https://sourceforge.net/p/geneontology/annotation-issues/1249)

_Copied from original issue: geneontology/go-annotation#1230_

**Comment by pgaudet** [comment]
_From @ValWood on November 3, 2017 10:58_

Is this because mappings d not propagate across non-experimental evidence codes?

If so, shouldn't they?

**Comment by ValWood** [comment]
This is no longer an issue,  a problem F-P link has been removed.

v
