### ISSUE TITLE
How to name specific MAPK pathways

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14676]
_From @ukemi on July 13, 2017 12:23_

Perhaps a model were we just say

MAPK cascade part_of "response to osmolarity stress"
MAPK cascade part_of "response to oxidative stress"
would work better. The current situation already has lots of problems.

For instance the same pathway named differently (is stress-activated MAPK cascade the same as MAPK cascade involved in osmosensory signaling pathway?)

_Copied from original issue: geneontology/go-annotation#1597_

**Comment by pgaudet** [comment]
_From @ValWood on July 13, 2017 13:0_



Problem illustrated here:
https://github.com/pombase/curation/issues/1593

so terms like

GO:0051403  stress-activated MAPK cascade
and
GO:0000161MAPK cascade involved in osmosensory signaling pathway

Or
MAPK cascade in response to starvation
and
GO:0071507MAPK cascade involved in conjugation with cellular fusion

are frequently used to describe the exact same pathway.
The pathways can be activated in subtly different ways in response to different stresses.
so it does not make sense to precompose them all.

It was been unclear to me whether the labels in GO represented the names of the main pathways (historically) , or if they were meant to be comprehensive (an hence largely  redundant) with respect to stresses

Between species problems emerge. The main stress pathway in  pombe sty1 , is routinely called HOG1 osmolarity sensing pathway in S. cerevisiae, but the conserved  pathway senses many stresses (oxidative/osmolarity). Often these are curated at the level of the chemical used (hydrogen peroxide, salt stress, heat)

A general approach would really help here.


--

**Comment by pgaudet** [comment]
_From @ValWood on July 15, 2017 7:18_

Antonia did a "clean up"
This is wheat we have
http://pombase2.aska.gen.nz/term/GO%3A0000165
The  pathway MF's are also connected to each other by has_substrate, so we can  generate the individual pathways (we would like to include substrates on this page too, longer term).

I think we should move
MAPK cascade involved in osmosensory signaling pathway
to be
stress-activated MAPK cascade involved_in cellular response to osmotic stress
to reduce the duplication

MAPK cascade involved in osmosensory signaling pathway is just a sub branch of the main stress MAP cascade.....

--

**Comment by pgaudet** [comment]
_From @ValWood on October 1, 2017 12:27_

I think the decision here is that we need the different named pathways.

Yeast has 3.
Stress activated
Pheromone activated
Cell integrity


Need to check how these should be named with SGD @srengel 
Re-annotate ours  to correct flavour of MAPK where necessary


and how they relate to the canonical human pathways

**Comment by pgaudet** [comment]
_From @ukemi on October 1, 2017 20:1_

I thought I had read that yeast has one called osmosensing or osmolarity sensing?

**Comment by pgaudet** [comment]
_From @srengel on October 1, 2017 20:11_

Do you mean the HOG1 pathway? Osmosensory signaling pathway.

**Comment by pgaudet** [comment]
_From @ValWood on October 1, 2017 21:46_

yep but that is the "stress activated pathway".
It responds to multiple stresses (osmolarity, oxidative stress, heat, some nutrient limitation).
I think it's a single pathway though?

I thought that to capture individual stresses we might do
stress activated MAP kinase pathway part_of "response to oxidative stress" etc.
perhaps?

**Comment by pgaudet** [comment]
The little I know about this from PAINT seems like a small number of MAP kinases are involved in the response to a large number of inducers. My understanding is that often the type of inducer doesn't really matter, it's more the assay than a conclusion about a specific stress inducer. (This is why I wanted to have 'response to stress' to manually annotate with PAINT but mostly nobody agreed). 

Thanks Pascale

**Comment by pgaudet** [comment]
_From @srengel on October 2, 2017 8:24_

heat stress goes through one set of sensors, that can also sense oxidative and osmotic stress, but osmo and oxi stress also can go through another set of sensors.  both converge on the same MAPKK.  we have a little diagram here: http://wikipathways.org/index.php/Pathway:WP2838

i forwarded this issue to Rob at SGD, he might have more insight to share.

**Comment by pgaudet** [comment]
_From @RLovering on October 2, 2017 8:48_

my interpretation is the same as Val's. We would annotate a gene: intracellular signaling pathway part_of response to stimulus.

**Comment by pgaudet** [comment]
_From @robnash on October 2, 2017 18:5_

Hi,

Not sure what input is needed here? There are as many as five MAPK pathways in budding The hyperosmotic stress pathway also called the High Osmolarity Glycerol (HOG) response pathway does have different upstream inputs that as far as I can remember feed through a conserved MAPK pathway including: hyperosomtic stress, oxidative stress and heat shock (See PMID: 15603750 for comparison of pombe, cerevisiae and albicans). 

In addition to this stress activated MAPK pathway budding yeast also has the follwoign pathways:

mating or pheromone response pathway
filamentous/invasive growth pathway 
cell wall integrity pathway

and not sure that this is canonical as it contains SMK1 (MAPK) but is activated by CAK1, apparently has the RAS/cAMP pathway and IME2 upstream and has only been partially defined (PMID: 26246597, PMID: 19087957)

spore assembly/morphogenesis pathway

There are some nice overviews of all of these in these article:

Hamel LP, Nicole MC, Duplessis S, Ellis BE. Mitogen-activated protein kinase
signaling in plant-interacting fungi: distinct messages from conserved
messengers. Plant Cell. 2012 Apr;24(4):1327-51. 
PMID: 22517321; PMCID: PMC3398478.

Engelberg D, Perlman R, Levitzki A. Transmembrane signaling in Saccharomyces
cerevisiae as a model for signaling in metazoans: state of the art after 25
years. Cell Signal. 2014 Dec;26(12):2865-78. 
PubMed PMID: 25218923.

I think of the central MAPK components as modules that often respond to different inputs and result in different outputs, as some of these MAPK components are used in more than one pathway (e.g. mating and filamentation).

Some diagrams to orient you:

http://www.plantcell.org/content/plantcell/24/4/1327/F1.large.jpg

http://www.genome.jp/kegg-bin/show_pathway?ko04011

http://www.sciencedirect.com/science?_ob=MiamiCaptionURL&_method=retrieve&_eid=1-s2.0-S0167488907001218&_image=1-s2.0-S0167488907001218-gr1.jpg&_cid=271024&_explode=defaultEXP_LIST&_idxType=defaultREF_WORK_INDEX_TYPE&_alpha=defaultALPHA&_ba=&_rdoc=1&_fmt=FULL&_issn=01674889&_pii=S0167488907001218&md5=c300f8a67689b4b673272065e4cae720

Cheers,
Rob

**Comment by pgaudet** [comment]
_From @ValWood on October 5, 2017 13:46_

It seems that we need to figure how the  MAPK pathways in each species  and their different names relate to each other.

It should be fairly straightforward.
Fission yeast has 3 "fairly linear" pathways (3 of each component MAPKKK, MPKK and MAPK present).

In fission yeast
Sty1/Spc1 MAPK = S.c  Hog1
(canonical MAPK stress pathway)
but the hog1 pathway in GO  should be a descendant  of this and  have taxon restrictions
(it has its Own MAPKKK but shares  the MAPKK and MAPK with canonical stress pathway?)

pombe has cell integrity pathway (the MAPK is pmk1 = SLT2 in S. cerevisiae)
I don't know which the "ancestral pathway is, or if this has a metazoan counterpart?

pombe has the pheromone pathway (Spk1 = S. cerevisiae FUS3).
For this we have been using

MAPK cascade part of positive regulation of conjugation with cellular fusion
but do we probably  need to instantiate each  independent  pathway
So we would have
"MAPK pheromone response pathway"
and 
"MAPK cell integrity pathway"

If we go down this route we should rename

GO:0000196    MAPK cascade involved in cell wall organization or biogenesis | is_a
as
"MAPK cell integrity signalling"

and
GO:0071507    MAPK cascade involved in conjugation with cellular fusion
as
"MAPK pheromone response signalling"

So we can slot these "cassettes" into place  in the broader context of "pheromone signalling"
and "cell integrity signalling"

**Comment by pgaudet** [comment]
_From @ValWood on October 5, 2017 13:48_


although I don't think we should have terms like
GO:1903616    MAPK cascade involved in axon regeneration

there should be a distinction between 
a) the name of the  pathway (specific module) is referred to by the community
and
b)  the range of downstream targets. 

GO:1903616    MAPK cascade involved in axon regeneration
seems to be a  specific downstream target of  one of the modules?

**Comment by pgaudet** [comment]
_From @ValWood on October 18, 2017 9:27_

From https://github.com/geneontology/go-ontology/issues/14323#issuecomment-336973187

MAPK cascade involved in conjugation with cellular fusion
MAPK cascade involved in cell wall organization or biogenesi

were previously used to represent specific MAPK modules.


I think what we are trying to represent here are the 3 main types....
These are illustrated nicely in the KEGG MAPK pathway diagram link posted by Rob:
http://www.genome.jp/kegg-bin/show_pathway?ko04011

This is the human
http://www.genome.jp/kegg/pathway/hsa/hsa04010.html

So it seems these are "equivalent"
KEGG human classical
GO:0070371 ERK1 and ERK2 cascade (for metazoa) (MAPK1/3)
KEGG yeast pheromone
GO:0071507 MAPK cascade involved in conjugation with cellular fusion
(Features is downstream of G-protein signalling?)

These are "equivalent"
KEGG human JNK and p38
GO has for human:
GO:0007254 JNK cascade (child of stress-activated MAPK cascade)
GO:0038066 p38MAPK cascade (child of stress-activated MAPK cascade)
KEGG yeast "high osmolarity"
GO:0051403 stress-activated MAPK cascade (pombe uses this term, there is also GO:0000161 MAPK cascade involved in osmosensory signaling pathway (but this is really an inout variation of the main stress pathway module)

These are "equivalent"
KEGG human ERK5
GO:0070375 ERK5 cascade (only has 3 manual annotations!)
KEGG Cell wall stress (yeast)
GO MAPK cascade involved in cell wall organization or biogenesis (for yeast)

I think this is correct although it would need double checking.....

**Comment by pgaudet** [comment]
_From @ValWood on October 18, 2017 9:52_


I can't think of a way to name the orthologous modules *except* to include the major MAK names:

GO:0070375 ERK5 cascade  = MAPK7/SLT2/pmk1 MAPK module
(ERK5 more commonly called MAPK7)

GO:0070371 ERK1 and ERK2 cascade  = MAPK1,3/FUS3/Spk1 MAPK module

( ERK1 and ERK2 cascade more commonly called MAPK1,3)

This would avoid using potentially confusing concepts related to what the pathways regulate but would make the modules types more instantly recognizable for  both metazoa and yeast.

**Comment by pgaudet** [comment]
_From @robnash on October 18, 2017 17:27_

Unless these are renamed, I think it would be very unintuitive to name the module members in yeast based on mammalian cascades like those you describ with names like ERK5 cascade and ERK1 and ERK2 cascade. I would prefer Pascale's idea of migrating up to "MAPK cascade" for now and use column 16 to describe the "part of" for particular perturbation/effector driven pathway activation.

**Comment by ukemi** [comment]
Helpful review articles:

- PMID:26646897-In plants MAPK pathways respond to stress and developmental signals. MAPKs regulate: protein stability, catalytic activity, protein localization, protein binding.

- PMID:28903453 shows four different kinds of pathways in figure 1. The pathways are classified by the MAPKs that they contain: ERK, p38, JNK and ERK5. The authors imply that each of the pathways, although activated canonically by a given type of signal, can also be activated in other ways and there is cross talk between the pathways.

- PMID:28669664 uses the same categorization as above.

- PMID:25227612 describes the Hog1 pathway and groups p38, JNK and Hog1 into one class of stress-activated MAPKs. The metazoan pathways are more complex.

- PMID:20880736 says there are five pathways in yeast and names three: pheromone response (Fus3), filamentous growth response (Kss1), and osmostress response (Hog1) all use the same MAPKKK. 

-PMID:17604854  enumerates the five:pheromone/ pheromone response pathway (Fus3, Kss1), partial nutrient deprivition/filamentous growth pathway (Kss1), hyperosmolarity/glycerol pathway (Hog1), cell wall stress/cell wall integrity pathway (Mpk1), nutrient starvation/ spore wall assembly pathway (Smk1). Again, there is lots of cross-talk.

**Comment by ukemi** [comment]
Proposal to discuss on annotation call:
Mapk cascade
--ERK1 and ERK2 cascade PMID:28903453
--ERK5 cascade PMID:28903453
--MAPK cascade involved with conjugation with cellular fusion (RENAME 'pheromone response MAPK cascade' Fus3)PMID:17604854
--MAPK cascade involved in cell wall organization and biosynthesis (RENAME 'cell wall integrity MAPK cascade' Mpk1)PMID:17604854
--stress-activated MAPK cascade
----JNK cascade PMID:28903453
----p38MAPK cascade PMID:28903453
----MAPK cascade involved in osmosensory signaling (RENAME 'osmosensory signaling MAPK cascade' Hog1)PMID:17604854
----MAPK cascade involved in nutrient starvation (RENAME  spore wall assembly MAPK cascade Smk)
PMID:17604854
----filamentous growth MAPK cascade PMID:17604854

For all of the others, review annotations to see if they can be merged into one of these, or reannotate to one of these. I'm not sure if we should have named pathways for plants?

**Comment by ValWood** [comment]
This is great. I think it would be nice if there was always a common parent for orthologous pathways but it might even be impossible! This  would be a big improvement.

**Comment by robnash** [comment]
Yes, I like this proposal. I like the fact that all pathways would be named the way researchers would expect to see them!

**Comment by ukemi** [comment]
@vanaukenk can we put this on agenda for the next annotation call? I'd like to generate the required annotations review tickets. It would be nice to wrap this up before the May meeting.

**Comment by ukemi** [comment]
@tberardini, can you weigh in on whether it would be worthwhile to have named pathways for plants? If so, what do you suggest?

**Comment by tberardini** [comment]
I found this 2015 paper, https://onlinelibrary.wiley.com/doi/epdf/10.1111/tpj.12808, "Identification and characterization of an **ABA‐activated MAP kinase cascade** [emphasis mine] in Arabidopsis thaliana" which could fall under 'stress-activated MAPK cascade'.

**Comment by pgaudet** [comment]
Just wondering - if we add any inducer of the MAK pathway, as a separate GO term, will we not create a very large number of terms ? 
(this case seems different from classes that describe pathways by the ligand and receptor, in which case there are much fewer possibilities; but since the MAPK pathway integrates various signals I am a bit worried about the 'ABA‐activated ' pattern. )

Pascale

**Comment by tberardini** [comment]
You don't need to create the term 'ABA-activated MAPK cascade', the gene products that belong to this cascade could fall under/be annotated to 'stress-activated MAPK cascade.' and not any of its current (or proposed to be renamed) child terms if that level of specificity is not desired.

**Comment by pgaudet** [comment]
Ah got it, thanks !
