### ISSUE TITLE
NTR: rotatasome

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14683]
Described in _Pseudotrichonympha leei, Pseudotrichonympha lifesoni, and Pseudotrichonympha pearti, new species of parabasalian flagellates and the description of a rotating subcellular structure_

https://www.nature.com/articles/s41598-017-16259-8

Def: an intracellular body of unknown function found in Pseudotrichonympha

**Comment by pgaudet** [comment]
Hi @cmungall 

If we were to vote on the creation of this term, I would say no because we don't know the composition, so there are no proteins to annotate to it.  Moreover the authors speculate it may be a symbiont... 

Thanks, Pascale

**Comment by pgaudet** [comment]
At the GH hackaton we decided to close this. Not enough evidence yet to include this term.
