### ISSUE TITLE
GO:0004516 (nicotinate phosphoribosyltransferase activity) should now be a ligase?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#14684]
GO:0004516 is currently classed as a 'transferase activity' in the GO, with an EC xref of 2.4.2.11

But the EC reclassified this enzyme as a ligase at some point.  See: 
http://enzyme.expasy.org/EC/2.4.2.11

So, please check, but it looks like GO:0004516 should also be moved to be under 'ligase activity' in the GO, with the EC xref updated to 6.3.4.21 (Nicotinate phosphoribosyltransferase).

@hattrill

**Comment by hdrabkin** [comment]
However, not all known ligases are under 6.3.4, only some of them; 
I'll change the EC number now,
I am at a loss as to why this is now a ligase rather than a transferase; it is not something I would expect to get returned if I searched on "ligase"

**Comment by hdrabkin** [comment]
EC 6.3: Forming Carbon-Nitrogen bonds GO:0016879
Done
