### ISSUE TITLE
GO:0007585  ! respiratory gaseous exchange flipped w.r.t GO:0003016-respiratory system process

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14681]
![image](https://user-images.githubusercontent.com/50745/33465408-957af9ee-d5fc-11e7-8e60-db756b156b9f.png)

**Comment by ukemi** [comment]
The def of 'respiratory gaseous exchange' is very broad and includes plants. Do we want to lump things like stomata in plants into the respiratory system term? If not, this switch will create a TPV.

**Comment by ukemi** [comment]
@tberardini , I know we discussed this long ago and came up with the current structure. What do you think?

**Comment by tberardini** [comment]
>  Do we want to lump things like stomata in plants into the respiratory system term?

I would not want to do this.

Though I do not see any plant genes annotated to 'respiratory gaseous exchange', the definition does include plants and microorganisms. There isn't a 'respiratory system' in plants.  I would prefer not to flip order of the terms in the relationship.

**Comment by ukemi** [comment]
But the potential exists that you would at least want to regulate to regulatory terms, right? Isn't there some very cool biology with respect to opening and closing the stomata to regulate the exchange and also to keep plants from dehydrating, night versus day etc?

**Comment by tberardini** [comment]
Yes, even though the terms (core and regulation) have not been used for plant gene products yet, I can see wanting to use them.

**Comment by cmungall** [comment]
we can't keep the existing structure though

diaphragm contraction is_a respiratory system process is_a respiratory gaseous exchange: TPV!

currently only one child, bad smell!

```
     is_a GO:0003016 ! respiratory system process *** 
      is_a GO:0002086 ! diaphragm contraction
```

is GO:0003016 any use? we get the grouping in animals from uberon (once we axiomatize GO:0002086)

I say get rid of it 

we have 13 experimental annotations but they are all IMP in mouse:

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=annotation_class:%22GO:0003016%22&fq=evidence_subset_closure_label:%22experimental%20evidence%22&sfq=document_category:%22annotation%22

Looking at the MP terms, if we want to capture this as weak causally upstream of GO annotations (it's not clear we should) then some will go into things like 'lung saccule development'. For others the phenotype is something like 'respiratory distress' or 'pulmonary edema'. There isn't a direct GO cognate for these so I can see the desire for a broad 'respiratory system process', but I don't really see the point of making weaker shadow versions of the MP annotations if we don't have any insight into function

**Comment by ukemi** [comment]
I would be tempted to merge respiratory system process into the gaseous exchange term and then make the diaphragm term a part of to the gaseous exchange term.

**Comment by tberardini** [comment]
> I would be tempted to merge respiratory system process into the gaseous exchange term and then make the diaphragm term a part of to the gaseous exchange term.

And make 'respiratory system process' a narrow synonym, right?

**Comment by cmungall** [comment]
On 7 Dec 2017, at 8:09, David Hill wrote:

> I would be tempted to merge respiratory system process into the 
> gaseous exchange term and then make the diaphragm term a part of to 
> the gaseous exchange term.

that doesn't seem right. gaseous exchange seems to have a specific 
physiological meaning, e.g.

"Gas exchange is the biological process by which gases move passively by 
diffusion across a surface. Typically, this surface is - or contains - a 
biological membrane that forms the boundary between an organism and its 
extracellular environment."

from https://en.wikipedia.org/wiki/Gas_exchange

contraction of diaphragm would have some kind of causal relation to GE, 
but for it to be part-of GE would make GE so broad to essentially be 
"respiratory system process" (even if the term is not used in plants, 
this proposed GE term would essentially be "multi-species respiratory 
related process")

More generally, I feel the emphasis on broad physiology is misplaced. We 
should focus on processes like control of stomata size, muscle 
contraction, development of the respiratory organs.

Many of the GO annotations just mirror what you can get in a more 
granular way from phenotype annotation. We should focus on what GO does 
well.

See
http://amigo.geneontology.org/amigo/term/GO:0007585

the IGI has a bit more info than what you get from the pheno annotation, 
regulation of resp system process
https://www.ncbi.nlm.nih.gov/pubmed/16982420

But this feels like a missed opportunity. How is it regulating this, and 
what is the actual process regulated?

Skimming the paper it seems like we could make a GOCAM where these gene 
is involved in GABAergic/glycinergic and glutamatergic synaptic 
transmission in the Pre-Bötzinger complex and this regulates a rhythmic 
muscular process in the diaphragm.

Even without GOCAMs we could have made a more precise annotation.

No plant annotations yet but this seems really important to a ton of 
plant use cases, it affects agriculture, climate...

and there are ton of interesting alternate mechanisms of 'breathing' in 
other animals, seems a shame just to bin under a very vague term

**Comment by ukemi** [comment]
Yep. This is assigned to you, will yo edit or do you want to reassign?

**Comment by ukemi** [comment]
I don't think gaseous exchange was meant to be restricted to the difffusion, but was meant to include how the gasses get moved. That is why it is such a general term. But you are correct, from our viewpoint it would be much better to make a specific annotation to an existing or new term than to such a broad term. But unless we commit the resources to enhance annotation and ontology development specifically in this are of biology, do we want to go that route or leave it general for now?

**Comment by ukemi** [comment]
Maybe the action here is simply to make the diaphragm term a Part_of and keep the existing structure?

**Comment by pgaudet** [comment]
Maybe add a comment ?

**Comment by ukemi** [comment]
Proposal:

Change 'respiratory system process' to 'respiratory gaseous exchange by respiratory system'
make 'diaphragm contraction' a part_of 'respiratory gaseous exchange by respiratory system'

**Comment by ukemi** [comment]
@mungall and @tberardini. Excavating history here trying to close some of these older tickets. I think the issue here is one of parthood. 'Respiratory system process'=A system process carried out by the organs and tissues of the respiratory system. The respiratory system is an organ system responsible for respiratory gaseous exchange.

I think that this term should be renamed as above suggested or the definition should be tweaked.
I think this should more properly read: A process carried out by the organs and tissues of the respiratory system. The respiratory system is an organ system responsible for respiratory gaseous exchange.

Any respiratory system process would then be a part-of respiratory gaseous exchange. I would be cautious about the 'bad smell' of diaphragm contraction being the only child at this point. I suspect this is due more to incompleteness than to ground truth. Gaseous respiration in animals is more complex than just the movement of the diaphragm. I suspect a physiologist might also include the cilia of the trachea etc.

**Comment by tberardini** [comment]
> I think that this term should be renamed as above suggested or the definition should be tweaked.

How about both?   Together, those steps would be extra clarifying.

**Comment by ukemi** [comment]
OK. I've tweaked the term names and relationships as described above. If this doesn't work, please reopen the ticket.
