### ISSUE TITLE
Query  GO:0032066 nucleolus to nucleoplasm transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14690]
_From @pgaudet on June 20, 2017 15:50_

This issue arises form 
https://github.com/geneontology/go-ontology/issues/13686

Val writes: 
The nucleolus is not a separate compartment as such

nucleolus
Ontology Cellular Component
Definition A small, dense body one or more of which are present in the nucleus of eukaryotic cells. It is rich in RNA and protein, is not bounded by a limiting membrane, and is not seen during mitosis. Its prime function is the transcription of the nucleolar DNA into 45S ribosomal-precursor RNA, the processing of this RNA into 5.8S, 18S, and 28S components of ribosomal RNA, and the association of these components with 5S RNA and proteins synthesized outside the nucleolus. This association results in the formation of ribonucleoprotein precursors; these pass into the cytoplasm and mature into the 40S and 60S subunits of the ribosome.

...and I'm not aware of a transport mechanism between the two ... This has only 3 EXP annotations
UniProtKB Q14191 WRN IDA PMID:11420665 MGI
UniProtKB Q3YBR2 TBRG1 IDA PMID:17110379 HGNC
UniProtKB Q9Y3T9 NOC2L IDA PMID:20123734 UniProt

@ukemi 
@RLovering 
@sylvainpoux

would you please check your annotations and see if this term is required? 

Thanks, Pascale

_Copied from original issue: geneontology/go-annotation#1571_

**Comment by pgaudet** [comment]
_From @ValWood on June 20, 2017 16:56_

to clarify, should say 
of a transport mechanism between the  nucleolus and  nucleoplasm 
(context in other ticket)
v

**Comment by pgaudet** [comment]
Hi @RLovering 
@hdrabkin 

I think the term 'GO:1902570 protein localization to nucleolus' would be more appropriate; is that OK for you ? I could do a merge. 

Thanks, Pascale

**Comment by pgaudet** [comment]
_From @hdrabkin on November 30, 2017 14:25_

Yes, the authors refer to  'nucleolar localization' , so I think that will be safe.

**Comment by RLovering** [comment]
Hi
I have just had a quick look at the HGNC annotation, and fig 4 in the paper states: Representative confocal images (shown above) illustrate how NIAM promotes partial redistribution of ARF from nucleoli to the nucleoplasm, whereas control cells lacking NIAM exhibit highly discrete nucleolar localization of ARF. 
However, I have reannotated this to GO:1990173 protein localization to nucleoplasm

I think you could do the merge with GO:1990173 protein localization to nucleoplasm, but the merge suggested above ( GO:0032066 nucleolus to nucleoplasm transport with GO:1902570 protein localization to nucleolus) would be completely wrong. 

If the other 2 annotations are revised then I guess the other option is just to obsolete the term.

Best

Ruth
