### ISSUE TITLE
Missing parentage GO:0120113

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#14696]
Hello! 

Could you please add 2 parent terms to GO:0120113  protein localization by the NVT pathway

GO:0061919 & GO:0072665

**Comment by ukemi** [comment]
Please see #14453. We though this was distinct and did not use autophagy machinery.

**Comment by ValWood** [comment]
Yes I don't think we should add using "autophagic machinery" (but I still think it's probably  a bit of a fudge to group CVT and autophagy under autophagy)
but we should add GO:0072665 (it is transport to vacuole)

**Comment by ukemi** [comment]
I think that is already there, isn't it?

**Comment by ValWood** [comment]
It is!
