### ISSUE TITLE
merge GO:0031662    positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14709]
GO:0031662    positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle

Has only 2 EXP annotations

should merge into
GO:0010971    positive regulation of G2/M transition of mitotic cell cycle

becasue
G2/M transition of mitotic cell cycle

ise defined
The mitotic cell cycle transition by which a cell in G2 commits to M phase. The process begins when the kinase activity of M cyclin/CDK complex reaches a threshold high enough for the cell cycle to proceed. This is accomplished by activating a positive feedback loop that results in the accumulation of unphosphorylated and active M cyclin/CDK complex.

which means that  
GO:0010971    positive regulation of G2/M transition of mitotic cell cycle
and
GO:0031662    positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle

are logically equivalent (i.e positive regulation of G2/M IS  only achieved by positive regulation of CDk1)

**Comment by hdrabkin** [comment]
@ValWood 
can you comment on the synonyms for the GO:0031662 ; does it make sense to keep them?

**Comment by hdrabkin** [comment]
Hi @ValWood , can you comment on whether I should keep all of the synonyms for 1662?

**Comment by ValWood** [comment]
I would just keep the term name.

I don't know why we have the "upregulation" synonyms anyway (who says upregulation?)
;)

**Comment by hdrabkin** [comment]
done
