### ISSUE TITLE
MP mitochondrial transport relations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14707]
protein import into mitochondrial matrix
has parent
GO:0044743   
protein transmembrane import into intracellular organelle
but not
GO:1990542 mitochondrial transmembrane transport

**Comment by ValWood** [comment]
GO:1990542    mitochondrial transmembrane transport
has lost its parent
GO:0006839 (mitochondrial transport)
2017-11-30	Deleted	RELATION	is a GO:0006839 (mitochondrial transport)

and

MP	GO:1904983	glycine import into mitochondrion
should have the parent 
GO:1990542    mitochondrial transmembrane transport
added
(only has GO:0006839 (mitochondrial transport)

**Comment by pgaudet** [comment]
protein import into mitochondrial matrix
Logical definition was:
'protein import'
 and ('occurs in' some cytoplasm)
 and ('has target end location' some 'mitochondrial matrix')

changed to
'protein import'
 and ('has target start location' some cytoplasm)
 and ('has target end location' some 'mitochondrial matrix')
 and ('results in transport across' some 'mitochondrial membrane')

accoring to https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/organelle_transmembrane_transport.yaml

**Comment by pgaudet** [comment]
@ValWood ... nothing with logical definitions is a quick fix ;)
