### ISSUE TITLE
obsoletion - cAMP biosynthetic process 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14718]
Hello, 
Following annotation reviews here: 
https://github.com/geneontology/go-annotation/issues/1691

I propose to merge: 
-  GO:0030817 regulation of cAMP biosynthetic process into
-> GO:0007188 adenylate cyclase-modulating G-protein coupled receptor signaling pathway
--  3 EXP annotations, all to G-protein coupled **receptors** (ie, that's how it's been interpreted)

- GO:0030818 negative regulation of cAMP biosynthetic process
--  94 EXP annotations, **most** to G-protein coupled **receptors** but also annotations of Adenylate cyclase and others
- GO:0030819 positive regulation of cAMP biosynthetic process 
--  59 EXP annotations, **most** to G-protein coupled **receptors** but also annotations of phosphodiesterase and other proteins
These two should perhaps be obsoleted to avoid any misinterpretation. There are probably other correct annotations, including these that we made during the annotation review. 

@pfey03 
@ukemi 

Does that seem OK to you ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi

All annotations to the regulation of cAMP biosynthesis terms by UCL have  been revised

Ruth

**Comment by pgaudet** [comment]
Obsoletion notice sent Dec 6, 2017 


The proposal has been made to obsolete 

GO:0030818 negative regulation of cAMP biosynthetic process
-- 94 EXP annotations, most to G-protein coupled receptors but also annotations of Adenylate cyclase and others

GO:0030819 positive regulation of cAMP biosynthetic process
-- 59 EXP annotations, most to G-protein coupled receptors but also annotations of phosphodiesterase and other proteins



The reason for obsoletion is that the term has been used inconsistently for proteins involved in G-protein coupled receptor pathway, and the regulation of the GPCR pathway. Obsoletion will avoid any misinterpretation. 

Most groups have alrad updated their annotations (https://github.com/geneontology/go-annotation/issues/1691) 


We are opening a comment period for this proposed obsoletion. Please comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/14718

We’d like to proceed and obsolete this term on Dec 13, 2017. Unless objections are received by Dec 13, 2017, we will assume that you agree to this change.


Thanks, Pascale
