### ISSUE TITLE
Logical definitions organelle transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14716]
Hello, 

The logical definitions for transport into/out of organelles are inconsistent: 

we sometimes have 
transport
 and ('has target start location' some **cytoplasm**)
 and ('has target end location' some nucleus)
 and ('results in transport across' some 'nuclear envelope')

but sometimes the start location is **cytosol**. 

I think cytosol is correct; isn't it ? 
@dosumis @cmungall @ukemi @thomaspd

**Comment by pgaudet** [comment]
This came up while working on #14711

**Comment by cmungall** [comment]
Yes, use cytosol here

**Comment by dosumis** [comment]
Cytoplasm is broader.  Could cover starting point inside some other organelle.

**Comment by pgaudet** [comment]
thanks
