### ISSUE TITLE
TPV 	cleavage furrow

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14737]
cleavage furrow  has the parent
GO:0097610 - cell surface furrow
and cell surface,

however 
The cleavage furrow is a plasma membrane invagination at the cell division site. 
So it is really a specific organization of the plasma mambrane?

cell surface is defined
The external part of the cell wall and/or plasma membrane.

**Comment by vanaukenk** [comment]
@ValWood - I think you're right.
I'll update the parentage of GO:0032154 'cleavage furrow' to be an is_a child of GO:0098590 'plasma membrane region'.
I'll also update the definition of GO:0097610 'cell surface furrow' to no longer refer to 'cleavage furrow' as an example.
