### ISSUE TITLE
NTR: regulation terms for adenylate cyclase-activating adrenergic receptor signaling pathway

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#14733]
Hello,

Could I request all the regulation terms for GO:0071880 "adenylate cyclase-activating adrenergic receptor signaling pathway"?

For annotation of miR-133a from PMID:24807785.

If accepted, please add the following GO REFs:
GOC:rph
GOC:BHF_miRNA
GOC:BHF

Thanks,
Rachael.

**Comment by pgaudet** [comment]
Hi @rachhuntley 

Is there a adenylate cyclase-inhibiting type of adrenergic receptor signaling ? 

If this does not exist, we should probably rename 'regulation of adrenergic receptor signaling pathway' and its negative and positive children. 

Thanks, Pascale

**Comment by rachhuntley** [comment]
Yes, there is https://www.ebi.ac.uk/QuickGO/term/GO:0071881

**Comment by pgaudet** [comment]
OK thanks - but then we should probably be more specific and do 
- "regulation of adenylate cyclase-activating adrenergic receptor signaling pathway"
and 
- "regulation adenylate cyclase-inhibiting adrenergic receptor signaling pathway"?

and remove the general class 'regulation of adrenergic receptor signaling pathway' - as the type of pathway being regulated should be know. 

What do you think ? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
I'm copying in @RLovering as 'regulation of adrenergic receptor signaling pathway' is a BHF-UCL requested term and there are two annotations directly to it, one of which is Ruth's. The other annotation I will update to the more specific term requested here.

I agree with adding the regulation terms for the adenylate cyclase-inhibiting term.

Thanks,
Rachael.

**Comment by RLovering** [comment]
There are 11 manual annotations to the term, regulation of adrenergic receptor signaling pathway and child terms.

I can see some are probably not popular: negative regulation of adrenergic receptor signaling pathway involved in heart process

but I would like to know what is going to happen to these terms, and to be honest reviewing 11 annotations is not a 5 min job. I have done a lot of revisions recently and I need to do other things for a while before looking at this

Ruth

**Comment by rachhuntley** [comment]
We are only talking about annotations directly to that term. Yours is on P41220. You should be able to update it to either 
    "regulation of adenylate cyclase-activating adrenergic receptor signaling pathway"
    or
    "regulation adenylate cyclase-inhibiting adrenergic receptor signaling pathway"?

Pascale is only proposing to remove the general parent regulation of adrenergic receptor signaling pathway.

**Comment by RLovering** [comment]
ok sounds good to me ;)

**Comment by pgaudet** [comment]
Hello again @rachhuntley @RLovering 
In fact there are 7 EXP annotations to the children of     GO:0071877 regulation of adrenergic receptor signaling pathway. 

**Current existing terms:** 
'regulation of adrenergic receptor signaling pathway'
'negative regulation of adrenergic receptor signaling pathway'
'negative regulation of adrenergic receptor signaling pathway involved in heart process'
'negative regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
'negative regulation of beta1-adrenergic receptor activity'
'positive regulation of adrenergic receptor signaling pathway'
'positive regulation of adrenergic receptor signaling pathway involved in heart process'
'positive regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
'positive regulation of beta1-adrenergic receptor activity'
'regulation of adrenergic receptor signaling pathway involved in heart process'
'negative regulation of adrenergic receptor signaling pathway involved in heart process'
'negative regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
'positive regulation of adrenergic receptor signaling pathway involved in heart process'
'positive regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
'regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
'negative regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
'positive regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'


**What I would like to have, to avoid the multiplication of combinatorial terms, I propose that the children be only the most specific terms:  **
- 'regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
--'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
--'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'

-'regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
--'negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
--'positive regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'


and then if you need: 
'regulation of adrenergic receptor activating/inhibiting signaling pathway involved in positive regulation of heart rate'
and their positive and negative as required. 


I can put a 'DO NOT ANNOTATE' flag on the existing terms, create the new terms, give you some time to move the annotations, and then obsolete the existing terms; would that work?  

I also need to know about the regulation of heart rate: is it mediated by an adenylate cyclase-activating adrenergic signaling, ACA inhibiting, or both? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
I think this is fine, except that I'm not sure we should have the regulation of regulation terms (i.e. regulation of adrenergic receptor activating/inhibiting signaling pathway involved in positive regulation of heart rate).
Instead, I would be in favour of having "regulation of adenylate cyclase-activating/inhibiting adrenergic receptor signaling pathway involved in heart process" (and the positive and negative) as one of the annotations that needs to be re-homed is involved in cardiac muscle cell contraction rather than a specific effect on heart rate.

As for your question about regulation of heart rate (or heart process), I would think that both activating and inhibiting adrenergic signaling would regulate because both are affecting the level of cAMP, which mediates the physiological responses of the heart.

@RLovering, any other thoughts?

Rachael.

**Comment by pgaudet** [comment]
Hi @RLovering 
Can you please check whether for the 7 EXP annotations to ' GO:0071877 regulation of adrenergic receptor signaling pathway', can you check whether they are looking at ACA-activating or ACA-inhibiting adrenergic receptor signaling pathway? 

Thanks, Pascale

**Comment by RLovering** [comment]
There are now only 2 EXP direct annotations to 1. PMID: 21291891 inhibitory: key statements: Furthermore, RGS2 ablation, similar to βAR agonist stimulation, sustains the β(2)AR-G(i) signaling in cultured cells, whereas adenoviral overexpression of RGS2 suppresses agonist-activated β(2)AR-G(i) signaling in cardiomyocytes and HEK293 cells. These findings not only define RGS2 as a novel negative regulator of the β(2)AR-G(i) signaling but also provide a potential novel target for the treatment of chronic heart failure.

Therefore actually the best term would be negative regulation of GO:0086096    adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process
or negative regulation of GO:0007193 adenylate cyclase-inhibiting G-protein coupled receptor signaling pathway

Are you planning to create these terms?

The other paper was annotated by Rachael: PMID:24807785
The paper above (1: PMID: 21291891) states: Two major β-adrenergic receptor (βAR) subtypes, β(1)AR and β(2)AR, are expressed in mammalian heart with β(1)AR coupling to G(s) and β(2)AR dually coupling to G(s) and G(i) proteins. The expts in PMID:24807785 discuss miR regulation of selective β1AR stimulation. I would therefore suggest that in the second paper it is ACA activating.

Rachael please confirm @rachhuntley

**Comment by rachhuntley** [comment]
I think we need to look at the annotations to the child terms as well, I can do this on Monday.
Yes, PMID:24807785 needs an activating term.

Ruth, in your paper, the statement "overexpression of RGS2 suppresses agonist-activated β(2)AR-G(i) signaling" suggests to me the GO term should be 'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway', i.e. RGS2 is suppressing the activation of β(2)AR? I have looked at the paper yet though.

**Comment by pgaudet** [comment]
Hi @rachhuntley @RLovering 
Can you also look at 
http://amigo.geneontology.org/amigo/term/GO:0086024
The term is under ACA-activating; is this right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Here's the plan: 
REGULATION

1)	OBSOLETE: 
'regulation of adrenergic receptor signaling pathway involved in heart process'
REPLACE BY 
'regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
'regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'


2)	OBSOLETE: 
'negative regulation of adrenergic receptor signaling pathway involved in heart process'
REPLACE BY 
'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
'negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'


3)	OBSOLETE: 
'positive regulation of adrenergic receptor signaling pathway involved in heart process'
REPLACE BY 
'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
'positive regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'



4)	OBSOLETE 'regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
OBSOLETE 'negative regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
OBSOLETE 'positive regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
⎝	No replacement


PATHWAY
5)	GO:0086096 adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process
Move under GO:0071881 adenylate cyclase-inhibiting adrenergic receptor signaling pathway
6)	GO:0086024 adrenergic receptor signaling pathway involved in positive regulation of heart rate
7)	OBSOLETE
GO:0086024 adrenergic receptor signaling pathway involved in positive regulation of heart rate
GO:0086023 adrenergic receptor signaling pathway involved in heart process


OK ?

**Comment by pgaudet** [comment]
Here are what the changes look like: 

BEFORE - pathway
![image](https://user-images.githubusercontent.com/4782928/36277620-aeee5520-1291-11e8-9059-f416be14991f.png)


	regulation
![image](https://user-images.githubusercontent.com/4782928/36277623-b1926bae-1291-11e8-81ba-ffb9cc955424.png)



----
AFTER - pathway
 
![image](https://user-images.githubusercontent.com/4782928/36277626-b3f617f6-1291-11e8-8b1b-b7e11b630216.png)

	regulation
![image](https://user-images.githubusercontent.com/4782928/36277634-b66d283a-1291-11e8-8347-d03d2a35d188.png)

**Comment by pgaudet** [comment]
I also renamed 
GO:0086030 adrenergic receptor signaling pathway involved in cardiac muscle relaxation
RENAMED adenylate cyclase-activating adrenergic receptor signaling pathway involved in cardiac muscle relaxation
This is consistent with the parents; hopefully it’s also consistent with the annotations

---
Still to do: 
5)	OBSOLETE
GO:0086024 adrenergic receptor signaling pathway involved in positive regulation of heart rate
(not yet done; just renamed ‘adenylate cyclase-activating adrenergic receptor signaling pathway involved in positive regulation of heart rate’) 

Thanks, Pascale

**Comment by rachhuntley** [comment]
Hi Pascale, 

Thanks for this, however the regulation terms you added aren't totally consistent with your original proposal, specifically, for the 'activating' terms you have 'G-protein coupled receptor signaling pathway', but for the inhibiting terms you have 'adrenergic receptor signaling pathway' - is there a reason for this?

Your original proposal:
    'regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
    --'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
    --'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'

-'regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
--'negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
--'positive regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'

I will look at the other questions today. QuickGO is down at the moment and AmiGO just confuses me!

**Comment by rachhuntley** [comment]
With regards to the annotations to GO:0086030 adrenergic receptor signaling pathway involved in cardiac muscle relaxation, there is only one experimental annotation from PMID:22459152 and this looks like it is activating: "<a specific inhibitor of adenylate cyclase> abolished the inotropic and lusitropic effects of both serpinin (Supplemental Fig. S1) and pGlu-serpinin (Fig. 4).". So I think your renaming works for this annotation.

**Comment by rachhuntley** [comment]
>>http://amigo.geneontology.org/amigo/term/GO:0086024
The term is under ACA-activating; is this right ?

Yes, this term refers to activation of an intracellular Gs protein. Gs activates adenylate cyclase.

**Comment by RLovering** [comment]
Hi 
I hadn't realised all the different edits you were doing. So have gone to QuickGO to check regulation terms:
 P23634 ATP2B4 replace annotation with negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process
Q9Z0J4 Nos1 replace annotation with positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process

If we have missed any I guess these will come up in error reports

Ruth

**Comment by RLovering** [comment]
Hi Pascale

would it be possible to add the aliases (i) stands for inhibiting and (s) is stimulatory to the G protein ontology somewhere?

Thanks

Ruth

**Comment by rachhuntley** [comment]
I've looked at all seven annotations and these are the updates I think we should do (fortunately I got the same for the two Ruth suggested above!). One of them is from MGI and I think they are wrong to have positive regulation (see below).

PMID:20395454
abeta-42_human Update 'positive regulation of adrenergic receptor signaling pathway' to 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'

PMID:12529373
ADRA2A Update 'negative regulation of adrenergic receptor signaling pathway' to 'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
(α2AAR suppresses the signaling by β1AR "coexpression with α2AAR results in reduced β1AR affinity for isoproterenol and other βAR-selective ligands” "Our findings reveal that β1AR and α2AAR robustly associate in cells and that α2AAR can regulate β1AR internalization and ligand binding.”)

PMID:17242280
ATP2B4 Update 'negative regulation of adrenergic receptor signaling pathway involved in heart process' to 'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'

PMID:20516643
Gsk3a Update 'positive regulation of adrenergic receptor signaling pathway' to 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'

PMID:21291891
Rgs2 Update 'regulation of adrenergic receptor signaling pathway' to 'negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'

PMID:17242280
Nos1 Update 'positive regulation of adrenergic receptor signaling pathway involved in heart process' to 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'

PMID:21982743 (MGI)
Arrdc3 Update 'positive regulation of adrenergic receptor signaling pathway' to 'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
("loss of ARRDC3 increased the response to β-adrenergic stimulation” "suggesting the hypothesis that loss of ARRDC3 leads to enhanced energy expenditure through increased intracellular β-adrenergic signaling.")

**Comment by pgaudet** [comment]
Hi @rachhuntley 
This is what I actually did: I think the terms containing G-proteins are parents. 

REGULATION

1)	
**OBSOLETE:** 
' GO:1901204 regulation of adrenergic receptor signaling pathway involved in heart process'
**REPLACE BY** 
' GO_0140192 regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
'biological regulation'  and regulates some 'adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'

' GO_0140193 regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'


2)	
**OBSOLETE:** 
' GO:1901205 negative regulation of adrenergic receptor signaling pathway involved in heart process'
**REPLACE BY** 
'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
' GO_0140194  negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'


3)	
**OBSOLETE:** 
' GO:1901206 positive regulation of adrenergic receptor signaling pathway involved in heart process'
**REPLACE BY** 
'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
' GO_0140195  positive regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process'

4)	
**OBSOLETE '** GO:1903245 regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
**OBSOLETE** 'GO:1903246 negative regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
OBSOLETE 'GO:1903247 positive regulation of adrenergic receptor signaling pathway involved in positive regulation of heart rate'
**No replacement**

5)	**RENAME** ‘GO:0071877 regulation of adrenergic receptor signaling pathway’ -> 
regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway (single annotation to an inhibiting protein (MGI:1098271)
6)	**RENAME** ‘GO:0071878  negative regulation of adrenergic receptor signaling pathway -> negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway (single annotation to an activating protein

**PATHWAY**
7)	GO:0086096 adenylate cyclase-inhibiting adrenergic receptor signaling pathway involved in heart process
**Move under** GO:0071881 adenylate cyclase-inhibiting adrenergic receptor signaling pathway
8)  GO:0086023 adrenergic receptor signaling pathway involved in heart process
**rename** adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process

**Comment by pgaudet** [comment]
Hi @RLovering 
Where do you want the  (i) and (s) synonyms? These refer to the Galpha subunits, so I dont know where to put it in terms such as 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process' . 

Thanks, Pascale

**Comment by rachhuntley** [comment]
So Pascale,

Do you also have the following terms as parents to the 'involved in heart process' terms?
'regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
--'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
--'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'

-'regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
--'negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
--'positive regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'

(I'm not sure how the G-protein terms fit in with these)

<<Can I go ahead with the obsoletion of 'GO:0086024 adrenergic receptor signaling pathway involved in positive regulation of heart rate’?

So, if we wanted terms referring to the regulation of the heart rate, we would request something like e.g. 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart rate' as a child of 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'?

**Comment by pgaudet** [comment]
> Do you also have the following terms as parents to the 'involved in heart process' terms?
'regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
YES GO_0140192 
--'negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
YES GO:0140199
--'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'
YES GO:0140196

-'regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
YES GO:0140193
--'negative regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
GO:0140194
--'positive regulation of adenylate cyclase-inhibiting adrenergic receptor signaling pathway'
YES GO:0140195

----

> <<Can

 I go ahead with the obsoletion of 'GO:0086024 adrenergic receptor signaling pathway involved in positive regulation of heart rate’?

> So, if we wanted terms referring to the regulation of the heart rate, we would request something like e.g. 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart rate' as a child of 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process'
Yes

**Comment by pgaudet** [comment]
Hi @rachhuntley 
Sorry about the late reply ! In fact according to your notes above, GO:0071879 should have been renamed to 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'. 

> PMID:20395454
abeta-42_human Update 'positive regulation of adrenergic receptor signaling pathway' to 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway'

> PMID:20516643
Gsk3a Update 'positive regulation of adrenergic receptor signaling pathway' to 'positive regulation of adenylate cyclase-activating adrenergic receptor signaling pathway' 

Now fixed. Thanks, Pascale
