### ISSUE TITLE
MP 	various missing mitochondrial  transmembrane transport parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14739]
mitochondrial iron ion transmembrane transport

has no parent to "mitochondrial transmembrane transport"

**Comment by ValWood** [comment]
mitochondrial tricarboxylic acid transmembrane transport

**Comment by ValWood** [comment]
and
GO:1990547 | mitochondrial phosphate ion transmembrane transport
-- | --

**Comment by ValWood** [comment]
and 

GO:1990540 | mitochondrial manganese ion transmembrane transport

**Comment by ValWood** [comment]
also these are missing "mitochondrial transport" parentage

mitochondrial ADP transmembrane transport
mitochondrial ATP transmembrane transport
mitochondrial iron ion transmembrane transport
mitochondrial tricarboxylic acid transmembrane transport

**Comment by pgaudet** [comment]
in fact they were all missing ! I now fixed the logical definition. 

Thanks, Pascale
