### ISSUE TITLE
NTR: mitochondrial guanine nucleotide transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14740]
child of
GO:1903790    guanine nucleotide transmembrane transport

standard def

PMID:25320081

**Comment by pgaudet** [comment]
It's there ! GO:0140140
https://github.com/geneontology/go-ontology/issues/14619

**Comment by ValWood** [comment]
missing parent?
https://www.ebi.ac.uk/QuickGO/term/GO:1903790

**Comment by pgaudet** [comment]
Hi @ValWood 
You mean it's missing the parent GO:1903790 ? 

This should be solved with  #14739

Thanks, Pascale

**Comment by ValWood** [comment]
yep!
