### ISSUE TITLE
MP protein import into nucleus (LOST)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14748]
"protein import into nucleus" has lost the parent
"nucleocytoplasmic transport"

This causes a big drop in numbers to a grouping term and will affect slims and enrichemtns

**Comment by ValWood** [comment]
also
protein export from nucleus (GO:0006611

there is still something else missing to get the totals back.....

**Comment by ValWood** [comment]
and export

**Comment by pgaudet** [comment]
There was an inconsistency in the logical definitions 
- cytoplasm instead of cytosol
- nucleus instead of nuclear lumen. 

Thanks for picking that up!

Pascale
