### ISSUE TITLE
GO:1990391 DNA repair complex - add synonym

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14749]
Please add synonym:
WHY1 complex [NARROW]

dbxref: EBI-16426962

References (FYI):
PMID:24192350 (structure)
PMID:20551348 (DNA repair)
PMID:17217467 telomere maintenance)

I don't think it warrants a new child term.

Thanks, Birgit

**Comment by hdrabkin** [comment]
EBI-16426962 appears to be invalid id space. Is it EBI:??

**Comment by bmeldal** [comment]
Valid ID, complex being released as I type!

But: xref should be IntAct:EBI-16426962

Sorry.

**Comment by hdrabkin** [comment]
done
