### ISSUE TITLE
NTR zinc ion export from vacuole

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14755]
def
The directed movement of zinc ions from inside the vacuole, across the vacuolar membrane and into the cytosol.

synonym
vacuole to the cytosol copper ion transmembrane transport

parents
GO:0034486 vacuolar transmembrane transport
GO:0071577    zinc II ion transmembrane transport ?

Reference
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC203372/

**Comment by pgaudet** [comment]
Hi @ValWood 
About Zinc versus Zinc II - seems to me the phisiological form should be Zinc II - but do we really need to specify ? 
This is also quite inconsistent for all ions. 

@ukemi what do you suggest? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't think we need to specify unless there are multiple form (iron).....dual occurence could be merged and included as synonyms?

**Comment by pgaudet** [comment]
Iron, yes - zinc, are you sure it's always 2+ ?

**Comment by ValWood** [comment]
No, I haven't a clue.....

**Comment by ValWood** [comment]
this review says only 2 families of zinc transporter in metazoa
https://www.ncbi.nlm.nih.gov/pubmed/26084690

I think this is
http://www.ebi.ac.uk/interpro/entry/IPR002524
and
http://www.ebi.ac.uk/interpro/entry/IPR003689
and the same appears to apply to fission yeast.

So maybe if these are both for zinc 2+....
