### ISSUE TITLE
GO:0070688 (MLL5-L complex) retracted paper

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#14751]
Hello,
GO:0070688 (MLL5-L complex) is based on PMID:19377461 which has been retracted (PMID: 24336203). Although the annotation for the MLL5 human entry (Q8IZD2) has been removed, an ISS based annotation is still present for the mouse entry (Q3UG20). So far no other papers has been published to support the existence of this complex. Only the interaction with HCFC1 and OGT has been confirmed (PMID:23629655). I am not sure what is the best thing to do with this GO term.

Thank you

**Comment by ukemi** [comment]
The mouse annotation will update automatically. It seems like we should obsolete this term. @bmeldal would you agree?

**Comment by bmeldal** [comment]
It doesn't look like we have curated this complex yet and there's no entry in IntAct either. Happy to obsolete.

**Comment by ukemi** [comment]
The proposal has been made to obsolete GO:0070688 MLL5-L complex

The reason for obsoletion is that there is no evidence that this complex exists.

AmiGO2 shows there are no annotations to this term.
It is not used in other ontologies.


Details can be found here:
https://github.com/geneontology/go-ontology/issues/14751


We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete this term on Dec 27, 2017

*** Unless objections are received by Dec 27, 2017 , we will assume that
you
agree to this change. ***

Thanks,

David
