### ISSUE TITLE
Taxon restraint for GO:0005503 - all-trans retinal binding

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#14750]
Hi all,

Bit of a curious case here. I've got an archael rhodopsin protein (Nop-1) from a fungus that can bind all-trans retinal however we don't have a GO term for it that I can annotate to. Could we please remove the taxon restraint for GO:0005503 or at least consider an alternative to capture this? The evidence is pretty clear with regards to it binding specifically all-trans retinal and how it plays a functional role in the biology of this fungus. 

The paper supporting this is here: http://pubs.acs.org/doi/full/10.1021/bi9916170 or if you want the PMID:10571987.

Best,

George

**Comment by krchristie** [comment]
@ggeorghiou - I am slightly confused. Are you are calling a fungal Nop-1 an archael rhodopsin protein? Fungi are eukaryotes. The paper does describe the similarity between the the N. crassa Nop-1 protein and prokaryotic archaeal rhodopsins. 

In any case, the current taxon constraint, most easily seen in QuicGO: https://www.ebi.ac.uk/QuickGO/term/GO:0005503, is: '**only in taxon: Metazoa**' is too narrow for either fungi or Archaea.

This taxon constraint is coming from an ancestor term: 'retinoid binding' (GO:0005501).

A quick Google search suggests that retinoids are quite ancient: https://books.google.com/books?id=lTZPCAAAQBAJ&pg=PA84&lpg=PA84&dq=taxonomic+distribution+of+retinoids&source=bl&ots=m3fGi2q7UW&sig=57JzwsjT8B4AuTYezniT3cTtmB8&hl=en&sa=X&ved=0ahUKEwikv_SB1ILYAhVJxoMKHe-eBGAQ6AEIXzAH#v=onepage&q=taxonomic%20distribution%20of%20retinoids&f=false

Thus, I am inclined to just remove this taxon constraint without any replacement. Any objections @ukemi @cmungall ?

**Comment by ggeorghiou** [comment]
Apologies Karen, I'm cleaning up outstanding annotation issues in the GOA database and I inherited that paper. Was not thinking clearly when I wrote out the request. 

Removing the taxon constraint would be fine.
