### ISSUE TITLE
Ontology Engineering

### ISSUE THREAD

**Issue by jaugusti** [geneontology/go-ontology#14763]
Greetings,
I'm doing a Master's degree in Computer Science at UFSM (Universidade Federal de Santa Maria) and my research is about bioinformatics, more specifically cancer and ontologies. I am studying ontology engineering and would like to know what is the methodolody used for the construction, formalization and validation of Gene Ontology (like: Ontology Development 101 [NOY and MCGUINESS], On-to-Knowledge and METHONTOLOGY, etc). 

If you could suggest any source to ease my research. This is very important for me and for my work.

Thanks

**Comment by cmungall** [comment]
You can ask on the obo-discuss list, GO uses a lot of the same methodologies and approaches shared across OBO. obofoundry.org

See also

Mungall, C. J., Dietze, H., & Osumi-Sutherland, D. (2014). Use of OWL within the Gene Ontology. In M. Keet & V. Tamma (Eds.), Proceedings of the 11th International Workshop on OWL: Experiences and Directions (OWLED 2014) (pp. 25–36). Riva del Garda, Italy, October 17-18, 2014. http://doi.org/10.1101/010090
