### ISSUE TITLE
Taxon restraints on GO:0000921 and GO:0036214

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#14777]
Hi all,

I'm getting the following taxon restraint for the use of these two GO terms: 

GO:0000278 (mitotic cell cycle) and its descendants should ONLY be used with gene products from the taxonomic group Eukaryota. 

I'm trying to fix annotations from MTBBase and UniProt that have been annotated to septum ring assembly (UniProt IDs:Q55559, P9WI75, P9WN95, Q55900, and Q55901). I believe the annotations are correct based on the papers I've read (PMID:15130131 for Q55559, Q55900, and Q55901; PMID:11932443 for P9WN95; PMID:15866927 for P9WI75). Any chance this could be reivewed and the taxon restrain removed?

Best,

George

**Comment by cmungall** [comment]
possibly a dupe with #11676

**Comment by pgaudet** [comment]
@vanaukenk you can assign yourself #11676 as well (or assign me) - but they should be done together. 

Thanks, Pascale

**Comment by ValWood** [comment]
#11676  should not cause a problem for 

septin ring assembly
https://www.ebi.ac.uk/QuickGO/term/GO:0000921
it is not related to  mitotic cell cycle...this constraint should remain for eukaryote only
I'll take a quick look...

**Comment by ValWood** [comment]
Actually  #11676 will fix
 1 remove parent "mitotic citokinesis from
Barrier septum assembly

(is ticked but still exists. the parent just needs changing from mitotic cytokinesis to cytokinesis).

**Comment by vanaukenk** [comment]
@ggeorghiou 
I'm not seeing the taxon constraints for GO:0000921 and GO:0036214 in Protege or QuickGO.
Can you confirm?
Thx.

**Comment by ggeorghiou** [comment]
@vanaukenk they seem to have disappeared. I say we close this issue then?

**Comment by vanaukenk** [comment]
Will close this issue but re-visit #11676
