### ISSUE TITLE
move all ComplexPortal ACs into dbxref field

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14773]
This was discussed as part of another ticket but requires a systematic move of any CP ACs that are under definition xrefs to dbxref.

https://www.ebi.ac.uk/QuickGO/term/GO:0110001
is a good example of a term that ended up with both! The "protein complex" section I think comes from our GPAD as well.

I know the links are broken as they point to IntAct, not the CP, but that will be fixed with our new GPAD the fix of which depends on our new primary ACs which are getting closer to being in production!

**Comment by bmeldal** [comment]
Argh, looks like David did it yesterday but I didn't spot this ticket before I raised the other one this morning!
https://github.com/geneontology/go-ontology/pull/14768

I'll close this ticket once I can see the changes have been implemented.

**Comment by ukemi** [comment]
Hi @bmeldal,
Yup. I moved them yesterday. I think that @krchristie had cleaned up the others a while ago. She reminded me that the term xref was the right place for them. Let me know if you spot others.
