### ISSUE TITLE
Histone succinyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#14784]
Hello,

I would need a bunch of GO terms to cover histone succinyltransferase activity

Thanks

Sylvain

1)
GO:XXXXXXX peptide N-succinyltransferase activity

Catalysis of the acetylation of an amino acid residue of a peptide or protein, according to the reaction: succinyl-CoA + peptide = CoA + N-succinylpeptide. 

child of GO:0034212 peptide N-acetyltransferase activity

PMID:29211711

2)
GO:XXXXXXX peptide-lysine-N-succinyltransferase activity

Catalysis of the reaction: succinyl-CoA + lysine in peptide = CoA + N-succinyl-lysine-peptide. 

child of GO:XXXXXXX peptide N-succinyltransferase activity

PMID:29211711

2)
GO:XXXXXXX histone succinyltransferase activity

Catalysis of the reaction: succinyl-CoA + histone = CoA + succinyl-histone. 

child of GO:XXXXXXX protein succinyltransferase activity

PMID:29211711

3)
GO:XXXXXXX histone succinylation

The modification of a histone by the addition of an succinyl group. 

child of GO:0018335 protein succinylation

PMID:29211711

**Comment by hdrabkin** [comment]
Assume you meant for this one
GO:XXXXXXX histone succinyltransferase activity

Catalysis of the reaction: succinyl-CoA + histone = CoA + succinyl-histone.

child of GO:XXXXXXX protein succinyltransferase activity <<<<<<,  peptide N-succinyltransferase activity

**Comment by hdrabkin** [comment]
Done
[Term]
+id: GO:0106075
+name: peptide N-succinyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the acetylation of an amino acid residue of a peptide or protein, according to the reaction: succinyl-CoA + peptide = CoA + N-succinylpeptide." [PMID:29211711]
+is_a: GO:0034212 ! peptide N-acetyltransferase activity
+created_by: hjd
+creation_date: 2017-12-15T18:23:58Z
+
+[Term]
+id: GO:0106076
+name: peptide-lysine-N-succinyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: succinyl-CoA + lysine in peptide = CoA + N-succinyl-lysine-peptide." [PMID:29211711]
+is_a: GO:0106075 ! peptide N-succinyltransferase activity
+created_by: hjd
+creation_date: 2017-12-15T18:25:16Z
+
+[Term]
+id: GO:0106077
+name: histone succinylation
+namespace: biological_process
+def: "The modification of a histone by the addition of an succinyl group." [PMID:29211711]
+is_a: GO:0018335 ! protein succinylation
+created_by: hjd
+creation_date: 2017-12-15T18:27:16Z
+
+[Term]
+id: GO:0106078
+name: histone succinyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: succinyl-CoA + histone = CoA + succinyl-histone." [PMID:29211711]
+is_a: GO:0106075 ! peptide N-succinyltransferase activity
+created_by: hjd
+creation_date: 2017-12-15T18:29:40Z
+
