### ISSUE TITLE
Fix GO terms wrongly referring to EC 6.2.1.3

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#14783]
EC 6.2.1.3 = Long-chain-fatty-acid--CoA ligase. 

Looking at occurences of this in GO terms in the current GO-basic obo file:

One is correct:
- GO:0004467 (long-chain fatty acid-CoA ligase activity) has this EC# as an xref (and lists it in square brackets after the definition and many synonyms)

But I think these 6 are incorrect - please remove from xref/definition lines:
- GO:0102391 (decanoate--CoA ligase activity) has this EC# as an xref and in the definition

- GO:0015645 (fatty acid ligase activity) has it in the definition and synonyms (the given EC xref here is EC:6.2.1, which seems correct)

- GO:0003996 (acyl-CoA ligase activity) has it in the definition

- GO:0031955 (short-chain fatty acid-CoA ligase activity) has it in the definition

- GO:0031956 (medium-chain fatty acid-CoA ligase activity) has it in the definition

- GO:0031957 (very long-chain fatty acid-CoA ligase activity) has it in the definition

**Comment by hdrabkin** [comment]
Further investigation: EC only has EC id for long-chain
Metacyc uses EC 6.2.1.3 as xref for long,short, medium, etc.

**Comment by sjm41** [comment]
Thanks for looking further into this Harold.
So the name + comment of the EC term isn't really consistent with the name/defs of the GO terms...
Focussing on defs/comments in EC/GO, then EC:6.2.1.3 is equatable to GO terms for medium, long and very-long fatty acid-CoA ligase activity (GO:0031956, GO:0004467, GO:0031957).
In that case, EC 6.2.1.3 should pobably be added as an xref to GO:0031956 (medium-chain) and GO:0031957 (very long-chain) and remain as an xref to GO:0004467 (long-chain) and GO:0102391 (decanoate). Yes?

**Comment by sjm41** [comment]
Looks like there also needs to be some editing of defs and relationships in the GO in this area:

- Make GO:0102391 (decanoate--CoA ligase activity) a child of GO:0031956 (medium-chain fatty acid-CoA ligase activity)
- Replace "carboxylic acid" with "fatty acid" in defs of GO:0031955 & GO:0031956 & GO:0031957: 
- Replace "fatty acids" with "carboxylic acids" in def of GO:0003996.
- If current def of GO:0003996 (acyl-CoA ligase activity) is correct (restricted to long-chain carboxylic acids), then make GO:0004467 (long-chain fatty acid-CoA ligase activity) a child of it.  But if GO:0003996 is really meant to cover all length carboxylic acids, then the def should be changed and short/medium/long, very-long fatty acid-CoA ligase activity (GO:0031955, GO:0031956, GO:0004467 and GO:0031957) should all be children of it.

![screen shot 2017-12-22 at 10 14 24](https://user-images.githubusercontent.com/16306861/34294878-721475ae-e702-11e7-96b1-db9db75888f9.png)

**Comment by sjm41** [comment]
@hdrabkin  Almost all points in my previous post have been resolved, one way or another.  Only remaining thing to do is:

- [ ] Replace "carboxylic acid" with "fatty acid" in def of GO:0031956 

id: GO:0031956
name: medium-chain fatty acid-CoA ligase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + a medium-chain carboxylic acid + CoA = AMP + diphosphate + an acyl-CoA; a medium-chain fatty acid is any fatty acid with a chain length of between C6 and C12." [GOC:mah, RHEA:48340]
synonym: "medium-chain fatty acid activation" RELATED []
synonym: "medium-chain fatty-acid-CoA ligase activity" EXACT [GOC:bf]
synonym: "medium-chain-fatty-acid-CoA ligase activity" EXACT []
xref: EC:6.2.1.2
xref: RHEA:48340
