### ISSUE TITLE
Add cell to GO:0060122

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#14786]
This ticket is from 
 mind add a “cell” to the term name? à inner ear receptor cell stereocilium organization
 
inner ear receptor stereocilium organization
Definition:            A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a stereocilium. A stereocilium is an actin-based protrusion from the apical surface of inner ear receptor cells.
GO:0060122

**Comment by hdrabkin** [comment]
done.

**Comment by LiNiMGI** [comment]
Thanks
