### ISSUE TITLE
COPII vesicle coat (GO:0030127) parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14797]
One of two multimeric complexes that forms a membrane vesicle coat. COPII is best characterized in S. cerevisiae, where the subunits are called Sar1p, Sec13p, Sec31p, Sec23p, and Sec24p. Vesicles with COPII coats are found associated with endoplasmic reticulum (ER) membranes at steady state.

should this have ER  parent? (has Golgi apparatus part)?

**Comment by mah11** [comment]
If the vesicles shuttle between ER and Golgi, then it's a bit dodgy to say the coat is part_of either ER or Golgi because part_of means _always_ part of.

**Comment by ukemi** [comment]
I will remove the parent from the COPII vesicle.

**Comment by ukemi** [comment]
Seems to be coming from a bad assertion that a Golgi-associated vesicle is a Golgi part. Based on the def, this is not always true.
