### ISSUE TITLE
merge? difference, GO:0016972 thiol oxidase activity/GO:0003756  =protein disulfide isomerase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14792]
I can't see a difference:

GO:0016972 thiol oxidase activity
 4 R'C(R)SH + O2 = 2 R'C(R)S-S(R)CR' + 2 H2O.

GO:0003756  =protein disulfide isomerase activity
Catalysis of the rearrangement of both intrachain and interchain disulfide bonds in proteins.
protein thiol-disulfide exchange	exact

![diff](https://user-images.githubusercontent.com/7359272/34097938-aca7b0d8-e3d2-11e7-822a-7946e9d9b105.jpg)

**Comment by mah11** [comment]
GO:0016972 is very clearly not restricted to protein substrates.

They also have very different EC cross-references, although the information for GO:0003756/EC:5.3.4.1 is unsatisfyingly woolly. (GO:0003756 has_part GO:0016972 may possibyl be accurate ...?)

**Comment by ValWood** [comment]
Do "thiol oxidases" have substrates other than proteins?

GO:0016972 thiol oxidase activity has only 24 annotations and most of those appear to be

http://www.pantherdb.org/panther/family.do?clsAccession=PTHR22897
and
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR12645
 
which are both  protein-disulphide isomerase

**Comment by ukemi** [comment]
From the enzyme names, it would seem that the oxidase simply cleaves bonds, but the isomerase rearranges them?

**Comment by ValWood** [comment]
I wondered that, but since the isomerase has the parent "intra molecular oxidoreductase", I then assumed that    the reaction of the isomerase encompassed the reduction part?

**Comment by ukemi** [comment]
That makes sense to me too. I think that you would need to break the bond to rearrange it. Maybe a has_part?

**Comment by ValWood** [comment]
but an protein  isomerization isn't classed as 2 reactions is it?  Or  perhaps it is?

**Comment by ukemi** [comment]
No. That's probably why the two terms are distinct as terms and in placement.

**Comment by ValWood** [comment]
So maybe here I just need to make sure that all protein-disulphide isomerases have
GO:0016972 thiol oxidase activity
and can close this?

**Comment by krchristie** [comment]
@ValWood - It looks to me from reading the thread that this is not an ontology issue, so I'm going to close this. If I have missed something, just reopen it.

**Comment by ValWood** [comment]
pombase, for example
![inconsistent](https://user-images.githubusercontent.com/7359272/34224706-b22406a2-e5bb-11e7-9409-2cc92dea4800.jpg)

**Comment by ValWood** [comment]
I guess minimally, a comment on 
GO:0003756 =protein disulfide isomerase activity
that a concurrent annotation should also be made to
GO:0016972 thiol oxidase activity

would improve annotation consistency ?

That is provided that I interpreted  the comments in the ticket correctly.

**Comment by ValWood** [comment]
I'll close this. I'm not over-bothered about it and I guess Rhea will resolve issues like this.
v
