### ISSUE TITLE
decision on lipid translocases

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14793]
https://en.wikipedia.org/wiki/Flippase
https://www.pombase.org/term/GO:0034203
translocation is *currently* a type of =  transmembrane transport
lipid translocation
https://www.ebi.ac.uk/QuickGO/term/GO:0034204

The current def fits both
from
The process in which a solute is transported across a lipid bilayer, from one side of a membrane to the other.

but I think it could be clearer.

This includes transport *through* the bilayer, or from one side of the bilayer to the other.

Translocation would need to move under "transmembrane transport"

**Comment by pgaudet** [comment]
References
PMID: 18439418

**Comment by ValWood** [comment]
GO:0004012 - phospholipid-translocating ATPase activity
 GO:0017128 - phospholipid scramblase activity (which appears to be an ATP independent translocating activity)

phosphatidic acid transporter activity- This one is defined like a TM transporter, but it is only used for translocation so far as I can see

Looking at this
![translocation](https://user-images.githubusercontent.com/7359272/34715802-bf55936c-f525-11e7-8fda-261467e92760.jpg)

It seems that we need a term 
"lipid translocating activity"
to group these? (glycolipid, phospholipid etc)

**Comment by pgaudet** [comment]
Carried over from #14492


GO ID  - Label | Annotations | Action
-- | -- | --
GO:1902388 ceramide   1-phosphate transporter activity | NOT   TM  - intramembrane | **Transfer**
GO:0035620 ceramide transporter   activity | **Must review annotations - mix   transporter/carrier 8 EXP** | No action yet
GO:0017127 cholesterol transporter   activity | **Must review annotations - mix transporter/carrier 22 EXP** | No action yet
GO:0017089 glycolipid transporter   activity | more chaperone | ? |  
GO:0034202 glycolipid-translocating   activity | 3 NOT; 1 EXP | **Flippases**
GO:0034437 glycoprotein transporter   activity | 2 EXP annotations: one indirect,   one possibly endocytosis | ? |  
GO:0015648 lipid-linked peptidoglycan   transporter activity | 3 EXP annotations to 2 proteins,   flippases | *Move to some flippase term*
GO:0005319 lipid transporter activity |   |   |  
GO:0042954 lipoprotein transporter   activity | rather **cargo** |   |  
GO:0005324 long-chain fatty acid   transporter activity |   |   |  
GO:0008525 phosphatidylcholine   transporter activity | Mix transport - flippase | **To review**
GO:1904121 phosphatidylethanolamine   transporter activity | Mix transport - flippase | **To review**
GO:0008526 phosphatidylinositol   transporter activity | all **transfer** |   |  
GO:0005548 phospholipid transporter   activity |   |   |  
GO:0008565 protein transporter   activity |   | **To review** for ex importins, karyopherins   are annotated
GO:0046624 sphingolipid transporter   activity | Mix transport - flippase | **To review**
GO:0015248 sterol transporter   activity | Many TM, but others such as P22059   (chaperone?) |

**Comment by pgaudet** [comment]
@ValWood 
We now have moved flippases under 'intramembrane transporter activity' - does that work for you ?

**Comment by pgaudet** [comment]
> It seems that we need a term
"lipid translocating activity"
to group these? (glycolipid, phospholipid)

Done

**Comment by pgaudet** [comment]
Looking at this with @marcfeuermann 
we propose to add 'flippase' (movement of lipids from the cytosolic to the exoplasmic leaftlet of a membrane) and 'floppase' (movement of lipids from the exoplasmic to the cytosolic of a membrane)

(and move existing terms as children as appropriate, dependent on the direction of the lipid movement). 

Would that be OK ? Why are these terms not in GO ? 
@ukemi @ValWood do you know? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Proposed new terms: 
+[Term]
+id: GO:0140326
+name: ATPase-coupled intramembrane lipid transporter activity
+namespace: molecular_function
+synonym: "Catalysis of the movement of lipids from one membrane leaflet to the other (lipid flippase activity)." EXACT [PMID:16828084]
+is_a: GO:0140303 ! intramembrane lipid transporter activity
+created_by: pg
+creation_date: 2019-04-29T12:42:26Z
+
+[Term]
+id: GO:0140327
+name: flippase activity
+namespace: molecular_function
+def: "Catalysis of the movement of lipids from the exoplasmic to the cytosolic leaftlet of a membrane, using energy from ATP hydrolysis to pump the lipid." [PMID:20043909, PMID:25284293, Wikipedia:Flippase]
+is_a: GO:0140326 ! ATPase-coupled intramembrane lipid transporter activity
+created_by: pg
+creation_date: 2019-04-29T12:51:21Z
+
+[Term]
+id: GO:0140328
+name: floppase activity
+namespace: molecular_function
+def: "Catalysis of the movement of lipids from the cytosolic to the exoplasmic leaftlet of a membrane, using energy from ATP hydrolysis to pump the lipid." []
+is_a: GO:0140326 ! ATPase-coupled intramembrane lipid transporter activity
+created_by: pg
+creation_date: 2019-04-29T12:58:53Z
https://github.com/geneontology/go-ontology/pull/17201

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/17201

**Comment by pgaudet** [comment]
New structure: 

'intermembrane lipid transfer activity'
'intramembrane lipid transporter activity'
- 'ATPase-coupled intramembrane lipid transporter activity'
-- 'ATPase-coupled intramembrane glycolipid transporter activity'
-- 'ATPase-coupled intramembrane lipopolysaccharide transporter activity'
-- 'ATPase-coupled phospholipid transporter activity'
--- 'ATPase-coupled ceramide transporter activity'
---'ATPase-coupled phosphatidylcholine transporter activity'
---'ATPase-coupled phosphatidylethanolamine transporter activity'
---'ATPase-coupled phosphatidylserine transporter activity'
--'flippase activity'
--'floppase activity'
- 'phospholipid scramblase activity'

**Comment by ValWood** [comment]
I'm a bit confused about the changes.

Currently
GO:0034202   glycolipid-translocating activity broad "flippase activity"


GO:0090555    phosphatidylethanolamine-translocating ATPase activity
phosphatidylethanolamine flippase activity | exact

and others...

This ticket is quite confusing anyway though because it dates from the days when "translocation" was merged with "transmembrane transport"

**Comment by ValWood** [comment]
Looks like you probably dealt with all this
https://github.com/geneontology/go-ontology/issues/17186
so reclosing.

Will open new current tickets if I spot any outstanding issues.

**Comment by pgaudet** [comment]
I apologize about the confusion. 

Note that I have removed all flippases activities for floppases. We can create flippases as we find examples. 

Thanks, 
Pascale

**Comment by ValWood** [comment]
I don't understand how you decided flippase or floppase 

https://www.yeastgenome.org/locus/YMR162C#go
for example, is flippase

**Comment by ValWood** [comment]
and
https://www.yeastgenome.org/locus/YIL048W

but for some i dont think we know...

**Comment by pgaudet** [comment]
Hi @ValWood 
Welcome back ! 

We looked at this closely with @marcfeuermann and put some comments to help clarify: 
 - flippase activity= from the exoplasmic to the cytosolic leaftlet of a membrane
 - floppase activity= from the cytosolic to the exoplasmic leaftlet of a membrane

However people are quite sloppy with the nomenclature. Most enzymes we looked at are actually floppases, but are called flippases in papers. 

We put this comment: 
"Nomenclature note. Flippases and floppases are ATP-dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature, they catalyze lipid transfer towards the inward monolayer (flippases) or towards the outward monolayer (floppases). Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements. Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane (PMID 20043909)."

With @marcfeuermann we figured that if the paper doesn't test whether an enzyme flips or flops, then no MF can be assigned. 

OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK.
I will review  ours https://github.com/pombase/curation/issues/2373, there are not many, and let you know if  anything is awry.

**Comment by deustp01** [comment]
To help curators and users deal with variable usage by authors, maybe add something to indicate direction to the term names themselves:
"flippase (inward translocation) activity"
"floppase (outward translocation) activity"

**Comment by pgaudet** [comment]
GO:0015248 sterol transporter activity >> have been re-annotated except for WB:WBGene00003071 and CGD:CAL0129966. 
- WB:WBGene00003071  should be re-annotated to "GO:0030228 - lipoprotein particle receptor activity"
- CGD:CAL0129966 seems to really be a transmembrane transporter, that associated with an enzyme to produce a sterol ester (which is presumably more soluble and can get across the membrane?) 
So, I will change the label of GO:0015248 sterol transporter activity to sterol **transmembrane** transporter activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0015248 sterol transporter activity'. The reason for obsoletion is that this term is an unnecessary grouping term; transporter activity should specific the mechanism. Please consider: GO:0034041 ABC-type sterol transporter activity, GO:0120015 sterol transfer activity and GO:0030228 - lipoprotein particle receptor activity. 

There are 2 annotations to this term, see https://github.com/geneontology/go-annotation/issues/2365. There is one RHEA mapping (RHEA:39747) that will be moved as narrow match to GO:0034041 ABC-type sterol transporter activity.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/14793

Thanks, Pascale

**Comment by pgaudet** [comment]
Also added RHEA xref on [sterol transfer activity](http://purl.obolibrary.org/obo/GO_0120015) since RHEA also mentions NPC1L, that catalyzes intermembrane sterol transfer.

**Comment by pgaudet** [comment]
Changed label: GO:0005324
-name: long-chain fatty acid transporter activity
+name: long-chain fatty acid transmembrane transporter activity


to match definition.

**Comment by deustp01** [comment]
Reactome annotations (not listed above) have been fixed - corrected annotations will become public in June 2024 release.

**Comment by pgaudet** [comment]
Removed RHEA:39747 from [sterol transfer activity](http://purl.obolibrary.org/obo/GO_0120015) since RHEA describes transmembrane transport and GO_0120015 intermembrane transport

**Comment by deustp01** [comment]
> RHEA describes transmembrane transport and GO_0120015 intermembrane transport

I tripped over this too. What is an acceptable term for sterol transmembrane transport? I didn't see one.

**Comment by pgaudet** [comment]
I think the ABC transporter esterifies the sterol and transports it across the membrane. Is this how you also understand the mechanism?

**Comment by deustp01** [comment]
> I think the ABC transporter esterifies the sterol and transports it across the membrane. Is this how you also understand the mechanism?

No. [RHEA:39747](https://www.rhea-db.org/rhea/39747) is simply cholesterol(in) = cholesterol(out), no esterification. Similarly, Reactome [R-HSA-265443 "NPC1L1-mediated cholesterol uptake"](https://reactome.org/content/detail/R-HSA-265443) is simply the movement of cholesterol with no involvement of ATP, so I don't think it fits the description of ABC transport.

**Comment by deustp01** [comment]
[NPC1L1 (UniProt Q9UHC9)](https://www.uniprot.org/uniprotkb/Q9UHC9/entry) is not an ABC transporter, so no.

**Comment by pgaudet** [comment]
Ha, right, this should be annotated to GO:0120015 - sterol transfer activity

**Comment by deustp01** [comment]
> GO:0120015 - sterol transfer activity

Or for the more specific reactions in RHEA and Reactome, its is_a child [GO:0120020 cholesterol transfer activity](https://www.ebi.ac.uk/QuickGO/term/GO:0120020). 

I'll fix the Reactome NPC1L1 annotation accordingly for now, but I think it's still not right, because [sterol or cholesterol] transfer activity is "Removes [sterol or cholesterol] from a membrane or a monolayer lipid particle, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to an acceptor membrane or lipid particle." while RHEA and Reactome rreactions are describing its movement across one lipid bilayer membrane, no trip through an aqueous phase to move from one lipid environment to a distant one.
