### ISSUE TITLE
GO:0110001 toxin-antitoxin complex, definition

### ISSUE THREAD

**Issue by JoannaArgasinska** [geneontology/go-ontology#14795]
the definition states: " bacterial protein complex". However, the antitoxin can be an RNA as well. Can you include this information as well?  An sRNA antitoxin review paper: PMID: 25093388 
Thank you 
Joanna

**Comment by hdrabkin** [comment]
Modified def to
A bacterial protein complex that neutralises its own toxin by complexing the toxin with the antitoxin. The toxin can be either a protein or an RNA. The neutralising toxin-antitoxin complex also acts as a transcriptional repressor of the toxin-antitoxin operon.
Added PMID as a reference.

**Comment by AntonPetrov** [comment]
@hdrabkin Thank you for looking into this and updating the definition. However, I don't think it covers the case where the **antitoxin is an RNA**.

For example, here is an extract from a recent review:
**sRNA antitoxins: more than one way to repress a toxin**:
https://www.ncbi.nlm.nih.gov/pubmed/?term=25093388

> the antitoxin can be an RNA as well. For type I and type III loci, the **antitoxins are RNAs**. Type I antitoxins repress toxin protein expression through interacting with the toxin mRNA, thereby targeting the mRNA for degradation or preventing its translation or both; **type III antitoxins directly bind to the toxin protein**, sequestering it.

Would it make sense to change the following sentence?

> The *anti*toxin can be either a protein or an RNA. 

Feel free to let me know if you need more information.

**Comment by hdrabkin** [comment]
Nuts; I meant to say 'antitoxin' as I was going from that review; I will fix it today.

**Comment by AntonPetrov** [comment]
Thank you very much, this is very helpful for our work on [Rfam](http://rfam.org)!
