### ISSUE TITLE
Makefile doesn't find object properties when seeding import modules

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#14804]
There are a few RO terms used in go-plus which aren't in ro_import (e.g. 'bearer of'). This is easily missed because some RO axioms are duplicated in go-edit.

The makefile creates a seed file for module extraction by dumping the term IRIs referenced in the ontology:

https://github.com/geneontology/go-ontology/blob/7f5f14e021e9e3ef704acadf23e0a7f840f8996d/src/ontology/Makefile#L245-L246

The owltools command used to extract the terms referenced in the ontology seems to leave out object properties:

https://github.com/owlcollab/owltools/blob/178e1f994aa4a5e9e4d43c7a5243145436c553a8/OWLTools-Core/src/main/java/owltools/io/TableRenderer.java#L44-L45

Either owltools should be fixed, or the makefile should use a robot SPARQL query (or both).

**Comment by cmungall** [comment]
+1 to robot sparql. I think this part of the Makefile predates that possibility

**Comment by balhoff** [comment]
I’ve got this done, will be submitting a PR.
