### ISSUE TITLE
autophagy question (autophagy group)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14800]
Can we call

phosphatidylinositol 3-kinase complex, class III, type I ( Google 233 results, all GO?)

autophagy-specific phosphatidylinositol 3-kinase (PtdIns3K) complex  (Google About 1,790 results) 

would make it easier for users (and curators).

**Comment by ValWood** [comment]
Do we have a term for the Atg18-Atg2 complex ?  (one of the 6 functional groups that is part of autophagosome assembly?)
The others appear to be present.

**Comment by ukemi** [comment]
@bmeldal ?

**Comment by ValWood** [comment]
Why have mitophagy with exact synonym macromitophagy?
and “autophagy of mitochondrion” with related synonym “mitophagy”

Why not
mitophagy  (exact = “autophagy of mitochondrion”)
with children
—macromitophagy 
—micromitophagy

would be much, much clearer

ditto pexophagy

**Comment by ukemi** [comment]
I would be very concerned to change the names of the terms because these names and the organization resulted from a great deal of discussion and feedback with experts in the field. I could add a synonym to the complex, but it looks like the primary name is the one that is its official name.

**Comment by RLovering** [comment]
I think that the experts stated that micromitophagy is not a type of mitophagy

**Comment by ValWood** [comment]
OK I see now but it took a bit of figuring out because you would expect 
micromitophagy  too be a  type of mitophagy. The autophagy community do this "broadening" a lot in papers (phrases like Macroautophagy (herein autophagy)...the paper I was reading this week...not very helpful).

It would be helpful for curators to:
 
1. Define  mitophagy more explicity as "selective autophagy" , instead of just "macroautophagy" (which is a synonym anyway).  

2. Remove mitophagy  as a related synonym of  GO:0000422   autophagy of mitochondrion
 (since it is a child anyway, it would  correctly be narrow, but is not required and added to my confusion)

3. Add a comment  to  Micromitophagy:
Note that the autophagy community more commonly refers to 
"macromitophagy"  as "mitophagy", and therefore "micromitophagy" is not a type of mitophagy
then it would be immediately obvious why it is arranged this way.

and the same for pexophagy, if the same holds...

**Comment by ukemi** [comment]
The generalization that the community uses is the key here. In almost all cases, the general terms are used to refer to the macro process. As you say above, if you curate enough autophagy papers, you will soon realize that autophagy is used in place for macroautophagy pretty much all the time. This is the same for the subtypes. The majority of the time the macro distinction seems to be made only if there is a comparison to the micro.

As for the first request, phosphatidylinositol 3-kinase complex, class III, type I is the 'official' designation of the complex. If we renamed it with an autophagy-specific name, it would be misleading because although most of the time it functions in the context of autophagy, it is also used in other processes. I can add a synonym.

As I said above, I am very hesitant to change these terms and their definitions after the huge amount of discussion and expert input we have had about them.

**Comment by ValWood** [comment]
phosphatidylinositol 3-kinase complex, class III, type I 
is specific for autophagy isn't it?
so could this be an exact synoym?

2. above needs addressing, because currently it isn't correct.

I still think the terms will be difficult for curators so the comment  in 3. would be useful.

1. would also be *very* useful to curators because otherwise you need to figure out that "macrophagy" is selective autophagy. It isn't critical though.

**Comment by bmeldal** [comment]
Yes, we have it as autophagy-specific, too:
https://www.ebi.ac.uk/complexportal/complex/EBI-2904077
so Val's term would be fine as synonym.

We also have ATG2-ATG18 complex
https://www.ebi.ac.uk/complexportal/complex/EBI-11599487
but it has no specific GO complex term associated. I guess it was one of the earlier CP terms created before we consistently requested missing terms.
I guess the appropriate GO term can be created.

**Comment by ukemi** [comment]
I am addressing this ticket now. I will add Val's term as an exact synonym and add the comments that she suggests. If we want the AGT2-AGT18 complex, can @bmeldal add it as a separate ticket with the appropriate information?

**Comment by bmeldal** [comment]
AGT2-AGT18 complex request:
https://github.com/geneontology/go-ontology/issues/16407

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/pull/16406
