### ISSUE TITLE
(minor) comment on nicotinic acetylcholine receptors that act as ion channels

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14822]
see comment:

```
[Term]
id: GO:0015464
name: acetylcholine receptor activity
namespace: molecular_function
def: "Combining with acetylcholine and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity." [GOC:jl, GOC:signaling]
***comment: For nicotinic acetylcholine receptors that act as ion channels, instead use 'acetylcholine-gated cation channel activity ; GO:0005892***'.
is_a: GO:0004888 ! transmembrane signaling receptor activity
is_a: GO:0030594 ! neurotransmitter receptor activity
intersection_of: GO:0004872 ! receptor activity
intersection_of: has_input CHEBI:15355 ! acetylcholine
relationship: has_part GO:0042166 ! acetylcholine binding
```

GO:0005892 is the complex. 

should this instead say GO:0022848?

For reference:

```
id: GO:0022848
name: acetylcholine-gated cation-selective channel activity
namespace: molecular_function
alt_id: GO:0004889
alt_id: GO:0016904
def: "Selectively enables the transmembrane transfer of a cation by a channel that opens upon binding acetylcholine." [GOC:mah, PMID:2466967]
synonym: "acetylcholine-activated cation-selective channel activity" EXACT []
synonym: "acetylcholine-gated cation channel activity" EXACT []
synonym: "iontropic acetylcholine receptor activity" EXACT []
synonym: "nicotinergic acetylcholine receptor activity" EXACT []
synonym: "nicotinic acetylcholine-activated cation-selective channel activity" EXACT [GOC:bf]
is_a: GO:0005231 ! excitatory extracellular ligand-gated ion channel activity
is_a: GO:0022824 ! transmitter-gated ion channel activity
intersection_of: GO:0022834 ! ligand-gated channel activity
intersection_of: regulated_by GO:0042166 ! acetylcholine binding
intersection_of: transports_or_maintains_localization_of CHEBI:36916 ! cation
```

additional Q: would `nAChR activity` be an acceptable synonym here?

**Comment by bmeldal** [comment]
Yes, that was a typo, referring to the complex rather than the activity in the comment of GO:0015464.

>additional Q: would nAChR activity be an acceptable synonym here?

Only applicable to GO:0022848, the other term I think is for the muscarinic AchRs receptors but I don't think I have curated them yet.

**Comment by ukemi** [comment]
I will change the comment and add the synonym, but it seems like tere are more issues here. Why is the GO:0022848 not considered an acetylcholine receptor? It seems that we have logical defs in this area that are not necessary and sufficient. In the case of the nicotinic receptor, it says it is regulated by acetylcholine binding, but in the case of the generic receptor it has input of acetylcholine. Therefore the nicotinic receptor is not classified as a receptor. I could just assert the receptor parent, but this seems to defeat the purpose of having the logical defs and it doesn't sit well with me.

**Comment by ukemi** [comment]
Plus, it's being classified as a mechanosensitive receptor. Clearly this area of the ontology needs some work.

**Comment by ukemi** [comment]
I've opened a new ticket for the logical issues. #14823

**Comment by bmeldal** [comment]
related tickets:

https://github.com/geneontology/go-ontology/issues/11978
I don't think everything the ticket says has been done is actually visible... The Comment is still there even though David OS said he'd deleted it.

https://github.com/geneontology/go-ontology/issues/9085
Rebecca removed the references to nicotinic and muscarinic but I think we need them systematically as synonyms as that's what these receptors are known as - even though they are external compounds.

I spent a considerable amount of time on these a while ago, notes are here:
https://docs.google.com/document/d/1OmYM_1mkln_oSDCygVzSzoHqbXVrrcjthC9wQImG3-I/edit?usp=sharing

Complexes can be found in the CP searching with "acetylcholine".

**Comment by bmeldal** [comment]
Sorry, @ukemi posts crossed! Do you want me to move my comment to the new ticket?

Happy New Year!

**Comment by ukemi** [comment]
Yes please. Thanks @bmeldal. I always worry when a ticket say (minor).

**Comment by bmeldal** [comment]
Done. Yes, nothing is ever 'minor' in nature or in GO!
