### ISSUE TITLE
Reg of T cell activation does not imply reg of adhesion

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14828]
Hi

Please would you consider removing the is_a relation between

GO:1903037   regulation of leukocyte cell-cell adhesion (parent)
and
GO:0050863   regulation of T cell activation (child)

While activation of T cells will require adhesion, I do not think that regulating T cell activation will ALWAYS result from regulating adhesion

Thanks

Ruth

@rachhuntley @ukemi (and Alex Diehl?)

**Comment by ukemi** [comment]
Seems strange to me. I think it can be removed.  @addiehl ?

**Comment by addiehl** [comment]
I don't understand this connection between the two terms, and would be happy to see it removed.

Thanks, Alex

**Comment by vanaukenk** [comment]
Okay, I will remove the is_a relation between:

GO:1903037 regulation of leukocyte cell-cell adhesion (parent)
and
GO:0050863 regulation of T cell activation (child)

**Comment by RLovering** [comment]
great thanks
