### ISSUE TITLE
MP (missing parent) intermembrane lipid transfer (affects slims)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14832]
https://www.ebi.ac.uk/QuickGO/term/GO:0120009
def

The transport of lipids between membranes in which a lipid molecule is transported through an aqueous phase from the outer leaflet of a donor membrane to the outer leaflet of an acceptor membrane. This process does not require metabolic energy and can be either spontaneous or mediated by lipid transfer proteins (LTPs). PMID:20823909 PMID:24220498 PMID:25797198

![membrane](https://user-images.githubusercontent.com/7359272/34670142-f5ecc512-f46c-11e7-9f49-9cea19ba8097.jpg)

This term is really about membrane organization.
Should have the parent GO:0061024   membrane organization
https://www.ebi.ac.uk/QuickGO/term/GO:0061024

**Comment by vanaukenk** [comment]
Yes, 'intermembrane lipid transfer' would seem to fit with the 'arrangement of constituent parts' bit of the 'membrane organization' definition.

@krchristie - your initials are referenced with the GO:0120009 term definition.  Any objections to this additional parentage?

**Comment by ValWood** [comment]
GO:0034204 - lipid translocation
is this too?

**Comment by ValWood** [comment]
@krchristie  does this sound OK to you. I'd like to get this one in if possible, I'm wrapping up a paper about "unknowns" and it depends on "process slimming"

cheers

Val

**Comment by krchristie** [comment]
@ValWood - Yes, I'm fine with adding the parent **GO:0061024 membrane organization** to the term **intermembrane lipid transfer**.

Sorry for the delay. I'm on a deadline to resubmit a manuscript by 1/21/18.

**Comment by ValWood** [comment]
no worries, we might 'steal' this one tomorrow.

val

**Comment by krchristie** [comment]
It's not mine to do, just to comment whether I agree or not, so no worries on my part.

**Comment by pgaudet** [comment]
- Added parent 'membrane organization' to 'intermembrane lipid transfer'
- Added EXACT synonym intramembrane lipid transfer to 'lipid translocation' 

Pascale

**Comment by ValWood** [comment]
hi,

did you also add parent
'membrane organization' to 'lipid translocation'
?
v
