### ISSUE TITLE
MP some aspect of contractile ring localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14834]
The contractile ring is localised to the PM by various anchoring components. 

GO:1903474 maintenance of mitotic actomyosin contractile ring localization
Any maintenance of actomyosin contractile ring localization that is involved in mitotic cell cycle. PMID:12345 (incorrect PMID!)
should be part of
GO:0007016 cytoskeletal anchoring at the plasma membrane

Suggest also  updating def of
GO:1903474  maintenance of mitotic actomyosin contractile ring localization
to
A process that maintains the mitotic actinomyosin contractile ring at the plasma membrane

We could rename this  term "anchoring of the mitotic actomyosin contractile ring to the plasma membrane"
refs
PMID:19139265
PMID:28784611

~I think historically, we have 
"establishment and maintenance"  to distinguish "site selection" from "anchoring"
but there is another term for "site selection"
so
GO:1903486 - establishment of mitotic actomyosin contractile ring localization
and cytokinesis, site selection (GO:0007105) could probably merge?~

**Comment by ValWood** [comment]
Actually we have site selection (where the ring will be placed)
Then there are 2 parts to "contractile ring anchoring", establishment, and maintenance. Some pathways place the ring in the correct place, and  some prevent it from moving once it is placed in the correct place, so I x'd the final comment.

**Comment by hdrabkin** [comment]
after dozens of build attempts this finally done.
