### ISSUE TITLE
GO parentage to check

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14836]
From the last chat with Sylvain, these were the  SPKW mappings ones which I thought were not transferases because the functions are not transferases in GO.
So, we need to check the GO parentage for these....

~UniProtKB-KW:KW-0808    transferase    S.pombe    cys11    O59701~
~UniProtKB-KW:KW-0808    transferase    S.pombe    cys12    P87131~
see https://github.com/geneontology/go-ontology/issues/14968 for ontology fix

~UniProtKB-KW:KW-0808    transferase    S.pombe    SPAC6G10.03c    O14249~
~UniProtKB-KW:KW-0808    transferase    S.pombe    ykt6    O60073~
~UniProtKB-KW:KW-0808    transferase    S.pombe    nat1    O74985~
~UniProtKB-KW:KW-0808    transferase    S.pombe    trp1    Q92370~

~UniProtKB-KW:KW-0808    transferase    S.pombe    rib4    Q9UUB1~
see https://github.com/geneontology/go-ontology/issues/14969

transfered from
https://github.com/geneontology/go-annotation/issues/1503

**Comment by ukemi** [comment]
Should this be on the annotation tracker or the ontology tracker?

**Comment by ValWood** [comment]
Ontology......we need to find the individual terms with incorrect parentage.  I thought the Keywords were wrong but in this case it was the ontology.

**Comment by ValWood** [comment]
all done

**Comment by ValWood** [comment]
![mitochondrial gene expression](https://user-images.githubusercontent.com/7359272/35565853-1c4af3a4-05b7-11e8-97be-180b98d4b56b.jpg)
