### ISSUE TITLE
ragulator complex, revise definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14831]
Ragulator, small definition tweak
Existing Definition
A protein complex that contains MAPKSP1 (MP1, Map2k1ip1), ROBLD3 (p14, Mapbpip), C11orf59 (p18), LAMTOR4 and LAMTOR5. The complex is anchored to lipid rafts in late endosome membranes via C11orf59, recruits mTORC1 to lysosomal membranes in amino acid signaling to mTORC1, constitutes a guanine nucleotide exchange factor (GEF) for the Rag GTPases, and is also involved in ERK/MAPK signaling.

To
Proposed
An eukaryotically conserved protein complex comprising human LAMTOR1-5. The complex is anchored to lipid rafts in late endosome membranes via LAMTOR1,  constitutes a guanine nucleotide exchange factor (GEF) for the Rag GTPases. 

i.e.
- revise names, clarify example organism and taxonomic distribution
- delete the part about ERK/MAPK signalling as this is indirect, it is upstream)
- generics by adding “vacuolar”
- recruits mTORC1 to lysosomal/vacuolar membranes in amino acid signaling to mTORC1 is not a conserved process regulated by Ragulator

add ref for yeast (fission)
PMID: 29199950

(we probably should stick mainly to functions when describing complexes as much as possible especially for signalling complexes where  processes regulated will be varied).

@Antonialock   (as you will probably approve Kaz's paper?)

**Comment by krchristie** [comment]
@ValWood - Could you please propose a revised definition.

**Comment by ValWood** [comment]
It's above (I added "proposed" to the new one)

**Comment by krchristie** [comment]
I think we should write out the full list of human genes though. The way you wrote LAMTOR1-5, I thought you were referring to a single gene of that name. Also, the way you've written it could be interpreted as the complex only existing in human, so here's a revision:

An eukaryotically conserved protein complex; in humans, it is comprised of LAMTOR1, LAMTOR2, LAMTOR3, LAMTOR4, and LAMTOR5. The complex is anchored to lipid rafts in late endosome membranes via LAMTOR1, constitutes a guanine nucleotide exchange factor (GEF) for the Rag GTPases.

**Comment by ValWood** [comment]
Sounds better.
