### ISSUE TITLE
NTR: intron specific  pre-mRNA splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14835]
NTR: intron specific pre-mRNA splicing
A splicing factor required for excision of selected introns.

PMID:28947618

**Comment by krchristie** [comment]
How is this different from the existing term **alternative mRNA splicing, via spliceosome (GO:0000380)**, which is often specific to certain introns?

**Comment by ValWood** [comment]
Alternative splicing refers to using different intron/exon boundaries. This is a splicing factor which  is required for the normal splicing of certain individual introns (around 50 identified). The proteins aren't alternatively spliced though....
v

**Comment by ValWood** [comment]
It seems to be  mainly specific introns within proteins with lots of introns....

**Comment by ukemi** [comment]
Then isn't it just splicing?

**Comment by ValWood** [comment]
I wasn't sure. The user requested intron-specific splicing, but I think I might have requested this before and we came to the same conclusion.

So I'll use plain "splicing" with the specific genes as extensions (we don't have a way to capture the specific introns).

The  author also suggested "regulation", but I don't think this is regulation is it? It is absolutely required for the splicing of specific introns...but not for all introns...?

**Comment by krchristie** [comment]
This seems to me like just plain splicing. I agree that is does not sound like regulation either in the absence of alternative splicing.

Since it seems that we are in agreement that no new term is required, I am going to close this ticket. If I missed something, I'm confident you'll reopen it.
