### ISSUE TITLE
child of carrier activity for GO:0031207 - Sec62/Sec63 complex and SRP

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14847]
from
https://github.com/geneontology/go-annotation/issues/1740#issuecomment-356264762

should GO:0031207   
Sec62/Sec63 complex
A protein complex involved in the posttranslational targeting of proteins to the ER. In yeast, it is a tetrameric complex consisting of Sec62p, Sec63p, Sec71p and Sec72p.

and
GO:0005786   signal recognition particle, endoplasmic reticulum targeting
https://www.ebi.ac.uk/QuickGO/term/GO:0005786

be annotated as carriers? If so we would need a more specific carrier term for them.

As far as I'm aware these are both complex which brings the  protein to the translocon, so should be a carrier rather than a transporter?

**Comment by pgaudet** [comment]
Hi @ValWood 

I am not following - these are CC terms; you want to add a relation 'capable of' carrier activity? 

Thanks, Pascale

**Comment by ValWood** [comment]
Sorry, not clear.
 
I mean the members of the Sec62/Sec63 complex and the SRP (GO:0005786 signal recognition particle, endoplasmic reticulum targeting).

 Scrub the sec62/63, we don't know the exact function of this.

However, 
GO:0005786 signal recognition particle, endoplasmic reticulum targeting 
is a protein carrier.
However, molecular carrier is not for direct annotation, and there is no suitable child  term to make an annotation.

**Comment by ValWood** [comment]
I just checked QuickGO
and these generally do not have a MF annotation except for
GO:0030942    endoplasmic reticulum signal peptide binding

but nothing to represent the "carrier activity" of the SRP

**Comment by pgaudet** [comment]
Hi @ValWood 

First: this is probably not 'carrier' as we intended it: the SRP does not really deliver the protein, but it brings the ribosome, the ER and the protein together so that the protein does get to the ER. 

I thought this could go under 'protein binding, bridging', but @pedruzzi reminded by that the SRP is a complex, so that any function that we would define to capture that bridging would apply to the entire complex, not to any single subunit (right?) 

what do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK, I thought this was exactly a "carrier" by binding to the ribosome and bringing it to the recepto (similarly to the nucleocytoplasmic carriers that bind signal sequences).

But I'm happy to annotate to: 
MF "ER signal sequence binding" 
part_of   BP GO:0006614  SRP-dependent cotranslational protein targeting to membrane

**Comment by ValWood** [comment]
I just checked the def of

GO:0140104    molecular carrier activity

Definition (GO:0140104 GONUTS page) Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.

Is too restrictive  for protein carriers like "nucleocytoplasmic carrier activity"
(not molecule or ion)

**Comment by ValWood** [comment]
ignore. previous (deleted!)

I think this def fits SRP too?

**Comment by ValWood** [comment]
Ah I see, because it is ribosome. But  why can't  you have a carrier for a complex? Is it different?

**Comment by pgaudet** [comment]
Its more that use dont usually annotate complexes with MF - you annotate gene-by-gene, don't you ? So for most use cases it would be wrong. Perhaps we could use contributes to!

**Comment by ValWood** [comment]
GO:0005786  is one of the cases where I would use contributes to. Its a function of the complete complex (like DNA polymerase, ATP synthase, proteasome, etc).  I only use contributes_to for cases where the function is  an emergent property of the entire complex.

**Comment by pedruzzi** [comment]
About carrier:
yes you can imagine having a carrier for a complex, I still think its not the right term here. It's not like the SRP takes the ribosome piggyback and moves it across the cell. We're talking of the entire translation machinery, with the fully active ribosome still linked to the mRNA. The function of the SRP is to
-recognize an bind to the signal sequence of a preprotein on a translating ribosome
-stall the translation of the ribosome to prevent unproductive release of the preprotein into the cytosol
-recognize and bind to the SRP receptor on the ER membrane
The translation machinery gets there by itself by diffusion, I assume, and the SRP is linked to it, ensuring the correct targeting and alignment of the machinery on the translocon before the block on translation is released and the emerging polypeptide can traverse the membrane

![](http://accessmedicine.mhmedical.com/data/books/1687/mes_ch2_f011.png)

Defining this as a carrier is stretching the concept of a molecular carrier a bit too far in my opinion

**Comment by pedruzzi** [comment]
I also have never seen anyone talking about SRP referring about it as a carrier (while for most of the child terms under molecular carrier this is the case). I believe we should try to capture as best what is known about the function of a protein, and not too much try to impose our own concepts just for the sake of classification.
Or in other words, I don't believe anyone searching for molecular carriers in a cell will be disappointed not finding the SRP in the results list

**Comment by pedruzzi** [comment]
For other terms:
I favor @pgaudet 's proposal of GO:0030674: protein binding, bridging, as this would be valid for both SRP and SRP receptor, their function being bringing the translating ribosome and the translocon together so they can exert their correct function.
It might be too indirect for the current definition though (which was done to capture adaptor proteins)

**Comment by ValWood** [comment]
OK, yes I agree.Thanks @pedruzzi

**Comment by bmeldal** [comment]
And we are back at the old discussion:
https://github.com/geneontology/go-annotation/issues/1662 (inferring GP MF from complex MF)
and
https://github.com/geneontology/go-annotation/issues/1650 (contributes_to)

@pgaudet **we**, at the CP, annotate complexes with MF terms :)

Adding these ticket refs so we have examples for the WG and survey. Thank you :)

**Comment by pgaudet** [comment]
So, is the decision to make 'GO:0005786 signal recognition particle, endoplasmic reticulum targeting' a child of 'protein binding, bridging'? Or do we need more guidance from the Protein Complex group ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi, scratch my previous comment - I don't what I need to do now. The term that we have now is 'GO:0030942 endoplasmic reticulum signal peptide binding'. The parent of that is fine (binding). 

What I understand if that you would like a function for the entire SRP, that would have 
'has part GO:0030942 endoplasmic reticulum signal peptide binding', 
'has part protein binding, bridging' (and perhaps also has part ribosome binding'? 
ie are you asking to create a new term 'signal recognition particle activity' ? 

Thanks, Pascale

**Comment by ValWood** [comment]
You can close this. I wasn't sure if they were carriers. Since they aren't I'm happy with existing annotations to  GO:0030942 endoplasmic reticulum signal peptide binding' etc for now.
