### ISSUE TITLE
GO:0000996 core DNA-dependent RNA polymerase binding promoter specificity activity - simplify name, fix log definition and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14848]
- No direct annotations
- Parent of sigma factor & eukaryotic orthologs (mitochondrion/plastid sigma factors)
- Sigma factor binds DNA and binds the RNA polymerase to provide specificity for the transcription

![image](https://user-images.githubusercontent.com/4782928/34761637-ebbfe5be-f5e4-11e7-856e-8fbdeb0d10da.png)

Changes: 
1) core DNA-dependent RNA polymerase binding promoter specificity activity (GO:0000996)
-> Rename ‘promoter selection factor activity’
-> Add tag ‘do not annotate’ 
-> change logical definition 
**from** 
-is_a: GO:0000990 ! transcription factor activity, core RNA polymerase binding
-intersection_of: GO:0003674 ! molecular_function
-intersection_of: has_part GO:0000976 ! transcription regulatory region sequence-specific DNA binding
 intersection_of: has_part GO:0043175 ! RNA polymerase core enzyme binding
-intersection_of: part_of GO:0006355 ! regulation of transcription, DNA-templated
-relationship: has_part GO:0000976 ! transcription regulatory region sequence-specific DNA binding
**to**: 
+intersection_of: GO:0140110 ! transcription regulator activity
+intersection_of: has_part GO:0001046 ! core promoter sequence-specific DNA binding
 intersection_of: has_part GO:0043175 ! RNA polymerase core enzyme binding
+intersection_of: part_of GO:2000142 ! regulation of DNA-templated transcription, initiation

2) plastid sigma factor activity (GO:0001053)
-> move out of 'sigma factor activity', and make it a direct child of ‘DNA-dependent RNA polymerase promoter selection factor’
-> Add relationship: has_part GO:0001019 ! plastid RNA polymerase regulatory region DNA binding

3) mitochondrial RNA polymerase binding promoter specificity activity (GO:0016988)
-> Rename: 'mitochondrial promoter specificity activity'
-> Fix logical definition 
**from**
-intersection_of: GO:0003674 ! molecular_function
-intersection_of: has_part GO:0044212 ! transcription regulatory region DNA binding
-relationship: part_of GO:0006391 ! transcription initiation from mitochondrial promoter
 intersection_of: has_part GO:0001001 ! mitochondrial single-subunit type RNA polymerase binding
 intersection_of: part_of GO:1903108 ! regulation of transcription from mitochondrial promoter
 relationship: has_part GO:0001001 ! mitochondrial single-subunit type RNA polymerase binding
 relationship: has_part GO:0001018 ! mitochondrial promoter sequence-specific DNA binding
**to**
+intersection_of: has_part GO:0001018 ! mitochondrial promoter sequence-specific DNA binding
+intersection_of: GO:0000996 ! DNA-dependent RNA polymerase promoter selection factor intersection_of: has_part GO:0001001 ! mitochondrial single-subunit type RNA polymerase binding
 intersection_of: part_of GO:1903108 ! regulation of transcription from mitochondrial promoter
 relationship: has_part GO:0001001 ! mitochondrial single-subunit type RNA polymerase binding
 relationship: has_part GO:0001018 ! mitochondrial promoter sequence-specific DNA binding

4) sigma factor activity 
-> Add 'only_in_taxon NCBITaxon:2 ! Bacteria'

**Comment by pgaudet** [comment]
@krchristie are you OK with this proposal ? 

Thanks, Pascale

**Comment by krchristie** [comment]
I am OK with this, but think that if you are going to make the term 'sigma factor activity' bacterial specific, than you should also change the name to 'bacterial sigma factor activity'

**Comment by pgaudet** [comment]
Thanks @krchristie 
@keseler @tberardini 

Do you think that the different sigma factors (bacterial, plastic and mitochondrial) should be separate terms ? 

Thanks, 

Pascale

**Comment by krchristie** [comment]
The mitochondrial factors you are talking about in this ticket are NOT sigma factors (the mitochondrial RNA polymerase is more closely related to viral single subunit RNAPs than to multisubunit bacterial/plastid RNAP).

Yes, I think it is useful to have these separate terms for plastid and bacterial sigma factors because if you do not have them, you can not link them to the existing separate BP terms for bacterial transcription, plastid transcription, and mitochondrial transcription.

**Comment by pgaudet** [comment]
After discussion with Colin, I have implemented the following changes: 

* DNA-dependent RNA polymerase promoter selection factor
-> rename ‘promoter selection factor activity
* Add archeal sigma

**Comment by krchristie** [comment]
What is the basis for having anything called archael sigma? 

Archaea have an RNA polymerase more like eukaryotic RNA polymerase than like bacterial RNA polymerase and I have never come across any mention of a "sigma factor" in the context of archaeal transcription. Can you provide a reference that this is a reasonable name to use for Archaea based on the literature?

**Comment by pgaudet** [comment]
Hi @krchristie 
Thanks for the input. here's the reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC24121/
In fact the term label is 'archeal promoter selectivity factor' (I should add 'activity'. 

Does that work ? 

Thanks, Pascale

**Comment by krchristie** [comment]
I am fine with calling it "archeal promoter selectivity factor activity". Thanks Pascale

**Comment by krchristie** [comment]
Actually, I am having second thoughts about calling it "archeal promoter selectivity factor activity". From the paper, the archaeal factors seem closer to GTFs for RNAP II, and they never call it the name you want to use.

**Comment by pgaudet** [comment]
OK. I will leave out the archaeal promoter selectivity factor activity for now. I am saving the information here in case we decide to add it later. 

+id: GO:0140154
+name: archeal promoter selectivity factor activity
+namespace: molecular_function
+def: "Transcription factor that recruits RNA polymerase to promoters and define the direction of transcription in archae. Considered the functional homolog of the bacterial sigma factor and of the eukaryotic TFIIB." [GOC:txnOH-2018, PMID:10570129]
+is_a: GO:0000996 ! promoter selection factor activity
+relationship: only_in_taxon NCBITaxon:2157 ! Archaea

Thanks, Pascale
