### ISSUE TITLE
regulation of cell proliferation terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14846]
Can we apply the same annotation restrictions to
GO:0008284    positive regulation of cell proliferation
GO:0008285    negative regulation of cell proliferation
GO:0042127    regulation of cell proliferation

as to the parent cell proliferation?

**Comment by ValWood** [comment]
All should also be labeled "not for direct annotation"?

**Comment by ukemi** [comment]
We use these terms a lot and put a cell type in the annotation extension.

**Comment by ValWood** [comment]
Ok just the fungal taxon restriction like the parent?

**Comment by hdrabkin** [comment]
So why is there no regulation of cell proliferation in yeast?

**Comment by ValWood** [comment]
We don't use the proliferation term full stop. Its a problem term (its really about  population level growth, and not really a process). It's only used in multicellular organisms to  annotate proliferation of specific cell types.

I could probably annotate pretty much everything in pombe to proliferation....it isn't useful...

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/11478
This isn't the only ticket, we have had lots of discussion about the use of "proliferation" for single-celled organisms in the past. PomBase and SGD don't use it.

**Comment by hdrabkin** [comment]
Ok, so after talking with @krchristie to get some background, etc. 
As @ValWood  pointed out:  the term ‘cell proliferation’ is marked as “never_in_taxon Fungi’ and has the comment:
"This term was moved out from being a child of 'cellular process' because it is a cell population-level process, and cellular processes are restricted to those processes that involve individual cells. Also note that this term is intended to be used for the proliferation of cells within a multicellular organism, not for the expansion of a population of single-celled organisms."
The last sentence is the crux here; 
Note, that the term ‘cell proliferation’ IS labeled as being in the gosubset_prok.  Would either/or both
@@jimhu-tamuor @srengel  care to comment on this point? 
A suggestion was also made whether we  should have a term with such a general name that is intended specifically for multicellular organisms, but not for single celled ones. If this term is intended to be only for multicellular organisms, it seems it should be named ‘multicellular organism cell proliferation’.

H

**Comment by krchristie** [comment]
tagging @jimhu-tamu since tag above does not look active

**Comment by srengel** [comment]
i agree with Val.  we don't use the term for yeast.

**Comment by jimhu-tamu** [comment]
Hmm... my tag should work, but Harod used 2 @ symbols above.

I wasn't involved in originally tagging it, but I suspect it is related to how the vernacular use of growth in both bacteria and cellular fungi is really something more like proliferation than growth as used in GO. In liquid culture, when we measure growth rates by optical methods, we aren't just measuring anything getting bigger. We're measuring increased cell density as the result of a combination of cell size and number (the OD will keep going up in cells that are filamenting, for example).

Colonies getting bigger is growth, but that's not in the scope of GO, I think.  Does that make sense?

**Comment by ValWood** [comment]
That's my thoughts exactly, proliferation is a  population phenotype for single celled organisms. Usually when  authors say "required for proliferation" they mean "viable population".
If such a term were allowed in GO it would be very difficult to position in the hierarchy , as it would need to encompass both growth (including biosynthesis of proteins and other building blocks), and cell cycle/division.

It would be really great if this could be restricted to the multicellular usage of "growth of a population of cell of a specific  type". I'm not convinced this is really a process, but it  is clearly useful, and it making the term "multicellular only" reduces the problem.

**Comment by hdrabkin** [comment]
Are we done with this? 
So all I need to do is add taxon restriction to the children? All agreed?

**Comment by ValWood** [comment]
Yes, we don't use this term in Fungi.
Although the taxon restriction should populate downwards so the mapping I had a problem with should already be caught by the taxon violation?

**Comment by ValWood** [comment]
I don't understand why this isn't already a violation
https://github.com/geneontology/go-annotation/issues/1742
http://www.ebi.ac.uk/interpro/entry/IPR026872

**Comment by hdrabkin** [comment]
Just thinking; this sentence
"In yeast, protein farnesylation is important for maintaining normal cell morphology [PMID: 10617635] and for cell cycle progression [PMID: 11580838]. "

So could it be cell cycle progression is being equated with assigning the GO ID for regulation of cell proliferation? which is not necessarily true. Is it a ip2go problem?

**Comment by ValWood** [comment]
It's indirect...let's not go there ;)

Actually in fission yeast  farnesylation does not even have any cell cycle phenotypes as far as I can see, but we don't annotate cell cycle  for all cell cycle phenotypes because most are too upstream...otherwise we would have ~1000 gene products  annotated to regulation of cell cycle and counting.
We identified 100's here and https://www.ncbi.nlm.nih.gov/pubmed/23697806
but we (and our community) would not find it useful to have all of these annotated to GO cell cycle processes.

The problem is the mapping from InterPro. The mapping will go away when the taxon restriction is applied ...but I don't know why the taxon restriction is not there already is "cell proliferation" is taxon restricted?

**Comment by hdrabkin** [comment]
Ok; added restriction to the 3 regulation terms as requested; closing
Yes cell prolif does have the restriction; anyways, let's see what happens; closing

**Comment by ValWood** [comment]
Maybes taxon restrictions do not propagate down "regulates" terms ?

(although that would be very odd?)

It would be good to know why it wasn't working?

**Comment by cmungall** [comment]
regulates can be cross-species

**Comment by ValWood** [comment]
@cmungall  Any regulation?
I thought cross-species terms would all be under
https://www.ebi.ac.uk/QuickGO/term/GO:0044419
interspecies interaction between organisms

**Comment by cmungall** [comment]
They are, bust many descendants of this trace to host processes via regulates, e.g.

http://amigo.geneontology.org/amigo/term/GO:0039502

One solution here is to use a different relation for x-species regulation.

**Comment by ValWood** [comment]
Yes I always forget this. I preferred the old system where they were pathogen-host interactions were explicitly disjoint. It was much clearer.

A different relationship is a good idea.

**Comment by happy-lorna** [comment]
@hdrabkin I still dont see the tax constraint for GO:0042127 "regulation of cell proliferation"

**Comment by hdrabkin** [comment]
I put them in; I just checked; never in taxon Fungi is in each.

**Comment by happy-lorna** [comment]
OK it seems the changes have not been pulled into QuickGO yet (I am chasing that up here). 
Not that I don't trust that you have added the changes, but in case I am looking for someting like this in the future, and it is not in QuickGO, where else can I look?

**Comment by hdrabkin** [comment]
I'd 1rst check that Quickgo has indeeded updated relative to when the ticket was closed. At MGI, I download the version that was loaded (we do this each night) and check the obo file for the record. 
There ARE times when for whatever reasons, the production pipeline doesn't update the versions that people use for downloading.

**Comment by happy-lorna** [comment]
Initial thoughts were that these constraints would be picked up in the update this Saturday and so be visible on QuickGO from then. However, a bit more digging by @tonysawfordebi has uncovered that the GPplus.obo (?) file where they get this information from has not been getting updated for 10 months. They will have to pull the data from elsewhere now, all of which might take a bit of time to sort out.
