### ISSUE TITLE
TPV glycine import into mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14858]
is a decendant of
drug transmembrane transport
glycine import into across plasma membrane
 cation transmembrane transport

**Comment by pgaudet** [comment]
These are all inferred by inferencing over CHEBI 'roles' - see https://github.com/geneontology/go-ontology/issues/14626

However these CHEBI roles are very permissive, so @ukemi has proposed to remove that. Is that OK for you ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @ValWood 
I removed 'glycine import into across plasma membrane' (thanks @ukemi for noticing that one!) 
Others are due to reasoning over roles; we'll discuss that at the next ontology call. 

Thanks. Pascale

**Comment by ukemi** [comment]
Actually the cation one is because the NH2 can be protonated to the conjugate base glycinium, making it a cation. So this is one we will have to live with.
