### ISSUE TITLE
Merge RNA polIII transcription factor activity terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14852]
Hello, 

(Edited as suggested by @krchristie ) 

The proposal has been made to merge 
- GO:0001004 'transcription factor activity, RNA polymerase III promoter sequence-specific binding, TFIIIB recruiting'
and its 4 children: 
- GO:0001038 'RNA polymerase III hybrid type promoter TFIIIB recruiting transcription factor activity'
- GO:0001005 'transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting'
- GO:0001008 'transcription factor activity, RNA polymerase III type 2 promoter sequence-specific binding, TFIIIB recruiting'
- GO:0001004 'transcription factor activity, RNA polymerase III type 3 promoter TFIIIB recruiting'

The reason for the merge is that these three functions are too detailed; it's not informative to break the functions of these proteins to that degree. 

Discussion on the impact on annotations can be found here: 
https://github.com/geneontology/go-annotation/issues/1734

Thanks, Pascale

@krchristie 
please comment

**Comment by krchristie** [comment]
No objections to merging, but I'm not sure it's strictly true to say that "that these three functions are mediated by the same proteins". My recollection is that there are some differences. Maybe something more on the lines of too detailed to be useful.

**Comment by pgaudet** [comment]
thanks @krchristie
