### ISSUE TITLE
Transcription BP: simplify some term labels

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14854]
GO:0001121 transcription from bacterial-type RNA polymerase promoter -> bacterial transcription
GO:0006390 transcription from mitochondrial promoter -> mitochondrial transcription
GO:0042792 rRNA transcription from mitochondrial promoter -> mitochondrial rRNA transcription
GO:0042793 transcription from plastid promoter -> plastid rRNA transcription
GO:0042794 rRNA transcription from plastid promoter -> plastid rRNA transcription
GO:0006360 transcription from RNA polymerase I promoter -> transcription by RNA polymerase I 
GO:0042790 transcription of nuclear large rRNA transcript from RNA polymerase I promoter -> transcription of nucleolar large rRNA by RNA polymerase I
GO:0006366 transcription from RNA polymerase II promoter -> transcription by RNA polymerase II
GO:0042789 mRNA transcription from RNA polymerase II promoter -> mRNA transcription by RNA polymerase II
GO:0061614 pri-miRNA transcription from RNA polymerase II promoter -> pri-miRNA transcription by RNA polymerase II
GO:0001015 snoRNA transcription from an RNA polymerase II promoter -> snoRNA transcription by RNA polymerase II
GO:0042795 snRNA transcription from RNA polymerase II promoter -> snRNA transcription by RNA polymerase II
GO:0097394 telomeric repeat-containing RNA transcription from RNA pol II promoter -> telomeric repeat-containing RNA transcription by RNA polymerase II
GO:0006383 transcription from RNA polymerase III promoter -> transcription by RNA polymerase III
GO:0042796 snRNA transcription from RNA polymerase III promoter
GO:0042797 tRNA transcription from RNA polymerase III promoter -> tRNA transcription by RNA polymerase III
GO:0001059 transcription from RNA polymerase IV promoter -> transcription by RNA polymerase IV
GO:0001060 transcription from RNA polymerase V promoter  -> transcription by RNA polymerase V

@thomaspd @krchristie @ValWood @tberardini (plastidial?) 
Feedback welcome. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+1 by Colin Logie

**Comment by tberardini** [comment]
@pgaudet, if you'd like to keep in sync with the not entirely analogous translation term, then it would be 'plastid transcription'.

plastid translation
http://amigo.geneontology.org/amigo/term/GO:0032544

For real clarity though, I would prefer keeping the slightly longer forms on the left below:

GO:0001121 transcription from bacterial-type RNA polymerase promoter -> bacterial transcription
GO:0006390 transcription from mitochondrial promoter -> mitochondrial transcription
GO:0042793 transcription from plastid promoter -> plastidial transcription

**Comment by ValWood** [comment]
@tberardini  just curious why you think the longer term names are clearer, they don't provide any additional info? Isn't a researcher more likely to say  "mitochondrial transcription" than 
"transcription from mitochondrial promoter" and these are absolutely equivalent?

Isn't natural language is better unless disambiguation is required, and I thought we were aiming for that  in term names where possible?

**Comment by tberardini** [comment]
@ValWood : I did some more reading and **I retract my objection to the shortened terms**.  The concerns I had were not backed up by literature.

**Comment by ValWood** [comment]
great, i though i was missing somerhing ;)

**Comment by pgaudet** [comment]
I also did all the regulation terms: 
GO:1903108  regulation of transcription from mitochondrial promoter -> regulation of mitochondrial transcription
GO:1903109  positive regulation of transcription from mitochondrial promoter

Any process that activates or increases the frequency, rate or extent of transcription [from mitochondrial promoter]. ->  occuring in the mitochondrion.

GO:0006356 regulation of transcription from RNA polymerase I promoter -> regulation of transcription by RNA polymerase I
Any process that modulates the frequency, rate or extent of transcription [from an RNA polymerase I promoter.] mediated by RNA polymerase I.

GO:0016479 negative regulation of transcription from RNA polymerase I promoter -> negative regulation of transcription by RNA polymerase I

GO:2001208 negative regulation of transcription elongation from RNA polymerase I promoter -> negative regulation of transcription elongation by RNA polymerase I

GO:1901837 negative regulation of transcription of nuclear large rRNA transcript from RNA polymerase I promoter -> negative regulation of transcription of nucleolar large rRNA by RNA polymerase I


GO:0045943 positive regulation of transcription from RNA polymerase I promoter

GO:0006357 regulation of transcription from RNA polymerase II promoter ->  regulation of transcription by RNA polymerase II

GO:0000122 negative regulation of transcription from RNA polymerase II promoter -> negative regulation of transcription by RNA polymerase III

GO:0045944 positive regulation of transcription from RNA polymerase II promoter -> positive regulation of transcription by RNA polymerase II

GO:0006359 regulation of transcription from RNA polymerase III promoter ->  regulation of transcription by RNA polymerase III

GO:0016480 negative regulation of transcription from RNA polymerase III promoter -> negative regulation of transcription by RNA polymerase III

GO:0045945 positive regulation of transcription from RNA polymerase III promoter -> positive regulation of transcription by RNA polymerase III

GO:1904279 regulation of transcription from RNA polymerase V promoter -> regulation of transcription from RNA polymerase V promoter

GO:1904280 negative regulation of transcription from RNA polymerase V promoter -> negative regulation of transcription by RNA polymerase V

GO:1904281 positive regulation of transcription from RNA polymerase V promoter -> positive regulation of transcription by RNA polymerase V

**Comment by pgaudet** [comment]
GO:1901836 regulation of transcription of nuclear large rRNA transcript from RNA polymerase I promoter -> regulation of transcription of nucleolar large rRNA by RNA polymerase I

GO:1901838 positive regulation of transcription of nuclear large rRNA transcript from RNA polymerase I promoter -> positive regulation of transcription of nucleolar large rRNA by RNA polymerase I

GO:1905380 regulation of snRNA transcription from RNA polymerase II promoter -> regulation of snRNA transcription by RNA polymerase II

GO:1905381 negative regulation of snRNA transcription from RNA polymerase II promoter->  negative regulation of snRNA transcription by RNA polymerase II
GO:1905382 positive regulation of snRNA transcription from RNA polymerase II promoter -> positive regulation of snRNA transcription by RNA polymerase II

GO:0060962 regulation of ribosomal protein gene transcription from RNA polymerase II promoter
GO:0010688 negative regulation of ribosomal protein gene transcription from RNA polymerase II promoter -> negative regulation of ribosomal protein gene transcription by RNA polymerase II
positive regulation of ribosomal protein gene transcription from RNA polymerase II promoter -> positive regulation of ribosomal protein gene transcription by RNA polymerase II

GO:1902893 regulation of pri-miRNA transcription from RNA polymerase II promoter
GO:1902894 negative regulation of pri-miRNA transcription from RNA polymerase II promoter
GO:1902895 positive regulation of pri-miRNA transcription from RNA polymerase II promoter
