### ISSUE TITLE
NTR: positive/negative regulation of GO:0061462 protein localization to lysosome

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14859]
Figure 5 in PMID:24305806 shows that ROCK2 negatively regulates the localization of BACE1 as well as APP to lysosomes.

Intended annotation:
ROCK2 O75116 - IMP - negative regulation of protein localization to lysosome - has_regulation_target BACE1 P56817 | has_regulation_target APP P05067

cc: @RLovering 

GOC:aruk
GOC:bc

**Comment by ukemi** [comment]
Is this really regulating a process of localization, or is it a pathological consequence of inhibiting ROCK2 pharmacologically? It seems like maybe better annotations that describe the mechanism are possible. @vanaukenk ?

**Comment by paolaroncaglia** [comment]
@ukemi @BarbaraCzub @RLovering 
The paper that @BarbaraCzub is looking at dates back to 2013, so my first thought was to try and look for more recent, detailed evidences of the molecular role of ROCK2 in relation to APP. I had a quick look at a couple of more recent abstracts, but couldn’t find any conclusive statement (but mine wasn’t an exhaustive search). Anyway, looking at figure 5 in Barbara’s paper, I too would annotate ROCK2 to ‘negative regulation of protein localization to lysosome’. I agree that the detailed molecular mechanism(s) can’t be extracted from fig. 5, but I think that the statements “has_regulation_target BACE1 P56817 | has_regulation_target APP P05067” would still be justified (I’ll leave the last word on this to accustomed annotators).

**Comment by ukemi** [comment]
@paolaroncaglia 
Thanks for the feedback. Would regulates_transport_of be a better relation to use for the BACE1 and the APP?

**Comment by paolaroncaglia** [comment]
@ukemi 
That does sound nicer, though we'd still be saying something a bit more specific than the paper allows to detail. But if those AEs are good to be used that way, then yes transport would probably be more correct.

**Comment by ukemi** [comment]
Ah you are right. There is no proof of transport.

**Comment by vanaukenk** [comment]
Yes, I think for our existing set of annotation extension relations, 'has regulation target' is probably the best we have for capturing this information.
I don't see that we have a relation 'regulates o results in localization of'.

**Comment by BarbaraCzub** [comment]
Thank you all for your comments. I'll go ahead and make this new regulation term when the issue of Travis checks has been resolved, and then I'll make the intended annotation. Thanks!
