### ISSUE TITLE
Proposal to obsolete     GO:0051858  avoidance of symbiont defenses and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14862]
Hello, 

The proposal has been made to obsolete 
GO:0051858  avoidance of symbiont defenses
GO:0051860 evasion or tolerance of symbiont defenses
GO:0051859 suppression of symbiont defenses 
GO:0052196 negative regulation by host of symbiont defense response

The reason for obsoletion is that these terms represent normal 'immune response'. Consistent with this, there are no annotations to these terms. We are opening a comment period for this proposed obsoletion. Please comment on the ticket:
https://github.com/geneontology/go-ontology/issues/14862

We’d like to proceed and obsolete this term on Jan 17, 2018. Unless objections are received by Jan 17, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@pmasson55 do you have any comments ?

**Comment by mgiglio99** [comment]
Hi Pascale,
These are part of the PAMGO terms. I'd like to think about this a bit more before these get obsoleted. I'm sure we considered immune response terms and had a reason for thinking something separate was needed. If the above terms are covered by immune response terms, are there terms these could be merged into?
Michelle

**Comment by pgaudet** [comment]
Hi @mgiglio99 
Thanks for your comment! To be honest I was simply thinking of 'immune response'; but without any reference or annotations I don't know what was intended. I found some notes here: 
http://wiki.geneontology.org/index.php/Talk:PAMGO_work_in_progress#Avoidance.2C_Evasion_and_Tolerance.2C_oh_my.21
but I wasn't able to understand the intended usage of most of these terms based on those. 

Another point is that the lack of references and lack of annotations is quite widespread for this project, so it's very difficult to know which terms are necessary or not, and it creates a lot of annotation inconsistencies. For example there are over 1000 terms under 'interspecies interaction between organisms', but only about half have been used, and only about 200 have been used more than 10 times (including IEA). If you limit to Experimental there are only 100 terms with more than 10 annotations. 
If anyone from PamGO can help us understand and populate these terms , that'd be great ! 

Thanks, Pascale
