### ISSUE TITLE
NTR: ER plasma membrane contact site

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14861]
name: ER plasma membrane contact site
synonym: ER-PM contact site
def:
A contact site between the Endoplasmic Reticulum membrane and the plasma membrane, structured by bridging complexes. 

dbxref   PMID:29290560  PMID: 23041194

child of
GO:0044232    organelle membrane contact site
https://www.ebi.ac.uk/QuickGO/term/GO:0044232

update def of "organelle membrane contact site" to include plasma membrane

A zone of apposition between the membranes of two organelles **** or an organelle and the plasma membrane***, structured by bridging complexes. Membrane contact sites (MCSs) are specialized for communication, including the efficient traffic of small molecules such as Ca2+ ions and lipids, as well as enzyme-substrate interactions.

**Comment by ukemi** [comment]
We think carefully to make sure this change in definition is ok. A plasma membrane is not currently an organelle. If the contact site includes both a part of the plasma membrane and a part of the organelle, there will be a TPV for organelle part.

**Comment by ValWood** [comment]
maybe have a plain "membrane contact site" term is_a "membrane part"

but organelle contact site term name might then need to be clarified as 
organelle-organelle membrane contact site

**Comment by ValWood** [comment]
not to self, put session through, need to fix curs/a4e15abcd73293ed#

**Comment by pgaudet** [comment]
@ukemi 
How about if we update the definition as follows: 
"A zone of apposition between the membranes of an organelle with another membrane, either that of another organelle or the plasma membrane, structured by bridging complexes. Membrane contact sites (MCSs) are specialized for communication, including the efficient traffic of small molecules such as Ca2+ ions and lipids, as well as enzyme-substrate interactions."
I dont think this is inconsistent; what do you think ?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140268
+name: endoplasmic reticulum-plasma membrane contact site
+namespace: cellular_component
+def: "A contact site between the endoplasmic reticulum membrane and the plasma membrane, structured by bridging complexes." [PMID:23041194, PMID:29290560]
+synonym: "ER-plasma membrane contact site" EXACT []
+synonym: "ER-PM contact site" EXACT []
+intersection_of: GO:0044232 ! organelle membrane contact site
+intersection_of: overlaps GO:0005789 ! endoplasmic reticulum membrane
+intersection_of: overlaps GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-09-26T09:29:41Z
