### ISSUE TITLE
MP  endoplasmic reticulum localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14866]
GO:0051643   endoplasmic reticulum localization

should this be a descendant of 
GO:0007029    endoplasmic reticulum organization

I'm never sure but it does sound like arrangement of constituent parts?

https://github.com/pombase/fypo/issues/3194

**Comment by ukemi** [comment]
Localization would be the process that localizes something to the ER. Would that necessarily be part of the ER's organization? @vanaukenk , weren't you looking into these kinds of terms?

**Comment by ValWood** [comment]
endoplasmic reticulum localization
Biological Process
GO:0051643 endoplasmic reticulum localization
is about localization of the ER itself

Definition 
Any process in which endoplasmic reticulum is transported to, and/or maintained in, a specific location within the cell.

it includes 
GO:0061817    endoplasmic reticulum-plasma membrane tethering
and
GO:0051685    maintenance of ER location
as children


localization to the ER is 
GO:0070972    protein localization to endoplasmic reticulum

**Comment by vanaukenk** [comment]
Here are some of the relevant terms and definitions:

endoplasmic reticulum organization
GO:0007029  A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the endoplasmic reticulum.

endoplasmic reticulum localization
GO:0051643 Any process in which endoplasmic reticulum is transported to, and/or maintained in, a specific location within the cell.

protein localization to endoplasmic reticulum
GO:0070972 A process in which a protein is transported to, or maintained in, a location within the endoplasmic reticulum.

@ValWood What would the relation between the endoplasmic reticulum localization and organization terms be?

It seems that an organelle could be fully organized but still undergo a change in its localization (e.g. a nucleus that migrates from one part of the cell to another).

**Comment by ValWood** [comment]
HI @vanaukenk 

Yes, I agree

"arrangement of constituent parts" is  disjoint from  localization.

I sometimes get confused. For instance "chromosome localization" seems that it should sometimes be part of "chromosome organization"   when it's to do with the localization  of chromatin to specific nuclear envelope regions (chromosome is an organelle too).



v

**Comment by ValWood** [comment]
>
It seems that an organelle could be fully organized but still undergo a change in its localization (e.g. a nucleus that migrates from one part of the cell to another).

Yes, I think this is where I always stumble with this one. It is to do with "intrinsic organization" rather than "spatial organization" ?

Would comments help for others?

**Comment by ValWood** [comment]
or  even def revisions?

**Comment by ValWood** [comment]
can close this one...
