### ISSUE TITLE
MP endosomal transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14874]
endosomal transport is no longer a "vesicle-medated transport".

I think this was lost recently when "vacuolar transport" parent was deleted (I agree that does not sound correct),
but "vesicle-mediated transport should be added instead.

cheers,

Val

**Comment by pgaudet** [comment]
Hi @ValWood 
The reason why this doesn't work is that the logical definition is: 
transport
 and ('occurs in' some intracellular)
 and ('results in transport to from or in' some endosome)

whereas 
vesicle-mediated transport is: 
transport
 and (mediated_by some vesicle)

I am guessing that the logical definition of endosomal transport is incorrect, but should we first review annotations? 

Thanks, Pascale

**Comment by ValWood** [comment]
Oh yes that's correct. We discussed this before
https://github.com/geneontology/go-ontology/issues/11589
The resolution was to check that all of the children have a vesicle-mediated transport parentage. I think they probably do.

I  just need to make sure the annotations are more specific than "endosomal transport" where possible....

**Comment by pgaudet** [comment]
tomorrow ?

**Comment by ValWood** [comment]
Can close, I made this "not for direct annotation" locally at PomBase, but its quite a specific term to block more generally (at the moment ;)

**Comment by pgaudet** [comment]
I created a ticket to review annotations and deal with this one. 
https://github.com/geneontology/go-annotation/issues/1778

Thanks, Pascale

**Comment by pgaudet** [comment]
- Looks like the annotation reviews show that all annotated proteins are part of vesicle-mediated endocytic transport. So we can fix the definition and the logical definition. 

- I will also merge 'GO:0032439 endosome localization' since all 6 EXP annotations also represent vesicle-mediated endocytic transport.
