### ISSUE TITLE
Travis checks are failing

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#14871]
Hi,

@hdrabkin 
@krchristie 
@BarbaraCzub 
@paolaroncaglia 

Just a ticket to let other ontology editors know that the Travis checks are currently failing and so it's probably a good idea to hold off on making more commits.

@ukemi and I Skyped with @dougli1sqrd yesterday and he and @cmungall are looking into it.

Thx.

**Comment by ukemi** [comment]
Any updates as to why this is happening?

**Comment by vanaukenk** [comment]
Restarting the Travis builds for failed checks seems to get the checks to work now, but we'll leave the ticket open since it looks like the same error messages are still there and we'd like Chris and Eric to comment about what to do going forward.

**Comment by dougli1sqrd** [comment]
I just added a change to robot that should eventually propogate through that cuts down a ton on logging output. One hypothesis was that the travis check had too much logging. Also though, Travis has been having some issues, so maybe that's cleared up. @vanaukenk, do I take your last comment to mean things seem to be working?

**Comment by hdrabkin** [comment]
Just had a timeout failure
"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
"
Will wait a bit then try again

**Comment by cmungall** [comment]
https://www.traviscistatus.com

they are still having issues

Note if you have robot installed locally you can run the exact same tests that travis runs. It's not nearly as convenient, but it avoid being blocked

**Comment by hdrabkin** [comment]
well, I just changed one more id and recommitted and pushed; let's see what happens

**Comment by ukemi** [comment]
We need to get good documentation in place for running robot locally.

**Comment by hdrabkin** [comment]
yah, right now my notes from Berkely are in the office ( I have a special Berkely book). 8-(

**Comment by ukemi** [comment]
The plan is to move the ontology editors' SOPs back to the wiki so that all of the annotation and ontology editors docs will be in the same place and in the same format. We can work on this in February.

**Comment by hdrabkin** [comment]
no luck; failed again.

**Comment by ukemi** [comment]
My build timed out this morning.

**Comment by ukemi** [comment]
It seems like this command is generating a lot of errors.

`robot reduce -r elk -i go-pre.obo -o go-pre-reduced.obo`

**Comment by hdrabkin** [comment]
Is that new? I didn't notice that yesterday when I was watching the log build

**Comment by hdrabkin** [comment]
I just did a pull to my local and it had changed, but I don't see your pull request on the web site anymore.  Did it finally work?

**Comment by ukemi** [comment]
Yup. After triggering the build around five times.

**Comment by hdrabkin** [comment]
I'm going to try one! Watch out.

**Comment by hdrabkin** [comment]
Nope; first attempt timed out.

**Comment by hdrabkin** [comment]
sent one through with no problems. 
Now trying  one 4 times; all timing out, but I see I build after me as gone through ok.

**Comment by dougli1sqrd** [comment]
I'm reasonably certain https://github.com/geneontology/go-ontology/pull/14907 will make this work.

**Comment by dougli1sqrd** [comment]
Make sure you update any existing PRs!

**Comment by hdrabkin** [comment]
seems to be now stuck much earlier on this line
travis_wait make travis_test; 17 minutes thus far

**Comment by hdrabkin** [comment]
It timed out and failed due to thet travis_wait make travis_test
:home/travis/.travis/job_stages: line 169:  4163 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait make travis_test" exited with 0.

**Comment by hdrabkin** [comment]
actually, there is a fail message with 
The command "travis_wait make travis_test" exited with 137.
Done. Your build exited with 1.
I hav NO idea what is wrong.

**Comment by ukemi** [comment]
I think it is because the command waits 20 minutes and the build took 21. @dougli1sqrd ?

https://github.com/geneontology/go-ontology/pull/14905

**Comment by dougli1sqrd** [comment]
Yeah, you can see the error message saying something about it taking longer than 20 minutes inside the `travis_wait`. We can keep increasing the wait time, to something like 30 minutes. But also it's bad that it takes this long.

**Comment by hdrabkin** [comment]
I just restarted the build; should I stop it or wait?

**Comment by dougli1sqrd** [comment]
I'm making a change that should increase the timeout and the memory used for robot, so maybe it'll speed up a little.

**Comment by hdrabkin** [comment]
ok, I just canceled the build and wait a half hour before trying again.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/14911
Okay Herald, try updating your PR from master and try again?

**Comment by hdrabkin** [comment]
Ok, off it goes

**Comment by hdrabkin** [comment]
It worked!!!

**Comment by hdrabkin** [comment]
Twice now in a row! I'm on a roll!

**Comment by BarbaraCzub** [comment]
Yay! Thank you @dougli1sqrd and @hdrabkin for fixing and testing.
So do I understand correctly that this means we can start making commits now?

cc
@RLovering 
@paolaroncaglia

**Comment by hdrabkin** [comment]
LOL; I wasn't really testing it; I was desperately trying to close two tickets!

**Comment by BarbaraCzub** [comment]
For the benefit of us all! :)

**Comment by ukemi** [comment]
I think we can close this with the assumption that we are going to try to streamline the checks and make them run faster.
