### ISSUE TITLE
NTR mitotic spindle pole body insertion to nuclear envelope

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14887]
I need a term to describe "insertion of the mitotic spindle pole body into the nuclear envelope"

refs

PMID:28619713
PMID:7744953
PMID: 27889481
PMID: 9285819
PMID: 15385623

**Comment by vanaukenk** [comment]
@ValWood 

There is also this term:

GO:1990608 mitotic spindle pole body localization to nuclear envelope

Would it be better to rename this term to be 'mitotic spindle pole body insertion into the nuclear envelope' and re-house existing annotations to this term, as appropriate?

There is only one annotation to GO:1990608 and that is to pombe kms2

**Comment by ValWood** [comment]
We probably could, but I think this existing term might still be required to cover any localization of the SPB to the nuclear envelope.

The SPB is initially inserted (localization established), and then they move across the nuclear envelope during spindle assembly. Maybe this is different because it is movement within the nuclear envelope, but for now I was assuming it was also a part of  "localization to" the nuclear envelope ?

So my plan was to move kms1 (which is involved in insertion) down to the new specific  term for "establishment of localization/insertion".

Let me know what you think...

**Comment by ValWood** [comment]
here instead of
spindle pole body insertion into nuclear envelope
in think we should go with "tethering" in both cases.

the spindle pole body is "tethered to the nuclear envelope" "insertion" is sometimes used but 
I don't think its really clear how it happens.

so 

NTR: mitotic spindle pole body tethering to the nuclear envelope
related synonym: mitotic spindle pole body insertion into the nuclear envelope

probably reflects knowledge better.

**Comment by ValWood** [comment]
See also
https://github.com/geneontology/go-ontology/issues/14829

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0099022
although "tethering" has a very specific context here
vesicle tethering
Biological Process

Definition (GO:0099022 GONUTS page)
The initial, indirect interaction between a vesicle membrane and a membrane to which it is targeted for fusion. This interaction is mediated by tethering factors (or complexes), which interact with both membranes.

maybe for this we should just go with Sandra's original  "anchoring", because this is not "tethering in the same sense"

**Comment by ValWood** [comment]
I now think we should broaden tethering, because tethering is definitely used a lot in the "chromosome tethering context" and we carefully captured the  difference between "tethering and clustering"

So "tethering is fine, so long as it can be  defined in a way that can apply to the tethering of  vesicles to membranes , and or chromosomes to membranes.

if this is not possible some disambiguation will be required.....

**Comment by vanaukenk** [comment]
Okay, at @ValWood - here is a summary:

1) Change label of GO:0071790 from 'establishment of spindle pole body localization to nuclear envelope' to 'mitotic spindle pole tethering to nuclear envelope'

2) Add related synonym: 'mitotic spindle pole body insertion into nuclear envelope'

3) Val, can you please double-check whether PMID:20434336 is still appropriate?

4) @suzialeksander @srengel - if this term name is changed as above, will the existing SGD annotation to NBP1 still be correct, particularly wrt the related synonym suggested in 2?  The reference for the NBP1 annotation refers mostly to SPB insertion.

Thx.

**Comment by srengel** [comment]
@vanaukenk i think it should be fine for NBP1.  keeping the '...SPB insertion...' synonym will be key, because the 'insertion' language is what is typically used in papers studying this.  for budding yeast, anyway.

**Comment by ValWood** [comment]
The complications are that 
tethering in pombe occurs before insertion (the SPB is tethered during interphase and inserted during mitosis).  In S. cerevisiae  the SPB is inserted during interphase. 

So instead  I can use

GO:0043495    protein membrane anchor
part of 
GO:1990608 mitotic spindle pole body localization to nuclear envelope
synonym narrow: spindle pole body insertion into nuclear envelope
synonym narrow: mitotic spindle pole body tethering to the nuclear envelope

for what I need (for the tethering part).

This loses the fact that it is "establishment" (annotations  to describe the same processes are split between the existing mitotic term and the  establishment term).

However, I'm not sure that we need  separate establishment and maintenance terms here
we could  simplify the ontology by merging
GO:0071790    establishment of spindle pole body localization to nuclear envelope
up to it's parent.

Then we could refine the types of localization later if different gene products are involved. At the moment there don't appear to be clear differences between the 2 branches ...

I'm in favour of lumping until splitting is clearly required.

**Comment by ValWood** [comment]
PMID:20434336 is incorrect whatever, any of the other refs above are good.

**Comment by ValWood** [comment]
I will look at this again.
will revise based on recent migration of some tethering terms to  MF (anchoring)

**Comment by ValWood** [comment]
note to self curs/e28e479729269ce9#

**Comment by ValWood** [comment]
This issue has come up again:
https://github.com/pombase/fypo/issues/3752

I will summarize

**Comment by ValWood** [comment]
GO:0071790 mitotic spindle pole body localization now exists

But I still I require a  descendant
GONEW : mitotic spindle pole body insertion into the nuclear envelope
A process in which  the  duplicated mitotic spindle pole body is inserted into a fenestra which opens  in  the nuclear envelope in early mitosis, and is subsequently tethered to the membrane.

Justification:
The duplicated mitotic (and meiotic SPB move around *within* the membrane, but this is a *separate* process to represent the initial  "insertion" step (see the figure in the link below). 
Tethering is only part of the process - the genes I am annotating are not tethers but the process is still relatively uncharacterised.

Nice reviews from Sue Jasperson.
https://www.sciencedirect.com/science/article/pii/S0955067413001415?via%3Dihub
https://www.sciencedirect.com/science/article/pii/S0955067413001415?via%3Dihub#fig0010
https://www.sciencedirect.com/science/article/pii/S0955067413001415#fig0020
(this can be used as a referece also  ******ADD PMID)


I am currently annotating some old papers including this one which can be used as a reference:
 PMID:19487457  "The S. pombe mitotic regulator Cut12 promotes spindle pole body
  activation and integration into the nuclear envelope."

**Comment by ValWood** [comment]
We definitely need a new term for this. 
Localization of the SPB is broader than insertion.
So, could this be added? We now need it for a few papers, one from 2 years ago that I had totally forgotten about and some I am now annotating.

Also our phenotype defs will require it.

**Comment by ValWood** [comment]
note also that these  narrow definitions should be moved from the ancestor tot eh new term.

establishment of spindle pole body localisation in nuclear envelope | narrow
establishment of spindle pole body localization in nuclear envelope | narrow
establishment of spindle pole body localization to nuclear envelope | narrow

or be removed. I don't think they are even required if we get the "insertion" term

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140480
+name: mitotic spindle pole body insertion into the nuclear envelope
+namespace: biological_process
+def: "A process in which the duplicated mitotic spindle pole body is inserted into a fenestra which opens in the nuclear envelope in early mitosis, and is subsequently tethered to the membrane." [PMID:19487457, PMID:24529240]
+synonym: "establishment of spindle pole body localisation in nuclear envelope" NARROW []
+synonym: "establishment of spindle pole body localization in nuclear envelope" NARROW []
+synonym: "establishment of spindle pole body localization to nuclear envelope" NARROW []
+is_a: GO:0070631 ! spindle pole body localization
+intersection_of: GO:0051179 ! localization
+intersection_of: has_target_end_location GO:0005635 ! nuclear envelope
+intersection_of: transports_or_maintains_localization_of GO:0044732 ! mitotic spindle pole body
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/14887 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-25T14:45:40Z

**Comment by mah11** [comment]
Is that synonym scope correct?

**Comment by pgaudet** [comment]
Is it ?

**Comment by ValWood** [comment]
Narrow is incorrect, sorry.
I think it should be exact
"to the nuclear envelope" is only insertion.
after insertion the spindle pole body moves within the nuclear envelope.
So the broader term will be"mitotic spindle pole body localization "
I'm not aware of any other function or process that localizes to the nuclear envelope.

The tethering activities (MFs)  will keep it them in the nuclear envelope  while they  are migratiog, but could be coupled to "Insertion" process  or localization process.

**Comment by pgaudet** [comment]
I fixed the 3 synonyms to EXACT: 

+synonym: "establishment of spindle pole body localisation in nuclear envelope" EXACT []
+synonym: "establishment of spindle pole body localization in nuclear envelope" EXACT []
+synonym: "establishment of spindle pole body localization to nuclear envelope" EXACT []

Was there something else to do ? 



Thanks, Pascale
