### ISSUE TITLE
contacts file

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14880]
My bookmark isn't working, did it move?

https://github.com/geneontology/go-ontology/blob/master/curator_group_contacts.tsv

**Comment by pgaudet** [comment]
Hi @ValWood 
The file moved here: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

(go-site repo, where all meta information is meant to be stored. 

Thanks, Pascale

**Comment by ukemi** [comment]
Can we close this one?

**Comment by ValWood** [comment]
Yep I updated my link
