### ISSUE TITLE
OTR: synonyms for GO:0140052 cellular response to oxidised low-density lipoprotein particle stimulus

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14886]
GO:0140052 cellular response to oxidised low-density lipoprotein particle stimulus

Synonyms:
cellular response to ox-LDL particle stimulus
cellular response to oxLDL particle stimulus
cellular response to oxidised LDL particle stimulus
cellular response to oxidized LDL particle stimulus
cellular response to oxidized low-density lipoprotein particle stimulus

Related to #13712

@RLovering 
@paolaroncaglia

**Comment by RLovering** [comment]
I can see these will help a curator find the term

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
I agree with your proposed addition of synonyms too.
