### ISSUE TITLE
NTR: oxidised low-density lipoprotein particle receptor activity

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14885]
PMID:27607416, Figure 5.

Background in #13712

Parent term: GO:0030228 lipoprotein particle receptor activity*
Definition: Combining with an oxidised low-density lipoprotein particle and delivering it into the cell via endocytosis. PMID:27607416, GOC:aruk, GOC:bc
Exact Synonyms: ox-LDL particle receptor activity, oxLDL particle receptor activity, oxidised LDL particle receptor activity, oxidized LDL particle receptor activity, oxidized low-density lipoprotein particle receptor activity
Related Synonyms: oxidised low-density lipoprotein receptor activity, ox-LDL receptor activity, oxLDL receptor activity, oxidised LDL receptor activity, oxidized LDL receptor activity, oxidized low-density lipoprotein receptor activity

*LDL- and oxLDL-related terms should be 'siblings' based on ChEBI
image
![image](https://user-images.githubusercontent.com/16541096/35097058-650979aa-fc46-11e7-88c4-e6887f88e0fa.png)

@paolaroncaglia
@RLovering

**Comment by RLovering** [comment]
Hi Barbara

it would be helpful if you explained what you are proposing here. Are these currently siblings? do these terms exist.

I don't want to have to look up the ontology to try to work out why you are raising a ticket

Thanks

Ruth

**Comment by BarbaraCzub** [comment]
Hi Ruth, 

This is a new term request. I was just reviewing some P2GO tickets pending, and realised that the cellular response term #13712 had been updated from LDL to oxLDL after we discussed this (22nd June 2017 UCL team meeting minutes), but the receptor activity and clearance terms #14884 had not been. They are needed because the paper showed that oxLDL had an effect, but LDL did not. The reference to these terms being siblings is a reminder for me _not_ to make oxLDL a child of LDL, but to follow the same hierarchy as ChEBI, and make them both child terms of the same parent term.

Please let me know, if you have any other questions.

Thanks,
Barbara

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
This request looks good to me too, thanks.
While checking your suggested parent GO:0030228 lipoprotein particle receptor activity, I noticed that the label of its child GO:0005041 low-density lipoprotein receptor activity should be corrected to low-density lipoprotein _particle_ receptor activity. Could you fix that, please? And keep 'low-density lipoprotein receptor activity' as a related synonym. Many thanks.

**Comment by BarbaraCzub** [comment]
Thanks @paolaroncaglia for pointing this out. I'll fix the label and add the synonym.
