### ISSUE TITLE
refine def: glycine import into mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14882]
GO:1904983    
glycine import into mitochondrion

Definition 
The directed movement of glycine across a membrane from cytosol to mitochondrion. PMID:26821380

refine to
GO:1904983    glycine import into mitochondrial matrix
redefine
The process in which a solute is transported from the mitochondrial intermembrane space to the mitochondrial matrix.

See @asangrador  comment from
https://github.com/geneontology/go-annotation/issues/1750#issuecomment-358339508

According to PMID: 28404662:
"Mitochondria possess both outer and inner membranes with differential permeabilities. The outer mitochondrial membrane is permeable to solutes up to ∼5 kDa, while the inner membrane is comparatively impermeable to enable efficient oxidative phosphorylation. Various transporters reside within the inner mitochondrial membrane to overcome its permeability barrier, including transporters required to facilitate the synthesis of heme."

And SLC25 is supposed to be a family of inner mitochondrial membrane transporters. The SLC25A38 member from S. cerevisiae Hem25/YDL119C was detected among these [10930523]. I think that paper is where our annotation came from for MIM.

**Comment by ValWood** [comment]
This probably applies to any of the "mitochondrial carrier" functions because all of these "small molecule transporters" are in the IMM

**Comment by deustp01** [comment]
That change to the definition, "... into mitochondrial matrix" (from "... into mitochondrion") makes all the difference. Certainly we, following textbook views and consistent with PMID: 28404662, have always figured that relatively low-mass stuff finds its way into the mitochondrial intermembrane space spontaneously, but that a protein-mediated molecular function is normally required to get it between that space and the mitochondrial matrix.

**Comment by ValWood** [comment]
Hi  deustp01, it's only specifically for this term

GO:1904983
glycine import into mitochondrion

and other low molecular weight stuff would need to be checked on a case-by-case basis.
Def. not for all import into the mitochondria.

**Comment by ValWood** [comment]
This family (the mitochondrial carriers)
http://www.ebi.ac.uk/interpro/entry/IPR002067
https://www.pombase.org/gene_subset/interpro:IPR023395
appears to be exclusively IMM

**Comment by deustp01** [comment]
Sure. Only noting that based on our anecdotal sample of low mw stuff and annotation standards, the approach is likely to be widely useful: pores but no specific carriers in the outer membrane, specific carriers / pumps / transporters in the inner membrane. And asserting that a function is needed to get to and from the matrix does not necessarily mean that no function is needed to get between the cytosol and the intermembrane space, a distinction that was lost in the earlier phrase "... into mitochondrion".

**Comment by ValWood** [comment]
For the glycine family I checked and all EXP annotations are for this family
SLC25A38 member from S. cerevisiae Hem25/YDL119C

**Comment by ValWood** [comment]
Yes agreed! I didn't even know until today that the outer membrane was  relatively permeable!

**Comment by pgaudet** [comment]
HI @ValWood 
I did think about this before but I wonder about making the more specific terms (import into matrix; I guess this should be done for most solutes? Or do you want to do just glycine for now ?

**Comment by ValWood** [comment]
Lets discuss tomorrow. Easier....

**Comment by pgaudet** [comment]
This is what we currently have : 
x import into the mitochondrion: 
* 'folic acid import into mitochondrion'
*'glycine import into mitochondrion' 
*'RNA import into mitochondrion'
*'tRNA import into mitochondrion'
*'rRNA import into mitochondrion'
* 'pyrimidine nucleotide import into mitochondrion'

all except 'pyrimidine nucleotide import into mitochondrion' already have 'target end location' in the logical definition; I dont think these can really end up anywhere else. 

Surprisingly, 'pyrimidine nucleotide import into mitochondrion' has target end location 'mitochondrial intermembrane space'. However the paper cited mentions transport to the matrix: PMID: 16194150 

So I will 
 [] adjust the textual definitions for the above terms
 [] fix the logical definition for 'pyrimidine nucleotide import into mitochondrion' to make the end location = matrix

@ValWood @deustp01 
Let me know if you see a problem with this plan. 

Thanks, Pascale
