### ISSUE TITLE
NTR: oxidised low-density lipoprotein particle clearance

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14884]
PMID:27607416, Figure 3.

Background in #13712

Parent term: GO:0034381 plasma lipoprotein particle clearance*
Definition: The process in which an oxidised low-density lipoprotein particle is removed from the blood via receptor-mediated endocytosis and its constituent parts degraded. PMID:27607416, GOC:aruk, GOC:bc
Synonyms: ox-LDL particle clearance, oxLDL particle clearance, oxidised LDL particle clearance, oxidized LDL particle clearance, oxidized low-density lipoprotein particle clearance

*LDL- and oxLDL-related terms should be 'siblings' based on ChEBI
![image](https://user-images.githubusercontent.com/16541096/35096600-b91df8ec-fc44-11e7-9e36-9016e50144ce.png)

@paolaroncaglia 
@RLovering

**Comment by RLovering** [comment]
again please explain why this ticket has been created so that I can comment on it

**Comment by BarbaraCzub** [comment]
Hi Ruth, 

This is a new term request. I was just reviewing some P2GO tickets pending, and realised that the cellular response term #13712 had been updated from LDL to oxLDL after we discussed this (22nd June 2017 UCL team meeting minutes), but the receptor activity #14885 and clearance terms had not been. They are needed because the paper showed that oxLDL had an effect, but LDL did not. The reference to these terms being siblings is a reminder for me _not_ to make oxLDL a child of LDL, but to follow the same hierarchy as ChEBI, and make them both child terms of the same parent term.

Please let me know, if you have any other questions.

Thanks,
Barbara

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
Looks good to me, thanks.
