### ISSUE TITLE
iron assimilation and transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14892]
We have a term "iron assimilation" which always bothers me.

We have to use it for the  transmembrane transport of iron when it needs to be reduced before uptake. This means that this  transporter is not  annotated as part of transmembrane transport unless you make an additional annotation.

I'm not sure that we need this term at all.

Can't we just call this  "iron ion transmembrane transport"  to me the reductase is part of the transmembrane transport process?...in the same way that  other 
activities 
like
https://www.pombase.org/gene/SPCC965.06 (reductase)
https://www.pombase.org/gene/SPBC27B12.07 (we don't know how)
https://www.pombase.org/gene/SPAC1F8.02c cell-surface heme aquisition protein

What  do you think? does that seem odd?

**Comment by RLovering** [comment]
I agree, I had a student working on iron transport and he never identified this term :)

**Comment by pgaudet** [comment]
Useful references:
https://www.sciencedirect.com/science/article/pii/S1367593113000203

**Comment by RLovering** [comment]
Hi
I had a student who annotated iron homeostasis as regulation of this seems to be important in Cardiovascular disease.

His thesis has a summary:In order to understand cellular iron ion homeostasis, it is important to firstly review the mechanism by which iron is taken up by cells, as presented in figure 2. One of the main proteins involved in this process is transferrin, which circulates in the blood (Ganz, 2013). When blood plasma is in an iron-rich state, diferric transferrin (holotransferrin) binds to transferrin receptor 1 (TFRC) (Morgan and Laurell, 1963; Morgan and Appleton, 1969; Moos, 2002; Aisen, 2004; Ganz, 2013). The holotransferrin/TFRC assembly is then endocytosed into a clathrin-coated pit, assisted by AP2 (an adaptor protein complex) (Conner and Schmid, 2003) and internalises to an endosome (Aisen, 2004). The lowered pH in the endosome (~5.6) facilitates iron release from transferrin, which returns to the cell surface (Qian et al., 2002). The iron (in its ferrous form Fe2+) then crosses the endosomal membrane through DMT1 (Fleming et al., 1998). Iron in the cytosol is used as a cofactor for many chemical reactions, or stored as ferritin (Qian et al., 2002). (figure hopefully below).

Transferrin, P02787, which circulates in the blood I think is an Iron transporter. 

If not what should it's MF be?

![screen shot 2018-02-23 at 10 10 01](https://user-images.githubusercontent.com/12080010/36589003-c509b642-1881-11e8-99a7-d171c6f73abf.png)

**Comment by ValWood** [comment]
Hi Ruth
It's an "iron sulfur cluster carrier"
https://www.ebi.ac.uk/QuickGO/term/GO:0140132
It isn't involved in "directed movement" so it isn't a "transporter"
but it is a "carrier" part_of  "iron sulfur cluster transport"

Val

**Comment by deustp01** [comment]
I don't think iron-sulfur works because it's plain Fe(2+) CHEBI:29033, not an iron-sulfur cluster (CHEBI:30408) that's involved here.
Would it be useful to think of ferritin protein as having the same function with respect to extracellular iron as albumin does for extracellular bile acids and free fatty acids?

**Comment by ValWood** [comment]
Ah ok, some term under here though
https://www.ebi.ac.uk/QuickGO/term/GO:0140104

**Comment by RLovering** [comment]
Hi
so when I looked at the Transferrin, P02787 annotations we had not annotated it to a transporting function. (hooray). However when I tried to create the annotation GO:0140104   molecular carrier activity I was not able to do so because of : Restrictions
This term should not be used for direct annotation. See comment below for further information.
Comments
https://github.com/geneontology/go-ontology/issues/14221
I tried to add more specific information but this was not allowed with Protein2GO.
Does this mean that there are going to be individual terms for each type of molecular carrier? 
Or should I request metal ion carrier activity?
Or should I request that curators can use GO:0140104   molecular carrier activity as long as they specify the location and the object carried.

Thanks for the help with this, it is obviously not my area and I don't want to get this wrong again.

Ruth
![screen shot 2018-02-23 at 19 10 16](https://user-images.githubusercontent.com/12080010/36612285-183c12aa-18ce-11e8-9427-612db62b46ad.png)

**Comment by ValWood** [comment]
Well, this raises a question

Currently
metallochaperone and iron chaperone activity
https://www.ebi.ac.uk/QuickGO/term/GO:0034986

are defined in terms of delivery to compartments. Perhaps this should be broadened for delivery to cells?

**Comment by ValWood** [comment]
Note that the BHF annotations to this term  "iron chaperone activity" include frataxin, that would definitely be   "iron sulfur cluster carrier"

(but a grouping term for iron-containing carriers would  be nice here for curators to find things)

**Comment by ValWood** [comment]
Ruth new terms may be needed. The terms existed before but the arrangement is very new...part of MF refactoring.
v

**Comment by RLovering** [comment]
OK so I am completely blind it seems when looking at these terms. 

Added to frataxin,  "iron sulfur cluster carrier.
But it also seems to just bind iron (ferrous 2+) and is involved in heme biosynthesis. So I will leave the iron chaperone activity annotation.

wrt Transferrin, P02787 it does 'assist in the delivery of Fe3+ to the endosome via binding to the transferrin receptor. So maybe the definition of GO:0034986 iron chaperone activity: Assists in the delivery of iron ions to target proteins or compartments. is OK?

I will add this term to this record now, I have found a couple of papers that refer to transferrin as a metallochaperone eg https://pubs.acs.org/doi/abs/10.1021/acs.inorgchem.7b00372?journalCode=inocaj 

Thanks

Ruth

**Comment by ValWood** [comment]
I did not know until today that iron could be endocytosed, although  @pgaudet  mentioned it last week, I was still convinced that endocytosis  was only  regulating transporter localization...

**Comment by dianeoinglis** [comment]
Siderophores are secondary metabolites produced by fungi and some bacteria that bind iron in the environment and are then taken into a cell by transport. This process is often referred to as 'iron assimilation' in siderophore literature.
Diane

**Comment by deustp01** [comment]
I'm not expert at all here but at a glance it looks like frataxin binds Fe ions and enables their delivery to the place where sulfur is also independently being delivered and where iron-sulfur complexes form as a result, so frataxin function has a role in iron-sulfur assembly process but does not bind or transport the complex: http://www.uniprot.org/citations/12785837 - "Holo frataxin ... mediate[s] the transfer of iron from holo frataxin to nucleation sites for [2Fe-2S] cluster formation on ISU." So a iron sulfur cluster carrier annotation looks wrong.

**Comment by RLovering** [comment]
Thank you Peter. This makes sense, I have deleted the  "iron sulfur cluster carrier" and  "iron sulfur cluster binding" terms.

**Comment by pgaudet** [comment]
For specific forms of iron, I will rename simply 'iron import' (the iron form should be captured in the MF annotation): 
* GO:0098707 ferrous iron import across plasma membrane -> iron import across plasma membrane
* GO:0098706 ferric iron import across cell outer membrane ->  iron import across cell outer membrane

**Comment by RLovering** [comment]
Hi Pascale

if you are getting rid of the iron specific form terms will you also get rid of terms like GO:0072512 trivalent inorganic cation transport, otherwise we would need to annotate to this term and to the iron transport term?

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

Yes, the plan is to get rid of the specific form of iron in the BP, only keeping them in the MF. Does that make sense ? 

I will commit what I have done so far. There are 4 types of iron transport: 
- transmembrane 
- endocytic 
- siderophore-mediated
- reductive iron assimilation (in which Fe3+ is converted into Fe2+ and then transported by  TM transport). 

Does that seem OK to you ? 

Thanks, Pascale

@Antonialock I think you have also looking into this.

**Comment by ValWood** [comment]
@Antonialock  has been looking at iron sulphur cluster biosynthesis

**Comment by pgaudet** [comment]
- [ ] GO:0033212 changed label iron assimilation to iron import into cell

**Comment by pgaudet** [comment]
Here are the changes I made: 


Term |   | Change |   |   |  
-- | -- | -- | -- | -- | --
GO:0015682 | ferric iron transport | MERGE INTO | GO:0006826 | iron ion transport
GO:0015684 | ferrous iron transport | MERGE INTO | GO:0006826 | iron ion transport
GO:0097286 | iron ion import | MERGE INTO | GO:0006826 | iron ion transport
GO:0070627 | ferrous iron import | MERGE INTO | GO:0033212 | iron import into cell
GO:0042928 | ferrichrome transport | RENAMED | ferrichrome import into cell |  
  |   | CHANGED DEF | NEW: A process in which ferrichrome   is transported into the cell by specific cell surface receptors. Ferrichromes   are any of a group of growth-promoting Fe(III) chelates formed by various   genera of microfungi. They are homodetic cyclic hexapeptides made up of a   tripeptide of glycine (or other small neutral amino acids) and a tripeptide   of an N'acyl-N4-hydroxy-L-ornithine. (OLD: The directed movement of a   ferrichrome into, out of or within a cell, or between cells, by means of some   agent such as a transporter or pore. Ferrichromes are any of a group of   growth-promoting Fe(III) chelates formed by various genera of microfungi.   They are homodetic cyclic hexapeptides made up of a tripeptide of glycine (or   other small neutral amino acids) and a tripeptide of an   N'acyl-N4-hydroxy-L-ornithine.)
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
GO:0015685 | ferric-enterobactin transport | RENAMED | ferric-enterobactin import into cell
  |   | CHANGED DEF | NEW: A process in which   ferric-enterobactin, the iron-bound form of the siderophore enterobactin, is   transported into the cell by specific cell surface receptors. (OLD: The   directed movement of ferric-enterobactin into, out of or within a cell, or   between cells, by means of some agent such as a transporter or pore.)
  |   |   |   |   |  
GO:0015686 | ferric triacetylfusarinine C transport | RENAMED | ferric triacetylfusarinine C import   into cell
GO:0015687 | ferric-hydroxamate transport | RENAMED | ferric-hydroxamate import into cell
  |   | CHANGED DEF | NEW: A process in which   ferric-hydroxamate, the iron-bound form of the iron chelator hydroxamate, is   transported into the cell by specific cell surface receptors. (OLD: The   directed movement of ferric-hydroxamate into, out of or within a cell, or   between cells, by means of some agent such as a transporter or pore.)
  |   |   |   |   |  
  |   |   |   |   |  
GO:0015688 | iron chelate transport | MERGE INTO | siderophore-dependent iron import   into cell
  |   |   |   |   |  
GO:0033212 | iron import into cell | CHANGED DEF | NEW: The directed movement of iron   ions from outside of a cell into the cytoplasmic compartment. This may occur   via transport across the plasma membrane or via endocytosis. (OLD: The   directed movement of iron ions from outside of a cell into the cytoplasmic   compartment. This may occur via transport across the plasma membrane or via   endocytosis.)
  |   |   |   |   |  
GO:1900390 | regulation of iron ion import | MERGE INTO | GO:0034756 | regulation of iron ion transport
  |   |   |   |   |  
GO:1903874 | ferrous iron transmembrane transport | MERGE INTO | GO:0034755 | iron ion transmembrane transport

**Comment by pgaudet** [comment]
@ValWood @RLovering @hdrabkin @dsiegele
Does that look right to you ? 

Thanks; Pascale

**Comment by pgaudet** [comment]
Changes: 


Term |   | Change |   |   |  
-- | -- | -- | -- | -- | --
GO:0015682 | ferric iron transport | MERGE INTO | GO:0006826 | iron ion transport
GO:0015684 | ferrous iron transport | MERGE INTO | GO:0006826 | iron ion transport
GO:0097286 | iron ion import | MERGE INTO | GO:0006826 | iron ion transport
GO:0070627 | ferrous iron import | MERGE INTO | GO:0033212 | iron import into cell
GO:0042928 | ferrichrome transport | RENAMED | ferrichrome import into cell |  
  |   | CHANGED DEF | NEW: A process in which ferrichrome   is transported into the cell by specific cell surface receptors. Ferrichromes   are any of a group of growth-promoting Fe(III) chelates formed by various   genera of microfungi. They are homodetic cyclic hexapeptides made up of a   tripeptide of glycine (or other small neutral amino acids) and a tripeptide   of an N'acyl-N4-hydroxy-L-ornithine. (OLD: The directed movement of a   ferrichrome into, out of or within a cell, or between cells, by means of some   agent such as a transporter or pore. Ferrichromes are any of a group of   growth-promoting Fe(III) chelates formed by various genera of microfungi.   They are homodetic cyclic hexapeptides made up of a tripeptide of glycine (or   other small neutral amino acids) and a tripeptide of an   N'acyl-N4-hydroxy-L-ornithine.)
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
GO:0015685 | ferric-enterobactin transport | RENAMED | ferric-enterobactin import into cell
  |   | CHANGED DEF | NEW: A process in which   ferric-enterobactin, the iron-bound form of the siderophore enterobactin, is   transported into the cell by specific cell surface receptors. (OLD: The   directed movement of ferric-enterobactin into, out of or within a cell, or   between cells, by means of some agent such as a transporter or pore.)
  |   |   |   |   |  
GO:0015686 | ferric triacetylfusarinine C transport | RENAMED | ferric triacetylfusarinine C import   into cell
GO:0015687 | ferric-hydroxamate transport | RENAMED | ferric-hydroxamate import into cell
  |   | CHANGED DEF | NEW: A process in which   ferric-hydroxamate, the iron-bound form of the iron chelator hydroxamate, is   transported into the cell by specific cell surface receptors. (OLD: The   directed movement of ferric-hydroxamate into, out of or within a cell, or   between cells, by means of some agent such as a transporter or pore.)
  |   |   |   |   |  
  |   |   |   |   |  
GO:0015688 | iron chelate transport | MERGE INTO | siderophore-dependent iron import   into cell
  |   |   |   |   |  
GO:0033212 | iron import into cell | CHANGED DEF | NEW: The directed movement of iron   ions from outside of a cell into the cytoplasmic compartment. This may occur   via transport across the plasma membrane or via endocytosis. (OLD: The   directed movement of iron ions from outside of a cell into the cytoplasmic   compartment. This may occur via transport across the plasma membrane or via   endocytosis.)
  |   |   |   |   |  
GO:1900390 | regulation of iron ion import | MERGE INTO | GO:0034756 | regulation of iron ion transport
  |   |   |   |   |  
GO:1903874 | ferrous iron transmembrane transport | MERGE INTO | GO:0034755 | iron ion transmembrane transport
  |   |   |   |   |

**Comment by ValWood** [comment]
@Antonialock

**Comment by pgaudet** [comment]
@ValWood @RLovering @hdrabkin @dsiegele @Antonialock
I would like to merge these changes today (since it's a lot; conflicts would be difficult to fix). 
Let me know if you'd like more time to check. 

Thanks, Pascale

**Comment by dsiegele** [comment]
Hi Pascale, Your changes look OK to me.  thank you!  Debby

**Comment by hdrabkin** [comment]
Seems good

**Comment by ValWood** [comment]
Sounds Ok to me .
@Antonialock ?

**Comment by Antonialock** [comment]
I don't feel confident enough to say that all the changes look ok. If it is helpful I don't have any objections.

**Comment by RLovering** [comment]
I have no objections, sorry to be late
