### ISSUE TITLE
TPV:  rRNA export from nucleus is under TRANSMEMBRANE TRANSPORT

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14891]
GO:0006407 - rRNA export from nucleus

can you remove "transmembrane transport" parent. Its mucking up the slims.

Cheers

**Comment by deustp01** [comment]
Aside from that, isn't the parentage also wrong because traversing the nuclear pore is not transmembrane transport?

**Comment by ValWood** [comment]
Yes, that is why it is wrong ;)

**Comment by ValWood** [comment]
i.e.  nucleocytoplasmic transport is not transmembrane transport is why it is wrong. Affecting slims is why it is urgent ;)

(I know I need to be more precise!)
