### ISSUE TITLE
Proposal to obsolete 'regulation of transcription during mitotic cell cycle' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14896]
Hello, 

The proposal has been made to obsolete 'GO:0045896 regulation of transcription during mitotic cell cycle' and its children: 
GO:0007068 'negative regulation of transcription during mitotic cell cycle'
GO:0045897 'positive regulation of transcription during mitotic cell cycle'

GO:0046017'regulation of transcription from RNA polymerase I promoter during mitotic cell cycle'
GO:0046021'regulation of transcription from RNA polymerase II promoter during mitotic cell cycle'
GO:0046023'regulation of transcription from RNA polymerase III promoter during mitotic cell cycle'

GO:0007069'negative regulation of transcription from RNA polymerase I promoter during mitotic cell cycle'
GO:0007070'negative regulation of transcription from RNA polymerase II promoter during mitotic cell cycle' GO:0007071'negative regulation of transcription from RNA polymerase III promoter during mitotic cell cycle'

GO:0046018'positive regulation of transcription from RNA polymerase I promoter during mitotic cell cycle'
GO:0046022'positive regulation of transcription from RNA polymerase II promoter during mitotic cell cycle'
GO:0046024 'positive regulation of transcription from RNA polymerase III promoter during mitotic cell cycle'

The reason for obsoletion is that 'during' should be captured using an annotation extension. There are very few 'during' terms in the ontology. 

There are 15 manual annotations (13 EXP + 2 TAS) to 3 of these 12 terms. Annotations should be rehoused to the parent, or probably to the term 'GO:0006357 regulation of transcription from RNA polymerase II promoter' 

Contributors of these annotations are 

MGI @ukemi 
SGD @srengel 
UniProt @ggeorghiou 
BHF-UCL @RLovering 

Also tagging @ValWood since she suggested this, and @krchristie and @thomaspd for general input. 

Annotations are below: 
id | protein |   | GO term | extension | Contributor | Organism | Evidence | Reference | Date
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
MGI:MGI:1202876 | transcription factor 7 like 1 (T   cell specific, HMG box) | GO:0046022 | {"relationship": {"relation": [{"id":   "RO:0002211", "label": "regulates"},   {"id": "BFO:0000066", "label": "occurs   in"}], "id": "EMAPA:16728", "label":   "EMAPA:16728"}}\|{"relationship": {"relation":   [{"id": "RO:0002211", "label":   "regulates"}, {"id": "BFO:0000066",   "label": "occurs in"}], "id":   "CL:0000082", "label": "epithelial cell of   lung"}}\|{"relationship": {"relation":   [{"id": "GOREL:0000015", "label":   "has_regulation_target"}], "id":   "MGI:MGI:88180", "label":   "MGI:MGI:88180"}}\|{"relationship": {"relation":   [{"id": "RO:0002211", "label":   "regulates"}, {"id": "BFO:0000066",   "label": "occurs in"}], "id":   "EMAPA:16728", "label":   "EMAPA:16728"}}\|{"relationship": {"relation":   [{"id": "RO:0002211", "label":   "regulates"}, {"id": "BFO:0000066",   "label": "occurs in"}], "id":   "CL:0000082", "label": "epithelial cell of   lung"}}\|{"relationship": {"relation":   [{"id": "GOREL:0000015", "label":   "has_regulation_target"}], "id":   "MGI:MGI:97357", "label": "MGI:MGI:97357"}} | MGI | NCBITaxon:10090 | IDA | MGI:MGI:3582095\|PMID:15907834 | 20050912
SGD:S000005645 | Serine kinase involved in cell cycle   regulation and rDNA integrity | GO:0007069 | {"relationship": {"relation": [{"id":   "RO:0002092", "label": "happens_during"}],   "id": "GO:0000090", "label": "mitotic   anaphase"}} | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000179822\|PMID:25851096 | 20150417
SGD:S000000364 | Cyclin-dependent kinase (CDK)   catalytic subunit | GO:0007070 | {"relationship": {"relation": [{"id":   "GOREL:0000752", "label": "has_direct_input"}],   "id": "UniProtKB:P34161", "label":   "UniProtKB:P34161"}} | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000147401\|PMID:22056777 | 20150716
SGD:S000000316 | General transcriptional co-repressor | GO:0007070 |   | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000050114\|PMID:9560430 | 20120224
SGD:S000005805 | Component of the Sum1p-Rfm1p-Hst1p   complex | GO:0007070 |   | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000072806\|PMID:12612074 | 20130427
SGD:S000000680 | General repressor of transcription | GO:0007070 |   | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000050114\|PMID:9560430 | 20120224
SGD:S000002718 | Transcriptional repressor that   regulates middle-sporulation genes | GO:0007070 |   | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000040525\|PMID:10562556 | 20110801
SGD:S000002615 | Rpd3L histone deacetylase complex   subunit | GO:0007070 |   | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000047047\|PMID:8618927 | 20110802
SGD:S000002615 | Rpd3L histone deacetylase complex   subunit | GO:0007070 |   | SGD | NCBITaxon:559292 | IMP | SGD_REF:S000054292\|PMID:7926768 | 20110802
FB:FBgn0017430 | Negative elongation factor E | GO:0007070 |   | UniProt | NCBITaxon:7227 | IDA | FB:FBrf0159697\|PMID:12782658 | 20031219
FB:FBgn0010416 | TH1 |   | GO:0007070 |   | UniProt | NCBITaxon:7227 | IDA | FB:FBrf0159697\|PMID:12782658 | 20031219
UniProtKB:Q14587 | Zinc finger protein 268 | GO:0046022 |   | UniProt | NCBITaxon:9606 | IMP | PMID:23091055 | 20130927
UniProtKB:P06400 | Retinoblastoma-associated protein | GO:0007070 |   | BHF-UCL | NCBITaxon:9606 | TAS | PMID:19149898 | 20130513
UniProtKB:P51532 | Transcription activator BRG1 | GO:0007070 |   | BHF-UCL | NCBITaxon:9606 | TAS | PMID:19149898 | 20130513

Thanks, Pascale

**Comment by ValWood** [comment]
There should not have been a link to the mitotic cell cycle for this term. It is not part_of the cell cycle. It is just for transcription which occurs *during* the  mitotic cell cycle. 

There is another term for transcription "involved in" the mitotic cell cycle.

I'm not even sure that the "transition" is regulated by transcription. Transcription only provides the gene products required at the correct time, but does not usually regulate the transition itself which is regulated by subsequent signals from signalling pathways. The regulation of the transition is post-translational (at least in fission yeast). I.e the transcription is required for the cell cycle transition, but is not regulating it. The situation in budding yeast is slightly different because there is a positive feedback loop to produce more cyclins. 

You need to be careful connecting transcription to cell cycle transition regulation, as this is often only a "readout". You can probably say that the transcription is regulating the cell cycle, but it isn't  likely to be regulating the transition.

v

**Comment by srengel** [comment]
i fixed the SGD annotations.
changed 7070 to 122 happens_during 278 mitotic cell cycle.
changed 7069 to 16479, and it already had happens_during 90 mitotic anaphase.

**Comment by pgaudet** [comment]
Hi @RLovering 

@ukemi says that the property chain would not infer 'part of' from 'happens during' (David please correct me if this is not right!) 

That being said, with respect to the choice of annotation: IMO you should try to represent the biology rather than fitting to a model - what I mean is that I dont know what 'regulation of gene expression during mitosis' means: does it *happen* during mitosis, as the relation indicates ? If that's the case, then most genes are expressed during some part of the cell cycle, is this really informative ? Rb certainly regulates cell cycle transition, this is what really should be captured. 

Thanks, Pascale

**Comment by ValWood** [comment]
Agreed, see comment above happens_during is not involved _in

**Comment by RLovering** [comment]
Hi
sorry I cannot claim to be a cell cycle expert so please advise on how to capture the following summary (PMID: 19149898): In the presence of p16INK4a, pRb remains hypophosphorylated and forms active pRb-E2F transcriptional repressor complexes that silence genes required for S-phase entry. Consequently, ectopic expression of p16INK4a promotes pRb-dependent G1 cell cycle arrest and senescence.

RB1 P06400 is already annotated to negative regulation of G1/S transition of mitotic cell cycle so I have now created the annotation:
RB1 GO:0000122 negative regulation of transcription by RNA polymerase II AE part_of negative regulation of G1/S transition of mitotic cell cycle 
Or should this be:
RB1 GO:0000122 negative regulation of transcription by RNA polymerase II AE negatively regulates G1/S transition of mitotic cell cycle 
and 
GO:0071930 negative regulation of transcription involved in G1/S transition of mitotic cell cycle in my mind this is effectively the same term but is this term going to stay?
Let me know if you think this is appropriate annotation for RB1 protein, and I will modify annotations.
Thanks
Ruth

**Comment by RLovering** [comment]
I have updated P51532 as well so please go ahead with merge

**Comment by pgaudet** [comment]
Hi @RLovering 
WRT 

> RB1 P06400 is already annotated to negative regulation of G1/S transition of mitotic cell cycle so I have now created the annotation:
RB1 GO:0000122 negative regulation of transcription by RNA polymerase II AE part_of negative regulation of G1/S transition of mitotic cell cycle
Or should this be:
RB1 GO:0000122 negative regulation of transcription by RNA polymerase II AE negatively regulates G1/S transition of mitotic cell cycle

Aren't these two statements equivalent ? @vanaukenk  


> GO:0071930 negative regulation of transcription involved in G1/S transition of mitotic cell cycle in my mind this is effectively the same term but is this term going to stay?
If it's useful it can stay. Personally I dont this this is a process. @thomaspd 's proposed new definition of BP in #14899 might help: "a biological process represents a specific objective that the organism is genetically “programmed” to achieve. Each biological process is often described by its outcome or ending state, e.g., the biological process of cell division results in the creation of two daughter cells (a divided cell) from a single parent cell. A biological process is accomplished by a particular set of molecular processes carried out by specific gene products, often in a highly regulated manner and in a particular temporal sequence."

Terms such as  "GO:0071930 negative regulation of transcription involved in G1/S transition of mitotic cell cycle" seem to me to be grouping terms of proteins having the same function and playing a role in the same BP - ie unlike glycolysis, for example, where you'll get all enzymes involved in the pathway, in terms such as  "GO:0071930 negative regulation of transcription involved in G1/S transition of mitotic cell cycle" you'll get proteins involved in multiple pathways, but that (a) regulate tx and (b) play a role in G1/S transition. This is why those ones seem better captured in GO-CAM models. 

What do you think ? 

Pascale

**Comment by ValWood** [comment]
Although the G2/M transition is not *directly* regulated by transcription (of course all of the gene products need to be there, but all of the regulation is *post translational*). 
G1/S is a bit different in some species.

I don't know much about it because  G1 is so short in pombe it is not much studied, but from what I understand, cerevisiae G1/S is directly regulated transcriptionally. Attainment of a threshold  level of the active CDK seems to absolutely require  a positive feedback loop  acting through trancription which increases cyclin level to reach the threshold required for the transition to occur. 
In fact the current definition  of G1/S is clearly based on  S. cerevisiae:


"The process begins with the build up of G1 cyclin-dependent kinase (G1 CDK), resulting in the activation of transcription of G1 cyclins. The process ends with the positive feedback of the G1 cyclins on the G1 CDK which commits the cell to S phase, in which DNA replication is initiated."

I'm a bit confused by the negative regulation term though....
