### ISSUE TITLE
mitochondrial transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14908]
Hello, 

There are 3 terms describing mitochondrial transcription factors, but as far as I can tell there is only one or two specific transcription factor (in all eukaroytoes). So I plan to merge: 

-GO:0001144 'transcription factor activity, mitochondrial proximal promoter sequence-specific binding' and
. GO:0001143 'transcription factor activity, mitochondrial RNA polymerase core promoter sequence-specific DNA binding'
-> Merge into parent (GO:0001142 'mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding')
see also new reference (3D structure): PMID:29149603

---
As well, for  GO:0001146 'transcription factor activity, mitochondrial RNA polymerase terminator site sequence-specific binding', there is no evidence that the function exists, see PMID:29033127; 
mitochondrial termination seems spontaneous in the absence of anti-termination factor, see PMID:25690892 (and also PMID:29033127). Therefore to avoid any confusion I plan to obsolete the term. 

There are no annotations to either of these 4 terms. 

@krchristie @ValWood @thomaspd do you have any feedback before I proceed? 

Thanks, Pascale

**Comment by ValWood** [comment]
I agree.  
PomBase only have 2 annotations to mitochondrial transcription. 

SPAC1002.08c | mitochondrial RNA polymerase specificity factor, methyltransferase Mtf1
rpo41 | SPAC26H5.12 | mitochondrial RNA polymerase Rpo41

I used
GO:0001018 - mitochondrial promoter sequence-specific DNA binding
for both...

**Comment by pgaudet** [comment]
Obsoletion notice sent for GO:0001146

>Dear all, 

>The proposal has been made to obsolete ' GO:0001146 transcription factor activity, mitochondrial RNA polymerase terminator site sequence-specific binding’. 

>The reason for obsoletion is that there is no evidence that the function exists, see PMID:29033127; mitochondrial termination seems spontaneous in the absence of anti-termination factor, see PMID:25690892 (and also PMID:29033127). Therefore to avoid any confusion I plan to obsolete the term. There are no annotations or mappings to this term. 

>Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/14908. 

>We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on January 31, 2018. Unless objections are received by January 31, 2018  we will assume that you agree to this change. 

>Thanks, Pascale

**Comment by pgaudet** [comment]
This is what I did for the merge: 
(1) Merge: 
-GO:0001144 'transcription factor activity, mitochondrial proximal promoter sequence-specific binding' and
. GO:0001143 'transcription factor activity, mitochondrial RNA polymerase core promoter sequence-specific DNA binding'
-> Merge into parent (GO:0001142 'mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding') 
-> Renamed: ‘mitochondrial transcription factor activity’
(2) Made ‘mitochondrion promoter specificity activity’ a child
-> renamed from mitochondrial RNA polymerase promoter specificity activity

Question: Do we need to have 'mitochondrion specific transcription factor activity' as a child of  ‘mitochondrial transcription factor activity’?

**Comment by ValWood** [comment]
> Question: Do we need to have 'mitochondrion specific transcription factor activity' as a child of ‘mitochondrial transcription factor activity’?

I don't think so, 

but note
Merge into parent (GO:0001142 'mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding')
isn't the correct ID

**Comment by pgaudet** [comment]
@ValWood 

> Merge into parent (GO:0001142 'mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding')

what do you mean ?

**Comment by ValWood** [comment]
ignore that, user error

**Comment by ValWood** [comment]
I'm still confused what we would annotate to these.

I used

DNA-directed 5'-3' RNA polymerase activity
for
https://www.pombase.org/gene/SPAC26H5.12

and 

methyltransferase activity
for
https://www.pombase.org/gene/SPAC1002.08c

 what is the transcription factor term for?

**Comment by ValWood** [comment]
I'm  still confused what the term
GO:0001142    mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding

would be used to annotate

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0001142

it has 3 annotations. One of them
http://www.uniprot.org/uniprot/Q23272  I'm not sure that this acts as a transcription factor in the mitochondria? The description says it upregulates mitochondrial gene expression by regulating 
"complexes via the up-regulation of chaperone and assembly factor genes" but these are nuclear transcribed.

This is the only experimental annotation.....

**Comment by pgaudet** [comment]
Yeah I disputed Q23272 , but the paper does state that "Mitochondrial ATFS-1 binds mtDNA and limits accumulation of mtDNA-encoded mRNAs" - it seemed unusual but correct. What do you think ? 

Thanks, Pascale

**Comment by krchristie** [comment]
From this quote from the paper (PMID:25773600) used for the experimental annotation of ATFS-1:

> ATFS-1 binding to mtDNA was specifically enriched during mitochondrial stress (Figure 5B), which required ATFS-1-specific antibodies (Figure 5B) and was reduced in atfs-1(tm4525) worms (Figure S5B). While the regulatory segments of C. elegans mtDNA have not been extensively characterized, ATFS-1 binding was most enriched in an A-T-rich segment lacking protein or RNA coding genes (Figure 5A) suggested to be the regulatory region or D-loop (Bratic et al., 2010). Interestingly, this segment contained a UPRmtE in the region where ATFS-1 binding was most enriched (Figures 5A and 5C). 

it does seem to me that it is correct for the protein to be annotated to the term "mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding" (GO:0001142).


In addition, I think that this GO term is also appropriate for TFAM (though the mouse annotations do not currently reflect this and I will check some papers to see if I can make mouse annotations).

Here's a quote from: Kang I, Chu CT, Kaufman BA. The mitochondrial transcription factor TFAM in
neurodegeneration: Emerging evidence and mechanisms. FEBS Lett. 2018 Jan 24. PMID:29364506

> **The role of TFAM in regulating mtDNA replication, transcription, and packaging**
> TFAM was discovered as a mitochondrial protein that stimulated transcription of model
templates in mitochondrial extracts [39].  TFAM is a nuclear-encoded protein that is
synthesized in the cytoplasm and imported into the mitochondria [40]. The protein
contains two high mobility group (HMG) box domains that insert into the DNA minor groove
on the light strand promoter (LSP), heavy strand promoter 1 (HSP1), or non-specific
regions of the mtDNA [41-43]. TFAM-binding cause s a distortion of the mtDNA and result s
in DNA bending [42-46].  This distortion enables the specific binding of POLRMT
(mitochondrial RNA polymerase) to the start site, where TFAM binds to the N-terminus of
POLRMT to recruit TFB2M (mitochondrial Transcription Factor 2) while maintaining an open
DNA complex arrangement that enables productive transcription initiation [47-51]

**Comment by krchristie** [comment]
@pgaudet - Regarding your plan to obsolete this term:

> As well, for GO:0001146 'transcription factor activity, mitochondrial RNA polymerase terminator site sequence-specific binding', there is no evidence that the function exists, see PMID:29033127;
mitochondrial termination seems spontaneous in the absence of anti-termination factor, see PMID:25690892 (and also PMID:29033127). Therefore to avoid any confusion I plan to obsolete the term.

The papers you cite do indicate that TEFM binds the mitochondrial termination site and promotes elongation through it, i.e. antitermination. If you obsolete this term, how do you plan to represent this activity of binding to the terminators and promoting transcription elongation?

**Comment by pgaudet** [comment]
Hello,


What about this: 

(1) Merge
- 'GO:0001142 mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding'
-- 'GO:0001144 transcription factor activity, mitochondrial proximal promoter sequence-specific binding'
-- 'GO:0001143 transcription factor activity, mitochondrial RNA polymerase core promoter sequence-specific DNA binding'

-- GO:0034246 mitochondrial RNA polymerase promoter specificity activity"

into the parent above 'mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding', and rename 
'mitochondrial sequence-specific DNA binding transcription factor activity'

(2) Merge "GO:0001146 transcription factor activity, mitochondrial RNA polymerase terminator site sequence-specific binding" (0 annotations)  into "GO:0001145 mitochondrial RNA polymerase termination site sequence-specific DNA binding" (0 annotations) 


(3) If needed for MTF1 we can add a new BP "transcriptional open complex formation at mitochondrial promoter"

@krchristie Would that work? 

Thanks, Pascale

**Comment by pgaudet** [comment]
update definition GO:0001145 mitochondrial RNA polymerase termination site sequence-specific DNA binding: to "Interacting selectively and non-covalently with a DNA sequence that controls mitochondrial transcriptional termination."

**Comment by krchristie** [comment]
Hi @pgaudet 

I think this sounds OK, provided that it includes moving the term GO:0034246 (currently called "mitochondrial RNA polymerase promoter specificity activity") to no longer be under GO:0000996 "promoter selection factor activity"

I can't really tell from this where GO:0034246 will be in your plan.

-K

**Comment by pgaudet** [comment]
Hi @krchristie 
yes I renamed the term to 'mitochondrial sequence-specific DNA binding transcription factor activity' 

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet - I was really wondering what parentage this term is going to have, since it shouldn't be under the 'promoter selection factor activity' term.

**Comment by pgaudet** [comment]
No, I moved it. 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/4782928/37607031-3a733656-2b97-11e8-98f6-ecf07f2c24fc.png">

**Comment by krchristie** [comment]
Perfect :) Thank you
