### ISSUE TITLE
GO-MFOEM compatibility: Definition of GO_0007613 (memory) revision?

### ISSUE THREAD

**Issue by matentzn** [geneontology/go-ontology#14913]
I am trying to align a number of ontologies with phenotypes relevant to neurobiology. I am encountering this issue:

"memory" according to GO is a subclass of "memory or learning" which, in turn, is a descendant of "process" and "occurrent". While this appears certainly true for "learning" I intuitively (without being a neurobiologist), feel that "memory" is more something of a continuant -> a feeling that MFOEM ([Emotion ontology](https://github.com/jannahastings/emotion-ontology)) appears to share. For the sake of compatibility, do you think you might be willing to revise your definition? For now, removing the assertion that memory is a subclass of "memory or learning" would do, but in the long run, the ontologically more correct way to fix this would be to remove all restrictions on memory or learning, and add them onto "learning" and "memory" instead. Or alternatively, provide me with a good argument for the MFOEM people to revise their interpretation. Many thanks.

**Comment by ukemi** [comment]
The definition of memory is 'The activities involved in the mental information processing system that receives (registers), modifies, stores, and retrieves informational stimuli. The main stages involved in the formation and retrieval of memory are encoding (processing of received information by acquisition), storage (building a permanent record of received information as a result of consolidation) and retrieval (calling back the stored information and use it in a suitable way to execute a given task). ' So although the primary string for the term name is memory and can be confused with the continuant of 'a memory'. The term actually refers more to 'remembering'. However that string as the primary term name is a bit clunky. I think our definition is ok, maybe rename the term to 'memory process'? I don't think 'formation of a memory' will work becasue it would also include processes involved in retention.

**Comment by ukemi** [comment]
Here is the full description of the term.

http://amigo.geneontology.org/amigo/term/GO:0007613

**Comment by matentzn** [comment]
Thanks @ukemi ! I got fooled by the label as well, but I agree now ith your assessment. I have asked the Mental Functioning Ontology people now for a revision instead. Thanks for the help, the ticket can be closed, unless you want to use it to propose an alternative label for the class.
