### ISSUE TITLE
rename GO:0005297 'hydrogen:proline symporter activity'

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#14918]
A small issue but the could GO:0005297 be renamed 'proline:proton symporter activity' - it is a child of GO:0015295 solute:proton symporter activity and the other child terms all use the 'xxx:proton symport' syntax. Just noticed that GO:0005280 is 'hydrogen:amino acid symporter actvity' which should also be corrected. Thank you

Amanda

**Comment by pgaudet** [comment]
Hi, 

We had agreed to use proton on another ticket (#14580). So I will rename anything with hydrogen:  



GO_0005280 | hydrogen:amino acid symporter activity | amino acid:proton symporter activity
-- | -- | --
GO_0005356 | hydrogen:glucose symporter activity | glucose:proton symporter activity
GO_0008900 | hydrogen:potassium-exchanging ATPase activity | potassium:proton exchanging ATPase activity
GO_0005889 | hydrogen:potassium-exchanging ATPase complex | potassium:proton exchanging ATPase complex
GO_0005297 | hydrogen:proline symporter activity | proline:proton symporter activity
GO_0047067 | hydrogen:quinone oxidoreductase activity | quinone:proton oxidoreductase activity
GO_0005276 | vesicular hydrogen:amino acid antiporter activity | vesicular amino acid:proton antiporter activity
GO_0005357 | constitutive hydrogen:glucose symporter activity | constitutive glucose:proton symporter activity
GO_0005359 | low-affinity hydrogen:glucose symporter activity | low-affinity glucose:proton symporter activity
GO_0005358 | high-affinity hydrogen:glucose symporter activity | high-affinity glucose:proton symporter activity
GO_1904451 | regulation of hydrogen:potassium-exchanging ATPase activity | regulation of potassium:proton exchanging ATPase activity
GO_0005360 | insulin-responsive hydrogen:glucose symporter activity | insulin-responsive glucose:proton symporter activity
GO_1904452 | negative regulation of hydrogen:potassium-exchanging ATPase activity | negative regulation of potassium:proton exchanging ATPase activity
GO_1904453 | positive regulation of hydrogen:potassium-exchanging ATPase activity | positive regulation of potassium:proton exchanging ATPase activity
GO_0015504 | cytosine:hydrogen ion symporter activity | cytosine:proton symporter activity
GO_0015540 | 3-hydroxyphenyl propionate:hydrogen ion symporter activity | 3-hydroxyphenyl propionate:proton symporter activity

Also, I propose that  
* "GO_0006818   hydrogen transport"  and  "GO_1902600  hydrogen ion transmembrane transport" should be merged into  "GO:0015992 proton transport"

and 
* "GO_0015078  hydrogen ion transmembrane  transporter activity" be renamed "proton transmembrane   transporter activity". 

@amandamackie
Does that seem OK to you ? 

Thanks, Pascale

**Comment by mah11** [comment]
> Also, I propose that .. "GO_0006818 hydrogen transport" and "GO_1902600 hydrogen ion transmembrane transport" should be merged into "GO:0015992 proton transport"

This part of the proposal doesn't fit with the existence of GO:0015993 "molecular hydrogen transport", which is is_a GO:0006818 at present. If, but only if, molecular hydrogen is never transported in a biological system, then GO:0015993 can be made obsolete and GO:0015992 and GO:0006818 can be merged. Otherwise, the existing arrangement would be correct.

GO:1902600 specifies "transmembrane", whereas GO:0015992 does not. They shouldn't merge if there is any proton transport that isn't transmembrane.

**Comment by pgaudet** [comment]
Hi @mah11 
Molecular Hydrogen is H2. As far as I know this form is not directly used by proteins, but I'd like to get @deustp01 's advice here. 

Thanks, Pascale

**Comment by deustp01** [comment]
I don't know of transporters that move molecular hydrogen H2, but those clever archaebacteria probably have a way to do it. However, all the items on Pascale's list above from 2 hr ago involve protons, for sure, and moving a proton ought to involve molecular machinery different from that used to move H2.

**Comment by pgaudet** [comment]
As far as I can tell H2 diffuses, see 
https://www.researchgate.net/post/How_molecular_hydrogen_is_transported_through_the_cytoplasmic_membrane_of_Escherichia_coli

So until we have evidence that the process exists, I prefer to remove the term, so we don' use it accidentally. 

Thanks for the feedback ! 

Pascale

**Comment by pgaudet** [comment]
All is done here.
