### ISSUE TITLE
Are all the specific TFII-class terms needed

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14916]
Hi Pascale

following discussion on Thurs 18th Jan

There are 34 TFII-class MF terms in GO. But there is not consistent representation for each TFII subtype

1. TFII*-class transcription factor binding (9 terms)

2. TFIIIB-type transcription factor activity (1 term with this structure)
**now obsolete** #15788

3. transcription factor activity, TFIID-class binding; transcription factor activity, TFIIF-class transcription factor binding (6 terms)
**now obsolete** #15538 

4. transcription factor activity, TFII*-class transcription factor recruiting (3 terms)
**moved under transcription factor binding** 
#15577 

5. RNA polymerase III type 1 promoter TFIIIB-type transcription factor activity (4 terms)
**now obsolete** #14857

6. transcription factor activity, RNA polymerase III type 3 promoter TFIIIB recruiting; RNA polymerase III hybrid type promoter TFIIIB recruiting transcription factor activity; transcription factor activity, RNA polymerase III promoter sequence-specific binding, TFIIIB recruiting (I think there are 6 terms with this general theme)
**Merged into GO:0001004 RNA polymerase III assembly factor activity** #14852 

7. TFIIB-class transcription factor binding involved in negative regulation of transcription (1 term)
**Being obsoleted** #16059 

8 2 obsolete terms 

9. 2 terms with TFII in definition

10. GO:0001098 basal transcription machinery binding
>GO:0001099 basal RNA polymerase II transcription machinery binding
>>GO:0000993 | RNA polymerase II core binding
>>GO:0001091 RNA polymerase II basal transcription factor binding
>>>TFIIx-class transcription factor binding (9 terms)
Question:
a. do we need the specific terms or can we just use RNA polymerase II basal transcription factor binding?

 basal transcription factor binding >3,000 proteins are annotated with GO:0001098 basal transcription machinery binding, however only 90 of these are with experimental support.

**Comment by krchristie** [comment]
@pgaudet - This seems like it belongs in the TF work you're doing, and like some of these may be things you are already working on. Do you want this ticket?

**Comment by ukemi** [comment]
If it is reassigned, let me know so I can update the rota.

**Comment by pgaudet** [comment]
Sure, I'll take it. 

Pascale

**Comment by RLovering** [comment]
**1. TFIIx-class transcription factor binding** (9 terms)
GO:0001098 basal transcription machinery binding
>GO:0001099 basal RNA polymerase II transcription machinery binding
>>GO:0000993 | RNA polymerase II core binding
>>GO:0001091 RNA polymerase II basal transcription factor binding
>>>TFIIx-class transcription factor binding (9 terms)

Proposal merge all 9 child terms into 
>>GO:0001091 RNA polymerase II basal transcription factor binding

**2 TFIIIB-type transcription factor activity**
Definition: Interacting selectively and non-covalently with an RNA polymerase III (Pol III) complex, typically composed of seventeen subunits, and with another protein, macromolecule, or complex, permitting those molecules to function in a coordinated way, .....
2 parent terms
GO:0000995   transcription factor activity, core RNA polymerase III binding
GO:0001007   transcription factor activity, RNA polymerase III transcription factor binding
> GO:0001026   TFIIIB-type transcription factor activity

GO:0000126   transcription factor TFIIIB complex states TFIIIB contains the TATA-binding protein (TBP) and two Pol III-specific proteins, B'' and BRF. 

I do not think we should have a GO term to group 3 proteins at a functional level. 

There are 9 annotations associated with this MF, I propose we merge this term with GO:0000995, and also co-annotate all these proteins with GO:0001007, or more specific term such as GO:0001098 basal transcription machinery binding

If we are going to keep GO:0001007, then the definition is too vague, it needs to be more specific and give examples of what the 'RNA polymerase III transcription factors' are. so include a statement that the TFs here are GTFs, dbTFs and would we also include any mediator or co-factor TFs?

Question 
Do we want to have binding terms that provide options for binding to all of the RNA pol III types of 'TFs' (as present in GO) such as:

GO:0001007   transcription factor activity, RNA polymerase III transcription factor binding
>New GO term: RNA polymerase III basal transcription machinery binding
>New GO term: RNA polymerase III dbTF binding
>New GO term: RNA polymerase III assembly factor binding
>plus terms if there are mediator or co-factor TFs?

**Comment by RLovering** [comment]
**3. transcription factor activity, TFIID-class binding; transcription factor activity, TFIIF-class transcription factor binding** (6 terms) (34 expt annotations)

ontology structure
GO:0001083 transcription factor activity, RNA polymerase II basal transcription factor binding
Child terms:
GO:0001084    transcription factor activity, TFIID-class binding 
GO:0001088    transcription factor activity, TFIIE-class binding 
> GO:0001136    transcription factor activity, TFIIE-class transcription factor recruiting
GO:0001089    transcription factor activity, TFIIF-class transcription factor binding 
> GO:0001137    transcription factor activity, TFIIF-class transcription factor recruiting
GO:0001086    transcription factor activity, TFIIA-class binding
GO:0001087    transcription factor activity, TFIIB-class binding
GO:0001132    RNA polymerase II transcription factor activity, TBP-class protein binding
>GO:0001129    RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly
GO:0001090    transcription factor activity, TFIIH-class binding
> GO:0001138    transcription factor activity, TFIIH-class transcription factor recruiting

Proposal: With the merge suggest AE fields updated is possible.
merge all of the child binding terms above into:
GO:0001083 transcription factor activity, RNA polymerase II basal transcription factor binding

But also create new Child terms (or rename), and merge the recruiting/assembly terms into the equivalent less specific new term below:
GO:0001083 transcription factor activity, RNA polymerase II basal transcription factor binding
> New GO term transcription factor activity, RNA polymerase II basal transcription factor recruiting
> New GO term transcription factor activity, involved in RNA polymerase II preinitiation complex assembly

Possibly only need one of these terms and make sure the definition states that binding to a basel TF is required (which is implied by the parent term)
Also I don't think TF activity is required in the term name because if the protein was recruiting or assembling then I think it would be a TF

Alternatively is capture of the class bound important in which case keep these terms! But still consider whether assembly and recruitment could be considered similar enough to standardise the terms

**Comment by pgaudet** [comment]
@RLovering 
The issues 2-7 are dealt with. 

# 1 and 9 are related; I will create a new ticket. 

What do you want to do about # 8? 

I think this can be closed - if you agree, please do :) 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
there is nothing to do with point 8
I will close the ticket
Thanks
Ruth
