### ISSUE TITLE
transcription factor binding term: improve definition of term and term name?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#14915]
Hi Pascale 

following discussion on Thurs 18th Jan

GO:0061629 RNA polymerase II sequence-specific DNA binding transcription factor binding
current definition:
Interacting selectively and non-covalently with a sequence-specific DNA binding RNA polymerase II transcription factor, any of the factors that interact selectively and non-covalently with a specific DNA sequence in order to modulate transcription.

This is a good term and should be kept. But the term name should be revised inline with the MF term revisions.

This whole branch needs to be revised. It was agreed that it is useful to have TF binding terms. Once the new MF TF activity terms are agreed then the binding branch needs to be revised. we also agreed the definition could be improved to something like:
new definition:
Interacting selectively and non-covalently with a sequence-specific DNA binding RNA polymerase II transcription factor, any of the factors that interact selectively and non-covalently with a specific DNA sequence within a regulatory region in order to modulate transcription.

In the discussion we were generally agreed that it is useful to have binding terms for dbTFs, mediator TFs, General/basal TFs, co-factor TFs, etc but that distinguishing between activating and repressing TF binding might be more than is necessary and also can cause problems when a TF has activating and repressing activities. 

Questions to confirm with other curators/TF groups:
1. for these TF binding terms is it important to state the TFs are Pol I, II etc types?
2. for these TF binding terms is it important to state whether the TF is activating or repressing?

Ruth

**Comment by hdrabkin** [comment]
I will add @krchristie  to this discussion. I'd like to see actionable items for this ticket.

**Comment by krchristie** [comment]
Regarding these two questions:
   
>  1. for these TF binding terms is it important to state the TFs are Pol I, II etc types?

If you want to link these types of terms to the processes they are involved in, which are also distinguished by which RNA polymerase is doing the transcription, you need to keep these separate.

>     2. for these TF binding terms is it important to state whether the TF is activating or repressing?

I am not sure this is useful as, at least for RNAP II, there are lots of TFs that can be either activating or repressing, depending on the location of the TF binding site, so 'activating' or 'repressing' do not seem to be intrinsic properties of TFs.

**Comment by bmeldal** [comment]
I agree with @krchristie I've had to add activating and repressing terms to the same complexes as it's situation-dependent.

**Comment by pgaudet** [comment]
@hdrabkin should I take this ticket ?

**Comment by pgaudet** [comment]
Hello,

about @krchristie 's comment: 
       

> for these TF binding terms is it important to state the TFs are Pol I, II etc types?

>> If you want to link these types of terms to the processes they are involved in, which are also distinguished by which RNA polymerase is doing the transcription, you need to keep these separate.

Isn't this equivalent to saying 'wnt signaling pathway wnt binding'?

Thanks, Pascale

**Comment by hdrabkin** [comment]
@pgaudet : be my guest!

**Comment by krchristie** [comment]
@RLovering 

> from our discussion 25 Jan 2018. we would create a 'MF' term to describe the function for the different RNA polymerase general transcription factors. We appreciate that equivalent terms (eg GO:0016251) were obsoleted because they were being used to describe a wide range of transcription factors. However if we recognise specific GTF subcomplexes such as TFIIB, TFIID, TFIIE, TFIIF, TFIIH and limit the new MF to these complexes this would enable us to group the TFIIB, TFIID, TFIIE, TFIIF, TFIIH subunits based on their RNA pol I/II/III etc specificities. Functionally grouping the TFIIB, TFIID, TFIIE, TFIIF, TFIIH subunit proteins by their binding does not group these as some dbTFs and the mediator proteins etc do bind the TFIIB, TFIID, TFIIE, TFIIF, TFIIH proteins and therefore the binding terms do not enable grouping by function.

Anything that starts with TFII is already by definition a TF for RNAP II, so I'm not following the suggestion to `to group the TFIIB, TFIID, TFIIE, TFIIF, TFIIH subunits based on their RNA pol I/II/III etc specificities`. I don't believe I've ever come across any of the RNAP II GTFs being involved in RNAP I or RNAP III transcription. Each of those RNAP's have their own TFs.

**Comment by pgaudet** [comment]
Hi @RLovering 
I think the general transcription factor activity part of this ticket has been addressed; is this right ? 

Here's how I propose to address the binding terms (note that this is not under 'transcription factor activity anymore, but we're dealing strictly with binding): 
1. create 2 parents: 
- general transcription initiation factor binding
- DNA-binding transcription factor binding
2. standardize names general transcription initiation factor binding
GO:0001179 RNA polymerase I transcription factor binding -> new name: RNA polymerase I general transcription initiation factor binding
GO:0001091 RNA polymerase II basal transcription factor binding -> new name: RNA polymerase II general transcription initiation factor binding
GO:0001025 RNA polymerase III transcription factor binding -> new name: RNA polymerase III general transcription initiation factor binding
3. move terms under appropriate parent

These 3 steps are done, I am ready to merge. 

Here's the 'before' and 'after' organization of the ontology: 

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/4782928/49159274-6691bf00-f324-11e8-84bf-cbbced2c92d5.png">


If this is OK I will merge this. 
@RLovering 
@ValWood

**Comment by pgaudet** [comment]
Next steps: 
4. Merge GO:0001085 RNA polymerase II transcription factor binding into GO:0061629 RNA polymerase II-specific DNA-binding transcription factor binding ? Or obsolete, depending on whether annotations are consistent

134 EXP annotations -> need to be reviewed 

5. Fix nuclear hormone, nuclear receptor, steroid hormone receptor binding

I will open different tickets for these. 

Thanks, Pascale

**Comment by pgaudet** [comment]
BTW I checked annotations to 
GO:0001155	- TFIIIA-class transcription factor complex binding (1 RGD)
GO:0001156	- TFIIIC-class transcription factor complex binding (4 SGD, 2 UniProt)

they all seem OK 
https://docs.google.com/spreadsheets/d/1YDPlj90pMtWOFyEraW-qqH75MFaEJxZoYs4pRp8RwIM/edit#gid=0
