### ISSUE TITLE
Obsoletion notice for 'GO:0005357 constitutive hydrogen:glucose symporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14924]
Dear all, 

The proposal has been made to obsolete 'GO:0005357 constitutive hydrogen:glucose symporter activity'. The reason for obsoletion is that the constitutive aspect of the transporter is unlikely to be an aspect of the activity, but instead it probably relates to the expression level of the transporter. 

There are not references in the term and no annotations to this term. 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 1, 2018. Unless objections are received by  Feb 1, 2018  we will assume that you agree to this change. 

Thanks, Pascale

**Comment by deustp01** [comment]
It humans, it's useful to distinguish glucose transporters that are constitutively present in the plasma membrane from ones that move between the plasma membrane and a sequestered intracellular location where they have no access to transportable glucose, but that sounds like something to handle by annotating regulation of function, not as a function proper. So no objection from here.
