### ISSUE TITLE
Obsoletion notice: “GO:0005276 vesicular hydrogen:amino acid antiporter activity”.

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14926]
Dear all, 

The proposal has been made to obsolete “GO:0005276 vesicular hydrogen:amino acid antiporter activity”. The reason for obsoletion is that the cellular component does not belong is the MF according to the documentation: http://wiki.geneontology.org/index.php/Transporter_terms_standard_definitions 

There is a single annotation to this term by Reactome (TAS). 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 1, 2018. Unless objections are received by  Feb 1, 2018  we will assume that you agree to this change. 

Thanks, Pascale

**Comment by deustp01** [comment]
This annotation may be an error - we appear to be annotating a symporter so even if this antiporter term were OK for you it looks incorrect for us. Will check.

**Comment by deustp01** [comment]
Indeed that one annotation of ours is an error; we've changed it locally and the change will propagate to our public site with our next release in March.
