### ISSUE TITLE
NTR: ubiquitin activating enzyme complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#14921]
Hi can you please create a new complex term 'ubiquitin activating enzyme complex' related to the MF GO:0004839 ubiquitin activating enzyme activity?
see also ref PMID: 9545234
Thanks a lot
Livia

**Comment by bmeldal** [comment]
Livia, you forgot to add the complex ACs as dbxrefs and give your GOC ID.

**Comment by liviap** [comment]
oh, you are right, here is the complex  xref: EBI-16629455

**Comment by liviap** [comment]
thanks Birgit!!
:-)

**Comment by krchristie** [comment]
Hi Livia,

Could you please also suggest a definition for the new complex term and provide your personal GOC ID for me to attach to that definition.

Thanks!

-Karen

**Comment by liviap** [comment]
Hi Kren,
you are right, I've been too lazy... please, find below few more details...
Livia

Name: ubiquitin activating enzyme complex
 Ontology: cellular_component Def: A protein complex responsible for the catalysis of the reaction: E1 + ubiquitin + ATP--> E1-ubiquitin + AMP + PPi, where the E1-ubiquitin linkage is a thioester bond between the C-terminal glycine of Ub and a sulfhydryl side group of an E1 cysteine residue. This is the first step in a cascade of reactions in which ubiquitin is ultimately added to a protein substrate.
 References: GOC:lnp
PMID:9545234 Relationships:
capable_of GO:0004839 ubiquitin activating enzyme activity
Synonyms:
E1 complex
E1 ubiquitin-activating enzyme
 DB xref: IntAct:EBI-16629455
