### ISSUE TITLE
Hyphens in complex GO terms; transcription-related examples

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14936]
Hi Pascale,

I am aware that a revision of transcription-related terms is currently in progress and I would like to request that you consider the inclusion of hyphens within relevant phrases. 

My request is related to a discussion, which I had with Ruth about a linguistic issue regarding the GO term: "GO:0061629 RNA polymerase II sequence-specific DNA binding transcription factor binding". 

This GO term contains a lot of information in it, and the lack of a hyphen between 'DNA' and 'binding' made it impossible for me to understand it without reading the definition and checking the ancestor relations. 

After all a 'dog eating cat' and a 'dog-eating cat' have opposite meanings. 

The same applies to 'DNA binding [x]' and 'DNA-binding [x]'. 

As well as 'protein binding' and 'protein-binding'. Or even 'transcription factor binding' and 'transcription factor-binding' (although in this latter case I admit I don't know what grammatical rules apply in context of two-word entities, such as 'transcription factors').

The less complex 'DNA binding' GO terms are intuitively easier to understand (than terms like "GO:0061629"), because it is simply easier to disregard linguistic accuracy, when the amount of information in a term is smaller.

However, to ensure these GO terms are grammatically correct, either the hyphen should be there, or the word order within the 'DNA binding' (and similar) phrases should be inverted (because the intended meaning is that an entity is binding DNA, so it is itself a DNA-binding entity). 

Since the focus is on activity, in context of GO, it would probably be more appropriate to invert the order of words in relevant GO terms and say 'binding DNA'. ('DNA binding' [without a hyphen] suggests that DNA is binding something, and not that something else is binding DNA). But as I said above with less complex terms, the lack of hyphens can be more easily disregarded without slowing down the annotation process.

But with more complex terms (e.g. "GO:006162"), if hyphens are omitted, this makes it harder to understand what a term is actually intended to mean (especially, if it is not a GO term, which you use regularly). In such cases I would rather annotate only to the relevant ancestor term to make sure the annotation is 100% correct (rather than read several definitions of different children before I find the most appropriate more specific GO term).

I am not sure whether other curators (and/or users of GO) have had similar thoughts, and how much attention this aspect should be given during the revisions. Based on my own experience, nuances such as hyphens within GO terms certainly make a difference to interpretation of a (complex) GO term name, and consequently the time necessary for identification of the correct GO terms for annotation.

I did not know what other ticket(s) to link this to, but I hope the tag is fine.

Thanks,
Barbara

cc:
@RLovering 
@paolaroncaglia 

re:
https://github.com/geneontology/go-ontology/projects/7

**Comment by paolaroncaglia** [comment]
I agree that adding a hyphen in the name (and definition) of GO:0061629 ‘RNA polymerase II sequence-specific DNA binding transcription factor binding’ might make it slightly easier to grasp the concept behind this term. The repetition of ‘binding’ in the term name is a bit awkward, and the hyphen would help.

**Comment by pgaudet** [comment]
Hyphenated the following terms: 
 id: GO:0003700
-name: DNA binding transcription factor activity
+name: DNA-binding transcription factor activity

 id: GO:0001070
-name: RNA binding transcription regulator activity
+name: RNA-binding transcription regulator activity

 id: GO:0034246
-name: mitochondrial sequence-specific DNA binding transcription factor activity
+name: mitochondrial sequence-specific DNA-binding transcription factor activity

 id: GO:0051090
-name: regulation of DNA binding transcription factor activity
+name: regulation of DNA-binding transcription factor activity

 id: GO:0043433
-name: negative regulation of DNA binding transcription factor activity
+name: negative regulation of DNA-binding transcription factor activity

 id: GO:0051091
-name: positive regulation of DNA binding transcription factor activity
+name: positive regulation of DNA-binding transcription factor activity

 id: GO:0061629
-name: RNA polymerase II sequence-specific DNA binding transcription factor binding
+name: RNA polymerase II sequence-specific DNA-binding transcription factor binding


@BarbaraCzub does that address the issue? 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi @pgaudet. Yes, thank you. I think these terms are much more easily interpretable now. (Especially the last one, which has 'binding' in the GO term name twice). Thanks!
Barbara

**Comment by pgaudet** [comment]
OK. I will also change in the definitions (for example "A **DNA binding transcription factor activity** that is directly regulated by binding of a ligand to the protein with this activity.  Examples include the lac and trp repressors in E.coli and many steroid hormone receptors." ), to be consistent. 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Thank you!
