### ISSUE TITLE
'only in taxon' vs only_in_taxon

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#14945]
It seems odd that both  `'only in taxon'` and `only_in_taxon` are available in Protege when one loads the editors' version of GO into Protege. Here are the usage counts (as of 1/26/18):
`'only in taxon'` - 1216 - these seem to be constraints for GO terms
`only_in_taxon`  -     21 - these all look like constraints for PRO (PR:) terms

In contrast, `never_in_taxon` only seems to have the version with underscores, not a parallel version with spaces.

I am doing this while looking at the instructions (http://go-ontology.readthedocs.io/en/latest/TaxonRestriction.html), but if you try to autocomplete the string 'only' in the Class expression editor to add a new SubClass, both `'only in taxon'` and `only_in_taxon` come up, which seems like it could lead to inconsistency. It also just seems weird that both versions of what seems like the same relationship are present.

Should they be consolidated?

**Comment by balhoff** [comment]
It seems like this might be an issue with PRO: the `only_in_taxon` version has IRI `http://purl.obolibrary.org/obo/pr#only_in_taxon` instead of the one from RO: `http://purl.obolibrary.org/obo/RO_0002160`.

**Comment by ukemi** [comment]
I agree. This seems like it might be an issue with the relation being imported from PRO. @hdrabkin can you follow up with PRO on this and then close this ticket? @cmungall, is this the correct behavior of the imports pipeline? Should the one from PRO have been filtered out?

**Comment by hdrabkin** [comment]
I have sent an email to Darren Natale. I assume we need PRO to start using the IRI from RO?

**Comment by nataled** [comment]
How old is the version being used here? We've used the RO IRI for at least the past three releases of PRO (I didn't check beyond that).

**Comment by cmungall** [comment]
@balhoff is correct, this aspect of the obo2owl conversion is definitely confusing here, it was designed to allow people to have human-readable relation labels in their obo, the tradeoff was complexity in the translation rules.

 * Spec (normative): http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.9.3
 * Recommendations (informative): http://owlcollab.github.io/oboformat/doc/obo-syntax.html#8.2.2

**Comment by nataled** [comment]
@balhoff I see you are doing your own OBO-to-OWL translation. I noticed some time ago that both OORT and ROBOT fail to do this properly, so when we release the PRO OWL file we do a post-processing to convert this and other relations to the correct IRI. I had assumed you were using that post-processed PRO OWL file, hence my confusion.

Do this (here, in perl) to your pr_import.owl:

s/pr\#only_in_taxon/RO_0002160/

**Comment by balhoff** [comment]
Yes, I see the Makefile downloads the OBO:

https://github.com/geneontology/go-ontology/blob/6e966665062b3dc224e283aaeec710c774ec86c0/src/ontology/Makefile#L299-L301

@cmungall is that still needed?

**Comment by cmungall** [comment]
I often configure makefiles to download the obo for pr and ncbitaxon as 
they are so huge.

We need to get people distributing owlzip! 
https://github.com/owlcs/owlapi/issues/375

It would be great also if pro distributed modules. No ontology needs to 
use anything below the generic protein in their axioms

I say for now we leave as is, PR will presumably fix next release, until 
then we just let editors know to pick the right relation

**Comment by cmungall** [comment]
We all use the OWLAPI, which is canonical. Oort, Robot and owltools all 
use the OWLAPI, so the conversion is correct.

**Comment by nataled** [comment]
Unfortunately it is precisely the generic proteins that make PRO so huge (assuming here you refer to the gene-level guys). The distribution of modules is on our to-do list, though it isn't clear to me why you'd need to do anything beyond using Ontobee to grab the desired terms (for separate discussion).

The conversion by the OWLAPI might be 'correct' but it is clearly not doing the optimal job. Again, a separate discussion.

Pertinent to this discussion, however, is your last point: "PR will presumably fix next release..." Can you describe what that fix should be? We follow the correct OBO format when using relations, and we follow to correct OWL format when using them as well. What am I missing?

**Comment by balhoff** [comment]
@nataled I believe that if you modify your `only_in_taxon` typedef to look like this, everything will be fine:

```
[Typedef]
id: only_in_taxon
name: only_in_taxon
def: "U only_in_taxon T: U is a feature found in only in organisms of species of taxon T. The feature cannot be found in an organism of any species outside of (not subsumed by) that taxon. Down-propagates in U hierarchy, up-propagates in T hierarchy (species taxonomy). Implies applicable_to_taxon." [ROC:Waclaw]
comment: Down-propagates. The original name for this in the paper is 'specific_to'. Applicable to genes because some genes are lost in sub-species (strains) of a species.
synonym: "never_outside_taxon" EXACT []
synonym: "specific_to" EXACT []
synonym: "specific_to_taxon" EXACT []
is_transitive: false
xref: RO:0002160
```

The xref will magically become the term IRI in the OWL translation.

**Comment by nataled** [comment]
Would that work if the id is already the RO identifier? This is how it looks now (taking out the def, comment, etc):

[Typedef]
id: RO:0002160
name: only_in_taxon

I can easily add the xref to the term but I'm not sure that will work. Do I have to take a backwards step by using the name/label as the identifier?

**Comment by balhoff** [comment]
>  Do I have to take a backwards step by using the name/label as the identifier?

I think so, in order to match up with the usage of the `only_in_taxon` name as an ID in the [Term] stanzas. This avoids changing all those other usages.

**Comment by nataled** [comment]
The reversion and xref addition is complete. The update will appear with the next release, which is currently in progress.

**Comment by balhoff** [comment]
Great, thanks!
