### ISSUE TITLE
NTR:   membrane tethering

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14953]
NTR:membrane tethering
A process in which a protein or proteins, associated with a  membrane interacts selectively and non-covalently with  another protein, protein complex  or  organelle, in order to maintain the a specific membrane location.

NTR: nuclear membrane tethering
 synonym "tethering at the nuclear periphery”
Def
A process in which a protein or proteins associated with the nuclear membrane (often in the nuclear lumen) interacts selectively and non-covalently with  another protein, protein complex  or organelle, in order to maintain the  specific membrane  associated location. 

--rename -> GO:1990933    microtubule cytoskeleton attachment to nuclear envelope -> nuclear membrane cytoskeleton attachment 
NTR nuclear membrane chromosome attachment
--GO:0097240    chromosome attachment to the nuclear envelope
--GO:0120109    mitotic telomere clustering and tethering at nuclear periphery
-- GO:0070197     meiotic attachment of telomere to nuclear envelope

![34648484-ccadb142-f391-11e7-9e92-e18c33b20c4b 2](https://user-images.githubusercontent.com/7359272/35514578-8c36c0d0-04fe-11e8-833f-d42ea9762e9f.jpg)

other membrane tethering and vesicle tethering processes could also go under here?

**Comment by pgaudet** [comment]
Hello, 

Just checking the relation between this and the term we created here: 
https://github.com/geneontology/go-ontology/issues/13969
('organelle localization by membrane tethering') 

Perhaps that term is not clear and should be renamed ? 

Pascale

**Comment by ValWood** [comment]
I was going to suggest the organelle term went under here.
but actually if everything that is tethered is an organelle, then instead the children of my proposed "membrane tethering" can go under "organelle tethering" instead.

They are slightly different becausue all of "organelle localization by membrane tethering" are membrane-membrane tethering processes...

**Comment by ValWood** [comment]
might be useful
https://www.ncbi.nlm.nih.gov/pubmed/29359129?dopt=Abstract

**Comment by pgaudet** [comment]
Is this different from the parent class 'membrane docking' ? 'The initial attachment of a membrane or protein to a target membrane. Docking requires only that the proteins come close enough to interact and adhere.'

**Comment by ValWood** [comment]
Good question:
https://github.com/geneontology/go-ontology/issues/18464

**Comment by ValWood** [comment]
I'll close this as out of date because most are now in function.
I have processes where required.
