### ISSUE TITLE
NTR: EDS1 disease-resistance complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14952]
Name: EDS1 disease-resistance complex

Def: A plant complex involved in basal disease resistance and resistance (R) gene-mediated effector triggered immunity (ETI). Regulates accumulation of the hormone salicylic acid (SA) which is a necessary component of systemic immunity. Involved in responds to bacteria, viruses and oomycetes.

Synonyms:
EDS1-PAD4-SAG101 complex [NARROW]
EDS1-SAG101 complex [NARROW]
EDS1-PAD4 complex [NARROW]

Relationships:
is_a GO:0043234 protein complex
capable_of_part_of GO:0009626 plant-type hypersensitive response
capable_of_part_of GO:0009862 systemic acquired resistance, salicylic acid mediated signaling pathway

GOC id:bhm

dbxrefs:
IntAct:EBI-16423498
IntAct:EBI-16748728
IntAct:EBI-16423002
IntAct:EBI-16748699
IntAct:EBI-16422538
IntAct:EBI-16748636

I hope this makes sense, no specific MF known yet. It interacts with the R genes triggering ETI and systemic resistance.

Birgit

**Comment by hdrabkin** [comment]
I need references..

**Comment by bmeldal** [comment]
Thanks, Harold, I knew I missed something!
PMID:11574472 & 16040633

Am I bm or bhm?

**Comment by hdrabkin** [comment]
I looked at a couple other complex requests and they have "GOC:bm".  (eg, SWI/SNF complex) and brahma complex) ; but there are some complex terms with bhm. I don't know.

**Comment by bmeldal** [comment]
Hi @hdrabkin 
Kimberly checked the yaml file for me and I'm bhm.
I've just asked her what to do about the other misassigned complexes but if you could change this one to bhm that would be great.
Thanks.

**Comment by hdrabkin** [comment]
will do; there aren't that many goc:bm, so if you are sure they are your requests, I can change them by hand when I do this one.

**Comment by bmeldal** [comment]
Thanks. Kimberly is looking into it already. bm was taken when I started working with GO so at least some older entries aren't mine.

**Comment by hdrabkin** [comment]
"Brenley McIntosh"
I'll go in and change EDS1 disease-resistance complex
