### ISSUE TITLE
NTR: TTT complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#14951]
Hi ! 
Can you please add the following term?
Thanks a lot
Livia

Name: TTT complex
 Ontology: cellular_component
 Def: A protein complex responsible for the stabilisation of protein levels of the phosphatidylinositol 3-kinase-related protein kinase (PIKK) family proteins. TTT complex is part of the ASTRA complex (GO:0070209)
 References: GOC:lnp
PMID: 20810650 Relationships:
Is a GO:0043234 protein complex
capable_of_part_of GO:0050821 protein stabilization
capable_of_part_of GO:2000003 positive regulation of DNA damage checkpoint

capable_of 
Synonyms:
Triple T complex [exact]
TEL2-TTI1-TTI2 complex [narrow]
TELO2-TTI1-TTI2 complex [narrow]
 DB xref: IntAct:EBI-16631004

Please also add the following relationship: 
GO:0070209 ASTRA complex has_part GO:NEW TTT complex
PMID: 22505622

**Comment by ValWood** [comment]
Hi,

A few things to consider:

1. Note that organism names using gene products should probably only be added if they are named this way in the publication.

2. If these names  are used in the puplication, presumably they use protein identifiers and not gene identifiers (for S. cereivisiae these would be  Tel2p-Tti1p-Tti2p

If the authors don't use these name it  is better to add a comment, (or extend the differentia) instead to say  which organism/genes were used to define the complex.

3. If the authors do use these names, they are exact names for the complex, so the synonyms should be exact.

4.  Is there evidence for the triple-t complex existing independently in budding yeast?

**Comment by liviap** [comment]
Hi!
I am not sure I have completely understood your points, so please be patient about my answers..
1. I am using the names as reported in the publication
2. the publication is not from s. cerevisiae, however, as far as I had the opportunity to see, also in yeast the complex is named in the same way (see 28827813)
3. I've added the 'narrow' to make the definition a little more broader and make it include also other names from different species. But you are probably much more experienced than me, so if you think I should flag the synonym as exact, I will.
4. yes, there s the evidence of the complex existing independently (see also 28827813) ( again this is not necessarily an yeast complex... by the way, it seems to be conserved across species..)
Thanks a lot for your comments
Livia

**Comment by ValWood** [comment]
OK from  the yeast paper it's Tel2-Tti1-Tti2 PMID:28827813 would be exact as it is referring to the same complex albeit in another species.

**Comment by vanaukenk** [comment]
@liviap 
I've added the term and synonyms, but not the has_part relation yet.  I don't see many of those relations in the protein complex part of the ontology and want to double-check before adding this one.

**Comment by bmeldal** [comment]
Hi Kimberly,

We don't often have the situation where we'd use has_part for complexes as we wouldn't add pre-assembly complexes without function. This one is an exception, as the TTT complex has a role on its own as well as being a subcomplex of ASTRA. The only other place were I remember using has_part relationships are for the large machineries like the polymerases and primosome, that are made up of several subcomplexes that come and go.

Birgit

**Comment by vanaukenk** [comment]
Thanks @bmeldal   
I've added the has_part relation.
