### ISSUE TITLE
Review design pattern for multi-organism process 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#14956]
I would like to review the design pattern for multi-organism process.

I am currently looking at the equivalence axiom for 'multi-organism plasmodesmata-mediated intercellular transport'  (GO:1902588):

'plasmodesmata-mediated intercellular transport' and ('bearer of' some 'multi-organismal process quality') 

and am not quite sure how to interpret its meaning.

Also note that there are no annotations to this term.

**Comment by cmungall** [comment]
It sounds circular: a multiorganism X is an X that has the property of being multiorganism.

But it's easy to apply and 'does the work' for us, in terms of shadowing the parents of X in the MOP hierarchy.

MOPQ has a more detailed axiom that uses OWL cardinality. This is tedious to type each time, so we use a named quality as a shortcut. Also we don't actually need the more detailed axiom.

But all this should be described in the description: field of the yaml..

**Comment by vanaukenk** [comment]
For reference:

https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/multi_organism_process.yaml

**Comment by pgaudet** [comment]
This term seems like an odd grouping class that groups completely unrelated processes on the basis that different organisms participates: it groups reproduction, viral infection for example. 

Why do we need this term? 
I discussed this with @thomaspd  - I think he has some suggestions about this. 

Thanks, Pascale

**Comment by thomaspd** [comment]
In the GO, biological processes should be from the perspective of the organism that encodes the genes performing the process.  So for multiorganism processes these are always from multiple perspectives, and there should not just be one term to group them.

**Comment by pgaudet** [comment]
Hello, 

How about the relations used in the LD ? 
 and ('bearer of' some 'multi-organismal process quality')

This doesn't specify anything more specific than the parent term. Can we remove the LDs that make use of that pattern? 

I'd like to get @cmungall 's input on this.

Thanks, Pascale

**Comment by pgaudet** [comment]
Based on yesterday's ontology call, I will try to remove this class and re-house terms either under  GO:0044419 interspecies interaction between organisms
GO:0051703 intraspecies interaction between organisms 

Thanks, Pascale

**Comment by pgaudet** [comment]
out of date, this term will be obsoleted see #19769
