### ISSUE TITLE
NTR: term to distinguish new from old basal body

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#14963]
In the issue "NTR: GO terms for kinetoplastid ciliary components" #14713, @Achchuthan requested a term for "ciliary pro-basal body" (below). Having previously wanted to be able to annotate "mother centriole" versus "daughter centriole", I deferred this portion of the previous ticket to this ticket focused specifically on the question of should we have terms in GO to represent the old versus the new centriole/basal body, and if so, can we do it in a way that is generally applicable.

[Term]
name: ciliary pro-basal body
namespace: cellular_component
def: "The cilary pro-basal body is an immature form of the ciliary basal body found next to the basal body of many cilia. Pro-basal bodies do not nucleate a cilium, but may become modified and 'mature' into a basal body which then nucleates a cilium"
comment: The pro-basal body is the structure similar to a 'ciliary basal body' (GO:0036064) or 'centriole' (GO:0005814) often found next to the 'ciliary basal body' (GO:0036064) of a cilium. Pro-basal bodies are distinct from basal bodies as they are not at the base of a cilium, but may nucleate a cilium in future ciliogenesis. While 'immature' they may contain proteins unique to this state. Note that cilia and eukaryotic flagella are deemed to be equivalent.
synonym: "flagellar pro-basal body" EXACT []
synonym: "pro-basal body" BROAD []
synonym: "pro-centriole" BROAD []
is_a: GO:0005815 ! microtubule organizing center
intersection_of: GO:0005815 ! microtubule organizing center
PMID:26862392, PMID:28049148

**Comment by krchristie** [comment]
Also see https://github.com/geneontology/go-ontology/issues/14285 for another comment on need for distinguishing between mother and daughter centrioles/basal bodies

**Comment by Achchuthan** [comment]
Hi @krchristie,

Are there any updates on this issue?

Thanks & best wishes,
Achchuthan

**Comment by Achchuthan** [comment]
Hi,
Are there any followup discussions or developments regarding this issue?
Thanks,
Achchuthan

**Comment by krchristie** [comment]
Hi Achchuthan,

Sorry, I have not done any work on this. I will be at a meeting of the Gene Ontology Consortium next week, but I will try to put this one on my priority list to start looking at again in a couple weeks to see if this is something we could do, though I think it will be tricky.

Thanks,

-Karen

**Comment by Achchuthan** [comment]
Thanks Karen.

**Comment by ValWood** [comment]
We do have a precedent for this with spindle pole body

new mitotic spindle pole body https://www.pombase.org/term/GO:0071958
old mitotic spindle pole body https://www.pombase.org/term/GO:0071958

and although we have not comprehensively annotated to these terms  the terms have allowed us to separate  components which are restricted to one or the other.  The  SIN signalling localizes to the new SPB and some things (SIP/FAR complex) to the old.

So,  the composition (and function)  is different I guess this warrants independent terms?

**Comment by Achchuthan** [comment]
Thanks @ValWood for giving a precedent for this new term request. 
@krchristie, this new term is required to annotate cellular localisations from the TrypTag project (http://tryptag.org/), where they have distinguished the localisatiob of proteins to ciliary basal bodies and pro-basal bodies. I am wondering whether we can use the same precedent mentioned by @ValWood to create this new term.

Thanks & best wishes,
Achchuthan

**Comment by Achchuthan** [comment]
Hi @krchristie,

Sorry to bother you again. Did you have a chance to make any decision on this old ticket. The guys from the TrypTag project are currently working on wrapping up the project and writing the main paper. so, we are planning to integrate their images and GO annotations in our November/ December release. so, I am wondering whether there is still any chance to work on this term before this deadline. Or should we look for a different strategy to annotate proteins with this localization?

Thanks again for your help.

Best wishes,
Achchuthan

**Comment by krchristie** [comment]
Hi @Achchuthan 

The delay isn't lack of precedent, it's been that I think this may end up being complicated, but I'll take a look today and see if I think I can do this on your publication timeline.

thanks,

-Karen

**Comment by Achchuthan** [comment]
Hi @krchristie, Thanks for agreeing to look at this issue.

-Achchuthan

**Comment by krchristie** [comment]
@Achchuthan - I've looked into this a little bit. The tricky bit is that in many eukaryotes, centrioles are part of ciliary basal bodies and also part of centrosomes that organize the spindle during chromosome separation. If I understand correctly, in Kinetoplastids, centrioles are part of ciliary basal bodies, but are not involved in centrosomes and chromosome separation. I'm thinking about how to do this in a way that works for both roles of centrioles in eukaryotes where they are involved in both cilia and chromosome separation.

**Comment by Achchuthan** [comment]
Hi @krchristie,

Thanks for looking into it. Your understanding makes sense to me as well.

-Achchuthan

**Comment by pgaudet** [comment]
@krchristie 
Just checking if this is ready to implement or if you need more information ?

**Comment by krchristie** [comment]
It's first on my priority list for this morning as I am still doing some reading to understand what to do.

**Comment by krchristie** [comment]
Based on my reading, I think that I will need to make child terms of `centriole` for the mother and daughter centrioles. It may be worth making some additional connections between terms, e.g. a `ciliary basal body` is a `mother centriole`, but I haven't quite sorted out the details.

For today, I will just add the term you need, though based on my reading, I've made some changes to the definition, comment, and parentage of the term you requested. I'll indicate what changes I've made from your original request. Let me know if you disagree with anything I've put and I'll make modifications to make sure this term works broadly for both cells that do and do not use centrioles in cellular replication.

> [Term]
> name: ciliary pro-basal body
> namespace: cellular_component
unchanged

> def: "The cilary pro-basal body is an immature form of the ciliary basal body found next to the basal body of a cilium. Pro-basal bodies do not nucleate a cilium, but may become modified and 'mature' into a basal body which then nucleates a cilium"

**new** def: "The cilary pro-basal body is an immature, partially assembled form of a ciliary basal body found next to the basal body of a cilium. Pro-basal bodies are not capable of nucleating a cilium. As the cell progresses through the cell cycle, continuing assembly will convert the pro-basal body into a mature basal body that is capable of nucleating a cilium.

> comment: The pro-basal body is the structure similar to a 'ciliary basal body' (GO:0036064) or 'centriole' (GO:0005814) often found next to the 'ciliary basal body' (GO:0036064) of a cilium. Pro-basal bodies are distinct from basal bodies as they are not at the base of a cilium, but may nucleate a cilium in future ciliogenesis. While 'immature' they may contain proteins unique to this state. Note that cilia and eukaryotic flagella are deemed to be equivalent.

**new** comment: Pro-basal bodies are distinct from basal bodies as they are not at the base of a cilium and are not capable of nucleating a cilium. While immature, they contain some structures in common with the mature basal body and also may contain proteins unique to the immature state. Note that cilia and eukaryotic flagella are deemed to be equivalent. In many eukaryotic cells, 'ciliary basal body' (GO:0036064) and 'centriole' (GO:0005814) represent a common entity that cycles through its function in cell division, then ciliogenesis, then cell division again. However, these structures are modified extensively as they transition into each other, and may contain different proteins, specific to each component. In other eukaryotic cells, centrioles are not involved in cell division but only in cilium assembly, which is thought to be the ancestral role of the centriole/basal body.

> synonym: "flagellar pro-basal body" EXACT []
> synonym: "pro-basal body" BROAD []
> synonym: "pro-centriole" BROAD []
unchanged

> is_a: GO:0005815 ! microtubule organizing center
> intersection_of: GO:0005815 ! microtubule organizing center
No, a pro-basal body cannot be is_a: GO:0005815 ! microtubule organizing center because it is not capable of organizing MTs.

is_a: GO:0110165 ! cellular anatomical entity

> PMID:26862392, PMID:28049148
I kept these two references and added some additional published papers as well as you and me.

**GOC:ach, GOC:krc**, PMID:26862392, PMID:28049148, **PMID:30601682, PMID:29142065, PMID:17505520**

**Comment by Achchuthan** [comment]
Hi @krchristie, 
Thank you very much for taking your time to work on this term. I really really appreciate your help. Your new definition and all explanations make sense to me.
Thanks,
Achchuthan

**Comment by krchristie** [comment]
Hi @Achchuthan - Sorry it took so long. Thanks for taking a look at what I put in to confirm you agree.

**Comment by Achchuthan** [comment]
Hi @krchristie,
No problem. Thanks again for working on this term and providing it within our timelines. I can understand that creating this term required quite a lot of thought and background reading.

**Comment by pgaudet** [comment]
Looks like this is all done ? 

please reopen if not.

**Comment by Achchuthan** [comment]
Thanks @pgaudet. This is done.
