### ISSUE TITLE
cysteine synthase (issue highlighted by KW mapping)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14968]
cysteine synthase used to be a "lyase"  EC. 4.2.99.8 and is still in GO

but it  should be  E.C. 2.5.1.47 (transferase)

**Comment by pgaudet** [comment]
Changed xref in definition: 

-def: "Catalysis of the reaction: O3-acetyl-L-serine + hydrogen sulfide = L-cysteine + acetate." [EC:4.2.99.8]
+def: "Catalysis of the reaction: O3-acetyl-L-serine + hydrogen sulfide = L-cysteine + acetate." [EC:2.5.1.47]

----

Changed parent according to EC: 
-is_a: GO:0016835 ! carbon-oxygen lyase activity
+is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups

- Pascale

**Comment by pgaudet** [comment]
@hdrabkin Can you please confirm that this is OK ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Looks good;
