### ISSUE TITLE
6,7-dimethyl-8-ribityllumazine synthase issue (highlighted by SPKW mapping)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14969]
rib4
http://www.uniprot.org/uniprot/Q9UUB1
Catalyzes the formation of 6,7-dimethyl-8-ribityllumazine by condensation of 5-amino-6-(D-ribitylamino)uracil with 3,4-dihydroxy-2-butanone 4-phosphate. This is the penultimate step in the biosynthesis of riboflavin. Also binds riboflavin with an unexpected high affinity

in GO is an isomerase

according to UniProt is a transferase, check EC

**Comment by ValWood** [comment]
2.5.1.78

**Comment by pgaudet** [comment]
Added parent ''transferase activity, transferring alkyl or aryl (other than methyl) groups'
@hdrabkin can you please confirm this is OK ? 

Thanks, Pascale
