### ISSUE TITLE
Inconsistent usage of 'occurs in' some cell

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14976]
Hello, 

We are using 'occurs in' some cell very inconsistently, for example: 
cell redox homeostasis 
![image](https://user-images.githubusercontent.com/4782928/35569738-3e9d5d28-05cd-11e8-86c4-9cc1092ebb5c.png)

but we don't have such a relation for example in 'cellular process' 

This create weird stats for processes occurring in cells; for example in UniProt there are 369,208 entries annotated to cell via inferences; yet UniProt has over 90 million entries; this number isn't very accurate. 

One option might be to put a 'do not annotate' flag on 'cell', so that these annotations would not be created. 
Would this work ? @ukemi @cmungall 

Thanks, Pascale

**Comment by ukemi** [comment]
This is because of the old problem of 'cellular' in GO not only referring to things that occur in a single cell, for example cell-cell communication or synaptic transmission.

**Comment by pgaudet** [comment]
OK. How about 
> 'adding do not annotate' flag on 'cell'?

**Comment by pgaudet** [comment]
This is redundant with https://github.com/geneontology/go-ontology/issues/12849
