### ISSUE TITLE
GO:0005643 nuclear pore - not nuclear pore complex [EXACT]

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14978]
GO:0005643 nuclear pore 
(Any of the numerous similar discrete openings in the nuclear envelope of a eukaryotic cell, where the inner and outer nuclear membranes are joined.)

currently has 2 exact synonyms:
nuclear pore complex [EXACT]
NPC [EXACT]

I don't think the cellular location of the nuclear pore is the same as the NP complex?

There is a separate complex term:
GO:0046930 pore complex
Any small opening in a membrane that allows the passage of gases and/or liquids.

That def could probably do with a bit of refining - as again, the complex is not the space but what surrounds the space/creates it.

Or am I barking up the wrong tree?

Birgit

**Comment by ValWood** [comment]
I think nuclear pore is just badly defined. It should be describing the complex.

**Comment by bmeldal** [comment]
So, something like:

**A protein complex providing** a discrete opening in the nuclear envelope of a eukaryotic cell, where the inner and outer nuclear membranes are joined.

Does it need a bit more about what's going through? I haven't actually reviewed the NPC yet, just came across it at a tangent...

**Comment by pgaudet** [comment]
@bmeldal 
Sorry I dont understand the problem with the synonyms. The nuclear pore is child of ''nuclear protein-containing complex'', so NPC and nuclear pore complex seem OK s synonyms ? 

I edited the definition as you suggested. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Thanks, @pgaudet 

I don't think the synonyms needed changing. I must have added them just for information when I created the ticket.

I'm going to create ticket to request a similar change in the def for the pore complex as that one also defines the hole, not the complex.
