### ISSUE TITLE
Q actin nucleator? 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14988]
What term would we use to describe the MF of an actin nucleator?

Currently actin nucleation is a process, but it sounds more like an activity. It can be performed by a single gene product (like formin), or comlex (arp2-3 complex)

**Comment by ukemi** [comment]
But it looks like they cooperate in the cell (PMID:21093244). Why not actin binding or one or more of its children, G or F actin binding depending on the mechanism: arp-complex-like, formin-like or Cobl-like (my favorite).

**Comment by ValWood** [comment]
OK.
