### ISSUE TITLE
  2 questions about NMD

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14982]
Is "deadenylation decapping " is always part of "NMD"  or is it used in other contexts (Im trying to figure a) if it is part of NMD, and b)  why it is not generally annotated to NDD.

I also spotted that we have 2 terms  (parent child), 

nuclear-transcribed mRNA catabolic process, nonsense-mediated decay
nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay

but isn't NMD always 5' to 3'?

I'm confused but I thought you would know immediately?

**Comment by ValWood** [comment]
arising from
https://github.com/geneontology/go-annotation/issues/1279

**Comment by krchristie** [comment]
My recollection, from quite some time ago, when Midori was still at SGD, or not long after, was that deadenylation decapping is NOT always part of NMD.

Regarding the two terms you are confused about:
nuclear-transcribed mRNA catabolic process, nonsense-mediated decay
nuclear-transcribed mRNA catabolic process, 3'-5' **exonucleolytic** nonsense-mediated decay

Notice that there is are terms for both directions with definitions that indicate the key distinction, i.e. the lack of either a pA tail or the lack of a 5' cap. 
- nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay
- nuclear-transcribed mRNA catabolic process, 5'-3' exonucleolytic nonsense-mediated decay

Personally, I'm more familiar with 3'-5' NMD, which I think was discovered before 5'-3' NMD, but I have vague recollection of discussing the 5'-3' version with Midori when the term was added, and that term cites a different PMID than the 3'-5' term.

I think there is nothing to do here, so I am closing this ticket.
