### ISSUE TITLE
NTR: regulation terms for entry into reproductive diapause

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14983]
Hi,

Could I have positive and negative regulation terms for:

GO:0055116 entry into reproductive diapause

Term name: positive regulation of entry into reproductive diapause
Def: Any process that activates or increases the rate or extent of the dormancy process that results in entry into reproductive diapause. Reproductive diapause is a form of diapause where the organism itself will remain fully active, including feeding and other routine activities, but the reproductive organs experience a tissue-specific reduction in metabolism, with characteristic triggering and releasing stimuli. 
Ref:PMID:18650956

Term name: negative regulation of entry into reproductive diapause
Def:Any process that stops, prevents, or reduces the frequency, rate or extent of the dormancy process that results in entry into reproductive diapause. Reproductive diapause is a form of diapause where the organism itself will remain fully active, including feeding and other routine activities, but the reproductive organs experience a tissue-specific reduction in metabolism, with characteristic triggering and releasing stimuli. 
Ref:PMID:18650956

GOC:ha

**Comment by hattrill** [comment]
David, I have a terrible confession to make. I copy-pasted the wrong PMID!

Ref for both should be PMID:27689881

I will go put myself in the corner! Forgive me!

**Comment by ukemi** [comment]
That's what I get for trusting you. I will fix it now.

**Comment by hattrill** [comment]
I should be on some watch list!
Thanks!
