### ISSUE TITLE
phospholipid scrambling vs phospholipid translocation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14987]
GO:0017121  phospholipid scrambling
The movement of a population of phospholipid molecules from one leaflet of the plasma membrane bilayer to the opposite leaflet, resulting in loss of lipid asymmetry and surface exposure of phosphatidylserine (PS) and phosphatidylethanolamine (PE).

GO:0045332 phospholipid translocation
The movement of a phospholipid molecule from one leaflet of a membrane bilayer to the opposite leaflet.

**Comment by ValWood** [comment]
GO:0045332 
The movement of a phospholipid molecule from one leaflet of a membrane bilayer to the opposite leaflet.

**Comment by ValWood** [comment]
Q is scrambling  really only for PM?

otherwise these  sound identical?

**Comment by ValWood** [comment]
maybe  different mechanisms but same process?

https://en.wikipedia.org/wiki/Phospholipid_scramblase

**Comment by ValWood** [comment]
Scramblase is an enzyme, present in the cell membrane, that can transport (scramble) the negatively charged phospholipids from the inner-leaflet to the outer-leaflet, and vice versa.

**Comment by ValWood** [comment]
Some flippases - often instead called scramblases[1] - are energy-independent and bidirectional, causing reversible equilibration of phospholipid between the two sides of the https://en.wikipedia.org/wiki/Flippase

membrane, whereas others are energy-dependent and unidirectional, using energy from ATP hydrolysis to pump the phospholipid in a preferred direction.[4] Flippases are described as transporters that move lipids from the exoplasmic to the cytosolic face, while floppases transport in the reverse direction.[1]

**Comment by ValWood** [comment]
I think we can mege the processes, and then precisely define the MFs

**Comment by ValWood** [comment]
These are definitely referring to the same process...

![merge](https://user-images.githubusercontent.com/7359272/46290445-c9184a00-c583-11e8-851a-2faa46d43d83.jpg)

**Comment by ValWood** [comment]
Suggest a merge.

@deustp01  do you know if this process can occur in  other membrane in addition to PM?

If so we could make the term GO:0017121 the  "plasma membrane phospholipid translocation term", standardize the defs and make the appropriate  parentage additions.

**Comment by mah11** [comment]
The comments and links make a distinction:

[Term]
id: GO:0017121
name: phospholipid scrambling
namespace: biological_process
def: "The movement of a population of phospholipid molecules from one leaflet of the plasma membrane bilayer to the opposite leaflet, resulting in loss of lipid asymmetry and surface exposure of phosphatidylserine (PS) and phosphatidylethanolamine (PE)." [GOC:cjm, PMID:20043909, PMID:20302864]
comment: Note that this term describes the trans-bilayer motion of a population of phospholipid molecules, and should not be confused with 'phospholipid translocation ; GO:0045332'.
synonym: "PL scrambling" EXACT []
is_a: GO:0007009 ! plasma membrane organization
is_a: GO:0097035 ! regulation of membrane lipid distribution
relationship: has_part GO:0045332 ! phospholipid translocation

[Term]
id: GO:0045332
name: phospholipid translocation
namespace: biological_process
def: "The movement of a phospholipid molecule from one leaflet of a membrane bilayer to the opposite leaflet." [ISBN:0815316194, PMID:16452632, PMID:20043909, PMID:20302864]
comment: Note that this term describes the transbilayer motion of individual phospholipid molecules, and should not be confused with 'phospholipid scrambling ; GO:0017121'.
synonym: "flippase" RELATED []
is_a: GO:0015914 ! phospholipid transport
is_a: GO:0034204 ! lipid translocation

(Note: I'm neutral w.r.t. whether the distinction is important enough to retain.)

**Comment by ValWood** [comment]
We think to we don't want to represent scrambling as a separate process.

So 
name: phospholipid scrambling become "PM phospholipid translocation"

AND

both terms will get "related synonym: phospholipid scrambling"

**Comment by alanbridge** [comment]
Hi 

merging these two concepts seems wrong somehow. 

Phospholipid translocation is defined as "The movement of a phospholipid molecule from one leaflet of a membrane bilayer to the opposite leaflet." Seems like a good definition.

Phospholipid translocation could lead to the establishment of asymmetry or the loss of asymmetry in membranes.

Phospholipid translocation could be further divided based on i) type of phospholipid ii) leaflet from -> leaflet to. 

Scrambling refers to the process whereby **a population** of lipids is "shuffled" such that asymmetry between leaflets is lost. So there is one major difference: translocation deals with one lipid (?) while scrambling is of a population of lipids.

So scrambling seems to be a distinct process - it specifically leads to loss of asymmetry, and would normally include translocation of several types of lipids in several directions.

I wonder if phospholipid translocation is a function and scrambling a process that includes potentially several such functions. I wonder why translocation is not a function? We would represent translocation in Rhea by a reaction like lipid [in] = lipid [out], which needs more detail obviously. I can't think of a way to represent scrambling in Rhea though which also makes me think they are distinct.

All the best, Alan

**Comment by cmungall** [comment]
> I wonder why translocation is not a function

```
id: GO:0004012
name: phospholipid-translocating ATPase activity
namespace: molecular_function
alt_id: GO:0008557
def: "Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, driven by the hydrolysis of ATP." [EC:3.6.3.1, PMID:15919184, PMID:9099684]
synonym: "aminophospholipid-transporting ATPase" RELATED []
synonym: "ATP phosphohydrolase (phospholipid-flipping)" EXACT [EC:3.6.3.1]
synonym: "flippase activity" BROAD [EC:3.6.3.1]
synonym: "magnesium-ATPase activity" RELATED [EC:3.6.3.1]
synonym: "Mg(2+)-ATPase activity" RELATED [EC:3.6.3.1]
synonym: "Mg2+-ATPase activity" EXACT [EC:3.6.3.1]
synonym: "phospholipid translocating ATPase activity" EXACT []
synonym: "phospholipid-transporting ATPase activity" EXACT [EC:3.6.3.1]
synonym: "phospolipid flippase activity" EXACT []
xref: EC:3.6.3.1
xref: MetaCyc:3.6.3.1-RXN
xref: Reactome:REACT_115892 "Aminophospholipids are transported from in the internal to the external side of the plasma membrane, Homo sapiens"
xref: Reactome:REACT_24989 "P-type ATPase type IV subfamily transporters may mediate phospholipid transfer, Homo sapiens"
xref: RHEA:14989
is_a: GO:0005548 ! phospholipid transporter activity
is_a: GO:0043492 ! ATPase activity, coupled to movement of substances
relationship: part_of GO:0045332 ! phospholipid translocation
```

**Comment by alanbridge** [comment]
Thanks Chris. Not sure as to the distinction between the process and the function though?

**Comment by ValWood** [comment]
Hi @alanbridge 
Good points.

We do have a problem that many MF terms are also represented in the process ontology.
However, for transport I think this is OK.
Here is my rationale:

glucose transmembrane transporter activity (MF) single step transporting glucose with a specific affinity.
glucose transmembrane transport (BP), sum total of the contribution to the transport process of the different activities, plus enable us to capture "regulation of glucose transmembrane".
It's a bit clunky, but I think it's a pragmatic approach as it enables users to enrich easily over specific substrate transport processes, and these do align well with the physiological role 'modules' in the cell.

This is in contrast to the modification terms in process (protein phosphorylation etc), which there is probably a strong case to get rid of because they do not align well with biological modules and are really only recasting the activity in the process ontology.

It seems that "translocation/scrabbling" is more like the "glucose transmembrane transport" example. However, from your comments, I think the problem here is the existing definition.

We should not have "Note that this term describes the transbilayer motion of individual phospholipid molecules" in the process term because this is more like an activity.
Instead we should  use something more like the "scrambling" definition for the process term. I would also be happy if the process was called "phospholipid scrambling" now that you clearly explained the difference.

Would that work?

**Comment by alanbridge** [comment]
Hi Val 

I think I see what you mean. 

So GO would have distinct processes for lipid transport and lipid scrambling, to link regulators to the main actor (the transporter with the MF); and GO would have distinct MFs for transporters/scramblases for specific chemical classes. The scrambling and transport are really two separate processes and shouldn't be merged; scrambling resets asymmetry, transport most likely creates or maintains it.  

I guess if the MF are correctly specified (for individual molecules as well as classes of molecules) then an enrichment tool should tell them that this gene set is enriched in transporters for specific classes - like lipids, steroids, fatty acids - and chemical features (also classes) like ketones, acids, whatever. 

I guess eventually all these terms (MF and BP) would also include a specification of the start/end points as well as the chemical classes? I had a peek in Rhea, which has a generic reaction https://www.rhea-db.org/reaction?id=14989 which has 3 child reactions (for PC/CE/PS). Interesting that the relative start/end points differ for each lipid. Eventually we should be using GO for compartments in Rhea.

All the best, Alan

**Comment by pgaudet** [comment]
Good reference : PMID:25955841
"An asymmetric membrane is a system not at equilibrium, which would prefer a symmetric distribution of membrane lipids. Thus, maintaining membrane asymmetry in live cells is an active process (requiring ATP) carried out by proteins, known as flipases or floppases."

**Comment by pgaudet** [comment]
Hello, 

Looking at this ticket again, also with the work that @marcfeuermann and I just did on the corresponding activities (GO:0140303 intramembrane lipid transporter activity and children), here's what we propose: 

 - [ ] GO:0034204 lipid translocation 
-> change label establishment or maintenance of membrane asymmetry
-> change definition, from 'The translocation, or flipping, of lipid molecules from one monolayer of a membrane bilayer to the opposite monolayer.' to 'The translocation, or flipping, of lipid molecules from one monolayer of a membrane bilayer to the opposite monolayer to establish or maintain the asymmetry of a membrane.'
- [ ]  Merge the children that describe specific lipids (since these are already captured in the MF): 
'glycolipid translocation'
'phospholipid translocation'
'aminophospholipid translocation'
'lysophospholipid translocation'
'sphingolipid translocation'
'ceramide translocation'

3. Review other terms to see if they can be made children, for eg: 

ER to chloroplast lipid transport'
ER to Golgi ceramide transport'
plasma membrane phospholipid scrambling'


OK ? @ValWood @alanbridge 

Annotations are being reviewed to make sure they are consistent with this proposal. 
https://github.com/geneontology/go-annotation/issues/2367

Thanks, Pascale

**Comment by marcfeuermann** [comment]
I'm currently reviewing the corresponding annotations. In most cases, the new definition is right. However, sometimes the flip/flop is used to export lipids to extracellular lipid particles, or to import lipids into cells. In these cases, I would not use this term but create new terms such as 'lipid export from the cell' and 'lipid  import into the cell'.

**Comment by marcfeuermann** [comment]
... And of course we need the term 'disruption of membrane asymmetry' for the scramblases.

**Comment by pgaudet** [comment]
- [ ] GO:0034204 lipid translocation will need to get obsoleted, because annotations represent several processes

**Comment by ValWood** [comment]
> I would not use this term but create new terms such as 'lipid export from the cell' and 'lipid import into the cell'.

aren't these examples of
GO:0120009 | | intermembrane lipid transfer

because they are alway  moving  between lipid bilayers?

or do you have different examples?

**Comment by ValWood** [comment]
>... And of course we need the term 'disruption of membrane asymmetry' for the scramblases. 

Do we definitely need this term? or should it be built into the definition of the process of 
GO:0034204    lipid translocation
(it's an output/reason for  this process)

**Comment by ValWood** [comment]
>GO:0034204 lipid translocation

was only meant to mean intramembrane transfer. 

At least this is how it is defined, and I how I consistently used it.

"The translocation, or flipping, of lipid molecules from one monolayer of a membrane bilayer to the opposite monolayer."

What else does it mean?

**Comment by ValWood** [comment]
I'd quite like to keep some of the  high-level substrate specificity in BP is we can for enrichment purposes. Not absolutely necessary  but will probably be quite useful for enrichment to have these particular process groupings.
