### ISSUE TITLE
difference between tRNA 5'-leader removal/ tRNA 5'-end processing?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14999]
I don't understand the difference between these.....

tRNA 5'-leader removal
Definition (GO:0001682)
Generation of the mature 5'-end of the tRNA, usually via an endonucleolytic cleavage by RNase P. PMID:11592395

GO:0099116  tRNA 5'-end processing
Definition (GO:0099116)
The process in which the 5' end of a pre-tRNA molecule is converted to that of a mature tRNA. PMID:27484477

**Comment by ValWood** [comment]
![difference](https://user-images.githubusercontent.com/7359272/35668800-d496d148-072a-11e8-834a-b23dfd70cdc6.jpg)

**Comment by hdrabkin** [comment]
end processing is not just leader removal.;
Quoting from PMC4284800
In Bacteria and Archaea, tRNAHis species are almost always encoded with an additional 5'-G nucleotide that is retained during 5'-end maturation by RNase P (indicated by the blue lightning bolt), ensuring the presence of the 5'-G-1 residue that is required to recognize the tRNAHis by its canonical Histidyl-tRNA synthetase (HisRS). 
However, in most eukaryotes, the pre-tRNAHis does not encode the additional G-1 and eukaryotic Thg1 enzymes catalyze a specialized 5'-end editing reaction to post-transcriptionally add G-1 to the tRNA and thus ensure proper recognition

**Comment by hdrabkin** [comment]
So GO:0099116 tRNA 5'-end processing is broader and would encompass the G-1 additions. 
GO:0001682 could be a part_of GO:0099116

**Comment by ValWood** [comment]
parentage suggestions sound good.
\v

**Comment by hdrabkin** [comment]
You're back!

**Comment by hdrabkin** [comment]
done

**Comment by ValWood** [comment]
well of a fashion,  I borrowed a tiny lap top from Antonia... i can catch up with e-mail now

**Comment by hdrabkin** [comment]
Forgot to clode
