### ISSUE TITLE
NTR 3 transmembrane terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14994]
1. proline import across plasma membrane child of GO:1905647
PMID: 10654085
(I think permeases are always PM? possibly)

2. borate export across plasma membrane  child of GO:0035445 
PMID: 17459946

3. zinc  II ion plasma membrane import
PMID:18637840 

All PomBase TM transporters will then be annotated as specifically as possible I think...then just ongoing maintenance

**Comment by pgaudet** [comment]
Hi @ValWood 
Not sure what you are asking: 
1) GO:1905647 is already proline import across plasma membrane

> I think permeases are always PM? 
I dont know - couldn't they be mitochondrial ? https://en.wikipedia.org/wiki/Amino_acid_permease


-- 
I added the other two terms: 

+[Term]
+id: GO:0140159
+name: borate export across plasma membrane
+namespace: biological_process
+def: "The directed movement of borate from inside of a cell, across the plasma membrane and into the extracellular region." [GOC:vw, PMID:17459946]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005576 ! extracellular region
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+intersection_of: transports_or_maintains_localization_of CHEBI:22908 ! borate
+created_by: pg
+creation_date: 2018-02-02T10:21:37Z
+
+[Term]
+id: GO:0140160
+name: zinc II ion import across plasma membrane
+namespace: biological_process
+def: "The directed movement of zinc(2+) ions from outside of a cell, across the plasma membrane and into the cytosol." [GOC:vw, PMID:18637840]
+synonym: "zinc II ion plasma membrane import" EXACT []
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:29105 ! zinc(2+)
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-02T10:28:21Z
