### ISSUE TITLE
Travis checks failing with wget step for owltools

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#14990]
Hi,

My most recent Travis checks have failed with the following error message:

The command "wget http://build.berkeleybop.org/userContent/owltools/owltools -O bin/owltools" failed and exited with 8 during .

@dougli1sqrd can you take a look?

Thx.

**Comment by ukemi** [comment]
Looks like a network error.

**Comment by ukemi** [comment]
I just tried to restart and got the same error.

**Comment by vanaukenk** [comment]
This looks to be working now, so I'm closing the ticket.
