### ISSUE TITLE
odd transporter parentage (L-leucine)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15008]
L-leucine transmembrane transporter activity
(actually all amino acid transport)
has the parent  "cation transmembrane transport"

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015190

would people expect that (is this another CHEBI issue?)

**Comment by pgaudet** [comment]
Indeed this is a ChEBI issue. Amino acids are ionized in cells, therefore considered ions. Probably the most relevant term for biologists is 'inorganic ions' 

Perhaps the solution is to remove 'anion transport' and 'cation transport', this way what we'll have under 'ion transport' will be either 'organic' or inorganic'. Would that be more intuitive? 

I'm adding this to the editors' discussion. 


Thanks, Pascale

**Comment by pgaudet** [comment]
is it OK that some AA are both anions and cations ? 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/4782928/35820954-a4e88696-0aa7-11e8-8930-5fd360b7e5d0.png">

**Comment by pgaudet** [comment]
If we use the 'neutral' form of the amino acids (for eg: arginine), then we dont have all these ion inferences. The ontology is inconsistent in that restect: 

For example, L-arginine transport: 
transport
 and (imports some L-arginine)

while 'arginine transport' is defined as follows: 
'basic amino acid transport'
 and ('transports or maintains localization of' some argininate)


Which is right ? Should we implement rules to avoid inconsistencies here? 

Thanks, Pascale
