### ISSUE TITLE
GO:0008108 & GO:0070569 (uridylyltransferase related terms) synonyms

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15006]
GO:0008108 UDP-glucose:hexose-1-phosphate uridylyltransferase activity
has several synonyms, including 

uridyltransferase activity | exact
uridyl transferase activity | broad

I'm thinking these should both be "broad"?

Alternatively, the parent GO:0070569 uridylyltransferase activity has no synonyms- this is where I expected to see at least 'uridylyl transferase activity'.

Thanks

**Comment by ukemi** [comment]
Makes sense to me.

**Comment by vanaukenk** [comment]
@suzialeksander @ukemi 
I will make both synonyms above broad synonyms for GO:0008108  and also add them as exact synonyms to the parent term, GO:0070569.
On a side note, we had an interesting discussion yesterday with Larry H. about synonyms in GO.  This is a nice example of how GO's classification of synonyms is very important for text mining.

**Comment by vanaukenk** [comment]
@suzialeksander - we will need a GOC xref for you, e.g. GOC:sal

Let me know what you would like to use and I'll add it to the users.yaml file.
