### ISSUE TITLE
TPV: lots of drug transport!

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15000]
GO:1903401    L-lysine transmembrane transport
is_a
GO:1903400    L-arginine transmembrane transport
is_a
GO:0071422    succinate transmembrane transport
is_a
GO:1905544    L-methionine import across plasma membrane
is_a
GO:1904555    L-proline transmembrane transport
is_a
GO:1904556    L-tryptophan transmembrane transport
is_a
GO:1903092    pyridoxine transmembrane transport
is_a
GO:1901477    benomyl transmembrane transport
is_a
GO:1903091    pyridoxamine transmembrane transport
is_a
GO:0035445    borate transmembrane transport
is_a
GO:0089709    L-histidine transmembrane transport
is_a
GO:1903803    L-glutamine import across plasma membrane
is_a
GO:1903090    pyridoxal transmembrane transport
is_a
GO:0080170    hydrogen peroxide transmembrane transport
is_a
GO:1990961    drug transmembrane export
is_a
GO:1902270    (R)-carnitine transmembrane transport
is_a
GO:0035378    carbon dioxide transmembrane transport
is_a
GO:1903785    L-valine transmembrane transport
is_a
GO:0015238    drug transmembrane transporter activity
part_of
GO:0071939    vitamin A import
is_a
GO:0089711    L-glutamate transmembrane transport
is_a
GO:0090514    L-tyrosine transmembrane import into vacuole
is_a
GO:1901962    S-adenosyl-L-methionine transmembrane transport
is_a
GO:0097339    glycolate transmembrane transport
is_a
GO:1990544    mitochondrial ATP transmembrane transport
is_a
GO:1903222    quinolinic acid transmembrane transport
is_a
GO:1904947    folic acid import into mitochondrion
is_a
GO:1904447    folic acid import across plasma membrane
is_a
GO:1902599    sulfathiazole transmembrane transport
is_a
GO:1902598    creatine transmembrane transport
is_a
GO:1903811    L-asparagine import across plasma membrane
is_a
GO:1904983    glycine import into mitochondrion
is_a
GO:1905135    biotin import across plasma membrane
is_a
GO:1903088    5-amino-1-ribofuranosylimidazole-4-carboxamide transmembrane transport
is_a
GO:1903807    L-threonine import across plasma membrane
is_a
GO:1903804    glycine import across plasma membrane
is_a
GO:1903791    uracil transmembrane transport
is_a
GO:1903808    L-tyrosine import across plasma membrane
is_a
GO:1903352    L-ornithine transmembrane transport
is_a
GO:0071934    thiamine transmembrane transport
is_a
GO:0098712    L-glutamate import across plasma membrane
is_a
GO:1903710    spermine transmembrane transport

**Comment by pgaudet** [comment]
This is due to the inferences from ChEBI roles. We will remove all those and add 'relevant' relations back. #14626
