### ISSUE TITLE
bacterial collagenases

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#15011]
Hello, I've been annotating bacterial collagenases, which are secreted metallopeptidases important for carbon acquisition in saprophytic bacteria and additionally in virulence for pathogenic bacteria like Clostridia (Q9X721 for example, which is in the throes of integration into UniProtKB/Swiss-Prot).  GO:0032963, collagen metabolic process (https://www.ebi.ac.uk/QuickGO/term/GO:0032963) looks like it has taxon constraints, if I read the info correctly. But while only eukaryotes can make collagen, bacteria can degrade it. So can I use collagen metabolic process for bacteria, and if I currently can't what do you think about permitting it? There used to be a microbial collagenase GO term (GO:0051405) but it is obsolete. This paper (PMID 3002446) shows both endopeptidase and tripeptidylcarboxypeptidase activity of ColG, Q9X721. 
Thanks, Andrea

**Comment by ukemi** [comment]
Looks like the parent should be switched to make it more generic. Also check the logical def. Is it necessary and sufficient?

**Comment by AndreaAuchincloss** [comment]
Necessary and sufficient to degrade collagen? It only acts on the triple helical region of collagen, but it can really go to town on that, so it is certainly capable of doing a lot of damage to collagen.

**Comment by pgaudet** [comment]
Looks like the problem is the subclass 'multicellular organismal macromolecule metabolic process'
- also ''collagen catabolic process' should NOT be Subclass of 'multicellular organismal catabolic process''  

Thanks, Pascale

**Comment by pgaudet** [comment]
@hdrabkin stealing this while you were sleeping since @AndreaAuchincloss came to explain the problem
