### ISSUE TITLE
MAPK cascade definitions

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15012]
Moved from https://github.com/geneontology/go-annotation/issues/1795

Hi
sorry to be a pain but the definition and comments associated with GO:0070371 ERK1 and ERK2 cascade are confusing:
Definition:An intracellular protein kinase cascade containing at least ERK1 or ERK2 (MAPKs), a MEK (a MAPKK) and a MAP3K. The cascade can also contain two additional tiers: the upstream MAP4K and the downstream MAP Kinase-activated kinase (MAPKAPK). The kinases in each tier phosphorylate and activate the kinases in the downstream tier to transmit a signal within a cell. PMID:20811974
comments:Note that this MAPKKK cascade is commonly referred to as the ERK pathway in the literature, but involves only ERK1 or ERK2, not other ERK kinases.

I think this means that MAP4K and MAPKAPK should both be annotated to GO:0070371 ERK1 and ERK2 cascade, rather than regulating the GO:0070371 ERK1 and ERK2 cascade.

If this is correct maybe these could be revised to:
Definition:An intracellular protein kinase cascade containing at least ERK1 or ERK2 (MAPKs), a MEK (a MAPKK) and a MAP3K. The cascade may involve 5 different kinases, as it can also contain two additional tiers: the upstream MAP4K and the downstream MAP Kinase-activated kinase (MAPKAPK). The kinases in each tier phosphorylate and activate the kinases in the downstream tier to transmit a signal within a cell. PMID:20811974

comments:Note that the MAPKKK cascade is commonly referred to as the ERK pathway in the literature, but the ERK pathway is often only part of the ERK1 and ERK2 cascade as it involves only ERK1 or ERK2, and not other ERK kinases.

I have tried to indicate the suggested revisions using bold highlights

PS I have updated the annotation listed for BHF from positive regulation of ERK1 and ERK2 cascade to ERK1 and ERK2 cascade

Ruth

Also, in the definition if MEK (a MAPKK) is MAP2K, could we change 'MEK (a MAPKK)' in the definition to 'MEK (a MAPKK/MAP2K)'

**Comment by ukemi** [comment]
Thanks @RLovering. This was part of the reason that I thought the annotation review was worth it.

**Comment by ukemi** [comment]
I also thought that at the meeting in Cambridge, we decided that the downstream MAPKAK was not a part of the cascade, but rather downstream of it. @sabrinatoro, am I remembering correctly?

**Comment by sabrinatoro** [comment]
@ukemi: correct, we agreed that the downstream activated kinases (or whatever is activated by the cascade) was not part of the cascade. 
We however discussed the need to indicate when a gene/protein (kinase or not) is activated by a cascade. But discussions did not go further than that. 
We might need to restart this discussion.

**Comment by ukemi** [comment]
I think the best way to indicate the downstream functions is in a GO-CAM model. But I will modify the current defs to remove the downstream activity.
