### ISSUE TITLE
NTR: m7G(5')pppN diphosphatase complex 

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15021]
Hallo,
could you please add the following term?
Many thanks in advance
Livia

Term: 
Name: m7G(5')pppN diphosphatase complex 
Ontology: cellular_component 
Def: A protein complex that catalyses the reaction: 7-methylguanosine 5'-triphospho-5'-polynucleotide + H2O = 7-methylguanosine 5'-phosphate + polynucleotide.

References:
PMID: 22985415 GOC:lnp
 Relationships: is_a GO:1903293 phosphatase complex
capable_of GO:0050072 m7G(5')pppN diphosphatase activity
capable_of GO:0000340 RNA 7-methylguanosine cap binding
capable_of_part_of GO:0000956 nuclear-transcribed mRNA catabolic process 
dbxref:
Intact: EBI-15484673
Synonyms:
m7G(5')pppN diphosphatase enzyme [exact]
M(7)G(5')pppN pyrophosphatase enzyme [exact]
m7G(5')pppN pyrophosphatase enzyme [exact]
7-methylguanosine-5'-triphospho-5'-polynucleotide 7-methylguanosine-5'-phosphohydrolase enzyme [exact]
DCS1 decapping scavenger complex [exact]

**Comment by bmeldal** [comment]
Livia,

We don't add PDB ACs (that's UniProt's job :) )
IntAct is dbxref (rather than definition xref).

Birgit
x

**Comment by liviap** [comment]
:) thanks Birgit!!
-modified-

**Comment by hdrabkin** [comment]
Hi @liviap (Livia)
I'm quickly looking at the PMID you supplies, and I'm missing something; 
Is this a protein complex? I see statements to the DcpS protein complexed to the mononucleotide cap structure, but can't find anything discussing the structural state of DcpS complexed to other proteins.

**Comment by liviap** [comment]
you are right, it always appear as just DcpS, because, as shown in crystal 5bv3, DcpS is a homodimeric complex

**Comment by hdrabkin** [comment]
Do you have a reference for the homodimer? Also I would put the homodimer in the def to make it clear.

"A homodimeric protein complex that catalyses the reaction: 7-methylguanosine 5'-triphospho-5'-polynucleotide + H2O = 7-methylguanosine 5'-phosphate + polynucleotide."

**Comment by liviap** [comment]
this is the reference of the dimer: 26258763.
My personal opinion it to leave the definition a bit more relaxed to make sure, it might be not to yeast-specific. But if you believe that is better to specify that it's an homodimer, than it's fine to me.

**Comment by hdrabkin** [comment]
GO:0106095
done

**Comment by liviap** [comment]
thanks a lot for your help!
