### ISSUE TITLE
Error in definition of GO:0004356 (glutamate-ammonia ligase activity)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15036]
Current definition is:
Glutamate-ammonia ligases catalyze the reaction: L-glutamate + ATP + NH(4)(+) = L-glutamine + ADP + 2 H(+) + phosphate
[Xref is to EC:6.3.1.2]

I think "NH(4)" should be "NH(3)"?

**Comment by deustp01** [comment]
Indeed the EC definition is catalysis of the reaction ATP + L-glutamate + NH(3) <=> ADP + phosphate + L-glutamine (https://enzyme.expasy.org/EC/6.3.1.2) but at pH7.3 ammonia is protonated. NH(4)+. (This issue of conforming either to EC or to reality must have come up and been resolved in the past.)

**Comment by deustp01** [comment]
But @ukemi points out that these ionization state issues are resolved computationally in GO so fixing the definition isn't needed.

**Comment by ukemi** [comment]
I can change the textual definition, but behind the scenes, the ionization states are ignored in the ontology. At some point this could be revisited, but @deustp01 points out the issue in this ticket. The literature and usage is often not accurate, so we opted to gloss it over.

**Comment by sjm41** [comment]
OK, whatever you think best - not a big issue.  Just noticed the discrepancy between the GO def and the EC reaction and thought I'd report it.

**Comment by ukemi** [comment]
I will change this to make it consistent with EC. Eventually it would be nice if we could use the Rhea reactions as the definitive definitions. We will discuss this strategy in May.

**Comment by deustp01** [comment]
But Rhea reactions are meticulously constructed to show charge states at pH 7.3, so there's not a good fit with GO's charge-agnostic view (with hidden workaround to compensate for lack of charge-agnostic parent terms in ChEBI). That's not an objection, and the difference can probably be sorted out with some kind of mapping - just one more chore.
