### ISSUE TITLE
NTR: LMA1 complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15039]
Hi, 
could you please consider to add the following term?
Thank you in advance,
Livia
Term 1: 
Name: LMA1 complex 
Ontology: cellular_component
 Def: A protein complex involved in the facilitation of vesicle fusion such as homotypic vacuole and ER-derived COPII vesicle fusion with the Golgi.

References:
PMID: 9015301 
GOC:lnp

Relationships:
 is_a GO:0043234 protein complex 
capable_of GO:0005515 protein binding
capable_of_part_of GO:0042144 vacuole fusion, non-autophagic 
 DB xref: 
IntAct: EBI-16411729

**Comment by bmeldal** [comment]
I'll have a look with Livia to see if we can come up with a name that's not composition-specific.
[I was already gone when she made the request yesterday.]

**Comment by liviap** [comment]
I admit that LMA1 complex sounds as a protein/gene, I really don't know where it comes from. However, the name is not composition specific, since the components are thioredoxin and IB2. As far as I could see the complex itself is named LMA1.

**Comment by liviap** [comment]
Hi @krchristie ,
thank you very much for adding the term.
Unfortunately, I have to ask you to modify the name, the relationships and the definition, and to add two synonyms as follow:
Thank you in advance,
Livia


Term 1: 
Name: membrane fusion priming complex 
Ontology: cellular_component
 Def: A protein complex that primes vacuolar or vesicular membranes for fusion with other intracellular membranes, by promoting the dissociation of cis-SNARE complexes.

References:
PMID: 12914955
GOC:lnp

Relationships:
 is_a GO:0043234 protein complex 
capable_of_part_of GO:0090174 organelle membrane fusion
 DB xref: 
IntAct: EBI-16411729
synonyms:
LMA1 complex [exact]
GATA16 [exact]

**Comment by krchristie** [comment]
I was wondering if the synonym be "GATA16", which sounds like a single gene product, or something like "GATA16 complex".

**Comment by krchristie** [comment]
After taking a quick look at the paper, I am actually wondering if the synonym should be "GATE-16 complex", since "GATE-16" is discussed in the paper, not GATA16.

**Comment by liviap** [comment]
it was GATE16 (apologies for the typo) and it is a homodimeric complex, so I think you are absolutely right: GATE-16 complex is more appropriate
