### ISSUE TITLE
Ligase activity GO terms whose EC xref is too broad

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15037]
I suggest the following EC xrefs are deleted- they are too broad for the given GO term:
GO:0004774: remove EC:6.2.1 xref
GO:0015645: remove EC:6.2.1 xref
GO:0016421: remove EC:6.4.1 xref
GO:0003909: remove EC:6.5.1 xref
GO:0008452: remove EC:6.5.1 xref

**Comment by hdrabkin** [comment]
These are on my spreadsheet list I am going through, but I'll just do these now to close the ticket (there are many more)

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks Harold!  (Sorry to pre-empt your spreadsheet clean-up, but wanted to report these as part of completing my D.melanogaster ligase review.)
