### ISSUE TITLE
response to ceramide

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15047]
I would like to see "response to ceramide” and “cellular response to ceramide” added to the GO ontology under the parent terms “response to lipid” (GO:0033993) and “cellular response to lipid” (GO:0071396), respectively.  The definitions could be “Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a ceramide stimulus.” and "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a ceramide stimulus.” Examples can be found in PMID:18006463.

**Comment by hdrabkin** [comment]
Any thoughts about using extensions with CHEBI:17761 ceramide?

**Comment by slaulederkind** [comment]
RGD doesn't use extensions.

**Comment by ValWood** [comment]
Isn't this only a condition used to activate apoptosis  here?
(sometimes these  terms are more like phenotypes than processes)

See also
https://github.com/geneontology/go-annotation/issues/1807

**Comment by hdrabkin** [comment]
GO:0106097 cellular response to ceramide
GO:0106096 response to ceramide
