### ISSUE TITLE
sequence-specific regulation of translation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15049]
I would like to see "sequence-specific regulation of translation”, “sequence-specific positive regulation of…” and "sequence-specific negative regulation of…” added to the GO ontology under the parent term "regulation of translation” (GO:0006417).  The definitions could be "Any sequence-specific process that modulates/increases/decreases the frequency, rate or extent of the chemical reactions and pathways resulting in the formation of proteins by the translation of mRNA or circRNA.”  Example can be found in PMID: 7523370.

**Comment by pgaudet** [comment]
Hi @slaulederkind 

Can you use ' GO:0008494 translation activator activity'? It doesn't mention RNA binding but it's a parent of RNA binding. If needed we could probably add 'sequence-specific' in the term label (but at least RNA binding seems necessary). 

What do you think ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
"translation repressor activity, nucleic acid binding" (GO:0000900) should work, but I still think a granular BP term would be nice.

**Comment by pgaudet** [comment]
Hi @slaulederkind 

In fact the definition of "translation repressor activity, nucleic acid binding" (GO:0000900) seems to describe what is reported in the paper quite well: 
Antagonizes the ribosome-mediated translation of mRNA into a polypeptide via direct binding (through a selective and non-covalent interaction) to nucleic acid.

How about if we changed the term label to 
"translation repressor activity, mRNA regulatory element binding"? 

(Do you have examples of activators? GO:0008494 could perhaps be improved as well) . 

Thanks, Pascale
