### ISSUE TITLE
regulation of D-aspartate import across plasma membrane

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15041]
I would like to see "regulation of D-aspartate import across plasma membrane”, 
positive regulation of…” and " negative regulation of…” added to the GO ontology under the parent term "D-aspartate import across plasma membrane” (GO:0140016).  The definitions could be "Any process that modulates/increases/decreases the frequency, rate or extent the directed import of D-aspartate from the extracellular region across the plasma membrane and into the cytosol."  Example can be found in PMID:17364745.

**Comment by vanaukenk** [comment]
Hi @slaulederkind 
I was curious about the D-aspartate transport, so was wondering if it is just being used as an analogue for L-glutamate, and if so, would annotating to regulation of L-glutamate import across plasma membrane be best here?
Thx.

**Comment by slaulederkind** [comment]
There is a glutamate transporter (Slc1a3, GLAST) that also functions as an aspartate/glutamate exchanger.  That is the protein on which this term request was based.

**Comment by pgaudet** [comment]
Hi @slaulederkind 
I just looked at the paper, and they are clearly using D-aspartate as an analogue for glutamate. 
"we used immunohistochemical techniques to trace retinal uptake of the glutamate analogue D-aspartate in situ and demonstrated that inhibition of PKC impaired the activity of the Müller cell glutamate transporter GLAST"

We can add the terms if you find another reference where this is physiologically relevant. 

Thanks, Pascale

**Comment by slaulederkind** [comment]
PMID:8772431

**Comment by pgaudet** [comment]
@slaulederkind 

That paper talks about transport, so it doesn't provide evidence for regulation of transport. 
Trying to find some literature about this - it seems like it's transported solely by the aspartate transporter, do there doesn't seem to be any specific mechanism regulating aspartate transport - see for eg PMC3555687. 

Can you find papers that demonstrates that specific regulation of aspartate transport exists ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Thanks for your patience Stan ! I think this paper shows a process that is 'causally upstream' of the regulation of D-aspartate import but it's regulation. 

Thanks, Pascale
