### ISSUE TITLE
Equivalent Class Check

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15057]
We need a check for equivalent classes in the ontology. This should fail the Travis checks when they are detected. We should double check to see if we have any currently and fix them.

**Comment by dougli1sqrd** [comment]
I thought we had something like this already? https://github.com/geneontology/go-ontology/blob/master/src/sparql/equivalent-classes-violation.sparql? Is this not working? Can you give an example of which classes are equivalent?

**Comment by pgaudet** [comment]
probably equivalent to https://github.com/geneontology/go-ontology/issues/13308

**Comment by dougli1sqrd** [comment]
@pgaudet Thanks for detecting equivalent ticket violations!

Does that sparql query I linked above not work? Do you have an example of an existing violation that we're not catching now?

**Comment by pgaudet** [comment]
Hi @dougli1sqrd 
In the current master, GO:0008381 and GO:0022839 have the same equivalence axiom. 

I did a pull request to fix it but I havent merged it yet (https://github.com/geneontology/go-ontology/pull/15056)
So you can test your script with master. 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/15060

I think this should do it?

**Comment by dougli1sqrd** [comment]
failing of this travis build proves this works: https://travis-ci.org/geneontology/go-ontology/builds/338712020?utm_source=email&utm_medium=notification

**Comment by pgaudet** [comment]
I cannot tell if it's fixed: it does pick up the error but still the build has worked; is this what we expect ? 

![image](https://user-images.githubusercontent.com/4782928/35969363-dec96ee0-0cc6-11e8-9c37-b138971109d2.png)


Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Yeah this is fixed. I just updated my branch with your fixed master, and my check passes. Rerunning travis now.
