### ISSUE TITLE
NTR: beta-pinacene synthase activity

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#15055]
Please let me know of any questions. 
Thanks,
Bob Dodson

Name: beta-pinacene synthase activity
Ontology: function
Synonyms:  
Definition: Catalysis of the cyclization of geranylgeranyl pyrophosphate (GGPP) to yield the monocyclic diterpene beta-pinacene.
CHEBI:139494
Child of: GO:0010333 terpene synthase activity

References:
PMID:28696553 Mechanisms of the Diterpene Cyclases Beta-Pinacene Synthase from Dictyostelium discoideum and Hydropyrene Synthase from Streptomyces clavuligerus.

**Comment by hdrabkin** [comment]
Is this 
EC 4.2.3.122
(+)-beta-pinene synthase (EC 4.2.3.122, (+)-pinene cyclase, cyclase III) is an enzyme with systematic name geranyl-diphosphate diphosphate-lyase ((+)-beta-pinene-forming).[1][2] This enzyme catalyses the following chemical reaction
  geranyl diphosphate ⇌(+)-beta-pinene + diphosphate

**Comment by rjdodson** [comment]
@hdrabkin 
This does not appear to be EC 4.2.3.122 (+)-beta-pinene synthase, although it is certainly confusingly close in name. 
The enzyme in question here has only been recently described, and I used the name given by the authors: "beta-pinacene synthase". They do not provide an EC number. I also previously requested the addition of the the new compound "beta-pinacene" at CHEBI, and they approved and assigned it as CHEBI:139494.
Please let me know if you have further questions.
Thanks,
Bob

**Comment by hdrabkin** [comment]
@rjdodson , so you have  a suggested is_a parent

**Comment by rjdodson** [comment]
@hdrabkin:  apologies, I forgot to add a suggested parent. 

Going back and checking my notes, I see that I had meant to add as a suggested parent:

GO:0010333 terpene synthase activity

In the paper, the authors describe this as a cyclase reaction, and in this case it is described as a cyclization reaction of the linear terpene geranylgeranyl pyrophosphate (GGPP) to beta-pinene (a monocyclic diterpene). So I would suggest GO:0010333 terpene synthase activity as parent, which is a child of GO:0016838. 

Sorry I forgot to add this previously. Thanks and let me know if you have further questions.
Bob

**Comment by hdrabkin** [comment]
Thanks Bob; I saw it finally in the orginal text. Coffee not kickeing in yet

**Comment by hdrabkin** [comment]
GO:0106101
done
