### ISSUE TITLE
NTR:polyphosphate-mediated signaling

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#15052]
Hello:

Two recent papers from Dictyostelium suggest the need for a new GO process term for polyphosphate signaling.  

Name: polyphosphate-mediated signaling
Ontology: biological_process
Synonyms: polyphosphate signaling
Alternate IDs: None
Child of: GO:0007267: cell-cell signaling, or GO:0035425: autocrine signalling
Definition: Any process that mediates the transfer of information from one cell to another using c-di-GMP as the signal.

It seem customary to also create regulation terms for signaling pathways, so we should probably create these associated terms as well.

regulation of polyphosphate-mediated signaling
positive regulation of polyphosphate-mediated signaling
negative regulation of polyphosphate-mediated signaling

References:
PMID:27519410  Extracellular polyphosphate inhibits proliferation in an autocrine negative feedback loop in Dictyostelium discoideum.
PMID:28584190  Extracellular polyphosphate signals through Ras and Akt to prime Dictyostelium discoideum cells for development. 

Please let me know if you have further questions. 

Bob

**Comment by vanaukenk** [comment]
@rjdodson 
Do you know if polyphosphate-mediated signaling is always autocrine signaling?  If so, I can make the new term a child of GO:0035425, but if we're not sure, then I will just make the new term a child of GO:0007267.  
Also, if you have gene products to annotate to the regulation terms, then I'm happy to create them.  Otherwise, we can wait until they are needed for annotation

**Comment by rjdodson** [comment]
@vanaukenk 
I do not know if polyphosphate-mediated signaling is always autocrine signaling. It is clear that the polyphosphate is extracellular, but I was really just basing the request for autocrine signaling on the author's statements. I have no problem with you making this a child of GO:0007267, cell-cell signaling, and maybe that is best.

I also do not at this time have gene products to annotate with the regulation terms, so fine to wait on creating them until needed. 

That answers your questions, but maybe for more background in case you're interested: I really only have two GPs that I was planning to annotate with "polyphosphate signaling" and even they I think would be considered as a "part_of" or "involved_in" type relationship, and not really directly involved. In addition, I have a number of genes that have been identified by proteomics analysis to be either up or down-regulated in response to polyphosphate. So these will need a HTP ev code and again are not directly related to polyphosphate-mediated signaling. Last year, I encountered a similar situation with c-di-GMP signaling. I initially submitted a NTR for this as "response to c-di-GMP" 

https://github.com/geneontology/go-ontology/issues/14175

but was persuaded to switch this to "c-di-GMP-mediated signaling"

https://github.com/geneontology/go-ontology/issues/14180

I'm still a little unclear on how best to curate these.  

Anyway, sorry...I'm not trying to complicate this ticket. If you want to comment on any of this please feel free, but if you would rather just create the terms and move on, that's fine too! I guess this will all eventually be  clearer in GO-CAM models with the ability to use additional relations between GPs, BPs and MFs.

**Comment by vanaukenk** [comment]
Hi @rjdodson - no worries.

I can create a new term for 'polyphosphate-mediated signaling'.  If I'm reading the paper abstracts correctly, the Ras and Akt gene products could be annotated to this term.  Is that consistent with what you were thinking?  For GO, we would consider the statement: gene product X 'involved_in' process Y, as being directly involved, though, so if that's not the correct statement then we would need to come up with another way to annotate these gene products.

For the differential expression experiments, I agree with @ukemi in #14175; it is difficult to know from these types of experiments whether the differentially expressed gene products are 'involved_in' a response or downstream of the response, so even with an HTP evidence code, it's not clear what the correct annotation statement would be.  We need to convene a working group to address the 'response to' terms and their use, as this is a persistent issue.

**Comment by rjdodson** [comment]
Hi @vanaukenk 
Yes, that is more or less what I was thinking. I was going to curate the Ras and Akt gene products, and maybe some others from the other reference, with the new GO term "polyphosphate-mediated signaling". And as noted, I wasn't really sure about the genes in the expression experiments, but based on your and David's comments, I now will not do so. So please create the new GO term when you have a chance, and I promise to use it with restraint. 

Thanks,
Bob
