### ISSUE TITLE
GO:0043332 - mating projection tip missing parentage?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15076]
Hi, I think there should be an is_a relationship added here:

GO:0043332 - mating projection tip 
is_a
GO:0051286 - cell tip

**Comment by krchristie** [comment]
I agree. 

In addition, right next to 'mating projection tip', there was a term for 'hyphal tip' that I thought was also a 'cell tip', so I have added this parentage to both terms 'mating projection tip' and 'hyphal tip'.

-Karen
