### ISSUE TITLE
horsetail nucleus -obsolete?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15077]
Hi,

we wonder if "horsetail nucleus" should be obsoleted? 
These annotations could be moved to nucleus during "during meiotic prophase" / during meiotic G2 / during horsetail nuclear movement

(we still want to keep "horsetail nucleus leading edge" but it is enough that this is_a nuclear part)

**Comment by ValWood** [comment]
Sounds OK.
you could rename GO:0071687    horsetail nucleus leading edge
to nucleus leading edge  (narrow synonym horsetail nucleus leading edge)

**Comment by vanaukenk** [comment]
Okay, here's the plan:

1) Obsolete GO:0071686 horsetail nucleus
2) Add 'horsetail nucleus' as a narrow synonym of GO:0005634 'nucleus'
3) Obsolete GO:0071687 horsetail nucleus leading edge
4) Add new term GO:new 'nucleus leading edge'
5) Add 'horsetail nucleus leading edge' as a narrow synonym of GO:new 'nucleus leading edge'

**Comment by vanaukenk** [comment]
Actually, will just rename GO:0071687 to 'nucleus leading edge' as @ValWood suggested.
