### ISSUE TITLE
GO:0003861 definition update

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#15078]
The current definition for that term, "Catalysis of the reaction: 3-isopropylmalate = 2-isopropylmaleate + H2O.", is incorrect.  Please update to the correct definition, "Catalysis of the reaction: (2R,3S)-3-isopropylmalate = (2S)-2-isopropylmalate." (see EC 4.2.1.33, https://enzyme.expasy.org/EC/4.2.1.33)

Thanks,
Ingrid

**Comment by hdrabkin** [comment]
Done.
