### ISSUE TITLE
MP: plasma membrane raft distribution

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15079]
add parent 
"plasma membrane organization"

**Comment by ValWood** [comment]
Whoops sorry, that might be wrong. Localization isn't necessarily part of organization.

Although here it seems to be because if you are localizing something which is a part_of some larger entity, presumably you are organizing the larger entity? So although not organization for the raft itself, it is organization of the entire PM membrane?

 @ukemi?

**Comment by ValWood** [comment]
I'm not receiving notifications from GitHub, even for tickets I opened?

**Comment by pgaudet** [comment]
Check your settings ?

**Comment by ukemi** [comment]
Localization isn't necessarily part of organization, but in this case I think it is. I think controlling the distribution of the rafts would be considered part of the localization of the plasma membrane.
