### ISSUE TITLE
Make L-amino acid default

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15087]
follow on from
https://github.com/geneontology/go-ontology/issues/15022

Make L-amino acid the default (but exact synonym)

Only make a term if D-form only if required

**Comment by pgaudet** [comment]
https://en.wikipedia.org/wiki/Amino_acid

**Comment by deustp01** [comment]
Works fine for mammals, but what about bacteria that use D-amino acids in their cell walls and L-amino acids in their proteins, and thus synthesize, transport both and distinguish between them?

**Comment by pgaudet** [comment]
Thanks @deustp01 
Do they synthetize all amino acids as D-form ?

**Comment by deustp01** [comment]
I don't know - @hdrabkin ? Or Jim Hu?

**Comment by pgaudet** [comment]
According to wikipedia (I know...) "These are all L-stereoisomers ("left-handed" isomers), although a few D-amino acids ("right-handed") occur in bacterial envelopes, as a neuromodulator (D-serine), and in some antibiotics.[12]" https://en.wikipedia.org/wiki/Amino_acid

**Comment by ValWood** [comment]
Is this out of date?

**Comment by pgaudet** [comment]
Yes, we will deal with this with the CHEBI 7.3 ticket
https://github.com/geneontology/go-ontology/issues/27059
