### ISSUE TITLE
difference between  GO:0102083 & GO:0004150

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15080]
are
GO:0102083   7,8-dihydromonapterin aldolase activity
and
GO:0004150	dihydroneopterin aldolase activity
the same thing?

**Comment by hdrabkin** [comment]
different substrates; note that the two have different metacyc xrefs

**Comment by ValWood** [comment]
@hdrabkin  which is the correct one for the
trifunctional dihydropteroatesynthase/2-amino-4-hydroxy-6-hydro xymethyldihydropteridinediphosphokinase/dihydroneopterin aldolase
?
https://www.pombase.org/gene/SPBC1734.03

do you know?

**Comment by ValWood** [comment]
Neither has many EXP annotations, but it seems tat maybe  S. cerevisiae uses the incorrect term, and I ISS'd to that would you agree?

Is there a bacterial/ eukaryotic difference (if so taxon restrictions could be added)

**Comment by deustp01** [comment]
Or is this distinction too fine-grained? Do all of the (few) annotated enzymes have broad enough substrate specificity to handle both substrates?

**Comment by hdrabkin** [comment]
I contacted Peifen to clarifiy and am waiting.

**Comment by hdrabkin** [comment]
@pzhang Peifen responds
(by proposed term she means the GO:0102083 )

"The two terms are different, as you pointed out that the substrates are different (although the substrates are isomers). I would remove EC 4.1.2.25 from the proposed term. You could use this PubMed as a reference for the proposed term GO:0102083: PMID:15107504 "

**Comment by hdrabkin** [comment]
This is done; closed.
