### ISSUE TITLE
NTR: PNGase complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15086]
Hi,
Can you please help me adding this complex term related to GO:0019789 molecular function. I haven’t specified the stoichiometry in the definition since it seems not be conserved (see 16249333 and 15964983).
Thanks to you and to @bmeldal,

Livia

Term:
Name: PNGase complex
Def: A protein complex responsible for the catalysis of the reaction: 4-N-(N-acetyl-D-glucosaminyl)-protein + H2O = N-acetyl-beta-D-glucosaminylamine + peptide L-aspartate. This reaction is the hydrolysis of an N4-(acetyl-beta-D-glucosaminyl)asparagine residue in which the N-acetyl-D-glucosamine residue may be further glycosylated, to yield a (substituted) N-acetyl-beta-D-glucosaminylamine and the peptide containing an aspartic residue.
References:
GOC:lnp
PMID: 16249333 and 15964983
Relationships:
is_a GO:1905368 peptidase complex
capable_of GO:0019789 SUMO peptide-N4-(N-acetyl-beta-glucosaminyl)asparagine amidase activity
capable_of_part_of GO:0035977 protein deglycosylation involved in glycoprotein catabolic process
DB xref:
IntAct: EBI-16422385

**Comment by krchristie** [comment]
I have added the capable_of relationship to the GO ID you requested, but note that the term GO:0019789 is named "**SUMO transferase activity**" 
NOT: "**SUMO peptide-N4-(N-acetyl-beta-glucosaminyl)asparagine amidase activity**"

If you think the MF term needs to be something different let me know.

**Comment by liviap** [comment]
ups, there is something wrong: it should be
 capable_of GO:0000224 peptide-N4-(N-acetyl-beta-glucosaminyl)asparagine amidase activity
it has nothing to do with sumo... my apologies

**Comment by krchristie** [comment]
Thanks for the speedy correction, I'll be able to fix it before I even finish committing the term.
