### ISSUE TITLE
MP GO:0000916 - actomyosin contractile ring contraction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15082]
should
GO:0000916 - actomyosin contractile ring contraction
be a descendant of
~GO:0030036 actin cytoskeleton organization?~

GO:0044837   actomyosin contractile ring organization

**Comment by pgaudet** [comment]
Manual annotations are from pombase, SGD, dictybase and Flybase

If that seems OK to these groups I'll add the parent. 
@srengel 
@hattrill 
@pfey03 

Thanks, Pascale

**Comment by hattrill** [comment]
Ok with me. But not my specialist subject!

**Comment by pfey03** [comment]
Yes, I agree 100%. But when looking at the graph, there is also the parent term 

GO:0036213 - contractile ring contraction
Def:"The process of an actomyosin ring getting smaller in diameter."

GO:0000916 - actomyosin contractile ring contraction
The process of an actomyosin ring getting smaller in diameter, in the context of cytokinesis that takes place as part of a cell cycle.

1. Is there any contractile ring contraction not part of cytokinesis / cell division? My ignorance if the answer is yes
2. If 1 is yes, then both should be be a descendant of 'actin cytoskeleton organization' if it's no, then these terms should be merged and a descendent of GO:0030036.

Thanks,
Petra

**Comment by srengel** [comment]
seems like yes, GO:0000916 actomyosin contractile ring contraction should be a descendant of GO:0030036 actin cytoskeleton organization

**Comment by ValWood** [comment]
I changed the suggestion to
GO:0044837 actomyosin contractile ring organization

pfey03  GO:0036213 - contractile ring contraction
is to cover plant cytokinesis I think uses a different mechanism (not actomyosin)

**Comment by ValWood** [comment]
![actinomyosin](https://user-images.githubusercontent.com/7359272/36163510-82737a2c-10e1-11e8-8d74-4b2cfe175d09.jpg)


so it seems that
i) "actomyosin contractile ring contraction" should be part of "actomyosin contractile ring organization"

AND
ii) actomyosin contractile ring organization
should be part of "cytoskeleton dependent cytokinesis"
