### ISSUE TITLE
actin servering parentage question

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15092]
Should
GO:0051014 - actin filament severing
The process in which an actin filament is broken down into smaller filaments.

be part of 
GO:0030042 - actin filament depolymerization

I ask because a few "actin actin depolymerizing factors"
are actually actin severing  or severing regulators

and "debranching" is a type of severing, and "debranching" seems to be a type of depolymerization?

**Comment by ukemi** [comment]
No. Proteins can sever actin filaments into smaller fragments without depolymerizing the filament.
