### ISSUE TITLE
NTR: NAGS/NAGK complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15090]
Hi,

Can you please help me adding this complex term associated to GO:0004042 and GO:0003991 molecular functions. 
Thanks,

Livia
PS: @bmeldal would you please give it a look as well?

Term:
Name: NAGS/NAGK complex

Def: A protein complex that acts both as N-acetylglutamate synthase (NAGS) catalysing the production of N-Acetylglutamate from glutamate and acetyl-CoA, and as N-acetylglutamate kinase (NAGK) catalysing the reaction ATP + N-acetyl-L-glutamate = ADP + N-acetyl-L-glutamyl 5-phosphate. 

References:

GOC:lnp

PMID: 11553611

Relationships:

is_a GO:0031248 protein acetyltransferase complex

capable_of GO:0003991 acetylglutamate kinase activity

capable_of GO:0004042 acetyl-CoA:L-glutamate N-acetyltransferase activity

capable_of_part_of GO:0006526 arginine biosynthetic process

part_of GO:0005759 mitochondrial matrix

DB xref:

IntAct: EBI-15101175

**Comment by hdrabkin** [comment]
any idea on how many components?

**Comment by bmeldal** [comment]
As it's a generic complex based on an activity I would hazard a guess that might vary with specific complexes and species... but I haven't looked.

**Comment by liviap** [comment]
the components vary from yeast (dimer) to vertebrate (mostly) tetramer (see 26068232 ) so I would leave it as a general protein complex.

**Comment by hdrabkin** [comment]
Ok, just checking; This  will go in today

**Comment by liviap** [comment]
thanks a lot

**Comment by hdrabkin** [comment]
GO:0106098
Done
