### ISSUE TITLE
Need anatomy imports for bone morphogenesis terms

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15099]
Terms added, but still need UBERON terms for the logical defs. Need to request:

UBERON:0008913- perichondral bone
UBERON:0008907- dermal bone
UBERON:0007842- membrane bone
UBERON:0002513- endochondral bone
UBERON:0012075- replacement bone

**Comment by ukemi** [comment]
Requested. We need a new import build.

**Comment by ukemi** [comment]
Now also need primitive palate. Added to the text file, but now the Travis checks are failing in the pull request.
UBERON:0012316- primitive palate

**Comment by ukemi** [comment]
#15102

**Comment by balhoff** [comment]
@ukemi please check if you've got what you need now. I updated the Uberon import.
