### ISSUE TITLE
never_in_Fungi? really?

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#15101]
we got an email from P2GO with a bunch of taxon_constraint violations for these terms:
GO:0001056 | RNA polymerase III activity
GO:0042797 | tRNA transcription by RNA polymerase III
GO:0006383 | transcription by RNA polymerase III
GO:0001195 | maintenance of transcriptional fideli...
GO:0070898 | RNA polymerase III transcriptional pr...
GO:0006384 | transcription initiation from RNA pol...
GO:0042791 | 5S class rRNA transcription by RNA po...
GO:0001152 | transcription factor activity, RNA po...
GO:0006386 | termination of RNA polymerase III tra...
GO:0031564 | transcription antitermination
GO:0001073 | transcription antitermination factor ...

why are these suddenly never_in_Fungi?  is something amiss, or did we miss a conversation?

**Comment by ValWood** [comment]
Wow thats odd, because as far as I'm aware the taxon constraints aren't active  right now!

**Comment by cmungall** [comment]
cc-ing @tonysawfordebi for the P2GO pipeline part.

@dougli1sqrd and @kltm will be announcing the new URLs for each groups reasoner violation reports shortly

**Comment by pgaudet** [comment]
Sorry about that ! 
* The Pol II problems were a side effect of the merge from #9617
* For antitermination, the problem is that it was a child of attenuation, so I moved it out, and directly under 'regulation of DNA-templated transcription, termination'. 

Let me know if you see other problems. 

Thanks, Pascale

**Comment by cmungall** [comment]
@tonysawfordebi ignore my previous ping, I assumed this was a tools and not an ontology thing
