### ISSUE TITLE
"response to" terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15103]
We should take a good look what we are really using these  terms to annotate.

Many appear to represent conditions. Some are phenotypes. Some are the target of a drug. Some are requested to construct logical definitions  of phenotypes and should not be used in annotation (maybe we could do this differently?). It often isn't clear which BP  the response  is  related to (when it usually  could be). etc. You can throw any chemical at an organism and most times there will be some "response"...what does it mean?

Some examples:
cellular response to topoisomerase inhibitor? (drug target?)
cellular response to gold(3+)????
cellular response to alkane?
cellular response to boron-containing substance levels?
GO:1901593 response to GW 7647 ?????
GO:0072757 cellular response to camptothecin (camptothecin is A topoisomerase inhibitor see above)
GO:1904842 response to nitroglycerin? hmmm....
GO:0070301 cellular response to hydrogen peroxide?? isn't that just the oxidative stress response? It's a condition used to produce oxidative stress (response to oxidative stress is a useful one, if qualified).

It would be better if these  terms were only used   as refinements to true process annotations:

"signalling pathway x" occurs_during "response to y"
or "cellular detoxification" in response to y.

 It is difficult to assess what is "unknown" with so many uninformative "response to x " annotations...

**Comment by ValWood** [comment]
Comment from @mah11 
Re "response to" terms: quite a few of the strange-looking ones are there to allow other ontologies (including FYPO) to use them in logical definitions or other cross-references. Any such terms should be flagged as not for gene product annotation (I thought they were, but it's certainly possible that some were missed).

https://mailman.stanford.edu/pipermail/go-ontology/2016-April/007432.html

**Comment by ValWood** [comment]
I deleted the  discussion about "response to" from
https://github.com/geneontology/go-annotation/issues/1807

this is something for the future...

@RLovering 
@rachhuntley 
@pgaudet

**Comment by vanaukenk** [comment]
@ValWood 
Can you move these comments to #14303?
I've added a new label, Request for proposal, to that ticket.
We need a concrete proposal for creating ontology terms as well as annotation usage for 'response to' terms.  This may require a working group, but there are likely several people with a stake in this area of the ontology.
Thx.

**Comment by vanaukenk** [comment]
Moved comments to #14303.

Closing.
