### ISSUE TITLE
Remove logical definition secondary metabolic/biosynthetic/catabolic process terms 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15113]
To address https://github.com/geneontology/go-ontology/pull/14769
ChEBI merged primary and secondary metabolic processes; we cannot use these terms in logical definitions anymore. 

Pascale

**Comment by pgaudet** [comment]
@cmungall if this is what you needed please merge.

**Comment by dianeoinglis** [comment]
Please note that "metabolic process" and "secondary metabolic process' are incorrect for these term names. The terms are "metabolite biosynthetic process" and "secondary metabolite biosythetic process." Diane

**Comment by pgaudet** [comment]
What do editors this of @dianeoinglis 's suggestion ?

**Comment by dianeoinglis** [comment]
To further clarify, it would be good if the situation re the merge in ChEBI were included in the definitions:

'metabolite metabolic process'
include: ..."metabolism of primary or secondary metabolites..."

Diane

**Comment by pgaudet** [comment]
@dianeoinglis 

If we change the term labels we'll end up with 'primary metabolite metabolic process'; is that what you mean ? I am not sure this is clearer for users. I can add this as a synonym. 

Also, where do you suggest we add 

> include: ..."metabolism of primary or secondary metabolites..."
in the definition ("The chemical reactions and pathways involving those compounds which are formed as a part of the normal anabolic and catabolic processes. These processes take place in most, if not all, cells of the organism")? 

Thanks, Pascale

**Comment by dianeoinglis** [comment]
OK. I've worked through the tree and the merging of primary and secondary process and their definitions require changes to both definitions and terms to maintain scientific accuracy. The merged definition will be incorrect if the statement ..."as part of the normal anabolic and catabolic process" remains as this is not true for secondary metabolism. Secondary metabolites are typically optional, are not required for growth of an organism but typically confer some advantage in the environment such as escape from predation or competition with other species, more...Furthermore, all organisms do not produce a given 'metabolite but are more commonly made by a small subset or just one organism from a taxonomic group. 

So, the definitions of 'biosynthetic/catabolic/anabolic process must accommodate both types of metabolites.

Next, therms 'primary metabolic/'biosynthetic/catabolic/anabolic process' and 'secondary 'biosynthetic/catabolic/anabolic process' should be obsoleted and replaced with 'metabolite 'biosynthetic/catabolic/anabolic process' with the synonyms ''metabolite metabolism,' 'metabolite biosynthesis,' ''metabolite metabolic process,' etc for the catabolic and anabolic process terms.Then, all of the 'primary and secondary metabolites 'biosynthetiic process' terms have to be moved under their respective parent terms, 'metabolite 'biosynthetic/catabolic/anabolic process.'

An additional option that would require much work is to further create the child terms, 'fungal/bacterial/plant metabolic process' but this probably is not necessary at this point.

I hope this description and explanation is clear. Let me know if I have left anything out or if there are clarifications needed.

Diane

**Comment by pgaudet** [comment]
Hi @dianeoinglis 

A few things: 

- ChEBI merged primary and secondary metabolic process, but GO didn't (as far as I know we dont intend to; @ukemi is this right?) 
- As far as I understand GO doesn't use 'metabolic process' in the sense of acting on a 'metabolite'; it's much wider ; for example 'DNA-dependent replication' is a biosynthetic process - we couldn't have it under 'metabolite biosynthesis (right?) 

(To be clear: all I did here was to remove the logical definitions that referred to ChEBI primary and secondary metabolic process - no term merge was done, no definitions were changed). 

So I dont think there is anything else to do with this ticket. 

@ukemi is what I wrote here accurate? 
@dianeoinglis please close the ticket unless you see another action. 

Thanks, Pascale

**Comment by ukemi** [comment]
ChEBI doesn't represent processes. They merged primary and secondary metabolite into metabolite. As far as I know, we don't have plans to merge primary metabolic process and secondary metabolic process. As for the second question, it depends on how you define a metabolite. In ChEBI, it is a role. I suspect that this tells us that we will need to revisit our classifications.

**Comment by pgaudet** [comment]
Thanks for the clarification for point 1 @ukemi

WRT point 2: As far as I can tell we don't use 'metabolite' anywhere else in the logical definitions, so this avoids the problem, doesn't it @ukemi ?

**Comment by ukemi** [comment]
I just checked. You are correct. We do not use the ChEBI role in GO terms.

**Comment by dianeoinglis** [comment]
Thanks.
