### ISSUE TITLE
GO:2000640 - positive regulation of SREBP signaling pathway parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15122]
GO:2000640 - positive regulation of SREBP signaling pathway
is a 
is_a positive regulation of transcription by RNA polymerase II

I don't think we now normally connect the signalling pathway to transcription do we?

**Comment by RLovering** [comment]
see BMP signaling pathway

**Comment by vanaukenk** [comment]
@ValWood @RLovering 

GO:0030509 BMP signaling pathway
GO:0008293 torso signaling pathway

are both asserted is_a children of 

GO:0006357 regulation of transcription by RNA polymerase II

and

GO:0032933 SREBP signaling pathway

is an asserted is_a child of GO:0045944 positive regulation of transcription by RNA polymerase II promoter

(but note there is also GO:0010735 positive regulation of transcription via serum response element binding as a child of GO:0045944)

We're discussing here in Denver, but it does seem that for signaling pathways that ultimately regulate transcription the is_a parentage between the signaling pathway and regulation of transcription is correct.  However, it also looks like the ontology is not complete for these relationships, e.g. GO:0060070 canonical Wnt signaling pathway does not have a relation to GO:0006357 regulation of transcription by RNA polymerase II.

Thoughts?

**Comment by ValWood** [comment]
test

**Comment by ValWood** [comment]
test

**Comment by ValWood** [comment]
Apologies I wasn't watching the tracker for some reason. If you tagged me in anything the past few days and I didn't respond, pls re-ping me...

This one later I'll respond to later...

**Comment by ValWood** [comment]
I thought that a decision was made not to try to model the regulation of transcription by a signalling pathway in the ontology.  MAP kinase signalling, TOR signalling etc all regulate transcription as one of their responses but don't they all  do other things too?

I had assumed that we would make independent annotations for gene specific regulation of transcription  on the transcription factor itself (capturing the gene products regulated). 

The reason I brought this up is that the  SREBP signaling pathway is an odd case. It involves the release of an ER membrane bound TF during response to hypoxia. The release of the TF is complicated and tightly controlled and involved a ubiquitin ligase complex, a protease, and the proteasome.  It also involves some oxygen sensing that is done by a ribosomal subunit. The consequence is, that all of these gene products which are involved in the regulation of SREBP signalling pathway become annotated to "regulation of transcription".

This looks very odd, but I'm not sure what the solution is. I just have a gut feeling that they should be separated in some way......

**Comment by pgaudet** [comment]
Since we removed the link between the pathway and regulation of transcription for BMP and torso, I am removing it from SREBP as well.
