### ISSUE TITLE
NTR: 2-keto-3-deoxy-L-rhamnonate aldolase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#15130]
As a child of GO:0016832.  Proposed definition: Catalysis of the reaction 2-dehydro-3-deoxy-L-rhamnonate = pyruvate + (S)-lactaldehyde.  
This is EC 4.1.2.53, http://www.enzyme-database.org/query.php?name=4.1.2.53.

Thanks,
Ingrid

**Comment by hdrabkin** [comment]
Hi Ingrid. Could you please also supply a PMID to be used as a reference. Thanks

**Comment by keseler** [comment]
PMID 18754683
Thanks!

**Comment by hdrabkin** [comment]
GO:0106099
Done.
