### ISSUE TITLE
MP 	L-phenylalanine:2-oxoglutarate aminotransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15138]
shoudl
L-phenylalanine:2-oxoglutarate aminotransferase activity
be a descendant of
aromatic-amino-acid:2-oxoglutarate aminotransferase activity

?

**Comment by ukemi** [comment]
Yup.

**Comment by krchristie** [comment]
Agreed. 

In looking at the two terms, I also noticed that the L-phenylalanine term is associated with multiple EC numbers, possibly related to this interesting note on the entry for 2.6.1.57 (https://enzyme.expasy.org/EC/2.6.1.57):

**ENZYME entry: EC 2.6.1.57**
**Accepted Name**: Aromatic-amino-acid transaminase.
**Reaction catalysed**: An aromatic amino acid + 2-oxoglutarate <=> an aromatic oxo acid + L-glutamate
**Cofactor(s)**: Pyridoxal 5'-phosphate.
**Comment(s)**
- L-methionine can also act as donor, more slowly. 
- Oxaloacetate can act as acceptor. 
- Controlled proteolysis converts the enzyme to EC 2.6.1.1.

In looking at the EC pages for 2.6.1.5, 2.6.1.5, and 2.6.1.9, it is clear that these EC numbers are not appropriate descriptions of the GO term "L-phenylalanine:2-oxoglutarate aminotransferase activity" (GO:0080130) (and Harold Drabkin agrees). Thus, I am removing these EC number references from this term.

**Comment by ValWood** [comment]
yup, also opened a ticket for that yesterday:
https://github.com/geneontology/go-annotation/issues/1816
