### ISSUE TITLE
NTR: COPII vesicles tethering complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15145]
Hi,

Can you please help me adding this complex term, I'm not totally sure about the name, it is called 'GRASP65–GM130 complex' in human (9628863) and  it's known to be composed by bug1 and grh1 proteins in yeast
Thanks,

Livia
PS: @bmeldal would you please give it a look as well?

Term: 
Name: COPII vesicles tethering complex
Def: A protein complex that resides in the cis-golgi membrane and plays a role in the tethering of COPII vesicles, through an interaction with vesicle tethering proteins (p115 in H. Sapiens and Uso1 S. cerevisiae), granting the cis-Golgi and endoplasmic reticulum to Golgi vesicle-mediated transport.
It is composed by GRASP65 and GM130 protein in H. Sapiens and by Bug1 and Grh1 proteins in S. cerevisiae.
References
GOC:lnp
PMID: 21482742 and 9628863
Relationships:
is_a GO:0099023 tethering complex
capable_of_part_of GO:0007030 Golgi organization 
part_of GO:0033106 cis-Golgi network membrane 

DB xref:
IntAct: EBI-14061261
GRASP65–GM130 complex [exact]
Bug1-Grh1 complex [narrow]

**Comment by bmeldal** [comment]
H. sapiens - small "s" ;-)
Although, I think we usually just say "human" in the defs.
Birgit

**Comment by hdrabkin** [comment]
GO:0106102

**Comment by hdrabkin** [comment]
done
