### ISSUE TITLE
Travis Checks not running!

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15153]
We have made several pull requests over the last hour and there is no indication that the Travis checks are running.

**Comment by ukemi** [comment]
Seems that they are slow, but have recovered.

**Comment by vanaukenk** [comment]
Sorry - we need to re-open this ticket.
The Travis checks don't seem to be starting now.

**Comment by balhoff** [comment]
I think it's a transient Travis problem: https://www.traviscistatus.com

> We are currently seeing a backlog of public/open source builds on all our infrastructures. Apologies for the inconveniences.

**Comment by vanaukenk** [comment]
Okay, thanks for the update and Link, @balhoff
