### ISSUE TITLE
Obsoletion notice for 'protein complex biogenesis' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15173]
Dear all, 

The proposal has been made to obsolete protein complex biogenesis in #12782 
The reason for obsoletion is that 'biogenesis' as related to a protein is translation, and there is no indication that the members of these complexes are synthesized in a particular way. Historically biogenesis terms were created for some processes when they knew that the production of something was affected but were not sure whether it was the transcription, translation, assembly etc.

There are a few experimental annotations that may need to be rehoused: 

'protein complex biogenesis' – 0 EXP
'chloroplast ribulose bisphosphate carboxylase complex biogenesis' 5 EXP TAIR @tberardini 
'mitochondrial respiratory chain complex I biogenesis' 3 EXP - TAIR @tberardini & UniProt @ggeorghiou 
'mitochondrial respiratory chain complex II biogenesis' 1 EXP UniProt @ggeorghiou 
'mitochondrial respiratory chain complex III biogenesis' 8 EXP SDG @srengel UniProt @ggeorghiou  Flybase @hattrill 
'mitochondrial respiratory chain complex IV biogenesis' 12 EXP TAIR @tberardini  Flybase @hattrill SDG @srengel 
'proton-transporting ATP synthase complex biogenesis' 2 EXP TAIR @tberardini SDG @srengel 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 23, 2018. Unless objections are received by  Feb 23, 2018  we will assume that you agree to this change. 

Thanks, Pascale

**Comment by SuperManu74** [comment]
What about proteins involved in the splicing of component of the mitochondrial respiratory chain complex I such as Q9CA78 (Nuclear intron maturase). This really contributes to the biogenesis of the complex without being involved in protein translation. COnsidering that biogenesis of protein is only the translation step is absolutely ignoring all the process of gene processing to produce proteins. I am really confused here...which term can I use instead of "GO:0097031; mitochondrial respiratory chain complex I biogenesis" ?!?

**Comment by pgaudet** [comment]
Hi @SuperManu74
Can you please explain what you mean? According to UniProt Q9CA78 is invollved in intron splicing, not in complex assembly. 

Thanks, Pascale

**Comment by SuperManu74** [comment]
Q9CA78 is involved in the splicing of mRNA encoding proteins of the mitochondrial respiratory chain complex I, so when you disturb it you have impaired biogenesis of mitochondrial respiratory chain complex I subunits.

**Comment by pgaudet** [comment]
This is what we now call 'causally upstream of' in GO-CAM models 
Q9CA78 is not involved in biogenesis of mitochondrial respiratory chain complex I subunits - these either assemble on their own, or whatever chaperone is responsible should be annotated. 

Probably what you are looking for is to put the targets of Q9CA78 (ie, genes encoding proteins of the mitochondrial respiratory chain complex I), which would then result in an inference of the (indirect) role of Q9CA78 in biogenesis of mitochondrial respiratory chain complex I subunit. 

@vanaukenk @ukemi perhaps this should be added to our examples?

**Comment by vanaukenk** [comment]
I'll add the paper to our list of examples; we should create a GO-CAM for this paper:

https://www.ncbi.nlm.nih.gov/pubmed/24506473
