### ISSUE TITLE
GO:0042744 - hydrogen peroxide catabolic process, parentage (reasoning over roles from chebi)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15180]
GO:0042744 - hydrogen peroxide catabolic process is_a cofactor catabolic process why is that?

**Comment by pgaudet** [comment]
ChEBI puts it as a drug and a co-factor. Can you ask them to revisit this ?

**Comment by ValWood** [comment]
Presumably for CHEBI  is_a needs to always be true?
@ukemi  (so hydrogen peroxide would be neither?)

**Comment by ukemi** [comment]
I think it has to do with the roles. We really need to stop reasoning over them. @cmungall

**Comment by ukemi** [comment]
Unfortunately the roles are not true in all contexts. For example:

[Term]
id: GO:0046085 ! adenosine metabolic process
+is_a: GO:0017144 {is_inferred="true"} ! drug metabolic process
is_a: GO:0046128 {is_inferred="true"} ! purine ribonucleoside metabolic process

**Comment by krchristie** [comment]
Between removing grouping terms for cofactor metabolism: 
**obsoletion of grouping terms for "cofactor" & "coenzyme" roles** #19243 

and ceasing to reason over ChEBI roles:
**cessation of reasoning over ChEBI roles, i.e. stop inferring relationships like "ATP binding" is_a "drug binding"** #19479 

this is fixed.
