### ISSUE TITLE
proposal to obsolete GO:0051441 positive regulation of ubiquitin-protein ligase activity involved in meiotic cell cycle 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15196]
Dear all, 

The proposal has been made to obsolete
GO:0051440 regulation of ubiquitin-protein ligase activity involved in meiotic cell cycle
GO:0051442 negative regulation of ubiquitin-protein ligase activity involved in meiotic cell cycle
GO:0051441 positive regulation of ubiquitin-protein ligase activity involved in meiotic cell cycle
GO:0051437 positive regulation of ubiquitin-protein ligase activity involved in regulation of mitotic cell cycle transition

The reason for obsoletion is that GO:0051441 is a precomposed MF involved in process term.

it would be better to annotate

MF part of meiotic cell cycle (and to a more specific term explaining which aspect of the meiotic cell cycler)

GO:0051437 positive regulation of ubiquitin-protein ligase activity involved in regulation of mitotic cell cycle transition
MF part of meiotic cell cycle transition (and to a more specific term explaining which aspect of the meiotic cell cycle transition i.e metaphase/anaphase or G2/M etc). 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 27, 2018. Unless objections are received by Feb 27, 2018 we will assume that you agree to this change.

Thanks, Pascale

**Comment by ValWood** [comment]
GO:0051437
http://www.uniprot.org/citations/20659444
@vanaukenk  (this is just viability, I think I would do the appropriate neddylation MF and no process for now, it is pleiotropic  phenotypes

**Comment by ValWood** [comment]
for GO:0051441
- [ ]  SGD @srengel  (1)
- [ ] MGI @ukemi (1)
- [ ] Flybase @hattrill

**Comment by bmeldal** [comment]
What about the equivalent GO:0051439 regulation of ubiquitin-protein ligase activity involved in mitotic cell cycle? Shouldn't that also be obsoleted?

**Comment by pgaudet** [comment]
Hi @bmeldal 
Thanks for the reminder. Yes GO:0051439  will also go - there are no direct annotations however. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Thanks. There were 6 complexes with GO:0051439 which I have moved all up to the parent term as well.

**Comment by pgaudet** [comment]
For reference those are the annotations :

@ukemi  MGI:1914371 PMID:25246615
 @srengel  S000003084   PMID:17889668

I'm ready to merge this one. 

Thanks, Pascale
