### ISSUE TITLE
Release to SVN failing

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15195]
I got two emails this morning that the release to svn is failing. The link is not very informative.

release-go-to-svn - Build # 581 - Still Failing: Check console output at http://build.berkeleybop.org/job/release-go-to-svn/581/ to view the results.

**Comment by ukemi** [comment]
Seems to have something to do with this obsoletion:

Caused by: Error: Attempted to specify obsolete value obsolete storage protein import into fat body for consider tag.
on line: 90422

Was this term used in a consider tag and then obsoleted?

**Comment by pgaudet** [comment]
I see -GO:0015032 was a 'consider ' of another obsolete term (GO:0007590). 

I'll try to remove that. 

Pascale

**Comment by pgaudet** [comment]
I tried to fix the error, but I'll let @ukemi close the ticket if the problem is resolved. 

Pascale

**Comment by ukemi** [comment]
Seems to be fixed.
