### ISSUE TITLE
Unresolvable PURL in go-plus.json

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#15192]
I just noticed that the latest version of go-plus.json (or at least the latest one that we downloaded & processed) contains this version tag:

"version" : "http://purl.obolibrary.org/obo/go/releases/2018-02-18/extensions/go-plus.owl"

If, however, you try to follow the link, you get the following 404:

An Exception Has Occurred
Unknown location: /ontology-releases/2018-02-18/extensions/go-plus.owl

HTTP Response Status
404 Not Found

**Comment by pgaudet** [comment]
@kltm Is this still a problem ?

**Comment by balhoff** [comment]
The earliest release in the new pipeline [looks to be 2018-03-06](http://release.geneontology.org). I think this may eventually be addressed by https://github.com/geneontology/go-site/issues/483. It seems like we could close this ticket as covered by that one.
