### ISSUE TITLE
NTR: positive regulation of apoptosis in bone marrow

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15191]
Hello,

Could I request the positive regulation term for GO:0071839 "apoptotic process in bone marrow"?

For annotation of miR-146a from PMID:27908889.

If accepted, please add the following GO REFs:
GOC:rph
GOC:BHF_miRNA
GOC:BHF

Thanks,
Rachael.

**Comment by ukemi** [comment]
Annotation extensions?

**Comment by rachhuntley** [comment]
I don't mind doing annotation extensions, but the regulation and negative regulation of this term already exist.

**Comment by krchristie** [comment]
In light of the existing of the other two regulation terms, seems fine to create the pos reg term too.
