### ISSUE TITLE
NTR: new transmembrane transporter specificities

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15201]
urea import across plasma membrane PMID17218313
polyamine import across plasma membrane PMID17218313

pyridoxine import across plasma membrane -exists
http://amigo.geneontology.org/amigo/term/GO:1903075

spermidine  import across plasma membrane PMID: 15637075

pyridoxal  import across plasma membrane  -exists https://www.ebi.ac.uk/QuickGO/term/GO:1903075

zinc II ion transmembrane import into ER  PMID:11886869 ( note to self zhf1)

oligopeptide  import across plasma membrane PMID:22226946
dipeptide  import across plasma membrane PMID:22226946
tripeptide import across plasma membrane PMID:22226946

**Comment by pgaudet** [comment]
pyridoxine transport -> merge into pyridoxine tm transport
polyamine transporter -> merge into polyamine  tm transport
spermidine transport -> merge into polyamine  tm transport
pyridoxal -> merge into polyamine  tm transport
oligopeptide
dieptide
tripeptide

**Comment by pgaudet** [comment]
Created new terms: 
+[Term]
+id: GO:0140201
+name: urea import across plasma membrane
+namespace: biological_process
+def: "The directed movement of urea from outside of a cell, across the plasma membrane and into the cytosol." [PMID:17218313]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:16199 ! urea
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-20T10:15:45Z
+
+[Term]
+id: GO:0140202
+name: polyamine import across plasma membrane
+namespace: biological_process
+def: "The directed movement of a polyamine from outside of a cell, across the plasma membrane and into the cytosol." [PMID:17218313]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:88061 ! polyamine
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-20T10:24:54Z
+
+[Term]
+id: GO:0140203
+name: spermidine import across plasma membrane
+namespace: biological_process
+def: "The directed movement of spermidine from outside of a cell, across the plasma membrane and into the cytosol." [GOC:vw]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:16610 ! spermidine
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-21T19:10:07Z
+
+[Term]
+id: GO:0140204
+name: pyridoxal import across plasma membrane
+namespace: biological_process
+def: "The directed movement of pyridoxal from outside of a cell, across the plasma membrane and into the cytosol." [GOC:vw]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:17310 ! pyridoxal
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-21T19:17:27Z

**Comment by deustp01** [comment]
Pyridoxal (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17310) and pyridoxine (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16709) are different molecules. Neither one is a polyamine so the merger of pyridoxine into polyamine transport suggested by @pgaudet looks odd.

In @ValWood 's orignal comment, the same GO ID http://amigo.geneontology.org/amigo/term/GO:1903075 is given for both pyridoxine import (yes) and pyridoxal transport (no).

What am I missing here?

**Comment by pgaudet** [comment]
@deustp01 It was a typo! thanks

**Comment by pgaudet** [comment]
Created 3 new terms 
+[Term]
+id: GO:0140205
+name: oligopeptide import across plasma membrane
+namespace: biological_process
+def: "The directed movement of an oligopeptide from outside of a cell, across the plasma membrane and into the cytosol." [PMID:22226946]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:25676 ! oligopeptide
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-22T15:48:21Z
+
+[Term]
+id: GO:0140206
+name: dipeptide import across plasma membrane
+namespace: biological_process
+def: "The directed movement of a dipeptide from outside of a cell, across the plasma membrane and into the cytosol." [PMID:22226946]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:46761 ! dipeptide
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-22T15:49:19Z
+
+[Term]
+id: GO:0140207
+name: tripeptide import across plasma membrane
+namespace: biological_process
+def: "The directed movement of a tripeptide from outside of a cell, across the plasma membrane and into the cytosol." [PMID:22226946]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:47923 ! tripeptide
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-02-22T15:49:55Z
