### ISSUE TITLE
MP copper ion import into ascospore-type prospore

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15202]
copper ion import into ascospore-type prospore

needs to be is_a
GO:0035434    copper ion transmembrane transport

**Comment by mah11** [comment]
that doesn't make sense - GO:0097430 is_a GO:0035434, not part_of, surely?

**Comment by ValWood** [comment]
fixed

**Comment by pgaudet** [comment]
Hi @ValWood 
We don't have very many terms of that pattern (transport into cell type) - should we not leave this to extensions? 

Thanks, Pascale

**Comment by ValWood** [comment]
correction
copper ion import across prospore membane
GO:0005628    prospore membrane

(more accurate!)

**Comment by pgaudet** [comment]
This still sound cell-typ-ish but OK ! 

BTW this is from extracellular to extracellular, right ? (It was was child of intracellular transport). 

Thanks, Pascale

**Comment by pgaudet** [comment]
New def: The directed movement of copper ions from outside of a cell, across the ascospore-type prospore membrane and into the cytosol.
OK ?

**Comment by ValWood** [comment]
Yeah but we do have a lot of stuff already describing prospore membrane biology so it seems OK ;)

def OK.

**Comment by ValWood** [comment]
We don't have anything else to describe this structure, because the  existing plasma membrane is the ascus, it isn't really just a cell type specific term- it's describing a structure we cannot annotate any other way.

**Comment by pgaudet** [comment]
OK !
