### ISSUE TITLE
MP GO:0042776 - mitochondrial ATP synthesis coupled proton transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15207]
GO:0042776 - mitochondrial ATP synthesis coupled proton transport

add the parent
GO:0006091    generation of precursor metabolites and energy

Its a rubbish term, but I use this to group energy generation, as nothing else suitable

**Comment by ValWood** [comment]
maybe this is the term
GO:0015985    energy coupled proton transport, down electrochemical gradient
 requiring 
GO:0006091
prent?

**Comment by ValWood** [comment]
Affects slims

**Comment by hdrabkin** [comment]
Notes
GO:0015985  def The transport of protons across a membrane to generate an electrochemical gradient (proton-motive force) that provides energy for the synthesis of ATP or GTP.

GO:0042776 def hTe transport of protons across a mitochondrial membrane to generate an electrochemical gradient (proton-motive force) that powers ATP synthesis.

GO:0006091 def     The chemical reactions and pathways resulting in the formation of precursor metabolites, substances from which energy is derived, and any process involved in the liberation of energy from these substances.

**Comment by hdrabkin** [comment]
Fell safer adding to GO:0042776

**Comment by ValWood** [comment]
so
GO:0042776 - mitochondrial ATP synthesis coupled proton transport

is_a
GO:0006091 generation of precursor metabolites and energy

?

**Comment by hdrabkin** [comment]
That's what I just commited from your original suggestion.

**Comment by ValWood** [comment]
Thanks! Im confusing myself ;)

**Comment by ValWood** [comment]
Actually Harold, a better parent for 
GO:0042776 - mitochondrial ATP synthesis coupled proton transport


would be 
oxidative phosphorylation? do you agree?
(it's a descendant of GO:0006091
https://en.wikipedia.org/wiki/Oxidative_phosphorylation)

**Comment by hdrabkin** [comment]
ok, that would work and still give you the grouping you were looking for
