### ISSUE TITLE
term obsoletion GO:0072317 glucan endo-1,3-beta-D-glucosidase activity involved in ascospore release from ascus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15204]
MF involved in BP
only used by PomBase. Please obsolete I'll post compose:
GO:0072317 glucan endo-1,3-beta-D-glucosidase activity involved in ascospore release from ascus

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0072317 glucan endo-1,3-beta-D-glucosidase activity involved in ascospore release from ascus. 

The reason for obsoletion is that it should be captured as a GO-CAM model. The term in only used by PomBase. 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 27, 2018. Unless objections are received by Feb 27, 2018 we will assume that you agree to this change.

Thanks, Pascale
