### ISSUE TITLE
incorrect or missing parent mannosyltransferase  branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15208]
there appear to be 2 branches in MF representing the same thing:

![small problem](https://user-images.githubusercontent.com/7359272/36388730-c276e6ce-1594-11e8-95e1-f2941dcba6f5.jpg)

**Comment by ValWood** [comment]
So

GDP-Man:Man2GlcNAc2-PP-dolichol alpha-1,6-mannosyltransferase activity

Definition | 
Catalysis of the reaction: GDP-alpha-D-mannose(2-) + a (mannosyl)2-(N-acetylglucosaminyl)2-diphosphodolichol <=> H+ + GDP(3-) + a (mannosyl)3-(N-acetylglucosaminyl)2-diphosphodolichol


should be a child of
GO:0033164 - glycolipid 6-alpha-mannosyltransferase activity

Definition | Parents
Catalysis of the transfer of an alpha-D-mannosyl residue from GDP-mannose into lipid-linked oligosaccharide, forming an alpha-(1->6)-D-mannosyl-D-mannose linkage.

**Comment by ValWood** [comment]
I'm not totally sure that both branches are required?

**Comment by ValWood** [comment]
ok maybe not they have different ECs.

**Comment by ValWood** [comment]
hmm but
GO:0004378    JSON
GDP-Man:Man1GlcNAc2-PP-Dol alpha-1,3-mannosyltransferase activity
Molecular Function

Definition (GO:0004378 GONUTS page)
Catalysis of the reaction: beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-D-GlcNAc-diphosphodolichol + GDP-alpha-D-mannose = alpha-D-Man-(1->3)-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-D-GlcNAc-diphosphodolichol + GDP + H+. This reaction is the transfer of an alpha-D-mannosyl residue from GDP-mannose into lipid-linked oligosaccharide, forming an alpha-(1->3)-D-mannosyl-D-mannose linkage.

also has 2.4.1.232?

**Comment by ValWood** [comment]
this ticket is slightly related
https://github.com/geneontology/go-ontology/issues/14655#issuecomment-366616915

**Comment by ValWood** [comment]
Hi Harold, will this be covered in your Rhea work?

**Comment by ValWood** [comment]
pinging @hdrabkin  any solution?

**Comment by hdrabkin** [comment]
the EC:2.4.1.232 can be used for the mechanism for each. 
pinging Peter @deustp01 and @amorgat .

**Comment by deustp01** [comment]
Sorry - nothing to add from here.

**Comment by ValWood** [comment]
@hdrabkin  should the parent relation be added here?

**Comment by ValWood** [comment]
covered by https://github.com/geneontology/go-ontology/issues/24984
