### ISSUE TITLE
MP dolichol-linked oligosaccharide biosynthetic process (GO:0006488)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15203]
shouldn't 
dolichol-linked oligosaccharide biosynthetic process (GO:0006488)
have the parent
N-linked glycosylation (GO:0006487)????

**Comment by ValWood** [comment]
http://www.thefog.ca/research.html

**Comment by ValWood** [comment]
I am picking up a few mappings from various sources to GO:0006487 for 
dolichol-linked oligosaccharide biosynthetic process (GO:0006488)
and that doesn't seem incorrect.

**Comment by mah11** [comment]
I guess it depends on how much you want part_of to cover. The oligosaccharides get built up on dolichol and then transferred to the substrate protein, so one could argue that GO:0006488 precedes and is required for (but ends before) N-linked glycosylation.

**Comment by ValWood** [comment]
Well do they have any other purpose except for glycosylation (this is referring to the process rather than the specific MF of transferring the  dolichol-linked oligosaccharide.

I guess it comes down to what users would expect to see?

**Comment by ValWood** [comment]
Wikepedia (I know it isn't authoititve but its a starting point)

descibes the process  biosynthesis of N-linked glycans occurs via 3 major steps

1. Synthesis of dolichol-linked precursor oligosaccharide
2. En bloc transfer of precursor oligosaccharide to protein
3. Processing of the oligosaccharide

**Comment by ukemi** [comment]
Reviews seem to agree with this.
