### ISSUE TITLE
'acetate-CoA ligase activity' parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15215]
GO:0003987 : acetate-CoA ligase activity
Catalysis of the reaction: ATP + acetate + CoA = AMP + diphosphate + acetyl-CoA.

This term is currently a child of these two terms:
GO:0016405 : CoA-ligase activity
Catalysis of the reaction: substrate + ATP + CoASH = AMP + diphosphate + substrate-CoA. 

GO:0016878 : acid-thiol ligase activity
Catalysis of the joining of an acid and a thiol via a carbon-sulfur bond, with the concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate.

Given acetate is a short-chain fatty acid, I _think_ GO:0003987 should also be a child of:
GO:0015645 : fatty acid ligase activity
Catalysis of the ligation of a fatty acid to an acceptor, coupled to the hydrolysis of ATP.

**Comment by ukemi** [comment]
Hi @sjm41 

This isn't supported by ChEBI, so I am going to leave it as is.

-David
