### ISSUE TITLE
Add EC xref to "NADPHX epimerase activity" & "NADHX epimerase activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15214]
I think we can add 'EC 5.1.99.6' as an xref to both these GO terms:

GO:0052857 : NADPHX epimerase activity
Catalysis of the reaction: (R)-NADPHX = (S)-NADPHX.

GO:0052856 : NADHX epimerase activity
Catalysis of the reaction: (R)-NADHX = (S)-NADHX.

https://enzyme.expasy.org/EC/5.1.99.6
NAD(P)H-hydrate epimerase. 

- (6R)-6-beta-hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide <=> (6S)-6-beta-hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide
- (6R)-6-beta-hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide phosphate <=> (6S)-6-beta-hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide phosphate

**Comment by sjm41** [comment]
Hi Harold
I was about to make a ticket to add this EC xref, when discovered this old one that is still open.
Can you add this xref to both GO terms, or did you see a problem with doing so?

**Comment by hdrabkin** [comment]
Fell through the cracks I guess. I also have the Rhea's for both.

**Comment by hdrabkin** [comment]
Done

**Comment by sjm41** [comment]
great, thanks!
