### ISSUE TITLE
typo in definitions

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15216]
The definitions for “regulation of sarcomere organization” (GO:0060297), “positive regulation of sarcomere organization” (GO:0060298), and “negative regulation of sarcomere organization (GO:0060299) need “of” added between “extent” and “myofibril assembly”.

**Comment by ValWood** [comment]
The missing "of" is in here:
https://github.com/geneontology/go-ontology/issues/15228

**Comment by slaulederkind** [comment]
Funny.
