### ISSUE TITLE
NTRs: Top3β-TDRD3 complex and RNA topoisomerase activity

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15223]
Hallo,
can you please help me with these two new terms?
thanks a lot
Livia
Term1: Name: Top3beta-TDRD3 complex
Def: A protein complex that has DNA topoisomerase type I  and RNA topoisomerase activities.

References:
GOC:lnp
PMID: 
28176834 and 23912945
Relationships:
is_a GO:0032991 protein-containing complex

capable_of GO:0003917 DNA topoisomerase type I activity
capable_of GO:NEW(term2) RNA topoisomerase activity
capable_of GO:0003725 double-stranded RNA binding
capable_of GO:0003727 single-stranded RNA binding
capable_of GO:0003697 single-stranded DNA binding
capable_of_part_of GO:0006265 DNA topological change

DB xref:
IntAct: EBI-16748965 and EBI-16767487

Name: RNA topoisomerase activity
Def: Catalysis of the transient cleavage and passage of individual RNA strands or double helices through one another, resulting a topological transformation in RNA.

References:
GOC:lnp
PMID: 
27257063 and 23912945

is_a GO:0016853 isomerase activity
Is_a GO:0140098 catalytic activity, acting on RNA

**Comment by liviap** [comment]
@bmeldal would you mind to check it?

**Comment by bmeldal** [comment]
>Top3β

I'd spell out Top3beta as many applications (incl our own editor) can't read Greek letters and scramble them up :(

>GO:0043234 protein complex

Now merged into GO:0032991 protein-containing complex!!! (It's live!)

> part_of GO:0005634 nucleus

NOT IF also applicable to unicellular organisms - but I haven't checked!

**Comment by liviap** [comment]
I've updated the issue as you suggested :)

**Comment by liviap** [comment]
Sorry to bother...Any update on it?

Livia

**Comment by pgaudet** [comment]
Hi @liviap 
Can we name this term 'DNA topoisomerase I-TDRD3 complex'? 

Thanks, Pascale

**Comment by liviap** [comment]
Hi @pgaudet !
Yes, I think it's fine.
thanks a lot
Livia

**Comment by pgaudet** [comment]
Did you request RNA topoisomerase activity (NEW?)

**Comment by liviap** [comment]
yes

**Comment by pgaudet** [comment]
ticket # please ? Sorry I cannot find it. 

Pascale

**Comment by liviap** [comment]
can it be #15223?

**Comment by pgaudet** [comment]
duh ! Sorry !! thanks

**Comment by pgaudet** [comment]
I didn't add 'part of ' nucleus since this activity is also present in bacteria.

Pascale

**Comment by liviap** [comment]
it's fine, thanks for that!
Livia
