### ISSUE TITLE
Obsolete  GO:0102222

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#15220]
This is one of the Peifen/metacyc mapping ids. Peifen requests that it be obsoleted as she now considers the def incomprehensible. There are no annotations to this term, so I will just obsolete it without a review process; agreeded?
name: 6-phosophogluco-3-phosphogluco-starch phosphatase activity

namespace: molecular_function
def: "Catalysis of the reaction: m+q H2O + a 6-phosphogluco-3-phosphogluco-amylopectin <=> m+q hydrogenphosphate + a 6-phosphogluco-3-phosphogluco-amylopectin" [EC:3.1.3.-]
xref: EC:3.1.3.-
xref: MetaCyc:RXN-12218
is_a: GO:0016791 ! phosphatase activity

**Comment by pgaudet** [comment]
I agree although the guidelines are to do the announcement. Sometimes
someone comes forward with some information. I admit that I don't always
wait the full 7 days.

Pascale

Le 20 févr. 2018 1:11 PM, "Harold Drabkin" <notifications@github.com> a
écrit :

**Comment by hdrabkin** [comment]
The reason I would be slightly embarrassed is that Peifen noted:

"**The reaction does not make sense to me**. It is good that you brought it up and I checked manually. Please make the term obsolete."

**Comment by pgaudet** [comment]
Well, you can write 'This reaction is not believed to exist'. 

Is MetaCyc also obsoleting this ? 
https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-12218&redirect=T

Pascale

**Comment by hdrabkin** [comment]
No, I think this was a case of something that was in some stage of work but was wrong.
At Metacyc,  MetaCyc:RXN-12218 resolves to MetaCyc:EC 3.1.3.-  !!
I am always leary of Metacyc ids with EC numbers as Metacyc ids if the EC number is a 3 digit EC
This one is  represents "Phosphoric monoester hydrolases "; NOT terribly specific.

**Comment by pgaudet** [comment]
What I mean is that MetaCyc has the same strange reaction 

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/4782928/36490167-a1bb215e-16f5-11e8-83e6-610ba335179f.png">

**Comment by deustp01** [comment]
MetaCyc accommodates generic features in reactions, using controlled vocabularies of their own invention (reasonably enough, as they were annotating reactions and developing needs for new terms before GO or ChEBI or Rhea (or Reactome) were in existence). This reaction is to be read like an algebraic equation, to capture the fact that complete hydrolysis of a polymer of known composition and structure but unknown extent consumes and generates predictable numbers of known molecules once the extent is specified.

**Comment by hdrabkin** [comment]
And it appears meaningless
The oddity was discovered because
This requested term (2228) had same name as 2222 which already went in. When She looked
at 2222, it made no sense. 

[Term]
id: GO:0102228 = GO:0102222 same name Add this metacyc id
name: 6-phosophogluco-3-phosphogluco-starch phosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: n H2O + a 6-phosphogluco-3-phosphogluco-amylopectin <=> n hydrogenphosphate + an exposed unphosphorylated, unbranched malto-oligosaccharide tail on amylopectin" [EC:3.1.3.-]
xref: EC:3.1.3.-   <<<< will remove btw
xref: MetaCyc:RXN-12277
is_a: GO:0016791 ! phosphatase activity

So I can't have two ids with same name. 2228 appears fine.

**Comment by pgaudet** [comment]
Obsoleted with the comment "This term was obsoleted because it was created by error."
