### ISSUE TITLE
appropriate place(s) for "dehydroepiandrosterone sulfotransferase" synonym

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#15222]
I was annotating PMID:1588921 (https://www.ncbi.nlm.nih.gov/pubmed/?term=1588921) and had a hard time identifying the appropriate function term for the enzyme named DHEA-ST and described as "capable of catalyzing the sulfation of DHEA" (DHEA stands for "dehydroepiandrosterone").

1. If you search GO for "dehydroepiandrosterone sulfotransferase", you get only one term: 
"**alcohol sulfotransferase activty" (GO:0004027)** and the EXACT synonym in question has an EC reference of EC:2.8.2.2. However, the ENZYME page for the EC number EC:2.8.2.2 (https://enzyme.expasy.org/EC/2.8.2.2) doesn't mention dehydroepiandrosterone at all.

2. If you search GO for "DHEA", you get this term:
**"steroid sulfotransferase activity" (GO:0050294)** (with the EC xref of EC:2.8.2.15; https://enzyme.expasy.org/EC/2.8.2.15) due to this database_cross_reference from Reactome describing the reaction indicated in the paper being annotated:

> Reactome:REACT_6969
> dehydroepiandrosterone (DHEA) + PAPS => DHEA sulfate + PAP, Homo sapiens

3. The UniProt entry for Q06520 (ST2A1_HUMAN) is the enzyme which is called DHEA-ST and its page lists this info:

> Protein names:
> - Recommended name: Bile salt sulfotransferase (EC:2.8.2.14)
> - Alternative name(s):Dehydroepiandrosterone sulfotransferase
> - Short name: DHEA-ST

The EC# 2.8.2.14 is associated with the MF term **bile-salt sulfotransferase activity (GO:0047704)**

However, the EC page for EC 2.8.2.14 (https://enzyme.expasy.org/EC/2.8.2.14) has these interesting comments:
- The formation of sulfate esters of bile acids is an essential step in the prevention of toxicity by monohydroxy bile acids in many species.
- This enzyme is both a bile salt and a 3-hydroxysteroid sulfotransferase.
- In addition to the 5-beta-bile acid glycolithocholate, deoxycholate, 3-beta-hydroxy-5-cholenoate and dehydroepiandrosterone (3-beta- hydroxyandrost-5-en-17-one) also act as substrates (see also EC 2.8.2.2 and EC 2.8.2.34).
- May be identical to EC 2.8.2.2. 

@deustp01 & @hdrabkin - Can you help me make sense of this. Currently, I have selected the term for "bile-salt sulfotransferase activity" for my annotation since this is consistent with both the UniProt page for the gene linked to the reference and the description of substrates on the ENZYME page for EC:2.8.2.14 (https://enzyme.expasy.org/EC/2.8.2.14) DOES list dehydroepiandrosterone sulfotransferase as a substrate. 

I am wondering if the synonym "dehydroepiandrosterone sulfotransferase" should be removed from "**alcohol sulfotransferase activty" (GO:0004027)**  or just changed from EXACT to BROAD, and also if this synonym should be added to **"steroid sulfotransferase activity" (GO:0050294)**
and/or **bile-salt sulfotransferase activity (GO:0047704)**

**Comment by ValWood** [comment]
pinging @deustp01 & @hdrabkin

**Comment by pgaudet** [comment]
@kaxelsen Maybe you can help with this?

**Comment by kaxelsen** [comment]
The activity is shown in pmid:2764897 and is linked to Q06520 (ST2A1_HUMAN) . We do not yet have the reactions in Rhea, but I will create them when I have the time. dehydroepiandrosterone is not a bile-salt, so it should be linked to EC 2.8.2.2.

**Comment by hdrabkin** [comment]
I don't see how 
dehydroepiandrosterone sulfotransferase" could be a synonym of alcohol sulfotransferase activity" (GO:0004027) .
Actually most of the synonyms there could be considered more like some sort of substrate specific terms for
the def
3'-phosphoadenosine 5'-phosphosulfate + an alcohol = adenosine 3',5'-bisphosphate + an alkyl sulfate.
RHEA currently maps 3 reactions to the EC:2.8.2.2

RHEA:59304
3'-phosphoadenylyl sulfate + firefly L-luciferin = adenosine 3',5'-bisphosphate + firefly L-sulfoluciferin + H+
RHEA:59300
3'-phosphoadenylyl sulfate + firefly D-luciferin = adenosine 3',5'-bisphosphate + firefly D-sulfoluciferin + H+
RHEA:52368
3'-phosphoadenylyl sulfate + cholesterol = adenosine 3',5'-bisphosphate + cholesterol sulfate + H+

**Comment by kaxelsen** [comment]
A hydroxy group is an alcohol, and there is a hydroxy group on C3 of dehydroepiandrosterone, see https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:28689

**Comment by hdrabkin** [comment]
yes, I agree that hydroxysteroid sulfotransferase is a type of an alcohol sulfotransferase, but I'm not comfortable using it as as synonym.

**Comment by pgaudet** [comment]
The comment in EC:2.8.2.2 mentions that "Primary and secondary alcohols, including aliphatic alcohols, ascorbate, chloramphenicol, ephedrine and hydroxysteroids", so I suggest we add this comment and perhaps the other activites as 'narrowMatch'?

**Comment by kaxelsen** [comment]
Note that child relations in Rhea do not have anything to do with EC numbers. Relations in Rhea only looks at the chemistry, and in the chemical sense the substrates cholesterol and firefly luciferin are alcohols. Perhaps the error is to use Rhea child reactions as synonyms for the GO term.

**Comment by kaxelsen** [comment]
> The activity is shown in pmid:2764897 and is linked to Q06520 (ST2A1_HUMAN) . We do not yet have the reactions in Rhea, but I will create them when I have the time. dehydroepiandrosterone is not a bile-salt, so it should be linked to EC 2.8.2.2.

I have now had time to look at the reaction. It turns out I was wrong. The reaction is
RHEA:51216 3'-phosphoadenylyl sulfate + 3β-hydroxyandrost-5-en-17-one = 3β-sulfooxy-androst-5-en-17-one + adenosine 3',5'-bisphosphate + H+
3β-hydroxyandrost-5-en-17-one = dehydroepiandrosterone

We are working on the relationships. Currently RHEA:22552 produces "an alkyl sulfate", which does not quite fit steroids, but we are working on an update of RHEA:22552 to be more inclusive, so soon RHEA:5121 might become is-a RHEA:22552

**Comment by ValWood** [comment]
@pgaudet will  the Rhea mapping make this ticket out of date?

**Comment by raymond91125** [comment]
As @kaxelsen pointed out, the best fit to an existing GO term is GO:0004027 alcohol sulfotransferase activity = EC:2.8.2.2 = RHEA:22552. DHEA is a hydroxysteroid and not a phenolic steroid.
@krchristie Please let me know if you need anything else. Thanks.
