### ISSUE TITLE
NTR: negative regulaton of all-trans-retinyl-ester hydrolase, 11-cis retinol forming activity

### ISSUE THREAD

**Issue by ken7smith** [geneontology/go-ontology#15221]
negative regulation of all-trans-retinyl-ester hydrolase, 11-cis retinol forming activity

negative catalysis of the reaction: H(2)O + all-trans-retinyl ester = 11-cis-retinol + fatty acid.

molecular function

child term of regulation of all-trans-retinyl-ester hydrolase, 11-cis retinol forming activity

pubmed ID 23407971
@jimhu-tamu

**Comment by ukemi** [comment]
Added these a few days ago. Must have made a typo in the PR.
