### ISSUE TITLE
EC xrefs for DNA topoisomerase activities

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15236]
**1.  GO:0003916 DNA topoisomerase activity**
This currently has an xref to 5.99.1.-, but this should be removed (as it's not specific to DNA topoisomerases)

=

**2.  GO:0061505 DNA topoisomerase II activity**
Catalysis of a DNA topological transformation by transiently cleaving a pair of complementary DNA strands to form a gate through which a second double-stranded DNA segment is passed, after which the severed strands in the first DNA segment are rejoined; changes the linking number in multiples of 2. 

This lacks any xref, but should have an xref to:
EC 5.99.1.3 DNA topoisomerase (ATP-hydrolyzing).
ATP-dependent breakage, passage and rejoining of double-stranded DNA

=

**3.  GO:0003917 DNA topoisomerase type I activity**
Catalysis of a DNA topological transformation by transiently cleaving one DNA strand at a time to allow passage of another strand; changes the linking number by +1 per catalytic cycle.

Nothing to do here - this has a correct xref to:
EC 5.99.1.2 DNA topoisomerase
ATP-independent breakage of single-stranded DNA, followed by passage and rejoining

**Comment by hdrabkin** [comment]
GO:0003916 was on my list! Gone
Done closed
