### ISSUE TITLE
Placement of "fatty acid ligase activity" & children

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15231]
Hi @ukemi

Just following up the outstanding points (ignoring the issue of whether to relax the CoA ligase definition) you mentioned in #15051:

i) it looks like all of the x-chain fatty acid-COA ligases should [become children of "CoA-ligase activity"] because they fit the definition of a CoA ligase.

ii) I think all the fatty acid ligases be children of acid-thiol ligase activity? It looks to me like it they should unless you know of some that aren't in GO yet, but are.

I agree with (i) and (ii).
And I note that your point (ii) seems to fit with the EC classification:
EC:6.2.1.-	Acid--thiol ligases
EC:6.2.1.1	Acetate--CoA ligase
EC:6.2.1.2	Butyrate--CoA ligase
EC:6.2.1.3	Long-chain-fatty-acid--CoA ligase
etc.

See screenshot below for current relationships (not showing 'long chain fatty acid-CoA ligase activity' here because of its additional parentage).

(Apologies if I misunderstood the conclusion of #15051 and the above changes are not appropriate at this time.)

![screen shot 2018-02-21 at 22 13 48](https://user-images.githubusercontent.com/16306861/36509168-b8fdfaba-1756-11e8-84dd-f44ab02cc26c.png)

**Comment by ukemi** [comment]
Nice! I agree with all of this and will make these changes.
