### ISSUE TITLE
Add user id to references for ticket 10873

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#15240]
Hi Chris: here's the ticket request

Well now that I have done almost all of the Sue Rhee/Peifen Zang/ metacyc/plant enzyme request (#10873, a couple terms still being fleshed out), I realize that we should have also had Peifen add  GOC:pz from the users.yaml file  as an additional definition reference for all of the terms.  
Is there an easy way you could do this with a script (that is, for a range of GO ids, append GOC:pz to the definition references? That way it’s easy to identify the terms.
 There are currently about 51 occurrences of GOC:pz in the current file already; these appear to be terms that Tanya made but used GOC:pz as the reference.
 The id range is something like
GO:0102016  through GO:0103118 (~1102; not all ids were used in the end due to rejections and those found to be duplicates of already existing terms):

**Comment by cmungall** [comment]
Can you clarify - every existing term between IDs GO:0102016 and GO:0103118 (inclusive) should gain definition reference?

**Comment by hdrabkin** [comment]
Yes, they should get the GOC:pz 
As it stands, they currently either a PMID (a few), or an EC id. They all should have her id also.
