### ISSUE TITLE
NTR: glycerol-3-phosphate transmembrane transport

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15243]
NTR: glycerol-3-phosphate transmembrane transport 
biological_process
Def: The process in which glycerol-3-phosphate is transported across a membrane. 
Reference: PMID:20133652 

Parent: GO:0015794 glycerol-3-phosphate transport 
Child: GO:0015169 glycerol-3-phosphate transmembrane transporter activity (part_of NTR:glycerol-3-phosphate transmembrane transport)

structure based on existing GO:0001407 glycerophosphodiester transmembrane transport

Thanks 
Suzi

tagging @ValWood because she needs our annotation for an ISS

**Comment by pgaudet** [comment]
Hi @suzialeksander @ValWood 
Looks like transmembrane is the only mechanism; is it OK to rename 'GO:0015794 glycerol-3-phosphate transport' -> transmembrane transport ? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
I think that sounds OK.  I looked up a few G3P transporters but they're all permeases, so I don't have a solid example of this not being acceptable.

**Comment by ValWood** [comment]
yep, no know egs.

**Comment by pgaudet** [comment]
Also made GO:0070811 glycerol-2-phosphate transport -> transmembrane (no annotations)

**Comment by deustp01** [comment]
Would a taxon constraint be useful here? From what I've been able to find, never_in_mammalia is true, and maybe a broader one. (The so-called glycerol phosphate shuttle actually shuttles reducing equivalent, using always-cytosolic glycerol phosphate in the process.)
