### ISSUE TITLE
GO:0075243 oospore formation incorrect parent ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15248]
Hello, 

While working on #12231 I noticed a misplaced term: GO:0075243 oospore formation
is_a biosynthetic process 

'biosynthetic process'
 and 'anatomical structure formation involved in morphogenesis'
 and ('results in formation of' some oospore)
 and ('results in formation of' some oospore)
_(sic)_ 

Perhaps it should be 'part of 'sexual sporulation' ? (the definition talks about fusion). 

There are no annotations so if any clarification is needed that would not impact annotations. 

Thanks, Pascale

**Comment by ukemi** [comment]
This is just a bad logical definition, it shouldn't be a biosynthetic process.

**Comment by ukemi** [comment]
But interestingly enough the two differentia seem to point to two different objects, one is a CL class and the other is a FAO class. Do we need both? @cmungall this seems to be an issue with imports.

**Comment by ukemi** [comment]
def: "The process in which male and female gametangia develop and fuse to form an oospore, a thick-walled resting spore of oomycetes." [GOC:pamgo_curators]
 is_a: GO:0043935 ! sexual sporulation resulting in formation of a cellular spore
-intersection_of: GO:0009058 ! biosynthetic process
 intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
-intersection_of: results_in_formation_of CL:0002380 ! oospore
 intersection_of: results_in_formation_of FAO:0000039 ! oospore

**Comment by ukemi** [comment]
GO_0009058
 and GO_0048646
 and (RO_0002297 some CL_0002380)
 and (RO_0002297 some FAO_0000039)

**Comment by dianeoinglis** [comment]
I agree that 'biosythetic process is an inappropriate parent. I do think the definition should be appended to state ...in Oomytes and certain algae and fungi.

Disne
