### ISSUE TITLE
MICOS, MIB and SAM

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15245]
In GO we have only MICOS, with exact synonym MIB complex.

BUT
https://www.sciencedirect.com/science/article/pii/S0167488915003626

We find three main forms of the complex: A) The MICOS complex, containing all the MICOS proteins, B) a membrane bridging subcomplex, containing in addition SAMM50, MTX2 and the previously uncharacterized MTX3, and C) the complete MIB complex containing in addition DNAJC11 and MTX1.

MICOS interacts with components of the sorting and assembly machinery (SAM) complex [12] of the outer membrane [13] to form the mitochondrial intermembrane space bridging (MIB) complex

NTR : MIB complex
Def A mitochondrial  intermembrane space bridging complex consisting of components of the 
MICOS complex in the inner membrane , the SAM complex  in the outer membrane, a conserved DNAJ protein  (human DNAJC11)  and Metaxin 1

remove as exact synonym "MIB complex" from "MICOS complex"

Swap synonym of existing "SAM complex" GO:0001401 with current name 
"mitochondrial sorting and assembly machinery complex" it's difficult to recognize

https://www.sciencedirect.com/science/article/pii/S0167488915003626
and refe therin.

Nice figure for species conservation
![micos and mib](https://user-images.githubusercontent.com/7359272/36589619-ce3bfeda-1883-11e8-96e2-09245b608cd5.jpg)
ervation in this paper:

**Comment by ValWood** [comment]
figure in https://github.com/geneontology/go-ontology/issues/16113
shows this clearly...

**Comment by pgaudet** [comment]
@bmeldal Any comments on this one ?

**Comment by pgaudet** [comment]
- Created new term: 

+[Term]
+id: GO:0140275
+name: MIB complex
+namespace: cellular_component
+def: "A mitochondrial intermembrane space bridging complex consisting of components of the MICOS complex in the inner mitochondrial membrane, the SAM complex in the outer membrane, a conserved DNAJ protein (human DNAJC11) and Metaxin 1." [PMID:26477565]
+synonym: "mitochondrial intermembrane space bridging complex" EXACT []
+synonym: "mitofilin complex" EXACT []
+is_a: GO:0032991 ! protein-containing complex
+relationship: part_of GO:0031305 ! integral component of mitochondrial inner membrane
+created_by: pg
+creation_date: 2018-10-01T17:10:27Z

- Removed exact synonym "MIB complex" from "MICOS complex"

Thanks, Pascale

**Comment by ValWood** [comment]
@bmeldal  any comments on this one?

**Comment by pgaudet** [comment]
In any case, this is done. If there are problem please open a new ticket.

**Comment by bmeldal** [comment]
Hi Val,

So far we only have the yeast MICOS complex (https://www.ebi.ac.uk/complexportal/complex/CPX-140) and the "ortholog" of SAM complex (SAM35/37/50, https://www.ebi.ac.uk/complexportal/complex/CPX-1744).

I had a look at the quoted review with the human expression profile and looked at the orthologs. It appears that MICOS is fairly conserved in principle but SAMs/MTXs/DNAJ don't have clear orthologs across eukaryotes (F1 is a bit misleading, you ahve to read the text to find all the caveats ;-) ). The complexes, at least the MIB, probably exists but might turn out to be less conserved than the def says right now.

I'd leave it for now but there might be changes required if and when more data is available.
