### ISSUE TITLE
Merge GO:0044274 multicellular organismal biosynthetic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15249]
Hello,

While working on #12231 

'GO:0044274 multicellular organismal biosynthetic process' - no children, no annotations. 

Parents/siblings: 
(5 EXP)	multicellular organismal protein catabolic process
(4 EXP)	multicellular organismal protein metabolic process
(3 EXP)	multicellular organismal lipid catabolic process
(3 EXP)	regulation of multicellular organismal metabolic process
(2 EXP)	multicellular organism metabolic process
(1 EXP)	multicellular organismal macromolecule metabolic process
(1 EXP)	negative regulation of multicellular organismal metabolic process

Affected groups : 
(7)	WB
(5)	MGI
(3)	BHF-UCL
(3)	FlyBase
(1)	UniProt

Specific children include
'C4 photosynthesis'
'NAD-malic enzyme C4 photosynthesis'
'NADP-malic enzyme C4 photosynthesis'
'PEP carboxykinase C4 photosynthesis'
'adaptive thermogenesis'
'angiotensin catabolic process in blood'
'diet induced thermogenesis'
'intestinal lipid catabolic process'
'protein catabolic process by pepsin'
'salivary polysaccharide catabolic process'

I think the terms have been created to group metabolic processes that only occur in multicellular organisms but that list seems incomplete and difficult to maintain. 
We should make sure the terms have the correct taxon constraints instead. 

Notifying affected groups so they can comment (and anyone else, of course!) 
@ukemi @RLovering @hattrill @sylvainpoux @vanaukenk 

Thanks, Pascale

**Comment by vanaukenk** [comment]
I'm looking at the WB annotations here and will try to update to more informative terms wherever possible.

**Comment by pgaudet** [comment]
- [ ]  multicellular organismal protein catabolic process
 - [ ]  multicellular organismal protein metabolic process
 - [ ]  multicellular organismal lipid catabolic process
 - [ ]  multicellular organism metabolic process
 - [ ]  multicellular organismal macromolecule metabolic process
 - [ ]  regulation of multicellular organismal metabolic process
 - [ ]  negative regulation of multicellular organismal metabolic process
 - [ ]  positive regulation of multicellular organismal metabolic process
