### ISSUE TITLE
endosomal transport, annotation number drop

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15246]
I had 70 gene products annotated  2 days ago (correctly), and now I have only 51.

A child term must have been removed but I can't tell what?

**Comment by pgaudet** [comment]
Hi @ValWood 

Do you have a few missing genes to help identify the problem?

**Comment by pgaudet** [comment]
It must somehow be due to #12362

**Comment by ValWood** [comment]
No I think I'm wrong, I think I was thinking of endocytosis.

But isn't it odd that we have more annotations to endocytosis than to endosomal transport (surely endocytosis is_a endosomal transport?)

**Comment by pgaudet** [comment]
@ValWood someday you will give me a heart attack !! 

- endocytosis is_a vesicle transport, not an endosomal transport
- endosomal transport and endocytosis are disjoint 

<img width="367" alt="image" src="https://user-images.githubusercontent.com/4782928/36593589-5b62d6e2-1868-11e8-8d37-e6b92d189d20.png">

- as far as I know endosomal transport can be part of endocytosis or exocytosis. Endosomal transport uses endosomal vesicles, that's all
![image](https://user-images.githubusercontent.com/4782928/36593651-a2d31b18-1868-11e8-84c8-9cef94db2af7.png)


@marcfeuermann could comment to make sure I got this right.

Thanks, Pascale

**Comment by ValWood** [comment]
Sorry yes. Something seems not right though. Unfortunatly I can't check how many were annotated to endocsomal process yesterday  I can see the old number before I re run the query but then I lose it!

This seems odd though  don't you think?
![parentage](https://user-images.githubusercontent.com/7359272/36593778-1750bd90-1893-11e8-934f-2e8a0fc7f1d4.jpg)

I'm sure there used to be closer alignment between annotation to these terms. Now they only have 3 annotations in common?

**Comment by ValWood** [comment]
we  can close this one...

**Comment by ValWood** [comment]
I'm going to reopen this. There are definitely some issues that I can see,  and I haven't managed to track the cause of the from in numbers.

This is what I noticed so far  (although it doesn't appear to be  the cause).

1. GO:0098927    vesicle-mediated transport between endosomal compartments
A cellular transport process in which transported substances are moved in membrane-bounded vesicles between endosomal compartments, e.g, between early endosome and sorting endosome. PMID:10930469
is currently disjoint from endosomal transport

( I don't really know what this means other than "endosomal transport")

**Comment by ValWood** [comment]
2. GO:0034058    JSON
endosomal vesicle fusion
Biological Process

Definition The homotypic fusion of endocytic vesicles to form or add to an early endosome. PMID:11964142 PMID:9422733

This is a child of vesicle-mediated transport, but not of endosomal transport. Presumably it should be?

**Comment by ValWood** [comment]
3. GO:2000803    endosomal signal transduction
Definition (GO:2000803 GONUTS page)
The process in which a signal is passed on to downstream components located at the endosome. Endosomes can provide important intracellular signaling platforms and provide spatial and temporal control over signal transduction. PMID:15084302 PMID:17662591

Suggest obsoletion, because this is not something that could currently be used to annotate specific gene products. All it is saying is that some pathways may converge on the endosome?
It doesn't really reflect how we reflect signalling  in GO (no annotations).

**Comment by ValWood** [comment]
4. GO:0070676   intralumenal vesicle formation
Has  exact synonym "endosome membrane budding" (this would seem to be a much clearer primary term name?
The invagination of the endosome membrane and resulting formation of a vesicle within the lumen of the endosome. PMID:19234443

This has no relationship to "endosomal transport" but presumably only happens as part of endosomal transport?

I still haven't found "the one"!

**Comment by ValWood** [comment]
5. OK got it!

GO:0008333    endosome to lysosome transport
The directed movement of substances from endosomes to lysosomes.
this used to have
is a GO:0016197 (endosomal transport)

seems to fit
The directed movement of substances mediated by an endosome, a membrane-bounded organelle that carries materials enclosed in the lumen or located in the endosomal membrane.

**Comment by ValWood** [comment]
Also
6. early endosome to Golgi transport
7. late endosome to lysosome transport
8. (both of these should also be decendants of endosome to lysosome transport? currently not_
9. late endosome to vacuole transport

**Comment by ValWood** [comment]
10. GO:0061502    early endosome to recycling endosome transport
I  don't really know what this one means (7 manual annotations).  How do you distinguish a recycling endosome from a non-recycling endosome?

**Comment by ValWood** [comment]
11. Terms  seem the same
GO:0042147    retrograde transport, endosome to Golgi
defined
The directed movement of membrane-bounded vesicles from endosomes back to the trans-Golgi network where they are recycled for further rounds of transport. PMID:10873832 PMID:16936697

child
GO:0071955    recycling endosome to Golgi transport
Definition (GO:0071955 GONUTS page)
The directed movement of substances from recycling endosomes to the Golgi.

**Comment by ValWood** [comment]
12. Sound the same (currently not related except via v-m-t)

GO:0048201  vesicle targeting plasma membrane to endosome
The process in which vesicles formed at the plasma membrane are directed to specific destinations in endosome membranes, mediated by molecules at the vesicle membrane and target membrane surfaces. PMID:10219233

GO:0048227    plasma membrane to endosome transport
Transport of a vesicle from the plasma membrane to the endosome.

**Comment by ValWood** [comment]
I think that's it. I can check after changes.

**Comment by ValWood** [comment]
Of course , it depends whether "endosomal transport" is only within endosomal compartments or also includes transport from  endosomes to other compartments (the  def suggests the latter?)

**Comment by pgaudet** [comment]
Another issue is that I dont think lysosomal transport should be a child of vacuolar transport. 
@marcfeuermann can you please confirm ?

**Comment by pgaudet** [comment]
One problem is the confusion with the standard definitions: for eg
'lysosomal transport' is defined as 'The directed movement of substances into, out of or within a lysosome.' 
- 'within' is clearly wrong' 
- all these should be 'vesicular transport': 
--  vesicular transport from endosome to lysosome
-- vesicular transport from early endosome to Golgi 
-- vesicular transport from late endosome to lysosome 
-- vesicular transport from late endosome to vacuole 


@ValWood 
@marcfeuermann
Would something like that make sense ? 

Thanks, Pascale

**Comment by deustp01** [comment]
According to my textbook, a lot of the arrows in the part of the diagram above devoted to uptake of material from outside the cell denote "maturation" or "fusion", not vesicle-mediated transport - i.e., an endosome is transformed into a lysosome. (All in contrast to the export side, where vesicles form from one organelle to carry content to the next orgamelle.)

**Comment by ValWood** [comment]
Possibly the term vesicle-mediated transport is part of the problem. I can't remember the exact history but it was the term used to describe "transport by membrane trafficking".  So  maybe this term needs rethinking ?  I an't remember why we did not use "membrane trafficking" at the time ?

Definition (GO:0016192 GONUTS page)
A cellular transport process in which transported substances are moved in membrane-bounded vesicles; transported substances are enclosed in the vesicle lumen or located in the vesicle membrane. The process begins with a step that directs a substance to the forming vesicle, and includes vesicle budding and coating. Vesicles are then targeted to, and fuse with, an acceptor membrane.

The def seems to fit the situation where  something begins as a vesicle but fuses  with other vesicles to become a larger organelle.

Maybe this is an area where expert input is required.....

**Comment by ValWood** [comment]
might help to show which things need merging or connecting

![endosomal](https://user-images.githubusercontent.com/7359272/37364428-6dfe9c4e-26f2-11e8-9331-e84cebb313ba.jpg)

**Comment by ValWood** [comment]
Although there are issues with the vesicle-mediated transport branch, the issue here is resolved
77 | endosomal transport (GO:0016197)
