### ISSUE TITLE
Is 'peptidyl-diphthine' a real compund? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15251]
When I google it I only find GO terms. 

Perhaps we mean just 'diphthine'? I thought the peptidyl was used when the synthesis/modification occured within a protein. Here I dont think this is the case (for eg peptidyl-diphthine biosynthetic process from peptidyl-histidine has Def: The chemical reactions and pathways resulting in the formation of peptidyl-diphthine from other compounds, including peptidyl-histidine." 

which I think is produced by 'diphthine synthase activity' , 'Catalysis of the reaction: S-adenosyl-L-methionine + 2-(3-carboxy-3-aminopropyl)-L-histidine = S-adenosyl-L-homocysteine + 2-(3-carboxy-3-(methylammonio)propyl)-L-histidine.' 

So it seems we should remove the 'peptidyl' from the term label ? 

Applies to 

'peptidyl-diphthine biosynthetic process from peptidyl-histidine' 
'peptidyl-diphthine catabolic process' 
'peptidyl-diphthine metabolic process' 
and possibly also to 
'peptidyl-dehydroalanine biosynthetic process from peptidyl-tyrosine or peptidyl-serine'
'peptidyl-diphthamide biosynthetic process from peptidyl-histidine'
'peptidyl-thyronine biosynthetic process from peptidyl-tyrosine'
another potential PTM: 
peptidyl-L-glutamic acid 5-methyl ester biosynthetic process from glutamine

Thanks, Pascale

**Comment by ukemi** [comment]
Not my area of expertise, but it seems that these histidine residues are modified in the context of the proteins postranslationally. We would have to do a careful examination of the pathways to address all the terms you have above, but peptidyl-diphthine might be an intermediate in the synthesis of diphthamide. I'm not sure if it doesn't funnel into more than one pathway or is an endpoint itself in some cases. Perhaps a careful reading of PMID:23971743 or some of the other references could answer this.
diphthine residue--CHEBI:48230

**Comment by deustp01** [comment]
Yes, it's a post-translational modification of a specific histidine in EEF2 (Eukaryotic Elongation Factor 2) (https://reactome.org/PathwayBrowser/#/R-HSA-5358493) (and see references cited in the annotation). Of clinical interest because diphtheria toxin catalyzes further modification of the diphthine residue, inactivating EEF2. As far as I know, it's a very well conserved process in eukaryotes and this one histidine is the only known target in the whole human proteome.

**Comment by pgaudet** [comment]
Thanks all ! 
We seem to ahave two different term label patterns for PTMs: 

'peptidyl-lysine myristoylation'
'peptidyl-S-myristoyl-L-cysteine biosynthetic process from peptidyl-cysteine'

I think the latter is confusing, I will reformulate as the former. 

Pascale
