### ISSUE TITLE
Query: ergothioneine biosynthesis from histidine via N-alpha,N-alpha,N-alpha-trimethyl-L-histidine' versus ergothioneine biosynthesis from N-alpha,N-alpha,N-alpha-trimethyl-L-histidine'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15256]
While working on #12231 I came across these two terms: 

'GO:0052704 ergothioneine biosynthesis from histidine via N-alpha,N-alpha,N-alpha-trimethyl-L-histidine'
"The pathway resulting in the formation of ergothioneine from histidine. Histidine undergoes three methylations by a histidine-alpha-N-methyltransferase (EC:2.1.1.44) to form N-alpha,N-alpha,N-alpha-trimethyl-L-histidine (also known as hercynine or histidine betaine). N-alpha,N-alpha,N-alpha-trimethyl-L-histidine is modified by the ligation of gamma-glutamyl-cysteine and oxygen; this intermediate undergoes further modification by the removal of glutamate to produce hercynylcysteine sulfoxide. Finally, a beta-lyase acts on this compound, removing pyruvate, ammonia and oxygen to produce ergothioneine."

and 
'GO:0052711 ergothioneine biosynthesis from N-alpha,N-alpha,N-alpha-trimethyl-L-histidine'

Is there a difference between ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@deustp01 @hdrabkin

**Comment by ukemi** [comment]
#11163

**Comment by deustp01** [comment]
Nothing to add to the expert biochemical discussion already in #11163

**Comment by pgaudet** [comment]
OK duplicate, sorry
