### ISSUE TITLE
NTR: SLAC complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15267]
Hello,
I've a ntr for the slac complex, can anyone please help me with that?
thanks a lot
Livia

Term1: 
Name: SLAC complex
Def: A protein complex that regulates Arp2/3 complex-mediated actin nucleation.

References:
GOC:lnp
PMID: 
22973053
Relationships:
is_a GO:0032991 protein-containing complex
capable_of_part_of GO:0034315 regulation of Arp2/3 complex-mediated actin nucleation

DB xref:
IntAct: EBI-7506670

**Comment by vanaukenk** [comment]
Hi @liviap - are there defining members of the complex that we could cite in the definition?  Thx.

**Comment by liviap** [comment]
in S. cerevisiae the components are LAS17 and SLA1 (ref: 22973053)

**Comment by liviap** [comment]
Sorry to bother...Any update on it?

Livia
