### ISSUE TITLE
MP nucleobase-containing compound catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15262]
from
https://github.com/geneontology/go-ontology/issues/15250

nucleobase-containing compound metabolic process (GO:0006139)

should be a child of "small molecule metabolic process"

currently it isn't. Could that be added too?
(this was one of the purposes for this term, to try to group all of the canonical metabolism excluding  DNA metabolism)

**Comment by deustp01** [comment]
But nucleobase-containing compound metabolic process (GO:0006139) has GO:0090304 nucleic acid metabolic process "Any cellular metabolic process involving nucleic acids" as an is_a child. Is that the relationship you want?

**Comment by ValWood** [comment]
Right you are. I got confused ......
