### ISSUE TITLE
Merge regulation of nuclear import for specific cargos into Regulation of protein import into nucleus

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15268]
**(SEE UPDATED PROPOSAL BELOW)**
As part of #13686
we will merge children terms of 

Regulation of protein import into nucleus and their respective positive and negative children as follows: 

**Merge into 'regulation of protein import'**
'regulation of catenin import into nucleus'
'regulation of SMAD protein import into nucleus'
'regulation of STAT protein import into nucleus'
'regulation of transcription factor import into nucleus'
'regulation of NF-kappaB import into nucleus'
'regulation of NFAT protein import into nucleus'

**Merge into 'positive regulation of protein import'**
'positive regulation of catenin import into nucleus'
'positive regulation of protein import into nucleus, translocation'
'positive regulation of SMAD protein import into nucleus'
'positive regulation of STAT protein import into nucleus'
'positive regulation of transcription factor import into nucleus'
'positive regulation of NF-kappaB import into nucleus'
'positive regulation of NFAT protein import into nucleus'

**Merge into 'negative regulation of protein import'**
'negative regulation of NF-kappaB import into nucleus'
'negative regulation of NFAT protein import into nucleus'
'negative regulation of STAT protein import into nucleus'
'negative regulation of SMAD protein import into nucleus'
'negative regulation of catenin import into nucleus'
'negative regulation of transcription factor import into nucleus'

People might want to review their annotations to add extensions - annotations have been saved here: 
https://docs.google.com/spreadsheets/d/1BzmGzHyuwGPnGgy1tZ075fFMJezL_Yx9dinM05SLWW4/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Email sent to go-consortium: "Obsoletion and merge notice: Protein import into the nucleus"
(...)
On a related note, all ‘regulation’ terms of the above terms will be merged into their respectve regulation parent. Details are here: https://github.com/geneontology/go-ontology/issues/15268


Pascale

**Comment by RLovering** [comment]
Hi
before these are all merged into these very unspecific parents please could we consider what will be lost with these merges.
For example, there are lots of different signaling pathways that converge on the regulation of NF-kappaB import into the nucleus, which regulate the activity of NF-kappaB, and the regulation of transcription by this TF. However there are 41 GO BP terms that include NF-kappaB in their name or description. Rather than doing this merge and leaving people to work out how to reannotate this information to check that this information isn't lost, would it be possible to review these terms, work out how to capture this information appropriately and non-redundantly, and then provide a similar set of terms for the other regulation of 'specific TF' import into nucleus. 

I realise this means more work but I do think that a lot will be lost by just changing everything to regulation of protein import into nucleus (AE 'specific TF') and also really for many proteins this isn't what we are trying to capture. So maybe the merge isn't the best thing to do.

For example, maybe it would be more appropriate to merge 
'regulation of NF-kappaB import into nucleus'
GO:0043122   regulation of I-kappaB kinase/NF-kappaB signaling

or at the very least keep GO:0042990   regulation of transcription factor import into nucleus

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

Thanks for the feedback, that's a very good point. I made a revised proposal:


Regulation | Merge into 
-- | -- 
regulation of catenin import into nucleus' | GO:0030111 regulation of Wnt signaling pathway |  
regulation of SMAD protein import into nucleus' | ?? No regulation of SMAD protein signaling; change label ?
regulation of STAT protein import into nucleus' | GO:1904892 regulation of STAT cascade or GO:0046425 regulation of JAK-STAT cascade
regulation of NF-kappaB import into nucleus' | GO:1901222 regulation of NIK/NF-kappaB signaling
regulation of NFAT protein import into nucleus' | GO:0070884 regulation of calcineurin-NFAT signaling cascade
regulation of transcription factor import into nucleus' | needs to be mapped manually to each pathway



Positive regulation | Merge into 
-- | -- 
positive regulation of catenin import into nucleus' | GO:0030177 positive regulation of Wnt signaling pathway |  
positive regulation of SMAD protein import into nucleus' | ?? No positive regulation of SMAD protein signaling; change label ?
positive regulation of STAT protein import into nucleus' | GO:1904894 positive regulation of STAT cascade or GO:0046427 positive regulation of JAK-STAT cascade ?
positive regulation of NF-kappaB import into nucleus' | GO:1901224 positive regulation of NIK/NF-kappaB signaling
positive regulation of NFAT protein import into nucleus' | GO:0070886 positive regulation of calcineurin-NFAT signaling cascade
positive regulation of transcription factor import into nucleus' | needs to be mapped manually to each pathway


Negative regulation | Merge into 
-- | -- 
negative regulation of catenin import into nucleus' | GO:0030178 negative regulation of Wnt signaling pathway |  
negative regulation of NF-kappaB import into nucleus' | GO:1901223 negative regulation of NIK/NF-kappaB signaling
negative regulation of NFAT protein import into nucleus' | GO:0070885 negative regulation of calcineurin-NFAT signaling cascade
negative regulation of STAT protein import into nucleus' | GO:1904893 negative regulation of STAT cascade or GO:0046427 positive regulation of JAK-STAT cascade ?
negative regulation of SMAD protein import into nucleus' | ?? No negative regulation of SMAD protein signaling; change label ?
negative regulation of transcription factor import into nucleus' | needs to be mapped manually to each pathway

**Comment by RLovering** [comment]
Hi Pascale

I agree with this proposal. 
note that there is the term:GO:0060395   SMAD protein signal transduction
could this be a parent to a set of regulation terms ie regulation of SMAD protein signal transduction created by renaming the regulation terms for SMAD protein import into nucleus?

The only thing is that if you consider the current ontology: 
GO:0007178    transmembrane receptor protein serine/threonine kinase signaling pathway
part_of child GO:0060395   SMAD protein signal transduction
Definition The cascade of processes by which a signal interacts with a receptor, causing a change in the activity of a SMAD protein, and ultimately effecting a change in the functioning of the cell.
So TGFbeta will need to be annotated to both GO:0060395   SMAD protein signal transduction and GO:0007179   transforming growth factor beta receptor signaling pathway. ie TGFbeta is not regulating SMAD protein signal transduction. 

In addition, in 2007 I annotated SMAD3 as to the regulation of SMAD protein import into nucleus, (it regulates the import of SMAD4). I think now this would be more appropriate to be just GO:0060395   SMAD protein signal transduction. So I really do want to systematically look at the annotations that exist before the terms are removed.

Also I agree that the 'regulation of transcription factor import into nucleus' and child annotations will need to be reviewed on a case by case basis. However, could the recommendation be that the curator considers instead annotating this to 'regulation of transcription factor activity' eg in PMID: 15799969 the authors report SMAD3 directly binds to SMAD4 and this leads to the translocation of SMAD4 into the nucleus and the PMID: 15799969 

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering 
This is why I was leaning towards obsoletion for these - annotations *do* need to get reviewed anyway. 

Also, from the annotations you've looked at, is the protein always involved in regulation of the pathway? Can some of them be part of the pathway? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @RLovering 
Is SMAD signaling distinct from TGF-B signaling ? 
https://en.wikipedia.org/wiki/SMAD_(protein)

Thanks, Pascale

**Comment by RLovering** [comment]
No don't do this. see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5655313/ 
States: Growth differentiation factor (GDF11), also called as bone morphogenetic protein 11(BMP11) belongs to the transforming growth factor-β (TGF-β) superfamily. 
- ie if you chose to do this it needs to be clear this is a superfamily. So BMP signaling probably uses SMADs too

This paper also also states: GDF11 transmits signals through type I and II serine/threonine kinase receptors, similar to other TGF-β superfamily members. GDF11 binds first to Activin receptor II (ActRII) including ActRIIA and ActRIIB, and then recruits Activin receptor I (ActRI) including ALK4, ALK5 and ALK7 [16, 17, 18]. GDF11 binding to its receptors activates Smad and non-Smad signaling pathways that represent canonical and non-canonical signaling pathways downstream of TGF-β superfamily members. 

See reviews https://www.ncbi.nlm.nih.gov/pubmed/27920040 and https://www.ncbi.nlm.nih.gov/pubmed/27836834 I haven't read this paper but the abstract discusses TGFbeta, activins, Nodal, and BMP signaling.

Hope that helps

Ruth

**Comment by pgaudet** [comment]
ok - so SMAD signaling will be its own pathway for now. We can revisit later. 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/15285/commits/88142be820b7f59cf7a7af61daaca67fc2b8f69a

**Comment by pgaudet** [comment]
Obsolete 
* GO:0042991 transcription factor import into nucleus
* GO:0042990 regulation of transcription factor import into nucleus
* GO:0036283 positive regulation of transcription factor import into nucleus in response to oxidative stress
* GO:0042992 negative regulation of transcription factor import into nucleus
* GO:0042993 positive regulation of transcription factor import into nucleus


The reason for obsoletion is that there is no distinct pathway to import transcription factors into the nucleus. 

Pascale
