### ISSUE TITLE
NTR: mitochondrial respiratory chain complex IV pre-assemply complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15278]
Hi,
I'm suggesting a new complex term,
Thanks for the help!
Livia

term
Name: mitochondrial respiratory chain complex IV pre-assemply complex
Definition: a protein complex that regulates mitochondrial respiratory chain complex IV (COX) formation. It acts by regulating mitochondrial COX1 translation and by promoting the assembly of COX components.
Reference:
21068384
GOC: lnp
relations:
is_a  GO:0098800 inner mitochondrial membrane protein complex
capable_of_part_of GO:0070130 negative regulation of mitochondrial translation
capable_of_part_of GO:0033617 mitochondrial respiratory chain complex IV assembly
part_of GO:0031305 integral component of mitochondrial inner membrane
DBxref
IntAct EBI-16632200
synonyms:
COX pre-assemply complex [narrow]
COX1 preassemply complex [exact]

**Comment by ukemi** [comment]
Should this be a child of GO:0101031 'chaperone complex'?

**Comment by liviap** [comment]
if you believe it fits with the definition it's ok to me, but I would add id as an extra annotation and not to replace the previous ones...

**Comment by ukemi** [comment]
Having a look at the paper, I think it fits. But your comment that this is an annotation is an interesting one. If we put this in the ontology, it is an asserted relationship between two classes. In the long run, the complex working group needs to make the call as to whether this kind of information lives in annotations or as asserted relations in the ontology. That has been under discussion recently. I will just mention a couple people on that working group here as a record. @bmeldal @vanaukenk @thomaspd. 
For now, I will continue to add these to the ontology.

**Comment by liviap** [comment]
I apologise, I've written annotation, but I meant a relation!!

**Comment by ukemi** [comment]
No worries. I think it is still an issue. I'm making it a chaperone complex and is_a integral component of mitochondrial inner membrane. It seems to better fit the definition.
