### ISSUE TITLE
NTR:large ribosomal subunit pre-assembly complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15279]
Hi,
can anyone help me with this?
thanks
Livia

Term1:
 Name:  large ribosomal subunit pre-assembly complex
Def: A protein complex that is required during early maturation of nascent 60S ribosomal subunits. The complex interacts with the large ribosomal subunit rRNA via one of the components (Urb2 in S. cerevisiae) and requires a RNA helicase (Dbp6 in S. cerevisiae).
[in S. cerevisiae it is composed by: Dbp6, Rsa3, Urb1, Urb2, Nop8]
References:
GOC:lnp
PMID: 
9528757 and 17145778
Relationships:
is_a GO:0101031 chaperone complex
capable_of GO:0070180 large ribosomal subunit rRNA binding
capable_of_part_of GO:0000027 ribosomal large subunit assembly

DB xref:
IntAct: EBI-16630962

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140714
+name: large ribosomal subunit pre-assembly complex
+namespace: cellular_component
+def: "A protein complex that assists early maturation of nascent 60S ribosomal subunits. The complex interacts with the large ribosomal subunit rRNA via one of the components (Urb2 in S. cerevisiae) and requires a RNA helicase (Dbp6 in S. cerevisiae)." [GOC:lnp, PMID:17145778, PMID:9528757]
+is_a: GO:0101031 ! chaperone complex
+relationship: capable_of_part_of GO:0000027 ! ribosomal large subunit assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/15279 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-15T12:17:56Z
+
