### ISSUE TITLE
Is the release pipeline broken?

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#15274]
These two files:

http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json
http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl

are both showing a version IRI of:

http://purl.obolibrary.org/obo/go/releases/2018-02-20/extensions/go-plus.owl

go-plus.owl has been updated several times since 20 Feb, so has something gone wrong with the release pipeline?

**Comment by tonysawfordebi** [comment]
Is there an alternative location where I can find an up-to-date version of go-plus.json?

**Comment by bmeldal** [comment]
There've been no Jenkins reports for a few days but they've come through this morning.

**Comment by tonysawfordebi** [comment]
The version of go-plus.json that we grabbed at about 3am this morning still had the 2018-02-20 timestamp.

I'll try grabbing it again now to see whether it's been updated.

**Comment by tonysawfordebi** [comment]
Nope, http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json is still stuck at 2018-02-20

**Comment by tonysawfordebi** [comment]
@cmungall Any word on what's happening here?

**Comment by cmungall** [comment]
@tonysawfordebi very sorry about the lack of response

I can try and track down what was going on, but either way it works now:

      "version" : "http://purl.obolibrary.org/obo/go/releases/2018-08-28/extensions/go-plus.owl"
