### ISSUE TITLE
neurogenesis inconsistencies

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15272]
There is a bit of inconsistency in the definitions of terms in the "neurogenesis" arm of BP.  The definiton of "neurogenesis" (GO:0022008) is: Generation of cells within the nervous system.  That definition makes the following example #1 a reasonable child of "neurogenesis", until you come across example #2 which has a more narrow definition of "neurogenesis" which is inconsistent with the term and definition in example #1.  I suggest a review of the definition of "neurogenesis" and its children.

EXAMPLE #1 CHILD OF NEUROGENESIS: "gliogenesis" (GO:0042063) DEFINITION: The process that results in the generation of glial cells. This includes the production of glial progenitors and their differentiation into mature glia.

EXAMPLE #2 CHILD OF NEUROGENESIS: "regulation of neurogenesis" (GO:0050767) DEFINITION: Any process that modulates the frequency, rate or extent of neurogenesis, the origin and formation of neurons.

**Comment by ukemi** [comment]
If no comments against, I am going to relax the definition of the regulation term.

**Comment by BarbaraCzub** [comment]
Hi @ukemi I agree it makes sense to relax the definition of the regulation term to fit with that of the parent.

**Comment by cmungall** [comment]
perhaps this was relaxed too far "cells in the nervous system" includes endothelial cells in blood vessels, epithelial cells of the CP, etc.

Also, I am not an expert but I am not familiar with the term "neurogenesis" being inclusive of glial cells. I bet when curators directly annotate to neurogenesis they are assuming neurons. This means that we have many annotations that are more general than they should be (a quick sample seems to confirm this). And in fact many of those seem like they are better placed under a more specific term like neuron differentiation.

The definitions are still inconsistently worded:

id: GO:0042063
name: gliogenesis
def: "The process that results in the generation of glial cells. This includes the production of glial progenitors and their differentiation into mature glia." [GOC:dgh, GOC:jid]


id: GO:0022008
name: neurogenesis
def: "Generation of cells within the nervous system." [GO_REF:0000021, GOC:cls, GOC:curators, GOC:dgh, GOC:dph, GOC:jid]

The gliogenesis definition better hints at the start and end but neurogenesis is very open to interpretation

I wish we had made some of these do not annotate from the outset.
