### ISSUE TITLE
	gamma-glutamyltranspeptidase/

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15273]
Background
https://github.com/geneontology/go-annotation/issues/1324#issuecomment-368718417

gamma-glutamyltranspeptidase ==glutathione hydrolase activity

we have EC mappings to substrate specific  versions

+ | hypoglycin A gamma-glutamyl transpeptidase activity
+ | leukotriene C4 gamma-glutamyl transferase activity

(I don't know if these terms exist in pombe).
If these terms are valid, they should be descendants of glutathione hydrolase activity

**Comment by ValWood** [comment]
hmm

hypoglycin A
Hypoglycin A is a naturally occurring amino acid derivative found in the unripened fruit of the Ackee tree (Blighia sapida) and in the seeds of the box elder tree (Acer negundo). It is toxic if ingested, and is the causative agent of Jamaican vomiting sickness. A 2017 Lancet report established a link between the consumption of ...

also add a taxon restriction never in yeast I think for any compound mentioning leukotriene, we don't have the enzyme to make it.

**Comment by hdrabkin** [comment]
@ValWood , Checking: yeast might not make it, but would there be enzymes to handle exposure to it?
see https://en.wikipedia.org/wiki/Hypoglycin_A#Toxicity
Or  leukotrienes in general: any effect on fungi?
I can't find any but you might know of something?

**Comment by ValWood** [comment]
I have never come across them. it is unlikely since its seems to only produced in organism with immune system... You can leave as I have filtered. But it seems glutathione hydrolase activity should not always  have  all of these activities annotated in lots of species??

**Comment by hdrabkin** [comment]
It does what it does,  depending on the acceptor; when water, it's a hydrolase; when a peptide or amino acid, ti's a transferase.  This is why it might have multiple metacyc mappings
Gamma-glutamyltransferase (also γ-glutamyltransferase, GGT, gamma-GT; EC 2.3.2.2) is a transferase (a type of enzyme) that catalyzes the transfer of gamma-glutamyl functional groups from molecules such as glutathione to an acceptor that may be an amino acid, a peptide or water (forming glutamate).

I'll go ahead with the parentage and the constraint for the two you mention;

**Comment by ValWood** [comment]
but haven't we previously established that gamma-glutamyltranspeptidase  (a type of enzyme) is not physiologically relevant. It's just the assay conditions?

geneontology/go-annotation#1324 (comment)

In a test tube one can set up conditions in which the enzyme will transfer the gamma-glutamyl portion of the substrate to an acceptor molecule, but this requires non-physiologic conditions, including millmolar concentrations of an acceptor such as glygly. This reaction is used in assays to detect the presence of the enzyme, but is not a physiological function of GGT.

**Comment by hdrabkin** [comment]
about that: Peifen suggested to me that it does in fact happen, but I can't find the reference yet.

**Comment by ValWood** [comment]
I know that a transferase is a type of Harold, I have a biochemistry degree... but don't tell anyone, I have forgotten it all : )

**Comment by ValWood** [comment]
The experts in the previous ticket suggested that it did not happen...

**Comment by hdrabkin** [comment]
I know; that's why I am still holding the request (somewhere; now I can't find it argh!)

**Comment by hdrabkin** [comment]
I found it!
The term requested had the same name as the obsolete term.
Here response was to rename the term name to reflect the substrate;
[Term]
id: GO:0103068  This term was obsoleted because the it does not correspond to a physiological reactio
name:  gamma-glutamyl transferase activity
namespace: molecular_function
def: "Catalysis of the reaction: leukotriene C4(2-) + a standard alpha amino acid <=> leukotriene D4(1-) + an (gamma-L-glutamyl)-L-amino acid" [EC:2.3.2.2]
xref: EC:2.3.2.2
xref: MetaCyc:RXN66-336
is_a: GO:0016755 ! transferase activity, transferring amino-acyl groups
Peifen: see below
(Please rename to 'leukotriene C4 gamma-glutamyl transferase activity'. The reaction as appeared in the definition of the proposed term is a physiological reaction, see https://www.ncbi.nlm.nih.gov/pubmed/1676842 and https://www.ncbi.nlm.nih.gov/pubmed/9139674)

Thus  GO:0103068  is the term you see.

**Comment by ValWood** [comment]
Surely these should have different EC numbers?

**Comment by deustp01** [comment]
That's part of the murky history, I think - the previous round of discussion may have been set off by an EC decision to discontinue numbers corresponding to the non-physiological reactions.

**Comment by ukemi** [comment]
Murky indeed. I think these are all realted:

#12955, #12956, #13571, #13572

**Comment by hdrabkin** [comment]
Ec does not have an id for 'leukotriene C4 gamma-glutamyl transferase (or every single enzymatic reaction in GO for that matter).
However the MetaCyc:RXN66-336 xref  maps to MetaCyc Reaction: 2.3.2.2; ie, EC:2.3.2.2, and Metacyc rxn displays the C4-leukotriene as the substrate.

**Comment by deustp01** [comment]
@hdrabkin , how fine-grained is EC? For example, in the domain of oxidoreductase reactions, if all known enzymes all act on a whole family of substrates (as might be the case for some of that eicosanoid metabolism) would EC create different accession number solely for the purpose of individuating substrates or would it create one number for the family? And does GO want to stop at the family level?

**Comment by hdrabkin** [comment]
I don't think so; that's why many of Pfeifen's enzyme requests have the same EC but different MetaCyc ids.

**Comment by hdrabkin** [comment]
I can remove the xref but keep it as a reference I suppose.

**Comment by ValWood** [comment]
seems to be done?
