### ISSUE TITLE
Proposal for revised ontology for extracellular matrix

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15294]
Note: Further tickets will be made and cross-referenced in this ticket as appropriate.

The ontology under Extracellular matrix (GO:0031012) is very confused mostly due to the existence of the child term Extracellular matrix component (GO:0044420; do_not_annotate). The definition of this seems synonymous with Extracellular matrix (GO:0031012) and both are used inconsistently as parents, i.e.  some descendants of ECM are also descendants of ECM component, but not all. Additionally, many of the child terms of these two terms should be placed under more specific term(s).

Current definitions:
Extracellular matrix (GO:0031012) A structure lying external to one or more cells, which provides structural support for cells or tissues. 

Extracellular matrix component (GO:0044420) Any constituent part of the extracellular matrix, the structure lying external to one or more cells, which provides structural support for cells or tissues; may be completely external to the cell (as in animals) or be part of the cell (as often seen in plants). 

Could ECM component be made obsolete and its descendants would become either is_a child terms of ECM or part_of child terms of the subtypes of ECM, as specified below?

Proposal for revised ontology for extracellular matrix (GO:0031012)
Relations are for the given term to its parent. Note: descendants are not shown if there are no changes to position or relation

**Update:** see attached word file for proposed ontology structure as formatting here is not good.
[Revised ontology for extracellular matrix.docx](https://github.com/geneontology/go-ontology/files/1774393/Revised.ontology.for.extracellular.matrix.docx)

extracellular matrix (GO:0031012) (see GitHub #15295 #15298)
-	is_a GO:0097311 biofilm matrix (see GitHub #15299)
-	is_a GO:1990377 organomineral extracellular matrix
-	is_a GO:0005578 proteinaceous extracellular matrix (see GitHub #15297)
        o   part_of GO_NEW: proteinaceous extracellular matrix core-associated (see GitHub #15296)
        o   part_of GO_NEW: proteinaceous extracellular matrix core (see GitHub #15296)
             •	 part_of GO:0030934 anchoring collagen complex
             •	part_of GO:0098644 complex of collagen trimers
             •	part_of GO:1990324 collagen type XXVI trimer
             •	part_of GO:1990326 collagen type XXVIII trimer
             •	part_of GO:1990971 EMILIN complex
             •	part_of GO:1990972 multimerin complex
             •	part_of GO:0090733 tenascin complex
             •	part_of GO:0001527 microfibril
             •	part_of GO:1990341 thrombospondin complex
             •	part_of GO:0061800 fibronectin fibril
             •	part_of GO:0071953 elastic fiber
        o   part_of GO:0099126 transforming growth factor beta complex
        o   is_a GO:0005614 interstitial matrix
        o   is_a GO:0033166 hyaline layer
        o   is_a GO:0033165 interphotoreceptor matrix
        o   is_a GO:0005604 basement membrane (see GitHub #15300)
        o   is_a GO:0060102 collagen and cuticulin-based cuticle extracellular matrix
        o   is_a GO:0099535 synapse associated extracellular matrix
             •	part_of GO:0098965 extracellular matrix of synaptic cleft  (see GitHub #15301)
             •	part_of GO:0098966 perisynaptic extracellular matrix
             •	part_of GO:0072534 perineuronal net (see GitHub #15301 #15302)

**Comment by ukemi** [comment]
In addition to the changes to ontology structure above. We are also considering merging the proteinaceous extracellular matrix with the parent extracellular matrix. After a great deal of searching by @rachhuntley  and me, we are convinced that all ECMs contain at least some protein. The parent ECM term will have three children:

biofilm matrix - will include children for both fungal and bacterial biofilms. 
collagen-based extracellular matrix
organomineral extracellular matrix

The children of the current proteinaceous term will be rehoused under the collagen-based term. @rachhuntley  did I get this right?

**Comment by rachhuntley** [comment]
Hi David,
Yes, I think this works for the existing child terms of proteinaceous ECM.
Thanks.

**Comment by rachhuntley** [comment]
A new term "collagen-containing extracellular matrix" was added here #15565.
Groups annotating metazoan species should reconsider re-annotating gene products that are currently annotated to GO:0031012 to this more specific term.
