### ISSUE TITLE
NTR: small ribosomal subunit processing (or maturation?) complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15290]
Hallo,
here a new term to suggest
thanks in advance
Livia

Term1:
 Name: small ribosomal subunit processing (or maturation?) complex
Def: A protein complex that is required during early maturation of nascent 40S ribosomal subunits. The complex has endonuclease activity, it interacts with the small ribosomal subunit pre-rRNA and cleave it it to produce the mature 18S (or small ribosomal subunit) rRNA.
[in S. cerevisiae it is composed by: Rc11p and Bms1p]
References:
GOC:lnp
PMID:
25064857
Relationships:
is_a GO:1905348 endonuclease complex
capable_of GO:0003924 GTPase activity (??)
part_of GO:0005730 nucleolus
capable_of_part_of GO:2000232 regulation of rRNA processing
capable_of GO:0070181 small ribosomal subunit rRNA binding
capable_of_part_of GO:0042274 ribosomal small subunit biogenesis

DB xref:
IntAct: EBI-16720319

**Comment by krchristie** [comment]
It might be good to say a "small protein complex" at the beginning of the definition because my first thought was that this was another large complex like the SSU processome and the 90S preribosome complexes which are large assemblages that include the U3 snoRNA as well as rRNA in some stage of processing.

Also, is it know which cleaveage(s) this complex is involved in? The U3 snoRNA and another snoRNP that I forget the name/number of just now is also thought to be involved in these early rRNA cleaveages.

**Comment by liviap** [comment]
Hi @krchristie ,
thanks for your helph!
ok, I understand that the term might create confusion, so it might be worth saying 'heterodimeric' or 'small';
yes it's known that it cleaves A2 sites (21849504)

**Comment by hdrabkin** [comment]
Like this?
Def: A small heterodimeric protein complex that is required during early maturation of nascent 40S ribosomal subunits. The complex has endonuclease activity, it interacts with the small ribosomal subunit pre-rRNA and cleave it it to produce the mature 18S (or small ribosomal subunit) rRNA.
[in S. cerevisiae it is composed by: Rc11p and Bms1p]

I can also include PMID:21849504 in the def refs.

**Comment by liviap** [comment]
it sounds perfect!
:)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140638
+name: small ribosomal subunit processing complex
+namespace: cellular_component
+def: "A small heterodimeric protein complex that is required during early maturation of nascent 40S ribosomal subunits. The complex has endonuclease activity, it interacts with the small ribosomal subunit pre-rRNA and cleave it it to produce the mature 18S (or small ribosomal subunit) rRNA. In S. cerevisiae it is composed of Rc11p and Bms1p." [GOC:lnp, PMID:21849504, PMID:25064857]
+synonym: "small ribosomal subunit maturation complex" RELATED []
+is_a: GO:1905348 ! endonuclease complex
+relationship: capable_of_part_of GO:0042274 ! ribosomal small subunit biogenesis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/15290 xsd:anyURI
+created_by: pg
+creation_date: 2021-04-21T08:07:11Z

**Comment by ValWood** [comment]
There is a problem with the protein name Rc11....should i be rRl1?

**Comment by ValWood** [comment]
corrected Rcl1
