### ISSUE TITLE
Make extracellular matrix (GO:0031012) do_not_annotate

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15295]
Can extracellular matrix (GO:0031012) be tagged with 'do_not_annotate' as it should be possible to choose one of the child terms based on species, e.g. biofilm matrix for bacteria, proteinaceous ECM for metazoa. 

There are currently 2294 direct manual annotations to Extracellular matrix, 565 of which are to experimental codes (the majority of these are BHF-UCL).

The only mappings to Extracellular matrix (GO:0031012) are:
InterPro:IPR001818 
InterPro:IPR010363 
InterPro:IPR010515 
InterPro:IPR015455
InterPro:IPR021158
InterPro:IPR021190
InterPro:IPR027118
InterPro:IPR030705
InterPro:IPR030743
InterPro:IPR032822
InterPro:IPR032973
InterPro:IPR033078
InterPro:IPR037286
InterPro:IPR037349

and from a quick look I think these should be simple to re-assign to a child term based on the species coverage.

See GitHub #15294

**Comment by bmeldal** [comment]
and 144 complexes but I can't see if they are direct annotations or to children from the website, I'll ask our devs to run an SQL query.

**Comment by rachhuntley** [comment]
It's not possible to have terms for each type of ECM, therefore extracellular matrix (GO:0031012) needs to be annotatable. Proteinaceous ECM was merged into GO:0031012 here #15563.
A new term "collagen-containing extracellular matrix" was added here #15565.
Groups annotating metazoan species should reconsider re-annotating gene products that are currently annotated to GO:0031012 to this more specific term.

**Comment by rachhuntley** [comment]
Hi David @ukemi, no I didn't yet as I didn't know if there is a particular standard process you follow for this. Let's do it next call.

**Comment by ukemi** [comment]
Hi @rachhuntley ,
Should we close this one since the plant terms will still be annotated? I think this ticket is out of date because we merged the protein term into the parent.

**Comment by rachhuntley** [comment]
Re-annotation of extracellular matrix was requested here https://github.com/geneontology/go-annotation/issues/1943

InterPro mappings have also been dealt with here https://github.com/geneontology/go-annotation/issues/1944

Nothing more to do on this ticket, therefore closing.
