### ISSUE TITLE
Apparent blocking error in go-basic.obo: multiply labeled edge

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#15293]
Between Feb 28th at midnight and Feb 28th 5pm, an error was introduced that is blocking the go data pipeline.

```
Removed: 2129 links
11:50:54  :: ERROR: multiply-labeled-edge: GO:0046425 GO:0007259 --> part_of regulates
11:50:57  Makefile:213: recipe for target 'go-basic.obo' failed
11:50:57 make: *** [go-basic.obo] Error 1
```

@pgaudet @cmungall

**Comment by kltm** [comment]
@dougli1sqrd

**Comment by dougli1sqrd** [comment]
It looks like this is the offending line: https://github.com/geneontology/go-ontology/pull/15285/files#diff-3cf7b2b4f9db4df4cae7c72388fdba78R311346. This caused there to be more than one "link" between these two classes. 

Side note, the error "multiply-labeled-link" is confusing. Maybe we can make that more clear. I was ready to see a predicate ("link"?) with more than one label.

**Comment by cmungall** [comment]
@dougli1sqrd let's get this implemented in a sparql test
