### ISSUE TITLE
AP lyase/endonuclease problems

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15308]
(continuation of #13409)
@pgaudet
@jimhu-tamu
@kaxelsen

Under the 'lyase activity' MF branch there is:

**DNA-(apurinic or apyrimidinic site) lyase activity (GO:0003906)**
Def: Catalysis of the cleavage of the C-O-P bond in the AP site created when DNA glycosylase removes a damaged base, involved in the DNA base excision repair pathway (BER).
Synonyms: endodeoxyribonuclease (apurinic or apyrimidinic) activity [exact], deoxyribonuclease (apurinic or apyrimidinic) activity [exact], AP lyase activity [exact], UV endonuclease [broad], endonuclease VIII activity [related], DNA-(apurinic or apyrimidinic site) 5'-phosphomonoester-lyase activity [exact], AP site-DNA 5'-phosphomonoester-lyase activity [exact]
EC: 4.2.99.18

...which has 3 children:
**class I DNA-(apurinic or apyrimidinic site) lyase activity (GO:0140078)**
Def: Catalysis of the cleavage of an AP site 3' of the baseless site by a beta-lyase mechanism, leaving an unsaturated aldehyde, termed a 3'-(4-hydroxy-5-phospho-2-pentenal) residue, and a 5'-phosphate. PMID:1698278
Synonyms: AP endonuclease class I activity [related]
EC: 4.2.99.18

**class II DNA-(apurinic or apyrimidinic site) lyase activity (GO:0140079)**
Def: Catalysis of the cleavage of an AP site 5' of the baseless site, by a hydrolytic mechanism, leaving a 3'-hydroxyl and a 5'-deoxyribose phosphate residue. PMID:1698278
Synonyms: n/a
EC: n/a
(this is also a child of 'nuclease activity')

**class III/IV DNA-(apurinic or apyrimidinic site) lyase activity (GO:0140080)**
Def: Catalysis of the cleavage of an AP site 3' and 5' of the baseless site, generating a 3'-phosphate and a 5'-OH. PMID:2519777
Synonyms: endonuclease IV [related], endonuclease III [related]
EC: 4.2.99.18

Then, in the separate hydrolase->endonuclease branch, there is this:

**apurinic/apyrimidinic endodeoxyribonuclease activity (GO:0052720)**
Def: Catalysis of the hydrolysis of ester linkages immediately 5' to an apurinic/apyrimidinic (AP; also called abasic) site within a deoxyribonucleic acid molecule by creating internal breaks, generating a single-strand break with 5'-deoxyribose phosphate and 3'-hydroxyl ends. PMID:19401441
Synonyms: apurinic deoxyendoribonuclease activity [narrow], abasic deoxyendoribonuclease activity [exact], AP deoxyendoribonuclease activity [exact], apyrimidinic deoxyendoribonuclease activity [narrow]
EC: n/a

![screen shot 2018-03-02 at 10 16 40](https://user-images.githubusercontent.com/16306861/36897056-f28b2be2-1e0c-11e8-8e39-b0c52f378b05.png)

The EC:4.2.99.18 that crops up above is:
**DNA-(apurinic or apyrimidinic site) lyase.**
aka: AP endonuclease class I, AP lyase, Deoxyribonuclease (apurinic or apyrimidinic), Endodeoxyribonuclease (apurinic or apyrimidinic)
Rxn: The C-O-P bond 3' to the apurinic or apyrimidinic site in DNA is broken by a beta-elimination reaction, leaving a 3'-terminal unsaturated sugar and a product with a terminal 5'-phosphate
Comments: 'Nicking' of the phosphodiester bond is due to a lyase-type reaction, not hydrolysis.
https://enzyme.expasy.org/EC/4.2.99.18

ISSUES:

1. Only class I (GO:0140078) is defined as a lyase activity. So I think the parent "DNA-(apurinic or apyrimidinic site) lyase activity" (GO:0003906) should be obsoleted or merged with the "class I DNA-(apurinic or apyrimidinic site) lyase activity" (GO:0140078) term
2. Then "class I DNA-(apurinic or apyrimidinic site) lyase activity" (GO:0140078) should be a direct child of "carbon-oxygen lyase activity" & a suitable 'AP endodeoxyribonuclease' term.  The EC:4.2.99.18 xref for this is correct.
3. "class II DNA-(apurinic or apyrimidinic site) lyase activity (GO:0140079)" is defined as a hydrolase (not lyase) endonuclease activity, so should have its name and parentage changed.  BUT looks like this term can just be deleted/merged with "apurinic/apyrimidinic endodeoxyribonuclease activity (GO:0052720)", which appears to be the same activity and is correctly positioned
4. "class III/IV DNA-(apurinic or apyrimidinic site) lyase activity" (GO:0140080) is not defined as a lyase activity AFAIK, so should have its name changed and just go under a suitable 'Endodeoxyribonuclease' term.
5. looks like we'll need a new high-level term like "DNA-(apurinic or apyrimidinic site) endonuclease activity" to group the class I, II and III terms (as they can be hydrolases or lyases)

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by pgaudet** [comment]
Hi @ sjm41  One problem is that 'DNA-(apurinic or apyrimidinic site) lyase activity (GO:0003906)' didn't use to have children, and people have not yet moved their annotations. 


Here's what I propose: 
For Issue 1 and 5: 
  - [ ] Rename GO:0003906 DNA-(apurinic or apyrimidinic site) lyase activity  (has all the annotations): rename "DNA-(apurinic or apyrimidinic site) endonuclease activity", according to https://en.wikipedia.org/wiki/AP_endonuclease
  - [ ] Remove "carbon-oxygen lyase activity" parent

For issue 2: 
  - [ ] Add "carbon-oxygen lyase activity" parent to "class I DNA-(apurinic or apyrimidinic site) lyase activity" (GO:0140078), and keep under GO:0003906 "DNA-(apurinic or apyrimidinic site) endonuclease activity"

For issue 3: 
  - [ ] Merge class II DNA-(apurinic or apyrimidinic site) lyase activity (GO:0140079) with "apurinic/apyrimidinic endodeoxyribonuclease activity (GO:0052720)"; make the GO:0052720 term label "apurinic/apyrimidinic endodeoxyribonuclease activity" a broad synonym
- change label to "class II DNA-(apurinic or apyrimidinic site) endonuclease activity" 

For issue 4: 
  - [ ]  "class III/IV DNA-(apurinic or apyrimidinic site) lyase activity" (GO:0140080)
  - [ ]  change label to " lass III/IV DNA-(apurinic or apyrimidinic site) endonuclease activity

Does that work ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @sjm41 
I fixed the first two points above. 

I'll open a different ticket for the 3rd point, it's a little different scope. 

Thanks, Pascale

**Comment by pgaudet** [comment]
BTW I also removed the lyase synonyms on all terms except for class I. 

Pascale

**Comment by sjm41** [comment]
Great, thanks for those additional fixes!
Yes, I thought (feared) point 3 touched on a wider issue....sorry!
