### ISSUE TITLE
dipeptide and tripeptide transporters

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15309]
current terms are
tripeptide transporter activity
isn't transmembrane.

This can probably be renamed?
if not 
NTR tripeptide transmembrane transporter activity

**Comment by pgaudet** [comment]
Maybe this is a problem with the longer release cycle - but this was done here #14492 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/4782928/36918546-4328b450-1e28-11e8-8f94-114913cec3e6.png">

**Comment by pgaudet** [comment]
@ValWood please close if that's OK with you.
