### ISSUE TITLE
Change parentage of middle lamella

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15305]
Shouldn't 'middle lamella' (GO:0009519) be part_of plant-type cell wall (GO:0009505) instead of is_a extracellular matrix component?  (https://en.wikipedia.org/wiki/Cell_wall#Layers)

@tberardini ?

**Comment by tberardini** [comment]
I think the sticky bit is that the middle lamella, since it cements cell walls of adjacent plant cells together, is not part of a single cell.  This is probably why it was put into extracellular matrix component.  It fits better as part of plant_type cell wall.  Go ahead and move.

**Comment by rachhuntley** [comment]
Looking more into this, the middle lamella seems to fit the definition of an extracellular matrix (A structure lying external to one or more cells, which provides structural support, biochemical or biomechanical cues for cells or tissues.)

This is supported by these sentences from a recent paper (https://www.ncbi.nlm.nih.gov/pubmed/28140367):
The ML is a thin layer of approximately 50 nm thickness that is sandwiched between the primary cell walls of neighboring cells. It is distinguishable at light and electron microscopic levels and its material properties and chemical composition are different from those of the adjacent cell walls.

The contribution of the ML to maintaining the structural integrity of a plant is crucial as it acts as a cementing agent that prevents plant cells from sliding against or detaching from each other. 

Being part of the extracellular matrix, the ML has to yield and expand to accommodate cell growth, but how this in-plane expansion happens is virtually unknown.

The ML is also reported to play an important role in the modification of cell wall chemistry as a defence mechanism against pathogen invasion .

Therefore, I think we should probably not move it to plant-type cell wall but instead make it is_a extracellular matrix instead of is_a extracellular matrix component?
