### ISSUE TITLE
Basement membrane relation to parent

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15300]
Basement membrane (GO:0005604) should be is_a proteinaceous ECM (is currently part_of) as it’s consistently described as a type of ECM (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3039528/)

See #15294

**Comment by rachhuntley** [comment]
@ukemi This wikipedia entry goes into detail about the structure of the basal lamina and basement membrane https://en.wikipedia.org/wiki/Basal_lamina (and the confusion over terminology):

"The basal lamina is a layer of extracellular matrix secreted by the epithelial cells, on which the epithelium sits. It is often incorrectly referred to as the basement membrane, though it does constitute a portion of the basement membrane."

Therefore basal lamina is part_of basement membrane.

According to this page, the lamina lucida and lamina densa are part of the basal lamina (this is currently correctly represented in the ontology), but the lamina reticularis is part of the basement membrane (currently the ontology has this as part of basal lamina).

Is this a sufficient reference, or do we need experimental papers?

I'll continue to look into whether the basement membrane is only collagen-containing.

**Comment by rachhuntley** [comment]
Regarding the question of whether a basement membrane always contains collagen (for placement of basement membrane is_a collagen-containing extracellular matrix), this paper
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5395295/states "The emergence of the diversity of multicellular animals involved cells joining together to form tissues and organs. The ‘glue’ that enabled the cells to work together is made of rope-like molecules called collagen, which assemble into scaffolds. These smart scaffolds tether proteins forming basement membranes that connect cells, provide strength to tissues, and transmit information that influences how the cells behave.” 
"The basement membrane is a supramolecular scaffold, comprised of a toolkit of proteins including collagen IV, laminin, perlecan, and nidogen (Hynes, 2012; Fahey and Degnan, 2010)."

Also, figure 1 in this paper shows basement membranes in various taxons and collagen is always present. 

Also here https://www.tandfonline.com/doi/abs/10.3109/10409239209082560 
"The major molecular constituents of basement membranes are collagen IV, laminin-entactin/nidogen complexes, and proteoglycans.”

So I think we can safely say the basement membrane is collagen-containing.

**Comment by rachhuntley** [comment]
I also asked the expert these questions, but haven't heard back yet.

**Comment by rachhuntley** [comment]
Another good reference for basement membranes
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3039528/

**Comment by rachhuntley** [comment]
Awaiting response from Sylvie regarding whether basal lamina is_a or is part_of basement membrane. David's suggestion is to have basal lamina as a broad synonym of basement membrane and also have a basal lamina term that is part_of basement membrane.

**Comment by rachhuntley** [comment]
Response from Sylvie:
"I would not trust Wikipedia content, which is not always reviewed, or the article entitled "Prostaglandins in Cancer Cell Adhesion, Migration, and Invasion" (PMC3299390), which was not written by experts in the field of basement membranes. 
I attach to this e-mail a paper entitled "Lamina lucida of basement membrane: an artefact", which concludes that that "the lamina lucida is an artefact formed during conventional tissue preparation, and in its original condition in the living state, the basement membrane is composed of a single layer made up of lamina densa material"."
[ChanMicroscopyResTech1994[1].pdf](https://github.com/geneontology/go-ontology/files/1943444/ChanMicroscopyResTech1994.1.pdf)

**Comment by rachhuntley** [comment]
Numbers of annotations to child terms of basement membrane

sublamina densa: 27 annos (25 IEA)
basal lamina: 525 annos (417 IEA)
 -lamina reticularis: 0 annos
 -lamina densa: 0 annos
 -lamina lucida: 0 annos

**Comment by ukemi** [comment]
So shall we propose to obsolete lamina lucida and merge lamina densa into basement membrane? From this information, it seems reasonable. What about the two terms that have annotations?

**Comment by rachhuntley** [comment]
I agree.
This is what Sylvie originally said about 'basal lamina' (525 direct annotations):
In the extracellular matrix field basal lamina is often used at a synonym of basement membrane.
- See Yurchenco, 2011 (first line, first paragraph)
- See references in Basal lamina an overview ScienceDirect Topics

So based on this, perhaps we can merge this with 'basement membrane'?

The second annotated term 'sub-lamina densa' has only one experimental annotation (BHF) to this paper http://europepmc.org/abstract/MED/15623520, which was the paper referenced when the term was created. This paper refers to lamina lucida and lamina densa, so it is probably based on the artefactual components. The IEAs for this term are all based on the one experimental annotation. I suggest obsoleting this one as well.
