### ISSUE TITLE
Taxon constraints for plant terms

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15315]
It looks like these terms should have the taxon constraint only_in_plant: 
pollen coat (GO:0070505)
pollen wall (GO:0043667)
Ubisch body (GO:0070645) see also #15307

See also #15306

**Comment by cmungall** [comment]
this one should inherit a TC from PO:

```
id: GO:0043667
name: pollen wall
relationship: part_of PO:0025281 ! pollen
```

pollen coat needs a similar part of

last should be part-of PO:0025313

**Comment by rachhuntley** [comment]
How do we proceed with this?
If the taxon constraints are not being inherited, is this an issue for PO? Don't all PO terms have a TC for only_in_plant?

**Comment by cmungall** [comment]
Once PO make a new release we'll inherit the TCs at the root: https://github.com/Planteome/plant-ontology/issues/687

**Comment by ukemi** [comment]
Closing this because when the taxon constraints are inherited appropriately from PO, this issue should be resolved.
