### ISSUE TITLE
TPV GO:0051072 4,6-pyruvylated galactose residue biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15311]
https://www.ebi.ac.uk/QuickGO/term/GO:0051072
4,6-pyruvylated galactose residue biosynthetic process
The chemical reactions and pathways resulting in the formation of the pyruvylated galactose residue 4-6-O-[(R)(1-carboxyethylidine)]-Gal-beta-1,3-. The galactose residue is part of a larger polysaccharide chain. PMID:15173185

shouldn't have parentage to  "small molecule metabolic process">I think it's the  immediate carbohydrate derivative parent possibly that is incorrect.  but this parentage would still exist up the carboxylic acid branch. The problem here is likely higher up?

![tpv](https://user-images.githubusercontent.com/7359272/36898329-4ca15cbe-1e12-11e8-82f3-4a3311d5f903.jpg)

**Comment by ukemi** [comment]
I think the logical definition needs to be removed. The term refers to a residue, but the logical definition refers to just the free carbohydrate. 

I suggest we remove the logical definition, which will remove the carbohydrate derivative parent and the monocarboxylic acid parent. This will leave it a child of cellular polysaccharide biosynthetic process. 

@hdrabkin @deustp01  what do you think. It appears that organic acids in ChEBI are limited to what GO has decided are small molecules. If we remove the organic acid- small molecule link, we will have to manually reclassify all the children.
