### ISSUE TITLE
 NTR : regulation of small molecule metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15314]
seems to be missing?
NTR : regulation of small molecule metabolic process

**Comment by ukemi** [comment]
Have we even come to a consensus about what 'small' is when referring to these?

**Comment by ValWood** [comment]
I think the current set of terms under here is OK, except:
https://github.com/geneontology/go-ontology/issues/14047
We use it to represent "general metabolism" excluding things like transcription,translation, DNA metabolism,  and it works  well (except for the vitamin/cofactor issue).

I don't know how we would represent this important module without this term...it isn't perfect but it's all we have...
