### ISSUE TITLE
zinc vs zinc II in transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15310]
Did we establish that all zinc ion transport  is zinc II?

If so can this standardize?

We pick up redundant IEA's in this additional branch:

![zinc2](https://user-images.githubusercontent.com/7359272/36897900-662649a8-1e10-11e8-9f5e-6d1225193c5b.jpg)

**Comment by ValWood** [comment]
![zinc](https://user-images.githubusercontent.com/7359272/36897974-b8645002-1e10-11e8-99c9-1a2d591d7507.jpg)

**Comment by deustp01** [comment]
According to my ancient general chemistry textbook (1965 - but probably not an area with new discoveries), "Although zinc and cadmium display only the +2 ionization state, both +1 and +2 are known for mercury." Three facts for the price of one.

**Comment by ValWood** [comment]
Thank you!
