### ISSUE TITLE
Incorrect taxon constraint propagating through the component ontology

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#15325]
Hi,

Tried to add some annotations in P2G for yeast genes to actin cortical patch, and when I hit submit I get the following error:

"Annotation failed taxon constraint GO:0005623 (cell) and its descendants should ONLY be used with gene products from the taxonomic group cellular organisms"

Suzi suggested I check with either @Pascale or @tonysawfordebi  

Something is really wrong here as this annotation should be permitted, and must be due to a recent change.

Cheers,
Rob

**Comment by tonysawfordebi** [comment]
@robnash GO:0005623 does have the constraint "only_in_taxon taxon:131567 (cellular organisms)" associated with it, and GO:0030479 (actin cortical patch) is a descendant of GO:0005623, so the constraint also applies to it.

Can you give me an example UniProtKB accession of a protein that you're trying to annotate to GO:0030479?

**Comment by tonysawfordebi** [comment]
I've just checked in our database, and there are 70 annotations from SGD to GO:0030479. I've done a spot check of half-a-dozen of the annotated proteins, running them through the validation code that P2G uses to check for taxon constraint violations, and they all passed.

BTW, I checked when the taxon constraint was added to GO:0005623, and it was in December 2015, so it's not new by any stretch of the imagination.

**Comment by tonysawfordebi** [comment]
That's what I'm thinking, @ukemi, and why I asked for an example.

**Comment by robnash** [comment]
Hi,

Was using UniProt IDs for the proteins in question, so I don't think it was a typo. Was trying to annotate  TDA2 (P40045) and AIM21	(P40563). Suzi also looked over my shoulder so I know I am not fully crazy :)

Anyway, just tried again and everything is working fine. So not sure what happened but it has mysteriously gone away. Thats what I get for trying to add some annotations just before leaving on Friday.

Cheers,
Rob
