### ISSUE TITLE
NTR: bI3 and bI4 intron splicing complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15326]
Hi,
I have to related terms to request: bI3 intron splicing complex and bI4 intron splicing complex.
Thanks in advance
Livia

Term1
Name: bI4 intron splicing complex
Def: A protein complex required for the splicing of intron 4 of the cytochrome b (COB) gene. In S. cerevisiae, the complex contains the maturase bI4 (which derives from one of the products of the splicing), Leucyl-tRNA synthetase NAM2 and the intron 4 of the cytochrome b pre-mRNA. The two proteins stimulate the ribozyme activity of the pre-mRNA which autoctalyse a group I intron splicing.

References:
GOC:lnp
PMID:
19622748
Relationships:
is_a GO:1902555 endoribonuclease complex
capable_of GO:0004521 endoribonuclease activity
part_of GO:0005739 mitochondrion
capable_of_part_of GO:0000372 Group I intron splicing
capable_of_part_of GO:0006397 mRNA processing

DB xref:EBI-16420264

Term2
Name: bI3 intron splicing complex
Def: A protein complex required for the splicing of intron 3 of the cytochrome b (COB) gene. In S. cerevisiae, the complex contains the maturase bI3 (which derives from one of the products of the splicing), the MRS1 cofactor and the intron 4 of the cytochrome b pre-mRNA. The two proteins stimulate the ribozyme activity of the pre-mRNA which autoctalyse a group I intron splicing.

References:
GOC:lnp
PMID:
11773622
Relationships:
is_a GO:1902555 endoribonuclease complex
capable_of GO:0004521 endoribonuclease activity
part_of GO:0005739 mitochondrion
capable_of_part_of GO:0000372 Group I intron splicing
capable_of_part_of GO:0006397 mRNA processing

DB xref:EBI-16426213

**Comment by hdrabkin** [comment]
@krchristie could you take a quick peek at this?

**Comment by krchristie** [comment]
@hdrabkin - These complexes sound reasonable to me based on my knowledge of splicing in cerevisiae, and generally. My understanding is that very few of the Group I and Group II introns are actually self splicing in vivo, but that most require a maturase that binds to the intron to stabilize its structure and allow RNA autocatalysis of the splicing reaction.

 Did you have any specific questions?

**Comment by hdrabkin** [comment]
No, just lately hesitant to proceed with complexes unless reviewed by more of an expert than myself.

**Comment by hdrabkin** [comment]
Sorry for the delay
+id: GO:0106391
+name: bI4 intron splicing complex

+id: GO:0106392
+name: bI3 intron splicing complex

Note: part_of mitochondrion not used
