### ISSUE TITLE
Fix label for GO:0061990, molecular_function "beta-ketodecanoyl-[acyl-carrier-protein] synthase

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#15322]
https://github.com/geneontology/helpdesk/issues/103

Close helpdesk ticket when this is done, thx!

**Comment by ukemi** [comment]
I have a PR to fix the label, but I still think the annotations need to be reviewed.

**Comment by ukemi** [comment]
I fixes two labels. Closing this ticket, but leaving the helpdesk ticket open until the annotations are reviewed.
