### ISSUE TITLE
NTR: regulation term for GO:0097688 glutamate receptor clustering

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#15330]
Could I have a regualtion term for:
GO:0097688 glutamate receptor clustering

regulation of glutamate receptor clustering
Any process that modulates the frequency, rate or extent of glutamate receptor clustering.
PMID:28455372
GOC:ha

**Comment by hdrabkin** [comment]
Hi @hattrill ; do you also need the +/- reg terms as well?

**Comment by hattrill** [comment]
I don't have any examples of negative clustering, so I don't think so.

That said, if it is general policy to add +/- terms to save future work, then I will use the +ve.

**Comment by ukemi** [comment]
It wouldn't be negative clustering, it would be a separate process that negatively regulates the clustering process. This is an important distinction in modeling.

**Comment by hattrill** [comment]
Yes - that was my kind of thinking.

**Comment by hattrill** [comment]
So, let's not have the +/- and just have the reg

**Comment by pgaudet** [comment]
Hi, 

just wondering: isn't receptor clustering is spontaneous or mediated by self-assembly; ie what *mediates* receptor clustering ? It seems to me everything that has to do with receptor clustering is regulation - isn't it ? 

Pascale

**Comment by hdrabkin** [comment]
GO:0106104 regulation of glutamate receptor clustering

**Comment by hattrill** [comment]
Hmmm...difficult to say. The process is a bit foggy - a bar domain protein does something that casues the receptors to cluster and that thing is regulated by other proteins.
So, it might well be, bar domain protein does something to membrane/cytoskeleton that enhances clustering and that is regulated by the other proteins.

**Comment by hdrabkin** [comment]
The term went in before any of this discussion

**Comment by hattrill** [comment]
That's fine! In any case, I need the reg term!

**Comment by hdrabkin** [comment]
Ok, I will close this ticket
