### ISSUE TITLE
GO:0061804    mitotic spindle elongation during mitotic prophase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15342]
should be part of 
GO:0090307    mitotic spindle assembly
(I thought we already did that one?)

**Comment by ukemi** [comment]
I thought we had decided that the elongation wasn't part of the assembly, but rather part of the organization. @hdrabkin , if you make this switch, make sure the other elongation terms are consistent.

**Comment by ValWood** [comment]
The first part of elongation is assembly. That is the part that happens at mitotic prophase. A spindle assembly by elongating.....

**Comment by ValWood** [comment]
Ignore it's all covered in here.
With expert input from Takashi...
https://github.com/geneontology/go-ontology/issues/13461
this is a duplicate
