### ISSUE TITLE
NTR: protein localization to mitotic spindle pole body

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15344]
I want this term to annotate a bona fida  anchor for sid4 at the spindle pole body.

If we don't want to add these term I could do this another way, if there  was a molecular function term to describe a "molecular anchor"  that would encapsulate the fact that ppc89 is involved in localizing sid4. At present I used "protein binding" but  this does not capture the localization concept.
PMID:16775007

**Comment by ValWood** [comment]
These data indicate that Ppc89 is required to recruit or maintain a variety of proteins at the SPB and suggest that Ppc89 might be required for SPB integrity.

**Comment by pgaudet** [comment]
IMO 'localization' used in this way is fine.

Pascale

**Comment by ValWood** [comment]
not to self curs/574df5dbdb6edf7f

**Comment by krchristie** [comment]
Neither of these existing terms work for you? 
- asymmetric protein localization to new mitotic spindle pole body (GO:0061510)
- asymmetric protein localization to old mitotic spindle pole body (GO:0061509)

**Comment by ValWood** [comment]
no, we need a parent that does not mention asymmetric localization....

**Comment by krchristie** [comment]
This term already exists:
protein localization to mitotic spindle pole body (GO:1902440)

**Comment by ValWood** [comment]
I was looking in the wrong place ;)
