### ISSUE TITLE
mitotic spindle organization in nucleus 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15341]
this is a problematic term.

for fission yeast most mitotic spindle organization occurs in the nucleus.
The term has no children.

I suggest obsoletion and using the more specific terms with 
occurs in GO:0005634 (nucleus)

Looking at the history it seems that the term was created for fungi (used to be called 
mitotic spindle organization and biogenesis (sensu Fungi)

but we really don't need it. It will lead to inconsistent annotations.

Only has 15 annotations to 9 genes  SGD
1 dicty annotation 

@srengel 
@pfey03 

do you agree that other terms would be more appropriate?

**Comment by srengel** [comment]
i can rehouse these, i don't object to that.  they could be moved 30472 to 7052 col16 occurs_in 5634.

side note: i see two sibling terms that could also be obsoleted for same reason (during could be moved to col16):
• mitotic spindle elongation during mitotic anaphase 
• mitotic spindle elongation during mitotic prophase

**Comment by ValWood** [comment]
These are different

• mitotic spindle elongation during mitotic anaphase
• mitotic spindle elongation during mitotic prophase

They aren't about where the process occurs. the reason there are 2 terms is to disambiguate the 2 separate stages of spindle elongation.
The first, pre chromosome segregation stage (spindle assembly), and the stage during anaphase B when the spindle fully elongates.

v

**Comment by pgaudet** [comment]
Hi @ValWood 
Which more specific term do you suggest people use? I don't see any children. 

Would it be OK to merge into the parent "mitotic spindle organization" as a narrow synonym? 

Thanks, Pascale

**Comment by ValWood** [comment]
I mean more specific annotation (i.e other children of  mitotic spindle organization  rather than 
more specific to the "in the nucleus term"

A merge and narrow synonym would be perfect.
