### ISSUE TITLE
Status - GO release and PAINT annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15351]
Hi @cmungall 

What is the status on PAINT annotations integration (and export) in the GO database? 

For example this family have been modified in July - this is not yet showing up in AmiGO (annotation should be deleted): 

TMS1 | Vacuolar membrane protein of unknown function |   | L-serine transmembrane transporter activity |   | GO_Central | Saccharomyces cerevisiae S288C | IBA | PANTHER:PTN000043695 | serine incorporator pthr10383 |   | SGD_REF:S000185201 | 20150303

Thanks, Pascale

**Comment by suzialeksander** [comment]
This looks OK to me now, I don't see this annotation on http://amigo.geneontology.org/amigo/gene_product/SGD:S000002512.   OK to close?

**Comment by pgaudet** [comment]
Looks good. Thanks for checking !
