### ISSUE TITLE
GO:0009022 tRNA nucleotidyltransferase activity not a transferase, but is an exonuclease

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15357]
Hello, 

While working on #15308, I came across a wiki page that states that 'most nucleases are hydrolases' .. implying that they are not all nucleases: 
https://en.wikipedia.org/wiki/Nuclease

Nuclease activity (GO:0004518) has the following comment: "Note that 'tRNA nucleotidyltransferase activity ; GO:0009022', also known as 'ribonuclease PH', and 'DNA-(apurinic or apyrimidinic site) lyase activity ; GO:0003906' do not have parentage in the 'nuclease activity' branch of the ontology because both GO and the Enzyme Commission define nuclease activity as a type of hydrolysis."

However I dont find just 'nuclease activity' in EC. We have a link to a partial EC, 3.1.-.- , but this corresponds to "hydrolases, acting on Ester Bonds", so it's not specific to nucleases. 

I propose to remove the EC x reference from nuclease activity (GO:0004518) , and to add more specific parents to children terms, based on the comment above. 

@hdrabkin 
@sjm41 
Does that seem OK to you ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
The name for GO:0009022 is extremely confusing; when I look at the name I think of the tRNA 3'CCA addition enzyme, not a nuclease.  
Remember EC usually does not really have grouping terms; they classify by the type of reaction on a very broad scale. Thus, GO has nuclease activity, which makes sense to GO, but if all a nuclease has to do to be a nuclease is to 'cleave the phosphodiester backbone", then, no; not all nucleases are hydrolyases. I Think removal of the xref is warrented,

**Comment by pgaudet** [comment]
Great !

**Comment by sjm41** [comment]
_**I propose to remove the EC x reference from nuclease activity (GO:0004518)**_
Yes, definitely agree.

**_and to add more specific parents to children terms, based on the comment above._**
Would be good to see these proposals.
E.g. I think you'll need to remove the current parent-child relationship between 'hydrolase activity, acting on ester bonds (GO:0016788)' and 'nuclease activity (GO:0004518)'. Right?

**Comment by pgaudet** [comment]
@sjm41 
Yes, nuclease activity would be directly under MF. More specific children could be hydrolases or others as appropriate. 

Pascale

**Comment by ValWood** [comment]
this  term is now called 

GO:0009022  
phosphate-dependent exonuclease activity

so can this ticket close?

**Comment by sjm41** [comment]
Looks like the edits to 'nuclease activity' parentage still need to happen:
![Screenshot 2022-11-21 at 14 04 14](https://user-images.githubusercontent.com/16306861/203074682-cc523732-d19c-48de-8af4-81d41e38c564.png)

Also, do we really want to keep the BP term "GO:0090305 nucleic acid phosphodiester bond hydrolysis"?  Sounds rather like a MF to me....

**Comment by sjm41** [comment]
So, is there another ticket to take care of the edits to 'nuclease activity' parentage mentioned above?

**Comment by hdrabkin** [comment]
Not that I know of. It might we better to create a ticket specifically for the nuclease activity parentage.

**Comment by sjm41** [comment]
OK - Pascale first reported the issue with nuclease activity - do you want me to make the new ticket @pgaudet ?

**Comment by sjm41** [comment]
Made new ticket for nuclease parentage issue: #24408

**Comment by pgaudet** [comment]
thanks @sjm41
