### ISSUE TITLE
NTR plasma membrane binding

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15352]
Hi,

I would like to request
plasma membrane binding 
from PMID:26702831 fig2 and fig6

**Comment by pgaudet** [comment]
Don't we annotate to 'phospholipid binding' for such cases? (and CC plasma membrane or extrinsic to plasma membrane) ?

**Comment by ukemi** [comment]
I agree. I don't think plasma membrane binding is very useful.

**Comment by Antonialock** [comment]
great thanks!
