### ISSUE TITLE
NTR: Nonsense-mediated decay complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15365]
Hi,
I'd like to request a new go term for the following complex.
Thanks in advance
Livia

Name: Nonsense-mediated decay complex
Def: A highly conserved protein complex that recognises and elicits the rapid degradation of mRNAs in which an amino-acid codon has changed to a nonsense codon; occurs when the 3' end is not protected by a 3'-poly(A) tail; degradation proceeds in the 3' to 5' direction.

References:
GOC:lnp
PMID:
1569946, 9032286, 29282598
Relationships:
is_a GO:1902494 catalytic complex
capable_of_part_of GO:0071026 cytoplasmic RNA surveillance
capable_of_part_of GO:0070478 nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay
capable_of GO:0004004 ATP-dependent RNA helicase activity
capable_of GO:0036002 pre-mRNA binding

DB xref:EBI-16420380

**Comment by ValWood** [comment]
Can we this the Upf complex ? (term biologist use)
synonym
Upf1p-Upf2p-Upf3p complex
(if this is what it is?)

**Comment by krchristie** [comment]
I need some clarification of exactly what complex you want a term for. While I understand that there is some debate about defining complexes by their composition, I think that without at least some description of the composition, often by 1 or more specific examples, with any notable exceptions mentioned if needed, it is very hard as a curator to read the definition and know if the term is meant for the complex at hand or not.

Here are the results of some PubMed searches
* "nonsense-mediated decay complex" => Quoted phrase not found.
* "Upf complex"  => 9 results
* "NMD complex" => 7 results

Looking briefly at a variety of those papers suggests that there may be at least a couple different complexes, a Upf complex composed of Upf1, Upf2, and Upf3, and also a NMD complex (also referred to once as the Upf1-2-3 NMD complex) composed of the Upf complex plus additional NMD factors. Here are some examples:

quote from: **Takeda S et al. Role of a tyrosine phosphorylation of SMG-9 in binding of SMG-9 to IQGAP and the NMD complex. Biochem Biophys Res Commun. 2011 Jun 24;410(1):29-33. PMID:21640080**
> SMG-9 has been recently characterized as a component of the nonsense-mediated mRNA decay (NMD) complex that contributes to a RNA surveillance by degradation of mRNAs containing premature translation termination codons [6,7]. The NMD complex contains many proteins such as SMG-1 to SMG-10 (SMG-2 to SMG-4 are also named as Upf1 to Upf3) [6–9]. 

quote from: **Kerényi F et al. Phosphorylation of the N-and C-terminal UPF1 domains plays a critical role in plant nonsense-mediated mRNA decay. Plant J. 2013 Dec;76(5):836-48. PMID:24118551**
> The eRF3-bound UPF1 recruits the UPF2 and UPF3 proteins and then the assembled UPF1-2-3 NMD complex induces rapid degradation of the transcript. 

quote from: **Son M, Wickner RB. Nonsense-mediated mRNA decay factors cure most [PSI+] prion variants. Proc Natl Acad Sci U S A. 2018 Feb 6;115(6):E1184-E1193. PMID:29358398**
> We find that the curing ability of Upf proteins is uncorrelated with these previously reported functions but does depend on their interaction with Sup35p and formation of the Upf1p-Upf2p-Upf3p complex (i.e., the Upf complex).

**Comment by liviap** [comment]
Dear @krchristie,
to be honest, as my usual practice, I've chosen this term name to make it consistent with other GO terms such as GO:2000624 or GO:2000623. I have to say that, sometimes, I find GO terms inconsistent with each-other (which is a pity since we are talking about ontology)... as a user, I've often got trouble in querying GO. But this is my personal opinion and might not reflect GO terms name policy, so, if you believe this is the case and  since in pubmed "Upf complex"  and "NMD complex" are more popular, "NMD complex" could be fine to me, with "Upf complex" as a synonym.

**Comment by pgaudet** [comment]
Indeed the protein complex group is supposed to provide naming guidelines as one of the goals of the group. @bmeldal perhaps this is a good example?

**Comment by ValWood** [comment]
I'm with Karen here. We should use  the names the community use. The ontology is not to enforce/standardize  names for terms, we  provide structure via definitions and logical relationships, rather than by term names.

**Comment by bmeldal** [comment]
My gut feeling is to call it nonsense-mediate decay complex as that's the full name and and matches the term names of the process.

The community seems to call this complex by lots of different names depending on personal preference and species. In the original S.c. paper it's called Upf1p-Nmd2p-Upf3p complex but the actual official gene symbols are NAM7, NMD2 and UPF3. Go figure!

We can then have a long list of synonyms, I've just expanded the synonyms in the CP as I was looking through this ticket with Livia.

As Livia mentioned above, if the common name doesn't exist in GO the data is not FAIR (=! findable in this case). Searching with "NMD" finds NMDA terms first, "...nonsense-mediated decay" is only the 5th hit and it's a child of the parents term at that...

As for our practice: we use the community name as term name and if there are various versions we use the most informative name for the human user as term name and everything else as synonyms. Synonyms are indexed so the complex will still show up.

And so it continues... ;-)

**Comment by krchristie** [comment]
sigh... I thought I had put in a response but I must have forgotten to actually click "Comment"...

I have two issues here:

**1. Regarding the name for the complex:** - As I pointed out earlier, searching PubMed for several related strings suggests that "nonsense-mediated decay complex" is NEVER found, suggesting to me that this is a poor choice for the complex name, in contrast to "NMD complex" which is found.
- "nonsense-mediated decay complex" => Quoted phrase not found.
- "Upf complex" => 9 results
- "NMD complex" => 7 results

**2. Identity/composition of the complex** - 
**A.** From what little reading I did, it seemed to me that the Upf complex is a small complex consisting of Upf1, Upf2, and Upf3, while the NMD complex is a larger complex of 9-10 subunits containing the Upf complex plus multiple additional proteins. I think that some indication of composition is required here to provide clarity of what complex this term is trying to represent
**B.** Do we need two terms here, one for Upf complex and another for NMD complex?

**Comment by krchristie** [comment]
Also, I agree that it is a problem that NMD does NOT bring up many of the nonsense mediated decay process terms, so I think that we should add appropriate synonyms to these terms.

**Comment by krchristie** [comment]
To act on this ticket, I need more detail regarding the composition, so that it is clear whether this term refers to the minimal Upf1-2-3 complex of the larger NMD complex. I was also wondering if there should be two terms, as indicated in a previous comment.

I also have a question about this requested dbxref: DB xref:EBI-16420380
Is EBI the prefix, or is EBI part of the ID and something else is the prefix? Should the prefix be IntAct?

**Comment by bmeldal** [comment]
Yup, syntax error:
DB xref:
IntAct:EBI-16420380

I'll let Livia answer the composition question :)

**Comment by krchristie** [comment]
Thanks for providing the correct syntax for the dbxref @bmeldal 

@liviap - When you have a chance, please provide more info about the composition of the desired term, or if we need two terms (more detail in previous comments).

**Comment by liviap** [comment]
Hi @krchristie !!!
Sorry for my superlate reply, I've been on Holiday!
Regarding the composition, as far as I could see NAM7, NMD2 and UPF3 correspond to UPFs proteins. In 17704778 the complex is called "nonsense-mediated mRNA decay complex" and refers to Upf1,2,3 , even though the complex is more often named "upf complex".
To summarise, in my opinion the complex is only one (Upf1-2-3 complex or NMD complex), I wouldn't add a larger complex for NMD .

**Comment by liviap** [comment]
Sorry to bother...Any update on it?

Livia

**Comment by edwong57** [comment]
capable_of GO:0004004 ATP-dependent RNA helicase activity was obsoleted, so I used 'RNA helicase activity' instead. I added Upf complex as a synonym.
