### ISSUE TITLE
missing parentage GO:0010106 cellular response to iron ion starvation

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15364]
should GO:0010106 cellular response to iron ion starvation
be part_of GO:0006879 cellular iron ion homeostasis ?

**Comment by RLovering** [comment]
I have often wondered this about the homeostasis terms and cellular response terms

Ruth

**Comment by Antonialock** [comment]
yeah I'm unsure. I'm trying to think of "cellular response to X" that are not linked to "homeostatic control of X" but can't think of any. But it feels like they could/might very well exist.

for example. during "cellular response to nitrogen starvation" you get global downregulation of gene expression in fission yeast. This obviously wouldn't be a homeostatic response, only a "response to nitrogen starvation". (there are no homeostasis terms for nitrogen so it is not a good example, but I can't think of any examples involving processes where both a homeostasis terms and "response to" terms exist).

**Comment by pgaudet** [comment]
I think the response to signaling molecules break that rule - for eg cellular response to dopamine, cellular response to insulin stimulus, etc. 
Pascale

**Comment by Antonialock** [comment]
@pgaudet there are no terms for "insulin homeostasis" or "dopamine homeostasis" so I don't understand how they are relevant?

**Comment by Antonialock** [comment]
(although wouldn't it make sense if "cellular response to insulin" was part of "glucose homeostasis"?

**Comment by pgaudet** [comment]
I thought you meant all 'responses' were homeostasis - sorry.

**Comment by Antonialock** [comment]
Ah no, I meant "when there is a 'response to presence/absence of substance' and a 'homeostasis of substance' term for the same substance, then should the response to terms be part_of homeostasis?

**Comment by Antonialock** [comment]
I haven't considered all terms of this type so the ticket is just about the iron terms

**Comment by pgaudet** [comment]
The problem is that 'response to' is more general. In certain cases the role of the protein is homeostasis is not clearly demonstrated (ie when they only look at expression, which is often the case) - perhaps for example here: https://www.ncbi.nlm.nih.gov/pubmed/17236162) 

what do you think ? 

Pascale

**Comment by Antonialock** [comment]
Well from the abstract those genes would fit both homeostasis and response to iron starvation? 

A curator would use judgement when annotating - i.e. if an RNA seq experiment shows upregulation of 150 genes then we wouldn't annotate all 150 to "response to X" (at least I hope not!), but if there is smaller scale characterization, author intent, additional information (these proteins are known/suspected to be involved in siderophore biosynthesis) then there isn't an issue?

**Comment by deustp01** [comment]
A priori, in a variable environment wouldn't "X homeostasis" generally have parts "response to X deficiency" and "response to X excess"? That might get complicated for nitrogen sources in a prototroph or for glucose, but for metal ions both parts seem reliably needed. But poking around in GO looking for examples, I can't find any, so maybe this is an idea that has already been disposed of. @mah11 ?

**Comment by pgaudet** [comment]
Well I certainly don't have a problem doing a merge... Many people seem more familiar with the response to terms, should we ask for people to review their annotations?

**Comment by Antonialock** [comment]
I think with merging we would lose specificity? I meant adding this parentage:
1. cellular response to iron ion starvation **part_of** cellular iron ion homeostasis
2. cellular response to iron ion  **part_of** cellular iron ion homeostasis

**Comment by ValWood** [comment]
I think we should  not use "in response to" as processes (except in a few exceptions).

They  should be available  to use as extensions  (happens during response to x)

https://github.com/geneontology/go-ontology/issues/14303
@cmungall  suggested using  event exposure ontology for this...

I just feel that they are not  very useful to describe actual biological processes.....

There are exceptions though, maybe starvation is one of those.

I guess the terms should be part of the corresponding homeostasis term if it exists...

**Comment by Antonialock** [comment]
well if it is useful to have a term for starvation, then isn't it useful to have a term for "overload" (which for iron is toxic)

**Comment by Antonialock** [comment]
on a tangent:
Are the siderophore biosynthesis genes part of the "response to..." or the result of the "response to..."
i.e. should we annotate just the signaling cascade to the "response to" term or all the genes that form part of the response? (and are the TFs then regulating the response?)

**Comment by Antonialock** [comment]
I think I'd be leaning towards annotating siderophore biosynthesis to "response to" and the TF to "regulating the response to" but care would need to be taken so you don't annotate genes that are implicated due to knock-on effects?

**Comment by ValWood** [comment]
Isn't overload  abnormal process though (occurs if systems are faulty- heamochromotosis!)

**Comment by deustp01** [comment]
Haemochromatosis is abnormal, yes, but in some cases, it's due to a failure of the normal mechanisms the body uses to deal with high environmental iron levels, and that's the point here: homeostasis requires both an ability to scrounge iron when it's scarce and to fend it off when it's abundant.

**Comment by ValWood** [comment]
Good point. I was focussed on the  Haemochromatosis since I recently found I was homozygous postitive for faulty HFE...... now I need to avoid  iron rich environment as well as food!

**Comment by Antonialock** [comment]
I think pombe has "normal processes" to deal with an abundance of iron 
e.g.
"Iron enters cells through the activity of membrane transporters or receptor-mediated endocytosis. While most of the intracellular iron gets safely stored either in complex with the iron-storage protein ferritin (for example, plant and mammalian cells) or inside organelles (for example, yeast and plant cells), a small amount of total cellular iron is present as a metabolically available pool in the cytoplasm, termed the labile iron pool (LIP). The LIP consists of iron loosely bound to small negatively charged molecules and proteins4 and provides iron for cellular processes including haem and Fe–S cluster biosyntheses5.

Appropriate storage of any excess of iron, which is not used metabolically, is essential to prevent cellular toxicity due to engagement of iron in Fenton-type chemistry in the presence of oxygen and production of potentially damaging reactive oxygen species6. Ferritin represents the most common and ancient mechanism of iron storage and homeostasis in nature, as it is found in most bacteria, archaea, plants and animals, but not in yeast7. In the absence of ferritin, the yeast vacuole serves as the main iron-storage/sequestration organelle. In response to demands, iron moves to and from the yeast vacuole through the activity of iron transporters in the yeast vacuolar membrane; CCC1 (Ca2+-sensitive cross complementer 1) is proposed to import iron, while a complex constituted by Smf3p and Fet5p-Fth1p exports iron8,9,10. Thus, vacuolar sequestration by CCC1 in yeast is likely to be the primary mechanism for detoxification of excess iron in this organism. "

from https://www.nature.com/articles/ncomms10403

**Comment by cmungall** [comment]
Let me try a simplistic summary:

 1. Response to X is still valid even if X is pathological/stress, so long as there is some evolved mechanism for dealing with X
 2. Response to X should only be a pre-composed term if there is reasonable evidence this is an evolved response. Otherwise c16. I might argue that if X is experimental i shouldn't even go in c16, the combo of the term plus c16 should still describe in-vivo biology
 3. We need to encode formally as design patterns:
    * response-to decreased levels of X (aka starvation) part-of X homeostasis
    * response-to increased levels of X part-of X homeostasis

**Comment by Antonialock** [comment]
> I might argue that if X is experimental i shouldn't even go in c16, the combo of the term plus c16 should still describe in-vivo biology

I guess what you mean by "if X is experimental" is that it is not something that a cell is likely to encounter in situ? I agree if you mean that we should annotate to "cellular response to DNA damage" but not "cellular response to phleomycin" (DNA cleaver)

**Comment by ValWood** [comment]
Summary sounds good

**Comment by pgaudet** [comment]
Hello, 

I've added the relation 'cellular response to iron ion starvation is 'part of cellular iron ion homeostasis' - is this what was requested ? (ie I didn't create a design pattern @cmungall )

@Antonialock Is this is OK please let me know. 

Another point:  When I look at annotations I am not sure there really is a difference between response to and homeostasis in this case - also I am not sure the chlidren are very informative: 
- GO:1901966 regulation of cellular response to iron ion starvation
- GO:1901967 negative regulation of cellular response to iron ion starvation
- GO:0033217 regulation of transcription from RNA polymerase II promoter in response to iron ion starvation 

Thanks, Pascale

**Comment by Antonialock** [comment]
Yes it is what I requested but I might be using "response to" in a narrower sense than how it is intended to be used?

**Comment by pgaudet** [comment]
Well there are a limited number of possible responses in this case: to have correct iron level in the cell you need to either import it (under 'starvation' conditions) or sequester it when there is too much. 

What else is there ? 

Pascale

**Comment by Antonialock** [comment]
That sounds sensible to me.

**Comment by pgaudet** [comment]
OK - i'll close the ticket. Please open a new ticket if you want to deal with 

    GO:1901966 regulation of cellular response to iron ion starvation
    GO:1901967 negative regulation of cellular response to iron ion starvation
    GO:0033217 regulation of transcription from RNA polymerase II promoter in response to iron ion starvation

(which are probably iron homeostasis as well). 

Thanks !! 

Pascale
