### ISSUE TITLE
precomposed F- in P merge up?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15368]
These will lead to inconsistencies

ubiquitin protein ligase activity involved in ERAD pathway
(5 EXP)

ubiquitin protein ligase activity involved in chloroplast disassembly
(1 EXP)

**Comment by pgaudet** [comment]
ubiquitin protein ligase activity involved in ERAD pathway
(5 EXP) BHF-UCH 
UniProtKB	A0AVI4	TMEM129	PMID:24807418
UniProtKB	Q14258	TRIM25	PMID:24810856
UniProtKB	Q86TM6	SYVN1	PMID:14593114
UniProtKB	Q96GF1	RNF185	PMID:24019521
UniProtKB	Q9UNE7	STUB1	PMID:23990462

ubiquitin protein ligase activity involved in chloroplast disassembly
(1 EXP) TAIR 
UniProtKB:F4ILG6	PUB4	PMID:26494759	

@RLovering @tberardini  are you OK with merging up to 'ubiquitin protein ligase activity ' ? 
Thanks, Pascale

**Comment by ValWood** [comment]
instead 
ubiquitin protein ligase activity part_of ERAD pathway

(so we do not need
ubiquitin protein ligase activity involved in "every process"
...not sustainable....

**Comment by pgaudet** [comment]
@ValWood 
Can I remove the synonyms
- mitotic anaphase-promoting complex activity 
- ubiquitin-protein ligase activity involved in positive regulation of mitotic metaphase/anaphase transition
?

**Comment by RLovering** [comment]
give me a min to update the AE fields. FYI these are Rebecca's as part of the Parkinsons-UCL project ;)

**Comment by RLovering** [comment]
ok done please go ahead. I have changed the annotations to the ubiquitin-protein ligase activity term and added the AE part_of as suggested

**Comment by ValWood** [comment]
synonyms can remove.
ubiquitin-protein ligase activity involved in positive regulation of mitotic metaphase/anaphase transition

is from a previous F-P merge

**Comment by pgaudet** [comment]
I am going to merge the pr - @tberardini hopefully that's OK for you ? 

Thanks, Pascale

**Comment by tberardini** [comment]
@ValWood -"These will lead to inconsistencies"

Why?

I haven't had time today to look into this yet.  Can you wait to merge please?

**Comment by ValWood** [comment]
Because to be consistent we would need to request
"ubiquitin ligase activity"  part of "every process" which would be 100's of new  terms?

**Comment by tberardini** [comment]
Ok, I understand.  Thanks for providing the context @ValWood.  Go ahead and merge, @pgaudet.  Our system should pick up the merged terms and transfer the annotation accordingly.

**Comment by ValWood** [comment]
We already decomposed the few others rather than pre compose *every one*...The plan is not to precompose MF involved in BP as it would be generally unsustainable and is a sensible place  to post compose.

**Comment by pgaudet** [comment]
@ValWood 

We still have a few terms containing the 'involved in ERAD pathway' string: 

- 'ubiquitin-specific protease activity involved in negative regulation of ERAD pathway' <GO_1904455> (0 annotations)
'- ubiquitin-specific protease activity involved in positive regulation of ERAD pathway'<GO_1904454> 1 EXP BHF 


Should I also merge these up ?

**Comment by RLovering** [comment]
I have revised the annotations, only it was a Parkinson's UCL annotation, hopefully there isn't a BHF one too
Ruth

**Comment by pgaudet** [comment]
Thanks you !

**Comment by pgaudet** [comment]
Now we have this one left: 

'GO:1904265 ubiquitin-specific protease activity involved in negative regulation of retrograde protein transport, ER to cytosol - @RLovering Can this be reannotated and the term merged up ? 

This is the last term that is 'ubiquitin hydrolase involved in x'. 

Thanks, Pascale

**Comment by RLovering** [comment]
yes I have revised the annotation and you can now delete or merge up this term
Thanks

Ruth
