### ISSUE TITLE
NTRs? for "proximal portion of axoneme" and "distal portion of axoneme"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#15361]
I am annotating PMID_26909801 and it shows a bunch of localization evidence, e.g. Dnah11 is in proximal portion of the axoneme of a "9+2 motile cilium" in respiratory epithelium, but is pan-axonemal in the "9+0 motile cilium" of the mouse embryonic node. In human cells, they also show that human DNAH11 is in proximal portion of the axoneme of a "9+2 motile cilium" in respiratory epithelium, while DNAH9  is found in only the distal region of the axoneme of these same cells.

Currently, I can annotate to the term "axoneme" and make a model or extensions to indicate the appropriate type of axoneme (9+2 motile vs 9+0 motile) and cell type or anatomy structure.

However, it seems this misses the main point of this work, which is localization of DNAH11 or DNAH9 to the **_proximal_** versus **_distal_** portions of the axoneme in these specific cell types.

I could capture the proximal and distal specific localizations with GO terms with two new terms:
proximal portion of axoneme GO:new1
distal portion of axoneme GO:new2

@paolaroncaglia @JohnvanDam @ukemi  Any objections to this proposal?

thanks,

Karen

**Comment by ukemi** [comment]
I agree. After a quick scan of the paper it looks like the take home message is the specific localization. Plus this seems to have a clinical importance.

**Comment by paolaroncaglia** [comment]
@krchristie @ukemi 
I haven’t had a chance to read that paper, but the summary that you both give find me in full agreement with the new terms proposal. Plus there are a few other examples of the use of ‘proximal’ and ‘distal’ in GO where this improves the information content. Thanks.

**Comment by krchristie** [comment]
human annotations updated to use new terms on 3/12/2018
mouse annotations updated to use new term on 3/16/2018
