### ISSUE TITLE
def tweak : establishment of spindle pole body localization to nuclear envelope

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15360]
establishment of localization in cell
is defined
Any process, occuring in a cell, that localizes a substance or cellular component. This may occur via movement, tethering or selective degradation.

this is the correct def for "establishment of localization, it isn't necessarily transport"

However
GO:0071790    establishment of spindle pole body localization to nuclear envelope
is defined
A process in which a spindle pole body is transported to a specific location in the nuclear envelope. A spindle pole body is a type of microtubule organizing center found in fungal cells. PMID:20434336

This should be broadened because it  usually refers to tethering 
A process in which a spindle pole body is *localized* to a specific location in the nuclear envelope.

**Comment by mah11** [comment]
Wouldn't tethering be maintenance of SPB localization?

**Comment by ValWood** [comment]
I get confused by this. I think my confusion comes from the contractile  ring. There is the process of "establishment of localization of the contractile ring" (this involved tethering, not transport).

Then there is the process of keeping the contractile ring at it's location. This also involves tethering, but different pathways keep the ring at its location when it is built.

Maybe the solution  for the spindle pole body is not to have a distinction between "establishment" and "maintenance" and just go with localization. 

establishment has
PomBase cut11,kms2,tts1
SGD NBP1

maintenance has no annotations

**Comment by ValWood** [comment]
I forgot about this one,
https://github.com/geneontology/go-ontology/issues/14887
should be done at the same time,
I think the solution is to have

localization (insertion plus later movement within the nuclear envelope)
--insertion (syn establishment, initial localization)
get rid of "maintenance" we have no genes for that

**Comment by vanaukenk** [comment]
@valwood - trying to summarize here for both this ticket and #14487:

GO:0070631 spindle pole body localization
is_a		GO:0070632 establishment of spindle pole body localization (any changes?)
part_of 	GO:1990944 maintenance of spindle pole body localization (no annotations, obsolete?)
is_a		GO:0071789 spindle pole body localization to nuclear envelope (update definition?)
		part_of	GO:0071790 establishment of spindle pole body localization to nuclear envelope (Change term label to be 'spindle pole body insertion into nuclear envelope? Update definition? Make 'establishment' label an exact synonym?)
				is_a	GO:new mitotic spindle pole body insertion into nuclear envelope
		is_a	       GO:1990608 mitotic spindle pole body localization to nuclear envelope
			       part_of GO:new mitotic spindle body insertion into nuclear envelope

Any new terms needed for the later movement within the nuclear envelope, or do they already exist somewhere?

GO:0071790 still needs an is_a parent; I think that could still be GO:0070632 as it is currently.

Do you want to include tethering synonyms anywhere?
I saw, too, that there is an exact synonym for GO:0071789 of 'spindle pole body docking'.

Would this review be worth citing as a reference for these terms?
https://www.ncbi.nlm.nih.gov/pubmed/26951196

Thx.

**Comment by pgaudet** [comment]
Hi @ValWood 
I suppose you are talking about maintenance of the contractile ring and related structures? We have many children under 'maintenance of localization': 

'SREBP-SCAP complex retention in endoplasmic reticulum'
'cholesterol storage'
'cortical protein anchoring'
'cytoplasmic sequestering of CFTR protein'
'cytoplasmic sequestering of NF-kappaB'
'cytoplasmic sequestering of protein involved in G2 DNA damage checkpoint'
'cytoplasmic sequestering of protein involved in mitotic DNA replication checkpoint'
'cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint'
'cytoplasmic sequestering of protein'
'cytoplasmic sequestering of transcription factor'
'cytoskeletal anchoring at nuclear membrane'
'cytoskeletal anchoring at plasma membrane'
'extracellular sequestering of copper ion'
'extracellular sequestering of iron ion'
'intracellular sequestering of copper ion'
'intracellular sequestering of iron ion'
'lipid storage'
'maintenance of ER location'
'maintenance of Golgi location'
'maintenance of RNA location'
'maintenance of centrosome location'
'maintenance of chromosome location'
'maintenance of dense core granule location'
'maintenance of endoplasmic reticulum location involved in endoplasmic reticulum polarization at cell division site'
'maintenance of granzyme B location in T cell secretory granule'
'maintenance of location in cell'
'maintenance of mitochondrion location'
'maintenance of nucleus location'
'maintenance of oocyte nucleus location involved in oocyte dorsal/ventral axis specification'
'maintenance of organelle location'
'maintenance of pigment granule location'
'maintenance of plastid location'
'maintenance of pole plasm mRNA location'
'maintenance of protease location in T cell secretory granule'
'maintenance of protease location in mast cell secretory granule'
'maintenance of protein complex location in cytoplasm'
'maintenance of protein complex location'
'maintenance of protein localization at cell tip'
'maintenance of protein localization at growing cell tip'
'maintenance of protein localization in endoplasmic reticulum'
'maintenance of protein localization in organelle'
'maintenance of protein localization to heterochromatin'
'maintenance of protein location in T cell secretory granule'
'maintenance of protein location in cell cortex of cell tip'
'maintenance of protein location in cell'
'maintenance of protein location in chloroplast'
'maintenance of protein location in extracellular region'
'maintenance of protein location in mast cell secretory granule'
'maintenance of protein location in membrane'
'maintenance of protein location in mitochondrion'
'maintenance of protein location in nucleus'
'maintenance of protein location in peroxisome'
'maintenance of protein location in plasma membrane'
'maintenance of protein location in vacuole'
'maintenance of protein location to spindle pole body'
'maintenance of protein location'
'maintenance of secretory granule location'
'maintenance of spindle location'
'maintenance of spindle pole body localization'
'maintenance of vacuolar location'
'maintenance of vesicle location'
'negative regulation of protein export from nucleus'
'negative regulation of ribosomal large subunit export from nucleus'
'negative regulation of ribosomal small subunit export from nucleus'
'negative regulation of ribosomal subunit export from nucleus'
'negative regulation of tRNA export from nucleus'
'nuclear matrix anchoring at nuclear membrane'
'protein retention in ER lumen'
'protein retention in Golgi apparatus'
'sequestering of BMP in extracellular matrix'
'sequestering of TGFbeta in extracellular matrix'
'sequestering of actin monomers'
'sequestering of calcium ion'
'sequestering of copper ion'
'sequestering of iron ion'
'sequestering of manganese ion'
'sequestering of mercury'
'sequestering of metal ion'
'sequestering of neurotransmitter'
'sequestering of triglyceride'
'sequestering of zinc ion'
'sequestration of proteasome core complex in proteasome storage granule'
'vacuolar sequestering of sodium ion'
'vacuolar sequestering'
'vacuole-ER tethering'

Pascale

**Comment by ValWood** [comment]
Sorry I haven't done this, it's on my list for today.  I'll need to refresh.
If you don't hear form me prod me again.

**Comment by ValWood** [comment]
>GO:0070631 spindle pole body localization
is_a	GO:0070632 establishment of spindle pole body localization (any changes?)

I would get rid of this too.
It should not be used for direct annotation anyway... (I don't think we have any justification to distinguish establishment from maintenence here/)

> part_of GO:1990944 maintenance of spindle pole body localization (no annotations, obsolete?)

yep

> is_a	GO:0071789 spindle pole body localization to nuclear envelope (update definition?)
part_of	GO:0071790 establishment of spindle pole body localization to nuclear envelope (Change term label to be 'spindle pole body insertion into nuclear envelope? Update definition? Make 'establishment' label an exact synonym?)

yes, but move parent up to  the general "localization" term.

revised def
A process in which a spindle pole body is embedded  in the nuclear envelope.



> is_a	GO:new mitotic spindle pole body insertion into nuclear envelope
is_a	GO:1990608 mitotic spindle pole body localization to nuclear envelope

yes

> Any new terms needed for the later movement within the nuclear envelope, or do they already exist somewhere?

I think we should add when we need them. I don't think I would annotate this as a process. The SPBs move as the spindle is assembled....


> GO:0071790 still needs an is_a parent; I think that could still be GO:0070632 as it is currently.

will be gone

> Do you want to include tethering synonyms anywhere?
I saw, too, that there is an exact synonym for GO:0071789 of 'spindle pole body docking'.

let's exclude for now and add  from specific sources.

> Would this review be worth citing as a reference for these terms?
https://www.ncbi.nlm.nih.gov/pubmed/26951196

yes this could be used

**Comment by mah11** [comment]
clarification for @pgaudet 

> I suppose you are talking about maintenance of the contractile ring and related structures?

No, this ticket is about spindle pole bodies (GO:00058816 and subclasses).

> We have many children under 'maintenance of localization':

Yes, and many of them represent processes to which gene products contribute. Those are fine.

Occasionally we come across one that doesn't reflect a gene-product-mediated process (presumably from overzealously following the localization/establishment/maintenance pattern), e.g. because the target stays put once localized without further intervention. The "maintenance of SPB localization" terms are such examples.

**Comment by ValWood** [comment]
Confirmation about this term from Takashi Toda:

"I agree that “insertion” is more accurate, and furthermore insertion of daughter SPB into the nuclear membrane."


@vanaukenk  do you need any more info for this one?

**Comment by mah11** [comment]
also see discussion in #16695 (different CC, but the query about what to precompose applies)

**Comment by ValWood** [comment]
I think  the changes to SPB localization have been updated to reflect the actual processes observed so this one is now out of date...
