### ISSUE TITLE
cellular ketone metabolic process missing children?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15378]
shouldn't a lot of sugar metabolism terms be is_a cellular ketone metabolic process?
(The chemical reactions and pathways involving any of a class of organic compounds that contain the carbonyl group, CO, and in which the carbonyl group is bonded only to carbon atoms)

e.g fructose metabolic process, sorbose metabolic process

**Comment by ukemi** [comment]
Closing this becasue it depends on ChEBI.

**Comment by deustp01** [comment]
Piling on after the whistle. Monosaccharides spontaneously isomerize between "keto" andf "enol" forms, nd the equilibrium state has a fair amount of keto form, I think. But biochemists still don't think of sugars as ketone derivatives, so there probably isn't much to gain from pushing ChEBI to make terms to enable it.

**Comment by ukemi** [comment]
I hadn't noticed @cmungall 's request above and wrote to ChEBI separately, hoefully they will come to the same conclusion as you.

**Comment by cmungall** [comment]
I tend to keep shadow tickets open til upstreams are closed YMMV
