### ISSUE TITLE
question about differing parentage in child terms

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15373]
Hi,

I wonder why
GO:0052708 N-alpha,N-alpha,N-alpha-trimethyl-L-histidine metabolic process &
GO:0052698 ergothioneine metabolic process
has the two parents:
GO:0042398 cellular modified amino acid biosynthetic process
GO:0006520 cellular amino acid metabolic process

but
GO:1903256 selenoneine metabolic process &
GO:0019502 stachydrine metabolic process
only have:
GO:0042398 cellular modified amino acid biosynthetic process

should GO:0006520 cellular amino acid metabolic process be removed from the former, added to the latter, or is there a reason for the difference?

**Comment by ukemi** [comment]
I have tidied up this area of the ontology and let the reasoner do the work. Now all of the superclasses are reasoned through ChEBI. It looks like:

ergothioneine is a modified histidine and is a sulfur amino acid and is an amino-acid betaine
selenoneine is a modifies histidine and is an amino-acid betaine, but is not an amino acid
stachydrine is an alpha-amino acid and is an amino-acid betaine and is a modified amino acid, but is not an amino acid
N-alpha,N-alpha,N-alpha-trimethyl-L-histidine is an amino-acid betaine and is an alpha-amino acid and is a modified amino acid. 

Looking at these in ChEBI, they all look  reasonable to me, but I'd rather leave it up to the structural chemists.
