### ISSUE TITLE
GO:0006544 glycine metabolic process remove parent?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15376]
GO:0006544 glycine metabolic process
is_a
GO:0042133  neurotransmitter metabolic process

but this is not true for all glycine metabolism? e.g. tRNA metabolism, porphyrin biosynthesis..

**Comment by pgaudet** [comment]
This is right according to 
https://en.wikipedia.org/wiki/Glycine#As_a_neurotransmitter

**Comment by ukemi** [comment]
Yup so is glutamine, just not in all contexts.

**Comment by Antonialock** [comment]
yes, so what I mean is that 
"neurotransmitter metabolic process" is to "glycine metabolic process"
like
"homologous recombination" is to "DNA repair"

some times it is part of it, sometimes not, so it shouldn't be an is_a?

**Comment by pgaudet** [comment]
Ah interesting idea ! @cmungall @ukemi : could we sort out this 'roles' problem by using a different relation?

**Comment by ValWood** [comment]
Fixed by @krchristie  CheBI roles work?

**Comment by krchristie** [comment]
> Fixed by @krchristie CheBI roles work?

Looking at the inferred view of the editors file in Protege, it looks to me like this relationship has been removed by ceasing to infer over roles, so yes I think this is fixed.

**Comment by krchristie** [comment]
@ValWood - thanks for tagging me on this

**Comment by cmungall** [comment]
Can we go further and just remove `neurotransmitter {metabolism,catabolism,biosynthesis}`?

They are not useful as query classes as results will be confusing incomplete

They seem not particularly useful as classes to directly annotate to. we surely always known more specifically what the chemical is. or in some cases there may be a more informative term for the synaptic context.

E.g
https://www.ncbi.nlm.nih.gov/books/NBK11110

I thought at one point we had decided to remap these to something like synthesis and part-of some neurotransmission?

Some of the direct annotations to biosynthesis come from a mapping from
https://reactome.org/PathwayBrowser/#/R-HSA-112311
it's not clear why this is mapped to the term. Made a separate ticket: https://github.com/geneontology/pathways2GO/issues/113

We also get a lot of annotations to these groupings from

https://www.uniprot.org/keywords/KW-0531
https://www.uniprot.org/keywords/KW-0531

I think a more descriptive term may be more useful here
