### ISSUE TITLE
NTR: mRNA alternative polyadenylation

### ISSUE THREAD

**Issue by Andrestutz** [geneontology/go-ontology#15389]
Dear GO editors,

Could you please consider to create a GO term, "mRNA alternative polyadenylation", 
for a new process described in PMID:29276085. 

That paper shows that the cleavage factor Im (CFIm) complex,
composed of NUDT21/CPSF5, CPSF6 and CPSF7, acts as a positive regulator in
alternative polyadenylation (APA) of pre-mRNAs.

This term would be a child of "mRNA polyadenylation" (GO:0006378).

In the mean time, could you also create regulation GO terms for it.

Thanks a lot for your help

Andre stutz

**Comment by vanaukenk** [comment]
@Andrestutz 
Can you suggest an appropriate definition for the new term 'mRNA alternative polyadenylation'?

I'm trying to understand if we need a new term for 'mRNA alternative polyadenylation' or whether the gene products in this paper could instead be annotated to the existing term 'regulation of mRNA polyadenylation' (GO:1900363) with perhaps an expanded definition to indicate that regulation includes polyadenylation site selection.

**Comment by Andrestutz** [comment]
Hi,

The poly(A) tail 3'-end addition on almost all protein encoding nuclear mRNA is
the result of an RNA processing reaction, where a multiprotein complex
assembles on specific sequences on the pre-mRNAs, called the cleavage and
polyadenylation signals (pA signals). The core pA signals consist of sequences
that flank either side of where the pre-mRNA is endonucleolytically cleaved and
subsequently polyadenylated (see a review in PubMed:28453393).

The CFIm complex composed of NUDT21/CPSF5, CPSF6 and CPSF7 contributes to the
recruitment of the multiprotein complex on these core pA signals and promotes
mRNA cleavage and polyadenylation. Most pre-mRNAs contain multiple pA signals,
resulting in alternative cleavage and polyadenylation (APA) producing mRNAs
with variable 3'-end length formation. The CFIm complex has the particularity
to act as a key regulator of cleavage and polyadenylation site choice during
APA through its binding to 5'-UGUA-3' elements localized in the 3'-untranslated
region (UTR) for a huge number of pre-mRNAs.

I recommend to create a new GO term.

Definition: mRNA alternative polyadenylation
The process of generating multiple mRNA molecules with variable 3'-end length
formation from a given pre-mRNA by differential use of cleavage and
polyadenylation signals (pA signals).

Reviewed in PubMed:28453393.

Have a nice day

Andre stutz

**Comment by vanaukenk** [comment]
Thank you @Andrestutz 
I will add the new term as an is_a child of 'regulation of mRNA polyadenylation' with the definitions and references you suggest above.

**Comment by sylvainpoux** [comment]
Hi,
@vanaukenk 
@Andrestutz 

I noticed that the GO:0110104 mRNA alternative polyadenylation is still not available. 

In the same occasion, would it be possible to have the child term 'Regulation of mRNA alternative polyadenylation'?

I have articles that describe proteins that directly regulate the process

Thanks

Sylvain

**Comment by pgaudet** [comment]
@sylvainpoux 

Can you provide the references for R'egulation of mRNA alternative polyadenylation'?

(GO:0110104 mRNA alternative polyadenylation is now available)

Thanks, Pascale

**Comment by sylvainpoux** [comment]
This is a rather old story. 
Please have a look to this paper PubMed:29507755.
Thanks
Sylvain
