### ISSUE TITLE
parentage of ADP ribosylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15386]
This is a child of "protein glycosylation"
which seems wrong,  so it seems that "protein glycosylation" should be resticted further in some way?

**Comment by ValWood** [comment]
results in GPs likre
Tryptophan--tRNA ligase, cytoplasmic P23381
DNA repair protein XRCC1
being annotated to protein glycosylatin.
Seems wrong?

**Comment by pgaudet** [comment]
Indeed,  "protein ADP ribosylation" is an asserted subclass of "protein glycosylation". This does seem wrong (dates from 2012); it should be directly under "protein modification process", right ? 

Thanks, Pascale

**Comment by deustp01** [comment]
From Wikipedia:
Many different amino acid side chains have been described as ADP-ribose acceptors. **From a chemical perspective, this modification represents protein glycosylation:** the transfer of ADP-ribose occurs onto amino acid side chains with a nucleophilic oxygen, nitrogen, or sulfur, resulting in N-, O-, or S-glycosidic linkage to the ribose of the ADP-ribose[14]. Originally, acidic amino acids (glutamate and aspartate) were described as the main sites of ADP-ribosylation. However, many other ADP-ribose acceptor sites such as serine[15][16], arginine[17], cysteine[18], lysine[19], diphthamide[20], phosphoserine[21], and asparagine[22] have been identified in subsequent works.
(https://en.wikipedia.org/wiki/ADP-ribosylation)

Maybe a workaround is to distinguish glycosylation processes that incorporate an adenine as part of the glyco moiety from ones that incorporate only monosaccharides and derivatives of them.

**Comment by pgaudet** [comment]
Right - another point where biologists and chemists diverge..... :(

**Comment by ValWood** [comment]
I guess my issue is that the ADP-ribosylation and the protein glycosylation appear to occur in completely different contexts.

I don't mind  the nucleotide part so much

GDP-Man:Man1GlcNAc2-PP-Dol alpha-1,3-mannosyltransferase activity
for example

but the "ribose" instead of the "hexose" addition appears to be a strong biological partitioning (ER as part of glycosylation of cell surface proteins vs ribose as part of  nuclear event, ( as far I can see but I would need to look into this further)

**Comment by deustp01** [comment]
That's the beauty of the nucleotide part - without meaning to, it gives you exactly the differentium (?) that you need without further looking, because the ER events never incorporate one into a glyco-whatever-modified protein.

**Comment by ValWood** [comment]
Of course, got you!

**Comment by pgaudet** [comment]
Fixed by https://github.com/geneontology/go-ontology/pull/15396
