### ISSUE TITLE
GO:0046209 nitric oxide metabolic process is_a GO:0042133 neurotransmitter metabolic process

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15381]
GO:0046209 nitric oxide metabolic process is_a GO:0042133 neurotransmitter metabolic process 

I don't think it is true that nitric oxide metabolism is always neurotransmitter metabolism?
For example:

 - It is synthesized in phagolysosomes to act along with oxygen radicals in killing phagocytized microbes (inducible NOS) 
 - As a neurotransmitter (neuronal NOS)
 - Nitric oxide produced by endothelial cells causes relaxation in vascular smooth muscle, leading to blood vessel dilation (endothelial NOS).

I don't even think "signaling" would work as a parent because I guess some NO metabolism is cellular detoxification (for example in response to high intake of exogenous NO)? (Maybe would work for NO biosynthesis?)

Also the only taxon restraint is for pombe - I filtered on this annotation for a few different organisms (cerevisiae, cyanobacteria, e. coli, flowering plants - just a grab bag of organisms without nervous systems readily available in quickgo) and got 6000 annotations back - these organisms don't even have nervous systems so it looks like it is causing issues?

**Comment by pgaudet** [comment]
This is due to ChEBI roles being used to infer relations. We are planning to remove them. 

Pascale

**Comment by pgaudet** [comment]
This ticket is redundant with #14626

**Comment by cmungall** [comment]
We should remove all owl definitions that reference biological roles

**Comment by krchristie** [comment]
@ukemi - This one wasn't assigned to anyone, so I've claimed it and tagged you so you can included it in the rota list for me.

**Comment by pgaudet** [comment]
This is fixed with removal of reasoning over roles.
