### ISSUE TITLE
New GO term for L-alanyl-tRNA deacylase

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#15387]
Hello,

Would it be possible to create a new GO term for a new activity of tRNA deacylase DTD2?
Proposed GO term: L-alanyl-tRNA(Thr) deacylase activity
Definition:Hydrolysis of the removal of L-alanine from threonine residues in charged non-cognate tRNA.
PMID:29410408
Parent:GO:0002161

Thanks
Rossana

**Comment by hdrabkin** [comment]
Hydrolysis of the removal of L-alanine from threonine residues in charged non-cognate tRNA.
tweak
Catalysis of the hydrolysis of misacylated ala-tRNA(thr).

**Comment by hdrabkin** [comment]
ala-tRNA(Thr) hydrolase activity GO:0106105 (name change for consistency with others).
