### ISSUE TITLE
Change parent of diphthine-ammonia ligase activity (GO:0017178)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15398]
diphthine-ammonia ligase activity (GO:0017178)
Def: Catalysis of the reaction: ATP + diphthine + NH(4)(+) = ADP + diphthamide + H(+) + phosphate. 
Xref: EC:6.3.1.14

Currently child of:
acid-amino acid ligase activity (GO:0016881)
Def: Catalysis of the ligation of an acid to an amino acid via a carbon-nitrogen bond, with the concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate.
Xref: EC:6.3.2.-

Ought to be changed to be child of:
acid-ammonia (or amide) ligase activity (GO:0016880)
Def:  Catalysis of the ligation of an acid to ammonia (NH3) or an amide via a carbon-nitrogen bond, with the concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate. 
Xref: EC:6.3.1.-

(This is likely explained by this activity being previously under 6.3.2.- in EC:
https://enzyme.expasy.org/EC/6.3.1.14
Diphthine--ammonia ligase.
Comment: Formerly EC 6.3.2.22.)

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by ukemi** [comment]
Done here:
https://github.com/geneontology/go-ontology/pull/15436
