### ISSUE TITLE
JAK-STAT cascade

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15395]
Hi All

I was going to email you about this, but then decided that at some point it would end up here so it might as well start here.

I have discussed this with Helen and Giulia. 

1. There is a problem of calling the GO:0007259 JAK-STAT cascade process a 'pathway' or 'cascade' when it only has 2 proteins. 
2. Although some species have more than 1 JAK and more than 1 STAT, for some species the GO term group will have only 2 proteins. In addition, if the JAKs and STATs are pathway specific then in enrichment if one of these pathway is dysregulated only 2 proteins will be detected as dysregulated and this will not lead to the term being enriched.
3. In flies, JAK-STAT is one receptor (domeless) and three ligands (unpaired1-3) and FlyBase are not asking for an unpaired signaling pathway or a domeless pathway. However for flies it makes sense to classify it as pathway because it starts at the membrane and ends in the nucleus. There are no signaling intermediaries between receptor binding and transcription other than JAK-STAT. 
 
So we have 2 proposals: 
A.  rename the JAK-STAT cascade which would involve:
1.	The cascade will need to be renamed eg receptor signaling pathway via JAK-STAT (or mediated by)
2.	The parent terms will need to change from intracellular signalling pathway to receptor signaling pathway
3.	Additional annotations for JAK and STAT will need to be made to associated the term 'intracellular signalling pathway' with them.

B. Have a JAK-STAT cascade term AND receptor signaling pathway mediated by JAK-STAT (or via)
1. Advantages: means that if the JAK-STAT module stands alone and can be plugged into various scenarios. It would retain intracellular signaling.  For the pathway as a whole, we can capture regulation of the pathway at points other than JAK-STAT. 
2. Disadvantages: redundancy with labelling JAK and STAT components. But this will be happening with other signaling terms.

We await your thoughts with enthusiasm

Best

Ruth

**Comment by vanaukenk** [comment]
I think I like Proposal A, but am wondering if we need step 3.  

Are we consistently annotating gene products that act in a signaling pathway downstream of a receptor to some child of 'intracellular signal transduction'?

IIRC, we discussed the utility of representing signaling 'modules' at the workshop, but I don't recall if we decided which 'modules' should be represented and where, in the ontology.

Would it be okay/enough to have something like this (simplified for illustration):

GO:0007165 signal transduction
-GO:0007166 cell surface receptor signaling pathway
--GO:0019221 cytokine-mediated signaling pathway
--GO:new receptor signaling pathway via JAK-STAT
---GO:new cytokine-mediated signaling pathway via JAK-STAT
----GO:0035771 interleukin-4-mediated signaling pathway (could be renamed 'interleukin-4-mediated signaling via JAK-STAT)

**Comment by RLovering** [comment]
Hi Kimberly

yes I think this looks great. Although I would be wary of stating that interleukin-4-mediated signaling pathway is a child of cytokine-mediated signaling pathway via JAK-STAT without seeing the literature to confirm that IL4 signals only through JAK-STAT as it is possible is signals through other intracellular signaling pathways

Best

Ruth

**Comment by vanaukenk** [comment]
@RLovering 
Yes, I agree about the IL-4 term; it was there just to illustrate a possible organization for these kinds of terms.

**Comment by hattrill** [comment]
BTW - I like this solution very much, too!

**Comment by RLovering** [comment]
Hi Kimberly
could this revised ontology be approved now?
Are you going to put GO:0007259 JAK-STAT cascade as a child of GO:new receptor signaling pathway via JAK-STAT, or just rename GO:0007259 JAK-STAT cascade as receptor signaling pathway via JAK-STAT

Thanks

Ruth

**Comment by vanaukenk** [comment]
@RLovering 
I was actually thinking of renaming GO:0007259 JAK-STAT cascade as receptor signaling pathway via JAK-STAT.  
Will this work for existing annotations to GO:0007259?

**Comment by RLovering** [comment]
Hi 
yes this will be perfect
Ruth
