### ISSUE TITLE
synonym problem carbon catabolite repression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15400]
@kimrutherford pointed out
term name is exact synonym of another term
https://www.ebi.ac.uk/QuickGO/term/GO:0061985
https://www.ebi.ac.uk/QuickGO/term/GO:0045013

**Comment by ValWood** [comment]
@pgaudet I think you touched CCR recently?

**Comment by pgaudet** [comment]
I thought it was @ukemi
