### ISSUE TITLE
MP zinc ion export from vacuole

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15401]
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0140147

Is missing ancestor

GO:0071577  zinc ion transmembrane transport

**Comment by pgaudet** [comment]
Also merged 
into GO:0140160 zinc ion import across plasma membrane (1 EXP)
GO:0071578 zinc ion transmembrane import (13 EXP)
