### ISSUE TITLE
cold-induced thermogenesis

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#15414]
This ticket stems from #84 on the https://github.com/geneontology/helpdesk/issues/83#issuecomment-372829184.
The proposal is to create new terms for an annotation project .
The requester suggests that the terms of heat generation and homeothermy do not suffice. 

"Cold-induced thermogenesis (CIT) should be a children term of the existing term "adaptive thermogenesis". In GO, adaptive thermogenesis has only one children term "diet-induced thermogenesis". Cold-induced thermogenesis is another important type of adaptive thermogenesis, which is an endothermic thermoregulation process with a basic property of the ability to generate heat by increasing metabolism in response to cold ambient temperatures to maintain a stable core body temperature. ."

Will need to get a decent reference.

**Comment by hdrabkin** [comment]
@dsptk2017, can you please supply what you would consider a good definition AND reference your your required term. Thanks.

**Comment by hdrabkin** [comment]
"The process of heat production in an organism in response to cold or low temperature"
? 
The process by which exposure to low ambient temperatures, mammals increase oxidative metabolism for the production of heat. PMID: 28988821

**Comment by dsptk2017** [comment]
@hdrabkin  I think this definition is better . "an endothermic thermoregulation process with a basic property of the ability to generate heat by increasing metabolism in response to cold ambient temperatures to maintain a stable core body temperature." (PMID: 27876809 ).

**Comment by hdrabkin** [comment]
@dsptk2017 
Tweaked a bit to be consistent with other terms
"The process by which heat is generated by increasing metabolism in response to cold ambient temperatures to maintain a stable core body temperature." 
PMID: 27876809 
is_a adaptive thermogenesis

It also occurs to me: is this process limited to mammals?

**Comment by hdrabkin** [comment]
synonyms
CIT

**Comment by dsptk2017** [comment]
@hdrabkin  Yes.  CIT is its synonym. Is adaptive thermogenesis is limited to mammals?

**Comment by hdrabkin** [comment]
do you mean yes it is limited to mammals (I ask because I may want to put in some taxa restrictions (ie, only in mammals). 
GO:0106106
is_a adaptive thermogenesis
 also 
is_a temperature homeostasis

**Comment by hdrabkin** [comment]
term added; closed

**Comment by dsptk2017** [comment]
I mean yes. CIT is its synonym. I not sure whether it is limited to mammals. If its parent term "adaptive thermogenesis" is limited to mammals, CIT should also be limited to mammals.

**Comment by hdrabkin** [comment]
Ok, I'll leave like it is for now
So you can now annotate to GO:0106106; You may want to contact GOA about uploading/adding your annotations.

**Comment by deustp01** [comment]
This is a deeply naive question, but thermogenesis sounds like it should be restricted by definition to warm-blooded animals, so mammals and birds?

**Comment by dsptk2017** [comment]
I am not sure. I just know birds have thermogenesis.

**Comment by dsptk2017** [comment]
Ok. I will contact GOA. Thank you very much.
