### ISSUE TITLE
Missing relationship between 'dendrite arborization' and 'neuron projection arborization'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#15412]
@paolaroncaglia pointed out that 'dendrite arborization' does not appear to be a child of 'neuron projection arborization' in GO.

<img width="514" alt="screen shot 2018-03-14 at 13 09 53" src="https://user-images.githubusercontent.com/16541096/37405789-7d77f5e4-278d-11e8-8167-ec519039616d.png">

To do: add the missing is_a relationship.

cc @RLovering @ukemi

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia @ukemi @pgaudet @vanaukenk 

I made a simple edit yesterday (I manually added a relationship after @paolaroncaglia pointed out it was missing), and Travis checks passed (https://github.com/geneontology/go-ontology/pull/15413). 

So I could just merge it, but now I wonder whether this relationship ('dendrite arborization' is_a 'neuron projection arborization') should actually have been inferred? Because a 'dendrite' is_a 'neuron projection'... So it seems to me that this should have been inferred? Unless the fact that 'dendrite' is also a part_of 'dendritic tree' which itself is_a 'neuron projection' too (screenshot below) causes some logical inconsistencies, hence the lack of inference?

![screen shot 2018-03-15 at 11 35 39](https://user-images.githubusercontent.com/16541096/37461030-0890234c-2845-11e8-8dc9-826a94656ee2.png)

And I also wonder whether 'dendrite arborization' should be renamed as 'dendritic tree arborization' (based on the CC ontology, a 'dendrite' is a branch of (part_of) the 'dendritic tree', so a 'dendrite' cannot grow branches/arborize, but a 'dendritic tree' can). 'Dendrite arborization' should probably still be kept as a broad synonym due to naming inconsistencies in literature.

Could you please advise?

(This is related to https://github.com/geneontology/go-ontology/issues/15417)

cc @RLovering

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub 
Please see https://github.com/geneontology/go-ontology/issues/15417 
If dendrite is_a neuron projection, then the arborization terms should automatically be stated by the reasoner, not sure why this isn't happening but I can't dig deeper at the moment, sorry.
I'm not sure about the renaming instead. I guess the tree originates from a dendrite anyway? But I understand your concern. @ukemi @dosumis could you advice please as I'll be away and won't have a chance to look at this in Protege for a few days. Barbara is trying to fix this for a poster that she's presenting on Tuesday. Many thanks!

**Comment by dosumis** [comment]
Inference would require an EquivalentClass definition on 'neuron projection arborization'.  As there isn't one right now and adding one would not be trivial (you'd probably need to use a term from PATO as the differentium), adding by hand (as you've done) is the best way to do this.

**Comment by BarbaraCzub** [comment]
Thanks @dosumis
