### ISSUE TITLE
angiotensin term definitions need improving

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15424]
Following from https://github.com/geneontology/go-ontology/issues/15410#issuecomment-373291191 

GO:0002002 regulation of angiotensin levels in blood
previous Definition (GO:0002002 GONUTS page)
The process that modulates the level of angiotensin in the blood by balancing the maturation of renin substrate to mature angiotensin and the catabolism of mature angiotensin.

recently Definition revised to: "The process that modulates the level of angiotensin in the blood by balancing the maturation angiotensinogen to angiotensin and the catabolism of mature angiotensin. Angiotensinogen is processed by the renin protease."

Please change this again, as there are many enzymes involved in this process ( https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3214724/ figure 1 ), not just renin, to:
"The proteolytic cleavage of angiotensinogen leads to the production of a variety of angiotensin isoforms. The process that modulates the level of a variety of angiotensin isoforms in the blood by the proteolytic cleavage of angiotensinogen and angiotensin isoforms to create the active peptide hormone angiotensin isoforms; modulation is also achieved through the removal of these isoforms from the circulation."

Were there any other term definitions that were modified to remove 'renin substrate'? It seems to me that there are still lots of definitions that need revisions to recognise that renin is not the only enzyme involved and 'renin substrate' in the term is not appropriate as renin may digest other proteins than angiotensinogen

If you can provide a list of the terms that are being kept and their definitions I can try to workout how to revise these, unless you are happy with the suggestion above and can use this as a 'template'?

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 
I fixed the definition as requested. The term 'renin substrate' is not anywhere in the ontology anymore. 

'Renin' is in the definition of a number of terms that also have 'renin' in the label - so that seems correct: (except the first one I am not sure about): 

'angiotensin-mediated vasodilation involved in regulation of systemic arterial blood pressure' GO_0002033
'regulation of systemic arterial blood pressure by renin-angiotensin' GO_0003081
'regulation of blood volume by renin-angiotensin' GO_0002016
'negative regulation of renin secretion into blood stream' GO_1900134
'regulation of blood vessel diameter by renin-angiotensin' GO_0002034

'regulation of systemic arterial blood pressure by circulatory renin-angiotensin' GO_0001991
'regulation of systemic arterial blood pressure by local renal renin-angiotensin' GO_0003086

'renin secretion into blood stream' GO_0002001
'regulation of renin secretion into blood stream' GO_1900133
'positive regulation of renin secretion into blood stream' GO_1900135

Thanks, Pascale

**Comment by pgaudet** [comment]
@RLovering 
Sorry I just looked more closely - if you start the definition with "The proteolytic cleavage of angiotensinogen leads to the production of a variety of angiotensin isoforms" then how is that different from 'angiotensin maturation'? 

How about: "The process that modulates the level of a variety of angiotensin isoforms in the blood. This occurs by the proteolytic cleavage of angiotensinogen and angiotensin isoforms to create the active peptide hormone angiotensin isoforms, as well as through the removal of these isoforms from the circulation."

Thanks, Pascale

**Comment by RLovering** [comment]
brilliant
thanks

**Comment by pgaudet** [comment]
Hi @RLovering 
Re-reading this - what do you mean by 'isoform'? In GO I think we use 'isoforms' to mean a different splicing product (like UniProt) - here I think you mean is different cleavage product, right ? If that's the case the we could have this definition: 

"The process that modulates the level of any of the various angiotensinogen proteolytic products in the blood. This occurs by the proteolytic cleavage of angiotensinogen to create the active peptide hormones angiotensin I and angiotensin II, as well as through the removal of these peptides from the circulation."

Would that be OK ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
the problem with this statement is there are more hormones created by cleavage than the ones you mention. See the figure I keep pointing you to. 4 are listed in wikipedia.

And yes you are right these are cleavage products.

How about: "The process that modulates the level of any of the various angiotensinogen proteolytic products in the blood. This occurs by the proteolytic cleavage of angiotensinogen, and its proteolytic products, to create a variety of active peptide hormones, such as angiotensin I and angiotensin II, as well as through the removal of these peptides from the circulation."

I have modified the definition among other things I have added ', and its proteolytic products and ,' because I think only angiotensin I is created by the cleavage of angiotensinogen, for example  angiotensin II is created by the cleavage of  angiotensin I 

Please don't keep pushing these decisions within hours, I have a lot of other commitments in my working life and it is very stressful feeling like I have to reply to you within 1 hour or even 1 day. FYI I am at a 2 day ARUK meeting Tuesday and Wednesday and I am on holiday from  this Sunday till after easter.

Best

Ruth

**Comment by pgaudet** [comment]
Excellent !! I'm now committing, pushing, merging and closing ;) 

Pascale
