### ISSUE TITLE
replaced_by:obsolete term id situations

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#15429]
Our OBO parsing scripts have been failing on loading because some obsolete terms have replaced_by terms that are themselves obsolete or were merged into other terms.  Upon closer examination, there are only a few but they are doozies.

(1) GO:0022815 replaced by GO:0022891 which was itself replaced by GO:0022857
(2) GO:0003733 replaced by GO:0030529 which was merged into GO:1990904
(3) GO:0030531 replaced by GO:0030529 which was merged into GO:1990904
(4) GO:0030356 replaced by GO:0030531 which was replaced by GO:0030529 which was merged into GO:1990904

I suggest that the replaced by fields be updated as follows:

(1) GO:0022815 replaced by GO:0022857
(2) GO:0003733 replaced by GO:1990904
(3) GO:0030531 replaced by GO:1990904
(4) GO:0030356 replaced by GO:1990904

Any objections?  How can we prevent this from happening in the future?  Is this a problem that others have also encountered in their GO loading pipelines?

**Comment by cmungall** [comment]
@dougli1sqrd will implement a check to prevent this happening moving forward.

I'll repair these in place for now

**Comment by tberardini** [comment]
Thank you, Chris!

**Comment by dougli1sqrd** [comment]
I made a sparql query that finds a couple more. Let's make sure that this isn't being to aggresive:
```
?class	?replacement
<http://purl.obolibrary.org/obo/GO_0008581>	<http://purl.obolibrary.org/obo/GO_0004221>
<http://purl.obolibrary.org/obo/GO_0008436>	<http://purl.obolibrary.org/obo/GO_0030530>
<http://purl.obolibrary.org/obo/GO_0030356>	<http://purl.obolibrary.org/obo/GO_0030531>
<http://purl.obolibrary.org/obo/GO_0003733>	<http://purl.obolibrary.org/obo/GO_0030529>
<http://purl.obolibrary.org/obo/GO_0022815>	<http://purl.obolibrary.org/obo/GO_0022891>
<http://purl.obolibrary.org/obo/GO_0030531>	<http://purl.obolibrary.org/obo/GO_0030529>
```

The sparql for this was: 
```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX IAO: <http://purl.obolibrary.org/obo/IAO_>

SELECT ?class ?replacement
WHERE {
  ?class IAO:0100001 ?repl .
  BIND(IF(isLITERAL(?repl), URI(CONCAT("http://purl.obolibrary.org/obo/", STRBEFORE(?repl, ":"), "_", STRAFTER(?repl, ":"))), ?repl) as ?replacement )
  ?replacement owl:deprecated true .

  FILTER NOT EXISTS {
    ?class IAO:0000231 IAO:0000227 .
  }
}
```

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/15506

**Comment by ukemi** [comment]
Looks like @dougli1sqrd check also found some that had consider tags in the obsolete replaced_by term. Do you want to add these to the transitive closure, or should I fix them by hand?

**Comment by tberardini** [comment]
@dougli1sqrd 
> ?class
	?replacement
<http://purl.obolibrary.org/obo/GO_0008581>	<http://purl.obolibrary.org/obo/GO_0004221>
<http://purl.obolibrary.org/obo/GO_0008436>	<http://purl.obolibrary.org/obo/GO_0030530>

These are correctly identified and not the query being overly aggressive.  Are we going to fix the problems by hand, as @ukemi  suggests, or will a script take care of the cleanup?  Thanks.

**Comment by pgaudet** [comment]
* http://purl.obolibrary.org/obo/GO_0008581 (obsolete ubiquitin-specific protease 5 activity) http://purl.obolibrary.org/obo/GO_0004221 (obsolete ubiquitin thiolesterase activity)
replace by: GO:0004843 thiol-dependent ubiquitin-specific protease activity
* GO:0008577 can also be replaced by GO:0004843 if needed
* http://purl.obolibrary.org/obo/GO_0008436	(obsolete heterogeneous nuclear ribonucleoprotein) 
replace by GO:1990904 ribonucleoprotein complex

**Comment by pgaudet** [comment]
Hi @dougli1sqrd 
Are you also checking that the 'consider' terms are not obsolete (or alt_ids?) 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
No, the check just looks at 'replaced by' to detect when we have a chain of obsoletes.

**Comment by pgaudet** [comment]
I think the 'consider' terms should also be valid. @dougli1sqrd do you want to implement a new check for this ? 

Thanks, 
Pascale
