### ISSUE TITLE
What's happened to GO:0043234 (protein complex)?

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-ontology#15421]
I've just discovered that GO:0043234 (protein complex) no longer exists as a term in its own right, but has been made secondary to GO:0032991, which itself has been renamed from macromolecular complex to protein-containing complex.

The problem that I have is that GO:0043234 is used in the following files to categorise the types of entities that various databases mint identifiers for, and to specify what kinds of with/from are valid with different evidence codes:

https://github.com/geneontology/go-site/blob/master/metadata/eco-usage-constraints.yaml
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml
http://purl.obolibrary.org/obo/go/snapshot/extensions/go-upper.obo

The disappearance of GO:0043234 means that a lot of validations of with/from are now failing when they shouldn't.

Is it valid to replace all occurrences of GO:0043234 with GO:0032991, and, if so, can somebody do it ASAP, please?

**Comment by pgaudet** [comment]
Hi @tonysawfordebi 
The decision to merge 'protein complex' into 'macromoelecular complex' was made here #12782 
The reason was that it was too difficult to maintain the children of GO:0043234 (most were under GO:0032991 directly). 

I suppose that does mean changing the checks since all these now allow both protein and RNA. 
Pascale

**Comment by tonysawfordebi** [comment]
I've edited the three files to either remove references to GO:0043234 (go-upper.obo) or change them to GO:0032991 (db-xrefs.yaml & eco-usage-constraints.yaml).

It would be good if somebody could give eco-usage-constraints a scan, to make sure that changing from protein complex to protein-containing complex hasn't opened the net too wide for any of the affected rules.

**Comment by pgaudet** [comment]
@tonysawfordebi I'm happy to have a look. Where are the eco-usage-constraints ?

**Comment by tonysawfordebi** [comment]
@pgaudet: https://github.com/geneontology/go-site/blob/master/metadata/eco-usage-constraints.yaml

**Comment by pgaudet** [comment]
I dont think 
- IGI 
- ISO
- ISS
-IEA
- HGI
- HMP
should allow protein_complex

Were these valid before ? Do we have examples ? 
@vanaukenk what do you think ?

**Comment by tonysawfordebi** [comment]
I haven't changed any of the rules (*); they're what were originally agreed as part of an effort spearheaded by (I think) Rachael three or four years ago.

(*) not strictly true: I added in the HMP rule as a copy/paste of the IMP one when the HTP evidence codes were introduced at the back end of last year.

**Comment by vanaukenk** [comment]
@tonysawfordebi 
Would it be possible to get a breakdown of the number of times, per evidence code, a protein complex ID has been used in the With/From field in Protein2GO?
I was looking to see if this query was an option on the Protein2GO reports page, but didn't see it.  Let me know if I'm missing it, though.
Thx.

**Comment by tonysawfordebi** [comment]
@vanaukenk 
There aren't *that* many annotations that refer to a protein complex (or, to be precise, an IntAct complex ID) in their with/from.

There are 242 in total, and the breakdown by evidence code is:

- IGI 171
- IPI 	56
- ISS 15

You can see them in QuickGO by going to https://www.ebi.ac.uk/QuickGO/annotations?withFrom=IntAct

**Comment by vanaukenk** [comment]
Great; thank you @tonysawfordebi !

**Comment by bmeldal** [comment]
A quick scan of the list in QuickGO rings alarm bells: Why would you have processes with a complex AC in the with/from field???

Another issue: all the links open in IntAct but need to point to the CP. Will that be fixed when you upload our new file and add the separate source "complexportal"?

**Comment by bmeldal** [comment]
Oh, and somewhere we need to let the community know that GO:0043234 (protein complex) no longer exists! Can we send a message to go-friends? And tweet it? I feel it should come from the GO editor rather than myself for authority. And a tweet from the GO account which I have no access too (I will retweet!!!).

**Comment by tonysawfordebi** [comment]
@bmeldal 
The "misguided links" thing is a known issue, caused by the fact that there are two URLs specified in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml for IntAct - one for interactions, and one for complexes - and, at the moment we are picking up the wrong one. As you surmise, this will all correct itself when we make the switch to using CP CPX-nnn identifiers for complexes.

**Comment by tonysawfordebi** [comment]
How long does it normally take for edits to propagate through the system?
I edited the IntAct entry in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml last Thursday, but the derived JSON file (https://s3.amazonaws.com/go-public/metadata/db-xrefs.json) has not yet caught up.

**Comment by pgaudet** [comment]
@bmeldal Can we review these annotations together ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
Yes, can do, @pgaudet Do you want to skype? Maybe email me off-ticket for logistics ;-)

**Comment by pgaudet** [comment]
After discussion with @bmeldal 


**ALLOWED**
Entity | GO term | ECO | entity 'with' 
-- | -- | -- | --
GP | protein-containing complex binding | IPI | Protein complex
Protein complex | MF or BP | ISS | Protein complex


**NOT ALLOWED**
Entity | GO term | ECO | entity 'with' 
-- | -- | -- | --
GP or protein complex | any GO term | IGI | Protein complex

**TO BE DISCUSSED**
Entity | GO term | ECO | entity 'with' 
-- | -- | -- | --
GP or protein complex | any GO term | ISS | Protein complex
Protein complex | Part_of CC:protein-containing complex | ISS | Protein complex

**Comment by bmeldal** [comment]
We'll discuss this on the next Complex WG call. I still have to send an email to arrange a date.

**Comment by tonysawfordebi** [comment]
OK - I'm not going to make any modifications to eco-usage-constraints.yaml until I know the full extent of the proposed changes.

**Comment by pgaudet** [comment]
Other possible rules:
* If we have a Protein Complex in Col 2, it should NOT be annotated to Protein Complex (this is effectively a cross-reference between Intact and GO-CC-complex

**Comment by pgaudet** [comment]
@vanaukenk : Complexes can go in the 'with' columns for the above evidence codes. 

As far as I can tell there is no change needed. @tonysawfordebi please close this if its ok. 

Thanks, Pascale

**Comment by bmeldal** [comment]
update following call

**Comment by tonysawfordebi** [comment]
@bmeldal Constraint now implemented.

**Comment by bmeldal** [comment]
That was quick. 
@RLovering @NancyCampbell @BarbaraCzub @rachhuntley let me know if you have trouble using CP ACs in the right way.

**Comment by BarbaraCzub** [comment]
Hi @bmeldal, the CP ACs work well in P2GO, but not in QuickGO. (QuickGO still displays IntAct ACs).

**Comment by bmeldal** [comment]
Yes, Tony told me there's a fix imminent.

I was referring to running into trouble using CP ACs in P2GO since Tony added the new rule today.

**Comment by BarbaraCzub** [comment]
Tested. The rule appears to work:
<img width="995" alt="screen shot 2018-04-25 at 15 03 35" src="https://user-images.githubusercontent.com/16541096/39250893-e33beab6-4899-11e8-8288-b2417be07e9a.png">

**Comment by bmeldal** [comment]
There will always be erroneous annotations in there as we will find it difficult to filter these out of our gpad as we need them in our DB as xrefs on the CP website...
Just a warning as you may see those but they should have source DB=complexportal

But good to see people can see when they try to create them.

**Comment by pgaudet** [comment]
@tonysawfordebi @bmeldal 
Can this be closed ? 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
Yep, think so.

**Comment by bmeldal** [comment]
I had left it open as the rules need to be added to the Wiki somewhere but that's now also an AI from the NYC meeting.
@vanaukenk
