### ISSUE TITLE
Check for exact synonym and term name match

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15435]
We should not allow term names (labels) to match exact synonyms of other terms. This needs to be added to the Travis checks.

**Comment by dougli1sqrd** [comment]
Can you give an example?

**Comment by cmungall** [comment]
```
SELECT ?c1 ?n ?c2 WHERE {?c1 <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?n . ?c2 <http://www.w3.org/2000/01/rdf-schema#label> ?n . FILTER (?c1 != ?c2)}
```

**Comment by pgaudet** [comment]
@dougli1sqrd I think this can be closed ? 
https://github.com/geneontology/go-ontology/pull/15504

**Comment by dougli1sqrd** [comment]
yep! Thanks for keeping up on it :)
