### ISSUE TITLE
merge GO:0102005 with GO:0043333?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15433]
@drabkin, it looks like these might be the same enzyme, just named slightly differently. Can you check the details and merge if appropritate.

**Comment by hdrabkin** [comment]
Thought it might have been from the Peifen set 0102005, (based on high id range), but it appears not. Will need to investiage.

**Comment by ukemi** [comment]
Thanks. There are lots of enzymes where there is an exact synonym from EC that matches another term name. But in almost all cases, they aren't exactly the same.

**Comment by hdrabkin** [comment]
Yes, I saw this a lot with the plant stuff.

**Comment by ukemi** [comment]
Once I clean it up, I will open a ticket for a check, so this won't happen.

**Comment by hdrabkin** [comment]
I fear many of Peifens will fall into these, as for expediency, I just checked for duplicate term names (which aren't allowed). 8-(.

**Comment by hdrabkin** [comment]
Digging around in the annotations
GO:0043333 has one annotation for Ecoli ; this protein is listed on the EC entry page (EC 2.1.1.201, which is listed as the xref for GO:0102005!
GO:0102005 has 15, mostly IEA;  one experiment to human; that UniProt id for that protein is not listed on the EC entry page; however, the record for the human protein at UniProt lists the EC number. 
Based on this, I'm thinking of a merge

**Comment by pgaudet** [comment]
Done here #15686
