### ISSUE TITLE
new GO term request

### ISSUE THREAD

**Issue by ebakker2** [geneontology/go-ontology#15437]
Could you add a GO term for:  indole-3-butyric acid conjugation?

thanks,
Erica

**Comment by ukemi** [comment]
Can you provide a few more details?
https://github.com/geneontology/go-ontology/blob/master/CONTRIBUTING.md

**Comment by vanaukenk** [comment]
@ebakker2 

Could you please provide additional details for us to create this term in the ontology, most importantly:

- Suggested parentage
- Suggested definition
- Appropriate paper(s) for references

Thank you.

**Comment by tberardini** [comment]
@vanaukenk and @ukemi : @ebakker2 is a new part-time curator for TAIR.  She's learning the ropes and I should have given her a pointer to the https://github.com/geneontology/go-ontology/blob/master/CONTRIBUTING.md file when I recommended requesting a new term through github.  I thought it showed up when one clicked on 'New Issue' but it doesn't.

**Comment by ebakker2** [comment]
I will take a look and add the requested information.

thanks,
Erica

**Comment by EricaBakker** [comment]
Is this ok? This is my first submission. thanks!

Term: indole-3-butyric acid conjugate metabolic process
Definition: The chemical reactions and pathways involving indole-3-butyric acid (IBA) conjugates, a bound form of IBA.
Parents: GO:0010249 auxin conjugate metabolic process
Papers: https://doi.org/10.1074/jbc.RA118.002006

**Comment by tberardini** [comment]
Did this get added?  Thanks for checking.

**Comment by 123seher** [comment]
Eliminate this theart

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pgaudet** [comment]
Yes ! sorry about the long delay in the reply. 

GO:0033473
