### ISSUE TITLE
Term names that are also exact synonyms

### ISSUE THREAD

**Issue by kimrutherford** [geneontology/go-ontology#15431]
As a follow up to #15400 I queried the PomBase Chado database for GO term names that are also exact synonyms.  The GO terms in the database come from go-basic.obo from March 13th.

Here's the list.  Hope it helps.

|                             name                              |  term_id   | syn_term_id 
|---------------------------------------------------------------|------------|-------------
|    cellular response to environmental stimulus                | GO:0104004 | GO:0071496
|    negative regulation of mitophagy                           | GO:1901525 | GO:1903147
|    microtubule-based protein transport                        | GO:0099118 | GO:0098840
|    carbon catabolite repression                               | GO:0061985 | GO:0045013
|    establishment of ER localization                           | GO:0051686 | GO:0099089
|    regulation of viral life cycle                             | GO:1903900 | GO:0050792
|    methylcrotonoyl-CoA carboxylase complex                    | GO:1905202 | GO:0002169
|    perisynaptic extracellular matrix                          | GO:0098966 | GO:0099535
|    peptidase inhibitor complex                                | GO:1904090 | GO:0097179
|    nitrite reductase activity                                 | GO:0098809 | GO:0050421
|    DMNT synthase activity                                     | GO:0102171 | GO:0097008
|    trehalose synthase activity                                | GO:0102986 | GO:0047471
|    2-octaprenyl-6-methoxy-1,4-benzoquinone methylase activity | GO:0102005 | GO:0043333
|    dehydroquinate synthase activity                           | GO:0102042 | GO:0003856
|    chalcone synthase activity                                 | GO:0102128 | GO:0016210
|    limonene hydroxylase activity                              | GO:0102133 | GO:0018676
|    pterin-4alpha-carbinolamine dehydratase activity           | GO:0102434 | GO:0008124
|    5-epi-aristolochene synthase activity                      | GO:0102698 | GO:0045483
|    tartronate semialdehyde reductase activity                 | GO:0103032 | GO:0008679
|    N-acetyl-beta-D-galactosaminidase activity                 | GO:0102148 | GO:0032428
|    murein hydrolase activity                                  | GO:0103028 | GO:0008745
|    glutarate semialdehyde dehydrogenase activity              | GO:0102810 | GO:0047949
|    dTDP-L-rhamnose synthetase activity                        | GO:0102030 | GO:0008830

("carbon catabolite repression" was fixed in #15400)

**Comment by ukemi** [comment]
It looks like a lot of these are coming in as exact synonyms from EC, but they are not exact because they either refer to different EC numbers or other different cross refs. I'm cleaning them up.
