### ISSUE TITLE
Relabel GO:0022605 "Mammalian oogenesis stage"

### ISSUE THREAD

**Issue by thomaspd** [geneontology/go-ontology#15441]
The child terms are specific to mammals, and all experimental annotations are to mammalian gene products.

**Comment by cmungall** [comment]
lots of non-mammal experimental annots:

http://amigo.geneontology.org/amigo/term/GO:0048477

![image](https://user-images.githubusercontent.com/50745/37549311-e0bab5b0-293b-11e8-80aa-d8c8817f4875.png)

**Comment by thomaspd** [comment]
That link is to the wrong GO term.  Try GO:0022605 instead.

**Comment by cmungall** [comment]
oh right yes I see. I agree, needs renamed.

additional notes:

It looks like we have 3 experimental direct annotations onto stages - I think stages should not be annotated directly? We have that rule for cell cycle stages.

There is an argument for moving all anatomical structure specific stages out of GO. We already manage whole-organism life cycle stages in separate ontologies.

**Comment by ukemi** [comment]
We can rename it as long as we don't think we will never add other children that aren't mammalian. Although these are named stages, according to what biologists call them, I think they actually refer to processes that make up oogenesis. So in this case, oogenesis stage is actually oogenesis part, but no one would ever search on that.
