### ISSUE TITLE
response to cytokine/hormone

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15448]
should response to cytokine be part_of signaling? (cell-cell signaling?)

**Comment by Antonialock** [comment]
same with "response to hormone"

**Comment by deustp01** [comment]
Maybe not, for both, because those responses include things like transcriptional activation / repression, cytoskeletal rearrangements and changes in cell motility, and the like, which are beyond the boundaries of a signaling process. @ukemi, as boundary expert?

**Comment by ValWood** [comment]
I agree, the signalling is one of the responses. This is a reason why we don't use them for direct annotation at PomBase (@Antonialock  you should leave "response to" terms out of the slim.
There isn't enough info about the process for what we are trying to do.)

**Comment by ukemi** [comment]
I agree with @deustp01. The response can me much more than just the signaling.
