### ISSUE TITLE
dUMP kinase activity

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15447]
I would like to see "dUMP kinase activity”, added to the GO ontology under the parent term "uridylate kinase activity” (GO:0009041).  The definition could be "Catalysis of the reaction: ATP + dUMP = ADP + dUDP”.  Example can be found in PMID: 3010881.

**Comment by pgaudet** [comment]
I don't think 'dUMP kinase activity' is a type of 'uridylate kinase activity' - it should probably be a GO:0019201 nucleotide kinase activity. 

Pascale

**Comment by deustp01** [comment]
But "2'-deoxyuridine 3'-monophosphate (CHEBI:46322) is a deoxyuridine phosphate (CHEBI:23641)" (ChEBI) and "Deoxyuridine monophosphate (dUMP), also known as deoxyuridylic acid or deoxyuridylate in its conjugate acid and conjugate base forms" (Wikipedia)

**Comment by slaulederkind** [comment]
If "UMP kinase activity" (GO:0033862) is a child of "uridylate kinase activity" (GO:0009041, and the definition of "uridylate kinase activity" is "Catalysis of the reaction: ATP + (d)UMP = ADP + (d)UDP", why would "dUMP kinase activity" not be a child also?  That equation is really two equations with two alternate substrates (dUMP and UMP) and products (dUDP and UDP).  There are two separate enzyme activities implied in that equation: "UMP kinase activity"  and "dUMP kinase activity"

**Comment by pgaudet** [comment]
@slaulederkind OK - I missed that, thanks.

Pascale

**Comment by krchristie** [comment]
@slaulederkind - added term as you requested. 

Also added EXACT synonyms parallel to those of the existing EXACT synonyms of the existing "UMP kinase activity" term, but changing "UMP" to "dUMP" or "uridine" to "deoxyuridine". If you think any of these are inappropriate, let me know and I'll remove them.
