### ISSUE TITLE
GO:0006577 amino-acid betaine metabolic process

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15449]
Should GO:0006577 amino-acid betaine metabolic process
have the parent GO:0006575 cellular modified amino acid metabolic process
(carnitine is a dipeptide)

@ValWood

**Comment by ukemi** [comment]
Please check ChEBI.. These relations in GO are all derived from their structure.

**Comment by Antonialock** [comment]
I don't know how to check it.

**Comment by ukemi** [comment]
https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:22860&treeView=true#vizualisation

It looks like 'amino-acid betaine (CHEBI:22860)is not a child of 'amino acid derivative' (ChEBI:83821). If we want to get the relationship in GO, we should request it at ChEBI. This is true for any request that refers to the inherent chemical hierarchy in GO. We automatically generate them from the ChEBI ontology.

**Comment by Antonialock** [comment]
ok cheers, I emailed their helpdesk

**Comment by ValWood** [comment]
@Antonialock   there is a tracker here
https://github.com/ebi-chebi/ChEBI/issues
then you can link to this issue

**Comment by Antonialock** [comment]
They replied and said they've added it, so I guess it will filter through in time :)

**Comment by ValWood** [comment]
wow that's much quicker than using the tracker :)
