### ISSUE TITLE
Connect acetolactate synthase GO:0003984 to valine biosynthesis GO0009099

### ISSUE THREAD

**Issue by danolson1** [geneontology/go-ontology#15454]
I'm trying to find genes associated with valine production. I started with term GO:0003984, which identifies acetolactate synthase, which is one of the early steps in this pathway. It doesn't look like this term is connected to valine biosynthesis GO:0009099. I would expect that GO:0003984 would be a child of GO:0009099.

Thanks,
Dan

**Comment by hdrabkin** [comment]
I'll make a has_part GO:0003984 to GO:0009099
But then should I also add while I'm at it
ketol-acid reductoisomerase activity
dihydroxy-acid dehydratase activity
L-valine transaminase activity

The last two activities also involved in other pathways, hence the has_part is a better choice
Taking info on the other steps from 
https://biocyc.org/META/new-image?object=VALSYN-PWY

**Comment by danolson1** [comment]
Thanks. When do you think the change will show up in the change log? https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003984

**Comment by hdrabkin** [comment]
@ukemi can you look at what I plan to do with this?

**Comment by ukemi** [comment]
Hi @hdrabkin,  This makes sense, but it won't show up in annotations. So to get the entire list of genes, either they will have to be annotated to valine biosynthetic process or a search will need to be done on all the enzyme activities that are necessary parts.

**Comment by hdrabkin** [comment]
Yes, I'm assuming @danolson will want to do this

**Comment by danolson1** [comment]
Is there something you need be to do? I don't understand @hdrabkin 's last comment. (also, FYI, @DanOlson is not me, despite the similar name).

**Comment by hdrabkin** [comment]
No; this is going in as we speak. I assumed you would want to get back genes annotated to the various genes involved in the pathway; so they would need annotations first. However, if you are just 'browsing the ontology', everything is good.

**Comment by hdrabkin** [comment]
done; (and changed your id in my comment; sorry). 
CLosing

**Comment by danolson1** [comment]
@hdrabkin or @ukemi, can you send me a link to show me where the changes were made? On the 0009099 page (https://www.ebi.ac.uk/QuickGO/term/GO:0009099), the last update was 2016-11-28. On the 0003984 page (https://www.ebi.ac.uk/QuickGO/term/GO:0003984), the last update was 2015-04-24.

Thanks,
Dan

**Comment by hdrabkin** [comment]
You can see it in the ontology file which can be found here
http://purl.obolibrary.org/obo/go.obo (3-31-18 version)

[Term]
id: GO:0009099
name: valine biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of valine, 2-amino-3-methylbutanoic acid." [GOC:ai]
subset: gosubset_prok
synonym: "valine anabolism" EXACT []
synonym: "valine biosynthesis" EXACT []
synonym: "valine formation" EXACT []
synonym: "valine synthesis" EXACT []
xref: MetaCyc:VALSYN-PWY
is_a: GO:0006573 ! valine metabolic process
is_a: GO:0009082 ! branched-chain amino acid biosynthetic process
is_a: GO:1901607 ! alpha-amino acid biosynthetic process
relationship: has_part GO:0003984 ! acetolactate synthase activity
relationship: has_part GO:0004160 ! dihydroxy-acid dehydratase activity
relationship: has_part GO:0004455 ! ketol-acid reductoisomerase activity
relationship: has_part GO:0052655 ! L-valine transaminase activity
