### ISSUE TITLE
GO:0043647 - inositol phosphate metabolic process  parentage

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15450]
should
GO:0043647 - inositol phosphate metabolic process 

be part_of
GO:0006020 - inositol metabolic process

(apologies if this is one for chebi, just let me know if I should send the question to them)

**Comment by pgaudet** [comment]
I dont think so : if a protein metabolises inositol phosphate, it does not necessarily metabolize inositol; right ? 

Pascale

**Comment by deustp01** [comment]
But ChEBI may be lurking here. Inositol phosphate (CHEBI:24846) is_a cyclitol phosphate (CHEBI:23450) is_a cyclitol (CHEBI:23451). Not quite ubiquitol phosphate is_a ubiquitol, in which case ubiquitol phosphate metabolism is_a ubiquitol metabolism, despite the fact that many enzymes that act on ubiquitol won't ouch ubiquitol phosphate and vise versa. @ukemi ?

**Comment by ukemi** [comment]
The entire lineage of GO with respect to chemicals should reflect that of ChEBI (and be generated by ChEBI) with the exception of very few cases where we have some terms that aren't in ChEBI.

**Comment by ukemi** [comment]
I just noticed this is requesting a part_of relation. If every metabolic pathway that metabolizes inositol has as one of it's subprocesses the metabolism of inositol phosphate, this would be true. We do not generate part_of relations from the ChEBI ontology. Those come from painstakingly looking at pathways exhaustively.

**Comment by Antonialock** [comment]
ah, I guess most metabolism and biosynthesis is....but not catabolism. So I presume that is a no then.
