### ISSUE TITLE
GO:0019562 L-phenylalanine catabolic process to phosphoenolpyruvate-is it real?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15457]
While fixing the logical definition of this term, @pgaudet and I noticed that the xref link to metacyc shows a pathway that doesn't seem to fit the definition of this term. We can't find any evidence for the pathway occurring in this direction. It's possible that there was a typo in the end-product? We are not sure about this very fuzzy definition:
The chemical reactions and pathways resulting in the breakdown of L-phenylalanine into other compounds, including phosphoenolpyruvate.

PR is here #15456

Can anyone shed light on this?

**Comment by deustp01** [comment]
Poking around in KEGG and MetaCyc turned up no pathways that go from phenylalanine to phosphoenolpyruvate or to an intermediate on a pathway that leads to it. The MetaCyc pathway that is cross-referenced in the GO entry, PHENYLALANINE-DEG1-PWY, is actually a cyclic process that regenerates a cofactor consumed in the course of converting phenylalanine to tyrosine. That process is essential for phenylalanine catabolism via tyrosine, but it doesn't generate phosphoenolpyruvate or something that can be converted to it either.

So a mistake of some sort but no clue from here as to what was intended.

**Comment by pgaudet** [comment]
Note that this probably also applies to GO:0019446 tyrosine catabolic process to phosphoenolpyruvate. 

Thanks, Pascale

**Comment by deustp01** [comment]
Yes, for sure.

**Comment by ukemi** [comment]
Thanks @deustp01. 
Let's propose an obsoletion of these two. Thank goodness there are also no annotations.  I'm going to hand it over to you @pgaudet.

**Comment by ukemi** [comment]
PS. @drabkin and I also spent a couple of hours trying to find these pathways with no luck.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0019562 L-phenylalanine catabolic process to phosphoenolpyruvate and 

GO:0019446 tyrosine catabolic process to phosphoenolpyruvate. 

The reason for obsoletion is that there is no evidence that this is a real process. There are no annotations, no mappings, and no references associated with the term, and the MetaCyc cross reference describes a different pathway, PHENYLALANINE-DEG1-PWY. 

There are no annotations or mappings to this term. Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/15457


We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on March 28, 2018. Unless objections are received by March 28, 2018  we will assume that you agree to this change. 


Thanks, Pascale
