### ISSUE TITLE
NTR Golgi to cleavage furrow transport

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15469]
hello,
I'd like to request
 Golgi to cleavage furrow transport

is_a post-Golgi vesicle-mediated transport
is_a intracellular transport

standard def
PMID:25977474

**Comment by ValWood** [comment]
That seems an odd term to me....I'll take a look at the paper later...

**Comment by ValWood** [comment]
should be is_a

GO:0006893    Golgi to plasma membrane transport ?

I think I would probably use this with occurs_at "cell division site"

cleavage furrow might be problematic
https://www.ebi.ac.uk/QuickGO/term/GO:0032154

**Comment by Antonialock** [comment]
yes...I think I see your point. would be nice to have something a bit more specific than PM, but it can do.

**Comment by pgaudet** [comment]
You can also consider 'protein localization to cleavage furrow'. 

Pascale
