### ISSUE TITLE
Review representation of alternative mRNA splicing, via spliceosome

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#15473]
We need to review representation of alternative mRNA splicing, via spliceosome to clarify its relationship to mRNA splicing, via spliceosome and regulation of mRNA splicing, via spliceosome.

As part of this, we will need to review the associated sub-processes and molecular functions to ensure that we don't have redundant concepts here.

For reference:

![image](https://user-images.githubusercontent.com/1730534/37786000-f2c1ecca-2dd1-11e8-8381-6d2a4b156103.png)

![image](https://user-images.githubusercontent.com/1730534/37785920-ba47f038-2dd1-11e8-8c9c-a0586d976fc7.png)

![image](https://user-images.githubusercontent.com/1730534/37785851-91dc2c54-2dd1-11e8-8923-a3c9ac9e8f3a.png)

**Comment by krchristie** [comment]
@vanaukenk - Let me know if I can help. I put in most of these terms.

**Comment by ValWood** [comment]
closing, there is a later duplicate ticket
https://github.com/geneontology/go-ontology/issues/23362

Note that in the 2nd image "mRNA splice site selection" isn't really about selecting alternative splice sites. It's children are
GO:0000389    mRNA 3'-splice site recognition 
GO:0000395    mRNA 5'-splice site recognition

Possible this term should be renamed "mRNA splice site recognition"?
