### ISSUE TITLE
duplicate nucleotide kinase molecular function terms? 

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15471]
GO:0019201 nucleotide kinase activity "Catalysis of the reaction: ATP + nucleoside monophosphate = ADP + nucleoside diphosphate. "
and
GO:0050145 nucleoside phosphate kinase activity "Catalysis of the reaction: ATP + nucleoside phosphate = ADP + nucleoside diphosphate."

Despite the differences in parentage (looking quickly, GO:0019201 looks like its parents are a subset of those of GO:0050145), I can't find a difference between these two terms. Note that while the definition for GO:0050145 sounds more general when it lists substrates, the list of products removes any ambiguity / generality that would distinguish it from GO:0019201. What am I missing? If a merger is in order, no preference from here about which term survives. @ukemi ? @hdrabkin ?

**Comment by ukemi** [comment]
Are all nucleoside phosphates nucleotides? If I recall there are some that are phosphorylated on different residues and didn't fall into the nucleotide category.

**Comment by ukemi** [comment]
Transferred from https://github.com/geneontology/go-annotation/issues/1878

**Comment by hdrabkin** [comment]
a compound consisting of a nucleoside linked to a phosphate group (ye olde handbook of bmb
e composed of three subunit molecules: a nitrogenous base, a five-carbon sugar (ribose or deoxyribose), and at least one phosphate group. Wiki
No designation as to where the phosphate group is on

This may need term merge

**Comment by ukemi** [comment]
Yup. Should check ChEBI just to be sure that they reflect this.

**Comment by pgaudet** [comment]
I think the distinction is between 
*nucleoside monophosphate kinase (=nucleotide kinase, according to https://en.wikipedia.org/wiki/Nucleoside-phosphate_kinase
and 
*nucleoside diphosphate kinase 2.7.4.6  https://en.wikipedia.org/wiki/Nucleoside-diphosphate_kinase (GO:0004550). I think this is the term that GO:0050145 should be merged into. 

Pascale

**Comment by deustp01** [comment]
Pascale's comment points to a trap. Does each existing term unambiguously indicate the number of phosphate groups on the substrate (input) of the reaction the annotated protein is enabling? I for example thought that GO:0050145, once its definition was studied closely, was specifying a monophosphate kinase, while Pascale, after close study, sees it as a term for a diphosphate kinase. After close re-study, I don't see a way out.

**Comment by hdrabkin** [comment]
NMP -A> NDP -B> NTP

Step A is the monophosphate kinase
Setp B is the diphosphate kinase

GO:0050145 has synonyms  NMP-kinase activity | nucleoside monophosphate kinase activity | 
The term name and def to NOT specifiy substrate

GO:0019201  def specifies monophophate substrate although term does not.
  | Catalysis of the reaction: ATP + nucleoside monophosphate = ADP + nucleoside diphosphate.

**Comment by hdrabkin** [comment]
So if we have a go term for step B, GO:0004550, then if we merge GO:0019201 and  GO:0050145 we should change the name to indicate a nucleotide monophosphate kinase


  -

**Comment by pgaudet** [comment]
That would certainly be clearer - although a nucleotide is a monophosphate, it's redundant. It would be more elegant to have it in the synonyms. 

Pascale

**Comment by hdrabkin** [comment]
sorry meant nucleoside monophosphate kinase activity. That way no questions;

**Comment by deustp01** [comment]
As long as the redundant names are preserved someplace, that's fine. I think usage of "nucleotide" to mean a molecule with one or more phosphates is fairly widespread, accompanied by the use of nucleotide mono / di / triphosphate when the user wants to specify an exact number.

**Comment by hdrabkin** [comment]
So I forgot now what it was I was suppose to do with this.
 merge GO:0019201 and GO:0050145 we should and  change the name to indicate a nucleoside monophosphate kinase?

**Comment by pgaudet** [comment]
We have 
- **GO:0050145 nucleoside phosphate kinase activity**: ATP + nucleoside phosphate = ADP + nucleoside diphosphate. Source: EC:2.7.4.4, MetaCyc:NUCLEOSIDE-PHOSPHATE-KINASE-RXN
- **GO:0004550 nucleoside diphosphate kinase activity**: ATP + nucleoside diphosphate = ADP + nucleoside triphosphate. Source: EC:2.7.4.6
- **GO:0019201 nucleotide kinase activity** : ATP + nucleoside monophosphate = ADP + nucleoside diphosphate - according to wikipedia this is EC:2.7.4.4


so, I think you can merge GO:0019201 and GO:0050145, and fix the names. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Done!
