### ISSUE TITLE
NTR : regulation terms for GO:0044539/long-chain fatty acid import

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#15479]
Dear GO editors,
could you please create regulations terms, including positive and negative regulation, for the Biological process GO:0044539/long-chain fatty acid import. In Fig 3f  of PubMed=28178239, siRNA of EPRS,  decrease LCFA uptake and I would like to annotate that EPRS regulates this process.
Thanks in advance for your help.
Lionel

**Comment by pgaudet** [comment]
@lbreuza 
Can you specify import where ? I suppose into the cell ? 

Thanks, Pascale

**Comment by lbreuza** [comment]
@pgaudet 
yes, uptake of LCFA by cells.
