### ISSUE TITLE
NTR: regulation terms for GO:1901737 (R)-mevalonic acid biosynthetic process

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15482]
Could I please have all the regulation terms for GO:1901737?

For annotation of PMID:24296663

Please add GOC_REFs:
GOC:rph
GOC:BHF
GOC:BHF_miRNA

Thanks.

**Comment by hdrabkin** [comment]
GO:0106107 for regulates
GO:0106108 for negative
GO:0106109 for positive
