### ISSUE TITLE
symbiont process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15497]
_From @ValWood on March 28, 2018 16:10_

human has 1403 annotations to "symbiont process". I find these very misleading.
The practice of annotating human genes to viral processes seems very strange to me full stop...

_Copied from original issue: geneontology/go-annotation#1891_

**Comment by pgaudet** [comment]
_From @ValWood on March 28, 2018 16:16_

for example 600+  human 
genes

annotated to
GO:0019058   viral life cycle
Definition
A set of processes which all viruses follow to ensure survival; includes attachment and entry of the virus particle, decoding of genome information, translation of viral mRNA by host ribosomes, genome replication, and assembly and release of viral particles containing the genome. Source: ISBN:1555811272

...makes it very difficult to identify/ analyse known/unknown human processes, these don't fit the proposed definition of a GO process

**Comment by pgaudet** [comment]
_From @ValWood on March 28, 2018 16:17_

"A biological process represents a specific objective that the organism is genetically “programmed” to achieve.
https://github.com/geneontology/go-ontology/issues/14899

**Comment by pgaudet** [comment]
We need to fix the ontology (there are lots of tickets). There are many children that are either dubious or at the wrong place. Examples: 
- autophagy of host cells involved in interaction with symbiont (not sure what that means - is this a symbiont or a host process?)
- regulation of entry of bacterium into host cell (dubious)
- negative regulation by host of viral genome replication (not a symbiont process)

- etc ! 

Pascale

**Comment by pgaudet** [comment]
_From @ValWood on March 28, 2018 18:38_

OK, we'll ignore these terms for our purposes...

**Comment by pgaudet** [comment]
_From @ValWood on March 28, 2018 18:38_

you can close this if it's covered...

**Comment by pgaudet** [comment]
_From @cmungall on March 28, 2018 19:36_

Relevant ticket:
https://github.com/geneontology/go-ontology/issues/14807

I think many of the part-of children of symbiont process should in fact be regulates.

**Comment by pgaudet** [comment]
_From @ValWood on March 28, 2018 20:0_

> I think many of the part-of children of symbiont process should in fact be regulates.

I don't think that solves the problem.

Human genes are not "regulating" viral processes....virus are co-opting human processes for their own purposes..... A big difference.

**Comment by pgaudet** [comment]
_From @cmungall on March 28, 2018 22:7_

Ah sorry I realized I forgot to give context.

I just picked a random term with annotations under 'symbiont process', http://amigo.geneontology.org/amigo/term/GO:0070946, neutrophil mediated killing of gram-positive bacterium.  (a bacterial one, not viral)

![symb](https://user-images.githubusercontent.com/50745/38058233-04655092-3297-11e8-8b72-9fb17f902d3c.png)


There are a couple of mouse genes with experimental annotations to this. So this was bacterial and there isn't any co-option involved. So it's hopefully more straightforward, but in fact there are a number of issues here.

First is this:

```
id: GO:0051702
name: interaction with symbiont
relationship: part_of GO:0044403 ! symbiont process
```

This doesn't seem right but I'm not sure I fully understand the new definition of symbiont process (which is kind of an odd term no biologist would use, the only hits in google are to GO, or apparently "symbiont process engineer" is a job at hewlett packard). At least with a traditional definition of symbiosis, it's not the case that all interactions with the symbiont would be symbiotic interactions. For example, if my gene products enable some defense against a parasite, that isn't part of the general parasitism process. But it could be considered regulating the activities that are part of the parasitism.

but there is also a problem here:

```
id: GO:0070944
name: neutrophil mediated killing of bacterium
is_a: GO:0070943 ! neutrophil mediated killing of symbiont cell
...
```

AFAIK it's only a symbiont if there is some kind of long-term interaction. Is it considered a parasite if it's a short term opportunistic infection? I suppose arguments can be made that all bacteria on a host can be regarded somewhere on the spectrum commensal/mutual/parasite regardless of duration of interaction. But this then renders the concept of symbiont to be so broad there is little point having a distinction between symbiont process and the parent 'interspecies interaction between organisms', the only differentia is one of relative size.

**Comment by pgaudet** [comment]
_From @ValWood on March 29, 2018 0:16_

yes, but it should be possible to  annotate a process to the host if it is an "evolved function".
Humans aren't "programmed" to replicate viruses  whatever the relationship between  the two...

**Comment by cmungall** [comment]
It's not clear why this was moved from the annotation tracker to the ontology tracker. What is the change in the ontology that will lead to resolution here? Can we discuss this on a multi-species call?

This seems like an annotation or a mapping issue

Just focusing on human, genes that are involved in symbiont process:

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=isa_partof_closure:%22GO:0044403%22&sfq=document_category:%22annotation%22

(I use the term involved in in the strict gp2term sense)

![image](https://user-images.githubusercontent.com/50745/96216203-90fabe80-0f34-11eb-8faf-a87a81f65b00.png)


There is a lot of pretty vague (not very useful?) annotations coming in from SP annotations to:

https://www.uniprot.org/keywords/KW-0945 Host-virus interaction ==> 

```
id: GO:0016032
name: viral process
namespace: biological_process
alt_id: GO:0022415
def: "A multi-organism process in which a virus is a participant. The other participant is the host. Includes infection of a host cell, replication of the viral genome, and assembly of progeny virus particles. In some cases the viral genetic material may integrate into the host genome and only subsequently, under particular circumstances, 'complete' its life cycle." [GOC:bf, GOC:jl, GOC:mah]
comment: See also the biological process terms 'viral infectious cycle ; GO:0019058' and 'lysogeny ; GO:0030069'.
subset: goslim_metagenomics
subset: goslim_pir
synonym: "viral infection" RELATED []
synonym: "virulence" RELATED []
synonym: "virus process" EXACT [GOC:bf, GOC:jl]
xref: Wikipedia:Viral_life_cycle
is_a: GO:0044403 ! symbiotic process
```

Are we sure this mapping is valid? Or maybe a link from the vague 'viral process' to symbiotic process is not valid? The combination seems to weaken the concept of 'symbiont process' to be less useful? Is the virus even in an 'intimate' relationship with its host? I would appreciate the opinions of viral ecologists here.

Other annotations seem to be cases of hijacked host functions, e.g from:

http://amigo.geneontology.org/amigo/reference/PMID:21501828

Are these meaningfully symbiotic?

**Comment by ValWood** [comment]
Personally I don't think we should have the concept of symbiosis in GO. It isn't really a process its the type of relationship that occurs between two interacting species. 

The term symbiotic process has siblings "interaction with symbiont" or "interaction with host" . We could perhaps  merge symbiotic process into "interspecies interaction between organisms" as a related synonym.

Use of  "interaction with symbiont" or "interaction with host"  would make it clear we were annoting a 'symbiotic process' without declaring "symbiosis" as a actual  process.

There is still so much tat still needs to be fixed it's hard to know where to begin, but here at the top is a good place......

**Comment by mgiglio99** [comment]
So, I think a lot of confusion got introduced when the original PAMGO "symbiosis" term got changed to "symbiont process" - which was not the same concept at all.  That change broke a lot of the relationships that PAMGO had established. What it should have been, and has since been changed to, is "symbiotic process". Both "interaction with host" and "interaction with symbiont" should be is_a children of "symbiotic process". However, currently "interaction with symbiont" is not - that one is messed up and fixing that is in my proposed changes to this node that is documented in https://github.com/geneontology/go-ontology/issues/19431
That has been on the multiorganism to-do list for a long time (along with a lot of other stuff.)

@cmungall , above you flip back and forth between saying "symbiont process" and "symbiotic process" - there is no "symbiont process" anymore so we need to be careful in talking about these. Those two terms do not mean the same thing at all. But as I said above,the fact that "symbiont process" ever existed where "symbiosis" had been, messed a lot of things up.

On Chris's specific Keyword mapping question: I don't think "host-virus interaction" should be mapped to "viral process". I'm sure that results in a lot of host proteins being erroneously given annotations for viral things. Part of the problem is that some terms got rearranged and added during the time that "symbiont process" existed - but then, as I said above, "symbiont process" became "symbiotic process" (which is what is should be) causing yet more confusion.

Another problem is that the viral terms were developed in a whole separate effort from the PAMGO terms - so there are clashes and inconsistencies there.

Regarding the "viral process" term specifically, I actually don't think this term should exist - it would be like having a term "bacterial process" or "plant process". I'm guessing that the viral terms under "viral process" should have homes in the "regular" process nodes or under "interaction with host". But I haven't really explored them enough to say for sure.

**Comment by mgiglio99** [comment]
Tagging @nsuvarnaiari and @dsiegele so they can be part of the thread.

**Comment by cmungall** [comment]
@mgiglio99: 

 - you're right: I was switching between the labels symbiont/symbiotic process. I wasn't aware of this history and changes here (minor pet peeve: why do we sometimes feel the need to affix "process" on the end of processes? Why didn't we just go back to the original name?)
 - I agree with your analysis of "viral process". @pgaudet should we make a separate ontology ticket for this? (This is likely to be non-trivial but I think it's best to have a new ticket here with clear proposal)
 - the mapping: we agree the mapping for KW:HVI to VP is bad (and untenable in VP goes away). What should it map to?
    - note that GO:0019048 "modulation by virus of host process" has an EXACT syn "host-virus interaction". It seems this syn should not be EXACT
    - would GO:0044419 hopping up two levels "interspecies interaction between organisms" be valid? Do we even define organism (many consider this to only be cellular organisms)? Is this even useful?

**Comment by pgaudet** [comment]
This is now resolved by having 'biological process involved in symbiotic interaction'
