### ISSUE TITLE
de/glutamylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15496]
under
GO:0043687    post-translational protein modification
is

GO:0018193    peptidyl-amino acid modification
The alteration of an amino acid residue in a peptide.

and then
GO:0018200    JSON
peptidyl-glutamic acid modification
The modification of peptidyl-glutamic acid.

These terms are describing the modification *of* a peptidyl-glutamic amino acid.

Then the next child is
GO:0018095    protein polyglutamylation
The addition of one or more alpha-linked glutamyl units to the gamma carboxyl group of peptidyl-glutamic acid.

this is describing something different.... its the *addition of a glutamyl units*  to an existing polypeptide chain.... rather than addition to glutamyl units?

OK now we switched so:

then:
this has a descendant
GO:0035608    protein deglutamylation

Definition (GO:0035608 GONUTS page)
The removal of a glutamate residue from a protein. Glutamate residues in proteins can be gene-encoded, or added as side chains during the protein modification process of polyglutamylation. PMID:21074048

despite the fact that  "Glutamate residues in proteins can be gene-encoded" , this is not relevent here, because this term is only concerned with the "modification-type" protein polyglutamylation.

At the next level

A GO:0035611    protein branching point deglutamylation | is_a
B GO:0035610    protein side chain deglutamylation | is_a
C GO:0035609    C-terminal protein deglutamylation
A&B are the same as the parent term

C 
GO:0035609    C-terminal protein deglutamylation
Definition (GO:0035609 GONUTS page)
The removal of a C-terminal, gene-encoded glutamate residue from a protein. PMID:21074048

has no right being under "protein modification" (see above)

====

https://www.ebi.ac.uk/QuickGO/term/GO:0070740

from
https://github.com/geneontology/go-annotation/issues/1896#issuecomment-377020984

**Comment by ValWood** [comment]
I asked the fission yeast community and this modification has been looked for in fission yeast, but not detected.
Could we have a taxon restriction added?

(Since it only seems to happen in ageing cells, and I can't see any evidence for  a 'purpose' I wondered if this was really an evolved modification, or if it is a  toxic reaction, and  the removal is part of "protein repair"?)

**Comment by hdrabkin** [comment]
just for Pombe?

**Comment by hdrabkin** [comment]
"Moreover, we identified the same posttranslational modification in eEF1A from Schizosaccharomyces pombe " (polyglutaminylation) (Protein glutaminylation is a yeast-specific posttranslational modification of elongation factor 1A). ???
Or are you talking about just the deglutaminylation?? 
Why would it not belong under protein modfication? (demethylation is (via protein dealkylation)?

**Comment by ValWood** [comment]
I was only asking about "deglutaminylation", but i only asked about tubulin (which seems to be the major  target of deglutaminylation but ignore the taxon restriction part.

**Comment by ValWood** [comment]
Hi Harold,

The problem was this term (and others like it)

GO:0035609 C-terminal protein deglutamylation
Definition (GO:0035609 GONUTS page)
The removal of a C-terminal, gene-encoded glutamate residue from a protein. PMID:21074048


This isn't a modification, its removal of a gene encoded C-terminal residue?

**Comment by hdrabkin** [comment]
It would be a modification of the protein sequence regardless of how the glutamic acid residue got there; either from polyglutamtaminyization. or coded.

**Comment by ValWood** [comment]
I don't understand ;)
How can it be a modification if its encoded?
but close if you think it's correct.

**Comment by deustp01** [comment]
I guess it could be a further modification - first the protein gets covalently conjugated with something, and then that something undergoes further chemical reactions. Certainly in the world of glycosylation of mammalian proteins, all those steps are named as kinds of modification. But, agreed, removal on an encoded C-terminal glutamine is a different kind of modification than addition of glutamine residues to the encoded C-terminus of a protein followed by removal of some of the added residues.

**Comment by ValWood** [comment]
Let's ignore this,  I will remember this ticket if it crops up again....

**Comment by ValWood** [comment]
I'm  *trying* to stay out of the weeds....this isn't really hampering anything right now....

**Comment by hdrabkin** [comment]
The removal is a modification of the protein. Same as met-removal at the N-terminus of a protein is a post-translational modification; the met is encoded in that case also, but it is still protein processing/modification.
