### ISSUE TITLE
glycerol homeostasis

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15495]
I would like to see "glycerol homeostasis” added to the GO ontology under the parent term "chemical homeostasis” (GO:0048878). The definition could be "Any process involved in the maintenance of an internal steady state of glycerol within an organism or cell.”  Example can be found in PMID:15220221.

**Comment by pgaudet** [comment]
Hi @slaulederkind 
This really seems to be an example of a read out: The abstract states "we determined tissue glycerol levels as a marker of lipolysis " - meaning that they are really testing 'GO:0016042 lipid catabolic process' or 'GO:0061725 cytosolic lipolysis' - what do you think ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Yes, lipolysis is what the authors were testing.

**Comment by deustp01** [comment]
Wouldn't we want to restrict the use of "X homeostasis" to cases where there are sensors and feedbacks that function to detect X levels and change processes that generate or consume X to maintain its level within a range? So, glucose homeostasis in mammals. I'm not aware of such a system for glycerol but that may be ignorance.
