### ISSUE TITLE
biological regulation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15490]
only has 7 direct annotations

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=regulates_closure:%22GO:0065007%22&sfq=document_category:%22annotation%22

@pgaudet  can we make this "not for direct annotation"
(manual or annotation transfer), if you don't know more than this you don't really know anything...

**Comment by pgaudet** [comment]
Hi Val, 

I created a ticket to review annotations (https://github.com/geneontology/go-annotation/issues/1887)

Shouldn't we also add 'do not annotate to 

'regulation of biological process' (0 direct)
'negative regulation of biological process' (0 direct)
'positive regulation of biological process' (2 direct)? 

Thanks, Pascale

**Comment by ValWood** [comment]
great.

Shouldn't we also add 'do not annotate to

absolutely!

**Comment by ValWood** [comment]
from any source, EXP or inferred....
