### ISSUE TITLE
is an adaptor just another word for a scaffold protein?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15509]
Hi

I think a review of this area of the ontology is needed.
It seems to me that the definitions for  'molecular adaptor activity' and 'structural molecule activity' are very close and that possibly these and their child terms need to be more closely aligned. Currently these parent terms converge on the term GO:0005078 MAP-kinase scaffold activity. Which seems to highlight that an adaptor protein is a type of scaffold protein. What do you think?

GO:0060090    molecular adaptor activity
Definition The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way.

> is_a GO:0035591   signaling adaptor activity
Definition The binding activity of a molecule that brings together two or more molecules in a signaling pathway, permitting those molecules to function in a coordinated way. Adaptor molecules themselves do not have catalytic activity.

>> is_a  GO:0005078    MAP-kinase scaffold activity
Definition The binding activity of a molecule that functions as a physical support for the assembly of a multiprotein mitogen-activated protein kinase (MAPK) complex. Binds multiple kinases of the MAPKKK cascade, and also upstream signaling proteins, permitting those molecules to function in a coordinated way. Bringing together multiple enzymes and their substrates enables the signal to be transduced quickly and efficiently.

GO:0005198   structural molecule activity
Definition The action of a molecule that contributes to the structural integrity of a complex or its assembly within or outside a cell.

> is_a GO:0032947   protein-containing complex scaffold activity
Definition A structural molecule activity that provides a physical support for the assembly of a multiprotein complex. The scaffold may or may not be part of the final complex.

>> is_a  GO:0005078    MAP-kinase scaffold activity

Ruth

**Comment by RLovering** [comment]
if scaffold and adaptor are related then perhaps the following ontology would work:
GO:0005198 structural molecule activity
> is_a GO:0032947 protein-containing complex scaffold activity
>> is_a GO:0060090 molecular adaptor activity
>>> is_a GO:0035591 signaling adaptor activity
>>>> is_a GO:0005078 MAP-kinase scaffold activity

see also ticket https://github.com/geneontology/go-annotation/issues/1899#issuecomment-377683784

**Comment by pgaudet** [comment]
@RLovering The difference is that the adaptor links two molecules; while the structural molecule activity contributes to the overall stability of a complex. 

Improvements to the definitions are welcome. 

@ukemi I wonder is the parent 'signaling adaptor activity' is right for 'GO:0005078 MAP-kinase scaffold activity'? 

Thanks, Pascale

**Comment by ukemi** [comment]
The MAPK scaffold activity seems to fit the definition of 'signaling adaptor activity' to me. The distinction between the signaling term and the structural parent is that the parent can be used for things like cytoskeletal proteins that are purely structural.

**Comment by pgaudet** [comment]
ok. Should we close this ?

**Comment by ukemi** [comment]
I think @RLovering 's comment from the 31st of March makes sense.

**Comment by pgaudet** [comment]
I am not sure scaffold and adaptor are always related; sometimes the adaptor just bring things together, it does not necessarily have a scaffold role.

**Comment by ukemi** [comment]
OK. Maybe we could improve a bit on the adapter definition to make this clearer?

**Comment by RLovering** [comment]
I'm lost, are we saying that GO:0005078 MAP-kinase scaffold activity should actually be called MAP-kinase adaptor activity?

 GO:0032947 protein-containing complex scaffold activity
definition: A structural molecule activity that provides a physical support for the assembly of a multiprotein complex. The scaffold may or may not be part of the final complex. 
 GO:0035591 signaling adaptor activity
definition: The binding activity of a molecule that brings together two or more molecules in a signaling pathway, permitting those molecules to function in a coordinated way. Adaptor molecules themselves do not have catalytic activity. 

How exactly are you going to tell the difference between a scaffold molecule that provides 'physical support' for 2 proteins and an adaptor that binds 2 proteins?

I'm going to see if Sandra Orchard (I will have to email her as I don't know her handle) and Birgit @bmeldal have any thoughts about the difference between a scaffold and an adaptor

Best

Ruth

**Comment by ukemi** [comment]
No one calls it that. We try to use the terms used by the community.

**Comment by bmeldal** [comment]
Without too much thought (!): an adaptor could link 2 complexes together to get them somewhere while the scaffolding protein is part of the complex. 

Analogy: when I was a kid my mum clipped a long string between my gloves and threaded it through the jacket sleeves so I wouldn't loose my gloves. The string is an adaptor, connected to but not part of either glove. The scaffolding element is the thread used to sew the fabric parts of the glove together. You can remove the string (= adaptor) without breaking the gloves (= complexes). :)

@sandraorchard

**Comment by RLovering** [comment]
Response from Sandra:
Its rather open to debate, but I'd say that 
Scaffold protein - hold specific proteins in a defined conformation so they can form a signalling module
Adaptor - a looser arrangement, still groups proteins in close proximity to enable signalling but a less defined set and won't hold them in any specific conformation.
Does that help?
Sandra

**Comment by RLovering** [comment]
I like Sandra's comments on this which make this clearer to me, but I still think experimentally these are very difficult to distinguish.
Do we really need to distinguish them?
Ruth

**Comment by ValWood** [comment]
I think scaffold and adaptor are slightly  different.
However sometimes a 'scaffold' is also an 'adaptor' . They are different activities.

The scaffold provides physical support for the complex (I would say it was required for structuaral integrity rather than stability)

In this complex cdc11 and sid4 are both "scaffolds"
https://cloud.githubusercontent.com/assets/7359272/18230776/b7fa235a-729d-11e6-883e-13a6af9d2df7.jpg

They could also both be described as "adaptors" (the adaptor activity is provided by the scaffolding)
The MAP kinase scaffold is similar, it is both a scaffold and an adaptor.

Some things are adaptors but not scaffolds (tethers of microtubules and the like)
Some things are  scaffolds but not adaptors. (a ribosomal scaffold for example)

This clause in the definition is a bit weak to describe this part:
"permitting those molecules to function in a coordinated way."

A scaffold also permits  molecules to function in a coordinated way.

The "adaptor" serves as a "connector" between explicit molecules (either to pass a signal, connect 2 cell components, I'm trying to think of a common theme....)

**Comment by ValWood** [comment]
Note that neither of these terms are confined to signalling.

My classical non-signalling adaptor is the microtubule-kinetochore attachment machinery.

**Comment by ValWood** [comment]
An adaptor attaches x to y so that z can occur

**Comment by ValWood** [comment]
I like Birgits analogy, and I think that probably encapsulates what we should  mean by "adaptor"

I have always thought that "adaptor" was the wrong activity for the MAP kinase scaffold. I haven't seen it called that, and I'm still not convinced it is regulating the pathway other than bringing the other signalling components into  close proximity. This regulation isn't really  a property of the scaffold (the thing regulating the pathway are the upstream events bringing these components together on the scaffold).

**Comment by pgaudet** [comment]
**GO:0060090 molecular adaptor activity**
**CURRENT Definition** The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, ~often stoichiometric interaction,~ permitting those molecules to function in a coordinated way.
**PROPOSED Comment** An adaptor is not an integral part of the molecules it brings together; neither are the molecules brought together necessarily a stable complex. Consider annotating to 'structural molecule activity ; GO:0005198' if the gene product annotated is an integral part of the complex. 


----

**GO:0005198 structural molecule activity**
**CURRENT Definition**  The action of a molecule that contributes to the structural integrity of a complex or its assembly within or outside a cell. 
**PROPOSED Definition** The action of a molecule that contributes to the structural integrity of a complex ~or its assembly within or outside a cell~.
**PROPOSED Comment**  A structural molecule is an integral part of the complex to which it provides stability. To annotate gene products that bring two or more proteins together, but are not part of the complex, consider annotating to 'molecular adaptor activity ; GO:0060090'. 

---
Does that clarify the issue (correctly?)

Thanks, Pascale

**Comment by ValWood** [comment]
Well then we have the problem that  "MAP kinase scaffold" is a conflation of scaffold and adaptor 
(in def and parentage).

I also think we should avoid the word "stability" in the comment.  I don't think this is quite right, the scaffold is structuraal integrity. Stability is  a separate issue (linked to many processes,   including synthesis and degradataion).

>An adaptor is not an integral part of the molecules it brings together; 

is also a bit unclear, and I'm not sure this is *alwayss * true.

Also we need to consider that "signaling adaptor" might be used slighly differently in the field than our generic "molecular adaptor" term

The current definition of adaptor definitely needs to be refining. At present you could annotate practically anything which binds to 2 things simultaneously. It isn't really pinning down the meaning od "adaptor"

**Comment by pgaudet** [comment]
>Well then we have the problem that "MAP kinase scaffold" is a conflation of scaffold and adaptor
(in def and parentage). 
Let's do this as a second step ? 

> I also think we should avoid the word "stability" in the comment. I don't think this is quite right, the scaffold is structuraal integrity. Stability is a separate issue (linked to many processes, including synthesis and degradataion). 
Good point. How about just 
" A structural molecule is an integral part of the complex ~to which it provides stability~. To annotate gene products that bring two or more proteins together, but are not part of the complex, consider annotating to 'molecular adaptor activity ; GO:0060090'."

>>  An adaptor is not an integral part of the molecules it brings together;

> is also a bit unclear, and I'm not sure this is *alwayss * true.
To me that's the easiest way to distinguish; I think it's two for all the children of 
-  GO:0030674 protein binding, bridging and 
- GO:0030533 triplet codon-amino acid adaptor activity 

I think we need to anyway look at children of 'signaling adaptor activity' and their annotations - it looks like there is some inconsistency there (that may result from the definitions of the terms not being clear enough).             

Let me know if I can implement the changes in definitions and comments as proposed here.

**Comment by ValWood** [comment]
For adaptor how about

The binding activity of a molecule that *connects* together two ~or more~ molecules (proteins, complexes of cellular structures) through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way.

I would leave our "or more" because it becomes ambiguous and obscures the fact that the adaptor  is linking 2 cellular entities by bridging them.  This does not rule out the terms use as a 3-way adaptor, but  makes the elemental activity clearer and less likely  to be confused with a scaffold.

**Comment by ValWood** [comment]
Maybe the comments could also include examples?

**Comment by pgaudet** [comment]
Discussion with @RLovering 
- Adaptor is a more general term for scaffold
- These should be moved out of  GO:0005198 structural molecule activity

Proposed hierarchy: 
molecular_function
-  GO:0060090 molecular adaptor activity
 
--  GO:0030674 protein binding, bridging

 --   GO:0035591 signaling adaptor activity (should this be a GO:0030674 protein binding, bridging?) 
 --- GO:0008269 JAK pathway signal transduction adaptor activity
 --- GO:0005078 MAP-kinase scaffold activity** (need to also have GO:0032947 as parent)
 --- GO:0005070 SH3/SH2 adaptor activity
 --- GO:0030159 receptor signaling complex scaffold activity -> change label 'receptor signaling complex adaptor activity' to make this more general
 ----  GO:0005068 transmembrane receptor protein tyrosine kinase adaptor activity 
 --   GO:0030533 triplet codon-amino acid adaptor activity 

( --- GO:0032947 protein-containing complex scaffold activity - merge into molecular adaptor activity) 
+ add synonyms ADAPTOR + SCAFFOLD if appropriate
----

molecular_function
- GO:0005198 structural molecule activity
--  GO:0017056 structural constituent of nuclear pore
-- GO:0003735 structural constituent of ribosome
-- etc

Would that be a good solution ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I still think scaffold and adaptor are different things.


can we avoid the  use fo the word "scaffold" and make it a related synonym if we are referrign to "adaptor activity"

https://en.wikipedia.org/wiki/Scaffold_protein
Although scaffolds are not strictly defined in function, they are known to interact and/or bind with multiple members of a signalling pathway, tethering them into complexes. In such pathways, they regulate signal transduction and help localize pathway components (organized in complexes) to specific areas of the cell such as the plasma membrane, the cytoplasm, the nucleus, the Golgi, endosomes, and the mitochondria.

Scaffold proteins act in at least four ways: tethering signaling components, localizing these components to specific areas of the cell, regulating signal transduction by coordinating positive and negative feedback signals, and insulating correct signaling proteins from competing proteins.[1]

**Comment by RLovering** [comment]
I think that Sandra's definition is more specific than wikipedias and that although there is no overlap between the genes listed in https://en.wikipedia.org/wiki/Signal_transducing_adaptor_protein and the wikipedia description of scaffolds in general the common theme is that they both bind more than one protein and have no enzyme activity. This is also the case for the GO definitions:

GO:0060090 molecular adaptor activity
Definition: The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way. (this actually sounds like it is describing the signaling scaffold proteins and I am not sure the definition should say this. perhaps it should be: The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, interaction, enabling appropriate functioning of at least one of these molecules. An adaptor does not usually have an enzyme activity). 

 GO:0032947 protein-containing complex scaffold activity
Definition: A structural molecule activity that provides a physical support for the assembly of a multiprotein complex. The scaffold may or may not be part of the final complex. 

- tethering signaling components - how is this experimentally distinguised as different from an adaptor?

- localising to a specific area of the cell - how is this experimentally distinguised as different from an adaptor?

- regulating signal transduction - (scaffolds bind all three kinases, enhancing kinase specificity and restricting signal amplification by limiting kinase phosphorylation to only one downstream target) - how is this experimentally distinguised as different from an adaptor?

- Insulating correct signaling proteins from inactivation - how is this experimentally distinguised as different from an adaptor?

I think it is very difficult to apply these terms and consequently these have not been used for all adaptors and all scaffold proteins. If we are going to have these as separate functions then we need to have examples of experimental data that will enable these terms to be applied. When I have used the term it has usually been because the author says ' the adaptor' or the 'scaffold protein' or the protein name includes the word adaptor or scaffold (eg HOMER) and there is expt evidence that the protein is binding at least 2 appropriate proteins. The alternative is that we could have a list of proteins that when they are shown to bind an appropriate target can then be annotated as adaptor or scaffold.

But maybe there are good experiments which are often used and can be used to distinguish scaffold from adaptor and curators can be given guidelines based on these expts to ensure consistent application of the terms.

I guess I just think it would be useful to have a grouping terms for proteins that have no enzyme activity and are not structural - like myosin - but which hold entities in a specific location/proximity to another entity. Adaptor seems like a very general term, and by having this as a parent to scaffold then the signaling adaptor and scaffold terms will be much more closely linked.

**Comment by ValWood** [comment]
OK, I think you are right. I just checked our annotations to "protein complex scaffold", and they could all be described as adaptors.

**Comment by pgaudet** [comment]
I'll go ahead with the merge then. 

Thanks for the comments ! 

Pascale

**Comment by hattrill** [comment]
Just looking at cullin-ubiquitin ligase complex (CRL) and could do with some help in placing the components:
Cullins are always referred to as scaffolding proteins, which seems analogous to MAP-kinase scaffold activity, in that they are required to link the E3 ligase and substrate recognition protein or Skp1/other adaptor-substrate recognition protein.

So for the components of a CRL complex, does this look right?
cullin: molecular adaptor activity
Adaptor protein e.g. Skp1: molecular adaptor activity
Substrate recognition protein e.g. F-box protein: protein binding, bridging involved in substrate recognition for ubiquitination 
![Screen Shot 2019-03-14 at 08 12 37](https://user-images.githubusercontent.com/11865746/54342355-22f16580-4634-11e9-8faf-a402d9f08bf7.png)

**Comment by ValWood** [comment]
This might be a useful eg of the difference. 
Cullin fits our definition  of adaptor, but I have never seen it described as one. 
In the 'old' situation, I would describe cullin as a 'scaffold" and skp1, and F-boxes as  protein-binding bridging which fits community usage.

I think it is absolutely required for the catalytic activity? so it could be
ubiquitin protein ligase activity contributes_to

**Comment by pgaudet** [comment]
This is why scaffold and adaptors have been merged - (not yet visible in AmiGO); looks like this was the correct decision? 

The other important point is that 'scaffolds' have been removed from the 'structural molecule activity' branch. 

Let me know if this seems OK. Should we add more information to help distinguish these two branches? 

Thanks, Pascale

**Comment by ValWood** [comment]
but biologists wouldn't call cullin an adaptor, they would call it a scaffold...it has a slightly different role from the adaptor.

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Cullin
Cullins are a family of hydrophobic scaffold proteins which provide support for ubiquitin ligases (E3)

then the skp1 and F-box are substrate-specific adaptors

**Comment by pgaudet** [comment]
Right - I didn't rename everything 'adaptor' - I kept the term labels are they were. I paste the current (modified) version of the ontology: 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/4782928/54345348-29d3a480-4643-11e9-859c-e37d05e7ae56.png">

**Comment by hattrill** [comment]
I think that I would be inclined not to give cullins a 'contributes_to' the enzyme activity as we can breakdown the roles in the complex....although I probably have done in the past, but that will get sorted in the contributes_to clean-up.
I am ok with using adaptor for cullins. I guess there might be a case for having an intermediate term:
'enzyme complex scaffold activity' but it might just muddy the water and it might be difficult to place with regard to 'signaling adaptor activity'.
