### ISSUE TITLE
merged/obsolete terms have 'no result' in QuickGO

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#15502]
E.g. GO:0043234 protein complex no longer has a result in QuickGO when it should point to GO:0032991 protein-containing complex which it got merged into.

Amigo2 has an obsoletion page and points to the new AC.

A search directly in the url will redirect.

**Comment by ukemi** [comment]
I just checked, an they the merged term strings are valid synonyms. So this should be working.

**Comment by ValWood** [comment]
I mailed QuickGO a while ago about this. It would be useful.....
v

**Comment by ukemi** [comment]
I'm going to close this ticket because I don't think this is an issue with the ontology. Everything looks ok to me on our end.
