### ISSUE TITLE
GO:0090435 protein localization to nuclear envelope TPV to membrane organization (via Matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15514]
A number of proteins are involved in "localizing proteins to the nuclear envelope", but  they are not involved in membrane organization per se. So this parentage should be removed?

http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC19G7.15
(actually I don't think that this should be annotated to "protein localization to nuclear inner membrane" either, but that's another story.....)

**Comment by ValWood** [comment]
I don't think so.... or at least here, you agreed to remove.
https://github.com/geneontology/go-ontology/issues/12929
duplicate?

**Comment by ValWood** [comment]
As a general rule, localizing something to a membrane is sometimes organization, but often it isn't so the link might be able to be added to descendants...

**Comment by ukemi** [comment]
OK. I remembered working on it, I just couldn't remember what I did.
