### ISSUE TITLE
NTR: transmembrane receptor protein kinase adaptor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15511]
GO:0035591   signaling adaptor activity
> is_a New term: transmembrane receptor protein kinase adaptor activity
>> is_a GO:0005068 transmembrane receptor protein tyrosine kinase adaptor activity
>> is_a New term: transmembrane receptor protein serine/threonine kinase adaptor activity

New term: transmembrane receptor protein kinase adaptor activity
Definition: The binding activity of a molecule that brings together a transmembrane receptor protein kinase and one or more other molecules, permitting them to function in a coordinated way. PMID: 16601693
GOC:rl
GOC:BHF

if you agree with New term: transmembrane receptor protein serine/threonine kinase adaptor activity
then this would need the Definition: The binding activity of a molecule that brings together a transmembrane receptor protein serine/threonine kinase and one or more other molecules, permitting them to function in a coordinated way. PMID: 16601693
GOC:rl
GOC:BHF

In addition, I think the ontology
 GO:0009967   positive regulation of signal transduction
> part_of GO:0035591   signaling adaptor activity 
is wrong. I do not think all signaling adaptors positively regulate signaling, they could be binding to inhibitors.
Therefore I think the ontology should change to 
GO:0009966   regulation of signal transduction
> part_of GO:0035591   signaling adaptor activity

**Comment by pgaudet** [comment]
Hi @RLovering 
Can you not use just 'protein binding, bridging'? 
The reason I am suggesting this is that the editors had a discussion with respect to terms such as 'serine/threonine protein kinase binding' and we though it was not possible to show both 'protein binding' AND the activity of the bound protein in the same experiment. So it seemed preferable to use the annotation extension to describe which protein is being bound. 

As far as I know we are not going to removing existing terms (yet), but it seems best not to create any new ones, if it can be avoided. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

I would rather use GO:0035591 signaling adaptor activity rather than 'protein binding, bridging', I just realised that there was an inconsistency here. Although I would like to see a child term such as transmembrane receptor adaptor activity. 
'protein binding, bridging' does not imply any role in signaling pathways. I know that the process term associated with the protein will provide this information, however it feels like the MF role of some proteins is considered more 'important' than others, ie we name receptors and TFs but adaptors are another protein given a 'vague' MF term because they are 'just sticky'. Being 'just sticky' was the reason adhesion molecules lost their MF term a few years ago, and this term has now been re-instated. 

please consider 

Thanks

Ruth

**Comment by ValWood** [comment]
@RLovering Current?

Suggestion

GO:0035591    signaling adaptor activity
 has_input  GO:0019199  transmembrane receptor protein kinase activity

 is that correct?  what 2 things is it an adaptor between?

**Comment by RLovering** [comment]
but I anticipate that there are other signaling adaptors that do not bind the receptor. Helen and Giulia have been working a lot on signaling perhaps they have some thoughts on this. Maybe they have found there is no need for these types of terms.

@hattrill @gantonazzo

**Comment by ValWood** [comment]
>but I anticipate that there are other signaling adaptors that do not bind the receptor.

agree. This works for those too.
I have annotated quite a few, in various different contexts (adapting various signalling pathway components, kinases and phosphatases, to the plasma membrane and the Spindle pole body)
https://www.pombase.org/term/GO:0035591

in fact, one child is :
signaling receptor complex adaptor activity
maybe this should merge into "signaling adaptor activity" because it does not add anything that cannot be inferred from the substrates.

Maybe this is useful criteria for whether a  new term should be created? Using these criteria 
MAP-kinase scaffold activity would merge because the "MAP kinase" would be the substrate?

**Comment by hattrill** [comment]
Yes: signaling adaptors can either directly bind the receptor or interact with other proteins that bind the receptor or act in other intracellular signaling complexes.

I think that the 'bridging' aspect is important. It ideally should have 2 inputs: e.g. a receptor and an intracellular signaling protein.
(I don't think that the activity MF should be the input - should be an actual physical substrate)

In terms of Ruth's request...Ialthough there are concerns about over-proliferation of terms, having a few specific adaptor terms to capture common signaling paradigms is useful (and I would like to be able to point to the very set of proteins that act as MAPK scaffolds as they have very interesting properties and are distinct from receptor binding classes). We have 'transmembrane receptor protein tyrosine kinase adaptor activity', so Ruth's request just seems like an very limited addition and tidy up.

**Comment by deustp01** [comment]
Isn't this also something that is naturally handled by a GO-CAM model, avoiding the need for new terms and simultaneously allowing for annotations precisely tailored to the specific proteins involved in the process and the distinctive roles of each?

**Comment by ValWood** [comment]
I think that is what we are saying here. In these instances all can be handled by "signalling adaptor activity"

 All of the above discussion also applies to GO-CAM too....the idea is to minimise the number of terms required to describe the activity within the model.

Sometimes you do need an additional MF term to add detail to the model  but that doesn't seem to be the case here.

**Comment by RLovering** [comment]
But isn't it important, as Helen also points out, to be able to identify where in the signaling pathway the protein has a role. Yes we can just look at the model and look at the protiens bound and work this out. But we also need to provide simple GO annotations that also provide this information. An adaptor that is close to a receptor may be considered a more key hub protein than an adaptor which is within an internal signaling pathway because the internal signaling adaptors will be associated with many different signaling pathways whereas an adaptor at the receptor site may have a more specific activity, Alternatively a signaling adaptor at the end of the signaling pathway that is interacting with the cytoskeleton and enabling the signaling pathway to change the cell morphology/migration etc will be considered different drug targets. 

I can see that you want to minimise terms, but how do you make this call? why is an adaptor that brings the receptor and the intracellular kinases considered to have the same function as an adaptor that brings the kinases and actin together?

**Comment by ValWood** [comment]
> But isn't it important, as Helen also points out, to be able to identify where in the signaling pathway the protein has a role. 

I agree with @deustp01 this comes from the substrate information (this should be available for user interpretation in a GO-Cam or in conventional annotation paradigm). It is less important to hardcode in MF the location in a pathway the adaptor works because that information is provided by the connections to effectors and substrates linked to the same process/pathway (you can just follow the chain of inputs)

However, any context which is not captured by the substrate connection ( for example whether the adaptor is only to recruit pathway components, or provide an adaptor for the substrate), is an important distinction that needs to be captured in the activity since it would not be obvious from the adaptor  the substrate information.
At least this is the criteria I use when I make term requests....

**Comment by RLovering** [comment]
For complex systems it is not always possible to know which protein is providing the 'receptor' activity for a ligand but it might be known which adaptors and other intracellular signaling proteins are transmitting the signal.

So perhaps a better terms would be

transmembrane receptor adaptor activity - because it is not always clear which subunit of the receptor is bound by the adaptor?

currently 420 distinct gene products are associated with the GO term: 
 GO:0005068 transmembrane receptor protein tyrosine kinase adaptor activity
although only 12 expt evidence and 7 TAS/NAS. Although I think this reflects a general problem of curators not knowing how and when to apply adaptor terms rather than anything else.

Currently we have:
 GO:0030159 signaling receptor complex adaptor activity
 > GO:0030160 synaptic receptor adaptor activity
 > GO:0005068 transmembrane receptor protein tyrosine kinase adaptor activity

From what you have said if we look at the existing terms and any new terms these would be better as:
 GO:0030159 signaling receptor complex adaptor activity
Current Definition: The binding activity of a molecule that provides a physical support for the assembly of a multiprotein receptor signaling complex. 
 
> GO:0030160 synaptic receptor adaptor activity
Current definition: The binding activity of a molecule that provides a physical support bridging a synaptic signaling receptor and a downstream signaling molecule.
>> maybe the definition should be revised inline with the parent term definition to:
>>>The binding activity of a molecule that provides a physical support for the assembly of a multiprotein synaptic receptor signaling complex. 

>  new term: transmembrane receptor complex adaptor activity
Definition: The binding activity of a molecule that provides a physical support for the assembly of a multiprotein transmembrane receptor signaling complex. 

>> GO:0005068 transmembrane receptor protein tyrosine kinase adaptor activity 
> merge into the above new term, or rename this term to the more general new term transmembrane receptor complex adaptor activity

Any chance that this will be acceptable?

**Comment by ValWood** [comment]
I don't know. I assumed that we would not want receptors for every activity so I don't request them.  Maybe it is OK.

**Comment by pgaudet** [comment]
Hi @RLovering 
I wonder if 'GO:0030159 signaling receptor complex adaptor activity' is not sufficient here, and you can use the 'has input' relation to specify the target ? 

And we could obsolete 
'synaptic receptor adaptor activity' and
'transmembrane receptor protein tyrosine kinase adaptor activity' 
on the basis that they would lead to combinatorial explosion. 

Similarly in the 'GO:0035591 signaling adaptor activity' sibling branch - we could perhaps create a general term such as 'intracellular signaling protein adaptor activity' and do without the specific children 
'JAK pathway signal transduction adaptor activity'
'MAP-kinase scaffold activity'
? 

(I am aware I said the opposite in the 'protein binding' ticket #15218 but that branch is almost impossible to tackle right now, whereas we could have something neat and GO-CAM-compliant here.) 

Maybe @vanaukenk you have encountered this function in models ? What is the appropriate level of granularity for GO-CAMs ? 

Thanks, Pascale

**Comment by RLovering** [comment]
I'm happy to use GO:0030159. Plus decisions on intracellular adaptor etc
Ruth

**Comment by pgaudet** [comment]
So we're good to close this ? @RLovering

**Comment by RLovering** [comment]
yes fine with me
