### ISSUE TITLE
taxon constraints

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15521]
the following terms should have taxon constraint for fungi

mitochondrial respiratory chain complex I
(never in)

from
https://github.com/geneontology/go-annotation/issues/1917#issuecomment-378862240

**Comment by ValWood** [comment]
correction.

Never in Schizosaccharomyces
Never in Saccharomyces.

@Antonialock   Reminded me that other fungi have it.

**Comment by Antonialock** [comment]
https://www.sciencedirect.com/science/article/pii/S0005272800002516?via%3Dihub#BIB12
