### ISSUE TITLE
Move 'transcription cofactor activity' as a direct child of 'transcription regulator activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15536]
hello, 

For the Transcription refactoring, I will 
* move  'GO:0003712 transcription cofactor activity' as a direct child of 'GO:0140110 transcription regulator activity' (instead of the current 'GO:0000989 transcription factor activity, transcription factor binding', which will get obsoleted).

* update definition from 'Interacting selectively and non-covalently with a regulatory transcription factor and also with the basal transcription machinery in order to modulate transcription. Cofactors generally do not bind the template nucleic acid, but rather mediate protein-protein interactions between regulatory transcription factors and the basal transcription machinery' 

to 'Interacting selectively and non-covalently with a regulatory transcription factor and also with the basal transcription machinery in order to modulate transcription. Cofactors generally do not bind the template nucleic acid, but rather mediate protein-protein interactions between regulatory transcription factors and chromatin-modifying factors and/or the basal transcription machinery.' 

@krchristie @RLovering @ValWood @hattrill 
Is this OK for you? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ukemi 
The logical definition of 'transcription cofactor activity'

is 
molecular_function
 and ('has part' some 'transcription factor binding')
 and (regulates some 'nucleic acid-templated transcription')

This does not seem 'necessary and sufficient to me (it would cover tx factors that are dimers, for example). I plan to remove this - what do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
The current definition of 'GO:0003712 transcription cofactor activity' states that 'cofactors mediate protein-protein interactions between regulatory transcription factors and the basal transcription machinery.'; however more recent literature shows that 'act through bringing enzymatic activities to the locality of the site of their recruitment to the genome. These enzymes either covalently modify chromatin, or result in chromatin reorganisation, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3963257/

**Comment by pgaudet** [comment]
@keseler Do bacteria have co-repressors? 
It's in the prok go-slim, that seems odd. 

Thanks, Pascale

**Comment by ukemi** [comment]
Agreed. Unless we think that each of the subunits of a dimeric transcription factor like the nuclear receptors are both transcription factors and cofactors.

**Comment by pgaudet** [comment]
@ValWood GO:0001076 - transcription factor activity, RNA polymerase II transcription factor binding - may get obsoleted - this will in a different ticket. 

Thanks, Pascale
