### ISSUE TITLE
Obsoletion notice: Some children of GO:0000988	transcription factor activity, protein binding'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15538]
Hello,

As part of the Transcription Factor refactoring project, it has been agreed to obsolete  'GO:0000988	transcription factor activity, protein binding' (see #14790), but first children must be either obsoleted or rehoused. 

I have reviewed the children and I propose, as a first step, to obsolete the following children that have not been very much used: 

  |   |   | Manual EXP, NAS, TAS, RCA, IC | ISS,   ISO, ISA | Impacted groups
-- | -- | -- | -- | -- | --
GO:0001139 | transcription   factor activity, core RNA polymerase II recruiting' |   | 8 | 2 | SGD   (EXP, IC)
GO:0001084 | transcription   factor activity, TFIID-class binding' | consider:   GO:0001094 TFIID-class transcription factor binding | 2 | 2 | BHF-UCL SGD
GO:0001134 | transcription   factor activity, transcription factor recruiting' | consider: DNA binding transcription factor activity (for the   specific protein annotated) | 2 | 2 | CAFA   (2 EXP)
GO:0001087 | transcription   factor activity, TFIIB-class binding' | consider:   GO:0001093 TFIIB-class transcription factor binding | 1 | 2 | BHF-UCL
GO:0001088 | transcription   factor activity, TFIIE-class binding' | consider:   GO:0001095 TFIIE-class transcription factor binding | 1 | 0 | SDG   (mediator complex)
GO:0001090 | transcription   factor activity, TFIIH-class binding' | consider:   GO:0001097 TFIIH-class transcription factor binding | 1 | 1 | SDG   (mediator complex)
GO:0001138 | transcription   factor activity, TFIIH-class transcription factor recruiting' | consider:   GO:0001097 TFIIH-class transcription factor binding | 1 | 1 | SDG   (mediator complex)
GO:0001086 | transcription   factor activity, TFIIA-class binding' | consider:   GO:0001092 TFIIA-class transcription factor binding | 0 | 0 |  
GO:0001136 | transcription   factor activity, TFIIE-class transcription factor recruiting' | consider:   GO:0001095 TFIIE-class transcription factor binding | 0 | 0 |  
GO:0001089 | transcription factor activity, TFIIF-class binding'  | consider:   GO:0001096 TFIIF-class transcription factor binding | 0 | 0 |  
GO:0001137 | transcription   factor activity, TFIIF-class transcription factor recruiting' | consider:   GO:0001096 TFIIF-class transcription factor binding | (SGD: PAF1/CDC73) | 0 |  
GO:0001082 | transcription factor activity, RNA polymerase I transcription factor binding' | 4 | 0 (only ISO) | SGD (RRN3)  
GO:0001083 | transcription factor activity, RNA polymerase II basal transcription factor binding' | 0  | 0 |  
GO:0001153 | transcription factor activity, RNA polymerase III transcription factor recruiting' | 0 | 0 |  
 GO:0001007 | transcription factor activity, RNA polymerase III transcription factor binding | 4  | 7 | UniProt BRF2 (UniProt:Q9HAW0) FlyBase

Impacted groups are: 
SGD @suzialeksander 
Flybase @hattrill 
dictyBase @pfey03 
BHF @RLovering 

Also tagging for feedback: 
@krchristie 
@ValWood 

The reason for obsoletion is to simplify the transcription branch of the ontology. These terms have hardly been used. The corresponding ‘binding’ terms, in combination with a transcription regulator term, is sufficient to capture the function of the annotated gene products.

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on April 17, 2018. Unless objections are received by April 17, 2018, we will assume that you agree to this change.

Thanks, 

Pascale

**Comment by pfey03** [comment]
We have no EXP annotation to GO:0000988 or its children. There are a 100 total for Dicty, 74 are IBA and rest IEA.

Thanks,
Petra

**Comment by RLovering** [comment]
BHF-UCL annotations revised - all done

**Comment by pgaudet** [comment]
Hi @bmeldal 
The proposal is not touching GO:0000988 yet - only the children mentioned there. Can you check if the children are potentially also a problem ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
GO:0001134 - 4 cpxs with child GO:0001135 transcription factor activity, RNA polymerase II transcription factor recruiting

Already annotated to GO:0051123 RNA polymerase II transcriptional preinitiation complex assembly which probably captures its activity better.

All deleted.

**Comment by pgaudet** [comment]
Obsolete 
* GO:0001084 transcription factor activity, TFIID-class binding
* GO:0001087 transcription   factor activity, TFIIB-class binding
* GO:0001088 transcription factor activity, TFIIE-class binding
* GO:0001090  transcription factor activity, TFIIH-class binding'
* GO:0001086 transcription factor activity, TFIIA-class binding

**Comment by pgaudet** [comment]
@ValWood (and Colin Logie) suggested that the 'recruiting' terms may capture a different type of activity, so I didn't touch them and created a new ticket to discuss how to handle them 

#15577
