### ISSUE TITLE
Rename 'GO:0044539 long-chain fatty acid import' to 'long-chain fatty acid import into cell'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15541]
Hello, 

We have decided to fix 'import' terms that don't describe where the import takes place (either by merging into the 'transport' parent or by adding the location of the transport. (see point 4 in #13356) 

Looking at the annotations to GO:0044539 long-chain fatty acid import, I think we can rename it long-chain fatty acid import into cell', but I would like the affected groups to confirm this: 
https://docs.google.com/spreadsheets/d/1MveZshX0EeN1v1Tz8bI6UCMdzchoMbsfj2jj6GURjb0/edit#gid=0

BHF-UCL @rachhuntley 
CGD  @marekskrzypek
SGD @suzialeksander 
UniProt @ggeorghiou 

Thank you in advance for your help, 

Pascale

**Comment by pgaudet** [comment]
Hi @alanbridge 
Thanks for looking into this. The issue is that 'import' without know where the substrate in imported is no different from transport - see point 4 in #13356 

So there are two options: 
1) Merge GO:0044539 long-chain fatty acid import' into GO:0015909 long-chain fatty acid transport
2) Review annotations to GO:0044539 long-chain fatty acid import and move those that are not 'into cell', to the correct term. 

Do you have a preference ? Do you know how many annotations are NOT import into cell? 

Thanks, Pascale

**Comment by alanbridge** [comment]
I guess as transport is a more general term than import option 1 looks OK. I am afraid I don't know how many of these transport annotations are NOT import into a cell; but you could look at this by retrieving the annotations to experimental transport terms and checking the subcellular locations of the proteins (for ACSL3, it's intracellular organelle membranes like ER, peroxisome, mitochondrion). How many are known to be in other locations? Probably quite a few as lipid metabolism involves frequent transport to and from intracellular stores... 

More generally, could import be dealt with by composing transport terms with a "from" and "to" compartment? 

Like: "Transport of X from Y to Z." 

People could then query GO for instances of transport where Z is their preferred "in" (like an organelle, the cell etc) to get occurrences of import?

**Comment by alanbridge** [comment]
I guess that could be: 

"Transport of CHEBI:57560* from "some compartment" to GO:0005777"

*the anion, major microspecies at pH7.3 :-)

**Comment by alanbridge** [comment]
and a child term...

"Transport of CHEBI:57560* from GO:0005829 to GO:0005777"

(from cytosol to peroxisome)

**Comment by pgaudet** [comment]
I reviewed the annotations again. There are a few unresolved cases, but for protein potentially not involved in transport at all, so the change in term label and ontology position would not make the annotations worse.

**Comment by pgaudet** [comment]
@RLovering you still have 3 annotations to review - whenever you can 
https://docs.google.com/spreadsheets/d/1MveZshX0EeN1v1Tz8bI6UCMdzchoMbsfj2jj6GURjb0/edit#gid=0

**Comment by RLovering** [comment]
Hi
Please could we have a more specific fatty acid term as an is_a child of the following:
 GO:0032365 intracellular lipid transport
 GO:0015909 long-chain fatty acid transport
New term: intracellular long-chain fatty acid transport

This is a big group of chemicals and I think a grouping term would be helpful
To be associated with Fabp3 P11404 PMID: 15835924 
Thanks 
Ruth

**Comment by RLovering** [comment]
BHF annotations all checked, Note that one of these was not changed
Ruth

**Comment by pgaudet** [comment]
@RLovering 
Do you want just 'intracellular long-chain fatty acid transport', or is the transport across some membrane (into an organelle?)
