### ISSUE TITLE
GO:0045094 interleukin-18 beta subunit binding

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#15555]
Dear GO annotators,

Could you please review GO:0045094 interleukin-18 beta subunit binding? 
For structure and binding mode of interleukin-18 to ligand-binding receptor subunit IL18R1 (alpha chain) and signaling receptor subunit IL18RAP (beta chain), please check PubMed=25500532 and PubMed=14528293.

Many thanks for your help,

Nevila Hyka-Nouspikel

**Comment by hdrabkin** [comment]
Hi @nnouspikel 
Can you be more specific? Review for what? 
The two papers you cite are for the human IL18RAP correct?

**Comment by hdrabkin** [comment]
So if these two terms refer to something that does not exist, I might need to obsolete them. I think the PMID used for these was somehow misread such that IL1B has mistaken for IL18

**Comment by hdrabkin** [comment]
I see there appear to be no annotations to either of these terms. I will put an obsoletion request in.

**Comment by hdrabkin** [comment]
The terms GO:0045093 and GO:00450934 were obsoleted 4/24/2018
