### ISSUE TITLE
NTR: vomitoxin biosynthetic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#15570]
There are GO terms available for biosynthetic processes of several individual mycotoxins. Can I request GO term for vomitoxin (deoxynivalenol) biosynthetic process?

Accession: GO:xxxxxx
Name: vomitoxin biosynthetic process
Ontology: biological_process
Synonyms: vomitoxin anabolism, vomitoxin biosynthesis, vomitoxin formation, vomitoxin synthesis, deoxynivalenol biosynthetic process, DON biosynthetic process
Definition: The chemical reactions and pathways resulting in the formation of type B trichothecene vomitoxin, a poisonous substance produced by some species of fungi and predominantly occurs in grains such as wheat, barley and oats.
is_a: GO:0043386 ! mycotoxin biosynthetic process
Source: CHEBI:10022, PMID:8637056, PMID:19333439, PMID:25680507, PMID:25758923, https://doi.org/10.1007/BF03356188, http://www.inchem.org/documents/jecfa/jecmono/v47je05.htm

**Comment by hdrabkin** [comment]
done

**Comment by Achchuthan** [comment]
Thanks @hdrabkin
