### ISSUE TITLE
Transcription factor activity, recruiting 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15577]
Following up on #15538 
I obsoleted many children of 'transcription factor activity, protein binding', but not the 'recruiting'. Here are the terms. I'll make a proposal about these soon. 

- Pascale

GO ID | Term   label | New label | Manual   EXP, NAS, TAS, RCA, IC | ISS,   ISO, ISA | Impacted groups
-- | -- | -- | -- | -- | --
GO:0001139 | transcription factor activity,   core RNA polymerase II recruiting' | RNA polymerase II complex recruiting activity | 8 | 2 | SGD (EXP, IC)
GO:0001134 | transcription factor activity,   transcription factor recruiting' | transcription factor recruiting activity | 2 | 2 | CAFA (2 EXP)
GO:0001135 | transcription factor activity,   transcription factor activity, RNA polymerase II transcription factor   recruiting | RNA polymerase II transcription factor recruiting activity, | 1 | 1 | SDG (mediator complex)
GO:0001186 | transcription factor activity, RNA   polymerase I transcription factor recruiting | RNA polymerase I transcription factor recruiting activity, | 4 | 0 | SGD SPT15
GO:0001011 | transcription factor activity, sequence-specific DNA binding, RNA polymerase recruiting |   3 | 2 |  BHF-UCL, RGD, FlyBase
GO:0001010 | transcription factor activity, sequence-specific DNA-binding transcription factor recruiting | RNA polymerase II sequence-specific DNA-binding transcription factor recruiting activity |  6 | 1  | SGD, BHF, UniProt

**Comment by pgaudet** [comment]
I will move these under just 'binding' (ie, recruiting is a specific type of binding). 

OK @krchristie @ValWood @RLovering ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
GO:0001139 | transcription factor activity, core RNA polymerase II recruiting' |
-> change label to transcription factor activity, RNA polymerase II complex recruiting'

**Comment by pgaudet** [comment]
Also, changed label of 'GO:0000993 RNA polymerase II core binding' to 'RNA polymerase II complex binding'

**Comment by ValWood** [comment]
I agree with the move.

Later we should look into defining  MF protein recruitment more formally and linking it to BP "protein localization"

There are lots of chromatin associated factors where the primary function is "recruitment" and the annotations for these are "all over the shop"

Can we talk about recruitment with the treancription experts on a future call?

**Comment by krchristie** [comment]
I don't disagree moving this under binding. My impression is that recruiting, at least in this context, has a more specific implication that if thing A is recruiting thing B, then thing A is already localized to a place to which it is thing bring thing B there too. Which seems consistent with Val's suggestion to align recruiting with localization.

**Comment by pgaudet** [comment]
Great, thanks for the feedback.
