### ISSUE TITLE
rearrange term names checkpoint signalling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15582]
can we switch terms like
signal transduction involved in mitotic G2 DNA damage checkpoint
to
mitotic G2 DNA damage checkpoint signalling?

**Comment by ukemi** [comment]
@krchristie, I seem to have lost the ability to assign people to tickets. Could you please claim this ticket and assign yourself?

**Comment by pgaudet** [comment]
I assigned myself as a test - can you take this ticket anyway?

**Comment by krchristie** [comment]
@ukemi - The specific term @ValWood would like to change the name of is an 'involved in' term. Do we allow these to be changed? We can always add Val's preferred name as a synonym.

**Comment by cmungall** [comment]
Related: I note that 'cell cycle checkpoint' is textually defined as "[...]ends with signal transduction"

yet there is no relationship to signal transduction.

I think there should be an 'ends_with' relationship. In RO, ends_with is a subproperty of part-of, for the case when the endpoint of the part matches the endpoint of the whole.

**Comment by ValWood** [comment]
@krchristie  
I'm suggesting this change because nobody refers to 
"signal transduction involved in mitotic G2 DNA damage checkpoint"
biologists call it "x checkpoint signalling", I don't really know why we have named them with "involved in"

..... it is a narrower part (the signalling part) of the checkpoint, so it will have a part_of relationship to the broader checkpoint term.

Lots of annotations to checkpoints involved  gene products which sense the damage, or localize the checkpoint  signalling components (etc) or are required for the checkpoint to occur, and are not part of the signalling per se.

@cmungall  so the "signalling" is only part of the checkpoint, and only this part should have a connection to "signal transduction"

Checkpoints are the part of the cell cycle terms which still need some work.
I wasn't planning to address this here but I know it needs to be done...there are *lots* of dodgy annotations in the checkpoint area.  When this is addressed it should  be quite easy to refine the terms generally and  standardize the definitions with starts and ends.

A cell cycle checkpoint that acts during *blah* and prevents *blah* until *blah*, thereby ensuring *blah*. An *blah* checkpoint begins when blah is sensed and *blah* is recruited  to initiate checkpoint signalling and ends when effector molecules for the "response to x checkpoint* are phosphorylated.

The problem is that we don't always  yet know  the  precise events which happen above the signalling pathway in sensing and recruitment (i.e. exact beginning), this is still an active area of research. We could  more easily define the signalling part.

This also reminds me that I wrote some checkpoint annotation guidelines and presented on a call once (the gist was that things mutants that cause problem that activate a checkpoint should not be annotated to the checkpoint). The used to be on the wiki but I can't find them. They were supposed to be added  as annotation comments on the terms, but the comment does not seem to be on any terms, and I can't find the ticket (open or closed). It would be useful to locate and add this because it would help to prevent  more problem annotations being added until there is chance to refine the branch.

**Comment by ValWood** [comment]
@cmungall  maight make it clearer:
![20180418_092327_resized](https://user-images.githubusercontent.com/7359272/38920100-6548cb56-42ea-11e8-9035-ffd8114539f6.jpg)

the signalling negatively regulates the cell cycle transition.
This needs to be a separate part_of the checkpoint, and the only term related to "regulation of the transition". This is because we don't want the proteins involved in sensing  damage and recruiting checkpoints  annotated to "negative regulation of cell cycle transition". Biologists would find this odd, as this is really a  collection of "signalling pathways" converging on cdc2

like so:
![cdc18](https://user-images.githubusercontent.com/7359272/38920513-550764ea-42eb-11e8-859e-7e5591feb8d4.jpg)

Here we are pulling cdc18 and orc1 into the cell cycle control network because the ancestry goes from the "checkpoint term" to "regulation of the transition" rather than from the 
"signalling" term.

**Comment by pgaudet** [comment]
Hi @krchristie 

@ValWood 's suggestion seems to better describe the biology. We use 'involved in' in at least two different ways in GO, (1) terms where we would use part_of in GO-CAM models, for eg: DNA synthesis involved in DNA repair, (2) netrin receptor activity involved in chemoattraction (where we would use 'involved in' in GO-CAM models). 

The term 'signal transduction involved in mitotic G2 DNA damage checkpoint' suggests we are connecting two different pathways, but if I understand Val's request, this is not the case, we are talking about a specific signaling pathway, so the name should reflect this. 

Is this right Val ? 

Thanks, Pascale

**Comment by ValWood** [comment]
> Is this right Val ?
yes.

**Comment by cmungall** [comment]
> We use 'involved in' in at least two different ways in GO, (1) terms where we would use part_of in GO-CAM models, for eg: DNA synthesis involved in DNA repair, (2) netrin receptor activity involved in chemoattraction (where we would use 'involved in' in GO-CAM models)

Yes, exactly. I think we should get rid of the *nomenclature* "involved in" in the pre-composed P-and-part-of-W classes in the ontology, across the board (which is compatible with having more specific nomenclature just for classes following a checkpoint signaling pattern). The use of "involved in" is obviously confusing to us. And it's just not consistent with the axioms in the ontology and GO-CAMs, where we clearly use part-of. 

Minor quibble: we would still use part-of in a GO-CAM for 2, I think you mean the gene product would be involved in chemoattraction.

**Comment by cmungall** [comment]
@ValWood thanks for your diagram. I think it's consistent with my suggestion to add an ends-with axiom as I have done [in this open pull request](https://github.com/geneontology/go-ontology/pull/15596).

I find it helps to draw partonomies with lines depicting points in time, so we can be precise about when a process starts and when it ends. **This will be increasingly important for consistent GO-CAMs, and for getting consistent gene sets with classic annotations**.

Does this make sense:

![image](https://user-images.githubusercontent.com/50745/39159716-f2990b62-471b-11e8-9231-b230cccca469.png)

The cloud indicates imprecision about a temporal boundary

**Comment by vanaukenk** [comment]
@ValWood 
Is this the meeting where you presented the annotation guidelines:
http://wiki.geneontology.org/index.php/Annotation_Call_December_9,_2014#Checkpoint_terms_guidelines

**Comment by ValWood** [comment]
@vanaukenk  yes, Midori found it ;)
https://github.com/geneontology/go-ontology/issues/15598
I'm  remember putting them on the cell cycle wiki though, and that I can't find.....

**Comment by cmungall** [comment]
ah ok, if the sensing is part of the checkpoint I think this one is more accurate, I made the part-of more explicit

![image](https://user-images.githubusercontent.com/50745/39200330-bccce2f8-47a0-11e8-8a30-1f88b826d6d5.png)

**Comment by ValWood** [comment]
I think that is correct (at least from the pombe viewpoint- I asked a few  checkpoint researchers when I was doing this,  some reviewed the lists, and I since had feedback that the enrichments work better for fission yeast in this area when they work on multiple species).  We *still* struggle with the annotations in this area though!

**Comment by ValWood** [comment]
This is out of date. 
sensing is the first step in signalling, and will move to MF
recruitment is really part of signalling too because it is modification dependent.

The signalling parentage and term names will be addressed by
https://github.com/geneontology/go-ontology/issues/20935
