### ISSUE TITLE
find checkpoint  annotation guidelines

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15598]
Need to add comments to checkpoint  terms to prevent their use for  mutants that cause "checkpoint activation".
Track down the text.  from
https://github.com/geneontology/go-ontology/issues/15582#issuecomment-382304319

**Comment by ValWood** [comment]
@mah11  found this in the agenda of
http://wiki.geneontology.org/index.php/Annotation_Call_December_9,_2014


Checkpoint terms guidelines
Annotation to checkpoint terms is based partly on a priori knowledge that certain problems encountered by the cell lead to cell cycle arrest that is, at least in principle, reversible (provided that the problem encountered can be fixed). A checkpoint pathway comprises sensors which detect the problem, and signalling and effector molecules which function to negatively regulate a specific cell cycle transition.

Gene products should not be annotated to checkpoint terms based on mutations that result in activation of the checkpoint (i.e, cause cell cycle arrest). Such mutations cause a problem which is detected by the checkpoint sensor, and cell cycle arrest indicates that the checkpoint is functioning normally. This does not represent positive regulation of the checkpoint. The mutated gene itself is not necessarily part of the checkpoint in a normal cell (although some gene products are involved in both a cell cycle process and in a related checkpoint). For example, DNA replication defects due to mutations can result in DNA damage or stalled and collapsed replication forks, which can be recognised by a checkpoint sensor, but most gene products involved in DNA replication are not involved in the checkpoint. [add note about exception as an example?]

Gene products can be annotated to checkpoint terms when a mutation results in inactivation of the checkpoint. Such gene products may be the sensor (the first component of a checkpoint) or any component of the signalling pathway to the effector. Compromising the checkpoint means that mutations which would normally halt the cell cycle no longer do so.

Genes which are involved in correcting the problems detected by the checkpoint (e.g. DNA damage, spindle assembly defects) should not be annotated to the checkpoint terms, because they act downstream of the checkpoint itself. These genes should instead be annotated to "response to checkpoint x" terms, which are in a separate branch of the ontology.

Since I can't track the actual comments that were supposed to be added I'll  construct something based on the above  for editing and inclusion.

**Comment by ValWood** [comment]
OK, I reduced to 

Gene products should not be annotated to checkpoint terms based on mutations that result in activation of the checkpoint (i.e, cause cell cycle arrest). Such mutations cause a problem which is detected by the checkpoint sensor, and cell cycle arrest indicates that the checkpoint is functioning normally. This does not represent positive regulation of the checkpoint since the mutated gene  is not necessarily part of the checkpoint in a normal cell. Gene products can be annotated to checkpoint terms when a mutation results in inactivation of the checkpoint. This includes, recruiting the checkpoint signalling components, part of the sensor machinery detecting the damage, or any component of the signalling pathway to the effector. 
Genes which are involved in correcting the problems detected by the checkpoint  should also not be annotated to the checkpoint terms, because they act downstream of the checkpoint. These genes should instead be annotated to "response to checkpoint x" terms, which are in a separate branch of the ontology.


It is still quite a long comment because it describes 2 major sources of checkpoint annotation errors, and the   interpretation of the experiment can be quite subtle in some cases if you don't look at checkpoint related paper a lot.....

This comment, or some variation  of it should be added to every term in the checkpoint branch which is available for  direct annotation.

we could shorten it by omitting the part about when the terms CAN be used
"Gene products can be annotated to checkpoint terms when a mutation results in inactivation of the checkpoint. This includes, recruiting the checkpoint signalling components, part of the sensor machinery detecting the damage, or any component of the signalling pathway to the effector. "

**Comment by ValWood** [comment]
@pgaudet 
It  might be better if  "comments" (useful to everyone)  could be separated from "annotation guidelines" (for curators)

**Comment by pgaudet** [comment]
Yes ! @cmungall is supposed to implement new fields in the GO file - Chis what do we need to do to make that happen ?

**Comment by ValWood** [comment]
@vanaukenk

**Comment by pgaudet** [comment]
@ValWood I added this to the wiki for now: 

http://wiki.geneontology.org/index.php/Guidelines_for_checkpoints

OK ?

**Comment by ValWood** [comment]
OK but it would be great longer term if curators could see this at annotation time. It's quite a large source of  annotation errors in the  cell cycle branch. I will look at these some point  when  pick up the matrix project again (in about a month). If there are still a lot of errors I will try to reduce the comment further so that it can be added as an annotation comment.

What is stopping it being added as a comment to checkpoint terms, is it too long? 
Or are we waiting until we can add annotation comments separately from general comments?
