### ISSUE TITLE
GO:0022850 serotonin-gated cation-selective channel activity - update comment

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#15595]
Currently:

Comments:
Note that this term represents an activity and not a gene product. Consider also annotating to the molecular function term 'serotonin receptor activity ; GO:0004993'.

Change to

Comments:
Note that this term represents an activity and not a gene product. Consider also annotating to the molecular function term '**G-protein coupled** serotonin receptor activity ; GO:0004993'.

because the name for GO:0004993 got updated :)

Birgit

**Comment by hdrabkin** [comment]
done did
