### ISSUE TITLE
NTR: acidocalcisome organization

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#15609]
Accession: GO:xxxxxx
Name: acidocalcisome organization
Ontology: biological_process
Synonyms: acidocalcisome organisation, acidocalcisome biogenesis, acidocalcisome organization and biogenesis, metachromatic granule organization, volutin granule organization, polyphosphate vacuole organization
Definition: A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of an acidocalcisome. An acidocalcisome is an electron-dense acidic membrane-bounded organelle which contains a matrix of pyrophosphate and polyphosphates with bound calcium and other cations.
is_a: GO:0006996 ! organelle organization
Source: GO:0020022, PMID:25964650, PMID:26523947

**Comment by hdrabkin** [comment]
GO:0106117; GO:0020022 uses to assign exact vs related synonyms.

**Comment by Achchuthan** [comment]
Thanks a lot @hdrabkin
