### ISSUE TITLE
GO:0000155 - phosphorelay sensor kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15613]
is classed as a 
signaling receptor activity
is  that correct?

**Comment by pgaudet** [comment]
Ah! I guess, in the sense that it receives a signal??

This seems incorrect @thomaspd what do you think?

**Comment by ValWood** [comment]
It's kind of weird because it isn't at the top of the pathway. Using this logic any kinase would be a receptor.
It acts as a "sensor" but I don't think this should be classed as a "receptor" should it.
I don't fully understand "response regulators" though.
 https://en.wikipedia.org/wiki/Response_regulator

**Comment by pgaudet** [comment]
Many of the sensors are TM, hence 'receptors' (I am not sure this applies to ALL, though) 

![image](https://user-images.githubusercontent.com/4782928/38996681-064158fa-43ec-11e8-96b6-66b253946afe.png)

**Comment by ValWood** [comment]
Ah right. I don't think ours our @Antonialock 

But isn't this just 2 activities (i.e a multifunctional protein) combined into a single function term, in that case?

**Comment by pgaudet** [comment]
I ask Swiss-Prot curators for help.

**Comment by Antonialock** [comment]
I don't think the upstream regulators of pombe mak1/2/3 (the histidine kinases) are known. I wouldn't think of them as receptors, they are not TM?

I don't understand your proposed changes Pascale
I think these systems are slightly different in eukaryotes comapred to prokaryotes
In prokaryotes you have "true" two-component regulatory systems, but eukaryotic systems tend to be a bit more complicated (multistep phosphorelay, not just 2 components). 

in pombe we have annotated:
phosphorelay sensor kinase activity - mak1, mak2, mak3,
histidine phosphotransfer kinase activity - mpr1
phosphorelay response regulator activity - mcs4, prr1


e.g.
![screen shot 2018-04-27 at 11 32 48](https://user-images.githubusercontent.com/12727506/39358671-c686ce92-4a0e-11e8-9805-4e55b9a7063a.png)

**Comment by Antonialock** [comment]
and if you obsolete GO:0000156 phosphorelay response regulator activity, then what shouldw e annotate to instead (for the cases above?)

**Comment by Antonialock** [comment]
![screen shot 2018-04-27 at 11 43 10](https://user-images.githubusercontent.com/12727506/39359030-34b934b2-4a10-11e8-9c42-9e87b9b2649e.png)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3829895/

**Comment by pgaudet** [comment]
OK very good, we will keep all the terms - in the 4-component version of the cascade, the phosphorelay sensor kinase and histidine phosphotransfer kinase activities  are mediated by separate members of the pathway. 

Thanks @Antonialock

**Comment by pgaudet** [comment]
I would like to hear from @thomaspd about Val's original question: 
 is phosphorelay sensor kinase activity a signaling receptor activity? 
This fits the current definition of signaling receptor activity, "Receiving a signal and transmitting it in the cell to initiate a change in cell activity. A signal is a physical entity or change in state that is used to transfer information in order to trigger a response.", but is this too vast ? 

Thanks, Pascale

**Comment by tberardini** [comment]
I finally had time to look at this issue.  I agree with @Antonialock.  Thanks for keeping the terms.

**Comment by pgaudet** [comment]
@Antonialock 
I need a littte more help: 

the definition is "Catalysis of the phosphorylation of a histidine residue in response to detection of an extracellular signal such as a chemical ligand or change in environment, to initiate a change in cell state or activity. The two-component sensor is a histidine kinase that autophosphorylates a histidine residue in its active site. _The phosphate is then transferred to an aspartate residue in a downstream response regulator, to trigger a response_."

I think that last sentence describes the GO:0009927 histidine phosphotransfer kinase activity (which is why I thought of a merge initially); do you think we should specify that this may be a different activity(in the 4-component system)? 

Thanks, Pascale

**Comment by Antonialock** [comment]
So the phosphorelay sensor kinase (GO:0000155)
1. autophosphorylates
2. transfers the phosphate

 - in 2 component systems the phosphate is transferred to a response regulator (GO:0000156)
 - in 'multi' phosphorelay systems the histidine is first transferred to a GO:0000155, which passes it on to a response regulator

**Comment by Antonialock** [comment]
Ok, this just got a bit more complicated...

Looking at wikipedia there might be a case to make these two different things in terms of MFs? (I always thought of multistep phosphorelays as a more complicated version of 2component systems, but they actually look a bit different, at least according to wikipedia...).

2 component system
1. histidine kinase (HK) autophosphorylates on a histidine residue
2. the response regulator (RR) then catalyzes the transfer of the phosphoryl group from the HK to an aspartate residue on the response regulator's receiver domain

multistep phosphorelay
1. HK autophosphorylates on a histidine and transfers the phosphate to an internal receiver domain
2. a histidine phosphotransferase (hPt) receives the phosphate, and transfers it to an RR
there are two types of histidine phosphotransferases: a more common monomeric without catalytic activity that interacts with one RR (it's called a "shuttle") and a less common dimeric catalytic type 

assuming this is all true (it's from wikipedia....but I don't have time to dig deeper into it right now):

For 2 component systems:
-HK can be annotated to GO:0000155 phosphorelay sensor kinase activity (rename term to 2-component sensor kinase activity to avoid confusion?)
-Annotate RR to GO:0000156 but change the def to reflect that the RR catalyzes the transfer
(note: need to check that wikipedia isn't wrong about this)

for multistep phosphorelay systems
- annotate the histidine kinase to GO:new - multistep phosphorelay sensor kinase activity, and tweak the def to reflect that the phosphate is transferred to an internal receiver domain
- annotate the hPt to GO:0009927? - may need two terms? one for dimeric catalytic proteins and one for  noncatalytic monomeric proteins?
- Are these RRs orthogonal to the RRs in 2component systems? (need to check)

**Comment by pgaudet** [comment]
Hi @Antonialock 

I can see a case for making two processes; but shouldn't we just make two annotations to the proteins having both sensor kinase and and phosphotrasfer activities ? 

And regarding 
>  hPt to GO:0009927? - may need two terms? one for dimeric catalytic proteins and one for noncatalytic monomeric proteins?

I suggest we use 'contributes to' for the dimeric forms; we shouldn't create separate terms. 

What do you think ? 

Pascale

**Comment by Antonialock** [comment]
Sounds ok I think? 

I’m happy to annotate according to the excellent guidelines that accompany the terms :-P

**Comment by ValWood** [comment]
We can probably close this? 

phosphorelay sensor kinase activity
is no longer is_a receptor
