### ISSUE TITLE
NTR: cichorine biosynthetic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#15610]
There are GO terms available for biosynthetic processes of several individual mycotoxins/ secondary metabolites. Can I request GO term for cichorine biosynthetic process please?

Accession: GO:xxxxxx
Name: cichorine biosynthetic process
Ontology: biological_process
Synonyms: cichorine anabolism, cichorine biosynthesis, cichorine formation, cichorine synthesis
Definition: The chemical reactions and pathways resulting in the formation of cichorine, a secondary metabolite found in some species of fungi such as Aspergillus silvativus, Aspergillus nidulans and Alternaria cichorii.
is_a: GO:0043386 ! mycotoxin biosynthetic process
is_a: GO:0044550 ! secondary metabolite biosynthetic process
Source: CHEBI:64977, PMID:24244835

**Comment by Achchuthan** [comment]
Thanks a lot @ukemi

**Comment by vanaukenk** [comment]
Just FYI, I've created an entry for Ach in the users.yaml and his GOC xref is: GOC:ach.
Thx.
