### ISSUE TITLE
NTR: regulation terms for sterol biosynthetic process

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15614]
Hello,

Could I please have all the regulation terms for GO:0016126 sterol biosynthetic process.

For PMID:16459310.

Please add the references:
GOC:rph
GOC:BHF
GOC:BHF_miRNA

Thanks.

**Comment by hdrabkin** [comment]
GO:0106118 regulation term
GO:0106119 neg reg term
GO:0106120 pos reg term
