### ISSUE TITLE
Fungal NTRs: Perithecium development & Protoperithecium formation

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#15616]
Accession: GO:xxxxxx
Name: Perithecium development
Ontology: biological_process
Definition: The process whose specific outcome is the progression of a perithecium over time, from its formation to the mature structure. Peritheicum is a flask-shaped fruiting body of certain molds and ascomycetous fungi having a pore for the escape of spores. In the ascomycetous fungi such as _Neurospora crassa_ and _Sordaria macrospora_, these perithecia are formed in the sexual phase and they discharge ascospores through the ostiolum at the tip of the perithecial neck.
is_a: GO:0030582 ! reproductive fruiting body development
Source: BTO:0002164, PMID:125266, PMID:19547974, PMID:20739093, PMID:25311923, https://link.springer.com/chapter/10.1007/978-3-642-00286-1_2 

Accession: GO:xxxxxx
Name: Protoperithecium formation
Ontology: biological_process
Synonyms: Primordium formation
Definition: The process of producing fruiting body precursors, called protoperithecia. Protoperitheicium is a spherical structure that is formed in the sexual phase of ascomycetous fungi such as _Neurospora crassa_ and _Sordaria macrospora_. Protoperithecium is formed by the enveloping of ascogonia cells by sterile hyphae and it develops into perithecium.
Comment: Note that this term represents protoperithecium formation across homothallic and heterothallic species that do not have the same mechanism.
is_a: GO:0030582 ! reproductive fruiting body development
Source: PMID:125266, PMID:4410944, PMID:6235211, PMID:6235212, PMID:20739093, PMID:25311923, https://link.springer.com/chapter/10.1007/978-3-642-00286-1_2

**Comment by krchristie** [comment]
I have temporarily removed definition dbxrefs that were from BTO or were urls as they are violating a check for valid IDs in references:

 :: ERROR: valid-id-space: bad id space 'BTO' in xref BTO:0002164
 :: ERROR: valid-id-space: bad id space 'https' in xref https://link.springer.com/chapter/10.1007

@Achchuthan - Are these urls for DOI's? If so, then the appropriate format is like this:
> DOI:10.1078/0176-1617-00593

@cmungall - What is needed to allow a BTO ID as a definition dbxref? BTO is a valid OBO Foundry ontology. Here's the link for the relevent BTO term:
http://www.ontobee.org/ontology/BTO?iri=http://purl.obolibrary.org/obo/BTO_0002164

**Comment by krchristie** [comment]
reopening until BTO issue is resolved

**Comment by krchristie** [comment]
@cmungall - There's a pull request to add an entry for BTO to db-xrefs.yaml:
https://github.com/geneontology/go-site/pull/655

I'm not sure why it failed, or why I never saw an option to add you as a reviewer.

**Comment by krchristie** [comment]
Tried again (https://github.com/geneontology/go-ontology/pull/15842) to put in BTO reference:

but still getting this error:
` :: ERROR: valid-id-space: bad id space 'BTO' in xref BTO:0002164`

**Comment by cmungall** [comment]
sorry I missed this the first time round. Merged, but will take a day to percolate.

I propose as a general principle for development terms

 - we axiomatize using the appropriate ontology (FAO here)
 - we don't reference an ontology term in the development term def xref as this is redundant (but FAO may choose to reference a BTO term if it chooses)

**Comment by cmungall** [comment]
FAO request: https://github.com/obophenotype/fungal-anatomy-ontology/issues/19
Inquiry into status of FAO: https://github.com/obophenotype/fungal-anatomy-ontology/issues/18
