### ISSUE TITLE
Proposal to obsolete some catabolic processes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15636]
Dear all, 

The proposal has been made to obsolete 
GO:0044239   salivary polysaccharide catabolic process 
GO:0044251   protein catabolic process by pepsin

The reason for obsoletion is that these terms represent the location of a process (salivary polysaccharide catabolic process), which can be captured by the relation 'occurs in', and a specific gene product (protein catabolic process by pepsin), which should be captured as an annotation. 

There are no annotations and no mappings to those terms. 

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/15636

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on April 30, 2018. Unless objections are received by April 30, 2018, we will assume that you agree to this change.

Thanks, 

Pascale

**Comment by ValWood** [comment]
I agree these terms would go, but  the purpose was possibly partly to  differentiate the "extracellular catabolism during digestion"  as in:
https://github.com/geneontology/go-ontology/issues/14761

and distinguish it from endogenous protein breakdown...
