### ISSUE TITLE
New Term Request : Pipecolic Acid Biosynthesis

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#15634]
term: pipecolic acid biosynthesis
definition: The chemical reactions and pathways resulting in the synthesis of pipecolic acid (CHEBI:17964)from L-Lysine.

is a: antimicrobial peptide biosynthetic process (GO:0002777)
(maybe) is a: L-lysine catabolic process to acetyl-CoA via L-pipecolate (GO:0033514)

references:
https://doi.org/10.1104/pp.17.00222
https://doi.org/10.1105/tpc.16.00486

**Comment by ukemi** [comment]
Hi @lreiser,
I can choose the L enantiomer. Would that be more appropriate? Also not that it will be mapped to the ChEBI term for the conjugate base.

**Comment by lreiser** [comment]
sure. seems so.
CHEBI:26142

**Comment by ukemi** [comment]
I have added the term without a logical def for now. Once we have the ability to import the compound from chebi, I will modify it with the correct reference. 

Is it really an antimicrobial peptide? It is a single amino-acid derivative. For now I have just given it a chemical parent.

PMID:27758894 and PMID:28330936. ChEBI:30633.

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/pull/15653

**Comment by lreiser** [comment]
"Is it really an antimicrobial peptide? It is a single amino-acid derivative. For now I have just given it a chemical parent."

Yep you are right- bad choice there on my part

**Comment by ukemi** [comment]
I was just going to add this, but perhaps it is better to make a new request. I don't see N-hydroxypipecholate(ic acid) in ChEBI, so we will need to request it.
