### ISSUE TITLE
GO:0035178 turning behavior

### ISSUE THREAD

**Issue by sandyl27** [geneontology/go-ontology#15645]
Is this the same thing as spontaneous reversal? 

PMID:26054666

**Comment by ukemi** [comment]
I think this term was originally meant to be a locomotory response to a stimulus, like tapping the worm on the anterior end and it responding by backing up. I'm not sure it would cover the spontaneous forward and backward direction changes they exhibit. Do we know if these are controlled by the same genetic program? How spontaneous is the spontaneous behavior? Is it triggered by some kind of stimulus? @vanaukenk any ideas?

Assigning to you even though you are off the rota. If we need to add a term, go ahead and reassign this to me.

**Comment by vanaukenk** [comment]
Hi @sandyl27 
GO:0035178 'turning behavior' is not the same as spontaneous reversals, which are periods of brief, spontaneous backward locomotion.
Which gene products from PMID:26054666 do you want to annotate to a behavior term?  It looks as if the paper is showing a role for the TGFb signaling pathway in regulating the expression of a glutamate receptor GLR-1 that, in turn, positively regulates the frequency of backward locomotion.  This would be a nice GO-CAM model.

**Comment by sandyl27** [comment]
This is for CACAO and they were looking at annotating daf7.

**Comment by vanaukenk** [comment]
Thanks @sandyl27 
In this case, I think I would annotate the TGFb pathway members like daf-7 to 'negative regulation of gene expression' to capture the effects on glr-1 expression and then annotate glr-1 to 'positive regulation of backward locomotion'.  Does that make sense?
