### ISSUE TITLE
Division of thermoception into hot and cold perception

### ISSUE THREAD

**Issue by Clare72** [geneontology/go-ontology#15646]
I would like to suggest that "thermoception" be divided into "detection of hot stimulus" and "detection of cold stimulus".
These functions have been shown to be carried out by different neurons, for example [PMID 21335241](https://www.ncbi.nlm.nih.gov/pubmed/21335241)

**Comment by pgaudet** [comment]
Hi, 

A naive question: Are they mediated by different molecules ? We annotate gene products, not cells. 

Thanks, Pascale

**Comment by Clare72** [comment]
Yes, loss of function *brv* gene mutants lose cold-avoidance behaviour, but retain hot-avoidance (same reference).
