### ISSUE TITLE
problematic ontology commits in "conjugation with cellular fusion branch"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15641]
since early March the number of genes annotated to the "conjugation 
with cellular fusion" 

has oscillated between ~95 ~105
https://github.com/pombase/curation/issues/1901

even though we did not remove all of these. It seems that a parent keeps being removed and added back?

**Comment by hdrabkin** [comment]
Changes in inferences from logical defs? I see you flag a signal transduction term? any relations to MapKinases?

**Comment by ValWood** [comment]
this term is one of the problem,
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000750
but in QUICKGO the parentage is correct right now.
However in the ontology we picked up last nigh it was not there (QuickGO might be a bit behind).

Does everybodys obo file have this parent right now?
https://www.ebi.ac.uk/QuickGO/term/GO:0000747
right now?

**Comment by hdrabkin** [comment]
What I'm seeing in protege is GO:0000750 is part of some response to pheromone triggering conjugation with cellular fusion and is_a 'signal transduction involved in positive regulation of conjugation with cellular fusion'

**Comment by ValWood** [comment]
I guess I'll just need to see if it fixes itself again. @pgaudet  it would be good to touch on this in the editors call. I have a feeling somebodies ontology version is overwriting the changes, but I don't  know enough about how this might happen to be sure....

**Comment by pgaudet** [comment]
@ValWood 
 fab1 | SPBC3E7.01 | 1-phosphatidylinositol-3-phosphate 5-kinase Fab1
is annotated to 'pheromone-dependent signal transduction involved in conjugation with cellular fusion' - looks like it's fixed again ? 

We discussed this at the ontology call - it's really weird that this would fluctuate; where are you getting this data for ? 

Thanks, Pascale

**Comment by ValWood** [comment]
yes we are back at 108 now and the parent is present again.
https://www.pombase.org/term_genes/GO:0000747

@kimrutherford where do we get the GO ontology file from?

**Comment by hdrabkin** [comment]
We get ours from the same purl, loaded daily.

**Comment by ValWood** [comment]
ok I'll close this, and keep an eye on the totals in case it occurs again....

**Comment by pgaudet** [comment]
Thanks @ValWood 
If you could count daily for a little while that would help - otherwise it's really hard to trace the problem - too many commits. 

Pascale

**Comment by ValWood** [comment]
dropped from 108 to 101 over the weekend, no changes by us....

**Comment by ValWood** [comment]
problem seems to be

positive regulation of induction of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter

see for example
https://www.pombase.org/gene/SPCC4B3.08

no longer has conjugation parent

**Comment by pgaudet** [comment]
@ValWood  the term is obsolete, as far as I can tell - are you talking about GO:1990894?

**Comment by ValWood** [comment]
Oh yes, I don't know why we still have that ....will figure

**Comment by ValWood** [comment]
The term was this one...it still exists?
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1904788

**Comment by pgaudet** [comment]
yes it does ! Looks like it was forgotten (although if you still use it that means you need it ?)

**Comment by hdrabkin** [comment]
GO:1904788 is still there;
positive regulation of induction of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter
The other term GO:1990894 obsoleted because  during the TG review process.  It should have been created using a template.
positive regulation of induction of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter

Now, I notice that GO:1904788 has the following logical def
regulation of transcription by RNA polymerase II'
 and ('positively regulates' some 'induction of conjugation with cellular fusion'), and thus the reasoner infers  is_a 'positive regulation of induction of conjugation with cellular fusion.

**Comment by ValWood** [comment]
I guess we could post-compose these so they have an  explicit regulation of conjugation, but the induction of conjugation is directly transcriptionally regulated not post transcriptional.... 

....so if the reasoner is inferring the relationship  why does it keep getting removed?
..or is it never added.? I know sometimes we do see the correct inference to

"positive regulation of induction of conjugation with cellular fusion"
and sometime it disappears (like now)

**Comment by hdrabkin** [comment]
I am wondering if it is a problem on your end just because right now in a recent pull,  I can see it but you can't see it in your system.  FWIW, MGI has the 'positive regulation of induction of conjugation with cellular fusion', which means it is in go-basic.obo, which is what we load.

So I guess we might need the specifics as to when exactly you loaded the GO and from which purl, etc. to see if we can find a recent version that loses it in go-edit.obo?

**Comment by hdrabkin** [comment]
QuickGO also has the parent
positive regulation of induction of conjugation with cellular fusion.

**Comment by ValWood** [comment]
@kimrutherford 
@mah11 
do you know which version this is?/ from where?

**Comment by mah11** [comment]
> do you know which version this is?/ from where?

My favorite question again: what's "this"?

In case it's relevant: The go-basic we've loaded is identical to the one I got from the GO repository yesterday, and differs from the just-updated go-basic only in a couple of MF terms that appear to have no connection with conjugation. All the copies of go-basic I've looked at in the past quarter-hour have had paths from GO:1904788 to GO:0000747, via some regulates as well as is_a links.

**Comment by mah11** [comment]
No, I said the go-basic.obo we've loaded _does_ have connections between GO:1904788 and conjugation:

me earlier:
> All the copies of go-basic I've looked at in the past quarter-hour have paths from GO:1904788 to GO:0000747, via some regulates as well as is_a links.

**Comment by ValWood** [comment]
sorry that is what I meant "has links" (i changed my mind while typing, comment now edited).

So, it seems that the go-basic we are using and the main version are not the same?

**Comment by hdrabkin** [comment]
What do you mean by 'main version'?  go-basic has the links you are missing. So does the main version
See:
http://www.geneontology.org/page/download-ontology
go-basic.obo does not have 'has_part' or 'occurs_in', which in this case, doesn't matter for what you are seeing or not. 
And it sounds like Midori is saying that the version pombe is using DOES have the connections between the two terms.

**Comment by hdrabkin** [comment]
The links between the two terms  are also in go.obo

**Comment by ValWood** [comment]
OK got it, sorry! We'll need to figure out why we don't see them locally...strange...

**Comment by mah11** [comment]
> So, it seems that the go-basic we are using and the main version are not the same?

Incorrect; they've been the same.
