### ISSUE TITLE
Fungal NTR: Vegetative mycelium formation

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#15640]
There are GO terms available for hyphal growth (GO:0030448), the parent term and for aerial mycelium formation/ aerial hyphal growth (GO:0097736), another distinct biological process in Fungi. I am wondering whether a new term could be created for vegetative mycelium formation/ basal hyphal growth please?

The definition is given below:

Accession: GO:xxxxxx
Name: vegetative mycelium formation
Ontology: biological_process
Synonyms: basal hyphal growth
Definition: The process of hyphal growth that is characterised by apical extension, branching, and fusion of basal hyphae to form a colony on and in the superficial layer of substrate in order to reach out for nutrients. The rate of growth of basal hyphae can be measured by race tube assays (e.g. inoculating Neurospora crassa on one end of long glass tubes containing a layer of substrate and measure basal hyphal extension over time).
Comment: Basal hyphae are not synonymous with aerial hyphae and are distinct phases of growth.
is_a: GO:0030448 ! hyphal growth
Source: PMID:16801547, PMID:21643041, ISBN:1908230126, http://newprairiepress.org/fgr/vol50/iss1/8/

Thanks & best wishes,
Achchuthan

**Comment by krchristie** [comment]
I do see the two terms you refer to, though note that the term "hyphal growth" (GO:0030448) is NOT a parent term of "aerial mycelium formation" (GO:0097736) in GO. There does not appear to be any relationship within the ontology between the two terms:

> [Term]
> id: GO:0030448
> name: hyphal growth
> namespace: biological_process
> def: "Growth of fungi as threadlike, tubular structures that may contain multiple nuclei and may or may not be divided internally by septa, or cross-walls." [GOC:mcc, ISBN:0471522295]
> subset: goslim_candida
> is_a: GO:0030447 ! filamentous growth
> intersection_of: GO:0040007 ! growth
> intersection_of: results_in_growth_of FAO:0001001 ! hypha
> 
> [Term]
> id: GO:0097736
> name: aerial mycelium formation
> namespace: biological_process
> def: "The process by which hyphae grow in an upward or outward direction from the surface of the substrate; from there, propagative spores develop in or on characteristic structures that are distinctive of some fungal and bacterial species. The spe\
> cies that form an aerial mycelium develop conidiophores at the ends of the aerial hyphae." [GOC:di, PMID:12832397]
> synonym: "aerial hyphal growth" RELATED []
> synonym: "fertile mycelium formation" RELATED []
> is_a: GO:0019954 ! asexual reproduction
> is_a: GO:0048856 ! anatomical structure development
> relationship: only_in_taxon NCBITaxon_Union:0000020
> created_by: paola
> creation_date: 2016-10-14T14:25:22Z

Also note that there are a couple outstanding issues relating to various types of fungal filamentous growth:

 Clarify diff between 'hyphal growth' and 'filamentous growth' #13157 
 Pseudohyphal growth definition is S. cerevisie-specific #13164 

Tagging @srengel @dianeoinglis - to keep you posted of another ticket related to hyphal growth.

**Comment by ValWood** [comment]
@pgaudet  I think you could close this, as  Ach is no longer workingat FungiDB  there seems to be no replacement fungal curator. We should probably not add terms if they are not going to be used immediately since ongoing work may change how  terms like "growth nodes" are eventually modelled (they seem to be a bit mixed up between growth and morphology).

**Comment by pgaudet** [comment]
OK, thanks for the feedback.
