### ISSUE TITLE
non homologous end joining 

### ISSUE THREAD

**Issue by sandyl27** [geneontology/go-ontology#15644]
should there be new terms or synonyms for fidelity and efficiency? 

ex. PMID:29227966
POT1 inhibits the efficiency but promotes the fidelity of nonhomologous end joining at non-telomeric DNA regions.

**Comment by ValWood** [comment]
Are these different processes though? Isn't this just a type of regulation?

**Comment by ValWood** [comment]
hmm that would be a problem because it would be +ve and -ve regulation simultaneously.
it seems to be regulation of a specific sub-pathway choice...

**Comment by hdrabkin** [comment]
Can you formulate a concrete action item? Is this to make regulation terms for 'non homologous end joining"? I don't see even this term? 
I see we have 'regulation of protection from non-homologous end joining at telomere' ??
Please make this clear.

**Comment by sandyl27** [comment]
There is a term in quickGO GO:0006303 double-strand break repair via nonhomologous end joining, and it has regulation terms.

**Comment by sandyl27** [comment]
There is a term in quickGO GO:0006303 double-strand break repair via nonhomologous end joining. 
@jimhu-tamu

**Comment by hdrabkin** [comment]
I would think the regulation terms cover efficiency and fidelity (Any process that modulates the frequency, rate or extent of [process]), no?

**Comment by ValWood** [comment]
Closing.
