### ISSUE TITLE
consider:obsolete term id situations  AND alt_ids

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15654]
Similar to #15429
We need a check that look up obsolete terms in the 'consider' and alt_id fields. 

Right now 'consider' fails at the ontology building step (not sure what happens with alt_ids but this should also be picked up by Travis checks). 
http://build.berkeleybop.org/job/release-go-to-svn/644/console

Thanks, Pascale

**Comment by balhoff** [comment]
I think this is in place now: https://github.com/geneontology/go-ontology/blob/master/src/sparql/replacedby-obsolete-violation.sparql

**Comment by pgaudet** [comment]
Thanks !
