### ISSUE TITLE
NTR: positive regulation of cobalamin metabolic process

### ISSUE THREAD

**Issue by sandyl27** [geneontology/go-ontology#15659]
positive regulation of cobalamin metabolic process

Definition: Any process that increases the frequency, rate or extent of the chemical reactions and pathways involving cobalamin (vitamin B12), a water-soluble vitamin characterized by possession of a corrin nucleus containing a cobalt atom. 

Parent: GO:0106064 regulation of cobalamin metabolic process

**Comment by hdrabkin** [comment]
Using the PMID for parent term. Please supply reference def for use?

**Comment by sandyl27** [comment]
PMID:29056341

**Comment by hdrabkin** [comment]
ok, same ref as parent term fine
