### ISSUE TITLE
NTR: calcium-dependent carbohydrate binding

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#15662]
Hi,
Q9BWP8/COLEC11 binds glycans in a calcium-dependent manner according to PubMed=25912189. I have also found calcium-dependent protein binding/GO:0048306. Would not it make sense to have such a child term for carbohydrate binding/GO:0030246.
Thanks for considering my question.
Lionel

**Comment by krchristie** [comment]
Makes sense to me too. I've added a term. Thanks for the suggestion @lbreuza
