### ISSUE TITLE
NTR: calcium-dependent dynein outer arm binding

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#15668]
From HJD's reviewi of our annotations using colocalizes to any protein complex and child (see ticket https://github.com/geneontology/go-annotation/issues/1940)
For Efcab1, there was an ISO _colocalizes_with_ **outer dynein arm** via PMID:18620543

To capture the intent of this annotation, a new binding term is required for:
**calcium-dependent dynein outer arm binding**

The new annotation will be mouse Efcab1 by ISO with UniProtKB:Q8T893, citing PMID:18620543|IDA as the original experimental evidence.

**Comment by ValWood** [comment]
Hi Karen,

I thought we weren't adding new GP specific binding terms ?

Val

**Comment by krchristie** [comment]
Hi @ValWood - This isn't a single GP, it's a structure composed of a complex.

**Comment by ValWood** [comment]
Ah right I thought the outer arm was a single subunit but that's a complex in itself.. got it...

**Comment by krchristie** [comment]
Hey @ukemi & @cmungall 

I notice that some of the children of 'protein binding' have equivalence axioms like this one:

"14-3-3 protein binding" (GO:0071889)
Equivalent to: `

> binding
>  and ('has input' some '14-3-3 protein')

I've just added a couple terms for types of 'calcium-dependent binding', so I am wondering if there is anything I could add to make equivalence axioms for these new terms, e.g.:

> binding
>  and ('has input' some 'outer dynein arm') 
>  and ??? requires calcium ???
> 
>

**Comment by ukemi** [comment]
Does it really buy us anything if we don't have an exhaustive representation of calcium-required activities?

**Comment by krchristie** [comment]
Not now, but perhaps in the future.

**Comment by krchristie** [comment]
'has necessary participant' is not an option in Protege

These two relationships are the closest, in terms of wording:
- 'has necessary component activity'
- 'has participant'

but neither seems correct.

@cmungall - Do you know if there is a way to specify this type of thing, in this case, the fact that calcium is necessary for the binding?

**Comment by krchristie** [comment]
7/15/19 - We discussed this ticket at the Editors call and Pascal suggested using `has_part some 'calcium ion binding'`

However, having looked at what we do in other places and what terms we have, I am still not sure what would be the appropriate solution.

We have some MF terms that have equivalence axioms like this one:
**term name**: calcium ion sequestering activity
`'molecular sequestering activity' and ('has part' some 'calcium ion binding')`

However, to do that for the term, "**calcium-dependent dynein outer arm binding**," I would need to have a term for just "**dynein outer arm binding**", which does not currently exist.

Currently, we have this structure:
> -- protein binding
--- calcium-dependent protein binding
---- calcium-dependent dynein outer arm binding

I see that neither the equivalence axiom or any of its subclass relationships of the term "**calcium-dependent protein binding**" specify anything about calcium binding. For this term, it seems that this equivalence axiom would be true:
`'protein binding' and ('has part' some 'calcium ion binding')`

However, I am not sure if the 'has part' some 'calcium ion binding' would propagate to the child term to solve my issue.

So, I am not sure what is an appropriate and effective solution.

**Comment by pgaudet** [comment]
Just wondering, is 'dynein outer arm binding' always calcium-dependent ?

**Comment by pgaudet** [comment]
(to decide whether we need both terms).

**Comment by ukemi** [comment]
@krchristie, I think you have already come up with an appropriate solution. I think the original hesitation might have been about the nature of calcium dependency. We used to be very conservative about things like that. If there was a chance that the function was calcium dependent, but did not require binding, we shied away or we would have made the term something like 'calcium binding dependent protein binding'. If you look at the object properties in Protege, you will see that 'has part' is declared as being transitive, so it will be inherited.

**Comment by krchristie** [comment]
At the current time, I have only needed the "**calcium-dependent outer dynein arm binding**". It wouldn't surprise me if there is non-calcium dependent binding too, though I do not currently need "**outer dynein arm binding**" for annotation, so I had not wanted to create a term that I don't need for annotation.

For the moment, since @ukemi says that the has_part is transitive, I think that creating the equivalence axiom `'protein binding' and ('has part' some 'calcium ion binding')` for the term "calcium-dependent protein binding" will be sufficient. But if either of you think that I should create the term "**outer dynein arm binding**" so that I can make an equivalence axiom for "**calcium-dependent outer dynein arm binding**", I''m not opposed to doing that also.
