### ISSUE TITLE
NTR: Negative regulation of ERBB4 signaling pathway

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#15661]
Hi, 

New term requested: Negative regulation of ERBB4 signaling pathway
Definition: Any process that stops, prevents or reduces the frequency, rate or extent of ERBB4 signaling pathway

The request is supported by Figure 5 in PMID: 15219672 . They show that ACPT selectively
regulates the ErbB4 tyrosine kinase pathway.

Parent terms: 
GO:1901185- negative regulation of ERBB signaling pathway
GO:0038130 - ERBB4 signaling pathway

There is already a term, as specific as the one we are requesting, for another ERBB protein (GO:1905578-regulation of ERBB3 signaling pathway).

Thanks,
Mila

**Comment by ukemi** [comment]
@pgaudet and @thomaspd, I'm tagging this for editor's discussion. Do we want to go this route for all pathways?

**Comment by pgaudet** [comment]
Hi @krchristie 


For the paper that @milarolo wants to annotate, the paper does state that "ACPT (...)  selectively
regulates the ErbB4 tyrosine kinase pathway", and Fig 5 shows that ACPT acts as a tyrosine phosphatase to modulate signals mediated by ErbB4, so I suppose adding the regulation terms is OK. 


----

However this branch needs some work: I just chatted with our kinase expert, Jonas Cicenas. He did his thesis on ERBB2. He describe the pathways in his thesis, starting on page 21: https://edoc.unibas.ch/489/1/DissB_7661.pdf

As far as I understand, multiple ligands activate one or more receptor (Fig 4 pasted below), and these can in turn activate: 
- Ras/MAPK pathway
- PI3K/Akt pathway
- PLCgamma pathway 
- Src
- JAK/STAT

<img width="612" alt="image" src="https://user-images.githubusercontent.com/4782928/39467299-a0113c4e-4d2d-11e8-9beb-93470b08f341.png">

See also PMID: 29494066 "Ten different ligands can selectively bind to each receptor, and ligand binding leads to downstream pathways involved in cellular growth and proliferation as well as differentiation" 

PMID:28791631 "ErbB signaling networks consist of several modules that are interconnected and overlapping. By regulating these signaling networks, ErbB receptors govern fundamental cellular processes, including proliferation, cell migration , metabolism, and survival. The activated ErbB receptors (homodimers and heterodimers ) form signaling complexes with many signaling proteins, as described above. The formation of the receptor-signaling protein complexes then initiates the activation of various signaling pathways , including Ras /ERK, PI3K /Ak t, PLC-γ1, Sr c, and STAT" 

I am not sure how one would tell which "pathway" you are really looking at. We need to define these better (possibly ligand/receptor combinations???? 


Pascale

**Comment by krchristie** [comment]
Hi @pgaudet - Thanks for checking into this!

I'll just make the term as requested so that @milarolo can capture what was shown.
