### ISSUE TITLE
NTR: MIH complex

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#15675]
Hi,

I would like to propose the following complex term be added to the component ontology as an instance of protein containing complex (GO:0032991) and a child term of cellular bud neck (GO:0005935).

Term: MIH complex

Definition: A trimeric complex involved in cytokinesis. Proposed to bridge actomyosin ring contraction and septum synthesis in yeast, resulting in the coordination of these processes, and leading to plasma membrane ingression and fusion.  In the yeast Saccharomyces cerevisiae this complex consists of Mlc1p, Iqg1p and Hof1p proteins.

Synonyms: Mlc1p–Iqg1p–Hof1p complex

Definition_references:

PMID: 24895401
PMID: 24413167

Cheers,
Rob

**Comment by bmeldal** [comment]
Nice, new to the complex portal, too!
@sandraorchard

**Comment by robnash** [comment]
Great, this has been around for a while but missed. I also posted a request for the Aim21-Tda2 complex which is new (https://github.com/geneontology/go-ontology/issues/15329) but has yet to be added in GO.

Cheers,
Rob
