### ISSUE TITLE
Are GO:0102005 and GO:0043333 the same?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15686]
@drabkin. These are being flagged by @dougli1sqrd 's new check to be sure that exact synonyms don't match term names. Can you check to see if these are the same activity? If they are could you merge them? If they are not, can you remove or adjust the synonym on GO:0043333?

**Comment by hdrabkin** [comment]
I will have Peifen comment

**Comment by hdrabkin** [comment]
I will adjust the synonym now; have not heard back.

**Comment by hdrabkin** [comment]
Of course, now I get an email that they are the same. So opening ticket up until the successful merge

**Comment by hdrabkin** [comment]
done; closing again
