### ISSUE TITLE
All terms below "centrosome cycle"  should be taxonomically restricted for fungi

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15685]
centrosome cycle
https://www.ebi.ac.uk/QuickGO/term/GO:0007098

has
GO:0007098 | centrosome cycle | Never in Taxon | 4751 | Fungi

but the descendant 
GO:0046604    positive regulation of mitotic centrosome separation
does not, and we are getting PAINT mappings for this.

All terms below "centrosome cycle" should be taxonomically restricted for fungi (unless we decide to combine the orthologous structures of "centrosome" and "spindle pole body" in GO (some authors do not refer to the SPB as the centrosome). However ups to now we have annotated to mutually exclusive branches following a more "traditional" view.

A merging of these branches would be quite a lot of work, and while they are separated in this way, centrosome terms should all be unavailable for fungal annotations.....

**Comment by ValWood** [comment]
also 
regulation of cell migration
should have the same taxon restrictions for dikarya as the parent terms

**Comment by mah11** [comment]
hmm, I thought never_in_taxon and only_in_taxon were supposed to propagate "down" via transitive relations already, so I guess the issue is to propagate over regulates as well?

(or does that also already happen? ... which would make this another PAINT problem)

**Comment by ValWood** [comment]
> hmm, I thought never_in_taxon and only_in_taxon were supposed to propagate "down" via transitive relations already,

well they used to, but they don't any longer -apparently because of the "regulation via another organism" stuff which is now allowed. I don't think that pathogens should use the same terms as the hosts, they aren't  regulating the same processes. It was *much* better when pathogen terms were in an independent branch IMHO.....

**Comment by pgaudet** [comment]
Hi @ValWood 

The taxon constraints *are* propagated down (in principle). However there are problems with the implementations of taxon constraints for PAINT annotations. I'm marking this 'Rules' to check with @dougli1sqrd or @cmungall 
Pascale

**Comment by cmungall** [comment]
sorry, not sure what the action required here is

**Comment by pgaudet** [comment]
@cmungall Where can we look at taxon constraints error reports ?

**Comment by ValWood** [comment]
taxon checks are not currently implemented:
https://github.com/geneontology/go-annotation/issues/1928

but, when they are,
GO:0046604 positive regulation of mitotic centrosome separation
is not taxonomically restricted, even though the parent GO:0007098  centrosome cycle is.

**Comment by pgaudet** [comment]
This seems to be still a problem with the PAINT annotation imports - 

centrosome cycle
https://www.ebi.ac.uk/QuickGO/term/GO:0007098

is not annotated according to Pantree: 
http://www.pantree.org/node/annotationNode.jsp?id=PTN001061464

@dustine32 is this anywhere in the files exported by the PAINT pipeline ?

**Comment by ValWood** [comment]
centrosome cycle was supposed to merge into centrosome organiszation?
https://github.com/geneontology/go-ontology/issues/13247

**Comment by pgaudet** [comment]
Species annotated are non-MOD species; so it's probably related to this: 
https://github.com/geneontology/amigo/issues/533

**Comment by dustine32** [comment]
@pgaudet Looks like it is related to the old PAINT _other.gaf issue https://github.com/geneontology/amigo/issues/533. Checking the last few months worth of "_other.gaf" files submitted by PAINT, I can't find any lines at all for GO:0046604. However, the GO:0046604 IBAs shown in amigo do appear in this GAF:
http://www.geneontology.org/gene-associations/submission/paint/pre-submission/gene_association.paint_other.gaf

**Comment by pgaudet** [comment]
Hi @dustine32 

Is PAINT now filtering out the annotations that fail taxon constraints ? (It doesn't look like it - for example http://amigo.geneontology.org/amigo/gene_product/UniProtKB:A0A0D1DU59 (UMAG_03898) should *not* have an annotation to GO:0010824 regulation of centrosome duplication. 

Can you please let me know where we stand with respect to filtering these annotations? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Although - do taxon constraints propagate down 'regulation'? 
@cmungall @dougli1sqrd

**Comment by pgaudet** [comment]
@ukemi do you know if taxon constraints propagate down 'regulation'?

**Comment by ukemi** [comment]
I don't believe they do. If they do, I don't think they should. It is possible for one organism to regulate a process in another organism even if the target process is restricted. I thought we had this discussion previously.

**Comment by pgaudet** [comment]
Good to know ! I'll add it for these terms.
