### ISSUE TITLE
ntr protein localization to plasma membrane of cell tip

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15689]
def: A process in which a protein is transported to, or maintained in, a specific location at the plasma membrane of cell tip

child of
GO:0072659
and
GO:0072659    protein localization to cell tip

ref
PMID:27852900

**Comment by ukemi** [comment]
@dougli1sqrd, I'm adding you to this because this is one of the tickets we will do together on this BioFriday.

**Comment by ukemi** [comment]
Hi @ValWood 
Is this protein localization or the localization of phosphatidyl serine?

**Comment by ValWood** [comment]
It's protein localization. The pps1 regulates the localization of  rho1 and cdc42 by controling PM phosphatidyl serine composition (I need the +ve regulation term)
