### ISSUE TITLE
New molecular function terms

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#15683]
Related to 
#15634 
Per  the author

1 . Term Name:  L-Lysine alpha-aminotransferase (e.g. Arabidopsis ALD1)
Definition: Catalyzes the reaction: L-lysine + pyruvate= epsilon-amino-alpha-ketocaproic acid (KAC) + alanine
is_a:GO:0008483

2. Term Name: dehydropipecolic acid reductase (e.g. Arabidopsis SARD4) 
Defintion: Catalyzes the reaction: dehydropipecolic acid + NAD(P)H + H+ = L-pipecolic acid + NAD(P)+
is_a:GO:0016646 (CHANGED THIS PER PEIFEN)

3. Term Name: pipecolic acid N-hydroxylase (e.g. Arabidopsis FMO1)
Definition: Catalyzes the reaction: L-pipecolic acid + NAD(P)H + O2 + H+ = N-hydroxypipecolic acid + NAD(P)+ + H2O 

is_a:GO:0016712

**Comment by ukemi** [comment]
@dougli1sqrd, I'm adding you to this because this is one of the tickets we will do together on this BioFriday.

**Comment by lreiser** [comment]
Cool. These terms/ definitions came from the author of this paper (Jürgen Zeier)
https://doi.org/10.1104/pp.17.00222

**Comment by ukemi** [comment]
Thanks @lreiser. We will check to be sure these aren't already covered by the terms that @hdrabkin added for Peifen. Do you know if this is the only way this pathway is executed? If it is, it would be really nice to tie these functions with the process.

**Comment by lreiser** [comment]
@ukemi  so yesterday I was at a conference in Berkeley where Elizabeth Sattely from Stanford ALSO presented  on this pathway- discovered by a different approach 
https://www.biorxiv.org/content/early/2018/03/25/288449
So a newly discovered pathway. I know she knows Peifen so maybe she already asked. I can check.

**Comment by lreiser** [comment]
I don't think so- he just submitted annotations to us. I can ask Beth Sattely and see if she has.

**Comment by lreiser** [comment]
@ukemi  Peifen said she had not submitted term requests for this pathway to Harold,  but that she would review these terms today or tomorrow. I also sent them to Beth Sattely today.

**Comment by ukemi** [comment]
Thanks @lreiser. I can go ahead and add these and then add the cross refs once they are available. Is that ok with you?

**Comment by lreiser** [comment]
Yes please. Then I can complete some annotations and that will make me happy as a clam.
