### ISSUE TITLE
NTR: intraciliary transport particle A binding

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#15692]
From annotation review ticket (co-localizes_with complex terms): https://github.com/geneontology/go-annotation/issues/1940

I need a term to indicate "intraciliary transport complex A binding"

from: 

> Mukhopadhyay S, Wen X, Chih B, Nelson CD, Lane WS, Scales SJ, Jackson PK.
> TULP3 bridges the IFT-A complex and membrane phosphoinositides to promote
> trafficking of G protein-coupled receptors into primary cilia. Genes Dev. 2010
> Oct 1;24(19):2180-93. doi: 10.1101/gad.1966210. PubMed PMID: 20889716

**Comment by krchristie** [comment]
@sylvainpoux - This is the ticket for the new term that should replace these _colocalizes_with_ annotations that both MGI and SWIS made: 

_colocalizes_with_ **intraciliary transport particle A** (GO:0030991)

**Comment by RLovering** [comment]
Hi Karen

for those of us that look at tickets depending on the ticket title it would be very helpful if you included the term requested in the title rather than the ticket number

Thanks

Ruth

**Comment by krchristie** [comment]
@RLovering - Apologies that I forgot to finish the title of the ticket. I've corrected that now.

**Comment by krchristie** [comment]
reopening to remind me to reannotate once term is available in MGI

**Comment by krchristie** [comment]
**Notes for reannotation**
Gene = Tulp3
New GO ID - GO:0120160 (intraciliary transport particle A binding) [to replace colocalizes_with annot]

**Comment by krchristie** [comment]
I've finished my annotation review and changed the annotation to this new term. 

@pgaudet - I'm assigning you the ticket now to address my previous question about whether the "protein complex" label is appropriate on this ticket when this is not a request for a CC term, but for an MF term for binding to the complex. You can close the ticket when you've addressed that question. Thanks!

**Comment by pgaudet** [comment]
@krchristie I don't mind which label we take - I like to have some 'biology' label so we can make rough groupings; is there an other label you this is more appropriate ?

**Comment by krchristie** [comment]
@pgaudet  I would have thought that 'binding' would be more appropriate.
