### ISSUE TITLE
query about Lem3p-Dnf1p complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15693]
Accession GO:1990531
NameLem3p-Dnf1p complex
def: A protein complex that functions as a phospholipid-translocating P-Type ATPase. 
Source: PMID:15090616, 
GOC:dph, GOC:rb

This definition does not seem to be specific enough for the term name , there are quite a few combinations of proteins that fit this definition.

Could we make a more generic "flippase" complex term?  

see
Coordinated Overexpression in Yeast of a P4-ATPase and Its Associated Cdc50 Subunit: The Case of the Drs2p/Cdc50p Lipid Flippase Complex.
Methods Mol Biol. 2016;1377:37-55. 
PMID: 26695021

A high-yield co-expression system for the purification of an intact Drs2p-Cdc50p lipid flippase complex, critically dependent on and stabilized by phosphatidylinositol-4-phosphate.
PLoS One. 2014  PMID: 25393116

These complexes appear to have (at least one) member from each of these families 
IPR006539 | P-type ATPase, subfamily IV
and a 
IPR005045 | CDC50/LEM3 family member

Is it possible to say which way the flippase acts to refine the def?  (I think this one is external to internal PM membrane but I'm not completely sure, I'm guessing  because I have a flippase which is not either of these families and it seems to be  internal to external)

thanks,

val

**Comment by bmeldal** [comment]
Sandra annotated it in the CP as  GO:0098533 ATPase dependent transmembrane transport complex:

https://www.ebi.ac.uk/complexportal/complex/CPX-1021

There are 4 P4-ATPases in the CP, all annotated more or less the same. I guess the specific name was created after she curated the P4s...

**Comment by ValWood** [comment]
This is lipid *translocation* though
https://www.ebi.ac.uk/QuickGO/term/GO:0034204
not transmembrane transport (Transmembrane transport requires transport of a solute across a lipid bilayer)

Here the lipid is transferred from one leaflet to another.

I think GO:0098533 is a grouping term for transmembrane transporters,  by it's placement, although the definition is sub-optimal...

**Comment by bmeldal** [comment]
You are right, I will mend them. These are old entries.

**Comment by bmeldal** [comment]
Actually, before I mend ours, I propose the following updates:
 
-GO:1990531 Lem3p-Dnf1p complex
+GO:1990531 phospholipid-translocating ATPase complex 

-A protein complex that functions as a phospholipid-translocating P-Type ATPase. 
+A protein complex that functions has phospholipid-translocating P-Type ATPase activity. 

+Synonym: Lem3p-Dnf1p complex [NARROW]
+Synonym: Lem3-Dnf1 complex [NARROW]
+Synonym: Dnf1-Lem3 complex [NARROW]
+Synonym: Dnf2-Lem3 complex [NARROW]
+Synonym: DRS2-CDC50 complex [NARROW]
+Synonym: CDC50-DRS2 complex [NARROW]
+Synonym: DNF3-CRF1 complex [NARROW]
+Synonym: CRF1-DNF3 complex [NARROW]
+Synonym: P4-ATPase complex [EXACT]
+Synonym: phospholipid flippase complex [EXACT]
+Synonym: aminophospholipid translocase complex [EXACT]
+Synonym: APLT complex [EXACT]

Relationships:
-is_a GO:1990351 transporter complex (wrong activity!)

Note to self:
Change def in CP from "A membrane pump which actively transports, or flips..." to "A membrane pump which actively **translocates**, or flips..."

What did I miss? ;-)

**Comment by ValWood** [comment]
Sounds good!

**Comment by hdrabkin** [comment]
A protein complex that functions as a phospholipid-translocating P-Type ATPase.
Why do you want the def to change to this below?  The current def says the same thing?

+A protein complex that functions has phospholipid-translocating P-Type ATPase activity.

**Comment by hdrabkin** [comment]
Don't understand this:
-is_a GO:1990351 transporter complex (wrong activity!) is inferred I think from the 
'capable of phospholipid-translocating ATPase activity" 

Have changed term name and synonyms as first pass.

**Comment by bmeldal** [comment]
>A protein complex that functions as a phospholipid-translocating P-Type ATPase.
Why do you want the def to change to this below? The current def says the same thing?

Just the syntax. It was standardised when we could still use TG templates to create complex terms from their activities.

>-is_a GO:1990351 transporter complex (wrong activity!) is inferred I think from the
'capable of phospholipid-translocating ATPase activity"

As @ValWood mentioned above, this is a flippase that just moves a phospholipid form one membrane to another by flipping it over. It's not really transporting stuff. 

>Def for transport:
"The directed movement of substances (such as macromolecules, small molecules, ions) or cellular components (such as complexes and organelles) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter, pore or motor protein."

I'm not sure "The directed movement of substances (such as macromolecules, small molecules, ions) or cellular components (such as complexes and organelles) into, out of or **within a cell**..." is really capturing what's happening to these PLs. But Val and I might be wrong.

**Comment by pgaudet** [comment]
Flippases need to be fixed #14793

**Comment by bmeldal** [comment]
So, park this one til #14793 has been dealt with?

**Comment by bmeldal** [comment]
Ok, so transporter complex is correct then as is_a parent as it's defined for all types of transport.

In that case, this could be closed and I update the annotation in the CP.

**Comment by ValWood** [comment]
I still need a term to use ;)

**Comment by bmeldal** [comment]
The term's been updated to be valid for all phospholipid-translocating ATPases

GO:1990531 phospholipid-translocating ATPase complex
with the specific complexes demoted to narrow synonyms.

Or do you need something more generic?

**Comment by ValWood** [comment]
Ah right Ok, if those updates are done, I'm good! I wasn't following properly!

**Comment by ValWood** [comment]
The term is not updated yet. Is it done? if I use it with the  name
"phospholipid-translocating ATPase complex"

**Comment by bmeldal** [comment]
updated according to QuickGO:
https://www.ebi.ac.uk/QuickGO/term/GO:1990531

**Comment by ValWood** [comment]
OK!
