### ISSUE TITLE
duplicated terms?

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#15703]
http://amigo.geneontology.org/amigo/term/GO:0103054

http://amigo.geneontology.org/amigo/term/GO:0102972
these look like the same thing to me...
neither has any annotations.
Should they be merged?

**Comment by cmungall** [comment]
my goodness these have been there a while - they fail exact name checks since they differ by a space character...

these have different metacyc IDs associated

MetaCyc:RXN-6544
MetaCyc:RXN-947

**Comment by hdrabkin** [comment]
If they have different metacycs they should be different so may need to change term name anyways; I think these are from Peifen; I'll check. All these plant giberillins give me a headache.

**Comment by lreiser** [comment]
Ah yes products .. I missed that difference going back and forth between the two screens.. thought I checked the equations.

**Comment by hdrabkin** [comment]
Name changes 
Accession  GO:0102972
Name  gibberellin A12,2-oxoglutarate:oxygen oxidoreductase activity (gibberellin A110-forming)
Accession GO:0103054
Name gibberellin A12, 2-oxoglutarate:oxygen oxidoreductase activity (gibberellin A15-forming) 
done
