### ISSUE TITLE
parentage of GO:0019825 "oxygen binding"

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#15702]
The only parentage now is: GO:0019825 "oxygen binding" is_a GO:0008144 "drug binding". Don't want to re-open or complicate the recent discussion of the use of the word "drug" in GO, but shouldn't "oxygen binding" also have an is_a parent like GO:0036094 "small molecule binding"?

**Comment by ukemi** [comment]
No worries. Looks like the inferences aren't doing much for us here. I am asserting the small molecule binding parent.
