### ISSUE TITLE
Incorrect taxon constraint violations error from GOA checking script?

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-ontology#15701]
We got a report indicating that some of our annotations violated the taxon constraint GO:0000747, only_in_taxon <species not known>. See examples below:

GO:0000755 cytogamy   
GO:0000742 karyogamy involved in conjugation wit...
GO:0000747 conjugation with cellular fusion
 GO:0000743 nuclear migration involved in conjuga..
GO:0000752 agglutination involved in conjugation...

Full description of constraint in Protein2GO: GO:0000747 (conjugation with cellular fusion) and its descendants should ONLY be used with gene products from the taxonomic group Fungi or Dictyostelium

I think there's a bug somewhere.

**Comment by krchristie** [comment]
So as Edith pointed out, there is an ONLY IN taxon constraint on this term:

**conjugation with cellular fusion** (GO:0000747)
'only in taxon' some NCBITaxon_Union_0000022

where the taxon union is defined here:
http://www.geneontology.org/quality_control/annotation_checks/taxon_checks/taxon_union_terms.obo

> [Term]
> id: NCBITaxon_Union:0000022
> name: Fungi or Dictyostelium
> namespace: union_terms
> union_of: NCBITaxon:4751 ! Fungi
> union_of: NCBITaxon:5782 ! Dictyostelium

It seems beyond the scope of the ontology why annotations to a fungal species would be violating a taxon constraint that says annotations should be made ONLY to Fungi or Dictyostelium.

@cmungall - Any ideas?

**Comment by cmungall** [comment]
@edwong57 can you point to the report

**Comment by krchristie** [comment]
@edwong57 - The taxon constraints in the GO file look appropriate. I've put them all below where EA indicates the Equivalence Axiom for the three terms that inherit the taxon constraint via the GO term used in their EA.

If this still a problem, perhaps there is some issue with the GOA checking script that you should report to GOA. 

GO:0000755 cytogamy `only_in_taxon some Fungi`

GO:0000747 conjugation with cellular fusion `only_in_taxon some 'Fungi or Dictyostelium'`
- GO:0000742 karyogamy involved in conjugation with cellular fusion
 EA = `karyogamy and ('part of' some 'conjugation with cellular fusion')`

- GO:0000743 nuclear migration involved in conjugation with cellular fusion
 EA = `'nuclear migration' and ('part of' some 'conjugation with cellular fusion')`

- GO:0000752 agglutination involved in conjugation with cellular fusion
 EA = `''adhesion between unicellular organisms' and ('part of' some 'conjugation with cellular fusion')`
