### ISSUE TITLE
New GO term for new EC 7, translocases

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#15712]
Hi,

I need a GO term for the new EC class 7 that will cover Translocases.
The EC list definition is:
These enzymes catalyse the movement of ions or molecules across membranes or their separation within membranes, the reaction is designated as a transfer from ‘side 1’ to ‘side 2’ because the designations ‘in’ and ‘out’, which had previously been used, can be ambiguous. The subclasses designate the types of components transferred and the sub-sub-classes indicate the reaction processes that provide the driving force for the translocation.

The subclasses will be 

EC 7.1  Catalysing the translocation of hydrons 
EC 7.2  Catalysing the translocation of inorganic cations 
EC 7.3  Catalysing the translocation of inorganic anions and their chelates 
EC 7.4  Catalysing the translocation amino acids and peptides 
EC 7.5  Catalysing the translocation carbohydrates and their derivatives 
EC 7.6   Catalysing the translocation of other compounds 

The new class will be populated with existing enzymes that are poorly classified in the existing classes. Most will come from EC 3.6 (P-type ATPases and ABC transporters) but also electron carrier oxidases (e.g. EC 1.6.1.5, EC 1.10.3.13, EC 1.10.2.2) will be transferred here.

Cheers,
Kristian

**Comment by hdrabkin** [comment]
None of these appear to be in the current EC (https://enzyme.expasy.org/) , so I am reluctant to put them into GO before they become available.

**Comment by pgaudet** [comment]
Done here #17127
