### ISSUE TITLE
NTR: Lymphotoxin-alpha Lymphotoxin-beta Lymphotoxin-beta heterotrimer complex

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15736]
From https://github.com/geneontology/helpdesk/issues/124 

@elmbeech, I've moved your request to this ontology tracker; this is the best place to resolve this issue.

Dear GeneOntology helpdesk,

I was searching AmiGO for a cellular component GO Term for Lymphotoxin-alpha Lymphotoxin-beta Lymphotoxin-beta heterotrimer, because our wetlab will perform experiments with this heterotrimer and I would like to annotate the experiment properly.

This is the reagent used in our lab:

    https://www.rndsystems.com/products/recombinant-human-lymphotoxin-alpha1-beta2-protein_8884-ly
    https://resources.rndsystems.com/pdfs/datasheets/8884-ly.pdf

This is what is written about the heterotrimer:
"The Lymphotoxin alpha 1/ beta 2 heterotrimer binds and activates the Lymphotoxin beta R/TNFRSF3 (LT beta R) which is expressed on macrophages, dendritic cells, hepatocytes, intestinal epithelial cells (IEC), follicular dendritic cells (FDC), and high endothelial venules (HEV)"

This are the related uniprot protein identifiers:

    LTA P01374: http://www.uniprot.org/uniprot/P01374
    LTB Q06643: http://www.uniprot.org/uniprot/Q06643

Could this term be generated?

This are the publications listed by the vendor that hetero timers are formed: 
+ https://www.ncbi.nlm.nih.gov/pubmed/7916655 (Browning 1993: Lymphotoxin beta, a novel member of the TNF family that forms a heteromeric complex with lymphotoxin on the cell surface.) 
+ https://www.ncbi.nlm.nih.gov/pubmed/1733951 (Androlewicz MJ 1999: Lymphotoxin is expressed as a heteromeric complex with a distinct 33-kDa glycoprotein on the surface of an activated human T cell hybridoma. ) 
+ https://www.ncbi.nlm.nih.gov/pubmed/23524463 (Upadhya 2013: Lymphotoxin signalling in immune homeostasis and the control of microorganisms.) Was I was looking for is something like : 
+ http://amigo.geneontology.org/amigo/term/GO:0043256 for the Laminin Complex 
+ http://amigo.geneontology.org/amigo/term/GO:0005587 for Collagen 4 
+ http://amigo.geneontology.org/amigo/term/GO:0005584 for Collagen 1 
+ http://amigo.geneontology.org/amigo/term/GO:0034666 for Integrin alpha2-beta1 Complex 

This is maybe a bit a miss use from GeneOntology. But I am not aware of an other controlled vocabulary identifier for protein complexes then GO terms. UniProt specifies only on protein level. I use this identifiers to label my data. For example: 
+ Laminin_Complex_go0043256 for a data point that was caused by Laminin treatment 
+ COL1A1_P02453 for a data point caused by Collagen alpha-1(I) chain treatment 
+ CDH8_P55286 for Cadherin-8 treatment 
... and so on. I think this makes data integration afterwords easier. And it makes much more clear which protein treatment really was done. Till now I always fond a GO term for the protein complexes I was looking for but not this time, when I was searching for a term for a Lymphotoxin Complex. Please let me know if you think I should not use go terms as I do. I don't know if I can contribute much from the biological side, as I am just a simple bioinformatician. 

Best, Elmar Bucher

**Comment by ukemi** [comment]
Thanks @bmeldal ! I was hoping you would comment. I am going to need a good reference for the term.

**Comment by bmeldal** [comment]
David, next time give me a mention, I just noticed it in the daily emails.

@elmbeech can you please quote a paper with experimental evidence for the complex?

**Comment by elmbeech** [comment]
Hi Brigit and David,

Good to hear that I am not the only one carrying about protein complexes : ).

I am on travel till the end of May. And I have no computer with me but my smart phone. I happy to help with annotation as soon as I am back, and I sure will!
Excuse this delay. 

Talk to you upon return.
Tank you, Elmar

---- On Tue, 15 May 2018 07:58:31 -0700 notifications@github.com wrote ----

Hi Elmar,

Birgit here from Complex Portal (www.ebi.ac.uk/complexportal). We curate complexes as biological units and annotate them to GO terms. Your requested complex has not yet been curated and no interaction evidence is curated in IntAct either (www.ebi.ac.uk/intact). But Mentha (I accesses it via PSICQUIC: http://www.ebi.ac.uk/Tools/webservices/psicquic/view/ and searched for "P01374 AND Q06643") has evidence, albeit very old one. We'd be happy to curate new terms for your.

In GO I'd call it Lymphotoxin complex and make a synonym:
Lymphotoxin alpha-beta [narrow]

Without spending a lot of time reading papers, it appears stoichiometry could be alpha2-beta1 or alpha1-beta2 - or homotrimers (see UniProt). We don't capture the stoichiometry in the term name but it could be mentioned in the definition (A homo- or heterotrimeric complex consisting of alpha and beta subunits in different stoichiometric combinations...). There was a time when each combination was created in GO but if the function is the same for all variants you only need one GO term. I

n the Complex Portal we would create all variants and entries are species-specific, too. Complexes can then be used as annotation objects the same way as proteins.

I hope this is a start. Welcome to the world of complexes ;-)

Birgit

**Comment by ukemi** [comment]
It seems we are in synch. I am away starting Friday for the next week too.

**Comment by bmeldal** [comment]
There is no functional statement in the current def and all complexes need some functional statement, not just composition.

Elmar quotes:

>"The Lymphotoxin alpha 1/ beta 2 heterotrimer binds and activates the Lymphotoxin beta R/TNFRSF3 (LT beta R) which is expressed on macrophages, dendritic cells, hepatocytes, intestinal epithelial cells (IEC), follicular dendritic cells (FDC), and high endothelial venules (HEV)"

I would change def to:

"A protein-containing complex that binds to and activates the Lymphotoxin beta R/TNFRSF3 (LT beta R). Forms homo- or heterotrimeric protein complexes consisting of alpha and beta lymphotoxin subunits in different stoichiometric combinations."

BUT - I can't identify which protein **TNFRSF3** refers to. I guess it's the receptor but UniProt hasn't got an exact synonym for gene names. I was to wait for @elmbeech to clarify.

Elmar, next time it would be helpful if you suggest the term definition directly. We may still tweak it but it's easier for us to pick it up.

Thanks,
Birgit
