### ISSUE TITLE
OTR: GO:0102560 typo

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15735]
From https://github.com/geneontology/helpdesk/issues/116 @chrish00
id: GO:0102560
name: 5-phospho-alpha-D-ribose 1,2-cyclic phosphate 1-phsophohydrolase activity
Should this be “phosphohydrolase”?

**Comment by ukemi** [comment]
Can you check the name of this enzyme activity based on EC and either change the name or correct the spelling?

**Comment by hdrabkin** [comment]
obvious typo; 
however, going to that EC, what was used here is not the EC name
EC official name is Phosphoribosyl 1,2-cyclic phosphate 1,2-diphosphodiesterase; 
I am tempted to change the name and put Peifen's as a synonym? Thoughts

**Comment by hdrabkin** [comment]
Sigh
Same EC used as xref for two terms with different metacyc id 
I'll fix typo now and get some thoughts if this should be a term merge too

**Comment by pgaudet** [comment]
GO:0102561 D-ribose 2,5-bisphosphate 2-phosphohydrolase activity
& GO:0102560 5-phospho-alpha-D-ribose 1,2-cyclic phosphate 1-phsophohydrolase activity
have the same METACYC ID. 

I am merging these. 

Pascale

**Comment by pgaudet** [comment]
Actually there are 2 MetaCyc: RXN-14995 and RXN-14996, and 2 RHEA: RHEA:41613 and RHEA:41617

**Comment by pgaudet** [comment]
I've added the cross references to RHEA. @hdrabkin if you think there is something else to do please reopen. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
e EC:3.1.4.57 associated with this term.
RHEA:41612 alpha-D-ribose 1,2-cyclic phosphate 5-phosphate + H2O = D-ribose 2,5-bisphosphate + H(+) is mapped directly to the EC.
However, you picked: 
RHEA:41613  alpha-D-ribose 1,2-cyclic phosphate 5-phosphate + H2O => D-ribose 2,5-bisphosphate + H(+); 
Why?

**Comment by pgaudet** [comment]
I think I got the mapping from MetaCyc. if this is incorrect can you please fix ? Or she we add multiple cross-references ?

**Comment by hdrabkin** [comment]
You cannot have more than one rhea per go term. So we can't use both.
The reaction you picked was the Uni-directional, but wanted to know how you knew this.
 RXN-14995  and  RXN-14996  reference the same EC:3.1.4.57
 EC:3.1.4.57 references RHEA:41612 
EC:3.1.4.57 uses <=>, not =>; 
And problably use the RHEA:41612

**Comment by pgaudet** [comment]
Fixed the xref to RHEA:41612.
