### ISSUE TITLE
Microbiota homeostasis

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#15748]
Dear GO annotators,

I would need your help with the annotation of a mouse protein that influences the composition of the gut microbiota (Q8BH82_NAPEP_MOUSE; PMID:25757720). Which GO term would you suggest to describe this activity?  Would it be better to create a new GO term such as microbiota homeostasis?

Many thanks!

Nevila  Hyka-Nouspikel

**Comment by nnouspikel** [comment]
Maybe something of interest for @pgaudet

**Comment by pgaudet** [comment]
Hi Nevila, 

That's a good question! We do have the term 'homeostasis of number of cells in a free-living population' that is defined as 'The biological process involved in maintaining the steady-state number of cells within a population of free-living cells such as the bacteria in the gut.' - sound like this is what you need ? 

(that part of the ontology is a little strange though; I am not sure the children are really consistent with this term). 

Does that help ? 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Thank you Pascale for the quick answer. GO:0048874  'homeostasis of number of cells in a free-living population'  seems like a good option.

Thanks again,

Nevila

**Comment by ukemi** [comment]
Close this?

**Comment by pgaudet** [comment]
Shouldn't we improve the label? Nevila do you have a suggestion?

Le mer. 16 mai 2018 à 3:12 PM, David Hill <notifications@github.com> a
écrit :

**Comment by ukemi** [comment]
Or add a synonym, microbiota seems rather specific. I suspect the existing term encompasses more.

**Comment by pgaudet** [comment]
Hi @nnouspikel 
Are these terms really clear? 
How about renaming 'homeostasis of number of cells in a free-living population' -> 'regulation of intestinal microbiota composition'? (since you'd be the first to use that term). 
(and we probably need to move children out). 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Hi Pascale,

It sounds good. I wondered if we could add the notion that the regulation is done by the host: 
host-induced regulation of intestinal microbiota composition?

Many thanks,

Nevila

**Comment by pgaudet** [comment]
Hi @nnouspikel 
I changed the term label to 'host-**mediated** regulation of intestinal microbiota composition' (also added 'induced' as synonym; is this OK ? 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Thank you Pascale. Sounds very good.

Cheers,

Nevila
