### ISSUE TITLE
Amigo  numbers over-inflated, but no annotation present

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15740]
This is really strange.

I have 128  proteins annotated to "actin cytoskeleton organization"
this is whet we submit to GO.
In AmiGO if I search on pombe proteins annotated to "actin cytoskeleton organization"
i get 185 gene products reported.

I down-loaded this list and looked at the difference

One member is
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBP23A10.08
but when I looked at this gene product in AmiGO
this does not have an annotation to "actin cytoskeleton organization" or one of its  descendants?

**Comment by ValWood** [comment]
So, it seems that what you get from a query does not match what is displayed on the  Amigo gene product pages?

**Comment by ValWood** [comment]
another example,
no annotation to  "actin cytoskeleton organization"
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC14C4.09

**Comment by ValWood** [comment]
@huaiyumi  this is an AmiGO problem.
Once this is correct it will be easier to troubleshoot the PANther enrichment  to see why the results don't match what  are in the GO database.

**Comment by ValWood** [comment]
This is the file of 128 genes annotated to "actin cytoskeketon organization" in our current GAF
[cytoskeleton_list.txt](https://github.com/geneontology/go-ontology/files/2001071/cytoskeleton_list.txt)

These are the 57 genes in the download list
[gene_list_57.txt](https://github.com/geneontology/go-ontology/files/2001102/gene_list_57.txt)
that aren't annotated to "actin cytoskeleton organization"

**Comment by kltm** [comment]
@ValWood Not an amigo problem (amigo just displays what it is given), but possibly some pipeline issue. Also tagging on @dougli1sqrd .

**Comment by ValWood** [comment]
It's weird because AmiGO seems to be internally inconsistent. The list I downloaded is FRM Amigo?

**Comment by cmungall** [comment]
If AmiGO is internally inconsistent then it would be an AmiGO issue, but I believe it is consistent

> In AmiGO if I search on pombe proteins annotated to "actin cytoskeleton organization"
i get 185 gene products reported.

Do you still have the URL you used? Or we can walk through this together.

If I start on
http://amigo.geneontology.org/amigo/term/GO:0030036

And then select the link to the list of genes (sorry this is still unintuitive), then filter on pombase

i.e:

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0030036%22&sfq=document_category:%22bioentity%22

download link:

http://golr.geneontology.org/solr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=bioentity,bioentity_label&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&hl.snippets=1000&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=regulates_closure:%22GO:0030036%22&fq=document_category:%22bioentity%22&fq=taxon_subset_closure_label:%22Schizosaccharomyces%20pombe%22&facet.field=source&facet.field=taxon_subset_closure_label&facet.field=type&facet.field=panther_family_label&facet.field=annotation_class_list_label&facet.field=regulates_closure_label&q=*:*

I get 136, this does *not* include SPAC14C4.09

```
$ curl -s -L 'http://golr.geneontology.org/solr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=bioentity,bioentity_label&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&hl.snippets=1000&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=regulates_closure:%22GO:0030036%22&fq=document_category:%22bioentity%22&fq=taxon_subset_closure_label:%22Schizosaccharomyces%20pombe%22&facet.field=source&facet.field=taxon_subset_closure_label&facet.field=type&facet.field=panther_family_label&facet.field=annotation_class_list_label&facet.field=regulates_closure_label&q=*:*' | grep SPAC14C4.09
```

it still doesn't match your 128, we have an extra 8. But I can't reproduce your 185

**Comment by cmungall** [comment]
Likely a DNS issue from recent switchover from Stanford. I had the same issue. Can you do a hard refresh/reload?

I just want to confirm the path that you went through to get the list of 186, I want to get to the bottom of this

**Comment by ValWood** [comment]
just from the GO term. I'm now getting correctly "136"

**Comment by ValWood** [comment]
This is the list of IDs I got from the "download" previously

[cyto_amigo.txt](https://github.com/geneontology/go-ontology/files/2001746/cyto_amigo.txt)

[cytoskeleton_list.txt](https://github.com/geneontology/go-ontology/files/2001748/cytoskeleton_list.txt)

**Comment by ValWood** [comment]
The thing that I find really confusing is that  these, as far as I known have nver been annotated to "actin cytoskeleton organization"

but there is usually  a  (tenuous) link to cytoskeleton (for example complexes which contain an actin like protein but are involved in transcription, clathrin coats, septins etc).
So I thought maybe this was paint annotations, but it seems not. I just can't see where the annotations would come from.

**Comment by ValWood** [comment]
The difference you see now 128-136 is fine. This *is* due to PAINT (I will check these).

but why it was 186 is still odd...

**Comment by ukemi** [comment]
Should this be closed and moved to the AMIGO2 tracker? It doesn't seem like an ontology task.

**Comment by kltm** [comment]
I believe that this issue has been resolved for the time being either way?

**Comment by ValWood** [comment]
We still haven't been able to trace the cause. The numbers fluctuate.

We have been trying to trace it locally without success.
https://github.com/pombase/curation/issues/1901
https://github.com/pombase/pombase-chado/issues/678

.. I think it is most likely ontology. seems to be different handling of regulation over regulates. I'm not sure where or how...

**Comment by ValWood** [comment]
I haven't seen this issue for a while.
I'll re report if it happens again.
