### ISSUE TITLE
growth term, make not for direct annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15742]
as per discussion about PAINT
Not a useful term (child terms /regulation are useful)

**Comment by ValWood** [comment]
@pgaudet @ukemi

**Comment by pgaudet** [comment]
Created an annotation review ticket: 
https://github.com/geneontology/go-annotation/issues/1973


Thanks, Pascale

**Comment by ukemi** [comment]
I just checked, and this is already in the do not annotate subset.
