### ISSUE TITLE
Difference between cytokinesis and morphogenesis checkpoint terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15751]
hi, 

This may be a question for @ValWood and @mah11 : 

While fixing terms sharing the same exact synonym, I came across these 2 pairs of terms: 

    GO:0072398   signal transduction involved in cytokinesis checkpoint  
    GO:1903822   signal transduction involved in morphogenesis checkpoint

    GO:1903821    detection of stimulus involved in morphogenesis checkpoint 
    GO:0072397    detection of stimulus involved in cytokinesis checkpoint

That all mention 'septin checkpoint' in the synonym. There are no annotations to any of these terms; Can I get help WRT which synonyms are correct, and perhaps improvements to the definitions? 

Thanks, Pascale

**Comment by ValWood** [comment]
@ukemi  and I did this as an outcome of the cell cycle meeting.
I don't remember the details, but it was complicated ....will try to dig out the old tickets later.

All I know is that they are 2 different checkpoints which often become confused because  of the original naming.

I'm not sure why there are no annotations because I'm sure I annotated these checkpoints after the meeting, and SGD had them annotated too (I think I discussed also with Rob Nash
can't find his ID in here? https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv)

Right now I need to check-point out of my hotel room and head to the Frick,  will dig deeper when I get back..

**Comment by mah11** [comment]
Nothing about checkpoints is ever really a question for me ;)

But from looking the terms for the checkpoints themselves, my guess is that the "septin checkpoint" synonyms should be included for the morphogenesis checkpoint terms. It's less clear whether the synonyms should removed from the cytokinesis checkpoint terms or consistently included, but as RELATED scope, for both checkpoints (see GO:0044878 and GO:0044879, as well as the obsolete terms GO:0000078 and GO:0031565 - there was a bit of a mess in the past).

**Comment by ValWood** [comment]
I think this ticket has the history
https://github.com/geneontology/go-ontology/issues/11354

**Comment by ValWood** [comment]
cytokinesis after mitosis checkpoint
should be EXACT for 
mitotic cytokinesis checkpoint
(In fact I thought from the ticket that this would be the primary name?)

I agree with Midori that the septin checkpoint synonym should only be on the "morphogenesis checkpoint" term

In fact this term:
https://www.ebi.ac.uk/QuickGO/term/GO:0044878
does NOT have the "septin synonym"

I think we can also obsolete the parent terms (and regulates)  which does not refer to mitosis.  Since this checkpoint is specifically about blocking a  subsequent cytokinesis after mitosis there is no meiotic equivalent.....

**Comment by pgaudet** [comment]
Hi @ValWood 
Can you please make a little check list of what you want for this ticket ? 

Thanks :) 

Pascale

**Comment by ValWood** [comment]
ACtually after double checking the parents are fine.

Just
- [ ]  make "cytokinesis after mitosis checkpoint" exact synonym of "mitotic cytokinesis checkpoint"

- [ ]  "septin checkpoint" should only be a synonym of "morphogenesis checkpoint"

- [ ]  "septin checkpoint" should not be incuded in  "mitotic cytokinesis checkpoint"

is that enough to fix the problem?

**Comment by pgaudet** [comment]
Here are the synonyms I fixed: 

 **name: signal transduction involved in cytokinesis checkpoint**
  REMOVED:
-synonym: "signal transduction involved in septin checkpoint" RELATED []


 **name:response to cytokinesis checkpoint signaling**
 REMOVED: 
-synonym: "response to signal involved in septin checkpoint" EXACT [GOC:mah]
-synonym: "septin checkpoint effector process" EXACT [GOC:mah]
-synonym: "response to septin checkpoint signaling" EXACT []


 **name:regulation of response to cytokinesis checkpoint signaling**
 REMOVED:
-synonym: "regulation of response to septin checkpoint signaling" EXACT []
-synonym: "regulation of response to signal involved in septin checkpoint" EXACT [GOC:TermGenie]
-synonym: "regulation of septin checkpoint effector process" EXACT [GOC:TermGenie]


 **name:positive regulation of response to cytokinesis checkpoint signaling**
 REMOVED:
-synonym: "activation of response to septin checkpoint signaling" NARROW [GOC:TermGenie]
-synonym: "activation of response to signal involved in septin checkpoint" EXACT [GOC:TermGenie]
-synonym: "activation of septin checkpoint effector process" EXACT [GOC:TermGenie]
-synonym: "positive regulation of response to septin checkpoint signaling" EXACT []
-synonym: "positive regulation of response to signal involved in septin checkpoint" EXACT [GOC:TermGenie]
-synonym: "positive regulation of septin checkpoint effector process" EXACT [GOC:TermGenie]
-synonym: "up regulation of response to septin checkpoint signaling" EXACT [GOC:TermGenie]
-synonym: "up regulation of response to signal involved in septin checkpoint" EXACT [GOC:TermGenie]
-synonym: "up regulation of septin checkpoint effector process" EXACT [GOC:TermGenie]
-synonym: "up-regulation of response to septin checkpoint signaling" EXACT [GOC:TermGenie]
-synonym: "up-regulation of response to signal involved in septin checkpoint" EXACT [GOC:TermGenie]
-synonym: "up-regulation of septin checkpoint effector process" EXACT [GOC:TermGenie]
-synonym: "upregulation of response to septin checkpoint signaling" EXACT [GOC:TermGenie]
-synonym: "upregulation of response to signal involved in septin checkpoint" EXACT [GOC:TermGenie]
-synonym: "upregulation of septin checkpoint effector process" EXACT [GOC:TermGenie]




 **name: signal transduction involved in morphogenesis checkpoint**
 REMOVED:
-synonym: "signal transduction involved in septin checkpoint" RELATED [GOC:TermGenie]
-synonym: "signaling cascade involved in morphogenesis checkpoint" NARROW [GOC:TermGenie]
-synonym: "signaling cascade involved in septin checkpoint" NARROW [GOC:TermGenie]
-synonym: "signaling pathway involved in septin checkpoint" RELATED [GOC:TermGenie]
-synonym: "signalling cascade involved in septin checkpoint" RELATED [GOC:TermGenie]
-synonym: "signalling pathway involved in septin checkpoint" RELATED [GOC:TermGenie]

CHANGED SYNONYM TYPE TO 'EXACT':
+synonym: "signal transduction involved in septin checkpoint" EXACT [GOC:TermGenie]
+synonym: "signaling cascade involved in morphogenesis checkpoint" EXACT [GOC:TermGenie]
+synonym: "signaling cascade involved in septin checkpoint" EXACT [GOC:TermGenie]
+synonym: "signaling pathway involved in septin checkpoint" EXACT [GOC:TermGenie]
+synonym: "signalling cascade involved in septin checkpoint" EXACT [GOC:TermGenie]
+synonym: "signalling pathway involved in septin checkpoint" EXACT [GOC:TermGenie]

Let me know if you spot a problem. 

Thanks, Pascale

**Comment by ValWood** [comment]
> Obsoletion comment in "cytokinesis after mitosis checkpoint" is "The reason this term was made obsolete is that the two terms cytokinesis checkpoint (GO:0031565) and cytokinesis after mitosis (GO:0000078) were conflated in meaning."; so should I make this an exact synonym?

you don't need  to add the synonym it should be clear enough from the definition.
It may add back confusion.  I'm a bit worried that our annotations  to this disappeared. I'll look into that....I'm sure we had some...

**Comment by pgaudet** [comment]
OK - it was obsoleted in 2015 - FYI. 

I'm closing this sine the ontology part is done; re-open it if you need.

Thanks, Pascale
