### ISSUE TITLE
'detection of...' terms for thermoception subclasses

### ISSUE THREAD

**Issue by Clare72** [geneontology/go-ontology#15753]
Similar to the structure for 'thermoception', please can you make 'detection of...' part_of children for 'sensory perception of cold stimulus' and 'sensory perception of hot stimulus' i.e. 'detection of cold stimulus involved in sensory perception of cold stimulus' and 'detection of hot stimulus involved in sensory perception of hot stimulus'.

**Comment by krchristie** [comment]
Please provide more detail about exactly what new terms you are requesting, with proposed names, definitions, parents, references, and any other essential details.

Also please explain how these proposed new terms would differ from the existing terms for:
- sensory perception of cold stimulus
- sensory perception of hot stimulus

**Comment by Clare72** [comment]
'thermoception' (GO:0050955) has a part_of child - 'detection of temperature stimulus involved in thermoception' (GO:0050960), which is the first step in the process of thermoception - converting temperature to a molecular signal.

The terms for sensory perception of hot and cold stimulus (GO:0062035 and GO:0062036) need equivalent part_of children. Definitions can be copied and pasted from 'detection of temperature stimulus involved in thermoception' (GO:0050960), replacing the word 'temperature' with 'hot' or 'cold', and the word 'thermoception' with the appropriate 'detection of...' term.

**Comment by krchristie** [comment]
@Clare72 - Can you please indicate what reference (PMID, etc) should be used for the definitions of the new terms.

**Comment by Clare72** [comment]
The reference from the parent terms should be sufficient:
http://www.ncbi.nlm.nih.gov/pubmed/21335241
