### ISSUE TITLE
NTR telodendria 3 terms

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#15769]
new: Teleodendria
Def: Telodendria are projections that originate from the photoreceptor pedicle and form gap junctions with other photoreceptors within the outer plexiform layer of the retina. 

is a:  GO:0043005  neuron projection

new: cone teleodendria
Cone telodendria are projections that originate from the cone pedicle and form gap junctions with other photoreceptors within the outer plexiform layer of the retina. 
originates from: GO:0044316  cone cell pedicle
PubMed: 29127712
is a:  Teleodendria
originates from  GO:0044316 cone cell pedicle

New:rod teleodendria
Rod telodendria are projections that originate from the rod pedicle and form gap junctions with other photoreceptors within the outer plexiform layer of the retina.  
PMID:    14755521
is a:  Teleodendria

**Comment by krchristie** [comment]
@cerivs - I think that these definitions are too specific by mentioning photoreceptors. Prompted by a quick look at this Wiki page: https://en.wikipedia.org/wiki/Axon

I searched in PubMed also, and there are papers that discuss telodendria in non-retinal cells, specifically a couple in muscle cells and also one about them in crab brain where they are mentioned as being present in Kenyon cells which are associated with mushroom bodies and thus olfaction (https://en.wikipedia.org/wiki/Kenyon_cell)

Can you propose definitions that are less specific.

thanks,

-Karen

Results from PubMed search that are either definitely not or possibly not retina: 
1: Murphy MC, Fox EA. Mice deficient in brain-derived neurotrophic factor have
altered development of gastric vagal sensory innervation. J Comp Neurol. 2010 Aug
1;518(15):2934-51. doi: 10.1002/cne.22372. PMID:20533354

2: Fox EA, Phillips RJ, Martinson FA, Baronowsky EA, Powley TL. C-Kit mutant mice
have a selective loss of vagal intramuscular mechanoreceptors in the forestomach.
Anat Embryol (Berl). 2001 Jul;204(1):11-26. PMID:11506430

3: Fox EA, Phillips RJ, Martinson FA, Baronowsky EA, Powley TL. Vagal afferent
innervation of smooth muscle in the stomach and duodenum of the mouse: morphology
and topography. J Comp Neurol. 2000 Dec 18;428(3):558-76. PMID: 11074451

4: Tuckwell HC. Voltage clamp calculations for myelinated and demyelinated axons.
Eur Biophys J. 1993;22(1):71-7. PMID: 8390352

5: Tkacs NC, Wurster RD. Strength-duration and activity-dependent excitability
properties of frog afferent axons and their intraspinal projections. J
Neurophysiol. 1991 Mar;65(3):468-76. PMID:1646866

6: Fahrenbach WH. The brain of the horseshoe crab (Limulus polyphemus). III.
Cellular and synaptic organization of the corpora pedunculata. Tissue Cell.
1979;11(1):163-200. PMID:451992

**Comment by cerivs** [comment]
new: telodendria
Def: Telodendria are projections that originate from the  axon pedicle and form gap junctions with other neurons. 

is a: GO:0043005 neuron projection

new: cone telodendria
Cone telodendria are projections that originate from the cone pedicle and form gap junctions with other photoreceptors within the outer plexiform layer of the retina.
originates from: GO:0044316 cone cell pedicle
PubMed: 29127712
is a: teleodendria
originates from GO:0044316 cone cell pedicle

New: rod telodendria
Rod telodendria are projections that originate from the rod pedicle and form gap junctions with other photoreceptors within the outer plexiform layer of the retina.
PMID: 14755521
is a: telodendria

**Comment by cerivs** [comment]
Most of the instances I see in PubMed are studies of retina (27/33).  I kept the 2 very specific terms to accommodate retina specific use cases where they are frequently studied.

**Comment by krchristie** [comment]
@cerivs - Sorry so slow to respond to your update. I was on medical leave in October and am still catching up. Thanks for the update for the general term, and of course you're right that the two specific terms are fine.
