### ISSUE TITLE
Reviewing glycerol-3-phosphate dehydrogenase activity terms 

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-ontology#15775]
Hi there are 5 related terms for glycerol-3-phosphate dehydrogenase activity in GO based on the type of molecule that is oxidized

GO:0004368    glycerol-3-phosphate dehydrogenase activity
Catalysis of the reaction: sn-glycerol 3-phosphate + a quinone = glycerone phosphate + a quinol.
EC:1.1.5.3

GO:0047952    glycerol-3-phosphate dehydrogenase [NAD(P)+] activity
Catalysis of the reaction: sn-glycerol 3-phosphate + NAD(P)+ = glycerone phosphate + NAD(P)H + H+.
EC:1.1.1.94

GO:0036439    glycerol-3-phosphate dehydrogenase [NADP+] activity
Catalysis of the reaction: glycerol 3-phosphate + NADP+ = glycerone phosphate + H+ + NADPH.
EC:1.1.1.94

GO:0004367    glycerol-3-phosphate dehydrogenase [NAD+] activity
Catalysis of the reaction: sn-glycerol 3-phosphate + NAD+ = glycerone phosphate + NADH + H+.
EC:1.1.1.8

GO:0047014    glycerol-3-phosphate 1-dehydrogenase [NADP+] activity
Catalysis of the reaction: sn-glycerol 3-phosphate + NADP(+) = D-glyceraldehyde 3-phosphate + H(+) + NADPH.
EC:1.1.1.177

attached a screen shot of the current relationship of the terms
![screen shot 2018-05-22 at 11 36 56](https://user-images.githubusercontent.com/37106684/40359936-4b311c54-5dbc-11e8-82b5-beace67f38e3.png)

We have couple of issues with these terms. 

1) The terms and the definitions for GO:0047952 and GO:0036439 look similar with same EC number and are confusing. They have multiple annotations associated with each term separately. Not sure if those annotations have any duplicates. If you agree that the terms are same then it will be good to merge them to avoid confusion and duplications.

2)The glycerol-3-phosphate 1-dehydrogenase [NADP+] activity (GO:0047014) term seems related to the above but the activity is slightly different with the rest. So far there are no annotations associated with this term. We don't know if it can be merged with any of the above but think that it can be obsoleted.

3)Regarding GO:0004368    glycerol-3-phosphate dehydrogenase activity. This term looks like a more general term. It would be more helpful if the name is renamed according to its definition, like:
"glycerol-3-phosphate dehydrogenase (quinone) activity" or "glycerol-3-phosphate dehydrogenase (FAD) activity".

Tagging @hattrill @sjm41

**Comment by hdrabkin** [comment]
GO:0047952 has metacyc MetaCyc:GLYC3PDEHYDROGBIOSYN-RXN
 and GO:0036439  has none but has Rhea mappings. Most likely the same reaction

Interestingly, I think GO:0004369 USED to have (quinone) or FAD dependent in it's name (if I'm remembering correctly).

**Comment by pgaudet** [comment]
> Interestingly, I think GO:0004369 USED to have (quinone) or FAD dependent in it's name (if I'm remembering correctly).

Not according to QuickGO change log's: 
https://www.ebi.ac.uk/QuickGO/term/GO:0004369

**Comment by hdrabkin** [comment]
It must have been a very related term that used quinone or FAD rather than NAD for dehydrogenase then.

**Comment by hdrabkin** [comment]
GO:0036439  has RHEA:11099, NADP(+) + sn-glycerol 3-phosphate <=> dihydroxyacetone phosphate + H(+) + NADPH; 
which is rxn refered to by MetacycID GLYC3PDEHYDROGBIOSYN-RXN for GO:0047952 
GO:0036439  has additiona mapping to KEGG:R00844, 

Definition | sn-Glycerol 3-phosphate + NADP+ <=> Glycerone phosphate + NADPH + H+
Because THE EC number

**Comment by hdrabkin** [comment]
merged GO:0047952 and GO:0036439 
Tweaked GO:0004368  name
product of  GO:0004368  very different and has different EC; 
I am trying to think of a way to make the name clearer.

**Comment by ValWood** [comment]
seems complete? what is the outstanding name fix task?

**Comment by ValWood** [comment]
pinging @hdrabkin

**Comment by sjm41** [comment]
Closing this. Outstanding issues mentioned here got addressed in #19191
