### ISSUE TITLE
Proposal to obsolete GO:0001026 TFIIIB-type transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15788]
Dear all, 

The proposal has been made to obsolete 'GO:0001026 TFIIIB-type transcription factor activity'. The reason for obsoletion is that it represents a gene product (more specifically, a protein complex composed of 3 proteins). Annotations should be moved to 'GO:0000995 RNA polymerase III general transcription initiation factor activity'. 

**10 EXP annotations**
https://docs.google.com/spreadsheets/d/1OgEAdJ5Y5z7SJpPNxWzW4WKPIsWfcnn0KpBTg9PdhnE/edit#gid=0

**3 InterPro mappings:** 
* InterPro:IPR030701
* InterPro:IPR029529
* InterPro:IPR017174

Comments can be added to the ticket: #15788 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on May 30, 2018. Unless objections are received by May 30, 2018, we will assume that you agree to this change.

Thanks,

Pascale

**Comment by ValWood** [comment]
I'm done for the spreadsheet.
Also fixing https://github.com/pombase/curation/issues/2002

**Comment by ValWood** [comment]
I'm done for the spreadsheet, also fixing none EXP
https://github.com/pombase/curation/issues/2004

**Comment by pgaudet** [comment]
@asangrador Did InterPro see this ticket ? 

Thanks, Pascale
