### ISSUE TITLE
Proposal to obsolete 'GO:0001167 RNA polymerase I transcription factor activity, sequence-specific DNA binding' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15787]
Dear all,

The proposal has been made to obsolete 'GO:0001167 RNA polymerase I transcription factor activity, sequence-specific DNA binding'

and its 3 children:
'GO:0001169 transcription factor activity, RNA polymerase I CORE element sequence-specific binding'
'GO:0001170 transcription factor activity, RNA polymerase I enhancer sequence-specific binding'
'GO:0001168 transcription factor activity, RNA polymerase I upstream control element sequence-specific binding'

The reason for obsoletion is that these terms have been used to annotate general RNA pol I transcription factors. We have changed the label of GO:0001181 from 'transcription factor activity, core RNA polymerase I binding' to RNA polymerase I general transcription initiation factor activity, so all proteins annotated to GO:0001167, GO:0001168, GO:0001169, and GO:0001170 can be annotated to this term (if they are not already; GO:0001181 ).

* 1 InterPro mapping: InterPro:IPR022793 

**Manual annotations:** 
* GO:0001167 and GO:0001170 have no annotations
* GO:0001168: 4 SGD + 1 pombase
* GO:0001169:  6 pombase 
https://docs.google.com/spreadsheets/d/143SYe5omzyHciGw8Plkz-OzEOaFt9_AV-9jDUASsN7s/edit#gid=0

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/15787

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on May 30, 2018. Unless objections are received by May 30, 2018, we will assume that you agree to this change.

Thanks,

Pascale

**Comment by srengel** [comment]
changed the SGD annotations as requested.  done.

**Comment by pgaudet** [comment]
@ValWood is this OK for you ?

**Comment by ValWood** [comment]
Yep,

Can you do the renaming for
RNA polymerase I general transcription initiation factor activity = GO:0001181
RNA polymerase II general transcription initiation factor activity = GO:0016251
RNA polymerase III general transcription initiation factor activity = GO:0000995

will make it easier for us to reannotate. 

Cheers

Val

**Comment by pgaudet** [comment]
It's done ! We now need to wait for the release. Maybe we can pick that up again after the release (I don't see many options!)

**Comment by ValWood** [comment]
So how often does the ontology  get released? I thought it was daily.

I changed most of my annotations to use the IDs above. The problem is because many of these are ISS and TAS I had to do it in our legacy system. This  system is fussy about the term name and ID matching. I used the new term name so these are not getting through  to our website....I may need to wait to see what I've done to proceed.....

**Comment by pgaudet** [comment]
Yes it is, sorry I was confused. 

But the build has been failing, 
Caused by: java.io.FileNotFoundException: http://snapshot.geneontology.org/ontology/extensions/caro_import.owl

@cmungall @balhoff can this be restored? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 
The changes to 
RNA polymerase I general transcription initiation factor activity = GO:0001181
RNA polymerase II general transcription initiation factor activity = GO:0016251
RNA polymerase III general transcription initiation factor activity = GO:0000995

are now in AmiGO. I am ready to go ahead with the obsoletions proposed here. Is that OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think so,  if others are OK. I can mop up any that I didn't catch tomorrow.

**Comment by pgaudet** [comment]
pombase is the only group with annotations to these 3 terms. I'll merge. 

(Go back to writing ;)

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/pull/15853
