### ISSUE TITLE
Add synonym: Macrophage polarization and regulation terms

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#15791]
Dear GO editors,
It looks like the ontology is not describing the process of macrophage polarization to produce M1 or M2 macrophages that have at least different functions and cytokine expression patterns. The process is described in the following reviews: PubMed=22025054 and PubMed=29455468. I am not sure if it should be a child of macrophage activation/GO:0042116 or macrophage differentiation/GO:0030225 or regulation of macrophage cytokine production/GO:0010935. 
PubMed=28471450, for instance, shows that PJA2 regulates this process.
Thanks for your help.
Best regards.
Lionel

**Comment by pgaudet** [comment]
Hi @lbreuza 
Can you list the exact terms you'd like, definitions and parent? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Added synonyms: 

- macrophage activation = macrophage polarization
- regulation of macrophage activation= regulation of macrophage polarization 
- negative regulation of macrophage activation= negative regulation of macrophage polarization
- positive regulation of macrophage activation = positive regulation of macrophage polarization
- macrophage activation involved in immune response =  macrophage polarization involved in immune response

Thanks, Pascale
