### ISSUE TITLE
MP equatorial cell cortex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15793]
Definition (GO:1990753 GONUTS page)
The region of the cell cortex in a mitotically dividing cell that flanks the central spindle and corresponds to the site of actomyosin ring formation that results in cleavage furrow formation and ingression.

add parent "cell division site" ?

**Comment by pgaudet** [comment]
@ValWood if you are not sure, is there anyone's input in particular you would like ?

**Comment by ValWood** [comment]
well, since "equatorial cell cortex is defined"

The region of the cell cortex in a mitotically dividing cell that flanks the central spindle and corresponds to the site of actomyosin ring formation that results in cleavage furrow formation and ingression.

I think it should be.

**Comment by ValWood** [comment]
Also based on the outcome of:
https://github.com/geneontology/go-ontology/issues/14794

**Comment by pgaudet** [comment]
added 'equatorial cell cortex' part of some 'cell division site'. 

Pascale
