### ISSUE TITLE
GO:0006606 protein import into nucleus is both part_of and is_a protein GO:0034504 localization to nucleus

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15816]
GO:0006606 protein import into nucleus is both part_of and is_a protein GO:0034504 localization to nucleus

Looking at the children of list for GO:0034504 localization to nucleus and the ancestor tree for GO:0006606 protein import into nucleus, both show GO:0006606 protein import into nucleus linked twice to GO:0034504 localization to nucleus.

I thought there was some other issue like this but I can't find it, sorry if this is a known issue

https://www.ebi.ac.uk/QuickGO/term/GO:0034504

https://www.ebi.ac.uk/QuickGO/term/GO:0006606

**Comment by pgaudet** [comment]
Hi @suzialeksander 
This is an interesting one ! I don't know how to see this in Protégé, so I am adding this to 'editors' discussion' to have more information. 

If I remove the asserted 'part of' relation, I dont see that the 'is_a GO:0034504  protein localization to nucleus' in Protege.

**Comment by pgaudet** [comment]
Ready to close - but we still need to discuss at the editors' call.
