### ISSUE TITLE
Merge 'GO:0001789	G-protein coupled receptor signaling pathway, coupled to S1P second messenger' into 'GO:0003376 sphingosine-1-phosphate signaling pathway' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15822]
Hello, 

The single paper annotated 'GO:0001789	G-protein coupled receptor signaling pathway, coupled to S1P second messenger' in fact shows  S1P used as a first messenger WRT the G-protein. 

https://www.nature.com/articles/nature01643

@tberardini can you check and let me know whether you'd be OK with that merge ? 

Thanks, Pascale

**Comment by tberardini** [comment]
@pgaudet  Yes, the merge is fine.  I looked at the paper and annotation from 2004.

**Comment by pgaudet** [comment]
Removed comment: "Sphingosine-1-phosphate (S1P) can act both as an extracellular ligand for cell surface G-protein coupled receptors, and as an intracellular second messenger. GO:0003376 describes a pathway where S1P acts as an extracellular ligand. Where S1P acts within the cell to transmit a signal, consider instead 'intracellular signal transduction ; GO:0035556' or 'G-protein signaling, coupled to S1P second messenger (sphingosine kinase activating) ; GO:0001789'." 

The role as an intracellular signaling molecule has not been clearly shown, see https://en.wikipedia.org/wiki/Sphingosine_kinase. )
