### ISSUE TITLE
regulation terms for GO:0007465 R7 cell fate commitment

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#15824]
Could I request positive/negative regulation terms for:
GO:0007465	R7 cell fate commitment

regulation of R7 cell fate commitment
Def: Any process that modulates the frequency, rate or extent of R7 photoreceptor cell fate commitment. 

positive regulation of R7 cell fate commitment
Def: Any process that activates or increases the frequency, rate or extent of  R7 photoreceptor cell fate commitment. 

negative regulation of R7 cell fate commitment
Def: Any process that stops, prevents, or reduces the frequency, rate or extent of  R7 photoreceptor cell fate commitment. 

Ref for all:
PMID:22878552
GOC:ha

**Comment by hdrabkin** [comment]
Somehow lost in email notice
+id: GO:0106396
+name: regulation of R7 cell fate commitment
+id: GO:0106397
+name: positive regulation of R7 cell fate commitment
+id: GO:0106398
+name: negative regulation of R7 cell fate commitment
