### ISSUE TITLE
Proposal to obsolete children of 'receptor transactivation' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15823]
Hello, 

While working on the GPCR branch, I came across two children of the term 'receptor transactivation' (GO:0035624) : 

GO:0035625    epidermal growth factor-activated receptor transactivation by G-protein coupled receptor signaling pathway  - 5 annotations BHF
GO:0038040                cross-receptor activation within G-protein coupled receptor heterodimer - 0 annotations

With @RLovering we propose that these terms be obsoleted and that the target of receptor transactivation be captured as GO-CAM models (or with annotation extensions). 

If there are no objections I will proceed to the obsoletion on June 1st, 2018. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@vanaukenk @ukemi @thomaspd @hattrill @selewis 
Do you think we should keep these terms ?

**Comment by hattrill** [comment]
@pgaudet, I am happy to do away with these terms.

**Comment by pgaudet** [comment]
Question for editors: do we want to keep these terms ?
