### ISSUE TITLE
IDs missing for never_in_taxon for pellicle

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#15832]
```
[Term]
id: GO:0020039
name: pellicle
namespace: cellular_component
def: "The structure enclosing certain parasite cells such as certain apicomplexa and Euglenozoa; consists of the cell membrane with its associated infrastructure of microtubules, microfilaments and other organelles." [GOC:mah, GOC:mb]
is_a: GO:0044464 ! cell part
property_value: never_in_taxon "Bacteria" xsd:string
property_value: never_in_taxon "Opisthokonta" xsd:string
```

I'm not sure if this happened in Protege or some kind of odd conversion error

**Comment by pgaudet** [comment]
@cmungall 
FYI When I changed something else in the ontology (#15815), the line you modified got further modified to 

-relationship: never_in_taxon NCBITaxon:2 ! Bacteria <prokaryote>
+relationship: never_in_taxon NCBITaxon:2 ! Bacteria

The change seems OK but I was surprised to see this. 
Thanks, Pascale
