### ISSUE TITLE
lysosome membrane instead of  lysosomal membrane

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#15835]
Hi,
Could please change the term to lysosome membrane because for instance there is endosome membrane and not endosomal membrane. Alternatively one could at least add it as a synonym. When one search lysosome AND membrane, the term never appears.
Thanks for your help.
Lionel

**Comment by cmungall** [comment]
I unassigned @dougli1sqrd as I assume that wasn't deliberate @ukemi ?

**Comment by ukemi** [comment]
I assign @dougli1sqrd to tickets that we look at together on Fridays. We have been doing tickets together so that he can become familiar with ontology editors' workflow and have an understanding of the kinds of things we check and consider when addressing a ticket.

**Comment by lbreuza** [comment]
Hi,
you have closed the ticket but I do not know if you have accepted or not the proposed change.
Thanks

**Comment by ukemi** [comment]
I have added it as a synonym.
