### ISSUE TITLE
GO:0001077 "transcriptional activator activity, RNA polymerase II proximal promoter sequence-specific DNA binding" should be related to "binding"?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15843]
GO:0001077 transcriptional activator activity, RNA polymerase II proximal promoter sequence-specific DNA binding

We were just looking at this term, and it seems it should somehow be related to  GO:0043565
sequence-specific DNA binding? There's currently no link to any binding terms, is this intentional?

https://www.ebi.ac.uk/QuickGO/term/GO:0001077

Thanks

**Comment by pgaudet** [comment]
Hi @suzialeksander 

yes, it was intentional in the 2011 transcription factor ontology work, the terms are not connected. It's been confusing, and some of the changes we are doing now are aimed at addressing this issues (among others). 

Thanks, Pascale

**Comment by ukemi** [comment]
There is a relationship, it is just not visible in QuickGO. Any flavor of has_part is not visible, but it is in the full ontology.

**Comment by ukemi** [comment]
This is an anonymous ancestor in the ontology:

'has part' some 'RNA polymerase II proximal promoter sequence-specific DNA binding'
