### ISSUE TITLE
MBF transcription complex assembly

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#15854]
id: GO:new
name: MBF transcription complex assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of a set of components to form an MBF transcription complex." 
synonym: "DSC1 transcription factor complex assembly" EXACT []
synonym: "MBF complex assembly" EXACT []
synonym: "Mlu1-box binding factor assembly" EXACT []
is_a: GO:0034622 ! cellular protein-containing complex assembly

results in formation of GO:0030907

Suggested def is standard wording with this particular complex slotted in. Val has requested a phenotype term for PMID:9303312, and from a quick glance it looks like that paper can be used for the GO def as well.

**Comment by krchristie** [comment]
@mah11 - Thanks for the complete stanza info, as usual. It makes your tickets so quick & easy to do! :)

**Comment by mah11** [comment]
I haven't forgotten the view from the other side of a GO ticket ;)

Thanks for adding.
