### ISSUE TITLE
Fix Jenkins failure due to 'consider altid'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15859]
GO:0016986 obsolete transcription initiation factor activity 
had 'consider' GO:0000996 which is a secondary ID to sigma factor activity (GO:0016987)

What's weird is that the change was merged April 20th (according to QuickGO, so probably even earlier), and only now we get a failure. 

Also this should have failed at the Travis checks. I'll create a new ticket for Eric to add this check. 

Thanks, Pascale

**Comment by ukemi** [comment]
Hmmm. I thought we already had this check in Travis.

**Comment by pgaudet** [comment]
I thought so too. @dougli1sqrd - can you help ?
