### ISSUE TITLE
Are "food intake" and "energy expenditure" BP?

### ISSUE THREAD

**Issue by pengyubio** [geneontology/go-ontology#15851]
homeostasis is a BP. https://www.ebi.ac.uk/QuickGO/search/homeostasis

"energy homeostasis" is a BP (it is not included in GO though). wikipedia says "... is a biological process that involves the coordinated homeostatic regulation of food intake (energy inflow) and energy expenditure (energy outflow)."

So should "food intake" and "energy expenditure" be also considered as BPs.

**Comment by ukemi** [comment]
This becomes difficult when we try to make the definition fit all organisms.

**Comment by pgaudet** [comment]
It's strange - I cannot find the ticket where  GO:0097009 "energy homeostasis"'s obsoletion has been announced. 

Pascale

**Comment by pengyubio** [comment]
@ukemi Could you elaborate more on your comments? Are you referring that "energy homeostasis", "food intake" or "energy expenditure" may not be appropriate for all organisms? 

> This becomes difficult when we try to make the definition fit all organisms.

**Comment by ukemi** [comment]
I was actually thinking about food intake and energy expenditure. Does intake of food always directly relate to energy inflow or is it also used for other things? It seems to me that defining specific processes for energy expenditure is even more vague. I also couldn't find a proposal to obsolete energy homeostasis, but I was a bit surprised it wasn't on your radar.

**Comment by pgaudet** [comment]
If there are no papers describing the processes (food intake and energy expenditure) I'll assume for now that energy homeostasis is sufficient. 

I'll add the 'food intake' and 'energy expenditure' as narrow synonyms. 

Thanks, Pascale
