### ISSUE TITLE
new term request: L-arginine 3-hydroxylase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#15856]
Dear GO annotators,

I need your help to create a new term to describe the activity of Q8N371_KDM8 :
L-arginine 3-hydroxylase activity (PMID:29563586)
RHEA:56744: 2-oxoglutarate + [protein]-L-arginine + O2 = [protein]-(3R)-3-hydroxy-L-arginine + CO2 + succinate
As child of GO:0016706

Many thanks,

Nevila Hyka-Nouspikel

**Comment by ValWood** [comment]
Hi @vanaukenk  can this be added?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140554
+name: L-arginine 3-hydroxylase activity
+namespace: molecular_function
+def: "Catalyzes the reaction: 2-oxoglutarate + [protein]-L-arginine + O2 = [protein]-(3R)-3-hydroxy-L-arginine + CO2 + succinate." [PMID:29563586, RHEA:56744]
+xref: RHEA:56744
+is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/15856 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-20T13:32:53Z
