### ISSUE TITLE
general transcription factor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15866]
should "general transcription factor" be called "general transcription initiation factor"?
(based on existing children)

![initiation](https://user-images.githubusercontent.com/7359272/40991196-e3939308-68ea-11e8-9aa7-407b36fed27b.jpg)

**Comment by pgaudet** [comment]
I was trying to keep it simpler but I agree it should be consistent. 

Pascale

**Comment by ValWood** [comment]
but we have general elongation factors to, like
general transcription elongation factor TFIIS?

**Comment by ValWood** [comment]
Although it is defined:
Definition 
An activity that contributes to transcription start site selection and transcription initiation.

So  should I use something else for "general elongation factors"?

**Comment by ValWood** [comment]
Also, for
general transcription factor activity
An activity that contributes to transcription start site selection and transcription initiation.

aren't the "functions" more accurately  "start site selection" and "recruitment" - the process is transcription initiation?

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/pull/15867/commits/7f59f2fd8b80949d406841339095ea9fff9da017
