### ISSUE TITLE
add taxon restriction to GO:0104005

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15871]
never in Schizosaccharomyces

(I get confused by who would use these terms in annotation, should it be "only in virus"?)

**Comment by pgaudet** [comment]
In fact, it should be 'never in symbiont'. 

This is to represent a host protein's function in a symbiont/viral process. How is this term causing problem for pombe ?

**Comment by ValWood** [comment]
We try to block all branches that are not relevant to our users. It makes it easier for community curators to locate/choose terms when navigating down.

**Comment by ukemi** [comment]
But in a symbiotic relationship, both organisms are symbionts. There are three kinds of symbiotic relationships: mutualism, commensalism and parisitism.

**Comment by pgaudet** [comment]
Right but we only annotate from one organism's perspective at a time - don't we ?

**Comment by ukemi** [comment]
Yes, but never in symbiont would exclude both. I think never in Schizosaccharomyces will satisfy @ValWood 's needs. It will still allow us to use the term for other taxa.
