### ISSUE TITLE
NTR: Negative regulation of CD4 positive, alpha-beta memory T cell  proliferation

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#15879]
Hi, 
New term requested: Negative regulation of CD4-positive, alpha-beta memory T cell  proliferation

Request is supported by figure 2 in paper PMID: 24691993
Parent term: 
GO:2000562  "negative regulation of CD4-positive, alpha-beta T cell proliferation" 

Thank you,

Mila

**Comment by vanaukenk** [comment]
@milarolo 
Also for this term, is this the correct cell type:
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000897
Thanks.

**Comment by milarolo** [comment]
Yes, that is correct

Mila

**Comment by milarolo** [comment]
Any decision  taken on this issue?
Mila

**Comment by pgaudet** [comment]
Closing, we should use extensions/GO-CAMs to represent such specific cell types.
