### ISSUE TITLE
URI for go "shorthand" annotation is not resolving.

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [geneontology/go-ontology#15881]
Its my understanding that all URI's associated with ontology terms should resolve?  But

    http://www.geneontology.org/formats/oboInOwl%23shorthand breaks, and\

    http://www.geneontology.org/formats/oboInOwl#shorthand

yields an RDF file that has no mention of "shorthand" in it. I see file is dated from 2012.  Was a past decision made to phase out "shorthand" in favour of "hasSynonym" ? I want to hold onto semantics that things like MIC and LASER as abbreviations (if not acronyms).

Secondly I wanted to know if shorthand is an annotation that also covers abbreviation annotations.  Currently there is http://purl.obolibrary.org/obo/HP_0045077 which I was going to use, but I see GO shorthand seems much more common.

**Comment by cmungall** [comment]
Hi Damion,

This isn't really in scope for GO, the oboInOwl vocabulary is housed with us for historic reasons, but it is used by multiple applications.

The shorthand property has nothing to do with synonyms. You can find a technical description of it here http://owlcollab.github.io/oboformat/doc/obo-syntax.html (TL;DR - you don't need to worry about it if you aren't using obo format).

We don't indicate abbreviations in any systematic way in GO. You may want to look at how Uberon annotates a synonym as being an abbreviation: https://github.com/obophenotype/uberon/wiki/Using-uberon-for-text-mining

Follow up any Qs on https://github.com/information-artifact-ontology/ontology-metadata/issues

Thanks!
