### ISSUE TITLE
Is cancer excluded from GO?

### ISSUE THREAD

**Issue by pengyubio** [geneontology/go-ontology#15882]
I don't see `growth of cancer` mentioned in GO. But there is `response to tumor cell`. Can I understand that any BP about cancer itself cannot be included but other BP in response to cancer can be included in GO_BP?

**Comment by pgaudet** [comment]
Cancer is definitely excluded (see my comment in #15849). For diseases you should consider Disease Ontology.

Pascale

**Comment by addiehl** [comment]
The reason that response to cancer is included is that there are genetically programmed mechanisms in the immune system to spot and eliminate tumor cells, such as the KIR receptors of natural killer cells that detect if MHC class I molecules are missing on cells, as is common for many tumor cells.  Just like pathogenic symbionts, cancer is a naturally occurring threat and there are genes and proteins that have evolved to combat that threat.

Growth of cancer cells is considered abnormal, as typically mechanisms contributing to cancer growth represent a diversion from the normal mechanisms regulation cell proliferation.
