### ISSUE TITLE
Should taxon contraints be inherited over all relations? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15888]
@cmungall 

Following up on #15887 

It seems to me that the taxon constraints shouldn't be inherited over 'capable_of_part_of '; where are the rules for this ? 

Thanks, Pascale

**Comment by deustp01** [comment]
My hunch (i.e., no good argument) is the opposite. Could you give an example where inheriting a constraint is wrong? Thanks

**Comment by pgaudet** [comment]
From #15887

exocyst has 
relationship: capable_of_part_of GO:0097712 ! vesicle targeting, trans-Golgi to periciliary membrane compartment

and GO:0097712 has:
Never in Taxon 4890 Ascomycota


Isn't it possible that a structure/complex (perhaps even organelle) has different roles in different species ? 

Pascale

**Comment by mah11** [comment]
To me inheriting constraints over relations like capable_of_part_of seems to make sense, and the problem here is which capable_of_part_of links should be present in the first place.

> Isn't it possible that a structure/complex (perhaps even organelle) has different roles in different species?

Certainly. But in such cases, a capable_of_part_of link shouldn't be included in the ontology. It's not true that every instance of an exocyst can participate in an instance of a GO:0097712 process, but by including the capable_of_part_of link GO is claiming that all do have that ability.

**Comment by pgaudet** [comment]
OK - @krchristie Did you create this relation ? Are you ok to remove it ?

**Comment by cmungall** [comment]
To answer the question in the title of the ticket: No, taxon constraints should not propagate over all relations. It is possible to regulate processes in other species for example. It is also possible to be located_in another species (but not part_of).

The current set of property chains is conservative. It does however include the capable_of and capable_of part_of relations. This is an interesting case as there is amount of fudging hidden in the 'capable' word. But I agree with others that the correct thing to do here is to be more conservative with assigning function to complexes in the ontology. The original intent was only to do this when the relationship was true by definition. The ontology is for generalizations that always hold, annotations for everything else.

**Comment by cmungall** [comment]
PR to remove relationship: #15891

**Comment by krchristie** [comment]
@pgaudet - I am not sure which relationship for which term you are asking about.

**Comment by pgaudet** [comment]
@krchristie 

exocyst has
relationship: capable_of_part_of GO:0097712 ! vesicle targeting, trans-Golgi to periciliary membrane compartment

and GO:0097712 has:
Never in Taxon 4890 Ascomycota

**Comment by krchristie** [comment]
I don't recall doing either of these things, but this relationship: 

```
exocyst has
relationship: capable_of_part_of GO:0097712 ! vesicle targeting, trans-Golgi to periciliary membrane compartment
```

seems inappropriate since I think the exocyst is conserved in organisms which do not have cilia.

This taxon constraint: 
```
GO:0097712 has:
Never in Taxon 4890 Ascomycota
```

seems true, but insufficient.

**Comment by ukemi** [comment]
Relationship removed in above pull request.
