### ISSUE TITLE
taxon restriction  fixes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15887]
Terms seem to have disappeared from Canto, see the ticket  I just opened:
https://github.com/pombase/canto/issues/1489

**Comment by ValWood** [comment]
This seems to be caused by inappropriate taxon restrictions.

**Comment by ValWood** [comment]
We think the exocyst problem is due to:

relationship: capable_of_part_of GO:0097712 ! vesicle targeting, trans-Golgi to periciliary membrane compartment

and GO:0097712 has:
Never in Taxon 	4890 	Ascomycota

**Comment by ValWood** [comment]
This is quite urgent as we cant use "exocyst " terms of approve sessions containing this term

**Comment by pgaudet** [comment]
hi @ValWood 

How can you not have endoreduplication, but the regulation exist?

**Comment by cmungall** [comment]
My PR removes the functional relationship. For a general discussion on whether this should be propagated hop over to #15888

**Comment by ukemi** [comment]
So does this ticket have to do with a build issue or something that needs to be done (or is done) in the ontology?

**Comment by ValWood** [comment]
Sorry I thought I changed the label to taxon restriction fixes last night.

I get a bit confused  with endoreduplication.  Pombe can do it, but it isn't part of its' normal lifestyle and there is a signalling pathway to suppress it. Maybe it should not have a taxon restriction? I'm not sure. @mah11  ?

@cmungall  do we need to do anything especially for "capabale of part of". I presumed these relationships should always be true, and this one isn't.

pombe does not do GO:0097712    
vesicle targeting, trans-Golgi to periciliary membrane compartment
because it doesn't have a  "periciliary membrane compartment"
should that relation be removed?

**Comment by cmungall** [comment]
Your assumption is correct, my pull request removes the relationship, if @ukemi or any of the ontology team approves an merges it then this will be fixed in the next snapshot release

**Comment by ukemi** [comment]
@ValWood  if this solves the problem, please close this ticket.

**Comment by ValWood** [comment]
is that committed? It still doesn't show up in Canto or here https://www.ebi.ac.uk/QuickGO/term/GO:0000145
For canto changes are usually visible next day.

**Comment by ValWood** [comment]
reopening as the change did not come through?

**Comment by ukemi** [comment]
It looks like the svn pipeline is hung up on something. We will investigate. The change is there in the snapshot release.

**Comment by ukemi** [comment]
Hi @ValWood 

Are you getting your ontology from the PURL on the GO site? It is pointing to the snapshot.

**Comment by ValWood** [comment]
I forget...I need to ask @kimrutherford

**Comment by ukemi** [comment]
OK. Let me know and if the problem still isn't corrected maybe we can chat by skype.

**Comment by kimrutherford** [comment]
We usually use http://purl.obolibrary.org/obo/go/extensions/go-plus.owl but last week I noticed that it was causing an internal error in owltools when we make the pombe-only subset.  I assumed it was a temporary glitch so I switched to the SVN go-plus.owl to get our nightly cron job working again.

I just tried the PURL go-plus.owl again with owltools.  There's still an error so I've now reported it:
  https://github.com/owlcollab/owltools/issues/260

**Comment by ukemi** [comment]
@dougli1sqrd can you try to troubleshoot this?

**Comment by ValWood** [comment]
Hi Doug, any news on this? We still can't use this term due to taxon constraints:

![problem](https://user-images.githubusercontent.com/7359272/41402939-7ff796be-6fbb-11e8-91ba-ed6ec4afc79a.jpg)

**Comment by kimrutherford** [comment]
> I just tried the PURL go-plus.owl again with owltools. There's still an error so I've now reported it:
> owlcollab/owltools#260

I've just tried again and the PURL go-plus.owl now works fine with owltools.  So I've switched our nightly update back to using that.

@ValWood: that term (GO:0000145) is available in Canto now.

**Comment by ValWood** [comment]
OK thanks!
