### ISSUE TITLE
NTR: Negative regulation of CD4-positive, alpha-beta effector T cell proliferation

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#15880]
Hi, 
New term requested: Negative regulation of CD4-positive, alpha-beta effector T cell  proliferation

Request is supported by figure 2 in paper PMID: 24691993
Parent term: 
GO:2000562  "negative regulation of CD4-positive, alpha-beta T cell proliferation" 

Thank you,

Mila

**Comment by vanaukenk** [comment]
Hi @milarolo 
Just to confirm, is this the correct cell type for this term:
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001044
Thx.

**Comment by milarolo** [comment]
Yes that is correct
Mila

**Comment by milarolo** [comment]
Any decision taken in this issue?
Mila

**Comment by pgaudet** [comment]
Closing, we should use extensions/GO-CAMs to represent such specific cell types.
