### ISSUE TITLE
add parent grouping term "purine phosphoribosyltransferase"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15897]
for
hypoxanthine phosphoribosyl- transferase, 
xanthine phosphoribosyltransferase 
guanine phosphoribosyl- transferase
adenine phosphoribosyltransferase activity
any others?

PMID:5123876

**Comment by hdrabkin** [comment]
Catalysis of the reaction RMP + diphosphate = R + 5-phospho-alpha-D-ribose 1-diphosphate.
R is single letter abbreviation for puRine
Child of GO:0016763

**Comment by hdrabkin** [comment]
GO:0106130 added. Done

**Comment by ukemi** [comment]
@deustp01, @goodb, @vanaukenk 

This bit of the ontology is a good test of our work. We will need to create a logical def for the term Harold added.

**Comment by goodb** [comment]
It doesn't look like there is an exact match for this in RHEA right now.
Would need some help selecting the right CHEBIs but then easy to make the
definition.

**Comment by ukemi** [comment]
Worth doing, even if it is just to test the reasoning.  Great call today.

**Comment by ukemi** [comment]
Let's try this, with the biochebi equivalencies it should work:

xanthine phosphoribosyltransferase = RHEA:10800 (note this is the master, not what we currently map to)
hypoxanthine phosphoribosyltransferase activity = RHEA:17973
adenine phosphoribosyltransferase activity = RHEA:16609
guanine phosphoribosyltransferase = RHEA:25424 (clearly we have holes in our mapping!)

purine phosphoribosyltransferase activity = GO_0003824
 and (has_substance_bag some 
    (SubstanceSet
     and ((has_member_part some 
        (CHEBI_26386
         and (has_stoichiometry value "1"^^xsd:string)))
     and (has_member_part some 
        (CHEBI_58017
         and (has_stoichiometry value "1"^^xsd:string))))))
 and (has_substance_bag some 
    (SubstanceSet
     and ((has_member_part some 
        (CHEBI_33019
         and (has_stoichiometry value "1"^^xsd:string)))
     and (has_member_part some 
        (CHEBI_37021
         and (has_stoichiometry value "1"^^xsd:string))))))
