### ISSUE TITLE
term request: starch granule initiation

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#15892]
term:starch granule initiation
definition:The sequence of events that initiates (or primes) the synthesis of semi-crystalline starch granules within photosynthetic chloroplasts or non-photosynthetic amyloplasts.
suggested parentage: is a GO:0019252 starch biosynthetic process

Reference(s):Seung et al. 2017; doi: 10.1105/tpc.17.00222

Term suggested by a user trying to annotate MFP1 (At3g16000) and MRC (At4g32190),  PTST2 (At1g27070) and PTST3 (At5g03420)

**Comment by ukemi** [comment]
PMID:28684429
