### ISSUE TITLE
missing parents or odd arrangement, purine nucleotide salvage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15898]
![mp](https://user-images.githubusercontent.com/7359272/41260926-69a13d3e-6dd1-11e8-8744-e0299315f54a.jpg)

**Comment by ValWood** [comment]
There should be a connection here

1. guanine salvage missing purine nucleotide parent

2. I also noticed that 

GO:0043103 | hypoxanthine salvage
has narrow synonyms 


guanine, xanthine and their nucleoside salvage | narrow
-- | --
adenine, hypoxanthine and their nucleoside salvage | narrow

but does not have these as children...

**Comment by ukemi** [comment]
But guanine is just the base. Seems ok to me, but should look at the pathway.

**Comment by deustp01** [comment]
Yes. Textbook salvage starts with the free purine base and yields base-ribose-monophosphate https://en.wikipedia.org/wiki/Hypoxanthine-guanine_phosphoribosyltransferase

**Comment by ValWood** [comment]
Yup. I'm using totally the wrong processes!
