### ISSUE TITLE
go-plus equates ChEBI independent continuants and SO generically dependent continuants

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#15894]
The go-lego ontology (the ontology used in Noctua, which imports go-plus) has hundreds of unsatisfiable classes that result from disjointness of 'independent continuant' and 'generically dependent continuant'. The disjointness axiom is asserted in ECO, which is imported into go-lego (but it is declared in BFO as well). Problematic class relationships include:

- `CHEBI:messenger RNA` == `SO:mRNA`
- `SO:transcript` SubClassOf `CHEBI:ribonucleic acid`

and several other related classes. How are these bridges between SO and ChEBI being used?

**Comment by ukemi** [comment]
We should look at this closely as a group. I think it is interesting. We will need to look more closely at exactly how we use these. It will be a good group exercise.

**Comment by balhoff** [comment]
After a little more investigation @ukemi and I see that the link from the SO terms to 'generically dependent continuant' is not asserted in SO, but is actually being asserted by OBI. Presumably ECO imports this content from OBI. However @cmungall's paper at https://doi.org/10.1016/j.jbi.2010.03.002 makes it clear that the SO terms are intended to be subclasses of 'generically dependent continuant'.

The paper mentions a "SOM" hierarchy (Sequence Ontology:Molecules) which would contain the actual molecules that would be material entities. There is a mention of this on the [SO wiki](http://www.sequenceontology.org/so_wiki/index.php/SOM) but it doesn't seem actively maintained.

So... in the short term we could exclude ECO from Noctua reasoning (but it needs to be available for autocomplete), but it seems like SO terms and ChEBI terms should be related in a different way, and GO should make sure material entity terms are used where that is intended.

**Comment by balhoff** [comment]
I just came across the [Molecular Sequence Ontology (MSO)](https://github.com/The-Sequence-Ontology/MSO) project by @mikebada and @msinclair2 and see that @cmungall and @nataled have been active there. So I'm guessing there is already a plan to deal with this issue.

**Comment by cmungall** [comment]
not sure when MSO will be ready we need an interim plan..

**Comment by msinclair2** [comment]
We are nearing completion, we hope to be ready to release by the end of October (2018), but Mike Bada can tell you more.  The MSO, but not the refactored SO, is pretty much in its final form, but its classes have to be updated as many additions have been made since when we started working on it.

My opinion is that, if all you need is the bridge and are working with the molecules (MSO), which I believe is what most of GO would form its cross products with, then the necessary relation, "generically depends on", has already been implemented.  You can download MSO_reasoned.owl, and SO_refactored.owl, from the MSO repo under files.  SO_refactored.owl is not ready to be reasoned over quite yet, and not all necessary axioms have been transferred, but you can find the SO class you need by searching for the label.  You'll see it is asserted to generically depend on some MSO IRI.  You can then find that IRI in the MSO and import that class into go-lego, because all the relevant MSO classes are independent continuants.

**Comment by balhoff** [comment]
I'm wondering how things would be structured if we went ahead and revised usage of SO terms to reflect inheritance from generically dependent continuant. We would need to revise the "bridge equivalences" and also usages of SO terms as chemical entities in GO logical definitions. I'm not sure of the exact preferred pattern, but looking in RO I imagine it to be something like this:

For the equivalence definitions, we would change

old: [CHEBI:messenger RNA](http://purl.obolibrary.org/obo/CHEBI_33699) == [SO:mRNA](http://purl.obolibrary.org/obo/SO_0000234)

to

new: [CHEBI:messenger RNA](http://purl.obolibrary.org/obo/CHEBI_33699) == [bearer of](http://purl.obolibrary.org/obo/RO_0000053) some ([concretizes](http://purl.obolibrary.org/obo/RO_0000059) some [SO:mRNA](http://purl.obolibrary.org/obo/SO_0000234))

and then change a definition for a particular GO term like so:

old: [GO:mRNA polyadenylation](http://purl.obolibrary.org/obo/GO_0006378) == [GO:RNA polyadenylation](http://purl.obolibrary.org/obo/GO_0043631) and ([has output](http://purl.obolibrary.org/obo/RO_0002234) some [SO:polyadenylated_mRNA](http://purl.obolibrary.org/obo/SO_0000871))

to 

new: [GO:mRNA polyadenylation](http://purl.obolibrary.org/obo/GO_0006378) == [GO:RNA polyadenylation](http://purl.obolibrary.org/obo/GO_0043631) and ([has output](http://purl.obolibrary.org/obo/RO_0002234) some ([bearer of](http://purl.obolibrary.org/obo/RO_0000053) some ([concretizes](http://purl.obolibrary.org/obo/RO_0000059) some  [SO:polyadenylated_mRNA](http://purl.obolibrary.org/obo/SO_0000871))))

Is this the right way to relate these?

**Comment by msinclair2** [comment]
> revised usage of SO terms to reflect inheritance from generically dependent continuant

This is exactly what we are doing with SO refactored.

> usages of SO terms as chemical entities

These are available in MSO.  That's what MSO is.

> old: CHEBI:messenger RNA == SO:mRNA
> 
> to
> 
> new: CHEBI:messenger RNA == bearer of some (concretizes some SO:mRNA)

You just need:

CHEBI:messenger RNA == MSO:mRNA

In the definition of SO:mRNA refactored, there is SO:mRNA generically depends on MSO:mRNA.

Concretizes is not the right relation here, I believe.  "Generically depends on" does not currently exist in the RO.  I have raised this issue on the RO but received no response.  It _should_ be there.  Consult Arp et. al. for the definition on p. 105.

**Comment by balhoff** [comment]
Thanks @msinclair2, yes it sounds like it would be best for GO to be able to use MSO directly. In the meantime it might be worth updating our definitions with these (or corrected) patterns. Thanks for the info on 'generically depends on'; is there an inverse that could go from the independent continuant to the generically dependent continuant?

**Comment by msinclair2** [comment]
Yes @balhoff, the inverse would be "generic bearer of".  I've been trying to wake up @cmungall several times (nudge nudge) to get these into the RO.  I'm not making them up, they are part of BFO. In the interim we have simply created this relation as part of the refactored SO.

@balhoff please look at our [MSO_reasoned.owl](https://github.com/The-Sequence-Ontology/MSO/blob/master/files/MSO_reasoned.owl).  And consider actively participating.  We need the input of someone who would actually use the new ontologies in logical definitions.  One of the main goals of this project was to get SO out of its logical silo, the existence of which you have discovered in this issue.

**Comment by mikebada** [comment]
I agree that I think we can be ready on the order of several months.  I think the MSO is in good shape, although right now I’m trying to replace as many of the MSO/SO-specific object properties with RO relations instead.  (Speaking of which, Chris, is has_component here to stay in the RO?  We had to create some new relations for the exact use case specified in its comment, i.e., for assigning cardinality to has_part assertions, but I think we could use has_component instead.)   I think the main tasks left to do are mostly engineering, including automatically generating the SO from the MSO (much of which is finished), generating .obo files, and quality control.

**Comment by mikebada** [comment]
Jim, I think your new axiomatizations are correct if you want to link to SO classes (as generically dependent continuants).  If there are efforts already underway at formally linking to SO/MSO classes, we’d be interested in collaborating.

**Comment by cmungall** [comment]
Ideally we would have no dependencies on any ontologies that were not 
available using standard OBO PURLs for classes and the ontology, but we 
need the full import closure to be coherent so if hardcoding some 
temporary URLs works for us for now...

**Comment by cmungall** [comment]
Yes, 'has component' is the standard way to represent cardinality, it's 
used a lot in uberon

having said that our strategy is often to isolate non-EL axioms and 
reason on those in the advance

**Comment by msinclair2** [comment]
Mike, I think if Jim would like to bypass the MSO as it currently is, he should just use:

[CHEBI:messenger RNA](http://purl.obolibrary.org/obo/CHEBI_33699) == generic bearer of some [SO:mRNA](http://purl.obolibrary.org/obo/SO_0000234) 

as soon as 'generic bearer of' gets added to the RO.  IMO 'concretizes' should not be used as a workaround for generic dependence per se.  The main issue was not having generic dependence and its inverse in the RO.  As soon as I learn how to make pull requests I will make one for this for the RO.

**Comment by msinclair2** [comment]
On the other hand, if go-lego _requires_ the specification of an SDC (as a quality most likely) then I agree about the use of concretizes.  Does it make sense to do that here?

**Comment by balhoff** [comment]
@msinclair2 right, if we can avoid specifying the intermediate specifically dependent continuant, that would be preferred I think.

**Comment by msinclair2** [comment]
@cmungall created pull request [#233](https://github.com/oborel/obo-relations/pull/233) to add generically depends on and inverse.

**Comment by msinclair2** [comment]
@balhoff There is now a shortcut relation called "[is carrier of](https://github.com/oborel/obo-relations/pull/233#issuecomment-416247335)" incorporated into RO (or soon to be) to fulfill the role you initially requested [above](https://github.com/geneontology/go-ontology/issues/15894#issuecomment-399575705).

**Comment by ukemi** [comment]
@balhoff, I thought this one was fixed. Should we close it?

**Comment by balhoff** [comment]
I wouldn't call it fixed, but we alleviated the problem by not pulling in the disjointness axioms from OBI. Since the plan with regard to MSO and SO is being actively discussed elsewhere, I guess we can close this and revisit once MSO is officially released.

**Comment by cmungall** [comment]
Correct
