### ISSUE TITLE
GO:0090485    chromosome number maintenance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15901]
I think we should obsolete this term.
It isn't clear what it means. It is defined as
The maintenance of the standard number of chromosomes in a cell.

this could mean  many things, ~but its more a phenotypes thana process~, but its very ambiguous

It has no reference, is a very high level stub.

There is  1 experimental annotation.

Other terms to consider (perhaps)
GO:0042023    DNA endoreduplication ?
GO:0007059 chromosome segregation
GO:1903467    negative regulation of mitotic DNA replication initiation

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0090485 chromosome number maintenance. The reason for obsoletion is that this term represents a phenotype, and could be captured by other terms such as GO:0007059 chromosome segregation or GO:1903467 negative regulation of mitotic DNA replication initiation. 

There is a single annotation to WBGene00006940 @vanaukenk 

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/15901

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on July 9, 2018. Unless objections are received by July 9, 2018, we will assume that you agree to this change.

Thanks,

Pascale

**Comment by deustp01** [comment]
Don't know how useful this specific term is but it really does not sound like a phenotype. Consider GO:0042593 glucose homeostasis, a legitimate biological process term (unlike hyperglycemia or hypoglycemia, which are phenotypes). By analogy, maintenance of euploidy sounds like a process; aneuploidy sounds like a phenotype.

**Comment by ValWood** [comment]
Amended comment to say "very ambiguous" , mainly it isn't clear what process it refers to.

**Comment by vanaukenk** [comment]
Hi,
Looking at the paper in question, it looks like the annotation may be resulting from the observation that loss of wee-1.3 activity results in polyploidy, with the actual underlying processes affected being oocyte meiotic arrest and oocyte maturation.
@ValWood - it looks like this annotation is coming from UniProt_GOA.
I've assigned George so that he can follow up with the GOA curator.  
Thx.

**Comment by ValWood** [comment]
OK in this case it is representing a phenotype. This is what I was trying to articulate above.

Basically cdc2-pathway positively regulated DNA replication in S-phase and negatively regulates in G2. so if you lose wee1 inhibition you will get re-replication without mitosis (increase in ploidy)

It's just "negative regulation of initiation" at inappropriate time.

The increase in ploidy is not a normal process for the cell type in question (presumably)

**Comment by ggeorghiou** [comment]
Hi all, the annotation has been changed.

**Comment by ValWood** [comment]
Hi @ggeorghiou  note that  if you used "negative regulation of DNA replication"  specify  
during "mitotic G2 phase" or whatever is appropriate, in an extension. Otherwise (because this pathway +vely regulates the same processes  during S-phase   the annotation becomes confusing. I fell into this trap earlier...

**Comment by ValWood** [comment]
Although I didn't read the paper, this might not be appropriate !
...and it was meiotic...

**Comment by ValWood** [comment]
I looked at the paper.  nuclear division is blocked, but because   wee1 inhibition of cdc1 is relieved,  replication is reinitiated.   I don't know how this phenotype should be interpreted in terms of 
worm oogenesis though....  I guess  anything required for a meiotic cell cycle is part of oogenesis in a worm?


You probably wouldn't make  "negative regulation of DNA replication" from this paper as this annotation requires a bit more context.

...interesting...

**Comment by pgaudet** [comment]
Hi @deustp01 and everyone, 

I lean torwards @ValWood 's interpretation that chromosome number maintenance represents too many distinct processes to be needed in GO. Homeostasis is a little different because we don't always have a way to describe it otherwise; in this case it seems like to do. Perhaps a merge would be better, so as to keep that term label as a synonym somewhere? (for example into GO:0007059 chromosome segregation) ? 

Pascale

**Comment by ValWood** [comment]
I would obsolete.
The experiment being annotated to this term had *absolutely nothing* to do with chromosome segregation.

**Comment by deustp01** [comment]
Someone's annotation mistake isn't really a reason to obsolete a term.

On the other hand, it's really high-level and vague - maybe even keep as a do-not-annotate (or annotate only when nothing more concrete is supported by the evidence) grouping term?

**Comment by ValWood** [comment]
But we don't know exactly what it means,  and it's a "stub" it has no children.

There are other correctly positioned terms that probably almost certainly cover what the requester intended.... from our best guesses.....

but as defined

The maintenance of the standard number of chromosomes in a cell.

could relate to a number of processes (regulation of DNA endoreduplication being one).
