### ISSUE TITLE
Redefine or modify the curator comment for ubiquitin ligase inhibitor activity (GO:1990948)?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15904]
_From @robnash on June 13, 2018 19:7_

Hi,

I was annotating a novel protein shown to be an inhibitor of the Anaphase-Promoting Complex/Cyclosome (APC/C), acting on two mitotic forms of the APC/C, APC/C-cdc20 and APC/C-cdh1 from new paper by Schuyler et al., 2018 (29883473)

I was going to annotate to GO:1990948 ubiquitin ligase inhibitor activity and use column 16 inputs to specify both APC/C-cdc20 (CPX-760) and APC/C-cdh1 (CPX-761). However, associated with this term is curator comment (https://www.ebi.ac.uk/QuickGO/term/GO:1990948):

Comments
this term is only for gene products which bind to and directly inhibit the APC-Cdc20 complex (i.e the MCC complex).

So I used the upper level term for these annotations.

GO:0055105	ubiquitin-protein transferase inhibitor activity 

although I would have liked to use the more granular term.

Question is should we:

1) Modify the curator comment to state that GO:1990948 can be used to annotate all forms of the APC/C which in yeast are: APC/C-Cdc20, APC/C-Cdh1 and the meiotic form APC/C-Ama1

2) Modify the definition to be more inclusive so this term could be used for all forms of the APC/C or possibly so it could be used to annotate any ubiquitin ligase inhibitor, as to my knowledge there no terms other than the parent that could be used for other E2 inhibitors?

3) Create more instances for the other APC/C variants, like APC/C-Cdh1. I personally do not favor this solution, as it creates very specific terms. 

Cheers,
Rob

_Copied from original issue: geneontology/go-annotation#2008_

**Comment by ValWood** [comment]
I think it would be OK to remove this comment. It does not match the fact that 

APC-cdc20 is a narrow synonym.

I think we changed this at some point and did not remove the comment maybe?

**Comment by ValWood** [comment]
I already used it with different substrates to cdc20/slp1 here:
https://www.pombase.org/gene/SPAC5D6.08c

**Comment by robnash** [comment]
@ukemi @ValWood 
Thanks, will update my annotations!
