### ISSUE TITLE
GO:0072588 box H/ACA RNP complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15918]
this term is merging multiple complexes together.....

A ribonucleoprotein complex that contains an RNA of the box H/ACA type and the four core proteins dyskerin, NOP10, NHP2, and GAR1 (human protein nomenclature). RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity. These include the vertebrate telomerase RNP complex. PMID:17284456 PMID:20227365

note that the 4 core proteins are members of  *multiple complexes* 

including  telomerase
AND
box H/ACA snoRNP pseudouridylase complex
(when box H/ACA snoRNP is a  pseudouridylase is contains a pseudouridylase component)

This term was added by @mah11  in 2011, so I'm not sure why it says it was created by BHF
box H/ACA RNP complex GO:0072588

It was originally created   for this:

A ribonucleoprotein complex that contains an RNA of the box H/ACA type, a subtype of the small nucleolar RNA (snoRNA) family. RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs, although some have evolved other functions. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and on U2 small nuclear RNA (U2 snRNA).

but at some point the definition and meaning were radically changed.

~Now  we have no term for
Added | SYNONYM | box H/ACA snoRNP pseudouridylase complex~

There is a child term for this but it isn't obvious, see suggestion below

**Comment by ValWood** [comment]
This overlaps with what @bmeldal  was pointing out here:

https://github.com/geneontology/go-ontology/issues/15918

b) Most other box H/ACA RNP complexes have specific pseudouridine synthesis activity. That would suggest box H/ACA telomerase RNP complex shouldn't be a child of box H/ACA RNP complex as it's not functionally the same (or more specific) - it lost its canonical function.

The simplest solution to deal with the non-telomerase part of this is:


1. obsolete the old, originally correct term that morphed into a grouping term
GO:0072588 box H/ACA RNP complex
(it is grouping functionally heterogeneous complexes)

2, Rename 
GO:0072589    box H/ACA scaRNP complex
to
nucleoplasmic box H/ACA RNP pseudouridylase complex
so it is clearer what it is (currently exact synonym)

3. 
The GO:0072589 def needs fixing:
A box H/ACA RNP complex that is located in the Cajal body of the nucleoplasm. In higher eukaryotes, box H/ACA RNP located in Cajal bodies mediate pseudouridylation of spliceosomal snRNAs. PMID:17284456 PMID:20227365

Yeast don't have structures identified as Cajal bodies (AFAIK)? anyone?

suggest:

A ribonucleoprotein complex that contains an RNA of the box H/ACA type, a subtype of the small nucleolar RNA (snoRNA) family, and a pseudouridylase.  Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and on U2 small nuclear RNA (U2 snRNA).

4. Remove Cajal body parent

**Comment by ValWood** [comment]
@RLovering 
@bmeldal

**Comment by bmeldal** [comment]
I think @krchristie is looking into box H/ACA complexes, too. She used them as examples for the complex presentation at NYC mtg.

Pool resources/expertise?

**Comment by krchristie** [comment]
There is an existing ticket on the box H/ACA snoRNP complexes. Basically, I think the final structure should be mostly already as someone has already done for the box C/D snoRNP complexes, with some exceptions that I've already outlined here: https://github.com/geneontology/go-ontology/issues/11686

Please read that previous ticket.

I think that this new ticket is largely a duplicate, so I'm inclined close it and ask you to add anything not already mentioned in the existing ticket there.

**Comment by RLovering** [comment]
Is this still under discussion or has this been sorted out now?

**Comment by ValWood** [comment]
closing, since is presumably a duplicate of
https://github.com/geneontology/go-ontology/issues/11686
