### ISSUE TITLE
add synonym to CENP-A containing nucleosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15913]
CENP-S–T–W–X

Cnp1, together with the non- canonical nucleosome complex CENP-S–T–W–X (SpMhf1, SpCnp20, SpNew1, and SpMhf2), defines the landmark of centromeric chromatin structure (Stoler et al., 1995; Takahashi et al., 2000, 2005).

**Comment by ValWood** [comment]
original paper
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3277711/

**Comment by krchristie** [comment]
I assumed this should be an EXACT synonym. If that's not true, please let me know what it should be.

**Comment by ValWood** [comment]
yes exact, thanks
