### ISSUE TITLE
new term request: acyl-CoA delta5-desaturase activity 

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#15910]
Dear GO annotators,

I need your help to create a new term to describe the activity of  O60427_FADS1_HUMAN (EC 1.14.19.44) :

GO: acyl-CoA delta5-desaturase activity 
as a child of 
GO:0016215 acyl-CoA desaturase activity

For reference please check: PMID:10601301; PMID:10769175

Many thanks,

Nevila Hyka-Nouspikel

**Comment by ukemi** [comment]
This EC corresponds to 2 different Rhea reactions: RHEA:46420 and RHEA:46424. The EC name is 'Acyl-CoA (8-3)-desaturase' and the definition includes both reactions. If we make a single term, we will need to figure out how to define this activity taking both of those (and possible others covered by the EC description) into account. It will probably be something similar to the first comment in the EC entry. Alternatively, we could make more than one function that corresponds to each Rhea reaction. Would we want a grouping term, it seems like we would?

Reactome has FADS1 annotated to GO:0045485 in R-HSA-2046092.1. @deustp01 

This is another nice example of a challenge for our summer project. @goodb @vanaukenk

**Comment by deustp01** [comment]
Both reactions describe the creation of a 5Z double bond in a molecule that already has 8Z,11Z,14Z double binds and optionally a 17Z double bond.

The Reactome reaction corresponds to RHEA:46424 (not exactly matched because of a charge state discrepancy).
