### ISSUE TITLE
cell adhesion receptor signaling pathway via beta-catenin

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15914]
New ticket from #1966

Comment from Helen

Yes, looks like the LPP3-PTEN is a separate pathway, even more divergent than Norrin.

@vanaukenk - I wonder that if we have many more examples like this, that it would justify a parent kinda-like "receptor-mediated signaling pathway via beta catenin"(....but better)

![41523473-ff45e966-72d1-11e8-8a89-35d0feafc745](https://user-images.githubusercontent.com/12080010/41525803-20aae216-72da-11e8-98a1-49b8ca8516bd.png)

**Comment by RLovering** [comment]
Hi Helen

I was just thinking of suggesting something like 'receptor signaling pathway via beta-catenin' too. 

Also this would follow what we have decided to do with JAK-STAT: receptor signaling pathway via JAK-STAT

Maybe in this example there should be a child:
cell adhesion receptor signaling pathway via beta-catenin. 

There is a bit of a lack of terms for signalling through adhesion molecules. We have GO:0007229 integrin-mediated signaling pathway maybe there should also be cadherin-mediated signaling pathway. The problem again is all cadherin signaling via beta-catenin? 

There are a lot of articles with a search for cadherin and catenin, Note: https://www.ncbi.nlm.nih.gov/pubmed/?term=29103954 
![screen shot 2018-06-18 at 09 23 20](https://user-images.githubusercontent.com/12080010/41525600-7113feb4-72d9-11e8-8719-e1dce2557659.png)

**Comment by RLovering** [comment]
Also see https://www.ncbi.nlm.nih.gov/pubmed/?term=27096107 Figure 3
![screen shot 2018-06-18 at 09 36 53](https://user-images.githubusercontent.com/12080010/41526184-563f8a02-72db-11e8-9400-d0cebe843e86.png)

This suggests a E-cadherin-α6β1 integrin signal pathway. I guess this would get captured under the transactivation term, rather than having another signaling pathway?

Ruth

**Comment by vanaukenk** [comment]
@hattrill @RLovering 
Specifically for the LPP3-PTEN paper, I'm not convinced that there is a separate beta-catenin signaling pathway here as opposed to a description of another mechanism for regulating canonical Wnt signaling.
This paper was the only one I could find that talked about LPP3 and PTEN:
https://www.ncbi.nlm.nih.gov/pubmed/20123964
Are there others that would help us define this signaling pathway better for GO?

**Comment by RLovering** [comment]
Hi Kimberly

In 2009 review there does seem to be a few papers showing that LPP3 is an unusual LPP as it is able to bind integrins https://www.ncbi.nlm.nih.gov/pubmed/?term=19066402 (see section NONCATALYTIC ACTIONS OF THE LPPS ON THE CELL SURFACE). Not sure how relevant this is to the discussion. There are 4 papers that mention the LPP3 and catenin.

There is no actual evidence that a wnt receptor is involved, so what should I do? Shall I just use a (NEW TERM) cell adhesion molecule signaling pathway term and annotate the catenins to this?

Thanks for helping with this

Ruth

**Comment by RLovering** [comment]
ok I agree no term required 
Thanks
Ruth
