### ISSUE TITLE
NTRs - chaperone-mediated lipoprotein transport 

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-ontology#15917]
NTRs
I. Name: chaperone-mediated lipoprotein transport 
Def: the directed movement of lipoproteins within a cell mediated by chaperone molecules that bind to the transported lipoprotein. 
is a  GO:0042953 lipoprotein transport

II. Name: chaperone-mediated lipoprotein transport across the periplasmic space
Def: the directed movement of lipoproteins from the plasma membrane across the periplasmic space to the outer membrane, mediated by chaperone molecules that bind to the transported lipoprotein. 
is a GO:0044874 lipoprotein localization to outer membrane

Ref: PMID 7628437 [https://www.ncbi.nlm.nih.gov/pubmed/7628437]

Thanks
Amanda

**Comment by pgaudet** [comment]
Hi @amandamackie 

Apologies about the long delay for responding to your query. 

It looks like the term you are describing should be a molecular function, for example 'lipoprotein carrier activity'. I think the BP 'GO:0042953 lipoprotein transport' correctly describe the biological role of the gene described in PMID:7628437 ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
Agreed and thanks for the response. 

By way of explanation, I requested this term after noting a specific BP term (GO:0072323) for 'chaperone mediated **protein** transport across the periplasmic space' and thought that it would be appropriate to have a counterpart term for lipoproteins. The gene product in question, LolA, is part of a well characterized lipoprotein transport system in gram negative bacteria.

Amanda

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140597
+name: protein carrier activity
+namespace: molecular_function
+def: "Binding to and carrying a protein between two different cellular locations by moving along with the target protein." [PMID:7628437]
+intersection_of: GO:0140104 ! molecular carrier activity
+intersection_of: transports_or_maintains_localization_of PR:000000001 ! protein
+relationship: has_part GO:0005515 ! protein binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/15917 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-10T06:16:16Z
+
+[Term]
+id: GO:0140598
+name: lipoprotein carrier activity
+namespace: molecular_function
+def: "Binding to and carrying a lipoprotein between two different cellular locations by moving along with the target lipoprotein." [PMID:7628437]
+intersection_of: GO:0140104 ! molecular carrier activity
+intersection_of: transports_or_maintains_localization_of CHEBI:6495 ! lipoprotein
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/15917 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-10T06:16:26Z

**Comment by pgaudet** [comment]
I will merge GO:0072323 chaperone-mediated protein transport across periplasmic space 
into   its parent  GO:0072322 protein transport across periplasmic space. 

Thanks, Pascale

**Comment by pgaudet** [comment]
protein carrier activity

added synonyms: 

+synonym: "protein carrier chaperone" EXACT []
+synonym: "protein chaperone" BROAD []

**Comment by ValWood** [comment]
this is a related ticket that includes 'chaperone'
https://github.com/geneontology/go-ontology/issues/17117
maybe merge here too instead of obsolete?

**Comment by pgaudet** [comment]
I would prefer not to merge, because some reannotation is needed in several cases (see https://docs.google.com/spreadsheets/d/18cumXK6_Iim-kkq5krL-kYsbAUq4mDVi929p0w1INPk/edit#gid=0)
