### ISSUE TITLE
regulates_activity_of: Range vs. usage note 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15912]
Looking at the usage note for regulates_activity_of (and even the subset), it seems like a complex would be valid, but complexes aren't included in the range. 

Specifically, PMID:19129197 shows "Rad54 strongly stimulates the Mus81·Mms4 nuclease activity on a broad range of DNA substrates".  We'd like to annotate to Rad54 with regulates_activity_of(Mus81/Mms4 complex), CPX-1670, but that gives an error.  Could the range and the usage note be brought into agreement? 

id: regulates_activity_of
name: regulates activity of
def: "A relation that holds between the regulation of a molecular function and the agent that executes that function." []
subset: AE_sequence_or_complex
property_value: local_domain "GO:0098772 GO:0065009" xsd:string
property_value: local_range "GO:0043234 SO:0000374 PR:000000001" xsd:string
property_value: usage "Use this relation to link either a molecular function, or a biological process that regulates a molecular function, to the gene product or complex that executes the regulated function." xsd:string
is_a: regulates_o_has_agent ! regulates_o_has_agent

**Comment by vanaukenk** [comment]
Hi @suzialeksander 
Where are you seeing the error and what is the error message?
GO:0043234 is the ID for 'protein complex' so they should be allowed.

**Comment by suzialeksander** [comment]
We have one of those GOA email warnings.  It's also prohibited in Protein2GO.  Sorry, should I ask EBI about this instead? I thought it was a mistake in the gorel.obo file I'm looking at.


We have identified that one or more annotations by your group have a problem in the ANNOTATION_EXTENSION column.
...
You can find details of the valid set of relations that can be used in an annotation extension, including their DOMAIN and RANGE constraints, at https://www.ebi.ac.uk/Tools/QGValidate/AnnotationExtensionRelations.html
...
Invalid range for regulates_activity_of: ComplexPortal:CPX-1670

**Comment by vanaukenk** [comment]
Okay, I think the issue here is actually that GO:0043234 is now at Alt_id for GO:0032991, so the
local range for 'regulates activity of' should be updated to reflect that.

@tonysawfordebi - do you get the information about domain and range constraints for annotation extension relations from gorel.obo?

**Comment by vanaukenk** [comment]
Note: GO:0043234 is used in range for 'regulates o has agent' and 'regulates activity of'
Will need to be updated in both places.

**Comment by tonysawfordebi** [comment]
@vanaukenk Yes, we get all domain & range information from gorel.obo, which we then munge together with what we find in http://purl.obolibrary.org/obo/go/snapshot/extensions/gorel.obo and db-xrefs.yaml in order to validate extensions.

**Comment by balhoff** [comment]
Thanks @vanaukenk and @tonysawfordebi. Some of this might be useful to include within the Noctua reasoner checks.

**Comment by balhoff** [comment]
Oops, I thought I was replying to https://github.com/geneontology/go-site/issues/613.

**Comment by vanaukenk** [comment]
I've updated the Range for any relations in gorel.obo that refer to GO:0043234, replacing that with GO:0032991.

@tonysawfordebi @suzialeksander - I'll close this ticket, but please re-open if any problems arise.  Thx.
