### ISSUE TITLE
bradykinin catabolic process parentage

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15923]
Hi, 

this relationship looks weird
bradykinin catabolic process is_a drug catabolic process

**Comment by deustp01** [comment]
Didn't something like this come up recently, about a month ago, where some other naturally occurring molecule got tagged with the ChEBI "drug" role and similar weirdness resulted? And wasn't there a conclusion then about how to keep this from happening?

**Comment by Antonialock** [comment]
https://github.com/geneontology/go-ontology/issues/14626

**Comment by ukemi** [comment]
Closing this because it will be fixed in the above ticket.... whenever we get a chance to implement that.
