### ISSUE TITLE
Create ChEBI import with Rhea reaction chemicals

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15926]
In order to get full reasoning based on the Rhea reaction participants, we will need to import the ChEBI identifiers for chemicals that are currently missing from the ChEBI import. A way to do this that is completely in alignment with our current pipeline is to add the ChEBI identifiers to  go-ontology/src/ontology/imports/chebi_terms.txt and then run the makefile.

**Comment by ukemi** [comment]
If anyone is looking at this, its worth noting that the expanded CHEBI import did not include the General class axioms for the new additional CHEBI terms. Hence, e.g.,
diphosphoric acid (CHEBI_29888) is not equated with diphosphate(3-) (CHEBI_33019) in the merged ontology.
@ukemi
Member
ukemi commented 2 hours ago

Isn't that part of the make_file? We can talk about it on Monday, but it makes sense to me to go ahead and run the ChEBI import with the additional terms we will need for the Rhea defs and if it all looks ok go ahead and merge that into master. It won't hurt anything to have the additional ChEBI classes I don't think. It's one more step we can do to get concrete progress along the way.
@goodb
Member
goodb commented an hour ago
Yes, I assume it is part of the make file and ought to work fine when built
that way.  I haven't got set up to do the complete build locally (todo
list..) and thus merged the Robot-generated chebi extract manually into
Protege - thus missing the generation of those axioms.  It probably won't
make a lot of difference to our discussion, just may end up missing a few
more inferences.

**Comment by ukemi** [comment]
The way we usually add terms to the imports is by adding them here:
https://github.com/geneontology/go-ontology/blob/master/src/ontology/imports/chebi_terms.txt
and then having someone run the makefile in ROBOT. I'm not sure if there is an easier way, but if we simply add all the uris necessary for the Rhea logical defs to this file, it should work. Chris (or you or @balhoff might know an easier way).

**Comment by cmungall** [comment]
That should work

**Comment by goodb** [comment]
(edit) Moving this comment over from other thread.  

Added missing RHEA terms to GOPlus import file see branch #issue-14984-chebi-import . See https://github.com/geneontology/go-ontology/blob/issue-14984-chebi-import/src/ontology/imports/chebi_terms.txt

**Comment by ukemi** [comment]
It looks like there are about 8000 new terms in @goodb 's branch of chebi_terms.txt. @cmungall, any idea if that will be too big? If not, can we create a pull request for those additions and @dougli1sqrd , @vanaukenk and I can work on making the new ChEBI import file? If we do it successfully on a local branch, we can fire up Protege with the new ChEBI imports to make sure we don't bog things down. Sound like a plan?

**Comment by goodb** [comment]
I have a question on protocol here.  It seems a little weird that we have
two ways of getting CHEBI terms into the ontology - via this file and the
makefile and via just putting them into the main ontology file.  As a
general rule, it seems like it would be better to pick one way or the other
to improve understanding and ease maintenance over the years??

**Comment by ukemi** [comment]
The txt file is just a request for a term that we want imported into the ChEBI file that we use. All of the terms from external ontologies live in separate input files that are loaded into Protege and they only contain a subset of terms that we cross-reference in GO. We use the structure of the 'mini' external ontology for reasoning, but we assert the relationships between GO terms and the terms from the external ontologies while we are editing. We can only use them if they are already in the import file. This allows us to use a consistent version of an external ontology and we don't have to worry about the external ontology changing in a way that would break something.  Ontology editors would love it if we could use any term from any of the external ontologies when we need them. TermGenie used to allow that, but our current workflow doesn't. When we need to use an external term that isn't in an import yet, we need to run the makefile to import the missing term. @cmungall, @dougli1sqrd or @balhoff can comment more thoroughly on why we need to run the extra step of creating the import files manually, but it does allow us to run checks on the file before we officially start to use them. I suspect with your large change in the txt file, the diff we get after running the makefile will be very large and we will simply trust it if it passes all the automated checks.

**Comment by cmungall** [comment]
what is the size of  the owl?

currently

$ du -sh imports/chebi_import.owl
8.2M    imports/chebi_import.owl

**Comment by goodb** [comment]
Thanks for the comment @amorgat .  Definitely relevant and has already come up on this other thread: https://github.com/geneontology/go-ontology/issues/15930#issuecomment-399322630 .  We need to make a decision about what level to model the reaction participants for these logical definitions.  If we stick to only using CHEBI terms, are the definitions (as for example in that thread) that involve generics and polymers logically incorrect or just less specific than they could be? e.g., is that equivalency inference incorrect - as I think I read @hdrabkin 's comment to say?  If it is incorrect, than we can either eliminate equations that involve generics and polymers from the import or we will need to expand the substance definitions beyond those represented in CHEBI.  Thoughts?

**Comment by ukemi** [comment]
Progress on this thread specifically with respect to ChEBI imports. I used @goodb's branch to run the import makefile in docker. The new import file in my branch is 33M. I have not pushed it to origin. @cmungall commented that this is a bit large. However, I have sent the file to Ben and on Monday, @hdrabkin, @deustp01 and I will use my local branch to sanity check that it seemed to have built properly. From there we need to come up with a solution about how to handle a file that is this large.

**Comment by ukemi** [comment]
Spot checking the new chebi import in my local branch:

ADP metabolic process is classified by the reasoner as a purine ribonucleoside monophosphate metabolic process. This seems like an incorrect classification by ChEBI. This is also in the live ontology.

Same type of issue with CDP. It is listed as a ribonucleoside. This is also in the live ontology (GO:0046704).

Otherwise, the live ontology mimics the new import. 

@goodb   When checking for new chemicals in the .txt file on your request branch, we find chemical such as pyranoside (CHEBI:75504) and Ala-Gly zwitterion (CHEBI:73786)  that don't seem to be used in any of the Rhea reactions that are in newMFsfromRhea.ttl.  When we look up the RHEA reactions that use these chemicals in GO we do not find those RHEA identifiers as xrefs. It is possible that the requested chemicals are more than we need?

In some cases things look ok, CHEBI_58127 is in the new file and crossreferences GO:0047917 (RHEA_15052) and GO:0047344 (RHEA_10711).

**Comment by goodb** [comment]
@ukemi the new CHEBI term request covers all of the CHEBIs used anywhere in RHEA.  We could reduce that for the moment, but the thought (from @cmungall originally I believe) was to just bring them all in at once rather then doing so piecemeal.  

The newMFsfromRhea ontology (and its several more advanced descendants) only contains terms with existing manually specified xrefs from GO to RHEA.  This set can be grown as we've discussed, for example, by using EC numbers shared by GO terms and RHEA reactions to find additional matches.  

My take here is to go ahead with the full import.  Its not such an outlandish size that the software team can not find a solution for dealing with it in github and it will smooth development over the coming months by reducing the need for new imports to be processed.  But, if the consensus disagrees, let me know and I can make a term set that only contains chebis from currently xref'd reactions.

**Comment by hdrabkin** [comment]
I created a chebi ticket 
https://github.com/ebi-chebi/ChEBI/issues/3479
which is is copied inin https://github.com/geneontology/go-ontology/issues/16036

**Comment by goodb** [comment]
@cmungall it looks like this issue got summer-stuck.  If I recall correctly, the concern was the size of the import but that we tested in github and it seemed to be fine.  What do you think?  Would like to clear the issue one way or another.  (By doing the full import as proposed or cutting it down to the currently active subset that affects the proposed logical defs).

**Comment by ukemi** [comment]
Since the above ticket ebi-chebi/ChEBI#3479 would resolve a large number of logical issues, it would be nice if this fix were part of the new import build.

**Comment by goodb** [comment]
@ukemi I assume that is still on chebi's plate right?  (I guess specifically on @G-Owen 's plate based on the issue assignment.)

**Comment by goodb** [comment]
@ukemi chebi has closed that ticket.  Is it time to go ahead and merge the expanded set of chebi into Master so we have what we need to finish work leading up to Geneva ?

**Comment by ukemi** [comment]
I think so as long as the file size isn't an issue. I'd like to get confirmation of that from @cmungall or @balhoff. The we should add the required chemicals to https://github.com/geneontology/go-ontology/blob/master/src/ontology/imports/chebi_terms.txt. I would like @hdrabkin to build the import so he has experience. If we can update the txt file by Monday's meeting, we can have him run the build using docker on the call. I suspect the diff is going to be too big to do anything useful with. See one, do one, teach one.

**Comment by goodb** [comment]
The file was updated a while ago just made an official PR for that update https://github.com/geneontology/go-ontology/pull/16601

**Comment by ukemi** [comment]
I believe this was completed this week.
