### ISSUE TITLE
NTR: regulation terms for GO:0005319 lipid transporter activity

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15925]
Could I please have all the regulation terms for GO:0005319 lipid transporter activity

For PMID:27365390

Please add references:
GOC:rph
GOC:BHF
GOC:BHF_miRNA

**Comment by rachhuntley** [comment]
I'm not sure it would. It's for annotating a miRNA that the authors show reduces MTP (lipid transport) activity. The miRNA is also shown to reduce the mRNA expression of the lipid transporter MTP, but it was not shown to directly bind the MTP transcript, so we can't say that it silences the gene.

As we don't know if it's direct, I'd prefer to use a regulation term. Even if it was shown to directly silence MTP, I'm not sure I would want to annotate the miRNA with an activity term like this.

**Comment by pgaudet** [comment]
In this case why not use 'regulation of lipid transport'?

**Comment by rachhuntley** [comment]
The authors do show an effect on lipid secretion in a separate experiment, so I can annotate to reg. of lipid transport as well, but the figure I want to annotate is showing that the miRNA reduces MTP activity, so this seems a more specific annotation. The miRNA is acting on the transporter rather than anything else that might be involved in the transport.

**Comment by rachhuntley** [comment]
I'm not sure I understand you. Here is the paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4479415/

Extract:
"miR-34a also reduced MTP and ApoB protein levels (Fig. 3b, c and Supplementary Fig. 6a) and MTP activity (Supplementary Fig. 6b). In contrast, loss of miR-34a increased MTP activity (Supplementary Fig. 6c). Consistent with the latter data, miR-34a inhibited VLDL secretion (Fig. 3d)."

Proposed annotations:
From Fig 3b, c and Supp Fig. 6a we can annotate miR-34a to neg. reg. of gene expression of MTP and ApoB

From Supp. Fig. 6b/c we want to annotate miR-34a to neg. reg. of lipid transporter activity (has_regulation_target MTP)

From Fig. 3d we can annotate miR-34a to neg. reg. of lipid transport (but instead I've opted for cholesterol homeostasis, as I wasn't sure that the secretion was transport).

So although they have shown reduced MTP activity with miR-34a and reduced VLDL secretion, they haven't shown that the latter is caused by the former, they are two independent experiments.

**Comment by vanaukenk** [comment]
@rachhuntley 

To be consistent with previous annotation, I will add the requested regulation terms.

It would be good to discuss this example wrt a GO-CAM model and use of the expanded set of gene product-to-term relations as it's a common theme, i.e. an upstream molecule regulating expression of a downstream molecule with activity 'x', and going forward we want to make sure we're all annotating these types of experiments similarly.

**Comment by rachhuntley** [comment]
Thanks Kimberly @vanaukenk, I agree it would be good to get a consensus on this.
