### ISSUE TITLE
Ancestry of GO:0016469 proton-transporting two-sector ATPase complex

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#15936]
Ancestry of GO:0016469 proton-transporting two-sector ATPase complex

Is there any particular reason that GO:0016469 proton-transporting two-sector ATPase complex is not a child of GO:1904949 ATPase complex? I looked through some old SF-era tickets and saw something about the ATP branch being a mess, but I'm not sure if it was ever addressed.

Thanks

**Comment by ValWood** [comment]
I will take this and add the parent next week
