### ISSUE TITLE
NTR fluoride ion channel activity

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-ontology#15938]
NTR; fluoride ion channel activity
Def: enables the energy independent diffusion of fluoride ions across a lipid bilayer
Is a: GO:0005253 anion channel activity
Is a: GO:0015103 fluoride transmembrane transporter activity

Refs: PMID 25156118 [https://www.ncbi.nlm.nih.gov/pubmed/25156118] and
PMID     23991286 [https://www.ncbi.nlm.nih.gov/pubmed/23991286]

**Comment by ukemi** [comment]
Added in #15946
