### ISSUE TITLE
NTR: Regulation terms for GO:0035897 proteolysis in other organism

### ISSUE THREAD

**Issue by Kawatebi** [geneontology/go-ontology#15934]
Could I please have a regulation terms for  GO:0035897 'proteolysis in other organism'

Publication: DOI:10.1016/j.procbio.2017.03.015  Fig.7-8

Many thanks

**Comment by Kawatebi** [comment]
Any update on this?

I forgot to add a definition for negative regulation, so here it is: 

"Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of protein hydrolysis in a second organism."

Many thanks.

**Comment by pgaudet** [comment]
Is this inhibition also occurring in vivo? While it seems to have important clinical implications, this looks like a non-physiological setup, which would make it outside the scope of GO. 

Thanks, Pascale

**Comment by Kawatebi** [comment]
That's true. It likely acts as a insecticide but as mosquito isn't a herbivore it is a non-physiological set-up. So please ignore my request.

Thanks for taking a look for me, Kate
