### ISSUE TITLE
minor adjustments to GO:0070867

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#15932]
From existing links, it looks like GO:0070867 ! mating projection tip membrane should be is_a GO:0031520 ! plasma membrane of cell tip.

Also, may we have some synonyms?
synonym: "shmoo tip membrane" NARROW []
synonym: "mating projection membrane fusion domain" EXACT [PMID:29134248]

thanks,
m

**Comment by mah11** [comment]
Those equivalence axioms look fine. Thanks!

**Comment by krchristie** [comment]
Awesome, thanks for checking @mah11 :)
