### ISSUE TITLE
general transcription factors / term query: RNA polymerase III assembly factor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15941]
Q
Do we still need
RNA polymerase III assembly factor activity?
(how doe this differ from GO:0000995? merge?)

![needed](https://user-images.githubusercontent.com/7359272/41833017-8b7a7cb6-7846-11e8-9189-877ec0ba7b32.jpg)

Should all transcription initiation factors be defined as  "recruitment factors" involved in asembly of the initiation complex?

**Comment by ValWood** [comment]
RNA polymerase III assembly factor activity has
11 annotations EXP annotations, all SGD, all TFIIIC

**Comment by pgaudet** [comment]
Hi @krchristie 
What do you think of this suggestion ?

**Comment by krchristie** [comment]
I don't mind merging the terms and I think that the "RNA polymerase III general transcription initiation factor activity" name seems the better of the two.

> Should all transcription initiation factors be defined as "recruitment factors" involved in asembly of the initiation complex?

However, this suggestion for a definition seems too narrow as it ignores the roles in start site selection included in the definition of "RNA polymerase III general transcription initiation factor activity".

**Comment by ValWood** [comment]
This was a question  I wanted to raise on the next call.

The new "general initiation factors"  are useful as grouping terms, for users and annotators. However because they don't really describe the molecular functions, I 
would prefer that we still have descendants to these terms representing the actual functions.

But in this case how separable are "recruitment" and "start site selection"?
Isn't start site selection "recruitment to a specific location"

**Comment by krchristie** [comment]
My impression is that recruitment and start site selection are considered separate fiunctions. Recruitment is the series of binding interactions that bring the RNAP to a promoter. Start site selection is a very narrowly targeted function that determines exactly where the RNAP starts making the transcript.

**Comment by ValWood** [comment]
OK, we should pin this down precisely. It sounds like you are saying that recruitment does not determine start site. Is that correct?

**Comment by krchristie** [comment]
My impression is that recruitment affects start site generally in determining where the RNAP is bound. However, my impression is that there is a more specific process going on within the PIC to determine specific start site.

**Comment by ValWood** [comment]
Thanks, @krchristie  are there any good papers or reviews about this difference?
v

**Comment by pgaudet** [comment]
Hi @ValWood 
TFIIIC (to take that example) has as a function 'RNA polymerase III regulatory region DNA binding' (or more likely 'polymerase III regulatory region sequence-specific DNA binding'), according to https://en.wikipedia.org/wiki/RNA_polymerase_III

So, would you like to have a term to describe that function, like "regulatory region DNA binding RNA polymerase III general transcription initiation factor activity" - is this what you mean ? 

Pascale

**Comment by ValWood** [comment]
Yes I guess so.... It seems a bit clunky but it's the only way I can think of to avoid  inconsistencies  caused by annotating the same activity in multiple branches.

Can you see what Paul thinks about this?

**Comment by krchristie** [comment]
@ValWood - Sorry, I haven't read on this recently, so you might as well do your own PubMed search and pick the things that look useful to you.

**Comment by ValWood** [comment]
@pgaudet  can we ask the transcription group about this? I wouldn't really know what to search on to find out about this distinction.

**Comment by pgaudet** [comment]
Certainly !

**Comment by pgaudet** [comment]
Looking at the history, this term is already the results of other merges: 
#14852 
#15531 
and *used* to be called 'recruiting'. The existing annotations (11 EXP and 1 InterPro family) are consistent with this. So I will change the main label to 'RNA polymerase III transcription factor recruiting activity' and move it as a sibling of the polI and II counterparts: 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/4782928/42265096-d446bb8e-7f72-11e8-8525-ef576729d706.png">

OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Sounds good
