### ISSUE TITLE
Missing parent (MP) catecholamine biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15942]
Isn't this  a biogenic amine?

![catecholamine is a biogenic amine](https://user-images.githubusercontent.com/7359272/41833656-23303d3c-7849-11e8-9046-9ebf21736b6f.jpg)

**Comment by pgaudet** [comment]
@hdrabkin Isn't this coming from CheBI ? Should we create a ticket there ?

**Comment by ValWood** [comment]
I can do that, I should create them there but I like to check first, pretty sure catecholamine is a biogenic amine....

@Antonialock  keep an eye on this one, we can refine our generic slim , I think once in place

**Comment by ValWood** [comment]
we will close when we updated our in progress slim

**Comment by hdrabkin** [comment]
I wonder if "biogenic' amine is actually role (biologically active).
I don't see a biogenic amine in Chebi

**Comment by ValWood** [comment]
Ah OK  how does "biogenic amine" logically define in GO?

Feel free to take it back if more complicated!

**Comment by ukemi** [comment]
It's not in ChEBI. If we are going to create this, it will need to be manually asserted. But there is some weirdness with monoamines I think.

**Comment by hdrabkin** [comment]
We use the phrase in some terms: like
Term: | cellular biogenic amine metabolic process 
 Syn:  biogenic amine metabolism
The chemical reactions and pathways  occurring at the level of individual cells involving any of a roup of  naturally occurring, **biologically active** amines, such as norepinephrine,  histamine, and erotonin, many of which act as neurotransmitter

**Comment by ValWood** [comment]
I was basing my assumptions on catacholamine on
https://en.wikipedia.org/wiki/Catecholamine

and since
Included among catecholamines are epinephrine (adrenaline), norepinephrine (noradrenaline), and dopamine. 

?

**Comment by cmungall** [comment]
> It's not in ChEBI. If we are going to create this, it will need to be manually asserted

Should be a last resort - I don't see a link to a CHEBI ticket here?

**Comment by ValWood** [comment]
It's there.....in that I linked the CHEBI ticket to this ticket.
but more explictly:
https://github.com/ebi-chebi/ChEBI/issues/3490

**Comment by ValWood** [comment]
If CHebo do not want to add consider obsoleting "biogenic amine" and linking

'celecholamine' to "cellular amine'

**Comment by ukemi** [comment]
Biogenic amine is not really clearly identifiable by ChEBI. However, our logical definition of amine metabolic process, which includes chebi 'amine' actually seems too narrow based on the chemical definition . Perhaps we need to modify our term to be organic amino compound.

**Comment by ValWood** [comment]
I think @ukemi is referring to "cellular biogeneic amine" (is this correct? @ukemi ?)

**Comment by ValWood** [comment]
Unassigning myself as  I have no task.

**Comment by ValWood** [comment]
Chebi have punted this issue back to GO.
Can the parentage be manually asserted?
