### ISSUE TITLE
TPV histamine secretion by mast cell &  mast cell degranulation	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15943]
GO:0002553    histamine secretion by mast cell

and
	mast cell degranulation	

are children of

GO:0032418   lysosome localization

**Comment by ValWood** [comment]
Here I thought the p[arent looed incorrect, so the fix should  e easy, or the ticket can be closed if correct.

I just couldn't see how  it fit with lysosomes localization

**Comment by pgaudet** [comment]
'lysosome localization' is inferred from the logical definition: 

'regulated exocytosis'
 and ('occurs in' some 'mast cell granule')
 and ('transports or maintains localization of' some 'mast cell granule')

+ the fact that 'mast cell granule is_a lysozyme

I think the 'occurs in' some 'mast cell granule' is odd, I will remove it. 

Thanks, Pascale
