### ISSUE TITLE
focal adhesion cellular component and process graphs do not align

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15954]
Hi

I am concerned that these two graphs do not align. 
Either focal adhesion CC terms should include a cell-cell junction parent term.
Or the biological process GO:0048041 focal adhesion assembly should not have the parent term GO:0045216    cell-cell junction organization

see screen shots

Thanks

Ruth
<img width="193" alt="screen shot 2018-06-26 at 14 55 16" src="https://user-images.githubusercontent.com/12080010/41910180-99e2db34-7951-11e8-9bf3-65d5c4ec35b3.png">
<img width="291" alt="screen shot 2018-06-26 at 14 55 07" src="https://user-images.githubusercontent.com/12080010/41910181-9a20b8be-7951-11e8-82a5-d8d0e6344b7d.png">

**Comment by ukemi** [comment]
Looks like the problem is with the parent of adherens junction assembly.
