### ISSUE TITLE
new child  GO:1990735    gamma-tubulin complex localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15955]
NTR:  gamma-tubulin complex localization to nuclear side of  mitotic spindle pole body

Definition (GO:1990735 GONUTS page)
Any process in which a gamma-tubulin complex is transported to, or maintained in, a specific location at the nuclear side of the mitotic spindle pole body. PMID:19942852

child of
GO:1990735    gamma-tubulin complex localization to mitotic spindle pole body

**Comment by ValWood** [comment]
ticket revised

**Comment by ValWood** [comment]
and for 
NTR: gamma-tubulin complex localization to cytoplasmic side of mitotic spindle pole body

mto1 plays a critical role here.
There are more papers but we can use this one
https://www.pombase.org/reference/PMID:19001497

If you don't want to do this specificity, we can put complex IDs in the extensions if we have 
got rid of the specific "gamma tubulin comple localization" term

and instead had
complex localization to nuclear side of mitotic spindle pole body
complex localization to cytoplasm side of mitotic spindle pole body

it's the processes going on at the diffent sides of the SPB which are important for modularization

**Comment by vanaukenk** [comment]
@ValWood 
I can add these two new terms.  Same reference for both?

**Comment by ValWood** [comment]
Different refs, there is a PMID for each term above.
v

**Comment by ValWood** [comment]
this is done so closing
