### ISSUE TITLE
missing parent for kinase inhibitor activity #15951

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15952]
Following on from missing parent for kinase regulator activity #15951

The kinase inhibitor graph has errors that need sorting out. hopefully you can see the graph attached.
<img width="906" alt="screen shot 2018-06-26 at 13 24 41" src="https://user-images.githubusercontent.com/12080010/41905616-63414f82-7944-11e8-8e3d-c9964a88905e.png">

1. tyrosine kinase activity should NOT be a parent of any kind to  GO:0004860 protein kinase inhibitor activity- please remove urgently 

2. to 'replicate' the ontology graph that GO:0004860 protein kinase inhibitor activity has, GO: 0019210 kinase inhibitor activity should have the part_of parent GO:0033673 negative regulation of kinase activity (see graph)

3. Note that the equivalent term to 'GO:0032147 activation of protein kinase activity' does not exist for the kinase and protein kinase inhibitor terms - but I am not sure there is sufficient difference between positive regulation and activation to warrant this term

Thanks

Ruth

**Comment by ukemi** [comment]
Hi @RLovering ,

The red arrow means negative regulation. I think that is fine. I will create the appropriate function->process part of relationships.

-David

**Comment by RLovering** [comment]
but the red arrow means that GO:0004860 protein kinase inhibitor activity (which could be associated with a serine protein kinase inhibitor)  as negatively regulating protein tyrosine kinase activity.

**Comment by ukemi** [comment]
Oops, you are right. My mistake.
