### ISSUE TITLE
missing parent for kinase regulator activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15951]
Hi 
There are inconsistencies between the parents for kinase regulator terms and protein kinase regulator terms. I have listed the edits required for the kinase terms which would align these 2 ontologies.

please could this relationship be added: 

GO:0019207 kinase regulator activity
should have the part_of parent term
GO:0043549    regulation of kinase activity

AS GO:0019887 protein kinase regulator activity
has the part_of parent
GO:0045859 regulation of protein kinase activity

Plus
GO:0019209   kinase activator activity
Should have the part_of parent
NEW GO Term: activation of kinase activity
with the is_a parent GO:0033674 positive regulation of kinase activity
Alternatively just create the part_of parent
GO:0033674 positive regulation of kinase activity

AS GO:0030295   protein kinase activator activity
has the part of parent
GO:0032147   activation of protein kinase activity (although I am not sure that this term is needed?)
which has the is_a parent
GO:0045860   positive regulation of protein kinase activity

I will open a separate ticket for the kinase inhibitor which looks worse

thanks

**Comment by pgaudet** [comment]
Hi @RLovering 
Do we really need the processes here 'NEW GO Term: activation of kinase activity'? I think this is clearly a MF. I think there was a ticket to remove these 'activation of activity' BPs (I cannot find the ticket - @ukemi do you remember that ?) 

Thanks, Pascale

**Comment by RLovering** [comment]
Ok

if the new term is not required then GO:0032147 activation of protein kinase activity should be removed.

But we still need a connection between 
GO:0019209 kinase activator activity
and GO:0033674 positive regulation of kinase activity

Thanks

Ruth
