### ISSUE TITLE
glucose import terms

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15961]
Hi

I wasn't sure if there was a move towards removing some of these more specific terms: 
GO:0046323 glucose import (1614 annotations)
is_a GO:0098708 glucose import across plasma membrane (14 annotations)

There are only regulation terms for the parent term (with 3000 annotations), although often the gps are regulating glucose import across plasma membrane. 

Also I don't like the ontology graph for the GO term (and child terms). I think this first relationship should be remove:
GO:1900076    regulation of cellular response to insulin stimulus
is_a GO:2001273    regulation of glucose import in response to insulin stimulus
definition: Any process that modulates the frequency, rate or extent of glucose import in response to insulin stimulus.
The definition and term imply the regulation of glucose import not the regulation of the response to insulin stimulus. Therefore this parent should be replace with the part_of parent GO:0032869 cellular response to insulin stimulus

These relationships are good:
GO:0044381 glucose import in response to insulin stimulus
regulates GO:2001273 regulation of glucose import in response to insulin stimulus

GO:0046324 regulation of glucose import
is_a GO:2001273 regulation of glucose import in response to insulin stimulus

Sorry there are 2 issues being discussed here, but I think these are quick fixes. 

I guess the only thing is whether these highlight other issues that might exist if other regulation terms have 2 regulation parents which might be incorrect too.

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 
I had started to move 'import' to 'import across plasma membrane (ie into the more specific term; see #15022) - glucose is not finished as it needs quite some annotation reviews. I'll create the Annotation review request. 

----
The other part is interesting: 
- 'regulation of glucose import in response to insulin stimulus' has logical definition 
'biological_process
 and (regulates some 'glucose import in response to insulin stimulus')' 
which creates the following assertions: 
- regulation of glucose import
- regulation of cellular response to insulin stimulus. 

but in this case we'd like the regulation to be only for the glucose, not for the response. Ontology reasoning aside, the annotations to 'regulation of glucose import in response to insulin stimulus' look like signaling molecules; can you have a look and let me know what you think ? 
It seems like 'regulation of glucose import in response to insulin stimulus'  should perhaps be obsoleted and annotations be 'regulation of insulin signaling' or 'cellular response to insulin stimulus. '

What do you think ? 

Thanks, Pascale

**Comment by RLovering** [comment]
So if we get rid of regulation of glucose import in response to insulin stimulus then we would replace this with the annotation:
regulation of glucose import AE field part of cellular response to insulin stimulus

is that what you are proposing?

Ruth

**Comment by pgaudet** [comment]
@RLovering 
We can do what you say, but looking at some annotations, I think most of them can be moved to either 
* GO:0008286  insulin receptor signaling pathway
* GO:0046626 regulation of insulin receptor signaling pathway
* GO:0042593 glucose homeostasis
* GO:0001678 cellular glucose homeostasis 

I think 'regulation of glucose import' without understanding the mechanism is tricky; in many cases we only know that the glucose level changes (=homeostasis), but not that the import is directly impacted. 

This disadvantage of the homoeostasis terms is that we dont know whether the glucose level increases or decreases, but since we know little about the mechanism anyway, we are probably not loosing that much information. 

What do you think ? We can look at some annotations together.

**Comment by pgaudet** [comment]
EXP annotations are here: (there are only 30)
https://docs.google.com/spreadsheets/d/1C7Y1KucIrPzVRm_L44_mQ-6sp0EM6WjHSpoSnJDIn1Q/edit#gid=0

**Comment by RLovering** [comment]
Hi Pascale 
I am on holiday next week, can I look at this when I return. I do need to remind myself of the generally accepted biology before having a proper discussion.

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering ping! Can you please review the annotations when you have a minute ?

**Comment by RLovering** [comment]
Hi Pascale

I have revised 3 of the annotations, all of which were adapter proteins. So these are now annotated to: changed to:
regulation of glucose import 
and regulation of insulin receptor signaling pathway AE Part_of regulation of glucose import

However, PMID:23812417 includes Rachael's annotations (plus a microRNA not on your table)
So I would like Rachael's thoughts on these

Ruth

@rachhuntley

**Comment by rachhuntley** [comment]
I haven't followed all of this thread, but after checking the paper I've updated mine to the same as Ruth's above (with pos. and neg. as appropriate).

**Comment by pgaudet** [comment]
Created annotation ticket: https://github.com/geneontology/go-annotation/issues/2052

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'regulation of glucose import in response to insulin stimulus (and + and - children)’. The reason for obsoletion is that this term represents a GO-CAM model. Most annotations have already been moved; see https://github.com/geneontology/go-annotation/issues/2052
MGI (8 EXP annotations) and AgBase (4 EXP annotations) have not yet responded. 

There are no InterPro2GO mappings to this term; this term is not included in any subset(s)(slims).
New or existing terms that are suggested for transferring annotations (optional).
Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/15961
 
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 24th, 2018. Unless objections are received by September 24th, 2018, we will assume that you agree to this change.

Thanks, Pascale
