### ISSUE TITLE
cell swimming/ cell gliding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15968]
this seems an odd process
https://www.ebi.ac.uk/QuickGO/term/GO:0071975

how is it different from cell motility (it's cell motility in liquid)

**Comment by pgaudet** [comment]
There are only 8 EXP to 'bacterial-type flagellum-dependent swimming motility' 
merge ?

**Comment by ValWood** [comment]
yup, I would merge "cell swimming" to be a "related?"   synonym of "cell motility" and keep everything else as it is.

![swimming](https://user-images.githubusercontent.com/7359272/42074152-984ee6a6-7b62-11e8-913b-2ba77c84e986.jpg)

**Comment by pgaudet** [comment]
Wikipedia defines a number of types of cell motility: 
https://en.wikipedia.org/wiki/Motility

At the cellular level, different modes of motility exist:

* flagellar motility, a swimming-like motion (observed for example in spermatozoa, propelled by the regular beat of their flagellum, or E. coli, which swims by rotating a helical prokaryotic flagellum)
*  amoeboid movement, a crawling-like movement, which also makes swimming possible[14][15]
*  gliding motility
*  swarming motility
*  twitching motility, a form of motility used by bacteria to crawl over surfaces using grappling hook-like filaments called type IV pili.
*  filopodia, enabling movement of the axonal growth cone[16]

According to the paper cited in the 'cell swimming' term, these seem to be distinct mechanisms: 
https://www.nature.com/articles/nrmicro1900

Pascale

**Comment by ValWood** [comment]
this is the 'type' of motility enabled by a particular mechanism

flagellum  (mechanism) enables "swimming motility"

type IV pili (mechanism) enables "twitching motility"

filopodia based movement    enables "swimming motility"  "movement of the axonal growth cone" 

pseudopodia based motility  (amoeboid movement)   enables "crawling" or "swimming"

It's a conflation...

**Comment by ValWood** [comment]
I put that in my comment. 
To me this is a bit like saying that humans and fish can do swimming motility using legs and tails.

I don't think we necessarily nedd the *type* of motitlity in the GO term, but the definitiona should state the type of motility that a particular movement can enable.


You can swim via filiopodia, pseudopodia, flagellum,  but  clearly they can't all have the parent "swimming motility" becasue it isn't always true.

So if you keep obth axis of classification it encourages inconsistent annotation. Inevitably some people will go for the swimming branch and some for the flagellum branch. We don't want two separate branches to  describe the  exact same process.

It's a nice example actually for GO-splaining

**Comment by ValWood** [comment]
...so the part about the type of motility enabled by the mechanism should go in the definition.

**Comment by jimhu-tamu** [comment]
I oppose this merge if I'm understanding what is being proposed (not sure). The processes are different. Gliding is always on a surface. Swimming is in liquid. This would be like merging swimming and walking for humans.

cc: @dsiegele

**Comment by pgaudet** [comment]
Existing terms in these two branches are: 

- GO:0071976 cell gliding / 6 EXP
+ children : 
-- GO:0071980 cell surface adhesin-mediated gliding motility - No annotations
-- GO:0030982 adventurous gliding motility  - No annotations

- GO:0071975 cell swimming - No annotations 
+ children : 
-- GO:0071977	bacterial-type flagellum-dependent swimming motility 7 EXP PseudoCAP
-- GO:0071979 cytoskeleton-mediated cell swimming - No annotations

**Comment by krchristie** [comment]
Like @jimhu-tamu I currently oppose merging gliding and swimming.

**Comment by ValWood** [comment]
This ticket wasn't about merging swimming and gliding. It was about choosing one axis of classification  to describe a  process so that it becomes described identically by different curators. The current arrangement will result in annotations being made inconsistently in different branches. I'm happy for this to close if it isn't considered important. It doesn't affect yeast so I don't  mind. It can just become a QC issue for the future.

if it isn't clear, you have a branch for flagellum mediated movement (which is  a type of swimming?) and a branch with swimming on its own. A curator could arbitrarily choose either.

**Comment by ValWood** [comment]
I'll close it. The branch is hardly used. There are more urgent thingss
