### ISSUE TITLE
rename  GO:0034389   lipid particle organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15963]
GO:0034389   lipid particle organization

to 
lipid droplet organization (currently exact synonym)

for consistency with descendants

**Comment by pgaudet** [comment]
This was discussed with @RLovering ; Ruth is this how you wanted it ? 
(I think droplet isn't much used in the literature - to be confirmed by Ruth). 

Pascale

**Comment by ValWood** [comment]
PubMed
lipid droplet 2774
lipid particle 159

**Comment by ukemi** [comment]
I think they are different.

**Comment by ValWood** [comment]
more work then


![really](https://user-images.githubusercontent.com/7359272/41972956-6414a522-7a0b-11e8-9fde-b0f8c4284c87.jpg)

**Comment by ValWood** [comment]
lipid particle organisation | exact
for GO:0034389 currently.....

**Comment by ValWood** [comment]
It's not an organelle is it?

**Comment by ValWood** [comment]
OK 

we say
GO:0043227    membrane-bounded organelle
Organized structure of distinctive morphology and function, bounded by a single or double lipid bilayer membrane. Includes the nucleus, mitochondria, plastids, vacuoles, and vesicles. Excludes the plasma membrane.


wikipedia says:
 Individual organelles are usually separately enclosed within their own lipid bilayers, but cannot be bound by one.

and doesn't list it
https://en.wikipedia.org/wiki/Organelle


but I don't think it does any harm to place it here....

**Comment by ValWood** [comment]
Ah OK, it's a "*non*-membrane bounded organelle"....

**Comment by pgaudet** [comment]
I now remember that there was a related ticket #13534 in which I had renamed most lipid particle (but somehow missed that term). 

Now fixed. 

Thanks, 
Pascale

**Comment by pgaudet** [comment]
Yes I did.
