### ISSUE TITLE
difference between a motility and a migration term (possible term merge)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15967]
In this instance,  is there a distinction between motility and migration?

GO:0090248    cell migration involved in somitogenic axis elongation
GO:0090247    cell motility involved in somitogenic axis elongation

if not suggest merge  to deepen existing annotations to migration

**Comment by vanaukenk** [comment]
@ValWood 
In AmiGO, I see one annotation to GO:0090248 from Zfin, so it doesn't look like a merge would change anything here as the migration term is a child of the motility term, as is the case for the relationship between motility and migration terms more generally in the ontology.

**Comment by ValWood** [comment]
Is there actually a *difference* in meaning between the two terms though?
I did not see one from reading the definitions and there are no siblings?

**Comment by ukemi** [comment]
Migration requires a direction. Motility is just movement. An ameba is motile. A neural crest cell migrates.

**Comment by ValWood** [comment]
That makes sense, but during  development, in this case why do you need a motility term?  This branch should only have migration shouldn't it?

**Comment by ukemi** [comment]
On the surface I would think yes, but both of these terms were the result of listening to a talk at the 2009 ASCB meeting. I don't think we would have created them if we didn't think there was a need for both. Unfortunately I just scanned the abstracts for the meeting and I couldn't find this talk. If you are going to merge, I would keep the migration term.

**Comment by ValWood** [comment]
I'm always wary from the terms that originated from listening to talks !

**Comment by vanaukenk** [comment]
@ValWood @ukemi 
Shall I go ahead and merge the motility term into the migration term?
That seems a reasonable thing to do at this point.

**Comment by ukemi** [comment]
"I guess", he says reluctantly.

**Comment by ValWood** [comment]
Hi @ukemi, what bothers you about this. Haven't we established  that the meaning is the same
in the context of "somitogenic axis elongation" ? (probably others, although I am sure there will be cases  where migration and motility are distinct but for devlopment it must be mainly *always* directional).

**Comment by vanaukenk** [comment]
Asking @RLovering to review annotations to 'regulation of cell motility involved in somitogenic axis elongation' before going ahead with merge.
https://github.com/geneontology/go-annotation/issues/2040

**Comment by ValWood** [comment]
I can see why this term would need to be precomposed to  bring it under the correct embroyonic development brances.

My question relates to why the "motility" term exists, and not just the more specific migration term.
Would you ever need to annotate to "motility" in this branch (and other developmental branches)

above @ukemi  said

"Migration requires a direction. Motility is just movement. An ameba is motile. A neural crest cell migrates."

so it isn't clear to me why these terms  have a migration parent in the development branch if motility is *always* migration here. It just allows for non-specific annotation. Maybe it is required to be ontologically correct but in this branch what would the siblings of the migration terms be?
If  siblings  could be added, they would need to stay, and "migration" could be made could be made "not for direct annotation" in this branch.


No annotation  review should be required, this is just an ontology issue. A merge would not affect existing annotation (except for the zfin annotation which would be more specific (motility).

 If a merge goes ahead the migration  synonyms would be "broad" in this branch to  encapsulate the slightly different meaning.
