### ISSUE TITLE
positive regulation of focal adhesion disassembly

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15964]
The assembly and disassembly of focal adhesion can be measured independently. I do not know if disassembly is completely independent of the assembly process. I guess there can be no disassembly unless there is assembly first. However, as we have GO:1905071 occluding junction disassembly terms I was hoping we could have an disassembly term, as follows:

GO:0034332 adherens junction organization
> is_a NEW TERM adherens junction disassembly
Definition: The disaggregation of an adherens junction into its constituent components. An adherens junction is a cell junction at which the cytoplasmic face of the plasma membrane is attached to actin filaments. PMID: 25490267

>> is_a NEW TERM cell-substrate adherens junction disassembly
Definition: The disaggregation of a cell-substrate adherens junction into its constituent components. PMID: 25490267

>>> is_a NEW TERM focal adhesion disassembly
Definition: The disaggregation of a focal adhesion into its constituent components. A focal adhesion, a complex of intracellular signaling and structural proteins that provides a structural link between the internal actin cytoskeleton and the ECM, and also function as a locus of signal transduction activity. PMID: 25490267

>>> regulation NEW TERM regulation of focal adhesion disassembly
Definition: Any process that modulates the frequency, rate or extent of disaggregation of a focal adhesion into its constituent components. PMID: 25490267

>>>> is_a NEW TERM positive regulation NEW TERM negative regulation of focal adhesion disassembly
Definition: Any process that activates or increases the frequency, rate or extent of disaggregation of a focal adhesion into its constituent components. PMID: 25490267

I haven't included all the parent terms here, I think looking at the ontology for the assembly terms might help, although care needs to be taken not to imply the role of positive reg of FA disassembly on adhesion. In the experiment shown in figure 3D in PMID: 25490267 Knockdown of MAP4K4 leads to both assembly and disassembly down regulation in the cells and this leads to a reduction in migration and adhesion. I can help with this more if you agree that we need these terms. 

Thanks

Ruth

**Comment by krchristie** [comment]
Hi @RLovering - I've put all these terms in, including both the positive and negative reg terms.

Compared to the regulation of focal adhesion assembly terms, which are automatically classified as 'regulation of cell junction assembly', there might be some need for some additional 'regulation of' terms to make sure that the equivalence axioms for the disassembly terms are generating all the correct classifications, but I'll leave it for now and if there is some classification that appears to be missing, we can add some intermediate terms.
