### ISSUE TITLE
propose primary term name change for mitochondrial respiratory chain complex IV assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15962]
can we call
GO:0033617    mitochondrial respiratory chain complex IV assembly

mitochondrial cytochrome c oxidase assembly

as it is universally referred?

(we don't refer to the ATP synthase as complex V)

**Comment by hdrabkin** [comment]
I can make the current name a synonym

**Comment by ValWood** [comment]
please, yes.
v

**Comment by ValWood** [comment]
Hi Harold,

Can we do this one

make mitochondrial cytochrome c oxidase assembly primary and 

GO:0033617 mitochondrial respiratory chain complex IV assembly exact synonym?

cheers

Val

**Comment by hdrabkin** [comment]
For some reason, I had this marked off in my spreadsheet.  
Done
