### ISSUE TITLE
Should 'Integrator complex' and mediator complex' be part of 'DNA-directed RNA polymerase II complex'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15979]
Continuing the work from #15870 

@bmeldal @krchristie are 'Integrator complex' and mediator complex'  part of 'DNA-directed RNA polymerase II complex'? 

Thanks, Pascale

**Comment by bmeldal** [comment]
From https://www.ebi.ac.uk/complexportal/complex/CPX-3227:

>Plays an essential role in gene expression regulation by **acting as a bridge between DNA-binding transcription factors and the RNA polymerase II (RNAPII) transcription machinery**, serving as a **central scaffold within the pre-initiation complex**. The Mediator complex is also targeted by sequence-specific, DNA-binding transcription factors and appears to **regulate RNAPII** at both the initiation and elongation stages of transcription. The Mediator complex, having a compact conformation in its free form, is recruited to promoters by direct interactions with regulatory proteins and unfolds to an extended conformation and partially surrounds RNAPII specifically interacting with the unphosphorylated form of its C-terminal domain. **The Mediator complex dissociates from the RNA polymerase II holoenzyme and stays at the promoter when transcriptional elongation begins.** Reversibly associates with the CKM complex (CPX-3232, CPX-3263). Mediator lacking the CKM complex has a stimulatory effect on basal transcription. In contrast, Mediator containing the sub-complex represses basal transcription.

So, no, not part of RNAPII. Will also need to change *holocomplex* in our def!

**Comment by bmeldal** [comment]
Have you got proteins for Integrator complex? I don't think we've curated that one yet.

GO:0032039 integrator complex
"A protein complex that **stably associates with the C-terminus of RNA polymerase II** and mediates 3'-end processing of small nuclear RNAs generated by RNA polymerase II."

So no, I'd say not part of RNAPII either. It interacts with it.

**Comment by pgaudet** [comment]
@ValWood I was referring to 'core mediator' GO:0070847 - this one is part of  GO:0016591 
DNA-directed RNA polymerase II, holoenzyme

**Comment by ValWood** [comment]
OK so core mediator merges into mediator? fine by me. We only use mediator.

**Comment by pgaudet** [comment]
I just wanted core mediator moved to NOT be a 'part of' GO:0016591
DNA-directed RNA polymerase II, holoenzyme. 

I can merge core mediator and mediator, I don't know of the distinction is important.

**Comment by pgaudet** [comment]
integrator complex -> change parent from 'nucleoplasm part' to 'part of' some nucleus (when it's active it's mot in the nucleoplasm) 

core mediator complex -> change parent from 'nucleoplasm part' to 'part of' some nucleus(when it's active it's mot in the nucleoplasm)

**Comment by ValWood** [comment]
I think its now somewhat arbitrary functionally.
https://en.wikipedia.org/wiki/Mediator_(coactivator)
some subunits are not always present, and there are different modules, but I don't see the advantage in annotating a core vs holo...

**Comment by ValWood** [comment]
core is without the cdk module

**Comment by ValWood** [comment]
the cdk module is not essential but many subunits are.  not sure...

**Comment by pgaudet** [comment]
Yeah we can leave the mediator and the core mediator separate for now. I'm just removing them from 'part of pol II  holoenzyme'. 

Pascale
