### ISSUE TITLE
To remove the synonyms for four GO terms related to cold-induced thermogenesis.

### ISSUE THREAD

**Issue by lijinbio** [geneontology/go-ontology#15973]
Hi GO,

We request to remove the synonyms for four GO terms previously assigned to us.

```
GO:0106106  cold-induced thermogenesis                         CIT
GO:0120161  regulation of cold-induced thermogenesis           regulation of CIT
GO:0120162  positive regulation of cold-induced thermogenesis  positive regulation of CIT
GO:0120163  negative regulation of cold-induced thermogenesis  negative regulation of CIT
```

Where CIT should not be a synonym for cold-induced thermogenesis since CIT is ambiguous that can refer to many other meanings, such as cold ischemia time (PMID: 29952816). Particularly, PubMed has returned over 3000 papers mentioning CIT, but most of them are not related to cold-induced thermogenesis. Therefore, please help remove the synonyms for above four GO terms. Thank you.

Best regards,
Jin

**Comment by ukemi** [comment]
Or perhaps just change the scope.

**Comment by hdrabkin** [comment]
already "related synonym"; would broad be better?

**Comment by ukemi** [comment]
Related should be fine.

**Comment by hdrabkin** [comment]
From original request: "Cold-induced thermogenesis (CIT) should be a children term of the existing term "adaptive thermogenesis".

**Comment by ukemi** [comment]
Synonyms
Alternative words or phrases closely related in meaning to the term name, with indication of the relationship between the name and synonym given by the synonym scope. The scopes for GO synonyms are:

exact
    an exact equivalent; interchangeable with the term name 
    e.g. ornithine cycle is an exact synonym of urea cycle 
broad
    the synonym is broader than the term name 
    e.g. cell division is a broad synonym of cytokinesis 
narrow
    the synonym is narrower or more precise than the term name 
    e.g. pyrimidine-dimer repair by photolyase is a narrow synonym of photoreactive repair 
related
    the terms are related in some way not covered above 
    e.g. cytochrome bc1 complex is a related synonym of ubiquinol-cytochrome-c reductase activity virulence is a related synonym of pathogenesis

**Comment by cmungall** [comment]
We can also use an abbreviation synonym type

This is the uberon syn guidelines which are derived from the GO ones:
https://github.com/obophenotype/uberon/wiki/Using-uberon-for-text-mining

I'd like to unify this across OBO ontologies

**Comment by pgaudet** [comment]
Opened a new ticket for the general issue brought up here. The work requested here is done according to our current guidelines.
