### ISSUE TITLE
Cdr2 medial cortical node complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15982]
At present we  have a grouping term
medial cortical node (GO:0071341)
medial cortical node representing nodes that form at the medial cortex at a different point in time.

I'd like a child term
Cdr2 medial cortical node complex
with the additional parent GO:1902911    protein kinase complex

def: A megadalton sized  complex organized an oligomeric core of SAD family  protein kinase involved in the cell size–dependent regulation of wee1 localization and required for phosphorylation of Wee1 in vivo.

ref PMID:29514920

The biophysical nature of Cdr2 nodes has been unclear. For example, these structures could represent stable biochemical complexes, or alternatively, they could be comprised of weakly aggregated proteins. The critical role of nodes in Wee1 signaling led us to investigate their stability in cell lysates. Using TIRF microscopy, we observed node-like structures in the lysates of cdr2-monomeric EGFP (mEGFP) cells (Fig. 1 D). These struc- tures were absent in the lysates of cdr2ΔC-mEGFP cells and in lysates of control cells that do not express GFP (Fig. 1 D). This result suggests that nodes remain intact upon cell lysis and may represent stable complexes. To test this possibility, we performed subcellular fractionation of detergent extracts on velocity sucrose gradients. The mutant cdr2ΔC was found in early fractions representing monomeric proteins and/or small complexes (Fig. 1 E). In contrast, full-length Cdr2 migrated in a broad pattern with a peak at 60S (Figs. 1 E and S1, A and B), consistent with a megadalton-sized complex. These fractions could be dialyzed and centrifuged on a second sucrose gradient without altering the sedimentation pattern of Cdr2 (Fig. S1 C), suggesting that nodes contain a stable core. TIRF microscopy of sucrose gradient fractions from Cdr2-mEGFP cells revealed node-like structures in later fractions and diffuse signal in ear- lier fractions (Fig. S1 D). Thus, Cdr2 nodes represent large stable complexes as revealed by independent imaging and biochem- ical approaches.

**Comment by ValWood** [comment]
medial cortical node (GO:0071341) is too restrictive as it refers only to early nodal activities

**Comment by ValWood** [comment]
I'll review  medial cortical node (GO:0071341)
and suggest  extended def. Should be OK as only used by pombe

**Comment by vanaukenk** [comment]
@ValWood 
I am assuming the relation between the requested complex term and the medial cortical node parent is part_of ?

**Comment by ValWood** [comment]
Yes, at first we didn't really know what the cortical nodes were, but is now seems that they are big macromolecular complexes (signalling foci).
