### ISSUE TITLE
Change equivalence axioms for nuclear DNA-directed RNA polymerase complex children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15980]
Hello, 

is the equivalence axiom of 'nuclear DNA-directed RNA polymerase complex' correct: 

'DNA-directed RNA polymerase complex'
 and ('part of' some nucleus)

... given that the children do not have logical definitions (and so, cannot be distinguished logically from the parent?) 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/4782928/42164040-082e9ddc-7e05-11e8-8b80-b436aa4a5274.png">

Thanks, Pascale

**Comment by ukemi** [comment]
Yes. This equivalence axiom is ok because it is necessary and sufficient to describe all instances of this class. All 'nuclear DNA-directed RNA polymerase complexes' are DNA-directed RNA polymerase complexes that are a part of a nucleus and there is no DNA-directed RNA polymerase complex that is part of a nucleus that is not a 'nuclear DNA-directed RNA polymerase complex'.

**Comment by pgaudet** [comment]
So it's OK that this also applies to all children ?

**Comment by ukemi** [comment]
All the children should also fit this class. However, the children should have other discriminating factors that separate them from one another, in this case, it would be the type of polymerase.

**Comment by pgaudet** [comment]
OK, thanks. To distinguish the type of polymerase, I can add 'capable of RNA polymerase I activity' (for example); is this right ?

**Comment by ukemi** [comment]
That seems like it would work, but what about the Pol II holoenzyme versus just the complex?

**Comment by pgaudet** [comment]
see #10556 - the  Pol II holoenzyme should go.

**Comment by pgaudet** [comment]
- Added logical definitions 
+intersection_of: GO:0000428 ! DNA-directed RNA polymerase complex
+intersection_of: capable_of GO:0001056 ! RNA polymerase I activity
+intersection_of: part_of GO:0005634 ! nucleus
for Pol I, II, III, IV, V

- Simplified term labels: 
from DNA-directed RNA polymerase I complex
to : RNA polymerase I complex
for Pol I, II, III, IV, V
