### ISSUE TITLE
NTR protein deamidation

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-ontology#15994]
NTR: protein deamidation

Def: the removal of amide groups from asparaginyl (Asn) and glutaminyl (Gln) residues in proteins

Is a GO:0006464 cellular protein modification process

Refs: PMID 11606750 and PMID 6304723

**Comment by pgaudet** [comment]
Hi @amandamackie 
Is this process mediated by a protein ? Looking quickly at the papers it seems like they measure deamidation of target proteins, not which proteins *mediate* the deamidation. 

('targets' of processes should not be annotated to the process). 

Thanks, Pascale

**Comment by amandamackie** [comment]
Hi Pascale,

Yes, CheB in E. coli mediates deamidation of chemoreceptor proteins. Actually I just saw the term GO:0018199 which is peptidyl glutamine modification so glutamine deamidation could be a child of that. I'll try and dig up a better reference 

Amanda

**Comment by pgaudet** [comment]
Great thanks - that wasn't obvious from the papers you sent (apologies if I didn't look closely enough though!)

**Comment by pgaudet** [comment]
Looking (quickly again) at https://en.wikipedia.org/wiki/Protein-glutamate_methylesterase, based on the fact that E. coli CheB (P07330) is annotated to EC 3.1.1.61 (http://www.sbcs.qmul.ac.uk/iubmb/enzyme/EC3/1/1/61.html), it looks like the enzyme catalyzes a demethylation, not a deamidation?

**Comment by amandamackie** [comment]
Yes, it does both - it deamidates glutamine residues (EC3.5.1.44) and it demethylates methylglutamates. It's all part of the adaption response in bacterial chemotaxis. Here's a review paper PMID 9442881 in Table 1 you can see that CheB is described as a methylesterase/amidase

**Comment by hdrabkin** [comment]
Interesting; PMID:25367007 states "Deamidation of asparagines and glutamines occurs spontaneously in proteins and results in protein degradation. Deamidation of asparaginyl residues in proteins produces a mixture of asparaginyl, n-aspartyl, and isoaspartyl residues, which has been linked to the pathology of some neurodegenerative disease"; 
PMID:11606750 does not really mention an enzymatic activity, but appears to measure spontaneous deamidation of purified proteins (?). 
However, PMID: 6304723 does show evidence that Che-B appears to *mediate *the deamination of a specific residue 

Question: Has this ever been shown with a purified protein product in vitro (ie, Che-B in a test-tube)?

BUT, Even if non-enzymatic, the rates could be enhanced/regulated by other proteins (like Che-B).

**Comment by deustp01** [comment]
Question: Has this ever been shown with a purified protein product in vitro (ie, Che-B in a test-tube)?

Answer: Sort of. See PMID:10919788 / PMCID:PMC92152 for a description of experiments in which an enzyme partially purified from the soil bacterium Chryseobacterium proteolyticum sp. nov. deaminated casein in vitro in studies said to distinguish deamidase activity from transaminase activity (which can mimic deamidase activity under the right assay conditions).

**Comment by amandamackie** [comment]
Based on the above, the term that I require is peptidyl or protein glutamine deamidation; my apologies for not being more specific in the first instance
Def: removal of amide groups from glutaminyl (Gln) residues in proteins

**Comment by hdrabkin** [comment]
maybe 'peptidyl/protein glutamine deamidation' would do the trick.

**Comment by pgaudet** [comment]
Isn't this inconsistent with other similar terms? Ie they are all named
'peptidyl...', aren't they?

**Comment by hdrabkin** [comment]
No; under peptide modifcation, there is a single term peptide amidation, which if one looks is NOT an amino acid side chain modification

Actually we may need two process terms, each specifying the target amino acid:

one a child of 
peptidyl-glutamine modification
the other a child of 
peptidyl-asparaginyl modification

**Comment by ValWood** [comment]
Hi @kaxelsen any feedback on this?

**Comment by kaxelsen** [comment]
In a way yes. EC 3.5.1.44 has been added to all the CheB proteins and in the entry from Halobacterium salinarum, i saw  When I pmid:18514223, in which one finding is: "CheB is required for Htr deamidations, at least at a specific glutamine–glutamate pair in Htr2 and a specific aspartate–glutamine pair in Htr4." It should be noted that this is not done with purified proteins but by MS/MS anaylsis of peptides from a size fraction of the entire proteome.

**Comment by ValWood** [comment]
what is the action here now that we no longer add modifications to the BP ontology?

**Comment by pgaudet** [comment]
Hi @amandamackie 
As @ValWood points out, we are not creating these types of biological processes anymore - ie processes that correspond exactly to a MF. If you'd like another term, such as a signaling pathway, we can create this, but otherwise in this case we would conclude that the bp that the enzyme is involved in is unknown. 

Thanks, Pascale
