### ISSUE TITLE
Improve definition of 'transcription coregulator activity' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15998]
Further improvements over changes made in #15566

New definitions by Colin Logie: 

**GO:0003712 transcription coregulator activity**
A protein or a member of a complex that interacts specifically and non-covalently with a DNA-bound DNA-binding transcription factor to either activate or repress the transcription of specific genes. 
Coregulators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second ATP-dependent class modifies the conformation of chromatin. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.

_(Previous definition: A protein or a member of a complex that interacts specifically and non-covalently with a DNA bound DNA-binding transcription factor to either activate or repress the transcription of specific genes. Coregulators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second ATP-dependent class modifies the conformation of chromatin. Another type of coregulator activity is the bridging of a DNA-binding transcription factor to the basal transcription machinery. The Mediator complex, which bridges transcription factors and RNA polymerase, is also a transcription coregulator (specifically, a coactivator)._

**GO:0003713 transcription coactivator activity**
A protein or a member of a complex that interacts specifically and non-covalently with a DNA-bound DNA-binding transcription factor to activate the transcription of specific genes. Coactivators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second ATP-dependent class modifies the conformation of chromatin. Another type of coregulator activity is the bridging of a DNA-binding transcription factor to the basal transcription machinery. The Mediator complex, which bridges transcription factors and RNA polymerase, is also a transcription coactivator.

_(Previous definition: A protein or a member of a complex that interacts specifically and non-covalently with a DNA-binding transcription factor to activate the transcription of specific genes. Coregulators often act by altering chromatin structure and modifications. The Mediator complex, which bridges transcription factors and RNA polymerase, is also a transcription coactivator.)_

**GO:0003714 transcription corepressor activity**
A protein or a member of a complex that interacts specifically and non-covalently with a DNA-bound DNA-binding transcription factor to repress the transcription of specific genes. Corepressors often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second ATP-dependent class modifies the conformation of chromatin. A third class occludes DNA-binding transcription factor protein-protein interaction domains. A third class of corepressors prevents interactions of DNA bound DNA-binding transcription factor with coactivators. 

_(Previous definition: A protein or a member of a complex that interacts specifically and non-covalently with a DNA-binding transcription factor to repress the transcription of specific genes. Coregulators often act by altering chromatin structure and modifications.)_

**Comment by pgaudet** [comment]
@krchristie @ValWood @RLovering 
Can you have a look and let me know if that seems correct to you ?

Thanks, Pascale

**Comment by ukemi** [comment]
We just ran into this looking at Ncoa4. It has a DNA binding domain, but I couldn't find any direct evidence that it acted as a typical DNA-binding transcription factor.

**Comment by krchristie** [comment]
@pgaudet - These definitions seem OK to me.
