### ISSUE TITLE
Revise 'GO:0036466 synaptic vesicle recycling via endosome'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#15990]
Revise 'GO:0036466 synaptic vesicle recycling via endosome'. Edit definition/modify relations, if required, to fit with the points emphasised by Pim in https://github.com/geneontology/go-ontology/issues/14540

**Comment by vanaukenk** [comment]
@ukemi - should @BarbaraCzub Barbara actually be assigned to this one?
You can give me another ticket in it's place :-)

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk and @ukemi, I opened this issue, because it's been hidden in another ticket, and it temporarily disappeared off the radar. But I need to prioritise annotating, so unless I happen to need this term for annotation, I will not be making any revisions to it in the near future (cc @RLovering). Since this has not been addressed for so long anyway, I assume this is not urgent?

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-ontology/issues/16825

**Comment by BarbaraCzub** [comment]
According to PMID:15217342 'GO:0036466 synaptic vesicle recycling via endosome' refers specifically to vesicles endocytosed via the clathrin-mediated route, and it is the process occurring _after_ clathrin-mediated endocytosis. It occurs in the presynaptic neuron. This is shown in PMID:15217342 in Figure 1 in steps 8 and 9 and in more detail in Figure 3.

Therefore, I will update the current definition only slightly to make it clear that the endosomal recycling occurs _after_ _clathrin-mediated_ endocytosis:

Current:
"Synaptic vesicle recycling where vesicles endocytose via clathrin-coated pits, re-acidify, and refill with neurotransmitters after passing through an endosomal intermediate. PMID:15217342"

Revised:
"Synaptic vesicle recycling where vesicles endocytose**d** via clathrin-coated pits re-acidify and refill with neurotransmitters after passing through an endosomal intermediate. PMID:15217342"

I will also remove the current relationship to 'postsynapse' ('synaptic vesicle recycling' is a part of 'synaptic vesicle cycle', which occurs in the 'presynapse') (please see Figure 1 in PMID:15217342).

At the same time I'll remove the relation between 'synaptic vesicle endosomal processing' and 'synaptic vesicle cycle' because the processing is _not_ a part of the cycle according to the GO term overview (please see screenshots below).

![screenshot 2019-02-04 at 16 21 40](https://user-images.githubusercontent.com/16541096/52221398-0590e500-2899-11e9-8a9b-15d40bb4bd79.png)

![gh15990](https://user-images.githubusercontent.com/16541096/52221414-0d508980-2899-11e9-9eb4-e887e18e63fe.png)

cc @RLovering @pgaudet @dosumis @pvannierop @ukemi @vanaukenk

**Comment by BarbaraCzub** [comment]
I will also add a _part_of_ relation between 'GO:0036466 synaptic vesicle recycling via endosome' (child term) and 'GO:0099532 synaptic vesicle endosomal processing' (parent term) to align the ontology relationships with the information in the 'GO:0099532 synaptic vesicle endosomal processing' term overview, i.e. "This [synaptic vesicle endosomal processing] covers processing of synaptic vesicles trafficked to synapse as well as of endocytosed vesicles as part of recycling. It is there for not part of the synaptic vesicle cycle." (I'll also correct the typo in this statement: 'there for' --> 'therefore').

cc @RLovering @pgaudet @dosumis @pvannierop @ukemi @vanaukenk

**Comment by BarbaraCzub** [comment]
@pvannierop @ftwkoopmans

Since these terms are in the synapse_slim, could you please confirm whether the SynGO team/project/experts agree with the revisions, which I suggested above?

Please do let me know, if I should not be making (any of) the suggested changes.

Thanks,
Barbara

cc @RLovering @thomaspd

**Comment by BarbaraCzub** [comment]
Hi @pvannierop @ftwkoopmans
Is it ok if I go ahead and make these changes?
Thanks,
Barbara
cc @RLovering

**Comment by ftwkoopmans** [comment]
If the intent of this term is to strictly use this for recycling clathrin coated vesicles, the proposed changes would be fine. However, this excludes activity-dependent bulk endocytosis, a major mode of SV retrieval during stimulation/activity. So perhaps it is better to keep the scope for 'SV recycling via endosome' inclusive for both major modes of endocytosis. 

We don't have a use-case for further specialization of the term into clathrin-mediated or bulk endocytosis atm. Published evidence often points to 'SV recycling via endosome' and perhaps not the specific mechanism, so we'd probably end up annotating against this generic term in most cases.

**Comment by BarbaraCzub** [comment]
Hi @ftwkoopmans 
Thank you for getting back to me wrt 'synaptic vesicle recycling via endosome'.

According to the Sudhof review of synaptic vesicle cycle (PMID:15217342, Figure 1 and Figure 3), 'synaptic vesicle recycling via endosome' occurs _after_ clathrin-mediated endocytosis, therefore it should refer specifically to vesicles endocytosed via the clathrin-mediated route.
The bulk endocytosis will still have the 'grandparent' term 'synaptic vesicle recycling', which covers the process with the endosome intermediate as well as the 'kiss-and-stay' and 'kiss-and-run' reuse/recycling mechanisms (PMID:15217342, Figure 3). So this relation to 'synaptic vesicle recycling' would be maintained. 

With regard to the use case, 'SV recycling via endosome' suggest that a clathrin-mediated endocytosis would have occurred in the first place (again based on the same review (PMID:15217342). And if this is not clear from the experiments, then the more generic GO term 'synaptic vesicle recycling' will cover recycling of vesicles endocytosed via either mechanism.

So since this is not going to affect any of the SynGO work, then I will refine the definition 'synaptic vesicle recycling via endosome' as I suggested above. 

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
@ftwkoopmans my second suggested revision is that we should break the relationship between  'synaptic vesicle recycling via endosome' and its current 'postsynapse' parent. 'Synaptic vesicle recycling (via endosome)' is a part of 'synaptic vesicle cycle', which occurs in the 'presynapse' (Please see Figure 1 in the same review PMID:15217342). Therefore, I think there is an error in the ontology and the relation to 'postsynapse' is incorrect. Could you please correct me, if I am wrong and the relation to 'postsynapse' is in fact correct? I will appreciate the SynGO team's advice on this.
Thanks,
Barbara

cc @RLovering @thomaspd @pgaudet

**Comment by BarbaraCzub** [comment]
@ftwkoopmans my third suggested revision is about the relations of the GO term 'synaptic vesicle endosomal processing'. The comment in the GO term entry states that the processing is **not** a part of 'synaptic vesicle cycle', whereas the ontology shows the opposite (please see the screenshots in my comment above 4 days ago). 

I think we need to remove the ontology relationship. If we keep it and remove the comment, then 'synaptic vesicle endosomal processing' would just be synonymous with 'synaptic vesicle recycling via endosome', wouldn't it? 

After removing the parent relationship to 'synaptic vesicle cycle', I will then add a _part_of_ relation between 'GO:0036466 synaptic vesicle recycling via endosome' (child term) and 'GO:0099532 synaptic vesicle endosomal processing' (parent term) to finish off these revisions. 

Before I make any of these changes, could you please confirm whether these will be in agreement with the SynGO work?

I will look forward to hearing from you.

Thanks,
Barbara

cc @RLovering @thomaspd @pgaudet

**Comment by ftwkoopmans** [comment]
> @ftwkoopmans my second suggested revision is that we should break the relationship between 'synaptic vesicle recycling via endosome' and its current 'postsynapse' parent. 'Synaptic vesicle recycling (via endosome)' is a part of 'synaptic vesicle cycle', which occurs in the 'presynapse' (Please see Figure 1 in the same review PMID:15217342). Therefore, I think there is an error in the ontology and the relation to 'postsynapse' is incorrect. Could you please correct me, if I am wrong and the relation to 'postsynapse' is in fact correct? I will appreciate the SynGO team's advice on this.
> Thanks,
> Barbara

agreed, drop the postsynapse relation

**Comment by ftwkoopmans** [comment]
> @ftwkoopmans my third suggested revision is about the relations of the GO term 'synaptic vesicle endosomal processing'. The comment in the GO term entry states that the processing is **not** a part of 'synaptic vesicle cycle', whereas the ontology shows the opposite (please see the screenshots in my comment above 4 days ago).
> 
> I think we need to remove the ontology relationship. If we keep it and remove the comment, then 'synaptic vesicle endosomal processing' would just be synonymous with 'synaptic vesicle recycling via endosome', wouldn't it?
> 
> After removing the parent relationship to 'synaptic vesicle cycle', I will then add a _part_of_ relation between 'GO:0036466 synaptic vesicle recycling via endosome' (child term) and 'GO:0099532 synaptic vesicle endosomal processing' (parent term) to finish off these revisions.
> 
> Before I make any of these changes, could you please confirm whether these will be in agreement with the SynGO work?
> 
> I will look forward to hearing from you.
> 
> Thanks,
> Barbara
> 

I think your proposed edits cover our original intent for this term (which are mentioned in the GO term comment)

**Comment by ftwkoopmans** [comment]
> Hi @ftwkoopmans
> Thank you for getting back to me wrt 'synaptic vesicle recycling via endosome'.
> 
> According to the Sudhof review of synaptic vesicle cycle (PMID:15217342, Figure 1 and Figure 3), 'synaptic vesicle recycling via endosome' occurs _after_ clathrin-mediated endocytosis, therefore it should refer specifically to vesicles endocytosed via the clathrin-mediated route.
> The bulk endocytosis will still have the 'grandparent' term 'synaptic vesicle recycling', which covers the process with the endosome intermediate as well as the 'kiss-and-stay' and 'kiss-and-run' reuse/recycling mechanisms (PMID:15217342, Figure 3). So this relation to 'synaptic vesicle recycling' would be maintained.
> 
> With regard to the use case, 'SV recycling via endosome' suggest that a clathrin-mediated endocytosis would have occurred in the first place (again based on the same review (PMID:15217342). And if this is not clear from the experiments, then the more generic GO term 'synaptic vesicle recycling' will cover recycling of vesicles endocytosed via either mechanism.
> 
> So since this is not going to affect any of the SynGO work, then I will refine the definition 'synaptic vesicle recycling via endosome' as I suggested above.
> 
> Thanks,
> Barbara

I think this works if you explicitly state that this term only captures SV recycling events that have a clathrin coated vesicle as intermediate (clathrin-mediated endocytosis). For now we can put activity-dependent bulk endocytosis annotations in the more general SV recycling term, as you mentioned.

After the paper is out we can finally get back to expanding SynGO annotations. I'll see if I can get any domain experts for endocytosis on board for a review of respective ontologies in future SynGO meetups.

**Comment by BarbaraCzub** [comment]
> > @ftwkoopmans my third suggested revision is about the relations of the GO term 'synaptic vesicle endosomal processing'. The comment in the GO term entry states that the processing is **not** a part of 'synaptic vesicle cycle', whereas the ontology shows the opposite (please see the screenshots in my comment above 4 days ago).
> > I think we need to remove the ontology relationship. If we keep it and remove the comment, then 'synaptic vesicle endosomal processing' would just be synonymous with 'synaptic vesicle recycling via endosome', wouldn't it?
> > After removing the parent relationship to 'synaptic vesicle cycle', I will then add a _part_of_ relation between 'GO:0036466 synaptic vesicle recycling via endosome' (child term) and 'GO:0099532 synaptic vesicle endosomal processing' (parent term) to finish off these revisions.
> > Before I make any of these changes, could you please confirm whether these will be in agreement with the SynGO work?
> > I will look forward to hearing from you.
> > Thanks,
> > Barbara
> 
> I think your proposed edits cover our original intent for this term (which are mentioned in the GO term comment)

Thanks ftwkoopmans
This is very helpful.
In this case I'll make the suggested changes for the 'synaptic vesicle endosomal processing' GO term.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
> > Hi @ftwkoopmans
> > Thank you for getting back to me wrt 'synaptic vesicle recycling via endosome'.
> > According to the Sudhof review of synaptic vesicle cycle (PMID:15217342, Figure 1 and Figure 3), 'synaptic vesicle recycling via endosome' occurs _after_ clathrin-mediated endocytosis, therefore it should refer specifically to vesicles endocytosed via the clathrin-mediated route.
> > The bulk endocytosis will still have the 'grandparent' term 'synaptic vesicle recycling', which covers the process with the endosome intermediate as well as the 'kiss-and-stay' and 'kiss-and-run' reuse/recycling mechanisms (PMID:15217342, Figure 3). So this relation to 'synaptic vesicle recycling' would be maintained.
> > With regard to the use case, 'SV recycling via endosome' suggest that a clathrin-mediated endocytosis would have occurred in the first place (again based on the same review (PMID:15217342). And if this is not clear from the experiments, then the more generic GO term 'synaptic vesicle recycling' will cover recycling of vesicles endocytosed via either mechanism.
> > So since this is not going to affect any of the SynGO work, then I will refine the definition 'synaptic vesicle recycling via endosome' as I suggested above.
> > Thanks,
> > Barbara
> 
> I think this works if you explicitly state that this term only captures SV recycling events that have a clathrin coated vesicle as intermediate (clathrin-mediated endocytosis). For now we can put activity-dependent bulk endocytosis annotations in the more general SV recycling term, as you mentioned.
> 
> After the paper is out we can finally get back to expanding SynGO annotations. I'll see if I can get any domain experts for endocytosis on board for a review of respective ontologies in future SynGO meetups.

Thanks @ftwkoopmans , so I will make the suggested (only minor) revision now, and if domain experts will be able to comment on this further, then we will re-visit this in the future.
Thanks for all your help with this. I'll go ahead with the suggested edits.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-ontology/pull/16921
