### ISSUE TITLE
NTRs: 'visual system development' and child term

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16007]
While annotating PMID:22632727 I have come across the term 'eye-specific segregation', a visual developmental process modulated by complement-dependent synaptic pruning (re: https://github.com/geneontology/go-ontology/issues/16003).

I suggest the following new terms:

> New1: visual system development
Definition: The process whose specific outcome is the progression of the visual system over time, from its formation to the mature structure. The visual system forms a part of the central nervous system and it is required for integrating and coordinating visual stimuli. In vertebrates it consists of the neural retina in the eye and brain regions which process information received from the eye. 
PMIDs: 20647017, 22632727. GOC:aruk. GOC:bc.
Related synonyms: visual pathway development, optic pathway development 
is_a parent: central nervous system development

>> New1a: eye-specific patterning
Definition: Early postnatal developmental process, during which axons of retinal ganglion cells (RGCs), transmitting overlapping inputs from both eyes, segregate into distinct eye-specific non-overlapping regions in the dorsal lateral geniculate nucleus (dLGN) of the thalamus.
PMID: 16025107, 2263272, 29322522. GOC:aruk. GOC:bc.
Exact synonym: eye-specific segregation
Related synonym: binocular vision development

Please let me know, if you have any comments or suggestions regarding these terms.

Thanks,
Barbara

cc:
@RLovering
@rachhuntley
@paolaroncaglia

**Comment by krchristie** [comment]
I was wondering if it would be OK for a general term for 'visual system development' to be a type of 'central nervous system development' as cephalopods have complex visual system but have  eyes and nervous system that are significantly different than those of vertebrates. Checking PubMed, this is fine for cephalopods, but perhaps you could add this sentence [and additional references] to help make it clear that this term is also applicable to cephalopods:

Similarly in cephalopods, the visual system consists of a neural retina in a camera-type eye as well as optic regions of the brain for processing visual input. [PMID:15004427, GOC:krc]

It might also be worth considering if this definition is applicable to all visual systems, e.g. insects with compound eyes. @hattrill

**Comment by krchristie** [comment]
Regarding the second term for 'eye-specific patterning', the definition seems specific to vertebrate anatomy, so you might want to consider making the term explicitly more specific, e.g. 'vertebrate eye-specific patterning', or something to clarify, and perhaps a taxon constraint.

**Comment by cmungall** [comment]
[UBERON:0002104](http://purl.obolibrary.org/obo/UBERON_0002104) ! visual system

in uberon this is not part of the CNS, as the visual system includes the whole eye which includes non-nervous tissue. From a developmental perspective this is probably too strict and eye development truly is part of CNS development

**Comment by hattrill** [comment]
Hi Karen, I am going to pass this question on to Mr VFB @dosumis as the answer I came up was both contraditory and non-commital!

**Comment by BarbaraCzub** [comment]
Thank you @krchristie for your suggestion wrt invertebrates and @cmungall for pointing out that the visual system is not a part of the CNS since it includes the whole eye. Based on your feedback I've made a few revisions to the suggested terms (below). The revised 'visual system development' definition should now be general enough to cover vertebrates as well as invertebrates, and not be restrictive to the CNS. Whereas 'vertebrate eye-specific patterning' will certainly be restricted to vertebrates, and it will also be a part of 'central nervous system development'. Please let me know, if you have any more comments. Thanks!

> GO:0048880 'sensory system development'
>> New1: 'visual system development' (is_a: GO:0048880 'sensory system development')
Definition: The process whose specific outcome is the progression of the visual system over time, from its formation to the mature structure, including the eye, parts of the central nervous system (CNS) involved in processing of visual inputs, and connecting nerve pathways.
PMIDs: 20647017, 22632727, PMID:15004427, GOC:krc, GOC:aruk, GOC:bc.
Related synonyms: visual pathway development, optic pathway development
>>> GO:0001654 'eye development' (part_of: New1: 'visual system development')
>>> New1a: vertebrate eye-specific patterning (part_of: New1: 'visual system development', part_of: GO:0007417 'central nervous system development', only_in_taxon some 'Vertebrata <Metazoa>')
Definition: Early postnatal vertebrate developmental process, during which axons of retinal ganglion cells (RGCs), transmitting overlapping inputs from both eyes, segregate into distinct eye-specific non-overlapping regions in the dorsal lateral geniculate nucleus (dLGN) of the thalamus.
PMID: 16025107, 2263272, 29322522. GOC:aruk. GOC:bc.
Exact synonym: vertebrate eye-specific segregation
Related synonyms: eye-specific segregation, eye-specific patterning, binocular vision development

**Comment by krchristie** [comment]
Hi @BarbaraCzub - You've address all of my concerns, so this looks fine to me. Thanks :)

**Comment by BarbaraCzub** [comment]
Hi @krchristie, thanks for your feedback.

**Comment by dosumis** [comment]
Suggested edits look good to me.

**Comment by BarbaraCzub** [comment]
Thanks @dosumis!
