### ISSUE TITLE
NTR steroid hormone biosynthesis

### ISSUE THREAD

**Issue by lenov** [geneontology/go-ontology#16000]
Hello,

There is a term for "steroid biosynthesis", but no term for "steroid hormone biosynthesis". The two things are different, see KEGG PATHWAYS map00100 and map00140

It would be very useful to have a term:

name:  steroid hormone biosynthesis process

def: The chemical reactions and pathways resulting in the formation of any steroid hormone, naturally occurring substances secreted by specialized cells that affects the metabolism or behavior of other cells possessing functional receptors for the hormone. 

is_a: GO:0042446 hormone biosynthetic process

children:
all the children of  GO:0042446 that are biosynthetic processes of steroid hormons (e.g. quercetin,  vitamin D3, ecdysteroid, etc. There are quite a lot)

**Comment by krchristie** [comment]
I made the requested new term 'steroid hormone biosynthetic process' with this equivalence axiom:

'steroid biosynthetic process'
 and ('has output' some 'substance with hormone role')

which (with the reasoner on) results in automatic classification of these terms as child terms of the new term:

![20180706steroidhormonebiosysthesis](https://user-images.githubusercontent.com/10533218/42403379-9abd6074-8135-11e8-859d-09968865fc81.jpg)

I don't really want to get into manually classifying the child terms, so I am going to leave this as it came out via reasoning. 

If you feel this equivalence axiom is incorrect, please let me know, and perhaps suggest what it should be.

Thanks, Karen

Note: I haven't actually been able to commit this yet, so you won't see it in the production version yet.

**Comment by ukemi** [comment]
I thought ChEBI had a class for steroid hormone, but I may be mistaken.

**Comment by krchristie** [comment]
@ukemi - ChEBI does have a class for steroid hormone:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:26764 

ChEBI Name | steroid hormone
-- | --
ChEBI ID | CHEBI:26764
Definition | Any steroid that acts as hormone.

but I'm not really sure what you  are suggesting with that comment. It also doesn't really change the fact that I do not want to manually classify any of the pre-existing terms that were direct children of 'hormone biosynthetic process'. Running the reasoner automatically classifies a number of things under the new term 'steroid hormone biosynthetic process', including two of the things that @lenov mentioned, specifically ecdysteroid and vitamin D3. However, he also mentioned quercetin and the term 'quercetin biosynthetic process' did NOT get automatically classified as a 'steroid hormone biosynthetic process'. So, if the 'quercetin biosynthetic process'  or any other hormone biosynthetic terms should be classified under the new steroid hormone biosynthetic process' term, then it may be that there are issues with their classification in ChEBI.

@lenov - Could you please provide a reference for the definition. A PubMed ID would be fine. We can also credit you as a source for the definition if you let me know what initials you use (for example, definitions credited to me are listed with the dbxref GOC:krc). If you have not previously been credited, we will need to check the current list to make sure we create something unique for you. DOI's are also allowed. A definition may have multiple references, of multiple different types.

**Comment by krchristie** [comment]
@lenov - I can't proceed with this without a reference cited for the definition, one or more PMIDs and/or one or more curators (e.g. GOC:krc) can be cited. If you can provide this info this week, I should be able to finish this before I go on vacation from July 21-28.

Thanks, Karen

**Comment by krchristie** [comment]
@lenov - Not having completed this one before going on medical leave, I'm finally looking at it again today. In the absence of a PubMed ID to cite for the definition reference, I have included both you (GOC:nln) and me (GOC:krc) via our official citations in the users.yaml file.
