### ISSUE TITLE
NTRs: 'multiple-synapse bouton' and 'multiple spine synapse assembly'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16001]
While annotating PMID:24487234, I have come across Figure 1 (i-k), which shows that mice lacking Cx3cr1 contain significantly fewer multisynapse boutons (MSBs) than wild-type mice. The authors also differentiate between two types of MSBs, and show that this effect is true only for MSB type 1 (MSB1), in which synaptic terminal bouton makes contact onto two or more dendritic spines from the same dendrite (rather than type 2 (MSB2), in which the contact is made with spines protruding from multiple dendrites.

Other references describing multisynapse boutons include: PMIDs: 7482800, 8366344, 10586883, 11248111, 11466428, 18501438, 22028887, 29774619.

I suggest the following new terms:

> CC New1: multiple synapse bouton 
Definition: A single axon terminal bouton making contact onto two or more dendritic spines protruding either from a single or multiple dendrites. 
PMIDs: 7482800, 8366344, 10586883, 11248111, 11466428, 18501438, 22028887, 29774619. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic boutons, multi-synaptic boutons, multisynapse boutons, multi-synapse boutons, multiple-synapse boutons, MSB, multiple spine synapse bouton. 
Broad/Related synonym: multisynapse, multi-synapse, multiple synapse
is_a parent: ‘terminal bouton’

>> CC New1a: multiple synapse bouton, contacting single dendrite  
Definition: A single axon terminal bouton making contact onto two or more dendritic spines protruding from the same dendrite. 
PMIDs: 10586883, 11248111, 22028887, 24487234. GOC:aruk. GOC:bc. 
Exact synonym: type 1 multiple-synapse bouton, type 1 multisynaptic boutons, type 1 multi-synaptic boutons, type 1 multisynapse boutons, type 1 multi-synapse boutons, type 1 multiple-synapse boutons, MSB1, type 1 multiple spine synapse bouton. 

>> CC New1b: multiple synapse bouton, contacting multiple dendrites 
Definition: A single axon terminal bouton making contact onto two or more dendritic spines protruding from multiple dendrites. 
PMIDs: 7482800, 8366344, 10586883, 11248111, 22028887, 24487234. GOC:aruk. GOC:bc.
Exact synonym: type 2 multiple-synapse bouton, type 2 multisynaptic boutons, type 2 multi-synaptic boutons, type 2 multisynapse boutons, type 2 multi-synapse boutons, type 2 multiple-synapse boutons, MSB2, type 2 multiple spine synapse bouton. 

> BP New1: multiple spine synapse assembly
Definition: The aggregation, arrangement and bonding together of a multiple synapse bouton and two or more dendritic spines protruding either from a single or multiple dendrites.
PMIDs: 7482800, 8366344, 10586883, 11248111, 11466428, 18501438, 22028887, 29774619. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic assembly, multi-synaptic assembly, multisynapse assembly, multi-synapse assembly, multisynaptic biogenesis, multi-synaptic biogenesis, multisynapse biogenesis, multi-synapse biogenesis.
is_a parent: synapse assembly

>> BP New1a: multiple spine synapse assembly, single dendrite
Definition: The aggregation, arrangement and bonding together of a multiple-synapse bouton and two or more dendritic spines protruding from a single dendrite.
PMIDs: 10586883, 11248111, 22028887, 24487234. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic assembly, multi-synaptic assembly, multisynapse assembly, multi-synapse assembly, multisynaptic biogenesis, multi-synaptic biogenesis, multisynapse biogenesis, multi-synapse biogenesis.

>> BP New1b: multiple spine synapse assembly, multiple dendrites
Definition: The aggregation, arrangement and bonding together of a multiple-synapse bouton and two or more dendritic spines protruding from multiple dendrites.
PMIDs: 7482800, 8366344, 10586883, 11248111, 22028887, 24487234. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic assembly, multi-synaptic assembly, multisynapse assembly, multi-synapse assembly, multisynaptic biogenesis, multi-synaptic biogenesis, multisynapse biogenesis, multi-synapse biogenesis.

@Pimmelorus, if you could find a moment, could you please let me know whether you agree with the above suggestions based on your expert knowledge?

@paolaroncaglia, could you please take a look at the suggested names for the more specific terms differentiating between multiple spine synapses involving either a single dendrite or multiple dendrites? I did consider naming them 'type 1...' and 'type 2...' like I did for the synonyms, but only PMID:24487234 seems to describe them by these names.

Thanks,
Barbara

cc:
@RLovering
@rachhuntley

**Comment by Pimmelorus** [comment]
@BarbaraCzub 
I see no problem with your implementations. However, the paper that you state is on synaptic pruning (removal), not synapse assembly as suggested by your terms. When looking at static synapse numbers, one can not make our whether a protein is involved in promoting synapse removal or reducing synapse assembly. For this reason SynGO defaults to 'synapse organization' when the precise mechanism is unknown.

**Comment by paolaroncaglia** [comment]
@BarbaraCzub
(cc:
@RLovering
@rachhuntley)

Looking at the BP terms now

BP New1: multiple spine synapse assembly
**(assembly -> organization as previously agreed)**
Definition: The aggregation, arrangement and bonding together of a multiple synapse bouton and two or more dendritic spines protruding either from a single or multiple dendrites.
**(Modify based on 'organization')**
PMIDs: 7482800, 8366344, 10586883, 11248111, 11466428, 18501438, 22028887, 29774619. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic assembly, multi-synaptic assembly, multisynapse assembly, multi-synapse assembly, multisynaptic biogenesis, multi-synaptic biogenesis, multisynapse biogenesis, multi-synapse biogenesis.
**(Modify based on 'organization')**
is_a parent: synapse assembly
**(Modify based on 'organization')**

BP New1a: multiple spine synapse assembly, single dendrite
Definition: The aggregation, arrangement and bonding together of a multiple-synapse bouton and two or more dendritic spines protruding from a single dendrite.
PMIDs: 10586883, 11248111, 22028887, 24487234. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic assembly, multi-synaptic assembly, multisynapse assembly, multi-synapse assembly, multisynaptic biogenesis, multi-synaptic biogenesis, multisynapse biogenesis, multi-synapse biogenesis.
**(Name and definition to be modified based on 'organization'. 
It would be incorrect to add the same exact synonyms as the parent term, in fact I think there's an ontology check that flags when multiple terms have the same synonym(s).)**

BP New1b: multiple spine synapse assembly, multiple dendrites
Definition: The aggregation, arrangement and bonding together of a multiple-synapse bouton and two or more dendritic spines protruding from multiple dendrites.
PMIDs: 7482800, 8366344, 10586883, 11248111, 22028887, 24487234. GOC:aruk. GOC:bc.
Exact synonym: multisynaptic assembly, multi-synaptic assembly, multisynapse assembly, multi-synapse assembly, multisynaptic biogenesis, multi-synaptic biogenesis, multisynapse biogenesis, multi-synapse biogenesis.
**(Name and definition to be modified based on 'organization'. 
It would be incorrect to add the same exact synonyms as the parent term, in fact I think there's an ontology check that flags when multiple terms have the same synonym(s).)**

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia 

Thank you for your feedback, I'll follow your suggestions. 

I do not recall any definite statements from the literature about functional differences between multiple synapse boutons, contacting single or multiple dendrites, therefore, I will not be adding these comments for now. I expect the functional differences may become clearer as I continue annotating, and so I will add these comments if/when I've come across conclusive evidence.

The plural forms 'boutons' in the CC synonym sections were copy-paste error, as was including the BP parent term as synonym. Thank you for pointing these out.

Thank you for your help!
Barbara
