### ISSUE TITLE
Process or phenotype? 'synaptic multiplicity (development)'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16002]
I have come across the term 'synaptic multiplicity', while annotating PMID:24487234, which shows that mice lacking Cx3cr1 contain significantly fewer multisynapse boutons (MSBs) than wild-type mice, which manifests itself as a deficit in 'synaptic multiplicity' in adulthood.

But should synaptic multiplicity formation be considered a developmental process, or is synaptic multiplicity (or here: its deficit) a phenotype?  

A new BP term 'synaptic multiplicity development' could potentially by defined as: 'A postnatal developmental process, modulated by microglia-mediated synaptic pruning essential for proper neural circuit maturation, during which two neurons initially connect through a single synapse and add more connections over time to form multiple spine synapses'.  

Could someone please share their thoughts on this? @Pimmelorus, perhaps you'd be able to comment on this?

Thanks,
Barbara

cc:
@RLovering
@paolaroncaglia
@rachhuntley

**Comment by Pimmelorus** [comment]
@BarbaraCzub 
To be honest, I have never heard of MSBs or synapse multiplicity before. As I read the paper, synaptic multiplicity (SM) represents the extent to which a single presynaptic terminal forms synapses with different dendritic spines. High SM is observed at an immature developmental stage of the neuronal network:

> These findings show that a transient reduction in microglia results in a long-term deficit in synaptic multiplicity despite normal excitatory synapse number and suggest that there is a critical window during which microglia-mediated synaptic pruning is essential for proper circuit maturation.

I would *not* consider 'SM development' a BP term since SM is a proxy for the development of the neuronal circuitry driven by synapse pruning.

**Comment by BarbaraCzub** [comment]
Hi @Pimmelorus, thank you for your feedback. Could you also please comment on 'functional connectivity'? I suppose that similarly to your conclusion regarding 'synaptic multiplicity', you would not consider 'functional connectivity' a process either, because it is also a reflection of more specific underlying processes?

Thanks,
Barbara

**Comment by Pimmelorus** [comment]
> I suppose that similarly to your conclusion regarding 'synaptic multiplicity', you would not consider 'functional connectivity' a process either

No, indeed. It is a trait with different phenotypes, not a process.

**Comment by BarbaraCzub** [comment]
Thank you!
