### ISSUE TITLE
NTRs: 'synapse pruning' and child terms

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16003]
I have recently come across several papers describing 'synapse pruning' (e.g. PMIDs: 18083105, 21778362 , 22632727) and its more specific complement-dependent type (e.g. PMIDs:18083105, 22632727), yet, we do not have GO terms describing these processes.

Below are my suggestions:

> New1: synapse pruning
Definition: Developmental process involving microglial phagocytic engulfment of redundant synapse fragments, required for maintenance of optimal long-term synapse density and activity.
PMIDs: 18083105, 21778362 , 22632727. GOC:aruk. GOC:bc.
Exact synonym: synaptic pruning
Related synonyms: synapse elimination, synapse remodelling, synaptic elimination, synaptic remodelling (or should these be 'broad' synonyms? @paolaroncaglia or @ukemi perhaps you could advise on this?)
is_a parents: neuron remodeling; phagocytosis, engulfment

>> New1a: complement-dependent synaptic pruning
Definition: Synaptic pruning mediated by complement system signalling.
PMIDs:18083105, 22632727, 29844190. GOC:aruk. GOC:bc.
Exact synonym: complement-dependent synaptic pruning

Please let me know, if you have any comments, or suggestions, esp. with regard to the definitions. @Pimmelorus, perhaps you'd be able to comment on this?

Thanks,
Barbara

cc:
@RLovering
@rachhuntley
@paolaroncaglia

**Comment by Pimmelorus** [comment]
@BarbaraCzub 
I use the term 'synapse disassembly (GO:0098883)' for synaptic pruning.

**Comment by Pimmelorus** [comment]
@BarbaraCzub 
I am in no way an expert in synapse pruning, but I think that your interpretation of the process and its child terms is incorrect. Take a look at this wikipedia text on synapse pruning:

> The three models explaining synaptic pruning are axon degeneration, axon retraction, and axon shedding. In all cases, the synapses are formed by a transient axon terminal, and synapse elimination is caused by the axon pruning. Each model offers a different method in which the axon is removed to delete the synapse. In small-scale axon arbor pruning, neural activity is thought to be an important regulator,[citation needed] but the molecular mechanism remains unclear. Hormones and trophic factors are thought to be the main extrinsic factors regulating large-scale stereotyped axon pruning.[6]

I conclude that 'synapse pruning' describes the loss of synapses (see terms 'synapse elimination' and 'delete the synapse' in the text above) and that there are different ways this can be caused. So I think that the terms are 'synapse disassembly (GO:0098883)' and 'synaptic pruning' should be considered synonyms.

**Comment by BarbaraCzub** [comment]
Thanks @Pimmelorus for your quick reply and clarifying this. You're certainly much more of an expert than I am, so I am going to follow your suggestion, and add 'synapse pruning' as a synonym of  'synapse disassembly (GO:0098883)'. It did cross my mind that the 'synapse retraction' referred to in PMID: 12062020 (that only paper which I found mentioning this) might have been intended more broadly as a 'neurite retraction' for which we do actually have a GO term ('neuron projection retraction' (GO:0106028)). So, your feedback is reassuring, thank you.

**Comment by BarbaraCzub** [comment]
To do:

- [ ] Find out how many annotations to 'synapse disassembly' are expected from the SynGO project

- [ ] Would the mechanism for these annotations always be pruning by microglia (i.e. phagocytic engulfment)? 

- [ ] Based on the above should 'synapse disassembly' be obsoleted/changed to 'synapse pruning'? Or should 'synapse pruning become a new independent term?

**Comment by BarbaraCzub** [comment]
None of the papers annotated by SynGO use the phrase 'synapse disassembly'; however, they mention 'elimination', 'pruning', 'retraction', 'collapse', 'refinement', or 'remodelling' (analysis details:
https://docs.google.com/spreadsheets/d/1x0PeAEHlsyaBaTN7rf_Oe1icrhkGKtTQIlmDeAP35kM/edit?usp=sharing).

---
Language definitions:

To [prune](https://dictionary.cambridge.org/dictionary/english/prune) (from Cambridge Dictionary):
- to cut off branches from a tree, bush, or plant, especially so that it will grow better in the future;
- to reduce something by removing things that are not necessary.

To [disassemble](https://dictionary.cambridge.org/dictionary/english/disassemble) (from Cambridge Dictionary):
- to separate something into its different parts.

To [retract](https://dictionary.cambridge.org/dictionary/english/retract) (from Cambridge Dictionary):
- to pull something back or in.

To [eliminate](https://dictionary.cambridge.org/dictionary/english/eliminate) (from Cambridge Dictionary)
-  to remove or take away someone or something.

To [refine](https://dictionary.cambridge.org/dictionary/english/refine) (from Cambridge Dictionary)
- to make something pure or improve something, especially by removing unwanted material.

To [remodel](https://dictionary.cambridge.org/dictionary/english/remodel) (from Cambridge Dictionary)
- to give a new shape or form to something.

To [collapse](https://dictionary.cambridge.org/dictionary/english/collapse) (from Cambridge Dictionary)
- to fall down suddenly because of pressure or having no strength or support (from Cambridge Dictionary);
- to fold something into a smaller shape, usually so it can be stored, or (especially of furniture) to fold in this way (from Cambridge Dictionary) (from dictionary.com);
- to fall or cave in; crumble suddenly (from dictionary.com);
- to break down; come to nothing; fail (from dictionary.com).

I also checked the top 3 definitions in oxforddictionaries.com and dictionary.com and the are in agreement with the definitions from dictionary.cambridge.org

**Comment by BarbaraCzub** [comment]
Preliminary conclusions:
The terms 'disassembly' and/or 'retraction' may be appropriate to describe processes affecting the synaptic cytoskeleton. This would need to be specified in the definition.

Refs.:
https://docs.google.com/spreadsheets/d/1wHRDLAUjaPVlEMwnvU_uHEWzsfKiN2GNOfzEydvBtNI/edit?usp=sharing

**Comment by Pimmelorus** [comment]
Just to explain where the use of the term **disassembly** comes from. It is based on the GO pattern "assembly, maintenance, modification, disassembly" to describe the life-cycle of cellular structures. According to these broad classes any process that removes a synapse, should be placed in the **disassembly** category. The term **synaptic pruning** is a term used to remove redundant synapses which is most prominent during development. In that term the dictionary entry "to reduce something by removing things that are not necessary" does best describe the process since during development more synapses than needed are initially created and the synapses that are no longer needed are removed by 'synapse pruning'. In that sense pruning is removal/disassembly of synapses that are no longer necessary.

**retraction** is certainly wrong, since the synapse does not retract. The axon may do this, but the synapse is there or it is not.

**Comment by Pimmelorus** [comment]
>Based on the literature, which I've read, my understanding is that 'pruning' always involves phagocytic engulfment by microglia (e.g. PMIDs: 18083105, 21778362, 22632716, 29844190).

Redundant cellular components are either processed by the neurons themselves via autophagy (see PMID:29709573), via autophagy by astrocytes, or may involve microglia.

>This is why I originally suggested that the term 'synapse pruning' should be related in the ontology to 'phagocytosis, engulfment' as well as 'neuron remodeling' (a process which encompasses 'pruning' according to the GO definition).

 'neuron remodeling' is correct, 'phagocytosis, engulfment' I do not know whether this is correct for all instances of pruning.

>But then what should we do about papers like e.g. PMID: 12062020, where the authors do not mention 'pruning', but they use the term 'synaptic retraction'?

I suggest to correct their use of terminology. Neuronal processes retract, synapses do not.

>So perhaps 'pruning' should be categorised as a developmental process (as a child term of 'phagocytosis, engulfment' and 'neuron remodeling'), whereas 'disassembly' could remain where it is as a broader term?

Synaptic pruning is not always occurring in development, but also in the mature animal. I remain with my point that synapse pruning is a term that means that certain synapses are removed, whereas other remain. I think that removal is equivalent to disassembly. If this is a big issue for you, you may need to consult an expert in the field.

**Comment by BarbaraCzub** [comment]
Thanks, Pim, for your feedback and the PMID to this very recent synaptic pruning review. I'll take a look at the sections and cited research papers on neurons and astrocytes in addition to microglia to get a broader understanding.

**Comment by BarbaraCzub** [comment]
Hi @Pimmelorus, we discussed this issue in the Ontology Editors' Call today again. And we've decided that, based on your expert suggestions and based on evidence from literature, the terms 'synapse pruning' and 'synapse disassembly' should be synonymous. 

However, because 'synapse pruning' appears to be used in published research more frequently than 'synapse disassembly' the term 'synapse pruning' should be the primary GO term, whereas 'synapse disassembly' (as well as '...clearance', '...elimination', and '...removal') will be exact synonyms. 

@Pimmelorus or @ftwkoopmans, could you please let me know whether you are happy with this change in context of the SynGO annotation tool? (This term is in the synapse slim). Or should I keep 'synapse disassembly' as the syngo_official_label, like you previously requested for https://www.ebi.ac.uk/QuickGO/term/GO:0097471 (https://github.com/geneontology/synapse/issues/194).

cc 
@ukemi  
@RLovering

**Comment by BarbaraCzub** [comment]
To do:
- [ ]  Add exact synonyms of 'synapse disassembly' to GO term entry, specifically 'synapse/synaptic pruning', '... clearance', '...elimination', and '...removal'.
- [ ]  Make 'synapse pruning' the primary GO term name. Keep 'synapse disassembly' as an exact synonym.
- [ ]  Add the child term 'complement-dependent synapse pruning' (and exact synonyms: 'complement-dependent/mediated synapse/synaptic pruning/clearance/removal/elimination/disassembly').
- [ ]  Follow up on syngo_official_label.

**Comment by BarbaraCzub** [comment]
@Pimmelorus @ftwkoopmans the name of this GO term has now been changed from 'synapse disassembly' to 'synapse pruning', and 'synapse disassembly' has become an exact synonym. 

Would you like me to assign the syngo_official_label to its exact synonym 'synapse disassembly'? Or are you happy to have 'synapse pruning' displayed in your annotation tool?

Thanks,
Barbara

**Comment by Pimmelorus** [comment]
@BarbaraCzub 
Please make 'synapse disassembly' the syngo_official_label.

**Comment by BarbaraCzub** [comment]
Hi @Pimmelorus ok, thanks for confirming this, I'll make 'synapse disassembly' the syngo_official_label.
