### ISSUE TITLE
plant-based taxon constraints required GO:0090395

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16018]
plant cell papilla
https://www.ebi.ac.uk/QuickGO/term/GO:0090395

only in....

**Comment by ValWood** [comment]
Also
GO:0090691 formation of plant organ boundary
GO:0090698 post-embryonic plant morphogenesi
GO:0090627 plant epidermal cell differentiation
GO:0048760 plant parenchymal cell differentiation

**Comment by ValWood** [comment]
GO:0070505    pollen coat

**Comment by krchristie** [comment]
@cmungall - How would I know if the ticket you did in the plant-ontology:
Place taxon constraint at root of PO - https://github.com/Planteome/plant-ontology/pull/686
fixes this ticket?

I don't see any taxon constraints in the GO file on the couple terms I checked of those @ValWood has listed here. I have no idea how to check this.

**Comment by rachhuntley** [comment]
I have a similar problem seeing how this fixes https://github.com/geneontology/go-ontology/issues/15315

QuickGO shows taxon constraints (e.g. https://www.ebi.ac.uk/QuickGO/term/GO:0043667), but not any plant-specific ones. In the above linked term there is a cross-ontology relation to PO, so there may well be inherited taxon constraints here. Is it because the TCs are not applied by GO that we don't see them in the file?

**Comment by ukemi** [comment]
But the problem seems to be deeper than this. If we look at pollen wall (GO:0043667), it is a part of pollen. Pollen is a PO term (PO:0025281) that has inherited an anonymous class only_in_taxon some Viridiplantae. For class-class relations, this means that pollen wall should inherit the taxon restriction. Are we missing a property chain 'part of'-o-only_in_taxon -->only_in_taxon? I do not see that property chain.

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/RO_0002160 only in taxon

subPropertyOf
http://purl.obolibrary.org/obo/RO_0002162 in taxon

```
(part of o in taxon) subPropertyOf in taxon
(results in developmental progression of o in taxon) subPropertyOf in taxon
(has developmental contribution from o in taxon) subPropertyOf in taxon
(develops from part of o in taxon) subPropertyOf in taxon
(actively participates in o in taxon) subPropertyOf in taxon
(capable of o in taxon) subPropertyOf in taxon
(has prototype o in taxon) subPropertyOf in taxon
(expressed in o in taxon) subPropertyOf in taxon
(develops from o in taxon) subPropertyOf in taxon
(has part o in taxon) subPropertyOf in taxon
```

The subPropertyOf is potentially confusing, dates to before we were using OWL and encoding quantifiers in relation.

@ukemi do you want to rebuild po_import.owl - this should bring in the TC to the parent class

It's not easy to see inferred TCs in Protege. v5.5 *might* help with this, if not we can see if we want to dedicate resources to writing a plugin that would help (cc @balhoff)

**Comment by ValWood** [comment]
Stealing from @krchristie  assigned to @pgaudet

**Comment by ValWood** [comment]
summary GO:0090395 plant cell papilla 
GO:0090691 formation of plant organ boundary
GO:0090698 post-embryonic plant morphogenesis
GO:0090627 plant epidermal cell differentiation
GO:0048760 plant parenchymal cell differentiation
GO:0010313 phytochrome binding (5 EXP)
GO:0010597 green leaf volatile biosynthetic process
GO:0070505 pollen coat

**Comment by pgaudet** [comment]
https://github.com/Planteome/plant-ontology/pull/686
has been merged in August, and we still don't have the constraints implemented in GO. 

@cmungall Should I add them manually ?

**Comment by cmungall** [comment]
Not sure what you mean by not having them. Did someone remake po import?

**Comment by pgaudet** [comment]
I don't know. Don't they all get made when we update the imports ?

**Comment by cmungall** [comment]
They are dynamically inferred from PO, but only if there are GO axioms connecting to PO

So we have constraints for eg plant epidermal cell differentiation:

![image](https://user-images.githubusercontent.com/50745/47761729-c8540000-dc76-11e8-8a44-7b5a2affdfd9.png)


I haven't exhaustively checked them all, but for some that are missing:

post-embryonic plant morphogenesis : unaxiomatized, should connect to plant development

green leaf volatile biosynthetic process : add TC directly?

**Comment by pgaudet** [comment]
Hard-coded the taxon restriction. But I'd really like to see how this is suppose to work !
