### ISSUE TITLE
GO:0008420	CTD phosphatase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16016]
GO:0008420 | CTD phosphatase activity
Is defined
Catalysis of the reaction: phospho-(DNA-directed RNA polymerase) + H2O = (DNA-directed RNA polymerase) + phosphate.

but this is also used to refer to other  heptad repeat substrates such as  those in tef
Spt5 

If this is *really* only for pol I can you make it explicit like

RNA polymerase II carboxy-terminal domain kinase activity

Personally, I would prefer generic: i.e.

phosphorylation occurs on residues in the carboxy-terminal domain (CTD) repeats 
(+ present in transcription associated proteins)

since the same kinases and phosphatases phosphorylate   both CTD heptad repeat substrates

**Comment by ukemi** [comment]
The EC definition for the xref is very generic and the name is just 'protein serine/threonine phosphatase':
[a protein]-serine/threonine phosphate + H(2)O <=> [a protein]-serine/threonine + phosphate

@hdrabkin, what do you think? There is no literature reference for this. Should we relax the textual definition, remove the EC xref, or obsolete this term?

**Comment by ukemi** [comment]
It looks like most of the annotations are to the RNA polymerase flavor of this activity. Maybe just change the def?

**Comment by ukemi** [comment]
@ggeorghiou, can you check the mouse annotation to Ppm1m from PMID:14654243 that is from UniProt? I'm not sure it should be to CTD phosphatase activity.

**Comment by ggeorghiou** [comment]
@ukemi evidence is pretty vague to use CTD phosphatase activity. I've gone ahead and deleted the annotation since MGI has already annotated it to phosphoprotein phosphatase activity

**Comment by ValWood** [comment]
It's a useful term because it relates to the CTD code, and we have the equivalent kinase terms

although that is called
RNA polymerase II carboxy-terminal domain kinase activity (GO:0008353)

Useful review
https://www.sciencedirect.com/science/article/pii/S0168952512000467

**Comment by hdrabkin** [comment]
The 3 digit xref should be removed at the least

**Comment by ukemi** [comment]
So I think the course of action you are suggesting is to make the term name and definition more specific and we should remove the xref. Based on the annotations, I think this is ok. I will use your reference above as a ref for the definition, ok?

**Comment by ValWood** [comment]
OK, can you standardise both to 

RNA polymerase II CTD kinase activity
RNA polymerase II CTD phosphatase activity
(I think we can use CTD here, nobody spells it out...)

**Comment by krchristie** [comment]
I am in agreement with @ValWood that making the term name and definition more specific to the CTD heptapeptide repeat would be good. For the RNAP II CTD, there are a set of kinases and phosphatases that are very specific to the heptapeptide repeat. I'm not familiar with Spt5.

I also agree that it would be preferred to use CTD in the main name, though it might be worth making a synonym using the full words instead of the acronym. 

I wonder if it would be worth including the heptapeptide repeat phrase in the term names:
- RNA polymerase II CTD heptapeptide repeat kinase activity
- RNA polymerase II CTD heptapeptide repeat phosphatase activity
