### ISSUE TITLE
Def query recombinase activity (GO:0000150)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16037]
This doesn't seem right?

Catalysis of the identification and base-pairing of homologous sequences between single-stranded DNA and double-stranded DNA.

recombination isn't catalysing base pairing is it (that doesn't involve catalysis?) ? Isn't it catalysing the exchange reaction ?

(I spotted this because it doesn't map to an EC-type)

**Comment by ValWood** [comment]
@hdrabkin Does recombinase have an entry in Rhea?

**Comment by mah11** [comment]
There's some explanation in #3917 (note that the ontology currently has the GO:0009009 is_a GO:0000150 link that the older ticket says shouldn't be there ... and it contradicts the comments added then).

**Comment by hdrabkin** [comment]
I doubt RHEA has this. ; rhea is reactant- specific and the reactants must be in CHEBI;

**Comment by hdrabkin** [comment]
elh: Eurie Hong
No ref. 
REALLY early GO term (150). 

I found this short paragraph on the Nature Research site
Recombinases are enzymes that catalyse site-specific recombination events within DNA; for example, genetic recombination during meiosis in which recombination serves to generate new combinations of alleles on chromosomes. DNA recombination events involve DNA breakage, strand exchange between homologous segments and rejoining of the DNA by DNA ligases. Recombinases also function in recombinational DNA repair.

This sounds like a processy thing .
But:
From Wikis: 'catalyze directionally sensitive DNA exchange reactions'.

**Comment by ValWood** [comment]
This isn't urgent. Next time we are annotating a recombinase we will ask the author. Flagging as "low priority"

**Comment by hdrabkin** [comment]
Not many direct annotations in Amigo: 500-ish, of which about 30-ish are direct exps.

**Comment by ValWood** [comment]
Closing for now, someone can open a new ticket he the problem is identified.
