### ISSUE TITLE
taxon constriants required on protein binding terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16048]
As we step up our work with fungal annotation groups it would be useful to hide some of  the non-relevant gene product and protein family specific binding terms that are hanging around.

never in yeast
GO:0005040 decoy death receptor activity
GO:0044548 S100 protein binding  (24 EXP)
GO:0046332 SMAD binding (174 EXP)
GO:0019955 cytokine binding (293)
GO:0002039 p53 binding (93)
GO:0043236 lamin binding (24)
GO:0043236 laminin binding (64 EXP)
GO:0043560 insulin receptor substrate binding
GO:0043559 insulin binding
GO:0034189 very-low-density lipoprotein particle binding 
GO:0030492 hemoglobin binding
GO:0097108 hedgehog family protein binding
GO:0031423 hexon binding
GO:0019838 growth factor binding
GO:0001968 fibronectin binding
GO:0070097 delta-catenin binding

These, we could probably get rid of now. They have small numbers of annotations. The arguement for keeping origianlly was that you  may not know which family member referrred to, but these  are 1:1s?

GO:0046980 tapasin binding  (5 EXP)
GO:0002046 opsin binding (4 EXP)
GO:0001846 opsonin binding (19 EXP)
GO:0038100 nodal binding  (6) Gene product specific term (not family (family is TGF so member should be obvious)
GO:0030984 kininogen binding (14 EXP inc 6 C. albicans?)
GO:0034711 inhibin binding  (0 annotation, contradictory def: Interacting selectively and non-covalently with an inhibin monomer, any of the polypeptides that combine to form activin and inhibin dimers.
GO:0031720 haptoglobin binding (2 EXP) human only has one haptoglobin?
GO:0002162  dystroglycan binding (23 EXP, all but 5 have a with field) only one dystroglycan in human

This one is odd. How do you define an antigen?
GO:1990405 protein antigen binding  (14 EXP)  mixed annotations  ( anything can be an antigen?)

**Comment by ValWood** [comment]
GO:0071253 connexin binding
GO:0001848 complement binding
GO:0044730 bone sialoprotein binding
GO:0034185 apolipoprotein binding 
GO:0043532 angiostatin binding 
GO:0055100 adiponectin binding
GO:0017147 Wnt-protein binding 
GO:0045569 TRAIL binding
GO:0097371 MDM2/MDM4 family protein binding  
GO:0061675 RBL family protein binding  
GO:0089719 RHG protein domain binding   
GO:0097678 SOCS family protein binding   
GO:0097677 STAT family protein binding  
GO:0098769 TIMP family protein binding
GO:0030881 beta-2-microglobulin binding  
GO:0098770 FBXO family protein binding
GO:0045294 alpha-catenin binding 
GO:0008013  beta-catenin binding  
GO:0045295 gamma-catenin binding
GO:0046977 TAP binding

**Comment by ValWood** [comment]
Would it also be possible to group these under

protein domain specific binding
and
protein family binding

Looking through these it is usually obvious from the  term/name def when in one of these categories.

This would make it easier to locate the used terms like "protein binding, bridging" and other  protein binding terms representing functions. At the moment the list is long, and it's difficult.

(Note this isn't new it was agreed to do this at a GO meeting a couple of years ago)

**Comment by ValWood** [comment]
Just add  NCBITaxon:4751 ! Fungi  to all
I'm really not bothered about the other improvements if you aren't.

**Comment by krchristie** [comment]
I added the constraint `relationship: never_in_taxon NCBITaxon:4751 ! Fungi` to everything on your list except these two for the reason listed for each:
- GO:0043236 laminin binding - already had: 
`never_in_taxon NCBITaxon:4751 ! Fungi`
- GO:0019838 growth factor binding - already had: 
`never_in_taxon NCBITaxon_Union:0000023 {id="GOTAX:0001006"} ! Fungi or Bacteria or Archaea`


full stanzas:
[Term]
id: GO:0019838
name: growth factor binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with any growth factor, proteins or polypeptides that stimulate a cell or organism to grow or proliferate." [GOC:curators]
subset: goslim_chembl
synonym: "neurotrophin TRK receptor activity" RELATED []
is_a: GO:0005515 ! protein binding
relationship: never_in_taxon NCBITaxon_Union:0000023 {id="GOTAX:0001006"} ! Fungi or Bacteria or Archaea                

[Term]
id: GO:0043236
name: laminin binding
namespace: molecular_function
alt_id: GO:0043238
alt_id: GO:0043239
def: "Interacting selectively and non-covalently with laminins, glycoproteins that are major constituents of the basement membrane of cells." [GOC:ecd]
synonym: "laminin-2 binding" NARROW []
synonym: "laminin-4 binding" NARROW []
is_a: GO:0005515 ! protein binding
is_a: GO:0050840 ! extracellular matrix binding
relationship: never_in_taxon NCBITaxon:4751 ! Fungi

**Comment by ValWood** [comment]
weirdly laminin binding  taxon constraint does not  show in QuiCKGO

https://www.ebi.ac.uk/QuickGO/term/GO:0043236
and it makes it through to our curation tool.

Is there a problem with this (syntax or something?)

**Comment by krchristie** [comment]
There doesn't appear to be anything unusual about the syntax of the taxon constraint on this term. Maybe it would be worth checking if your tool and QuickGO limit which taxons they recognize.

I did see an inconsistency with how some but not all of the taxon constraint lines refer to GOTAX IDs which I reported here: https://github.com/geneontology/go-ontology/issues/16176

**Comment by cmungall** [comment]
Longer term, if we keep these binding terms, we should treat the substrate like any other ontology class and add the taxon constraints there. See my slides from the Barcelona meeting https://drive.google.com/drive/u/0/search?q=auto-deepening-of-protein-binding
