### ISSUE TITLE
animal  taxon contraints required

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16047]
- [x] GO:0072564    blood microparticle formation
- [x] GO:0097497    blood vessel endothelial cell delamination
- [x] GO:1990936	vascular smooth muscle cell dedifferentiation
- [x] GO:0010657      muscle cell apoptotic process
- [x] GO:1904019	epithelial cell apoptotic process
- [x] GO:0090136	epithelial cell-cell adhesion
- [x] GO:0002414	immunoglobulin transcytosis in epithelial cells
- [x] GO:0099622      cardiac muscle cell membrane repolarization
- [x] GO:0017145	stem cell division
- [x] GO:0048864	stem cell development
- [x] GO:0048863	stem cell differentiation
- [x] GO:0034117    erythrocyte aggregation
- [x] GO:0007159    leukocyte cell-cell adhesion
- [x] GO:0034117    erythrocyte aggregation

- [x] (note also inconsistent hyphenation for blood-brain)

GO:0038084	vascular endothelial growth factor signaling pathway
GO:0061772    drug transport across blood-nerve barrier
GO:1990379    lipid transport across blood brain barrier
GO:0060856    establishment of blood-brain barrier
GO:1990963    establishment of blood-retinal barrier
GO:0007159    leukocyte cell-cell adhesion
GO:1902217 erythrocyte apoptotic process
GO:1990377    organomineral extracellular matrix (seems to be for shells and eggs)
GO:0062023 collagen-containing extracellular matrix

obophenotype/cell-ontology#524
and
https://github.com/geneontology/go-ontology/issues/16449
- [x] GO:0071839	apoptotic process in bone marrow

**Comment by ValWood** [comment]
GO:1902217 erythrocyte apoptotic process

**Comment by ValWood** [comment]
GO:0030345    structural constituent of tooth enamel

**Comment by ValWood** [comment]
GO:0030280      structural constituent of epidermis
GO:0030281      structural constituent of cutaneous appendage

**Comment by ValWood** [comment]
GO:0008307	structural constituent of muscle
GO:0008316	structural constituent of vitelline membrane
GO:0016490	structural constituent of peritrophic membrane
GO:0019911	structural constituent of myelin sheath

**Comment by cmungall** [comment]
These should all be axiomatized using uberon

**Comment by ukemi** [comment]
Adding a bit more to the comment. I think if we make all of the structural constituent of x terms = structural molecule activity occurs_in some x, these should fall out through UBERON.

**Comment by ValWood** [comment]
GO:1990377    organomineral extracellular matrix (seems to be for shells and eggs)

**Comment by ValWood** [comment]
GO:0062023    collagen-containing extracellular matrix

**Comment by krchristie** [comment]
@cmungall & @ukemi - In what way would you like to proceed with axiomization via UBERON?

@ValWood - "Animal" is not a taxon. Do you have a specific constraint in mind? Below are some of the ones already used in GO. Does Metazoa seem like the appropriate level?


---- NCBITaxon:33208 ! Metazoa
----- NCBITaxon:6072 ! Eumetazoa
------ NCBITaxon:33213 ! Bilateria
------- NCBITaxon:33511 ! Deuterostomia
-------- NCBITaxon:7711 ! Chordata
--------- NCBITaxon:89593 ! Craniata <chordata>
---------- NCBITaxon:7742 ! Vertebrata <Metazoa>
----------- NCBITaxon:7776 ! Gnathostomata <vertebrate>

---------- NCBITaxon:40674 ! Mammalia
----------- NCBITaxon:32525 ! Theria <Mammalia> 
------------ NCBITaxon:9443 ! Primates
------------- NCBITaxon:9606 ! Homo sapiens
---------- NCBITaxon:8457 ! Sauropsida
----------- NCBITaxon:8782 ! Aves
---------- NCBITaxon:32443 ! Teleostei

-------- NCBITaxon:27896 ! Planariidae

------- NCBITaxon:33317 ! Protostomia
-------- NCBITaxon:6656 ! Arthropoda
--------- NCBITaxon:7147 ! Diptera
---------- NCBITaxon:50557 ! Insecta
----------- NCBITaxon:33392 ! Holometabola
------------ NCBITaxon:7203 ! Brachycera
-------- NCBITaxon:6231 ! Nematoda
--------- NCBITaxon:6237 ! Caenorhabditis

----- NCBITaxon:6073 ! Cnidaria

**Comment by cmungall** [comment]
yep, metazoa

TCs for gross structures in uberon are complete and cover Val's list. CL may be incomplete

add new ones here
https://github.com/obophenotype/cell-ontology/issues/new

some may be inherited (e.g epithelial cell part_of epithelium only_in eumetazoa), but others don't have a fixed structure so will need to be added

 - leukocyte, erythrocyte (I suggest broader: CL:0000988 ! hematopoietic cell)
 - stem cell
 - muscle cell

**Comment by krchristie** [comment]
@cmungall - I do not understand what I need to do for this ticket. 

I can easily add an only_in_taxon NCBITaxon:33208 ! Metazoa for all of these terms, but I do not know what you are suggesting with respect to axiomitization via UBERON. Please clarify, perhaps with a specific example for one term.

**Comment by ValWood** [comment]
Hi Chris,

We can steal this one from Karen.
I'm working with @pgaudet  this morning to close tickets
What needs to be done?

Val

**Comment by ValWood** [comment]
To close,

GO:0038084	vascular endothelial growth factor signaling pathway
GO:0061772 drug transport across blood-nerve barrier
GO:1990379 lipid transport across blood brain barrier
GO:0060856 establishment of blood-brain barrier
GO:1990963 establishment of blood-retinal barrier
GO:0007159 leukocyte cell-cell adhesion
GO:1902217 erythrocyte apoptotic process
GO:1990377 organomineral extracellular matrix (seems to be for shells and eggs)
GO:0062023 collagen-containing extracellular matrix

need logical defs

**Comment by pgaudet** [comment]
Added taxon contraints 'only in metazoa' except for 

 GO:1904019 epithelial cell apoptotic process
GO:0090136 epithelial cell-cell adhesion
GO:1990377 organomineral extracellular matrix (seems to be for shells and eggs)

added: 
relationship: never_in_taxon NCBITaxon:33090 ! Viridiplantae
relationship: never_in_taxon NCBITaxon_Union:0000023 ! Fungi or Bacteria or Archaea

**Comment by hattrill** [comment]
Could we discuss "GO:0048010 vascular endothelial growth factor receptor signaling pathway"?

In  flies we have a receptor named "PDGF- and VEGF-receptor related". We discussed whether this should represent a distinct pathway or whether it belonged with PDGFR- or VEGFR- activated pathways. Based on relatedness, the downstream pathway, how it is referred to in the literature, and advice from an expert, we class this as a VEGFR (/equivalent to). Although not the same in terms of vasculature, the definition does not describe the context or the ligand - it is based on the classification of the receptor, so we are comfortable with annotating this pathway to GO:0048010 for flies.

**Comment by hattrill** [comment]
The blood brain barrier in D.mel is equivalent to that of vertebrates. I would rather that the definition is revised to say "....circulating blood or the hemolymph system" than a taxon-restriction here. I'm not sure why it's needed.
https://www.ncbi.nlm.nih.gov/pubmed/26103549

**Comment by pgaudet** [comment]
Hi @hattrill 
I changed the taxon restriction for GO:0048010 as well as terms containing 'blood brain barrier' to Eumetazoa; does that work ? 

Which definition do you want me to change? 

Thanks, Pascale

**Comment by hattrill** [comment]
Taxon fix works for me @pgaudet. I am therefore ok with keeping the definitions as it is.

**Comment by cmungall** [comment]
You of course inherit BBB constraints from Uberon, which is already Eumetazoa minus Porifera.

We use the term hemolymphatic fluid as the grouping for true blood plus hemolymph. The term itself came from GO. We use Uberon to record in one place these terminological decisions, which we should use universally across GO

**Comment by cmungall** [comment]
Ping @tonysawfordebi for quickgo questions

yes, it would be useful to see inferences in Protege, @balhoff is thinking about this

**Comment by pgaudet** [comment]
@cmungall actually my question is: is there a way to see inferred taxon constraints, other than using QuickGO ?

**Comment by balhoff** [comment]
@pgaudet there is a nice way to check whether an 'only in taxon' would be redundant if added. In Protege, turn on the reasoner (ELK) and go to the DL Query tab. For the requested taxon constraint (e.g. Eukaryota) and GO term (e.g. 'CAM photosynthesis'), do a DL query for "Equivalent classes":

`'CAM photosynthesis' and 'in taxon' some Eukaryota`

Since this term already has the constraint 'Viridiplantae', you will see that this expression is equivalent to 'CAM photosynthesis' itself. So there is no need to add a taxon constraint to 'Eukaryota'.

On the other hand, if someone requested that this be restricted to 'Embryophyta', the equivalent class query for `'CAM photosynthesis' and 'in taxon' some Embryophyta` would have no results in the DL query panel. So adding that restriction to 'CAM photosynthesis' would be new information.

Does that make sense? Note that your DL query must use 'in taxon', not 'only in taxon'. Querying the classification for 'never in taxon' inference is more difficult, but for 'in taxon' this procedure should provide complete results.

**Comment by ukemi** [comment]
We should add this query to the editors' documentation in the taxon constraints section.

**Comment by pgaudet** [comment]
@balhoff 

Thanks for the tip, that's very useful. 

I guess here I was mentioning an implicit constraint, ie coming from an external ontology. Does that work the same way ? 

 @tonysawfordebi do you calculate taxon constraints that come from external vocabularies ? 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
We only consider taxon constraints that are defined in http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json

**Comment by balhoff** [comment]
@pgaudet yes this will work on the combined constraints coming from all the loaded ontologies. So if a reference to Uberon somewhere results in an inferred taxon constraint on a GO term, you will have the same sort of results using the DL query method.

**Comment by alexsign** [comment]
The large number of taxon constrains seems to vanish. Does anything get changed?

**Comment by tonysawfordebi** [comment]
Specifically, we seem to have lost all of the constraints in the attached file.

[deleted_taxon_constraints.xlsx](https://github.com/geneontology/go-ontology/files/2638995/deleted_taxon_constraints.xlsx)

**Comment by pgaudet** [comment]
@ukemi @goodb @cmungall 
I thought these changes did not affect the files produced. Otherwise we needed to give people some notification to change their scripts. 

To discuss today at the editors call. 

Pascale

**Comment by ukemi** [comment]
@balhoff

**Comment by ukemi** [comment]
@tonysawfordebi and @alexsign. Just to be certain, in which file are the restrictions missing?

**Comment by tonysawfordebi** [comment]
@ukemi As per https://github.com/geneontology/go-ontology/issues/16047#issuecomment-441248703 up there ^^^, we get all constraint information from http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json

**Comment by balhoff** [comment]
@alexsign @tonysawfordebi the taxon constraints are all now owl:imported into go-plus from `http://purl.obolibrary.org/obo/go/imports/go_taxon_constraints.owl`. Sorry, I missed your use case when thinking about downstream effects of this change. From the OWL perspective it's no different from before.

Perhaps instead of publishing the import, it would be better for us to merge the file into go-plus during release production.

**Comment by tonysawfordebi** [comment]
@balhoff We're still not seeing the imported constraints in http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json - when are they likely to find their way there?

**Comment by balhoff** [comment]
@tonysawfordebi it's waiting for a successful snapshot run here: https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/

@kltm is it possible to give an ETA on the next snapshot?

**Comment by kltm** [comment]
@balhoff While marked as "failing", the snapshots are actually successful for the parts that you are interested in--the ontologies should still have been released and files put in the appropriate location

**Comment by kltm** [comment]
@balhoff I take it back. There was a successful run on the 4th, but last night failed. Looking in to it now.

**Comment by tonysawfordebi** [comment]
Thanks @balhoff - our ontology update pipeline is no longer throwing any errors.
