### ISSUE TITLE
NTR: regulation terms for GO:0032782 bile acid secretion

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#16040]
Hello,

Can I please request all of the regulation terms for GO:0032782?

For annotation of PMID:22767443
Please add GO Refs:
GOC:rph
GOC:BHF
GOC:BHF_miRNA

thanks,
Rachael.

**Comment by pgaudet** [comment]
Hi @rachhuntley 
Again this is 'acts upstream of'; can you not use this in P2GO now ? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
So are we supposed to be using acts upstream of (or it's +/- children) instead of regulation now?
The documentation for acts upstream of says "The acts upstream of gene product to GO term relation is used when the experimental evidence is sufficient to determine the mechanism relating a gene product's activity (MF) to a biological process and that activity occurs before that biological process, is not an integral part of the process, **nor does it regulate the process**. "

The authors of this paper say:
"Here we test the proposal that miR-33 also modulates hepatic bile metabolism by decreasing the expression of specific sterol transporters in the canalicular membrane of hepatocytes.", 
which sounds like regulation by the miRNA to me.

I often create interaction networks for miRNAs and their targets and then overlay GO terms, specifically separating the regulation of a MF or BP from involvement in the process itself. If I start using this qualifier then when I make the networks using Cytoscape/BinGO, the regulation will be lost and it will appear as if the miRNA is part of the process, since these tools don't take account of these qualifiers.
Maybe I missed where this was discussed, but I'm not sure of the goal here.

**Comment by krchristie** [comment]
@pgaudet - Are you objecting to these regulation terms being made?

**Comment by pgaudet** [comment]
Hi @krchristie 

To be consistent with current practices we can create them. We can revisit when we finalize the guidelines for the GP2term relations. 

Thanks, Pascale
