### ISSUE TITLE
comment field GO:0003712

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16046]
does not resolve in quickgo 
https://www.ebi.ac.uk/QuickGO/term/GO:0003712

looks like this in canto:
![comment](https://user-images.githubusercontent.com/7359272/42537589-3e2923e2-848d-11e8-9e98-d4cbe0c76097.jpg)

**Comment by pgaudet** [comment]
Hi @tonysawfordebi 
Can QuickGO be fixed to support URLs in comments ? 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
I'll pass the request on to the developers.

**Comment by pgaudet** [comment]
Fixed. 

<img width="883" alt="image" src="https://user-images.githubusercontent.com/4782928/44682670-e3955b80-a9f8-11e8-8419-4bf3122ff121.png">
