### ISSUE TITLE
GO:1902217    erythrocyte apoptotic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16049]
this was in my  "taxon constraint required" list, but I thought it seemed odd so I split it out from the others.

Do erythrocyte's do "apoptosis"? I thought that apoptosis was defined by a set of characteristics that included "chromatin condensation", and "nuclear fragmentation".

If it's really OK, just add a suitable animal-based taxon constraint

**Comment by mah11** [comment]
avian erythrocytes have nuclei

**Comment by ValWood** [comment]
You know some very obscure stuff.

However, for this term, the paper used to create was http://europepmc.org/abstract/MED/14569084
for human.

Will wait until @RLovering  gets back to check the logic of using apoptosis (has no annotations)

**Comment by cmungall** [comment]
See this review https://www.nature.com/articles/4400953, cited in the above paper

_A semantic and hence delicate problem arises from the use of erythrocytes for the study of cell death or apoptosis. If we consider Ca2+ ionophore-induced RBC senescence as ‘apoptotic’, then the results reported here16,17 may be interpreted to mean that ‘apoptosis’ can occur in the absence of mitochondria, nuclei, and caspase activation. That apoptosis may occur in the absence of a nucleus (that is in freshly enucleated cells, so-called cytoplasts) or in the absence of caspase activation (that is in the presence of caspase-inhibitors or in Apaf-1 or caspase knock-out cells) has been reported in the past,33,34,35 and the true originality of the present articles16,17 would be to show death in the absence of mitochondria.36 However, in a way the erythrocyte must be considered as a post-apoptotic creature, in the sense that transient, presumably mitochondrion-triggered caspase activation10 has lead to the formation of an organelle-free mummy (just as ancient Egyptians removed organs from the corpse before mummification). Seen from this angle, it appears logical that the final implosion of RBC occurs via a non-apoptotic process which we might call erythroptosis._

_Irrespective of this semantic problem, the second death of erythrocytes is characterized by some features that are shared by apoptosis. Indeed, classical apoptosis of mammalian cells, in vitro erythrocyte senescence,16,17 and artifactual induction of cell death in monocellular organisms37,38 is invariably accompanied by phosphatidylserine exposure and microvesiculation as well as nuclear condensation (when a nucleus is present). Again, two interpretations of this parallelism are possible. Either it hints at the existence of a common biochemical ‘program’ that has been conserved throughout evolution, or it simply means that an increase in entropy leading to disintegration of a cell or a cell-derived vesicle gives rise to a common phenomology._

Cool!

**Comment by addiehl** [comment]
There's even a name for this apoptosis-like programmed cell death in erythrocytes: "eryptosis" [PMID:16910766].

However, it seems that even PCD in nucleated chicken erythrocytes may not be cascade-driven, and thus perhaps not classical apoptosis [PMID:9718364].  This is a 1998 study, however, and perhaps there is newer work on this area.

**Comment by ukemi** [comment]
It seems that there is normal apoptosis in nucleated erythrocytes. See PMID:11113889 and the authors of the paper that is cited above indicate this.

**Comment by ValWood** [comment]
OK I'll just move this to the  tax constraint list.
