### ISSUE TITLE
Obsolete 'transcription factor activity, protein binding' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16053]
This ticket replaces #15798, which is now quite out of date. 

Following up on yesterday's annotation call, I propose to obsolete: 

-  [x]   GO:0000988  transcription factor activity, protein binding
-  [x]  GO:0000989  transcription factor activity, transcription factor binding
-  [x]   GO:0000990  transcription factor activity, core RNA polymerase binding
-  [x]   GO:0000991  'transcription factor activity, core RNA polymerase II binding
-  [x]   GO:0001076  transcription factor activity, RNA polymerase II transcription factor binding
-  [x]   GO:0001129  RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly
-  [x]   GO:0001132  RNA polymerase II transcription factor activity, TBP-class protein binding
-  [x]   GO:0001190  transcriptional activator activity, RNA polymerase II transcription factor binding
-  [x]   GO:0001191  transcriptional repressor activity, RNA polymerase II transcription factor binding
-  [x]  GO:0098811  transcriptional repressor activity, RNA polymerase II activating transcription factor binding

The reason for obsoletion is that these concepts are partly covered by other concepts in the ontology and usage has been inconsistent.

Annotations and potential replacements are here: https://docs.google.com/spreadsheets/d/1jwgpZF3paxNOHvEHQ4v_uxOFb3FjQUOnxSJpswIzyMI/edit#gid=0

Annotation guidelines are here: https://goo.gl/dsvB18

Thanks, Pascale

**Comment by bmeldal** [comment]
What about 
GO:0008134 transcription factor binding and children?
How is the former different to GO:0000989 transcription factor activity, transcription factor binding - to be obsoleted?
Shouldn't both go then?
Birgit

**Comment by pgaudet** [comment]
Hi @bmeldal 
> What about GO:0008134 transcription factor binding and children?
I think GO:0008134 transcription factor binding will stay - this is now a 'protein binding' question, not a transcription factor question. 

>How is the former different to GO:0000989 transcription factor activity, transcription factor binding - to be obsoleted? 
I also thought these were the same, this is why I had first propose to merge, but the initial annotation reviews suggested that this is not how people had used the term, so it seems cleaner to obsolete. Also given that there are relatively few annotations, so it's worth reviewing the annotations. 

What do you think ? 

Pascale

**Comment by bmeldal** [comment]
Is there a different ticket for obsoletion of GO:0008134 that I have missed as it's not on the above list? Nor is it a child of the listed terms either as far as I can see but the QuickGO basket is broken today so can't compare easily.

I would obsolete the GO:0008134 branch, too, and replace annotations with GO:0140110 transcription regulator activity or children.

Birgit

**Comment by pgaudet** [comment]
@bmeldal can you re-read my previous response RE GO:0008134? (I edited the format)

**Comment by bmeldal** [comment]
Oh, I think I see the difference:

>GO:0008134 transcription factor binding

applies to any GP that binds to a TF even if it's not a TF itself (maybe a repressor)? Seems a bit of a bucket term but I guess it's got it's uses.

So, if my complex is a TF (which those with these annotations all are), then use GO:0140110 transcription regulator activity or children?

**Comment by pgaudet** [comment]
> GO:0008134 transcription factor binding
> applies to any GP that binds to a TF even if it's not a TF itself (maybe a repressor)? Seems a bit of a bucket term but I guess it's got it's uses.

Right. The ticket relevant to the binding aspect is #14915; can you please comment there ? 

Cheers, Pascale

**Comment by bmeldal** [comment]
Great, got it!
All complexes changed. All TFs with to-be-obsoleted terms now have annotations to GO:0140110 transcription regulator activity or children. However, as the term is new I doubt all TFs in the Complex Portal are annotated with this branch... I'd have to do some archaeology to fix that!

I have a few complexes that are annotated to GO:0008134 transcription factor binding but they are chromatin remodellers (histone acetylases etc) that also bind TFs.

#14915 confuses me!

**Comment by RLovering** [comment]
Hi Pascale
sorry I have been away, was a decision made about the MF term for proteins that regulate the activity of a DNA binding TF activity through protein binding? I don't really want to edit these annotations until an appropriate child of GO:0140110 transcription regulator activity is available. We agreed that GO:0003712   transcription coregulator activity is not the correct term (now).
Thanks
Ruth

**Comment by RLovering** [comment]
or from your comments above maybe we just use the child terms of 
GO:0003712 transcription coregulator activity
GO:0003713    transcription coactivator activity
GO:0003714    transcription corepressor activity
Help appreciated

Thanks
Ruth

**Comment by ValWood** [comment]
I think we do need the different types here. I think we plan to discuss.....but not sure when...

**Comment by RLovering** [comment]
Hi Pascale
please confirm if these terms  
GO:0003712 transcription coregulator activity
GO:0003713 transcription coactivator activity
GO:0003714 transcription corepressor activity 

can be used for proteins that do not modify DNA/histones and are not a part of the mediator eg by ablation of transcriptional activator function: repressors targeting transcriptional activators and co-activators, resulting in their degradation, nuclear export, or inhibiting their ability to bind DNA (or inhibiting a TF activity in some way).

Thanks

Ruth

**Comment by ValWood** [comment]
Hi Ruth,

I think Pascale is still away.
I believe this is the right place for such annotations, but I think the plan is to add new classes  to be more specific about the different activities they perform (Or maybe move existing terms which meant the same thing to here, and rename). I plan to  wait to  move things from elsewhere   to here in order to get the  final specificity.

**Comment by pgaudet** [comment]
Annotations to GO:0000991 are here: https://docs.google.com/spreadsheets/d/16CWA5XBcBHVTaKutTcKtWLmqTeaU9x4Pt-TNBNxpxqQ/edit#gid=0
(note: this includes all non-EXP). Terms have already been merged but some people might want to look at their annotations to these terms. 

Annotations exist for 
flybase @hattrill 
pombase @ValWood 
SGD @srengel 

Pascale

**Comment by pgaudet** [comment]
Yeah it's old - we probably did the different annotations via other ticket - that spreadsheet was not attached to any ticket. I also think it's fine; no action needed anymore.
