### ISSUE TITLE
Move 'transcription factor recruiting activity' back under 'transcription regulator activity' (and DO NOT connect to preinitiation complex assembly)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16057]
Following up on #15577 , in which I moved ‘GO:0001134 transcription factor recruiting activity' under ’ GO:0008134 transcription factor binding'

In the previous ticket @ValWood and @krchristie suggested that we 
>  look into defining MF protein recruitment more formally and linking it to BP "protein localization"

> There are lots of chromatin associated factors where the primary function is "recruitment" and the annotations for these are "all over the shop"

> Can we talk about recruitment with the treancription experts on a future call?

**Comment by pgaudet** [comment]
Hi @ValWood 
Speaking with Colin, he thinks that PIC assembly (which is already a parent for 'RNA polymerase II complex recruiting activity') reflects the process better than localization. Does assembly work for you ? I'll check that this parent is in all the 'recruiting' terms. 

Thanks, Pascale

**Comment by ValWood** [comment]
How does he feel about my previous suggestion that we call these  "recruitment"?

Recruitment sees to be what biologists use, and would be  part of both "assembly and localization"

This would also be much clearer to curators (assays are often for localization dependencies).

We would also need a "specific binding activity" to describe  recruitment ( the MF), but it would be much more consistent to describe in this way  for all "binding in order to recruit component x to chromatin" , across the board (in transcription, but also in for example 'kinetochore assembly'  and other  recruitment type processes (basically some modification event allows  some other component to bind (localize) and this results in assembly of the complex

**Comment by ValWood** [comment]
we even have compound terms to capture this (localization and assembly), like

protein localization to kinetochore involved in kinetochore assembly

this would probably  be better as 
MF protein recruitment part of  BP kinetochore assembly


or various
protein localization to chromosome, centromeric region
which would also probably fit
MF protein recruitment part of  BP kinetochore assembly

Whatever we use it should be a more general approach...

**Comment by pgaudet** [comment]
@ValWood The reason for favoring 'assembly' over 'localization' is that the PIC complex is temporary; localization would be to a stable structure like the plasma membrane. Does that make sense?

**Comment by ValWood** [comment]
Just for the record, I now totally agree with  Colin's proposal.

**Comment by ValWood** [comment]
GO:0001135 RNA polymerase II transcription regulator recruiting activity
under
GO:0001134 transcription regulator recruiting activity
is OK.

I don't think all 
GO:0001135 RNA polymerase II transcription regulator recruiting activity
is preiniitation complex assembly though?

**Comment by pgaudet** [comment]
Then I misunderstood what you were asking  in  #15577
Can you please re-state ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think I said that all recruitment  could be considered *assembly*  (of something) but I'm not sure that all recruitment is "PIC assembly".
Some "recruiters" recruit other DNA binding gene-specific transcription factors for example.

This is the only example I can think off the top of my head...
Here teb1 binds DNA and recruits the DNA binding TF ams2

![teb1](https://user-images.githubusercontent.com/7359272/43731975-2116a4d4-99a8-11e8-9558-d8c5dc506929.jpg)

I wouldn't  annotate this to PIC assembly? I would annotate  the  general TFs to PIC assembly.....

**Comment by pgaudet** [comment]
So, if I understand correctly, this should be captured at annotation, not in the ontology?

**Comment by pgaudet** [comment]
@ValWood you would like just 'protein-containing complex assembly', or something like that; is that what you mean ?

**Comment by ValWood** [comment]
No, I still want it to be a "transcription regulator-type recruiter".

Can we chat about this on the call? I don't think these  are really  involved in PIC assembly. I assumed that  they connected to an already assembled PIC?  We can ask...

**Comment by pgaudet** [comment]
It's on the agenda for Thursday.

**Comment by pgaudet** [comment]
At the transcription call we decided NOT to connect PIC assembly.
