### ISSUE TITLE
cell fate committment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16089]
needs taxon restriction, never in yeast
https://www.pombase.org/term_genes/GO:0045165
(at least fitting this definition, its defined as a multicellular organismal process)

This seems to come from the parentage to

genetic imprinting at mating-type locus
gene conversion at mating-type locus
donor selection etc

@Antonialock   (FYI)

**Comment by ValWood** [comment]
So actually it's a TPV for lots of it's children terms. Taxon restriction won't help yet as we would lose valid annotations.

**Comment by ukemi** [comment]
I think this would be a mistake. Years ago when learning about cell differentiation, two basic model systems I learned about were yeast mating type and phase variation in bacteria. Unless this is very outdated, I think it would still be useful.

**Comment by vanaukenk** [comment]
@ValWood @ukemi 
I think the distinction between what happens in yeast and what happens during multicellular organism development may be worth re-visiting in the ontology.  There may be some similar molecular control mechanisms at work, but in yeast is commitment more a case of cell cycle regulation than a step on the way to terminal cell differentiation?

**Comment by ValWood** [comment]
I have a problem with the definition.
"capacity to differentiate into particular kinds of cells. 
"
I think we could  go with the parent:
"cell differentiation"

but also the current definition would not really fit:
The process in which relatively unspecialized cells, e.g. embryonic or regenerative cells, acquire specialized structural and/or functional features that characterize the cells, tissues, or organs of the mature organism or some other relatively stable phase of the organism's life history. Differentiation includes the processes involved in commitment of a cell to a specific fate and its subsequent development to the mature state.

It is true yeast are sold as a model for differentiation. 

They could be OK with much broader definitions ......

@mah11  @Antonialock

**Comment by vanaukenk** [comment]
@ValWood 
I had also wondered if 'cell differentiation' might be a better parent, but agree that the current definition of this term doesn't really fit.  I don't know if we want to broaden the 'cell differentiation' definition, though, or whether it would be better to split the mating-type switching terms out into their own type of 'developmental process involved in reproduction'.  This review had an interesting perspective:
http://www.genetics.org/content/genetics/206/1/9.full.pdf

**Comment by vanaukenk** [comment]
@ValWood 
Any additional thoughts on this one?

**Comment by ValWood** [comment]
I think broadening the def should work. Will chat to @Antonialock  and @mah11  about this next week, probably Thursday (or if they have a suggestion they can add here before that)

**Comment by ValWood** [comment]
@Antonialock  do you agree with this change?

**Comment by Antonialock** [comment]
Hmm, I am not sure & I don't have strong feelings at the moment (I'm sure I  could be convinced either way). 

"The commitment of cells to specific cell fates " might fit with the signaling pathway of making and sensing pheromones & committing to sexual reproduction - where the cell eventually shuffles up its genome with another individual (a terminal fate for the two original genomes?)

**Comment by ValWood** [comment]
I can just close this one. Logical defs will sort any problems in the future hopefully.
