### ISSUE TITLE
Catalytic activities that are missing 'enzyme type' parent

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16083]
Hi @hdrabkin 

For the MF refactoring @thomaspd and I noticed a number of terms that are directly under GO:0003824 catalytic activity and that could perhaps be integrated under one of the terms that represents the different types of enzymes. 

Those are: 
 - [ ]  GO:0032451 demethylase activity: because there are dozens of different demethylases that have very disparate substrates, this one is tricky (ie, ec classes 1.5, 1.14, 2.1, 3.3);  can't just go with EC:1

 - [x]  GO:0034061 DNA polymerase activity  >>. EC:2.7.7 nucleotidyltransferase activity ;
 already present as parent GO:0016779
                 also has a ' catalytic activity acting on DNA'; not an ec class

 - [x]  GO:0003964 RNA-directed DNA polymerase activity
         Child of above; no cat activity parent

 - [x]  GO:0004133 glycogen debranching enzyme activity >>  EC: 3.2.1.
 - [ ]  GO:0061783 peptidoglycan muralytic activity (removal of a muramyl group from a compound.)
           GO Def "A catalytic activity that contributes to the degradation of peptidoglycan." 
            aka 'Muramidase' 
             So maybe EC 3.2.1: Glycosidases, i.e. enzymes hydrolysing O- and S-glycosyl compounds

 - [x]  GO:1990055 phenylacetaldehyde synthase activity; EC:4.1.1, because 
      it is  4.1.1.109    Phenylacetaldehyde synthase.   Done

 - [x]  GO:0046905 phytoene synthase activity   EC: 2.5.1; done
 - [x]  GO:0008987 quinolinate synthetase A activity EC 2.5.1 because this is related to 2.5.1.72 Done.

 - [x]  GO:0010280 UDP-L-rhamnose synthase activity; no EC assigned; working (Metacyc id not helpful)   However, since rhamnose is a 6 carbon sugar, I think 4.1 EC 2.4.1: Hexosyltransferases might suffice

 - [x]  GO:0046572 versicolorin B synthase activity Thisis  EC Number: 4.2.1.143, so 4.2.1 parent; done

Can they be put under one of these: 
GO:0009975 cyclase activity
GO:0016787 hydrolase activity
GO:0016853 isomerase activity
GO:0016874 ligase activity
GO:0016829 lyase activity
GO:0016491 oxidoreductase activity
GO:0016740 transferase activity

Thanks, Pascale

**Comment by hdrabkin** [comment]
I will edit in line above

**Comment by ValWood** [comment]
I was looking at enzymes which do not map to EC classes the other day.

I reported this one.
I looked into the demethylase one. This one can't be resolved because demethylases can work via  oxireductase or hydroalse mechanism.

**Comment by ValWood** [comment]
Oh you say that in the ticket :)

For the synthases, if they are used to represent "compound" activities,  it would be better to remove them and represent only in process. We have discussed this before but I don't remember the outcome. It  does result in lots of annotation consistency though, so it would be better if "only one way to annotate".

@ukemi  or @deustp01  may remember previous discussions. Maybe they never concluded?

**Comment by hdrabkin** [comment]
Can you give me an example?

**Comment by ValWood** [comment]
I was  thinking of fatty acid synthase 
or  ferrichrome synthetase and other such like. But maybe the ones above are not this type, or they fit neatly  under one EC....

**Comment by hdrabkin** [comment]
GO:0061783 peptidoglycan muralytic activity (removal of a muramyl group from a compound.)
           GO Def "A catalytic activity that contributes to the degradation of peptidoglycan." 
     this def sounds like a process? It's one of several enzymes that degrade peptidoglycan

A enzyme that has muralytic activity would be a muramidase, which is a type of 
           EC 3.2.1: Glycosidases, i.e. enzymes hydrolysing O- and S-glycosyl compounds
    The def really needs work to include this, ie catalysis hydrolysis of 1,4-beta-linkages between N-acetylmuramic acid and N-acetyl-D-glucosamine residues in peptidoglycan
           Lysozyme already has this def; 
So maybe merge GO:0061783 into GO:0003796 lysozyme activity, which already has ec mapping.

?

**Comment by pgaudet** [comment]
- []  GO:0004133 glycogen debranching enzyme activity >> EC: 3.2.1.
-> moved under 'hydrolase activity'

 - []  GO:0010280 UDP-L-rhamnose synthase activity
-> moved under 'transferase activity'

We did all we can for this ticket ! 

Thanks @hdrabkin @ValWood

**Comment by deustp01** [comment]
**Glycogen debranching enzyme** is actually a [**transferase**, EC 2.4.1.25](https://www.brenda-enzymes.org/enzyme.php?ecno=2.4.1.25). The steps in glycogen catabolism are, first, a phosphorolysis reaction that removed individual glucose residues from the end of a linear polyglucose until only four are left. Then debranching enzyme transfers a three-residue oligosaccharide to the end of another branch, and, finally, a [hydrolase (EC 3.2.1.33)](https://www.brenda-enzymes.org/enzyme.php?ecno=3.2.1.33) cleaves the 1,6 linkage attaching the first residue of the branch to the rest of the glycogen branched polymer.

The confusing part is that in E. coli and some bacteria, these two activities are expressed by two different gene products while in mammals, yeasts, and some other bacteria (phylogeny from [Wikipedia](https://en.wikipedia.org/wiki/Glycogen_debranching_enzyme)), they are expressed by two separate domains of a single gene product, [AGL in humans](https://www.uniprot.org/uniprot/P35573). But it's still two distinct activities with different EC numbers and different GO molecular function terms. [PMID:11375985](https://www.ncbi.nlm.nih.gov/pubmed/11375985) describes targeted mutagenesis of a yeast enzyme to define and resolve the two catalytic sites.

**Comment by pgaudet** [comment]
Thanks @deustp01 

I should remove this assertion. 
'glycogen debranching enzyme activity' has 3 children in GO: 

- GO:0004134 4-alpha-glucanotransferase activity EC 2.4.1.25 that you describe
- GO:0004135 amylo-alpha-1,6-glucosidase activity EC 3.2.1.33
 -GO:0019156 isoamylase activity EC 3.2.1.68

Some enzymes annotated to 'glycogen debranching enzyme activity'
are bifunctional, see amigo.geneontology.org/amigo/gene_product/MGI:MGI:1924809

I think the safest is to obsolete 'glycogen debranching enzyme activity', recommend annotation to one of the children, and to the BP. 

Thoughts @deustp01  @hdrabkin ? 

Thanks, Pascale

**Comment by deustp01** [comment]
Obsolete? Or, given all the history and ambiguity (to remove a four-residue branch completely, both transferase and hydrolase activities are needed), maybe keep 'glycogen debranching activity' as a grouping term with a strong recommendation not to use it for annotation, but to use the transferase or glucosidase child instead? @hdrabkin ? @ukemi ?

**Comment by hdrabkin** [comment]
I would be more comfortable with @deustp01 's suggestion

**Comment by pgaudet** [comment]
We only have 3 enzymes that are directly under 'catalytic activity: 

<img width="378" alt="image" src="https://user-images.githubusercontent.com/4782928/54206867-700cf480-44d9-11e9-800a-0dfff3ecfcb4.png">


Demethylase is because there are many different mechanisms, but at least the reaction is always to remove a methyl group. 

'glycogen debranching enzyme activity' and 'peptidoglycan muralytic activity' are different in that they group many functions to accomplish what seems to be a process. (see also @hdrabkin's comment from July 17th)

**Comment by deustp01** [comment]
GO consistency matters too, and here it looks like a strong argument for getting rid of 'glycogen debranching enzyme activity'. Actually, that might also be an argument for breaking up demethylase activity as well, into one child for each mechanism. Where EC does cleanly classify enzyme activities by reaction mechanism, that classification is worth following for molecular function. Also, we have process terms available (or could make them) to group all the ways of removing a methyl group or all the steps of removing a glycogen branch. (Pretty much repeating @hdrabkin 's comment from July 17th)

**Comment by ValWood** [comment]
...but if we are hoping to remove these "function" terms from the process ontology in the medium/long term (methylation, phosphorylation etc), then maybe for this case the grouping term is better under catalytic activity in function? It could be a do not annotate term, although do we always know the mechanism anyway.

It would not be good if you knew that something was a methylase but you did not know the mechanism, so you could only assign process term? (I never use MF in BP terms ...)

**Comment by deustp01** [comment]
But we should group functions based on shared molecular mechanistic detail; different molecular mechanisms that yield the same outcome, as well as successive steps to an outcome seem like the sorts of things that should be grouped with process terms.

**Comment by ValWood** [comment]
That ship sailed a recently though....

We now have  transcription regulator  activity, translation factor activity, general transcription iniitation factor activity, etc...lots of non-mechanistic (or even  true function) groupings.

**Comment by pgaudet** [comment]
> ..but if we are hoping to remove these "function" terms from the process ontology in the medium/long term (methylation, phosphorylation etc), then maybe for this case the grouping term is better under catalytic activity in function? 

Right - but the other axis of classification that we did with @thomaspd was to do with the type of substrate (we have 
- 'catalytic activity, acting on a protein'
- 'catalytic activity, acting on DNA'
- 'catalytic activity, acting on RNA'
we wanted to add some more classes, including 'acting on metabolite' and possibly 'acting on polysaccharide' 

but the  'glycogen debranching enzyme activity' and 'peptidoglycan muralytic activity' branches are really reflecting a process, as far as I can tell; I think it's quite different from phosphorylation. 

Pascale

**Comment by ukemi** [comment]
We also now have a substrate axis of differentiation.

**Comment by ValWood** [comment]
I have methyltransferases (5)  in "conserved unknowns" where all we know is that they are methyltransferases. I  don't know anything about the substrates (although I predict that some are ancient  tRNA methyltransferases).

I would like to continue to annotate to MF methytransferase, and not to "methylation"

**Comment by pgaudet** [comment]
It's OK if methyltransferases stay. The idea was to try to group things as much as possible - if this is the maximum, it's OK. 

I am not sure the grouping terms are needed for 'glycogen debranching enzyme activity' and 'peptidoglycan muralytic activity' but if people feel they are needed they can also stay.

**Comment by ValWood** [comment]
based on Peters comments do we really need
 'glycogen debranching enzyme activity'?
in fact the children of this term don't even appear to be glycogen specific.

peptidoglycan muralytic activity also seems odd and has no direct annotations.

I agree they aren't needed

**Comment by ValWood** [comment]
What is the action here?
at one point in the ticket  it says

"We did all we can for this ticket !"

than it goes into potential
obsoletion of  'glycogen debranching enzyme activity'?

If this is still an action should we put it in a new ticket so that nobody has to read all of this?

Please summarize action @hdrabkin

**Comment by pgaudet** [comment]
sure lets close
