### ISSUE TITLE
Parentage of perisynaptic extracellular matrix

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#16087]
perisynaptic extracellular matrix GO:0098966 currently has two is_a parents:
is_a extracellular matrix component
is_a collagen-containing extracellular matrix
but I don't think it can have both of these parents. As it's describing an ECM in a particular region, I think the relation to extracellular matrix component should be removed.

It's definition is "The portion of the extracellular matrix that lies within the perisynaptic space."

**Comment by ukemi** [comment]
We looked at this in Protege and although it is odd, it seems correct.
