### ISSUE TITLE
copper delivery

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16084]
the term for this is

GO:0015680    intracellular copper ion transport
intracellular copper delivery | exact

but I don't think this is transport, it's  just insertion?

see
 Cerqua C, Morbidoni V, Desbats MA, Doimo M, Frasson C, Sacconi S, Baldoin MC, Sartori G, Basso G, Salviati L, Trevisson E. | Related Articles

 COX16 is required for assembly of cytochrome c oxidase in human cells and is involved in copper delivery to COX2.
 Biochim Biophys Acta. 2018 Jan 18;. [Epub ahead of print]
 PMID: 29355485

**Comment by krchristie** [comment]
@ValWood - this term is used for experimental annotations for several genes, some of which look like they  match the definition, e.g. FET4, CTR2. Therefore, I think that this term needs to continue to be what it is.

| Gene/product | Gene/product name | Annotation extension | Contributor Organism | Evidence |
| --- | --- | --- | --- | --- |	
| COX17 | Copper metallochaperone that transfers copper to Sco1p and Cox11p | SGD | Saccharomyces cerevisiae S288C | IDA |
| COX17 | Copper metallochaperone that transfers copper to Sco1p and Cox11p | SGD | Saccharomyces cerevisiae S288C | IMP |
| FET4 | Low-affinity Fe(II) transporter of the plasma membrane | SGD | Saccharomyces cerevisiae S288C | IMP |
| CTR2 | Low-affinity copper transporter of the vacuolar membrane | SGD | Saccharomyces cerevisiae S288C | IMP |
| Atox1 | antioxidant 1 copper chaperone | RGD | Rattus norvegicus | IMP  |
| CCS1 | Copper chaperone for superoxide dismutase Sod1p | SGD | Saccharomyces cerevisiae S288C | IMP |
| CCS | Copper chaperone for superoxide dismutase | PINC | Homo sapiens TAS |
| COPT5 | AT5G20650 | TAIR | Arabidopsis thaliana | IMP  |

I took a quick look at the paper you mention, but it is not clear to me what COX16 is doing. 

If you'd like to propose a new term specifically for 'copper delivery', please propose a new term with all the appropriate details:

name: [term name]
namespace: BP
def: "definition text "[definition dbxrefs, e.g. GOC:abc, PMID:12345678]
is_a: [GO term]
relationship: [any other appropriate relationships]

**Comment by krchristie** [comment]
I'm fine with letting @pgaudet take care of this if she wants, but considering that longstanding GO practice is that the meaning of the term is defined by the definition, currently:
`Def: The directed movement of copper (Cu) ions within a cell.`

I think that keeping this term with this existing meaning and removing the synonym, IF needed, would be more consistent with our stated practice.

**Comment by ValWood** [comment]
Yes but it's in the wrong place in the ontology in this case.....

**Comment by ValWood** [comment]
...in addition most of the usage is for the "chaperone", not the transmembrane transporter.

Probably obsoletion is the only way to deal with it in this case.

**Comment by pgaudet** [comment]
see also https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3875331/

**Comment by pgaudet** [comment]
Hello, 

Looking at these more closely, it seems like the odd balls in the annotations are FET4 and CTR2. Here's what I did: 
- Changed parent to 'protein maturation' (as an aside: but is this really OK under 'gene expression'?)
- also changed definitions of the corresponding MF to "Directly binding to and delivering copper ions to a target protein." (also for the parent 'metallochaperone' and sibling 'iron chaperone')

- There is no corresponding iron delivery term, however there is 'protein maturation by iron-sulfur cluster transfer', so we could rename 'intracellular copper ion delivery' to 'protein maturation by copper ion transfer'? 

If that works I will implement the changes and ask an annotation review for FET4 and CTR2.

Thanks, Pascale

**Comment by ValWood** [comment]
I agree with these proposed changes. @Antonialock  could you glance over and see if this looks OK? (Antonia has been working on our iron-sulfur pathway and so should spot any problems with these).

Re the protein maturation under gene expression, the rationale is that:
gene expression def:
The process in which a gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form.
 
I think it is correct.

**Comment by pgaudet** [comment]
Hi @Antonialock, 

This ticket is only about the copper chaperone ("intracellular copper ion delivery" - what I proposed to call "protein maturation by copper ion transfer"). I think that 2 and 4 are the same thing (or I dont know if they can really be distinguished): I think proteins carry copper in the intracellular environment and the copper can be transferred to specific target proteins

(I dont see how 'import into cell' and 'homeostatic control ' are related). 

Thanks, Pascale

**Comment by pgaudet** [comment]
Looking at the ontology structure, I went ahead and renamed 'intracellular copper ion delivery' to ' protein maturation by copper ion transfer' 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/4782928/45287608-f758bb80-b4e8-11e8-8323-875694df4168.png">


Pascale
