### ISSUE TITLE
All gene product specific  secretion related terms, block  for direct annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16103]
gene product specific, no annotations, suggest obsoletion?

GO:0038055    BMP secretion

GO:0110010    basolateral protein secretion  
(3 annotation FlyBase) suggest   
"secretion" occurs_at GO:0097575? or similar
@hattrill ?

**Comment by RLovering** [comment]
This is not gene product specific, there are many paralogs in mammals

**Comment by ValWood** [comment]
...but since it has no annotation isn't this a case where you would know which molecule was being secreted. Anyway BMP secretion isn't really a process, the secreted molecule is the target of the secretion process.

I don't really understand how this term got in? Unless it has its own specific secretory pathway?

It's like  having a term for say, say  "BMP glycosylation" isn't it?
I don't get it?

**Comment by ValWood** [comment]
OK I'll close this one, but it sounds as though you are referring to the signalling component  rather than the actual secretory pathway, which is proposed to be highly conserved from yeast to man.

**Comment by ValWood** [comment]
In this case should
GO:0038055 BMP secretion
be blocked dor direct annotations?

**Comment by RLovering** [comment]
probably ;)

**Comment by ValWood** [comment]
Action, gene product specific secretion terms. Block all for direct annotation.
(regulation terms will be avaiable).

Is that OK?

**Comment by RLovering** [comment]
Hi Val
I think this is in line with a recent GOC meeting discussion (about biosynthesis I think), as you say the proteins involved in the secretory process itself are not specific for the secreted product. This does mean that we will be saying that 'regulation of secretion' ends with the 'cargo' being targeted to a secretory vesicle. The process of secretion starts with the cargo associated with the secretory vesicle. Does that sound right? or should the transport to the secretory vesicle be included in secretion? Can the parent term definitions be made more specific? Currently the parent (secretion and regulation of secretion) definitions have no start and end points.

**Comment by ValWood** [comment]
I think you can annotate a signalling pathway regulating a process to "regulation of that process".
You can regulate a process (i.e frequency) via signalling. 
I don't think this means that regulation of a process ends with cargo selection.

However, the secretion branch is problematic. I think the meaning depends if you are referring to secretion  by cell (which is covered by exocytosis), or secretion by tissue. 
I know nothing about the latter, but exocytosis from the def:

"Exocytosis begins with steps that prepare vesicles for fusion with the membrane (tethering and docking) and ends when molecules are secreted from the cell. PMID:22323285"

I think there are problems here because the "signalling" for cargo selection isn't regulating these steps is it?.....it's regulating something way-way upstream....

**Comment by RLovering** [comment]
good point. Sorry I don't have more time for this now.

**Comment by ValWood** [comment]
Will be addressed by 

https://github.com/geneontology/go-ontology/issues/19115
