### ISSUE TITLE
cytokine activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16105]
I think there is a problem with the signaling ontology for these ligand activity MF terms.

We have agreed that a ligand that stimulates a ligand signaling pathway is part of the pathway. Therefore a cytokine would be annotated to GO:0019221 cytokine-mediated signaling pathway.
The ancestor parent being GO:0034097  response to cytokine and ultimately GO:0050896  response to stimulus.

However, GO:0005125 cytokine activity has the parent GO:0030545 receptor regulator activity; GO:0009966 regulation of signal transduction and ultimately GO:0048583 regulation of response to stimulus. 

Thus a cytokine is annotated to regulation of a signaling pathway and involved in a signaling pathway. Not sure the best way to break this contradiction. 

Could it be set up more like the GO:0004896 cytokine receptor activity term:
GO:0060089   molecular transducer activity
> is_a GO:0038023  signaling receptor activity
>> is_a GO:0004888  transmembrane signaling receptor activity
>>> is a GO:0004896 cytokine receptor activity
GO:0019221 cytokine-mediated signaling pathway
> part_of GO:0004896 cytokine receptor activity

eg (remove the parent GO:0030545 receptor regulator activity) and establish the new ontology as : 
GO:0060089   molecular transducer activity
> is_a GO:0048018    receptor ligand activity
>>> is_a GO:0005125 cytokine activity
GO:0019221 cytokine-mediated signaling pathway
> part_of GO:0005125 cytokine activity

It would get rid of a lot redundant general and conflicting annotations if this could be applied to all ligands. Plus it would mean that curators could see that the ligand should be annotated to the signaling pathway, not to regulation of it.

Thanks

Ruth

**Comment by ukemi** [comment]
Looking at this agin, I'm also wondering if the current structure is correct at the class level. Particularly 'regulation of signaling receptor activity' part-of 'regulation of signal transduction'. I'm not sure with the current causal chain view of functions, this relationship hold for all instances. It doesn't seem to hold for receptor ligands.

**Comment by pgaudet** [comment]
@RLovering 
I cannot move 'GO:0048018 receptor ligand activity' (and its child 'cytokine activity') under 'GO:0060089 molecular transducer activity' as 'molecular transducer activity' is defined as a "compound function in which an effector function is controlled by one or more regulatory components"

**Comment by pgaudet** [comment]
id: GO:0030546
OLD: name: receptor activator activity
NEW name: signaling receptor activator activity

REMOVE is_a: GO:0030545 ! receptor regulator activity
REMOVE: relationship: part_of GO:2000273 ! positive regulation of signaling receptor activity
REMOVE: relationship: positively_regulates GO:0038023 ! signaling receptor activity

NEW LOGICAL DEFINITION
 intersection_of: GO:0003674 ! molecular_function
 intersection_of: directly_positively_regulates GO:0038023 ! signaling receptor activity


----

 id: GO:0030546
name: receptor ligand activity
REMOVE: is_a: GO:0003674 ! molecular_function
REMOVE: relationship: directly_regulates GO:0038023 ! signaling receptor activity

PARENTS: 
 is_a: GO:0005102 ! signaling receptor binding
+is_a: GO:0030546 ! signaling receptor activator activity
+relationship: directly_positively_regulates GO:0038023 ! signaling receptor activity
+relationship: part_of GO:0007165 ! signal transduction


---
id: GO:0030545
name: receptor regulator activity
REMOVE:  relationship: part_of GO:0010469 ! regulation of signaling receptor activity

LOGICAL DEFINITION: 
molecular_function
 and ('directly regulates' some 'signaling receptor activity')


I *think* this will remove the unwanted link.
