### ISSUE TITLE
GO:0071554 cell wall organization and biogenesis taxon restrictions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16108]
Should have  never in vertebrates (minimally)?
Human 6 annotations, D. rereio 8 annotations  etc

Or only in fungi, plants bacteria?

Do dicty have a "cell wall" @pfey03 ? (7 annotations purpureum 21 discoideum)
@vanaukenk C.elegans don't do they?  (11 annotations)

**Comment by vanaukenk** [comment]
@ValWood 

In some cases here I think we're looking at annotations to antimicrobials, i.e. immune effectors.

We could make a ticket in the go-annotation tracker to do more thorough annotation review, but there does seem to be some legitimate annotation as part of an evolved host defense process of cell wall catabolism.

**Comment by ValWood** [comment]
I still think these types of annotation are strange (both host defense responses and pathogen host interactions)

There should be clear pathogen-host and host-defense response branches  in the ontology like there used to be (IMHO). I really wish we could go return to this. Otherwise in the future  annotations will become (are already) very confusing. - I  wonder even if the existing annotations include the  taxon ID of the pathogen or host for example.

In addition to being confusing, this representation makes annotation difficult and will make it increasingly difficult to implement  taxon checks.


Not many people actively annotating pathogens right now but   when we are this will become a bigger problem.

**Comment by vanaukenk** [comment]
Added to agenda for next QC/QA call.

**Comment by ValWood** [comment]
I'm still confused. Do we have examples of vertebrates degrading cell walls (other than by digestion). Would people expect to see  digestive enzymes annotated to "cell wall catabolism"? of the ingested organism (this is similar).

I wouldn't refer to the breakdown of another organism carbohydrate component as "cell wall catabolism", but it isn't easy to see how to prevent it ...

**Comment by ValWood** [comment]
For now, put the taxon restriction on
GO:0042546    cell wall biogenesis

**Comment by pgaudet** [comment]
Added never in vertebrates

**Comment by pgaudet** [comment]
@vanaukenk I'm working with @ValWood on tickets, I fixed this one.
