### ISSUE TITLE
response to chemokine add child relation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16104]
Hi

please  could a child term link be made as follows:

GO:1990869   cellular response to chemokine
part_of child GO:0070098   chemokine-mediated signaling pathway

Thanks

Ruth

**Comment by ukemi** [comment]
Wouldn't it be the other way around? The signaling pathway would be part of the overall response wouldn't it. Im always a bit baffled by the response terms.

**Comment by ukemi** [comment]
OK. I see now,, that is the way you want it and it is consistent with others.
