### ISSUE TITLE
micos complex/ cristae junction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16113]
I thought the micos complex *was* the cristae junction.

![micos](https://user-images.githubusercontent.com/7359272/43102043-f3f180fa-8ec1-11e8-85ac-f6124a9fe29e.jpg)

if not is it part_of ?

**Comment by hdrabkin** [comment]
From a quick look at lit, it seems that it is a complex involved in the maintenance of cristae junction, not the junction itself?

**Comment by ValWood** [comment]
I don't think they are separable....
see
https://link.springer.com/article/10.1007%2Fs00441-016-2433-7#Fig2
from
https://www.ncbi.nlm.nih.gov/pubmed/27245231

**Comment by ValWood** [comment]
Seems that it should be part_of?

**Comment by ValWood** [comment]
OK maybe not. If it forms the contact site with the OM and this results in the formation of the cristae junction...
Will close...

**Comment by ValWood** [comment]
stest.

However the def of crista junction looks wrong
-- | --
A tubular structure of relatively uniform size that connects a mitochondrial crista to the mitochondrial inner boundary membrane.



shouldn't that be connects cristae  to the mitochondrialouter membrane. In which case they would be equivalent?

**Comment by ValWood** [comment]
Yes, it is  joins the inner membrane t the outer membrane and this forms the  cristae junction. At least that is how I understand it but that could be wrong.

See
![micos](https://user-images.githubusercontent.com/7359272/43166266-fe9276d2-8f8d-11e8-9fa1-75ff11f59a6d.jpg)

from the review above. Which is your paper?

Do we have a mitochondria expert?

**Comment by ValWood** [comment]
The only things I have annotated to the cristae junction are MICOS (ISS from SGD)

**Comment by ValWood** [comment]
OK, I had forgortten about this one

https://github.com/geneontology/go-ontology/issues/15245
partly overlapping...

**Comment by pgaudet** [comment]
What's the action here ?

**Comment by ValWood** [comment]
can close,  issues covered by #15245
