### ISSUE TITLE
mitochondrial inner membrane protein insertion complex (GO:0042721)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16112]
please please can we call this the 

TIM22 inner membrane protein import complex
 (or similar).

I think this one is the Tim 22 complex

Tim23 complex seems to be
mitochondrial inner membrane presequence translocase complex (GO:0005744)
(Tim23 is currently a narrow synonym, I'm not sure why it is narrow)

I have *NO* idea why we don't refer to them how the world refer to them.......

**Comment by ValWood** [comment]
these are the varios
![mitochondrial translocases](https://user-images.githubusercontent.com/7359272/43100040-f9afb300-8ebb-11e8-9903-fd4302c48ec9.jpg)
us translocases and their *universal* names

@pgaudet   might be good to deal with this when finishing  up transport?

**Comment by pgaudet** [comment]
Here's what I did: 

 **id: GO:0005744**
-name: mitochondrial inner membrane presequence translocase complex
**+name: TIM23 mitochondrial import inner membrane translocase complex**
-def: "The protein transport machinery of the mitochondrial inner membrane that contains three essential Tim proteins: Tim17 and Tim23 are thought to build a preprotein translocation channel while Tim44 interacts transiently with the matrix heat-shock protein Hsp70 to form an ATP-driven import motor." [EC:3.6.3.51, PMID:8851659]
**+def: "The protein transport machinery of the mitochondrial inner membrane that typically transports proteins that possess a matrix-targeting N-terminal presequence. The TIM23 complex contains three essential Tim proteins: Tim17 and Tim23 are thought to build a preprotein translocation channel while Tim44 interacts transiently with the matrix heat-shock protein Hsp70 to form an ATP-driven import motor." [EC:3.6.3.51, PMID:27554484, PMID:8851659]**
-synonym: "mitochondrial inner membrane pre-sequence translocase complex" EXACT []
-synonym: "mitochondrial inner membrane translocase complex" EXACT []
-synonym: "Tim23 complex" NARROW []
+synonym: "mitochondrial inner membrane pre-sequence translocase complex" **BROAD** []
+synonym: "mitochondrial inner membrane presequence translocase complex" **BROAD** []
+synonym: "mitochondrial inner membrane translocase complex" **BROAD** []
+synonym: "Tim23 complex" **EXACT** []


----

**id: GO:0042721**
-name: mitochondrial inner membrane protein insertion complex
**+name: TIM22 mitochondrial import inner membrane translocase complex**
-def: "A multi-subunit complex embedded in the mitochondrial inner membrane that mediates insertion of carrier proteins into the inner membrane." [PMID:12191765]
**+def: "A multi-subunit complex embedded in the mitochondrial inner membrane that mediates the inner membrane insertion of multi-transmembrane spanning proteins that contain internal targeting elements. In yeast cells, TIM22 is a 300-kDa complex, consisting of four membrane integral subunits, Tim22, Tim54, Tim18 and Sdh3, and a peripheral chaperone complex consisting of the small TIM proteins, Tim9-Tim10-Tim12." [PMID:12191765, PMID:27554484]**
-synonym: "Tim22 complex" NARROW []
+synonym: "mitochondrial inner membrane protein insertion complex" EXACT []
+synonym: "mitochondrial protein translocase complex" **BROAD** []
+synonym: "Tim22 complex" **EXACT** []

**Comment by ValWood** [comment]
Thanks, this has been bugging me for years. I always needed to go to the defs to figure it out.

**Comment by pgaudet** [comment]
ok, so I merge ?

**Comment by ValWood** [comment]
Merge what? I thought you just renamed?

**Comment by pgaudet** [comment]
sorry - merge the pull request, ie put these changes I described above into GO.

**Comment by ValWood** [comment]
yep...
