### ISSUE TITLE
GO:0045259  proton-transporting ATP synthase complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16111]
none of the synonyms contain "F1-F0"  can this be added?

Wouldn't it be more recognisable if it were called:

F-type or F-ATPase

I always need to think about 
GO:0045259  proton-transporting ATP synthase complex

**Comment by hdrabkin** [comment]
F1-F0 complex? related, exact, narrow, etc. ?

**Comment by ValWood** [comment]
exact? from def and other names?

**Comment by hdrabkin** [comment]
done; synonym added
