### ISSUE TITLE
new primary term name for GO:0044233 ER-mitochondrion membrane contact site

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16122]
current:
 GO:0044233 ER-mitochondrion membrane contact site
(never used PuBMed)
MAKE THIS A SYNONYM INSTEAD

to NEW TERM NAME
Mitochondria-associated ER Membrane ( new primary term name)
(32 exact match)
MOST COMMONLY USED

BY FOR EG, ADD THESE AS REFS
Mitochondria-associated Endoplasmic Reticulum Membrane (new exact, for searching)
https://www.ncbi.nlm.nih.gov/pubmed/22078959
https://www.ncbi.nlm.nih.gov/pubmed/29684109
https://www.ncbi.nlm.nih.gov/pubmed/29626751

ADD THIS AS A SYNONYM
Mitochondria-associated Membrane (add synonym related)
https://en.wikipedia.org/wiki/Mitochondria_associated_membranes

ADD THIS AS A SYNONYM
mitochondria-endoplasmic reticulum (ER) contacts (add synonym exact)
https://www.ncbi.nlm.nih.gov/pubmed/29870872

alter existing
endoplasmic-reticulum-mitochondrion membrane contact site
to remove hyphen between endoplasmic-reticulum

**Comment by hdrabkin** [comment]
okydoky done.
