### ISSUE TITLE
NTRs: box C/D snoRNP complex binding and box H/ACA snoRNP complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16137]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'box C/D snoRNP complex binding' and ' box H/ACA snoRNP complex binding' based on
PMID:10679015 
( Conserved composition of mammalian box H/ACA and box C/D small nucleolar ribonucleoprotein particles and their interaction with the common factor Nopp140.)

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0031428 box C/D snoRNP complex
GO:0031429  box H/ACA snoRNP complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
