### ISSUE TITLE
NTR: GARP complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16135]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'GARP complex binding' based on
PMID:20163565
( novel syntaxin 6-interacting protein, SHIP164, regulates syntaxin 6-dependent sorting from early endosomes.)
 " SHIP164 is part of a large (approximately 700 kDa) complex, and interacts with components of the Golgi-associated retrograde protein (GARP) tethering complex."

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0000938 GARP complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
