### ISSUE TITLE
NTR: SAGA complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16134]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'SAGA complex binding' based on 
PMID:27185460 
(The Spliceosomal Protein SF3B5 is a Novel Component of Drosophila SAGA that Functions in Gene Expression Independent of Splicing.) 
Even if on the title is referred as a novel component, it is still considered as just associating with it (checked with Birgit)

Thanks,
Penelope

**Comment by ukemi** [comment]
Do we really want to go the route of instantiating all these complex binding terms? Added to Editors' discussion.

**Comment by pgarmiri** [comment]
Hi @ukemi , I was just following what @pgaudet  said in the ticket referenced above.
 
(You can use the protein complex ID to annotate, using 'with', or yes, request the complex binding term (we had decided we would create these until we have a better structure to capture the information)).

Please let me know the outcome on this at the Editors' discussion. I am reviewing the UniProt annotations that have contribute_to with a protein complex term and I expect that more will arise.

Thanks,
Penelope

**Comment by ukemi** [comment]
Hi @pgarmiri. Sorry. I didn't remember this decision and we didn't get a chance to discuss it on the call yesterday. @pgaudet, is this the route we are taking? They are easy enough to create.

**Comment by ValWood** [comment]
I think increasingly we have been putting the GO complex ID  in the extension with a complex binding term. Or preferably use "protein binding" annotation with the specific subunit of the bound complex (we nearly always know this, at least for more recent papers).

**Comment by pgaudet** [comment]
This is where the decision was made: https://github.com/geneontology/go-ontology/issues/13148
This was discussed on an editors call. 

So my understanding is to create any protein complex binding term. 

Or else obsolete them. Either way works for me, the problem was that some groups could not annotate with extensions. 

Thanks, 
Pascale

**Comment by ValWood** [comment]
If you decide to obsolete we should keep some probably . Like ribosome binding. larger macromolecular complexes.....

**Comment by ukemi** [comment]
They are easy enough to add. I tend not to obsolete.

**Comment by ValWood** [comment]
I'd be happy for them to go if it makes ontology development maintenance easier.
We tend not to use them, if possible. I think M @mah11 . has used a lot in logical defs for FYPO but I think they could be constructed with complex + binding terms...

For some reason I think I thought they were going, so we have moved over to capture with extensions. If you are adding let me know and I'll request terms for these.

**Comment by pgaudet** [comment]
I am agnostic - I just want consistency :)

**Comment by ValWood** [comment]
Me too! I also don't want to continue annotating   to complex binding and then   need to change them all later when we have many more annotations....

At present I only have  ~65 annotations, so easy to change to extensions right now.  A pain in the future.......

Although really we only use  them as a last resort if we can't specify the subunit so maybe they will not increase very much....

**Comment by pgarmiri** [comment]
GO:0000124 SAGA complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
