### ISSUE TITLE
NTRs:PSII associated light-harvesting complex II binding, chloroplast photosystem I binding and chloroplast photosystem II binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16136]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need new terms to indicate 'PSII associated light-harvesting complex II binding', 'chloroplast photosystem I binding' and 'chloroplast photosystem II binding' based on
PMID:17400553
( The mobile thylakoid phosphoprotein TSP9 interacts with the light-harvesting complex II and the peripheries of both photosystems.)

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0009517 PSII associated light-harvesting complex II
 GO:0030093 chloroplast photosystem I
 GO:0030095 chloroplast photosystem II

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
