### ISSUE TITLE
taxonomic scope of "renal system development"

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16143]
Prompted by AGR expression ribbon discussion

```
id: GO:0072001
name: renal system development
namespace: biological_process
def: "The process whose specific outcome is the progression of the renal system over time, from its formation to the mature structure. The renal system maintains fluid balance and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products. In humans, the renal system comprises a pair of kidneys, a pair of ureters, urinary bladder, urethra, sphincter muscle and associated blood vessels." [GOC:mtg_kidney_jan10, GOC:yaf, http://en.wikibooks.org/wiki/Human_Physiology/The_Urinary_System]
synonym: "urinary system development" BROAD [GOC:yaf]
synonym: "urinary tract development" BROAD [GOC:yaf, PMID:17881463]
is_a: GO:0048731 ! system development
intersection_of: GO:0048731 ! system development
intersection_of: results_in_development_of UBERON:0001008 ! renal system
relationship: part_of GO:0001655 ! urogenital system development
```

What is the intended taxonomy scope here? The accompanying kidney paper explicitly mentions tubules (which includes drosophila, but would exclude C elegans). Indeed the term has been used for Dmel but not Cele.

The uberon class follows the def of the GO class, taking the kidney paper as reference. But it is mapped to excretory system in WBbt, which makes it implicitly broader than GO. Also, since Uberon treats it broader, GO does not inherit a TC that excludes Cele, if that is the intention.

I'm not sure if all the following is true for the Cele excretory system, I think so?

"...maintains fluid balance and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products"

It's not really clear that we require a term that is broad enough to cover Dmel + verts yet exclude Cele. We already have http://amigo.geneontology.org/amigo/term/GO:0061326 "renal tubule development" which groups Dmel Malpighian tubules and true renal tubules, why do we need an additional level of Dmel + vert grouping?

Seems most straightforward to explicitly broaden the already broad "renal system" and relabel "excretory system" and include Cele. Of course, such broad pan-metazoa system-level groupings should be used with caution .e.g in gene propagation

**Comment by ukemi** [comment]
@vanaukenk, I'll let you comment on this one. I don't recall discussing worms at the renal meeting, but if I recall correctly we did want to include flies.

**Comment by vanaukenk** [comment]
"Seems most straightforward to explicitly broaden the already broad "renal system" and relabel "excretory system" and include Cele. Of course, such broad pan-metazoa system-level groupings should be used with caution .e.g in gene propagation."

I agree that a more general term of "excretory system development" would be useful and we could use that for C. elegans.  "renal system" is not used much at all in the C. elegans literature; "excretory system" is the preferred way of describing the analogous system in worms.

However, if we relabel the existing "renal system development" to be "excretory system development", then I think we'll need to revise the parentage in GO because the C. elegans excretory system is not mesodermally derived as the current part_of relation between "renal system development" and "urogenital system development" would imply.

**Comment by ukemi** [comment]
Hi @vanaukenk. I'm not seeing the relationship to the mesoderm in AmiGO2. Where are you seeing it?

**Comment by vanaukenk** [comment]
@ukemi  
I was tracing that through UBERON.
In GO, 'renal system development' is part_of 'urogenital system development' and in UBERON, 'genitourinary system' (exact synonym: urogenital system ) (UBERON:0004122) has an is_a relation to 'mesoderm-derived structure' (UBERON:0004120).

**Comment by cmungall** [comment]
Fixed to be specific to vertebrates. 

(it's still a bit odd to have a genital + renal system grouping for many inverts? the coupling makes sense for verts where there are shared structures and development? at least the terminology 'urogenital system' seems a bit vertebratey)

**Comment by ukemi** [comment]
I agree it is very verebratey.

**Comment by vanaukenk** [comment]
Yes, it is vertebratey.
I just did a TPC search on the C. elegans literature for 'urogenital'.  The returned citations are referring to the vertebrate system in the intro or discussion section of papers, and not many papers are returned (49 out of a corpus of 23613 possible papers).

**Comment by ukemi** [comment]
Hmm. So it seems that we would not only have to rename the renal system to be the excretory system, which doesn't seem to be much of a stretch. But we would have to sever the part_of link in Uberon between the new 'excretory system' and 'genitourinary system'. Then we would have to reassign the appropriate part_of renal system classes in UBERON to be part_of 'genitourinary system'. If we could reason over the partonomy in UBERON I think we would get correct classification in GO.

**Comment by cmungall** [comment]
> So it seems that we would not only have to rename the renal system to be the excretory system, which doesn't seem to be much of a stretch.

Yep


> But we would have to sever the part_of link in Uberon between the new 'excretory system' and 'genitourinary system'. Then we would have to reassign the appropriate part_of renal system classes in UBERON to be part_of 'genitourinary system'.

Yes. We should always think carefully when removing links in the ontology if this will impact users. However, I think that by having part-ofs at the appropriate level will work here, as we should not be annotating directly to high level terms like renal/excretory system.

We already have links from specific embryonic classes like nephric ridge. Would also add to kidney.

>  If we could reason over the partonomy in UBERON I think we would get correct classification in GO.

Yes. We can start with mutual asserts just to ensure we don't lose info.

**Comment by ukemi** [comment]
Good point, and what about CO2? But what we really want is this:
maintains fluid balance and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products
ie we want something analagous to the renal system. Is there a better name we can use?

**Comment by cerivs** [comment]
well osmoregulatory systems but that gets you ionocytes in fish and amphibians too.

**Comment by cerivs** [comment]
The system needs to encompass the worm system that "...consists of just three unicellular tubes (canal, duct, and pore), a secretory gland, and two associated neurons. " https://dx.doi.org/10.1534%2Fgenetics.116.189357 as well as the pronephrose, mesanephrose and adult kidneys of vertebrates.    It looks like we need some sort of liquid excretory system.  Since in verts the colon/lower intestine contributes to fluid balance, electrolyte balance, acid/base balance, it is difficult to generalize by function enough to encompass C. elegans and verts without encompassing portions of the digestive system.

**Comment by cerivs** [comment]
I think the main differentia, which I am not sure how to express succinctly is that the renal system and the C. elegans excretory cells  remove nitrogen waste, and provide osmoregulatory function to the non-gut  portion of the organism.  In fish and birds the renal products end up in the coacal chamber as do the outputs from the digestive system so the the entire system can't be physically disjoint.

**Comment by ukemi** [comment]
The plot thickens. @mdolanme pointed out that we have 'renal system process' with exact synonym 'excretory system process'. I think we need to change this synonym to broad based on this discussion.

**Comment by cmungall** [comment]
Should we at least have a do not annotate on it? Shouldn't you always know a more specific term?

Of direct annotations (93), all are in vertebrates, 18 are experimental.

**Comment by ukemi** [comment]
I just spent the day going through all of the MGI annotations to renal system development and was able to change all of them to more specific terms describing either a more specific developmental process or at least point to more specific anatomical structures. A lot of these annotation were made before the kideny development project was done, so I suspect the terms I used didn't exist at the time. I think @cmungall 's suggestion is the most practical. We should mark the renal system development term a 'do not manually annotate' term and ask for annotation review of the remaining annotations.

**Comment by ukemi** [comment]
Annotation review suggested in:
https://github.com/geneontology/go-annotation/issues/2392

**Comment by pgaudet** [comment]
> 'do not manually annotate'

why not use ''do not annotate'?

**Comment by ukemi** [comment]
Fine with me.

**Comment by pgaudet** [comment]
@ukemi I've added 'do not annotate' to GO:0072001 renal system development

If that resolves this issue, please close the ticket. 

Thanks, Pascale

**Comment by hattrill** [comment]
Thanks! :-)

**Comment by ukemi** [comment]
Hopefully it will work, but I can't see why it shouldn't. The taxon restriction on renal system is much looser, only_in some eumetazoa.

**Comment by hattrill** [comment]
Fingers crossed!
