### ISSUE TITLE
Change labels: 'transcription factor recruiting activity' to 'transcription regulator recruiting activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16144]
to be consistent with the term label of GO:0140110 transcription regulator activity 
 id: GO:0001134
-name: transcription factor recruiting activity
+name: transcription regulator recruiting activity

 id: GO:0001186
-name: RNA polymerase I transcription factor recruiting activity
+name: RNA polymerase I transcription regulator recruiting activity

 id: GO:0001135
-name: RNA polymerase II transcription factor recruiting activity
+name: RNA polymerase II transcription regulator recruiting activity

 id: GO:0001004
-name: RNA polymerase III transcription factor recruiting activity
+name: RNA polymerase III transcription regulator recruiting activity

@ValWood @krchristie @RLovering

**Comment by RLovering** [comment]
I think this is good
