### ISSUE TITLE
NTR: BBSome binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16140]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'BBSome binding' based on
PMID:20603001 
(The conserved Bardet-Biedl syndrome proteins assemble a coat that traffics membrane proteins to cilia.)

"Arl6(GTP)-mediated recruitment of the BBSome to synthetic liposomes produces distinct patches of polymerized coat apposed onto the lipid bilayer."

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0034464 BBSome

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
