### ISSUE TITLE
Map slim terms for 'GO:0000988  transcription factor activity, protein binding'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16147]
Hello, 

I obsoleted GO:0000988  transcription factor activity, protein binding' (#16053 ). Some groups had this term in their slims; I propose to replace by GO:0140110  transcription regulator activity (and will do that for the go_slim generic); please let me know what you'd like to do: (GO:0140110 , another term, or just remove from the slim): 

    goslim_aspergillus -> @marekskrzypek
    goslim_generic @pgaudet ->  GO:0140110  transcription regulator activity 
    goslim_mouse 
    goslim_agr @selewis 
    goslim_candida  -> @marekskrzypek
    goslim_yeast @suzialeksander @srengel 

(I'll deal with goslim_chembl later - I haven't got a contact yet for this one).

**Comment by mdolanme** [comment]
This term has been removed from the mouse slim.

**Comment by pgaudet** [comment]
@marekskrzypek @suzialeksander @srengel   @selewis
Can you let me know if the proposed changes are OK ? 
(I'd rather not let the slims get too much out of date). 

Thanks Pascale

**Comment by pgaudet** [comment]
Hi @marekskrzypek @selewis @srengel 

* goslim_generic, goslim_yeast, and goslim_agr already had a mapping to GO:0003700 DNA-binding transcription factor activity. I assume this is sufficient
* I added the mapping to goslim_aspergillus and goslim_candida. 

Please open a new ticket if you have different suggestions.

Thanks, Pascale

**Comment by marekskrzypek** [comment]
Thank you, Pascale. This is good!

Marek



On Aug 10, 2018, at 9:42 AM, pgaudet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @marekskrzypek<https://github.com/marekskrzypek> @selewis<https://github.com/selewis> @srengel<https://github.com/srengel>

  *   goslim_generic, goslim_yeast, and goslim_agr already had a mapping to GO:0003700 DNA-binding transcription factor activity. I assume this is sufficient
  *   I added the mapping to goslim_aspergillus and goslim_candida.

Please open a new ticket if you have different suggestions.

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet  @ukemi @selewis @srengel 

We were just discussing the goslim_agr on an Alliance call and had a question about having an obsolete term in a slim subset.

Looking in Protege, it looks like GO:0000988 is still present in seven subsets.

Should subsets be removed from an obsolete term, or should this be handled, for example, by filtering out obsolete terms when displaying and/or using a slim?

<img width="1680" alt="go_0000988 subsets" src="https://user-images.githubusercontent.com/1730534/45043637-bcafd880-b03b-11e8-927f-bffdce5b272f.png">

There is also some history of this discussion on this ticket:
https://github.com/geneontology/go-ontology/issues/14677

**Comment by pgaudet** [comment]
Sure, I'll fix that. (I think I intended to remove the term and just added GO:0003700 to all concerned slims instead)

For me it's OK to maintain that by hand, there are not so many slims, and not so many terms per slim.

For terms for which we have 'replace by' the ontology editors can certainly also update the ontology.  

**The issue is that the slim maintainer should be responsive as to what action they want us to take - that was the whole reason to fix the slim yaml files and know who to contact.**  If there are no maintainer I would be in favor of archiving the slim. (see for example #16292)

I assumed that obsolete terms in slims would be ignored by whatever tools, so it would give the maintainer a chance to figure out what to so. 

Thanks, Pascale

**Comment by pgaudet** [comment]
In fact -  not doing automatic changes would highlight the fact that a slim is not maintained, therefore not needed; would't that be helpful to know in the end ?

**Comment by ukemi** [comment]
I'll update the editors' documentation.

**Comment by ukemi** [comment]
OK. I updated the documentation. I also went ahead and changed the old procedure to the one that uses the plugin. @pgaudet , since you are the chief obsoletion person, can you check for accuracy?
http://wiki.geneontology.org/index.php/Obsoleting_an_Existing_Ontology_Term#Prot.C3.A9g.C3.A9_Obsoletion_Process

**Comment by pgaudet** [comment]
@ukemi 
The plugin doesn't work for me. Can we have two options in the documentation ? 
(Or we can ask all new curators to use the plug in and somehow fix y version of protege at some point). At any rate, I cannot confirm this procedure as this is not what I do. 

Pascale

**Comment by ukemi** [comment]
Sorry @pgaudet. We should get the plugin working on your machine. I will keep two procedures for the moment, but I think everyone else uses the plugin.

**Comment by ukemi** [comment]
OK. The documentation has both procedures now.
