### ISSUE TITLE
NTR: oligosaccharyltransferase complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16146]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'oligosaccharyltransferase complex binding' based on
PMID:12887896
(Oligosaccharyltransferase isoforms that contain different catalytic STT3 subunits have distinct enzymatic properties.)

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0008250 oligosaccharyltransferase complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
