### ISSUE TITLE
protein sequestering  activity (was: sequestering)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16157]
So should this be in MF too?
It seems so?

 we would then obsolete
https://www.pombase.org/term/GO:0051220
cytoplasmic sequestering of protein involved in mitotic DNA replication checkpoint
cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint

and  use  MF part_of BP

**Comment by ValWood** [comment]
and
GO biological process sequestering of actin monomers (GO:0042989)
(unrelated!)

**Comment by ValWood** [comment]
GO:0042994    cytoplasmic sequestering of transcription factor !

**Comment by pgaudet** [comment]
A term along those lines would also be needed to capture things relevant to tx factors such as: 
- tagging for degradation: p53 on gene, when phosphorylated by PIC it leaves promoter (degradation is sort of a way to sequester - we need to express this more clearly)
and
- nuclear export: nucleoplasmic shuttling eg NFkappaB by IKKB, not part of TF ontology restructure. need GO term eg Db Transcription factor inhibitor/repressor activity include in defintion that this often occurs in the cytoplasm and may include HSPs egs would be steroid receptor/NkappaB binding protein

Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140311
+name: protein sequestering activity
+namespace: molecular_function
+def: "The selective interaction of a protein with a specific protein, thereby preventing it from  interacting with other partners or inhibiting its localization to other areas of the cell.." [PMID:1493333]
+is_a: GO:0003674 ! molecular_function
+is_a: GO:0005515 ! protein binding
+created_by: pg
+creation_date: 2019-03-26T14:34:16Z

**Comment by pgaudet** [comment]
I can fix the definition if you have improvements to suggest ! 

Pascale
