### ISSUE TITLE
NTR: TAP complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16155]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'TAP complex binding' based on
PMID:17947644
(Molecular architecture of the TAP-associated MHC class I peptide-loading complex.)

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0042825  TAP complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
