### ISSUE TITLE
Review mf_needs_review subset - possible obsoletions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16166]
Hello @hdrabkin 

At a receont ontology call we elected you to review the terms in the 'mf_needs_review' slim (and then presumably retiring that slim). 

The following have a comment that the obsoletion is planned: 
FMN reductase   activity' <http://purl.obolibrary.org/obo/GO_0008752> DONE IN #16166 
'carotene 7,8-desaturase activity'   <http://purl.obolibrary.org/obo/GO_0016719> DONE in #2050
'dihydroorotate oxidase activity'   <http://purl.obolibrary.org/obo/GO_0004158> obsoleted in #23789
**'hydroxynitrilase activity'   <http://purl.obolibrary.org/obo/GO_0047606>** add RHEA xrefs and missing children
> GO:0052891  aliphatic (S)-hydroxynitrile lyase activity
+xref: RHEA:56588 {source="skos:narrowMatch"}
+xref: RHEA:56592 {source="skos:narrowMatch"}
+is_a: GO:0047606 ! hydroxynitrilase activity

> GO:0052892 aromatic (S)-hydroxynitrile lyase activity
+is_a: GO:0047606 ! hydroxynitrilase activity

> GO:0052919 'aliphatic (R)-hydroxynitrile lyase activity'
+is_a: GO:0047606 ! hydroxynitrilase activity

'polyamine oxidase activity'   <http://purl.obolibrary.org/obo/GO_0046592> branch improved in #24701
'tRNA adenylyltransferase activity'   <http://purl.obolibrary.org/obo/GO_0004810> DONE in #19854

Those have no comment: 

'DNA-N1-methyladenine   dioxygenase activity' <http://purl.obolibrary.org/obo/GO_0043734>
'alcohol dehydrogenase (acceptor)   activity' <http://purl.obolibrary.org/obo/GO_0018468> Merged (cannot find the ticket) 
'amine dehydrogenase activity'   <http://purl.obolibrary.org/obo/GO_0030058> OK Has a RHEA
'aspartyl esterase activity'   <http://purl.obolibrary.org/obo/GO_0045330> ?????
'chondroitin ABC lyase activity'   <http://purl.obolibrary.org/obo/GO_0047486> Obsoleted in #24702
'clavaminate synthase activity'   <http://purl.obolibrary.org/obo/GO_0033758> OK Has a RHEA and an EC
'cobyrinic acid a,c-diamide synthase   activity' <http://purl.obolibrary.org/obo/GO_0042242> OK Has a RHEA and an EC
'dolichyl-phosphate-mannose-glycolipid   alpha-mannosyltransferase activity'   <http://purl.obolibrary.org/obo/GO_0004584> Obsoleted in #14578 
'gibberellin 20-oxidase activity'   <http://purl.obolibrary.org/obo/GO_0045544> ?? No RHEA, some TAIR annotations
**'glutamin-(asparagin-)ase activity'   <http://purl.obolibrary.org/obo/GO_0050417> Could obsolete in favor of asparaginase activity and glutaminase activity (no annotations)**
'linoleate diol synthase activity'   <http://purl.obolibrary.org/obo/GO_0033751> obsoleted in 
#22050
'oxidosqualene cyclase activity'   <http://purl.obolibrary.org/obo/GO_0031559> OK grouping class 
'polyamine oxidase activity'   <http://purl.obolibrary.org/obo/GO_0046592> branch improved in #24701
'protein-N-terminal glutamine   amidohydrolase activity' <http://purl.obolibrary.org/obo/GO_0070773> OK Has a RHEA and an EC
thalianol synthase activity'   <http://purl.obolibrary.org/obo/GO_0051746> OK Has a RHEA and an EC

Thanks, Pascale
'tRNA cytidylyltransferase activity'   <http://purl.obolibrary.org/obo/GO_0016437> Fixed in #19854
'trans-octaprenyltranstransferase   activity' <http://purl.obolibrary.org/obo/GO_0050347> Done in #23417
'trans-pentaprenyltranstransferase   activity' <http://purl.obolibrary.org/obo/GO_0048045> Obsoleted in #23202

**Comment by hdrabkin** [comment]
I'm holding off on obsoleting the two tRNA terms. I should untag them
'tRNA adenylyltransferase activity' http://purl.obolibrary.org/obo/GO_0004810; 
'tRNA cytidylyltransferase activity' http://purl.obolibrary.org/obo/GO_0016437

**Comment by hdrabkin** [comment]
Yes, I remember
 EC 2.7.7.71 was transferred to  EC 2.7.7.72   (GO_0016437)
EC: EC 2.7.7.25 was transferred to EC 2.7.7.72 (GO_0004810)
I think a merge would be more appropriate, and that way no annotations need fixing;
 the same enzyme catalyzes both reactions (except in ONE organism, which needs two separate enzymes (one to add the Cs, and the other to add the As).

**Comment by hdrabkin** [comment]
FMN reductase activity' http://purl.obolibrary.org/obo/GO_0008752
EC 1.5.1.29
Deleted entry: FMN reductase [NAD(P)H]. Now covered by EC 1.5.1.38 [FMN reductase (NADPH)], EC 1.5.1.39 [FMN reductase [NAD(P)H])] and EC 1.5.1.41 (riboflavin reductase [NAD(P)H])

carotene 7,8-desaturase activity' http://purl.obolibrary.org/obo/GO_0016719
EC:1.14.99.30; transferred to EC 1.3.5.6; we have this EC activity as a synonym for GO_0016719

'dihydroorotate oxidase activity' http://purl.obolibrary.org/obo/GO_0004158
EC 1.3.3.1 Transferred entry: 1.3.98.1

**Comment by hdrabkin** [comment]
'hydroxynitrilase activity' http://purl.obolibrary.org/obo/GO_0047606
 EC:4.1.2.37; now EC 4.1.2.47, (S)-hydroxynitrile lyase
a hydroxynitrile = cyanide + an aldehyde or ketone to
An aliphatic (S)-hydroxynitrile <=> cyanide + an aliphatic aldehyde or ketone
An aromatic (S)-hydroxynitrile <=> cyanide + an aromatic aldehyd

**Comment by hdrabkin** [comment]
So for the ones with no comment it is hard to know why it is in this slim
http://www.ontobee.org/ontology/GO?iri=http://purl.obolibrary.org/obo/GO_0043734
The EC mapping to this is a grouping term (1.14.11)  and need to be removed or remapped; I think it's closest to EC 1.14.11.51  although 0043734 mentions both  N1-methyladenine and N3-methylcytosine wherease the EC id only mentions  N1-methyladenine 
Has 131 annotations!!! 17 IEA and the bulk of the rest are ISO/ISS/ etc. with 8 manual via experiment (IDA, IMP,

**Comment by hdrabkin** [comment]
clavaminate synthase activity' http://purl.obolibrary.org/obo/GO_0033758  EC:1.14.11.21
Nothing wrong with this but has no annotations; 
cobyrinic acid a,c-diamide synthase activity http://www.ontobee.org/ontology/GO?iri=http://purl.obolibrary.org/obo/GO_0042242 
Has 2 EC numbers, but only one matches EC:6.3.5.10 (Adenosylcobyric acid synthase (glutamine-hydrolyzing).) and EC:6.3.5.11 (Cobyrinate a,c-diamide synthase (glutamine-hydrolyzing). )
THe latter fits the def, the former actually maps to GO:0051921; I could fix this by removing EC:6.3.5.10 from GO_0042242

**Comment by hdrabkin** [comment]
@pgaudet , if I can fix some immediately, do you want me to just remove the member of the for review slim? Let me know (I will continue doing the analysis and put results in this ticket).

**Comment by pgaudet** [comment]
Hi @hdrabkin 
I think that review slim should be deleted. If you want I can delete it now (well, soon). This ticket is just to make sure that the terms needing review are getting reviewed (and it seems OK to be that some are right and stay in the ontology). 

OK with you?

**Comment by hdrabkin** [comment]
'alcohol dehydrogenase (acceptor) activity' http://purl.obolibrary.org/obo/GO_0018468
This term has an EC that has been transferred
 EC 1.1.99.8 now is EC:1.1.2.8 (Alcohol dehydrogenase (cytochrome c).) and 1.1.2. 7 (Methanol dehydrogenase (cytochrome c).
1.1.28 maps to three GO terms , GO:0052936, GO:0052934, and GO:0052935
1.1.2.7 has no mapping in GO; the methanol dehydrogenases in GO does not use cytochrome but uses NAD and mapps to 1.1.1.244
GO:001846 looks more like a grouping term; it has 16; I would just remove the EC mapping. 
'alcohol dehydrogenase
  (acceptor) activity" acceptor could be either NAD or cytochrome 

--

**Comment by hdrabkin** [comment]
Sure; this ticket suffices to my being able to be tracking them. As I make final fixes I can mark them resolved.

**Comment by hdrabkin** [comment]
thalianol synthase activity' http://purl.obolibrary.org/obo/GO_0051746; add  EC 5.4.99.31; RHEA:26163
'linoleate diol synthase activity' http://purl.obolibrary.org/obo/GO_0033751
    has :EC:1.13.11.44; MetaCyc:1.13.11.44-RXN
  EC transfered to  1.13.11.60

Clavaminate synthase. EC 1.14.11.21; catalysis of 3 reactions This is how EC has it as does GO.
However, RHEA has 3 separate RHEA ids for this. 
      Deoxyamidinoproclavaminate + 2-oxoglutarate + O(2) <=> amidinoproclavaminate + succinate + CO(2) 
    Proclavaminate + 2-oxoglutarate + O(2) <=> dihydroclavaminate + succinate + CO(2) + H(2)O
    Dihydroclavaminate + 2-oxoglutarate + O(2) <=> clavaminate + succinate + CO(2) + H(2)O
RHEA:19785, RHEA:12773, and RHEA:20021;
