### ISSUE TITLE
Obsolete mf_needs_review subset 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16167]
Once reviewing the terms has been done, see #16166

**Comment by pgaudet** [comment]
@hdrabkin I don't suppose you still need this ? Can I go ahead? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Hi @pgaudet ; not sure what it is I still need? DO you mean the slim itself? No, all the terms are in the 16167 ticket, I can reference that.

**Comment by pgaudet** [comment]
Right the slim itself.  Thanks ! 

Pascale
