### ISSUE TITLE
true path violations under "mitotic spindle checkpoint" (incorrect parent, causes TPVs)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16168]
ALL of the immediate parents of "mitotic spindle checkpoint" EXCEPT "mitotic cell cycle checkpoint"
should move down  to be parents of
"mitotic spindle assembly checkpoint"

The other checkpoints are considered part of the "spindle checkpoint", but they are not  involved in the regulation of the metaphase/anaphase transition. 

For example the 
"Dma1-dependent checkpoint" negatively regulates the SIN/cytokinesis until the spindle assembly checkpoint is switched off.

**Comment by ValWood** [comment]
It's only one term, so would be quick

GO:0045841    negative regulation of mitotic metaphase/anaphase transition

**Comment by krchristie** [comment]
@ValWood - It is hard in Protege to see ALL of the parent terms, so could you please provide a list of exactly which terms should be parents of "mitotic spindle assembly checkpoint" instead of parents of "mitotic spindle checkpoint"

**Comment by ValWood** [comment]
I did in the following comment?

**Comment by pgaudet** [comment]
@krchristie I am surprised that it's difficult to see the parents in Protégé; isn't it just the 'subclasses' and equivalence axiom genera ?

Pascale

**Comment by ValWood** [comment]
@pgaudet  we can steal this one, it's quick...

**Comment by ValWood** [comment]
GO:0007094    JSON
mitotic spindle assembly checkpoint
Biological Process

Definition (GO:0007094 GONUTS page)
A cell cycle checkpoint that delays the metaphase/anaphase transition of a mitotic nuclear division until the spindle is correctly assembled and chromosomes are attached to the spindle. PMID:12360190

should be the term related to 
GO:0045841 negative regulation of mitotic metaphase/anaphase transition

**Comment by ValWood** [comment]
NO ACTION

**Comment by ValWood** [comment]
change relationship of
mitotic spindle assembly checkpoint
to
GO:0071174    mitotic spindle checkpoint
