### ISSUE TITLE
rename presequence translocase-associated import motor (GO:0001405)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16163]
rename
PAM complex, Tim23 associated import motor

Existing Definition 
-- | --
Protein complex located on the matrix side of the mitochondrial inner membrane and associated with the presequence translocase complex; hydrolyzes ATP to provide the force to drive import of proteins into the mitochondrial matrix.

new Def

-- | --
Protein complex located on the matrix side of the mitochondrial inner membrane and associated with the TIM23 mitochondrial import inner membrane translocase complex (GO:0005744); ATPase motor activity to drive import of proteins into the mitochondrial matrix.

**Comment by ValWood** [comment]
should also have parent "mitochondrial matrix"

**Comment by hdrabkin** [comment]
done did
