### ISSUE TITLE
GO:1990000 positive regulation of amyloid fibril formation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16169]
_From @ValWood on July 27, 2018 10:33_

Amyloid fibrils are abnormal (or is there any case where this is a normal process?). 
I can see you would have terms for clearance but not for regulation of formation?

_Copied from original issue: geneontology/go-annotation#2038_

**Comment by ukemi** [comment]
Years ago I worked on this for a brief time. It is a fascinating subject that was quite controversial. There was discussion about including these structures, as well as Lewy Bodies, in GO and we decided to include them. 
PMID:28937655

**Comment by pgaudet** [comment]
Added this comment to 
GO:1990000 positive regulation of amyloid fibril formation
and regulation children: 

> Although deposition of amyloid fibrils is associated with diseases, e.g. Alzheimer's disease, amyloid formation is a normal process. Disease occurs when the balance between amyloid formation and clearance is disrupted (reviewed e.g. in PMID:29654159 and PMID:28937655). An example of this is seen when human RIP1 and RIP3 kinases form a heterodimeric functional amyloid signaling complex (PMID:22817896).

I added the 3 references there as additional references. 

----

Remaining question: The reference cited for the 'regulation', PMID:23106396, talks about 'defense against amyloid fibers' - which is now getting in the diseases realm, isn't is ? It does seems like a normal phenomenon, but it seems to be 'response to pathogenic amyloid fibril formation' rather than just a normal regulation. 

Papers annotated to these regulation terms (all ARUK) seem to describe phenotypes )although I must say I glanced very quickly). 

@BarbaraCzub please open a new ticket if you want to address this issue. (I will close this one as the work requested here is done). 

Thanks, Pascale

**Comment by pgaudet** [comment]
I edited the last sentence of the comment slightly 

>An example of a normal amyloid complex is composed of human RIP1 and RIP3 kinases  (PMID:22817896).

Thanks, Pascale
