### ISSUE TITLE
NTR:lectin-induced modified bacterial internalization

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#16177]
Hi: 
Recent work in Dictyostelium has revealed that lectin-coated bacteria evade host digestion, a phenomenon the authors termed lectin-induced modified bacterial internalization. Mammalian cells also display this ability, suggesting this process may be a general feature of eukaryotes. I am not certain if the parent suggested below is correct, as this seems to specifically involve bacterial symbionts. Please let me know if you have any questions.

Thanks,
Bob

Name: lectin-induced modified bacterial internalization
Ontology: biological_process
Synonyms: LIMBI
Alternate IDs: None
Child of: GO:0052182 modification by host of symbiont morphology or physiology via secreted substance
Definition: The process in which an organism effects a change in the structure or function of a symbiont organism, mediated by secretion of lectins which bind to the bacterial surface. The symbiont is defined as the smaller of the organisms involved in a symbiotic interaction.

PMID:30049880 Lectins modulate the microbiota of social amoebae

**Comment by hdrabkin** [comment]
GO:0106136

**Comment by rjdodson** [comment]
Thanks for adding this term. It now occurs to me that in order to fully curate the gene for which I requested this term, I will need an additional component term. In the reference cited above, the authors show that a Dictyostelium lectin protein (DscA) binds to the cell surface of an endosymbiont bacterium, K. pneumoniae. Unless I'm missing something, I cannot really find a GO component term which correctly describes this cellular location, so I'm requesting creation of a new GO component term. Let me know if you have any questions, or prefer that I submit a new ticket for this. 

Thanks,
Bob

Name: symbiont cell surface
Ontology: cellular_component
Synonyms: endosymbiont cell surface
Alternate IDs: None
Child of: GO:0044217 other organism part
Definition: The cell surface of a secondary, endosymbiont organism with which the first organism is interacting. The symbiont is defined as the smaller of the organisms involved in a symbiotic interaction.
PMID:30049880 Lectins modulate the microbiota of social amoebae

**Comment by hdrabkin** [comment]
GO:0106139
name: symbiont cell surface
