### ISSUE TITLE
What are GOTAX IDs? and why are there multiple ones for a single NCBITaxon ID?

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#16176]
@cmungall @ukemi - Could you take a look at this please.

Below is a subset of taxon lines grepped out of the go-edit.obo file (because I was hoping to quickly identify the taxon IDs we use frequently to identify the correct one I should use for a ticket I am working on).

1. Why do **some, but not all,** never_in_taxon and only_in_taxon lines contain a reference to a GOTAX ID?
2. Why do some, but not all, of these lines with a GOTAX ID also contain a source="PMID:nnnn"? [these lines wrapped when I copied them into the ticket, but they are single lines in the go-edit.obo file].
3. Why does a single NCBITaxon ID have multiple GOTAX IDs?
4. What are GOTAX IDs and what purpose do they serve, especially considering that they are not present for every use of an individual NCBITaxon ID, and there are multiple different GOTAX IDs referred to for an individual NCBITaxon ID?

These seem really odd, and are NOT mentioned in the instructions for adding a taxon restriction: http://wiki.geneontology.org/index.php/Adding_Taxon_Restrictions

> relationship: never_in_taxon NCBITaxon:33090 ! Viridiplantae
> relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0000520"} ! Viridiplantae
> relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0010012"} ! Viridiplantae
> relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0010013"} ! Viridiplantae
> relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0010014"} ! Viridiplantae
> relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0010030"} ! Viridiplantae
> relationship: never_in_taxon NCBITaxon:33090 {id="GOTAX:0010036"} ! Viridiplantae

> relationship: never_in_taxon NCBITaxon:33208 ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000039"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000457"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000468"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000469"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000470"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000471"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000472"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000473"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000474"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000475"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000476"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000477"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000478"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000479"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000480", source="PMID:21311032"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000491", source="PMID:21311032"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000492", source="PMID:21311032"} ! Metazoa
> relationship: never_in_taxon NCBITaxon:33208 {id="GOTAX:0000493", source="PMID:21311032"} ! Metazoa

> relationship: only_in_taxon NCBITaxon:7742 ! Vertebrata <Metazoa>
> relationship: only_in_taxon NCBITaxon:7742 {id="GOTAX:0000430"} ! Vertebrata <Metazoa>
> relationship: only_in_taxon NCBITaxon:7742 {id="GOTAX:0000481"} ! Vertebrata <Metazoa>
> relationship: only_in_taxon NCBITaxon:7742 {id="GOTAX:0000494"} ! Vertebrata <Metazoa>
> relationship: only_in_taxon NCBITaxon:7742 {id="GOTAX:0000495"} ! Vertebrata <Metazoa>

**Comment by ValWood** [comment]
This might be the reason that some taxon IDs don't show in QuickGO

see #16048 
laminin binding taxon constraint does not show in QuiCKGO
https://www.ebi.ac.uk/QuickGO/term/GO:0043236


and it makes it through to our curation tool.
Is there a problem with this (syntax or something?)

@cmungall  ?

**Comment by ValWood** [comment]
Although unlikely because this one is
GO:0043236 laminin binding - already had:
never_in_taxon NCBITaxon:4751 ! Fungi

@kimrutherford 
@tonysawfordebi 

I'm stumped...

**Comment by ValWood** [comment]
@kimrutherford could you check if there is any such taxon constaint for
GO:0043236 laminin binding - already had:
never_in_taxon NCBITaxon:4751 ! Fungi
in the file we are consuming?

thanks

**Comment by tonysawfordebi** [comment]
GOTAX IDs are a legacy artefact from the early days of taxon constraints. In the dim & distant, every taxon constraint had its own (manually-assigned) GOTAX ID, but this hasn't been necessary for quite some time, and they can actually be removed.

**Comment by ValWood** [comment]
@tonysawfordebi  any ideas why 
GO:0043236 laminin binding - never_in_taxon NCBITaxon:4751 ! Fungi
does not appear in QUickGO?

(It's probably the same reason we  recognise it in Canto)

**Comment by tonysawfordebi** [comment]
It looks like that constraint is not present in http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json which is where we pick all taxon constraints up from.

**Comment by ValWood** [comment]
Thanks! That is the problem!

**Comment by kimrutherford** [comment]
> @kimrutherford could you check if there is any such taxon constaint for
> GO:0043236 laminin binding - already had:
> never_in_taxon NCBITaxon:4751 ! Fungi

There is no constraint in go-plus.owl.  When was it added?

**Comment by pgaudet** [comment]
Added to editor's discussion to find out what we should do about this.

**Comment by ValWood** [comment]
Did you find out what the issue is here?
I think this might be why we still don't get some of the taxon restrictions....

**Comment by pgaudet** [comment]
No, we didn't discuss it (and I suspect @cmungall is the one who knows the answer, he wasn't there).

**Comment by cmungall** [comment]
> No, we didn't discuss it (and I suspect @cmungall is the one who knows the answer, he wasn't there).

@tonysawfordebi said earlier:

> GOTAX IDs are a legacy artefact from the early days of taxon constraints. In the dim & distant, every taxon constraint had its own (manually-assigned) GOTAX ID, but this hasn't been necessary for quite some time, and they can actually be removed.

Note also these are axiom annotations

**Comment by pgaudet** [comment]
OK - so they can be removed, as @tonysawfordebi said ? 

I dont understand the implications of the fact that they are axiom annotations. 

Thanks for your response. 

Pascale

**Comment by ValWood** [comment]
Does some additional/different syntax constraint need to be added instead?
These taxon constraints are not visible to us ((in Canto)

**Comment by ValWood** [comment]
Can you discuss on you next editors call. We think this might be at the root of some of the 
taxon issues we are seeing at PomBAse,

tks

Val

**Comment by cmungall** [comment]
axiom annotations are ignored for reasoning

it's possible that old ontology tools, such as the chado ontology loader I wrote many moons ago, will have issues with axiom annotations. What are the issues? It looks like we got the taxon slim working, is this separate?

**Comment by kimrutherford** [comment]
> it's possible that old ontology tools, such as the chado ontology loader I wrote many moons ago, will
> have issues with axiom annotations.

We use owltools to make a taxon restricted OBO file for Canto.

> But we do see "lamin binding"

Yep, I just checked and that term is still in our OBO file for loading into Canto.

**Comment by pgaudet** [comment]
Right now, laminin binding has this: 


[Term]
id: GO:0043236
name: laminin binding
namespace: molecular_function
alt_id: GO:0043238
alt_id: GO:0043239
def: "Interacting selectively and non-covalently with laminins, glycoproteins that are major constituents of the basement membrane of cells." [GOC:ecd]
synonym: "laminin-2 binding" NARROW []
synonym: "laminin-4 binding" NARROW []
is_a: GO:0005515 ! protein binding
is_a: GO:0050840 ! extracellular matrix binding
relationship: never_in_taxon NCBITaxon:4751 ! Fungi

**Comment by ValWood** [comment]
@kimrutherford  are we definitely excluding 
relationship: never_in_taxon NCBITaxon:4751 ! Fungi
Is this taxon constraint in the obo file ?

**Comment by ValWood** [comment]
OK sorry I was typing lamin. Laminin IS taxon restricted.

**Comment by pgaudet** [comment]
From the editors' call:
@cmungall will remove the id="GOTAX:..."

**Comment by kimrutherford** [comment]
> > But we do see "lamin binding"
> Yep, I just checked and that term is still in our OBO file for loading into Canto.

"lamin binding" is in the pombe-only OBO file, but "laminin binding" is not.  So all good now?

**Comment by pgaudet** [comment]
> "lamin binding" is in the pombe-only OBO file, but "laminin binding" is not. So all good now?

Yes - Lamin binding should be there. All good.

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/commit/47e90641b6743c897821cf280eb2ce057d32c427
