### ISSUE TITLE
 mitochondrial  membrane insertion and import process  terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16170]
protein insertion into mitochondrial membrane from inner side (GO:0032979)

The process in which a protein is incorporated into the mitochondrial membrane from the inner side. This includes membrane insertion of newly synthesized mitochondrially-encoded proteins, and insertion of nuclear-encoded proteins after their import into the mitochondrial matrix.

This term is clearly for  insertion into the inner membrane (based on the mention of "from the matrix"

could it be renamed to 
protein insertion into mitochondrial inner membrane from matrix side (GO:0032979)

- [x]  revised def

The process in which a protein is incorporated into the mitochondrial *inner*  membrane from the *matrix*  side. This includes membrane insertion of newly synthesized mitochondrially-encoded proteins, and insertion of nuclear-encoded proteins after their import into the mitochondrial matrix.

**Comment by ValWood** [comment]
Actually maybe  @pgaudet  should do this as its transport related.

This is the process term  to describe "insertases". It might not be needed but I think that is why it was created.

The problem is that insertases are described as transporters
https://www.ebi.ac.uk/QuickGO/term/GO:0032977

but this term is not
https://www.ebi.ac.uk/QuickGO/term/GO:0032979

**Comment by ValWood** [comment]
for reference

![mitochondrial translocases](https://user-images.githubusercontent.com/7359272/43485478-405d690c-9509-11e8-8daf-f922ceb725b6.jpg)

**Comment by ValWood** [comment]
OXA1 is the inner membrane  insertase above.

**Comment by ValWood** [comment]
If you rename I'll discuss the invertase/transport  with Pascale it was one of the outstanding  transport issues. There is an inconsistency  between the function and the process. Just take your name off when you are done with the rename and add me instead.

**Comment by hdrabkin** [comment]
Ok, tweaked name and def; removing myself

**Comment by ValWood** [comment]
GO:0032977    JSON
membrane insertase activity
Molecular Function

Definition (GO:0032977 GONUTS page)
Mediates the integration of proteins into a membrane from the inner side of the membrane. Membrane insertases are highly conserved and include the bacterial YidC family, the plant chloroplast Alb3 family, and the fungal and animal mitochondrial Oxa1/Cox18 family. PMID:14739936

**Comment by pgaudet** [comment]
- 'protein import into mitochondrial inner membrane' -> rename 'protein insertion into mitochondrial inner membrane'
-- add missing parent 
- GO:0032979  protein insertion into mitochondrial inner membrane from matrix side: 
-- removed 'side' from term label
-- added logical definition: transport
 and ('has target start location' some 'mitochondrial matrix')
 and ('has target end location' some 'mitochondrial inner membrane')
 and ('transports or maintains localization of' some protein)
- protein import into mitochondrial outer membrane -> rename 'protein insertion into mitochondrial outer membrane'

**Comment by pgaudet** [comment]
We are making the term     GO:0045039  protein import into mitochondrial inner membrane more general. 

**Old definition:** The process comprising the import of proteins into the mitochondrion from outside the organelle and their insertion into the mitochondrial inner membrane. The translocase of the outer membrane complex mediates the passage of these proteins across the outer membrane, after which they are guided by either of two inner membrane translocase complexes into their final destination in the inner membrane. Source: GOC:mcc, GOC:vw, PMID:18672008

**New definition:**  The processes mediating the insertion of proteins into the mitochondrial inner membrane. Mitochondrial inner membrane proteins can get inserted from the cytosol, by crossing the outer membrane and being guided by an inner membrane translocase complex into their final destination in the inner membrane. Some proteins present in the intermemnrane space can get inserted into the inner mitochondrial membrane. Finally, some proteins are inserted into the inner membrane from the matrix side of the membrane. 

**Old logical definition:** 

**New logical definition:** 
transport
 and ('has target end location' some 'mitochondrial inner membrane')
 and (imports some protein)
and (has_target_start_location some cytosol)
and (results_in_transport_across some 'mitochondrial outer membrane')


transport
 and ('has target end location' some 'mitochondrial inner membrane')
 and (imports some protein)

**Comment by pgaudet** [comment]
@ValWood Is that reflecting what we said ?

**Comment by pgaudet** [comment]
Groups with EXP evidence to 'GO:0045039 protein insertion into mitochondrial inner membrane'
(28)	SGD @srengel 
(7)	UniProt @ggeorghiou @sylvainpoux 
(4)	BHF-UCL @RLovering 
(2)	WB @vanaukenk 

Since we made that term more general, please create a new ticket of you'd like to create a terms that describes protein insertion into mitochondrial inner membrane **via the cytosol**. 

Thanks, Pascale

**Comment by RLovering** [comment]
Does this mean that the annotations will automatically be updated? ie I don't have to do anything? And I have no time to revisit these papers and decide if a more specific term is required. I'm happy with the decision
Ruth

**Comment by pgaudet** [comment]
@RLovering Right - no action needed. 

Thanks, Pascale

**Comment by srengel** [comment]
ok then SGD is leaving all these as is.  :)

**Comment by ValWood** [comment]
I'll just explain a bit of the background to this because it isn't clear for the above.

1. For starters, "some insertion into membrane" terms were described as "import into membrane", so this needed standardizing.

2. These were not connected in the ontology. To bring them together the definition of one term  needed to be "broadened"

@pgaudet  fix sp
***intermemnrane*** space can get inserted 

3. I remembered why the term 
GO:0032979   
protein insertion into mitochondrial inner membrane from matrix 
needed to exist.

It is only required for  Cox18 and Oxa1 (cox18 is another insertase but isn't in the figure above).

These 2 insertases insert proteins from the matrix, but some of these proteins *never* exist  in the cytosol *because* they are mitochondrially transcribed and translated, so the existing term
for "import/insertion" could not be used for these substrates because they were never in the cytosol.

if it is helpful, when I check these, I will make a list of which complexes should be annotated to which term, and circulate. All existing annotations should be correct after the changes (and some were incorrect before them).

So I wouldn't worry about the annotations too much.

The outstanding part of this ticket now is that "insertases" are described as "transporters", but "insertion into membrane" is not defined as "transport". I don't know which is correct, but I *think* I remember Maria Costanza telling me that "insertion" was transport.  If I can find the discussion I will forward it but I guess it is in the old SF tracker somewhere.

**Comment by ValWood** [comment]
@pgaudet  I see you added transport. All seems good.
