### ISSUE TITLE
Move histone (de)acetylase activity under transcription coregulator activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16180]
(this needs to be completed with the help @sylvainpoux and Colin, and anyone else who would like to provide input)

- Proposal:
- GO:0004402: histone acetyltransferase activity: move under coactivator activity
- GO:0004407: histone deacetylase activity: move under corepressor activity

"Acetylation, which occurs normally in a cell, neutralizes the positive charges on the histone by changing amines into amides and decreases the ability of the histones to bind to DNA. This decreased binding allows chromatin expansion, permitting genetic transcription to take place. Histone deacetylases remove those acetyl groups, increasing the positive charge of histone tails and encouraging high-affinity binding between the histones and DNA backbone. The increased DNA binding condenses DNA structure, preventing transcription." 
https://en.wikipedia.org/wiki/Histone_deacetylase

**Comment by srengel** [comment]
Wait, this proposed change makes me uncomfortable.. if we do this, then won’t we be saying that histine acetylation and deacetylation only occurs in the context of transcription?  Histone acetylases and deacetylases only work for regulating transcription? What about DNA repair, etc?

**Comment by krchristie** [comment]
I agree with @srengel that these histone modification enzymes should not be made specific to transcription. My understanding is that these chromatin enzymes also affect DNA replication and repair.

**Comment by sylvainpoux** [comment]
A complex question: chromatin modifiers generally affect a range of processes, such as Transcription regulation, DNA repair and replication etc. Linking chromatin modifications to other processes is therefore unsafe.

The specificity of histone acetylation/deacetylation is that we know that histone acetylation is associated with transcription activation while deacetylation is associated with transcription repression, regardless of positions of modifications. Other modifications have different effects on transcription depending on sites that are modified (H3K4me is associated with gene activation and H3K9me is associated with repression).

**Comment by pgaudet** [comment]
So, perhaps the solution would be to create sub-types of transcription coregulators histone acetylase+deacetylase activity. To think about. 

Low priority.

**Comment by krchristie** [comment]
I know you've already closed this, but for future, it might be tricky to create subtypes of histone acetylase/deacetylase activities with respect to processes like trancription, DNA repair and replication, etc. as I'm under the impression that these chromatin modification enzymes are rather general, i.e. not very specific to any of the downstream processes like transcription or replication.

**Comment by pgaudet** [comment]
Thanks for the comment @krchristie 
If we decide to do this this will be useful. 

Pascale
