### ISSUE TITLE
format of never_in_taxon constraint for GO:0003713 "transcription coactivator activity"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#16191]
Hi @pgaudet - Do I remember correctly that you recently added a taxon constraint for this GO term?

For other reasons, I've been looking at taxon constraints and the syntax of the never_in_taxon constraint for this term is inconsistent with the syntax of all of the other ones, including the ones I just added by following these instructions: http://wiki.geneontology.org/index.php/Adding_Taxon_Restrictions

In this term, the taxon constraint looks like this:
[Term]
id: GO:0003713
name: transcription coactivator activity
namespace: molecular_function
**property_value: never_in_taxon "Bacteria" xsd:string**

In other terms, it looks like this:
[Term]
id: GO:0005055
name: laminin receptor activity
namespace: molecular_function
**relationship: never_in_taxon NCBITaxon:4751 ! Fungi**

**Comment by pgaudet** [comment]
Hi @krchristie It was a mistake, thanks for pointing it out. 

Pascale
