### ISSUE TITLE
NTR: FACT complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16199]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'FACT complex binding' based on
PMID:10682845
(p97 ATPase, an ATPase involved in membrane fusion, interacts with DNA unwinding factor (DUF) that functions in DNA replication.)

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0035101 FACT complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
