### ISSUE TITLE
NTR:  Sec61 translocon complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16198]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'endoplasmic reticulum Sec complex binding' based on
PMID:9792704
(The mechanism underlying cystic fibrosis transmembrane conductance regulator transport from the endoplasmic reticulum to the proteasome includes Sec61beta and a cytosolic, deglycosylated intermediary.)

Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 
How about using GO:0005784 Sec61 translocon complex ? Def: A translocon complex that contains a core heterotrimer of conserved alpha, beta and gamma subunits, and may contain additional proteins (translocon-associated proteins or TRAPs); in budding yeast the core proteins are Sec61p, Sbh1p, and Sss1p. The Sec61 translocon complex functions in cotranslational and posttranslational translocation events.

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
I had a look in more detail and the term you suggested ( GO:0005784 Sec61 translocon complex ) seem to be referring to the right complex. Thanks for pointing me there. I will change the title of the ticket. 

Trying to find details for the one I selected initially (  GO:0031205  endoplasmic reticulum Sec complex ), I found out that the PMID associated with them ( PMID:12158317 ) is not existent or nor recognized by either pubmed or europepmc. 

Thanks,

Penelope

**Comment by pgaudet** [comment]
But you want 'complex binding' and I incorrectly gave you a complex (CC) term. So I think your term request is still valid. 

Pascale

**Comment by pgarmiri** [comment]
Yes, the requests for a  'complex binding' term is still valid but for a different complex (ie. the one you suggested than the one that I initially requested).  :)
I have updated the title accordingly.

**Comment by srengel** [comment]
Aren’t these instances? Why are we making specific binding terms like this? Shouldn’t this be handled with col16?

**Comment by ukemi** [comment]
Hi @srengel 

They aren't instances, but your point is still well-taken. There is discussion here: #16134. I guess since some people can't use column 16, we decided to go ahead and create the terms. We really need to move away from this though. But an annotation to just complex binding without being able to take the accessory data (column 16 in the gaf format) into account seems meaningless to me.

**Comment by hdrabkin** [comment]
@pgarmiri, doe s your request for "Sec61 translocon complex binding" still stand.

**Comment by hdrabkin** [comment]
GO:0106138
