### ISSUE TITLE
NTR: IkappaB kinase complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16195]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'IkappaB kinase complex binding' based on
PMID:12492477
(Mixed lineage kinase LZK and antioxidant protein-1 activate NF-kappaB synergistically.)

Thanks,
Penelope

**Comment by pgaudet** [comment]
GO:0038059 IKKalpha-IKKalpha complex ?

**Comment by pgarmiri** [comment]
Hi @pgaudet , 
it seems that GO:0038059 IKKalpha-IKKalpha complex that you suggested is a different complex. This is a homodimer of IKKalpha (IkappaB kinase alpha).
The IkappaB kinase complex (IκB kinase complex) is composed of three subunits each encoded by a separate gene:
    IKK-α (also known as IKK1) (CHUK)
    IKK-β (also known as IKK2) (IKBKB)
    IKK-γ (also known as NEMO) (IKBKG)

Thanks,

Penelope

**Comment by hdrabkin** [comment]
GO:0106137
