### ISSUE TITLE
NTR: NuA4 histone acetyltransferase complex binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16197]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'NuA4 histone acetyltransferase complex binding' based on
PMID:15528408
(Acetylation by Tip60 is required for selective histone variant exchange at DNA lesions.)

Thanks,
Penelope

**Comment by pgarmiri** [comment]
GO:0035267 NuA4 histone acetyltransferase complex

**Comment by ukemi** [comment]
Added in:
https://github.com/geneontology/go-ontology/pull/16317
