### ISSUE TITLE
NTR: transcription factor TFIID complex binding 

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16196]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'transcription factor TFIID complex binding' based on
PMID:12040021
(Multiprotein bridging factor-1 (MBF-1) is a cofactor for nuclear receptors that regulate lipid metabolism.)

Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 
The term  GO:0001094 TFIID-class transcription factor binding was renamed 'TFIID-class transcription factor complex binding' in #16061, so I think you can use that. 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Thank you @pgaudet!
