### ISSUE TITLE
Obsolete "primary growth" GO:0080189

### ISSUE THREAD

**Issue by selewis** [geneontology/go-ontology#16190]
No annotations to this term
The label is very ambiguous (it only applies to plant structures)

![image](https://user-images.githubusercontent.com/1519120/43660599-580b90da-9714-11e8-852b-38d58902b18b.png)

**Comment by ukemi** [comment]
@tberardini are you ok with this? I'm not sure why we don't have secondary growth. Was it obsoleted?

**Comment by tberardini** [comment]
@ukemi  : We do have 'secondary growth'. http://amigo.geneontology.org/amigo/term/GO:0080117

@selewis : Would a change in primary term label to 'plant primary growth' be enough to retain this term?  Though this term has not been used for annotation, I think this is a legitimate biological process.

**Comment by selewis** [comment]
@tberardini - Yes, I can see keeping it. But as a whole the direct children of growth are a motley assortment of classes without seeming rhyme nor reason. It would be helpful if someone reviewed this area to make it more sensible and intuitive. I'm not sure it's placement in the graph is optimal.

That said, the same is true of the children of DNA repair, and that needs cleanup more urgently.

**Comment by pgaudet** [comment]
Hi @selewis I create projects in the Ontology repo for 'growth' and 'DNA repair' (we should create a few others that come up often). The ontology editors/managers can prioritize these, once ongoing projects are done (ECM + MF refactor/transcription). 

Thanks, Pascale
