### ISSUE TITLE
TPV GO:0045039    protein import into mitochondrial inner membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16203]
Is positioned as transmembrane transport  (i.e through the membrane), but defined as an insertase (inserted into the membrane)

def
The process comprising the import of proteins into the mitochondrion from outside the organelle and their insertion into the mitochondrial inner membrane. The translocase of the outer membrane complex mediates the passage of these proteins across the outer membrane, after which they are guided by either of two inner membrane translocase complexes into their final destination in the inner membrane. PMID:18672008

we have another process term for the insertase:

![insertion](https://user-images.githubusercontent.com/7359272/43741484-6cabe53a-99c6-11e8-9b4e-b1c51c8be3ec.jpg)

**Comment by ValWood** [comment]
....GO:0051204    protein insertion into mitochondrial membrane
The process that results in the incorporation of a protein into a mitochondrial membrane.

so I think we need  to obsolete

GO:0045039 protein import into mitochondrial inner membrane 

recommend
GO:0030150    protein import into mitochondrial matrix
for import across the inner membrane 

and
GO:0051204    protein insertion into mitochondrial membrane

for insertases.

**Comment by pgaudet** [comment]
How about merging GO:0045039 protein import into mitochondrial inner membrane
into 
GO:0051204 protein insertion into mitochondrial membrane ?

**Comment by pgaudet** [comment]
@ValWood I'd like to review the annotations together. 
* GO:0045039 protein import into mitochondrial inner membrane seems correctly annotated, to TIM22 complex proteins and other participants to the import into the inner membrane process. 
(I agree than 'insertion' rather than 'import' sounds more correct)

* GO:0051204 protein insertion into mitochondrial membrane has a child 'protein insertion into mitochondrial membrane from inner side' which seems to mean 'export', so that reduces the meaning its parent might have. 

* what is 'import _across_ the inner membrane' ? 

Thanks, Pascale



'

**Comment by ValWood** [comment]
Let me come back to this one with more details....

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/16170
will be useful in explanation. I  will get to this before we chat on Monday...

**Comment by ValWood** [comment]
Let's look at this one. ....Just need to gather the background stuff...

**Comment by ValWood** [comment]
from
https://www.sciencedirect.com/science/article/pii/S000527281000037X
for reference

![mitochondrial translocases](https://user-images.githubusercontent.com/7359272/43485478-405d690c-9509-11e8-8daf-f922ceb725b6.jpg)

dooes this help? I will try to list the processes.

**Comment by ValWood** [comment]
This is how I understand it:

- TOM is an outermembrane translocase.
It transports proteins *accross* the mitochondrial outer membrane. 
It can be annotated to:
protein import into mitochondrial intermembrane space (GO:0045041)
and, because it functions together with Tim23 to  get proteins into the matrix
it can  should also be annotated to 
protein import into mitochondrial matrix (GO:0030150)

See:
https://www.researchgate.net/publication/10663985_Functional_cooperation_and_separation_of_translocators_in_protein_import_into_mitochondria_the_double-membrane_bounded_organelles/figures?lo=1

Both of these processes are "transmembrane transport"


- [ ] Tim23  is a translocase. It transports proteins across the inner membrane. 

it can be annotated to
protein import into mitochondrial matrix (GO:0030150)
It is also a transmembrane transporter.

Tim23 (or a sub-part) can also function as an insertase (it is multifunctional), by a 'lateral gate - mechanism'.
(depicted by horizontal arrow within the membrane)
See SAM50 has a lateral gate according to model https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5959003/figure/F8/

Note that "membrane insertion"  is not "transmembrane transport". Transmembrane transport is only when both leaflets of the bi-layer are traversed.

Other insertases incluse oxa1  (see figure) and cox18 (not shown in figure). These insert some things into the mitochondrial IM  which have been imported into the matrix. They also insert all  of the mitochondrially encoded proteins into the inner membrane.

The small TIM complexes are " folding chaperones"

SO the problems are.
1. Insertion seems to have 2 terms describing it
GO:0051204 and GO:0045039

2.  Neither the insertases, or the translocases are involved in "targeting" but they have a targeting parent. This should be removed. I think things get targeted to the mitochondria by the SRP receptor, but I'm not sure. Anyways, none of the processes here are 'targeting' but they have a targeting ancestor.

Does that make sense?

**Comment by ValWood** [comment]
The insertase problem is fixed by another ticket
