### ISSUE TITLE
parentage question "DNA replication"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16204]
Is there any obvious reason why "DNA replication" isn't a "cellular component biogenesis"?

**Comment by pgaudet** [comment]
interesting ! Although that sounds strange, I can't think of a reason, based on the rest of the ontology.

**Comment by ValWood** [comment]
regulation of viral replication probably.

Can add to
GO:0033260    nuclear DNA replication
and
GO:0006264    mitochondrial DNA replication
probably?

**Comment by ukemi** [comment]
Is DNA in the cellular component ontology?

**Comment by ValWood** [comment]
no, good point. but presumably there should be some relationship between "DNA replication" and "chromosome" ?

**Comment by pgaudet** [comment]
you mean something like 'chromosome biogenesis'?

**Comment by ukemi** [comment]
Is all DNA in a chromosome? What about plasmids or other extrachromosomal DNA?

**Comment by ValWood** [comment]
let's close this....there was a reason I requested it, but it's not a big deal ATM
