### ISSUE TITLE
Simplify label 'DNA-templated transcriptional preinitiation complex assembly'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16201]
Change label 'DNA-templated transcriptional preinitiation complex assembly' to 
'transcriptional preinitiation complex assembly

(RNA-templated 'preinitiation complex' does not seem to exist) 

@krchristie Is this right ? 

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet - I don't know enough about RNA-templated transcription to say that a PIC does or does not exist for this. Personally, I prefer term names that are less ambiguous. Many times when we make term names simpler and thus potentially ambiguous, it comes back to bite us later when we discover that we have inconsistent annotations.
