### ISSUE TITLE
cytoplasmic located TFs that translocate to nucleus on activation?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16202]
Hi Pascale

I think last week we were talking about the issue of whether new terms were required for TFs such as SMADs that, like nuclear receptors, remain in the cytoplasm until activated and then move to the nucleus. 
The SMADs have:  
GO:0005072 transforming growth factor beta receptor, cytoplasmic mediator activity
| is_a GO:0030618                transforming growth factor beta receptor, pathway-specific cytoplasmic mediator activity 
| is_a GO:0030616                transforming growth factor beta receptor, common-partner cytoplasmic mediator activity 
| is_a GO:0030617                transforming growth factor beta receptor, inhibitory cytoplasmic mediator activity

But maybe is a term for similar but non-SMAD proteins needed?

I'm not sure if there should be a new term to describe these types of proteins, maybe these family specific terms are sufficient? 

But the other issue is should there be a MF term for the proteins that sequester TFs in the cytoplasm? Or can we just call these TF repressors. GO has the Cellular Component term:  
GO:0090569 cytoplasmic transcriptional repressor complex
A protein complex, located in the cytoplasm, that possesses activity that prevents or downregulates transcription. 

Do you think it would be helpful to have a MF term to describe this activity other than protein binding?

I haven't looked at this in any detail, it just came up in our discussion but I think it would be good to resolve this as part of the TF project

Thanks

Ruth

**Comment by pgaudet** [comment]
Hello @RLovering 

Coming back to this - the solution we had agreed on was to use the term 'protein sequestering activity', and I propose that for SMADs you would annotate this to 'occurs in' cytoplasm. 

Does that work ? 


If that's the case I could either obsolete the 4 SMAD terms, or merge them into 'protein sequestering activity'. I am leaning towards obsoletion because I find those MFs very unclear, they would look odd as synonyms. What do you think? 

Thanks, Pascale

**TERMS IMPACTED**: 
GO:0005072 transforming growth factor beta receptor, cytoplasmic mediator activity
| is_a GO:0030618 transforming growth factor beta receptor, pathway-specific cytoplasmic mediator activity
| is_a GO:0030616 transforming growth factor beta receptor, common-partner cytoplasmic mediator activity
| is_a GO:0030617 transforming growth factor beta receptor, inhibitory cytoplasmic mediator activity

**Comment by pgaudet** [comment]
Discussing with @RLovering 

- The I-SMADs should be annotated to 'DNA-binding transcription factor inhibitor activity' (GO:0140416), occurs_in cytoplasm. 
- Others need to be looked at, they are possibly DNA-binding transcription factors (GO:0000981)

and obsolete the 4 terms above. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

GO:0005072 transforming growth factor beta receptor, cytoplasmic mediator activity
and children: GO:0030618 transforming growth factor beta receptor, pathway-specific cytoplasmic mediator activity
GO:0030616 transforming growth factor beta receptor, common-partner cytoplasmic mediator activity
GO:0030617 transforming growth factor beta receptor, inhibitory cytoplasmic mediator activity

The reason for obsoletion is that there are other terms that represent the same functions; for example: 

- GO:0030617 transforming growth factor beta receptor, inhibitory cytoplasmic mediator activity
should be annotated as 'GO:0140416 DNA-binding transcription factor inhibitor activity', occurs_in cytosol
- others may be GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific, or GO:0003712 transcription coregulator activity. 

16 annotations need to be reviewed, see 
https://github.com/geneontology/go-annotation/issues/2858

Group | Number of annotations
-- | --
BHF-UCL | 11
ComplexPortal | 1
FlyBase | 2
WB | 1
PINC | 1

mappings to those terms. Those terms are not present in any subsets.

There are no mappings to those term. Those terms are not present in any subsets.

You can add any comments to the ticket: 
https://github.com/geneontology/go-ontology/issues/16202

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 19th, 2020. Unless objections are received by March 19th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@ukemi I dont think this is in the right project ??

**Comment by ukemi** [comment]
? Feel free to move it then?
