### ISSUE TITLE
Should 'synapse development' be an EXACT synonym of 'synapse organization'?

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16218]
I've just noticed that 'synapse development' is an EXACT synonym of 'synapse organization':

https://www.ebi.ac.uk/QuickGO/term/GO:0050808

Definitions of developmental processes specify that they involve '_progression over time, from formation to mature structure_' (see e.g. https://www.ebi.ac.uk/QuickGO/term/GO:0031175).

I do not think this is in agreement with the definition of 'synapse organization', which is: 'A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, _**or disassembly**_ of a synapse (...)."

I would prefer to change this from an _exact synonym_ to a _related synonym_ unless this should really be an _exact_ synonym? @Pimmelorus or @dosumis perhaps you'd be able to comment? 

@paolaroncaglia would you agree?

cc @RLovering

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 

I agree with your suggested change. The discrepancy probably boils down to the use of the same wording (‘development’) for a cellular component rather than for an anatomical structure, and to the fact that the roles of the synonyms may not apply in the same way in the two branches.

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia, thanks for your comments and explanation.

**Comment by Pimmelorus** [comment]
@BarbaraCzub 
I agree that these are not synonyms. It is more that "synapse development" is part_of "synapse organization" (or maybe is_a).

**Comment by BarbaraCzub** [comment]
Thanks @Pimmelorus
