### ISSUE TITLE
NTR: neuron-glia/glia neuron signalling

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16216]
PMID:16547515 shows that tumour necrosis factor is involved in signalling between glial cells and hippocampal neurons. Signalling from neurons to glial cells has also been demonstrated (PMIDs cited near definitions below).

> GO:0007267   cell-cell signaling
>> New1:	   glial cell-neuron signaling (is_a)
>>> GO:0036520   astrocyte-dopaminergic neuron signaling (is_a)

>>> New2:   glial cell-hippocampal neuron signaling (is_a)

>> New3:   neuron-glial cell signaling (is_a)

Definitions:
GO:0007267 cell-cell signaling
Any process that mediates the transfer of information from one cell to another. This process includes signal transduction in the receiving cell and, where applicable, release of a ligand and any processes that actively facilitate its transport and presentation to the receiving cell. Examples include signaling via soluble ligands, via cell adhesion molecules and via gap junctions.

New1: glial cell-neuron signaling
Cell-cell signaling that mediates the transfer of information from a glial cell to a neuron. PMID:16144764, PMID:16547515, PMID:27788368

New2: glial cell-hippocampal neuron signaling
Cell-cell signaling that mediates the transfer of information from a glial cell to a hippocampal neuron. PMID:16547515

GO:0036520 astrocyte-dopaminergic neuron signaling
Cell-cell signaling that mediates the transfer of information from an astrocyte to a dopaminergic neuron. PMID:12794311 PMID:21752258

New3: neuron-glial cell signaling
Cell-cell signaling that mediates the transfer of information from a neuron to a glial cell. PMID:11399439, PMID:15252819, PMID:27788368

cc
@RLovering 
@paolaroncaglia

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 

Your proposal looks fine, but I have a general concern. This might have been addressed in recent signalling work that I was not involved in, so apologies in advance if this is not a matter of doubt for other editors and curators. I thought that new signalling terms should be added if they are needed to represent biochemical differences in the mechanisms of signalling itself, while cell types between which the signalling occurs should be captured by extensions. Was this discussed previously and resolved one way or another? Asking because your proposed definition do not specify differences in the signalling process other than the cells involved. Looking at all the children of GO:0007267 cell-cell signaling, I do see a handful of terms similar to the ones you’re proposing, so there are indeed precedents, but GO-CAM comes to mind for other terms such as GO:0021937 ‘cerebellar Purkinje cell-granule cell precursor cell signaling involved in regulation of granule cell precursor cell proliferation’ and GO:0060802 ‘epiblast cell-extraembryonic ectoderm cell signaling involved in anterior/posterior axis specification’…

If instead the new cell-cell signalling terms you propose represent novel mechanisms, should they have the additional parent GO:0033209 ‘tumor necrosis factor-mediated signaling pathway’? (“A series of molecular signals initiated by the binding of a tumor necrosis factor to a receptor on the surface of a cell, and ending with regulation of a downstream cellular process, e.g. transcription.”)

Thanks,
Paola

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia, thanks for your feedback. In context of the neuroinflammation field, I believe it would be informative to users of enrichment analysis tools to know whether a protein is involved in signalling from a neuron to a glial cell, or the other way round (not all enrichment tools will include data from annotation extensions). I am not suggesting we should add any complex '[signalling'] (...) involved in (...) [process]' terms, but only specify cell types participating in cell-cell signalling, and the directionality of this communication (like had been done for 'GO:0036520 astrocyte-dopaminergic neuron signaling', on which I based the proposed new term entires). I do not know about novel mechanisms though (but it was certainly not my intention to make any of the suggested terms specific to tumour necrosis factor). Having said that, I've not been involved in any signalling work either, and I am not aware of any guidelines resulting from it. @RLovering would you be able to advise on this? 
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Hi @pgaudet this could certainly be captured with extensions. But would this be useful to end-users? (Not all analysis tools will include data from extensions). And similar (or even much more specific) terms already exist.

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
@pgaudet 
This is a touchy subject, and I myself do not necessarily take one side entirely (in fact, a few months ago I sent @ukemi a user example from a paper showing enrichment for specific ‘binding’ terms). It’d be useful to have clear guidelines, but my understanding is that the general topic is still being debated among GOC members. Perhaps until that is resolved (ha…), allow Barbara to create the intermediate terms New1 (glial cell-neuron signaling) and New3 (neuron-glial cell signaling), do not create the more specific term New2 (glial cell-hippocampal neuron signaling), and leave the existing GO:0036520 (astrocyte-dopaminergic neuron signaling) where it is?

**Comment by BarbaraCzub** [comment]
I like your suggestion @paolaroncaglia . @pgaudet thanks for adding this to our discussion list.

**Comment by BarbaraCzub** [comment]
Decision from today's ontology call: continue this discussion during next week's call.

**Comment by BarbaraCzub** [comment]
Decision from today's ontology call: put this on hold until guidelines for these types of signalling terms are agreed at the next GOC meeting.

**Comment by BarbaraCzub** [comment]
Hello, @pgaudet, I was wondering whether there have been any updates on the GO guidelines regarding cell-cell signalling?
@RLovering and I discussed this with a panel of neuroscience expert advisors during our project meeting last month. The neuroscientists advised that 'glial cell-neuron signaling' and 'neuron-glial cell signaling' are high-level terms, not specifying the types of neurons, or types of glial cells, involved. They emphasised they would find it helpful to see these terms in their enrichment analysis (rather than seeing the much more vague 'cell-cell signalling') since annotation extensions are generally not shown in analyses results. 
The experts agreed that more specific terms describing types of glia, e.g., microglia, astrocytes, oligodendrocytes, or Schwann cells, etc., or types of neurons, e.g., pyramidal, bipolar, Purkinje, or dopaminergic, etc., might not be required. However, the high-level terms like 'glial cell-neuron signaling' and 'neuron-glial cell signaling' should exit in GO.
Our current annotation project focuses on microglial proteins and neuroinflammation, and so the captured processes entail a lot of 'glial cell-neuron signaling' and 'neuron-glial cell signaling'. In view of this, as well as based on the outlook of the neuroscience experts and their research needs, I would like to add these two terms to the ontology, if no further guidelines have been outlined?

**Comment by pgaudet** [comment]
I think I asked separately (at least I dont see the comment here): can you define what makes these processes different ? Are there different pathways/molecules/modules involved? Or is it the same pathway being used by different combinations of cells ? 

@thomaspd @vanaukenk @ukemi any thoughts on that one?

**Comment by BarbaraCzub** [comment]
The process can involve different pathways or molecules depending on which tissues they occur in. E.g. during development microglia signal to neurons to trigger apoptosis. This involves different signalling molecules in different parts of the nervous system: "In the developing retina, the neuronal death studied in eye explants results from the production of NGF by invading microglia (Frade and Barde, 1998). In spinal cord explants, microglial tumor necrosis factor α (TNFα) commits differentiating motoneurons to die unless they are rescued by muscle-derived trophic factors (Sedel et al., 2004). In developing cerebellar slices, microglia induce Purkinje cell apoptosis by releasing superoxide ions produced by a respiratory burst (Marín-Teva et al., 2004)." (http://www.jneurosci.org/content/28/32/8138.long)
So for a complete annotation it would be necessary to capture both: the cell types involved as well as the singalling molecules mediating their communication. The reason why our neurological panel advised we should make these GO terms (specifying the high-level cell types like neurons and glia) available is that it is more informative for users of enrichment analyses to see whether a molecule is involved in singaling from a glial cell to a neuron, or from a neuron to a glial cell, than just from 'cell to cell'. @RLovering would you like to add any further comments?

**Comment by RLovering** [comment]
I agree with Barbara and that this was the advise from our advisory panel. 

I also want to point out that Barbara is not requesting terms for every specific cell type. She is requesting terms for commonly used grouping 'terms' for cells. For example there are 45 specific cell types listed as child terms of 'glial cell' in CL: CL_0000125. There is currently no way to group the cell type information included in the AE or Noctua annotations, consequently if someone wanted to identify all the annotations associated with cell-cell interactions that are relevant to glial cells they would need to paste 45 IDs into the search field. But this still would not help those using GO to analyse their HTP data.

**Comment by pgaudet** [comment]
Sounds good. I'd be useful if you could make definitions that describe how the different processes differ, rather than just naming the two cell types. 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
I'll include as much detail as I will be able to extract from the relevant references.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
New_I: glial cell-neuron signaling
Cell-cell signaling that mediates the transfer of information from a glial cell to a neuron. This signaling has been shown to be mediated by various molecules, depending on which glial cells release them, and in which tissues the signalling occurs, e.g. microglial cell-derived nerve growth factor (NGF) in the retina, or microglial cell-derived superoxide ions in the cerebellum. PMID:9459440, PMID:14980203, PMID:16144764, PMID:16547515, PMID:18685038, PMID:27788368.

New_II: neuron-glial cell signaling
Cell-cell signaling that mediates the transfer of information from a neuron to a glial cell. This signalling has been shown to be mediated by various molecules released by different types of neurons, e.g. glutamate, γ-amino butyric acid (GABA), noradrenaline, acetylcholine, dopamine and adenosine. PMID:10195197, PMID:10196584, PMID:10377338, PMID:10493741, PMID:11356870, PMID:11399439, PMID:15252819, PMID:27788368.
