### ISSUE TITLE
NTR: P-TEFb complex binding 

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16213]
Hi,

From annotation review ticket (co-localizes_with complex terms): geneontology/go-annotation#1940

I need a term to indicate 'P-TEFb complex binding' based on
PMID:18391197 
(TFIID component TAF7 functionally interacts with both TFIIH and P-TEFb. )

Thanks,
Penelope

**Comment by ukemi** [comment]
Hi @pgarmiri 

It would make it a little easier for us if you could include the name and identifier of the complex terms in these requests. It saves us having to look them up when creating logical definitions.

**Comment by hdrabkin** [comment]
GO:0106140  P-TEFb complex binding
