### ISSUE TITLE
new term request: phloem unloading

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16226]
Name: phloem unloading
Definition: The process of unloading sucrose that is produced in the source tissues, from the sieve tube or companion cell of the phloem into the sink tissues.

Parentage: is a GO:0015770 sucrose transport
Source: kinda text book plant physiology. Can it be GOC:lr?

**Comment by vanaukenk** [comment]
@lreiser 
It'd be good to actually add a published paper (could be a review) or textbook to support the term definition.  This helps if we ever need to review a term, for example, to make sure it has been used consistently for annotation.
Even a reference for the paper you are using for annotation would be fine.  
Thx.

**Comment by lreiser** [comment]
Okey dokey....here is the PMID:30018170

**Comment by vanaukenk** [comment]
Thanks for the reference @lreiser.
Would it be okay to actually have the existing phloem loading and proposed phloem unloading terms be direct children of the more specific 'sucrose transmembrane transport'?

**Comment by lreiser** [comment]
@vanaukenk I used the generic term  because some types of phloem unloading involve movement through plasmadesma (pores sort  of like nuclear pores) but it is definitely sometimes (or very  often) an instance of sucrose transmembrane transport. So biologically correct.

**Comment by vanaukenk** [comment]
Okay, thanks; I'll make the parentage as you initially suggested.

**Comment by lreiser** [comment]
Actually .. hold off... I think my definition of phloem unloading is actually too narrow- there are other things besides sucrose that are moved via  long distance transport in plants - other solutes like amino acids. 
so this term:
phloem unloading: The movement of solutes (e.g. sucrose or amino acids), that are produced in the source tissues, from the sieve tube or companion cell of the phloem, into the sink tissues.

would have as a child:
phloem sucrose unloading: the movement of sucrose  that is produced in the source tissues, from the sieve tube or companion cell of the phloem, into the sink tissues.

which would also be an instance of sucrose transmembrane transport.

there is also
GO:0010233 phloem transport
so an instance of that.

**Comment by lreiser** [comment]
I should have dug around earlier and then would have found all the terms

 so
phloem unloading is  an instance of phloem transport
phloem unloading has a type: phloem sucrose unloading

phloem sucrose unloading is a type of sucrose transport
sort of like this example from the loading aspect....
GO:0010232 vascular transport
                   
                     [is_a relation] GO:0010233 phloem transport
                         [Current term] GO:0090408 phloem nitrate loading

**Comment by vanaukenk** [comment]
@lreiser looking at this again, do we also need a term for phloem loading?

Currently, 'phloem loading' is a broad synonym of GO:0009915 'phloem sucrose loading' and GO:0090408 'phloem nitrate loading' but if we create a new term for 'phloem unloading' then it seems  that we should also create a 'phloem loading' parent for the existing, more specific phloem loading terms in order to be consistent.  We would then remove 'phloem loading' as a broad synonym of those child terms.

**Comment by lreiser** [comment]
Hi @vanaukenk , I conferred with @tberardini and we suggest the following

1. Remove phloem loading as a synonym of phloem sucrose loading and phloem nitrate loading (GO:0090408 ). 
2. Add phloem loading as its own term (child of phloem transport) with the definition: The process of loading solutes into the sieve tube or companion cell of the phloem for long distance transport from source to sink.
3. Revise the definition of phloem transport (GO:0010233) The directed movement of substances, into, out of or within the phloem during long distance transport between source  and sink tissues. 
4. Add 'phloem unloading' as above as a child of phloem transport (part of?). 
5. Add child term 'phloem sucrose unloading' which is also a child of sucrose transport.


>phloem transport (exists)
  ->phloem loading (new)
  ->phloem unloading (new)
   -->phloem sucrose unloading (new: also isa  sucrose transport)

leonore

**Comment by vanaukenk** [comment]
Thanks @lreiser @tberardini   That all makes sense.

For the new phloem loading term, and the existing phloem transport term, it would be nice to also include a reference.  I found the review below , but if there is a more recent one, I'm happy to use it instead:

https://www.ncbi.nlm.nih.gov/pubmed/19025382

**Comment by lreiser** [comment]
@vanaukenk , did the terms get added?
Do you need any thing more from me  ? I think the reference is fine.

**Comment by vanaukenk** [comment]
@lreiser - sorry for the delay.  Here's the new structure of the ontology I have in my notes for this ticket:

GO:0010233 phloem transport
- GO:new phloem loading
--GO:0090448 phloem glucosinolate loading
--GO:0090408 phloem nitrate loading
--GO:0009915 phloem sucrose loading
-GO:new phloem unloading
--GO:new phloem sucrose unloading
-GO:1990388 xylem-to-phloem iron transport

GO:0015770  sucrose transport
- GO:0009915 phloem sucrose loading
- GO:new phloem sucrose unloading

GO:1901349 glucosinolate transport
- GO:0090448 phloem glucosinolate loading
 
The latter is_a relation for glucosinolate transport and phloem glucosinolate transport does not exist in the ontology currently, so I was going to add it.

Definitions

phloem loading
The process of loading solutes into the sieve tube or companion cell of the phloem for long distance transport from source to sink.

phloem unloading
The process of unloading sucrose that is produced in the source tissues, from the sieve tube or companion cell of the phloem into the sink tissues.

phloem transport
The directed movement of substances, into, out of or within the phloem during long distance transport between source and sink tissues.

**Comment by vanaukenk** [comment]
@lreiser - these terms are now in, and the parentage, defs, and synonyms cleaned up.
