### ISSUE TITLE
NTR: flavin prenyltransferase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#16228]
Proposed definition: Catalysis of the reaction: dimethylallylphosphate + FMNH2 = prenylated FMNH2 + phosphate.  EC reaction 2.5.1.129.  Proposed parent: GO:0004659 prenyltransferase activity.  Publication: PMID 26083743.

Thanks,
Ingrid

**Comment by ukemi** [comment]
Be sure to look for a Rhea xref.

**Comment by hdrabkin** [comment]
Thanks @deustp01 
GO:0106141 flavin prenyltransferase activity
