### ISSUE TITLE
'regulation of synaptic scaling' - new term or synonym?

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16222]
It is stated in PMID:16547515 that:

> "Two general forms of synaptic plasticity that operate on different
timescales are thought to contribute to the activity-dependent
refinement of neural circuitry during development: (1) long-term
potentiation (LTP) and long-term depression (LTD), which
involve rapid adjustments in the strengths of individual synapses
in response to specific patterns of correlated synaptic activity, and
(2) homeostatic synaptic scaling, which entails uniform adjustments
in the strength of all synapses on a cell in response to
prolonged changes in the cell’s electrical activity [PMID:14630218, PMID:14735113]."

In GO we certainly have GO terms for (1). But do we have GO terms for (2)?

Experiments presented in PMID:16547515 show that:
> "(...) synaptic scaling in
response to prolonged blockade of activity is mediated by the
pro-inflammatory cytokine tumour-necrosis factor-a (TNF-a).
Using mixtures of wild-type and TNF-a-deficient neurons and
glia, we also show that glia are the source of the TNF-a that is
required for this form of synaptic scaling."

In order to capture the role of TNF in this regulation of synaptic scaling, I wanted to suggest a new term:
> New1: regulation of synaptic scaling
Suggested definition: "A process that modulates synaptic scaling. Synaptic scaling is a form of synaptic plasticity, which entails uniform adjustments in the strength of all synapses on a cell in response to prolonged changes in the cell’s electrical activity."
PMID:14630218, PMID:14735113, PMID:16547515.
Related synonym: regulation of homeostatic synaptic scaling

But then, while browsing the ontology for a suitable parent term, I came across 'GO:0031916 regulation of synaptic metaplasticity', and started wondering whether the two terms would describe the same process.
> 'GO:0031916 regulation of synaptic metaplasticity'
Defined as: "A process that modulates synaptic metaplasticity. Metaplasticity is a higher-order form of plasticity and is manifest as a change in the ability to induce subsequent synaptic plasticity that is the ability of synapses to change as circumstances require." [PMID:8658594].

['GO:0031916 regulation of synaptic metaplasticity'](https://www.ebi.ac.uk/QuickGO/term/GO:0031916) is quite an old term (added to GO in 2005 ), it does not have any annotations associated with it, and the cited PMID is an opinion article, not a research article. But I wonder whether the new term I wanted to suggest should actually be a synonym of GO:0031916?

A PubMed search reveals that both phrases have recently been in use: 

https://www.ncbi.nlm.nih.gov/pubmed/?term=synaptic+metaplasticity
https://www.ncbi.nlm.nih.gov/pubmed/?term=synaptic+scaling

@paolaroncaglia could you perhaps share your thoughts on this?

Thanks,
Barbara

cc @RLovering 

This issue is based on the same research article as this 'cell-cell signalling' NTR: https://github.com/geneontology/go-ontology/issues/16216

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
The definition of homeostatic synaptic scaling from the publication you mention sounds more granular (or different anyway) than the one of the existing term ’regulation of synaptic metaplasticity’. Therefore I would not connect the two, and I’d make your suggested new term a child of GO:0048167 ‘regulation of synaptic plasticity’. You may also want to add ‘homeostatic synaptic scaling’ as a related synonym (in addition to ‘regulation of…’ as you suggest).

A related note: looking at the children of GO:0048167 ‘regulation of synaptic plasticity’, the class labels may benefit from a bit more consistency, i.e. ‘regulation of long term synaptic depression’ should be edited to ‘regulation of long-term synaptic depression’, and ’long term synaptic depression’ to ‘long-term synaptic depression’. Their descendants should be checked for consistency, too. The old labels should be kept as synonyms. 

Thanks!
Paola

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia thanks for sharing your thoughts on this. I'll follow your advice, and add this as a new term, as well as add the related synonyms. I'll also review labels of children of GO:0048167 ‘regulation of synaptic plasticity’ for consistency, as you suggest.
Thank you,
Barbara
