### ISSUE TITLE
Merge 'ferric iron transmembrane transport' into  'ferric iron import across plasma membrane'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16236]
This ticket #14892 will lead to a lot of changes, so I am trying to split up some sub-issues.

Merge 'GO:0015683 ferric iron transmembrane transport'
into 
'GO:0098706 ferric iron import across plasma membrane'
+ add taxon restriction 'only in bacteria'. 

- Only bacteria can transport ferric iron (3+) across membranes(PMID:24312900); in mammalian cells (and in fungus) ferric iron is internalized by endocytosis, and reduced to ferrous iron (2+) for intracellular (ie mitochondrial) transport. 

Tagging @ValWood @RLovering for input since you have commented on the other ticket; but comments by everyone is welcome. 

Thanks, Pascale

**Comment by ValWood** [comment]
This makes sense to me....
PomBase have no annotations to either term...

**Comment by pgaudet** [comment]
Also need to change the reference: PMID:8321236 talks about reductive iron transport

**Comment by pgaudet** [comment]
Added comment 
"In most organisms, ferric iron (3+) is reduced to ferrous iron (2+) before being transported into the cell. Some infectuous bacteria can extract the ferric iron bound to the the host's transferrin and transport it via a transmembrane transporter (for example, TbpAB of N. meningitidis and N. gonorrheae)."

**Comment by pgaudet** [comment]
@marcfeuermann Can we review this together ? 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/4782928/44084553-518c6332-9fb7-11e8-869a-98dd809cccc7.png">

**Comment by RLovering** [comment]
Based on the figure I added to the previous ticket I agree that transmembrane transport of Fe+ does not occur in mammals. 
However, Fe3+ does get into the cells by endocytosis, but does not cross the membrane until it is reduced to Fe2+. Hopefully a BP term will be available for the proteins that are responsible for the endocytosis of Fe3+
Thanks
Ruth

**Comment by pgaudet** [comment]
@RLovering yes, of course.

**Comment by pgaudet** [comment]
Hi @amandamackie

Based on the papers you provided in https://github.com/geneontology/go-annotation/issues/2054#issuecomment-413070749

I now wonder if there is such as thing a transmembrane transport or ferric iron; do you know ? It looks like ferric iron is only transported in complex with sideriphores, is this right ? 

@jimhu-tamu @dsiegele Comments ? 

If there are no instances of ferric acid TM transport I will obsolete the terms.

Thanks, Pascale

**Comment by dsiegele** [comment]
Hi Pascale,

There are examples of ferrous (Fe2+) and ferric (Fe3+) transmembrane transport systems among the bacteria, which are used to transport iron across the plasma membrane.

transmembrane transport of Fe3+:
Miethke M. 
Molecular strategies of microbial iron assimilation: from high-affinity complexes to cofactor assembly systems. 
Metallomics. 2013 Jan;5(1):15-28. PMID: 23192658 doi: 10.1039/c2mt20193c.
     This system has an outer membrane protein that is able to take iron away from ferritin or lactoferrin and transport it to a Fe3+ binding protein in the periplasm. The periplasmic protein then delivers the Fe3+ to a transport system located in the cytoplasmic membrane.

transmembrane transport of Fe2+:
Cheryl K. Y. Lau  Karla D. Krewulak  Hans J. Vogel
Bacterial ferrous iron transport: the Feo system
FEMS Microbiology Reviews, Volume 40, Issue 2, 1 March 2016, Pages 273–298, https://doi.org/10.1093/femsre/fuv049

In the archaea, there are examples of predicted transmembrane transport of Fe2+ based on sequence similarity to the bacterial Feo system. I haven't looked for articles with experimental evidence.
Leyn SA, Rodionov DA. 
Comparative genomics of DtxR family regulons for metal homeostasis in Archaea.
J Bacteriol. 2015 Feb;197(3):451-8. doi: 10.1128/JB.02386-14. PMID: 25404694

**Comment by pgaudet** [comment]
Thanks @dsiegele this is very useful. 

The 'transmembrane transport' term would also allow to annotate Fe3+ export (ie to an 'export' child that is no in the ontology), but I don't think this exists; do you know? 

Thanks, Pascale

**Comment by pgaudet** [comment]
* Merged terms
* Changed label:  ferric iron import across cell outer membrane
* Changed definition: The directed movement of ferric iron (Fe(III) or Fe3+) ions from outside of a cell, across the cell outer membrane and into the periplasmic space."
* Added comment: 
Ferric iron is rarely transported in the free form. Some bacteria have a system in which an outer membrane protein takes iron away from host ferritin or lactoferrin and transport it to a Fe3+ binding protein in the periplasm. The periplasmic protein then delivers the Fe3+ to a transport system located in the cytoplasmic membrane. Consider also GO:0015891     siderophore transport. 
* Added taxon constraint: only_in_taxon some Bacteria

I will leave the ticket open until the rest of the changes in this branch are done, so I can update the comment to include the other mechanisms of transport.

**Comment by pgaudet** [comment]
Moved comment to MF 'GO:0015091 ferric iron transmembrane transporter activity'
