### ISSUE TITLE
Travis builds are taking over 30 minutes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16232]
Carried on from https://github.com/geneontology/go-site/issues/760

We absolutely need to bring this down

**Comment by cmungall** [comment]
I suspect this is the report step

see for example:

```
2018-08-09 13:06:33,219 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(<http://purl.obolibrary.org/obo/NCBITaxon_11593> owl:Thin
g), referencedObject=<http://purl.obolibrary.org/obo/NCBITaxon_11593>, category=DEPRECATED]
ROBOT_JAVA_ARGS=-Xmx8G robot verify --input go-edit.obo --queries  ../sparql/equivalent-classes-violation.sparql  ../sparql/trailing-whitespace-violation.sparql  ../sparql/owldef-self-referen
ce-violation.sparql  ../sparql/synonym-label-match-violation.sparql  ../sparql/replacedby-obsolete-violation.sparql  ../sparql/duplicate-exact-synonym-violation.sparql  ../sparql/duplicate-sy
nonym-violation.sparql -O reports/
PASS Rule ../sparql/equivalent-classes-violation.sparql: 0 violation(s)
PASS Rule ../sparql/trailing-whitespace-violation.sparql: 0 violation(s)
PASS Rule ../sparql/owldef-self-reference-violation.sparql: 0 violation(s)
PASS Rule ../sparql/synonym-label-match-violation.sparql: 0 violation(s)
PASS Rule ../sparql/replacedby-obsolete-violation.sparql: 0 violation(s)
PASS Rule ../sparql/duplicate-exact-synonym-violation.sparql: 0 violation(s)
PASS Rule ../sparql/duplicate-synonym-violation.sparql: 0 violation(s)
ROBOT_JAVA_ARGS=-Xmx8G robot verify --input reasoned.owl --queries ../sparql/multiple-class-links-violation.sparql -O reports/
PASS Rule ../sparql/multiple-class-links-violation.sparql: 0 violation(s)
ROBOT_JAVA_ARGS=-Xmx8G robot merge --input go-edit.obo verify --queries ../sparql/obsolete-reference-violation.sparql -O reports/
PASS Rule ../sparql/obsolete-reference-violation.sparql: 0 violation(s)
wget http://purl.obolibrary.org/obo/go.obo -O go-lastrelease.owl && touch go-lastrelease.owl
--2018-08-09 13:25:32--  http://purl.obolibrary.org/obo/go.obo
Resolving purl.obolibrary.org (purl.obolibrary.org)... 52.3.123.63
Connecting to purl.obolibrary.org (purl.obolibrary.org)|52.3.123.63|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://snapshot.geneontology.org/ontology/go.obo [following]
```

@dougli1sqrd - we need individual timings per command to better debug

Note also that many of the SPARQL checks we run are now defaults in [robot report](http://robot.obolibrary.org/report) with the v1.1.0 release, which is now included in the odkfull docker container. We will want to switch to this later after testing it for timings

**Comment by dougli1sqrd** [comment]
Can you install `ts` on your cmungall/oort image? `ts` will print a timestamp for a given bash line.
https://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command

**Comment by dougli1sqrd** [comment]
Also, we have this from a while ago: https://github.com/geneontology/go-ontology/pull/15284

**Comment by dougli1sqrd** [comment]
I'm getting:
```
ROBOT_JAVA_ARGS=-Xmx8G robot reason -i enhanced.owl -r ELK -e asserted-only relax reduce annotate -V http://purl.obolibrary.org/obo/go/releases/`date +%Y-%m-%d`/go.owl -o reasoned.owl
```
as taking 10 minutes.

**Comment by dougli1sqrd** [comment]
When I run robot verify locally in docker, I see it taking 41 seconds.

**Comment by cmungall** [comment]
Thanks!

Note the cmungall/oort image has been supplanted by obolibrary/odkfull

See
https://github.com/INCATools/ontology-development-kit/tree/master/docker/odkfull

Do you want to make a PR here?

https://github.com/INCATools/ontology-development-kit/blob/master/template/src/ontology/run.sh

From the other linked ticket, it seems reduce may be a culprit - there's no reason to run this for test purposes (but it's vital for the published version), but it may be tricky to make this step vary depending on test vs releases. May be algorithmic improvements we can make

The robot verify step definitely seems to be taking a while on some travis builds...

**Comment by cmungall** [comment]
Oh, deja vu

Hyeongsik previously optimized reduce:
https://github.com/ontodev/robot/pull/270

I wonder if your timings are to do with using an old docker image that predated this  fix? (note that odkfull is now tied to explicit robot releases making all this a bit more predictable)

OK, looking at the PR you linked to

https://github.com/geneontology/go-ontology/pull/15284/files

It looks like you added something to add reporting already, but this PR was maybe closed prematurely? Up to you whether to go with ts or the simple bash script in this PR

**Comment by dougli1sqrd** [comment]
I like the idea of using `ts` a little more than `time`. So I can add `ts` package to the Dockerfile, update run.sh in go-ontology to use the new image.

**Comment by pgaudet** [comment]
My builds are still failing. You can see errors 
https://travis-ci.org/geneontology/go-ontology/builds/414805741?utm_source=github_status&utm_medium=notification
(errors like
https://travis-ci.org/geneontology/go-ontology/builds/414805741?utm_source=github_status&utm_medium=notification)

https://travis-ci.org/geneontology/go-ontology/builds/414432843?utm_source=github_status&utm_medium=notification
(45 minutes time out error, but this comes before 45 minutes). 

Thanks, Pascale

**Comment by cmungall** [comment]
Update

 - @dougli1sqrd will determine which operations take most time
 - @balhoff will profile and suggest optimizations

**Comment by balhoff** [comment]
Here are some timings extracted from Travis for [a pull request](#16239) today:

```
ROBOT_JAVA_ARGS=-Xmx8G robot query -i go-edit.obo --construct ../sparql/constructDisjointInTaxon.sparql disjoint_in_taxon.owl -f ttl
real	0m44.927s
user	1m13.772s
sys	0m1.872s


OWLTOOLS_MEMORY=8G owltools --use-catalog go-edit.obo disjoint_in_taxon.owl --merge-support-ontologies -o enhanced.owl
2018-08-13 16:31:37,754 WARN  (OBOFormatParser:1505) LINE: 460979 accepting bad xref with spaces:<MetaCyc: RXN-15910>  LINE:
real	0m39.476s
user	1m6.260s
sys	0m1.668s


ROBOT_JAVA_ARGS=-Xmx8G robot reason -i enhanced.owl -r ELK -e asserted-only relax reduce annotate -V http://purl.obolibrary.org/obo/go/releases/`date +%Y-%m-%d`/go.owl -o reasoned.owl
real	1m47.505s
user	2m46.776s
sys	0m2.480s


ROBOT_JAVA_ARGS=-Xmx8G robot verify --input go-edit.obo --queries  ../sparql/equivalent-classes-violation.sparql  ../sparql/trailing-whitespace-violation.sparql  ../sparql/owldef-self-reference-violation.sparql  ../sparql/synonym-label-match-violation.sparql  ../sparql/replacedby-obsolete-violation.sparql  ../sparql/duplicate-exact-synonym-violation.sparql  ../sparql/duplicate-synonym-violation.sparql -O reports/
real	0m56.515s
user	1m33.732s
sys	0m1.376s


ROBOT_JAVA_ARGS=-Xmx8G robot verify --input reasoned.owl --queries ../sparql/multiple-class-links-violation.sparql -O reports/
PASS Rule ../sparql/multiple-class-links-violation.sparql: 0 violation(s)
real	1m1.240s
user	1m40.028s
sys	0m1.432s


ROBOT_JAVA_ARGS=-Xmx8G robot merge --input go-edit.obo verify --queries ../sparql/obsolete-reference-violation.sparql -O reports/
PASS Rule ../sparql/obsolete-reference-violation.sparql: 0 violation(s)
real	0m58.249s
user	1m39.612s
sys	0m1.292s


OWLTOOLS_MEMORY=8G owltools --use-catalog go-edit.obo --verify-changes -p go-lastrelease.owl -o change-report.txt --id-prefix-filter GO: --check-missing-labels && touch change-report.txt
real	0m31.557s
user	0m57.008s
sys	0m1.236s


OWLTOOLS_MEMORY=8G owltools --use-catalog reasoned.owl --remove-imports-declarations --remove-dangling --make-subset-by-properties BFO:0000050 RO:0002211 RO:0002212 RO:0002213 BFO:0000051 BFO:0000066 RO:0002091 RO:0002092 RO:0002093 --set-ontology-id http://purl.obolibrary.org/obo/go.owl -o -f obo go-pre.obo.tmp && egrep -v '(property_value|relationship): never_in_taxon' go-pre.obo.tmp > go-pre.obo
real	0m42.359s
user	1m15.864s
sys	0m1.340s


ROBOT_JAVA_ARGS=-Xmx8G robot reduce -r elk -i go-pre.obo -o go-pre-reduced.obo
real	0m34.738s
user	0m59.692s
sys	0m1.312s


ontology-release-runner --catalog-xml catalog-v001.xml --ignoreLock --skip-release-folder --skip-format owx --skip-format metadata --outdir build --allow-overwrite --asserted --simple --no-reasoner --remove-trailing-qualifiers go-pre-reduced.obo &&\
../util/check-obo-for-standard-release.pl --disable-xrf-abbs-check --disable-multiply-labeled-edge build/go.obo &&\
cp build/subsets/* subsets/ &&\
cp build/go.obo go.obo &&\
cp build/go-simple.obo . &&\
cp build/go.owl .
real	2m7.505s
user	3m2.116s
sys	0m3.500s


ROBOT_JAVA_ARGS=-Xmx8G robot query -f tsv -i go.owl -s ../sparql/owl-stats.sparql reports/owl-stats.tsv -s ../sparql/basic-report.sparql reports/basic-report.tsv -s ../sparql/class-count-by-prefix.sparql reports/class-count-by-prefix.tsv -s ../sparql/edges.sparql reports/edges.tsv -s ../sparql/labels.sparql reports/labels.tsv -s ../sparql/xrefs.sparql reports/xrefs.tsv -s ../sparql/obsoletes.sparql reports/obsoletes.tsv -s ../sparql/synonyms.sparql reports/synonyms.tsv
real	1m7.018s
user	1m49.296s
sys	0m1.440s
```

**Comment by balhoff** [comment]
One issue we have is simply loading the ontology for every separate command. For example, on my laptop, running `time ROBOT_JAVA_ARGS=-Xmx8G robot query -i go-edit.obo` loads the ontology and then errors because I didn't provide a query:

```
real	0m51.008s
user	1m25.232s
sys	0m4.468s
```

So every separate step will have a 1 minute overhead for loading GO and imports.

**Comment by cmungall** [comment]
Would doing an initial conversion to a faster to load format help?

**Comment by cmungall** [comment]
ah right I should really look at the ticket rather than working backwards through email..

OK, it's clear we could save a lot of time by compacting commands together.
