### ISSUE TITLE
refine  cell separation after cytokinesis and *during* cytokinesis are  different processes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16238]
related tickets
https://github.com/geneontology/go-ontology/issues/16237
https://github.com/geneontology/go-ontology/issues/15939

GO:0000920  cell separation after cytokinesis
The process of physically separating progeny cells after cytokinesis; this may involve enzymatic digestion of septum or cell wall components.
and has child terms related to cell wall degradation
https://www.pombase.org/term/GO:0000920

Was created for fungi
where "cell separation" occurs after the completion of cytokinesis (the  cell wall is digested during this process,  but  in mutants where this does not occur there is no cell cytokinesis/cycle defect, cells can keep cycling but 'chain together' (like a string of sausages in pombe).

We did not define this well enough to exclude cell separation which occurs  *during* cytokinesis  (i.e abscission) in  for example mammalian cells,

- [x] 1. Suggest refine def to
The process of physically separating progeny cells after cytokinesis; this ~may involve~ involves enzymatic digestion of septum or cell wall components.
(I don't know why it says "may")

To illustrate how the process differs in fungi:
![speration](https://user-images.githubusercontent.com/7359272/44043771-9417398a-9f1b-11e8-8ec6-34055bdbd620.jpg)

You can see that the plasma membrane exists (and two daughter cells are no longer conjoined), before separation.
(cytokinesis is complete when two daughter cells are created, even if they are still 'stuck' together via  their cell wall)

- [ ] Add taxon constraint "only in fungi"  (possibly plant, I remember discussing with Tanya?)
or maybe add never ins?

- [3] 

Add a comment:

This term is not for use to describe cell separation via abscission. Abscission is a different process. It is part of cytokinesis and involves ingression of the midbody?  and repair of the disrupted plasma membrane.
Here the dausghter cells are still conjined:
![abscission](https://user-images.githubusercontent.com/7359272/44044020-3c1916c6-9f1c-11e8-9b22-aa710fd2bb3c.jpg)

**Comment by pgaudet** [comment]
@tberardini Can you please let us know whether this process occurs in plants ?

**Comment by pgaudet** [comment]
@ValWood The term seems correctly used in bacteria, at least in PMID:19525345

**Comment by pgaudet** [comment]
Improved definition of midbody abscission: 
The process by which the midbody, the cytoplasmic bridge that connects the two prospective daughter cells, is severed at the end of mitotic cytokinesis, resulting in two separate daughter cells.

**Comment by pgaudet** [comment]
@ValWood 
Woudn't it be clearer if we mentioned the cell wall in the definition ? 

Your proposed definition: The process of physically separating progeny cells after cytokinesis; this involves enzymatic digestion of septum or cell wall components.

How about: The process of physically separating **the cell walls of** progeny cells after cytokinesis; this involves enzymatic digestion of septum or cell wall components.

?? 

Thanks, Pascale

**Comment by ValWood** [comment]
> The term seems correctly used in bacteria, at least in PMID:19525345

Yes include taxa.

>Woudn't it be clearer if we mentioned the cell wall in the definition ?

Yes, Even further
The process of physically separating the septal cell wall material by enzymatic digestion, occurs after daughter cells are separated by cytokinesis .

It is always the septum (the septum is cell-wall material).

**Comment by pgaudet** [comment]
**Taxon constraints:** I did 
+relationship: never_in_taxon NCBITaxon:33208 ! Metazoa
+relationship: never_in_taxon NCBITaxon:554915 ! Amoebozoa
(I dont think I can do 2 'only in taxon' for different taxa)

**Comment by pgaudet** [comment]
@ValWood How about changing the label to 
'septum separation after cytokinesis'?

**Comment by ValWood** [comment]
> 'septum separation after cytokinesis'?

much better!

**Comment by tberardini** [comment]
How about _septum digestion after cytokinesis_?     It does not look like this process occurs in plant cells.

**Comment by ValWood** [comment]
That would be OK too.

**Comment by mah11** [comment]
> > 'septum separation after cytokinesis'?
> 
> much better!

But the septum doesn't _separate_; it's degraded so the daughter _cells_ separate. So this name is not biologically accurate.

> How about septum digestion after cytokinesis? 

Not just OK, better for reason given above. Or "cell separation by septum digestion after cytokinesis" if you want the full picture.

**Comment by mah11** [comment]
> The central part of the septum (primary septum) is cleaved but the secondary septum is still there and becomes the new cell wall.

... After which it is no longer a septum.

>  People do refer to this process as septum separation.

But one of the motivations for GO is to be less woolly than biologists writing papers in natural English ;)

**Comment by ValWood** [comment]
Fair enough. @tberardini  's suggestion was better anyway!

**Comment by pgaudet** [comment]
So, now we have ' septum digestion after cytokinesis'. I hope I followed the thread correctly. 

Thanks, Pascale

**Comment by tberardini** [comment]
Do you want to alert the people that have used this term to annotate metazoan genes?  I noted at least a few IMP annotations when I was scanning AmiGO earlier.

**Comment by pgaudet** [comment]
@tberardini I did https://github.com/geneontology/go-annotation/issues/2053
Most annotations have already been moved. 

Pascale
