### ISSUE TITLE
Remove unused slims

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16243]
Hello, 

I emailed Jane Lomax and she proposes that we get rid of 

goantislim_grouping
~goslim_chembl~
goslim_virus
virus_checked

@pmasson55 -> is this OK for you guys? Have you been using this slim ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The following GO-slims have not been maintained and will be retired:

goantislim_grouping
goslim_chembl
goslim_virus
virus_checked


We’d like to proceed and obsolete this term on August 21, 2018. Unless objections are received by August 21, 2018  we will assume that you agree to this change.  If you are interested in maintaining one of these slims, please comment on this ticket: 

https://github.com/geneontology/go-ontology/issues/16243


Thanks, Pascale

**Comment by pgaudet** [comment]
Wait until Prudence replies before merging. 

(@dosumis email Aug 14:)

> I have no stake in these slims, but this seems like very short notice (didn’t we used to => 2 weeks?) - especially in the middle of August when many of those affected are likely to be on holiday.  I just forwarded to Prudence, who I think is responsible for goslim_chembl.  She’s on holiday until the 25th.

Pascale

**Comment by PruMM** [comment]
Hi Pascale
Regarding the goslim_chembl and frequency of update. The ChEMBL data release cycle is longer than most resources- so our updates to the ChEMBL slim would be every 18 months or so. Can this slim be kept as it has been a fairly new resource to the drug discovery user and the upatek has been building up gradually- regards
 Prudence

**Comment by pgaudet** [comment]
Great, thank you for your response. 

Pascale
