### ISSUE TITLE
karyogamy involved in conjugation with mutual genetic exchange - Is this a real process? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16248]
Hello, 

While working on the cell fusion ticket #15939, I came across 
- GO:0000744 karyogamy involved in conjugation with mutual genetic exchange (0 annotations). 

It is defined as "During sexual reproduction, the creation of a single nucleus from multiple nuclei as a result of fusing the lipid bilayers that surround each nuclei. This occurs after the mutual exchange of nuclei."

However, if the nuclei are exchanged, how can they fuse ? Does anyone have a reference for this ? 

Thanks, Pascale

**Comment by mah11** [comment]
I don't know much about this type of conjugation (and I don't really have time to dig into it further), but it's the type done by ciliated protozoans, so expect weirdness. If I understand correctly, the diagram in Figure 1 of PMID:21933443 shows what normally happens, and it does look like micronuclei do undergo both exchange and fusion. Also try https://www.ncbi.nlm.nih.gov/books/NBK6002/

**Comment by pgaudet** [comment]
Thanks Midori ! 
This figure is useful: (from PMID:19204800)

![image](https://user-images.githubusercontent.com/4782928/44093405-c43723e2-9fd3-11e8-8da5-50aafb73df11.png)

**Comment by mah11** [comment]
I like how one of the arrows is labeled "Food" :)

**Comment by pgaudet** [comment]
Perhaps it would be clearer if the label was: 
'karyogamy during in conjugation with mutual genetic exchange' (as I proposed for 'karyogamy involved in conjugation with cellular fusion' here: https://github.com/geneontology/go-ontology/pull/16242) 

And the definition changed to 
CURRENT: "During sexual reproduction, the creation of a single nucleus from multiple nuclei as a result of fusing the lipid bilayers that surround each nuclei. This occurs after the mutual exchange of nuclei."

PROPOSED: "During sexual reproduction, the creation of a single nucleus from **two** nuclei as a result of fusing the **nuclear envelopes** that surround each nuclei. This occurs following the mutual exchange of one of the two nuclei produced by the mitosis that follows the second meiotic nuclear division. This occurs, for example in Tetrahymena."

What do you think @mah11 ?

**Comment by pgaudet** [comment]
Thanks Midori !
