### ISSUE TITLE
Merge GO:0070872 plasma membrane organization involved in conjugation into GO:0032220 	plasma membrane fusion involved in cytogamy

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16258]
From comments in #15939

**Comment by pgaudet** [comment]
@mah comment in #15939 

> I can't find 'plasma membrane fusion involved in conjugation with cellular fusion'
only 'plasma membrane organization involved in conjugation with cellular fusion' 

This is a bit odd, and I don't remember why it was done this way (I added the PM fusion term here, but almost certainly following advice from someone else):

![go_32220](https://user-images.githubusercontent.com/5196259/44096605-99beb102-9fd3-11e8-990a-e70869ab7802.png)


It's GO:0032220 part_of GO:0000755
and GO:0032220 is_a GO:0045026
and GO:0000755 part_of GO:0000747

**Comment by pgaudet** [comment]
@mah11 
Given that GO:0070872 plasma membrane organization involved in conjugation with cellular fusion
has no annotations, and the the definitions are similar enough, I will merge it into  GO:0032220 
plasma membrane fusion involved in cytogamy

**Comment by pgaudet** [comment]
@ValWood  @mah11  Should I add this reference ? PMID:29134248?

**Comment by ValWood** [comment]
Yes, please.

val
