### ISSUE TITLE
MP borate export across plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16251]
Borate is required in small quantities but is toxic to microbes in larger quantities. Therefore have borate PM exporter

GO:0140159    borate export across plasma membrane -> add detoxification

**Comment by ukemi** [comment]
@tberardini will this work for plants where the transport of boron on an organismal level is critical? Is the export always detoxification or is it sometimes exported from say root cells into the plant vascular system for use elsewhere?

We need to be very careful about creating instance relationships in the ontology.

**Comment by ValWood** [comment]
Ah plants. Good point!

**Comment by ukemi** [comment]
Actually, I meant to specify borate, but I think the same argument applies, does it not?

**Comment by ukemi** [comment]
@tberardini if you still agree, can you close this ticket?

**Comment by ukemi** [comment]
I think this one nails it shut.
PMID:18603465
Plus it mentions my favorite plant structure, the Casparian Strip.
