### ISSUE TITLE
Question regarding relation 'has necessary component activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16266]
Hello @cmungall (I guess)

Maybe this is a ticket for RO, but I want to make sure I formulate the issue correctly: 
I thought @dosumis had created the relation 'has necessary component activity'  to capture compounds functions, and for example to deal with the old DNA binding issue regarding to transcription factors (see #16214). 

I thought regulates would not be transitive over 'has necessary component'. Which means that: 

  **DNA binding 
   -- 'is_a' DNA-binding transcription factor activity
   ----- 'regulates' regulation of DNA-binding transcription factor activity (== 'is_a' regulation of DNA binding)**

 While:  
  **DNA binding 
   -- 'has necessary component' DNA-binding transcription factor activity
   ----- 'regulates'  regulation of DNA-binding transcription factor activity (is NOT a regulation of DNA binding), ie 'regulates' would not be transitive over 'has necessary component'**

Currently there are no inference chains; can we add some (Is this a RO ticket?) 
(Also, right now it's a child of 'positively regulated by', which seems very odd). 

This would be very useful to deal with all compound functions (which is probably everything except for binding). 

Thanks, Pascale

**Comment by cmungall** [comment]
It may be best to hammer out precisely what is required on this ticket first.

I'm going to need to allocate a chunk of time to focus on this to give it the response it deserves - can this wait until we see each other at USC?

In the meantime I believe there were some graphical documents (in a ticket?) that illustrated the thinking here - do you happen to have those?

**Comment by pgaudet** [comment]
Yes let's discuss at USC. I dont find the graphical documents in a ticket - I see a lot of discussion here
#14012 but no graphics. 

Pascale

**Comment by pgaudet** [comment]
Resolved here: https://github.com/geneontology/go-ontology/issues/16972
