### ISSUE TITLE
 NTR negative regulation of cellular response to phosphate starvation

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16276]
Hi, 

could I please request negative regulation of cellular response to phosphate starvation (and also a "regulation" parent to the new term and the existing pos reg term)

cheers

**Comment by ValWood** [comment]
ref PMID:29414789

Changed subject from PMID so people can recognise  what the ticket is about in "daily digest'
(Otherwise we need to click on them to know if relevant)

**Comment by Antonialock** [comment]
thanks!

**Comment by Antonialock** [comment]
Hi Karen, would it be possible for you to take a look at this some time soon? It is for one of our community curation sessions.

**Comment by krchristie** [comment]
Thanks for taking care of this @pgaudet

**Comment by pgaudet** [comment]
of course!

**Comment by Antonialock** [comment]
thanks!
