### ISSUE TITLE
Obsolete GO:0000903 regulation of cell shape during vegetative growth phase (was: "phase" branch term has an "annotatable" descendant.)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16285]
I notice that a "phase" branch term has a  "annotatable" descendant. 

GO:0000903    regulation of cell shape during vegetative growth phase

This branch was supposed to be disjoint  from the rest of the ontology (confusingly it is a separate aspect describing when things occur).

This is  also odd because it has a    

part_of relation to the phase. This is not correct, the relationship to "vegetative growth phase" is "happens_during"

Maybe logical defs need fixing?

I'm not really sure why the term is required. The parent with a happens_during extension would be correct would'nt it?

Annotations 
PomBase 1
SGD 2

**Comment by pgaudet** [comment]
Hi @ValWood 
I changed the logical definition to have "happens_during" rather than "part_of". Let me know if this addresses the issue or if you want to propose obsoletion.

**Comment by pgaudet** [comment]
Please reopen if needed. Thanks, Pascale

**Comment by ValWood** [comment]
I would rather obsolete to be consistent and always do phases with extensions...
@cmungall ?
It might be helpful to maintain this disjointly in case it is ever  decided to move the branch out of GO... but more it just seems like a natural place to always post compost to me...

**Comment by ValWood** [comment]
Another reason, that I just thought of, since we already have a lot of phase specific data, we are implementing "phase" filtering over all of our GO data. This is much easier to do if the phases are neatly in extensions.

https://github.com/pombase/website/issues/877

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0000903 regulation of cell shape during vegetative growth phase. The reason for obsoletion is that the 

There are 3 experimental annotations to this term by SGD (2 EXP) and PomBase (1 EXP). 
There are no InterPro2GO mappings to this term and the term is not in any subsets. 
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/16285
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 4th, 2018. Unless objections are received by September 4th, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@srengel 
> i have changed the SGD annotations to regulation of cell shape GO:0008360 w/col16 happens_during(GO:0072690) single-celled organism vegetative growth phase
