### ISSUE TITLE
New metabolism/enzyme terms part 1( molecular function and biological process)

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16299]
@hdrabkin ...I get the feeling this may end up on your doorstep...I can separate these out futher into individual requests for each term. They are logically grouped here because the enzymes catalyze reactions that are part of the pathways. Also from the same paper describing the biology.

Term: fraxetin 5-hydroxylase activity  ==     GO:0106144
Defintion: Catalyzes the reaction fraxetin+ NAD(P)H + 02= sideretin + NAD(P)(+) + H20
Suggested Parentage: GO:0016709
Ref:PMID:29581584

Term: scopoletin 8-hydroxylase activity  == GO:0106145
Def: Catalyzes the hydroxylation of scopoletin at position C-8 to form fraxetin (Scopoletin + 2-oxoglutarate+O2=fraxetin +succinate+ CO2)
Suggested Parentage: GO:0016709
Ref: PMID:29581584, PMID:29361149

Term: sideretin biosynthesis === GO:0106146
Def: The chemical reactions and pathways resulting in the formation of sideretin.
Suggested parentage: GO:009805 (coumarin biosynthetic process)
Ref:PMID:29581584

Term: fraxetin biosynthesis == GO:0106147
Def: The chemical reactions and pathways resulting in the formation of fraxetin.
Suggested parentage: GO:009805 (coumarin biosynthetic process)
Ref:PMID:29581584

**Comment by hdrabkin** [comment]
I will request both the reduced and oxidized forms while I'm at it.

**Comment by hdrabkin** [comment]
I decided to go ahead and put these in now while I'm waiting for CHEBI ids; I also requested two EC numbers (I have no idea how long they will take). It looks like RHEA would like the CHEBI ids or structures first. CHEBI should not take long, so I'll wait for them.

**Comment by hdrabkin** [comment]
Will be in next monthly CHEBI release

submission: 13730
chebi_id: CHEBI:142096
name: sideretin (oxidized form)

submission: 13729
chebi_id: CHEBI:142095
name: sideretin (reduced form)

**Comment by hdrabkin** [comment]
fraxetin 5 hydroxylase EC:1.14.14.fm (pending);  EC 1.14.14.fm, RHEA:57844

**Comment by hdrabkin** [comment]
Scopoletin 8-hydroxylase EC:1.14.11.ag (pending) EC 1.14.11.ag, RHEA:57848

**Comment by ValWood** [comment]
@hdrabkin  Is this done?

**Comment by hdrabkin** [comment]
RHEAs and ECs now public.
