### ISSUE TITLE
ntr Trm8-Trm82 complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16296]
Trm8-Trm82 complex

synonyms
tRNA (m7G46) methyltransferase 
tRNA m7G methylation complex

refs
https://www.ncbi.nlm.nih.gov/pubmed/18184583
https://www.ncbi.nlm.nih.gov/pubmed/17382321
https://www.ncbi.nlm.nih.gov/pubmed/18164779

parent
tRNA methyltransferase complex (GO:0043527)

standard def
suggest
A protein complex involved in the catalysis of the formation of the modified nucleotide 1-methyl~adenosine~ guanine (m17) in tRNA. In yeast, it is a heterotetramer of two subunits, Trm8 (catalytic) and Trm82 (WD repeat).

**Comment by hdrabkin** [comment]
The synonyms and references indicate G methylation but your def indicates adenosine methylation. 
? Confirm def please?

**Comment by hdrabkin** [comment]
Ok; just checking; and I must say that PMID: 18164779 is a really cool paper!!
What is the m17? do you mean nt 46?

**Comment by ValWood** [comment]
yes thats a hangove from the old def too...

**Comment by hdrabkin** [comment]
A protein complex involved in the catalysis of the formation of the modified nucleotide 7-methylguanine (at position 46  in certain tRNAs, such as tRNA(phe). In yeast, it is a heterotetramer of two subunits, Trm8 (catalytic) and Trm82 (WD repeat).

**Comment by hdrabkin** [comment]
@ValWood , I think it should be named tRNA (m7G46) methyltransferase complex to be consistent with it's sibs. Your suggested name would be a synonym.

**Comment by ValWood** [comment]
OK!

**Comment by hdrabkin** [comment]
GO:0106143
