### ISSUE TITLE
suggest obsoletion, splicing factor binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16307]
Has 3 EXP annotation, no chance of being consistent since there are ~125 "splicing factors"

All have "with" fields. Obsolete, or merge into protein binding?

**Comment by pgaudet** [comment]
@ValWood How about we discuss this more generally (rather than creating individual tickets for each term in this branch?)

**Comment by ValWood** [comment]
OK. I was picking off a few that were especially confusing or meaningless, or had small numbers of annotation,  because getting rid of them all at once would be too much recuration work.

**Comment by pgaudet** [comment]
I would prefer a global solution.

**Comment by ValWood** [comment]
Even though you want to do this globally we could just get rid of "splicing factor binding" now since it is clearly not a good term, and only has 3 EXP. Will prevent a new annotation.

**Comment by ValWood** [comment]
Should we close this ?

**Comment by pgaudet** [comment]
@cmungall any thoughts ?

**Comment by ValWood** [comment]
Did you want to close this one? we do need a global solution, but this term is particularly useless ;)

It only had 3 annotations before and now it has 8- only 3 have a with field. If you know something is a splicing factor binding, then you *must* know what it binds to. This term is encouraging laziness as the "with" field is not enforced for protein binding children.

**Comment by ValWood** [comment]
Also, there is another ticket  dealing with a global solution that I forgot about:
https://github.com/geneontology/go-ontology/issues/16186
