### ISSUE TITLE
GO:0031028   septation initiation signaling Ancestry

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16308]
Ancestry
https://www.ebi.ac.uk/QuickGO/term/GO:0031028

This terms has lots of parents for the processes it regulates. However I think it is a branched pathway, so these assertionas might not always be true.

Also it doesn't seem to be normal practice to put all of the processes regulated by a pathway in the ontology? Should these be done by coupling signalling to the regulated process at annotation time?

**Comment by pgaudet** [comment]
Removed parents: 

-is_a: GO:0007096 ! regulation of exit from mitosis
-is_a: GO:0031991 ! regulation of actomyosin contractile ring contraction
-is_a: GO:1901893 ! positive regulation of cell septum assembly
-is_a: GO:1903438 ! positive regulation of mitotic cytokinetic process

Kept: 
 is_a: GO:0007265 ! Ras protein signal transduction

Thanks, Pascale

**Comment by ValWood** [comment]
great, that one will be really helpful
