### ISSUE TITLE
NTR:endoplasmic reticulum-plasma membrane contact site

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#16304]
Checking whether this would be an appropriate GO term.  Please review.  Thank you!

name: endoplasmic reticulum-plasma membrane contact site
definition: A region of the ER membrane and plasma membrane where the two membranes touch and are tethered together.  Proteins within the ER membrane interact with the lipids in the PM through lipid-binding domains. (see Fig.1a of PMID: 29782498)
exact synonyms: EPCS, endoplasmic reticulum-plasma membrane contact junction
is_a: PM part
is_a: ER part
part_of: ER membrane? or cytoplasmic side of endoplasmic reticulum membrane, GO:0098554?
part_of: plasma membrane? or cytoplasmic side of plasma membrane,GO:0009898?
references: 
PMID:30012696
https://www.ncbi.nlm.nih.gov/pubmed/30012696
PMID:29782498
https://www.ncbi.nlm.nih.gov/pubmed/29782498
PMID:27955928
https://www.ncbi.nlm.nih.gov/pubmed/27955928

**Comment by ValWood** [comment]
I hope so ;)
https://github.com/geneontology/go-ontology/issues/14861

**Comment by ukemi** [comment]
@krchristie , please close both tickets when you have completed this request. I am leaving them both open for reference.

**Comment by pgaudet** [comment]
I didn't realize these tickets were duplicated when I closed #14861 
I added the references mentioned by @tberardini 

For info, the logical definition is: 

'organelle membrane contact site'
 and (overlaps some 'endoplasmic reticulum membrane')
 and (overlaps some 'plasma membrane')

Thanks, Pascale

**Comment by tberardini** [comment]
Did you also add the synonyms in this ticket?

exact synonyms: EPCS, endoplasmic reticulum-plasma membrane contact junction

**Comment by pgaudet** [comment]
I had missed that, thanks for checking! 

Pascale

**Comment by tberardini** [comment]
Thanks, Pascale.
