### ISSUE TITLE
New metabolism/enzyme terms part 2( molecular function and biological process)

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16300]
Another paper that describes new enzymatic activity and corresponding metabolic pathway

Term: 4-hydroxyindole-3- carbonyl nitrile biosynthesis
Def: The chemical reactions and pathways resulting in the formation of 4-hydroxyindole-3- carbonyl nitrile (4-OH-ICN), a cyanogenic glucoside.
Reference: PMID:26352477
Suggested parentage: is a GO:0019756 cyanogenic glycoside biosynthetic process

Term: Indole-3-carbonyl nitrile 4-hydroxylase activity
Def: indole-3-carbonyl nitrile + NADPH +O2=4-hydroxyindole-3- carbonyl nitrile + NADP(+) + H20
Reference: PMID:26352477
Suggested parentage: is a GO:0016709

**Comment by ukemi** [comment]
Guess this one needs a ChEBI identifier too. The structure is in the paper.

**Comment by hdrabkin** [comment]
CHEBI ids requested; EC requested

**Comment by hdrabkin** [comment]
Will add terms now; waiting on CHEBI and EC
GO:0106148  4-hydroxyindole-3- carbonyl nitrile biosynthesis
GO:0106149  indole-3-carbonyl nitrile 4-hydroxylase activity

**Comment by hdrabkin** [comment]
submission: 13742 Approved
chebi_id: CHEBI:142138
name: 4-hydroxy-indole-3-carbonyl nitrile

submission: 13743 Approved
chebi_id: CHEBI:142139
name: indole-3-carbonyl nitrile

**Comment by hdrabkin** [comment]
indole-3-carbonyl nitrile 4-hydroxylase EC:1.14.14.fn (pending) :RHEA:57868.

Note none of these are actually in EC or RHEA yet.

**Comment by ValWood** [comment]
@hdrabkin  do you still need this ticket open?

**Comment by hdrabkin** [comment]
RHEA:57864 used instead for this newer EC:1.14.14.165; closing
