### ISSUE TITLE
unnecessary "process involved in process" term to obsolete

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16301]
GO:0000456    dimethylation involved in SSU-rRNA maturation

1 annotation (PomBase)

not required

![redundant](https://user-images.githubusercontent.com/7359272/44735216-ba052e80-aae3-11e8-9b82-12d3c595a7f6.jpg)

+ | 18S rRNA (adenine(1779)-N(6)/adenine(1780)-N(6))-dimethyltransferase activity
  | involved in maturation of SSU-rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)

annotation covers it...

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete GO:0000456 dimethylation involved in SSU-rRNA maturation. The reason for obsoletion is that this term can be captured as a GO-CAM model.

There is 1 manual annotation (PomBase); no InterPro mappings; the term is not present in any slims. 

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/16301

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on September 5, 2018. Unless objections are received by September 5, 2018, we will assume that you agree to this change.

Thanks,

Pascale
