### ISSUE TITLE
Moving taxon contraints to a yaml file ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16306]
Hello, 

@thomaspd  proposes to manage taxon constraints via a yaml file - I am putting this here for discussion with the editors. 

Pascale

**Comment by pgaudet** [comment]
@thomaspd would you be OK with an OBO or OWL file ? So we can more easily manipulate it in protégé.

**Comment by ukemi** [comment]
Are we doing this? What are the pros and cons of using this approach? Once we have made that decision, we need to have a plan to implement the taxon restrictions as a new import. @balhoff says we can do it, but visualizing it in Protege might be a challenge.

**Comment by balhoff** [comment]
Just to be clear—visualizing the axioms generated by a TSV-based system (using DOS-DP) would be the same as we have now, but we were talking about being able to see the inferred taxon constraints for a given term. This may require a specialized plugin.

**Comment by balhoff** [comment]
Implemented by #16508.

**Comment by balhoff** [comment]
I updated the wiki documentation: http://wiki.geneontology.org/index.php/Adding_Taxon_Restrictions
