### ISSUE TITLE
refine defs for cell cycle transition regulation terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16313]
e.g.

GO biological process
regulation of G1/S transition of mitotic cell cycle (GO:2000045)

Any cell cycle regulatory process that controls the commitment of a cell from G1 to S phase of the mitotic cell cycle.

-> A signalling pathway that results in the activation of a cyclin-dependent  protein kinase.

I will make a list...

**Comment by ValWood** [comment]
GO:1902806    regulation of cell cycle G1/S phase transition
GO:1902749    regulation of cell cycle G2/M phase transition
GO:1902807    negative regulation of cell cycle G1/S phase transition | is_a
GO:1902808    positive regulation of cell cycle G1/S phase transition
GO:1902751    positive regulation of cell cycle G2/M phase transition 
GO:1902750    negative regulation of cell cycle G2/M phase transition
GO:0110030    regulation of G2/MI transition of meiotic cell cycle
GO:0010971    positive regulation of G2/M transition of mitotic cell cycle
GO:0110032    positive regulation of G2/MI transition of meiotic cell cycle

I don't think I missed any. basically all children of 
GO:1902806    regulation of cell cycle G1/S phase transition
and
GO:1902749    regulation of cell cycle G2/M phase transition


Just add the "clause"
A signalling pathway that results in the activation of a cyclin-dependent protein kinase.

All cell cycle transition regulation  (G1/S and G2/M) is a  highly conserved signalling pathway, and it always converges on a cyclin-dependent protein kinase.

Adding this clause should prevent this been used for the bzillions of genes (trancription/translation/splicing etc. etc.) which cause a cell cycle phenotype (block), but are not regulation per se.

**Comment by ValWood** [comment]
Any sigalling pathway  that  results in the activation of a cyclin dependent kinase to modulate the transition from G2 phase to M phase of the mitotic cell cycle.

**Comment by pgaudet** [comment]
How about: Any sigalling pathway  that  results in the activation of a cyclin dependent kinase to modulate the switch from G2 phase to M phase of the mitotic cell cycle.

**Comment by ValWood** [comment]
@jvhayles

Hi Jacky, 
We'd like to make these definitions more precise so that the transition terms only get used for cell cycle regulators.
Can we define the transtion as a "switch"?
Cheers

Val

**Comment by ValWood** [comment]
Also is there a way to be precise about the kinase. I guess we could jsut say Cyclin dependent Kinase 1?  Does that cover all  G1/S and G2/M transition regulators though?

**Comment by ValWood** [comment]
That won't work. In human I think its CDK1,2 and 3. But there are other cyclin dependent kinases like the mediator, TFIIH and TefB associated.

What do people call the CDKs to exclude these ones?
Just "cell cycle CDK" maybe?

**Comment by mah11** [comment]
whatever you do, _please_ hyphenate "cyclin-dependent"

**Comment by ValWood** [comment]
In a def i would. Here I'm just *typing* quickly.

**Comment by ValWood** [comment]
apologies
positive regulation
Any sigalling pathway that results in the activation of a cyclin-dependent kinase to modulate the switch from G2 phase to M phase of the cell cycle.

negative regulation
Any sigalling pathway that results in the inhibition of a cyclin-dependent kinase to modulate the switch from G2 phase to M phase of the cell cycle.

regulation
Any sigalling pathway that results in the activation or  inhibition of a cyclin-dependent kinase to modulate the switch from G2 phase to M phase of the cell cycle.

**Comment by pgaudet** [comment]
I found more terms than you listed - is this right ? 

name: regulation of G2/M transition of mitotic cell cycle
name: negative regulation of G2/M transition of mitotic cell cycle
positive regulation of G2/M transition of mitotic cell cycle


name: regulation of G2/MI transition of meiotic cell cycle
name: negative regulation of G2/MI transition of meiotic cell cycle
name: positive regulation of G2/MI transition of meiotic cell cycle


name: regulation of cell cycle G2/M phase transition
name: positive regulation of cell cycle G2/M phase transition
name: negative regulation of cell cycle G2/M phase transition


name: regulation of cell cycle G1/S phase transition
name: negative regulation of cell cycle G1/S phase transition
name: positive regulation of cell cycle G1/S phase transition

name: regulation of G1/S transition of mitotic cell cycle
name: positive regulation of G1/S transition of mitotic cell cycle
name: negative regulation of G1/S transition of mitotic cell cycle

Thanks, Pascale

**Comment by ValWood** [comment]
Yes I forgot about the meiotic and the grouping terms.
