### ISSUE TITLE
obsolete GO:0031659     positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16312]
GO:0031659    
positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

10 EXP annotations

This term is adequate
positive regulation of  G1/S transition of mitotic cell cycle
(regulation of CDK is a given because this is the end point)

If you are directly regulating the kinase use:

cyclin-dependent protein serine/threonine kinase activator activity has_substrate *cdc2* part of positive regulation of G1/S transition of mitotic cell cycle

**Comment by pgaudet** [comment]
There are 9 EXP annotations - see

https://docs.google.com/spreadsheets/d/1ARpUTcTIj8BrMa57HGC0RCjLSaFLHgI1hTgkLkZ_oys/edit#gid=0

1 pombase @ValWood 
1 UniProt @ggeorghiou 
7 BHF @RLovering 

By looking (relatively quickly) it looks like we probably captured the role in cell cycle with other annotations - but please comment if you object to obsoletion. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Err - in fact we should obsolete the triad - 

-  GO:0031657 regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle
--  GO:0031658 negative regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle
-- GO:0031659 positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle 

I'm adding the annotations the the same Annotation Review document.

**Comment by pgarmiri** [comment]
The UniProt annotation has been updated.
 Thanks, Penelope

**Comment by pgaudet** [comment]
@ValWood  @RLovering

Can you please look at your annotations? 
https://docs.google.com/spreadsheets/d/1ARpUTcTIj8BrMa57HGC0RCjLSaFLHgI1hTgkLkZ_oys/edit#gid=0

Thanks, Pascale

**Comment by ValWood** [comment]
done,
v

**Comment by srengel** [comment]
i changed the 2 SGD annotations to negative regulation of cyclin-dependent protein serine/threonine kinase activity GO:0045736 happens_during GO:0000082 G1/S transition of mitotic cell cycle
