### ISSUE TITLE
mRNA methyltransferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16310]
should
GO:0016422 | mRNA (2'-O-methyladenosine-N6-)-methyltransferase activity |
be a child of 
GO:0001734 | mRNA (N6-adenosine)-methyltransferase activity |  

(I wonder becase PomBAse used GO:0001734, SGD use GO:0016422

but the complex term is:
GO:0036396 | RNA N6-methyladenosine methyltransferase complex

**Comment by vanaukenk** [comment]
@ValWood 

From the definitions, it looks like these terms are describing different sequence contexts of adenosine methylation and thus, that GO:0016422 is not describing a subclass of GO:0001734.  

@hdrabkin - can you please take a look at the definitions to confirm that this is the case and that the current parentage is okay?

For the annotations, it looks like SGD also has an IMP annotation to GO:0001734 but actually an IBA annotation for GO:0016422.

**Comment by hdrabkin** [comment]
Def for GO:0016422 (mRNA (2'-O-methyladenosine-N6-)-methyltransferase activity) is 
Catalysis of the reaction: S-adenosyl-L-methionine + m(7)G(5')pppAm = S-adenosyl-L-homocysteine + m(7)G(5')pppm(6)Am.
THIS IS NOT consistent with the term name. 
No reference to the 2'-O-methyl
EC def is 
S-adenosyl-L-methionine + a 5-(N(7)-methyl 5-triphosphoguanosine)-2'-O-methyladenosine-[mRNA] <=> S-adenosyl-L-homocysteine + a 5-(N(7)-methyl 5-triphosphoguanosine)-N(6),2'-O-dimethyladenosine-[mRNA]

I'm not seeing a relationship between  GO:0001734 and GO:0016422; they are sibs

![screen shot 2018-09-07 at 4 23 25 pm](https://user-images.githubusercontent.com/10440080/45241462-9b105480-b2ba-11e8-97fa-208572eecbec.jpg)

I appear to have made GO:0001734 but do not remember anything at all;

**Comment by ValWood** [comment]
So, what is the solution here?

**Comment by pgaudet** [comment]
@colinlog Can you help with this one ?

**Comment by hdrabkin** [comment]
I'd say basically because the two substrates are different, no they should not have parent/child relationship
 GO:0001734's substrate is an unmodified A residue, internal to the RNA chain; GO:0016422 's substrate is a 2'O-methylated A at the RNA 5' end.

**Comment by ValWood** [comment]
OK closing!
