### ISSUE TITLE
make GO:0060468 | prevention of polyspermy more general

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16329]
To describe the fertilization block in 
Nature. 2018 Aug;560(7718):397-400. Epub 2018 Aug 8.
Gamete fusion triggers bipartite transcription factor assembly to block re-fertilization.

the authors selected the GO term:
GO:0060468 | prevention of polyspermy

I wonder if we could generalise this term
The negative regulation of fertilization process that takes place as part of egg activation, ensuring that only a single sperm fertilizes the egg.

i.e 
term name: negative regulation of re-fertilization?

The negative regulation of fertilization process  after initial fertilization event that prevents the fusion of more than two gametes? Or something along those lines?

**Comment by ValWood** [comment]
GO:0007343    egg activation
part_of
 single fertilization looks like a possible TPV?

**Comment by ukemi** [comment]
This doesn't sit well with me, but assigning to @vanaukenk to get another developmental biologist's opinion.

**Comment by ValWood** [comment]
In this case maybe a general parent term?

**Comment by ValWood** [comment]
GO:0009566  fertilization
Definition 
The union of gametes of opposite during the process of sexual reproduction to form a zygote. It involves the fusion of the gametic nuclei (karyogamy) and cytoplasm (plasmogamy).

The union of gametes of opposite  sexes *or mating types* during the process of sexual reproduction to form a zygote. It involves the fusion of the gametic nuclei (karyogamy) and cytoplasm (cytogamy).

plasmogamy does not even exist in GO,  should it be added as an exact synonym of cytogamy?

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Plasmogamy narrow symonym ?

**Comment by ValWood** [comment]
To support
"Presumably these are parallel processes. GO:0060468 | prevention of polyspermy can be independent of egg activation (although they occur simultaneously?)" above

In conclusion
Thus, mating repression in zygotes shares components with, but bifurcates from, meiotic induction.

**Comment by ValWood** [comment]
Final note:

The author also suggested

"Regulation of asymmetric gene expression from parental genomes"
Factor that regulates differential gene expression of homologous parental gene copies

Although important, this seems more like a consequence of the mechanism of the fertilization block. I wasn't sure if it was possible to capture this in GO, although there are a few terms related to the genration of asymettry in development I could not find anything related to  asymettric zygotic expression, or even a general asymettric process term. Any ideas?

**Comment by vanaukenk** [comment]
@ValWood - Working on this ticket, I am looking at the term GO:0000747 conjugation with cellular fusion that is a sibling of fertilization.
A few thoughts/questions that I have:  
If we update the definition of fertilization to include a reference to mating types do these two terms then start to overlap in meaning?  Would fertilization then need to be a parent of GO:0000747?
How often does the fungal community refer to 'fertilization' vs 'conjugation'?  
Would the existing 'negative regulation of conjugation with cellular fusion' be a better term, or parent for a new term, for what you're trying to capture with this paper?

**Comment by ValWood** [comment]
Thought:

I don't think "fertilization" and "conjugation with cellular fusion" are equivalent.

"conjugation with cellular fusion" is the yeast term for "mating". In fact, nobody really calls this "conjugation with cellular fusion" but we needed to use this term to disambiguate from 

GO:0007618   mating
The pairwise union of individuals for the purpose of sexual reproduction, ultimately resulting in the formation of zygotes.

which was bagged for the multicellular equivalent.

So i'm not an expert in this *at all* but I would say that  both processes (conjugation and mating)  are broader, and result in, or involve the 'fertilization of a gamete'.

It seems that the "prevention of polyspermy" is therefore a post-mating process?
(its a bit analogous to  the prevention of re-replication after replication has taken place)

I agree,  that this would also be a type of "negative regulation of conjugation with cellular fusion", but this is  a very general process which could apply at any stage in conjugation and missed the important post-conjugation aspect, very cooly demonstrated by this work (including the  exact mechanism).

The solution here would be to have  a sibling term to 
GO:0060468 | prevention of polyspermy

NTR prevention of polyzygosity in spores
this could have  parentage to a fertilization block, AND "negative regulation of conjugation with cellular fusion"

 @mah11  does that sound sensible to you
and @Antonialock  (I know you are busy too busy to look in detail)

**Comment by Antonialock** [comment]
I'm not completely following but I agree that conjugation with cellular fusion is analogous to mating.

I am not sure if prevention of polyspermy is always downstream of mating, there must also be mechanims  that go on during mating to ensure there is only one cell:cell fusion site?

**Comment by ValWood** [comment]
so the main question is

"is mating/conjugation" broader then fertilization. I think it definitely  is? (nobody uses these interchangably in yeast). Fettilization is only part_of the mating process.

if so, my preferred solution is 

make a more general parent
"term name: negative regulation of re-fertilization?

The negative regulation of fertilization process after initial fertilization event that prevents the fusion of more than two gametes? Or something along those lines?


make "prevention of polyspermy" a child of this

add a new child:

NTR prevention of polyzygosity in spores
this could have additional parentage to "negative regulation of conjugation with cellular fusion"

It would be great if I could do this soon, since it was a high profile Nature paper, and a community curation session. 
I forgot about it and I'd like to  make it live very soon.

**Comment by mah11** [comment]
> prevention of polyzygosity in spores

I agree that adding a new term is preferable to altering the existing GO:0060468, but this phrase does not make sense.

Zygosity isn't the same thing as ploidy, and the emphasis on spore ploidy will make hard to tell that the term would (or should) be usable for any yeasts, and maybe any fungi. (Remember that budding yeast doesn't usually undergo sporulation immediately after conjugation.)

I think it would be better for the term name to describe the actual regulation event itself, rather than its downstream consequences. Ideas:

negative regulation of conjugation with zygote
negative regulation of cell fusion with zygote during conjugation
negative regulation of conjugation between three or more cells


> "is mating/conjugation" broader then fertilization.

I've rarely seen "fertilization" used to refer to anything in yeast, and in the few cases I have seen have been a bit woolly - wordings have been imprecise enough to allow for either the "conjugation with cellular fusion" meaning or just the cell fusion part. So I don't think we should have a fungal-oriented term with "fertilization" in the name; related synonyms would be fine.

I don't know enough to comment on whether all prevention of polyspermy-or-analogous-problem is post-mating, for fungal or broader senses of "mating".

**Comment by ValWood** [comment]
Thanks!

I like
"negative regulation of conjugation between three or more cells"
since it is very clear   what  is being negatively regulated, and why it would be a synonym of 
GO:0060468 | prevention of polyspermy

**Comment by ValWood** [comment]
Any thought on this. I just noticed that we are still using 
"prevention of polyspermy" which is incorrect and looks strange!

**Comment by Antonialock** [comment]
I think I like "negative regulation of conjugation with zygote" best

I think it is more specific than ""negative regulation of conjugation between three or more cells" - this term could also any gene product that ensures that the cell only projects towards one other cell? (maybe?)

I think the "negative regulation of conjugation with zygote" captures the post fusion part ("post-fusion reconstitution of a bipartite transcription factor blocks re-fertilization")

I also think that the paper uses some "unconventional yeast language" - probably to put it in context of the broader scientific audience. I don't think yeast researchers typically refer to vegetatative or shmooing cells as 'gametes'. Or 'fertilization'.

**Comment by ValWood** [comment]
OK let's  go with that. We can always improve later.

>I also think that the paper uses some "unconventional yeast language" - probably to put it in context of the broader scientific audience. I don't think yeast researchers typically refer to vegetatative or shmooing cells as 'gametes'. Or 'fertilization'.

That may be so but GO is supposed to normalize  different language, or at least identify common parents.

**Comment by ValWood** [comment]
@vanaukenk  there seems to be a solution agreed on but not implemented.
Cheers
Val

**Comment by ValWood** [comment]
I think the proposal was 
NTR "negative regulation of conjugation with zygote"
(although we do not have "conjugation with zygote")

Can anyone suggest an appropriate definition?

**Comment by Antonialock** [comment]
"A process that prevents a zygote from fusing with additional cells " ?

**Comment by ValWood** [comment]
"A process that prevents a zygote from fusing with additional gametes " ?

**Comment by Antonialock** [comment]
maybe it is personal but I dislike calling yeast cells gametes

**Comment by ValWood** [comment]
OK! A process that prevents a zygote from fusing with additional cells "

**Comment by pgaudet** [comment]
So, the action is 

NTR "negative regulation of conjugation with zygote"
A process that prevents a zygote from fusing with additional cells "

* Can you please provide a reference ? 
* Are there other actions that I missed ?

**Comment by ValWood** [comment]
Nature
. 2018 Aug;560(7718):397-400. doi: 10.1038/s41586-018-0407-5. Epub 2018 Aug 8.
Gamete fusion triggers bipartite transcription factor assembly to block re-fertilization
Aleksandar Vještica 1, Laura Merlini 1, Pedro Junior Nkosi 1, Sophie G Martin 2
PMID: 30089908

**Comment by pgaudet** [comment]
1. Added new term: 

+[Term]
+id: GO:0140538
+name: negative regulation of conjugation with zygote
+namespace: biological_process
+def: "A process that prevents a zygote from fusing with additional cells." [PMID:30089908]
+is_a: GO:0060467 ! negative regulation of fertilization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16329 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-07T07:50:23Z

2. Made 'GO:0060468 prevention of polyspermy' a child of that new term. 

Thanks, Pascale

**Comment by ValWood** [comment]
@Antonialock 

Aleksander requested

There are two findings in the paper that I failed to capture by the availble terms.

1) Pi and Mi proteins govern ASYMMETRICALLY zygotic expression of their target mei3, such that it is more rapidly and robustly expressed from the P-cell genome.

2) Pi, Mi, Mei3, and Mei2 function to establish a re-fertilization block in zygotes. In the provided list of terms I have used the term "polyspermy block" which might not be the most suitable given that in yeast zygotes are produced by isogametes.

this term is for 2). Should I just replace the  current 'part_of' here?

https://curation.pombase.org/pombe/curs/46c89f342f117ca5/ro

**Comment by ValWood** [comment]
Ignore, it is further down the session

<img width="1078" alt="Screenshot 2020-11-08 at 08 50 31" src="https://user-images.githubusercontent.com/7359272/98460827-82a06b00-219f-11eb-8ba4-63bf2318b597.png">

but why does "prevention of polyspermy" show up as an unknown term?
I can still see it in QuickGO, and that should still exist @pgaudet ?

**Comment by ValWood** [comment]
@pgaudet Any idea what is happening here?

GO:0140538 is not yet available (they usually arrive the next day), and 
 the term we were using 
GO:0060468    prevention of polyspermy is no longer available (I can't see why, there are no taxon constraints?) but I cant put the session back  into our database

**Comment by pgaudet** [comment]
GO:0060468 prevention of polyspermy
has taxon constraints: 

GO:0007338 | single fertilization | Never in Taxon | 58024 | Spermatophyta |  
GO:0007338 | single fertilization | Only in Taxon | 2759 | Eukaryota
https://www.ebi.ac.uk/QuickGO/term/GO:0060468

I dont think this should block it for you ? 

===

For GO:0140538 negative regulation of conjugation with zygote: I created it on Nov 7th, and the last snapshot ran on Nov8th, I suppose it just missed it. You can view the most recent snapshot date here: 
http://snapshot.geneontology.org/metadata/release-date.json


Thanks, Pascale

**Comment by ValWood** [comment]
no don't worry. I just wante dto check that there wasn't a problem.

vsal

**Comment by pgaudet** [comment]
the fact that you dont see GO:0060468  seems odd.

**Comment by ValWood** [comment]
Hmm @mah11 @kimrutherford  any ideas (might be a Canto issue)

**Comment by ValWood** [comment]
I still don't see this term?

**Comment by balhoff** [comment]
@ValWood I thought we determined in #20362 that this was expected.

**Comment by ValWood** [comment]
sorry I should be precise ! "this" here is

+[Term]
+id: GO:0140538
+name: negative regulation of conjugation with zygote
+namespace: biological_process
+def: "A process that prevents a zygote from fusing with additional cells." [PMID:30089908]
+is_a: GO:0060467 ! negative regulation of fertilization
+property_value: term_tracker_item #16329 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-07T07:50:23Z

the replacement term further back in the ticket.

**Comment by balhoff** [comment]
@ValWood that term will be excluded by `owltools --make-species-subset` for the same reasons.

**Comment by ValWood** [comment]
That term was added for fission yeast though @pgaudet?

**Comment by ValWood** [comment]
I think we need to put the new term 

+id: GO:0140538
+name: negative regulation of conjugation with zygote

directly under sexual reproduction

**Comment by balhoff** [comment]
> directly under sexual reproduction

Looks like that would work.

**Comment by Antonialock** [comment]
> 
> 
> "A process that prevents a zygote from fusing with additional gametes " ?

I realized why I dislike the word 'gamete' for yeasts - and in your proposed context I think it would be ok to call them gamete (but keeping it at cells is also ok! I don't mean that it needs to change, I just wanted to clarify since I just had this epiphany)

Often, papers will refer to "spores" as "gametes" - but I think this is completely incorrect (spores are the progeny! Spores may go on to develop into gametes, but the 'spore form' itself is not a sexually capable state)

**Comment by ValWood** [comment]
Hi,

I still can't use this term. Is there any issue to moving it directly under 'sexual reproduction' ?

Thanks
Vl

**Comment by pgaudet** [comment]
Hi @ValWood 

Do you want 'negative regulation of conjugation with zygote' part_of 'sexual reproduction'  ? (I dont think is can be is_a?) 

What would be the is_a - the most general in 'biological regulation' but that seems too general. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Or can I use is_a 'negative regulation of reproductive process' ?

**Comment by Antonialock** [comment]
I don't think 'negative regulation of reproductive process' fits
- it's a QC mechanism to prevent an upstream process from happening again

2 gametes fuse -> zygote formation
once the zygote has formed you don't want any other gametes fusing with your zygote.

**Comment by pgaudet** [comment]
ok - what is the is_a parent then ?

**Comment by Antonialock** [comment]
I think the current parentage looks ok?
ia_a neg reg of fertilization
which is part_of sexual reproduction?

**Comment by pgaudet** [comment]
For info - regulation of fertilization is_a 'regulation of reproductive process'

**Comment by Antonialock** [comment]
are gene products that are involved in prevention of genome re-replication annotated to "negative regulation of DNA replication"
(I can't think of specific example gps for this to check) @ValWood ?

if they are then I guess it could be a neg reg of reproductive process?

**Comment by ValWood** [comment]
cdc18, I think...

**Comment by Antonialock** [comment]
till doesn't feel right in this context...maybe it's just me?

ensuring that a process progresses in the right order is not the same as negatively regulating the process?

**Comment by ValWood** [comment]
I don't know-  but when I surveyed all of PomBase annotations to "regulation of blah"
regulation falls into multiple classes and one of those  I classed as "downstream regulation",
negatively regulating the re-occurance of a process, or  for example disassembling a structure after a process has occurred. So perhaps it is OK?

I think there is a lot of scope for  defining different types of regulation more precisely  (otherwise we will never know what we mean by regulation)  but in the current system I don't think there is anything to prevent it being modelled in this way?

**Comment by ValWood** [comment]
I think it's fine becasuse it's analogous to "prevention of poilyspermy" and that has "negative regulation of fertilization parentage.

But it's a very good point that ideally  you need to know if this  is negative regulation of the process beginning at all, or negative regulation of re-initiating a  process.

**Comment by Antonialock** [comment]
ok thanks Val, that makes sense.

**Comment by pgaudet** [comment]
What's the action ?

**Comment by ValWood** [comment]
make 

+id: GO:0140538
+name: negative regulation of conjugation with zygote

a regulation of fertilization

**Comment by pgaudet** [comment]
> a regulation of fertilization

negative regulation of fertilization ? 

Also part_of 'sexual reproduction'   ? 

sorry about the back and forth

**Comment by pgaudet** [comment]
'negative regulation of fertilization' is a already there - if you dont want  part_of 'sexual reproduction' please close. 

Wow - had you put 'quick fix' on that one ;) ???

**Comment by ValWood** [comment]
"Quick fix" label is the kiss of death....

I still can't use the term today, which means that something is still incorrect from the taxon?????

**Comment by pgaudet** [comment]
Yes - fertilization is a multiorganism process. We are going around in circles....

**Comment by Antonialock** [comment]
so can't sexual reproduction (or adecendant) be an instance where multi-organism process is ok for unicerllular organisms? (how can you sexually reproduce without involving more than one organism?)

**Comment by ValWood** [comment]
I think there is an issue with the logic somewhere.  I still can't approve the session. I only took the session out of pom base  out to add this new term, and now I can't get it back into PomBase. I feel really bad as it's an important  recent Nature paper that a lot of people will look at and I'm sure the author will notice its absence soon....

https://curation.pombase.org/pombe/curs/46c89f342f117ca5

If it doesn't look like a fix is imminent  I will remove the terms temporarily. What do you think? Does anyone know what the problem is? I don't?

@balhoff ?

**Comment by ValWood** [comment]
but multi organism process should. be OK for any species that does sexual reproduction.
we use GO:0000747    conjugation with cellular fusion all the time with no problems?

**Comment by mah11** [comment]
@balhoff explained in https://github.com/geneontology/go-ontology/issues/20362#issuecomment-726391379 that fertilization inherits `never_in_taxon 'Schizosaccharomyces pombe'` via an axiom in the Cell Ontology. (Note: QuickGO doesn't show these inherited taxon constraints.)

The text definition of GO:0140538 is less specific than the term name:

GO:0140538 ! negative regulation of conjugation with zygote
def: "A process that prevents a zygote from fusing with additional cells." [PMID:30089908]

Having "conjugation" in the name also clashes with the link `GO:0060468 ! prevention of polyspermy is_a GO:0140538`, because sperm/egg fertilization is essentially never called conjugation.

Possible solutions:

- Move GO:0140538 to `is_a GO:0031138 ! negative regulation of conjugation with cellular fusion`, remove `GO:0060468 is_a GO:0140538`, and adjust the GO:0140538 text definition to match the name; or

- Rename GO:0140538 (e.g. to "negative regulation of cell fusion with zygote"), and move it to `is_a GO:2000242 ! negative regulation of reproductive process`; optional: also add a new term specifically for negative regulation of conjugation with cellular fusion; or

- Have the CL editors remove `'capable of' some 'multicellular organismal reproductive process'` from gamete (CL:0000300). In this case I would still edit either the name or the text def for GO:0140538 so they match.

**Comment by ValWood** [comment]
I am still unable to use
+id: GO:0140538
+name: negative regulation of conjugation with zygote

Is it possible to implement one of the above solutions?

**Comment by pgaudet** [comment]
Sorry Val, Travis had been down. 

I implemented the first suggestion: 

**GO:0140538 negative regulation of conjugation with zygote**
- changed def of '' to 'A process that prevents a zygote from fusing an additional cell.' 
- removed parent is_a: GO:0060467 ! negative regulation of fertilization
- added parent: is_a: GO:0031138 ! negative regulation of conjugation with cellular fusion

**GO:0060468 prevention of polyspermy**
- removed parent is_a: GO:0140538 ! negative regulation of conjugation with zygote


Should we still open a ticket for CL to remove 'capable of' some 'multicellular organismal reproductive process' from gamete (CL:0000300) ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Oh yes sorry I forgot about that, I wasn't sure there had been a final decision. Dying to get this one done!

**Comment by pgaudet** [comment]
OK done https://github.com/obophenotype/cell-ontology/issues/818

**Comment by ValWood** [comment]
ah right, is this about

>Should we still open a ticket for CL to remove 'capable of' some 'multicellular organismal reproductive process' from gamete (CL:0000300) ?


@Antonialock said
I also think that the paper uses some "unconventional yeast language" - probably to put it in context of the broader scientific audience. I don't think yeast researchers typically refer to vegetatative or shmooing cells as 'gametes'. Or 'fertilization'.

so
I think we should have made

+id: GO:0140538
+name: negative regulation of conjugation with zygote

is_a

GO:0031138    negative regulation of conjugation with cellular fusion

not is_a
GO:0060467    negative regulation of fertilization

**Comment by ValWood** [comment]
My fault sorry.

**Comment by balhoff** [comment]
> I think we should have made
> 
> +id: GO:0140538
> +name: negative regulation of conjugation with zygote
> 
> is_a
> 
> GO:0031138 negative regulation of conjugation with cellular fusion
> 
> not is_a
> GO:0060467 negative regulation of fertilization

Yes, I think this will remove the problem causing this to be excluded from pombe via --make-species-subset.

**Comment by ValWood** [comment]
yay! I'm doing a little dance in my kitchen!
