### ISSUE TITLE
Merge 'cellular response to dsRNA' into 'cellular response to exogenous dsRNA'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16323]
Following up on  #14263

We should merge 'GO:0071359 cellular response to dsRNA' into 'GO:0071360 cellular response to **exogenous** dsRNA', since this what the term was presumably created for (see discussion in  #14263) 

https://docs.google.com/spreadsheets/d/1CmncvLQ3y_eukC7OfT37NTAcT_1gB3SZTg8FALj0M4g/edit#gid=0

Groups impacted: 

Group | Number manual annotations
-- | --
MGI | 2
UniProt | 3
RGD | 6

**Comment by pgaudet** [comment]
@ukemi 
@ggeorghiou 
@slaulederkind 

Can you please have a look ? 

Thanks, Pascale

**Comment by ukemi** [comment]
PMID:24114535 suggests that endogenous RNA encoded by the Alu locus helps to trigger the inflammasome response in mice and humans. I think this needs to be investigated before this merge occurs. Do cells respond to endogenous retroviral transposons?

**Comment by ukemi** [comment]
PMID:26068187

**Comment by pgaudet** [comment]
How about a term like 'cellular response to retrotransposon-derived dsRNA'?

**Comment by ukemi** [comment]
But then what is the parent of both terms? I'm sure there are conserved mechanisms.

**Comment by pgaudet** [comment]
How about 'response to foreign dsRNA' ? PMID:15877599

**Comment by ukemi** [comment]
I don't know the field well enough to know if the mechanisms are completely conserved between responses to exogenous and endogenous dsRNA. If they are conserved, why not just have the generic term?

**Comment by deustp01** [comment]
My textbook says that for larger multicellular organisms, there are no endogenous dsRNAs, only exogenous (primarily viral) ones, and that's why innate immune responses triggered by any dsRNA are a good thing.

**Comment by ukemi** [comment]
But what about endogenous retroviruses? I was looking at this paper:
PMID:24114535

At some point are the stable ones considered endogenous? They become stable genome features.  MGI:2675046

**Comment by deustp01** [comment]
My textbook is incomplete and a bit out of date. However, from the introduction to the paper, it looks like the basic idea may be right: persistent dsRNA triggers innate immune reactions; the normal response to endogenous retroviral transcripts is immediate degradation.

"Geographic atrophy (GA) is an advanced form of age-related macular degeneration characterized by central loss of vision due to confluent areas of retinal pigmented epithelium (RPE) loss and overlying photoreceptor degeneration. To date, there is no approved therapy available for this disease, due largely to lack of clear understanding of its molecular pathogenesis. Recently, we showed that the microRNA (miRNA) processing enzyme DICER1 is specifically reduced in the RPE of GA eyes. The reduced DICER1 levels in the RPE result in an increased abundance of Alu RNA transcripts, which in turn promotes RPE cell death. **_Under healthy conditions, DICER1-mediated enzymatic processing metabolizes these Alu RNAs into innocuous cleavage fragments_**; consequently a deficit in DICER1 abundance results in an increased accumulation of toxic Alu RNA transcripts and RPE degeneration."

So on the one hand it is an endogenous dsRNA but on the other the response to it is not a normal process.

**Comment by deustp01** [comment]
(sorry - hit the wrong button)

**Comment by pgaudet** [comment]
Ah! Thanks Peter - so what is the function of DICER with respect to the Alu RNA transcripts ? Would it be ore correct to annotate to '    GO:0071025  RNA surveillance, "The chemical reactions and pathways resulting in the breakdown of RNA, ribonucleic acid, one of the two main type of nucleic acid, consisting of a long, unbranched macromolecule formed from ribonucleotides joined in 3',5'-phosphodiester linkage" (and a child of RNA catabolic process)? 

Pascale

**Comment by deustp01** [comment]
With the proviso that I'm totally non-expert here, RNA surveillance sounds right. That looks like a normal function and its failure leads to pathology.

**Comment by pgaudet** [comment]
@ukemi does that work for you ?

**Comment by slaulederkind** [comment]
I haven't seen a consideration of pre-miRNA, which is endogenous dsRNA.  Dicer is also a processer of pre-miRNA.

**Comment by slaulederkind** [comment]
The increase in a particular pre-miRNA will have an effect on various genes/gene products.  PMID:19958814 But you'd probably be more convinced of the need for endogenous dsRNA by considering siRNA. PMID:11238371

**Comment by pgaudet** [comment]
Hi @slaulederkind 
I am not convinced that the glutamate ionotropic receptor AMPA type subunit 1 *responds to* miRNA: in fact it seems to regulate them (although indirectly). How about "GO:0060964 regulation of gene silencing by miRNA"? Wouldn't that represent better the role of Gria1 here ? 

Pascale

**Comment by slaulederkind** [comment]
That's a good point about Gria1.  But for the general dsRNA issue, I think the siRNA duplex is reason enough to keep a term for endogenous dsRNA. PMID:11238371

**Comment by pgaudet** [comment]
The point is not that there is no endogenous dsRNA in the cell; the question is, is there a response to it? Can you give examples where that term would be relevant ?

**Comment by slaulederkind** [comment]
The kinase activity of Pkr responds to levels of dsRNA.  PMID:30174290

**Comment by RLovering** [comment]
isn't there also dsRNA when microRNAs anneal with their target mRNA? As well as dsRNA due to internal annealing?

**Comment by pgaudet** [comment]
But is this really a 'response'? Could it not be a more specific pathway, a bit like the 'RNA surveillance' that David encountered above ? I am trying to understand what the mtRNAs are signaling, but the paper only reports 'mtRNA binding' and the activation of Pkr following that binding.

**Comment by deustp01** [comment]
Here is another paper from the same authors that Stan cited earlier - PMID:24939934
Judging from their abstract, they are working hard to make the interaction of endogenous dsRNA and PRK behave like the initiation step of a signaling cascade:

> dsRNA-dependent protein kinase R (PKR) is a ubiquitously expressed enzyme well known for its roles in immune response. Upon binding to viral dsRNA, PKR undergoes autophosphorylation, and the phosphorylated PKR (pPKR) regulates translation and multiple signaling pathways in infected cells. Here, we found that PKR is activated in uninfected cells, specifically during mitosis, by binding to dsRNAs formed by inverted Alu repeats (IRAlus). While PKR and IRAlu-containing RNAs are segregated in the cytosol and nucleus of interphase cells, respectively, they interact during mitosis when nuclear structure is disrupted. Once phosphorylated, PKR suppresses global translation by phosphorylating the α subunit of eukaryotic initiation factor 2 (eIF2α). In addition, pPKR acts as an upstream kinase for c-Jun N-terminal kinase and regulates the levels of multiple mitotic factors such as cyclins A and B and Polo-like kinase 1 and phosphorylation of histone H3. Disruption of PKR activation via RNAi or expression of a transdominant-negative mutant leads to misregulation of the mitotic factors, delay in mitotic progression, and defects in cytokinesis. Our study unveils a novel function of PKR and endogenous dsRNAs as signaling molecules during the mitosis of uninfected cells.

Looking at the list of other papers citing this one, it's less clear whether this idea is getting much traction with other workers, but that's an annotation strategy issue - capture the consensus of the field or capture each distinct viewpoint?

**Comment by slaulederkind** [comment]
That sounds correct.  We use 'response to' when the data lacks details of the specific process being affected.

**Comment by pgaudet** [comment]
OK, I am leaving this as-is: 
- 'cellular response to dsRNA'
-- is_a  'cellular response to exogenous dsRNA'
