### ISSUE TITLE
obo json is implemented differently in robot vs owltools

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-ontology#16321]
It appears as if robot and owltools have two different implementations of obojson. I will present an example:

Given the obo:
```
[Term]
id: GO:1
name: obsolete class A
namespace: molecular_function
def: "OBSOLETE. Does A
is_obsolete: true
replaced_by: GO:2

[Term]
id: GO:2
name: replacement class
namespace: molecular_function
def: "A non obsolete class"

[Term]
id: GO:3
name: ferric iron import across cell outer membrane
namespace: biological_process
alt_id: GO:4
def: "The directed movement of ferric iron (Fe(III) or Fe3+)
comment: Ferric iron is rarely transported in the free form. 
```

With owltools (like in the go-ontology Makefile) this produces the contents of this gist: https://gist.github.com/dougli1sqrd/d6a182bd782657cf16c2ede1ed4431d1. Note how obsolete classes are formed, with the `deprecated: true` mapping in `meta` dictionary object (line 39 for example). 

With robot, we produce this: https://gist.github.com/dougli1sqrd/1c3831396a624bcd09170ccc59430097. Note how here the obsolete class is implemented as a full URI `owl:deprecated`. This is in a `meta` object, inside a `basicPropertyValues` object. (line 39 again for the example). 

Which format is correct? And whichever one is incorrect we should open tickets with the appropriate repo to correct the format.

**Comment by balhoff** [comment]
I opened a ticket: https://github.com/owlcollab/owltools/issues/292
