### ISSUE TITLE
NTR: Pi Mi complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16327]
Def
A transcription factor complex  composed of a homeodomain protein the M-specific  peptide Mi  and a that acts at the regulatory region of  genes required for the activation of meiosis.

Descendant of
GO:0090575    RNA polymerase II transcription factor complex

Nature. 2018 Aug;560(7718):397-400. doi: 10.1038/s41586-018-0407-5. Epub 2018 Aug 8.
Gamete fusion triggers bipartite transcription factor assembly to block re-fertilization.

Mei3 expression is under the regulation of two cell-type-specific factors, the P-specific homeodomain protein Pi and the M-specific 42-amino-acid peptide Mi6,7. We found that Pi and Mi formed complexes insensitive to nuclease treatment both in vivo and when expressed in bacteria (Fig. 2d, e). Mi co-expression also stabilized Pi levels (Fig. 2d). Chromatin immunoprecipitation experiments further showed that Pi and Mi associate with the mei3 promoter, but only when both proteins are present (Fig. 2f, Extended Data Fig. 2c). Thus, the Pi–Mi complex—but not its individual subunits—binds chromatin and induces mei3 expression.

**Comment by ukemi** [comment]
"A transcription factor complex composed of a homeodomain protein the M-specific peptide Mi and a that acts at the regulatory region of genes required for the activation of meiosis."

Seems like there is something missing in the def. peptide Mi and a what?

**Comment by ValWood** [comment]
"and" is in the wrong place!

homeodomain protein *and* the M-specific peptide Mi
