### ISSUE TITLE
references to external ontologies are causing Travis Failures

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#16349]
This morning while trying to obsolete a term, the Travis checked failed because the term was used in an external ontology. This check should only fail if the term is used in GO and not an imported ontology. Otherwise we become dependent on changes to external ontologies before we can conduct our work.

ROBOT_JAVA_ARGS=-Xmx8G robot merge --input go-edit.obo verify --queries ../sparql/obsolete-reference-violation.sparql -O reports/
FAIL Rule ../sparql/obsolete-reference-violation.sparql: 1 violation(s)
goTerm,obsolete
http://purl.obolibrary.org/obo/UBERON_0001967,http://purl.obolibrary.org/obo/GO_0008004
VERIFICATION FAILED there were violations of at least one rule
For details see: http://robot.obolibrary.org/
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.

**Comment by cmungall** [comment]
@dougli1sqrd can you look into providing a solution within ROBOT?

@ukemi in this case I didn't see the obsoletion notice go out. I saw the original https://github.com/obophenotype/uberon/issues/1436 but then in #15652 the last comment says the term was resurrected....

**Comment by cmungall** [comment]
@dougli1sqrd  - The robot extension might be generally useful but in this case the blockage is serving a useful function, so deprioritize this.

@ukemi - a new uberon release is out and will percolate by midnight tonight

quick tip; to check the release version:

```
$ curl -L -s http://purl.obolibrary.org/obo/uberon.owl | grep versionIRI
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/uberon/releases/2018-07-30/uberon.owl"/>
^C
```

You should see 2018-09-10. After that you can rebuild the import and the dependency should be removed.

**Comment by pgaudet** [comment]
Did we decide NOT to do this ? @cmungall it seems you think this is the desired behavior?

**Comment by cmungall** [comment]
correct, no need for a change in robot behavior. The immediate issue was solved by a rebuild of anatomy this a.m
