### ISSUE TITLE
Remove all obsolete terms from all slims 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16348]

**Comment by ukemi** [comment]
See discussion here: #16147

**Comment by pgaudet** [comment]
Terms impacted: 

GO:0009370 signal transducer activity
subset: goslim_aspergillus 
subset: goslim_candida
subset: goslim_chembl
subset: goslim_generic 
subset: goslim_metagenomics
subset: goslim_plant 
subset: goslim_yeast 


----
GO:0005624 obsolete membrane fraction
subset: goslim_aspergillus
subset: goslim_candida
subset: goslim_yeast 


----

GO:0070271 obsolete protein complex biogenesis
subset: goslim_yeast

---
GO:0030528 obsolete transcription regulator activity
REPLACED BY GO:0140110 transcription regulator activity
subset: goslim_plant 

---

GO:0044460 obsolete flagellum part 
subset: gocheck_do_not_annotate

---

GO:0097285 obsolete cell-type specific apoptotic process
subset: gocheck_do_not_annotate


@srengel  @tberardini  	@marekskrzypek @PruMM

Please create a new ticket if you would like further changes to your slim. 

Thanks, Pascale
