### ISSUE TITLE
NTR: BCOR complex

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#16344]
Hi,
Can I please have a new term based on PMID:16943429, PMID:24515802 and PMID:22325352?

Definition:
A protein-containing complex that monoubiquitinates histone H2A on K119, thus it facilitates the maintenance of the transcriptionally repressive state of some genes, such as BCL6. It consists of the corepressor BCOR or BCORL1, a Polycomb group (PcG) and a SCF ubiquitin ligase subcomplexes.
 In mammals, the core subunits of the complex include the PcG and PcG-associated proteins NSPC1, RING1, RNF2, and RYBP and the components of the SCF ubiquitin ligase, SKP1, and FBXL10. 

Synonyms:
BCL6 corepressor (BCOR) complex (exact)
BCOR/BCORL1 complex  (exact)
Non-canonical PRC1-BCOR complex (exact)
Non-canonical BCOR-PRC1.1 Complex (exact)
PRC1.1 complex (exact)

It should be a child of GO:0000152 'nuclear ubiquitin ligase complex'.

Thanks,

Penelope

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140261
+name: BCOR complex
+namespace: cellular_component
+def: "A protein-containing complex that monoubiquitinates histone H2A on K119, thus it facilitates the maintenance of the transcriptionally repressive state of some genes, such as BCL6. It consists of the corepressor BCOR or BCORL1, a Polycomb group (PcG) and a SCF ubiquitin ligase subcomplexes.\nIn mammals, the core subunits of the complex include the PcG and PcG-associated proteins NSPC1, RING1, RNF2, and RYBP and the components of the SCF ubiquitin ligase, SKP1, and FBXL10." [PMID:16943429, PMID:22325352, PMID:24515802]
+synonym: "BCL6 corepressor (BCOR) complex" EXACT []
+synonym: "BCOR/BCORL1 complex" EXACT []
+synonym: "non-canonical BCOR-PRC1.1 complex" EXACT []
+synonym: "non-canonical PRC1-BCOR complex" EXACT []
+synonym: "PRC1.1 complex" EXACT []
+is_a: GO:0000152 ! nuclear ubiquitin ligase complex
+created_by: pg
+creation_date: 2018-09-11T09:35:05Z

**Comment by pgaudet** [comment]
sorry @vanaukenk I accidentally saw this ticket as mine

**Comment by pgarmiri** [comment]
Thanks!
