### ISSUE TITLE
Annotation not in QuickGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16359]
Hi @tonysawfordebi 

remind me, don't you import MODs IPI annotations?
i.e.

  | lsc1 | Lsk1 associated cyclin |   | CTDK-1 complex |   | PomBase | Schizosaccharomyces pombe | IPI

If not what is the reason? I forget?

**Comment by tonysawfordebi** [comment]
Yes, we do - the only evidence code we don't import is IEA.

**Comment by ValWood** [comment]
It's 

PomBase	SPBC530.13	lsc1		GO:0070692	PMID:17502918	IPI	PomBase:SPAC2F3.15	C	Lsk1 associated cyclin		protein	taxon:4896	20151109	PomBase

**Comment by tonysawfordebi** [comment]
Unless I'm missing something, that annotation *is* visible in QuickGO:

https://www.ebi.ac.uk/QuickGO/annotations?reference=PMID:17502918

(PomBase:SPBC530.13 maps to UniProtKB:O59748)

**Comment by ValWood** [comment]
OK sorry. My bad.
I thought we could not see it last night when looking at PAINT annotations. 

@pgaudet

**Comment by pgaudet** [comment]
great
