### ISSUE TITLE
missing  hexose transport processes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16357]
gluconate import across plasma membrane 
child of
gluconate transmembrane transport
~carbohydrate import across plasma membrane~

hexose import across plasma membrane 
child of
hexose transmembrane transport
and
carbohydrate import across plasma membrane 

standard defs

to improve
https://www.pombase.org/reference/PMID:10735857

**Comment by deustp01** [comment]
Problem - gluconate (CHEBI:24265) is not a carbohydrate (CHEBI:16646). Not sure about this, but I'd expect this distinction matters for the biology, that hexose transporters wouldn't work on organic anions and vice versa.

**Comment by ValWood** [comment]
OK in that case Pascale that PAINT family we just looked at can't have  hexose or carbohydrate as for some of that group the only identified substrate was gluconate...
https://github.com/geneontology/go-annotation/issues/1315

I will fix parentage request above.

**Comment by ValWood** [comment]
NTR: gluconate import across plasma membrane
child of
GO:0035429    gluconate transmembrane transport

and
NTR hexose import across plasma membrane
child of
GO:0008645 hexose transmembrane transport
and
GO:0098704 carbohydrate import across plasma membrane

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140270
+name: gluconate import across plasma membrane
+namespace: biological_process
+def: "The directed movement of gluconate from outside of a cell, across the plasma membrane and into the cytosol." [GOC:vw]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:24265 ! gluconate
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-10-01T08:47:35Z
+
+[Term]
+id: GO:0140271
+name: hexose import across plasma membrane
+namespace: biological_process
+def: "The directed movement of hexose from outside of a cell, across the plasma membrane and into the cytosol." [GOC:vw]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: imports CHEBI:18133 ! hexose
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2018-10-01T08:49:49Z
