### ISSUE TITLE
'division septum assembly' incorrectly part_of 'mitotic cell cycle'  - creates incorrect taxon constraints

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16365]

**Comment by pgaudet** [comment]
'GO:0000918 division septum assembly'
has the following logical definition: 

'cellular component assembly'
 and ('part of' some 'mitotic cell cycle')
 and (results_in_assembly_of some 'division septum')

However 'mitotic cell cycle' is limited to eukaryotes. Would it be OK to replace 'part of some mitotic cell cycle' by 'cytokinesis'? 

@ValWood 

Thanks, Pascale

**Comment by ValWood** [comment]
I think that would be fine.

As primary and secondary septa are restricted  to eukaryotes (at least as far as we know), could they still have the parent "
GO:1902410    mitotic cytokinetic process

(this keeps them under  mitotic cell cycle, as this is a "mitotic cell cycle process" in eukaryotes

**Comment by vanaukenk** [comment]
Should we also place taxon restrictions on any GO terms that refer to a cell septum?  

The definition of cell septum references a cell wall:

Definition
A structure composed of peptidoglycan and often chitin in addition to other materials. It usually forms perpendicular to the long axis of a cell or hypha and grows centripetally from the cell wall to the center of the cell and often functions in the compartmentalization of a cell into two daughter cells.

But I have seen cell septum terms used for a handful of metazoan annotations, so perhaps a never_in_taxon 'metazoa' for cell septum terms?

I can make a separate ticket for that, if this seems an okay thing to do.

**Comment by ValWood** [comment]
Hi @vanaukenk  I think a taxon restriction would be correct here. It's  definitely a cell wall related feature. and composed of cell wall material.
if there is another type, it wont fit this def and we would need a new term for it anyway....

**Comment by jimhu-tamu** [comment]
We were looking at some CACAO annotations related to septum formation and came across this issue when searching for 'septum" as a keyword. I'm not sure I understand what happened, but while primary and secondary may be eukaryote specific, I don't think division septum itself should have the eukaryotic taxon constraint that comes from inheritance from mitosis.

**Comment by pgaudet** [comment]
@jimhu-tamu Can you tell me which terms are causing problems? I thought I only added taxon constraints for primary and secondary septum; i cannot find them on 'cell septum assembly' and 'regulation of cell septum  assembly'. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Neither can I find taxon constraints on the CC terms 'cell septum' or 'division septum'.

**Comment by ValWood** [comment]
Oh right. I thought the problem was the parentage of "cell septum assembly", but this seems OK. It has no parentage to the mitotic cell cycle.

**Comment by jimhu-tamu** [comment]
Maybe it was an older version. I'm not seeing it now and I was looking on QuickGO with a student during CACAO class a week ago. 

The term we want to use is GO:0000918 division septum site selection based on mutants that make extra division septa.

The concerns I see now are:
* The parentage of the assembly term includes: GO:0061640 cytoskeleton-dependent cytokinesis. Is the definition of that excluding prokaryotes?
* Some exact synonyms of GO:0000917 should be changed to narrow.

**Comment by ValWood** [comment]
the parent has the comment

Note that this term should not be used for direct annotation. When annotating eukaryotic species, mitotic or meiotic cytokinesis should always be specified for manual annotation and for prokaryotic species use 'FtsZ-dependent cytokinesis ; GO:0043093' or Cdv-dependent cytokinesis ; GO:0061639. Also, note that cytokinesis does not necessarily result in physical separation and detachment of the two daughter cells from each other.

I'm not sure what plants would use ?

**Comment by pgaudet** [comment]
Changes made: 

 - [ ] ' GO:0000918 division septum site selection' removed parent  'relationship: part_of GO:0061640 ! cytoskeleton-dependent cytokinesis' (kept 'part of' some 'division septum assembly'; this should be OK for both prok and euk)

 - Fixed synonym types for GO:0000917 division septum assembly

-synonym: "division septum assembly involved in cell cycle cytokinesis" EXACT []
-synonym: "division septum assembly involved in cell cycle cytokinesis involved in mitotic cell cycle" EXACT [GOC:TermGenie]
+synonym: "division septum assembly involved in cell cycle cytokinesis" NARROW []
+synonym: "division septum assembly involved in cell cycle cytokinesis involved in mitotic cell cycle" NARROW [GOC:TermGenie]
 synonym: "division septum formation" EXACT [GOC:mah]
-synonym: "division septum formation involved in cell cycle cytokinesis" EXACT []
-synonym: "division septum formation involved in cell cycle cytokinesis involved in mitotic cell cycle" EXACT [GOC:TermGenie]
-synonym: "division septum formation involved in mitotic cell cycle" EXACT [GOC:TermGenie]
+synonym: "division septum formation involved in cell cycle cytokinesis" NARROW []
+synonym: "division septum formation involved in cell cycle cytokinesis involved in mitotic cell cycle" NARROW [GOC:TermGenie]
+synonym: "division septum formation involved in mitotic cell cycle" NARROW [GOC:TermGenie]
 synonym: "formation of division septum" EXACT []
-synonym: "formation of division septum involved in mitotic cell cycle" EXACT [GOC:TermGenie]
-synonym: "mitotic division septum assembly" EXACT []
+synonym: "formation of division septum involved in mitotic cell cycle" NARROW [GOC:TermGenie]
+synonym: "mitotic division septum assembly" NARROW []
 synonym: "septation" BROAD []
 synonym: "septin assembly and septum biosynthesis" RELATED []
-synonym: "septin assembly and septum biosynthesis involved in mitotic cell cycle" RELATED [GOC:TermGenie]
+synonym: "septin assembly and septum biosynthesis involved in mitotic cell cycle" NARROW [GOC:TermGenie]
 synonym: "septin assembly and septum formation" RELATED []
-synonym: "septin assembly and septum formation involved in mitotic cell cycle" RELATED [GOC:TermGenie]
+synonym: "septin assembly and septum formation involved in mitotic cell cycle" NARROW [GOC:TermGenie]

**Comment by pgaudet** [comment]
@ValWood 
The term for plants is 'cytokinesis by cell plate formation' - however it wasn't a 'is_a' cytokinesis. I added the parent - @tberardini Is this right ?

**Comment by pgaudet** [comment]
In fact 'cytokinesis by cell plate formation' was 
- is_a mitotic cytokinetic process; I replaced that by 'is_a' cytokinesis. OK @tberardini

**Comment by tberardini** [comment]
Yes, ok to move 'cytokinesis by cell plate formation' to is_a 'cytokinesis.

For record: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3676507/
