### ISSUE TITLE
rename: oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, 2-oxoglutarate as one donor, and incorporation of one atom each of oxygen into both donors

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16361]
GO:0016706
oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, 2-oxoglutarate as one donor, and incorporation of one atom each of oxygen into both donors

to 
2-oxoglutarate-dependent dioxygenase activity
(it is an exact synonym already)

**Comment by ukemi** [comment]
The standard practice is to follow the nomenclature from the EC reference. IN this case, it is the more complicated term. Unless we decide to change this policy, we will leave the simpler term as an exact synonym.

**Comment by pgaudet** [comment]
GO:0016706 has a x-ref to a partial EC: 
> Oxidoreductases
Acting on paired donors, with incorporation or reduction of molecular oxygen

Looks like the second part just describes what's in common - the label seems to be just 'oxidoreductases' - so perhaps it's not so heretic if we change the GO label as @ValWood suggests ?

**Comment by ValWood** [comment]
;) 
It was  a very annoying term name , it was almost a story ;)
