### ISSUE TITLE
odd parentage for GO:2000144    positive regulation of DNA-templated transcription, initiation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16362]
GO:2000144    positive regulation of DNA-templated transcription, initiation
has the parent
GO:0031334    positive regulation of protein complex assembly?

@pgaudet  Is that intentional?
for example all mediator subunis become annotated to 
GO:0031334    positive regulation of protein complex assembly
which look very odd?

**Comment by pgaudet** [comment]
I haven't much touched the Process branch yet. This parent has been there since 2010. I thik it related to the synonym 'positive regulation of DNA-dependent RNA polymerase complex assembly at promoter', which is more or less what transcription initiation is.  To be discussed with the transcription group.

**Comment by ValWood** [comment]
Is this true though? We recently said that  members of a complex were not involved in assembly.  Isn't the assembly autonomous?

**Comment by pgaudet** [comment]
To be discussed with @colinlog

**Comment by colinlog** [comment]
Concerning assembly and transcription: perhaps the naming 'GO:0031334 positive regulation of protein complex assembly' is confusing, but indeed, the gist of it **is** what Pascal stated above on Sept. 2018. As literature support I would like to invoke a passage from the summary of a chapter written by Patrick Cramer, a famed structural biologist in the field of transcription. The reference is a book:   "Molecular Biology of Assemblies and Machines by Alasdair Steven, Wolfgang Baumeister, Louise N. Johnson, Richard N. Perham". The passage reads: "In eukaryotes, the TATA box is recognized by a subunit of General Transcription Factor TFIID. TFIID and other General Transcription Factors combine with RAN polymerase II to form the pre-initiation complex (PIC) on promoter DNA. The mediator complex stabilizes the PIC and communicates signals from gene-specific transcription factors, which mainly bind upstream from the start site and can act positively (activators) or negatively (repressors)."  So, G0031334 could be re-described as  'positive regulation of protein complex formation'?  OR, perhaps much better? GO:0031334 could have a child that is defined as  'positive regulation of protein-DNA complex formation' and that could be linked to GO:2000144, breaking the  direct link between 31334 and 2000144 that rightly offends Val? Of course, a 'negative regulation ...' would then be expected as well.

**Comment by pgaudet** [comment]
@ValWood I dont see that relation- can you please check ? 

![image](https://user-images.githubusercontent.com/4782928/76326621-3556bb80-62e9-11ea-8015-f0aa4b5da2c2.png)

**Comment by ValWood** [comment]
I have no idea what I was looking at!
