### ISSUE TITLE
zombie slims

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16372]
This is likely a question for @cmungall 

Most of the slims I removed are cleanly gone from the ontology, however goslim_goa and gosubset_prok seem to be coming back from some import : 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/4782928/45425950-11d29680-b69b-11e8-8462-fd92d55c98d0.png">

Any idea what's happening ? Should we just ignore this or do we need to remove these slims from [wherever they are coming from]? 

Thanks, Pascale

**Comment by ukemi** [comment]
It looks like they are coming from extensions/x-disjoint.owl

**Comment by ukemi** [comment]
If you hover over the term, it will say where it comes from. Then if you go to the top menu bar in protege, you can switch ontologies in the drop down menu. Switch to go/imports/x-disjoint.owl.
Now search on object properties and you will see the zombie ones appearing as bold under subset property. As for whether or not it is safe to edit this file.....?

**Comment by ukemi** [comment]
For example:

https://github.com/geneontology/go-ontology/blob/master/src/ontology/imports/x-disjoint.owl

has this:

    

    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/go/extensions/x-disjoint#goslim_candida">
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Candida GO slim</rdfs:comment>
        <rdfs:subPropertyOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#SubsetProperty"/>
</owl:AnnotationProperty>
