### ISSUE TITLE
NTR: zearalenone biosynthetic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#16376]
Accession: GO:xxxxxx
Name: zearalenone biosynthetic process
Ontology: biological_process
Synonyms: zearalenone anabolism, zearalenone biosynthesis, zearalenone formation, zearalenone synthesis
Definition: The chemical reactions and pathways resulting in the formation of zearalenone, a mycotoxin produced by several _Fusarium_ species, is most commonly found as a contaminant in stored grain and has chronic estrogenic effects on mammals.
is_a: GO:0043386 ! mycotoxin biosynthetic process
is_a: GO:0033068 ! macrolide biosynthetic process
Source: CHEBI:10106, PMID:16517624, PMID:20578001

**Comment by hdrabkin** [comment]
GO:0043386
