### ISSUE TITLE
missing parent of endoplasmic reticulum-plasma membrane tethering

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16377]
should 
GO:0044232 organelle membrane contact site
be a parent of
endoplasmic reticulum-plasma membrane tethering
?
cheers

**Comment by ValWood** [comment]
endoplasmic reticulum-plasma membrane tethering P
GO:0044232 organelle membrane contact site C

**Comment by ValWood** [comment]
but  endoplasmic reticulum-plasma membrane contact site
is requested if that is what you need:
https://github.com/geneontology/go-ontology/issues/16304
