### ISSUE TITLE
NTR: methylated histone binding

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16389]
We received this term request from a PomBase community curator. From #16186 it wasn't completely clear whether GO will retain the "histone binding" branch in the long term, but in case they are kept for long enough to make it worthwhile, we'd like to use the requested new term.

Here's a stanza modeled on GO:0035064:

id: GO:new
name: methylated histone binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with a histone in which a residue has been modified by phosphorylation. Histones are any of a group of water-soluble proteins found in association with the DNA of eukaroytic chromosomes." [GOC:mah, PMID:20679485]
is_a: GO:0042393 ! histone binding
is_a: GO:0140031 ! phosphorylation-dependent protein binding

**Comment by hdrabkin** [comment]
Term already exits in ontology GO:0035064; 
Done

**Comment by hdrabkin** [comment]
Need more coffee; 
GO:0106153
Done
