### ISSUE TITLE
NTR: Perithecium formation

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#16392]
Hi,
I have previously submitted NTRs for protoperithecium formation and perithecium development (#15616 ). Thanks a lot for providing these terms. 

Can I request perithecium formation as a child term of perithecium development?

Here is the definition:
Accession: GO:xxxxxx
Name: Perithecium formation
Ontology: biological_process
Definition: The process of producing flask-shaped fruiting bodies, called perithecia. In the ascomycetous fungi such as Neurospora crassa and Sordaria macrospora, these perithecia are formed in the sexual phase and they discharge ascospores through the ostiolum at the tip of the perithecial neck.
is_a: GO:0120165 ! perithecium development
Source: BTO:0002164, PMID:19547974, PMID:21134480, PMID:25311923, DOI:10.1007/978-3-642-00286-1_2

Thanks & best wishes,
Achchuthan

**Comment by hdrabkin** [comment]
GO:0106154
done
