### ISSUE TITLE
New Term Request: pollen aperture formation

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16396]
New term requested

term name: pollen aperture formation
definition: specification and process of forming apertures, or areas where exine is reduced or absent, in the pollen cell wall.
suggested parentage: part of GO:0010208 pollen wall assembly
reference: PMID:30150313

**Comment by ukemi** [comment]
Hi @lreiser 
I don't see pollen aperture in the PO or in cellular component. Does it make sense to add it to CC? It seems from the definition that it is a region of the cell wall.

**Comment by ukemi** [comment]
or perhaps part of the pollen wall (GO:0043667)? Should this be a type of cell wall and is it distinct from pollen coat?

**Comment by lreiser** [comment]
It could be added as a part of the pollen wall- a region where the exine is absent or reduced. I have no annotation to that particular term tho- the proteins involved are located in the PM in the region where the aperture forms-probably having something to do with inhibiting production/secretion of exine in those regions.

**Comment by ukemi** [comment]
OK. I tweaked your definition a bit. I will link my commit to this ticket. If what I did doesn't work for you, reopen this and let me know how to fix it.

**Comment by lreiser** [comment]
okey dokey
