### ISSUE TITLE
add synonyms to GO:1905368 peptidase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#16391]
Please add synonyms:

protease complex [EXACT] 
(cf GO:0008233 peptidase activity - protease activity [EXACT])

Tryptase complex [NARROW]
- unless you think it should be a child term. But it doesn't differ in function from its parent. PMID:29661938
It would just be nice to have a search result for tryptases :)

Thanks,
Birgit

**Comment by hdrabkin** [comment]
done.
