### ISSUE TITLE
Merge 'GO:0033216 ferric iron import' into parent 'GO:0006826 iron ion transport'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16408]
Dear all, 

~The proposal has been made to obsolete 'GO:0033216 ferric iron import'. 
The reason for obsoletion is that this term is not precise enough. There are EXP 5 annotations and 2 IC annotations (the rest are ISO, IEA and IBA). There are no mappings. The term is not present in any slim.~

Annotations are here: https://github.com/geneontology/go-ontology/issues/16408
https://docs.google.com/spreadsheets/d/1R7q8p7s4m_PF5dhkW09o1ghgpyYRxdyGF7jr5Kb6ezo/edit#gid=0

Any comments can be  added to the issue: . 
~We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on October 1st, 2018. Unless objections are received by October 1st, 2018, we will assume that you agree to this change.~

Thanks, Pascale

**Comment by pgaudet** [comment]
I'll merge into the parent GO:0006826 iron ion transport for now.

**Comment by RLovering** [comment]
Brilliant, so in theory I don't need to edit anything.

**Comment by pgaudet** [comment]
you might need to look at a few little things ;)

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/16415 Done

**Comment by hdrabkin** [comment]
So seeing this upon getting back from a meeting 
FERRIC means iron 3 ( Fe3+); that's far more precise than iron ion. 
There is also a Ferrous form (Fe2+).  Our annotations were to the Fe3+ import
In fact, one of the papers the point was to distinquish between Fe2+ vs Fe3+ 
"Reduction of Fe(III) to Fe(II) seems to be a prerequisite for iron uptake by the intestine in both mice and humans. This enzymatic  step  is  bypassed  if  iron  reaches  the  microvillous
membrane as Fe(II), eg, when excess ascorbic acid or orange juice is added to the radioactive iron test dose.1 We therefore compared Fe(III) and Fe(II) iron absorption steps in control B6 and b2m2/2 mice"
That distinction is now gone from our annotations.

**Comment by pgaudet** [comment]
Hi @hdrabkin 

I reorganized the iron transport branch significantly - see #14892 and image below. 

In cells other than bacteria, ferric iron is transported either via 'reductive iron assimilation' or by endocytosis (by binding to transferrin). That endocytic part is not yet finished, I hope to do this this week. (Note that my changes shown below are not yet merged).  

<img width="409" alt="image" src="https://user-images.githubusercontent.com/4782928/46820949-74c85380-cd55-11e8-8e2f-1688ea740f24.png">

Thanks, Pascale
