### ISSUE TITLE
NTR: Woronin body (Fungi)

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#16401]
Accession: GO:xxxxxx
Name: Woronin body
Ontology: cellular_component
Definition: Woronin body is a peroxisome-derived dense-core vesicle that seals septal pores upon hyphal lysis to prevent excessive cytoplasmic loss. It is specific to several genera of filamentous ascomycetes. 
is_a: GO:0005777 ! peroxisome
Taxonomic restriction: NCBITaxon:4890 ## Ascomycota
Source: PMID:12640443, PMID:15155882, PMID:18227279, PMID:20707002, PMID:23882222

**Comment by pgaudet** [comment]
Hi @Achchuthan 
Is Woronin body a type of peroxisome ? It looks like it is derived from it (I am not sure what the relation would be - @ukemi what do you recommend? )

Thanks, Pascale

**Comment by ukemi** [comment]
If it is distinct, but derived from it, then based on the definition above it should be a type of dense core granule. The distinction looks straightforward in the ontology. A dense core granule is a type of secretory vesicle. If it is related to or derived from the peroxisome, then it could be a type of microbody.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140266
+name: Woronin body
+namespace: cellular_component
+def: "Peroxisome-derived dense-core vesicle that seals septal pores upon hyphal lysis to prevent excessive cytoplasmic loss. It is specific to several genera of filamentous ascomycetes." [PMID:12640443, PMID:15155882, PMID:18227279, PMID:20707002, PMID:23882222]
+is_a: GO:0042579 ! microbody
+relationship: only_in_taxon NCBITaxon:4890 ! Ascomycota
+created_by: pg
+creation_date: 2018-09-24T14:53:37Z

**Comment by Achchuthan** [comment]
HI @pgaudet ,
Thank you very much for adding Woronin body to GO. I agree with your classification of it to microbody as parent term. This is definitely a kind of vesicle that is derived from peroxisome, but, it is distinct from peroxisome.

Thanks & best wishes,
Achchuthan
