### ISSUE TITLE
Many terms look like they are missing parent 'post-translational protein modification

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16405]
Why are these not under GO:0043687 'post-translational protein modification'? 

'protein acylation'
'protein ADP-ribosylation'
'protein alkylation'
'protein amidation'
'protein arginylation'
'protein biotinylation'
'protein carbamoylation'
'protein carboxylation'
'protein de-ADP-ribosylation'
'protein deacylation'
'protein dealkylation'
'protein deamination'
'protein deglutathionylation'
'protein deglycation'
'protein deglycosylation'
'protein dehydration'
'protein delipidation'
'protein denucleotidylation'
'protein dephosphorylation'
'protein desulfurization'
'protein esterification'
'protein flavinylation'
'protein glucuronidation'
'protein glutathionylation'
'protein glycosylation'
'protein halogenation'
'protein hydroxylation'
'protein initiator methionine removal'
'protein lipidation'
'protein modification by small protein conjugation or removal'
'protein nitrosylation'
'protein nucleotidylation'
'protein oxidation'
'protein phosphopantetheinylation'
'protein phosphorylation'
'protein polyamination'
'protein prenylation'
'protein sialylation'
'protein sulfation'
'protein sulfhydration'
'protein tyrosinylation'
''protein-tetrapyrrole linkage'

Thanks, Pascale

**Comment by ukemi** [comment]
I remember this as well. If I recall correctly there was also discussion about whether or not removing the group was a post-translational modification. I guess technically we could consider it one.

**Comment by ukemi** [comment]
Going to close this. If we want to investigate each one individually, we should go that route.
