### ISSUE TITLE
missing parent to GO:0005925 focal adhesion

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16402]
hello, 

shouldn't GO:0005925 focal adhesion be part_of GO:0031012 extracellular matrix

cheers

**Comment by ValWood** [comment]
I don't think it is actually part_of

Probably adjacent_to?

Small region on the surface of a cell that anchors the cell to the extracellular matrix and that forms a point of termination of actin filaments.

**Comment by ukemi** [comment]
Certainly not part_of.

**Comment by ukemi** [comment]
Looking at adjacent_to, I'm a bit hesitant of using it as well. It says the two structures need to share a boundary. It has only been used for membranes in GO, but it has been used for a lot of anatomical structures in UBERON. It doesn't quite fit for a focal adhesion or its parent a cell-substrate adherens junction.
