### ISSUE TITLE
Change parentage request: pollen wall

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16413]
Hi
In the course of reviewing the Plant GO slim terms and associated annotations I found (realized)  that pollen wall terms were children of 
 GO:0030312 external encapsulating structure

It makes sense to me that the pollen wall should be  a child instance of  sexual spore wall (GO:0097514)

**Comment by ukemi** [comment]
Is pollen really a spore?

**Comment by lreiser** [comment]
Well technically the direct product of meiosis is the microspore and there is usually a mitotic division or two to produce generative/vegetative cells. SO if the definition is narrow (directly a product of meiosis) . Maybe the solution for us is to modify the plant GO slim to include pollen wall, not the parent term. It just seemed weird to me to see it there.

**Comment by vanaukenk** [comment]
@lreiser - let me know if you'd still like any changes to the parentage.  Thx.

**Comment by rachhuntley** [comment]
Hi Leonore,
Just to let you know that we put pollen wall under external encapsulating structure based on discussions with Laurel Cooper in this ticket https://github.com/geneontology/go-ontology/issues/15306

**Comment by lreiser** [comment]
Thanks Rachel, I can see why it was there. I was trying to understand the use of external encapsulating structure in the plant GO Slim, and so was looking at the terms that had annotations in plants- seems like its all around pollen wall. As a plant biologist- would you be OK with using pollen wall for the slim term rather than its parent. Most of the terms below are in cell wall (which makes sense)

**Comment by rachhuntley** [comment]
I think pollen wall would be fine as the slim term rather than the parent. We couldn't put pollen wall as a cell wall as it surrounds more than one cell.
