### ISSUE TITLE
NTR: Negative Regulation of CRISPR-cas system

### ISSUE THREAD

**Issue by jdc-cpt** [geneontology/go-ontology#16423]
New Term: Negative regulation of CRISPR-cas system
Definition: Negative regulation of an adaptive immune response of bacteria that serves to clear host cells of foreign DNA and RNA. It has three distinct stage: acquisition of foreign DNA by integration into CRISPR loci in the host chromosome, CRISPR RNA (crRNA) biogenesis, and target interference. CISPR stands for Clustered Regularly Interspaced Short Palindromic Repeat, which describes the nature of the loci.
Notes: This reference describes the function of anti-CRISPR proteins within a bacterial genome to protect itself from its CRISPR system. 
PMID: 30190308, 30190307
@sandyl27 @jimhu-tamu
This is for CACAO

**Comment by pgaudet** [comment]
Shouldn't it be 'defense response to against CRISPR-cas system', rather than just negative regulation?

**Comment by jimhu-tamu** [comment]
We didn’t think “response to” was appropriate here. These are from species where the guide RNA would target somewhere in their own genome. The anti-CRISPRs that are presumably constitutively expressed to keep the CRISPR cas from causing suicide. No phage or mobile element is being responded to. I think of it as preventing an autoimmune response. 

Other anti-CRISPRs are carried by viruses for overcoming host defense, but not these.

**Comment by jrr-cpt** [comment]
@vanaukenk Any progress on this NTR?

**Comment by vanaukenk** [comment]
@jrr-cpt 

I've added regulation of CRISPR-cas system and negative regulation of CRISRP-cas system to the ontology.

In looking over what we have more generally for the CRISPR-cas system in GO, I came across the term 'evasion by virus of CRISPR-cas system':

http://amigo.geneontology.org/amigo/term/GO:0098672

There are no annotations to the 'evasion' term, but I am wondering if and how this term and the negative regulation of CRISPR-cas system should be related in the ontology.

The definition for the 'evasion' term seems quite broad, but the associated references suggest some commonalities between it and the negative regulation term.  

I am concerned about having two conceptually related terms that have no relationship in the ontology, but it is hard to know exactly how the evasion term was meant to be used with no associated annotations.

Do you have any thoughts about this?

Also tagging @SIBvirus for input here.

Possibly we will need to think about having more specific child terms of 'negative regulation of CRISPR-cas system' to account for the different mechanisms, and purposes, of the regulation but I'd like to know more about the processes before doing that.  

Thx.

**Comment by vanaukenk** [comment]
Also, @jimhu-tamu 

If bacteria encode anti-CRISPRs that serve to essentially prevent bacterial suicide, do you think our placement of CRISPR-cas system in the ontology as a defense response is still correct? 

![image](https://user-images.githubusercontent.com/1730534/48503321-d164d580-e80f-11e8-8def-ca47e73204c5.png)

**Comment by cmungall** [comment]
@jrr-cpt 
> I think that GO:0098672 'evasion by virus of CRISPR-cas system' is not a good term

I agree! To me 'evasion' is a bit vague, it encompasses things like mutations in the target sequence, which isn't even a biological process

(((Ontologists side note: this term has an invalid has-participant relationship to a process

`relationship: has_participant GO:0099048 ! CRISPR-cas system`

we will catch these when we switch to Elk5)))

> rather using GO-CAM (?) use with 'negative regulation of CRISRP-cas system' would better capture what we know now and what we suspect we might find later.

Yes! even without GO-CAM or extensions I think it is good to be more precise than 'evade'. If it's negatively regulating or interfering we should say it!

@vanaukenk 
> There are no annotations to the 'evasion' term

actually some were added after you commented 2 years ago! And unfortunately they chose the 'evasion' term rather than your more appropriate negative regulation term

note there is a keyword mapping to the evasion term, but not keyword mapping to the evasion term

The majority of our experimental annotations to 'evasion'/GO:0098672 come from this paper:

http://amigo.geneontology.org/amigo/reference/PMID:30046034

This paper resulted in annotations only to GO:0098672, no other terms

From my reading of the paper it's clear the mechanism is known, I would not say it is "evasion", it is by targeting the nuclease activity of Cas9. This could be captured by go-cam or extensions, as jrr-cpt  suggests.

But even just with a simple annotation, these annotations should have been to a more mechanistically precise term.

I prefer the newer neg-reg-of-CRISPR term, but what I don't like is that it's still a bit vague about the mechanism. We use neg-reg a lot of the time when we don't know what's happening. I think here it's clear, it's interfering with the nuclease activity?

A bold solution would be to merge the the existing 'evasion' term into the new unused 'negative regulation' term  -- and maybe even call the term "anti-CRISPR", this is what is used in the literature.

This might make some uneasy, as we'd be making a stronger statement (I haven't fully absorbed the thoughtful comments and about self targeting spaces). But there is something to be said for having fewer terms to choose from!

**Comment by cmungall** [comment]
@vanaukenk the placement of CRISPR-cas system (see above in https://github.com/geneontology/go-ontology/issues/16423#issuecomment-438764909) feels a little odd to me. The 'clearance' part seems odd, even when it's targeted against phages.

it seems like it should itself negatively regulate some process, such as viral lifecycle (when not employed to avoid self-suicide)

the def has a typo (CISPR):

```
def: "An adaptive immune response of bacteria that serves to clear host cells of foreign DNA and RNA. It has three distinct stage: acquisition of foreign DNA by integration into CRISPR loci in the host chromosome, CRISPR RNA (crRNA) biogenesis, and target interference. CISPR stands for Clustered Regularly Interspaced Short Palindromic Repeat, which describes the natur
```

also the def states foreign, which sounds like not always true...

**Comment by pgaudet** [comment]
@ValWood we should look at this. 

@vanaukenk I am stealing this as part of the multiorg work. I hope that's OK.

**Comment by ValWood** [comment]
Yes I saw that go by this morning. Chris has a good point about "evasion"

**Comment by vanaukenk** [comment]
> @vanaukenk I am stealing this as part of the multiorg work. I hope that's OK.

@pgaudet that is fine since I am no longer on the ontology rota

**Comment by pgaudet** [comment]
These 2 related terms have not been used: 
* GO:0110132 regulation of CRISPR-cas system
* GO:0110133 negative regulation of CRISPR-cas system 

Look into merging - and look for what would be the best way to formulate this. 

@pmasson55 There is a link to https://viralzone.expasy.org/3962?outline=all_by_protein 

Maybe 'defense against (host) defense system/response'? 

@dsiegele @mgiglio99 Thoughts on this ?

**Comment by pgaudet** [comment]
Discussion on multiorganism call: 

 - [ ] obsolete the 'new' (not so new) terms
- GO:0110132 regulation of CRISPR-cas system
- GO:0110133 negative regulation of CRISPR-cas system
- Add: Consider: "GO:NEW tolerance to self CRISPR-cas system" 
- Consider: "GO:0098672 "evasion by virus of CRISPR-cas system" 
 - [ ] create a term  "tolerance to self CRISPR-cas system"
- subclass of 'GO:0002376 immune system process' 
- (NOT an inter-species process)
- Synonym: anti-CRISPR
 - [ ] Fix GO:0098672 "evasion by virus of CRISPR-cas system" 
-> change label to "inhibition of host CRISPR-cas system by virus" 
 - [ ] NTR: cas nuclease inhibitor activity
- PMID:30046034, PMID:28785032
- Definition:

**Comment by pgaudet** [comment]
@addiehl Does the proposal above work for you ? This puts those terms under 'immune system development', which is incorrect since this is under multiorganism process. Do you have suggestions as to how to deal with this ?

**Comment by addiehl** [comment]
Not sure if it's too late to comment on this, but I can see there are outstanding issues.

A fundamental issue here is the definition of what a "system" is in the GO. Per the gloss on the definition of GO:0048731 'system development' the working definition of system for this term is
"A system is a regularly interacting or interdependent group of organs or tissues that work together to carry out a given biological process."

This is fundamentally at odds with systems like CRISPR-CAS that work on the molecular or cellular levels, sometimes in unicellular organisms.  Examples of GO terms that make reference to systems which are not systems per the above definition (this not necessarily an exhaustive list):
GO:0099048 CRISPR-cas system
GO:0012505 endomembrane system
GO:0009521 photosystem
GO:0009522 photosystem I
GO:0009523 photosystem II
GO:0030253 protein secretion by the type I secretion system
GO:0015628 protein secretion by the type II secretion system
GO:0030254 protein secretion by the type III secretion system
GO:0044097 secretion by the type IV secretion system
GO:0030255 protein secretion by the type IV secretion system
GO:0044098 DNA secretion by the type IV secretion system
GO:0046819 protein secretion by the type V secretion system
GO:0062051 lipopolysaccharide transport system
GO:0000160 phosphorelay signal transduction system
GO:0071629 cytoplasm protein quality control by the ubiquitin-proteasome system
GO:0071630 nuclear protein quality control by the ubiquitin-proteasome system

While we typically think of an immune system as a system as a system that occurs in multicellular animals, at least some or many plant biologists like to talk about plant immune systems (which makes sense given that many innate immune recognition strategies are shared by plants and animals), and at least some microbiologists talk about CRISPR-Cas and other molecular level defense systems as immune systems of bacteria (nicely reviewed in [PMID:31695182](https://pubmed.ncbi.nlm.nih.gov/31695182/), among other places).  CRISPR-Cas even exhibits memory of past viral infections.

A better working definition of system for the GO would be "A system is a regularly interacting or interdependent group of lipid membranes, nucleic acids, proteins, cells, organs, or tissues that work together to carry out a given biological process."

We could then move 'system development' directly under 'developmental process' and broaden the definition to be 
"The process whose specific outcome is the progression of a system over time, from its formation to the mature structure. A system is a regularly interacting or interdependent group of lipid membranes, nucleic acids, proteins, cells, organs, or tissues that work together to carry out a given biological process."

We could even add a child (thinking fondly of @ukemi), 'multicellular organismal system development' with the definition
"The process whose specific outcome is the progression of an organismal system over time, from its formation to the mature structure. An organismal system is a regularly interacting or interdependent group of organs or tissues that work together to carry out a given biological process."
This term would also be under 'multicellular organism development'

Then we would keep 'immune system development' as a child of 'system development' and move all the rest of the current children of 'system development' under 'organismal system development' ('animal organ development', 'limbic system development', 'vasculature system development', etc.)

An additional change would be to definitions of 'immune system development' to include the broader definition of system:
"The process whose specific outcome is the progression of an organismal system whose objective is to provide calibrated responses by an organism to a potential internal or invasive threat, over time, from its formation to the mature structure. A system is a regularly interacting or interdependent group of lipid membranes, nucleic acids, proteins, cells, organs, or tissues that work together to carry out a given biological process."

With these changes we can add 'tolerance to self CRISPR-cas system' as a child of 'tolerance induction'.

New hierarchy:
biological_process
--developmental process
----system development
------immune system development
--------tolerance induction
----------tolerance to self CRISPR-cas system
------multicellular organismal system development [new term]
----multicellular organismal process
------multicellular organism development
--------multicellular organismal system development [new term]
--immune system process
----immune system development
------tolerance induction
--------tolerance to self CRISPR-cas system

Perhaps someday there will be additional children of 'system development' that aren't children of 'multicellular organismal system development'

Thanks for your tolerance of my late reply and long winded response and daring to suggest changes to the development process hierarchy!
Alex

**Comment by cmungall** [comment]
Perhaps we can obsolete "system development"? I think your broadened definition makes sense but it's so broad it sure covers everything in GO, it's all systems biology.

**Comment by pgaudet** [comment]
Discussion on the multiorganism call today: 

- We dont want to do such large changes as proposed above (at least not here). From the comment above: https://github.com/geneontology/go-ontology/issues/16423#issuecomment-681057690
- We'd like to 

- [ ] obsolete GO:0110132 regulation of CRISPR-cas system (0 annotations)
- [ ] obsolete  GO:0110133 negative regulation of CRISPR-cas system (0 annotations)
-> Consider: "GO:0098672 "evasion by virus of CRISPR-cas system"

- [ ] change label GO:0098672 "evasion by virus of CRISPR-cas system" to "inhibition of host CRISPR-cas system by virus"
- [ ]  GO:0098672 add synonym: anti-CRISPR [BROAD]

- [ ] NTR:  nuclease inhibitor activity
-> PMID:30046034, PMID:28785032, PMID:29554913

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
 GO:0110132 regulation of CRISPR-cas system 
and  GO:0110133 negative regulation of CRISPR-cas system 

The reason for obsoletion is that these terms do not clearly capture the processes described in papers cited. The existing term GO:0098672 "evasion by virus of CRISPR-cas system" is more appropriate. 

There are no annotations, no mappings to these terms. These terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/16423

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140721
+name: nuclease inhibitor activity
+namespace: molecular_function
+def: "Binds to and modulates the activity of a nuclease." [PMID:28785032, PMID:29554913, PMID:30046034]
+intersection_of: GO:0098772 ! molecular function regulator
+intersection_of: negatively_regulates GO:0004518 ! nuclease activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16423 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-16T09:09:45Z

**Comment by cmungall** [comment]
Hmm, I am not so sure about this - I thought we all agreed "evasion" was very vague. There is a very precise mechanism with anti-CRISPR. I am also not sure about distributing the concept of anti-CRISPR across two branches

**Comment by pgaudet** [comment]
Not sure what you refer to. I have changed of label GO:0098672 "evasion by virus of CRISPR-cas system" to "inhibition of host CRISPR-cas system by virus" - seems like we're saying the same thing?
