### ISSUE TITLE
exogenous protein binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16430]
@pgaudet  did we discuss this recently (I see to remember we did, briefly).

We were wondering  at PHIBAse whether it would be possible to have a term

"exogenous protein binding" for cases when a pathogen binds to a host protein.

 Such a term would only be used from the pathogen perspective, and I guess would have the  host protein in the with field and 2 taxon IDs in the taxon field. 
Separating out such a term, in addition to making the point clearly, would allow us to have syntax checks to see that the taxon information is always collected.

What do you think?

(In addition to using for GO annotation, we want to point to this term in the PHIPO pathogen host interaction phenotype ontology to capture instances of altered host protein binding)

@CuzickA

**Comment by pgaudet** [comment]
I like it - however how would we restrict to the pathogen perspective ? For example could it be a parent for 'viral receptor activity' (provided that the receptor binds a protein) - or other host proteins binding symbiont proteins?

**Comment by ValWood** [comment]
MAybe we don't need a restriction in GO, it could be used for the pathogen or the host.

then  "viral receptor activity" (used for human annotation), could go under here.

Within the Canto project we would use this GO term to construct pathogen host phenotype terms logically (for example  "reduced exogenous protein binding"). Within our system we are only using the PHIPO ontology to annotate pathogens, so the restriction we require locally would  be implicit. The GO term can be more generic.

**Comment by ValWood** [comment]
@CuzickA  we have one
