### ISSUE TITLE
OTR: GO:0001070 RNA-binding transcription regulator activity- typo

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#16439]
GO:0001070. RNA-binding transcription regulator activity

Typo in comments:

Added **tacon** constraints, edited definition see https://github.com/geneontology/go-ontology/issues/15872

**Comment by ukemi** [comment]
@pgaudet have we been adding these comments on a regular basis? Don't we usually just put this in the pull request?

**Comment by pgaudet** [comment]
Yes I have been. We had discussed that at some ontology call when I first tarted to work on the ontology, I wanted to link the GH tickets and I thought this was how to do it. 

I guess we can remove them but I must say I have already used these links to find in which tickets I made a modification. It's probably not useful for users though. 

Pascale

**Comment by ukemi** [comment]
I thought we were going to add a new property called editors' notes or something like that. I will fix the typo, but we should bring this up on a call.

**Comment by pgaudet** [comment]
OK, but where do we put them in the meantime ??

**Comment by ukemi** [comment]
That's why I left it.
