### ISSUE TITLE
Ancestry for  GO:0001070 RNA-binding transcription regulator activity

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#16440]
I just had a question come up about GO:0001070 RNA-binding transcription regulator activity- why isn't this term related to GO:0003723 RNA binding in any way? Should there be a relationship or was this intentional?

Thanks

**Comment by ukemi** [comment]
It does through:
'has part' some 'transcription regulatory region RNA binding'

**Comment by suzialeksander** [comment]
@ukemi, what is the easiest way for someone (casual user) to view the 'has_part'? QuickGO/Amigo show 'occurs_in' but not 'has_part', only when I look at go.obo do I see that relationship- and that's slightly beyond what a non-GO person would think of looking at

**Comment by ukemi** [comment]
It's not ideal, but if you look at the neighborhood view in AmiGO2, you see the has_part as a BFO relation  BFO:0000051.

**Comment by cmungall** [comment]
We've had extensive discussions about this in the past. QuickGO used to show has-part in the graph view but this was massively confusing. Better to bury in a tabular view like the neighborhood view like amigo, if we show the user at all.

What would a user do with this info when they see it? What's the use case?

**Comment by suzialeksander** [comment]
@cmungall ENCODE is doing some kind of function prediction where they need to see if the  groupings of transcription factors are accurate, if I understand- and they're tracing the terms back up the tree.  No worries, I think she's OK with digging through the obo for now.  If there are any more questions I'll ask at/after Montreal.
