### ISSUE TITLE
switch name and synonym GO:0071839	apoptotic process in bone marrow

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16449]
to
GO:0071839	apoptotic process in bone marrow cell

**Comment by pgaudet** [comment]
Also changed 
* 'regulation of apoptotic process in bone marrow'
* positive and negative 
*  GO:0035602 fibroblast growth factor receptor signaling pathway involved in negative regulation of apoptotic process in bone marrow

Pascale
