### ISSUE TITLE
taxon restrictions required for anatomical structure   from UBERON

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16448]
Follow on from:
https://github.com/geneontology/go-ontology/issues/16047

Add axiomatisation to get taxon contraints from UBERON for:

GO:0030280 structural constituent of epidermis
GO:0030281 structural constituent of cutaneous appendage
GO:0008307	structural constituent of muscle
GO:0008316	structural constituent of vitelline membrane
GO:0016490	structural constituent of peritrophic membrane
GO:0019911	structural constituent of myelin sheath
GO:0030345 structural constituent of tooth enamel

https://github.com/geneontology/go-ontology/issues/16047

**Comment by ValWood** [comment]
David suggested:
Adding a bit more to the comment. I think if we make all of the structural constituent of x terms = structural molecule activity occurs_in some x (x is an uberon term), these should fall out through UBERON.

**Comment by pgaudet** [comment]
Need to look at all terms to see if we can make logical definitions: 

'structural constituent of albumen'
'structural constituent of bone'
'structural constituent of carboxysome'
'structural constituent of cell wall'
'structural constituent of chorion'
'structural constituent of chromatin'
'structural constituent of cuticle'
'structural constituent of cytoskeleton'
'structural constituent of egg coat'
'structural constituent of epidermis'
'structural constituent of eye lens'
'structural constituent of muscle'
'structural constituent of myelin sheath'
'structural constituent of nuclear pore'
'structural constituent of peritrophic membrane'
'structural constituent of postsynapse'
'structural constituent of postsynaptic actin cytoskeleton'
'structural constituent of postsynaptic density'
'structural constituent of postsynaptic intermediate filament cytoskeleton'
'structural constituent of postsynaptic specialization'
'structural constituent of presynapse'
'structural constituent of presynaptic actin cytoskeleton'
'structural constituent of presynaptic active zone'
'structural constituent of ribosome'
'structural constituent of synapse'
'structural constituent of virion'
'structural molecule activity conferring elasticity'

**Comment by pgaudet** [comment]
This probably involves some annotation review and a few obsoletions. To revisit.

**Comment by pgaudet** [comment]
Added logical definition to most children of 'structural molecule activity' 

except for 
-  structural constituent of peritrophic membrane (no Uberon term)
- structural constituent of eye lens (no uberon term)

**Comment by pgaudet** [comment]
Hi @hattrill @ukemi 
Would it make sense to separate GO:0005212 structural constituent of eye lens
into 
- structural constituent of camera-type eye 
and  structural constituent of transparent eye (or compound eye?) to align with Uberon? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Created new ticket for this other project https://github.com/geneontology/go-ontology/issues/16612
