### ISSUE TITLE
Wrong EC xref on malonyl-CoA synthetase activity (GO:0090409)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16443]
GO:0090409
malonyl-CoA synthetase activity
Catalysis of the reaction: malonate + ATP + coenzyme A = malonyl-CoA + AMP + diphosphate.
Current EC xref is 6.2.1.14 (https://enzyme.expasy.org/EC/6.2.1.14)

But looks like it should be 6.2.1.n3 (https://enzyme.expasy.org/EC/6.2.1.n3)

**Comment by ukemi** [comment]
Check for a Rhea xref.

**Comment by hdrabkin** [comment]
RHEA:32139
and fixed EC

**Comment by sjm41** [comment]
Thanks!
