### ISSUE TITLE
GO:0000917    division septum assembly/ recent changes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16479]
GO:0000917    division septum assembly

2018-09-27 | Deleted | RELATION | part of GO:0000278 (mitotic cell cycle)
2018-09-27 | Deleted | RELATION | is a GO:1902410 (mitotic cytokinetic process)
2017-09-24 | Deleted | SYNONYM | mitotic barrier septum assembly

For fission yeast the annotations to this term are no longer picked up by our slim (which uses mitotic cytokinesis, so that we know that everything we annotated to cytokinesis becomes part of the "mitotic cell cycle")

So could we have a child term with the old parents added back?

NTR: mitotic  division septum assembly
(this is now an exact synonym of the GO:0000917    division septum assembly term, it should have been narrow, but these synonyms now need to be deleted)

please move
GO:0031671    primary cell septum biogenesis
and
GO:1990344    secondary cell septum biogenesis

under the new term.

Thanks

Val

**Comment by pgaudet** [comment]
Do you need the equivalent regulation terms as well?

**Comment by ValWood** [comment]
please.
