### ISSUE TITLE
Dead EC xref on GO:0043909

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16476]
id: GO:0043909
name: N-acetylcitrulline deacetylase activity
xref: EC:3.5.1.B4

Maybe remove EC xref or replace with partial EC:3.5.1.-

**Comment by sjm41** [comment]
Hmmm, just noticed in the change log that the partial EC:3.5.1 was deleted and the new EC:3.5.1.B4 was added recently, on 2018-05-31. So I guess there was a reason for this change - but I don't see that new EC number at https://enzyme.expasy.org/

**Comment by hdrabkin** [comment]
A partial EC will not be used for a definitive EC. 
The "B4" usually means it's been supplied by Brenda awaiting EC.

**Comment by hdrabkin** [comment]
May change xref to BRENDA:EC:3.5.1.B4

**Comment by sjm41** [comment]
Ah, OK.  I didn't know about the "B" = "supplied by Brenda awaiting EC." aspect.

**Comment by hdrabkin** [comment]
I'm going to reset this as looking through my notes for 5-31, I seem to have lost where I got this. However, EC just handed me 3 new EC numbers but they all have letters at the end! Waiting a reponse for what these mean!

**Comment by pgaudet** [comment]
I think these are temporary identifiers @kaxelsen is this right ?

**Comment by hdrabkin** [comment]
I just got a reply from EC to how to 'move' these forward, which I will do.

**Comment by kaxelsen** [comment]
FYI (From my mail to hdrabkin): The B in EC numbers found at Brenda means it is a preliminary EC number. The preliminary EC numbers are used for entries where the catalytic activity is known, but where there no EC numbers exists. This means that it is not necessarily in progress in the IUBMB pipeline. You can also find preliminary EC numbers containing an 'M' at MetaCyc and others including 'n' in ENZYME. 

If you would like to have a preliminary EC number changed into a complete EC number, the easiest solution is to submit the reaction.

**Comment by sjm41** [comment]
@hdrabkin - shall we close this?  Looks like you removed EC:3.5.1.B4 from GO:0043909 at some point, and there's no extant EC replacement.

**Comment by hdrabkin** [comment]
The EC was removed and a RHEA is being used now. Will close.
