### ISSUE TITLE
TPV hydrogen sulfide biosynthetic process 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16478]
GO:0009403    toxin biosynthetic process

can an endogenously produced molecule be a toxin? It is _toxic_ but it isn't a toxin is it?

At least it is not produced to be a  _toxin_ its a toxic by product of other reactions

Human "Cystathionine beta-synthase" is annotated to 
GO:0009403    toxin biosynthetic process
 for example.

That seems odd?

**Comment by ukemi** [comment]
Coming in via a ChEBI role.

**Comment by pgaudet** [comment]
This will be closed when I do #15379 (and will also deal with #14047 - and maybe others) 

That being said, Gareth Owen from ChEBI will be at the Montreal meeting, so perhaps we could discuss a less drastic solution. I'll wait for that discussion to do the merge proposed there. 

Pascale

**Comment by krchristie** [comment]
This was fixed by this ticket:
**cessation of reasoning over ChEBI roles, i.e. stop inferring relationships like "ATP binding" is_a "drug binding"** #19479
