### ISSUE TITLE
Malformed EC numbers in defs of GO:0102584 & GO:0102585

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16477]
From the GO-basic.obo file, GO:0102584 & GO:0102585 each contain a malformed EC number in their def lines - they are missing a period (see below).  Neither entry has an EC xref, so either the EC number in the def should be removed, or the given (partial) EC should be added as an xref.

Also, just noticed "5-O-glucosyltransferase activity" is repeated in the GO:0102584 term name.

[Term]
id: GO:0102584
name: cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-glucosyltransferase activity 5-O-glucosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: cyanidin 3-O-[2''-O-xylosyl) 6''-O-(p-coumaroyl) glucoside + UDP-alpha-D-glucose <=> cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-glucoside + UDP + H+" [EC:2.4.1-, GOC:pz]
xref: MetaCyc:RXN-15330
is_a: GO:0016758 ! transferase activity, transferring hexosyl groups

[Term]
id: GO:0102585
name: cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-glucoside malonyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-glucoside + malonyl-CoA + H+ <=> cyanidin 3-O-[2''-O-(xylosyl)-6''-O-(p-coumaroyl) glucoside] 5-O-malonylglucoside + coenzyme A." [EC:2.3.1-, GOC:pz]
xref: MetaCyc:RXN-15331
is_a: GO:0016747 ! transferase activity, transferring acyl groups other than amino-acyl groups

**Comment by sjm41** [comment]
@hdrabkin Looks like the malformed EC numbers in the def lines have been fixed, though they are grouping terms and should just be removed IMO?

Do you think this repetition is correct?
_Also, just noticed "5-O-glucosyltransferase activity" is repeated in the GO:0102584 term name._

**Comment by hdrabkin** [comment]
ECs removed and replaced with PMIDs based on Metacyc/Plantcyc record info.

**Comment by hdrabkin** [comment]
and fixed the duplication in term name

**Comment by sjm41** [comment]
Thanks!
