### ISSUE TITLE
Do we need all terms under GO:0006271 DNA strand elongation involved in DNA replication'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16484]

**Comment by mah11** [comment]
Leading and lagging strand elongation are profoundly different from each other, so these are essential (including the parts of lagging str. elong.):

GO:0006272 ! leading strand elongation
GO:0006273 ! lagging strand elongation
GO:0090629 ! lagging strand initiation
GO:0033567 ! DNA replication, Okazaki fragment processing
GO:0043137 ! DNA replication, removal of RNA primer

Bacterial replication uses fewer different polymerases, so it's probably worth keeping:

GO:1902331 ! DNA strand elongation involved in bacterial-type DNA replication
(which implies also keeping GO:1902319! DNA strand elongation involved in nuclear cell cycle DNA replication)

... and maybe add leading and lagging bacterial terms? Up to those who annotate bacteria, I think.

I don't know whether there are any differences in strand elongation between mitotic and premeiotic replication; in species that have both, there are differences in regulation of initiation but I'm not sure whether anything else differs, nor, if so, what. That means I can't make an explicit case for or against 
differentiating between "mitotic" and "premeiotic" under "nuclear cell cycle DNA replication"; "nuclear cell cycle" may be precise enough.

**Comment by ValWood** [comment]
closing
