### ISSUE TITLE
Merge GO:1903756    regulation of transcription from RNA polymerase II promoter by histone modification

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16483]
This term and children should be  done with GO cam

MF specific histone modification part_of transcription term

**Comment by ValWood** [comment]
follow on from
https://github.com/geneontology/go-ontology/issues/11583

**Comment by pgaudet** [comment]
@bmeldal 
> note there is also a complex annotation ComplexPortal:CPX-1384
Is this merge OK with you ?

**Comment by bmeldal** [comment]
I'm going to move the complex to its current parent term of GO:0006357 regulation of transcription by RNA polymerase II because GO:0034401 chromatin organization involved in regulation of transcription has the tag **"do not manually annotate"**.

**Comment by pgaudet** [comment]
Ah good point

**Comment by pgaudet** [comment]
Isn't that a little weird @ValWood ?  (GO:0034401 chromatin organization involved in regulation of transcription has the tag "do not manually annotate".) 

Children are: 
'chromatin organization involved in negative regulation of transcription'
'chromatin silencing at centromere outer repeat region'
'chromatin silencing at centromere'
'chromatin silencing at rDNA'
'chromatin silencing at silent mating-type cassette'
'chromatin silencing at subtelomere'
'chromatin silencing at telomere'
'chromatin silencing by small RNA'
'chromatin silencing'
'chromatin-mediated maintenance of transcription'
'heterochromatin assembly involved in chromatin silencing at centromere outer repeat region'
'heterochromatin assembly involved in chromatin silencing by small RNA'
'heterochromatin assembly involved in chromatin silencing'
'heterochromatin maintenance involved in chromatin silencing at centromere outer repeat region'
'heterochromatin maintenance involved in chromatin silencing'
'heterochromatin organization involved in chromatin silencing'
'methylation-dependent chromatin silencing'
'transfer RNA gene-mediated silencing'

We want the annotation to specify telomere/hererochomatin/centromere ...?

**Comment by bmeldal** [comment]
That's not how it looks in QuickGO. There is only one child: GO:0097549 chromatin organization involved in negative regulation of transcription,
that has one child: GO:0070868 heterochromatin organization involved in chromatin silencing
that has 2 children and so on. 

I agree, the ontology doesn't look right. 
And one cannot annotate to a neutral or positive activity...

**Comment by ValWood** [comment]
> Isn't that a little weird @ValWood ? (GO:0034401 chromatin organization involved in regulation of transcription has the tag "do not manually annotate".)

I remember a discussion that if you knew this you should be able to use one of the children. I think it was one of the very first 'do not annotates'. That said, I still think it's a weird term....
and the entire branch needs bringing up to date. The problem is the field has moved on a lot  since the early 'silencing terms' were added.

**Comment by ValWood** [comment]
hmm, it was odd when it had no children:
https://github.com/geneontology/go-ontology/issues/11856

**Comment by pgaudet** [comment]
OK I am finalizing this merge. I will remove the taxon constraints for now. 

I will create a new tickets to review this branch. 

Pascale
