### ISSUE TITLE
Incorrect Reactome xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16487]
This may be an issue for Reactome rather than GO?
But I noticed these odd, high level xrefs to 'ligase activity':

[Term]
id: GO:0016874
name: ligase activity
xref: EC:6
xref: Reactome:REACT_115603 "Ligation of DNA at sites of patch replacement, Gallus gallus"
xref: Reactome:REACT_116018 "Ligation of newly synthesized repair patch to incised DNA in GG-NER, Gallus gallus"
is_a: GO:0003824 ! catalytic activity

Also, I don't see any record of these xrefs being adding in the change log on this page:
https://www.ebi.ac.uk/QuickGO/term/GO:0016874

**Comment by ukemi** [comment]
The Reactome xrefs will be getting updated soon.  #12518.

**Comment by sjm41** [comment]
Ah, good.  Thanks for the pointer to that other ticket.
Very please to read this there:
"Regarding xrefs to multiple species, I believe the advice from @deustp01 is to only maintain the xref to human as the others can be derived as needed."
@hattrill

**Comment by ukemi** [comment]
Yes. That is the current plan. GO will only have the human xrefs in the ontology.
