### ISSUE TITLE
add synonyms to chaperone-mediated autophagy

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16499]
Hi Barbara
 
Please would you add a couple of exact synonyms to the following term:
 
GO:0061684 chaperone-mediated autophagy
exact synonyms
chaperone-assisted selective autophagy 
CASA 
PMID: 23434281

Thanks

Ruth

**Comment by BarbaraCzub** [comment]
Hi @RLovering,

Should I also move 'CMA' from 'related synonyms' to 'exact synonyms'? 

It is is an acronym of 'chaperone-mediated autophagy' and it is based on the same original reference (PMID:22743996). 

Thanks,
Barbara

**Comment by RLovering** [comment]
yes it sounds like you should
