### ISSUE TITLE
add chloroplast to Plant GO slim

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16494]
@tberardini and I were discussing including chloroplast (GO:0009507)
in the plant go slim.
there is of course a thylakoid term (part of a chloroplast) and a plastid term but arguably folks would be interested in this specific magical organelle.

**Comment by tberardini** [comment]
Adding chloroplast to the plant slim makes sense to me.  Unless there are objections, I'll add that tomorrow.

**Comment by tberardini** [comment]
Well, I ran into some issues.  See https://github.com/geneontology/go-ontology/pull/16502
