### ISSUE TITLE
Obsolete GO:0001011 transcription factor activity, sequence-specific DNA binding, RNA polymerase recruiting

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16493]
GO:0001011 transcription factor activity, sequence-specific DNA binding, RNA polymerase recruiting

The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.

- 4 genes with manual annotations to this term - these also multiple other MF annotations

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/1f4XbluhrBfLqGD4uOjs57LFO_979tNlpRCafL84R8-E/edit#gid=0

2 BHF @RLovering 
2 flybase @hattrill

**Comment by hattrill** [comment]
done

**Comment by RLovering** [comment]
done

**Comment by pgaudet** [comment]
thanks !
