### ISSUE TITLE
NTR: glutamate import into mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16497]
sibling of

GO:0090454    glutamate transmembrane import into vacuole
GO:1904983    glycine import into mitochondrion

descendant of
GO:1990542    mitochondrial transmembrane transport

standard definition:

Molecular identification and functional characterization of a novel glutamate transporter in yeast and plant mitochondria.
PMID: 30297026

I'm ISS'ing to SGD @suzialeksander 
@tberardini

**Comment by tberardini** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/?term=30297026

**Comment by mah11** [comment]
any word on this? we've got an annotation waiting for it ...

**Comment by vanaukenk** [comment]
@mah11 - I've added the term as L-glutamate import into mitochondrion based on the experiments in the paper (thanks @ukemi !)

Let me know if that's _not_ what you intended and sorry for the delay.

**Comment by mah11** [comment]
That should be fine. Thanks!
