### ISSUE TITLE
Eliminate use of GOCHE for biological roles except where these are guaranteed rigid

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16511]
We should examine all GOCHE classes that are bearers of biological roles. For any that are context-dependent, we should specify the context with the part-of pattern; e.g. instead of `Rel some (bearer-of some X-Role)` use `part-of some X-Process`.

If the classification is rigid, ie the chemicals always bear that role, then ok to keep.

Classes that reference a GOCHE biological role bearer:

|Class|Name|Role|Role Name|
|---|---|---|---|
|GO:0009672|auxin:proton symporter activity|GOCHE:22676|substance with auxin role|
|GO:0009733|response to auxin|GOCHE:22676|substance with auxin role|
|GO:0009850|auxin metabolic process|GOCHE:22676|substance with auxin role|
|GO:0009851|auxin biosynthetic process|GOCHE:22676|substance with auxin role|
|GO:0009852|auxin catabolic process|GOCHE:22676|substance with auxin role|
|GO:0010011|auxin binding|GOCHE:22676|substance with auxin role|
|GO:0010252|auxin homeostasis|GOCHE:22676|substance with auxin role|
|GO:0010315|auxin efflux|GOCHE:22676|substance with auxin role|
|GO:0010329|auxin efflux transmembrane transporter activity|GOCHE:22676|substance with auxin role|
|GO:0038198|auxin receptor activity|GOCHE:22676|substance with auxin role|
|GO:0060918|auxin transport|GOCHE:22676|substance with auxin role|
|GO:0071365|cellular response to auxin stimulus|GOCHE:22676|substance with auxin role|
|GO:0080161|auxin transmembrane transporter activity|GOCHE:22676|substance with auxin role|
|GO:0009672|auxin:proton symporter activity|GOCHE:22676|substance with auxin role|
|GO:0009733|response to auxin|GOCHE:22676|substance with auxin role|
|GO:0009850|auxin metabolic process|GOCHE:22676|substance with auxin role|
|GO:0009851|auxin biosynthetic process|GOCHE:22676|substance with auxin role|
|GO:0009852|auxin catabolic process|GOCHE:22676|substance with auxin role|
|GO:0010011|auxin binding|GOCHE:22676|substance with auxin role|
|GO:0010252|auxin homeostasis|GOCHE:22676|substance with auxin role|
|GO:0010315|auxin efflux|GOCHE:22676|substance with auxin role|
|GO:0010329|auxin efflux transmembrane transporter activity|GOCHE:22676|substance with auxin role|
|GO:0038198|auxin receptor activity|GOCHE:22676|substance with auxin role|
|GO:0060918|auxin transport|GOCHE:22676|substance with auxin role|
|GO:0071365|cellular response to auxin stimulus|GOCHE:22676|substance with auxin role|
|GO:0080161|auxin transmembrane transporter activity|GOCHE:22676|substance with auxin role|
|GO:0009672|auxin:proton symporter activity|GOCHE:22676|substance with auxin role|
|GO:0009733|response to auxin|GOCHE:22676|substance with auxin role|
|GO:0009850|auxin metabolic process|GOCHE:22676|substance with auxin role|
|GO:0009851|auxin biosynthetic process|GOCHE:22676|substance with auxin role|
|GO:0009852|auxin catabolic process|GOCHE:22676|substance with auxin role|
|GO:0010011|auxin binding|GOCHE:22676|substance with auxin role|
|GO:0010252|auxin homeostasis|GOCHE:22676|substance with auxin role|
|GO:0010315|auxin efflux|GOCHE:22676|substance with auxin role|
|GO:0010329|auxin efflux transmembrane transporter activity|GOCHE:22676|substance with auxin role|
|GO:0038198|auxin receptor activity|GOCHE:22676|substance with auxin role|
|GO:0060918|auxin transport|GOCHE:22676|substance with auxin role|
|GO:0071365|cellular response to auxin stimulus|GOCHE:22676|substance with auxin role|
|GO:0080161|auxin transmembrane transporter activity|GOCHE:22676|substance with auxin role|
|GO:0006732|coenzyme metabolic process|GOCHE:23354|substance with coenzyme role|
|GO:0009108|coenzyme biosynthetic process|GOCHE:23354|substance with coenzyme role|
|GO:0009109|coenzyme catabolic process|GOCHE:23354|substance with coenzyme role|
|GO:0050662|coenzyme binding|GOCHE:23354|substance with coenzyme role|
|GO:0051182|coenzyme transport|GOCHE:23354|substance with coenzyme role|
|GO:0051185|coenzyme transmembrane transporter activity|GOCHE:23354|substance with coenzyme role|
|GO:0048037|cofactor binding|GOCHE:23357|substance with cofactor role|
|GO:0051181|cofactor transport|GOCHE:23357|substance with cofactor role|
|GO:0051184|cofactor transmembrane transporter activity|GOCHE:23357|substance with cofactor role|
|GO:0051186|cofactor metabolic process|GOCHE:23357|substance with cofactor role|
|GO:0051187|cofactor catabolic process|GOCHE:23357|substance with cofactor role|
|GO:0051188|cofactor biosynthetic process|GOCHE:23357|substance with cofactor role|
|GO:0009690|cytokinin metabolic process|GOCHE:23530|substance with cytokinin role|
|GO:0009691|cytokinin biosynthetic process|GOCHE:23530|substance with cytokinin role|
|GO:0009735|response to cytokinin|GOCHE:23530|substance with cytokinin role|
|GO:0009823|cytokinin catabolic process|GOCHE:23530|substance with cytokinin role|
|GO:0009884|cytokinin receptor activity|GOCHE:23530|substance with cytokinin role|
|GO:0010184|cytokinin transport|GOCHE:23530|substance with cytokinin role|
|GO:0044373|cytokinin binding|GOCHE:23530|substance with cytokinin role|
|GO:0071368|cellular response to cytokinin stimulus|GOCHE:23530|substance with cytokinin role|
|GO:0009690|cytokinin metabolic process|GOCHE:23530|substance with cytokinin role|
|GO:0009691|cytokinin biosynthetic process|GOCHE:23530|substance with cytokinin role|
|GO:0009735|response to cytokinin|GOCHE:23530|substance with cytokinin role|
|GO:0009823|cytokinin catabolic process|GOCHE:23530|substance with cytokinin role|
|GO:0009884|cytokinin receptor activity|GOCHE:23530|substance with cytokinin role|
|GO:0010184|cytokinin transport|GOCHE:23530|substance with cytokinin role|
|GO:0044373|cytokinin binding|GOCHE:23530|substance with cytokinin role|
|GO:0071368|cellular response to cytokinin stimulus|GOCHE:23530|substance with cytokinin role|
|GO:0009690|cytokinin metabolic process|GOCHE:23530|substance with cytokinin role|
|GO:0009691|cytokinin biosynthetic process|GOCHE:23530|substance with cytokinin role|
|GO:0009735|response to cytokinin|GOCHE:23530|substance with cytokinin role|
|GO:0009823|cytokinin catabolic process|GOCHE:23530|substance with cytokinin role|
|GO:0009884|cytokinin receptor activity|GOCHE:23530|substance with cytokinin role|
|GO:0010184|cytokinin transport|GOCHE:23530|substance with cytokinin role|
|GO:0044373|cytokinin binding|GOCHE:23530|substance with cytokinin role|
|GO:0071368|cellular response to cytokinin stimulus|GOCHE:23530|substance with cytokinin role|
|GO:0006775|fat-soluble vitamin metabolic process|GOCHE:24020|substance with fat-soluble vitamin role|
|GO:0042362|fat-soluble vitamin biosynthetic process|GOCHE:24020|substance with fat-soluble vitamin role|
|GO:0042363|fat-soluble vitamin catabolic process|GOCHE:24020|substance with fat-soluble vitamin role|
|GO:0006775|fat-soluble vitamin metabolic process|GOCHE:24020|substance with fat-soluble vitamin role|
|GO:0042362|fat-soluble vitamin biosynthetic process|GOCHE:24020|substance with fat-soluble vitamin role|
|GO:0042363|fat-soluble vitamin catabolic process|GOCHE:24020|substance with fat-soluble vitamin role|
|GO:0060992|response to fungicide|GOCHE:24127|substance with fungicide role|
|GO:0009725|response to hormone|GOCHE:24621|substance with hormone role|
|GO:0009914|hormone transport|GOCHE:24621|substance with hormone role|
|GO:0032870|cellular response to hormone stimulus|GOCHE:24621|substance with hormone role|
|GO:0042445|hormone metabolic process|GOCHE:24621|substance with hormone role|
|GO:0042446|hormone biosynthetic process|GOCHE:24621|substance with hormone role|
|GO:0042447|hormone catabolic process|GOCHE:24621|substance with hormone role|
|GO:0042562|hormone binding|GOCHE:24621|substance with hormone role|
|GO:0046879|hormone secretion|GOCHE:24621|substance with hormone role|
|GO:0009725|response to hormone|GOCHE:24621|substance with hormone role|
|GO:0009914|hormone transport|GOCHE:24621|substance with hormone role|
|GO:0032870|cellular response to hormone stimulus|GOCHE:24621|substance with hormone role|
|GO:0042445|hormone metabolic process|GOCHE:24621|substance with hormone role|
|GO:0042446|hormone biosynthetic process|GOCHE:24621|substance with hormone role|
|GO:0042447|hormone catabolic process|GOCHE:24621|substance with hormone role|
|GO:0042562|hormone binding|GOCHE:24621|substance with hormone role|
|GO:0046879|hormone secretion|GOCHE:24621|substance with hormone role|
|GO:0010046|response to mycotoxin|GOCHE:25442|substance with mycotoxin role|
|GO:0036146|cellular response to mycotoxin|GOCHE:25442|substance with mycotoxin role|
|GO:0043385|mycotoxin metabolic process|GOCHE:25442|substance with mycotoxin role|
|GO:0043386|mycotoxin biosynthetic process|GOCHE:25442|substance with mycotoxin role|
|GO:0043387|mycotoxin catabolic process|GOCHE:25442|substance with mycotoxin role|
|GO:0010046|response to mycotoxin|GOCHE:25442|substance with mycotoxin role|
|GO:0036146|cellular response to mycotoxin|GOCHE:25442|substance with mycotoxin role|
|GO:0043385|mycotoxin metabolic process|GOCHE:25442|substance with mycotoxin role|
|GO:0043386|mycotoxin biosynthetic process|GOCHE:25442|substance with mycotoxin role|
|GO:0043387|mycotoxin catabolic process|GOCHE:25442|substance with mycotoxin role|
|GO:0010046|response to mycotoxin|GOCHE:25442|substance with mycotoxin role|
|GO:0036146|cellular response to mycotoxin|GOCHE:25442|substance with mycotoxin role|
|GO:0043385|mycotoxin metabolic process|GOCHE:25442|substance with mycotoxin role|
|GO:0043386|mycotoxin biosynthetic process|GOCHE:25442|substance with mycotoxin role|
|GO:0043387|mycotoxin catabolic process|GOCHE:25442|substance with mycotoxin role|
|GO:0001504|neurotransmitter uptake|GOCHE:25512|substance with neurotransmitter role|
|GO:0005326|neurotransmitter transporter activity|GOCHE:25512|substance with neurotransmitter role|
|GO:0005328|neurotransmitter:sodium symporter activity|GOCHE:25512|substance with neurotransmitter role|
|GO:0006836|neurotransmitter transport|GOCHE:25512|substance with neurotransmitter role|
|GO:0007269|neurotransmitter secretion|GOCHE:25512|substance with neurotransmitter role|
|GO:0015842|aminergic neurotransmitter loading into synaptic vesicle|GOCHE:25512|substance with neurotransmitter role|
|GO:0042133|neurotransmitter metabolic process|GOCHE:25512|substance with neurotransmitter role|
|GO:0042135|neurotransmitter catabolic process|GOCHE:25512|substance with neurotransmitter role|
|GO:0042136|neurotransmitter biosynthetic process|GOCHE:25512|substance with neurotransmitter role|
|GO:0042165|neurotransmitter binding|GOCHE:25512|substance with neurotransmitter role|
|GO:0051583|dopamine uptake involved in synaptic transmission|GOCHE:25512|substance with neurotransmitter role|
|GO:0051610|serotonin uptake|GOCHE:25512|substance with neurotransmitter role|
|GO:0051933|amino acid neurotransmitter reuptake|GOCHE:25512|substance with neurotransmitter role|
|GO:0051934|catecholamine uptake involved in synaptic transmission|GOCHE:25512|substance with neurotransmitter role|
|GO:0051935|glutamate reuptake|GOCHE:25512|substance with neurotransmitter role|
|GO:0051936|gamma-aminobutyric acid reuptake|GOCHE:25512|substance with neurotransmitter role|
|GO:0098700|neurotransmitter loading into synaptic vesicle|GOCHE:25512|substance with neurotransmitter role|
|GO:0098810|neurotransmitter reuptake|GOCHE:25512|substance with neurotransmitter role|
|GO:0099528|G protein-coupled neurotransmitter receptor activity|GOCHE:25512|substance with neurotransmitter role|
|GO:0005550|pheromone binding|GOCHE:26013|substance with pheromone role|
|GO:0016503|pheromone receptor activity|GOCHE:26013|substance with pheromone role|
|GO:0019236|response to pheromone|GOCHE:26013|substance with pheromone role|
|GO:0042810|pheromone metabolic process|GOCHE:26013|substance with pheromone role|
|GO:0042811|pheromone biosynthetic process|GOCHE:26013|substance with pheromone role|
|GO:0042812|pheromone catabolic process|GOCHE:26013|substance with pheromone role|
|GO:0071444|cellular response to pheromone|GOCHE:26013|substance with pheromone role|
|GO:0052314|phytoalexin metabolic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052315|phytoalexin biosynthetic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052316|phytoalexin catabolic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052314|phytoalexin metabolic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052315|phytoalexin biosynthetic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052316|phytoalexin catabolic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052314|phytoalexin metabolic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052315|phytoalexin biosynthetic process|GOCHE:26115|substance with phytoalexin role|
|GO:0052316|phytoalexin catabolic process|GOCHE:26115|substance with phytoalexin role|
|GO:0009237|siderophore metabolic process|GOCHE:26672|substance with siderophore role|
|GO:0015343|siderophore transmembrane transporter activity|GOCHE:26672|substance with siderophore role|
|GO:0015891|siderophore transport|GOCHE:26672|substance with siderophore role|
|GO:0019539|siderophore biosynthetic process from hydroxamic acid|GOCHE:26672|substance with siderophore role|
|GO:0019540|siderophore biosynthetic process from catechol|GOCHE:26672|substance with siderophore role|
|GO:0044718|siderophore transmembrane transport|GOCHE:26672|substance with siderophore role|
|GO:0046215|siderophore catabolic process|GOCHE:26672|substance with siderophore role|
|GO:0009237|siderophore metabolic process|GOCHE:26672|substance with siderophore role|
|GO:0015343|siderophore transmembrane transporter activity|GOCHE:26672|substance with siderophore role|
|GO:0015891|siderophore transport|GOCHE:26672|substance with siderophore role|
|GO:0019539|siderophore biosynthetic process from hydroxamic acid|GOCHE:26672|substance with siderophore role|
|GO:0019540|siderophore biosynthetic process from catechol|GOCHE:26672|substance with siderophore role|
|GO:0044718|siderophore transmembrane transport|GOCHE:26672|substance with siderophore role|
|GO:0046215|siderophore catabolic process|GOCHE:26672|substance with siderophore role|
|GO:0009403|toxin biosynthetic process|GOCHE:27026|substance with toxin role|
|GO:0009404|toxin metabolic process|GOCHE:27026|substance with toxin role|
|GO:0009407|toxin catabolic process|GOCHE:27026|substance with toxin role|
|GO:0019534|toxin transmembrane transporter activity|GOCHE:27026|substance with toxin role|
|GO:1901998|toxin transport|GOCHE:27026|substance with toxin role|
|GO:0009403|toxin biosynthetic process|GOCHE:27026|substance with toxin role|
|GO:0009404|toxin metabolic process|GOCHE:27026|substance with toxin role|
|GO:0009407|toxin catabolic process|GOCHE:27026|substance with toxin role|
|GO:0019534|toxin transmembrane transporter activity|GOCHE:27026|substance with toxin role|
|GO:1901998|toxin transport|GOCHE:27026|substance with toxin role|
|GO:0006767|water-soluble vitamin metabolic process|GOCHE:27314|substance with water-soluble vitamin role|
|GO:0042364|water-soluble vitamin biosynthetic process|GOCHE:27314|substance with water-soluble vitamin role|
|GO:0042365|water-soluble vitamin catabolic process|GOCHE:27314|substance with water-soluble vitamin role|
|GO:0006767|water-soluble vitamin metabolic process|GOCHE:27314|substance with water-soluble vitamin role|
|GO:0042364|water-soluble vitamin biosynthetic process|GOCHE:27314|substance with water-soluble vitamin role|
|GO:0042365|water-soluble vitamin catabolic process|GOCHE:27314|substance with water-soluble vitamin role|
|GO:0006766|vitamin metabolic process|GOCHE:33229|substance with vitamin role|
|GO:0009110|vitamin biosynthetic process|GOCHE:33229|substance with vitamin role|
|GO:0009111|vitamin catabolic process|GOCHE:33229|substance with vitamin role|
|GO:0019842|vitamin binding|GOCHE:33229|substance with vitamin role|
|GO:0033273|response to vitamin|GOCHE:33229|substance with vitamin role|
|GO:0035461|vitamin transmembrane transport|GOCHE:33229|substance with vitamin role|
|GO:0051180|vitamin transport|GOCHE:33229|substance with vitamin role|
|GO:0071295|cellular response to vitamin|GOCHE:33229|substance with vitamin role|
|GO:0090482|vitamin transmembrane transporter activity|GOCHE:33229|substance with vitamin role|
|GO:0006766|vitamin metabolic process|GOCHE:33229|substance with vitamin role|
|GO:0009110|vitamin biosynthetic process|GOCHE:33229|substance with vitamin role|
|GO:0009111|vitamin catabolic process|GOCHE:33229|substance with vitamin role|
|GO:0019842|vitamin binding|GOCHE:33229|substance with vitamin role|
|GO:0033273|response to vitamin|GOCHE:33229|substance with vitamin role|
|GO:0035461|vitamin transmembrane transport|GOCHE:33229|substance with vitamin role|
|GO:0051180|vitamin transport|GOCHE:33229|substance with vitamin role|
|GO:0071295|cellular response to vitamin|GOCHE:33229|substance with vitamin role|
|GO:0090482|vitamin transmembrane transporter activity|GOCHE:33229|substance with vitamin role|
|GO:0016999|antibiotic metabolic process|GOCHE:33281|substance with antimicrobial agent role|
|GO:0017000|antibiotic biosynthetic process|GOCHE:33281|substance with antimicrobial agent role|
|GO:0017001|antibiotic catabolic process|GOCHE:33281|substance with antimicrobial agent role|
|GO:0042891|antibiotic transport|GOCHE:33281|substance with antimicrobial agent role|
|GO:0042895|antibiotic transmembrane transporter activity|GOCHE:33281|substance with antimicrobial agent role|
|GO:0046677|response to antibiotic|GOCHE:33281|substance with antimicrobial agent role|
|GO:0071236|cellular response to antibiotic|GOCHE:33281|substance with antimicrobial agent role|
|GO:0007584|response to nutrient|GOCHE:33284|substance with nutrient role|
|GO:0031670|cellular response to nutrient|GOCHE:33284|substance with nutrient role|
|GO:0032094|response to food|GOCHE:33290|substance with food role|
|GO:0071240|cellular response to food|GOCHE:33290|substance with food role|
|GO:0097329|response to antimetabolite|GOCHE:35221|substance with antimetabolite role|
|GO:0098649|response to peptidyl-dipeptidase A inhibitor|GOCHE:35457|substance with EC 3.4.15.1 (peptidyl-dipeptidase A) inhibitor role|
|GO:0098649|response to peptidyl-dipeptidase A inhibitor|GOCHE:35457|substance with EC 3.4.15.1 (peptidyl-dipeptidase A) inhibitor role|
|GO:0006805|xenobiotic metabolic process|GOCHE:35703|substance with xenobiotic role|
|GO:0008559|xenobiotic transmembrane transporting ATPase activity|GOCHE:35703|substance with xenobiotic role|
|GO:0009410|response to xenobiotic stimulus|GOCHE:35703|substance with xenobiotic role|
|GO:0042178|xenobiotic catabolic process|GOCHE:35703|substance with xenobiotic role|
|GO:0042908|xenobiotic transport|GOCHE:35703|substance with xenobiotic role|
|GO:0042910|xenobiotic transmembrane transporter activity|GOCHE:35703|substance with xenobiotic role|
|GO:0071466|cellular response to xenobiotic stimulus|GOCHE:35703|substance with xenobiotic role|
|GO:0004903|growth hormone receptor activity|GOCHE:37845|substance with growth hormone role|
|GO:0030252|growth hormone secretion|GOCHE:37845|substance with growth hormone role|
|GO:0060416|response to growth hormone|GOCHE:37845|substance with growth hormone role|
|GO:0071378|cellular response to growth hormone stimulus|GOCHE:37845|substance with growth hormone role|
|GO:0004903|growth hormone receptor activity|GOCHE:37845|substance with growth hormone role|
|GO:0030252|growth hormone secretion|GOCHE:37845|substance with growth hormone role|
|GO:0060416|response to growth hormone|GOCHE:37845|substance with growth hormone role|
|GO:0071378|cellular response to growth hormone stimulus|GOCHE:37845|substance with growth hormone role|
|GO:0005497|androgen binding|GOCHE:50113|substance with androgen role|
|GO:0005497|androgen binding|GOCHE:50113|substance with androgen role|
|GO:0099130|estrogen binding|GOCHE:50114|substance with estrogen role|
|GO:0099130|estrogen binding|GOCHE:50114|substance with estrogen role|
|GO:0061477|response to aromatase inhibitor|GOCHE:50790|substance with EC 1.14.14.14 (aromatase) inhibitor role|
|GO:0061477|response to aromatase inhibitor|GOCHE:50790|substance with EC 1.14.14.14 (aromatase) inhibitor role|
|GO:0061479|response to reverse transcriptase inhibitor|GOCHE:59897|substance with EC 2.7.7.49 (RNA-directed DNA polymerase) inhibitor role|
|GO:0061479|response to reverse transcriptase inhibitor|GOCHE:59897|substance with EC 2.7.7.49 (RNA-directed DNA polymerase) inhibitor role|
|GO:0061479|response to reverse transcriptase inhibitor|GOCHE:59897|substance with EC 2.7.7.49 (RNA-directed DNA polymerase) inhibitor role|
|GO:0004887|thyroid hormone receptor activity|GOCHE:60311|substance with thyroid hormone role|
|GO:0015349|thyroid hormone transmembrane transporter activity|GOCHE:60311|substance with thyroid hormone role|
|GO:0042403|thyroid hormone metabolic process|GOCHE:60311|substance with thyroid hormone role|
|GO:0042404|thyroid hormone catabolic process|GOCHE:60311|substance with thyroid hormone role|
|GO:0070324|thyroid hormone binding|GOCHE:60311|substance with thyroid hormone role|
|GO:0070327|thyroid hormone transport|GOCHE:60311|substance with thyroid hormone role|
|GO:0097066|response to thyroid hormone|GOCHE:60311|substance with thyroid hormone role|
|GO:0097067|cellular response to thyroid hormone stimulus|GOCHE:60311|substance with thyroid hormone role|
|GO:0004887|thyroid hormone receptor activity|GOCHE:60311|substance with thyroid hormone role|
|GO:0015349|thyroid hormone transmembrane transporter activity|GOCHE:60311|substance with thyroid hormone role|
|GO:0042403|thyroid hormone metabolic process|GOCHE:60311|substance with thyroid hormone role|
|GO:0042404|thyroid hormone catabolic process|GOCHE:60311|substance with thyroid hormone role|
|GO:0070324|thyroid hormone binding|GOCHE:60311|substance with thyroid hormone role|
|GO:0070327|thyroid hormone transport|GOCHE:60311|substance with thyroid hormone role|
|GO:0097066|response to thyroid hormone|GOCHE:60311|substance with thyroid hormone role|
|GO:0097067|cellular response to thyroid hormone stimulus|GOCHE:60311|substance with thyroid hormone role|
|GO:0009636|response to toxic substance|GOCHE:64909|substance with poison role|
|GO:0097237|cellular response to toxic substance|GOCHE:64909|substance with poison role|

**Comment by pgaudet** [comment]
ontology editors agree to remove the ChEBI roles.

**Comment by krchristie** [comment]
The plan has changed significantly since this ticket was opened and it is now supplanted by other tickets.
