### ISSUE TITLE
MHC class Ib receptor activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#16512]
Dear GO annotators,

Would it be possible to consider creating new GO terms for MHC class Ib receptors:

GO:0032394 MHC class Ib receptor activity - parent
GO:new inhibitory MHC class Ib receptor activity - child level 1
GO:new activating MHC class Ib receptor activity - child level 1
GO:new HLA-E specific inhibitory MHC class Ib receptor activity - child level 2
GO:new HLA-G specific inhibitory MHC class Ib receptor activity - child level 2

For review please check:
onlinelibrary.wiley.com/doi/pdf/10.1002/9780470015902.a0024246

Many thanks for your help,

Nevila Hyka-Nouspikel

**Comment by addiehl** [comment]
I would be in favor of all of these terms, which would be defined similarly to GO:0032396 inhibitory MHC class I receptor activity and GO:0032397 inhibitory MHC class I receptor activity, and would each be annotatable with multiple gene products.

-- Alex

**Comment by ukemi** [comment]
Thanks @addiehl !

**Comment by ukemi** [comment]
Would theclass 1b parent be a child of the class I term or sibling?

**Comment by addiehl** [comment]
We have treated them as sibling terms in the past:
http://amigo.geneontology.org/amigo/term/GO:0042287

MHC Class I and MHC Class Ib family do share a fair bit of structural similarity, but are usually considered distinct enough structurally and functionally that immunologist treat them as separate groups of genes.  One big difference is that MHC Class I genes are extremely polymorphic to handle binding to a wide range of possible antigenic peptides and T cell receptors, whereas the MHC Class Ib genes are generally monomorphic, having been selected to binding specific types of peptide and/or non-peptide antigens, depending on the specific MHC Class Ib protein, and often have non-T cell receptor counter receptors on responding cell types that are more important in their biological roles than matching T cell receptors.

So I favor the sibling approach still.

**Comment by nnouspikel** [comment]
I agree

**Comment by nnouspikel** [comment]
Thank you so much!
