### ISSUE TITLE
Add taxon restriction neurotransmitter transporter activity (GO:0005326)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16510]
I'm not sure what it should be , but as long as its never in fungi...

we are picking up annotations, probably via CHEBI role (when will this be fixed, it seems like a simple change, don't infer over role?)

**Comment by cmungall** [comment]
Immediate Action: Ontology eds: GOCHE:25512 'substance with neurotransmitter role' is a non-rigid class, we should remove this from GOCHE and use the part_of some GO:neurotransmission pattern in all usages.

I have made a ticket for the more general issue: https://github.com/geneontology/go-ontology/issues/16511

**Comment by cmungall** [comment]
Just noticing other oddities here.

```
id: GO:0051610
name: serotonin uptake
namespace: biological_process
def: "The directed movement of serotonin into a cell, typically presynaptic neurons or glial cells. Serotonin (5-hydroxytryptamine) is a monoamine neurotransmitter occurring in the peripheral and central nervous systems." [GOC:ai]
synonym: "5-HT uptake" EXACT []
synonym: "5-hydroxytryptamine uptake" EXACT []
synonym: "5HT uptake" EXACT []
synonym: "serotonin import" EXACT [GOC:dph, GOC:tb]
is_a: GO:0001504 ! neurotransmitter uptake
intersection_of: GO:0006810 ! transport
intersection_of: has_target_end_location GO:0099523 ! presynaptic cytosol
intersection_of: has_target_start_location GO:0005576 ! extracellular region
intersection_of: imports CHEBI:28790 ! serotonin
intersection_of: imports GOCHE:25512 ! substance with neurotransmitter role
```

The text definition is waffly as to what kind of cell the serotonin is taken up into. Maybe neuron? Maybe glial? Maybe some other kind (plants use serotonin as hormone)?

In fact the `has_target_end_location GO:0099523 ! presynaptic cytosol` forces this to be neuron based on the part-of chain.

I suggest renaming this to 'serotonin uptake into neuron' or something similar, so it isn't used accidentally for plants (maybe the fact that "uptake" is a more neuro-y word signals this but I prefer to be explicit).

this one has the correct pattern:

```
id: GO:0051583
name: dopamine uptake involved in synaptic transmission
namespace: biological_process
def: "The directed movement of dopamine into a presynaptic neuron or glial cell. In this context, dopamine is a catecholamine neurotransmitter and a metabolic precursor of noradrenaline and adrenaline." [GOC:ai]
synonym: "dopamine import involved in synaptic transmission" EXACT [GOC:dph, GOC:tb]
synonym: "dopamine reuptake involved in synaptic transmission" EXACT []
is_a: GO:0051934 ! catecholamine uptake involved in synaptic transmission
intersection_of: GO:0006810 ! transport
intersection_of: has_target_end_location GO:0099523 ! presynaptic cytosol
intersection_of: has_target_start_location GO:0005576 ! extracellular region
intersection_of: imports CHEBI:18243 ! dopamine
intersection_of: imports GOCHE:25512 ! substance with neurotransmitter role
```

Pet peeve: I hate definition gloss. I know it's comforting to see it:

_The directed movement of serotonin into a cell, typically presynaptic neurons or glial cells. **Serotonin (5-hydroxytryptamine) is a monoamine neurotransmitter occurring in the peripheral and central nervous systems**_

But this can obfuscate. These glosses are vertebrate-centric and can serve to confuse when we broaden the taxonomic context.

**Comment by ValWood** [comment]
For the record its this parentage (maybe others)
GO:0005313    L-glutamate transmembrane transporter activity

**Comment by ValWood** [comment]
Action add taxon constraint
never in fungi
GO:0005326    neurotransmitter transmembrane transporter activity
GO:0006836    neurotransmitter transport
then for me this could close unless  there is an action from @cmungall ?

**Comment by pgaudet** [comment]
How about only in taxon Metazoa, similar to the restriction we have for other neural processes?

**Comment by pgaudet** [comment]
@cmungall 
you write "(note there is no need for a TC here, as we already have it on neurotransmission)" 

What term are you referring to ? We dont have 'neurotransmission' in the ontology.

**Comment by ValWood** [comment]
> How about only in taxon Metazoa, similar to the restriction we have for other neural processes?

works for me.

**Comment by pgaudet** [comment]
Added the taxon restriction on parent GO:0006836	neurotransmitter transport

**Comment by pgaudet** [comment]
@krchristie I've added the requested taxon constraint, any other issue related to roles should already have other tickets ?
