### ISSUE TITLE
Remove EC xref on "positive regulation of oxidoreductase activity" (GO:0051353)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16516]
I don't think EC:1.97.1 ("Other oxidoreductases") should be an xref of this BP term:

id: GO:0051353
name: positive regulation of oxidoreductase activity
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of oxidoreductase activity, the catalysis of an oxidation-reduction (redox) reaction, a reversible chemical reaction in which the oxidation state of an atom or atoms within a molecule is altered." [GOC:ai]
xref: EC:1.97.1

**Comment by pgaudet** [comment]
We should NOT have any ECO in BP terms - should we ?

**Comment by cmungall** [comment]
Agreed, no ECO on BP.

Worth adding a SPARQL check for this or likely to be a one-off?

**Comment by sjm41** [comment]
I found 3 other BP terms with EC xrefs.  Not sure if that's the lot...

These two *may* be OK (describe 2/3-step reaction that is carried out by multiple enzymes)?
9,9'-di-cis-zeta-carotene desaturation to 7,9,7',9'-tetra-cis-lycopene (GO:0052889)
tRNA 3'-terminal CCA addition (GO:0001680)

And this one is obsolete:
obsolete deoxyhypusine biosynthetic process from spermidine (obsolete GO:0050983).

Several more examples of EC numbers used as an attribution in the def line of BP terms, but I guess that's OK.

**Comment by hdrabkin** [comment]
I removed the ECs as xrefs for these three. But I also notice that the synonyms for  and GO:0052889 GO:0001680 are activities, not processes. They are all narrow or broad, but I don't think this should be allowed.

**Comment by ValWood** [comment]
What is the action here?
It seems that @hdrabkin  has done his bit and some further action is required.

**Comment by hdrabkin** [comment]
But I also notice that the synonyms for and GO:0052889 GO:0001680 are activities, not processes. They are all narrow or broad, but I don't think this should be allowed.; if these are still there I will remove

**Comment by hdrabkin** [comment]
removed from GO:0052889
Will start transfer of others to the actual activity term later.

**Comment by hdrabkin** [comment]
Actually can close this and I'll put a note to remove and transer the synonyms to the activities.

**Comment by sjm41** [comment]
OK, thanks Harold.  I'll close.
