### ISSUE TITLE
change to GO resulted in bitg drop in annotations to transcription

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16526]
Our genes annotated to transcription were 467 yesterday.
Today 409. I'm not sure what we lost or how, but it seems like an ontology change.
I'm sure the previous list was correct and we haven't changed a lot of annotations.

I will try to look later what is missing, but I'm not sure if I can easily access the existing list.

**Comment by ValWood** [comment]
one drop is here:
DNA-binding transcription factor activity, RNA polymerase II-specific (GO:0000981)

used to have ~93 annotations, now only has 71

**Comment by ValWood** [comment]
Everything previously annotated to
transcription factor activity, RNA polymerase II proximal promoter sequence-specific DNA binding (GO:0000982) (93) genes, should now be annotated to 


DNA-binding transcription factor activity, RNA polymerase II-specific (GO:0000981)

was this done as a merge?

**Comment by ValWood** [comment]
Around ~10 of the drop is due to me removing some phenotype annotations to silencing.
I can't account for the rest...

**Comment by mah11** [comment]
a lot of these should be resolved when we fix name/ID mismatches reported in our in-house loading logs

**Comment by ValWood** [comment]
OK, I think its probably fine....

**Comment by pgaudet** [comment]
@ValWood transcription factor activity, RNA polymerase II proximal promoter sequence-specific DNA binding  (GO:0000982) and DNA-binding transcription factor activity, RNA polymerase II-specific (GO:0000981) were merged. 

Does that explain the difference ?

**Comment by ValWood** [comment]
No a merge shouldn't affect our slim totals. I think maybe we haven't dealt with all of our  obsoletions. Will chat to @mah11  and open a new ticket if we still lost anything.
