### ISSUE TITLE
EC xref on "GMP reductase complex" (GO:1902560)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16520]
Feel free to just close this - more of a question than an issue.
I noticed that the "GMP reductase complex" CC term has an EC xref (see below).
This isn't wrong, but I _think_ it's the only example of a CC (complex) term in the GO with an EC xref -  I was expecting the EC (and Rhea) xref to be restricted to the MF term "GMP reductase activity" (GO:0003920) and had assumed this was general policy, but I may be wrong....

==

id: GO:1902560
name: GMP reductase complex
namespace: cellular_component
def: "An oxidoreductase complex which is capable of GMP reductase activity. It catalyses the irreversible reaction: GMP + 2 H(+) + NADPH => IMP + NADP(+) + NH(4)(+)." [GOC:bhm, GOC:TermGenie, PMID:12009299]
comment: An example of this is GMPR2 in human (UniProt Symbol Q9P2T1) in PMID:12009299 (inferred from direct assay).
xref: EC:1.7.1.7
xref: RHEA:17187
is_a: GO:1902494 ! catalytic complex

**Comment by vanaukenk** [comment]
Thanks @sjm41 - I will remove the xrefs from the complex term.
