### ISSUE TITLE
Obsoletion notice: GO:0021777 BMP signaling pathway involved in spinal cord association neuron specification

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16531]
@gantonazzo 

Should 'BMP signaling pathway involved in spinal cord association neuron specification' be a child of 
'BMP signaling pathway involved in spinal cord dorsal/ventral patterning'

Seems odd to me. 

Thanks, Pascale

**Comment by gantonazzo** [comment]
It seems odd to me too, and it looks like there aren't many annotations to 'BMP signaling pathway involved in spinal cord association neuron specification' and its child terms. Do we need this term at all?

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete 

GO:0021777 BMP signaling pathway involved in spinal cord association neuron specification

The reason for obsoletion is that BMP signaling is involved in multiple processes and specific processes should be captured using GO-CAM models. 

There is a single annotation to this term by AgBase. There are no mappings (cross-references); this term is not in any subset (slims). 

We are opening a comment period for this proposed obsoletion. Please comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/16531

We’d like to proceed and obsolete this term on Nov 6, 2018. Unless objections are received by Nov 6, 2018, we will assume that you agree to this change.


Thanks, Pascale

**Comment by pgaudet** [comment]
Note that the regulation terms will also be obsoleted: 


- GO:1902878 regulation of BMP signaling pathway involved in spinal cord association neuron specification
-- GO:1902879 negative regulation of BMP signaling pathway involved in spinal cord association neuron specification
-- GO:1902880 positive regulation of BMP signaling pathway involved in spinal cord association neuron specification
