### ISSUE TITLE
Remove link between GO:0021919 'BMP signaling pathway involved in spinal cord dorsal/ventral patterning' and GO:0021914 'negative regulation of smoothened signaling pathway involved in ventral spinal cord patterning'

### ISSUE THREAD

**Issue by gantonazzo** [geneontology/go-ontology#16530]
Hi,

GO:0021919 'BMP signaling pathway involved in spinal cord dorsal/ventral patterning' is currently a child of  GO:0021914 'negative regulation of smoothened signaling pathway involved in ventral spinal cord patterning'. Could we please revise this link (and possibly remove it)?

**Comment by cmungall** [comment]
in general we should not have asserted edges between regulation terms
