### ISSUE TITLE
steroid hormone receptor activity definition revision

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16535]
Hi

1. GO:0003707 steroid hormone receptor activity has GO terms in the definition that no longer exist: 
.........For steroid hormone receptors that act in the nucleus to regulate transcription, consider also annotating to the terms: ligand-activated sequence-specific DNA binding RNA polymerase II transcription factor activity ; GO:0038049' or ligand-activated RNA polymerase II transcription factor binding transcription factor activity ; GO:0038049'

Please update these GO IDs, perhaps replace with:
.........For steroid hormone receptors that act in the nucleus to regulate transcription, consider also annotating to the terms: GO:0004879 nuclear receptor activity, or GO:0030374 nuclear receptor transcription coactivator activity.

2. Also the comments associated with GO:0004879 nuclear receptor activity, please change: 'ligand-activated RNA polymerase II transcription factor binding transcription factor activity ; GO:0038049'  to GO:0030374 nuclear receptor transcription coactivator activity

3. Also the  comments associated with GO:0030374 nuclear receptor transcription coactivator activity need to change to: When the nuclear receptor functions by binding directly to DNA response elements, consider instead annotating to 'nuclear receptor activity, ; GO:0004879'.

4. Note merging androgen receptor activity into GO:0004879 nuclear receptor activity would mean that curators will also have to annotate to the previous 'androgen receptor activity' parent GO:0003707 steroid hormone receptor activity

Thanks

Ruth

**Comment by pgaudet** [comment]
Did 1-3. What do you mean in point 4 ?

**Comment by RLovering** [comment]
I think it would be good to keep the steroid hormone receptor term, but how about adding a note to the nuclear receptor term and suggest people consider annotating to the steroid hormone term if this is appropriate? The alternative would be to make 2 child terms, nuclear steroid receptor and transmembrane steroid receptor!

**Comment by pgaudet** [comment]
I created a new ticket to deal with the nuclear versus TM steroid receptor activity terms.
