### ISSUE TITLE
MP GO:1903515 | calcium ion transport from cytosol to endoplasmic reticulum

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16539]
GO:1903515 | calcium ion transport from cytosol to endoplasmic reticulum
does not have the parent
GO:0046967    cytosol to ER transport (shouldn't this be a transmembrane term, is there any other transport into the ER?)

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/pull/16542
