### ISSUE TITLE
NTR:  yolk syncytial layer development

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#16536]
I would like to request a new BP term:  yolk syncytial layer development
synonyms: YSL development

This term would be a child of GO:0048856 (anatomical structure development)
Should refer to the UBERON term UBERON:2000088 (YSL) (with the  results_in_development_of ??)

Please let me know if you need anything else. 
Thank you!

**Comment by hdrabkin** [comment]
Hi @sabrinatoro 
Can you please supply supporting PMIDs
Thanks.

**Comment by sabrinatoro** [comment]
Hi @hdrabkin 
PMID is PMID:29180571
(https://www.ncbi.nlm.nih.gov/pubmed?cmd=search&dopt=AbstractPlus&term=29180571)

**Comment by hdrabkin** [comment]
Can you supply a better suggested definition?

**Comment by sabrinatoro** [comment]
How about this (following the structure of other "development" definitions): 
The progression of the yolk syncytial layer over time, from its initial formation to the mature structure.
The yolk syncytial layer is the peripheral layer of the yolk cell including nuclei and non-yolky cytoplasm.

Note about taxon: 
the "yolk syncytial layer" structure can be found in Teleostei, Myxini, Chondrichthyes, Lepisosteiformes and Cephalopoda according to 
https://doi.org/10.1134/S1062359016030055 
https://link.springer.com/article/10.1134/S1062359016030055

**Comment by hdrabkin** [comment]
Yes, that's what I was thinking, but I wonder if I should make  the GO term name  agree with Uberon's label (YSL development).  Our in-house mouse anatomy geru thinks Uberon made a poor choice to use the abbreviation as the primary term name.

**Comment by cerivs** [comment]
We use the YSL as a primary label because that is what our users use.  But for uberon yolk syncytial layer makes more sense since the use of YSL isn't as common (I hope).

**Comment by cmungall** [comment]
Uberon and GO should always terminologically agree

**Comment by hdrabkin** [comment]
Good, that's what I thought.

**Comment by ValWood** [comment]
pinging @hdrabkin 
>2018: This will be reflected in the next release

**Comment by hdrabkin** [comment]
Term made but I don't see 'yolk syncytial layer' ; do I need to do an import request?
GO:0106336 yolk syncytial layer development
