### ISSUE TITLE
Merge  GO:0001199 transcription factor activity, metal ion regulated sequence-specific DNA binding & children into parent 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16534]
These functions terms are probably not necessary - DNA binding transcription factor activity is probably sufficient. I would like to find the correct way to describe the process before merging the function terms. See review here for a better way to capture the process: 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4631667/pdf/nihms714072.pdf

**Comment by bmeldal** [comment]
Change in one complex where we used it.

**Comment by pgaudet** [comment]
Hello, 

Looking more closely at this: I think we can safely merge these terms into their parents, and use 'activated_by' or 'inhibited_by' in P2GO, similar to what was recommended for nuclear receptors (see #16540)

Annotations are here: https://docs.google.com/spreadsheets/d/1GT5f-qZOyB9kfJfmw_sw6xTTzNp5KezlMwypRy5UX1s/edit#gid=0

**Impacted groups:** 
EcoCyc @keseler 
CAFA @ggeorghiou 
SGD @srengel  
TAIR @tberardini  (2 annotations - requested review)
PomBase @ValWood 
UniProt @ggeorghiou  (1 annotation - requested review)

Let me know if this is OK with you. 

Thanks, Pascale

**Comment by ValWood** [comment]
so will they merge into
"DNA-binding transcription factor activity"?
v

**Comment by ValWood** [comment]
I mean
DNA-binding transcription factor activity, RNA polymerase II-specific

**Comment by pgaudet** [comment]
> DNA-binding transcription factor activity, RNA polymerase II-specific
Yes, or 'bacterial RNA polymerase ...', as appropriate.

**Comment by ValWood** [comment]
done.
