### ISSUE TITLE
Merge nuclear receptors (transcription factors) into GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16540]
Hello, 

The following terms describing specific nuclear receptors (transcription factors) will be merged into GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific: 

* GO:0004882 androgen receptor activity + regulation children
* GO:0008434 calcitriol receptor activity
* GO:0004884 ecdysteroid hormone receptor activity 
* GO:0004880 juvenile hormone receptor activity 
* GO:0003708 retinoic acid receptor activity 
* GO:0004886 9-cis retinoic acid receptor activity  
* GO:0038052 RNA polymerase II transcription factor activity, estrogen-activated sequence-specific DNA binding  
* GO:0038050 RNA polymerase II transcription factor activity, glucocorticoid-activated sequence-specific DNA binding 
* GO:0004887 thyroid hormone receptor activity + regulation children

There is no action needed, unless groups want to capture the ligand using an annotation extension or a Noctua model. I have added the replacements here: 
https://docs.google.com/spreadsheets/d/19KvlqWegkVPXeWG1kvekH5HeDatimW68bGju-jski_0/edit#gid=0

Thanks, Pascale

**Comment by RLovering** [comment]
please give us a week or more to capture the information in the AE field before the merge

Thanks

Ruth

**Comment by pgaudet** [comment]
Sure no worries. (In any case everything is saved in the google doc). Pascale

**Comment by RLovering** [comment]
Hi 
I just noticed that  GO:0004887 thyroid hormone receptor activity has the parent  GO:0038023
signaling receptor activity. I think this parent should be added to the GO:0004879
nuclear receptor activity term. What do you think?

Thanks

Ruth

**Comment by pgaudet** [comment]
> I just noticed that GO:0004887 thyroid hormone receptor activity has the parent GO:0038023
signaling receptor activity. I think this parent should be added to the GO:0004879
nuclear receptor activity term. What do you think?

Yes, I added that back.

**Comment by hattrill** [comment]
@pgaudet Can you hold off until I have a chance to look? Should get to it soon. Thanks.

**Comment by bmeldal** [comment]
Doing them now. I have 23 complexes to fix in total (incl the historic ones that don't go in the GPAD). I will change them in our DB, but we don't use extensions.

**Comment by bmeldal** [comment]
done

**Comment by sabrinatoro** [comment]
@pgaudet 
It doesn't seem like "directly activates" is the correct relationship (I get an "inconsistent" error)

**Comment by hattrill** [comment]
I'm done.

**Comment by pgaudet** [comment]
@hdrabkin Can you have a look for MGI ? 
@ggeorghiou @sylvainpoux Are you good with just a merge or do you want to add extensions ?

**Comment by pgaudet** [comment]
@sabrinatoro I'd rather have @vanaukenk's input on this one. I can do 'has input' but 'activated by' would be more precise, but it's not in RO, just in GO_REL (I think). 

Sorry this is not very helpful! 

Pascale

**Comment by ukemi** [comment]
Regulation relations can only be used between processes, so directly_activates should fail the reasoning check. Unless there was some progress on sub-classifying participation at the recent RO meeting, I think 'has input' is the best we can do right now.

**Comment by pgaudet** [comment]
What we needed was to say 'x activity' activated_by CHEBI:xxxx

as described here: https://github.com/geneontology/annotation_extensions/blob/master/doc/activated_by.md

**Comment by vanaukenk** [comment]
Yes, right now 'has input' is the best relation to use between the MF of the transcription factor and the chemical entity.  

As @ukemi points out, the 'directly activates' relation describes a regulatory interaction between two processes so will give a reasoning error when used between a ChEBI term and a GO MF.

It would be helpful to get an update on any progress towards sub-classifying participants as discussed at the RO meeting.  Perhaps @cmungall could report back from the meeting on the 11/5 ontology editors call?

**Comment by ukemi** [comment]
A report from the RO meeting is on the agenda.

**Comment by vanaukenk** [comment]
Great; thanks @ukemi !

**Comment by RLovering** [comment]
Hi 
please could you provide a link to the agenda
Thanks
Ruth

**Comment by pgaudet** [comment]
To GO editors: Can I merge this ? Or do we need to wait for clarification on relations?

**Comment by pgaudet** [comment]
@sabrinatoro Please use 'has input' then :)

**Comment by sabrinatoro** [comment]
@pgaudet : will do! :-) 
I think it is ok if you continue with this merge (I'll get to it asap).

**Comment by sabrinatoro** [comment]
@pgaudet. @ukemi @vanaukenk 
Can we have "has input" + Chebi#?
(I am still having some inconsistency error... 
Thanks!

**Comment by ukemi** [comment]
Hmmm. What is your model?

**Comment by sabrinatoro** [comment]
oops, forgot to add this... http://noctua.geneontology.org/editor/graph/gomodel:5b91dbd100001025
(I also put this on Gitter for discussion)

**Comment by ukemi** [comment]
Wow. The roles come back to bite us again. Good catch Jim! @sabrinatoro, can you replace thyroid hormone and androgen with bonafide chemicals?

**Comment by sabrinatoro** [comment]
@ukemi : It took some digging, but I was able to find the bonafide chemicals. 
That being said, this is a solution which is different from the one suggested in this case (using "androgen" and "thyroid hormone" in annotation extensions)... I don't know if this will have consequences in the future and/or whether it is something to worry about.

**Comment by pgaudet** [comment]
On yesterday's ontology call, @ukemi  proposed that we annotate nuclear receptors like this: 
http://noctua.geneontology.org/editor/graph/gomodel:5b91dbd100001177?barista_token=v9idfze5v6yaqeork9wg#

(right @ukemi @vanaukenk ? ) 

----
@RLovering Aligning with protein2GO is certainly a concern - we just need to first agree on how to annotate... 

Pascale

**Comment by ukemi** [comment]
Yes. But of course we need to check how this works with property chains etc. It would be nice to have a general pattern for all receptors that works.

**Comment by ukemi** [comment]
@vanaukenk  and @sabrinatoro and I played around with this a lot this afternoon. In the end we decided it was least confusing to just use has_input, but I think that we really want a short-cut relation to describe this type of participation.

**Comment by ukemi** [comment]
BUT we need to define the short-cut relation very precisely with respect to how it relates to existing relations.

**Comment by pgaudet** [comment]
@ukemi So we don't use binding anymore ?
