### ISSUE TITLE
regulation of vein smooth muscle contraction

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#16545]
I would like to see "regulation of vein smooth muscle contraction”, “positive regulation of…” and " negative regulation of…” added to the GO ontology under the parent term "vein smooth muscle contraction” (GO:0014826).   The definitions could be "Any process that modulates/increases/decreases the frequency, rate or extent of vein smooth muscle contraction.  Example can be found in PMID:8428203.

**Comment by pgaudet** [comment]
Hi @slaulederkind 
What protein are you annotating here ? The title states that the muscarinic receptor **mediates** contractile activities in the rat isolated portal vein. Perhaps the existing terms is OK, and we don't need 'regulation'? it looks like the regulation would be capturing the increased contraction in the presence of ligand, but that seems normal if this is the receptor that signal vein contraction. 

What do you think ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Hi @pgaudet,

It looks like there is precedence for the muscarinic receptors being annotated to regulation of muscle contraction terms in rat. See human CHRM3 and the purinergic/adrenergic receptors. It also looks like downstream functions of the adrenergic pathways have also been annotated to the regulatory process.  I think most physiologists would say that these signaling pathways regulate the contraction and reserve the contraction itself for the cytoskeletal elements that carry out the process. I we decide that we do not want to go the regulation route here, we should go back and remove all of the existing annotations and terms that refer to the regulation of smooth muscle contraction. @vanaukenk what do you think?
