### ISSUE TITLE
Positive regulation of  GO:0006105 succinate metabolic process

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16559]
Hi

for the annotation of GHR please could I have this term
Ref PMID:18648510

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering Thinking about his further, perhaps we should use 'acts upstream of'? what do you think ? 
@vanaukenk  this consistent with the Transcription annotation guidelines in Noctua if I remember well?

**Comment by RLovering** [comment]
yes I am happy to add acts up stream of positive effect. but having read the paper properly I think I only want to include the regulation of one of the metabolic pathways - sorry about this
