### ISSUE TITLE
Obsolete GO:0001074 transcription factor activity, RNA polymerase II proximal promoter sequence-specific DNA binding involved in preinitiation complex assembly

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16554]
Dear all, 

The proposal has been made to obsolete 'GO:0001074 transcription factor activity, RNA polymerase II proximal promoter sequence-specific DNA binding involved in preinitiation complex assembly'. 

The reason for obsoletion is that this term represents a GO-CAM model. There is a single manual annotation to this term (UCL-BHF). There are no mappings to his term; this term is not in any subsets (slims). 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/16554

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 8th, 2018. Unless objections are received by November 8th, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by RLovering** [comment]
Ok I have updated my annotation please go ahead and delete term
Ruth
