### ISSUE TITLE
Automatically manage dbxrefs between ComplexPortal and GO complex terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16553]
From #16513

Suggested action points: 
1.  **CP group**: Create and maintain a mapping file between CPX-GO IDs (we can use the GPAD for this)
2. **GOC**: Put in place a mechanism to maintain the GO xrefs to CPX up to date at each release. 
2.1 Involves removing all current dbxrefs (ie both "IntAct:EBI-xxx" as well as existing ComplexPortal:CPX-xxx), to have the mechanism completely automated. 
3. For new term creation: No CPX xref would be manually added; these would be requested directly to CP if missing. (At the moment if this happen we can direct people to the 'request' button on the CP page). 

Thanks, Pascale

@bmeldal

**Comment by bmeldal** [comment]
from @tonysawfordebi by email:

I think there's (possibly) some confusion here...

Any references to complexes in the Cross-references section of QuickGO's term page are derived from xrefs that are defined in the ontology itself; they get passed through to QuickGO untouched.

The content of the Protein Complexes section is derived from *annotations* between complexes and complex terms, and we now don't have very many of those, because it has been decided that complexes should not be annotated to complex terms any more, because these annotations are really cross-references. If that is the case, then - in my simple-minded view of the world - they should go into the ontology along with the existing cross-references. Either that, or there should be *no* complex cross-references in the ontology, and somebody needs to come up with a new mechanism for specifying them. What we really don't want is two separate ways of doing essentially the same thing.

What are the objections to having the xrefs in GO itself? To me, it doesn't really seem any different to having xrefs to, say, ChEBI entries.

Cheers,
Tony

**Comment by bmeldal** [comment]
Ok, the source of the data is clear:

**xrefs**: from the hard-coded ontology entries. Currently, the xrefs only get added at the point of requesting a new term. The old EBI-xxx links are dead as they still point to IntAct, not Complex Portal.

**"Protein Complexes"**: from the "annotations" done via Protein2GO. Updated with every release but this type of annotation is no longer permitted as it's a xref and we don't want it in the annotation files. Groups are removing these annotation as we speak, making sure they are done to the individual GPs. That means that this section will be empty very soon.

**Logical endpoints:**

- One place for all CP AC-GO CC term xrefs that are updated via CP GPAD.

- Data should be visible through QuickGO and Amigo.

- ACs are all of CPX-xxxx type and links point to CP (not EBI-xxxxxxx ACs pointing to 0 results in IntAct).

Question: How can we implement this pipeline so it's automatic?

**My humble opinion:**

I don't mind which section it goes in as long as it's updated automatically as no-one is going to add the missing xrefs manually. If it goes via the ontology it'll be in the files. If it goes directly onto the website it won't be in the files except the GPAD we supply on our IntAct ftp site and therefore less visibly for programmatic users.

**Comment by pgaudet** [comment]
@cmungall If ComplexPortal provides and maintains a mapping file, will the x-references be automatically be maintained ?

**Comment by deustp01** [comment]
Perhaps the planned way to handle xrefs from catalyzed Reactome reactions to GO MF terms would apply here (with the very big disclaimer that we haven't implemented it yet). Reactome generates a complete table of reaction - MF pairs in connection with each release (no distinction among new, revised, and old items); GO takes that list, drops all existing Reactome - MF xrefs and generates a complete new set from the new list. Generating the list is our chore (but a scriptable one) and a user curious about the history of an xref must come to us and ask about the history of the Reactome reaction instance to find out; generating the xrefs is GO's (scriptable) chore.

**Comment by pgaudet** [comment]
Thanks @deustp01 
And how are these xreferences integrated into the ontology ? Is there already a process in place?

**Comment by ukemi** [comment]
The process at the moment is that we manually add them to terms upon request. But perhaps this can be rolled into a similar process to the one we are putting in place for reactome xrefs.

**Comment by goodb** [comment]
Okay for me.  The main things that would need to happen are (1) decide what, if any, xrefs should remain directly asserted in the ontology file (hopefully zero I would guess). (2) take any out that will be maintained externally.  (3) for @noedelta to construct and maintain a file like [the one Reactome is providing](https://reactome.org/download/current/Reactions2GoTerms_human.txt) and make sure that remains stable and accessible via an HTTP request.  (4) for me or some one in GO software to adjust the ontology makefile to grab those xrefs and add them into the go when its constructed.

**Comment by bmeldal** [comment]
Hi @goodb There is no search url behind the hyperlinks to Reactome for the new refs:
e.g. https://www.ebi.ac.uk/QuickGO/term/GO:0008253
New ticket? Known bug?
It also doesn't display the name that is included in the file. In the above example there are 13 Reactome xrefs and the user can't tell what's what just from the AC.

**Comment by deustp01** [comment]
We definitely want links to the Reactome events, and a display on the QuickGO page of the name of each reaction would be good. @goodb , the event names are in the mapping file we provide. @fabregat , if this isn't obvious, can you point Ben to the optimal feature in the content service https://reactome.org/ContentService/ to make the links?

There is also a longer term problem buried in here, which is that any one GO MF term can map to many Reactome events (the current record is 402 for "protein serine/threonine kinase activity"). As discussed in Geneva in December, the Reactome events are really annotations, not ontology terms so both to tidy up the display and for logical consistency, a different way of representing and displaying the Go-to-Reactome links would be good. That's not an argument against the quick patches noted here, only a thought that they should be quick patches, not building for the ages.

**Comment by goodb** [comment]
Hi @bmeldal these look like QuickGO display problems, not ontology problems.  Looking at the [go.obo file in snapshot](http://snapshot.geneontology.org/ontology/go.obo) I see that the names are there.  The URL for each would be composed by appending the HSA identifier to the prefix: https://reactome.org/content/detail/  .   e.g. https://reactome.org/content/detail/R-HSA-109278

xref: EC:3.1.3.5
xref: MetaCyc:5-NUCLEOTID-RXN
xref: reactome:R-HSA-109278 "NT5E:Zn2+ hydrolyses AMP,dAMP,GMP, IMP"
xref: reactome:R-HSA-109291 "CMP or TMP or UMP + H2O => cytidine, thymidine, or uridine + orthophosphate [NT5E]"
xref: reactome:R-HSA-109380 "(d)CMP, TMP, or (d)UMP + H2O => (deoxy)cytidine, thymidine, or (deoxy)uridine + orthophosphate (NT5C1A)"
xref: reactome:R-HSA-109387 "(d)AMP, (d)GMP, or (d)IMP + H2O => (deoxy)adenosine, (deoxy)guanosine, or (deoxy)inosine + orthophosphate (NT5C1A)"
xref: reactome:R-HSA-109415 "AMP + H2O => adenosine + orthophosphate [NT5C1B]"
xref: reactome:R-HSA-109449 "(d)CMP, TMP, or (d)UMP + H2O => (deoxy)cytidine, thymidine, or (deoxy)uridine + orthophosphate (NT5C3)"
xref: reactome:R-HSA-109470 "(d)GMP or (d)IMP + H2O => (d)G or (d)I + orthophosphate (NT5C)"
xref: reactome:R-HSA-109480 "TMP, uridine 2', 3', or 5' monophosphates, or deoxyuridine 3' or 5' monophosphates + H2O => thymidine or (deoxy)uridine + orthophosphate [NT5C]"
xref: reactome:R-HSA-109514 "TMP, (d)UMP, uridine 2' monophosphate, or uridine 3'-monophosphate + H2O => thymidine, deoxyuridine, or uridine + orthophosphate [NT5M]"
xref: reactome:R-HSA-5694126 "NT5C3B hydrolyses 7MGP to 7MG"
xref: reactome:R-HSA-74248 "(d)GMP or (d)IMP + H2O => (2'-deoxy)guanosine or (2'-deoxy)inosine + orthophosphate (NT5C2)"
xref: reactome:R-HSA-8940070 "NT5E:Zn2+ hydrolyses NAD+"
xref: reactome:R-HSA-8940074 "NT5E:Zn2+ hydrolyses NMN"

**Comment by cmungall** [comment]
QuickGO should be using the metadata from https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L2509-L2523 so this should all work automatically

cc @alexsign

**Comment by bmeldal** [comment]
@goodb 
The xrefs are already in the following file:
ftp://ftp.ebi.ac.uk/pub/databases/intact/current/various/
complex_portal.gpa

This file contains all GO annotations that we export. It would have to be parsed for protein-containing complex terms and children. Could you do it easily at your end from this file?

**Comment by goodb** [comment]
I'm not seeing xrefs as I normally see them in that file.  Am I missing something?  
The short answer is no, not really.  If your side can produce a file with the same structure as the reactome one.  e.g. 3 tab delimited columns like this: 
Identifier	Name	GO_Term
R-HSA-1008248	Adenylate Kinase 3 is a GTP-AMP phosphotransferase	GO:0046899

Then we can build the xrefs into the ontology as it is constructed very easily.

**Comment by bmeldal** [comment]
The link I gave you is to the GDAP which is an annotation file, hence why I asked if you can parse it out from there. 

I'll discuss with @noedelta and get back to you.

**Comment by alexsign** [comment]
@cmungall Sorry Chris, I missed this somehow. But, yes you are right it's all automatic. Problem is in inconsistency between json/obo files and db-xrefs.yaml.
for example:
go-plus.json:          "val" : "reactome:R-HSA-109278"
go obo:  xref: reactome:R-HSA-109278 
...
so "reactome" all lower case

but in  db-xrefs.yaml
 database: Reactome
  name: Reactome - a curated knowledgebase of biological pathways
  synonyms:
    - REACTOME
    - REAC
...
no all lowercase synonym there. I guess easy fix is to add another synonym "reactome" to db-xrefs.yaml

After is done next QuickGO ontology update should solve the issue with links to Reactome.

**Comment by cmungall** [comment]
@goodb looks like should be leading upper case

**Comment by goodb** [comment]
okay.  See https://github.com/geneontology/go-ontology/pull/16856 for update to make process

**Comment by alexsign** [comment]
@goodb @cmungall the issue with the Reactome links from QuickGO is fixed after last Ontology update 2019-03-29. Thanks.

**Comment by deustp01** [comment]
> but in db-xrefs.yaml
> database: Reactome
> name: Reactome - a curated knowledgebase of biological pathways
> synonyms:
> - REACTOME
> - REAC
> ...
> no all lowercase synonym there. I guess easy fix is to add another synonym "reactome" to db-xrefs.yaml

From January 18 - sorry for the lapse. If that second synonym, REAC, is intended to catch old-style (now obsolete) Reactome stable IDs, it should be REACT.

**Comment by alexsign** [comment]
@goodb @cmungall yesterday update of Ontology has all lower case "reactome" again. 
Example from go-plus.json: "val" : "reactome:R-HSA-6800138"
I thought the agreement was to use "val" : "Reactome:R-HSA-6800138"
which was fixed in Ontology update from 2019-03-29

**Comment by balhoff** [comment]
@alexsign I see what you mean—I will look into this. So far I don't see any build process changes that should have led to this.

**Comment by balhoff** [comment]
@alexsign this appears to be correct in the ontology build, but the overall GO snapshot pipeline (i.e. including the annotations) has been having problems for a while now. Once those issues clear out I am expecting this to be corrected.

**Comment by alexsign** [comment]
@balhoff thanks, I'll keep what I have now until the issue is fixed

**Comment by pgaudet** [comment]
@cmungall @balhoff 
Would we now be able to load a mapping file if ComplexPortal were to provide it ? 

Thanks, Pascale

**Comment by goodb** [comment]
@pgaudet see comments above.  If they can provide a simple tabular mapping file like the Reactome one, then yes.

**Comment by pgaudet** [comment]
@bmeldal

**Comment by bmeldal** [comment]
It's on our to-do list but I don't have an ETA yet. Sorry.

**Comment by pgaudet** [comment]
No worries- at least we know the action now. I'm assigning this one to you now. 

We can also close this until you are ready to submit ? Up to you. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Leave it open so it remains on my to-do list!

**Comment by pgaudet** [comment]
@bmeldal any update on this?

**Comment by bmeldal** [comment]
I still haven't got a developer to create this file. Sorry.

**Comment by pgaudet** [comment]
No problem, just checking.

**Comment by pgaudet** [comment]
@bmeldal Hi ! This is my once-a year ping ;)

**Comment by cmungall** [comment]
it took me less time to write this than it did to read this ticket from top to bottom:

```
curl -L -s ftp://ftp.ebi.ac.uk/pub/databases/intact/current/various/complex_portal.gpa |\
   perl -ne 'print "\n[Term]\nid: $3\nxref: $1:$2\n" if m@^(ComplexPortal)\t(\S+)\tpart_of\t(GO:\d+)@' 
```

output:

```
...
[Term]
id: GO:0005615
xref: ComplexPortal:CPX-3290

[Term]
id: GO:0070743
xref: ComplexPortal:CPX-3290
...
```

the hacky script will of course need changed when gpa changes to v2

anyway this part is easy. integrating this into the ontology file is harder than it should be, when I look at the go-ontology Makefile. I think we need to dedicate ~1day to rewriting how we manage import and export of mappings, and switch to sssom

**Comment by pgaudet** [comment]
thanks !

**Comment by bmeldal** [comment]
@pgaudet @cmungall does that mean you no longer need a separate mapping file from us? That would be ace!

**Comment by bmeldal** [comment]
@cmungall is your solution above a permanent fix? If yes, please close this ticket and I can close one on my end, too.

**Comment by pgaudet** [comment]
Meanwhile I will remove the few xrefs we have to CP (19) and Intact (227); the latter dont resolve anymore anyway and would need to be mapped manually, according to @bmeldal .

**Comment by pgaudet** [comment]
@cmungall 's script returns two types of results: 

1. complexes annotated to cellular anatomical entities: for eg: 
id: GO:0005743 mitochondrial inner membrane
xref: ComplexPortal:CPX-3281 Mitochondrial proton-transporting ATP synthase complex
 
This is not a xref: the annotation is right, but the GO and the CPX terms here are no equivalent.
 
2. Species-specific CP complexes to GO complexes: 
id: GO:0000172: ribonuclease MRP complex
xref: ComplexPortal:CPX-3284: yeast Nucleolar ribonuclease MRP complex
 
This is correct, and it potentially provides new information, since we cannot annotate a Protein Complex to a GO Protein complex (the complex is not part_of the complex, it is an instance of the complex, in a specific organism.

We could implement Chris' script in the ontology pipeline, filtering out any annotation to [cellular anatomical entity](http://purl.obolibrary.org/obo/GO_0110165)

Thanks, Pascale

**Comment by cmungall** [comment]
Shouldn't the gpa file be fixed?

> ComplexPortal	CPX-3284	part_of	GO:0000172	PMID:20075859	ECO:0000353		559292	20220104	ComplexPortal

This isn't properly a part-of

I think we need to add is_a to:

https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#allowed-gene-product-to-go-term-relations

I see we have a few issues about complexes in GPAD
https://github.com/orgs/geneontology/projects/91?card_filter_query=complex

But I don't see one for this particular issue.

We can of course still filter the annotations in the way @pgaudet describes, this is easy, but I think everything is simpler if the correct relations are used

**Comment by pgaudet** [comment]
Just a clarification about the semantics of the annotations: if we state in an entity is_a GO term, isn't that the definition of a mapping? 

It seems to me these are correctly being filtered out, as annotations?

**Comment by cmungall** [comment]
"mapping" is an underspecified term, but with sssom, mappings are typically
exact, broad, narrow, close, related.

**Comment by pgaudet** [comment]
This doesn't seem to be needed by users. We can reopen if we start getting requests.
