### ISSUE TITLE
resurrection of obsolete terms: GO:0016251

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#16568]
Using the example: GO:0016251

I know that reinstating obsoletions is rare, but for future reference, it is not good practice to unobsolete a class. A new ID should be created instead.

**Comment by pgaudet** [comment]
Hi @hattrill 
Can you explain your objection ? I un-obsoleted the term (and a few others) because we thought the meaning was OK, and the reason for obsoletion was not justified. 

Personally I find it very confusing when the same term exists as obsolete and non-obsolete, for example 
GO:0030528    obsolete transcription regulator activity
GO:0140110   transcription regulator activity

(perhaps this is mostly a display issue, and by default, obsolete should not be shown). 

Thanks, Pascale

**Comment by hattrill** [comment]
It's a tracking issue and a database thing. Once something is obsolete, then it shouldn't be used again, even if the name is identical. This term was dead for a long time, everyone anotating to the revived term may be doing it differently or in the light of new knowledge - it is, in effect, "new" - even if the definition hasn't changed. For instance, if someone has a decade-old annotation file, the contexual knowledge has changed and that annotation would need to be reviewed.

Some databases do not expect direct unobsoletions as it is not expected practice and will not deal with them coorectly.

**Comment by ukemi** [comment]
Adding editors' discuss to this because in the past I though we had decided to resurrect obsolete terms. I happened very infrequently. However, now that we are obsoleting so many terms I suspect it will be more common. The annotation points raised by @hattrill are interesting.

**Comment by deustp01** [comment]
For what it's worth, Reactome never un-obsoletes (though obsoletion is rare) but we also don't pay any attention to the history of instances in others' data so unobsoletion there would probably be handled correctly at our end, except that the humans who had manually replaced an obsolete GO term and who now needed to consider restoring the old one might be annoyed.

**Comment by ukemi** [comment]
Hi @hattrill. We discussed this a few weeks ago and decided that it was ok to resurrect the terms unless it is specifically breaking tools on your end. From a curation standpoint we decided it was less confusing for users to see a single term in the ontology rather than perhaps several examples of the same term string some of which are obsolete.

**Comment by hattrill** [comment]
We are set up to check this now, so we can deal with resurrections.

I will note that " However, now that we are obsoleting so many terms I suspect it will be more common" makes me a little unhappy - every time a term is obsoleted, we lose curated information - if we constantly flip-flop, then we just end up with patchy, incomplete annotation sets.

**Comment by pgaudet** [comment]
Are these so common ? I have probably resurrected 4-5 terms (maybe I am mis-remembering). 
Anyway, booth obsoletion and resurrection should be done very carefully.

**Comment by ValWood** [comment]
@hattrill, you shouldn't lose any information. Suggested terms should be equivalent or improved. Do you have egs where you lose info?

**Comment by hattrill** [comment]
What I am objecting to is that notion that the practice may become more common - the history of GO:0030528 obsolete transcription regulator activity shows the the "consider" is not always equivalent.
If an obsoleted term is resurrected, we are unlikely to go back and recurate all the re-housed annotations - or may be it should be a policy that we should reinstate the annotations as was prior to the obsoletion?

**Comment by pgaudet** [comment]
We'll document the procedure more clearly.

**Comment by pgaudet** [comment]
Hello, 

I've added a very short section here: 
http://wiki.geneontology.org/index.php/Principles_for_term_obsoletion

> In rare cases, obsolete GO terms may be restored, if the original meaning is conserved. In this case, an ID that had been obsolete at some point becomes a valid ID.

@ukemi @hattrill @vanaukenk 
Is that sufficient ? 

Thanks, Pascale

**Comment by hattrill** [comment]
That is sufficient for me - we've updated our pipeline to deal with this issue. 

It would be good if a similar notice that given for an obsoletion was sent round, as we might want to shift our prevously rehoused annotations.

**Comment by pgaudet** [comment]
Good point! I've added this to our procedure: http://wiki.geneontology.org/index.php/Restoring_an_Obsolete_Ontology_Term

Thanks !
