### ISSUE TITLE
positive regulation of GO:0042412 taurine biosynthetic process

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16562]
Hi

for the annotation of GHR please could I have this term
Ref PMID:18648510

I could just add the acts_upstream_of_positive_effect qualifier if that is more useful. Although I do wonder how analysis tools will 'group' data based on qualifiers

Thanks

Ruth

**Comment by ukemi** [comment]
If you know the mechanism, then the term is valid. I'll add it as long as you think that the GH pathway evolved to control the biosynthesis. I just wanted to double-check.

**Comment by RLovering** [comment]
Hi David

I have done a bit of digging and now I feel more confident that GHD should be associated with this term. I think the following paper PMID:24911144, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4071367/ is based on similar data to the paper I listed above.
However this paper has a nice figure (Fig 5J) included showing how the genes regulated by GHD and STAT are relevant to taurine synthesis, plus it is done by a different lab. Also there are other papers that describe the role of taurine in obesity, adipose tissue development, glucose and lipid metabolism, which all fit with the GHR role.
Do you think MGI would like to annotate this paper, or shall I do this once the term is created?

Best

Ruth

**Comment by ukemi** [comment]
Thanks Ruth,

I will add this as a definition reference. I checked and the paper is already in our curation stream. I'd like to try to use it in a GO-CAM model.

-David

**Comment by ukemi** [comment]
Ruth,

Which of your groups dbxrefs do you want me to add to this?

**Comment by RLovering** [comment]
Oh yes, I forgot about that, thanks for the reminder. definition_xref:GOC:BHF please
