### ISSUE TITLE
ntr: CMG & MCM complex processes

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16570]
id: GO:new1
name: CMG complex assembly
def: The aggregation, arrangement and bonding together of a set of components to form the CMG complex, a protein complex that contains the GINS complex, Cdc45p, and the heterohexameric MCM complex, and that is involved in unwinding DNA during replication. The process begins when additional proteins (e.g. Cdc45 and Sld3) join the loaded, inactive double MCM hexamer at replication origins, and ends when Mcm10 triggers the separation of the Mcm2-7 double hexamers, forming two active CMG complexes. [PMID:28501329, PMID:22718908]
is_a: GO:0022402 ! cell cycle process
is_a: GO:0065004 ! protein-DNA complex assembly
GO:1902315 ! nuclear cell cycle DNA replication initiation

id: GO:new2
name: MCM complex loading
def: The protein localization process in which two MCM complexes become associated with chromatin at replication origins. MCM loading begins when origin-bound ORC and Cdc6 (Cdc18 in fission yeast) recruit one MCM2-7/Cdt1 complex to the origin, includes formation of a succession of intermediate complexes and ATP hydrolysis-dependent Mcm2-7 ring closure, and ends when two MCM hexamers fully encircle DNA, and are oriented head-to-head. The double hexamer is inactive for DNA unwinding. MCM loading takes place during G1 phase, and precedes CMG complex assembly."
[MPDI:23603117, PMID:28191893, PMID:28191894, PMID:28501329]
synonym: "MCM complex loading at replication origin" EXACT [GOC:mah]
synonym: "MCM double hexamer formation at replication origin" EXACT [GOC:mah]
is_a: GO:0022402 ! cell cycle process
is_a: GO:0065004 ! protein-DNA complex assembly
GO:1902315 ! nuclear cell cycle DNA replication initiation

I don't know whether it's worth also adding terms for the various complexes formed as precursors or intermediates in either of these processes (e.g. OCCM, pre-LC; see figs 1 & 2 of PMID:28191893). It might spawn a mini-project that I don't have time to tackle!

**Comment by mah11** [comment]
any word on this?

**Comment by mah11** [comment]
at @pgaudet's invitation in the GO meeting, pinging my open tickets

**Comment by pgaudet** [comment]
Hi @mah11 Thanks for the reminder. 

CMG complex assembly -> sound like DNA is not an integral part of the complex ? I would rather have it simply under 'protein-containing complex' and the assembly term under 'protein-containing complex assembly'. Or the definitions should be changed. What do you think ?

**Comment by pgaudet** [comment]
Also for ' MCM complex loading' ->  according to your definition, would it not fir better under 'GO:0070727 cellular macromolecule localization' rather than 'protein-DNA complex assembly'? 

Thanks, Pascale

**Comment by mah11** [comment]
> CMG complex assembly -> sound like DNA is not an integral part of the complex 

This is not correct; CMG is a complex of proteins on DNA (some bind directly, and others indirectly by binding DNA-bound proteins), and never exists without the DNA. The portion of the definition that says "additional proteins ... join the loaded, inactive double MCM hexamer at replication origins" indicates this -- "loaded ... MCM" refers to an MCM double hexamer that has bound to DNA, and of course "replication origins" are DNA sequences.

I don't object if you want to change the def wording somehow, but I don't know exactly what to suggest.

> Also for ' MCM complex loading' -> according to your definition, would it not fir better under 'GO:0070727 cellular macromolecule localization' rather than 'protein-DNA complex assembly'?

Well, the definition explicitly states that the outcome of the loading process is that "two MCM hexamers fully encircle DNA". I can see how MCM loading could also fit "macromolecule localization", but I'm not convinced that localization fits *better* thas assembly. If MCM loading isn't protein-DNA complex assembly it's a challenge to think of anything that is. 

I'm trying, but failing, to remember why I put "protein localization process" in the text for one def but not the other ... in both processes some proteins get localized to where some others are already on DNA at origins, forming new protein-DNA complexes, so to me both processes would actually fit under both protein localization and complex assembly.

**Comment by mah11** [comment]
p.s. both should be part_of GO:1902315 ! nuclear cell cycle DNA replication initiation ... I just spotted that the part_of relation is missing from the stanzas

**Comment by pgaudet** [comment]
Here you go 

+[Term]
+id: GO:0140529
+name: CMG complex assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form the CMG complex, a protein complex that contains the GINS complex, Cdc45p, and the heterohexameric MCM complex, and that is involved in unwinding DNA during replication. The process begins when additional proteins (e.g. Cdc45 and Sld3) join the loaded, inactive double MCM hexamer at replication origins, and ends when Mcm10 triggers the separation of the Mcm2-7 double hexamers, forming two active CMG complexes." [PMID:22718908, PMID:28501329]
+is_a: GO:0022402 ! cell cycle process
+is_a: GO:0065004 ! protein-DNA complex assembly
+intersection_of: GO:0065004 ! protein-DNA complex assembly
+intersection_of: results_in_assembly_of GO:0071162 ! CMG complex
+relationship: part_of GO:1902315 ! nuclear cell cycle DNA replication initiation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16570 xsd:anyURI
+created_by: pg
+creation_date: 2020-10-12T16:42:17Z
+
+[Term]
+id: GO:0140530
+name: MCM complex loading
+namespace: biological_process
+def: "The protein localization process in which two MCM complexes become associated with chromatin at replication origins. MCM loading begins when origin-bound ORC and Cdc6 (Cdc18 in fission yeast) recruit one MCM2-7/Cdt1 complex to the origin, includes formation of a succession of intermediate complexes and ATP hydrolysis-dependent Mcm2-7 ring closure, and ends when two MCM hexamers fully encircle DNA, and are oriented head-to-head. The double hexamer is inactive for DNA unwinding. MCM loading takes place during G1 phase, and precedes CMG complex assembly." [] {comment="PMID:28501329", comment="PMID:28191894", comment="PMID:23603117", comment="PMID:28191893"}
+synonym: "MCM complex loading at replication origin" EXACT []
+synonym: "MCM double hexamer formation at replication origin" EXACT []
+is_a: GO:0022402 ! cell cycle process
+is_a: GO:0065004 ! protein-DNA complex assembly
+relationship: part_of GO:1902315 ! nuclear cell cycle DNA replication initiation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16570 xsd:anyURI
+created_by: pg
+creation_date: 2020-10-12T16:46:23Z

I'm not sure we need the intermediate complexes ? 

Thanks, Pascale

**Comment by mah11** [comment]
brilliant; thanks!

I have no immediate need for the intermediate complexes, and I really don't want to get sidetracked into trying to craft definitions for them!
