### ISSUE TITLE
New Term Request: 

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16573]
term: TIC complex associated chloroplast protein import motor
definition: protein complex located in the chloroplast inner membrane and facing the stroma that is associated with the chloroplast inner membrane translocase complex  (GO:0031897) and provides the ATPase motor activity to drive import of proteins into the chloroplast stroma.

suggested parentage:
part of : GO:0009706 chloroplast inner membrane
part of: GO:0031897 Tic complex

Reference: 
PMID:30309901

**Comment by bmeldal** [comment]
Comments: 

I'd call it "Ycf2/FtsHi complex", or at least add it as synonym.
Add "complex" to the end of the term names.

It is not part of the TIC complex but associated, so can't have that part_of relationship. 

Relationships:
is_a GO:1904949 ATPase complex (there is no term for AAA ATPase complex - do we need one?)
capable_of GO:0016887 ATPase activity
capable_of_part_of GO:0045037 protein import into chloroplast stroma

No Complex Portal ID yet, we don't have any plant complexes yet. Working on a future project though ;-)

Birgit

**Comment by ukemi** [comment]
I'll add the original requested name as a synonym, correct?

**Comment by ukemi** [comment]
I'm making it capable of motor activity. Let me know if this is wrong.

**Comment by bmeldal** [comment]
>I'm making it capable of motor activity. Let me know if this is wrong.

I guess that was additional to ATPase activity as they are in different branches.
