### ISSUE TITLE
New term request: cytoophidium organization

### ISSUE THREAD

**Issue by Kawatebi** [geneontology/go-ontology#16583]
Term: Regulation of cytoophidium organization

Definition: A process which results in the assembly, arrangement of constituent parts, or disassembly of cytoophidium

As a child of:
GO:0097435 supramolecular fiber organization

Source: Pubmed:25223282 Fig.3
"Taken together, these data suggest that DAck plays a role in nucleotide biosynthesis by modulating CTPS filament organization which ultimately promotes CTPS enzymatic activity."

**Comment by ValWood** [comment]
this should probably be
"cytoophidium organization" not "regulation of"

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140904
+name: cytoophidium organization
+namespace: biological_process
+def: "A process which results in the assembly, arrangement of constituent parts, or disassembly of a cytoophidium. Cytoophidia are mesoscale, intracellular, filamentous structures that contain metabolic enzymes." [PMID:25223282, PMID:27362644]
+is_a: GO:0097435 ! supramolecular fiber organization
+intersection_of: GO:0016043 ! cellular component organization
+intersection_of: results_in_organization_of GO:0097268 ! cytoophidium
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16583 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-26T08:55:10Z
