### ISSUE TITLE
New term request: Positive regulation of CTP biosynthetic process

### ISSUE THREAD

**Issue by Kawatebi** [geneontology/go-ontology#16584]
Term: Positive regulation of CTP biosynthetic process

Definition: Any process that increases the frequency, rate or extent of the chemical reactions and pathways resulting in the formation of CTP, cytidine 5'-triphosphate.

As a child of:
GO:0006241 CTP biosynthetic process

Source: Pubmed:25223282 Fig.3
"These results support the idea that maintenance of adequate CTP levels is promoted by DAck and is required for germ cell membrane integrity and oogenesis."

**Comment by ukemi** [comment]
Is this really tied to biosynthesis or is it just a measure of levels?

**Comment by hdrabkin** [comment]
I think the key here is ' DAck plays a role in nucleotide biosynthesis by modulating CTPS filament organization which ultimately promotes CTPS enzymatic activity. We are talking about the actual activity of the enzyme (CTPS) itself. The paper implies that DAck promotes assembly of CTPS into filaments which are enzymatically active but I'm not sure if non-filamentous CTPS is inactive, because:
Wiki: Active CTP synthase exists as a homotetrameric enzyme. At low enzyme concentrations and in the absence of ATP and UTP, CTP synthase exists as inactive monomer. 
on filamentation: 't filamentation downregulates or upregulates CTP synthase activity depending on the species.[ In Drosophila, only one of the CTP synthase isoform forms the filament.

A note from the wiki page: https://en.wikipedia.org/wiki/CTP_synthetase
indicates human CTPS activity can be downregulated by phosphorylation and GTP can allosterically regulate the activity. SO I'm convinced that CTP biosynthesis can be regulated in at least two ways, if not three..... 

What is not clear is

**Comment by pgaudet** [comment]
Can we say that it regulates the activity of the protein rather than that the process?

**Comment by hdrabkin** [comment]
That's exactly what is not clear from this paper anyways. Again, I'm in favor of the term in general based on the wiki statements, but the 'it" that is supposedly doing the regulating in the paper cited I'm not convinced should be annotated to the term if created. I would not use the PMID as a reference for the term (unless I'm missing something)

**Comment by pgaudet** [comment]
Hi @hdrabkin 

I don't think wikipedia and most of the literature uses the word regulation with the same meaning we do. In this case I think they refer to 'required for' (ie the formation of the filament is required for activity, but probably does't regulate the activity).

**Comment by hdrabkin** [comment]
I'm still not sure filament formation is required for the activity; maybe regulates, but again, that paper doesn't show -/+ activity, just that the filaments have the activity.
.

**Comment by pgaudet** [comment]
So, there doesn't seem to be enough evidence that this process exists (or that we know how it works) to create that term, IMHO.

**Comment by hdrabkin** [comment]
not based on the paper that is submitted by this ticket.  But there IS regulation of the final enzyme (CTPS) 
However, the papers involving effect of phosphorylation (PMID 15052328, PMID 17681942, PMID 20739275.) and allosteric binding shows two ways that CTP biosynthesis can be regulated by affecting the activity of the enzyme (PMID 18003612., PMC 2891682. PMID 16216072.. By regulating the enzyme activity do you not regulate the process of biosynthesis of CTP? 
So I agree that the process exists but NOT for use in the paper given with this ticket.(Pubmed:25223282 Fig.3)

**Comment by pgarmiri** [comment]
> 
> 
> I'm still not sure filament formation is required for the activity; maybe regulates, but again, that paper doesn't show -/+ activity, just that the filaments have the activity.
> .

Actually the authors of this paper (Pubmed:25223282) say that they did try to detect phosphorylation of CTPS by Ack (Supplementary Fig S5) but they were unable to see that and concluded that "DAck likely phosphorylates an as yet unidentified substrate that is essential for linking individual CTPS filaments into large, bundled, catalytically active assemblies". 

They did find that "a constitutively active mutant of CTPS spontaneously assembles into filaments supports the hypothesis that filaments are assembled for the purpose of nucleotide generation and that CTPS is catalytically active within them." Also, that "the active human enzyme assembled into filaments in the Drosophila ovary (Fig 4C) and rescued both the membrane integrity defects (Fig 4C) and the sterility of CTPSe/f female flies (Fig 4D). Based on these results, we conclude that Drosophila CTPS is likely catalytically active within filaments and that filament assembly promotes CTP synthesis."

Moveover, they found that total ovarian RNA levels were decreased in an inactive DAck mutant (DAck86)  flies compared to wild‐type flies, consistent with an important role of DAck in RNA production. Importantly, CTPSe/f (a reduced activity mutant) flies also exhibited reduced ovarian RNA levels, as expected, and this phenotype was rescued by transgenic expression of GFP‐CTPS1‐E161K (constitutively active mutant) (Fig 4F). Taken together, these data suggest that DAck plays a role in nucleotide biosynthesis by modulating CTPS filament organization which ultimately promotes CTPS enzymatic activity.

From what they say, modulating CTPS filament organization is not the only way of regulating the biosynthesis of CTP, but it promotes it.

**Comment by pgaudet** [comment]
Discussing with @hdrabkin  - DAck could perhaps be annotated to 'protein complex assembly', but there is no evidence that the assembly of the functional enzyme is a regulatory step in CTP biosynthesis. 

So, based on the papers discussed here, we decided not to create this term.
