### ISSUE TITLE
Curation Doubt on GO:0008656

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#16587]
Hi,
I have a curation doubt on GO:0008656 cysteine-type endopeptidase activator activity involved in apoptotic process: 
Definition: "Increases the rate of proteolysis catalyzed by a cysteine-type endopeptidase involved in the apoptotic process." 
Comments: "Examples of this are 1) granzymes that may bind to initiator caspases and cleave them, and 2) already active caspases, e.g. caspase 9, that cleave effector caspases."

I have a complex, called PIDDosome whose components are 7xCASP2:7xCRADD:5xPIDD1 and whose functions is to allow pairs of CASP2 subunits to self-cleave to release a processed and functional Caspase-2. I was wondering whether I can annotate this complex with the GO:0008656 function.
Thanks in advance
Kindest regards
Livia
@bmeldal

**Comment by bmeldal** [comment]
Thanks, David. It was actually I who had doubts. Should we add a further comment that self-activation is also applicable for this term?

Would you still co-annotate with the direct term 
GO:0097153 cysteine-type endopeptidase activity involved in apoptotic process?
I guess so.

**Comment by pgaudet** [comment]
Hi @bmeldal 

GO terms don't specify the substrate, only the gene product that mediates the activity. So acting on itself is fine. I can add something to the definition, but we cannot be exhaustive relative to possible substrates. I a little reluctant to add just because then, do we want to add this to all known cases ? (protein kinases seem a good example of this) 

What do you think ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
I was doubting if we did the right thing as the term has comments with examples that didn't quite fit the selfactivation situation; it mentions caspases that activate other caspases rather than themselves. Maybe I'm just too cautious. The PIDDosome is a bit of a nightmare to de-tangle, tbh.

**Comment by pgaudet** [comment]
@bmeldal @liviap Can you send the paper you are annotating ?

**Comment by ukemi** [comment]
I think self activation doesn't just hang on this term. I think it is generally applicable as legitimate MF. @vanaukenk, @thomaspd  and @pgaudet do you agree in light of the MF refactoring? Should this be moved to the annotation tracker? It seems like more an annotation practice question than an ontology question.

**Comment by bmeldal** [comment]
I think it's in this paper: PMID:15073321

Yes, should be in Annotation tracker.

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-annotation#2133
