### ISSUE TITLE
missing parent : fungal-type cell wall (1->3)-alpha-glucan biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16594]
does not have
GO:0051278   fungal-type cell wall polysaccharide biosynthetic process

we probably don't need all of these terms, but since we have them the parentage should be corrected.

**Comment by ValWood** [comment]
correction
fungal-type cell wall (1->3)-alpha-glucan biosynthetic process

but hte metabolic parents are likely  missing too

**Comment by ValWood** [comment]
need equivalent 
fungal-type cell wall (1->4)-alpha-glucan biosynthetic process

**Comment by ValWood** [comment]
also need

GO:0060624    regulation of fungal-type cell wall  (1->3)-beta-D-glucan biosynthetic process

in between
GO:0060624    regulation of ascospore wall (1->3)-beta-D-glucan biosynthetic process
and
regulation of cell  wall (1->3)-beta-D-glucan biosynthetic process

**Comment by ValWood** [comment]
Actually the regulation terms are  even dafter......

The same pathways probably regulate the entire synthesis, they aren't regulating the different synthase activities independently.

Unless anyone knows differently they should all be
regulation of 
GO:0051278   fungal-type cell wall polysaccharide biosynthetic process

**Comment by ukemi** [comment]
I'm going to make an attempt at doing all this through the reasoner by logically defining these terms to be the generic process and having the participants of each of the appropriate types of cell walls. I don't see any reason why these won't be necessary and sufficient.

**Comment by ukemi** [comment]
Alright. This was harder than I thought, but the PR is here:

https://github.com/geneontology/go-ontology/pull/16600

Lets give it  a few days to percolate through and then close this if everything looks ok. I ran into the 'cellular' issue that was causing mis-classification, but think I cleaned it all up.

**Comment by ukemi** [comment]
Hi Val. Can we close this one?

**Comment by ValWood** [comment]
I think so...
