### ISSUE TITLE
GO:0033573 query term not accessible due to  taxon constraints  via owltools

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16595]
GO:0033573 | high-affinity iron permease complex

has something happened to this term? It was used in the curation session I just opened. I can't reapprove it because I am told this term is no longer in the database. Oddly I can see it in QuickGO?

@mah11  curs/3a2dde8117141243

**Comment by ValWood** [comment]
I'll check this isn't a problem at our end first...

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1669
Summary:

@kimrutherford  says
I run owltools manually to make a pombe-only OBO and that term is definitely removed by the taxon constraints.

One of the parent terms is bacteria only:
GO:0015092 high-affinity ferric iron transmembrane transporter activity

It's not an is_a relation (it's "capable of") so I don't know if that would be enough to filter out your term GO:0033573.

.....We're using go-plus.owl and processing it with owltools.

@cmungall  who should be assigned?

**Comment by cmungall** [comment]
Nice catch, this is an ontology issue, see:

![image](https://user-images.githubusercontent.com/50745/48233064-b3f3bf80-e368-11e8-865a-7221b32a150d.png)

There is an error in the part_of

```
id: GO:0015092
name: high-affinity ferric iron transmembrane transporter activity
namespace: molecular_function
def: "Enables the transfer of ferric iron (Fe(III) or Fe3+) ions from one side of a membrane to the other. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:ai, PMID:1447137]
comment: https://github.com/geneontology/go-ontology/issues/14372
synonym: "high affinity ferric uptake transmembrane transporter activity" RELATED []
is_a: GO:0015091 ! ferric iron transmembrane transporter activity
***relationship: part_of GO:0098706 ! iron ion import across cell >>>>outer<<<< membrane
```

assigning @pgaudet randomly as I think she was working on transport most recently

**Comment by cmungall** [comment]
@balhoff would be awesome to have more direct feedback about inferred TC in Protege

**Comment by ValWood** [comment]
any chance to fix this. we can't re-approve the sessions until the term is available again.

cheers

val

**Comment by ukemi** [comment]
I think both the complex and the function should relate to the plasma membrane, not the outer membrane. I will fix this.
