### ISSUE TITLE
regulation of DNA topoisomerase activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16598]
Hi

please could the following term be created:
GO:0003916 DNA topoisomerase activity
> new regulation child term: regulation of DNA topoisomerase activity
Definition: Any process that modulates the frequency, rate or extent of DNA topoisomerase activity. 
>> is_a child term: positive regulation of DNA topoisomerase activity
Definition: Any process that activates or increases the frequency, rate or extent of DNA topoisomerase activity. 
>>>is_a DNA topoisomerase activator activity
Definition: Binds to and increases the activity of DNA topoisomerase.  
For the annotation of human ABL P00519 based on PMID:9558345 Figure 10B. Plus ABL and TOP1 directly interact based on https://www.uniprot.org/uniprot/P11387#interaction 

Note that the following terms are child terms to  GO:0003918 
DNA topoisomerase type II (ATP-hydrolyzing) activity and should be added as child terms to the terms requested above as appropriate:

GO:0072586                DNA topoisomerase (ATP-hydrolyzing) regulator activity | regulates
GO:2000371                regulation of DNA topoisomerase (ATP-hydrolyzing) activity | regulates
GO:0008657                DNA topoisomerase (ATP-hydrolyzing) inhibitor activity | negatively_regulates
GO:2000373                positive regulation of DNA topoisomerase (ATP-hydrolyzing) activity | positively_regulates
GO:0072587                DNA topoisomerase (ATP-hydrolyzing) activator activity | positively_regulates

Thanks

Ruth
dbxREF: GOC:rl
dbxREF: GOC:aruk

**Comment by pgaudet** [comment]
Hi @RLovering 

Trying to address this ticket - I only have access to the abstract of PMID:9558345, which states "(Abl) potentiates the DNA relaxation activity of topoisomerase I. These findings indicate that the interaction of c-Abl with DNA is both sequence-selective and structure-dependent. "

It seems Abl may participates in unwinding together with DNA topoisomerase? (but impossible to tell without looking at the paper).

**Comment by ValWood** [comment]
This might not be set in stone but I thought we were trying to phase out the use of "regulation of MFR terms" in BP (i.e. if you cannot  say  a gene product is a MF regulator, the really its 'causally upstream' of the process).

**Comment by RLovering** [comment]
Hi Val

yes this ticket has been open for too long and evolution has overtaken it, closing now ;)

Best

Ruth
