### ISSUE TITLE
Two has participant relations

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#16602]
This morning while working on the cell wall metabolism areas of GO I noticed that we have two has participant relations. One, 'has participant', is the one we have traditionally used and the other, has_participant, directly refers to a BFO term and comes in via the PO import. Of course I used the non-traditional one at first for all my edits and the obo file looked weird. 

Is this problematic and should we somehow filter the one used in PO?

**Comment by balhoff** [comment]
My guess is that this is an accident of history in PO, and we could probably get them to replace the IRI with the RO one. They both have the same numeric ID.

**Comment by ukemi** [comment]
@tberardini can you request this?

**Comment by balhoff** [comment]
I also meant to say—the BFO-namespaced `has_participant` and `participates_in` don't exist in RO. I did notice that PO has a property chain `part_of o participates_in -> participates_in`. I don't see this on `RO:participates in`. So if PO asserts this chain for `RO:participates in`, it may impact GO.

**Comment by ukemi** [comment]
Considering the generality of participates in, it seems that this property chain is valid, but you are correct. If PO makes this change, we will now create these inferences.

**Comment by cmungall** [comment]
Removed the chain on the PR. I think it's actually valid (for the generic has-participant, which may not be what GO ultimately needs) and thought we had it in RO. But in anycase, no one should inject into RO

**Comment by tberardini** [comment]
@cooperl09 Linking this GO issue to the PO one.
https://github.com/Planteome/plant-ontology/issues/689

**Comment by pgaudet** [comment]
Can this be closed ? @cmungall @balhoff

**Comment by balhoff** [comment]
I think PO issue is resolved. We still seem to have an extra BFO-namespaced 'participates in' coming from the Uberon import. I opened a PR: https://github.com/obophenotype/uberon/pull/1521

We'll need to wait for an Uberon release.

**Comment by balhoff** [comment]
This is fixed in Uberon now. It will resolve itself next time Uberon has a release.
