### ISSUE TITLE
NTR: flagellum attachment zone organization

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#16607]
Accession: GO:xxxxxx
Name: flagellum attachment zone organization
Ontology: biological_process
Synonyms: FAZ organization, flagellum attachment zone organisation
Definition: A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a flagellum attachment zone. FAZ is a network of cytoskeletal and membranous connections responsible for the lateral attachment of the cilium to the cell body in some trypanosomatid species.
is_a: GO:0006996 ! organelle organization
Source: GO:0120119, PMID:26776656

**Comment by Achchuthan** [comment]
Hi @vanaukenk,

Wondering whether you had any chance to look at this term?

Thanks,
Achchuthan

**Comment by vanaukenk** [comment]
@Achchuthan - the term has now been added and should be available for use in the next ontology release.
