### ISSUE TITLE
NTR: Calcium-Dependent Negative Regulation of Dopamine Secretion 

### ISSUE THREAD

**Issue by mayursst** [geneontology/go-ontology#16609]
This is for CACAO class @sandyl27 @jrr-cpt @jimhu-tamu

**Potential GoTerm Name**: Calcium-Dependent Negative Regulation of Dopamine Secretion 
**Definition**: Any process that stops, prevents, or reduces the frequency, rate of extent of the regulated release of dopamine in a calcium dependent manner. 
**Aspect**: Biological Process
**Relationships**: Child term of 'negative regulation of dopamine secretion (G0:0033602)'  OR
Suggested parent term — 'Calcium-Dependent Regulation of Dopamine Secretion';
Suggested Sibling Terms — 'Calcium-Dependent Positive Regulation of Dopamine Secretion'
**References** — PMID:28370453, See Figure 5
**Synonyms** — 'Calcium-dependent down-regulation of dopamine secretion'
'Calcium-dependent down regulation of dopamine secretion'
'Calcium-dependent inhibition of dopamine secretion'
'Calcium-dependent down-regulation of dopamine release'

**Comment by pgaudet** [comment]
Probably out of date
