### ISSUE TITLE
dsDNA loop formation is_a chromatin remodelling?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16603]
dsDNA loop formation (The formation and maintenance of DNA loops that juxtapose separated regions on the same dsDNA molecule)  
is_a chromosome organization

but should it be
is_a chromatin remodelling?
(Dynamic structural changes to eukaryotic chromatin occurring throughout the cell division cycle. These changes range from the local changes necessary for transcriptional regulation to global changes necessary for chromosome segregation.)

all annotations to this term are for eukaryotes

**Comment by Antonialock** [comment]
Promoter-enhancer looping is also chromatin remodelling? 

I don’t know much about dna loops...are there other types?

**Comment by ValWood** [comment]
Ok yes I want really think of any  ds ones that aren't....

**Comment by Antonialock** [comment]
So it looks like prokaryotes also loop their DNA...

if all eukaryotic dsDNA looping is chromatin remodelling though it would be nice if this was reflected in the parentage? 

(I actually annotated to Promoter-enhancer looping....I'd be happy if just this term had the chromatin remodelling parent if we're not sure about all dsDNA loops)

**Comment by ukemi** [comment]
But presumably this term is meant to cover both eukaryotes and prokaryotes. That's probably why it didn't have the chromatin parent.

**Comment by Antonialock** [comment]
So what's the best thing to do here? co-annotating to chromatin remodelling seems a bit clunky?

**Comment by ukemi** [comment]
Other than creating a term that encompasses both, co-annotation is the option that I would suggest.

**Comment by Antonialock** [comment]
I think process. I don't know how it works in "all cases" but in the example I looked at the process went something like this
- TF-X binds promoter 1 
- Starvation signal to transcribe the gene
- TF-Y binds promoter 2, and nucleosome eviction between promoter 1 and 2
- DNA loop formed between promoter 1 and 2

**Comment by Antonialock** [comment]
(there were some other players involved, that's just broadly how it went from memory)

**Comment by Antonialock** [comment]
cheers I will request chromatin looping
