### ISSUE TITLE
signaling pattern recognition receptor activity disambiguation and true path violations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16616]
defined
GO:0008329  signaling pattern recognition receptor activity
Combining with a pathogen-associated molecular pattern (PAMP), a structure conserved among microbial species, or damage-associated molecular pattern (DAMP), an endogenous molecule released from damaged cells), and transmitting a signal to initiate a change in cell activity.

this is clearly the term for a PAMP receptor, when a host receptor binds to a pathogen cell surface molecule  called a PAMP

However, it has children that are  NOT specific to PAMPs
lipoarabinomannan receptor activity  
lipopolysaccharide receptor activity  
lipoteichoic acid receptor activity  
peptidoglycan receptor activity  
polysaccharide receptor activity  

or at least not defined as being specific for PAMPS....

**Comment by ValWood** [comment]
Suggest, in addition to fixing the  descendants, 
renaming this 
"pathogen-associated molecular pattern receptor activity"
so that it cannot be misused.

**Comment by ukemi** [comment]
@addiehl  Could you have a look at this one too? Thanks!!

**Comment by addiehl** [comment]
will do

**Comment by ValWood** [comment]
Thanks Alex, no hurry for this. I found enough bugs  in the tool not need to pursue testing for a while.  
Id also  be interested whether you know about the location of these. According to this plant paper, PMID:20601497

I think that the pathogenic fungi that is recognised by the   "pattern recognition receptor" is recognising the  cell surface of the pathogen (a fungi) , but it is inside the host (plant leaf cell). I don't think it's a cell surface receptor but I could be wrong.....

**Comment by hattrill** [comment]
Agree with @ValWood suggestion of renaming/defining term to "pathogen-associated molecular pattern receptor activity".
We have also been looking at the pattern recognition pathway process terms, which we think could do with some revision along the same lines, and some rewiring. We are thinking about them wrt to Drosophila - which I need to discuss with the rest of our group next week.

**Comment by hattrill** [comment]
See you've openned a discussion on pathways here #16615

**Comment by ValWood** [comment]
Yes, I got a bit lost down there to be honest, it isn't very consistent with how we are supposed to annotate pathways. You could describe everything in about 20  different ways!

**Comment by ValWood** [comment]
Good point. Ant suggestions?

I worry about "molecular pattern recognition receptor"
because "molecular pattern" is a bit vague  (although I guess this could be covered in the def?).

Or, separate DAMP and PAMP receptors?  

Or  just use "signalling receptor activity"

Since the type will become obvious from "has_input" and part_of connection to the process.

**Comment by ValWood** [comment]
@ukemi 
@pgaudet 
thoughts how best to do this?

**Comment by hattrill** [comment]
Perhaps it would be good to separate out PAMPs and DAMPs - think that it would be a shame to lose them from the GO, as there is a lot of interest in these types of activities wrt disease. For DAMPs, the has_input won't make it obvious as these can be things like mtDNA fragments.

**Comment by deustp01** [comment]
Listening to immunologist colleagues talk, I get the impression that the "molecular pattern" terminology arises because they want their own distinctive way of describing the behavior  of a receptor (TOLL or other) with a broad and incompletely described specificity for ligands. And the DAMP - PAMP distinction is at least in part a way of specifying what the ultimate result of receptor activation will be: innate responses to set off a full immune reaction to a pathogen, or innate responses that lead to autoimmunity. At the level of describing the molecular details of a receptor:ligand interaction, this distinction may be out of scope. But a real cellular immunologist should jump in here; I'm pout of date and guessing to fill in gaps. You might ask Ludovic.Desvignes@nyulangone.org .

**Comment by ValWood** [comment]
That's a nice summary of expectations.

Maybe we  should do this by

signalling receptor activity  part_of GO:0080185 effector dependent induction by symbiont of host immune response (or whatever).


I'm happy to go either way.....

**Comment by ValWood** [comment]
Note that GO:0038187 is not currently positioned under "innate immune receptor"

**Comment by ValWood** [comment]
out of date
