### ISSUE TITLE
Review property axioms found in GO-plus but not in RO

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#16618]
Here is a listing of property axioms in GO-plus, or one of its imports, which are not found in RO as of 2018-11-14. I filtered some out of the Uberon import which were BSPO or Uberon-local properties. Perhaps we can review by either checking off (if we need to find a way to keep it) or ~striking through~ (if we can ditch) each axiom.

## `http://purl.obolibrary.org/obo/go/extensions/go-plus.owl`

- [ ] [regulates](http://purl.obolibrary.org/obo/RO_0002211) SubPropertyOf: [causally related to](http://purl.obolibrary.org/obo/RO_0002410) _—redundant with chain of subproperties in RO_
- [x] [regulates](http://purl.obolibrary.org/obo/RO_0002211) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [regulates](http://purl.obolibrary.org/obo/RO_0002211)
- [x] [positively regulates](http://purl.obolibrary.org/obo/RO_0002213) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [positively regulates](http://purl.obolibrary.org/obo/RO_0002213)
- [x] [negatively regulates](http://purl.obolibrary.org/obo/RO_0002212) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [negatively regulates](http://purl.obolibrary.org/obo/RO_0002212)
- [x] [develops_from](http://purl.obolibrary.org/obo/RO_0002202) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [develops_from](http://purl.obolibrary.org/obo/RO_0002202)
- [x] [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [develops_from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [develops_from](http://purl.obolibrary.org/obo/RO_0002202)
- [ ] [has application](http://purl.obolibrary.org/obo/GOCHEREL_0000002) SubPropertyOf: [has role](http://purl.obolibrary.org/obo/RO_0000087) _—not used in any axioms_
- [ ] [has_chemical_role](http://purl.obolibrary.org/obo/GOCHEREL_0000004) SubPropertyOf: [has role](http://purl.obolibrary.org/obo/RO_0000087)  _—not used in any axioms_
- [ ] [has_biological_role](http://purl.obolibrary.org/obo/GOCHEREL_0000003) SubPropertyOf: [has role](http://purl.obolibrary.org/obo/RO_0000087)  _—not used in any axioms_
- [ ]  Transitive: [derives from](http://purl.obolibrary.org/obo/RO_0001000) _—not used in any axioms (nor any related properties)_
- [ ] [acts_on_population_of](http://purl.obolibrary.org/obo/GOREL_0001006) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [mediated_by](http://purl.obolibrary.org/obo/GOREL_0001007) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results in acquisition of features of](http://purl.obolibrary.org/obo/RO_0002315) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results in development of](http://purl.obolibrary.org/obo/RO_0002296) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results_in_division_of](http://purl.obolibrary.org/obo/GOREL_0001019) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_fission_of](http://purl.obolibrary.org/obo/GOREL_0002004) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_fusion_of](http://purl.obolibrary.org/obo/GOREL_0002005) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results in growth of](http://purl.obolibrary.org/obo/RO_0002343) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results in maturation of](http://purl.obolibrary.org/obo/RO_0002299) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results in morphogenesis of](http://purl.obolibrary.org/obo/RO_0002298) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results in movement of](http://purl.obolibrary.org/obo/RO_0002565) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results in structural organization of](http://purl.obolibrary.org/obo/RO_0002355) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results_in_transport_to_from_or_mediated_by](http://purl.obolibrary.org/obo/GOREL_0002010) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057) _—redundant with chain of subproperties in RO_
- [ ] [results_in_maintenance_of](http://purl.obolibrary.org/obo/GOREL_0012006) SubPropertyOf: [results_in_organization_of](http://purl.obolibrary.org/obo/RO_0002592)
- [ ] [causally upstream of](http://purl.obolibrary.org/obo/RO_0002411) SubPropertyOf: [causally related to](http://purl.obolibrary.org/obo/RO_0002410)  _—redundant with chain of subproperties in RO_

- [ ] [causally upstream of or within](http://purl.obolibrary.org/obo/RO_0002418) SubPropertyOf: [causally related to](http://purl.obolibrary.org/obo/RO_0002410)  _—redundant with chain of subproperties in RO_
- [ ] [causally downstream of](http://purl.obolibrary.org/obo/RO_0002404) SubPropertyOf: [causally related to](http://purl.obolibrary.org/obo/RO_0002410)  _—redundant with chain of subproperties in RO_
- [ ] [causally downstream of or within](http://purl.obolibrary.org/obo/RO_0002427) SubPropertyOf: [causally related to](http://purl.obolibrary.org/obo/RO_0002410)  _—redundant with chain of subproperties in RO_
- [ ] [regulated by](http://purl.obolibrary.org/obo/RO_0002334) SubPropertyOf: [causally related to](http://purl.obolibrary.org/obo/RO_0002410)  _—redundant with chain of subproperties in RO_
- [ ] [causally related to](http://purl.obolibrary.org/obo/RO_0002410) SubPropertyOf: [related via dependence to](http://purl.obolibrary.org/obo/RO_0002609)  _—superproperty is obsolete_
- [ ] [regulates](http://purl.obolibrary.org/obo/RO_0002211) SubPropertyOf: [causally upstream of or within](http://purl.obolibrary.org/obo/RO_0002418)  _—redundant with chain of subproperties in RO_
- [ ] [capable of regulating](http://purl.obolibrary.org/obo/RO_0002596) SubPropertyOf: [causal relation between material entity and a process](http://purl.obolibrary.org/obo/RO_0002595) _—redundant with chain of subproperties in RO_
- [ ] [capable of part of](http://purl.obolibrary.org/obo/RO_0002216) SubPropertyOf: [causal relation between material entity and a process](http://purl.obolibrary.org/obo/RO_0002595) _—redundant with chain of subproperties in RO_
- [ ] [capable of](http://purl.obolibrary.org/obo/RO_0002215) SubPropertyOf: [causal relation between material entity and a process](http://purl.obolibrary.org/obo/RO_0002595) _—redundant with chain of subproperties in RO_
- [ ] [capable of](http://purl.obolibrary.org/obo/RO_0002215) SubPropertyOf: [functionally related to](http://purl.obolibrary.org/obo/RO_0002328) _—redundant with chain of subproperties in RO_
- [x] [regulates](http://purl.obolibrary.org/obo/RO_0002211) SubPropertyOf: [functionally related to](http://purl.obolibrary.org/obo/RO_0002328)
- [x] [regulated by](http://purl.obolibrary.org/obo/RO_0002334) SubPropertyOf: [functionally related to](http://purl.obolibrary.org/obo/RO_0002328)
- [ ] [is symbiosis](http://purl.obolibrary.org/obo/RO_0002465) SubPropertyOf: [helper property](http://purl.obolibrary.org/obo/RO_0002464) _—redundant with chain of subproperties in RO_
- [ ] [is ubiquitination](http://purl.obolibrary.org/obo/RO_0002482) SubPropertyOf: [helper property](http://purl.obolibrary.org/obo/RO_0002464) _—redundant with chain of subproperties in RO_
- [ ] [is kinase activity](http://purl.obolibrary.org/obo/RO_0002481) SubPropertyOf: [helper property](http://purl.obolibrary.org/obo/RO_0002464) _—redundant with chain of subproperties in RO_
- [x] [indirectly activates](http://purl.obolibrary.org/obo/RO_0002407) o [directly positively regulates](http://purl.obolibrary.org/obo/RO_0002629) SubPropertyOf: [indirectly activates](http://purl.obolibrary.org/obo/RO_0002407) _—RO is more specific_
- [x] [indirectly inhibits](http://purl.obolibrary.org/obo/RO_0002409) o [directly negatively regulates](http://purl.obolibrary.org/obo/RO_0002630) SubPropertyOf: [indirectly inhibits](http://purl.obolibrary.org/obo/RO_0002409) _—RO is more specific_
- [ ] [imports](http://purl.obolibrary.org/obo/RO_0002340) SubPropertyOf: [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) _—redundant with chain of subproperties in RO_
- [ ] [exports](http://purl.obolibrary.org/obo/RO_0002345) SubPropertyOf: [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) _—redundant with chain of subproperties in RO_
- [x] [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [occurs in](http://purl.obolibrary.org/obo/BFO_0000066)

## `http://purl.obolibrary.org/obo/go/extensions/ro_pending.owl`

- [ ] [acts_on_population_of](http://purl.obolibrary.org/obo/GOREL_0001006) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_transport_through](http://purl.obolibrary.org/obo/go/extensions/ro_pending#results_in_transport_through) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_remodeling_of](http://purl.obolibrary.org/obo/GOREL_0002007) SubPropertyOf: [results_in_organization_of](http://purl.obolibrary.org/obo/GOREL_0002006)
- [ ] [alters location of](http://purl.obolibrary.org/obo/go/extensions/ro_pending#alters_location_of) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_division_of](http://purl.obolibrary.org/obo/GOREL_0001019) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_assembly_of](http://purl.obolibrary.org/obo/GOREL_0002001) SubPropertyOf: [results_in_organization_of](http://purl.obolibrary.org/obo/GOREL_0002006)
- [ ] [mediated_by](http://purl.obolibrary.org/obo/GOREL_0001007) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
- [ ] [results_in_disassembly_of](http://purl.obolibrary.org/obo/GOREL_0002002) SubPropertyOf: [results_in_organization_of](http://purl.obolibrary.org/obo/GOREL_0002006)
- [ ] [results_in_maintenance_of](http://purl.obolibrary.org/obo/GOREL_0012006) SubPropertyOf: [results_in_organization_of](http://purl.obolibrary.org/obo/GOREL_0002006)
- [ ] [results_in_transport_to_from_or_mediated_by](http://purl.obolibrary.org/obo/GOREL_0002010) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)

## `http://purl.obolibrary.org/obo/go/imports/po_import.owl`

- [ ] [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [participates_in](http://purl.obolibrary.org/obo/BFO_0000056) SubPropertyOf: [participates_in](http://purl.obolibrary.org/obo/BFO_0000056)
- [ ] [participates_in](http://purl.obolibrary.org/obo/BFO_0000056) InverseOf [has_participant](http://purl.obolibrary.org/obo/BFO_0000057)

## `http://purl.obolibrary.org/obo/go/imports/uberon_import.owl`

- [ ] [simultaneous_with](http://purl.obolibrary.org/obo/RO_0002082) SubPropertyOf: [starts](http://purl.obolibrary.org/obo/RO_0002223)
- [ ] [develops_from](http://purl.obolibrary.org/obo/RO_0002202) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [develops_from](http://purl.obolibrary.org/obo/RO_0002202)
- [ ] [connects](http://purl.obolibrary.org/obo/RO_0002176) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ]  Transitive: [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254)
- [ ] [attaches_to](http://purl.obolibrary.org/obo/RO_0002371) SubPropertyOf: [connects](http://purl.obolibrary.org/obo/RO_0002176)
- [ ] [developmentally_induced_by](http://purl.obolibrary.org/obo/RO_0002256) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ]  Symmetric: [continuous_with](http://purl.obolibrary.org/obo/RO_0002150)
- [ ] [luminal space of](http://purl.obolibrary.org/obo/RO_0002572) SubPropertyOf: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
- [ ] [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [develops_from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [develops_from](http://purl.obolibrary.org/obo/RO_0002202)
- [ ] [capable of](http://purl.obolibrary.org/obo/RO_0002215) SubPropertyOf: [functionally related to](http://purl.obolibrary.org/obo/RO_0002328)
- [ ] [has skeleton](http://purl.obolibrary.org/obo/RO_0002551) Domain [organism subdivision](http://purl.obolibrary.org/obo/UBERON_0000475)
- [ ] [supplies](http://purl.obolibrary.org/obo/RO_0002178) Domain [artery](http://purl.obolibrary.org/obo/UBERON_0001637)
- [ ] [simultaneous_with](http://purl.obolibrary.org/obo/RO_0002082) SubPropertyOf: [ends](http://purl.obolibrary.org/obo/RO_0002229)
- [ ] [existence ends with](http://purl.obolibrary.org/obo/RO_0002493) Range [life cycle stage](http://purl.obolibrary.org/obo/UBERON_0000105)
- [ ]  Symmetric: [adjacent_to](http://purl.obolibrary.org/obo/RO_0002220)
- [ ] [supplies](http://purl.obolibrary.org/obo/RO_0002178) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [attaches_to](http://purl.obolibrary.org/obo/RO_0002371) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [innervated_by](http://purl.obolibrary.org/obo/RO_0002005) o [branching_part_of](http://purl.obolibrary.org/obo/RO_0002380) SubPropertyOf: [innervated_by](http://purl.obolibrary.org/obo/RO_0002005)
- [ ] [produced by](http://purl.obolibrary.org/obo/RO_0003001) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ]  Transitive: [has branching part](http://purl.obolibrary.org/obo/RO_0002569)
- [ ] [produces](http://purl.obolibrary.org/obo/RO_0003000) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [existence starts with](http://purl.obolibrary.org/obo/RO_0002489) Domain [anatomical entity](http://purl.obolibrary.org/obo/UBERON_0001062)
- [ ] [continuous_with](http://purl.obolibrary.org/obo/RO_0002150) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [existence starts during](http://purl.obolibrary.org/obo/RO_0002488) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [existence starts with](http://purl.obolibrary.org/obo/RO_0002489) Range [life cycle stage](http://purl.obolibrary.org/obo/UBERON_0000105)
- [ ] [drains](http://purl.obolibrary.org/obo/RO_0002179) Domain [vein](http://purl.obolibrary.org/obo/UBERON_0001638)
- [ ] [connected to](http://purl.obolibrary.org/obo/RO_0002170) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [develops_from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254)
- [ ] [existence ends with](http://purl.obolibrary.org/obo/RO_0002493) Domain [anatomical entity](http://purl.obolibrary.org/obo/UBERON_0001062)
- [ ] [innervated_by](http://purl.obolibrary.org/obo/RO_0002005) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [has skeleton](http://purl.obolibrary.org/obo/RO_0002551) Range [subdivision of skeleton](http://purl.obolibrary.org/obo/UBERON_0010912)
- [ ] [existence ends during](http://purl.obolibrary.org/obo/RO_0002492) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [ ] [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

**Comment by ukemi** [comment]
I'm a bit shocked there are so many.

**Comment by ukemi** [comment]
Hi @balhoff. I'm a bit confused by the report. When I look at regulates in RO, it is asserted as a subproperty of 'causally upstream of or within'. 'capable of' is a grandchild of 'functionally related to'.

**Comment by balhoff** [comment]
@ukemi these are just the actual assertions in each file—it doesn’t do any inference. If one of these can be found to be redundant with something more specific in RO, then we don’t need it here and we can strike it.

**Comment by ukemi** [comment]
Got it!

**Comment by balhoff** [comment]
I deleted the `ro_import` list, since we can just fix that by rebuilding the import. The Uberon ones should really be looked at in the Uberon project, but they may be informational here in case they're providing some inference GO is using.

**Comment by ukemi** [comment]
We really need to get rid of regulates o part of SubPropertyOf: regulates, but we should do it after we assert all of the current inferences generated by it. Most of them, if not all, are probably correct, but going forward with GO-CAM this one will create big problems.

**Comment by balhoff** [comment]
After #16647, the only (logical) property axioms remaining in go-edit are the above "injected" axioms that aren't in RO.

**Comment by balhoff** [comment]
Since this is much cleaned up now, I'll close this issue. There are a few remaining property axioms in go-edit, but they are easier to spot now since the redundant ones have been removed.
