### ISSUE TITLE
GO:0002221    pattern recognition receptor signaling pathway (pathogen host interaction)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16615]
I'm testing our pathogen-host  implementation of Canto. In addition to capturing pathogen host interaction phenotypes, we will also be able to make GO annotations, so I'll probably be suggesting/requesting things in this area.

There are numerous problems with this term:
GO:0002221    pattern recognition receptor signaling pathway
Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands. PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species, or damage-associated molecular pattern (DAMPs), endogenous molecules released from damaged cells. PMID:15199967

This is a term to describe the pathway activated by  the recognition of a pathogen cell surface molecule Pattern recognition receptor or PAMP.

However I could also use *any* of the sibling terms to describe this pathway:
GO:0002220    innate immune response activating cell surface receptor signaling pathway | 
GO:0035421    activation of MAPKK activity involved in innate immune response 
GO:0035419    activation of MAPK activity involved in innate immune response 
GO:0035422    activation of MAPKKK activity involved in innate immune response
(I think these MAPK specific terms should have been removed as part of the signallinf overhaul?)

I could also use a number  of the children of GO:0002221
GO:0002224    toll-like receptor signaling pathway |
GO:0002752    cell surface pattern recognition receptor signaling pathway | 

the receptor is simultaneously : 
"toll-like"  
"regognises a pathogen cell surface pattern" (its a pathogen inside the host  cell, but its a cell surface molecule  ON the pathogen that is being recognised"

This is the usual issue of too many orthoganal axis of classification. The main problem appears to be using the "receptor type" to define the GO signalling term.

I guess I'm going to use 
GO:0002221    pattern recognition receptor signaling pathway
but 

GO:0002221    pattern recognition receptor signaling pathway
definitly is a
GO:0002220    innate immune response activating cell surface receptor signaling pathway

and this really seems to be a better term.

Should  at least some of these terms be merged?

**Comment by ukemi** [comment]
@addiehl  could you please have a look at this?

**Comment by addiehl** [comment]
I will.  Give me a couple of days as I am out of town at the moment.

**Comment by ValWood** [comment]
replaced by
https://github.com/geneontology/go-ontology/issues/18588
