### ISSUE TITLE
NTR GBAF complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16624]
A SWI/SNF subcomplex that incorporates two mutually exclusive paralogs, GLTSCR1 (glioma tumor suppressor candidate region gene 1) or GLTSCR1L (GLTSCR1-like), BRD9 (bromodomain-containing 9) and the BAF subunits BAF155, BAF60, SS18, BAF53a, and BRG1/BRM. 

child of GO:0070603

PMID:29374058

**Comment by pgaudet** [comment]
@bmeldal Any comments on this?

**Comment by bmeldal** [comment]
Ah, I looked at that one and marked it for curation! I did the BAF family last year (what a pain it was!) but this is a new one and looks good :)
