### ISSUE TITLE
NTR Nicalin-NOMO complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16627]
synonym Nodal modulator complex

A protein complex regulating Nodal signaling. Subunits include Nicalin, NOMO and TMEM147.  

PMID:20538592

**Comment by bmeldal** [comment]
The paper doesn't have any functional experiments to show what it actually does, not even which process it's involved in. We can add part_of ER membrane.

Maybe say: "Subunits are highly conserved in vertebrates (or more generic?) and include Nicalin, NOMO and TMEM147." ?

**Comment by Antonialock** [comment]
t doesn't look like it's role is well understood yet

according to this recent  technical report:
Despite the study of Nomo in embryogenesis and pattern expression in embryo and adult tissues, its biological functions in mammalian postnatal tissues remain unknown. Since Nomo is required to produce proper axial mesoderm patterning, bone and heart formation, complete Nomo inhibition could impair embryo development. To study its functions during postnatal stages we decided to create a new mouse model to conditionally interfere with its functions.

https://link.springer.com/article/10.1007/s11033-019-05214-7

**Comment by Antonialock** [comment]
but from fish

Nomo (Nodal modulator) and its binding partner, Nicalin, are components of a novel protein complex involved in Nodal signaling. This complex has been revealed as an antagonist of Nodal signaling during mesendodermal patterning in zebrafish. The evolutionary conservation of Nicalin and Nomo in metazoans and plants indicates that the Nomo/Nicalin complex could have a similarly important role.

**Comment by hdrabkin** [comment]
Ok; term made.
+id: GO:0106249
+name: Nicalin-NOMO complex

**Comment by Antonialock** [comment]
Thanks!

--
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK
