### ISSUE TITLE
NTR:cholesterol glucosylation/deglucosylation

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#16623]
Dear editors,
there is now evidence in vertebrates that cholesterol (a lipid), can be glucosylated (a subtype of glycosylation) with glucosylceramide as glucose donnor. Same paper (PubMed=26724485) also shows that glucosylated cholesterol can also be deglucosylated by the same enzymes through the transfer of glucose to ceramides.
We already have a term for lipid glycosylation GO:0030259 and I was wondering if one should create a new term for lipid deglycosylation or extend its definition so that it includes also the deglycosylation. I also noticed there is a term  GO:0097359 UDP-glucosylation . Depending on the granularity you want to have in the ontology you may also consider having a parent term for GO:0097359 UDP-glucosylation that describes more generally glucosylation (including lipid glucosylation).
Alternatively one could create a very specific term for cholesterol glucosylation/deglucosylation.
Thanks in advance to check how this can be improved.
Lionel

**Comment by lbreuza** [comment]
Hi,
I had almost forgotten that request. Will you consider it or should we close the ticket?
Thanks for letting me know.

**Comment by hdrabkin** [comment]
and  did I
Could you please supply proposed def, is_a parent(s), and references for your proposed terms; this would help tremendously.

**Comment by lbreuza** [comment]
Hi Harold,
while looking at my request with fresh eyes, I realized that the term I was looking for is not absolutely required. I suppose I can use the term GO:0019377/glycolipid catabolic process instead. The breakdown of cholesteryl β-D-glucoside into cholesterol and glucose is indeed included in the definition of GO:0019377. I will close the ticket. Sorry for the inconvenience.
Best, Lionel
