### ISSUE TITLE
question about  GO:0009817 defense response to fungus, incompatible interaction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16621]
@tberardini   I thought I would check what TAiR used for RPP1 and its
GO:0009817     defense response to fungus, incompatible interaction

What does "incompatible interaction" mean?  it doesn't sound like a process?

the definition of the term is
A response of an organism to a fungus that prevents the occurrence or spread of disease.

so the differntia must be
that prevents the occurrence or spread of disease.
but isn't that what any  "defense response to fungus" does?

Isn't this term really combining phenotypic information into a GO process?

**Comment by tberardini** [comment]
Parent term definition:

**[defense response to fungus](http://amigo.geneontology.org/amigo/term/GO:0050832#display-lineage-tab):** Reactions triggered in response to the presence of a fungus that act to protect the cell or organism.

**[defense response to fungus, incompatible interaction](http://amigo.geneontology.org/amigo/term/GO:0009817#display-lineage-tab):**  A response of an organism to a fungus that prevents the occurrence or spread of disease.

From my brief review reading, the incompatible interaction encompasses the host organism's response (specific gene products are expressed that mediate the defense, for example to increase callose deposition at the site of infection) after the pathogen has penetrated the host and is beginning to spread.  Resistant plants can express such genes and mount a defense response (incompatible interaction) while susceptible plants don't have or don't express such genes and cannot mount a defense response (compatible interaction, not in GO scope).

@lreiser and/or @ebakker2: Can you add any insight to the specific term 'incompatible interaction' from any papers you've encountered recently?  Thanks.

**Comment by ValWood** [comment]
I have just been speaking to @CuzickA (plant pathogen curator at Rothamsted Research) . We think this is describing

effector-triggered immunity, it's just an orthogonal way of describing it.

We are  going to suggest  getting rid of the 
"defense response to species" terms in favour of the "actual processes"
(these aren't really species neutral. Often the signalling pathway is the same for different types of pathogen. There are differences but they would be better described as "specific processes"
under  

like
effector-triggered immunity
(there are even more  ways of describing this in the ontology, I will open a ticket about this shortly, but  welcome your insights here too.

I'll tag you all in the new ticket.

**Comment by ValWood** [comment]
closing in favour of
https://github.com/geneontology/go-ontology/issues/16655

**Comment by vanaukenk** [comment]
@ValWood  - I'm going to go ahead and close this ticket, since it looks like there is more complete info in #16655

**Comment by ValWood** [comment]
yes, I meant to do that...
