### ISSUE TITLE
GO:0001871     pattern binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16620]
very bad
GO:0001871     pattern binding

Interacting selectively and non-covalently with a repeating or polymeric structure, such as a polysaccharide or peptidoglycan. PMID:12072369 PMID:12225919 PMID:12507420 PMID:12925128 PMID:14523544

This is a *terrible* term.
It's a parent of

GO:0030247    polysaccharide binding | is_a
GO:0001876    lipoarabinomannan binding | is_a

and
neither of these stipulate "pattern" binding , whatever that means.... (which is actually.... nothing)

A repeated polymeric structure isn't a 'pattern'

and it has a synonym
pattern recognition activity???!!!???

**Comment by pgaudet** [comment]
Obsolete ? 
No direct annotations, 2 children can be rehoused: 
'lipoarabinomannan binding'
'polysaccharide binding'

**Comment by ValWood** [comment]
Yes for sure.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: GO:0001871 pattern binding

The reason for obsoletion is that this term was an unnecessary grouping term. There are no annotations, no InterPro2GO mappings to this term. This term is present in one slim: goslim_pir 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/16620

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 23rd, 2018. Unless objections are received by November 23rd, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@nataled Do you want to replace this term by something else, or just remove it ? 
Thanks, Pascale

**Comment by pgaudet** [comment]
@ukemi any idea why the term labels of some ChEBI and CARO have changed ? 
https://github.com/geneontology/go-ontology/pull/16645/commits/b5841e9ab314cc035cf7f03c4f7f1d7d5ca4bc8a

should I worry about that ?

**Comment by ukemi** [comment]
I used to see this a lot but just saw it again recently. In the past as long as identifiers were the same, I didn't worry about it. At the end of the day, it is the identifier to the external ontology that gets used. I am curious as to why this happens though. Those imports haven't been regenerated in a while.

**Comment by balhoff** [comment]
I did an RO_import update yesterday, which came with some CARO label changes: https://github.com/geneontology/go-ontology/pull/16644/files

**Comment by pgaudet** [comment]
So, would I be merging old labels ? I did a git pull before starting.

**Comment by ukemi** [comment]
Thanks Jim. That explains it.

**Comment by balhoff** [comment]
@pgaudet it's just because the OBO format puts the label in a comment anywhere the term is referenced, so there is a bit of a cascading effect as different files are edited.

**Comment by addiehl** [comment]
These pattern terms were created to match the usage of the word pattern in the scientific literature.  Not something I made up.  There are five Pubmed references associated with this term.  Did you read any of them?

**Comment by ValWood** [comment]
For sure they are  called "pattern recognition proteins", but can  "pattern binding" really be used  in this context as a grouping term for these descendants?

Can't gene products can bind to a polysaccharide  or a peptidoglycan without being a pattern recognition molecule?  I thought the pattern binding was to refer to recognizing a specific arrangement of  saccharide residues in a polymer  ?  Presumably binding to homomeric polymers are not recoginising specific "patterns"

if it isn't always true it should be
polysaccharide binding
--polysaccharide pattern binding

with the grouping term renamed to "polymeric pattern binding"

**Comment by ValWood** [comment]
I should have been clearer with my original request. My gripe is with the use of the word "pattern" to group "polysaccharide" and "lipoarabinomannan".

Polysaccharides occur in lots of contexts in addition to those recognised by immune molecules and these aren't called "patterns"    (cell wall polysaccharides, for example)

**Comment by ValWood** [comment]
What is the fix? It's really unclear to have 

"pattern binding" as a parent of 
"GO:0030247    polysaccharide binding "

It really means to bind a repeating motif in a polymer .

This would be analogous to making  "DNA lop binding" a parent of "DNA binding" or "protein motif binding " a parent of "protein binding". It doesn't seem to be ontologically correct as it is....

**Comment by pgaudet** [comment]
The fix is that pattern binding is now obsolete. 
- GO:0030247 polysaccharide binding  is now a child of carbohydrate binding
- GO:0001876    lipoarabinomannan binding is a GPI anchor binding. 

This is consistent with the MF structure. The 'pattern binding' aspect is relevant for the signaling BPs (see other tickets). 

OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think the term is valuable for "polymeric pattern binding", but it in the wrong place.

Should wait for @addiehl  to comment on my suggestion to move  and specify it.

**Comment by addiehl** [comment]
I am okay if 'pattern binding' goes away as a MF term, if pattern seems too vague and not referring to binding of a specific chemical class of molecules.  However, the mechanism of binding polysaccharides and related structures of bacterial origin as a means for activating the innate immune response and regulating the type of adaptive immune response that develops subsequently is well investigated (and indeed, was already well understood in 2005-2006 when I worked on many of these terms) and researchers in this field had already settled on the phrase 'pathogen-associated molecular patterns' to describe the targets of particular receptors and their signaling pathways, so we need continue to represent associated biological processes appropriately.

**Comment by pgaudet** [comment]
But isn't this just a normal binding? Can we not make the distinction under BP ? 
I think many of the children are NOT relevant to the kind of pattern binding we are discussing: 
(children of polysaccharide binding):
'(1->3),(1->4)-beta-glucan binding'
'(1->3)-beta-D-glucan binding'
'(1->4)-beta-D-galactan binding'
'(1->6)-beta-D-glucan binding'
'alpha-D-glucan binding'
'arabinogalactan binding'
'cellodextrin binding'
'cellulose binding'
'cyclodextrin binding'
'galacturonan binding'
'glycogen binding'
'heteropolysaccharide binding'
'inulin binding'
'mannan binding'
'pullulan binding'
'starch binding'
'xylan binding'

These are all inferred from ChEBI.

Pascale

**Comment by ValWood** [comment]
- well,  if we can convey the meaning precisely with the receptor function terms, probably there is no need for this term in binding.

- This depends on the outcome of https://github.com/geneontology/go-ontology/issues/16616

Q would the "pattern binding" term be used for any other gene products apart from receptors ?
