### ISSUE TITLE
NTR peptidyl-lysine 3-dioxygenase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16632]
NTR peptidyl-lysine 3-dioxygenase activity
I think this is a new EC? sibling to GO:0070815
"The finding that JMJD7 catalyzes (3S)-lysyl hydroxylation expands the repertoire of 2OG oxygenase-catalyzed modifications of basic residues,"
PMID:29915238

**Comment by hdrabkin** [comment]
I need to see the paper to contruct the reaction, but MGI does not have subscription to this Journal. Can you attach pdf?

**Comment by Antonialock** [comment]
thanks!

Here it is (supp and main)

[41589_2018_71_MOESM1_ESM.pdf](https://github.com/geneontology/go-ontology/files/2586330/41589_2018_71_MOESM1_ESM.pdf)

[s41589-018-0071-y.pdf](https://github.com/geneontology/go-ontology/files/2586331/s41589-018-0071-y.pdf)

**Comment by hdrabkin** [comment]
Proposed def
Catalysis of the reaction: protein L-lysine + 2-oxoglutarate + O2 = protein 3-hydroxy-L-lysine + succinate + CO2.

reasonable?

**Comment by Antonialock** [comment]
your proposed def sounds good

yes EC 1.14.11.4 corresponds to GO:0008475 procollagen-lysine 5-dioxygenase activity
Catalysis of the reaction: procollagen L-lysine + 2-oxoglutarate + O2 = procollagen 5-hydroxy-L-lysine + succinate + CO2. 

but I couldn't annotate to this term because it didn't fit the definition

**Comment by Antonialock** [comment]
This is not my area of expertise so happy to go with whatever you suggest (but GO:0070815 or GO:0008475 don't fit, and the next one up form that is GO:0016706 which has so many parents I thought I should ask for a new term)

**Comment by hdrabkin** [comment]
GO:0106155; done.

**Comment by Antonialock** [comment]
thanks!

**Comment by deustp01** [comment]
RHEA:40747 probably doesn't work because that reaction has free lysine (CHEBI:32551) as an input, not a lysine residue of an unspecified protein CHEBI:29969, as in RHEA:57156 (only as an example of a lysine residue target; otherwise it too is the wrong reaction)

**Comment by hdrabkin** [comment]
Yes, I looked up the reaction ref and they were definitely using free amino acids in their screen. So no rhea for me!

**Comment by ukemi** [comment]
Please request a Rhea reaction. @deustp01, should we also try to get this into Reactome?

**Comment by deustp01** [comment]
We actually have a canned "help" reply: your negative search result in Reactome is correct but JMJD7 is in scope for the Reactome project. Indeed, we have it in our set of proteins known to be interactors of our annotated ones. I'll look some more at the PMID cited at the top of this thread to see if there's any agreement on a plausible physiological protein substrate, but annotating the reaction looks easy and the interactors may suggest a process to associate the reaction with.

**Comment by Antonialock** [comment]
@deustp01 PMID:29459673 might also be of interest

We have reported that JMJD5 and JMJD7 (JMJD5/7) are responsible for the clipping of arginine methylated histone tails to generate "tailless nucleosomes", which could release the pausing RNA polymerase II (Pol II) into productive transcription elongation. JMJD5/7 function as endopeptidases that cleave histone tails specifically adjacent to methylated arginine residues and continue to degrade N-terminal residues of histones via their aminopeptidase activity. Here, we report structural and biochemical studies on JMJD5/7 to understand the basis of substrate recognition and catalysis mechanism by this JmjC subfamily. Recognition between these enzymes and histone substrates is specific, which is reflected by the binding data between enzymes and substrates. High structural similarity between JMJD5 and JMJD7 is reflected by the shared common substrates and high binding affinity. However, JMJD5 does not bind to arginine methylated histone tails with additional lysine acetylation while JMJD7 does not bind to arginine methylated histone tails with additional lysine methylation. Furthermore, the complex structures of JMJD5 and arginine derivatives revealed a Tudor domain-like binding pocket to accommodate the methylated sidechain of arginine, but not lysine. There also exists a glutamine close to the catalytic center, which may suggest a unique imidic acid mediated catalytic mechanism for proteolysis by JMJD5/7.

**Comment by deustp01** [comment]
Thanks - I'll take a look.

**Comment by hdrabkin** [comment]
@ukemi , EC/Rhea requests already sent.

**Comment by deustp01** [comment]
@ukemi asked for the human reaction to be created in Reactome. Here is the lysine hydroxylation reaction in draft form - reactomecurator.oicr.on.ca/PathwayBrowser/#/R-HSA-9629569 .
It follows Rhea reaction RHEA:57153 as closely as I could. This may be a use case for improving RHEA - Reactome mappings, for discussion in Geneva.

**Comment by Antonialock** [comment]
@ValWood pombe jmj4 ?

**Comment by ValWood** [comment]
> @ValWood pombe jmj4 ?

yep will update

**Comment by hdrabkin** [comment]
RHEA:57153 added; tag removed
