### ISSUE TITLE
NTR protein localization to ciliary base

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16633]
NTR protein localization to ciliary base
child of GO:0034613
standard def

PMID:24582806

**Comment by pgaudet** [comment]
@Antonialock Do you know if there is a relation to the 'ciliary transition zone'? Sounds like it should be a parent?

**Comment by Antonialock** [comment]
Thanks Pascale. I will just move this to a term in the slim we used. I'll close this request.
