### ISSUE TITLE
NTR iRhom2/ADAM17 sheddase complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16635]
child of GO:0032991
A complex consisting of ADAM17 in complex with regulatory iRhoms and FERM domain containing proteins
PMID:29897336

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140910
+name: iRhom2/ADAM17 sheddase complex
+namespace: cellular_component
+def: "A complex consisting of ADAM17 in complex with regulatory iRhoms and FERM domain containing proteins." [PMID:29897336]
+is_a: GO:0032991 ! protein-containing complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16635 xsd:anyURI
+created_by: pg
+creation_date: 2022-09-16T13:39:42Z

**Comment by pgaudet** [comment]
@ValWood
