### ISSUE TITLE
NTR N-acetylmannosamine binding

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16636]
NTR N-acetylmannosamine binding
CHEBI:62164 
standard def
PMID:24293368

**Comment by ValWood** [comment]
Is this endogenous binding?  i.e was it isolated bound, or  'forced' You should not annotate this if it was  just incubated together.

**Comment by pgaudet** [comment]
From the paper I don't see that this is a physiological binding (it may be!); have you seen evidence that it is ?

**Comment by Antonialock** [comment]
They just call it a high affinity ligand, it's a crystal structure. I guess it might not be physiological (why do they bother...)
