### ISSUE TITLE
NTR ubiquitin-dependent endosome transport via multivesicular body sorting pathway

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16640]
ubiquitin-dependent endosome transport via multivesicular body sorting pathway
suggested def: The directed movement of ubiquitinated substances from endosomes to lysosomes or vacuoles by a pathway in which molecules are sorted into multivesicular bodies, which then fuse with the target compartment. 
is_a GO:0070086
is_a GO:0032509
PMID:26797118

**Comment by pgaudet** [comment]
Hi @Antonialock 
Your definition does not state how this process is ubiquitin-dependent - can you please clarify ?

**Comment by pgaudet** [comment]
Also - which protein are you trying to annotate ?

**Comment by pgaudet** [comment]
The ubiquitination part seems to regulate the endocytosis - would 'GO:0010797 regulation of multivesicular body size involved in endosome transport' work for you ?

**Comment by ValWood** [comment]
It seems that this pathway is necessarily ubiquitin-dependent based on

GO:0071985    JSON
multivesicular body sorting pathway
Biological Process

Definition (GO:0071985 GONUTS page)
A vesicle-mediated transport process in which transmembrane proteins are ubiquitylated to facilitate their entry into luminal vesicles of multivesicular bodies (MVBs); upon subsequent fusion of MVBs with lysosomes or vacuoles, the cargo proteins are degraded. PMID:17603537

Judging by the request, I think Antonia wants to annotate simultaneously to
GO:0070086 GO:0070086   ubiquitin-dependent endocytosis
GO:0032509 endosome transport via multivesicular body sorting pathway
to describe a single process. 

@Antonialock  can you confirm? If so, this indicated likely duplication of terms with the same meaning in different branches of the ontology

**Comment by Antonialock** [comment]
they are redundant? I guess GO:0032509 will do for this purpose.

**Comment by Antonialock** [comment]
the def of GO:0032509 didn't include the bit about ub, so I thought I wanted a more specific term

**Comment by ValWood** [comment]
It doesn't explicitly, but because GO:0071985  is a parent it does implicitly.

But really the relationship between GO:0070086 and GO:0032509 needs establishing so we'll keep this one open to address that.

**Comment by pgaudet** [comment]
OK - let me know when there is an action for this.

**Comment by ValWood** [comment]
I think it's OK, closing
