### ISSUE TITLE
Change label 'GO:0044183 protein binding involved in protein folding' and move as a direct child of molecular function

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16649]
I propose to change the label of 'protein binding involved in protein folding' to a label more easy to find: 'protein folding chaperone'. 

As well, I'd like to make it a direct child of  molecular function, as this is a true 'molecular activity', not just a binding.

**Comment by ValWood** [comment]
Also in the ticket I just closed as "duplicate" 
what about:
unfolded protein binding (GO:0051082)

does that mean something slightly different?

**Comment by pgaudet** [comment]
I dont think these are different. I think the unfolded protein is just how you test protein folding (ie you denature it and look at it unfold). See 
http://science.sciencemag.org/content/353/6294/aac4354?casa_token=x0P-xac5lWQAAAAA:fi7awS-rnamIvw7KN9PU3LpLl9Szx8SVreXjkfFni97c8XtdBNlTJyhqrPMPHaI4aKFTdUhtjkHI1a8

What do you think ? 
(I think there is another ticker somwehere else).

**Comment by ValWood** [comment]
I can't think of any immediate difference but it might be good to ask more widely...

Maybe there are instances of binding to an unfolded protein to catabolise it, not to fold it?
I don't really know....

**Comment by pgaudet** [comment]
I'll go ahead and do that.
Just pinging a few people for comments: 
@thomaspd @vanaukenk @RLovering @hattrill 
+ anyone else who can think of an objection to this, please let me know. 

Pascale

**Comment by pgaudet** [comment]
@ValWood The new name will be 'protein folding chaperone'. If there is a  need for 'protein degradation chaperone' we can create that later.

**Comment by ValWood** [comment]
good point!

**Comment by pgaudet** [comment]
Changing the logical definition to 

molecular_function
 and 'has part' some 'protein binding'
 and ('part of' some 'protein folding')

@ukemi does that seem OK to you ?

**Comment by hattrill** [comment]
With regard to "unfolded protein binding", there are chaperones/co-chaperones/small HSPs that bind unfolded proteins to keep them unfolded so that they can be correctly folded by ATP-dep. chaperones or stop them from making big, nasty aggregates under cell stress.

**Comment by ukemi** [comment]
Correct. I'm not sure all of these refold the proteins. Sometimes they target them for destruction. That was part of the confusion with the original chaperone term.

**Comment by pgaudet** [comment]
@hattrill @ukemi 
This term specifically describes a **protein folding** activity - the definition "Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) that contributes to the process of **protein folding.**" 

We can discuss terms for unfolded protein binding separately if needed. 

Pascale
