### ISSUE TITLE
cell proliferation term name  tweaks & do not annotate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16659]
Follow up from QC call

Term "cell proliferation"

rename
"cell population proliferation"

to make usage clearer

Should also be made "not for direct annotation"
Annotations should be to cell-type specific proliferation , and if annotatable  should be to "regulation of x cell population proliferation"
These terms are not intended for anything required for growth and division of a single cell, but  specifically for the "regulation of population expansion".

**Comment by pgaudet** [comment]
@ValWood This term has many children - for example 'cardiac muscle cell proliferation'. Do you suggest renaming 'cardiac muscle cell population proliferation'  ?

**Comment by ValWood** [comment]
> This term has many children - for example 'cardiac muscle cell proliferation'. Do you suggest renaming 'cardiac muscle cell population proliferation' ?

I don't think that's necessary. These term more clearly refers to a population of cells in a multicellular organisms. "cell proliferation"  on is own doesn't.

**Comment by ValWood** [comment]
Above would also be OK if they have "cell type" as an extension?

**Comment by ValWood** [comment]
The above seems a lot. When I filter on "cell proliferation" direct annotation I only see Total annotations: 421;

**Comment by ValWood** [comment]
>The above seems a lot. When I filter on "cell proliferation" direct annotation I only see Total annotations: 421;

Ah ignore. I thought you were listing the annotations direct to "cell proliferation"

**Comment by pgaudet** [comment]
I meant to paste the DIRECT annotations: 

(116)	MGI
(113)	UniProt
(50)	FlyBase
(42)	TAIR
(26)	AgBase
(25)	RGD
(20)	ZFIN
(9)	GeneDB
(6)	BHF-UCL
(4)	GO_Noctua
(3)	WB
(3)	dictyBase
(2)	HGNC
(1)	Alzheimers_University_of_Toronto
(1)	CACAO

- Pascale

**Comment by sabrinatoro** [comment]
I looked at the ZFIN annotations. There would be no problem to rename the term "cell population proliferation". 
I will update some of the direct annotation to indicate the cell population or the process in which the cell proliferation is occurring.

**Comment by pgaudet** [comment]
I updated the term label to 'cell population proliferation' , as well at the regulation children, 'regulation of cell population proliferation', and positive and negative children. 

I'll ask for an annotation review before making the term 'do not annotate'. 

Thanks, Pascale

**Comment by pfey03** [comment]
The Dicty EXP were legacy and have been updated to term we use currently. These Dicty 'growth' IMP went years ago to 'cell proliferation' and then to 'asexual reproduction', which those were updated to.

I also deleted the legacy dictyBase ISS annotations
