### ISSUE TITLE
NTR and ontology revisions for plant immunity terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16655]
Attention
@lreiser (TAIR)
@ebakker2 (TAIR)
@tberardini (TAIR)
@CuzickA  (PHI_Base)

As part  of the PHI-Base project we are  building and ontology to represent  and annotate pathogen host interaction phenotypes. These terms will be logically defined using GO terms to describe 'normal' processes . We will also provide GO annotations for pathogen species and occasionaly for host species.

As part of the tool development I was curating this paper:
PMID:20601497 Activation of an Arabidopsis resistance protein is specified by the in planta association of its leucine-rich repeat domain with the cognate oomycete effector.
Authors | Krasileva KV, Dahlbeck D, Staskawicz BJ

And  we encounterd a few problems with the GO terms we would to use to describe the Arabidopsis protein.

Background for GO editors
Plants have evolved a multilevel innate immune system to protect them against infection by a diverse range of pathogens, including viruses, bacteria, fungi, oomycetes, and nematodes. Despite the great evolutionary distance among phytopathogens, the out- come of the plant–pathogen interactions is controlled by the same principles: the ability of the pathogen to suppress the plant immune system to establish infection, and the ability of plants to recognize the presence of a pathogen and to induce immune responses that restrict pathogen growth.

Plants  innate immune systems have 2 main components:
1. First line of defense: PAMP- triggered immunity (PTI)
Upon association with PAMPs, the pattern-recognition receptors activate a downstream mitogen-activated protein kinase signaling cascade that culminates in transcriptional activation and generation of the innate immune responses
To interfere with PTI effector proteins that are delivered into and function within the host plant cells

2. Second  line of defense: Effector-triggered immunity
https://en.wikipedia.org/wiki/Effector-triggered_immunity
The second layer of plant immunity depends on the ability of the plant to recognize these pathogen- derived effectors and trigger a robust resistance response that normally culminates in a hypersensitive cell death response (HR)
Effector-triggered immunity is mediated by a large group of structurally related intracellular innate immune receptors encoded by resistance (R) genes. 

RPP1, MOLECULAR FUNCTION

So RPP1 is an  "intracellular signalling receptor" for the  "pathogen-derived effectors"
We couldn't find anything suitable for this under "signaling receptor activity" 
https://www.ebi.ac.uk/QuickGO/term/GO:0038023
SUGGEST
NTR:
intracellular innate receptor activity
synonym related  resistance gene
synonym related receptor recognition
Combining with an effector entity produced by a pathogen in order to activate effector-triggered immunity in a host.
PMID: 21490299 is one paper that uses this  term to describe such receptors, however the term might not be specific enough to describe  effector-triggered immunity.
It would be OK to make the activity definition more general if necessary (we can link the activity to the process to capture this detail).

Notes/Comments: 
-  "intracellular innate receptor activity" may exist in other contexts, in which case this would need to be revised?
- It seems reasonable to describe receptors based on their ligands (i.e specifically a 'pathogen effector' , but  note that  pathogen 'effectors are fairly heterogeneous).
- we tried to make this generic  for effector-triggered immunity 
- "intracellular innate receptor activity" most slosely matched the community descriptions we could find. Generally these types of receptors are just called "resistance genes" which is not informative about the function.

RPP1 BIOLOGICAL PROCESS

~We looked for the term to describe the process 
"Effector-triggered immunity" and eventually located 
GO:0080185    effector dependent induction by symbiont of host immune response
which is *very nicely defined*
Any process that involves recognition of an effector, and by which an organism activates, maintains or increases the frequency, rate or extent of the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction. Effectors are proteins secreted into the host cell by pathogenic microbes, presumably to alter host immune response signaling. The best characterized effectors are bacterial effectors delivered into the host cell by type III secretion system (TTSS). Effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance or R proteins) and subsequent activation of host immune response. PMID:16497589
but is there any reason why the primary term name can't be
"Effector-triggered immunity"? 2,440,000 results 
"effector dependent induction by symbiont of host immune response" About 223 results
presumably all from GO.
I very nearly missed this term. And it only has 5 annotations which is no surprise!~

transferred to 
https://github.com/geneontology/go-ontology/issues/17014

**Comment by ValWood** [comment]
Now it gets a little more complicated:
Whilst curating this paper we found other terms that could be used interchangably with 
GO:0080185 effector dependent induction by symbiont of host immune response
(the ones I originally used).

These were
GO:0002229 | defense response to oomycetes
GO:0034052 | positive regulation of plant-type hypersensitive response

![plant immunity](https://user-images.githubusercontent.com/7359272/48773504-7b84a780-ecbf-11e8-8b0c-1a186a576889.jpg)


This raised 2 questions.
There are lots of  "defense response to (oomycete, fungi etc) "....terms
but this seems to be an orthogonal way of describing the  first or second responses. There are different responses  required to deal with different organisms, but shouldn't these be dealt with differently?

besed on:
Plants have evolved a multilevel innate immune system to protect them against infection by a diverse range of pathogens, including viruses, bacteria, fungi, oomycetes, and nematodes. Despite the great evolutionary distance among phytopathogens, the outcome of the plant–pathogen interactions is controlled by the same principles

These response to terms are not really saying anything about the mechanism in most branches, and they encourage inconsistent curation.

defense response to oomycete 48 EXP
defense response to fungus 696 EXP

it would be much more useful to say the *type* of response. It seems that curators  are annotating only in one branch.  Sometimes descendants, are shoe-horned  in t capture mechanisms, which results in 2 ways to say the same thing...

GO:0009817 defense response to fungus, incompatible interaction 
(we figured that this means 
whether or not a plant can mount a hypersensitive cell-death response, and it in effect a term to describe the extent of pathogenicity/virulence  and is therefore out of scope for GO
SUGGEST obsoletion?

antifungal innate immune response (14 EXP) 
as children


I would suggest merging these terms into the  most general mechanism terms.
If this isn't possible we can't describe processes simply and we would then need to request
specific terms to link these processes:

e.g.
GO:XXXXXXX effector dependent induction by oomycete of host immune response

GO:XXXXXXX effector dependent induction by fungus  of host immune response
child of
https://www.ebi.ac.uk/QuickGO/term/GO:0061760
and
GO:0080185   effector dependent induction by symbiont of host immune response

which seems another option,  if for some reason we really need to keep the classification by 
pathogen type

**Comment by ValWood** [comment]
ALso tagging
@hattrill  as fly use defense response to organism terms.

Maybe people want this axis of classifications, but it seems that using  this branch means that you  don't capture important details about mechanism innate, humoral, effector triggered immunity, PAMP-triggered immunity etc.....if you classifly/annotate by pathogen

**Comment by hattrill** [comment]
Yes, we've been talking about this too:
defense response to fungus,
defense response to gram negative bacterium,
defense response to gram positive bacterium

are not linked to innate immunity, etc. and there are many terms that could potentially describe one biological response to a pathogen e.g. recognition of a gram positive bacterium molecule that triggers the production of anti-microbial peptides can be annotated with many different terms, and it is not entirely clear on how we would use these in annotation consistently.

We have signaling pathways that are specific for gram positive, negative bacteria, fungi and viruses, so it is useful to capture that specificity. 
I should think that these pathogen recognition pathways are always "innate" - or would that be wrong? I am thinking IgE and parasites - I am not sure of the adaptive component there.

**Comment by tberardini** [comment]
@dhldhl  (Donghui): Can you please have a look at this?  Yes, I'll pulling you back into the GO world, with hope that your combined background in ontology development and plant-pathogen interactions can help us out.  Thanks.

**Comment by dhldhl** [comment]
This is a good review article on innate immunity in plants: https://www.ncbi.nlm.nih.gov/pubmed/16497589
I think the challenge here is that many of the GO terms try to describe the same process but each capture one aspect/subset of the process from different perspective, they overlap with each other; often used interchangeably but also with subtle difference or emphasis:

Effector triggered immunity (effector is from the pathogen perspective)
(plant type) hypersensitive response or R protein mediated resistance (this describes the same process from plant/host perspective)

defense response to xxx (pathogen) - these are more generic terms used when specific mechanisms are unknown. TAIR has a large # of annotations to these terms, so caution if the proposal is to obsolete them.

PAMGO created lots of terms from the microbe-host interactions perspective. My personal opinion is that while these terms are very specific, they are hard to use and hard for people (particularly users of GO) to understand.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2654661/

My 2cents are while we want to be specific, I'd prefer we preserve terms that are commonly used/accepted by the research community (terms such as PTI, ETI, HR, defense response etc), perhaps improve on improving the synonyms fields.

**Comment by ValWood** [comment]
Yes I will do a summary. It probably won't be this week.
I'll wait until I next speak with Alayne (@CuzickA ) and work through it with her.

Thanks @dhldhl that really useful.

**Comment by ValWood** [comment]
Have broken this down into separate tickets,

https://github.com/geneontology/go-ontology/issues/17017
https://github.com/geneontology/go-ontology/issues/17014
https://github.com/geneontology/go-ontology/issues/17013
https://github.com/geneontology/go-ontology/issues/17012

please follow/ comment if you are interested/affected.

val

**Comment by ValWood** [comment]
> Effector triggered immunity (effector is from the pathogen perspective)
(plant type) hypersensitive response or R protein mediated resistance (this describes the same process from plant/host perspective)

Although the effector is a pathogen derived entity,  Effector triggered immunity is a host process and defined in GO as a host process, and has only been used to annotate plant gene products.
Pathogen genes could, however, be annotated to "supression" of this process.

hypersensitive resonse (HRR) is a "readout" for ETI, it is a process that occurs in reponse to the "effector triggered immunity" signalling.
