### ISSUE TITLE
NTR: innate receptor ligand activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16656]
related to
https://github.com/geneontology/go-ontology/issues/16655

we also require a new term to describe the "effector" as a ligand for the proposed receptor:
"intracellular innate receptor activity"

the 
NTR: innate receptor ligand activity
synonym broad “pathogen effector”
The activity of a pathogen entity* that interacts with a host  receptor  "intracellular innate receptor activity" to activate effector triggered immunity (GO:0080185)    

* we used entity because effectors can be metabolites, proteins 

is_a
GO:0048018    receptor ligand activity

**Comment by hattrill** [comment]
I am bit confused as to why this seems to be restricted to intracellular events - perhaps this just needs to be made explict in the term name.

It's just that we could describe many ligands as having "innate receptor ligand activity":
In insects the toll pathway is activated by an endogenous ligand, spatzle, that cleaved to its activate form downstream of a protease cascade which is activated by a soluble, extracellular "pattern recognition" protein binding to a pathogenic molecule. 
Vertebrate Toll-like receptors directly bind pathogenic entities.
Insects have an innate receptor, Imd, that binds peptidoglycans.

**Comment by ValWood** [comment]
Yes you are right. This term should be generic for plasma membrane and intracellular receptors. There does not seem to be any reason to discriminate between these at present (it should also be clear  from the type of receptor co-annotated what the particular  "pathogen effector" is binding to).

Any suggestions to improve welcome. The pathogen community seem to use very general things like "effector' for the ligand  and 'resistance protein'  for the receptor, so it's difficult to pin down in a way that is explicit but will also be meaningful to these communities.

Also let us know if you think we missed any existing terms which already describe these activities...


  Attach files by dragging & dropping, selecting them, or pasting from the clipboard.

 Styling with Markdown is supported

**Comment by ValWood** [comment]
Doe this sound corrcect?

The activity of a pathogen entity that interacts with a host intracellular receptor or plasma membrane  receptor to activate effector-triggered immunity (GO:0080185)

**Comment by ValWood** [comment]
Here, I was specifically trying to describe the ligand that the pathogen produces for these receptors. This type of host receptor ligand  seems that it should have its own function term?

**Comment by hattrill** [comment]
Perhaps if the name was "innate receptor pathogen-derived ligand activity"  or "pathogen effector innate receptor ligand activity"?

**Comment by ValWood** [comment]
yes, also we might not need to say "innate" that is a given from 
" effector triggered immunity"?

**Comment by hattrill** [comment]
Agreed.

**Comment by pgaudet** [comment]
@ValWood 
1) Can you add a reference ? 

2) Is this the current proposal ? 

NTR: receptor pathogen-derived ligand activity
synonym related "innate receptor ligand activity"
synonym related  "pathogen effector innate receptor ligand activity"
synonym broad “pathogen effector”

Def: The activity of a pathogen entity that interacts with a host receptor intracellular innate receptor activity to activate effector triggered immunity (GO:0080185)

Thanks, Pascale

**Comment by ValWood** [comment]
PMID:20601497 Activation of an Arabidopsis resistance protein is specified by the in planta association of its leucine-rich repeat domain with the cognate oomycete effector.
Authors | Krasileva KV, Dahlbeck D, Staskawicz BJ

will do. 

The term name would need to be
 pathogen-derived receptor ligand activity

def
 The activity of a pathogen entity that interacts with a host receptor  to activate effector triggered immunity


Does that work?
@CuzickA 
@hattrill
