### ISSUE TITLE
propose obsoletion 'x domain-mediated complex assembly'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16658]
I think we should consider obsoleting this term, unless there is a strong reason to keep it.

It does not have any annotations or a reference. From my knowledge of LRR motifs they are often scaffolds for complexes (often signalling complexes). This means they are a component of the complex that they are required for the assembly of, and in this case not involved in the process of assembly (i.e. this would be only a phenotype, describing an interaction required for the complex to assemble correctly).

GO:0071571   LRR domain-mediated complex assembly
A process of protein complex assembly in which the arrangement and bonding together of the set of components that form the protein complex is mediated by an LRR (leucine-rich repeat) domain interaction.

**Comment by ValWood** [comment]
hmm


GO:0071571    LRR domain-mediated complex assembly
GO:0071531    Rel homology domain-mediated complex assembly
GO:0071530    FHA domain-mediated complex assembly
GO:0071538    SH2 domain-mediated complex assembly  44 annotations
GO:0071523    TIR domain-mediated complex assembly
GO:0071536    RING-like zinc finger domain-mediated complex assembly
GO:0071534    zf-TRAF domain-mediated complex assembly
GO:0071537    C3HC4-type RING finger domain-mediated complex assembly
GO:0030275    LRR domain binding  533 annotations
GO:0071552    RIP homotypic interaction motif-mediated complex assembly
GO:0071533    ankyrin repeat-mediated complex assembly

all have no annotations except for
GO:0071538    SH2 domain-mediated complex assembly  44 annotations

will try to trace the source of these. I'm not aware of a direct role in complex assembly for these domains (none are chaperones?)

**Comment by ValWood** [comment]
single  IDA annotation (others are ISO/IEA)

UniProtKB:P46108 | CRK | involved_in | GO:0071538    SH2 domain-mediated complex assembly | ECO:0000314 IDA | PMID:12384576 |   | 9606 Homo sapiens | CAFA

I'll tag @ggeorghiou 

http://europepmc.org/abstract/MED/12384576
The SH2 domain bridges two ligands that bind at distinct sites. 

So this seems a bit mechanistic to be in the process ontology 

It seems to be describing:
![tmp](https://user-images.githubusercontent.com/7359272/48788389-a3393700-ece2-11e8-9a46-083aec884b68.jpg)
![signalling](https://user-images.githubusercontent.com/7359272/48788889-ae409700-ece3-11e8-808a-0d5d408c44e8.jpg)

The usual activity for a SH3 domain is to mediate protein protein interactions.
This is part of the story in explaining the mode of action for this signalling pathway. It doesn't seem to be what we think of  as being "complex assembly"?

**Comment by pgaudet** [comment]
Right - these terms represent binding, so protein complex assembly. It seems like many were created by InterPro - but not used. @asangrador do you know if you were planning to use these terms ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

GO:0071523 | TIR domain-mediated complex assembly
GO:0071530 | FHA domain-mediated complex assembly
GO:0071531 | Rel homology domain-mediated complex assembly
GO:0071533 | ankyrin repeat-mediated complex assembly
GO:0071534 | zf-TRAF domain-mediated complex assembly
GO:0071536 | RING-like zinc finger domain-mediated complex assembly
GO:0071537 | C3HC4-type RING finger domain-mediated complex assembly
GO:0071538 | SH2 domain-mediated complex assembly 
GO:0071552 | RIP homotypic interaction motif-mediated complex assembly
GO:0071571 | LRR domain-mediated complex assembly

----

The reason for obsoletion is that these terms represent functions (binding), not processes. 

There is a single EXP annotation to GO:0071538 SH2 domain-mediated complex assembly. There are no InterPro2GO mappings to these term; these terms are not included in any subset(s)(slims). 
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/16658

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 3rd, 2018. Unless objections are received by December 3rd, 2018, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @pgarmiri , 

No, GO:0065003 'protein-containing complex assembly' is not going away ! 

The terms listed above describe domains involved in protein-protein interactions, but no necessarily the process of assembling a complex. It is possible that the protein(s) for which you have changed the annotations *are* involved in complex assembly, but just make sure this is not just a binding before using that term. 

I hope this is clear ! 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
Thanks for the clarification. I had a closer look to the paper  and some others and I decided to remove the  annotation.
Thanks,
Penelope
