### ISSUE TITLE
NTRs: GPCAT (glycero-3-phosphocholine acyltransferase) activity, process

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#16665]
An expert contacted us to point out our annotation to GPC1/GO:0071617 transferase activity, transferring acyl groups other than amino-acyl groups is a step too far in the synthesis pathway and we need a NTR to capture the novel activity.  
Based off PMID: 27758859 (which this expert wrote), I'm requesting a NTR: glycerophosphocholine acyltransferase activity, a child term of GO:0016747 transferase activity, transferring acyl groups other than amino-acyl groups.

This also could use a new process term, something along the lines of 
'phosphatidylcholine biosynthetic process from glycerophosphocholine via lysophosphatidylcholine'.
I know that's complicated and rather Nocuta-esque, but it's in line with existing child terms of GO:0006656 phosphatidylcholine biosynthetic process and reflects a novel activity/process.

This reflects BRENDA's glycerophosphocholine O-acyltransferase: https://www.brenda-enzymes.org/enzyme.php?ecno=2.3.1.B36

Synonyms include (I'm not an expert, but based off our correspondence)
GPCAT activity 
glycerophosphocholine O-acyltransferase activity 
glycero-3-phosphocholine acyltransferase activity

**Comment by ukemi** [comment]
Also check Rhea please.

**Comment by hdrabkin** [comment]
Suggested def? written as "Catalysis of the reaction: a + b = C?

**Comment by ukemi** [comment]
Should be in the Brenda entry shouldn't it?

**Comment by hdrabkin** [comment]
No it is not; https://www.brenda-enzymes.org/enzyme.php?ecno=2.3.1.B36
Multiple substrates. Note this is NOT a real EC number; 
I have asked EC for it's real status

**Comment by ukemi** [comment]
Check out the natural substrates and the reaction diagram.

**Comment by hdrabkin** [comment]
I see it in Brenda now; blind as bat; Natural Substrates table.
however, EC wrote back on the status: "No, it does not have any status at the IUBMB. It is a preliminary EC number, that is, it is unique and describes a specific enzyme in contrast to partial EC numbers (e.g. EC 2.3.1.-) that describes enzymes for which we only have partial information. The idea is that the partial EC number should be submitted to IUBMB, but it is not always the evidence is solid enough for it to be included in the EC list. For the evidence to be solid enough, the enzyme has to have been purified or expressed in a well defined expression system, and all the major reactants have to be identified. This means that deletion studies is not enough to create an EC number."

So maybe with the PMID submitted with this ticket, I can push to get a full id.
Based on the Brenda Natural Substrates section, I can formulate a GO term and then submit to EC

**Comment by suzialeksander** [comment]
Sorry about omitting the def, I knew I forgot something.  Yes, going off BRENDA, some version of: (?)

acyl-CoA  + glycerophosphocholine  = CoA +  1-acyl-sn-glycero-3-phosphocholine

If it helps, the activity was also featured in
PMID:18430972 Identification of a novel GPCAT activity and a new pathway for phosphatidylcholine biosynthesis in S. cerevisiae
PMID:25298156 Novel reactions in acyl editing of phosphatidylcholine by lysophosphatidylcholine transacylase (LPCT) and acyl-CoA:glycerophosphocholine acyltransferase (GPCAT) activities in microsomal preparations of plant tissues

**Comment by hdrabkin** [comment]
GO:0106158
glycero-3-phosphocholine acyltransferase activity

**Comment by alanbridge** [comment]
we created a couple of reactions for this in Rhea recently, 

RHEA:58476 an acyl-CoA + sn-glycerol 3-phosphocholine = a 1-acyl-sn-glycero-3-phosphocholine + CoA

which is a

RHEA:58460 an acyl-CoA + sn-glycerol 3-phosphocholine = a monoacyl-sn-glycero-3-phosphocholine + CoA

**Comment by suzialeksander** [comment]
@hdrabkin Sorry for the delay.  Yes, I have confirmed with the author that the synonyms are all exact.
Thanks

**Comment by ValWood** [comment]
closing?

**Comment by hdrabkin** [comment]
Will add RHEA:58476 to this and I had already made the synonyms related so can change to exact while I'm in there and will close once done.

**Comment by hdrabkin** [comment]
done

**Comment by pgaudet** [comment]
I removed the BRENDA link as (1) it was not resolving on the BRENDA website and (2) it's not an official EC; https://www.brenda-enzymes.info/enzyme.php?ecno=2.3.1.B36

<img width="695" alt="image" src="https://user-images.githubusercontent.com/4782928/116404477-f22e1380-a82e-11eb-8771-168f62b60077.png">
