### ISSUE TITLE
taxon constraints

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16666]
GO:0019763    immunoglobulin receptor activity (never in fungi_)

**Comment by ValWood** [comment]
GO:0008188   neuropeptide receptor activity

**Comment by ValWood** [comment]
GO:0004925   prolactin receptor activity  (never in fungi_)

**Comment by ValWood** [comment]
nociceptin receptor activity (never in fungi_)
collectin receptor activity (never in fungi_)

**Comment by ukemi** [comment]
@balhoff, are we doing these via an external file now?

**Comment by balhoff** [comment]
@ukemi I am still working on wrapping up that PR. If you go ahead and add some in the ontology, that's fine since I will be querying out the latest from go-edit right before merging.
