### ISSUE TITLE
cargo loading into vesicle (GO:0035459) is_a complex assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16663]
cargo loading into vesicle (GO:0035459)

I guess becuse of the way it is defined

Definition | Parents

The formation of a macromolecular complex between the coat proteins and proteins and/or lipoproteins that are going to be transported by a vesicle.

It seems strange though....

**Comment by ukemi** [comment]
Seems ok to me.

**Comment by ValWood** [comment]
We wouldn't usually call the attachment of a cargo to something "complex-assembly" though.

This seems to be used to annotate a cargo receptor.  It still seems odd.
To annotate the complex you would need to annotate the complex+ it's transported substrates.

Are you sure that seems OK?

**Comment by ukemi** [comment]
If it isn't the assembly of the cargo-receptor complex, then what is it, just binding? It seems to me that it is a special kind of binding that results in the cargo-receptor complex. @vanaukenk would this be a strategy to handle the more types of contextual binding cases?

**Comment by ValWood** [comment]
I see, it's the is_a parent that's a problem.....it also has is_a transport, not sure if that is correct though?  maybe it is... but why is_a "transport" and part_of "vesicle-mediated transport"?

It still seems strange but now I think about it I remember questioning this before. I was just doing a quick check of our "protein complex assembly" annotations and this seems not quite right...

**Comment by ValWood** [comment]
Leave if you think its OK

**Comment by bmeldal** [comment]
a) It depends on how you define a complex and if the receptor is a multi-protein unit that only forms when the cargo is bound, as in many membrane signaling receptors ;-)

b) I think the term name is confusing. The def describes essentially the docking of cargo to the vesicle coat proteins but the term name suggests it's the movement of the cargo INTO the vesicle.
