### ISSUE TITLE
parentage query GO:2000144    positive regulation of DNA-templated transcription, initiation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16661]
GO:2000144    positive regulation of DNA-templated transcription, initiation
is a descendant of
GO:0031334    positive regulation of protein complex assembly

is that correct, it seems odd.

this would imply that ALL "transcription initiation" is "protein complex assembly"?

**Comment by ValWood** [comment]
I could only find this relationship in QUickOG but not  when I use our query tool. Maybe it is coming from some weird inference?

**Comment by cmungall** [comment]
Currently asserted in go-edit, not inferred

However, it is an early TG term. We used to assert inferences so this is likely a stale assertion from a long-gone axiom. We should clean these up.
