### ISSUE TITLE
NTR: Negative regulation of hemidesmosome disassembly

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#16676]
Hi,
New term requested: Negative regulation of hemidesmosome disassembly.
Definition: Any process that stops, prevents or reduces the frequency, rate or extent  of hemidesmosome disassembly.
This term request is supported by Figure 5 in  PMID: 23611113. They show that  Necl-4 inhibits the TPA-induced hemidesmosome disassembly.
The parent term  should be: hemidesmosome disassembly (which doesn't exist yet. See my other request).
There is already a term for: hemidesmosome assembly (GO:0031581).

Thanks,
Mila

**Comment by vanaukenk** [comment]
@milarolo - how much is known about the mechanism whereby Necl-4 inhibits TPA-induced hemidesmosome disassembly?
We are trying to move towards an annotation practice whereby use of a regulation term would indicate that the molecular mechanism is known.
Would it be possible in this case to annotate Necl-4 to 'casually upstream of or within, negative effect' 'hemidesmosome disassembly'?
The last statement in the Discussion is partly what prompted my question:
"Thus, evidence has accumulated that Necl‐4 plays roles in regulating a variety of cellular functions, but the molecular mechanisms for these roles of Necl‐4 remain unknown, and it also remains unknown if these roles of Necl‐4 are mediated through its interaction with ErbB3 and integrin α6β4."

**Comment by milarolo** [comment]
Thank you very much for your response. I didn't know about that change with the regulation terms ("We are trying to move towards an annotation practice whereby use of a regulation term would indicate that the molecular mechanism is known."). I commented about it in the office, but they were also unaware. Is there any documentation about it that we have missed?
Anyway if this  is the case, I agree with you and I will use the term "hemidesmosome disassembly" with the qualifier "acts_upstream_of_or_within_negative_effect"
There is no "hemidesmosome disassembly" term so I have already requested it (#16677)
Thank  you,
Mila

**Comment by ukemi** [comment]
Does NECL4 really regulate the disassembly, or does it stabilize the hemidesmosome? It seems from the paper that in the absence of NECL4, which interacts with the integrin complex, the hemidesmosome disassembles. I'm not convinced that hemidesmosome disassembly is really a process that is actively achieved by the action of gene products.

**Comment by ValWood** [comment]
Closing as "out of scope"
