### ISSUE TITLE
NTR: Hemidesmosome disassembly

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#16677]
Hi,
New term requested: Hemidesmosome disassembly
Definition:  Disassembly of hemidesmosomes, integrin-containing protein complexes that bind to laminin in the basal lamina. Hemidesmosomes form the contact between the basal surface of epithelial cells and the underlying basal lamina.

Parent term: Cell junction organization (GO:0034330)
There is already a term for: Hemidesmosome assembly (GO:0031581)

This request is linked with the request for: Negative regulation of hemidesmosome disassembly.
PMID: 23611113, Fig: 5

Thanks,
Mila

**Comment by ValWood** [comment]
Is this still current?

**Comment by ValWood** [comment]
Seems out of scope.
https://github.com/geneontology/go-ontology/issues/16676
