### ISSUE TITLE
Toll vs TLR

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#16672]
Insect toll receptor/toll receptor-like signaling is currently in its own branch, separate from toll receptor-like signaling. This was done based on  #3293

The reason for this decision was based on the some differences between the pathway activation:

In insects, toll receptor signaling is associated with embryonic dorsoventral patterning and innate immunity. It is activated by the binding of spatzle, a ligand that lies downstream of several different proteolytic cascades, including some initiated by pathogenic entities.
In vertebrates and other invertebrates, toll signaling is directly activated by direct binding of pathogenic molecules - so TLRs are acting as direct pattern recognition receptors.

Currently, TLR signaling pathways are classied into two distinct types - the myeloid differentiation primary response protein 88 (MyD88)-dependent pathways (also known as the canonical toll or toll-MyD88-NF-kappaB) and the TIR domain-containing adaptor-inducing IFNβ (TRIF)-dependent pathways. MyD88-dependent pathway is downstream of by almost all the TLRs.

Many of the TLRs are uncharacterised and there is some evidence that TLRs can act in other contexts besides DV patterning and innate immunity. There may well be other downstream pathways and some TLRs have been shown to mediate homophilic cell-cell adhesion.

PMID:30034391 Toll-Like Receptors, Associated Biological Roles, and Signaling Networks in Non-Mammals.
PMID:26150191 Different flavors of Toll guide olfaction.

So currently we have:
Toll signaling pathway GO:0008063 "A series of molecular signals initiated by the binding of an extracellular ligand to the receptor Toll on the surface of a target cell, and ending with regulation of a downstream cellular process, e.g. transcription."
toll-like receptor signaling pathway GO:0002224 "Any series of molecular signals generated as a consequence of binding to a toll-like receptor. Toll-like receptors directly bind pattern motifs from a variety of microbial sources to initiate innate immune response." 

toll-like receptor signaling pathway GO:0002224 has many children - some downstream pathway specific, some receptor-specific. This term is under "pattern recognition receptor signaling pathway" - "innate immune response-activating signal transduction".

This pattern in the GO is problematic, not least as we have gene-specific GO terms. Any insect Toll/TLR signaling pathway component will probably have to live under "Toll signaling pathway GO:0008063" as it is activated by spatzle or a similar ligand - even is this is part of the innate immune response. So, although the ligands may be different, the context is the same and the downstream pathway is the same and the receptor may be a TLR.

It would be good if we could fix this, whilst maintaining some of the innate immunity links.

There are a number of options/routes that we could follow:

1. Define the pathway by activator (e.g. TLR pattern-recognition activated signaling pathway, TLR endogenous ligand-activated signaling pathway. TLR homotypic....)
2. Define the pathway by the intracellular signaling module (we currently have these: GO:0002755	MyD88-dependent toll-like receptor signaling pathway, GO:0002756 MyD88-independent toll-like receptor signaling pathway, GO:0035664 TIRAP-dependent toll-like receptor signaling pathway)
3. Define the pathway by process context not by ligand: TLR signaling pathway involved in innate immune response, TLR signaling pathway involved in development
4. Define the pathway by the receptor and downstream signaling modules using extensions and co-annotation to describe the context.

These all have their issues, but I am sure that we do need a parent term for all toll/TLR signaling because that is the one common thread.

For spatzle-activate TLR pathways, I wonder if the protease cascades should be defined as separate pathways, so that the start point of Toll/TLR starts with ligand-receptor binding for all, rather than having a different start point.

**Comment by hattrill** [comment]
![screen shot 2018-11-21 at 09 17 20](https://user-images.githubusercontent.com/11865746/48847598-dbe81780-ed99-11e8-9d15-e9938b5a2150.png)
![screen shot 2018-11-21 at 14 30 06](https://user-images.githubusercontent.com/11865746/48847635-f7ebb900-ed99-11e8-8ccf-3dbc09c28616.png)

**Comment by hattrill** [comment]
Note: pattern recognition receptor pathways are a bit of a mess too.

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/issues/16615
https://github.com/geneontology/go-ontology/issues/16616
https://github.com/geneontology/go-ontology/issues/16620

**Comment by hattrill** [comment]
![Screenshot 2019-10-29 at 12 02 36](https://user-images.githubusercontent.com/11865746/67765640-85bd3300-fa44-11e9-84dc-046d8e894ccd.png)

**Comment by addiehl** [comment]
I've always argued to treat the insect toll pathway and the TLR pathways as separate systems despite some homologous components because of their differences in activation and downstream effects, per the 2006 issue cited above.

**Comment by hattrill** [comment]
But I don't think that division really works that well. It's very inflexible, could be potentially confusing for users of the GO and, as many elements of the pathway are conserved, really doesn't help cross-species comparison. Perhaps insects are the only species in which spatzle activates toll-signaling, but spatzles have been found in other invertebrates and have immune roles (molluscs - PMID:26477575, shrimp - PMID:31417561, PMID:21827783) and D.mel Toll and Toll-7 have also been shown to bind to virions (PMID:31088910). Invertebrates have been found to possess TLR that fall into the vertebrate-type and the protostome-type TLRs, that latter may bind PAMPs directly or maybe activated indirectly, like D.mel Toll, and there are huge variations in the number of TLRs in species (c.elegans has one, sea urchins 100s (PMID:30034391). Additionally, there is evidence suggesting that TLRs may also have roles in development (PMID:11025209, PMID:26279230, PMID:29109290).
![Screenshot 2019-10-30 at 10 32 08](https://user-images.githubusercontent.com/11865746/67852070-a4363380-fb03-11e9-8348-82d5d61643ee.png)

The current situation is confusing - the D.mel toll pathway has the conserved Myd88 module of signaling, but we have no mechanism of linking this to 'MyD88-dependent toll-like receptor signaling pathway' and Toll signaling in drosophila can be activated by extracellular PRRs such as peptidoglycan recognition proteins, but would not be found under a PRR signaling term. Minimally, there should be a generic term that can be used when the activator/downstream axis is not clear. And we should probably do anyway with receptor-specific terms 'toll-like receptor 15 signaling pathway' and 'toll-like receptor 15 signaling pathway')...both used for once for a TAS from reactome.

Mechanistically, there are four well-characterised TLR-signaling modes; two well-characterised mechanisms of activation (direct PRR by the TLR or binding a cytokine (that may be the product of a immune detection)) and two major biological roles (innate immunity and development) and I should think that probably encapsulates what a user might want to differentiate when they do a query.

![Screenshot 2019-10-30 at 11 14 22](https://user-images.githubusercontent.com/11865746/67853441-77375000-fb06-11e9-8064-707c9bac4024.png)
![Screenshot 2019-10-30 at 10 07 48](https://user-images.githubusercontent.com/11865746/67852579-92a15b80-fb04-11e9-91fa-9c22b32f7fa6.png)
![Screenshot 2019-10-30 at 09 01 52](https://user-images.githubusercontent.com/11865746/67852595-992fd300-fb04-11e9-8edb-dc3e260872c9.png)

**Comment by addiehl** [comment]
I would be in favor of common terms for things like MyD88 signaling pathways.  There is a term 'MyD88-dependent toll-like receptor signaling pathway' already for the TLR version of this.  I would agree that this ought to be renamed and redefined as 'MyD88-dependent toll-like receptor signaling pathway involved in innate immunity'. Perhaps a more general parent could be created for instance that covers non-immune signaling pathways.

Sorry to be so narrow minded about this, but when the TLR terms were created in 2006 I didn't want them subsumed under an insect signaling paradigm, particularly as their biology was already well worked out and distinct, and they are incredibly important for the functioning of the human immune system (and those of other vertebrates).  As I can see that the biology of non-mammalian TLRs is far more worked out now, I favor a more expansive approach as you are asking for.  I look forward to seeing a proposal that incorporates elements of points 1, 2, and 3 above.

**Comment by hattrill** [comment]
I'll have a go at coming up with a sketch of an insect-human GO-utopia in the next couple of weeks....it's a difficult one!

**Comment by hattrill** [comment]
have worked around using other changes so closing this
