### ISSUE TITLE
Add curation usage comments for transcription factor (GO:0003700) and cofactor (GO:0003712) activities

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16673]
The transcription working group looked at some annotation errors that mix up DNA binding transcription factor activity (GO:0003700) transcription coregulator activity (GO:0003712) and we plan to add the following comments to clarify the intended usage of the terms: 

**GO:0003700 DNA binding transcription factor activity**
- Definition: A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a gene to modulate transcription. Regulatory regions include promoters (proximal and distal) and enhancers. Genes are transcriptional units, and include bacterial operons.

**Add the following comment:** Note that most DNA binding transcription factors do not have enzymatic activity. If a protein has an enzymatic activity (for example, ubiquitin ligase, histone acetyl transferase), consider annotating to GO:0003712 transcription coregulator activity. The presence of specific domains known to be present in transcription factors (HOX, GATA etc) should be used to help decide whether a protein is a DNA binding transcription factor or a coregulator. 

----

**GO:0003712 transcription coregulator activity**
- Definition:  A protein or a member of a complex that interacts specifically and non-covalently with a DNA-bound DNA-binding transcription factor to either activate or repress the transcription of specific genes. Coregulators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second ATP-dependent class modifies the conformation of chromatin. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators. 

**Add the following comment:**  Most transcription coregulators do not bind DNA. Those that do usually bind DNA either in a non-specific or non-direct manner. If a protein binds DNA specifically, consider annotating to GO:0003700 DNA binding transcription factor activity. 

Does that seem ok ? 

@ValWood @RLovering @mlacencio

**Comment by RLovering** [comment]
did you mean to say the last line: If a protein binds DNA specifically, consider annotating to GO:0003700 DNA binding transcription factor activity. or should this be: If a protein binds DNA specifically, consider annotating to GO:0003700 DNA binding transcription factor activity (or child term)?

Also add (or child term) to the comments section of GO:0003700 DNA binding transcription factor activity to read: ....GO:0003712 transcription coregulator activity (or child term)

Thanks

Ruth

**Comment by pgaudet** [comment]
Updated comment based on more feedback from Marcio:

Curator guidance: Note that most DNA-binding transcription factors do not have enzymatic activity. The presence of specific domains known to be present in DNA-binding transcription factors (HOX, GATA etc) should be used to help decide whether a protein is a DNA binding transcription factor or a coregulator. If a protein has an enzymatic activity (for example, ubiquitin ligase, histone acetyl transferase) and no known DNA binding domain, consider annotating to GO:0003712 transcription coregulator activity. Special care should be taken with proteins containing Myb/SANT and ARID domains, since only a subset of proteins containing these domains are DNA-binding transcription factors for specific genes. 

Pascale
