### ISSUE TITLE
Protein mono-ADP-ribosylation and protein poly-ADP-ribosylation

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#16680]
Hi,
I would need two new process terms to discriminate between mono-ADP-ribosylation and poly-ADP-ribosylation

GO:xxxxxxx protein mono-ADP-ribosylation
Definition: The transfer, from NAD, of a single (mono) ADP-ribose molecule to protein amino acids. 
child of GO:0006471 protein ADP-ribosylation IDA
PMID:25043379

GO:xxxxxxx protein poly-ADP-ribosylation
Definition: The transfer, from NAD, of a polymer of ADP-ribose molecules to protein amino acids, building up a polymer with an average chain length of 20-30 units. 
child of GO:0006471 protein ADP-ribosylation IDA
PMID:25043379

**Comment by pgaudet** [comment]
@sylvainpoux,  protein poly-ADP-ribosylation already exists: GO:0070212
I added the reference.
