### ISSUE TITLE
NTR peptidyl-arginine 3-dioxygenase activity

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#16689]
Could we have a new MF term for peptidyl-arginine 3-dioxygenase activity. The new term would be a sibling to peptidyl-lysine 3-dioxygenase activity #16632 (now GO:0106155 peptidyl-lysine 3-dioxygenase activity).

The reference for the new request is PMID 29563586. Proposed def: Catalysis of the reaction: protein L-arginine + 2-oxoglutarate + O2 = protein 3-hydroxy-L-arginine + succinate + CO2.

I think this is distinct from  GO:0102525 2-oxoglutarate, L-arginine oxygenase (succinate-forming) activity because that term looks like activity on free arginine while this one would apply to arginine residues in peptides.

**Comment by hdrabkin** [comment]
Same ref as 16632?

**Comment by deustp01** [comment]
No - 16632 (peptidyl-lysine-etc.) was PMID:29915238. This one is PMID:29563586. I'll e-mail you a PDF copy separately.

**Comment by hdrabkin** [comment]
oops; committed already; will need to fix separetly; I didn't notice the PMID  here; argh

**Comment by hdrabkin** [comment]
Done along with 16632 
id: GO:0106156
+name: peptidyl-lysine 4-dioxygenase activity

+id: GO:0106157
+name: peptidyl-arginine 3-dioxygenase activity

**Comment by hdrabkin** [comment]
RHEA for GO:0106157 is RHEA:56744  Already exists for GO:0140554 SAME reaction but a different name (L-arginine 3-hydrolyase activity)  (not indicating protein/peptide. );

RHEA for GO:0106156 is RHEA:57156

**Comment by hdrabkin** [comment]
This slipped by me. Merge done.

**Comment by pgaudet** [comment]
Added EC:1.14.11.73
