### ISSUE TITLE
untraceable ontology changes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16687]
For the past 2 days  our "slimmed" annotation have changed substantially.
This does not appear to be due to a single cause.

This list (annotated to a process but unslimmed) usually has ~20 entries. Today it is 60. I think it was even higher yesterday.

Here are some oddities:

dad1 | SPAC16A10.05c | DASH complex subunit Dad1
dad2 | SPAC1805.07c | DASH complex subunit Dad2
dad3 | SPAC14C4.16 | DASH complex subunit Dad3
dad4 | SPBC3B9.22c | DASH complex subunit Dad4
dad5 | SPCC417.02 | DASH complex subunit Dad5
dam1 | SPAC589.08c | DASH complex subunit Dam1
duo1 | SPBC32F12.08c | DASH complex subunit Duo1

All of these are annotated to

mitotic sister chromatid biorientation

which should slim to
mitotic sister chromatid segregation | GO:0000070 | 157
but no longer does

and it still appears to have this parent 
https://www.ebi.ac.uk/QuickGO/term/GO:1990758
so I'm stumped ?

@kimrutherford 
@mah11 
any clue ?

**Comment by ValWood** [comment]
also exo84
https://www.pombase.org/gene/SPAC6F12.08c

vesicle tethering involved in exocytosis
no longer slims to vesicle-mediated transport

**Comment by balhoff** [comment]
@ValWood do you use `go.owl`, or `go-plus.owl`? Wondering if I've messed you up via this: #16688

**Comment by ValWood** [comment]
I'm not sure. I thought go-basic, but we might have switched... @kimrutherford ?

**Comment by kimrutherford** [comment]
It looks like a new go-basic.obo has come out of the pipeline.  The "data-version" has changed.

But there is only a one line change in the file and it seems unrelated to Val's problem.

Should we wait a bit longer or do you think the axiom change didn't fix things?

**Comment by balhoff** [comment]
@kimrutherford the version on date `2018-11-25` includes the corrected axioms. Can you check which one you're looking at? When I loaded into Protege to check, it initially downloaded the previous day release, I guess due to caching somewhere.

**Comment by ukemi** [comment]
I think @balhoff is correct.

In the current editors' version of the ontology:

If I look at 'mitotic sister chromatid biorientation', it is asserted to be 'attachment of mitotic spindle microtubules to kinetochore'. 

'attachment of mitotic spindle microtubules to kinetochore' is defined as: 'attachment of spindle microtubules to kinetochore' and ('part of' some 'mitotic metaphase plate congression').

'mitotic metaphase plate congression' is asserted to be 'part of' some 'mitotic sister chromatid segregation' which would make it slim.

Are we somehow missing the 'part_of' declarations that are in the equivalence axioms when we generate the basic file?

**Comment by balhoff** [comment]
I was guessing that `owltools` is relying on the transitivity of `part of` for OWL reasoning, and this was missing.

**Comment by ukemi** [comment]
OK. This should be resolved then. Val and Kim, can you double-check and let us know? Then we can close this ticket.

**Comment by ValWood** [comment]
As of this morning it wasn't fixed. We expected the change to have propagated. We'll need to wait for Kim to come back online to check but for us it didn't yet fix.

**Comment by kimrutherford** [comment]
Thanks you both.

I've got the 2018-11-25 go-basic now and the closure output from owltools has the part_of relation that was missing.

@ValWood It will be in www.pombase.org in the morning.

**Comment by ukemi** [comment]
Yay! Thanks everyone!

**Comment by ValWood** [comment]
reopening because I'm getting a new error which seems that it could be related to this (manifests the same in Canto).

![untitled](https://user-images.githubusercontent.com/7359272/49591017-30c48a00-f965-11e8-98bd-38abf1a148f7.jpg)

the annotation is, in fact, incorrect (it's a phenotype), so I will delete it. However, I can't see from the current taxon constraints why it would not be available to us (in fact it was there when I first looked at this curation session yesterday or the day before).

Cheers

Val

**Comment by pgaudet** [comment]
Is there apoptosis in pombe ? This term has a taxon constraint: 

GO:0006915 | apoptotic process | Only in Taxon | 33154 | Opisthokonta

**Comment by mah11** [comment]
Opisthokonta includes Fungi, so that _shouldn't_ be the problem ...

**Comment by pgaudet** [comment]
Oh ! never mind !

**Comment by mah11** [comment]
... but it does look like PomBase Canto hasn't loaded GO:0006915 either, so something's up, tho I can't tell whether it's that taxon constraint or something different.

**Comment by ukemi** [comment]
I just looked in Protege with @balhoff. We couldn't see a taxon constraint on this term when we queried. Are you sure it's not something on your end?

**Comment by ValWood** [comment]
It could be, but it wasn't last time ;) and *as far as I know* we didn't change anything.

Kim @kimrutherford  will check our end when he comes online tonight.

**Comment by kimrutherford** [comment]
> It could be, but it wasn't last time ;) and as far as I know we didn't change anything.

I think it's a different problem this time.

I had a look at the pombe taxon restricted OBO file generated by owtools.  Oddly, the stanza for GO:0006915 has no name:

```
[Term]
id: GO:0006915
alt_id: GO:0006917
alt_id: GO:0008632
```

Canto OBO loader ignores terms without names.  I hadn't noticed the problem in the logs.

We have been using an old version of owtools so I thought I'd try the latest owltools from git master branch.  With that version, GO:0006915 doesn't appear the output file at all.

The taxon constraints look OK to me too so I'm stumped.

**Comment by ValWood** [comment]
GO:0043653  is still unavailable to us.

**Comment by ValWood** [comment]
I still can't access apoptosis related terms even though they should not be taxon restricted.

VAL

**Comment by ValWood** [comment]
Actually this isn't the correct ticket for this issue is it? This was another problem... But I can't find the original ticket

**Comment by ValWood** [comment]
re-closing and opening a new ticket. I still can't locate the ticket where I reported the problem recently?
