### ISSUE TITLE
NTR peptidyl-lysine 4-dioxygenase activity

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#16692]
Could we have a new MF term for peptidyl-lysine 4-dioxygenase activity. The new term would be a sibling to peptidyl-lysine 3-dioxygenase activity #16632 (now GO:0106155 peptidyl-lysine 3-dioxygenase activity) and to the peptidyl-arginine dioxygenase activity term requested yesterday on ticket 16689.

The reference for the new request is PMID 24486019. Proposed def: Catalysis of the reaction: protein L-lysine + 2-oxoglutarate + O2 = protein 4-hydroxy-L-lysine + succinate + CO2.

**Comment by hdrabkin** [comment]
Done along with 16632
id: GO:0106156
+name: peptidyl-lysine 4-dioxygenase activity

+id: GO:0106157
+name: peptidyl-arginine 3-dioxygenase activity
