### ISSUE TITLE
new term: chemosynthesis

### ISSUE THREAD

**Issue by diatomsRcool** [geneontology/go-ontology#16709]
chemosynthesis

the biological conversion of one or more carbon-containing molecules (usually carbon dioxide or methane) and nutrients into organic matter using the oxidation of inorganic compounds (e.g., hydrogen gas, hydrogen sulfide) or methane as a source of energy, rather than sunlight, as in photosynthesis.

https://en.wikipedia.org/wiki/Chemosynthesis

child of 'cellular metabolic process'

http://orcid.org/0000-0002-2908-3327

**Comment by ukemi** [comment]
Since I used to be a caver I am going to use PMID:25050523 as a literature reference for this term. Let me know if you have a better one.

**Comment by ukemi** [comment]
This term might also be a nice test case for our new procedure for adding taxon restriction in the ontology. Can you suggest any taxon restrictions we might want to add?

**Comment by ukemi** [comment]
I also tweaked the definition to make it similar to our definition for photosynthesis. Please comment if it is not satisfactory.

**Comment by diatomsRcool** [comment]
When a taxon restriction is added, does that include all members of a taxon or does it just exclude non-members?

**Comment by diatomsRcool** [comment]
definition looks good to me

**Comment by balhoff** [comment]
@diatomsRcool it would be a statement like "every instance of chemosynthesis is a member of taxon X" (chemosynthesis is only found in X and nowhere else) or "every instance of chemosynthesis is not a member of taxon Y" (chemosynthesis is never found in Y).

**Comment by ukemi** [comment]
Thanks @diatomsRcool. And we would like taxon restrictions to be complete if possible. So saying it is never in animals even though it is never in plants would be correct, but incomplete.

**Comment by diatomsRcool** [comment]
OK, here's the sticky bit. We could say that chemosynthesis is never found in eukaryotes BUT there are eukaryotes that have chemosynthetic bacteria as symbionts. In the case of the deep sea tube worm, the chemosynthetic symbiont has taken the place of the gut as the way to gain nourishment. The symbiosis is obligatory. So, would we then say that these worms are chemosynthetic eukaryotes? What would be the implication for other such associations, such as termites and cellulose-digesting gut bacteria? Lichens?
I'm inclined to model this very specifically, linking chemosynthesis to the bacteria and then linking the bacteria to the worm in an obligate symbiosis, but I can be convinced otherwise.

**Comment by ukemi** [comment]
I think I agree with you. The chemosynthesis occurs in the bacteria and would use gene products encoded by the bacterial genome. When I was creating the term I was under the impression it also occurred in some fungi. Is that correct?

**Comment by diatomsRcool** [comment]
I can't find any definitive evidence that a fungi can perform chemosynthesis, but there is a group of fungi wherein it is a possibility, but uncertain at this time. How would you like to handle that? For now, just say that no fungi can perform chemosynthesis?

**Comment by diatomsRcool** [comment]
Oh, and I found this https://en.wikipedia.org/wiki/Radiotrophic_fungus
You may want to also add "radiosynthesis"!

**Comment by diatomsRcool** [comment]
I think it can be in archaea too

**Comment by ukemi** [comment]
So 'only in prokaryota', which includes archaea and bacteria?

**Comment by diatomsRcool** [comment]
Yes
