### ISSUE TITLE
ntr: processes in meiotic chromosome organization

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16704]
We've received what amounts to a GO term request from Ayumu Yamamoto, who is doing community curation for PMID:27611693:

"We reported that a Taz1 fragment can induce centromere detachment from the SPB and kinetochore disassembly when it is artificially recruited to the SPB. ... I could not find appropriate terms for this."

I haven't gone through the paper in depth, but I gather from what I have read of it that both processes are normal parts of the reorganization that puts chromosomes into the orientation characteristic of meiotic nuclear divisions, and that the fragment mentioned in the request is a construct used to test the normal role of Taz1. @ValWood may know more than I do about the broader processes, and we can also put you in touch with Ayumu directly if you have questions.

In the stanzas below, I've put the details I've been able to suss out, plus some questions and comments about the parts I'm less sure of:

id: GO:new1
name: centromere detachment from spindle pole body involved in meiotic chromosome organization
def: The cell cycle process in which centromeres dissociate from the spindle pole body, contributing to the rearrangement of chromosomes into the orientation characteristic of meiotic prophase I. [GOC:mah,PMID:27611693]
synonym: "centromere detachment from SPB involved in meiotic chromosome organization" EXACT []
synonym: "centromere detachment from spindle pole body involved in chromosome organization involved in meiotic cell cycle" EXACT []
is_a: GO:0070192 ! chromosome organization involved in meiotic cell cycle
* some relationship to GO:1990571 ! meiotic centromere clustering ?
- centromeres have to detach from the SPB to be able to cluster away from it during meiosis, but whether the link is really part_of or "precedes & required for" isn't totally clear to me. 
- GO:0045141 ! meiotic telomere clustering also precedes GO:new1 - from the paper intro: centromeres are located at the SPB during mitotic interphase. Upon entering meiosis, telomeres cluster at the SPB, followed by centromere detachment from the SPB.

id: GO:new2
name: kinetochore disassembly involved in meiotic chromosome organization
def: The cell cycle process in which outer kinetochore components delocalize from the centromere, contributing to the rearrangement of chromosomes into the orientation characteristic of meiotic prophase I. [GOC:mah,PMID:27611693]
synonym: "kinetochore disassembly from spindle pole body involved in chromosome organization involved in meiotic cell cycle" EXACT []
is_a: GO:0070192 ! chromosome organization involved in meiotic cell cycle
- I guess this term could be made specific for the outer kinetochore (I have no strong preference)
- Similar considerations for additional parentage as for GO:new1

**Comment by srengel** [comment]
all sorts of proteins will mess up all sorts of processes is they are artificially recruited to the wrong place.  is this really something to capture in the GO?

**Comment by mah11** [comment]
1. My understanding (subject to correction) is that under normal circumstances, Taz1 does end up near the SPB because telomeres with Taz1 bound move close to where centromeres already are; the artificial construct was used to mimic this normal proximity, and thereby test what Taz1 does when it's near the SPB.

2. Even if 1 is wrong, that would be an argument only against annotating Taz1 to one or both new terms. It seems to be pretty well established that the processes occur in normal cells, so there isn't an artificial-recruitment argument against having the terms.

**Comment by ValWood** [comment]
I thought that initially when I saw the helpdesk ticket,
but this is just a clever experiment to dissect a normal process

"Efficient centromere detachment required telomere clustering-dependent SPB recruitment of a conserved telomere component, Taz1, and microtubules. Furthermore, when artificial SPB recruitment of Taz1 induced centromere detachment in telomere clustering-defective cells, spindle formation was impaired."

The chromosome segregation people create lots of clever assays like this. I haven't read this particular paper yet but it's a normal process anyway...

**Comment by mah11** [comment]
ping .... any word on this one? it's for one of our community curators.

**Comment by hdrabkin** [comment]
Hi @ValWood , it looks like you think these are ok (as a far greater expert on this than I)?

**Comment by ValWood** [comment]
Yes, it's a normal process. It's too early to tell if this would end up being captured by a molecular function, but we can always move later.

**Comment by hdrabkin** [comment]
GO:0106212
+name: centromere detachment from spindle pole body involved in meiotic chromosome organization
GO:0106213
+name: kinetochore disassembly involved in meiotic chromosome organization

terms are in; can add other relationships if needed later.
