### ISSUE TITLE
NTR: Complement component C3c binding

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#16710]
Hi,
New term requested: "Complement component C3c binding"
Parent term: GO:0001848: "Complement binding"
There is already a group of terms: GO:0001850/ GO:0001851/  GO:0001852/ GO:0001853/ GO:0001854 "Complement component (C3a, C3b, iC3b, C3dg, C3d) binding"
Supported by: PMID:  17051150, Fig:1B, there is also a structure in PDBe:  2ice

Thank you,
Mila

**Comment by pgaudet** [comment]
Out of date
