### ISSUE TITLE
Merge GO:0001085 RNA polymerase II transcription factor binding into GO:0061629 RNA polymerase II-specific DNA-binding transcription factor binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16716]
Or obsolete, depending on whether annotations are consistent

134 EXP annotations -> need to be reviewed

**Comment by ValWood** [comment]
I haven't looked  (we no longer use/never used GO:0001085)  but this merge sounds unsafe.... I have a feeling the original meaning (before obsoletions)  encompasses protein binding trancription factors too (i.e coregulators, and general TFs)

**Comment by pgaudet** [comment]
I think you are probably right

**Comment by pgaudet** [comment]
Done in #20409
