### ISSUE TITLE
molecular adaptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16721]
should protein membrane anchor
https://www.ebi.ac.uk/QuickGO/term/GO:0043495

have this parentage?

**Comment by pgaudet** [comment]
Shouldn't it ? This comes from discussions with @thomaspd

**Comment by ValWood** [comment]
It doesn't? I think it should...

**Comment by ValWood** [comment]
i.e. add "molecular adaptor activity"
parent to "protein membrane anchor"

**Comment by pgaudet** [comment]
AH !! got it. I'll add it.

**Comment by pgaudet** [comment]
In fact, shouldn't protein membrane anchor be a child of 'GO:0030674 protein binding, bridging'?

**Comment by ValWood** [comment]
No because the membrane anchor is defined as binding to a lipid and a protein...

**Comment by pgaudet** [comment]
Yeah but protein binding, bridging is 'a protein and another molecule (not necessarily a protein)

**Comment by ValWood** [comment]
Ah OK, it can then. I always thought "protein binding,bridging" needed 2 protein IDs in the "with" field.
