### ISSUE TITLE
taxon restrictions, never in fungi

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16722]
please add to

00336521
0030964
0035994
0014840
0035995
0014864
0014870
0014869
0046716
0120079
0007014
0061302
0014719
0090078
2000097
0120080
0120081
0051767
1902947
1902948
1902949
0031547
0031548
0031549
0031550
0044369
1902217
1902251
1902252
0097699
0097700
0097705
0097706
1900003
1900004
1900005
0038065
0038063
0006789

**Comment by hdrabkin** [comment]
Hey @ValWood ; should 1digit  be dropped from this?
00336521

**Comment by hdrabkin** [comment]
@ValWood 
can you please supply this list in a tab-delimited file with the GO term? Thanks

**Comment by hdrabkin** [comment]
@ValWood 
Cannot find GO:0014840 in current go-edit.obo file

**Comment by ValWood** [comment]
Argh, yes. But which one ;(

**Comment by ValWood** [comment]
Got it
GO:0033651 - host cell plastid

**Comment by ValWood** [comment]
--
GO:0090078 | smooth muscle derived foam cell differentiation |  
GO:0038065 | collagen-activated signaling pathway |  
GO:0038063 | collagen-activated tyrosine kinase receptor signaling pathway |  
GO:0031550 | positive regulation of brain-derived neurotrophic factor receptor signaling pathway |  
GO:0031549 | negative regulation of brain-derived neurotrophic factor receptor signaling pathway |  
GO:0031547 | brain-derived neurotrophic factor receptor signaling pathway |  
GO:0031548 | regulation of brain-derived neurotrophic factor receptor signaling pathway |  
GO:0006789 | bilirubin conjugation |  
GO:0051767 | nitric-oxide synthase biosynthetic process |  
GO:0014719 | skeletal muscle satellite cell activation |  
GO:2000097 | regulation of smooth muscle cell-matrix adhesion |  
GO:0035994 | response to muscle stretch |  
GO:0035995 | detection of muscle stretch |  
GO:0030964 | NADH dehydrogenase complex |  
GO:0033651 | host cell plastid |  
GO:1902949 | positive regulation of tau-protein kinase activity |  
GO:1902947 | regulation of tau-protein kinase activity |  
GO:1902948 | negative regulation of tau-protein kinase activity |  
GO:0061302 | smooth muscle cell-matrix adhesion |  
GO:1902251 | negative regulation of erythrocyte apoptotic process |  
GO:1902252 | positive regulation of erythrocyte apoptotic process |  
GO:0120079 | regulation of microfilament motor activity |  
GO:0120080 | negative regulation of microfilament motor activity |  
GO:0120081 | positive regulation of microfilament motor activity |  
GO:0097699 | vascular endothelial cell response to fluid shear stress |  
GO:0014870 | response to muscle inactivity |  
GO:0014869 | detection of muscle inactivity |  
GO:0014864 | detection of muscle activity |  
GO:1902217 | erythrocyte apoptotic process |  
GO:0097700 | vascular endothelial cell response to laminar fluid shear stress |  
GO:0097706 | vascular endothelial cell response to oscillatory fluid shear stress |  
GO:0097705 | vascular endothelial cell response to pulsatile fluid shear stress |  
GO:1900003 | regulation of serine-type endopeptidase activity |  
GO:1900005 | positive regulation of serine-type endopeptidase activity |  
GO:1900004 | negative regulation of serine-type endopeptidase activity |  
GO:0007014 | actin ubiquitination |  
GO:0046716 | muscle cell cellular homeostasis |  
GO:0044369 | feeding on blood of other organism

**Comment by ValWood** [comment]
I alsoreduced the list. Some were  narrow synonyms

**Comment by hdrabkin** [comment]
ok; @uberon  I have made a tab-deliminted file to append to the .tsv

**Comment by hdrabkin** [comment]
[val-taxon.txt](https://github.com/geneontology/go-ontology/files/2640516/val-taxon.txt)

**Comment by balhoff** [comment]
@ValWood sorry about the delay on this, I think it got tied up in some taxon restriction revisions that @thomaspd and I are working on. But I don't think the timeframe for getting that done makes sense to hold this ticket up—we should just add these in the current way, if the editors have approved.

**Comment by ukemi** [comment]
It seems that @hdrabkin made a file that can simply be appended to the current tsv file.

**Comment by ValWood** [comment]
OK, would be good to get these through.

**Comment by hdrabkin** [comment]
I thought I passed that file on to @thomaspd? Quite a while ago

**Comment by ukemi** [comment]
It is in this ticket in the comment above.

**Comment by ukemi** [comment]
I will just reassign this to @hdrabkin then. He can just paste the tsv at the end and regenerate the import.

**Comment by ukemi** [comment]
@hdrabkin, we can do this together if you need a refresher.

**Comment by ukemi** [comment]
Let's do this one at the same time.  #17028

**Comment by hdrabkin** [comment]
done
