### ISSUE TITLE
Obsolete GO:0001149 transcription factor activity, bacterial-type RNA polymerase termination site sequence-specific binding 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16730]
Hello, 

 'GO:0001149 transcription factor activity, bacterial-type RNA polymerase termination site sequence-specific binding' (def: Interacting selectively and non-covalently with a sequence of DNA that is a termination site for bacterial-type RNA polymerase in order to promote transcription termination by bacterial-type RNA polymerase.)

The reason for obsoletion is that this term is not correctly defined or positioned in the ontology: transcription factors do not regulate **initiation** of transcription (like other sibling terms). Maybe we need 'transcription terminator activity', but that was obsoleted. 

 'GO:0001149 transcription factor activity, bacterial-type RNA polymerase termination site sequence-specific binding'  has no annotations, so I don't know what the anticipated usage was. 

@jimhu-tamu @sandyl27 @pedruzzi @ivanerill @AndreaAuchincloss
Any objection to the obsoletion ? Or other suggestions? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsoletion email: 
Dear all, 

The proposal has been made to obsolete 'GO:0001149 transcription factor activity, bacterial-type RNA polymerase termination site sequence-specific binding’. The reason for the obsoletion is that the term is not correctly defined. 

There are no annotations or mappings to this term; this term is not present in any subsets (slims), 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/16730

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 10th, 2018. Unless objections are received by December 10th, 2018.  we will assume that you agree to this change.

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
I think it's OK to obsolete. Note that for a possible replacement (or more than one)
* Many of the regulators of termination I can think of bind the nascent RNA and not the DNA anyway
* While there are proteins in antitermination systems (e.g. lambda Q) that are site specific DNA binding proteins, I'm not sure that a molecular function term captures the role in the process.

**Comment by pgaudet** [comment]
Thanks for the feedback @jimhu-tamu 

Right - I am not clear between termination and antitermination (perhaps we also have some kind of phenotype problem?) Lamda Q is mention is the term 'GO:0001073 transcription antitermination factor activity, DNA binding' - def: Binds to DNA, typically within region of the promoter and transcribed region, to promote readthrough of a transcription termination site and thus extending the length of the RNA transcript produced. Examples of antitermination factors which bind DNA include the lambda Q protein.

Pascale

**Comment by pgaudet** [comment]
Done 
https://github.com/geneontology/go-ontology/pull/16772/commits/e465aa274a9c04c94edb808e2a4f87d4afc02384
