### ISSUE TITLE
Obsoletion notice GO:0001062 plastid   PEP-A RNA polymerase activity and GO:0001063 plastid PEP-B   RNA polymerase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16738]
Dear all, 

The proposal has been made to obsolete 
* GO:0001062 plastid   PEP-A RNA polymerase activity 
* GO:0001063 plastid PEP-B   RNA polymerase activity 

The reason for obsoletion is that these terms represent gene products. 

There are no annotations to these terms, no mappings; these terms are not present in any slims. Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/16738

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 10th, 2018. Unless objections are received by December 10th, 2018.  we will assume that you agree to this change.

Thanks, Pascale

**Comment by krchristie** [comment]
Hi Pascale,

My recollection from when I made these terms is that they represent the activities of distinct complexes, just like the similar terms for "RNA polymerase II activity" (GO:0001055), etc. So, I don't really understand the argument to obsolete these specific terms if you are keeping the other MF terms for RNA polymerase activities.

-Karen

**Comment by pgaudet** [comment]
But do we need a different function for each complex ? Isn't the parent, 'bacterial-type RNA polymerase activity', sufficient? 

(I could also merge, rather than obsoleting). 

Thanks, Pascale

**Comment by krchristie** [comment]
We have a different function for all of the other RNA polymerase activities, e.g. RNA polymerase I, RNA polymerase II, RNA polymerase III, etc. 

We have previously merged all of these into one function and then added function terms for activities of individual complexes back again. Part of the reasoning when we added them back again was for making Function-Process links between MF terms and BP terms such as "transcription from RNA polymerase II promoter"

If we are going to have functions for any of the individual activities, then I think that for consistency we should have different function terms for all of the activities. 

-Karen

**Comment by pgaudet** [comment]
Will merge up instead, see #21198

**Comment by pgaudet** [comment]
I will go ahead with the obsoletion and use a REPLACE_BY GO:0003899 DNA-directed 5'-3' RNA polymerase activity  tag. 

The F->P link is misleading, GO:0001061 bacterial-type RNA polymerase activity is part of bacterial transcription, but it's parent of plastid polymerases.
