### ISSUE TITLE
Obsolete 'RNA polymerase II transcription coactivator activity involved in preinitiation complex assembly' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16733]
Hello, 

The term 'GO:0001128 RNA polymerase II transcription coactivator activity involved in preinitiation complex assembly' represents a mix of function and process. There are 9 annotations, some to general transcription factors, some to specific transcription factors, some to co-factors. Because of the inconsistencies in annotations, I propose to obsolete the term. 

Impacted groups: 

SGD (6 EXP) @srengel 
AspGD (2 EXP) @marekskrzypek
FlyBase (2 EXP) @hattrill  

Let me know if you have comments/suggestions. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0001128 RNA polymerase II transcription coactivator activity involved in preinitiation complex assembly' The reason for obsoletion is that the term represents a mix of function and process and is not annotated consistently.

There are 10 EXP annotations by SGD (6EXP), AspGD (2 EXP) and FlyBase (2 EXP). 

There are no mappings; these terms are not present in any slims. 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/16733

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 10th, 2018. Unless objections are received by December 10th, 2018.  we will assume that you agree to this change.

Thanks, Pascale

**Comment by hattrill** [comment]
Changed ours to GTF activity.

**Comment by srengel** [comment]
late, but i have addressed the 6 SGD annotations.  we now have no more annotations to this term.

**Comment by pgaudet** [comment]
Thanks @srengel
