### ISSUE TITLE
NTR peptidyl-aspartic acid 3-dioxygenase activity

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#16745]
Could we have a new MF term for peptidyl-aspartic acid 3-dioxygenase activity. The new term would be a sibling to peptidyl-lysine 3-dioxygenase activity #16632 (now GO:0106155 peptidyl-lysine 3-dioxygenase activity).

The references for the new request are PMIDs 1856229 and 1378441. Proposed def: Catalysis of the reaction: protein L-aspartate + 2-oxoglutarate + O2 = protein 3-hydroxy-L-aspartate + succinate + CO2.

**Comment by ukemi** [comment]
Rhea:11508, EC:1.14.11.16, Metacyc:PEPTIDE-ASPARTATE-BETA-DIOXYGENASE-RXN?

**Comment by deustp01** [comment]
@ukemi @hdrabkin What is the difference between **peptide**-aspartate beta-dioxygenase activity - GO:0004597 (which I guess is the existing term I can use here and **peptidYL**-aspartate beta-dioxygenase activity, the new term I requested?
For example,
 GO:0036140
peptidyl-asparagine 3-dioxygenase activity

GO:0004597
peptide-aspartate beta-dioxygenase activity

Thanks
GO:0050169
peptide-tryptophan 2,3-dioxygenase activity

**Comment by ukemi** [comment]
Hmmmm. Looks like I have given your new term and GO:0004597 the same xrefs. Maybe a merge is in order. This should become obvious once we have the logical defs for MFs in place.

**Comment by hdrabkin** [comment]
I think they are the same based on the xrefs.
