### ISSUE TITLE
'translation factor activity, nucleic acid binding' versus 'translation repressor activity, non-nucleic acid binding'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16744]
Hello, 

I am not clear what 'translation factor activity, nucleic acid binding' versus 'translation repressor activity, non-nucleic acid binding' are supposed to represent. 

* GO:0045183 translation factor activity, non-nucleic acid binding: single annotation by MGI MGI:1334263 to a ubiquitin ligase activity. It seems that the process of 'repression of translation' was captured here, rather than a  real function. 
* GO:0000901 translation repressor activity, non-nucleic acid binding : Since ISO by MGI - link doesn't work. 

@hdrabkin  would you be OK if I merged these terms into their respective parents ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
(Note to self: the next step would probably be to also merge the nucleic acid binding terms, since this is probably the mechanism by which these proteins mediate activation/repression of transcription.)

**Comment by ValWood** [comment]
Hi @pgaudet  are these about trancription or translation?

**Comment by pgaudet** [comment]
translation. 

I'd like to finish MF refactoring

**Comment by ValWood** [comment]
OK edited above.I get it now but do there work on RNA not just "nucleic acid"

**Comment by pgaudet** [comment]
I dont understand your question.. Please rephrase

**Comment by ValWood** [comment]
I don't understand why the term is "nucleic acid binding". Shouldn't it be RNA binding (i.e are there translational repressors that bind to DNA?)

**Comment by pgaudet** [comment]
Oh! yes there are also children 

'translation regulator activity'
- 'translation factor activity, non-nucleic acid binding'
-- 'translation repressor activity, non-nucleic acid binding'

--'translation activator activity' (note that this one is a child of 'nucleic acid binding', but since this is not in the term name I dont think all proteins are nucleic acid binding

-'translation regulator activity, nucleic acid binding'
--'translation repressor activity, mRNA regulatory element binding'

What I am proposing in short is this: 

'translation regulator activity'
- 'translation activator activity'
- 'translation repressor activity'


Pascale

**Comment by ValWood** [comment]
I agree we should get rid of the RNA binding terms, but I think this is also covered by this more comprehensive ticket
https://github.com/geneontology/go-ontology/issues/29089
@pgaudet Please close if you agree

**Comment by ValWood** [comment]
It is covered in the other ticket. Still need to make a decision as part of the broader revisions

**Comment by pgaudet** [comment]
Right, the other ticket covers it.
