### ISSUE TITLE
Obsolete Hijacked molecular function

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16741]
Hello, 

The multiorganism process group (@jimhu-tamu; @pgaudet, @mgiglio99 @cmungall @pmasson55 @selewis @nsuvarnaiari @jrr-cpt) 
doesn't like the term 'hijacked molecular function. 

Right now we have the following structure: 

'exogenous protein binding'
- 'hijacked molecular function'
-- 'virus receptor activity'

I propose to obsolete 'hijacked molecular function' and keep 'virus receptor activity directly under 'exogenous protein binding'. Would that be OK ? 
@thomaspd please let me know what you think. 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't like this term either. I don't  think the pathogen community  would really know to look for this.Definitely obsolete.

**Comment by selewis** [comment]
I'm very hesitant about two things and one hinges on the other. 
First, I am not convinced that embedding the fact that the protein is used (i.e. function) by a different organism than the one that encodes it into the class itself is the best way to capture this information. The function may well be the same regardless of what organism is making use of it. We'll end up with redundancy. This will muddle function up with the identify of the organism using it (even if it just neutrally says 'something other than the organism that encodes it'). This is bound to lead to problems down the line. And yes I know it evolved in just one organism, but that organism may well be influenced by the organisms it lives with.

Second, the connotations of the word 'hijacked' are extremely negative (highwaymen, guns, nasty). If for practical considerations we're not going to model this correctly, then at least we should use a more neutral word.
