### ISSUE TITLE
Regulation terms for 'melanotic encapsulation of foreign target'

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#16749]
Could I request regulation terms for 'melanotic encapsulation of foreign target' GO:0035011?
PMID:15749104
GOC:ha

Thanks.

**Comment by pgaudet** [comment]
Also added PMID:18457993

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140539
+name: regulation of melanotic encapsulation of foreign target
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of melanotic encapsulation of foreign target." [PMID:15749104, PMID:18457993]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0035011 ! melanotic encapsulation of foreign target
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16749 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-07T08:16:00Z
+
+[Term]
+id: GO:0140540
+name: negative regulation melanotic encapsulation of foreign target
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of melanotic encapsulation of foreign target." [PMID:15749104, PMID:18457993]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0035011 ! melanotic encapsulation of foreign target
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16749 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-07T08:17:40Z
