### ISSUE TITLE
serine import into mitochondrion

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#16756]
Hi,

I would need a term for serine import into mitochondrion. Note that there is already a term for  GO:1904983 glycine import into mitochondrion

Thanks

Sylvain

Category: Process
Definition: The process in which serine is transported from the cytosol, into the mitochondrial matrix.
child of: 
GO:0032329 serine transport
GO:0003333 amino acid transmembrane transport
GO:1990542 mitochondrial transmembrane transport

PMID:30442778

**Comment by sylvainpoux** [comment]
Hi @ValWood, just to let you know that I updated the pombe entry and will curate the term in GO

**Comment by sylvainpoux** [comment]
Hi @pgaudet 

after 7 days, nobody took my tickets, may I ask you to assign it to someone?

Thanks

Sylvain

**Comment by pgaudet** [comment]
Created new term 
+[Term]
+id: GO:0140300
+name: serine import into mitochondrion
+namespace: biological_process
+def: "The process in which serine is transported from the cytosol, into the mitochondrial matrix." [PMID:30442778]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005759 ! mitochondrial matrix
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: imports CHEBI:17822 ! serine
+intersection_of: results_in_transport_across GO:0031966 ! mitochondrial membrane

**Comment by ValWood** [comment]
Thanks @sylvainpoux  ! I updated in PomBAse also, and removed the old "tricarboxylate"  ISS's I made previously.

I also contacted Pfam to update the family description, as this does not seem to be valid?

Cheers

Val
