### ISSUE TITLE
mRNA N-acetyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#16755]
Hi,
I would need a GO term for the following enzyme

Thanks

Sylvain

mRNA N-acetyltransferase activity
Category: Function
Definition: Catalysis of the reaction: acetyl-CoA + cytidine = CoA + N4-acetylcytidine. The cytidine is within the polynucleotide chain of an mRNA.
child of GO:0008080 N-acetyltransferase activity
PMID:30449621

It will correspond to RHEA:58480 (not yet public)

CC   -!- CATALYTIC ACTIVITY:
CC       Reaction=a cytidine in mRNA + acetyl-CoA + ATP + H2O = ADP + an
CC         N(4)-acetylcytidine in mRNA + CoA + H(+) + phosphate;
CC         Xref=Rhea:RHEA:58480, Rhea:RHEA-COMP:15145, Rhea:RHEA-
CC         COMP:15146, ChEBI:CHEBI:15377, ChEBI:CHEBI:15378,
CC         ChEBI:CHEBI:30616, ChEBI:CHEBI:43474, ChEBI:CHEBI:57287,
CC         ChEBI:CHEBI:57288, ChEBI:CHEBI:74900, ChEBI:CHEBI:82748,
CC         ChEBI:CHEBI:456216; Evidence={ECO:0000269|PubMed:30449621};

**Comment by hdrabkin** [comment]
The def needs to be changed to the rhea
Catalysis of the reaction: a cytidine in mRNA + acetyl-CoA + ATP + H2O = ADP + an
CC N(4)-acetylcytidine in mRNA + CoA + H(+) + phosphate.

**Comment by selewis** [comment]
Consistency is very important. Once upon a time the conventions were all written up as reference guides (e.g. for calcium/Ca or greek or what have you). It simply makes our lives easier.

**Comment by ukemi** [comment]
If I recall correctly, we decided to use the strings that Rhea uses in their reaction descriptions. I believe those are the strings that are listed in ChEBI as the UniProt synonyms. Am I correct @amorgat?

**Comment by cmungall** [comment]
This is correct.

**Comment by amorgat** [comment]
@deustp01  and @selewis sure constency is a very important but a difficult task.
In Rhea, as far as possible we follow  IUBMB conventions.
For proteins, usage is to use brackets -[protein] or -[specific protein] whereas for polynucleotides they rather use "... in mRNA", "... in DNA" etc
I don't know where the best place is to present and discuss our guidelines and practices. Maybe in a dedicated ticket? Any suggestions are welcome.

**Comment by deustp01** [comment]
In this case, IUBMB has to be the authority, I think, and if there is to be an argument about consistency it will need to be with them. And maybe that assertion with a link to wherever IUBMB keeps its rules is the key bit of documentation needed.

**Comment by amorgat** [comment]
@kaxelsen, are you aware of such IUBMB documentation? Or is it only usage?

**Comment by kaxelsen** [comment]
There are no guidelines for naming of compounds including a protein part. The naming policy has changed over time, but there has not been any effort to update old names so there is a great deal of inconsistency in the names. Even for simpler compounds several names can be used in parallel. So I think the closest you get to a consistent naming policy is in Rhea.

**Comment by hdrabkin** [comment]
RHEA:58480 was added. tag removed

**Comment by pgaudet** [comment]
Changed label to 'mRNA cytidine N-acetyltransferase activity'
