### ISSUE TITLE
Merge GO:0005040 decoy death receptor activity into 'receptor antagonist activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16753]
Hello, 

For the Molecular Function refactoring work, I will merge 'GO:0005040 decoy death receptor activity' (Def: "Combining with an extracellular messenger (death ligand) without transmission of the signal. Decoy death receptors compete with death receptors for ligand binding, and do not initiate apoptosis.") into GO:0048019 receptor antagonist activity (Interacts with receptors to reduce the action of another ligand, the agonist.)

**Comment by pgaudet** [comment]
@balhoff : The term I am merging had some taxon constraints. Do I need to modify the taxon constraint file ? Or are terms merged and obsoleted automatically removed from the TC file ? 

Thanks, Pascale

**Comment by balhoff** [comment]
At least for now you should edit the taxon constraint files. It seems like the Travis checks did a good job of pointing out that you needed to look there. Does that seem like a good procedure?

**Comment by pgaudet** [comment]
The Travis message is very cryptic to me - but OK I will do that. 

Thanks, Pascale

PS I will need someone to do the import thing, as I dont have Robot installed. I supposed that needs to be done first, then the merge or obsoletion can be done. Right ?

**Comment by balhoff** [comment]
> The Travis message is very cryptic to me

Yeah that is true. Actually I think it was only clear to me because you had already mentioned taxon constraints.

> I will need someone to do the import thing, as I dont have Robot installed. 

Do you have Docker? With the `run.sh` script, you don't need robot, just Docker running.

>  I supposed that needs to be done first, then the merge or obsoletion can be done.

I think you will get Travis errors until both the obsoletion and the taxon constraint update have been done. But I guess they can be edited in either order.

**Comment by pgaudet** [comment]
Right - sorry - no Docker. I can try to convince the ITs to install it but they were not keen.

**Comment by balhoff** [comment]
Okay, got it!

**Comment by pgaudet** [comment]
> I think you will get Travis errors until both the obsoletion and the taxon constraint update have been done

Really? The taxon constraint has no dependencies - should't we be able to remove anything there ? (I guess I'll see!)

**Comment by balhoff** [comment]
I thought a taxon constraint should fail the check that an obsoleted term has no relationships.

**Comment by cmungall** [comment]
> Right - sorry - no Docker. I can try to convince the ITs to install it 
> but they were not keen.

Can you tell them it's part of our SOP for ontology development?

You have a mac? It's a pretty basic install.

**Comment by cmungall** [comment]
> I thought a taxon constraint should fail the check that an obsoleted 
> term has no relationships.

+1
