### ISSUE TITLE
Improve definition of GO:0048019 receptor antagonist activity ?

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16757]
GO:0048019 receptor antagonist activity is defined as: "Interacts with receptors to reduce the action of another ligand, the agonist."
Wikipedia is a bit more precise:  "A receptor antagonist is a type of receptor ligand or drug that blocks or dampens a biological response by binding to and blocking a receptor rather than activating it like an agonist"

Should we use the definition from wikipedia? 
@ukemi What do you think ? 

Thanks, Pascale

**Comment by ukemi** [comment]
We certainly don't want to include drug. What exactly is wrong with the current def?

**Comment by pgaudet** [comment]
Right leaving drug out ! "A receptor antagonist is a type of receptor ligand that blocks or dampens a biological response by binding to and blocking a receptor rather than activating it like an agonist"

The problem with the current definition is that you dont get the notion of the competition with the ligand binding site. You could regulate some other (for eg cytoplasmic) part of the receptor, and stil lfit the definition, but I think antagonist is a little more precise. 

(That being said if people think the current definition is precise enough that's OK with me). 

Pascale

**Comment by ukemi** [comment]
OK. I will try to tweak the definition, but keep it as an MF rather than the thing doing the action.
