### ISSUE TITLE
GO:0000496 base pairing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16759]
Porting discussion (and action points) from https://github.com/geneontology/go-ontology/issues/16742#issuecomment-444848939

Comment from @ValWood 
base-pairing
I could not figure out why this term existed until I drilled down and got to the sensible terms like
GO:0000332 template for synthesis of G-rich strand of telomere DNA activity
in the DNA branch,

and
GO:0030555 RNA modification guide activity
GO:0030557 tRNA modification guide activity

Recommend obsoleting the "base-pairing" terms (or merging if they have been correctly used

replacing with a term along the lines
of
nucleic acid template activity
-DNA template activity
-RNA template activity

As the commonality here is providing a specific (guide RNA, codon/anticodon) template for complementary base-pairing, not the base pairing itself.

**Comment by pgaudet** [comment]
In the base-pairing term, there is a comment that these terms are to be used to annotate nucleic acids only. 

It's interesting that we make this distinction - usually terms are not created dependent on the types of molecule to be annotated ? If we ignore the type of molecule annotated, then these can be meged with their corresponding 'binding' term


GO:0000496 base pairing- 0 annotations
GO:0000497 base pairing with DNA - 0 annotations
GO:0000498 'base pairing with RNA - 0 annotations
GO:0000499 'base pairing with mRNA - 0 annotations
GO:0000944 'base pairing with rRNA - 6 annotations
GO:0000945 'base pairing with snRNA - 0 annotations
GO:0000946 'base pairing with tRNA - 0 annotations


---

**Comment by ValWood** [comment]
or into the  suggested grouping term for "template activity" (which could have a binding parent AND a molecular function parent).

That would retain any specificity for GO:0000944 'base pairing with rRNA - 6 annotations

**Comment by pgaudet** [comment]
Hello, 

Here's what I did: 

Moved the branch ''RNA modification guide activity' directly under molecular function. That takes care of all terms, such as: 
'RNA 2'-O-ribose methylation guide activity'
'RNA pseudouridylation guide activity'
'rRNA modification guide activity'
'snRNA modification guide activity'
'tRNA modification guide activity'

Except for GO:0000332 template for synthesis of G-rich strand of telomere DNA activity
in the DNA branch,
So I renamed its parent 'GO:0000497 base pairing with DNA' -> DNA template activity, and moved that one directly under MF as well. 

OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yep!
