### ISSUE TITLE
Obsolete GO:0061777  DNA clamp activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16752]
Dear all, 

The proposal has been made to obsolete 'GO:0061777 DNA clamp activity'. The reason for obsoletion is that the term captures the structure of the complex when bound to the DNA, not a specific function. 

There are 2 annotations to the term (pombase). There are no mappings; this term is not present in any subsets (slims). Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/16752

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 10th, 2018. Unless objections are received by December 12th, 2018.  we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
The discussion is in ticket #16742
In the end we agreed to the obsoletion.

**Comment by pgaudet** [comment]
Thanks @jimhu-tamu 
We do have DNA processivity factor activity as a GO term (GO:0030337)

Maybe we have terms for the other functions of the clamp as well. 

The current definition only states that a clamp is a structure that binds DNA: "A DNA binding activity in which a protein complex interacts selectively and non-covalently with single DNA duplex to tightly encircle the DNA." So if this is a true activity, we need to work on the definition. 

Thanks, Pascale

**Comment by mah11** [comment]
My impression from #16742 was that the only thing said about obsoleting GO:0061777 was that Val wouldn't oppose it. If it does go, I'll remove the PomBase annotations.

But it didn't seem fully decided, and the processivity factor activity (GO:0030337) probably doesn't fit whatever the 9-1-1 checkpoint clamp does. Although it's not fully characterized, it would probably fit a general "clamp activity" definition along the lines of:

"Interacting selectively and non-covalently with a single DNA duplex so as to encircle the DNA, diffuse freely along the length of the DNA molecule, and promote the binding of one or more other proteins to the DNA through multiple catalytic turnovers."

For the above, I found PMID:29860305 very helpful, and I also looked at PMID:30072380 and PMID:29357057.

**Comment by ValWood** [comment]
Perhaps the fact that it can slide along the DNA  does warrants its own specific type of DNA binding.  It's DNA binding but isn't bound to a fixed point on the DNA.

**Comment by pgaudet** [comment]
Right, I probably summarized the discussion a bit too succinctly. 

I am happy to redefine as you suggest, and keeping the term under DNA binding.

**Comment by jimhu-tamu** [comment]
The sliding is part of why I'm not even sure I think of it as DNA binding.

**Comment by pgaudet** [comment]
@jimhu-tamu what do you suggest then ?

**Comment by jimhu-tamu** [comment]
@pgaudet - I'm not sure. It depends on whether the binding parents include "topological binding", which is what is used for the [sliding clamps](https://www.ncbi.nlm.nih.gov/pubmed/7903401) and [cohesin](https://www.ncbi.nlm.nih.gov/pubmed/24291789) in the literature. I think the definition of GO:0005488 ! binding would allow this, in which case it would stay as DNA binding.

> The selective, non-covalent, often stoichiometric, interaction of a molecule with one or more specific sites on another molecule." [GOC:ceb, GOC:mah, ISBN:0198506732]

But when I think of binding, I think most of us think of physical interactions, not topological constraints. The energy required to pull a clamp off of a DNA molecule is related to the protein-protein interactions within the rings, not the noncovalent bonds between the protein and the nucleic acid.

Perhaps topological binding could be either a child or a narrow synonym for binding in general or ds DNA binding specifically or something in between. But I'm not sure about how generally applicable the concept of topological binding would be.

**Comment by ValWood** [comment]
From my conversations with various researchers when discussing cohesin activity, this is definitely a *type* of DNA binding.

It is usually articulated as "DNA binding activity" in the literature.

For e.g. Quick search
https://www.ncbi.nlm.nih.gov/pubmed/30201721

Intermediate step of cohesin's ATPase cycle allows cohesin to entrap DNA.
Çamdere GÖ1, Carlborg KK1, Koshland D2.

Cohesin is a four-subunit ATPase in the family of structural maintenance of chromosomes (SMC). Cohesin promotes sister chromatid cohesion, chromosome condensation, DNA repair, and transcription regulation. Cohesin performs these functions as a DNA tether and potentially a DNA-based motor. At least one of its ******DNA binding activities****** involves entrapment of DNA within a lumen formed by its subunits. This activity can be reconstituted in vitro by incubating cohesin with DNA, ATP, and cohesin loader. Previously we showed that a mutant form of cohesin (DE-cohesin) possesses the ability to bind and tether DNA in vivo. .....

**Comment by ValWood** [comment]
Cohesin SA2 is a sequence-independent *****DNA-binding protein******* that recognizes DNA replication and repair intermediates.
Countryman P1, Fan Y2, Gorthi A3,4, Pan H1, Strickland J1, Kaur P1, Wang X5, Lin J1,6, Lei X2,7, White C1, You C8, Wirth N9, Tessmer I9, Piehler J8, Riehn R1, Bishop AJR3,4, Tao YJ2, Wang 
Abstract
Proper chromosome alignment and segregation during mitosis depend on cohesion between sister chromatids, mediated by the cohesin protein complex, which also plays crucial roles in diverse genome maintenance pathways. Current models attribute DNA binding by cohesin to entrapment of dsDNA by the cohesin ring subunits (SMC1, SMC3, and RAD21 in humans).

**Comment by jimhu-tamu** [comment]
@ValWood from my brief reading it seems like cohesin has two DNA binding modes. An entrapment topological binding mode followed by a more stable mode that is more classical DNA binding. This means cohesin in the stable mode doesn't slide and fall off when a ds break is introduced nearby. But I'll have to find the paper again. By contrast, the sliding clamps will diffuse along the DNA for many kb and fall off the ends of linear DNA.

**Comment by pgaudet** [comment]
Comment from external expert James A. Borowiec, NYU

Hi Pascale,

Just my two cents - the key role of the DNA clamp is to increase DNA polymerase processivity. In the case of HSV UL42 processivity factor, the protein does not actually form a ring around the DNA, but rather contains a large area of basic charge that allows the factor (and the bound DNA polymerase UL30) to stay associated with the DNA even while also permitting sliding along the DNA (see  PMID:  10882068). Because the ring-structure is not completely conserved among all processivity factors, I think that losing the ‘DNA clamp activity’ is advisable. 

Regards,
Jim

--------------------------------------
James A. Borowiec, Ph.D.
Professor of Biochemistry and Molecular Pharmacology
Director, Research Emergency Management and Enterprise Resilience
Office of Science and Research
New York University School of Medicine

**Comment by pgaudet** [comment]
If we leave cohesin ATPase activity - is everyone OK with obsoletion of DNA clamp activity ? 


<img width="224" alt="image" src="https://user-images.githubusercontent.com/4782928/49799589-9c33a080-fd45-11e8-99ff-63248c00b03e.png">


Thanks, Pascale

**Comment by ValWood** [comment]
The cohesin term I want to keep
is topological DNA entrapment activity
https://www.ebi.ac.uk/QuickGO/term/GO:0061776 
The *DNA binding activity*

 (in addition to the ATPase activity, but this could potentially merge up, it probably doesn't need to be cohesin specific ATPase)

But Cohesin has more than one activity. It is an ATPase during loading and unloading. When it is loaded and performing its  real function it is  
a doing 
topological DNA entrapment 
PMID: 27797071
PMID: 30201721
PMID: 28842880

**Comment by pgaudet** [comment]
This ticket is limited to DNA clamp activity. If something needs to be done about cohesin ATPase activity, please open a different ticket. 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi @jimhu-tamu  I probably confused the issue bringing up the "topological DNA entrapment activity" term. 
topological DNA entrapment activity is not for clamps. It is a different activity, and specifically for the topological entrapment of both strands of DNA by cohesin.

The correct MF term for clamp activity is 
DNA polymerase processivity factor activity

(so @pgaudet  should this have a DNA binding parent?)

v

**Comment by jimhu-tamu** [comment]
> The correct MF term for clamp activity is DNA polymerase processivity factor activity

NOOOO!! This is wrong and I suspect it is related to the expert Borowiec answering the wrong question, IMO. 

Forming a ring-shaped clamp is one way to be a processivity factor. It's not the only way. In addition to the case mentioned by Borowiec, I have already been thinking of how thioredoxin has processivity factor activity in phage T7 replication.  The topological binding activity is necessary but not sufficient for some processivity factors such as PCNA and DnaN and T4 gp45 to act as processivity factors.  It's also necessary for other functions of these proteins in DNA repair and in the case of gp45, activation of late transcription.

To call that the correct term for clamp activity is like saying it's incorrect to call Lac repressor a site-specific DNA binding protein because it negatively regulates transcription.

**Comment by ValWood** [comment]
so presumably there are other "processivity factor" terms and people would choose the correct one.
The rationale is in https://github.com/geneontology/go-ontology/issues/16742

**Comment by jimhu-tamu** [comment]
I don't think we need multiple DNA replication processivity factor terms to capture different mechanisms - I don't see more than one in the molecular function aspect, and that is as it should be.

But the key point is whether the entrapment of a single DNA duplex is a molecular function that does not have a part_of relationship to its role in increasing the processivity of complexes involving DNA polymerases.  I'm saying that it is based on the roles in transcription and DNA repair.

In E. coli, the clamps get left behind in the wake of the fork, and it is thought that this is significant for function. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4284645/

> We quantify the recruitment, binding and turnover of β2-sliding clamps on DNA during replication. These quantitative in vivo results demonstrate that numerous β2-clamps in E. coli remain on the DNA behind the replication fork for a protracted period of time, allowing them to form a docking platform for other enzymes involved in DNA metabolism.
