### ISSUE TITLE
NTR/OTR(?): double-strand break repair via transcription-associated homologous recombination

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#16775]
Possible NTR: double-strand break repair via transcription-associated homologous recombination

I'm coming across several papers describing a HRR system where an existing RNA transcript is brought to a DSB by Rad54, and the RNA acts as a "bridge" for repair: see figure https://www.nature.com/articles/nature13682/figures/3 ; for a "happier" simpler fig see https://www.nature.com/articles/s41422-018-0105-8/figures/1

The def could very roughly rephrase PMID:25186730 "A mechanism of homologous recombination and DNA repair in which transcript RNA is used as a template for DSB repair"

The parent term would likely be GO:0000724 double-strand break repair via homologous recombination,
>  GO:0000724 double-strand break repair via homologous recombination
> Def: The error-free repair of a double-strand break in DNA in which the broken DNA molecule is repaired using homologous sequences. A strand in the broken DNA searches for a homologous region in an intact chromosome to serve as the template for DNA synthesis. The restoration of two intact DNA molecules results in the exchange, reciprocal or nonreciprocal, of genetic material between the intact DNA molecule and the broken DNA molecule. 
> 
but this def doesn't seem to allow the use of RNA as a template ("homologous region in an intact chromosome" , "intact DNA molecule"), so maybe just changing the def of GO:0000724 slightly? I'm certainly not an expert so if any recombination experts are out there, that would help. Or maybe I'm just in the wrong branch of GO?

Thanks!

Sources:
https://www.nature.com/articles/s41422-018-0105-8
PMID:25186730 ("novel",  2014 Nature) PMID:29545568 (yeast)  PMID:30367126 (research highlight)

There's also this:
https://github.com/geneontology/go-ontology/projects/12

**Comment by hdrabkin** [comment]
+id: GO:0106400
+name: double-strand break repair via transcription-associated homologous recombination
