### ISSUE TITLE
Create a simpler bio-chebi using the Rhea pH7_3 mapping

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16777]
ftp://ftp.expasy.org/databases/rhea/tsv/chebi_pH7_3_mapping.tsv

Options:

 1. We pick the pH7.3 mapping as the canonical entry, always use that, remove others from import file
 2. Create new grouping classes (eg GOCHE), defined either by union or by reflexive congjugate-base/tautomer OPs

**Comment by balhoff** [comment]
- [ ] update all CHEBI IDs used in GO to reference the pH7_3 term.
- [ ] create additional inferred subclass relations between pH7_3 terms using conflation script
- [ ] create new CHEBI import; or create GO-specific hierarchy composed of GOCHE IDs

**Comment by balhoff** [comment]
QC: produce reasoner diff on GO hierarchy after the above changes—did anything change?

**Comment by balhoff** [comment]
As of 2020-04-09 GO references 2084 CHEBI terms. But 901 of them are not mapped in the Rhea pH7_3 file. Is this something we should ask them to update? Some random examples:

```
http://purl.obolibrary.org/obo/CHEBI_10003
http://purl.obolibrary.org/obo/CHEBI_10119
http://purl.obolibrary.org/obo/CHEBI_10415
http://purl.obolibrary.org/obo/CHEBI_12777
http://purl.obolibrary.org/obo/CHEBI_12936
http://purl.obolibrary.org/obo/CHEBI_131429
```

**Comment by balhoff** [comment]
@alanbridge @amorgat if a CHEBI term is not in Rhea's chebi_pH7_3_mapping.tsv, is that because it is not used by Rhea? Do you aim to eventually include all CHEBI terms in that file? Thanks!

**Comment by amorgat** [comment]
@balhoff, chebi_pH7_3_mapping.tsv contains more data than those used in Rhea (Rel 111: 73384 pairs), it was computed on the whole chebi data set (CHECKED + SUBMITTED). But the mapping can be computed iff the ChEBI entry has  a 2D structure and an InChI or at least a SMILES ; and if the corresponding majors species @ pH 7.3 already exists in ChEBI.

http://purl.obolibrary.org/obo/CHEBI_10003 : no SMILES, no InChI, mixture

http://purl.obolibrary.org/obo/CHEBI_10119 (ziprasidone): SMILES & InChI, but the major species @ pH 7.3 doesn't exist in ChEBI (charged piperarazine)

http://purl.obolibrary.org/obo/CHEBI_10415 (beta-endorphin, 31 aa): SMILES & InChI but the major species @ pH 7.3 doesn't exist in ChEBI

http://purl.obolibrary.org/obo/CHEBI_12777 (vitamin A): no structure

http://purl.obolibrary.org/obo/CHEBI_12936 (D-galactose): no structure
aldehydo-D-galactose (CHEBI:17118) is a D-galactose (CHEBI:12936)
D-galactofuranose (CHEBI:143624) is a D-galactose (CHEBI:12936)
D-galactopyranose (CHEBI:4139) is a D-galactose (CHEBI:12936)

http://purl.obolibrary.org/obo/CHEBI_131429 (carcinine): SMILES & InChI but the major species @ pH 7.3 doesn't exist in ChEBI (charged amino term)

**Comment by balhoff** [comment]
@amorgat thank you, that's very helpful.

**Comment by amorgat** [comment]
I looked for CHEBI:131429 and found it was used in a GO:BP 
GO:905130 | carcinine import across plasma membrane

https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/import_across_plasma_membrane.tsv

@balhoff, can you tell us how these ChEBIs are used in GO? How many have SMILES and/or InChI?
ChEBI team has quite limited resource for the moment, we should investigate before requesting a bulk of new entries ;-)

**Comment by balhoff** [comment]
They are used in logical definitions in the editors' version (and drive classification). Unfortunately these axioms are filtered from the GO versions loaded into the online ontology browsers. For example,

``` 
'carcinine import across plasma membrane' EquivalentTo transport and ('has target start location' some 'extracellular region') and ('has target end location' some cytosol) and (imports some carcinine) and ('results in transport across' some 'plasma membrane')
```

I've been looking at these with @ukemi, and in some cases GO may just choose a better term that is in the mapping file. In any case he's got a much clearer picture of what we might need than I do, hopefully he can comment.

**Comment by pgaudet** [comment]
Is this because we are not using the correct ChEBI ?

**Comment by deustp01** [comment]
@ukemi would it be reasonable to ask GO curators not only to identify the relevant chemicals when making a new term request but also the physiologically relevant form of the chemical (or an explicit statement that the data aren't available to make that identification?

And perhaps if the problem is that only an agnostic parent entry is available from ChEBI now, that could be used as a placeholder?

If this is excessive micro-management, feel free to ignore.

**Comment by ukemi** [comment]
At some point, we would like it to be the only thing available, but I don't think the request is unreasonable.

**Comment by pgaudet** [comment]
@deustp01 Will you give guidelines as to how to do that ?

**Comment by deustp01** [comment]
@pgaudet This is really a social engineering guideline, asking curators to sort out the chemistry related to new molecular function term requests more completely. (Not sure how helpful that is)

**Comment by balhoff** [comment]
bio-chebi is now based on the ph 7.3 mappings.
