### ISSUE TITLE
meiotic drive

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16780]
Hello GO,

Here's a fun one for you!

For a community-curated paper on some of the aptly named _wtf_ genes in pombe, we could do with a term for the fascinating phenomenon of meiotic drive. Though weird, it does occur naturally and therefore is "normal" in at least that sense.

id: GO:new
name: meiotic drive
def: A biological process that results in the unequal transmission of alleles, haplotypes, or chromosomes from a parental genome to gametes.
is_a: ???

optional "gloss" for definition: In the absence of meiotic drive, the two copies of each gene or chromosome in a diploid organism are transmitted to offspring with equal probability.
(or edit to make less specific for haploid/diploid)

Possible references include PMIDs 26920473, 29499907, and 29322557 (the last is mostly specific to the fission yeast wtf drivers). It's quite likely that my suggested definition could be improved if someone can devote a bit of time to it.

We only have an immediate need for a general term; if you want to include terms for some or all of the various types of meiotic drive known, we would use one for "poison-antidote", as opposed to "killer-target" or any others; the reviews should provide definitions.

As hinted in the obo stanza, parentage is where I'm struggling the most. It might be a type of reproductive process, or regulation of reproduction? Maybe specifically gametogenesis, or regulation thereof?

I've really just skimmed the surface of this topic (and the text of the reviews I've cited). We can put you in touch with some of the people working on meiotic drive in fission yeast if that would help; less sure what we might contribute w.r.t. other drive mechanisms should you want to go there. So if you've got any questions, don't hesitate to ask - but be warned, the initial response is likely to be "I have no idea".

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Meiotic_drive

**Comment by ValWood** [comment]
Note there are different mechanisms for drive, and some  "meiotic drive" is really post-meiotic
 https://en.wikipedia.org/wiki/Intragenomic_conflict

**Comment by Antonialock** [comment]
Fraternicide is not uncommon... Typically I guess to reduce competition for resources (birds?). But also bees (queen bees related? And male bees being reduced in numbers by siblings in some species (not many of them needed)). Also some downright odd examples like sand sharks https://en.m.wikipedia.org/wiki/Cannibalism#Intrauterine_cannibalism

Those cases do seem a bit different in that closest siblings are killed off. Meiotic drive is slightly different in that if you are really closely related then you are spared, whereas if you are slightly different genetically then you are killed. 

There’s also cannibalistic tadpoles that (unlike the majority of tadpoles in that frog species) are born with teeth...they then gobble up all tadpoles that aren’t at least their siblings, or cousins

**Comment by mah11** [comment]
> Note there are different mechanisms for drive, and some "meiotic drive" is really post-meiotic

From the reviews I've looked at, I gather that the phrase "meiotic drive" has come to be used for mechanisms that don't act directly on the meiotic divisions as well as those that do.

For example, from PMID:29499907 "There are two general classes of meiotic drivers [9]. Class one drivers, sometimes called ‘true meiotic drivers’ (see Glossary), act during the meiotic chromosome divisions. ... The second class of driver is the ‘killer meiotic drivers’ ... [that act] by sabotaging otherwise viable meiotic products that do not inherit the selfish allele."

and PMID:29322557 has "The term meiotic drive was coined 60 years ago to specifically describe biased segregation into the one gamete made during asymmetric (female) meiosis (Sandler & Novitski, 1957). ... The term meiotic drive is also widely used to describe the actions of other selfish alleles that act to bias their own transmission into gametes without directly affecting chromosome segregation in meiosis (Lindholm et al., 2016; Zimmering, Sandler, & Nicoletti, 1970). These drivers act by causing the death or malfunction of gametes that fail to inherit them and can thus be called ‘gamete‐killers’ or ‘killers.’ "

The unifying feature is that alleles are unequally represented (i.e. the "driver" is overrepresented) among the surviving products of meiosis. Maybe that should be made more explicit in the term def, to avoid confusion with phenomena such as the examples Antonia listed. None of them is considered meiotic drive, because they don't alter which alleles make it into surviving gametes; they act at other stages of the organisms' life cycles. (The thing with bees is that workers share 3/4 of their genes on average, instead of the usual sibling 1/2, largely because of the haplodiploid sex determination system found in Hymenoptera - https://en.wikipedia.org/wiki/Haplodiploidy.)

**Comment by vanaukenk** [comment]
Yes, this is a really fascinating topic!

For now, I propose that we add a general term, 'meiotic drive' as an is_a child of 'reproductive process'.  

I'll use the definition and references you suggest above, @mah11 .

When we find that we need more specific terms to distinguish different mechanisms, we can add them and perhaps refine their placement in the ontology.

Sound okay?
