### ISSUE TITLE
Explore import of unipathway into GO ontology/go-cam

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16787]
As discussed at GO-Rhea-Reactome Geneva meeting

Bring in all unipathway linear pathways as GO processes

TBD: represent ordering between MF steps as nested OWL expression in ontology vs as template GO-CAMs

![image](https://user-images.githubusercontent.com/50745/49807678-fb4fe000-fd5a-11e8-9f65-0679377807ce.png)

cc @amorgat

**Comment by pgaudet** [comment]
I dont think we can even get that data anymore 

@amorgat please let us know if this is not true. 

Closing
