### ISSUE TITLE
regulation of poly(A)-specific ribonuclease activity

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16793]
id: GO:new1
name: regulation of poly(A)-specific ribonuclease activity
namespace: biological_process
def: "Any process that modulates the rate, frequency or extent of the catalysis of the exonucleolytic cleavage of poly(A) to 5'-AMP." [GOC:mah,PMID:29932902]
intersection_of: GO:0008150 ! biological_process
intersection_of: regulates GO:0004535 ! poly(A)-specific ribonuclease activity

if you also need asserted links, they would be:
is_a: GO:1901917 ! regulation of exoribonuclease activity
relationship: regulates GO:0004535 ! poly(A)-specific ribonuclease activity

and + and - subtypes, following same pattern

id: GO:new2
name: negative regulation of poly(A)-specific ribonuclease activity

id: GO:new3
name: positive regulation of poly(A)-specific ribonuclease activity

to use to annotate effect of S. pombe Pabp RNA binding on Ccr4 and Caf1 nuclease activities in the context of removing poly(A) tails

**Comment by mah11** [comment]
edited to add pos reg request

**Comment by mah11** [comment]
any progress?

**Comment by hdrabkin** [comment]
Slipped through in vacation; will do later today.

**Comment by hdrabkin** [comment]
+id: GO:0106246
+name: regulation of poly(A)-specific ribonuclease activity
+id: GO:0106247
+name: negative regulation of poly(A)-specific ribonuclease activity
+name: positive regulation of poly(A)-specific ribonuclease activity
+namespace: biological_process

Done.

**Comment by mah11** [comment]
hooray, thanks!
