### ISSUE TITLE
incorrect synonym scopes for enterobactin binding

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16803]
```
[Term]
id: GO:1903981
name: enterobactin binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with enterobactin." [GO_REF:0000067, GOC:mr, GOC:TermGenie, PMID:21951132]
***synonym: "Enterochelin" EXACT []
???synonym: "siderophore" NARROW []
intersection_of: GO:0005488 ! binding
intersection_of: has_input CHEBI:28855 ! enterobactin
```

**Comment by vanaukenk** [comment]
Existing synonyms:

***synonym: "Enterochelin" EXACT []
???synonym: "siderophore" NARROW []

@cmungall  From a quick review of the literature, here is one possible synonym fix:  

synonym: "enterochelin binding" EXACT 
synonym: "siderophore binding" BROAD

Alternatively, "siderophore binding" could actually become a new term that is a parent of "enterobactin binding".

See:
https://en.wikipedia.org/wiki/Enterobactin
https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:28855

What do you think?

**Comment by cmungall** [comment]
normally I'd opt for a new term but given it's binding maybe not a priority, stick with a broad syn? I don't have strong opinions
