### ISSUE TITLE
CHANGED PROPOSAL-  MF refactor: create new high level class: 'DNA structure modifier'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16804]
Hello, 

GO:0097617 annealing activity and GO:0008301 DNA binding, bending are types of 'binding', but they should probably have a 'true' molecular activity parent (see also #16742). I propose  to create a new term ~nucleic acid topology modifier~  ->  'DNA structure modifier' The hierarchy would look like this: 

- GONEW:  'DNA structure modifier'
-- GO:0097617 annealing activity
--- GO:1990814 DNA/DNA annealing activity
--- GO:0097098 DNA/RNA hybrid annealing activity
--- GO:0033592 RNA strand annealing activity
-- GO:0008301 DNA binding, bending

We can also add other children such as 
- GO:0003916 DNA topoisomerase activity
- GO:0034057 RNA strand exchange activity
-  GO:0004386 helicase activity

1. Is this OK ? @ValWood @thomaspd 
2. Do you prefer 'nucleic acid topology modifier' or 'nucleic acid structure modifier'? 
2. Should we add other grouping terms: DNA topology modifier and RNA topology modifier? I was wondering whether there are enough children to justify adding these. 

----

Paul had proposed to add a lot more terms, but it seems to me it's beyond just 'topology modifier', see screenshots: 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/4782928/49989759-8f988d80-ff7b-11e8-9912-76a9c8f92e3a.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/4782928/49989774-9fb06d00-ff7b-11e8-9ba9-d0b596f2f795.png">

Thanks in advance for the feedback, Pascale

**Comment by mah11** [comment]
> - GONEW: nucleic acid topology modifier
> -- GO:0097617 annealing activity
> --- GO:1990814 DNA/DNA annealing activity
> --- GO:0097098 DNA/RNA hybrid annealing activity
> --- GO:0033592 RNA strand annealing activity
> -- GO:0008301 DNA binding, bending
> 
> Is this OK ?

As drafted above, NO. It may be OK to create the "nucleic acid topology modifier" term, but it would not work as a parent of all suggested descendants. DNA bending does not alter DNA topology, and I'm not sure annealing necessarily does. DNA topology is only changed when the linking number changes, which requires breaking one or both DNA strands, i.e. what topoisomerases do.

It's not the most intuitive subject, but I found this helpful:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2643378/ (PMID:19225573)

As it stands, I'm not entirely sure anything besides topoisomerases could fit under "nucleic acid topology modifier", and if there isn't anything else, then the topoisomerase activity term itself does the necessary grouping.

> Do you prefer 'nucleic acid topology modifier' or 'nucleic acid structure modifier'?

These do NOT mean the same thing. Topology is much narrower. If you use 'nucleic acid structure modifier', then you could place a lot more terms under it.

**Comment by ValWood** [comment]
Agreed. I don't see a stong need for a grouping term for these. As I said in the previous ticket. Most have enzyme activity parent, AND DNA binding parent. This is fine

Annealing is an odd one. It seems to be used to annotate things which result in the removal of single strand binding proteins. I don't really know what the activity is but it definitely *Isn't* a topological change

**Comment by pgaudet** [comment]
Annealing is quite odd as a MF anyway. The term cites https://en.wikipedia.org/wiki/Nucleic_acid_thermodynamics#Annealing

"Annealing, in genetics, means for complementary sequences of single-stranded DNA or RNA to pair by hydrogen bonds to form a double-stranded polynucleotide. **Before annealing can occur, one of the strands may need to be phosphorylated by an enzyme such as kinase to allow proper hydrogen bonding to occur.** (...) "

Perhaps this should be a process?

**Comment by ValWood** [comment]
> Before annealing can occur, one of the strands may need to be phosphorylated by an enzyme such as kinase to allow proper hydrogen bonding to occur

really? we should tell the microarray people?
citation required !

**Comment by pgaudet** [comment]
New proposal discussed with @thomaspd 


 * GONEW:  'DNA structure modifier'
     -- GO:0097617 annealing activity
      --- GO:1990814 DNA/DNA annealing activity
      --- GO:0097098 DNA/RNA hybrid annealing activity
      --- GO:0033592 RNA strand annealing activity
   -- GO:0008301 DNA binding, bending
   -- GO:0003916 DNA topoisomerase activity
   -- GO:0034057 RNA strand exchange activity
   -- GO:0004386 helicase activity

**Comment by pgaudet** [comment]
@ValWood @mah11 Does that look better ?

**Comment by ValWood** [comment]
Do we need this term? All should have the parent
catalytic activity, acting on DNA

If you do add (I'm  a bit ambivalent)

1.  GO:0004386 helicase activity would not go under here (RNA helicases)

2. How are you defining "structure modifier"? (presumably any geometric or topological change?), shouldn't things like 
crossover junction endodeoxyribonuclease activity (GO:0008821)
recombinase activity (GO:0000150)
go under here too?

3.  I recommend we get rid of 
DNA topological change (GO:0006265)  and DNA geometric change (GO:0032392) from process? (they could point to the new proposed term?)

**Comment by pgaudet** [comment]
Is annealing a catalytic activity ? That would probably solve the issue.

**Comment by ukemi** [comment]
I don't think so. A catalyst is something that lowers the activation energy of a reaction, thereby increasing its rate,  and is not consumed.

**Comment by pgaudet** [comment]
"DNA annealing may occur spontaneously, but it is promoted in vivo by certain classes of annealing proteins. " PMID:25646379. That seems to fit the definition of a catalyst ?

**Comment by pgaudet** [comment]
Unless the catalyst needs to consume energy - I dont think all annealing 'facilitators' use ATP. But if that's not a requirement then I dont see what is missing to call this reaction a catalytic reaction.

**Comment by ukemi** [comment]
I think so yes.

**Comment by mah11** [comment]
> "DNA annealing may occur spontaneously, but it is promoted in vivo by certain classes of annealing proteins." PMID:25646379. That seems to fit the definition of a catalyst ?
> 
> Unless the catalyst needs to consume energy 

I haven't seen catalysts referred to as consuming energy or not consuming energy, but I'm fairly sure that's beside the point. Catalysts work by providing an alternative route for a reaction with a lower activation energy than the uncatalyzed version. I don't know the exact mechanism by which "facilitators" promote annealing, but it does sound like catalysis to me anyway.

**Comment by mah11** [comment]
On the more general question about the altered proposal:

I don't feel like there's a grouping term missing, i.e. I don't need a new grouping term.

I would very much need to see the definition of the proposed grouping term to understand why any deoxyribonuclease - not just the ones Val mentioned - would not also fit it. And any definition that could distinguish (topological + geometric) changes from backbone cleavage would probably cry out for a term name more specific than "structure modifier".

**Comment by deustp01** [comment]
Lowering activation energy is different from consuming net energy. Protein hydrolysis is a spontaneous (if slow) reaction; trypsin et al. increase the rate and impose specificity by providing an active site that captures specific peptides and juxtaposes them to enzyme amino acid residues and cofactors precisely positioned to support hydrolysis. No energy is consumes; some should be released.

**Comment by pgaudet** [comment]
I am happy to move the terms under catalytic activity 
-- GO:0097617 annealing activity
--- GO:1990814 DNA/DNA annealing activity
--- GO:0097098 DNA/RNA hybrid annealing activity
--- GO:0033592 RNA strand annealing activity

Pascale

**Comment by pgaudet** [comment]
Wont implement
