### ISSUE TITLE
OTR: GO:0061473 murein tripeptide carboxypeptidase activity- typo

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#16802]
GO:0061473 murein tripeptide carboxypeptidase activity

http://amigo.geneontology.org/amigo/term/GO:0061473

> Definition:  Catalysis of the reaction L-Ala-**_gamma;_**-D-Glu-meso-Dap (murein tripeptide) + H2O = L-Ala-γ-D-Glu + meso-diaminopimelate. 

The missing & in `&gamma;` is causing the letter γ not to appear. 

Also, would it be in line to make an exact synonym to help with search results?
"Catalysis of the reaction L-Ala-gamma-D-Glu-meso-Dap (murein tripeptide) + H2O = L-Ala-gamma-D-Glu + meso-diaminopimelate"

**Comment by ukemi** [comment]
We generally don't use the Greek letters, we spell them out. I will fix this term.

**Comment by pgaudet** [comment]
Added RHEA:28398 xref
