### ISSUE TITLE
Remove EC:3.1.3.41 as xref to phosphatase activity (GO:0016791)?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16819]
EC:3.1.3.41 = 4-nitrophenylphosphatase (4-nitrophenyl phosphate + H(2)O <=> 4-nitrophenol + phosphate)
https://enzyme.expasy.org/EC/3.1.3.41

I'm not sure if this should really be an xref (and included in the def) of phosphatase activity (GO:0016791)?  The other partial xref (EC:3.1.3.-) is fine.

**Comment by hdrabkin** [comment]
This was due to a merge; that ec should have been removed; done

**Comment by sjm41** [comment]
Thanks Harold.
Can/did you remove this EC from the definition line as well?  Current full definition reads:
"Catalysis of the hydrolysis of phosphoric monoesters, releasing inorganic phosphate." [EC:3.1.3, EC:3.1.3.41, GOC:curators, GOC:pg]

**Comment by hdrabkin** [comment]
yes; it is gone gone
