### ISSUE TITLE
fix taxon restriction 'iron ion import across cell outer membrane'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16829]
'iron ion import across cell outer membrane' SubClassOf 'only in taxon' some Bacteria

from
https://github.com/geneontology/go-ontology/issues/16776

**Comment by ukemi** [comment]
Since both organelles and bacteria can have outer membranes, I will remove the TR.

-D

**Comment by ValWood** [comment]
This term is still unavailable to us?

**Comment by ukemi** [comment]
Looks like it is coming from the restriction on 'cell envelope'. Are you sure you want the 'cell outer membrane' taxon restriction removed? 'Cell outer membrane' is a part_of 'cell envelope'. 

Cell outer membrane: A lipid bilayer that forms the outermost membrane of the cell envelope; enriched in polysaccharide and protein; the outer leaflet of the membrane contains specific lipopolysaccharide structures.

**Comment by ValWood** [comment]
I'm not sure what the problem is. All I know is that there is a taxon restriction somewhere that prevents us from using the term?
But I can't see what the taxon restriction is.

**Comment by ValWood** [comment]
I just rechecked and the term is still unavailable to us

**Comment by ukemi** [comment]
I see the taxon restriction, but do yeast have an outer CELL membrane and is it part_of a 'cell envelope'? Is this really the term you want to use?

**Comment by ValWood** [comment]
Actually the term I can't approve is this one
GO:0033573    high-affinity iron permease complex

**Comment by mah11** [comment]
yeah, that's all part of the chain from https://github.com/geneontology/go-ontology/issues/16776#issuecomment-449491917 ... and it's the GO:0015092 part_of GO:0098706 link that looks most suspect to me

**Comment by ValWood** [comment]
See the comment from @balhoff in the previous ticket:
---

Sorry for the slow reply! This one is due to an actual taxon constraint:

'high-affinity iron permease complex' SubClassOf 'capable of' some 'high-affinity ferric iron transmembrane transporter activity'
'high-affinity ferric iron transmembrane transporter activity' SubClassOf 'part of' some 'iron ion import across cell outer membrane'
'iron ion import across cell outer membrane' SubClassOf 'only in taxon' some Bacteria

**Comment by ukemi** [comment]
I think @mah11 is correct. 

Based on the def:

'high-affinity ferric iron transmembrane transporter activity' SubClassOf 'part of' some 'iron ion import across cell outer membrane'

should be:
'high-affinity ferric iron transmembrane transporter activity' SubClassOf 'part of' some 'iron ion transmembrane transport'

**Comment by mah11** [comment]
@ukemi - yes, that sounds good. phew!

**Comment by Antonialock** [comment]
yep sounds good

**Comment by ukemi** [comment]
OK. I will fix this. I can actually do it with some shuffling of terms further up the graph that don't seem to have necessary and sufficient definitions. Thanks Everyone.
