### ISSUE TITLE
Remove EC:6.2.1.20 from definition of fatty acid ligase activity (GO:0015645)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16820]
EC:6.2.1.20 doesn't appear as an xref/synonym to this term, but is quoted in the definition.  I don't think it's appropriate and should be removed.

**Comment by hdrabkin** [comment]
Current def:Catalysis of the ligation of a fatty acid to an acceptor, coupled to the hydrolysis of ATP.
this  Rhea fits the def better
RHEA:51580 | a fatty acid(out) + ATP(in) + CoA(in) + H(+)(out) = AMP(in) + an acyl-CoA(in) + diphosphate(in) + H(+)(in)
and is associated with EC:6.2.1.3 at RHEA

**Comment by sjm41** [comment]
Just to be clear, the full definition line in GO is:
**"Catalysis of the ligation of a fatty acid to an acceptor, coupled to the hydrolysis of ATP." [EC:6.2.1.20, EC:6.2.1.3, GOC:cjk, GOC:mah]**

I'm requesting/suggesting that the "EC:6.2.1.20" be removed as an attribution/source.

**Comment by hdrabkin** [comment]
It appears this was done a while ago and I never closed the ticket
