### ISSUE TITLE
ntr  spindle pole body anchor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16832]
I want to annotate that cut11 is a "spindle pole body anchor

I'm using

GO:0043495 | protein membrane anchor

do I need a term "spindle pole body anchor"
or can I do this:

cut11 | GO:0043495 | protein membrane anchor | IDA  | has_input mitotic spindle pole body

**Comment by ukemi** [comment]
has_input is a relation between a continuant and an occurent.

**Comment by ValWood** [comment]
So I guess that means we could post compose using the GO ID with has input?. What is preferred?

**Comment by hdrabkin** [comment]
After some discussion, we think it would just be better to make the new term "spindle pole body anchor"
I need a suggested def and parent, PMID,

**Comment by ValWood** [comment]
term:  mitotic spindle pole body anchor
Def:
Interacting selectively and non-covalently with a mitotic spindle pole body and a membrane, in order to maintain specific membrane location of the spindle pole body.


PMID:9763447
cut11(+): A gene required for cell cycle-dependent spindle pole body anchoring in the nuclear envelope and bipolar spindle formation in Schizosaccharomyces pombe.
West RR, Vaisberg EV, Ding R, Nurse P, McIntosh JR.

**Comment by hdrabkin** [comment]
Thanks @ValWood 
is_a GO:0043495 | protein membrane anchor?

**Comment by ValWood** [comment]
yes ;)

**Comment by hdrabkin** [comment]
Sorry; no sleep last night and now have noisy office space neighbors

id: GO:0106166
name: spindle pole body anchor
