### ISSUE TITLE
protein-containing complex binding: pre-compose X complex binding terms or use extensions?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16833]
if we are precomponsing these (I think I saw some recently), I would like:
   nuclear MIS12/MIND complex (GO:0000818) complex binding

standard definition
PMID:29180432

**Comment by bmeldal** [comment]
Yes, we are precomposing these as I can't create CP entries for all the GO complexes at the rate you guys are annotating ;-) I'd need an army of curators...

Term should be *nuclear MIS12/MIND complex binding* (just 1x "complex")

**Comment by cmungall** [comment]
Curious why you need to pre-compose the binding term Val, as can easily be done in extensions?

**Comment by ValWood** [comment]
I don't need to- but I would rather do them all the same way, as I really dislike having a mixture, or not using a  suitable term that is present- it's confusing for users.

I would  be happy to post-compose but I think we should then get rid of the existing ones:
https://www.ebi.ac.uk/QuickGO/term/GO:0044877

**Comment by bmeldal** [comment]
Ok, let's discuss this on the call on Thursday as it's a general decision that needs making.

**Comment by bmeldal** [comment]
Related to https://github.com/geneontology/go-annotation/issues/1876

**Comment by bmeldal** [comment]
@srengel : item 3 on Thursday's Complex WG call (5 pm GMT / 12 noon EST / 9 am PST - did I get the time zones right?)

**Comment by ukemi** [comment]
If done correctly, the precomposed terms versus the terms using annotation extensions should be semantically identical, so it shouldn't create any reannotation problems downstream.

**Comment by ValWood** [comment]
Even though they are the semantically equivalent it is confusing for users and community curators to have 2  different ways of saying the same thing. It would be nice that at certain points in the ontology we either pre-compose or post compose  (allowing interconversion to flatten/unflatten when required). 
Maybe there are reasons that this is not possible though...

**Comment by srengel** [comment]
"Even though they are the semantically equivalent it is confusing for users and community curators"

i would add professional curators to this list as well.  trying to explain all this to new curators is problematic.

**Comment by bmeldal** [comment]
Discussed:
Annotation review required:
GP1 | protein-containing complex binding | IPI | "protein|gene ID|CP AC|multiple proteins" 
or
GP1 | protein-containing complex binding | IPI | GP2 EXT has_direct_input "complex AC"
where "with" protein is expt interactor and GP2 is part of a complex acc to another expt
--> should this be IC?
--> allow with extention unless CP AC in WITH/FROM

related:
ISS without extension should not be used! - all agree --> ticket!
GP1 | protein-containing complex binding | ISS | GP2 EXT has_direct_input "complex AC"
Which complex is it? Expt complex or ISS complex??? Probably the expt complex.

**Comment by bmeldal** [comment]
Example of GP1 binding Cpx1:
https://www.ebi.ac.uk/intact/interaction/EBI-11579151

Example of GP1 binding GP2 in Cpx1:
https://www.ebi.ac.uk/intact/interaction/EBI-10915922
(we don't display GP2 on the website but we can select it in the editor)

**Comment by bmeldal** [comment]
Call 31/1/19:

Edith: would it be the same for IDA? --> provide example.

**Comment by bmeldal** [comment]
Presented at Cambridge GOC mtg on 11/4/19:

Agreed to no longer use pre-composed "x complex binding" terms but with/from field (and AE where required).

- [Rule implementations](https://github.com/geneontology/go-site/issues/1056) - ticket in progress
- Obsoletion tickets: to be created (will be linked to *rule* ticket)
- Annotation review ticket: to be created

Closing as new ticket will capture remaining tasks.
