### ISSUE TITLE
Add RHEA xrefs where possible to the Plant/Metacyc enzyme requests

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#16839]
As discussed on the Ontology call (1/7/2019) Harold will add RHEA xrefs to the set of Plant enzyme activity terms added under issue 10873; https://github.com/geneontology/go-ontology/issues/10873)  where a full EC is specified. Check that EC and RHEA agree; If good will add manually ; Punt questions to Peifen via Tanya

**Comment by tberardini** [comment]
Consult with Peifen resulted in these suggestions/comments:

1. The stereospecificity captured in the Metacyc reaction request is critical.  Try to preserve this information as much as possible.
2. ChEBI names, where possible, were used in the reactions at GO's request.
3. Full EC numbers could now be available for those Metacyc reactions that previously only had partial ones as Ron C. at MetaCyc might have created new EC entries and then cross-referenced them to MetaCyc in the years since the original request.  Suggest using SmartTables functionality at MetaCyc to input Metacyc reaction ids and output EC ids.

**Comment by hdrabkin** [comment]
Is she comfortable with the notion that once a RHEA gets assigned, the RHEA def will replace the original term def. ?

**Comment by ukemi** [comment]
Note Rhea does capture stereospecificty, but this may be lost if we map to the pH 7.3 entities. We will need to look into whether or not this will happen. Tag @balhoff #16777

**Comment by deustp01** [comment]
Maybe I'm missing something here but it looks like Rhea can handle stereochemistry and ionization state at the same time, e.g. RHEA:13913 "L-threonine = D-threonine" https://www.rhea-db.org/reaction?id=13913

**Comment by tberardini** [comment]
Adding @peifenz

**Comment by peifenz** [comment]
Harold, it will be really nice if somewhere you could include a notion of the history of replacing the EC with Rhea for the set of terms I submitted for PMN.

**Comment by hdrabkin** [comment]
Hi @peifenz 
Well, the plan would be that this would occur for those that I manual add the RHEA xref. 

Here is an example of one that would not be different

[Term]
id: GO:0102198
name: L-idonate 5-dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-idonate + NAD= 5-dehydro-D-gluconate + NADH + H+" [EC:1.1.1.366]
xref: EC:1.1.1.366
xref: MetaCyc:RXN-12107
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
EC name: L-idonate 5-dehydrogenase (NAD(+)); rxn def ok; metacyc ok ; would map to RHEA:21172
RHEA L-idonate + NAD(+) = 5-dehydro-D-gluconate + H(+) + NADH

**Comment by peifenz** [comment]
Do you mean that RHEA is added as another xref line, and you won't change the EC part in the def line? If so, no problem at all.

**Comment by hdrabkin** [comment]
RHEA will be added as an additional XREF; the EC xref will stay, but the def you provided will be replaced with the RHEA def. RHEA becomes the authority for the reaction def.

**Comment by hdrabkin** [comment]
When I find one that will change significantly, I'll fly it by you first

**Comment by peifenz** [comment]
I see. I also just read the previous messages in this thread. I understand your plan better now. Sure, I could check them out.

**Comment by hdrabkin** [comment]
24 added on 2-15-19

**Comment by pgaudet** [comment]
@hdrabkin can we close this?

**Comment by hdrabkin** [comment]
Yes lets close; we handle these through other tickets as needed (remove 3 digit ECs to leaves, etc.).
