### ISSUE TITLE
ARE binding element query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16842]
In GO we have

GO:0017091 | AU-rich element binding

and

ARE binding | exact

An ARE binding motif has a very  defined consensus (conserved from yeast to human), so maybe we should add that to the definition ?
ARE UUAUUUAUU

I'm slightly confused by why the child term specifies  3'-UTR
GO:0035925    mRNA 3'-UTR AU-rich region binding

but  GO:0017091 | AU-rich element binding
does not because functional  ARE-elements  are in the 3'UTR? 
so both terms should be consistent.

(if we need them).

Note the SO definition of
U_rich_element    (CURRENT_SVN)
http://www.sequenceontology.org/browser/current_svn/term/SO:0001180
 A cis-acting element found in the 3' UTR of some mRNA which is rich in AUUUA pentamers. Messenger RNAs bearing multiple AU-rich elements are often unstable.

**Comment by vanaukenk** [comment]
@ValWood 
It looks like we should move the ARE synonyms from the parent, GO:0017091, to the child term, GO:0035925, and review the experimental annotations to the parent as at least some of these annotations seem to describe binding to an ARE in an mRNA 3'-UTR.
It seems that would clarify the distinction between the two terms better and make the annotations more consistent. 
What do you think?

**Comment by ValWood** [comment]
OK-  I'm not sure what the parent would refer to if not  to GO:0035925
but if you move  the synonym I am fine with  that. I'll make sure any annotatiosn we have move down to GO:0035925.

cheers
val

**Comment by pgaudet** [comment]
Why do we need both the parent and the child ? Are there AU-rich elements in other RNAs ?

**Comment by ValWood** [comment]
I thought they should merge.... I wanted the precise definition and I guess it wasn't clear whether there were different *types* of AU  rich elements outside of UTRs, but if defined precisely I think we only need one term?

**Comment by pgaudet** [comment]
All EXP annotations are to the mRNA child, expect for ELAVL1 Q15717, which is probably an oversight, as it is described in UniProt as "RNA-binding protein that binds to the 3'-UTR region of mRNAs and increases their stability"

I'll do the merge and improve the definition.

**Comment by pgaudet** [comment]
PMC6804641 mentions U-rich sequences such as UUUUUUU, UUUAUUU and UUUGUUU as well as common AU-rich motifs such as UAUUUAU. I dont know if we should specify the sequence ? 

@colinlog Any suggestions ? 

Thanks, Pascale

**Comment by ValWood** [comment]
That's why I wanted it to be more specific. I wanted ARE which is UAUUUAU  probably minimally AUUUA consensus, not any old UUUUUUU

**Comment by pgaudet** [comment]
In this case do we need 'U binding element ?

**Comment by ValWood** [comment]
Not sure.
I only need ARE-element is_a AU rich element with the consensus UAUUUAU in the 3'UTR

there might be other types of AU-rich element in mRNA, I'm not sure. This is the only one I'm aware of that is functionally defined.

**Comment by pgaudet** [comment]
How about this as a def : "Interacting selectively and non-covalently with a region containing frequent adenine and uridine bases within the 3' untranslated region of a mRNA molecule. The consensus binding site for AU-rich binding proteins is UUAUUUAUU. AU-rich binding proteins control the stability and/or translation of mRNAs."

Thanks, Pascale

**Comment by ValWood** [comment]
"Interacting selectively and non-covalently with a region containing frequent adenine and uridine bases within the 3' untranslated region of a mRNA molecule. The ARE-binding element consensus ~binding site for AU-rich~  ~proteins~ is UUAUUUAUU. ~AU-rich~ ARE-binding element binding proteins control the stability and/or translation of mRNAs."

**Comment by pgaudet** [comment]
Thanks, this sounds better. 

I further simplified to 

ARE-binding proteins control the stability and/or translation of mRNAs (from "ARE-binding element binding protein"). 

Thanks, Pascale

**Comment by colinlog** [comment]
On the sequence motif side of this ticket I agree with what was said in the
last few hours. The notion that UAUUUAU is the *consensus* implies that
there may well be a UUUUUUU sequence that functions as an ARE. It is
therefore superfluous to add the other possible sequences.

However, I would like to add that many AREs are in introns and there may
well be 5'UTRs with AREs. See

The AU-rich element landscape across human transcriptome reveals a large
proportion in introns and regulation by ELAVL1/HuR
for a literature reference on this. From that I gather that there are more
intronic AREs than 3' UTR AREs. This may be a reason to change the
parentage of GO:0035925 away from GO:0003730 and towards GO:0003729?

**Comment by pgaudet** [comment]
OK, I'll change the parent and add this to the definition. 

I suppose intronic AU-rich elements  are not involved in mRNA stability and translation ?

**Comment by pgaudet** [comment]
Changed definition as follows: 

Interacting selectively and non-covalently with a region containing frequent adenine and uridine bases within the 3' untranslated region of a mRNA molecule or in pre-mRNA intron. The ARE-binding element consensus is UUAUUUAUU. ARE-binding proteins control the stability and/or translation of mRNAs.
