### ISSUE TITLE
RNA 2'-O-methyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#16849]
Hi,
I would need a generic term for RNA 2'-O-methyltransferase activity

Thanks

Sylvain

Description: Catalysis of the reaction: S-adenosyl-L-methionine + RNA = S-adenosyl-L-homocysteine + RNA containing 2'-O-methylribonucleotide. 

Child of  
GO:0008171 O-methyltransferase activity
GO:0008173 RNA methyltransferase activity

Parent of:
GO:0090486 small RNA 2'-O-methyltransferase
GO:0030743 rRNA (adenosine-2'-O-)-methyltransferase activity
GO:0070677 rRNA (cytosine-2'-O-)-methyltransferase activity
GO:0004483 mRNA (nucleoside-2'-O-)-methyltransferase activity
GO:0008650 rRNA (uridine-2'-O-)-methyltransferase activity
GO:0106050 tRNA 2'-O-methyltransferase activity
GO:0070039 rRNA (guanosine-2'-O-)-methyltransferase activity

PMID:30626973;
Cross-reference RHEA:58956 (not yet public)

**Comment by ukemi** [comment]
PR #16863
Will add Rhea when public. Tagging.
