### ISSUE TITLE
TPV in  nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16846]
GO:0043928    JSON
exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay

has the child

GO:0070478    nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay

this is incorrect. Deadenylation-dependent decay isn't nonsense -mediated

**Comment by ukemi** [comment]
The term names and IDs in this request don't match up, but I think I found the error ans have fixed it.
