### ISSUE TITLE
DNA polymerase processivity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16847]
DNA polymerase processivity factor activity
Molecular Function

Definition (GO:0030337 GONUTS page)
An enzyme regulator activity that increases the processivity of polymerization by DNA polymerase, by allowing the polymerase to move rapidly along DNA while remaining topologically bound to it. PMID:7903401 PMID:8087839

therefore should have a "regulates" relationship to "DNA polymerase" not just "enzyme regulator"?

![processivity](https://user-images.githubusercontent.com/7359272/51051094-aeb22b80-15ca-11e9-8c87-a8d57ef87280.jpg)

**Comment by keslingmj** [comment]
Hi Val,

Yes, the processivity factor activity directly affects DNA polymerase (or a DNA polymerase complex).
It’s probably obvious to you, but it is distinct from the DNA polymerase activity.

**Comment by ValWood** [comment]
Closing. I'm not sure what  I was thinking of here...

**Comment by pgaudet** [comment]
Well, that would be similar to 'protein kinase regulator activity', where we have: 

molecular_function
 and ('directly regulates' some 'protein kinase activity')

So, I think this can be implemented.

**Comment by pgaudet** [comment]
Actually all logical definitions of those enzyme regulators activity terms should be fixed. 


Thanks, Pascale

**Comment by ValWood** [comment]
So what is the action, just to add a relation (this can be closed for me)

**Comment by pgaudet** [comment]
We now have 
'molecular function regulator activity'
 and ('positively regulates' some 'DNA polymerase activity')


So I think this can be closed.
