### ISSUE TITLE
nuclear-transcribed mRNA catabolic 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16843]
This term
GO:0043928    exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay

seems to be describing a single step  in this process (3'-5'-exoribonuclease activity)
?

I'm struggling a lot to locate the correct terms in this area - lots appear to be MF single  steps.

For this, I think I should use the parent?
deadenylation-dependent decapping of nuclear-transcribed mRNA

and suggest a term merge
of 
GO:0043928    exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay

**Comment by ValWood** [comment]
Actually, it's probably a grouping term for  3'-5' and 5'-3' which both occur as part of 
deadenylation-dependent decay, but is it really necessary to group a process sub-part just because it is functionally similar?

**Comment by ValWood** [comment]
Actually, although it isn't evident from the term name, this is for the degradation if the transcript body, and it seems to exist to differentiate the degradation of the transcript body from the degradation of the polyA tail which are distinct but overlapping mechanism.

There is probably a better way to do this using SO extensions.

Anyway for now, since it exists, I used it.

and In this case could I get a positive regulation term?

Is there a way to change the term name to make it clearer?

**Comment by ValWood** [comment]
It's tricky because I don't think a word exists to describe the processed but deadenylated mRNA...

**Comment by hdrabkin** [comment]
Hi @ValWood 
clarify please:   +  regulation term for the GO:0043928  term?
PMID for ref

**Comment by ValWood** [comment]
yep 
PMID:30601114

**Comment by hdrabkin** [comment]
id: GO:0106163
+name: regulation of exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay
+[Term]
+id: GO:0106164
+name: positive regulation of exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay
+[Term]
+id: GO:0106165
+name: negative regulation of exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay

**Comment by srengel** [comment]
this is another confusing case of 'why are we making these long involved-in terms' instead of using extensions and GO-CAM.

**Comment by ValWood** [comment]
I think so far we only tried to purge 
"function " involved_in "process" becuse it si very clear how to precompose these and it folloes NOctua modelling.

This is slightly different. It looks like a "process" involved in "process" term, but really its just a very, very clunky way to refer to apart of  "deadenylation-dependent decay".

I had some inspiration how to improve this term name to remove the involved in and make this 
 part of process clearer,  I'm trying to remember what it was...

**Comment by hdrabkin** [comment]
These are now in as per the request. Can I close this ticket?

**Comment by ValWood** [comment]
Got it, Harold could you rename these to

exonucleolytic nuclear-transcribed mRNA catabolic process  of deadenylated mRNA
+ regulation

Everything else (parent and definition) is the same but it will be much clearer to a curator which step in the process this refers to. It took me ages to figure this out....It's the process of degradation (usually exosomal) , of the processes pre-mRNA *after* the polyadenylated residues are removed by CCR4-NOT (usually).

(you would still need this term for Noctua there isn't another way to make this annotation clear)

In fact I don't know why we need to specify 
 "nuclear-transcribed mRNA catabolic"  in the  adenylation-dependent branch, this is a give, so it  could even be:


exonucleolytic catabolic process  of deadenylated mRNA

**Comment by srengel** [comment]
"exonucleolytic catabolic process of deadenylated mRNA"

oo i like this much better!

**Comment by hdrabkin** [comment]
GO:0043928 exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-dependent decay would also get renamed.
'exonucleolytic catabolic process of deadenylated mRNA'
seems a little odd. You want to say the exonucleolytic cat proc that has deadenylated mRNA as it's target yes?

**Comment by hdrabkin** [comment]
exonucleolytic catabolism of deadenylated mRNA?

**Comment by ValWood** [comment]
Yes this is exactly what it means

def is
The chemical reactions and pathways resulting in the breakdown of the transcript body of a nuclear-transcribed mRNA that occurs when the ends are not protected by the 3'-poly(A) tail.

http://mpmp.huji.ac.il/maps/mRNAdeg.html
its  the parts after deadenylation

![deadennylation](https://user-images.githubusercontent.com/7359272/51194793-b4b64e00-18e3-11e9-8617-5e716ee82b53.jpg)

I think the ontology  could be simplified in this area, but this works for now and is clearer than the existing term.

**Comment by hdrabkin** [comment]
ok, I can change the names of all of these later today.

**Comment by hdrabkin** [comment]
name changes incorporated.
