### ISSUE TITLE
ntr RNA binding term PRE-element 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16841]
I would like a term to represent  "RNA PRE-element binding"

Interacting selectively and non-covalently with a region of RNA containing a PRE element (consensus) UGUAAAUA

We have lots of other RNA  binding specificity elements, so we should either add this one or punt them all to SO extensions.

PMID:30601114
parent 
GO:0003723 | RNA binding

**Comment by ukemi** [comment]
Does this element exist in SO?

**Comment by ValWood** [comment]
Not yet, 
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/455

there does not appear to be any activity on this tracker though....

**Comment by ukemi** [comment]
Wouldn't this just be an AU-rich element? That term already exists.

**Comment by ukemi** [comment]
OK. I see in the paper that they are separate.

**Comment by ValWood** [comment]
Yes they are different elements 

Tristetraprolin ->AREs
Pumilio PREs

**Comment by ValWood** [comment]
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/455
SO term now exists for logical def
SO:0002234 pumilio_response_element

**Comment by ValWood** [comment]
I only reopened this for the logical definition, so if this can. be added this can then close.

**Comment by pgaudet** [comment]
Added to SO imports. Can complete when SO imports have ran.

**Comment by pgaudet** [comment]
id: GO:0062104
name: pumilio-response element binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with a region of RNA containing a Pumilio-response element element. The consensus sequence for the element is UGUAAAUA." [PMID:30601114]
synonym: "PRE binding" EXACT [PMID:30601114]
is_a: GO:0003723 ! RNA binding
created_by: dph
creation_date: 2019-01-11T13:38:26Z
