### ISSUE TITLE
what is the difference, mRNA catabolic process terms?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16844]
positive regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
Any process that activates or increases the frequency, rate or extent of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay.

has the child term
positive regulation of nuclear-transcribed mRNA poly(A) tail shortening
Any process that increases the frequency, rate or extent of poly(A) tail shortening of a nuclear-transcribed mRNA. Poly(A) tail shortening is the decrease in length of the poly(A) tail of an mRNA from full length to an oligo(A) length.

What is the difference?

**Comment by ValWood** [comment]
I think I understand
GO:0000289    nuclear-transcribed mRNA poly(A) tail shortening
is only one step

**Comment by ukemi** [comment]
I was just writing that.

**Comment by ValWood** [comment]
OK :)

There is a small issue. I only found the term in the "regulation branch"  but not from
nuclear-transcribed mRNA catabolic process, deadenylation-dependent 

(I think there is a missing parent?)

**Comment by ValWood** [comment]
I should warn you I am still on figure 1 of this paper!

**Comment by ukemi** [comment]
I think that is because the tail shortening can happen independently of the catabolism. IIRC correctly from my old embryology days, in some early embryos like surf clams and sea urchins the polyA tail controls the movement of mRNA in and out of the nucleus and also controls its subsequent translation. 

I think that is still believed to be true. PMID:24910447

**Comment by ValWood** [comment]
but isn't this part of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay

the translation is controlled by the degradation?

**Comment by ValWood** [comment]
also 
positive regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay

has the child term
positive regulation of nuclear-transcribed mRNA poly(A) tail shortening

**Comment by ValWood** [comment]
AFIIK the deadenylation isn't related to nucleocytoplasmic transport (the polyA may be required for transport but its removal doesn't happen until it's in the cytoplasm)

**Comment by ValWood** [comment]
There is a overview nice figure in this review
https://www.nature.com/articles/nrm2104

**Comment by ukemi** [comment]
I guess I am confused. What relationship do you think is missing?

**Comment by ukemi** [comment]
But maybe I am showing my age, I thought things were different in oocytes..  
PMID:2628165
PMID:29972882 
PMID:24910447

**Comment by ukemi** [comment]
PMID:29467249
PMID:24476825

But I haven't really studied this field for a while, so if you think all of this translational control via polyA tail length is achieved by simply regulating catabolism, I will go with your more current knowledge.

I still need to know what relationship you want.

**Comment by ValWood** [comment]
PMID:29467249 says

 poly(A) tail is important for mediating the translocation of a completely processed
mRNA to the cytoplasm

This is true, this is pre-deadenylation though.

In addition, poly(A) tails can play key regulatory roles in
enhancing translation efficiency 

This is true but I don't think that impacts that deadenylation is targeting for decay?

and 
 "When an mRNA is no longer being used for translation, poly(A) tail
shortening is one of the key steps initiating decay of the body of the message "

Since in this ticket , we are referring only to  the deadenylation part, I think this relationship is safe.  

I will check this with an expert, if you still have doubts, but at the moment we are inconsistent.

positive regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent 
has the child term
positive regulation of nuclear-transcribed mRNA poly(A) tail shortening

but
nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
does not have the child
mRNA catabolic process, deadenylation-dependent decay.

**Comment by ukemi** [comment]
I don't see this term: mRNA catabolic process, deadenylation-dependent decay

**Comment by ValWood** [comment]
Corrected above comment. I copy pasted the wrong part

**Comment by ukemi** [comment]
I see the child. 
nuclear-transcribed mRNA poly(A) tail shortening 
'part of' some 'nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay'

**Comment by ValWood** [comment]
hmmph, i'm sure something was missing, but you are right this is all correct.

**Comment by ukemi** [comment]
OK. If you find something just reopen.
