### ISSUE TITLE
revise Definition CCR4-NOT complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16840]
current def
The evolutionarily conserved CCR4-NOT complex is involved in several aspects of mRNA metabolism, including repression and activation of mRNA initiation, control of mRNA elongation, and the deadenylation and subsequent degradation of mRNA. In Saccharomyces the CCR4-NOT complex comprises a core complex of 9 proteins (Ccr4p, Caf1p, Caf40p, Caf130p, Not1p, Not2p, Not3p, Not4p, and Not5p), Caf4p, Caf16p, and several less well characterized proteins.

proposed def
The Ccr4-Not complex is an eukaryotically   conserved deadenylase that can initiate cytoplasmic mRNA decay, and reduce translation by releasing poly(A)-binding protein (Pab1/PABPC1). Ccr4-Not contains seven core subunits, including two poly(A)-specific exonucleases, Ccr4/CNOT6/CNOT6L and Caf1/Pop2/CNOT7/CNOT8

(it seems more appropriate to focus on the  the "deadenylase activity")

ADD refs
Parker, R. (2012). RNA degradation in Saccharomyces cerevisae. Genetics 191, 671–702.

Tucker, M., Valencia-Sanchez, M.A., Staples, R.R., Chen, J., Denis, C.L., and Parker, R. (2001). The transcription factor associated Ccr4 and Caf1 proteins are components of the major cytoplasmic mRNA deadenylase in Saccharomyces cerevisiae. Cell 104, 377–386.

and 
PMID:30601114
Title: | RNA-binding proteins distinguish between similar sequence motifs to promote targeted deadenylation by Ccr4-Not.
Authors: | Webster MW, Stowell JA, Passmore LA

**Comment by hdrabkin** [comment]
PMID:11239395 and PMID:22785621

**Comment by ValWood** [comment]
Can the def be updated, then this can close?

Although I think @colinlog  was going to ask about  somebody about  CCR4-Not?

**Comment by hdrabkin** [comment]
done
