### ISSUE TITLE
NTR: question PAMP  binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16857]
Is it possible to have a term for

NTR PAMP  binding
--NTR chitin PAMP binding (broad chitin fragment binding)

Fungal pathogens  have cell surface chitin that is recognised by the host, and broken down by host chitinases.
These fragments if can elicit a "PAMP triggered immunity".
Therefore to evade this response the fungi produces a "chitinase-like protein"   which binds to and masks these fragments from the host.

PAMP binding
Interacting selectively and non-covalently with a  pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species.

chitin PAMP binding
Interacting selectively and non-covalently with a  chitin fragment which function  as a PAMP, structures conserved among microbial species.

**Comment by ValWood** [comment]
One question is whether we want to add the specific PAMPs with extensions.

**Comment by ValWood** [comment]
ref Suppression of Plant Immunity by Fungal Chitinase- like Effectors
PMID: 30220500

@CuzickA

**Comment by deustp01** [comment]
Terms for specific PAMPs? In principle, no. They're typically not proteins but in the spirit of not having protein-specific GO terms there probably shouldn't be terms for specific polysaccharides either. If the issue were only human responses to PAMPs, one could define PAMP families that are more general and abstract by looking at how the human host is handling the PAMP, i.e., which TOLL-like receptor family is activated, which in turn is a function of where the PAMP is presented to the host cell (cell surface vs endosome, for example) and what chemical class the PAMP falls into (ds RNA versus polysaccharide, for example). No clue here whether this works for the full range of PAMPs and the full range of host organisms.

**Comment by ValWood** [comment]
OK so can we have 
PAMP binding
Interacting selectively and non-covalently with a pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species.

and then can precompose the rest.

I'd like this os that some MF can be connected to the process.
I can post compose chitin.

**Comment by addiehl** [comment]
Are most PAMPs available as ChEBI IDs or some other ontology (for the purposes of post-composition)?

**Comment by ValWood** [comment]
I couldn't find anythign resembling PAMP in CHEBI so this grouping term would be useful.  It's likely we can find something to  put in the slots .....

**Comment by ukemi** [comment]
Good point @addiehl. I guess I will make the term (reluctantly).

**Comment by deustp01** [comment]
This may be a tangent, but PAMP (pathogen-associated molecular pattern) is more nearly a role than a class of chemicals.

**Comment by deustp01** [comment]
Certainly when a mammalian Toll-like receptor is doing the binding here. Ignorance here about generality - are there lipopolysaccharide-binding proteins in bacteria etc. that have non-innate-immunity functions?

**Comment by ValWood** [comment]
Not all lipopolysaccharides are PAMPs are they? they would only be a PAMP if in the context of a host-pathogen interaction.

I 'm also trying to find suitable activity term for the gene product (in this case we could skip the PAMP- binding term and build that into the activity). I can't see anything suitable.

It's a pathogen protein which binds to PAMPs (in this case the chitin fragment), to conceal from the PAMP receptor? It's a type of pathogen effector but clearly we probably don't want to put effector into GO  as they are a homogenous group of  proteins (and non-proteins), and act in different ways. I'm stuck! I can't don't know how we would label it.

I was going to avoid this until it became clearer by  doing

MF chitin PAMP binding part_of 
GO:0052034 | negative regulation by symbiont of microbe-associated molecular pattern-induced host innate immune response

**Comment by mah11** [comment]
> Not all lipopolysaccharides are PAMPs are they? they would only be a PAMP if in the context of a host-pathogen interaction.

If so, sounds like @d is right s PAMP is a role rather than a structural chemical classification.

> I'm also trying to find suitable activity term for the gene product

GO:0038187 ! pattern recognition receptor activity or its only subclass, GO:0008329 ! signaling pattern recognition receptor activity? Both specifically mention PAMP in the defs.

**Comment by mah11** [comment]
fixed @ ref for P D'E ...

**Comment by ValWood** [comment]
No- it isn't a "pattern recognition receptor activity"
It is a pathogen protein masking the chitin fragments from the host PRR receptor.
It evolved from a chitinase, its chitinase related with no active site.

**Comment by mah11** [comment]
In that case, it sounds like chitin binding, and best to connect to the PAMP business via some part_of BP extension. The reason I think so is because of the "PAMP is a role" angle. The optimal BP may be some regulation-of-MF thing that regulates the pattern recognition receptor by competing for its ligand.

**Comment by addiehl** [comment]
Finding the appropriate synonyms is important then.  The existing name is long, but fits de facto naming patterns of GO.

**Comment by ukemi** [comment]
chitin binding part_of "BP negative regulation of pattern recognition receptor activity" part_of GO:0052034 | negative regulation by symbiont of microbe-associated molecular pattern-induced host innate immune response

Looks like a GO-CAM model to me.

**Comment by ukemi** [comment]
Since this isn't my field at all, when the discussion is settled could someone give me a summary of the edits I need to make?

**Comment by ValWood** [comment]
I'll speak with @CuzickA  and  Co  to see if we can come up with a way to represent the MF that will be recognisable to the pathogen community.  We don't have anything to represent this type of activity in GO. 

I really think it will be confusing  for this community to represent a well-studied MF as

"binding activity has_regulation_target (BP  regulation_of_MF)"

This would be equivalent to representing a

"transcription coregulator activity" as
"Protein binding" has_regulation_target "regulation of DNA binding transcription factor activity'

It is semantically correct but it wouldn't helpful for  the pathogen community

The seem to be short of names for  these individual concepts. Everything is called an "effector".

**Comment by ValWood** [comment]
I spoke with our collaborators and  Kim Hammon-Kosack thought that

"receptor decoy activity" was the correct MF to describe what this gene product is doing.

basically, it is a pathogen gene product (ex-chitinase) which has been repurposed to 
bind and sequester chitin fragments away from the host receptor. It doesn't look like a  traditional receptor.

ntr  receptor decoy activity
def 
A gene product which recognizes, binds and sequesters specific receptor ligands
in order to prevent it from binding to its regular receptor

ntr: PAMP receptor decoy activity
A pathogen (or symbiont) gene product which recognizes and binds and sequesters  host  PAMP ligands in order to prevent it from binding to  the host PAMP receptor

PMID: 20724636

If we ever have a sequestering activity, these terms would be a child

Currently I can only see "binding' as a suitable parent for ntr  "receptor decoy activity" but 

 "PAMP receptor decoy activity" could have "antigen binding"

I can't immediately think of a way to specify a "chitin fragment" as a substrate, but maybe we can just use chitin?

**Comment by pgaudet** [comment]
We do have 'GO:0048019 receptor decoy activity' as a synonym of 'receptor antagonist activity' (The activity of a gene product that interacts with a receptor to decrease the ability of the receptor agonist to bind and activate the receptor.)

We can create 'PAMP receptor decoy activity' as a child of GO:0048019. Would that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm not sure that  "receptor decoy activity'" should be a synonym of 'receptor antagonist activity' 
though.

an agonist binds to the receptor, and  the decoy is an indpendent  gene product to the receptor

**Comment by pgaudet** [comment]
You seem to describe something that sequesters ligands, which is different from how I have seen decoy receptors being described: https://en.wikipedia.org/wiki/Decoy_receptors

?

**Comment by ValWood** [comment]
The wikepedia def is
"A decoy receptor is a receptor that is able to recognize and bind specific growth factors or cytokines efficiently but is not structurally able to signal or activate the intended receptor complex. It acts as an inhibitor, binding a ligand and keeping it from binding to its regular receptor."

which fits perfectly what the hijacked-chitinase is doing.

It is binding to ligands to prevent these ligands binding to the cognate receptor. OK it isn't  a "canonical receptor"
(i.e it might not *look* like the receptor decoys which *resemble* receptors. But at the molecular level it is *acting* as a "receptor decoy".

**Comment by pgaudet** [comment]
OK - so in the current definition we are missing the 'sequestering' idea, is that the problem ? 
> "The activity of a gene product that interacts with a receptor to decrease the ability of the receptor agonist to bind and activate the receptor."

**Comment by ValWood** [comment]
I don't think a receptor agonist  is necessarily sequestering.

I don't think "receptor agonist" is really equivalent to "decoy receptor" is it?

**Comment by pgaudet** [comment]
@ValWood 

I created 2 terms, 'receptor decoy activity' and 'PAMP receptor decoy activity', children of molecular sequestering activity: https://github.com/geneontology/go-ontology/issues/17069

Do you still want 'PAMP binding' ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think the receptor will cover it. We'll use this before we go further.
v

**Comment by pgaudet** [comment]
Thanks
