### ISSUE TITLE
Consider synonym bacterial microcompartment for polyhedral organelle

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16852]
polyhedral organelle: http://amigo.geneontology.org/amigo/term/GO:0031469#display-lineage-tab
Definition
An organelle found in bacteria consisting of a proteinaceous coat containing metabolic enzymes whose purpose is the sequestration or concentration of metabolites and which has the appearance of a polygonal granule by electron microscopy. Source: PMID:10498708, PMID:11844753, PMID:12923081, GOC:js

is a more standard name for this not bacterial microcompartment? Consider adding this as a synonym plus BMC

Would this not lead to more annotations via a link to
https://www.ebi.ac.uk/interpro/entry/IPR000249

(we only have 4, but BMCs have been well characterized we have some experts here at lbl)

cc @jimhu-tamu

**Comment by ValWood** [comment]
This seems a fairly strightforward synonym additions, if appropriate?

**Comment by pgaudet** [comment]
@sarach06 @EBI-Hsinyu 
Can you add the polyhedral organelle: http://amigo.geneontology.org/amigo/term/GO:0031469 mapping to IPR000249 ? 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have added the term to this entry, which will be visible in the next InterPro release (83.0).
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks @sarach06 !

**Comment by pgaudet** [comment]
Done here: #22465
