### ISSUE TITLE
NTR: inositol-5-diphosphate-1,3,4,6-tetrakisphosphate 5-diphosphatase activity

### ISSUE THREAD

**Issue by kmacpher5** [geneontology/go-ontology#16850]
Could we please create the new molecular function term detailed below, as a child term of GO:0052840?

Molecular Function term:
inositol-5-diphosphate-1,3,4,6-tetrakisphosphate 5-diphosphatase activity

Description:
Catalysis of the reaction: inositol-5-diphosphate 1,3,4,6-tetrakisphosphate + H2O → inositol 1,3,4,5,6-pentakisphosphate + phosphate.

Reference:
PMID:10777568

Crossrefs:
EC:3.6.1.52
MetaCyc:RXN-10963

**Comment by srengel** [comment]
is this a different reaction than 52840 or just a more specific renaming?

**Comment by kmacpher5** [comment]
This is a more specific renaming, in the same manner as:

GO:0052842 inositol diphosphate pentakisphosphate diphosphatase activity

and its child term:
GO:0052845 inositol-5-diphosphate-1,2,3,4,6-pentakisphosphate diphosphatase activity

**Comment by srengel** [comment]
so if it's just a renaming, and not actually a different reaction, then why not rename 52840 instead of creating a 2nd term to describe the same reaction?

**Comment by kmacpher5** [comment]
I'm sorry, I misunderstood your earlier question, the two terms are not equal. The term I'm requesting would be a more specific child of 0052842, one that specifies that the inositol diphosphate tetrakisphosphate involved in the reaction has its diphosphate at the 5 position

**Comment by ukemi** [comment]
Note that the EC number reaction is not as specific as the reaction in the definition for this new term. 

I think the first reactant is CHEBI:62928. 

I don't see this reaction in Rhea, but we should double-check with @amorgat or @alanbridge. It is similar to RHEA:56312

The parent term GO:0052840 also does not have an xref to Rhea.

**Comment by amorgat** [comment]
The studied reaction is missing in Rhea and MetaCyc.

MetaCyc:RXN-10963 is the parent of the requested reaction
a diphospho-1D-myo-inositol tetrakisphosphate + H2O = D-myo-inositol 1,3,4,5,6-pentakisphosphate + phosphate + H+
See comment in http://metacyc.ai.sri.com/compound?orgid=META&id=DIPHOSPHO-1D-MYO-INOSITOL-TETRAKISPHOSPH#tab=RXNS
"Please note that the exact location of the β-phosphate has not been determined yet. This structure is provided for illustration purpose. "

CHEBI:57733 is the normalized structure for 1D-myo-inositol 1,3,4,5,6-pentakisphosphate 
I've just submitted a new ChEBI for 5-diphospho-1D-myo-inositol 1,3,4,6-tetrakisphosphate
see https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:142939
and I'm going to create the missing reaction in Rhea.

**Comment by ukemi** [comment]
Thanks @amorgat. In GO we have the existing parent:

GO:0052840----Catalysis of the reaction: inositol diphosphate tetrakisphosphate + H2O = inositol 1,3,4,5,6-pentakisphosphate + phosphate. xref MetaCyc:RXN-10963

This molecular function has no Rhea xref. Is it out of scope because of the non-specificity of reactant structures?

**Comment by vanaukenk** [comment]
@amorgat 
Is the missing reaction now in Rhea?
I had searched with the new ChEBI ID but did not find a match at Rhea.
Thank you. --Kimberly

**Comment by amorgat** [comment]
@vanaukenk 
I apologize for the late reply 
The reaction is RHEA:59500, it is not yet publicly available.
I added it as an alternate reaction of EC 3.6.1.52

RHEA:59500
5-diphospho-1D-myo-inositol 1,3,4,6-tetrakisphosphate + H2O = 1D-myo-inositol 1,3,4,5,6-pentakisphosphate + H+ + phosphate

**Comment by ValWood** [comment]
@srengel 
term seems to exist, so closing
GO:0106211    inositol-5-diphosphate-1,3,4,6-tetrakisphosphate diphosphatase activity
