### ISSUE TITLE
NTR: Xyloside xylosyltransferase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#16869]
Could I request:

name: xyloside xylosyltransferase activity

Def: UDP-xylose:α-xyloside α1,3-xylosyltransferase actvity, adding an xylose to an O-linked xylose-glucose acceptor (xylose-α1,3-glucoseβ1-O-Ser/Thr). 
(Sorry, this is a bit weak - could do with a bit of editior input.)

Xrefs:EC:2.4.2.n3
RHEA:22820
RHEA:56600 
PMID:22117070

Reaction (from EC): UDP-alpha-D-xylose + alpha-D-xylose-(1->3)-beta-D-glucosyl-R <=> UDP + alpha-D-xylose-(1->3)-alpha-D-xylose-(1->3)-beta-D-glucosyl-R

This is to annotate a xyloside xylosyltransferase that adds a second xylose to Notch Receptor EGF repeats - the RHEA xrefs are specific for EGF repeats, but the EC is not - I don't think that the nature of the underlining structure should matter for the activity (ie any glycoprotein acceptor will do).

Is_a:
UDP-xylosyltransferase activity GO:0035252

**Comment by deustp01** [comment]
"The RHEA xrefs are specific for EGF repeats, but the EC is not"
In a case like this where the reaction chemistry itself is the same for both protein participants, would it be possible to ask Rhea to broaden their reaction annotation to use a generic protein? Getting grandiose, could Rhea be proactive and, where it's clear that the reaction to be annotated could proceed with any of a variety of specific proteins as inputs, create the Rhea reaction with a generic protein input in the first place?
@ukemi @amorgat

**Comment by ukemi** [comment]
We don't want a single GO MF to point to more than one Rhea reaction. We want to be able to capture them precisely and take their definitions. @hattrill, does either of the rhea reactions fit your annotation needs?

**Comment by amorgat** [comment]
**_"The RHEA xrefs are specific for EGF repeats, but the EC is not"_**

WARNING: EC:2.4.2.n3 is a **_preliminary_** EC. It is NOT an official IUBMB entry.
There is a warning in the IntEnz page (https://www.ebi.ac.uk/intenz/query?cmd=SearchID&id=19969) but not in the enzyme@ExPASy page (https://enzyme.expasy.org/EC/2.4.2.n3)
"_This is a preliminary EC number. The content has not yet been validated and included in the official IUBMB Enzyme list_."

There are 2 Rhea reactions because the enzyme can acts on 3-O-[α-D-xylosyl-(1→3)-β-D-glucosyl]-**L-seryl** residue or 3-O-[α-D-xylosyl-(1→3)-β-D-glucosyl]-**L-threonyl** residue 

We (SIB) are in the process to re-organize enzyme classification data. I think this preliminary EC is in 
Kristian's to-do list. @kaxelsen, please you comment on EC:2.4.2.n3? Could we update existing Rhea reactions or create parent reactions?

@deustp01 
"Getting grandiose, could Rhea be proactive and, where it's clear that the reaction to be annotated could proceed with any of a variety of specific proteins as inputs, create the Rhea reaction with a generic protein input in the first place?"
Yes, this is definitely the direction we want to go!  Will be discussed during our Rhea meeting this week.

**Comment by hattrill** [comment]
The particular enzymatic activity that I am curating results in the addition of a xyl to a Protein-Ser-O-Glc-Xyl of the EGF repeats of Notch receptor.  RHEA:22820 describes this reaction. 
It would be good for us (FlyBase) to have an EC xref in the GO, as we use this xref in other pipelines. 
From my perspective, it is the linkage and the underlying substrate protein-O-Glc-Xyl, that is the interesting bit - the EGF repeat I am not so fussed about. (But, I haven't come across this dixylose-Glc-O-X modification in non-EGF repeats, but I have not looked exhaustively.)

**Comment by kaxelsen** [comment]
I have now looked at this pathway both in Rhea and in the IUBMB nomenclature. 
1. I have updated EC 2.4.2.42 at IUBMB (covering GXYLT1 and GXYLT2). The reaction described was actually more specific than the one in Rhea, as it was described for "-EGF-like domain of bovine factor IX(45-87)". I have now changed it to "EGF domain containing protein" using the agreed nomenclature for the carbohydrate part of the reaction. I have realised RHEA:56564 is wrong, as the glycosylation only takes place on serine amino acids in the CXSXPC motif of the EGF domains, and not on threonine residues as described in RHEA:56564.
2. I have created a new EC number at IUBMB covering the preliminary EC 2.4.2.n3. This covers the activity of XXYLT1. For this entry, RHEA:56600 is wrong (threonyl residue).
3. I have created two EC numbers covering the activity of POGLUT1 (or rumi in fruit flies) that catalyzes the first step in the pathway, and in addition has xylosyltransferase activity. The two EC numbers will be in classes: EC 2.4.2. (xylosyltransferase activity) and EC 2.4.1 (glucosyltransferase activity). The corresponding Rhea reactions are: RHEA:62016 and RHEA:58116, respectively.

**Comment by hdrabkin** [comment]
@hattrill and @kaxelsen  was waiting for the RHEAs to become public but now I"ve totally lost the point of this thread.
Is the request term xyloside xylosyltransferase activity suppose to be assigned to  EC:2.4.2.42?
What RHEA should I use?

**Comment by kaxelsen** [comment]
Unfortunately my entries created Nov. 15 2019 have been stuck in the EC system until now, so they will only become public after having been in review, but this will happen soon, so they should become public in ~2 months. So I will soon be able to communicate the EC numbers.

**Comment by kaxelsen** [comment]
Now I have the EC numbers. I will list them in pathway order:
**POGLUT1** EC 2.4.2.63 RHEA:62016 L-seryl-[EGF-like domain protein] + UDP-α-D-xylose = 3-O-(β-D-xylosyl)-L-seryl-[EGF-like domain protein] + H+ + UDP 
**POGLUT1** EC 2.4.1.376 RHEA:58116 L-seryl-[EGF-like domain protein] + UDP-α-D-glucose = 3-O-(β-D-glucosyl)-L-seryl-[EGF-like domain protein] + H+ + UDP
**GXYLT2** EC 2.4.2.42 RHEA:56064 3-O-(β-D-glucosyl)-L-seryl-[EGF-like domain protein] + UDP-α-D-xylose = 3-O-[α-D-xylosyl-(1→3)-β-D-glucosyl]-L-seryl-[EGF-like domain protein] + H+ + UDP
**XXYLT1** EC 2.4.2.62 RHEA:22820 3-O-[α-D-xylosyl-(1→3)-β-D-glucosyl]-L-seryl-[EGF-like domain protein] + UDP-α-D-xylose = 3-O-[α-D-xylosyl-(1→3)-α-D-xylosyl-(1→3)-β-D-glucosyl]-L-seryl-[EGF-like domain protein] + H+ + UDP

**Comment by pgaudet** [comment]
Ready ?

**Comment by kaxelsen** [comment]
If you ask about the EC numbers, they became public just before June 23, and are now also in the UniProtKB

**Comment by pgaudet** [comment]
@hattrill  this is the term you requested: 

 
+[Term]
+id: GO:0140560
+name: xylosyl alpha-1,3-xylosyltransferase
+namespace: molecular_function
+def: "Catalyzes the reaction: UDP-alpha-D-xylose + [protein with EGF-like domain]-3-O-(alpha-D-xylosyl-(1->3)-beta-D-glucosyl)-L-serine <=> UDP + [protein with EGF-like domain]-3-O-(alpha-D-xylosyl-(1->3)-alpha-D-xylosyl-(1->3)-beta-D-glucosyl)-L-serine. The enzyme, found in animals and insects, is involved in the biosynthesis of the alpha-D-xylosyl-(1->3)-alpha-D-xylosyl-(1->3)- beta-D-glucosyl trisaccharide on epidermal growth factor-like (EGF- like) domains." [PMID:22117070, PMID:8982869, RHEA:22820]
+xref: EC:2.4.2.62
+xref: RHEA:22820
+is_a: GO:0016757 ! transferase activity, transferring glycosyl groups
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16869 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-25T13:45:18Z

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 

> GXYLT2 EC:2.4.2.42 RHEA:56064 

EC transferred to EC:2.4.1.17
GO already exists:     GO:0015020  glucuronosyltransferase activity :) 

However Rhea has reactions for both EC:2.4.1.17 (RHEA:21032) and EC 2.4.2.42  (RHEA:56064)

I guess we also need the two reactions in GO ? I dont understand why EC:2.4.1.17 was transferred. 

Thanks, Pascale

**Comment by hattrill** [comment]
Thanks @pgaudet

**Comment by pgaudet** [comment]
Created other 2 terms recommended by @kaxelsen 

+[Term]
+id: GO:0140561
+name: EGF-domain serine glucosyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: UDP-alpha-D-glucose + [protein with EGF-like domain]-L-serine <=> UDP + [protein with EGF-like domain]-3-O-(beta-D-glucosyl)-L-serine." [RHEA:58116]
+xref: EC:2.4.1.376
+xref: RHEA:58116
+is_a: GO:0035251 ! UDP-glucosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16869 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-25T14:19:23Z
+
+[Term]
+id: GO:0140562
+name: EGF-domain serine xylosyltransferase activity
+namespace: molecular_function
+def: "Catalyses the reaction: UDP-alpha-D-xylose + [protein with EGF-like domain]-L-serine <=> UDP + [protein with EGF-like domain]-3-O-(beta-D-xylosyl)-L-serine." [RHEA:62016]
+xref: EC 2.4.2.63
+xref: RHEA:62016
+is_a: GO:0035252 ! UDP-xylosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16869 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-25T14:30:56Z

Thanks, Pascale

**Comment by kaxelsen** [comment]
> 
> 
> @amorgat @kaxelsen
> 
> > GXYLT2 EC:2.4.2.42 RHEA:56064
> 
> EC transferred to EC:2.4.1.17
> GO already exists: GO:0015020 glucuronosyltransferase activity :)
> 
> However Rhea has reactions for both EC:2.4.1.17 (RHEA:21032) and EC 2.4.2.42 (RHEA:56064)
> 
> I guess we also need the two reactions in GO ? I dont understand why EC:2.4.1.17 was transferred.
> 
> Thanks, Pascale

I think you have looked at EC 2.4.1.42 (one) that has been transferred to EC 2.4.1.17.
EC 2.4.2.42 (two) is active and will remain so.

**Comment by pgaudet** [comment]
Thanks @kaxelsen !!!

**Comment by pgaudet** [comment]
I will add  'UDP-D-xylose:beta-D-glucoside alpha-1,3-D-xylosyltransferase activity' (EC:2.4.2.42 /RHEA:56064) as a child of  GO:0035252 UDP-xylosyltransferase activity, and move the reference PMID:30127001 (Two novel protein O-glucosyltransferases that modify sites distinct from POGLUT1 and affect Notch trafficking and signaling) to the new term.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140563
+name: UDP-D-xylose:beta-D-glucoside alpha-1,3-D-xylosyltransferase activity
+namespace: molecular_function
+def: "Catalyzes the reaction: UDP-alpha-D-xylose + [protein with EGF-like domain]-3-O-(beta-D-glucosyl)-L-serine <=> UDP + [protein with EGF-like domain]-3-O-(alpha-D-xylosyl-(1->3)-beta-D-glucosyl)-L-serine." [EC:2.4.2.42, PMID:30127001, RHEA:56064]
+xref: EC:2.4.2.42
+xref: RHEA:56064
+is_a: GO:0035252 ! UDP-xylosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16869 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-25T16:07:58Z
+

**Comment by hdrabkin** [comment]
Since rheas were added already I will remove tag
