### ISSUE TITLE
cell proliferation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16871]
I thought we were making this "not for direct annotation"? I still see lots of annotations, so i checked and I don't see any indication that only children should be annotated?

**Comment by ukemi** [comment]
#16659

**Comment by ValWood** [comment]
Yes that was correct. It would be good longer term if an extension can be forced too in these cases @pgaudet @vanaukenk can we put this on the QC "master list"?

**Comment by pgaudet** [comment]
The rule has been created; it just needs to be implemented. 

https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000051.md
