### ISSUE TITLE
Publish pre-reasoned and merged go-lego.owl

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#16874]
I would like to change go-lego.owl to be a pre-reasoned and merged version of the current file, which is an empty ontology with just an imports chain. Arachne reasoning in Noctua requires some of the OWL EL subsumption inferences to be asserted in advance. Otherwise, reasoning will be less complete or else provide redundant results, as in https://github.com/geneontology/minerva/issues/210.

The result would be a 1.3 GB OWL file. @kltm is there any issue with adding this size of file to the ontology build output in the pipeline?

cc @cmungall

**Comment by balhoff** [comment]
In case it isn't obvious, this would be accomplished by adding a target to the go-ontology makefile.

**Comment by cmungall** [comment]
Would we create a go-lego-edit with the source imports?

**Comment by balhoff** [comment]
> Would we create a go-lego-edit with the source imports?

Yes, I would move the current file to go-lego-edit.

**Comment by kltm** [comment]
@balhoff A file that size /shouldn't/ be a problem. At least, at first, we can try and see. It should compress well so likely won't be a problem.

**Comment by balhoff** [comment]
This is going to be needed for proper functionality of go-shapes constraint checking for anatomical entity subclasses.
