### ISSUE TITLE
GO:0032188   establishment of actomyosin contractile ring localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16879]
Obsoletion or merge

This is analogous to
"cytokinesis, site selection"

GO:0007105    cytokinesis, site selection
GO:1902408    mitotic cytokinesis, site selection

these terms are more used (GO:0032188   establishment of actomyosin contractile ring localization and descendants only used by PomBAse, I'm moving the annotations now...

**Comment by vanaukenk** [comment]
@ValWood 
We discussed this ticket on the editor's call today and @krchristie reminded us that, in S. cerevisiae, septin ring localization determines the cytokinesis site, followed by actomyosin ring localization.
There was, as well, a lengthy discussion about this that I found in an old ticket:  #2974
The consensus was that we would thus not want to merge these terms.

**Comment by ukemi** [comment]
Even in embryos, the two processes are linked but not the same. The positioning of the spindle determines the axis and position of eventual cell division. So the spindle positioning comes first, the contractile ring is positioned based on the spindle. PMID:26173082

**Comment by vanaukenk** [comment]
The definition and exact synonyms for GO:0032188:

Definition:
The process in which a contractile ring is assembled in a specific location as part of a process of cell cycle cytokinesis.

Exact synonyms:
cytokinesis site selection by contractile ring positioning
establishment of contractile ring localization involved in cell cycle cytokinesis
establishment of contractile ring localisation involved in cell cycle cytokinesis

Suggest that it really is referring to a more specific process than the parent term.

**Comment by ValWood** [comment]
Well OK, but I'm not sure that these two terms are any different if they were logically defined.

 SPB signalling is upstream of site selection, septin governs site selection. These facts are not incompatible with the suggested merge. These events are largely conserved (and probably studied in most depth in fission yeast).

Something dictates the positioning of the ring (establishment of the ring position?), and these terms don't specify what that something is...

To me these terms appear to be identically defined.
GO:0007105    cytokinesis, site selection
The process of marking the place where cytokinesis will occur.

GO:0032188  establishment of actomyosin contractile ring localization
The process in which a contractile ring is assembled in a specific location as part of a process of cell cycle cytokinesis.

PomBase is the only group that used both, but *I* can't differentiate between them....

If you want to say something different to this maybe a new term is required.
Could you try to make logical definitions so we can see the difference?

**Comment by ValWood** [comment]
i.e "establishment of localization" is *positioning*, OR part of "positioning". You can't establish the localization of something if you don't know where to put it....

**Comment by vanaukenk** [comment]
@ValWood 

I think it would help if we can clarify the definition of 'cytokinesis, site selection'.

What is meant by "_marking the place_ where cytokinesis will occur."

I suspect that "site selection" is a phrase more commonly found in fungal/bacterial literature but other organisms would also need to establish the localization of the actomyosin contractile ring.  

Perhaps there is a more general term that we could introduce as a parent?

**Comment by ValWood** [comment]
There is a wonderful  (and fairly recent, Oct 17) review  by Tom Pollard
Nine unanswered questions about cytokinesis.
https://www.ncbi.nlm.nih.gov/pubmed/28807993

human, pombe , cerevisiae
![f2 large](https://user-images.githubusercontent.com/7359272/53398620-f1289f80-39a1-11e9-973c-a81c723c99a0.jpg)


There are multiple pathways controlling cytokinetic ring positioning in human
in different cell types
![f3 large 1](https://user-images.githubusercontent.com/7359272/53398657-10273180-39a2-11e9-946c-ff5281480953.jpg)

The marking of the position of the contractile ring is considered the  first step in cytokinesis.

This is what GO looks like currently

![site selection](https://user-images.githubusercontent.com/7359272/53398735-495fa180-39a2-11e9-982a-310d13017416.jpg)

At present "site selection" and establishment of localization are not related. Logically, they absolutely must be?  Selecting the site where the ring is positioned must be part of "establishing the localization"???

I’m not sure what else “establishment of localisation” could refer to?


"Question 2: How do cells position the contractile ring?
Perhaps the greatest source of the curiosity in the field has been how cells position the division plane for cytokinesis."


This is how pombe "marks" the position of the ring to assemble:

"**Fission yeast cells establish the cleavage position** early in interphase but can adjust later if necessary (Cheffings et al., 2016). Contractile ring precursors called type 1 nodes assemble from proteins on the inside of the plasma membrane in a band around the centrally located nucleus. The protein kinase Cdr2p is a scaffold for protein kinases Cdr1p and Wee1p in these nodes (Martin and Berthelot-Grosjean, 2009; Moseley et al., 2009). Type 1 nodes assemble when the activity of the septation initiation network (SIN) declines at the end of mitosis (Pu et al., 2015), because the SIN kinase Sid2p blocks their assembly by phosphorylating Cdr2p (Rincon et al., 2017). Signals from the poles of the cell, including the Pom1p kinase, exclude type 1 nodes from the poles, so they concentrate in the middle of the cell (Fig. 2). An intermolecular autophosphorylation mechanism establishes the gradient of Pom1p at both poles (Hersch et al., 2015). A second type of node composed of adapter protein Blt1p, guanine nucleotide exchange factor Gef2p, and kinesin-3 (Klp8p) emerges from the previous contractile ring as it disassembles (Moseley et al., 2009; Akamatsu et al., 2014). These type 2 nodes diffuse on the inside of the plasma membrane until they are captured by stationary type 1 nodes around the equator. During late interphase, polo kinase stimulates movement of anillin Mid1p from the nucleus to the nodes, and the position of the nucleus can influence the position of the nodes (Almonacid et al., 2011). When the cell enters mitosis, nodes accumulate contractile ring proteins (see Question 3). **This elegant positioning mechanism is still incompletely understood..."**


Note that there are *different* positioning mechanisms, but my question is "how does site selction" differ "from establishment of localization"

Does anybody have any examples of genes annotated to one, and not the other (correctly!). I don't.... which is why I raised the question...

**Comment by ValWood** [comment]
The only group who has used 

http://amigo.geneontology.org/amigo/term/GO:1902408
cytokinesis, site selection (GO:0007105)
(plus 2 geneDB annotations)

There are only 33 EXP annotations to 
I am proposing the merge for consistency.

cytokinesis, site selection (GO:0007105) has some children referring to the S. cerevisiae mechanism. These could be relocated under the "establishment of localization" term?


cytokinesis, site selection (GO:0007105) is an ancinet term. In 2010 a synonym

2010-09-15 | Deleted | SYNONYM | contractile ring positioning

was deleted, not sure why because to me, this is exactly what site selection is?

**Comment by ValWood** [comment]
update previus comment to:
There are only 33 EXP annotations to cytokinesis, site selection (GO:0007105)
http://amigo.geneontology.org/amigo/GO:0007105
I am proposing the merge for consistency.

cytokinesis, site selection (GO:0007105) has some children referring to the S. cerevisiae mechanism. These could be relocated under the "establishment of localization" term?

cytokinesis, site selection (GO:0007105) is an ancient term. In 2010 a synonym
2010-09-15 | Deleted | SYNONYM | contractile ring positioning
was deleted, not sure why because to me, this is exactly what site selection is?

**Comment by ValWood** [comment]
comments from the newer ticket

@ValWood 
are

GO:1903486 establishment of mitotic actomyosin contractile ring localization
Any establishment of actomyosin contractile ring localization that is involved in mitotic cell cycle.
and

GO:0007105 cytokinesis, site selection
Definition
The process of marking the place where cytokinesis will occur.

the same thing?

**Comment by ValWood** [comment]
@mah No, GO:1903486 is narrower, because plants (e.g. PMID:30999231).

**Comment by ValWood** [comment]
@ValWood :
but establishment occurs in yeast too (mid1 placement at the cortex). I'm still struggling to figure out how establishment or location and site-selection differ...

although I probably should have asked
GO:0032188 establishment of actomyosin contractile ring localization
and
GO:0007105 cytokinesis, site selection

**Comment by ValWood** [comment]
> but establishment occurs in yeast too (mid1 placement at the cortex). 

I'm not sure how that's relevant to the fact that establishing contractile ring localization is narrower than selecting the site of cytokinesis.

> I'm still struggling to figure out how establishment or location and site-selection differ...

The difference is that in plants there's no actomyosin contractile ring. The phragmoplast and cell plate nevertheless form at a non-random site.

For organisms that do have an actomyosin contractile ring, it does indeed form at the site of cytokinesis, but that is not the only type of site selection that GO:0007105 has to cover.

**Comment by ValWood** [comment]
I still think something  is a bit odd:

<img width="509" alt="Screenshot 2020-11-02 at 18 29 23" src="https://user-images.githubusercontent.com/7359272/97905129-646ae300-1d39-11eb-9257-4488c53738b0.png">

**Comment by ValWood** [comment]
@mah11 
But it looks basically correct, apart from a missing link - GO:1903486 should be is_a or part_of GO:1902408. Part_of would parallel GO:0032188 part_of GO:0007105, but perhaps both should be is_a.

Otherwise, it's only as odd as the biology it has to represent.

**Comment by ValWood** [comment]
@ValWood :

I think I am confused by the different labels then.

If it is correct, it probably should be is_a

but then

Since
GO:0032188 establishment of actomyosin contractile ring localization
Biological Process
Definition
The process in which a contractile ring is assembled in a specific location as part of a process of cell cycle cytokinesis.

is_a
GO:0007105 cytokinesis, site selection
Definition The process of marking the place where cytokinesis will occur.

It might be better to standardize the definitions and labels

i.e GO:0007105 cytokinesis, site selection and GO:0032188 actomyosin contractile ring localization, site selection

OR

GO:0007105 establishment of contractile ring localization and GO:0032188 establishment of actomyosin contractile ring localization

and standardizing the definitions. I think it's very confusing and I do a lot of cytokinesis annotation, so I suspect other will too. Very low number of EXP annotations seems to confirm this.

I'm still not convinced the current arrangement is the intended usage.
I'd previously assumed site selection was for things like mid1, marking the position where the ring would form, not actually building the ring- but if it was, we probably don't need this specificity.

**Comment by ValWood** [comment]
at some point I will look at this... not urgent but will need to do it to build a model of cytokinesis.

**Comment by ValWood** [comment]
I'm annotating cytokinesis papers at the moment. I came across this again. 

The missing link needs to be added
GO:1903486 should be is_a or part_of GO:1902408
and the labels standardised.

**Comment by ValWood** [comment]
This is a very long and very confusing ticket.
I created a new ticket https://github.com/geneontology/go-ontology/issues/25071  with a plan.
Note that there was quite a lot of push back in this ticket, but the current arrangement is inconsistent and confusing.
Please note any objections in the new ticket with specific annotation issues. I'll leave the new ticket for a few weeks until I proceed to give time for comments,

**Comment by pgaudet** [comment]
Should we close this ticket then?

**Comment by ValWood** [comment]
Oh yes, I meant to do that!
