### ISSUE TITLE
bad definition xref for G protein-coupled acetylcholine receptor activity

### ISSUE THREAD

**Issue by goodb** [geneontology/go-ontology#16875]
GO:0016907 'G protein-coupled acetylcholine receptor activity' has a cross reference to: 
OneLook:www.onelook.com 

This seems to effect a number of other terms as well, e.g. Chaperone Binding

**Comment by ukemi** [comment]
I suggest we remove these, find specific references for the terms and modify the definitions as needed based on the specific refs.

**Comment by vanaukenk** [comment]
Here's the list:

![image](https://user-images.githubusercontent.com/1730534/52418690-9267b880-2abc-11e9-93b0-ce2a0d1a98a9.png)

**Comment by pgaudet** [comment]
*  GO:0051164  L-xylitol metabolic process
** GOC:ai - remove onelook.com
*  GO:0052545 callose localization 
** change onelook.com to PMID:18397379  (an annotated paper)
* GO:0051216 cartilage development
** change DOI:10.1371/journal.pone.0051070 to PMID:23251424 and remove  onelook.com


* GO:0051087 chaperone binding
** Change onelook.come to PMID:10585443  (an annotated paper)
* GO:0051026 chiasma assembly
** Change onelook.come to PMID: 23396135
* GO:0051981  copper chelate transmembrane transporter activity
** Change to PMID:26512647
* GO:0051424  corticotropin-releasing hormone binding
** Change to PMID:7556876
* GO:0016805  dipeptidase activity
** Change to PMID:19879002

* GO:0051501  diterpene phytoalexin metabolic process
** Keep other xref: ISBN:0721662544, GOC:ai
* GO:0051541  elastin metabolic process
** Change to GOC:curators
* GO:0052094  formation by symbiont of haustorium for nutrient acquisition from   host
** Keep GOC:mtg_pamgo_17jul06 
* GO:0051866  general adaptation syndrome
** Keep PMID:14847556, Wikipedia:General_adaptation_syndrome
* GO:0042344  indole glucosinolate catabolic process
** Replace by PMID:29122987
* GO:0015603  iron chelate transmembrane transporter activity
** Replace by PMID:17660286
* GO:0051143  propanediol metabolic process
** Replace by PMID:15995211
* GO:0015708  silicic acid import across plasma membrane
** Change to PMID:16572174
* GO:0016790  thiolester hydrolase activity
** change to 3.1.2 
@hdrabkin Do you have any recommendation
* GO:0051923  sulfation
* change to Wikipedia:Sulfation

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/18525

**Comment by pgaudet** [comment]
Removed bad xrefs.

**Comment by hdrabkin** [comment]
Didn't see the email fo rthis
"EC.3.1.2 does map to thioester hydrolases in EC; a ligit grouping term for this GO id

**Comment by pgaudet** [comment]
OK thanks !
