### ISSUE TITLE
MF instead of BP GO:0051220    cytoplasmic sequestering of protein ->MF sequestration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16877]
GO:0051220    cytoplasmic sequestering of protein (and children)

this is generally used for  the actual sequesteres (i.e 14-3-3 proteins).
It would be better if this was a MF term, and anything indirect  (if required) just used "maintenance of localization"

We really need a
"sequestration activity" in MF it crops up frequently.

**Comment by pgaudet** [comment]
Hi @ValWood 
So, we should merge BP GO:0051220 cytoplasmic sequestering of protein into "maintenance of (protein)  localization" and create a new MF term  - is this what you are asking ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Oh  welcome back. We have missed you! 

To me the  "sequestering activity" thing is a big issue.  It's similar to the "recruitment issue".
We have tonnes of examples of these-  we need to make sure we have a consistent way to handle them. At present we straddle MF and BP ontologies for both arbitrarily.

It would be great to have a session on these on an  editors call.  I'm interested how @vanaukenk  and @ukemi  handle them activities in nouctua models because we don't generally have MF terms to capture... but I'm convinced these should often be captured as fundamental activities   for these gene products, not just processes.

**Comment by pgaudet** [comment]
I think this was addressed here #17076
I still need to obsolete the processes, but there's a ticket for that - #17075

Thanks, Pascale
