### ISSUE TITLE
GO:0044810    Dma1-dependent checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16878]
GO:0044810    Dma1-dependent checkpoint

please merge into the parent (it is the same checkpoint, just part of it)

Only used by PomBase.

**Comment by ValWood** [comment]
also
GO:0044811    response to Dma1-dependent checkpoint signaling
GO:1902420    signal transduction involved in Dma1-dependent checkpoint
GO:1902419    detection of stimulus involved in Dma1-dependent checkpoint

**Comment by ukemi** [comment]
Are you sure you want to do this? There are two children of the parent; one that checks to see if the spindle forms (DMA-1 dependent) and the other that checks the orientation of the spindle. If we merge the former into the parent that only leaves one type of child, the orientation-dependent one. Having a single subclass in the ontology is usually not a good sign.

**Comment by mah11** [comment]
I see three subtypes of mitotic spindle checkpoint (GO:0071174): assembly (GO:0007094), orientation (GO:0031578), and Dma1-dependent (GO:0044810)

@ValWood might be suggesting that GO:0044810 can merge into GO:0007094 (and parts ditto), which would still leave two types.

There's also a comment on GO:0071174 to update if any merge happens.

**Comment by ValWood** [comment]
There should still be a spindle assembly checkpoint, and a spindle orientation checkpoint. 

Dma1-dependent checkpoint as a child of spindle assembly checkpoint. I  never found anything to annotate to Dma1-dependent checkpoint  except Dma1 and  it functions is through the normal mitotic spindle assembly checkpoint.  I now read ALL the papers on Dma1 and I'm convinced it doesn't warrant it's own term. I can place it in the model of GO:0007094    mitotic spindle assembly checkpoint.

It seems originally DMA1-dependent checkpoint was incorrectly positioned (it should have been under "assembly checkpoint" , but there will still be 2 children of mitotic spindle checkpoint

i)  GO:0031578 mitotic spindle orientation checkpoint
ii) GO:0007094    mitotic spindle assembly checkpoint

**Comment by mah11** [comment]
snap!

**Comment by ukemi** [comment]
Got it. Thanks!

**Comment by ukemi** [comment]
PR in. Fingers crossed that all this merging worked.
