### ISSUE TITLE
ntr: 	negative regulation of protein localization to cell tip	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16887]
descendant  of
GO:1903067 | negative regulation of protein localization to cell tip

Standard text def (as for parent but with "non-growing")
logical def, as for parent + GO:0035839    non-growing cell tip
Ref PMID:18328707

**Comment by ukemi** [comment]
ntr: negative regulation of protein localization to cell tip  descendent of negative regulation of protein localization to cell tip????????

**Comment by ukemi** [comment]
Do you mean negative regulation of protein localization to non-growing cell tip?

**Comment by ukemi** [comment]
Looking at the paper, I think that is what is being requested.

**Comment by ukemi** [comment]
Good because the pull request is already being checked.

**Comment by ValWood** [comment]
yes I edited the title ;)
thanks
