### ISSUE TITLE
propose to remove pollen-pistil interaction (GO:0009875) from plant go slim

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16883]
pollen-pistil interaction GO:0009875 (75 annotations in AmiGO) is a child of another slim term
pollination GO:0009856 (499 annotations in AmiGO)

@cooperl09 
@tberardini

**Comment by cooperl09** [comment]
It's not clear what you are proposing here.  Are you suggesting to move pollen-pistil interaction (GO:0009875) to another spot, or obsolete it?

In fact, pollen-pistil interaction (GO:0009875) is not a child of pollination (GO:0009856), but is_a reproductive process (GO:0022414) and is_a  cell communication (GO:0007154), and is part_of pollination (GO:0009856), which seems appropriate (although def'n could use some work).

We have 758 direct annotations on pollen-pistil interaction (GO:0009875) the Planteome database, from 4 sources.

**Comment by cooperl09** [comment]
What is the reason for removing it from the goslim_plant?

**Comment by cooperl09** [comment]
Propose renaming pollen-pistil interaction (GO:0009875) to pollen-stigma interaction (GO:0009875), as the stigma (PO:0009073) is the actual plant structure on which the pollen lands and interacts.

**Comment by lreiser** [comment]
@cooperl09 no not obsolete  but just remove from the slim because it is a part_of pollination (also a slim term). I agree the term name definition should change. Pollen-pistil would imply more than pollen-stigma interactions but everything else going on til I guess fertilization.

**Comment by vanaukenk** [comment]
@lreiser @cooperl09 @tberardini 

I will remove pollen-pistil interaction (GO:0009875) from the plant GO slim.

For updating the name GO:0009875 to 'pollen-stigma interaction', can you please confirm that all of the existing experimental annotations to that term (1) and its children (23) will still be okay?

19 of the 24 annotations are from TAIR; there are four from UniProt and one from TIGR.

Thx.

**Comment by lreiser** [comment]
@cooperl09 @tberardini 
Sorry- had to refresh my memory about plant sex and the different types of self incompatibility mechanisms

Most of the annotations from TAIR are reasonably to pollen-stigma as they represent events that occur in that body part. Moreover the definitions of pollen recognition (acceptance and rejection) also are specific for sporophytic self incompatibility systems.
This is fine for Brassicas.

Some of the  annotations in TAIR to children are to pollen tube adhesion which occurs in both stigma and style.
http://amigo.geneontology.org/amigo/term/GO:0009865
so still also technically true.

I am not so sure though that the current structure works for Solanaceae which use a different incompatibility mechanism that is an interaction between the pollen tube and RNAses secreted by the the female bits including the style. 

What about having 
pollen-pistil interaction
->>pollen stigma interaction
->> pollen- style interaction
And putting the different types of self/non self recognition systems in according to the appropriate tissue types? 

@vanaukenk maybe this should just be a separate ticket for the pollen- pistil naming.

**Comment by vanaukenk** [comment]
@lreiser 
Yes, please start a new ticket as this will be different work and we can track efforts better that way.  
Thanks.

**Comment by pgaudet** [comment]
@vanaukenk Sorry if I missed something -  did you change the plant slim ? I dont see the PR. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
https://github.com/geneontology/go-ontology/pull/16913

**Comment by pgaudet** [comment]
great !
