### ISSUE TITLE
NTR: clathrin-coated endocytic vesicle lumen

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#16888]
Could we have a new cell_component term? (One we missed in a bigger request a few years for additional vesicle types, their membranes and their lumens)
GO:new "clathrin-coated endocytic vesicle lumen"
definition: "The volume enclosed by the membrane of a clathrin-coated endocytic vesicle."
is_a child of GO:0071682 "endocytic vesicle lumen"
part_of child of GO:0045334 "clathrin-coated endocytic vesicle"
PMID:2516741
Thanks.

**Comment by ukemi** [comment]
Should be able to define this with a logical definition.

**Comment by deustp01** [comment]
Is there a new term for clathrin-coated endocytic vesicle lumen, or did it get lost in the phagolysosome confusion?
Thanks

**Comment by hdrabkin** [comment]
very lost; going in now
+id: GO:0106176
+name: clathrin-coated endocytic vesicle lumen
