### ISSUE TITLE
refine def spindle pole body anchor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16884]
GO:0106166    spindle pole body anchor

Current Definition 
Interacting selectively and non-covalently with a mitotic spindle pole body and a membrane, in order to maintain specific membrane location of the spindle pole body. PMID:9763447

refine to
Interacting selectively and non-covalently with a mitotic spindle pole body and (THE NUCLEAR) membrane, in order to maintain the ~specific~ membrane location of the spindle pole body. PMID:9763447

The SPB is  only anchored in the nuclear membrane

**Comment by hdrabkin** [comment]
done
