### ISSUE TITLE
malformed and spurious definition db_xrefs

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16895]
@kimrutherford found some spurious ones while parsing these to display

* PMIG:10085024  (malformed PMID?)
* PMID:pm  (type, should be GOC?)

I'm also confused why we have mappings as definition db_xrefs?
* PO:0000029
* KEGG:R05612
* RHEA:20836
* EC:3.2.1.108
* BioCyc:PWY-882
* BRENDA:1.11.1.15
* BTO:0002164
* CHEBI:10022
* Intact:EBI-9345927
* intAct:EBI-9636287
* InterPro:IPR000001
* Pfam:PF03166

why we refer to nucleotide entries at all?
* EMBL:AF304352

why  we use none pubmed IDs  to reference publiciations
* dictyBase_REF:2530

@cmungall

**Comment by cmungall** [comment]
I suggest the ontology group looks at this and determines policy for definition xrefs, @dougli1sqrd can then implement checks to enforce these

**Comment by bmeldal** [comment]
The IntAct ones were supposed to have been removed from the definitions and made dbxrefs. We are also in the process of updating the old EBI-xxx xrefs as they go no-where since we moved to CPX-xxx. That was one last place (in the dbxrefs) where we missed the update!

**Comment by ukemi** [comment]
I would like to see the definition xrefs reserved for stable publications that support the existence, placement and definition of a term. All references to other resources should go in the dbxrefs. This is also related to #16875

**Comment by tberardini** [comment]
* PO:0000029  -   obsolete PO term

http://browser.planteome.org/amigo/term/PO:0000029
