### ISSUE TITLE
Should 'astrocyte activation' be a part_of child of 'astrocyte development'?

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#16899]
Hi @addiehl 
I noticed today that 'astrocyte activation' is a part_of child of 'astrocyte development' even though 'cell activation' is not a child of 'cell development'. Figure 1A in https://doi.org/10.3389/fnmol.2017.00088 summarises specific roles of astrocytes prior to activation and so it seems to suggest that these cells should probably be considered fully developed already before they get activated (?). @RLovering and @ukemi suggested I should check with you whether that relationship should be there. (It is not explicit based on the references provided with the 'astrocyte activation' GO term, but it is certainly supported by the CL ontology). @ukemi said "In some, but not all cases activation is a part of development because the activated cell is considered to be the final developmental state." So perhaps this is indeed true for astrocytes and we should leave this as it is?
Thanks,
Barbara

**Comment by ukemi** [comment]
Note that in CL a subtype of astrocyte, mature astrocyte, has an exact synonym of 'activated astrocyte'. This implies that when activation occurs it is always part of the development of some astrocyte.

**Comment by ukemi** [comment]
I think most developmental biologists would not consider egg activation to be part of egg development.

**Comment by ukemi** [comment]
I think we can close this one and leave the ontology structure as is because it is consistent with the representation in CL.

**Comment by BarbaraCzub** [comment]
Ok
