### ISSUE TITLE
extracellular ATP signaling

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#16896]
It looks like there has been some work in this area in multiple organisms.

Extracellular ATP as a signaling molecule for epithelial cells.
https://www.ncbi.nlm.nih.gov/pubmed/12948585

Extracellular ATP signaling and clinical relevance.
https://www.ncbi.nlm.nih.gov/pubmed/29274390

Extracellular ATP signaling in plants.
https://www.ncbi.nlm.nih.gov/pubmed/20817461

name: extracellular ATP-mediated signaling pathway
def: A series of molecular signals mediated by the detection of extracellular ATP. 
references: PMID:29274390, PMID:20817461, PMID:12948585
is_a: signal transduction, GO:0007165
is_a: cellular response to ATP, GO:0071318

Hope that's enough info.  Thanks.

**Comment by hdrabkin** [comment]
This seems like it will end up being a parent term of more ...

**Comment by tberardini** [comment]
@hdrabkin Is there enough information in this request to add the term now?

**Comment by hdrabkin** [comment]
Yes; it is being added now: GO:0106167

**Comment by tberardini** [comment]
Thank you, @hdrabkin.  Very much appreciated.
