### ISSUE TITLE
ntr: zinc ion export from cytosol

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16893]
parent of 
zinc ion import into Golgi membrane  
zinc ion import into endoplasmic reticulum  

child of

GO:0071577
Term name | zinc ion transmembrane transport

def
The directed import of zinc(2+) from the cytosol into another compartment by a transmembrane transporter.

ref
PMID:29529046
(There are assays which support this annotation, but not the more specific terms)

**Comment by ukemi** [comment]
I'm a little concerned about running into a import versus export dilemma. A export is B import. Would it make more sense to have a 'zinc iron import into organelle' term and define it:
The directed import of zinc(2+) from the cytosol into a membrane bound organelle by transmembrane transport.

**Comment by srengel** [comment]
i can already see that this term will be misused based on the term/definition combo.  

i'm sure unsuspecting curators will run across this term 'zinc iron export from cytosol' and use it for zinc going out of the cell, which is in direct violation of the definition ('...from the cytosol into another compartment...').

**Comment by deustp01** [comment]
zinc ion, not iron?

**Comment by ValWood** [comment]
edited title

@ukemi  yes - your suggestion is better.
"zinc ion import into organelle"

**Comment by ukemi** [comment]
@srengel are you ok with that?

**Comment by srengel** [comment]
works!
