### ISSUE TITLE
NTR: coated vesicle lumen terms

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#16906]
Could we have four more new cell_component terms, in addition to the one requested last week (https://github.com/geneontology/go-ontology/issues/16888)? These are all ones we missed in a bigger request a few years for additional vesicle types, their membranes and their lumens.

GO:new "phagocytic vesicle lumen"
definition: "The volume enclosed by the membrane of a phagocytic vesicle."
is_a child of GO:0060205 "cytoplasmic vesicle lumen"
part_of child of GO:0032010 "phagolysosome"
PMID:29471269

GO:new "phagocytic vesicle membrane"
definition: "The volume enclosed by the membrane of a phagocytic vesicle."
is_a child of GO:0030659 "cytoplasmic vesicle membrane"
part_of child of GO:0032010 "phagolysosome"
PMID:29471269

GO:new "COPI-coated vesicle lumen"
definition: "The volume enclosed by the membrane of a COPI-coated endocytic vesicle."
is_a child of GO:0060205 cytoplasmic vesicle lumen
part_of child of GO:003013 COPI-coated vesicle
PMID:29535154

GO:new "COPII-coated vesicle lumen"
definition: "The volume enclosed by the membrane of a COPII-coated endocytic vesicle."
is_a child of GO:0060205 cytoplasmic vesicle lumen
part_of child of GO:0030134 COPII-coated ER to Golgi transport vesicle
PMID:21172817

Thanks.

**Comment by hdrabkin** [comment]
GO:new "phagocytic vesicle membrane"
definition: "The volume enclosed by the membrane of a phagocytic vesicle."  <<<<??????
is_a child of GO:0030659 "cytoplasmic vesicle membrane"
part_of child of GO:0032010 "phagolysosome"
PMID:29471269

**Comment by deustp01** [comment]
That works too. The previous one was invented by copy-pasting an existing definition for cytoplasmic vesicle membrane and changing the vesicle name.

**Comment by hdrabkin** [comment]
+id: GO:0106168
+name: phagocytic vesicle lumen

+id: GO:0106169
+name: phagocytic vesicle membrane
+
+[Term]
+id: GO:0106170
+name: COPI-coated vesicle lumen

+id: GO:0106171
+name: COPII-coated vesicle lumen
+

**Comment by hdrabkin** [comment]
Two terms were in already (one I had put in previously, and one from Midori);  I will kill this merge request and start a new one.
ome were already in the file.  It appears I had put them in 8-(. 
 ERROR: duplicate-names: GO:0030670 GO:0106169 --> phagocytic vesicle membrane
ERROR: duplicate-names: GO:0097013 GO:0106168 --> phagocytic vesicle lumen
 ERROR: duplicate-defs: GO:0097013 GO:0106168 --> The volume enclosed by the membrane of a phagocytic vesicle.
ERROR: duplicate-defs: GO:0030670 GO:0106169 --> The lipid bilayer surrounding a phagocytic vesicle.

**Comment by deustp01** [comment]
Isn't there a distinction between GO: 0045335 phagocytic vesicle "A membrane-bounded intracellular vesicle that arises from the ingestion of particulate material by phagocytosis."
and
GO:0032010 phagolysosome "A membrane-bounded intracellular vesicle formed by maturation of an early phagosome following the ingestion of particulate material by phagocytosis; during maturation, phagosomes acquire markers of late endosomes and lysosomes" (synonym late phagocytic vesicle).
We need terms for parts of the latter. There are already terms for phagocytic vesicle membrane and lumen.

**Comment by hdrabkin** [comment]
I'm sorry, neither of these GO ids were in error. (GO: 0045335  and GO:0032010)

The errors were duplicate term name and definition; Am I missing some point?
GO:0030670 vs  GO:0106169  are identical
GO:0097013  vs GO:0106168  are identical

**Comment by hdrabkin** [comment]
Here are the IDS for the two new terms.
+id: GO:0106172
+name: COPI-coated vesicle lumen
+
+[Term]
+id: GO:0106173
+name: COPII-coated vesicle lumen

**Comment by deustp01** [comment]
BUT there is already a term  GO:0061474 phagolysosome membrane which will work for us. Don't know why I missed it earlier - sorry.

**Comment by deustp01** [comment]
Phagolysosome (GO:0032010) is different from phagocytic vesicle (GO:0045335), and the request is for a phagolysosome lumen term, as a part_of phagolysosome (GO:0032010). Unless you're arguing that since phagolysosome is an is_a child of phagocytic vesicle and that's already detailed enough - we should just use phagocytic vesicle as a cell_component term localizing our entities and events.

This is a real question - I'm not sure the ultra-precise specification of changes in a vesicle as is proceeds through endocytosis to lysosomal fusion is needed in the cell_component ontology. But if it is needed (or anyway plausible enough not to worry about now) then I do need a part term for its lumen.

Thanks

Peter

**Comment by hdrabkin** [comment]
Ok, the two terms are in; so closing

**Comment by deustp01** [comment]
Yes, please. Apologies for the poor proofreading.

**Comment by hdrabkin** [comment]
AH; NOT it makes sense.
+id: GO:0106174
+name: phagolysosome vesicle lumen
+namespace: cellular_component
+def: "The volume enclosed by the membrane of a phagolysosome." [GOC:pde, PMID:29471269]
+
+[Term]
+id: GO:0106175
+name: phagolysosome vesicle membrane
+namespace: cellular_component
+def: "The lipid bylayer surrounding a phagolysosome." 
now can close
