### ISSUE TITLE
Add do_not_annotate_directly to multi-organism process

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16902]
Note we have this E coli gene that is annotated directly to MOP:

http://amigo.geneontology.org/amigo/reference/PMID:23667443

Can we not provide a more specific term in cases like this? cc @jimhu-tamu

**Comment by ValWood** [comment]
This term is on my list for the next batch to block. I sent them in an e-mail to the QC group but I'll open a ticket instead.

**Comment by ValWood** [comment]
no in this list for  blocking direct annotation
https://github.com/geneontology/go-ontology/issues/16101
I'll transfer to a spreadsheet soon for implementation

**Comment by pgaudet** [comment]
Direct annotation was removed - I now added the restriction.
