### ISSUE TITLE
fatty acid primary amide biosynthesis

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#16905]
Dear GO annotators,

Could you please consider creating a new term:
GO:new fatty acid primary amide biosynthesis (FAPA biosynthesis)
probably as a child of GO:0043604 amide biosynthetic process

The new term is needed for annotation of P14925_AMD_RAT, PMID:10079066
For review please see: PMID:15952893 

Many thanks for your help,

Nevila Hyka-Nouspikel

**Comment by ukemi** [comment]
fatty amide CHEBI:29348?

**Comment by nnouspikel** [comment]
Hi,
Thank you for taking care of this request.
Yes fatty acid primary amides are fatty amides. Probably a subclass of fatty amides different from ethanolamides CHEBI:15897. Let me know please if you think that we need a new ChEBI entry for this subclass.
All the best,
Nevila

**Comment by ukemi** [comment]
Hi Nevila,
If you want the specificity, we will need a ChEBI class for reference. We can make the term and manually place it in the ontology for now.

**Comment by nnouspikel** [comment]
Thank you David. 
Just submitted a new ChEBI for this subclass: primary fatty acid amide CHEBI:143129. Should be the appropriate reference. 
Cheers

**Comment by ukemi** [comment]
I am adding the term without a logical def for now and will add the CHEBI identifier when it becomes available for use. It looks like the review also talks about degradation of these molecules. Do you think we should go ahead and add the metabolism and catabolism terms?

**Comment by nnouspikel** [comment]
Hi David,
Thank you for creating the new term. It's a good idea to add the metabolism and catabolism ones as well. Could cite as reference for the FAA hydrolysis: PMID:11128635.
All the best
Nevila
