### ISSUE TITLE
Are Sodium-dependent and Sodium symporter the same?

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#16903]
I wonder if you can clarify the confusing issue for me. What is the different between the two classes below
 
  GO:0008520
  L-ascorbate:sodium symporter activity
 
  GO:0070890
  sodium-dependent L-ascorbate transmembrane transporter activity
 
  It seems to me these terms are the same even they are classified differently.

**Comment by ValWood** [comment]
They seem the same to me too (from definitions).

Seems to require strightforward merge because they are parent child and GO:0070890 has no other siblings.

**Comment by ValWood** [comment]
@hdrabkin  it seems that  these 2  terms could be merged, what do you think?

**Comment by hdrabkin** [comment]
Not sure
To me, sodium dependent does not always mean it's sodium that is being transported (like it could be allosteric); I am not an expert.  
GO:0070890 is now alt id to GO:0008520 
So this was already done.

**Comment by ValWood** [comment]
presumably the defs were equivalent. For what it's worth, I did not yet come across any transporter that was sodium-dependent but did not transport sodium....
