### ISSUE TITLE
NTR: Complement component C1r binding 

### ISSUE THREAD

**Issue by sandyl27** [geneontology/go-ontology#16919]
NTR: Complement component C1r binding 
definition: Interacting selectively and non-covalently with the C1r component of the classical complement cascade.
molecular function
parents: GO:00001848 complement binding 
Reference: PMID:26808924

**Comment by ukemi** [comment]
I thought we had decided not to add specific protein binding terms to the ontology from now on. From a quick scan of this paper, I think a better annotation might be to serine-type endopeptidase inhibitor activity.
