### ISSUE TITLE
Add step to Makefile to clean up intermediate files (or otherwise remove them)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#16925]
Currently, while building targets such as generate-mappings and prepare_release (in src/ontology/Makefile), some intermediate files are generated that are not meant as final products. For example:

 target/external2go/reactome_xrefs.ofn
 target/external2go/Reactions2GoTerms_human.txt

Closing this ticket would either be the removal of these files after their use or an additional make target that would remove them.

**Comment by balhoff** [comment]
Since `external2go` seems to have a specific meaning in the release, I think the simplest solution would be to create these files in a different temp directory that is not part of the release.

**Comment by kltm** [comment]
I would agree that that would be a simple solution. Essentially, all I want is for target/external2go/ to contain only final products.

**Comment by cmungall** [comment]
+1
