### ISSUE TITLE
NTR: negative regulation of hemolytic activity

### ISSUE THREAD

**Issue by apowell37** [geneontology/go-ontology#16920]
definition: Any process that decreases the rate, frequency or extent of hemolysis activity.
molecular function
parents: GO:0048519 negative regulation of biological process
Reference: PMID:26808924

**Comment by ukemi** [comment]
There is no hemolytic activity term in the ontology. We only have 'hemolysis in other organism'. But looking quickly at this paper, isn't the hemolysis observed the assay for complement activity? It seems to me the biology this paper is about is the interaction of the spirochete with the complement pathway. I would suggest using one of the regulation terms for complement activation.
