### ISSUE TITLE
big ontology issue, parentage disappeared dirupting slims

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16936]
branched-chain amino acid catabolic process
valine catabolic process
no longer slim to
GO:0006520    cellular amino acid metabolic process

**Comment by ValWood** [comment]
They look OK in  QuickGO, so this was either fixed already of it happened very recently and QuickGO isn't yet updated

**Comment by ValWood** [comment]
also non of these are slimming

+ | ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process
-- | --
+ | nuclear RNA surveillance
+ | rRNA catabolic process
+ | snoRNA catabolic process
+ | snRNA catabolic process
+ | tRNA catabolic process

https://www.pombase.org/gene/SPBP35G2.08c

**Comment by ValWood** [comment]
maybe something went wrong with our nightly update, will check and reopen if necessary.

**Comment by mah11** [comment]
these look related ...

https://github.com/geneontology/helpdesk/issues/192
https://github.com/geneontology/go-site/issues/999
