### ISSUE TITLE
people should not be class xrefs, only definition xrefs

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16933]
This is the converse of #16895

Noticed by Simon: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/826#issuecomment-465031254

e.g

```
id: GO:0099073
name: mitochondrion-derived vesicle
namespace: cellular_component
def: "A vesicle derived via budding from a mitochondrion.  These vesicles often contain inner membrane and, much more rarely, cristae." [PMID:18207745, PMID:20619655, PMID:22226745, PMID:23300790]
synonym: "MDV" EXACT [PMID:26618722]
xref: GOC:bc
xref: GOC:pad
xref: GOC:PARL-UCL
is_a: GO:0031410 ! cytoplasmic vesicle
```

I don't think we should ever do this. If a person contributed to the def, include as def xref

**Comment by ukemi** [comment]
@RLovering , are you ok with us moving all of these dbxrefs to definition dbxrefs?

**Comment by RLovering** [comment]
Hi David

thanks for asking. I am a bit confused. Could you explain where should the dbxrefs be if the term is: 

- created by someone
- moved within the ontology
- provided with a new definition (you have confirmed above that in this case the editor and funding/group dbxrefs to definition dbxrefs
- given a revised term name

I am happy with moving the dbxrefs in line with GOC policy

Thanks

Ruth

@BarbaraCzub

**Comment by ukemi** [comment]
Hi Ruth,

All of the above are associated with the meaning of the term, so they xrefs should be  in the definition xref. The term xrefs should be reserved for pointing to external resources.

-D

**Comment by krchristie** [comment]
There weren't all that many of these. Here's a summary of the changes I made.

12: xref: GOC:mengo_curators (1 was already in def dbxref, other 11 needed to be added)

All remaining people IDs were not already present in def dbxref, so were added:

4 sets of: 
- xref: GOC:bc
- xref: GOC:pad
- xref: GOC:PARL-UCL

1: xref: GOC:rb

6: xref: GOC:kmv
