### ISSUE TITLE
Proposal to rename pollen-pistil >> pollen-stigma interaction

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16938]
Per #16883
Laurel suggested changing the name of GO:0009875 to 'pollen-stigma interaction'.
the current definition is
"The interaction between a pollen grain and pistil"

1. option is to rename and update the definition 
" The interactions/cell cell communication that occurs between the pollen grain (male gametophyte) and the stigmatic tissues of the female sporophyte after the pollen reaches the stigmatic papillae."

2. Alternatively we can leave this term as is and add more specific children
pollen-pistil interaction GO:0009875
 >>pollen- stigma interaction (GO:NNNNNN) Def:" The interactions (or cell to cell communication) that occur between the pollen grain (male gametophyte) and the stigmatic tissues of the female sporophyte after the pollen reaches the stigmatic papillae."
>>pollen-style interaction (GO:NNNNNN) Def: The interactions (or cell to cell communication) that occur between the male gametophyte (pollen/pollen tube) and the stylar tissues of the female sporophyte

@cooperl09 what do you think?
@tberardini

**Comment by tberardini** [comment]
I'm in favor of option 2 as that gives maximum flexibility in annotation, depending on how much information is available.

**Comment by cmungall** [comment]
I agree

remember to axiomatize all these class using PO!

I also agree with the rewording of the definition to use the genus term

**Comment by pgaudet** [comment]
@lreiser Do you have references for these new terms ?

**Comment by pgaudet** [comment]
@cmungall @ukemi 
What is the sytax to axiomatize these terms ?

**Comment by pgaudet** [comment]
I dont fins pistil in PO: https://www.ebi.ac.uk/ols/search?q=pistil&ontology=po

**Comment by pgaudet** [comment]
Sorry I thought this was assigned to me. @hdrabkin let me know if you want to do it- but I essentially did it.

**Comment by hdrabkin** [comment]
@pgaudet Just saw this now; if  you say you already did it, go ahead.

**Comment by lreiser** [comment]
Hi 
for this I wanted to add transmitting tract in the definition
pollen-style interaction (GO:NNNNNN) Def: The interactions (or cell to cell communication) that occur between the male gametophyte (pollen/pollen tube) and the stylar (e.g. transmitting tract) tissues of the female sporophyte.

For pistil the closest PO term is PO:0009062 gynoecium.

Here is a reference
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5210727/
