### ISSUE TITLE
	phosphatidic acid biosynthetic process parentage missing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16949]
this parentage 
GO:0046474   glycerophospholipid biosynthetic process
is present in quickgo, not in GO

is the removal intentional?

**Comment by ukemi** [comment]
Should be fixed with the new GCIs that @balhoff is adding.

**Comment by ukemi** [comment]
I just checked and this relation is in ChEBI.

phosphatidic acid (CHEBI:16337) is a glycerophospholipid (CHEBI:37739).
In GO we assert the conjugate base.

**Comment by ukemi** [comment]
@balhoff. Checked at 7:19PM Eastern. I still don't see this, but I can't tell if you have rebuilt all the files. I don't see the GCIs for phosphatidate (-2) that have the new relations.

**Comment by balhoff** [comment]
Not yet. :-) Found something else I missed. Will keep you posted.

**Comment by balhoff** [comment]
Okay @ukemi please check it out now.

**Comment by ukemi** [comment]
Yay! The GCIs are there and phosphatidic acid biosynthetic process is_a glycerophospholipid biosynthetic process.

**Comment by ValWood** [comment]
Great!
