### ISSUE TITLE
Add primary input-output relations to manual pathways

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#16943]
Now that the has_primary_input and has_primary_output dust has settled, we need to go back and look at the pathways that we have manually created to change the metabolites appropriately. Another thing on our list next week @deustp01.

**Comment by deustp01** [comment]
Yes. Do we have a NYC action item list or ticket? @ukemi

**Comment by ukemi** [comment]
You wish has come true. @vanaukenk, let's keep track of the things we do next Thursday and Friday in this project.

@huaiyumi @goodb @thomaspd @cmungall

**Comment by ukemi** [comment]
Many of these will probably be solved with the GCI updates, but we should check: #16953, #16951, #16950, #16949

**Comment by ukemi** [comment]
So here are some things to ponder:

NADH oxidation and NADPH oxidation/regeneration--- Are they NAD(P)H/NAD(P) metabolism?  I think we don't want them to be. 

@deustp01 I just did glycolysis, do you remember any other pathways we did that din't have biosynthesis/catabolism in their names?

**Comment by deustp01** [comment]
**Preventing unwanted reasoner inferences.** We want to say that glycolysis is the conversion of glucose to pyruvate accompanied by the generation of NADH from NAD+ and of ATP from ADP. But then we need advice from someone good at writing weasely fine print on how to phrase this so the reasoner is not allowed to view glycolysis as an aspect of, or a variant of ATP and NADH metabolism.

Maybe we could go at it from the other end, and assert that "nucleotide metabolism" comprises reactions that convert non-nucleotide compounds into nucleotides and vice versa, as well as reactions that convert one nucleoptide into another (e.g., IMP to AMP) and non-nucleotide compounds and is separate from, maybe a sibling of, "nucleotide interconversion", reactions that alter the 5'-phosphorylation state of a nucleotide.

Then we wouldn't need to put limits on the reason - it would find nucleotide interconversion when it looks at glycolysis but that's OK.

I think this could work for NAD(P) as well - "NAD(P) metabolism" comprises reactions that make it from other chemicals and vice versa, "NAD(P) - NAD(P)H interconversion or oxidoreduction" comprises reactions that change the redox state of NAD(P).

**Pathway names that lack the words biosynthesis / catabolism.** Among the ones we've thought about, the fermentations? More generally, TCA cycle, urea cycle, pentose phosphate pathway. There may be a pattern here: processes that are cyclical or that are networks don't necessarily progress from a single starting point to a single goal, while biosynthesis and catabolism do generally have this linear progressive feature. And the loops and networks do have metabolism grouping terms as parents, so their connection to linear metabolism is preserved. The fermentations are linear, but we could fix that by renaming "fermentation of pyruvate to X" to "fermentative catabolism of pyruvate to X".

Effects of all of this on slims are another issue.

**Comment by ukemi** [comment]
I think we can fulfill your wish. I will show you how on Thursday. I did a test with my favorite pathway.

**Comment by ukemi** [comment]
I did the fermentations and the pentose-phosphate shunt this afternoon. I did molybdenum cofactor biosynthesis. I think the TCA cycle is ok, but we should look together.

You're spot on in your second paragraph too!

**Comment by ukemi** [comment]
Added by hand in NYC.

**Comment by ukemi** [comment]
Note that the final decision was to include gycolysis as a metabolic process for the 'currency chemicals'. This is very easy to change if we change our minds.
