### ISSUE TITLE
pentose-phosphate shunt, non-oxidative branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16948]
I would expect to see this as "carbohydrate metabolism" but now it is 

"carbohydrate derivative metabolism" (because glyceraldehyde 3-phosphate is classified as a phospho-sugar?) NOTE: glucose-3 phosphate also has this classification!  

This isn't really where I would expect to find it ?

 and it no longer slims for us.

Were  would expect to find it with

GO:0006091    JSON
generation of precursor metabolites and energy

Could this be added?

**Comment by ukemi** [comment]
We will look at this at the end of the week, but my first reaction is that if it keeps its current definition, it is a carbohydrate derivative metabolism. All the textbooks that I look at say the pathway starts with G6P, not glucose. Unless we add in the glucokinase step, it should remain this way.

**Comment by ValWood** [comment]
Ah OK so is the parentage always based on  the first compound in the pathway?

**Comment by deustp01** [comment]
No. As far as I can tell, there's a historical inconsistency. Logically, glycolysis and the pentose phosphate pathway start by converting the common molecule glucose-6-phosphate into something that is pathway specific, but in biochemist culture, glycolysis is said to start with glucose and its first step is said to be phosphorylation to form glucose-6-phosphate. But the pentose phosphate pathway is said to start with glucose-6-phosphate.

**Comment by ValWood** [comment]
I think it just never occurred to me to refer to "glucose-6-phosphate." as a "carbohydrate derivative"  It's a phosphorylated glucose sugar but isn't it still a carbohydrate. I thought a carbohydrate derivative as things like UDP-glucose....
It seems that this will cause lots of logic issues?

**Comment by ukemi** [comment]
The logic will follow the ChEBI classifiaction. The parentage is not based on the first compound in the pathway, it's based on primary participants. For catabolism that is usually one of the first compounds input into a pathway, for biosynthesis it is usually one of the last outputs of a pathway (emphasis on usually). If I had said glucose-6-phosphate was a carbohydrate on one of my old biochemistry exams, I think my professor would have marked it wrong.

**Comment by ValWood** [comment]
the reason I asked is because it won't slim...

![slimming](https://user-images.githubusercontent.com/7359272/53685785-2ec95780-3d17-11e9-83fd-3e2c31e8669c.jpg)

although glycolysis also used to have 
generation of precursor metabolites and energy
and now it doesn't...

**Comment by deustp01** [comment]
Both  GO:0009051 pentose-phosphate shunt, oxidative branch and  GO:0009052 pentose-phosphate shunt, non-oxidative branch are is-a children of GO:1901135 carbohydrate derivative metabolic process, it seems like their shared parent, GO:0006098 pentose-phosphate shunt could also have the p-p shunt is_a parent, which doesn't fix the slim but it gets as close as a half-century of biochemist usage will probably allow (it's the metabolism of pentose and other phosphates (carbohydrate derivatives), not of pentose (carbohydrate) itself. I'm reporting our biochemist colleagues' word choice, not justifying it.

**Comment by ukemi** [comment]
Some of the work that we did with refactoring the way inputs and outputs of metabolic processes are handled now allows us to say things like ADP being input to a catabolic process doesn't necessarily mean that the ADP is being catabolized. With that in place, we are now able to define things like ADP->ATP and 'NADPH regeneration' as 'generation of precursor metabolites and energy'. This is one of the things we did at our NYC meeting with @deustp01 last week. With the new assertions in place, the reasoner is inferring that 'glycolytic process' and the oxidative branch of the pentose phosphate shunt are 'generation of precurson metabolites and energy'. But we couldn't see an obvious reason why the non-oxidative branch would be. 

As for the carbohydrate-derivative classification, we also checked several more textbooks in NYC and they all had the shunt beginning with the G6P, as is stated in the previous comment.

**Comment by ukemi** [comment]
But, the whole shunt is still not classified as a generation of precursor metabolites and energy. I suspect this is because just because something that is the output of a part of a process doesn't mean that it is an output of the whole process. It could be an input of another part of the process and therefore not output. Next week @deustp01 @vanaukenk and I will look at this more closely. I think that we might have to add the additional overall inputs and outputs to the 'pentose phosphate shunt'. Then the whole pathway will classify.

**Comment by ukemi** [comment]
OK. I added the key reactants back the the parent pathway. All looks good to me now. Interesting that we have to do this. There has got to be a better way using property chains.

**Comment by deustp01** [comment]
> Some of the work that we did with refactoring the way inputs and outputs of metabolic processes are handled now allows us to say things like ADP being input to a catabolic process doesn't necessarily mean that the ADP is being catabolized. With that in place, we are now able to define things like ADP->ATP and 'NADPH regeneration' as 'generation of precursor metabolites and energy'. This is one of the things we did at our NYC meeting with @deustp01 last week. With the new assertions in place, the reasoner is inferring that 'glycolytic process' and the oxidative branch of the pentose phosphate shunt are 'generation of precursor metabolites and energy'. **_But we couldn't see an obvious reason why the non-oxidative branch would be._**

First, an obsessive / paranoid bit of clarification: "generation of precursor metabolites and energy" means generation of precursors OR energy OR both, right?

As long as that is true, then the non-oxidative branch fits as well: it yields erythrose 4-phosphate that can be used for phenylalanine biosynthesis in plants and microorganisms, and fructose 6-phosphate and glyceraldehyde 3-phosphate both of which can be metabolized to pyruvate and NADH and ATP. So some precursor metabolites and some energy.

**Comment by ukemi** [comment]
Or is correct. I will also assert the non-oxidative branch. Thanks @deustp01 .

**Comment by ukemi** [comment]
OK, the PR is in now. It would be really nice if we could write axioms for the generation of precursor metabolites and energy. If we could list all of the precursor metabolites as children and then define them as any process in which they were output, we would get automatic classification. I am always uncomfortable asserting is_a relations when a term has a logical def. It is an indication of incomplete definitions. Maybe we could look into this in the summer when you are here.

**Comment by deustp01** [comment]
Sorry. More fussing.
First, should the definition of GO:0006098 pentose-phosphate shunt be changed?
Now:

> The glucose-6-phosphate catabolic process in which, coupled to NADPH synthesis, glucose-6-P is oxidized with the formation of carbon dioxide (CO2) and ribulose 5-phosphate; ribulose 5-P then enters a series of reactions interconverting sugar phosphates. The pentose phosphate pathway is a major source of reducing equivalents for biosynthesis reactions and is also important for the conversion of hexoses to pentoses.

Proposed:

> The metabolic process in which glucose-6-phosphate is oxidized to form carbon dioxide (CO2) and ribulose 5-phosphate, coupled to reduction of NADP+ to NADPH; ribulose 5-P then enters a series of reactions that can yield biosynthetic precursors (ribose-5-phosphate and erythrose-4-phosphate) and glycolytic intermediates (fructose-6-phosphate and glyceraldehyde-3-phosphate).

And, working from the QuickGO ancestry chart above, it qualifies as an is-a child of GO:0044238 primary metabolic process (The chemical reactions and pathways involving those compounds which are formed as a part of the normal anabolic and catabolic processes. These processes take place in most, if not all, cells of the organism) or as an is-a child of GO:0051156 glucose-6-phosphate metabolic process (The chemical reactions and pathways involving glucose 6-phosphate, a monophosphorylated derivative of glucose with the phosphate group attached to C-6). Would one or both of those parentages help with the slimming issue that started this issue?

**Comment by ukemi** [comment]
No worries @deustp01. I always value your input. Let's have another look at this together. To fit your definition, we would want to change the logical definition too.

**Comment by ValWood** [comment]
1 
> Some of the work that we did with refactoring the way inputs and outputs of metabolic processes are handled now allows us to say things like ADP being input to a catabolic process doesn't necessarily mean that the ADP is being catabolized. With that in place, we..

Will you talk about this at the GO meeting? It would be really useful...

2. It would be really nice if we could write axioms for the generation of precursor metabolites and energy.

Agreed....we use this in pombe and generic slims, as do lots of other groups/slims. We are aware that it is rather a vague term....

**Comment by deustp01** [comment]
Pentose phosphate definition and logical definition. The chemicals I added to the definition look like bad  choices for primary inputs or outputs just because they bridge this process to diverse other ones. They could be ordinary inputs and outputs. Is it better to aim for logical definitions that contain the minimum set of elements needed to specify an instance uniquely or is it OK to add more? My guess is "minimum" but let's discuss, maybe tomorrow afternoon briefly? @vanaukenk ?

**Comment by ukemi** [comment]
We will certainly talk about it at the GOC meeting. It's something we have been wanting to do for a long time. Maybe we can take a little time after the pathways2GO meeting tomorrow.

**Comment by ukemi** [comment]
It would be best to use the minimum criteria that would make the definition necessary and sufficient as we tried to do with glycolysis. But if we want to define this as a G6P metabolic process, we will need to change the logical definition to be a metabolic process. The only reason why we would specify chemicals as primary inputs and outputs would be if we wanted to classify this process as a metabolism of those chemicals. If we could create a list of all of the chemicals that we think are 'precursor metabolites', it would be relatively straightforward to make a class 'generation of precursor metabolite X' and logically define it as any metabolic process that has output some X. Then all processes in which that chemical was an output would classify automatically. This is similar to how we have handled the generation of ATP from ADP and NADPH regeneration. I think we can tweak the NAD(P) terms a bit more. But at the end of the day, any process that converts ADP to ATP and Generated NADPH from NADP gets automatically classified as a 'generation of precursor metabolites and energy'.

**Comment by ukemi** [comment]
Hi @deustp01 just a quick note that I looked at this in more detail this morning. I think you are correct that the textual definition needs tweaking. This process is in fact being inferred to be a metabolic process, not a catabolic one. I still think it would be worthwhile to have a quick look together to make sure that things are up to snuff.

**Comment by ukemi** [comment]
Tweaking the textual def. Leaving as a carbohydrate derivative metabolic process as is specified by the textbooks.
