### ISSUE TITLE
N-glycan processing (GO:0006491)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16952]
is_a glycoprotein metabolic process

but based on the def it should be 
is_a glycoprotein biosynthetic process?

**Comment by mah11** [comment]
No, it looks correct as is - the glycan processing pathways include some trimming steps, and the text def mentions both glycosidases and glycosyltransferases.

(e.g. fig 2 in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4236024/)

**Comment by ValWood** [comment]
But, 

the definition root is "The conversion of N-linked glycan (N = nitrogen) structures from the initially transferred oligosaccharide to a mature form"

this is part of  "biosynthesis" in this context

but I agree the  "N-glycan processing" can precede the ER quality control step, but in this case the def should make this clear.

**Comment by mah11** [comment]
No, the standard def for biosynthesis is "The chemical reactions and pathways resulting in the formation of x". Conversion to a mature form may include parts other than biosynthesis. Neither GO:0006491 specifically nor maturation or "processing" generally is defined as part of biosynthesis.

I'm not opposed in principle to editing the def text, but to me it is already clear.

**Comment by mah11** [comment]
oh, and the definition has nothing to do with the timing of glycan processing relative to ER quality control; some of the glycan processing takes place in the Golgi anyway

**Comment by ValWood** [comment]
There is something wrong here.

N-linked glycoprotein maturation | exact
glycoprotein trimming involved in glycoprotein maturation | exact

These aren't exact?

We need  descendants to annotate if the processing is part of maturation or  degradation.

**Comment by mah11** [comment]
I think the 'maturation' exact synonym is correct based on the review I looked at. The 'trimming' synonym should be narrow.

I wouldn't expect full-on degradation to be counted as "processing", tho with the caveat that I don't know this area particularly well.

**Comment by ukemi** [comment]
I agree with @mah11, it seems that the 'trimming' synonym should be narrow.

**Comment by ukemi** [comment]
I'm going to change the synonym type. If you decide that more needs to be done, please open another ticket.
