### ISSUE TITLE
	 U6 snRNA 3'-end processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16953]
no  longer slims to/ has ancestor

snRNA metabolic process

**Comment by ukemi** [comment]
We will need to add the new relations to the children manually.

**Comment by ukemi** [comment]
Started with terms with ' in the string.

**Comment by ukemi** [comment]
Part 1 PR: https://github.com/geneontology/go-ontology/pull/16954

**Comment by ukemi** [comment]
Val,

I went through and cleaned up the rest of these manually. I'm hoping I didn't overlook any. Running the reasoner looks good and all these are back under the metabolic process terms. I'm going to close this ticket after I merge my PR. If you spot anything else in the RNA branch, open another ticket and assign it to me.

**Comment by ValWood** [comment]
OK thanks, will check tomorrow.

**Comment by ukemi** [comment]
Part 2 PR: https://github.com/geneontology/go-ontology/pull/16955
