### ISSUE TITLE
cyclic-GMP-AMP hydrolase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#16966]
Hi GO,
I would need a new GO term for cGAMP hydrolase activity.

Thanks

Sylvain

Molecular Function
Definition: Catalysis of the reaction: cyclic GMP-AMP + 2 H2O = AMP + GMP
child of GO:0016818 hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides

PMID:25344812
Xref: Rhea:58808 (not yet public)

**Comment by hdrabkin** [comment]
I cannot use the Rhea until it becomes public; 
.

**Comment by ukemi** [comment]
Right, so tag it with Rhea pending and leave it open. Then check every once in a while and when it becomes available, add it and close the ticket.

**Comment by hdrabkin** [comment]
yes I know; just note to requestor

**Comment by hdrabkin** [comment]
GO:0106177
will add rhea xref when available

**Comment by sylvainpoux** [comment]
Thanks Harold!
