### ISSUE TITLE
ntr & def edits - linear elements

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16969]
We've recently learned of some ways to improve the representation of linear elements and their assembly in GO.

1. CC - edit one definition and add one new term

a. linear element ; GO:0030998

current def: "A proteinaceous scaffold associated with S. pombe chromosomes during meiotic prophase. Linear elements have a structure related to but not equivalent to the synaptonemal complex."

suggested new def: "A proteinaceous scaffold associated with fission yeast chromosomes during meiotic prophase. Linear elements consist of a protein complex, LinE, with four main structural components (Rec10, Rec25, Rec27, and Mug20 in S. pombe) associated with chromatin. The resulting structure is related to but not equivalent to the synaptonemal complex."

or delete more of the old def; I don't mind

b. new term

id: GO:new1
name: LinE complex 
def: "A protein complex that associates with chromatin to form linear elements in fission yeast. In S. pombe, the LinE complex contains four main structural components (Rec10, Rec25, Rec27, and Mug20) and other associated proteins."
GO:0032991 ! protein-containing complex
is_a: GO:0044428 ! nuclear part

As I understand it, this complex first forms in the nucleus and then binds to chromatin to form linear elements.

2. BP - edit one existing def and add two new terms

a. linear element assembly ; GO:0030999

current def: "The cell cycle process in which a proteinaceous scaffold, related to the synaptonemal complex, is assembled in association with S. pombe chromosomes during meiotic prophase."

suggested new def: "The cell cycle process in which linear elements are assembled in association with fission yeast chromosomes during meiotic prophase. Linear element assembly begins with LinE complex formation and ends when LinE complexes are associated with chromatin in structures visible as nuclear foci. A linear element is a proteinaceous scaffold related to the synaptonemal complex."

b. new terms

id: GO:new2
name: LinE complex assembly
def: "The aggregation, arrangement and bonding together of a set of components during meiotic prophase to form a LinE complex, the protein complex that associates with chromatin to form linear elements in fission yeast. In S. pombe, the LinE complex contains four main structural components (Rec10, Rec25, Rec27, and Mug20) and other associated proteins."
GO:0034622 ! cellular protein-containing complex assembly
relationship: part_of GO:0030999 ! linear element assembly

id: GO:new3
name: choose one of "linear element maturation", "LinE focus formation", "LinE chromosome loading"
def: "The close association of LinE complexes with chromatin during meiotic prophase to form mature linear elements."
synonyms: any of the above not used as the term name
is_a: ??? maybe GO:0070192 ! chromosome organization involved in meiotic cell cycle; otherwise I'm not sure of anything more specific than GO:0016043 ! cellular component organization
relationship: part_of GO:0030999 ! linear element assembly

The two parts of linear element assembly can be separated phenotypically - there are mutants in which LinE complexes form apparently normally but don't associate with chromatin.

This is all based on personal communications to @Antonialock from Cristina Martín Castellanos, who has done an awesome job of community curation for PMID:30640914. I think you can use that paper as a definition reference for all of the edited defs and new terms, or we can ask Cristina if she can recommend other papers.

(enough labels on this one?)

**Comment by ukemi** [comment]
Couldn't you find any more tags to add to this?

Quick question:
The resulting structure is related to but not equivalent to the synaptonemal complex."

Is there any way we could put how they are different in the definition?

**Comment by mah11** [comment]
> Couldn't you find any more tags to add to this?

Does it count as "in progress" now that you've claimed it? ;)

> Is there any way we could put how they are different in the definition?

I'd be very happy to, but I don't know this biology well. From a very quick nose round ...

- PMID:16532354 (https://link.springer.com/article/10.1007%2Fs00412-006-0047-7) is a review that isn't recent enough to be completely up-to-date, and I haven't read the whole thing, but we may still be able to work with a couple of passages from it:
  - "The SC is a tripartite structure consisting of two parallel lateral elements (to which chromatin loops are attached) and transversal filaments which hold the lateral elements, and thereby the homologous chromosomes, together (Wettstein et al. 1984)."
   - "It was noticed that the general morphology of LinEs, their time and place of appearance and their silver staining reactivity were reminiscent of the axial1 or lateral elements of SCs in other organisms (Bähler et al. 1993)."

- PMID:16043696 (https://www.pnas.org/content/102/31/10952) has
   - "In most organisms, a large proteinaceous structure, the synaptonemal complex (SC), forms between homologs around the time of crossing over and disappears before meiosis I. S. pombe lacks a full-fledged SC but does form linear elements, which by electron microscopy resemble the axial element precursors to lateral elements of the SC in other organisms (6, 7). "

 Is any of that useful? If not, @Antonialock could ask Cristina and probably get plenty of info in reply.

**Comment by mah11** [comment]
> I miss working with you @mah11 ! 

awwww :)

> The above was very helpful.

oh good.

> It seems like the distinction is essentially a taxon restriction, correct?

That, and the synaptonemal complex seems to have more parts, at least by electron microscopy.

> I see a never in pombe for the synaptonemal complex, but I don't see any on the linear element.

I've never heard of anything to do with meiotic chromosomes being called "linear elements" in anything other than fission yeast, so yes, I think it can have "only in Schizosaccharomyces" until/unless additional biology crops up.
