### ISSUE TITLE
obsoletion proposal: GO:1904013 Xenon atom binding and GO:1904012 platinum binding

### ISSUE THREAD

**Issue by uhinz** [geneontology/go-ontology#16968]
Hi,
PMID:10089464  describes that crystallization was done under Xenon atmosphere. Xenon is a "noble gaz", i.e. it is chemically inert, poorly soluble in water and of very low abundance, and thus extremely unlikely to bind to a protein.
GO:1904013 (Xenon atom binding) : Interacting selectively and non-covalently with xenon atom. PMID:10089464 
In the same paper, the authors use a heavy-metal derivative (a platinum compound, not a simple platinum ion) to determine the structure. Again, this is something that happens exclusively in vitro.

I'd propose to obsolete both terms,  GO:1904012 (platinum binding) and GO:1904013 (Xenon atom binding)

Best wishes,
Ursula

**Comment by pgaudet** [comment]
Send message to go-friends: 

Dear all, 

The proposal has been made to obsolete GO:1904013 xenon atom binding and GO:1904012 platinum binding. 

The reason for obsoletion is that these atoms do not have physiological relevance. There is one annotation to each term (to the same protein, using the same paper). There are no mappings; the term is not present in any subsets (slims). 

Any comments can be added to the issue: #16968

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 11th, 2019. Unless objections are received by March 11th, 2019. we will assume that you agree to this change.

Thanks, Pascale
