### ISSUE TITLE
Move membrane insertase under 'molecular carrier activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16976]
All transporter activities should be transmembrane transporters.

**Comment by ValWood** [comment]
> All transporter activities should be transmembrane transporters.

This should be the other way around?
And it doesn't match the title?

**Comment by pgaudet** [comment]
> This should be the other way around?
And it doesn't match the title?

Right - that's not the point of this ticket, you're right - just a note to myself as to why we want to move membrane insertase out and the next ticket to open. 

Thanks, Pascale
