### ISSUE TITLE
Location of Transmembrane Protein 9 in Human mis-assigned

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-ontology#16979]
Location of Transmembrane Protein 9 in Human mis-assigned
There are 2 closely related proteins: TMEM9B (Q9NQ34) and TMEM9 (Q9P0T7) in Humans.  A research paper "The lysosomal transmembrane protein 9B regulates the activity of inflammatory signaling pathways". PMID: 18541524. looked at TMEM9B but not TMEM9.  They showed that it was localized in the lysosome and late endosome.  GO annotation ascribed these locations to TMEM9 rather than TMEM9B, though they used the correct PMID.  They got the BP annotation correct, though.

**Comment by pgaudet** [comment]
@keslingmj These types of requests (dealing with annotations rather than GO terms) need to be opened in the Annotation Tracker - https://github.com/geneontology/go-annotation/issues

I will move your ticket there. 

Thanks, Pascale

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-annotation#2281

**Comment by keslingmj** [comment]
Thanks Pascale.  That's what I was looking for!
