### ISSUE TITLE
Modification to the definitions for microRNA process terms

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16998]
I have identified a few papers where a microRNA downregulates the level of a lncRNA. Ie there is evidence that it is not just mRNAs that are downregulated by miRs. although there is evidence that regulation of the lncRNAs can occur in the nucleus PMID: 23985560, this is AGO2-mediated. Additional papers have also confirmed that lncRNAs are downregulated by a AGO2 and miR-mediated process (PMID: 28379604). 

I am therefore requesting the revision of the definitions for some of these terms to remove the mRNA specificity and allow the terms to be used when the RNA does not encode a protein.

The problem is that there are alot of terms which mention mRNAs in this branch. I have discussed this with Rachael Huntley and she agrees with this proposal.

 GO:0035194 posttranscriptional gene silencing by RNA
revised definition (change mRNA to RNA (often mRNA)): Any process of posttranscriptional gene inactivation (silencing) mediated by small RNA molecules that may trigger RNA (often mRNA) degradation or negatively regulate translation

 GO:0035195 gene silencing by miRNA
revised definition (change mRNA to RNA (often mRNA)): Downregulation of gene expression through the action of microRNAs (miRNAs), endogenous 21-24 nucleotide small RNAs processed from stem-loop RNA precursors (pre-miRNAs). Once incorporated into a RNA-induced silencing complex (RISC), miRNAs can downregulate gene expression by either of two posttranscriptional mechanisms: endolytic cleavage of the RNA (often mRNA) or mRNA translational repression, usually accompanied by poly-A tail shortening and subsequent degradation of the mRNA. 

 GO:0060964 regulation of gene silencing by miRNA
revised definition (change mRNA to RNA (often mRNA)):  Any process that modulates the rate, frequency, or extent of the downregulation of gene expression through the action of microRNAs (miRNAs), endogenous 21-24 nucleotide small RNAs processed from stem-loop RNA precursors (pre-miRNAs). Once incorporated into a RNA-induced silencing complex (RISC), miRNAs can downregulate gene expression by either of two posttranscriptional mechanisms: RNA (often mRNA) cleavage or translational repression. 

 GO:0060965 negative regulation of gene silencing by miRNA
revised definition (change mRNA to RNA (often mRNA)):  
Any process that decreases the rate, frequency, or extent of the downregulation of gene expression through the action of microRNAs (miRNAs), endogenous 21-24 nucleotide small RNAs processed from stem-loop RNA precursors (pre-miRNAs). Once incorporated into a RNA-induced silencing complex (RISC), miRNAs can downregulate gene expression by either of two posttranscriptional mechanisms: RNA (often mRNA) cleavage or translational repression.

 GO:0035196 production of miRNAs involved in gene silencing by miRNA
revised definition (change mRNA to RNA (often mRNA)):  
Cleavage of stem-loop RNA precursors into microRNAs (miRNAs), a class of small RNAs that primarily silence genes by blocking the translation of mRNA transcripts into protein, or by increasing the degradation of non-protein-coding RNA transcripts. PMID:15066275 PMID:15066283 

In addition a new Molecular Function term is needed:
GO:0003723 RNA binding 
> is_a child New term RNA binding involved in posttranscriptional gene silencing
Definition: Any RNA binding that is involved in posttranscriptional gene silencing.
(PMID: 23985560, PMID: 28379604).
>> Is_a child: GO:1903231 mRNA binding involved in posttranscriptional gene silencing
Definition: Any mRNA binding that is involved in posttranscriptional gene silencing.

 GO:0016441 posttranscriptional gene silencing
> part_of child New term RNA binding involved in posttranscriptional gene silencing

I may have missed some terms, but it would be good to have an agreement on the principle and then hopefully any I have missed will be agreed on too?

Thanks 

Ruth
@BarbaraCzub

**Comment by BarbaraCzub** [comment]
Hi @RLovering
I agree it is a good idea to implement these revisions, so that these terms could also be used to capture regulation of expression of long non-coding (lnc) RNAs, and not only protein-coding mRNAs.
I'll start making these edits, and then if I find any other missing terms, I'll suggest them in this (or a new) ticket.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
@RLovering what is your dbxref?

**Comment by ukemi** [comment]
Hi @BarbaraCzub. Could you also add the publication references to the new defs, so we have some precedence for the change?

**Comment by BarbaraCzub** [comment]
Of course. Good point. I'll add these when I add the new term (next branch). Thanks @ukemi !

**Comment by BarbaraCzub** [comment]
@RLovering have you annotated any other relevant papers in addition to PMID:28379604?

**Comment by RLovering** [comment]
GOC:rl

**Comment by RLovering** [comment]
PMID: 23985560

**Comment by BarbaraCzub** [comment]
Thanks!
