### ISSUE TITLE
GO:0017122 protein N-acetylglucosaminyltransferase complex, definition and use in bacteria

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#16994]
Hi,
I have 2 questions for this term.
1) This term as defined in GO (pasted here):
"Heterotrimeric enzyme complex, which in humans is composed of two large subunits of the same size, and one smaller subunit. Functions in the addition of nucleotide-activated sugars onto the polypeptide. PMID:15247246".
In fact the rat enzyme is active as a homotrimer (AC P56558) composed only of the 110 kDa subunit (the "smaller" 78 kDa subunit may be a spliced version or a proteolytic product of the larger) see discussion in PMID 10542233. The human enzyme crystallizes as a monomer, and PMID 21240259 says "The model is shown as a monomer, but OGT may exist in different oligomerization states in cells.". So the definition is incorrect.

2) This term has only been used in bacteria (!), where the complex is a heterotetramer of 2 GtfA and 2 GtfB subunits (PMID 24936067). Neither bacterial subunit is a paralogue of the eukaryotic enzyme. As the bacterial enzyme has a totally different subunit composition, which is part of the definition itself, is it appropriate to have it annotated with this term? 

My personal opinion is that this term shouldn't mention subunit composition at all, and then it could be used for a complex in any organism that has this activity. Then I can use it to annotate my bacterial enzyme, as well as human, rat and rabbit...

Thanks for your help, Andrea

**Comment by pgaudet** [comment]
@bmeldal What do you recommend ?

**Comment by bmeldal** [comment]
I agree with Andrea, complex terms would be defined by their activity, not composition. Definitions can include examples, like "in human it is composted of...".

Suggested definition:

A protein complex capable of protein N-acetylglucosaminyltransferase activity, the addition of nucleotide-activated sugars onto the polypeptide according to reaction: UDP-N-acetyl-D-glucosamine + protein = UDP + 4-N-(N-acetyl-D-glucosaminyl)-protein.

[optional addition]
The complex has different compositions in different species: In mammals it is often a homotrimer, in bacteria a heterotetramer of 2 different subunits.

Birgit

**Comment by pgaudet** [comment]
Thanks !
