### ISSUE TITLE
Change definition 'GO:0038024 cargo receptor activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16996]
Hello, 

With @lbreuza we noticed that the definition of 'GO:0038024 cargo receptor activity' refers to endocytosis; however there are also intracellular cargo receptors, so we propose to update the definition to account for that. 

CURRENT DEF: Combining selectively with an extracellular substance and delivering the substance into the cell via endocytosis.
NEW DEF: Binding specifically to a substance (cargo) to deliver it to a transport vesicle. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood We looked at several of these terms together; does that seem OK to you ?

**Comment by ValWood** [comment]
Yes definitely should be broadened!
ALso cargo receptor does not have the parent

protein binding,bridging,  and
molecular adaptor activity
