### ISSUE TITLE
Merge 'GO:0015557 arginine targeting transmembrane transporter activity' into 'GO:0009977 proton motive force dependent protein transmembrane transporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17006]
'GO:0015557 arginine targeting transmembrane transporter activity' represents a transport pathway,  GO:0043953 protein transport by the Tat complex. 

Proteins involved in GO:0043953 protein transport by the Tat complex are annotated to 'GO:0009977 proton motive force dependent protein transmembrane transporter activity', so I will (1) merge GO:0015557 into that term. 

and (2) add synonym 'Twin-arginine translocation pathway' to GO:0043953 protein transport by the Tat complex. 

FYI there are annotations by 
TAIR @tberardini 
EcoCyc @keseler 
UniProt @sylvainpoux 
and PseudoCAP. 

Thanks, Pascale

**Comment by tberardini** [comment]
Do the annotations need reviewing?

**Comment by ValWood** [comment]
Seems an odd merge if it is describing an arginine transporter?

**Comment by pgaudet** [comment]
It's not an arginine transporter - it recognizes twin arginines as signals (note that term label was GO:0015557 arginine **targeting** transmembrane transporter activity' 


@tberardini There were no annotations to GO:0015557 (sorry about the confusion; my query was rather 'does this make sense since you have annotated the same function differently - but I should have formulated it !) . 

Thanks, Pascale
