### ISSUE TITLE
Query 'GO:0015219 protein-DNA complex transmembrane transporter activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17005]
Hello, 

Anyone knows any gene product that could be annotated to 'GO:0015219 protein-DNA complex transmembrane transporter activity'? and to the corresponding process  GO:0051035 DNA transmembrane transporter activity' ? 

These terms were created in 2001 and have never been used. I will propose to obsolete unless someone can identify potential proteins to annotate to these. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete 'GO:0015219 protein-DNA complex transmembrane transporter activity'

The reason for obsoletion is that there are no instances of this function in the literature.

There are no annotations to these terms and no mappings. The terms are not in any subsets (slims).

Any comments can be added to the issue: geneontology/go-ontology#17005

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 15th, 2019. Unless objections are received by March 15th, 2019. we will assume that you agree to this change.

Thanks, Pascale

**Comment by mgiglio99** [comment]
Hi @pgaudet 
There are many naturally competent bacteria that transport DNA across their membranes from the outside of the cell into the inside of the cell. They generally reuse the type II secretion system acting in reverse to retract type IV pili and pull in the DNA. So I guess those proteins would be annotated both to secretion and to DNA transporting transmembrane activity.  Perhaps no one in prok land has gotten around to doing those annotations. 
Here are some papers:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3816411/
https://jb.asm.org/content/196/8/1471
https://www.sciencedirect.com/science/article/pii/S096098221631003X?via%3Dihub
I think it likely that there are papers that would also provide evidence for protein-DNA transport - but I haven't looked for that yet.
Michelle

**Comment by pgaudet** [comment]
Do they transport DNA in a complex with a protein ? I couldn't find any evidence for that.

**Comment by mgiglio99** [comment]
That's the bit I'm still checking on. I haven't found evidence for that yet either, unless you count that the DNA is stuck to the pilus proteins, and the pilus with the DNA attached gets pulled in.

**Comment by mgiglio99** [comment]
This paper talks about relaxase proteins traveling with DNA across the membrane:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2786583/
This paper mentions that DNA-protein complexes can be transported, but I haven't had a chance to read it carefully or chase down the refs:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3922410/

**Comment by pgaudet** [comment]
- PMC2786583 mentions a DNA-protein complex, but the protein part of the complex helps in the translocation, it's not really a target of the transport. 
- PMC3922410 mentions "Each of these systems exports distinct DNA **or** protein substrates" - no protein-DNA complex. 

I will obsolete; we can always recreate the term if needed.
