### ISSUE TITLE
canalicular membrane

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#17003]

**Comment by brendamg** [comment]
Hey, what can I do with the term "canalicular membrane" of hepatocytes. It`s the location for the enzyme 7_6_2.3. PMID:9068608 and PMID:9034162
The small apical (canalicular) domains of hepatocytes form a luminal meshwork of tubules between adjacent hepatocytes and are the sites of primary bile formation.
Transport of bile acids across the canalicular membrane of the hepatocyte provides the primary motive force for generation of bile flow and is rate limiting in the vectorial movement of bile acids from blood to bile. 
Do you think it is a new term? or s.th. like "plasma membrane"?
Best whishes, Marion

**Comment by ukemi** [comment]
Maybe a synonym of intracellular canaliculus GO:0046691?

**Comment by cmungall** [comment]
> Maybe a synonym of intracellular canaliculus GO:0046691?

It's not clear to me if this is intended for gastric cells only, or if that is intended as an exemplar?

what about plasma membrane of cells of the
http://purl.obolibrary.org/obo/UBERON_0001283

**Comment by brendamg** [comment]
Canalicular membrane is only used for bile acid transport and canalicular plasma membrane is used as a synonym.

**Comment by ValWood** [comment]
so this sounds exact
https://www.ebi.ac.uk/QuickGO/term/GO:0046691 occurs_in hepatocyte
@brendamg  can this one be closed?

**Comment by hdrabkin** [comment]
So is this NTR or synonym request

**Comment by ValWood** [comment]
intracellular canaliculus
is defined
Definition (GO:0046691 GONUTS page)
An apical plasma membrane part that forms a narrow enfolded luminal membrane channel, lined with numerous microvilli, that appears to extend into the cytoplasm of the cell. A specialized network of intracellular canaliculi is a characteristic feature of parietal cells of the gastric mucosa in vertebrates. PMID:10700045

so it seems that you can add "canalicular membrane" based on the term, definition and requester comment.

**Comment by ValWood** [comment]
added "as a synonym"

**Comment by hdrabkin** [comment]
done
