### ISSUE TITLE
Proposal to obsolete 'lipoprotein transporter activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17004]
Hello, 

For completing the work on MF refactoring: 
The term 'lipoprotein transporter activity' has been used inconsistently - see annotation review here: 
https://github.com/geneontology/go-annotation/issues/2285

I propose to obsolete this term and create two new terms: 
-  ~lipoprotein transmembrane transporter activity~ for bacteria lolC, E and D and 
-> lipoprotein releasing activity' #17058
- lipoprotein carrier activity for bacteria lolA

See https://www.pnas.org/content/114/18/4769 - Fig 1

Thanks, Pascale

**Comment by deustp01** [comment]
@pgaudet Terminology question - the definitions are framed in terms of bacterial proteins with these functions. How do we apply them to human ones? No problem distinguishing transport in the sense of moving something across a membrane from transport in the sense of assembling a lipoprotein complex that can move in extracellular fluids of multicellular organisms and optionally home to receptors on specific cell surfaces or other lipoprotein types; just need some advice on applying your terms to tyhetwo categories.
Thanks

**Comment by pgaudet** [comment]
@deustp01 
I am not sure I am following - both functions I propose are species-agnostic: Does it help if I removed the names of the genes that should be annotated to each ? 

*  lipoprotein transmembrane transporter activity 
*  lipoprotein carrier activity

**Comment by deustp01** [comment]
Got it. OK, the one Reactome annotation that now uses GO:0042954 lipoprotein transporter activity can be edited to use G:xxx lipoprotein transmembrane transporter activity. Does that term exist yet (can't find in QuickGO or Amigo)?

**Comment by pgaudet** [comment]
@deustp01 My recommendation is in https://github.com/geneontology/go-annotation/issues/2285
Move to 'GO:0038024 cargo receptor activity'	

Let me know what you think ! 

Pascale

**Comment by deustp01** [comment]
@pgaudet Looking closer, I think our original annotation was a mistake. What is actually getting transported across the membrane here is a complex of a protein and a vitamin. (I cab=n see why we might have equated that complex to a lipoprotein but it looks wrong.) So what is the best single term here:
GO:0090482 vitamin transmembrane transporter activity
GO:0008320 protein transmembrane transporter activity
GO:0022857 transmembrane transporter activity.
This is a question about GO usage; any one of the terms works for us. Maybe GO:0008320 protein transmembrane transporter activity is best, if from the GO view "protein" includes a protein that has bound a small non-protein molecule. Which one shall we use?

**Comment by pgaudet** [comment]
Hi @deustp01 
Reactome also has an annotation to 'low-density lipoprotein particle receptor activity', which is consistent with the UniProt description 'Multiligand endocytic receptor (etc). 

So, is it ALSO a transmembrane transporter ? This would be quite unusual. 

(Maybe we can skype if that's easier). 

Thanks, Pascale

**Comment by pgaudet** [comment]
@mgiglio99 @keseler 
Can I go ahead with the obsoletion and creation of the proposed terms? (see annotations here: https://docs.google.com/spreadsheets/d/13YY6cRqfcXngf3y5Aetw3zlt20qDMfpilnWX6jf6sH4/edit#gid=0)

Thanks, Pascale

**Comment by deustp01** [comment]
@pgaudet Yes, Skype would be good. I'm peter.deustachio

**Comment by deustp01** [comment]
The MF annotation has been changed to GO:0038024 cargo receptor activity at least for now (until we can come up with a more specific term). That change will propagate to the public Reactome site with our June 2019 release but in the meantime term obsoletion can go ahead.

**Comment by pgaudet** [comment]
Dear all, 

For the Molecular Function refactoring, the proposal has been made to obsolete 'GO:0042954 lipoprotein transporter activity’, and to create two new terms to correctly capture the function of the proteins currently annotated to this term, 

lipoprotein transmembrane transporter activity for bacteria lolC, E and D and
lipoprotein carrier activity for bacteria lolA

Annotations to eukaryotes have been removed. There are 9 ISS annotations to bacterial genes by ISS by TIGR and JCVI. The reason for obsoletion is that terms have been incorrectly used. 

This term isn’t present in any slims. There are a number of mappings to this term: 

InterPro:IPR011925
InterPro:IPR011926
InterPro:IPR015854
InterPro:IPR018323
UniRule:UR000100917
(which correspond to LolA, C, D and E descibed above). 



Any comments can be added to the issue: #17004

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 18th, 2019. Unless objections are received by March 18th, 2019. we will assume that you agree to this change.

Thanks, Pascale

**Comment by mgiglio99** [comment]
@pgaudet 
Yes, you can go ahead and change the TIGR and JCVI annotations to the new term 'lipoprotein transmembrane transporter acitivity'
