### ISSUE TITLE
phenyloplast as new term?

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#17002]
Hey, 
PMID 24683183 describes a new organelle: Phenol homeostasis is ensured in vanilla fruit by storage under solid form in a new chloroplast-derived organelle, the phenyloplast.
It`s the location of the enzyme 4_1_2.41. 
Could you please add it to the cellular component ontology? 
Thank you, Marion from BRENDA-Enzymes

**Comment by ukemi** [comment]
Cool. Although it makes me wonder if vanilla should be one of my favorite ice cream flavors. As a sanity check this should be a child of plastid?

**Comment by brendamg** [comment]
Yes I think so. Or simply derived from chloroplast.
