### ISSUE TITLE
missing parent of GO:0045087    innate immune response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17013]
Is a descendant of
GO:0006952    defense response

should this be moved to be a descendant of  "defense response to other organism"

![innate immune response](https://user-images.githubusercontent.com/7359272/54111665-5639b780-43dc-11e9-886a-8628a8b97067.jpg)

**Comment by pgaudet** [comment]
That seems reasonable to me and consistent with the definitions of the terms.
