### ISSUE TITLE
rename :effector dependent induction by symbiont of host immune response TO symbiont induction of host effector-triggered immunity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17014]
We looked for the term to describe the process
"Effector-triggered immunity" and eventually located

GO:0080185 effector dependent induction by symbiont of host immune response
which is very nicely defined
Any process that involves recognition of an effector, and by which an organism activates, maintains or increases the frequency, rate or extent of the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction. Effectors are proteins secreted into the host cell by pathogenic microbes, presumably to alter host immune response signaling. The best characterized effectors are bacterial effectors delivered into the host cell by type III secretion system (TTSS). Effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance or R proteins) and subsequent activation of host immune response. PMID:16497589

but is there any reason why the primary term name can't contain

"Effector-triggered immunity"? 2,440,000 results

"effector dependent induction by symbiont of host immune response" About 223 results
presumably all from GO.

I very nearly missed this term. And it only has 5 annotations which is no surprise!

**Comment by ValWood** [comment]
Once this name is changed can we have
positive and negative regulation terms for  "Effector-triggered immunity

and then, a special type of "negative regulation" 
symbiont-mediated supression of effector triggered  immunity  
negative regulation of effector-triggered immunity by a pathogen or symbiont.

this would have a "never in metazoa" taxon restriction

**Comment by ValWood** [comment]
There are problems here.

"effector triggered immunity"

has a ancestor "response to host"
This is as a result of the  ancestor   "reponse to host defenses"

Thi ETI *is* a response response to host defences, since it is a response to the first wave (Pamp-triggered immunity). Hover, this causes many violations because this is quite indirect.

The  pathogen  production of an "effector" is the actual response to host-defences (first layer PIT layer).

Then,  the host mounts a ETI reponse (if it can). But it isn't really correct to call the host ETI response a  "response to host defences". This is conflated because it is through the pathogen.
In effect, this is a "response response" and it's switching between pathogen and host.

I  really think the solution here is to remove "response to" terms.
I *know* we have a problem if we don't know what the *precise* response is, BUT in these cases maybe we should not be annotating, as it's only really a phenotype"

**Comment by ValWood** [comment]
getting rid of the  "response to" would also resolve: 
https://github.com/geneontology/go-ontology/issues/17017

**Comment by ValWood** [comment]
If removing the "response to" is a step to far an alternative is to just remove

![response to](https://user-images.githubusercontent.com/7359272/54128259-982a2400-4403-11e9-956b-ee123a75afa2.jpg)

response to host and 
response to host defenses
from the ontology
and keep "response  to other organism" this would be correct when this type of conflation occurs and a host responds to a pathogen responding to a host.

For now could you remove "response to host defences" as a parent of GO:0080185  as its confusingly incorrect.

**Comment by ValWood** [comment]
GO:0080185
effector triggered immunity
should also have the parent "innate immune response"


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4189875/
The focus of this review will be on innate immunity, particularly on “effector triggered immunity” (ETI), a process by which bacterial toxins or secreted proteins initiate a protective immune response in the host.

**Comment by pgaudet** [comment]
Similar to what I reported in #17040

'GO:0080185 effector dependent induction by symbiont of host immune response' is only used in 3 annotations (in AmiGO), for **host** proteins. The definition suggests that we are looking to annotate *symbiont* proteins that trigger the 'effector dependent host immune response'; is this right ?

**Comment by ValWood** [comment]
We have problems here.

The "effector triggered immunity" is a plant pathway triggered by pathogen  effectors. The pathogen effector has a role in "supressing the plant immune system by some pathway (known or unknown). (not through this pathway).

The plant recognizes the effector (in another level of immune response) and  triggers the "effector triggered immunity" signalling, which results in the hypersensitive cell death response. The plant kills its own tissue on purpose to reduce the pathogen infection. The purpose of the effector from the pathogen point of view is NOT to induce this pathway (which is why I mistakenly though it applied to the host ). 

So to me, although this term is cast from the pathogen perspective, it seems wrong to have such a term?

The pathogen effector also evolves to *evade* the "effector triggered immunity" pathway. But this isn't a process. The outcome (depending on the molecular combination of pathogen effector and host receptor is either positive regulation of  ETI, or not (i.e self cell killing  by plant or no plant cell killing) either results in the activation of this pathway, or it doesn't. 

The immune evasion here is happening by evolution and isn't a process it's a strain/species dependent  trait?

**Comment by ValWood** [comment]
@CuzickA  is this correct?

The pathogen  effector doesn't actively "modulates" the plant ETI . It just aims to evade it (over time) by selection of variations which are not recognised by the plant innate immune receptor. If this is  the case, this term does not belong in GO ( this means the original GO annotations I tried to make are incorrect, I added a comment to the session to this effect).

Or maybe there are other trypes of "effector" which activate this pathway intentionally (but this wouldn't really make sense as it works against the pathogen?, why would the pathogen process trigger immunity?).

**Comment by ValWood** [comment]
If this is correct I suggest obsoletion of this term.

and the parent
GO:0052559    JSON
induction by symbiont of host immune response
Definition (GO:0052559 GONUTS page)
Any process in which an organism activates the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction.

These are not  normal biological processes for these "effectors"

**Comment by lreiser** [comment]
following

**Comment by lreiser** [comment]
Following
I agree that TAIR annotations to GO:0052308 should be moved.
Looks like a small number(11 annotations) and I will review them today.

**Comment by pgaudet** [comment]
GO:0052559 induction by symbiont of host immune response
has some annotations; do you think these are not correct ? 

(TAIR @tberardini and RGD @slaulederkind are probably wrong) 

Pascale

**Comment by CuzickA** [comment]
> Or maybe there are other trypes of "effector" which activate this pathway intentionally (but this wouldn't really make sense as it works against the pathogen?, why would the pathogen process trigger immunity?).

> 
@ValWood 
Biotrophic pathogens require living host tissues to obtain their nutrients and the ETI host cell death defense response kills the host cell and thus the biotrophic pathogen in the host cell.
Nectrotrophic pathogens live on dead host tissues which they kill before or during colonization. (Hemibiotrophs start out as biotrophs and switch to a necrotrophic lifestyle). Nectrotrophic effectors can trigger host cell death to benefit their growth- effector triggered susceptibility (ETS). We have one of these types of papers on our curation list PMID:22241993 The cysteine rich necrotrophic effector SnTox1 produced by Stagonospora nodorum triggers susceptibility of wheat lines harboring Snn1.

Tagging @KEHammond to have a read through this ticket

**Comment by ValWood** [comment]
OK. In that case maybe  once we get to that we can define some suitable

necrotrophic effector-triggered host-cell death?
For this situation.
We could then make it clear that this is "evolved"  symbiont induced death of host tissue?

**Comment by KEHammond** [comment]
Dear Val,
I am with Alayne  this afternoon going through this ticket.

The normal function  is 'effector triggered susceptibility' in hosts. The pathogen is trying to infect the host and produced the effector to aid infection.   The host evolves a response which we call 'effector triggered resistance'  by directly or indirectly recognising the incoming effector and activates many defence responses. This works perfectly for the biotrophs.  For the hemibiotrophs and necrotrophs something else happens and the effector recognition and tissue death does not stop  the pathogen and disease ensues. The later most probably happens because these pathogens have evolved mechanisms to overcome the induced host defences.   

Hope that helps,

Kim

**Comment by lreiser** [comment]
@pgaudet @tberardini 
3 TAIR annotations to  GO:0052559 reviewed and removed.

**Comment by tberardini** [comment]
Thanks very much, @lreiser.

**Comment by ValWood** [comment]
Thanks @KEHammond 

so we need

GO:0080185  symbiont induction of host effector-triggered immunity  
for necrotrophic effectors which activate the host ETI pathways


we can probably  add  "effector triggered susceptibility"   as  a related synonyms to 
GO:0042783    evasion of host immune response

"effector triggered susceptibility"  doesn't  tell us  any more about how the effector is making the plant susceptible 

 The 'evolved' role of  biotrophic effectors is to avoid the plant immune response. They may not be doing this by manipulating ETI (more likely interfering with PTI? ) but could be affect any of numerous  plant processes ( They are  only recognised by the plant ETI).

This is why it is really difficult to add a "Molecular function" or any more spcific process than   GO:0042783 to pathogen effectors in GO. We know they are mitigating/evading/manipulating the plant responses  we don't usually know the mechanism (I.e molecular function MF)  , or even the specific process  (BP) (at least for the papers I read so far)
We only know that on the other side the plant resistance receptors recognize them and initiate the second plant defenses (ETI).

Is that a reasonable summary ?

**Comment by ValWood** [comment]
this ticket is replaced by
https://github.com/geneontology/go-ontology/issues/18310
and
https://github.com/geneontology/go-ontology/issues/18311
which are much simplified
