### ISSUE TITLE
children of GO:0003994 aconitate hydratase activity?

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#17037]
'GO:0047780 citrate dehydratase activity' and 'GO:0052633 isocitrate hydro-lyase (cis-aconitate-forming) activity' should probably be children of 'GO:0003994 aconitate hydratase activity'?
https://github.com/geneontology/go-ontology/issues/9423

**Comment by ukemi** [comment]
There is already a has_part relationship between these terms.
