### ISSUE TITLE
ATP synthase parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17035]
proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)

has the parents

cation-transporting ATPase activity
is_a ATPase activity, coupled to transmembrane movement of ions, rotational mechanism

but this is ATP  synthase not ATPase

**Comment by dsiegele** [comment]
There are 3 types of proton translocating ATPases with a rotational mechanism: P-type, V-type, and F-type. I think the P-type and V-type ATPases function only as ATP-ases. But the F-type ATPases can function either as an ATP synthase (where protons crossing a membrane drive synthesis of ATP from ADP + P1) or as an ATPase (where ATP -> ADP + Pi provides the energy to move protons back across the membrane).  The location of GO:0046933 in GO makes sense to me in terms of the biochemistry because all the protein complexes I know of that have proton-transporting ATP synthase activity, rotational mechanism are also proton-translocating ATPases. But that may not fit with the logic of the ontology structure. 

Links:
https://en.wikipedia.org/wiki/Proton_ATPase


Stewart et al. (2014) Current Opinion in Structural Biology 
https://doi.org/10.1016/j.sbi.2013.11.013

**Comment by ValWood** [comment]
but to annotate the non ATP synthase direction you would use

proton-transporting ATPase activity, rotational mechanism?

(some of the exact synonyms are conflicting too)

**Comment by ukemi** [comment]
Quick note for the assigned curator. The = sign in the definitions means that these reactions are all defined as bidirectional despite their names. At first glance this leads me to agree with @dsiegele.

**Comment by ValWood** [comment]
But we have both reactions in GO?

I think it is really important for representing the biology that we retain this distinction.
ATP synthase creates the energy currency for the cell.

There is an old discussion about having both terms somewhere but I suspect it is so old it is on Source Forge (I can't find it on GitHub), but I seem to remember that , the reverse mitochondrial reaction isn't physiologically relevant. So surely we should represent the reaction in the correct direction with appropriate parentage?

Otherwise it's really difficult to model the biology.

We represent the v-ATPase  as an ATPase and the mitochondial F0-F1 as an ATP synthase?

**Comment by deustp01** [comment]
EC and Rhea treat all chemical reactions as reversible in principle, if I remember right. @dsiegele ? This one is probably a valid example - given high enough concentrations of what we normally think of as reaction products, the system could be driven to generate what we think of as reaction substrates. Doesn't GO follow this usage, that by default the description of the direction of a molecular function is agnostic as to direction? So is a direction emerges, that can only happen at the process level? Unless there's some way to impose a "physiological direction" attribute on the function from outside of GO? @ukemi ?

**Comment by ValWood** [comment]
Hmm, I see, so how does that work with kinase/phosphatase etc?

**Comment by deustp01** [comment]
It takes a hell of as lot of phosphoprotein, ADP, and patience.

**Comment by ValWood** [comment]
;)
but we don't follow the agnostic as to direction  for GO in this case?

**Comment by deustp01** [comment]
Here's an example:
   GO:0004713 protein tyrosine kinase activity
   Molecular Function
   Definition: Catalysis of the reaction: ATP + a protein tyrosine = ADP + protein tyrosine phosphate. 
Which takes us back to @ukemi 's comment above:
> Quick note for the assigned curator. The = sign in the definitions means that these reactions are all defined as bidirectional despite their names.

**Comment by dsiegele** [comment]
The reverse reaction (ATP --> ADP + H+) is physiologically relevant in bacteria. During fermentative growth, i.e. growth without an electron transport chain, some taxa of bacteria use this process to generate a pmf.

**Comment by ValWood** [comment]
> Here's an example:
GO:0004713 protein tyrosine kinase activity

OK I misunderstood, I think. @deustp01  you are saying that we don't specify the direction *even though* we annotate directionally based on the term name?

>The reverse reaction (ATP --> ADP + H+) is physiologically relevant in bacteria.

There should be a term for this too.

At present it's really confusing because the entire ancestry is specified as ATPase

see the parent
GO:0019829    cation-transporting ATPase activity
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + cation(out) = ADP + phosphate + cation(in).

until this term when the term name switches to  ATP synthase.  It should be consistent but I don't want to annotate a mitochondrial F1F0 ATP synthase as an ATPase. It would look wrong.

There is clearly a precedent for forcing directionality when it is biologically important (kinase/phophatase).

**Comment by dsiegele** [comment]
In Trypanosoma brucei, the mitochondrial F1Fo ATPase functions differently depending upon the host organism. In the insect host, it functions as an ATP synthase and generates ATP.  In the mammalian bloodstream form of T. brucei, the same enzyme functions primarily as an ATPase and is required to maintain the mitochondrial membrane potential.

PMID: 28414727

**Comment by dsiegele** [comment]
also,  https://doi.org/10.1111/j.1432-1033.1992.tb17278.x

**Comment by ValWood** [comment]
That's OK, we have terms for both activities

GO:0046933    proton-transporting ATP synthase activity, rotational mechanism
or
GO:0046961    proton-transporting ATPase activity, rotational mechanism

coupled to the appropriate process and the lifecycle stage

 This is a reason why it is important to represent both directions- because they represent different aspects of biology.

Parentage of both terms demonstrates more clearly why the parentage is incorrect:
![parentage](https://user-images.githubusercontent.com/7359272/55135701-564bee00-5124-11e9-96af-c52755a72358.jpg)

**Comment by vanaukenk** [comment]
After discussion with @ValWood and @pgaudet, we propose to add GO:0016776 'phosphotransferase activity, phosphate group as acceptor' as a parent to the 'proton-transporting ATP synthase term and remove the ATPase parent.  Not having the phosphotransferase parent seems to be missing a biologically relevant MF parent.

For curation, curators would annotate to the ATP synthase and/or ATPase MF terms and, ideally, provide the appropriate biological context to capture when the 'machine' and its subunits enable each type of MF.

We also discussed the 'proton transmembrane transporter activity' MF parent for 'proton-transporting ATP synthase.  According to the definition, this MF seems to fit GO:0022803 'passive transmembrane transporter activity':

"Enables the transfer of a single solute from one side of a membrane to the other by a mechanism involving conformational change, either by facilitated diffusion or in a membrane potential dependent process if the solute is charged."

@pgaudet - does this seem correct to you?

Note that the question remains about which RHEA to xref to for each MF term and also that synonyms will need to be reassigned appropriately.

**Comment by pgaudet** [comment]
> @pgaudet - does this seem correct to you?

Yes

> Note that the question remains about which RHEA to xref to for each MF term and also that synonyms will need to be reassigned appropriately.

I thought we had decided on the directionality of the Rhea reaction for both (or at least for one of them - I think Rhea is missing the synthase?) 

Thanks, Pascale

**Comment by vanaukenk** [comment]
>I thought we had decided on the directionality of the Rhea reaction for both (or at least for one of them - I think Rhea is missing the synthase?)

I think we weren't clear on exactly how 'in' and 'out' should be interpreted, but tagging @amorgat here for guidance.
