### ISSUE TITLE
BMP/Dpp signaling pathways

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17052]
decapentaplegic signaling pathway GO:0008101

Looking a Dpp signaling, I think that 'decapentaplegic signaling pathway' GO:0008101 should be merged with or at least moved under 'BMP signaling pathway' GO:0030509 as Dpp is a member of the BMP family and we have other BMP family ligands that don't have equivalent ligand-based signaling classes. 
I would prefer a merge, as it is cleaner. Apart from one UniProt annotation, to UniProtKB:Q9V853, we (FlyBase) are the only group that have used this GO:0008101 in manual annotation.

**Comment by vanaukenk** [comment]
@hattrill  I can merge 'decapentaplegic signaling pathway' into 'BMP signaling pathway'.

I think we should also then merge the three 'regulation of decapentaplegic signaling pathway' terms into the corresponding 'regulation of BMP signaling pathway' terms.

For all of these merges, I'll make the decapentaplegic terms narrow synonyms.  Are there synonyms for the other BMP family ligands that you'd like to add?

It looks like UniProt is also the only group besides FlyBase that has annotations to the regulation terms, so tagging @milarolo to make sure they are also okay with these merges.  Thx.

**Comment by milarolo** [comment]
It's fine with us. You can go ahead with the merge.

**Comment by hattrill** [comment]
Hi Kimberly, 

Sounds good. 

The other ligands (such as glass bottom boat and screw) tend not to be used in the pathway names - tend to be classed just as BMPs - so no need for other synonyms. 

Thanks, 
Helen
