### ISSUE TITLE
Merge and rename 'autophagy involved in symbiotic interaction' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17055]
Hello, 

I think this 'autophagy involved in symbiotic interaction' triad should be cleaned: 

 -  GO:0075071 autophagy involved in symbiotic interaction
 --  GO:0075044 autophagy of host cells involved in interaction with symbiont
 ---  GO:0075072 autophagy of symbiont cells involved in interaction with host 
 ---- GO:0075073 autophagy of symbiont cells on or near host surface

Only 'GO:0075044 autophagy of host cells involved in interaction with symbiont' has been used - it looks like a defense mechanism to clear infection. 

Pascale

**Comment by marcfeuermann** [comment]
Hi,
Autophagy plays indeed an important role in host-symbiont interactions, and I totally agree with Pascale, some cleaning of the existing terms seems necessary.

**GO:0075071 - autophagy involved in symbiotic interaction**: 
This term looks really weird. One of the roles of autophagy is the defense against pathogens, So autophagy is "almost always" involved in symbiotic interactions. We even have created the term **xenophagy** . So, all host autophagic proteins should be annotated with GO:0075071.

However, there are proteins of the symbionts that indeed regulate autophagy of the host, to block it or to hijack it to their advantage (via a positive regulation).
So I would replace **'GO:0075071 - autophagy involved in symbiotic interaction'** by **'modulation by symbiont of host autophagic process'**, which will be a child of  **'GO:0044068 - modulation by symbiont of host cellular process'**.

As this modulation could be a positive or a negative regulation I would propose to create the following children:
**'positive regulation by symbiont of host autophagic process'** (this would replace **GO: GO:0075044**)
**'negative regulation by symbiont of host autophagic process'**

I've never seen a case where the host regulates the autophagy of the symbiont. Even if it cannot be ruled out. There is always the possibility to create a new and more appropriate term in the future, if we find that such a case was indeed described. 

I'm not sure the terms **'GO:0075072 - autophagy of symbiont cells involved in interaction with host'** and **'GO:0075073 autophagy of symbiont cells on or near host surface'** are relevant. They were infered from PMID:18837106. Many papers describe the importance of autophagy of the fungus Magnaporthe oryzae in virulence toward its host. Again, there is no specific autophagy process for infection/virulence. Moreover, as mentioned earlier, the host plant does not play any role in regulating autophagy of the fungus.

I hope this will be helpful. May be @ukemi, you might have some suggestions.
Regards,
Marc.

**Comment by ukemi** [comment]
Hi @marcfeuermann 
During the autophagy overhaul, if I recall correctly we did not modify these terms. I've always hesitated to modify the organism interaction terms without input from experts.

**Comment by ValWood** [comment]
Hi @marcfeuermann
I like these suggestions and *fully* support changing to
"modulation by symbiont of host autophagic process" this is much clearer than existing term names.

The existing term names in this branch give me a head-spin.

I also fully favour removing the unnecessary parent groupings to represent everything reciprocally if we have no use case.

**Comment by pgaudet** [comment]
Thanks @marcfeuermann 

To summarize: 

- 'GO:0075071 autophagy involved in symbiotic interaction' -> modulation by symbiont of host autophagic process
- 'GO:0075044 autophagy of host cells involved in interaction with symbiont' -> 'positive regulation by symbiont of host autophagic process' 
- 'GO:NEW negative regulation by symbiont of host autophagic process'

Obsolete these terms: 
'GO:0075191  autophagy of host cells on or near symbiont surface'
'GO:0075072 autophagy of symbiont cells involved in interaction with host'
'GO:0075073 autophagy of symbiont cells on or near host surface'
'GO:0075074 spore autophagy involved in appressorium formation on or near host'

Is that right ? 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
If you put all these terms downstream of **GO:0044068 - modulation by symbiont of host cellular process** it is fine for me :-) 
Thanks a lot
Marc

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
'GO:0075191 autophagy of host cells on or near symbiont surface'
'GO:0075074 spore autophagy involved in appressorium formation on or near host'
'GO:0075072 autophagy of symbiont cells involved in interaction with host'
'GO:0075073 autophagy of symbiont cells on or near host surface'

The reason for obsoletion is that there is no specific autophagy process for infection/virulence. 
Also, the autophagy of symbiont by hosts can been captured using the term 'xenophagy GO:0098792'.

**Comment by genegodbold** [comment]
Forgive me for interjecting, but I'm trying to help out a group seeking to improve PathGO so I've been following you to see how you deal with GO. I've been annotating virulence proteins for a long time. I don't know if it is helpful, but there are a few examples of bacterial parasites manipulating host xenophagic processes. It's a form of immune evasion on the part of the bug. 

BopA from Burkholderia pseudomallei is a type III secretion system effector. It prevents targeting  of the bacterium by an LC3-associated phagocytosis which is also a sort of xenophagy (PMID22790007)

InternalinK from LIsteria monocytogenes appears to have some role in recruiting the host major vault protein to the bacterial surface which appears to protect it from xenophagy (PMID21829365)

SseL from Salmonella is an effector protease and deubiquitinase that reduces elimination of the bacterium by xenophagy (PMID22719249)
 
Shigella VirA inactivates host Rab1 which prevents host LC3 recruitment and inhibits xenophagy (PMID26015503) 

Not that you need my two cents, but I agree with Marc's comments that "autophagy" when applied to "symbionts" is just weird. 

Yours,
Gene

**Comment by marcfeuermann** [comment]
Hi Gene,
Your input is welcome and these are nice candidates for annotation using the newly created terms. Thanks a lot.
Regards,
Marc

**Comment by pgaudet** [comment]
Done! Thanks everyone for the feedback, Pascale

**Comment by pgaudet** [comment]
Change label to 'suppression of host autophagy' - The multi-organism WG has decided to use "induction" and "suppression" of host processes to distinguish from normal regulation.

**Comment by genegodbold** [comment]
Hey @pgaudet,
I like "suppression", but I think "induction" is an inappropriate word choice (https://www.merriam-webster.com/dictionary/induction). It connotes a passivity which doesn't fit here. 

Parent terms for these on/off binaries are often "modulation" and that's fine, though I prefer terms like "manipulation" and "hijacking" when it comes to parasites, as I think they better capture the alien/foreign character of how the parasite attempts to exert its molecular program on the host.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141088
+name: symbiont-mediated activation of host autophagy
+namespace: biological_process
+def: "A process in which a symbiont initiates, promotes, or enhances the activation of autophagy in the host cell. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+synonym: "induction of host autophagy" EXACT []
+synonym: "positive regulation by symbiont of host autophagy" EXACT []
+is_a: GO:0075071 ! symbiont-mediated perturbation of host autophagy
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/17055" xsd:anyURI
+created_by: pg
+creation_date: 2023-07-19T14:39:06Z



@genegodbold if you have non-viral papers for this, I would add them to this term.

**Comment by genegodbold** [comment]
- Omp33-36 from _Acinetobacter baumannii_ modulates autophagy in HEp-2 cells, increasing levels of the autophagic markers p62 and LC3B-II [PMID:25156738].
- Ats-1 from _Anaplasma phagocytophilum_, a T4SS effector, binds host beclin 1 (UniProtQ14457), a subunit of the class III PI3K and Atg14L which contributes to the instigation of autophagy in the host cell. Ats-1 localizes the host proteins beclin-1, Atg14L, and LC3 on the Anaplasma inclusion. This results in the membrane vesicle formation. Ats-1 by itself can nucleate autophagosomes decorated around Anaplasma inclusions with host ER autophagy proteins. Ats-1 promotes the growth of _Anaplasma phagocytophilum_ in host cells. Depleting beclin suppresses parasite infection [PMID:23197835][PMID:23388398]
- CvpB/Cig2 from _Coxiella burnetii_ is a T4SS effector important for interactions between the Coxiella-containing vacuole (CCV) and host autophagosomes and enhances the fusogenic properties of the CCV. The CCV has a unique ability to fuse promiscuously with other host compartments of the C. burnetii-infected cell. This requires a functional host autophagic system [PMID:25080348].
- Ectopically expressed Ehrlichia translocated factor-1 (Etf-1) from _Ehrlichia chaffeensis_ activates host class III PtdIns-3 kinase which results in autophagosome formation. Etf-1 interacts directly with host Rab5, PIK3C3 and BECN1 [PMID:27541856]. 

@pgaudet, I also have quite a few bacterial factors that inhibit autophagy/xenophagy
