### ISSUE TITLE
wrong parent for  GO:0006600 creatine metabolic process

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#17056]
GO:0006600 creatine metabolic process is_a  GO:1901605 alpha-amino acid metabolic process, but while creatine (CHEBI:57947 - creatine zwitterion (predominant form at pH 7.3); CHEBI:16919 - creatine) is an amino acid, it is not an **_alpha_** amino acid. A better is_a parent might be  GO:0006520 cellular amino acid metabolic process where it will have siblings like beta-alanine metabolic process.

**Comment by ukemi** [comment]
Looks like a ChEBI ticket is in order. Creatinate is an alpha amino acid anion.

**Comment by ukemi** [comment]
Should be fixed with new ChEBI import.
