### ISSUE TITLE
NTR: ubiquinone biosynthesis complex

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#17068]
Based on PMID 30686758, there is a cytosolic complex of proteins that comprise much of the pathway of ubiquinone biosynthesis: UbiE, F, G, H, I, J and K (in E. coli and probably Salmonella).  I'm not quite sure whether it should be a cytosolic part or something closer to the membrane - at some point, the end product needs to be delivered directly to the membrane.

Thanks,
Ingrid

**Comment by deustp01** [comment]
Would something like GO:0009898 "cytoplasmic side of plasma membrane" work to localize the complex?

**Comment by keseler** [comment]
Is that a membrane part?  The complex really does seem to reside in the cytosol, so GO:0031234, extrinsic component of the cytoplasmic side... might be appropriate, but also seems to be more specific than the evidence in the paper.  It would probably be best to just have it as a cytosolic part for now.
BTW, it seems to me that GO:0031234 should also be a cytosolic part.  Or does it depend what it predominantly purifies with - membrane, soluble, both?

**Comment by deustp01** [comment]
Yes. GO:0009898 "cytoplasmic side of plasma membrane" is part_of plasma membrane.
The term you mentioned seems promising: GO:0031234 "extrinsic component of cytoplasmic side of plasma membrane" Definition: The component of a plasma membrane consisting of gene products and protein complexes that are loosely bound to its cytoplasmic surface, but not integrated into the hydrophobic region.
I don't know how to define a boundary between membrane-ish and cytoplasm-ish. @ukemi?

**Comment by ukemi** [comment]
I think the boundary is defined by what we consider the primary association of the protein/complex. For example transmembrane receptors are associated with the membrane even though they catalyze their activities on either sides.

**Comment by vanaukenk** [comment]
@keseler 
I can make a new catalytic complex term that is part_of the cytosol for this complex.
Can you suggest an appropriate name and definition?  Thx.

**Comment by keseler** [comment]
@vanaukenk 
The paper just calls it the "Ubi complex", but I find that insufficient for annotation purposes (but good for a synonym?).   Maybe "ubiquinone biosynthesis complex"?
proposed definition:
"The cytosolic Ubi complex is composed of enzymes and accessory factors of the ubiquinone biosynthesis pathway and enables synthesis of the extremely hydrophobic molecule ubiquinone in the cytosol."

The paper calls it a "stable metabolon".  Should there be something about its composition in E. coli?  I don't want to make it too E. coli-centric; I'm pretty sure this complex, perhaps with different enzymes or accessory factors, exists elsewhere, too.

**Comment by vanaukenk** [comment]
@keseler 
There is some precedent for statements in complex definitions like, "In x organism, the complex consists of....." where the names of the members are listed.  I think that would be okay to do here, since we're not making a general statement about complex membership and listing the members from the reference might help users understand the term better.

We could also add a 'capable of part of' relation to ubiquinone biosynthesis or one of the more specific children, if you thought one of the children was more appropriate:

![image](https://user-images.githubusercontent.com/1730534/55511910-c16b5800-562f-11e9-8f62-46e10a4cc3ac.png)

**Comment by vanaukenk** [comment]
@keseler - I've added the 'ubiquinone biosynthesis complex' term to the ontology.  
I'm leaving the ticket open for now, though, as I'd like to discuss possible logical definitions with the ontology editors.

**Comment by pgaudet** [comment]
Discussion on Editors' call: in this case these are different functions, not some emerging function of the complex. We would capture a logical definition only if there is one overall function for the complex. (@vanaukenk please edit this if that was not accurate)

**Comment by ukemi** [comment]
PMID:27060254 is useful for the yeast and mammal viewpoint.

**Comment by vanaukenk** [comment]
After discussion on the editor's call, I updated the term definition and parentage to make this term more inclusive of any protein complex that is 'capable of part of' some ubiquinone biosynthetic process.

I also added another synonym and additional references to help clarify what we're trying to capture with this class in the ontology.
