### ISSUE TITLE
acetylcholine secretion should not be under hormone secretion

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#17063]
GO currently has:

![image](https://user-images.githubusercontent.com/112839/54867084-a60c6d00-4d52-11e9-9036-f03b0dca6c31.png)

This is incorrect.  neurotransmission != hormone secretion and this is the only case where the two are tangled in GO right now.  acetylcholine secretion should be removed from under hormone secretion.  If acetylcholine acts as a hormone under some circumstances, then that should be  represented by a new 'acetylcholine hormone secretion' term.

This is leading to incorrect classification of neurons as neurosecretory in FBbt which is a problem for VFB.

(More broadly this points to the need for better modelling of roles - the same molecule can play the role of a hormone in some situations and the role of a neurotransmitter in others), but I wouldn't want a general fix for this issue to get in the way of an easy quick fix).

**Comment by ukemi** [comment]
@cmungall this is also due to the ChEBI roles. We need to fix this issue more globally. Note we do have 'acetylcholine secretion, neurotransmission', which specifies context. I suspect this was added because of the potential hormone role, but the genus term should still not be using the role.

**Comment by cmungall** [comment]
Agreed, we should never use the biological role branch of CHEBI, each should be replaced by a BP.

how about

hormone secretion = secretion and involved-in endocrine signaling 

That is assuming hormone is always endocrine.. I guess not. Went down a worm (ho ho) hole here:
#17084

**Comment by ukemi** [comment]
This works sometimes, but doesn't work for things like binding terms. I thought about the above suggestions, but is the secretion part of the signaling? It is not part of the signaling pathway by our definitions. At one point I suggested that we have a more global term, signaling and broke it down into the generation of the signal and the reception of the signal. The signaling pathways would be reception. If I recall correctly that idea was rejected.

**Comment by pgaudet** [comment]
Can we not use hormone secretion = secretion and upstream of-cell-cell signaling (to also avoid the endocrine issue) ?

**Comment by dosumis** [comment]
cell-cell signalling ligand roles:

hormone
.   paracrine (local)
.   autocrine (self)
.   endocrine (via circulatory system)
neurotransmitter (across synapse, regulating postsynaptic membrane
potential)

Neurobiology terminology poss source of confusion.  Term hormone not
generally usex

Neuromodulator: paracrine signalling between neurons that modulates
neuronal signalling.  (My attempt at def - could probably be improved)

But...
Some neuromodulators are released at synapses. Neurotransmitters sometimes
work in paracrine fashion in nervous system.

**Comment by ukemi** [comment]
As well as all the immune system-related roles. Sometimes by the same molecules and signaling pathways. For example dopamine can also act in the nervous system, the immune system or the renal system.

**Comment by dosumis** [comment]
**Quick fix**: Please move 'acetylcholine sercretion' from under hormone secretion and 'acetylcholine transport' from under 'hormone transport'.  If these are inferences deriving from CHEBI then this can be fixed by using the plain CHEBI term in formal defs - not the GOCHE term for the molecule with the role.  

It would be great if you could do this soon as embarassing to have to explain to VFB users.

**A more complete fix could look something like this:**

cell-cell signaling
.   cell-cell signaling by hormone
.       paracrine cell-cell signaling
.       autocrine cell-cell signaling: cell-cell signaling between cells in close proximity
.       endocrine cell-cell signaling: cell-cell signaling via a ligand transported through the circulatory system
.   neurotransmission (already in correct place)
.   cell-cell signaling by neuronmodulator

hormone secretion EquivalentTo: secretion and part_of some 'cell-cell signaling by hormone'

CHEBI roles could (should?) be defined using these GO terms.

**Comment by ukemi** [comment]
The quickest fix would be to remove the logical def of hormone secretion to remove the role term. We can't do it directly at the level of the acetylcholine because it includes both the roles and the chemicals.

**Comment by ukemi** [comment]
OK. So as a quick fix, I will remove the logical definition of 'hormone secretion', which refers to the role. I will look at all of the currently inferred children of hormone secretion and assert the ones that I am confident have rigid roles as hormones. We need to systematically do this for other areas of the ontology, but this should be good here. Sorry it has taken so long @dosumis.

**Comment by cmungall** [comment]
Thanks, this is the best short term course of action and I like DOS's
proposal to use GO processes instead of CHEBI for hormone

**Comment by ukemi** [comment]
Just to try to be consistent. I am doing the same for hormone transport. Epinephrine transport is asserted as a hormone transport. I am going to remove that one. I'm pretty sure it is also a neurotransmitter. I agree that we should use processes, with the secretion terms it might be safe to use a causal relation...

**Comment by ukemi** [comment]
@krchristie, here is an example of how we solved one of these.
