### ISSUE TITLE
cargo receptor activity, update synonyms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17079]
Synonym | Type
-- | --
receptor activity involved in receptor-mediated endocytosis | exact
-> narrow or remove

receptor activity involved in ligand uptake | exact
-> narrow or remove (not only uptake)

receptor activity | broad -> related
this is  should also be related for "signalling receptor"

transport receptor activity | broad

endocytic receptor activity | exact  -> narrow

**Comment by pgaudet** [comment]
Done as part of the other ticket #17072

> receptor activity | broad -> related
this is should also be related for "signalling receptor"

This was already the case.
