### ISSUE TITLE
Obsoletion notice: GO:0008565 protein transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17071]
Dear all, 

The proposal has been made to obsolete GO:0008565 protein transporter activity. The reason for obsoletion is that the term has been inconsistently used: it’s been used mostly as the ‘protein transport’ process, but annotations represent various mechanisms to transport proteins. 

There are 116 EXP annotations as shown below. I have created a review ticket with suggestions as to how to re-annotate: 
https://github.com/geneontology/go-annotation/issues/2293

Contributor   (Assigned by) | Number of annotations
-- | --
CACAO | 1 @sandyl27 
dictyBase | 1 @pfey03 
EcoCyc | 1 @keseler  
EcoliWiki | 3
FlyBase | 9  @hattrill 
GeneDB | 2 @ggeorghiou 
MGI | 13 @hdrabkin 
SGD | 47 @srengel 
TAIR | 6 @tberardini 
UniProt | 30 @milarolo 

There are also 8 InterPro families with mappings @happy-lorna  

This term is present in 3 slims: 
goslim_chembl
goslim_generic
goslim_yeast
(the slim tags could be moved to the BP 'GO:0015031 protein transport'?) 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17071
We are opening a comment period for this proposed obsoletion. Since this involves some reannotation, I propose to obsolete this term on April 8th, 2019. Unless objections are received by April 8th, 2019, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pfey03** [comment]
Took care of mine, thanks!

**Comment by ValWood** [comment]
Hi Pascale, for obsoletions can you also  non-exp evidence codes. Pombe has a lot of ISS which we will need to reannotate but they are not in this list. We prefer to do them before the term disappears.
Also we have one experimental (IGI) but that doesn't appear.
https://www.pombase.org/term/GO:0008565

**Comment by pfey03** [comment]
I also found one IC we have and deleted that.

**Comment by pgaudet** [comment]
I have added a second spreadsheet with the non-IEAs annotations 


Contributor   (Assigned by) | Number of annotations
-- | --
AgBase | 1
ARUK-UCL | 1
ComplexPortal | 3
dictyBase | 10
FlyBase | 32
GeneDB | 14
JCVI | 12
MGI | 18
PINC | 3
PomBase | 6
RGD | 1
SGD | 1
TAIR | 4
TIGR | 12
UniProt | 66

**Comment by gthayman** [comment]
RGD has deleted the one TAS annotation.

**Comment by pgaudet** [comment]
Still to do: delete Reactome dbxrefs
