### ISSUE TITLE
NTR: cargo adaptor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17072]
Hello, 

In #17071 I explained why I think 'GO:0008565 protein transporter activity' should be obsoleted.  

To rehouse some annotations to AP adaptor, retromer, exomer, ect components, I will create a new term 'cargo adaptor activity' as descibed in PMID:25795254. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140312
+name: cargo adaptor activity
+namespace: molecular_function
+def: "Binding directly to sorting signals in the cytosolic tails of transmembrane cargos (or transmembrane cargo receptors serving as recognition interfaces for lumenal cargos), to  concentrate them into vesicles or tubules for transport through the secretory and endocytic pathways of cell." [PMID:25795254]
+is_a: GO:0003674 ! molecular_function
+created_by: pg
+creation_date: 2019-03-26T17:01:45Z
+

**Comment by pgaudet** [comment]
@lbreuza Does that seem OK ?

**Comment by ValWood** [comment]
We already have

clathrin adaptor activity (used for AP complex) substrate adaptors.

Will this be a descendant?

**Comment by pgaudet** [comment]
> We already have clathrin adaptor activity (used for AP complex) substrate adaptors. Will this be a descendant? 

Right now 'clathrin adaptor activity' is a child of 'endocytic adaptor activity' but we need something more general, like 'vesicular transport adaptor activity'. Would that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
works for me

**Comment by lbreuza** [comment]
Definition looks good to me. Will it replace 'endocytic adaptor activity' or a parent of it? I would say yes.

**Comment by pgaudet** [comment]
Hello, 

I edited the definition to be more general: 

Binding directly to sorting signals in the cytosolic tails of transmembrane cargos (or transmembrane cargo receptors serving as recognition interfaces for lumenal cargos), to  concentrate them into vesicles or tubules for transport through vesicular pathways such as intracellular vesicular transport, as well as the secretory and endocytic pathways of cell.

> Will it replace 'endocytic adaptor activity' or be a parent of it? 

Should these be siblings ?  The endocytic adaptor brings the endocytic receptor to its substrate - while this new 'cargo adaptor' term is a type of cargo receptor (maybe that's a better term label?)

**Comment by pgaudet** [comment]
In fact I think 'endocytic adaptor activity' should be renamed 'endocytic receptor adaptor activity' (definition is 'The activity of bridging an endocytic receptor to its substrate (for substrates that do not directly bind the cargo receptor).'

**Comment by ValWood** [comment]
what about the child
clathrin adaptor activity (GO:0035615)
For some reason this has a totally different def, 
The binding activity of a molecule that brings together clathrin and one or more other molecules, permitting them to function in a coordinated way.

which seems incorrect and insufficient for a clathrin adaptor,  (which is a cargo receptor?)

**Comment by pgaudet** [comment]
@lbreuza  @ValWood  Does this look OK ? 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/4782928/55155786-87deac80-5158-11e9-8275-438dba77fc2b.png">

**Comment by ValWood** [comment]
It looks fine. Perhaps "endocytic adaptor" is surplus ?
No need to put the process (endocytosis) in here is there?
Does the clathrin term have any siblings?

(I think it could add confusion later if particular coat proteins are  work across different pathways...)

**Comment by ValWood** [comment]
In the receptor branch, "endocytic  receptor" is an exact synonym of 
GO:0038024    cargo receptor activity, 
(maybe make that narrow?)

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/17079

**Comment by pgaudet** [comment]
+ changed the logical definition from 
molecular_function
 and ('part of' some 'receptor-mediated endocytosis')

to molecular_function
 and ('part of' some 'vesicle-mediated transport')

**Comment by pgaudet** [comment]
I also created a new grouping term: 
+[Term]
+id: GO:0140316
+name: vesicular transport adaptor activity
+namespace: molecular_function
+def: "Binding directly to sorting signals in the cytosolic tails of transmembrane cargos (or transmembrane cargo receptors serving as recognition interfaces for lumenal cargos), to concentrate them into vesicles or tubules for transport via intracellular vesicular transport or the secretory pathway." [PMID:25795254]
+is_a: GO:0140312 ! cargo adaptor activity
+created_by: pg

**Comment by pgaudet** [comment]
and updated the synonyms

**Comment by ValWood** [comment]
> Never mind - I see that the endocytic receptor is considered the 'cargo'

I don't think that is quite right. The cargo is the receptor substrate?

(unless you mean that the receptor is the 'substrate' of the adaptor

**Comment by pgaudet** [comment]
> (unless you mean that the receptor is the 'substrate' of the adaptor

I think this is what is meant in the literature. So the endocytic receptor comes in with its own cargo, and the receptor + its cargo becomes the cargo (I think).

**Comment by pgaudet** [comment]
I also fixed the definition of 'clathrin adaptor activity' for 
Bringing together a cargo protein with clathrin, responsible for the formation of endocytic vesicles. 

To match other definitions (improvements are welcome!) 

Pascale

**Comment by lbreuza** [comment]
> 
> 
> It looks fine. Perhaps "endocytic adaptor" is surplus ?
> No need to put the process (endocytosis) in here is there?
> Does the clathrin term have any siblings?
> 
> (I think it could add confusion later if particular coat proteins are work across different pathways...)

**Comment by lbreuza** [comment]
> (I think it could add confusion later if particular coat proteins are work across different pathways...)

I agree with Val comments.

**Comment by pgaudet** [comment]
@ValWood WRT your comment: 

> Perhaps "endocytic adaptor" is surplus ?
No need to put the process (endocytosis) in here is there?
Does the clathrin term have any siblings?

> (I think it could add confusion later if particular coat proteins are work across different pathways...)

This is a term you are requested. If you dont think it is needed, the simplest organization would be: 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/4782928/55221795-a2715e00-520a-11e9-84de-f13277d0ff72.png">


and get rid of 

'vesicular transport adaptor activity' and 
'endocytic adaptor activity'

**Comment by ValWood** [comment]
That sounds OK to me. Only direct to endocytic adaptor are 5 SGD annotations so maybe check with them @srengel  but I think it is surplus. Annotations could merge into "cargo adaptor activity"
or move down to COPII or clathrin?

**Comment by pgaudet** [comment]
It does seem like 'endocytic adaptor' should be removed, as clathrin and clathrin adaptors can be found in intracellular vesicles as well (PMID:19317650)

I am not sure whether there are endocytic-specific adaptors and intracellular-specific adaptors - @lbreuza do you know ? 

If thats the case then would we create all the different possible subclasses, such as 'endocytic clathrin adaptor' ; 'intracellular vesicular clathrin adaptor' .... ? 

The simplest version possible is the one I pasted two comments above; is this sufficient to describe the different functions ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@lbreuza agrees with the simplified version 

![image](https://user-images.githubusercontent.com/4782928/55403226-a88e7400-5555-11e9-8ec0-e2e7a8c2d779.png)

SGD @srengel @suzialeksander   and wormbase @vanaukenk  have annotations to 'endocytic adaptor activity'; would you be OK if the term label was just 'cargo adaptor activity' and annotatee endocytosis as the process ? 


Thanks, Pascale

**Comment by pgaudet** [comment]
Note to self: improve definition for cargo adaptor activity, since there is confusion about cargo and cargo receptor: 

Change from 
> Binding directly to sorting signals in the cytosolic tails of transmembrane cargos (or transmembrane cargo receptors serving as recognition interfaces for lumenal cargos), to concentrate them into vesicles or tubules for transport through vesicular pathways such as intracellular vesicular transport, as well as the secretory and endocytic pathways of cell.

to 
Binding together a cargo, or a cargo plus its receptor, with a protein composing the vesicular transport machinery (such as clathrin or COPII).

or something better ...

**Comment by vanaukenk** [comment]
@pgaudet 
I updated the WB annotation to 'clathrin adaptor activity' as this seemed to describe the role of CED-6 best.
The process in this case is apoptotic cell engulfment.

**Comment by pgaudet** [comment]
thanks @vanaukenk @srengel for the rapid response. I updated the ontology structure and improved the definitions for both 
- cargo receptor activity: Binding specifically to a substance (cargo) to deliver it to a transport vesicle. Cargo receptors span a membrane (either the plasma membrane or a vesicle membrane), binding simultaneously to cargo molecules and coat adaptors, to efficiently recruit soluble proteins to nascent vesicles.
- cargo adaptor activity: Binding directly to the structural scaffolding elements of a vesicle coat (such as clathrin or COPII), and bridging the membrane, cargo, and membrane deformation machinery.

**Comment by RLovering** [comment]
Hi sorry to be a pain but how will this term relate to the proteins being discussed here:  NTR protein transport chaperone #17073 ? GO:0140318 protein carrier activity? Only the protein I wanted to annotate binds microtubules and a target and this leads to localization of the target to a different part of the cell.
The definition of the cargo adaptor activity seems very similar to the definition of a term I am looking for except it is limited to the vesicle coat and therefore not appropriate to microtubule 'bridging'.
I guess I just wonder if cargo adaptor activity should be limited to the vesicle coat
Thanks
Ruth

**Comment by pgaudet** [comment]
Right - the cargo terms refer to vesicular transport. I'll comment in #17073

**Comment by pgaudet** [comment]
Errrr  this is not mention in the other ticket. What are you trying to annotate ?

**Comment by RLovering** [comment]
BAG3 we had agreed I would annotate it with GO:0140318 protein carrier activity

**Comment by pgaudet** [comment]
So are we all good ? (we can do this by email if not)

**Comment by RLovering** [comment]
yes it is all fine, please do go ahead. I just wondered how these two terms would be related. sorry to disrupt the process.

**Comment by pgaudet** [comment]
Ah ! No problem, thanks for asking ! The terms are not related: 

<img width="354" alt="image" src="https://user-images.githubusercontent.com/4782928/55485548-f45f1d00-562a-11e9-842e-f9b61951a4a1.png">


Do you think they should be ?
