### ISSUE TITLE
Obsolete 'antibiotic transmembrane transporter activity' and 'antibiotic transport'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17082]
Hi @cmungall 

To continue on #16962

I suppose we also want to obsolete 'antibiotic transmembrane transporter activity'? 

Thanks, Pascale

**Comment by pgaudet** [comment]
There are three types of annotations: 
(A)  transporters being hacked to **import** antibiotic in target cells (not a normal function; should it be in the scope?) Examples: E coli cycA, dtpA (with experiments showing that overexpression increases sensitivity to the antibiotic); efflux pumps, etc

-> Do we need a special term for this hacked function? 

(B) transports that **export** antibiotics from the species that synthesizes them (such as E. coli macB; http://amigo.geneontology.org/amigo/reference/PMID:28504659) 

-> should be annotated simply to 'transmembrane transporter activity' and 'export across plasma membrane' (like any other export); the substance can be specified by the 'has inout' relation

(C) transports that **export** antibiotics from the targeted species to detoxify 
-> annotate to 'GO:1990961 xenobiotic detoxification by transmembrane export across the plasma
membrane'

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0042895 antibiotic transmembrane transporter activity' and 'GO:0042891 antibiotic transport’. 

The reason for obsoletion is that the terms have been inconsistently used. There are three different uses: 
(A) transporters being hacked to import antibiotic in target cells (not a normal function; should it be in the scope?) Examples: E coli cycA, dtpA (with experiments showing that overexpression increases sensitivity to the antibiotic); efflux pumps, etc

-> Do we need a special term for this hacked function? Please let me know as you review your annotations, whether you find a place to re-house them or not. 

(B) transports that export antibiotics from the species that synthesizes them (such as E. coli macB; http://amigo.geneontology.org/amigo/reference/PMID:28504659)

-> annotate to 'transmembrane transporter activity' and 'export across plasma membrane' (like any other export); the substance can be specified by the 'has input' relation

(C) transports that export antibiotics from the targeted species to detoxify
-> annotate to 'GO:1990961 xenobiotic detoxification by transmembrane export across the plasma membrane'


Annotations: 
 'GO:0042895 antibiotic transmembrane transporter activity’ 
14 EXP annotations: https://docs.google.com/spreadsheets/d/1UaATMC_ch16EPYXSnaPI7QOJHUQJgbFyM198tK4nqDY/edit#gid=0

 'GO:0042891 antibiotic transport’. 
15 EXP annotations: https://docs.google.com/spreadsheets/d/1Iex3RzncnY10hexEpz4kNSREBJTbZI3L7MNJ_wqlPS0/edit#gid=0
1 InterPro mapping IPR022324 -> annotate to 'GO:1990961 xenobiotic detoxification by transmembrane export across the plasma membrane’

Those terms are not in any subsets (slims). 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/17082

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on April 4th, 2019. Unless objections are received by April 4rd, we will assume that you agree to this change.

Thanks, Pascale

**Comment by hdrabkin** [comment]
MGI only has annotations from RGD orthology load.

**Comment by dsiegele** [comment]
No objections.

**Comment by amandamackie** [comment]
Hi Pascale, (issue forwarded to me from Keseler@EcoCyc)

No objections to the proposed obsoletion but I would like to comment on rehousing to GO:1990961. 

Several of the most important efflux pumps in gram-negative bacteria (eg AcrAB-TolC) export antibiotics/xenobiotics across the outer membrane and are therefore not covered by a term that is specific to export across the plasma membrane. 

I am not sure whether this requires a separate term eg xenobiotic detoxification by export across the outer membrane, or an expansion of the definition of 1990961 to include the outer membrane. I'm inclined to think it should be a separate term since there are also transporters in gram negs which export across the inner/plasma membrane only.

Thank you
Amanda

**Comment by pgaudet** [comment]
Hi @amandamackie 
I think this is covered by the new term you requested here: https://github.com/geneontology/go-ontology/issues/17094
(which I just created)

I think some bacteria do both - detoxify AND export antibiotics that they produce, so 2 terms seem appropriate. 

Thanks, Pascale
