### ISSUE TITLE
Obsoletion notice: GO:0015307 drug:proton antiporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17081]
Dear all, 

The proposal has been made to obsolete GO:0015307 drug:proton antiporter activity
(see longer discussion in #16962) 

The rationale is that whether a particular case of transmembrane transport for a chemical constitutes a non-drug or drug transport is difficult to determine. 

There are 22 annotations to this term (all EXP): https://github.com/geneontology/go-annotation/issues/2302

by the following groups: 

Group | Number of annotations
-- | --
CACAO | 1 @sandyl27 
CGD | 2 @marekskrzypek 
EcoCyc | 9 @keseler
JCVI | 5 (not editable - not in UniProt)
PseudoCAP | 2 @glwinsor 
Reactome | 1 @deustp01 

We suggest that proteins be reannotated to 'GO:0015299 solute:proton antiporter activity' with 'has input' and the appropriate ChEBI term. 

There are 2 Reactome mappings: 
    R-HSA-597628 
    R-HSA-434650

This term is not in any slim. 

Any comments can be added to the issue: #https://github.com/geneontology/go-ontology/issues/17081
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on April 3rd. Unless objections are received by April 3rd, we will assume that you agree to this change.

Thanks, Pascale

**Comment by sandyl27** [comment]
fixed CACAO
