### ISSUE TITLE
Change label 'GO:1990961 drug transmembrane export' to 'xenobiotic detoxification by transmembrane export across the plasma membrane'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17087]
Dear all,

As part of a bigger ticket to obsolete drug transmembrane transporter #16962 (but to keep 'xenobiotic transport'), I will change the term label of 'GO:1990961 drug transmembrane export' to 'xenobiotic detoxification by transmembrane export across the plasma membrane', and move the term under 'detoxification' - the rationale being that a compound is a xenobiotic only in the organism that does not make it. So, to annotate export say of penicilin in the fungus that makes it, we should simply use the term 'export across plasma membrane' . 

There is a single direct annotation by PomBase @ValWood 

Thanks, Pascale

**Comment by cmungall** [comment]
I noticed you changed to logical axioms to

```
is_a: GO:0098754 ! detoxification
relationship: has_part GO:0055085 ! transmembrane transport
```

So genes will not be returned in transport queries, or transmembrane transport queries

in this case
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC18B5.01c

the pombase gene will be returned thanks to IBAs, but it should be returned from the original TAS which is a survey of transporters:

http://amigo.geneontology.org/amigo/reference/PMID:16849797

I think in cases like this it is safer to obsolete than to change the semantics

**Comment by cmungall** [comment]
Note there is also an RGD direct annotation to the regulation term
http://amigo.geneontology.org/amigo/gene_product/RGD:3112

(note there are also direct annotations to 'drug export')

This paper
http://amigo.geneontology.org/amigo/reference/PMID:15198509

Looking at the abstract, I am not sure why a regulation term was used. I think this is a transmembrane transporter involved in xenobiotic toxification

**Comment by pgaudet** [comment]
> So genes will not be returned in transport queries, or transmembrane transport queries

I thought we were soon changing the inference rules and that they *would* be returned - isn't is the case ? Otherwise I'll edit the subclasses. 

I did open a ticket for the RGD annotation https://github.com/geneontology/go-annotation/issues/2303

**Comment by cmungall** [comment]
I suggest a new axiom for this class:

`equivalentTo 'export across plasma membrane' and part_of some detoxification`

**Comment by pgaudet** [comment]
Added 
'export across plasma membrane'
and 'part of' some detoxification
and exports some xenobiotic

**Comment by cmungall** [comment]
great!

Re: inference rules, that is only for enables (MF)

**Comment by ukemi** [comment]
Note that we have toxin transport as well. Are all xenobiotics toxins?

**Comment by ValWood** [comment]
No remember we need to distinguish "toxin" from "toxic". We had a long discussion about this once. Somewhere...
