### ISSUE TITLE
Should GO:0047396 be a child of GO:0046423??

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17092]
Can somebody more knowledgable than I check if "glycosylphosphatidylinositol diacylglycerol-lyase activity (GO:0047396)" should really be a child of "allene-oxide cyclase activity" (GO:0046423).
On the face of it, and checking info in the xrefs at Rhea/MetaCyc/citations, that relationship doesn't seem to make sense - means that "glycosylphosphatidylinositol diacylglycerol-lyase activity" ends up being a great-grandchild of "isomerase activity".

[Term]
id: GO:0047396
name: glycosylphosphatidylinositol diacylglycerol-lyase activity
namespace: molecular_function
def: "Catalysis of the reaction: 6-(alpha-D-glucosaminyl)-1-phosphatidyl-1D-myo-inositol = 1,2-diacyl-sn-glycerol + 6-(alpha-D-glucosaminyl)-1D-myo-inositol 1,2-cyclic phosphate." [EC:4.6.1.14, MetaCyc:3.1.4.47-RXN]
synonym: "(glycosyl)phosphatidylinositol-specific phospholipase C activity" EXACT [EC:4.6.1.14]
synonym: "6-(alpha-D-glucosaminyl)-1-phosphatidyl-1D-myo-inositol diacyl-sn-glycerol-lyase [6-(alpha-D-glucosaminyl)-1D-myo-inositol 1,2-cyclic phosphate-forming]" RELATED [EC:4.6.1.14]
synonym: "6-(alpha-D-glucosaminyl)-1-phosphatidyl-1D-myo-inositol diacylglycerol-lyase (1,2-cyclic-phosphate-forming) activity" EXACT [EC:4.6.1.14]
synonym: "glycosyl inositol phospholipid anchor-hydrolyzing enzyme activity" EXACT [EC:4.6.1.14]
synonym: "glycosylphosphatidylinositol-phospholipase C activity" NARROW [EC:4.6.1.14]
synonym: "glycosylphosphatidylinositol-specific phospholipase C activity" EXACT [EC:4.6.1.14]
synonym: "GPI-PLC activity" EXACT [EC:4.6.1.14]
synonym: "GPI-specific phospholipase C activity" EXACT [EC:4.6.1.14]
synonym: "variant-surface-glycoprotein phospholipase C activity" EXACT []
synonym: "VSG-lipase activity" EXACT [EC:4.6.1.14]
xref: EC:4.6.1.14
xref: MetaCyc:3.1.4.47-RXN
xref: RHEA:14333
is_a: GO:0016849 ! phosphorus-oxygen lyase activity
is_a: GO:0046423 ! allene-oxide cyclase activity

[Term]
id: GO:0046423
name: allene-oxide cyclase activity
namespace: molecular_function
def: "Catalysis of the reaction: (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate = (15Z)-12-oxophyto-10,15-dienoate." [EC:5.3.99.6, RHEA:22592]
synonym: "(9Z)-(13S)-12,13-epoxyoctadeca-9,11,15-trienoate isomerase (cyclizing)" EXACT [EC:5.3.99.6]
xref: EC:5.3.99.6
xref: KEGG:R03402
xref: MetaCyc:ALLENE-OXIDE-CYCLASE-RXN
xref: RHEA:22592
is_a: GO:0009975 ! cyclase activity
is_a: GO:0016860 ! intramolecular oxidoreductase activity

**Comment by ValWood** [comment]
I think this might be resolved? Close?

**Comment by ValWood** [comment]
@sjm41

**Comment by hdrabkin** [comment]
removed is_a: GO:0046423 ! allene-oxide cyclase activity Already done; closing

**Comment by sjm41** [comment]
Thanks for checking @ValWood. Thanks for fixing @hdrabkin
