### ISSUE TITLE
mRNA cleavage, missing mRNA metabolism parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17093]
see
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006379

**Comment by ValWood** [comment]
Also, although I can see it in Quickgo,
positive regulation of mitochondrial translation is no longer slimming to mitochondiral translation
could you check that too

**Comment by pgaudet** [comment]
Some relation was deleted  on 2019-02-28 | Deleted | RELATION | is a GO:0016071 (mRNA metabolic process)

The only ticket (PR) I see that seems to relate to this is 
https://github.com/geneontology/go-ontology/commit/d31f903febd24edbd90779e25eb55c9eb52bdb34
@ukemi

**Comment by ukemi** [comment]
Mitochondrial translation is still defined as a process that regulates some mitochondrial translation. So as long as you are slimming over regulates, this should still slim. 

mRNA cleavage will be fixed with this edit.
