### ISSUE TITLE
NTR: flowering

### ISSUE THREAD

**Issue by Zoe-13** [geneontology/go-ontology#17106]
Flowering 
Definition- A change from the vegetative to the reproductive phase.
Aspect: Biological process
Relationships: parent is GO:0022414, reproductive process. GO:00448573, photoperiodism, flowering becomes child of new term
Reference: PMID: 23899645
Synonyms: blooming, blossoming
This is for CACAO class: @sandyl27 @jrr-cpt @jimhu-tamu

**Comment by tberardini** [comment]
This term already exists, please use GO:0010228.

http://amigo.geneontology.org/amigo/term/GO:0010228

**Comment by pgaudet** [comment]
Should we add a synonym ?

**Comment by tberardini** [comment]
It's already there.

Accession
    GO:0010228
Name
    vegetative to reproductive phase transition of meristem
Ontology
    biological_process
Synonyms
    transition from vegetative to reproductive phase, floral evocation, **flowering**

**Comment by tberardini** [comment]
I don't think 'blossoming' or 'blooming' is a synonym for the biological process 'flowering'.  That's more like a stage of flower development, when the flower opens.  If you really stretch it, I guess it could be a 'related' synonym.  Consider http://amigo.geneontology.org/amigo/term/PO:0007616, the PO developmental stage term, 'flowering stage'.
