### ISSUE TITLE
propose obsolete chaperone-mediated protein transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17117]
GO:0072321   chaperone-mediated protein transport

This is compounding a function and a process. The term is unclear anyway. It has been used to annotate things upsteam of nucleocytoplasmic transport.
I'm not sure that any transport is really chaperone -mediated? chaperones only participate, they don't mediate?

**Comment by ValWood** [comment]
Actually it has 19 annotations, mainly bacterial (only a few human, rat)
But  maybe there is a bacterial process that should be  described this way (but doubtful considering the activity of a chaperone is not to transport?)

**Comment by mah11** [comment]
What would you use instead to annotate the process described in the paper cited for the def? Diagram in figure 1 ...

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2873164/

**Comment by ValWood** [comment]
GO:0051205    protein insertion into membrane

so 
chaperone activity part_of GO:0051205    protein insertion into membrane
A chaperone is  stopping misfolding/aggregation during insertion.

If it is doing both insertion and chaperoning it would also  have
GO:0032977    membrane insertase activity

**Comment by ValWood** [comment]
So lots of processes are chaperone-mediated in that a chaperone (or multiple chaperones are involved). Ribosome assembly, nucleosome assembly, many transport processes. It's just one part of the process though...it seems odd to say "chaperone-mediated"  for a process every time a chaperone is involved.

**Comment by ValWood** [comment]
ping...

**Comment by ValWood** [comment]
Actually, you dealt with it already in the newer ticket so this is now a duplicate...closing.
https://github.com/geneontology/go-annotation/issues/3622

**Comment by pgaudet** [comment]
thanks !
