### ISSUE TITLE
Obsolete 'voltage-gated sulfate antiporter activity'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17122]
Hello, 

The term 'voltage-gated sulfate antiporter activity' was created by @mah11, with one of its synonyms = prestin. Despite its similarity to transporters, it looks like prestin is **not** a transporter, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4061261/

> Unlike its paralogs, which are capable of transporting anions across the cell membrane, prestin primarily functions as a motor protein with unique capability of performing direct and reciprocal electromechanical conversion on microsecond time scale. 

See also Section 5.4 of the same paper. 

Two other points: 
- if it is a transporter, it would transport Cl−/HCO3− (according to the same review)
- the voltage-gated function is the motor activity, not the transporter activity (see also PMID:19383462). 

Since the term incorrectly describes the function of prestin, I propose to obsolete it. 

There are no annotations, no mappings, to this term. This term is not in any slim. 

Thanks, Pascale

**Comment by mah11** [comment]
> 'voltage-gated sulfate antiporter activity' was created by @mah11

I did not create this term.

**Comment by pgaudet** [comment]
oups ! sorry then !

**Comment by pgaudet** [comment]
Email sent April 4th 
Dear all, 

The proposal has been made to obsolete 'GO:0046609 voltage-gated sulfate antiporter activity’. The reason for obsoletion is that there is no evidence that this function exists. 

There are no annotations, no mappings to this term. This term is not in any subsets (slims). 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17122. 
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on April 8th, 2019.
Unless objections are received by April 8th, 2019, we will assume that you agree to this change.

Thanks, Pascale
