### ISSUE TITLE
Logical definition inorganic phosphate transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17120]
Hello, 

Working on the antiporters, I realized that ChEBI 'inorganic phosphate' does not map up to an anion. I think we should be using 'phosphate ion'. 

Example usage:     GO:0015315  organophosphate:inorganic phosphate antiporter activity
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P57057

If this seems OK I will replace  'inorganic phosphate'  to  'phosphate ion' for all transporters mentioning inorganic phosphate (Pi). 

@hdrabkin @amorgat Does that seem OK to you ? 

Thanks, Pascale

**Comment by amorgat** [comment]
@pgaudet fine with me
