### ISSUE TITLE
Add new EC classes to go GO

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#17127]
Schema here excerpted from https://iubmb.org/wp-content/uploads/sites/2790/2018/10/Translocases-EC-7.pdf
I need these because as I go through the rhea mapping, transporters are being remapped from various EC id to children of EC:7
Translocases (EC 7): A new EC Class     This will be a child of catalytic activity
These enzymes are classified under a new EC class of translocases (EC 7). The reactions catalyzed are designated as transfers from ‘side 1’ to ‘side 2’ because the designations ‘in’ and ‘out’   (or ‘cis’ and ‘trans’), which had been used previously, lack clarity and can be ambiguous. The comments associated with each entry then describe the specific translocations catalyzed. 
EC:7. Catalysis the movement of ions or molecules across membranes or their separation within membranes.
The subclasses designate the types of ion or molecule translocated:
EC 7.1 Catalysis of the translocation of hydrons (hydron being the general name for H+ in its natural abundance).
EC 7.2 Catalysis of the translocation of inorganic cations and their chelates.
EC 7.3 Catalysis of the  translocation of inorganic anions
EC 7.4 Catalysis of the translocation of amino acids and peptides.
EC 7.5 Catalysis of the translocation of carbohydrates and their derivatives.
EC 7.6 Catalysis of the translocation of other compounds not included in EC:7.1 through EC:7.5	.

The subsubclasses concern the reaction that provided the driving force for the translocation, where  these are relevant:
EC 7.x.1 translocations linked to oxidoreductase reactions
 example 7.1.1 translocation of inorganic cations and their chelates linked to oxidoreductase reactions
and so on.
EC 7.x.2 translocations linked to the hydrolysis of a nucleoside triphosphate
EC 7.x .3 translocations linked to the hydrolysis of a diphosphate
EC 7.x.4 translocations linked to a decarboxylation reaction
Exchange transporters that are not dependent on enzyme catalysed reactions, such as the exchange of ions across membranes, are not included and pores that change conformation between open and closed states in response to phosphorylation or some other catalysed reaction are classified under EC 5.6 (Macromolecular conformational isomerases). class).

If there are no objections I will add the 7.1 through 7.6 asap.

**Comment by hdrabkin** [comment]
Will use http://www.enzyme-database.org/ as a general reference
This link
http://www.enzyme-database.org/news.php
announces  EC 7 and repeats the above descriptions, but is only a 'recent news" page that will most likely change.

**Comment by hdrabkin** [comment]
I added the 2 digit children today. 
We have a lot of ATPase coupled transporters, so may need to add this class
EC 7.x.2 translocations linked to the hydrolysis of a nucleoside triphosphate where X is 1 though 5.
Example GO:0043225 ATPase-coupled anion transmembrane transporter activity
might need eventual parent of 
EC 7.3.2  Catalysis of the translocation of inorganic anions coupled to ATP hydrolysis

**Comment by hdrabkin** [comment]
Added 7.1.1, 7.1.2, 7.1.3, and 7.1.4 on 5-7-2019

**Comment by hdrabkin** [comment]
Added 7.2.1, 7.2.2, 7.2.3, and 7.2.4 on 5-8-2019

**Comment by hdrabkin** [comment]
Added 7.5.1, 7.5.2, 7.5.3, and 7.5.4
Obsoleted 7.6 as being a bad class name; children of this class should be children of translocase activity (EC:7)

**Comment by hdrabkin** [comment]
Since the 7.6 term is not used by anything else at all, I see no reason to wait; I shouldn't have put it in last week.

**Comment by pgaudet** [comment]
Hi @hdrabkin 
I wish we had coordinated on this. I didn't realize you were going to copy the whole EC hierachy in GO - is this absolutely necessary? 

For example 'translocase activity', defined as 'Catalysis the movement of ions or molecules across membranes or their separation within membranes.' , mixes what I had put as transmembrane transporter activity and intra/intermembrane activity. 
These new terms are not even under 'transporter activity', which means we now have a separate 'transporter activity' under catalytic activity (but not named as such). 

This is the structure I was trying to build (and I was slowing seeing where the lipid transporters could go): 

<img width="369" alt="image" src="https://user-images.githubusercontent.com/4782928/57474678-ef793300-7292-11e9-866f-27795b20ab23.png">


Can we discuss how we want to build this ? 

Also pinging @thomaspd since we discussed together how to model these as part of MF refactoring.

Thanks, Pascale

**Comment by pgaudet** [comment]
I thought you were just going to replace the ECs that had been moved.

**Comment by hdrabkin** [comment]
I did this because of the new ECs, at least for the pz terms, often mapped to the old EC class above it (ie, if xref was  EC:3.6.3.21 the term had a parent of EC:3.6.3 or EC:3.6 (which we have grouping terms for.).  Note we have other EC grouping terms and these can group by mechanism; 


--

**Comment by pgaudet** [comment]
But why do we need a separate branch in the ontology ? 
And do we really need the top level terms ? The xref is to the home page of the enzyme database (http://www.enzyme-database.org/), it's not clear where you got the definitions from, and of there are enzymes with these activities. 
- For example EC7 could be a synonym of 'transporter activity' (ie transporter activity by an undefined mechanism)
- Do you have examples of proteins that do 'translocase activity acting on amino acids and peptides linked to a decarboxylation reaction' ? 

Thanks again, 
Pascale

**Comment by pgaudet** [comment]
PS: I thought we were not adding partial ECs anymore - I guess I misunderstood ?

**Comment by hdrabkin** [comment]
I canceled my build
The partials are for grouping purposes and they are already there for EC1 through 6. 
If Peifeng used one of those in there parentage and the EC changed to a EC7, then the parentage would now be wrong; Thus I thought to supply. The URL for the def ref is explained (the announcement url

**Comment by ValWood** [comment]
>PS: I thought we were not adding partial ECs anymore - I guess I misunderstood ?

I thought so too. Only full ECs. Also, at ISB (or the GO meeting?  somebody said that  even aligning EC with Rhea was problematic and that EC isn't actively maintained. My understanding was that over time it would probably wane away (nobody explictly said that....but it seems inevitable)

**Comment by deustp01** [comment]
There certainly were concerns about the future of EC discussed in April 2019. But if EC becomes static, its higher-level (partial) terms are the most durable ones: oxidoreductase activity seems unlikely to be deprecated or re-conceived. And I thought that partial EC numbers are appropriate cross-references for grouping (higher-level) terms within the catalyst activity part of the GO molecular function ontology, but not for leaf terms. It's hard to be confident that we'll never need to annotate the assertion that a gene product mediates a reaction whose mechanism has not yet been fully worked out so only a grouping term is accurate, given the limitations of the data.

**Comment by cmungall** [comment]
Agree with Peter.

RHEA xrefs are equivalents
We make EC xrefs to leaf (4 digit EC) and non-leaf, but we don't guarantee
equivalence, just best match. We will get leaf xrefs from RHEA

**Comment by hdrabkin** [comment]
After discussion will @pgaudet, I am obsoleting the terms associated with the class 7 ECs. I made them anticipating a problem that may not exist because of alterations in the transporter structure. The worry came knowing that a lot of the terms added in the Plant Enzyme addition had grouping terms that mapped to EC 3 or 2 digit ids as parents, and that if those terms had a 4 digit EC that now was a EC 7 class, the is_a parent term using a grouping term would need a replacement. 

An example of my concern

GO:0102023 vitamin B12 ABC transporter activity had EC 3.6.3.33 as Xref.
We have a grouping term
GO:0016820 hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances, which cross-references  EC:3.6.3


The original stanza for GO:0102023 from the request used  GO:0016820 as the is_a parent.
So now EC:3.6.33 is remapped to EC:7.6.2.8
Obviously GO:0016820 is no longer valid. 
BUT, apparently, @pgaudet removed that Is_a and replaced it with a logical def. 

Same for GO:0102025 ATPase-coupled thiosulfate transmembrane transporter activity
is_a GO:0016820 ! hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances
xref: EC:3.6.3.25
EC changed to EC:7.3.2.3
Would now need is_a to (EC:7.3.2), GO:0106196
However, GO:0102025  no longer has GO:0016820 as a parent; so no problem. 

(remember the bulk of the Plant Enzyme terms came in from a more or less bulk load, so the parentage was NOT looked at for terms that did not raise any other flags

Again, I will remove the class 7 so no one will start using them and cause more harm


--

**Comment by hdrabkin** [comment]
Ok, these are all gone now. Can  I close this now?

**Comment by pgaudet** [comment]
yes you can close.

WRT 
GO:0102025 ATPase-coupled thiosulfate transmembrane transporter activity
and 
GO:0102023 vitamin B12 ABC transporter activity 
we have decided that these will have 'has part' ATPase, and not 'is a' hydrolase. So in GO we cannot have these is_a relations. Is that OK for the Plant Enzymes? 

Thanks again for your help on this, 

Pascale

**Comment by hdrabkin** [comment]
I don't think the parentage was a big issue since the low-level grouping terms were often used. What is more important for these is that when a RHEA is added and used as the official definition, that the Metacyc id is still valid (since the whole point of the project was to align the Metacyc/plantcyc ids with GO.
