### ISSUE TITLE
Obsoletion proposal 'GO:0034437 glycoprotein transporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17130]
Hello, 

The proposal has been made to obsolete 'GO:0034437 glycoprotein transporter activity'. The reason for obsoletion is that it is not clear that this function exists. Glycoproteins are transported via the secretory pathway. 

There are 3 EXP and 1 ISS annotations to this function  (see https://github.com/geneontology/go-annotation/issues/2316). 

There are no mappings to this term; this term is not in any subsets (slims).

Any comments can be  added to the issue: 
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on April 16th, 2019.
Unless objections are received by April 16th, 2019, we will assume that you agree to this change.

Thanks, Pascale

**Comment by hdrabkin** [comment]
Is a glycoprotein considered a carbohydrate derivative?
Looks like CHEBI says yes
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17089

EC 7.5 Catalysis of the translocation of carbohydrates and their derivatives.
Note EC 7 defined as as transfers from ‘side 1’ to ‘side 2’ because the designations ‘in’ and ‘out’ (or ‘cis’ and ‘trans’),
Enzymes already listed as children include
7.5.2.1      ABC-type maltose transporter
7.5.2.2      ABC-type oligosaccharide transporter
7.5.2.3      ABC-type beta-glucan transporter
7.5.2.4      ABC-type teichoic-acid transporter
7.5.2.5      ABC-type lipopolysaccharide transporter
7.5.2.6      ABC-type lipid A-core oligosaccharide transporter

**Comment by ValWood** [comment]
I would say that a  glycoprotein has_part carbohydrate derivative, but  it isn't one...

**Comment by hdrabkin** [comment]
We need to get CHEBI's input on this before deleting this term.

**Comment by deustp01** [comment]
My impression from previous similar discussions is that ChEBI either does not use the has_part relationship at all or uses it differently and that, to ChEBI, a covalent structure with sub-parts that are derivatives of chemical classes A, and B, and C is said by ChEBI to be is_a A derivative AND is_a B derivative AND is_a C derivative.

**Comment by hdrabkin** [comment]
They did use has something like 'has functional parent' or something like that; we had to get them to change nucletide, etc. because we were getting is_a carbohydrate because of the sugar, etc.

**Comment by ValWood** [comment]
Hi @hdrabkin but why do we need CHEBi's input for the obsoletion. How CHEBI defined glycoprotein is a separate issue from whether "glycoprotein transporter activity" exists?

**Comment by hdrabkin** [comment]
Are we very certain that in no case do is there a transport of a glycoprotein across a membrane not involving a vesicle?

**Comment by hdrabkin** [comment]
I was looking at this
https://www.pnas.org/content/110/26/10860
Transport of glycoprotein into a plastid

**Comment by hdrabkin** [comment]
@tberardini can you comment?

**Comment by deustp01** [comment]
Plastids: question out of ignorance - do any glycoproteins enter mitochondria via the TIM / TOM machinery?

**Comment by tberardini** [comment]
Found this more recent (2016) paper: [Golgi-to-plastid trafficking of proteins through secretory pathway: Insights into vesicle-mediated import toward the plastids]( https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5058459/)  Looks like the TIC/TOC machinery is not used.  Three possible models for transport via secretory vesicles are presented.

**Comment by hdrabkin** [comment]
OK, so then we ARE sure that we can get rid of this term? If so then fine by me.

**Comment by deustp01** [comment]
The Midori model that GO terms are not created comprehensively but only as much as is needed to annotate known features of known proteins probably applies here, with the bonus that there's a good template available if a glycoprotein transporter is discovered.

**Comment by tberardini** [comment]
Can we codify 'the Midori model'?

**Comment by ValWood** [comment]
Yes the "Midori model" makes things much less confusing. We appreciate it very much in FYPO. Don't add anything unless you have an observation.

This area is interesting area of biology  because of  the (relatively) new work on connections and contact points between the  nuclear lumen ER and mitochondria. I suspect a lot of  'unknown' biology is in here...

**Comment by RLovering** [comment]
Hi I would like to have more than a week to revise this annotation. I still have several others to look at from other tickets and I am in Cambridge for 7 days at meetings this week so it will be very challenging to find the time to look at all of the revisions requested before the 16th
Thanks

Ruth

**Comment by pgaudet** [comment]
No problem @RLovering 
Let me know when you're done looking at this. 

Thanks, Pascale

**Comment by RLovering** [comment]
thanks I am done with this, happy with the term being obsoleted

**Comment by pgaudet** [comment]
Actually this term has one Reactome mapping: reactome:R-HSA-1022127
@deustp01

**Comment by pgaudet** [comment]
DERL2 UniProt entry states "May act by forming a channel that allows the retrotranslocation of misfolded glycoproteins into the cytosol where they are ubiquitinated and degraded by the proteasome. "

If this is the case I can change the label and parent of this term to 'glycoprotein transmembrane transporter activity'. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I will not obsolete. see #17149

**Comment by RLovering** [comment]
Hi
sorry to reopen but wasn't there was a comment a few years ago about protein binding when people used 'glycoprotein binding' and it was not necessarily shown that the protein bound was glycosylated, but it was known to be a glycoprotein. Is it really necessary and appropriate to have this specificity? Are you going to also have phosphorylated protein transporter activity too?

It seems like the key thing here might be that it is a misfolded protein? Or does it only transport glycoproteins?

See PMID:23867461 Abstract statement: Our study is the first to report that derlin2 functions with HRD1 in ERAD of certain substrates independent of their glycosylation status.

**Comment by pgaudet** [comment]
Hello, 

Looking at this review: PMID:28985557, it looks like the transport is not glycoprotein-specific, but rather transports misfolded proteins, so I will go ahead with the obsoletion. 

Pascale
