### ISSUE TITLE
negative regulation of protein localization to plasma membrane of medial cortex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17156]
ntr :negative regulation of protein localization to plasma membrane of medial cortex

standard def

descendant of
GO:1903077 | negative regulation of protein localization to plasma membrane
and
GO:0106011    regulation of protein localization to medial cortex (needs a -ve reg term)

Ref: PMID:30853434
Title | NDR Kinase Sid2 Drives Anillin-like Mid1 from the Membrane to Promote Cytokinesis and Medial Division Site Placement.

(another way to do this would be some sort of MF 'dissociation factor', it is basically phosphorylation antagonising the "recruitment"- actually, this would be somewhat better, but it would be an additional MF for the protein kinase)

**Comment by ValWood** [comment]
It's the "inhibition of binding" which often comes up. Does anyone have a LEGO model where they have sone this? @ukemi @vanaukenk ?

**Comment by pgaudet** [comment]
Isn't this some kind of sequestering ?

**Comment by ValWood** [comment]
Not really. Its really (usually)  about breaking down components after use to recycle the components.

It's really hard to describe this activity. I had the same issue with cohesion, in trying to describe the menchism of "cohesin ring opening" (the binding of the gate to close the ring is inhibited).

This is (usually) to describe a molecule that makes a modification  that prevents two other molecules binding. 
Sequestering is different.

There isn't  a huge hurry for this, I  know the examples I have so far and I can retrofit. It would be useful to see how others have done these...

**Comment by pgaudet** [comment]
To create this term, I think I also need to create: 
- medial cortex plasma membrane
and 
- protein localization to medial cortex plasma membrane

@ValWood OK ? I suppose I can cite the same paper.

**Comment by pgaudet** [comment]
Is 'GO:0032178 medial membrane band' the same as 'medial cortex plasma membrane' ?

**Comment by ValWood** [comment]
Actually, I am not sure that this request makes sense! because cortex and PM are disjoint.

perhaps I should just do:
ntr :negative regulation of protein localization to  medial cortex?

in which case I only need this regulation term

**Comment by pgaudet** [comment]
Sure. And just to be sure: there is no relation to 'GO:0032178 medial membrane band' ?

**Comment by ValWood** [comment]
> Is 'GO:0032178 medial membrane band' the same as 'medial cortex plasma membrane' ?

yes this would be equivalent.

The problem I have is:
medial cortex is the "cortex" underlying the plasma membrane.

This protein is in the medial cortex (It is the very first protein in the cortical  nodes that precede the formation of the cytokinetic ring). And it is attatched to the plasma membrane. So it is simultaneously part of the 

GO:0032178    medial membrane band
GO:0098753    anchored component of the cytoplasmic side of the plasma membrane
GO:0031097    medial cortex
A medial cortical band overlaying the nucleus which acts as a landmark for contractile ring positioning and plays a role in cell cycle regulation. PMID:15572668 PMID:19474789

I  don't need to include plasma membrane, in fact the resolution of the experiment only shows conrtical mislocalization  so this works.
But  this is a general issue for annotation consistency.

**Comment by pgaudet** [comment]
I am creating the term - I dont know what to recommend for the annotation consistency problem.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140325
+name: negative regulation of protein localization to medial cortex
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of protein localization to the medial cortex." [PMID:30853434]
+is_a: GO:1903077 ! negative regulation of protein localization to plasma membrane
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0071574 ! protein localization to medial cortex
+created_by: pg
+creation_date: 2019-04-17T11:58:27Z
+

**Comment by ValWood** [comment]
Great thanks, this works...
