### ISSUE TITLE
GO:0140132 | iron-sulfur cluster carrier activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#17151]
GO:0140132 | iron-sulfur cluster carrier activity

should have parent 

GO:0051536 | iron-sulfur cluster binding?

**Comment by pgaudet** [comment]
'has part' would be the correct relation.

**Comment by krchristie** [comment]
I added the has_part relationship @pgaudet  indicated between the two terms:
iron-sulfur cluster carrier activity (GO:0140132)
_has_part_ iron-sulfur cluster binding (GO:0051536)
