### ISSUE TITLE
Obsoletion notice: GO:0033570 transferrin transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17157]
Dear all, 

The proposal has been made to obsolete 'GO:0033570 transferrin transmembrane transporter activity'. The reason for obsoletion is that this function does not exist: 
- Eukaryotes/animals' transferrin binds iron in the blood, and is uptaken by the cell by endocytosis. This activity is represented by 'GO:0004998 transferrin receptor activity' 
- Bacteria can scavenge the iron from the transferrin molecule, but only transports iron, not the transferrin-iron complex. 

There are no manual annotations to this term. 
There is a single InterPro mapping to InterPro:IPR037324, which should be annotated to  'GO:0004998 transferrin receptor activity'  @happy-lorna 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17157. 
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on April 23rd, 2019.
Unless objections are received by April 23rd, 2019, we will assume that you agree to this change.

Thanks, Pascale

**Comment by happy-lorna** [comment]
I have updated the IPR037324 annotation. It will be visible in our next release.

**Comment by pgaudet** [comment]
Thanks!
