### ISSUE TITLE
Get rfam2go from rfam site

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#17153]
See also #16989 

Talking with Rob and Lorna, they previously pushed to svn but we are moving away from svn. I am coordinating with the Rfam team on location for new deposit on ftp

**Comment by alexsign** [comment]
@cmungall I see that rfam2go already disappear from
http://www.geneontology.org/external2go/rfam2go
can I please have it back till you finish with the new pipeline or have a new location in case it was moved.

**Comment by cmungall** [comment]
You can grab from here for now: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/external2go/

**Comment by AntonPetrov** [comment]
@kalvari and I will aim to deploy the rfam2go file and an md5 checksum on Rfam FTP in the week of April 29th. We will update this issue when everything is ready.

**Comment by kalvari** [comment]
@cmungall The `rfam2go` and the `md5` checksum are now ready for you on the [Rfam FTP](http://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/rfam2go/)

Let us know if you have any questions or suggestions for improvements.

**Comment by pgaudet** [comment]
Changed in the Makefile.
