### ISSUE TITLE
septation initiation signalling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17154]
I think we should remove the "regulation of process" parentage from this term, and make the annotations post composed. Although this pathway does regulate septation, ring constriction etc, it would be better to connect these via downstream targets.

ALso the pathway branches so removing these parents will ensure we haven't hard-coded  things from one branch to another.

Later on I will specify the core pathway more clearly (beginning and end)

How it looks:
![SIN](https://user-images.githubusercontent.com/7359272/56123390-46c60500-5f6c-11e9-9bce-3cfce8093746.jpg)

**Comment by ValWood** [comment]
I should add that I requested these parents when we hard-coded more in the ontology.

**Comment by ValWood** [comment]
The septation initiation network (SIN), analogous to the Hippo pathway of multicellular organisms, is a signaling cascade that triggers node dispersal, CR assembly and constriction, and septum formation [4, 5].
PMID:30853434

**Comment by pgaudet** [comment]
Shouldn't this be in the annotation tracker ?

**Comment by ValWood** [comment]
No I wanted to remove some ancestors (we don't seem to hard code these to signalling pathways?)

**Comment by pgaudet** [comment]
So, you only want to keep 'Ras protein signal transduction' as a parent ? 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/4782928/56135065-3fb0ee00-5f90-11e9-9ea6-03ae67af46f1.png">

**Comment by ValWood** [comment]
Yes. Maybe you can check this with @ukemi 


I thought these parents were being removed but
https://www.ebi.ac.uk/QuickGO/term/GO:0071507
has them for the connection to the "regulation of conjugation".

I looked at Hippo signaling and it didn't have any regulation terms associated.

So now I'm not sure what was decided? 
This would  prevent the "regulation of regulation cycles....."
but perhaps there is another way to do this?

So this is part of the problem with enrichment.
Some pathways regulate the SIN.
SIN regulates cytokinesis. 
Our users expect to see the SIN annotated to cytokinesis (I can demonstrate this, the kinases are intimately associated with the cytokinetic ring and regulate many steps in the process), BUT they wouldn't necessarily expect the pathways regulating the SIN to have this annotation.

**Comment by ukemi** [comment]
This is analagous to the discussion we had on yesterdays editors' call. If the relationship does not hold universally, we cannot make a class-based relationship.

**Comment by vanaukenk** [comment]
@ValWood -  to summarize the action needed here:

1. Remove the four is_a regulation parent term relationships from GO:0031028 'septation initiation signaling'.

2. Keep the sole is_a parent to GO:0007265 'Ras protein signal transduction'.

3. The only remaining inherited regulation parent will be GO:0050794 'regulation of cellular process'.

Please confirm.  Thx!

**Comment by ValWood** [comment]
Well all are true so maybe it is OK to leave them? I guess this can be encoded in the ontology.

The part of the pathway described as SIN is linear, the forking comes later, so this part does regulate all of these processes.

Just to confirm, the inferences have changed/or are changing recently so that 
regulation of SIN annotations will not become annotated to the processes that the SIN regulates. Is this corrrect? If so it can stay as it is.

v

**Comment by ukemi** [comment]
But are they always true every time the pathway is executed? That's the key for the class relationships. It has to be true for every instance of the class.

**Comment by vanaukenk** [comment]
>Just to confirm, the inferences have changed/or are changing recently so that
>regulation of SIN annotations will not become annotated to the processes that the SIN regulates. Is >this corrrect?

@ValWood @ukemi - can you clarify this?  Are these inferences currently being made?

**Comment by ValWood** [comment]
These are true in every instance as far as I'm aware. These separate processes are all regulated every time the SIN is activated. It's one of those examples where the pathway activates the terminal kinases which has many substrates during cytokinesis and mitotic exit.

My concern about these terms might be resolved by  removing  the property chain inference regulates_o_part-of->regulates (my concern was that  +ve or -ve regulation of the SIN  then become annotated to the processes that SIN regulates, which is a step to far).

Lets close with no action and I can reassess after the changes...
