### ISSUE TITLE
histone H3-K37 methylation

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#17168]
related to #17061, and can cite the same paper (PMID:30773398)

stanza shamelessly copied from GO:0010452 ...

[Term]
id: GO:new
name: histone H3-K37 methylation
namespace: biological_process
def: "The modification of histone H3 by addition of one or more methyl groups to lysine at position 37 of the histone." []
synonym: "histone H3 K37 methylation" EXACT []
synonym: "histone H3K37me" EXACT []
synonym: "histone lysine H3 K37 methylation" EXACT []
is_a: GO:0034968 ! histone lysine methylation

**Comment by hdrabkin** [comment]
GO:0106185
done

**Comment by mah11** [comment]
tyvm :)
