### ISSUE TITLE
Merge 'GO:0097689  iron channel activity' into GO:0005381 iron ion transmembrane transporter activity  (+ related terms)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17162]
Hello, 

I would like to merge 

 - [ ] GO:0097689 iron channel activity -> Merge into GO:0005381 iron ion transmembrane transporter activity 
 - [x] GO:0097690 iron channel inhibitor activity 0 annotations -> change label 'iron ion transmembrane transporter inhibitor activity'
 - [x] GO:1904254 regulation of iron channel activity 0 annotations -> ~Merge into respective regulation term~ (does not exist) -> change label to 'regulation of iron ion transmembrane transporter activity' 
 - [x] GO:1904255 negative regulation of iron channel activity 0 annotations -> ~Merge into respective regulation term~  (does not exist) -> change label to 'negative regulation of iron ion transmembrane transporter activity' 
 - [x] GO:1904256 positive regulation of iron channel activity 0 annotations -> ~Merge into respective regulation term~  (does not exist)  -> change label 'positive regulation of iron ion transmembrane transporter activity' 

There is a single BHF annotation to GO:0097689 iron channel activity @RLovering 

Thanks, Pascale

**Comment by pgaudet** [comment]
+ removed asserted classes to 'transition metal ion transmembrane transporter activity' - let the reasoner figure them out (=no change)

**Comment by RLovering** [comment]
Hi Pascale
what do you want to do with this? Wikipedia has a good summary of Ferroportin https://en.wikipedia.org/wiki/Ferroportin 

It is the only mammalian iron exporter: Ferroportin-1, also known as solute carrier family 40 member 1 (SLC40A1) or iron-regulated transporter 1 (IREG1)

Ruth

**Comment by pgaudet** [comment]
Thanks Ruth. I did do the merge. Can you make sure that the protein is
annotated to the 'export' process? (although I am not sure we have this for
iron, if not please request it )

Thanks, Pascale

Le mer. 17 avr. 2019 à 11:07 PM, Ruth Lovering <notifications@github.com> a
écrit :
