### ISSUE TITLE
NTR: Repression of monocyte activation

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#17161]
@milarolo I have moved this ticket here to the go-ontology tracker, as @pgaudet advised, and closed the issue in the go-annotation tracker (https://github.com/geneontology/go-annotation/issues/2321).
![Screenshot 2019-04-16 at 15 23 51](https://user-images.githubusercontent.com/16541096/56217865-d696ac80-605b-11e9-9445-9bb8ca9c06f3.png)
cc @RLovering

**Comment by BarbaraCzub** [comment]
Hi @milarolo 

If you agree, I will add 'negative regulation of monocyte activation' as the primary GO term, because it will be an 'is_a' child of 'negative regulation of leukocyte activation' (screenshot below), so this will allow to keep the naming conventions consistent. I will add 'repression of monocyte activation' as an exact synonym, if this was the term used in the referenced paper. 
Is this ok?

And could you please let me know what dbxrefs to add? It will be GOC:aruk for the project, and should I add any others?

Thanks,
Barbara

cc @RLovering 

![Screenshot 2019-04-16 at 16 12 46](https://user-images.githubusercontent.com/16541096/56221894-f8476200-6062-11e9-9c5a-d6cf30ba6143.png)

**Comment by milarolo** [comment]
Hi Barbara,

About the new term that I requested "repression of monocyte activation":

I agree with you that "negative regulation of monocyte activation" is better to keep  the naming conventions consistent.

I agree adding "repression of monocyte activation" as an exact synonym of the new term created.

About the dbxref, GOC:aruk would be fine. I don't think you need to add others.

I just have a question about making it a child of "negative regulation of leukocyte activation". I thought it would be better to make it a child of "monocyte activation". Is there a specific reason why you chose that term for the parent?

Thank you for taking care of this,

**Comment by BarbaraCzub** [comment]
Hi Mila,

Thanks for your comments and questions. 

You are correct about making "monocyte activation" a parent of "negative regulation of monocyte activation". It will indeed become an additional parent on this new term, connected to it using the ontology relation 'negatively_regulates'.

Whereas "negative regulation of leukocyte activation" will be the '*is_a*' parent of "negative regulation of monocyte activation". Every term in the ontology needs to have an 'is_a' parent, or else things break, which is why I only mentioned this parent. The parents related to the new term using the '(positively/negatively)_regulates' relationships will be inferred automatically via logical definitions. I hope this answers your question. Please let me know, if you have any other questions.

Thanks,
Barbara

**Comment by milarolo** [comment]
Thank you for your clarification Barbara
Mila
