### ISSUE TITLE
Is it appropriate to name GO:0022900 as "electron transport chain"?

### ISSUE THREAD

**Issue by pengyubio** [geneontology/go-ontology#17172]
The electron transport chain is commonly defined as "a series of protein complexes ..." in literature.

https://www.ncbi.nlm.nih.gov/books/NBK526105/
https://en.wikipedia.org/wiki/Electron_transport_chain

In other words, it is not a process per se. It just enables the process of transporting electrons.

But GO BP defines it as a process ("A process in which a series of electron carriers ...") which is inconsistent with the literature. For this reason, it sounds like it should be renamed to something else that is not in conflict with the commonly accepted definition in the literature.

**Comment by deustp01** [comment]
But two paragraphs on [(https://www.ncbi.nlm.nih.gov/books/NBK526105/)]:

> Oxidative phosphorylation is made up of 2 parts: the electron transport chain (ETC) and chemiosmosis. The ETC is a collection of proteins and organic molecules, which electrons pass through in a series of redox reactions, and release energy. The energy released forms a proton gradient, which is used in chemiosmosis to make a large amount of ATP.

How should we parse this statement? Is it asserting that oxidative phosphorylation is the sum of a process (chemiosmosis) and a supercomplex (the electron transport chain), or two supercomplexes (the ATPase complex and coupled transporter complexes that mediate chemiosmosis plus the electron transport supercomplex), or should we read it as an ordinary-language statement with ordinary-language imprecision as asserting that the overall process has two sub-process parts? Unlike the first two readings, this one looks like a really good fit to the known biology that GO is trying to capture.

**Comment by pengyubio** [comment]
@deustp01 The author clearly used ETC to refer two things in this passage: 1) the process that GO BP refers, 2) the corresponding complex.

When this kind of ambiguity occurs, GO should not just use one of the possible usages. The meaning used in GO of the phrase should be consistent with the common meaning of the phrase in the literature. Based on the PubMed search with the query `"electron transport chain"[tiab]`,  it mostly refers to the complex instead of the process. Using "electron transport chain" to refer to the process will cause confusion when people mostly use it to refer to the complex.

One should also look up the dictionary definition of the root word of the phrase. In this case,`chain` is defined as "a sequence of items of the same type forming a line" in New Oxford American Dictionary. It doesn't have the meaning of `process`, which may explain why its most common usage refers to the complex.

For these reasons, "electron transport chain" is not the best term name. Something more appropriate and less ambiguous is preferred.

**Comment by bmeldal** [comment]
I'm with Peter here :)

Ontology semantics = precise
Human semantics = very ambiguous

ETC: "A process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient."

I think ETC chain = series of components AND processes: 
the processes of multiple redox reactions facilitated by a chain of complexes resulting the establishment of a proton gradient across a membrane
--> overall, what's **meant to be** defined is the series of processes but a chain of complexes is facilitating the process.

Just my 2p...

**Comment by ValWood** [comment]
I agree, I couldn't think of a better label for the precise we are trying to describe here:

definition:
"A process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient."

And since this is a BP term  it shouldn't really be misinterpreted. Labels are ambiguous. Definitions are precise.

**Comment by pengyubio** [comment]
@ValWood @bmeldal Just having a definition is not necessarily always sufficient. Let's put it in another way. If a phrase can mean both a complex and a biological process, it has to be disambiguated. If the molecular complex meaning of ETC were to put in GO, how would you disambiguate the molecular complex ETC term name and the biological process ETC term name?

**Comment by bmeldal** [comment]
As Val said, the definition clearly describes this term as a process. Yes, the title is a little ambiguous in this case and that's why we always remind people to check the definition first. 

Personally, when I hear "ETC" I immediately think of the process, not just the chain of complexes that facilitate the process.

**Comment by ValWood** [comment]
GO:0098803    respiratory chain complex ?

**Comment by ValWood** [comment]
...is the closest component term (for this reason).
The constitutive complexes are clearly defined

**Comment by ukemi** [comment]
Plus the term is a child of biological_process. There are many many cases where a term name is ambiguously used in the community. That is why it is very important to look at the definition of the term and how the term is placed in the ontology. We try to use term names that are used frequently in the community and as @deustp01 points out above, this label is used to describe the process.

**Comment by pengyubio** [comment]
@ValWood So there is not a term for the ETC complex. My question is: if the ETC complex were in GO, how you would disambiguate the names of the term for the complex and the term for the process? Or if there were some other phrase that could mean both a complex and a process, how would the exact phrase be assigned to one of the two terms? I think that it better to make the names consistent with the common usage in the literature, i.e., to assign the phrase to the term for which that is most commonly used in the literature.

@ukemi @bmeldal I think this ambiguity was caused by the overloading of the same phrase. The most commonly accepted definition of "electron transport chain" is still the corresponding complex rather than the process. This can be seen in the widely used textbook Molecular Biology of the Cell (5/ed): "The entire set of proteins in the membrane, together with the small molecules involved in the orderly sequence of electron transfers, is called an electron-transport chain." If such an influential textbook define "electron transport chain" as a complex, why GO would use "electron transport chain" for the less used and overloaded meaning of the ETC process? Having a definition sentence of a term is not a substitution for a good name of the term.

Most of the ambiguous phrases should have a major meaning and one or more minor meanings. So the ambiguity can be resolved by checking which meaning is used most frequently in the literature and using that meaning. With this relatively objective principle, the determination of the ambiguous term name will be very clear. Only when a phrase is equally used for multiple meanings, which should be rare, there might need a discussion.

**Comment by ValWood** [comment]
> My question is: if the ETC complex were in GO, how you would disambiguate the names of the term for the complex and the term for the process? Or if there were some other phrase that could mean both a complex and a process, how would the exact phrase be assigned to one of the two terms?

As I explained above "ETC complex" is not in GO, because it isn't a single complex. There was a long discussion about ETC process vs. component a  but I can't find it. Maybe it was back on the SF tracker.

We would not use the same primary name for 2 terms (although one phrase could be a synonym). But more importantly we do not annotate to term labels, we annotate to the definitions. A curator would need to figure out the meaning and make the correct assignment. Curation isn't text-mining, we are interpreting the data and making the correct selection after reading the definition.

GO:0070469    respirasome Definition
The protein complexes that form the electron transport system (the respiratory chain), associated with a cell membrane, usually the plasma membrane (in prokaryotes) or the inner mitochondrial membrane (on eukaryotes). The respiratory chain complexes transfer electrons from an electron donor to an electron acceptor and are associated with a proton pump to create a transmembrane electrochemical gradient.

has exact synonym "membrane electron transport chain" (but this should probably be related because of the ambiguity)

**Comment by bmeldal** [comment]
@pengyubio 

If you provide a better term name for ETC process that is less ambiguous to the user community we can change that and make ETC a synonym.

Similarly, GO:0070469 respirasome (synonym: membrane electron transport chain) looks like the "ETC complex" you are looking for. Does it need a better name? Looks like the term name got swapped at some point (see 'comment').

You will find GO:0098803 respiratory chain complex as a part_of child of respirasome as they are the constituent parts of the respirasome, while respirasome is a bucket term.

NB: Most complex terms end in 'complex' or "-some" and are disambiguated from their processes that way.

**Comment by ValWood** [comment]
closing. If there is a specific action,  (i.e renaming suggestion idea), open a new ticket and link back to this one for context.
