### ISSUE TITLE
incorrect? inferences for 'dentin secretion'

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17174]
I'm looking at the term 'dentin secretion' with the reasoner on and I see that the reasoner is placing it under 'extracellular transport', which seems incorrect.

The definition of '**extracellular transport**' is what I would expect and seems to me that it indicates that the whole process should occur outside of cells:
> Def:  'The transport of substances that occurs outside cells.'

However, with the reasoner on, I see the term 'dentin secretion' under 'extracellular transport' instead of under 'secretion'.

The term 'extracellular exosome macropinocytosis' also shows up under 'extracellular transport', though it seems that this should really be under 'import into cell'.

**Comment by cmungall** [comment]
If you still have Protege open and the reasoner on, can you post the explanation? Click on the ? where it shows the subClassOf in the description tab. Then do a screencap and post it here.

If you have already closed it, no worries

**Comment by krchristie** [comment]
Here are the 4 explanations for 'dentine secretion'

![20190422-dentinSecretion-expls1-2](https://user-images.githubusercontent.com/10533218/56537674-f4f61f80-6515-11e9-92fb-d175ea846ba4.jpg)

![20190422-dentinSecretion-expls3-4](https://user-images.githubusercontent.com/10533218/56537829-62a24b80-6516-11e9-967b-76836c2711e3.jpg)

**Comment by krchristie** [comment]
Here are the 2 explanations of 'extracellular exosome macropinocytosis' SubClass of 'extracellular transport':

![20190422-exosomeMacropinocytosis-expls1-2](https://user-images.githubusercontent.com/10533218/56537989-be6cd480-6516-11e9-8ffc-65e9abb0e3a9.jpg)

**Comment by ukemi** [comment]
Interesting. Let's look at this at an ontology meeting. There appears to be a flaw in our reasoning with respect to start and end location and where the transported entity normally resides.

**Comment by ukemi** [comment]
problem with

'transports or maintains localization of' o 'part of' SubPropertyOf: 'occurs in'
?

@balhoff

**Comment by pgaudet** [comment]
When I remove 'tissue' has part' some 'extracellular matrix' the incorrect inference goes away. 

Maybe there is a way to fix this within GO but the Uberon subclass seems to be causing problems. 

Pascale

**Comment by ukemi** [comment]
I don't think this is the fundamental issue. I think it is a deeper problem with the logic rules. We also shouldn't modify external ontologies locally.

**Comment by pgaudet** [comment]
I wasn't editing Uberon - I just wanted to see the inferences being made.

**Comment by cmungall** [comment]
Thanks! 

The problem comes down to these axioms:

![image](https://user-images.githubusercontent.com/50745/56787951-ed9f7200-67b2-11e9-9042-2a6d4dedfecc.png)

I think the first is fine: if you transport something you're also transporting its sub-parts

But the second one is wrong - just because you are transporting something doesn't mean you are in that location. E.g if I am carrying a glass of water from one room to another I am not in the glass of water! 

I'll take care of this

**Comment by ukemi** [comment]
Exactly! I talked a bit about this with @balhoff too. In addition, I can endocytose an extracellular vesicle, but that just means the vesicle is the input of the process. It doesn't mean that the process takes place where the input vesicle is located. This also affects the synaptic vesicle question you had a while ago. I think it's exactly the same issue.

**Comment by cmungall** [comment]
Sorry I did that thing again of answering when you had already given the answer, I'm blaming it on github syncing...

Also, top tip: usually only the first explanation is required. Useful to know if Protege is being slow calculating all

**Comment by ukemi** [comment]
No worries! Always good to have confirmation.

**Comment by balhoff** [comment]
I just wanted to connect this ticket to the discussion in #16546, which came up last fall.

**Comment by pgaudet** [comment]
This came up again in https://github.com/geneontology/go-ontology/pull/19739

@ukemi suggested to rename of GO:0070468 to be dentin extracellular matrix secretion and then remove the logical def. Keep the asserted children.
https://github.com/geneontology/go-ontology/pull/19739#issuecomment-672974935

Thanks, Pascale

**Comment by pgaudet** [comment]
I dont see any asserted children (I did keep the asserted parents, 
- is_a 'extracellular matrix constituent secretion'
- 'part of' some 'odontogenesis of dentin-containing tooth'

**Comment by ukemi** [comment]
Sorry, asserted parents.
