### ISSUE TITLE
NTR: mucociliary transport & refinements to 'epithelial cilium movement' terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17181]
I need a new term for 'mucociliary transport'. Here's what I'm thinking for the term:

mucociliary transport
Def: The respiratory system process driven by motile cilia on epithelial cells of the respiratory tract by which mucus and associated inhaled particles and pathogens trapped within it are moved out of the airways. 
Def reference: PMID:27864314; GOC:krc
is_a 'respiratory system process'
is_a 'extracellular transport'

Then, I notice this process, which is related:
'cerebrospinal fluid circulation' (GO:0090660)

I think that this process should also be:
is_a 'extracellular transport'

It might be worth having a grouping term to indicate that these are both extracellular transport processes mediated by cilia. 
- mucociliary transport
- cerebrospinal fluid circulation

**Comment by krchristie** [comment]
Thinking about an appropriate grouping term for these two terms:
- mucociliary transport (proposed)
- cerebrospinal fluid circulation (GO:0090660)

I think we actually already have it:

**epithelial cilium movement (GO:0003351)**
**Current Def**: The directed, self-propelled movement of a cilium of an epithelial cell. This movement is usually coordinated between many epithelial cells, and serves to move fluid.

I propose to alter the name and definition to be a little more clear and to give it additional parentage under 'extracellular transport':

**epithelial cilium movement involved in extracellular fluid movement (GO:0003351)**
**Proposed Def**: The directed, self-propelled movement of cilia of epithelial cells. Depending on the type of cell, there may be one or many cilia per cell. This movement is usually coordinated between many epithelial cells, and serves to move extracellular fluid. 
**is_a**: extracellullar transport (GO:0003351)

This term already has two children, both of which already fit the changes to the definition that I am proposing, so if I 

```
- extracellullar transport (new is_a parent for GO:0003351)
-- epithelial cilium movement involved in extracellular fluid movement (GO:0003351)
--- cerebrospinal fluid circulation (GO:0090660)
--- epithelial cilium movement involved in determination of left/right asymmetry (GO:0060287)
--- cilium movement involved in otolith formation (GO:0003355)
--- mucociliary transport (GO:new)
```

@ukemi and @doughowe - Since one or both of you were involved in most of these existing terms, do you have any suggestions or objections to this proposal?

**Comment by krchristie** [comment]
It would be helpful to add PMID:19043402, used in annotation to the term 'cilium movement involved in otolith formation', to be one of its def dbxrefs.

**Comment by krchristie** [comment]
Good review to use as reference for mucociliary transport term: PMID:27864314
'mucociliary clearance' might be the better main term name, with 'mucociliary transport' as an exact synonym.

**Comment by krchristie** [comment]
Looking at these terms together, I have some suggestions for clarifiying some of the definitions. 

- **epithelial cilium movement**
**Current Def**: The directed, self-propelled movement of a cilium of an epithelial cell. This movement is usually coordinated between many epithelial cells, and serves to move fluid.
**Proposed New Def**: The directed, self-propelled movement of the cilia of epithelial cells, most commonly multiciliated cells. This movement is usually coordinated between many epithelial cells, and serves to move fluid.

- **cilium movement involved in otolith formation**
**Current Def**: The directed, self-propelled movement of a cilium of an inner ear epithelial cell, resulting the aggregation of otolith seed particles.
**Proposed New Def**: The directed, self-propelled movement of cilia of inner ear epithelial cells, resulting the aggregation of otolith seed particles.


- **epithelial cilium movement involved in determination of left/right asymmetry (GO:0060287)**
**Current Def**: The movement of cilia of epithelial cells resulting in the transport of signals which determine asymmetry in an organism's body plan with respect to the left and right halves.
**Proposed New Def**: The movement of cilia of epithelial cells of the Left Right Organizer (LRO), also referred to as the node in mouse or the Kupffer's vesicle in zebrafish, resulting in the leftward fluid flow across the LRO and generation or transport of a signal which determines asymmetry in an organism's body plan with respect to the left and right halves.

I also think it might be good to add a taxon constraint "only in Vertebrata" to this term about determination of left/right asymmetry. It's not completely clear what the mechanism of L/R asymmetry generation is in Drosophila (PMID:18328746), but it is not this one, or anything driven by cilia.

**Comment by ukemi** [comment]
Hi @krchristie you know the biology of cilia better than I. The only issue I see here is that going from the movement of a cilium to the movement of a population of cilia changes the parentage because cilium movement (one cilium) would now have to be a necessary part of the population term. This will have effects on annotation propagation. The other question in my mind would be, will annotators be confused now and not want to annotate to the population term for gene products that are involved in the movement of a specific cilium? Is that appropriate? This kind of annotator confusion could lead to a future proposal for obsoletion.

**Comment by krchristie** [comment]
I think that my new definitions are less likely to cause annotator confusion. The old ones just sounded really weird. I also don't think we need to change the parentage. It's still the movement of individual cilia, but in the context of being in a group of cilia. I thought the older definitions didn't include enough of the context and ended up seeming to suggest that the fluid flow could result as the movement of a single cilium.

**Comment by krchristie** [comment]
One more question @ukemi - Are ependymal cells of the lining of the brain ventricles considered to be a type of epithelial cell? 

from: https://en.wikipedia.org/wiki/Ependyma
Ependyma is the thin neuroepithelial lining of the ventricular system of the brain and the central canal of the spinal cord.

If not, then perhaps the word 'epithelial' should be removed from the name of the term 'epithelial cilium movement involved in extracellular fluid movement'.

**Comment by ukemi** [comment]
We go by CL. They are ciliated epithelial cells.

**Comment by krchristie** [comment]
Awesome. I'll leave the word epithelial in the term name. Thanks for checking for me.
