### ISSUE TITLE
isoflavonoid processes should be related to flavonoid processes

### ISSUE THREAD

**Issue by mdolanme** [geneontology/go-ontology#17187]
Since isoflavonoid 'is_a' flavonoid according to ChEBI, appropriate process terms in GO should be 'is_a' related -- e.g. 'isoflavonoid catabolic process' should be related to 'flavonoid catabolic process' (or somewhere up the graph).

**Comment by ukemi** [comment]
In ChEBI, isoflavonoid (CHEBI:50753) is a subclass of a grouping term, flavonoids (CHEBI:72554). The specific flavonoid (CHEBI:47916) is a sibling of isoflavonoid. We don't have a class that represents the metabolism of the grouping term we could create a flavonoid compound metabolic process using the grouping term if you think that would be helpful.

**Comment by ukemi** [comment]
ping @hdrabkin

**Comment by hdrabkin** [comment]
I had already misread the chebi term and mistook it for a non-super class term. Given the structures of isoflavonoid vs other types of flavonoid, I am not sure.
