### ISSUE TITLE
Query GO:0004012, phospholipid-translocating ATPase activity and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17186]
From #17164

@vanaukenk: 
> I have a question about GO:0004012, phospholipid-translocating ATPase activity.
Is that activity transmembrane transport, or does it refer to translocation of phospholipids from one monolayer to the other, e.g. cytoplasmic leaflet to exoplasmic leaflet?

@pgaudet: 
> Hi @vanaukenk
Good point. These are described as flippases or scramblases, see https://en.wikipedia.org/wiki/ATP10A "The aminophospholipid translocases transport phosphatidylserine and phosphatidylethanolamine from one side of a bilayer to another."
I will not touch these for now - these will probably need an annotation review.
Thanks, Pascale

@ValWood:
>should be placed under
GO:0120013 intermembrane lipid transfer activity
or GO:0140303 intramembrane lipid transporter activity
which should also have a common parent, probably.

>corrected above to
GO:0140303 intramembrane lipid transporter activity

>but
phospholipid-translocating ATPase activity (GO:0004012)
appear to be defined as GO:0140303 intramembrane lipid transporter activity (inner to outer leaflet)

>possibly equivalent?

>the intermembrane ones are the
sec14 cytosolic factor family

**Comment by ValWood** [comment]
Also consider the position of

GO:0017128    phospholipid scramblase activity

Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, by an ATP-independent mechanism.

(the ATP independent intra membrane term)

**Comment by pgaudet** [comment]
Right, thanks ! 

It seems annotations need to be reviewed - for example P08183 looks like transmembrane transporter (PMID:8898203) - @RLovering

**Comment by ValWood** [comment]
I used the matrix to identify violations

GO:0045332
should not probably overlap with
GO:0022857
or
GO:0055085 


![violations](https://user-images.githubusercontent.com/7359272/56730081-d62e9d80-674e-11e9-978c-4b0075658cc5.jpg)

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=isa_partof_closure:%22GO:0055085%22&fq=isa_partof_closure:%22GO:0045332%22

![sources](https://user-images.githubusercontent.com/7359272/56730160-14c45800-674f-11e9-80ba-52c3293eb0fe.jpg)

unfortunately, you cant switch this to an annotation view to see the evidence

but these are the sources:
![sources](https://user-images.githubusercontent.com/7359272/56730194-31609000-674f-11e9-9f95-013dc1ff55f1.jpg)

**Comment by ValWood** [comment]
both of the PomBase ones will be fixed by
https://github.com/geneontology/go-annotation/issues/2329

**Comment by ValWood** [comment]
GAh this should be on teh annotation tracker...will migrate

**Comment by ukemi** [comment]
Not sure what the action is here, but assigning.

**Comment by pgaudet** [comment]
I can do it. I think the action will be either a merge or a better definition of the terms.

**Comment by pgaudet** [comment]
@marcfeuermann and I looked at all these terms and their annotations. I am changing the labels to make the direction of the lipid transfer as follows: 

- 'ATPase-coupled ceramide transporter activity' -> ceramide floppase activity
- 'ATPase-coupled phosphatidylcholine transporter activity' -> phosphatidylcholine floppase activity
- 'ATPase-coupled phosphatidylserine transporter activity'  -> phosphatidylserine floppase activity

Since all papers show that they are floppases (moving the lipid from the cytoplasic side leaflet to the exocytoplasmic leaflet of the membrane). 

Thanks, Pascale

**Comment by pgaudet** [comment]
and fixed the definitions: 
"Catalysis of the movement of [x] from the cytosolic to the exoplasmic leaftlet of a membrane, using energy from the hydrolysis of ATP."

**Comment by pgaudet** [comment]
Also: 
GO:0015437 ATPase-coupled intramembrane lipopolysaccharide transporter activity -> lipopolysaccharide floppase activity

GO:0034202 ATPase-coupled intramembrane glycolipid transporter activity -> glycolipid floppase activity

**Comment by pgaudet** [comment]
For 
GO:0004012ATPase-coupled phospholipid transporter activity and 
GO:0090555 ATPase-coupled phosphatidylethanolamine transporter activity

it looks like there are both flippases and floppases. I will create both terms and ask for annotation reviews.

**Comment by pgaudet** [comment]
GO:0090555 ATPase-coupled phosphatidylethanolamine transporter activity
-> change label to 'phosphatidylethanolamine flippase activity' and ask for annotation review, as there may be one floppase:  
https://github.com/geneontology/go-annotation/issues/2341

**Comment by pgaudet** [comment]
Updated comment to 
'Nomenclature note. Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane. Flippases and floppases are ATP-dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature, they catalyze lipid transfer towards the inward monolayer (flippases) or towards the outward monolayer (floppases). Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements (PMID 20043909).'

**Comment by marcfeuermann** [comment]
The P4 ATPases are usually considered as "flippases". In the litterature, the term "flippase" is used for most lipid translocating enzymes, whether they have flippase or floppase activity.
Many ABC transporters have also been shown to transport lipids from one side to the other side of a membrane, mostly from inside (cytoplasmic) to outside (exocytoplasmic), in addition to perform transmembrane transport of various other compounds. The mechanisms involved in the flip/flop of lipids by ABC transporters is still under debate, but it is usually accepted as flippase activity (in fact mostly floppase, when considering the direction).

**Comment by pgaudet** [comment]
- [ ] Change label sphingolipid-translocating ATPase activity (1 annotation, under review) https://docs.google.com/spreadsheets/d/1Y3v52aUxi0a8sgd83z8PDHC4RYllgIx4z9sRpmqv2wM/edit#gid=0

**Comment by pgaudet** [comment]
This branch is now all revised.
