### ISSUE TITLE
Taxon constraint from pyridine nucleotide biosynthetic process

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17197]
Could you look into this.

GO:0006741 NADP biosynthetic process flagging up taxon constraint: "Never in" Metazoa & Fungi. 
(This term used for NAP Kinase, for example - so needed)

This constraint has been inherited from
GO:0019363 pyridine nucleotide biosynthetic process
2019-04-26 	Added 	CONSTRAINT 	never_in_taxon NCBITaxon:4751 (Fungi)
2019-04-26 	Added 	CONSTRAINT 	never_in_taxon NCBITaxon:33208 (Metazoa)

**Comment by hdrabkin** [comment]
Now that I am looking at it..... This might be true of the base level, but not of the nucleotide level....

**Comment by deustp01** [comment]
It's not true at the base level either: carbamoyl phosphate -> carbamoyl aspartate -> dihydroorotate -> orotate (a free pyrimidine base) which then reacts with phosphoribosyl pyrophosphate (PRPP) to form orotidine monophosphate, a nucleotide. PMID: 6105839 is a definitive review including discussion of bacterial, fly, and mammalian versions of the process.
(Purines are synthesized in a pathway that starts with (PRPP) and then builds the purine structure as an increasingly elaborate ribose-phosphate derivative, so no free purine base is ever formed.)

**Comment by deustp01** [comment]
Unless quinolinate (ChEBI:46828), formed in the de novo synthesis of NAD,  counts as a base. From the drawing, it looks like a dicarboxylate derivative of pyridine so it might qualify. Also the salvage pathway for NAD starts from nicotinate (ChEBI:32544), a monocarboxylated pyridine.

**Comment by hdrabkin** [comment]
So I am inclined to just remove both of these restraints as being just wrong.

**Comment by ukemi** [comment]
Hmmm. The parentage here indicates that it is a child of pyridine-containing compound terms, not pyridine terms. So I don't think the taxon constraint pyridine terms should apply.

**Comment by ukemi** [comment]
The taxon constraints are on the pyridine nucleotide terms. This is what is incorrect since nicotinamide nucleotides are pyridine nucleotides.

**Comment by hdrabkin** [comment]
um; I can't seem to find this in the tsv file ?

**Comment by ukemi** [comment]
Hmmmm. Perhaps a typo in the tsv file?

GO:0019363 	protoporphyrinogen IX biosynthetic process from glutamate 	NCBITaxon:4751 	Fungi
GO:0019363 	protoporphyrinogen IX biosynthetic process from glutamate 	NCBITaxon:33208 	Metazoa

Should be GO:0019353 I think.

**Comment by hdrabkin** [comment]
Ah, I was looking for 
GO:0019363 'pyridine nucleotide biosynthetic process' ; odd couldn't find the GO id either. 
but there they are

**Comment by hdrabkin** [comment]
ok; changed xxxxxx63 to 53;
