### ISSUE TITLE
'sperm flagellum movement' redundant with 'sperm flagellum movement involved in flagellated sperm motility'?

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17193]
I think that the term 'sperm flagellum movement' is actually redundant with its child term 'sperm flagellum movement involved in flagellated sperm motility' as the sperm flagellum serves no other purpose in the sperm than sperm motility. 

-- sperm flagellum movement (GO:0097724)
--- sperm flagellum movement involved in flagellated sperm motility (GO:1905419)

Looking in Amigo, I think that there are no direct annotations to 'sperm flagellum movement'. All 18 annotations that show up on the page for this term are actually made directly to the child term.
http://amigo.geneontology.org/amigo/term/GO:0097724

In the equivalence axiom, the term 'sperm flagellum movement' could be replaced by 'cilium movement' since we've been explicit in many places that 'cilium' and 'flagellum' are equivalent in the context of eukaryotes.
```
'sperm flagellum movement'
 and ('part of' some 'flagellated sperm motility')
```
Therefore, I propose to merge **sperm flagellum movement (GO:0097724)** 
into **sperm flagellum movement involved in flagellated sperm motility (GO:1905419)**

**Comment by cmungall** [comment]
agreed. Looks like it was intended to mirror the cilium movement terms, but of course cilia are involved in not-cell-motility processes. We should have a check for single-children like these

**Comment by krchristie** [comment]
Looking for single children may not always signal a problem though. Here's a example close by in the ontology where there is only one child:

-- cililum movement involved in cell motility
--- sperm flagellum movement involved in flagellated sperm movement

There's no need to have a term for something like 'cilium movement involved in single celled organism movement since the parent term is sufficient for that. The reason for the sperm term is related to other places in the ontology where we want to specify flagellated sperm.
