### ISSUE TITLE
ntr: ELL-EAF-EBP complex (and SEC)

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#17203]
Hi,

A couple of possible new terms from PMID:30102332:

Although I don't need GO:new1, the introduction describes it, so here are the details in case it's worth adding the term for annotators who could use it.

The def for GO:new2 is a bit woollier at present, but that's the one I can use for some fission yeast gene products if it's added.

ID: GO:new1
name: super elongation complex
def: A protein complex that increases the overall rate of RNA polymerase II transcription elongation by suppressing transient polymerase pausing. The complex contains a transcription factor of the ELL family, as well as P-TEFb and EAF, AF9 or ENL, and an AFF family protein.
synonym: SEC (exact, unless the abbreviation is used for anything else)
is_a: GO:0008023 ! transcription elongation factor complex
has_part GO:0032783 ! ELL-EAF complex
capable_of_part_of GO:0032968 ! positive regulation of transcription elongation from RNA polymerase II promoter

- Introduction suggests only_in_taxon Metazoa; I haven't looked at the cited papers. Discussion has: "In mammalian cells, the multisubunit SEC is assembled combinatorially from one of three ELL family members, one of two EAF family members, the cyclin-dependent kinase T-TEFb (Cdk9/Cyclin C), one of two AF9 family members, and one of four AFF family members, which provides the scaffold upon which the SEC assembles."

ID: GO:new2
name: ELL-EAF-EBP complex
def: A protein complex that increases the overall rate of RNA polymerase II transcription elongation, and resembles a simpler version of a super elongation complex. The complex contains a transcription factor of the ELL family, EAF, and an AFF family protein or distant relative (Ell1, Eaf1, and Ebp1 in Schizosaccharomyces pombe).
is_a: GO:0008023 ! transcription elongation factor complex
capable_of_part_of GO:0032968 ! positive regulation of transcription elongation from RNA polymerase II promoter

- This complex has recently been identified in S. pombe; I don't know what other taxa may have complexes that fit this definition, but it does sound like the authors hope and expect that some will turn up, perhaps in other fungi. I'm open to alternative suggestions for the name.

- There are also some tantalizing hints that the complex may somehow associate with P-TEFb such that the actual functional unit is a "rudimentary SEC", but there isn't really enough data to support a complex term for it at present.

**Comment by bmeldal** [comment]
I'm wondering if 

ELL-EAF-EBP complex from PMID:[30102332](http://europepmc.org/articles/PMC6212713)

is just a better characterisation of the "old" 

GO:0032783 ELL-EAF complex from PMID:[17150956](http://www.jbc.org/content/282/8/5761.full), 

now with an additional subunit EBP.

We run the risk again of defining complexes by their composition rather than their function. They all seem to be super elongation complexes.

**Suggestion:** 
Update GO:0032783 ELL-EAF complex

**New Name: super elongation complex**
Old Def: 
A heterodimeric protein complex that acts as an RNA polymerase II elongation factor; the complex is conserved from yeast to humans, and is present in S. pombe, but absent from S. cerevisiae.

New def (combining with Midori's suggestions above):
 
A transcription elongation factor complex that increases the overall rate of RNA polymerase II transcription elongation by suppressing transient polymerase pausing. At minimum, the complex contains a transcription factor of the ELL family, an EAF protein, and an AFF family protein or distant relative and most likely also P-TEFb and AF9 or ENL. The complex is conserved from yeast to humans. In Schizosaccharomyces pombe it contains Ell1, Eaf1, and Ebp1, but it is absent from S. cerevisiae.

> synonym: SEC (exact, unless the abbreviation is used for anything else)

There are other Sec complexes in GO, related to ER and cytoplamic membrane secretion SecXXX proteins.

**Comment by mah11** [comment]
> I'm wondering if ELL-EAF-EBP complex from PMID:30102332 is just a better characterisation of the "old" GO:0032783 ELL-EAF complex from PMID:17150956, now with an additional subunit EBP.

This may well be the case, but I don't know enough to make that call. I can pass the question along to the author who curated PMID:30102332 for us if that will help.

> They all seem to be super elongation complexes.

I'm very reluctant to say they could all use the same GO CC term without checking with the authors. They give the impression in the paper that the distinction between the SEC as characterized in mammals and any simpler version(s) (of which the pombe complex is the first identified example) is of evolutionary importance. Again, I'm happy to forward the question, and specifically ask whether there are any functional distinctions to accompany the composition differences.

I also don't know whether it's been shown that the pombe complex "increases the overall rate of RNA polymerase II transcription elongation by suppressing transient polymerase pausing" as the metazoan SEC does.

**Comment by mah11** [comment]
Questions sent to J. Conaway:

1. GO has a term for "ELL-EAF complex" (GO:0032783), which is defined as: "A heterodimeric protein complex that acts as an RNA polymerase II elongation factor; the complex is conserved from yeast to humans, and is present in S. pombe, but absent from S. cerevisiae." Should this remain as a separate term, or is it simply that there's one complex, but EBP wasn't identified as part of it several years ago (when GO:0032783 was defined)? In the latter case we can amend the name and definition of the existing term.

2. I've suggested adding a term for the metazoan SEC, and a term for the pombe complex. To include two (or more) terms for complexes, GO strongly prefers to be able to distinguish their functions as well as their compositions. With that in mind, would it suffice to have one "super elongation complex" term, with a definition that acknowledges the simpler and more elaborate versions? Or can you suggest any functional features that could be used to distinguish two terms from each other?

3. On a related note, do you know how the pombe complex regulates transcription elongation? For the metazoan SEC, we can say that it "increases the overall rate of RNA polymerase II transcription elongation by suppressing transient polymerase pausing", but would the same level of specificity hold true for pombe or any other species that has the "rudimentary" SEC?

**Comment by bmeldal** [comment]
Good plan, Midori :)

**Comment by mah11** [comment]
I haven't ever heard back, so don't know if there's anything to do here ...

**Comment by pgaudet** [comment]
Ah ! I can implement changes proposed by @bmeldal ?

**Comment by mah11** [comment]
I guess so, since I haven't heard otherwise.

**Comment by mah11** [comment]
If @bmeldal's changes inspire any of our users to complain, maybe they'll give us more to go on ;) If so, I can open a new ticket then.

**Comment by bmeldal** [comment]
I'm happy for @mah11 and my suggestions to be implemented but Midori has reservations around the common (or not!) function of the metazoan and pombe SEC. As it's not in Saccharomyces I can't compare to what we curated...

**Comment by pgaudet** [comment]
Fixed definition, added two NARROW synonyms: 

+synonym: "ELL-EAF complex" NARROW []
+synonym: "ELL-EAF-EBP complex" NARROW []

Thanks, Pascale
