### ISSUE TITLE
Should thapsigargin and tunicamycin terms be deleted?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#17227]
I think that the terms describing thapsigargin (inhibits SERCA) and tunicamycin (induce endoplasmic reticulum stress) should be deleted. These are just naturally occurring chemicals that are used to cause a specific change in the cell by inhibiting a process. Unless there are other organism systems that have gene products that are specifically present to enable consumption of the plants/bacteria these are derived.

The majority of annotations are IEAs. Before deletion (if agreed) curators should review these and check that the intent of the author using these chemicals is captured.

GO:1904579 cellular response to thapsigargin 9 annotations
GO:1904578 response to thapsigargin 9 annotations
GO:1905893 positive regulation of cellular response to thapsigargin 1 annotations
GO:1905892 negative regulation of cellular response to thapsigargin 47 annotations
GO:1905891 regulation of cellular response to thapsigargin 48 annotations 

GO:1904577 cellular response to tunicamycin 4 annotations
GO:1904576 response to tunicamycin 15 annotations
GO:1905896 positive regulation of cellular response to tunicamycin 1 annotations
GO:1905895 negative regulation of cellular response to tunicamycin 47 annotations
GO:1905894 regulation of cellular response to tunicamycin 48 annotations 

I have added this ticket to Val's ticket https://github.com/geneontology/go-ontology/issues/16565 which seems to be also questioning this idea of drawing a line between a drug that is also a naturally occuring substance in the body and a drug which is used as a specific inhibitor in an experimental system to investigate a specific process, ie as an inhibitor etc. ie we should in these cases annotate 'author intent' rather than experimental conditions. 
I am assuming that as new synthetic drugs are tested as inhibitors these will not be given specific GO terms. Although I do not object to the annotation of gps involved in drug metabolism / transport etc and also for being able to capture the metabolised 'drug'

Thanks

Ruth

**Comment by ukemi** [comment]
On the editors' call we decided that an ontology editor should have a look at the annotations and decide if they really represent annotations to a process that is specifically inhibited and would fall under the umbrella of the IMP guidelines:

any procedure that disturbs the expression or function of the gene, including RNAi, anti-sense RNAs, antibody depletion, or the use of any molecule or experimental condition that may disturb or affect the normal functioning of the gene, including: inhibitors, blockers, modifiers, antagonists, temperature shifts, or changes in pH or ionic strength.

    For example, an experiment using baicalein to inhibit the activity of 12-LOX in a murine bladder cancer cell line inhibits cell proliferation in a concentration dependent manner (see PMID:15161019) and results in an annotation to the GO term cell proliferation using the IMP evidence code for the 12-LOX gene.

**Comment by hdrabkin** [comment]
I won't look at the IEAs right away

**Comment by ValWood** [comment]
I agree with @RLovering  these are chemicals used  as experimental inhibitors of specific processes.We should remove these terms ( they are usually just part of the experimental conditions).

Added "response_to_terms" label to this ticket and a few others

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:1904579 cellular response to thapsigargin and GO:1904578 response to thapsigargin & regulation children. The reason for obsoletion is that these drugs cause ER stress, so the papers should likely be re-annotated to 'GO:0034976 response to endoplasmic reticulum stress'. 


There are 7 manual annotations remaining: 
1 GeneDB 
7 RGD

Annotations are here: 
https://github.com/geneontology/go-annotation/issues/4229

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on July 5th, 2022. Unless objections are received by July 5th, 2022, we will assume that you agree to this change.
 
You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/17227

Thanks, Pascale

**Comment by slaulederkind** [comment]
All manual RGD annotations have been changed.
