### ISSUE TITLE
NTR, plasma membrane, cell tip

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17222]
NTR: plasma membrane, cell tip

ancestor  of
plasma membrane of growing cell tip GO:1902929   

descendant of
plasma membrane part GO:0044459
cell tip GO:0051286

def
Any plasma membrane part that is part of a  cell tip

Also
NTR: cytoplasmic side of plasma membrane, cell tip
The leaflet the plasma membrane at the cell tip that faces the cytoplasm and any proteins embedded or anchored in it or attached to its surface.
ref:PMID:28292899

**Comment by mah11** [comment]
for the first one, just add a synonym to GO:0031520 ! plasma membrane of cell tip (which has only existed for 10 years or so ;) )

**Comment by ValWood** [comment]
And fix the parent/graph. I thought the term existed!

but under plasma membrane part I could only see this:

![part](https://user-images.githubusercontent.com/7359272/57027792-4187dc00-6c35-11e9-91cd-fa92513b14f6.jpg)

**Comment by ValWood** [comment]
i.e
![plasma membrane](https://user-images.githubusercontent.com/7359272/57027872-7ac04c00-6c35-11e9-9deb-42f249a79211.jpg)

**Comment by hdrabkin** [comment]
Clarifications needed
For
NTR: cytoplasmic side of plasma membrane, cell tip
The leaflet the plasma membrane at the cell tip that faces the cytoplasm and any proteins embedded or anchored in it or attached to its surface.
ref:PMID:28292899

what is is_a parent?

**Comment by ValWood** [comment]
is_a GO:0009898   cytoplasmic side of plasma membrane

part_of GO:0031520  plasma membrane of cell tip

**Comment by ukemi** [comment]
@hdrabkin do you want me to just take this one?

**Comment by hdrabkin** [comment]
I just added the NTR GO:0106186 cytoplasmic side of plasma membrane, cell tip and am waiting on Travis

**Comment by mah11** [comment]
To clarify, the asserted parents of GO:0031520 look correct. GO:1902929 should become is_a GO:0031520.

**Comment by ValWood** [comment]
Hi Harold. I dont see this?

**Comment by ValWood** [comment]
ignore
