### ISSUE TITLE
NTR 'xenobiotic detoxification by transmembrane export across the outer membrane'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17234]
Hello, 

For 
https://github.com/geneontology/go-annotation/issues/2334

I will create 'xenobiotic detoxification by transmembrane export across the outer membrane'

Thanks, Pascale

**Comment by pgaudet** [comment]
@amandamackie is PMID:11948170 a good reference for this term ? 
Of if you have a better one, please send it. 

Thanks, Pascale

**Comment by amandamackie** [comment]
No don't use PMID 11948170, it's about SugE which exports substrate across the plasma/inner membrane.

I would recommend PMID: 28355133 (Wang 2017) for the new term. It's on the AcrABTolC complex which pumps substrate across the outer membrane in E. coli. 
Fig 7 reproduced below from that paper shows current model of proposed mechanism for the complex (A = pump in closed state; B = pump in open state; S = substrate)
![image](https://user-images.githubusercontent.com/18317338/57201733-7fdc1d00-6fe0-11e9-84ca-915bd848d121.png)

Thanks for the new term
Amanda
