### ISSUE TITLE
term obsoletions "interaction with host via secreted substance released from...." in pathogen host interaction branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17243]
I'm annotating a paper with @CuzickA 

Alayne selected
 GO:0085005    interaction with host via secreted substance released from invasive hyphae
GO:0044046    interaction with host via substance released outside of symbiont

which is all true but *DOES NOT* describe a process.

It does not really make sense to describe a symbiont/ host interaction  interaction in GO beyond
GO:0051701    interaction with host
unless you can be more specific about the process.

The differentia here are not processes,  they are about i) where the pathogen host effector came from and b) how it got out of the pathogen BUT what is the *actual*  process?

In the case we are annotating  the process is "effector triggered necrosis"
(i.e the pathogen effector enters the plant and activates the host cell death pathway). 
I will request a term for this (in a more processy form), I don't think we have it.

(and parent)
GO:0052048    JSON
interaction with host via secreted substance involved in symbiotic interaction

GO:0085002    JSON
interaction with host mediated by secreted substance released by symbiont from symbiotic structure

**Comment by ValWood** [comment]
@CuzickA  does this sound OK to you?

**Comment by ValWood** [comment]
The branch I propose we obsolete has only 63 annotation (total) all but 9 are Magnaporth Orzae

(some of the terms under here are even crazier

"interaction with host via protein secreted by type II secretion system" !
)

suggest just merging this branch up to

GO:0051701    interaction with host

**Comment by pgaudet** [comment]
@mgiglio99 
Is that OK with you ?

**Comment by mgiglio99** [comment]
Val I completely understand what you are saying and I agree with you that the added parts beyond 'interaction with host' are not describing the process. However, I think one of the reasons that those bits were added on was to provide a way to annotate something was an effector protein and also to capture ones secreted by specific systems since, at the time anyway, there wasn't another way to do that.
So before we get rid of these - how would we go about capturing that info?
GO doesn't have "effector" as a function. But with terms like Val suggested "effector triggered necrosis" that is sort of, but not really, captured - since that term doesn't indicate that the protein you annotate it to is the actual effector. 
Is there a way to capture the targets of things independent of interactions? For example a way to use GO to say that something was the target of a type III secretion system? I seem to recall many years ago there was some talk of this - but I've been out of the loop for a long time.

And btw, what does "JSON" mean?

**Comment by ValWood** [comment]
Hi Michelle,

Great question.
1. confaltion of export mechanism with pathogen host interaction 
The gene products exported by a specific secretory system should be annotated as targets of that system. This isn't always a great solution, and I have pondered over it lots. This works well 
if the export is achieved by one or a small number of gene products, but it  doesn't work well for larger machinery like for instance a proteasome, or the entire secretory system. We end up with targets annotated to individual components of the system like "cargo receptors". i don't think Noctua solves this problem either. We really need a way to capture substrates of larger machinery, but we shouldn't conflate them into other downsteam processes. This is alrger issue would be good to discuss on an annotation call.

2. 
> GO doesn't have "effector" as a function. But with terms like Val suggested "effector triggered necrosis" that is sort of, but not really, captured - since that term doesn't indicate that the protein you annotate it to is the actual effector. Is there a way to capture this?

Here "effector triggered necrosis"  is the biological process caused by the effector. This is a term which would be used by the pathogen ONLY, and I don't think you could annotate anything other than effectors to this term, so in some ways it does capture "effector" but as a BP.

The "effectors" will also need a complimentary function term if this is known (sometimes it isn't, it is only known that the molecule causes virulence in which case MF is unknown, but you could do the appropriate "effector-mediated process" term.

The problem is that "effector" isn't really a single function. Although pathogen community use it, it should only be in GO as a related synonym of the different activities which effectors are found to perform. So far I have come across a few- some act as decoy molecules, for example, to sequester chitin fragments which are detected by the host. Some act as receptor ligands. I'm sure there are lots more. So a single MF term is not suitable to capture this heterogeneous mixture of functions. In summary effector isn't a term that can be a primary term name in GO, but we can add as related (broad) synonyms. We could even make the terms clearer by adding effector to the term names if that helps the community.

i.e PAMP binding effector
but I think we can only do this if we know the specific effector mechanism.


3. JSON appears when you cut and past from QuickGO. I sometimes forget to delete it. Removed.

**Comment by ValWood** [comment]
The protein secretion system case it is possible to capture targets:

GO:0015628 type II secretion system has_input secreted_gene_product

**Comment by pgaudet** [comment]
Hi Michelle, 

WRT  
> to capture ones secreted by specific systems

We have decided a long time ago that 'targets' of activities are not captured (other than by an 'has input' extension). The classical example is that if a protein is phosphorylated by a certain kinase, that substrate is not involved in the kinase activity or in the phosphorylation process. 

So similarly, if a protein is secreted by a certain system, that's not its function. (You can however annotate the secretion system members with that input). 

In this case I am not sure what you mean by 'effector' - it sounds like its the protein that triggers the immune response in the host. It is not the 'evolved' role of the protein to get recognized by the host, so that's not a GO 'function'. However I understand the interest in capturing that information - we need to find a way that wouldn't be conflated with the annotations describing how the process occurs normally. 

It may be helpful to look at some annotations.

Thanks, Pascale

**Comment by ValWood** [comment]
It is an evolved  role for the effector to  manipulate the host immune system though. But it's a grouping term  for  different types of molecular function. it just means "molecule produced by the pathogen to affect the host immune system"

**Comment by mgiglio99** [comment]
> So similarly, if a protein is secreted by a certain system, that's not its function. 

I completely agree and totally get this - I was just hoping for a way to use the GO to somehow capture targets and it sounds like has_input is the way to do it.
As Val said:

> GO:0015628 type II secretion system has_input secreted_gene_product

Ok - so the secretion part we can capture.

Now for the effector part.

First to comment on Val's suggested term - "effector triggered necrosis" - this sounds more like a term about the process of necrosis, but you only want effectors to be annotated with this so do you think maybe "effector triggering of necrosis" might be more clear? 

Second, on effector as being a grouping term for more than one function, is that any different than the current GO:0050827 "toxin activity" ?
If we can have toxin, can we have effector?

**Comment by pgaudet** [comment]
@mgiglio99 Can you please describe what you mean by 'effector'?

**Comment by ValWood** [comment]
I think since we have toxin (and transcription regulator), maybe  we should be able to have effector as a grouping term.

An effector (for GO purposes) would be a 
"pathogen/symbiont  protein that  enables the pathogen to invade host tissue, suppress its immune system, or otherwise help the pathogen to survive"

**Comment by ValWood** [comment]
>First to comment on Val's suggested term - "effector triggered necrosis" - this sounds more like a term about the process of necrosis, but you only want effectors to be annotated with this so do you think maybe "effector triggering of necrosis" might be more clear?

Maybe , I will check but  effector-triggered necrosis should be a synonym, as that is how the community refer to this process in necrotrophic fungi. 

(it would be clearly defined as a pathogen term and it can have taxon restrictions )

**Comment by pgaudet** [comment]
So that would be the definition for a term called 'effector activity'? or perhaphs 'symbiont effector activity', to make it less ambiguous ?

**Comment by addiehl** [comment]
Just want to point out in a somewhat different GO context that the immune system branch has a high level term 'immune effector process', defined as "Any process of the immune system that can potentially contribute to an immune response", as well as a number of other terms that include the word effector.  This is in line with the immunological literature that separates immune responses into their activation and effector processes.  In English, the verb "to effect" means to cause something to happen, and in this sense an immune effector process is a process that does the work of the immune system in carrying out an immune response.  "immune effector process" is obviously a grouping term, but one that immunologists doing term enrichment would immediately recognize.

Presumably an "effector function" is a _process_ carried out by an individual protein (in a microbial context) that causes or enables a more general process to occur, such as invasion of host tissue, suppression of the immune system of a host, or induction of the death of a host cell.  We can assume a "protein effector" is a protein with an "effector function".  While we may not need to include "effector function" as a grouping term in MF, it is useful to think about this when faced with community usage of the word "effector" in describing particular proteins and what they do.

**Comment by mgiglio99** [comment]
> An effector (for GO purposes) would be a
> "pathogen/symbiont protein that enables the pathogen to invade host tissue, suppress its immune system, or otherwise help the pathogen to survive"

I like this definition although I'd add something about evading immunes\ system and avoid making it too specific to pathogens, so how about this:
"a symbiont protein, often from a pathogen, that enables the symbiont to invade host tissue, suppress or evade host immune systems, or otherwise help the symbiont to survive and replicate in the host."

I'd go with "symbiont effector activity" as the term name. Which I think would help with Alex's point about other types of effectors. But maybe Alex would object to the use of the word "activity". Should it be "symbiont effector function"?

Now all of this said, I'm still not sure it's a good idea to make such a term. It is definitely an artificial grouping of many different functions with a fairly vague definition. But it does mean something important to the relevant communities.  And since we have "toxin activity", that really opens the door to this kind of thing.  (And I must say that many years ago when I first got involved in GO, there was a term "toxin activity" that was obsoleted for the exact reason that it didn't represent a true function. I remember the debates about that term very well. I'm happy to see it back, but having accepted the logic that led to its obsoletion in the past, I still have reservations.)

**Comment by ValWood** [comment]
Would it be possible to call this term"pathogenic effector activity"
It is appropriate for pathogens or symbionts  (because sometimes there is no  interaction phenotype, i.e virulence). However, it is ALWAYS  referred to as a "pathogen effector"

"pathogen effector  Google About 38,000 results 
"pathogenic effector" Google About 53,000 results 
"symbiont effector" Google About 41 results

(It could be defined as a "symbiont effector" but we should use the language the community understands in the term names)

**Comment by ValWood** [comment]
i.e. use a version of Michelle's definition

"A molecular function  that enables the symbiont (often a pathogen) to invade host tissue, suppress or evade host immune systems, or otherwise survive and replicate in the host."

(changed from protein to Molecular function)

**Comment by ValWood** [comment]
Actually, I wonder if this definition is now too broad ...

"or otherwise survive and replicate in the host" could include lots of activities in addition to effectors...i.e any process which helps the pathogen to replicate in the host. For a fungi this could even cover the fungal replication machinery, of the biogenesis of the penetration machinery, but these are not effectors.

Is the effector always secreted by the pathogen? Or are there any other restricting criteria

@CuzickA ?

**Comment by pgaudet** [comment]
Hi @ValWood @mgiglio99 
What is the action here ? 

First can we improve (or obsolete) the branch 
GO:0052047 interaction with other organism via secreted substance involved in symbiotic interaction? 

And do you want a new term created ? or to modify the definition of 'immune effector process? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't think we need new terms (there are many suitable existing terms). It could merge with GO:0051701 interaction with host
but people may want to know to annotate more specifically in a more appropriate existing sub-branch.

**Comment by pgaudet** [comment]
> It could merge with GO:0051701 interaction with host 

Which term(s)?

**Comment by mgiglio99** [comment]
> Actually, I wonder if this definition is now too broad ...

I see what you mean. I do think that they are always secreted. So how about:
"A molecular function enabled by a protein secreted from the symbiont into host cells that enables the symbiont (generally a pathogen) to invade host tissue and suppress or evade the host immune system."

**Comment by mgiglio99** [comment]
> I don't think we need new terms (there are many suitable existing terms).

Assuming by this you mean no need for new process terms?

**Comment by ValWood** [comment]
> Assuming by this you mean no need for new process terms?

Yes, but I think  GO:0052048 JSON
interaction with host via secreted substance involved in symbiotic interaction

are very problematic terms. They don't really supply anything which would not be gleaned from  using 
GO:0051701 interaction with host 
or  a more specific child in another branch. These terms would always require co annotation and lead to annotation inconsistency (which is evident from the fact that they haven't been used). How the molecule exits the pathogen is orthogonal to the "pathogen interaction process"

We can discuss on a call, but I can't see how this is not a confusing process.

**Comment by mgiglio99** [comment]
Let me try to sum up:

1. I think we agree that GO:0052048 'interaction with host via secreted substance involved in symbiotic interaction' and its children are not good terms - they conflate export mechanism and host interaction. So we should merge them into 'interaction with host'.  
2. Val's NTR for 'effector-triggered necrosis' is not needed since as she described in #17244 , there is a term that can be used and she requested the needed synonym.
3. We are still a bit undecided on whether there should a new term for 'pathogen effector activity' (another name under consideration is 'symbiont effector activity') with the definition "A molecular function enabled by a protein secreted from the symbiont into host cells that enables the symbiont (generally a pathogen) to invade host tissue and suppress or evade the host immune system."

Is this correct?

Michelle

**Comment by ValWood** [comment]
I agree with your summary.

I like the idea of a MF grouping term, mainly because effector terms are difficult to locate during curation, it would be *extremely useful"* for the community, and it's a really important biological grouping.

Note that  we have "antioxidant activity" and have recently added back, toxin, transcription regulator (and hopefully soon "chaperone") for this reason.

It's probably not  ontologically rigorous to include these heterogeneous grouping terms, but for pragmatic purposes, for both curators and users, the wins over-ride this anomoly.... and they should all have descendent instances which include the "ontologically correct" parent.

This will also act as a placeholder for  molecules that clearly function as effector, but the mechanism unknown? Maybe in the future there will be a better way to find these subsets, and at that point they can easily be taken away but in the meantime annotation and GO use will be improved.

**Comment by mgiglio99** [comment]
Hi Val,
I agree with you on the effector term.
Michelle

**Comment by pgaudet** [comment]
I will move 'lectin-induced modified bacterial internalization' under 'interaction with symbiont, and obsolete the rest: 

'interaction with host mediated by secreted substance entering host via endocytosis'
'interaction with host mediated by secreted substance released by symbiont from symbiotic structure'
'interaction with host mediated by symbiont secreted substance released from Maurer's cleft'
'interaction with host mediated by symbiont secreted substance released from symbiont-containing vacuole'
'interaction with host via protein secreted by Sec complex'
'interaction with host via protein secreted by Tat complex'
'interaction with host via protein secreted by type I secretion system'
'interaction with host via protein secreted by type II secretion system'
'interaction with host via protein secreted by type III secretion system'
-> consider protein secretion by the type III secretion system; extracellular, GO_NEW:(pathogen/symbiont) effector activity 

'interaction with host via protein secreted by type V secretion system'
'interaction with host via protein secreted by type VI secretion system'
'interaction with host via protein secreted by type VII secretion system'
'interaction with host via secreted substance involved in symbiotic interaction'
'interaction with host via secreted substance released from haustorium'
'interaction with host via secreted substance released from invasive hyphae'
'interaction with host via secreted substance released from microneme'
'interaction with host via secreted substance released from rhoptry'
'interaction with host via secreted substance released from stylet'
'interaction with host via substance secreted by type IV secretion system'
'interaction with other organism via protein secreted by type II secretion system involved in symbiotic interaction'
'interaction with other organism via protein secreted by type III secretion system involved in symbiotic interaction'
'interaction with other organism via substance secreted by type IV secretion system involved in symbiotic interaction'
'interaction with symbiont via secreted substance involved in symbiotic interaction'
'modification by host of symbiont morphology or physiology via secreted substance'
'modification by symbiont of host morphology or physiology via protein secreted by Sec complex'
'modification by symbiont of host morphology or physiology via protein secreted by Tat complex'
'modification by symbiont of host morphology or physiology via protein secreted by type I secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type II secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type III secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type V secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type VI secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type VII secretion system'
'modification by symbiont of host morphology or physiology via secreted substance'
'modification by symbiont of host morphology or physiology via substance secreted by type IV secretion system'
'modification of morphology or physiology of other organism via protein secreted by type II secretion system involved in symbiotic interaction'
'modification of morphology or physiology of other organism via protein secreted by type III secretion system involved in symbiotic interaction'
'modification of morphology or physiology of other organism via secreted substance involved in symbiotic interaction'
'modification of morphology or physiology of other organism via substance secreted by type IV secretion system involved in symbiotic interaction'

**Comment by pgaudet** [comment]
So I am clear: I merge all these terms: 

'interaction with host mediated by secreted substance entering host via endocytosis'
'interaction with host mediated by secreted substance released by symbiont from symbiotic structure'
'interaction with host mediated by symbiont secreted substance released from Maurer's cleft'
'interaction with host mediated by symbiont secreted substance released from symbiont-containing vacuole'
'interaction with host via protein secreted by Sec complex'
'interaction with host via protein secreted by Tat complex'
'interaction with host via protein secreted by type I secretion system'
'interaction with host via protein secreted by type II secretion system'
'interaction with host via protein secreted by type III secretion system'
'interaction with host via protein secreted by type V secretion system'
'interaction with host via protein secreted by type VI secretion system'
'interaction with host via protein secreted by type VII secretion system'
'interaction with host via secreted substance involved in symbiotic interaction'
'interaction with host via secreted substance released from haustorium'
'interaction with host via secreted substance released from invasive hyphae'
'interaction with host via secreted substance released from microneme'
'interaction with host via secreted substance released from rhoptry'
'interaction with host via secreted substance released from stylet'
'interaction with host via substance secreted by type IV secretion system'
'interaction with other organism via protein secreted by type II secretion system involved in symbiotic interaction'
'interaction with other organism via protein secreted by type III secretion system involved in symbiotic interaction'
'interaction with other organism via substance secreted by type IV secretion system involved in symbiotic interaction'
'interaction with symbiont via secreted substance involved in symbiotic interaction'
'lectin-induced modified bacterial internalization'
'modification by host of symbiont morphology or physiology via secreted substance'
'modification by symbiont of host morphology or physiology via protein secreted by Sec complex'
'modification by symbiont of host morphology or physiology via protein secreted by Tat complex'
'modification by symbiont of host morphology or physiology via protein secreted by type I secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type II secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type III secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type V secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type VI secretion system'
'modification by symbiont of host morphology or physiology via protein secreted by type VII secretion system'
'modification by symbiont of host morphology or physiology via secreted substance'
'modification by symbiont of host morphology or physiology via substance secreted by type IV secretion system'
'modification of morphology or physiology of other organism via protein secreted by type II secretion system involved in symbiotic interaction'
'modification of morphology or physiology of other organism via protein secreted by type III secretion system involved in symbiotic interaction'
'modification of morphology or physiology of other organism via secreted substance involved in symbiotic interaction'
'modification of morphology or physiology of other organism via substance secreted by type IV secretion system involved in symbiotic interaction'

**Comment by pgaudet** [comment]
@ValWood or @mgiglio99 Can you please create a new ticket for the effector term ? 

Thanks, Pascale

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/2376

**Comment by pgaudet** [comment]
Hi @mgiglio99 @ValWood 
I don't know if we want to keep any terms of that branch. I kept these for now (and simplified labels) 

 - 'GO:0052047 symbiotic process mediated by secreted substance' (was: interaction with other organism via secreted substance involved in symbiotic interaction)
 -- 'GO:0052213 interaction with symbiont via secreted substance' (was: interaction with symbiont via secreted substance involved in symbiotic interaction)
 -- 'GO:0052048 interaction with host via secreted substance'  (was: interaction with host via secreted substance involved in symbiotic interaction)

Do we need ???

**Comment by ValWood** [comment]
I don't think we need them....

**Comment by pgaudet** [comment]
Created a new ticket for the last group of terms (see previous comment): https://github.com/geneontology/go-ontology/issues/17489
