### ISSUE TITLE
NTR cell cortex of non-growing cell tip

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17249]
The cell cortex of a cell tip which is not a growth-site.

ref: I'll find a suitable one in a minute...but PMID:17895368 will do

**Comment by vanaukenk** [comment]
Proposed parent term would be:

http://amigo.geneontology.org/amigo/term/GO:0051285 

![image](https://user-images.githubusercontent.com/1730534/57863163-9562fb00-77c7-11e9-9a7b-5ca1869b3976.png)

**Comment by ValWood** [comment]
and

GO:0035839    non-growing cell tip

**Comment by ValWood** [comment]
and
GO:0035839    non-growing cell tip

**Comment by ValWood** [comment]
parents 
GO:0051285 cell cortex of cell tip
GO:0035839 non-growing cell tip
definition
The region directly beneath the plasma membrane at the cell tip at which no growth takes place.
ref PMID:17895368

coulld this be added? seems quick

**Comment by pgaudet** [comment]
Do you mind if I name this term 'cell cortex of non-growing cell tip region'? Otherwise it sounds like this is the cell cortex of the tip of a non-growing cell (this is what I first thought).

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140472
+name: cell cortex of non-growing cell tip
+namespace: biological_process
+def: "The region directly beneath the plasma membrane at the cell tip at which no growth takes place." [PMID:17895368]
+intersection_of: GO:0099738 ! cell cortex region
+intersection_of: part_of GO:0035839 ! non-growing cell tip
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/17249 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-18T13:33:58Z

**Comment by ValWood** [comment]
The other terms refer to "non-growing cell tip" so these would need to change. I also think is a bit clunky and redundant to add'region' and it's clear from the definition (and the alternative would be out of scope for CC?)

Also, the current terms precisely match the usage in publications.
