### ISSUE TITLE
help finding enzyme activity conversion of IP-7 to ip8

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17247]
I am looking for the activity to describe the conversion of IP7-> IP8 but I can't find it!
![IP7-8](https://user-images.githubusercontent.com/7359272/57358978-7aacd880-716e-11e9-8c94-c63dc0a128cb.jpg)

can anyone help?
@deustp01 @hdrabkin 

(note this figure isn't from the paper I am curating, It's just one I found Googling) I'm curating PMID:29440310

**Comment by ValWood** [comment]
while PPIP5Ks/Vip1 can add a diphosphate group to position 1 of IP6 and 5-IP7, thus generating 1-IP7 and 1,5-IP8 (named IP8 in the text), respectively (1, 2, 18, 19). The physiological in vivo substrate(s) of the kinase domain of the PPIP5K/Vip1 family has not been easy to define in a number of organisms analyzed to date (1–3). However, high-performance liquid chromatograph (HPLC) analysis of inositol phosphates in an S. cerevisiae VIP1 deletion strain suggested that Vip1 kinase activity might be responsible for the generation of IP8, as has been demonstrated for the PPIP5K/Vip1 family members in Cryptococcus neoformans and Arabidopsis thaliana (6, 11, 20). Also in mammalian cells PPIP5Ks are mainly responsible for IP8 synthesis since 􏰀2% of the IP7 pool is synthesized by PPIP5K (21).

**Comment by pgaudet** [comment]
GO:0000829 or a child ? 

see also https://link.springer.com/content/pdf/10.1007%2Fs00018-005-5446-z.pdf

**Comment by ValWood** [comment]
but the text says 
"while PPIP5Ks/Vip1 can add a **diphosphate** group to position 1 of IP6 and 5-IP7, thus generating 1-IP7 and 1,5-IP8 "

I wondered about that but how does this relate to
5-diphosphoinositol pentakisphosphate 3-kinase activity

which is a term we used before (but may be incorrect)

**Comment by ValWood** [comment]
pdf looks useful but I can't access even with VPN connection for some odd reason , because we obviusly have Springer access...

**Comment by ValWood** [comment]
I think you are right

**Comment by pgaudet** [comment]
I emailed you the pdf 

The nomenclature is quite confusing 

![image](https://user-images.githubusercontent.com/4782928/57360388-4f2feb00-717a-11e9-97be-52f8f2ea47ef.png)

**Comment by ValWood** [comment]
OK,  Ursula Fleig, the author just mailed me. Ursula will curate this on May 20th so I  will close this and re-open with any new requests for missing terms!
