### ISSUE TITLE
NTR: effector triggered necrosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17244]
follow on from
https://github.com/geneontology/go-ontology/issues/17243

I found the term we needed:

GO:0052040    modulation by symbiont of host programmed cell death
under
GO:0044003    modification by symbiont of host morphology or physiology
a sibling of
GO:0044044    interaction with host via substance in symbiont surface

This is yet another example of orthogonal ways to annotate in this branch.

GO:0044003    modification by symbiont of host morphology or physiology
is MUCH more "processy" 

The term name is  probably not easy to understand? Perhaps
"alteration of host morphology or physiology by symbiont?"

~So now, we need  a descendant term "NTR effector triggered necrosis" which is how  the plant pathogen community  label this process.
(don't be confused by the use of 'necrosis' in a term related to PCD- it is now known that the leaf necrosis observed when  necrotic fungal pathogens affect plants is mediated by 
activating the plant cell death pathway).
def: To follow
ref: to follow~  add synonym instead, see below

**Comment by ValWood** [comment]
Actually  the parent term is probably fine:
Any process in which an organism modulates the frequency, rate or extent of programmed cell death in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.


so add

effector triggered necrosis, narrow  PMID: 27641772 PMID:22241993

(there are lots of organism specific terms under here like viral specific terms, but this is the only differentia)

**Comment by ValWood** [comment]
Actually these should be added to

GO:0034053    modulation by symbiont of host defense-related programmed cell death


(the same term but with 'defense related' ???)
GO:0034053    modulation by symbiont of host defense-related programmed cell death

but does a pathogen ever regulate non defense related PCD?
Maybe merge?

**Comment by ukemi** [comment]
Fixed in #17269
