### ISSUE TITLE
'gliosis' vs. 'glial cell activation'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#17248]
I have contacted the inflammation expert on the ARUK-UCL project to comment on the 'gliosis' vs. 'glial cell activation'. 

For now, I am pasting a summary of information from the original ticket (https://github.com/geneontology/go-ontology/issues/16720) and links provided by @pengyubio here, as Ruth suggested:

https://www.ncbi.nlm.nih.gov/pubmed/24462092
https://www.ncbi.nlm.nih.gov/pubmed/14556716
https://www.ncbi.nlm.nih.gov/pubmed/27265809

<img width="841" alt="Screenshot 2019-05-08 at 15 12 10" src="https://user-images.githubusercontent.com/16541096/57374552-d6de1f80-71a3-11e9-8f89-c8071dff8b37.png">
<img width="783" alt="Screenshot 2019-05-08 at 15 12 22" src="https://user-images.githubusercontent.com/16541096/57374553-d6de1f80-71a3-11e9-9b4f-b0abade5340f.png">
<img width="606" alt="Screenshot 2019-05-08 at 15 12 51" src="https://user-images.githubusercontent.com/16541096/57374554-d776b600-71a3-11e9-935b-21f14bfc95fe.png">
<img width="591" alt="Screenshot 2019-05-08 at 15 12 59" src="https://user-images.githubusercontent.com/16541096/57374556-d776b600-71a3-11e9-84fd-044bdfaaabbb.png">
<img width="580" alt="Screenshot 2019-05-08 at 15 13 12" src="https://user-images.githubusercontent.com/16541096/57374558-d80f4c80-71a3-11e9-9222-f3e0ddde22c1.png">

cc
@RLovering @vanaukenk @pengyubio

**Comment by pengyubio** [comment]
@RLovering "gliosis" is used both as a process and a phenotype in the literature. Because "reactive gliosis" is more precisely used in the literature for the process, it is suggested as the term name instead of "gliosis" alone.

@BarbaraCzub So "reactive gliosis" is not the same as "glial cell activation" (the first meaning of it in my original message).
@RLovering @vanaukenk Is there any conclusion that can be made to this ticket?

**Comment by RLovering** [comment]
@pengyubio Do you think that the current term glial cell activation as currently defined and with its place in the ontology is completely equivalent to the term reactive gliosis that you have requested?

There are currently no annotations manual annotations associated with this term itself only to the more specific cell type terms.

My concerns are:
1. are there experiments which separate the difference between glial cell activation and reactive gliosis? The problem is that many expts add cytokines etc to look at glial cell activation and do not necessarily mean that these are in response to damaged neurons. Or do you feel that reactive gliosis can occur without neuron damage?
2. my gut feeling is that not all glial cell activation occurs as part of reactive gliosis. So if you look at each of the child terms are you completely sure that every case of  GO:0002265 astrocyte activation involved in immune response also a case of reactive gliosis? 
If not then I have a problem with your suggestion.

Thanks

Ruth

**Comment by pengyubio** [comment]
@RLovering According to <https://www.ncbi.nlm.nih.gov/pubmed/24462092>, "reactive gliosis" should be specific to CNS damage. I understand your point that "a cytokine, chemokine, cellular ligand, or soluble factor" may not be caused by CNS damage. In this case, a new term named "reactive gliosis" should be added. What do you think?

**Comment by BarbaraCzub** [comment]
Hi @pengyubio, 

Thank you for your insights and comments on this subject. 

I have discussed this with Ruth (@RLovering). We agree that "reactive gliosis" should be added to Gene Ontology, as an is_a child term of "GO:0150076 neuroinflammatory response", to allow to capture information from relevant animal models. 

@pengyubio, would you like to suggest the most suitable definition for this new term as well as advise what GOC dbxrefs I should add? (I will include PMID:24462092 as the literature reference for this GO term and I will add 'gliosis' as a _broad_ synonym). 

We were also wondering who you are, if you do not mind introducing yourself, and whether we could seek your advice in the future with regard to other neuroinflammation-related issues?

@vanaukenk would you like to add any comments or suggestions before I go ahead and add this term?

Thanks,
Barbara

**Comment by pengyubio** [comment]
> would you like to suggest the most suitable definition for this new term

The definition on Wikipedia for "gliosis" should be suitable for "reactive gliosis".

`a nonspecific reactive change of glial cells in response to damage to the central nervous system (CNS)`

> as well as advise what GOC dbxrefs I should add?

I am not familiar with GOC dbxrefs. Would you please show me where it is explained? Thanks.

**Comment by ValWood** [comment]
> a nonspecific reactive change of glial cells in response to damage to the central nervous system (CNS)

isn't this a phenotype?

**Comment by BarbaraCzub** [comment]
> > would you like to suggest the most suitable definition for this new term
> 
> The definition on Wikipedia for "gliosis" should be suitable for "reactive gliosis".
> 
> `a nonspecific reactive change of glial cells in response to damage to the central nervous system (CNS)`

Thanks @pengyubio 
I wonder whether we should expand the definition to include some more details:
"A nonspecific reactive change of glial cells, occurring over several days, in response to damage to the central nervous system (CNS). Reactive gliosis typically involves the proliferation or hypertrophy of several different types of glial cells, including astrocytes, microglia, and oligodendrocytes, and could result in formation of a glial scar (PMID:24462092)." 

> 
> > as well as advise what GOC dbxrefs I should add?
> 
> I am not familiar with GOC dbxrefs. Would you please show me where it is explained? Thanks.

GOC dbxref is an acronym for Gene Ontology Consortium database cross reference. Some GO Consortium member groups can have GOC dbxrefs associated with them. For instance, if new terms are contributed to GO thanks to resources provided by Alzheimer's Research UK (ARUK - our funding body at UCL atm), they will have the reference "GOC:aruk" to acknowledge the funders. This will be displayed as "GOC:aruk" next to the GO term definition in AmiGO or as an acknowledgement in QuickGO (see e.g.: https://www.ebi.ac.uk/QuickGO/term/GO:0150076). GO curators and/or editors can also have GOC dbxrefs associated with them specifically. I am not sure whether GOC has a webpage where these are explained. @vanaukenk perhaps you might know whether there is one? 

Anyhow, going back to my original question, it is not necessary to include a GOC dbxref with every new term. I was just wondering whether perhaps you have a GOC dbxref associated with your project(s) that you might like to link to this new term in addition to the reference associated with ARUK.

**Comment by BarbaraCzub** [comment]
> > a nonspecific reactive change of glial cells in response to damage to the central nervous system (CNS)
> 
> isn't this a phenotype?

Hi @ValWood, Ruth and I had the same question.
@pengyubio commented on this 3 days ago. Please see above.

**Comment by pengyubio** [comment]
> isn't this a phenotype?

It is more of a wording issue. You can change it to something like the following or anything that makes it like a process but not a phenotype.

"A nonspecific reactive change of glial cells ..." -> "a process by which glial cells make nonspecific reactive changes ...".

> as well as advise what GOC dbxrefs I should add?

What about `GOC:YuBioLab`?

> I wonder whether we should expand the definition to include some more details:
> "Reactive gliosis typically involves the proliferation or hypertrophy of several different types of glial cells, including astrocytes, ..."

Adding more details should be fine.

**Comment by BarbaraCzub** [comment]
> > isn't this a phenotype?
> 
> It is more of a wording issue. You can change it to something like the following or anything that makes it like a process but not a phenotype.
> 
> "A nonspecific reactive change of glial cells ..." -> "a process by which glial cells make nonspecific reactive changes ...".
>

Ok, so I will use the following as the definition:
"A process during which glial cells undergo nonspecific reactive changes in response to damage to the central nervous system (CNS). The process occurs over several days and it typically involves the proliferation or hypertrophy of several different types of glial cells, including astrocytes, microglia, and oligodendrocytes, and could result in formation of a glial scar (PMID:24462092)."

> > as well as advise what GOC dbxrefs I should add?
> 
> What about `GOC:YuBioLab`?
> 

Does this dbxref already exist, or does it need to be added to the GOC database? (If it needs to be added, then this request should probably be directed to @kltm ?)

**Comment by ukemi** [comment]
Hi @BarbaraCzub. Please remember the definition should take the form of a necessary and sufficient genus and differentia.

**Comment by BarbaraCzub** [comment]
> Hi @BarbaraCzub. Please remember the definition should take the form of a necessary and sufficient genus and differentia.

Thanks @ukemi, I've modified the suggested definition slightly. 
"A neuroinflammatory response, occurring over several days, during which glial cells undergo nonspecific reactive changes in response to damage to the central nervous system (CNS); typically involves the proliferation or hypertrophy of different types of glial cells (PMID:24462092)."

**Comment by kltm** [comment]
@BarbaraCzub I believe that this is under discussion?
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L3403
Tagging @pengyubio

**Comment by BarbaraCzub** [comment]
Hi @kltm thanks for attaching this link. I have found this file before, but I was not sure whether this was the right/relevant one, because ARUK-UCL is listed in it as 'ARUK-UCL', whereas the dbxref assigned to ARUK-UCL is 'GOC:aruk' (and apparently it matters that 'aruk' is not capitalised). Anyhow, should I use 'GOC:YuBioLab' for a new term requested by the YuBioLab?

**Comment by vanaukenk** [comment]
@BarbaraCzub @kltm @ukemi 

The GOC:aruk is in the users.yaml file:

https://github.com/geneontology/go-site/blob/master/metadata/users.yaml

Do we want to just create an entry for Peng Yu in the users.yaml and assign a GOC xref to use there?

**Comment by kltm** [comment]
@vanaukenk A quick related question here: can an ORCID be used in lieu of an xref for a user?

**Comment by BarbaraCzub** [comment]
> @BarbaraCzub @kltm @ukemi
> 
> The GOC:aruk is in the users.yaml file:
> 
> https://github.com/geneontology/go-site/blob/master/metadata/users.yaml
> 
> Do we want to just create an entry for Peng Yu in the users.yaml and assign a GOC xref to use there?

Thanks, @vanaukenk , for pointing us to this file.  And, yes, my question was whether we can assign a GOC xref for Peng Yu. Wrt to @kltm's question about the ORCID, I agree it is a good idea to use it for individual users. However, I thought that here the GOC ref would be for the whole Peng Yu Lab and/or relating to any project from the Peng Yu Lab. But perhaps I misunderstood? @pengyubio would you like to comment?

**Comment by pengyubio** [comment]
I prefer a GOC ref for my lab.

**Comment by BarbaraCzub** [comment]
Thanks @pengyubio. @kltm please see the comment above. This is intended as a lab/project-wide GOC xref. Could GOC:YuBioLab be added to the users.yaml file?

**Comment by BarbaraCzub** [comment]
I've added the GO term. I'll add the GOC reference, when it becomes available.

**Comment by kltm** [comment]
@BarbaraCzub @pengyubio @vanaukenk After a little back and forth, it looks like the best way forward for now is to go ahead and add `GOC:YuBioLab` as the other current groups in there (e.g. GOC:aruk). If somebody could either prep the PR or add the information in here, we can move forward on that.
Another product of the conversation is that it's perfectly fine to have ORCIDs as URLs in there to mark individual contributions.

**Comment by BarbaraCzub** [comment]
Thanks @kltm What information do you need in order to add GOC:YuBioLab? Presumably @pengyubio would be the best person to provide it?

**Comment by kltm** [comment]
@BarbaraCzub For example, information as here: https://github.com/geneontology/go-site/blob/master/metadata/users.yaml#L612

**Comment by BarbaraCzub** [comment]
Hi @pengyubio, 
Could you please provide @kltm with information needed to create the GOC:YuBioLab cross-reference? Please see the link in the comment above for examples.
I will then be able to update the GO term with your reference and close this issue.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Hi @pengyubio 
I am going to close this issue now. If you'd like to add the GOC xref at a later date, we can re-open it then.
Thanks,
Barbara
