### ISSUE TITLE
obsoletion request cytoplasmic sequestering of protein involved in mitotic DNA replication checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17251]
These are only used to annotate 1 paper by PomBAse (for 14-3-3 proteins)
I would prefer to post compose these
as described here: https://github.com/pombase/curation/issues/2385
(It doesn't really make sense to do it this way anyway)

**Comment by ValWood** [comment]
and
GO:1905507 | cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint

**Comment by pgaudet** [comment]
See also discussion here https://github.com/geneontology/go-ontology/issues/17075

**Comment by pgaudet** [comment]
What about 'GO:1905482 cytoplasmic sequestering of protein involved in G2 DNA damage checkpoint'?

**Comment by ValWood** [comment]
also obsolete...

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

'GO:1905482 cytoplasmic sequestering of protein involved in G2 DNA damage checkpoint' 
'GO:1905481 cytoplasmic sequestering of protein involved in mitotic DNA replication checkpoint' 
'GO:1905507 cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint' 

The reason for obsoletion is that these represent GO-CAM models. The terms have only been used by PomBase. They are no mappings to this term. This term is not in any subset. 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17075
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on May 10th. Unless objections are received by May 10th, we will assume that you agree to this change.

Thanks, Pascale
