### ISSUE TITLE
NTR: Culmorin biosynthetic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#17253]
Accession: GO:xxxxxx
Name: culmorin biosynthetic process
Ontology: biological_process
Synonyms: culmorin anabolism, culmorin biosynthesis, culmorin formation, culmorin synthesis
Definition: The chemical reactions and pathways resulting in the formation of culmorin, a sesquiterpenoid fungal metabolite and mycotoxin produced by some ascomycete species such as  Fusarium culmorum, F. graminearum, F. venenatum and Leptosphaeria oraemaris.
is_a: GO:0043386 ! mycotoxin biosynthetic process
is_a: GO:0051762 ! sesquiterpene biosynthetic process
Source: CHEBI:143197, PMID:19880637, PMID:26673640

**Comment by hdrabkin** [comment]
GO:0106210; done

**Comment by Achchuthan** [comment]
Thanks a lot @hdrabkin
