### ISSUE TITLE
Merge 'GO:0046731 passive induction of host immune response by virus' and children? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17256]
Hello, 

GO:0046731 passive induction of host immune response by virus
is defined as "The unintentional stimulation by a virus of a host defense response to viral infection, as part of the viral infectious cycle." - so that doesn't sound like any gene product is actually doing anything. 

Similar for the children: 
- GO:0046734 passive induction of host cell-mediated immune response by virus
- GO:0046733 passive induction of host humoral immune response by virus
- GO:0046735 passive induction of host innate immune response by virus 

There is a single annotation to this term by SWIE (@milarolo ) to a human protein (which is anyway inconsistent with the term's meaning. 

I propose to obsolete that branch, or merge it into GO:0046730 induction of host immune response by virus

@mgiglio99 @pmasson55 @ValWood 

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
It seems so to me. Although I'm not a viral expert. But you know my opinion- If it isn't clear and isn't used....

**Comment by mgiglio99** [comment]
I agree, these can go. I vote for merging them.

**Comment by pgaudet** [comment]
Hi @mgiglio99 

While doing the merge I noticed that the 'active' form of the terms is now unnecessary: 

- 'induction of host immune response by virus' (1) 
--'active induction of host immune response by virus' (2) 
--- 'active induction of cell-mediated immune response in host by virus' (3) 
--- 'active induction of humoral immune response in host by virus' (4) 
--- 'active induction of innate immune response in host by virus' (5) 


How about if I merged (2) into (1) and removed the 'active' from the term label for terms (3), (4), and (5)?

Thanks, Pascale

**Comment by mgiglio99** [comment]
Sounds good,
Michelle
