### ISSUE TITLE
Merge 'tungstate transmembrane transporter activity' and 'ATPase-coupled tungstate transmembrane transporter activity'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17258]
Hello, 

'GO:1901237 tungstate transmembrane transporter activity'
'GO:1901238 ATPase-coupled tungstate transmembrane transporter activity'

both cite the same papers that refer to ABC transporters, so according to their references, these represent the same activity. 

It sounds like they were created for completeness. I think these should be merged. 

RHEA:32839 is x-referenced in the parent GO:1901237; @amorgat is this correct ? There are no proteins linked to it. As far as I can tell in the literature all tungstate transport is via ABC transporters. 

Maybe @amandamackie you know about this ? 

Thanks, Pascale

**Comment by amorgat** [comment]
@pgaudet well spotted and sorry for the delay!

RHEA:32839 is an oooold reaction, created for the Microme project, with no citations, no cross-references,... gloups! I will obsolete this reaction right now!

The Rhea reaction to consider is RHEA:35027 which is linked EC 7.3.2.6 and 3 Swiss-Prot entries

RHEA:35027    ATP + H2O + tungstate(in) = ADP + H+ + phosphate + tungstate(out) 

Link to Swiss-prot entries: https://www.uniprot.org/uniprot/?query=annotation%3A%28type%3A%22catalytic+activity%22+rhea%3A35027%29&sort=score
