### ISSUE TITLE
mitotic cytokinetic process descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17264]
mitotic actomyosin contractile ring disassembly
cellular bud site selection
mitotic division septum assembly
 mitotic actomyosin contractile ring assembly
cellular bud neck septin ring organization

need to move under:
mitotic cytokinetic process

**Comment by ukemi** [comment]
You must be looking at the spreadsheet. I assume you wan these to be is_a children.

**Comment by ValWood** [comment]
I'm not looking at the spreadsheet yet, I'm processing a  community curation session on cytokinesis...

Next task!

**Comment by ukemi** [comment]
I'm pretty sure some of these are on the spreadsheet. Is is_a correct?

**Comment by ValWood** [comment]
ignore. I think they are already there. The relations I was looking at are part_of
