### ISSUE TITLE
methylcytosine to 5-glyceryl-methylcytosine dioxygenase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17267]
Hi GO,

I would need a new term for an interesting new DNA modification. Please note that the name is not great, but it acts on the same substrate as GO:0070579 with a different product. Any suggestion is welcome

Thanks

Sylvain

Category: Function
Definition: Catalysis of the reaction: methylcytosine + L-ascorbate + O2 = 5-glyceryl-methylcytosine + glyoxylate + CO2.

child of GO:0016705 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

PMID:31043749
Xref Rhea (not yet public) RHEA:60132 and RHEA:60136

**Comment by krchristie** [comment]
@sylvainpoux - I don't have any better suggestions for the term name, so I've just created it as you suggested. If better names arise in the future, it can be changed.

**Comment by ukemi** [comment]
Hi @krchristie in other place we have (x forming) parenthetically in the term name. I wonder if this is more conventional to distinguish.

GO:0043762  - aryl-CoA synthetase (ADP-forming) activity

**Comment by krchristie** [comment]
Possibly, though many of these -forming term names seem to be referring to what form of nucleotide phosphate is produced, particularly when needed to distinguish between multiple options:
- (3R)-3-isopropenyl-6-oxoheptanoate:CoA ligase (ADP-forming) activity
- (3R)-3-isopropenyl-6-oxoheptanoate:CoA ligase (AMP-forming) activity

As I've already committed before seeing your comment @ukemi I'll just leave it as is, but it can be changed if desired.
