### ISSUE TITLE
NTR: photoreceptor specific subsections of TZ

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17273]
This paper has evidence for two novel photoreceptor subdivisions of the transition zone (TZ) which I need for annotation.

> Dharmat R, et al. SPATA7 maintains a novel photoreceptor-specific zone in the distal connecting cilium. J Cell Biol. 2018 Aug 6;217(8):2851-2865. PMID:29899041 (J:264617)

> The  photoreceptor  CC  has  been  classically  defined  as  a  homogenous, elongated structural homologue of  the TZ present in the prototypic  primary  cilium.  Although  composed  of   similar  biochemical modules as the TZ, it is unclear how a structurally elaborate CC is established and maintained within the photoreceptors. In this study, we have identified distinct protein localization patterns within the CC substructure using high-resolution microscopy on mouse models of  photoreceptor ciliopathy. Based on the protein  composition,  we  define  two  novel  CC  zones  (Fig. 7 b):  a  PCC, which is similar to the TZ of  the primary cilium and houses all major TZ complexes (NPHP, MKS, and RPGR), and a DCC zone spanning the distal two thirds of the CC, which is shown to be occupied by SPATA7 interactors. The DCC is structurally unique to the photoreceptor and is maintained by retina-specific ciliopathy protein, SPATA7, and its interacting partners RPGR and RPGRIP1. Loss of these key proteins, particularly SPATA7, leads to mislocalization of DCC proteins, which are essential for photoreceptor sensory cilium stability.  Hence, this region acts as a photoreceptor-specific TZ (PSTZ; Fig. 7 b) within the CC.

Based on this paper, I will add these two terms:

term: photoreceptor proximal connecting cilium
def: The proximal region of the connecting cilium is similar to the transition zone of primary cilia and houses several major transition zone complexes, including NPHP, MKS, and RPGR. [GOC:krc, PMID:29899041]
synonym (related): photoreceptor PCC
synonym (related): PCC

term: photoreceptor distal connecting cilium
def: The distal region of the connecting cilium is structurally unique to the photoreceptor and is maintained by retina-specific protein, SPATA7, and its interacting partners RPGR and RPGRIP1. It is essential for photoreceptor sensory cilium stability. [GOC:krc, PMID:29899041]
synonym (related): photoreceptor DCC
synonym (related): DCC

**Comment by krchristie** [comment]
@ukemi - I opened my own ticket and completed it. Just tagging you to include it in the rota.

**Comment by ukemi** [comment]
Done. Thanks @krchristie
