### ISSUE TITLE
NTR LPS localization to cell outer membrane

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17278]
For https://github.com/geneontology/go-annotation/issues/2338

PMID: 24639492

**Comment by pgaudet** [comment]
@amandamackie

**Comment by pgaudet** [comment]
id: GO:0140334
name: lipopolysaccharide localization to cell outer membrane
namespace: biological_process
def: "A process in which a lipopolysaccharide is transported to the cell outer membrane." [PMID:24639492]
synonym: "LPS localization to cell outer membrane" EXACT []
intersection_of: GO:0033036 ! macromolecule localization
intersection_of: has_target_end_location GO:0009279 ! cell outer membrane
intersection_of: transports_or_maintains_localization_of CHEBI:16412 ! lipopolysaccharide
created_by: pg
creation_date: 2019-05-13T12:23:36Z

**Comment by ValWood** [comment]
Shouldn't this term be

name: lipopolysaccharide (transmembrane) transport to cell outer membrane

-localization is broader and for when it is localized, but not actively transported  but anchored
or localization maintained etc

**Comment by pgaudet** [comment]
so you consider movement from inner membrane to outer membrane, 'transmembrane'? (the LPS goes through the periplasmic space)

**Comment by ValWood** [comment]
> so you consider movement from inner membrane to outer membrane

No, but MFS superfamily are all TM transporters as far as I know. MAybe there are exceptions.
They have usually 10 or 11 TM domains  so It's difficult to reconcile this family with transport across the periplasmic space.

Is this gene product involved in transport across the inner or outer membrane rather than across the periplasmic space.  mostly carriers are involved in transport across lumen, not TM transporters...

**Comment by pgaudet** [comment]
@ValWood This is to annotate lptD and LptE (https://www.uniprot.org/uniprot/P31554)
AFAIK those are not MSF superfamily ?

**Comment by pgaudet** [comment]
Closing. @ValWood please reopen if you still think this is not correct.

**Comment by ValWood** [comment]
OK I must have been looking at the wrong thing.
