### ISSUE TITLE
Merge and change labels: 'glutathione S-conjugate-transporting ATPase activity' and 'glutathione S-conjugate-exporting ATPase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17285]
Hello, 

There are two similar transport terms in the ontology: 

'glutathione S-conjugate-transporting ATPase activity' -> no annotations
'glutathione S-conjugate-exporting ATPase activity' -> EXP annotations to yeast YCF1 @srengel and to TAIR ABCC3 @tberardini 
(All annotations are from 2004)

In fact the activity is to transport glutathione conjugated to a toxic chemical (such as arsenic) 
into the vacuole. 

I will merge the 2 terms and change the label to 'glutathione S-conjugate transmembrane transporter activity' 

Thanks, Pascale

**Comment by tberardini** [comment]
@pgaudet  Thanks for the notification.  Which direction are you merging?  Transporting into exporting or exporting into transporting?

**Comment by pgaudet** [comment]
transporting. 
Exporting should be a BP. 
(an in this case it's transmembrane transport into the vacuole- 
I prefer that phrasing because itherwise we could have 'export into the vacuole' or 'import into the vacuole'... 

Thanks, Pascale

**Comment by tberardini** [comment]
So, you are keeping the  'transporting' ID and changing that label.  Ok, I think our software *should* transfer the annotation accordingly.  If there are few enough annotations, I can do the transfer manually.  The merge makes sense.

**Comment by srengel** [comment]
this is fine, so i think i don't have to do anything, right?

**Comment by pgaudet** [comment]
No action needed unless you disagree or you would like a new term. Sounds like we're all OK. 

I can keep the ID for the exporter, since annotations are to that term. Anyway the term label will be changed to ATP-coupled glutathione S-conjugate transmembrane transporter activity. 

Thanks for the quick response ! 

Pascale
