### ISSUE TITLE
Merge GO:0010175 sphingosine transmembrane transporter activity into -> GO:0140338 sphingomyelin transfer activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17304]
Hello, 

As far as I can tell, sphingolipids are not known to be transported across a membrane - see  PMID:25382749 (https://onlinelibrary.wiley.com/doi/full/10.1111/tra.12239)

>  Post‐Golgi vesicular trafficking of sphingolipids
After SM and GSLs are synthesized within the lumen of the Golgi and the TGN, these lipids are transported to the PM. These lipids are then endocytosed and either targeted for degradation in lysosomes or recycled back to the PM. These transport steps are thought to depend on vesicle trafficking systems that are defined by secretory and endocytic proteins. 

Does anyone know of a transmembrane transport route for sphingolipids ? 

If not I will obsolete the term. 

Thanks, Pascale

**Comment by ValWood** [comment]
Only from Googling so not looked in detail but this protein

is Major Facilitator superfamily
https://www.uniprot.org/uniprot/Q91VM4#family_and_domains

https://and described  as a sphingolipid transporter

**Comment by pgaudet** [comment]
I see it's a Sphingosine-1-phosphate transporter - maybe I should change the term label ?

**Comment by marcfeuermann** [comment]
Sphingosine-1-phosphate (S1P) is an important secreted lipid mediator involved in angiogenesis and immunity, and deserves a change of the term label. Within cells, it mostly travels on vesicles, but the mechanism of secretion is not clear.  S1P seems also to be exported by ABCA1 (which exports cholesterol) and is associated with HDL in the blood. So the secretion mechanisms for both lipids are probably similar. These non-soluble compounds bind to lipoproteins such as ApoE. So transmembrane transport cannot be ruled-out. As for cholesterol transport, needs further literature reading and probably advice from an expert.
