### ISSUE TITLE
NTR: 4-hydroxybutyrate receptor

### ISSUE THREAD

**Issue by magrane** [geneontology/go-ontology#17318]
New term requested: 4-hydroxybutyrate receptor activity

Synonym: gamma-hydroxybutyrate receptor activity

PMID: 17197387

Thanks,
Michele

**Comment by ukemi** [comment]
Hi @magrane. I'm making it a GPCR based on the paper. Let me know if you think this is too specific.

**Comment by magrane** [comment]
I think that making it a GPCR would be too specific. Although PMID:17197387 says that it is a GPCR, the corresponding UniProt record, Q9HAB3, doesn't contain any GPCR-specific InterPro signatures and the sequence has >7 transmembrane domains.

**Comment by ukemi** [comment]
OK. I will revise. Thanks!
