### ISSUE TITLE
NTR: endocytosis, site selection

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17315]
The process of selecting and or marking the position where  endocytosis will occur.

descendent of
part_of GO:0006897    endocytosis

ref PMID:30044717

**Comment by krchristie** [comment]
@ValWood - An is_a parent is required. Can you propose one?

**Comment by ValWood** [comment]
Looking at
https://www.ebi.ac.uk/QuickGO/term/GO:0007105

maybe an "endocytic process"term is also required?

There do not seem to be any other parts of endocytosis described. All the other terms are *types* of endocytic process. For example, membrane invagination is only a narrow synonym of endocytosis.....

**Comment by pgaudet** [comment]
Right ! This is a place where we are inconsistent. 
For example we have 'apoptotic process' but not apoptosis ...

**Comment by krchristie** [comment]
I don't think we would need an 'endocytic process' term in addition to an 'endocytosis' term. In the case of 'apoptotic process' that @pgaudet mentioned, we only have the 'apoptotic process' term with 'apoptosis' as a narrow synonym.

Also, the QuickGO page for 'endocytosis' https://www.ebi.ac.uk/QuickGO/term/GO:0006897
shows several part_of child terms, listed here:

Child Term | Relationship to GO:0006897
-- | --
GO:0099051                vesicle scission involved in endocytosis | part_of
GO:0006911                phagocytosis, engulfment | part_of
GO:0006910                phagocytosis, recognition | part_of
GO:0038024                cargo receptor activity | part_of

**Comment by krchristie** [comment]
Looking at the is_a parentage of existing terms site selection terms like 'cellular bud site selection', 'cytokinesis, site selection', or 'division septum site selection' is not informative as to a possible is_a parentage of the term you request.

What do you think of this term for an is_a parent?:
**establishment of protein localization to plasma membrane (GO:0061951)**

**Comment by ValWood** [comment]
That could work.

**Comment by krchristie** [comment]
I also notice the term 'endocytic patch', which is defined as a 'cell cortex part'. Should your new term instead be some sort of localization to the cortex? or have some relationship to the CC term 'endocytic patch'?

Please advise what you think seems best.

> [Term]
> id: GO:0061645
> name: endocytic patch
> namespace: cellular_component
> def: "The part of the cell cortex consisting of  an aggregation of proteins that will give rise to an endocytic vesicle." [GOC:dph, PMID:22949647]
> is_a: GO:0044448 ! cell cortex part
> created_by: dph
> creation_date: 2014-09-02T09:23:38Z

**Comment by ValWood** [comment]
I'm not sure. It's actually at the cell division site, and the  protein which does the site selection is phospholipid binding so it is membrane attached. If this is tricky I can just go with endocytosis. I wanted to capture the 'site selection' because I hadn't seen it before but e wcan wait iuntil the process is clearer to add the term A MF might turn out to be more appropriate...

**Comment by ValWood** [comment]
ok I'll close, and revisit in the future...

**Comment by krchristie** [comment]
Rather than not add the 'site selection' term, how about selecting a less specific is_a parent, perhaps one of these:
- 'protein localization to cell periphery' (parent term of both 'pl to plasma membrane' and 'pl to cell cortex'
- 'cellular protein localization' (parent term of 'protein localization to cell periphery')

**Comment by ValWood** [comment]
OK good plan let's use:

'protein localization to cell periphery' (parent term of both 'pl to plasma membrane' and 'pl to cell cortex'
