### ISSUE TITLE
Flippases/floppases synonyms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17323]
Suggestion from @deustp01 

To help curators and users deal with variable usage by authors, maybe add something to indicate direction to the term names themselves:
"flippase (inward translocation) activity"
"floppase (outward translocation) activity"

@ukemi is it OK to have parentheses in term labels ?

**Comment by ukemi** [comment]
D-glutamate(D-aspartate) oxidase activity, GO:0047819
L-cystine L-cysteine-lyase (deaminating), GO:0044540

**Comment by pgaudet** [comment]
@marcfeuermann @deustp01 @ValWood 

What do you think - should we add this only to the parent class (flippase/floppase), or to all terms ?

**Comment by marcfeuermann** [comment]
I think inward and outward is still confusing. Flippase activity is transport from exocytoplasmic compartment to cytoplasm, so inward for plasma membrane, but outward for Golgi membrans, ER, ...
For floppase it is the reverse. I'm not convinced that curators will always check the parent terms, so adding this only to the parents will probably not be really useful.

**Comment by pgaudet** [comment]
Right, inward/outward is not meaningful for membranes other than the plasma membrane. I will add synonyms such as: 
- floppase activity (cytosolic to exoplasmic leaftlet) 
- flippase activity (exoplasmic to cytosolic leaftlet) 

to all terms.

**Comment by marcfeuermann** [comment]
Fine for me.

**Comment by pgaudet** [comment]
+ add synonyms 'x translocase activity'
