### ISSUE TITLE
Changes to 'GO:0120013 intermembrane lipid transfer activity' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17330]
Hello, 

While fixing annotations to lipid transport (https://github.com/geneontology/go-annotation/issues/2357), we noticed that the definition of 'intermembrane lipid transfer activity' is too narrow, because there is a very similar activity that transfers lipids from lipoparticles (like LDL and HDL), that are not bound by *membranes*, but rather by lipid monolayers. 

So for GO:0120013 intermembrane lipid transfer activity' and children I will 
- remove 'intermembrane' from the main term label and add it as a narrow synonym
- change the definition from "Enables the removal of a lipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane" 
to "Removes a lipid from a membrane or a monolayer lipid particle, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to an acceptor membrane or lipid particle."

Tagging @krchristie since she had added many of these terms 2 years ago. 

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet - Sounds like appropriate changes to accommodate advances in the field.

**Comment by pgaudet** [comment]
Great, thanks !

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/issues/17327
