### ISSUE TITLE
Obsoletion notice: nucleosome mobilization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17338]
GO:0042766    nucleosome mobilization
exact synonym "nucleosome sliding" 
is not related to 

GO:0016584    nucleosome positioning

(neither has localization)

I was looking because I saw this:

  | Levendosky RF, Bowman GD. | Related Articles

  | Asymmetry between the two acidic patches dictates the direction of nucleosome sliding by the ISWI chromatin remodeler.
  | Elife. 2019 May 16;8. [Epub ahead of print]
  | PMID: 31094676

**Comment by vanaukenk** [comment]
@ValWood  Can you please clarify what edits you'd like?
Are you asking for a grouping term such as 'nucleosome localization' that would be a parent of both 'nucleosome mobilization' and 'nucleosome positioning'?  It could perhaps be under 'protein-containing complex localization'.
Thx.

**Comment by ValWood** [comment]
In addition, if "nucleosome sliding" is an exact synonym of "nucleosome mobilization",  should 
"nucleosome mobilization" be a descendant of "nucleosome positioning" ?

**Comment by ValWood** [comment]
Probably txn group should discuss this as part of the chromatin remodelling processes and activities

**Comment by pgaudet** [comment]
We'll obsolete 'nuclesome mobilization' in favor of the new MF terms  'GO:0140751 histone octamer slider activity' and 'GO:0140750 nucleosome array spacer activity'.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made by the Transcription working group to obsolete GO:0016584 nucleosome positioning. The reason for obsoletion is that this should be captured as a molecular function, either 'GO:0140658 ATP-dependent chromatin remodeler activity' or a child, 'GO:0140751 histone octamer slider activity' or 'GO:0140750 nucleosome array spacer activity'.

There are 53 annotations to this term, see 
https://github.com/geneontology/go-annotation/issues/4026


    22 CPX annotations
    16 FlyBase
    1 PomBase - removed
    14 SGD

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/17338

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 3, 2022. Unless objections are received by February 3, we will assume that you agree to this change.

**Comment by hattrill** [comment]
FB done!
