### ISSUE TITLE
add synonyms to : GO:0044409 entry into host

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17341]
we were looking for a term for host penetration. Found lots of terms but couldn't locate this"

GO:0044409  entry into host

could we add exact synonyms
"penetration into host"
and host penetration""

also 

GO:0052066    entry of symbiont into host cell by promotion of host phagocytosis

GO:0075052    entry into host via a specialized structure
exact synonym host penetration  via a specialized structure
etc

**Comment by krchristie** [comment]
@ValWood - Am I reading this correctly that this ticket is only about requesting synonyms for existing terms, but is not actually requesting any new terms?

**Comment by ValWood** [comment]
Yes sorry it started as a new term request, but then we located the term but I didn't change the title.

**Comment by krchristie** [comment]
great. thanks for confirming!

**Comment by krchristie** [comment]
@ValWood - Here is the link to see what I've added so far. The pull request is already in progress, but if there is anything else you want, add specifics to this ticket and I'll add them too.

https://github.com/geneontology/go-ontology/pull/17346/files

**Comment by krchristie** [comment]
Also, when I added the 'synonym' label, I assumed you wanted the 'PomBase' label and added it also. Feel free to remove it if that was an incorrect assumption.
