### ISSUE TITLE
regulation of mitochondrial translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17345]
@pgaudet  the one we just discussed, is this because  the LD "regulates some process", rather than  "regulates some translation" could you re-check for me?

**Comment by pgaudet** [comment]
The LD is

biological_process
and regulates some mitochondrial translation

Pascale

**Comment by ValWood** [comment]
and should annotation currently be transitive over this? @ukemi  ?

**Comment by ukemi** [comment]
I'm not sure about exactly what you mean. It depends on whether or not you have closure over regulates when computing annotations.

**Comment by ValWood** [comment]
We do....but this  isn't mapping to translation. 

Ignore for now, I want to check with Kim that we picked up the new GO after some recent owl tool fixes first...

**Comment by ValWood** [comment]
A bit more information

"regulation of mitochondrial  translation" does become annotated to "mitochondrial translation"

However it isn't annotated to "mitochondrial gene expression" which is a parent of "mitochondrial translation".

(mitochondrial gene expression is our slim term)

Does that help?

**Comment by ValWood** [comment]
@kimrutherford checked the owltools output and there is no inferred relationship between "regulation of mitochondrial translation" and "mitochondrial gene expression".

Is this intentional? there should be one...

**Comment by pgaudet** [comment]
@balhoff Maybe you can help ?

**Comment by balhoff** [comment]
It looks like 'mitochondrial translation' is 'part of' 'mitochondrial gene expression' rather than subclass. We took out the chain `regulates o part_of -> regulates` (see #12344). However this chain is still active during classification of the ontology for release. So 'regulation of mitochondrial translation' is inferred to be a subclass of 'regulation of gene expression.' If there were such a term as 'regulation of mitochondrial gene expression', I would expect it to be inferred under that as well (at least until we completely get rid of the property chain).

**Comment by pgaudet** [comment]
@ValWood what is the action here ?

**Comment by ValWood** [comment]
add
'regulation of mitochondrial gene expression'
between
regulation of  gene expression
and
regulation of mitochondrial translation

and the issue will go away.
v

**Comment by ukemi** [comment]
@balhoff, do you think I should go ahead and assert these now since the property chain will go away at some point and we will want to assert all of the ones on the spreadsheet?

**Comment by ValWood** [comment]
How long will this be until the inferences are fixed?. It also seems to affect our inferences vi FYPO.

**Comment by ukemi** [comment]
They should be fixed. These inferences are created during the release process and then the chains are removed. I am pretty sure when I looked in Protege they were there.
