### ISSUE TITLE
glucosylceramide/galactosylceramide translocating activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17342]
children of 

GO:0034202 | glycolipid-translocating activity
-- | --

reference PMID:30530492

**Comment by pgaudet** [comment]
How many more do you figure we'll need ? 

How about creating a 'glycoceramide flippase activity' to cover all these ? 
@marcfeuermann points out that we may end up with many different specific compounds. 

Thanks, Pascale

**Comment by ValWood** [comment]
glycoceramide sounds good.

OR I Could use CHEBI. Some specificity might be quite useful though.

**Comment by pgaudet** [comment]
[Term]
id: GO:0140351
name: glycosylceramide flippase activity
namespace: molecular_function
def: "Catalysis of the movement of glycosylceramide from the exoplasmic to the cytosolic leaftlet of a membrane, using energy from the hydrolysis of ATP. Glycosylceramides are ceramides containing a functional group derived from a sugar." [PMID:30530492]
synonym: "galactocerebroside flippase activity" NARROW []
synonym: "galactosylceramide flippase activity" NARROW []
synonym: "glucosylceramide flippase activity" NARROW []
synonym: "glycoceramide flippase activity" EXACT []
intersection_of: GO:0140327 ! flippase activity
intersection_of: transports_or_maintains_localization_of CHEBI:62941 ! glycosylceramide
created_by: pg
creation_date: 2019-05-20T13:29:48Z

**Comment by pgaudet** [comment]
I've added the other terms as synonyms. Using ChEBI seems like a good idea. 

Thanks, Pascale
