### ISSUE TITLE
NTR: transport across blood-brain barrier

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#17362]
As a part for the next ARUK-UCL annotation project, we are focusing on maintenance of and transport across the blood-brain barrier (BBB). 

There is currently no GO term for 'transport across blood-brain barrier' and we would like to add it to group all the different types of transport across the blood-brain barrier that currently have specific GO terms representing them in GO. 

The reference for this GO term will be [PMID:29377008](https://www.ncbi.nlm.nih.gov/pubmed/29377008) (Nat Rev Neurol. 2018 Mar;14(3):133-150. doi: 10.1038/nrneurol.2017.188. Epub 2018 Jan 29.
Blood-brain barrier breakdown in Alzheimer disease and other neurodegenerative disorders.
Sweeney MD1, Sagare AP1, Zlokovic BV1.).

I would like to use 'GO:0070633 transepithelial transport' as the parent term. The BBB consists of capillary endothelial cells (a type of epithelial cell: ([https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115)).

cc @RLovering

**Comment by pgaudet** [comment]
Good idea. We do have a few children but no grouping term: 

GO_1990379 'lipid transport across blood-brain barrier' 
GO_0097716 'copper ion transport across blood-brain barrier' 
GO_1990962'xenobiotic transport across blood-brain barrier' 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet. However, based on the [UBERON entry for blood brain barrier](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000120), I think the parent term here needs to be 'GO:0006810 transport', and not 'GO:0070633 transepithelial transport' like I initially suggested.
Thanks,
Barbara
