### ISSUE TITLE
NTR: calpain complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17365]
Name: calpain complex
Def: A calcium-dependent protease complex that processes its substrate by limited proteolysis rather than degrading it. In some cases limited proteolysis is required for the activation of its substrate.
Reference:
PMID:10639123
Synonyms:
M-caplain [NARROW]
mu-calpain [NARROW]
GOCID:bhm

Logical definitions:
is_a GO:1905369 endopeptidase complex
part_of GO:0005737 cytoplasm
enables GO:0004198 calcium-dependent cysteine-type endopeptidase activity
enables GO:0005509 calcium ion binding
involved_in GO:0006508 proteolysis

**Comment by vanaukenk** [comment]
Added term, but note change in relations:

enables -> 'capable of'
involved_in -> 'capable of part of'
