### ISSUE TITLE
Merge GO:0103095 wax ester synthase activity into GO:0047196 long-chain-alcohol O-fatty-acyltransferase activity ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17361]
Hi @hdrabkin 

This is a GOC:pz reaction - the new term (GO:0103095) has the same EC as GO:0047196 and a very similar definition. Should we merge them ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
But if the metacyc ids are different I'd check with her first; Is the EC in RHEA? do they list more than one reaction mapping to the EC?
We WILL run into this where several GO terms can have the same EC id but different RHEAs.

**Comment by pgaudet** [comment]
Are we aiming to represent all RHEA ? I thought we only wanted the generic reaction.

**Comment by hdrabkin** [comment]
I also see that the  MetaCyc:XNQT-4193 resolves at Metacyc to  MetaCyc:2.3.1.75-RXN
So perhaps basically these two are the same thing. I 'll see if I can get Peifen's input.

**Comment by pgaudet** [comment]
Great.

**Comment by peifenz** [comment]
The difference between the two GO terms is the carbon length of the substrate alcohol. Long-chain alcohol (C16 and C18) is in GO:0047196 however the optimum length of C20 was indicated in EC 2.3.1.75 and in the reference for that EC number. Very long chain alcohol (C20 and longer) is in GO:0103095. What is the chain length indicated in the RHEA reaction?

**Comment by hdrabkin** [comment]
Unspecified
RHEA:38443: a long chain fatty alcohol + an acyl-CoA = a wax ester + CoA
This was picked and added to GO:0103095 using the cross ref EC:2.3.1.75 that was supplied, to RHEA

**Comment by hdrabkin** [comment]
Again, the metacyc id you supplied for GO:0103095 seems to be the same as the one for GO:0047196

**Comment by hdrabkin** [comment]
Rhea came from here
https://www.rhea-db.org/searchresults?q=EC%3A2.3.1.75

**Comment by deustp01** [comment]
And the abstract of the cited paper only mentions tests of 18- and 20-carbon acyl CoAs so there's little there to support conclusions about the chain-length preference of the enzyme, if any (and Rhea does not specify).

**Comment by peifenz** [comment]
What is the metacyc reaction ID for GO:0103095 (I left my old job almost a year ago so I no longer have access to my files), RXNQT-4193? If so, then it is different from 2.3.1.75-RXN in GO:0047196. Anyways, I think it is better to remove EC number 2.3.1.75 from GO:0103095. The metacyc reaction 2.3.1.75-RXN is for the EC 2.3.1.75. I am also OK to merge the two GO terms.

**Comment by hdrabkin** [comment]
But when I enter RXNQT-4193 in the metacyc search I got back the same page that the 2.3.1.75-RNX

**Comment by peifenz** [comment]
That was strange. Using the quick search box on metacyc, I get this page: 
https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=RXNQT-4193

**Comment by hdrabkin** [comment]
Yes, and that is the same page that you get if you input 2.3.1.75-RXN

**Comment by hdrabkin** [comment]
So would you agree that the RHEA def would be ok for this term? Remember that the RHEA will be used to populate the text definition (RHEA:38443: a long chain fatty alcohol + an acyl-CoA = a wax ester + CoA), and that is what will be used to construct logical defs (because RHEA uses the CHEBI names).

**Comment by peifenz** [comment]
This page is for 2.3.1.75-RXN:

https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=2.3.1.75-RXN

The RHEA def is very similar to the EC def and is cross-ref EC2.3.1.75, so works fine.

**Comment by hdrabkin** [comment]
@pgaudet I will merge this before leaving for vacation today; do you have a preference for the primary term id?

**Comment by pgaudet** [comment]
Long chain seems more neutral, what do you think?

Le ven. 24 mai 2019 à 4:58 PM, Harold Drabkin <notifications@github.com> a
écrit :

**Comment by hdrabkin** [comment]
yes I think so too; actually I didn't think you were around so I just did it

**Comment by hdrabkin** [comment]
All done; heading out for vacation!
