### ISSUE TITLE
Merge helicase and ATP-dependent helicases

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17371]
Hello, 

There is no ATP-independent helicase. A grouping term had been created in case a GTP-dependent helicase existed, but this is not yet the case. So to simplify the ontology I propose to merge the following terms:

Term | Merge into 
-- | --
GO:0033680 ATP-dependent DNA/RNA helicase activity | GO:0033677 DNA/RNA helicase activity
GO:0033681 ATP-dependent 3'-5' DNA/RNA helicase activity | GO:0033679 3'-5' DNA/RNA helicase activity
GO:0033682 ATP-dependent 5'-3' DNA/RNA helicase activity | GO:0033678 5'-3' DNA/RNA helicase activity
GO:0004003 ATP-dependent DNA helicase activity  | GO:0003678 DNA helicase activity
GO:0043140 ATP-dependent 3'-5' DNA helicase activity | GO:0043138 3'-5' DNA helicase activity
GO:0043141 ATP-dependent 5'-3' DNA helicase activity | GO:0043139 5'-3' DNA helicase activity
GO:0004004 ATP-dependent RNA helicase activity | GO:0003724 RNA helicase activity
GO:0034459 ATP-dependent 3'-5' RNA helicase activity | GO:0034458 3'-5' RNA helicase activity
GO:0032575 ATP-dependent 5'-3' RNA helicase activity | GO:0032574 5'-3' RNA helicase activity
GO:1990163  ATP-dependent four-way junction helicase activity |  GO:0009378  four-way junction helicase activity
GO:0008026 ATP-dependent helicase activity |  GO_0004386 helicase activity
GO:1902449 regulation of ATP-dependent DNA helicase activity | GO:1905774 regulation of DNA helicase activity
GO:1902451 negative regulation of ATP-dependent DNA helicase activity | GO:1905775 negative regulation of DNA helicase activity
GO:1902451 positive regulation of ATP-dependent DNA helicase activity | GO:1905776 positive regulation of DNA helicase activity

Remove 'ATP-dependent' from the following terms: 
----

 - [x]  'double-stranded DNA-dependent ATP-dependent DNA helicase activity'
 - [x] 'single-stranded DNA-dependent ATP-dependent DNA helicase activity'
 - [x] 'single-stranded DNA-dependent ATP-dependent 3'-5' DNA helicase activity'
 - [x] ' regulation of ATP-dependent RNA helicase activity
 - [x] ' negative regulation of ATP-dependent RNA helicase activity

Thanks, Pascale

**Comment by ValWood** [comment]
1 Will the helicases still de defined as "ATP dependent" even though it isn't in the term name?

2. Why have "DNA-dependent" for  a DNA helicase. Isn't that a given?

**Comment by pgaudet** [comment]
> Will the helicases still de defined as "ATP dependent" even though it isn't in the term name?

Yes 

> Why have "DNA-dependent" for a DNA helicase.

God point. I'll remove that too. 

Thanks!
