### ISSUE TITLE
reactome_xrefs_import references to alt_ids

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#17387]
We recently had a PR failure resulting from one term being merged into another term, when there was a reactome xref to the GO term which became an alt_id.

Having these annotations on alt_ids caused these annotation axioms to be stored in the owl-axioms section in the OBO output, violating one of the makefile checks.

Because the PR needed to be merged in order to fix errors already committed to the master branch, I manually removed these xrefs from the reactome_xrefs_import. I also disabled the makefile trigger which causes the reactome import to be rebuilt automatically.

How should we deal with references to alt_ids in the reactome mapping? The current procedure uses dosdp-tools and is nice and declarative.

cc @cmungall @goodb

**Comment by pgaudet** [comment]
@balhoff is manually replacing the alt_ids in the reactome_import file a good solution for now ? I can add to the documentation.

**Comment by balhoff** [comment]
Yes I think that is all we can do right now until we have an automatic solution.

**Comment by pgaudet** [comment]
OK. Just to be sure - this file is NOT the main mapping file, right ? We only edit it so that the Travis checks dont give errors, is this right ?

**Comment by balhoff** [comment]
This is the source of the xrefs that end up in the ontology. It is merged during the release. So mappings that are deleted are gone until this file is fully rebuilt. For that reason the change you made (replacing the merged term with the current ID) is better than what I did at first (deleting the mapping).

**Comment by goodb** [comment]
Another thing that should happen here is to alert @deustp01 and the Reactome team that they are using deprecated ontology terms.  If they fix that within Reactome, the problem ought to clear itself up automatically.  (though our build should of course handle the interim more gracefully).

**Comment by pgaudet** [comment]
@deustp01 Does Reactome automatically maps secondary IDs to Primary Ids? Same question for obsoletes. 
ie do you need notifications, or do you have an internal process?

**Comment by pgaudet** [comment]
Ontology editors documentation added : http://wiki.geneontology.org/index.php/Merging_Ontology_Terms

**Comment by deustp01** [comment]
(Some of this repeats an e-mail sent to Pascale Monday 5/27).

We maintain a local copy of GO, essentially flat lists of GO CC, MF, and BP terms directly accessible via our annotation tool. That copy is updated at the start of the process to generate each new release of Reactome material. Releases are done every three months; the update happens about a month before the release becomes public so our GO term usage lags the latest version of GO by a month on the day of a new release and by about four months on the day before that release is superseded.

The update process consists of looking up each local GO term in the latest released (not daily snapshot) GO-obo file http://current.geneontology.org/ontology/go.obo. The local record is updated to resolve any discrepancies. If a local term has become obsolete and the term has not been used in any annotations, the term is simply deleted. If the term has been used for annotations, that fact is logged and the relevant curators are asked to re-annotate using a currently valid term:

Reactome   Instance | Obsolete Term | Suggested action | New/replacement GO Terms | Curator
-- | -- | -- | -- | --
[GO_MolecularFunction:1042335]   obsolete transcription factor activity, sequence-specific DNA binding, RNA   polymerase recruiting | 1011 | Manual cleanup (referrers   exist) | N/A | Naithani,   Sushma (Plant)
[GO_MolecularFunction:81747]   obsolete antibiotic transmembrane transporter activity | 42895 | Manual cleanup (referrers   exist) | N/A | Augustin   (Bijay)
[GO_MolecularFunction:3173]   obsolete protein transporter activity | 8565 | Manual cleanup (referrers   exist) | N/A | Bijay,   Marc
[GO_MolecularFunction:5433173]   obsolete cyclic pyranopterin monophosphate synthase activity | 61597 | Manual cleanup (referrers   exist) | N/A | Amarasinghe,   Vindhya (Plant)
[GO_BiologicalProcess:20632]   obsolete protein import into nucleus, translocation | 60 | Manual cleanup (referrers   exist) | N/A | Lisa
[GO_MolecularFunction:357978]   obsolete glycoprotein transmembrane transporter activity | 34437 | Manual cleanup (referrers   exist) | N/A | Bijay
[GO_MolecularFunction:383460]   obsolete purine NTP-dependent helicase activity | 70035 | Automatic Deletion (no   referrers) | N/A |  
[GO_MolecularFunction:383813]   obsolete GTP-dependent helicase activity | 70036 | Automatic Deletion (no   referrers) | N/A |  

If a local term has been replaced, secondary and primary identifiers are used to automatically patch annotations

DB_ID | Primary   accession | Primary   Class | DB_ID   (Secondary; to be deleted) | Secondary   accession (to be deleted) | Secondary   Class | Referrers to be redirected to Primary accession
-- | -- | -- | -- | -- | -- | --
5263430 | 1902599 | GO_BiologicalProcess | 25833 | 15906 | GO_BiologicalProcess |  
13288 | 15297 | GO_MolecularFunction | 8857217 | 99516 | GO_MolecularFunction |  
4240 | 15267 | GO_MolecularFunction | 258560 | 22838 | GO_MolecularFunction | [CatalystActivity:432020] substrate-specific channel   activity of AQP7 tetramer [plasma membrane]; [CatalystActivity:432043]   substrate-specific channel activity of AQP9 tetramer [plasma membrane];   [CatalystActivity:432058] substrate-specific channel activity of AQP3   tetramer [plasma membrane]; [CatalystActivity:432044] substrate-specific   channel activity of AQP10 tetramer [plasma membrane]
10390 | 5381 | GO_MolecularFunction | 5691722 | 97689 | GO_MolecularFunction |  
81778 | 42910 | GO_MolecularFunction | 3162 | 15238 | GO_MolecularFunction | [CatalystActivity:9639422] drug transmembrane   transporter activity of smvA [plasma membrane]
258384 | 60090 | GO_MolecularFunction | 262491 | 32947 | GO_MolecularFunction |  
3295321 | 61513 | GO_MolecularFunction | 24904 | 8524 | GO_MolecularFunction |  
9644986 | 140312 | GO_MolecularFunction | 5634446 | 98748 | GO_MolecularFunction |  
6265 | 9977 | GO_MolecularFunction | 24092 | 15557 | GO_MolecularFunction |  

Any new GO terms in GO-obo not in the local copy are added.

The Reactome GAF and the mapping file that pairs GO MF terms with the stable IDs of Reactome reactions that use those terms (used to make the GO MF to Reactome xrefs that set off this ticket) are generated at release time, so typically about a month after the update.

@jweiser, am I missing anything

**Comment by jweiser** [comment]
@deustp01 I don't think so.  That's a good summary.

**Comment by balhoff** [comment]
The plan is to handle this with some enhancements to `robot repair`, which would run during the build pipeline: https://github.com/ontodev/robot/issues/492#issuecomment-500489213
