### ISSUE TITLE
NTR: different RNA capping mechanism, decapping

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#17383]
In addition to the well-known RNA capping of eukaryotic pol II transcripts, it turns out that different cap modifications on RNA (NAD, dephospho-CoA) also exist in prokaryotes.  However, the mechanism for incorporation of the cap modification is different; here, they are incorporated as "non-canonical initiating nucleotides" at transcription initiation (PMID 27383794, 29681497).  This is in fact not specific to prokaryotes; it also happens in yeast, PMID 27383794.

To me, the existing "RNA capping" term GO:0036260 definitely sounds broad enough to accommodate this process, but its definition would currently be too specific.  The specific cap structures described above could be added as child terms to GO:0036260.

Decapping of NAD-modified RNAs should also get a GO term (as a MF, because it is only one step?); it's a hydrolase, NadC in E. coli (PMID 25533955, 27428510).

Cheers,
Ingrid

**Comment by vanaukenk** [comment]
@keseler 

I agree that the current definition of 'RNA capping' GO:0036260 should now be made more general to accommodate other mechanisms of RNA capping and other species.

For the more specific child terms for NAD and dephospho-CoA capping, what bacterial gene products would you annotate?  RNAP subunits?  Can you suggest definitions for these terms?

For RNA decapping, we do currently have BP terms for decapping (e.g. deadenylation-dependent decapping of nuclear-transcribed mRNA GO:0000290) but I'd like to confirm with the GO editors on whether an enzyme like the NudC hydrolase should just get an MF annotation for this or also a BP decapping annotation.  A BP annotation to some type of RNA processing term seems warranted.

Side note: NudC is a nice example of a homodimeric emergent function. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5003112/

**Comment by sylvainpoux** [comment]
Hi,
apparently both Ingrid @keseler and me requested GO terms for the same pathway. For information, the addition of NAD-cap is not so clear in eukaryotes, and it looks like that at least some NAD-cap is added post-transcriptionally, since a number of snoRNAs that are produced post-transcriptionally have a NAD-cap (PMID:28283058)

Please also note that there are 2 different mechanisms for NAP-decapping in eukaryotes, with two different reactions, one forming NMN and one forming NAD (PMID:28283058, PMID:31101919)

**Comment by vanaukenk** [comment]
Closing this ticket, as the remaining work has been done in #17594, save adding Rhea xrefs when they become public.
@keseler - I think we've added most of what can be added at this point, but please let me know if you have any additional questions/comments.  Thx.
