### ISSUE TITLE
obsolete GO:0044044    interaction with host via substance in symbiont surface

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17389]
this seems to be describing binding and isn't a process.

All annotations are CAFA.

One example
The role of anchorless proteins on the surface of most pathogenic microorganisms has long been studied in context to their interactions with multiple host proteins, facilitating the dissemination of pathogen within the host tissues. In order to gain more insights into anthrax pathogenesis, we hereby report the presence of a prominent moonlighting enzyme, Glyceraldehyde-3-phosphate dehydrogenase (GAPDH) on the surface and in the extracellular medium of Bacillus anthracis. Out of the three heterologously expressed recombinant isoforms, rGapA (334 amino acids in native form; GapA) showed a significant NAD+ mediated GAPDH activity, whereas rGapB (342 amino acids in native form; GapB) showed a slight activity with NADP+. The rGapN (479 amino acids in native form; GapN) was enzymatically inactive with either NAD+ or NADP+. GapA was ascertained to be present in the extracellular medium and on the surface of B. anthracis. On the other hand, GapN was absent from both the surface and extracellular medium, whereas GapB was scarcely present on the surface of B. anthracis. Human plasminogen predominantly interacted with the rGapA isoform at physiological concentrations and the interaction was found to be lysine dependent. Immunization with rGapA resulted in a significant protection upon challenge with Bacillus anthracis in the murine model.

is just describing an interaction. Others seem to be similar (or different!) but just binding.

**Comment by ValWood** [comment]
maybe a molecular function term is required for

"host binding to symbiont antigen" or similar?

associated processes seem to be largely unexplored or activation of some immune system pathway.

**Comment by pgaudet** [comment]
Maybe 'host protein binding to symbiont protein'?

**Comment by ValWood** [comment]
that would work. 
We don't absolutely need this term because  protein binding taxon A protein binding taxon B works too.....mainly we need to get rid of the process term.

**Comment by pgaudet** [comment]
It would be interesting to know what exactly people were trying to capture. For example PMID:19848587

> Streptococcus suis serotype 2 (SS2) has evolved into a highly infectious entity, posing a great threat to public health. Screening for and identification of protective antigens plays an important role in developing therapies against SS2 infections.
Multiple strategies were used to investigate a new surface protein that has the potential to be a protective antigen. These strategies included molecular cloning, biochemical and biophysical analyses, enzymatic assay, immunological approaches (eg, immunoelectron microscopy), and experimental infections of animals.
We identified an enolase gene from SS2 and systematically characterized its protein product, enolase. Biophysical data indicated that S. suis enolase is an octameric protein. Enzymatic assays verified its ability to catalyze the dehydration of 2-phospho-D-glycerate to phosphoenolpyruvate. In consideration of the strong antigenicity of enolase, an efficient enolase-based method was established for monitoring SS2 infections. Combined evidence strongly indicated that SS2 enolase can localize on the bacterial cell surface and facilitate bacterial adherence. Additionally, we found that enolase can confer complete protection against SS2 infection to mice, which suggests that enolase has potential as a vaccine candidate.

This is a CAFA annotations - @ggeorghiou 
One interesting finding is that enolase can be used as a vaccine antigen, but that's not in the scope of GO and would anyone find this with the term ' interaction with host via substance in symbiont surface' ? 

I think a CC annotation to cell surface is the most relevant - even as a  tool to identify candidates for vaccines. 

Pascale

**Comment by ValWood** [comment]
Agreed, these are out of scope. I think quite a few were like this. These aren't evolved functions of the pathogen proteins. I suggest just to obsolete the term, and  the obsoletion will force removal or reannotation to the correct term if appropriate.

**Comment by pgaudet** [comment]
@mgiglio99 Is that OK with you ?

**Comment by mgiglio99** [comment]
Yes, sounds fine.

**Comment by RLovering** [comment]
btw there is already the term antigen binding, is there any reason why a term is needed like host binding to symbiont antigen? I know that with autoimmune diseases and allergies the host is binding to a non-symbiont antigen but this is not a 'normal' process. In theory the system is set up to bind non-self antigens, ie symbionts. What I am not sure about is whether all symbiont binding can be considered as antigen binding.

**Comment by ValWood** [comment]
I agree about antigen binding
https://github.com/geneontology/go-ontology/issues/16186

**Comment by pgaudet** [comment]
In fact I think the annotations represent the antigen ? Bacterial proteins are annotated to this term.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete
GO:0044044	interaction with host via substance in symbiont surface and 
GO:0044045	interaction with host via substance in symbiont cell outer membrane

The reason for obsoletion is that these terms conflate a process and the mechanism of secretion of the compound mediating the process. 

There are 17 EXP annotations by CAFA: https://docs.google.com/spreadsheets/d/13Jp2QRFEBMeR2tqOW980VJXMvUr9krRrLXZw03IVVRw/edit#gid=0


There are no mappings to this term. This term is not present in any subset (slim). 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/17389

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on June 17th, 2019. Unless objections are received by June 17th, 2019. we will assume that you agree to this change.

Thanks, Pascale
