### ISSUE TITLE
NTR cargo receptor ligand activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17391]
To address https://github.com/geneontology/go-annotation/issues/2364

To annotate for example retinoic acid, apoB etc

synonym= cargo 

Need to make it clear that this is NOT for sequestering of receptors (+ endocytosis) to downregulate signaling.

**Comment by pgaudet** [comment]
@RLovering Please provide a PMID to use as a reference.

**Comment by RLovering** [comment]
For example ApoB P04114 PMID 15797858

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140355
+name: cargo receptor ligand activity
+namespace: molecular_function
+def: "The activity of a gene product that interacts with a cargo receptor and initiates endocytosis." [PMID:15797858]
+synonym: "cargo" RELATED []
+is_a: GO:0005488 ! binding
+created_by: pg
+creation_date: 2019-05-27T09:56:50Z

The definition could probably be improved! Suggestions are welcome. 

Thanks, Pascale
