### ISSUE TITLE
Obsolete 'other organism cell' and move 'other organism part' unde 'cellular anatomical entity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17394]
'GO:0044216 other organism cell' (4 EXP) and 
'GO:0044217 other organism part' (0 annotations)

have only 'host'-type terms are children. Are they necessary? Need to look at annotations.

**Comment by pgaudet** [comment]
Need to look at other children of 'other organism part'

**Comment by RLovering** [comment]
All 3 UCL annotations to GO:0044216 other organism cell have been removed

**Comment by pgaudet** [comment]
Thanks !

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
- GO:0044216 other organism cell' (annotations have been removed, see https://docs.google.com/spreadsheets/d/10rxn6SXnSI3v6InT09PvMLCAY6HDIond1os5YeUiWYE/edit#gid=0)
- GO:0044217 other organism part' (0 annotations)
- GO:0044218 other organism cell membrane  (14 annotations, see https://docs.google.com/spreadsheets/d/1NZ6-lK_X4XuzL4ScQ-RclPIm5xcQI8jW2S0wGBp9cms/edit#gid=0

The reason for annotation is that more specific terms should be used (either host or symbiont cellular component, for proteins located to another organism part) or in some cases the annotation should be removed. 

There are no mappings to these terms. The terms are not present in any subset (slim).

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/17394

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on June 17th, 2019. Unless objections are received by June 17th, 2019. we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Hello, 

Note that there are UniProt-Keywords mappings to GO:0044218

UniProtKB-SubCell:SL-0451
UniProtKB-KW:KW-1052

@ggeorghiou 

Thanks, Pascale

**Comment by pgaudet** [comment]
@pgarmiri I think those mappings need to be removed. In GO this would be captured as 'extracellular', we would not capture *where* in the target cell the protein is active.

**Comment by pgaudet** [comment]
- [ ] obsoleted 'other organism cell', since anyway we don't have 'cell' anymore. 
 - [ ] could we put 'other organism part' under 'cellular antomical entity? that might work for intracellular symbionts and viruses; we could consider that they are part of a cell?

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
The mappings have been removed.
Kind regards,
Penelope

**Comment by pgaudet** [comment]
Move 'other organism part' under ''cellular anatomical entity' as discussed on the ontology editors call, see http://wiki.geneontology.org/index.php/Ontology_meeting_2021-03-15
