### ISSUE TITLE
SAGA definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17397]
ends weirdly:

A SAGA-type histone acetyltransferase complex that contains Spt8 (in budding yeast) or a homolog thereof; additional polypeptides include Spt group, consisting of Spt7, Spt3, and Spt20/Ada5, which interact with the TATA-binding protein (TBP); the Ada group, consisting of Ada1, Ada2, Ada3, Ada4/Gcn5, and Ada5/Spt20, which is functionally linked to the nucleosomal HAT activity; Tra1, an ATM/PI-3 kinase-related protein that targets DNA-bound activators for recruitment to promoters; the TBP-associated factor (TAF) proteins, consisting of Taf5, Taf6, Taf9, Taf10, and Taf12, which mediate nucleosomal HAT activity and are thought to help recruit the basal transcription machinery; the ubiquitin specifc protease Ubp-8.

note that SAGA also 
contains deubiquitinating activity of histone H2B, which deubiquitinates and destabilizes H2B.

so maybe the ubp8  part could say this instead?

**Comment by ValWood** [comment]
The SAGA complex is a multiprotein complex that can be divided into five distinct functional modules: a recruitment module (Tra1), an acetylation module (Gcn5, Ada2, and Ngg1/Ada3), a TBP interaction unit (Spt3 and Spt8), a Dub module (Ubp8, Sus1, Sgf11, and Sgf73), and an architecture unit (Spt7, Spt20, Hfi1/Ada1, Taf5, Taf6, Taf9, and Taf12) (Koutelou et al. 2010).


Koutelou, E., C. L. Hirsch, and S. Y. Dent, 2010 Multiple faces of the SAGA complex. Curr. Opin. Cell Biol. 22: 374–382.

**Comment by ValWood** [comment]
This is a much nicer def....gets rid of all the conversational and hedging bits.

**Comment by pgaudet** [comment]
@bmeldal what do you think ?

**Comment by krchristie** [comment]
@ValWood - I agree that the current def is clunky. However, it's not clear that your proposed definition is a consensus view. It also seems to be missing some subunits. Here's a comparison of the modules and subunits listed in the paper you mentioned as well as in a 2015 review that came up in my PubMed search. The three subunits in bold+italic in the side of the table for the Moraga paper are listed in the subunit table in the Koutelou paper, but not included in the definition you propose, so it's not clear to me, having only looked at the paper briefly, where Koutelou et al. think those three proteins fit into their scheme of the SAGA complex.

| Koutelou et al. 2010. | PMID:20363118 | Moraga & Aquea 2015 | PMID:26528322 |
| ----- | ---- | ---- | ---- |
| recruitment module | Tra1 |  |  |
| TBP interaction unit | Spt3 and Spt8 |  |  |
| architecture unit | Spt7, Spt20, Hfi1/Ada1, Taf5, Taf6, Taf9, and Taf12 |  |  |
| acetylation module | Gcn5, Ada2, & Ngg1/Ada3 | HAT | Gcn5, Ada2, Ada3, & **_Sgf29_** | 
| Dub module | Ubp8, Sus1, Sgf11, and Sgf73 | DUBm | Ubp8, Sgf11, Sus1, Sgf73 |
| | | SPT | Spt8, Spt20/Ada5, Spt7/Staf65, Spt3, Ada1/Staf42, Tra1/Trrap |
| | | TAF | Taf5, Taf6, Taf9, **_Taf10_**, Taf12 |
| | | other | **_Chd1_** |

It would also be great to your your opinion @bmeldal

**Comment by ValWood** [comment]
taf10 TAF
sgf29 HAT
CHD1 could be excluded for now
The objective isn't to exhaustively list every subunit, but rather  to uniquely define SAGA -  listing  the funtionally defined independent modules seems to a better way to do this than listing every gene - if we can include the genes  it's helpful, but not absolutely necessary.

**Comment by krchristie** [comment]
@ValWood - The Moraga & Aquea paper is more recent than the paper you cite, and it lists different modules, as well as includes the "extra" three subunits. This suggests to me that the modules in the Koutelou paper may not be a consensus view.

Also, the comparision table from the Moraga & Aquea paper suggests a high degree of conservation of all three of those subunits, so leaving them out may be misleading.
https://www.frontiersin.org/files/Articles/162964/fpls-06-00865-HTML/image_m/fpls-06-00865-t001.jpg

**Comment by ValWood** [comment]
OK there seem to be lots of close variants reported:
![variants](https://user-images.githubusercontent.com/7359272/58532932-f2ef4280-81de-11e9-9a64-c4b3605b796d.jpg)


we could just mention the consensus modules and not report the gene names at all?

**Comment by bmeldal** [comment]
Oh, another chromatin remodeler! Can't you pick something easier ;-)

I had a look at our entries:
https://www.ebi.ac.uk/complexportal/complex/CPX-656 (yeast)
https://www.ebi.ac.uk/complexportal/complex/CPX-900 (human)

I haven't curated either of them but looking at the defs they vary a bit between yeast and human (mouse is a clone of the human entry). Neither curator added the papers you mention above. I don't have time to go through all the evidence but seems to me that our understanding of these complexes is still very much emerging. 

Mila curated the human & mouse entries and decided that SAGA and STAGA may well be the same!

I suggest to tone down the def to the recognised functions. You could mention that there are several modules to the complex but my gut feeling is that these modules are described based on the experiments people performed and may be somewhat artefactual.

I know that doesn't help too much!

PS: Good to have you back, Karen!

**Comment by ValWood** [comment]
Ok, let's not spend too much time on this. 

I see now that the final clause isn't a truncation but the end of a long list.

closing...
