### ISSUE TITLE
Transporters: Move 'nucleocytoplasmic carrier activity' and children under 'transporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17399]
Hello, 

At some point in the MF refactoring we thought we could define transporter activities as 'transmembrane', so we has put 'nucleocytoplasmic carrier activity' and children under 'molecular carrier activity': 

'nucleocytoplasmic carrier activity'
'nuclear export signal receptor activity'
'nuclear import signal receptor activity'

The definition of 'molecular carrier activity' is 'Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.'

But the work on flippases/floppases/scramblases lead us to revisit this. I propose that the distinction between a carrier and a transporter is that carriers bring a molecule to a molecule, and a transporter brings a molecule to a cellular location. 

~So I propose to change the definition~  of carrier to **Directly binding to a specific ion or molecule and delivering it** ~either~ **to an acceptor molecule** ~or to a specific location~'. (will not do, see https://github.com/geneontology/go-ontology/issues/17399#issuecomment-697806371)

Transporter is defined as 'Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells.' 
This is the standard definition, so I don't know if we want to change it, but if we do, it would be to something like 'Enables the directed movement of substances (such as macromolecules, small molecules, ions) between different cellular locations.' 

@ValWood OK ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also moved 
- mobile ion carrier activity
- oxygen carrier activity

Not sure what to do about 'protein carrier activity' 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't really know precisely  what protein carrier refers to. It only has 27 EXP. I think we could get rid of it (most are to children, insertases). Insertase could go directly under  carrier? the rest reannotate?

**Comment by pgaudet** [comment]
It's trying to capture the function of "the soluble TIM chaperone complexes of S. cerevisiae Tim9-Tim10 and Tim8-Tim13, that provide a shuttle system between TOM and the membrane insertases TIM22 and SAM and, thus, ensure that precursors are kept in a translocation-competent conformation.  " (see comment). See also #17073

What do you suggest ?

**Comment by ValWood** [comment]
these are chaperones, not transporter I think....as far as I'm aware they only prevent misfolding while the protein mover from outer to inner membrane. 

see:
https://github.com/geneontology/go-ontology/issues/17073

**Comment by pgaudet** [comment]
Discussing with @thomaspd 
"The carrier moves along with its cargo. "

**Comment by pgaudet** [comment]
The only 2 terms left under 'transporter activity' that are not strictly transmembrane are 
* 'lipid transfer activity'
* 'intramembrane lipid transporter activity'

Maybe those are carriers ? Need to check the literature

**Comment by ValWood** [comment]
"carrier " has multiple meanings.

but these might fit the GO sense oof carrier.

For example some of thedescendants have "exact" carrier synonyms

phospholipid transfer activity
https://www.ebi.ac.uk/QuickGO/term/GO:0120014

The lipid transporter activity is the  'translocase:broad flippsase:related' term
and includes the scramblases.

 I'm not sure if it would make sense for these not to be transporters.  A transport expert would be required. Where are they in TC?

**Comment by ValWood** [comment]
> Discussing with @thomaspd
"The carrier moves along with its cargo. "

Is that always true (even for the chaperone-type delivery  'carriers' ) which are only 'inserting a molecule'. Does the carrier move anywhere? 

If this is a requirement it should be in the definition?

**Comment by pgaudet** [comment]
The definition of 'nucleocytoplasmic carrier activity' 
is "Binding to and carrying a cargo between the nucleus and the cytoplasm by moving along with the cargo. The cargo can be either a RNA or a protein." 

I think this is fine.
