### ISSUE TITLE
NTR heme export from vacuole

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#17407]
I'd like to request 
heme export from vacuole

is_a heme transmembrane transport, vacuolar transmembrane transport

PMID:28193844

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140357
+name: heme export from vacuole to cytoplasm
+namespace: biological_process
+def: "The directed movement of heme from the vacuole to the cytoplasm." [PMID:28193844]
+comment: Create new term see https://github.com/geneontology/go-ontology/issues/17407
+intersection_of: GO:0006810 ! transport
+intersection_of: exports CHEBI:30413 ! heme
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005775 ! vacuolar lumen
+intersection_of: results_in_transport_across GO:0005774 ! vacuolar membrane
+created_by: pg
+creation_date: 2019-05-28T07:40:48Z
