### ISSUE TITLE
PomBase number of helicases just dropped from 82 to 39??

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17418]
Something with the has_parts. Maybe these changes shouldn't be made until the 
correct inferences are  established?

**Comment by ValWood** [comment]
0 | ATP-dependent helicase activity (GO:0008026)
-- | --

**Comment by ValWood** [comment]
used to have most helicases?

**Comment by pgaudet** [comment]
I merged a number of terms. see #17371

**Comment by ukemi** [comment]
I'm not sure why the has_part inferences would have anything to do with this drop. Presumably the primary annotation was to the helicase and there are no MF has_part helicase. I just did a DL query to be sure. There is nothing that matches ''has part' some 'helicase activity'.

**Comment by ValWood** [comment]
ino80 | SNF2 family ATP-dependent 3' to 5' DNA helicase Ino80 |   | ATP-dependent 3'-5' DNA helicase activity |   | PomBase | Schizosaccharomyces pombe | ISO | SGD:S000003118 | family not named pthr45685 | protein |   | GO_REF:0000024 | 20060320


In amigo. This annotation has disappeared from pombase.  
I suspect it is becasue teh term name changed and we need to fix at our end.
Apologies!

**Comment by ValWood** [comment]
(our old  legacy system does a check that the term name and ID agree, these are all old ISS's)

**Comment by ValWood** [comment]
reopening because PomBase now has zero annotations to 
GO:0004386    helicase activity

**Comment by ValWood** [comment]
ignore
