### ISSUE TITLE
MP thiamine transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17411]
thamine transport

(can probably merge as all thamine transport is probably transmembrane?)

**Comment by pgaudet** [comment]
Weird 

Thiamine transport had LD

transport
 and ('transports or maintains localization of' some 'thiamine(1+)')

and Thiamine transmembrane transport 
transport
 and ('transports or maintains localization of' some thiamine)
 and ('results in transport across' some membrane)

I thought GOCHE would map these two forms of thiamine. Anyway, I changed both to 'thiamine'. 

We have many cases of usage of thiamine and thiamine(1+); @ukemi do we need to standardize that ? 

Thanks, Pascale
