### ISSUE TITLE
Difference 'ATP synthase activity' and 'proton-transporting ATPase activity, rotational mechanism'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17412]
Hello, 

We have these 2 pairs of terms: 

'proton-transporting ATP synthase activity, rotational mechanism' -> EC 7.1.2.2
'proton-transporting ATPase activity, rotational mechanism' -> EC 7.1.2.2

'sodium-transporting ATP synthase activity, rotational mechanism' -> 7.2.2.1  
'sodium-transporting ATPase activity, rotational mechanism' -> 7.2.2.1  

I think the reason to have 2 activities is that there is both transport and ATP synthesis being carried out by the same enzymatic complex ? 

But it's confusing to have 'ATP synthase activity' under 'transmembrane transporter activity'. 

I think the two terms should be merged. We could add 'part of some proton transmembrane transport' and part of some ATP synthesis'. 

Thoughts anyone ? 

Thanks, Pascale

**Comment by ValWood** [comment]
1. We use 
proton-transporting ATP synthase activity, rotational mechanism' -> EC 7.1.2.2

for the mitochondrial ATP synthase
and

'proton-transporting ATPase activity, rotational mechanism' -> EC 7.1.2.2
for the vacuolar ATPas

this represents the 2 physiological directions. I think this is important to capture. The mitchondrial synthesises ATP and the vacuolar does not. 

all the detail in this ticket is relevant
https://github.com/geneontology/go-ontology/issues/17035


but not 
'sodium-transporting ATP synthase activity, rotational mechanism' -> 7.2.2.1
'sodium-transporting ATPase activity, rotational mechanism' -> 7.2.2.1

I don't know what there are for. Is this some weird bacterial thing? are these used?

**Comment by ValWood** [comment]
no annotations
'sodium-transporting ATP synthase activity, rotational mechanism' -> 7.2.2.1
'sodium-transporting ATPase activity, rotational mechanism' -> 7.2.2.1

obsolete both as do not exist and keep the other 2?

**Comment by pgaudet** [comment]
7.2.2.1 is meant for  Q08636 (for eg), see 
https://enzyme.expasy.org/EC/7.2.2.1

**Comment by pgaudet** [comment]
although it's annotated to 'proton-transporting ATP synthase activity, rotational mechanism'

**Comment by ValWood** [comment]
Ok this isn't "rotational mechanism"

**Comment by ValWood** [comment]
these are P-type ATPases I think?

**Comment by pgaudet** [comment]
> proton-transporting ATP synthase activity, rotational mechanism'

Is this H+ transport ? 
Should it have a link to ATP synthesis ?

**Comment by ValWood** [comment]
>Is this H+ transport ?
yes but in GO we refer to H+ as proton (can't remember why but there was some history)
so that would be:
GO:1902600    proton transmembrane transport
It has this parent already, maybe add synomym?

> Should it have a link to ATP synthesis ?

it already does?
GO:0006754    ATP biosynthetic process

**Comment by pgaudet** [comment]
7.2.2.1 **is** rotational mechanism  - see 
https://en.wikipedia.org/wiki/V-ATPase

**Comment by ValWood** [comment]
the sodium one - does a rotational mechanism exist for this. I thought rotational mechanism was ontly the vacuolar and Fo-F1 ATPases?

**Comment by pgaudet** [comment]
>  Should it have a link to ATP synthesis ?

>> it already does?
GO:0006754 ATP biosynthetic process


Where do you see that ? 

![image](https://user-images.githubusercontent.com/4782928/58550639-7c6a3900-820e-11e9-82fe-bd3158786e0a.png)

**Comment by ValWood** [comment]
That's weird, I really thought I saw them yesterday, but  the term I was looking at hed many more parent than this one. 

Even the process term does not have all the parents I saw....I can't think what else would have both of these parents either...

**Comment by ValWood** [comment]
I think I was looking at this
https://www.ebi.ac.uk/QuickGO/term/GO:0042776

**Comment by pgaudet** [comment]
ok well this is a process ;)

**Comment by vanaukenk** [comment]
Closing this ticket as the work has been addressed in #17035 
I'm leaving the sodium terms for now as there do seem to be bacteria that have these activities.
If there are any further issues, please re-open this ticket.
