### ISSUE TITLE
OTR: pre-rRNA binding as synonym to GO:0042134 rRNA primary transcript binding

### ISSUE THREAD

**Issue by jpa29** [geneontology/go-ontology#17427]
NTR: pre-rRNA binding 
Proposed definition: Interacting selectively and non-covalently with pre-ribosomal RNA (pre-rRNA).
Reference:PMID: 3327689 
This term will be a child of GO:0003723 RNA binding like GO:0036002 pre-mRNA binding

**Comment by ValWood** [comment]
GO:0042134    rRNA primary transcript binding
Definition (GO:0042134 GONUTS page)
Interacting selectively and non-covalently with an unprocessed ribosomal RNA transcript.

add synonym?

**Comment by suzialeksander** [comment]
Perfect. Yes, make this a synonym!
