### ISSUE TITLE
cell tip parentage

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#17420]
should cell tip be is_a cell pole? The comments don't suggest so but it looks like it would fit from the defs?

**Comment by ValWood** [comment]
The commet does suggest it?

Cell tip
Comments
Note that this term differs from 'cell pole ; GO:0060187' in that it is applicable to the thin ends of elongated cells, such as the ends of axons or dendrites.

it sounds the same but narrower?

**Comment by ukemi** [comment]
I'm not sure. Round cells like eggs can have 'poles'. AFAIK they are defined along an linear axis (like the north and south poles of the earth). I'm not sure tips follow this rule. I don't think anyone would consider the vegetal pole of an egg to be a tip.

**Comment by ValWood** [comment]
OK, we should  just make sure we don't use pole/ We only used it once out of  232 annotations.

**Comment by ValWood** [comment]
When I say we, it was I whoops, now fixed.
