### ISSUE TITLE
NTR: 3-butenylglucosinolate 2-hydroxylase activity

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#17429]
Catalysis of the reaction: gluconapin + a reduced unknown electron carrier + oxygen → ξ-progoitrin + an oxidized unknown electron carrier + H2O

Metacyc:
https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=RXNQT-4343

PMID:18945935

Synonym: But-3-enyl Glucosinolate-2-hydroxylase

Parentage:
is_a dioxygenase activity, GO:0051213
http://amigo.geneontology.org/amigo/term/GO:0051213

**Comment by ukemi** [comment]
3-butenylglucosinolate = gluconapin(1−) CHEBI:5411
ξ-progoitrin = CHEBI:79350

Not in Rhea. Tagging @amorgat @alanbridge

**Comment by tberardini** [comment]
Yeah, I checked Rhea and EC and couldn't find this activity/reaction in either of them. Metacyc is the only place I found it so far.  Can we estimate when this term might be added?  I've forgotten the flow.  Add to Rhea first, then to GO or the other way around?

**Comment by ukemi** [comment]
We can add it with the Rhea pending tag. We will leave the ticket open and then update it and the definition when the Rhea reaction becomes available. I suspect the name might be changed to something like gluconapin 2-hydrolase activity and the chemicals in the def will be changed to reflect the official ChEBI names. @vanaukenk do you want me to take this one?

**Comment by tberardini** [comment]
Did this get added?  Thanks for checking.

**Comment by 123seher** [comment]
Eliminate this thread

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amorgat** [comment]
Hi GO,
I have created RHEA:60628
AH2 + gluconapin + O2 = A + H2O + ξ-progoitrin
gluconapin = CHEBI:5411
ξ-progoitrin = CHEBI:47798
Sorry for the delay but there was an error in the 2D structure of CHEBI:47798.

**Comment by tberardini** [comment]
Thanks @amorgat!  Appreciate your help.

**Comment by tberardini** [comment]
No longer Rhea_pending.

**Comment by ukemi** [comment]
Still not public?

**Comment by ukemi** [comment]
Hi @tberardini   I'm adding this, but am going to add back the Rhea-pending tag because I still don't see the reaction when I search Rhea.

**Comment by ukemi** [comment]
Let me know if anything looks weird.

**Comment by amorgat** [comment]
Rhea follows the same production cycle as UniProtKB, so the reaction will - unfortunately -  not be available before release 2019_07 (2019-07-31).

**Comment by ukemi** [comment]
No worries @amorgat. I just keep the tag on these and check every once in a while. When they are available I add them.

**Comment by amorgat** [comment]
Tanks @ukemi !

**Comment by tberardini** [comment]
It's live.
https://www.rhea-db.org/reaction?id=60628

**Comment by tberardini** [comment]
Thanks for the term.  @amorgat and @ukemi 
http://amigo.geneontology.org/amigo/term/GO:0062131

**Comment by ukemi** [comment]
Thanks for the heads up. Adding now.

**Comment by hdrabkin** [comment]
RHEA was added; removing tag
