### ISSUE TITLE
New term request: "Positive regulation of protein localization to cell-cell junction localization"

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#17432]
Hi Barbara,
Could you please create the following new term:
"Positive regulation of protein localization to cell-cell junction localization"
The parent should be "protein localization to cell-cell junction" but it is not available either.  So I think it would be a good Idea to create that one as well.
This one would be the child of "protein localization to cell junction" (GO:1902414)

Thanks,
Mila

**Comment by BarbaraCzub** [comment]
Hi Mila,
Could you please provide the PubMed identifier(s) that I should include as a reference for these new terms?
Thanks,
Barbara

**Comment by milarolo** [comment]
Hi Barbara,
Sorry, I forgot to add that.
PMID: 26706435

**Comment by BarbaraCzub** [comment]
Thank you!
