### ISSUE TITLE
MP GO:0046961

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17439]
If ~GO:00466961~ GO:0046961 is remaining, it should be a parent of  GO:0046961

(IEA annotation is displaying since no longer filtered)

![MP, ](https://user-images.githubusercontent.com/7359272/58783395-b786b680-85d8-11e9-956a-5488b739520a.jpg)

**Comment by ValWood** [comment]
![MP](https://user-images.githubusercontent.com/7359272/58783446-d38a5800-85d8-11e9-88e4-998de0afbb26.jpg)

**Comment by pgaudet** [comment]
This is how it is now; is it OK ? 

<img width="579" alt="image" src="https://user-images.githubusercontent.com/4782928/60177107-0abde480-97e6-11e9-8070-cef5828cbeb1.png">

Thanks, Pascale

**Comment by ValWood** [comment]
that should do it

**Comment by pgaudet** [comment]
I will look at this one again once #17373 is closed.

**Comment by pgaudet** [comment]
I think this was addressed here: #17035.
