### ISSUE TITLE
NTR: inositol-5-diphosphate-1,3,4,6-tetrakisphosphate diphosphatase activity

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#17443]
Hi,

The following paper describes a novel inositol phosphate dephosphorylation activity in yeast:

Wang H, et al. (2018) Structural and biochemical characterization of Siw14: A protein-tyrosine phosphatase fold that metabolizes inositol pyrophosphates. J Biol Chem 293(18):6905-6914 PMID:29540476 

I would therefore like to request the following new molecular function term:

NTR: inositol-5-diphosphate-1,3,4,6-tetrakisphosphate diphosphatase activity 

Definition: 
Catalysis of the reaction: inositol-5-diphosphate-1,3,4,6-tetrakisphosphate + H2O = inositol 1,3,4,5,6-pentakisphosphate + phosphate. 

Synonyms:
5-diphosphoinositol 1,3,4,6-tetrakisphosphate diphosphatase activity
5-diphospho-myo-inositol 1,3,4,6-tetrakisphosphate diphosphatase activity
5-PP-InsP4 activity

In terms of placement in the ontology, this new term should be an instance of GO:0052840 inositol diphosphate tetrakisphosphate diphosphatase activity so should have an is_a relationship to this term. 

Definition reference: PMID:29540476

Thanks,
Rob

**Comment by ukemi** [comment]
RHEA:59500?

**Comment by robnash** [comment]
I am unsure if this is correct. I was looking at CHEBI:62928 (5-diphospho-myo-inositol 1,3,4,6-tetrakisphosphate) when I put this together but RHEA:59500 refers to CHEBI:142939 5-diphospho-1D-myo-inositol 1,3,4,6-tetrakisphosphate(11−), the fully deprotonated form?

**Comment by deustp01** [comment]
@ukemi ? General policy is that Rhea is the authority on ionization states under physiological conditions as well as stereochemistry so I guess that if you think they are wrong on this one, the thing to do is to work with them to get the Rhea reaction corrected so GO can refer to it.

**Comment by hdrabkin** [comment]
I'll bet at pH 7.3, the phosphates are deprotonated.

**Comment by ukemi** [comment]
@amorgat, @alanbridge ?

**Comment by deustp01** [comment]
ChEBI and Rhea explicitly agree with @hdrabkin 's bet:
<img width="1171" alt="Screen Shot 2019-06-05 at 10 25 46 AM" src="https://user-images.githubusercontent.com/12737623/58964176-7a5b2980-877c-11e9-8857-ce1319e3d9b1.png">
Note the "major species at pH 7.3" tag in the ChEBI definition.

**Comment by ukemi** [comment]
:) Also keep in mind that GO, unlike Reactome and Rhea doesn't distinguish charge states.

**Comment by amorgat** [comment]
Hi GO,

RHEA:59500 was requested by https://github.com/geneontology/go-ontology/issues/16850 ;-)

Yes, the major species at pH 7.3 has its phosphates deprotonated.
I can see in our internal note that the structure of CHEBI:142939 has bee determined in PMID:9359429

I will add PMID:29540476 citation to RHEA:59500 and will check that the 2 other reactions described in the figure 1 of PMID:29540476 are in Rhea

**Comment by robnash** [comment]
Another request ( #16850) is refering to the same function, so maybe the information and references can be combined when this term is created. My colleague was requesting the same term but named it slightly differently. We will leave the naming nuances up to the experts.

**Comment by hdrabkin** [comment]
So if the request for 16850 is indeed the same as this ticket, perhaps this ticket can be closed and I can just add the RHEA to the 16850 term?

**Comment by hdrabkin** [comment]
Term made GO:0106211, xref-ed to RHEA; used RHEA as text definition also. 
May want to close #16850 
I did not use the EC or metacyc supplied, as they relate more to the parent term.
