### ISSUE TITLE
MP GO:0006491    N-glycan processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17440]
GO:0006491    N-glycan processing

2017-01-27 | Deleted | RELATION | part of GO:0006487 (protein N-linked glycosylation)

I wondered why this is. Now some of the "N-linked glycosylation pathway" no longer slim to glycosylation?

**Comment by ukemi** [comment]
I think this was done because it isn't clear that ALL processing is part of glycosylation.

**Comment by ValWood** [comment]
It sounds like that are from the def: 

The conversion of N-linked glycan (N = nitrogen) structures from the initially transferred oligosaccharide to a mature form, by the actions of glycosidases and glycosyltransferases

and all my annotations are. Which parts of  N-glycan processing are not part of glycosylation, do you have an example?

**Comment by ukemi** [comment]
PMID:17074831? @krchristie will decide.

**Comment by ValWood** [comment]
The processing (trimming)  is part of the ER QC system, but it is still part of the broader glycosylation process i.e:

https://en.wikipedia.org/wiki/N-linked_glycosylation#Processing_of_glycan

(when people talk about the process fo glycosylation, they don't exclude these steps which are absolutely required for maturation- otherwise, we no longer have a term to refer to the entire pathway)

==

This initial trimming step is thought to act as a quality control step in the ER to monitor protein folding.

Once the protein is folded correctly, the three glucose residues are removed by glucosidase I and II. The removal of the final glucose residue signals that the glycoprotein is ready for transit from the ER to the cis-Golgi.[4] However, if the protein is not folded properly, the glucose residues are not removed and thus the glycoprotein can’t leave the endoplasmic reticulum. A chaperone protein (calnexin/calreticulin) binds to the unfolded or partially folded protein to assist protein folding.

**Comment by krchristie** [comment]
It looks to me that the lack of a relationship between these two terms is consistent with their current definitions and positions in the graph, where the first term is described as the addition of the initial carbohydrate or derivative to a protein, while the second term is described as subsequent modifications to that initial carbohydrate.

**protein N-linked glycosylation**
**Def:** A protein glycosylation process in which a carbohydrate or carbohydrate derivative unit is added to a protein via the N4 atom of peptidyl-asparagine, the omega-N of arginine, or the N1' atom peptidyl-tryptophan.

**N-glycan processing**
**Def:** The conversion of N-linked glycan (N = nitrogen) structures from the initially transferred oligosaccharide to a mature form, by the actions of glycosidases and glycosyltransferases. The early processing steps are conserved and play roles in glycoprotein folding and trafficking.

To group these two things, I think you would need some other broader term. Perhaps the existing term 'glycoprotein metabolic process' would be appropriate (def below). To do that would mean giving 'protein N-linked glycosylation' additional is_a parentage under 'glycoprotein metabolic process'. We could also add think about adding a more specific term for 'protein N-glycan metabolic process', or perhaps for 'N-linked proteoglycan biosynthetic process', which I think we could make under 'proteoglycan biosynthetic process'.

Let me know what you think.

-K

**glycoprotein metabolic process**
**Def:** The chemical reactions and pathways involving glycoproteins, any protein that contains covalently bound glycose (i.e. monosaccharide) residues; the glycose occurs most commonly as oligosaccharide or fairly small polysaccharide but occasionally as monosaccharide.

**proteoglycan biosynthetic process**
**Def:** The chemical reactions and pathways resulting in the formation of proteoglycans, any glycoprotein in which the carbohydrate units are glycosaminoglycans.

**Comment by ValWood** [comment]
I'm a bit confused, and not an expert. But I really thought that people who study this refer to the entire pathway as "protein glycosylation". And indeed that is still a parent because 
all GO:0006491 N-glycan processing
is still part of 
https://www.pombase.org/term/GO:0006486
I think this is correct?

 However, if this *Is* true, then logically

GO:0006491 N-glycan processing
should be part_of
GO:0006487 protein N-linked glycosylation
