### ISSUE TITLE
New term request: Biomineralization

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#17448]
This is a follow-on from #17209
The current GO term for biomineralization (GO:0031214, biomineral tissue development) does not work for entries outside of animals. It is a child of GO:0048513, animal organ development and of GO:0009888 tissue development, and the definition speaks of "hard tissues". I need a process term suitable for bacteria, that could probably be a parent to GO:0031214, please.

I suggest the following definition, which is based on the UniProtKB keyword. I can't find a single review that covers everything from vertebrate tissue to marine animals to bacterial biomineralization, sorry. Bacteria were recently shown to make a cement-like material, see PMID     24395694, so there is more than one kind of biomineralization in bacteria.
Thanks, Andrea

Biomineralization.
The process where mineral crystals are deposited in an organized fashion in a matrix (either cellular or extracellular) by living organisms. This gives rise to inorganic compound-based structures such as skeleton, teeth, ivory, shells, cuticle, corals as well as bacterial biomineralization products.

**Comment by ukemi** [comment]
Note there is a wikipedia entry that covers everything, so a grouping term is probably reasonable.

**Comment by vanaukenk** [comment]
@AndreaAuchincloss 

Do you think we should include formation in the definition, as well?

The process where mineral crystals are _formed_ and deposited in an organized fashion in a matrix (either cellular or extracellular) by living organisms. This gives rise to inorganic compound-based structures such as skeleton, teeth, ivory, shells, cuticle, corals as well as bacterial biomineralization products.

**Comment by AndreaAuchincloss** [comment]
@vanaukenk 
Good idea, yes that is better.
