### ISSUE TITLE
small update Ndc80 complex/ improve definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17446]
-- | --
A protein complex conserved among eukaryotes that forms part of the kinetochore and plays an essential role in forming stable kinetochore-microtubule attachments. The complex contains proteins known in several species, including budding and fission yeasts, as Ndc80p, Nuf2p, Spc24p, and Spc25p. In vertebrates it is part of the outer plate of the kinetochore.

revised
An outer kinetochore protein complex providing the platform with which the plus ends of  spindle microtubules directly interact to form stable kinetochore-microtubule attachments. 
Gloss: Common subunit nomenclature is used from yeast to human (Ndc80, Nuf2, Spc24, and Spc25). 

add def PMID: 28502666

**Comment by krchristie** [comment]
@ValWood - I have updated this term with your definition plus a few additional modifications. I have removed the word "Gloss:" as my impression is that CJM uses this for the entire textual definition, not just a portion of it. It's also not something we include in definitions. I also modified the second sentence slightly, so I've entered this:

> Def: An outer kinetochore protein complex which provides the platform with which the plus ends of spindle microtubules directly interact to form stable kinetochore-microtubule attachments. A common subunit nomenclature is used from yeast to human: Ndc80, Nuf2, Spc24, and Spc25.

I'll assume you're fine with these modifications, but let me know if not.

**Comment by ValWood** [comment]
Yes great, thanks.

I only separated what I considered "gloss" because it isn't part of the "necessary and sufficient" but it's useful for curators. I'm not sure how you distinguish such parts of definitions behind the scenes (if at all)?

**Comment by krchristie** [comment]
My understanding is that all of the textual definition is what CJM calls "gloss". I really detest this usage is it implies that this part is just extra fluff, while for me, as an annotator, it is the part the is really helpful. 

The logical definition, in contrast, is rarely useful to me as it doesn't really provide any info that wasn't obvious from the term name and/or position in the graph. The "necessary & sufficient" critierion is only applicable to a logical definition, not to the textual definition. The Ndc80 complex does not have a logical def, but here's an example for a different term:

**mRNA editing complex**
`'protein-containing complex'
 and ('capable of part of' some 'mRNA modification')`

**Comment by ValWood** [comment]
@cmungall  is this true? 
I thought there was also a defined criterion for a textual def  (root with differentia) and then there is sometimes some unnecessary stuff that's useful but isn't part of the real text def (gloss).  
Actually I think it is @ukemi  who uses the term "gloss" for this appendage.

I never know if the "gloss" part   should really go in a comment. But yes @krchristie  I agree with you the text definitions are much more useful for us as curators than LD  (although for me this  is partly because there is nowhere i can actually easily see the LD in any of the tools that I use so they remain a bit of a blind spot. I would really, really  like to be able to see and use them more)

**Comment by ValWood** [comment]
suggest LD for Ndc80 complex

part_of GO:0000940    condensed chromosome outer kinetochore
has_function GO:0051010   microtubule plus-end binding

I don't know if these are the right relationships but these axioms should uniquely define Ndc80 complex since it is currently considered to be the only complex which directly binds to the microtubules  at the outer kinetochore interface (many more proteins /complexes are implicated indirectly in  "microtubule attachment", but don't bind directly to the microtubule plus end).

**Comment by ValWood** [comment]
reopening in case the LD is useful

**Comment by krchristie** [comment]
This:
`'part of' some 'condensed chromosome outer kinetochore' and enables some 'microtubule plus-end binding'`
is allowed as an equivalence axiom in Protege, so I'll put it in.

Since the equivalence axiom now specifies being part of a specific subregion of the kinetochore, I will also remove the explicit statement that 
'Ndc80 complex' part_of 'kinetochore'

**Comment by pgaudet** [comment]
Is that definition necessary and sufficient (although I suppose @ukemi would have mentioned something if he didn't think so). But it seems odd that the ndn80 complex is the only one that is 'part of' some 'condensed chromosome outer kinetochore' and that enables some 'microtubule plus-end binding'. 

Pascale

**Comment by ValWood** [comment]
not really...
![ndc802](https://user-images.githubusercontent.com/7359272/58967160-91fdd680-87ab-11e9-80c8-54c8cdbcd154.jpg)

![ndc80](https://user-images.githubusercontent.com/7359272/58967184-9aeea800-87ab-11e9-8d01-6f1b8db03b22.jpg)

**Comment by ValWood** [comment]
although the yeast specific  "DASH" complex is also defined as part of the outer kinetochore and this also binds to microtubule plus ends and is not shown in these figures....

I wonder if DASH is a 'true' part of the 'outer kinetochore' though....

**Comment by ValWood** [comment]
OK a revised def:

An outer kinetochore protein complex (part of the KMN network, also known as the NMS complex) providing the platform with which the plus ends of spindle microtubules directly interact to form stable kinetochore-microtubule attachments.

Gloss: Common subunit nomenclature is used from yeast to human (Ndc80, Nuf2, Spc24, and Spc25).

This excludes DASH and other things with hang around at microtubule tips and are 'associated ' with the kinetochore. I'm not really sure these are part of the outer kinetochore proper, or if they are really just 'kinetochore-associated', but I see that some papers refer to DASH as a kinetochore component, so let's err on the side of caution.

**Comment by krchristie** [comment]
The term for 'DASH complex' is currently a subclass of 'condensed nuclear chromosome outer kinetochore', in the ontology. Thus it seems that your proposed logical definition for the Ndc80 complex isn't sufficient and I won't put that in. I will update the definition again.

**Comment by ValWood** [comment]
The revised  def above will work because Ndc80 is the only part of NMS/KMN which binds to microtubules.

**Comment by krchristie** [comment]
I'm fine with your revised def and will put that in. 

What I'm not going to put in is the logical def (aka equivalence axiom) you suggested yesterday:
`'part of' some 'condensed chromosome outer kinetochore' and enables some 'microtubule plus end binding'`
because it's not clear that this distinguishes Ndc80 from DASH.

**Comment by ValWood** [comment]
the more specific part_of  GO:0031617 NMS complex should work though, although oddly Ndc80 is not part_of NMS (it is mentioned in the GO:0031617 definiton?)

**Comment by krchristie** [comment]
please be explicit and write out exactly what you think would be appropriate as an equivalence axiom

**Comment by ValWood** [comment]
I'm not sure what they look like but  based on the  above I guess it would be

 'part of' some ''GO:0031617  NMS complex" and enables some 'microtubule plus-end binding'

note that NMS complex is more of a component than a complex, it is  more often called the "KMN kinetochore network".

**Comment by krchristie** [comment]
Great. Thanks for giving me the pieces that you think define the Ndc80 complex (the exact syntax isn't as important as knowing what pieces you think should be there.) 

In the equivalence axiom, Protege can only use other terms as they are currently named, so it has to be 'NMS complex' because that's the current name of the term. If that's something you want to change, please start a new ticket for that.

**Comment by cmungall** [comment]
Val: correct: gloss = part after first fullstop. Happy to use another term
if gloss is offensive. I agree about showing LD in tools.
