### ISSUE TITLE
NTR: MutSgamma complex

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#17444]
Hi,

I need to request a new cellular component protein complex term, the MutSgamma complex, that is composed of a heterodimer of Msh4-Msh5. As opposed to the many existing GO:0032300 mismatch repair complexes, that includes the MutSalpha complex (GO:0032301) and the MutSbeta complex (GO:0032302), the MutSgamma complex has been shown NOT to be involved mismatch repair, but is instead involved in meiotic reciprocal recombination between homologs. 

See PMID: 7622037, PMID: 8001134, PMID: 9374523 and reviewed in PMID:27648641

"The MSH4/MSH5 heterodimer, known collectively as MutSγ, is first recruited to specific sites of ongoing DSB repair and is unique among the MutS heterodimers in that it does not itself engage in mismatch correction.  Instead, in vitro studies of human MutSγ indicate that the complex forms a sliding clamp that encircles dHJ substrates and can translocate along the DNA in an ATP-dependent fashion, allowing the accumulation of further MutSγ clamps at that DSB repair site."  

The complex portal ID for the complex is CPX-1704 (https://www.ebi.ac.uk/complexportal/complex/CPX-1704).

Here are the details of the NTR

NTR: MutSgamma complex 

Definition: A heterodimer involved in the stabilization of DNA recombination intermediates, the promotion of crossover recombination, and the proper assembly of the synaptonemal complex in meiotic prophase nuclei. In yeast the complex consists of two subunits, Msh4 and Msh5.

Synonym:  Msh4-Msh5 complex

In terms of placement in the ontology, it should have a:

Capable of part of relationship to 'reciprocal meiotic recombination' (GO:0007131) and an is_a relationship to 'nuclear part' (GO:0044428)

Definition references: PMID: 9374523, PMID: 8001134, PMID: 7622037 

Thanks,
Rob

**Comment by bmeldal** [comment]
Looks like this was one of our earlier ones and we never requested a GO term - there is no component annotation.

parent:
is_a GO:0032991 protein-containing complex

This is another example where we don't yet know its actual molecular function so creating a function-related term is impossible.
