### ISSUE TITLE
NTR heme export from vacuole

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#17458]
Hi,

Id like to request heme export from vacuole
standard def

PMID:28193844

**Comment by ukemi** [comment]
Based on this paper, I think the term you want is 'heme export from vacuole to cytoplasm' (GO:0141357). I don't think there is the need for the more generic term is there?

**Comment by Antonialock** [comment]
@ValWood

**Comment by ValWood** [comment]
this looks fine. Its described and positioned as transmembrane transport of heme across the vacuolar membrane into the cytoplamsm.

@Antonialock  isn't that what you need?

**Comment by ValWood** [comment]
consistent with
Abc3 as vacuolar hemin exporter

**Comment by ValWood** [comment]
for MF
GO:0015439    ATPase-coupled heme transmembrane transporter activity
part_of 'heme export from vacuole to cytoplasm' 

which matches what I did in the other substrate branches. E.g zinc:

https://www.pombase.org/term/GO:0005385

**Comment by Antonialock** [comment]
Ok, I just wanted to ask because in another ticket you said:

“Antonia I don't think you need to encode the final destination into the import . that will be described by other steps”

**Comment by Antonialock** [comment]
https://github.com/pombase/curation/issues/2406

**Comment by ValWood** [comment]
I was referring to "heme import across plasma membrane into vacuole"   Here  the internalization and final destination are different processes  (endocytosis and transmembrane transport).
