### ISSUE TITLE
Is it redundant to specify "is_a" for GO:0120161, GO:0120162 and GO:0120163?

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17467]
From Peng Yu by direct email:

For GO:0120161, GO:0120162 and GO:0120163, I
am wondering whether their "is_a" field is necessary.

Suppose A1, ..., A_n and B_1, ..., B_n are ontology classes. Suppose

B1 is_a B2
...
B_{n-1} is_a B_n

and

A1 regulates B1
...
A_n regulates B_n

I think the following should hold.

A1 is_a A2
...
A_{n-1} is_a A_n

In this case, the three is_a in each of GO:0120161, GO:0120162 and
GO:0120163 can be derived so that there is no need to include them in
the OBO file. Is it so?

I don't see this property listed on "Relation Reasoning Summary". But
it sounds like this property is simple and may be discussed somewhere
already. If not, maybe it should added to GO documentation? Thanks.

ftp://ftp.geneontology.org/go/www/GO.ontology.relations.shtml

[Term]
id: GO:0120161
name: regulation of cold-induced thermogenesis
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of
cold-induced thermogenesis." [PMID:27876809]
synonym: "regulation of CIT" RELATED []
is_a: GO:0019222 ! regulation of metabolic process
is_a: GO:0051239 ! regulation of multicellular organismal process
is_a: GO:0065008 ! regulation of biological quality
intersection_of: GO:0008150 ! biological_process
intersection_of: regulates GO:0106106 ! cold-induced thermogenesis
relationship: regulates GO:0106106 ! cold-induced thermogenesis
created_by: kchris
creation_date: 2018-05-14T17:03:19Z

[Term]
id: GO:0120162
name: positive regulation of cold-induced thermogenesis
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or
extent of cold-induced thermogenesis." [PMID:27876809]
synonym: "positive regulation of CIT" RELATED []
is_a: GO:0009893 ! positive regulation of metabolic process
is_a: GO:0051240 ! positive regulation of multicellular organismal process
is_a: GO:0120161 ! regulation of cold-induced thermogenesis
intersection_of: GO:0008150 ! biological_process
intersection_of: positively_regulates GO:0106106 ! cold-induced thermogenesis
relationship: positively_regulates GO:0106106 ! cold-induced thermogenesis
created_by: kchris
creation_date: 2018-05-14T17:14:51Z

[Term]
id: GO:0120163
name: negative regulation of cold-induced thermogenesis
namespace: biological_process
def: "Any process that stops, prevents, or reduces the rate of
cold-induced thermogenesis." [PMID:27876809]
synonym: "negative regulation of CIT" RELATED []
is_a: GO:0009892 ! negative regulation of metabolic process
is_a: GO:0051241 ! negative regulation of multicellular organismal process
is_a: GO:0120161 ! regulation of cold-induced thermogenesis
intersection_of: GO:0008150 ! biological_process
intersection_of: negatively_regulates GO:0106106 ! cold-induced thermogenesis
relationship: negatively_regulates GO:0106106 ! cold-induced thermogenesis
created_by: kchris
creation_date: 2018-05-14T17:18:59Z

--
Regards,

Peng Yu, Ph.D.

**Comment by balhoff** [comment]
(this is directed to Peng Yu, not @krchristie)

There are many redundant `is_a` assertions in the OBO file, since the class hierarchy is precomputed before release using an OWL reasoner. This is a convenience for many users who prefer to have these inferences included in the file rather than having to use an OWL reasoner within their own systems.

There is a version of GO with no precomputed inferences included, available at `http://purl.obolibrary.org/obo/go/go-base.owl`.

**Comment by krchristie** [comment]
Hi Peng Yu,

You don't say which version of the ontology file you are looking at, but based on your comment that you see instantiated is_a relationships for these regulation terms, you are probably looking at one of the derived versions of the ontology file that includes all of the relationships that can be derived from reasoning.

In the editors version of the file, these regulation terms are all defined with equivalence axioms, e.g. `biological_process
 and (regulates some 'cold-induced thermogenesis')`

Then, when reasoning is applied, the is_a relationships you specify are all generated. In the screenshot of the editors version of the file from Protege for the "regulation of cold-induced thermogenesis" term (GO:0120161), you can see that the equivalence axiom has a white background, indicating that it is directly asserted. In contrast, all three of the is_a relationships you mention are highlighted in yellow, meaning that they are inferred by the reasoning. 

![20190606-regTermCIT](https://user-images.githubusercontent.com/10533218/59044436-fb74f800-8832-11e9-9ea7-60210cf61b80.jpg)

So, in the primary version of the file, you are correct that these is_a relationships can be derived. @balhoff has pointed you to a version of the file without precomputed inferences.

**Comment by krchristie** [comment]
@ukemi - I created this ticket from an email and have closed it promptly. Just tagging you so you see it to include in the rota.

**Comment by pengyubio** [comment]
@balhoff I only see `go-base.owl` but not `go-base.obo` at http://snapshot.geneontology.org/ontology/.

The `go-base.owl` file seems to be too verbose. It is 160MB (much larger than the other obo files and results in long download time). Can a `go-base.obo` be generated and posted there?

**Comment by pengyubio** [comment]
@krchristie I used `go.obo` on http://snapshot.geneontology.org/ontology/. What tool did you use to view the ontology shown in the snapshot?

**Comment by krchristie** [comment]
@pengyubio The tool is Protege, available here: https://protege.stanford.edu/ 

I'm not sure what file to direct you to though as I don't access the editors file (go-edit.obo) through the snapshot. @balhoff might be better able to tell you which obo format file would be what you are looking for.

**Comment by pengyubio** [comment]
@krchristie I see also webprotege. I'd like to use a cloud app rather a local app to save local disk space. Do you know if webprotege is equivalent to protege in terms of viewing and editing obo files? Thanks.

**Comment by krchristie** [comment]
Sorry, I do not. Questions about Protege would be better addressed to Protege support, options for which are listed on their website.

**Comment by cmungall** [comment]
@pengyubio actually the entailments you assume don't actually hold. As a rule of thumb you only get entailments of direct subClassOf if you have equivalence axioms somewhere, e.g. `A1 EquivalentTo regulates some B1` (see Karen's example above)

If you are interested in this area then I recommend reading up on description logics and reasoning. You can start with the GO OWL guide aimed at ontology editors: https://readthedocs.org/projects/go-protege-tutorial/

See also the resources here:
http://obofoundry.org/resources

I would caution against trying to come up with your own rules for how this all works as there may be mistaken assumptions.

I would also caution against using go-base, this has a very specific use case (being able to regenerate inferences using a standard OWL reasoner). Attempts to use it for other purposes will likely not be successful.

**Comment by pengyubio** [comment]
@cmungall It says `Download and install the latest version of Protege (5.1) for ontology development.` Will a more current version also work?

https://go-protege-tutorial.readthedocs.io/en/latest/InitialPreparation.html#clone-this-repository

**Comment by cmungall** [comment]
yes
