### ISSUE TITLE
Move molecular sequeestering activity under molecular function regulator? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17466]
This came up while looking at some annotations with @vanaukenk 
@ValWood what do you think?

**Comment by pgaudet** [comment]
Humm... but then the 'sequesterer' does not bind directly to the protein affected, so that's probably not correct to put it under molecular function regulator.

**Comment by ValWood** [comment]
I'm never sure about this. Personally I think MF regulators should alter the activity. These don't alter the activity, they just  keep the molecule away from the substrate, not by affecting the intrinsic activity as far as I know.

I don't know if this is an important distinction, but it could be.  For example, a kinase "sequestered" from the nucleus at the cell periphery might still have activity on substrates at the periphery. I don't if it does, but it could.....I guess I don't  know the answer.

Although the things I would annotate to "sequestering activity" would always be in direct contact with their substrate.

**Comment by pgaudet** [comment]
OK sounds good
