### ISSUE TITLE
removing 3 duplicate synonyms that differ only by presence/absence of a def dbxref

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17460]
I keep seeing these three synonyms get reordered in diffs for other tickets, and looking closely, I notice that the only difference between the members of each pair of synonyms is the presence versus absence of a definition dbxref. Therefore, these synonyms seem redundant and I am going to remove the ones lacking a def dbxref.

~/repos/go-ontology(ndc80complexImproveDefinition-v2-17446) $ git diff
diff --git a/src/ontology/go-edit.obo b/src/ontology/go-edit.obo
index 17123e7..3dd1570 100644
--- a/src/ontology/go-edit.obo
+++ b/src/ontology/go-edit.obo
@@ -108903,8 +108903,8 @@ name: phosphate ion transmembrane transporter activity
 namespace: molecular_function
 alt_id: GO:1901677
 def: "Enables the transfer of phosphate (PO4 3-) ions from one side of a membrane to the other." [GOC:ai]
**-synonym: "phosphate transmembrane transporter activity" RELATED [GOC:vw]
 synonym: "phosphate transmembrane transporter activity" RELATED []
+synonym: "phosphate transmembrane transporter activity" RELATED [GOC:vw]**
 xref: RHEA:32823
 intersection_of: GO:0022857 ! transmembrane transporter activity
 intersection_of: transports_or_maintains_localization_of CHEBI:35780 ! phosphate ion

@@ -517070,8 +517070,8 @@ synonym: "downregulation of ferrous iron export" NARROW [GOC:TermGenie]
 synonym: "downregulation of iron(2+) export" NARROW [GOC:TermGenie]
 synonym: "inhibition of ferrous iron export" NARROW [GOC:TermGenie]
 synonym: "inhibition of iron(2+) export" NARROW [GOC:TermGenie]
**-synonym: "negative regulation of ferrous iron export" NARROW []
 synonym: "negative regulation of ferrous iron export" NARROW [GOC:TermGenie]
+synonym: "negative regulation of ferrous iron export" NARROW []**
 synonym: "negative regulation of iron(2+) export" NARROW []
 intersection_of: GO:0065007 ! biological regulation
 intersection_of: negatively_regulates GO:1903988 ! iron ion export across plasma membrane

@@ -517085,8 +517085,8 @@ namespace: biological_process
 def: "Any process that activates or increases the frequency, rate or extent of export of iron ions from inside of a cell, across the plasma membrane and into the extracellular region." [GO_REF:0000058, GOC:BHF, GOC:kom, GOC:TermGenie, PMID:15514116]
 synonym: "activation of ferrous iron export" NARROW [GOC:TermGenie]
 synonym: "activation of iron(2+) export" NARROW [GOC:TermGenie]
**-synonym: "positive regulation of ferrous iron export" NARROW [GOC:TermGenie]
 synonym: "positive regulation of ferrous iron export" NARROW []
+synonym: "positive regulation of ferrous iron export" NARROW [GOC:TermGenie]**
 synonym: "positive regulation of iron(2+) export" NARROW []
 synonym: "up regulation of ferrous iron export" NARROW [GOC:TermGenie]
 synonym: "up regulation of iron(2+) export" NARROW [GOC:TermGenie]

**Comment by krchristie** [comment]
@ukemi @pgaudet - tagging you since you've both commented on seeing this too.

@ukemi - Since I self assigned, please make sure to include this ticket on the rota.

**Comment by ukemi** [comment]
Yeah. I'm not exactly sure why this is happening, but I also saw a reordering of some synonyms in one of my recent commits. Maybe a merge occurred that had the same synonyms?

**Comment by krchristie** [comment]
perhaps that's why it happened. In any case, the duplicates lacking a def dbxref are gone now, so at least for those three, this should stop happening.
