### ISSUE TITLE
hyphal growth vs filamentous growth

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17477]
During our PHIbase session this morning we reilised we didn't know the differenrce between filamentous growth and hyphal growth.

Defined

GO:0030447    filamentous growth 
The process in which a multicellular organism, a unicellular organism or a group of unicellular organisms grow in a threadlike, filamentous shape. PMID:11729141

and
GO:0030448    hyphal growth
Definition 
Growth of fungi as threadlike, tubular structures that may contain multiple nuclei and may or may not be divided internally by septa, or cross-walls.

I'm not sure what is different between these terms.

filamentous appears to include population growth  i.e group of organisms (out of scope for GO?)  in addition to cell level filamentous growth

hyphal growth mentions fungi (but has no taxon restrictions)

Are these  really different processes, and if so how? Who should I ask?

@mah11  are  filaments and hyphae defined differently in FAO?

**Comment by ValWood** [comment]
@CuzickA

**Comment by krchristie** [comment]
There are at multiple types of filamentous growth. In addition to hyphal growth, pseudohyphal growth such as exists in S. cerevisiae, is considered to be filamentous growth. 

I am going to close this ticket because it is a duplicate of an existing ticket. Please put any further comments here:
**Clarify diff between 'hyphal growth' and 'filamentous growth' #13157**


There is also a related ticket:
**Pseudohyphal growth definition is S. cerevisie-specific #13164** 

My recollection is that I was waiting for input on some of these.

**Comment by 123seher** [comment]
Require swimming
Ali
Ahsan
Afzal
Zeeshan
Ambreen
Seher
Next month

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by krchristie** [comment]
@ukemi  - Tagging you to include in rota

**Comment by ValWood** [comment]
I'm trying to establish with certaintly  how hyphal growth differs from filamentous growth. It has become clear that they are differnet from the discussions in the other ticket. However
the definitions  do not make htis distinction clear.

SInce hyphal growht is a type of filamentous growth, follwing a genus differetia hypahl growth should be defined

A type of filamentous growth that "add differentia here"

Currently  the differentia appears to be:
that may contain multiple nuclei and may or may not be divided internally by septa, or cross-walls.

but because the definition says "may or may not contain these differentia" I am struggling to 
figure out what exactly is different from the parent term? There must be some defining criteria that is always present?

**Comment by ValWood** [comment]
In addition, it isn't really clear what we mean by "growth" in this context.

The papers I looked at describing hyphal growth are describing "colony morphology" (this fungus can grow in filamentous/hyphal form. This refers to a population and is really about proliferation (growth plus division). This seems to be out of scope for GO. Note that in GO we only represent an expansion of specific cell-types in GO, not organismal proliferation (population expansion).

When the term "hyphal growth" is used to refer to specific hyphae (-which is within scope for GO),  "hyphal growth" refers to "growth + morphology" not just to growth.  For example, misshapen hyphae would be classed as a problem with hyphal growth. This might be OK, I am never sure. I think I questioned this once and @mah11 said it was OK because growth also has a direction (but this seems to be lacking from the definition of growth?)

**Comment by ValWood** [comment]
I looked at the first two  publications for hyphal growth annotation in QuickGO

so for example, the first candida paper annotation

http://europepmc.org/abstract/MED/19154328
deletion of the Ca2+ transporters that modulate cytosolic [Ca2+] (Mid1, Cch1 or Pmr1) did not affect hyphal length but curve formation was severely reduced in mid1Delta and cch1Delta and abolished in pmr1Delta.

this is referring to hyphal  morphology, not to a size increase.

Some with the second paper annotating HAC1 to "hyphal growth"
http://europepmc.org/abstract/MED/18602013
 In addition, we show that Hac1 plays an important role in regulating the morphology of C. albicans and in the expression of genes encoding cell surface proteins during ER stress, factors that are important in virulence of this fungal pathogen.

again, this is about morphology, not growth.

So I'm not really sure what we are trying to capture with the "hyphal growth" annotations....

**Comment by ValWood** [comment]
closing for
https://github.com/geneontology/go-ontology/issues/13157
