### ISSUE TITLE
Merge GO:0065006  protein-carbohydrate complex assembly into GO:0006486 protein glycosylation ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17473]
Is there a difference between GO:0065006 protein-carbohydrate complex assembly (The aggregation, arrangement and bonding together of proteins and carbohydrates to form a protein-carbohydrate complex.) 
and 
GO:0006486 protein glycosylation (A protein modification process that results in the addition of a carbohydrate or carbohydrate derivative unit to a protein amino acid, e.g. the addition of glycan chains to proteins)  ?

The only paper annotated to GO:0065006
shows glycosylation of HLA, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3092352/figure/fig1/

Thanks, Pascale

**Comment by ukemi** [comment]
I would have thought that the former referred to complexes of proteins and carbohydrates whereas the latter refers to covalent modifications.

**Comment by ValWood** [comment]
We only have a single protein-carbohydrate complex in GO
GO:0071666    Slit-Robo signaling complex

this seems to be a complex that has a heparin-sulphate modification.

Do we really need protein-carbohydrate complex terms at all?

**Comment by hdrabkin** [comment]
I agree with @ukemi . Seems to me GO:0006486 refers to a protein modification, not a complex. A complex to me implies non-covalent interactions between two or more components.

**Comment by pgaudet** [comment]
> this seems to be a complex that has a heparin-sulphate modification.

If it's a modification then it's a PTM, not a complex ? 
'protein-carbohydrate complex assembly' would be some kind of protein-carbohydrate bridging/chaperone activity; I cannot think of examples. 

If nobody has examples then we should probably merge. 

Thanks, Pascale

**Comment by 123seher** [comment]
Eliminate poor illetrateand abnormals

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
