### ISSUE TITLE
NTR: head-tail coupling apparatus

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17474]
In annotation of PMID:24415959, I need a term for 'head-tail coupling apparatus'.

PMID:30032984 provides a better description of the structure:
> The flagellum is anchored to the sperm head through the head-tail coupling apparatus (HTCA), a centrosome-based structure consisting of two cylindrical microtubule-based centrioles and associated components.

name: sperm head-tail coupling apparatus
Def: A centrosome-based structure consisting of two cylindrical microtubule-based centrioles and associated components which anchors the flagellum to the sperm head.
def dbxrefs: PMID:24415959, PMID:30032984, GOC:krc
synonym (EXACT): head-tail coupling apparatus
synonym (RELATED):  HTCA

**Comment by krchristie** [comment]
@ukemi - please include this ticket in the rota

**Comment by ukemi** [comment]
Done
