### ISSUE TITLE
Caspase complexes are not always in the cytosol

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17486]
While examining logically inconsistent models in the Reactome import, we identified an inconsistency where the caspase3 complex was acting in the nucleoplasm in the reactome model, but is defined in GO as acting in the cytosol and being a cytosolic complex. There are references that show the complex can move and be active in the nucleus: PMID:30111833, PMID:22912727. We need to move the caspase complex from the cytosol.

**Comment by deustp01** [comment]
@ukemi, @goodb, I'm back and ready to review the annotations and think about the biology. How do I find the GO-CAM model that triggered the inconsistency report? (Same question for the models derived from these Reactome pathways:
Synthesis_of_Lipoxins_(LX)
Synthesis_of_5-eicosatetraenoic_acids
Apoptotic_cleavage_of_cellular_proteins
Breakdown_of_the_nuclear_lamina
Apoptosis_induced_DNA_fragmentation
Synthesis_of_Leukotrienes_(LT)and_Eoxins(EX)
tRNA_modification_in_the_nucleus_and_cytosol
mentioned in GitHub issue inconsistent model #64
Thanks
Peter

**Comment by ukemi** [comment]
Hi @deustp01. The first thing would be to see if you agree with this ticket that based on the literature and the Reactome models, caspases complexes don't always act in the cytosol. At the Berkeley hackathon, the discussion concluded that we will not look for annotations from these imports at this time (@goodb correct me if I am wrong). So our job will be to look at the newest models and determine if the import was accurate. We should also look at the other inconsistent models to see what we need to modify.

**Comment by goodb** [comment]
@deustp01 You can use the URL pattern that you see below to look up human pathway conversions in noctua-dev based on their reactome identifier.  I pulled them all out for the inconsistent pathways:

Synthesis of Lipoxins (LX) | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-2142700
-- | --
Synthesis of 5-eicosatetraenoic acids | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-2142688
Apoptotic cleavage of cellular proteins | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-111465
Breakdown of the nuclear lamina | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-352238
Apoptosis induced DNA fragmentation | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-140342
Synthesis of Leukotrienes (LT)and Eoxins(EX) | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-2142691
tRNA modification in the nucleus and cytosol | http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-6782315

**Comment by goodb** [comment]
@ukemi whether you want to look at the gpad form of these models or not is a decision for you to make.  We just concluded that, as far as the direct export from Noctua was concerned, the appropriate entity identifiers for the first column there are the new Reactome entities.  The export works as you would expect right now, e.g. http://noctua-dev.berkeleybop.org/download/gomodel:R-HSA-156582/gpad  

Now, if we want to convert reactome entity-centric gpad into e.g. uniprot-centric gpad, that can be done in a separate gpad to gpad conversion process.  From a software perspective this is a cleaner division of labor in the code than hacking reactome-specific work into the general all-noctua gpad export code.  But, if we get to a point where direct reactome model to uniprot gpad support from the client is a priority we can move the logic there.  

If you want me to generate a uniprot-centric gpad file for all the reactome models, just make an issue for me and I'll work on it.

**Comment by ukemi** [comment]
Thanks @goodb. It will certainly be worth looking at then. one of the ultimate goals would be to pick up the Reactome-provided GOC annotations from these models rather than having @deustp01 provide a separate file. I'm betting the models will be better, but still needs the test. Why don't we leave it at us looking at the Reactome entities for now and if it all looks good, we will take the next step. 

I agree that it is a cleaner division. It may eventually allow us to go to not only UniProtKB, but also isoform-specific identifiers.

**Comment by ukemi** [comment]
We are also cluttering up this ticket with extra information. This ticket is specifically about the caspases. I will split out the remaining inconsistent models into a new ticket. Otherwise we will lose this extra info when I make the caspase edits.

**Comment by deustp01** [comment]
Bottom line: Reactome has annotated the generation of a complex composed of fragments of proteolytically cleaved caspase-3 that is formed in the cytosol, and that can translocate to the nucleus where it mediates the cleavage of nuclear target proteins.
Reactome pathway R-HSA-140342 (Apoptosis induced DNA fragmentation [https://reactome.org/PathwayBrowser/#/R-HSA-75153&SEL=R-HSA-140342&PATH=R-HSA-5357801,R-HSA-109581](url) and the [GO-CAM model](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:R-HSA-140342) derived from it.
Specifically, in the Reactome pathway, reaction R-HSA-211219, (T[ranslocation of caspase-3 to the nucleus](https://reactome.org/PathwayBrowser/#/R-HSA-75153&SEL=R-HSA-211219&PATH=R-HSA-5357801,R-HSA-109581)), which is also visible in the GO-CAM model:
  
The “caspase-3” entity in the Reactome translocation event is actually a heterotetramer complex formed in a preceding reaction in which a both subunits of a dimer of full-length caspase-3 proteins are cleaved between residues 175 and 176 to generate amino- and carboxyterminal fragments of the protein, i.e., the final activated caspase-3 entity is actually a complex consisting of two copies of a polypeptide corresponding to residues 1-175 of canonical caspase-3 protein plus two copies of a ;polypeptide corresponding to residues 176-277 of canonical caspase-3 protein. The preceding reaction is R-HSA-418845, “Activation of caspase-3” (https://reactome.org/PathwayBrowser/#/R-HSA-418889&SEL=R-HSA-418845&PATH=R-HSA-5357801,R-HSA-109581,R-HSA-5357769), which is part of a different pathway.
I have not checked the evidence for the formation of the cleaved cytosolic caspase-3 tetramer, but I think this is pretty widely accepted. For the nuclear translocation, the evidence is a J Biol Chem paper from Tony Hunter and colleagues, PMID: 15569692. A snippet from the abstract:
Caspase-3 is thought to play an important role(s) in the nuclear morphological changes that occur in apoptotic cells and many nuclear substrates for caspase-3 have been identified despite the cytoplasmic localization of procaspase-3. Therefore, whether activated caspase-3 is localized in the nuclei and how active caspase-3 has access to its nuclear targets are important and unresolved questions. Here we confirmed nuclear localizations for both caspase-3-p17 and caspase-3-p12 subunits of active caspase in apoptotic cells using subcellular fractionation analysis.
Naïve questions: does the GO-CAM import capture the caspase-3 cleavage products and the formation of the complex? (The cleavage may count as a post-translational modification and not be captured, and the complex may look like a homodimer or homotetramer and thus not be captured?) Would this lumping of various forms of caspase-3

**Comment by ukemi** [comment]
Bottom bottom line. I think you confirm (and I agree) that the 'caspase complex' can act and is found sometimes in the nucleus. Therefore we need to remove the cytosolic restriction in the ontology.
