### ISSUE TITLE
GO:0061631 "ubiquitin conjugating enzyme activity" queries

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17499]
1. Are we able to add an EC xref to this term?  "E2 ubiquitin-conjugating enzyme" (https://enzyme.expasy.org/EC/2.3.2.23) seems to match, but I'm no expert.
I see there are also a couple of other EC entries related to E2, and maybe that's the issue here?:
(E3-independent) E2 ubiquitin-conjugating enzyme (https://enzyme.expasy.org/EC/2.3.2.24)
N-terminal E2 ubiquitin-conjugating enzyme (https://enzyme.expasy.org/EC/2.3.2.25)

2. I don't why "HECT E3" is given as a synonym (related) for this GO term.  Remove this?

Tagging @hattrill

**Comment by ukemi** [comment]
HECT E3 is a synonym because it doesn't act like a typical E3. It is kind of a hybrid. That's why it is related. See PMID 29858610 and the bit about mechanism.

**Comment by ValWood** [comment]
I  also thought it is a misleading synonym, and I still think it is :)
https://github.com/geneontology/go-ontology/issues/11190

I don't think it is helpful because you wouldn't annotate E3's to this term?

**Comment by ValWood** [comment]
corrected above

**Comment by ukemi** [comment]
OK. Remove the synonym.

**Comment by pgaudet** [comment]
@kaxelsen can explain why this synonym was there - the nomenclature in papers is extremely misleading as well.

**Comment by ValWood** [comment]
It isn't untrue that it is a "related synonym". it is "related" but it isn't helpful for curators. it implies that this is the correct GO term for HECT domain proteins - and it isn't. Therefore it would be better to remove it. 

If we wanted to add the synonym HECT to a GO term it would be to  GO:0061630 (I don't think it can be more specific?)  but it would be better to make a mapping than to add a synonym?

I really think it was originally added to the wrong GO term?

**Comment by kaxelsen** [comment]
Even though "ubiquitin conjugating enzyme activity" is widely used in the literature, I think the term is very imprecise and it is only by looking at the definition that I can understand that it fits, any of the transferase steps carried out by E2 and E3 ligases (EC 2.3.2.23-27 + EC 2.3.2.31). 

I cannot see why especially "HECT E3" is included as a synonym, it is just one of several E3 ligases, and as said above I think they all fit equally well to the definition. So I would simply use the synonyms "E2" and "E3"

**Comment by sjm41** [comment]
Hi @kaxelsen 

Sounds like the GO definition of ubiquitin conjugating enzyme activity (GO:0061631) either needs to be tightened, or GO shouldn't have separate terms for this and ubiquitin protein ligase activity (GO:0061630)?

Below are the current relationships, defs, and pertinent synonyms for those two terms.  (Note that the MetaCyc xref for 'ubiquitin-protein transferase activity (GO:0004842)'is wrong - I'll make a separate ticket for that).

```
ubiquitin-like protein transferase activity (GO:0019787)
|_ubiquitin-like protein conjugating enzyme activity (GO:0061650)
	|_ubiquitin conjugating enzyme activity (GO:0061631)
|_ubiquitin-like protein ligase activity (GO:0061659)
	|_ubiquitin protein ligase activity (GO:0061630)
|_ubiquitin-protein transferase activity (GO:0004842)
	|_ubiquitin conjugating enzyme activity (GO:0061631)
	|_ubiquitin protein ligase activity (GO:0061630)
```

**ubiquitin-protein transferase activity (GO:0004842)**
**Def**: Catalysis of the transfer of ubiquitin from one protein to another via the reaction X-Ub + Y --> Y-Ub + X, where both X-Ub and Y-Ub are covalent linkages.
**Synonyms include**: ubiquitin protein ligase activity (narrow), ubiquitin conjugating enzyme activity (narrow), E2 (related), E3 (related)
**Xrefs include**: KEGG:R03876, MetaCyc:UBIQUITIN--PROTEIN-LIGASE-RXN (=6.2.1.45, i.e. ubiquitin activating enzyme E1)

**ubiquitin conjugating enzyme activity (GO:0061631)**
**Def**:Isoenergetic transfer of ubiquitin from one protein to another via the reaction X-ubiquitin + Y -> Y-ubiquitin + X, where both the X-ubiquitin and Y-ubiquitin linkages are thioester bonds between the C-terminal glycine of ubiquitin and a sulfhydryl side group of a cysteine residue.
**Synonyms**: E2 (related), HECT E3 (related)

**ubiquitin protein ligase activity (GO:0061630)**
**Def**:Catalysis of the transfer of ubiquitin to a substrate protein via the reaction X-ubiquitin + S -> X + S-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the S-ubiquitin linkage is an amide bond: an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate or, in the linear extension of ubiquitin chains, a peptide bond the between the C-terminal glycine and N-terminal methionine of ubiquitin residues.
**Synonyms include**: E3 (related)

**Comment by kaxelsen** [comment]
Hi sjm41,

I now notice the difference between 
ubiquitin-protein transferase activity (GO:0004842) and
ubiquitin conjugating enzyme activity (GO:0061631)
and remember why the synonym "E3 HECT" was added to GO:0061631.

For GO:0061631 it is stated in the definition that ubiquitin is conjugated to Cys residues. This reaction is specific for E2 enzymes, that conjugates ubiquitin to themselves and/or to Cys residues in E3 proteins, but it also true for E3 HECT, since this protein in a first step transfers ubiquitin to a Cys residue in its own HECT domain. In a second step the ubiquitin is then transferred to a Lys in a target protein (cf. GO:0061630). 

For GO:0004842 it is only stated that X-Ub and Y-Ub are covalent linkages, so this GO term covers both E2 and E3 activity and is a parent of GO:0061631 and GO:0061630.

**Comment by sjm41** [comment]
Thanks @kaxelsen - so it looks like the GO definitions and relationships are fine!

I also understand the reason for the HECT E3 synonym now - is there any way of adding Kristian's explanation as a comment/note to GO:0061631 so people can see that in QuickGO/Amigo/the ontology file?  That would help, and might stop folks getting confused by it?

Returning to my original query - is it appropriate to add the EC number(s) I mentioned (and any Rhea IDs??) as xrefs to GO:0061631?  Part of the stimulation for asking is that we found that KEGG annotates E2 enzymes using EC 2.3.2.23, but we couldn't find that EC within GO.
https://www.kegg.jp/dbget-bin/www_bget?ec:2.3.2.23

**Comment by pgaudet** [comment]
What I have done before is add a link from the comments to the relevant ticket, with some header like 'xx synonyms discussion, see [ticket #]' - and while this is not yet in our standard procedures, I suggest we do this for this one. This question comes up often.

Pascale

**Comment by sjm41** [comment]
Hi @hdrabkin 

1. Can we do as Pascale suggested in her 18th June reply - i.e. add a link to this ticket as a 'comment' on the GO:0061631 entry?
2. Do you think we can add EC 2.3.2.23 as a xref to GO:0061631?

**Comment by hdrabkin** [comment]
Sure I can do this today.

**Comment by hdrabkin** [comment]
Hi @sjm41;  I think @balhoff is going to set up a ticket tag for protege so that the ticket # is not loaded into the public GO? So I may hold off on suggestion 1.

**Comment by hdrabkin** [comment]
Added EC 2.3.2.23 as a xref to GO:0061631.

**Comment by sjm41** [comment]
Thanks Harold.

I understand point 1 will have to wait.  (I'll note that I see ~250 mentions of "github.com/geneontology/go-ontology/issues" in the current go-basic.obo file, so there's clearly a precedent for adding such references in comments!)

**Comment by ValWood** [comment]
> (I'll note that I see ~250 mentions of "github.com/geneontology/go-ontology/issues" in the current go-basic.obo file, so there's clearly a precedent for adding such references in comments!)

this has only started happening recently and I have been complaining about it. I doesn't look great 
in  browsers. At least different types of comments are mixed- public facing info, curation advice, ontology changes (often uninterpretable to the average user).

A link to the entire history (like QuickGO ) would be useful, but if we continue displaying these , over the years the edits will drown out the useful comments

**Comment by hdrabkin** [comment]
'the edits will drown out the useful comments'  That's what I worry about (along with global warming, etc.). 
Jim is close to doing something;
