### ISSUE TITLE
Change label 'intracellular' -> 'intracellular region'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17490]
Hello, 

While discussing with @mgiglio99 and @ValWood it occurred to us that the label 'intracellular' sounds odd. Are there objections - or better suggestions - to renaming 'intracellular region'? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
So why is 'intracelluar region' any more 'odd' than intracellular? What is the point here?

**Comment by pgaudet** [comment]
'intracellular' sounds like an adjective - seems like one needs a noun here.

**Comment by ukemi** [comment]
Good practice would be a singular noun, but region implies partonomy to me. What about intracellular component?

**Comment by ukemi** [comment]
Plus region implies a spatial relationship. I don't think all intracellular components are defined spatially.

**Comment by mgiglio99** [comment]
We were thinking of it as a parallel term to 'extracellular region' 
Similar concepts so makes more sense that they be structured the same.
If region works for extracellular seems it would also work for intracellular.

**Comment by ukemi** [comment]
Looking at the defs and structure of the ontology, I guess region would work and fit the defintion.

**Comment by ukemi** [comment]
Maybe tweak the def too??
The living contents of a cell; the matter contained within (but not including) the plasma membrane, usually taken to exclude large vacuoles and masses of secretory or ingested material. In eukaryotes it includes the nucleus and cytoplasm.

The part of a cell contained within (but not including) the plasma membrane, usually taken to exclude large vacuoles and masses of secretory or ingested material. In eukaryotes it includes the nucleus and cytoplasm.

**Comment by ukemi** [comment]
Or maybe the def is ok.

**Comment by mgiglio99** [comment]
I liked your new def better - the phrase "living contents of a cell" feels a bit odd, the contents aren't really living on their own. Yours is cleaner.

**Comment by pgaudet** [comment]
Redundant with #17776
