### ISSUE TITLE
membrane flow/movement /trafficking

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17494]
I can't find anything in GO to represent membrane trafficking.

I want to annotate  Lem2 to some process to  represent membrane movement from the ER to the nucleus. I don't  know where to place such a term?

The only term I can find in the ontology for membrane movement is  "membrane raft localization", but this does not have a suitable parent.

The term I want would be something like:

membrane trafficking between ER and nucelus
plus regulation terms

Any process in which membrane is transported from the ER to the nucleus.
PMID:31015410
Title | Nuclear membrane protein Lem2 regulates nuclear size through membrane flow.
Authors | Kume K, Cantwell H, Burrell A, Nurse P

**Comment by pgaudet** [comment]
membrane organization or a child ?

**Comment by hdrabkin** [comment]
NTR a child of membrane org?

**Comment by ValWood** [comment]
Yes that 'would work. Localization would be a bit weird, but I guess.

**Comment by pgaudet** [comment]
Do you need the 'regulation' terms ? From the abstract 'membrane trafficking between ER and nucleus' would be part of 'GO:0097298 regulation of nucleus size'?

**Comment by ValWood** [comment]
I think we should leave the regulation of size for now.
The abstract says "regulating nuclear size" but I'm not sure this is really the 'regulation' in. the GO sense, it seems to be more of an effector of the. upstream regulation.

I think it is worth waiting for subsequent papers, this is a fairly new topic with little information.

**Comment by raymond91125** [comment]
I think membrane flow / trafficking may be divided into inter-membrane (vesicle dependent?) PMID: 25702105 vs intra-membrane (vesicle independent?) PMID: 23545422. Since ER and nuclear membrane are continuous, it is more about intra-membrane flow or dynamics.

**Comment by ValWood** [comment]
@raymond91125 
>Since ER and nuclear membrane are continuous, it is more about intra-membrane flow or dynamics.

Good point.

In this case,  I think here, since we know nothing as yet about the mechanism
"GO:0010256    endomembrane system organization" 
would be appropriate, and this is already a parent of the terms I used. So in this case I think we should leave this alone until more is known about the mechanism, the important relationship to 'membrane organization' is already captured.
