### ISSUE TITLE
Fly glue term

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17502]
I'd like to add a cc term that relate to the fly glue scretion that they use to attach the pupa to a substrate during metamorphosis. 

cellular component:
puparial glue: A glue which attaches the pupae to the substrate during metamorphosis.
Taxon restriction: Taxid: 7147
PMID:825230 
not quite sure what the parentage should be, as don’t think I would class glue as an extracellular matrix. Perhaps:
is_a
extracellular region part

note that the MF puparial glue (sensu Diptera) GO:0008141 was obsoleted as it refered to a gene product rather than a function.

**Comment by ukemi** [comment]
There are other things like barnacles and seaweed that attach to substrates. Do you think that is is worth have a more general term like 'extracellular adhesive component' that would be a child of extracellular region. I don't know much about the nature of these things, but I will poke around the literature. I'm not sure they all have gene products in them.

**Comment by hattrill** [comment]
I did have a similar thought. I'd be happy with term like that...I was thinking along the lines of bioadhesive - there is a lot of excitement to do with mussel bioadhesive.

**Comment by ukemi** [comment]
A quick search on holdfast (how's that for digging up ancient knowledge?) suggests that they may mediate adhesion by polysaccharides.

**Comment by ukemi** [comment]
I take it back PMID:29250784.

**Comment by hattrill** [comment]
Check this out:  Mussel foot proteins!
PMID:27917020 Recent approaches in designing bioadhesive materials inspired by mussel adhesive protein.

**Comment by hattrill** [comment]
https://en.wikipedia.org/wiki/Bioadhesive
(I am just off out, so don't be sad if I don't immediately reply!)

**Comment by ukemi** [comment]
So how do we distinguish this term from cell adhesion molecules that are responsible for cell-substrate adhesion?

cell adhesion (GO:0007155)---The attachment of a cell, either to another cell or to an underlying substrate such as the extracellular matrix, via cell adhesion molecules. Source: GOC:pf, GOC:hb

protein complex involved in cell adhesion (GO:0098636)--Any protein complex that is capable of carrying out some part of the process of cell adhesion to the cell matrix or to another cell. Source: GOC:dos

**Comment by ukemi** [comment]
No worries.

**Comment by ukemi** [comment]
The second term would actually be a protein containing complex.

**Comment by hattrill** [comment]
I guess this would be extra-organism?

**Comment by ukemi** [comment]
protein complex involved in cell-matrix adhesion (GO:0098637)--Any protein complex that is capable of carrying out some part of the process of cell-matrix adhesion. Source: GOC:dos

But then is it a cellular component or an anatomical structure?

**Comment by hattrill** [comment]
I am not sure if protein complex is the route to go down. Thinking about it, it is more of a type of extracellular matrix - more of a meshwork, an apical secretion that hardens - so perhaps this is it's home. I guess a bit like "organomineral extracellular matrix" - which seems to mean a bird/reptile type egg shell.

**Comment by ukemi** [comment]
OK. Adding 'adhesive extracellular matrix' with a narrow synonym 'puparial glue'. Once I merge, this ticket will close. If you don't like what I did, reopen it and we can revisit. You can look at the pull request and file diff by clicking on the link that will show up when I add it.
