### ISSUE TITLE
Incorrect MetaCyc xref on ubiquitin-protein transferase activity (GO:0004842)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17501]
MetaCyc xref points to:
https://biocyc.org/META/NEW-IMAGE?type=NIL&object=UBIQUITIN--PROTEIN-LIGASE-RXN

which corresponds to EC:6.2.1.45 ( E1 ubiquitin-activating enzyme)

But the GO term is for ubiquitin transferase activity (E2/E3), so that MetaCyc xref should be removed/changed.

**Comment by sjm41** [comment]
Relates to #17499

**Comment by pgaudet** [comment]
Just running this by @kaxelsen but that seems right to me.

**Comment by kaxelsen** [comment]
I agree, the MetaCyc x-ref is wrong

**Comment by hdrabkin** [comment]
Metacyc removed; term actually looks more like a grouping term.

**Comment by sjm41** [comment]
Thanks Harold.
