### ISSUE TITLE
transmembrane transport/nulceocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17517]
RGD have quite a few nucleoporins annotated to "transmembrane transport" (mianly by IEA I think

  | Nup62cl | nucleoporin 62 C-terminal like | Rattus norvegicus |   | gene | RGD |  
  | Nup153 | nucleoporin 153 | Rattus norvegicus | nuclear pore complex protein nup pthr23193 | gene | RGD |  
  | Nup205 | nucleoporin 205 | Rattus norvegicus | family not named pthr31344 | gene | RGD |  
  | Nup155 | nucleoporin 155 | Rattus norvegicus | nuclear pore complex protein nup155 pthr10350 | gene | RGD |  
  | Nupl2 | nucleoporin like 2 | Rattus norvegicus | family not named pthr46527 | gene | RGD |  
  | Nup107 | nucleoporin 107 | Rattus norvegicus | nup107-related pthr13003 | gene | RGD
  | Nup62cl | nucleoporin 62 C-terminal like | Rattus norvegicus |   | gene | RGD |  
  | Tsc2 | TSC complex subunit 2 | Rattus norvegicus | tuberin pthr10063 | gene | RGD | 
  | Nup153 | nucleoporin 153 | Rattus norvegicus | nuclear pore complex protein nup pthr23193 | gene | RGD |  
  | Nup205 | nucleoporin 205 | Rattus norvegicus | family not named pthr31344 | gene | RGD

**Comment by pgaudet** [comment]
Shouldn't this be in the annotation tracker?

**Comment by ValWood** [comment]
yep wrong tracker
moving

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/2404
