### ISSUE TITLE
Matrix: large increase in annotations shared between amino acid metabolism and co-factor metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17516]
This intersection used to be *almost* zero.

Now it is  1976

I suspect this is some CHEBI alignment issue

Pombe (used to be zero) now 23

Includes
https://www.pombase.org/gene/SPAC10F6.13c

one problem might be that
2-oxoglutarate metabolic process (GO:0006103)
is_a cofactor meatabolic process.

 2-oxoglutarate  isn't a co-factor is it?

**Comment by pgaudet** [comment]
This relates to CheBI roles @ukemi

**Comment by dsiegele** [comment]
The pathways tab for [CHEBI:16810](https://www.ebi.ac.uk/chebi/pathway.do?chebiId=CHEBI:16810) (2-oxoglutarate(2−)) shows reactions involving ALKBH2 and ALKBH3. human-ALKBH3 is "a structural member of the Fe(II)/2OG-dependent dioxygenase superfamily (PMC1523172). These proteins use 2OG as a co-substrate, not a cofactor.

**Comment by ukemi** [comment]
This one might be fixed in the new ChEBI import generated by ontobot.

**Comment by krchristie** [comment]
This should be fixed now that `cofactor metabolism` has been obsoleted.
