### ISSUE TITLE
divalent inorganic cation transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17514]
GO:0072511 | divalent inorganic cation transport | IBA with P35670 , PTN000642961 , MGI:103297

this copper transporter has a mapping to
divalent inorganic cation transport

but would be better "cation transmembrane transport"?

https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/%7Bids%7D/chart?ids=GO:0006878%2CGO:0060003%2CGO:0072511

(@pgaudet  Pascale is this grouping term even required? it's a sibling to transmembrane transport)

**Comment by pgaudet** [comment]
I dont know if this grouping term is required. AFAIK these come from GOCHE, but 
@ukemi @cmungall :  do we need to replicate the ChEBI hierarchy ? If terms are not useful to biologists (such as this one); can we remove them ? 
Thanks, Pascale

**Comment by ukemi** [comment]
Do we want to be able to distinguish inorganic cations from organic cations and transmembrane transport from just transport? If so, then these terms should stay and I suggest updating annotations. If we don't think those distinctions are necessary and are willing to live with the lack of chemical exhausitveness in the ontology then they can be simplified. If we keep the terms, then it seems like this is an annotation issue.

**Comment by pgaudet** [comment]
I think the question is the 'divalent' part. organic/inorganic seems OK.

**Comment by pgaudet** [comment]
Merge 
GO:0072511 divalent inorganic cation transport -> 0 direct annotations
and 
GO:0015672 monovalent inorganic cation transport -> 10 EXP; ~1000 total

into  GO:0098662 inorganic cation transmembrane transport

**Comment by pgaudet** [comment]
And to be consistent, merge 

GO:0072509 divalent inorganic cation transmembrane transporter activity 
and GO:0015077 monovalent inorganic cation transmembrane transporter activity 
into 
GO:0022890 inorganic cation transmembrane transporter activity

**Comment by pgaudet** [comment]
There are more... 

- GO:0070838 divalent metal ion transport
merge into GO:0030001 metal ion transport


- GO:0072512 trivalent inorganic cation transport 
merge into GO:0006812 cation transport

- GO:0070839 divalent metal ion export 
-> change label to metal ion export
