### ISSUE TITLE
Matrix: TPV creates annotations shared between amino acid metabolism and nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17518]
https://www.ebi.ac.uk/QuickGO/term/GO:0018401
peptidyl-proline hydroxylation to 4-hydroxy-L-proline

Should  not have a parent to "cellular amino acid metabolic process", 
OR "cellular modified amino acid...blah"

GO:0018401  is describing a protein modification

**Comment by ukemi** [comment]
Check to see if amino acid in GO includes amino acid residues in ChEBI.

**Comment by ValWood** [comment]
I don't think it does generally even if it does for this, becasue this the only  protein modification which has this problem ....

It could be fixed by solution (merge)  proposed in
https://github.com/geneontology/go-annotation/issues/2423
if that works?

**Comment by hdrabkin** [comment]
is amino acid metabolism only restricted to free amino acids or does it include amino acids as residues.  I'm having trouble connecting to CHEBI today to check parentage there (times out) 8-(

**Comment by ukemi** [comment]
You can look in GO. The ChEBI import is in the editor's version of the ontology.

**Comment by hdrabkin** [comment]
So still trying to figure out if we want to imply amino acid metabolism is only refering to a free amino acid, as opposed to when it's a residue in a protein.

**Comment by ValWood** [comment]
we do...this has always been the cse. If we didn't ALL protein metabolism would be also amino acid metabolism.
We define amino acid metabolism as referring only to free amino acids.

**Comment by ValWood** [comment]
Actually we don't say this explicitly, but a protein isn't an amino acid.
We have made lots of fixes in the past to prevent  protein metabolism/modifications being descendent of amino acid metabolism.

**Comment by ValWood** [comment]
Hi Harold, there are 2 issues here.

1. The  free amino acid term should  probably not exist .
2. The modification term should not have an amino acid parentage (it has both  cellular protein modification AND amino acid metabolsm)

v

**Comment by hdrabkin** [comment]
It's not very clear it the def. 
So I can 'fix' this by removing peptidyl-proline hydroxylation to 4-hydroxy-L-proline under amino acid metabolism. II can leave the peptidyl-proline hydroxylation parent.

**Comment by deustp01** [comment]
An analogous case that appears to be handled correctly in the process hierarchy is the metabolism of a histidine residue in a protein (actually only in one protein, as far as anyone knows) to convert it to a diphthine residue ([GO:0017179](https://www.ebi.ac.uk/QuickGO/term/GO:0017179)) but never free histidine to form free diphthine.

**Comment by ValWood** [comment]
2 parents need to be removed

GO:0006575    cellular modified amino acid metabolic process

and 
GO:1901605    alpha-amino acid metabolic process

**Comment by hdrabkin** [comment]
peptidyl-proline hydroxylation to 4-hydroxy-L-proline had  
is_a 4-hydroxyproline metabolic process  			     			      		      
Is_a peptidyl-proline hydroxylation

I removed 4-hydroxyproline metabolic process
The other isa_ is fine.

Which term has the parents you speak of ?

**Comment by hdrabkin** [comment]
And the  4-hydroxyproline metabolic process shouldn't be removed.
UniProt has an annotation vi PMID:21998747 where they speak of the metabolism of free 4-hydroxyproline.  (we get an ISO to  the mouse ortholog protein Hoga1 via this paper.

**Comment by hdrabkin** [comment]
Do I think I can close now?

**Comment by ValWood** [comment]
yes you are right. I was confused. I was looking at 4-hydroxyproline metabolic process not the peptidyl term. Closing.
