### ISSUE TITLE
NTR: Galactosaminogalactan biosynthetic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#17525]
Accession: GO:xxxxxx
Name: galactosaminogalactan biosynthetic process
Ontology: biological_process
Synonyms: galactosaminogalactan anabolism, galactosaminogalactan biosynthesis, galactosaminogalactan formation, galactosaminogalactan synthesis, GAG biosynthetic process
Definition: The chemical reactions and pathways resulting in the formation of the exopolysaccharide galactosaminogalactan. GAG is a heteropolysaccharide composed of α-1,4 linked galactose, N-acetyl galactosamine (GalNAc) and galactosamine (GalN).
is_a: GO:0051278 ! fungal-type cell wall polysaccharide biosynthetic process
Source: CHEBI:143889, PMID:173713, PMID:22102815, PMID:24257745, PMID:26492565, PMID:26932183, PMID:27048799, PMID:30667338

**Comment by ukemi** [comment]
Will need to rebuild the ChEBI import.

**Comment by hdrabkin** [comment]
Didn't realize this was still hanging; sorry about that. 
GO:0106218
