### ISSUE TITLE
cyclic-GMP-AMP transmembrane transporter activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17522]
Hi @pgaudet 

I would need 2 GO terms for cGAMP transport across the membrane.

term 1: cyclic-GMP-AMP transmembrane transporter activity
category: Funcrion
Enables the transfer of cyclic-GMP-AMP from one side of a membrane to the other.
child of GO:0015205 nucleobase transmembrane transporter activity

term 2: cyclic-GMP-AMP transmembrane transport
Category: Process
The process in which cyclic-GMP-AMP is transported across a membrane.
child of GO:0015851 nucleobase transport

Here arte the CheBI terms associated with cGAMP

CHEBI:143093 2'-3'-cGAMP
CHEBI:71501 / 3'-3'-cGAMP

Note that RHEA:60464 (for 2',3'-cGAMP) and RHEA:60468 (for 3',3'-cGAMP) have been created for this transporter activity

Cheers

Sylvain

**Comment by pgaudet** [comment]
@sylvainpoux Do you have a reference for these ? What type of transporters is it ? Can you give me the Rhea reactions ? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,
sorry, I forgot to give you the paper: PMID:31126740

RX   PubMed=31126740; DOI=10.1016/j.molcel.2019.05.006;
RA   Ritchie C., Cordova A.F., Hess G.T., Bassik M.C., Li L.;
RT   "SLC19A1 Is an Importer of the Immunotransmitter cGAMP.";
RL   Mol. Cell. 0:0-0(2019).

There are 2 Rhea, but I'm not sure they are yet public:
RHEA:60464 (for 2',3'-cGAMP)
RHEA:60468 (for 3',3'-cGAMP) 

Cheers

Sylvain

**Comment by sylvainpoux** [comment]
Hi Pascale,
well the mechanism is not so clear in my opinion, it is why we finally decided to only create a very generic reaction:

CC   -!- CATALYTIC ACTIVITY:
CC       Reaction=2',3'-cGAMP(out) = 2',3'-cGAMP(in); Xref=Rhea:RHEA:60464,
CC         ChEBI:CHEBI:143093; Evidence={ECO:0000269|PubMed:31126740};
CC       PhysiologicalDirection=left-to-right; Xref=Rhea:RHEA:60465;
CC         Evidence={ECO:0000269|PubMed:31126740};
CC   -!- CATALYTIC ACTIVITY:
CC       Reaction=3',3'-cGAMP(out) = 3',3'-cGAMP(in); Xref=Rhea:RHEA:60468,
CC         ChEBI:CHEBI:71501; Evidence={ECO:0000269|PubMed:31126740};
CC       PhysiologicalDirection=left-to-right; Xref=Rhea:RHEA:60469;
CC         Evidence={ECO:0000269|PubMed:31126740};

Does it help?

Thanks

Sylvain

**Comment by pgaudet** [comment]
No :( 

In GO we have the parent(?) c-GMP-AMP CHEBI:71580

If you want 2',3'-cGAMP and 3',3'-cGAMP then I guess you are asking for 2 MF and 2 BP terms ? 
Otherwise, is there a more general Rhea term I can reference ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
These are the terms I created - let me know if edits are needed. 

+[Term]
+id: GO:0140360
+name: cyclic-GMP-AMP transmembrane transporter activity
+namespace: molecular_function
+def: "Enables the transfer of cyclic-GMP-AMP from one side of a membrane to the other." [PMID:31126740]
+intersection_of: GO:0005215 ! transporter activity
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+intersection_of: transports_or_maintains_localization_of CHEBI:71580 ! c-GMP-AMP
+created_by: pg
+creation_date: 2019-07-02T14:49:32Z
+
+[Term]
+id: GO:0140361
+name: cyclic-GMP-AMP transmembrane import across plasma membrane
+namespace: biological_process
+def: "The directed movement of cyclic-GMP-AMP from outside of a cell, across the plasma membrane and into the cytosol." []
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+intersection_of: transports_or_maintains_localization_of CHEBI:71580 ! c-GMP-AMP
+created_by: pg
+creation_date: 2019-07-02T15:49:24Z

Thanks, Pascale
