### ISSUE TITLE
Transfer Reactome xrefs to new ABC-type transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17534]
Hi @deustp01 
I have created a new grouping term for ABC-type transmembrane transporter activity, GO:0140359. 

You might want to transfer the Reactome x-references from GO:0042626 ATPase-coupled transmembrane transporter activity to this new term. 

Thanks, Pascale

**Comment by deustp01** [comment]
Hi @pgaudet 
I'm not sure how to proceed. The new grouping term looks good, but most of our annotations are not to the old grouping term GO:0042626 ATPase-coupled transmembrane transporter activity, but to children that specify in addition the chemical nature of the ligand that is transported. Should I request new terms that are children of GO:0140359 ABC-type transmembrane transporter activity for each kind of ligand? Or lose this information?
Thanks
Peter

**Comment by pgaudet** [comment]
Strange, I see some direct mappings: 

    R-HSA-266070 
    R-HSA-5362459 
    R-HSA-5223313 
    R-HSA-5387389 
    R-HSA-5683325

<img width="949" alt="image" src="https://user-images.githubusercontent.com/4782928/60455307-5b926a80-9c36-11e9-94db-a625e4809337.png">


Children terms will stay. If you need more specific terms we can create them. 

Thanks, Pascale

**Comment by deustp01** [comment]
I fixed all the instances you found - OK to close this ticket?

**Comment by ValWood** [comment]
Last comment was

> I fixed all the instances you found - OK to close this ticket?

so closing
