### ISSUE TITLE
NTR: regulation terms for vesicle fusion with Golgi apparatus

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#17539]
i would like to please request general, positive, and negative regulation terms for GO:0048280 vesicle fusion with Golgi apparatus

this is in response to the Matrix project.

@ValWood

**Comment by hdrabkin** [comment]
@srengel, do you have a PMID to be used for these?

**Comment by srengel** [comment]
Hi @hdrabkin PMID: 26195667

**Comment by hdrabkin** [comment]
+id: GO:0106214
+name: regulation of vesicle fusion with Golgi apparatus
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of vesicle fusion with Golgi apparatus." [GOC:se, PMID:26195667]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0048280 ! vesicle fusion with Golgi apparatus
+created_by: hjd
+creation_date: 2019-06-27T15:12:22Z
+
+[Term]
+id: GO:0106215
+name: negative regulation of vesicle fusion with Golgi apparatus
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of vesicle fustion with Golgi apparatus." [GOC:se, PMID:26195667]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0048280 ! vesicle fusion with Golgi apparatus
+created_by: hjd
+creation_date: 2019-06-27T15:17:17Z
+
+[Term]
+id: GO:0106216
+name: positive regulation of vesicle fusion with Golgi apparatus
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of vesicle fusion with Golgi apparatus." [GOC:se, PMID:26195667]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0048280 ! vesicle fusion with Golgi apparatus
+created_by: hjd
+creation_date: 2019-06-27T15:20:59Z

**Comment by srengel** [comment]
thanks @hdrabkin !
