### ISSUE TITLE
NTR: regulation terms for glutamine biosynthesis

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17535]
I would like positive and negative regulation terms for GO:0006542 glutamine biosynthetic process. 

ref for reg:PMID:19755423
GOC:ha

While we're on the subject:
GO:0006542 glutamine biosynthetic process has the child:
GO:1901704 L-glutamine biosynthetic process 
as only the L-form is naturally occurring, I don't think we need this.
GO:1901704 L-glutamine biosynthetic process  is also a child of drug metabolic process GO:0017144 - might come from https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18050 roles? - but I do not think this is relevant for GO.

**Comment by ukemi** [comment]
The drug relationship is inferred from a known issue with our use of ChEBI roles. The D- versus L-glutamine is an interesting issue. Although we mostly think that 'the L- form is the biologically relevant form', this might not be completely true. Several chemical databases including ChEBI say that this molecule is a metabolite and from the abstract, there is this publication supporting it being in a biological system. So I think we will keep both D- and L-. I assume you want regulation of the L- enantiomers?
PMID:11043757

**Comment by hattrill** [comment]
Well, that's my textbook biology nuked!

L-enantiomer, please!

**Comment by hdrabkin** [comment]
See https://www.genome.jp/kegg-bin/show_pathway?map=map00471&show_description=show
for pathways using D-glutamine
