### ISSUE TITLE
NTR: regulation terms for histidine biosynthetic process

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#17537]
i would like to please request general, positive, and negative regulation terms for GO:0000105 histidine biosynthetic process..  

this is in response to the Matrix project.

@ValWood

**Comment by krchristie** [comment]
Since these terms got the standard format definitions, I used my own reference (GOC:krc) as the source of the definitions. Let me know if there should be a PMID or if you would like me to credit you @srengel

**Comment by srengel** [comment]
all good @krchristie i don't need credit because i don't feel like i did anything, i only passed along the request; Val identified the need and you implemented it.  :)
