### ISSUE TITLE
Synonyms of GO:0061684 chaperone-mediated autophagy

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#17559]
Hi @RLovering @BarbaraCzub (and @ukemi),

I noticed that GO:0061684 chaperone-mediated autophagy has exact synonyms CMA and CASA. I see you agreed to that in https://github.com/geneontology/go-ontology/issues/16499. However, I think in the past we also agreed that, in general, acronyms should not be exact synonyms, as they are potentially ambiguous. For example, the acronym finder here https://acronyms.thefreedictionary.com shows 205 results for "CMA", 45 alone in the Science and Medicine area. Even CASA is quite ambiguous with 75 results, including e.g. "Cancer-Associated Serum Antigen". 
I can't remember if we resolved to make acronyms broad or related synonyms and/or if we documented that decision anywhere. But I would suggest to fix them for the autophagy term please. Thanks! :-)

**Comment by ukemi** [comment]
Thanks @paolaroncaglia. I will take care of these.
