### ISSUE TITLE
Return "-" to partial EC ids for Xrefs in GO ontology

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#17563]
The "-" are needed for proper linkout to expasy.
MGI has to watch to make sure that any UniProt records where a partial EC is used does not cause propagation of all of the 4 digit ECs that are children.

**Comment by hdrabkin** [comment]
I put a TR in on our side; In digging around in the Ontology file, my removal of these from leaf nodes may actually be enough to fix.
Here is a good one to watch
http://www.informatics.jax.org/marker/MGI:1916968
has multiple ECs coming from multiplle mapped UniProt ids
EC: 2.7.-.-, 2.7.1.140, 2.7.1.151
If we put back the "-" for EC:2.7 , would I suddenly get all of the matching children from 2.7?

**Comment by hdrabkin** [comment]
@sabrinatoro 
I remember that Zfin had an issue with this also in that when we removed the "-" from our entry, MGI and Zfin dropped several thousand EC2GO IEA annotations. 
It appears as if the extra annotations were a result of mappings being generated to any GO term that had an EC id that would be included in the 3 or less EC grouping terms. 
Since then I have been removing all 3 or less digit xrefs from leaf nodes (more specific reactions)
Do you have any additional info that might help our testing?

**Comment by hdrabkin** [comment]
Hi @cmungall , I need to have whatever disallows addition of EC numbers with a '-' in them to start testing their effect on MGI's Ec2GO load.

**Comment by sabrinatoro** [comment]
@hdrabkin : I am not ignoring you! :-) Doug is not in this week, and he is the one who could answer your question. I'll make sure he looks into this when he is back next week!

**Comment by doughowe** [comment]
If you are talking about restoring "-" that appears in EC#s which are aliases in the GO ontology....I don't see how that would affect us.  We get the EC#s from UniProt, and we get the associated GO annotations via application of EC2GO translations.  Now...if the - was left out of the EC2GO file but it was present in the EC# we got from UniProt..that might break things...but it doesn't sound like that is what is being discussed.

**Comment by hdrabkin** [comment]
I asked because both MGI and Zfin noticed a hugh drop in EC2GO when we removed the dashes. (like for mgi, around 10000. These were mappings where a single protein was getting dozens of GO annotations based on the protein record having a 3 digit ec with a dash, and then getting annotations to all of the enzymes in that EC class (If there was a GO id that fell under that class). With the removal of 3 digit ecs from any term other than a grouping term, I hope this won't happen again.

**Comment by doughowe** [comment]
Ya, I have a vague memory of that, but it isn't clear where the GO term alias enters into the creation of annotations.

**Comment by hdrabkin** [comment]
I just remember that all that was done initially was to remove the "-"s, and the next ec2go run removed all of those annotations. MGI does our own ecg20 annotations during our UniProt load. Does Zfin do the same or do you take them separately from somewhere?

**Comment by doughowe** [comment]
We do the same...apply EC2GO locally right after we do our UniProt load.

**Comment by pgaudet** [comment]
Hi @hdrabkin @doughowe 

Are we ready to restore the hyphens for partial EC numbers?

**Comment by hdrabkin** [comment]
Hi @pgaudet. The only way we can test is if some are put in,  which I cannot do because Chris put a block in for new .- entires. (I put in a TR for this at our end but if there are no files that can be tested, the TR is moot). I thought I had pinged him on this ticket.
@cmungall can you lift the block so some can be tested? 
To test this, the entries need to appear or not in the ec2go file. 
I am still finding some 3 digit in non-leaf nodes that did not appear on the orginal report I was working on (3 digit without .-).

**Comment by cmungall** [comment]
I do not know what you mean by block.

I think this is a very simple issue. What is the canonical syntax for non-leaf ECs (i.e. depth D=1, 2, or 3)? I had previously assumed the syntax was to include D digits and `D-1` periods. E.g. `EC:2.7`

However, it seems that in fact the canonical syntax is to always include 3 periods, and to include `4-D` hyphens. E.g. `EC:2.7.-.-`. This is consistent with expasy, identifiers.org, ... (have not checked Rhea cc @amorgat).

This is entirely a syntax issue. I don't know what you mean by MGI propagating, but this has nothing to do with the syntax.

It seems we should restore the dashes for non-leaves. Note this will have the side-effect of re-introducing the dashes for non-leaves in ec2go, since ec2go is derived from go. So we should give some warning. The dashes can be reintroduced programmatically.

**Comment by amorgat** [comment]
Rhea is only linked to "complete" ECs (depth D=4)
UniProt uses hyphens (e.g `EC:2.7.-.-`)

**Comment by pgaudet** [comment]
> I do not know what you mean by block.

Travis check fail when you enter something like EC:1.1.-.-
You need to enter EC:1.1, but then the links to EC do not resolve. 

Can you fix the Travis check so that the syntax required 3 periods and 4 characters (either digits or dash?)

**Comment by hdrabkin** [comment]
Yes, a 'heads up" would be good. I have already put an order for our loads to NOT assign an GO terms mapping for  a 3 digit EC if that is the EC the protein record has  I will push this ahead of time to be ready.

**Comment by pgaudet** [comment]
@balhoff Can you change the Travis checks so that the ECs need this format: 
EC:#.#.#.# 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Wait; if there are any EC.x.y.z, or EC:x.y, or EC:x this would cause the build to fail? We haven't fixed all of these yet (ie, .- added). The fix has to go first right?

**Comment by pgaudet** [comment]
Yes, but the errors in the PR would tell us what to fix - I assumed

**Comment by hdrabkin** [comment]
I could be hundreds; and it would fall on the next push attemp? Chris needs to put the "-" back into the 1, 2, and 3 digit ecs first.
