### ISSUE TITLE
OTR: GO:0000243 commitment complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17560]
Looking at the definitions I wonder if 

GO:0000243 commitment complex
Def: A spliceosomal complex that is formed by association of the U1 snRNP with the 5' splice site of an unspliced intron in an RNA transcript. 
and
https://www.ebi.ac.uk/complexportal/complex/CPX-1418
Def: Formation of this complex is the first defined step in the yeast splicing pathway and is responsible for intron recognition, which targets pre-mRNA to the splicing pathway. Binding of the 5-prime end of U1 snRNP (CPX-23) to the 5-prime splice site through base-pairing forms first a basal complex only dependent on a 5-prime splice site (CC1) and then a more stable second complex dependent on a branchpoint as well as a 5-prime splice site region (CC2). Interactions between the BBP-MUD2 branchpoint-binding complex (CPX-1417) and the U1 snRNP protein PRP40 (P33203) defines a bridge between the two ends of the intron. PRP5 may interact with U1 snRNP and other proteins to bridge the 5' splice site and the UACUAACA box of the pre-mRNA's branchpoint region. It may also recruit U2 snRNP (CPX-26) which binds to the intron branch site of the commitment complex to form the pre-spliceosome in an ATP dependent step.

is actually a
GO:0071010 prespliceosome
Def: A spliceosomal complex that is formed by association of the 5' splice site and the branch point sequence with specific snRNPs. The prespliceosome includes many proteins in addition to those found in the bound snRNPs. Commitment to a given pair of 5' and 3' splice sites occurs at the time of prespliceosome formation. Prespliceosome complexes are not active for splicing, but are instead an early step in the assembly of a spliceosomal complex.

Sandra added both to the CP entry which was flagged up by Darren's attempt to define complexes by LDs as we can only have one child of 'protein complex'. https://github.com/geneontology/go-ontology/issues/15875

Currently, its is_a parent is 
GO:0005684 U2-type spliceosomal complex > GO:0005681 spliceosomal complex

Birgit

**Comment by krchristie** [comment]
To me, the Complex Portal definition, though a bit dense, is consistent with the existing GO definitions, though the CP definition adds more detail about CC1 and CC2.

So all of this part is talking about the commitment complex, which has only the U1 snRNP present in the complex:
> CPX-1418: Formation of this complex is the first defined step in the yeast splicing pathway and is responsible for intron recognition, which targets pre-mRNA to the splicing pathway. Binding of the 5-prime end of U1 snRNP (CPX-23) to the 5-prime splice site through base-pairing forms first a basal complex only dependent on a 5-prime splice site (CC1) and then a more stable second complex dependent on a branchpoint as well as a 5-prime splice site region (CC2). Interactions between the BBP-MUD2 branchpoint-binding complex (CPX-1417) and the U1 snRNP protein PRP40 protein (P33203) defines a bridge between the two ends of the intron. PRP5 may interact with U1 snRNP and other proteins to bridge the 5' splice site and the UACUAACA box of the pre-mRNA's branchpoint region. 

Then this last sentence talks about PRP5 possibly having a rule in recruiting the U2 snRNP to the intron branch site:
> It may also recruit U2 snRNP (CPX-26) which binds to the intron branch site of the commitment complex to form the pre-spliceosome in an ATP dependent step.

Once U2 snRNP joins the complex, we are now talking about the pre-spliceosome. However, everything in CPX-1418 definition seems consistent with it JUST being about the CC, and not encompassing the pre-spliceosome, since the def discusses the role of PRP5, but does not include having the U2 snRNP in the complex yet.

So to me, the CPX-1418 definition looks consistent with, though more detailed than, the GOC definition of commitment complex. I think that the GO term for pre-spliceosome should not be associated with CPX-1418.

**Comment by krchristie** [comment]
Or alternatively, if this portion of the CPX-1418 definition which talks about CC2:
> CPX-1418:  and then a more stable second complex dependent on a branchpoint as well as a 5-prime splice site region (CC2). 
 
If CC2 is meant to be equivalent to the 'pre-spliceosome and encompass both the first and second complexes of splicing, then perhaps this term needs to be split out into two terms to match what we have in GO. 

However, I notice that on the page for CPX-1418, it only lists the U1 snRNP, and NOT the U2 snRNP. So, I'm inclined to think that CPX-1418 is just a more detailed definition for the commitment complex, and does NOT encompass the pre-spliceosome.

**Comment by bmeldal** [comment]
Thanks, Karen. I'll take prespliceosome out of the commitment complex in the CP.
