### ISSUE TITLE
NTR: structural constituent of nuclear membrane?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17582]
I'm trying to assign a function to the nuclear pore. 

As we have terms like "GO:0005199 structural constituent of cell wall" can we have "structural constituent of nuclear membrane?"

PMID:24315095, 27016207 (and many others!)

Note to self: CPX-873/EBI-12593774

**Comment by ValWood** [comment]
GO:0017056 | structural constituent of nuclear pore
 might work?

(It isn't really a structural constituent of the membrane?)

**Comment by deustp01** [comment]
Or maybe structural constituent of nuclear envelope (GO:0005635 nuclear envelope (where the envelope, in turn, is "The **_double_** lipid bilayer enclosing the nucleus and separating its contents from the rest of the cytoplasm ...".

**Comment by bmeldal** [comment]
@ValWood that works for the individual GPS but not the entire complex as it can't be part of itself ;-)

@deustp01 "structural constituent of nuclear envelope": yes, that would work.

If people think it's ok, I'll formulate the term.

**Comment by ValWood** [comment]
I don't think the entire pore is  well-described asa structural component of the nuclear envelope though really ?

We don't have an MF  to describe the role of the  pore itself in the nucleocytoplasmic tansport context. We only have GO:0140142   nucleocytoplasmic carrier activity for the karyopherins.

We discussed having something like "nuclear pore activity" and describing its function precisely during the transport overhaul-  but ended up punting and using the "structural component" term. I guess partly because every individual pore component would require "contributes_to". However, if you are describing the function of the complex maybe we should add a term for this?

**Comment by ukemi** [comment]
@pgaudet, you have done most of the work on the transporters recently. The sticky bit about making an activity is as @ValWood says, then how would we distinguish things like karyopherins? We do have channel activities.

**Comment by ValWood** [comment]
karyopherins are "carriers" and use
https://www.ebi.ac.uk/QuickGO/term/GO:0140142 or children

We can't use "channel" for the nuclear pore. 
i) Channels are 'selective" the nuclear pore isn't selective (the carriers provide selectivity, *everything * goes through the pore.
ii) "channel activity " is defined as a transmembrane transporter. The nuclear pore is not a transmembrane transporter.

**Comment by ukemi** [comment]
i) or the nucleoporins help to make it selective. PMID:26541386; PMID:24066078
ii) I know we had discussed this before, but it could be considered a double-membrane transmembrane transporter. 

Anyways, I don't want to rehash old issues. We should do whatever is in synch with the way you guys modified the transporter part of the ontology, so I await your instructions.

**Comment by ValWood** [comment]
i) yes the nucleoporins  provide selectivity, but the pore itself does not have selectivity

ii) I know we had discussed this before, but it could be considered a double-membrane transmembrane transporter.

No, transmembrane transport requires that something passes through the lipid bilayer. No lipid bilayer is traversed  by the nuclear pore/transport . The cytoplasm is continuous with the nuclear compartment. This is a critical distinction to preserve- nucleocytoplasmic transport and  transmembrane transport are  mutually exclusive processes and are related to totally different processes modules & phenotype)s.

**Comment by bmeldal** [comment]
I'm listening :) (but can't add anything new although veer towards Val's opinion)
and apologise for opening another can of worms ;-)

It's important to remember that I'm annotating the WHOLE nuclear pore machinery and not the individual components.

For now, it has no MF annotation. I'll add it when you found a solution.

**Comment by ukemi** [comment]
This gets a bit weird. Would we have a relationship between mitochondrion and ATP synthesis coupled to proton transport?

**Comment by ukemi** [comment]
I'm not sure we want to add a function for the WHOLE pore.

**Comment by ValWood** [comment]
Why not though?

The MF
proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)
applies to the entire
mitochondrial proton-transporting ATP synthase complex, coupling factor F(o)

but we need to use "contributes_to" with this MF  for each contributing subunit.
The  complex object would not  require "contributes_to" qualifiers.


Quite a number of MF terms in GO are the function of the entire complex?

**Comment by ukemi** [comment]
But is the pore just a complex? Or in the ontology should all cellular components be related to the functions and processes they carry out?

**Comment by ValWood** [comment]
Well people usually refer to is as the "nuclear pore complex"
But I don't know where to draw the line. You could say the same for "kinetochore" and "spindle pole body"

this is how we define complex
A protein complex in this context is meant as a stable set of interacting proteins which can be co-purified by an acceptable method, and where the complex has been shown to exist as an isolated, functional unit in vivo.

The nuclear pore can be isolated, and is a (multi) functional unit.

**Comment by pgaudet** [comment]
Editors meeting: 
- Maybe a function for the nuclear pore would be appropriate, but not 'structural constituent of the nuclear membrane'. What would be its function?

**Comment by pgaudet** [comment]
I like @ValWood 's proposal 

> We discussed having something like "nuclear pore activity" and describing its function precisely during the transport overhaul- but ended up punting and using the "structural component" term. I guess partly because every individual pore component would require "contributes_to". However, if you are describing the function of the complex maybe we should add a term for this?

We could consider renaming the "structural component" term to nuclear pore activity, so the individual subunit's functions would be under transporter activity rather than under 'structural constituent'. 

Pascale

**Comment by ValWood** [comment]
I thought about this more and I think it might be tricky
different parts of the nuclear pore have different functions.
https://www.cell.com/cell/pdf/S0092-8674(16)30048-4.pdf
would it seem odd to see the  nuclear basket described as a transporter or should this be restricted to the channel. etc.

**Comment by bmeldal** [comment]
Before we curated this complex I had a chat with one of Martin Beck's* postdocs at a conference where he was presenting a poster on the latest EM of the pore and he sent me a bunch of relevant papers. They consider the entire pore complex as a unit exactly how we define a complex as the functional unit in the cell that needs all its components to carry out its function.

It's a bit like the proteosome, that has an ATPase subunit and a protease subunit but they need each other to act in protein degradation. In that case it easier as we can assign two, clear catalytic functions. 

But we need something for the NPC along the lines of Val's and Pascale's suggestion..

* leading lab in NPC research at EMBL Heidelberg

**Comment by ValWood** [comment]
The  proteasome is a good analogy. I would not annotate ALL proteasome subunits to "protease activity" only the catalytic core. Although some regulatory subunits  also have independent ubiquitin protease activity.

Here "degradation", which applies to the entire complex is a process, not a function.

So- for the nuclear pore the  process is nucleocytoplasmic transport, and the individual peripheral components may have a transporter function, or some other activity (scaffold, substrate adaptor etc)

**Comment by bmeldal** [comment]
The process for the NPC is clear :) I'm trying to work out if we can assign a function to the whole complex.

**Comment by ukemi** [comment]
@pgaudet. Can you specify which new term we need?

**Comment by pgaudet** [comment]
I am now leaning toward what @ValWood said - probably we can only annotate the entire NPC to a process, not a single function. 

Pascale

**Comment by bmeldal** [comment]
Ok. Closing then.
