### ISSUE TITLE
NTR cytoskeletal protein membrane adaptor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17580]
![rga7_rng10](https://user-images.githubusercontent.com/7359272/60572284-305e6700-9d6d-11e9-933a-76b292534c35.jpg)

I would like to describe  the MF of being a cytoskeletal adaptor which binds to a protein and a membrane lipid

this is both a
GO:0008093	cytoskeletal adaptor activity
and a
GO:0043495    protein membrane anchor 

I suggest calling this 

cytoskeletal protein membrane adaptor

def
Interacting selectively and non-covalently with both a  cytoskeletal protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location.

descendant of 
GO:0043495    protein membrane anchor
GO:0008093	cytoskeletal adaptor activity

dbxref PMID:30840879

narrow synonyms
F-BAR domain adaptor
BAR domain adaptor

~TPV Note that 
“protein biding bridging, is a TPV for the proposed new term and for  the existing  term “protein membrane anchor” because  these bind to a protein and a “membrane lipid”~

**Comment by pgaudet** [comment]
> “protein biding bridging", is a TPV for the proposed new term and for the existing term “protein membrane anchor” because these bind to a protein and a “membrane lipid”

Why ? The definition of “protein biding bridging" states bridging is between a protein and another macromolecule. 

I can add 'lipid binding' (or has_part) as a parent of this new term - let me know. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140362
+name: cytoskeletal protein membrane adaptor activity
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with both a cytoskeletal protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location." [PMID:30840879]
+synonym: "BAR domain adaptor" NARROW []
+synonym: "F-BAR domain adaptor" NARROW []
+is_a: GO:0008093 ! cytoskeletal adaptor activity
+is_a: GO:0043495 ! protein membrane anchor
+created_by: pg
+creation_date: 2019-07-08T14:05:20Z
+

**Comment by ValWood** [comment]
I missed the "ohter macromolecule bit!

**Comment by ValWood** [comment]
I wonder if, now we have this, we don't need this:

anchoring of the mitotic actomyosin contractile ring to the plasma membrane (GO:1903474)

It seems to be more MF than BP

?

**Comment by ValWood** [comment]
the outstanding question here  is if we still require

anchoring of the mitotic actomyosin contractile ring to the plasma membrane (GO:1903474)

because we can use the MF anchoring terms with the BP ring localization terms. This seems to combine both, but the original issue is done.

I will look at 
anchoring of the mitotic actomyosin contractile ring to the plasma membrane (GO:1903474)
to see if is necessary

**Comment by ValWood** [comment]
update 
**anchoring of the mitotic actomyosin contractile ring to the plasma membrane**
is already  obsolete, so this ticket is all done
