### ISSUE TITLE
Streamline the import process

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17586]
It would be really nice if ontology editors didn't need to go through the hassle of generating imports manually. Currently the editors have to run docker, manually check the obo files that are generated and then commit and create pull requests every time they want to change an import. Not all editors can do this.

In my wildest dreams it would be great to have a tool that we called something like 'ontobot' that would regenerate the import files and automatically create a pull request when the new import is available. In addition to providing the comparison of the obo and owl files in the PR, it would be really great if we could somehow have a report of the inferences that change in GO based on the changes in the underlying imports.

**Comment by balhoff** [comment]
@ontobot lives! :-)

Example PR: #17585

**Comment by ukemi** [comment]
It's like a dream come true!
