### ISSUE TITLE
NAD-capping of mRNAs

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17594]
Hi GO,

I would have a series of requests for a very interesting (and complex) topic. A new cap is present in the 5'-end of some mRNAs, both in bacteria and eukaryotes. Interestingly, it plays an opposite role (RNA stabilization in prokaryotes and RNA decay in eukaryotes).

For the moment, I don't request terms for the addition of NAD to RNAs since it is still unclear. It looks like that in bacteria, it can be mediated by the polymerase, but it is still unclear in eukaryotes

Thanks

Sylvain

PS: Pascale suggested to assign Kimberly @keseler  for this request as it concerns RNA capping

1) GO:XXXXXX1 RNA NAD-cap (NAD-forming) hydrolase activity
Category: Function
Catalysis of the reaction: a 5'-end NAD(+)-phospho-ribonucleoside in mRNA + H2O = a 5'-end phospho-ribonucleoside in mRNA + H(+) + NAD(+) 

Decapping enzyme for NAD-capped RNAs: specifically hydrolyzes the nicotinamide adenine dinucleotide (NAD) cap from a subset of RNAs by removing the entire NAD moiety from the 5'-end of an NAD-capped mRNA.

child of: GO:0016818 hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides
PMID:28283058

Xref
Rhea:60880 (not yet public)
Reaction=a 5'-end NAD(+)-phospho-ribonucleoside in mRNA + H2O = a 5'-end phospho-ribonucleoside in mRNA + H(+) + NAD(+) 

2) GO:XXXXXX2 RNA NAD-cap (NMN-forming) hydrolase activity
Category: Function
Catalysis of the reaction: a 5'-end NAD(+)-phospho-ribonucleoside in mRNA + H2O = a 5'-end phospho-adenosine-phospho-ribonucleoside in mRNA + beta-nicotinamide D-ribonucleotide + 2 H(+)

mRNA decapping enzyme that specifically removes the nicotinamide adenine dinucleotide (NAD) cap from a subset of mRNAs by hydrolyzing the diphosphate linkage to produce nicotinamide mononucleotide (NMN) and 5' monophosphate mRNA.

child of: GO:0016818 hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides
PMID:25533955
PMID:31101919

Xref
RHEA:60876 (not yet public)
Reaction=a 5'-end NAD(+)-phospho-ribonucleoside in mRNA + H2O = a 5'-end phospho-adenosine-phospho-ribonucleoside in mRNA + beta-nicotinamide D-ribonucleotide + 2 H(+)

3) we would need to create create a parent term for GO:0031087, GO:0000290 and GO:0036450:

GO:XXXXXX3 RNA decapping
Category: Process
Cleavage of the 5'-cap of a RNA.
child of: GO:0016070 RNA metabolic process
PMID:25533955
PMID:31101919

GO:XXXXXX3 RNA decapping will be parent of:
GO:0031087 deadenylation-independent decapping of nuclear-transcribed mRNA
GO:0000290 deadenylation-dependent decapping of nuclear-transcribed mRNA
GO:0036450 polyuridylation-dependent decapping of nuclear-transcribed mRNA

Maybe specifiy that we talk about  RNA 7-methylguanosine cap for the 3 GO terms above

4) GO:XXXXXX4  NAD-cap decapping
Category: Process
Cleavage of the 5'- NAD-cap of a RNA. The NAD-cap is present at the 5'-end of some RNAs in both bacetria and eukaryotes. While it promotes RNA stability in bacteria, it promotes RNA decay in eukaryotes.
child of GO:XXXXXXX RNA decapping
PMID:28283058
PMID:25533955
PMID:31101919

**Comment by vanaukenk** [comment]
See also #17383

**Comment by vanaukenk** [comment]
Thanks @sylvainpoux for the very thorough term requests.
I'll add all of the requested terms as well as a new term 'methylguanosine-cap decapping' to give a parallel structure to the children of 'RNA decapping'.
I agree with you that, currently, a term for 'NAD capping' is not yet warranted, but we can certainly add it later, if needed.
Note that adding these terms should also close #17383.

**Comment by hdrabkin** [comment]
@vanaukenk , the RHEA:60880   is now available. I can add this to GO:0110152 and remove rhea pending?

**Comment by vanaukenk** [comment]
Yes, please, do.

Thanks @hdrabkin

**Comment by hdrabkin** [comment]
donedid

**Comment by pgaudet** [comment]
I think this is all done. 

@sylvainpoux please reopen if that was not the case.
