### ISSUE TITLE
MP modulation by symbiont of host defense-related PCD

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17597]
GO:0034053
modulation by symbiont of host defense-related programmed cell death

should be
is_a
regulation of
GO:0097300   programmed necrotic cell death

@CuzickA

**Comment by ukemi** [comment]
Is it always programmed necrotic cell death, never apoptotic?

**Comment by ValWood** [comment]
Well this is a tricky one. In the plant community they call the death  "necrotic death" whatever the menchism, because "necrotic lesions" are  what is observed.

The mechanism isn't always clear. In the cese we looked at either  we don't know, or it is referred to as PCD. If it is PCD or not for plants it is necrotic cell death.

Normally In response to a pathogen the plant activates the hypersensitive repsone, a host immune response-  the normal  defense against biotrophs (localized cell killing). 
However this isn't a pathogen process, since the host is doing the activating.

However for necrotrophic fungi  actively switch on  the plant host hypersensitive response  to kill the plant becasue they live on the dead tissue.

It would make sense that if the pathogen is doing the killing  (implied by  this particular term "modulation by symbiont of host defense-related PCD" then it is always "necrotic".

It also seems to completely fit this definition:
GO:0097300    programmed necrotic cell death
Definition (GO:0097300 GONUTS page)
A necrotic cell death process that results from the activation of endogenous cellular processes, such as signaling involving death domain receptors or Toll-like receptors. PMID:21760595

because it is always necrotic.

**Comment by ValWood** [comment]
clarified the comment above a little...

**Comment by pgaudet** [comment]
Does this term only apply to plants ? If you want to describe 'necrotic cell death' I think we need a new term.

**Comment by ValWood** [comment]
We want to use
GO:0034053 modulation by symbiont of host defense-related programmed cell death
to logically define a phenotype.

As far as I can  see, logically 
all
GO:0034053
modulation by symbiont of host defense-related programmed cell death

must be
regulation of GO:0097300 programmed necrotic cell death

which is why we are asking for the parent.


Do symbionts regulate host defenses and cause cell death that isn't necrotic? if the pathogen is causing cell death can it be other?

**Comment by mah11** [comment]
I don't really quite know, but ...

https://doi.org/10.1371/journal.ppat.1000478

and maybe
https://www.ncbi.nlm.nih.gov/pubmed/20191202
https://www.ncbi.nlm.nih.gov/pubmed/12766474
https://www.ncbi.nlm.nih.gov/pubmed/11595833

**Comment by ValWood** [comment]
Hmm. OK yes this doesn't seem quite right.

We can probably use  both  GO:0034053 and GO:0097300  in the logical defs.
At the moment we aren't creating the logical defs, we are just noting the GO terms we think are most appropriate so they are ready.  James is looking into design patterns with Nico.

@CuzickA could you note both of these  GO IDs for this one. We can look closer nearer the time, but I will close this ticket.
