### ISSUE TITLE
tRNA methyltransferase complexes are not always cytosolic

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17603]
This is another issue that crept up in the Reactome alignment work. GO has asserted that tRNA methyltransferase complex is cytosolic, but there are examples of the enzyme working in the nucleus:
PMID:17071714, PMID:30704115, PMID:7430257
Some of these look like monomers. See Reactome R-HSA-6782315 for more referenced examples. Specifically R-HSA-6783454 for a complex.

**Comment by deustp01** [comment]
> Specifically R-HSA-6783454 for a complex.

Anderson, Hinnebusch and colleagues (PMID:9851972) characterized (assays of methylation states of specific tRNAs in mutant and wild-type yeast cells) two components of a yeast complex required for some tRNA methylation (not clear to me that they showed a direct catalytic role for purified complex). The yeast complex is localized to the nucleus. Anderson and colleagues (PMID:16043508) went on to show that the human orthologs of these two proteins can complement the phenotype of mutant yeast strains. They did not describe the subcellular localization of the human proteins.

From these data, Reactome curators annotated a human tRNA methylation reaction and inferred a nuclear location for its participants ([R-HSA-6783492](https://reactome.org/PathwayBrowser/#/R-HSA-6782315&SEL=R-HSA-6783492&PATH=R-HSA-8953854,R-HSA-72306). 

But even if the human inference is wrong, the original yeast work identifies a case that violates the GO only-in-cytosol rule.
