### ISSUE TITLE
Enzymes using NAD+ and NADP+ should be children of enzymes using NAD(P)+

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17607]
In the current hierarchy, enzymes like succinate-semialdehyde dehydrogenase (NAD+) activity, succinate-semialdehyde dehydrogenase (NADP+) activity and succinate-semialdehyde dehydrogenase (NAD(P)+) activity are siblings. The two former types of enzyme should be subclasses of the latter because NAD(P)+ is the grouping term for both. This was noticed as part of the Pathways2GO project while trying to determine necessary MFs in GABA degradation.

**Comment by ukemi** [comment]
While reviewing the ontology editors' documentation, this set of edits may need to be reversed. According to the old editors' documentation the NAD(P) explicitly means the enzyme can use both. This would mean that the NAD(P) terms should be children of the NAD and NADP terms respectively.

**Comment by ukemi** [comment]
The discussion on the ontology call today resulted in Pascale's proposal to remove the NAD(P) NAD(P)H terms from the ontology and when an enzyme can use both substrates annotate to both reactions. 

Rhea does not use the parenthetical chemicals. Searching for CHEBI:25524 and CHEBI:13392 returns no results. 

We need to construct a query to determine how many genes are annotated to the (P) terms.

**Comment by deustp01** [comment]
The rule for vertebrates (and maybe other taxa?) is that an enzyme uses either exclusively NAD+ or exclusively NADP+. The famous exception* is glutamate dehydrogenase (in humans, GLUD1, UniProt P00367) which enables the activity represented as EC:1.4.1.3 and GO:0004353 "glutamate dehydrogenase (NAD(P)+) activity"). A search in Rhea for EC:1.4.1.3, exactly as @ukemi says, gets two sets of reactions, one for NAD+ (15133) and one for NADP+ (11612).

*Even the exception is partial - according to the Devlin textbook, the reaction of 2-oxoglutarate and ammonium to form glutamate uses NADP while the reaction of glutamate to form 2-oxoglutarate and ammonium uses NAD+.

**Comment by ukemi** [comment]
Thinking about this (obsessively, not that I ever do that) with respect to the definitions of the terms, I think that in GO the NAD(P)+/ NAD(P)H terms have to refer to an enzyme that can use one or the other. 

ChEBI: NAD(P)--A coenzyme that may be NAD or NADP.
            NAD (CHEBI:13389) is a NAD(P) (CHEBI:25524)
            NADP (CHEBI:25523) is a NAD(P) (CHEBI:25524)

ChEBI: NAD(P)H--A coenzyme that may be NADH or NADPH.
           NADH (CHEBI:16908) is a NAD(P)H (CHEBI:13392)
           NADPH (CHEBI:16474) is a NAD(P)H (CHEBI:13392)

From GO
 GO:0050463   nitrate reductase [NAD(P)H] activity
def:Catalysis of the reaction: nitrite + NAD(P)+ + H2O = nitrate + NAD(P)H + H+.

GO:0009703  nitrate reductase (NADH) activity
def:Catalysis of the reaction: nitrite + NAD+ + H2O = nitrate + NADH + H+.

If NAD+ is_a NAD(P) and NADH is_a NAD(P)H, then GO:0009703 is_a GO:0050463.

**Comment by ukemi** [comment]
After speaking with @balhoff I decided to test this with the reasoner. If I create a test classes where an input is NAD(P)+ and a second class where the input is NADP+, the latter activity is inferred as a type of the former activity.

This confirms my logic above.
