### ISSUE TITLE
leucocyte terms for taxon constraint

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17613]
Could you put a taxon constrain on:

GO:0002443 | leukocyte mediated immunity
GO:0045321 | leukocyte activation
GO:0050900 | leukocyte migration

I think that the appropriate taxid is Protostomia NCBI:txid33317

(From the CL:
hemocyte (sensu Nematoda and Protostomia) CL:0000387 are the immune cells of inverts (rather than leukocyte CL:0000738 which is a vertebrate thing))

(I haven't exhaustively gone through the GO to look for leukocyte terms, just these nodes looked like good bets for what I was looking at.)

**Comment by pgaudet** [comment]
Taxon constraints should exist !! We just need to get them in the reports.....

**Comment by ukemi** [comment]
Would it make more sense to have these constraints in CL on the cell type and then create valid property chains to inherit them in GO? That way we would be sure not to miss any. 
I don't see any declared taxon constraints in cl.owl.
It would be interesting to devise a hierarchy of taxon restraints  UBERON-CL-GO
@balhoff?

**Comment by pgaudet** [comment]
> Would it make more sense to have these constraints in CL on the cell type 

I thought this was already what was happening.

**Comment by balhoff** [comment]
Like @ukemi I didn't see any taxon constraints in CL. I think @dosumis and @matentzn have been working on CL lately. Any plans for this?

**Comment by dosumis** [comment]
No plans right now - but we should definitely add them.  In the first instance, we should add these terms where the names make this explicit (e.g. hemocyte (sensu Nematoda and Protostomia)) IIRC there are some explicitly arthropod terms too.  Do you have a list of cases where you need this for GO right now?  If so, could you put them on a CL ticket?  Even better if you can do a pull request.

**Comment by ukemi** [comment]
Yes. Some could be inherited from Uberon, a good start but they won't be specific enough for all classes. It just seems like a better strategy to add them to the elemental unit than for GO to have to add them to every term that involves a certain cell type.
But I guess the fix for now is to do that.

**Comment by krchristie** [comment]
taxon constraint was added in CL on 9/6/19 so should appear in next release and then will be available

**Comment by krchristie** [comment]
@hattrill - The CL term for `leucocyte` now has a taxon constraint on it. Has this solved your issue?

I think plans are in the works to allow GO editors to see constraints inherited from other ontologies, but it isn't in place yet.

**Comment by hattrill** [comment]
Thanks.
It would be good if they were explict in the GO (either from a manual or computational route) as the problems we encounter our from other pipelines propagating such terms. Manual annotations are easily fixed, but other keeping on top of other pipelines is hard work and better if they can do the work without us having to step in.

**Comment by krchristie** [comment]
**7/27/2020 - Discussion at Ontology Editors' call**
- @balhoff is already working on a system to import taxon constraints from other ontologies such as the cell ontology and UBERON and have those display in Protege. 
- It would be useful if we can incorporate these constraints in such a way as to make it easy to also display the inherited taxon constraints in annotator tools.

**Comment by pgaudet** [comment]
Hi @krchristie @balhoff 

I see in Protegé that GO:0002443 | leukocyte mediated immunity only has the inferred taxon constraint 'in taxon' only (not (Schizosaccharomyces))

This is not what was requested. Do we need to do something else to address this ticket ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
We are not getting taxon constraints from CL yet. 

@cmungall says it should be done by the next call.

**Comment by pgaudet** [comment]
@balhoff what's the status of this one ?

**Comment by balhoff** [comment]
We now have leukocyte only_in_taxon Verterbrata imported from CL. However this constraint doesn't propagate over any of the relations used to link these terms to leukocyte:

- 'leukocyte mediated immunity': process_has_causal_agent
- 'leukocyte activation': has_input
- 'leukocyte migration': results_in_movement_of.

**Comment by pgaudet** [comment]
Thanks @balhoff 
I wonder if those relations are OK ?

**Comment by dosumis** [comment]
Are they ever used across species?

**Comment by pgaudet** [comment]
What do you mean ?

**Comment by pgaudet** [comment]
Added a RO ticket for process has causal agent: https://github.com/oborel/obo-relations/issues/409

**Comment by pgaudet** [comment]
* 'leukocyte activation': has_input -> maybe this is analogous to 'cell development', so a new relation such as 'results in activation of' may be appropriate ?

**Comment by raymond91125** [comment]
Should we just add the taxon constraints directly in GO for now?

**Comment by hattrill** [comment]
> 

Yes please!

**Comment by raymond91125** [comment]
@pgaudet do you think that's good?

**Comment by pgaudet** [comment]
We could - I would prefer if this worked from CL - I _think_ that the problem is with the relation in the LD: 'process_has_causal_agent' - @balhoff is this correct ?

**Comment by raymond91125** [comment]
@pgaudet do we close this ticket or continue to discuss 'x mediated process' here?
I'm not sure if 'x mediated process' doesn't have the same problem as 'process_has_causal_agent'. We need a way to specify that x or causal agent is part of the organism in which the process takes place.

**Comment by pgaudet** [comment]
Created new ticket
