### ISSUE TITLE
Add Travis check for obsolete GO term definitions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17625]
Hello, 

The definitions of obsolete GO terms should begin with "OBSOLETE. " This was not the case (see #17623). Can we add a Travis check for this ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Not sure who is writing these now, but have tagged who I think are the appropriate people.

**Comment by balhoff** [comment]
@dougli1sqrd implemented this.
