### ISSUE TITLE
GO:0120113    protein localization by the NVT pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17628]
GO:0120113 protein localization by the NVT pathway

Is a transport pathway and is defined

A pathway targeting soluble cytosolic proteins to the vacuole lumen. It uses a selective autophagy receptor protein Nbr1, which is an ortholog of mammalian NBR1, and is remotely related to S. cerevisiae Cvt pathway receptor protein Atg19. Similar to the Cvt pathway, the cargos transported by this pathway are hydrolases, which presumably contribute to the hydrolytic activities in the vacuole lumen. Different from the Cvt pathway, this pathway does not require the macroautophagy machinery, but instead relies on the ESCRT machinery for cargo sequestration. This pathway is observed in the fission yeast S. pombe. PMID:26365378

nit sure why the term name is "localization"

Could we fix this to

cytoplasm to vacuole transport by the NVT pathway

And add the appropriate transport parent(s)

https://github.com/pombase/curation/issues/2464

**Comment by ukemi** [comment]
I think it should still be a protein localization to the vacuole in addition to what you are requesting, don't you?

**Comment by ValWood** [comment]
I'm not sure if all localization is by transport. It might be better to add if requested (this is what Midori does for FYPO). For example I don't know if we need a term for "maintenance" of vacuolar localization (which is the class that most non-transport  localization falls into)

**Comment by ukemi** [comment]
No but in this case, it is a localization. That's all that's required to maintain the subclass relationship.

**Comment by ukemi** [comment]
PS> Not all localization is by transport.

**Comment by ValWood** [comment]
I know. But all transport is localization!
So- do we have any mecahinsms for localization to the vacuole that are not transport? If not we don't require the additional parent (yet). It will need some dort of localization parent but I don't know how specific ist needs to be.

**Comment by deustp01** [comment]
When vesicles form by budding from an intracellular membrane like Golgi or from the plasma membrane, they entrap a bit of adjacent lumenal content, and if that is coupled to a mechanism that concentrates specific entities there, the result is specific entity uptake into a vesicle that is not transport.

**Comment by ValWood** [comment]
Oh, isn't this always some type of vesicle-mediated transport? At least when we are annotating specific genes ? 

Anyway I have no problem with the localization parentage. It's  only that for fission yeast phenotype ontology we don't add terms until required and this seems to work really well (prevents us adding things that would not be used for annotation). I didn't get why we did it  this way  for a while, but it seems to improve the ontology development & the annotation.
