### ISSUE TITLE
Taxon Constraint on GO:0007338 and children to exclude seed plants

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#17635]
I came across some loci in TAIR that were automagically IEA annotated to 
GO:0007338 single fertilization (15 annotations)
and 
GO:0007339 (1 annotation)
Can we EXCLUDE GO:0007338 and its children from being applied to the Spermatophyta (id 58024)

**Comment by hdrabkin** [comment]
Done

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/pull/17649
