### ISSUE TITLE
parentage for membrane transfer MF

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17648]
https://www.ebi.ac.uk/QuickGO/term/GO:0120015

GO:0120015    sterol transfer activity

Definition (GO:0120015 GONUTS page)
Removes a sterol from a membrane or a monolayer lipid particle, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to an acceptor membrane or lipid particle.

I think this term is defined as "intermembrane" sterol transfer

I see we have
GO:0140303    intramembrane lipid transporter activity

but not     intermembrane lipid transporter activity

should we add this term?

**Comment by pgaudet** [comment]
> I see we have
GO:0140303 intramembrane lipid transporter activity
but not intermembrane lipid transporter activity


We have renamed 'intermembrane lipid transporter activity' to 'lipid transfer activity' on 2019-05-18 . 

The issue was that most terms were named 'xx transfer activity', to seems like this is what the people in the field call this activity. 

Is this OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK so  "lipid transfer activity" IS ONLY for intermembrane
I feel it would be less confusing to have this spelled out in the term name but if it cannot be: 

- [ ]  'lipid transfer activity' should be part of  GO:0120009   intermembrane lipid transfer

- [ ] It would also be helpful if the definition mentioned "intermembrane lipid transfer"
It does say this but you need to read it a couple of times ;)

- [ ]  " intermembrane lipid transfer activity" should be *EXACT* not narrow.

**Comment by ValWood** [comment]
GO:0140303   intramembrane lipid transporter activity
should be part_of
GO:0034204    lipid translocation

**Comment by pgaudet** [comment]
* lipid transfer activity' def: added "This results in intermembrane transfer of lipids.". 

* Also added logical definition to 'ATPase-coupled intramembrane lipid transporter activity':
'intramembrane lipid transporter activity'
and 'has part' some 'ATPase activity'

Thanks, Pascale

**Comment by pgaudet** [comment]
Removed obsolete Rhea
https://www.rhea-db.org/reaction?id=14989

@amorgat Has this been replaced by another reaction ?
