### ISSUE TITLE
NTR: very long chain fatty acid elongase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17647]
https://www.pombase.org/reference/PMID:30975915

Catalysis of the reaction: fatty acid (C-20? or longer) + 2-C = fatty acid (C-20? or longer + 2-C).

I would like this term because 

"Therefore, very-long-chain fatty acids
must be synthesized in the cell. Mammalian cells have seven fatty acid
elongase genes (ELVOL1-ELOVL7) (Leonard et al., 2004; Jakobsson
et al., 2006). Several diseases related to fatty acid metabolism, such as
Stargardt muscular dystrophy, ichthyosis and neurological disorders,
have been found in humans (reviewed in Kihara, 2012; Logan and
Anderson, 2014; Agbaga, 2016; Kihara, 2016). In S. cerevisiae, there
are three genes encoding fatty acid elongases: ELO1, ELO2 and ELO3
(Toke and Martin, 1996; Oh et al., 1997). Elo1 catalyzes elongation of
long-chain fatty acids, whereas Elo2 and Elo3 catalyze that of verylong-chain
fatty acids. The double deletion of S. cerevisiae Elo2 and
Elo3 is lethal (Revardel et al., 1995; Silve et al., 1996), indicating
that very-long-chain fatty acids are essential for cell growth.
However, the roles of very-long-chain fatty acids in the
maintenance of intracellular membranes are not well understood."

In pombe too the long chain and the very long chain fatty acids have  very different phenotypes- see the paper above

**Comment by ukemi** [comment]
ping @alanbridge for comments

**Comment by ValWood** [comment]
I think https://github.com/geneontology/go-ontology/issues/18897
probably makes this one obsolete?
so closing
@Antonialock
