### ISSUE TITLE
Courtship behaviors part_of -> is_a

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#17653]
GO currently has:

![image](https://user-images.githubusercontent.com/112839/61804223-73bb6b00-ae2b-11e9-8b03-ee847b1b34f8.png)

It's not clear to me why male courtship behavior is 'part of' courtship behaviour rather than a subClass. For automated classification in phenotype ontologies, it would be much better if this relationship was switched to subClassOf. 

CC @hattrill @Clare72

**Comment by ukemi** [comment]
Seems strange to me too. I'll fix both male and female.
