### ISSUE TITLE
Photoreceptor ontology revisions required

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#17656]
Hi there is a problem in this branch of the ontology, but note that the rearrangements must keep in mind the previous requests made to make sure this domain reflects compound as well as camara eyes #6972, #470

please see the attached screenshot

Cell development terms are usually placed with part_of relations to the equivalent parent cell differentiation term. 
Therefore please add a part_of relation between these
Parent:  GO:0060221 retinal rod cell differentiation
Child:  GO:0046548 retinal rod cell development

Also create the GO term camera-type eye photoreceptor cell development so that the annotations can propagate up the ontology appropriately
 GO:0060219 camera-type eye photoreceptor cell differentiation
 part_of NEW term camera-type eye photoreceptor cell development
is_a GO:0046548 retinal rod cell development

 GO:0042462 eye photoreceptor cell development
is_a NEW term camera-type eye photoreceptor cell development
is_a GO:0046548 retinal rod cell development

Plus remove the direct parent GO:0042462 eye photoreceptor cell development from GO:0046548 retinal rod cell development as this will be a grandparent with the addition of the new GO term
Thanks
Ruth

**Comment by RLovering** [comment]
![Screenshot 2019-07-25 at 12 56 08](https://user-images.githubusercontent.com/12080010/61873673-6ca16500-aede-11e9-8ab7-18be4f44267c.png)

**Comment by ukemi** [comment]
The compound eye shouldn't be a problem, because the retinal rod cells are distinguished. I'll look at this one more closely when I return from my vacation/holidays.

**Comment by RLovering** [comment]
Great, 
also I should have said also add New term as a parent to GO:0046549 retinal cone cell development:
 GO:0042462 eye photoreceptor cell development
is_a NEW term camera-type eye photoreceptor cell development
GO:0046549 retinal cone cell development
and remove the direct parent  GO:0042462 eye photoreceptor cell development as this will be the grandparent

I don't think there are any regulation terms for these to worry about
