### ISSUE TITLE
New term requests:  cellular structures that are formed via liquid-liquid phase transition

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17658]
Request by Balint Meszaros bmeszaros - at- caesar.elte.hu

https://docs.google.com/document/d/19tLY1Hc-zhR-ebE9sOe4K5hUg1iE1MvKEkj_O44_7kc/edit#

Proposed GO terms

 - [x] New term label: TIS granule
Ontology: cellular_component
Definition: A ribonucleoprotein granule located in the cytoplasm that is formed by the RNA-binding protein TIS11B and RNA molecules, enriched in membrane protein-encoding mRNAs with multiple AU-rich elements. TIS granules are reticular meshworks intertwined with the endoplasmic reticulum (ER).
Position in the GO hierarchy: is_a:cytoplasmic ribonucleoprotein granule (GO:0036464)
Where the term has been used: PMID:30449617, PMID:30479375
Synonyms: -
Cross-references:
Wikipedia:     https://en.wikipedia.org/wiki/TIGER_domain
Example protein(s): TIS11B (UniProt:Q07352, PMID:30449617)
------------------------------------------------------------------------------------------------------------------------
 - [x]  New term label: GW-body
Ontology: cellular_component
Definition: A ribonucleoprotein granule located in the cytoplasm and the nucleus. GW-bodies minimally contain the Argonaute2 (Ago2) and TNRC6B proteins, together with specific target RNAs.
Position in the GO hierarchy: is_a:cytoplasmic ribonucleoprotein granule (GO:0036464), regulates:RISC complex (GO:0016442)
Where the term has been used: PMID:29576456, PMID:26930655, PMID:16418578
Synonyms: -
Cross-references: -
Example protein(s): TNRC6B (UniProt:Q9UPQ9, PMID:29576456), AGO2 (UniProt:Q9UKV8, PMID:29576456)
------------------------------------------------------------------------------------------------------------------------
 - [x]  New term label: ~bacterial~ RNP-body
Ontology: cellular_component
Definition: A ribonucleoprotein granule located in the cytoplasm of bacteria, minimally containing the RNase E protein and RNA molecules. Bacterial RNP-bodies are similar to eukaryotic P-bodies and stress granules.
Position in the GO hierarchy: is_a:cytoplasmic ribonucleoprotein granule (GO:0036464)
Where the term has been used: PMID:30197298
Synonyms: BR-body
Cross-references: -
Example protein(s): RNase E (UniProt:Q9A749, PMID:30197298)
-----------------------------------------------------------------------------------------------------------------------
 - [x]   New term label: galectin lattice
Ontology: cellular_component
Definition: A non-stoichiometric protein complex formed by several galectins crosslinking glycosylated ligands to form a dynamic lattice. The galectin lattice modulates receptor kinase signaling and the functionality of membrane receptors, by regulating the diffusion, compartmentalization and endocytosis of plasma membrane glycoproteins and glycolipids.
Position in the GO hierarchy: is_a:protein complex involved in cell-cell adhesion (GO:0098635)
Where the term has been used: PMID:28893908, PMID:30951647, PMID:26092931, PMID:19021578
Synonyms: -
Cross-references: -
Example protein(s): Galectin-3 (UniProt:P17931, PMID:28893908)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: membrane cluster
Ontology: cellular_component
Definition: A multiprotein complex composed of several transmembrane receptors in the plasma membrane (typically glycosylated receptors, immune receptors, cell adhesion receptors, Wnt receptors, and receptor tyrosine kinases) and cytosolic proteins that bind to the intracellular receptor tails. The cluster is stabilized by extracellular ligand oligomerization, domain-domain interactions, and the multivalent binding of the intracellular partners.
Position in the GO hierarchy: is_a:protein-containing complex (GO:0032991). Also this should be a parent term of:
TCR signalosome (GO:0036398)
Wnt signalosome (GO:1990909)
the newly defined “nephrin cluster”
Where the term has been used: PMID:30951647, PMID:25321392, PMID:27056844
Synonyms: -
Cross-references: -
Example protein(s): nephrin (UniProt:O60500, PMID:26553976), N-WASP (UniProt:O00401, PMID:26553976), Nck1 (UniProt:P16333, PMID:26553976), LAT (UniProt:O43561, PMID:27056844), GRB2 (UniProt:P62993, PMID:27056844), SOS1 (UniProt:Q07889, PMID:27056844)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: nephrin cluster
Ontology: cellular_component
Definition: A multiprotein complex composed of several transmembrane nephrin receptors and cytosolic proteins, including N-WASP and Nck1, bound to the intracellular receptor tails. The nephrin cluster is capable of transmitting cell-cell adhesion and associated intracellular signals, and increases the activity of actin regulatory proteins toward actin assembly by the Arp2/3 complex.
Position in the GO hierarchy: is_a:membrane cluster (this is a term that is newly proposed as well. The most specific, currently existing GO terms which should be ancestor for this is “protein-containing complex GO:0032991”). regulates:Arp2/3 protein complex (GO:0005885)
Where the term has been used: PMID:25321392, PMID:30846599, PMID:26553976
Synonyms: nephrin signalosome
Cross-references: -
Example protein(s): nephrin (UniProt:O60500, PMID:26553976), N-WASP (UniProt:O00401, PMID:26553976), Nck1 (UniProt:P16333, PMID:26553976)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: Sam68 nuclear body
Ontology: cellular_component
Definition: Sam68 nuclear bodies (SNBs) are membraneless organelles in the mammalian nucleus, usually observed in the perinucleolar region. SNBs are composed of several proteins and architectural RNAs, segregating into two distinct RNase-sensitive substructures. One substructure is present as a distinct nuclear body, termed the DBC1 body, and the more dynamic substructure including Sam68 joins with the help of the HNRNPL adaptor protein to form the intact SNB.
Position in the GO hierarchy: is_a:nuclear body (GO:0016604), is_a:nuclear protein granule (this is a term that is newly proposed as well. The most specific, currently existing GO terms which should be ancestors for this term are “intracellular non-membrane-bounded organelle GO:0043232” and “protein-containing complex GO:0032991”)
Where the term has been used: PMID:27377249, PMID:11694584
Synonyms: SNB
Cross-references: -
Example protein(s): Sam68 (UniProt:Q07666, PMID:27377249), HNRNPD (UniProt:Q14103, PMID:27377249), HNRNPL (UniProt:P14866, PMID:27377249)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: selective hydrogel-like meshwork formed by FG-nucleoporins
Ontology: cellular_component
Definition: A membraneless protein condensate containing FG-rich nucleoporin repeats, serving as the permeability barrier of nuclear pore complexes in various eukaryotes. This meshwork is composed minimally of Nup98, and controls the exchange between the nucleus and cytoplasm via size-sensitive facilitated translocation.
Position in the GO hierarchy: is_a:protein-containing complex (GO:0032991), is_a:intracellular non-membrane-bounded organelle (GO:0043232), part_of:nuclear pore central transport channel (GO:0044613)
Where the term has been used: PMID:17082456, PMID:25562883
Synonyms: FG particle
Cross-references: -
Example protein(s): Nup98 (UniProt:P52948, PMID:25562883), Nsp1 (UniProt:P14907, PMID:20304795), Nup100 (UniProt:Q02629, PMID:25562883)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: Sec-body
Ontology: cellular_component
Definition: Sec bodies are non-membrane bound stress assemblies that incorporate components of the ER exit sites to protect them during stress, in conjunction with the inhibition of the protein transport through the secretory pathway. Sec bodies contain minimally two members of the Sec protein family, Sec23 and Sec24.
Position in the GO hierarchy: is_a:cytoplasmic protein granule (GO:XXXXXXX - this is a term that is newly proposed as well. The most specific, currently existing GO terms which should be ancestors for this term are “intracellular non-membrane-bounded organelle GO:0043232” and “protein-containing complex GO:0032991”)
Where the term has been used: PMID:25386913, PMID:27874829
Synonyms: -
Cross-references: -
Example protein(s): Sec16 (UniProt:Q5BI67, PMID:25386913) Sec24AB (UniProt:A1Z813, PMID:25386913) Sec23 (UniProt:Q9VNF8, PMID:25386913)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: synaptic vesicle cluster matrix
Ontology: cellular_component
Definition: A membraneless organelle containing synapsins and possibly other proteins, located in the presynaptic cytosol. This synapsin-containing condensate serves as a matrix for neurotransmitter-containing synaptic vesicles (SVs), which form tight clusters. These clusters act as a reservoir from which SVs are drawn for exocytosis during sustained activity.
Position in the GO hierarchy: is_a:intracellular non-membrane-bounded organelle (GO:0043232), part_of:presynaptic cytosol (GO:0099523), regulates:synaptic vesicle (GO:0008021)
Where the term has been used: PMID:29976799, PMID:28279363, PMID:30093586
Synonyms: -
Cross-references: -
Example protein(s): SYN1 (UniProt:P17600, PMID:29976799), SYN2 (UniProt:Q92777, PMID:29976799)
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: cytoplasmic protein granule
Ontology: cellular_component
Definition: A membraneless organelle residing in the cytoplasm, consisting of a non-stoichiometric mixture of proteins forming a dynamic condensate. The organelle might contain other types of macromolecules (typically DNA or RNA), but this is not required for a functioning organelle.
Position in the GO hierarchy: is_a:intracellular protein granule (this is a term that is newly proposed as well. The most specific, currently existing GO terms which should be ancestors for this term are “intracellular non-membrane-bounded organelle GO:0043232” and “protein-containing complex GO:0032991”)
Where the term has been used: PMID:27802129, PMID:30401430, PMID:30661983, PMID:30849390
Synonyms: -
Cross-references: -
Example protein(s): cpeb4 (UniProt:D8V196, PMID:27802129), PrP (UniProt:P04156, PMID:30401430), Amyloid-beta oligomer (UniProt:P05067, PMID:30401430), RIM1 (UniProt:Q9JIR4, PMID:30661983), RIM-BP2 (UniProt:Q9JIR1, PMID:30661983)
Note: This is an umbrella term for membraneless organelles that only require proteins to form in the cytoplasm. These organelles are being described in increasing numbers, and while some specialized ones (such as the Sec body) have individual names, most are solely described in a biophysical/cell biology context without assigning a name to them. Therefore, the proposed term label is not necessarily used in the referenced papers; however, we believe it is an adequate generic term to collectively describe the granules studied in them.
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: nuclear protein granule
Ontology: cellular_component
Definition: A membraneless organelle residing in the nucleus, consisting of a non-stoichiometric mixture of proteins forming a dynamic condensate. The organelle might contain other types of macromolecules (typically DNA or RNA), but this is not required for a functioning organelle.
Position in the GO hierarchy: is_a:nuclear body (GO:0016604), is_a:intracellular protein granule (this is a term that is newly proposed as well. The most specific, currently existing GO terms which should be ancestors for this term are “intracellular non-membrane-bounded organelle GO:0043232” and “protein-containing complex GO:0032991”)
Where the term has been used: PMID:22454397, PMID:24267890, PMID:26286827, PMID:29650702, PMID:30244836
Synonyms: -
Cross-references: -
Example protein(s): TAF15 (UniProt:Q92804, PMID:22454397), EWS (UniProt:Q01844, PMID:22454397), SPOP (UniProt:O43791, PMID:30244836), DAXX (UniProt:Q9UER7, PMID:30244836)
Note: This is an umbrella term for membraneless organelles that only require proteins to form in the nucleus. These organelles are being described in increasing numbers, and most are solely described in a biophysical/cell biology context without assigning a name to them. Therefore, the proposed term label is not necessarily used in the referenced papers; however, we believe it is an adequate generic term to collectively describe the granules studied in them.
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: intracellular protein granule
Ontology: cellular_component
Definition: A membraneless organelle residing in the cytoplasm or the nucleus, consisting of a non-stoichiometric mixture of proteins forming a dynamic condensate. The organelle might contain other types of macromolecules (typically DNA or RNA), but this is not required for a functioning organelle.
Position in the GO hierarchy: is_a:intracellular non-membrane-bounded organelle (GO:0043232), is_a:protein-containing complex (GO:0032991)
Where the term has been used: PMID:28854361
Synonyms: -
Cross-references: -
Example protein(s): HSPB2 (UniProt:Q16082, PMID:28854361)
Note: This is an umbrella term for membraneless organelles that only require proteins to form in the cytoplasm and the nucleus. While most of these experiments establish the subcellular localization of the organelle, several in vitro studies lack this type of information. Furthermore, some macromolecules are able to form the same membraneless organelles in both locations. Therefore, the proposed term label is not necessarily used in the referenced papers; however, we believe it is an adequate generic term to collectively describe the granules studied in them.
------------------------------------------------------------------------------------------------------------------------
 - [] New term label: intracellular DNA/protein granule
Ontology: cellular_component
Definition: A membraneless organelle residing in the cytoplasm or the nucleus, consisting of a non-stoichiometric mixture of DNA and proteins forming a dynamic condensate.
Position in the GO hierarchy: is_a:intracellular non-membrane-bounded organelle (GO:0043232), is_a:protein-DNA complex (GO:0032993)
Where the term has been used: PMID:29976794, PMID:31142647
Synonyms: -
Cross-references: -
Example protein(s): cGAS (Q8N884, PMID:29976794)
Note: This is an umbrella term for membraneless organelles that require DNA in addition to proteins to form in the cytoplasm and the nucleus. While most of these experiments establish the subcellular localization of the organelle, several in vitro studies lack this type of information. Furthermore, some macromolecules are able to form the same membraneless organelles in both locations. Therefore, the proposed term label is not necessarily used in the referenced papers; however, we believe it is an adequate generic term to collectively describe the granules studied in them.

----

**Comment by pgaudet** [comment]
Created 4 terms: 

+[Term]
+id: GO:0140363
+name: TIS granule
+namespace: cellular_component
+is_a: GO:0036464 ! cytoplasmic ribonucleoprotein granule
+property_value: http://purl.org/dc/elements/1.1/description "A ribonucleoprotein granule located in the cytoplasm that is formed by the RNA-binding protein TIS11B and RNA molecules, enriched in membrane protein-encoding mRNAs with multiple AU-rich elements. TIS granules are reticular meshworks intertwined with the endoplasmic reticulum (ER)." xsd:string {xref="PMID:30449617", xref="PMID:30479375", xref="Wikipedia:TIGER_domain"}
+created_by: pg
+creation_date: 2019-07-25T19:20:58Z
+
+[Term]
+id: GO:0140364
+name: GW body
+namespace: cellular_component
+def: "A ribonucleoprotein granule located in the cytoplasm and the nucleus. GW-bodies minimally contain the Argonaute2 (Ago2) and TNRC6B proteins, together with specific target RNAs." [PMID:16418578, PMID:26930655, PMID:29576456]
+synonym: "GW-body" EXACT []
+is_a: GO:0036464 ! cytoplasmic ribonucleoprotein granule
+created_by: pg
+creation_date: 2019-07-25T19:26:48Z
+
+[Term]
+id: GO:0140365
+name: RNP body
+namespace: cellular_component
+def: "A ribonucleoprotein granule located in the cytoplasm of bacteria, minimally containing the RNase E protein and RNA molecules. Bacterial RNP-bodies are similar to eukaryotic P-bodies and stress granules." [PMID:30197298]
+synonym: "BR-body" EXACT []
+is_a: GO:0036464 ! cytoplasmic ribonucleoprotein granule
+created_by: pg
+creation_date: 2019-07-25T19:31:17Z
+
+[Term]
+id: GO:0140366
+name: galectin lattice
+namespace: cellular_component
+def: "A non-stoichiometric protein complex formed by several galectins crosslinking glycosylated ligands to form a dynamic lattice. The galectin lattice modulates receptor kinase signaling and the functionality of membrane receptors, by regulating the diffusion, compartmentalization and endocytosis of plasma membrane glycoproteins and glycolipids." [PMID:19021578, PMID:26092931, PMID:28893908, PMID:30951647]
+is_a: GO:0098635 ! protein complex involved in cell-cell adhesion
+created_by: pg
+creation_date: 2019-07-25T19:35:05Z

----

I have questions about the others.

**Comment by pgaudet** [comment]
Question regarding
- intracellular protein granule
- cytoplasmic protein granule
- nuclear protein granule
- intracellular DNA/protein granule

Those really are the CC that are the terms that are distinguished by the observation that they are formed via liquid-liquid phase transition. This is a newly described process, but according to https://phys.org/news/2018-09-insights-dna-phase.html, it is not clear whether this a really a 'true' process. 

Regardless, these terms are not much distinct from just 'protein-containing complex' and what is different here is how the complexes are created, so if we need these terms, they would rather be processes. I already raised that with Belint, I will ask again. Meanwhile if anyone has suggestions one way or the other they would be welcome @ukemi @bmeldal 

Thanks, Pascale

**Comment by pgaudet** [comment]
Question about the new proposed term 'membrane cluster' and its proposed child 'nephrin cluster'. We do have the BP 'receptor clustering', but I dont think we have any components. Should we create these ? I thought they were not 'true' complexes ie not a fixed stochiometry. 

@vanaukenk @ValWood @ukemi @bmeldal 
Any thoughts on whether these terms should be created ? 

Thanks, Pascale

**Comment by ValWood** [comment]
personal opionion.

I think we should avoid the vague grouping term 'membrane cluster'- because this could open the gate to add any vague group of membrane proteins.

However, it seems that "nephrin cluster" is a name to describe a more complex cellular component in the kidney cells:


"Nephrin is a central component of the glomerular ultrafilter, with both structural and signaling functions. The extracellular domain of nephrin and other components of the slit diaphragm seem to form a porous molecular sieve. The intracellular domain of nephrin is associated with linker proteins, such as CD2-associated protein and Nck proteins that can connect nephrin to the actin cytoskeleton."

Perhaps a different parent could be used. It's difficult because it seems to have a complex role as a sieve, membrane/cytoskeletal anchor (maybe this could be a parent?)

**Comment by ValWood** [comment]
although you should check - is this related to the 

GO:0036053    JSON
glomerular endothelium fenestra
Cellular Component

Definition (GO:0036053 GONUTS page)
A large plasma membrane-lined circular pore that perforates the flattened glomerular endothelium and, unlike those of other fenestrated capillaries, is not spanned by diaphragms; the density and size of glomerular fenestrae account, at least in part, for the high permeability of the glomerular capillary wall to water and small solutes.

which has only CD34 and A0P127 annotated

if so maybe a merge? I have no idea about the biology here!

**Comment by bmeldal** [comment]
Hi Pascale,

I agree, 'membrane cluster' is a bit too generic. Plus, we already have GO:0098796 membrane protein complex and it would be tricky to distinguish between these 2 terms.

**Comment by vanaukenk** [comment]
I agree with @ValWood and @bmeldal 

From the proposed definition, I'm not convinced that 'membrane cluster' adds a heretofore missing concept to the CC ontology.

We could probably expand upon the definition of 'membrane protein complex', though, to be clearer about what can be considered a 'membrane protein complex': 

"Any protein complex that is part of a membrane."

**Comment by pgaudet** [comment]
@vanaukenk How can we improve the definition of 'membrane protein complex'? Would this work: 

"Any protein-containing complex that has a segment located in a membrane (either intrinsically or extrinsically)." ??

**Comment by bmeldal** [comment]
My gut feeling says that any protein-containing membrane complexes are only intrinsic to membrane...

**Comment by deustp01** [comment]
or at least have one or more components that are intrinsic to the membrane?

**Comment by pgaudet** [comment]
> or at least have one or more components that are intrinsic to the membrane?

I thought that was the intended meaning.

**Comment by pgaudet** [comment]
Haven't heard back from Balint. I'll assume this is all good.
