### ISSUE TITLE
GO:0140311    protein sequestering activity parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17654]
GO:0140311    protein sequestering activity

should this be a child of protein binding too?

**Comment by pgaudet** [comment]
It already 'has part' protein binding. 

The reason to do it like this is that if we don't, proteins annotated to 'regulation of protein sequestering activity' will also be inferred to be 'regulation of protein binding'. 

The pb is that we don't see the 'has part' in AmiGO nor QuickGO - we should discuss the implications of adding these. 

Pascale

**Comment by ValWood** [comment]
So if a gene product is sequestering, it is binding. If it has_part binding, it must have other parts- what would these be? The "sequestering activity"  mechanism is only binding (to prevent movement), or is there something else.

I am thinking of 14-3-3 proteins and the like, but are there other mechanisms?

**Comment by ValWood** [comment]
Closing.
