### ISSUE TITLE
NTRs, fork processing-related PMID:30667359

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#17657]
A PomBase community curator, Matt Whitby, has requested two new terms for PMID:30667359:

1. negative regulation of template switch recombination

For this one, I suggest:

name: negative regulation of template switch recombination involved in replication fork processing
def: "Any process that stops, prevents or reduces the frequency, rate or extent of recombination that results in template switching associated with recombination-dependent replication downstream of a replication fork barrier that occurs as part of replication fork processing."
is_a: GO:1903221 ! regulation of mitotic recombination involved in replication fork processing

I gather that template switching in this context is just a thing that happens at some frequency, and is usually deleterious for the cell/organism - I'm not at all sure it's a bona fide genetically programmed "biological process" as GO now defines them, or the adaptive role of the gene products that happen to cause it or let it take place. So I don't feel an immediate need to add a template switching term just so GO:new1 can have a "regulates GO:bp" link. The is_a GO:1903221 link will suffice. For similar reasons, I also have no need for the generic "regulation" or "positive regulation" terms.

2. positive regulation of recombination-dependent DNA replication

In this case, the regulated process may be essentially the same as GO:1990426 ! mitotic recombination-dependent replication fork processing; again, I'm not sure, but if it is the same thing then I'd be happy to use 'positive regulation of mitotic recombination-dependent replication fork processing' as the name and put the suggested text in as a synonym.

Matt suggested "A cellular process in which the restart of DNA replication by homologous recombination is promoted" as a definition; the mention of "restart" does fit with the fork processing context. I am far from an expert in this area, so if you have questions about this or any of the rest of the ticket, I probably won't be able to answer, but will happily forward any to Matt.

For both terms, PMID:28586299 and PMID:31149897 also have some relevant information and could be cited for the defs.

**Comment by krchristie** [comment]
@ukemi - With respect to item #1 in this ticket, I wanted to check with you on if there are any guidelines about adding a regulation term for something that we don't have a non-regulation process term. I do see a few regulation terms without an equivalence axiom, but they are definitely the minority in a quick glance.

**Comment by ukemi** [comment]
Hi @krchristie. It is bad practice to create a regulation term without a core term. We should try to clean up the others you found, or figure out why they are that way.

**Comment by mah11** [comment]
Well, what I think is going on biologically (out-of-depth caveats apply) is that the process of mitotic recombination involved in replication fork processing (GO:1903211) is normally regulated in such a way that template switching -- which I gather would otherwise happen -- is suppressed.

If there is a different way to describe and define this type of regulation, that's fine. But my impression is that it's not exactly the same as simple negative or positive regulation of the entire GO:1903211 process, but there isn't a "template switching" process that meets GO's criteria of being normal and mediated by gene products that have been selected in evolution to carry it out.

That said, it might be OK to add a "template switching" term if you insist, but it should be flagged as do-not-annotate because I don't think it's adaptive or a normal process.

If you need additional information, I cannot provide it myself, but I'm happy to forward any questions to Matt Whitby, who requested these terms (see https://curation.pombase.org/pombe/curs/772e462e74088043/ro/).

Tangent: as a different example of bona fide "regulation of X" where there is no core X, see #12533, although it isn't a model for the present request as the reasons for not having the X BP are somewhat different (and note that GO:0061487 still has not been made obsolete nor merged into GO:0006270; one or the other really should happen).

**Comment by krchristie** [comment]
For item 1. for "**negative regulation of template switch recombination involved in replication fork processing**",  thanks @mah11 for the very helpful comments on the background. 

To me, to make a negative regulation term makes it sound like regulation of a process that occurs normally. What about the idea of calling the term something like 'suppression of template switching' or perhaps even better would be something phrased positively to indicate what is happening instead of what happens when the actual process fails, perhaps something like 'maintenance of template selection involved in replication fork processing'

Then, rather using the standard definition for a negative regulation term, we could come up with a definition that indicates that this is a process that maintains the selection of the appropriate template and that results in template switching when it fails.


For item 2., the suggested term '**positive regulation of recombination-dependent DNA replication**'

> In this case, the regulated process may be essentially the same as GO:1990426 ! mitotic recombination-dependent replication fork processing; again, I'm not sure, but if it is the same thing then I'd be happy to use 'positive regulation of mitotic recombination-dependent replication fork processing' as the name and put the suggested text in as a synonym.

> Matt suggested "A cellular process in which the restart of DNA replication by homologous recombination is promoted" as a definition; the mention of "restart" does fit with the fork processing context. I am far from an expert in this area, so if you have questions about this or any of the rest of the ticket, I probably won't be able to answer, but will happily forward any to Matt.

@mah11 - Could you have Matt consider the term "**GO:1990426 ! mitotic recombination-dependent replication fork processing**" and see if it works for his need, and if not, then write a definition that distinguishes it from this existing term.

**Comment by mah11** [comment]
> To me, to make a negative regulation term makes it sound like regulation of a process that occurs normally. What about the idea of calling the term something like 'suppression of template switching' or perhaps even better would be something phrased positively to indicate what is happening instead of what happens when the actual process fails, perhaps something like 'maintenance of template selection involved in replication fork processing'

I'd be happy with either wording, although I'd like to make sure it's OK with Matt as well before we proceed.

In fact, it might work well to use your 'maintenance' suggestion as the term name, and include the 'suppression' and 'negative regulation' versions as synonyms (I'm asking for the 'negative regulation' synonym to be included mainly because Matt requested that wording, although it's likely that he was simply following the many examples visible in GO).

Any consequential text definitions edits are likewise fine with me. Matt suggested "A cellular process in which the frequency of template switch recombination associated with recombination-dependent replication downstream of a replication fork barrier is suppressed.", which might already be pretty close.

I'll relay these suggestions to Matt, along with your suggestion/question about using GO:1990426 for the second case.

Thanks for all the ideas!
m

**Comment by mah11** [comment]
I haven't heard back from Matt, so I guess you could proceed as you see fit.

**Comment by mah11** [comment]
at @pgaudet's invitation in the GO meeting, pinging my open tickets

**Comment by krchristie** [comment]
Hi @mah11 

For Item 1. - Going through the discussion in this ticket again, and wanting to create a logical definition that placed it appropriately in the regulation branch, I came up with this term. Let me know if you have any additions or corrections.

+[Term]
+**id**: GO:0120291
+**name**: negative regulation of mitotic recombination involved in replication fork processing
+**namespace**: biological_process
+**def**: "Any process that inhibits or decreases the rate of mitotic DNA recombination during replication fork processing. Suppression of recombination at replication forks is necessary to prevent template switching." [GOC:krc, GOC:mah, PMID:30667359]
+**synonym**: "maintenance of template fidelity during replication fork processing" EXACT []
+**synonym**: "negative regulation of template switch recombination involved in replication fork processing" EXACT []
+**synonym**: "suppression of template switching during replication fork processing" EXACT []
+**intersection_of**: GO:0065007 ! biological regulation
+**intersection_of**: negatively_regulates GO:1903211 ! mitotic recombination involved in replication fork processing
+**intersection_of**: part_of GO:0031297 ! replication fork processing
+**created_by**: krc
+**creation_date**: 2021-01-06T01:21:55Z

Thanks,

-Karen

**Comment by krchristie** [comment]
For Item 2: I created this term.

+[Term]
+**id**: GO:0120292
+**name**: positive regulation of mitotic recombination-dependent replication fork processing
+**namespace**: biological_process
+**def**: "Any process that activates or increases the frequency, rate or extent of replication fork processing that includes recombination between DNA near the arrested fork and homologous sequences. Proteins involved in homologous recombination are required for replication restart." [GOC:krc, GOC:mah, PMID:23093942, PMID:28586299, PMID:31149897]
+**synonym**: "positive regulation of homologous recombination dependent replication fork recovery" RELATED [PMID:23093942]
+**synonym**: "positive regulation of homologous recombination-dependent replication fork processing" EXACT []
+**synonym**: "positive regulation of recombination-dependent DNA replication" EXACT []
+**intersection_of**: GO:0065007 ! biological regulation
+**intersection_of**: positively_regulates GO:1990426 ! mitotic recombination-dependent replication fork processing
+**created_by**: krc
+**creation_date**: 2021-01-06T19:09:21Z

I also added the extra PMIDs you listed as def refs for the first term.

**Comment by mah11** [comment]
Great- it's really nice to have this sorted. Thanks!
