### ISSUE TITLE
transmembrane transporter defs

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17662]
@RLovering pointed out  that the specificity of the transmembrane transporter term is not clear

Primary active transporter of a solute across a membrane, via the reaction: ATP + H2O = ADP + phosphate, to directly drive the transport of a substance across a membrane. The transport protein may be transiently phosphorylated (P-type transporters), or not (ABC-type transporters and other families of transporters). Primary active transport occurs up the solute's concentration gradient and is driven by a primary energy source.

Is this clear that the lipid bilayer needs to be traversed. Should we be more explicit to exclude intramembrane and intermembrane transporters?

**Comment by pgaudet** [comment]
Isn't 'across a membrane' clear ? How would you formulate ?

**Comment by ValWood** [comment]
If flippases are included (as here)
https://github.com/geneontology/go-ontology/issues/17672
then transmembrane is across a membrane or through a membrane.

If flippases are excluded it is only across the bilayer through the membrane.

I don't know exactly how to  word these  topologically different transport events. I will have a think. I might ask my boss  about this, he is knowledgable about transmembrane transport.

**Comment by pgaudet** [comment]
Currently flippases/floppases are NOT under this term: 

 - 'intramembrane lipid transporter activity'
 -- 'ATPase-coupled intramembrane lipid transporter activity'
 --- 'flippase activity'

(just checking that I understood your previous comment correctly). 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't think there is an action here
