### ISSUE TITLE
What should the specificity for tRNA methylation be?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17669]
to capture the processes of
https://github.com/geneontology/go-ontology/issues/17665

I'd be happy with a general term like
tRNA guanine methylation  
and
tRNA cytosine methylation  

although these dont exist. However these do:

tRNA (guanine-N7)-methylation  
tRNA C5-cytosine methylation  
tRNA N1-guanine methylation  
tRNA N2-guanine methylation  
etc

**Comment by ValWood** [comment]
@ukemi Would it make sense for this to be done with
https://github.com/geneontology/go-ontology/issues/17665
by Harold?

**Comment by ukemi** [comment]
I meant to do that!

**Comment by hdrabkin** [comment]
This seem ok; see ticket #17665
