### ISSUE TITLE
NTR tRNA (cytidine 32-2'-O)-methyltransferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17665]
term tRNA (cytosine 32-2'-O)-methyltransferase

def:
Catalysis of the reaction: S-adenosyl-L-methionine + cytosine32 in tRNA= S-adenosyl-L-homocysteine + 2'-O-methylcytidine32 in tRNA

child of
GO:0052666    tRNA (cytosine-2'-O-)-methyltransferase activity

ref: PMID:25404562

(we have tRNA cytosine56-2'-O)-methyltransferase)

**Comment by ValWood** [comment]
@hdrabkin  I don't know if this is right. I'm confused by the reaction?

**Comment by hdrabkin** [comment]
So this specifically methylates the 2' O of C32 in a tRNA; that should be in the def also.  
But this sentence seems confusing
'S. cerevisiae Trm7 interacts separately with Trm732 and Trm734 to 2'-O-methylate three substrate tRNAs at anticodon loop residues C₃₂ and N₃₄, " 
N would be any nucleotide at position 34, so not C specific? 
OR
So Trm7 /Trm732 does one, and Trm7/Trm734 does the other???
Let me try and read this a while.

**Comment by hdrabkin** [comment]
The more I read seems this protein does both C32m AND G34m just like its yeast counterpart. 
So it does have C32m activity AND G34m activity (just not both at once obviously).

**Comment by ValWood** [comment]
I also want the equivalent term for 

GO:0009020    tRNA (guanosine-2'-O-)-methyltransferase activity

I guess it's because this  only works on a restricted set of codons - so presumably
the C is conserved in the codon and the N is variable? I could not figure that either.

It took me ages to figure what Cm was, there was no abbreviation!

**Comment by hdrabkin** [comment]
So the Trm7 /Trm732  does the C32m, and the  Trm7/Trm734 does the G34m
so yes, an term for  tRNA (guanosine32-2'-O-)-methyltransferase activity. 
They do state earlier that it's N34,
Note the C32 is not in the anticodon itself, but a bit earlier in the ac-loop (just coming out of the 5' side of the ac-stem. Position 34, however, IS part of the anticodon itself (34,35, and 36).
I'm always wondering if we want to be this specific (ie, certainly GO:0009020 and GO:0052666 would both still be correctly describing the activities.  
But if we DOt have RNA cytosine56-2'-O)-methyltransferase, may be fair. Note that we decided for the tRNA pseudoU synthases we only have 1 (although there ARE several position specific activites, but all have same mechanism). All of the site-specific reactions are synonyms of the master reaction (this was an ontology editors decision).  Might need to discuss next week on ontology call?

**Comment by ValWood** [comment]
OK, I wondered whether we wanted the specificity, but without it I can't really capture what these do uniquely ... and there does seem to be a precedent.

**Comment by hdrabkin** [comment]
I was going to propose to remove that precedent (tRNA cytosine56-2'-O)-methyltransferase); since we can't' do this for each position.
And we can't do it with a GO-Cam (has input/output) because there are no ids for specific positions in a tRNA. 
But for histone methylases, we DO have terms for specific positions .... . 
We need to be consistent somehow.

**Comment by hdrabkin** [comment]
And even if we did not have the specific terms for the histone methylases, we could just use one general term (ie, histone methylase activity) and after assigning PRO ids for any particular histone position, we could do input (histone X unmethylated at positon N) and output histone X methylated at position N; two separate ids). However, we have no good way to do this with tRNAs

**Comment by ValWood** [comment]
I think we have been here before.  I think the positions are important for tRNA annotation. Otherwise you just have a residue type and you can't distinguish the specific  modification performed by the protein.

**Comment by ValWood** [comment]
I think people really want to keep the histone modifications because of the histone code relationship to different processes. We have discussed this a lot and come to the same conclusion. For the heterochromtin community it would be a big loss if we could not make these distinctions in GO. We do use PRO but  because we use these terms so much it would not be very slick and o would make annotations very unwieldy.
I feel they are appropriate for tRNA too.

**Comment by hdrabkin** [comment]
So we may also need to rethink the tRNA pseudouridine synthase activity (headache). I've put this on the editors discuss for next monday.

**Comment by ValWood** [comment]
I think we need ALL of these activities instantiated into MF

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6321623/figure/ijms-19-03738-f001/

**Comment by hdrabkin** [comment]
And those are just the methylations. I think if we do the methylations we do ALL of the site-specific modifications.

**Comment by ValWood** [comment]
I can't think of another way to specify the activity of these proteins?

**Comment by ValWood** [comment]
This seems to fall clearly into the GO remit of providing functional annotation. It's really useful functional specificity.

**Comment by hdrabkin** [comment]
Having just checked a few in RHEA, they DO have reactions at the specific  position level for 2'O methyl in TRNAs as well as the pseudouridine reactions at different tRNA positions. 
So I will start going ahead with at least these /
This also reflects on #10557, with G residues in tRNA.
@amorgat is that correct and would RHEA agree to make additional?

**Comment by pgaudet** [comment]
Do we want to be perfectly aligned with Rhea for everything ? 
This is certainly not what we decided for transporters - where we decided to keep both P-types and ABC transporters, which Rhea merged. 
It seems to me the opposite may be true in some cases: we may not want the same granularity as Rhea in all areas of GO. 

???

**Comment by ValWood** [comment]
We might not want to fully align with Rhea, but here  I think the MFs are really useful and provide the only way to differentiate these gene products ..... also they are  generally highly conserved so it's a once-only finite task (at least to get the ones we already know about, we still think there are some more lurking in the unknowns).

I'm noticing a resurgence in interest in tRNA related research in fission yeast ....probably because of the link between nutrient level and modification based codon usage and expression programmes.

**Comment by deustp01** [comment]
As I remember the terms of the Geneva Agreement, we follow Rhea strictly for chemicals. Rhea annotates chemical reactions without regard to reaction mechanism, so if two different transporters use entirely different strategies to move a molecule of X from here to there and convert an input molecule of ATP to an output ADP + phosphate, Rhea would have only one reaction for both molecular functions. Here, the chemical entities in the reactions differ in a way that ChEBI and Rhea both recognize in their annotations, so I guess the transporter example does not apply and the Geneva terms suggest that multiple GO molecular function terms are appropriate (not necessarily the conclusion we want).

Or am I oversimplifying? I know we want a mapping between A Rhea reaction and a GO molecular function, but is it required to be 1:1, or are we allowed to say that one GO molecular function can map to a family of related Rhea reactions, thereby asserting that one of the properties of this molecular function (across taxa) is its broad substrate specificity? @ukemi ?

**Comment by ukemi** [comment]
The original idea was to use the Rhea reactions as equivalence axioms for enzymatic activities. This would allow automatic classification of MFs based on participants. We would still need to classify by reaction mechanism manually. This strategy would require a 1:1 mapping of Rhea to MF or it would result in equivalent classes. We can revisit this.

**Comment by ValWood** [comment]
So is a decision made to add these?
If so could I get the single term for this session so I can respond to the author/curator.

**Comment by hdrabkin** [comment]
On an ontology call we agreed that we do not want to go down the path of specifying position in tRNAs.  The fact that there are some terms already in needs to be examined, and we would propose merging those terms into an appropriate parent.

**Comment by ValWood** [comment]
In this case, how do we capture the specificity of the different tRNAs? We will require another system to do this, but it seems to be completely in scope for GO?

**Comment by ValWood** [comment]
I guess we can add to the product line,  so please let us know  when the merges occur,  I will transfer this information to the product lines.

**Comment by hdrabkin** [comment]
We did not think this was within the scope of GO.

**Comment by ValWood** [comment]
I'm confused why this is out of scope since
https://github.com/geneontology/go-ontology/issues/20221

tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity
was added recently.

How do these differ in scope?

**Comment by hdrabkin** [comment]
made terms for C32 and G32
+[Term]
+id: GO:0106339
+name: tRNA (cytidine 32-2'-O)-methyltransferase activity
+id: GO:0106340
+name: tRNA (guanosine 32-2'-O)-methyltransferase activity

**Comment by ValWood** [comment]
Thanks Harold.

I also noticed there is a space missing in this one:
tRNA cytosine56-2'-O)-methyltransferase

**Comment by hdrabkin** [comment]
not anymore!
