### ISSUE TITLE
OTR: name and definition of DNA topoisomerase I-TDRD3 complex

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17667]
In working out what is needed for this request: https://github.com/geneontology/go-ontology/issues/15575, I think we need to fix the name and definition of this term:

**id**: GO:0140225
**name**: DNA topoisomerase I-TDRD3 complex
**def**: A protein complex that has DNA topoisomerase type I and RNA topoisomerase activities.

Tagging @liviap @bmeldal @pgaudet since you all commented on the original NTR ticket.

While I agree with the comments in https://github.com/geneontology/go-ontology/issues/15223, that use of Greek letters is problematic, the name of this term makes it really hard to understand what it is supposed to be. Both of the papers cited for this term call it topoisomerase III-beta. While it is true that topoisomerase III-beta is in the topoisomerase Type IA class, I think it is inconsistent with the published literature to say that the name of this complex is "DNA topoisomerase I-TDRD3 complex". It also seems that just calling this a "topoisomerase I" is misleading. Vertebrate topoisomerase III-beta is a member of the topoisomerase IA subfamily and shouldn't be referred to as a "topoisomerase I", which is generally used as the name of a specific bacterial enzyme which is also a member of the topoisomerase IA subfamily.

Here's a reformatted (web version is hard to read) summary table of topoisomerases from: https://en.wikipedia.org/wiki/Topoisomerase#Classes
![wikiTable-reformatted](https://user-images.githubusercontent.com/10533218/61980217-e868e380-afaa-11e9-964d-fd9f331f3b8d.jpg)
_Note: I've copied the data in this wiki table exactly, except that it is inconsistent with other sources on the Multiplicity of vertebrate (human) type II enzymes, so I've indicated that inconsistency._

Here are the names & synonyms I would suggest:
name: DNA topoisomerase III-beta-TDRD3 complex
synonym (EXACT?): Top3-beta-TDRD3 complex
synonym (RELATED?) - DNA topoisomerase type IA-TDRD3 complex `I'm not committed to this one, but if you want to keep a name similar to the current term name, I think this is better than using the misleading name we are currently using. I could also skip this one entirely.`

Regarding the definition, the existing definition: `A protein complex that has DNA topoisomerase type I and RNA topoisomerase activities.` seems like it is insufficient to distinguish the complex of the vertebrate Top3-beta complex with TDRD3 from any complexes that occur between bacterial topoisomerase III and whatever might help target them to appropriate substrates which also include both DNA and RNA substrates.

**Ahmad et al. 2016**. RNA topoisomerase is prevalent in all domains of life and associates with polyribosomes in animals. Nucleic Acids Res. 44(13):6335-49. PMID:27257063

> Unlike the well-characterized DNA topoisomerases, RNA topoisomerases have received far less attention and their prevalence, function and mechanism of action are largely unknown. To date, only two proteins have been reported to possess topoisomerase activity for RNA–E. coli topoisomerase III (EcoTop3) (3) and human topoisomerase 3β (HumTop3β) (4). Both belong to the Type IA family of topoisomerases, hinting that this family may have dual activities for both DNA and RNA. However, two other members of the type IA family from identical species, E. coli topoisomerase I (EcoTop1) and human topoisomerase 3α (HumTop3α), lack RNA topoisomerase activity. 

As the quote above indicates, there isn't really an obvious grouping class that this existing definition could easily be applied to in order to have a general parent class since only some of the Type IA topo enzymes possess RNA topo activity as well as DNA topo activity.

So, if this term is meant to be specific for the vertebrate topo III-beta-TRDR3 complex, and to exclude any complexes of bacterial topo III, then it seems we have to include composition info consistent with the name of the term, e.g.:

**possible new def**: A protein complex _**comprised of topoisomerase III beta and TDRD3**_ that has DNA topoisomerase type I and RNA topoisomerase activities.

**Comment by liviap** [comment]
Hi @krchristie, 
Thanks a lot for handling that. your suggestion sounds fine to me.
Livia

**Comment by krchristie** [comment]
The more I think about the idea of this synonym:
synonym (RELATED?) - DNA topoisomerase type IA-TDRD3 complex 

I think we should NOT do this since it seems to imply a generic DNA topo of type IA, but this term was requested specifically for a complex that contains Top3beta and not Top3alpha.

**Comment by bmeldal** [comment]
I agree, 

>synonym (RELATED?) - DNA topoisomerase type IA-TDRD3 complex

would be misleading.

(Not that the different, historic, Roman numerals in names and subfamilies aren't misleading in the first place!)

Also in CP: 
[TDRD3-TOP3B type IA topoisomerase complex](https://www.ebi.ac.uk/complexportal/complex/CPX-1621)
[RecQ helicase-Topo III complex](https://www.ebi.ac.uk/complexportal/complex/CPX-1071)
