### ISSUE TITLE
Logical definition of GO:0099186 ('structural constituent of postsynapse') needs fixing

### ISSUE THREAD

**Issue by matentzn** [geneontology/go-ontology#17676]
Currently:

```
'structural molecule activity' and ('part of' some 'postsynapse organization') and ('occurs in' some 'postsynapse assembly')
```

should be:

```
'structural molecule activity' and ('part of' some 'postsynapse organization') and ('part of' some 'postsynapse assembly')
```

('postsynapse assembly' is a biological process -> occurrent. occurs in has range 'independent continuant')

@cmungall @dosumis

**Comment by pgaudet** [comment]
Close ?

**Comment by matentzn** [comment]
I mean, you can close it if you merge the PR https://github.com/geneontology/go-ontology/pull/17677

I am not allowed to do so :P

**Comment by pgaudet** [comment]
'postsynapse assembly' is a 'postsynapse organization'
Do we really need 'structural constituent of postsynapse' to be child of both ? 

Also, structural constituents should not be involved in assembly, or not necessarily, should they?
'structural constituent of presynapse' only has
'structural molecule activity'
 and ('part of' some 'presynapse organization')

While we're at it, can we add a reference for this term ? There are no annotations, so it's hard to tell what it's intended for. Sounds like a CC converted to a MF. Again, comparing with the presynapse term, it seems like we meant 'scaffold', which we have recently merged with 'signaling adaptor activity' (GO:0035591). Would it make sense to move these two terms under there ? 

Thanks, Pascale

**Comment by matentzn** [comment]
This is a question for @dosumis 

I don’t know any of the biology. Just the ontology police :P

**Comment by cmungall** [comment]
Maybe open a new ticket to go over the structural constituent branch, both
w.r.t. use cases, and having a consistent DP?

**Comment by dosumis** [comment]
>  There are no annotations, so it's hard to tell what it's intended for. Sounds like a CC converted to a MF.

IIRC this was one of a set of terms requested by SynGO to annotate proteins required for the structural integrity of synapses and their components.  There are many known structual components of the synapse, so surprising if no annotations. Are the SynGO annotations being kept up to date?

Re patterns: 

I'm responsible for the  "'structural molecule activity' and ('part of' some 'fu organization')" pattern.  I think it makese sense and means that the classification automatically tracks the organization branch, which in turn automatically tracks CC.  

> 'postsynapse assembly' is a 'postsynapse organization'
>  Do we really need 'structural constituent of postsynapse' to be child of both ?

Agree - probably best to just keep it to 'postsynapse organization' and drop the assembly bit.
