### ISSUE TITLE
term request: "Atg8 conjugating enzyme activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17675]
This term is to describe Atg8 conjugating (E2-like) enzymatic activity, as performed by the ATG3 protein.

We already have a term for the E1 (GO:0019779) (=ATG7) and E3 (GO:0019776) (= ATG5-ATG12) enzymes in this cascade.

That E3 term (GO:0019776) is named "Atg8 ligase activity" with def "Catalysis of the covalent attachment of the ubiquitin-like protein Atg8 to substrate molecules; phosphatidylethanolamine is a known substrate." and synonyms including "Atg8 conjugating enzyme activity".

So I guess I'm really suggesting that this existing term to split into 2, to be consistent with how recent literature describes the process.

See PMID: 18704115 & PMID: 28234446 for reviews.  Also see the research papers PMID: 11100732 and PMID: 17986448.  (I'll attach fig 2C from 18704115 to this ticket.)
Also see the UniProt summary for human ATG3: https://www.uniprot.org/uniprot/Q9NT62

I'm not sure how to phrase the definition, but something like "catalyses the transfer of the ubiquitin-like protein ATG8 from the E1 activating enzyme (ATG7) to other substrates, which include phosphatidylethanolamine."

Because the substrate here is not a protein, I don't think this new term can be a child of "ubiquitin-like protein conjugating enzyme activity" (GO:0061650), which is a shame.

The existing 'Atg8 ligase activity' term (GO:0019776) is a direct child of 'transferase activity'.
I'd suggest making a new parent term 'Atg8 transferase activity' as a child of 'transferase activity', and then putting the separate ligase and conjugating terms under that.

@marcfeuermann 

![Screenshot 2019-08-02 at 08 41 53](https://user-images.githubusercontent.com/16306861/62353409-86583300-b502-11e9-886b-0c85e33f786e.png)

**Comment by ValWood** [comment]
PomBAse and SGD both have atg3 annotations to Atg8 ligase activity so we will need to fix these.
An annotation review might be required when the new term is added .

**Comment by pgaudet** [comment]
@sjm41 Do you know if the 'transferase' are just grouping terms? this seems unnecessary and confusing.

**Comment by sjm41** [comment]
The suggestion for new organization of the new ATG8 terms was to mirror what we already have for existing "ubiquitin-like protein transferase activity" terms, i.e.:

```
transferase activity (GO:0016740)
|_acyltransferase activity (GO:0016746)
    |_aminoacyltransferase activity (GO:0016755)
        |_ubiquitin-like protein transferase activity (GO:0019787)
            |_ubiquitin-protein transferase activity (GO:0004842)
                |_ubiquitin conjugating enzyme activity (GO:0061631)
                |_ubiquitin protein ligase activity (GO:0061630)
            |_SUMO transferase activity (GO:0019789)
                |_SUMO conjugating enzyme activity (GO:0061656)
                |_SUMO ligase activity (GO:0061665)
            |_UFM1 transferase activity (GO:0071568)
                |_UFM1 conjugating enzyme activity (GO:0061657)
                |_UFM1 ligase activity (GO:0061666)
            |_NEDD8 transferase activity (GO:0019788)
                |_NEDD8 conjugating enzyme activity (GO:0061654)
                |_NEDD8 ligase activity (GO:0061663)
            |_Atg12 transferase activity (GO:0019777)
                |_Atg12 conjugating enzyme activity (GO:0061651)
                |_Atg12 ligase activity (GO:0061660)
            |_Atg8 ligase activity (GO:0019776)
```

So my suggestion is to make the Atg8 terms look like this:
```
transferase activity (GO:0016740)
|_acyltransferase activity (GO:0016746)
    |_aminoacyltransferase activity (GO:0016755)
        |_ubiquitin-like protein transferase activity (GO:0019787)
            |_Atg8 transferase activity (NEW)
                |_Atg8 conjugating enzyme activity (NEW)
                |_Atg8 ligase activity (GO:0019776)
```

**Comment by sjm41** [comment]
Ah, and there's also an orthogonal classification of these enzymes, by reaction (conjugating vs ligase) rather than by substrate. I think both classifications are valid and useful to maintain.

The organization of that axis including the Atg8 edits would look like this:
```
transferase activity (GO:0016740)
|_acyltransferase activity (GO:0016746)
    |_aminoacyltransferase activity (GO:0016755)
        |_ubiquitin-like protein transferase activity (GO:0019787)
            |_ubiquitin-like protein conjugating enzyme activity (GO:0061650)
                |_ubiquitin conjugating enzyme activity (GO:0061631)
                |_SUMO conjugating enzyme activity (GO:0061656)
                |_UFM1 conjugating enzyme activity (GO:0061657)
                |_NEDD8 conjugating enzyme activity (GO:0061654)
                |_Atg12 conjugating enzyme activity (GO:0061651)
                |_Atg8 conjugating enzyme activity (NEW)
            |_ubiquitin-like protein ligase activity (GO:0061659)
                |_ubiquitin protein ligase activity (GO:0061630)
                |_SUMO ligase activity (GO:0061665)
                |_UFM1 ligase activity (GO:0061666)
                |_NEDD8 ligase activity (GO:0061663)
                |_Atg12 ligase activity (GO:0061660)
                |_Atg8 ligase activity (GO:0019776) <-changed parent
```

**Comment by sjm41** [comment]
Regarding parentage of the Atg8 terms, I see I originally wrote this:
_Because the substrate here is not a protein, I don't think this new term can be a child of "ubiquitin-like protein conjugating enzyme activity" (GO:0061650), which is a shame.
The existing 'Atg8 ligase activity' term (GO:0019776) is a direct child of 'transferase activity'.
I'd suggest making a new parent term 'Atg8 transferase activity' as a child of 'transferase activity', and then putting the separate ligase and conjugating terms under that._

Relationships in the ontology have changed a bit since I wrote that, and the tree currently looks like this:
![Screenshot 2023-06-05 at 11 59 09](https://github.com/geneontology/go-ontology/assets/16306861/4c4f6d85-8158-4de6-91b8-ce5bfaa45379)

Seems like the is_a relationship between "aminoacyltransferase activity (GO:0016755)" and "catalytic activity, acting on a protein (GO:0140096)" should be removed? Then the new Atg8 term relationships I'm suggesting here are fine.

**Comment by pgaudet** [comment]
+name: Atg8-family conjugating enzyme activity
+namespace: molecular_function
+def: "Isoenergetic transfer of an Atg8 family modifer from one protein to a phosphatidylethanolamine or  phosphatidylserine on a membrane, via the reaction X-Atg8 + Y = Y-Atg8 + X." [PMID:11100732, PMID:17986448, PMID:18704115, PMID:28234446]
+synonym: "APG8 conjugating enzyme activity" EXACT []
+synonym: "Atg8 conjugating enzyme activity" NARROW []
+synonym: "Atg8-like conjugating activity" EXACT []
+synonym: "E2" BROAD []
+is_a: GO:0061650 ! ubiquitin-like protein conjugating enzyme activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/17675" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-05T10:10:22Z
+

**Comment by pgaudet** [comment]
> Seems like the is_a relationship between "aminoacyltransferase activity (GO:0016755)" and "catalytic activity, acting on a protein (GO:0140096)" should be removed?  

Good catch, done

**Comment by pgaudet** [comment]
@sjm41 
Since ATG3 links a protein to a lipid, I think the (grand) parent 'catalytic activity, acting on a protein' is OK, isn't it? 

Thanks, Pascale

**Comment by sjm41** [comment]
_Since ATG3 links a protein to a lipid, I think the (grand) parent 'catalytic activity, acting on a protein' is OK, isn't it?_
I agree - (grand) parentage to that term for either the existing "Atg8 ligase activity" term (ATG5-12 complex) or the new "Atg8-family conjugating enzyme activity" term (performed by ATG3) seems OK.

**Comment by sjm41** [comment]
You've probably already done it, but the 2 'conjugating' synonyms should be removed from the ligase term:

id: GO:0019776
name: Atg8 ligase activity
namespace: molecular_function
def: "Catalysis of the covalent attachment of the ubiquitin-like protein Atg8 to substrate molecules; phosphatidylethanolamine is a known substrate." [GOC:mah, PMID:12826404]
synonym: "APG8 conjugating enzyme activity" EXACT []
synonym: "APG8 ligase activity" EXACT []
synonym: "Atg8 conjugating enzyme activity" EXACT []
is_a: GO:0019787 ! ubiquitin-like protein transferase activity

**Comment by marcfeuermann** [comment]
Ubiquitinyl should be ATG8 in the last part of the second reaction.

**Comment by pgaudet** [comment]
@marcfeuermann do you know if these also work via transthioesterification ? (ie is the "S-" correct?

**Comment by sjm41** [comment]
Yes, that seems right (with Marc's edit).

Though the placement of the 'S' in "S-Atg8-[E1 Atg8-family-activating enzyme]-L-cysteine" seems odd - I thought the sulfhydryl group concerned was the one in the cysteine residue of the E1/E2?
