### ISSUE TITLE
NTR: septin collar of invasive hyphae

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17678]
A septin ~ring~ collar  in pathogenic fungi involved in  the constriction of hyphae at  the  plant plasmodesma enabling  penetrate of an adjacent cell.

PMID: 29567712

NTR: septic ring of invasive hyphae

Note that the definition of the parent term is currently too specific
https://www.ebi.ac.uk/QuickGO/term/GO:0005940
A tight ring-shaped structure that forms in the division plane at the site of cytokinesis

because these septin rings are not cytokinesis associated structures.

The parentage looks OK because it doesn't  reference cell division plane.

Note that there is a term
GO:0032161   cleavage apparatus septin structure
which represents the cleavage septins, so it seems that when this term was added the relationships were not fully resolved (AFAIK all cleavage septin structures are septin rings, but I  could be wrong?)

![septin](https://user-images.githubusercontent.com/7359272/62465013-db57ab80-b785-11e9-820d-8d229388afa4.jpg)

**Comment by ukemi** [comment]
So is the action here to add a new term and to tweak the definition of an existing term? If so, what is the definition and placement of the new term and how should the definition be tweaked? Is there a reference for the definition tweak?

**Comment by ValWood** [comment]
1. 
The new term definition is above:

A septic ring in pathogenic fungi involved in the constriction of hyphae at the plant plasmodesma enabling penetrate of an adjacent cell.

2.
The new term is_a septin ring

3.  The exisitng definition need to have the refernece to "cytokinesis" removed. I don't think this requires a definition. I think it is a mistake since we have the term
Any of a series of structures composed of septins and septin-associated proteins localized to the cleavage plane which are involved in cytokinesis. PMID:12101122 PMID:15774761 PMID:16009555

to represent the grouping term for the  septin structures that are involved in cytokinesis

**Comment by ukemi** [comment]
Thanks. Will do this now.

**Comment by ValWood** [comment]
It's a bit confusing because the budding yeast collar and ring are separately defined. Both are involved in cytokinesis.  The collar forms from a ring. It really seems to be a "different shaped ring", it's really just semantics. I don't think that we really need separate grouping terms for collars and rings, but separate grouping terms might be required for cytokinetic vs non-cytokinetic structures.

In fungal pathogens the septin structure may or may not be involved in cytokinsis.
Sone 'rings' are involved in narrowing hyphae. The authors call them "collars"....

**Comment by ValWood** [comment]
see what I mena...

the collar is a 'ring'
![collar](https://user-images.githubusercontent.com/7359272/62548268-702dd800-b85e-11e9-9e0e-85d8f3e4da3e.jpg)

and the ring is a ring ;)

**Comment by ukemi** [comment]
So now I'm confused again. Is what you want exactly what you specified above?

**Comment by ValWood** [comment]
I don't know. All I know is that the new ring/collar isn't a cleavage apparatus.

I now see that this term
https://www.ebi.ac.uk/QuickGO/term/GO:0032173
is not under cleavage apparatus, so it can go under here without causing a true path violation

**Comment by ukemi** [comment]
So I will make the term a collar and put it under the existing one.

**Comment by ValWood** [comment]
Yep sorry. Originally I thought collar and ring were used interchangably. 

The rings will only be cytokinesis, because they only exist after the collar splits.

(In pombe  people only call the structure a septin ring - pre and post split, I have never seen the use of the collar- hence my confusion)
