### ISSUE TITLE
tRNA uridine(34) acetyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17686]
Hi GO,

I would need a GO term for tRNA uridine(34) acetyltransferase activity (which mediates formation of carboxymethyluridine in the wobble base at position 34 in tRNAs)

Thanks

Sylvain

Term: tRNA uridine(34) acetyltransferase activity
Definition: 
Catalysis of the reaction: acetyl-CoA + H2O + S-adenosyl-L-methionine + uridine(34) in tRNA = 5'-deoxyadenosine + carboxymethyluridine(34) in tRNA + CoA + 2 H(+) + L-methionine;

child of GO:0016407 acetyltransferase activity

Xref:
RHEA:61020

PMID:25151136;
PMID:30733442;

**Comment by hdrabkin** [comment]
Cannot find RHEA:61020 in Rhea

**Comment by sylvainpoux** [comment]
Hi Harold,
RHEA:61020 is not yet public. Here is the reaction as it appears in Rhea:

CC   -!- CATALYTIC ACTIVITY:
CC       Reaction=acetyl-CoA + H2O + S-adenosyl-L-methionine + uridine(34)
CC         in tRNA = 5'-deoxyadenosine + carboxymethyluridine(34) in tRNA +
CC         CoA + 2 H(+) + L-methionine; Xref=Rhea:RHEA:61020, Rhea:RHEA-
CC         COMP:10407, Rhea:RHEA-COMP:11727, ChEBI:CHEBI:15377,
CC         ChEBI:CHEBI:15378, ChEBI:CHEBI:17319, ChEBI:CHEBI:57287,
CC         ChEBI:CHEBI:57288, ChEBI:CHEBI:57844, ChEBI:CHEBI:59789,
CC         ChEBI:CHEBI:65315, ChEBI:CHEBI:74882;
CC         Evidence={ECO:0000269|PubMed:25151136};
CC       PhysiologicalDirection=left-to-right; Xref=Rhea:RHEA:61021;
CC         Evidence={ECO:0000269|PubMed:25151136};

Thanks

Sylvain

**Comment by sylvainpoux** [comment]
Hi Harold,
I would like to curate papers related to ELP3 and would like to know if you already created the GO term requested?
Cheers
Sylvain

**Comment by sylvainpoux** [comment]
Hi Harold,

you raise an important question, and I admit that it is difficult to find a good balance and determine to which detail annotate. tRNA modifications are complex and creating a GO term for each position is clearly not a solution.

That said, why have I requested this term?

1) tRNA wobble uridine modification is an important process, there is a GO term for it (GO:0002098).

2) there is already a GO function term for the step following tRNA uridine(34) acetyltransferase activity that I request  (GO:0016300; F:tRNA (uracil) methyltransferase activity)

I therefore consider that it would be useful to have the different steps described in GO

However, it is up to you

Thanks

Sylvain

**Comment by ValWood** [comment]
For what it's worth, I am in favour of these specific  tRNA modification activities if it is the only way to distinguish the activities in the pathway. This is what I was trying to articulate here  
https://github.com/geneontology/go-ontology/issues/17665
but Sylvain provides a good example.

I agreed - but   I wasn't very satisfied with the solution. It really feels like GO is the place for us  to capture this specificity.

**Comment by hdrabkin** [comment]
I have been giving this MUCH thought 
The tRNA position numbering is somewhat invariant; that is, position 54 and 55 is always 54 and 55 regardless of the entire length of the tRNA (note these two positions lie after the variable loop. 
The two areas where the length varies is the D loop (minor variance) and variable region). So when was says T54Psi55, it's understood to be the same position. This is not the case in the modification position of nucleotides in rRNAs, etc. (@krchristie jump in if I'm wrong). 
Thus  34 is always 34, 54 is always 54 (doesn't matter what the tRNA is); 55 is always 55, etc. (EXCEPT for weird mammalian mitochondrial tRNAs, but let's not go there)
Numbering is usually done according to the  'universal conventional' rules set down by
prinzl, M., Horn, C., Brown, M., Ioudovitch, A., and Steinberg, S. (1998). Compilation of tRNA sequences and sequences of tRNA genes. Nucleic Acids Res. 26, 148–153. doi: 10.1093/nar/26.1.148
GIVEN the convention, it might be 'safe'

**Comment by pgaudet** [comment]
Sounds reasonable.

**Comment by krchristie** [comment]
Hi @hdrabkin - I don't object to specifying positions in tRNAs if you feel they are useful. When we discussed this at the ontology editors call a few weeks back, my question was whether the modifications/positions were conserved in tRNAs and it sounds like they are. Representing specific positions of modifications on rRNAs is clearly a different situation.

**Comment by hdrabkin** [comment]
[Term]
+id: GO:0106261
+name: tRNA uridine(34) acetyltransferase activity
