### ISSUE TITLE
zinc ion import into Golgi membrane (GO:1904257)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17697]
This sounds a bit weird:

Definition | Parents
-- | --
The directed import of zinc(2+) from the cytosol across the Golgi membrane into the Golgi apparatus.

It should be import into Golgi, not import into Golgi membrane?

**Comment by pgaudet** [comment]
Looks like I did that (based on the dates of the changes) (changed 'across' to 'into' without changing the membrane part). 

I am also tempted to remove the comment 'This term covers zinc(2+) import *across* the Golgi membrane through a channel or pore. It does not cover import via vesicle fusion with Golgi membrane, as in this case transport does not involve crossing the membrane.' 

Is there such type of endocytic zinc transport into the Golgi ? This comment is present in almost all the transport terms, it's confusing when there is no endocytic pathway. 

Pascale

**Comment by ValWood** [comment]
I do not know of any endocytic mechanism and based on experiments in yeast it does not happen.

Alkaline phophatase in the secretory pathway requires zinc. The authors of the paper I just read 
https://curation.pombase.org/pombe/curs/2c0b3f9b052bea9e
 knocked out all 3  zinc Golgi transporters to inactivate alkaline phosphatase. This implies there is no other  mechanism for zinc to enter the Golgi in a controlled way.

similarly in this paper
https://www.pombase.org/reference/PMID:29529046
zinc homeostasis in organelles is totally dependent on the transporters.

So I think at present it is fairly safe to say we do not know of this way (this probably applies to  other transmembrane transporter small molecules too).
