### ISSUE TITLE
NTR: cellular anatomical entity

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#17696]
For the GO-CAM schema, we would like to group cellular components under CARO anatomical entity, so that we can state that a molecular function instance occurs in 0 or 1 anatomical entity (being a cellular component, cell, or gross anatomical structure). I opened a PR #17695 to this end, but it introduces a problem in that it makes protein-containing complex a subclass of anatomical entity. CARO anatomical entity states it has "granularity above the level of a protein complex". Complexes are a bit of a problem as anatomical entities anyway, because (I think) we don't want to have GO-CAMs stating that functions occur in complexes.

There is currently no term that groups other cellular components to the exclusion of protein-containing complex. Could we add a term like 'cellular anatomical entity' as a child of 'cellular_component', with all cellular components as children with the exception of 'protein-containing complex'? Then in `go-bridge.owl` we would make 'cellular anatomical entity' a child of CARO 'anatomical entity'.

**Comment by pgaudet** [comment]
Interesting. I had understood "granularity above the level of a protein complex" to exclude protein complex (as in >, not >=). 

Pascale

**Comment by cmungall** [comment]
This parallels exactly a conversation we are having in obo core, I will link to here when we have a ticket

**Comment by ukemi** [comment]
It seems this will be needed if we want to successfully coordinate with CARO and intend to use their definition of anatomical entity.

**Comment by balhoff** [comment]
@ukemi or @vanaukenk would you mind creating a pull request for this? I am not set up for minting term IDs.

**Comment by vanaukenk** [comment]
Will do.

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/pull/17704

**Comment by ukemi** [comment]
Looks like we created the term and merged, but we still haven't moved the "xyz part' terms to be direct children of cellular component. We need to do this and then assert everything under those that is not a protein-containing complex to be a cellular anatomical entity. Otherwise some protein-containing complexes are asserted or inferred to be cellular anatomical entities. For example look at 6-phosphofructokinase complex.

**Comment by ukemi** [comment]
Should we unmerge #17704 or just work from it as a starting point?

**Comment by pgaudet** [comment]
Ah ! Perhps we should undo the changes, then. 

@balhoff Would you be doing the script to move the part terms under the new term ? Any idea how long that would take to do ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Or, would it be easier to leave this in place as the first step. This didn't break anything, but now there are a lot of protein complexes that are mis-classifed as cellular anatomical entities.

**Comment by balhoff** [comment]
> Would you be doing the script to move the part terms under the new term ? Any idea how long that would take to do ?

I can do this. I don't think it would take very long. I'm wondering about the class hierarchy of these. Why is it asserted? I see that `cell projection part` is asserted subclass of `cell part`. But then there is no `part_of some cell` on `cell projection` which would have allowed that to be inferred instead. Is this a holdover from an earlier modeling style?

**Comment by cmungall** [comment]
Assume it's a holdover.

I could potentially do this using hacky tools like `obo-sed.pl` but I think you could do it in a more principled way Jim.

**Comment by ukemi** [comment]
Good to see these comments. I don't think un-merging is a good idea since we coined a new identifier. I think this is a holdover from the old style where we created a new is_a path by simply make a xyz part term for a part_of parent of the term that was not subsumed. Let's discuss on Monday's call.

**Comment by pgaudet** [comment]
Can you not annotate to 'occurs_in' neuron as we proposed ?

**Comment by pgaudet** [comment]
located_in?

**Comment by pgaudet** [comment]
>  In GO-CAM these could be represented as 'cellular anatomical structure' part_of some neuron? 

I thought we could annotate location to a cell without a CC annotation.

**Comment by pgaudet** [comment]
As I understand the ShEx this is allowed.

**Comment by pgaudet** [comment]
obsolete ?

**Comment by bmeldal** [comment]
What did you do with GO:0099080 supramolecular complex? Is it a complex, is it a structure???

Otherwise, no objections :)

**Comment by ukemi** [comment]
@balhoff, is this one done?

**Comment by balhoff** [comment]
@ukemi I think so, although there are still 40 terms that are inferred subclasses of both 'cellular anatomical entity' and 'protein-containing complex'. But we have #17777 for that.

**Comment by ukemi** [comment]
Yup. Hopefully I will take care of those very soon once I clear some other tasks off my plate.
