### ISSUE TITLE
NTR:eupodium

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#17690]
A new cell projection structure was described in a 1997 Dictyostelium paper which I have just come across. The authors identified and named the structure "eupodium" and described it as similar to,  but distinct from, the podosome and invadopodium. Below are suggestions for the definition and position in the GO hierarchy. 
Please let me know if you have any questions. 
Thanks,
Bob

Name: eupodium
Ontology: cellular_component
Synonyms: knobby foot
Alternate IDs: None
Child of: GO:0120025 plasma membrane bounded cell projection

Definition: A cell projection emerging from the lamellipodium, enriched in F-actin and actin-binding proteins. The eupodium is a transiently formed, stationary anchoring foot that functions to secure the amoeba to the substratum.

PMID:9096956 Amoeboid movement anchored by eupodia, new actin-rich knobby feet in Dictyostelium

PMID:10328951 Architectural dynamics of F-actin in eupodia suggests their role in invasive locomotion in Dictyostelium.

**Comment by pgaudet** [comment]
Hi @rjdodson ! 

When I search PubMed for eupodium, this is the only paper that is returned. In papers that cite it, nobody mention the eupodium. 

Eupodium could be added as a synonym of 'plasma membrane bounded cell projection', or of 'pseudopodium', which seems likely to be what they were observing in Dicty. 

What do you think ? 

Thanks, Pascale

**Comment by rjdodson** [comment]
Hi @pgaudet!
Hope you are well and thanks for commenting on this issue! 

A search in PubMed for "eupodia" rather than "eupodium" returns a total of 4 papers, two of which are referenced above. But, all papers are from the same author, all are from Dictyostelium, and so clearly this is not a widely used term.

I first considered not submitting a NTR here as the eupodium is a projection that extends from the pseudopodium or lamellipodium, and so yes, is a part of those structures. However, as described in PMID:9096956 at least, the pseudopodium and lamellipodium are motile protrusive structures, whereas the eupodium is a strictly stationary protrusive structure, that is, never displaying any lateral movement, and whose function is to anchor a portion of the amoeba to the substratum. Fig. 4 in PMID:9096956 provides a graphic display of the relation of the eupodium to the lamellipodium. So while the eupodium is an extension of the lamellipodium, it performs a different function. 

In PMID:10328951, the authors say this regarding the difference between eupodia and pseudopodia: 
"Regardless of these similarities, however, eupodia are distinctive from pseudopodia in the following features: (1) eupodia are much smaller than pseudopodia (the average diameter has been estimated to be 0.95 􏰆m [1]), (2) eupodia are ventral structures while pseudopodia are anterior or dorsal structures (ibid), and most importantly, (3) strictly accurate 
temporal and spatial coordination are present in the formation of these structures. In other words, eupodia are formed only at the base of protruding lamellipodium and disappear when the lamellipodium is retracted. Consistent with this observation, we showed that the assembly of the F-actin system into eupodia always precedes the protrusion of lamellipodium."
(Note that the authors of this paper consider the lamellipodium to be a type of pseudopodium.)

I guess it's somewhat a matter of perspective on what we consider to be the defining characteristic of the eupodium. If we view it simply as physically part of the lamellipodium, then maybe it doesn't warrant a new term. But if we consider that it has a separate function from the lamellipodium, then maybe it does need to be a separate term. 

What do you think?
Thanks,
Bob

**Comment by pgaudet** [comment]
Since the last time the term was used is almost 20 years ago, I'd be tempted not to create the term, but use the parent for annotation.

**Comment by rjdodson** [comment]
That's fair, the term certainly isn't commonly used, and also this structure was only described in Dicty. So then I'll just annotate all the proteins localized in the eupodium with the GO term: GO:0120025 plasma membrane bounded cell projection. 
Should eupodium  even be a synonym for plasma membrane bounded cell projection? Seems kind of specific for such a broad term.
Thanks for your comments.
Bob

**Comment by krchristie** [comment]
I've just taken a quick look at the first several NARROW synonyms in the ontology file, and to make a name for a specialized structure a NARROW synonym for a general term like 'plasma membrane bounded cell projection' seems consistent with existing practice. I could use the papers you cite as references for the NARROW synonym.

That seems like a reasonable compromise to me between not adding a new term but still representing the usage in GO. Does that work for you @pgaudet  and @rjdodson ?

**Comment by rjdodson** [comment]
Hi @krchristie: 
Yes, that sounds reasonable to me. And if the term eupodium ever shows up again, at least it would be found by searching GO. 
Thanks,
Bob

**Comment by krchristie** [comment]
In addition to the two PMIDs you cited, I've added @rjdodson and @krchristie as references on the narrow synonym to facilitate tracking down the logic in future.
