### ISSUE TITLE
alpha DNA polymerase:primase complex - DNA polymerase and primase question

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17692]
alpha DNA polymerase:primase complex 
is defined as "A complex of four polypeptides, comprising large and small DNA polymerase alpha subunits and two primase subunits, which catalyzes the synthesis of an RNA primer on the lagging strand of replicating DNA; the smaller of the two primase subunits alone can catalyze oligoribonucleotide synthesis. PMID:11395402"

This is DNA polymerase alpha (?): which makes the RNA primer, and then the DNA pol subunit does some limited DNA synthesis.

is_a nuclear DNA-directed RNA polymerase complex
part_of nuclear replisome (which is not classed as a DNA polymerase complex in GO)

This seems to have some history....so perhaps this is a product of change, but I would expect it to relate to both DNA-directed RNA polymerase complex and DNA polymerase complex.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4817131/

**Comment by hattrill** [comment]
tagging @sjm41

**Comment by pgaudet** [comment]
Why should it be a 'DNA-directed RNA polymerase complex', because it makes the RNA primer ? 

Relevant tickets: 
#11942
#11165 
#12575

**Comment by hattrill** [comment]
It first makes the RNA primer then extends it - two subunits do the priming and one does the DNA elongation

**Comment by ukemi** [comment]
This is an interesting issue that points out the distinction of how complexes are represented in GO. If complexes are represented by membership, then this complex would be a DNA polymerase complex because it contains a DNA polymerase subunit. If complexes are represented as functional units, this complex would not be a DNA polymerase complex because functionally the DNA polymerase complex would synthesize DNA. Currently we have the functional distinction in GO:
This complex through inheritance is: capable of' some 'DNA-directed 5'-3' RNA polymerase activity'
If we were to add the DNA polymerase complex parent, this would also inherit  this: capable of' some 'DNA polymerase activity'
I think this would be incorrect since the primase complex synthesizes RNA. If we want to add the DNA polymerase complex parent to the term because it contains a DNA polymerase subunit, we need to remove the functional assertions about the parents of these terms. Given the two options, I think it is richer for GO to have the functional relationships than the membership relationships. @pgaudet, do you think this is consistent with the current thinking?

**Comment by hattrill** [comment]
I am sorry, I am confused. Both the DNA and RNA polymerase subunits can function independently in vitro. In vivo, the complex is the unit that had both activties - why can't it both be capable of' some 'DNA-directed 5'-3' RNA polymerase activity' and capable of' some 'DNA polymerase activity'?

On a separate point: 
why: 'DNA-directed 5'-3' RNA polymerase activity' 
when we have
GO:0003896 | DNA primase activity would be the more correct

**Comment by ukemi** [comment]
Then we would need to modify the def to include the DNA polymerase activity. Right now it specifies only the ability to make the primer. I can modify the def to include the DNA polymerase activity. I will check the ref to make sure that this activity is included.

I think your correct about the primase activity parent.

**Comment by ukemi** [comment]
If you look at the ref, I think this term was only meant to describe the complex with respect to the primase activity. From the paper, it looks like it always copurifies with DNA pol alpha. See the section on eukaryotic primases. Complexes complexes complexes oh my.

Should we try to find a separate ref that describes all of the enzymatic activities of the complex? Of course down the road this might lead to issues teasing out which gene product do what. No worse than we are now though.

**Comment by deustp01** [comment]
Jim Borowiec at NYU is an expert on the enzymology of DNA replication who has collborated extensively on the Reactome annotations in this area. I can provide his e-mail address if someone would like to try to recruit him for GO.

**Comment by ukemi** [comment]
I think this reference supports the tweak of the definition and additional parent. PMID:26975377

**Comment by hattrill** [comment]
This is good: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4817131/  (PMID26975377)

Ultimately.... it would just seem strange to a user to do a query with 'DNA polymerase complex' and not get any subunits of the DNA polymerase alpha. The activity you see with the complex, just depends on the assay.

**Comment by mah11** [comment]
> I think this term was only meant to describe the complex with respect to the primase
activity.

What?!? Are we talking about GO:0005658 (that's the ID for the name "alpha DNA polymerase:primase complex")? If so, that term most assuredly was and is meant to describe the tetrameric complex that includes DNA polymerase and DNA primase subunits, and, as Helen has noted above, executes BOTH functions during DNA replication. (The DNA polymerase only adds a short stretch, ~20 nt, to the primer, but it does indeed act.)

It would be fine to edit the definition to explicitly mention DNA polymerase activity, and to give it 'capable of' links to both GO:0003896 DNA primase activity and GO:0003887 DNA-directed DNA polymerase activity.

Don't be misled by the fact that the text definition cites a review entitled "DNA primases". In it, the passage on eukaryotic primases describes the complex composition, including the DNA polymerase subunits. That sait, it would also be OK to add the reference Helen found.

**Comment by hattrill** [comment]
This reveiw PMID:26109351 appears to have a good summary of primases across species that we should probably look at...just in case there are primases that just do the RNA pol bit.

**Comment by mah11** [comment]
> just in case there are primases that just do the RNA pol bit.

oh, there are ... but they wouldn't use the GO:0005658 CC term anyway

**Comment by ukemi** [comment]
OK. I will modify the definition and add the additional parent. I will also add the additional references.

**Comment by hattrill** [comment]
Hi David,

Something here may have got lost in translation:

I see changes to def and additions of 
relationship: capable_of GO:0003887 ! DNA-directed DNA polymerase activity
relationship: capable_of GO:0003896 ! DNA primase activity

but no 
is_a 
GO:0042575 | DNA polymerase complex

**Comment by ukemi** [comment]
Thanks @hattrill. I will double check. I thought it was inferred, but maybe that was before I added the primase activity. If it's not, I will assert it.

**Comment by ukemi** [comment]
I'm seeing it as being inferred in Protege running ELK. @balhoff?

**Comment by ukemi** [comment]
Looks like the release hasn't happened.  @kltm

**Comment by ukemi** [comment]
@hattrill, where do you see the changes that you note above?

**Comment by ukemi** [comment]
I see the superclass in today's snapshot release.
