### ISSUE TITLE
Fix definition GO:0030387  fructosamine-3-kinase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17709]
Reported by @sylvainpoux 

Definition is "Catalysis of the phosphorylation of fructosamine to form fructosamine-3-kinase."

Should be "Catalysis of the phosphorylation of fructosamine to form fructosamine-3-phosphate."

**Comment by pgaudet** [comment]
Term should probably be merged with

**Comment by pgaudet** [comment]
@sylvainpoux waiting for your feedback to decide on the merge. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

Where do we stand with this ?

**Comment by sylvainpoux** [comment]
Sorry Pascale,
I forgot this issue. I would not merge these 2 terms because it looks like that the enzyme also acts on non-protein substrates

**Comment by ValWood** [comment]
So close?
