### ISSUE TITLE
definition / taxon issue - "mitophagy" vs "autophagy of mitochondrion" vs "micromitophagy" 

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#17700]
GO:0000422 autophagy of mitochondrion "The autophagic process in which mitochondria are delivered to the vacuole and degraded in response to changing cellular conditions." PMID:15798367 PMID:19289147 PMID:23065344

GO:0000423 mitophagy "The selective autophagy process in which a mitochondrion is degraded by macroautophagy." PMID:15798367
Comments: this terms refers to the macroautophagy process and is named by common usage. There are a separate micromitophagy and mitophagy by induced vacuole formation processes.

GO:000424 micromitophagy " Degradation of a mitochondrion by lysosomal microautophagy." PMID:15798367 PMID:27003723
Comments: this term is not a child of mitophagy because the community generally uses the latter term to refer to the macroautophagy of mitochondria.

The definition / taxon issue is the use of the word "vacuole" in the definition of GO:0000422 autophagy of mitochondrion. From the associated literature citations, vacuole appears to mean specifically GO:0000324 fungal type vacuole, not the generic membrane-bounded intracellular structure found in many taxa. Is this taxon constraint - "only in fungi" - meant for GO:0000432, and if so should it be added to the term with a resulting horrendous legacy cleanup of existing annotations to non-fungal proteins?

And if that is not what "vacuole" is intended to mean in the definition of GO:0000422, then what is the intended difference between GO:0000422 and GO:0000423?

The answer to this question will probably also apply to GO:0030242 autophagy of peroxisome  and GO:0000425 pexophagy.

**Comment by ukemi** [comment]
This was certainly not meant to be restricted to fungi. I will tweak the definition.

**Comment by ukemi** [comment]
I don't think there is an issue here. Looking at the definition of vacuole as we use it, it is not restricted to fungi:

A closed structure, found only in eukaryotic cells, that is completely surrounded by unit membrane and contains liquid material. Cells contain one or several vacuoles, that may have different functions from each other. Vacuoles have a diverse array of functions. They can act as a storage organelle for nutrients or waste products, as a degradative compartment, as a cost-effective way of increasing cell size, and as a homeostatic regulator controlling both turgor pressure and pH of the cytosol.

**Comment by ukemi** [comment]
In fact, we have a class under lytic vacuole specific for fungal-type vacuole.

**Comment by ukemi** [comment]
Second question. GO:0000422 autophagy of mitochondrion is a grouping term that collects several different types of autophagic degradation of mitochondria. GO:0000423 mitophagy is specific for the autophagy by a marcroautophagy mechanism.

**Comment by deustp01** [comment]
With the definition tweaked to say that the vacuole in  GO:0000422 autophagy of mitochondrion is the generic (grouping) one and not the one specific to fungi, this issue can be closed, I think. Off on a tangent, I bet that a lot of the current annotations to GO:0000422 autophagy of mitochondrion could be re-directed to one of the more specific children (as is the case for the Reactome ones, to be fixed shortly).
Thanks

**Comment by ukemi** [comment]
OK. I changed vacuole to 'a type of vacuole'.

**Comment by deustp01** [comment]
While we're in the weeds, how about "... delivered to vacuole of any type and ...". That's too broad - there are some kinds of vacuoles, I guess, that never are involved in degrading anything, but the next bit specifies that the consequence of delivery is degradation so that gets the needed restriction.

**Comment by ukemi** [comment]
Not sure I like 'any type' because depending on the type of autophagy, it could be specific. My hope is that the curator will look at vacuole in the CC ontology and realize that it is not specific for fungi or plants or paramecia....

**Comment by deustp01** [comment]
True. Back to "a vacuole", which actually looks quite generic to anyone who hasn't just read this thread.
