### ISSUE TITLE
obsoletion/merge : DNA damage induced protein phosphorylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17715]
has 13 annotations (including 2 pombe)
GO:0006975    DNA damage induced protein phosphorylation

Is only used for kinases in the checkpoint pathway.

We don't have  other phosphorylation events with  the inducing mechanism

but this could be 
protein kinase part_of  DNA damage checkpoint signalling

No need to capture that the signalling is induced by DNA damage in a term.

Do you agree?

**Comment by ValWood** [comment]
i.e annotation consistency would improve ... 2 ways of saying the same thing.

**Comment by krchristie** [comment]
@ValWood - I'm not entirely clear on what term you are proposing that '**GO:0006975 DNA damage induced protein phosphorylation**' could be merged into. Could you please clarify.

**Comment by ValWood** [comment]
protein phosphorylation.

It seems odd to have "DNA damage induced phosphorylation" (we don't have, for example,  nitrogen starvation-induced phosphorylation, oxidative stress-induced phosphorylation or any other conditional phosphorylation...all phosphorylation is conditional on something...). 

Obsoletion might be better  to give people the opportunity   to make the connection between the MF kinase and the process.

protein kinase part_of DNA damage checkpoint signalling
would say the same thing

**Comment by krchristie** [comment]
So you're proposing obsoletion and people replace with a GO-CAM model?

**Comment by ukemi** [comment]
Always though?
PMID:16223874

**Comment by ValWood** [comment]
@ukemi PMID:16223874 reports that TRF2 id phosphorylated In_response_to DNA damage. It is the target of the phosphorylation, not the thing doing the phosphorylation., so it shouldn't be annotated using this term. That's another reason why the term is misleading (potentially 100's of genes are phosphorylated in response to DNA damage, but we should not annotate them using this term).

The kinase doing this phosphorylation is  ATM, the DNA damage checkpoint kinase.

@krchristie - Ideally this would be a GO CAM, but even 
GO:0072422    signal transduction involved in DNA damage checkpoint
with the kinase annotation would be sufficient.

That is essentially what 
"DNA damage induced protein phosphorylation" is. Its really only another way of saying "DNA damage checkpoint signalling".

All of the current  annotations are to kinases in the DNA damage checkpoint pathways.

Maybe we should also change 
GO:0072422    signal transduction involved in DNA damage checkpoint
to
GO:0072422    DNA damage checkpoint signaling 
(I don't know why we worded it this way)
If you think so, I will open a separate ticket for this.

**Comment by ukemi** [comment]
But is it happening in the context of a checkpoint, or as part of telomere maintenance?

**Comment by ValWood** [comment]
Uncapped and eroded telomeres are one of the things the DNA damage checkpoint senses.  DSO yes, it is involved in telomere maintenance through checkpoint activation.
But ONLY the kinases (or their regulators) would be annotated to this term (not the targets/substrates). They are not involved in phosphorylation.

The DNA damage checkpoint (or other DNA integrity pathway) signalling is _the_ pathway which responds to damaged DNA. It's another way of saying the same thing.

If we allow things like this why not "oxidative damage -dependent phosphorylation" for the MAP kinase oxidative stress pathway, for example?

**Comment by ukemi** [comment]
I'm not commenting on whether or not the substrates are annotated, I'm questioning whether or not this always happens in the context of the checkpoint. If it is always the case, then we are good.

**Comment by ValWood** [comment]
Ah OK. Well the DNA damage is always detected by the DNA integrity  checkpoints (damage or replication). There may be some damage dependent phosphorylation further downstream where the kinase is not considered part of checkpoint signalling, but I am not aware of any. Even so, it seems a strange way to annotate these. "phosphorylation" isn't really a process, it's a MF in the process ontology. So  we probably shouldn't combine these terms with "responses"

Any term could be combined with part_of "response to DNA damage" ....

For example more correctly 
"protein kinase" part_of "GO:0006974    cellular response to DNA damage stimulus" would be equivalent and more compliant with  normal annotation practice (i.e GO-CAM)

I don't see why this particular term combining a "modification in BP" and a "response" term is instantiated?  Particularly as it is only used for checkpoint signalling at present , where this is a given. 

It's not a big deal if you want to keep it, but I will migrate/remove  PomBase annotations for consistency. I didn't think it would be controversial because it seems so odd.

**Comment by pgaudet** [comment]
I agree that this term is odd; it skips a level of BP, in the sense that there are many DNA damage-response pathways in which there is protein phosphorylation; this is not capturing any of them, it's just saying that there is protein phosphorylation in response to DNA damage. 

There are 13 annotations; it would be good to move them to a more meaningful term (in this case obsoletion would be best). 

Thanks, Pascale

**Comment by RLovering** [comment]
BHF-UCL annotation deleted

**Comment by ValWood** [comment]
closing because this is now a duplicate.

**Comment by ValWood** [comment]
makes more sense to keep this one open.
Removed PomBase annotations today

**Comment by ValWood** [comment]
It could merge into 
DNA damage checkpoint signalling

**Comment by ValWood** [comment]
DNA damage induced protein phosphorylation
now has 10 annotations
suggest obsolete and suggest
DNA damage checkpoint signalling

**Comment by ValWood** [comment]
Can this be done as part of the protein modification in B clean up (10 EXP remaining), but a merge would work here.

**Comment by pgaudet** [comment]
Merged into GO:0042770
 name: signal transduction in response to DNA damage

Thanks, Pascale
