### ISSUE TITLE
DNA synthesis/DNA replication question

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17716]
Hullo!

Looking at the annotation of replicative polymerases.

The current structure of the ontology means we want to annotate with:
GO:0006261 	DNA-dependent DNA replication 	
we have to remember to also co-annotate with:
GO:0090592 	DNA synthesis involved in DNA replication
so that it can be found under 
DNA biosynthetic process
and 
DNA replication

As many of these mutants are lethal, there is a lot of in vitro experiments - and so not many chances to annotate the experimental work with 
GO:1904860 | DNA biosynthetic process involved in mitotic DNA replication
which "bags" both branches.

There may be a very good reason why not, but any chance of a:

DNA synthesis involved in DNA-dependent DNA replication??
![Screenshot 2019-08-15 at 14 38 47](https://user-images.githubusercontent.com/11865746/63098863-c3dda700-bf6b-11e9-92e7-51c08e118fbb.png)

**Comment by hattrill** [comment]
Adding to this, if one were to annotate to 
-mitochondrial DNA replication
we have to remember to co-annotate with a biosynthesis branch term:
![Screenshot 2019-08-20 at 08 22 21](https://user-images.githubusercontent.com/11865746/63326311-e4b74b00-c323-11e9-901c-ca9fbdbe1f76.png)

**Comment by ValWood** [comment]
I think "mitochondrial DNA replication" could go under biosynthesis.

The reason for the difference in nuclear replication is that not all replication is biosynthetic. I can't remember why (@mah11 will know). To me now this seems odd but I think it is that some of the subprocesses are not biosynthetic processes (possibly something to do with primer degradation during removal caused TPVs?).

 If this is the case, i can't think of any immediate reason why "mitochondrial DNA replication" cannot go directly under "DNA synthesis involved in DNA replication" (giving it the DNA biosyntheic process parent) , because it's all equivalent to "leading strand synthesis"

**Comment by mah11** [comment]
> The reason for the difference in nuclear replication is that not all replication is biosynthetic

No; it's that DNA replication involves more than just DNA synthesis.

The same may be true for mitochondrial DNA replication, at least in some systems. I don't know it well, but a brief search suggests that different mechanisms exist, e.g.

https://academic.oup.com/jb/article/164/3/183/5040786
http://www.biochemsoctrans.org/content/45/2/513

**Comment by ValWood** [comment]
I still think this is odd. To all intents and purposes DNA replication is a biosynthetic process. Which "parts" are not biosynthesis?

**Comment by mah11** [comment]
primers are made of RNA

**Comment by ValWood** [comment]
Got it. So DNA replication is part of "cellular biosynthetic process", but not part_of DNA biosynthesis.

**Comment by hattrill** [comment]
So the "involved in" might be a good fudge?
e.g.
DNA synthesis involved in DNA-dependent DNA replication
DNA synthesis involved inmitochondrial DNA replication

It would be helpful to users coming from a top-down query point-of-view.

**Comment by mah11** [comment]
> So DNA replication is part of "cellular biosynthetic process",

I don't know the intended scope of that grouping term, so I'm not in a position to comment.

**Comment by ValWood** [comment]
In these cases I think it is clearer if the terms are worded

DNA-dependent DNA replication, DNA synthesis

this matches
GO:0006269    DNA replication, synthesis of RNA primer

and it is clearer that this is a sub-part of the process.

To me, 
DNA synthesis involved in DNA-dependent DNA replication
just looks confusing....

**Comment by srengel** [comment]
i agree that this term isn't great and could at turn users off: DNA synthesis involved in DNA-dependent DNA replication

**Comment by hattrill** [comment]
As long as the inheritance works, I don't mind!

**Comment by sjm41** [comment]
@vanaukenk, others: any more views/progress on this one?
I'm particularly keen to have "mitochondrial DNA replication (GO:0006264)" put under the "DNA biosynthetic process (GO:0071897)" branch (see Val's comment above).
Thanks, Steven

**Comment by vanaukenk** [comment]
@sjm41 

As @hattrill suggested, how about we create the new term, 'DNA synthesis involved in mitochondrial DNA replication' and position it in the ontology as follows:

is_a DNA biosynthetic process (GO:0071897)
part_of mitochondrial DNA replication (GO:0006264)
- DNA synthesis involved in mitochondrial DNA replication (GO:new)

and defined as:
"Any DNA biosynthetic process that is involved in mitochondrial DNA replication."

We could use Midori's two reviews above as definition xrefs, but I'm happy to add more papers if you have some from your curation.

**Comment by sjm41** [comment]
Thanks @vanaukenk - this approach sounds good.
But wouldn't the new term be a is_a child of "DNA synthesis involved in DNA replication" (GO:0090592) rather than "DNA biosynthetic process" (GO:0071897)?
(see Helen's screenshot in her second post above).

Then the new term would be a 'sister' term to the existing "DNA biosynthetic process involved in mitotic DNA replication" (GO:1904860).

On that note, it would be good to use the same wording for these two sister terms  - e.g. use "DNA synthesis involved in..." for both.

**Comment by vanaukenk** [comment]
@sjm41 

Yes, you're right about the more granular parent, and the wording for all of the terms should be the same, although it looks like we have both versions throughout this part of the ontology with some terms having synonyms and not others.

@ukemi - do you have opinions on which language should prevail: 'DNA biosynthetic process' vs 'DNA synthesis' ?

**Comment by ukemi** [comment]
It's kind of a toss-up. I think the community uses DNA synthesis more that biosynthesis, but to keep internally consistent in the ontology with other terms, biosynthesis would be more appropriate. Our general rule is to use what is used by the community and then make a synonym for people who are searching across the ontology.

**Comment by ukemi** [comment]
Pubmed:
"DNA synthesis" ~45,500
"DNA biosynthesis" ~34,000

**Comment by vanaukenk** [comment]
Thanks, @ukemi 
For these child terms, I'll go with "DNA synthesis" and make sure all of the appropriate synonyms are there.
