### ISSUE TITLE
GO_REL: Remove negative relations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17712]
Following discussions on the GO-CAM model specs: We will not allow negations in extensions. Therefore these GO_REL relations can be deprecated: 

- not_during
- not_exist_during 18 annotations (17 pombase @ValWood 1 MGI @ukemi)
- not_occurs_at
- not_occurs_in (1 annotation) : MGI:1346525 @ukemi 

Thanks, Pascale

**Comment by ukemi** [comment]
MGI done

**Comment by pgaudet** [comment]
Annotation ticket https://github.com/geneontology/go-annotation/issues/2581

**Comment by ValWood** [comment]
@mah11  I thought we did not submit these?

**Comment by mah11** [comment]
> @mah11 I thought we did not submit these?

We used to, until very recently (last week!).

**Comment by pgaudet** [comment]
Do you need them ? I understood these are a placeholder ?

**Comment by pgaudet** [comment]
I'm removing them. Please let me know if it's a problem !

Pascale

**Comment by ValWood** [comment]
No it's fine. Midori already removed them at our end. I think we know which ones they are if there is ever a way to negate extensions, but in the whole scheme of things maybe we should not bother ;)
