### ISSUE TITLE
missing parents for biofilm formation and flocculation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17727]
![biofilm](https://user-images.githubusercontent.com/7359272/63262262-6b651d00-c27d-11e9-935b-2590c6b0c382.jpg)

There are similarities between flocculation and biofilm formation that are not represented in the ontology.

Flocculation should have multi organism cellular process as a parent
biofilm formation should have "aggregation of unicellular organisms" as a parent

@CuzickA

**Comment by ValWood** [comment]
Actually @CuzickA  candida does biofilm formation so the  biofilms may net be aggregations of unicellular organism, BUT they are cell aggregations, and they don't have this parent.

**Comment by pgaudet** [comment]
@krchristie I am taking this ticket for the work on multi-organism processes. 

Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] changed parent: biofilm formation -> 'aggregation of unicellular organisms'
