### ISSUE TITLE
check def's of Rpd3S and Rpd3L - presumed errors

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#17724]
an SGD user has written in saying that the definitions of Rpd3S complex GO:0032221 and Rpd3L complex GO:0033698 have errors.  can you please check and correct as necessary?

> To whom it may concern,
> 
> My name is Natalia Reim, and I am a PhD student in the Winston lab. I noticed that the descriptions for the GO terms Rpd3S complex and Rpd3L complex are backwards in terms of where those complexes preferentially deacetylate histones. Rpd3S deacetylates histones across coding regions, whereas Rpd3L preferentially deacetylates histones near promoter regions. I wanted to bring that to your attention. Links to the pages are below.
> 
> https://www.yeastgenome.org/go/GO:0032221
> https://www.yeastgenome.org/go/GO:0033698

**Comment by ukemi** [comment]
From PMID:17450151 it looks as though this is correct. Technically we should switch the term labels since terms are supposed to be associated with definitions, not labels. @ValWood and @srengel , based on curation practice, do you think it would be better to switch labels/synonyms or definitions? All of the experimental annotations are from SGD or Pombase.

**Comment by ValWood** [comment]
We have annotated to the labels here, I think. The def switching was not noticed by us (I  remember doing these terms with Rama).

 @srengel  your shout. If the labels are switched to match the defs we can easily reaannotate to match.
However if SGD used the labels too, and all of the ISS will also be the wrong way around it might  be better to   fix the definitions on this occasion.

Or  more correctly - to obsolete with a single direct replacement

**Comment by ukemi** [comment]
If we obsolete, then we you will have to re-annotate. Presumably the ISS annotations are based on the experimental annotations, so if you both annotated to the labels, then switching the definitions should correct everything including ISS. Your call.

**Comment by srengel** [comment]
Oh please let’s just please fix the definitions.  The errant phrases were added later by someone, and I didn’t find any ticket explaining why they were added, or who added them.  We have definitely annotated to the term names.

**Comment by ValWood** [comment]
Actually, I , looking at pombe annotations I have  16 annotations to the small complex and 5 to the large complex. This doesn't make sense. Are we absolutely sure that nobody swapped the LABELS at  some point?

**Comment by ValWood** [comment]
no they didn't ...we will need to fix ours... I have no idea what I did here....

**Comment by ukemi** [comment]
So should I just swap the definitions as @srengel suggests?

**Comment by ValWood** [comment]
yes that would be correct  to match the names, we will reannotate.

**Comment by ukemi** [comment]
OK. Unless anyone really objects, I will just swap the definitions and the labels will still be associated with the existing identifiers.

**Comment by srengel** [comment]
No no, it’s not swap the entire definitions, it’s just fix the bad phrases that were entered later.

**Comment by srengel** [comment]
For 3S, change first sentence from this: A eukaryotically conserved histone deacetylase complex which deacetylates histones preferentially in promoter regions.

To this: A eukaryotically conserved histone deacetylase complex which deacetylates histones across gene coding regions.

Then for 3L, change first sentence from this: A histone deacetylase complex which deacetylates histones across gene coding regions. 

To this: A histone deacetylase complex which deacetylates histones preferentially in promoter regions.

**Comment by ukemi** [comment]
Thanks @srengel

**Comment by srengel** [comment]
👍

**Comment by ValWood** [comment]
I was just about  to fix these PomBAse end, but the dleted and the added definitions seem to be identical


2019-08-23 | Deleted | DEFINITION | A eukaryotically conserved histone deacetylase complex which deacetylates histones preferentially in promoter regions. Composed of a catalytic histone deacetylase subunit, a chromodomain protein, a SIN3 family co-repressor, and a WD repeat protein (Clr6p, Alp13p, Pst2p, and Prw1p respectively in Schizosaccharomyces; Rpd3p, Sin3p, Ume1p, Rco1p and Eaf3 in Saccharomyces; homologs thereof in other species).
-- | -- | -- | --
2019-08-23 | Added | DEFINITION | A eukaryotically conserved histone deacetylase complex which deacetylates histones across gene coding regions. Composed of a catalytic histone deacetylase subunit, a chromodomain protein, a SIN3 family co-repressor, and a WD repeat protein (Clr6p, Alp13p, Pst2p, and Prw1p respectively in Schizosaccharomyces; Rpd3p, Sin3p, Ume1p, Rco1p and Eaf3 in Saccharomyces; homologs thereof in other species).

could you check?

**Comment by ValWood** [comment]
Ah got it. It was only the first part of the definition that was incorrect. Not the described subunits.

**Comment by ValWood** [comment]
I am confused though. I am double checking against SGD.

For pombe I reckon this is RPd3L, and the pombe annotation needs switching

but SGD has as  RPD3S
 RCO1 https://www.yeastgenome.org/locus/YMR075W#go

But the SGD annotation should be correct already because it matched the definitions

@srengel  which complex do you reckon this should be?

**Comment by ValWood** [comment]
No this is clearly S from the def....so confused. Sorry!

**Comment by srengel** [comment]
we have RCO1 in Rpd3S.

**Comment by ukemi** [comment]
Is this still an ontology issue or does it need to be moved to annotation?

**Comment by ValWood** [comment]
> Is this still an ontology issue or does it need to be moved to annotation?

No, it's all fine  I already reclosed, (then reopened, then reclosed).

It's very confusing at my end- everything was wrong. I think it's sorted...
