### ISSUE TITLE
Revise definition for cellular_component

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#17729]
Recent discussions of [annotation extension relations](https://github.com/geneontology/go-annotation/issues/2584) as well as [GO-CAM specifications](https://github.com/geneontology/go-shapes) has led to re-examining the definition of cellular_component.

We would like to convey in the definition that GO cellular components, such as membranes or the cytoskeleton, include the physical extent of gene products that function either by being: 1) fully or partially contained within them, e.g. an EGF receptor, or 2) in direct contact with them, e.g. a kinesin motor.

This would allow us to simplify how we express the relation between the MF 'enabled by' a gene product and where the MF occurs, i.e. 'occurs in'.

Here's a stab at a new def for cellular_component:

A location, relative to cellular compartments and structures, occupied by a macromolecular machine when it carries out a molecular function. Cellular structures include the physical extent of the gene products that are either fully or partially embedded within them as well as the gene products that function via attachment to that structure.  
Source: GOC:pdt, NIF_Subcellular:sao-1337158144

Perhaps move the next part to a comment and more explicitly state what relations we use for gp2CC?
There are two ways in which the gene ontology describes locations of gene products: (1) relative to cellular structures (e.g., cytoplasmic side of plasma membrane) or compartments (e.g., mitochondrion), and (2) the stable macromolecular complexes of which they are parts (e.g., the ribosome). 

Some additionally relevant tickets and history:
https://github.com/geneontology/go-annotation/issues/2584
https://github.com/geneontology/go-ontology/issues/17668
https://github.com/geneontology/go-ontology/issues/3521

**Comment by ukemi** [comment]
If we do this, it will impact how disjoint classes are defined in the ontology.

**Comment by vanaukenk** [comment]
More reason to work on the spatial relations in the ontology.

**Comment by pgaudet** [comment]
Updated definition to 

A location, relative to cellular compartments and structures, occupied by a macromolecular machine. There are three types of  cellular components described in the gene ontology: (1) the cellular anatomical entity where a gene product carries out a molecular function (e.g., plasma membrane, cytoskeleton) or membrane-enclosed compartments (e.g., mitochondrion); 
(2) virion components, where viral proteins act, and (3) the stable macromolecular complexes of which gene product are parts (e.g., the clathrin complex).
