### ISSUE TITLE
revise biofilm formation def

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17728]
Definition (GO:0042710 GONUTS page)
A process in which planktonically growing microorganisms grow at a liquid-air interface or on a solid substrate under the flow of a liquid and produce extracellular polymers that facilitate matrix formation, resulting in a change in the organisms' growth rate and gene transcription. PMID:11932229

1. What does planktonically mean here? I can't find a definition of "planktonically" which makes sense in this context . Does this mean "individually growing"? Is this required for a necessary and sufficent definition?

2. Should "resulting in"
~resulting in a change in the organisms' growth rate and gene transcription~

be removed? This seems that it is linking the process to a downstream process, and could be confusing for curators?

**Comment by ValWood** [comment]
@CuzickA

**Comment by ukemi** [comment]
@krchristie, assigning two to you since they are closely related.

**Comment by pgaudet** [comment]
Redundant with #20085
