### ISSUE TITLE
add "signalling receptor activity" as exact synonym

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17725]
English speakers will search on "signaling activity" and do not find
"signalling receptor activity" because synonym isn't there.
I just saw this situation.

Could the "signalling" be added as synonyms to all signalling terms?

**Comment by vanaukenk** [comment]
@ukemi  - this seems best accomplished via script whereby any term names that include 'signaling' should, if they don't already, have an EXACT synonym added using the 'signalling' variant.
What do you think?

**Comment by ValWood** [comment]
Does such a script exist yet?
If not who  will create it?
adding infrastructure label
