### ISSUE TITLE
rename MF terms for topoisomerase type I & II activity terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17734]
The two relevant topoisomerase MF terms are currently named like this: 
- DNA topoisomerase type I activity (GO:0003917)
- DNA topoisomerase type II (ATP-hydrolyzing) activity  (GO:0003918)

As described in https://github.com/geneontology/go-ontology/issues/15575, these names have actively promoted confusion, leading in part to the creation of one redundant and one completely spurious topoisomerase II activity term.  (I plan to merge one and obsolete the other as detailed here: https://github.com/geneontology/go-ontology/issues/17661).

They also lack clarity with respect to the distinguishing features of the two major classes of topoisomerases:
- topoisomerase type I (**single** strand cut, ATP-**independent**)
- topoisomerase type II (**double** strand cut, ATP-**hydrolyzing**)

However, considering the potential confusion between the two major classes (topoisomerase type I & topoisomerase type II) and specific enzymes (topoisomerase I, topoisomerase II, topoisomerase III, topoisomerase IV, etc.), I am inclined to add info to the two type terms rather than remove it. 

One additional consideration is the fact that the type I topo enzymes can also have RNA topoisomerase activity (`"RNA topoisomerase activity is prevalent in Type IA topoisomerases from bacteria, archaea, and eukarya" - Ahmad et al. 2016, PMID:27257063`), it might be best to remove "DNA" from the term names.

Thus, I proposed to rename these terms like this:
- topoisomerase type I (single strand cut, ATP-independent) activity [GO:0003917]
- topoisomerase type II (double strand cut, ATP-hydrolyzing) activity [GO:0003918]

@bmeldal - Does this seem reasonable to you?

**Comment by krchristie** [comment]
Actually, considering that there is an MF term for "RNA topoisomerase activity", these MF terms can just keep specificity for DNA. 

I still think it's better to add the info that distinguishes the two major classes of topo enzymes, e.g. # strands cut and ATP utilization since it helps distinguish from the more specific individual enzyme names. Also, since we have a term named "DNA topoisomerase II" that I plan to obsolete, it avoids any issues with name versus ID conflicts.

So with this in mind, I modify my proposed new term names to these:
- DNA topoisomerase type I (single strand cut, ATP-independent) activity [GO:0003917]
- DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity [GO:0003918]

**Comment by bmeldal** [comment]
Yup, sounds like a good solution - for now ;-)
