### ISSUE TITLE
merge ? pantothenate biosynthetic process from valine

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17737]
Based on @marcfeuermann comments here:
https://github.com/geneontology/go-annotation/issues/2397

"From PMID:11154694 (http://www.jbc.org/content/276/14/10794.long) the biosynthesis pathways of the beta-alanine precursor seem to differ in S. cerevisae and bactera, but the biosynthesis pathways of the pantoate precursor look similar.
Valine is a a far upstream precursor of pantoate and I propose to replace "pantothenate biosynthetic process from valine" by "pantothenate biosynthetic process".

should we even have this term?

GO:0033317    pantothenate biosynthetic process from valine

particularly as it is defined:

Definition (GO:0033317 GONUTS page)
The chemical reactions and pathways resulting in the formation of pantothenate, the anion of pantothenic acid, from other compounds, including valine.

from other compounds "including valine" means any precursor?

i.e there is no difference?

**Comment by marcfeuermann** [comment]
I do not know why the term with the valine has been created. I think we do not need it and I would indeed obsolete it. 
@pgaudet ?

**Comment by ukemi** [comment]
The structure of the ontology suggests there are two separate pathways, one through valine and one through  2-dehydropantolactone.

**Comment by ValWood** [comment]
It appears to be a linear pathway:

http://www.llamp.net/?q=Nca%20CoA%20biosynthesis

L-valine ->  -> 3-methyl 2-oxobutanoate->2-dehydropantolactone

**Comment by marcfeuermann** [comment]
I agree Val. Sorry, I should have added more details in my previous comments. When I said valine is a far upstream precursor I meant that it is so upstream that it even not appears in many papers in which the pathway starts at the 2-dehydropantolactone level.

**Comment by pgaudet** [comment]
The reason why this 'from valine' term exists is that we also have 'from 2-dehydropantolactone' (GO:0033318), based on MetaCyc  
https://biocyc.org/META/NEW-IMAGE?type=NIL&object=PANTO-PWY (phosphopantothenate biosynthesis I)
https://biocyc.org/META/NEW-IMAGE?type=NIL&object=PWY-3961 (phosphopantothenate biosynthesis II)

Although there are no annotations to GO:0033318

And the cross references seem mixed up. 

Anyone knows about this pathway ? @marcfeuermann ??

**Comment by ValWood** [comment]
Quoting @marcfeuermann  above ;)

"I do not know why the term with the valine has been created. I think we do not need it and I would indeed obsolete it (or merge the 2 terms)."

**Comment by pgaudet** [comment]
Then I would do a 3-way merge: 

 GO:0015940 pantothenate biosynthetic process
--  GO:0033318 pantothenate biosynthetic process from 2-dehydropantolactone
-- GO:0033317 pantothenate biosynthetic process from valine 

I am still not clear why MetaCyc has two pathways. Looks like both pantonate and pantolactate can be condensed with alanine to form 
@keseler can you help ? 

I see that https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=RXN-6401
uses the reaction 4.3.3.- to condense pantolactone and alanine into pentothenate, but in EC I see no children of 4.3.3.- that may catalyze this reaction. 

Thanks, Pascale

**Comment by keseler** [comment]
Sorry for the late reply.  I have asked Ron Caspi for his opinion; here's our combined wisdom, such as it is.

I don't think the "from valine" part for GO:0033317 is really reasonable.  As shown in MetaCyc, the pathway really starts with 3-methyl-2-oxobutanoate, which is an intermediate in the valine biosynthesis pathway.  Yes, the last enzyme in valine biosynthesis, IlvE, can technically catalyze the reverse reaction and produce 3-methyl-2-oxobutanoate from valine, but I'm not sure this would happen in vivo.  Btw, the PWY-3921 cited in that GO term definition may have been a typo; in any case, it doesn't exist in MetaCyc any more.

Then the question becomes, is there a good reason for having child terms for GO:0015940?  There do seem to be different pathways for synthesizing pantothenate (or rather, phosphopantothenate*), although the experimental support for the second pathway captured by GO:0033318, PWY-3961 in MetaCyc, isn't exactly astonishing.  I wonder if any more has been discovered in the last 15 years.  Unfortunately we don't have the funding at the moment to research this question.  If this pathway exists, it probably won't get its starting compound from valine biosynthesis, and I think it might be sufficiently different to merit a separate GO term.

Regarding the * above, MetaCyc has a third, archaeal, pathway for phosphopantothenate biosynthesis, https://metacyc.org/META/NEW-IMAGE?type=NIL&object=PWY-6654.  There, it seems that the last two chemical transformations are happening in reverse order, i.e. pantothenate is not a pathway intermediate.  This means it couldn't really be classified under a "pantothenate biosynthetic process" parent.  Given that the experimental support for this pathway is reasonable, it might be useful to rename/redefine the parent term to something like "pantothenate/phosphopantothenate biosynthetic process".

Now for the philosophical argument.  I don't know what the current thinking within GO is with respect to representing different pathways to the same end compound.  How different do pathways have to be to merit a separate GO term?  No idea... :-( 

Hope this helps,
Ingrid

**Comment by ValWood** [comment]
So @pgaudet  it seem this can merge. Quick ticket?

**Comment by pgaudet** [comment]
So I merge 
'pantothenate biosynthetic process from 2-dehydropantolactone'
and 
'pantothenate biosynthetic process from valine'

into 'GO:0015940 pantothenate biosynthetic process'

Right ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes.
