### ISSUE TITLE
OTR: RecQ helicase-Topo III complex

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17735]
In https://github.com/geneontology/go-ontology/issues/15575 @bmeldal said:

> I also found
> GO:0031422 RecQ helicase-Topo III complex:

> We annotated it in CP for yeast.
> It's defined in GO as
> "A complex containing a RecQ family helicase and a topoisomerase III homologue; may also include one or more additional proteins; conserved from E. coli to human."
and we annotated it with "GO:0003917 DNA topoisomerase type I activity".
Is this effectively also a Type IA Topo?

The reference () cited for this term is this paper:
Chang et al. 2005. RMI1/NCE4, a suppressor of genome instability, encodes a member of the RecQ helicase/Topo III complex. EMBO J.  24(11):2024-33. PMID:15889139

Here's a quote:
> A subset of RecQ family members physically interacts with topoisomerase III (Top3) homologues (Gangloff et al, 1994; Goodwin et al, 1999; Johnson et al, 2000; Wu et al, 2000). Escherichia coli RecQ stimulates Top3 to catenate and decatenate covalently closed duplex DNA (Harmon et al, 1999) and BLM is able to stimulate the DNA strand passage activity of Top3α (Oakley and Hickson, 2002). Furthermore, BLM and Top3α can work together to resolve a recombination intermediate containing a double Holliday junction (Wu and Hickson, 2003). S. cerevisiae strains lacking TOP3 exhibit a severe growth defect, sensitivity to DNA‐damaging agents, and hyper‐recombination (Wallis et al, 1989; Gangloff et al, 1994; Chang et al, 2002). Most of the defects exhibited by top3 mutants can be suppressed by mutation of SGS1 (Gangloff et al, 1994; Chakraverty et al, 2001), a relationship that is conserved in Schizosaccharomyces pombe where mutations in the recQ homologue rqh1+ can suppress the lethality of top3Δ mutants (Maftahi et al, 1999). These data support models in which RecQ helicase action produces a toxic DNA structure that is resolved by Top3 (Gangloff et al, 1994; Ira et al, 2003; Wu and Hickson, 2003). 

Based on this quote, this term is intended to be a general term for complexes of RecQ family helicases with topoisomerase III enzymes. This includes bacterial Topo III as well as both mammalian topo III-alpha and topo III-beta, so it is specific for the topoisomerase III enzymes, which are within the type IA subfamily, but the term is not broad enough to encompass all type IA topoisomerases.

With this in mind, I propose that we rename this term:
**Existing name:** RecQ helicase-Topo III complex
**New name:** RecQ family helicase-topoisomerase III complex

and make the existing term name into an exact synonym.

I am fine with the existing definition. 

@bmeldal - Do you have any additional suggestions with respect to this term?

**Comment by krchristie** [comment]
In #15575 @krchristie said:
> Also, I am wondering if TDRD3 is a helicase?, in which case the existing "DNA topoisomerase I-TDRD3 complex" term would be a subtype of "RecQ helicase-Topo III complex"

**Comment by bmeldal** [comment]
>"A complex containing a RecQ family helicase and a topoisomerase III homologue; may also include one or more additional proteins; conserved from E. coli to human."

Maybe add clarification for the Topo Type IA:

"A complex containing a RecQ family helicase and a topoisomerase III homologue (a member of topoisomerase type IA); may also include one or more additional proteins; conserved from E. coli to human."

>Also, I am wondering if TDRD3 is a helicase?, in which case the existing "DNA topoisomerase I-TDRD3 complex" term would be a subtype of "RecQ helicase-Topo III complex"

UniProt says:

Q9H7E2 (TDRD3_HUMAN)
Scaffolding protein that specifically recognizes and binds dimethylarginine-containing proteins. In nucleus, acts as a coactivator: recognizes and binds asymmetric dimethylation on the core histone tails associated with transcriptional activation (H3R17me2a and H4R3me2a) and recruits proteins at these arginine-methylated loci. In cytoplasm, may play a role in the assembly and/or disassembly of mRNA stress granules and in the regulation of translation of target mRNAs by binding Arg/Gly-rich motifs (GAR) in dimethylarginine-containing proteins.

GO - Molecular function
    RNA binding Source: UniProtKB
    chromatin binding Source: UniProtKB
    methylated histone binding Source: UniProtKB
    transcription coactivator activity Source: UniProtKB

Doesn't look like TDRD3 is a helicase or at least not yet confirmed as one so I'd keep it where it is.

Apologies for the signal silence, I was also on holiday, back today :)

**Comment by krchristie** [comment]
> > "A complex containing a RecQ family helicase and a topoisomerase III homologue; may also include one or more additional proteins; conserved from E. coli to human."
> 
> Maybe add clarification for the Topo Type IA:
> 
> "A complex containing a RecQ family helicase and a topoisomerase III homologue (a member of topoisomerase type IA); may also include one or more additional proteins; conserved from E. coli to human."

Good idea!!

> > Also, I am wondering if TDRD3 is a helicase?, in which case the existing "DNA topoisomerase I-TDRD3 complex" term would be a subtype of "RecQ helicase-Topo III complex"
> 
> UniProt says:
> 
> Q9H7E2 (TDRD3_HUMAN)
> Scaffolding protein that specifically recognizes and binds dimethylarginine-containing proteins. In nucleus, acts as a coactivator: recognizes and binds asymmetric dimethylation on the core histone tails associated with transcriptional activation (H3R17me2a and H4R3me2a) and recruits proteins at these arginine-methylated loci. In cytoplasm, may play a role in the assembly and/or disassembly of mRNA stress granules and in the regulation of translation of target mRNAs by binding Arg/Gly-rich motifs (GAR) in dimethylarginine-containing proteins.
> 
> GO - Molecular function
> RNA binding Source: UniProtKB
> chromatin binding Source: UniProtKB
> methylated histone binding Source: UniProtKB
> transcription coactivator activity Source: UniProtKB
> 
> Doesn't look like TDRD3 is a helicase or at least not yet confirmed as one so I'd keep it where it is.

Great. Thanks for looking into this for me.
 
> Apologies for the signal silence, I was also on holiday, back today :)

No worries. I hope you had a lovely time :)
