### ISSUE TITLE
NTR: DNA gyrase complex

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17736]
In https://github.com/geneontology/go-ontology/issues/15575, @bmeldal said:

> **Type IIA:**

> - Acc to your table, Topo II (bacs) and Topo IV (bacs) have different activities so justifies different complex terms with relationships to their respective (fixed) functions :) 

> We have already curated the 2 E. coli complexes ([gyrase](https://www.ebi.ac.uk/complexportal/complex/CPX-2177) and [Topo IV](https://www.ebi.ac.uk/complexportal/complex/CPX-1104)) and assigned 
"GO:0009330 DNA topoisomerase complex (ATP-hydrolyzing)". 
> and
> "GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity" & "GO:0034335 DNA supercoiling activity" 
to both.
> (Once the MF terms are fixed I have to remove the parent-child duplicated annotations!)
We must have missed the existence of the Topo IV term.

> **Action:**
> - We need a NEW term for Topo II / gyrase!

Based on the Wikipedia page for DNA gyrase: https://en.wikipedia.org/wiki/DNA_gyrase, here is a start for the proposed new complex term:

**name**: DNA gyrase complex
**definition**: A heterotetrameric enzyme, which in most bacterial species is composed of two subunits each of an A subunit (GyrA) and a B subunit (GyrB). It can introduce negative supercoils into DNA at the expense of ATP hydrolysis, an activity unique to DNA gyrase, as well as relax positive supercoils, which can also be done by topoisomerase IV.

@bmeldal - Any comments or suggestions?

**Comment by bmeldal** [comment]
Suggested def:

A bacterial type IIA topoisomerase that is unique in its function of introducing negative supercoils into DNA at the expense of ATP hydrolysis. Also capable of relaxing positive supercoils, an activity shared with topoisomerase IV. Mostly composed of two copies each of an A subunit (GyrA) and a B subunit (GyrB).

Synonym:
Topoisomerase II [EXACT]

References:
PMID:20675723
-> plus any you have :)

The positive supercoil relaxing is mentioned in the wiki entry and CP but not in your table. Hmmm.... Must be true if we added it ;-)

Thanks for making the ticket, I didn't get round to it before my own holidays.

**Comment by krchristie** [comment]
> Suggested def:
> 
> A bacterial type IIA topoisomerase that is unique in its function of introducing negative supercoils into DNA at the expense of ATP hydrolysis. Also capable of relaxing positive supercoils, an activity shared with topoisomerase IV. Mostly composed of two copies each of an A subunit (GyrA) and a B subunit (GyrB).

I'm fine with discussing the functions in the first sentence, but I'm going to try to rephrase to include both functions in a single sentence.

I'll also change "Mostly" to some thing like "Typically" to discuss the composition.
 
> Synonym:
> Topoisomerase II [EXACT]

Yes, thanks for making sure I get this in.
 
> References:
> PMID:20675723
> -> plus any you have :)

Thanks for providing a PMID for a reference. I only looked at the Wikipedia page, so I'll use that too.
 
> The positive supercoil relaxing is mentioned in the wiki entry and CP but not in your table. Hmmm.... Must be true if we added it ;-)

I copied the table from a Wikipedia page without much in the way of modification other than reformatting so I could see the whole thing at one time instead of having to scroll both up/down and right/left, so I think it's an error of omission there. While I don't have any specific references in my head, or written down, I've seen plenty of references that both DNA gyrase and topo IV can relax (-) supercoils.
 
> Thanks for making the ticket, I didn't get round to it before my own holidays.

No worries. I need to start focusing on another area so I really wanted to get all the topo stuff wrapped up as soon as possible, or at least specified clearly if not actually done.

**Comment by bmeldal** [comment]
Should it be
is_a GO:0009330 DNA topoisomerase complex (ATP-hydrolyzing)
and
capable_of GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity?
(except with the new term names of course)

Otherwise all good :)

**Comment by krchristie** [comment]
Regarding the question
> Should it be
is_a GO:0009330 DNA topoisomerase complex (ATP-hydrolyzing)
and
capable_of GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity?

I was thinking as I closed this that the `DNA gyrase (aka topo II)` term should be 
`is_a GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)`

but that I would wait until I changed the name of GO:0009330

Then, there's the question of what to put for capable of. If we just say 
`capable_of GO:0003918 DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity`

Then we should also say exactly the same thing for `GO:0009340 DNA topoisomerase IV complex`, which currently does not have a statement of what it can do.

We do already have a child term of GO:0003918 for the supercoiling activity, but not for the topo type II relaxation activity:

-- GO:0003918 DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity
--- GO:0034335 DNA supercoiling activity

It seems that it might be better if we added an additional MF term for `supercoil relaxing activity, via double strand cut` (or some better string.

Then, 
DNA gyrase would be:
`is_a GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)`
`capable_of GO:0034335 DNA supercoiling activity`
`capable_of supercoil relaxing activity, via double strand cut`

topoisomerase IV complex would be
`is_a GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)`
`capable_of supercoil relaxing activity, via double strand cut`

Note that the `GO:0034335 DNA supercoiling activity` term has `DNA gyrase activity` as an exact synonym. However, when the definition of this term says that not all DNA gyrases are capable of introducing supercoils, I think that we should leave the `DNA gyrase activity` synonyms for this term to help draw the connection between this activity and DNA gyrase enzymes, but change them to RELATED, or maybe to NARROW.

... sigh, reading the definition of `DNA supercoiling activity`, I'm not sure what we should do about the capable of statements if NOT ALL `DNA gyrase` enzymes are capable_of `DNA supercoiling activity`. 

Perhaps it would be best to only make this capable_of statement:

GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)
capable_of GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity

and then explicitly say `DNA gyrase complex` and `DNA topoisomerase IV complex` are both is_a `GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)`

**Comment by bmeldal** [comment]
...sight - indeed!

I didn't know you where planning on changing the relationships after doing the name changes, I thought we missed them as I forgot to add them to the ticket yesterday.

Happy to go with 
'DNA gyrase complex' and 'DNA topoisomerase IV complex'
'is_a GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)'
and
'GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)'
'capable_of GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity'

for now. I think there is nothing wrong with those statements.

**Supercoils** are a different business, and I know nothing about the details (I haven't read into it in detail). But from the defs here it seems that 

a) there are 2 types of supercoils: (+) and (-)
b) topos can do 3 things: remove, relax and generate supercoils! 

And the combination of these activities differentiate the Type I and Type II topos.

If we want to eventually define all complexes logically we need to make some additional distinction between the gyrase and Topo IV by adding a relevant supercoil activity term. However, we aren't anywhere near that point yet so in order to close this chapter I'd leave the supercoils be supercoils and tackle that issue when we really need it (i.e. when people need the different MF terms for annotation).

Happy to 

>leave the DNA gyrase activity synonyms for this term to help draw the connection between this activity and DNA gyrase enzymes, but change them to RELATED, or maybe to NARROW.

Birgit

**Comment by krchristie** [comment]
> ...sight - indeed!
> 
> I didn't know you where planning on changing the relationships after doing the name changes, I thought we missed them as I forgot to add them to the ticket yesterday.

I realize it wasn't really written anywhere, but I felt a little uncomfortable making the gyrase and topo IV complex terms child terms of the existing term that's meant to be the general topo II complex term until we clarified it...

 
> Happy to go with
> 
> `DNA gyrase complex` and `DNA topoisomerase IV complex`
> `is_a GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)`
> and
> `GO:0009330 DNA topoisomerase II complex (double strand cut, ATP-hydrolyzing)`
> `capable_of GO:0003918 DNA topoisomerase type II (ATP-hydrolyzing) activity`
> 
> for now. I think there is nothing wrong with those statements.

agreed
 
> **Supercoils** are a different business, and I know nothing about the details (I haven't read into it in detail). But from the defs here it seems that
> 
> a) there are 2 types of supercoils: (+) and (-)
> b) topos can do 3 things: remove, relax and generate supercoils!

Is there a difference between removing and relaxing? or is that just a difference in amount of relaxing/removing?
 
> And the combination of these activities differentiate the Type I and Type II topos.
> 
> If we want to eventually define all complexes logically we need to make some additional distinction between the gyrase and Topo IV by adding a relevant supercoil activity term. However, we aren't anywhere near that point yet so in order to close this chapter I'd leave the supercoils be supercoils and tackle that issue when we really need it (i.e. when people need the different MF terms for annotation).

Your comment makes me think that we should modify the name of the existing "DNA supercoiling term' to make it clear that it is specific to negative ones
 
> Happy to
> 
> > leave the DNA gyrase activity synonyms for this term to help draw the connection between this activity and DNA gyrase enzymes, but change them to RELATED, or maybe to NARROW.

cool

**Comment by bmeldal** [comment]
>I realize it wasn't really written anywhere, but I felt a little uncomfortable making the gyrase and topo IV complex terms child terms of the existing term that's meant to be the general topo II complex term until we clarified it...

True. I guess you are about to commit those name changes very soon anyway.

>Is there a difference between removing and relaxing? or is that just a difference in amount of relaxing/removing?

No idea, these terms are all in your/Wiki table :)

>Your comment makes me think that we should modify the name of the existing "DNA supercoiling term' to make it clear that it is specific to negative ones

Yes, that might be worth doing.

**Comment by krchristie** [comment]
@bmeldal - I think I did everything we agreed upon in the discussion since you reopened this ticket in the ticket referenced just above this comment, but let me know if you see anything I missed.

- equivalence axioms and parentage for topo type II complex terms to the extent currently possible in the ontology
- clarified "DNA supercoiling activity" term

**Comment by bmeldal** [comment]
Yes, I think that's it - for now ;-)
