### ISSUE TITLE
trophic interaction vs trophic process

### ISSUE THREAD

**Issue by diatomsRcool** [geneontology/go-ontology#17741]
Is 'trophic interaction' is in scope for GO? If not, is it a valid subclass of biological process managed in another ontology?
See discussion here
https://github.com/EcologicalSemantics/ecocore/issues/70

**Comment by ValWood** [comment]
Do you have an example of a normal  "tropic interaction' process. This would help.

I'm not sure that in GO these would be described as multispecies processes, but as single  species processes- feeding etc. I might have understood what you are trying to describe though. If we had examples it would help to see if these are processes that could be used to annotate gene products.

**Comment by diatomsRcool** [comment]
A normal "trophic interaction" process would include predation. That is clearly a multi-species process. My motive for asking this is that I want to rename "trophic interaction" in ecocore to "trophic process" and make it a child of GO biological process. The children of trophic process would include autotrophy and heterotrophy, thus not all of them would be multi-species processes.
I'm not sure that you would want to use terms like carnivory or lithotrophy to annotate gene products. Perhaps trophic process is a subclass of GO biological process, but managed in ecocore?

**Comment by ValWood** [comment]
Your scope for trophic process seems broad. How does it align with/relate to :
 "interaction with host" https://www.ebi.ac.uk/QuickGO/term/GO:0051701

Can you define the process of "trophic process" ? that might help. Then we can assess if we are always referring to biological processes.

**Comment by pgaudet** [comment]
Check also  GO:0044419 interspecies interaction between organisms

**Comment by diatomsRcool** [comment]
right now the definition of trophic process is "a process during which a living entity acquires or generates food and energy from a living, dead, or non-living entity."

**Comment by diatomsRcool** [comment]
I could make trophic process a child of BFO process......

**Comment by pgaudet** [comment]
Add as a synonym of 'GO:0007631 feeding behavior ?

**Comment by ValWood** [comment]
GO:0044002    acquisition of nutrients from host
or the parent
GO:0051816   acquisition of nutrients from other organism during symbiotic interaction
?

**Comment by ukemi** [comment]
As discussed at the ontology meeting, although there are terms in GO that would be subclasses of this term the term itself would encompass much more than is in the scope of GO. Therefore I am closing this issue.
