### ISSUE TITLE
obsolete: interspecies quorum sensing (GO:0052097) & intraspecies quorum sensing (GO:0052100)

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17756]
Of the 47 annotations to '**quorum sensing involved in interaction with host**', 33 are experimental 
- 31 IMP from Mony et al. 2014 
- 1 IMP + 1 IDA from Fujiya et al. 2007

Looking quickly at these 2 papers plus a couple 2006 reviews they led me to, I think that it is specious to try to separate out `interspecies quorum sensing (GO:0052097)` & `intraspecies quorum sensing (GO:0052100)`. Other than in a laboratory monoculture, an organism that is putting out these signals and detecting them, is probably doing it in the context of multiple organisms and it's really the same basic system whether it's detecting its own signal or that of another organism. 

Thus, I propose to obsolete these two terms, which have no annotations anyway, since I do not think there is a different process going on between these two things, rather just some differences in specific interactions:
- interspecies quorum sensing (GO:0052097)
- intraspecies quorum sensing (GO:0052100)

----------

**References:**
Mony et al. 2014. Genome-wide dissection of the quorum sensing signalling pathway in Trypanosoma brucei. Nature. 2505(7485):681-685. PMID:24336212 (31 IMP annotations)

Fujiya et al. 2007. The Bacillus subtilis quorum-sensing molecule CSF contributes to intestinal homeostasis via OCTN2, a host cell membrane transporter. Cell Host Microbe. 1(4):299-308.  PMID:18005709 (1 IMP annotation, 1 IDA annotation)

Bassler BL, Losick R. 2006. Bacterially speaking. Cell. 125(2):237-46. Review. PMID:16630813.

Camilli A, Bassler BL. 2006. Bacterial small-molecule signaling pathways. Science. 311(5764):1113-6. Review. PMID:16497924

_Originally posted by @krchristie in https://github.com/geneontology/go-ontology/issues/17730#issuecomment-524072591_

**Comment by mgiglio99** [comment]
Hi all,
I agree that these two terms can be obsoleted.
Although I can imagine a scenario where particular transcription factors only respond to signals from a different species. There are no examples of that yet in the annotations.

One question not on these terms but on related ones - the term 'cell-cell signaling involved in quorum sensing' GO:0010699 as defined doesn't seem much different from its parent 'quorum sensing'. Should this term be be merged into its parent and 'quorum sensing' be made a child of 'cell-cell signaling'? (As GO:0010699 currently is)

**Comment by krchristie** [comment]
> Hi all,
> I agree that these two terms can be obsoleted.

Great. Thanks for your input.

> Although I can imagine a scenario where particular transcription factors only respond to signals from a different species. There are no examples of that yet in the annotations.

I agree with you that some components of the quorum sensing pathway, whether the receptors for detection, molecules in the signaling pathway, or transcription factors, might act only in response to either signals from members of the same species or some other species. However, it seems better to me if we make more specific terms like:
- detection of signal from same species
- detection of signal from other species
etc.

I think that these more specific terms might make more sense to annotators than the current terms, which as currently named and defined, suggest two separate processes, one for detection of and response to other members of the same species and a second one for detection of and response to other species, when the reality seems to be one system that detects and responds to multiple inputs, sometimes depending on their relative levels.
 
> One question not on these terms but on related ones - the term 'cell-cell signaling involved in quorum sensing' GO:0010699 as defined doesn't seem much different from its parent 'quorum sensing'. Should this term be be merged into its parent and 'quorum sensing' be made a child of 'cell-cell signaling'? (As GO:0010699 currently is)

That's a good question. From the original ticket, https://github.com/geneontology/go-ontology/issues/17730, discussing the definition of "quorum sensing", I'm copying a quote that I put there:

from Bassler, Bonnie L (1999). PMID:10607620
`Quorum sensing, or the control of gene expression in response to cell density, is used by both Gram-negative and Gram-positive bacteria to regulate a variety of physiological functions. In all cases, quorum sensing involves the production and detection of extracellular signalling molecules called autoinducers.`

Then here's the definition of **cell-cell signaling**:
`Def: Any process that mediates the transfer of information from one cell to another. This process includes signal transduction in the receiving cell and, where applicable, release of a ligand and any processes that actively facilitate its transport and presentation to the receiving cell.  Examples include signaling via soluble ligands, via cell adhesion molecules and via gap junctions.`

So, for quorum sensing, the definition that we're currently proposing includes the production of the signal, which I was assuming would include the biosynthetic process/pathway for producing the signal. If that's appropriate under **cell-cell signaling**, then it does seem that **quorum sensing** itself should be under **cell-cell signaling**. @ukemi - Do you have any thoughts on whether **quorum sensing** itself should be an is_a child of **cell-cell signaling**?

> Revised new definition for **quorum sensing** (from https://github.com/geneontology/go-ontology/issues/17730): - The process in which single-celled organisms carry out coordinated responses by monitoring their own population density, and often also that of other microbes, **by producing small, diffusible, signal molecules**, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.

I'll check what annotations have been made directly to '**cell-cell signaling involved in quorum sensing' GO:0010699** and see if they are enlightening.

**Comment by krchristie** [comment]
> > One question not on these terms but on related ones - the term 'cell-cell signaling involved in quorum sensing' GO:0010699 as defined doesn't seem much different from its parent 'quorum sensing'. Should this term be be merged into its parent and 'quorum sensing' be made a child of 'cell-cell signaling'? (As GO:0010699 currently is)
> 
> That's a good question. From the original ticket, #17730, discussing the definition of "quorum sensing", I'm copying a quote that I put there:
> 
> from Bassler, Bonnie L (1999). PMID:10607620
> `Quorum sensing, or the control of gene expression in response to cell density, is used by both Gram-negative and Gram-positive bacteria to regulate a variety of physiological functions. In all cases, quorum sensing involves the production and detection of extracellular signalling molecules called autoinducers.`
> 
> Then here's the definition of **cell-cell signaling**:
> `Def: Any process that mediates the transfer of information from one cell to another. This process includes signal transduction in the receiving cell and, where applicable, release of a ligand and any processes that actively facilitate its transport and presentation to the receiving cell. Examples include signaling via soluble ligands, via cell adhesion molecules and via gap junctions.`
> 
> So, for quorum sensing, the definition that we're currently proposing includes the production of the signal, which I was assuming would include the biosynthetic process/pathway for producing the signal. If that's appropriate under **cell-cell signaling**, then it does seem that **quorum sensing** itself should be under **cell-cell signaling**. @ukemi - Do you have any thoughts on whether **quorum sensing** itself should be an is_a child of **cell-cell signaling**?
> 
> > Revised new definition for **quorum sensing** (from #17730): - The process in which single-celled organisms carry out coordinated responses by monitoring their own population density, and often also that of other microbes, **by producing small, diffusible, signal molecules**, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.
> 
> I'll check what annotations have been made directly to '**cell-cell signaling involved in quorum sensing' GO:0010699** and see if they are enlightening.

I think you're right @mgiglio99. I can't see any difference between the term `cell-cell signaling involved in quorum sensing` (GO:0010699) and its parent term `quorum sensing`. In addition, the proposed new definition of `quorum sensing` that we've agreed upon in  **Question: quorum sensing GO:0009372 #17730** seems like it should be a child of `cell-cell signaling`.

I'll open a new ticket to propose merging **`cell-cell signaling involved in quorum sensing GO:0010699`** into `quorum sensing`
