### ISSUE TITLE
MAtrix: Incorrect Ensembl annotation transfer

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17750]
slc25a16 solute carrier family 25 member 16 has annotations transferred to it from human DNA2 helicase. (Ensembl pipeline)
 
I don't know who to assign this to?

  | Slc25a16 | solute carrier family 25 member 16 |   | DNA replication checkpoint |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110

  | Slc25a16 | solute carrier family 25 member 16 |   | DNA double-strand break processing |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | mitochondrial DNA replication |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | base-excision repair |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | DNA replication, removal of RNA primer |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | mitochondrial DNA repair |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | positive regulation of DNA replication |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | DNA replication, Okazaki fragment processing |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | nucleic acid phosphodiester bond hydrolysis |   | GOC | Rattus norvegicus | IEA | GO:0004518 | family not named pthr24089 | gene |   | GO_REF:0000108RGD:1600115 | 20190110

**Comment by ukemi** [comment]
Is this the correct tracker for this request?

**Comment by ValWood** [comment]
no ;)
