### ISSUE TITLE
GOREL: Make 'during' a do_not_annotate term

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17753]
Annotations to be reviewed are here: 
https://github.com/geneontology/go-annotation/issues/2607

**Comment by pgaudet** [comment]
It already is - it doesn't have the tag 'valid_for_annotation_extensions'. 

I need to check with @alexsign as to why there are annotations coming from P2GO with the 'during' relation. 

Pascale

**Comment by pgaudet** [comment]
@alexsign why are there annotations coming from P2GO with the 'during' relation?

**Comment by alexsign** [comment]
@pgaudet Hi Pascale, I can see all annotations with "during" in extension flagged as invalid. We do not automatically remove annotations which is belongs to Internal groups in Protein2GO. Instead we send out monthly report and it's up to curators to fix or delete them.

**Comment by pgaudet** [comment]
Ah !! OK thank you for the response. 

Pascale

**Comment by alexsign** [comment]
@pgaudet looks like it's 23 in total and all belongs to Alzheimers Project at University of Toronto. I'm not sure what is the best course of action in this case. I have contact email: Sejal.Patel@camh.ca

**Comment by RLovering** [comment]
Hi Both
I do not think Sejal will address these. As she was a student of mine (before she started with Uni of Toronto) I thought I had been given permission to edit her annotations, however it doesn't look like this is the case. Perhaps UniProt has this permission?

Ruth

**Comment by alexsign** [comment]
@RLovering I can give the permissions to edit this annotations if needed.

**Comment by RLovering** [comment]
I have just emailed Sejal to see if she has any thoughts on who she would like to have permission

**Comment by pgaudet** [comment]
Thanks !
