### ISSUE TITLE
new term request:nuclear exosome targeting complex

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#17768]
Hi,
could you please create a new term Go component corresponding to nuclear exosome targeting complex from  PMID:21855801
Here is few words of its function and composition:
In mammals, two distinct exosome cofactors have so far been characterized, which are the nucleolar-localized hTRAMP complex (Fasken et al., 2011, Lubas et al., 2011) and the nucleoplasm-specific Nuclear EXosome Targeting (NEXT) complex (Lubas et al., 2011). Sharing hMTR4 with hTRAMP, the otherwise distinct trimeric NEXT complex is further composed of the RNA recognition motif (RRM)-containing RBM7 and the zinc-knuckle ZCCHC8 proteins. Consistent with their different nuclear localization, hTRAMP and NEXT complexes operate on different RNA substrates. While hTRAMP is involved in oligoadenylation of nucleolar rRNAs to facilitate their decay, depletion of NEXT subunits leads to the stabilization of nuclear exosome substrates such as PROMoter uPstream Transcripts (PROMPTs) and 3′-extended products from U1/U2 snRNA- and replication-dependent histone (RDH) genes (Andersen et al., 2013, Lubas et al., 2011, Ntini et al., 2013, Shcherbik et al., 2010).
Many thanks.
Guilaine

**Comment by bmeldal** [comment]
Not the most stringent evidence as it's a combination of various experiments that also contain core exosome proteins but if subunit composition changes it can always be amended. Although, given the paper is 8 years old, maybe there's new evidence? I don't have time to that search.
