### ISSUE TITLE
Obsolete 'cell part' terms and upper level reorganization

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17778]
Obsoletion notice: 'x part' terms

Dear all, 

GO is reorganizing some of the top level terms in the Cellular Component branch to better fit future annotation requirements. (see also [1])

We have created a new term, 'cellular anatomical entity', that groups all cellular components that are not protein-containing complexes or whole cells. Now the CC aspect of the ontology will have the following main branches: 

- cell
- 'cellular anatomical entity'
- intracellular (see [2])
- 'other organism part'
- 'protein-containing complex'
- virion
- 'virion part'

As a part of this reorganization we are obsoleting 'x part' terms such as 'nuclear part'. Instead, parts will be asserted directly in the ontology. For example, a term x that is a nuclear part will have the relationship x part_of nucleus. 

The following terms will be obsoleted: 

GO:0033267 axon part
GO:0044447 axoneme part
GO:0097312 bacterial biofilm matrix component
GO:0044461 bacterial-type flagellum part
GO:0044448 cell cortex part
GO:0032155 cell division site part
GO:0044464 cell part - mapped to NIF_Subcellular:sao628508602
GO:0044463 cell projection part
GO:0044457 cell septum part
GO:0044426 cell wall part
GO:0044434 chloroplast part
GO:0044427 chromosomal part
GO:0044441 ciliary part
GO:0060103 collagen and cuticulin-based cuticle extracellular matrix part
GO:0044449 contractile fiber part
GO:0044444 cytoplasmic part
GO:0044433 cytoplasmic vesicle part
GO:0044430 cytoskeletal part
GO:0044445 cytosolic part
GO:0044432 endoplasmic reticulum part
GO:0044440 endosomal part
GO:0044462 external encapsulating structure part
GO:0044420 extracellular matrix component
GO:0044421 extracellular region part
GO:0044431 Golgi apparatus part
GO:0044424 intracellular part
GO:0110144 magnetosome part
GO:0044425 membrane part
GO:0044438 microbody part
GO:0044450 microtubule organizing center part
GO:0044455 mitochondrial membrane part
GO:0044429 mitochondrial part
GO:0097458 neuron part
GO:0044454 nuclear chromosome part
GO:0044453 nuclear membrane part
GO:0044428 nuclear part - mapped to NIF_Subcellular:  sao1499850686
GO:0044452 nucleolar part
GO:0044451 nucleoplasm part
GO:0044422 organelle part
GO:0044439 peroxisomal part
GO:0044443 pilus part
GO:0120038 plasma membrane bounded cell projection part
GO:0044459 plasma membrane part
GO:0044435 plastid part
GO:0097425 smooth endoplasmic reticulum part - mapped to NIF_Subcellular:sao184202831
GO:0097223 sperm part
GO:0044456 synapse part - mapped to NIF_Subcellular:sao1784069613
GO:0044436 thylakoid part
GO:0044437 vacuolar part

**goslim-pir:** 
GO:0044464 cell part

**go-slim-flybase-ribbon**
GO:0097458 neuron part

Darren, Helen: Let me know if you want other terms instead in your slim. 

There are a few annotations to those terms: 
https://github.com/geneontology/go-annotation/issues/2632

affecting the folowing groups: 
AspGD : 1 annotation
CGD : 2 
GeneDB : 1
GR : 2
JCVI : 1
MGI : 13
SGN : 7 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/17778

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 4th, 2019. Unless objections are received by September 4th, 2019 we will assume that you agree to this change. 

Thanks, Pascale

[1] https://github.com/geneontology/go-ontology/issues/17696
[2] https://github.com/geneontology/go-ontology/issues/17776

**Comment by balhoff** [comment]
This is done.

**Comment by hattrill** [comment]
Hi @pgaudet - does this mean that there will be a new term "neuron" so that there is a x part_of neuron as this does not currently exist?

**Comment by pgaudet** [comment]
No. You can annotate to occurs_in CL:neuron, if appropriate, a GO term for the intracellular localization. 

Pascale

**Comment by ukemi** [comment]
I think we can close this one?
