### ISSUE TITLE
Intracellular children?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17776]
Currently the only subtype of this class is SMAD complex. Do we really mean for this term to represent an intracellular anatomical entitiy? We need to be able to define it more precisely.

**Comment by pgaudet** [comment]
Maybe this one is under intracellular because it's both cytosolic and nuclear, so cytoplasmic would not be right; although I assume that's not the only case - all nuclear receptors for example...

**Comment by ukemi** [comment]
I think the solution here is to rename it 'intracellular region' and change the def to: A cellular anatomical structure contained within (but not including) the plasma membrane. In eukaryotes it includes the nucleus and cytoplasm.

1104 terms 'cellular anatomical entity' and 'part of' some intracellular..... sigh

**Comment by balhoff** [comment]
How about 'intracellular anatomical structure'? To me, 'region' would seem to *contain* 'nucleus' rather than be a superclass.

**Comment by pgaudet** [comment]
Would 'intracellular anatomical structure' contain complexes ? (thinking of the SMAD issue above)

**Comment by pgaudet** [comment]
OK, good.

**Comment by pgaudet** [comment]
Decisions: WRT intracellular

 - [ ]   SMAD complex: remove 'intracellular' parent
 - [ ]  change label 'intracellular' to 'intracellular anatomical structure' 
 - [ ]  change def intracellular to "A component of a cell contained within (but not including) the plasma membrane. In eukaryotes it includes the nucleus and cytoplasm."


Thanks, Pascale

**Comment by ukemi** [comment]
I thought this needed more than just a label change, but I think the group had decided to change the label.

**Comment by pgaudet** [comment]
Yes I made all changes suggested above (the check boxes were not updating - sorry)
