### ISSUE TITLE
OTR: diff between GO:0030316 osteoclast differentiation and GO:0072674 multinuclear osteoclast differentiation?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17791]
GO:0030316 osteoclast differentiation:
The process in which a relatively unspecialized monocyte acquires the specialized features of an osteoclast. An osteoclast is a specialized phagocytic cell associated with the absorption and removal of the mineralized matrix of bone tissue. PMID:12161749 

GO:0072674 **multinuclear** osteoclast differentiation:
The process in which a relatively unspecialized monocyte acquires the specialized features of a **multinuclear** osteoclast. An osteoclast is a specialized phagocytic cell associated with the absorption and removal of the mineralized matrix of bone tissue. PMID:12713016

Wikipedia:
An osteoclast is a large **multinucleated** cell and human osteoclasts on bone typically have five nuclei and are 150–200 µm in diameter. When osteoclast-inducing cytokines are used to convert macrophages to osteoclasts, very large cells that may reach 100 µm in diameter occur. These may have dozens of nuclei, and typically express major osteoclast proteins but have significant differences from cells in living bone because of the not-natural substrate.[4][5] The size of the multinucleated assembled osteoclast allows it to focus the ion transport, protein secretory and vesicular transport capabilities of many macrophages on a localized area of bone.

Seems to me that osteoclasts are **multinuclear** by definition.
-> Collapse child into parent term?

**Comment by ukemi** [comment]
The cell ontology has three subclasses of osteoclast: odontoclast, mononuclear osteoclast and multinuclear osteoclast. The classes have many references associated with them and GO uses the cell ontology as its source of cell information.

**Comment by bmeldal** [comment]
Ok, I didn't cf cell ontology links.
