### ISSUE TITLE
Merge terms -  'response to phytoalexin production by other organism involved in symbiotic interaction' and children (was:obsolete...) 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17790]
While working on #17441 

I came across this branch: 

-  GO:0052549 response to phytoalexin production by other organism involved in symbiotic interaction
- - GO:0052566 response to host phytoalexin production
- - - GO:0052378 evasion or tolerance by organism of phytoalexins produced by other organism involved in symbiotic interaction
- - -  - GO:0052061 evasion or tolerance by symbiont of host-produced phytoalexins 

- - - GO:0052304 modulation by organism of phytoalexin production in other organism involved in symbiotic interaction
- - -  GO:0052329 positive regulation by organism of phytoalexin production in other organism involved in symbiotic interaction 
- - - -  GO:0052165 modulation by symbiont of host phytoalexin production
- - - - - GO:1990217 negative regulation by symbiont of host phytoalexin production
- - - - -  GO:0052344 positive regulation by symbiont of host phytoalexin production 
- - - - - - GO:0052062 induction by symbiont of host phytoalexin production

The only term with annotations is 'GO:0052062 induction by symbiont of host phytoalexin production'; 5 annotations by PAMGO_VMD. The process described in the annotated papers would fit better under 'GO:0080185 effector-dependent induction by symbiont of host immune response'. 

I propose we obsolete the terms listed above, and add 'replace by' or 'consider' 'GO:0080185 effector-dependent induction by symbiont of host immune response'. 

@mgiglio99 @ValWood what do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@tberardini maybe you want to weigh in as well ?

**Comment by ValWood** [comment]
I don't see any annotations to these terms? Where do you see them?

**Comment by ValWood** [comment]
I agree they should be obsoleted, and your  replaced_by solution sounds sensible

**Comment by pgaudet** [comment]
Annotations are here: http://amigo.geneontology.org/amigo/term/GO:0052062
I think there are no annotations in QuickGO because the IDs are not valid. 

Pascale

**Comment by pgaudet** [comment]
Discussing with @mgiglio99  - here's the plan: 


Term | Action
-- | --
GO:0052062 induction by symbiont of host   phytoalexin production | > Move under 'interaction with host'
  |  
Merges |  
GO:0052329 positive regulation by   organism of phytoalexin production in other organism involved in symbiotic   interaction | GO:0052344 positive regulation by symbiont of host phytoalexin production
GO:0052549 response to phytoalexin   production by other organism involved in symbiotic interaction | GO:0052566 response to host phytoalexin production
GO:0052378 evasion or tolerance by   organism of phytoalexins produced by other organism involved in symbiotic   interaction | GO:0052061 evasion or tolerance by symbiont of host-produced phytoalexins
GO:0052304 modulation by organism of   phytoalexin production in other organism involved in symbiotic interaction | GO:0052165 modulation by symbiont of host phytoalexin production
  |  
GO:1990217 negative regulation by   symbiont of host phytoalexin production | OK
