### ISSUE TITLE
make phase branch of GO an ontology subset

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17792]
Would it be possible to make the 'phase' branch of GO an ontology subset?
https://www.ebi.ac.uk/QuickGO/term/GO:0044848
and descendants

Restrictions
This term should not be used for direct manual annotation; it may, however, be used for mapping to external vocabularies in order to create electronic annotations. 
See comment below for further information.

Comments
Note that phases are is_a disjoint from other biological processes. happens_during relationships can operate between phases and other biological processes e.g. DNA replication happens_during S phase.

this would allow us to easily configure our curation tool to  'hide' these for  direct annotation, and only make available as extensions.

https://github.com/pombase/canto/issues/1794

**Comment by ukemi** [comment]
Isn't it already since biological phase is a term?

**Comment by ValWood** [comment]
We wanted it to  have a subset def and tags in the ontology. I don't think this is the case.  You ned to read the comment.

**Comment by pgaudet** [comment]
You want all the terms in that branch to be in the same subset ? 
The 'do not annotate' flag is not enough to filter the terms out of the annotation tool ?

**Comment by ValWood** [comment]
I'll close this. I don't know why I wanted to do it. I think it was to make the branch available for extensions in other contexts  but we already do that so there isn't a problem.
