### ISSUE TITLE
New Go term: Eupatolide synthase

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#17803]
Hi GO,

I would need a GO term for Eupatolide synthase activity (which hydroxylates 8-beta-hydroxy-germacrene A acid to 6-alpha,8-beta-hydroxy-germacrene A acid, which, in turn, undergo spontaneous lactonization to become eupatolide)

Thanks

Emmanuel

Term: Eupatolide synthase activity
Definition:
Catalysis of the reaction: 
8beta-hydroxygermacra-1(10),4,11(13)-trien-12-oate + O2 + reduced [NADPH--hemoprotein reductase] = eupatolide + 2 H2O + oxidized [NADPH--hemoprotein reductase];

probably child of GO:0004497 monooxygenase activity

Xref:
RHEA:57972
EC:1.14.14.169

PMID:29758164;

**Comment by SuperManu74** [comment]
UP

**Comment by hdrabkin** [comment]
sorry this slipped by ; adding today.
+id: GO:0106244
+name: eupatolide synthase activity
