### ISSUE TITLE
voltage-gated ion channel activity parentage

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17807]
GO:0005244 voltage-gated ion channel activity parentage

is a child of voltage-gated channel activity and ion gated channel activity. Looking at https://en.wikipedia.org/wiki/Voltage-gated_ion_channel, I think that the mechanism should be only defined as voltage-gated

gated channel activity 
 |__voltage-gated channel activity__|
 |__ion gated channel activity ______|
                                                          |__voltage-gated ion channel activity

**Comment by pgaudet** [comment]
This was caused by an incorrect logical definition for 'ion gated channel activity': 

-intersection_of: GO:0022836 ! gated channel activity
-intersection_of: transports_or_maintains_localization_of CHEBI:24870 ! ion

I removed it. 

Thanks for reporting ! 

Pascale

**Comment by hattrill** [comment]
Ace! Thanks!
