### ISSUE TITLE
New GO term: Germacrene A hydroxylase

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#17801]
Hi GO,

I would need a GO term for Germacrene A hydroxylase activity (which mediates formation of germacrene A acid from germacrene A via multisteps reactions)

Thanks

Emmanuel

Term: Germacrene A hydroxylase activity
Definition:
Catalysis of the reaction: 
(+)-(R)-germacrene A + 3 O2 + 3 reduced [NADPH--hemoprotein reductase] = germacra-1(10),4,11(13)-trien-12-oate + 4 H(+) + 4 H2O + 3 oxidized [NADPH--hemoprotein reductase];

child of GO:0004497 monooxygenase activity

Xref:
RHEA:30303
EC:1.14.14.95

PMID:20351109;
PMID:11299372;
PMID:20351109;

**Comment by hdrabkin** [comment]
+id: GO:0106223
+name: germacrene A hydroxylase activity
