### ISSUE TITLE
NTR: decoy receptor complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17809]
A complex term to go with GO:0140319 receptor decoy activity

Name: decoy receptor complex
Def: A receptor complex that recognizes, binds and sequesters a specific receptor ligand to prevent it from binding to its regular receptor. May be soluble or membrane bound.

Relationships:
is_a GO:0043235 receptor complex
capable_of GO:0140319 receptor decoy activity

Reference:
PMID:9168977
PMID:30621730

GOCID:bhm

Synonyms:
Osteoprotegerin complex [NARROW]
Osteoclastogenesis inhibitory factor [NARROW]

Editor, please ignore.
Note to self: EBI-21990873

**Comment by deustp01** [comment]
Or should this be an annotation (GO-CAM?) that combines binding and negative regulation, analogous to the ligand trap annotation in our BMP signaling pathway ([R-HSA-201451](https://reactome.org/PathwayBrowser/#/R-HSA-201451&PATH=R-HSA-162582,R-HSA-9006936) - particularly reactions [R-HSA-201457](https://reactome.org/PathwayBrowser/#/R-HSA-201451&SEL=R-HSA-201457&PATH=R-HSA-162582,R-HSA-9006936) and [R-HSA-201443](https://reactome.org/PathwayBrowser/#/R-HSA-201451&SEL=R-HSA-201443&PATH=R-HSA-162582,R-HSA-9006936)?

**Comment by bmeldal** [comment]
This is to link the CP entry to a GO complex term. If you feel that decoy receptor is not valid I'll have to link it to "receptor complex"...

**Comment by ValWood** [comment]
hi @deustp01 ,

It hink we still require "receptor decoy activity" for GOCAM modellig

As I understand it @pgaudet  is trying to establish MF terms to cover binding annotations when the mechanism is known..
We would use MF part of Process to connect a molecular function   to a biological process in GOCAM syntax, but not a MF term + BP term to capture a molecular function.

**Comment by pgaudet** [comment]
The activity is fine; do we need a complex ?

**Comment by bmeldal** [comment]
Does that mean 'decoy receptor complex' is outside the scope of GO?
