### ISSUE TITLE
'interaction with host' definition probably needs improvement

### ISSUE THREAD

**Issue by yongqunh** [geneontology/go-ontology#17812]
In OHMI, we define 'host-microbiome interaction' as a subclass of GO 'interaction with host'. However, this assertion is not a good fit because the term 'host-microbiome interaction' focuses on two organisms rather than a host organism and a collection of microorganisms which is needed for the host-microbiome interaction.

**Comment by pgaudet** [comment]
Hi @yongqunh 

What is your request exactly ? 'host-microbiome interaction' is outside the scope of GO, as it defines relations between organisms. GO represents the functions of genes. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@yongqunh just checking if you can please answer my question ?

**Comment by yongqunh** [comment]
@pgaudet you are right that the term 'host-microbiome interaction' defines relations between organisms. So it is outside the scope of GO. Thanks.
