### ISSUE TITLE
mRNA (cytosine-5-)-methyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17813]
Hi GO,

I would need two terms to cover mRNA (cytosine-5-)-methylation

Thanks

Sylvain

1) One term for the enzyme catalyzing the modification:
Term: mRNA (cytosine-5-)-methyltransferase activity
Category: Function
Definition: Catalysis of the reaction:: a cytidine in mRNA + S-adenosyl-L-methionine = a 5-methylcytidine in mRNA + H(+) + S-adenosyl-L-homocysteine

child of  GO:0008174 mRNA methyltransferase activity
PubMed=23871666
PubMed=22395603

2) One term for the 'reader' of this modification
Term: C5-methylcytosine-containing RNA binding
Category: Function
Definition: Interacting selectively and non-covalently with an RNA molecule modified by C5-methylcytosine

child of GO:0003723 RNA binding
PubMed=28418038

**Comment by ukemi** [comment]
Hi Sylvain. We should request this in Rhea. All I see are the tRNA and rRNA ones. Looks like this will be an important mechanism of epitranscript marking.

**Comment by ukemi** [comment]
Note we might want to name it mRNA (cytidine-5-)-methyltransferase activity? See Rhea:47780 for a similar example. At some point we need to figure out a strategy for the Rhea generics. ping @deustp01 @hdrabkin @cmungall @balhoff @goodb

**Comment by sylvainpoux** [comment]
Hi David,
here is the Rhea reaction for the mRNA (cytidine/cytosine-5-)-methyltransferase activity

Xref: RHEA:61464,

Thanks

Sylvain

CC   -!- CATALYTIC ACTIVITY:
CC       Reaction=a cytidine in mRNA + S-adenosyl-L-methionine = a 5-
CC         methylcytidine in mRNA + H(+) + S-adenosyl-L-homocysteine;
CC         Xref=Rhea:RHEA:61464, Rhea:RHEA-COMP:15145, Rhea:RHEA-
CC         COMP:15826, ChEBI:CHEBI:15378, ChEBI:CHEBI:57856,
CC         ChEBI:CHEBI:59789, ChEBI:CHEBI:74483, ChEBI:CHEBI:82748;
CC         Evidence={ECO:0000269|PubMed:22395603,
CC         ECO:0000269|PubMed:28418038, ECO:0000269|PubMed:31358969};

**Comment by ukemi** [comment]
Thanks Sylvain. I'm adding the terms now, but will keep this open so I can remember to add the Rhea xref when it is public. Sorry for the delay!

**Comment by hdrabkin** [comment]
RHEA added; removing tag
