### ISSUE TITLE
Merge terms for plant defense responses

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17827]
Hello, 

Continuing the work on the multi-species processes, aiming to remove terms that represent processes for which there is no evidence exists, I would like to merge the following terms: 

TERM | MERGE INTO
-- | --
GO:0052445 modulation   by organism of defense-related salicylic acid-mediated signal transduction   pathway in other organism involved in symbiotic interaction | GO:0052081 modulation by   symbiont of defense-related host salicylic acid-mediated signal transduction   pathway
GO:0052252 negative   regulation by organism of defense-related salicylic acid-mediated signal   transduction pathway of other organism involved in symbiotic interaction | GO:0052003 negative   regulation by symbiont of defense-related host salicylic acid-mediated signal   transduction pathway
GO:0052270 positive   regulation by organism of defense-related salicylic acid-mediated signal   transduction pathway in other organism involved in symbiotic interaction | GO:0052072 positive   regulation by symbiont of defense-related host salicylic acid-mediated signal   transduction pathway
GO:0052443   modulation by organism of defense-related jasmonic acid-mediated signal   transduction pathway in other organism involved in symbiotic interaction | GO:0052082 modulation by   symbiont of defense-related host jasmonic acid-mediated signal transduction   pathway
GO:0052267   negative regulation by organism of defense-related jasmonic acid-mediated   signal transduction pathway in other organism involved in symbiotic   interaction | GO:0052069 negative regulation   by symbiont of defense-related host jasmonic acid-mediated signal   transduction pathway
GO:0052271   positive regulation by organism of defense-related jasmonic acid-mediated   signal transduction pathway in other organism involved in symbiotic   interaction | GO:0052073 positive regulation   by symbiont of defense-related host jasmonic acid-mediated signal   transduction pathway
GO:0052279   modulation by organism of ethylene-mediated defense response of other   organism involved in symbiotic interaction | GO:0052084 modulation by   symbiont of host ethylene-mediated defense response
GO:0052254   negative regulation by organism of ethylene-mediated defense response of   other organism involved in symbiotic interaction | GO:0052005 negative regulation   by symbiont of host ethylene-mediated defense response
GO:0052274   positive regulation by organism of ethylene-mediated defense response of   other organism involved in symbiotic interaction | GO:0052076 positive regulation   by symbiont of host ethylene-mediated defense response
GO:0052268   negative regulation by organism of defense-related ethylene-mediated signal   transduction pathway in other organism involved in symbiotic interaction | GO:0052005 negative regulation   by symbiont of host ethylene-mediated defense response
GO:0052269   positive regulation by organism of defense-related ethylene-mediated signal   transduction pathway in other organism involved in symbiotic interaction | GO:0052076 positive regulation   by symbiont of host ethylene-mediated defense response

The reason is that these are plant-specific defense responses, and AFAIK there is no evidence that processes such as 'positive regulation by host of symbiont ethylene-mediated defense response - I dont think plants are ever symbionts ?? 

@tberardini Is this a reasonable proposal ? 

Thanks, Pascale

**Comment by tberardini** [comment]
> @tberardini Is this a reasonable proposal ?

I just saw this so no time to think about whether it's reasonable or not but it looks like you've gone ahead and merged. Fait accompli :)

**Comment by pgaudet** [comment]
I can unmerge if its a problem.

**Comment by tberardini** [comment]
Not a problem, I didn't have time to look at this on Friday.
