### ISSUE TITLE
fix pyruvate dehydrogenase activities

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17822]
```
EC:1.2.1.51 > GO:pyruvate dehydrogenase [NAD(P)+] activity ; GO:0034603
EC:1.2.1.51 > GO:pyruvate dehydrogenase (NADP+) activity ; GO:0050243
```
enzyme.dat:
```
ID   1.2.1.51
DE   Pyruvate dehydrogenase (NADP(+)).
AN   Pyruvate:NADP(+) oxidoreductase.
CA   Pyruvate + CoA + NADP(+) = acetyl-CoA + CO(2) + NADPH.
```
So, EC:1.2.1.51 === GO:0050243, and GO:0050243 is_a GO:0034603. Thus, GO:0034603 is a superset of EC:1.2.1.51 and so can no longer have an association with it.

I'll submit a PR.

**Comment by rwst** [comment]
@pgaudet Is the merge final, so this ticket and the PR can be closed?

Re: NAD(P): there are 159 definitions containing the string

**Comment by pgaudet** [comment]
Ah ! This is not a `git merge` - I was suggesting to merge the 2 terms. 

I think @hdrabkin should have a look at these before we finalize. He's off until Monday, it should be done early next week. 

Thanks, Pascale

**Comment by deustp01** [comment]
@pgaudet said 

> @ukemi Did we not say we would get rid of the "NAD(P) " terms any only keep the specific ones ?

We may have (forgetfulness here) but, there is maybe one mammalian enzyme that can use either  NAD or NADP, and probably in other non-vertebrate domains of life that don't use the mammalian strategy to maintain separate pools of reducing equivalents for energy generation (NAD) and for biosyntheses (NADP) there are more.

My recollection of @ukemi 's fix was that it was directed more to sorting out parentage in the ontology, to properly show relationships among functions that require NAD, ones that require NADP, and ones where the specific requirement NAD vs NADP has not been established? So sorting @rwst 's 159 definitions into these three categories looks like a next step.

**Comment by pgaudet** [comment]
OK, thanks for the reminder.

**Comment by ukemi** [comment]
@deustp01, that is correct. The discussion was about NAD(P) in the definitions and whether or not those classes represented both reactions or either reaction. From an ontological standpoint since ChEBI has NAD and NADP as children of NAD(P), we decided it had to mean either. If we know that a particular 'gene product' can catalyze both, we would annotate to both children.

**Comment by pgaudet** [comment]
My recollection was that there were only a few enzymes for which we needed the general term, NAD(P), is pyruvate dehydrogenase one of them ?

**Comment by deustp01** [comment]
L Reed, who is probably the preeminent authority (PMID: 2188967) says pyruvate dehydrogenase uses only NAD, on the basis of studies of various mammals and eubacteria, and says the same for other alpha-ketoacid dehydrogenases.

**Comment by ukemi** [comment]
In Euglena, from metacyc? PMID:3110154, PMID:11023353, PMID:11319255.

**Comment by deustp01** [comment]
Looking quickly at the first PMID, the Euglena enzyme may qualify for the same EC number (needs more enzymology expertise than I have) but looks like it mediates a distinct biological function so it might qualify for a different GO term, a case of one EC mapping to more than one GO MF. I suspect that Rhea would be with GO in this case because once all the small molecule participants are listed (and not only the NADP vs NAP) it looks like a chemcially distinct reaction. @hdrabkin ?

**Comment by hdrabkin** [comment]
SO what I thought was agreed on is that the "either P or not P" would be removed and have the two (NAD, and NADP) and that if something uses both, you would annotate to both. Am I wrong?

**Comment by deustp01** [comment]
This is exactly the parentage issue that @ukemi sorted out. The solution made perfect sense when I read it but I can't now reconstruct it so you need to ask him.

**Comment by ukemi** [comment]
If the enzyme uses both in a natural setting, then the gene product encoding that enzyme should be annotated to both the NAD+ term and the NADP term. If the enzyme ever only uses one, then the gene product encoding the enzyme should be annotated to the appropriate term. The NAD(P) terms, for the moment, are used for cases of ambiguity where we don't know. This is probably a rare case, but for now we will keep these as grouping classes.

**Comment by rwst** [comment]
As you don't seem to see a need for documentation the ticket becomes irrelevant to me. Closed.

**Comment by hdrabkin** [comment]
Removed EC from GO:0034603
