### ISSUE TITLE
EC numbers linked with multiple functions 

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17821]
I'm trying to model exactly those GO function items that have an EC number. There is a basic problem with some of them, their relative position in the ontology. Example from the ec2go file:
```
EC:1.4.3.21 > GO:primary amine oxidase activity ; GO:0008131
EC:1.4.3.21 > GO:tryptamine:oxygen oxidoreductase (deaminating) activity ; GO:0052593
EC:1.4.3.21 > GO:aminoacetone:oxygen oxidoreductase(deaminating) activity ; GO:0052594
EC:1.4.3.21 > GO:aliphatic-amine oxidase activity ; GO:0052595
EC:1.4.3.21 > GO:phenethylamine:oxygen oxidoreductase (deaminating) activity ; GO:0052596
```
From inspection the EC:1.4.3.21 itself corresponds exactly to primary amine oxidase activity (GO:0008131). From this formally, the other GO items would be subsets/subclasses of GO:0008131, so should have GO:0008131 as parent in the ontology. Instead all have GO:0016641 (EC:1.4.3) as parent. This is not wrong but fails to include the knowledge that there is an exact correspondence between GO:0008131 and EC:1.4.3.21, with all derived conclusions that could be made.

So, either the parent-children relations in the ontology could be improved, or some function items should have different EC numbers. Note this is only one example, see below. In my opinion ec2go should attach a qualifier exact/broad/narrow to every EC-->GO association so the GO ontology can have the proper topology.

Other examples:
```
EC:3.1.1.4 > GO:phospholipase A2 activity ; GO:0004623
EC:3.1.1.4 > GO:phospholipase A2 activity (consuming 1,2-dipalmitoylphosphatidylcholine) ; GO:0102567
EC:3.1.1.4 > GO:phospholipase A2 activity consuming 1,2-dioleoylphosphatidylethanolamine) ; GO:0102568
=== all have parent EC:3.1.1 > GO:phospholipase activity ; GO:0004620

EC:1.4.3.22 > GO:diamine oxidase activity ; GO:0052597
EC:1.4.3.22 > GO:histamine oxidase activity ; GO:0052598
EC:1.4.3.22 > GO:methylputrescine oxidase activity ; GO:0052599
EC:1.4.3.22 > GO:propane-1,3-diamine oxidase activity ; GO:0052600
=== all have parent EC:1.4.3 > GO:oxidoreductase activity, acting on the CH-NH2 group of donors, oxygen as acceptor ; GO:0016641

EC:3.2.1.1 > GO:alpha-amylase activity ; GO:0004556
EC:3.2.1.1 > GO:alpha-amylase activity (releasing maltohexaose) ; GO:0103025
=== all have parent EC:3.2.1 > GO:hydrolase activity, hydrolyzing O-glycosyl compounds ; GO:0004553

```(lots more)

**Comment by rwst** [comment]
With #17892 this could be resolved by giving an exact assertion to one of the entries.

**Comment by hdrabkin** [comment]
I'm not sure I understand your point here. Note that a single EC (4 digit) can be associated with more than one GO term. We are working to have a single RHEA as an xref to any one particular GO term.  THe RHEA will then become the exact definition for the GO term.  Often RHEA maps a single EC to multiple RHEA. 
The 3 digit parents, as you say are not wrong. They indicate a common mechanism.

**Comment by rwst** [comment]
As you say we have multiple GO terms associated with one EC, and often one of the GOs is defined exactly as the EC (the other GOs being children of it). In this case the parent would be distinguished by having an exact_database_cross_reference to the EC while the children remain normal database_cross_references. But I just see and you are right, this is not applicable with this ticket.

**Comment by rwst** [comment]
> We are working to have a single RHEA as an xref to any one particular GO term.

Glad to hear. I think I'll wait for that as it completely changes the situation.
