### ISSUE TITLE
Merge  GO:0004739 pyruvate dehydrogenase (acetyl-transferring) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17825]
Hello, 

Following up on #17822, I checked the PAINT annotations and a few references. According to reaction in Figure 1 in PMID: 19081061 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/4782928/64843439-6ccc0000-d605-11e9-9931-311141617070.png">

I think O:0034604 pyruvate dehydrogenase (NAD+) activity should be merged into 
 GO:0004739 pyruvate dehydrogenase (acetyl-transferring) activity. 

We could perhaps merge or obsolete  GO:0034603 pyruvate dehydrogenase [NAD(P)+] activity (no annotations; inaccurately assigned to EC:1.2.1.51 , as reported in #17822).

Thanks, Pascale

**Comment by ValWood** [comment]
I was just looking at this because in SGD and hence in pombase the 
E1 subunits are annotated with pyruvate dehydrogenase (acetyl-transferring) activity even though they produce Co2 and NADH.

It would be useful to resolve this.

@rozaru

**Comment by ValWood** [comment]
For reference 
The PDH complex composed of three main enzyme components:

E1 (Pyruvate dehydrogenase enzyme): It catalyzes the decarboxylation of pyruvate, releasing CO
  and forming a hydroxyethyl-TPP intermediate.
E2 (Dihydrolipoyl transacetylase): This enzyme transfers the acetyl group from the hydroxyethyl-TPP intermediate to coenzyme A, forming acetyl-CoA.
E3 (Dihydrolipoyl dehydrogenase): It regenerates the oxidized form of the lipoamide and reduces NAD
  to NADH in the process.

**Comment by sjm41** [comment]
The PDH E1 subunits ought to be annotated as follows:

enables **pyruvate dehydrogenase (NAD+) activity**(GO:0034604) = EC:1.2.1.104
(i.e. the specific activity of E1)

contributes_to **pyruvate dehydrogenase (acetyl-transferring) activity**(GO:0004739) = EC:1.2.4.1
(i.e. the overall activity of the PDH complex)

Definitely don't want to merge GO:0034604 and GO:0004739

**Comment by ValWood** [comment]
Got it.
Will ask SGD to make the missing annotations.
@edwong57  could SGD co-annotate pda1 and pdb1 the e1 subunits to 
pyruvate dehydrogenase (NAD+) activity(GO:0034604) = EC:1.2.1.104

Also, some of the descriptions seem to be slightly wrong.
For example PDA1  has 
Pyruvate dehydrogenase (acetyl-transferring) subunit of the mitochondrial pyruvate dehydrogenase complex

**Comment by sjm41** [comment]
Sorry, entered my previous comment too quickly and made some errors - now edited and corrected!

**Comment by ValWood** [comment]
@sjm41  do you agree that we can close this one as a duplicate?
