### ISSUE TITLE
fix parent link of 1-methoxypyrene 6,7-monooxygenase activity

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17829]
This has a wrong parent, introduced in e62999696 (i.e. from #12211):
```
id: GO:0034932
name: 1-methoxypyrene 6,7-monooxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: 1-methoxypyrene + O2 + 2 H+ + 2 e- = 1-methoxypyrene-6,7-oxide + H2O." [UM-BBD_reactionID:r0954]
xref: UM-BBD_reactionID:r0954
is_a: GO:0016638 ! oxidoreductase activity, acting on the CH-NH2 group of donors
```
http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0954 has this as EC:1.14.-.- (GO:0016705 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen). So I think the is_a link is wrong, as there is no CH-NH2 in any reaction part.

**Comment by hdrabkin** [comment]
Done
