### ISSUE TITLE
integral component of membranes: complexes or anatomical entities

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17836]
While cleaning up dual parentage of protein-containing complexes and cellular anatomical entities there were a few terms that were 'integral to blah membrane' and therefore classified as cellular anatomical entities. 
high-affinity iron exporter complex
high-affinity iron permease complex
mitochondrial respiratory chain complex IV pre-assembly complex
I cleaned them up by making them part-of the respective membranes for now. We should either move the integral etc terms to be direct children of the root class. Or even better, we should eliminate the spatial terms and create better more complete spatial relations in the ontology: spans, adjacent_to etc. This is a large project but we have talked about it many times.

**Comment by ukemi** [comment]
See this PR: #17839

**Comment by deustp01** [comment]
Start by cleaning up a distinction I made badly on the September 9 ontology call. The distinction that is probably useful is between cell components that are impermeable like plasma and vesicle membranes and ones that are permeable like the nucleolus or a glycogen granule. For the second kind of component, these relationships (adjacent, spans, etc.) may still be formally relevant but for reasoning to determine whether something located "here" can make direct contact with something located "there" they aren't needed. That's sort of a tangent - wanted to get it out before forgetting,

**Comment by bmeldal** [comment]
> I cleaned them up by making them part-of the respective membranes for now. 

That's what I expected they all were. Pattern should be `complex` *part_of* `cellular anatomical entity`. That's how we annotate anyway.

As for changing it to more expressive relationships I would need a bit more info as to how that would work.

**Comment by pgaudet** [comment]
I think this is done - all complexes are under protein-containing complex. Please re-open if I missed some instances.
