### ISSUE TITLE
merge polyprenyl dihydroxybenzoate methyltransferase activities

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17834]
The definitions show **3**-polyprenyl-4,**5**-dihydroxybenzoate and **3**,4-dihydroxy-**5**-polyprenylbenzoate but this is the same molecule, see https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:64694 --- exchanging 3 and 5 changes nothing. So the definition of GO:0010420 and GO:1990886 are identical. The nearest parent of the united item should be GO:0008757: S-adenosylmethionine-dependent methyltransferase activity.
```
id: GO:0010420
name: polyprenyldihydroxybenzoate methyltransferase activity
def: "Catalysis of the reaction: S-adenosyl-L-methionine + 3-polyprenyl-4,5-dihydroxybenzoate = S-adenosyl-L-homocysteine + 3-polyprenyl-4-hydroxy-5-methoxybenzoate + H+." [PMID:9628017]
xref: MetaCyc:RXN-9281
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

id: GO:1990886
name: 3,4-dihydroxy-5-polyprenylbenzoic acid O-methyltransferase activity
def: "Catalysis of the reaction: 3,4-dihydroxy-5-polyprenylbenzoic acid + S-adenosyl-L-methionine = 3-methoxy-4-hydroxy-5-polyprenylbenzoic acid + S-adenosyl-L-homocysteine + H+." [EC:2.1.1.114, PMID:10419476, RHEA:44452]
xref: EC:2.1.1.114
is_a: GO:0008171 ! O-methyltransferase activity

```

**Comment by hdrabkin** [comment]
I know I wrote comments here; The metacyc id actually refers to 
3,4-dihydroxy-5-polyprenylbenzoic acid, not a 3-polyprenyl-4,5-dihydroxybenzoate
Anyway, will merge GO:0010420 into GO:1990886;

**Comment by hdrabkin** [comment]
More compicated; GO:0010420 has children. 
All have EC:2.1.1.114, but refer to some of the six RHEA rxns for this EC. 
5 of those reactions define a specific prenyl number (octaprenyl, hexaprenly, etc.) , whereas GO:0010420 is 'polyphenyl'.  The EC itself is thepolypreny version. so easiest is to merge GO:1990886 into GO:0010420; This will keep parent/child

**Comment by hdrabkin** [comment]
done
