### ISSUE TITLE
fix parent link of vanillate O-demethylase (anaerobic) activity

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17832]
This was introduced with #12211:
```
id: GO:0018487
name: vanillate O-demethylase (anaerobic) activity
def: "Catalysis of the reaction: vanillate + Co+ = Co3+-CH3 + 3,4-dihydroxybenzoate." [UM-BBD_reactionID:r0758]
xref: UM-BBD_reactionID:r0758
---> is_a: GO:0016623 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, oxygen as acceptor
is_a: GO:0032451 ! demethylase activity
```
The UM-BBD page http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0758 gives only the demethylase EC, and the only ref PMID 11344134 does not have a hint of any other activity involving aldehydes or ketones.

**Comment by rwst** [comment]
That was a bit cryptic by me. Note the wrong oxidoreductase parent.

**Comment by hdrabkin** [comment]
So I could just remove the GO:0016623 parent?  
The EC 2.1.1.- used at the EAWAG maps to methytransferases so I can change to that if we have it (I'm pretty sure we do). https://www.qmul.ac.uk/sbcs/iubmb/enzyme/EC2/1/1/

**Comment by rwst** [comment]
> So I could just remove the GO:0016623 parent?

Exactly, in my opinion.

**Comment by hdrabkin** [comment]
done
