### ISSUE TITLE
NTR: Regulation of transepithelial transport

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-ontology#17831]
Hi Barbara,
Could you please create this term:
Regulation of transepithelial transport
It would by a child of "Transepithelial transport" (GO:0070633)
The request is for this paper:
PMID: 27593915
Thank you,
Mila

**Comment by milarolo** [comment]
Sorry, I forgot to mention the figure:
Fig: 3

**Comment by BarbaraCzub** [comment]
Hi Mila, of course.
All the best,
Barbara
cc @RLovering
