### ISSUE TITLE
missing colon in EC dbxref in term GO:0015422

### ISSUE THREAD

**Issue by easr** [geneontology/go-ontology#17847]
in the synonym 'ABC-type oligosaccharide transporter', the dbxref is missing a colon:

[Term]
id: GO:0015422
name: ATPase-coupled oligosaccharide transmembrane transporter activity
namespace: molecular_function
alt_id: GO:0015609
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + oligosaccharide(out) = ADP + phosphate + oligosaccharide(in)." [EC:7.5.2.2]
synonym: "ABC-type oligosaccharide transporter" EXACT [EC 7.5.2.2]
...

should be:

[Term]
id: GO:0015422
name: ATPase-coupled oligosaccharide transmembrane transporter activity
namespace: molecular_function
alt_id: GO:0015609
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + oligosaccharide(out) = ADP + phosphate + oligosaccharide(in)." [EC:7.5.2.2]
synonym: "ABC-type oligosaccharide transporter" EXACT [EC:7.5.2.2]
...

**Comment by ukemi** [comment]
This appears to be already fixed in the snapshot and editors' version of the ontology. It should be fixed in the next official release.
