### ISSUE TITLE
remove obsolete EC 2.1.1.125/126 from entries

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17843]
enzyme.dat:
```
ID   2.1.1.125
DE   Transferred entry: 2.1.1.319, 2.1.1.320, 2.1.1.321 and 2.1.1.322.
//
ID   2.1.1.126
DE   Transferred entry: 2.1.1.319, 2.1.1.320, 2.1.1.321 and 2.1.1.322.
```
We still have:
```
id: GO:0016273
name: arginine N-methyltransferase activity
def: "Enables the transfer of a methyl group from S-adenosyl-L-methionine to an amino group of an arginine residue." [GOC:mah]
xref: EC:2.1.1.125
```
also several synonym mappings to [EC:2.1.1.125] and [EC:2.1.1.126], and a comment [EC:2.1.1.125] in a definition

**Comment by hdrabkin** [comment]
I could make each of these entries. Maybe old term can be parent as seems very generic. Then any annotations would need to be transfered to the correct term?

EC 2.1.1.319  RHEA:48096 This eukaryotic enzyme catalyzes the **sequential dimethylation** of one of the terminal guanidino nitrogen atoms in arginine residues, resulting in formation of asymmetric dimethylarginine residues.
EC 2.1.1.320 RHEA:48108 The enzyme catalyzes the methylation of one of the terminal guanidino nitrogen atoms in arginine residues within proteins, forming monomethylarginine, followed by the methylation of the second terminal nitrogen atom to form a symmetrical dimethylarginine. 
EC 2.1.1.321 RHEA:48100 Type III protein arginine methyltransferases catalyze the single methylation of one of the terminal nitrogen atoms of the guanidino group in an L-arginine residue within a protein.  Unlike type I and type II protein arginine methyltransferases, which also catalyze this reaction, type III enzymes do not methylate the substrate any further. 
EC 2.1.1.322  RHEA:48116 methylates the the Delta-nitrogen atom of arginine residues within proteins.

**Comment by rwst** [comment]
Agree! :+1:

**Comment by hdrabkin** [comment]
I would can the RHEA defs directly though

**Comment by hdrabkin** [comment]
Theses terms were  already in GO with different names and more textual definitions but having the EC cross refs.  Adding RHEA to these to fix. (eventual def will come from RHEA). 
Done
