### ISSUE TITLE
NTR: catalase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17848]
Name: catalase complex
Def: A well-conserved peroxidase complex that catalyses the reaction: 2 hydrogen peroxide = O2 + 2 H2O. 

GOCID:bhm

References:
PMID:10656833

Relationships:
is_a GO:1990204 oxidoreductase complex (we don't have a term for peroxidase complex either)
capable_of GO:0004096 catalase activity
capable_of_part_of GO:0042744 hydrogen peroxide catabolic process
capable_of_part_of GO:0061692 cellular detoxification of hydrogen peroxide

[Note to self - editor, please ignore: EBI-22027925]

**Comment by ukemi** [comment]
I noticed that there was a restriction on the oxidoreductase complex that specified it as being a pert of a cell. This was causing lots of complexes that are capable of oxidoreductase activity not being classified under it. I removed that restriction based on the textual def, which says 'Any protein complex that possesses oxidoreductase activity.'
