### ISSUE TITLE
fix EC xref of alpha-glucosidase

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17840]
The problematic EC comes from https://github.com/geneontology/go-ontology/commit/f8fa1db0754867cd7c6d4e4e524ced7ef01e54a9#diff-3cf7b2b4f9db4df4cae7c72388fdba78R446074 by @hdrabkin. Sorry to be so obnoxious :wink: Here the entry is parent to all sorts of alpha-glucosidases which have their own EC so it can't really have this EC, rather 3.2.1.- (broad mapping type). 
```
id: GO:0090599
name: alpha-glucosidase activity
def: "Catalysis of the hydrolysis of terminal, non-reducing alpha-linked alpha-D-glucose residue with release of alpha-D-glucose." [GOC:tb]
xref: EC:3.2.1.20
is_a: GO:0015926 ! glucosidase activity
```

**Comment by rwst** [comment]
@hdrabkin Would it be helpful if I opened pull requests for the more simple issues like these? I'm hesitating since you are assigned to this ticket.

**Comment by hdrabkin** [comment]
No; I need to think more about this.
Specifically, this entry using this def seems valid as a stand alone for the alpha glucosidase.
BUT
3.2.1.- covers a lot other (enzymes hydrolyzing O- and S-glycosyl compounds.) and would actually be a parent to 3.2.1.20 (and is in EC)  however, RHEA does not have a map to this but tdoes to .21 and .19

**Comment by hdrabkin** [comment]
It also looks like several of the 'children'  of GO:0090599 can be considered children and do use the same EC number, but definition points to slightly different substrates (ie, alpha 1-3 vs alpha 1-4)  (and have no separate EC themselves), but others are actually sibs of GO:0090599 in the EC hierarchy (like EC;3.2.1.33

**Comment by rwst** [comment]
> BUT 3.2.1.- covers a lot other (enzymes hydrolyzing O- and S-glycosyl compounds.) and would actually be a parent to 3.2.1.20 

If you would say GO:0090599 is EC 3.2.1.- that does not mean it's an EXACT association. Here the associated EC 3.2.1.- would be BROAD.

**Comment by hdrabkin** [comment]
I am not in favor of having a less than 4 digit EC as an XREF, because they are really grouping terms and not equivalent. So, for example, something could be an is_a to a 3 digit EC, because the 3 digit EC would include all of them.  3 digit ECs are really grouping terms. However,  GO:0090599 looks like a grouping term in it's def because one could group the alpha  alpha 1-3 and alpha 1-4 reactions under them. But the term def as it stands (which comes from EC), IS  GO:0090599. 
GO:0004553 has an XREF to 3.2.1 (but it's def does not inlcude S-glycosyl, only O-glycosyl

**Comment by rwst** [comment]
Then just remove the XREF from GO:0090599?

**Comment by hdrabkin** [comment]
It would still stay as a def ref since that IS the def for the EC.
I was thinking of moving out from under it the things that should be its sibs according to EC; granted ECs mechanistic classification is a little flat

**Comment by rwst** [comment]
With #17892 this could be resolved easily.

**Comment by pgaudet** [comment]
I think the EC xref is correct - EC only has a 4-level hierarchy so some 4-digit terms are children of others, but this cannot e catupred by the EC system.

**Comment by Artoria2e5** [comment]
I do not believe the EC xref is correct. The [expasy page](https://enzyme.expasy.org/EC/3.2.1.20) tells us two reasons why:

* It needs to be 1->4, from the reaction definition.
* It needs to prefer oligosaccharides, from the commentary.

Even if we ignore the second point, the EC is still for 1->4 only.
