### ISSUE TITLE
taxon restrictions "never in fungi"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17857]
Please could you add 
"never in fungi"
to
phage shock 
pilus assembly
adult somatic muscle development
smooth muscle cell differentiation
neuromuscular junction development
myoblast fusion
regulation of myoblast fusion

many thanks

Val

**Comment by ValWood** [comment]
@harryscholes (submitted by)

**Comment by ukemi** [comment]
We could add these, but it seems like a better solution would restrict all but 'phage shock'  in the anatomy ontologies. @balhoff is this a viable option and then inherit them in GO? For example muscle (and all its parts) would never be in fungi.

**Comment by ukemi** [comment]
Maybe better for the muscle anatomy terms to be only_in animalia?

**Comment by balhoff** [comment]
@ukemi I think that should work. Some of this might just be missing axioms in imports. CL already connects 'myoblast' to 'mesoderm' via 'develops from' and 'part of'. Mesoderm is 'only in taxon' 'Eumetazoa'.

**Comment by ukemi** [comment]
I'm adding the pilus assembly and the phage shock terms to the never-in-taxon.txt file. Seems like there should be a better way of doing this than at the level of the individual process terms. @balhoff what do you think is the best course of action, adding these other terms as a stop-gap for now or working to get the restrictions from the anatomy?

**Comment by balhoff** [comment]
We are currently importing from `cl-basic` rather than the full CL. This leaves out 'develops from' axioms connecting these cells to mesoderm. @cmungall do you know the reason for using `cl-basic`?

https://github.com/geneontology/go-ontology/blob/2cb1bdc7ccb8e35b4b4170e7b89cfcdca4a34d25/src/ontology/Makefile#L388

**Comment by ukemi** [comment]
#17883

**Comment by ValWood** [comment]
phage shock should be only in bacteria

Also
GO:0030199 collagen fibril organization (ADD TC never in fungi)  (this term, or a parent, should have multicellular process parent too?)

GO:0030512 negative regulation of transforming growth factor beta receptor signaling pathway. Can this taxon constraint for GO:0007179  transferred onto the regulation terms?

GO:1900136 regulation of cytokine activity
Please add taxon constraint “never in fungi”  to GO:0005125  cytokine activity
and regulation descendants

GO:0034332   adherens junction organization (ADD TC never in fungi)  (this term, or a parent, should have multicellular process parent too?)

GO:0045747  regulation of Notch signaling pathway Please add taxon constraint “never in fungi”  to GO:0007219 Notch signaling pathway and regulation descendants

GO:0018189 pyrroloquinoline quinone biosynthetic process (please ADD TC only in bacteria)

**Comment by ukemi** [comment]
Fixed with #17920
