### ISSUE TITLE
Add EC xref to protein adenylyltransferase activity (GO:0070733)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17854]
[Term]
id: GO:0070733
name: protein adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + protein = diphosphate + adenylyl-protein; mediates the addition of an adenylyl (adenosine 5'-monophosphate; AMP group) to specific residues of target proteins." [GOC:mah, PMID:19039103, PMID:19362538]

Matches EC 2.7.7.n1:
https://enzyme.expasy.org/EC/2.7.7.n1

**Comment by hdrabkin** [comment]
A while ago some at EC has told me EC 2.7.7.n1: is not an official number. It just indicates that someone has made a request. I was told NOT to use any .n1, etc. as an Xref.
However, I need to contact them on this one because it has two reactions associated with it.

**Comment by hdrabkin** [comment]
What is interesting is that RHEA actually has this and makes separate reactions
RHEA:54292 (APPROVED)
ATP + L-threonyl-[protein] = 3-O-(5'-adenylyl)-L-threonyl-[protein] + diphosphate 
RHEA:54288          (APPROVED)
ATP + L-tyrosyl-[protein] = diphosphate + O-(5'-adenylyl)-L-tyrosyl-[protein] 

So I suppose I should make the two children to this term with the appropriate amino acid target, and then have annotations moved depending upon the substrate used.

**Comment by sjm41** [comment]
Re. not using the 'unofficial' EC refs, I see two cases where these are already used - should they be removed?

id: GO:0052849
name: NADPH-dependent curcumin reductase activity
xref: EC:1.3.1.n3

id: GO:0090409
name: malonyl-CoA synthetase activity
xref: EC:6.2.1.n3

**Comment by hdrabkin** [comment]
Once I get confirmation from EC I would do that. What took me by surprise is RHEA using them. I need to inquire on the status of the x.x.x.n's

**Comment by hdrabkin** [comment]
And I have NO idea what makes an 'n1' vs 'n3" in these naming schemes.

**Comment by hdrabkin** [comment]
Fired off the questions; I found the old email and I was told "These letters cannot be used. They are only internal place holders until the entries go to review." 
My asking about them might get them fast-tracked though.

**Comment by sjm41** [comment]
OK, thanks.  We will see....  I'm also unclear what the turnaround time might be in changing an internal ID to an official one.  (Actually, if they really are 'internal', why are they available on the public website at all...?)

**Comment by hdrabkin** [comment]
Lol; I have the exact same questions!

**Comment by hdrabkin** [comment]
So today:
"EC numbers including an 'n' as part of the serial digit are preliminary EC numbers, i.e. EC numbers describing well characterized enzymes that SIB have corrected while waiting for them to be integrated in the EC list. We did that during a period when we (I) was not involved in the IUBMB nomenclature work, and where waiting times for new EC numbers were even longer than they are now.

1. Yes, these preliminary EC numbers are stable
2. RHEA can use
3. They stay with the 'n' until (if ever) they are included in the EC list and thus a complete EC number is created for them. At that point they will be transferred in our list (the ENZYME database) so they will not simply disappear.
4. The only difference between an n1 and an n3 is that they are separate enzymes. "

So, we can use; so will do this for  you and close

**Comment by sjm41** [comment]
OK, that's a clear reply. Thanks for adding.
