### ISSUE TITLE
Inconsistent relationships for EC:2.7.7.72-related GO terms 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17855]
The following terms are related by having the same EC xref, but their relationships within the GO are implemented inconsistently - maybe that's intentional, but I don't think so?

[Term]
id: GO:0052927
name: CTP:tRNA cytidylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate." [KEGG_REACTION:R09383]
xref: EC:2.7.7.72
xref: KEGG_REACTION:R09383
is_a: GO:0016779 ! nucleotidyltransferase activity
is_a: GO:0140101 ! catalytic activity, acting on a tRNA

[Term]
id: GO:0052928
name: CTP:3'-cytidine-tRNA cytidylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: a tRNA with a 3' cytidine + CTP = a tRNA with a 3' CC end + diphosphate." [KEGG_REACTION:R09384]
xref: EC:2.7.7.72
xref: KEGG_REACTION:R09384
is_a: GO:0016779 ! nucleotidyltransferase activity
is_a: GO:0140101 ! catalytic activity, acting on a tRNA

[Term]
id: GO:0052929
name: ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: a tRNA with a 3' CC end + ATP = a tRNA with a 3' CCA end + diphosphate." [KEGG_REACTION:R09386]
synonym: "ATP:3'-CC-tRNA adenylyltransferase activity" EXACT []
synonym: "ATP:tRNA adenylyltransferase activity" BROAD []
xref: EC:2.7.7.72
xref: KEGG_REACTION:R09386
is_a: GO:0004810 ! tRNA adenylyltransferase activity

For the first two, suggest replace:
is_a: GO:0016779 ! nucleotidyltransferase activity
with:
is_a: GO:0016437 ! tRNA cytidylyltransferase activity

For the last one, suggest add:
is_a: GO:0140101 ! catalytic activity, acting on a tRNA

![Screen Shot 2019-09-18 at 13 18 32](https://user-images.githubusercontent.com/16306861/65148449-1d783c00-da18-11e9-8064-a6ab1657dc1f.png)

**Comment by hdrabkin** [comment]
I need to fix these; I know. Specifically, the EC id refers to the tRNA CCA enzyme, which can add C or A depending. However, we need to take account of certain organisms where the "CC" and the A are added by different activities.

**Comment by hdrabkin** [comment]
So note here that EC:2.7.7.72 has only 1 RHEA even though people DO sometimes merely assay for the addition of A to 3' end of tRNA (but the other two additions have to happen before this can happen)

**Comment by sjm41** [comment]
@hdrabkin The issues originally reported here have largely been fixed in https://github.com/geneontology/go-ontology/issues/19854.

Only one thing remaining: add "is_a: GO:0140101 ! catalytic activity, acting on a tRNA" to this term:

id: GO:0052929
name: ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: a tRNA with a 3' CC end + ATP = a tRNA with a 3' CCA end + diphosphate." [PMID:31936900, PMID:33095240, RHEA:60012]
synonym: "ATP:3'-CC-tRNA adenylyltransferase activity" EXACT []
synonym: "ATP:tRNA adenylyltransferase activity" BROAD []
xref: KEGG_REACTION:R09386
xref: RHEA:60012
is_a: GO:0070566 ! adenylyltransferase activity

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks!
