### ISSUE TITLE
Add EC xref to tRNA guanylyltransferase activity (GO:0008193)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17853]
[Term]
id: GO:0008193
name: tRNA guanylyltransferase activity
namespace: molecular_function
def: "Catalysis of the posttranscriptional addition of a guanyl residue to the 5' end of a tRNA molecule; observed for His tRNAs." [PMID:1660461]

I think we can add EC 2.7.7.79 as an xref here?
https://enzyme.expasy.org/EC/2.7.7.79

**Comment by hdrabkin** [comment]
yep

**Comment by hdrabkin** [comment]
RHEA:54564 is also added now.

**Comment by sjm41** [comment]
Thanks Harold!
