### ISSUE TITLE
Issue with generation of some old TermGenie synonyms?

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#17865]
Hi, 

I noticed that 
GO:1903449 androst-4-ene-3,17-dione biosynthetic process 
has the exact synonym "androstenedione", which is incorrect (incomplete). I found that weird, knowing that GO:19XXXXX terms were automatically generated by TermGenie. The issue propagated to the 3 regulation terms of GO:1903449, so you may want to remove the incomplete/incorrect synonyms of all 4 terms. Not sure if the originating incomplete synonym was added manually (unlikely). I haven't easily found other examples of terms with similarly complex labels as GO:1903449 AND generated via TermGenie, so I'm not sure if it was a bug.

Thanks,
Paola

**Comment by ukemi** [comment]
Thanks for the heads up @paolaroncaglia !

**Comment by ukemi** [comment]
It looks like it might have been a manual mistake because it doesn't have the TG xref. I'll fix it.

**Comment by paolaroncaglia** [comment]
Thank you @ukemi .
