### ISSUE TITLE
"pyruvate kinase activity" should be child of "kinase activity"?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17864]
Shouldn't "pyruvate kinase activity" (GO:0004743) be a child of "kinase activity" (GO:0016301)?
(This is in addition to being a child of "phosphotransferase activity, alcohol group as acceptor" (GO:0016773).)

I see from the change log that its relationship to kinase activity was deleted in 2015-07-22, but I don't see why.

GO def is is "**Catalysis of the reaction: ATP + pyruvate = ADP + phosphoenolpyruvate.**"
Rhea entry is here: https://www.rhea-db.org/reaction.xhtml?id=18157
Both theses appear to satisfy the GO definition of "kinase activity" (= "Catalysis of the transfer of a phosphate group, usually from ATP, to a substrate molecule.")

**Comment by sjm41** [comment]
Tagging @hattrill

**Comment by ukemi** [comment]
No, it never works in the kinase direction. It can be assayed that way, but physiologically always works in the reverse. I think we should modify the def.  

Sanity check @deustp01.

**Comment by ukemi** [comment]
PS. I thought we had fixed this during the glycolysis project.

**Comment by deustp01** [comment]
Locally this is a sore point. In previous years that is what we taught the medical students. The old crusty lecturer got deposed and now we teach them some sort of inconclusive fuzz. But in GO and Reactome and reality it remains physiologically irreversible. (There are other textbook irreversible reactions that actually can be reversed under some normal conditions but as far as I know this is not one of them.)

**Comment by ukemi** [comment]
Thanks @deustp01! I will modify the def and the Rhea xref to be the unidirectional reaction. Always good to have a biochemistry professor to back me up.

**Comment by sjm41** [comment]
Ah, I see - thanks both!
Modifying the def and the Rhea xref will be good.
Should we modify the term name too?  "pyruvate kinase activity" kinda suggests that proteins annotated with this term do act in the kinase direction....

**Comment by ukemi** [comment]
Unfortunately I think modifying the term name would lead to a lot of confusion. It's pretty universal that 'the last step in glycolysis is catalyzed by pyruvate kinase', even though it's backwards.

**Comment by sjm41** [comment]
OK, understood.
