### ISSUE TITLE
NTR: N6-mAMP deaminase activity

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#17873]
Enzymatic activity reported here: https://www.ncbi.nlm.nih.gov/pubmed/?term=10.1105%2Ftpc.18.00236

name: N6-mAMP deaminase activity
definition: Catalysis of the reaction: H+ + H2O + N6-methyl-AMP = IMP + methylamine
ref: PMID:29884623
synonym: (exact) MAPDA
After I couldn't find it in EC or Metacyc, I requested addition to RHEA through their tracker and they added this reaction: RHEA:16001
(It will become publicly available at the release 2019_10 scheduled
for November 13.)

**Comment by ukemi** [comment]
@deustp01 this looks like R-HSA-2161187. May want to add an xref for the next Reactome release.
It's in the purine salvage pathway. I'm making it a direct child of deaminase activity.

**Comment by hdrabkin** [comment]
RHEA added removing tag
