### ISSUE TITLE
Mitochondrial potassium channel

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17876]
Hi GO,

I would need a bunch of terms for a long sought mitochondrial potassium channel described in PMID:31435016

1)
Mitochondrial potassium channel activity
Category function
Definition:
Enables the ATP-dependent diffusion of a potassium ion across the mitochondrial inner membrane.
child of GO:0005267; F:potassium channel activity
Xref: PMID:31435016;

2)
Mitochondrial potassium channel complex 
child of GO:0034705 potassium channel complex 
Category: Component
Definition: The Mitochondrial potassium channel (MITOK) is composed of the channel subunit (CCDC51/MITOK) and the ATP-binding subunit (ABCB8/MITOSUR).
Xref: PMID:31435016;

**Comment by ukemi** [comment]
Hi Sylvain. I'm trying to be clever and define these logically. It looks good to me, but let me know if you think anything looks out of place.

-David
