### ISSUE TITLE
nonexisting ECs in two activities

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17875]
Rhea doesn't know these reactions. BRENDA gives this as EC but the B suggests it's their placement. So maybe call it xref: BRENDA:2.7.1.B19 ?

https://www.brenda-enzymes.org/enzyme.php?ecno=2.7.1.B19
https://www.brenda-enzymes.org/enzyme.php?ecno=3.5.1.B4
```
id: GO:0052671
name: geranylgeraniol kinase activity
def: "Catalysis of the reaction: geranylgeraniol + nucleoside triphosphate = all-trans-geranyl-geranyl monophosphate + nucleoside diphosphate." [GOC:kd, MetaCyc:RXN-11629]
synonym: "geranylgeraniol phosphotransferase activity" EXACT []
xref: EC:2.7.1.B19

id: GO:0043909
name: N-acetylcitrulline deacetylase activity
namespace: molecular_function
def: "Catalysis of the reaction: N-acetyl-L-citrulline + H2O = citrulline + acet
ate." [GOC:jl, IMG:02799, PMID:16750290]
synonym: "acetylcitrulline deacetylase activity" EXACT []
synonym: "N-acetyl-L-citrulline deacetylase activity" EXACT []
xref: EC:3.5.1.B4
xref: IMG:02799
```

**Comment by hdrabkin** [comment]
Let me ask Kristian.

**Comment by hdrabkin** [comment]
I just received this from Kristian
"You have touched one of the peculiar things about preliminary EC numbers. The thing is that there is no coordination of assigning these numbers, so Brenda, MetaCyc and ENZYME each create their own and assign their own preliminary numbers, Brenda using B, MetaCyc M and ENZYME n as part of the serial (fourth) digit. 

So if you are interested in a Rhea reaction linked to a MetaCyc or Brenda preliminary EC number you should submit a reaction request so we can create such a reaction. We have no plans of including the preliminary EC numbers from MetaCyc and Brenda in ENZYME. We actually don't add any new preliminary EC numbers to ENZYME. We either make a submission to the EC list or we create a Rhea reaction and stay with that."

**Comment by hdrabkin** [comment]
SO
A BRENDA link will work to take it to Brenda.
But do we want to???

**Comment by hdrabkin** [comment]
I AM requesting RHEA entries.

**Comment by hdrabkin** [comment]
One of the children of GO:0052671 has a proper EC (ATP substrate). The other with CTP substrate does not; requesting RHEA for it.

**Comment by hdrabkin** [comment]
RHEA:61092 (not released yet) for GO:0043909
H2O + N2-acetyl-L-citrulline = acetate + L-citrulline

**Comment by hdrabkin** [comment]
RHEA:61092 |  now public; adding to GO:0043909; removed EC

**Comment by hdrabkin** [comment]
GO:0102243 
RHEA:61660  
ATP + geraniol = (2E)-geranyl phosphate + ADP + H(+) 
mapped to EC:2.7.1.216

**Comment by hdrabkin** [comment]
I added these in March,  but forgot to close
