### ISSUE TITLE
new term request "smooth spongiome"

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#17880]
I have a new term request "smooth spongiome", ec 3.1.4.11.
Def.: Wikipedia: "The contractile vacuole has several structures attached to it in most cells, such as membrane folds, tubules, water tracts and small vesicles. These structures have been termed the spongiome; the contractile vacuole together with the spongiome is sometimes called the "contractile vacuole complex (CVC). The spongiome serves several functions in water transport into the contractile vacuole and in localization and docking of the contractile vacuole within the cell."

--

**Comment by ukemi** [comment]
There is a nice study here: PMID:23890380
From this paper it looks like it should be spongiome. We probably should add contractile vacuole complex as a non-membrane bounded organelle and then have the spongiome and the current contractile vacuole (a cytoplasmic vesicle)  cellular anatomical structures that are parts of the CVC.
