### ISSUE TITLE
Please revise: GO:0075251 'uredospore formation' is_a 'biosynthetic process'

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#17886]
Hi,
GO:0075251 'uredospore formation'
is currently a subclass of 
GO:0043936 asexual sporulation resulting in formation of a cellular spore
and
GO:0009058 biosynthetic process
(http://amigo.geneontology.org/amigo/term/GO:0075251, https://www.ebi.ac.uk/QuickGO/term/GO:0075251).
I suggest to delete the latter please. May have been a mistake as part of the obsoletion of 'single-organism biosynthetic process' (see Change Log in the QuickGO link above).
Thanks,
Paola

**Comment by ukemi** [comment]
I will clean up the others too.
