### ISSUE TITLE
Merge 'acquisition by symbiont of nutrients from host via siderophores' into 'iron acquisition by symbiont from host'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17896]
Merge 'GO:0052099 acquisition by symbiont of nutrients from host via siderophores' (2 annotations)
'GO:0044847 iron acquisition by symbiont from host' (0 annotations)
since siderophores transport iron, there is no difference between those 2 terms. 

Pascale

**Comment by ValWood** [comment]
You probably spotted but existing


iron acquisition by symbiont from host heme | broad

should be narrow
