### ISSUE TITLE
Obsolete 'GO:0051850 acquisition of nutrients from symbiont' and children ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17899]
Hello, 

I think those terms were created to mirror the symbiont processes: 

 - GO:0051850 acquisition of nutrients from symbiont
 -- GO:0052098 formation by host of specialized structure for nutrient acquisition from symbiont
 --  GO:0052460 modulation by host of nutrient release from symbiont 
 --- GO:0052520 positive regulation by organism of nutrient release from other organism involved in symbiotic interaction
--- GO:0052519 positive regulation by host of nutrient release from symbiont 

There are no annotations or mappings for any of these terms. 

@mgiglio99 @ValWood would you be OK with obsoleting those ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Actually, I wonder if there is evidence for the existence of the entire branch ? 
'modulation of nutrient release from other organism involved in symbiotic interaction' and children - no annotations, no references in any of the terms. 

Anyone has examples of this process ? 

Thanks, Pascale

**Comment by mgiglio99** [comment]
I think these terms are exactly what happens in lichen.
The fungal partner in a lichen causes the symbiont algae or cyanobacteria to leak out the sugars they produce by photosynthesis which become a food source for the fungus.

**Comment by ukemi** [comment]
lichen?

**Comment by ukemi** [comment]
termites?

**Comment by pgaudet** [comment]
OK, I'll add a precision for the lichen example. 

Is GO:0052098 formation by host of specialized structure for nutrient acquisition from symbiont
relevant to termites ?

**Comment by mgiglio99** [comment]
There are arbuscular mycorrhizal fungi which form structures called appressoria on plant roots where there is an exchange of nutrients between the plant and fungus.
And some lichen fungi have structures for getting nutrients from their photosynthetic partners.

will check on termites.

**Comment by ukemi** [comment]
I don't think that is the case for termites, but I thought you were proposing to get rid of the whole branch.

**Comment by pgaudet** [comment]
In this case the fungus is the symbiont, right ? I was wondering which host form these structures.

**Comment by mgiglio99** [comment]
Not sure how I forgot to mention this one - humans gain nutrients from their gut microbiomes both in terms of vitamins synthesized by the bacteria and through things that can be digested by bacteria but not us.
No specialized structures that I know of though.

**Comment by pgaudet** [comment]
Right but there are no precise mechanisms to specifically acquire nutrients from the microbes in the gut - it's just transported as any other metabolite, isn't it ?

**Comment by mgiglio99** [comment]
As far as I know.
But there are some structures formed for this with the lichens. Where the fungus makes a haustoria structure (similar to that used by pathogenic fungi) to get nutrients out of the algae.

**Comment by ukemi** [comment]
Perhaps read PMID:19278554.

**Comment by mgiglio99** [comment]
That paper seems to mostly talk about the mechanisms in terms of getting nutrients from hosts, but several of the examples in the paper actually involve nutrients going in both directions to host and to symbiont along with associated structures - like the arbuscular mycorrhizal fungi and the appressoria, and the modified haustoria in the lichens. In the first case it is the symbiont making the structure that both host and symbiont benefit from, but in the second case (lichen) it is the fungus making the structure, which I think people would probably consider the "host" since its the bigger species in the partnership.

**Comment by ValWood** [comment]
I just wanted tosymbont  throw in that today I noticed that

GO:0036377    arbuscular mycorrhizal association
A form of mutualism between a fungus and the roots of a vascular plant, where hyphae of the fungus penetrate the plant cell wall and invaginate its cell membrane. Once inside, the fungus forms highly branched structures for nutrient exchange with the plant called arbuscules. Aids in the acquisition by the plant of nutrients such as phosphorus from the soil.

is directly under "symbiotic process" and not under  "interaction with host" or "interaction with symbiont.

So we either want to 
a) reclassify this term, or 
b) make all such terms host/symbiont agnostic

**Comment by mgiglio99** [comment]
Summing up what I think we've decided:
We'll keep GO:0051850 'acquisition of nutrients from symbiont' and children.
Correct?

Val - should there be a new issue for GO:0036377 'arbuscular mycorrhizal association' parentage?

**Comment by ValWood** [comment]
Probably but I'm not sure how I would use 
 'arbuscular mycorrhizal association' in annotation. It seems to be describing an entire lifestyle?

Does it mean ''acquisition of nutrients by arbuscular mycorrhizal association'
