### ISSUE TITLE
rename GO:0052067 negative regulation by symbiont of entry into host cell via phagocytosis to "phagocytosis avoidence or antiphagocytosis"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17893]
AND remove "entry into host" parentage

GO:0052067 negative regulation by symbiont of entry into host cell via phagocytosis

Defined
Any process in which an organism stops or prevents itself undergoing phagocytosis into a cell in the host organism.

and
GO:0052380 modulation by symbiont of entry into host via phagocytosis

 This isn't  "entry into host"  as defined by GO
and should not have this phrase in the term name or  parent.

GO:0044409 entry into host
Definition (GO:0044409)
Penetration by a symbiont into the body, tissues, or cells of a host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

This is more about the lifecycle process of entering the host to colonize it.

However the annotations to
GO:0052067 negative regulation by symbiont of entry into host cell via phagocytosis
are more about engulfment by macrophages in destruction of the pathogen.

(this also fits with the other parentages of this term which are about immune evasion)

**Comment by ValWood** [comment]
phagocytosis is ingestion by host not desired by pathogen
entry into host is defined Penetration by a symbiont into... desired by pathogen/symbiont

Suggest renaming

"Antiphagocytosis" to clarify.

**Comment by ValWood** [comment]
Is GO:0052380 modulation by symbiont of entry into host via phagocytosis
even required?
It seems that this is just a parent for the negative regulation term?

**Comment by mah11** [comment]
> phagocytosis is ingestion by host not desired by pathogen
> entry into host is defined Penetration by a symbiont into... desired by pathogen/symbiont

I would not try to argue that the current term names are necessarily ideal, but I suspect that GO:0052380 is meant to represent entry into a host by a symbiont that co-opts the host phagocytic machinery. For those symbionts, phagocytic ingestion is "desired", and "entry into host" ancestry does make sense.

I've only skimmed part of this review, but it looks pretty comprehensive:
https://www.sciencedirect.com/science/article/pii/S1931312812003083

I agree that GO:0052067 is at best ambiguous, and could refer to (different) symbionts that evade host phagocytosis rather than subvert it.

**Comment by ValWood** [comment]
@ukemi  I stole this from @hdrabkin  and assigned to @pgaudet  as we are adressign related terms

**Comment by hdrabkin** [comment]
@ValWood by all means!

**Comment by ValWood** [comment]
Actions

- [ ] . Rename GO:0052067 
negative regulation by symbiont of entry into host cell via phagocytosis to

"antiphagocytosis" 
synonym "phagocytosis avoidence" 

This fits the definition
Defined
Any process in which an organism stops or prevents itself undergoing phagocytosis into a cell in the host organism.

and the exisitng 5 annotations.

 - [ ] Remove the parent "entry into host" from this term

**Comment by ValWood** [comment]
I got too confused so I made a new ticket

https://github.com/geneontology/go-ontology/issues/17983
