### ISSUE TITLE
Consistency in labels of (cellular) metabolic processes

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#17904]
Hi,
Not sure if there's already an ongoing discussion on this.
GO differentiates between
GO:0008152 metabolic process (The chemical reactions and pathways, including anabolism and catabolism, by which _living organisms_ transform chemical substances.)
and its child
GO:0044237 cellular metabolic process (The chemical reactions and pathways by which _individual cells_ transform chemical substances.).
However, not all descendants of 'cellular metabolic process' contain 'cellular' in their label (though some do in their exact synonyms). See e.g. the Ancestor chart in https://www.ebi.ac.uk/QuickGO/term/GO:0006593 where alpha amino acid metabolic process, alpha amino acid catabolic process, ornithine metabolic process and ornithine catabolic process don't contain 'cellular' in their label. There is 'cellular amino acid metabolic process' but no 'amino acid metabolic process'. Ultimately, amino acids are synthesized at the level of a single cell, so I get why 'amino acid metabolic process' is less useful. But then you have 
'negative regulation of ornithine catabolic process' 
is a subclass of 
'negative regulation of _cellular_ amino acid metabolic process'
The ancestry shows that 'negative regulation of ornithine catabolic process' refers to the single-cell process, but the name doesn't, and the parentage to a 'cellular' term may seem incorrect at first glance. Being more consistent with including 'cellular' in labels (or not) would help.
Thanks,
Paola

**Comment by pgaudet** [comment]
We want to merge all those. 
Maybe to discuss on an ontology call for the strategy? 
Should we drop the 'cellular' terms (since this is implied) ? 

Thanks, Pascale

**Comment by ukemi** [comment]
If we have decided to merge these, then I suggest that they be merged in the non-cellular direction. The result will be that there will not be a direct link to cellular process in the ontology.

**Comment by cmungall** [comment]
My proposal makes metabolic process a subclass of cellular process. https://gist.github.com/cmungall/4ed28123c3db832a7d99cbdd8e8a5920

I think the use case for CP is a grouping for things at a level of granularity

**Comment by ukemi** [comment]
But if you ask an endocrinologist to describe glucose metabolism, I suspect they will talk about it at a system and organismal level.

**Comment by pgaudet** [comment]
- [x] GO:0006520 ~cellular~ amino acid metabolic process
- [x] GO:0008652 ~cellular~ amino acid biosynthetic process
- [x] GO:0009063 ~cellular~ amino acid catabolic process
- [x] GO:0009072 aromatic amino acid ~family~ metabolic process

**Comment by pgaudet** [comment]
Obsolete with replaced by: 

- [x] GO:0044260 cellular macromolecule metabolic process  >> GO:0043170 macromolecule metabolic process
- [x] GO:0044265 cellular macromolecule catabolic process  >>  GO:0009057 macromolecule catabolic process
- [x]  GO:0034645 cellular macromolecule biosynthetic process   >> GO:0009059 macromolecule biosynthetic process
- [x] GO:2000112 regulation of cellular macromolecule biosynthetic process >> GO:0010556 regulation of macromolecule biosynthetic process
- [x] GO:0010558 negative regulation of macromolecule biosynthetic process >> GO:2000113 negative regulation of cellular macromolecule biosynthetic process


Obsolete, unnecessary grouping class: 
- [x] GO:0070589 cellular component macromolecule biosynthetic process (no annotations, no mappings, not in subsets)

**Comment by pgaudet** [comment]
- [ ] GO:0044262 cellular carbohydrate metabolic process >>  GO:0005975 carbohydrate metabolic process
- [ ] GO:0034637 cellular carbohydrate biosynthetic process >> GO:0016051 carbohydrate biosynthetic process
- [ ] GO:0044275 cellular carbohydrate catabolic process >> GO:0016052 carbohydrate catabolic process
- [ ] GO:0010675 regulation of cellular carbohydrate metabolic process >> GO:0006109 regulation of carbohydrate metabolic process
- [ ] GO:0010676 positive regulation of cellular carbohydrate metabolic process >> GO:0045913 positive regulation of carbohydrate metabolic process 
- [ ] GO:0043471 regulation of cellular carbohydrate catabolic process >> GO:0045912 negative regulation of carbohydrate metabolic process

**Comment by pgaudet** [comment]
- [ ] GO:0044264 cellular polysaccharide metabolic process >> GO:0005976 polysaccharide metabolic process
- [ ] GO:0033692 cellular polysaccharide biosynthetic process >>  GO:0000271 polysaccharide biosynthetic process
- [ ] GO:0044247 cellular polysaccharide catabolic process  >> GO:0000272 polysaccharide catabolic process

**Comment by pgaudet** [comment]
- [ ] GO:0006073 cellular glucan metabolic process  >> GO:0044042 glucan metabolic process

**Comment by pgaudet** [comment]
Still need to look at: (list not exhaustive): 

- [ ] GO:0044107 cellular alcohol metabolic process
- [ ] GO:0006081 cellular aldehyde metabolic process
- [ ] GO:0043446 cellular alkane metabolic process
- [ ] GO:0043449 cellular alkene metabolic process
- [ ] GO:0043452 cellular alkyne metabolic process
- [ ] GO:0006725 cellular aromatic compound metabolic process
- [ ] GO:0046950 cellular ketone body metabolic process
- [ ] GO:0042180 cellular ketone metabolic process
- [ ] GO:0044255 cellular lipid metabolic process
- [ ] GO:0044260 cellular macromolecule metabolic process
- [ ] GO:0043094 cellular metabolic compound salvage
- [ ] GO:0006575 cellular modified amino acid metabolic process
- [ ] GO:0034641 cellular nitrogen compound metabolic process
- [ ] GO:0090345 cellular organohalogen metabolic process

**Comment by pgaudet** [comment]
Work will be continued here: 
https://github.com/geneontology/go-ontology/issues/28908
