### ISSUE TITLE
Evasion of host defense reponse - merges

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17906]
Hello, 

I propose to merge the following terms: 

**GO:0051834 evasion or tolerance of defenses of other organism involved in symbiotic interaction:** 
Any process, either active or passive, by which an organism avoids or tolerates the effects of a second organism's defense(s), where the two organisms are in a symbiotic interaction. Defenses may be induced by the presence of the organism or may be preformed (e.g. physical barriers).

3 EXP annotations to Candida (single paper) -> OK to move

**GO:0051807 evasion or tolerance of defense response of other organism involved in symbiotic interaction:** 
Any process, either active or passive, by which an organism avoids or tolerates the effects of a second organism's defense response; the defense response is mounted by the second organism in response to the presence of the first organism, where the two organisms are in a symbiotic interaction.

0 annotations

**GO:0044415 'evasion or tolerance of host defenses':** 
Any process, either active or passive, by which an organism avoids or tolerates the effects of its host organism's defense(s). Host defenses may be induced by the presence of the organism or may be preformed (e.g. physical barriers). The host is defined as the larger of the organisms involved in a symbiotic interaction.

3 EXP UniProt - bacteria

**Merge into GO:0030682 evasion or tolerance of host defense response:** 
Any process, either active or passive, by which an organism avoids or tolerates the effects of its host organism's defense response. The host defense response is mounted by the host in response to the presence of the organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

2 EXP annotations + InterPro mapping

@mgiglio99 @ValWood what do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Could we also merge GO:0044413 avoidance of host defenses ? 
4 annotations

**Comment by ValWood** [comment]
Blimey yes, no wonder this branch is confusing...merge, merge, merge...

**Comment by ValWood** [comment]
I guess when you do these merges, child terms like
modulation by symbiont of host immune response' GO:0052553
will also merge intot he appropriate children?
this will deal with  #17441

**Comment by pgaudet** [comment]
Right I was looking into these too.

**Comment by ValWood** [comment]
so the term 

GO:0052553 | modulation by symbiont of host immune response
would end up a child of , or merged into

GO:0020012 | evasion or tolerance of host immune response


![merges](https://user-images.githubusercontent.com/7359272/65616000-33ef3c00-dfb2-11e9-90af-ff5e4eb4931b.jpg)

I guess modulation is always  evasion and not tolerance?

It's a shame that the same processes are described differently, sometimes by the outcome (evasion, tolerance), and sometimes by what is done to the host (modulation of the immune system).

It will be difficult to normalize these without loss of  information....some assumptions would need to be made.

One idea from the PHI-base team was to say "manipulation of the host immune system"
I don't know if that will be useful here.

**Comment by pgaudet** [comment]
manipulation sounds like modulation to me - we can add synonyms if needed?

**Comment by ValWood** [comment]
> Could we also merge GO:0044413 avoidance of host defenses ?

Yes because this is a parent of "avoidance or tolerence", which is  broader, so it is just wrong!

**Comment by ValWood** [comment]
> manipulation sounds like modulation to me - we can add synonyms if needed?

I guess it does.

I was thinking that manipulation covered tolerance or  evasion and modification/modulation

but if you think you can do merges without altering the meanings I would keep it as it is.

**Comment by mgiglio99** [comment]
In principle, I'm fine with these merges. However, one distinction to track is that between "defenses" and "defense response". Not all defenses are a response. So, maybe do the merges into GO:0044415 'evasion or tolerance of host defenses' (rather than GO:0030682 'evasion or tolerance of host defense response').

Also, I'm confused about what will happen to the 'modulation...' terms - are they part of this merge too? Or will they be separate?

**Comment by pgaudet** [comment]
@mgiglio99 Modulation is separate - @ValWood we should be careful not to mix up too many discussions, it gets too confusing to know what is done afterwards.

**Comment by pgaudet** [comment]
@mgiglio99 what is the difference between defense and defense response ? I cannot find 'defense' in the non-multispecies part of the ontology, and the definitions do not make that clear. 

There is a single 'correct' annotation to 'evasion or tolerance of host defenses by virus' to a viral protein (Q2V8W4, based on PMID:17804495) (and 2 others to human proteins, which are likely incorrect). Q2V8W4 looks like it binds a receptor on the host, so I am not sure this is the best annotation. 

What do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note to self: local branch name: issue-merge_defense_responses

**Comment by ValWood** [comment]
>@ValWood we should be careful not to mix up too many discussions, it gets too confusing to know what is done afterwards.

OK, I thought that was in one of the branches you were merging.

I was thinking about this branch some more (One of) the fundamental issues is the naming and definition/use of

"evasion or tolerance". 

This phrasing It isn't really helpful with respect to specific biological processes. A symbiont can tolerate OR evade  the immune system by "hiding" OR "defending". 

The current definiton is *totally* circular (it just substitutes avoids for evades):
Any process, either active or passive, by which an organism avoids or tolerates the effects of its host organism's defense(s). Host defenses may be induced by the presence of the organism or may be preformed (e.g. physical barriers). The host is defined as the larger of the organisms involved in a symbiotic interaction.


We need to be much clearer here exactly which concepts are included. even after the merges it isn't really clear. But beginning from immune evasion, and defining more clearly would seem to help.

It might be better to get rid of "tolerance' which seems too wooly, in favour of just

Immune evasion (which from googling appears to include both hiding and defending?)
Mechanisms by which an organisms can hide itself from the host to prevent recognition bythe host, or defend against the host by altering the host immune system.
(with better biological phrasing, but I would know which strategies were included under this term).

It would be good to know the history of the inclusion of "tolerance". Which processes was the inclusion required for? @mgiglio99  can you remember? Am I overlooking something?

**Comment by ValWood** [comment]
google top def
Immune evasion strategies are those bacterial pathogens use to avoid or inactivate host defenses and ensure their own survival within a host.

**Comment by addiehl** [comment]
See my response to #17894 in regards to the difference between evasion and tolerance and an literature example of tolerance that specifically uses the word tolerance.

**Comment by mgiglio99** [comment]
> what is the difference between defense and defense response ? I cannot find 'defense' in the non-multispecies part of the ontology, and the definitions do not make that clear.

Defenses can be pre-existing things like structures or constantly circulating molecules or an environment maintained to be hostile to microbes (like low iron levels). A defense response requires the host to detect the symbiont and then take some kind of action. It is one kind of defense.
