### ISSUE TITLE
Obsolete children of GO:0052201 response to symbiont defenses' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17907]
Hello, 

We currently have this structure under 'modulation by organism of defense response of other organism involved in symbiotic interaction' : 

'GO:0052201 response to symbiont defenses' and children: 
- 'GO:0052181 modulation by host of symbiont defense response'
- 'GO:0052197 positive regulation by host of symbiont defense response'
- 'GO:0052393 induction by host of symbiont defense response'

I suppose the 'response to symbiont defenses' may exist; however I don't think 'modulation by host of symbiont defense response' and children are not actual host processes, this is the equivalent of effectors, on the host side. I propose to obsolete 
- 'GO:0052181 modulation by host of symbiont defense response'
- 'GO:0052197 positive regulation by host of symbiont defense response'
- 'GO:0052393 induction by host of symbiont defense response'

and figure out host effectors as we encounter them, unless someone already has examples ? 

@mgiglio99 @ValWood 
Thanks, Pascale

**Comment by ValWood** [comment]
I would get rid of any of these that have not been used until we have examples (unlikely)?

**Comment by mgiglio99** [comment]
I agree.

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete the following terms: 
'GO:0052181 modulation by host of symbiont defense response'
'GO:0052197 positive regulation by host of symbiont defense response'
'GO:0052393 induction by host of symbiont defense response'
The reason for obsoletion is that there is no evidence that the host can modulate or regulate a symbiont’s defense response. There are no annotations or mapping to these terms. Those terms are not in any subsets. 



Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/17907

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 30th. Unless objections are received by September 30th, we will assume that you agree to this change.

Thanks, Pascale

**Comment by genegodbold** [comment]
Not that my experience is dispositive, but I have *never* seen a molecular mechanism for how a host would manipulate the defense response of a symbiont. Plenty the other way, of course.
