### ISSUE TITLE
add bridging axioms for ZFA, DGA and other anatomy ontologies used in GO-CAMs

### ISSUE THREAD

**Issue by goodb** [geneontology/go-ontology#17914]
In the integrated ontology called go-lego.owl that is used to build GO-CAMs, all anatomy terms should be linked under the common parent term http://purl.obolibrary.org/obo/CARO_0000000 .  This is necessary for schema validation, see: https://github.com/geneontology/go-shapes/pull/160

For example: http://purl.obolibrary.org/obo/ZFA_0009019 and http://purl.obolibrary.org/obo/FBbt_00100504

**Comment by balhoff** [comment]
I added bridges to CARO for DDANAT, EMAPA, and PO. Fly anatomy is not in there at all. I think that would be a separate request if it needs to get into go-lego. I haven't done anything with stages yet.

**Comment by vanaukenk** [comment]
From discussion on 2019-10-30 GO-CAM specifications call, we think that it would be nice to just use GO 'biological phase' or UBERON 'life cycle stage' in the ShEx, if possible, and bridge other life stage ontologies, accordingly.

@cmungall do you think we could choose one or the other, or do we need both GO and UBERON biological phase and life cycle stages, respectively?

**Comment by balhoff** [comment]
When we link stages to an upper term, need to include XAO developmental stage, which I am adding to go-lego for #19259.

**Comment by balhoff** [comment]
Done in https://github.com/geneontology/go-ontology/pull/22287

There is a separate issue to add GO biological phases: https://github.com/geneontology/minerva/issues/496
