### ISSUE TITLE
removal of cofactor & coenzyme roles from equivalence axioms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#17911]
As discussed in this pull request "**DO NOT MERGE-Update ChEBI import**": https://github.com/geneontology/go-ontology/pull/17673

We are going to follow this plan:

> 1. proceed with deleting the equivalence axioms that use either the cofactor or coenzyme roles
> 2. create a pull request
> 3. ask Jim to do the diff of inferences on the PR which can then be discussed

**Comment by krchristie** [comment]
For my analysis of the diff between the versions with these 12 equivalence axioms and with them removed, and for subsequent discussion, please see the pull request "**removed all 12 axioms using cofactor or coenzyme roles**" #17913

**Comment by krchristie** [comment]
Repeating summary from "r**emoved all 12 axioms using cofactor or coenzyme roles**" #17913 here in the ticket:

Thanks @pgaudet for pointing out the issue that the equivalence axiom of `FAD transport` references the GO term `cofactor transport`. With respect to changing these axioms, I think that's within the scope of the ChEBI roles project, so I will assign that ticket to myself.

However, the lack of classification of `x transmembrane transport` terms as types of `x transport` terms where x is some compound, may or may not be related to the `cofactor` role as the classification issue exists in the current updated master version of the ontology where I have not removed the `cofactor/coenzyme` roles.

![FADtransportVsTransmembrane](https://user-images.githubusercontent.com/10533218/65975135-04fa1f80-e423-11e9-9d66-dbd6a3d5f61b.jpg)

But one step at a time, 

- I'll proceed with the ticket to remove the 12 equivalence axioms using `cofactor/coenzyme` roles
- I'll make a ticket to change the equivalence axiom of `FAD transport` to see if it fixes the classification of the `FAD transmembrane transport` term.
- Depending on what happens there, I'll make a ticket about the lack of automatic classification of `x transmembrane transport` terms as types of `x transport` terms where x is some compound

**Comment by krchristie** [comment]
comment from @ukemi in pull request "**removed all 12 axioms using cofactor or coenzyme roles**" #17913 
> We should probably start commenting in the ticket instead of in the pull request. But one thing this points out is to check to see where the relations to role terms have been asserted in the ontology. It might lead to weirdness when we pull out the inferences.

@ukemi - I'm not sure what you're suggesting that we need to do. The 12 equivalence axioms I removed are ALL of the places in the GO editors file that we directly reference the GOCHE terms for either
- substance with cofactor role
- substance with coenzyme role

Thus, the diff Jim made should be ALL of the changes that will occur from removing the roles. Near the bottom of the diff in the pull request, you can see that the two GOCHE terms are removed as classes in the reasoned file:

> substance with coenzyme role http://purl.obolibrary.org/obo/GOCHE_23354
> Removed
> 
>     Class: substance with coenzyme role
> 
> substance with cofactor role http://purl.obolibrary.org/obo/GOCHE_23357
> Removed
> 
>     Class: substance with cofactor role


The issue @pgaudet was talking about was that the equivalence axiom for the term`FAD transport` refers to the GO term for `cofactor transport`. As I've discussed with @deustp01, we should consider that we may need to remove all direct assertions of specific substances under terms like `cofactor transport` because if we only keep in the ontology the ones that are rigid, then it looks like we are providing a grouping term, but it produces a biologically unsatisfying result that it provides only a partial result containing only the things that always have that role, but not the things that only sometimes have that role, rather than everything that can have that role.

**Comment by ukemi** [comment]
Looks like you have already done what i am suggesting. I just wanted to be sure you hadn't only looked at places where we had referenced them in logical defs.

**Comment by krchristie** [comment]
On 10/9/19 at the GOC meeting in Berkeley , I presented the status of this project, slides here:
https://drive.google.com/drive/u/0/folders/1f2o49dgfyWNMoq8uo5tKGnW2AufWtViF 

The summary is that removing these equivalence axioms related to the cofactor and coenzyme roles 
- mostly removes only things we want to remove
- points out some inconsistencies in usage, or not, of cofactor terms within equivalence axioms
- partial coding of substances with cofactor roles into the ontology (by hard coding only the ones that always have a given role but NOT hard coding the ones that have multiple roles) leads to incomplete representation within GO of things like `cofactor metabolism` or `cofactor binding`.

At the GOC meeting, we agreed that the third issue is a problem and that we need to come up with another way to deal with roles than what we are doing now. At least two options were mentioned at the meeting including those listed below, but there may be additional options.
- not coding roles into the ontology, but instead making it possible to query at the annotation level for annotations relevant to a given role
- coding them into the ontology using some alternative relationship that does not require being ALWAYS true

**Comment by krchristie** [comment]
I think further discussion at an editors call is needed for me to know how to proceed on this ticket so I'll add the editors discussion label.

**Comment by krchristie** [comment]
**Summary of discussion at ontology editors meeting on 10/21/19**
- Immediate action to test what will happen if we stop reasoning over ChEBI roles so that we can stop blocking the ChEBI import
-- @balhoff - will change the code to make this change and generate a pull request
-- @krchristie - will work with @balhoff to analyze the effects of this change
- We still need to come up with a strategy to give users what they expect with respect to substances with roles such as cofactors. Perhaps a smaller working group might be a more productive way to go forward with this.

**Comment by balhoff** [comment]
@krchristie here is the result on the GO classification if the role reasoning is removed (I eliminated logical definitions linking GOCHE terms to CHEBI roles):

https://github.com/geneontology/go-ontology/blob/without-role-reasoning/src/ontology/go-diff-without-role-reasoning.md

**Comment by krchristie** [comment]
This proposal has been rejected. Instead we will obsolete the `cofactor` & `coenzyme` grouping terms as described in the ticket linked above.
