### ISSUE TITLE
part_of children to symbiotic process

### ISSUE THREAD

**Issue by mgiglio99** [geneontology/go-ontology#17928]
I noticed that 'interaction with host' GO:0051701 is a part_of child to 'symbiotic process' GO:0044403. However, it seems to me that it should be an is_a child. 
I'm wondering if the part_of relationship is left over from when the parent term was 'symbiosis',  rather than 'symbiotic process'.
It would simplify the tree to get rid of the part_of's. 
 'interaction with host' now has an is_a parent of 'interspecies interaction between organisms' which itself is a parent of symbiotic process'. that relationship could be removed if 'interaction with host' was an is_a of 'symbiotic process'.

![Screen Shot 2019-09-30 at 10 19 46 PM](https://user-images.githubusercontent.com/14871756/65929520-70ff6800-e3d0-11e9-81fd-44a9006ee829.png)

There are actually several other part_of children to 'symbiotic process' as well that I think could be is_a's. And all of the part_of children are not treated the same. For example - 'adhesion of symbiont to host' does not have the same is_a parent as 'interaction with host'  (And on a related note, I wonder why 'adhesion of symbiont to host' is not a child of 'interaction with host')

![Screen Shot 2019-09-30 at 10 23 42 PM](https://user-images.githubusercontent.com/14871756/65929680-000c8000-e3d1-11e9-863c-72bea7de3f6e.png)

Here is a screen shot showing all the children of 'symbiotic process' - I think most , if not all, of these part_of's could (should) be is_a's 

![Screen Shot 2019-09-30 at 10 21 27 PM](https://user-images.githubusercontent.com/14871756/65929850-92148880-e3d1-11e9-9a69-781bb8262297.png)

**Comment by pgaudet** [comment]
I think the parent 'multi-organism process' is wrong though - it should be 'interspecies interaction between organisms' (multi-organism also covers multi organisms of the same species). 

OK @mgiglio99 ?

**Comment by mgiglio99** [comment]
Are you meaning specifically for 'adhesion of symbiont to host'?
If so, I agree. If we make the relationship for 'adhesion to host'  is_a to 'symbiotic process' then we can just remove the 'multi-organism process' parent for 'adhesion to host'

**Comment by pgaudet** [comment]
OK. 

I also meant generally -  'interspecies interaction between organisms' is a child or 'multi-organism process', and more precise to represent symbiotic relations. 

Pascale

**Comment by mgiglio99** [comment]
Yes indeed. But all of the ones I was thinking of are currently part_of children of 'symbiotic process' which is a child of 'interspecies interaction between organisms' - so if we just change all of those to is_a, then we can remove their other is_a parents to 'interspecies interaction between organisms' or 'multi-organism' process, or whatever they have to make them is_a complete. (Unless the other parent makes sense, like 'biological adhesion' for 'adhesion of symbiont to host'.)

**Comment by pgaudet** [comment]
Right, got it. Thanks !
