### ISSUE TITLE
Remove bad cross-references to TIGRFAM

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17935]
Remove bad cross-references to TIGRFAM: 
GO:0031004    potassium ion-transporting ATPase complex 
has cross-reference to TIGR_TIGRFAMS:TIGR01497

GO:0042380 hydroxymethylbutenyl pyrophosphate reductase activity
has mentions TIGR00216. 

I will remove those, unless @mgiglio99 you think these are valid ? 

Thanks, Pascale

**Comment by mgiglio99** [comment]
For the first one the TIGRFAM is for a subunit of the complex but I don't think it makes sense to cross reference it. So yes to remove cross_ref.
For the second one, the comment in general seems not great. Should I get someone to review this activity and see if the comment can just be removed?

**Comment by pgaudet** [comment]
I already removed the comment but let me know if you want to add anything back. 

Thanks, Pascale

**Comment by mgiglio99** [comment]
ok - I'll add it to my list of things to look at - but I think you can still leave this issue closed.
