### ISSUE TITLE
Fix 'modulation of complement activation in other organism' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17932]
Hello, 

I think the following terms should be 'in host' rather than 'in other organism':  

'modulation of complement activation in other organism'
and children: 
'modulation of complement activation, alternative pathway in other organism'
'negative regulation of complement activation, alternative pathway in other organism'
'positive regulation of complement activation, alternative pathway in other organism'
'modulation of complement activation, classical pathway in other organism'
'negative regulation of complement activation, classical pathway in other organism'
'positive regulation of complement activation, classical pathway in other organism'
'modulation of complement activation, lectin pathway in other organism'
'negative regulation of complement activation, lectin pathway in other organism'
'positive regulation of complement activation, lectin pathway in other organism'
'modulation of mast cell degranulation in other organism'
'positive regulation of mast cell degranulation in other organism'

(note that there are no annotations to any of these terms)

OK @mgiglio99 @addiehl @ValWood ? 

Thanks, Pascale

**Comment by addiehl** [comment]
I agree these should just be in host.  There are proteins in the wild that could well be annotated to some of these terms: "Complement inhibition by gram-positive pathogens: molecular mechanisms and therapeutic implications" (PMID:20062962) is just the tip of the iceberg of such potential annotations, but of course I don't do annotation anymore and I have never annotated bacterial proteins.  Nevertheless, lack of annotations does not make a term invalid in this case.

Alex

**Comment by pgaudet** [comment]
Paper cited in one of the terms mentions some snake venom: 
https://www.ncbi.nlm.nih.gov/pubmed/20837040

In this case the 'target' is not a host but a prey. 

Most other terms relevant to venoms are under this branch: 
- GO:0051705 multi-organism behavior
--  GO:0035737 injection of substance in to other organism
---  GO:0035738 envenomation resulting in modification of morphology or physiology of other organism 
--- etc

So specifically the terms above would be redundant with 'GO:0044646 envenomation resulting in modulation of complement activation in other organism' and children 
- GO:0044646 envenomation resulting in modulation of complement activation in other organism
 - GO:0044642 envenomation resulting in modulation of complement activation, alternative pathway in other organism
- GO:0044636 envenomation resulting in modulation of complement activation, classical pathway in other organism
- GO:0044639 envenomation resulting in modulation of complement activation, lectin pathway in other organism 

Since there are no annotations on any of these terms, I can change the snake references to the envenomation terms and change the term labels as I suggested above. 

Longer term - do we need two branches to represent hosts versus preys (and preys attached by envenomation versus other mechanisms to deliver a toxin?) 

Thanks, Pascale

**Comment by mgiglio99** [comment]
I initially thought there should already be host terms for these, thinking they were PAMGO or PAMGO-like. From the date looks like these were not PAMGO terms, so I guess that's why there's no corresponding host terms.

If we have the 'envenomation' set and we want a 'host' set, shouldn't they both be children of the 'other organism' set mentioned above?

And is it correct that the 'envenomation' parent is 'injection of substance into other organism'? It seems to me that parent is about the actual injection, where as the envenomation children are are about what the proteins are doing once they are in. Seems not quite right to me.

**Comment by pgaudet** [comment]
> Seems not quite right to me.

Me neither. Moreover, other mechanism of delivering toxins (for example by frogs) would not apply, even though the mechanism of action of the actual toxin could be the same. 

Moreover (again), the actual 'injection' is also unrelated to how a toxin acts, so I would argue in favor of uncoupling delivery and mode of action of the toxin. 

See also #15553 

Pascale

**Comment by mgiglio99** [comment]
I agree.

**Comment by pgaudet** [comment]
Will be fixed in #22349
