### ISSUE TITLE
EC 2.4.1.173 present in 4 GO terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17949]
Hello, 

EC:2.4.1.173 is a cross reference for 4 terms: 
- GO:0102203  brassicasterol glucosyltransferase activity
- GO:0102202 soladodine glucosyltransferase activity
- GO:0102205 cholesterol allpha-glucosyltransferase activity (I'll correct the typo)
- GO:0016906 sterol 3-beta-glucosyltransferase activity

These correspond to 4 different MetaCyc reactions, but all are cross-referencing the same proteins, as if there is some promiscuity in substrates ? 

@keseler are these really different reactions ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
This is ok. EC does this.
Also, I imagine they will have separate RHEA reactions reflecting this. I will check and add.

**Comment by pgaudet** [comment]
ok good !

**Comment by hdrabkin** [comment]
The EC maps to only 1 RHEA; RHEA:22724
a sterol + UDP-alpha-D-glucose = a sterol 3-beta-D-glucoside + H(+) + UDP
Cross reference: EC 2.4.1.173
This matches  GO:0016906 
I can request RHEA for the other ones. 
Remember: the EC id is mechanism. All 4 rxns use the same mechanism but the exact reactants differ. I will request the 3 for rhea

**Comment by keseler** [comment]
I'll be checking back with our MetaCyc curator/EC number expert, Ron.  The primary issue is that 2.4.1.173 has the generic "a sterol" as a substrate.  In MetaCyc, there are "instance reactions" with solasodine (RXN-12123), cholesterol (RXN-12127), ergosterol, brassicasterol (RXN-12125), digitoxigenin, sitosterol, and stigmasterol.  They don't seem to have their own EC numbers.

**Comment by hdrabkin** [comment]
It's more important for GO that they have their own RHEA ids. 
It's ok metacyc has the instance; you can think or the RHEA as the instance also; using the same mechanism as the EC:2.4.173;

**Comment by hdrabkin** [comment]
@pgaudet 
I didn't realize  you had fixed the typo and used the ticket number.
I just put a push using the same number to add a RHEA to one ID. Now the PR doesn't show up
Can you remedy this. ?

**Comment by hdrabkin** [comment]
@pgaudet , I fixed it. never mind

**Comment by hdrabkin** [comment]
I just added the RHEA for GO:0016906 and have put in requests for the other 3 reactions

**Comment by pgaudet** [comment]
thanks!

**Comment by pgaudet** [comment]
I think this is done ?

**Comment by hdrabkin** [comment]
The requested RHEAs are Still not in RHEA public yet. Please leave open.

**Comment by hdrabkin** [comment]
The following RHEA ids are now public
RHEA:61840 brassicasterol + UDP-α-D-glucose = brassicasterol
3-β-D-glucoside + H+ + UDP (MetaCyc RXN-12125)
RHEA:61844 solasodine + UDP-α-D-glucose = H+ + solasodine
3-β-D-glucoside + UDP (MetaCyc RXN-12123)
RHEA:61848 cholesterol + UDP-α-D-glucose = cholesteryl 3-β-D-glucoside +
H+ + UDP (MetaCyc RXN-12127)
RHEA:61828 stigmasterol + UDP-α-D-glucose = H+ + stigmasterol
3-β-D-glucoside + UDP (MetaCyc RXN-12126) (GO:0051508
RHEA:61832 (24R)-ethylcholest-5-en-3β-ol + UDP-α-D-glucose = H+ +
sitosterol 3-β-D-glucoside + UDP (MetaCyc RXN-12128) GO:0051507
RHEA:61836 ergosterol + UDP-α-D-glucose = ergosteryl 3-β-D-glucoside +
H+ + UDP (MetaCyc RXN-16975) (GO:0051506)

I believe GO:0051505 cholesterol UDP-glucosyltransferase activity should be merged into GO:0102205 cholesterol alpha-glucosyltransferase activity (which has RHEA, metacyc, etc.).

**Comment by hdrabkin** [comment]
Merged term GO:0051505 cholesterol UDP-glucosyltransferase activity into O:0102205 cholesterol alpha-glucosyltransferase activity

**Comment by hdrabkin** [comment]
Rhea's added; removing tag
