### ISSUE TITLE
NTR: metacyclogenesis

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#17941]
Can I request a new GO term entry for metacyclogenesis process please?

Accession: GO:xxxxxx
Name: metacyclogenesis
Ontology: biological_process
Definition: The morphological, biochemical and genetic changes that induce the differentiation of non-pathogenic parasites into pathogenic metacyclic parasites in the Trypanosomatidae species. The pathogenic parasites are known as metacyclic trypomastigotes in Trypanosoma and metacyclic promastigotes in Leishmania.
Taxonomic restriction: NCBITaxon:5654 ## Trypanosomatidae
Source: PMID:12152483, PMID:21514274, PMID:2659372, PMID:29091711, PMID:29409544

Thanks & best wishes,
Achchuthan

**Comment by cmungall** [comment]
We should include a link to the parasite life cycle term

**Comment by Achchuthan** [comment]
Thanks @cmungall. The metacyclic trypomastigote stage is OPL:0000149 and metacyclic promastigote stage is OPL:0000006

**Comment by Achchuthan** [comment]
Hi @pgaudet,
I am wondering whether you had a chance to look at this request?
Thanks a lot for your help.
Best wishes,
Achchuthan

**Comment by pgaudet** [comment]
Hi @cmungall I dont know how you want to add the references to the life stages. I tried 'occurs during' but I think we dont have the OPL ontology loaded. 

Maybe @balhoff you know how to handle this ?

**Comment by pgaudet** [comment]
(sorry I just saw the ticket in the OPL ontology. I think I cannot add the xlinks for now).

**Comment by balhoff** [comment]
@pgaudet would you like to add an OPL import?

**Comment by pgaudet** [comment]
I think this is what @cmungall is asking, yes

**Comment by pgaudet** [comment]
New term: 

id: GO:0140384
name: metacyclogenesis
namespace: biological_process
def: "The morphological, biochemical and genetic changes that induce the differentiation of non-pathogenic parasites into pathogenic metacyclic parasites in the Trypanosomatidae species. The pathogenic parasites are known as metacyclic trypomastigotes in Trypanosoma and metacyclic promastigotes in Leishmania." [PMID:12152483, PMID:21514274, PMID:2659372, PMID:29091711, PMID:29409544]
is_a: GO:0044114 ! development of symbiont in host
created_by: pg
creation_date: 2019-11-20T13:25:55Z

**Comment by pgaudet** [comment]
PR for taxon constraint: https://github.com/geneontology/go-ontology/pull/18220

**Comment by pgaudet** [comment]
- [ ] Still need to add links to the parasite life cycle term

**Comment by Achchuthan** [comment]
Thanks a lot @pgaudet and @balhoff.

**Comment by pgaudet** [comment]
I dont know what to do next for this ticket.

**Comment by balhoff** [comment]
I added the import file. If you update you should be able to use the parasite terms now.

**Comment by pgaudet** [comment]
Hi @Achchuthan 
Can you please specific which stage is the end point of metacyclogenesis? 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet,
There is no single end stage for metacyclogenesis across kinetoplastida parasites. The end stage of metacyclogenesis in Trypanosoma is metacyclic trypomastigote stage (OPL:0000149) and the end stage in Leishmania is metacyclic promastigote stage (OPL:0000006).
Thanks,
Achchuthan

**Comment by pgaudet** [comment]
@cmungall 
What do you recommend ? As far as I can tell the options are to either create two terms or to not include these terms. 

Thanks, Pascale

**Comment by cmungall** [comment]
@Achchuthan @zhengj2007 - should OPL not include a generic grouping class "metacyclic stage" that groups the metacyclic stages in both taxa?

**Comment by zhengj2007** [comment]
Hi @cmungall 
OPL does not have term "metacyclic stage" and the term is not found in any other OBO Foundry ontologies. Do you mean OPL should add a new term "metacyclic stage"?

**Comment by cstoeckert** [comment]
OPL will work on adding a general metacyclic stage (which appears restricted to trypanosomatid parasites).

**Comment by pgaudet** [comment]
Added the term in olp-imports: https://github.com/geneontology/go-ontology/pull/18754

I can fix the LD once the imports have been regenerated.

**Comment by pgaudet** [comment]
@balhoff 
Can you please regenerate the OPL imports ?

**Comment by balhoff** [comment]
@pgaudet it doesn't look like OPL has made a new release yet.

**Comment by zhengj2007** [comment]
@pgaudet @balhoff We will make a new release soon.

**Comment by zhengj2007** [comment]
@pgaudet @balhoff The new release of OPL has been made. The required term is available, ‘Trypanosomatida metacyclic stage’ OPL_0000322.

The latest released OPL version IRI is: http://purl.obolibrary.org/obo/opl/2020-02-08/opl.owl

**Comment by pgaudet** [comment]
Added ends_with OPL:0000322 ! Trypanosomatida metacyclic stage.
