### ISSUE TITLE
Bad EC GO:0103116 ATPase-coupled alpha-D-galactofuranose transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17951]
Hello, 

GO:0103116     ATPase-coupled alpha-D-galactofuranose transporter activity
has no annotations, and a reference to a partial EC that is now deleted/replaced. 

@hdrabkin Can you check what this corresponds to? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Ok I will first delete the partial if uses as an xref. Partials are for grouping terms only
We can leave GOC:pz for now as the def ref.
There is really no proper reference at Metacyc for it.
I will request a RHEA

**Comment by hdrabkin** [comment]
Leaving this open until I hear from RHEA; partial EC removed

**Comment by hdrabkin** [comment]
RHEA:61716 now public
EC:7.5.2.9
Added to GO:0103116
