### ISSUE TITLE
arachidonate 12(R)-lipoxygenase activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#17958]
Hi,
PMID=10100631 and 11256953 describes arachidonate 12(R)-lipoxygenase activity.
Could you please create a go term for this function.
Many thanks.
Guilaine

**Comment by hdrabkin** [comment]
Hi @Argoudpuy 
Can you please write out the reaction is this is not correct?
Arachidonate + O(2) <=> (5Z,8Z,10E,14Z)-(12S)-12-hydroperoxyicosa-5,8,10,14-tetraenoate
(EC 1.13.11.31)
https://en.wikipedia.org/wiki/ALOX12 
RHEA:10428 (5Z,8Z,11Z,14Z)-eicosatetraenoate + O2 = (12S)-hydroperoxy-(5Z,8Z,10E,14Z)-eicosatetraenoate Cross reference: EC 1.13.11.31

suggested is_A parent?

**Comment by hdrabkin** [comment]
I see we already have
GO:0004052 arachidonate 12-lipoxygenase activity
talysis of the reaction: arachidonate + O(2) = (5Z,8Z,10E,12S,14Z)-12-hydroperoxyicosa-5,8,10,14-tetraenoate.
XREF: EC:1.13.11.31
RHEA:10428; 
Both RHEA and EC specify the product as the 12(S), and the reaction defined in GO mentions 12S although the GO term name does  not.
So basically the only difference here is that the product is 12(R) correct?
I'll need to request a RHEA fo your proposed term so I need to be sure about the product name

arachidonate + O(2)=(5Z,8Z,10E,12R,14Z)-12-hydroperoxyicosa-5,8,10,14-tetraenoate

**Comment by hdrabkin** [comment]
Term created; rhea pending
+id: GO:0106237
+name: arachidonate 12(R)-lipoxygenase activity

**Comment by hdrabkin** [comment]
Also renamed GO:0004052 to reflect the RHEA and EC assigned 
arachidonate 12-lipoxygenase activity - > arachidonate 12(S)-lipoxygenase activity

**Comment by ValWood** [comment]
I see this is already done so closing

**Comment by hdrabkin** [comment]
Rhea has not yet made id for 
+arachidonate 12(R)-lipoxygenase

**Comment by hdrabkin** [comment]
should have come through; checking

**Comment by hdrabkin** [comment]
RHEA:41336 for GO:0106237 now available in RHEA public release. Adding to the 12R term and closing

**Comment by hdrabkin** [comment]
rhea added removing tag
