### ISSUE TITLE
vitamin D 23-hydroxylase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#17968]
Dear GO curators,

Could you please consider creating these new GO terms:

vitamin D 23-hydroxylase activity as child of GO:0004497: monooxygenase activity
25-hydroxycholecalciferol-23-hydroxylase activity [Rhea:46616]
1-alpha,25-dihydroxyvitamin D3 23-hydroxylase activity [Rhea:49193]
ref: PMID:24893882 review: PMID:30205156; PMID: 22100522

Many thanks

Nevila Hyka-Nouspikel

**Comment by ukemi** [comment]
Is there a Rhea identifier for the generic 'vitamin D 23-hydroxylase' reaction? For 1-alpha,25-dihydroxyvitamin D3 23-hydroxylase activity I will use Rhea:49192 unless you know the reaction only ever proceeds in the 49193 direction.

**Comment by nnouspikel** [comment]
Hi David,

Thank you for taking care of this. 

I thought we might need to create a generic term ‘vitamin D 23-hydroxylase activity’ by analogy to GO:0070576. There is no generic reaction for this activity. 
Based on GO:0004497 monooxygenase activity definition, RHEA:49193 would be correct. But if the rule is not to show the reaction direction, then by all means we can use Rhea:49192.

Best regards,

Nevila

**Comment by ukemi** [comment]
HI Nevila,

I'm making these as children of oxidoreductase based on the D24 and D25 reactions. If you think I should move them all to monooxygenase, let me know and I will.

-David

**Comment by nnouspikel** [comment]
Thank you so much David.  Moving them to monooxygenase would be correct. 

All the best,
Nevila
