### ISSUE TITLE
peptidyl-lysine 2-hydroxyisobutyrylation and glutarylation

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#17966]
Hi GO,

I would need a bunch of new terms for enzymes mediating new PTMs (some of them are histone marks)

Thanks

Sylvain

1)
Term: peptidyl-lysine 2-hydroxyisobutyrylation
Category: Process
Definition: The 2-hydroxyisobutyrylation of a lysine residue in a protein.
child of GO:0043543 protein acylation
PMID:29775581 

2)
Term: peptide 2-hydroxyisobutyryltransferase activity
Category: Function
Definition: Catalysis of the reaction: 2-hydroxyisobutyryl-CoA + lysine in peptide = CoA + N-2-hydroxyisobutyryl-lysine-peptide. 
child of GO:0016410 N-acyltransferase activity
RHEA:24180
PMID:29775581 

3)
Term: peptidyl-lysine glutarylation
Category: Process
Definition: The glutarylation of a lysine residue in a protein.
child of GO:0043543 protein acylation
PMID:31542297 

4)
Term: peptide glutaryltransferase activity
Category: Function
Definition: Catalysis of the reaction: glutaryl-CoA + L-lysyl-[protein] = CoA + H+ + N6-glutaryl-L-lysyl-[protein]
child of GO:0016410 N-acyltransferase activity
RHEA:18009
PMID:31542297 

5)
Term: histone glutaryltransferase activity
Category: Function
Definition: Catalysis of the reaction: glutaryl-CoA + histone = CoA + H+ + N6-glutaryl-histone
child of peptide glutaryltransferase activity
PMID:31542297 

6)
Note that hierarchy of the following terms should be modified
GO:0106075 peptide N-succinyltransferase activity
GO:0140065 peptide butyryltransferase activity
GO:0140064 peptide crotonyltransferase activity

These terms should be child of GO:0016410 N-acyltransferase activity and not N-acetyltransferase

The same for 
GO:0140067; P:peptidyl-lysine butyrylation
GO:0140066; P:peptidyl-lysine crotonylation
GO:0061921; P:peptidyl-lysine propionylation

**Comment by sylvainpoux** [comment]
Hi Harold,
I would be wondering if you already looked at this ticket, because I would need these terms to curate my papers
Thanks
Sylvain

**Comment by hdrabkin** [comment]
Hi Sylvain
I have been away at the GOC meeting followed by a vacation; I will try to get these in today

**Comment by hdrabkin** [comment]
Have you already looked to see if your MF requests have a RHEA id, and if so please add to this ticket? Thanks

**Comment by sylvainpoux** [comment]
No problem,
by the way, I encountered one new deacylase reaction and would need 2 new terms. Would it be possible to handle them in the same time? the Rhea is included

Term:
Protein-propionyllysine depropionylase activity
Category: Function
Definition:
Catalysis of the reaction: protein-propionyllysine + NAD(+) => protein-lysine + 3''-O-propanoyl-ADP-D-ribose + nicotinamide. This reaction is the removal of a propionyl group from a propionylated lysine residue of a protein or peptide.
Xref: 
Rhea:23500
PMID:30026585

Protein depropionylation
Category: Process
Definition:
The removal of a propionyl group from a residue in a peptide or protein.
Child of:  GO:0035601 protein deacylation
Xref: PMID:30026585

**Comment by hdrabkin** [comment]
Hi @sylvainpoux 
what would be the parent for protein-propionyllysine depropionylase activity?
clearly not a hydrolase type deacylase
Also, do you  have a RHEA for histone glutaryltransferase activity; I've put the term in but need a RHEA

**Comment by sylvainpoux** [comment]
We usually do not create Rhea reactions for specific class of proteins (there are few exceptions). It is why we have not created a specific Rhea for this: histone is a protein

**Comment by sylvainpoux** [comment]
Regarding  protein-propionyllysine depropionylase activity, very good point! Actually the reaction is an acyltransferase reaction (EC 2.3.1.-) and we could add GO:0016410 N-acyltransferase activity as parent.

This also means that previous reactions below are wrong and should be modified (see for example https://www.uniprot.org/uniprot/Q8K2C6):

GO:0036055 protein-succinyllysine desuccinylase activity RHEA:47664
GO:0061697 protein-glutaryllysine deglutarylase activity RHEA:47668
GO:0036054 protein-malonyllysine demalonylase activity RHEA:47672 

Could you change the definition of these terms and change their parent term?

Thanks

Sylvain

**Comment by hdrabkin** [comment]
BTW, chebi does have an id for histone, so I suppose rhea might consider it. Anyway, I'll complete this ticket today and then go dark so I can work on my presentation for a meeting next week.

**Comment by hdrabkin** [comment]
GO:0036055 protein-succinyllysine desuccinylase activity RHEA:47664 ????? 47668 but no free succinate in the rhea
GO:0061697 protein-glutaryllysine deglutarylase activity RHEA:47668   ->  RHEA:47664?
GO:0036054 protein-malonyllysine demalonylase activity RHEA:47672  Current GO does not have NAD+ as reactant. 
These all seem to use water whereas you new term does not. 
also  Cannot find RHEA:23500 ; is this a new RHEA?

**Comment by sylvainpoux** [comment]
Sorry, yes:
1)
GO:0036055 protein-succinyllysine desuccinylase activity  -> RHEA:47668
GO:0061697 protein-glutaryllysine deglutarylase activity RHEA:47664
2)
Yes, GO reaction should be modified and NAD added (many sirtuin reactions have been modified recently)
3) Yes, RHEA:23500 is new and it actually uses water (my mistake again, I was just back from the US and jetlagged when I submitted these terms). Here is the complete reaction:
Reaction=H2O + N(6)-propanoyl-L-lysyl-[protein] + NAD(+) = 3''-O-propanoyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide;
Xref=Rhea:RHEA:23500, Rhea:RHEA-COMP:9752, Rhea:RHEA-COMP:13758, ChEBI:CHEBI:15377, ChEBI:CHEBI:17154, ChEBI:CHEBI:29969, ChEBI:CHEBI:57540, ChEBI:CHEBI:138019, ChEBI:CHEBI:145015;

Sorry for the misunderstanding

**Comment by hdrabkin** [comment]
ok; the new term went  in without the RHEA:23500 but will now fix with water, ad and this ticket is marked RHEA pending.
Just to be clear though, these are still all N-acyl-transferases and not ''hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds''?

**Comment by hdrabkin** [comment]
Can you please recheck the parent. I ask because 22076378[PMID]  calls them 'NAD-dependent deacetylases (GO:0033558, protein deacetylase) _ not deacylases .

**Comment by sylvainpoux** [comment]
Sirtuins are commonly named "NAD-dependent deacetylases" but a number of them are in fact deacylases (SIRT5; https://www.uniprot.org/uniprot/Q9NXA8) or deacetylases and deacylases (SIRT7)
succinyl, glutaryl, malonyl, propionyl are all acylations

**Comment by hdrabkin** [comment]
Ok, just wanted to be sure before going through to change them. Thanks @sylvainpoux !

**Comment by pgaudet** [comment]
@hdrabkin 
I was looking for something else but came across this - is this ready to implement ?

**Comment by hdrabkin** [comment]
I was going to add the RHEA as part of the bulk load, but I'll just add it now and close.

**Comment by hdrabkin** [comment]
removing RHEA pending tab=g
