### ISSUE TITLE
2 terms with the same name, cellular response to zinc ion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17961]
![bad](https://user-images.githubusercontent.com/7359272/66235533-217aae00-e6e8-11e9-88b7-ce88fc253505.jpg)

**Comment by ValWood** [comment]
I get it. One is the starvation term (truncated) , and  the other one is the high zinc.

**Comment by cmungall** [comment]
it's not the first time this has come up - make quickgo ticket?
