### ISSUE TITLE
transcription in response to nutrient terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17974]
What is the long term plan for these:
1) GO:0034225 regulation of transcription from RNA polymerase II promoter in response to zinc ion starvation

2 GO:0061986 negative regulation of transcription by glucose

Shoud these be post composed or precomposed?

**Comment by ValWood** [comment]
OK @pgaudet  I see your review ticket

**Comment by pgaudet** [comment]
To be obsoleted as part of #12739
