### ISSUE TITLE
GO:0051824 recognition of other organism involved in symbiotic interaction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17977]
We need to decide what to do with this branch
There is overlap with "response to" and other areas
GO:0051824 recognition of other organism involved in symbiotic interaction

**Comment by ValWood** [comment]
There are  ZERO annotation in this branch.
What  does it mean specifically?
Another organism is recognised by a  receptor  interaction. 
 This term does not seem to be required.

I would annotatate  to a receptor for recognition.

I suggest we just obsolete. There clearly hasn't been a need (the immune system signalling pathways  *are * the recognition processes).

It's just another way of saying the same thing ?

**Comment by ValWood** [comment]
@mgiglio99 ?

**Comment by pgaudet** [comment]
This branch has 3 terms: 
'recognition of other organism involved in symbiotic interaction'
'recognition of host'
'recognition of symbiont'

I propose we merge them into GO:0098543 detection of other organism. 

@mgiglio99 @val OK ?

**Comment by ValWood** [comment]
Yes.

But, I don't  even think the detection term is required. I think we discussed this on Friday so it could be in another ticket.

It  seems to be a process term to describe a "receptor"

These are the  (ONLY!) 30  EXP annotations:

UniProtKB	C0LGT6	EFR		GO:0016045	PMID:16713565	IDA		P	LRR receptor-like serine/threonine-protein kinase EFR	EFR,At5g20480,F7C8.70	protein	taxon:3702	20061003	TAIR		
UniProtKB	O60603	TLR2		GO:0042496	PMID:19931471	IDA		P	Toll-like receptor 2	TLR2,TIL4	protein	taxon:9606	20101109	MGI		
UniProtKB	O60603	TLR2		GO:0042495	PMID:19931471	IDA		P	Toll-like receptor 2	TLR2,TIL4	protein	taxon:9606	20101109	MGI		
UniProtKB	O75594	PGLYRP1		GO:0016045	PMID:11461926	IDA		P	Peptidoglycan recognition protein 1	PGLYRP1,PGLYRP,PGRP,TNFSF3L,SBBI68,UNQ639/PRO1269	protein	taxon:9606	20031216	UniProt		
UniProtKB	O88622	Parg		GO:0016045	PMID:15282315	IMP	MGI:MGI:3052740	P	Poly(ADP-ribose) glycohydrolase	Parg	protein	taxon:10090	20041005	MGI		
UniProtKB	P01889	HLA-B		GO:0016045	PMID:22321387	IMP		P	HLA class I histocompatibility antigen, B-7 alpha chain	HLA-B,HLAB	protein	taxon:9606|taxon:1280	20120308	UniProt		
UniProtKB	P13761	HLA-DRB1		GO:0016045	PMID:22321387	IMP		P	HLA class II histocompatibility antigen, DRB1-7 beta chain	HLA-DRB1	protein	taxon:9606|taxon:1280	20120308	UniProt		
UniProtKB	P20792	daf-1		GO:0016045	PMID:25303524	IMP		P	Cell surface receptor daf-1	daf-1,F29C4.1	protein	taxon:6239	20160201	UniProt	occurs_in(WBbt:0005835),occurs_in(WBbt:0006834)	
UniProtKB	P92172	daf-7		GO:0016045	PMID:25303524	IMP		P	Dauer larva development regulatory growth factor daf-7	daf-7,B0412.2	protein	taxon:6239	20160201	UniProt	occurs_in(WBbt:0005667)	
UniProtKB	Q15399	TLR1		GO:0042495	PMID:19931471	IDA		P	Toll-like receptor 1	TLR1,KIAA0012	protein	taxon:9606	20101109	MGI		
UniProtKB	Q3UP24	Nlrc4		GO:0016045	PMID:22885697	IMP		P	NLR family CARD domain-containing protein 4	Nlrc4,Card12,Ipaf	protein	taxon:10090	20120921	UniProt		
UniProtKB	Q42484	RPS2		GO:0016045	PMID:11333251	IMP		P	Disease resistance protein RPS2	RPS2,At4g26090,F20B18.200	protein	taxon:3702	20061002	TAIR		
UniProtKB	Q54KX3	vps13F		GO:0016045	PMID:28076662	IMP		P	Putative vacuolar protein sorting-associated protein 13F	vps13F,DDB_G0287055	protein	taxon:44689	20170217	dictyBase		
UniProtKB	Q54U89	far1		GO:0016045	PMID:28076662	IMP		P	Metabotropic glutamate receptor-like protein L	far1,grlL,DDB_G0281211	protein	taxon:44689	20170217	dictyBase		
UniProtKB	Q8BV57	Ssc5d		GO:0042494	PMID:21217009	IDA		P	Soluble scavenger receptor cysteine-rich domain-containing protein SSC5D	Ssc5d,S5D-SRCRB	protein	taxon:10090	20140214	UniProt		
UniProtKB	Q8CJ91	Cd209b		GO:0016045	PMID:14707091	IDA		P	CD209 antigen-like protein B	Cd209b	protein	taxon:10090	20040602	MGI		
UniProtKB	Q8CJ91	Cd209b		GO:0001879	PMID:14707091	IDA		P	CD209 antigen-like protein B	Cd209b	protein	taxon:10090	20040602	MGI		
UniProtKB	Q96LB8	PGLYRP4		GO:0016045	PMID:11461926	IDA		P	Peptidoglycan recognition protein 4	PGLYRP4,PGRPIB,SBBI67	protein	taxon:9606	20031216	UniProt		
UniProtKB	Q96LB9	PGLYRP3		GO:0016045	PMID:11461926	IDA		P	Peptidoglycan recognition protein 3	PGLYRP3,PGRPIA	protein	taxon:9606	20031216	UniProt		
UniProtKB	Q96PD5	PGLYRP2		GO:0016045	PMID:11461926	IDA		P	N-acetylmuramoyl-L-alanine amidase	PGLYRP2,PGLYRPL,PGRPL,UNQ3103/PRO10102	protein	taxon:9606	20031216	UniProt		
UniProtKB	Q9BXN2	CLEC7A		GO:0016046	PMID:19358895	IDA		P	C-type lectin domain family 7 member A	CLEC7A,BGR,CLECSF12,DECTIN1,UNQ539/PRO1082	protein	taxon:9606|taxon:5476	20190503	ARUK-UCL	occurs_in(CL:0000451)|occurs_in(CL:0000235)	
UniProtKB	Q9FL28	FLS2		GO:0016045	PMID:10911994	IMP		P	LRR receptor-like serine/threonine-protein kinase FLS2	FLS2,At5g46330,MPL12.13,MPL12.8	protein	taxon:3702	20060920	TAIR		
UniProtKB	Q9HC29	NOD2		GO:0016045	PMID:15653568	IDA		P	Nucleotide-binding oligomerization domain-containing protein 2	NOD2,CARD15,IBD1	protein	taxon:9606	20060523	HGNC-UCL		
UniProtKB	Q9JIB6	Naip6		GO:0016045	PMID:21874021	IMP		P	Baculoviral IAP repeat-containing protein 1f	Naip6,Birc1f,Naip-rs4	protein	taxon:10090	20120921	UniProt		
UniProtKB	Q9LYU4	GH3.12		GO:0016046	PMID:10224270	IMP		P	4-substituted benzoates-glutamate ligase GH3.12	GH3.12,GDG1,PBS3,WIN3,At5g13320,T22N19.5,T31B5.140	protein	taxon:3702	20060920	TAIR		
UniProtKB	Q9NPP4	NLRC4		GO:0016045	PMID:15107016	IDA		P	NLR family CARD domain-containing protein 4	NLRC4,CARD12,CLAN,CLAN1,IPAF,UNQ6189/PRO20215	protein	taxon:9606	20060524	HGNC-UCL		
UniProtKB	Q9QUK4	Naip2		GO:0016045	PMID:21874021	IMP		P	Baculoviral IAP repeat-containing protein 1b	Naip2,Birc1b,Naip-rs6	protein	taxon:10090	20120921	UniProt		
UniProtKB	Q9R016	Naip5		GO:0016045	PMID:21874021	IMP		P	Baculoviral IAP repeat-containing protein 1e	Naip5,Birc1e,Naip-rs3	protein	taxon:10090	20120921	UniProt		
UniProtKB	Q9Y239	NOD1		GO:0016045	PMID:15653568	IDA		P	Nucleotide-binding oligomerization domain-containing protein 1	NOD1,CARD4	protein	taxon:9606	20060523	HGNC-UCL		
UniProtKB	Q9Y2C9	TLR6		GO:0042496	PMID:19931471	IDA		P	Toll-like receptor 6	TLR6	protein	taxon:9606	20101109	MGI		

They are all to
detection of diacyl bacterial lipopeptide (MF!)
detection of triacyl bacterial lipopeptide (MF!)
detection of bacterial lipoprotein (MF!)
detection of bacterium
detection of yeast (1)
detection of fungus (2)

Most look like receptors (but possibly not all),

so they could be  curated better as:

MF receptor BP immune process(if known) part_of "response to fungus/bacterium)

The receptor does the detection? So detection is a function not a process?

**Comment by pgaudet** [comment]
1. I'll first do the merge of 
'recognition of other organism involved in symbiotic interaction'
'recognition of host'
'recognition of symbiont'
if it's OK with @mgiglio99 

2. Then open an annotation ticket for your other comment (https://github.com/geneontology/go-ontology/issues/17977#issuecomment-544892013)

**Comment by mgiglio99** [comment]
Are the proposed merges as follows:
-'recognition of other organism involved in symbiotic interaction' into 'detection of other organism'?
-'recognition of symbiont' into 'detection of symbiont'?
Those I'm fine with.
But there is no 'detection of host' term and I think we really need that. Could we turn 'recognition of host' into 'detection of host'?
There are Rhizobium genes that specify host range and are involved with the bacterium associating with specific hosts.

I have worries about the 'detection' branch, I'm not sure about have all of the separate terms for detection of each type of thing - but that can be a separate issue.

**Comment by ValWood** [comment]
In principle I am fine with 'detection of host' but I  do you have examples?

We should maybe discuss precisely what is meant by "detection" -I'm still confused by this term as a biological process. Possibly I am missing something but I can't immediately think of anything that detects but is not a "receptor."

I would annotate this  "detection process" as
MF "x receptor" part_of BP "x immune signalling process".

This raises a question about "detection" terms in general.
Ignoring , for now,  the "detection of (insert you favourate organism or clade) there are lots of  other terms:

detection of oxygen (12 EXP) why not use a  receptor or signalling pathway?
detection of nutrient (2 EXP)  ditto
detection of cAMP (1 EXP)   ditto
detection of pheromone  (20 EXP mainly IEP) ditto
detection of glucose (11 annotations) ditto

I'm sure we discussed/agreed to obsoleting these terms at the signalling workshop?  @ukemi  @pgaudet  do you agree?  Did this just get overlooked? If so I can open a ticket. These terms appear to be "biological processes" describing the molecular function of a receptor? (Actually I will do this anyway)

Clearly, these terms are massively  under-annotated which indicates a likely problem.

**Comment by pgaudet** [comment]
I agree that all the detection stuff sounds very much like some sort of 'receptor' MF.

**Comment by pgaudet** [comment]
* 'recognition of host' already had exact synonym 'detection of host' (I thought we had a check preventing this - @dougli1sqrd )
I changed the label to 'detection of host'

* GO:0051855 recognition of symbiont -> Merged into GO:0009602 detection of symbiont

* GO:0051824 recognition of other organism involved in symbiotic interaction -> Merged into GO:0098543 detection of other organism


Pascale

**Comment by mgiglio99** [comment]
I also agree that the detection terms sound a lot like receptors.
So then the  process for the symbiotic ones would be just 'interaction with host' or 'interaction with symbiont' - is that correct?

**Comment by pgaudet** [comment]
- detection of oxygen (12 EXP) why not use a receptor or signalling pathway?
-> suggest obsoletion, consider: MF GO:0019826 oxygen sensor activity + BP GO:0032364 oxygen homeostasis
- detection of nutrient (2 EXP) ditto
-> suggest obsoletion and reannotation; papers don't seem to talk about the compounds detected as nutrients
- detection of cAMP (1 EXP) ditto
-> suggest obsoletion, consider: GO:0030552 cAMP binding
- detection of pheromone (20 EXP mainly IEP) ditto
-> suggest obsoletion, consider GO:0016503 pheromone receptor activity
- detection of glucose (11 annotations) ditto
-> suggest obsoletion, and create 'glucose sensor activity'?
