### ISSUE TITLE
EC 7.1.-.- are NOT transporters

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17988]
7.1.1.1      Proton-translocating NAD(P)(+) transhydrogenase
7.1.1.2      NADH:ubiquinone reductase (H(+)-translocating)
7.1.1.3      Ubiquinol oxidase (H(+)-transporting)
7.1.1.4      Caldariellaquinol oxidase (H(+)-transporting)
7.1.1.5      Menaquinol oxidase (H(+)-transporting)
7.1.1.6      Plastoquinol--plastocyanin reductase
7.1.1.7      Ubiquinol oxidase (electrogenic, proton-motive force generating)
7.1.1.8      Quinol--cytochrome-c reductase

@deustp01

**Comment by hdrabkin** [comment]
I can't find a EC:7.7.- class; It stops at EC:7.6

EC 7Translocases | Catalyse the movement of ions or molecules across membranes or their separation within membranes |  
https://www.qmul.ac.uk/sbcs/iubmb/enzyme/EC7/
6 subclasses 7.1 through 7.6
Did I say something that said 7.7; typo?

**Comment by hdrabkin** [comment]
see also
https://www.qmul.ac.uk/sbcs/iubmb/enzyme/EC7/0101p.html

**Comment by pgaudet** [comment]
sorry I meant 7.1 - see list of ECs in the first comment.

**Comment by ukemi** [comment]
So is proton transport not a transport?

**Comment by hdrabkin** [comment]
Yes proton transport is covered here I think:
EC 7.1 Catalysing the translocation of hydrons (aka proton H+)
EC 7.1.1 Hydron translocation or charge separation linked to oxidoreductase reactions
EC 7.1.2 Hydron translocation linked to the hydrolysis of a nucleoside triphosphate
EC 7.1.3 Hydron translocation or charge separation linked to oxidoreductase reactions

**Comment by deustp01** [comment]
> So is proton transport not a transport?

Sure. What I was fretting about is that moving that proton necessarily also involves reducing something and oxidizing something. This reorganization has the effect of taking enzymes that were classified as enabling oxidation - reduction reactions (and not as enabling transport) and now classifying them as enabling transport (with oxidation - reduction smuggled in). Where is the gain in information accuracy and usability for whoever consumes GO (and EC) annotations?

**Comment by pgaudet** [comment]
Is the biological aim of this reaction to move a proton around or to reduce it ? 

I think we need to think about this like what we did for ATP hydrolysis - a protein kinase is NOT going 'ATP catabolic process', it is phosphorylating a protein. 

Do you see what I mean ?

**Comment by pgaudet** [comment]
The link to transporter was removed. Fixed EC:1.10.9.1 to EC:7.1.1.6.
