### ISSUE TITLE
removal of unnecessary  grouping term under "entry into host"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17987]
If you agree that we do not require the grouping terms in 
GO:0044411 entry into host through host barriers
and
https://github.com/geneontology/go-ontology/issues/17984

I suggest we also get rid of
GO:0075052    entry into host via a specialized structure

and just have all the 

entry into host via blah
directly under the "entry into host" term

**Comment by ValWood** [comment]
done

**Comment by pgaudet** [comment]
- [ ] Merged GO:0044411 entry into host through host barriers into 
GO:0030260 entry into host cell
 - [ ] Changed label GO:0075052 entry into host via a specialized structure -> 'entry into host via penetration peg', since this is more precise. Change definition accordingly.
