### ISSUE TITLE
regulating the host phagocytosis machinery

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17983]
<img width="1059" alt="Screenshot 2019-10-09 at 20 09 23" src="https://user-images.githubusercontent.com/7359272/66512395-bad30700-ead0-11e9-868a-f34a9222d3f9.png">

These are the terms related to modulation of host phagocytosis by symbiont

GO:0052190    modulation by symbiont of host phagocytosis
Any process in which an organism modulates the frequency, rate or extent of phagocytosis, the engulfing by phagocytes of external particulate material, in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

GO:0052191    positive regulation by symbiont of host phagocytosis

This term, in a different place:

GO:0052067  negative regulation by symbiont of entry into host cell via phagocytosis

So the symbiont  uses the host phagocytosis machinery for entry into the host.
This is described by the child of  GO:0052190    
GO:0052191    positive regulation by symbiont of host phagocytosis
Definition Any process in which an organism activates, maintains or increases the frequency, rate or extent of phagocytosis, the engulfing by phagocytes of external particulate material, in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

i.e if the symbiont is  positively regulating the phagocytosis machinery it is using it to enter the host.

Therefore this is the term which should have an "entry into host parentage". I think it would be better to describe this term as a 'hijacking' process.

The GO:0052067  negative regulation by symbiont of entry into host cell via phagocytosis
is describing *avoidence* of engulfment by  host phagocytosis (i.e by macrophages).
this term is nothing to do with "entry into host", but this term does have (incorrectly)  the entry into host parentage.

**Comment by ValWood** [comment]
Actions

- [ ] . Rename GO:0052067 
negative regulation by symbiont of entry into host cell via phagocytosis to
to
"antiphagocytosis" 
synonym "phagocytosis avoidence" 

This fits the definition
Any process in which an organism stops or prevents itself undergoing phagocytosis into a cell in the host organism.
and the exisiting 5 annotations.

 - [ ] Remove the parent "entry into host" from this term

- [ ]  Add the parent "entry into host" to 
GO:0052190 modulation by symbiont of host phagocytosis

- [ ] Possibly rename the term for entry into host  so it isn't a regulation term, but a hijacking term

**Comment by ValWood** [comment]
After speaking with @thomaspd  have revised the above. 

We should rename all of the "entry into host" terms

"entry into host via XXX" 

I will open a ticket to cover these.

**Comment by pgaudet** [comment]
Need to look at other relevant terms: 

* 'GO_0052231 modulation of phagocytosis in other organism involved in symbiotic interaction' 
* 'GO_0052522 positive regulation by organism of phagocytosis in other organism involved in symbiotic interaction' 
* 'GO_0052379 modulation by organism of entry into other organism via phagocytosis involved in symbiotic interaction' 
* 'GO_0052483 negative regulation by organism of entry into cell of other organism via phagocytosis involved in symbiotic interaction' 
* 'GO:0052066 entry of symbiont into host cell by promotion of host phagocytosis'

**Comment by ValWood** [comment]
gah, this is almost an exact duplicate of
https://github.com/geneontology/go-ontology/issues/18562
but it has some useful suggestions. We should address both together today.
