### ISSUE TITLE
entry into host through natural portals

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17985]
Penetration by a symbiont into a host organism via naturally occurring openings in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.
Secondary IDs

I can't immediately think of any genes in a symbiont that would be annotated to this. Does anyone have any examples?

If not I suggest obsoletion.

There is a single annotation from

The intestinal resident Candida glabrata opportunistically infects humans. However few genetic factors for adaptation in the intestine are identified in this fungus. Here we describe the C. glabrata CYB2 gene encoding lactate dehydrogenase as an adaptation factor for survival in the intestine. CYB2 was identified as a virulence factor by a silkworm infection study. To determine the function of CYB2, we analysed in vitro phenotypes of the mutant Δcyb2. The Δcyb2 mutant grew well in glucose medium under aerobic and anaerobic conditions, was not supersensitive to nitric oxide which has fungicidal-effect in phagocytes, and had normal levels of general virulence factors protease, lipase and adherence activities. A previous report suggested that Cyb2p is responsible for lactate assimilation. Additionally, it was speculated that lactate assimilation was required for Candida virulence because Candida must synthesize glucose via gluconeogenesis under glucose-limited conditions such as in the host. Indeed, the Δcyb2 mutant could not grow on lactate medium in which lactate is the sole carbon source in the absence of glucose, indicating that Cyb2p plays a role in lactate assimilation. We hypothesized that Cyb2p-mediated lactate assimilation is necessary for proliferation in the intestinal tract, as the intestine is rich in lactate produced by bacteria flora, but not glucose. The Δcyb2 mutant showed 100-fold decreased adaptation and few cells of Saccharomyces cerevisiae can adapt in mouse ceca. Interestingly, C. glabrata could assimilate lactate under hypoxic conditions, dependent on CYB2, but not yeast S. cerevisiae. Because accessible oxygen is limited in the intestine, the ability for lactate assimilation in hypoxic conditions may provide an advantage for a pathogenic yeast. From those results, we conclude that Cyb2p-mediated lactate assimilation is an intestinal adaptation factor of C. glabrata.
Supporting Data

I don't get this annotation from this paper?

**Comment by addiehl** [comment]
While I don't have time to fully research this area, I found in the following review that various pathogens can cause plant stomata to open and allow entry.  Stomata are natural portals in plant leaves that normally allow gas exchange, and which plants will close in response to danger signals (as also discussed in this paper)
https://www.ncbi.nlm.nih.gov/pubmed/20514224
 
I wonder if the PAMGO people were thinking along these lines when they created this term.
@mgiglio99

**Comment by ValWood** [comment]
I think the current thinking is to make terms for these types of  processes.

So this would be describing some process like

"entry into host via evasion of stomatal defense"
But it seems odd to have "grouping terms" with no instantiated children?

**Comment by ValWood** [comment]
the other side of the arms race here would be "PAMP-triggered stomatal closure"

**Comment by addiehl** [comment]
While I am all in favor of pre-composed specific terms like 'entry into host via evasion of stomatal defense' I guess these two terms allow an annotator to at least distinguish between using an existing host entry point and crossing a physical barrier in the host.

If the terms are retained, the final 's' should be dropped in any case:
entry into host through natural portal
entry into host through host barrier

Then their grouping term-ness is perhaps less highlighted.

**Comment by mgiglio99** [comment]
The example Alex mentions was indeed what PAMGO was going for. And I recently mentioned this stomata opening in github issue #17905  as an example of 'effector-mediated evasion or tolerance of host defense response'. I referenced a different paper: PMID:27359369.
I don't feel strongly about keeping the grouping terms. 
Should we go ahead and make some version of the stomata child term?

**Comment by ValWood** [comment]
We should be careful not to conflate 2 processes here.

i) effectors enter the host and cause the stomata to open (so this is an effector meditated manipulation of the host immune system).
ii) fungal hyphae (possibly other things for other organims) penetrate through the stomata

So the manipulation of the host  defenses to open the stomata is a process upstream of the actual entry through the stomata. I'm not sure which individual gene products would be used to annotate "entry into host through stomata". This seems to be an organism level process. Possibly genes responsible for hyphal formation?  However, if a fungi forms hyphae and cannot make them, then it can't infect the host, so I am not sure yet that I would use a process term as specific as 'entry through natural portals' because it isn't  so relevant to the pathogen process that I am annotating. The mechanism of entry is just a 'feature' of the infective process?

This is a good reason why generally it's best not to pre-empt terms that will be required but add them when needed.  General experience with GO over the years is that when the terms have been added to the ontology when not coupled to a curator request is when the ontology has required to be overhauled later.

In FYPO we don't add terms, or even add grouping term we think might be needed until we  require the sibling terms...consequently, we rarely need to obsolete a term.

**Comment by mgiglio99** [comment]
I wasn't thinking of 'entry into host through stomata' but rather of a new term for 'effector-mediated opening of host stomata' - which could be a child of 'effector-mediated manipulation of host defense response'

**Comment by ValWood** [comment]
Yes, this would make sense!

**Comment by ValWood** [comment]
If you have any examples we would love to curate some of these. I am looking  for examples of  plant effectors where we know how the effector is workling.....
@CuzickA

**Comment by mgiglio99** [comment]
This paper is a nice review - PMID:27359369

**Comment by ValWood** [comment]
Thanks
val

**Comment by ValWood** [comment]
Existing terms will be dealt with by
https://github.com/geneontology/go-ontology/issues/18557

new terms can be requested as required
