### ISSUE TITLE
Do we need this term GO:0044411    entry into host through host barriers

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17984]
GO:0044411    entry into host through host barriers

Definition (GO:0044411 GONUTS page)
Penetration by a symbiont into a host organism via active breaching of the physical barriers of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

Are there any other ways of entering a host?
Is this a useful grouping term?

**Comment by addiehl** [comment]
Isn't this term meant to be in contrast to GO:0051829 entry into host through natural portals ("Penetration by a symbiont into a host organism via naturally occurring openings in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.")?

**Comment by ValWood** [comment]
See 
https://github.com/geneontology/go-ontology/issues/17985

How would you annotate a gene to this term?
I have not found any examples.
Do you know of any?

It seems these grouping terms are a bit surplus/orthogonal  since you can only annotate genes involved in processes.

**Comment by ValWood** [comment]
Does it include for example the phagocytosis machinery? maybe. But is this a necessary grouping term? I don't see how it is very helpful to  classify in this way. It only makes it more difficult to locate the correct term.

**Comment by addiehl** [comment]
There are, for instance, lots of papers on bacterial penetration of mucus:
https://www.google.com/search?client=safari&rls=en&q=bacterial+mucus+penetration&ie=UTF-8&oe=UTF-8

If the main issue is entry into host versus its more specific children, I still am in favor of the specialization.  It strikes me the main problem is lack of annotation effort directed at appropriate gene products that might be annotated to such terms, which is not a fault of the terms, but merely the availability of interest and funding.  Same problem as for immunology.

Might even be appropriate to have a specific term for symbiont penetration of mucus, which is actually pretty important in colonization of the gut, nose, etc. and disease processes (from the perspective of the host, normal process for the pathogen).

**Comment by ValWood** [comment]
So here, we would add

GO:0044411 entry into host via penetration of mucus 

(if there are identified genes involved specifically in this process?)

The terms need to be easily identifiable by curators.

**Comment by ValWood** [comment]
but a membrane  is a host barrier?
So this  grouping term would seem to be applicable to any mechanism of entry?

**Comment by addiehl** [comment]
a mucus layer or mucus membrane is definitely a host barrier.  It's not a membrane in the sense of a plastic sheet, more like a coating.

Here a nice paper about influenza proteins and mucus barriers.
https://www.biorxiv.org/content/biorxiv/early/2019/01/04/512467.full.pdf

**Comment by ValWood** [comment]
I agree that mucus is a host barrier, but isn't a membrane or a cell wall also a host barrier? Therefore any mechanism of entry into a cell  could be grouped under this term. I don't find it easy to know exactly what the grouping term refers to?

**Comment by ValWood** [comment]
This is dealt with
