### ISSUE TITLE
resolution of meiotic recombination intermediates

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#17994]
Hi, 

for PMID 22292001
I need 
regulation of resolution of meiotic recombination intermediates

regulates GO:0000712

resolution of meiotic recombination intermediates is also missing this relationship
is_a GO:0071139

**Comment by ValWood** [comment]
GO:0000712    resolution of meiotic recombination intermediates?

**Comment by mah11** [comment]
yep - GO:0000712 is missing the 'is_a GO:0071139' link

**Comment by Antonialock** [comment]
thought it was weird ! Thanks

**Comment by Antonialock** [comment]
updated descr

**Comment by mah11** [comment]
I think for now we'll just use GO:0000712 for annotations - the paper doesn't provide any data about a regulatory mechanism (although there's a tantalizing possibility, it's untested).

So all we need in the short term here is the missing link GO:0000712 is_a GO:0071139.
