### ISSUE TITLE
GO:0008329    signaling pattern recognition receptor activity (merge + add synonyms)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17995]
I could not locate this.

I was going to use just receptor but then I found 
GO:0008329    signaling pattern recognition receptor activity
by a convoluted route.

Can we add exact synonyms

PAMP receptor
Pathogen associated molecular pattern receptor

I owuld  prefer primary name "PAMP receptor" but  this might require discussion (maybe this name is only most commonly used from the fungal perspective?)

**Comment by hattrill** [comment]
Us flies tend to use 'pattern recognition receptors' (although commonly refer to the ligands as PAMPs). As DAMPs are also in the definition, I think that PRR is probably better for the primary name.

**Comment by ValWood** [comment]
OK agree.
Nobody calls them. 
'signaling' pattern recognition receptors
so this signaling prefix doesn't aid searching
signaling should be part of the definition ( which it is)

"PRR receptor" as primary name because it is in fairly common usage, so this would be fine for me.
@pgaudet what are the rules about abbreviations these days?

**Comment by ValWood** [comment]
Oh
GO:0038187   pattern recognition receptor activity

so what's the difference?

Merge?

**Comment by ValWood** [comment]
his term and its child terms are intended for gene products which are directly coupled to a signal transduction pathway. For pattern recognition receptors which do not relay an intracellular signal (e.g. endocytic pattern recognition receptors), consider instead annotating to 'pattern recognition receptor activity ; GO:0038187' and/or the child terms of 'pattern binding ; GO:0001871'. Note that many gene products that are called pattern recognition receptors in the literature have a broad range of potential ligands and also can be annotated to 'scavenger receptor activity ; GO:0005044'.

I'm not sure what "endocytic pattern recognition" receptors are...

but the comment doesn't really make sense because the parent

pattern recognition receptor activity
pattern recognition receptor activity
Combining with a pathogen-associated molecular pattern (PAMP), a structure conserved among microbial species, or damage-associated molecular pattern (DAMP), an endogenous molecule released from damaged cells), to initiate a change in cell activity.

is defined explicitly to be a microbial PAMP? You would have no clue that this had anything to do with endocytosis?

**Comment by hattrill** [comment]
We have some soluble extracellular factors that bind PAMPs and then trigger an extracellular cascade which then activates a TM receptor which triggers intracellular signaling....

It would be good to clarify whether we want separate terms for membrane receptor type activity (ie transmit signal across membrane) and PAMPs that act upstream of membrane events. Perhaps this is what the original intention was:
-pattern recognition receptor activity
--signaling pattern recognition receptor activity

But the definitions are not helping me here!

**Comment by ValWood** [comment]
pattern recognition receptors
synonym
narrow PAMP receptor
narrow MAMP receptor
narrowmicrobe-associated Molecular patter receptor
exact broad PRR  
DAMP
Damage associated molecular pattern receptor

DAMPS are mentioned in the definition but these are different. 
These are damage-associate receptors that trigger an inflamatory response so should not be in this term
DAMPs include things like  host-produced heat-shock proteins 

Slight modification to the definition for clarity:

Combining with a pathogen-associated molecular pattern (PAMP), a structure conserved among microbial species, or damage-associated molecular pattern (DAMP), an endogenous molecule released from *HOST* damaged cells), to initiate ~a change in cell activity~ *a  innate immune response*.

So this is now quite a general term and should work for most things?

I think from the changes @pgaudet and I did on Friday, this term is now a child of  a new term "innate immune receptor activity" ? is that correct (I don't see this change yet).

**Comment by pgaudet** [comment]
@ValWood 

What about 'Pathogen associated molecular pattern receptor' ? do you still want that as a synonym ?

**Comment by pgaudet** [comment]
@hattrill 

> We have some soluble extracellular factors that bind PAMPs and then trigger an extracellular cascade which then activates a TM receptor which triggers intracellular signaling....

Can you give some examples ?

**Comment by ValWood** [comment]
Oops, yes please....

**Comment by pgaudet** [comment]
I am guessing NARROW

**Comment by ValWood** [comment]
Yup

**Comment by pgaudet** [comment]
Is there another ticket proposing the merge of 

 GO:0038187 pattern recognition receptor activity and 
GO:0008329 signaling pattern recognition receptor activity ? 

or should I keep this one open ?

**Comment by ValWood** [comment]
I think this *is* the ticket for the merge

**Comment by pgaudet** [comment]
Hi @hattrill 
Looking at the wikipedia page, they mention two types of PAMP receptors: membrane-bound PRRs and cytoplasmic PRRs  (https://en.wikipedia.org/wiki/Pattern_recognition_receptor). I also found papers describing extracellular soluble PAMPs (for example PMID:27469378). 

In all cases, they signal to trigger the innate immune response. 

There is no mention of an , soluble . In any case, both are signaling receptors. 

All 5 EXP annotations to     
GO:0038187   pattern recognition receptor activity are membrane-bound PRRs. 

For GO:0008329 signaling pattern recognition receptor activity, at least one annotated protein, human TRIM5 (Q9C035), is intracellular. 

I have not checked the others. 

In any case, the distinction we have now (signaling vs non-signaling) doesn't seem to be relevant.
I know in other places we have the cellular location in the MF term, such as 'transmembrane receptor protein tyrosine kinase activity'; I could create children if we feel this is needed. 

For now I propose to merge 
GO:0008329 signaling pattern recognition receptor activity
into
GO:0038187   pattern recognition receptor activity 

@hattrill @addiehl @mgiglio99 Let me know if you have objections.

Thanks, Pascale

**Comment by pgaudet** [comment]
One more thing. I see from the comment in GO:0008329 
that there are also 'endocytic pattern-recognition receptor'. Those are NOT signaling, so annotating to GO:0038187 would have been also wrong, since this is a child of signaling receptor activity. 

According to https://bio.libretexts.org/Bookshelves/Microbiology/Book%3A_Microbiology_(Kaiser)/Unit_5%3A_Innate_Immunity/11.4%3A_Early_Induced_Innate_Immunity/11.3B%3A_Pattern-Recognition_Receptors_(PRRs)

we probably need those: 
- pattern recognition receptors (PRRs)
- endocytic pattern recognition receptors
- signaling pattern recognition receptors
- danger-associated molecular patterns
- danger recognition receptors

Need to look more closely.

**Comment by ValWood** [comment]
I came across the endocytic thing the other day. I should have noted it in this ticket.
This isn't what I was reading, but it's saying the same thing:
https://link.springer.com/chapter/10.1007/978-3-642-41787-0_9

I think this is just a confusion. The PAMP surface receptors depend on endocytosis.

I haven't come across an endocytic pattern recognition receptor or any review describing one

@CuzickA  have you?

If not I think we should just remove references to endocytosis here.

**Comment by ValWood** [comment]
If we are ferring to the recognition of endocytic cargo
we already have terms for that:
GO:0038024    cargo receptor activity

endocytic receptor activity | narrow
-- | --
I would not call this a PAMP .../pattern recognition receptor

**Comment by ValWood** [comment]
pattern recognition receptor activity are a type of immune receptor
cargo receptors aren't

**Comment by pgaudet** [comment]
OK, going ahead with the merge: 

GO:0008329 signaling pattern recognition receptor activity
into
GO:0038187   pattern recognition receptor activity

**Comment by pgaudet** [comment]
Another question: are we sure that all children are ONLY PRR ? 

'pattern recognition receptor activity'
'lipoarabinomannan receptor activity'
'lipopolysaccharide receptor activity'
'lipoteichoic acid receptor activity'
'peptidoglycan receptor activity'
'polysaccharide receptor activity'
'(1->3)-beta-D-glucan receptor activity'

I will change *their* definitions to from 
"Combining with x and transmitting the signal to initiate a change in cell activity." 
to 
"Combining with x and transmitting the signal to initiate an innate immune response."

Thanks, Pascale

**Comment by ValWood** [comment]
Alayne @CuzickA  found this:
 
'Many pattern-recognition receptors are located on the surface of these cells where they can interact with PAMPs on the surface of microbes. Others PRRs are found within the phagolysosomes of phagocytes where they can interact with PAMPs located within microbes that have been phagocytosed. Some PRRs are found in the cytosol of the cell.'

'There are two functionally different major classes of pattern-recognition receptors: endocytic pattern-recognition receptors and signaling pattern-recognition receptors. '

'Endocytic pattern-recognition receptors, also called phagocytic pattern-recognition receptors, are found on the surface of phagocytes and promote the attachment of microorganisms to phagocytes leading to their subsequent engulfment and destruction.' And they follow up with some examples.

So it seems these do exist!

**Comment by ValWood** [comment]
Re

'pattern recognition receptor activity'
'lipoarabinomannan receptor activity'
'lipopolysaccharide receptor activity'
'lipoteichoic acid receptor activity'
'peptidoglycan receptor activity'
'polysaccharide receptor activity'
'(1->3)-beta-D-glucan receptor activity'

These can definitely occur outside immune signalling.
For  example in yeast in sel-self recoginiton and mating.

I think it will be fine if you  put
'lipoarabinomannan  immune receptor activity"

etc for these terms.
 I am goingto quickly check the list to see if any have been used outside the "immune receptor" context.

**Comment by pgaudet** [comment]
WRT 'lipopolysaccharide receptor activity'
* Mouse ptafr (MGI:106066) annotated from PMID:9013981 - describes signaling response in macrophages -> I would say this is immune response. 
* Human SCARB1 seems to be a cargo receptor for LPS. I'Ll create a new term to describe this. 
@RLovering 

Thanks, Pascale

**Comment by pgaudet** [comment]
Actually @RLovering and I just looked that the paper for SCARB1 and it definitely describes an innate immune response. 
I am adding 'immune receptor' to all those terms.
