### ISSUE TITLE
relationship of plant-type hypersensitive response  to effector triggered immunity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18001]
GO:0009626     plant-type hypersensitive response
 
The rapid, localized death of plant cells in response to invasion by a pathogen.

GO Comments
Note that term is to be used to annotate gene products in the plant. To annotate symbiont gene products that induce the hypersensitive response, consider the biological process term 'modulation by symbiont of host defense-related programmed cell death ; GO:0034053'.

@CuzickA 

How does "effector-triggered immunity" apply to this term?
I have them annotated as analogous. However, I am not sure if effector -triggered immunity is a term used to describe the  symbiont or the host?

**Comment by ValWood** [comment]
@CuzickA 

This wikipedia def confused me:

https://en.wikipedia.org/wiki/Effector-triggered_immunity
Effector-triggered immunity (ETI) is a property of the innate immune system. ETI was first identified in plants[1][2] but has also been identified in animal cells.[3]

The innate immune system is common to all multicellular organisms and forms the first line of defense against pathogens. Infected cells recognize that they are under attack by detecting the pathogen directly through the Pathogen Associated Molecular Patterns (PAMPS) which bind with the Pattern Recognition Receptors (PRR) on the host cells. Host cells also recognize the pathogen through effector-triggered immunity,[4] whereby the host cells are alerted to the pathogen by the associated damage caused by pathogenic toxins or effectors.

=

I thought that "effector -triggered immunity" referred to Hypersensitive response, but it seems not based  on this wikipedia article?
@CuzickA Can you confirm so I can update my model?

It seems that  "effector -triggered immunity" is a 'property' rather than a process. Even so, we should identify the related GO term and apply this as a related synonym for searching because it is  a phrase  your community are likely to use frequently


My current (new) understanding is that PTI and HR are both effector-mediate immunity?
I guess this is the critical question.

**Comment by CuzickA** [comment]
> How does "effector-triggered immunity" apply to this term?
I have them annotated as analogous. However, I am not sure if effector -triggered immunity is a term used to describe the symbiont or the host?

I think this is ok. The pathogen effector is triggering the host immunity. The defense response is happening in the host in response to the pathogen.

**Comment by CuzickA** [comment]
> I thought that "effector -triggered immunity" referred to Hypersensitive response, but it seems not based on this wikipedia article?
@CuzickA Can you confirm so I can update my model?

ETI signaling can induce HR/PCD so we often use HR as a read out for ETI.
For biotrophic pathogens the HR would serve as a defence mechanism kiiling the host cell(s) containing the pathogen.

(Some necrotrophic pathogen hijack this PCD pathway as they colonise dead tissue.)

**Comment by CuzickA** [comment]
> My current (new) understanding is that PTI and HR are both effector-mediate immunity?
I guess this is the critical question.

There is PTI and ETI (common read out HR). There is also probably overlap between PTI and ETI. It would be nice to have clear defs for a PAMP and an effector as there also seems to be overlap here https://github.com/PHI-base/curation/issues/42

**Comment by ValWood** [comment]
OK. 
Thanks this is all really useful. I am making a spreadsheet with resolution and outstnding questions. One quick question and then this ticket can close ( I think). What is PCD?

**Comment by ValWood** [comment]
Summary:  PTI and ETI  pathways both have  HR as a readout (response)

Note: there are a number of assays used to determine HR, I am documenting these.
We still need to address the difference between "PAMP" and "effector". I can see they are different but I can't articulate the difference because they are sometimes used interchangeably.

**Comment by ValWood** [comment]
Summary:  PTI and ETI  pathways both have  HR as a readout (response)

Note: there are a number of assays used to determine HR, I am documenting these.
We still need to address the difference between "PAMP" and "effector". I can see they are different but I can't articulate the difference because they are sometimes used interchangeably.

**Comment by pgaudet** [comment]
Programmed cell death?

Le mar. 15 oct. 2019 à 6:27 PM, Val Wood <notifications@github.com> a
écrit :

**Comment by ValWood** [comment]
yes, thanks!

**Comment by CuzickA** [comment]
> Programmed cell death?

Yes HR is a type of PCD.

> Summary: PTI and ETI pathways both have HR as a readout (response)

This isn't correct.

PTI typically involves MAPK signalling, callose deposition, ROS burst and pathogen-related (antimicrobial) gene expression.
ETI has HR (eg PMID:20601497 if pathogen atr1 allele is recognised by host R (resistance) gene RPP1 allele triggers signal for HR therefore avirulent interaction/ resistance (reduced or no disease) (some pathogen and host strain combinations may not result in recognition therefore virulent interaction disease ensues). 

This may be useful
https://en.wikipedia.org/wiki/Plant_disease_resistance

**Comment by ValWood** [comment]
>Summary: PTI and ETI pathways both have HR as a readout (response)
This isn't correct.

OK I updated my summary.

It seems that the main difference between ETI and PTI ais that 
EIT is triggered by damage or toxins
PTI is triggered by direct recognition of the pathogen ( independently of any damage caused by the toxin or the effector.)

 We can add other differentia , but some things (like ROS bust) appear to be  general  characteristics, but not specific to either pathway.

**Comment by ValWood** [comment]
Closing this. I will open a new clearer ticket.
