### ISSUE TITLE
Logical definition for sperm motility is missing

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#18009]
Need to add logical def.

**Comment by krchristie** [comment]
I know it looks weird that the term `sperm motility` doesn't have a logical def and the term `flagellated sperm motility` does have one that invokes a term called just `sperm` (CL:0000019 ! sperm), so I want to remind you of the history from this ticket:

https://github.com/geneontology/go-ontology/issues/15945 
> The term for 'sperm motility' was created by Paola and myself when we also created the term for 'amoeboid sperm motility' term to make the distinction between that and 'flagellated sperm motility'. If I recall correctly, the existing term for flagellated sperm motility was originally named just 'sperm motility', but was defined such that it was clearly flagellum-dependent, so we opted to keep it as the specific term, consistent with its definition.
> 
> My recollection of the logical def is that the existing CL term for 'sperm' specifies a flagellated sperm, so it seemed sufficient for the logical definition of 'flagellated sperm motility'. I think we discussed whether the CL term for sperm should be changed, but I have vague recollections that we were told CL focuses on mammalian cells, so we didn't attempt to get that changed.
> 
> Here is the CL term for 'sperm':
> http://bioportal.bioontology.org/ontologies/CL?p=classes&conceptid=CL%3A0000019

At the time, we created the term `sperm motility`, Paola and I were not able to figure out how we could make logical definitions for either `sperm motility` or `amoeboid sperm motility` when the CL term is specific to a flagellated sperm so weren't aware of terms we could use to refer to a sperm generally or to an amoeboid sperm.

**Comment by cmungall** [comment]
CL is broader than mammals, but you are right to be cautious about making
assumptions about the exact meaning of classes if it's unclear.

CL is a bit squishy as to whether it pertains to metazoa or broader. We
need to have more TCs in CL so people are not guessing.

I assume GO sperm motility also needs to apply to plants (again: on our
side, we could be more explicit. We have a lack of TCs here so the default
assumption is broadly applicable, but it's always good to be explicit, e.g.
include examples in the definition gloss). So it is unsafe to use the CL
class if it is cryptically more restricted.

Here is how I would suggest approaching issues like this: Just as GO exists
to serve a community, so does the rest of OBO, and that includes serving
GO. If OBO isn't doing a good job in providing the concept GO needs then I
recommend being more pushy. Furthermore, we should be trying to use
biological language consistently, so if GO uses "sperm cell" differently
than CL "sperm cell" this is not good (although we haven't determined it
definitely is different yet)

**Comment by ukemi** [comment]
It is certainly different. In GO, we need to include worm sperm in this class. They are ameboid cells. Opened a ticket here: https://github.com/obophenotype/cell-ontology/issues/587

**Comment by krchristie** [comment]
Remember that we do already have this structure:
-- sperm motility
--- amoeboid sperm motility
--- flagellated sperm motility (has logical def using CL term that is defined as being a flagellated cell, though it is named only as 'sperm'). 

My thinking on plant sperm is that we do not  need to account for sperm motility since they are moved by the pollen tube formation but the plant sperm is not itself motile.

It might be good to push CL on having a structure more like ours, e.g.
-- sperm cell
--- amoeboid sperm cell
--- flagellated sperm cell
--- ?? something for plants ??

**Comment by cmungall** [comment]
I thought some plant sperm cells were motile? E.g
http://www.plantphysiol.org/content/127/4/1500

>

**Comment by ukemi** [comment]
I think I was asked about fern sperm on my qualifying exam. If I recall, they are motile.

**Comment by krchristie** [comment]
Yes, I think it may be the sperm of angiosperms specifically that I am remembering checking on and Paola and I, with input from Tanya, came to the conclusion that we didn't need to represent anything special with respect to sperm motility for this class because the sperm are not actually motile. Other plants do have flagellated sperm, but our existing term for `flagellated sperm motility` is sufficient for any kind of flagellated sperm.

**Comment by krchristie** [comment]
If we proceed with the merge proposed in **merge?: "flagellated sperm motility (GO:0030317)" & "sperm flagellum movement involved in flagellated sperm motility (GO:1905419)" #18070**, then the logical definitions of both terms should be considered to make a new logical def that incorporates everything that should be there.

**Comment by ukemi** [comment]
CL_0011013 (motile sperm cell)
CL_0011014 (non-motile sperm cell)
CL_0011015 (amoeboid sperm cell)
CL_0011016 (flagellated sperm cell)

**Comment by ukemi** [comment]
@krchristie, do you want me to complete this ticket adding the cell types above? Then you can decide on the merge?
I will need to add them to the cell import and then let ontobot run. I don't see them on ontobee, but I assume that they are public.

**Comment by ukemi** [comment]
Or would it be easier for you to take this? It's up to you.

**Comment by krchristie** [comment]
> @krchristie, do you want me to complete this ticket adding the cell types above? Then you can decide on the merge?
> I will need to add them to the cell import and then let ontobot run. I don't see them on ontobee, but I assume that they are public.

Sounds perfect. When you've done the cell import, I'll do the merge.

**Comment by ukemi** [comment]
@balhoff, from where do we pull CL? If I ask for these will they be available?
CL_0011013 (motile sperm cell)
CL_0011014 (non-motile sperm cell)
CL_0011015 (amoeboid sperm cell)
CL_0011016 (flagellated sperm cell)

**Comment by balhoff** [comment]
Currently we use cl-basic because of some conflicts between CL and Uberon: https://github.com/geneontology/go-ontology/blob/18cee120c1b2f2cc32444b13793fcaa7f25b5ee8/src/ontology/Makefile#L391

It should work to request these in the terms file.

**Comment by balhoff** [comment]
@ukemi can you review the pending GO changes due to the currently open CL import? It won't get rebuilt until that is merged or closed: https://github.com/geneontology/go-ontology/pull/17965

**Comment by ukemi** [comment]
They all look ok, except all the anatomical entity inferences. They aren't necessarily wrong, but I thought we wanted to suppress them. My PR for the cell requests is here.

https://github.com/geneontology/go-ontology/pull/18429

**Comment by balhoff** [comment]
I think we should just accept them.

**Comment by ukemi** [comment]
Done.

**Comment by ukemi** [comment]
Note some of these are complexes and bear on this ticket. https://github.com/geneontology/go-ontology/issues/17836
More support of having the spatial relations take center stage in the next phase of projects.

**Comment by ukemi** [comment]
@balhoff, I don't see the new terms in the diff:
https://github.com/geneontology/go-ontology/pull/18431

**Comment by balhoff** [comment]
Oh that's weird. Clearly I haven't fixed the "only changed the date" problem either. Were your terms already in the previously open PR?

**Comment by ukemi** [comment]
I just added them to the text file this morning, so they shouldn't have been. I also just did a pull and I see the SO terms for the other ticket, but not the CL terms for this one.

**Comment by balhoff** [comment]
These IRIs don't exist in the current CL release. Were they just recently created?

**Comment by ukemi** [comment]
Looks like maybe it wasn't merged, but the ticket was closed.
https://github.com/obophenotype/cell-ontology/issues/587

**Comment by ukemi** [comment]
I guess that would explain it.

**Comment by ValWood** [comment]
Done?

**Comment by krchristie** [comment]
> Done?

doesn't look like it, but I'll check more carefully when I have an ontology week.

**Comment by raymond91125** [comment]
Apparently done on 2019-11-05
