### ISSUE TITLE
NTR  meiosis I spindle microtubule depolymerization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18008]
I would like a meiosis I version of this term
(or, minimally spindle microtubule depolymerization)
However the processes are quite different so the specific terms are useful and will conveniently group in the correct chromosome segregation event)

GO:1990755
Ontology	biological_process
Term name
mitotic spindle microtubule depolymerization
Definition
The removal of tubulin heterodimers from one or both ends of a microtubule that is part of the mitotic spindle.

PMID:23770679
Title	Microtubules and Alp7-Alp14 (TACC-TOG) reposition chromosomes before meiotic segregation.

**Comment by pgaudet** [comment]
@ValWood Do you still need this term, or is it one of those that will become MF ?

**Comment by ValWood** [comment]
I'm not sure. I don't think this is the actual polymerase. Let's leave it for now, I can revisit in a subsequent paper.

**Comment by ValWood** [comment]
Closing, we don't want. to add this...
