### ISSUE TITLE
OTR: def, synonyms for GO:2000984 negative regulation of ATP citrate synthase activity 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#18013]
Hi, 
We had a user contact us through Helpdesk about the definition of GO:2000984 negative regulation of ATP citrate synthase activity:

> Please fix an error on GO:2000984.
> It indicates negative regulation of citrate synthase (CS) when actually it is ATP-citrate lyase (ACL).

> Citrate synthase (forms citrate from oxaloacetate and acetylCoA in the mitochondrion with NO ATP involvement) is a different enzyme than ATP-citrate lyase (generates acetylCoA and oxaloacetate with the aid of ATP in the cytosol) and they catalyze different reactions (not the same one). At a glance it may look like they catalyze a bidirectional reaction but actually it is not.

Note, if the term is split or changed, the synonyms may also need to be addressed.  If you need further information from this user (https://biology.ucdavis.edu/people/cecilia-giulivi), I am providing them the ticket URL but don't know if they have a GH- please tag me to email them.

Thanks

**Comment by ukemi** [comment]
This term (GO:2000984) regulates 'ATP citrate synthase' (GO:0003878), which refers to RHEA:21160/EC:2.3.3.8. According to EC, the official IUBMB name for this enzyme is 'ATP citrate synthase' and it is defined as the reaction: ADP + phosphate + acetyl-CoA + oxaloacetate = ATP + citrate + CoA. Note that this reaction does use ATP. An alternative name for the enzyme is 'citrate-ATP lyase', shown as a synonym. 

Note there is a separate enzymatic activity 'citrate synthase activity' (GO:0036440) that corresponds to RHEA:16845 and does not use ATP in the reaction. The reaction is: acetyl-CoA + H2O + oxaloacetate = citrate + CoA + H(+). The enzyme comes in two flavors depending on which side of the oxaloacetate the acetyl group is added.

ping @suzialeksander

**Comment by suzialeksander** [comment]
Thanks @ukemi, I've emailed the user to check if this can be closed.

**Comment by suzialeksander** [comment]
Response: 

> Looks better than before. I'd add that the enzyme in the second paragraph that starts with Note is part of the Krebs' cycle whereas the one described in the first paragraph is not.

>Also, can you clarify this sentence for me, please? "The enzyme comes in two flavors depending on which side of the oxaloacetate the acetyl group is added."

>What flavors you mean? isoforms? different species?

**Comment by ukemi** [comment]
GO:0050450 citrate (Re)-synthase activity: Catalysis of the reaction: acetyl-CoA + H2O + oxaloacetate = citrate + CoA, where the acetyl group is added to the re-face of oxaloacetate; acetyl-CoA provides the two carbon atoms of the pro-R carboxymethyl group. Source: MetaCyc:CITRATE-RE-SYNTHASE-RXN, EC:2.3.3.3, ISBN:0121227073

GO:0004108 citrate (Si)-synthase activity: Catalysis of the reaction: acetyl-CoA + H2O + oxaloacetate = citrate + CoA, where the acetyl group is added to the si-face of oxaloacetate; acetyl-CoA thus provides the two carbon atoms of the pro-S carboxymethyl group. Source: EC:2.3.3.1, ISBN:0121227073

**Comment by suzialeksander** [comment]
Response: 

> Got it.
They are referring to the mammalian vs. others.

Thanks @ukemi
