### ISSUE TITLE
merge: cell-cell signaling involved in quorum sensing (GO:0010699) into its parent term quorum sensing (GO:0009372)

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#18018]
> > One question not on these terms but on related ones - the term 'cell-cell signaling involved in quorum sensing' GO:0010699 as defined doesn't seem much different from its parent 'quorum sensing'. Should this term be be merged into its parent and 'quorum sensing' be made a child of 'cell-cell signaling'? (As GO:0010699 currently is)
> 
> That's a good question. From the original ticket, #17730, discussing the definition of "quorum sensing", I'm copying a quote that I put there:
> 
> from Bassler, Bonnie L (1999). PMID:10607620
> `Quorum sensing, or the control of gene expression in response to cell density, is used by both Gram-negative and Gram-positive bacteria to regulate a variety of physiological functions. In all cases, quorum sensing involves the production and detection of extracellular signalling molecules called autoinducers.`
> 
> Then here's the definition of **cell-cell signaling**:
> `Def: Any process that mediates the transfer of information from one cell to another. This process includes signal transduction in the receiving cell and, where applicable, release of a ligand and any processes that actively facilitate its transport and presentation to the receiving cell. Examples include signaling via soluble ligands, via cell adhesion molecules and via gap junctions.`
> 
> So, for quorum sensing, the definition that we're currently proposing includes the production of the signal, which I was assuming would include the biosynthetic process/pathway for producing the signal. If that's appropriate under **cell-cell signaling**, then it does seem that **quorum sensing** itself should be under **cell-cell signaling**. @ukemi - Do you have any thoughts on whether **quorum sensing** itself should be an is_a child of **cell-cell signaling**?
> 
> > Revised new definition for **quorum sensing** (from #17730): - The process in which single-celled organisms carry out coordinated responses by monitoring their own population density, and often also that of other microbes, **by producing small, diffusible, signal molecules**, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.
> 
> I'll check what annotations have been made directly to '**cell-cell signaling involved in quorum sensing' GO:0010699** and see if they are enlightening.

I think you're right @mgiglio99. I can't see any difference between the term `cell-cell signaling involved in quorum sensing` (GO:0010699) and its parent term `quorum sensing`. In addition, the proposed new definition of `quorum sensing` that we've agreed upon in  **Question: quorum sensing GO:0009372 #17730** seems like it should be a child of `cell-cell signaling`.

I'll open a new ticket to propose merging **`cell-cell signaling involved in quorum sensing GO:0010699`** into `quorum sensing`

_Originally posted by @krchristie in https://github.com/geneontology/go-ontology/issues/17756#issuecomment-543208640_

**Comment by krchristie** [comment]
In **obsolete: interspecies quorum sensing (GO:0052097) & intraspecies quorum sensing (GO:0052100) #17756** , @mgiglio99 made this comment and question: 

> the term 'cell-cell signaling involved in quorum sensing' GO:0010699 as defined doesn't seem much different from its parent 'quorum sensing'. Should this term be be merged into its parent and 'quorum sensing' be made a child of 'cell-cell signaling'? (As GO:0010699 currently is)

I agree with @mgiglio99 that the distinction between `quorum sensing` and `cell-cell signaling involved in quorum sensing` are not particularly well defined. Then, in this ticket: **Question: quorum sensing GO:0009372 #17730**, we agreed upon a revised definition of `quorum sensing` that seems pretty clear that `quorum sensing` meets the description of `cell-cell signaling` (@ukemi - Do you agree?). 

Here are the terms for `quorum sensing`, `cell-cell signaling involved in quorum sensing`, and also for `cell-cell signaling`:

[Term]
id: GO:0009372
**name: quorum sensing**
namespace: biological_process
def: "The process in which single-celled organisms monitor their population density by detecting the concentration of small, diffusible signal molecules produced by the cells themselves." [PMID:15716452, PMID:8288518]
subset: goslim_metagenomics
subset: goslim_pir
synonym: "quorum sensing system" EXACT []
xref: MIPS_funcat:34.11.03.15
xref: Wikipedia:Quorum_sensing
is_a: GO:0044764 ! multi-organism cellular process
**=> Revised new definition:** - The process in which single-celled organisms carry out coordinated responses by monitoring their own population density, and often also that of other microbes, by producing small, diffusible, signal molecules, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.

[Term]
id: GO:0010699
**name: cell-cell signaling involved in quorum sensing**
namespace: biological_process
def: "The cell-cell signaling process in which single-celled organisms monitor population density by detecting the concentration of small diffusible signal molecules." [GOC:dph, GOC:tb]
synonym: "cell-cell signalling involved in quorum sensing" EXACT []
intersection_of: GO:0007267 ! cell-cell signaling
intersection_of: part_of GO:0009372 ! quorum sensing


[Term]
id: GO:0007267
**name: cell-cell signaling**
namespace: biological_process
def: "Any process that mediates the transfer of information from one cell to another. This process includes signal transduction in the receiving cell and, where applicable, release of a ligand and any processes that actively facilitate its transport and presentation to the receiving cell. Examples include signaling via soluble ligands, via cell adhesion molecules and via gap junctions." [GOC:dos, GOC:mah]
subset: goslim_chembl
subset: goslim_generic
subset: goslim_plant
synonym: "cell-cell signalling" EXACT []
is_a: GO:0007154 ! cell communication
is_a: GO:0023052 ! signaling

**Comment by krchristie** [comment]
@ukemi suggested:
> I would always suggest that you make the definition of the genus/differentia standard. If you think the process is a cell-cell signaling, then define it as a cell-cell signaling in which blah blah blah. If you can’t do that, then it is not a cell-cell signaling. In this case, you would probably want to convert the blah blah blah into the cells or contexts in which one cell sends a signal to another cell.

So, applying that principle to the proposed new definition of `quorum sensing` gives this:

**=> Revised new definition: - `quorum sensing`**

The cell-cell signaling process in which single-celled organisms carry out coordinated responses by monitoring their own population density, and often also that of other microbes, by producing small, diffusible, signal molecules, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.

@mgiglio99 - This seems good to me. Does this work for you?

**Comment by mgiglio99** [comment]
Yes, looks good.
: )

**Comment by krchristie** [comment]
@mgiglio99 - Great. I'll go ahead and merge `cell-cell signaling involved in quorum sensing (GO:0010699)` into its parent term `quorum sensing (GO:0009372)` and modify the definition of `quorum sensing` as we've agreed above.
