### ISSUE TITLE
Query about "phosphatidylinositol kinase" terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18016]
This is more of a query than a request at this stage - hope that's OK - somewhat related to #18015.

Is "phosphatidylinositol kinase activity" (GO:0052742) meant to be a grouping term for all types/classes of phosphatidylinositol kinase? It name and definition (Catalysis of the reaction: ATP + a phosphatidylinositol = ADP + a phosphatidylinositol phosphate.) suggest (to me at least) that it is a general grouping term, but it only has these three terms as direct children:
GO:0004430    1-phosphatidylinositol 4-kinase activity
GO:0052810    1-phosphatidylinositol-5-kinase activity
GO:0016303    1-phosphatidylinositol-3-kinase activity

If "phosphatidylinositol kinase activity" is meant to be just for kinases phosphorylating the naked inositol ring (i.e. no existing phosphate group is present), then I think its name/definition needs tightening up, giving the product as "a phosphatidylinositol MONOphosphate".
And if that's the case, it would be very useful to introduce a new parent term that covers all types of phosphatidylinositol kinase, if possible.

If, on the other hand, if "phosphatidylinositol kinase activity" is indeed meant to be a general grouping term for all types of phosphatidylinositol kinase, then these two should also be considered children of it:
phosphatidylinositol phosphate kinase activity (GO:0016307)
phosphatidylinositol bisphosphate kinase activity (GO:0052813)

![Screen Shot 2019-10-17 at 14 29 31](https://user-images.githubusercontent.com/16306861/67013208-a69f9300-f0ea-11e9-956c-a6399654d4dd.png)

**Comment by sjm41** [comment]
@hattrill

**Comment by sjm41** [comment]
I've looked into this some more - also see attached pdf.

I think the reasons for my confusion boil down to:
1. There is currently no overall grouping term for all types of phosphatidylinositol kinase. Although "phosphatidylinositol kinase activity" (GO:0052742) sounds like this is this grouping term, it is actually for specific kinase activity on the naked (as opposed to a mono/bisphosphate) inositol substrate.

2. However, the similarly named and defined "phosphatidylinositol 3-kinase activity" (GO:0035004) **is** used as a grouping term for all 3 types of substrates (naked, monophosphate, bisphosphate), phosphorylated on at position 3. (The extended definition of this term clarifies its meaning.)

3. While "phosphatidylinositol 3-kinase activity (GO:0035004)" exists as a grouping term, there is no equivalent term for "phosphatidylinositol 4-kinase activity" or "phosphatidylinositol 5-kinase activity".


Suggestions:
- add new overall grouping term to group all type of phosphatidylinositol kinase
- add new grouping terms for "phosphatidylinositol 4-kinase activity" and "phosphatidylinositol 5-kinase activity"
- improve term name and definition of current "phosphatidylinositol kinase activity" (GO:0052742) to make it clearer this is specifically for kinase activity on the naked inositol ring.
- clarify the definitions of grouping terms, following the pattern of the definition of "phosphatidylinositol 3-kinase activity" (GO:0035004
- generally, improve consistency of these term names & definitions (see attached rich text file). E.g. consistently use either "1-phosphatidylinositol-" or "phosphatidylinositol-" in term name, consistently put ATP either first or last in the reaction description
- also see ticket #18076 for error report in definition of GO:0052811

[PI_kinases_in_GO.pdf](https://github.com/geneontology/go-ontology/files/3783845/PI_kinases_in_GO.pdf)

**Comment by sjm41** [comment]
Any thoughts on this Harold?

**Comment by sjm41** [comment]
@hdrabkin Given you've just worked on https://github.com/geneontology/go-ontology/issues/18015, do you fancy taking a look at this somewhat related (and similarly aged) ticket?

**Comment by sjm41** [comment]
Hi @pgaudet Would you be able to take a look at this (old) ticket, or should we assign to someone else?

**Comment by pgaudet** [comment]
Obsolete GO:0052812 phosphatidylinositol-3,4-bisphosphate 5-kinase activity, see #25355

**Comment by sjm41** [comment]
@pgaudet Thanks for working on this!  Removing those 3 grouping classes (but keeping GO:0052742 phosphatidylinositol kinase activity) works for me, though I haven't checked the references for those 10 EXP annotations to see if a more specific child term could be used.

As is often the case, there are two possible axes of classification for PIKs:
1. Position on the inositol ring that is phosphorylated (3, 4 or 5)
2. Whether the substrate is PI (ie. un-phophorylated), PI monophosphate or PI bisphosphate.

Fully representing both axes in GO would complicated and is probably unnecessary. Your flattened grouping shown above would certainly simplify things.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms 
* GO:0016307 phosphatidylinositol phosphate kinase activity >> 4 EXP (no EC/RHEA)
* GO:0052813 phosphatidylinositol bisphosphate kinase activity >> 1 EXP (no EC/RHEA)
* GO:0035004 phosphatidylinositol 3-kinase activity >> 5 EXP (no EC/RHEA)
The reason for obsoletion is that these represent unnecessary grouping classes. There are 10 EXP annotations to these terms, 6 InterPro mappings, 5 Reacome and 1 UniRule, see
see https://docs.google.com/spreadsheets/d/1r7TotHEmXHQhsHMrZ6w0sjVL1gRQyzJ-G3dFVWr6Jh4/edit#gid=0

These terms are not present in any subsets. 
REPLACEMENTS: 
* GO:0035004 phosphatidylinositol 3-kinase activity will be replaced by GO:0016303  1-phosphatidylinositol-3-kinase activity (same meaning)l
* GO:0052813 and GO:0016307 will be replaced by the new parent, GO:0052742 phosphatidylinositol kinase activity

Therefore, if your group uses automated replacement of obsolete terms, no action is required. 

Impacted groups: 

Group | Number of annotations 
-- | --
GeneDB | 1
TAIR | 2
dictyBase | 1
BHF-UCL | 1
FlyBase | 2
RGD | 1
SGD | 1
ZFIN | 1


You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/18016

Thanks, Pascale
