### ISSUE TITLE
obsoletion GO:0075171 and similar in response to host branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18010]
regulation of symbiont pathways in response to host should probably be obsoleted 
if not used. 

for example
GO:0075171    regulation of MAP kinase-mediated signal transduction in response to host

No doubt  the MAP kinase stress pathways are activated in response to host defenses but I don't think we have any examples yet  (and we could use the regulation of MAP kinase-mediated signal transduction and precompose the "response to host" part if we did)

**Comment by pgaudet** [comment]
This entire branch*, `GO:0075147 regulation of signal transduction in response to host` and children, has 2 annotations  specifically to `regulation of calcium or calmodulin-mediated signal transduction in response to host` to a single tomato gene (SGN:9783), based on PMID:23621884, which describes resistance to plant pathogens, so the annotations should be moved to 'defense response to bacteria' and 'defense response to fungus'. 

There is no more specific term in the 'immune response' branch describing the calcium signaling, so possibly an annotation to `GO:0019722 calcium-mediated signaling`. If we need a more specific term, I suggest we put it under `immune response-regulating signaling pathway` somehow. 

Descendants of GO:0075147 regulation of signal transduction in response to host` 

'modulation of symbiont adenylate cyclase-mediated signal transduction in response to host'
'negative regulation of G protein-coupled receptor signaling pathway in response to host'
'negative regulation of G-protein alpha subunit-mediated signal transduction in response to host'
'negative regulation of G-protein beta subunit-mediated signal transduction in response to host'
'negative regulation of G-protein gamma subunit-mediated signal transduction in response to host'
'negative regulation of MAP kinase-mediated signal transduction in response to host'
'negative regulation of cAMP-mediated signaling in response to host'
'negative regulation of calcium or calmodulin-mediated signal transduction in response to host'
'negative regulation of protein kinase-mediated signal transduction in response to host'
'negative regulation of receptor-mediated signal transduction in response to host'
'negative regulation of signal transduction in response to host'
'negative regulation of symbiont adenylate cyclase-mediated signal transduction in response to host'
'negative regulation of transmembrane receptor-mediated cAMP signal transduction in response to host'
'negative regulation of transmembrane receptor-mediated signal transduction in response to host'
'positive regulation of G protein-coupled receptor signaling pathway in response to host'
'positive regulation of G-protein alpha subunit-mediated signal transduction in response to host'
'positive regulation of G-protein beta subunit-mediated signal transduction in response to host'
'positive regulation of G-protein gamma subunit-mediated signal transduction in response to host'
'positive regulation of MAP kinase-mediated signal transduction in response to host'
'positive regulation of cAMP-mediated signaling in response to host'
'positive regulation of calcium or calmodulin-mediated signal transduction in response to host'
'positive regulation of receptor-mediated signal transduction in response to host'
'positive regulation of signal transduction in response to host'
'positive regulation of symbiont adenylate cyclase-mediated signal transduction in response to host'
'positive regulation of symbiont protein kinase-mediated signal transduction in response to host'
'positive regulation of transmembrane receptor-mediated cAMP signal transduction in response to host'
'positive regulation of transmembrane receptor-mediated signal transduction in response to host'
'regulation of G protein-coupled receptor signaling pathway in response to host'
'regulation of G-protein alpha subunit-mediated signal transduction in response to host'
'regulation of G-protein beta subunit-mediated signal transduction in response to host'
'regulation of G-protein gamma subunit-mediated signal transduction in response to host'
'regulation of MAP kinase-mediated signal transduction in response to host'
'regulation of cAMP-mediated signaling in response to host'
'regulation of calcium or calmodulin-mediated signal transduction in response to host'
'regulation of protein kinase-mediated signal transduction in response to host'
'regulation of receptor-mediated signal transduction in response to host'
'regulation of transmembrane receptor-mediated cAMP signaling in response to host'
'regulation of transmembrane receptor-mediated signal transduction in response to host'


I think these can all be obsoleted. 

@mgiglio99 @addiehl what do you recommend ? 

Thanks, Pascale

**Comment by mgiglio99** [comment]
I'm ok with obsoleting these since we have no examples. But I wonder if such examples exist in things like nematode and other pathogenic worms.
But we can always resurrect them if needed.

**Comment by genegodbold** [comment]
Fungi and protozoan parasites are people, too! Or, more to the point, eukaryotes with those pathways. But those terms do not spark joy with me so I agree they should be tidied clean away.
