### ISSUE TITLE
gamma catenin binding taxon restriction

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#18019]
Insects do not have gamma catenin, just beta.
Could you put a taxon restriction on for Insecta Taxonomy ID:50557.

Looking at PMC3141441 'The evolutionary history of the catenin gene family during metazoan evolution', looks like this restriction could be extended to non-vertebrates.

Note:
@pgaudet PANTHER:PTN000288612 gamma catenin binding

**Comment by ukemi** [comment]
maybe only in vertebrates, but to be safe for now I will make it never in insects.

**Comment by hattrill** [comment]
Thanks!
