### ISSUE TITLE
R-loop disassembly

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#18012]
Hi GO,
I would need a term to annotate R-loop disassembly
Thanks
Sylvain

Category: Process
Definition:
A R-loop disassembly process that results in the disassembly of R-loops. R-loops are three-stranded nucleic acid structures consisting of an RNA:DNA heteroduplex and a “looped-out” non-template strand. Aberrant formation and persistence of R-loops block transcription elongation and cause DNA damage, mechanisms that resolve R-loops are essential for genome stability.

is_a DNA metabolic process
Part_of GO:0006261 DNA-dependent DNA replication
Xref.
PMID: 28790157

**Comment by sylvainpoux** [comment]
Hi David,
have you progressed on this request? Because I have another protein involved in the same process
Thanks
Sylvain

**Comment by ukemi** [comment]
Sorry Sylvain. This one fell off my radar. I'll do it now.

**Comment by sylvainpoux** [comment]
Thanks!
Sylvain

**Comment by ValWood** [comment]
R-loop disassembly has 2 parents

1) GO:0006259    DNA metabolic process -OK

2) GO:0006261    DNA-dependent DNA replication -needs removing

These are pathogenic legions, obstructions of DNA replication that need removing:

 "are common sites of genome instability: they can trigger DSBs through collisions with the transcription or replication machineries or through active processing by nucleotide excision-repair nucleases "

**Comment by ValWood** [comment]
Also, would. 
"R-loop processing" be a better name for this process (aka DNA double-strand break processing" since these are toxic structures.

This is how they seem to be referred to in publications 
e.g. pombe PMID: 29622660  T. brucie PMID: 34749530  human PMID: 34039990

**Comment by pgaudet** [comment]
Changed the label, and moved under GO:0006338 ! chromatin remodeling

I hope this is right @colinlog 

Thanks, Pascale

**Comment by pgaudet** [comment]
+ added references 
PMID:27252122, PMID:33986538
