### ISSUE TITLE
Logical definitions &Taxon constraints

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18027]
Hello, 

Are LD used to calculate taxon constraints ? 

For example: GO:0005199 structural constituent of cell wall
has LD
'structural molecule activity' and ('occurs in' some 'cell wall')

cell well has TC 'never in metazoa'; this could be inherited by GO:0005199. 

How does it actually work ? 

Thanks, Pascale

**Comment by balhoff** [comment]
Yes logical definitions are used to calculate taxon constraints. This happens mostly through the property chains defined for 'in taxon': http://www.ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002162

But there doesn't seem to be one that uses 'occurs in', so this one isn't being enforced on the . @cmungall are there any reasons not to propagate 'in taxon' over 'occurs in'?

**Comment by cmungall** [comment]
Endosymbionts etc

**Comment by pgaudet** [comment]
But then - endosymbionts are annotated to 'host [structure]' (eg 'host nucleus'), so there is no risk of confusion, is there ?

**Comment by balhoff** [comment]
@cmungall 'occurs in' propagates over 'part of', but not over 'located in'. Would you say an endosymbiont is 'part of' the host, or instead 'located in'? Just wondering if there is a strong enough difference there to make it safe for 'in taxon' to propagate over 'occurs in'.

**Comment by cmungall** [comment]
located-in.

but... See section 3.9.3 of BFO2 reference. The intent is for it to chain
over located-in it seems. So a missing axiom for RO. But yes a stricter
relation would be better for GO

**Comment by vanaukenk** [comment]
578 'occurs in' edges in GO.  How many of the 'occurs in' values have taxon constraints?

One proposal: we could create a stronger relation than 'occurs in' for GO to mean 'occurs in' and is from the same organism.  Using this stronger relation would allow us to propagate the taxon constraint for the physical place where the process 'occurs'.

What would be the implication for GO-CAM modeling?
Proposal: use 'located in' between continuants when they are not from the same species; use 'part of' when the continuants are from the same species.

For specific examples:
GO 'structural constituent of epidermis' -> change 'epidermis' in logical def to be 'skin epidermis' 
BUT....check child term 'structural constituent of cutaneous appendage' to make sure this is all still correct.

GO 'chorion' -> what was the intended use of this term?
Looks to have been intended for insects.  
Proposal: re-name to 'insect chorion' and use the re-named GO term in the logical def of 'structural constituent of chorion'.

General request: it would be very helpful to be able to see all of the taxon constraints in Protege.
How best to do this?
Use a special reasoner in Protege?
There are some technical considerations here.

Fun side project:
Look at all 'structural constituent of x' terms to see if we really still need these in a GO-CAM world.

**Comment by pgaudet** [comment]
I created tickets for epidermis and chorion.

**Comment by pgaudet** [comment]
I will add a taxon constraint for 'GO:0005199 structural constituent of cell wall' 

If @balhoff (or someone else) can do SPARQL query to identify more terms using 'occurs_in' some 'cellular component' where the CC has a taxon constraint, that would be useful to add more taxon constraints. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
Here's a recent, very interesting example of localization of host proteins to endosymbiont CCs:

https://www.ncbi.nlm.nih.gov/pubmed/31587897

**Comment by pgaudet** [comment]
1 | http://purl.obolibrary.org/obo/GO_0001678 | "cellular glucose homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
-- | -- | -- | -- | -- | -- | --
2 | http://purl.obolibrary.org/obo/GO_0006279 | "premeiotic DNA replication"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005634 | "nucleus"@en | http://purl.obolibrary.org/obo/NCBITaxon_2759 | "Eukaryota"^^xsd:string
3 | http://purl.obolibrary.org/obo/GO_0006279 | "premeiotic DNA replication"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005634 | "nucleus"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_2759 | "Eukaryota"^^xsd:string
4 | http://purl.obolibrary.org/obo/GO_0006873 | "cellular ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
5 | http://purl.obolibrary.org/obo/GO_0006874 | "cellular calcium ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
6 | http://purl.obolibrary.org/obo/GO_0006882 | "cellular zinc ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
7 | http://purl.obolibrary.org/obo/GO_0009992 | "cellular water homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
8 | http://purl.obolibrary.org/obo/GO_0010217 | "cellular aluminum ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
9 | http://purl.obolibrary.org/obo/GO_0010961 | "cellular magnesium ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
10 | http://purl.obolibrary.org/obo/GO_0010992 | "ubiquitin recycling"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
11 | http://purl.obolibrary.org/obo/GO_0030002 | "cellular anion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
12 | http://purl.obolibrary.org/obo/GO_0030003 | "cellular cation homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
13 | http://purl.obolibrary.org/obo/GO_0030004 | "cellular monovalent inorganic cation homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
14 | http://purl.obolibrary.org/obo/GO_0030320 | "cellular monovalent inorganic anion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
15 | http://purl.obolibrary.org/obo/GO_0030643 | "cellular phosphate ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
16 | http://purl.obolibrary.org/obo/GO_0033502 | "cellular galactose homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
17 | http://purl.obolibrary.org/obo/GO_0035356 | "cellular triglyceride homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
18 | http://purl.obolibrary.org/obo/GO_0035735 | "intraciliary transport involved in cilium assembly"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005929 | "cilium"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_2759 | "Eukaryota"^^xsd:string
19 | http://purl.obolibrary.org/obo/GO_0035785 | "cellular nickel ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
20 | http://purl.obolibrary.org/obo/GO_0042049 | "cellular acyl-CoA homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
21 | http://purl.obolibrary.org/obo/GO_0046716 | "muscle cell cellular homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
22 | http://purl.obolibrary.org/obo/GO_0051305 | "chromosome movement towards spindle pole"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
23 | http://purl.obolibrary.org/obo/GO_0055082 | "cellular chemical homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
24 | http://purl.obolibrary.org/obo/GO_0072501 | "cellular divalent inorganic anion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
25 | http://purl.obolibrary.org/obo/GO_0072502 | "cellular trivalent inorganic anion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
26 | http://purl.obolibrary.org/obo/GO_0070050 | "neuron cellular homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
27 | http://purl.obolibrary.org/obo/GO_0070219 | "cellular sulfide ion homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
28 | http://purl.obolibrary.org/obo/GO_0090145 | "mitochondrial nucleoid organization involved in mitochondrial fission"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005739 | "mitochondrion"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_2759 | "Eukaryota"^^xsd:string
29 | http://purl.obolibrary.org/obo/GO_0090156 | "cellular sphingolipid homeostasis"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
30 | http://purl.obolibrary.org/obo/GO_0099606 | "microtubule plus-end directed mitotic chromosome migration"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005623 | "cell"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_131567 | "cellular organisms"^^xsd:string
31 | http://purl.obolibrary.org/obo/GO_1902969 | "mitotic DNA replication"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005634 | "nucleus"@en | http://purl.obolibrary.org/obo/NCBITaxon_2759 | "Eukaryota"^^xsd:string
32 | http://purl.obolibrary.org/obo/GO_1902969 | "mitotic DNA replication"^^xsd:string | http://purl.obolibrary.org/obo/GO_0005634 | "nucleus"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_2759 | "Eukaryota"^^xsd:string
33 | http://purl.obolibrary.org/obo/GO_0003009 | "skeletal muscle contraction"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
34 | http://purl.obolibrary.org/obo/GO_0006939 | "smooth muscle contraction"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
35 | http://purl.obolibrary.org/obo/GO_0014734 | "skeletal muscle hypertrophy"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
36 | http://purl.obolibrary.org/obo/GO_0014805 | "smooth muscle adaptation"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
37 | http://purl.obolibrary.org/obo/GO_0014887 | "cardiac muscle adaptation"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
38 | http://purl.obolibrary.org/obo/GO_0014888 | "striated muscle adaptation"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
39 | http://purl.obolibrary.org/obo/GO_0014895 | "smooth muscle hypertrophy"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
40 | http://purl.obolibrary.org/obo/GO_0014897 | "striated muscle hypertrophy"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
41 | http://purl.obolibrary.org/obo/GO_0035765 | "motor neuron precursor migration involved in dorsal motor nucleus of vagus nerve formation"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002028 | "hindbrain"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_89593 | "Craniata <chordata>"^^xsd:string
42 | http://purl.obolibrary.org/obo/GO_0043501 | "skeletal muscle adaptation"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
43 | http://purl.obolibrary.org/obo/GO_0044557 | "relaxation of smooth muscle"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
44 | http://purl.obolibrary.org/obo/GO_0060048 | "cardiac muscle contraction"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
45 | http://purl.obolibrary.org/obo/GO_0055119 | "relaxation of cardiac muscle"^^xsd:string | http://purl.obolibrary.org/obo/UBERON_0002385 | "muscle tissue"^^xsd:string | http://purl.obolibrary.org/obo/NCBITaxon_6072 | "Eumetazoa"^^xsd:string
46 | http://purl.obolibrary.org/obo/GO_0090076 | "relaxation of skeletal muscle"^^xsd:string

**Comment by balhoff** [comment]
@pgaudet are those from my query? The first version had a problem. Here are two better queries:

- only_in_taxon: http://yasgui.org/short/hmuluhqLw
- never_in_taxon: http://yasgui.org/short/8bF235FVK

**Comment by pgaudet** [comment]
@jimhu-tamu Do you need to regenerate the taxon imports ? or does this happen automatically daily?

**Comment by balhoff** [comment]
It happens daily.
