### ISSUE TITLE
NTR: glycosome organization

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#18020]
Can I request a new GO term entry for "glycosome organization" process please?

Accession: GO:xxxxxx
Name: glycosome organization
Ontology: biological_process
Synonyms: glycosome organisation, glycosome biogenesis, glycosome organization and biogenesis
Definition: A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a glycosome, a membrane-bounded organelle found in organisms from the order Kinetoplastida that houses the enzymes of glycolysis.
is_a: GO:0006996 ! organelle organization
Source: GO:0020015, PMID: 2676581, PMID:8056787, PMID:15539076, PMID:28426655, PMID:31341002

Thanks & best wishes,
Achchuthan

**Comment by hdrabkin** [comment]
GO:0106233 done.

**Comment by Achchuthan** [comment]
Thanks a lot @hdrabkin
