### ISSUE TITLE
new taxon constraint GO:0002250 adaptive immune response only in animals/never in plants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18028]
The plant people I am talking to state that plants only have innate immunity.

Therefore can we have a taxon constraint on 
https://www.ebi.ac.uk/QuickGO/term/GO:0002250

GO:0002250    adaptive immune response

do you agree @tberardini

**Comment by cmungall** [comment]
There is another ticket about this somewhere with comments from Alex, I think in the context of CRISPR. Can't search right now..

**Comment by cmungall** [comment]
Oh it was a discussion with you #16298 this wasn't satisfactorily resolved afaicr

**Comment by ValWood** [comment]
THis is slightly different (less contentious).The other ticket discussed whether lower organisms has "immune systems" . I am told that they do, so that's fine.

this is how far the adaptive immune system exists. AFAIK this is "never in" planta, fungi bacteria

@addiehl  is that correct?

https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/plant-immunity
https://www.nature.com/articles/nature05286
https://www.sciencedaily.com/releases/2019/07/190715103305.htm

**Comment by tberardini** [comment]
> do you agree @tberardini
Yup.

**Comment by cmungall** [comment]
On Mon, Oct 21, 2019 at 9:51 AM Alexander Diehl <notifications@github.com>
wrote:

> I think as GO:0002250 is currently defined, it is appropriate to have a
> taxon constraint limiting it to animals.
>
Yep. The question is therefore is it currently labeled too broadly for its
specific definition?

> However, CRISPR and some other systems in bacteria have been termed
> adaptive immune systems (https://www.ncbi.nlm.nih.gov/pubmed/22079134)
> since the bacteria essentially learn the sequences of pathogens and create
> new pathogen sequence specific CRISPR loci. I'm willing to ignore this
> usage for the moment, though some bacteria-centric folk might complain.
>
Have we reached out to them? It's important GO works for everyone and the
terminology doesn't purely reflect mammals

>

**Comment by cmungall** [comment]
Notice that we have lots of IBAs directly to immune response. Surely for an
IBA you would know if it's innate or somatic adaptive?

>

**Comment by cmungall** [comment]
Also 8 direct non-IBA annotations to immune response in plants. We could
use taxon GCIs to infer that these are innate (e.g. immune response and
in-taxon some viridiplantae SubClassOf innate immune response), but a more
straightforward strategy may be do-not-manually-annotate and reannotate to
innate?

**Comment by addiehl** [comment]
In plants we can dictate that all immune responses are innate by nature, and thus enforce a do-not-annotate rule for 'immune response', but because innate immune responses often precede adaptive immune responses in animals (they are not biologically disjoint), depending on the experiment type and granularity of the data, some gp might be annotated directly to 'immune response'.

**Comment by ValWood** [comment]
adaptive immune response is defined
An immune response mediated by cells expressing specific receptors for antigen produced through a somatic diversification process, and allowing for an enhanced secondary response to subsequent exposures to the same antigen (immunological memory).

And I don't think this should change
Even if the bacterial CRISPR could be construed as"adaptive" it is very dissimilar and does not fit this particular def.

And, CRISPR this process already has a term under defense response:
GO:0099048    CRISPR-cas system
with 2 annotations!

I really think we should keep to our def of "adaptive immune response " at least for the time being or it will mess up a whole lot of stuff underneath  (if it ain't broke don't fix it).

So
i) add taxon restriction for only in animals, never in plants
II) ideally add "do not annotate" to "immune response" in plants, but we can't do taxon specific  "do not annotates" right now?
Another option is to make a comment to encourage deeper annotation?. 

 I do believe that when the overhaul is finished it will be easier to see the specific types of immune reponses. At present people are likely to give up give up.
The pathogen -host interaction area of GO is as dogs dinner (note: I'm not referring to @addiehl immune system processes) .

The current terms for pathogenes and hosts andimmune system manipulation are mind-blowingly incomprehensible,  usually multiple  ways to say the same thing, most hidden under obscure grouping terms. This has made the annotation a) minimal and b) totally inconsistent.

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/pull/18052
