### ISSUE TITLE
sync between GO and PO relationships?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#18024]
Is the GO structure of terms containing PO references checked against the PO structure of those terms? I thought this was the case but am seeing discrepancies. Has this been implemented in a similar way as the check for CheBI or is it still in the works?

<img width="459" alt="image" src="https://user-images.githubusercontent.com/4998871/67134463-171be200-f1c7-11e9-9555-843a162bce26.png">

vs.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/4998871/67134428-f81d5000-f1c6-11e9-873d-426083088937.png">

**Comment by balhoff** [comment]
Hi @tberardini yes this works the same as for ChEBI terms. There are PO terms used in logical definitions for these terms in the editor file. For example `'seed development'` is equivalent to `'anatomical structure development'
 and ('results in development of' some seed)`. The PO hierarchy will influence the GO hierarchy. But `'seed development'` is also manually asserted, within GO, to be part of `'fruit development'`. Can you provide some more details on a particular discrepancy to look at?

**Comment by ukemi** [comment]
The part_of relations will not be inferred unless you have recently done something clever. At one point I had envisioned that we would infer a process partonomy from the anatomical partonomy. I think this would be possible, but we would need to think carefully about it.

**Comment by tberardini** [comment]
Thanks @ukemi for the reminder about the part_of.  We're only using the is_a relationships for PO and other anatomy ontologies then, right?

**Comment by balhoff** [comment]
@tberardini we are using pretty much all the relationships; it just depends on how the GO terms are logically defined and whether there are any relevant property chains that come into play.

**Comment by pgaudet** [comment]
Is there an action here?

**Comment by tberardini** [comment]
I guess not.
