### ISSUE TITLE
immune pathways in plants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18033]
IN plants there are 3 main types of immunity (all innate), although some of these likely apply to metazoa too.

A.	
PAMP- triggered immunity (PTI) usually first line of defence
 Upon association with PAMPs, the pattern-recognition receptors activate a downstream mitogen-activated protein kinase signaling cascade that culminates in transcriptional activation and generation of the innate immune responses To interfere with PTI effector proteins that are delivered into and function within the host plant cells

B.	
Second line of defense: Effector-triggered immunity https://en.wikipedia.org/wiki/Effector-triggered_immunity 
The second layer of plant immunity depends on the ability of the plant to recognize these pathogen- derived effectors and trigger a robust resistance response that normally culminates in a hypersensitive cell death response (HR) Effector-triggered immunity is mediated by a large group of structurally related intracellular innate immune receptors encoded by resistance (R) genes.

C.	
systemic immunity
                split into 
                induced systemic resistance 
	        and
                systemic acquired resistance 

We have lots of terms which should  map onto these 3  terms (Or be descendants)
but at the moment they are difficult to locate because they are not arranged in any natural classification.

==
Suggest:

1. 
Need a grouping term for "systemic resistance":
(At the moment these systemic resistance terms have no common term)

2.
This term 
GO:0010204   defense response signaling pathway, resistance gene-independent
should be obsoleted  (or merged into parent term as narrow) because it classifies by what the pathway isn't

It could apply to "systemic immunity" or "PTI"

3.
This term 
GO:0009870    defense response signaling pathway, resistance gene-dependent	
represents
effector-triggered immunity/ effector -triggered immune signalling pathway
and would be better renamed and the definition improved.
I opened a ticket for this:
https://github.com/geneontology/go-ontology/issues/18034

4. 
This is not specific to any pathway and should be a parent of all of the above
GO:0002758    innate immune response-activating signal transduction
and probably renamed 

These are all innate immune signalling pathways and so we should model as we model other signalling in GO
i) signalling
ii) response

I do see some of these terms but they  are spread all over the graph in different branches

**Comment by ValWood** [comment]
Should all of these pathways be referred to as"immune signalling pathways?"

**Comment by ValWood** [comment]
So under "innate immune reponse"

We have these terms:

<img width="940" alt="Screenshot 2019-10-21 at 17 21 32" src="https://user-images.githubusercontent.com/7359272/67223507-4d579c80-f427-11e9-8e92-dcbc5a27045a.png">

**Comment by ValWood** [comment]
Once the above are done


We do want to keep
GO:0002221    pattern recognition receptor signaling pathway
GO:0002220    innate immune response activating cell surface receptor signaling pathway
https://github.com/geneontology/go-ontology/issues/18000#issuecomment-544413101


GO:0002221    pattern recognition receptor signaling pathway
will be a sibling of the above (point 1)

GO:0002220    innate immune response activating cell surface receptor signaling pathway
probasbly needs to merge with the parent, it is a more general gterm

**Comment by ValWood** [comment]
@tberardini ?
How does this sound? Should I tag anyone else?

**Comment by tberardini** [comment]
> Should I tag anyone else?
@cooperl09 @jaiswalp perhaps
