### ISSUE TITLE
OTR: DBD domain binding 

### ISSUE THREAD

**Issue by lpalbou** [geneontology/go-ontology#18047]
I was looking at [DBD domain binding](http://amigo.geneontology.org/amigo/term/GO:0050692) and there is a relation to [Protein binding](http://amigo.geneontology.org/amigo/term/GO:0005515) but not to [DNA binding](http://amigo.geneontology.org/amigo/term/GO:0003677), is that on purpose ? I may misunderstand something but the DBD does bind DNA and not other protein, so could it be a misclassification ?

I found that one in the "other" category with the ribbon and was surprised not to see it under DNA binding:
<img width="1161" alt="Screen Shot 2019-10-23 at 3 18 17 PM" src="https://user-images.githubusercontent.com/24249870/67438453-650a5e80-f5a8-11e9-8b69-61d0ac119a06.png">

In addition, I was looking at the definition ("The DNA binding domain of the vitamin D receptor, one of a family of receptors with the DBD..") and it seems to be very VDR oriented whereas to my knowledge every nuclear receptor has a DBD, including GCRs.

**Comment by cmungall** [comment]
A gene product may bind to the protein domain without binding to DNA?

**Comment by lpalbou** [comment]
I am unsure I understand your question: the dimerization process of nuclear receptors is driven by the LBD, not the DBD, but yes in the dimer, the DBDs of both subunit interacts to shape a binding site able to bind DNA. In that sense you could say there are some protein-protein interactions but the primary/biological role of a DBD is to bind and regulate DNA transcription, not to bind protein.. hence my surprise and why I would first describe a DBD domain as a "DNA binding" rather than a "Protein binding".

**Comment by srengel** [comment]
right.  the DBD domain itself is DNA binding, but something that is 'DBD-domain binding' is binding the DBD domain, which is within a protein, so 'protein binding'.

**Comment by bmeldal** [comment]
While I agree that @lpalbou mixed up the DNA- and protein-binding aspects (see @srengel comment) I do agree that the definition is odd with the specific description of the Vitamin D receptor DBD details. Should that section be removed or added as a comment?

Come to think of, the term name should also be "DBD binding" (= DNA binding domain binding) as "DBD **domain** binding" = DNA binding domain **domain** binding.

New ticket or change title?

**Comment by krchristie** [comment]
> While I agree that @lpalbou mixed up the DNA- and protein-binding aspects (see @srengel comment) I do agree that the definition is odd with the specific description of the Vitamin D receptor DBD details. Should that section be removed or added as a comment?

It seems to me that the Vitamin D receptor details should just be removed.
 
> Come to think of, the term name should also be "DBD binding" (= DNA binding domain binding) as "DBD **domain** binding" = DNA binding domain **domain** binding.

Perhaps the title should be spelled out as "DNA binding domain binding", with "DBD binding" as a synonym?

> New ticket or change title?

I think we could just change the title.

**Comment by bmeldal** [comment]
Go ahead, @krchristie :)

**Comment by krchristie** [comment]
@ukemi - Since I happened to read through this ticket and it seemed very simple, I just took it to save anyone else the time of reading through it.

**Comment by lpalbou** [comment]
Thanks for the clarification !
