### ISSUE TITLE
induction by symbiont of host immune system

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18043]
<img width="879" alt="Screenshot 2019-10-23 at 06 53 03" src="https://user-images.githubusercontent.com/7359272/67364701-fd342380-f567-11e9-95cf-a8f977deffde.png">

1. I don't see a difference between  "induction" and positive regulation?
2. I don't see a difference between modulation and regulation
3. Modification of...here is weird (but will become "mitigation?"
3. the term response to host response is a bit clunky and I wonder if this is necessary as a parent. I can see numerous problems with this  (can discuss on Friday).
4. Why is interaction with host a child of "response to host" ? that looks odd?

I think 1&2 will be covered by other tickets. I just think this is a nice example for a before and after screen shot ;)

**Comment by pgaudet** [comment]
@mgiglio99 Are you OK to merge 'positive regulation' into induction for all the symbiont terms ?

**Comment by addiehl** [comment]
I think the induction terms were created to cover the first step involved, whereas positive regulation involves any step that positively regulates an immune response.

However, these terms are inherently problematic as they potentially could apply to any antigenic protein produced by a symbiont, which is not an active process on the symbiont side, and a pointless GO annotation to make, as there are specialist databases, such as the Immune Epitope Database that capture this type of information more effectively.  Evolutionary selection favors avoidance of inducing an immune response.

The only situation where I can see a sensible GO annotation may be in the case of commensal bacteria/microbiota that produce proteins that may direct the immune response into a biased type of immune response, such as a type I or type II immune response, that favors maintaining the commensal relationship.

**Comment by pgaudet** [comment]
This is what I did so far: 


Term |   | Merge into |   |  
-- | -- | -- | -- | --
GO:0052533 positive   regulation by symbiont of host induced systemic resistance | 0 annotations | GO_0052103 | induction by symbiont of host   induced systemic resistance | 0 annotations
GO:0052166 positive   regulation by symbiont of host innate immune response | GO_0052390 | induction by symbiont of host   innate immune response | 0 annotations
GO:0052556 positive regulation by   symbiont of host immune response | 12 anno | GO_0052559 | induction by symbiont of host   immune response | 6 annotations
GO:0052347   positive regulation by symbiont of defense-related host nitric oxide   production | 3 annot | GO_0052063 | induction by symbiont of   defense-related host nitric oxide production | 0 annotations

**Comment by pgaudet** [comment]
Term |   | Merge into |   |  
-- | -- | -- | -- | --
GO:0052369   positive regulation by symbiont of defense-related host reactive oxygen   species production | 2 annotations | GO:0052064 | induction by symbiont of   defense-related host reactive oxygen species production | 4 annotations
GO:0052389   positive regulation by symbiont of defense-related host calcium ion flux | 0 annotations | GO_0052391 | induction by symbiont of   defense-related host calcium ion flux |  
GO:0052539   positive regulation by symbiont of defense-related host cell wall thickening | 0 annotations | GO_0052105 | induction by symbiont of   defense-related host cell wall thickening | 0 annotations
GO:0052509   positive regulation by symbiont of host defense response | 1 EXP | GO_0044416 | induction by symbiont of host   defense response | 12 EXP
GO:0052527   positive regulation by symbiont of host resistance gene-dependent defense   response | 3 EXP | GO_0052101 | induction by symbiont of host   resistance gene-dependent defense response | 1 EXP
GO:0052537   positive regulation by symbiont of host systemic acquired resistance | 0 annotations | GO_0052104 | induction by symbiont of host   systemic acquired resistance | 0 annotations
  |   |   |   |  
GO:0052109   positive regulation by symbiont of defense-related host cell wall callose   deposition | 0 annotations | Change label to 'induction by   symbiont of defense-related host cell wall callose deposition' |   |

**Comment by pgaudet** [comment]
Probably there are more terms to be merged - but I'll close this for now.
