### ISSUE TITLE
GO:0017082 'obsolete mineralocorticoid receptor activity', error in comment

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#18050]
Hi, 
GO:0017082 'obsolete mineralocorticoid receptor activity'
has the comment
"This term was obsoleted because it represents a gene product, see https://github.com/geneontology/go-ontology/issues/16733"
(https://www.ebi.ac.uk/QuickGO/term/GO:0017082).
But that ticket refers to a different term. The right ticket seems to be https://github.com/geneontology/go-ontology/issues/16732.
Also, in the ticket a term to be considered instead of the obsolete one is indicated, but this is not found in the ontology entry for the obsolete term. Just curious, is the current policy to simply add a link to the GitHub ticket? 
Thanks,
Paola

**Comment by pgaudet** [comment]
Hi Paola, 

Thanks for reporting this. I edited the comment on both terms that were obsoleted from #16732.

As far as policy goes: We are planning to have some kind of private GO editors note, but I have been linking tickets for much of the work I do (it makes it easier to track decisions). 

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
Thank you @pgaudet .
