### ISSUE TITLE
Term merge: "detection of cell density by secreted molecule" into "quorum sensing" ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18061]
*  GO:0009372    quorum sensing
Def: The process in which single-celled organisms monitor their population density by detecting the concentration of small, diffusible signal molecules produced by the cells themselves. 

*  GO:0060247     detection of cell density by secreted molecule
Def: The series of events in which information about the density of cells in a population is received by the detection of a secreted molecule and is converted into a molecular signal.
The latter term has no annotations. 

Is there really a difference ? 

@krchristie I know you were looking at quorum sensing recently - do you want to take this one ? 

Thanks, Pascale

**Comment by krchristie** [comment]
As I alluded to in  **term merges related to contact inhibition #18064**, I agree that 
`detection of cell density by secreted molecule (GO:0060247)` is the same thing as `quorum sensing (GO:0009372)`, so I plan to merge ` detection of cell density by secreted molecule (GO:0060247)` into `quorum sensing (GO:0009372)`, and then make `quorum sensing` into a direct child of `detection of cell density`.
