### ISSUE TITLE
GO 'chorion' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18078]
From discussion in #18027

The 'chorion' used in GO terms (or at least 'structural constituent of chorion') refers to insect chorion, which is different from reptilian, bird and mammalian chorion (the outermost membrane surrounding an embryo of a reptile, bird, or mammal. In mammals it contributes to the formation of the placenta.). 

Proposal: re-name to 'insect chorion' and use the re-named GO term in the logical def of 'structural constituent of chorion'.

Thanks, Pascale

**Comment by ukemi** [comment]
What about teleosts?

**Comment by ukemi** [comment]
I'll fix these up in the other ticket.
