### ISSUE TITLE
Do we need this distinction symbiotic /parasitic?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18073]
GO:0009603    detection of symbiotic fungus 
GO:0009623    response to parasitic fungus

**Comment by pgaudet** [comment]
I will merge 

response to symbiotic fungus
response to parasitic fungus

into response to fungus

(detection is handled by another ticket, #18098)

Thanks, Pascale

**Comment by pgaudet** [comment]
First it'd be good to check annotations: 
https://docs.google.com/spreadsheets/d/1nSzu7HhDGBcCnENOx-nPpw4nYtEr9J-K-GlaFGAQmCk/edit#gid=0

**Comment by pgaudet** [comment]
Useful review 
https://www.nature.com/articles/nrmicro2990

**Comment by pgaudet** [comment]
Decision 
Merged: 
- GO:0016047  detection of parasitic fungus
into detection of fungus

- GO:0009623 response to parasitic fungus
into defense response to fungus

I will open a new ticket for symbiotic processes. 

Thanks, Pascale

**Comment by pgaudet** [comment]
New ticket: #18342 18342
