### ISSUE TITLE
taxon restriction  neurofilament bundle assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18079]
only _in  meazoa?
GO:0033693    neurofilament bundle assembly

**Comment by ValWood** [comment]
GO:0052000
Term name | type IV pili-dependent aggregation

only in prokaryotes?

**Comment by krchristie** [comment]
> GO:0052000
> Term name | type IV pili-dependent aggregation
> The formation of bacterial aggregates in liquid culture dependent on the presence of type IV pili.
> 
> only in prokaryotes?

The type IV pili might also be in Archaea, as the Archeael type flagellum is related to bacterial type IV pilins:

**archaeal-type flagellum (GO:0097589)
Def:** A non-membrane-bounded organelle superficially similar to a bacterial-type flagellum; they both consist of filaments extending outside the cell, and rotate to propel the cell, but the archaeal flagella (also called archaella) have a unique structure which lacks a central channel. Similar to bacterial type IV pilins, the archaeal flagellins (archaellins) are made with class 3 signal peptides and they are processed by a type IV prepilin peptidase-like enzyme. The archaellins are typically modified by the addition of N-linked glycans which are necessary for proper assembly and/or function.

**Comment by pgaudet** [comment]
Yes, taxon constrains should be fixed: 
https://www.frontiersin.org/articles/10.3389/fmicb.2015.00190/full

Thanks, Pascale

**Comment by hdrabkin** [comment]
so only in prokaryote (includes archaea and eubacteria).?

**Comment by krchristie** [comment]
> so only in prokaryote (includes archaea and eubacteria).?

Yes, I think that's correct that prokaryote includes archaea and eubacteria.

I think I was looking at the definition of `type IV pili-dependent aggregation` which specifies "bacterial":
Def: The formation of **bacterial** aggregates in liquid culture dependent on the presence of type IV pili. aggregates in liquid culture dependent on the presence of type IV pili.

**Comment by hdrabkin** [comment]
done
