### ISSUE TITLE
NTR: hydroxyisourate hydrolase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#18075]
I need the corresponding complex term to this activity:
GO:0033971 hydroxyisourate hydrolase activity

Name: hydroxyisourate hydrolase complex
Def: A hydrolase complex that converts 5-hydroxyisourate (HIU) to 2-oxo-4-hydroxy-4-carboxy-5-ureidoimidazoline. This is the second step of the three-step enzymatic reaction that degrades uric acid to (S)-allantoin. 

Synonyms:
HIUH complex [NARROW]
HIU hydrolase complex [NARROW]
5-hydroxyisourate hydrolase complex [NARROW]

Relationships:
is_a  GO:1902494 catalytic complex
part_of GO:0005737 cytoplasm
capable_of GO:0033971 hydroxyisourate hydrolase activity
capable_of_part_of GO:0006144 purine nucleobase metabolic process (it should be **catabolic** process but the child doesn't exist)

Note to self: EBI-21944901 / CPX-4581

**Comment by hdrabkin** [comment]
Hi @bmeldal 
Do you have a PMID for the def?

**Comment by bmeldal** [comment]
Doh, I knew something was missing...!

PMID:21795808
GOID:bhm

**Comment by hdrabkin** [comment]
I was hoping you'd see this as I didn't see it until I created the term!  It's in waiting on Travis...
