### ISSUE TITLE
obsolete precomposed defense response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18071]
GO:1901244    
positive regulation of transcription from RNA polymerase II promoter involved in defense response to fungus

**Comment by pgaudet** [comment]
Annotation review ticket: 
https://docs.google.com/spreadsheets/d/11gOZhc75774IBCOA9mkK7narKWgls-u2P0SOFV55jiU/edit#gid=0

1 WormBase annotation @vanaukenk 
7 UniProt also disputed in P2GO  @pgarmiri

**Comment by pgarmiri** [comment]
The UniProt annotations have been checked and changed.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:1901244 positive regulation of transcription from RNA polymerase II promoter involved in defense response to fungus. 


The reason for obsoletion is that this term represents a GO-CAM model. 

Annotations have mostly been removed (one wormbase annotation left). 

There are no mappings to this term. This term is not present in any subset(s).

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/18071

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 11th, 2019. Unless objections are received by November 11th, we will assume that you agree to this change.

Thanks, Pascale
