### ISSUE TITLE
merge "flagellated sperm motility (GO:0030317)" & "sperm flagellum movement involved in flagellated sperm motility (GO:1905419)"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#18070]
Although @paolaroncaglia and I are responsible for the `GO:1905419 - sperm flagellum movement involved in flagellated sperm motility` term, I doubt that these are actually different processes (or distinguishable by annotators). Anything that moves the sperm flagellum will move the sperm and any processes or functions that regulate motility of the sperm are acting by regulating movement of the flagellum. I think `sperm flagellum movement involved in flagellated sperm motility (GO:1905419)` should be merged into `flagellated sperm motility (GO:0030317)`

> [Term]
> id: GO:0030317
> name: flagellated sperm motility
> namespace: biological_process
> def: "Any process involved in the controlled movement of a flagellated sperm cell." [GOC:cilia, GOC:jl, GOC:krc]
> is_a: GO:0060285 ! cilium-dependent cell motility
> is_a: GO:0097722 ! sperm motility
> intersection_of: GO:0006928 ! movement of cell or subcellular component
> intersection_of: has_input CL:0000019 ! sperm
> 
> [Term]
> id: GO:1905419
> name: sperm flagellum movement involved in flagellated sperm motility
> namespace: biological_process
> def: "The directed, self-propelled movement of a cilium (aka flagellum) that contributes to the movement of a flagellated sperm." [GO_REF:0000060, GOC:cilia, GOC:krc, GOC:TermGenie, PMID:26680031]
> intersection_of: GO:0003341 ! cilium movement
> intersection_of: part_of GO:0030317 ! flagellated sperm motility
> created_by: krc
> creation_date: 2016-09-01T17:52:39Z

Regarding the ticket for **Logical definition for sperm motility is missing #18009**, if we proceed with this proposed merge, then the logical definitions of both terms should be considered to make a new logical def that incorporates everything that should be there. 

There are barely any annotations to `sperm flagellum movement (GO:0030317) involved in flagellated sperm motility (GO:1905419)"`. 

GO Term | IDA | IEP | IGI | IMP | NAS | TAS | ISA | ISO | ISS | IBA | IEA | Grand Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
flagellated sperm motility | 9 | 2 | 8 | 107 | 1 | 2 | 3 | 106 | 87 | 127 | 200 | 652
negative regulation of   flagellated sperm motility | 2 |   |   | 2 |   |   |   | 5 |   |   | 4 | 13
positive regulation of   flagellated sperm motility | 4 |   |   | 7 | 1 |   |   | 14 | 9 | 91 | 9 | 135
positive regulation of   flagellated sperm motility involved in capacitation | 2 |   |   | 3 |   |   |   | 6 | 25 |   | 13 | 49
regulation of flagellated   sperm motility | 2 |   |   | 2 |   |   |   | 3 | 3 | 16 |   | 26
sperm flagellum movement   involved in flagellated sperm motility |   |   |   | 3 |   |   |   | 3 |   |   | 12 | 18
sperm axoneme assembly |   | 2 | 6 | 44 |   |   |   | 27 | 12 | 42 | 53 | 186

**Comment by paolaroncaglia** [comment]
Hi @krchristie,
I trust your judgement completely. Thank you!
Paola

**Comment by pgaudet** [comment]
Sounds good !

**Comment by krchristie** [comment]
If we merge the flagellum motility terms, I think we'd need to also merge `GO:0060294 - cilium movement involved in cell motility` into `GO:0060285 - cilium-dependent cell motility` also.

I haven't looked at the annotations yet.

**Comment by pgaudet** [comment]
Sounds reasonable, but maybe it should be done as a separate ticket ?

**Comment by krchristie** [comment]
> Sounds reasonable, but maybe it should be done as a separate ticket ?

Yes, I agree. I wanted to make sure I didn't forget about the parallel cilium terms.

**Comment by krchristie** [comment]
consider if I can make a better equivalence axiom that incorporates everything I need instead of manually asserting relationship that is missing after merge.

**Comment by krchristie** [comment]
For now, I went ahead and committed my pull request to directly assert that 'flagellated sperm motility' is a SubClassOf 'cilium movement involved in cell motility' so that it will have this parentage as well the 'cilium-dependent cell motility' parentage, but I think it would be better to see if there is a way to combine all of this into the equivalence axiom.

Here are some relevant equivalent axioms:

**flagellated sperm motility**:
`'cilium-dependent cell motility'
 and ('results in movement of' some sperm)`

**cilium movement involved in cell motility**
`'cilium movement'
 and ('part of' some 'cell motility')`

**sperm flagellum movement involved in flagellated sperm motility** [prior to merge]
`'cilium movement' and part_of 'flagellated sperm motility'`

**Comment by krchristie** [comment]
@cmungall - Below is what I have currently have in the ontology for the Equivalence Axiom and additional SubClass relationships for the term `flagellated sperm motility`. When we had the separate term for `sperm flagellum movement involved in flagellated sperm motility`, it wasn't necessary to assert this directly, but as was discussed earlier in this ticket, I don't think there's any real difference between `sperm flagellum movement involved in flagellated sperm motility` and `flagellated sperm motility`.

 Let me know If there's a good way to get all of the appropriate relationships as part of the equivalence axiom.

![flagellatedSpermMotility-EA-SC-20200720](https://user-images.githubusercontent.com/10533218/87987883-3a482a80-ca94-11ea-8b28-6cbcdf947a5c.png)

Thanks,

-Karen

**Comment by pgaudet** [comment]
These have been merged
