### ISSUE TITLE
missing parentage: dol-P-Man:Man(5)GlcNAc(2)-PP-Dol alpha-1,3-mannosyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18081]
dol-P-Man:Man(5)GlcNAc(2)-PP-Dol alpha-1,3-mannosyltransferase activity

seems that it should be a descendant of:

dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity

?

**Comment by hdrabkin** [comment]
Your suggested parent term's EC id has been split into 4 reactions
ENZYME entry: EC 2.4.1.130 has been split:
Transferred entry: 2.4.1.258   <<<<<<< This is the dol-P-Man:Man(5)GlcNAc(2)-PP etc term.
Transferred entry: 2.4.1.259
Transferred entry: 2.4.1.260
Transferred entry: 2.4.1.261

However, it may need to be obsoleted as apparently EC (or rhea)  no longer thinks it exists. 
The comments field:This term represents EC 2.4.1.130 and was too unspecific and covered several different enzymes with non-overlapping catalytic activities. Consider one of the following: GO:0052925, GO:0052926, GO:0052917 or GO:0052918. GO:0004584 is scheduled for obsoletion.

However there are 77 manual annotations; they may need to be rehoused?

**Comment by ukemi** [comment]
Thanks @hdrabkin. The annotations should be reviewed. Can you open a review request on the annotation tracker and link it to this ticket?

**Comment by ValWood** [comment]
I have 3 of these 

one is

alpha 1,2 mannosyltransferase required for addition of the third mannose onto the glycosylphosphatidylinositol (GPI) core structure (gpi10)
ISS from https://www.yeastgenome.org/locus/YGL142C#go

but that doesn't seem to be one of the ECs above?

**Comment by ValWood** [comment]
And the one for the second mannose.
Seem to be annotated to 
dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase 
in yeast and human, but aren't one of the 4 EC's above...

**Comment by hdrabkin** [comment]
I would need the exact reaction these annotations are referencing (NOT the generic GO Term Def) to see if I can get a RHEA. 
The thing is that those annotations may not have been using the correct term to begin with?

**Comment by hdrabkin** [comment]
Ignoring the EC
the 'alpha 1,2 mannosyltransferase" could be rehoused to alpha-1,2-mannosyltransferase? GO:0000026

**Comment by ValWood** [comment]
GPI10
Transfers the third mannose to Man2-GlcN-acyl-PI during GPI precursor assembly
https://www.ncbi.nlm.nih.gov/pubmed/9576863

**Comment by hdrabkin** [comment]
I tried seeing if I could get help 'rephrasing" the orginal term from RHEA:
'Such a reaction does not exist. The problem would be how to define 'a membrane
    lipid-linked oligosaccharide. As the definition of the compound is indeed very
    vague, it would be impossible to create a structure of the substrate and the
    product which is a prerequisite to create a Rhea reaction. We cannot even
    create the oligosaccharide as a polymer as the mannose units can be added to
    several positions.'

**Comment by pgaudet** [comment]
Did the term get obsoleted in the end ?

**Comment by hdrabkin** [comment]
No; annotations need to be checked and rehoused first.

**Comment by pgaudet** [comment]
So this should still be open ?
