### ISSUE TITLE
New term request: outer membrane protein complex

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-ontology#18086]
Ontology: cellular component
Definition: any protein complex that is part of the cell outer membrane

A protein complex formed by the RcsF lipoprotein and outer membrane beta-barrel proteins in E. coli was characterized by Konolova et al PMIDs 25267629 and 27282389. The complex plays a role in sensing envelope stress. 

Thank you
Amanda Mackie
EcoCyc curator

**Comment by pgaudet** [comment]
Isn't this a localization ?

**Comment by amandamackie** [comment]
No my wording may have been misleading. RcsF-OMP is the complex that sits in the outer membrane of the cell, it is a stress-sensing complex. The biological process term for this complex is 'response to envelope stress'; I require a cellular component term for it.

Amanda

**Comment by pgaudet** [comment]
How about something more precise like 'RcsF-Bam' complex? 
And use the second part of your definition, 'A protein complex formed by the RcsF lipoprotein and outer membrane beta-barrel proteins' 

?

**Comment by hdrabkin** [comment]
Does RcsF-OMP refer to the gene names?

**Comment by amandamackie** [comment]
Yes, _rcsF_ encodes an outer membrane lipoprotein (RcsF); it forms a complex in the outer membrane with any one of several outer membrane beta-barrel proteins (OMPs). RcsF-OmpA, RcsF-OmpF and  RcsF-OmpC complexes are described in PMID 25267629. 

Term: RcsF-OMP complex
Definition: A bacterial outer membrane protein complex consisting of the RcsF lipoprotein and any one of a number of outer membrane beta-barrel proteins (OMPs)

I'm guessing that we would still need a new term for 'outer membrane protein complex' though, as it would be the parent term.

**Comment by pgaudet** [comment]
> I'm guessing that we would still need a new term for 'outer membrane protein complex' though, as it would be the parent term.

We could - but we haven't done that systematically for other localizations - for example there is no 'nuclear protein-containing complex'. This has been annotated separately. 
However if the complex is always nuclear, them sometimes this is captured in the name and the definition. 

@ukemi Do we have guidelines for this ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
My hesitance with this is that the suggested term name is specifically using gene product names.  However, the originally requested term name has a def referring to specific gene products.

**Comment by pgaudet** [comment]
Well now we have terms like 

GO:0070531 BRCA1-A complex
GO:0070532 BRCA1-B complex
GO:0070533 BRCA1-C complex
GO:0070767 BRCA1-Rad51 complex


etc... Maybe they should go ? 

My point is just having  'x-component protein-containing complex' sets a precedent that I am not sure we want ? 

Pascale

**Comment by hdrabkin** [comment]
I wasn't even thinking that far ahead.

**Comment by ValWood** [comment]
But people often name complexes after one of the components?

**Comment by amandamackie** [comment]
For context, I made the term request because I needed a cellular component annotation for <i>rcsF<i> in EcoCyc. 
The CC term GO:0032991 protein-containing complex, has child terms for membrane protein complex, ER membrane protein complex, inner and outer mitochondrial membrane protein complex, nuclear membrane protein complex etc. but it does not have a term for outer membrane protein complex.

**Comment by hdrabkin** [comment]
But it appears you want a type of protein containing complex, which is fine but then you define it with specific gene names, so it's not as generic as the term name implies.
I notice ER membrane protein complex def is "Any protein complex that is part of the inner mitochondrial membrane." 

So maybe "Any protein complex that is part of the bacterial outer membrane. In E.coli, this is RcsF associated  with any one of several outer membrane beta-barrel proteins (OMPs), such as OmpA, OmpF, or OmpcC. 
Would this work?

**Comment by amandamackie** [comment]
Yes definitely; we seem to have come full circle. My original request (which can be seen at the start of this thread) was for that exact term (ie. outer membrane protein complex) and definition.

**Comment by hdrabkin** [comment]
+id: GO:0106234
+name: outer membrane protein complex
