### ISSUE TITLE
Obsolete ununsed GOREL

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18087]
* GOREL:0000030 modified_by  -  0 annotation extensions
* ~has_part~ need to first look at children

**Comment by pgaudet** [comment]
* GOREL:0001000 axis_of -  0 annotation extensions

**Comment by ukemi** [comment]
But this is used in chain relations for processes establishing polarity. I bet we have used that in AEs.

**Comment by pgaudet** [comment]
We have used 'has_output_o_axis_of'

**Comment by ukemi** [comment]
So don't we need the primitives? @cmungall or @balhoff?
