### ISSUE TITLE
hyphal growth ?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18118]
hyphal growth
Growth of fungi as threadlike, tubular structures that may contain multiple nuclei and may or may not be divided internally by septa, or cross-walls.

 formation of symbiont invasive hypha in host
Definition | The assembly by the symbiont of a threadlike, tubular structure, which may contain multiple nuclei and may or may not be divided internally by septa or cross-walls, for the purpose of invasive growth within its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

 formation of symbiont invasive hypha in host
seems to be describing  "invasive hyphal growth"?

should this be a synonym?
should  this be a child of
hyphal growth?

formation of hyphae is "growth of hyphae" (assembly seems an odd wording?)

**Comment by pgaudet** [comment]
@mgiglio99 what do you think ?

**Comment by ValWood** [comment]
assembly sounds weird too. it doesn't really assemble... it grows by extension...

**Comment by ukemi** [comment]
Is there an action here?

**Comment by mgiglio99** [comment]
I suggest keeping 'formation of symbiont invasive hypha in host' (and renaming would be fine) where it is and adding the second parent 'hyphal growth'

**Comment by ValWood** [comment]
@mgiglio99  sounds right.

**Comment by pgaudet** [comment]
- [x] added parent 'hyphal growth'
 - [x] changed term label to 'invasive hyphal growth' 
 - [x] changed term labels for regulation terms.
