### ISSUE TITLE
Merge: "GO:0002818 intracellular defense response" into GO:0006968 cellular defense response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18111]
I am  checking a paper  about an extracellular protease  inhibitor which  inhibits extracellular plant proteases.
PMID:15096512

@CuzickA  has found "intracellular defense response" (a new one to me)
and hence sugggested "extracellular defense response"

We could just  do

 serine-type peptidase inhibitor activity
part_of "defense response" occurs_in  extracellular space

but in this case I would object to "intracellular defense response"  as a term.

Suggestions?

**Comment by ValWood** [comment]
For the same paper @CuzickA  has also used


GO:0052054 | negative regulation by symbiont of host peptidase activity

which is totally correct but does not really match "modern GO-CAM annotation"

Should this term exist?

**Comment by pgaudet** [comment]
> but does not really match "modern GO-CAM annotation"

Why not ?

**Comment by ValWood** [comment]
because
MF serine-type peptidase inhibitor activity
part_of  BP "defense response"

means the same?
2 ways to say the same thing?

**Comment by ValWood** [comment]
one annotation to 
"intracellular defense response"

do we really need this term?

UniProtKB:P22749 | GNLY | involved_in | GO:0002818    intracellular defense response | ECO:0000314   IDA | PMID:9756476 |   | 9606 Homo sapiens | UniProt


lots of things are "intracellular defense responses. It doesn't seem to be a good axis of classificaation?

**Comment by ValWood** [comment]
Do you agree that this should go (orthogonal classification, combines location and process).

Also, often we cannot distinguish. It;'s also a bit of a continuum.
Binds plasma membrane receptor. 
Binds membrane receptor  from endocytic vesicle
Binds intracellular receptor.

Using this term will make for very inconsistent annotation unless we replicated all of the  different  types of response (IT HAS NO CHILDREN!)

Also the def is quite unclear
"A physiological defense response which occurs intracellularly"
Does it mean that the signalling is intracellular, or the response, the whole process? or part of it? It would not be simple to classify any immune response process to this term.

**Comment by pgaudet** [comment]
I will merge into 'GO:0006968 cellular defense response' , just so we keep the synonym.

**Comment by pgaudet** [comment]
Interesting because 'cellular defense response' has no children. But I think all those could be moved under it: 
'clearance of foreign intracellular nucleic acids'
'defense response by callose deposition'
'defense response by cell wall thickening'
'defense response to tumor cell'
'inflammatory response'

Thanks, Pascale
