### ISSUE TITLE
'adherens junction' vs. 'cell-cell adherens junction' vs. 'cell-substrate adherens junctions - relationships and definitions

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#18119]
Mila (@milarolo) has been annotating proteins associated with the [Blood-Brain Barrier Endothelial Connections](https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation/neurological-gene-0) as a part of the ARUK-UCL project. 

While annotating, Mila identified an incorrect relationship in the ontology between 'GO:0005912 adherens junction' (this is always a cell-cell junction - please see references in the next paragraph) and 'GO:0005924 cell-substrate adherens junction'.* 

*Some old papers (1998-1999) use phrases, such as 'cell-substrate adherens junction' (PMID:9832551) - and 'cell-matrix adherens junction' (PMID:10085297). It looks like at that time they did not have the same classification of cell junction structures that Mila has found in more recent papers. 

Based on more recent (2008-2017) reviews (PMIDs: 20571587, 17854762, 21422226, 28096264) and research articles (PMIDs: 28401269, 26923917), identified by Mila, an 'adherens junction' is always a 'cell-cell adherens junction'. Consequently, we would like to propose the following:

1.	The 'adherens junction' and 'cell-cell adherens junction' GO terms should be merged, because they are intended to represent the same structure. However, before doing this, we will need to carry out an annotation review for the 'adherens junction' term to make sure that all of these annotations do indeed represent 'cell-cell adherens junction' (https://github.com/geneontology/go-annotation/issues/2691).
2.	The ‘cell-substrate adherens junction’ should be obsoleted and manual experimental annotations (only 3 as of 4 Nov 2019) should probably be re-annotated to ‘cell-substrate junction’ or a relevant child term, perhaps ‘focal adhesion’ (https://github.com/geneontology/go-annotation/issues/2690).
_Obsoletion notice: https://github.com/geneontology/go-ontology/issues/18170_
3.	‘Cell-cell junction’ and ‘cell-substrate junction’ should be children of ‘anchoring junction’ (and definitions may need to be modified slightly) – please see the current and proposed ancestor charts below.
4.	The definition of ‘cell junction’ should also be revised to include junctions between membrane-bound cellular components, such as its child term ‘flagella connector’ (Definition: “A mobile transmembrane junction at the tip of the flagellum of some kinetoplastid species linking the tip of a new growing flagellum to an older flagellum PMID:11641501, PMID:15075226, PMID:16954145, PMID:26820516.”).
5.	The GO terms ‘fascia adherens’, ‘apical ectoplasmic specialization’ and ‘basal ectoplasmic specialization’ refer, respectively, to a cell-cell junction between myofibrils and cardiomyocytes, cell-cell junction between spermatids and Sertoli cells and cell-cell junction between Sertoli cells. They are currently children of ‘cell-cell adherens junction’. They will need to be re-positioned to become direct children of ‘cell-cell junction’ because the ‘adherens junction’ should refer specifically to connections between endothelial cells. Definitions need to be revised accordingly (please see table below).
6.	The corresponding BP GO terms need to be revised. This is a separate GitHub issue: https://github.com/geneontology/go-ontology/issues/18129

These above revisions led to others, which we will raise in separate tickets and reference here.

### Current Ancestor Chart
![Ancestor chart_041119](https://user-images.githubusercontent.com/16541096/68216350-d1964c00-fff1-11e9-9f7e-1ec00e9328ec.png)

### Proposed Ancestor Chart
<img width="672" alt="Proposed_Ancestor_Chart_1" src="https://user-images.githubusercontent.com/16541096/68216456-f68abf00-fff1-11e9-85b6-df38c1751b7a.png">
* Please see issue https://github.com/geneontology/go-ontology/issues/18120 for more information on the 'hemi-adherens junction'

### Definitions of related terms 
(please see the ancestor charts and notes above)

Term | Current   Definition | Proposed   Definition
-- | -- | --
GO:0030054   cell junction | A   cellular component that forms a specialized region of connection between two   or more cells or between a cell and the extracellular matrix. At a cell   junction, anchoring proteins extend through the plasma membrane to link   cytoskeletal proteins in one cell to cytoskeletal proteins in neighboring   cells or to proteins in the extracellular matrix. | A   cellular component that forms a specialized region of connection between two   or more cells, or between a cell and the extracellular matrix, or between two   membrane-bound components of a cell, such as flagella. PMIDs: 28096264, 26820516.
GO:0070161   anchoring junction | A   cell junction that mechanically attaches a cell (and its cytoskeleton) to   neighbouring cells, or to the extracellular matrix. | Grouping   term - no changes needed.
GO:0005912   adherens junction | A   cell junction at which anchoring proteins (cadherins or integrins) extend   through the plasma membrane and are attached to actin filaments. | A cell-cell junction composed of the epithelial cadherin–catenin complex. The epithelial cadherins, or E-cadherins, of each interacting cell extend through the plasma membrane into the extracellular space and bind to each other. The E-cadherins bind to catenins on the cytoplasmic side of the membrane, where the E-cadherin–catenin complex binds to cytoskeletal components and regulatory and signaling molecules. PMIDs: 17854762, 20571587,   21422226, 28096264.
GO:0005911   cell-cell junction | A   cell junction that forms a connection between two or more cells in a   multicellular organism; excludes direct cytoplasmic junctions such as ring   canals. | A   cell junction that forms a connection between two or more cells in a   multicellular organism; excludes direct cytoplasmic intercellular bridges,   such as ring canals in insects. PMIDs: 21422226, 28096264.
GO:0005913   cell-cell adherens junction | An   adherens junction which connects a cell to another cell. | n/a   – this term is redundant with and should be merged with ‘GO:0005912 adherens   junction’
GO:0030055   cell-substrate junction | A   cell junction that forms a connection between a cell and the extracellular   matrix. | A   cell junction that forms a connection between a cell and the   extracellular matrix. PMIDs: 8314002, 10419689, 16805308, 1643657, 26923917.
GO:0005924   cell-substrate adherens junction | An   adherens junction which connects a cell to the extracellular matrix. | n/a   – this term is not correct based on most recent classification and should be   obsoleted.
GO:0005916       fascia adherens | A   cell-cell adherens junction that contains the transmembrane protein   N-cadherin, which interacts with identical molecules from neighboring cells   to form a tight mechanical intercellular link; forms a large portion of the   intercalated disc, the structure at which myofibrils terminate in   cardiomyocytes. PMID:11732910 | A   cell-cell junction that contains the transmembrane protein N-cadherin, which   interacts with identical molecules from neighbouring cells to form a tight   mechanical intercellular link; forms a large portion of the intercalated   disc, the structure at which myofibrils terminate in cardiomyocytes. PMID:11732910
GO:0061831   apical ectoplasmic   specialization | Testis-specific   adherens junction between mature spermatids and Sertoli cells at the luminal   end of the Sertoli cell. PMID:22332112 PMID:23546604 | Testis-specific   junction between mature spermatids and Sertoli cells at the luminal end of   the Sertoli cell. PMID:22332112,   PMID:23546604
GO:0061832   basal ectoplasmic   specialization | Testis-specific   adherens junction between mature Sertoli cells involved in establishing the   blood-testis barrier of the Sertoli cell. PMID:22332112 PMID:23546604 | Testis-specific   junction between mature Sertoli cells involved in establishing the   blood-testis barrier of the Sertoli cell. PMID:22332112 PMID:23546604

cc
@RLovering 
@milarolo

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-ontology/issues/18120

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-annotation/issues/2690

https://github.com/geneontology/go-annotation/issues/2691

**Comment by ukemi** [comment]
Hi @BarbaraCzub. Note there are also assembly terms for the cell-substrate adherens junction terms and a protein localization to the cell-cell adherens junction. It should be straightforward to deal with these too. It's kind of weird that there is a hemi-adherens junction, but a quick look at the literature suggests you are correct in this proposal.

**Comment by BarbaraCzub** [comment]
Hi @ukemi. Yes, we do remember about the assembly and other BP terms and I'll open and link this ticket here. Thanks!

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-ontology/issues/18124

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-ontology/issues/18129

**Comment by BarbaraCzub** [comment]
Why does 'zonula adherens' have the exact synonym 'fascia adherens'? Are they the same thing? Or should this be a related synonym instead? 

Most of the experimental annotations are for invertebrates: https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0005915&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

**Comment by hattrill** [comment]
That doesn't seem quite right. There is a term for fascia adherens and from a quick look, 
(e.g. The mechanotransduction machinery at work at adherens junctions. PMID:25968913 PMCID:PMC4593723), seems that it similar to zonula adherens - as it's a band around the cell, but different, in that it includes proteins that make up adherens junctions and desmosomes and is restricted to cardiac tissue.

**Comment by BarbaraCzub** [comment]
> That doesn't seem quite right. There is a term for fascia adherens and from a quick look,
> (e.g. The mechanotransduction machinery at work at adherens junctions. PMID:25968913 PMCID:PMC4593723), seems that it similar to zonula adherens - as it's a band around the cell, but different, in that it includes proteins that make up adherens junctions and desmosomes and is restricted to cardiac tissue.

Thanks, Helen. I will remove this synonym.

**Comment by BarbaraCzub** [comment]
Points: 1, 3, 4, 5 and revisions of relations shown in the proposed ancestor chart are done.
Point 2 will be addressed in the Obsoletion notice: #18170.
Point 6 will be addressed in issue: #18129.
'Hemi-adherens' terms are being dealt with in issue #18120.
This issue can be closed.
