### ISSUE TITLE
MP GO:0018215 | protein phosphopantetheinylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18113]
We probably don't really need

GO:0018215 | protein phosphopantetheinylation

but since we have it

GO:0008897 | holo-[acyl-carrier-protein] synthase activity

should be is_a GO:0018215

**Comment by hdrabkin** [comment]
You mean part_of ?
GO:0008897 | holo-[acyl-carrier-protein] synthase activity is part of GO:0018215 | protein phosphopantetheinylation

**Comment by ValWood** [comment]
yes, sorry part_of

**Comment by ValWood** [comment]
seems quick to add this relationship?

**Comment by pgaudet** [comment]
Added part_of GO:0018215 ! protein phosphopantetheinylation
