### ISSUE TITLE
too many penetration peg terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18114]
GO:0075057    initiation of symbiont penetration peg
GO:0075058    modulation of symbiont penetration peg initiation
GO:0075060    negative regulation of symbiont penetration peg initiation
GO:0075059    positive regulation of symbiont penetration peg initiation
GO:0075053    formation of symbiont penetration peg for entry into host
GO:0075054    modulation of symbiont penetration peg formation for entry into host
GO:0075055    positive regulation of symbiont penetration peg formation for entry into host
GO:0075056    negative regulation of symbiont penetration peg formation for entry into host

please merge "initiation" into formation for entry into host
You only form a penetration peg for entry into host.
We have  2 sets of terms for forming it...

**Comment by ValWood** [comment]
and remove the parentage to locomotion?
GO:0075056  (and any others?)

**Comment by ValWood** [comment]
the correct parentage

GO:0075052    entry into host via a specialized structure

**Comment by pgaudet** [comment]
Term |   | Number of annotations | merge into |   |  
-- | -- | -- | -- | -- | --
GO:0075057 | initiation of symbiont penetration peg | 0 | GO:0075053 | formation of symbiont penetration peg for entry into host |  
GO:0075025 | initiation of appressorium on or near host | 0 | GO:0075016 | appressorium formation on or near host |  

However this cannot be is_a 'GO:0075052 entry into host via a specialized structure'; I can add 'part_of'. 

Thanks, Pascale

**Comment by pgaudet** [comment]
What about maturation ? Similar to initiation, if we merge intiation, we should also merge maturation ? 

GO:0075035 maturation of appressorium on or   near host -> merge into GO:0075016 | appressorium formation on or near host ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't understand.
In this case what  would be annotated to  "entry into host via specialised structure" ?
The structure forms to allow entry into host.

**Comment by ValWood** [comment]
unsurprisingly 
GO:0075052    entry into host via a specialized structure
has no annotations. 

Most experiments would  say "the pathogen could not enter the host" because the "x specialised structure" did not form....

**Comment by ValWood** [comment]
I can find papers about the maturation of the appressorium to form the penetration peg.
But I can't find anything about maturation of the penetration peg.

I think its another example of unnecessary filling in of terms.

See this abstract:
https://www.ncbi.nlm.nih.gov/pubmed/17704215

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/18557
will resolve
