### ISSUE TITLE
penetration peg and penetration hyphae

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18117]
GO:0075201   formation of symbiont penetration hypha for entry into host

has the definition
The assembly by the symbiont of a threadlike, tubular structure, which may contain multiple nuclei and may or may not be divided internally by septa or cross-walls, for the purpose of penetration into its host organism. In the case of an appressorium existing, **this term is defined in further details as the process in which the symbiont penetration peg expands to form a hypha** which traverses the epidermal cell and emerges into the intercellular space of the mesophyll tissue. The host is defined as the larger of the organisms involved in a symbiotic interaction.

@CuzickA  what is the difference between a penetration hyphae and a penetration peg?

**Comment by CuzickA** [comment]
> what is the difference between a penetration hyphae and a penetration peg?

I think that penetration hyphae grow on the surface and can enter plant stomata without a specific penetration structure, whereas the penetration peg is part of specific penetration machinery such as an appressorium.

**Comment by ValWood** [comment]
OK
nice appresorium summary figure:
https://fr.wikipedia.org/wiki/Appressorium#/media/Fichier:Haustorium_Erysiphe_necator.svg

so  with apressorium there is a penetration peg and entry through the cell wall.
If no apressorium entry cannot be through cell wall, and must be through stomata

**Comment by ValWood** [comment]
in that case this is misleading

GO:0075053    formation of symbiont penetration peg for entry into host 
GO:0075201    formation of symbiont penetration hypha for entry into host

because these are part of the same mechanism of entry, unless penetration hyphae is for penetration through stomata, in which case it is 
GO:0044410    entry into host through natural portals

but I think we have this covered in another ticket too.


we should obsolete 
GO:0075201 formation of symbiont penetration hypha for entry into host
anyway.
Formation of the hyphae is just "invasive hyphal growth"

**Comment by ValWood** [comment]
partially redundant with
https://github.com/geneontology/go-ontology/issues/18118

**Comment by pgaudet** [comment]
Also, do we need this distinction: 

GO:0075058 modulation of symbiont penetration peg initiation
GO:0075054 modulation of symbiont penetration peg formation for entry into host ?

**Comment by ValWood** [comment]
I don't think so. Why else would you form a penetration peg?

**Comment by ValWood** [comment]
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/1471-2180-9-S1-S7/figures/2

**Comment by ValWood** [comment]
So @CuzickA   is 
a) a penetration peg for crossing the cuticle 
b ) penetration hyphae enter cells through stomata 
c) and invasive hyphae invade the intracellular space?

**Comment by ValWood** [comment]
If this is true we should keep 

GO:0075201    formation of symbiont penetration hypha for entry into host
but clarify as host cell through stomata

and obsolete
GO:0044410    entry into host through natural portals

**Comment by CuzickA** [comment]
> a) a penetration peg for crossing the cuticle
b ) penetration hyphae enter cells through stomata
c) and invasive hyphae invade the intracellular space?

I discussed this with @martin2urban

a) yes
b) I think this would be better as 'penetration hyphae enter cells through natural portals' and then have 'stomata' as a child term. Penetration hyphae can also enter wounded plant tissue, this may occur from gnawing insects, wind damage with leaves rubbing against each other, cracks occurring at the end of plant leaves during growth, damage from another pathogen infection etc. 
c) invasive hyphase can invade intracellularly or the extracellular space (apoplast) depending on the pathogen

**Comment by mgiglio99** [comment]
not sure about obsoleting 'entry into host through natural portals' since there are other natural portals besides stomata.

**Comment by ValWood** [comment]
Here we need to think about mechanisms.

 From what I read, and from the above, fungi either enter the host using
i) appressorium and penetration peg to cross the cuticale,

Or 
ii)_ via invasive hyphae which can enter invade the intracellular space, or get into cells through stomata or damage.

I don't think we need terms for every way the fungi enter the host/host cell unless the mechanism is different.

We should  think about  what the experiments show; usually the host can enter the cell, or it can't 
but which genes would be annotated to a term like "entry into cell through stomata", wouldn't they just be genes required for hyphal growth/ hyphae formation?

**Comment by mgiglio99** [comment]
There are bacterial proteins that specifically interact with plant proteins to open up stomata so they can get in. So a term like "entry into cell through stomata" could be good for them.
(These bacterial proteins were mentioned in another ticket recently. )

**Comment by ValWood** [comment]
This is one of the areas @pgaudet and I hope to tackle after the  pattern recognition pathways related terms. There are quite a few open tickets about entry into host, and quite a few inconsistencies.

Maybe you could join us when we  do this part for the bacterial perspective?

**Comment by mgiglio99** [comment]
sure, I'd be glad to.

**Comment by ValWood** [comment]
replaced by
https://github.com/geneontology/go-ontology/issues/18557
