### ISSUE TITLE
Logically define 'cilium movement' as 'movement of cell or subcellular component' and 'results in movement of' some 'cilium'?

### ISSUE THREAD

**Issue by matentzn** [geneontology/go-ontology#18112]
To capture `movement of cell or subcellular component`, in particular, GO:0003341 - cilium movement logically, we would like to 

1) know which RO relationship is appropriate to capture the relation between the cell movement and the cilium. @dosumis has suggested RO:0002565 ("results in movement of"), e.g. GO:0060285 ---[has active participant]-->"cilium"
2) assert, in particular, the fact that GO:0003341 equivalentTo: GO:0006928  and `results in movement of` some GO:0005929

EDIT: replaced proposal from `has active participant` to `results in movement of`

**Comment by matentzn** [comment]
Sorry, I did not notive that `has active participant` was obsoleted. In any case, `results in movement of` seems more appropriate: http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002565

**Comment by ukemi** [comment]
I think this will work. I'm going to try to tidy up this area of the ontology.

**Comment by ukemi** [comment]
I had to add (and mediated_by some microtubule), but it seems to have worked.

**Comment by matentzn** [comment]
Thank you!
