### ISSUE TITLE
too many appressorium terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18115]
GO:0075039    establishment of turgor in appressorium 1 annotations
GO:0075021    cAMP-mediated activation of appressorium formation
GO:0075016    appressorium formation on or near host 1 annotations
GO:0075003    adhesion of symbiont appressorium to host
GO:0075022    ethylene-mediated activation of appressorium formation
GO:0075023    MAPK-mediated regulation of appressorium formation
GO:0075040    regulation of establishment of turgor in appressorium
GO:0075043    maintenance of turgor in appressorium by melanization
GO:0075035    maturation of appressorium on or near host 1 annotations
GO:0075024    phospholipase C-mediated activation of appressorium formation
GO:0075025    initiation of appressorium on or near host
GO:0075020    calcium or calmodulin-mediated activation of appressorium formation
GO:0075017    regulation of appressorium formation on or near host
GO:0075041    positive regulation of establishment of turgor in appressorium
GO:0075042    negative regulation of establishment of turgor in appressorium

I am annotating a MAP kinease which regulates 
 appressorium formation

however i don't want to use
GO:0075023    MAPK-mediated regulation of appressorium formation

I want to do just 
regulation of appressorium formation
I think the other terms 
GO:0075024    phospholipase C-mediated activation of appressorium formation
GO:0075020    calcium or calmodulin-mediated activation of appressorium formation

should also go because they are just other MFs in the signalling pathway.

also merge
GO:0075025    initiation of appressorium on or near host
into positive regulation

**Comment by ValWood** [comment]
also obsolete or merge
cAMP-mediated activation of appressorium formation 
ethylene-mediated activation of appressorium formation

**Comment by ValWood** [comment]
I'm not sure why we need to say "on or near host"?
Maybe somebody else knows?
 but why not just "appressorium formation"?  The purpose is the same wherever it forms?

**Comment by pgaudet** [comment]
> but why not just "appressorium formation"? The purpose is the same wherever it forms?

Also, the process of appressorium formation must be the same ? Unless it's a different appressorium, in which case this would be missing from the definition. 

@mgiglio99 do you know different appressorium? (appressoria?)

**Comment by mgiglio99** [comment]
I don't know of different appressoria but this is not my area of knowledge.
I think I agree that it could be just 'appressorium formation'

I see this term is a child of 'development involved in symbiotic interaction' - shouldn't 'development involved in symbiotic interaction' be a child of 'symbiotic process'? Rather than a direct child of 'interspecies interaction...' and 'multiorganism process'? If you think so - I can make a new ticket.

**Comment by ValWood** [comment]
I don't know if this is really development? Usually, for cell structures we say "formation" not development.

**Comment by mgiglio99** [comment]
I don't know much about appressoria, but what I read says they are a specialized cell - so would it be a kind of differentiation? How is that kind of thing handled? 
But either way - I agree that 'development' is not the right location.

**Comment by ValWood** [comment]
All this will be fixed by
https://github.com/geneontology/go-ontology/issues/18564
