### ISSUE TITLE
Drosophila subset

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#18122]
Hello!

Could you create a slim subset for Drosophila? 
Attaching file with 'name' 'ID' - 151 terms. Let me know if you need something different.

subsetdef: goslim_drosophila "Drosophila GO slim"

[Drosophila_slim.txt](https://github.com/geneontology/go-ontology/files/3810436/Drosophila_slim.txt)

**Comment by pgaudet** [comment]
@hattrill I cannot get to that file - can you paste the 151 terms here ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Here they are:
Term Name	GOID
DNA recombination	GO:0006310
DNA repair	GO:0006281
DNA replication	GO:0006260
DNA catabolic process	GO:0006308
mRNA metabolic process	GO:0016071
tRNA metabolic process	GO:0006399
rRNA metabolic process	GO:0016072
snRNA metabolic process	GO:0016073
snoRNA metabolic process	GO:0016074
piRNA metabolic process	GO:0034587
miRNA metabolic process	GO:0010586
transcription, DNA-templated	GO:0006351
RNA catabolic process	GO:0006401
gene silencing	GO:0016458
lipid metabolic process	GO:0006629
carbohydrate metabolic process	GO:0005975
cellular amino acid metabolic process	GO:0006520
nucleobase-containing small molecule metabolic process	GO:0055086
generation of precursor metabolites and energy	GO:0006091
sulfur compound metabolic process	GO:0006790
alcohol metabolic process	GO:0006066
cofactor metabolic process	GO:0051186
protein catabolic process	GO:0030163
protein maturation	GO:0051604
glycoprotein metabolic process	GO:0009100
protein lipidation	GO:0006497
protein modification by small protein conjugation or removal	GO:0070647
mitochondrial translation 	GO:003254
cytoplasmic translation	GO:0002181
vesicle-mediated transport	GO:0016192
ion transport	GO:0006811
mitochondrial transport	GO:0006839
nucleocytoplasmic transport	GO:0006913
protein targeting	GO:0006605
cytoskeleton-dependent intracellular transport	GO:0030705
lipid transport	GO:0006869
protein secretion	GO:0009306
cellular protein localization	GO:0034613
protein transmembrane transport	GO:0071806
RNA localization	GO:0006403
mitochondrion organization 	GO:0007005
cilium organization	GO:0044782
chromosome organization	GO:0051276
actin cytoskeleton organization	GO:0030036
microtubule cytoskeleton organization	GO:0000226
nucleus organization	GO:0006997
endomembrane system organization	GO:0010256
membrane organization	GO:0061024
synapse organization	GO:0050808
ribosome biogenesis	GO:0042254
protein folding	GO:0006457
autophagy	GO:0006914
intracellular signal transduction	GO:0035556
G protein-coupled receptor signaling pathway	GO:0007186
cell surface receptor signaling pathway	GO:0007166
meiotic cell cycle	GO:0051321
mitotic cell cycle	GO:0000278
cell death	GO:0008219
cell division	GO:0051301
cell growth	GO:0016049
cell population proliferation	GO:0008283
cell adhesion	GO:0007155
nervous system development	GO:0007399
muscle structure development	GO:0061061
epithelium development	GO:0060429
pattern specification process	GO:0007389
cuticle development	GO:0042335
respiratory system development	GO:0060541
gastrulation	GO:0007369
sensory perception	GO:0007600
cognition	GO:0050890
cell motility	GO:0048870
cell differentiation	GO:0030154
cell morphogenesis	GO:0000902
cell redox homeostasis	GO:0045454
chemical homeostasis	GO:0048878
immune response	GO:0006955
immune system development	GO:0002520
locomotory behavior	GO:0007626
reproductive behavior	GO:0019098
circadian rhythm	GO:0007623
response to chemical	GO:0042221
response to stress	GO:0006950
response to external stimulus	GO:0009605
molting cycle	GO:0042303
transferase activity, transferring glycosyl groups	GO:0016757
methyltransferase activity	GO:0008168
ubiquitin-like protein transferase activity	GO:0019787
transferase activity, transferring acyl groups	GO:0016746
transferase activity, transferring alkyl or aryl (other than methyl) groups	GO:0016765
phosphotransferase activity, alcohol group as acceptor	GO:0016773
kinase activity	GO:0016301
nucleotidyltransferase activity	GO:0016779
peptidase activity	GO:0008233
hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds	GO:0016810
carboxylic ester hydrolase activity	GO:0052689
lipase activity	GO:0016298
nuclease activity	GO:0004518
phosphatase activity	GO:0016791
ATPase activity	GO:0016887
GTPase activity	GO:0003924
hydrolase activity, acting on glycosyl bonds	GO:0016798
oxidoreductase activity	GO:0016491
ligase activity	GO:0016874
isomerase activity	GO:0016853
lyase activity	GO:0016829
enzyme regulator activity	GO:0030234
guanyl-nucleotide exchange factor activity	GO:0005085
signaling receptor activity	GO:0038023
receptor ligand activity	GO:0048018
transmembrane transporter activity	GO:0022857
structural constituent of cuticle	GO:0042302
structural constituent of ribosome	GO:0003735
structural constituent of cytoskeleton	GO:0005200
extracellular matrix structural constituent	GO:0005201
cytoskeletal protein binding	GO:0008092
transcription factor binding	GO:0008134
histone binding	GO:0042393
unfolded protein binding	GO:0051082
molecular adaptor activity	GO:0060090
chromatin binding	GO:0003682
carbohydrate binding	GO:0030246
chitin binding	GO:0008061
lipid binding	GO:0008289
metal ion binding	GO:0046872
enzyme binding	GO:0019899
RNA binding	GO:0003723
DNA binding	GO:0003677
translation regulator activity	GO:0045182
DNA-binding transcription factor activity	GO:0003700
transcription coregulator activity	GO:0003712
extracellular matrix	GO:0031012
extracellular space	GO:0005615
external encapsulating structure	GO:0030312
cell junction	GO:0030054
endosome	GO:0005768
coated vesicle	GO:0030135
secretory vesicle	GO:0099503
plasma membrane	GO:0005886
cilium	GO:0005929
cytosol	GO:0005829
nucleus	GO:0005634
chromosome	GO:0005694
nucleolus	GO:0005730
mitochondrion	GO:0005739
vacuole	GO:0005773
Golgi apparatus	GO:0005794
endoplasmic reticulum	GO:0005783
peroxisome	GO:0005777
cytoskeleton	GO:0005856
synapse	GO:0045202

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/pull/18137

Should have all 151 terms.

**Comment by hattrill** [comment]
That was quick! Thanks
