### ISSUE TITLE
Chorion terms: sort out insert, reptiles and mammals

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18128]
Hello, 

This arises from a ticket where I have added taxon constraints to a number of terms, including chorion (#18027). 

Can someone review the terms containing 'chorion' to make sure that we correctly distinguish between insect-type vs mammalian-type (and others) chorion? I am happy to help but I dont know much about this. 

* GO_0005213 | structural constituent of chorion
* GO_0007304 | chorion-containing eggshell formation
* GO_0007305 | vitelline membrane formation involved in chorion-containing eggshell   formation
* GO_0007306 | eggshell chorion assembly
* GO_0007307 | eggshell chorion gene amplification
* GO_0030381 | chorion-containing eggshell pattern formation
* GO_0042600 | chorion **(definition specifically mention insects)**
* GO_0044751 | cellular response to human chorionic gonadotropin stimulus
* GO_0044752 | response to human chorionic gonadotropin
* GO_0046844 | chorion micropyle formation
* GO_0060717 | chorion development
* GO_0060718 | chorionic trophoblast cell differentiation
* GO_0060719 | chorionic trophoblast cell development
* GO_0097360 | chorionic trophoblast cell proliferation
* GO_1901382 | regulation of chorionic trophoblast cell proliferation
* GO_1901383 | negative regulation of chorionic trophoblast cell proliferation
* GO_1901384 | positive regulation of chorionic trophoblast cell proliferation

Some of those terms use the following terms in axioms: 
* UBERON_0000920 | egg chorion
* UBERON_0003124 | chorion
* UBERON_0003265 | chorionic mesenchyme
* UBERON_0003374 | chorionic ectoderm
* UBERON_0004027 | chorionic plate
* UBERON_0005307 | chorion-containing eggshell
* UBERON_0007106 | chorionic villus
* CL_0011101 | chorionic trophoblast cell

Wikipedia describes the chorion as 'The chorion is the outermost fetal membrane around the embryo in mammals, birds and reptiles. It develops from an outer fold on the surface of the yolk sac, which lies outside the zona pellucida (in mammals), known as the vitelline membrane in other animals. In insects it is developed by the follicle cells while the egg is in the ovary.'  (https://en.wikipedia.org/wiki/Chorion)

So, looks like the structure is analogous but the development is different ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Looks like we have mixed up the structure in the logical defs. I will sort them out.

**Comment by ukemi** [comment]
@balhoff, it looks like we have GO:0042600 (Chorion), and Uberon has UBERON:0000920 (egg chorion). The UBERON term refers to the GO term in its definition. In GO we have used the UBERON term in logical definitions for terms like GO:0007306 (eggshell chorion assemby). I propose that we switch all the logical defs in GO that refer to the egg chorion to use the GO IRI and we retain the UBERON IRI for terms like 'chorion development' that refer to the tissue. Does this sound like the best plan?

**Comment by ukemi** [comment]
Maybe it would be better to declare an equivalence between the GO chorion and the UBERON eggshell chorion? If we go with the strategy above, we lose the route into UBERON.

**Comment by balhoff** [comment]
I don't think I have the experience to weigh in on this one. :-)

**Comment by ukemi** [comment]
Added to editors' discussion to see if this would be an appropriate strategy.

**Comment by cmungall** [comment]
We shouldn't have any equivalencies. If it belongs in GO I will obsolete
the uberon one. But if we want a larger structure then I will rename uberon
e.g chorion tissue and have a composed_primarily_of axiom (though I prefer
to avoid shadows)

**Comment by ukemi** [comment]
I'm not sure that the egg chorion/vitelline membrane of fish, reptiles, insects and birds would even be considered a tissue. The placental chorion certainly is. Both types of chorion kind of play similar roles in that they serve as a barrier between the embryo and the outside world. I think I am remembering this correctly, but will supplement with some references in this ticket. I'm getting old, so I'd like to check.

**Comment by ukemi** [comment]
fish- acellular PMID:8913023
fly- acellular PMID:27752139
reptiles- an epithelium? PMID:12353296 

I propose that for the tissue chorion, we retain the UBERON term and that for the egg chorion we consider it an extracellular structure, retain it in GO and make our cross references to it. Does this make sense?
Pinging @sabrinatoro @hattrill

**Comment by sabrinatoro** [comment]
@ukemi 
chorion in the ZFA as an ‘extraembryonic structure’. It does seem that the chorion is not a tissue. In Uberon, ‘egg chorion’ (UBERON_0000920 | egg chorion) is used for the noncellular membrane of insects and Fish and this term is crossreferenced to our ZFA term.

(I hope that helps)

**Comment by cmungall** [comment]
What is a good primary label for the Amniote structure? 'chorion membrane'
could still be taken to include egg corion. 'chorion cellular membrane' is
a bit awkward.

**Comment by cmungall** [comment]
I guess just 'amniote chorion' works, though I don't like embedding taxa in
names.

**Comment by ukemi** [comment]
Thanks @sabrinatoro. This helps. I think part of the confusion is that in organisms where the embryo develops inside the eggshell, the egg chorion becomes the embryonic chorion and serves as a semipermeable barrier between the embryo and its environment.
@cmungall, you are correct in that the terminology is confusing. In mouse we talk about extraembryonic membranes. What about 'chorion tissue' or 'chorionic tissue' sine it has_part a mesoderm and ectoderm? 
I'm still a little uncertain about the use in all reptiles, but the reference above suggests that it is at least cellular some of the time.

**Comment by hattrill** [comment]
In flies, the chorion is an extracellular structure that is part of the egg shell (it could be considered a type of extracellular matrix & is by some). It is secreted by follice cells and lies over the other eggshell layer, the vitelline membrane that surrounds the oocyte.

**Comment by ukemi** [comment]
Hi @sabrinatoro. It looks like you have annotations to 'chorionic trophoblast cell differentiation' by ISS. Do you think these are errors? I would like to change the 'chorion development' term in GO to point to the UBERON chorion term, which will refer to the tissue. But this won't make sense if we say the zebrafish chorion is a GO chorion, ie an extracellular matrix.

**Comment by cmungall** [comment]
this is definitely an error, http://purl.obolibrary.org/obo/CL_0011101 is
clearly uterine/mammalian, and this should fall out of the TCs too
