### ISSUE TITLE
ntr ATPase-coupled azole transmembrane transporter activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18127]
child of

GO:0042626 | ATPase-coupled transmembrane transporter activity 
GO:1901474 | azole transmembrane transporter activity

PMID:31501141

@CuzickA

**Comment by pgaudet** [comment]
Note: this is an ABC transporter

**Comment by ValWood** [comment]
Ah they aren't ATPase coupled?

ABC transporters are ATPases....

I can just use
GO:1901474 | azole transmembrane transporter activity

**Comment by pgaudet** [comment]
yes I need to change logical definition to many terms

**Comment by pgaudet** [comment]
@srengel S000003456 AZR1 is annotatoned to azole transmembrane transporter activity - however I don't see an transport assay in the paper. In any case, it should be annotated to 'azole:proton antiporter activity' based on it belonging to the major facilitator superfamily. 

Can you please have a look ? I would suggest you annotate to the process, 'azole transport', and perhaps 'cellular detoxification'. 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't think all MSFs are antiporters are they?

**Comment by pgaudet** [comment]
I dont know - this one is described as one. PMID:11113970

**Comment by ValWood** [comment]
I think the SGD annotation is fine. It's not a transport assay but its an assay used to determine the specificity of  obvious transporters and its only IMP?

We just used IMP for this  assay for the publication above... (@marcfeuermann co-author)
I  would not always use a sensitivity to make a transporter annnotation but  with curator knowledge of the family, author intent . etc./ aI think this seems OK?

**Comment by ValWood** [comment]
I think that might be wrong... at least pombe has 12 antiporters and  76 MFS transporters, Zero overlap.

**Comment by pgaudet** [comment]
OK sure. But can we use the correct transporter type 'azole:proton antiporter activity' ? 

Ideally I would get rid of all intermediate transporter types (x-compound transport), in favor of the mechanism (antiporter, symporter, ABC-coupled, P-type). The grouping relative to the compound should be in the BP. 

What do you think ?

**Comment by ValWood** [comment]
I don't see antiporter in PMID:11113970?

**Comment by pgaudet** [comment]
- [x] changed GO:0045117 'azole transport' to 'azole transmembrane transport' and edited logical definition accordingly. 

 - [x] changed GO:1901474
-name: azole transmembrane transporter activity
+name: ATPase-coupled azole transmembrane transporter activity

+ made it a child of 'ATPase-coupled transmembrane transporter activity' (which will become ABC-type transporter activity)

**Comment by pgaudet** [comment]
> I don't see antiporter in PMID:11113970?

"The proton‐motive‐force‐dependent multidrug efflux systems belong to the major facilitator superfamily (MFS) (Paulsen et al., 1996; Nelissen et al., 1997). The electrochemical proton gradient across the plasma membrane is generated by the H+‐translocating‐ATPase in this membrane, also implicated in the maintenance of intracellular pH (pHi)."

**Comment by ValWood** [comment]
I'm not sure that is correct. Or maybe it applies to a subset.
Or manybe Paulsen and Neilssen are incorrectly quoted...

**Comment by ValWood** [comment]
Wikipedia
..... These protein energetically drive transport utilizing the electrochemical gradient of the target substrate (uniporter), or act as a cotransporter where transport is coupled to the movement of a second substrate.

**Comment by pgaudet** [comment]
Lets discuss this tomorrow ?

**Comment by pgaudet** [comment]
- [x] azole transport: 
- Change label -> azole transmembrane transport
- change LD
- change textual definition 

- New term: 
 
+[Term]
+id: GO:0140394
+name: ATPase-coupled azole transmembrane transporter activity
+namespace: molecular_function
+def: "Enables the transfer of azoles, heterocyclic compound found in many biologically important substances, from one side of a membrane to the other according to the reaction: ATP + H2O + azole(in) = ADP + phosphate + azole(out)." []
+intersection_of: GO:0005215 ! transporter activity
+intersection_of: has_part GO:0016887 ! ATPase activity
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+intersection_of: transports_or_maintains_localization_of CHEBI:68452 ! azole
+created_by: pg
+creation_date: 2019-11-28T18:29:48Z

Pascale
