### ISSUE TITLE
‘connecting hemi-adherens junction’ and ‘focal adhesion’ – names, synonyms and definitions

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#18120]
Mila (@milarolo) has been annotating proteins associated with the [Blood-Brain Barrier Endothelial Connections](https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation/neurological-gene-0) as a part of the ARUK-UCL project. While annotating, Mila identified several issues with the term ‘connecting hemi-adherens junction’.

1.	Mila found only one paper using the long name ‘connecting hemi-adherens junction’: PMID: 8314002 (1 Nov 2019). When we followed up on this, we found other papers that use only ‘hemiadherens/hemi-adherens junction’ (based on PubMed or Google Scholar searches for either ‘hemi-adherens’ or ‘hemiadherens’; both accessed: 4 Nov 2019).
a.	We should rename ‘connecting hemi-adherens junction’ to ‘hemi-adherens junction'.

2.	‘Hemi-adherens junctions’ appear to be found only in invertebrates. All papers identified in PubMed or Google Scholar (both accessed: 4 Nov 2019) for either ‘hemi-adherens’ or ‘hemiadherens’ describe structures found in flies (_Drosophila_) and worms (_Caenorhabditis elegans, Mesostoma lingua, Gordius aquaticus, Paragordius varius, Pristionchus pacificus_ or _Geocentrophora wagini_). E.g. PMIDs: 8314002, 10419689, or 16805308. 
PMIDs: 6437808 and 18620229 provide further supporting evidence. PMID: 6437808 demonstrates that ‘hemi adherens junction’ are absent from the vertebrate chick heart. The authors observe and conclude: “The labelling was always exclusive to intercellular junctions while 'hemi adherens junctions' with the substrate or ECM, both in culture or in the intact tissues, were negative. This indicates that the molecular homology between the two types of contact, suggested by the presence of vinculin in both, is incomplete.”
Additionally, PMID: 18620229: shows that ‘hemi adherens junctions’ are not found in ascidians/sea squirts (phylum: Chordata); the authors state: “… no ‘hemi-adherens junctions’ have been observed in the ciliated cells at the heterologous cell border.”
a.	We should add a taxon constraint ‘only in invertebrates’ (and the definition – pasted in below – should be modified accordingly). 
b.	The term should have the exact synonyms ‘hemiadherens junction’ and ‘HAJ’.
@hattrill @gantonazzo @vanaukenk would you like to add any comments?

3.	The related term ‘apical hemi-adherens junction’ has no annotations. In addition, for ‘apical hemi-adherens junction’, we found only one paper using this term (PubMed search: none and Google search; 4 Nov 2019), and it was not the paper referenced in the current definition of this term in GO i.e. PMID: 8314002 (however, the paper is so old that the .pdf must have been from a picture, so I only searched it by eye, so might have missed the phrase; however, the term that the paper uses for sure is ‘hemi-adherens junction’).
a.	We should probably obsolete ‘apical hemi-adherens junction’, because it has no annotations, and the ‘apical’ aspect can be captured as contextual information in both Noctua and Protein2GO. I’ll open a separate ticket for this. @hattrill @gantonazzo @vanaukenk would you like to add any comments?

4.	‘Focal adhesion’ has the related synonym ‘hemi-adherens junction’. We found one paper, which mentions that they could be the same; however, this is a review with a non-traceable author statement (PMID: 21680409):
“Links to actin, sometimes in prominent bundles, also characterize the hemi-adherens junction, otherwise known as the focal contact, that joins the cell to extracellular matrix with spot-like welds at the basal lamina or apical cuticle.”
On the other hand, we found a review, which suggests that 'focal adhesion/contact' is synonymous with 'basal hemi-adherens junction':
"Basal HAJs (elsewhere called focal contacts) are integrin-based and connect epithelial cells to basement membranes or specialize into muscle-tendon junctions (20, 118)".
a.	We should replace the related synonym ‘hemi-adherens junction’ with ‘basal hemi-adherens junction’ and also add ‘basal HAJ’ as well as ‘cell-matrix adhesion’.

5.    There appear to be no BP GO terms that with the phrase 'hemi-adherens' or 'hemiadherens'; however, 'focal adhesion (dis)assembly' terms need to be revised.

### Proposed Ancestor Chart
<img width="672" alt="Proposed_Ancestor_Chart_1" src="https://user-images.githubusercontent.com/16541096/68216456-f68abf00-fff1-11e9-85b6-df38c1751b7a.png">

### Definitions of related terms 
(please see the ancestor charts and notes above)

Current   term name | Proposed   term name | Current   Definition | Proposed   Definition
-- | -- | -- | --
connecting   hemi-adherens junction | hemi-adherens   junction | A   cell-substrate adherens junction, also known as a hemiadherens junction (HAJ)   that forms one of a pair of junctions in opposing cells that are separated by   only 30-40nm, with a thin line of extracellular electron-dense material in   between; found where muscles attach to epidermal cells directly (in insects). | A   cell-substrate junction that forms one of a pair of junctions in opposing   cells that are separated by a thin line of extracellular electron-dense   material in between; found where muscles attach to epidermal cells directly   (in invertebrates) (PMIDs: 8314002, 10419689, 16805308).
Focal   adhesion | n/a | Small   region on the surface of a cell that anchors the cell to the extracellular   matrix and that forms a point of termination of actin filaments. | Small   region on the surface of a cell that anchors the cell to the extracellular   matrix via transmembrane integrin-containing macromolecular complexes and   binds to ends of actin cytoskeleton inside the cell (PMIDs: 1643657, 26923917, 19197329, 12191915, 15246682, 23033047, 28796323).

cc
@RLovering 
@milarolo

**Comment by BarbaraCzub** [comment]
https://github.com/geneontology/go-ontology/issues/18119

**Comment by hattrill** [comment]
Hi Barbara - I will get back to to on this (and adherens junctions), just consulting an expert.

**Comment by hattrill** [comment]
So the paired junction thing is a bit of a red herring. It's because the ECM in Drosophila tissues (and worms) can be very thin and so the hemi-adherens junctions just line up as they are binding the same ECM components so they just look aligned in EM. In instances where the ECM is thicker, it's clear that it's a cell-substrate contact.

No-one actually really uses the term hemi-adherens now - it's mostly a hangover from early EM studies. In terms of make-up and what they do, focal adhesions and hemi-adherens junctions (which have nothing much in common with adherens junctions) are essentially the same. Nick Brown (who is one of the few people to have used the term 'hemi-adherens', suggested to merge 'connecting hemi-adherens junction' with 'Focal adhesion' and have 'hemi-adherens junction' as an exact synonym.
The only change to the definition would be to remove the word "small" as it's more of a 'relative to what I see when doing EM'.

**Comment by hattrill** [comment]
With regards to 'apical hemi-adherens junction' - we had one annotation and it was not very good and now we have none! So, from our perspective, obsolete away!

However.....flies and worms do have apical adhesion complexes (that have sometimes been called 'apical hemi-adherens junction') that are super interesting, although not mega-defined, that link epidermal cells to the cuticlle. In flies, these cuticle attachment sites are linked to the microtubule cytoskeleton that transverses the cell to the basal junction. In worms, a similar contact exists but linked to intermediate filaments (which flies don't have). So, an apical junction term or cuticle attachment site, might be useful for us cuticle-bearing beasties. What say ye @vanaukenk ?
I will do more digging later.

**Comment by BarbaraCzub** [comment]
> So the paired junction thing is a bit of a red herring. It's because the ECM in Drosophila tissues (and worms) can be very thin and so the hemi-adherens junctions just line up as they are binding the same ECM components so they just look aligned in EM. In instances where the ECM is thicker, it's clear that it's a cell-substrate contact.
> 
> No-one actually really uses the term hemi-adherens now - it's mostly a hangover from early EM studies. In terms of make-up and what they do, focal adhesions and hemi-adherens junctions (which have nothing much in common with adherens junctions) are essentially the same. Nick Brown (who is one of the few people to have used the term 'hemi-adherens', suggested to merge 'connecting hemi-adherens junction' with 'Focal adhesion' and have 'hemi-adherens junction' as an exact synonym.
> The only change to the definition would be to remove the word "small" as it's more of a 'relative to what I see when doing EM'.

Hi Helen, this is so helpful. Thank you so much for checking this. According to AmiGO there is only one experimental 'connecting hemi-adherens junction' annotation, and it is from FlyBase, so I agree the merge will be a good solution. And thank you for pointing out that 'small' in the definition should be removed.

**Comment by BarbaraCzub** [comment]
> With regards to 'apical hemi-adherens junction' - we had one annotation and it was not very good and now we have none! So, from our perspective, obsolete away!
> 
> However.....flies and worms do have apical adhesion complexes (that have sometimes been called 'apical hemi-adherens junction') that are super interesting, although not mega-defined, that link epidermal cells to the cuticlle. In flies, these cuticle attachment sites are linked to the microtubule cytoskeleton that transverses the cell to the basal junction. In worms, a similar contact exists but linked to intermediate filaments (which flies don't have). So, an apical junction term or cuticle attachment site, might be useful for us cuticle-bearing beasties. What say ye @vanaukenk ?
> I will do more digging later.

There is GO:0043296 'apical junction complex' but it is not restricted to invertebrates:
Definition: "A functional unit located near the cell apex at the points of contact between epithelial cells, which in vertebrates is composed of the tight junction, the zonula adherens, and desmosomes and in some invertebrates, such as Drosophila, is composed of the subapical complex (SAC), the zonula adherens and the septate junction. Functions in the regulation of cell polarity, tissue integrity and intercellular adhesion and permeability. PMID:12525486 PMID:15196556"

It has a direct child: GO:0035003 'subapical complex', which appears to be specific to invertebrates:
Definition: "The most apical region of the lateral plasma membrane of an invertebrate epithelial cell. The subapical complex lies above the zonula adherens and the septate junction, and is comparable to the position of the tight junction of vertebrate cells. PMID:11752566 PMID:12500938"
29 of the 31 experimental annotations are for flies [here](https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0035003&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants), but there are also 2 UniProt annotations for human proteins (atm there is no taxon constraint associated with this term that would prevent it) (cc @pgarmiri).

**Comment by hattrill** [comment]
I think these as cell-cell contacts are ok. I will check.

**Comment by BarbaraCzub** [comment]
To do:

- [ ] Merge 'connecting hemi-adherens junction' into 'focal adhesion'. Make 'hemi-adherens junction' an exact synonym.

- [ ] Remove the word 'small' from the definition of the 'focal adhesion' suggested above. Add references for 'hemi-adherens junciton' to the 'focal adhesion' definition.

- [ ] Need a decision about ‘apical hemi-adherens junction’. It has zero GO annotations. Should it also be merged into 'apical junction complex' and become a (related or exact?) synonym?

**Comment by BarbaraCzub** [comment]
#18170

**Comment by hattrill** [comment]
I think that 'apical hemi-adherens junction’ actually refers to cuticle attachment points found in worms and flies. I will look up the references, but I have seen this term used when examining EM images.

**Comment by BarbaraCzub** [comment]
Thanks, Helen, ok, I won't be doing anything to 'apical hemi-adherens junction’ for now.

**Comment by hattrill** [comment]
Sorry, Barbara....have just ammended comment :)
Bit of cross-posting!

**Comment by BarbaraCzub** [comment]
Hi Helen, I think obsoletion is a sensible suggestion. According to QuickGO this term had been created back in 2001, so it appears nobody has used it for almost 20 years...

<img width="1094" alt="Screenshot 2019-11-18 at 10 37 05" src="https://user-images.githubusercontent.com/16541096/69033168-65531980-09ef-11ea-9555-85545a94c047.png">

**Comment by hattrill** [comment]
A long but sad life :(

**Comment by BarbaraCzub** [comment]
All right, I'll send out an obsoletion notice. Thanks, for all your help with this! :)

**Comment by BarbaraCzub** [comment]
- [ ] obsolete: 'connecting hemi-adherens junction' (not used for GO annotation at all since 2001 when it was created, has no children, is not a part of any subset/slim)
