### ISSUE TITLE
add synonym phosphopantetheinyl transferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18138]
tio
holo-[acyl-carrier-protein] synthase activity

tks
val

**Comment by hdrabkin** [comment]
'tio'  ?
note '4'-phosphopantetheinyl transferase activity ' , and '	4'-phosphopantetheinyltransferase activity ' are already synonyms,

**Comment by ValWood** [comment]
when i search  quickGo with  the text used in the paper

"phosphopantetheinyl transferase activity"

I could not find it. It took quite a while for me to track it down. I had to find an annotated entry

I wanted to save other people the time. ....

**Comment by hdrabkin** [comment]
Strange because I searched in our web browser and it could find it 'buried" in the 4- terms. Most likley your browser doesn't allow not searching on whole words. I'll add them won't hurt. But what does the 'tio' mean (it's too early in the morning for me yet; only 2 cups of coffee).

**Comment by ValWood** [comment]
I think it means typo

to

The search definitely doesn't work.

phosphopantetheinyltransferase activity
is top hit
phosphopantetheinyl transferase activity isn't in the list

**Comment by hdrabkin** [comment]
done 8-)
