### ISSUE TITLE
ntr: ds/ssDNA junction-specific dsDNA endonuclease

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18134]
activity MF term to use for pombe Slx1 (more details of substrate prefs & cleavage locations in paper; assayed on Y-shaped and stem-loop structures)

name: double-strand/single-strand DNA junction-specific double-stranded DNA endodeoxyribonuclease activity 
def: Catalysis of the endonucleolytic cleavage of double-stranded DNA near a double-strand/single-strand DNA junction. [PMID:14528010]
is_a: GO:1990238 ! double-stranded DNA endodeoxyribonuclease activity

**Comment by mah11** [comment]
fyi, I haven't found anything in RHEA that helped me

**Comment by mah11** [comment]
at @pgaudet's invitation in the GO meeting, pinging my open tickets

**Comment by hdrabkin** [comment]
This afternoon after meeting

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106332
+name: ds/ssDNA junction-specific dsDNA endonuclease activity

**Comment by mah11** [comment]
woohoo, thank you :)
