### ISSUE TITLE
ntr:rhamnolipid biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18132]
rhamnolipid biosynthesis
positive regulation of rhamnolipid biosynthesis

The chemical reactions and pathways resulting in the formation/production of a glycolipid surfactant that acts as a bacterial  biofilm dispersal
Found in Pseudomonas aeruginosa and other xxx bacteria
(I see Mycolicibacterium and Streptomyces? )

synonyms rhamnolipid production

parents
GO:0009247   glycolipid biosynthetic process

PMID:28715477

**Comment by ukemi** [comment]
The parent will be determined by ChEBI.

**Comment by ValWood** [comment]
Hi Harold, Is there a problem with this new term? Let me know if you nee
d any more information.

**Comment by hdrabkin** [comment]
somehow got lost in the chaos; going in today

**Comment by hdrabkin** [comment]
+id: GO:0106236
+name: rhamnolipid biosynthesis
done
