### ISSUE TITLE
new term request: Lewis x epitope biosynthetic process

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#18144]
see PMID:23000574

**Comment by ukemi** [comment]
This is a carbohydrate modification, also known for quite some time as SSEA-1. It is at least partially catalyzed by Fut9. 
CHEBI:59294

**Comment by ValWood** [comment]
So @ukeni @hdrabkin  is this in scope of GO?
Or should it be curated as a modification
and requested from https://github.com/HUPO-PSI/psi-mod-CV/ ?

**Comment by deustp01** [comment]
>It is at least partially catalyzed by Fut9.

But only partly. It's synthesis is a multistep process (PMID: 23019334) and at a glance it looks like the process builds the full Lewis tetrasaccharide by adding monosaccharide units so it may be a specific kind of  GO:0006486 protein glycosylation or  GO:0030259 lipid glycosylation, depending on the substrate on which the glyco moiety gets assembled.
The image is from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3501042/

<img width="707" alt="Screen Shot 2020-11-05 at 1 40 16 PM" src="https://user-images.githubusercontent.com/12737623/98283034-0d4d5400-1f6d-11eb-955c-6f762f4386f9.png"

But only partly. It's synthesis is a multistep process (PMID: 23019334) and at a glance it looks like the process builds the full Lewis tetrasaccharide by adding monosaccharide units so it may be a specific kind of  GO:0006486 protein glycosylation or  GO:0030259 lipid glycosylation, depending on the substrate on which the glyco moiety gets assembled.

**Comment by addiehl** [comment]
Seems like a valid process to me

**Comment by hdrabkin** [comment]
Requester needs to 
1. make def
2. indicate potential children.
3. assume  PMID:23000574 will suffice as reference.

**Comment by ValWood** [comment]
@Argoudpuy this  is what we have already 
https://www.ebi.ac.uk/QuickGO/term/GO:0008417
so the new terms  request definition will be based on the appropriate parent definition.

**Comment by hdrabkin** [comment]
SO GO:0005975  carbohydrate metabolic process would be a good parent for this process term?

**Comment by pgaudet** [comment]
Added LD 


'metabolic process'
and 'has primary output' some 'alpha-L-Fucp-(1->3)-[beta-D-Galp-(1->4)]-beta-D-GlcpNAc' (CHEBI:59294)
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:59294
