### ISSUE TITLE
GO terms mentioning EC:4.1.99.5

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18148]
Hi,

There are three GO terms with EC:4.1.99.5 in the xref and/or definition line.
I think one or two of these EC mentions need to be removed, but the situation is a bit unclear (to me).
Would appreciate an expert taking a look.

Q1. Should EC:4.1.99.5 be included as an xref/in the definition of all three GO terms?
Q2. If "aldehyde oxygenase (deformylating) activity" and "aldehyde decarbonylase activity" really are different activities, then does that mean EC are wrong to have 'Aldehyde decarbonylase' as a synonym of EC:4.1.99.5?

Below are the GO term entries, a screenshot of their relationships, and the EC entry:

**[Term]
id: GO:1990465
name: aldehyde oxygenase (deformylating) activity**
namespace: molecular_function
def: "Catalysis of the reaction a long-chain aldehyde + O(2) + 2 NADPH = an alkane + formate + H(2)O + 2 NADP(+)." [GOC:mengo_curators, PMID:22947199]
xref: EC:4.1.99.5
is_a: GO:0016830 ! carbon-carbon lyase activity

**[Term]
id: GO:0071771
name: aldehyde decarbonylase activity**
namespace: molecular_function
def: "Catalysis of the reaction: a C(n) aldehyde = C(n-1) alkane + CO." [GOC:kad, PMID:6593720, PMID:8718622]
synonym: "decarbonylase activity" EXACT [EC:4.1.99.5, GOC:kad, GOC:mah]
xref: EC:4.1.99
is_a: GO:0016830 ! carbon-carbon lyase activity

**[Term]
id: GO:0009924
name: octadecanal decarbonylase activity**
namespace: molecular_function
def: "Catalysis of the reaction: octadecanal = heptadecane + CO." [EC:4.1.99.5, GOC:tb]
synonym: "octadecanal alkane-lyase activity" EXACT []
xref: EC:4.1.99.5
xref: MetaCyc:OCTADECANAL-DECARBONYLASE-RXN
xref: RHEA:30415
is_a: GO:0071771 ! aldehyde decarbonylase activity

**https://enzyme.expasy.org/EC/4.1.99.5
ID   4.1.99.5
DE   Aldehyde oxygenase (deformylating).
AN   Aldehyde decarbonylase.**
CA   A long-chain aldehyde + O(2) + 2 NADPH = an alkane + formate + H(2)O +
CA   2 NADP(+).
CF   Fe cation.
CC   -!- Involved in the biosynthesis of alkanes.
CC   -!- The enzyme from the cyanobacterium Nostoc punctiforme PCC 73102 is
CC       only active in vitro in the presence of ferredoxin, ferredoxin
CC       reductase and NADPH, and produces mostly C(15) to C(17) alkanes.
CC   -!- The enzyme from pea (Pisum sativum) produces alkanes of chain length
CC       C18 to C32 and is inhibited by metal-chelating agents.

![Screen Shot 2019-11-12 at 08 19 02](https://user-images.githubusercontent.com/16306861/68654097-23c0fb00-0525-11ea-88ee-12b840753de9.png)

**Comment by hdrabkin** [comment]
RHEA:21440 added to GO:1990465
GO:0071771 does not have EC:4.1.99 but has EC:4.1.99.5 already;

**Comment by sjm41** [comment]
Hi Harold,

_GO:0071771 does not have EC:4.1.99 but has EC:4.1.99.5 already but reaction seems way less specific; remove the EC mapping_
Hmm, yes, looks like the full EC got added to that term sometime between GO release 2019-10-07 and 2019-12-09.
Anyway, you're now removing it anyway, so that's all OK!
Can/Did you remove it from the synonym line too?


What about the other two GO terms I mentioned? Do you think it's accurate/appropriate to have that EC xref on both of those?
