### ISSUE TITLE
EC:4.1.99 xrefs to remove

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18149]
4.1.99.- is for all "Other carbon-carbon lyases" in EC:
https://enzyme.expasy.org/EC/4.1.99.-

As such, I think it needs to be removed as an xref on these more specific GO terms:

[Term]
id: GO:0003913
name: DNA photolyase activity
xref: EC:4.1.99

[Term]
id: GO:0034579
name: (1-methylpentyl)succinate synthase activity
xref: EC:4.1.99

[Term]
id: GO:0071771
name: aldehyde decarbonylase activity
xref: EC:4.1.99
**N.B. see related ticket on this particular term - #18148**

**Comment by hdrabkin** [comment]
GO:0003913; updated to EC:4.1.99.3 and RHEA:10672
GO:0034579; removed 
GO:0071771; go def does not agree with assigned EC (4.1.99.5) used for def, and the gene mentioned in the publication uses the RHEA def I would get looking up 4.1.99.5 def and not the GO Def. 
@tberardini , this term was requested by Kate Dreher of Tair; can you trace? I think the def should be 
A long-chain aldehyde + O(2) + 2 NADPH <=> an alkane + formate + H(2)O + 2 NADP(+) (from EC def, to be changed to RHEA def 
a long-chain fatty aldehyde + H(+) + 2 NADPH + O2 = a long-chain alkane + formate + H2O + 2 NADP(+)

**Comment by sjm41** [comment]
GO:0003913; updated to EC:4.1.99.3 and RHEA:10672

I'm not sure that's right.
GO:0003913 is "DNA photolyase activity"
EC:4.1.99.3 is "Deoxyribodipyrimidine photo-lyase." 

and a child of GO:0003913 is "deoxyribodipyrimidine photo-lyase activity" (GO:0003904) that already has the specific EC:4.1.99.3 xref.

So I think GO:0003913/"DNA photolyase activity" can't have an EC xref.

**Comment by sjm41** [comment]
Hi Harold - just checking you saw my last reply on this?

**Comment by sjm41** [comment]
@tberardini Hi Tanya - Any thoughts on this, or the related #18148?

**Comment by hdrabkin** [comment]
I made the assignment based on DNA photolyase as a synonym in EC:4.1.99.3; 
https://enzyme.expasy.org/EC/4.1.99.3
However, I will move the RHEA

**Comment by sjm41** [comment]
Ah, I see.
I guess we'll then have two GO terms with the same EC xref - is that OK?

[Term]
id: GO:0003913
name: DNA photolyase activity
def: "Catalysis of the repair of a photoproduct resulting from ultraviolet irradiation of two adjacent pyrimidine residues in DNA." [GOC:mah, PMID:11124949]
xref: EC:4.1.99.3

[Term]
id: GO:0003904
name: deoxyribodipyrimidine photo-lyase activity
def: "Catalysis of the reaction: cyclobutadipyrimidine (in DNA) = 2 pyrimidine residues (in DNA). This reaction represents the reactivation of irradiated DNA by light." [EC:4.1.99.3]
xref: EC:4.1.99.3

**Comment by hdrabkin** [comment]
Yes absolutely because the EC is more about mechanism whereas RHEA is about the substrates and products. 
However, you know looking at the def "...two adjacent pyrimidine residues" in one  and .. cyclobutadipyrimidine  (in DNA); I can't really think of how  the two pyrimidines would be anthing other than adjacent.     Maybe these should be merged

**Comment by sjm41** [comment]
Note that id: GO:0003913 (DNA photolyase activity) is actually a parent of these two child terms, implying there must be some (intended) difference in scope of the 3 of them:

[Term]
id: GO:0003904
name: deoxyribodipyrimidine photo-lyase activity
def: "Catalysis of the reaction: cyclobutadipyrimidine (in DNA) = 2 pyrimidine residues (in DNA). This reaction represents the reactivation of irradiated DNA by light." [EC:4.1.99.3]
xref: EC:4.1.99.3

id: GO:0003914
name: DNA (6-4) photolyase activity
def: "Catalysis of the reaction: pyrimidine-pyrimidone (6-4) photoproduct (in DNA) = 2 pyrimidine residues (in DNA). Catalyzes the reactivation of ultraviolet-irradiated DNA." [GOC:mah, PMID:11124949]
xref: EC:4.1.99.13

**Comment by hdrabkin** [comment]
Hm.
The 6-4 is a specific reactant apparently occurring 33% of the time 
https://en.wikipedia.org/wiki/Pyrimidine_dimer

If anything,  GO:0003913 and GO:0003904 appear to be the same, but GO:0003904 is more specific. But apparently most people think of the 6,6,5,5 dimer unless otherwise noted.
see 
https://www.researchgate.net/figure/Pyrimidine-dimers-are-the-main-UV-induced-DNA-photoproducts-and-affect-the-phosphodiester_fig1_323371532

**Comment by mah11** [comment]
I haven't looked at these in many years, but I did put in some of the definitions back in the day. They are indeed a bit different, as Steven has inferred/guessed. There are (at least) two possible photoproducts that can form when UV hits two adjacent pyrimidines.

- GO:0003913 is for either.
- GO:0003904 is_a GO:0003913, and refers specifically to cyclobutane pyrimidine dimer (CPD)
- GO:0003914 is_a GO:0003913, and refers specifically to 6-4 photoproduct (6-4PP)

I found the introduction to https://doi.org/10.1093/nar/gkz359 helpful to dredge up the memory. There may be room to improve the the text defs, and I really can't help with the ER xrefs, but the ontology structure looks correct.

**Comment by hdrabkin** [comment]
No wait. I take back the merge.
The RHEA that goes with the EC and  will go with GO:0003904 and not GO:0003913,   specifically uses CHEBI term CHEBI:65263 for the 6,6,5,5

**Comment by hdrabkin** [comment]
Also requesting a RHEA for the 6-4 product while I"m at it.

**Comment by hdrabkin** [comment]
RHEA:62232 thymidine(6-4)thymidine in DNA = thymidine dimer in DNA
RHEA:62236 cytidine(6-4)cytidine in DNA = cytosine dimer in DNA + H+
RHEA:62240 thymidine(6-4)cytidine in DNA = thymine-cytidine dinucleotide in DNA
RHEA:62244 cytidine(6-4)thymidine in DNA = cytidine-thymine dinucleotide in DNA

They will be linked to EC 4.1.99.13, but the generic reaction will still be a
text reaction, as we cannot create "a pyrimidine" in Rhea, for that cytosine
and thymine are too different. The reaction should become available in release
2020_02 tentatively scheduled for 26 February 2020.

**Comment by sjm41** [comment]
Hi Harold,
I'm just catching up on this thread....
I think one conclusion from this (particularly reading Midori's comment of 22nd Nov) is that EC 4.1.99.3 should only be an xref on GO:0003904, right?
But I still see it on the parent term (GO:0003913), though it's not in the right format:
==
id: GO:0003913
name: DNA photolyase activity
namespace: molecular_function
def: "Catalysis of the repair of a photoproduct resulting from ultraviolet irradiation of two adjacent pyrimidine residues in DNA." [GOC:mah, PMID:11124949]
xref: EC:\:4.1.99.3
==

Maybe you tried to delete it but something went wrong??

**Comment by hdrabkin** [comment]
apparently something did. I'm surprised that the :: is not picked up in a travis check. I'm going in now to fix

**Comment by sjm41** [comment]
Looks like the syntax of the malformed xref got modified when I copied and pasted. It's actually "xref: EC:\:4.1.99.3"

**Comment by hdrabkin** [comment]
Gone.
