### ISSUE TITLE
glycosylphosphatidylinositol diacylglycerol-lyase activity (GO:0047396) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18145]
**glycosylphosphatidylinositol diacylglycerol-lyase activity (GO:0047396)**
Def: Catalysis of the reaction: 6-(alpha-D-glucosaminyl)-1-phosphatidyl-1D-myo-inositol = 1,2-diacyl-sn-glycerol + 6-(alpha-D-glucosaminyl)-1D-myo-inositol 1,2-cyclic phosphate.
Xrefs: EC:4.6.1.14, RHEA:14333

This term is currently an is_a child of these two terms:
1. phosphorus-oxygen lyase activity (GO:0016849) Def: Catalysis of the cleavage of a phosphorus-oxygen bond by other means than by hydrolysis or oxidation, or conversely adding a group to a double bond. Xref: EC:4.6.
=> This seems fine.

2. allene-oxide cyclase activity (GO:0046423) Def: Catalysis of the reaction: (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate = (15Z)-12-oxophyto-10,15-dienoate. Xrefs: EC:5.3.99.6, RHEA:22592
=> This doesn't look right.  That is, GO:0047396 doesn't appear to be a subclass of this activity.

Could somebody knowledgable check this?  @kaxelsen perhaps?

**Comment by sjm41** [comment]
Hi
Any thoughts/insight on this one guys?

**Comment by hdrabkin** [comment]
Missed this; remove one parent. done

**Comment by sjm41** [comment]
Thanks Harold.
