### ISSUE TITLE
NTRs: "basal body patch" & "subapical part of cell"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#18156]
For annotation of Mahuzier et al. 2018 PMID:29891944, I need two additional CC terms.

name: basal body patch
def: The region in the apical portion of multiciliated epithelial cells where the ciliary basal bodies cluster. [PMID:29891944, PMID:20685736, PMID:20164345, GOC:krc]
synonym_exact: centriolar patch
is_a: cellular anatomical entity | GO:0110165
part_of: apical part of cell | GO:0045177

name: subapical part of cell
def: The region of a polarized cell that is just below the apical region. For example, in a polarized epithelial cell, the apical region has an exposed surface and lies opposite to the basal lamina that separates the epithelium from other tissue so the subapical region is further from the exposed surface and closer to the basal lamina. [PMID:29891944, GOC:krc]
is_a: cellular anatomical entity | GO:0110165

**Comment by pgaudet** [comment]
Hi @krchristie : now that we have removed 'nuclear part', should we create terms like 'subapical part of cell' ? That seems inconsistent. 
(Note that we still have a few terms such as 
'plasma membrane part of cell junction' <http://purl.obolibrary.org/obo/GO_0061466>
'plasma membrane part of cell-substrate junction.' <http://purl.obolibrary.org/obo/GO_0061464>
'plasma membrane part of hemidesmosome' <http://purl.obolibrary.org/obo/GO_0061465>

@ukemi were these forgotten? )

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet - I thought about that, but we still have the term 'apical part of cell'. I was thinking it through, I don't think this is a 'part' term, but a region term. We could call it 'subapical region of cell' and it would mean the same thing.

**Comment by krchristie** [comment]
@pgaudet - Looking at the three terms you listed above, they don't seem like they are the same type as the offending 'part' terms that were removed, e.g. `nuclear part`. 

Terms like `nuclear part` were removed because they were used as grouping terms in order to provide is_a parentage for terms that did not otherwise have an is_a parent but the `nuclear part` term did not actually specify any specific region of the nucleaus.

In contrast, the three terms you mentioned as well as the existing `apical part of cell` and the `subapical part of cell` term that I need for annotation are specifying specific subregions of the cell than cannot otherwise be annotated, similarly to other existing terms like `extracellular region`.

**Comment by pgaudet** [comment]
OK sounds good, thanks !
