### ISSUE TITLE
NTR: Ceramide-1-phosphate phosphatase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#18165]
Hi,
could you please consider creating a term describing the activity of enzymes that dephosphorylate ceramide-1-phosphate:

Catalysis of the reaction: ceramide-1-phosphate + H2O = ceramide+ phosphate.
or more precisely :
H2O + N-acylsphing-4-enine 1-phosphate = an N-acylsphing-4-enine + phosphate

as described for instance in PubMed=10359651

Thanks for your help.
Lionel

**Comment by hdrabkin** [comment]
Since an N-acylsphingoid base 1-phosphate is a synonym for ceramide-1-phosphate (CHEBI: 84404, the anionic form); no synonym mentioned for neutral form (CHEBI:13956

This looks like RHEA:50888 : an N-acylsphingoid base 1-phosphate + H2O = N-acyl-sphingoid base + phosphate (this RHEA does use  the anionic form 88404 although the RHEA text def does not.

--

**Comment by lbreuza** [comment]
Hi Harold,
not sure to understand your comment. Is there an existing GO term I could use to describe the activity of my protein?
Best, Lionel

**Comment by hdrabkin** [comment]
No, but I think I'll be using the RHEA as the xref for the term you request. BTW, what parent do  you suggest?

**Comment by lbreuza** [comment]
GO:0042392 sphingosine-1-phosphate phosphatase activity which describes the same relation for a related lipid is a child of GO:0016791 phosphatase activity. This could be the direct parent. Alternatively you could create an intermediate parent for sphingolipid phosphatase activity and/or GO:0042577 lipid phosphatase activity. Please note that GO:0042392 sphingosine-1-phosphate phosphatase activity should also be moved to that parent.

**Comment by hdrabkin** [comment]
done; ntr + assign parents for it and  to GO:0042392 as suggested to GO:0042577 lipid phosphatase activity
