### ISSUE TITLE
NTR: GO terms for EC 5.1.3.32 and 5.4.99.62

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#18167]
EC 5.1.3.32, L-rhamnose mutarotase activity, definition: Catalysis of the reaction: alpha-L-rhamnose = beta-L-rhamnose.  Child term of GO:0016857.

EC 5.4.99.62, D-ribose pyranase activity, definition: Catalysis of the reaction: beta-D-ribopyranose = beta-D-ribofuranose.  Child term of GO:0016866.

Thanks!

**Comment by ukemi** [comment]
RHEA:25584 and RHEA:25432
