### ISSUE TITLE
bad parentage for hydrogen peroxide terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18178]
GO:0042542    response to hydrogen peroxide
has
GO:0046677    response to antibiotic 
ancestor

**Comment by ValWood** [comment]
GO:0042743    hydrogen peroxide metabolic process
has
GO:0016999   antibiotic metabolic process

**Comment by krchristie** [comment]
These will be fixed if we act on my proposal to stop reasoning over roles. 

This table shows all of the relationship changes for various hydrogen peroxide terms that will occur if we drop reasoning over roles. The two relationships @ValWood listed are indicated with stars in those rows.

Term | ID | Relationship change | Related term
-- | -- | -- | --
cellular response to hydrogen peroxide | GO:0070301 | Removed SubClassOf | cellular response to antibiotic
cellular response to hydrogen peroxide | GO:0070301 | Removed SubClassOf | cellular response to drug
cellular response to hydrogen peroxide | GO:0070301 | Removed SubClassOf | cellular response to toxic substance
hydrogen peroxide biosynthetic process | GO:0050665 | Removed SubClassOf | antibiotic biosynthetic process
hydrogen peroxide biosynthetic process | GO:0050665 | Removed SubClassOf | cofactor biosynthetic process
hydrogen peroxide biosynthetic   process | GO:0050665 | Added SubClassOf | cellular biosynthetic process
hydrogen peroxide catabolic process | GO:0042744 | Removed SubClassOf | antibiotic catabolic process
hydrogen peroxide catabolic process | GO:0042744 | Removed SubClassOf | cofactor catabolic process
hydrogen peroxide catabolic process | GO:0042744 | Removed SubClassOf | drug catabolic process
hydrogen peroxide catabolic   process | GO:0042744 | Added SubClassOf | cellular catabolic process
**hydrogen peroxide metabolic process | GO:0042743 | Removed SubClassOf | antibiotic metabolic process**
hydrogen peroxide metabolic process | GO:0042743 | Removed SubClassOf | cofactor metabolic process
hydrogen peroxide transmembrane transport | GO:0080170 | Removed SubClassOf | cofactor transport
hydrogen peroxide transmembrane transport | GO:0080170 | Removed SubClassOf | drug transmembrane transport
hydrogen peroxide   transmembrane transport | GO:0080170 | Added SubClassOf | transmembrane transport
negative regulation of hydrogen peroxide   metabolic process | GO:0010727 | Removed SubClassOf | negative regulation of cofactor metabolic process
negative regulation of hydrogen   peroxide-induced cell death | GO:1903206 | Removed SubClassOf | negative regulation of cellular response to drug
positive regulation of hydrogen peroxide   metabolic process | GO:0010726 | Removed SubClassOf | positive regulation of cofactor metabolic process
positive regulation of hydrogen   peroxide-induced cell death | GO:1905206 | Removed SubClassOf | positive regulation of cellular response to drug
regulation of hydrogen peroxide metabolic   process | GO:0010310 | Removed SubClassOf | regulation of cofactor metabolic process
regulation of hydrogen peroxide-induced   cell death | GO:1903205 | Removed SubClassOf | regulation of cellular response to drug
**response to hydrogen peroxide | GO:0042542 | Removed SubClassOf | response to antibiotic**
response to hydrogen peroxide | GO:0042542 | Removed SubClassOf | response to drug
response to hydrogen peroxide | GO:0042542 | Removed SubClassOf | response to toxic substance

**Comment by krchristie** [comment]
This table summarizes the 24 changes related to hydrogen peroxide terms with respect to some general categories. 21 relationships involving the roles `antibiotic` `cofactor` `drug`, and `toxin` will be removed. 3 relationships to general terms for cellular metabolism or transport will be added.

While I haven't looked at everything in as much detail as I've just done for these hydrogen peroxide terms, I think this is a good representative sample of the kinds of changes that comprise a large portion of the changes that will occur if we stop reasoning over roles.



category | Added SubClassOf | Removed SubClassOf
-- | -- | --
metabolism, general | 2 |  
transport, general | 1 |  
antibiotic |   | 5
cofactor |   | 7
drug |   | 7
toxin |   | 2
Grand Total | 3 | 21

**Comment by krchristie** [comment]
This was fixed by this ticket:
**cessation of reasoning over ChEBI roles, i.e. stop inferring relationships like "ATP binding" is_a "drug binding"** #19479
