### ISSUE TITLE
Coq6 is required for the C5-hydroxylation and C4-deamination

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18184]
how to locate a Rhea reaction in GO

I am looking for

https://www.rhea-db.org/reaction?id=20361

PMID: 21944752
PMID: 26260787

**Comment by deustp01** [comment]
Indeed, how to do this (especially how to do it without having Protege running with the OWL ontology loaded)?

**Comment by ukemi** [comment]
That would be a way that certainly works. I though AMIGO2 used to search xrefs in the ontology search, but maybe not. @kltm? I think this issue should be on the AmiGO2 tracker.

**Comment by ukemi** [comment]
Looks like we don't have this Rhea reaction as an MF in GO.

**Comment by ukemi** [comment]
Do you want it? I assume yes.

**Comment by pgaudet** [comment]
I dont think AmiGO searches cross-references. I agree it would be useful.

**Comment by ValWood** [comment]
Yes please!

I think there are 2 reactions  performed by  coq6

PMID: 21944752 Coenzyme Q biosynthesis: Coq6 is required for the C5-hydroxylation reaction

PMID: 26260787 Coq6 is responsible for the C4-deamination reaction in coenzyme Q biosynthesi

I'm not sure why both are PubMed IDs are attached to the same reaction?

**Comment by kltm** [comment]
@ukemi `definition_xref` is currently the only usable field for this. The interface is not wired to support it for various reason and was likely removed some time ago to reduce noise.
The bulk search interface could have such a thing added easily (but is not yet publicly available http://amigo.geneontology.org/amigo/bulk_search/ontology ).
AmiGO does support the reverse lookup, however, through annotations. E.g.: http://amigo.geneontology.org/amigo/reference?ref_id=PMID%3A26260787

**Comment by ValWood** [comment]
The reverse lookup won't help us here. There is no GO annotation yet...

But 
>definition_xref is currently the only usable field for this. 

should work then? (A Rhea xref would be a definition_xref, no?)

**Comment by ValWood** [comment]
pinging @hdrabkin  is this in the pipeline. No hurry - just checking it hasn't been added via another route

**Comment by hdrabkin** [comment]
So this is requesting 2 new MFs?
can you supply a reaction for them. 
 Coenzyme Q biosynthesis: Coq6 is required for the C5-hydroxylation reaction
Coq6 is responsible for the C4-deamination reaction in coenzyme Q biosynthesis

Is everything I need in Fig 1
I'll have to search on each of the structures in chebi to get the right reactants.

**Comment by ValWood** [comment]
sorry, I think there are 2 reactions performed (if I understood correctly). This isn't studied in fission yeast so I am trying to find the information from elsewhere.


1.  2-octaprenyl-6-methoxyphenol hydroxylase activity
which can be inferred from
https://www.uniprot.org/uniprot/P25534 (I got this info from SGD)
but here is a eukaryotic evidence https://pubmed.ncbi.nlm.nih.gov/21944752/
This term is available.

2. I am looking to annotate the more recent finding
Coq6 is responsible for the C4-deamination reaction in coenzyme Q biosynthesis in Saccharomyces cerevisiae
https://pubmed.ncbi.nlm.nih.gov/26260787/
I don't think this other activity annotated anywhere yet?

Abstract
The yeast Saccharomyces cerevisiae is able to use para-aminobenzoic acid (pABA) in addition to 4-hydroxybenzoic acid as a precursor of coenzyme Q, a redox lipid essential to the function of the mitochondrial respiratory chain. The biosynthesis of coenzyme Q from pABA requires a deamination reaction at position C4 of the benzene ring to substitute the amino group with an hydroxyl group. We show here that the FAD-dependent monooxygenase Coq6, which is known to hydroxylate position C5, also deaminates position C4 in a reaction implicating molecular oxygen, as demonstrated with labeling experiments. We identify mutations in Coq6 that abrogate the C4-deamination activity, whereas preserving the C5-hydroxylation activity. Several results support that the deletion of Coq9 impacts Coq6, thus explaining the C4-deamination defect observed in Δcoq9 cells. The vast majority of flavin monooxygenases catalyze hydroxylation reactions on a single position of their substrate. Coq6 is thus a rare example of a flavin monooxygenase that is able to act on two different carbon atoms of its C4-aminated substrate, allowing its deamination and ultimately its conversion into coenzyme Q by the other proteins constituting the coenzyme Q biosynthetic pathway.

This isn't annotated   in SGD yet.
The reaction  is in figure 1 
https://pubmed.ncbi.nlm.nih.gov/26260787/#&gid=article-figures&pid=figure-1-uid-0

but is this reaction  a biologically relevant part of coenzyme Q biosynthesis?
I  was looking for it because I thought it was important but  I don't understand how it fits into the pathway.

Tagging @srengel @edwong57  for SGD.
I can find the publication in SGD but  no curation is yet associated with it?
https://www.yeastgenome.org/reference/S000181145

**Comment by hdrabkin** [comment]
Trying to close this; the purpose of this ticket is not clear to me.  It's marked RHEA pending. 
2-octaprenyl-6-methoxyphenol hydroxylase activity is GO:0008681; it has a RHEA:29407; also has bad 3 digit EC which I am removing (no full ec known, except one form Metacyc but it's a temp id and not linkable) Have written EC about status of their temp id

Replacing def ref  with a PMID found in the metacyc xref

**Comment by ValWood** [comment]
I need the 2 MF terms to annotate coq6. It seems a shame not to annotate a gene product with a molecular function when it is known.

Rhea has one of the MFs annotated on the human entry
https://www.uniprot.org/uniprot/Q9Y2Z9
4-hydroxy-3-all-trans-hexaprenylbenzoate + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = 3,4-dihydroxy-5-all-trans-hexaprenylbenzoate + H2O + 2 oxidized [2Fe-2S]-[ferredoxin]

but the GO annotation is very general:
GO:0016712 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen

**Comment by ValWood** [comment]
Ah I see, you said:
2-octaprenyl-6-methoxyphenol hydroxylase activity is GO:0008681;


but coq6 is both
C5-hydroxylation reaction 
and C4 deamination

but I can just annotate to GO:0008681 so happy for you to close this.

**Comment by hdrabkin** [comment]
Ok, so 2-octaprenyl-6-methoxyphenol hydroxylase activity is GO:0008681

Is the RHEA reaction 4-hydroxy-3-all-trans-hexaprenylbenzoate + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = 3,4-dihydroxy-5-all-trans-hexaprenylbenzoate + H2O + 2 oxidized [2Fe-2S]-[ferredoxin]

The one you need added to GO?

**Comment by hdrabkin** [comment]
THE RHEA RHEA:20361 is not in GO yet, so I will add now and close this.

**Comment by ValWood** [comment]
No, thanks Harold !

**Comment by hdrabkin** [comment]
Too late! already done!
+id: GO:0106364
+name: 4-hydroxy-3-all-trans-hexaprenylbenzoate oxygenase activity

**Comment by hdrabkin** [comment]
RHEA:20361 was added; removing tag..

**Comment by ValWood** [comment]
Hi HArold,

Would either of these parents be correct?

GO:0016709 | oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen | IEA with IPR010971 | GO_REF:0000002 | 6

- | GO:0016712 | oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen

If not, I will request that bot of these mappings are removed.

**Comment by ValWood** [comment]
They aren't are they. I will ask for the mappings to be updated.
