### ISSUE TITLE
Pre-composed terms to obsolete

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18200]
* GO:0060864 positive regulation of floral organ abscission by small GTPase mediated signal transduction: 0 annotations, 0 mappings
* GO:0060868 regulation of vesicle-mediated transport involved in floral organ abscission by small GTPase mediated signal transduction: 0 annotations, 0 mappings
* GO:1903453 RNA interference involved in olfactory learning : 0 annotations, 0 mappings

**Comment by ValWood** [comment]
These look like they can go soon, no annotations.

**Comment by pgaudet** [comment]
A few more 

GO:190137 trehalose   biosynthetic process involved in ascospore formation
GO:1903134 trehalose catabolic process   involved in cellular response to stress
GO:0010680 cinnamic acid biosynthetic   process involved in coumarin metabolism
GO:0010682 cinnamic acid biosynthetic   process involved in flavonoid metabolism
GO:0010679 cinnamic acid biosynthetic   process involved in salicylic acid metabolism
GO:0010681 cinnamic acid biosynthetic   process involved in stilbene metabolism
GO:0060859 regulation of   vesicle-mediated transport involved in floral organ abscission
GO:0035528 UDP-N-acetylglucosamine   biosynthesis involved in chitin biosynthesis'

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 


GO:0060864 positive regulation of floral organ abscission by small GTPase mediated signal transduction:
GO:0060868 regulation of vesicle-mediated transport involved in floral organ abscission by small GTPase mediated signal transduction
GO:1903453 RNA interference involved in olfactory learning
GO:190137 trehalose   biosynthetic process involved in ascospore formation
GO:1903134 trehalose catabolic process   involved in cellular response to stress
GO:0010680 cinnamic acid biosynthetic   process involved in coumarin metabolism
GO:0010682 cinnamic acid biosynthetic   process involved in flavonoid metabolism
GO:0010679 cinnamic acid biosynthetic   process involved in salicylic acid metabolism
GO:0010681 cinnamic acid biosynthetic   process involved in stilbene metabolism
GO:0060859 regulation of   vesicle-mediated transport involved in floral organ abscission
GO:0035528 UDP-N-acetylglucosamine   biosynthesis involved in chitin biosynthesis'


The reason for obsoletion is that these are precomposed terms that do not represent specific pathways and that should be captured as GO-CAM models. 

There are no annotations, no mappings to these terms. These terms are not present in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/18200

Thanks, Pascale
