### ISSUE TITLE
NTR: tachykinin maturation

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#18205]
Hi,
Would you consider adding please:

GO:NEW tachykinin maturation
Is_a GO:0061837 neuropeptide processing
“The process leading to the attainment of the full functional capacity of tachykinin by post-translational proteolytic processing of its neuropeptide precursor.”
PMID:2422168
https://en.wikipedia.org/wiki/Tachykinin_peptides
Synonyms (all exact I think): tachykinin processing, tachykinin biosynthesis, tachykinin peptide maturation, tachykinin peptide processing

GO already has other tachykinin-related terms, as well as ‘maturation’ terms (see e.g. children of ‘peptide hormone processing‘. Thanks.

**Comment by pgaudet** [comment]
Hi @paolaroncaglia 

Is this a specific process ? A more recent paper, PMID:33382413, starts with "The kexin-like proprotein convertases perform the initial proteolytic cleavages that ultimately generate a variety of different mature peptide and proteins, ranging from brain neuropeptides, to endocrine peptide hormones, to structural proteins, among others." 

So, it doesn't seem like this is a specific process ? We would recommend using GO:0061837 neuropeptide processing and an extension for tachykinin CHEBI:140482 ? 

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
Hi @pgaudet ,

Thanks. My request stemmed from text search, not from annotation needs. The older paper I was looking at, and the precedents of other "maturation" terms in GO, led me to think that the request may be in scope for GO. No problem then - feel free to close this ticket.

Best,
Paola

**Comment by pgaudet** [comment]
Thanks for your reply @paolaroncaglia
