### ISSUE TITLE
cortical protein anchoring

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18214]
Do we need the term "cortical protein anchoring"?

I am picking up mappings to 2 proteins, but I already annotated these to the MF term 

microtubule cortical anchor activity 

Furthermore, the definition is too broad:
A process in which a protein or protein complex is maintained in a specific location in the cell cortex.

(this is just maintenance of localization).

Location can be maintained in other ways in addition to "anchoring"

but

maintenance of protein location in cell cortex of cell tip

is a child.

I would suggest to rename to

maintenance of protein location in cell cortex
to match parents and descendants

**Comment by mah11** [comment]
well, you requested it ;) ... back in 2006
#3304

**Comment by hdrabkin** [comment]
Changed and added old name as related synonym
