### ISSUE TITLE
GO:0043495 protein membrane anchor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18217]
GO:0043495 protein membrane anchor

is defined as an adaptor.
Interacting selectively and non-covalently with both a protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location

could it be renamed

GO:0043495 protein membrane adaptor

to make it clear that this is not for "anchors" which might  be intrinsic to a protein and localize itself to the membrane?

This matches better the def, parents and the siblings

**Comment by hdrabkin** [comment]
will use old name as synonym

**Comment by hdrabkin** [comment]
done
