### ISSUE TITLE
NTR psilocybin biosynthetic process and associated reactions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18210]
Hello, 

To annotate fungal secondary metabolites biosynthesis pathways, @marcfeuermann requested the following terms:

+[Term]
+id: GO:0140380
+name: psilocybin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of psilocybin, a psychotropic tryptamine-derived natural product." [PMID:28763571]
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: ends_with GO:0140381 ! 4-hydroxytryptamine 4-phosphate methyltransferase activity
+intersection_of: has_intermediate CHEBI:139217 ! 4-hydroxytryptamine
+intersection_of: has_intermediate CHEBI:139479 ! norbaeocystin
+intersection_of: has_intermediate CHEBI:16765 ! tryptamine
+intersection_of: has_part GO:0140382 ! tryptamine 4-monooxygenase activity
+intersection_of: has_part GO:0140383 ! 4-hydroxytryptamine kinase activity
+intersection_of: has_primary_input CHEBI:16828 ! L-tryptophan
+intersection_of: has_primary_output CHEBI:8614 ! psilocybin
+intersection_of: starts_with GO:0036469 ! L-tryptophan decarboxylase activity
+created_by: pg
+creation_date: 2019-11-20T10:03:05Z
+
+[Term]
+id: GO:0140381
+name: 4-hydroxytryptamine 4-phosphate methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: 2 S-adenosyl-L-methionine (SAM) + 4-hydroxytryptamine 4-phosphate (norbaeocystin) <=> 2 S-adenosyl-L-homocysteine + psilocybin." [PMID:28763571]
+synonym: "norbaeocystin methyltransferase" EXACT []
+synonym: "psilocybin synthase" EXACT []
+xref: EC 2.1.1.345
+xref: RHEA:55568
+is_a: GO:0008168 ! methyltransferase activity
+created_by: pg
+creation_date: 2019-11-20T10:16:28Z
+
+[Term]
+id: GO:0140382
+name: tryptamine 4-monooxygenase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: tryptamine + reduced acceptor + O(2) <=> 4-hydroxytryptamine + acceptor + H(2)O." [PMID:28763571]
+xref: EC 1.14.99.59
+xref: RHEA:15865
+is_a: GO:0004497 ! monooxygenase activity
+created_by: pg
+creation_date: 2019-11-20T10:26:21Z
+
+[Term]
+id: GO:0140383
+name: 4-hydroxytryptamine kinase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: 4-hydroxytryptamine + ATP = 4-hydoxytryptamine 4-phosphate + ADP + H(+)." [PMID:28763571]
+xref: EC:2.7.1.222
+xref: RHEA:55564
+is_a: GO:0016301 ! kinase activity
+created_by: pg
+creation_date: 2019-11-20T10:30:05Z

Also : 
* changed EC:4.1.1.28 -> EC:4.1.1.105

**Comment by pgaudet** [comment]
@ukemi @deustp01 Can you please check the logical definition ? We added all reactions and intermediates. Let me know if this is how to do it. 

Thanks, Pascale

**Comment by ukemi** [comment]
I don't know the pathway that well, but this looks ok to me. It is often not necessary to specify the intermediates unless they are required for further classification.

**Comment by pgaudet** [comment]
Should I add primary input and primary output for the MF ? 

Thanks, Pascale

**Comment by ukemi** [comment]
NO. Those are restircted to metabolism terms. No need to put any participants for MFs, those will all be populated with ChEBI identifiers from Rhea at some point in time.

**Comment by deustp01** [comment]
Nothing from here, because I don't know anything about this biochemistry.

**Comment by pgaudet** [comment]
OK thanks !
