### ISSUE TITLE
Update 'has_intermediate' from GOREL to RO in the ontology

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18229]
1. [Typedef]
id: has_intermediate
name: has intermediate
namespace: external
xref: GOREL:0002008

-> should be RO:0002505

**Comment by ukemi** [comment]
Argh. I thought we cleaned all these up a while ago.

**Comment by pgaudet** [comment]
It looks like it was the last one that has a valid RO. There are 9 more GORELs.
