### ISSUE TITLE
24-hydroxycholesterol 7alpha-hydroxylase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#18243]
Dear GO curators,

I would like to annotate CYP39A1 and CYP7A1 catalytic activities in GO and mapping to RHEA is:
CYP39A1 catalyzes [Rhea:46124] (PMID:25201972)
CYP7A1 catalyzes [RHEA:16093] (11013305)
CYP7A1 catalyzes [Rhea:46124] (11013305)
Maybe we need two GO terms 24 (R)-hydroxycholesterol 7alpha-hydroxylase activity and 24 (S)-hydroxycholesterol 7alpha-hydroxylase activity. 

Thank you very much for your help and looking forward to your feedback.

Nevila Hyka-Nouspikel

**Comment by hdrabkin** [comment]
Hi @nnouspikel 
What would the parents be for these terms?
I see you suggested two terms; Do we have one already?

**Comment by hdrabkin** [comment]
Ah, I see; we already have RHEA:16093 for GO:0033782;   however, the EC id used for this term  1.14.13.99, has been transferred to 1.14.14.26, which maps to a different RHEA RHEA:15129. This is a mess and will need to be straightened out first.

**Comment by ValWood** [comment]
hi @hdrabkin  added a rhea label to this term request, but since it is from December 2019 it might already be done?

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0033782
can this one close?

**Comment by ValWood** [comment]
I see just needs
name: 24-hydroxycholesterol 7alpha-hydroxylase activity ->
name: 24S-hydroxycholesterol 7alpha-hydroxylase activity

?

**Comment by nnouspikel** [comment]
Hi Val

[GO:0033782](https://www.ebi.ac.uk/QuickGO/term/GO:0033782) is mapped to [EC/1.14.14.26](https://enzyme.expasy.org/EC/1.14.14.26)  and [rhea/46124](https://www.rhea-db.org/rhea/46124)

so I believe 24(S)-hydroxycholesterol 7alpha-hydroxylase/monooxygenase activity would be the right GO term to use

24(S)-hydroxycholesterol represents the major metabolite in the brain [LMDB00330](https://lmdb.ca/metabolites/LMDB00330) ; [22891291](https://europepmc.org/article/MED/22891291)

Thanks for your help

**Comment by pgaudet** [comment]
Hi @nnouspikel 

I vhange the  term label of GO:0033782 from 24-hydroxycholesterol 7alpha-hydroxylase activity to 
 **24S**-hydroxycholesterol 7alpha-hydroxylase activity, since this anyways matched the definition. 

Since the R form is a minor metabolite, I propose we dont create the term for now. 

Thanks, Pascale
