### ISSUE TITLE
Obsolete 'protein binding involved in negative regulation of telomere maintenance via telomerase'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18248]
There are 2 annotations by pombase to 'protein binding involved in negative regulation of telomere maintenance via telomerase'. Should we obsolete this term and use 'part of' extension instead? 

@ValWood 

(term was requested here: #10698) 

Thanks, Pascale

**Comment by ValWood** [comment]
yes please, we will post-compose this annotation
v

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:1902496 protein binding involved in negative regulation of telomere maintenance via telomerase'. The reason for obsoletion is that this should be captured as a GO-CAM model. There were 2 annotations to this term (now removed). There are no mappings to this term; this term is not present in any slims. 

Any comments can be added to the issue: geneontology/go-ontology#18248.

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 29th, 2019. Unless objections are received by November 29th, we will assume that you agree to this change.

Thanks, Pascale
