### ISSUE TITLE
ntr: chromosome regions at SO:nnn

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18249]
For some improvements to logical definitions in FYPO, we'd like to request some CC terms for chromosome regions:

id: GO:new1
name: rDNA replication pause site heterochromatin
def: "A region of heterochromatin associated with sites in rDNA repeats where replication forks pause."
intersection_of: GO:0098687 ! chromosomal region
intersection_of: coincident_with SO:0001914
PMID:25417108

id: GO:new2 (modeled on GO:0034507)
name: chromosome, centromeric inner repeat region
namespace: cellular_component
def: "The portion of the centromeric region of a chromosome that contains the inner inverted repeat region of a modular centromere and part of the central core surrounding a non-conserved central region. This region is adjacent to the central core, on each chromosome arm." [SO:0001798]
synonym: "chromosome, centric outer repeat region" RELATED []
intersection_of: GO:0098687 ! chromosomal region
intersection_of: coincident_with SO:0001798 ! regional_centromere_inner_repeat_region
relationship: part_of GO:0000775 ! chromosome, centromeric region
PMID:21437270

The PMIDs above are the ones where we found the phenotypes that would be logically defined using the GO:new terms. That's the best I have on hand to associate with the GO terms, although for GO:new2 @ValWood may know of a suitable paper or review.

also see
https://github.com/obophenotype/upheno/issues/556

**Comment by ValWood** [comment]
I'm not sure about this.

I  seem to remember that a while ago we decided only to include the functionally distinct regions in GO, and not the fine grained sequence regions which could be sO terms

a) The central core (which is where the kinetochore forms) 
GO:0061638    CENP-A containing chromatin
The specialized chromatin located the centromeric core region or the entire centromeric region in organisms with point centromeres, which is enriched for CENP-A-containing nucleosomes. This chromatin forms a 3-dimensional structure which provides a platform for kinetochore assembly and microtubule attachment. PMID:20206496 PMID:22729156


b) the "pericentric regions" which from heterochromatin
and is represented by 
GO:0005721    pericentric heterochromatin
Heterochromatin that is located adjacent to the CENP-A rich centromere 'central core' and characterized by the modified histone H3K9me3. PMID:12019236 PMID:20206496 PMID:22729156


although I am confused that we still have terms like
GO:0034507    chromosome, centromeric outer repeat region

**Comment by ValWood** [comment]
I can't find the ticket though! I thought I did this with @ukemi a year or two ago...

**Comment by mah11** [comment]
Well, if these GO terms go obsolete (or aren't added in the first place) then some FYPO terms lose their current logical definitions. We (@matentzn, @dosumis, and I) may be able to craft a different pattern for them, or they could just do without. But I did promise Nico I would open this ticket ;)

**Comment by ukemi** [comment]
We discussed this on the ontology call yesterday and the group seemed ok with it.

**Comment by ValWood** [comment]
OK< but they still seem to me to be sequence regions rather than cellular components. I would have defined these logically with SO.

**Comment by dosumis** [comment]
The use case is for refering to location in chromatin in some chromosomal region defined SO sequence:

GO has a pattern for making the link to SO - originating in a request from Midori. e.g. see 
![image](https://user-images.githubusercontent.com/112839/69651402-f10c1c00-1067-11ea-8b91-ef853ba6a135.png)

We could potentially post-compose the entity in phenotype terms, but it would be much simpler for us if GO could add the term.

**Comment by ukemi** [comment]
Requested terms in the SO import. #18423

**Comment by ukemi** [comment]
@balhoff, is ontobot configured to run on SO imports?

**Comment by balhoff** [comment]
It wasn't for some reason, but now it is: #18428

**Comment by ukemi** [comment]
Thanks! There is more than just what I added there, but it looks ok. Will merge once the checks pass and then finish up on this ticket.
