### ISSUE TITLE
GO terms with EC:2.7.11 refs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18253]
There are ~20 GO terms with an xref to the partial EC number 2.7.11 (Protein-serine/threonine kinases)
https://enzyme.expasy.org/EC/2.7.11.-

I think only one of these xrefs is appropriate - the rest need to be replace/removed.  My suggestions are below, but should be checked of course.

==

id: GO:0004674
name: protein serine/threonine kinase activity
=> OK 

id: GO:0004675
name: transmembrane receptor protein serine/threonine kinase activity
=> replace with 2.7.11.30  <<<< two rheas; one for each (serine or threonine)

id: GO:0004676
name: 3-phosphoinositide-dependent protein kinase activity
=> remove xref <<<<<< removed

id: GO:0004677
name: DNA-dependent protein kinase activity
=> remove xref <<<<<< removed

id: GO:0004679
name: AMP-activated protein kinase activity
=> replace with 2.7.11.11   <<<<<< has two rheas; one for ser and one for thr

id: GO:0004690
name: cyclic nucleotide-dependent protein kinase activity
=> remove xref  <<<<<< removed

id: GO:0004694
name: eukaryotic translation initiation factor 2alpha kinase activity
=> remove xref <<<<<< removed

id: GO:0004698
name: calcium-dependent protein kinase C activity
=> replace with 2.7.11.13 two rheas; one for each (serine or threonine)

id: GO:0004704
name: NF-kappaB-inducing kinase activity
=> remove xref <<<<<< removed

id: GO:0004705
name: JUN kinase activity
=> remove xref GO:0004705

id: GO:0004706
name: JUN kinase kinase kinase activity
=> remove xref GO:0004706  <<<removed

id: GO:0004708
name: MAP kinase kinase activity
=> replace with 2.7.12.2  <<<< 3 RHEAS for tyr, ser, and thr

id: GO:0004711
name: ribosomal protein S6 kinase activity
=> remove xref  <<<removed

id: GO:0008349
name: MAP kinase kinase kinase kinase activity
=> remove xref  <<< removed

id: GO:0008545
name: JUN kinase kinase activity
=> remove xref <<< removed

id: GO:0016909
name: SAP kinase activity
=> remove xref <<< removed

id: GO:0019199
name: transmembrane receptor protein kinase activity
=> remove xref <<< removed

id: GO:0019912
name: cyclin-dependent protein kinase activating kinase activity
=> remove xref <<< removed

id: GO:0034211
name: GTP-dependent protein kinase activity
=> remove xref <<< removed

**Comment by hdrabkin** [comment]
I'll edit the above in line

**Comment by hdrabkin** [comment]
I put the notes in above so I can revisit; do we (G) want separate terms to correspond to the RHEAs.  I can't request a RHEA that says either Serine or Threonine. 
For annotation purposes, a PRO id for the specific substrate and prodct can be used to add to input/output for the reactions.

**Comment by sjm41** [comment]
Thanks Harold.
Can you clarify whether you are adding the new EC xrefs I suggested even when there are multiple Rhea xrefs?

**Comment by hdrabkin** [comment]
sorry; yes I did add them; turns out I think that the ones you suggested were already used for the definitions anyways.

**Comment by sjm41** [comment]
Great, thanks!
