### ISSUE TITLE
Add ontology description to go-edit

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#18251]
The (under development) OBO dashboard checks that each ontology describes itself with an annotation using the `http://purl.org/dc/elements/1.1/description` property. Can someone comment here with a concise description? I can add the annotation.

**Comment by balhoff** [comment]
Also need to add the title using `http://purl.org/dc/elements/1.1/title`.

**Comment by ukemi** [comment]
Maybe something from @thomaspd's review paper?

**Comment by ukemi** [comment]
From the GO Homepage: The network of biological classes describing the current best representation of the “universe” of biology. The molecular functions, cellular locations, and processes gene products may carry out. 
@thomaspd, is this ok?

**Comment by pgaudet** [comment]
@thomaspd says use this "The Gene Ontology (GO) provides a framework and set of concepts for describing the functions of gene products from all organisms."
