### ISSUE TITLE
'regulates levels of' relation now obsolete in GO

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#18254]
It looks like the RO relation 'regulates levels of' (RO:0002332) is now obsolete in GO.  

This is what I see when I search for it in Protege:
![image](https://user-images.githubusercontent.com/1730534/69453797-b128fa00-0d32-11ea-9a28-01d49c2df769.png)

Perhaps this was the result of this pull request:
https://github.com/geneontology/go-ontology/pull/18240

@balhoff @cmungall - can you provide some guidance on how best to fix this?

Also tagging: @ukemi @pgaudet

**Comment by ukemi** [comment]
I removed the owl stanza from the ro-pending file and have created a PR.

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/pull/18255

**Comment by ukemi** [comment]
The property was obsoleted in the ro-pending file, but is a valid RO property. I should still be in ro-import.

**Comment by balhoff** [comment]
@vanaukenk can you check that this is fixed now?

**Comment by vanaukenk** [comment]
It looks fine in Protege, now.

Thanks @ukemi and @balhoff !
