### ISSUE TITLE
ntr: lipid sensor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18259]
Can "lipid sensor activity"

be inserted in between

GO:0140299    small molecule sensor activity
and
GO:0032935    sterol sensor activity

https://www.sciencedirect.com/science/article/pii/S1097276518305884

https://www.sciencedirect.com/science/article/pii/S1097276518305884#fig2

This is a class of "mechanosensor" so could this also be added as an additonal parent?
(def responds to changes in mechanical force)

There are also "mechanosensors"  which sense changes in cell wall composition that I would like to group under a "mechanosensor activity" term shortly

**Comment by ValWood** [comment]
synonym of lipid sensor "membrane property sensor"
(maybe this would be a better term name with 'lipid sensor' as related. I guess free lipids  probably have sensors too, but these would not be mechnosensors.

**Comment by ValWood** [comment]
cell wall stress sensor

is_a mechanosensor
ref
Philip B, Levin DE; , Mol Cell Biol 2001;21:271-280.: Wsc1 and Mid2 are cell surface sensors for cell wall integrity signaling that act through Rom2, a guanine nucleotide exchange factor for Rho1. PUBMED:11113201 EPMC:11113201

**Comment by hdrabkin** [comment]
suggested defs?

**Comment by ValWood** [comment]
I assumed there was a "pattern' since this is slotting between 2 existing terms 
but

 sterol sensor is
Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of a sterol.

and small molecules sensor is

Binding to a small molecule and eliciting a change in the protein's activity in response to the intracellular level of that small molecule. PMID:26328879

Perhaps these should be standardized in some way?

**Comment by ValWood** [comment]
recommend
lipi sensor 
Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of a lipid.

Can this be added? Seems quick. 

Cheers

Val

**Comment by hdrabkin** [comment]
so verify/clarify
"lipid sensor activity" (PMID:30075144, 
is_a GO:0140299
and 
GO:0032935 is_a lipid sensor activity

**Comment by ValWood** [comment]
that's it, cheers Harold!

**Comment by hdrabkin** [comment]
+id: GO:0106254
+name: lipid sensor activity

**Comment by hdrabkin** [comment]
Should this still be a mechanosensor?

**Comment by ValWood** [comment]
Let's ignore that for now!
See:
https://github.com/geneontology/go-ontology/issues/18636
