### ISSUE TITLE
More transferase EC xrefs to update

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18257]
id: GO:0035004
name: phosphatidylinositol 3-kinase activity
xref: EC:2.7.1

=> change EC to 2.7.1.137

===

id: GO:0003896
name: DNA primase activity
xref: EC:2.7.7

=> remove this partial EC

===

id: GO:0004596
name: peptide alpha-N-acetyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: acetyl-CoA + peptide = CoA + N-alpha-acetylpeptide. This reaction is the acetylation of the N-terminal amino acid residue of a peptide or protein." [EC:2.3.1.88, GOC:mah]
synonym: "acetyl-CoA:peptide alpha-N-acetyltransferase activity" EXACT [EC:2.3.1.88]
synonym: "acetyl-CoA:peptide nalpha-acetyltransferase activity" EXACT [EC:2.3.1.88]
synonym: "amino-terminal amino acid-acetylating enzyme activity" RELATED [EC:2.3.1.88]
synonym: "beta-endorphin acetyltransferase activity" NARROW [EC:2.3.1.88]
synonym: "N(alpha)-acetyltransferase activity" RELATED [EC:2.3.1.88]
synonym: "nalpha-acetyltransferase activity" EXACT [EC:2.3.1.88]
synonym: "NAT activity" RELATED [EC:2.3.1.88]
synonym: "peptide acetyltransferase activity" RELATED [EC:2.3.1.88]
synonym: "protein N-terminal acetyltransferase activity" EXACT [EC:2.3.1.88]
xref: EC:2.3.1.88

=> EC:2.3.1.88 is now obsolete - split into 5 more specific terms (https://enzyme.expasy.org/EC/2.3.1.88) - so should be removed as an xref and reference for the synonyms

===

[Term]
id: GO:0070569
name: uridylyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of an uridylyl group to an acceptor." [GOC:mah]
synonym: "uridyl transferase activity" EXACT [EC:2.7.7.12]
synonym: "uridyltransferase activity" EXACT [EC:2.7.7.12]

=> EC:2.7.7.12 is a for specific (not generic) uridylyltransferase activity so should probably be removed as a reference for these synonyms

**Comment by hdrabkin** [comment]
Done; RHEA added where possible.

**Comment by sjm41** [comment]
Thanks!

**Comment by sjm41** [comment]
Hi Harold,

For this one:
===
id: GO:0003896
name: DNA primase activity
xref: EC:2.7.7
=> remove this partial EC
===

I see that you replaced the partial EC with EC:2.7.7.101.
But that's specifically for the DnaG primate of bacteria/archaea, so doesn't cover the DNA primases of eukaryotes. I think it should be removed....?
