### ISSUE TITLE
Merge 'GO:0062178 stationary phase' (was: needed to fix exists_during annotations)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18275]
to migrate these
https://github.com/geneontology/go-annotation/issues/2677

so that they are either i) involved in ii) phases or iii) responses (will during 'response be allowed, I forgot ?)

We will require some new phase terms.

First

"stationary phase"
A phase in microbial growth when, due to nutrient limitation, growth rate and death rate are equal

parent
GO:0072690    single-celled organism vegetative growth phase

**Comment by ukemi** [comment]
PMID?

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/8393130

**Comment by mah11** [comment]
I suppose this is a done deal now, but I'm not free of doubt about including this term. Unlike most (probably all - I haven't spotted any exceptions) of the rest of the "biological phase" branch of GO, stationary phase isn't a life cycle or developmental stage that all or part of a single organism can go through. It's entirely an artifact of growing microorganisms in laboratory cultures, and only applies to that kind of non-wild population of cells, not to an individual organism.

**Comment by ValWood** [comment]
Actually we already had
https://www.ebi.ac.uk/QuickGO/term/GO:0044838

so this can merge  and "stationary phase" can be  a related synonym

**Comment by ukemi** [comment]
Not sure it is the same as quiescence. Nothing in the definition suggests this is restricted to a single organism:A distinct period or stage in a biological process or cycle.
Will let @pgaudet decide about merge, keep or obsolete.

**Comment by mah11** [comment]
I'm less worried about the single organism vs. population angle than I am about the fact that stationary phase is essentially a phenomenon only seen in laboratory cultures, and whether that's in scope for GO. I agree that stationary phase and cell quiescence aren't identical (for one thing, cells can and do go into quiescence without lab manipulation).

**Comment by ukemi** [comment]
Good point! @pgaudet I think we should obsolete this one.

**Comment by ValWood** [comment]
obsolete ""stationary phase"" I will need to address these another way

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0062178 stationary phase (was: terms needed to fix exists_during annotations). The reason for obsoletion is that this process does not exists, but is an artifact of growing microorganisms in laboratory cultures. 

There are no annotations and no mappings to this term. This term is not present in any subsets.

Any comments can be added to the ticket: geneontology/go-ontology/18275.

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 4th, 2020. Unless objections are received by February 4th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by krchristie** [comment]
Having spent some time investigating the fact the the gene I was studying in S. cerevisiae made it harder to get my cells to come back from frozen stocks, I spent some time investigating "stationary phase". I never thought of it as a "laboratory artifact", but rather a laboratory induced nutrient limitation that induces the cells to go into a quiescent phase characterized by specific changes in gene expression and morphology, as stated very nicely by the abstract of the paper cited for the definition of the term for `stationary phase`:

**Werner-Washburne et al. 1993. Stationary phase in the yeast Saccharomyces cerevisiae. Microbiol Rev. PMID:8393130**
> Growth and proliferation of microorganisms such as the yeast Saccharomyces cerevisiae are controlled in part by the availability of nutrients. When proliferating yeast cells exhaust available nutrients, they enter a stationary phase characterized by cell cycle arrest and specific physiological, biochemical, and morphological changes. These changes include thickening of the cell wall, accumulation of reserve carbohydrates, and acquisition of thermotolerance. Recent characterization of mutant cells that are conditionally defective only for the resumption of proliferation from stationary phase provides evidence that stationary phase is a unique developmental state. 

I would also argue that it is thus not correct for a term for a quiescent phase to be listed as a type of "vegetative growth phase". 

If there's any reason to keep this term, I think it should be placed under `cell quiescence`. If there's no need to have a term specific to single cells, then it could be made a synonym of the `cell quiescence`, but perhaps SGD people should weigh in: @srengel @robnash

**Comment by ValWood** [comment]
Hi Karen thanks for the input.

I think we are OK here. I used GO:0044838  cell quiescence instead.

There is no "quiescence term listed under "vegetative growth phase". AFAIK

Val

**Comment by pgaudet** [comment]
Since there are no annotations to 'GO:0062178 stationary phase' I could merge as a narrow synonym, and put a note in the comment.

**Comment by ValWood** [comment]
Yes, I think "stationary phase" is already related, which is fine. I missed that!

**Comment by ValWood** [comment]
We are curating  a publication from the PomBase Co-PI  Jurg Bahler @bahler  laboratory.

Jurg is an expert in chronological ageing, and he thinks we need this term - In fact, we need it for this publication:
PMID:34464389
Title: | R-loops and regulatory changes in chronologically ageing fission yeast cells drive non-random patterns of genome rearrangements.

Jurrg says:
"stationary phase (triggered by depletion of glucose in high-density cell cultures, cells survive only a few days"

presumably this isn't just a laboratory condition (Karen  @krchristie  pointed this out above).

In this paper Jurg's group  studies a gene whose expression is dramatically decreased in stationary phase  (and  @pombase we use GO "phase terms" as extensions to RNA and protein level terms to say when in the lifecycle these occur).

So would it be possible to resurrect this term with a better definition?

The original definition was
 A phase in microbial growth when, due to nutrient limitation, growth rate and death rate are equal

suggest:
"stationary phase"
Definition: (in terms of is happening in a single cell)
A microbial lifecycle stage characterized by specific changes in gene expression and morphology, to decrease growth rate and maintain viability during nutrient (is it always glucose limitation for all species?).  
Gloss: (This is about the population so it's outside the scope of GO, but useful to include)
During stationary phase, the population size does not increase. Stationary phase cannot be maintained indefinitely.

Jurg, is this definition correct? and could it be improved?

**Comment by krchristie** [comment]
Note that the existing term for 'cell quiescence' is in the **gocheck_do_not_annotate** set and has this comment associated:
> Note that terminally differentiated cells in higher eukaryotes are typically quiescent but metabolically active. Note that this term should not be used for direct annotation. If you are trying to make an annotation to x phase, it is likely that the correct annotation is 'regulation of x/y phase transition' or to a process which occurs during the reported phase (i.e mitotic DNA replication for mitotic S-phase). To capture the phase when a specific location or process is observed, the phase term can be used in an annotation extension (PMID:24885854) applied to a cellular component term (with the relation exists_during) or a biological process term (with the relation happens_during). Also, note that this term should not be used for direct annotation. If you are trying to make an annotation to x phase, it is likely that the correct annotation is 'regulation of x/y phase transition' or to a process which occurs during the reported phase (i.e mitotic DNA replication for mitotic S-phase). To capture the phase when a specific location or process is observed, the phase term can be used in an annotation extension (PMID:24885854) applied to a cellular component term (with the relation exists_during) or a biological process term (with the relation happens_during).

Since yeast stationary phase is a type of cell quiescence, presumably it should be treated similarly where appropriate annotations would be for terms representing regulation of entry or exit from stationary phase. 

Also note that while stationary phase (GO:0062178) was obsoleted, we still have these three terms:
-- maintenance of stationary phase
--- maintenance of stationary phase in response to starvation
--- maintenance of stationary phase in response to toxin

The current definition of **maintenance of stationary phase** is inconsistent with the idea that stationary phase in yeast is a specific life cycle stage characterized by specific changes in gene expression and where cells are not dividing.
> The homeostatic process in which a population of cells changes its metabolic activity resulting in the rate of death in the population equaling the rate of reproduction. Stationary phase can be in response to limited nutrients or a build-up of toxic substances in the environment.

I question whether "**stationary phase in response to toxin**" is related to stationary phase induced by nutrient limitation, though with respect to cerevisiae, I have never heard of "**stationary phase in response to toxin**". Note that none of these 3 terms are associated with a publication as a reference.

**Comment by ValWood** [comment]
1. I  agree, based on what we already agreed above "stationary phase in response to toxin" makes no sense. Stationary phase happens in response to nutrient (only glucose??? limitation). I guess this can be obsoleted immediately? It has no annotations.

2. Is 'stationary phase' actually a type of quiescence if cells are still cycling albeit more slowly?  (I have no idea)

**Comment by krchristie** [comment]
> 1. I  agree, based on what we already agreed above "stationary phase in response to toxin" makes no sense. Stationary phase happens in response to nutrient (only glucose??? limitation). I guess this can be obsoleted immediately? It has no annotations.

makes sense to me
 
> 2. Is 'stationary phase' actually a type of quiescence if cells are still cycling albeit more slowly?  
(I have no idea)

My impression from when I was looking into this and reading Maggie Werner-Washburne's papers is that the cells are not cycling at all. Consistent with that idea, the growth curves for my cells in stationary phase were completely flat indicative of cessation of growth.

I think the GO definitions of stationary phase as a balance between growth and death are just wrong.

**Comment by bahler** [comment]
My impression from when I was looking into this and reading Maggie Werner-Washburne's papers is that the cells are not cycling at all. Consistent with that idea, the growth curves for my cells in stationary phase were completely flat indicative of cessation of growth.
I think the GO definitions of stationary phase as a balance between growth and death are just wrong.


è I agree: also in fission yeast cells are not really dividing during stationary phase. They are dying within a few days, however, in contrast to quiescence where cells remain metabolically active and can persist for extended times. So most fission yeast researchers distinguish between quiescence and stationary phase. But the latter is definitely a distinct physiological stage with some mutants showing phenotypes specifically during stationary phase. So it would be important to have this GO term to properly annotate these phenotypes.

Cheers,
-Jürg

**Comment by ValWood** [comment]
we will use "during" GO:0036227  mitotic G2 cell cycle arrest in response to glucose starvation
