### ISSUE TITLE
Logical definition of 'pharyngeal muscle development' 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#18285]
The logical definition of 'pharyngeal muscle development' refers to the UBERON term 'pharyngeal muscle' which has a part_of parent to 'musculoskeletal system'.

Annotation of nematode genes to 'pharyngeal muscle development' is therefore in violation of a taxon constraint via the inherited property chain: results in developmental progression of o in taxon subPropertyOf in taxon.

Right now there are only C. elegans and D. rerio annotations to the term, but we need to resolve the taxon violation for C. elegans.

Options:
1) remove the logical def entirely
2) re-write the logical def somehow to refer to 'muscle structure' part_of some 'pharynx' neither of which are children of 'musculoskeletal system' 
3) create appropriate nematode muscle terms in UBERON and corresponding GO terms
4) others?

**Comment by vanaukenk** [comment]
2020-06-22 ontology call:
Create two (?) child terms (nematode and vertebrate)
Check Drosophila annotation - what would the appropriate term be, one of the above or a third term?

**Comment by vanaukenk** [comment]
Here's a proposal for what to do with terms in GO that refer to 'pharynx'.

'pharynx' on its own is probably too general a term to be used to group annotations across vertebrates and invertebrates.

I propose that we split any pharynx, or pharyngeal muscle, terms into three categories for now: vertebrate, arthropod, and nematode.  While this division is broad and incomplete, it would allow us to safely house existing annotations (fish (2 types), mouse, human, D. melanogaster, and C. elegans) with appropriate parents (e.g. in C. elegans the pharynx is considered an organ, while in UBERON and FBbt pharynx appears to be considered an organ part.)

Logical definitions would refer to the appropriate anatomy terms from UBERON, WBbt, and FBbt and appropriate parent processes in GO.

Most of the current annotations to pharynx or pharyngeal terms in GO are for C. elegans genes, so some re-housing of annotations will be needed but the numbers are manageable.

@ukemi @hattrill @sabrinatoro @cmungall - any additional thoughts or suggestions?

**Comment by sabrinatoro** [comment]
@vanaukenk 
I chatted with Ceri, and we both agree that splitting into 3 based loosely on species is good.

**Comment by raymond91125** [comment]
'pharyngeal muscle development' LD: 'anatomical structure development'
 and ('results in development of' some 'pharyngeal muscle')
UBERON:0000933 'pharyngeal muscle' LD: "'muscle organ' and ('part of' some 'musculature of pharynx')"
UBERON:0004467 'musculature of pharynx' Always in taxon Chordata
If UBERON:0000933 is defined as "'muscle organ' and ('part of' some 'pharynx')", we would not have the taxon conflicts.
We've dealt with similar issues before using the more general Uberon pharynx term. https://github.com/geneontology/go-ontology/issues/13659.

**Comment by vanaukenk** [comment]
@raymond91125 
I was just reviewing the C. elegans taxon constraints and came across this one again.
I think your proposed solution above would work for this case, if no one else objects.
The alternative would be to have a specific nematode pharyngeal muscle development term, but I'm not sure that's really desirable.
Thanks.

**Comment by raymond91125** [comment]
@vanaukenk There is a proposal to obsolete generic pharynx https://github.com/obophenotype/uberon/issues/2728.
Thus I cannot do what I proposed to do. I'm waiting for a new nematode pharynx term for logical def.
Or do you think we should just remove LD for now? Thanks.

**Comment by vanaukenk** [comment]
Ah, thanks for that info @raymond91125 

In principle, I hate to remove logical definitions from the ontology.

I'll put this on the agenda for Monday's ontology call to see if we can figure out the who/what/when of the UBERON work.

**Comment by pgaudet** [comment]
@raymond91125 @vanaukenk Do we have a decision here? 

This is a list of terms that may need to be checked: 

GO:0061626 | pharyngeal arch artery morphogenesis
GO:1905905 | pharyngeal gland morphogenesis
GO:0043282 | pharyngeal muscle development
GO:0043050 | pharyngeal pumping
GO:0060037 | pharyngeal system development
GO:0060465 | pharynx development
GO:0110040 | pharynx morphogenesis
GO:0021563 | glossopharyngeal nerve development
GO:0021616 | glossopharyngeal nerve formation
GO:0021614 | glossopharyngeal nerve maturation
GO:0021615 | glossopharyngeal nerve morphogenesis
GO:0021617 | glossopharyngeal nerve structural organization
GO:0043051 | regulation of pharyngeal pumping
GO:0110041 | regulation of pharynx morphogenesis
GO:0002395 | immune response in nasopharyngeal-associated lymphoid tissue
GO:1903745 | negative regulation of pharyngeal pumping
GO:0110042 | negative regulation of pharynx morphogenesis
GO:1903746 | positive regulation of pharyngeal pumping
GO:0110043 | positive regulation of pharynx morphogenesis
GO:0002400 | tolerance induction in nasopharyngeal-associated lymphoid tissue


If needed, I think removing the LD is OK; we can revisit these once Uberon has been updated. 
Thanks, Pascale

**Comment by raymond91125** [comment]
Given that Uberon https://github.com/obophenotype/uberon/issues/2728 is moving to instantiate nematode/arthropod/chordate pharynx and obsolete generic pharynx, GO would need to
1. Make clear / add terms that refer to nematode / arthropod / chordate
2. Remove old LD
3. Apply new Uberon terms (TB made) for LD

Question is whether we should do the steps all at once or not.

**Comment by raymond91125** [comment]
GO:0061626 | pharyngeal arch artery morphogenesis | UBERON:0001042 chordate pharynx
GO:1905905 | pharyngeal gland morphogenesis | UBERON:0015232 nematode pharynx
GO:0043282 | pharyngeal muscle development | UBERON:0001042 chordate pharynx + UBERON:0015232 nematode pharynx
GO:0043050 | pharyngeal pumping | UBERON:0015232 nematode pharynx
  GO:0043051 | regulation of pharyngeal pumping
    GO:1903746 | positive regulation of pharyngeal pumping
    GO:1903745 | negative regulation of pharyngeal pumping
GO:0060037 | pharyngeal system development UBERON:0001042 chordate pharynx
GO:0060465 | pharynx development | UBERON:0001042 chordate pharynx + UBERON:0015232 nematode pharynx + UBERON:60005380 insect pharynx
GO:0110040 | pharynx morphogenesis | UBERON:0015232 nematode pharynx
  GO:0110041 | regulation of pharynx morphogenesis
    GO:0110043 | positive regulation of pharynx morphogenesis
    GO:0110042 | negative regulation of pharynx morphogenesis
GO:0021563 | glossopharyngeal nerve development | UBERON:0001042 chordate pharynx
  GO:0021616 | glossopharyngeal nerve formation
  GO:0021614 | glossopharyngeal nerve maturation
  GO:0021615 | glossopharyngeal nerve morphogenesis
  GO:0021617 | glossopharyngeal nerve structural organization

**Comment by raymond91125** [comment]
@pgaudet In this example, GO:1905905 | pharyngeal gland morphogenesis, the term label, definition, LD, and taxon constraints are all consistent or restricted to a process of vertebrates, although the PMID reference is about C elegans, and yet the annotation thus far is limited to nematodes. Would it be OK if we revise the label and definition to make it restrictive to nematodes? Or should we generate a new term and move the annotations?

**Comment by cmungall** [comment]
I think it's OK to make an exception for this given it's obviously nematode specific

**Comment by raymond91125** [comment]
[Term]
+id: GO:0160093
+name: chordate pharynx development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of cordate pharynx over time, from its formation to the mature structure." [PMID:23020903]
+intersection_of: GO:0048856 ! anatomical structure development
+intersection_of: results_in_development_of UBERON:0001042 ! chordate pharynx
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/18285" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-29T21:05:28Z
+
+[Term]
+id: GO:0160094
+name: nematode pharynx development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of nematode pharynx over time, from its formation to the mature structure." [PMID:18050503]
+intersection_of: GO:0048856 ! anatomical structure development
+intersection_of: results_in_development_of UBERON:0015232 ! nematode pharynx
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/18285" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-29T22:05:32Z
+
+[Term]
+id: GO:0160095
+name: insect pharynx development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of insect pharynx over time, from its formation to the mature structure." [PMID:10952900]
+intersection_of: GO:0048856 ! anatomical structure development
+intersection_of: results_in_development_of UBERON:60005380 ! insect pharynx
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/18285" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-29T22:14:25Z
+
+[Term]
+id: GO:0160096
+name: nematode pharyngeal muscle development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of the nematode pharyngeal muscle over time, from its formation to the mature structure." [GOC:go_curators]
+is_a: GO:0007517 ! muscle organ development
+relationship: part_of GO:0160094 ! nematode pharynx development
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/18285" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-29T22:49:13Z

**Comment by raymond91125** [comment]
Updated. Thanks for the alert.
