### ISSUE TITLE
Guidelines needed: ChEBI in definition cross references

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18288]
Hi, 

GO:2001310 gliotoxin biosynthetic process (and other terms) have ChEBI IDs in the definition cross reference: 

The chemical reactions and pathways resulting in the formation of the epipolythiodioxopiperazine gliotoxin, a poisonous substance produced by some species of fungi. Source: PMID:16333108, **CHEBI:5385**, PMID:18272357, CHEBI:299453, PMID:17574915, GOC:di

Does that make sense ? ChEBI does not help provide a definition for this process ? I would suggesting removing those from definition cross references. They should be 'inputs' or 'intermediates'. 

@ukemi @hdrabkin what do you think ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
I would remove them. They make no sense here.

**Comment by ukemi** [comment]
That is kind of weird. I agree they should be in the logical defs.

**Comment by pgaudet** [comment]
Only about half done.

**Comment by cmungall** [comment]
I think this makes sense.

It's worth articulating a rule here:

IF the text definition includes an embedded description of the differentia,
AND that description comes from source S, THEN S *should* be stated in the
definition provenance

I suspect that the second criteria doesn't hold for our existing
definitions, and we took the embedded definition from some textbook source.

As David H knows, I don't like embedded definitions, and I am
particularly not keen on some of the woolly ones we have in GO. See my
thoughts here in my ontotips series:

https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

**Comment by pgaudet** [comment]
For guidelines see #16895
