### ISSUE TITLE
cytoskeletal protein membrane adaptor/microtubule cortical anchor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18281]
cytoskeletal protein membrane adaptor (GO:0140362)
Definition	
Interacting selectively and non-covalently with both a cytoskeletal protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location.

and
microtubule cortical anchor activity (GO:0106006)
The binding activity that attaches a microtubule to the cell cortex.

are really describing the same activity.

The community describe these as "cortical anchors" because they are cortical. See

https://www.pombase.org/reference/PMID:16624923
Fission yeast Num1p is a cortical factor anchoring dynein and is essential for the horse-tail nuclear movement during meiotic prophase.

but  these bind to membrane lipids
eg. num1 binds to	
phosphatidylinositol-4,5-bisphosphate

so
cytoskeletal protein membrane adaptor (GO:0140362)
is also true.

This means we have 2 different functions to describe the same activity.
Its almost as if we don't really want to differentiate between the cortex and the PM in this situation because they are both true....

How should we resolve this?

**Comment by pgaudet** [comment]
Would the annotations be OK if we merged ?

**Comment by ValWood** [comment]
I think so, or parent child (one is microtubule, one is protein, although I think microtubule could be a narrow synonym.

maybe we can say "cytoskeleton plasma membrane anchor"

"interacting selectively and non-covalently with both a cytoskeletal protein or protein complex and directly with a plasma membrane lipid or membrane-associated protein, in order to maintain the localization of the cytoskeleton at a specific cortical membrane location.

**Comment by pgaudet** [comment]
For info 
cytoskeletal protein membrane adaptor (GO:0140362) -> 6 EXP
microtubule cortical anchor activity (GO:0106006)  -> 4 EXP

**Comment by pgaudet** [comment]
@ValWood I guess you are aware you requested GO:0140362 last July ? 

(also, there was an outstanding question in that ticket #17580) 

You still want to merge ? 

Thanks, Pascale

**Comment by ValWood** [comment]
yes. 

microtubule cortical anchor activity (GO:0106006
can merge into
cytoskeletal protein membrane adaptor (GO:0140362) 
as narrow.

These anchors are often referred to as "cortical anchors" but  this is because the  protein anchored to the plasma membrane resides in the cortex (i.e it is describing the location of the anchored component, rather than what is anchored to what)

**Comment by ValWood** [comment]
So currently I have this situation:

<img width="1192" alt="Screenshot 2020-01-30 at 14 15 02" src="https://user-images.githubusercontent.com/7359272/73457062-f557fc80-436a-11ea-92dc-6f15397b881e.png">


One gene product, same activity, described in 2 ways...

**Comment by ValWood** [comment]
BTW all EXP to both of these are pombe at present.

**Comment by pgaudet** [comment]
Good. Merged terms and fixed definition as you suggested above "Interacting selectively and non-covalently with both a cytoskeletal protein or protein complex and directly with a plasma membrane lipid or membrane-associated protein, in order to maintain the localization of the cytoskeleton at a specific cortical membrane location." [PMID:25736293, PMID:30840879]"


Thanks, Pascale

**Comment by ValWood** [comment]
I double-checked and the microtubule ones have  membrane lipid binding annotations, so it does seem OK.
