### ISSUE TITLE
Merge 'suppression by symbiont of x' and 'negative regulation of x'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18297]
Hello, 

Similar to what we did in #18043 for induction and positive regulation, suppression and negative regulation terms should be merged. For example: 

- 'negative regulation by symbiont of host defense response'
-> merge into: 'suppression of host defenses'

**Comment by pgaudet** [comment]
Merged: 
* "modulation by symbiont of host signal transduction mediated by G-protein alpha subunit" 
* "modulation by symbiont of host signal transduction mediated by G-protein beta subunit"
*"modulation by symbiont of host signal transduction mediated by G-protein gamma subunit" 
into GO:0075118 modulation by symbiont of host G protein-coupled receptor signal transduction 

Merged: 
* "negative regulation by symbiont of host signal transduction mediated by G-protein alpha subunit" 
*"negative regulation by symbiont of host signal transduction mediated by G-protein beta subunit" 
*"negative regulation by symbiont of host signal transduction mediated by G-protein gamma subunit" 
into GO:0075120 suppression by symbiont of host G protein-coupled receptor signal transduction

Merged: 
*"positive regulation by symbiont of host signal transduction mediated by G-protein alpha subunit" 
* "positive regulation by symbiont of host signal transduction mediated by G-protein beta subunit" 
*"positive regulation by symbiont of host signal transduction mediated by G-protein gamma subunit" 
into GO:0075119  induction by symbiont of host G protein-coupled receptor signal transduction

**Comment by ValWood** [comment]
> GO:0075120 suppression by symbiont of host G protein-coupled receptor signal transduction

We should probably obsolete this as it has no annotations? We would want to know the pathway not the receptor type. This seems like an odd term? Is there a PMID, I did not see any annotations.

**Comment by pgaudet** [comment]
Lets look  for literature before obsoleting. This entire branch has few annotations, to be honest.

**Comment by ValWood** [comment]
There are definitely G-proteins. The canonical PTI signalling has a G-protein receptor above the MAPK signalling
This is the cool figure I was looking for yesterday for PTI:
https://ars.els-cdn.com/content/image/1-s2.0-S1674205215000878-gr1.jpg

Agg1/2 AGB1 GPA1
I'm  pretty sure these would end up as 
effector-mediated activation or suppression of host PTI
