### ISSUE TITLE
Merge 'GO:0043390 aflatoxin B1 metabolic process' and 'GO:0043390  aflatoxin B2 metabolic process' into 'GO:0046222 aflatoxin metabolic process'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18291]
@marcfeuermann says that these compounds are synthesized by the same pathway, so there is no point having three different pathways. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also - removed the parent 
 GO:2000762 ! regulation of phenylpropanoid metabolic process

from "regulation of aflatoxin biosynthetic process'

**Comment by cmungall** [comment]
this is not really consistent with how we have modeled things so far.
