### ISSUE TITLE
NTR x 2; L-alanine export across the plasma membrane; L-alanine:proton antiport

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-ontology#18299]
I would would like a BP term for L-alanine export across the plasma membrane and an MF term for L-alanine:proton antiporter activity.

I've looked at the ontology structure for some other membrane transporters; it was a bit confusing to me but I think the BP term should be a child of both GO: 0032973 amino acid export across plasma membrane, and a child of L-alanine transmembrane transport (which needs to be created).
The MF term is a child of GO:0015299 solute:proton antiporter activity and also of GO:0034639 L-amino acid efflux transmembrane transporter activity

In E. coli, the AlaE inner membrane protein mediates export of L-alanine under peptide-rich growth conditions; export is energized by the PMF (ie L-alanine:proton antiport). Characterized by Kim et al PMID 26073055 and Katsube et al PMID 31591285

Thanks
Amanda

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140406
+name: L-alanine export across the plasma membrane
+namespace: biological_process
+def: "The directed movement of L-alanine from inside of a cell, across the plasma membrane and into the extracellular region." [PMID:26073055, PMID:31591285]
+intersection_of: GO:0006810 ! transport
+intersection_of: exports CHEBI:16977 ! L-alanine
+intersection_of: has_target_end_location GO:0005576 ! extracellular region
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2019-12-11T14:13:07Z
+
+[Term]
+id: GO:0140407
+name: L-alanine:proton antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: H+(out) + L-alanine(in) = H+(in) + L-alanine(out)." [PMID:26073055, PMID:31591285]
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: exports CHEBI:24636 ! proton
+intersection_of: imports CHEBI:16977 ! L-alanine
+created_by: pg
+creation_date: 2019-12-11T14:17:48Z

**Comment by pgaudet** [comment]
I did not create the intermediate term 'L-alanine transmembrane transport' - this is redundant with the MF. I know the ontology is not consistent in this area. 

Thanks, Pascale
