### ISSUE TITLE
references supporting definitions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18298]
There are a large mixture of references supporting definitions, but some do not appear to be definitions sources:

Here's a sample, there are others:

~ PMIG:10085024~ <<<<< cannot find
PMID:pm<<<<<< cannot find
GOC:mcc; <<<<<<< allowed; I always add the GOC: of the requestor, who usually supplies a def to begin with.
GOC:mtg_transport
GOC:jl <<<<<<< allowed; I always add the GOC: of the requestor, who usually supplies a def to begin with.
ISBN:0815340729 <<<< allowed; this is Molecular Biology of the Cell
PO:0000029 <<<< obsoleted PO term
KEGG:R05612
RHEA:20836 <<<< allowed as def
EMBL:AF304352  <<<<< replaced with PMID that this id goes with.
http://www.ultranet.com/~jkimball/BiologyPages/D/DNArepair.html
http://www.earthlife.net
EC:3.2.1.108; <<<<< allowed but also added RHEA
BioCyc:PWY-882
BRENDA:1.11.1.15  <<<< cannot find; someone removed and replaced with EC. I added RHEA
BTO:0002164
CHEBI:10022  <<< gone; cannot find in current ontology; someone else removed
CORUM:2870
DDANAT:0000068
dictyBase_REF:2530 <<<<<< dictybase contacted; this is an unpublished genbank reference but the author DO have papers that may be associated with this. Petra helped; these are all replaced by PMID.

DOI:10.1002/1096-9861 <<<<< This is allowed. 
FBbt:00005786
FB:FBrf0039640  <<<<<< replaced with DOI
Intact:EBI-9345927 <<< moved to xref
intAct:EBI-9636287 <<<<< moved to xref
InterPro:IPR000001 ,<<<<<<< removed.
IUPHAR_GPCR:1506
IUPHAR_RECEPTOR:1276
MeSH:C04.697.152  <<<<< removed but was in obsolete term anyways.
MetaCyc:1.10.2.1-RXN   <<<< replaced with RHEA:18677
NIF_Subcellular:sao1470140754
Pfam:PF03166
phi:0000005  <<<<< PHI contacted. cannot find on their site
PHI:0000011 <<<<<PHI contacted; cannot find on their site
Wikipedia:Gamma_ray
Wiki:Cystic_fibrosis_transmembrane_conductance_regulator

**Comment by ValWood** [comment]
FB:FBrf0039640
Is a flybase paper
http://flybase.org/reports/FBrf0039640.html
should we use PubMed?

Some look like DBxrefs although BRENDA /Rhea/ CHEBI/MetaCyc are  probably good definition sources 

from
https://github.com/pombase/website/issues/589

**Comment by ValWood** [comment]
EMBL: AF304352 in this instance is just an example entry not a definition

**Comment by ukemi** [comment]
Some of these look fine. Some look like typos.

**Comment by hdrabkin** [comment]
ISBNs are fine. DOI is fine (if PMID exists could be changed)
EC is fine if it represents the def or basis there-of; but now can use a RHEA
These could be xrefs if the term is a complex.
Intact:EBI-9345927
intAct:EBI-9636287
BRENDA:1.11.1.15 might be replaced with EC and RHEA

I would not use InterPRO domains or CHEBI terms as def refs; Maybe in logical defs

**Comment by hdrabkin** [comment]
For the flybase entry; journal not indexed by Pubmed evidenctly; however, it does have a valid DOI which can be used. https://doi.org/10.1016/0020-1790(83)90018-5

**Comment by hdrabkin** [comment]
I'm working commenting on these in line with 1rst post. This will take several passes.

**Comment by hdrabkin** [comment]
Has anyone been working on this? I find I cannot find some listed here as if someone else went in and changed.?

**Comment by pgaudet** [comment]
Not that I know of ...?

**Comment by hdrabkin** [comment]
I will carry on then

**Comment by hdrabkin** [comment]
um; I just noticed that the edits I made to the orginal post as I work through them are gone. Did I not forget to save?

**Comment by hdrabkin** [comment]
Essential done: id didin't know how to access some of the terms in their repective dbs to see what they were.
What do we want to do with the Intact ids that are to species-specific examples of the general defs for complexes?

**Comment by pgaudet** [comment]
> What do we want to do with the Intact ids that are to species-specific examples of the general defs for complexes?

Should these not be cross-refences instead of definition cross-references ? (as we do for Reactome?)

**Comment by hdrabkin** [comment]
I was thinking that.

**Comment by hdrabkin** [comment]
Finally got a handle on "PHI:" terms.
These are NOT from the pathogen-host interaction db as I first thought.These are from
- database: PHI
  name: MeGO (Phage and Mobile Element Ontology)
  generic_urls:
    - http://aclame.ulb.ac.be/Classification/mego.html
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      example_id: PHI:0000055

The two @ValWood pointed out (one has typo phi:  vs PHI:) are actually  equivalents of the GO term . I would think these should be xrefs rather that def refs. There are about 43 in the ontology total; a couple GO terms have > 1 PHI id. All created by Brenely. No paper references.
Some are xrefs already; most not. 
@jimhu-tamu do  you have any advice about these? 

There is another issue here maybe: two dbs using the same prefix; 
THe pathogen-host ids don't use leading zeros.

**Comment by rwst** [comment]
- Pfam:PF03166 this refers to a domain entry: https://pfam.xfam.org/family/PF03166. The referred to entry is "MAD homology 2 domain".
- Wikipedia:Gamma_ray, this is fine but maybe should go in xref
- Wikipedia:Cystic_fibrosis_transmembrane_conductance_regulator, formally fine but as CFTCR is a subset of the proteins with that function it might not be appropriate as ref

**Comment by pgaudet** [comment]
@ValWood Do you know where the PHI: links should go ? See for example GO:0075530
I had removed the entry from the db-xref.yaml but somhow I didn't notice we has cross-references. 
https://github.com/geneontology/go-site/issues/583

As far as I can tell aclame /MeGO ontology is not maintained since 2009.  

Thanks, Pascale

**Comment by pgaudet** [comment]
@rwst Pfam domains are likely outside the scope of GO - we are trying to define activities, not protein families. The links between GO terms and Pfam/InterPro are made at the level of the mappings between those resources - I'll remove them.


Thanks, Pascale

**Comment by hdrabkin** [comment]
the wiki gamma ray should definitely not be an xref; it's not an equivalence or mapping for the GO term
It was being use in the def ref I assume to define what a gamma ray is, but does not define the GO term. It should just be removed I think.

**Comment by pgaudet** [comment]
I removed 
* Wikipedia:Gamma_ray, this is fine but maybe should go in xref
* Wikipedia:Cystic_fibrosis_transmembrane_conductance
* 3 xrefs to SP entries

----

* Pfam:PF03166  is in the synonym xref - do we want this ? 

Thanks, Pascale

**Comment by ValWood** [comment]
@pgaudet  I have never come across PHIGO or MeGO. I don't think they are anything to do with PHI-base. @CuzickA can  you confirm?
v

**Comment by CuzickA** [comment]
Hi @ValWood I can confirm that PHIGO or MeGO is not data from PHI-base.

**Comment by ValWood** [comment]
@hdrabkin is this one still "in progress"  (trying to check status of all the tickets I opened, and close if no longer valid)

**Comment by pgaudet** [comment]
Fixed the remaining problematic def xrefs reported here. There may be more, please open a new ticket if you find more. 

Thanks, Pascale
