### ISSUE TITLE
incorrectly positioned phase term (anaphase)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18302]
https://www.ebi.ac.uk/QuickGO/term/GO:0051322

is directly under cell cycle phase.
It should . be under
GO:0000279   M phase

**Comment by ukemi** [comment]
What about meiotic anaphase? M phase is mitotic.

**Comment by ValWood** [comment]
anaphase should be here:
(sibling)
<img width="923" alt="Screenshot 2019-12-06 at 16 13 19" src="https://user-images.githubusercontent.com/7359272/70337631-64b9e000-1843-11ea-8912-ff2fd9771179.png">

**Comment by ValWood** [comment]
meiotic anaphase and 
mitotic anaphase are correctly placed under "M-phase"

**Comment by ValWood** [comment]
M phase is defined
A cell cycle phase during which nuclear division occurs, and which is comprises the phases: prophase, metaphase, anaphase and telophase.
(although historically it was named for "mitotic phase")

**Comment by ValWood** [comment]
Mphase does appear to be used for meiosis. I guess because researcher now use the same 
terms for transitions

meiotic G2/M-phase transition  for example

**Comment by ukemi** [comment]
I guess I'm just old-fashioned. I will move the term.

**Comment by ukemi** [comment]
Should it be a part-of or an is-a. Seems to me it should stay a cell cycle phase and be a part of M phase.

**Comment by ukemi** [comment]
prophase and metaphase are both part-of

**Comment by ukemi** [comment]
Part of is consistent with the current structure of that whole area of the ontology. That's what I am doing.

**Comment by ValWood** [comment]
Yep
