### ISSUE TITLE
renal terms and taxon issues

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#18307]
I am having taxon violation issues with:

GO:0003091 renal water homeostasis
GO:0003096 renal sodium ion transport
GO:0003097 renal water transport

because of the link to UBERON:0002113 kidney

But renal system process GO:0003014 is defined as:
 A organ system process carried out by any of the organs or tissues of the renal system. The renal system maintains fluid balance, and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products. In humans, the renal system comprises a pair of kidneys, a pair of ureters, urinary bladder, urethra, sphincter muscle and associated blood vessels; in other species, the renal system may comprise related structures (e.g., nephrocytes and malpighian tubules in Drosophila). 

So encompasses non-kidney excretory systems.

And Malpighian tubule development comes under the renal system development branch.

In Uberon, Malpighian tubule is part of the renal system. So perhaps the fix lies with UBERON? I don't know. But the fix should include other renal systems other than the kidney.

![Screenshot 2019-12-02 at 07 53 13](https://user-images.githubusercontent.com/11865746/69939999-128e5d00-14d9-11ea-877a-335c284fbcc1.png)
![Screenshot 2019-12-02 at 07 53 40](https://user-images.githubusercontent.com/11865746/69940003-14582080-14d9-11ea-84a4-4fb9dd392a75.png)
![UBERON_tubes](https://user-images.githubusercontent.com/11865746/69940037-2df96800-14d9-11ea-8c80-212d94d47dd2.png)
![Screenshot 2019-12-02 at 07 56 21](https://user-images.githubusercontent.com/11865746/69940068-4073a180-14d9-11ea-9c84-f2a123d2bbbc.png)

**Comment by ukemi** [comment]
Probably related to:  #16143
@cmungall

**Comment by hattrill** [comment]
Ok, thanks @ukemi 
Not sure if I really follow this long ticket. Renal terminology used a lot in fly and 'Representing Kidney Development Using the Gene Ontology'  https://doi.org/10.1371/journal.pone.0099864 went over this indepth.

**Comment by ukemi** [comment]
Yes. We shouldn't have taxon restrictions here. I think they are coming from uberon.

**Comment by ukemi** [comment]
Hmmm. We might be able to solve this ourselves. What do you think of changing 'renal water transport' from: 'water transport' and ('occurs in' some kidney)
to: 'water transport' and ('occurs in' some 'renal system')
etcetera... etcetera?

**Comment by hattrill** [comment]
Are you talking about the logical definition here? If so, that sounds correct.

**Comment by ukemi** [comment]
OK. I'm going to give this a try. Fingers crossed.

**Comment by hattrill** [comment]
Hi @ukemi - afraid that I am still getting taxon violations. Does not seem to have fixed issue.

**Comment by balhoff** [comment]
@ukemi I see 'renal water homeostasis' now references 'renal system', but it also has a taxon constraint to Vertebrata asserted in GO. Same with the other two terms.

**Comment by ukemi** [comment]
OK. I see three terms GO:000301, GO:0003097 and GO:0003096 that are probably the source of the problem. But I don't see them in only_in_taxon.tsv.

**Comment by balhoff** [comment]
I do see them online. Did you take them out of your local copy?

**Comment by ukemi** [comment]
Weird search issue. I have removed the TCs for 4 renal terms in #18652

**Comment by ukemi** [comment]
Closing this. Removal of the constraints from the ontology file should finally fix this issue.
