### ISSUE TITLE
incorrect logic about location of GP involved in BP that is extracellular 

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#18318]
In the model:
http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00002952

I made this annotation:

```
D430042O09Rik Mmus (MGI:4128978)
_acts_upstream_of_or_within_  cerebrospinal fluid circulation 
PMID:26714646
IMP
20190426
MGI
```

However, I have noticed that MGI is also displaying an annotation for the CC term '**extracellular region**' using the same reference and evidence code. This CC annotation has the source **GOC**, so presumably it comes from some BP->CC connection.

While it is true that '**cerebrospinal fluid circulation**' occurs in the extracellular region, it is **NOT** true that the gene products that are involved in generating that flow are located extracellularly. '**cerebrospinal fluid circulation**' is one of several children of '**epithelial cilium movement involved in extracellular fluid movement**'. In every case I have annotated, the gene products involved in movement of the cilium that create extracellular flow are located within the cilium.

What is needed to prevent extracellular component annotations from being made for gene products annotated to '**epithelial cilium movement involved in extracellular fluid movement**' or any of its children?

**Comment by vanaukenk** [comment]
One idea we might want to explore is using the gp2term relations to filter ontology-based inferences, i.e. if a gp 'acts upstream of or within' a BP, it wouldn't inherit an 'occurs in' relation to the CC term associated with that BP via inter-ontology links.

**Comment by pgaudet** [comment]
Weird that taxon constraints do not use 'occurs in' for propagation but annotation predictions do - 
the rules should be consistent. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@krchristie Is this still a problem ?

**Comment by krchristie** [comment]
@pgaudet - I'm not aware of any work on this. I'll try to check next week when it's an ontology week.

**Comment by pgaudet** [comment]
@ukemi 
This touches on modeling and export - can you please look at the model and see if that's still a problem? I dont see any extracellular annotations in the annotation preview. 

Thanks, Pascale

**Comment by ukemi** [comment]
I think @vanaukenk's suggestion above is correct, but I do not see this annotation in the preview or in the MGI interface.
