### ISSUE TITLE
NTR and rename term for effector mediated immune responses

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18310]
replaces ticket
https://github.com/geneontology/go-ontology/issues/18001

- [ ] GO:0034053 modulation by symbiont of host defense-related programmed cell death
Definition: Any process in which a symbiont modulates the frequency, rate or extent of defense-related programmed cell death in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

5 EXP annotations
I checked these 5 papers and these ALL refer to 
"Effector-mediated mitigation of host-defence related programmed cell death"
Can we change this terms name to "Effector-mediated mitigation of host-defence related programmed cell death", this will really help annotators and the "effector-mediated" alteration of host is a really important concept in the pathogen community.

- [ ]  GO:0034055    positive regulation by symbiont of host defense-related programmed cell death
->  effector-mediated activation of host-defence related programmed cell death

-  [ ] GO:0034054   negative regulation by symbiont of host defense-related programmed cell dea
-> effector-mediated supression of host-defence related programmed cell death

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
Then could we have children

GONEW1 effector-mediated mitigation of plant-type  hypersensitive response (GO:0009626  plant-type hypersensitive response)
GONEW2 effector-mediated activation of plant-type  hypersensitive response
GONEW3 effector-mediated supression of plant-type  hypersensitive response


PTI  is innate so
"effector-mediated activation of plant-type  hypersensitive response"
should have the parent
GO:0052559   induction by symbiont of host immune response

**Comment by ValWood** [comment]
- [ ] GO:0034053 has narrow synonyms for PT|I which should move to the new term

**Comment by ValWood** [comment]
- [ ] add synonym effector-triggered susceptibility (ETS) PMID:22241993

to the positive regulation terms

**Comment by CuzickA** [comment]
>  add synonym effector-triggered susceptibility (ETS) PMID:22241993
to the positive negative regulation terms

I think this should be added to the positive regulation term, as the nectrotrophic pathogen effectors are activating host programmed cell death.

**Comment by ValWood** [comment]
I forgot about this term
GO:0080185   effector-dependent induction by symbiont of host immune response
Definition (GO:0080185 GONUTS page)
Any process that involves recognition of an effector, and by which a symbiont activates, maintains or increases the frequency, rate or extent of the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction. Effectors are proteins secreted into the host cell by pathogenic microbes, presumably to alter host immune response signaling. The best characterized effectors are bacterial effectors delivered into the host cell by type III secretion system (TTSS). Effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance or R proteins) and subsequent activation of host immune response. PMID:16497589

I need to update this ticket

**Comment by ValWood** [comment]
this has been dealt with in another ticket.
When the existing terms are resolved I will request the new children.

**Comment by ValWood** [comment]
Hi @pgaudet  did this get committed.?

I still don't see
"effector-mediated mitigation of plant-type hypersensitive response"

**Comment by ValWood** [comment]
Actually this was dealt with by another ticket. I will open a new ticket to add the necessary syn onyms
