### ISSUE TITLE
GO:0052031 modulation by symbiont of host defense response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18317]
- [x] GO:0052031    modulation by symbiont of host defense response
->
mitigation of host defense response

**Comment by ValWood** [comment]
PMID: 31076860

Needs all the PTI synonyms
and narrow synonymsupression of chitin-triggered immunity"

**Comment by pgaudet** [comment]
Hi @ValWood 
I changed the term label for GO:0052031 modulation by symbiont of host defense response
to 'mitigation of host defense response': 

what are the other action points here already? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I also need a definition. Did we not define 'effector activity' somewhere ?

**Comment by ValWood** [comment]
I edited the above.
I don't think they should go under
GO:0002221 pattern recognition receptor signalling pathway
(GO:0002221 is a host term, this is manipulation of the host pathway by the pathogen?)
Aren't we going to disjoint these?

**Comment by ValWood** [comment]
Gah, I got this all wrong.
Will fix. The change you did is OK.

**Comment by pgaudet** [comment]
Look what I found !!!!!!

suppression by virus of host viral-induced cytoplasmic pattern recognition receptor signaling pathway

**Comment by ValWood** [comment]
yes there are terms all over the place...

Have you got a couple of hours today to go through this? I am going around in circles and everytime I come back to it I forget where I am up to and have to go through it all again. I'm wasting so much time on it, but I think I know what the main problems are.

I am just doing a summary diagram now of  the  main processes which might help.

**Comment by pgaudet** [comment]
Will revert this. We want to keep 'modulation' - mitigation was for evasion or tolerance.
