### ISSUE TITLE
2: effector-dependent suppression by symbiont of host immune response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18325]
After
https://github.com/geneontology/go-ontology/issues/18324

GO:NEW effector-dependent suppression by symbiont of host immune innate response
~exact synonym: effector-triggered susceptibility~

def
propose
Any process that involves the suppression of a host immune response by a secreted symbiont molecule; The host is defined as the larger of the organisms involved in a symbiotic interaction.

Effector-triggered susceptibility is achieved through the interaction between a pathogen effector and its host target that eventually impinges on immune signaling. Mechanistically, this interaction results in a modification of the target and its cellular fate (Kamoun, 2007)

**Comment by ValWood** [comment]
GO:NEW effector-triggered mitigation by symbiont of host immune response
exact synonym: effector-triggered susceptibility

as a grouping term for all the effector-mediated

**Comment by ValWood** [comment]
A process stimulated by a molecule secreted by a symbiont that suppresses an innate immune system process to increase tolerance by the host. The host is defined as the larger of the organisms involved in a symbiotic interaction.

**Comment by ValWood** [comment]
Also please add  an effector-mediated parent term for this and GO:0080185 the effector-mediated supression term

**Comment by ValWood** [comment]
repurpose  GO:0033660 for
GO:NEW effector-dependent suppression by symbiont of host immune innate response
and make the existing terms synonyms

**Comment by ValWood** [comment]
@CuzickA  said


    add synonym effector-triggered susceptibility (ETS) PMID:22241993
    to the positive negative regulation terms

I think this should be added to the positive regulation term, as the nectrotrophic pathogen effectors are activating host programmed cell death.

**Comment by ValWood** [comment]
The synonyms for this branch would be
suppression of effector-triggered immunity (PTI)

**Comment by pgaudet** [comment]
New terms: 

 
+[Term]
+id: GO:0140403
+name: effector-mediated suppression of host immune innate response by symbiont
+namespace: biological_process
+def: "A process mediated by a molecule secreted by a symbiont that results in the suppression of a host innate immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction." []
+synonym: "effector dependent suppression of host immune innate response by symbiont" EXACT []
+synonym: "effector triggered suppression of host immune innate response by symbiont" EXACT []
+synonym: "effector-dependent suppression of host immune innate response by symbiont" EXACT []
+synonym: "effector-triggered suppression of host immune innate response by symbiont" EXACT []
+synonym: "suppression of effector-triggered immunity (PTI)" EXACT []
+is_a: GO:0140404 ! effector-mediated modulation of host immune response by symbiont
+created_by: pg
+creation_date: 2019-12-05T11:34:55Z
+
+[Term]
+id: GO:0140404
+name: effector-mediated modulation of host immune response by symbiont
+def: "A process mediated by a molecule secreted by a symbiont that results in the modulation (either activation or suppresion) of a host innate immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction." []
+synonym: "effector mediated modulation of host immune response by symbiont" EXACT []
+synonym: "effector triggered modulation of host immune response by symbiont" EXACT []
+synonym: "effector-dependent modulation of host immune response by symbiont" EXACT []
+synonym: "effector-triggered modulation of host immune response by symbiont" EXACT []
+is_a: GO:0052553 ! modulation by symbiont of host immune response
+created_by: pg
+creation_date: 2019-12-05T11:38:44Z


@ValWood 
1. Are the synonyms OK ? 
2. I need references. 

Thanks, Pascale

**Comment by ValWood** [comment]
PMID: 30584105

**Comment by ValWood** [comment]
PMID:24073880 
PMID: 31076860
PMID: 21467214

**Comment by ValWood** [comment]
Considerable progress has recently been made in the characterization of fungal effectors (De Wit et al., 2009; Stergiopoulos and de Wit, 2009; de Jonge et al., 2011). Typically, these effectors are relatively small proteins that are secreted either through classical systems (requiring a signal peptide and transit through endoplasmic reticulum and Golgi) or, alternatively, for some species, may also be secreted through a nonclassical pathway (Ridout et al., 2006). Their putative, and in some cases proven, function is to enable colonization by the pathogen via interfering with a variety of plant-encoded virulence targets, to effectively suppress (or activate) defense responses that might otherwise hinder pathogen colonization. Plant defense responses are normally triggered through the recognition of various pathogen-derived signals collectively described as pathogen-associated molecular patterns (PAMPs; Nürnberger and Brunner, 2002; Nürnberger and Kemmerling, 2009), a process referred to as PAMP-triggered immunity (PTI) that is often targeted by pathogen effectors (van Esse et al., 2007, 2008; Doehlemann et al., 2009). This has led to plants evolving disease resistance proteins able to detect perturbations to virulence targets that then activate a second line of defense described as effector-triggered immunity (ETI; Boller and He, 2009). This subsequent level of immunity can itself be suppressed through pathogen effector functions (Houterman et al., 2008), giving rise to the “zig-zag” model for interactions of plant pathogens with the plant defense machinery (Jones and Dangl, 2006).

**Comment by pgaudet** [comment]
The text above is from 21467214. I will add this paper as a reference.
