### ISSUE TITLE
1. The pathogen effector term, tidy and add missing parents and children GO:0080185  effector-dependent induction by symbiont of host immune response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18324]
I never find this term  because it isn't in the expected branches, and a search of QuickGO on effector never finds it (likely because of the hyphen) 

GO:0080185    effector-dependent induction by symbiont of host immune response

I never search on "effector-dependent" because  I never see it called this

**Comment by ValWood** [comment]
current definition
Any process that involves recognition of an effector, and by which a symbiont activates, maintains or increases the frequency, rate or extent of the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction. Effectors are proteins secreted into the host cell by pathogenic microbes, presumably to alter host immune response signaling. The best characterized effectors are bacterial effectors delivered into the host cell by type III secretion system (TTSS). Effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance or R proteins) and subsequent activation of host immune response. PMID:16497589

propose
Any process that involves the activation of a host  immune response by a secreted symbiont molecule; The host is defined as the larger of the organisms involved in a symbiotic interaction. 

 The rest is not required and makes it more difficult  to process.

**Comment by ValWood** [comment]
Add a comment to this term:
This terms is usually used  to annotate necrotrophs, which intentionalluy activate host cell death pathways

Note, this term will need to be linked (and possibly merged wtih) 
some of the "symbiont cell death causing terms" I will chek this next

**Comment by pgaudet** [comment]
New definition: 
"A process stimulated by a molecule secreted by a symbiont that activates a host innate immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction. In the host, effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance or R proteins) and subsequent activation of the innate immune response."

**Comment by ValWood** [comment]
Finally this term has missing parents.
<img width="1014" alt="Screenshot 2019-12-03 at 15 12 21" src="https://user-images.githubusercontent.com/7359272/70063252-59ff1100-15df-11ea-9af0-8c06ddaa3c34.png">

**Comment by ValWood** [comment]
THis term/pathway where the pathogen intentionally activated the host immune response is only for necrotrophs of plants.

The pathway that is activated is the  host hypersensitive response which results in cell death
https://www.ebi.ac.uk/QuickGO/term/GO:0052042

so we should add a bit to the definition about the innate immune pathway activated being the "effector-triggered immunity/ hypersensitive response"

**Comment by ValWood** [comment]
This term
https://www.ebi.ac.uk/QuickGO/term/GO:0052042
GO:0052042   positive regulation by symbiont of host programmed cell death
should be a parent

**Comment by ValWood** [comment]
I now think
GO:0080185 effector-dependent induction by symbiont of plant hypersensitive response
would match the definition better

**Comment by pgaudet** [comment]
effector-triggered induction of plant hypersensitive response

**Comment by ValWood** [comment]
New definition:
"A process stimulated by a molecule secreted by a symbiont that activates a host a plant hypersensitive response in order to induce plant cell necrosis. The host is defined as the larger of the organisms involved in a symbiotic interaction.

**Comment by pgaudet** [comment]
Taxon constraints added: 
Never in metazoa
Never in Viriplantae
https://github.com/geneontology/go-ontology/pull/18328

**Comment by ValWood** [comment]
val to look at this part
In the host, effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance or R proteins) and subsequent activation of the innate immune response."
