### ISSUE TITLE
obsolete GO:0098504 DNA 3' dephosphorylation involved in DNA repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18320]
This  combined MF with BP and leads to inconsistent  annotation .

It should be done as
for example

ATP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity
part_of base-excision repair

**Comment by pgaudet** [comment]
Only 2 EXP by pombase SPAC23C11.04c. I assume you'll move them ?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0098504 DNA 3' dephosphorylation involved in DNA repair' and GO:0098503 DNA 3' dephosphorylation.  The reason for obsoletion is that these terms represents molecular functions, and not a specific coordinated process. There are 2 EXP annotations to GO:0098504 (being reviewed), and no annotations to GO:0098503. 

There is one InterPro mapping:   InterPro:IPR006550 @happy-lorna 
This term is not present in any subsets. 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/18320

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 10th, 2019. Unless objections are received by December 10th, 2019, we will assume that you agree to this change.

Thanks, Pascale

**Comment by ValWood** [comment]
done
