### ISSUE TITLE
Aren't positive and negative regulation disjoint ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18349]
I just came across ' GO:0043947 positive regulation by host of symbiont catalytic activity' 
which as (had) a parent: 

 GO:0052405 negative regulation by host of symbiont molecular function

Is this allowed ? 

Thanks, Pascale

**Comment by ukemi** [comment]
It is allowed, but off the top of my head this one sounds like an error.

**Comment by pgaudet** [comment]
OK. I removed it. I guess we have no way of flagging those then. 

Thanks, Pascale
