### ISSUE TITLE
revised def for GO:0080185 effector-triggered induction by symbiont of plant hypersensitive response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18351]
I had a final task in 
https://github.com/geneontology/go-ontology/issues/18324
to look at this  definition again.

Here is revised:

"A symbiont process whereby a molecule secreted by the symbiont activates plant effector-triggered immunity (ETI) signalling and the subsequent activation of a plant hypersensitive response to induce necrosis.  In the plant, effector-triggered immunity (ETI) involves the direct or indirect recognition of an effector protein by the host (for example through plant resistance receptor or R proteins)"

**Comment by pgaudet** [comment]
Also added parent 'positive regulation by symbiont of host programmed cell death'
