### ISSUE TITLE
add check for namespace validity

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#18362]
See #18356.

**Comment by ukemi** [comment]
@balhoff, I know this check used to be in place because I have had it fail in the past. In fact, I remember you helping me trace down the error in the Travis output.

**Comment by pgaudet** [comment]
I know it was picking up when it was completely missing - was it also picking up typos ? (I also thought so....)

**Comment by ukemi** [comment]
Yup. I had put them in without the underscore by hand and it caught it.

**Comment by cmungall** [comment]
I did a test where I replicate: #18493

it failed as expected

https://travis-ci.org/geneontology/go-ontology/builds/633390910#L235-L236

```
../util/check-obo-for-standard-release.pl --disable-isa-incomplete --xref-abbs GO.xrf_abbs go-edit.obo > go-edit.obo-check.tmp && mv go-edit.obo-check.tmp go-edit.obo-check
 :: ERROR: namespace-different-from-is_a-parent: GO:0150137 in biologica_process, GO:0042089 in biological_process
```

**Comment by cmungall** [comment]
My test did not properly replicate.

This was the original: #18323 

It passed travis.

I have discovered the reason. The check only looks at asserted is-a (subClassOf), not logical defs

**Comment by ukemi** [comment]
Nice detective work @cmungall? @dougli1sqrd, can we modify the test to include both?
