### ISSUE TITLE
NTR: maintenance of ciliary planar beating movement pattern

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#18363]
For annotation of **Shinohara et  al. 2015** - Absence of   Radial Spokes in Mouse Node Cilia Is Required for Rotational Movement but   Confers Ultrastructural Instability as a Trade-Off. (PMID:26506310), I need a new term:

Name: | maintenance of ciliary planar   beating movement pattern
-- | --
Def: | The maintenance of the pattern   of ciliary movement to the planar beating pattern. Connection between the   outer doublets and the central pair via the radial spokes constrains ciliary   movement to the planar beating pattern. Cilia that lack this connection, such   as those in the embryonic node or Kupfer's vesicle, display radial movement.   [GOC:krc, PMID:26506310]
is_a: ? | `cilium movement` or `regulation of cilium movement` Does this qualify as extent of movement? @ukemi - Do you think that constraining the movement pattern of the cilium can be construed as regulation of the "extent" of the movement of the cilium such that I can put this new term as an is_a child under `regulation of cilium movement`?

**Comment by krchristie** [comment]
Hey @ukemi - I need this new term but need some input about whether this can be considered regulation, and if not, where to put it.

The gene product Rsph4a is part of the radial spoke head in cilia (9+2 structure) that have the planar beating pattern. When Rsph4a is absent, the radial spoke connection between the outer doublets and the central pair is not present and cilia have a different movement pattern, i.e. the rotational movement such as is present in the 9+0 cilia of nodal cilia. Do you think it's OK to put this new term for `maintenance of ciliary planar beating movement pattern` under `regulation of cilium movement`?

It since it doesn't seem to fit as an is_a child of `cilium movement`, which currently has two child terms:
- `cilium movement involved in cell motility` (has one child term specific to sperm flagellum movement which was created to distinguish this type of sperm movement from amoeboid sperm movement; there didn't seem to be a good reason to make a term for the movement of non-sperm ciliated cells since there isn't really anything to distinguish this from the existing term.
- `epithelial cilium movement involved in extracellular fluid movement` (noting that this term has 4 child terms, 3 of which involve planar beating, while 1 involves rotational beating)

I kind of like having the new term `maintenance of ciliary planar beating movement pattern` being under `regulation of cilium movement` because it seems more useful to only annotate the things that mediate the switch from planar beating to rotational beating, rather than everything that is involved in cilium movement.

___
On a related topic which probably eventually merits its own ticket, I just remembered that Chlamydomonas cells, which have two flagella, can move by gliding along surfaces, which seems to be mediated by IFT (intraflagellar transport linked to transmembrane molecules which span the cilium membrane to contact the surface) as well as moving through liquids via the "standard" method of flagellar beating). This suggests we might actually need to distinguish `cilium movement involved in cell motility` into that mediated by [planar?] beating versus that mediated by IFT/gliding. Note that there is already a term for `cell gliding` with two child terms (both of which seem to be defined specifically for bacteria. 

[Term]
id: GO:0071976
name: cell gliding
namespace: biological_process
def: "Cell motility that results in the smooth movement of a cell along a solid surface." [PMID:18461074]
synonym: "cell gliding motility" EXACT [GOC:mah]
is_a: GO:0048870 ! cell motility
created_by: midori
creation_date: 2010-10-21T02:33:24Z

[Term]
id: GO:0071980
name: cell surface adhesin-mediated gliding motility
namespace: biological_process
def: "Cell gliding that results from the actions of cell surface adhesin proteins that are propelled by membrane motor proteins." [PMID:18461074]
is_a: GO:0071976 ! cell gliding
created_by: midori
creation_date: 2010-10-21T03:03:44Z

> from `Jarrell & McBride 2008. The surprisingly diverse ways that prokaryotes move. PMID:18461074.` - Bacteria have various non-flagellar mechanisms that are used for crawling over surfaces. Type IV pilus extension and retraction pulls cells over moist surfaces by twitching motility. Flavobacterium spp. gliding motility involves a motor embedded in the cell envelope that moves adhesins along the cell surface. Two models have recently been proposed for Myxococcus spp. adventurous gliding: first, extrusion of polysaccharides, and second, a focal adhesion model that involves movement of cell surface adhesins by cytoplasmic motor proteins that interact with the cytoskeleton. 

[Term]
id: GO:0060294
name: cilium movement involved in cell motility
namespace: biological_process
def: "Movement of cilia mediated by motor proteins that contributes to the movement of a cell." [GOC:BHF, GOC:dph, GOC:tb]
intersection_of: GO:0003341 ! cilium movement
intersection_of: part_of GO:0048870 ! cell motility
relationship: part_of GO:0060285 ! cilium-dependent cell motility

This definition seems like it is broad enough to encompass gliding motility which is powered by the IFT motors which move along the axoneme, as well as liquid motility mediated by ciliary beating which is powered by the axonemal motors (dynein). Might be worth checking direct annotations to see if the include anything due to gliding motility, or just to beating motility...

**Comment by ukemi** [comment]
It almost seems like a regulation of biological quality, with the quality being the shape of the movement.

It seems like making two cilium movement terms makes sense, but is it cilium movement or cilium mediated. From your description, it seems like the cilium itself doesn't move.

**Comment by ukemi** [comment]
Thinking more about this:
> I kind of like having the new term maintenance of ciliary planar beating movement pattern being under regulation of cilium movement because it seems more useful to only annotate the things that mediate the switch from planar beating to rotational beating, rather than everything that is involved in cilium movement.

I can see your point here. I guess what it comes down to is whether you think the two types of movement are different processes or just different way to regulate cilium movement. It seems like you are leaning towards that latter.

**Comment by krchristie** [comment]
> It almost seems like a regulation of biological quality, with the quality being the shape of the movement.
> 
> It seems like making two cilium movement terms makes sense, but is it cilium movement or cilium mediated. From your description, it seems like the cilium itself doesn't move.

The cilium definitely moves in both planar beating and rotational movement. It's not clear to me how much the cilium moves in ciliary IFT mediated cell gliding (though I think I saw some comment that the tip of the flagellum may move to control direction of gliding), but I'll decant all of that stuff to a different ticket specific to gliding motility mediated by cilia.

**Comment by ukemi** [comment]
Yeah. It was specifically the IFT one. I pictured it as kind of how a snake moves at a much smaller level.

**Comment by krchristie** [comment]
> Thinking more about this:
> 
> > I kind of like having the new term maintenance of ciliary planar beating movement pattern being under regulation of cilium movement because it seems more useful to only annotate the things that mediate the switch from planar beating to rotational beating, rather than everything that is involved in cilium movement.
> 
> I can see your point here. I guess what it comes down to is whether you think the two types of movement are different processes or just different way to regulate cilium movement. It seems like you are leaning towards that latter.

That's a really great way you've phrased that question and it helps me clarify my thinking. I don't think that the research community thinks of planar beating versus rotational movement as two different processes. Almost all of the gene products required for ciliary movement are the same for both movement patterns. In addition to my previous thought that the annotation will be more useful as a regulation of the movement pattern, I think it's also more consistent with how the research community has discussed this to talk about it as a regulation of the movement pattern.

**Comment by krchristie** [comment]
> Yeah. It was specifically the IFT one. I pictured it as kind of how a snake moves at a much smaller level.

Ha ha! Possibly more like a tank moving on a tread perhaps, where the glycoproteins that stick out through the cilium membrane are the tread and the IFT trains moving on the axoneme are the motor.

**Comment by krchristie** [comment]
I'll put in as a regulation term. If we come up with a better way, we can change it. Thanks for great discussion :)
