### ISSUE TITLE
ntr: spindle pole body-led chromosome movement during mitotic interphase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18373]
NTR: spindle poly body/centrosome led chromosome movement during mitotic interphase

definition
A microtubule-based process in which chromosomes migrate as a result of rapid spindle pole body (SPB) / centrosome oscillations during mitotic interphase 

parent
GO:0007018    microtubule-based movement

parent
GO:0070631    spindle pole body localization
parent
GO:0051303   establishment of chromosome localization
Definition (GO:0051303 GONUTS page)
The directed movement of a chromosome to a specific location.

- [ ] I chose this parent becasue it is the closest (I found it eventually with chromosome positioning)
Would "chromosome migration/moveemnt be a better primary name for this term? establishment of localization sounds odd for directed movement?
(Or  add as synonyms)

Note: I included centrosome becasue increasingly yeast researchers are referring to the SPB as the centrosome.

reference

PMID:31483748
Title | Effects of the microtubule nucleator Mto1 on chromosome movement, DNA repair and sister chromatid cohesion in fission yeast.

**Comment by mah11** [comment]
> spindle poly body lead chromosome movement during mitotic interphase

This wording doesn't make sense. I'm assuming "poly" is a typo for "pole", but what about "lead"? It's not grammatical as written. Is the term supposed to be "spindle pole body-led chromosome movement ..."?

Also: we've had a FYPO term for a while that suggests that "mitotic spindle pole body oscillation" is a process itself, I guess immediately upstream of the chromosome movement that the proposed new term represents. Should there also be a GO:new2 for the SPB oscillation? FYPO cites PMID:12390246 and PMID:19001497 (Caveat: I haven't looked at the papers since we added the FYPO term in 2016.)

**Comment by ValWood** [comment]
Yes, sorry:
spindle pole body-led chromosome movement during mitotic interphase

**Comment by ValWood** [comment]
Actually, I think 
spindle pole body-led chromosome movement during mitotic interphase

and
mitotic spindle pole body oscillation
are describing the same phenotype. Oscillating the SPB also moves the chromosomes...

exact synonym and additional parents?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140405
+name: spindle pole body-led chromosome movement during mitotic interphase
+namespace: biological_process
+def: "A microtubule-based process in which chromosomes migrate as a result of rapid spindle pole body (SPB) and centrosome oscillations during mitotic interphase." [PMID:31483748]
+is_a: GO:0007018 ! microtubule-based movement
+is_a: GO:0051303 ! establishment of chromosome localization
+is_a: GO:0070631 ! spindle pole body localization
+relationship: happens_during GO:0051329 ! mitotic interphase
+relationship: has_participant GO:0005816 ! spindle pole body
+created_by: pg
+creation_date: 2019-12-10T09:13:47Z

@cmungall @ukemi Should I have made a logical definition with some of the subclasses ? 

Thanks, Pascale

**Comment by cmungall** [comment]
hmm, is there an analogous process in meotic interphase?

Also, this new term seems to be separated from its friends under chromosome segregation (GO:0007059) should there not be some kind of link?

Something is not sitting quite right with the logical axioms for this for me, 3 asserted is-a parents is a bad smell. I think I need to refresh my memory on the processes here. I don't think this is high priority though so feel free to ignore.

**Comment by cmungall** [comment]
Might be worth revisiting when we have more CAMs for the cell cycle, this might inform how we think of the ontology

**Comment by ValWood** [comment]
This process isn't part of chromosome segregation. This happens during interphase 
and chromosome segregation occurs in mitosis.


Effects of the microtubule nucleator Mto1 on chromosome movement, DNA repair and sister chromatid cohesion in fission yeast.
--
Authors: | Zhurinsky J, Salas-Pino S, Iglesias-Romero AB, Torres-Mendez A, Knapp B, Flor-Parra I, Wang J, Bao K, Jia S, Chang F, Daga RR
Abstract: | Although the function of microtubules (MTs) in chromosome segregation during mitosis is well characterized, much less is known about the role of MTs on chromosomal functions during interphase. In the fission yeast Schizosaccharomyces pombe , dynamic cytoplasmic MT bundles move chromosomes in an oscillatory manner during interphase via linkages through the nuclear envelope (NE) at the spindle pole body (SPB) and other sites. Mto1 is a cytoplasmic factor that mediates the nucleation and attachment of cytoplasmic MTs to the nucleus. Here, we test the function of these cytoplasmic MTs and Mto1 on DNA repair and recombination during interphase. We find that mto1Δ cells exhibit defects in DNA repair and homologous recombination (HR) and abnormal DNA repair factory dynamics. In these cells, sister chromatids are not properly paired, and Rad21 binding along chromosome arms is reduced. Our findings suggest a model in which cytoplasmic MTs and Mto1 facilitate efficient DNA repair and HR by promoting dynamic chromosome organization and cohesion in the nucleus. Movie S1 Movie S1 Time-lapse images of LacI-GFP visualizing his2 locus movement in wild type cells. Frame rate 1frame/3seconds. Movie S2 Movie S2 Time-lapse imaging of LacI-GFP visualizing his2 locus movement in mto1 Δ cells. Note frequent separation of sister chromatids at the his2 locus. Frame rate 1frame/3seconds.[hide]

There is not an exact meiotic equivalent 
but there is this process https://www.ebi.ac.uk/QuickGO/term/GO:0030989
which occurs in meiotic prophase. Here the nucleus shuttles crazily from one side of the cell to the other.
It seems to have a rtelated but different purpose

**Comment by ValWood** [comment]
> Might be worth revisiting when we have more CAMs for the cell cycle, this might inform how we think of the ontology

A GO cam can be generated for mitotic chromosome segregation. Even the  model for  mitotic chromosome segregation part of the cell cycle
but this process has 183 components
http://www.esyn.org//builder.php?type=Graph&term=GO:0000070&interactionType=physical&source=pombase&includeInteractors=false

A model for the entire mitotic cell cycle would be unwieldy (449  proteins and counting).

Although I would not put this process under cell cycle.

**Comment by ValWood** [comment]
<img width="553" alt="Screenshot 2019-12-11 at 14 48 12" src="https://user-images.githubusercontent.com/7359272/70631592-4712bf00-1c25-11ea-8a64-dd7f7110fa01.png">
