### ISSUE TITLE
ntr: DNA repair term (or help finding one)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18377]
I'm looking for the correct DNA repair term for 

intrachromosomal homologous recombination (between sister chromatids)

interchromosomal HR between homologous chromosomes is unaffected.

I found
GO:1990067    intrachromosomal DNA recombination

But this isn't related to DNA repair, so I wondered what other context this occured in

This has only 2 annotations:

UniProtKB:Q588V7 | TEB | involved_in | GO:1990067    intrachromosomal DNA recombination | ECO:0000315   IMP | PMID:16517762 |   | 3702 Arabidopsis thaliana | UniProt |  

UniProtKB:Q9C9G6 | AE7 | involved_in | GO:1990067    intrachromosomal DNA recombination | ECO:0000315   IMP | PMID:23104832 |   | 3702 Arabidopsis thaliana | TAIR

both of these seem to be describing some response to DNA damage

**Comment by ValWood** [comment]
Oh I guess 
GO:1990067 intrachromosomal DNA recombination could refer to VDJ recombination?

**Comment by ValWood** [comment]
The only other thing I have to go on is

Homologous recombination is reduced in mto1Δ cells
As HR between sister chromatids is the primary pathway for DNA repair in G2 (Harrison and Haber, 2006), we assayed for possible defects in HR in the mto1∆ mutant. Intrachromosomal recombination (i.e., be- tween sister chromatids) was assayed using a genetically based approach developed by Ahn et al. (2005).

So 
GO:0042275    JSON
error-free postreplication DNA repair
The conversion of DNA-damage induced single-stranded gaps into large molecular weight DNA via processes such as template switching, which does not remove the replication-blocking lesions but does not increase the endogenous mutation rate. PMID:11459630

Could apply, but this says nothing about the mechanism.

I'm really confused in these terms, some are mechanism, some substrate, some when the repair occurs.

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5333053/

Abstract
Accurate DNA replication is crucial for cell survival and the maintenance of genome stability. Cells have developed mechanisms to cope with the frequent genotoxic injuries that arise from both endogenous and environmental sources. Lesions encountered during DNA replication are often tolerated by post-replication repair mechanisms that prevent replication fork collapse and avert the formation of DNA double strand breaks. There are two predominant post-replication repair pathways, trans-lesion synthesis (TLS) and template switching (TS). TLS is a DNA damage-tolerant and low-fidelity mode of DNA synthesis that utilizes specialized ‘Y-family’ DNA polymerases to replicate damaged templates. TS, however, is an error-free ‘DNA damage avoidance’ mode of DNA synthesis that uses a newly synthesized sister chromatid as a template in lieu of the damaged parent strand. Both TLS and TS pathways are tightly controlled signaling cascades that integrate DNA synthesis with the overall DNA damage response and are thus crucial for genome stability. This review will cover the current knowledge of the primary mediators of post-replication repair and how they are regulated in the cell.

so
TS, however, is an error-free ‘DNA damage avoidance’ mode of DNA synthesis that uses a newly synthesized sister chromatid as a template in lieu of the damaged parent strand.

would be useful to have this in the appropriate term.

**Comment by ValWood** [comment]
OK so 
GO:0042275    error-free postreplication DNA repair
The conversion of DNA-damage induced single-stranded gaps into large molecular weight DNA via processes such as template switching, which does not remove the replication-blocking lesions but does not increase the endogenous mutation rate. PMID:11459630

This sounds like the right thing, but 


- [ ]  1. Does it need a recombinational repair parentage too?

- [ ] 2. Add synonym "intrachromosomal homologous recombination"

- [ ] . Improve
GO:0042275  definition
The conversion of DNA-damage induced single-stranded gaps into large molecular weight DNA via processes such as template switching, which does not remove the replication-blocking lesions but does not increase the endogenous mutation rate. PMID:11459630

What does "such as" template switching mean,  are there other processes that apply?

Can this definition mention
"DNA molecule is repaired using the homologous sequence of the sister chromatid as a template"?

**Comment by ukemi** [comment]
PMID:7748165 and the references that cite it could be useful.

**Comment by ValWood** [comment]
closing as I didn't need this. I still think there are ontology issues but that would require a DNA repair expert to figure out what they are...
