### ISSUE TITLE
wrong EC on GO:0004601

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#18389]
The definition of GO:0004601 and the Rhea link make this EC 1.11.1.- instead of 1.11.1.7. Excerpt:
```
name: peroxidase activity
def: "Catalysis of the reaction: donor + hydrogen peroxide = oxidized donor + 2 H2O." [EC:1.11.1.7]
synonym: "lactoperoxidase activity" NARROW []
synonym: "myeloperoxidase activity" NARROW []
xref: EC:1.11.1.7
xref: KEGG_REACTION:R03532
xref: MetaCyc:PEROXID-RXN
xref: MIPS_funcat:32.07.07.05
xref: RHEA:23637
```

**Comment by hdrabkin** [comment]
Using RHEA's xref to the EC 
RHEA:56136 appears to be more appropriate
2 a phenolic donor + H2O2 = 2 a phenolic radical donor + 2 H2O; I will change the rhea to this.
And RHEA:23637 is marked obsolete at RHEA anyways.

**Comment by hdrabkin** [comment]
Replaced RHEA with correct RHEA:56136;
