### ISSUE TITLE
NTR: 'Negative regulation of interleukin-25 secretion'

### ISSUE THREAD

**Issue by ShirinSaverimuttu** [geneontology/go-ontology#18395]
Request for 'negative regulation of interleukin-25 secretion' term to be added.

Evidence - PMID: 27901018. Figure 3:

> Transfection of miR-31 significantly reduced the concentration of interleukin-25 within culture supernatants. 

Note: miR-31 directly targets interleukin-25 mRNA, reducing its expression (Figure 3).

Currently only GO:0072623 'interleukin-25 secretion' exists. 

cc
@BarbaraCzub 
@RLovering

**Comment by addiehl** [comment]
If the data supports it, I would recommend a term like "negative regulation of interleukin-25 biosynthesis," since it sounds like you can pinpoint that the biosynthesis is directly affected, not the downstream secretion process.

**Comment by BarbaraCzub** [comment]
We do annotate 'regulation of x biosynthesis' when the data supports it; with these terms we use the 'involved_in' qualifier for miRs. Whereas the 'regulation of x secretion' is only ever captured with the 'acts_upstream_of' qualifier, when miRs are the regulators. 
cc @RLovering @ShirinSaverimuttu
