### ISSUE TITLE
mitochondrial DNA & ER inheritance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18417]
GO:0033955    
mitochondrial DNA inheritance
Definition 
The process in which copies of the mitochondrial genome are distributed into daughter mitochondria upon mitochondrial fission.

13 annotation
1 PomBase
1 TAIR
1 MGI
10 GeneDB T. brucie

As far as I can tell, this is a phenotype, not an active process. DNA are partitioned arbitrarily when mitochondria undergo fission (but most daughters get some  copied because there are 1000's)
I am removing the PomBase annotation. 
Should  the term be obsoleted?
Or merged into the  (current) sibling "mitochondrial fission" as a related synonym?

**Comment by ValWood** [comment]
Also the child term

GO:0033955    JSON
mitochondrial DNA inheritance
Biological Process

Definition (GO:0033955 GONUTS page)
The process in which copies of the mitochondrial genome are distributed into daughter mitochondria upon mitochondrial fission.


No annotations, process  does not exist?

**Comment by ukemi** [comment]
Are you sure?
PMID:25237825

**Comment by ukemi** [comment]
PMID:29880721

**Comment by pgaudet** [comment]
@ValWood You mention GO:0033955 twice - I dont see a child for GO:0033955; can you check ?

**Comment by pgaudet** [comment]
Looking at the review PMID:24183694, it sound like mitochondrial DNA inheritance corresponds to mt DNA replication + segregation. 

I agree many of the annotations just look like phenotypes. I think the pombase annotation corresponds to 'GO:0090146 establishment of mitochondrion localization involved in mitochondrial fission' - what do you think ? 

I propose we review the annotations before deciding what to do here.

**Comment by ValWood** [comment]
I mean also:

GO:0000002    JSON
mitochondrial genome maintenance
Definition (GO:0000002 GONUTS page)
The maintenance of the structure and integrity of the mitochondrial genome; includes replication and segregation of the mitochondrial chromosome.

However , this has lots of annotations.

I have been under the impression for  many years that these are phenotypes. I have never seen an active mechanism for  "mitochondrial DNA inheritance" as defined here.

Fission happens and large DNA copy number means that most daughter mitochondria will have plenty.

This makes GO:0000002   mitochondrial genome maintenance 
unnecessary

I will have a quick look at the papers David suggested.

**Comment by ValWood** [comment]
i.e there is no mitochondrial segregation machinery

Its replication + mitochondrial fission

But it wouldn't make sense as a parent, it's just an "observation"

**Comment by ukemi** [comment]
The idea of the mitochondrial bottleneck during oogenesis was what I had in mind, but it looks like the modern thought on this is that it is just probability and there might not be a genetic mechanism. Still worth investigating further.

**Comment by ValWood** [comment]
Isn't that about 

GO:0000001    JSON
mitochondrion inheritance
Biological Process

Definition (GO:0000001 GONUTS page)
The distribution of mitochondria, including the mitochondrial genome, into daughter cells after mitosis or meiosis, mediated by interactions between mitochondria and the cytoskeleton. PMID:10873824 PMID:11389764

This is OK (although the mechanism appears to also be  dependent on fission.

Fission increases during division so there are more small mitochondria  increasing the chance of 
each daughter havoing mitochondria:

Additionally, increased mitochondrial fragmentation upon the onset of mitosis has also been observed (3), perhaps indicating a binomial partitioning or independent segregation mechanism for mitochondrial dis- tribution wherein each mitochondrion in the mother has a 50% likelihood of being partitioned into either of the daughter cells by virtue of symmetric division and without the involvement of active processes.
Although the molecular players that effect fission and fusion have been identified in several systems, the cellular signals that regulate these events are largely elusive. Here, we demonstrate that mitochondria piggyback on dynamic microtubules to selectively undergo fission when microtu- bules depolymerize. Reorganization of interphase microtu- bules into the nucleus when cells prepare for division also provide the cue for increased mitochondrial fission. We quantified the number of mitochondria in mother cells immediately after formation of mitotic spindle within the nucleus and the number of mitochondria in the resulting daughter cells and confirmed that the partitioning was indeed a good fit to a binomial distribution, indicating that an independent segregation mechanism serves to distribute mito- chondria into the two daughter cells. We determined that the presence of long and stabilized microtubules was inhibitory to unopposed fission even when Dnm1 was overexpressed. Finally, we discovered that microtubule-bound mitochondria were unlikely to undergo fission due to the unavailability of space between microtubules and mitochondria for the forma- tion of the Dnm1 ring.

**Comment by ValWood** [comment]
Its pretty cool. Fission is inhibited by association with  interphase microtubules.

This actually makes it difficult to separate ""fission" from "inheritance"  but I was going to ignore this for now. It is more meaningful than the 

"DNA inheritance" and "maintenence terms".

(I removed the PomBase annotation yesterday)

**Comment by ValWood** [comment]
The annotations seem to be  phenotypes;


TIM17 | Essential component of the TIM23 complex |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000004347 | mitochondrial import inner membrane translocase subunit tim-17 pthr10485 | protein |   | PMID:18826960 | 20120501
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | TIM17 | Essential component of the TIM23 complex |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000004676 | mitochondrial import inner membrane translocase subunit tim-17 pthr10485 | protein |   | PMID:18826960 | 20120501
  | MDV1 | Peripheral protein of cytosolic face of mitochondrial outer membrane |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr19857 | protein |   | PMID:11038182 | 20010118
  | MEF2 | Mitochondrial elongation factor involved in translational elongation |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr43261 | protein |   | PMID:21414316 | 20140325

Protein of unknown function		mitochondrial genome maintenance		SGD	Saccharomyces cerevisiae S288C	IMP			protein		PMID:19751518	20091009
	REX2	3'-5' RNA exonuclease		mitochondrial genome maintenance		SGD	Saccharomyces cerevisiae S288C	IMP		oligoribonuclease, mitochondrial pthr11046	protein		PMID:9933355	20080611
	REX2	3'-5' RNA exonuclease		mitochondrial genome maintenance		SGD	Saccharomyces cerevisiae S288C	IGI	SGD:S000004917	oligoribonuclease, mitochondrial pthr11046	protein		PMID:9933355	20080611
	REX2	3'-5' RNA exonuclease		mitochondrial genome maintenance		SGD	Saccharomyces cerevisiae S288C	IGI	SGD:S000006228	oligoribonuclease, mitochondrial pthr11046	protein		PMID:9933355	20080611


etc etc

**Comment by ValWood** [comment]
The same seems to apply to ER inheritance
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0048309&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

21 EXP all IMP from SGD

I don't think there is any active partitioning mechanism. Will check later with authors of curation I am checking.

**Comment by ValWood** [comment]
I checked with 2 pombe researchers who study ER organization:

1
my feeling is that there is no active 'partitioning mechanism' - beyond attaching the ER to the cortex as cells grow.  pombe divides in the middle so that takes care of ER distribution to both daughter cells. 

2
I agree with Snezhka. I also do not imagine an active mechanism just for ER inheritance – I feel that
1)      ER-PM contacts
2)      connection with nuclear envelope
3)      actomyosin transport (towards tips)
all can take care of ER dispersal to daughter cells. 

So, unless there is any active mechanism in budding yeast, because of budding, these seem like a phenotype of abnormal ER organization
 @srengel  could you check that?

**Comment by srengel** [comment]
@ValWood is the suggestion to move the ER inheritance ones up to ER organization?

i can move the mito genome maintenance ones to be phenotype annotations instead of GO.

**Comment by ValWood** [comment]
I hadn't thought about the ER one. Yes merge up and make related synonym would work?

**Comment by ValWood** [comment]
I wasn't sure if budding yeast had some 'special' mechanism because of budding, but when I looked most of the annotations were just to the reticulon-and other general ER membrane organization things.
v

**Comment by ValWood** [comment]
Although there is not identified mechanism  fpr mitochondrial inheritance in mitotic/somatic cells  There is now a  new paper describing a mechanism for inheritance in mitochondria during meiosis in isogamous organisms, by 'tethering'

PMID:31582398
Title | Cortical tethering of mitochondria by the anchor protein Mcp5 enables uniparental inheritance.

**Comment by ValWood** [comment]
there are several strategies for uniparental inheritance in meiosis

 including subjecting paternal mitochondria to
 (1) sequestration and ex- clusion (Yu and Russell, 1992), 
(2) selective lysosomal degrada- tion via ubiquitination (Sutovsky et al., 1999, 2000), or 
(3) simple dilution due to the large size of the female gamete in comparison to the male gamete (Birky, 1995; Wilson and Xu, 2012). (this one sounds passive)

So, there probab ly should. be a term for "mitochondrial inheritance during meiosis"

**Comment by ValWood** [comment]
~Also active  process in S. cerevisiae to get mitochondria into the bud (vegetative growth)
Tethering of mitochondria by Num1 aids in the retention of a mitochondrial population within the mother cell (Lackner et al., 2013), while another population is transported on actin cables to the bud by the activity of the myosin V, Myo2 (Altmann et al., 2008; Fo ̈rtsch et al., 2011).

**Comment by ValWood** [comment]
See also
https://github.com/geneontology/go-ontology/issues/12828

need to look at
GO:0051646   mitochondrion localization
GO:0048311   mitochondrion distribution
GO:0051659   maintenance of mitochondrion location
GO:0051654    establishment of mitochondrion localization
GO:0048312    intracellular distribution of mitochondria (synonym mitochondrion positioning within cell) 
GO:0000001    mitochondrion inheritance
GO:0033955    mitochondrial DNA inheritance

**Comment by ValWood** [comment]
<img width="776" alt="Screenshot 2020-03-29 at 15 34 14" src="https://user-images.githubusercontent.com/7359272/77851769-c3c8a980-71d2-11ea-8075-1b5c42d1dcf4.png">

**Comment by ValWood** [comment]
We should review to see what processes are annotated

All I have figured so far

Fission yeast
In pombe there is no mechanism for  "segregation of mitochondria
In interphase there are more larger mitochondria.
During mitosis there is a lot of mitochondrial fission to give larger numbers of smaller mitochondria.
https://www.pombase.org/reference/PMID:30602572
as a consequence, most cells will get some mitochondria in any division

Mitochondria are  critically tethered  in meiosis and this enables uniparental inheritance
https://www.pombase.org/reference/PMID:31582398

I annotated these to an adaptor term and   "mitochondrion localization"
I could have used *any* of the other terms.

**Comment by ValWood** [comment]
Suggestions

- [ ] I can't find any evidence that GO:0033955   
Definition 
The process in which copies of the mitochondrial genome are distributed into daughter mitochondria upon mitochondrial fission.

Is a process. It just happens during fission, there is no separate mechanism  for segregation

-> action, merge into parent
GO:0000266    JSON

-  [ ]   GO:0090146    establishment of mitochondrion localization involved in mitochondrial fission
mitochondrial fission

This term seems unnecessary, merge into 'mitochondrion fission' parent  or obsolete? (no annotations)
Also it is defineded as directed movement which would be wrong (directed movement is transport)  so obsoletion might be better?


- [ ]  GO:0090145   mitochondrial nucleoid organization involved in mitochondrial fission
Definition (GO:0090145 GONUTS page)
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the mitochondrial nucleoid that contributes to mitochondrial division.

I don't know what this means ?  It has no annotations. Is the nucleoid involved in fission - I have never read about this, is there a reference? (I apologise if I ever requested this term!)


- [ ]  GO:0048311    mitochondrion distribution
Biological Process
Definition 
Any process that establishes the spatial arrangement of mitochondria between and within cells.

I'm confused by this term. I think the 'between and within cells'. part is so that it  covers  localization. within a cell, AND inheritance. In this case it can merge into 
GO:0051646    mitochondrion localization
because "mitochondrion inheritance" is already a descendant, this term is redundant.

- [ ] ditto 
GO:0048312   intracellular distribution of mitochondria

has 22 EXP annotations. Some  annotation sseem to be describing 'fission' and in these cases localization is just a consequence (phenotype)

but I don't know enough about how mitochondria move around in animal cells. Some of these annotations  might be better described as transport as they possibly involve the. cytoskeleton, I'm not sure.....

- [ ] We can keep
- GO:0048309    endoplasmic reticulum inheritance
- in case S. cerevisiae has a cytoskeleton-based  mechanism  to get ER into the bud (as for mitochondria), but add a taxon restriction 
- "never in fission yeast/ S. pombe " so that it doesn't get PAINTED over to pombe

**Comment by pgaudet** [comment]
Taxon constraint for ER inheritance: https://github.com/geneontology/go-ontology/compare/master...pgaudet-patch-29?quick_pull=1

**Comment by pgaudet** [comment]
@ValWood 
How about this: 

 - [ ] GO:0048311 mitochondrion distribution &  GO:0048312 intracellular distribution of mitochondria
merge into GO:0051646 mitochondrion localization

 - [ ]  Obsolete 
GO:0090146 establishment of mitochondrion localization involved in mitochondrial fission
GO:0090147 regulation of establishment of mitochondrion localization involved in mitochondrial fission 
GO:0090145 mitochondrial nucleoid organization involved in mitochondrial fission
No annotations
 
 - [ ]  GO:0033955 mitochondrial DNA inheritance
Obsolete +
consider  GO:0000002 mitochondrial genome maintenance
consider  GO:0000266 mitochondrial fission

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0090146 establishment of mitochondrion localization involved in mitochondrial fission
GO:0090147 regulation of establishment of mitochondrion localization involved in mitochondrial fission
GO:0090145 mitochondrial nucleoid organization involved in mitochondrial fission
No annotations

GO:0033955 mitochondrial DNA inheritance - 12 EXP, annotation review ticket https://github.com/geneontology/go-annotation/issues/3674

The reason for obsoletion is that those terms represent phenotypes/observations of other processes, such as consider GO:0000002 mitochondrial genome maintenance and GO:0000266 mitochondrial fission. 

There are no mappings, those terms are not present in any subsets.

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 17th. Unless objections are received by March 17th, 2021, we will assume that you agree to this change.
 
You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/18417
 
 
Thanks, Pascale
