### ISSUE TITLE
cellular component movement has "motility' synonyms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18410]
cellular component movement has "motility' synonyms

GO:0051272    positive regulation of cellular component movement
Biological Process

Definition (GO:0051272 GONUTS page)
Any process that activates or increases the frequency, rate or extent of the movement of a cellular component.
Synonym | Type
-- | --
upregulation of cell motility | exact
stimulation of cell motility | narrow
up regulation of cell motility | exact
up-regulation of cell motility | exact
positive regulation of cell movement | related
activation of cell motility | narrow
positive regulation of cellular component motion | exact

these are different things?

**Comment by ukemi** [comment]
This just seems wrong. Cell motility is the motion of a cell, not any cellular component.

**Comment by deustp01** [comment]
The biology sort of makes sense, though. Increased activity of a ruffled membrane cell component leads to / is needed for / is the molecular mechanism by which a cell achieves greater motility. So the synonyms are inexact or wrong but there is a close relationship.

**Comment by ukemi** [comment]
But movement of any cellular component inside a cell, like nuclear migration, is also movement of a cellular component. But I don't think we would call it cell motility. That would be movement of the cell. So in a sense, you are right, but they shouldn't be exact synonyms. It looks like at some point someone changed the term, but didn't change the synonyms.

**Comment by deustp01** [comment]
@ukemi yes, exactly. There's a connection, the one suggested by the current synonyms is wrong, and it's beyond my ontological skill level to state it correctly.

**Comment by ukemi** [comment]
Maybe I'm missing something, but I thought the simplest solution would be to just change the synonyms to cellular component instead of cell.

**Comment by ukemi** [comment]
In 2009 this term was changed from regulation of cell motion to regulation of cellular component movement. This effectively changed the thing that was moving from the cell to a GO CC.

**Comment by ValWood** [comment]
I have never seen the word motility used in the context of a cellular components, only cells so I think that could also be confusing. Wouldn't it be better to delete them?

**Comment by ValWood** [comment]
Motility is the ability of an organism to move independently, using metabolic energy. This is in contrast to mobility, which describes the ability of an object to be moved.

**Comment by ukemi** [comment]
I have no problem deleting synonyms if you think they are misleading.

**Comment by ValWood** [comment]
It's worse than that.

Its children include things like

positive regulation of monocyte chemotaxis

which is cell migration!
	positive regulation of cell migration involved in sprouting angiogenesis
(201)	negative regulation of bacterial-type flagellum-dependent cell motility
(191)	positive regulation of cell motility
(169)	negative regulation of blood vessel endothelial cell migration
(164)	regulation of axon guidance

It seems to be a mixture of cellular components, and cells under here...

**Comment by ukemi** [comment]
Cells are a cellular component in GO.

**Comment by ValWood** [comment]
The cellular componenets I have used that have this parent, include

	negative regulation of plus-end directed microtubule sliding
+	positive regulation of actin filament-based movement
+	positive regulation of nuclear migration during mitotic telophase

but most cellular component movement (i.e chromosome movement) is not under this term...

**Comment by ukemi** [comment]
I think you are misunderstanding this term. Have a look at the definition and the term to which this regulation refers. Remember terms are tied to the definitions.

**Comment by ValWood** [comment]
So, some cell motility terms are under here:
https://www.ebi.ac.uk/QuickGO/term/GO:0016477 (cell migration)
and some are under here
https://www.ebi.ac.uk/QuickGO/term/GO:0051272 
which has the parent

GO:0006928    movement of cell or subcellular component

I don't think you should lump these.

Movement of a cell is motility.

Movement of (what I would call) a cellular component isn't

**Comment by ukemi** [comment]
Cell migration is different. It is special in that it results in the movement to a specific place. Amebae are motile, but their movement is not cell migration. When I look at the ontology here, the structure makes sense except for these synonyms.

**Comment by ukemi** [comment]
So migration is a special type of motility, and cell motility is a type of cellular component motility because in GO a cell is a cellular component.

**Comment by ukemi** [comment]
I am going to delete the synonyms. Please have a careful look at the structure and the definitions of these terms. I think they are consistent. I'm going to close this ticket after taking away the synonyms. If you think about this for a while after looking at the structure and the definitions, open another ticket with what you think needs to be done.

**Comment by ValWood** [comment]
OK I see now. Could the synonyms just move to the sibling 
GO:0048870    cell motility?

I guess I am confused by the use of cellular component here (the non regulation parent says
"cell or subcellular structure"
and the fact that not all  "cellular component movement" is under here.

But I never noticed this term before, so it probably isn't causing any harm.

**Comment by ukemi** [comment]
[Term]
id: GO:0005623
name: cell
namespace: cellular_component
def: "The basic structural and functional unit of all organisms. Includes the plasma membrane and any external encapsulating structures such as the cell wall and cell envelope." [GOC:go_curators]
subset: goslim_chembl
subset: goslim_generic
subset: goslim_plant
xref: NIF_Subcellular:sao1813327414
xref: Wikipedia:Cell_(biology)
is_a: GO:0005575 ! cellular_component
