### ISSUE TITLE
Question about GO:0052639 and GO:0052640.

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#18427]
Dear GO curators,
GO:0052639 and GO:0052640 are they the same?

If not
what is the difference between  **salicylic acid glucose ester** and **salicylic acid 2-O-glucoside**?

Regards

**Comment by hdrabkin** [comment]
hmm; I would say off the top of my head they are =, but let me do a chebi check (chebi search is not working at the moment... timing out)

**Comment by pgaudet** [comment]
Note that they have different MetaCyc x ref - the product looks different.

**Comment by Nizal-Shammry** [comment]
> hmm; I would say off the top of my head they are =, but let me do a chebi check (chebi search is not working at the moment... timing out)

I terms of chebi: I have only found **1-O-salicyl-D-glucose** (link: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:133564) and has_related_synonym that is  salicylate-D-glucose ester which I think is more related to GO:0052639. However, **salicylic acid 2-O-glucoside** seems not exist in chebi !!

**Comment by hdrabkin** [comment]
Yes one is an ester (ie, lined to the carboxylic acid group of salicylic acid (for example #1 in https://chem.libretexts.org/Bookshelves/Ancillary_Materials/Reference/Organic_Chemistry_Glossary/Ester) , and the other is linked to the 2'-OH of  salicyclic acid.  (technically an ether bond, where one R group is the salicylic acid, the other the glucoside). I will make a rhea request for these two reactions.

**Comment by hdrabkin** [comment]
AND remove the 3 digit ecs while I'm at it.

**Comment by hdrabkin** [comment]
Request to RHEA sent.

**Comment by hdrabkin** [comment]
CHEBI:133564 definitely for GO:0052639; 
Odd that when I put in the InChi supplied by Metacyc, CHEBI could not find. 
SO we are all agreed that these are definitely NOT the same terms. When they get different RHEAs, the reactions can be updated for clarity.

**Comment by hdrabkin** [comment]
removed 3 digit ecs

**Comment by Nizal-Shammry** [comment]
chebi updated: https://github.com/ebi-chebi/ChEBI/issues/3716

**Comment by hdrabkin** [comment]
Will still need to wait for RHEA, but I will append the CHEBI id to my RHEA request.

**Comment by hdrabkin** [comment]
Actually you don't have to wait for anything as it is clear what terms are which in an annotation. The RHEA ids will allow a clearer definition.

**Comment by hdrabkin** [comment]
RHEA:62312  salicylate + UDP-α-D-glucose => H+ + salicylate 2-O-β-D-glucoside + UDP
and
RHEA:62316 salicylate + UDP-α-D-glucose = 1-O-salicyl-β-D-glucose + UDP
are now approved
I can add these to the ontology once these become public

**Comment by hdrabkin** [comment]
As of today the RHEAs are not public yet.

**Comment by hdrabkin** [comment]
As of today, RHEAs are public; added and  closing ticket.
