### ISSUE TITLE
NTR: MOR signalling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18442]
MOR signaling pathway 
Synonym morphogenesis Orb6 network

def
Signalling pathway that regulates interphase polarized growth and cell separation at the end of cytokinesis through activation of the NDR1/2-related kinase 

Parent

Refs

Fission yeast germinal center (GC) kinase Ppk11 interacts with Pmo25 and plays an auxiliary role in concert with the morphogenesis Orb6 network (MOR) in cell morphogenesis. J Biol Chem 2010; 285:35196-205; PMID:20826805; http://dx.doi. org/10.1074/jbc.M110.176867

Conserved Orb6 phosphorylation sites are essential for polarized cell growth in Schizosaccharomyces pombe. PLoS ONE 2012; 7:e37221; PMID:22629372; http://dx.doi. org/10.1371/journal.pone.0037221

The mitosis-to-interphase transition is coordinated by cross talk between the SIN and MOR pathways in Schizosaccharomyces pombe. J Cell Biol 2010; 190:793-805; PMID:20805322; http://dx.doi.org/10.1083/jcb.201002055

Fission yeast MO25 protein is localized at SPB and septum and is essential for cell morphogenesis. EMBO J 2005; 24:3012- 25; PMID:16096637; http://dx.doi.org/10.1038/ sj.emboj.7600782

Ste20/GCK kinase Nak1/ Orb3 polarizes the actin cytoskeleton in fission yeast during the cell cycle. J Cell Sci 2005; 118:1033- 44; PMID:15731009; http://dx.doi.org/10.1242/ jcs.01690

Dividing the spoils of growth and the cell cycle: The fission yeast as a model for the study of cyto- kinesis. Cytoskeleton (Hoboken) 2011; 68:69-88; PMID:21246752; http://dx.doi.org/10.1002/ cm.20500

**Comment by ukemi** [comment]
Looks like MOR is most often used for mu-opioid signaling. Might use 'morphogenesis ORB6 signaling pathway', but still investigating.

**Comment by ukemi** [comment]
Hi @ValWood. I'm trying to come up with a name and a grouping for this pathway. Looking at PMID:22079013, it looks like it is in a family of pathways that includes the Hippo pathway. We have hippo signaling (GO:0035329) as a child of 'intracellular signal transduction'. So here is the big question: how does this new request relate to the hippo signaling pathway? From our definition of hippo signaling, it seems that it is a generic parent that would classify all of the pathways from this review (hippo or one of its orthologs). But then the question is, do we want to enumerate the pathways further and create six children or just create synonyms? We have septation initiation signaling, but it it categorized under 'small GTPase mediated signal transduction'. Since Sid2 is annotated to it, I imagine it is also in the mix here somehow. We need to decide where these pathways begin and end and what is the best way to distinguish or group them. Thoughts?

**Comment by ValWood** [comment]
human orthologs are 
pombe nak1 .  human STK38 https://www.uniprot.org/uniprot/Q15208
pombe orb6  human STK24/25/26 
pombe mob2  human MOB1A/2/3A/B/C
(these don't seem to be  annotated to specific pathways)

It isn;'t hippo,  (yeast don't have hippo and this pathway has human orthologs)

I was also going to open another ticket to 'suggest we remove some of the parents from SIN signalling including the GTPase parent. It would be has_part GTPAse activity, but 'small GTPase mediated signal transduction'. is an odd parent (I know I requested this in the past ). 
The MOR signalling network is called RAM signalling in S. cerevisiae.
I think it would be good to refer to this as RAM/MOR signalling pathway/network, so it could be used by pombe and S. cerevisiae.

Also  this pathway is described as  RAM/MOR signalling network in plants:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4479753/

The plant paper describes the network  quite generically:

The core of the yeast RAM signalling network consists of two kinases (CBK1 and KIC1) and four associated proteins (MOB, HYM1, TAO3 and SOG2) (Kurischko et al., 2005). The pivotal element of RAM is the kinase CBK1, belonging to the NDR (Nuclear Dbf2 Related) family of AGC kinases (Hergovich et al., 2006), and its activating protein MOB2. MOB2 has no intrinsic activity but its binding to CBK1 is necessary for the regulation of kinase activity. The CBK1–MOB2 complex has a dual role: the regulation of ACE2, a yeast-specific transcription factor driving the expression of genes involved in mother/daughter cell separation, and the control of polarized morphogenesis by co-ordinating the organization of the actin cytoskeleton. These two functions are independent (Nelson et al., 2003), but rely on common upstream regulatory components that have been shown to be generally conserved in eukaryotes (Maerz and Seiler, 2010): the four proteins HYM1, TAO3, SOG2 and KIC1 (Kurischko et al., 2005). KIC1 is a member of the PAK1/Ste20 kinase family and phosphorylates CBK1. HYM1, TAO3 and SOG2 have unknown molecular functions (Kurischko et al., 2005) but seem to act upstream of CBK1 activation (Nelson et al., 2003). As ACE2 is exclusively present in budding yeast, while the remaining RAM components are conserved among eukaryotes and fungi, an MOR (Morphogenesis Orb6 Network) network has been proposed as the conserved pathway regulating cell separation and polarity in fungi and higher eukaryotic organisms (Maerz and Seiler, 2010). For clarity and completeness, we refer throughout this paper to the RAM/MOR signalling network.



This is the only major yeast signalling pathway which does not have a GO term as far as I know.

**Comment by ukemi** [comment]
So how does this fit into figure 1 of the review? It shows hippo in flies.

**Comment by ukemi** [comment]
I can put it in as a placeholder, but I don't think we can use MOR because of confucsion with the mu opioid receptor. Even if I put it in, I'd like to refine it a bit.

**Comment by ValWood** [comment]
It's a huge family though. I think Hippo is an example of   Ste20 family protein kinase (as is Sid1). Fission yeast has 5 of the GC(germinal centre) kinases and none of them are orthologous to HIppo.

Which review?

**Comment by ValWood** [comment]
can't we use

RAM/MOR (It is often reported like this, and is used for plants). Then RAM and MOR can be narrow for searching

**Comment by ukemi** [comment]
This review: PMID:22079013
I will put it in as the RAM/MOR signaling pathway.

**Comment by ValWood** [comment]
Thanks @ukemi 
I will try to figure out generic beginning and end.
This will be useful even if it merges one day, but this is an 'ancient' conserved pathway that is well-studied in yeast.

**Comment by ukemi** [comment]
And if the reviews I read are accurate, it has been co-opted for other purposes in other organisms. The challenge is when has it diverged enough to be considered a separate pathway, an age-old question in GO.
