### ISSUE TITLE
Peregrinol diphosphate synthase activity

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#18441]
Hi GO,

I would need a GO term for peregrinol diphosphate synthase activity (which produces peregrinol diphosphate from geranylgeranyl diphosphate (GGPP))

Thanks

Emmanuel

Term: Peregrinol diphosphate synthase activity
Definition:
Catalysis of the reaction:
peregrinol diphosphate = all-trans-geranylgeranyl diphosphate + H2O;

probably child of GO:0016836 hydro-lyase activity

Xref:
RHEA:54652
EC:4.2.1.174

PMID:29315936, 24990389;

**Comment by hdrabkin** [comment]
Please suggest is_a parents

**Comment by SuperManu74** [comment]
probably child of GO:0016836 hydro-lyase activity

**Comment by hdrabkin** [comment]
Note all CHEBI's are in ontology already.

**Comment by hdrabkin** [comment]
+id: GO:0106238
+name: peregrinol diphosphate synthase activity
done.
