### ISSUE TITLE
Kolavenyl diphosphate synthase

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#18450]
Hi GO,

I would need a GO term for kolavenyl diphosphate synthase activity (which produces kolavenyl diphosphate from geranylgeranyl diphosphate (GGPP))

Thanks

Emmanuel

Term: Kolavenyl diphosphate synthase activity
Definition:
Catalysis of the reaction:
all-trans-geranylgeranyl diphosphate = (+)-kolavenyl diphosphate;

probably child of GO:0016872 intramolecular lyase activity

Xref:
RHEA:54676
EC:5.5.1.29

PMID:29315936;

**Comment by hdrabkin** [comment]
+id: GO:0106242
+name: kolavenyl diphosphate synthase activity
