### ISSUE TITLE
Should GO:0004674 and GO:0050316 be splitted into four terms !!

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#18460]
Dear GO curators,

From a computational point of view, dividing the GO:0004674 into two terms (i.e one for serine and the other for threonine) would be preferable. Similarly the GO:0050316.

**Comment by deustp01** [comment]
GO:0004674 - protein serine / threonine phosphorylation - at least in humans, as far as I know, enzymes that distinguish serine substrates from threonine ones are rare, if there are any at all. The downstream process consequences of threonine phosphorylation may differ from those of serine phosphorylation but no more that the differences between serine phosphorylation on different proteins (or different serine residues of the same protein. That sounds like something to deal with at the level of annotation. If I've missed something, PMIDs to set me straight and document the split would be great

GO:0050316 - deoxynucleotiode kinase. There is a large literature on the exact substrate specificities of these kinases, some of it captured [here](https://reactome.org/content/query?q=R-HSA-499943). Anything less than a split to create separate activity terms for each nucleotide mino- and di-phosphate substrate, noting also that some of the activities work on both ribo- and deoxyribonucleotides, would fail to capture some of the possible distinctions of substrate specificity. But is this much detail useful at the level of the ontology?

**Comment by Nizal-Shammry** [comment]
I think we have duplicate terms here: GO:0004674 GO:0004712

**Comment by deustp01** [comment]
No.  GO:0004712 protein serine/threonine/**_tyrosine_** kinase activity versus  GO:0004674 protein serine/threonine kinase activity - the distinction between acting only or ser / thr hydroxyl residues and on ser / thr / tyr hydroxyls is functionally important. I'm not sure that further distinction between ser and thr is useful.

**Comment by Nizal-Shammry** [comment]
Thanks for the great clarification, however, my comments were from an ontology's developer point of view. 

> No. GO:0004712 protein serine/threonine/**_tyrosine_** kinase activity versus GO:0004674 protein serine/threonine kinase activity - the distinction between acting only or ser / thr hydroxyl residues and on ser / thr / tyr hydroxyls is functionally important. I'm not sure that further distinction between ser and thr is useful.

**Comment by deustp01** [comment]
I'm confused. The two molecular functions GO:0004712 and GO:0004674 are different at the level of biology., so why does the formal logic of the ontology require them to be merged?

**Comment by Nizal-Shammry** [comment]
> I'm confused. The two molecular functions GO:0004712 and GO:0004674 are different at the level of biology., so why does the formal logic of the ontology require them to be merged?

Not merged, but to be split (i.e two different GO IDs) and documented

**Comment by deustp01** [comment]
An hour ago you labeled GO:0004712 and GO:0004674 as duplicates?

**Comment by ValWood** [comment]
I agree with @deustp01  - it does not make sense biologically to split these term.

Kinases which can phosphorylate serine,  can always also phosphorylate threonine. That is the specificity of a serine/threonine protein kinase.

Nobody would use the terms "serine protein kinase" or "threonine protein kinase" in annotation. If a kinase phosphorylates sering (or threonine) it's a  "serine/threonine protein kinase"

**Comment by Nizal-Shammry** [comment]
My background is NOT biology, I am on ontology developer and I thought from an ontology's design view, to make each GO ID associated with one chemical reaction and add their annotations. For example, the GO:0050316 has two chemical reactions while in Rhea it is divided into two reactions RHEA:12698 and RHEA:13518.

**Comment by deustp01** [comment]
A one to one mapping of GO terms and Rhea reactions is indeed the plan, and this example, one GO nucleotide kinase activity term pointing to two Rhea reactions, one for phosphorylation of dGMP and one for phosphorylation of dTMP does not fit the plan.

Indeed, @ukemi, @hdrabkin , split the one GO activity term to make two?

Except that, looking at the [EC entry](https://enzyme.expasy.org/EC/2.7.4.12) cross-referenced to [GO:0050316](https://www.ebi.ac.uk/QuickGO/term/GO:0050316) the GO term may have been constructed to accommodate an enzymatic activity with broad substrate specificity. There could be a GO term and a Rhea reaction for each specific substrate combination, and an enzyme's broad activity (and variation in breadth of activity from one member of the enzyme family to the next) could be handled at the annotation level. is clean and rigorous, but will cause a combinatorial explosion in GO and Rhea that will be difficult to manage, I expect.

**Comment by ValWood** [comment]
I would really, really, really prefer that  we did not spit this for pragmatic  and biological reasons.

Consider pombe CDK1/cdc2
https://www.pombase.org/gene/SPBC11B10.09
over 200 targets on serine/threonine protein kinase.

We usually know when a kinase is a serine/threonine protein kinase.
For all of these targets   serines and threonines are phosphorylated (I can not spot one where this is not the case although I did not check thoroughly).

I would need to map all of these annotations to  both sering protein kinase and threonine protein kinase. This would increase the number of annotations for cdc2 from >250 to 500, but it would not benefit the users at all.
Multiply this by all the kinases, and it's a lot of extra work for no gain. if this was implemented I would move up to "protein kinase activity" and lose the  serine/threonine specificity. 

I really think this is a special case and we should leave it as is.

**Comment by srengel** [comment]
I, too, would really, really, really prefer that we did not spit this for biological reasons.

**Comment by alanbridge** [comment]
Hi, 

having separate Rhea reactions for P-Ser and P-Thr is useful for UniProt. This allows us to capture the phosphorylation of individual amino acids and ultimately link these to specific sequence features - we are mapping PTM annotations to ChEBI too.  

We don't need a separate GO term for Ser kinase and Thr kinase though, it would be fine to have 1 GO term for Ser/Thr kinases mapped to two Rhea reactions.

All the best, Alan

**Comment by deustp01** [comment]
A  possibly tangential issue here is the goal to have a 1:1 mapping of GO molecular function - catalyst activity terms and Rhea reactions. @ukemi

**Comment by pgaudet** [comment]
I think we should close this. One important principle in the development of GO is that it represents the biology, even if sometimes the logic is not completely rigid.
