### ISSUE TITLE
New CC term: actin wave

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#18461]
Actin waves have been described for a while but this year the mechanism became more clear. It was shown that these waves propagate by de novo nucleation of filaments. I'm asking for a cellular component term.
PMID:31230946
PMID:31390543 (this is a nice summary and comment on the previous)

I have a paper where myosin I proteins localize to the actin wave PMID:31774725

It has been also described outside Dicty actin waves implicated in axon extension. PMID:26190109, PMID:31678045

New term: actin wave
A possible Def: wave-like propagation of actin networks consisting of dynamic structures traveling on the ventral (substrate-attached) side of the cell during cell migration, cytokinesis, adhesion and neurogenesis.

Thanks!

**Comment by pfey03** [comment]
@ukemi when will this term be available? Thanks!

**Comment by ukemi** [comment]
It is in the ontology. It's probably waiting for the release to catch up.
