### ISSUE TITLE
typo in oboInOwl

### ISSUE THREAD

**Issue by goekce** [geneontology/go-ontology#18474]
the following files

[contrib/oboInOwl.obo](../blob/master/contrib/oboInOwl.obo)
[contrib/oboInOwl](../blob/master/contrib/oboInOwl)
[contrib/oboInOwl.owl](../blob/master/contrib/oboInOwl.owl)

have the following typos:

``synonymy``
``is related the primary class name,``

which should be:

``synonym``
``is related to the primary class name,``

**Comment by ukemi** [comment]
@cmungall, is this a GO issue?

**Comment by ukemi** [comment]
I think synonymy is correct. I believe it is the quality of being synonymous or having the same meaning.

**Comment by goekce** [comment]
@ukemi you are right, I didn't know about this word!

**Comment by goekce** [comment]
Sorry, forgot to close the issue.
