### ISSUE TITLE
Need clarification on some terms from the GO

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#18477]
Dear GO curators,

What is meant by the following substances:

- X-HPO3-  and XH from GO:0018720 

- X-SO3(-)  from GO:0018723 

Regards

**Comment by deustp01** [comment]
"X" in these cases means an unspecified group. Thus. GO:0018270 describes the reaction of phenol with another molecule that includes an - HPO3- group to form phenylphosphate plus the other molecule with only an H where the - HPO3- had been. "R" is more commonly used than "X" but this is a common convention.

**Comment by ukemi** [comment]
Thanks @deustp01
