### ISSUE TITLE
Better definitions for amino acid transmembrane transporter activity terms

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#18481]
GO:0015174 basic amino acid transmembrane transporter activity "Enables the transfer of basic amino acids from one side of a membrane to the other. _**Basic amino acids have a pH above 7**_."

GO:0015175 neutral amino acid transmembrane transporter activity "Enables the transfer of neutral amino acids from one side of a membrane to the other. **_Neutral amino acids have a pH of 7_**." 

GO:0015172 acidic amino acid transmembrane transporter activity "Enables the transfer of acidic amino acids from one side of a membrane to the other. **_Acidic amino acids have a pH below 7_**."

The highlighted last sentence in each definition is wrong. A better wording would be "Basic amino acids have side chains with a positive charge at pH 7.x", "Acidic ... negative", and "neutral ... no". Additional issue: for Rhea, physiological pH is 7.2, not 7.0, so would 7.2 be a better pH in the definition? @amorgat?

**Comment by ukemi** [comment]
If we are going to be consistent, I would vote for 7.3 (according to the ticket below). Maybe we should split the chemical conversion task out into its own ticket? The ticket below encompasses several issue that really are a project.
#14984

**Comment by deustp01** [comment]
@ukemi @amorgat Yes, my mistake, 7.3 is right per previous discussion.
