### ISSUE TITLE
"fatty acyl transporter activity" inexact synonym for GO:0015245

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#18486]
Here "fatty acyl transporter activity" is given as EXACT but it really is BROAD, or it should have "transmembrane" added.
```
id: GO:0015245
name: fatty acid transmembrane transporter activity
namespace: molecular_function
def: "Enables the transfer of fatty acids from one side of a membrane to the other. Fatty acids are aliphatic monocarboxylic acids liberated from naturally occurring fats and oils by hydrolysis." synonym: "fatty acid transporter activity" RELATED []
synonym: "fatty acyl transporter activity" EXACT []
```

**Comment by rwst** [comment]
As this presupposes the same as with #18485 it can be closed too.

**Comment by pgaudet** [comment]
OK sounds good. In this case there are also lipid transporters that are not transmembrane (but rather inter/intramembrane), but maybe not fatty acids. 

Thanks, Pascale
