### ISSUE TITLE
Is there a difference between GO:0043764 and GO:0103118 !!

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#18488]
Dear GO curators,

The Rhea cross-references for the two terms GO:0043764 and GO:0103118 are the same RHEA:17817. Does that mean they are the same?

**Comment by cmungall** [comment]
As far as I can tell, GO:0043764 is not cross-referenced to Rhea, nor has it ever been in the past. Where are you browsing/downloading the ontology? It is possible you are using some non-sanctioned version with problems.

**Comment by Nizal-Shammry** [comment]
GO:0043764 is cross-referenceed to BioCyc ID:UDPHYDROXYMYRGLUCOSAMNACETYLTRANS-RXN, which in turn link it to RHEA:17818

**Comment by hdrabkin** [comment]
Although only GO:0103118 is x-refed to RHEA:17817, I see both reference EC:2.3.1.191, which is XREF's by RHEA to RHEA:17817.
Both reference say Metacyc id
MetaCyc:UDPHYDROXYMYRGLUCOSAMNACETYLTRANS-RXN
(which xref to RHEA:17817 
I think these should be merged

The only difference is the GO NAME which specifies the "R" form in once case and does not in the other.  THE EC actually refers to the R substrates.
I think this should be a merge.

**Comment by hdrabkin** [comment]
I will merge GO:0043764  into GO:0103118

**Comment by hdrabkin** [comment]
done
