### ISSUE TITLE
"iron transporter activity" inexact synonym for GO:0005381

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#18485]
I think "iron transporter activity" as shown is not an EXACT synonym, rather it's BROAD. Alternatively "iron transmembrane transporter activity" would be EXACT. Reason: existence of transporters that are not transmembrane.
```
id: GO:0005381
name: iron ion transmembrane transporter activity
namespace: molecular_function
...
synonym: "iron cation channel activity" EXACT []
synonym: "iron channel activity" EXACT []
synonym: "iron transporter activity" EXACT []
``

**Comment by ValWood** [comment]
Hi Ralf,

I'm not sure about this., Do you have an  example? I only have  transmembrane transporters and 'carriers".

In   GO carriers are not classed as transporters because they are not "directed movement" (I think that is the rationale?)

https://www.ebi.ac.uk/QuickGO/term/GO:0140132

**Comment by pgaudet** [comment]
@ValWood 
> In GO carriers are not classed as transporters because they are not "directed movement" (I think that is the rationale?)

Something like that - carriers deliver molecules to proteins, but not to specific cellular locations. 

Pascale

**Comment by rwst** [comment]
Ah ok if carriers are not transporters then I'm barking at the wrong tree. I had in mind P02787 serum transferrin which is I see now annotated as chaperone...Thanks

**Comment by pgaudet** [comment]
Thanks for the feedback !
