### ISSUE TITLE
NTR: tRNA-uridine aminocarboxypropyltransferase activity, EC 2.5.1.25

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#18492]
EC 2.5.1.25 was an orphan activity, i.e. there was no gene product associated with it.  Last month, two papers were published that identified the enzymes in E. coli and human, PMIDs 31804502 and 31863583.  Because different uridine positions in tRNAs are modified by the human and bacterial enzymes, Ron Caspi has made some changes to the EC reaction to make it more generic.  (I don't know when it will change officially; you can see it in the preview version of MetaCyc here: http://brg-preview.ai.sri.com/META/NEW-IMAGE?type=REACTION&object=RXN-21179)

Proposed definition: Catalysis of the transfer of the 3-amino-3-carboxypropyl group of S-adenosylmethionine to the N3 position of a specific uridine in tRNAs.
Child of GO:0016765.
I don't know if it would be appropriate to generate a new BP term as well; there are a variety of more specific terms under "tRNA modification", but none that apply to this enzyme.

Happy New Year!
-Ingrid

**Comment by hdrabkin** [comment]
This EC is already used by 
Note that GO:0016432, tRNA-uridine aminocarboxypropyltransferase activity. Is this not the same term. 
Catalysis of the reaction: S-adenosyl-L-methionine + tRNA uridine = 5'-methylthioadenosine + tRNA 3-(3-amino-3-carboxypropyl)-uridine.

**Comment by keseler** [comment]
Ack!  How did I manage to miss this???  Yes, that's the correct term!

Thanks, and sorry for my confusion...

-Ingrid

P.S. I used to be able to search AmiGO with an EC number, but that hasn't worked in a while.  Any idea why?

**Comment by hdrabkin** [comment]
Ok I'll close this;
Never tried to search for EC in Amigo; I know I can't in the MGI browser, so I resort to protege.
