### ISSUE TITLE
ingter and intra membrane transfer

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18490]
I think these might be the wrong way around:

<img width="479" alt="Screenshot 2020-01-06 at 16 54 01" src="https://user-images.githubusercontent.com/7359272/71833604-311de000-30a5-11ea-940c-14451004af17.png">

**Comment by ValWood** [comment]
so 
intramembrane lipid transporter is
Enables the transport of a lipid from a region of a membrane to a different region on the same membrane.

this implies that the other branch (transfer activity) is intermembrane?

it is defined
Removes a sterol from a membrane or a monolayer lipid particle, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to an acceptor membrane or lipid particle. PMID:20823909 PMID:24220498 PMID:25797198



I ask for confirmation becasue I  an annotating  OSH gene orthologs.

If this is correct, can we add "intermembrane transport/ transfer as synonyms"

**Comment by ValWood** [comment]
Its probably obvius so I closed. It took me a while to figure it out but I had some internal confounding annotations)

**Comment by pgaudet** [comment]
OK. Let me know if we can clarify somehow.
