### ISSUE TITLE
Can we remove unused TypeDefs from the ontology

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18509]
Hello, 

We have those relations in the ontology, that are not used anywhere: 

[Typedef]
id: during_which_ends
name: during which ends
namespace: external
xref: RO:0002084

[Typedef]
id: during_which_starts
name: during which starts
namespace: external
xref: RO:0002088

Can we delete them - to make sure we don't use them ? What is the process, is this simply manual? 

Thanks, Pascale

**Comment by balhoff** [comment]
You can just delete them.

**Comment by pgaudet** [comment]
Great !

**Comment by pgaudet** [comment]
@balhoff can I also remove 
in_taxon
never_in_taxon ?

**Comment by balhoff** [comment]
I think you can, given that these are only used in the external taxon constraint files now.
