### ISSUE TITLE
The relation 'directly negatively regulates' should not be in BP

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18510]
We have one instance of 'directly negatively regulates' in BP: 

'miRNA mediated inhibition of translation' = biological_process and (mediated_by some miRNA) and ('directly negatively regulates' some translation)

I will change this to 'negatively regulates' some translation.

**Comment by pgaudet** [comment]
@balhoff Is there a way to disallow some relations specifically for some GO aspect in the Travis checks?

**Comment by balhoff** [comment]
Yes I think so. For this, a BP should never be the subject of the relation?

**Comment by pgaudet** [comment]
Neither a BP nor a CC (to be comprehensive). Should I open a new ticket?

**Comment by balhoff** [comment]
Yes please.
