### ISSUE TITLE
microRNA mediated regulation of transcription

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#18512]
Hi 

It has been shown that microRNAs can regulate transcription by 'binding' to the promoter regions (see information below). Please could you create the following GO terms:

GO:0045944 ‘positive regulation of transcription by RNA polymerase II’
>is_a child new term 
‘miRNA-mediated activation of transcription by RNA polymerase II’

And also the create appropriately placed new terms:
‘miRNA-mediated regulation of transcription by RNA polymerase II’
‘miRNA-mediated inhibition of transcription by RNA polymerase II’

Also please revise the definition of 
GO:0001228 ‘DNA-binding transcription activator activity, RNA polymerase II-specific’ to include microRNAs.

Finally please add new GO term:
GO:0043973 histone H3-K4 acetylation
positive regulation child NEW TERM 'positive regulation of histone H3-K4 acetylation'
GO:0035066 positive regulation of histone acetylation
is_a_child NEW TERM 'positive regulation of histone H3-K4 acetylation'

**Justification**

PMID: 20737563 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3940365/

Figure 4: miR-205 is predicted to bind IL24 and IL32 promoters and thus stimulate their expression. Figure 5: These findings (especially the nuclear run-on assay in Figure 5D) validate the inferences made from Figure 4. E.g. The qRT-PCR in Figure 5B shows that mutated miRs have no effects on the expression of interleukins (similarly to the controls); the luciferase assay in Figure 5C shows that miR-205 increases the expression of IL24, which together with the predicted binding shown in Figure 4A supports the annotation ‘miRNA-mediated activation of transcription by RNA polymerase II’, whereas the nuclear run-on assay, which measures the relative abundance of newly formed transcripts of IL24 and IL32 provides a definitive validation of the role of miR-205 in ‘miRNA-mediated activation of transcription by RNA polymerase II’.

We would capture this using the New GO term:
‘miRNA-mediated activation of transcription by RNA polymerase II’

Figure 4 and 5 also collectively provide evidence to assign the function of a transcription activator to miR-205:

GO:0001228 ‘DNA-binding transcription activator activity, RNA polymerase II-specific’
However, the definition of this term only applies to proteins and complexes, so either a change to the definition is required.

Figure 6: supports an annotation along the lines of:
miR-205 involved_in GO:0035066 ‘positive regulation of histone acetylation’ part_of ‘miRNA-mediated activation of transcription by RNA polymerase II’

Potentially a more specific new term could be requested positive regulation of histone H3-K4 acetylation.
 
PMID: 27145859
Figure 2: supports a similar annotation for the miR.

**Comment by pgaudet** [comment]
Is @BarbaraCzub doing this one ?

**Comment by BarbaraCzub** [comment]
I'm happy to add the suggested new terms and broaden the definition of GO:0001228 ‘DNA-binding transcription activator activity, RNA polymerase II-specific’ to include non-coding RNAs. @pgaudet I hope this GO:0001228 revision will be in agreement with the other ongoing transcription revisions?

**Comment by pgaudet** [comment]
Yes I think so (although we didn't look at BP very closely yet)

**Comment by BarbaraCzub** [comment]
Ok, I'll expand the definition of GO:0001228 ‘DNA-binding transcription activator activity, RNA polymerase II-specific’ to include ncRNAs then. And I'll add the new BP terms for now (they can always be merged into the parents at a later date, if necessary).

**Comment by pgaudet** [comment]
Transcription call- obsolete these terms, there is no string evidence that miRNAs regulate gene expression at promoters, all papers we find have indirect evidence.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: 
* GO:0150164 miRNA-mediated regulation of transcription by RNA polymerase II
* GO:0150163 miRNA-mediated activation of transcription by RNA polymerase II
* GO:0150165 miRNA-mediated inhibition of transcription by RNA polymerase II 

The reason for obsoletion is that there is no evidence that these processes exist, ie miRNAs do not directly regulate transcription. 

There are no annotations or mappings to these terms, these terms are not present in any subsets.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/18512


Thanks, Pascale
