### ISSUE TITLE
Is there a difference between GO:0033799 and GO:0102437 ??

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#18527]
Dear GO curators,

Definition (GO:0033799 GONUTS page)
Catalysis of the reaction: S-adenosyl-L-methionine + myricetin = S-adenosyl-L-homocysteine + laricitrin. 

Definition (GO:0102437 GONUTS page)
Catalysis of the reaction: myricetin(1-) + S-adenosyl-L-methionine <=> 3-O-methylmyricetin + S-adenosyl-L-homocysteine 

Notes that In Chebi ontology: 3'-O-Methylmyricetin is a synonym for laricitrin CHEBI:31763

**Comment by Nizal-Shammry** [comment]
Also, the GO:0033799 is x-refed to RHEA:24280 which I think is incorrect. It should be cross-referenced to RHEA:25632, however, GO:0033799 is cross-referenced to KEGG_REACTION R06815 which is xref to RHEA:25632

**Comment by hdrabkin** [comment]
EC:2.1.1.149 mapping to GO:003799 does not map to RHEA:25632
In fact, this ec has been transferred to EC:2.1.1.267; This has 4 RHEAs associated with it, differing in the substrates> 

RHEA:25629 | myricetin + S-adenosyl-L-methionine = H(+) + laricitrin + S-adenosyl-L-homocysteine 					   		Cross reference: EC 2.1.1.267 | 

RHEA:25633 | laricitrin + S-adenosyl-L-methionine = H(+) + S-adenosyl-L-homocysteine + syringetin 					   		Cross reference: EC 2.1.1.267 | 

RHEA:55332 | a 3'-hydroxyflavone + S-adenosyl-L-methionine = a 3'-methoxyflavone + H(+) + S-adenosyl-L-homocysteine 		Cross reference: EC 2.1.1.267 
 					   			
RHEA:55336 | a 5'-hydroxy-3'-methoxyflavone + S-adenosyl-L-methionine = a 3',5'-dimethoxyflavone + H(+) + S-adenosyl-L-homocysteine 					   		Cross reference: EC 2.1.1.267

THE EC number has two reactions grouped under it 
    S-adenosyl-L-methionine + a 3'-hydroxyflavonoid <=> S-adenosyl-L-homocysteine + a 3'-methoxyflavonoid
and 
    S-adenosyl-L-methionine + a 5'-hydroxy-3'-methoxyflavonoid <=> S-adenosyl-L-homocysteine + a 3',5'-dimethoxyflavonoid

Based on this, this looks like a merge
THEN
1. change EC 
2. Use  RHEA:25629 for this reaction.

**Comment by hdrabkin** [comment]
GO:0033799 is winning term (older and has 3'-O vs 3-O in term title.
Merge done
