### ISSUE TITLE
Fix db-xrefs.yaml for IMG

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#18530]
E.g. http://amigo.geneontology.org/amigo/term/GO:0043770

Goes through a round of redirects and ends up on a login page. What should we do here @monicacecilia?

**Comment by pgaudet** [comment]
GO:0043811  phosphate:acyl-[acyl carrier protein] acyltransferase activity
remove IMG:01871
add 
+xref: EC:2.3.1.274
+xref: RHEA:42292

----

GO:0043851  methanol-specific methylcobalamin:coenzyme M methyltransferase activity - 0 annotations
IMG:01315, MetaCyc:RXN-8096

-> corresponds to EC:2.1.1.246/ RHEA:45208

- [x] merge into GO:1990088 [methyl-Co(III) methanol-specific corrinoid protein]:coenzyme M methyltransferase activity (0 annotations)
- [x] change label to methylcobamide:CoM methyltransferase activity to match UniProt Q48927
