### ISSUE TITLE
TPV for GO:1904091   peptidyl carrier protein activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18536]
GO:1904091    peptidyl carrier protein activity

Binding an amino-acid derived peptidyl group and presenting it for processing or offloading to a cognate enzyme. Covalently binds the peptidyl group via a phosphopantetheine prosthetic group and mediates protein-protein interactions with the enzyme conferring specificity. Peptidyl carrier protein (PCP) is involved in nonribosomal peptide biosynthetic process. PMID:17502372

maps to lipid metabolic prcoess becasue it is a decendant of "acyl carrier activity"
Should be siblings?

**Comment by pgaudet** [comment]
Hi @ValWood 

Thanks for reporting this. I discussed with @pedruzzi and he suggested creating a new grouping term: 

+[Term]
+id: GO:0140414
+name: phosphopantetheine-dependent carrier activity
+namespace: molecular_function
+def: "Binding a substrate via a thioester at the terminal thiol of a covalentely linked phosphopantetheine prosthetic group and mediating protein-protein interactions with cognate enzymes for processing or offloading of the thiol-bound substrate." [PMID:17502372]
+synonym: "carrier protein activity" EXACT []
+is_a: GO:0140104 ! molecular carrier activity
+created_by: pg
+creation_date: 2020-01-14T16:15:04Z

And I am moving all 3 terms under this new one. 

Thanks, Pascale

**Comment by ValWood** [comment]
Great I was going to suggest a grouping term, but trying tho think what to call it!
