### ISSUE TITLE
effector response to tumor necrosis factor

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#18535]
Hi

I have raised this issue on several occassions, and I appreciate that with GO-CAM perhaps this is covered. However, I think the current 'response to' ontology does not describe the processes that occur after the initial signaling event. Many  'response to.... ligand x' GO terms have only 1 child term, the ligand signaling pathway. But the point of the signaling pathway is to change the processes occuring in the cell and initiate the actual response. I realise that many responses to a stimulus lead to similar downstream effect, eg release of cytokines, or migration or proliferation etc. Wouldn't it be useful to group, for example, all the cytokines that are released following TNF-alpha stimulus separately from those growth factors that are released following BMP4 signaling?  Or do people think that grouping the signaling molecules and these 'effectors' all under the 'cellular response to.....' is all that is needed?

GO:0071356 cellular response to tumor necrosis factor
is_a child New Term effector response to tumor necrosis factor

Definition: Any dowstream processes that starts as a result of the tumor necrosis factor signaling pathway and contributes to the cellular changes that result from stimulation by tumor necrosis factor.

For example, in PMID:22499991 stimulation by TNFalpha leads to an increase in the transcription of miR-200b which reduces the expression of a transcription factor GATA2 and a signaling receptor (VEGFR2). I would like to annotate miR-200b as an effector of the cellular response to TNF rather than just to the GO term cellular response to TNF. Obviously GATA2 and VEGFR2 would not be associated with the the cellular response to TNF term. I guess currently I do capture the role of the miR and TNF-alpha using acts upstream of (New term to be requested) negative regulation of angiogenesis involved in wound healing AE part_of response to TNF.

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 

What do you mean by "effector" here ? Is it the same as in #18041 ? 

Thanks, Pascale

**Comment by ValWood** [comment]
It isn't the same as a "pathogen effector" which is a secreted pathogen molecule.

Possibly
GO:0002252    immune effector process ?

**Comment by pgaudet** [comment]
@RLovering I am not sure what you are trying to describe. 

Presumably the downstream responses to TNF are not a single process, but multiple processes. In GO-CAM you would say that TNF signaling is 'causally upstream' of the various pathways. I would prefer not to create the term you suggest, it seems to be a different way in addition to GO-CAM to connect pathways. 

What do you think ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Good point, I will close this
