### ISSUE TITLE
cobalamin ~metabolic~ biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18534]
~MMADHC	Methylmalonic aciduria and homocystinuria type D protein, mitochondrial		cobalamin metabolic process		UniProt	Homo sapiens	IDA		my011 protein pthr13192	protein		PMID:24722857	20160629~

UniProtKB:Q9H3L0 | MMADHC | involved_in | GO:0009108    coenzyme biosynthetic process | ECO:0000315   IMP | PMID:24722857 |   | 9606 Homo sapiens | UniProt

should this have a taxon restriction for eukaryotes?

**Comment by pgaudet** [comment]
Metabolic process is a parent of biosynthetic process - and Vit B is produced by bacteria https://en.wikipedia.org/wiki/Vitamin_B12#Bacteria_and_archaea

**Comment by pgaudet** [comment]
Yes -  GO:0009236 
cobalamin biosynthetic process  -> never in eukaryotes

**Comment by ukemi** [comment]
Wouldn't it be stronger to say only in prokaryotes?

**Comment by pgaudet** [comment]
Sure, yes.

**Comment by hdrabkin** [comment]
done
