### ISSUE TITLE
3'-dRP lyase activity

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18543]
I think I need a new GO MF term for an activity of Tdp1 (S. pombe and some orthologs). If one exists already I haven't found it. I've also become a bit confused reading up on it, so it would probably be a good idea to get input from someone at RHEA.

Anyway, for Tdp1 I need a term for 3'-deoxyribose phosphate lyase (synonym: 3'-dRP lyase). I'm curating PMID:22084197, and various passages in this paper suggest that "δ-elimination" and "δ-cleavage" refer to the same reaction. IT acts on a substrate produced by some types of AP endonuclease in the context of DNA repair.

The definition should include something like "Catalysis of the conversion of a 3'-deoxyribose phosphate in DNA to a 3'-phosphate." (Figure 5 says this differs from the 3'-diesterase activity of Apn1/Apn2, which produces 3'-OH.)

It also be worth looking at PMID:21276450.

It's proving easier to find papers on *5'*-dRP lyase (e.g. PMID:9556598, PMID:9614142, PMID:26826709, PubMed hits for "drp lyase activity" generally), and I don't think there's a GO MF term for that either.

name: 5'-deoxyribose phosphate lyase
synonym: 5'-dRP lyase

name: 3'-deoxyribose phosphate lyase
synonym: 3'-dRP lyase

Both should have paths to GO:0140097 ! catalytic activity, acting on DNA and something in the EC/mechanism-based branch of MF. I'm guessing somewhere under GO:0016829 'lyase activity' but I'm having trouble figuring out which bond is cleaved, hence the call for more informed input.

**Comment by mah11** [comment]
p.s. I think the 3'-dRP lyase substrate is generated by GO:0140078 ! class I DNA-(apurinic or apyrimidinic site) endonuclease activity

**Comment by hdrabkin** [comment]
Any RHEA and/or EC?

**Comment by mah11** [comment]
> Any RHEA and/or EC?

That is *exactly* the sort of stuff I tried to figure out over the couple days before I opened the ticket, but I have not succeeded. That's why I included the call for assistance.

**Comment by hdrabkin** [comment]
I found this on Brenda poking around with the 5'-dRP lyase
https://www.brenda-enzymes.org/enzyme.php?ecno=4.2.99.B1
'catalysis of the beta-elimination of the 5' deoxyribose-5-phosphate at an abasic site in DNA where a DNA-(apurinic or apyrimidinic site) lyase has already cleaved the C-O-P bond 3' to the apurinic or apyrimidinic site "

**Comment by mah11** [comment]
Yep, that looks like some of the other things I saw - it seemed easier to find info on the 5'-dRP lyase than the 3' version, and my nucleo*ide chemistry is rusty enough that I haven't sussed out how much 5' vs. 3' may differ ...

**Comment by hdrabkin** [comment]
So from what I understand now, you just need the one term?
MID:9556598, PMID:9614142, PMID:26826709, PubMed hits for "drp lyase activity" generally), and I don't think there's a GO MF term for that either.
name: 5'-deoxyribose phosphate lyase
synonym: 5'-dRP lyase

**Comment by hdrabkin** [comment]
I think based on Brenda,  EC:4.2.99 would be a good parent. 
https://www.brenda-enzymes.org/enzyme.php?ecno=4.2.99.B1&UniProtAcc=Q9UGP5
GO does not have a grouping term mapping to it, only to 4.2
             4.2.99 Other carbon-oxygen lyases
GO obsoleted term mapping to this EC
'Enzymes with this activity are 'miscellaneous' carbon-oxygen lyases that cannot be grouped into one of the specific subclasses of the carbon-oxygen lyases."
So 4.2 may be as good as we can do (4.2 Carbon-oxygen lyases).

**Comment by mah11** [comment]
I need the 3' version:

> name: 3'-deoxyribose phosphate lyase
> synonym: 3'-dRP lyase

I don't need the 5'-yada term now, but you're welcome to add it too. ;)

Out of necessity, but also experience, I trust you on the parentage.

**Comment by mah11** [comment]
at @pgaudet's invitation in the GO meeting, pinging my open tickets

**Comment by hdrabkin** [comment]
I have looked at this ticket multiple times, but still having many problems with this one @mah11 
Maybe I'm having a brain freeze, but I cannot figure out the structures of the substrate (3'-deoxyribose phostphate) or the products (3-'phosphate? and ....  
at least I can find a structure  for 5'-drp
https://metacyc.org/compound?orgid=META&id=5-Phospho-terminated-DNAs#
(NOT in CHEBI)
Without proper CHEBI ids I can't request a RHEA term for either.

**Comment by mah11** [comment]
I think I may have found it! (I tried to find reaction and structure details back when I opened the ticket, but no joy until maybe now.) It's the middle one in Figure 3E in this review:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4090310/

It's even got an arrow pointing to the cleavage site. I hope this is enough to go on ...

**Comment by hdrabkin** [comment]
So looking at figure 3E, the 3'-dRP is converted to a glycolate?  Fig. 3E is not really described fully even in text.
But 3'-dRP structure is not what I thought it would be;  Or I'm not reading the figure correctly (and of course

**Comment by mah11** [comment]
Oof. This has done my head in too. I just pummeled it again, and found a reaction diagram in PMID:24335147, Supplemental Figure 4C. Maybe I could've identified the compounds/residues/structures back when undergrad organic chemistry was fresh in my head, but now? not so much. I hope it helps, though!

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3339927/

**Comment by hdrabkin** [comment]
I'm adding that PMID to the term; and going with your def, now that I see the fig 4C, and also try to request a RHEA

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106334
+name: 3'-deoxyribose phosphate lyase activity

**Comment by hdrabkin** [comment]
Awaiting RHEA reaction Rhea help ticket 196127. I have asked them to look at sup. figure 4c to figure out how to call these.

**Comment by mah11** [comment]
hooray!

**Comment by pgaudet** [comment]
@hdrabkin has Rhea completed this ?

**Comment by hdrabkin** [comment]
Hi Harold,

The reactions depicted in Fig S4 are catalysed by two different enzymes. The
first part catalysed by Endo III is described in EC 4.2.99.18 by a text
reaction that we cannot describe in Rhea. For the second part catalysed by Tdp1
I have created a reaction in Rhea. In addition, I have created two other
reactions catalysed by Tdp1 which are also characterised in pmid:22375014.

The reaction from Fig. S4
RHEA:65764 (DNA)-3'-(deoxyribonucleoside 5'-phosphate)-(deoxyribose
5'-phosphate) + H2O = (2E,4S)-4,5-dihydroxypent-2-enal +
(DNA)-3'-(deoxyribonucleoside 3',5'-bisphosphate) + H+
The two additional reactions.
RHEA:65800 (DNA)-3'-(deoxyribonucleoside 5'-phosphate)-(L-tyrosyl phosphate) +
H2O = (DNA)-3'-(deoxyribonucleoside 3',5'-bisphosphate) + H+ + L-tyrosine
RHEA:65804 5'-L-tyrosylphosphate 2'-deoxynucleoside-(DNA) + H2O = H+ +
L-tyrosine + phospho-5'-(DNA)

These RHEAs for the 3'-dRP lyase are not pubic yet (ticket done   by RHEA 10/30/20; so might be in feb release

**Comment by hdrabkin** [comment]
3/5/2021
RHEA:65804 not public yet 
RHEA:65764 not poblic yet.

**Comment by hdrabkin** [comment]
4/23
Neither RHEA public yet

**Comment by pgaudet** [comment]
@amorgat It seems odd that those Rheas are not yet available?

**Comment by amorgat** [comment]
I'm really confused and apologize for that. 
The reactions requested by @hdrabkin a few months ago were created by @kaxelsen  but never approved, hence no chance to be publicly available.
I've approved them this morning, meaning that they will be publicly available on release 120 (July 28th).
We need more Rhea biocurators ;-)

RHEA:65764
(DNA)-3'-(deoxyribonucleoside 5'-phosphate)-(2,3-dehydro-2,3-deoxyribose 5'-phosphate) + H2O = (2E,4S)-4,5-dihydroxypent-2-enal + (DNA)-3'-(deoxyribonucleoside 3',5'-bisphosphate) + H+
RHEA:65800
(DNA)-3'-(deoxyribonucleoside 5'-phosphate)-(L-tyrosyl phosphate) + H2O = (DNA)-3'-(deoxyribonucleoside 3',5'-bisphosphate) + H+ + L-tyrosine
RHEA:65804
5'-L-tyrosylphosphate 2'-deoxynucleoside-(DNA) + H2O = H+ + L-tyrosine + phospho-5'-(DNA)

**Comment by kaxelsen** [comment]
> The reactions depicted in Fig S4 are catalysed by two different enzymes. The
> first part catalysed by Endo III is described in EC 4.2.99.18 by a text 
> reaction that we cannot describe in Rhea.

Note that we eventually also figured out how to create this reaction in Rhea.
It is now RHEA:66592
(DNA)-(deoxyribonucleoside 5'-phosphate)-(deoxyribose 5'-phosphate)-(deoxyribonucleoside 5'-phosphate) = (DNA)-3'-(deoxyribonucleoside 5'-phosphate)-(2,3-dehydro-2,3-deoxyribose 5'-phosphate) + H+ + phospho-5'-(DNA) 
that is publicly available.

**Comment by hdrabkin** [comment]
These are still not public 8/12/2021
The reactions requested by @hdrabkin a few months ago were created by @kaxelsen but never approved, hence no chance to be publicly available.
I've approved them this morning, meaning that they will be publicly available on release 120 (July 28th).

**Comment by kaxelsen** [comment]
Note that Rhea-db.org is still at release 119. Release 120 (corresponding to UniProt release 2021_04) was postponed to September 29.

**Comment by hdrabkin** [comment]
These RHEAs are now all in. RHEA:65764 added to NTR
