### ISSUE TITLE
Obsolete 'actin filament polymerization involved in x' terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18554]
Dear all, 

The proposal have been made to obsolete the following 'actin filament polymerization involved in x' terms. The reason for obsoletion is that the information should be captured as a GO-CAM. 

GOID | Term label | Number of annotations | Group
-- | -- | -- | --
GO:1903478 | actin filament bundle convergence involved in mitotic contractile ring   assembly | 4 | PomBase
GO:1904670 | actin filament polymerization involved in mitotic actomyosin contractile   ring assembly | 4 | PomBase
GO:0030037 | actin filament reorganization involved in cell cycle | 7 | 1 SGD + 6 FlyBase
GO:0070359 | actin polymerization-dependent cell motility involved in migration of   symbiont in host | 1 | UniProt-EBI
GO:1903481 | negative regulation of actin filament organization involved in mitotic   actomyosin contractile ring assembly | 0 |  
GO:0120172 | positive regulation of actin filament bundle convergence involved in   mitotic contractile ring assembly | 2 | PomBase
GO:0061955 | positive regulation of actin filament depolymerization involved in   acrosome reaction | 0 |  
GO:1903482 | positive regulation of actin filament organization involved in mitotic   actomyosin contractile ring assembly | 2 | PomBase
GO:0060475 | positive regulation of actin filament polymerization involved in acrosome   reaction | 0 |  
GO:0061954 | positive regulation of actin filament polymerization involved in sperm   capacitation | 0 |  
GO:0120173 | regulation of actin filament bundle convergence involved in mitotic   contractile ring assembly | 0 |  
GO:1903117 | regulation of actin filament organization involved in cytokinetic   actomyosin contractile ring assembly | 0 |  
GO:1903480 | regulation of actin filament organization involved in mitotic actomyosin   contractile ring assembly | 2 | PomBase

 - [x] To check: 
* Mappings: GO:0030037is mapped to MIPS_funcat (deprecated)
* Slims: None 

Thanks, Pascale

**Comment by ValWood** [comment]
can we keep this one and change to

GO:1903478 | actin filament bundle convergence involved in mitotic contractile ring   assembly


GO:1903478 |  mitotic contractile ring actin filament bundle convergence
this is a sub process in ring assembly

**Comment by ValWood** [comment]
It seems that the obsoletion notice went out but this wasn't completed

**Comment by ValWood** [comment]
I'd like to keep GO:1903478 for now , relabelled, but it might be possible to eventually get rid of it and replace by MF terms

**Comment by raymond91125** [comment]
GOID | Number of annotations | Status
-- | -- | -- 
GO:1903478  | 0 EXP
GO:1904670  | 0 EXP
GO:0030037  | 7 EXP | https://github.com/geneontology/go-annotation/issues/4409
GO:0070359  | 0 | OBSOLETED
GO:1903481  | 0 
GO:0120172  | 0
GO:0061955  | 0
GO:1903482  | 0
GO:1903482  | 0
GO:0060475  | 0
GO:0061954  | 0
GO:0120173  | 0
GO:1903117  | 0
GO:1903480  | 0

**Comment by pgaudet** [comment]
> probably
regulation of actin filament polymerization
should go too.
This can be described by activities.

his should be a separate ticket - there are a bout 200 EXP annotations to these regulation terms, plus several children.
