### ISSUE TITLE
obsoletion: GO:0052462 modulation by host of symbiont phagocytosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18559]
GO:0052462  modulation by host of symbiont phagocytosis
Any process in which an organism modulates the frequency, rate or extent of phagocytosis, the engulfing by phagocytes of external particulate material, in the symbiont organism. The symbiont is defined as the smaller of the organisms involved in a symbiotic interaction.

(and regulation children) 
no reference
no annotations
no evidence that the host modulates symbiont endocytosis

**Comment by ValWood** [comment]
Actually isn't this just "phagocytosis"?

**Comment by ValWood** [comment]
actually this term is nonsense.

" the engulfing by phagocytes of external particulate material, in the symbiont organism"
the symbiont does not have 'phagocytes"

The term is ambiguous but it is describing the process of phagocytosis by a symbiont, not phagocytosis OF a symbiont

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete "GO:0052462 modulation by host of symbiont phagocytosis". The reason for obsoletion is that there is no evidence that this process exists. 

There are no annotations and no mappings to this term. This term is not present in any subsets. 

Any comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/18559.

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 4th, 2020. Unless objections are received by February 4th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by genegodbold** [comment]
This is either really trivial and happens all the time, or it is really, really rare. I have been documenting interference with phagocytosis in pathogens. I've got 42 examples from bacteria and 3 from unicellular eukaryotes and the pattern is the parasite messes with the host proteins to affect phagocytosis. (Similarly I've got over 80 examples of complement subversion.) The host is *already* doing something--gobbling the beastie via phagocytosis (or killing it via membrane attack complex activation). "Modulating phagocytosis" is kind of beside the point for the immune system.

**Comment by pgaudet** [comment]
Thanks @genegodbold for the feedback

**Comment by ValWood** [comment]
Hi @genegodbold 

Isn't this
GO:0052067    JSON
antiphagocytosis
Biological Process

Definition (GO:0052067 GONUTS page)
Any process in which a symbiont avoids phagocytosis by a host cell, for example a phagocyte or a macrophage. The host is defined as the larger of the organisms involved in a symbiotic interaction. PMID:29114249

?

the term we are obsoleting refers to the host interfering **with parasite** phagocytosis. We have no  known examples of that.

Do you know of any?

Val

**Comment by pgaudet** [comment]
I understood he said he found no cases
> the parasite messes with the host proteins to subvert phagocytosis. 

(and not the other way around)

**Comment by ValWood** [comment]
OK,  Got it !

**Comment by genegodbold** [comment]
Yeah, sorry folks--that wasn't the clearest post. My understanding is that you are *correct* that the term should be obsolete. There are plenty of cases where the parasite messes with the host phagocytic process but that's NOT what this term is indicating. 

I was reading it as the host modulates the symbiont messing with host phagocytosis--which seems theoretically possible but kind of beside the point. 

" the engulfing by phagocytes of external particulate material, in the symbiont organism" If the actor here is the symbiont, then Val is right that this is ridiculous--there ain't no phagocytes in a symbiont.

**Comment by ValWood** [comment]
Hi @genegodbold  It was me who understood.
Out of interest, are you curating the anti-phagocytosis examples you are documenting into any resource? That sounds like a really interesting collection of data ;)

**Comment by genegodbold** [comment]
We're hoping to publish something on it later this year.

**Comment by ValWood** [comment]
Excellent!
