### ISSUE TITLE
Merge: GO:0020021    immortalization of host cell into GO:0019088 immortalization of host cell by virus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18569]
GO:0020021    immortalization of host cell (this isn't a normal process  for metazoa)
2 EXP annotations to challenge

keep
GO:0019088    immortalization of host cell by virus

**Comment by ukemi** [comment]
@pgaudet, should we just turn all this work into a project?

**Comment by ukemi** [comment]
OK. I felt bad because it seemed that I am assigning you a large number of tickets. But if it part of a project in which you are in charge, then that is ok. In my opinion, these types of project tickets are not part of the 'normal' rota.

**Comment by pgaudet** [comment]
Hi @ValWood 

Why don't I merge into the child GO:0019088 immortalization of host cell by virus?

**Comment by pgaudet** [comment]
Mouse and rat annotations still need to be reviewed: (probably just need to be removed): 

https://docs.google.com/spreadsheets/d/1-rDUh3A_Mitj2Xofi1wY7UPjho0BTy-I1vEN4_QzBB4/edit#gid=0

@gthayman 1 rat annotation
@hdrabkin 1 mouse annotation
I've deleted the AgBase annotation. 

Thanks, Pascale

**Comment by pgaudet** [comment]
> I this term is required it needs taxon restrictions if it is meant to be a viral term?

I agree. Although I think how people mean to use that is how a host protein is somehow involved in that process. But that wouldn't be a normal process anyway. 

I'll add taxon restrictions to both terms.

**Comment by pgaudet** [comment]
Another oddity is  GO:0020021 immortalization of host cell
has exact synonyms 

transformation of host cell | exact
host cell transformation | exact

(TBH I thought that this was the case ?) How 'transformation' is currently defined is "Any virus-induced change in the morphological, biochemical, or growth parameters of a cell" - which sounds just like "GO:0019048 modulation by virus of host morphology or physiology" (which I renamed "modulation by virus of host process in #18605)

**Comment by gthayman** [comment]
RGD done.

**Comment by hdrabkin** [comment]
MGI done

**Comment by pgaudet** [comment]
Discussion with @ValWood 
- [ ] We will do a 3-way merge 
 GO:0020021 immortalization of host cell
GO:0019088 immortalization of host cell by virus
into  
GO:0019087 transformation of host cell by virus

- [ ]  and add a taxon constraint on GO:0019087 transformation of host cell by virus
only in Viruses

Thanks, Pascale

**Comment by pgaudet** [comment]
References: 
PMID: 11119620
PMID: 18366075

**Comment by pgaudet** [comment]
I'll edit the defintion to be a bit more explicit : 
A process that results in change in growth, or indefinite reproduction of cells caused by the introduction of viral inheritable material.
