### ISSUE TITLE
Obsolete GO:0001134 transcription regulator recruiting activity and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18561]
Dear all, 

The proposal has been made to obsolete GO:0001134 transcription regulator recruiting activity and their children. 

The reason for obsoletion is that the function of all proteins annotated to those terms should already be captured by other transcriptional regulator activities - most often 'co-regulator activity' 

The function captured by the 'recruiting' terms represent "protein binding, bridging", but more relevant terms are suggested below. 

* GO:0001186 RNA polymerase I transcription regulator recruiting activity 
-> consider GO:0001188 RNA polymerase I preinitiation complex assembly
*  GO:0001135 RNA polymerase II transcription regulator recruiting activity
-> consider GO:0003713 transcription coactivator activity
-> consider GO:0016251 RNA polymerase II general transcription initiation factor activity
-> consider GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific
* GO:0001004 RNA polymerase III transcription regulator recruiting activity  
-> consider GO:0070898 RNA polymerase III preinitiation complex assembly

There are 42 manual annotations to those terms. Annotation review ticket is here: https://github.com/geneontology/go-annotation/issues/2774

Impacted groups: 

Contributor   (Assigned by) | Number of annotations
--|--
CAFA | 2
dictyBase | 2
MGI | 1
PomBase | 1
SGD | 37
UniProt | 1

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsoletion email notice sent.

**Comment by suzialeksander** [comment]
sgd done.
