### ISSUE TITLE
Obsoletion notice: phagocytosis modulation by symbiont terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18562]
Very strange.
The corresponding positive and negative regulation terms are in different parts of the ontology.

<img width="779" alt="phagocytosis" src="https://user-images.githubusercontent.com/7359272/72616541-1c580c80-392f-11ea-8553-d2650b04a4ce.png">

**Comment by ValWood** [comment]
Actually the terms are worded slightly differently but they have the same meaning.

GO:0052067 negative regulation by symbiont of entry into host cell via phagocytosis
GO:0052191 positive regulation by symbiont of host phagocytosis
GO:0052190 modulation by symbiont of host phagocytosis

I don't think
GO:0052191 positive regulation by symbiont of host phagocytosis 
happens? the host wants to avoid being phagocytized ?

It has one annotation NAS to a human gene product but this is a symbiont term?

**Comment by ValWood** [comment]
GO:0052067 negative regulation by symbiont of entry into host cell via phagocytosis

This one is OK, it has annotation about preventing host phagocytocic.
The term name should be changed so that  it is some sort of "avoidance of phagocytosis by symbiont". IT isn't a type of "entry into host" which is defined  in the context of "host infection"

**Comment by ValWood** [comment]
'GO_0052231 modulation of phagocytosis in other organism involved in symbiotic interaction'
'GO_0052522 positive regulation by organism of phagocytosis in other organism involved in symbiotic interaction'
'GO_0052379 modulation by organism of entry into other organism via phagocytosis involved in symbiotic interaction'
'GO_0052483 negative regulation by organism of entry into cell of other organism via phagocytosis involved in symbiotic interaction'
'GO:0052066 entry of symbiont into host cell by promotion of host phagocytosis'

**Comment by ValWood** [comment]
Also these do not make ANY sense

GO:0052191 positive regulation by symbiont of host phagocytosis
GO:0052190 modulation by symbiont of host phagocytosis

I don't think
GO:0052191 positive regulation by symbiont of host phagocytosis
happens? the host wants to avoid being phagocytized ?

**Comment by pgaudet** [comment]
- [ ] 'GO:0052483 negative regulation by organism of entry into cell of other organism via phagocytosis involved in symbiotic interaction'
5 EXP -> merge with antiphagocytosis @ValWood ??

**Comment by ValWood** [comment]
Yes but

i) Although the annotations all mean "antiphagocytosis"
the phrase 
GO:0052483 negative regulation by organism of entry into cell of other organism via phagocytosis involved in symbiotic interaction
talks about "entry into cell", so don't include the old term name as a synonym.

ii)  This annotation is a bit dodgy

GOA1 |   |   | negative regulation by symbiont of entry into host cell via phagocytosis |   | CGD | Candida albicans SC5314 | IMP |   |   | gene_product |   | CGD_REF:CAL0000158698PMID:23490206 | 20140625


Abstract
We have previously characterized several fungal-specific proteins from the human pathogen Candida albicans that either encode subunits of mitochondria Complex I (CI) of the electron transport chain (ETC) or regulate CI activity (Goa1p). Herein, the role of energy production and cell wall gene expression is investigated in the mitochondria mutant goa1Δ. We show that downregulation of cell wall-encoding genes in the goa1Δ results in sensitivity to cell wall inhibitors such as Congo red and Calcofluor white, reduced phagocytosis by a macrophage cell line, reduced recognition by macrophage receptors, and decreased expression of cytokines such as IL-6, IL-10 and IFN-γ. In spite of the reduced recognition by macrophages, the goa1Δ is still killed to the same extent as control strains. We also demonstrate that expression of the epithelial cell receptors E-cadherin and EGFR is also reduced in the presence of goa1Δ. Together, our data demonstrate the importance of mitochondria in the expression of cell wall biomolecules and the interaction of C. albicans with innate immune and epithelial cells. Our underlying premise is thatmitochondrial proteins such as Goa1p and other fungal-specific mitochondrial proteins regulate critical functions in cell growth and in virulence. As such, they remain as valid drug targets for antifungal drug discovery.


It's a phenotype/ readout . This is not interfering with the  mechanism of phagocytosis in a non-mutant situation, it's just an assay for the ability to infect the host. I will raise a dispute for this pointing to this ticket by way of explanation.

**Comment by pgaudet** [comment]
OK thanks

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

-  'GO:0052231 modulation of phagocytosis in other organism involved in symbiotic interaction' -> 0 annotations
- 'GO:0052522 positive regulation by organism of phagocytosis in other organism involved in symbiotic interaction' -> 0 annotations
- 'GO:0052379 modulation by organism of entry into other organism via phagocytosis involved in symbiotic interaction' -> 0 annotations
- GO:0052066 entry of symbiont into host cell by promotion of host phagocytosis: 1 human annotation - incorrect
- GO:0052191 positive regulation by symbiont of host phagocytosis -> 0 annotations
- GO:0052190 modulation by symbiont of host phagocytosis
3 EXP: 2 GeneDB, 1 MTBASE

The reason for obsoletion is that those processes do not exist; symbionts may enter cells via host endocytic mechanisms, but this does not involved any modulation or regulation. 

Consider annotating to GO:0085017 entry into host cell by a symbiont-containing vacuole. 

There are 4 annotations to those terms, as listed above. There are no mappings; those terms are not present in any subsets. 

Any comment may be added to the ticket:

https://github.com/geneontology/go-ontology/issues/18562.

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 14th, 2020. Unless objections are received by February 14th, 2020, we will assume that you agree to this change.


Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] GO:0052521 positive regulation by host of symbiont phagocytosis 0 annotations

**Comment by pgaudet** [comment]
@ValWood Did we say that 'GO:0052066 entry of symbiont into host cell by promotion of host phagocytosis' should really mean 'GO:0085017 entry into host cell by a symbiont-containing vacuole' ? I would add a 'consider' tag.

Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] I will also merge "GO:0052380 modulation by symbiont of entry into host via phagocytosis" into 'antiphagocytosis as a NARROW synonym (no annotations)

**Comment by ValWood** [comment]
the consider tag sounds OK

**Comment by ValWood** [comment]
hang on, this doesn't seem right

> I will also merge "GO:0052380 modulation by symbiont of entry into host via phagocytosis" into 'antiphagocytosis as a NARROW synonym (no annotations)

"GO:0052380 modulation by symbiont of entry into host via phagocytosis
is where the pathogen co-opts the phagocytosis machinery (I'm not sure if this should be really endocytic machinery? I don't know enough about this because I haven't annotated any such papers yet)

antiphagocytosis  is where the symbiont avoids host phagocytosis as a defense.

**Comment by pgaudet** [comment]
> I will also merge "GO:0052380 modulation by symbiont of entry into host via phagocytosis" into 'antiphagocytosis as a NARROW synonym (no annotations)


This was the parent of 'negative regulation' that we already merged into antiphagocytosis. I really think the only way the symbiont modulates phagocytsosis is by inhibiting it. 

I merged as BROAD synonym.
