### ISSUE TITLE
'Other organism' merges needed

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18565]
Only symbiont can enter into the host; the host cannot enter the symbiont. Those need to need to be merged into their children: 

'regulation by organism of entry into other organism involved in symbiotic interaction'
'modulation by organism of entry into other organism via phagocytosis involved in symbiotic interaction'
'negative regulation by organism of entry into other organism involved in symbiotic interaction'
'positive regulation by organism of entry into other organism involved in symbiotic interaction'

**Comment by pgaudet** [comment]
Duplicate of #18562 and #17983

**Comment by pgaudet** [comment]
This was not done yet.

**Comment by ValWood** [comment]
This might be done now. @pgaudet .. close?

**Comment by pgaudet** [comment]
yep thanks
