### ISSUE TITLE
Too many appressorium terms (used 3 times!)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18564]
GO:0075039    establishment of turgor in appressorium	**1 annotations**
- GO:0075021    cAMP-mediated activation of appressorium formation	
- GO:0075016    appressorium formation on or near host	**1 annotations**
- GO:0075003    adhesion of symbiont appressorium to host	
- GO:0075022    ethylene-mediated activation of appressorium formation	
- GO:0075023    MAPK-mediated regulation of appressorium formation	
- GO:0075040    regulation of establishment of turgor in appressorium	
- GO:0075043    maintenance of turgor in appressorium by melanization	
- GO:0075035    maturation of appressorium on or near host	**1 annotations**
- GO:0075024    phospholipase C-mediated activation of appressorium formation	
- GO:0075025    initiation of appressorium on or near host	
- GO:0075020    calcium or calmodulin-mediated activation of appressorium formation	
- GO:0075017    regulation of appressorium formation on or near host	
- GO:0075041    positive regulation of establishment of turgor in appressorium	
- GO:0075042    negative regulation of establishment of turgor in appressorium	
- GO:0075036    regulation of appressorium maturation on or near host	
- GO:0075026    regulation of appressorium initiation on or near host	
- GO:0075018    positive regulation of appressorium formation on or near host	
- GO:0075019    negative regulation of appressorium formation on or near host	
- GO:0075037    positive regulation of appressorium maturation on or near host	
- GO:0075038    negative regulation of appressorium maturation on or near host	
- GO:0075027    positive regulation of appressorium initiation on or near host	
- GO:0075028    negative regulation of appressorium initiation on or near host	
- GO:0075033    septum formation involved in appressorium formation on or near host	
- GO:0075034    nuclear division involved in appressorium formation on or near host

**Comment by ValWood** [comment]
- [ ]  GO:0075016 appressorium formation on or near host	1 annotations
-> GO:0075016 appressorium formation 
(and regulation terms)

- [ ] GO:0075021 cAMP-mediated activation of appressorium formation
- [ ] GO:0075023 MAPK-mediated regulation of appressorium formation
- [ ] GO:0075024 phospholipase C-mediated activation of appressorium formation
- [ ] GO:0075020 calcium or calmodulin-mediated activation of appressorium formation
merge into 

GO:0075017 regulation of appressorium formation (on or near host)
(this is just signalling pathway molecular function steps)

**Comment by ValWood** [comment]
obsolete 
GO:0075034 nuclear division involved in appressorium formation on or near host
GO:0075033 septum formation involved in appressorium formation on or near host

( this is just the cell cycle preceding apressorium formation)

**Comment by ValWood** [comment]
Apressorium formation
Following spore attachment and germination on the host surface, the emerging germ tube perceives physical cues such as surface hardness and hydrophobicity, as well as chemical signals including wax monomers that trigger appressorium formation. Appressorium formation begins when the tip of the germ tube ceases polar growth, hooks, and begins to swell. The contents of the spore are then mobilized into the developing appressorium, a septum develops at the neck of the appressorium, and the germ tube and spore collapse and die. As the appressorium matures, it becomes firmly attached to the plant surface and a dense layer of melanin is laid down in the appressorium wall, except across a pore at the plant interface. Turgor pressure increases inside the appressorium and a penetration hyphae emerges at the pore, which is driven through the plant cuticle into the underlying epidermal cells.

I think we should avoid wooly phases like initiation and maturation, and just keep the terms describing physical processes 

keep
GO:0075003 adhesion of symbiont appressorium to host

- [ ] rename
GO:0075043 maintenance of turgor in appressorium by melanization
to
 melanization of appressorium wall (increased turgor pressure is the outcome)
- [ ] redefine
The process in which melanin is produced in the appressorium of the symbiont on or near its host organism. ADD *this process  increases the turgor pressure in the appressorium.

- merge
- [ ] GO:0075035    maturation of appressorium on or near host	**1 annotations**
- [ ] GO:0075025    initiation of appressorium on or near host	
and corresponding regulation termns
into
GO:0075016 appressorium formation

- [ ] obsolete
GO:0075040    regulation of establishment of turgor in appressorium

**Comment by ValWood** [comment]
This is the paper
http://europepmc.org/article/MED/12514128
for 
GO:0075039 establishment of turgor in appressorium 1 annotations

This doesn't really seem to be the correct term. 

. Turgor generationin appressoria results from accumulation of up to 3 M glycerol in the appressorium (de Jong et al., 1997) and,therefore, mobilization of storage reserves is likely to be
critical for appressorium function. Our results indicate that TPS1 is required for appressorium function and cuticle penetration. The simplest explanation for this observation
is that trehalose is used as a reserve carbohydrate that contributes to appressorium turgor by acting as a compatible solute itself, or being converted to the pool of intracellular glycerol in the appressorium. Trehalose could also act as an accessory compatible solute or membrane protectant to allow appressoria to withstand high turgor.

at present therefor this should just be
trehalose synthase involved in appressorium formation
measuring turgor pressure is the assay

**Comment by ValWood** [comment]
GO:0075029    formation of symbiont germ tube hook structure on or near host
is also OK
->  GO:0075029    formation of symbiont germ tube hook structure for appressorium development? maybe

wikipedia
Appressorium formation begins when the tip of the germ tube ceases polar growth, hooks, and begins to swell.

**Comment by ValWood** [comment]
I would like to deprioritise this until I have annotated a few more appressorium papers. Just to see if the division between initiation and maturation is clear.

It is possible  the initiation part is referring to "signalling"

**Comment by pgaudet** [comment]
- [ ] rename initiation of appressorium on or near host 
  initiation of appressorium (and regulation)
 - [ ] rename maturation of appressorium on or near host 
maturation of appressorium   (and regulation)

(until we are clear about whether we want to merge or not)

**Comment by pgaudet** [comment]
- [x] adhesion of symbiont to host -> add parent 'interspecies interaction between organisms'

**Comment by pgaudet** [comment]
Looks like 'turgor' is not only the result of melanin deposition ? 
here they mention trehalose: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC140093/

**Comment by ValWood** [comment]
keep the turgor terms for now. I have seen some papers so I will look at those and refine (it might take a couple of months to get to these)

**Comment by pgaudet** [comment]
GO:0075039 establishment of turgor in appressorium  
Do you want me to rename 'trehalose synthase involved in appressorium formation' ? 
https://github.com/geneontology/go-ontology/issues/18564#issuecomment-575652030


====

Obsolete: 
GO:0075039 establishment of turgor in appressorium 1 annotations 
GO:0075040 regulation of establishment of turgor in appressorium
GO:0075041 positive regulation of establishment of turgor in appressorium
GO:0075042 negative regulation of establishment of turgor in appressorium
-> Those are readouts for melanization

GO:0075021 cAMP-mediated activation of appressorium formation
GO:0075023 MAPK-mediated regulation of appressorium formation
GO:0075024 phospholipase C-mediated activation of appressorium formation
GO:0075020 calcium or calmodulin-mediated activation of appressorium formation
GO:0075022 ethylene-mediated activation of appressorium formation
-> Those should be captured as GO-CAM models.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

GO:0075021 cAMP-mediated activation of appressorium formation
GO:0075023 MAPK-mediated regulation of appressorium formation
GO:0075024 phospholipase C-mediated activation of appressorium formation
GO:0075020 calcium or calmodulin-mediated activation of appressorium formation
GO:0075022 ethylene-mediated activation of appressorium formation
The reason for obsoletion is that these terms should be captured as GO-CAM pathways. 
There are no annotations and no mappings to those terms. Those terms are not present in any subsets.

Any comments can be made to the ticket:  https://github.com/geneontology/go-ontology/issues/18564

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 26th, 2020. Unless objections are received by February 26th, 2020, we will assume that you agree to this change.

Thanks, Pascale
