### ISSUE TITLE
~obsolete~ merge GO:0010204    defense response signaling pathway, resistance gene-independent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18587]
GO:0010204    defense response signaling pathway, resistance gene-independent

14 EXP annotations

This term should be obsoleted, becasue we shouldn't define things by what they aren't.
This would seem to apply to PAMP-mediated signalling, but could also apply to the non-immune system. There should always be a more precise term that could be used (or the parent)

**Comment by ValWood** [comment]
@tberardini  Hi Tanya, can you shed any light on this term. Is it meant for PTIO signalling? or something else?

Thanks

Val

**Comment by tberardini** [comment]
Can we please not obsolete this term? Add synonyms (see below) and expand definition to be more plant-y.


defense response signaling pathway, resistance gene-dependent
(add synonym: host resistance)


defense response signaling pathway, resistance gene-independent
(add synonym: nonhost resistance)


Digging back in the archives...looks like this was mean for resistance that doesn't involve R-genes.


Newer reviews:

https://www.ncbi.nlm.nih.gov/pubmed/25626072
https://apsjournals.apsnet.org/doi/full/10.1094/MPMI-10-16-0213-CR

**Comment by ValWood** [comment]
Hi Tanya,

So, my issue here was, that as I  am annotating plant  pathogens (and the corresponding plant genes), I came across this term. I have used the other term :
**defense response signaling pathway, resistance gene-dependent**
quite a lot, (when annotating pathogen effectors and the corresponding plant R-gene/protein.

but this arrangement implies  that implies that ALL other defense response signalling that is NOT
**defense response signaling pathway, resistance gene-dependent** would belong to GO:0010204  .

This would include, for example
GO:0002752    cell surface pattern recognition receptor signaling pathway

which could apply to Plant PTI signalling
and possibly numerous other terms. 

The  PRR signalling  terms (which I have requested a specific PTI child for)  are not related to GO:0010204 in any way.

I find https://www.ncbi.nlm.nih.gov/pubmed/15102376
Type I nonhost resistance does not produce any visible symptoms whereas type II nonhost resistance results in a rapid hypersensitive response with cell death.  So since cell death is usually mediated by 
defense response signaling pathway, resistance gene-dependent
which you have labelled as  "host resistance"
I'm not sure how well these synonyms correspond?

Can you clarify which signalling pathways  are "resistance gene-independent" and then 
we can see that other terms are related appropriately (or merged).
Possibly  GO:0010204 is meant to refer to PRR signalling? or is it for something else? or a combination of things?

As a newbie in this part of the graph it's  really confusing.   There seem to be lots of often unrelated ways to say the same thing, so the annotation is becoming very inconsistent.

cheers,
Val

**Comment by tberardini** [comment]
I'm not much more of a plant pathogen expert than you are.  This part of the graph was developed by Suparna, and it was in her area of expertise.  

Would your problem be solved if the term were called something more along the lines of nonhost resistance ?

**Comment by ValWood** [comment]
I think host and non-host resistance are a bit orthogonal to the processes. In the review above I see:

Host resistance and nonhost resistance are most commonly differentiated based on pathogen adaptation to a particular species (host) and lack of adaptation to other species (nonhost). Both host and nonhost resistances are the outcomes of the plant immune response. Plant innate immunity has been well described in previous reviews (Chisholm et al. 2006; Cohn et al. 2001; Dangl and Jones 2001; Dodds and Rathjen 2010; Jones and Dangl 2006). Among several components of the plant immune response, basal defense is the first line of defense and is initiated during the early phases of pathogen detection. Basal defense in plants is initiated with the perception of evolutionarily conserved microbial- or pathogen-associated molecular patterns (MAMPs or PAMPs) such as flagellin and EF-Tu by plant extracellular pathogen recognition receptors (PRRs) such as leucine-rich repeat kinases (Dangl et al. 2013; Zipfel 2008). Such responses are referred to as PAMP-triggered immunity (PTI). There are also some overlaps between basal defense and nonhost resistance because it is possible that both host and nonhost plants may recognize similar factors to initiate a defense response. Initiation of plant defense responses and the counter attack of pathogen are well explained by the widely accepted zig-zag model proposed by Jones and Dangl (2006). 


What I am learning in this area is that everyone used their own orthogonal terminology and introduces.
Host and non-host resistance seems to be **more about the ability of the pathogen to adapt** than about the plant process.

the review goes on to say:
"Host resistance and nonhost resistance are most commonly differentiated based on pathogen adaptation to a particular species (host) and lack of adaptation to other species (nonhost). Both host and nonhost resistances are the outcomes of the plant immune response. "

So there is overlap with the plant PTI here.

Pathogens cannot easily adapt to plant PTI because this recognises features of the pathogen that are necessary for pathogen survival (like chitin fragments, or chitinases).  This is generally the first line of defense. Simultaneously, pathogens can secrete effectors, these single gene effectors disrupt many processes and can adapt rapidly because there are no/or fewer evolutionary constraints. These are recognised by the resistance gene receptors. This fits nicely with the resistance gene  dependent term (and that might be the most plant-y way to describe this)., 

However, it seems strange to lump every non-resistance gene dependent process under "resistance gene independent" . It *is* a classification, but it doesn't seem to be based on plant processes, or at least it lumps EVERY non-resistance gene dependent plant immune process.

The small number of experimental annotations (14) alerts a problem. I'll see if I can figure out which processes the annotations are referring to...

**Comment by ValWood** [comment]
Are  host resistance and non-host resitance traits rather than processes?

From https://www.ncbi.nlm.nih.gov/pubmed/25626072

Host resistance is generally controlled by single R genes and less durable compared with nonhost resistance. In contrast, nonhost resistance is believed to be a multi-gene trait and more durable. In this review, we describe the mechanisms of host and nonhost resistance against fungal and bacterial plant pathogens.

**Comment by ValWood** [comment]
In biology, a trait or character is a feature of an organism. ... A visible trait is the final product of many molecular and biochemical processes.

host resistance and non host resistance sound like traits?

GO:0010204 defense response signaling pathway, resistance gene-independent

seems to be trying to describe a trait as a process. Often this seem to be the source of the ontology issues in this branch.  I think I have introduced some new traits in this branch. Now trying to fix...

**Comment by tberardini** [comment]
A great person to ask with your specific questions is Jeff Dangl at University of North Carolina.

https://bio.unc.edu/faculty-profile/dangl/

**Comment by ValWood** [comment]
I looked at all of the annotations. Most seem to be describing 
GO:0002221	pattern recognition receptor signaling pathway

EFR PMID:16713565
Perception of the bacterial PAMP EF-Tu by the receptor EFR restricts Agrobacterium-mediated transformation.
-> refers to PAMP triggered immunity signalling (PTI signalling)

RLP23  PMID:27251392
Abstract
Plants and animals employ innate immune systems to cope with microbial infection. Pattern-triggered immunity relies on the recognition of microbe-derived patterns by pattern recognition receptors (PRRs).
-> PRR-mediated signalling

RIN4  PMID:15935761
We find that RIN4 is itself a regulator of PAMP signaling.

Some of the annotations to 
GO:0010204 defense response signaling pathway, resistance gene-independent
are not to signalling at all.

I will open disputes on the annotation tracker about these.  I can't dispute them in P2GO.

So it seems that really 
GO:0010204	defense response signaling pathway, resistance gene-independent
is referring to
GO:0002221	pattern recognition receptor signaling pathway	

this makes sense, but 
GO:0002221	pattern recognition receptor signaling pathway would seem to be a better way to describe this.

So can we merge these and keep 
GO:0010204	defense response signaling pathway, resistance gene-independent
as a related synonym.

This way any "resistance gene-independent" which do not fit 
GO:0002221	pattern recognition receptor signaling pathway
can have another term?

**Comment by ValWood** [comment]
This one is PRR signalling pathway signalling

RLP30 PMID:18434605
RLP18 PMID:18434605

A number of novel developmental phenotypes were revealed for our CLV2 and TMM insertion mutants. In addition, one AtRLP gene was found to mediate abscisic acid sensitivity and another AtRLP gene was found to influence nonhost resistance toward Pseudomonas syringae pv phaseolicola. This genome-wide collection of Arabidopsis RLP gene T-DNA insertion mutants provides a tool for future investigations into the biological roles of RLPs.

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
The historical part of this seems to hold. This term was added in 2003. This was before much was known on how these were connected. The nomencalture seems to have evolved  with the knowledge since 2003

**Comment by ValWood** [comment]
Chatting with PHI-base collaborators

Non-host resistance is a phenomena where there is no documented  evidence t hat a species infects a particular host and can complete its life cycle.
It means that this particular plant isn't a host for a specific pathogen.

So in this case it seems not to be a process, but an orthogonal method of classification dependent on 
whether the pathogen caused infection or not?

**Comment by ValWood** [comment]
This terms seems that it could cover many things  ( basically all plant  immune responses that aren't resistance gene dependent).

In addition to PTI signalling, it could be used for  other processes (although it is very restrictive becasue it is limited to the signalling aspect).

It would be useful if  you could ask Suprana the extended scope?

**Comment by tberardini** [comment]
>It would be useful if you could ask Suprana the extended scope?

He, he. I could ask her but since it's been almost 14 years since she left the GO project and moved out of plant biology, I doubt she will be able to help.  Someone closer to the current state of research (and that's not me!) would be more helpful. It sounds like you are talking with an appropriate set - what do the PHIbase folks suggest? Did you get in touch with Jeff Dangl?

**Comment by ValWood** [comment]
>almost 14 years since she left the GO project

NEVER! OMG

I didn't get in touch with Jeff Dangle as I'm already multiple conference calls per week with a group of plant biologist who work on pathogen plant interactions.   I asked Kim-Hammond Kosack today, she has published over 100 papers in this area.

Basically  for this term we were really unclear what it meant, but everything that is not "resistance-gene dependent" leave a lot of other pathways lumped together.

Generally these processes are described  elsewhere  in the graph bymore  specific GO terms. Bear in mind that this term  has only 14 EXP annotations, the majority to  would be more appropriately annotated to
GO:0002221 pattern recognition receptor signaling pathway.
(see  above list)

The Rothamsted people  were of the same view. They thought it could possibly be a grouping term for all things not "resistant gene dependent"  but I'm not sure how useful this would be, and  how we could locate all of the relevant processes, and it would seem likely to cause many TPVs. On balance I think it would be better to  remove and reannotate.


and the ones above would GO to PTI
you would only need to review
See https://github.com/geneontology/go-annotation/issues/2790
Are you OK with that?

You can see by the scope of the annotations that what the term means, logically is
GO:0045087   innate immune response MINUS GO:0009870 defense response signaling pathway, resistance gene-dependent

Which is a bit like having a term for DNA metabolism MINUS  "DNA repair"

**Comment by pgaudet** [comment]
I think @ValWood is right that we can re-hourse those under a more specific term. For example in 
https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/r-gene - 
"Natural and Engineered Resistance to Plant Viruses, Part II", by Jack H. Westwood, Mark Stevens, in Advances in Virus Research, 2010, the authors state "Salivary components from M. persicae were recently shown to contain compounds which elicit plant defense responses independent of known SA- and JA-dependent pathways (De Vos and Jander, 2009)." 

So the R-gene independent pathways are dependent on something else. 

Thanks, Pascale

**Comment by tberardini** [comment]
> and the ones above would GO to PTI
you would only need to review
See geneontology/go-annotation#2790
Are you OK with that?

yup!  Thanks for doing so much of the background reading and correspondence with experts.

**Comment by pgaudet** [comment]
I will merge GO:0010204 defense response signaling pathway, resistance gene-independent
into GO:0002758 innate immune response-activating signal transduction
