### ISSUE TITLE
NTR: L-serine-phosphatidylethanolamine phosphatidyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18589]
In order to accurately capture the activity of "Phosphatidylserine synthase" enzymes (particularly PSS2 orthologs), I think we need this:

L-serine-phosphatidylethanolamine phosphatidyltransferase activity
xref: EC 2.7.8.29 (L-1-phosphatidylethanolamine + L-serine <=> L-1-phosphatidylserine + ethanolamine)
xref: RHEA:27606 (a 1,2-diacyl-sn-glycero-3-phosphoethanolamine + L-serine = 1,2-diacyl-sn-glycero-3-phospho-L-serine + ethanolamine)
=> maybe as a direct child of GO:0016780?

Refs:
PMID:31869331 (for Drosophila Pss = Q9VPD3)
PMID: 19014349 (for Human PSS1/PSS2 = P48651/Q9BVG9)

==

Note, we already have this related term (using different substrate):
id: GO:0003882
name: CDP-diacylglycerol-serine O-phosphatidyltransferase activity
def: "Catalysis of the reaction: CDP-diacylglycerol + L-serine = CMP + O-sn-phosphatidyl-L-serine." [EC:2.7.8.8]
xref: EC:2.7.8.8
xref: MetaCyc:PHOSPHASERSYN-RXN
xref: RHEA:16913
is_a: GO:0017169 ! CDP-alcohol phosphatidyltransferase activity

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by hdrabkin** [comment]
+id: GO:0106245
+name: L-serine-phosphatidylethanolamine phosphatidyltransferase activity

**Comment by sjm41** [comment]
Thanks Harold!
