### ISSUE TITLE
PAMP-triggered immunity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18588]
PAMP- triggered immunity (PTI) usually first line of defence
 Upon association with PAMPs, the pattern-recognition receptors activate a downstream mitogen-activated protein kinase signaling cascade that culminates in transcriptional activation and generation of the innate immune responses.

For PTI
I find . GO:0002221 pattern recognition receptor signaling pathway
Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands. PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species, or damage-associated molecular pattern (DAMPs), endogenous molecules released from damaged cells. PMID:15199967

so NTR could be a child of GO:0002221

NTR PAMP-triggered immunity signalling pathway
Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands to activate a plant innate immune response. PAMP-triggered immunity PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species.
exact synonym PTI signalling

~I would also be happy for this to be a synonym. BUT I'm a bit concerned about the mention of damage-associated molecular pattern (DAMPs) because these AFAIK are not innate immune response, they are inflammatory response. I really think these should be split.~
 the DAMPs are also regulating the immune response via  damage detection

Note that I could also use:
GO:0035420 MAPK cascade involved in innate immune response (0 annotations)
it might be best to get rid of this ?

**Comment by ValWood** [comment]
Note that 
GO:0002221 pattern recognition receptor signaling pathway

does not say anything explicityly about "activating" the  immune  response, but "activation" is a parent.

**Comment by ValWood** [comment]
NTR PAMP-triggered immunity signalling pathway
should also be a descendant of
GO:0002220    innate immune response activating cell surface receptor signaling pathway

**Comment by pgaudet** [comment]
I will remove 'damage-associated molecular pattern (DAMPs)' from all term definitions and synonyms. This is quite a different process in which the organism responds to its own molecules, see https://en.wikipedia.org/wiki/Damage-associated_molecular_pattern

Thanks, Pascale

**Comment by addiehl** [comment]
Per my comment in #18620, I disagree with changing the definition of GO:0002221.  Please do not rely solely on wikipedia for guidance here.  PAMPs and DAMPs often bind the same receptors leading to the same downstream processes.

I am happy to have PAMP-triggered immunity signaling pathway added, though again many of these pathways are the same as DAMP-triggered signaling pathways.

**Comment by ValWood** [comment]
This is a recent summary

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6760519/
Plants detect pathogen attack through the perception of conserved microbial signatures, called microbe-associated molecular patterns (MAMPs) or host-derived damage-associated molecular patterns (DAMPs), thanks to plant plasma membrane pattern recognition receptors (PRRs) (Boutrot and Zipfel, 2017). PRRs are generally receptor-like kinases (RLKs) or receptor-like proteins (RLPs) with an extracellular domain for MAMP/DAMP recognition (Trdá et al., 2015). MAMPs can be microbial structural components such as bacterial flagellin, lipopolysaccharides (LPSs), peptidoglycans (PGNs), rhamnolipids (RLs), fungal chitin, or oomycete β-glucans but also secreted toxins or enzymes like fungal xylanase or endopolygalacturonase (Figure 1). DAMPs are endogenous danger signals, such as oligogalacturonides (OGs) or cutin monomers, released from degraded plant cell wall or cuticle, respectively (Boller and Felix, 2009). The MAMP/DAMP perception triggers a complex cascade of signaling events, including ion fluxes such as Ca2+ influx, the production of reactive oxygen species (ROS) and nitric oxide, and the activation of mitogen-activated protein kinases (MAPKs). These early events induce a massive transcriptional reprogramming of primary and secondary metabolisms. The induction of specific defense-related genes leads to the synthesis of (i) pathogenesis-related (PR) proteins, including hydrolytic enzymes (e.g., β-1,3-glucanases or chitinases), which degrade pathogen cell wall; (ii) antimicrobial compounds like phytoalexins; (iii) compounds involved in cell wall reinforcement; and, in some cases, (iv) proteins involved in the hypersensitive response (HR), a form of programmed host cell death (Garcia-Brugger et al., 2006). Altogether, these defense reactions represent the MAMP-triggered immunity (MTI), which is finely regulated by phytohormones (salicylic acid [SA], jasmonic acid [JA], and ethylene [ET]) to finally prevent or delay pathogen infection, thus ensuring a basal plant resistance to pathogens.


so, we keep DAMP in the term,  but this seems to always be related to immunity.
It does seem that  PRR receptors are always related to immune signalling, so, in this case, they must presumably always be immune receptors ?

I'm trying to find a single term to represent PTI in the common usage of
PAMP or MAMP triggered immunity

So  you are saying that 
pattern recognition receptor signaling pathway
and 
PAMP triggered immunity
and
MAMP triggered immunity 
and 
"DAMP triggered immunity" should also be added

are equivalent? and therefore pattern recognition receptor signaling pathway is not broader, is that correct?

**Comment by addiehl** [comment]
in the ontology of 'AMPs, MAMPs are PAMPs

**Comment by addiehl** [comment]
I suspect plant (and animal) DAMPs get produced via mechanical injury (wounding) as well, producing the responses in plants mentioned above and inflammatory and wound healing responses in animals.  Whether these responses are immune responses somewhat stretches the general concept of immunity, but they are certainly defensive in the sense of trying to both repair the organism and be ready for pathogen entrance via the injury.  In reality, bacteria of some types are probably all over the surface of plants and animals and may act as potential pathogens if they gain access to the internal regions.

**Comment by ValWood** [comment]
here, 

- [ ] we need to  revert to the original def for

GO:0002221 pattern recognition receptor signaling pathway
Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands. PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species, or damage-associated molecular pattern (DAMPs), endogenous molecules released from damaged cells. PMID:15199967

which refers to DAMPs

 - [ ] add
NTR PAMP-triggered immunity signalling pathway
Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands to activate a plant innate immune response. PAMP-triggered immunity PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species.
exact synonym PTI signalling

 - [ ] NTR   PAMP-triggered immunity signalling pathway needs parents top BOTH GO:0002221
AND GO:0002758    innate immune response-activating signal transduction
 ( the immune activation in response to a pathogen is the essence of what we are trying to capture)

- [ ] Note that GO:0002221 pattern recognition receptor signaling pathway
will not be able to have 
GO:0002758    innate immune response-activating signal transduction
as a parent because @addiehl  points out that PRR  includes DAMPs  activating signalling and this may, or may not, be related to immune response signalling

I think that will resolve @addiehl is that OK?

**Comment by ValWood** [comment]
It might not be quite optimal as some damage/DAMPs will activate immune response , but  when we come across that I think we can add DAMps to  the "immune signalling term".

**Comment by addiehl** [comment]
This sounds good to me.

**Comment by ValWood** [comment]
@pgaudet  I think we. should to this becasue the plant reannotation for  "resistance -gene independence"
will require this new immune process linked  PRR signalling term

**Comment by pgaudet** [comment]
[Term]
id: GO:0140426
name: PAMP-triggered immunity signalling pathway
namespace: biological_process
def: "Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands to activate a plant innate immune response. PAMP-triggered immunity PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species." [PMID:25744358]
comment: Created new term, see https://github.com/geneontology/go-ontology/issues/18588.
synonym: "MAMP-triggered immunity signalling" EXACT []
synonym: "pathogen-associated molecular pattern signalling" EXACT []
synonym: "PTI signalling" EXACT []
is_a: GO:0002221 ! pattern recognition receptor signaling pathway
is_a: GO:0002758 ! innate immune response-activating signal transduction
created_by: pg
creation_date: 2020-02-11T11:08:57Z
