### ISSUE TITLE
GO:0140404    effector-mediated modulation of host immune response by symbiont

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18599]
GO:0140404    effector-mediated modulation of host immune response by symbiont
-> GO:0140404    effector-mediated modulation of host  INNATE immune response by symbiont

to match definition:

A process mediated by a molecule secreted by a symbiont that results in the modulation (either activation or suppresion) of a host innate immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction. PMID:21467214

**Comment by pgaudet** [comment]
Also change parent to match: 

-is_a: GO:0052553 ! modulation by symbiont of host immune response
+is_a: GO:0052167 ! modulation by symbiont of host innate immune response

Thanks, Pascale
