### ISSUE TITLE
suggest new term DNA-binding transcription factor inhibitor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#18596]
please could we have this MF term:
DNA-binding transcription factor inhibitor activity
as a child of the process 
 GO:0043433 negative regulation of DNA-binding transcription factor activity

and is_a child of
 GO:0140110 transcription regulator activity
> is a new term: DNA-binding transcription factor inhibitor activity
Definition: A molecular function that inhibits the activity of a DNA binding transcription factor (dbTF activity) by binding to the dbTF and preventing it from binding to DNA.

An example is TCF23 Q7RTU1 is an example of a protein that regulates transcription factors by heterodimerising or binding to DbTFs and prevent DNA binding and their specific genomic binding site where the dbTF would have activated or repressed transcription.
Also an example is NFKBIA P25963 which has a different way of regulating transcription factor activity by sequestering the dbTF (complex) in the cytoplasm. Another example is the HSP90 and HSP23 proteins that sequester steroid receptors away from the DNA.

Thanks

Ruth

**Comment by pgaudet** [comment]
[Term]
id: GO:0140416
name: DNA-binding transcription factor inhibitor activity
namespace: molecular_function
def: "An activity that stops, prevents, or reduces the activity of a DNA binding transcription factor activity." [PMID:10652346]
comment: Created new term https://github.com/geneontology/go-ontology/issues/18596.
intersection_of: GO:0098772 ! molecular function regulator
intersection_of: directly_negatively_regulates GO:0003700 ! DNA-binding transcription factor activity
created_by: pg
creation_date: 2020-01-21T14:17:39Z
