### ISSUE TITLE
regulation of mitotic DNA replication initiation from early origin

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18590]
by analogy with GO:0101017; for S. pombe rik1 and some phenotype LDs

id: GO:new
name: regulation of mitotic DNA replication initiation from early origin
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of firing from an early origin of replication involved in mitotic DNA replication." [PMID:22279046]
synonym: "regulation of early replication origin firing" EXACT []
is_a: GO:1903466 ! regulation of mitotic DNA replication initiation

early_origin_of_replication is SO:0002140

**Comment by ukemi** [comment]
Adding, but still need to import the early origin. I like your requests. It's almost like you were an ontology editor at some point in time.

**Comment by mah11** [comment]
> It's almost like you were an ontology editor at some point in time.

funny, that ;)

thanks for the term!
