### ISSUE TITLE
ntr: effector-mediated modulation of host process by symbiont

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18605]
I also need an additional parent to 
GO:0140404    JSON
effector-mediated modulation of host immune response by symbiont

effector-mediated modulation of host process by symbiont

my collaborators pointed out that many effectors are not manipulating defenses (for example, effectors inducing ribotoxic stress)

**Comment by pgaudet** [comment]
We are missing a general parent 'modulation of host process by symbiont' 

However we have those classes, that are inconsistent with the rest of the ontology

GOID | term label | proposed label | structure change
-- | -- | -- | --
GO:0051817 | modification of morphology or physiology of other organism involved in   symbiotic interaction | modulation of biological process in other organism | Merge
GO:0035821 | modification of morphology or physiology of other organism | modulation of biological process in   other organism
GO:0019048 | modulation by virus of host morphology or physiology | modulation by virus of host   biological process
GO:0051851 | modification by host of symbiont morphology or physiology | modulation by host of symbiont   biological process
GO:0044003 | modification by symbiont of host morphology or physiology | modulation by symbiont of host   biological process
GO:0035738 | envenomation resulting in modification of morphology or physiology of   other organism | envenomation resulting in   modification of biological process in other organism

**Comment by pgaudet** [comment]
I cannot find why we use 'morphology or physiology ' rather than 'biological process' @mgiglio99 do you remember ?

**Comment by ValWood** [comment]
process would be much better.

**Comment by mgiglio99** [comment]
I think for where we have 'modification if physiology' we could use 'modification of biological process' instead. But for the morphology part, I think that was when the microbes cause structural changes in the host - for example making a tumor grow. That is something that is not a regular process in the host - so would it be ok to say 'modification of biological process' for that?

**Comment by pgaudet** [comment]
@mgiglio99 Are you referring to 'GO:0051819 induction by symbiont of tumor or growth in host' ? 
I think this could be a 'developmental process', even if the structure doesn't exist in the host (ie in the absence of the symbiont). 

Are there other similar terms ?

**Comment by ValWood** [comment]
that would seem a bit weird for a tumor?

A biological process whose specific outcome is the progression of an integrated living unit: an anatomical structure (which may be a subcellular structure, cell, tissue, or organ), or organism over time from an initial condition to a later condition.

**Comment by pgaudet** [comment]
ok maybe...

**Comment by pgaudet** [comment]
its not a multi-organism process to start with - so where does it fit anyway ?

**Comment by ValWood** [comment]
interaction between species is described

Any process in which an organism has an effect on an organism of a different species.

which is correct.

and multi-organism process is
A biological process which involves another organism of the same or different species.

so that seems OK too?

**Comment by pgaudet** [comment]
So I can move the tumor term up there ? 
@mgiglio99 does that work for you?

**Comment by mgiglio99** [comment]
Just want to make sure I understand the overall plan.
I'm fine with making the term label changes as you have outlined above. But I'm not sure about the merge. But, if we make the name changes then we need to move out any structural things such as the tumor term and you are suggesting that we move it to one of the high level terms - either interspecies interaction or multi-organism process. However, there are other structure-related terms in this node that might not work with the new biological process names. Under 'modification by symbiont of host morphology or physiology' (which would have the new name 'modulation by symbiont of host biological process' ) there is 'modification by symbiont of host structure'. That has children like 'disassembly by symbiont of host cuticle'. That is not (I think) the modfication of a host process, but rather a symbiont process. So, I'm wondering if we should move 'modification by symbiont of host structure' out to be a sibling of the new re-named 'modulation by symbiont of host biological process'?  Then the tumor term could be a child of this. Same deal with 'modification by host of symbiont structure'. Terms in these nodes would need to be reviewed individually as some could be about host processes and some possibly don't make sense.

**Comment by ValWood** [comment]
Hi @mgiglio99 

is 

GO:0051817 | modification of morphology or physiology of other organism involved in symbiotic interaction


always effector mediated?

**Comment by pgaudet** [comment]
I'll do other changes, but not the merge. I agree an organism can modify a BP in another organism without being a symbiont. 

Pascale

**Comment by mgiglio99** [comment]
@ValWood I don't know if they are always effector mediated - I'd guess probably not.

**Comment by ValWood** [comment]
OK, I will assess each of the  effector-mediated parents once the terms are in place and see if any can merge into the parents.

**Comment by pgaudet** [comment]
New term: 

+[Term]
+id: GO:0140418
+name: effector-mediated modulation of host process by symbiont
+namespace: biological_process
+def: "A process mediated by a molecule secreted by a symbiont that results in the modulation (either activation or suppresion) of a host structure or process. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:21467214]
+comment: Created new term, see https://github.com/geneontology/go-ontology/issues/18605.
+synonym: "effector mediated modulation of host process by symbiont" EXACT []
+synonym: "effector triggered modulation of host process by symbiont" EXACT []
+synonym: "effector-dependent modulation of host process by symbiont" EXACT []
+is_a: GO:0044003 ! modification by symbiont of host process
+created_by: pg
+creation_date: 2020-01-29T21:24:42Z

----
I used the same reference as the parent, let me know if there is a better reference.

Thanks, Pascale
