### ISSUE TITLE
fix: inconsistencies in "effector-mediated" branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18606]
GO:0140403    effector-mediated suppression of host innate immune response by symbiont	is_a
GO:0080185    effector-triggered induction of plant hypersensitive response by symbiont	is_a

we use  effector-mediated and effector-triggered in primary term names.

Could we make these consistent?

I actually prefer "triggered" for these because the community call the processes "effector triggered immunity"

**Comment by pgaudet** [comment]
Hi @ValWood 
This is not in the ticket ( #18325) but I remember not using  'GO:0140403 effector-triggered suppression' because how can suppression be triggered ? That seemed an odd way to formulate it. 

This is why we end up with this structure: 

 GO:0140404 effector-mediated modulation of host immune response by symbiont
                                         [is_a relation] GO:0140403 effector-mediated suppression of host innate immune response by symbiont
                                         [is_a relation] GO:0080185 effector-triggered induction of plant hypersensitive response by symbiont 

What do you want to do ? 'triggered' everywhere? 

Thanks, Pascale

**Comment by ValWood** [comment]
No you are right.
It should be "mediated" everywhere.

but the "effector-mediated activation of innate..." term should have

"effector-triggered IMMUNITY" as an exact synonym

**Comment by pgaudet** [comment]
'effector-triggered induction of plant hypersensitive response by symbiont' 
should have synonym 'effector-triggered immunity' ????

The synonym sounds more general.

**Comment by ValWood** [comment]
it does, Could you add as broad

and to 
GO:0140404    JSON
effector-mediated modulation of host immune response by symbiont

as narrow.

**Comment by pgaudet** [comment]
> effector-mediated modulation of host immune response by symbiont

This is the new term label - is this not what you wanted ? (it cannot be term label and synonym)

**Comment by ValWood** [comment]
sorry, confusing

action

change
 'effector-triggered immunity'  to broad for GO:0080185


@CuzickA  OK?
