### ISSUE TITLE
obsoletion: transmission of virus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18601]
It  isn't clear what this term is describing.
The term has a parentage to "viral process"

It has 6 annotations:
UniProtKB:P46934	NEDD4	involved_in	GO:0019089    transmission of virus	ECO:0000315   IMP	PMID:15126635	
9606 Homo sapiens	BHF-UCL	
UniProtKB:Q62940	Nedd4	involved_in	GO:0019089    transmission of virus	ECO:0000266   ISO	PMID:15126635	
RGD:736612	10116 Rattus norvegicus	RGD	
UniProtKB:Q8UZ11	UL36	involved_in	GO:0019089    transmission of virus	ECO:0000315   IMP	PMID:15479829	
33703 Suid herpesvirus 1 (strain Kaplan)	AgBase	
UniProtKB:Q8UZ12	UL37	involved_in	GO:0019089    transmission of virus	ECO:0000315   IMP	PMID:15479829	
33703 Suid herpesvirus 1 (strain Kaplan)	AgBase	
UniProtKB:Q9VAL0	Spase12	involved_in	GO:0019089    transmission of virus	ECO:0000315   IMP	PMID:27383988	
7227 Drosophila melanogaster	UniProt	
UniProtKB:Q9VCA9	Spase22-23	involved_in	GO:0019089    transmission of virus	ECO:0000315   IMP	PMID:27383988	
7227 Drosophila melanogaster	UniProt

the first one, for example
Nedd4.1-mediated ubiquitination and subsequent recruitment of Tsg101 ensure HTLV-1 Gag trafficking towards the multivesicular body pathway prior to virus budding.

so human nedd4 should not be annotated to "viral transmission"

**Comment by pgaudet** [comment]
@pmasson55

**Comment by pmasson55** [comment]
I have no idea what this term is about...The definition doesn't help much:
"The transfer of virions in order to create new infection. "
I don't think any host proteins should be annotated with this term...Some people use it to annotate host proteins while others use it for viral proteins... 
 The definition should be more clear or the term should be deleted.

**Comment by pgaudet** [comment]
The whole branch should go: in AmiGO this are the annotations were have : 
- GO:0051821 dissemination or transmission of organism from other organism involved in symbiotic interaction -> 0 EXP 
-  GO:0051822 dissemination or transmission of organism from other organism by vector involved in symbiotic interaction-> 0 EXP  
- GO:0044007 dissemination or transmission of symbiont from host
- GO:0044008 dissemination or transmission of symbiont from host by vector -> 2 EXP 
- GO:0019089 transmission of virus -> 5 annotations
- GO:0044009  viral transmission by vector  -> 0 annotations

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0051821 dissemination or transmission of organism from other organism involved in symbiotic interaction' and children. 
- GO:0051821 dissemination or transmission of organism from other organism involved in symbiotic interaction -> 0 EXP 
-  GO:0051822 dissemination or transmission of organism from other organism by vector involved in symbiotic interaction-> 0 EXP  
- GO:0044007 dissemination or transmission of symbiont from host > 0 EXP  
- GO:0044008 dissemination or transmission of symbiont from host by vector -> 2 EXP 
- GO:0019089 transmission of virus -> 5 annotations
- GO:0044009  viral transmission by vector  -> 0 annotations

The reason for obsoletion is that those terms do not represent specific processes. If possible the genes should be annotated to more specific terms. 

Annotation review requests are here: 
- GO:0044008   https://docs.google.com/spreadsheets/d/1qFs7XoGqMhUeL-qKY0mEqlb-0n2KmtoRnzZcbbDI6ts/edit#gid=0
@Achchuthan @sandyl27 

- GO:0019089 https://docs.google.com/spreadsheets/d/1VQlN_F0IKcqL7gTG0tw9zFbfnXZ_fdctnTtoZvpSxVg/edit#gid=0
@pgarmiri @RLovering 

There are 3 InterPro domains with mapping to GO:0019089 transmission of virus

InterPro:IPR007935
InterPro:IPR004917
InterPro:IPR007982
@happy-lorna 

The terms are not present in any subsets. 

Any comment may be added to the ticket:

https://github.com/geneontology/go-ontology/issues/18601.


We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 10th, 2020. Unless objections are received by February 10th, 2020, we will assume that you agree to this change.


Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi, The 2 UniProt annotations have been reviewed and changed to GO:0050689 '
negative regulation of defense response to virus by host'
Thanks,
Penelope

**Comment by pgaudet** [comment]
Thanks !

**Comment by ValWood** [comment]
~Hi @pgarmiri Is that for 
https://www.uniprot.org/uniprot/Q9VCA9
I don't think these are "defense reponse"?
It seems that the virus is hijacking the host secretory pathway?
Here, we validated nine human genes required for flavivirus infectivity, and these were associated with endoplasmic reticulum functions including translocation, protein degradation, and N-linked glycosylation. In particular, a subset of endoplasmic reticulum-associated signal peptidase complex (SPCS) proteins was necessary for proper cleavage of the flavivirus structural proteins (prM and E) and secretion of viral particles.

**Comment by pgarmiri** [comment]
Hi @ValWood , good point! I have removed them now.

**Comment by pgaudet** [comment]
Hello, 

Just a reminder that this term will get obsoleted next Monday (unless someone needs more time). 

Thanks, Pascale

**Comment by typhainepl** [comment]
I've removed the GO terms from the InterPro entries.

**Comment by pgaudet** [comment]
Thanks @typhainepl
