### ISSUE TITLE
Improve definition of 'GO:0036206' regulation of histone gene expression

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18613]
The definition is too generic - @colinlog can provide a better definition.

**Comment by ValWood** [comment]
Do we need such a term (1 annotation).
I would never think to use this.

**Comment by pgaudet** [comment]
Colin says the mechanism of regulation is very specific, so let's wait for a new definition first - OK ?

**Comment by ValWood** [comment]
OK! but are we really talking about histone "expression",  (which includes translation etc) or really just about histone transcription?

**Comment by pgaudet** [comment]
could be transcription...

**Comment by pgaudet** [comment]
Obsoleted in  #20209
