### ISSUE TITLE
small revisions to mitotic contractile ring structure terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18615]
please  update these 3 terms as follows

MITOTIC actomyosin contractile ring, proximal layer
Definition (GO:0120104 GONUTS page)
The region of the MITOTIC actomyosin ring adjacent to the plasma membrane where membrane bound scaffolds are located.
https://github.com/geneontology/go-ontology/issues/14337

GO:0120105    JSON
MITOTIC actomyosin contractile ring, intermediate layer
Cellular Component
Definition (GO:0120105 GONUTS page)
The region of the MITOTIC actomyosin ring in between the proximal layer and the actin filament layer. This region contains the accessory protein network, some actin filaments and connections between the proximal layer and the actin filament layer. PMID:28914606

GO:0120106    MITOTIC actomyosin contractile ring, distal actin filament layer
Definition (GO:0120106 GONUTS page)
The region of the MITOTIC actomyosin ring containing actin filaments and cross linkers, myosin motors, and connections to the plasma membrane through the intermediate layer. It is further from the plasma membrane than the intermediate layer which it is adjacent to. PMID:28914606

and move underneath
GO:0110085    mitotic actomyosin contractile ring

meiotic contractile rings are so far uncharacterized, but at least in yeast are dissimilar to mitotic rings.

I'm the only person who has used these terms for manual annotation so far.

**Comment by ValWood** [comment]
This should be quick, it only needs 'mitotic' inserting into all the terms. I should have added this when I requested them.
We have no equivalent meiotic structures.

**Comment by pgaudet** [comment]
@ValWood 
Right now those 3 terms have the relation 
'part of' some 'actomyosin contractile ring'

You want me to change to ''part of' some 'mitotic actomyosin contractile ring'' , is that right ?

**Comment by pgaudet** [comment]
Also, I removed 'part of some cell'. 

Let me know if you wanted that.

**Comment by ValWood** [comment]
I don't understand the "part of some cell'
is that in the def? I don't see it (or in the parentage)

**Comment by pgaudet** [comment]
"part of some cell' was one of the parents
