### ISSUE TITLE
GO:0045087 remove comment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18619]
this comment doesn't really help curators or users so it is confusing.

Comment
This term was improved by GO_REF:0000022. It was moved.

**Comment by addiehl** [comment]
The point of this comment was to link to the GO immunology revision of 2006, as part of the accounting of which terms were affected by the revision.  At the time, I was told by the GO editorial office to add such comments as a tracking mechanism for the revision.

**Comment by ValWood** [comment]
Hmm, should that be a reference?

As I am reading this term,  it doesn't seem to be a comment for curators? Lots of terms are moved.

Comments are usually about How to use a term in curation, not about ontology changes.

**Comment by addiehl** [comment]
Well, I was explaining the history of the comment.  I don't really care if you want to remove it and all similar comments should they offend you.  They will continue to be present in archived versions of the GO should anyone care.  I don't believe these comments have any negative effects on the use of the GO, nor that their removal will improve the GO, but whatever.

**Comment by ValWood** [comment]
I think it is just in the wrong place?

I should see this type of comment in the outward facing tools, i.e here
https://www.ebi.ac.uk/QuickGO/term/GO:0045087


the exact change is recorded nicely in the change log]

2019-03-14 | Added | RELATION | is a GO:0098542 (defense response to other organism)
2019-03-14 | Deleted | RELATION | is a GO:0006952 (defense response)

but it would be inconsistent to describe ontology changes in these comments.

The GO ref GO_REF:0000022 is not accessible from term pages, so this isn't helpful to the user, and I'm not sure that if I tracked this reference down it would tell me the precise change.

But I'm sure there is a place to record  a GO REF which isn't the comments field?
@pgaudet

**Comment by pgaudet** [comment]
So far there isn't a comment field that is not public.

**Comment by ValWood** [comment]
But there is a place for x-refs?

**Comment by pgaudet** [comment]
GO_REF:0000022 is already in the term definition xref (at least for GO:0002344): 

> The process in which B cells produce antibodies with increased antigen affinity. This is accomplished by somatic hypermutation and selection for B cells which produce higher affinity antibodies to antigen. Source: ISBN:0781735149, GO_REF:0000022, GOC:jal, GOC:mtg_15nov05

I will remove all comments with GO_REF:0000022, make sure the GO_REF is in the def xreference, and remove GOC:mtg_15nov05 since that refers to the same meeting (see https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000022.md). 


Thanks, Pascale
