### ISSUE TITLE
Taxon constraint for GO:0021828

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#18622]
The term "gonadotrophin-releasing hormone neuronal migration to the hypothalamus" (GO:0021828)  and its definition is a valid term for Zebrafish (see PMID:27137492). 
However, there is a taxon constraint forbidding its used in zebrafish. I am assuming that this constraint comes from the "is_a" relationship with the term "cerebral cortex tangential migration using cell-axon interactions" (GO:0021824) - indeed, zebrafish does not have a cerebral cortex. I think the other parents are not excluded from the fish taxon. 

Could you remove the taxon constraint on "gonadotrophin-releasing hormone neuronal migration to the hypothalamus" (GO:0021828), please? 
Thank you

**Comment by ukemi** [comment]
Hi @sabrinatoro. I will do this by removing the cerebral cortex parent and probably adding another parent. Currently this is a true path violation.

**Comment by ukemi** [comment]
Actually, the remaining parent looks ok: hypothalamic tangential migration using cell-axon interactions. If it's not, reopen the ticket and I will fix it. This change should go in within the next half hour or so.
