### ISSUE TITLE
"limb developement" terms need review (definition or relation to UBERON) 

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#18624]
Taxon constraints for "limb development" (GO:0060173) and children terms are such that they cannot be used for Zebrafish. ("fin" terms are siblings of the limb terms) 
However:  "fins" are in the definition of "limb development" : " A limb is an appendage of an animal used for locomotion or grasping. Examples include legs, arms or some types of fin. "

If this term refers to UBERON:0002101, the definition for 'limb development' should be updated.
If this term refers to UBERON:0004708, the "limb development" and the "fin development" terms should be merged.

**Comment by balhoff** [comment]
The logical definition uses UBERON:0002101 'limb'. The definition should probably just mention "tetrapod limb".

**Comment by ukemi** [comment]
The fin terms are logically defined using appendage (UBERON:0000026). I think we need to remove the 'or some types of fin' from the textual definition.

**Comment by sabrinatoro** [comment]
Thank you @ukemi

**Comment by ukemi** [comment]
No worries @sabrinatoro. Just so I understand the issue completely. Do you think that some fins should be in a grouping class with limbs? If so, then we need to work that out on the UBERON side. I'm not certain why you are seeing the taxon constraint applied to annotations to fin development. Also when I look at the logical definition of fin development, it is referring to the UBERON term 'paired fin'. This is incorrect for medial fins. UBERON does have a term for a generic fin, but it looks like it is missing from the import. Here is what I suggest:
1. Import fin UBERON_0008897 and median fin UBERON_0008897 from UBERON
2. Change the logical definition of fin development to refer to the generic fin (UBERON_0008897)
3. Add a logical definition to medial fin development (median fin UBERON_0008897)
4. Remove the asserted superclasses and let UBERON do the work
5. Remove the mention of fin in the limb textual definition

All fins should then be appendages and only have the taxon restriction eumetazoa.
@balhoff, how about an evolutionary anatomist's sanity check?

**Comment by ukemi** [comment]
I guess one question I have is what about whales and dolphins? Have you guys considered them?

**Comment by balhoff** [comment]
@ukemi mammal fins go under limb, 'pectoral flipper' is a narrow synonym for 'forelimb':  http://purl.obolibrary.org/obo/UBERON_0002102

There is a grouping class 'paired limb/fin' which includes tetrapod limbs and teleost fins: http://purl.obolibrary.org/obo/UBERON_0004708

**Comment by sabrinatoro** [comment]
The zebrafish community often uses the word "limb" to refer to "fin", and especially in the case of using zebrafish as a model for human disease.
Therefore, curators used the terms "limb development" because it seems like a good term to use and the taxon constraint wasn't obvious (especially since 'fin' was in the definition).

One thing we might need to keep in mind, is the fact that not all the fins are evolutionary equals:
- the "paired fin" (pectoral and pelvic fins) are "limbs"
- other fins (dorsal fin, caudal fin, anal fin) are not "limbs"
So I think that we probably should make a difference between these in the ontology
(am I confusing the whole thing?)

**Comment by ukemi** [comment]
I saw that grouping class, but I thought it was inappropriate for the logical def of our fin terms because it would not be sufficient. However, it does address the issue that @sabrinatoro makes above. Maybe we should relax our logical def of limb development to refer to UBERON_0004708. This would fit the current textual definition and would still allow automatic classification.

**Comment by ukemi** [comment]
P.S. You're not confusing things. Biology can be complicated.

**Comment by ukemi** [comment]
OK. It looks like these guys are already in the imports. I will make the appropriate changes.

**Comment by sabrinatoro** [comment]
@ukemi 
your proposal to refer to UBERON_0004708 (paired limb/fin) is a great idea (Especially for users who would not know necessarily make the difference). 
However I think we will have to make some changes in the GO ontology to make sure that limb and ‘paired fins’ terms are merged (I will be happy to help with that if you need). 
The “fin” term could be kept to refer to “medial” fins (and therefore we should make it very clear in the definition).

**Comment by ukemi** [comment]
I don't think we can do that merge because we don't have a paired fin term. The terms should automatically classify. I am doing the edits now. Do you want me to skype with you and show you how the reasoning works out? Or we can just do it together.

**Comment by sabrinatoro** [comment]
sure, let's chat, whenever you have time
