### ISSUE TITLE
Really tiny typo in synonym of GO:0002223

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#18625]
GO:0002223 stimulatory C-type lectin receptor signaling pathway
has the narrow synonym
"stimulatory Ly49 family receptor signaling pathway.".
You may want to remove the end ".".
Thanks.

**Comment by pgaudet** [comment]
Others with the same problem: 


* GO:0036404 synonym:   "conversion of double-stranded small interfering RNA to single-stranded   small interfering RNA." 
* GO:0047152 synonym: "methanol-corrinoid protein Co-methyltransferase." 
* GO:0050819 synonym: "negative regulation of clotting." 
synonym: "neurotransmitter receptor activity involved in chemical synaptic transmission." 
* GO:1902360 synonym:   "conversion of double-stranded small interfering RNA to single-stranded small interfering RNA. involved  in (etc"
