### ISSUE TITLE
Taxon constraint for GO:0046844 (chorion micropyle formation) 

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#18623]
This term (and its definition) could be used for Zebrafish which has a chorion (UBERON:0003124)
The following publications report studies in which 'chorion micropyle formation' was studied: PMID:30327325, PMID:30608921

I believe that the taxon constraint issue is due to the parents of this term which are referring specifically to insects. 
Could you either change the parentage in the ontology so that this term can be used for zebrafish, or create a new one which would mean the same thing but that would be allowed with the fish taxon? 
Thank you

**Comment by ukemi** [comment]
I'll take this one too because I thought we already dealt with this. I'll see what's up.

**Comment by ukemi** [comment]
I see the problem, micropyle needs to be moved from being a part of chorion to part_of egg chorion. However, this opens another can of worms. chorion-containing eggshell formation is asserted to be only in insects. I think I need to remove that restriction.

**Comment by ukemi** [comment]
A quick search of the literature suggests that fish have a chorion-containing eggshell. In fact, it looks like the terms are used interchangeably. Egg chorion def: A protective, noncellular membrane that surrounds the eggs of various animals including insects and fish [GO].

**Comment by ukemi** [comment]
@sabrinatoro the UBERON term for chorion, UBERON:0003124, is restricted to the chorion tissue of amniotes. I think the zebrafish chorion would fall under the egg chorion, UBERON:0000920.

**Comment by ukemi** [comment]
Remove insect restriction on chorion terms.
https://github.com/geneontology/go-ontology/pull/18676

**Comment by ukemi** [comment]
OK. I think I have fixed this in GO, but nb @cmungall and @balhoff there are now two 'egg chorion' terms, one from UBERON and one from GO that refer to the same structure. I decided to rename the GO term egg chorion. I could have renamed it eggshell chorion, but at any rate they would still refer to the same thing. Should I open a ticket in the UBERON tracker to obsolete the term in UBERON?

**Comment by ukemi** [comment]
https://github.com/obophenotype/uberon/issues/1555
