### ISSUE TITLE
resolvin biosynthetic process

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#18638]
Dear GOA curators,
Could you please consider creating these new terms:
1. D-series resolvin biosynthetic process PMID:12391014
2. E-series resolvin biosynthetic process  PMID:21206090
3. 13-series resolvin biosynthetic process PMID:26236990
as children of GO:0033559?
The terms are needed to annotate P35354 PGH2_HUMAN which metabolizes docosahexaenoate (DHA, C22:6(n-3)) to 17R-HDHA, a precursor of the D-series resolvins (RvDs); converts docosapentaenoate (DPA, C22:5(n-3)) to 13R-HDPA, a precursor for 13-series resolvins (RvTs); converts eicosapentaenoate (EPA, C20:5(n-3)) primarily to 18S-HEPE that is further metabolized by ALOX5 and LTA4H to generate 18S-RvE1 and 18S-RvE2.

For review please see: PMID 24899309
and pathway refs:
http://www.reactome.org/content/detail/R-HSA-9023661
http://www.reactome.org/content/detail/R-HSA-9018896
http://www.reactome.org/content/detail/R-HSA-9018676
http://www.reactome.org/content/detail/R-HSA-9026403

Many thanks for your help,
Nevila Hyka-Nouspikel

**Comment by ukemi** [comment]
ChEBI identifiers are in the Reactome pathways.

**Comment by hdrabkin** [comment]
Hi @nnouspikel 
Trying to close out older tickets. 
Please, I need you to supply specific definitions for these terms. 
Thanks.

**Comment by nnouspikel** [comment]
Hi Harold,

Thank you for getting back to me. 

Here are the definitions as requested:
-	Parent term_new GO: resolvin biosynthetic process
Definition: The chemical reactions and pathways resulting in the formation of resolvins, di- or trihydroxy fatty acids derived from omega-3 polyunsaturated fatty acids, specifically icosapentaenoic acid, docosahexaenoic acid and docosapentaenoic acid.
child of GO:0006633 fatty acid biosynthetic process
more text to be added if necessary: resolvin biosynthesis is a combination of oxidation, reduction and hydrolysis reactions involving lipoxygenases and cyclooxygenases.
-	Child term_new GO: D-series resolvin biosynthetic process
Definition: The chemical reactions and pathways resulting in the formation of resolvin family D-series, hydroxy fatty acids derived from docosahexaenoic acid.
-	Child term_new GO: E-series resolvin biosynthetic process 
Definition: The chemical reactions and pathways resulting in the formation of resolvin family E-series, hydroxy fatty acids derived from icosapentaenoic acid.
-	Child term_new GO: 13-series resolvin biosynthetic process 
Definition: The chemical reactions and pathways resulting in the formation of resolvin family 13-series, hydroxy fatty acids derived from docosapentaenoic acid.

to consider creating 
new GO: resolution phase response PMID:28087575 
child of GO:0002526 acute inflammatory response
Definition: An active host response phase of acute inflammation driven by specialized pro-resolving mediators (SPMs) and signaling pathways, enabling timely tissue regeneration and return of function.
More text to be added if necessary:
Acute inflammatory response(s) are self-limited, resolve on their own and classically divide into initiation and resolution phases. 
SPMs – a superfamily of of proresolving mediators that include resolvins (Rvs), protectins (PDs), maresins (MaRs) and lipoxins (LXs).
**
Many thanks,

Nevila

**Comment by hdrabkin** [comment]
Sorry the ticket slipped through the cracks.

+id: GO:0106295
+name: resolvin biosynthetic process

+id: GO:0106296
+name: D-series resolvin biosynthetic process

+id: GO:0106297
+name: E-series resolvin biosynthetic process

+id: GO:0106298
+name: 13-series resolvin biosynthetic process
+
+id: GO:0106299
+name: resolution phase response
