### ISSUE TITLE
NTR:? mechanoreceptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18636]
I can't find a term for mechanoreceptor

although lots of terms mention mechanoreceptors?
GO:0042490    mechanoreceptor differentiation 7,301 annotations
GO:0045631    regulation of mechanoreceptor differentiation 503 annotations
GO:0045632    negative regulation of mechanoreceptor differentiation 270 annotations
GO:0045633    positive regulation of mechanoreceptor differentiation 78 annotations

as a type of transmembrane signalling receptor?

**Comment by ValWood** [comment]
For yeast we have stretch receptors to detect chenges in cell wall integrity

ref
https://www.ncbi.nlm.nih.gov/pubmed/31404395?dopt=Abstract

but I guess would encompass sound and other=sensorey receptors?

**Comment by ValWood** [comment]
note to self wsc1

**Comment by hdrabkin** [comment]
Will need
term definition; references, is parent (unless sure they would always be type of  transmembrane signalling receptor).

**Comment by ValWood** [comment]
Ah I think the "mechanoreceptor" in the terms above is different. It seems to be referring to a cell type. Is that correct?

**Comment by ValWood** [comment]
I wasn't sure if there was a term already but I couldn't find it.
The mechanoreceptors I am referring to are always TM receptors.
Reference above.


I'll write a def based on this if nothing exists already.

**Comment by ValWood** [comment]
All the terms above are missing the word "cell"
The children are all 
posterior lateral line neuromast hair cell differentiation
inner ear receptor cell development
etc

**Comment by ValWood** [comment]
Suggested def

Detecting with an  external mechanical stimuli and transmitting a signal from one side of the membrane to the other to initiate a change in cell activity or state as part of signal transduction.

**Comment by ValWood** [comment]
and fix

GO:0042490 mechanoreceptor **cell**  differentiation 7,301 annotations
GO:0045631 regulation of mechanoreceptor **cell**  differentiation 503 annotations
GO:0045632 negative regulation of mechanoreceptor  **cell**  differentiation 270 annotations
GO:0045633 positive regulation of mechanoreceptor **cell**  differentiation 78 annotations

**Comment by pgaudet** [comment]
Can you add synonyms to either (or all) of those: 

GO:0008381 mechanosensitive ion channel activity
                                     [is_a relation] GO:0043854 cyclic nucleotide-gated mechanosensitive ion channel activity
                                     [is_a relation] GO:0140135 mechanosensitive cation channel activity 

Thanks, Pascale

**Comment by ValWood** [comment]
Ah right I thought something existed already. However, I want to annotate yeast wsc1 which isn't an ion channel. Some mechanoreceptors are ion channels and some aren't?
These are like integrins
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6685044/figure/fig3/

**Comment by ValWood** [comment]
They are actually referred to as "sensors" rather than receptors.  How do we differentiate between a sensor and a receptor?

**Comment by pgaudet** [comment]
We use the 'sensor activity' term ;) 

However the most general one is 'small molecule sensor activity' ...?

**Comment by pgaudet** [comment]
How are integrins annotated ? I wonder if we need a separate activity or if we can add a synonym to an existing term.

**Comment by pgaudet** [comment]
OK in PAINT (PTHR23220) primary annotations are mostly to binding. 

So we probably need that new term.

**Comment by ValWood** [comment]
one integrin

actin binding Source: BHF-UCL
cadherin binding Source: BHF-UCL
cell adhesion molecule binding Source: UniProtKB
collagen binding involved in cell-matrix adhesion Source: UniProtKB
coreceptor activity Source: UniProtKB
fibronectin binding Source: UniProtKB
integrin binding Source: GO_Central
laminin binding Source: Ensembl
metal ion binding Source: UniProtKB-KW
protease binding Source: UniProtKB
protein-containing complex binding Source: UniProtKB
protein heterodimerization activity Source: UniProtKB
virus receptor activity Source: UniProtKB-KW
(plus more  81 total, mainly binding)

**Comment by pgaudet** [comment]
right :(

**Comment by ValWood** [comment]
EXP for  pthr10082 | protein_coding_gene



+ | − | (39) | signaling receptor activity
-- | -- | -- | --
+ | − | (11) | metal ion binding
+ | − | (8) | virus receptor activity
+ | − | (4) | integrin binding
+ | − | (3) | ICAM-3 receptor activity
+ | − | (3) | extracellular matrix protein binding
+ | − | (3) | heat shock protein binding
+ | − | (3) | protein kinase C binding
+ | − | (3) | protein kinase binding
+ | − | (2) | G protein-coupled receptor binding
+ | − | (2) | actin binding
+ | − | (2) | insulin-like growth factor I binding
+ | − | (2) | neuregulin binding
+ | − | (2) | protease binding
+ | − | (2) | protein heterodimerization activity
+ | − | (2) | protein tyrosine kinase binding
+ | − | (1) | C-X3-C chemokine binding
+ | − | (1) | collagen binding involved in cell-matrix adhesion
+ | − | (1) | fibronectin binding
+ | − | (1) | laminin binding

**Comment by krchristie** [comment]
There are a lot of integrins. When I was trying to annotate some of them a while ago, I don't remember anything about mechanosensory activity. Looking at Wikipedia: https://en.wikipedia.org/wiki/Integrin seems consistent with the idea that different integrins do different things, so possibly not safe to associate mechanosensor activity generally with integrins.

I have come across mechanosensing numerous times at cilia meetings. I don't know if I've seen a really clear elucidation of how this is working, whether there is a receptor in the ciliary membrane (not sure I've ever seen that suggested at all), or whether it is some mechanical property of the cilium as a whole.

The Wikipedia page on mechanoreceptors: https://en.wikipedia.org/wiki/Mechanoreceptor says 
> "A mechanoreceptor is a sensory neuron that responds to mechanical pressure or distortion." 

A specific example I know a lot about is a hair cell of the inner ear. The Wikipedia page for stereocilia has this description (https://en.wikipedia.org/wiki/Stereocilia_(inner_ear)):
> "In the inner ear, stereocilia are the mechanosensing organelles of hair cells, which respond to fluid motion in numerous types of animals for various functions, including hearing and balance. They are about 10–50 micrometers in length and share some similar features of microvilli.[1] The hair cells turn the fluid pressure and other mechanical stimuli into electric stimuli via the many microvilli that make up stereocilia rods.[2] Stereocilia exist in the auditory and vestibular systems."

To add to that, each hair cell has a specialized cilium called a kinocilium that is surrounded by an array of actin-filiment based stereocilia. The entire array of actin filaments and the kinocilium are all required for transducing the signal of the fluid in the cochlea to a signal, so definitely not simply a TM receptor for hair cells, though it may turn out that one or more of those are involved in the process as well.

Anyway, let's please not make a term or definition that says that a mechanoreceptor is a TM protein until we find papers that indicate this is the way to go.

**Comment by ValWood** [comment]
I'm going to close this. It's not so important right now. I can keep this as "transmembrane signalling receptor"...it was just something I saw go by in a review and I thought it would be nice to capture the specificity, but it sounds not so simple. I will wait until I have EXP publications for this.

**Comment by ValWood** [comment]
I have a publication!
Detection of surface forces by the cell-wall mechanosensor Wsc1 in yeast

Could I get 
mechanoreceptor activity
Combining with a mechanical force and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity or state as part of signal transduction.

parent
transmembrane signaling receptor activity

reference PMID: 34666001

**Comment by ValWood** [comment]
Can this term be added?  I guess I should have put it in a new ticket, but I thought it might be useful. to have this discussion to hand.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140894
+name: mechanoreceptor activity
+namespace: molecular_function
+def: "Combining with a mechanical force and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity or state as part of signal transduction." [PMID:23907979, PMID:34666001]
+is_a: GO:0004888 ! transmembrane signaling receptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/18636 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-22T14:23:45Z
+
