### ISSUE TITLE
GO:0001300    chronological cell aging

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18632]
GO:0001300    chronological cell aging
Definition (GO:0001300 GONUTS page)
The process associated with progression of the cell from its inception to the end of its lifespan that occurs when the cell is in a non-dividing, or quiescent, state. PMID:12044934

This isn't a process in the GO sense.

There are 42 EXP annotations to the term + descendants

Proably the annotations could move to some aspect of 
quiescence or senescence?

(I am moving the pombe annotations)

I would suggest obsoletion @srengel  what do you think? M<ost of the annotations are from SGD.

Jurg's lab, who studies ageing said "chronological ageing is a process like cancer is a process"

Lots of processes "affect" ageing obviously,  and there are probably some contexts where "ageing" is part of normal development. But chronological ageing is a trait?

**Comment by pgaudet** [comment]
For info: 

This is the ticket where the term was requested: #9284 
You also questioned it here: #14881 

Maybe this mostly applies to plants @tberardini ? 

Thanks, Pascale

**Comment by ValWood** [comment]
This is the ticket where the term was requested: #9284
isn't the ticket where the term was requested. These terms look fine (like ripening), they are "programmed ageing" not "deterioration and loss of function over time"

**Comment by ValWood** [comment]
I'm objec ting because  some of the community who don't realise GO is for normal procersses are suing this term. However most  of the  genes which impact chronoligical ageing won't be GO annotated.

I also don't really want to delete the community annotation becasue the term exists (and clearly chronoligical ageing exists). It just isn't a GO process.

**Comment by tberardini** [comment]
> Maybe this mostly applies to plants @tberardini ?

Nope, not a plant-related request. Rereading #9284 shows that 'chronological cell aging' was already present when the plant senescence terms were requested. There are no plant annotations to the term either.

**Comment by pgaudet** [comment]
Thanks @tberardini 

@srengel are you OK with obsoletion ?

**Comment by srengel** [comment]
hi only just now looking at this ticket.  was buried in the grant renewal last week but now i'm back looking at stuff today...

**Comment by srengel** [comment]
ok yes @pgaudet this is going to be fine with SGD.  i'll work through the annotations to remove them.

...are we going to also obsolete 'replicative cell aging'?

**Comment by ValWood** [comment]
This is a phenotype too.
67 annotation
57 SGD


The definition as a process doesn't really make much sense
The process associated with progression of the cell from its inception to the end of its lifespan that occurs as the cell continues cycles of growth and division. PMID:12044934

The mouse/Rat ones  I checked seem to be about accelerated lifespan and mortality. 

The reference for the term is
Over the past 10 years, considerable progress has been made in the yeast aging field. Multiple lines of evidence indicate that a cause of yeast aging stems from the inherent instability of repeated ribosomal DNA (rDNA). Over 16 yeast longevity genes have now been identified and the majority of these have been found to affect rDNA silencing or stability. Environmental conditions such as calorie restriction have been shown to modulate this mode of aging via Sir2, an NAD-dependent histone deacetylase (HDAC) that binds at the rDNA locus. Although this mechanism of aging appears to be yeast-specific, the longevity function of Sir2 is conserved in at least one multicellular organism, Caenorhabditis elegans (C. elegans). These findings are consistent with the idea that aging is a by-product of natural selection but longevity regulation is a **highly adaptive trait.** Characterizing this and other mechanisms of yeast aging should help identify additional components of longevity pathways in higher organisms.

which describes  ageing a trait

@pgaudet ?

**Comment by srengel** [comment]
ok 'chronological cell aging' annotations all removed. - unassigning myself from this ticket.

(i'll also work my way through the 'replicative cell aging' to remove those.)

**Comment by pgaudet** [comment]
@ValWood 
So, we propose to obsolete 
* GO:0001300 chronological cell aging
* GO:0001323 age-dependent general metabolic decline involved in chronological cell aging
* GO:0010978 gene silencing involved in chronological cell aging
* GO:0001305 progressive alteration of chromatin involved in chronological cell aging 
* GO:0090399 replicative senescence

* GO:1904727 negative regulation of replicative senescence
* GO:1904728 positive regulation of replicative senescence
* GO:1904726 regulation of replicative senescence 

Is this right ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think "replicative senescence" might be OK it's a metazoan cellular process.

It's GO:0001302   replicative cell aging that is the problem. The higher eukaryotic annotations should probably move to the  senescence terms

**Comment by ValWood** [comment]
obsoleting the "replicative senescence" terms would cause an uproar ;)

**Comment by pgaudet** [comment]
Apologies. I meant 

* GO:0001302 replicative cell aging - and children: 
* GO:0001321 age-dependent general metabolic decline involved in replicative cell aging
* GO:0001303 nucleolar fragmentation involved in replicative aging
* GO:0001304 progressive alteration of chromatin involved in replicative cell aging
*  GO:1900062 regulation of replicative cell aging

**Comment by ValWood** [comment]
If there are no objections. But they aren't processes are they?

**Comment by pgaudet** [comment]
I dont know - most annotations are from SGD (with a few from other groups). I can start an annotation review ticket.

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete 'GO:0001300 chronological cell aging' and its children. 

There are 22 EXP annotations. There are no mappings to these terms. These term is not present in any subsets.
Annotation review ticket is here: 
https://github.com/geneontology/go-annotation/issues/3255

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 28th, 2020. Unless objections are received by September 28th, 2020. we will assume that you agree to this change.

Comments may be added to the ticket : #18632

Thanks, Pascale

**Comment by pgaudet** [comment]
Forgot to add: The reason for obsoletion is that this represent an assay (how long the cell lives), not a true BP.

**Comment by pgaudet** [comment]
Will add "Consider: "
GO:0007569 cell aging
GO:0090398 cellular senescence
