### ISSUE TITLE
"actin fusion focus assembly" missing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18630]
GO:1990819    actin fusion focus
A focus at the mating projection tip where the cell wall is degraded during conjugation with cellular fusion. Actin filaments form an aster-like structure from this location. PMID:25825517

therefore 
actin fusion focus assembly (GO:1904600)
The aggregation, arrangement and bonding together of a set of components to form an actin fusion focus.

should be part of
"conjugation with cellular fusion"

**Comment by ValWood** [comment]
HI Harold,

could you add

GO:0000747    conjugation with cellular fusion
as a  part_of parent of
actin fusion focus assembly (GO:1904600)

**Comment by hdrabkin** [comment]
done
