### ISSUE TITLE
Remove inappropriate 2.4.1 and 2.4.2 partial EC xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18646]
Remove partial EC of "2.4.1" (which is for hexosyltransferases, GO:0016758) as an xref on these more specific GO terms:
glucosyltransferase activity (GO:0046527)
UDP-glucose:glycoprotein glucosyltransferase activity (GO:0003980)
lipopolysaccharide-1,6-galactosyltransferase activity (GO:0008921)
9-phenanthrol UDP-glucuronosyltransferase activity (GO:0018715)
1,2-dihydroxy-phenanthrene glycosyltransferase activity (GO:0018718)
lipopolysaccharide-1,5-galactosyltransferase activity (GO:0035496)
indole-3-butyrate beta-glucosyltransferase activity (GO:0052638)
benzoic acid glucosyltransferase activity (GO:0052641)
chondroitin hydrolase activity (GO:0052757)
cytokinin 9-beta-glucosyltransferase activity (GO:0080062)

Remove partial EC of "2.4.2" (which is for pentosyltransferases, GO:0016763) as an xref on this more specific GO term:
imidazoleglycerol-phosphate synthase activity (GO:0000107)

**Comment by hdrabkin** [comment]
Done but RHEA requested for some terms where CHEBI terms are defined 
GO:0052638 requested
RHEA added to GO:0000107

**Comment by hdrabkin** [comment]
RHEA request  for GO:0052638
RHEA:62708 (indol-3-yl)butanoate + UDP-α-D-glucose =
4-(indol-3-yl)butanoyl-β-D-glucose + UDP
It will become publicly available in Release 2020_02 scheduled for April 22.

**Comment by hdrabkin** [comment]
RHEA available and added.
