### ISSUE TITLE
Two metacyc xrefs to remove

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18648]
acetylglucosaminyltransferase activity (GO:0008375)
- remove xref to MetaCyc:2.4.1.223-RXN
(also xref to GO:0001888, which is correct)

galactosyltransferase activity (GO:0008378)
- remove xref to MetaCyc:2.4.1.151-RXN
(also xref to GO:0047276, which is correct (note: 2.4.1.151 was transferred to 2.4.1.87))

**Comment by hdrabkin** [comment]
Done; and RHEA:16221 added to GO:0001888 xref-ed to EC:2.4.1.223
