### ISSUE TITLE
NTR: ATP-sensitive calcium-release channel activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#18649]
I'm requesting  an new term:
ATP-sensitive calcium-release channel activity.
 Add as child of GO:0015278 calcium-release channel activity

This term comes from the activated_by annotation review. Dicty p2x Ca channels need ATP activation. PMID:22736763

**Comment by pgaudet** [comment]
Here you go: 

+[Term]
+id: GO:0140417
+name: ATP-sensitive calcium-release channel activity
+namespace: Enables the transmembrane transfer of a calcium ion from intracellular stores by a channel that opens when a ATP has been bound by the channel complex or one of its constituent parts. {xref="22736763"}
+namespace: molecular_function
+is_a: GO:0015278 ! calcium-release channel activity
+created_by: pg
+creation_date: 2020-01-27T09:22:04Z
