### ISSUE TITLE
Remove EC xref on oligosaccharyl transferase activity (GO:0004576)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18647]
oligosaccharyl transferase activity (GO:0004576)
- remove xref to EC:2.4.99.18 because it's for a more specific reaction than the GO def.

GO def: "Catalysis of the transfer of a oligosaccharyl group to an acceptor molecule, typically another carbohydrate or a lipid."

EC def: Dolichyl diphosphooligosaccharide + [protein]-L-asparagine <=> dolichyl diphosphate + a glycoprotein with the oligosaccharide chain attached by N-beta-D-glycosyl linkage to a protein L-asparagine

**Comment by hdrabkin** [comment]
The rhea also needed to be removed RHEA:22980
Done

**Comment by sjm41** [comment]
Thanks Harold.
