### ISSUE TITLE
rename "protein binding , bridging" as a type of "adaptor?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18655]
currently

molecular adaptor activity
--GO:0030533    triplet codon-amino acid adaptor activity | is_a
--GO:0030674    protein binding, bridging
----GO:0043495    protein membrane adaptor | is_a
----GO:1990756    protein binding, bridging involved in substrate recognition for ubiquitination | is_a
----GO:1990644    microtubule site clamp | is_a
----GO:0019895    kinesin-associated mitochondrial adaptor activity | is_a
----GO:0005483    soluble NSF attachment protein activity | is_a
----GO:0035591    signaling adaptor activity | is_a
----GO:0008093    cytoskeletal adaptor activity | is_a
etc

Would
protein binding, bridging-> protein-macromolecule adaptor (also makes it clearer that the bridging

 is not necessarily between 2 proteins?)

<img width="229" alt="Screenshot 2020-01-27 at 18 10 37" src="https://user-images.githubusercontent.com/7359272/73201184-55169380-4130-11ea-9b69-95f84a5b6afc.png">

This change would focus curators on the "Adaptor" ancestry rather  than the protein binding ancestry.

**Comment by ValWood** [comment]
Also 
GO:1990756    protein binding, bridging involved in substrate recognition for ubiquitination ->
ubiquitin ligase substrate adaptor?

**Comment by ValWood** [comment]
@pgaudet wrote

I cannot exactly remember why the label of this term is still "protein binding, bridging".

The only relevant comment I find is #16721
that states that 'protein binding, bridging' is not limited to protein-protein interactions (it also includes protein-lipid, for example). It may be worth it to have more specific terms, such as 'protein-protein adaptor activity' (which is now a narrow synonym of 'protein binding, bridging' ), and protin-lipid adaptor activity, for example. What do you think ?

**Comment by ValWood** [comment]
We already have a number of more specific terms (see above).
That's partially why the current name seems odd?

**Comment by pgaudet** [comment]
Some but not all of these terms end with 'activity' - should we use that for each term or remove it ?

**Comment by pgaudet** [comment]
I also edited the definition 

OLD def: "The binding activity of a molecule that brings together two or more protein molecules, or a protein and another macromolecule or complex, through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way." [GOC:bf, GOC:mah, GOC:vw]

NEW def: "The binding of a protein that brings together another macromolecule in contact, permitting those molecules to function in a coordinated way. The adaptor can bring together two proteins, or a protein and another macromolecule such as a lipid or a nucleic acid."

**Comment by pgaudet** [comment]
For now I've added 'activity' to all terms, since this is the current convention. 

@thomaspd Do you have a preference ? I know you wanted to simplify some term labels. In this case, it seems clear 'adaptor' is a MF, even without 'activity'. 

Thanks, Pascale

**Comment by ValWood** [comment]
I prefer the shorter labels, but I'm biased because I don't really like the "activity" appendage
