### ISSUE TITLE
many high level missing parents under MF 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18654]
I just noticed that  some molecular function regulators are not under
"molecular function regulator"

e.g
GO:0140110    transcription regulator activity	is_a
GO:0045182    translation regulator activity

**Comment by ValWood** [comment]
Also,
can you be both ?

GO:0098772    molecular function regulator	is_a
GO:0098772    molecular function regulator	regulates

**Comment by pgaudet** [comment]
Do we really have 
> GO:0140110 transcription regulator activity is_a
GO:0045182 translation regulator activity

? or this is just a pasting issue ? 

These two MF are not MF regulators, they regulate a BP. 

I *think* we should have 
GO:0140110 transcription regulator activity
molecular_function
regulates some 'transcription, DNA templated' 

(and same for translation) 

---
I don't understand the second question: 

> can you be both ?

> GO:0098772 molecular function regulator is_a
GO:0098772 molecular function regulator regulates

You mean you see terms that have both those parents ?

**Comment by ValWood** [comment]
Fist one, I must have imagined!

Re the second
> You mean you see terms that have both those parents ?

Yes, but maybe that is OK? closing
