### ISSUE TITLE
GO:0002754   intracellular vesicle pattern recognition receptor signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18679]
meaning of

GO:0002754    intracellular vesicle pattern recognition receptor signaling pathway
Any series of molecular signals generated as a consequence of an intracellular vesicle pattern recognition receptor (PRR) binding to one of its physiological ligands. PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species. PMID:15199967

I haven't come across any "vesicle pattern recognition receptor" if exists needs clarification.  The definition refers to PAMPs so this sounds like a classical pathogen PRR?
What is the intracellular vesicle part of? the plant? I can't figure out how this relates to the receptor  term? (or this definition).

The word "vesicle" does not appear in the cited reference:
https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.0105-2896.2004.0119.x

There are no annotations.

**Comment by ValWood** [comment]
@addiehl 
@mgiglio99 

any ideas?

**Comment by addiehl** [comment]
This: https://www.frontiersin.org/articles/10.3389/fimmu.2017.01075/full
TLR3, TLR7, TLR8, TLR9 all bind their ligands in endosomes.  Endosomes are vesicles.

**Comment by addiehl** [comment]
Also TLR11, TLR12, and TLR13 in mice are endosomal per the paper.

**Comment by ValWood** [comment]
This seems to be an odd axis of classification ? This information would be better captured with "occurs in" endosome.
Also, none to the toll-pathway terms are children of this term,  which means there  multiple ways to describe the same processes => inconsistent annotation and redundancy.

 We are even wondering  if we should specify "intracellular" or "cell surface" in other receptor terms, as these are really components, not  Molecular Functions.

**Comment by ValWood** [comment]
Action:

change to

GO:0002754 intracellular endosomal pattern recognition receptor signaling pathway

**Comment by pgaudet** [comment]
@ValWood Why did you close ?

**Comment by ValWood** [comment]
Ah sorry, not sure. I like closing tickets? (more than opening them!)
