### ISSUE TITLE
Standardize logical definitions for cell division terms

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#18673]
This ticket is to outline the steps needed to standardize the logical definitions for 'cell division' terms in the ontology.  This work will also be used to inform annotation of 'cell division' processes
and make sure that we express this concept consistently across all areas of GO.

See:  http://wiki.geneontology.org/index.php/Ontology_meeting_2020-01-27

- [x] Update existing logical definitions for 'cell division' and child terms to use 'has input', e.g. cell division and 'has input' some cell type @ukemi @vanaukenk 

- [x] Check any changed inferences resulting from this update (i.e. diff) @balhoff 

- [x] If it looks okay, make the changes in the ontology and annotation practice

We will use this example as a pilot for potentially making similar changes to other term defs.

**Comment by ukemi** [comment]
@balhoff Can you create the inference diff for this pull request?

**Comment by balhoff** [comment]
@ukemi I put it in a comment in the PR

**Comment by ukemi** [comment]
Thaks @balhoff. Looks like @vanaukenk and I will have to look at some of these. :(

**Comment by vanaukenk** [comment]
@ukemi Yes, let's take a look at some of the changed parentage - interesting!
Thanks @balhoff

**Comment by ukemi** [comment]
I hypothesize that the differences are due to us removing the asserted parents rather than the has_input change. But that also means that either the original asserted parents were incorrect, the hierarchy in the cell ontology is incorrect, or the logical definitions are not necessary and sufficient. Let's make a time to look at this before I head off on vacation.

**Comment by vanaukenk** [comment]
@ukemi 
Looking over the changes, I think your hypothesis is likely correct.  Let's carve out time to look this over before you go.

**Comment by vanaukenk** [comment]
Merged the changes in and am closing the ticket, but note that a related issue came up wrt classification of neuroblasts and stem cells in the Cell Ontology and we've created a ticket for that here:

https://github.com/obophenotype/cell-ontology/issues/617

What we have in GO right now reflects the current CL hierarchy, which could possibly change.
