### ISSUE TITLE
NTR: heme import into cell /heme via endocytosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18671]
is defined as a "transmembrane term"

but heme improt across the plasma membrane can also occur via non-transmembrane transport (i.e endocytosis)

see:
https://github.com/pombase/curation/issues/2406

**Comment by ValWood** [comment]
Note that we still need a transmembrane transport term for str3

**Comment by ValWood** [comment]
heme transport
--
Definition | The directed movement of heme, any compound of iron complexed in a porphyrin (tetrapyrrole) ring, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore.


needs to be broader, defined as TM transport (transporter or pore),
 but has child
endocytic hemoglobin import

**Comment by ValWood** [comment]
I used
endocytic hemoglobin import

**Comment by pgaudet** [comment]
Is that OK ? This is what I was going to suggest. But does pombe have hemoglobin ???? Or aybe you are annotating something else.

**Comment by ValWood** [comment]
Oh no, I was just about to correct that.  I mean heme, so there isn't a term I can use...

**Comment by deustp01** [comment]
> I used
> endocytic hemoglobin import

That sounds right. A necessary aspect of transport elsewhere is crossing a membrane and endocytosis by itself doesn't accomplish that, so the distinction seems exactly right. (Thinking back here to appropriate words to use to assert that something traverses the nuclear pore.)

**Comment by ValWood** [comment]
@deustp01 I'm annotating pombe so it's heme not hemoglobin ;)

**Comment by ValWood** [comment]
I need a parent? endocytic heme import?

**Comment by ValWood** [comment]
Note to self

IMP | Mourer T et al. (2017) | 
  | IMP | Mourer T et al. (2015)
  | IMP | Normant V et al. (2018)

**Comment by ValWood** [comment]
I think the outcome is
NTR: heme import
NTR: endocytic  heme import
standard def

**Comment by pgaudet** [comment]
References please ?

**Comment by ValWood** [comment]
PMID:28193844

**Comment by pgaudet** [comment]
also changed the term label and def for GO:0020028


-name: endocytic hemoglobin import
+name: endocytic hemoglobin import into cell
-def: "The directed movement into a tissue or a cell or organelle of externally available hemoglobin by receptor-mediated endocytosis." [GOC:mb]
+def: "The directed movement of hemoglobin into a cell by receptor-mediated endocytosis."

I don't think endocytosis happens in organelles - unless you consider endosomes but this is the end of endocytosis that ingested extracellular materials. 

Thanks, Pascale

**Comment by pgaudet** [comment]
New terms: 

+[Term]
+id: GO:0140420
+name: heme import into cell
+namespace: biological_process
+def: "The directed movement of a heme from outside of a cell into a cell. This may occur via transport across the plasma membrane or via endocytosis." [PMID:28193844]
+comment: Created new term, see https://github.com/geneontology/go-ontology/issues/18671.
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005622 ! intracellular
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: transports_or_maintains_localization_of CHEBI:30413 ! heme
+created_by: pg
+creation_date: 2020-01-30T13:10:07Z
+
+[Term]
+id: GO:0140421
+name: endocytic heme import into cell
+namespace: biological_process
+def: "The directed movement into cell of externally available heme by receptor-mediated endocytosis." [PMID:28193844]
+comment: Created new term, see https://github.com/geneontology/go-ontology/issues/18671.
+is_a: GO:0098657 ! import into cell
+intersection_of: GO:0006898 ! receptor-mediated endocytosis
+intersection_of: has_target_end_location GO:0005622 ! intracellular
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: transports_or_maintains_localization_of CHEBI:30413 ! heme
+created_by: pg
+creation_date: 2020-01-30T13:14:02Z
+

**Comment by pgaudet** [comment]
Should "heme assimilation" be a synonym ? Broad for the 3 terms ?

**Comment by ValWood** [comment]
I think it could.
