### ISSUE TITLE
remove comment GO:0080185

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18678]
GO:0080185    JSON
effector-mediated induction of plant hypersensitive response by symbiont
A symbiont process whereby a molecule secreted by the symbiont activates plant effector-triggered immunity (ETI)...

has the comment:
Note that this term should probably be only used to annotate plant pathogens. Evidence of direct recognition of pathogen effectors in animals is currently lacking, see PMID:23411798.

this comment is unnecessary because this is names and defined as a pathogen affecting plants  specific term.

**Comment by pgaudet** [comment]
ok
