### ISSUE TITLE
connecting . GO:0034053 and GO:0080185

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18682]
GO:0034053
Definition 
modulation by symbiont of host defense-related programmed cell death
Any process in which a symbiont modulates the frequency, rate or extent of defense-related programmed cell death in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.
modulation by symbiont of host HR | narrow
modulation by symbiont of host hypersensitive response | narrow

but these narrow synonyms  have their own terms (currently unrelated)
GO:0080185    effector-mediated induction of plant hypersensitive response by symbiont
Definition 
A symbiont process whereby a molecule secreted by the symbiont activates plant effector-triggered immunity (ETI) signalling and the subsequent activation of a plant hypersensitive response to induce necrosis. In the plant, ETI involves the direct or indirect recognition of an effector protein by the host. for example through plant resistance receptor or R proteins. PMID:16497589 PMID:22241993 PMID:23411798 PMID:27641772

There are 9 annotations to 
GO:0034053 modulation by symbiont of host defense-related programmed cell death

Some are effectors of HR in plants  and should move down to  GO:0080185 
Some are Effectors from human pathogens, so this term is required as a parent to the plant term.

**Comment by ValWood** [comment]
Hi @pgaudet  did you have a question about this one?
It looks straightforward?

**Comment by pgaudet** [comment]
Do you mean 
GO:0080185 effector-mediated induction of plant hypersensitive response by symbiont
should be a child of 

GO:0034053 modulation by symbiont of host defense-related programmed cell death

? 

Thanks, Pascale

**Comment by pgaudet** [comment]
And, are the two synonyms on the right term ?

**Comment by pgaudet** [comment]
I mean those 2: 
modulation by symbiont of host HR | narrow
modulation by symbiont of host hypersensitive response | narrow

**Comment by ValWood** [comment]
> Do you mean
GO:0080185 effector-mediated induction of plant hypersensitive response by symbiont
should be a child of
GO:0034053 modulation by symbiont of host defense-related programmed cell death

Yes.
plant hypersensitive response  is a type of programmed cell death

**Comment by ValWood** [comment]
I mean those 2:
modulation by symbiont of host HR | narrow
modulation by symbiont of host hypersensitive response | narrow

These synonyms would be better as "exact" synonyms of the more specific terms once the missing parentge is created.

**Comment by pgaudet** [comment]
ok

**Comment by pgaudet** [comment]
@ValWood 
I dont think I should put the 'modulation' as synonyms for 'induction'.


The parentage is OK. 

I think this is all good. 

Maybe you want to confirm once you can see the latest version of the ontology ?

**Comment by ValWood** [comment]
OK yes I will check It's getting confusing ;)

**Comment by pgaudet** [comment]
OK now
