### ISSUE TITLE
NTR: effector-mediated modulation of host process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18689]
PHI-base require an
NTR effector-mediated modulation of host process by symbiont

as an ancestor to
GO:0140415   effector-mediated modulation of host defenses by symbiont

because quite  few of the effector-mediated processes we are looking at are not altering host defenses. For example they might enter the chloroplast and interfere with the host etc

(note: I suspect that most of the pathogen host-interaction terms under 
GO:0044414   suppression of host defenses by symbiont 
are effector-mediated, but this wasn't clear from the terms, @mgiglio99  might be able to help here)

**Comment by pgaudet** [comment]
Done - duplicate of #18605

Thanks, Pascale
