### ISSUE TITLE
regulation of spatial distribution of DSB formation involved in recombination

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18691]
We have a community curation-based request for a new BP term for regulation of where double-strand breaks form in meiotic recombination.

papers: looking at PMID:30217891; also skimmed review PMID:25324213

id: GO:new
name: regulation of spatial distribution of meiotic DNA double-strand break formation involved in reciprocal meiotic recombination
def: Any process that modulates the distribution of sites along the chromosome where meiotic DNA double-strand break formation takes place as part of reciprocal meiotic recombination.
synonym: "spatial regulation of meiotic DNA double-strand break formation involved in reciprocal meiotic recombination" EXACT?(if so, this could be the term name)
synonym: "regulation of spatial distribution of meiotic DSB formation involved in reciprocal meiotic recombination" EXACT
synonym: "crossover interference" RELATED [PMID:30217891]
synonym: "DSB interference" RELATED [Antonia Lock - GOC:al?]
is_a: GO:1905261 ! regulation of meiotic DNA double-strand break formation involved in reciprocal meiotic recombination

I'm not sure what to suggest for a logical def - this regulates  GO:0010780 ! meiotic DNA double-strand break formation involved in reciprocal meiotic recombination, but the differentia from the parent GO:1905261 is that the regulation is "where" rather than "how much".

**Comment by ValWood** [comment]
Why is "DSB interference" related and not exact? Isn't this what the process has need called?
Or does it have other meanings?

**Comment by mah11** [comment]
> Why is "DSB interference" related and not exact?

It wasn't totally clear to me that "DSB interference" is a process, as opposed to the observed phenomenon that results from the spatial regulation process (i.e. more phenotype-ish than process).

**Comment by ValWood** [comment]
OK, I was just curious...

**Comment by mah11** [comment]
i.e. just what you said in https://github.com/geneontology/go-ontology/issues/18715#issuecomment-580893577 ... ;)

**Comment by ukemi** [comment]
I don't think we can do a logical def, but the term can surely be added.

**Comment by mah11** [comment]
thanks!
