### ISSUE TITLE
Possible unnecessary parents in  symbiont branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18696]
Should these be "regulation of the ACTUAL host process"  (like programmed cell death)  for example ? I thought not?  Otherwise they become annotated to the host processes.

<img width="1035" alt="Screenshot 2020-01-29 at 16 59 52" src="https://user-images.githubusercontent.com/7359272/73379023-6939cc80-42b9-11ea-9128-c2bef1b72cba.png">

**Comment by ValWood** [comment]
Can we discuss on Friday? I might not have this right...

**Comment by ValWood** [comment]
I will look at these terms again once changes  filter through

**Comment by pgaudet** [comment]
@ValWood will look at this again when the other changes we made this week and see if this is still an issue.

**Comment by ValWood** [comment]
This is OK. There are lots of possibly unnecessary parents, but I don't think they are incorrect.

I opened a ticket for the missing parentage  of "cell killing by symbiont" to symbiotic process. Otherwise we are done here.
