### ISSUE TITLE
rename GO:0033661 | suppression by symbiont of defense-related host reactive oxygen species production

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18697]
GO:NEW  effector-mediated suppression of ETI signalling by symbiont
exact : effector-mediated suppression of effector-triggered immunity signalling by symbiont
exact : effector-mediated suppression of defense response signaling pathway, resistance gene-dependent by symbiont

A process mediated by a molecule secreted by a symbiont that results in the suppression of host effector-triggered immunity signalling (i.e. GO:0009870). The host is defined as the larger of the organisms involved in a symbiotic interaction. 

descendant of
GO:0140403   effector-mediated suppression of host innate immune response by symbiont

this completes the terms we need currently to capture most  of the pathogen effects on plant signalling

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
Hi @CuzickA  this was the outstanding missing  term we discussed  today . Can you add some of the references ?

**Comment by pgaudet** [comment]
@ValWood 
I don't understand what the "(GO:0009870 defense response signaling pathway, resistance gene-dependent)." is doing in the definition- are you saying this new term is_a 'GO:0009870 defense response signaling pathway, resistance gene-dependent'? 


Thanks, Pascale

**Comment by pgaudet** [comment]
Or maybe you are saying that host effector-triggered immunity = GO:0009870 defense response signaling pathway, resistance gene-dependent ?

**Comment by ValWood** [comment]
> Or maybe you are saying that host effector-triggered immunity = GO:0009870 defense response signaling pathway, resistance gene-dependent ?

Yes I was (is exact synonym)

But this is all looking too confusing!

Actually, @CuzickA  this seems a bit wrong. We have been calling this process in plants "effector-triggered immunity"
and the plant term https://www.ebi.ac.uk/QuickGO/term/GO:0009870
has effector-triggered immunity | exact
This seems incorrect. @CuzickA should this be related?

@CuzickA Can you  add to this ticket the processes which are referred to as "effector-triggered immunity" from the pathogen or and plant perspective?


This term seems like we are trying to describe cases where a pathogen effector  ACTIVELY supresses the output of GO:0009870  but I can't recall an example of this?  Anyway this doesn't seem to be right, but I edited the request to use the primary GO terms to make it less ambiguous.

**Comment by ValWood** [comment]
I reedited the original comment.

@CuzickA  if this looks OK we can go ahead and add.

This will be for when the pathogen effector has an evolved function to suppress the plant ETI 
(i.e gene for gene)

If we need a term that is not signaling we can request that later.
I can find some references from our in progress sessions.

**Comment by ValWood** [comment]
This doesn't seem to be   quite right. The  gene-for-gene effector  (in biotrophs) evolves to avoid ETI not to suppress it? It isn't supressed- it just isn't activated?

@CuzickA ?

**Comment by ValWood** [comment]
@CuzickA  I can't find the example for this term.

thanks
Val

**Comment by CuzickA** [comment]
Hi @ValWood I think we were considering using this term for PMID:31804478 An effector protein of the wheat stripe rust fungus targets chloroplasts and suppresses chloroplast function.
 
Bax chemistry had been added to the tobacco leaf to trigger PCD defense and transient overexpression of pathogen 'Pst_12806' within the leaf abolished the PCD/HR. I'm not sure whether we decided on the best way to curate this yet?

**Comment by ValWood** [comment]
Oh yes.

So is this correct though.
This is the summary.

The pathogen protein PSTG_12806  binds to the host  TalSP. This  has a number of consequences 
inhibits photosynthesis, but the 'evolved function" is the attenuation of ROS production to inhibit defense signalling.


<img width="749" alt="Screenshot 2020-02-03 at 16 19 10" src="https://user-images.githubusercontent.com/7359272/73671779-8d275480-46a3-11ea-9584-eb8b5af65437.png">

But I don't think this can be described as PTI or ETI signalling ?

For this we can use

GO:0033661 | suppression by symbiont of defense-related host reactive oxygen species production

but we don't capture the fact that this is effector-mediated process for the pathogen  which is critical for PHI-base
(it is still unclear to me if we have any examples of interference with host defenses which are not effector mediated? @CuzickA  can you think of (evolved) examples we have annotated that are not effector mediated?)

**Comment by ValWood** [comment]
There is only a single annotation to 

GO:0033661 | suppression by symbiont of defense-related host reactive oxygen species production

and this IS effector mediated.

The current data suggest that the mycobacterial effector Eis regulates eukaryotic cell function through the direct modification of target proteins, effected by its N-acetyltransferase domain.

Instead of adding the requested term, could we *instead*

rename
GO:0033661 | suppression by symbiont of defense-related host reactive oxygen species production

to
GO:0033661 | effector-mediated suppression of defense-related host reactive oxygen species production by symbiont
def revise to
A process mediated by a molecule secreted by a symbiont that results in the suppression of production of reactive oxygen species as part of the innate immune response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

and add the parent
GO:0140415    effector-mediated modulation of host defenses by symbiont
actually I think there will be a more appropriate specific child (some other terms were linked up to this parent today)

@CuzickA  I don't think we should request 
 the suppression of ETI signalling until we have a clear example of this as an evolved function

**Comment by pgaudet** [comment]
Parent: change label
- [ ]  GO:0052164 modulation by symbiont of defense-related host reactive oxygen species production
 to 'defense to host-produced reactive oxygen species'

**Comment by pgaudet** [comment]
The reason for this change in labels is that the the symbiont doesn't necessarily block the produsction of ROS; but overall levels of ROS decrease, for example by the action of superoxide dismutase.
