### ISSUE TITLE
"disruption" terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18692]
In most of these  terms, the word "disruption" is used in lots of different contexts

1.

GO:0044004    disruption by symbiont of host cell
Definition (GO:0044004 GONUTS page)
Any process in which an organism has a negative effect on the functioning of the host's cells. The host is defined as the larger of the organisms involved in a symbiotic interaction.
- [ ] what is a "negative effect on the functioning of the host's cells?"

2.
- [ ] one descendant is
GO:0044054    rounding by symbiont of host cells?  
(1 annotation, phenotype?)

3.
- [ ] another descendant  is
GO:0044607   disruption by symbiont of host endothelial cells
Biological Process
Any process in which an organism has a negative effect on the functioning of the host's endothelial cells.
NO annotations
NO reference

4.
GO:0044661    disruption by virus of host cell
has a lot of annotations but some of the children look dubious

- [ ] . For example
GO:0098932   disruption by virus of host cell wall peptidoglycan during virus entry
-> degradation of host cell wall peptidoglycan during virus entry?

- [ ] 
Definition (GO:0098932 GONUTS page)
A process carried out by a virus that breaks down peptidoglycans in the cell wall of its host during viral entry.
Seems that the parentage of "viral entry into host" would be sufficient?

- [ ] GO:0044662    disruption by virus of host cell membrane
A process by which a virus has a negative effect on the functioning of a host cellular membrane.

I don't understand this one at all what is "negative effect on the functioning of a host cellular membrane"?
5 annotations CACAO
but looking at the paper it should probably merge into

GO:0044659    cytolysis by virus of host cell
Definition (GO:0044659 GONUTS page)
The killing by a virus of a cell by means of the rupture of cell membranes and the loss of cytoplasm. PMID:26728778

it's  another way of saying the same thing

i.e I think most of the high level "disruption terms" can be removed  as most of the meaningful terms have alternative sensible parents...

.

**Comment by pgaudet** [comment]
- [] GO:0044607 disruption by symbiont of host endothelial cells 
should be obsoleted and use an extension

**Comment by pgaudet** [comment]
Points 1, 3 and 4 -> see ticket #18719
Point 2: see ticket #18720
