### ISSUE TITLE
TPV: GO:0039633  killing by virus of host cell

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18693]
GO:0039633  killing by virus of host cell
Definition (GO:0039633 GONUTS page)
Any process mediated by a virus that results in the death of a cell in the host organism.

has the parent

GO:0019048    JSON
modulation by virus of host morphology or physiology
Biological Process
Definition (GO:0019048 GONUTS page)
The process in which a virus effects a change in the structure or processes of its host organism.

That doesn't look right?

**Comment by pgaudet** [comment]
Removed parents 'modulation by virus of host morphology or physiology' and 'disruption of cells of other organism' from all the 'cell killing' terms.
