### ISSUE TITLE
MP GO:0080185 | effector-mediated induction of plant hypersensitive response by symbiont |

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18694]
GO:0080185 | effector-mediated induction of plant hypersensitive response by symbiont |
A symbiont process whereby a molecule secreted by the symbiont activates plant effector-triggered immunity (ETI) signalling and the subsequent activation of a plant hypersensitive response to induce necrosis. In the plant, ETI involves the direct or indirect recognition of an effector protein by the host. for example through plant resistance receptor or R proteins. PMID:16497589 PMID:22241993 PMID:23411798 PMID:27641772

should be a descendant of
GO:0034053 | modulation by symbiont of host defense-related programmed cell death |  

i.e. HR induces PCD to cause necrosis.

**Comment by pgaudet** [comment]
Are all the parents for GO:0080185 OK ? 

# 'effector-mediated modulation of host innate immune response by symbiont'
# 'induction by symbiont of host innate immune response'
# 'modulation by symbiont of host defense-related programmed cell death' (NEW)
# 'modulation by symbiont of host resistance gene-dependent defense response'
# 'positive regulation by symbiont of host programmed cell death'

Thanks, Pascale

**Comment by ValWood** [comment]
I made a couple of changes to the def to mirror the existing GO term (and remove the ETI from the def, see below)

GO:0080185 | effector-mediated induction of plant hypersensitive response *signalling* by symbiont |
A symbiont process whereby a molecule secreted by the symbiont activates plant ~effector-triggered immunity (ETI)~ . **defense response signaling pathway, resistance gene-dependent  GO:0009870** ~subsequent activation of~ **in order to activate**  a plant hypersensitive response to induce necrosis. In the plant, ~ETI~ this process involves the direct or indirect recognition of an effector protein by the host  for example through plant resistance receptor or R proteins. PMID:16497589 PMID:22241993 PMID:23411798 PMID:27641772

change 
effector-triggered immunity | exact
to 
effector-triggered immunity | related
I now realise Effector-triggered immunity (ETI) is a property of the innate immune system, not a process
so this is the wrong phrase to use in exact synonyms. I will open a ticket to fix any other examples.

The way this term is defined to include the signalling and the response all of the above relations are true.

I have done it this way because the way this  most commonly occurs is that  the fungal effector  binds to the host receptor to induce the  signalling in order to induce cell death.
From the fungal perspective this is the *desired* outcome. It is  constructed  a little bit differently than the other terms  so that a single term will cover all of the process (rather than annotating to regulation of signalling, regulation of cell death etc)

I'm not completely sure this is ideal but it is a term  we will use a lot, and it captures everything we want to say.
One of the reasons we had to do it this way is that we don't really know anything about what happens between the receptor binding and the cell death output. It's a big black box.
Because of this, at the moment we aren't quite sure if the receptor/signalling pathway are specific for HR or regulate other processes too.

Most of  the experiments we are annotating for necrotrophic fungi interacting with plants will use this term.

**Comment by ValWood** [comment]
Sorry about this, I'm trying to cover all bases....

**Comment by pgaudet** [comment]
- [x] New definition (slightly edited form your suggestion https://github.com/geneontology/go-ontology/issues/18694#issuecomment-580293388) : "A symbiont process in which a molecule secreted by the symbiont activates a resistance gene-dependent defense response signaling pathway in the plant host, in order to activate a hypersensitive response to induce necrosis. In the plant, this process involves the direct or indirect recognition of the symbiont effector protein for example through plant resistance receptor or R proteins (or R genes)."
- [x] changed all 'exact' synonyms containing 'ETI' to 'related'

Thanks, Pascale
