### ISSUE TITLE
MP: GO:0140404 | effector-mediated modulation of host innate immune response by symbiont

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18695]
GO:0140404 | effector-mediated modulation of host innate immune response by symbiont |  

should be a descendant of
GO:0140415 | effector-mediated modulation of host defenses by symbiont

**Comment by ValWood** [comment]
I still don't see this parentage? Shoud I see it yet?

**Comment by pgaudet** [comment]
Well I see it in Protégé 
The snapshot release has not worked since Jan 28 

You can always look at the latest date the ontology was released here: http://snapshot.geneontology.org/metadata/release-date.json
