### ISSUE TITLE
GO:0047594 contains several invalid Xref IDs

### ISSUE THREAD

**Issue by althonos** [geneontology/go-ontology#18701]
Hi there !

A bunch of unfortunate spaces got inserted in several cross-references in the `GO:0047594` term:

```
[Term]
id: GO:0047594
name: 6-beta-hydroxyhyoscyamine epoxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: (6S)-6-hydroxyhyoscyamine + 2-oxoglutarate + O(2) = CO(2) + H(2)O + H(+) + scopolamine + succinate." [EC: 1.14.20.13, RHEA:12797]
synonym: "(6S)-6-hydroxyhyoscyamine,2-oxoglutarate oxidoreductase (epoxide-forming)" EXACT [EC: 1.14.20.13]
``` 

Both cases of EC numbers should be `EC:1.14.20.13`, without a space after the colon, with regards to the OBO 1.4 syntax.

**Comment by pgaudet** [comment]
Thanks for reporting this @althonos

**Comment by althonos** [comment]
Thanks @Melnorme1984 for the heads up about this as well
