### ISSUE TITLE
Remove definition xrefs containing 'http://www.chem.qmul.ac.uk' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18703]
Those get redirected to the general home page of the Chemistry program of Queen Mary University of London - that doesn't help define terms. 

https://www.qmul.ac.uk/undergraduate/coursefinder/courses/2020/chemistry//#p18

**Comment by mah11** [comment]
Should you need it for anything, I found the current URL for the Enzyme Nomenclature page:

https://www.qmul.ac.uk/sbcs/iubmb/enzyme/

**Comment by pgaudet** [comment]
Thanks @mah11 !!

**Comment by pgaudet** [comment]
We usually link to https://enzyme.expasy.org/

Should we also use https://www.qmul.ac.uk ??
