### ISSUE TITLE
small synonym fix GO:0140403

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18707]
remove
suppression of effector-triggered immunity (PTI) | exact

a) it would be ETI
b) this  term is not specific for either ETI or PTI suppression

**Comment by pgaudet** [comment]
should I change to BROAD ? or just remove ?

**Comment by pgaudet** [comment]
I fixed suppression of effector-triggered immunity (PTI) -> ETI yesterday (#18680)

You want it removed, or both ETI and PTI be added as broad synonyms ?

**Comment by ValWood** [comment]
Hang on with this one.
I will come back to it this afternoon.

I want to check a couple of things ......

**Comment by ValWood** [comment]
OK this should be

suppression of effector-triggered immunity (**E**TI) | ~exact~ broad

BUT
We we don't  need this synonym, because a term  meaning  exactly this will be created, but that is in another ticket.

**Comment by pgaudet** [comment]
@ValWood 

I am not following 
synonym: "suppression of effector-triggered immunity (ETI)" EXACT []

**Comment by ValWood** [comment]
There is  plant term for  ETI sitgnalling , see https://github.com/geneontology/go-ontology/issues/18733

We don't have a plant term for just "effector-triggered immunity". I don't think it would be appropriate to have such a term from the plant perspective because it is too broad. However, it is the term the pathogen community use most commonly.

Also note that 
GO:0140403 is BROADER than just signalling. It refers to the plant  suppressing the immunity during signalling, or in any of the downstream outputs. Often we cannot be more precise than this. We only know that ETI is suppressed.

(@CuzickA is this the case, all of the suppression of ETI have been through the receptor, do we have other examples)?
