### ISSUE TITLE
Update definition of  GO:0002144 - cytosolic tRNA wobble base thiouridylase complex

### ISSUE THREAD

**Issue by sandraorchard** [geneontology/go-ontology#18712]
If you change the definition from "A complex of two proteins involved in the thiolation of U34 in glutamate, lysine, and glutamine tRNAs of eukaryotes."  to ""A complex of two proteins involved in the thiolation of uridine 34 (U34) of tRNAs decoding two-family box triplets." then it works for prokaryotes too, which is what I need it for. PMID: 17062623 if you want to check it out.

**Comment by hdrabkin** [comment]
Done.
