### ISSUE TITLE
obsoletion GO:0044007    dissemination or transmission of symbiont from host

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18714]
follow in from

https://github.com/geneontology/go-ontology/issues/18601

also the  terms
GO:0044008    JSON
dissemination or transmission of symbiont from host by vector
Biological Process
Definition (GO:0044008 GONUTS page)
The movement of an organism from one host to another (or another place in the environment) by means of a third organism (often an insect or other animal). The host is defined as the larger of the organisms involved in a symbiotic interaction.

I'm not sure how that could be sensibly used in annotation as defined.

and
GO:0044007    dissemination or transmission of symbiont from host
The movement of an organism from a host to another host or from a host to another place in the environment. The host is defined as the larger of the organisms involved in a symbiotic interaction.

the scope of this seems to huge?

(there are only 4 EXP after the viral term is dealt with)

It is used for things like
MAP kinase kinase 1 (MKK1) is essential for transmission of Trypanosoma brucei by Glossina morsitans.

These grew normally in culture and were able to establish midgut infections in tsetse at normal rates and intensities, but were incapable of colonising the salivary glands. Transformation of null mutants with an ectopic copy of MKK1 enabled parasites to complete the life cycle in tsetse and infect mice. This is the first example of a gene that is indispensable for transmission of T. brucei. 

 It also raises the possibility that activating the MKK1 signalling cascade in vitro might trigger the differentiation and proliferation of life-cycle stages of T. brucei that are currently refractory to culture.

etc....

**Comment by pgaudet** [comment]
Duplicate - already done see #18601
