### ISSUE TITLE
MP: GO:0099046    clearance of foreign intracellular nucleic acids

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18727]
logically
GO:0099046    clearance of foreign intracellular nucleic acids

should be a descendant of
GO:0098542    defense response to other organism

?

**Comment by ValWood** [comment]
Ah no, not necessarily

**Comment by ValWood** [comment]
Except

def
A defense process that protects an organism from invading foreign DNA.

so it should...

**Comment by pgaudet** [comment]
Also changed def to 'A defense process that protects an organism from DNA or RNA from an invading organism.' 

Is that OK ?

**Comment by pgaudet** [comment]
I think I should also merge 

GO:0044356   clearance of foreign intracellular DNA by conversion of DNA cytidine to uridine
into GO:0099046 clearance of foreign intracellular nucleic acids
since this represents a MF. 

Thanks, Pascale

**Comment by pgaudet** [comment]
GO:0044356 clearance of foreign intracellular DNA by conversion of DNA cytidine to uridine

1 annotation: 


  | APOBEC3A | DNA dC->dU-editing enzyme APOBEC-3A |   | clearance of foreign intracellular DNA by conversion of DNA cytidine to uridine |   | UniProt | Homo sapiens | IDA |   | apolipoprotein b pthr13857 | protein |   | PMID:20062055
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
Yes to both
