### ISSUE TITLE
possible obsoletion: GO:0075048 cell wall strengthening in symbiont involved in entry into host

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18725]
GO:0075048    cell wall strengthening in symbiont involved in entry into host
A process in which the cell wall of the symbiont is strengthened or thickened during penetration into the body, tissues, or cells of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

I'm not sure that we need this term? It has no definition or annotations or reference.
It would be useful to know why the term was added.

In fungi appressorium form for entry into host and this  process has it's own whole branch:
https://www.ebi.ac.uk/QuickGO/term/GO:0075016
Cell wall  thickening is part of this process, but this seems to be a quite specific high-level term for a process  where we don't have much mechanistic information.

"An appressorium is a specialized cell typical of many fungal plant pathogens that is used to infect host plants. ... As the appressorium matures, it becomes firmly attached to the plant surface and a dense layer of melanin is laid down in the appressorium wall, except across a pore at the plant interface."

(Note: this might not be quite right because *appressoria* seem to be alternatively described as cell types and  cellular structures, I am following up on this for another non-GO issue)

Unless this has any obvious use for bacteria  @mgiglio99 ? in which case it can be refined, referenced and better positioned, I propose obsoletion.

Once this process is required for annotation it can be correctly defined, referenced and positioned.

**Comment by mgiglio99** [comment]
I don't know of any bacterial examples.
I agree - seems fine to get rid of it for now.

**Comment by pgaudet** [comment]
Will do as part of #18726
