### ISSUE TITLE
GO:0090648    response to environmental enrichment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18728]
I was looking at this term  because I was trying to figure out exactly what the parent
GO:0009605  response to external stimulus
included

GO:0090648    response to environmental enrichment
Definition (GO:0090648 GONUTS page)
Any process that results in a change in state or activity of an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of the provision of a combination of complex inanimate and social stimulations in the organism's housing environment. PMID:23644055 PMID:25934034

The definition didn't help so I looked at the papers for the 2 annotations:

i)  increase in basal dopaminergic signalling 
http://europepmc.org/article/MED/17487225

http://europepmc.org/article/MED/23644055
ii) The current study examines transcriptional responses of key ER stress target genes subsequent to psychological stress or cocaine. Rats were subjected to acute or repeated restraint stress or cocaine treatment and mRNA was isolated from dorsal striatum, medial prefrontal cortex and nucleus accumbens brain tissue. ER stress gene mRNA expression was measured using quantitative polymerase chain reaction (PCR) and RNA sequencing. Restraint stress and cocaine-induced transcription of the classic ER stress-induced genes (BIP, CHOP, ATF3 and GADD34) and of two other ER stress components x-box binding protein 1 (XBP1) and ATF6. In addition, rats living in an enriched environment (large group cage with novel toys changed daily).
......However, environmental enrichment, a paradigm that produces protective addiction and depression phenotypes in rats, attenuated the rapid induction of ATF3 and GADD34 after restraint stress.

"environmental enrichment" seems to be  part of the experimental set up not the process

**Comment by pgaudet** [comment]
Well, this seems to be 'something': 
https://en.wikipedia.org/wiki/Environmental_enrichment

**Comment by ValWood** [comment]
It sounds like an 'environmental condition' ?

Anyway "response to" doesn't seem a great way to describe these, but close if you think it's OK...
