### ISSUE TITLE
fix synonym relation  in GO:0009870

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18733]
follow on from https://github.com/geneontology/go-ontology/issues/18707

GO:0009870   defense response signaling pathway, resistance gene-dependent
this is the plant term that means "ETI signalling"

I don't know if it is the best name based on current thinking, but it is the historical name. I can ask about this at the PHI-Base RGA unless anyone  can add any clarity? the existing synonym
effector-triggered immunity exact
needs to be fixed to 
effector-triggered immunity signalling exact

ETI is much broader  than just "signalling" but my understanding is that this term would be used for any of the R-genes (receptors), and any downstream signalling (I have not yet seen any papers on the downstream signalling, but many effectors have been studied). My understanding is that these probably signal through a common pathway?

@CuzickA  (could you also tag Kim H-K, I can't locate here GIt-HUb)
@tberardini

**Comment by ValWood** [comment]
Also add
effector-triggered immunity (broad)
effector triggered immunity (broad)

(really hard to find these terms with string searches, these are more likely to match exactly what people type so will be more highly weighted)

**Comment by pgaudet** [comment]
Changed 
-synonym: "effector-triggered immunity" & effector-triggered immunity" 
from EXACT to BROAD 

Added
+synonym: "effector-triggered immune signaling" EXACT []
(instead of 'immunity signaling') 

OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes. Once the changes filter through and I fix my sessions I will double-check that everything looks sensible.
