### ISSUE TITLE
Is this term a  required? GO:0009814   defense response, incompatible interaction 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18738]
GO:0009814   defense response, incompatible interaction
Definition 
A response of a plant to a pathogenic agent that prevents the occurrence or spread of disease.

How does this  term differ from its parent "innate immune response"
(other than being plant specific?)

if this term is required, it should probably be renamed plant innate immune response?
Or defined more precisely.

However note that a LOT of plant  immune terms which would fit this definitions are not under "GO:0009814   defense response, incompatible interaction"

@tberardini

**Comment by ValWood** [comment]
Refers to the outcome of the process (i.e whether disease is observed).
If disease is not observed the interaction is "incompatible"
This isn't about the process per se. A particular interac tion can be "incompatible" for a particular pathogen gene.

Is an outcome of a process i.e  whether a disease can be caused
Example processes could be:
Hypersensitive response,
Lignification,
Activation of PTI or ETI signalling

but it does not include these processes 




Can we merge?

**Comment by ValWood** [comment]
@tberardini  any thoughts on this?

**Comment by tberardini** [comment]
@lreiser and @ebakker2 Can you please have a look at this issue and comment?

**Comment by lreiser** [comment]
So I think Val is right and we should revisit this part of the ontology apparently the last time it was really given a look was when Suparna Mundodi was at TAIR and the whole plant-pathogen issue was reviewed.

So I like the idea of having a 'plant type' innate immune response term

>Innate immune response
>>[is a] (plant type) innate immune response
>>>[is a] (plant type) pattern triggered immunity [PTI]
>>>[is a] (plant type) effector triggered immunity [ETI]
>>>[is a] systemic acquired resistance

But then we also have a lot of terms that are children of this
GO:0009814 defense response, incompatible interaction
that mostly are addressing the type of pathogen (fungal, bacterial, protozoan) which also includes specificity that probably doesn't belong in the GO term.

**Comment by ValWood** [comment]
> But then we also have a lot of terms that are children of this
GO:0009814 defense response, incompatible interaction
that mostly are addressing the type of pathogen (fungal, bacterial, protozoan) which also includes specificity that probably doesn't belong in the GO term.


@lreiser You are. right, I have been moaning about these too ;)
There are too many ways to describe the same process, so we have confusion and inconsistency.
it is getting clearer though !

**Comment by ValWood** [comment]
defense response, incompatible interaction
merge into parent -> innate immune response

systemic acquired resistance + regulation terms
->make a direct child of innate immune response
(currently grandchild) Q check is this all innate?

jasmonic acid and ethylene-dependent systemic resistance ->make a direct child of innate immune response

jasmonic acid and ethylene-dependent systemic resistance, ethylene mediated signaling pathway->make a direct child of innate immune response

systemic acquired resistance, salicylic acid mediated signaling pathway ->make a direct child of innate immune response

response to jasmonic acid stimulus involved in jasmonic acid and ethylene-dependent systemic resistance ->make a direct child of innate immune response

**Comment by ValWood** [comment]
This leaves the following

(67) | defense response to fungus, incompatible interaction
-- | --
+ | − | (55) | defense response to bacterium, incompatible interaction
+ | − | (7) | regulation of defense response to bacterium, incompatible interaction
+ | − | (5) | positive regulation of defense response to bacterium, incompatible interaction
+ | − | (3) | negative regulation of defense response to bacterium, incompatible interaction
+ | − | (3) | regulation of defense response to fungus, incompatible interaction
+ | − | (3) | response to jasmonic acid stimulus involved in jasmonic acid and ethylene-dependent systemic resistance
+ | − | (1) | defense response to protozoan, incompatible interaction


These have 2 parents one to "defense response to blah and one to incompatible interaction"

If we merge we will lose one of these axis.

Alternatively, we could create terms "innate immune response to blah", but personally this would mean expanding every term under these branches to include all of the different organism classes. This doesn't seem practical.

We could merge with "innate immune response" and inform the providers that if they still want "in response to organism x " they will need to annotate concurrently?

**Comment by ValWood** [comment]
If we go with option 2.
Contributors of the ones which would need reviewing to add "defense response to fungus" etc
@lreiser most are TAIR, would this be OK with you?


+ | − | (101) | TAIR
-- | -- | -- | --
+ | − | (27) | UniProt
+ | − | (5) | AgBase
+ | − | (1) | CACAO
+ | − | (1) | RGD
+ | − | (1) | TIGR

**Comment by lreiser** [comment]
@ValWood just 101? Sure- I can handle it

**Comment by ValWood** [comment]
@lreiser  would you prefer the existing term to merge into 
"defense response to fungus" or "innate immune response"
or @pgaudet  should we create the "innate immune response to fungus" terms? 

The the "innate immune response to fungus" approach  worries me because it would need to be replicated through the whole branch for every term for  virus, bacteria, fungi, oomycete etc.... it doesn't seem scalable.
Extensions would seem to be a much better option here (terms could even have a comment, consider extending this term with "defense response to blah)

Personally, I don't see why the "response to species"  is required if people routinely follow best practice capture the taxon in the dual taxon field. Maybe this should be enforced for this branch? That way, the annotation would become more consistent and the data could be mined more precisely.  Also, usually  a specific 'molecule' or pattern that is recognised (i.e lipid, carbohydrate) , not a 'species'.

Could you ask @thomaspd  about this next week? I could chat about  it if you like.

@lreiser do you want to wait until we chatted about the "response to species" terms before you do anything?

**Comment by ValWood** [comment]
This ticket is a duplicate of
https://github.com/geneontology/go-ontology/issues/18739
I suggest we go ahead and merge
GO:0009814 defense response, incompatible interaction
into "defense response"

There is a whole other argument about the "defense response to" terms  but that won't be adressed in this ticket.

I will raise "defense response to" as a GO meeting item.

**Comment by ValWood** [comment]
I'll close this one as duplicate so please refer to 
#18739

**Comment by pgaudet** [comment]
This ticket here has more information. I closed the other one.
