### ISSUE TITLE
GO:0002252    immune effector process (potentially term merge)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18737]
GO:0002252    immune effector process

Definition 
Any process of the immune system that can potentially contribute to an immune response.

how does this differ from:

GO:0006955    immune response
Any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat.

?

**Comment by ValWood** [comment]
Note that this has a large variety of descendants including plant and animal immune responses.

**Comment by ValWood** [comment]
@addiehl 
@mgiglio99 
any ideas?

**Comment by ValWood** [comment]
for example it has
i) defense response to virus (but not fungi or bacteria)
ii) a random selection of plant responses:
GO:0009864    induced systemic resistance, jasmonic acid mediated signaling pathway | is_a
GO:0009866    induced systemic resistance, ethylene mediated signaling pathway
iii) Some animal processes
GO:0002443    leukocyte mediated immunity
GO:0006956    complement activation
iv)  Some non immune defenzse mechanisms (i.s this seems not to be immune system?)
GO:0035010    encapsulation of foreign target

**Comment by addiehl** [comment]
Why?
1.  Immunologists typically refer to the activation and the effector stages of the immune responses. Immunologists talk about various specific biological processes as being types of effector activities that are part of the immune response.

2.  The 'immune effector process' hierarchy was structured as subclasses of 'immune system process'.  The idea was to provide a parts list of immune effector processes that could be part of various subtypes of immune response.

As for "for example it has"
i) not sure, but I think I made this choice because all defense responses to viruses involve innate or adaptive immune responses, but this was not necessarily true for defense responses to viruses or bacteria
ii)  these plant terms were moved under 'immune effector process' because they are effector processes of the plant immune system
iii) for all leukocyte mediated immunity, there are exact synonyms immune cell effector process, immune cell mediated immunity, leukocyte immune effector process that show how immunologists use "cell type" immunity to mean cell type mediated effector processes.  In other contexts the word immunity is sometimes interpreted differently.

Complement activation is a complicated area of discussion because spontaneous complement activation in the presence of a pathogen can interpreted as a de novo activation of an arm of the innate immune response with a directly linked effector response, while complement activation by (for instance) an antibody-opsonized target is definitely an effector response as part of an ongoing adaptive immune response.

iv) 'encapsulation of foreign target' was moved here per the cited reference PMID:12225920, Insect hemocytes and their role in immunity.  This process is an insect one, carried out by hemocytes, as a type of effector function in the innate immune response of the insect.

**Comment by ValWood** [comment]
Can you define the word "effector" in this context? (See the original question)

The current definition
"Any process of the immune system that can potentially contribute to an immune response."

Does not explain the mening of "effector" so I predumed it was a different context.

The pathogen "effector-mediated terms "  added more recently are defined (for example)
as:
A process mediated by a molecule secreted by a symbiont that results in the modulation (either activation or suppression) of a defense response.

I disregarded the term (GO:0002252), as a parent  because it  it did not seem to refer to same "effectors". 
For example,

GO:0008228   opsonization
The process in which a microorganism (or other particulate material) is rendered more susceptible to phagocytosis by coating with an opsonin, a blood serum protein such as a complement component or antibody.

Does not seem to be an "pathogen effector-mediated" process.  It seems to be an effector independent defense response?

Questions
What is the "entity" referred to as an "effector" in this particular context? This is not explained in the definition. 
What is the differentia to distinguish this term from "immune response"? 

With this information, we might be able to define the term more precisely so it is easier to understand what it refers to. and check whether it has the correct children. Currently  I can't see the common meaning of "effector"  here from the term itself, or its descendants?

**Comment by ValWood** [comment]
Note also that "GO:0002252 immune effector process" is not positioned under "immune response" It is under "immune system process"

**Comment by ValWood** [comment]
So when you say:

Why?
Immunologists typically refer to the activation and the effector stages of the immune responses. Immunologists talk about various specific biological processes as being types of effector activities that are part of the immune response.

What are immunologists referring to "effector stages". Do these have any relationship to the pathogen-effectors described  by the pathogen community ?

**Comment by RLovering** [comment]
we have effector process for apoptosis why is this a problem for the immune processes. Immunoglobulins are not involved in the signaling proceses but are part of the effector process

**Comment by pgaudet** [comment]
In apoptosis 'effector' is the part downstream from the signaling. Is that the same for immune processes ?

**Comment by RLovering** [comment]
I don't think it is as straight-forward as a linear pathway like that. There are so many different cell types involved. in that the effector process can lead to a activation of the next signaling pathway

**Comment by pgaudet** [comment]
OK. The way you described this - my interpretation was that there were effectors and signaling *functions* - ie not that those were justified to be grouped as similar types of processes. 

I am certainly over interpreting you quite brief comment ! 

Pascale

**Comment by ValWood** [comment]
The problem to me is that the  current definition : 

"Any process of the immune system that can potentially contribute to an immune response'

does not explain what an effector is.

The current definition is not in the standard format of genus, differentia.
See @cmungall blog post for best practice.
https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

Based on the current text, I do not know what this term means, it does not sound any different to "immune response" which is why I suggested a merge.
It is fine to have effector terms  in GO if they are defined so we know what the term is referring to.

See my earlier questions. is this the same as this effector?

GO:0140415 "A process mediated by a molecule secreted by a symbiont that results in the modulation (either activation or suppression) of a defense response.
(i.e a molecule secreted by a symbiont).
?

This has been used in a number of pathogen and plant terms.

If so, 
1) Some of the existing descendants seem to be incorrect (the plant terms are not  effector mediated  processes, they are PAMP mediated). PAMPs aren't pathogen-effectors they are molecules present in whole classes of microbes and usually required for the pathogen survival. Effectors are molecules that evolved in the pathogen  specifically to interrupt plant defenses.
2) Some terms which could be descendants re missing

If this use of "effector" is different from the use of the term "effector" by the pathogen community, what does it  refer to?

We can move forwards and fix things (definition, parents? descendants?)  once we understand   effector means in this context. The term does not need to be merged but it needs to be differentiated.

Until  yesterday I was ignoring this term because I thought it was some animal-specific immune process. Then  I noticed the plant descendants so it directly impacts the plant-pathogen work I am involved in and I need to understand what it means.

**Comment by addiehl** [comment]
Unfortunately, between teaching and meetings, I don't have time to properly respond to these comments before Thursday.  Please do not make changes before I have a chance to respond.

**Comment by pgaudet** [comment]
Sure. 

I have added the 'immune process' label (see on the right). If we cannot resolved this (and related) tickets by GH, we can also discuss in person in Paris. 

I dont think this one is urgent to close. 

Thanks for your time @addiehl

**Comment by pgaudet** [comment]
Hi @ValWood 

Are the descendants of this term till problematic ? For example I dont see the PAMP-mediated terms anymore. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@addiehl proposes to update the definition to 
'Any process of the immune system that executes a component of an immune response. An effector immune process takes place after its activation.' 

How does that sound ?

**Comment by pgaudet** [comment]
@addiehl

**Comment by pgaudet** [comment]
- I changed the definition of 'GO:0002252 immune effector process' to what @addiehl suggested, 'Any process of the immune system that executes a component of an immune response. An effector immune process takes place after its activation.'

- I removed the parent 'immune effector process' from the term  'defense response to virus'
- I added 'defense response to other organism' is_a immune response. 

Thanks, Pascale
