### ISSUE TITLE
GO:0009814 defense response, incompatible interaction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18742]
Is defined
Definition
A response of a plant to a pathogenic agent that prevents the occurrence or spread of disease.

but has non-plant annotations:
[non_plant.txt](https://github.com/geneontology/go-ontology/files/4148548/non_plant.txt)

**Comment by pgaudet** [comment]
There are C. elegans annotations to this term 

@vanaukenk Should we extend the definition ?

**Comment by ValWood** [comment]
I don't think we should include this term. It isn't describing a process really...
See
https://github.com/geneontology/go-ontology/issues/18738

Refers to the outcome of the process (i.e whether disease is observed).
If disease is not observed the interaction is "incompatible"
This isn't about the process per se. A particular interaction can be compatible or incompatible for a particular pathogen gene/host gene combination.


@vanaukenk  do you know which process this was trying to capture?
i would not move it to the broader non-plant term because  "incompatible interaction"  doesn't really belongs in GO does it?

@pgaudet  there is already a broader parent. I think they should all go. I should have put this ticket  on the 
 annotation tracker ?

**Comment by vanaukenk** [comment]
@ValWood 
I think the C. elegans annotations to this term are in error.  I'll raise a dispute in Protein2GO.

**Comment by ValWood** [comment]
You might want to mention not moving up to an "incompatible interaction parent" and point to the ticket. Otherwise it will need to be reannotated again.

**Comment by vanaukenk** [comment]
@ValWood 
Agreed.  I suspect this was just a term selection error (the word 'incompatible' doesn't appear in either of the references).

**Comment by vanaukenk** [comment]
@ValWood 

I created annotation disputes for annotations from both references that have C. elegans annotations to this term:

https://www.ncbi.nlm.nih.gov/pubmed/20600277
https://www.ncbi.nlm.nih.gov/pubmed/27184844

**Comment by vanaukenk** [comment]
@pgarmiri has deleted the C. elegans annotations to this term and the dispute resolved in Protein2GO.

**Comment by ValWood** [comment]
@pgaudet 


Action
we could merge this up to
GO:0045087    innate immune response
and nothing would be wrong, or lost
.

"incompatible interaction" only means that  the specific combination of pathogen and host do not cause disease.

**Comment by ValWood** [comment]
actually closing this one as "duplicate of"
https://github.com/geneontology/go-ontology/issues/18738
