### ISSUE TITLE
Rho-dependent protein serine/threonine kinase activity: axiomatize or obsolete

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#18750]
Looking at:

```
id: GO:0072518
name: Rho-dependent protein serine/threonine kinase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + a protein = ADP + a phosphoprotein. This reaction requires binding of the GTPase Rho." [GOC:ecd, PMID:12778124, PMID:20230755]
synonym: "Rho-associated protein kinase activity" EXACT [GOC:ecd]
synonym: "ROCK kinase activity" EXACT [GOC:ecd]
is_a: GO:0004674 ! protein serine/threonine kinase activity
```

First point: the part of the definition before the `.` should be unique. This is not. It's a generic kinase definition. The differentia must be moved before the period.

Further: we have a term `Rho GTPase binding` that could be used in a logical definition. A logical definition can help guide how this should be used in GO-CAMs.

But: do we even need these Rho-specific terms anyway? Do they not date from pre GO-CAM days, now is there a need for them if we can connect the activity of the Rho gene product to up and downstream activities?

The main argument I can see for keeping them is that annotations are transferred in paint and we would lose the transfer specificity by post-composing.

```
GO:0005089 ! Rho guanyl-nucleotide exchange factor activity
GO:0005094 ! Rho GDP-dissociation inhibitor activity
GO:0007266 ! Rho protein signal transduction
GO:0017048 ! Rho GTPase binding
GO:0051022 ! Rho GDP-dissociation inhibitor binding
```

**Comment by pgaudet** [comment]
I never understood why we have those terms, while we obsoleted all those for being 'gene products' (which can probably be argued):  
'obsolete small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003925>
'obsolete ARF small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003926>
'obsolete RAB small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003928>
'obsolete RAN small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003929>
'obsolete RAS small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003930>
'obsolete Rho small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003931>
'obsolete SAR small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0003932>
'obsolete RHEB small monomeric GTPase activity' <http://purl.obolibrary.org/obo/GO_0008619>

So we should have the same rule for functions and their regulation. 

Other than that, yes we should make sure the definitions are unambiguous. 

Should we restore the obsolete terms or merge the remaining ones ? 

Thanks, Pascale

**Comment by cmungall** [comment]
What do you think of my comment:

> The main argument I can see for keeping them is that annotations are transferred in paint and we would lose the transfer specificity by post-composing.

Essentially we are smuggling causal connections in the term, which we don't want to do long term, but while we are still operating with systems that are not natively cam, there is information in the precomposed term

Also, there is an opportunity to use these to unfold into richer GO-CAMs in the MOD import, cc @vanaukenk @ukemi

**Comment by deustp01** [comment]
Administrative tangent adding to @cmungall mention - this discussion overlaps with ones going on [here](https://github.com/geneontology/go-ontology/issues/18749#) and [here](https://github.com/geneontology/pathways2GO/issues/85). What I notice, of course is the central role that well-built GO-CAM models derived from well-curated Reactome pathways (both works in progress) could play in sorting out all of this, especially as we are starting a new project to revise and extend our annotations of RHO proteins and their various enablers / regulators / modulators.

At a minimum, looking at these longer-terms hopes might allow a clearer view of what smuggled connections to keep precisely because they can be displaced by CAMs eventually, and perhaps also to come up with a semi-realistic view of how to manage the displacement.

**Comment by ValWood** [comment]
I hope we purge all gene-product specific terms..... and terms which capture the target, or other information which can be captured by extensions. But I'm a "remover". Having multiple ways to say the same thing drives me crazy...

**Comment by pgaudet** [comment]
To be consistent, the proposal is to merge: 

'ARF guanyl-nucleotide exchange factor activity'
'cAMP-dependent guanyl-nucleotide exchange factor activity'
'Ras guanyl-nucleotide exchange factor activity'
'Rab guanyl-nucleotide exchange factor activity'
'Ral guanyl-nucleotide exchange factor activity'
'Ran guanyl-nucleotide exchange factor activity'
'Rap guanyl-nucleotide exchange factor activity'
'Rho guanyl-nucleotide exchange factor activity'
'Rac guanyl-nucleotide exchange factor activity'
'Sar guanyl-nucleotide exchange factor activity'

into : 'guanyl-nucleotide exchange factor activity'


-----

'ADP-ribosylation factor binding'
'Ras GTPase binding'
'Rab GTPase binding'
'Ral GTPase binding'
'Ran GTPase binding'
'Rho GTPase binding'
'GTP-Rho binding'
'Rac GTPase binding'

merge into: 'small GTPase binding'

There are many EXP annotations from UniProt, FlyBase, SGD, MGI, WB, UCL, but the merge should just remap all annotations. 

Tagging @pgarmiri @hattrill @srengel @suzialeksander @RLovering @pfey03 @tberardini @happy-lorna for info. 


Thanks, Pascale

**Comment by hattrill** [comment]
Tagging @sjm41

**Comment by ValWood** [comment]
These aren't just gene product specific though. They classify families by their different roles/substrates.
Although I am happy if they merge (in fact, some cases they could even be a bit misleading, and the substrate GTPases would be better captures in extensions). 

PomBase will preserve the family  classification in the gene product.
https://github.com/pombase/curation/issues/2617

Definitely the binding terms could merge - I think we should have as little classification as possible under protein binding.

**Comment by pgaudet** [comment]
I agree those different families have different cellular roles. 

But we have obsoleted the activities themselves (see my comment above: https://github.com/geneontology/go-ontology/issues/18750#issuecomment-581824310), I dont see a reason to do anything different for binding and GEF/GAP activities. 

Another possibility would be to restore the activities. 

Thanks, Pascale

**Comment by ValWood** [comment]
No I don't mind not having them. It's easier, and they are the same activity

**Comment by pgaudet** [comment]
Annotations: https://docs.google.com/spreadsheets/d/1nLCF4D_BULM9KhYBgufQiZj03_nhv4kIUWkj-gHDCN4/edit#gid=1229550309

**Comment by tberardini** [comment]
Confirming: no action necessary on the annotations, since they will be automatically remapped during the merge.  Is that correct?

**Comment by pgaudet** [comment]
Yes @tberardini

**Comment by pfey03** [comment]
I inspected many of our specific GTPAse binding (all parents in With field) and guanyl-nucleotide exchange factor activity (one needed correction anyway) and all others have extensions.Any automatic conversion should be fine for us.

Will the remappings be done in Protein2GO automatically?
Thanks!

**Comment by pgaudet** [comment]
> Will the remappings be done in Protein2GO automatically?

Yes, as with any merge.

**Comment by pgaudet** [comment]
GO:0043849 Ras palmitoyltransferase activity should also be merged.

**Comment by ValWood** [comment]
Would be nice to do these merges....there was no objection?

**Comment by pgaudet** [comment]
Also : 

- [ ] GO:1904475 regulation of Ras GTPase binding -> change label 'regulation of small GTPase binding'
- [ ] GO:1904476 negative regulation of Ras GTPase binding -> change label 'negative regulation of small GTPase binding'
- [ ] GO:1904477 positive regulation of Ras GTPase binding -> change label 'positive regulation of small GTPase binding'
- [ ] GO:2001106 regulation of Rho guanyl-nucleotide exchange factor activity  -> merge into GO:1904475
- [ ]  GO:2001107 negative regulation of Rho guanyl-nucleotide exchange factor activity  -> merge into GO:1904476
- [ ] GO:2001108 positive regulation of Rho guanyl-nucleotide exchange factor activity  -> merge into GO:1904477

**Comment by pgaudet** [comment]
- [ ] GO:1905097 regulation of guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase binding'
- [ ] GO:1905098 negative regulation of guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase binding'
- [ ] GO:1905099 positive regulation of guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase binding'
- [ ]  GO:2001106 regulation of Rho guanyl-nucleotide exchange factor activity -> merge into GO_1905097 
- [ ]   GO:2001107 negative regulation of Rho guanyl-nucleotide exchange factor activity -> merge into GO_1905098 
- [ ]  GO:2001108 positive regulation of Rho guanyl-nucleotide exchange factor activity  -> merge into GO_19050979

**Comment by pgaudet** [comment]
Still need to deal with 

- [ ] GO:1905097 regulation of guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase activity'
- [ ] GO:1905098 negative regulation of guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase activity'
- [ ] GO:1905099 positive regulation of guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase activity'
- [ ]  GO:2001106 regulation of Rho guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase activity'
- [ ]   GO:2001107 negative regulation of Rho guanyl-nucleotide exchange factor activity -> change label 'regulation of small GTPase activity'
- [ ]  GO:2001108 positive regulation of Rho guanyl-nucleotide exchange factor activity  -> change label 'regulation of small GTPase activity'
