### ISSUE TITLE
negative regulation of nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts 

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18757]
For PMID:24920274 we'd like the regulation terms for

GO:0033621 ! nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts 

(We have immediate uses for the negative regulation term to annotate pombe sme2, and don't mind the rest of the triad being included.)

**Comment by mah11** [comment]
at @pgaudet's invitation in the GO meeting, pinging my open tickets

**Comment by krchristie** [comment]
Sorry @mah11 - this one just slipped off my radar. Done now.

**Comment by mah11** [comment]
Thanks!
