### ISSUE TITLE
error in definition of GO:0017083

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#18756]
Hi,

It would seem that there is an error in the definition of the Go term GO:0017083 (4-galactosyl-N-acetylglucosaminide 3-alpha-L-fucosyltransferase activity)
In QuickGO the definition is:
Catalysis of the reaction: GDP-beta-L-fucose + beta-D-galactosyl-(1,4)-N-acetyl-D-glucosaminyl-R = GDP + 1,4-beta-D-galactosyl-(1,4)-[alpha-L-fucosyl-(1,4)]-N-acetyl-D-glucosaminyl-R. 

But it would seem that is : 
Catalysis of the reaction: GDP-L-fucose + beta-D-galactosyl-(1,4)-N-acetyl-D-glucosaminyl-R = GDP + beta-D-galactosyl-(1,4)-[alpha-L-fucosyl-(1,3)]-N-acetyl-D-glucosaminyl-R.

Many thanks for the correction.
Guilaine

**Comment by ukemi** [comment]
No Rhea xref yet.

**Comment by hdrabkin** [comment]
RHEA:14257 to this EC
beta-D-galactosyl-(1->4)-N-acetyl-beta-D-glucosaminyl derivative + GDP-beta-L-fucose = a beta-D-galactosyl-(1->4)-[alpha-L-fucosyl-(1->3)]-N-acetyl-beta-D-glucosaminyl derivative + GDP + H(+)

Corrected def and added RHEA
