### ISSUE TITLE
Some synonyms marked as "erroneous" in GO

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#18765]
Hi,

You may want to look into the following synonyms, and remove them if they really are erroneous, or edit them if not:

GO:0016711 flavonoid 3'-monooxygenase activity
exact synonym: flavonoid 3-hydroxylase (erroneous)
exact synonym: flavonoid 3-monooxygenase (erroneous)

GO:0047082 3,9-dihydroxypterocarpan 6a-monooxygenase activity
exact synonym: 3,9-dihydroxypterocarpan 6alpha-monooxygenase (erroneous)

GO:0004574 oligo-1,6-glucosidase activity
broad synonym: limit dextrinase (erroneous)

GO:0051060 pullulanase activity
broad synonym: limit dextrinase (erroneous)

Thanks,
Paola

**Comment by ukemi** [comment]
Interesting. It looks like these are coming in after a reclassification in EC. @hdrabkin or @deustp01 we could remove them or make them related for searching purposes and remove the (erroneous). Which do you think serves the community better? I guess it's kind of like having old gene symbols, some people might still look for them based on the old string even though it's misleading.

**Comment by hdrabkin** [comment]
In some cases I have come across when the EC changes, etc., I remove the EC reference in the synonyms if the new EC does not list the same synonyms and make them related solely so someone might find them.

**Comment by ukemi** [comment]
Thanks! That's my general thought too. I will move them to related.

**Comment by deustp01** [comment]
nothing to add from here. Thanks, Harold.

**Comment by pgaudet** [comment]
For 'limit dextrinase' we do have a term, 'limit dextrinase activity' - isn't it the practice to add a comment that says 'do not confuse with x' or something like that ? 

Its seems misleading to use 'related synonym' if they are erronous.

**Comment by hdrabkin** [comment]
I don't think these are errors; it's just that the NEW EC number does not list them as synonyms; EC might add them back.

**Comment by hdrabkin** [comment]
Frankly, I don't get how we actually DO use the EC alt names since they are not classified as exact, narrow, related, etc. ; Just alternative names

**Comment by hdrabkin** [comment]
I just emailed EC to see what their policy is.

**Comment by hdrabkin** [comment]
Reply from EC
Hi Harold,

I am not sure I understand the difference between 'exact synonym' and 'related'
in GO terminology. In IUBMB terminology alternative names are synonyms, related
names would belong to related enzymes that should have their own EC numbers.
Generally, there is no fixed policy concerning synonyms in the EC list, it is
up to the person doing the transfer to decide whether he or she wants to keep
the existing synonyms or not. A transfer often means that what was originally
thought to be the activity of the enzyme is not correct. So enzymes linked to
the 'original' function stop making sense as well. In such a case we do not
keep the original synonym.
In addition, if you get your EC data from ENZYME, we do not show all the
synonyms listed by IUBMB, as IUBMB synonyms include gene names and old versions
of the IUBMB systematic name. the IUBMB systematic name is not part of ENZYME
data, and gene names are shown and maintained in UniProtKB so we do not like to
duplicate it in ENZYME where is it not certain to be up-to-date.

Best,
Kristian

So I think we should not assume EC alt names are always exact.
