### ISSUE TITLE
Should GO:0016174 NAD(P)H oxidase exist?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18767]
I am looking at a paper describing a plant NADH(P) oxidase, and Im trying to figure what its activity is
(A fungal gene directly regulators the activity of the gene product)

there are 2 slightly different reactions

GO:0016174    NAD(P)H oxidase activity
Catalysis of the reaction: NAD(P)H + H+ + O2 = NAD(P)+ + hydrogen peroxide.

GO:0016175  superoxide-generating NADPH oxidase activity
Catalysis of the reaction: NAD(P)H + O2 = NAD(P)H + O2-. PMID:10806195

I assumed the reaction catalysed was
GO:0016175  superoxide-generating NADPH oxidase activity

but all arabidopsis are annotated to GO:0016174

form the paper intro
Generation of a burst of reactive oxygen species (ROS) catalyzed by NADPH oxidase (Nox) is an important defense mechanism for both mammals and plants against invading microbes (Doke, 1983; Reeves et al., 2002; Lambeth, 2004; Torres and Dangl, 2005). In phagocytes, activation of the membrane-associated NADPH oxidase (gp91phox/NOX2) to produce ROS in response to microbial or inflammation signals involves cytosolic recruitment of a heterotrimeric phagocyte oxidase complex (phox) together with the small GTP binding protein Rac2 (Diebold and Bokoch, 2001; Lambeth, 2004). The discovery of new functional members of the Nox family has led to the recognition that ROS production is a ubiquitous eukaryotic signaling system to control various dif- ferentiation processes, including cell proliferation, apoptosis, and hormone responses in animals (Suh et al., 1999; Lambeth et al., 2000; Lardy et al., 2005), programmed cell death and root hair growth in plants (Foreman et al., 2003; Carol et al., 2005), and sexual development and spore germination in filamentous fungi (Lara-Ortiz et al., 2003; Malagnac et al., 2004; Aguirre et al., 2005).

then I found this in another paper:

NADPH oxidase enzymes belong to a family of transmembrane
proteins able to transport electrons across a membrane -usually
the plasma membrane- from a cytosolic electron donor to oxygen
-the extracellular acceptor- t**hus catalyzing the generation of O•−
2
(Lambeth, 2004). However, the lifespan of superoxide molecules,
which are rapidly dismutated to H2O2 either spontaneously or
through the action of apoplastic superoxide dismutases (SOD),**
is extremely short (Bowler et al., 1994). NADPH oxidase (NOX)
activity was first described in mammal phagocytic cells and
consists of two plasma membrane proteins, gp91phox and
p22phox (phox for phagocyte oxidase). This protein complex
is regulated by its interaction with other cytosolic proteins
(p47phox, p67phox, p40phox, and Rac2) producing the active
form (Cross and Segal, 2004; Lambeth, 2004). Although these
mammalian protein complexes are the most studied NOXs, these
enzymes have also been characterized in other animals, fungi,
and plants. NADPH oxidase enzymes share a basic structure
consisting of six transmembrane domains, two heme-binding
sites and a long cytoplasmic C-terminal which includes FAD and
NADPH binding sites (Bedard et al., 2007).

so it seems that the reaction catalysed is 

GO:0016175  superoxide-generating NADPH oxidase activity
Catalysis of the reaction: NAD(P)H + O2 = NAD(P)H + O2-. 

Should GO:0016174 exist?
I can't find an EC number or a ref.

**Comment by hdrabkin** [comment]
RHEA:11260 : H(+) + NADPH + O2 = H2O2 + NADP(+)
Yes the term is real.
GO:0016174 NAD(P)H oxidase activity
Catalysis of the reaction: NAD(P)H + H+ + O2 = NAD(P)+ + hydrogen peroxide (H2O2)

**Comment by hdrabkin** [comment]
EC 1.6.3.1
PMID: 10401672
PMID: 10601291
PMID: 11822874
(refs are from the RHEA entry;
I will update GO:0016174

**Comment by hdrabkin** [comment]
The EC was there already in the term info.

**Comment by hdrabkin** [comment]
Update done. I assume I can close this.

**Comment by ValWood** [comment]
so even though EC's exist,  this is definitely not the case?

"two views of the identical molecular function, one that defines the reaction in terms of the immediate product of the reaction enabled by the oxidase activity and the other in terms of the first relatively stable product of that reaction."

if not, I'm not sure how to figure out which one I am annotating, and the common parent is

GO:0050664   oxidoreductase activity, acting on NAD(P)H, oxygen as acceptor
which is n't very satisfactory?

So in that case, if these 2 term definitely exist to describe different reactions, would it be possible to have a parent grouping term?

**Comment by ValWood** [comment]
Actually 
GO:0050664 oxidoreductase activity, acting on NAD(P)H, oxygen as acceptor
is OK.

or make the term name of
GO:0050664 oxidoreductase activity, acting on NAD(P)H, oxygen as acceptor

NADPH oxidase

currently broad for NADPH oxidase | broad for  GO:0016174   NAD(P)H oxidase activity

**Comment by hdrabkin** [comment]
Forgot to mention that I also added the EC name as an exact synonym NAD(P)H oxidase (H(2)O(2)-forming)
I could change to make THAT the name of 664, to make it more explicit, since the other term has 'superoxide' forming. I would not want to make a grouping term that I would feel the the need to make do not annotate since one makes superoxide and the other does not.

**Comment by hdrabkin** [comment]
OK; changed the name to bring it more in line with it's sib. That should make it very clear

**Comment by hdrabkin** [comment]
on nuts forgot to add 'activity' I'll get this right yet.

**Comment by ValWood** [comment]
OK thanks! I'll figure it out ;)

**Comment by hdrabkin** [comment]
Also noticed sib term does not have a RHEA; requesting
 [help #180802] in the subject line of all future correspondence to RHEA  about this issue.

**Comment by ValWood** [comment]
Hi Harold, any news on this one?

Thanks
Val

**Comment by hdrabkin** [comment]
Note if I didn't mention this before, consider GO:0016174  as a grouping term because its NAD(P). However, RHEA ids can either be NAD, OR NADP, not both. Only to be used IF one doesn't know; presumably, a paper would have an assay (?). 
If the enzyme in question CAN use both, it doesn't do it at the same time; hence the two reactions
RHEA:63180 NADPH + 2 O2 = H+ + NADP+ + 2 superoxide
RHEA:63184 NADH + 2 O2 = H+ + NAD+ + 2 superoxide
But not Public yet (will be on June release; so then can add and close this ticket.

**Comment by hdrabkin** [comment]
Rheas are now public. Made children of GO:0016175
+id: GO:0106291
+name: superoxide-generating NADH oxidase activity.

+id: GO:0106292
+name: superoxide-generating NADPH oxidase activity

**Comment by hdrabkin** [comment]
Made children for GO:0016174 with RHEA references.; removed rhea from GO:0016174

+id: GO:0106293
+name: NADH oxidase H202-forming activity

+id: GO:0106294
+name: NADPH oxidase H202-forming activity

Since RHEA has supplied the defs, I will defer to them that these are valid terms and close the ticket.
