### ISSUE TITLE
Natural language synonyms for synaptic transmission terms

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#18760]
GO:0007268 chemical synaptic transmission has several is_a children with the name in the format synaptic transmission, neurotransmitter.  These should have synonyms using natural language syntax of neurotransmitter synaptic transmission.  
                                  [is_a relation] GO:0098814 spontaneous synaptic transmission
                                 [is_a relation] GO:0007271 synaptic transmission, cholinergic
                                 [is_a relation] GO:0001963 synaptic transmission, dopaminergic
                                 [is_a relation] GO:0051932 synaptic transmission, GABAergic
                                 [is_a relation] GO:0035249 synaptic transmission, glutamatergic
                                 [is_a relation] GO:0060012 synaptic transmission, glycinergic
                                 [is_a relation] GO:0099155 synaptic transmission, noradrenergic
                                 [is_a relation] GO:0099153 synaptic transmission, serotonergic 

It would be nice if GO had a flag that indicated natural language synonyms.  @vanaukenk  Is this the right place to put this request?

**Comment by ukemi** [comment]
I will add the synonyms, but there is no flag for natural language synonyms, it seems like this would be quite subjective.
