### ISSUE TITLE
homologous recombination & gene conversion

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#18777]
We've received additional advice from Gerry Smith, our PomBase community expert in recombination.

At present the graph in the "DNA recombination" area includes this:

    DNA recombination
    [is_a] gene conversion
    [is_a] homologous recombination

(i.e. GO:0035822 ! gene conversion is_a: GO:0006310 ! DNA recombination and GO:0035825 ! homologous recombination is_a: GO:0006310 ! DNA recombination)

But according to Gerry:

> gene conversion and crossing over are types of homologous recombination.  In fact, one DNA interaction event (a recombination event) can produce both a gene convertant and a crossover. I think everybody in the field would agree with this statement.

here I take "crossing over" to mean the equal exchange represented in GO as GO:0035825 ! homologous recombination. From our email exchange I gather that

- gene conversion ≈ non-reciprocal recombinants ≈ unidirectional
- homologous recombination ≈ reciprocal recombinants ≈ crossovers ≈ bidirectional exchange

This new structure would accommodate it all:

    DNA recombination GO:0006310
    [is_a] homologous recombination GO:0035825
            [is_a] gene conversion GO:0035822
            [is_a] reciprocal homologous recombination GO:new
                [is_a] reciprocal meiotic recombination GO:0007131

If the change in meaning this implies for GO:0035825 seems too great, I'd be happy to rename it and assign the GO:new ID to the "homologous recombination" superclass (i.e. swap IDs GO:0035825 and GO:new in the graphlet above).

Gerry also suggests using "between highly homologous DNA molecules" to describe exchange for all three definitions (similar to what the "gene conversion" def has now).

If you have any questions or comments I'll relay them to Gerry, since this isn't an area I know well myself.

Also see #18751, which has a related recommendation from Gerry.

**Comment by ValWood** [comment]
Is there any chance this one can be addressed. I was reminded of it because I just asked for Gerry's input on a recombination annotation question. 
It would be good to act on his suggestions as he is a recombination guru, it's good that he has spent the time to look over the terms for us.

**Comment by pgaudet** [comment]
@ValWood Do you know how many annotations there are to each of those terms ? ie would we need to reannotate if we were to make those changes ?

**Comment by ValWood** [comment]
GO:0035822 gene conversion 35 EXP
 GO:0007131 reciprocal meiotic recombination 357 EXP

I don't know if reannotation would be required. I was assuming existing annotation would still be correct.

**Comment by mah11** [comment]
The impression I got from my exchange with Gerry was that things, including annotations, would be *more* correct if the changes were made.

**Comment by pgaudet** [comment]
@mah11 @ValWood I changed the parentage as suggested. 

- Can you provide a definition and a PMID for 'reciprocal homologous recombination GO:new' 
- Can you provide the definition changes you would like ?

Thanks, Pascale

**Comment by ValWood** [comment]
@mah11 if we remove the "meiosis-specific" part of
GO:0007131    reciprocal meiotic recombination

The cell cycle process in which double strand breaks are formed and repaired through a single or double Holliday junction intermediate.

i.e remove this part:
 This results in the equal exchange of genetic material between non-sister chromatids in a pair of homologous chromosomes. These reciprocal recombinant products ensure the proper segregation of homologous chromosomes during meiosis I and create genetic diversity. PMID:2087779

**Comment by ValWood** [comment]
Actually aren't  "gene conversion"  nd "reciprocal homologous recombination" both  just  different outcomes  of the same process?

**Comment by ValWood** [comment]
@mah11 we are confused by a couple of things:

A gene conversion ≈ non-reciprocal recombinants ≈ unidirectional
B homologous recombination ≈ reciprocal recombinants ≈ crossovers ≈ bidirectional exchange

so we are wondering how "homologous combination" can be a child of gene conversion

and, if that is OK what the definition of the new proposed term
      [is_a] reciprocal homologous recombination GO:new
would be

**Comment by mah11** [comment]
> so we are wondering how "homologous combination" can be a child of gene conversion

This was not proposed anywhere.

**Comment by mah11** [comment]
I thought there was enough info in the original summary to indicate how new definitions should be phrased, but here are suggestions written out:

id: GO:0035825
name: homologous recombination
def: "A DNA recombination process that results in the exchange of an equal amount of genetic material between highly homologous DNA molecules." [PMID:11139492, PMID:17304215]*
is_a: GO:0006310

id: GO:0035822
name: gene conversion
def: "A DNA recombination process that results in the unidirectional transfer of genetic material from a donor sequence to a highly homologous acceptor. The resulting acceptor sequence is identical to that of the donor." [GOC:mah, PMID:17846636]*
is_a: GO:0035825

id: GO:new
name: reciprocal homologous recombination
def: "A DNA recombination process that results in the bidirectional exchange of genetic material between highly homologous DNA molecules." [PMID:17846636]*
is_a: GO:0035825

*The additional information in the original summary here was a personal communication from Gerry Smith. If there's any reason why the refs cited for the old defs for GO:0007131, GO:0035822, and GO:0035825 won't suffice, we could ask Gerry for recommendations (e.g. reviews).

**Comment by ValWood** [comment]
But  are "gene conversion" and "reciprocal homologous recombination" really different biological processes or just different outcomes of the same process?

**Comment by ValWood** [comment]
This also  seems to be what Gerry is saying here:

gene conversion and crossing over are types of homologous recombination. In fact, one DNA interaction event (a recombination event) can produce both a gene convertant and a crossover. I think everybody in the field would agree with this statement.

one event can produce a "gene convertant" and a "cross over",  so in that case is it really separate processes ?

**Comment by ValWood** [comment]
ignore above

**Comment by ValWood** [comment]
>>so we are wondering how "homologous recombination" can be a child of gene conversion
This was not proposed anywhere.

I put this the wrong way around. I meant 
so we are wondering how  can be a child of "gene conversion" can be a child of "homologous recombination"

if one is 'reciprocal' and one is 'non-reciprocal'

**Comment by ValWood** [comment]
I think I get it now, above

homologous recombination ≈ reciprocal recombinants ≈ crossovers ≈ bidirectional exchange

should be 
reciprocal homologous recombination ≈ reciprocal recombinants ≈ crossovers ≈ bidirectional exchange

then it all logical sense
