### ISSUE TITLE
Small error in the definition of GO:0030907

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#18770]
Hi,

A user of our db wrote in today saying there was an error in the definition for the term 'MBF transcription complex'. It currently read 'A protein complex that binds to the Mlu1 cell cycle box (MCB) promoter element, consensus sequence ACGCGN, and is involved in regulation of transcription during the G1/S transition of the cell cycle. In Saccharomyces, the complex contains a heterodimer of the DNA binding protein Mbp1p and the activator Swi4p, and is associated with additional proteins known as Nrm1p, Msa1p, and Msa2p; in Schizosaccharomyces the complex contains Res1p, Res2p, and Cdc10p.' 

The activator in this complex is Swi6p not Swi4p, so the second sentence should read:

In Saccharomyces, the complex contains a heterodimer of the DNA binding protein Mbp1p and the activator **Swi6p**, and is associated with additional proteins ...

Cheers,
Rob

**Comment by pgaudet** [comment]
@ValWood I suppose if you didn't agree you would have put a comment already ?

**Comment by ValWood** [comment]
I defer to @robnash  for the cerevisiae composition ;)
