### ISSUE TITLE
Help! galactose catabolic process via UDP-galactose

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18771]
galactose catabolic process via UDP-galactose

is this an odd term?
It is used to annotate

UDP-glucose 4-epimerase activity

but this isn't really galactose catabolism is it?

In the cytosol, the key enzyme for UDP synthesis is UDP- galactose/-glucose 4-epimerase, which catalyses the inter- conversion of UDP-galactose and UDP-glucose. 

For example:
Deletion of uge1 causes a
defect in synthesis of UDP-galactose and deletion mutants are defective in galactosylation when grown in glucose medium. Gal10 is involved in galactosylation of cell- surface proteins under conditions of glucose starvation (Suzuki et al. 2010).

so the annotations. should be to 
UDP-galactose synthesis

galactose catabolic process Source: GO_Central
galactose catabolic process via UDP-galactose Source: SGD

Don't seem correct in this situation?
galactose catabolic process via UDP-galactose should probably not exist?

Asking  @deustp01

**Comment by ValWood** [comment]
Got it. This is OK for S. cerevisiae which uses galactose as a carbon source via this pathway. Pombe cannot use galactose as an energy source but uses the pathway to make UDP-galactose for galactosylation when glucose is scarce. I forgot this ;)

I will get the PAINT annotations blocked.

**Comment by pgaudet** [comment]
Should we not get a taxon constraint for this ? Is this only hapenning in cerevisiae ?

**Comment by ValWood** [comment]
Yes, we can add "never in pombe" I don't know enough about other yeasts to know whether they can grow on galactose of not....

**Comment by deustp01** [comment]
In humans, [UDG-galactose is both an intermediate in the conversion of galactose to glucose 6-phosphate and a precursor for biosyntheses involving incorporation of galactose units](https://reactome.org/PathwayBrowser/#/R-HSA-70370&PATH=R-HSA-1430728,R-HSA-71387). Depending on cell type and physiological state, that glucose 6-phosphate itself might be catabolized via glycolysis or used itself via the pentose phosphate shunt to synthesize ribose 5-phosphate. I don't know ant of the details but I expect that all of these processes can operate in fungi, again with dependencies on physiological state.

So it's a hard problem of sorting out pathway boundaries, reactions shared by diverse processes, and context provided by physiological state and cellular specialization.

<img width="928" alt="Screen Shot 2020-02-07 at 9 09 11 AM" src="https://user-images.githubusercontent.com/12737623/74036369-213a3a00-498a-11ea-871f-e5aa691a7d52.png">

**Comment by pgaudet** [comment]
Taxon constraint is there GO:0033499	galactose catabolic process via UDP-galactose	NCBITaxon:147554	Schizosaccharomycetes
