### ISSUE TITLE
Obsoletion of multi-organism biosynthetic process and children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18787]
There is no evidence that 'multi-organism biosynthesis' exists - so the following terms will be obsoleted: 

* GO:0044034 multi-organism biosynthetic process
* GO:0052226 biosynthesis of substance in other organism involved in symbiotic interaction
* GO:0052352 biosynthesis by host of substance in symbiont
* GO:0052007 biosynthesis by symbiont of substance in host 

There is one 1 TAS annotation by Reactome to 'biosynthesis by host of substance in symbiont'
@deustp01 

Thanks, Pascale

**Comment by deustp01** [comment]
No, but we do have one to GO:0052007 biosynthesis by symbiont of substance in host. Now fixed in internal database; will become visible with next release in March 2020.

But the process does exist. In this case an anthrax bacillus synthesizes something that is metabolized further when taken up by the infected human host so it's a disease process and out of scope for GO anyway, but the process seems real. Or am I misinterpreting the phrase "biosynthesis by symbiont of substance in host"?

**Comment by ValWood** [comment]
Also found an InterPro mapping to
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR015845/
It seems a plasmid involved transfer of an infective plasmid with metabolic genes

**Comment by ValWood** [comment]
Oh sorry that's the other way around.
We are discussing  "by host in symbiont" terms

**Comment by pgaudet** [comment]
Thanks @deustp01 

> out of scope for GO anyway, but the process seems real. 

I think you are interpreting the process correctly - but in this example, as you point out, the host probably gets tricked into metabolizing the toxic compound. 

In other cases - say a symbiont takes advantage that a metabolite is present in the host, and further metabolizes  it, I wouldn't say this is a 'multi-organism process' - the two organisms are not producing the compound together, but the host just happens to be the environment in which the symbiont lives. 

Do you see cases where these terms would be appropriate for GO annotations ? 

Thanks, Pascale

**Comment by deustp01** [comment]
Nitrogen fixation in plants? Shared metabolic processes in lichens (no clue from here what these might amount to)? Intracellular protozoan symbionts scavanging nucleotide intermediates that they can't synthesize de novo? Humans scavanging vitamin K metabolites from gut bacteria? The metabolism that accompanies quorum sensing?

and anyway trickery is a normal part of a lot of organismal behavior.

**Comment by pgaudet** [comment]
N fixation is only done solely by the bacteria - N2 is absorbed by the plant; isn't it ? 
https://en.wikipedia.org/wiki/Nitrogen_fixation

There is certainly symbiosis and co-evolution (some organisms do not make certain compound because they are provided by others) - is this case the plant does host the bacteria since having N2 is essential - but does not participate in the biosynthesis. 

> Humans scavanging vitamin K metabolites from gut bacteria

Again this is the source of the compound, I dont see how this process is accomplished by the two species. 

I can hold this one off to leave time for other comments. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: 
* GO:0044034 multi-organism biosynthetic process
*  GO:0052226 biosynthesis of substance in other organism involved in symbiotic interaction
* GO:0052352 biosynthesis by host of substance in symbiont
* GO:0052007 biosynthesis by symbiont of substance in host

The reason for obsoletion is that there is no evidence that hosts and symbionts have common biosynthesis processes (even though some substances produced by one organism may be used by the other). 

There is one InterPro mapping to this term, IPR015845. 
There are no manual annotations. Those terms are not present in any slims. 

Any comments can be made to the ticket: geneontology/go-ontology#18787

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 3rd, 2020. Unless objections are received by March 3rd, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@happy-lorna Can you please see if you can remove/change mapping for IPR015845 ?
