### ISSUE TITLE
GO / RHEA not 1:1

### ISSUE THREAD

**Issue by cbizon** [geneontology/go-ontology#18789]
GO:0004317 and GO:0008659 both have mapping to the same RHEA id: RHEA:13097.

There may be others like this, I have not exhaustively checked.

**Comment by hdrabkin** [comment]
Needs to merge; apparently one is an exact synonym of the other

**Comment by hdrabkin** [comment]
oops ignore previous comment (I deleted)

GO:0004317 3-**hydroxypalmitoyl**-[acyl-carrier-protein] dehydratase activity

GO:0008659 (3R)**-hydroxymyristoy**l-[acyl-carrier-protein] dehydratase activity

Both mapped to EC 4.2.1.59 3-**hydroxyacyl-**[acyl-carrier-protein] dehydratase.
but  has synonyms to **hydroxyoctanoyl-**[acyl-carrier-protein] dehydratase.

RHEA:13097 | a (3R)-hydroxyacyl-[ACP] = a (2E)-enoyl-[ACP] + H2O; this is generic
-
Although the EC id may be correctly mapped for mechanism, the two GO terms refer to a specific substrate. 
I will request CHEBI ids for both of the these; the RHEA will be removed for the specific terms.
It will however remain for GO:0019171

**Comment by hdrabkin** [comment]
4 rhea ids requested to apply to 4 reactions where the acyl-group is specified.

**Comment by hdrabkin** [comment]
BTW, here is a case where if the Defs had a PMID there would be no problem getting a RHEA. I am forced to use annotation references, and for two of these, the annotations are not experimental 8-(

**Comment by hdrabkin** [comment]
It turns out there were RHEA terms (hard to find).
Adding rhea to
 GO:0004317 RHEA:41908
GO:0008659 RHEA:41892 
GO:0008693 RHEA:41860
GO:0047451 RHEA:41844
PMID refs also added to these terms.
This addresses everything in this ticket.
