### ISSUE TITLE
Obsoletion of unused symbiont 'growth' terms 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18786]
Hello, 

These terms combine a process and a location, so they will be obsoleted: 

* GO:0044151 growth of host on or near symbiont surface
* GO:0044133 growth of symbiont on or near host (2 EXP ASAP @pgaudet)	
* GO:0044135 growth of symbiont on or near host phyllosphere
* GO:0044137 growth of symbiont on or near host rhizosphere

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete:
GO:0044151 growth of host on or near symbiont surface
GO:0044133 growth of symbiont on or near host (2 EXP ASAP deleted @pgaudet)
GO:0044135 growth of symbiont on or near host phyllosphere
GO:0044137 growth of symbiont on or near host rhizosphere
The reason for obsoletion is that these terms combine a process and a location. The location should be captured with an extension. 

There are no mappings to this term. This term is not present in any subsets. 

Any comment may be added to the ticket: https://github.com/geneontology/go-ontology/issues/18786

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 17th, 2020. Unless objections are received by February 17th, 2020, we will assume that you agree to this change.



Thanks, Pascale

**Comment by ValWood** [comment]
growth of symbiont in host
growth of symbiont in host cell
growth of symbiont in host vacuole
?

**Comment by pgaudet** [comment]
I thought we said we'd keep those last week.

**Comment by ValWood** [comment]
OK perhaps we did...
