### ISSUE TITLE
NTR: N4-acetylcytidine amidohydrolase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#18806]
Based on PMID 31964920.  Proposed definition: Catalysis of the reaction N4-acetylcytidine +H2O = cytidine + acetate.  Child term of GO:0016811.

Thanks,
Ingrid

**Comment by hdrabkin** [comment]
RHEA requested.

**Comment by hdrabkin** [comment]
+id: GO:0106251
+name: N4-acetylcytidine amidohydrolase activity

**Comment by hdrabkin** [comment]
RHEA:62932. It will become available in release 2020_03 scheduled for June 17.

**Comment by hdrabkin** [comment]
RHEA:62932  now available; added to the term. Closing ticket
