### ISSUE TITLE
GO:0140110 transcription regulator activity add relation to BP 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18801]
GO:0140110 transcription regulator activity
add relation ''part of' some 'transcription, DNA-templated''

**Comment by pgaudet** [comment]
We get confused with this one all the time !!! 

Children have links to more precise processes. 

This is OK - no action needed.

**Comment by vanaukenk** [comment]
@pgaudet 
Do you want this to be 'part of' some 'transcription, DNA-templated' or 'part of' some 'regulation of transcription, DNA-templated'?

**Comment by pgaudet** [comment]
Right I meant regulation, but the children terms have the links to the correct BPs. 

Thanks for catching this!
