### ISSUE TITLE
Add parent  to "repair of mitotic mono-orientation defect (GO:1990598)"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18815]
repair of mitotic mono-orientation defect (GO:1990598)

is part_of
mitotic sister chromatid biorientation

PMID:20739936
Nature. 2010 Oct 7;467(7316):719-23
Title | Phosphorylation of the CPC by Cdk1 promotes chromosome bi-orientation.
The dynamic regulation of kinetochore-microtubule attachment is governed by the CPC, consisting of Aurora B, INCENP, Survivin and Borealin/Dasra (Ark1, Pic1, Bir1 and Nbl1 in fission yeast)1,10, which concentrates on centromeres by passing through the chromosome arms from prophase to metaphase, and suddenly relocating to the spindle midzone at the metaphase-anaphase transition

**Comment by ValWood** [comment]
Although this appears to be "withing pathway" regulation. It could merge into 

regulation of mitotic sister chromatid biorientation

**Comment by pgaudet** [comment]
@ValWood I dont find the term 'regulation of mitotic sister chromatid biorientation' (or orientation). 

What's the ID ?

**Comment by ValWood** [comment]
GO:1990758 mitotic sister chromatid biorientation
(it has no regulation terms at present)

repair of mitotic mono-orientation defect (GO:1990598)
is  a regulatory process, so this could be renamed
positve regulation of mitotic sister chromatid biorientation
with 
repair of mitotic mono-orientation defect 
as a related synonym

(it's the pathway that dete4cts problems. But I guess it doesn't really do the repair. It probably just initiates a delay  until the attachment is corrected).

This way my existing  annotations  will look a bit more consistent (sometimes we use 'regulation of  
"regulation of attachment of spindle microtubules to kinetochore involved in meiotic chromosome segregation"
and sometimes the repair term for this process.

**Comment by ValWood** [comment]
"repair of mitotic merotelic kinetochore attachment defect"

can also merge into  the renamed GO:1990598

(it's the same pathway)

**Comment by ValWood** [comment]
repair of merotelic kinetochore attachment defect, meiosis I (make related synonym)
can be renamed
regulation of monopolar spindle attachment to meiosis I kinetochore

child of
monopolar spindle attachment to meiosis I kinetochore

(this one isn't even in the right place)

**Comment by ValWood** [comment]
Actions

mitotic terms

1. repair of mitotic mono-orientation defect (GO:1990598)
is a regulatory process, so this could be renamed
positive regulation of mitotic sister chromatid biorientation
with
repair of mitotic mono-orientation defect
as a related synonym
(rationale it's the pathway that detects problems. But I guess it doesn't really do the repair. It probably just initiates a delay until the attachment is corrected)

2. Add the parent GO:1990758 mitotic sister chromatid biorientation to GO:1990598

3. merge "repair of mitotic merotelic kinetochore attachment defect"
 into the renamed GO:1990598 (it's the same pathway/process)

Aligning equivalent meiotic terms

4. 
GO:0090699   repair of merotelic kinetochore attachment defect, meiosis I
can be renamed
regulation of monopolar spindle attachment to meiosis I kinetochore
(make repair of merotelic kinetochore attachment defect, meiosis I  related synonym) 

5. Add parent 
monopolar spindle attachment to meiosis I kinetochore
to renamed GO:0090699

**Comment by ValWood** [comment]
I have  summarized the actions for this one

**Comment by pgaudet** [comment]
* positive regulation of mitotic sister chromatid biorientation (GO:0140429) already exists (added in Feb #18821  - 4 EXP 
I will merge the old term (repair of mitotic mono-orientation defect (GO:1990598)/ 1 EXP) into this.

**Comment by pgaudet** [comment]
Likewise, 

> 4. GO:0090699 repair of merotelic kinetochore attachment defect, meiosis I
can be renamed
regulation of monopolar spindle attachment to meiosis I kinetochore
(make repair of merotelic kinetochore attachment defect, meiosis I related synonym)

I will merge in the existing term GO:1904967 regulation of monopolar spindle attachment to meiosis I kinetochore
