### ISSUE TITLE
Tidying up 'multi-organism behavior' children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18810]
Following up on the discussion we had on the ontology call regarding #14956

Move the following terms directly under behavior: 
* 'aggressive behavior'
*'behavioral defense response to insect'
*'behavioral defense response to nematode'
*'multi-organism reproductive behavior' -> move under 'reproductive behavior'
*'social behavior'
*'suckling behavior' (already under 'feeding behavior)
* injection of substance in to other organism -> move under 'multi-organism process'

**Comment by pgaudet** [comment]
The proposal has been made to obsolete GO:0051705 multi-organism behavior

The reason for obsoletion is that this is an unnecessary grouping term. 

There are no annotations and no mappings to this term. This term is present in the goslim_pir, but so is the parent 'multi-organism process GO:0051704', so no action is needed for now.

Any comment may be added to the ticket:https://github.com/geneontology/go-ontology/issues/18810

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 17th, 2020. Unless objections are received by February 17th, 2020, we will assume that you agree to this change.



Thanks, Pascale

**Comment by ValWood** [comment]
Could genes be annoted to this term?

GO:0002211    behavioral defense response to insect

A gene for fly swatting?

**Comment by ValWood** [comment]
This one is funny:
*'behavioral defense response to nematode'
no annotations but the reference is http://europepmc.org/article/MED/14506883

There is strong evidence suggesting that herbivore hosts have developed the foraging skills needed to take advantage of plant properties to combat parasites and thus use behaviour as a weapon in the host-parasite arms race.

You can't really annotate specific gene products to this!

**Comment by pgaudet** [comment]
Happy to obsolete some of those !

**Comment by cmungall** [comment]
Why would social behavior (SB) no longer be under MOP?

I don't love MOP but while it exists we should abide by it:

```
name: multi-organism process
def: "A biological process which involves another organism of the same or different species."
```

I don't like the definition as it uses a weasely 'involves' (in a different sense from how we use it for gene products). In some sense of the word, SB involves another organism.

There are 2 main readings:

 1. a MOP has multiple organisms as participants
 2. a MOP may have a single organism as participant, but that process is embedded in a larger process that involves another organism

If we treat social behavior as the behavior of a single organism, made in response to stimuli from another organism, with effectors directed towards that other organism, then SB is not a subclass of 1, but it is a subclass of 2, which justifies your proposed move.

I'd like to push forward with this but it may be worth reviewing MOP first, what does it really mean

Maybe we want to obsolete it too, and all the 'multi-organism P' terms

There are deeper problems here... social behavior is under BP, which is _a specific objective that the organism is genetically programmed to achieve_. I'm not sure everyone would agree. Humans are not fruitflies.

**Comment by pgaudet** [comment]
@cmungall 
'social behavior' is now under 'intraspecies interaction between organisms', so it does indicate that multiple organisms participate. 

I thought on the last ontology call we had agreed to obsolete 'multi-organism process' and re-classify everything under intra or inter-organism process. 

Let me know if you want to do this differently. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think you should get rid of multi organism process, it is too complicating. I notice that now everything under MOP here is "behaviour"  now except for the rather crazy

GO:0035737    JSON
injection of substance in to other organism
The process of forcing a substance into another organism, either by penetrating the skin of the other organism or by applying the substance externally to a sensitive tissue such as those that surround the eyes.

hmmmm....

so MOP can easily be removed.
(it has no direct annotations. "M-O cellular process" has a single experimental annotation)

**Comment by ValWood** [comment]
@cmungall Note that all of the  symbiont/host stuff is now under "interaction with other species"
(multi-organism process was just weird for this, it's usually a process in one species evolved to affect another species ).

**Comment by cmungall** [comment]
> social behavior' is now under 'intraspecies interaction between organisms', so it does indicate that multiple organisms participate.

ah I didn't see that. All good, thanks
