### ISSUE TITLE
Tidying up multi-organism processes: Children of GO:0098630 aggregation of unicellular organisms 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18814]
Move under 'intraspecies interaction between organisms': 
*  GO:0000752 agglutination involved in conjugation with cellular fusion
*   GO:0000758 agglutination involved in conjugation with mutual genetic exchange
*   GO:0031152 aggregation involved in sorocarp development
*   GO:0000128 flocculation

Move under 'interspecies interaction between organisms': 
*  GO:0036281 coflocculation

Merge
*   GO:0052000 type IV pili-dependent aggregation 0 annotations
-> merge into GO:0044010 single-species biofilm formation (see PMID:25852657)

**Comment by pgaudet** [comment]
Note that  'agglutination' is a child of 'cell-cell adhesion'
  [Inferred is_a relation] GO:0098609 cell-cell adhesion
                 [is_a relation] GO:0098610 adhesion between unicellular organisms
                     [Current term] GO:0000771 agglutination involved in conjugation
                         [is_a relation] GO:0000752 agglutination involved in conjugation with cellular fusion
                         [is_a relation] GO:0000758 agglutination involved in conjugation with mutual genetic exchange

**Comment by pgaudet** [comment]
Should 'cell aggregation': The clustering together and adhesion of initially separate cells to form an aggregate.  Examples include the clustering of unicellular organisms or blood cells in suspension and the condensation of mesenchymal cells during cartilage formation.

be a child of 'GO:0098609 cell-cell adhesion'? The attachment of one cell to another cell via adhesion molecules.

Thanks, Pascale

**Comment by pgaudet** [comment]
What is the difference between 

GO:0000128 flocculation: "The reversible, non-sexual aggregation of single-celled organisms in suspension to form aggregates of many cells known as flocs." 
and  GO:0043689 cell-cell adhesion involved in flocculation "The attachment of one single cell organism to another via adhesion molecules, occurring as a part of flocculation."? 

Looks like the most specific term was only used by pombase @ValWood 

If there are no objections I will merge.

**Comment by pgaudet** [comment]
Merge 
GO:0098741 adhesion between unicellular organisms via cell-wall interaction  -> 0 annotations
into parent: GO:0098610 adhesion between unicellular organisms
since whether or not there is a cell wall is a property of the organism; there are no two types of cell adhesion in organisms with cell walls.

**Comment by ValWood** [comment]
Eewww That was me...No objections...

**Comment by ValWood** [comment]
'cell aggregation': vs
 cell-cell adhesion'?

I think cell aggregation is a term @RLovering  uses in the ALS context. They sound the same to me but maybe there is a subtle difference?

**Comment by pgaudet** [comment]
- [ ] Merge: flocculation via extracellular polymer
into flocculation

- [ ] Merge: 'cell-cell adhesion involved in galactose-specific flocculation'
into 'galactose-specific flocculation'

- [ ] Merge: 'cell-cell adhesion involved in mannose-specific flocculation'
into  'mannose-specific flocculation'
(although those are probably MFs)

**Comment by pgaudet** [comment]
- [x]  pollen tube adhesion: remove multi organism process parent (the same organism can fertilize itself in plants)

**Comment by pgaudet** [comment]
- [ ] Merge  GO:0043706 heterophilic cell adhesion involved in cytoadherence to microvasculature, mediated by parasite protein
into GO:0020035 cytoadherence to microvasculature, mediated by symbiont protein

**Comment by mah11** [comment]
> pollen tube adhesion: remove multi organism process parent (the same organism can fertilize itself in plants)

This is dredged up from way back in my memory, so check with a plant person, e.g. @tberardini, rather than relying on me, but:

This might have the multi-organism process parent because the pollen is considered an organism itself, separate from the plant the pollen tube adheres to (whether that is or isn't the same plant that produced the pollen). The Plant Ontology has pollen is_a microgametophyte is_a whole plant ...

**Comment by tberardini** [comment]
>This might have the multi-organism process parent because the pollen is considered an organism itself.

Yup.  So the multi-organism interaction in pollen tube adhesion is between (1) organism A: the pollen from which the pollen tube grows and (2) organism B: the plant with the stigma on which the pollen has landed and where the pollen tube is doing its thing.  The pollen in (1) may have originated from the same plant as (2) but is still an entirely separate organism.

Weird and wonderful plants and their alternation of generations.

**Comment by pgaudet** [comment]
Few more fixes to this branch: 
 - [x]  pollen tube adhesion -> add parent 'intraspecies interaction between organisms' (to replace 'GO:0098740 multi organism cell adhesion')
- [ ] I think I can also merge 
GO:0000501 flocculation via cell wall protein-carbohydrate interaction 
 into : GO:0000128 flocculation
-> all flocculation takes place via cell wall protein-carbohydrate interactions; doesn't it ? @ValWood 

Thanks, Pascale

**Comment by ValWood** [comment]
I think that's OK.  It's a bit weird to say "protein-carbohydrate interactions"
AFIAK it's the sugar moiety of a glycoprotein interacting with the sugar moiety of a glycoprotein

**Comment by pgaudet** [comment]
That makes me remove the taxon constraint 
'GO:0000501 flocculation via cell wall protein-carbohydrate interaction	NCBITaxon:4751	ONLY IN Fungi' 

Maybe I could replace it by having NEVER IN METAZOA for the parent 
'adhesion between unicellular organisms'
Which includes children:  'agglutination involved in conjugation' and flocculation

Does that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yep, plus never in plant.

**Comment by mah11** [comment]
> I think I can also merge
GO:0000501 flocculation via cell wall protein-carbohydrate interaction
into : GO:0000128 flocculation
> -> all flocculation takes place via cell wall protein-carbohydrate interactions; doesn't it ? 

Well, there's the other subclass of GO:0000128, flocculation via extracellular polymer ! GO:0032128. It has been a *very* long time since I looked into it, but I don't recall it being clear whether the GO:0032128 flavor of flocculation does or doesn't work via the same kinds of interaction described for GO:0000501.

I have found a [more recent paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4551231/), and reaffirmed that it's hard to find info on truly biological instances of bacterial flocculation because search results throw up a ton of stuff about wastewater treatment ...

**Comment by pgaudet** [comment]
Thanks Midori. So, I will leave this until get get more information. This is what we now have: 
> 'adhesion between unicellular organisms'
          'agglutination involved in conjugation'
                    'agglutination involved in conjugation with cellular fusion'
                    'agglutination involved in conjugation with mutual genetic exchange'
          'conjugant formation'
          flocculation
                    'galactose-specific flocculation'
                    'mannose-specific flocculation'

with the parent class, 'adhesion between unicellular organisms', having a 'never in Metazoa/never in Viriplantae' taxon restriction. 

Does that seem right ? 

Thanks, Pascale

**Comment by mah11** [comment]
I guess so ... at least, I'm not aware of anything that makes any of that look wrong.

**Comment by pgaudet** [comment]
That works for me !! Thanks for checking.
