### ISSUE TITLE
regulation terms for GO:1990758    mitotic sister chromatid biorientation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18821]
GO:1990758    mitotic sister chromatid biorientation

(positive only)

reference
Nature. 2010 Oct 7;467(7316):719-23. doi: 10.1038/nature09390. Epub 2010 Aug 25.
Phosphorylation of the CPC by Cdk1 promotes chromosome bi-orientation.
Tsukahara T1, Tanno Y, Watanabe Y.

PMID: 20739936

**Comment by ValWood** [comment]
Could you add this term for me?
tks,
val

**Comment by ValWood** [comment]
Any chance I could get this term? I can't complete a community session because 4 annotation require the term.
Cheers
Val

**Comment by ValWood** [comment]
I also required 

positive regulation of
GO:0072356 | chromosome passenger complex localization to kinetochore

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140429
+name: positive regulation of mitotic sister chromatid biorientation
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of mitotic sister chromatid biorientation, the mitotic cell cycle process in which sister chromatids establish stable, end-on attachments to the plus ends of microtubules emanating from opposite spindle poles, oriented such that separation can proceed." [PMID:20739936]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:1990758 ! mitotic sister chromatid biorientation
+created_by: pg
+creation_date: 2020-02-19T05:16:40Z
+
+[Term]
+id: GO:0140430
+name: positive regulation of chromosome passenger complex localization to kinetochore
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of a chromosome passenger complex localization to kinetochore." [PMID:20739936]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0072356 ! chromosome passenger complex localization to kinetochore
+created_by: pg
+creation_date: 2020-02-19T05:19:45Z
