### ISSUE TITLE
spore dispersal

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18823]
GO:0075325    spore dispersal on or near host
GO:0075326    active spore dispersal on or near host
GO:0075327    passive spore dispersal on or near host

suggest
i) merge into a single term (no annotations to any so far but the passive term is unlikely to be required)

ii) This seems to be a single species process? Does it really belong in the multispecies branch?

**Comment by ValWood** [comment]
mechanisms wind, gravity, rodents, insects  these aren't gene dependent processes.

**Comment by ValWood** [comment]
I'm presuming this is a fungal term?

**Comment by pgaudet** [comment]
Let's merge into the parent and rename 'spore dispersal'. 
OK ?

**Comment by pgaudet** [comment]
https://en.wikipedia.org/wiki/Spore#Dispersal

**Comment by ValWood** [comment]
OK sounds good. We only need one term which  will cover any Gene products involved in active dispersion.

**Comment by pgaudet** [comment]
The parent - 'interaction with host' is then incorrect. 

How about 'reproduction' ??

**Comment by ValWood** [comment]
I don't think spore dispersal is really part of reproduction though...
@mah11  ?

**Comment by ValWood** [comment]
Localization? seems weird but that is what it is?

**Comment by mah11** [comment]
The selective advantage conferred by dipersing spores is in reproduction ...

**Comment by ValWood** [comment]
Of course!

**Comment by pgaudet** [comment]
OK I'll do 
spore dispersal is_a reproduction 

and we can edit later if we have a better solution. 

Thanks, Pascale
