### ISSUE TITLE
GO:0075141    maintenance of symbiont tolerance to host environment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18827]
Another hidden branch:

GO:0075141    maintenance of symbiont tolerance to host environment
Any process that contributes to the maintenance of a physiologic state in which the symbiont immune system does not react destructively against the components of its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

GO:0075238    maintenance of symbiont tolerance to host pH environment | is_a
-- | --
GO:0075143    maintenance of symbiont tolerance to host redox environment | is_a
GO:0075144    maintenance of symbiont tolerance to host iron concentration | is_a
GO:0075142    maintenance of symbiont tolerance to host oxygen tension environment | is_a
GO:0075145    maintenance of symbiont tolerance to host defense molecules | is_a
GO:0075146    maintenance of symbiont tolerance to host osmotic environment

These should either be obsoleted or merged into the appropriate "immune defense response" terms (the definition even mentions avoiding the host immune system!

 There are only 2 existing annotations and these are both  describing alterations to host metabolism

**Comment by pgaudet** [comment]
Annotations: 
(1)  @Achchuthan 
MTBBASE  icl UniProtKB:P9WKK7, PMID:10963599 

annotated to 'maintenance of symbiont tolerance to host environment'

The abstracts states "persistence of M. tuberculosis in mice is facilitated by isocitrate lyase (ICL), an enzyme essential for the metabolism of fatty acids. Disruption of the icl gene attenuated bacterial persistence and virulence in immune-competent mice without affecting bacterial growth during the acute phase of infection."

I dont have access to the full text (springer link gives an error), so I dont know what is shown. 

Maybe 'GO:0042783  evasion of host immune response' correctly capture the results ? 

----
(2)  @pgarmiri 
MT0649 UniProtKB:P96911, PMID:18979228 
The abstracts states " This suggests the gene may be involved in regulation of fatty acid synthesis and M. tuberculosis resistance to the surfactant defense of its host." , and this is shown in the paper by testing resistance to SDS. 

Would 'response to host defenses' suit better ? 

It seems more informative to me. 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
Thanks for the suggestion. I have updated the annotation.
Regards,
Penelope

**Comment by pgaudet** [comment]
I just looked at the full text of the MTBBASE annotation. The isocitrate lyase (ICL) protein is essential for symbiont survival since it makes fatty acids. Essentially disruption of basic metabolism of the symbiont can be used as a therapeutic target, which makes sense, but should be captured differently. 

FOR NOW: I propose to merge all the terms into the parent (which is the only one used), and change the label to 'symbiont tolerance to host environment'. 

To be revisited later, unless @mgiglio99 @dsiegele have better suggestions. 

Thanks, Pascale

**Comment by pgaudet** [comment]
GO:0075145    maintenance of symbiont tolerance to host defense molecules 
> will merge into GO:0075140   response to host defense molecules

**Comment by ValWood** [comment]
I agree. I wouldn't annotate this as a  GO pathogen host term. I would annotate the role in fatty acid metabolism. I would also annotate phenotypes for survival (inviable or whatever).

**Comment by pgaudet** [comment]
- 'symbiont tolerance to host environment' 
-> I will change parent from 'response to host' to 'interspecies interactions between organisms'

**Comment by Achchuthan** [comment]
Hi @pgaudet 

Not sure why i was tagged in this issue. The annotation was from MTBBASE for Mycobacterium tuberculosis rather than from GeneDB.

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Ohhh ! Apologies @Achchuthan
