### ISSUE TITLE
A question about tRNA transcription termination

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18837]
I am looking at the annotations to
https://www.pombase.org/reference/PMID:15632064

rpc11 (pol III transcription)
Analyses of two zinc ribbon mutants indicate that they are deficient in Pol III RNA 3' cleavage activity and produce pre-tRNASerUGAM transcripts with elongated 3'-oligo(U) tracts that are better substrates for La.

we annotated to
tRNA 3'-trailer cleavage
is this the correct term? or is this term for some post-transcriptional cleavage that occurs during maturation?  (these  sound like  activities (MF)  anyway, but they are biological process ontology BP?)

I ask because there is no cleavage term related to termination,

should we just be using
GO:0016892   endoribonuclease activity, producing 3'-phosphomonoesters
part_of
termination of RNA polymerase III transcription

@hdrabkin  do you know?
cheers
val

**Comment by hdrabkin** [comment]
Well, although this seems to be a part of pol III, my (possibly outdated )understanding, as outlined in the intro for this paper, was that termination and 3' processing were separate, in that La bound the 3'oligo U region of the primary transcript to that 5' processing could proceed before 3'.  However, it seems like it can be 'co-termination' especially for tRNAs with oligo-t tracts that do not terminate easily (as perhaps reflect on being able to easily bind La). 
So I think you could use tRNA 3'-trailer cleavage.

**Comment by ValWood** [comment]
OK I will keep it as it is. Thanks's Harold.

**Comment by ValWood** [comment]
but if |
I use "tRNA 3'-trailer cleavage" there is no annotation to transcription.
and it's a pol III subunit?

**Comment by hdrabkin** [comment]
but mutants still produce pre-tRNASerUGAM transcripts with elongated 3'-oligo(U) t? So transcription is unaffected. Not all subunits have to do with the transcription then. Some help to get the transcript off of the site.

**Comment by ValWood** [comment]
But it must be *something* to do with transcription ?

This is quite old but I expect it  hasn't changed much:

RNAPIII: a terminator on its own?
.....In vitro transcription using RNAPIII lacking the RNAPIII-specific subunits C11, C37, and C53 (RNAPIIIΔ) can support transcription initiation but fails to terminate properly (Landrieux et al. 2006). Adding back the heterodimer C37/C53 was sufficient to allow recognition of the terminator and to correct the termination defect, but not for transcription reinitiation. It was proposed that the C37/C53 complex reduces the elongation rate of RNAPIIIΔ, allowing for an increased pausing time at the terminator elements, which leads to release of the transcript and RNAPIII (Fig. 5). C11 is an essential subunit that mediates the intrinsic RNA cleavage activity of RNAPIII (Whitehall et al. 1994) and shows homology with the RNAPII subunit Rpb9 and to RNAPII elongation factor TFIIS (Chedin et al. 1998). Landrieux et al. (2006) showed that C11 RNA cleavage activity is not required for correct recognition of the RNAPIII terminator elements and release of the newly synthesized transcript. However, C11 itself, but not its cleavage activity, is required for reinitiation (Chedin et al. 1998; Landrieux et al. 2006). These experiments strongly suggest that termination and cleavage of the RNA precursor are not coupled in the RNAPIII transcription process. Consistent with its role in termination, structural analysis of RNAPIII showed that the C37/C53 heterodimer is positioned at the outer end of the DNA-binding cleft, toward the front of the EC, allowing the complex to sense the incoming DNA (Fernandez-Tornero et al. 2007).


Figure 5.
RNAPIII termination. Most of the termination activity is triggered by RNAPIII itself. The subunits C37 and C53 are essential for termination. The heterodimer C37–C53 might play a role in reducing the elongation rate of RNAPIII, allowing for an increased pausing time at the terminator, composed of a stretch of four to five Ts in the coding DNA strand. Several auxiliary factors, such as La, PC4, Topoisomerase I, or TFIIIC, are proposed to participate in RNAPIII termination in mammals.

**Comment by ValWood** [comment]
I found a paper that I can use to annotate the pombe role in termination, via complementation

The RNA cleavage activity of RNA polymerase III is mediated by an essential TFIIS-like subunit and is important for transcription termination

but C11 probably  isn't directly  "involved_in" (see above), the mutant stuffs termination because the transcript isn't cleaved.  It's required for reinitiation, so it's clearly part of transcription. I don't know how to annotate this... will check with transcription group.


@colinlog 
@pgaudet

**Comment by colinlog** [comment]
GO:0006386 'Termination of RNA pol III transcription' would seem appropriate to me for BP. 

The transcription termination sub-process is intrinsically the stage prior to transcription initiation from the point of view of the polymerase enzyme complex. Always. Except for the first time a newly translated and assembled RNA pol III complex does transcription. Of course it may be initiation on another piece of DNA than the one that was just transcribed. 

The transcription termination sub-process can involve a MF endoribonuclease function (for RNA pol II this is coupled to polyA site cleavage, for RNA pol I at rRNA genes the processing is well studied and involves endoribonuclease activity too, I thought, with redundance in possible activities etc...). 

Still, the most parsimonious alternative termination model is simply release of the RNA polymerase III complex and it's associated nascent RNA from the DNA template when a run of 4 Thymidines is encountered (i.e.; the current textbook model), followed by release of the 3' end of the RNA molecule from the enzyme. However, 'real' molecular biology appears to involve more 'coordinated handing over of the RNA' by physically coupling the steps downstream of synthesis to the processing steps via a ballet of transient protein-protein and RNA-protein binding events. 

All in all, 
For this one subunit of the RNA polymerase enzyme complex with a TFIIS-like domain:

BP GO:0006386, which is a child of GO:0006351 - 'transcription, DNA templated'. 
- and 
MF: ribonuclease, as suggested by @hdrabkin (check if the catalytic residues have been tested for the evidence code?)
- and
CC: RNA polymerase III complex

**Comment by ValWood** [comment]
The above publication implies that the 'cleavage activity' isn't necessarily performed by C11 though...

In this study, we characterize a new, small subunit of yeast Pol III, C11, homologous to Pol I A12.2 and Pol II B12.6 subunits and to elongation factor TFIIS. Subunit C11 is essential for cell viability and is required for the intrinsic 3′ exonucleolytic cleavage activity of Pol III ternary complexes. In vitro, a Pol III lacking C11 displays strong defects in elongation and termination properties. The data indicate that Pol III intrinsic cleavage activity is important for transcription termination. This observation may account for the essential character of the C11 subunit. A model is presented in which we propose that C11 allows the enzyme to switch between an RNA elongation and RNA cleavage mode, which facilitates termination, although transcript hydrolysis is unlikely to be a step in termination mechanism.


It doesn't *look* like a nuclease either

**Comment by colinlog** [comment]
can you use 'positively_regulates', or 'capable_of_part_of', or not?  

I guess, regulates is a bizarre use of the word that means 'enables_extrinsically triggered_switch'. The C11 subunit would be best described as, 'part of a metastable complex', whereby the transition to  the cleavage conformation requires the C11 subunit.  

What I wonder is: Was the Pol III subunit harbouring the ' intrinsic cleavage activity' identified? because then it would be easier to assign MF roles and house them under the GO:0006386 process with CC the Pol III complex. Otherwise, the complex can get the 'intrinsic activity, which is part_of for all the known subunits??

**Comment by ValWood** [comment]
Well there is an intrinsic ribonuclease for , the 'proofreading activity' maybe this cleavage uses this activity?
I will find out more... I know who I can ask. I can't immediately find anything .

**Comment by ValWood** [comment]
@hdrabkin  I will take this. It isn't high priority.

**Comment by colinlog** [comment]
@ValWood  @hdrabkin PMID: 12914699 for RNA polymerase II. They diffused TFIIS into PolII crystals and show the the RNA realigns in the active site. they conclude that "Our results support the idea that Pol II contains a single tunable active site for RNA polymerization and cleavage, in contrast to DNA polymerases with two separate active sites for DNA polymerization and cleavage". And TFIIs does the realignment. I would  infer that the TFIIS domain in the C11 RNA pol III subunit works similarly.

**Comment by ValWood** [comment]
I'll close this. I'm happy enough with the current annotation for rpc112.  This detail is very micro so closing...
