### ISSUE TITLE
SAP kinase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18838]
GO:0016909    JSON
SAP kinase activity
Definition (GO:0016909 GONUTS page)
Catalysis of the phosphorylation of proteins. A family of protein kinases that perform a crucial step in relaying signals from the plasma membrane to the nucleus. Strongly activated by stress signals such as heat or osmotic shock, DNA-damaging agents, inhibitors of protein synthesis and pro-inflammatory cytokines.

Our MAP kinases are annotated to this term, in addition to MAP kinase.
Do we need this term?

24 EXP annotations and they all look like MAP kinases?

(I'm going to move the pombase  ones (3)  to MAP kinase to be consistent with the other annotations)

**Comment by ValWood** [comment]
It's a little strange actually.

SAP kinase is a descendant of MAP kinase.

But MAP kinase is defined:
GO:0004707    MAP kinase activity
Molecular Function
Definition (GO:0004707 GONUTS page)
Catalysis of the reaction: protein + ATP = protein phosphate + ADP. This reaction is the phosphorylation of proteins. Mitogen-activated protein kinase; a family of protein kinases that perform a crucial step in relaying signals from the plasma membrane to the nucleus. They are activated by a wide range of proliferation- or differentiation-inducing signals; activation is strong with agonists such as polypeptide growth factors and tumor-promoting phorbol esters, but weak 
(in most cell backgrounds) by stress stimuli.


This isn't really true. Sty1 is a MAP kinase in pombe and it responds to stress stimuli.
Some but not all MAP kinases are stress-activated.
But here we are talking about the activity, not the specific MAPK- pathway and what activates it?

**Comment by ValWood** [comment]
Anyway we wend up with this. Same thing, described in different ways:

<img width="1011" alt="Screenshot 2020-02-12 at 15 51 29" src="https://user-images.githubusercontent.com/7359272/74351986-c6e91100-4daf-11ea-97eb-d12c9a870e97.png">

**Comment by ValWood** [comment]
I would suggest to merge SAP kinase into MAP kinase and refine the def of MAP kinase to be generic.

It could be defined as the terminal kinase in a MAP kinase cascade?
https://www.ebi.ac.uk/QuickGO/term/GO:0000165
An intracellular protein kinase cascade containing at least a MAPK, a MAPKK and a MAP3K.

**Comment by pgaudet** [comment]
There are 2 FlyBase NAS annotations and 1 SWIE annotation - if there are not objections I'll go ahead with the merge. 

@hattrill @pgarmiri

**Comment by pgaudet** [comment]
Removed synonyms that are not cited in EC: 

-synonym: "Dp38" RELATED [EC:2.7.11.24]
-synonym: "LeMPK3" RELATED [EC:2.7.11.24]
-synonym: "MAP-2 kinase activity" NARROW [EC:2.7.11.24]
-synonym: "MP kinase activity" NARROW []
-synonym: "Mpk2" NARROW []
-synonym: "p38" NARROW []
-synonym: "p38-2" RELATED [EC:2.7.11.24]
-synonym: "p38delta" RELATED [EC:2.7.11.24]
-synonym: "p42 mitogen-activated protein kinase activity" NARROW [EC:2.7.11.24]
-synonym: "p42mapk" RELATED [EC:2.7.11.24]
-synonym: "p44mpk" RELATED [EC:2.7.11.24]
-synonym: "PMK-1" RELATED [EC:2.7.11.24]
-synonym: "PMK-2" RELATED [EC:2.7.11.24]
-synonym: "PMK-3" RELATED [EC:2.7.11.24]
-synonym: "pp42" RELATED [EC:2.7.11.24]
-synonym: "pp44mapk" RELATED [EC:2.7.11.24]
-synonym: "SAPK2" NARROW []
-synonym: "STK26" RELATED [EC:2.7.11.24]


---- 
GO:0004674 protein serine/threonine kinase activity

and added Rhea xrefs to 

+xref: RHEA:17989
+xref: RHEA:46608

**Comment by hattrill** [comment]
@pgaudet ok with merge
