### ISSUE TITLE
GO:0140418. effector-mediated modulation of host process by symbiont

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18842]
missing parent child relationship

GO:0140418 effector-mediated modulation of host process by symbiont

GO:0140415    effector-mediated modulation of host defenses by symbiont

@pgaudet I am sure you did this. I saw  it? Was there some reversion?

**Comment by pgaudet** [comment]
You mean I've added the parents ? 
I don't know - but I can add them back

**Comment by ValWood** [comment]
Maybe this one was never done. It needs adding anyway.
