### ISSUE TITLE
problems with Taxon constraints?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18844]
GO taxon checks show
•	WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- PomBase SPAC13G6.06c gcv2 GO:0019464 GO_REF:0000024 ISO SGD:S000004801 P glycine cleavage complex subunit P (predicted) protein taxon:4896 20040618 PomBase

GO:0019464 is valid for fission yeast.

However, when I look at the term

GO:0042133 | neurotransmitter metabolic process | Never in Taxon | 4895 | Schizosaccharomyces

Some crazy reasoning going  on there...

**Comment by ValWood** [comment]
A few others too
GO:0097054
GO:0019483
GO:0009450
chebi roles again

**Comment by mah11** [comment]
Yes, this is the ChEBI roles thing again, so not really any need for another ticket.
