### ISSUE TITLE
 new term request: Eoxin biosynthetic process / Eoxin A4 biosynthetic process 

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#18848]
Hi,
Pubmed 23242647 describes the synthesis of eoxin A4 by ALOX15 from 15S-hydroperoxy-eicosatetraenoic acid (15S-HPETE).
Could you please create these new tems?
Many thanks.
Guilaine

**Comment by hdrabkin** [comment]
@Argoudpuy ; we need a little more info (standard request stuff). 
Suggested term def.
Suggested is_a parent.

**Comment by pgaudet** [comment]
As far as I could tell eoxin A4 synthesis corresponds to GO:1901753 leukotriene A4 biosynthetic process, while eoxin synthesis is GO:0046456 icosanoid biosynthetic process

I added some synonyms.
