### ISSUE TITLE
Some labels missing 'activity' in MF branch

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#18840]
Hi,
GO:0043495 'protein membrane adaptor' and its 3 children seem to be missing 'activity' at the end of their labels.
Same for GO:0044183 'protein folding chaperone', and, possibly, GO:0031386 'protein tag'.
Other adaptor and chaperone MF terms in GO are always appended with 'activity'.
Thanks,
Paola

**Comment by pgaudet** [comment]
I hadn't put 'activity' because those didn't seem like they could be mistaken for BPs. I am not sure it is a strong rule to have 'activity' on every MF. Let's discuss this on the next ontology call.

**Comment by pgaudet** [comment]
I made a spreadsheet of all types of 'activities' that are NOT under the 'catalytic activity branch: 

https://docs.google.com/spreadsheets/d/1t4Oene3WmUIFaAAH2S37k-Pa81qdU2V5IKVq8eYYSL8/edit#gid=0

My plan would be to fix branch by branch, removing 'activity' as appropriate. 

To be approved by the ontology group. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Pascale: to check if the usage matches the design patterns.

**Comment by ValWood** [comment]
will be fixed by https://github.com/geneontology/go-ontology/issues/15323
