### ISSUE TITLE
Obsolete GO:0150100 'RNA binding involved in posttranscriptional gene silencing' and  GO:1903231 'mRNA binding involved in posttranscriptional gene silencing' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18851]
Replace by: (parents) 
Use extension to capture 'part of x'

**Comment by pgaudet** [comment]
Hi, 

This came up gain on the microRNA/transcripion call today with @hattrill @RLovering and @gantonazzo 

We propose again to obsolete these two terms. 

There are 
* GO:0150100 RNA binding involved in posttranscriptional gene silencing -> 0 annotations
*  GO:1903231 mRNA binding involved in posttranscriptional gene silencing   -> ~ 1500 annotations
* * 1303	UCL (BHF, ARUK and ParkinsonsUK)
* * 166	FlyBase
* * 26	ZFIN
* * 7	MGI
* * 6	DIBU
* * 1	EcoCyc
* * 1	TAIR
Annotations to review are here: https://github.com/geneontology/go-annotation/issues/3976

We suggest that people replace all annotations by GO:0003729 mRNA binding + part of GO:0016441 posttranscriptional gene silencing or a child. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Nov 29, to leave time for groups to make corrections. Unless objections are received by Nov 29, 2021, we will assume that you agree to this change.
You may comment on the ticket: https://github.com/geneontology/go-ontology/issues/18851

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Alex 
sorry I have changed my mind - please do not make the changes I requested above, as I would like a MF activity term for the ncRNAs not just a binding term.
See ticket https://github.com/geneontology/go-ontology/issues/22441
Thanks
Ruth

**Comment by RLovering** [comment]
Hi Pascale please do not delete this term
Thanks
Ruth

**Comment by pgaudet** [comment]
Will not obsolete - see  #22441
