### ISSUE TITLE
Query  'post-mating behavior'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18877]
Hello @hattrill 

Looking at 'GO:0045297 post-mating behavior' - The specific behavior of an organism following mating.

There are only fly annotations to this term. Can you provide a more precise definition ? Otherwise maybe we would consider obsoleting. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also related to this: 'GO:0060403 post-mating oviposition' (and regulation children): The deposition of eggs, either fertilized or not, upon a surface or into a medium, following mating.

Is this really a different process than the parent oviposition? 
Thanks again, Pascale

**Comment by hattrill** [comment]
I will have a look. I am no expert of the post-mating behaviour of flies, but I guess that this doesn't refer rolling over and going to sleep!

**Comment by hattrill** [comment]
Looking at the annotations to post-mating behavior, I can't see anything worth keeping. It's not been used that much. 
As for GO:0060403 post-mating oviposition & reg term, I think that you can merge this with the parent - GO:0018991 oviposition, as the definitions are practically identical. I will review the annotations, as some should be dropped.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0045297 post-mating behavior. The reason for obsoletion is that this term is not precisely defined. 

Annotations have been removed. There are no mappings to this term. This term is not present in any subsets. 

Any comments can be made to the ticket:  https://github.com/geneontology/go-ontology/issues/18877

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 28th, 2020. Unless objections are received by February 28th, 2020, we will assume that you agree to this change.

Thanks, Pascale
