### ISSUE TITLE
trim down legorel.owl

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#18873]
go-lego, used for inference in Noctua, imports both all of RO as well as legorel.owl. legorel.owl duplicates a lot of axioms from RO, which may become stale. We should see what is unique in legorel.owl and just retain that (for example linking up to `http://purl.obolibrary.org/obo/LEGOREL_0000000`, which I think is used by Noctua.

**Comment by pgaudet** [comment]
Can we not use a single 'non-standard' ontology (go_rel /legorel /ropending )?

**Comment by balhoff** [comment]
Totally agree, hopefully we can get rid of this.

**Comment by balhoff** [comment]
The published `legorel.owl` file seems to be `legorel-edit.owl`, merged with its imports (RO). The only content in legorel is a list of relations asserted to be subproperty of `LEGOREL_0000000` ("lego relation"). This term is passed to Minerva at startup as "important relation parent". I'm not sure yet whether Noctua still relies on this information.
