### ISSUE TITLE
propose obsoletion: random coil DNA binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18879]
Molecular Function
Definition (GO:0003695 GONUTS page)
Interacting selectively and non-covalently with DNA in a random coil configuration.
Secondary IDs
GO:0016017

This is a strange term because a random coil is a structure orders of magnitude larger than a DNA binding motif?
No annotations, no reference.

**Comment by hdrabkin** [comment]
The term doesn't mention 'motif' but I don't think a motif needs to be a small linear region;
Currently reading these to see why the term may have been made.

Transition of Double-Stranded DNA Chains between Random Coil and Compact Globule States Induced by Cooperative Binding of Cationic Surfactant
and 
Architecture of the Escherichia coli nucleoid
('ll find the PMIDS )

**Comment by ValWood** [comment]
But even if microbial DNA transitions between these states, and a protein is bound to it, that doesn't mean that the protein is binding to a "random coil" it means the protein is binding to the DNA, and the DNA is in a  random coil configuration. Two totally different things ?

**Comment by hdrabkin** [comment]
which is why I'm reading to get a feel for why the term was made. @mah11 is has your tag on it. Do you by chance have any recollection? It's may be buried in old sourceforge .

**Comment by hdrabkin** [comment]
But @ValWood  your comment makes sense.

**Comment by hdrabkin** [comment]
But @ValWood  your comment makes sense. However, a protein could be binding DNA whose configuration is in random coil.

**Comment by pgaudet** [comment]
> However, a protein could be binding DNA whose configuration is in random coil.

Sure, but is that what provides the specificity for the binding ?

**Comment by ValWood** [comment]
> Sure, but is that what provides the specificity for the binding ?

Yes, I agree, it would not make sense to have such a term.
If a DNA molecule is a random coil (what species  does this apply to? bacteria?), then ANY DNA binding protein  which bound to this molecule would be "binding to a random coil DNA).  But nobody ever used it - you can see why...

**Comment by ValWood** [comment]
Added 2001. In 19 years, nobody used it.

**Comment by hdrabkin** [comment]
I tried searching SF to no avail. Did you find the original ticket?

**Comment by ValWood** [comment]
Nope, I looked to. Couldn't find it...

**Comment by mah11** [comment]
GO:0003695

> @mah11 is has your tag on it. Do you by chance have any recollection?

One can tell from the ID that this term is one of the Original Set that seeded GO (for which the main source was Michael Ashburner's brain). That means that there is no ticket requesting or describing its addition; it has existed with its ID since early 1999 (not 2001), and therefore predates having GO editors or taking term requests by any route, let alone monitoring them sensibly in any online tracking system.

I have no specific recollection other than that, so I infer that the definition has my xref because I included it in a big push I did some years ago to give every blasted term a text definition. I didn't pause to worry about whether any of the old-guard terms should go obsolete instead; if I had I bet the definition work would never have been finished!

None of the above should be interpreted as an argument for or against keeping the term. If it's not useful I don't mind if it goes the way of the dodo, or the gene-product-snuck-into-MF.

**Comment by hdrabkin** [comment]
Thanks @mah11, your recollections are in fact quite interesting. I have a go-friends announcement saved to a file if we all agreee to give it the axe?

**Comment by ValWood** [comment]
yes please do!

**Comment by hdrabkin** [comment]
@pgaudet shall I do the honors?

**Comment by pgaudet** [comment]
Sure ! and please copy the announcement on 
https://github.com/geneontology/go-announcements/issues

Thanks, Pascale

**Comment by colinlog** [comment]
On February 19, in Rende (Italy) , during the GREEKC meeting, transcription factor specialist Arttu Jolma argued that "
..
AT-hooks are not really DNA-binding domains,
folded protein structures that have evolved
only once and then formed families through
duplication and divergence.

They are instead unstructured peptide motifs
that are simple enough to have evolved
countless of times in situ but can yet display
some limited DNA binding specificity
..
"

According to him, via AT-rich DNA minor groove interaction. He could see 237 such ..[RPK]GRP[RPK].. domains in the human proteome (this is unpublished as yet, work of Arttu Jolma with Tim Hughes (Toronto)

If this is relevant here, we could perhaps (?) change the GO term's description from

-- random coil DNA binding

to 

-- unstructured peptide motif binding to AT-rich DNA (AT-hook)

**Comment by pgaudet** [comment]
Thanks @colinlog 
We already have   'GO:0003680  AT DNA binding' that I think captures what you are suggesting. 
although maybe that term can be improved (def currently is "Interacting selectively and non-covalently with oligo(A) and oligo(T) tracts of DNA (AT DNA).") 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Attempting to obsolete today
