### ISSUE TITLE
NTR: DNA-(abasic site) binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18878]
NTR: DNA-(abasic site) binding
synonym exact: DNA-(apurinic site/apyrimidinic site) binding
synonym exact: DNA AP site binding
synonym narrow:  DNA-(apurinic site) binding
synonym narrow:  DNA-(apyrimidinic site) binding

definition
Interacting selectively and non-covalently with a DNA site that has neither a purine nor a pyrimidine base. 
Apurinic sites can form spontaneously or when DNA glycosylase removes a damaged base.

Parent
GO:0003684    damaged DNA binding

**Comment by ValWood** [comment]
PMID:23245849

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140431
+name: DNA-(abasic site) binding
+def: "Interacting selectively and non-covalently with a DNA site that has neither a purine nor a pyrimidine base. Apurinic sites can form spontaneously or when DNA glycosylase removes a damaged base." [PMID:23245849]
+comment: Created new term, see https://github.com/geneontology/go-ontology/issues/18878.
+synonym: "DNA AP site binding" EXACT []
+synonym: "DNA-(apurinic site) binding" NARROW []
+synonym: "DNA-(apurinic site/apyrimidinic site) binding" EXACT []
+synonym: "DNA-(apyrimidinic site) binding" NARROW []
+is_a: GO:0003684 ! damaged DNA binding
+created_by: pg
+creation_date: 2020-02-19T05:30:09Z
