### ISSUE TITLE
Consider swapping label and synonym of GO:0008623 CHRAC

### ISSUE THREAD

**Issue by paola-scibite** [geneontology/go-ontology#18883]
Hi
(In case you're wondering, this is Paola Roncaglia on a SciBite-specific GitHub account...)
I came across GO:0008623 CHRAC
"An ISWI complex that contains an ATPase subunit of the ISWI family (SNF2H in mammals, Isw2 in S. cerevisiae), an ACF1 homolog, and additional small histone fold subunits (generally two of these, but Xenopus has only one and some additional non-conserved subunits). CHRAC plays roles in the regulation of RNA polymerase II transcription and in DNA replication and repair."
Exact synonym: chromatin accessibility complex
I know that labels and exact synonyms are technically equivalent, but many users are primarily exposed to labels only. Please consider swapping label and synonym in this case - the label is a bit obscure/acronym while the synonym is more explicit. It'd also be nice to include "chromatin accessibility complex" in the definition to clarify where the acronym CHRAC comes from. Thanks!

**Comment by ValWood** [comment]
Hi Paola,

I don't think the labels should swap here as there is a precedent for calling the chromatin remodelling complexes by their acronyms in GO, and these are the primary labels that researchers use.

check out the siblings

GO:0016590    ACF complex | is_a
GO:0016589    NURF complex | is_a
GO:0090536    NoRC complex | is_a
GO:0090537    CERF complex | is_a
GO:0090535    WICH complex | is_a
GO:0008623    CHRAC | is_a
GO:0016587    Isw1 complex | is_a
GO:0031213    RSF complex

and parents etc. 

However, this should have "complex" as part of its term name!

CHRAC is useful as an  unambiguous as a name (many  chromtin complexes will be involved in accessibility at some level, infact I think  chromatin accessibility complex should probably be a broad synonym ). ...and people should read definitions if they need to be sure what a term means.

I agree that "chromatin accessibility complex"  should be used in the definition too.

v

**Comment by paola-scibite** [comment]
@ValWood 
Thanks for your feedback. Yes, I was prompted by the absence of "complex" in the label, but if you called it 'CHRAC complex' that would translate to 'chromatin accessibility complex complex', which is why I didn't suggest that option ;-) 
I agree that if the wording 'chromatin accessibility complex' is not unambiguous, then that wouldn't be a good label by itself. I'll leave this to you. Cheers!

**Comment by ukemi** [comment]
The goal is for the primary term label to be the one that is most often used by the community. @ValWood, it sounds like these should remain as is?

**Comment by ValWood** [comment]
I think its OK as it is, but adding "complex" would be OK too... I'm OK with either.

**Comment by ukemi** [comment]
I will leave as is, keeping in mind that although the labels of the terms are designed to represent the handle that the community would use to identify the class, the definition is what distinguishes the term.
