### ISSUE TITLE
NTR:peroxynitrite isomerase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#18885]
Dear GO editors,
could you please create a term "peroxynitrite isomerase activity"
Molecular Function
Definition:
Catalysis of the reaction: peroxynitrite = nitrate. 
as a child of GO:0016853 isomerase activity

The activity is described in PubMed=30524950. 

Thanks for your help.
Lionel

**Comment by pgaudet** [comment]
no Rhea or EC ?

**Comment by pgaudet** [comment]
Is this different from GO:0072541 peroxynitrite reductase activity ? Catalysis of the reaction: 2 R-SH + ONOO- = R-SS-R + NO2- + H2O.

**Comment by lbreuza** [comment]
Hi Pascale,
Rhea is [Rhea:63116] but is not yet public. I will curate it to a partial EC=5.99.-.- which stands for "other isomerases".
The reaction is for sure difference from GO:0072541. It is not a reductase but a heme-dependent isomerase that takes peroxynitrite and converts it in nitrate without any other compound involved. This is why it is a child of GO:0016853 isomerase activity.
The data are not yet really solid but it makes sense to capture this information.
Thanks for your help
