### ISSUE TITLE
NTR:  5’-hydroxyl dinucleotide hydrolase 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18881]
Term:  5’-hydroxyl dinucleotide hydrolase 
Definition: Catalysis of the hydrolysis of phosphodiester bonds in 5'OH-RNA according to the reaction
5'OH-RNA + H20 =  5'OH-NpN  (dinucleotide) + 5'P-RNA

Descendant of:
GO:0004540    ribonuclease activity 
Catalysis of the hydrolysis of phosphodiester bonds in chains of RNA.

Reference: PMID: 31777937 
A novel 5'-hydroxyl dinucleotide hydrolase activity for the DXO/Rai1 family of enzymes.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140432
+name: 5’-hydroxyl dinucleotide hydrolase
+namespace: molecular_function
+def: "Catalysis of the hydrolysis of phosphodiester bonds in 5'OH-RNA according to the reaction 5'OH-RNA + H20 = 5'OH-NpN (dinucleotide) + 5'P-RNA." [PMID:31777937]
+comment: Created new term, see https://github.com/geneontology/go-ontology/issues/18881.
+is_a: GO:0004540 ! ribonuclease activity
+created_by: pg
+creation_date: 2020-02-19T05:50:35Z
