### ISSUE TITLE
small definition tweak? GO:0090503    RNA phosphodiester bond hydrolysis, exonucleolytic

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18880]
GO:0090503    RNA phosphodiester bond hydrolysis, exonucleolytic

is defined
The chemical reactions and pathways involving the hydrolysis of terminal 3',5'-phosphodiester bonds in one or two strands of ribonucleotides.

I think this should say
The chemical reactions and pathways involving the hydrolysis of terminal 3' or 5'-phosphodiester bonds in one or two strands of ribonucleotides.

?

**Comment by mah11** [comment]
I think not, because the phosphodiester bonds that form in RNA normally link the 3' carbon of one sugar to the 5' carbon of another, and that's what the current definition represents.

That said, I've just learned from skimming [this paper](https://doi.org/10.1073/pnas.1406234111) that 2'-5' bonds can also form, so maybe the RNA phosphodiester bond hydrolysis terms (including the grouping term, GO:0090501) should explicitly say "hydrolysis of 2',5'- or  3',5'-phosphodiester bonds ...", assuming that the activities can, in fact, cleave both kinds of bond. If they can only cleave 3',5' bonds the defs are correct.

**Comment by ValWood** [comment]
I was basing my assumption on this descendant:
GO:0004532    JSON
exoribonuclease activity
Molecular Function

Definition
Catalysis of the sequential cleavage of mononucleotides from a free 5' or 3' terminus of an RNA molecule.

So these are referring to different things? One is referring  explicitly to the phosphodiester bond which is always 3'-5' and the other is referring to the direction of nuclease activity which can act on the 5' or 3'. That's a bit confusing (for me)

**Comment by mah11** [comment]
> One is referring explicitly to the phosphodiester bond which is always 3'-5' and the other is referring to the direction of nuclease activity which can act on the 5' or 3'

It's this. The bond is 3'-5'. The "free terminus" is the 5' or 3' end of the molecule (and as opposed to a circular DNA or RNA). The enzyme goes to the 5' or 3' end of a linear molecule, and cleaves a 3'-5' bond to release the end-most nucleotide residue.

An endoribonuclease goes to the middle of a DNA or RNA molecule (linear or circular) and ... wait for it ... cleaves a 3'-5' bond.

**Comment by ValWood** [comment]
I know that is what I said. However, now this is  unequivocally established, there is no difference between the terms

GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
and
GO:0004532 exoribonuclease activity

They are both describing   5' or 3' exoribonucleases which cleave  3'-5' phosphodiester bonds?

How do they differ?

**Comment by ValWood** [comment]
> That's a bit confusing (for me)
referred to the fact that the design patterns were different. I understand biochemistry even if I sometimes pretend not to.

**Comment by pgaudet** [comment]
> GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
and
GO:0004532 exoribonuclease activity
>  How do they differ?

Stating the obvious: one is a BP, the other is a MF. But really we should merge the 1-step BPs. I am not sure

**Comment by ValWood** [comment]
Oh I totally missed that. I might have even .suggested it for a new MF parent!

**Comment by ValWood** [comment]
closing
