### ISSUE TITLE
stearoylation?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#18882]
Hello,

Need some advice and possibly a new term depending on what you think.

In 26214738 there is evidence that human TFRC is stearoylated, and that palmitoyl transferase ZDHCC6 is responsible for this stearoylation.

"Instead, we hypothesized that C18:0 might regulate proteins via covalent binding (‘stearoylation’), analogous to protein palmitoylation.We synthesized C18:0 derivatives with azide or alkyne functionalities, allowing covalent coupling to beads via copper-catalysed azide–alkyne cycloaddition (‘click chemistry’) (Extended Data Fig. 7b). We tested multiple derivatives, and only C17:0–azide induced mitochondrial fusion like C18:0 (Extended Data Fig. 7a). We treated HeLa cells with C17:0–azide for 2 h, lysed them in 8M urea to denature proteins, precipitated the lipid by coupling to beads, and identified covalently bound proteins by mass spectrometry. The most abundant protein in the lipid pulldown was TFR1 (Extended Data Fig. 7b, right), confirmed by immunoblotting (Extended Data Fig. 7c, lanes 1–3). Binding of TFR1 to C17:0–azide was abolished by treating lysates with hydroxylamine pH 7.5, indicating a thioester linkage"

"Palmitoyl-transferases covalently bind C16:0 before transferring
it to substrates. We found one member of this family, ZDHHC6, in our C17:0–azide pulldowns, suggesting that it is a C18:0 transferase. Indeed, knockdown of ZDHHC6 blunted TFR1 stearoylation
(Extended Data Fig. 7c, lane 5)"

Do you think there is enough evidence here to create MF stearoyltransferase activity, sibling to GO:0016409 palmitoyltransferase activity?

**Comment by pgaudet** [comment]
I wonder - since you don't seem so sure, should you annotate to the parent 'GO:0006497 protein lipidation' with some extension (a second 'has_input'?), CHEBI: 'stearoyl' , and we'd create a new term once there are enough annotations with that extension ? 

@vanaukenk this is along the lines of what we discussed for other terms - do you think this would be appropriate here?

**Comment by Antonialock** [comment]
Hmm, maybe then create a parent term to the palmitoylation term for S-acylation activity? 

from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5364179/
"Although, palmitate is thought to be the most common fatty acid found to be attached to S-palmitoylated proteins recent studies proved that other acyl groups such as stearate (C18:0) or oleate (C18:1) are also accepted in S-palmitoylation. Therefore, S-acylation is a more representative term than palmitoylation  (Jones et al., 1997; Sorek et al., 2007; Hurst and Hemsley, 2015).

just a caution, they also say this in the same pub:
"It is noteworthy that three types of protein palmitoylation are found so far, including S-palmitoylation, N-palmitoylation and O-palmitoylation. While S-palmitoylation can occur at any Cys residues along the protein sequence in which the palmitate is reversibly attached via thioester bond as shown in Figure ​Figure1,1, N-palmitoylation is a stable lipid modification at the N-terminal residue (very often Cys) through amide linkage."

"Since N-palmitoylation can be easily converted by S-palmitoyl migration, it is still not very clear whether N-palmitoylation is an independent enzyme-catalyzed reaction or just from S- to N-palmitoyl transfer (Ji et al., 2016). Less frequently, palmitoyl group can also be linked to a serine residue through ester bond via the so-called O-palmitoyltion. The identified O-palmitoylated targets so far include Wnt/Wg proteins and the peptide hormone preghrelin"

**Comment by Antonialock** [comment]
ALso I'm not sure if all palmitoyltransferases can also stearoylate (as in this case) or if you sometimes get a palmitoyltransferase that cannot stearoylate (or vice versa)

**Comment by pgaudet** [comment]
@Antonialock I hesitate to create the term - looking at the Uniprot Q9H6R6 (Q9H6R6), it *is* a palmitoyltransferase, maybe the substrate specificity is just a little large; is it really a different activity ? 

Anyway I'm happy to add if you think it is important. 

I wonder if @marcfeuermann knows about those modifications ?? 

Thanks, Pascale

**Comment by alanbridge** [comment]
Hi 

there are a variety of different protein lipid modifications such as

parent: 

> RHEA:20101 | a long-chain fatty acid + ATP + L-cysteinyl-[protein] = AMP + diphosphate + S-(long-chain fatty acyl)-L-cysteinyl-[protein]

children: 

> RHEA:59736 | L-cysteinyl-[protein] + tetradecanoyl-CoA = CoA + S-tetradecanoyl-L-cysteinyl-[protein]
> 
> RHEA:36683 | hexadecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-hexadecanoyl-L-cysteinyl-[protein]
> 
> RHEA:59740 | L-cysteinyl-[protein] + octadecanoyl-CoA = CoA + S-octadecanoyl-L-cysteinyl-[protein]
> 
> RHEA:59744 | (9Z)-octadecenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(9Z-octadecenoyl)-L-cysteinyl-[protein]
> 
> RHEA:59748 | (5Z,8Z,11Z,14Z)-eicosatetraenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-L-cysteinyl-[protein]

Some modifications seem to be associated with specific protein functions or pathways, as in the case of palmitoleoylation (=palmitoylation but with a 9Z double bond) (aka (9Z)-hexadecenoylation) of Wnt:

> RHEA:45336 | (9Z)-hexadecenoyl-CoA + [Wnt protein]-L-serine = [Wnt protein]-O-(9Z)-hexadecenoyl-L-serine + CoA

If you are working on palmitoyl transferases worth pinging Lionel Breuza (lionel.breuza@sib.swiss) who is working on Rhea annotation updates for the human set and orthologs.

All the best, Alan

**Comment by Antonialock** [comment]
Thanks Alan.

Pascale, it's probably the same MF, so does that mean the term def is too narrow?

**Comment by Antonialock** [comment]
@pgaudet as Alan pointed out there's
RHEA:59740    
L-cysteinyl-[protein] + octadecanoyl-CoA = CoA + S-octadecanoyl-L-cysteinyl-[protein] 

so should there be a new term, broadening of existing term, or not annotate this function until it is better understood?

**Comment by lbreuza** [comment]
Hi all,
stearoylation may give different properties to the same protein compared to palmitoylation (localization, stability) so it is worth capturing this information. The situation looks similar to ubiquitin ligases for instance that perform a shared catalytic activity but depending on the modified lysine, induce a different effect (degradation, localization). Maybe one should use this example to be consistent and maybe check what has been done for other protein-modifying enzymes.
In line with the curation of ubiquitin ligases, I would therefore use GO:0019707 protein-cysteine S-acyltransferase activity and ask for protein stearoylation as a child of the BP protein lipidation GO:0006497.
Lionel

**Comment by Antonialock** [comment]
Thank you Lionel, that sounds like a good solution ?

**Comment by pgaudet** [comment]
Created new BP term: 


+[Term]
+id: GO:0140438
+name: protein stearoylation
+namespace: biological_process
+def: "The covalent attachment of a stearoyl group to an amino acid in a protein." [PMID:26214738]
+is_a: GO:0006497 ! protein lipidation
+created_by: pg
+creation_date: 2020-03-11T07:54:48Z

I think that resolves this ticket ? 

Thanks, Pascale

**Comment by alanbridge** [comment]
Shouldn't protein stearoylation be a molecular function with a xref to RHEA:59740?

**Comment by pgaudet** [comment]
I understood @lbreuza was requesting a BP and was proposing to use GO:0019707 protein-cysteine S-acyltransferase activity 
Should I add  RHEA:59740 to that term ? 

Those are the MF terms we have in this area: 
'protein-cysteine S-acyltransferase activity'
'protein-cysteine S-myristoyltransferase activity'
'protein-cysteine S-palmitoyltransferase activity'

None have Rhea cross-references - any suggestion would be appreciated ! 

Thanks, Pascale

**Comment by alanbridge** [comment]
Hi Pascale 

'protein-cysteine S-acyltransferase activity' = no Rhea yet
'protein-cysteine S-myristoyltransferase activity' = RHEA:59736
'protein-cysteine S-palmitoyltransferase activity' - mapped to EC 2.3.1.225 = RHEA:36683 (this is actually the reaction specified by IUBMB for EC 2.3.1.225 - Protein S-acyltransferase)

This is one of those cases where the name of an enzyme class (EC 2.3.1.225 - Protein S-acyltransferase) and the reaction chosen to represent by IUBMB (which equates to 'protein-cysteine S-palmitoyltransferase activity' = RHEA:36683) don't quite match. I would leave the EC where it is though worth pinging Kristian to check that. I requested a new Rhea for protein-cysteine S-acyltransferase activity as a grouping term.

new GO terms and mappings 

'protein-cysteine S-stearoyltransferase activity' = RHEA:36683
'protein-cysteine S-oleoyltransferase activity' = RHEA:59744 
'protein-cysteine S-arachidonoyltransferase activity' = RHEA:59748

The definition of the BP is so close to the MF - "the covalent attachment..." is really a reaction - this will cause confusion IMO, I must confess I don't quite see the need as defined.

Hope that helps, Alan

**Comment by pgaudet** [comment]
Thanks Alan 

Right, the label 'protein S-acyltransferase' sound just like the parent 'protein-cysteine S-acyltransferase activity'. I wont add the synonym yet to avoid creating confusion.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140439
+name: protein-cysteine S-stearoyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the transfer of a stearoyl group to a sulfur atom on the cysteine of a protein molecule, in the reaction: hexadecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-hexadecanoyl-L-cysteinyl-[protein]." [PMID:12681491, PMID:22247542, PMID:22968831, RHEA:36683]
+xref: RHEA:36683
+is_a: GO:0019707 ! protein-cysteine S-acyltransferase activity
+created_by: pg
+creation_date: 2020-03-11T09:55:48Z
+
+[Term]
+id: GO:0140440
+name: protein-cysteine S-oleoyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the transfer of an oleoyl group to a sulfur atom on the cysteine of a protein molecule, in the reaction: (9Z)-octadecenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(9Z-octadecenoyl)-L-cysteinyl-[protein]." [PMID:22247542, RHEA:59744]
+xref: RHEA:59744
+is_a: GO:0019707 ! protein-cysteine S-acyltransferase activity
+created_by: pg
+creation_date: 2020-03-11T09:56:11Z
+
+[Term]
+id: GO:0140441
+name: protein-cysteine S-arachidonoyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the transfer of an arachidonoyl group to a sulfur atom on the cysteine of a protein molecule, in the reaction: hexadecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-hexadecanoyl-L-cysteinyl-[protein]." [PMID:12681491, PMID:22247542, PMID:22968831, RHEA:59748]
+xref: RHEA:59748
+is_a: GO:0019707 ! protein-cysteine S-acyltransferase activity
+created_by: pg
+creation_date: 2020-03-11T09:56:24Z

**Comment by alanbridge** [comment]
+id: GO:0140439 should xref 

RHEA:59740 | L-cysteinyl-[protein] + octadecanoyl-CoA = CoA + S-octadecanoyl-L-cysteinyl-[protein]

sorry my typo 

the def cites the wrong reaction too: 

for

+id: GO:0140441

the def is wrong (the reaction part again, same problem as above)

**Comment by alanbridge** [comment]
there is a mix of traditional and systematic nomenclature in the defs too (hexadecanoyl = palmitoyl, etc), I don't know if you might want to make this explicit by e.g. doubling up on the reaction text.

All the best, Alan

**Comment by pgaudet** [comment]
Thanks again @alanbridge 
I edited the definitions as follows: 

Catalysis of the transfer of a myristoyl (systematic name, tetradecanoyl) group to a sulfur atom on a cysteine residue of a protein molecule in the reaction: tetradecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-tetradecanoyl-L-cysteinyl-[protein].

+def: "Catalysis of the transfer of a palmitoyl (systematic name, hexadecanoyl) group to a sulfur atom on the cysteine of a protein molecule, in the reaction hexadecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-hexadecanoyl-L-cysteinyl-[protein]." [GOC:ai, GOC:pr, RHEA:36683]

+def: "Catalysis of the transfer of a stearoyl group to a sulfur atom on the cysteine of a protein molecule, in the reaction: octadecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-octadecanoyl-L-cysteinyl-[protein]." [PMID:12681491, PMID:22247542, PMID:22968831, RHEA:59740]

+def: "Catalysis of the transfer of an oleoyl (systematic name, octadecenoyl) group to a sulfur atom on the cysteine of a protein molecule, in the reaction: (9Z)-octadecenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(9Z-octadecenoyl)-L-cysteinyl-[protein]." [PMID:22247542, RHEA:59744]

+def: "Catalysis of the transfer of an arachidonoyl (systematic name, eicosatetraenoyl) group to a sulfur atom on the cysteine of a protein molecule, in the reaction: in the reaction: (5Z,8Z,11Z,14Z)-eicosatetraenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-L-cysteinyl-[protein]." [PMID:12681491, PMID:22247542, PMID:22968831, RHEA:59748]

Is this now correct ? 

Thanks, Pascale

**Comment by alanbridge** [comment]
+def: "Catalysis of the transfer of a stearoyl (systematic name, octadecanoyl) group to a sulfur atom on the cysteine of a protein molecule, in the reaction: octadecanoyl-CoA + L-cysteinyl-[protein] = CoA + S-octadecanoyl-L-cysteinyl-[protein]." [PMID:12681491, PMID:22247542, PMID:22968831, RHEA:59740]

+def: "Catalysis of the transfer of an oleoyl (systematic name, (9Z)-octadecenoyl) group to a sulfur atom on the cysteine of a protein molecule, in the reaction: (9Z)-octadecenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(9Z-octadecenoyl)-L-cysteinyl-[protein]." [PMID:22247542, RHEA:59744]

+def: "Catalysis of the transfer of an arachidonoyl (systematic name, 5Z,8Z,11Z,14Z-eicosatetraenoyl) group to a sulfur atom on the cysteine of a protein molecule, in the reaction: in the reaction: (5Z,8Z,11Z,14Z)-eicosatetraenoyl-CoA + L-cysteinyl-[protein] = CoA + S-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-L-cysteinyl-[protein]." [PMID:12681491, PMID:22247542, PMID:22968831, RHEA:59748]

**Comment by Antonialock** [comment]
Thank you both!

**Comment by alanbridge** [comment]
Hi 

just one last thing, @kaxelsen has now created a new parent Rhea reaction that groups all these activities (and could be logically mapped to GO:0019707):

RHEA:63372 an acyl-CoA + L-cysteinyl-[protein] = CoA + S-acyl-L-cysteinyl-[protein]

Should be out next release. 

Cheers, Alan

**Comment by pgaudet** [comment]
Thanks @alanbridge I'll add that.
