### ISSUE TITLE
NTRs: Negative regulation of interleukin-32 biosynthetic process/ negative regulation of interleukin-32 secretion

### ISSUE THREAD

**Issue by ShirinSaverimuttu** [geneontology/go-ontology#18892]
NTRs:  Negative regulation of interleukin-32 biosynthetic process/ negative regulation of interleukin-32 secretion

Evidence: PMID 23729669. Figure 3

> (C) MiR-29b significantly reduced the IL-32 UTR reporter activity 

> (H) Extracellular IL-32 protein levels were measured by ELISA.  IL-32 secretion was significantly enhanced by miR-29b inhibitor. 

Currently only the below annotations exist:
GO:0072637 interleukin-32 production 
GO:0072638 interleukin-32 secretion  (child term of GO:0072637)

**Comment by pgaudet** [comment]
I thought we were going to stick to 'production' and drop biosynthetic process, since protein biosythesis is translation ?

**Comment by BarbaraCzub** [comment]
I was aware there have been discussions going on, but I didn't realise there was a decision.

**Comment by addiehl** [comment]
Is this something to discuss in Paris?
Alex

**Comment by pgaudet** [comment]
Sure

**Comment by pgaudet** [comment]
I created a strawman document to note the discussion topics we'd like to address (this is in the GO Google drive/Meetings/2020-GOC-Paris: 

https://docs.google.com/document/d/1-LwggfQoWO57zLw4lkbq_LW3Jxwf9GJ1DcX3Nm0cd6Q/edit#

Thanks, Pascale
