### ISSUE TITLE
merge GO:0009922 fatty acid elongase activity and GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#18897]
Can these two terms be merged?

GO:0009922 fatty acid elongase activity
Catalysis of the reaction: fatty acid (C-16 or longer) + 2-C = fatty acid (C-16 or longer + 2-C).

~GO:0009922~ GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity
Catalysis of the reaction: malonyl-CoA + a very-long-chain 2,3,4-saturated fatty acyl CoA = carbon dioxide + coenzyme A + a very-long-chain oxoacyl-CoA

**Comment by ValWood** [comment]
Added defs, corrected GO ID :)

**Comment by ValWood** [comment]
Isn't "fatty acid elongase" just the gene product name?

Although how does it relate to the parent?

Definition | Parents
-- | --
Catalysis of the reaction: acetyl-CoA + n malonyl-CoA + 2n NADPH + 2n H+ = long-chain fatty acid + n+1 CoA + n CO2 + 2n NADP+.

**Comment by Antonialock** [comment]
I dont think fatty acid synthase activity (GO:0004312) should be a parent to GO:0009922 fatty acid elongase activity 

first you synthesise the fatty acid and then you elongate/desaturate/process further it

(unless I am missing something - I'm assuming that GO:0009922 fatty acid elongase activity is applicable to the ELOVL family of proteins

**Comment by Antonialock** [comment]
also I'm not sure what 'very long chain" means

ELOVL6 is a 'very long chain' elongase by name. However, it elongates C16:0 to C18:0 - but VLCFs are C20 or so and longer? Is the 'very' part a useful qualifier that needs to be specified in GO terms? If so what lengths is it applicable to?...

**Comment by Antonialock** [comment]
ah I think I get this organization
 GO:0009922 fatty acid elongase activity

must refer to elongases that are part of type II FAS?
In eukaryotes (type I) FAS is one large multifunctional enzyme, but archaea/bacteria appear to have discrete subunuits (and maybe also mitochondrial FAS in eukaryotes?)

but presumably sometimes elongation takes place without synthesis (dietary uptake?)



In any case the ELOVLs seem to be annotated to both
GO:0009922 fatty acid elongase activity
GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity

which seems redundant

**Comment by deustp01** [comment]
> also I'm not sure what 'very long chain" means
The textbook biochemistry view is that fatty acid synthesis yields long-chain fatty acids of chain length 16 or 18 carbons. Elongases catalyze the addition of two-carbon units to these long-chain fatty acids (and other enzymes catalyze the steps to reduce the addition product to yield a fatty acid with two more carbon atoms). As far as I can tell skimming [this review](https://www.ncbi.nlm.nih.gov/pubmed/16564093) the various elongase enzymes differ in the tissues ands physiological states in which they afre expressed, the regulation of that expression, and in substrate preference, but they all appear to have the same reaction mechanism. @hdrabkin, am I getting this right?

If so then all the elongases are related in the same way that, say, all the serine endopeptidases are, and can be covered by a single GO term with the other features =handled as annotations (like trypsin and thrombin).

**Comment by ukemi** [comment]
CHEBI:27283

**Comment by deustp01** [comment]
> CHEBI:27283

ChEBI defines that term as applying to molecules with at least 22 carbons - a term is needed for anything over 16. The alternative in ChEBI, alas, is CHEBI:15904 "A fatty acid with a chain length ranging from C13 to C22."

A basic problem here is that the biochemist view allows for overlap in the chain lengths specified for medium, long-chain, and very-long chain, and ChEBI is insisting on sharp boundaries.

**Comment by ukemi** [comment]
Yes, but in GO we rely on ChEBI. They are the word on chemicals. Pinging @alanbridge. If I recall correctly, he did quite a bit of work on lipid metabolism.

**Comment by deustp01** [comment]
So perhaps the fix is to have two MF terms, one for elongations involving C16 - C20 substrates, (could be "long chain elongation activity") and one for elongations involving substrates with C22 or more (could be "very long chain elongation activity"). Both terms mighty get the same EC (haven't checked this) and some proteins will need annotation with both MF terms to capture the full range of their activities but that sounds harmless.

**Comment by pgaudet** [comment]
Isn't this a process then ? Looks like the activity is the same but that both activities produce different lipids ?

**Comment by deustp01** [comment]
I don't think so. It's an issue of annotating enzymes with broad substrate specificities and, in this particular case, the range of substrates an enzyme can act on spans two ChEBI terms.

**Comment by Antonialock** [comment]
> 
> 
> Isn't this a process then ? Looks like the activity is the same but that both activities produce different lipids ?

Ah bingo, good point
Fatty acid elongation is a 4 step process.
In the first step (the one I am annotating) acyl-CoA is condensed with malonyl-CoA to form 3-ketoacyl-CoA.

So the enzyme I'm reading about elongates palmitoyl-CoA (16:0) to 3-ketostearoyl-CoA (C18:0), this is then processed further into stearate (by the susequent 3 steps)

this is equivalent to MF GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity

I don't know if it is ever a 1 step procedure a la GO:0009922 fatty acid elongase activity - I think (but not sure - would need to check this) that FAS performs a same/similar multi-step cycle? so it does sound like a process?

**Comment by ukemi** [comment]
This just reminds me that we need to look at lipid metabolism more generally.
#10773

**Comment by deustp01** [comment]
Indeed, elongation is a four-step process, the first step of which is catalyzed by enzymes called elongases (because that's the step in which the chain actually gets longer) and all that fussing above about substrate specificities and chain lengths is specifically about these enzymes.

**Comment by Antonialock** [comment]
So merge the two terms, remove FAS parentage, and remove ‘very long’ from GO: 0102756 ?

**Comment by alanbridge** [comment]
Hi 

Antonia you are right - fatty acid elongation occurs in 4 steps. Formation of a 3-keto product with 2 additional carbons is step 1, and the subsequent 3 steps resolve the keto group. That's 4 reactions that you could define as a process - but also as an "overall reaction" depending on the assay type and the way the data is presented. 

Your original question relates to:

> GO:0009922 fatty acid elongase activity
> Catalysis of the reaction: fatty acid (C-16 or longer) + 2-C = fatty acid (C-16 or longer + 2-C).
> 
> GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity
> Catalysis of the reaction: malonyl-CoA + a very-long-chain 2,3,4-saturated fatty acyl CoA = carbon dioxide + coenzyme A + a very-long-chain oxoacyl-CoA

**The two cannot be merged.** GO:0009922 represents the sum of 4 reactions, for 16 carbons or more, GO:0102756 represents step 1 of 4, for very long chains (and so excludes "ultra long"), and specifies acyl-CoA as the carrier. I don't see any need to change the definition of GO: 0102756 either. It's fine. 

Different people have different definitions of short, medium, long, very long, and ultra long chain FAs. This is perhaps not ideal :-) We try not to get too hung up on this; when updating legacy annotations in UniProt using Rhea we are capturing the precise substrates. Why not make GO terms for each of these?

You mentioned ELOVL6, which is https://uniprot.org/uniprot/Q920L5 (mouse). We have reannotated this and all other ELOVL family members - there are 7 (I agree the name is misleading). The reactions for ELOVL6 are shown below (I removed information about direction and evidences too).

*Parent reaction* 

maps to EC=2.3.1.199, GO:0102756

RHEA:32727
a very-long-chain acyl-CoA + H(+) + malonyl-CoA = a very-long-chain 3-oxoacyl-CoA + CO2 + CoA

"Child reactions"

RHEA:35315 (your reaction)
H(+) + hexadecanoyl-CoA + malonyl-CoA = 3-oxooctadecanoyl-CoA + CO2 + CoA

RHEA:39675 
(9Z)-hexadecenoyl-CoA + H(+) + malonyl-CoA = 3-oxo-(11Z)-octadecenoyl-CoA + CO2 + CoA

RHEA:60140
dodecanoyl-CoA + H(+) + malonyl-CoA = 3-oxotetradecanoyl-CoA + CO2 + CoA

RHEA:39167
H(+) + malonyl-CoA + tetradecanoyl-CoA = 3-oxohexadecanoyl-CoA + CO2 + CoA

RHEA:36511
(9Z)-octadecenoyl-CoA + H(+) + malonyl-CoA = (11Z)-3-oxoicosenoyl-CoA + CO2 + CoA

RHEA:36503
(9Z,12Z)-octadecadienoyl-CoA + H(+) + malonyl-CoA = (11Z,14Z)-3-oxoicosa-11,14-dienoyl-CoA + CO2 + CoA

RHEA:36523
(9Z,12Z,15Z)-octadecatrienoyl-CoA + H(+) + malonyl-CoA = (11Z,14Z,17Z)-3-oxoeicosatrienoyl-CoA + CO2 + CoA

All the best, Alan

**Comment by sjm41** [comment]
Hi all

I just stumbled across this issue myself, for a similar reason to @Antonialock in her original post.

Was there a consensus that the GO MF GO:0009922 (fatty acid elongase activity) represents a process?
Maybe equivalent to the BP term "GO:0030497 fatty acid elongation, which has def: The elongation of a fatty acid chain by the sequential addition of two-carbon units."  If so, should GO:0009922 should be merged with GO:0030497? (Or GO:0009922 should be obsoleted and any annotations transferred to GO:0030497)

Also, I think these two existing GO terms should be children of GO:0102756 (very-long-chain 3-ketoacyl-CoA synthase activity, EC:2.3.1.199) - both involve 'very long chain FAs': 

id: GO:0102338
name: 3-oxo-lignoceronyl-CoA synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: behenoyl-CoA(4-) + malonyl-CoA(5-) + H+ <=> 3-oxotetracosanoyl-CoA. + carbon dioxide + coenzyme A." [GOC:pz, RHEA:36507]
xref: MetaCyc:RXN-13297
xref: RHEA:36507
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups

id: GO:0102337
name: 3-oxo-cerotoyl-CoA synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: tetracosanoyl-CoA(4-) + malonyl-CoA(5-) + H+ <=> 3-oxohexacosanoyl-CoA + carbon dioxide + coenzyme A." [GOC:pz, RHEA:36515]
xref: MetaCyc:RXN-13296
xref: RHEA:36515
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups

**Comment by pgaudet** [comment]
After discussion with @sjm41 - these 2 terms are really equivalent. GO:0009922 fatty acid elongase activity was missing any cross references and had the wrong parent, so GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity was created by mistake because it was not clear that these were the same. 

- [x] Fixed definition to make clear that this reaction corresponds to the condensation step, as described in PMID:16564093: 

- old def: "Catalysis of the reaction: fatty acid (C-16 or longer) + 2-C = fatty acid (C-16 or longer + 2-C)." [GOC:tb]
- new def: "Catalysis of the reaction: fatty acid (C-16 or longer) + 2-C = fatty acid (C-16 or longer with an additional 2-C unit). This reaction is the condensation step of the endoplasmic reticulum fatty acid elongation cycle. [GOC:tb, PMID:16564093, PMID:19763486]

- [x]  Added some synonyms: 
+synonym: "condensing enzyme" BROAD []
+synonym: "elongation of very long chain fatty acids activity" EXACT []
+synonym: "ELOVL" EXACT []
+synonym: "very-long-chain 3-ketoacyl-CoA synthase" EXACT []
+synonym: "very-long-chain 3-oxoacyl-CoA synthase" EXACT []
+synonym: "very-long-chain beta-ketoacyl-CoA synthase" EXACT []

- [x] moved cross references:  
+xref: EC:2.3.1.199
+xref: MetaCyc:RXN-7697
+xref: RHEA:32727

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102756 very-long-chain 3-ketoacyl-CoA synthase activity . The reason for obsoletion is that this term corresponds to GO:0009922 fatty acid elongase activity.  GO:0102756  has no manual annotations, all annotations were assigned from EC and RHEA mappings, which have been transferred to GO:0009922. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/18897

Thanks, Pascale
