### ISSUE TITLE
GO:NEW  DNA-binding transcription repressor activity, RNA polymerase III-specific 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18891]
GO:NEW  DNA-binding transcription repressor activity, RNA polymerase III-specific
Def
A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a RNA polymerase III-transcribed gene to repress or decrease transcription. 

descendant of
GO:0001217   DNA-binding transcription repressor activity

~GO:0001227    DNA-binding transcription repressor activity, RNA polymerase II-specific~

References PMID:31833215, PMID:15590667

**Comment by ukemi** [comment]
Why a descendant of GO:0001227?

**Comment by hdrabkin** [comment]
I agree can't be pol III specific and a child of GO:0001227

**Comment by ValWood** [comment]
That line was just  'hanging around', it was the 'template' for my term name.

**Comment by hdrabkin** [comment]
+id: GO:0106250
+name: DNA-binding transcription repressor activity, RNA polymerase III-specific
done
