### ISSUE TITLE
parentage CDP-diacylglycerol biosynthetic process (GO:0016024)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18899]
CDP-diacylglycerol biosynthetic process (GO:0016024)

is_a pyrimidine nucleotide biosynthetic process

seems incorrect

**Comment by ukemi** [comment]
This is a ChEBI issue. The chemical classifications in GO are derived from ChEBI.

**Comment by ukemi** [comment]
Can you open a ticket in the ChEBI tracker?

**Comment by ValWood** [comment]
Done
https://github.com/ebi-chebi/ChEBI/issues/3753
v

**Comment by ValWood** [comment]
CHEBI removed this, so will close

**Comment by ukemi** [comment]
@balhoff, can you run ontobot on ChEBI so we can get this update, assuming these changes are in the ChEBI release?

**Comment by balhoff** [comment]
@ukemi we have been sitting on this old CHEBI PR: https://github.com/geneontology/go-ontology/pull/17673

Want me to just close and see what it looks like now?

**Comment by ukemi** [comment]
Ah, I remember now that there were serious issues with the roles, so we haven't updated in a while. We shouldn't update yet. ping @krchristie
