### ISSUE TITLE
GO:0043848    excinuclease cho activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18904]
Is this a gene product?

Has no annotations...

**Comment by pgaudet** [comment]
Looks like it ! Also, we link to a (dead) JGI gene page, indicating it *is* representing a GP: 
https://img.jgi.doe.gov/cgi-bin/pub/main.cgi?section=GeneDetail&page=geneDetail&gene_oid=00499

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete GO:0043848 excinuclease cho activity. The reason for obsoletion is that it represents a gene product. 

There are no annotations and no mappings to those terms. Those terms are not present in any subsets.

Any comments can be made to the ticket: geneontology/go-ontology#18904

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 26th, 2020. Unless objections are received by February 26th, 2020, we will assume that you agree to this change.

Thanks, Pascale
