### ISSUE TITLE
Remove MIPS_funcat xrefs ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18906]
Hello, 

Does anyone know if MIPS_funcat still exists ? If not, we should remove the xrefs we have to this resource. 

@thomaspd @ValWood @cmungall any idea? 

Thanks, Pascale

**Comment by ValWood** [comment]
It seems to have gone
https://en.wikipedia.org/wiki/Munich_Information_Center_for_Protein_Sequences
forwards to
https://www.helmholtz-muenchen.de/ibis/

**Comment by srengel** [comment]
oh yeah they went defunct some years ago.

**Comment by bmeldal** [comment]
The yeast MIPS complexes are gone, I looked for them many times!!!

CORUM (mammalian complexes) used funcat, too. But they have now mapped to GO.
