### ISSUE TITLE
GO:0000726     non-recombinational repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18901]
GO:0000726   non-recombinational repair
A DNA repair process in which that does not require the exchange of genetic material between the broken DNA molecule and a homologous region of DNA.

Is this a necessary grouping term?
It seems strange because it has 3 children

GO:0045002    double-strand break repair via single-strand annealing | is_a
GO:0036299    non-recombinational interstrand cross-link repair | is_a
GO:0006303    double-strand break repair via nonhomologous end joining

but these are not all of the kinds of repair that are  not recombinational
for example

GO:0006302    double-strand break repair | is_a
GO:0006301    postreplication repair | is_a
GO:0006284    base-excision repair

so it isn't really what it says it is....

**Comment by ValWood** [comment]
It only has 2 direct EXP annotations so should probably go?


REXO4	RNA exonuclease 4		non-recombinational repair	has input ENSEMBL:ENSG00000181019
occurs at SO:0000167	ARUK-UCL	Homo sapiens	IDA		exonuclease pthr12801	protein		PMID:21602889	20181201
	nfo	endonuclease IV		non-recombinational repair		EcoCyc	Escherichia coli K-12	IDA		endonuclease iv endodeoxyribonuclease iv pthr21445	protein	PR:P0A6C1	PMID:2453510	20110603

(the human one looks like BER, which indicates the problem with this type of 'exclusion' term

**Comment by pgaudet** [comment]
Created an annotation review ticket: https://github.com/geneontology/go-annotation/issues/2831

**Comment by pgaudet** [comment]
Annotations are now removed.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0000726 non-recombinational repair'. The reason for obsoletion is that this term is defined negatively, which is not good ontology practice, and is an unnecessary grouping term. There are no annotations or mappings to this term. This term is not in any subsets.

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/18901

Thanks, Pascale
