### ISSUE TITLE
NTR: terms related to plant-type regeneration and one move

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#18905]
We would like to add some terms related to regeneration in plants.

1. Plant type regeneration: GO:new
Definition: The regrowth or de-novo differentiation of a damaged or lost plant body part, such as an organ or tissue, or  of an entire plant body. This process may occur via de-differentiation and subsequent reprogramming of somatic cells or activation of existing undifferentiated cells.
Reference: DOI: 10.1242/dev.134668; TAIR:LR
Suggested Parentage: is a child of regeneration GO:0031099

2. Plant organ/tissue regeneration: GO:New
Def:The regrowth or de-novo differentiation of a damaged or lost plant body part, such as an organ or tissue such as a root or shoot meristem. This process may occur via de-differentiation and subsequent reprogramming of somatic cells or activation of existing undifferentiated cells.
Reference: DOI: 10.1242/dev.134668; TAIR:LR
Suggested Parentage: is a child of Plant type regeneration
Suggested Parentage: is a child of response to wounding GO:0002245

3.Shoot regeneration:  GO:New
Def: The regrowth or de-novo differentiation of  a damaged or lost shoot. This process may occur via de-differentiation and subsequent reprogramming of somatic cells or activation of existing undifferentiated (meristematic) cells to produce a new shoot meristem and subsequently a new root. 
Reference: DOI: 10.1242/dev.134668; TAIR:LR
Suggested Parentage: is a child of Plant organ/tissue regeneration
Suggested Parentage: is a child of Shoot System Development GO:0048367

4.Root  regeneration: The regrowth or de-novo differentiation of  a damaged or lost root . This process may occur via de-differentiation and subsequent reprogramming of somatic cells or activation of existing undifferentiated (meristematic) cells  to form a new root meristem and subsequently new root.
Reference: DOI: 10.1242/dev.134668; TAIR:LR
Suggested Parentage: is a child of Plant organ/tissue regeneration
Suggested Parentage: is a child of root development GO:0048364

5. Suggest to MOVE somatic embryogenesis (GO:0010262) to be a child of BOTH Embryo Development (GO: 0009790) AND the new Plant type regeneration term. The reason is that somatic embryos do not form seeds. 

See attached image file for what we think this could look like.
@tberardini @ebakker2 
![screenshot_1939](https://user-images.githubusercontent.com/14040923/74892723-468e5700-533f-11ea-95d6-02739439e730.png)

**Comment by ukemi** [comment]
Do we really need the plant-type regeneration term as a grouping term? Since the child nodes refer to plant structures we can use the PO terms in the logical definitions. I think(?) the classification would sort itself out based on that. If that makes sense to you guys, I'll past a straw-man proposal here.

**Comment by lreiser** [comment]
@ukemi if that is how to make it work best in the ontology sure. I doubt there would be a need to annotate to the grouping term.Looks like there is also a PO term for somatic embryo PO:0025302.

**Comment by ukemi** [comment]
I can make a term for any structure in PO and GO will follow that structure.

**Comment by lreiser** [comment]
@ukemi  awesome- you show that ontology who is boss!

**Comment by ukemi** [comment]
Hi @lreiser. I created the shoot and root terms and added the parent to the somatic embryogenesis term. I notice that we do have an animal organ regeneration term in GO. I could create a similar term for plants if you think it would be useful. If so, can you give me some advice based on the PO? root is_a plant axis, which is in turn a plant organ and in turn a plant structure. shoot system (which is what I used) is_a collective plant organ structure, which is in turn a plant structure. So, I could make a grouping term plant structure regeneration and these two new term would group under it. However, there are other terms that I could use as the anatomical terms for root and shoot: 'shoot system', 'shoot axis', root (which seems to be 'root axis' based on its parent) or 'root system'. In both cases, the axis is part-of the system. In GO, it seems like we have used two different levels of granularity for the existing terms, system for shoots and axis for roots. I followed that pattern for the new terms but thought I should double-check with you that you think this is right. Sorry to have opened up a potential can of worms from your relatively simple ticket, but it would be nice to sanity check this now that we are in this part of the ontology. If it would be easier to talk about this, we can do that too. 
Also, I don't see your personal xref as a valid xref, so I only added the paper.

**Comment by lreiser** [comment]
Oy- I am so sorry. I missed this notification and question. My apologies to you. I'd blame it on coronavirus hysteria but probably just a messy inbox.
Thank you for adding the terms to the ontology.

So I like the idea of a grouping term and if we can add it fine. That would include somatic embryogenesis and the root/shoot terms?

a shoot system (PO:0009006) can contain one or more shoot axis (think branch( , as can a root system (tap root like a carrot as single axis vs say the roots of a tomato plant.) WRT to regeneration-realistically this leads to only one axis would be produced. Basically its a type of ...dare I say it.. meristem organization as the cells de-differentiate or differentiate into a meristem to produce said organ. Somatic embryogenesis is weird, both root and shoot meristems (and axis') are produced.

Worms ahoy.

**Comment by ukemi** [comment]
In animals that can regenerate, a very similar process occurs. Cells de-differentiate and then re-differentiate to for the new structure. The de-differentiated structure is called a blastema. Axolotls are really good at regenerating limbs. So making a plant-specific term to me still seems a bit artificial and might lead to us missing some interesting biology if regenerative mechanisms are similar. Although I fully understand its utility in querying. Some day we will be able to do more sophisticated queries that take into account things like processes occurring in a plant structure, but not yet.   @tberardini, second opinion? 
I get the difference between the system and the axis. I will check the terms to make sure they are consistent. Thanks!

**Comment by ukemi** [comment]
OK. Just checked and I think we are good with the axis bit. I could create 'plant organ regeneration' very easily and it seems like this would be the best grouping term if you want it.

**Comment by lreiser** [comment]
I am ok with NOT adding more terms if they are not necessary.
