### ISSUE TITLE
MFs in BP ontology (DNA repair) -> GO:0000717 nucleotide-excision repair, DNA duplex unwinding 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18903]
These aseem to be molecular functions?

OBSOLETE ~GO:0033683    nucleotide-excision repair, DNA incision  (11,000 annotations 27 EXP)~
~GO:0000718    nucleotide-excision repair, DNA damage removal (1 NAS annotation)~ https://github.com/geneontology/go-ontology/issues/29220
GO:0000717    nucleotide-excision repair, DNA duplex unwinding (299 annotations 2 EXP annotations)
~GO:0006288    base-excision repair, DNA ligation (149 annotations, 6 EXP all ligases )~ https://github.com/pombase/pombase-chado/issues/1192
~GO:0000715     nucleotide-excision repair, DNA damage recognition (31,000 annotation 11 EXP)~

**Comment by ValWood** [comment]
Or merge up into the respective repair terms?

**Comment by ValWood** [comment]
moved
GO:0000715 nucleotide-excision repair, DNA damage recognition (31,000 annotation 11 EXP)
to related
https://github.com/geneontology/go-ontology/issues/19051

**Comment by ValWood** [comment]
Some of these might be multistep processes, but  ligation does not appear to be

**Comment by pgaudet** [comment]
They do seem like functions.

**Comment by ValWood** [comment]
This might be good jamboree fodder?

**Comment by ValWood** [comment]
see https://github.com/pombase/pombase-chado/issues/1192

**Comment by ValWood** [comment]
There are lots of "DNA duplex unwinding" terms  does this mean anything other than "helicase"?

<img width="624" alt="Screenshot 2024-11-14 at 11 45 50" src="https://github.com/user-attachments/assets/05960603-6ad3-48aa-b933-af776dfda1c3">

**Comment by ValWood** [comment]
@raymond91105  does your ticket cover all of these? if so this one can close.

**Comment by raymond91125** [comment]
Added what's left to https://github.com/geneontology/go-ontology/issues/29153
