### ISSUE TITLE
Term merge and  new regulation terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18916]
could we merge
GO:1990954    establishment of protein localization to meiotic spindle pole body
into the parent
(only used by PomBAse)

GO:1902441    protein localization to meiotic spindle pole body

**Comment by ValWood** [comment]
and could we add
GO:NEW     protein localization to meiotic spindle pole body
regulation, and positive regulation

PMID:22438582

**Comment by pgaudet** [comment]
@ValWood 
I suppose I should also merge GO:1990975 establishment of protein localization to mitotic spindle pole body in the same parent ?

**Comment by ValWood** [comment]
Yes I'm fine with that.

**Comment by ValWood** [comment]
Did I get the "positive regulation" term?
I don't see it yet..

**Comment by pgaudet** [comment]
GO:0140434 positive regulation of protein localization to meiotic spindle pole body 

There was a successful snapshot yesterday so you should see the new term soon.

**Comment by ValWood** [comment]
I see the term, but can you just check the parent because it wasn't under

GO:1902441 | protein localization to meiotic spindle pole body

in Canto. I checked QuickGO but that isn't up to date yet

**Comment by pgaudet** [comment]
It's under 'regulation of protein localization to meiotic spindle pole body' 
which seems right ?

**Comment by ValWood** [comment]
I didn't see any children of 
GO:1902441 | protein localization to meiotic spindle pole body
(i.e regulation...)
I will check again on monday
