### ISSUE TITLE
NTR positive regulation term for GO:0110026

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18913]
positive 

GO:0110026 | regulation of DNA strand resection involved in replication fork processing
-- | --

ref 
PMID:31575705

**Comment by ValWood** [comment]
Hi HArold, Could you add this one (should be very quick)
I'd like to get this one through quickly . It's a new curator.

**Comment by hdrabkin** [comment]
GO:0110026 already a regulation term, so will hadd + and -  for DNA strand resection involved in replication fork processing.

**Comment by hdrabkin** [comment]
Oh, I see the negative one already exists so I just need to add this one. 
+id: GO:0106253
+name: positive regulation of DNA strand resection involved in replication fork processing
