### ISSUE TITLE
platelet-activating factor acetylhydrolase - biological process

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#18914]
Dear GO curators,

Could you please consider creating these GO terms:

- GO_new: platelet activating factor catabolic process as child of GO:0046469 (PMID:16371369;  EC 3.1.1.47)
- GO_new: F2-isoprostane phospholipid ester catabolic process as child of GO:0009395
(PMID:16371369 and review PMID:25449649; isoprostane CHEBI:138408; F2-isoprostane CHEBI:142058)

Many thanks for your help.

Nevila Hyka-Nouspikel

**Comment by ukemi** [comment]
PAF=CHEBI:52450
@nnouspikel, does the F2-isoprostane grouping term also include the esterified forms? Would it be better to have just F2-isoprostane catabolic process? From the review figure 4 they are clearly a set of molecules, but they seem to all be grouped under isoprostane and F2-isoprostane. If we wish to enumerate all of the individual species, I think we need to ask ChEBI for the 'F2-isoprostane phospholipid ester' class.

**Comment by nnouspikel** [comment]
Hi David,

Thank you for taking care of this and sorry for the late answer. Yes, we could have just F2-isoprostane catabolic process as child of GO:0006692 prostanoid metabolic process. 
The release of isoprostanes from esterified phopholipids is part of their catabolism (https://www.lipidhome.co.uk/lipids/fa-eic/eicisop/index.htm).

Cheers,

Nevila
