### ISSUE TITLE
NTR: larynx morphogenesis

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#18924]
For annotation of  [PMID:28177282](https://www.ncbi.nlm.nih.gov/pubmed/?term=28177282) , I need a new term for `larynx morphogenesis`. Since there is an UBERON term for `larynx`, I can model the new term after `bronchus morphogenesis`, giving me this:

> [Term]
> id: GO:new
> name: larynx morphogenesis
> namespace: biological_process
> def: "The process in which the larynx is generated and organized. The larynx is a continuation of the pharynx that is involved in breathing, sound production, and protecting the trachea against food aspiration." [GOC:krc]
> is_a: GO:0009887 ! animal organ morphogenesis
> intersection_of: GO:0009653 ! anatomical structure morphogenesis
> intersection_of: results_in_morphogenesis_of UBERON:0001737 ! larynx

@ukemi - The term for `bronchus morphogenesis` that I am using as a model for the new term `larynx morphogenesis` also has a part of relationship to a term for `bronchus development`. No parallel term exists for `larynx development`. Is there a recommended practice within the development and morphogenesis area to create both terms, even if only one is currently requested for annotation?

**Comment by ukemi** [comment]
In the past this was standard practice in almost all cases. Also, the partonomy is not automated so the part_of relationships need to be asserted. This is something I think @balhoff and I talked about way back when he started, but as far as I know it ended at discussion. The idea would be to take advantage of the anatomy relationships in the development relationships.

**Comment by krchristie** [comment]
Thanks @ukemi - I'll make the term for `larynx development` and assert the appropriate part_of relationship from `larynx morphogenesis`.
