### ISSUE TITLE
merge GO:0030385 and GO:0103012

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#18939]
Hello, these seem to be identical:
```
id: GO:0030385
name: ferredoxin:thioredoxin reductase activity
namespace: molecular_function
def: "Catalysis of the two-electron reduction of the disulfide of thioredoxins w
ith electrons from ferredoxin involving a 4Fe-4S cluster and an adjacent active-
site disulfide." [PMID:14769790]
is_a: GO:0016730 ! oxidoreductase activity, acting on iron-sulfur proteins as do
nors
```
```
id: GO:0103012
name: ferredoxin-thioredoxin reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 H+ + 2 a reduced ferredoxin + an oxidized thioredoxin = 2 an oxidized ferredoxin + a reduced thioredoxin" [EC:1.8.7.2, GOC:pz]
xref: EC:1.8.7.2
xref: MetaCyc:RXN-9944
is_a: GO:0016673 ! oxidoreductase activity, acting on a sulfur group of donors, iron-sulfur protein as acceptor
```
See also https://www.rhea-db.org/reaction?id=42336

**Comment by ukemi** [comment]
I wonder how these got through the duplicate name check.

**Comment by hdrabkin** [comment]
Note the names are duplicate: one has : the other has -

**Comment by ukemi** [comment]
Yep. That's why!

**Comment by hdrabkin** [comment]
They have different is_a parents, but I will look closer later.

**Comment by hdrabkin** [comment]
RHEA:42336

**Comment by hdrabkin** [comment]
EC:1.8.7.2 def:
2 reduced ferredoxin + thioredoxin disulfide <=> 2 oxidized ferredoxin + thioredoxin + 2 H(+)

I just noticed for the parents: ONE (GO:0030385) parent is   GO:0016730 ! oxidoreductase activity, acting on **iron-sulfur proteins as donors**
The other (GO:0103012) parent is GO:0016730 ! oxidoreductase activity, acting on a sulfur group of donors, **iron-sulfur protein as acceptor**; the reverse reaction

RHEA:42336 | [thioredoxin]-disulfide + 2 H(+) + 2 reduced [2Fe-2S]-[ferredoxin] = [thioredoxin]-dithiol + 2 oxidized [2Fe-2S]-[ferredoxin]

RHEA:42338     
[thioredoxin]-dithiol + 2 oxidized [2Fe-2S]-[ferredoxin] => [thioredoxin]-disulfide + 2 H(+) + 2 reduced [2Fe-2S]-[ferredoxin]

**Comment by hdrabkin** [comment]
@deustp01 , do you have any insight? I might have overthought this..

**Comment by ValWood** [comment]
pinging @deustp01 
added "waiting for feedback" label.

**Comment by pgaudet** [comment]
Merged, and removed 'part of' chloroplast for 'ferredoxin:thioredoxin reductase complex since the enzyme is also present in bacteria according to EC https://enzyme.expasy.org/EC/1.8.7.2. 

Thanks, Pascale

**Comment by pgaudet** [comment]
RHEA:42336 is the non-directional reaction, so no need to worry about having both parents. I kept the same as EC: 'oxidoreductase activity, acting on a sulfur group of donors, iron-sulfur protein as acceptor'.

**Comment by pgaudet** [comment]
Also added taxon constraints 
GO:0103012	ferredoxin-thioredoxin reductase activity	NCBITaxon:33090	Viridiplantae
GO:0030386	ferredoxin:thioredoxin reductase complex	NCBITaxon:33090	Viridiplantae
