### ISSUE TITLE
MP:GO:1990758   mitotic sister chromatid biorientation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18937]
Should be is_a
GO:0051315    attachment of mitotic spindle microtubules to kinetochore

**Comment by ValWood** [comment]
(note that the non mitotic term already has this parent)

**Comment by pgaudet** [comment]
It already is - how come you don't see it ?

**Comment by ValWood** [comment]
I didn't see it in Canto so I checked QuickGO.

The regulation terms have it the parentage to the regulation terms.
I will double check....

**Comment by ValWood** [comment]
I think it is the regulation terms that aren't connected

under 
GO:1902423    regulation of attachment of mitotic spindle microtubules to kinetochore
I do not see the biorientation regulation terms

**Comment by pgaudet** [comment]
OK. That's probably because regulates is not transitive over is_a. This is what we wanted, for example we dont want 'regulation of ATPase-coupled transporter activity' to be a 'regulation of ATP activity'. So if you want the link I will infer it. 

Thanks, Pascale

**Comment by ValWood** [comment]
yes please, regulation of 
GO:1990758 mitotic sister chromatid biorientation
is a
GO:0051315 attachment of mitotic spindle microtubules to kinetochore

Its a pity the inference can't be cleverer and infer over regulation which isn't "has_part"
@cmungall @balhoff

**Comment by cmungall** [comment]
> That's probably because regulates is not transitive over is_a

Not sure what you mean. If R1 regulates some X, and R2 subClassOf R1, then R1 regulates some X. No property chain declarations required, this is just OWL

**Comment by pgaudet** [comment]
Right @cmungall ! I was think has_part 

Then I don't know why the relation @ValWood was expecting was not inferred.

**Comment by ValWood** [comment]
It is there now so closing.
