### ISSUE TITLE
Q replication fork restart

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18936]
I would like to annotate a GP involved in "replication restart"

GO:0031297    replication fork processing
Definition (GO:0031297 GONUTS page)
The process in which a DNA replication fork that has stalled is restored to a functional state and replication is restarted. The stalling may be due to DNA damage, DNA secondary structure, bound proteins, dNTP shortage, or other causes. PMID:11459955 PMID:15367656 PMID:17660542

replication restart | related
replication fork restart | related

Does anyone know why these are related? The first sentence of the def appears to be describing "replication restart"

**Comment by ValWood** [comment]
@mah11  will likely know the answer

**Comment by mah11** [comment]
Please stop saying I know things I don't.

From the definitions, and from a few papers I've seen in recent months, I gather that restarting replication is a knock-on effect -- albeit an adaptively advantageous effect -- of the DNA binding, recombination, etc. events that make up the larger replication fork processing ... er, process.

It might be worthwhile to edit the definition to describe the fork processing steps in a little more detail, but I don't have a big problem with the "restart" synonyms being related.

**Comment by ValWood** [comment]
I said "likely" because you work on the DNA metabolism area of curation.
Apologies if it offends you that I think you might know things.

**Comment by ValWood** [comment]
I used  replication fork processing
