### ISSUE TITLE
obsolete: heterochromatin assembly involved in chromatin silencing at centromere outer repeat region

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18954]
GO:1904497    heterochromatin assembly involved in chromatin silencing at centromere outer repeat region

it is too specific, no annotations
(it's basically  heterochromatin assembly) occurs_at

**Comment by ValWood** [comment]
and
chromatin silencing at centromere outer repeat region (GO:1990141)


(quite a lot of the  "chromatin silencing" terms should probably go in favour of heterochromatin assembly annotations)

**Comment by pgaudet** [comment]
How about 'heterochromatin assembly involved in chromatin silencing by small RNA' ? (this seems like it's formulated the wrong way around? - ie the title of one of the annotated paper seems a better phrasing 'RNAi-dependent heterochromatin assembly')

**Comment by ValWood** [comment]
Yes that sounds much better. I always  disliked this term name!

**Comment by pgaudet** [comment]
GO:1990141 chromatin silencing at centromere outer repeat region

has another child (in addition to GO:1904497 heterochromatin assembly involved in chromatin silencing at centromere outer repeat region) 

GO:1902368 heterochromatin maintenance involved in chromatin silencing at centromere outer repeat region 
2 EXP pombase. 

This term will also be obsoleted.

**Comment by ValWood** [comment]
both fixed

**Comment by pgaudet** [comment]
GO:1990141 chromatin silencing at centromere outer repeat region
 => 1 MGI, 3 pombase annotations. No mappings, no subsets.
GO:1904497 heterochromatin assembly involved in chromatin silencing at centromere outer repeat region => 1 pombase annotation. No mappings, no subsets.
GO:1902368 heterochromatin maintenance involved in chromatin silencing at centromere outer repeat region => 2 pombase annotations. No mappings, no subsets.

**Comment by pgaudet** [comment]
How about if I merged in the parents, would that be better ? 

* 'chromatin silencing at centromere outer repeat region' -> merge into 'chromatin silencing at centromere'
* 'heterochromatin maintenance involved in chromatin silencing at centromere outer repeat region'  -> merge into 'heterochromatin maintenance involved in chromatin silencing'
* 'heterochromatin assembly involved in chromatin silencing at centromere outer repeat region' -> 'heterochromatin assembly involved in chromatin silencing'

**Comment by ValWood** [comment]
We need to discuss, merging is better. Will add more soon.

**Comment by pgaudet** [comment]
Should I already merge those 3 ?

**Comment by ValWood** [comment]
@pgaudet  could you send me a  list of all the terms under "chromatin silencing"

I will do a spreadsheet of what  all the terms should move into (Have been thinking about it a lot).
Then can see what @colinlog  says on Friday 
(will circulate for comments as soon as I have done it).

**Comment by pgaudet** [comment]
Here is the list of the terms + the number of EXP annotations
https://docs.google.com/spreadsheets/d/1a-iWPesVFSTpSgRIx9p8D5D5BLNjzMGI8wHVmqvWu5Q/edit#gid=0

**Comment by ValWood** [comment]
OK I filled in the spreadsheet with what I think we should do with these.

If everyone agrees with this, we still need (later) to decide what are the appropriate  classifiers to use in the 
"heterochromatin assembly" branch (mechanism, facultative/ constitutive, genome location)

I suggest merges first and then see what the annotation looks like.
SGD  @srengel  and FlyBase @hattrill  should comment because along with PomBase  they have the vast majority of the annotations


(327) | SGD
-- | --
+ | − | (205) | PomBase
+ | − | (129) | FlyBase
+ | − | (73) | UniProt
+ | − | (45) | TAIR
+ | − | (17) | MGI
+ | − | (14) | CGD
+ | − | (11) | BHF-UCL
+ | − | (8) | GeneDB
+ | − | (4) | AspGD
+ | − | (4) | WB
+ | − | (3) | ARUK-UCL
+ | − | (2) | ComplexPortal
+ | − | (1) | CACAO

I sanity checked the annotations and it seems they would make sense for  the merges but  if we decide to go ahead, it might be worth people sanity checking their annotations again.

 A bit of background

Silencing has been problematic for a long time:

- Many of these terms were added before the mechanism became clear, and mostly these are  usually 'heterochromatin assembly phenotypes"
- - The PomBase  chromatin community have complained about the GO terms saying  (paraphrasing), it's time we moved on, we know the biology here. 
- Silencing is related to "negative regulation of transcription" but this isn't strictly correct for constitutive heterochromatin. The default state is transcriptionally silent so it isn't really directly  'negatively regulating transcription' 
-  these reorganization will allow us to have *only* the chromatin remodellers which are more closely related to active transcription in the transcription branch

Is that an accurate summary?

**Comment by ValWood** [comment]
Note, on the last call we talked about whether we wanted to keep the location specific terms in the "heterochromatin assembly" branch.
I think @RLovering  and @colinlog  thought that we did? Is that correct.

I would be happy either way, but if these were removed I would want to capture the locations with "occurs_at"

I can see that there would be advantages. It would be easier to classify by facultative/constitutive and by mechanism (RNAi dependent heterochromatin assembly),  if we did not need to factor in location too.

There are also terms like
GO:0031454   regulation of extent of heterochromatin assembly

**Comment by pgaudet** [comment]
Remaining edits will be done here: #19112

**Comment by pgaudet** [comment]
GO:1904497 was merged into 'GO:0031507 heterochromatin assembly'

**Comment by pgaudet** [comment]
GO:0031507 heterochromatin assembly
 -> remove relation  'part of' some 'chromatin silencing'
