### ISSUE TITLE
Change xrefs GO:0043770 demethylmenaquinone methyltransferase activity and related 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18959]
Cleaning up IMG: cross references #18908

@hdrabkin what do you think about merging those ? Last 3 are pz

GO:0043770 demethylmenaquinone methyltransferase activity
0 annotations wikipedia mentions EC 2.1.1.163

GO:0102094 S-adenosylmethionine:2-demethylmenaquinol methyltransferase activity
0 annotations

GO:0102955 S-adenosylmethionine:2-demethylmenaquinol-7 methyltransferase activity
1 annotation IEA EC mapping 

GO:0102027 S-adenosylmethionine:2-demethylquinol-8 methyltransferase activity
0 annotations

Thanks, Pascale

**Comment by hdrabkin** [comment]
a quionine and quionol are different; 
Also note diff substrates for 55 and 56
We had a similar type of thing a couple of weeks ago where it turns out that on quionine had to be converted to a quionol by a separate enzyme.

**Comment by pgaudet** [comment]
Cleaning up IMG: cross references #18908

**Comment by hdrabkin** [comment]
Do not merge

GO:0043770 is this rhea
RHEA:26466 | a 2-demethylmenaquinone + S-adenosyl-L-methionine = a menaquinone + H(+) + S-adenosyl-L-homocysteine

GO:0102955 is this rhea
RHEA:33255 | 2-demethylmenaquinol-7 + S-adenosyl-L-methionine = H(+) + menaquinol-7 + S-adenosyl-L-homocysteine

GO:0102027 is this RHEA
RHEA:30063 | 2-demethylmenaquinol-8 + S-adenosyl-L-methionine = H(+) + menaquinol-8 + S-adenosyl-L-homocysteine

All of these map to same EC in RHEA
EC 2.1.1.163

**Comment by hdrabkin** [comment]
(actually that EC maps to 11 different RHEA entries based on differences in substrates.
https://www.rhea-db.org/searchresults?q=EC%3A2.1.1.163

Note that this RHEA is less specific for the -ol substrates. 
THE RHEA 26466 is the more generic for the -one substrates
RHEA:42640 | a 2-demethylmenaquinol + S-adenosyl-L-methionine = a menaquinol + H(+) + S-adenosyl-L-homocysteine
-- | --

**Comment by pgaudet** [comment]
GO:0102094 S-adenosylmethionine:2-demethylmenaquinol methyltransferase activity
Added 
RHEA:26466

**Comment by pgaudet** [comment]
OK I didn't merge, but I am not convinced those are really different activities. 3 out of the 4 terms cite the same 2 papers (PMID:1444716 and PMID:9045837), describing the the Escherichia coli ubiE gene, as if it could have slightly different substrates: 
https://www.rhea-db.org/searchresults?q=2.1.1.163

Thanks, Pascale
