### ISSUE TITLE
What is GO:0043744 N2-acetyl-L-aminoadipate kinase activity ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18966]
Working on #18908 

GO:0043744
name: N2-acetyl-L-aminoadipate kinase activity
namespace: molecular_function
alt_id: GO:0043868
def: "Catalysis of the reaction: ATP + N-acetyl-L-aminoadipate = ADP + N-acetyl-L-aminoadipate 5-phosphate." [IMG:01448]

Has no annotations. 
Has a xref to https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-5182 but I cannot figure out why. 

@hdrabkin what do you think about that one ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
It's mapped to that Metacyc because
N-acetyl-L-2-aminoadipate(2−) is what the 'amino group carrier protein' is linked to 

This appears to be related to this
RHEA:28586 | ATP + N-acetyl-L-2-aminoadipate = ADP + N-acetyl-L-2-aminoadipate 6-phosphate
but this rhea product is the 6-phosphate not the 5. 
metacyc has this 
Enzyme Commission Primary Name: [amino group carrier protein]-L-2-aminoadipate 6-kinase 
Which I can't find in EC 
DO  you remember what IMG stood for?




-

**Comment by hdrabkin** [comment]
Ok; found where to get these.
SO, the IMG:01448
can be found here
https://img.jgi.doe.gov/cgi-bin/proportal/main.cgi?section=ImgTermBrowser&page=imgTermBrowser
But you need to search on "1448"; they do not use IMG or the leading zero 
Doing that you find
     1448  N2-acetyl-L-aminoadipate kinase (EC 2.7.2.-) which goes to a IMG Term Details page
where we find they have it crossed referenced to EC:2.7.2.-
it's part of the L-lysine synthesis by prokaryotic aminoadipate pathway
So important.

**Comment by pgaudet** [comment]
RHEA:28586          (OBSOLETE)

**Comment by pgaudet** [comment]
Replaced by RHEA:41944          (APPROVED)

[2-aminoadipate-carrier protein]-C-terminal-gamma-(L-2-aminoadip-2-yl)-L-glutamate + ATP = [2-aminoadipate-carrier protein]-C-terminal-gamma-(6-phospho-L-2-aminoadip-2-yl)-L-glutamate + ADP

**Comment by hdrabkin** [comment]
Ok, I'll tell Anne

**Comment by hdrabkin** [comment]
RHEA:28586 | ATP + N-acetyl-L-2-aminoadipate = ADP + N-acetyl-L-2-aminoadipate 6-phosphate fits but again, t

generate a 6-phosphate, not a 5
-- | --

**Comment by pgaudet** [comment]
Good references PMID:26966182 and PMID:25392000

Sound like it could be a child of

**Comment by pgaudet** [comment]
I wonder if it should be a child of 'molecular carrier activity' ?
@pedruzzi

**Comment by pgaudet** [comment]
"Several bacteria and archaea utilize the amino group-carrier protein, LysW, for lysine biosynthesis, in which an isopeptide bond is formed between the C-terminal Glu of LysW and an amino group of α-aminoadipate (AAA). **The resulting LysW-γ-AAA is phosphorylated by LysZ to form LysW-γ-AAA phosphate**, which is subsequently reduced to LysW-γ-aminoadipic semialdehyde (LysW-γ-AASA) through a reaction catalyzed by LysY. " (PMID:26966182)

So this is an 'amino acid kinase activity' (although the amino acid is modified when attached to a carrier protein).

**Comment by hdrabkin** [comment]
I'm thinking the '5-phosphate'  in the term def is an error because if you look at the structure of the  N-acetyl-L-2-aminoadipate I can't see where there would be a 5 phosphate; it should be 6

**Comment by pgaudet** [comment]
I think RHEA:41944 is right, NOT RHEA:28586

**Comment by hdrabkin** [comment]
In any event the def needs to be changed to the 6-phosphate

**Comment by pgaudet** [comment]
**New is bold**
_Removed is italics_

GO:0043744
 name: N2-acetyl-L-aminoadipate kinase activity
_-def: "Catalysis of the reaction: ATP + N-acetyl-L-aminoadipate = ADP + N-acetyl-L-aminoadipate 5-phosphate." [IMG:01448]_
**+def: "Catalysis of the reaction: ATP + N-acetyl-L-2-aminoadipate = ADP + N-acetyl-L-2-aminoadipate 6-phosphate." [PMID:25392000, PMID:26966182, RHEA:41944]
+synonym: "[LysW]-aminoadipate kinase" RELATED []**
 synonym: "acetylaminoadipate kinase activity" EXACT []
_-synonym: "LysZ" RELATED []_
 synonym: "N-acetyl-L-aminoadipate 5-phosphotransferase activity" EXACT []
 synonym: "N-acetylaminoadipate kinase activity" EXACT []
 xref: MetaCyc:RXN-5182
_-is_a: GO:0016301 ! kinase activity_
**+xref: RHEA:41944**
 is_a: GO:0016774 ! phosphotransferase activity, carboxyl group as acceptor
**+is_a: GO:0019202 ! amino acid kinase activity**

**Comment by hdrabkin** [comment]
FWIW, I have a file for RHEA where 41944 is the id they mapped go GO:0043744
--
