### ISSUE TITLE
Merge GO:0043775 cobyrinate a,c-diamide synthase activity and  GO:0042242 cobyrinic acid a,c-diamide synthase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18960]
@hdrabkin Do you agree with merging these ? 

GO:0043775 cobyrinate a,c-diamide synthase activity
0 annotations
EC:6.3.5.11 
RHEA:26289

GO:0042242 cobyrinic acid a,c-diamide synthase activity
EC:6.3.5.11
0 annotations 
PMID:2172209

**Comment by hdrabkin** [comment]
Merge first into second ; cobyrinic acid would not exist in solution I think (
use 42242 name as a related synonym.

**Comment by hdrabkin** [comment]
I'm sorry if not clear; the first term with rhea and ec should be the primary term.
GO:0043775 cobyrinate a,c-diamide synthase activity

**Comment by pgaudet** [comment]
Cleaning up IMG: cross references #18908
