### ISSUE TITLE
Find reference for GO:0043836 xanthine hydrolase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18968]
Working on #18908

id: GO:0043836
name: xanthine hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: xanthine + H2O = 4-ureido-5-imidazole carboxylate." [IMG:01834, MetaCyc:R127-RXN] 
No annotations
MetaCyc mentions an 'xanthine amidohydrolase' 

~into 
GO:0004854
name: xanthine dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: xanthine + NAD+ + H2O = urate + NADH + H+." [EC:1.17.1.4]
MetaCyc:RXN0-901~

~Sounds like MetaCyc:R127-RXN] is a little dubious and GO:0004854 and GO:0043836 represent the same activity.~

I'd like a reference to replace the IMG in GO:0043836.

Thanks, Pascale

**Comment by pgaudet** [comment]
@keseler @hdrabkin What do you think ?

**Comment by hdrabkin** [comment]
hydrolase and dehydrogenase are very different.  
I do not think these are the same. Different products. 
4-ureido-5-imidazole carboxylate. == 27580
urate == CHEBI:27216

Why are you saying the Metacyc rxn is dubious?

**Comment by keseler** [comment]
MetaCyc:R127-RXN is based on a couple of 1950's papers using unpurified enzymes.  I haven't checked if there is more recent data using purified enzymes, but it seems to be one of the crucial steps in a purine degradation pathway, PWY-5497.  It's a hydrolysis reaction that involves ring opening.

MetaCyc:RXN0-901 involves oxidation (no ring opening) using NAD.

So I agree with Harold that they are very different reactions, and should both be kept.  Now if only we could get people to fund the follow up on some old biochemistry...

**Comment by pgaudet** [comment]
Thanks @keseler 

Can you please provide the old paper ? I'll use that as a citation for GO:0043836
name: xanthine hydrolase activity. 

Thanks, Pascale

**Comment by keseler** [comment]
Sure, it's PMID 13278326.
Have a nice weekend!
-Ingrid

**Comment by pgaudet** [comment]
Thanks!
