### ISSUE TITLE
Add cross references GO:0043795 glyceraldehyde oxidoreductase activity into     GO:0043797 Name     glyceraldehyde-3-phosphate dehydrogenase (ferredoxin) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18961]
Cleaning up IMG: cross references #18908

@hdrabkin 
Do you agree with merging 
GO:0043795 glyceraldehyde oxidoreductase activity (single annotation, potentially incorrect, no EC)
Catalysis of the reaction: D-glyceraldehyde + H2O + acceptor = D-glycerate + reduced acceptor.

into 
GO:0043797  glyceraldehyde-3-phosphate dehydrogenase (ferredoxin) activity 
Catalysis of the reaction: D-glyceraldehyde-3-phosphate + H2O + 2 oxidized ferredoxin = 3-phospho-D-glycerate + 2 H+ + 2 reduced ferredoxin.
https://enzyme.expasy.org/EC/1.2.7.6

This is the closest reaction, going by definitions. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
They appear different. 
first rxn corresponds to https://www.genome.jp/dbget-bin/www_bget?ec:
ENZYME entry: EC 1.2.99.8, exact same reaction, RHEA:36047
Second reaction maps to RHEA:24148, EC:1.2.7.6

**Comment by pgaudet** [comment]
Cleaning up IMG: cross references #18908

**Comment by hdrabkin** [comment]
Do NOT merge; they are different. Add RHEA and ECs where missing

**Comment by pgaudet** [comment]
Will do, thanks.

**Comment by pgaudet** [comment]
dimethylamine methyltransferase activity
 namespace: molecular_function
 def: "Catalysis of the reaction: dimethylamine + a dimethylamine corrinoid protein = a methylated dimethylamine corrinoid protein + methylamine." [PMID:9874228]
 comment: This function is the first step in the pathway of methanogenesis from dimethylamine.
-synonym: "dimethylamine:corrinoid methyltransferase activity" EXACT []
 synonym: "dimethylamine-specific methylcobalamin:coenzyme M methyltransferase activity" NARROW []
+synonym: "dimethylamine:corrinoid methyltransferase activity" EXACT []
 synonym: "DMA methyltransferase 1" EXACT []
 synonym: "DMAMT 1" EXACT []
 synonym: "MT1" BROAD []
@@ -247312,7 +247312,9 @@ is_a: GO:0016903 ! oxidoreductase activity, acting on the aldehyde or oxo group
 id: GO:0043795
 name: glyceraldehyde oxidoreductase activity
 namespace: molecular_function
-def: "Catalysis of the reaction: D-glyceraldehyde + H2O + acceptor = D-glycerate + reduced acceptor." [IMG:01506]
+def: "Catalysis of the reaction: A + D-glyceraldehyde + H2O = (R)-glycerate + AH2 + H(+)." [PMID:10095793, RHEA:36047]
+xref: EC:1.2.99.8
+xref: RHEA:36047
