### ISSUE TITLE
Add xref hydroxyneurosporene-O-methyltransferase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18962]
Cleaning up IMG: cross references #18908

I dont find any references to 
id: GO:0043803
name: hydroxyneurosporene-O-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: demethylspheroidene + S-adenosyl-L-methionine = spheroidene + S-adenosyl-L-homocysteine." [IMG:01759]

No annotations, no mappings. Anyone knows what this is ? 

@hdrabkin @kaxelsen @amorgat 

If not I will propose to obsolete. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
This one is RHEA:30903 demethylspheroidene + S-adenosyl-L-methionine = H(+) + S-adenosyl-L-homocysteine + spheroidene

**Comment by kaxelsen** [comment]
And it is linked to EC 2.1.1.210 and three Swiss-Prot entries in Rhodobacter

**Comment by hdrabkin** [comment]
Oh good; we can add an ec too while we are at it. 
and add these PMIDs from RHEA
PMID: 12664193
PMID: 12770713
PMID: 7358679

**Comment by hdrabkin** [comment]
SO I looked in Amigo again
zero annotations.  Do these annotations to Rhodobacter not get submitted to GO?

**Comment by hdrabkin** [comment]
Ok; I find them in quickgo.
So this is a real problem is we cannot find annotations in the GO's official browser.

**Comment by kaxelsen** [comment]
I don't know, I am not doing the annotations.

**Comment by hdrabkin** [comment]
Maybe @pgaudet can comment

**Comment by pgaudet** [comment]
@hdrabkin you find annotations to hydroxyneurosporene-O-methyltransferase in QuickGO ?

**Comment by hdrabkin** [comment]
Yes I did

**Comment by pgaudet** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0043803 ?

**Comment by hdrabkin** [comment]
Ok, did not see significance of that box
BUT:
@keseler saw annotations ; 
three Swiss-Prot entries in Rhodobacter? 
And if is has a valid EC and valid RHEA, I think we should leave it.

**Comment by pgaudet** [comment]
Yep, thanks for the detective work !
