### ISSUE TITLE
What is GO:0043810 ornithine-acyl [acyl carrier protein] N-acyltransferase activity?

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18965]
Fixing IMG: xrefs #18908

GO:0043810
name: ornithine-acyl [acyl carrier protein] N-acyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-3-hydroxyacyl-[acyl-carrier protein] + L-ornithine = lyso-ornithine lipid + [acyl-carrier protein]." [IMG:02096]

I dont find any EC to this, and no reference.

@hdrabkin Do you know what it is ?

Thanks, Pascale

**Comment by hdrabkin** [comment]
https://img.jgi.doe.gov/cgi-bin/m/main.cgi?section=ImgTermBrowser&page=imgTermBrowserGenes&term_oid=2096
this is the name  associated with 10510 gene(s) at JGI and 1153 Trembl records at UniProt; none of them have a RHEA reaction 
I cannot find any reaction in RHEA; only one RHEA:53836  uses the (3R)-3-hydroxyacyl-[acyl-carrier protein] as a substrate (acp is their abbreviation for acyl-carrier protein) and its NOT this reaction.
I find no annotations in AMIGO to this term. Should we axe it?

**Comment by pgaudet** [comment]
@hdrabkin 
I think this provides evidence for the term ? 

PMID:30972461

**Comment by hdrabkin** [comment]
I'm not seeing how this paper can define
(3R)-3-hydroxyacyl-[acyl-carrier protein] + L-ornithine = lyso-ornithine lipid + [acyl-carrier protein]. at all.
It maybe shows the existence of the lipid, but not sure it defines how it came to be

**Comment by pgaudet** [comment]
@hdrabkin 

how about 
RHEA:20633          
a (3R)-hydroxyacyl-[ACP] + L-ornithine = a lyso-ornithine lipid + H(+) + holo-[ACP]

**Comment by hdrabkin** [comment]
Ah; yes that looks like it ; missed it. 
Maybe also add PMID:15341653 to def along with the rhea (the ref comes from the rhea entry).

**Comment by hdrabkin** [comment]
Maybe EC 2.3.2.30 also as xref (its maps to 
RHEA:20633
--

**Comment by pgaudet** [comment]
great, thanks !
