### ISSUE TITLE
What is GO:0043759 name: branched-chain acyl-CoA synthetase (ADP-forming) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18967]
Working on #18908

GO:0043759
name: branched-chain acyl-CoA synthetase (ADP-forming) activity
def: "Catalysis of the reaction: ATP + 2-methylbutanoate + CoA = ADP + orthophosphate + 2-methylbutanoyl-CoA." [IMG:01425]

No annotations, no other mappings. 

@hdrabkin 

Thanks, Pascale

**Comment by hdrabkin** [comment]
The reaction matches

RHEA:46180 | 2-methylbutanoate + ATP + CoA = 2-methylbutanoyl-CoA + AMP + diphosphate
I don't like the term name compared to the reaction.
RHEA ref
Fujino T, Takei YA, Sone H, Ioka RX, Kamataki A, Magoori K, Takahashi S, Sakai J, Yamamoto TT.
(2001)
Molecular identification and characterization of two medium-chain acyl-CoA synthetases, MACS1 and the Sa gene product.
The Journal of biological chemistry
276, 35961-35966
PMID: 11470804

At JGI 
(Protein Complex)  1425  branched-chain acyl-CoA synthetase (ADP-forming) (EC 6.2.1.-)
          762  branched-chain acyl-CoA synthetase (ADP-forming) alpha subunit (EC 6.2.1.-)
          763  branched-chain acyl-CoA synthetase (ADP-forming) beta subunit (EC 6.2.1.-)

**Comment by hdrabkin** [comment]
Might be useful to contact https://img.jgi.doe.gov/ to get proper link-out 
Clearly they no longer use IMG: I had to strip IMG:0 and the a command-F for 1425 to find their records

**Comment by pgaudet** [comment]
Right - I am removing link to IMG, also because they were link to *genes*, we cannot do this (this is an annotation...)

**Comment by pgaudet** [comment]
Should I just add the Rhea ?

Do you want to change the term label  ?

**Comment by hdrabkin** [comment]
I'm writing t them now;

**Comment by hdrabkin** [comment]
No wait
The RHEA reaction is not ADP forming
Definitely add the PMID

**Comment by pgaudet** [comment]
The PMID: 11470804 talks about 'medium-chain acyl-CoA synthetase' which corresponds to https://enzyme.expasy.org/EC/6.2.1.2

We have 10 terms that correspond to that EC: 

GO:0047476 | 3-alpha,7-alpha-dihydroxy-5-beta-cholestanate-CoA   ligase activity'
-- | --
GO:0018859 | 4-hydroxybenzoate-CoA ligase activity'
GO:0008771 | [citrate (pro-3S)-lyase] ligase activity'
GO:0018858 | benzoate-CoA ligase activity'
GO:0047760 | butyrate-CoA ligase activity'
GO:0047747 | cholate-CoA ligase activity'
GO:0047851 | dicarboxylate-CoA ligase activity'
GO:0008922 | long-chain fatty acid [acyl-carrier-protein] ligase activity'
GO:0008756 | o-succinylbenzoate-CoA ligase activity'
GO:0050197 | phytanate-CoA ligase activity'


Do we need an 11th ? 

Thanks, Pascale

**Comment by alanbridge** [comment]
medium-chain acyl-CoA synthetase is Rhea:48340 - https://www.rhea-db.org/reaction?id=48340 - you could have a GO term for that, and possible the child reactions too like: 

RHEA:33623	ATP + CoA + dodecanoate = AMP + diphosphate + dodecanoyl-CoA
RHEA:33627	ATP + CoA + decanoate = AMP + decanoyl-CoA + diphosphate	
RHEA:33631	ATP + CoA + octanoate = AMP + diphosphate + octanoyl-CoA	
RHEA:43740	ATP + CoA + hexanoate = AMP + diphosphate + hexanoyl-CoA	
RHEA:44080	ATP + CoA + undecanoate = AMP + diphosphate + undecanoyl-CoA	
RHEA:44088	ATP + CoA + heptanoate = AMP + diphosphate + heptanoyl-CoA	
RHEA:44228	9-decenoate + ATP + CoA = 9-decenoyl-CoA + AMP + diphosphate	
RHEA:54952	ATP + CoA + nonanoate = AMP + diphosphate + nonanoyl-CoA	

Of the 10 terms you cite that correspond to https://enzyme.expasy.org/EC/6.2.1.2 a few don't seem right.


GO:0047476 | 3-alpha,7-alpha-dihydroxy-5-beta-cholestanate-CoA ligase activity'
-- | --
GO:0018859 | 4-hydroxybenzoate-CoA ligase activity'
GO:0008771 | [citrate (pro-3S)-lyase] ligase activity'
GO:0018858 | benzoate-CoA ligase activity'

GO:0047747 | cholate-CoA ligase activity' - cholate is not a medium chain acyl group
GO:0047851 | dicarboxylate-CoA ligase activity' - a dicarboxylate is not necessarily a medium chain acyl group
GO:0008922 | long-chain fatty acid [acyl-carrier-protein] ligase activity' - a long chain is not a medium chain, and acyl carrier protein is not CoA 
GO:0008756 | o-succinylbenzoate-CoA ligase activity'
GO:0050197 | phytanate-CoA ligase activity'

**Comment by pgaudet** [comment]
Thanks @alanbridge 

Do you propose to obsolete those 9 terms: 

GO:0047476 | 3-alpha,7-alpha-dihydroxy-5-beta-cholestanate-CoA ligase activity'
GO:0018859 | 4-hydroxybenzoate-CoA ligase activity'
GO:0008771 | [citrate (pro-3S)-lyase] ligase activity'
GO:0018858 | benzoate-CoA ligase activity'
GO:0047747 | cholate-CoA ligase activity' - cholate is not a medium chain acyl group
GO:0047851 | dicarboxylate-CoA ligase activity' - a dicarboxylate is not necessarily a medium chain acyl group
GO:0008922 | long-chain fatty acid [acyl-carrier-protein] ligase activity' - a long chain is not a medium chain, and acyl carrier protein is not CoA
GO:0008756 | o-succinylbenzoate-CoA ligase activity'
GO:0050197 | phytanate-CoA ligase activity'

?

**Comment by hdrabkin** [comment]
or just change parentage on some? (eg GO:0008922 )?

**Comment by pgaudet** [comment]
right I see

**Comment by alanbridge** [comment]
not necessarily obsolete them but they are wrongly classified

**Comment by pgaudet** [comment]
GO:0031956 medium-chain fatty acid-CoA ligase activity
defined as Catalysis of the reaction: ATP + a medium-chain carboxylic acid + CoA = AMP + diphosphate + an acyl-CoA; a medium-chain fatty acid is any fatty acid with a chain length of between C6 and C12.

corresponds to Rhea:48340 mentioned by @alanbridge , so I will add the xref to this term. 

ALSO GO:0031956 is linked to EC:6.2.1.3 which corresponds to 'long-chain fatty acid-CoA ligase activity' , so I will edit the xref to EC:6.2.1.2 (based on RHEA xref). 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also fixed GO:0004467 long-chain fatty acid-CoA ligase activity to add RHEA:15421

**Comment by pgaudet** [comment]
GO:0102391 decanoate-CoA ligase activity
removed EC:6.2.1.3 (does not mention this activity); added RHEA:33627 as suggested above
https://github.com/geneontology/go-ontology/issues/18967#issuecomment-592030911

**Comment by pgaudet** [comment]
> Of the 10 terms you cite that correspond to https://enzyme.expasy.org/EC/6.2.1.2 a few don't seem to be correctly classified:


Right sorry, that was a mistake - those were EC/6.2.1.2x - completely unrelated.

**Comment by pgaudet** [comment]
GO:0043759 name: branched-chain acyl-CoA synthetase (ADP-forming) activity: 
- added GO:0031956 parent medium-chain fatty acid-CoA ligase activity
- added RHEA:46180
- changed label to methylbutanoate-CoA ligase activity
- fixed definition to "Catalysis of the reaction: ATP + 2-methylbutanoate + CoA = AMP +  diphosphate + 2-methylbutanoyl-CoA."

Thanks, Pascale
