### ISSUE TITLE
Add defxref cyclic nucleotide-gated mechanosensitive ion channel activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18969]
Working on #18908

Does this exist ? I cannot find any reference to it. 
id: GO:0043854
name: cyclic nucleotide-gated mechanosensitive ion channel activity
namespace: molecular_function
def: "Enables the transmembrane transfer of an ion by a channel that opens in response to a mechanical stress and when a cyclic nucleotide has been bound by the channel complex or one of its constituent parts." 

If not I will merge into 
id: GO:0043855
name: cyclic nucleotide-gated ion channel activity
namespace: molecular_function
def: "Enables the transmembrane transfer of an ion by a channel that opens when a cyclic nucleotide has been bound by the channel complex or one of its constituent parts." 

@dosumis Maybe you came across this ? 

Thanks, Pascale

**Comment by dosumis** [comment]
A quick google search turned up this:

https://www.sciencedirect.com/science/article/pii/S0006291X11022583

I  guess co-annotation could be  sufficient though as, IIRC, we have  mechanically gated ion channel activity.

**Comment by pgaudet** [comment]
Also fixed logical definition to be consistent with term label and def: 

-intersection_of: regulated_by GO:0030552 ! cAMP binding
+intersection_of: regulated_by GO:0030551 ! cyclic nucleotide binding
