### ISSUE TITLE
What is GO:0043804 imidazolone hydrolase activity ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18964]
Fixing IMG: xrefs #18908 

id: GO:0043804
name: imidazolone hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: N-formiminoglycine = imidazolone + H2O." [IMG:02122]

I dont find any EC to this, and no reference. 

@hdrabkin Do you know what it is ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Maybe related
RHEA:24935 | H2O + imidazol-4-one = N-formimidoylglycine
RHEA uses CHEBI:58479 N-formimidoylglycine zwitterion fo rN-formiminoglycine
(Formiminoglycine is a synonym of formimidoglycine).
Interestingly, RHEA notes that :24935 can occur spontaineously
the term 'imidazolone ' appears to be a parent term to many other terms such as imidazol-4-one
RHEA record has several references.

**Comment by pgaudet** [comment]
I think it's the reverse reaction 
RHEA:24937          (APPROVED)

N-formimidoylglycine => H2O + imidazol-4-one

**Comment by pgaudet** [comment]
id: GO:0043804
 name: imidazolone hydrolase activity
 namespace: molecular_function
-def: "Catalysis of the reaction: N-formiminoglycine = imidazolone + H2O." [IMG:02122]
+def: "Catalysis of the reaction: N-formimidoylglycine => H2O + imidazol-4-one." [PMID:27286964, RHEA:24937]
+comment: Note that this reaction can occur spontaneously (see RHEA:24937).
+xref: RHEA:24937
