### ISSUE TITLE
Merge GO:0034300 sporangiospore formation into GO:0043582 sporangium development ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18982]
Merge 
id: GO:0034300
name: sporangiospore formation
namespace: biological_process
def: "The process in which sporangiospores, a type of asexual spore found in fungi, are formed. Sporangiospores are formed within sac-like structure, the sporangium, following the division of the cytoplasm." [GOC:ds, GOC:mah, http://bugs.bio.usyd.edu.au/Mycology/Glossary/glossary_n_z.shtml]
is_a: GO:0043936 ! asexual sporulation resulting in formation of a cellular spore

=> 0 annotations, 0  mappings

GO:0043582 sporangium development
=> 0 annotations, 0  mappings

Are those the same ? 
Which species do they apply to ? 

@mah11 @marekskrzypek 

Thanks, Pascale

**Comment by mah11** [comment]
These are not the same. Sporangiospores (as in GO:0034300) are, well, spores, i.e. a type of cell. A sporangium (GO:0043582) is a structure - larger and often multicellular - in (or maybe on, in some species) which spores develop.

I'm sure both are specific to fungi, but I don't know enough to support any more specific taxon restriction. I looked into various fungal spore types for FAO, which doesn't have a separate term for "sporangiospore" I also didn't find much to distinguish sporangiospores from others, except that they develop in a sporangium, which is pretty circular. So I'm not sure GO needs GO:0034300. The ID says I added it, but so long ago that I feel no shame at not remembering a damn thing about doing so ;)

In general, it wasn't easy to define some of the spore types that *are* in FAO ...

**Comment by pgaudet** [comment]
Thanks @mah11 
Do you by any change have references for those concepts ? The xrefs don't wonk anymore 
(http://bugs.bio.usyd.edu.au/Mycology/Glossary/glossary_n_z.shtml) 

Thanks, Pascale

**Comment by mah11** [comment]
Unfortunately, I don't have anything specific for sporagium or sporangiospore. For sporangium, the FAO definition is really broad ("A structure within which spores develop.") and cites FAO:curators from before I inherited the ontology. Some of its subclasses have a little more to go on, but not much. Not sure I can do much more than share the frustration :/

I did find this ebook helpful for some terms, tho I don't remember offhand how much it says about sporangi-anything:
https://books.google.co.uk/books?id=oEmKmLkFaWwC

**Comment by mah11** [comment]
oh, I just remembered that Steve Oliver suggested a couple of people to consult about FAO generally. I haven't had time to follow up yet, but I'll forward the email off-ticket.

**Comment by pgaudet** [comment]
Thanks!

**Comment by pgaudet** [comment]
Closing this because OF COURSE we will not merge the spores with the spore-bearing structure. 
I emailed the contacts @mah11 provided and I will open tickets when I know what the action is.
