### ISSUE TITLE
Update README-editors.md to point to actual documentation

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#18986]
We have a README-editors.md file in this repo, as per convention with other OBO ontologies.

The first line states:

A step-by-step guide for GO Ontology Editors can be found at [http://go-ontology.readthedocs.io/](http://go-ontology.readthedocs.io/).

But we decided to move from RTD to the wiki. This should be updated.

It then goes on to say

This Jenkins job will create releases https://build.berkeleybop.org/job/release-go-ontology-snapshot

But this is out of date

**Comment by pgaudet** [comment]
@cmungall 
Do you mind if I delete this folder ? 
https://github.com/geneontology/go-ontology/tree/master/docs

**Comment by pgaudet** [comment]
I would like to merge the 2 README: 

General
https://github.com/geneontology/go-ontology/blob/master/README.md

Editors: 
https://github.com/geneontology/go-ontology/blob/master/src/ontology/README-editors.md

Anything not relevant to editors should go in the General doc.

**Comment by pgaudet** [comment]
@cmungall 
Do we still need the SynGO build ? 
> TEMPORARY

> https://build.berkeleybop.org/job/sync-go-editors-from-github/ - copy from this repo to old svn repo, from which current pipeline currently runs

**Comment by cmungall** [comment]
syngo or sync go?

yes but we don't need it in the README

**Comment by pgaudet** [comment]
> syngo or sync go?

It's sync go - sorry.

**Comment by pgaudet** [comment]
- [x]  Edited  go-ontology/src/ontology/README-editors.md 
- [x]  Edited   go-ontology/README.md 
- [x] Deleted folder go-ontology/docs/ (now replaced by the wiki; links to the wiki are in the READMEs)

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/19041
https://github.com/geneontology/go-ontology/pull/19042
https://github.com/geneontology/go-ontology/pull/19043
