### ISSUE TITLE
clarify term : contact site

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18994]
ID	GO:0044289
Term name contact site
Definition Sites of close apposition of the inner and outer mitochondrial membrane.

There are lots of contact sites

please rename
mitochondrial inner/outer membrane contact site (or similar)

**Comment by ValWood** [comment]
It might work  from a biological perspective to broaden the definition of this term and put it under here:

GO:0044232    organelle membrane contact site

(even though this is "within organelle")

Anyway, there are lots of "contact sites"

**Comment by pgaudet** [comment]
Maybe the relation should be 'adjacent to' organelle rather than 'part of'?

**Comment by ValWood** [comment]
also from duplicate (now closed) #14863

Is "bridge contact site"
Site of contact between the inner and outer mitochondrial membrane found in neuronal mitochondria; may play a role in maintaining the structural integrity of the inner and outer boundary membranes.
https://www.ebi.ac.uk/QuickGO/term/GO:0044285

the same thing too? It doesn't really sound as though it is specific to neuronal mitochondria...that would be odd?

**Comment by pgaudet** [comment]
>mitochondrial inner/outer membrane contact site (or similar) 

is OK within the mitochondrion though, do you agree ?

**Comment by pgaudet** [comment]
Actually this looks like it should be merged with   GO:0044284 mitochondrial crista junction 
Def "A tubular structure of relatively uniform size that connects a mitochondrial crista to the mitochondrial inner boundary membrane"

See PMID: 22009199

Thanks, Pascale

**Comment by pgaudet** [comment]
I broaden the definition of organelle contact site to 

"A zone of apposition between the membranes of an organelle with another membrane, either **another membrane of the same organelle**, that of another organelle, or the plasma membrane. Membrane contact sites (MCSs) are structured by bridging complexes. They are specialized for communication, including the efficient traffic of small molecules such as Ca2+ ions and lipids, as well as enzyme-substrate interactions."

**Comment by pgaudet** [comment]
Also moved 'mitochondrial crista junction' under  organelle contact site

**Comment by pgaudet** [comment]
I will merge GO:0044285 bridge contact site (0 annotations) into GO:0044289 mitochondrial name contact site- I cannot find evidence for 'bridge contact site' .

**Comment by ValWood** [comment]
Yes i think that would be a useful grouping.
