### ISSUE TITLE
evaluate report from OBO dashboard

### ISSUE THREAD

**Issue by nicolevasilevsky** [geneontology/go-ontology#18997]
http://obo-dashboard-test.ontodev.com/

Report here: http://obo-dashboard-test.ontodev.com/go/dashboard.html

**Comment by ukemi** [comment]
Hi @nicolevasilevsky. Can you give us a little more information about this and how we are supposed to evalutate it?

**Comment by balhoff** [comment]
#18251 relates to this.

**Comment by ukemi** [comment]
Thanks @balhoff. I think we still need input from @thomaspd for the description. I will take care of the whitespace error.

**Comment by ukemi** [comment]
@balhoff, do we need to add superclasses to each of the GO root nodes? They are there in the full GO with BFO import.

**Comment by balhoff** [comment]
@ukemi the superclass thing is just an INFO-level message, so I don't think we need to address that now. It might be a confusing change for users if it ends up in the release.

**Comment by pgaudet** [comment]
Added to the ticket #18251

"The Gene Ontology (GO) provides a framework and set of concepts for describing the functions of gene products from all organisms."

(from @thomaspd )

**Comment by ukemi** [comment]
@balhoff, can you add the annotation and close both tickets?

**Comment by balhoff** [comment]
Addressed all issues in #19169.
