### ISSUE TITLE
obsolete - (cellular) response to 17alpha-ethynylestradiol

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#19002]
I am wondering if it is appropriate to have terms for 17alpha-ethynylestradiol in GO when this is a synthetic estrogen and thus not a compound that is part of normal biology. 

**GO:1904486 - response to 17alpha-ethynylestradiol** 1 annotation by IDA
Def: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a 17alpha-ethynylestradiol stimulus.

**GO:1904487 - cellular response to 17alpha-ethynylestradiol** 0 annotations
Def: Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a 17alpha-ethynylestradiol stimulus.

There is only 1 annotation to one of these terms, from this paper. From the abstract, it is clear that 17alpha-ethynylestradiol is not an endogenous estrogen in birds.

Mattsson et al. 2008. **Selective activation of estrogen receptor alpha in Japanese quail embryos affects reproductive organ differentiation but not the male sexual behavior or the parvocellular vasotocin system**. Gen Comp Endocrinol. 159(2-3):150-7. PMID:18805421
> Estradiol is crucial for normal female differentiation in birds. Developmental effects of estrogen are believed to be mediated by slow genomic actions through the nuclear estrogen receptors alpha (ERalpha) and/or beta (ERbeta).  Consequently, exogenous compounds that interfere with the ERs may disrupt sexual differentiation of the reproductive organs and of the brain areas controlling sexual behaviors. The present study was conducted to elucidate the role of ERalpha in xenoestrogen-induced disruption of sexual differentiation in the Japanese quail (Coturnix japonica). Embryonic treatment with the synthetic estrogen, ethinylestradiol (EE(2)), and with the ERalpha-selective agonist, propyl pyrazole triol (PPT), induced oviductal malformations in females and retention of oviducts in males. Both EE(2) and PPT caused weight asymmetry between left and right testes and reduced the cloacal gland area in males. EE(2) significantly reduced the copulatory behavior in males whereas PPT had no effect on this behavior. The sexually dimorphic parvocellular vasotocin-immunoreactive (VT-ir) system in the medial preoptic nucleus (POM), the lateral septum (SL) and the medial part of the nucleus of the stria terminalis (BSTm), was not affected by EE(2) or PPT. Our results suggest that xenoestrogen-induced effects on reproductive organ differentiation are mediated by ERalpha, whereas demasculinization of male copulatory behavior and the VT-ir system appears not to be induced by activation of ERalpha alone.

**Comment by pgaudet** [comment]
I tend to agree - although for sure organisms respond to all types of chemicals they find in the environment. But perhaps synthetic chemicals should be treated separately ? 

ie do we want a class 'response to synthetic chemical' and use extensions to capture the chemical ? 

Note that this also relates to 'detoxification' and children - ie we should use the same solution for any specific children.

**Comment by krchristie** [comment]
> I tend to agree - although for sure organisms respond to all types of chemicals they find in the environment. But perhaps synthetic chemicals should be treated separately ?
> 
> ie do we want a class 'response to synthetic chemical' and use extensions to capture the chemical ?

If an organism is responding to a synthetic chemical it seems that it's generally because that chemical mimics something natural that the organism normally responds to. It seems to me that `response to chemical` with an extension to capture the chemical would be sufficient.
 
Another perspective on 17alpha-ethynylestradiol is that it is engaging the organisms normal ability to respond to estrogen, so it might be best captured by using the term `response to estrogen` and putting the specific chemical in an extension.

**Comment by pgaudet** [comment]
Oh if it's just to mimic the normal substrate I don't think we want to capture it in extensions - extensions should be what is biologically relevant. 

Comments from @vanaukenk @thomaspd would be helpful.

**Comment by pgaudet** [comment]
@krchristie Why is this CHEBI pending of you obsolete it ?

**Comment by krchristie** [comment]
> @krchristie Why is this CHEBI pending of you obsolete it ?

You're right, it doesn't really depend on finishing the ChEBI roles project. I was just thinking about it with that project since that's why I came across it.

**Comment by raymond91125** [comment]
To confirm, we would obsolete with replaced_by
GO:1904486 - response to 17alpha-ethynylestradiol  ->   GO:0043627 response to estrogen
GO:1904487 - cellular response to 17alpha-ethynylestradiol -> GO:0071391 cellular response to estrogen stimulus
