### ISSUE TITLE
taxon constraint issue in P2GO: yeast ARE part_of Eukaryota

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#19010]
in P2GO i'm trying to add 

GO:0090307 mitotic spindle assembly, and 
GO:0000022 mitotic spindle elongation

to TUB2, but i'm getting the error:

> Annotation failed taxon constraint GO:0000278 (mitotic cell cycle) and its descendants should ONLY be used with gene products from the taxonomic group Eukaryota

**Comment by balhoff** [comment]
I checked all three of these with S. cerevisiae with the reasoner in Protege and there is no error. Is it a problem at P2GO?

**Comment by pgaudet** [comment]
Maybe this was a temporary glitch ? That seems to work for me (see 'Deleted annotations' section in P2GO).

**Comment by srengel** [comment]
yes seems to have been a temporary issue.  thanks!
