### ISSUE TITLE
formation of penetration hyphae

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19014]
should "formation of penetration hyphae" this be related to 
"entry into host"

@CuzickA

**Comment by pgaudet** [comment]
part_of ?

**Comment by ValWood** [comment]
yep

**Comment by pgaudet** [comment]
I've added the relation to the parent 'GO:0075015 formation of infection structure on or near host' (part_of entry into host), so all children will inherit it: 

* 'appressorium formation'
* 'formation of symbiont germ tube hook structure for appressorium development'
* 'haustorium mother cell formation on or near host'
* 'haustorium neck formation'
* 'hyphopodium formation on or near host'
* 'infection cushion formation on or near host'
* 'penetration hypha formation'
* 'penetration peg formation'

I am also changing the term label of 'GO:0075015 formation of infection structure on or near host' 
to 'GO:0075015 formation of host infection structure'  

and the definition from "The process in which a symbiont structure that serves to infect the host is formed on or near its host organism. It includes physiological, developmental, and morphological changes of the symbiont. The host is defined as the larger of the organisms involved in a symbiotic interaction."

to "The process in which a symbiont structure that serves to infect the host is formed on its host organism. It includes physiological, developmental, and morphological changes of the symbiont. The host is defined as the larger of the organisms involved in a symbiotic interaction."


Thanks, Pascale
