### ISSUE TITLE
MP and other parentage issues effector-mediated terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19017]
<img width="339" alt="Screenshot 2020-03-02 at 16 58 04" src="https://user-images.githubusercontent.com/7359272/75698730-23e93000-5ca7-11ea-9428-c39c9f3c30fb.png">

I noticed that
GO:0140423    effector-mediated suppression of pattern-triggered immunity signaling

was not a child of
GO:0140418    effector-mediated modulation of host process by symbiont

and PTI is a host process. 

I think the issue is that 
GO:0140418    effector-mediated modulation of host process by symbiont

should be above
GO:0140415    effector-mediated modulation of host defenses by symbiont

I think  effectors can modulate host processes that are not immune system
(at least that was why we requested the term. However, the e.g., we were looking at today the  symbiont appeared to alter host photosynthesis, but it was really only doing this to reduce ROS production to damlp PTI... @CuzickA  do you have any other examples of  modulation of none immune processes by pathogen effectors?

**Comment by pgaudet** [comment]
> I think the issue is that
GO:0140418 effector-mediated modulation of host process by symbiont
should be above
GO:0140415 effector-mediated modulation of host defenses by symbiont

I think the reason it's like this is that host defenses are not necessarily processes.

**Comment by pgaudet** [comment]
It would have to be 'host defense response' for the parent to be changed, I think.

**Comment by ValWood** [comment]
OK in this case the missing parent is lower

GO:0140403   effector-mediated suppression of host innate immune response by symbiont
should be the parent of
O:0140423 effector-mediated suppression of pattern-triggered immunity signaling

**Comment by pgaudet** [comment]
This is done
