### ISSUE TITLE
txn in response to increased salt

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19012]
do we need

positive regulation of transcription from RNA polymerase II promoter in response to increased salt (GO:0061404)

and
positive regulation of transcription from RNA polymerase II promoter in response to salt stress (GO:0036251)

won't
positive regulation of transcription from RNA polymerase II promoter in response to osmotic stress (GO:0061393)

suffice?

If not I don't see why we need both  (GO:0061404) & (GO:0036251)
?

**Comment by pgaudet** [comment]
I thought we wanted to post-compose all those terms ?

**Comment by ValWood** [comment]
Oh yes, we are, so they will go anyway

**Comment by ValWood** [comment]
Should I close, if this will happen anyways

**Comment by ValWood** [comment]
I think this is done.
