### ISSUE TITLE
GO:0075061 invasive  hyphal growth

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19013]
Working with @CuzickA 

This is an odd term
GO:0075061 invasive  hyphal growth
Definition
The assembly by the symbiont of a threadlike, tubular structure, which may contain multiple nuclei and may or may not be divided internally by septa or cross-walls, for the purpose of invasive growth within its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

https://www.ebi.ac.uk/QuickGO/term/GO:0075061

We puzzled  for ages, and then realized we didn't require this term.

"Hyphal growth" is sufficient
Invasive hyphal growth is just  post penetration growth

We only required
GO:0075201   entry into host

(invasive growth can occur  after penetration the growth of hyphae post penetration)

This doesn't have any annotation. I can't see how it would be used for a  process annotation. Thoughts anyone?

**Comment by ValWood** [comment]
hyphal growth can occur on surface, or growing inside after pentration, so this is really

hyphal growth + location (within host cell)

**Comment by ValWood** [comment]
Although invasive filamentous growth is used quite a lot. Are these really viability assays though?

**Comment by ValWood** [comment]
We have asked our collaborators who are authors of the papers we were curating.

**Comment by krchristie** [comment]
> Although invasive filamentous growth is used quite a lot. Are these really viability assays though?

The assays for invasive filamentous growth in cerevisiae that I am familiar with are not viability assays. They are assays for invasion into the agar versus staying on the surface (and thus being easily washed off the agar surface) which is what cerevisiae growing in a "normal" budding mode do. If I remember correctly, invasive growth in cerevisiae is synonymous with filamentous growth (aka pseudohyphal growth for cerevisiae as it doesn't form true hyphae), as once the cells switch to the pseudohyphal growth pattern, they become capable of invading the agar.

**Comment by ValWood** [comment]
I think this term is probably used in different ways
i) growth mode
ii) viability in specific growth stage (for organisms which grow normally in filamentous form)

Or, maybe this isn't a problem and the filamentous branch is OK, and we only need to address the invasive branch. We need to look a the annotations.....

I'm always confused by these terms though...

**Comment by ValWood** [comment]
I think it would be OK to merge. If it is required we need to figure out why and define correctly. Sometimes these terms are talking about  "growth" during "particular lifestyle stage"

**Comment by pgaudet** [comment]
I'll obsolete the 'regulation terms' 
* GO:0075062 regulation of invasive hypha growth
* GO:0075064 negative regulation invasive hypha growth
* GO:0075063 positive regulation of invasive hypha growth 
(no annotations, no mappings, etc)

CC terms: 
* GO:0085039 'extra-invasive hyphal membrane
=> change label hyphal membrane
* GO:0062140 'septin collar of invasive hyphae
=> hyphae septin collar 
* GO:0085040 'extra-invasive hyphal space
= > obsolete

No annotations, no mappings, no subsets

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

GO:0075062 regulation of invasive hypha growth
GO:0075064 negative regulation invasive hypha growth
GO:0075063 positive regulation of invasive hypha growth
GO:0085040 'extra-invasive hyphal space

There are no annotations or mappings to those terms. Those terms are not in any subsets. 

The reason for obsoletion is that 'invasive hyphae' is no different from hyphae. 

Please add any comments to the ticket https://github.com/geneontology/go-ontology/issues/19013

Thanks, Pascale
