### ISSUE TITLE
MP negative regulation of transcription by transcription factor catabolism (GO:0010620)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19011]
negative regulation of transcription by transcription factor catabolism (GO:0010620)

This term is defined
Any process that stops, prevents, or reduces the frequency, rate or extent of DNA-dependent transcription using a mechanism that involves the catabolism of a sequence-specific DNA-binding transcription factor by hydrolysis of its peptide bonds, initiated by the covalent attachment of ubiquitin, and mediated by the proteasome.

therefore, the parent should be
GO:0000122    negative regulation of transcription by RNA polymerase II

instead of
negative regulation of transcription, DNA-templated

@pgaudet  needed for my Venn

**Comment by ukemi** [comment]
Have we restricted all transcription factors to Pol II?

**Comment by ValWood** [comment]
Ah no there is a "sequence-specific DNA-binding transcription factor" for Pol

Not to worry , I managed to include most of the relevant terms for my Venn. Can close this
