### ISSUE TITLE
Change label GO:0043903 regulation of symbiosis, encompassing mutualism through parasitism to regulation of interspecies interaction between organisms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19028]
GO:0043903 regulation of symbiosis, encompassing mutualism through parasitism
to regulation of interspecies interaction between organisms

This is required for #19027

@mgiglio99 Is that OK for you ? 

Thanks, Pascale

**Comment by ValWood** [comment]
In that case, would we need this parent?
https://www.ebi.ac.uk/QuickGO/term/GO:0044403
or will that merge into
interspecies interaction between organisms

**Comment by pgaudet** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0044403 'symbiotic process' 

could also probably be merged - this term is confusing, maybe doing away with it completely would be best ?

**Comment by ValWood** [comment]
Yes and it would seem really odd to have

interspecies interaction between organisms
--symbiotic process
----regulation of  interspecies interaction between organisms

which is what we would get with the changed regulation term

**Comment by mgiglio99** [comment]
Hi,
Please don't do anything on this one yet. I'm totally swamped for the next few days. But I will look at this over the weekend. Is that ok?
Thanks,
Michelle

**Comment by mgiglio99** [comment]
It looks like you already made this change.
(I know I said I'd get to it and that was two months ago so I can't complain.)
My suggestion was going to have been to take GO:0043903 'regulation of symbiosis, encompassing mutualism through parasitism' and change its label to 'regulation of symbiotic process' - then its parentage would have been fine.

(An aside - it appears the regulation terms don't show up as children of the terms they regulate in OLS - or am I doing something wrong - what I need to be doing is using protege)

I glean that the remaining question is whether to get rid of 'symbiotic process'. I think we should keep it as it separates that kind of intimate relationship from things like predation. Or the rejecting of pollen from other species. But one could argue that maybe we don't need grouping terms to differentiate that. But I think it's helpful.

If we keep it,  I see that several of the terms that are children of 'interspecies interaction between organisms' should be children of 'symbiotic process' - for example: 'interaction with symbiont'.

**Comment by mgiglio99** [comment]
Discussion with @pgaudet @ValWood @mgiglio99 @nsuvarnaiari @dsiegele 

1. We decided to keep 'symbiotic process' for now
2. We will rename GO:0043903 'regulation of interspecies interaction between organisms' (which is actually a new name - it was previously 'regulation of symbiosis, encompassing....') to 'regulation of symbiotic process' - (this will also remove the parentage problem)
3. Several of the children of 'interspecies interaction between organisms' should actually be children of 'symbiotic process' - we will work on these next
4. 'pathogenesis' - this term has been problematic for a long time. We decided to merge it into 'symbiotic process' and ask annotators to review all annotations to Metazoa. Suggestions of where to move the metazoan annotations are: 'interspecies interaction between organisms',  'killing of cells of another organism', 'toxin activity'. Referenced here: https://github.com/geneontology/go-ontology/issues/11057
5. We don't like the 'response to other organism' branch and want to do something about it.

**Comment by pgaudet** [comment]
OK so the only actionable item here is  # 2. I am doing this and closing. 

Thanks, Pascale

**Comment by mgiglio99** [comment]
Will we make new tickets for 3 and 5?

**Comment by pgaudet** [comment]
> Will we make new tickets for 3 and 5?

Now done ! Thanks for the reminder

https://github.com/geneontology/go-ontology/issues/19430
https://github.com/geneontology/go-ontology/issues/19431
