### ISSUE TITLE
Obsolete 'GO:0005623 cell'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19036]
Hello, 

Related to #17696 and #17778 - we had mentioned that we should obsolete 'cell' from GO, and use CL:0000000 cell if needed. 

There are few logical definitions using "cell" : 
- auxin influx
- auxin influx transmembrane transporter activity
- cell maturation
- cell morphogenesis
- cellular detoxification of methylglyoxal
- cellular homeostasis
- establishment of localization in cell
- extracellular matrix
- maintenance of protein localization in cell
- phenylacetyl-CoA 1,2-epoxidase complex

Disjoint classes:
- organelle
- protein-containing complexes
- symplast
- virion

----

**Comment by addiehl** [comment]
I am in favor of obsoleting GO:cell.
Alex

**Comment by nicolevasilevsky** [comment]
I am also in favor of obsoleting GO:cell and using CL:cell

**Comment by pgaudet** [comment]
First edit: Change the use of GO:0005623 ! cell in the ontology to CL:0000000 ! cell

This impacts the following terms: 
* GO:0048469 cell maturation 
* GO:0051649 establishment of localization in cell
* GO:0140041 cellular detoxification of methylglyoxal
* GO:0000902 cell morphogenesis
* GO:0019725 cellular homeostasis
* GO:0032507 maintenance of protein location in cell


----

Removed 'part of cell' for complexes: 
 - GO:0062077 phenylacetyl-CoA 1,2-epoxidase complex

Thanks, Pascale

**Comment by pgaudet** [comment]
id: GO:0010328
name: auxin influx transmembrane transporter activity
is_a: GO:0080161 ! auxin transmembrane transporter activity
intersection_of: GO:0080161 ! auxin transmembrane transporter activity
intersection_of: has_target_end_location GO:0005623 ! cell
relationship: part_of GO:0060919 ! auxin influx

-> all annotations are to transmembrane transporters. I will change the logical definition to 
'auxin transmembrane transporter activity'
 and ('results in transport across' some membrane)

(if I add start and end locations the LD will be the same a the BP logical definition)


id: GO:0060919
name: auxin influx
is_a: GO:0060918 ! auxin transport
intersection_of: GO:0060918 ! auxin transport
intersection_of: has_target_end_location GO:0005623 ! cell
intersection_of: has_target_start_location GO:0005576 ! extracellular region


-> all annotations are to transmembrane transporters. I will change the logical definition to 
'auxin transport'
 and ('has target start location' some 'extracellular region')
 and ('has target end location' some cytoplasm)
and ('results in transport across' some membrane)


To be consistent, also changed:
GO:0010315 auxin efflux
to 
'auxin transport'
 and ('has target end location' some 'extracellular region')
 and ('has target start location' some cytoplasm)
and ('results in transport across' some membrane)

**Comment by pgaudet** [comment]
@tberardini 

For other transporters I have merged 'influx'/'efflux' in the MF branch, and kept those  in the BO branch only. 

Would you be OK with merging those: 

'auxin transmembrane transporter activity'
'auxin efflux transmembrane transporter activity'
'auxin influx transmembrane transporter activity'

Thanks, Pascale

**Comment by balhoff** [comment]
There is discussion currently happening on the CL mailing list suggesting that CL:cell applies only to Metazoa. I think this should be resolved before GO makes this change.

**Comment by ukemi** [comment]
I think we also need to investigate how this will effect products like go-basic.obo. But in principle I think it would be nice to get rid of what amounts to 'duplicate' classes in different ontologies.

**Comment by tberardini** [comment]
> For other transporters I have merged 'influx'/'efflux' in the MF branch, and kept those in the BO branch only.

Why?  Was this discussed in another ticket that I missed (entirely possible).  Isn't the directionality of transport important to capture in MF?  There are specific proteins that transport in one direction vs the other (and not interchangeably).  Is that too specific a detail of mechanism to have in GO?

The BP branch?  (not BO?)

>Would you be OK with merging those:

'auxin transmembrane transporter activity'
'auxin efflux transmembrane transporter activity'
'auxin influx transmembrane transporter activity'

Not without further discussion.

**Comment by pgaudet** [comment]
Weird that cells would only apply to metazoa ! I guess that means CL only applies to metazoa, right ? So they would get rid of terms like 'prokaryotic cell' ? 

Thanks, Pascale

**Comment by addiehl** [comment]
No, the root term 'cell' applies to all cells from any organism, prokaryotic or eukaryotic.  Curation of cell types in the Cell Ontology has mostly focused on eukaryotic, and particularly vertebrate, cell types, with other communities, PO, FBBT, etc. developing cell type classes specific for particular domains.

**Comment by balhoff** [comment]
Thanks for clarifying, @addiehl. I might have misunderstood @cmungall's email comment. Maybe he was suggesting that subclasses of CL:cell outside of Metazoa would be curated in Dicty, PO, etc., but I will try not to put words in his mouth.

**Comment by ukemi** [comment]
The description on the obo foundry is:
The Cell Ontology is a structured controlled vocabulary for cell types in animals.

**Comment by pgaudet** [comment]
Well this is inconsistent with the actual entities in the ontology. @addiehl are you the person who deals with this ?

**Comment by addiehl** [comment]
The challenge is that the Cell Ontology was created initially to cover cell types from all of biology, and the root term cell is defined and intended to be applicable across all biology.  But for practical reasons, PO took over the plant cells in a modular way that still can link back to 'cell', and other communities similarly curate specialized cells for their organisms.  What get curated in CL is primarily vertebrate, with a focus on mammals and human.  So CL is both an umbrella ontology for all cells, including cells in vitro, in providing high level terms to link cell type modules to, and the default ontology for vertebrate cell types, and probably should be described this way.

I will discuss how we can better clarify this during the March 25 CL call (11 am ET, https://zoom.us/j/4056642234), so that the description of the Cell Ontology and its role as the umbrella ontology for cell types is clear.

**Comment by ukemi** [comment]
Thanks @addiehl. Although I agree that a single class would be best, I hope you can see why I am strongly encouraging caution.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to replace `GO:0005623 cell`  with `CL_0000000 cell` from the Cell Type ontology. 

There are currently no more terms in the ontology using `GO:0005623 cell`. We plan to implement this change in two weeks, on April 17, 2020.
Please let us know if you need more time to adjust your parsers or tools. 

Thanks, Pascale

**Comment by cmungall** [comment]
> I might have misunderstood @cmungall's email comment. Maybe he was suggesting that subclasses of CL:cell outside of Metazoa would be curated in Dicty, PO, etc., but I will try not to put words in his mouth

This is exactly what I was suggesting!
