### ISSUE TITLE
"polynucleotide 5'-hydroxyl-kinase activity" EC xref edits

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19048]
EC:2.7.1.- (https://enzyme.expasy.org/EC/2.7.1.-) is for all 'Phosphotransferases with an alcohol group as acceptor'
EC:2.7.1.78 (https://enzyme.expasy.org/EC/2.7.1.78) is for ATP-dependent Polynucleotide 5'-hydroxyl-kinase.

Therefore, the following edits in the GO are needed:

1. polynucleotide 5'-hydroxyl-kinase activity (GO:0051731)
- Remove partial EC xref of "2.7.1" and remove references to EC:2.7.1.78 from def & synonyms

2. GTP-dependent polynucleotide kinase activity (GO:0051735)
- Remove EC:2.7.1.78 from def

3. polyribonucleotide kinase activity (GO:0051732) & polydeoxyribonucleotide kinase activity (GO:0051733)
- Not sure if correct or not to keep references to EC:2.7.1.78 in def & synonyms??

4. ATP-dependent polynucleotide kinase activity (GO:0051734)
- this one looks good! :-)

**Comment by sjm41** [comment]
Hi @hdrabkin - Just checking you saw this one?

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Great, thanks!
