### ISSUE TITLE
MF in BP ontology DNA damage response, detection of DNA damage (GO:0042769)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19051]
This is a molecular function:
GO:0042769 DNA damage response, detection of DNA damage 
Definition	Parents
The series of events required to receive a stimulus indicating DNA damage has occurred and convert it to a molecular signal.

AND
GO:0072421 detection of DNA damage stimulus involved in DNA damage checkpoint
The series of events in which information about damage to DNA is received and converted into a molecular signal, contributing to a DNA damage checkpoint.

Can we obsolete and create new MF terms to describe "DNA damage sensor"

NTR: DNA damage sensor activity
A molecule that recognises toxic DNA structures, for example, double-strand breaks or collapsed replication forks, and initiates a signalling response.
(we might need a grouping term under 'small molecule sensor' activity.)

Here is an example in a recent paper that might serve as a good reference;
SIRT6. PMID:31995034
https://elifesciences.org/articles/51636
There are three confirmed sensors for double-strand break in human cells. A fourth protein, known as SIRT6, arrives within five seconds of DNA damage, and was known to make the DNA more accessible so that it can be repaired. However, it was unclear whether SIRT6 could detect the double-strand break itself, or whether it was recruited to the damage by another double-strand break sensor.
....Until now, very few DSB sensors have been identified, among them poly ADP-ribose polymerase-1 (PARP1), the MRN complex (MRE11, RAD50, NBS1) and Ku70/80 complex. All of these sensors initiate downstream signaling cascades which usually lead to the activation of specific repair pathways, such as homologous recombination (HR) or classical non-homologous end joining (C-NHEJ) (Andres et al., 2015; Sung et al., 2014; Woods et al., 2015). 

(not that this is not  the paper I am curating)

**Comment by ValWood** [comment]
Also
GO:0000715 nucleotide-excision repair, DNA damage recognition (31,000 annotation 11 EXP)
The identification of lesions in DNA, such as pyrimidine-dimers, intrastrand cross-links, and bulky adducts. The wide range of substrate specificity suggests the repair complex recognizes distortions in the DNA helix. PMID:10197977


seems to be describing sensors?
Although I am not sure that all 11 annotations are to sensors

**Comment by ValWood** [comment]
The paper I was curating/approving
PMID: 24663817
has
At the apex of the two checkpoint pathways, Rad3-Rad26, Rad9-Rad1-Hus1 (9-1-1 clamp), and Rad17 (9-1-1 clamp loader) function as checkpoint sensors (see reviews [13,14,15]). The sensors detect perturbed forks (single-stranded DNA) or various other types of DNA damage and work in collaboration to activate the effector kinases Cds1 and Chk1 via the mediators Mrc1 [16,17] and Crb2 [18], respectively.


in the intro.

**Comment by pgaudet** [comment]
@ValWood 
I guess the obsoletion would also apply to children 
'detection of DNA damage stimulus involved in DNA damage checkpoint'
'detection of DNA damage stimulus involved in G2 DNA damage checkpoint'
'detection of DNA damage stimulus involved in intra-S DNA damage checkpoint'
'detection of DNA damage stimulus involved in mitotic G1 DNA damage checkpoint'
'detection of DNA damage stimulus involved in mitotic G2 DNA damage checkpoint'
'detection of stimulus involved in DNA replication checkpoint'
'detection of stimulus involved in meiotic DNA replication checkpoint'
'detection of stimulus involved in mitotic DNA replication checkpoint'

?

**Comment by ValWood** [comment]
Yes, I think these should all be captured as "sensors"
A nice simplification in this branch.

**Comment by ValWood** [comment]
@pgaudet  this should be covered by the current changes, but we need the new term requested here "DNA damage sensor" to reannotate.
There are only 23 EXP annotations but the term has also been inconsistently used and most do not appear to be damage sensors.

**Comment by ValWood** [comment]
Hi Pascale,

could you add the new MF requested here
NTR: DNA damage sensor activity
A molecule that recognises toxic DNA structures, for example, double-strand breaks or collapsed replication forks, and initiates a signalling response.
(we might need a grouping term under 'small molecule sensor' activity.)

This term will be required for people to reannotate the gene products annotated to  "detection"  which are really sensing the DNA damage directly.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140612
+name: DNA damage sensor activity
+namespace: molecular_function
+def: "A molecule that recognises toxic DNA structures, for example, double-strand breaks or collapsed replication forks, and initiates a signalling response." [PMID:31995034]
+intersection_of: GO:0140299 ! small molecule sensor activity
+intersection_of: has_part GO:0003684 ! damaged DNA binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19051 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-03T18:11:17Z
+

**Comment by pgaudet** [comment]
annotations for DNA damage response, detection of DNA damage (GO:0042769) 

https://docs.google.com/spreadsheets/d/1JcTxvjDIEoXpSKtEgPN1lEc8UObdh1lnvl-bqHoV2HA/edit#gid=0

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0042769 DNA damage response, detection of DNA damage. The reason for obsoletion is that this corresponds to a molecular function (GO:0140612 DNA damage sensor activity). There are EXP 32 annotations to this term (some of which are already fixed, see https://github.com/geneontology/go-annotation/issues/3917). 

There are no mappings to this term; this term is not present in any subsets. 

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/19051
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Sept 15, 2021. Unless objections are received by Sept 15, we will assume that you agree to this change.
 
Thanks, Pascale
