### ISSUE TITLE
merge and small def update NURS complex/MTREC

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19059]
GO:1990477   NURS complex
Definition (GO:1990477 GONUTS page)
The nuclear RNA silencing (NURS) complex is a protein complex formed by  AN RNA BINDING PROTEIN Red1, AN RNA HELICASE Mtl1, Red5, Rmn1, Iss10/Pir1, and Ars2/Pir2 that ~regulates RNA degradation and histone H3 lysine 9 methylation~ *** ADD is required for the recruitment of the nuclear exosome to Mmi1 nuclear focus ***. It is likely related to the human CBCN complex. PMID:24713849

+ PMID:32012158

merge 
GO:1990345   MTREC complex (same thing)

+ PMID:32012158
These data indicate that the primary function of MTREC/NURS in meiotic transcript elimination is to link Mmi1 to the nuclear exosome physically.

**Comment by pgaudet** [comment]
Are the following relations correct ? 

'capable of part of' some 'histone H3-K9 methylation'
'capable of part of' some 'RNA catabolic process'

Thanks, Pascale

**Comment by pgaudet** [comment]
@bmeldal

**Comment by ValWood** [comment]
It isn't a methyltransferase - it might affect  'histone H3-K9 methylation' but it isn't the activity of the compex , it is indirect so I would not include this,.  It's role in methylation appears to be due to the control of some lncRNA trancripts involved in  somehow in facultative heterochromatin assembly

It's primary function appears to be to recriuit  the nuclear exosome to YTH-RNA- binding protein Mmi1. I would just say that, or  "RNA surveillance" (which it does this as part of)

**Comment by bmeldal** [comment]
Doesn't look like we have an instance of this complex so I'd go with what Val says!
