### ISSUE TITLE
TPV signalling adaptor activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19050]
signalling adaptor activity
has the parents
GO:0009967    positive regulation of signal transduction
GO:0023056    positive regulation of signaling
and

The scaffold I am annotating are not  necessarily "regulators" of signal transduction.
(they are part_of the signalling pathway, required for signalling but not necessarily _controlling_ the rate)

**Comment by pgaudet** [comment]
Right this should not be there, see also https://github.com/geneontology/go-ontology/issues/15509#issuecomment-471166184
