### ISSUE TITLE
Problem in goa_uniprot_all.gaf 

### ISSUE THREAD

**Issue by davidbio** [geneontology/go-ontology#19065]
I hope this is the right place to report this.

The following file shows a problem:
ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz

The taxon field in line 424083621 is invalid:
```bash
UniProtKB     A0A3D9LV76      CLW06_2627              GO:0016798      GO_REF:0000043  IEA     UniProtKB-KW:KW-0326    F       Endoglycosylceramidase  CLW06_2627      protein taxon:1827A0A2K5HFP6    CLDN8           GO:0030
054     GO_REF:0000043  IEA     UniProtKB-KW:KW-0965    C       Claudin CLDN8   protein taxon:336983    20200222        UniProt
```
**taxon:1827A0A2K5HFP6**

Probably a file merge went wrong, I don't know if more lines are missing or affected.

**Comment by pgaudet** [comment]
@alexsign 

@kltm also found those oddities in the 'Assigned by' column: 

   1 PAS domain S-box-containing protein
      1 protein
      2 20200222
      6 DIBU

Thanks, Pascale

**Comment by alexsign** [comment]
@davidbio it looks like there was an issue with the EBI filesystem when the gaf file was created. Because it, part of file disappeared and some rows got merged. I will try to recreate and rerelease the file and let you know when it's ready. My apologies for the inconvenience,
Alex

**Comment by davidbio** [comment]
@alexsign thank you for looking into this, I'll wait for the update.

**Comment by ukemi** [comment]
@pgaudet 
I'm assigning this to you as a monitor. You can close when they problem is resolved.

**Comment by alexsign** [comment]
@davidbio ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz is fixed now

**Comment by davidbio** [comment]
@alexsign I processed the file successfully and did not find any problem.
Thank you all.

**Comment by ValWood** [comment]
Done, closing
