### ISSUE TITLE
refine def, change name Mmi1 nuclear focus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19063]
rename
GO:1990251    JSON
Mmi1 nuclear focus
Definition (GO:1990251 GONUTS page)
A protein complex that forms during vegetative growth and is involved in **NUCLEAR MRNA SURVEILLANCE*** ~the selective degradation of meiosis-specific transcripts~. Contains at least Mmi1, or an ortholog of it AND THE EXOSOME. PMID:16823445 PMID:23980030

nuclear exosome focus
make 
MMi1 nuclear focus a synonym

**Comment by ValWood** [comment]
also obsolete
GO:1902666    protein localization to Mmi1 nuclear focus complex

(these are just phenotypes, it isn't clear that this doesn't occur autonomously)

**Comment by ValWood** [comment]
Actually we could rename this 
"GO:1902666 exosome focus formation"
some proteins appear to be key to this.

**Comment by ValWood** [comment]
deleted the previous comment.

this paper calls
the focus
nuclear exosome focus

Meiotic gene silencing complex MTREC/NURS recruits the nuclear exosome to YTH-RNA-binding protein Mmi1.
PMID: 32012158

and I think this name is more "generic" than an obscure pombe gene name.

**Comment by pgaudet** [comment]
@ValWood I dont understand how the complex contains the exosome - the exosome is an entire vesicle - can you please check ?

**Comment by pgaudet** [comment]
Ohhh ! OK it's one of those: 

'exosome (RNase complex)' <http://purl.obolibrary.org/obo/GO_0000178>
'nuclear exosome (RNase complex)' <http://purl.obolibrary.org/obo/GO_0000176>
'nuclear exosome targeting complex' <http://purl.obolibrary.org/obo/GO_0062141>
'nucleolar exosome (RNase complex)' <http://purl.obolibrary.org/obo/GO_0101019>
'cytoplasmic exosome (RNase complex)' <http://purl.obolibrary.org/obo/GO_0000177>

**Comment by pgaudet** [comment]
PMID:32012158 suggest that Mmi1 is not *part_of* the complex, it just binds to it.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:1902666 protein localization to Mmi1 nuclear focus complex'. The reason for obsoletion is that there is no evidence that this process exists (no factor mediates the localization of proteins to Mmi1 nuclear foci). 

There are no annotations or mappings to this term; this term is not in any subsets. 

Comments should be added to the ticket:
geneontology/go-ontology#19063

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 16th, 2020. Unless objections are received by March 16th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by ValWood** [comment]
nuclear exosome (RNase complex)
(note, this is specifically the nuclear exosome, cytoplasmic and nuclear exosome have different compositions)

**Comment by ValWood** [comment]
>PMID:32012158 suggest that Mmi1 is not part_of the complex, it just binds to it.

mmi1 isn't part of the 'exosome complex' but it's part of the 'exosome foci'.  This foci is where all of the surveillance machinery and the sequestered RNAs live.

**Comment by ValWood** [comment]
ok you figured that!
