### ISSUE TITLE
Merge GO:0052917 & GO:0052824?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19075]
Related to #16022:

These two terms *appear* to be the same - merge?

**dol-P-Man:Man(7)GlcNAc(2)-PP-Dol alpha-1,6-mannosyltransferase activity (GO:0052917)**

7 annotations (all to ALG12 orthologs)

Def:
Catalysis of the reaction: alpha-D-man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-(alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-alpha-D-Man-(1->6))-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-D-GlcNAc-diphosphodolichol + dolichyl D-mannosyl phosphate = H(+) + alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-(alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-(alpha-D-Man-(1->6))-alpha-D-Man-(1->6))-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-D-GlcNAc-diphosphodolichol + dolichyl phosphate.

Synonyms:
dolichyl-P-mannose:Man(7)GlcNAc(2)-PP-dolichyl mannosyltransferase activity | exact
dolichyl-P-Man:Man(7)GlcNAc(2)-PP-dolichyl alpha-6-mannosyltransferase activity

Xrefs:
EC | 2.4.1.260
KEGG_REACTION | R06260 |  
MetaCyc | RXN-5468 |  
RHEA | 29535

==
**dolichyl-pyrophosphate Man7GlcNAc2 alpha-1,6-mannosyltransferase activity (GO:0052824)**

2,331 annotations (seemingly to ALG12 orthologs)

Def:
Catalysis of the addition of mannose to dolichyl-pyrophosphate Man7GlcNAc2 (also written as Man7GlcNAc2-PP-Dol) in alpha-(1->6) linkage, producing Man8GlcNAc2-PP-Dol. PMID:10336995

Xrefs:
InterPro | IPR039485 | Dol-P-Man:Man(7)GlcNAc(2)-PP-Dol alpha-1,6-mannosyltransferase

And IPR039485 says:
"N-linked glycosylation in eukaryotes requires the assembly of lipid-linked oligosaccharide (LLO) precursor Glc3Man9GlcNAc2-pyrophosphate-dolichol (Glc3Man9Gn2-PDol). Addition of sugars to LLO is carried out sequentially by a serie of asparagine-linked glycosylation (Alg) glycosyltransferases [1]. ALG12 adds the eighth mannose residue in an alpha-1,6 linkage onto the dolichol-PP-oligosaccharide precursor (dolichol-PP-Man7GlcNAc2). Deficiency of ALG12 results in glycosylation disorder type lG"

**Comment by pgaudet** [comment]
That seems right. 

And GO:0033164 glycolipid 6-alpha-mannosyltransferase activity
should be renamed glycolipid 1,6-alpha-mannosyltransferase activity to be more consistent with its parent alpha-1,6-mannosyltransferase activity. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thoughts on this one @hdrabkin ?

**Comment by pgaudet** [comment]
Merged the two terms as requested.

**Comment by pgaudet** [comment]
@sjm41 What do you think about 

GO:0000009 alpha-1,6-mannosyltransferase activity
and   GO:0033164 glycolipid 6-alpha-mannosyltransferase activity 

They link to the same EC, EC:2.4.1.232

- Most annotations are to GO:0000009 (17 EXP)
- There are 5 EXP annotations to GO:0033164, 4 of which are to pimB/pimC (P9WMZ3 for example). PimB is linked to EC 2.4.1.346 and RHEA:52440, which we dont have in GO, we should probably create. 
- PimC has no EC  or RHEA link
- InterPro IPR007315 links to both 
    alpha-1,6-mannosyltransferase activity (GO:0000009)
    glycolipid mannosyltransferase activity (GO:0004376)
(is this right ?) 

Thanks, Pascale

**Comment by sjm41** [comment]
Seems GO:0033164 is more specific in that it specifies the substrate?  But the enzymatic activity appears to be the same as GO:0000009, as supported by the shared EC xref and the EC synonyms (https://enzyme.expasy.org/EC/2.4.1.232).  I don't think GO want MF terms that specify substrates, right? In that case, these two terms could be merged IMO.

(Doesn't look like there's a Rhea ID for 2.4.1.232.)

**Comment by sjm41** [comment]
Hi @pgaudet 
I just ran into this issue again, which we didn't finalise back in 2020.

Looking at the ontology now, I see 'alpha-1,6-mannosyltransferase activity' is the parent of two terms:

alpha-1,6-mannosyltransferase activity (xref EC:2.4.1.232)
           |__dolichyl-P-Man:Man(7)GlcNAc(2)-PP-dolichol alpha-1,6-mannosyltransferase (xref EC:2.4.1.260)
           |__glycolipid 1,6-alpha-mannosyltransferase activity (xref EC:2.4.1.232)

So 'alpha-1,6-mannosyltransferase activity' is a grouping term in the GO, with the def "Catalysis of the transfer of a mannose residue to an oligosaccharide, forming an alpha-(1->6) linkage."

That def doesn't match the EC:2.4.1.232, which is more specific, matching the other term (glycolipid 1,6-alpha-mannosyltransferase activity)

So I think the simplest (best?) thing to do now would be to keep both terms, but remove the EC number as an xref and in definition of alpha-1,6-mannosyltransferase activity (GO:0000009)

what do you say?

**Comment by sjm41** [comment]
@pgaudet Reviewing the above, I think the only thing left to do on this ticket is to remove EC:2.4.1.232 as an xref on the grouping term "alpha-1,6-mannosyltransferase activity (GO:0000009)", retaining that xref on the child term "glycolipid 1,6-alpha-mannosyltransferase activity (GO:0033164)".
Then we can close this.

**Comment by pgaudet** [comment]
thanks for the reminder!
