### ISSUE TITLE
MP GO:0140433    regulation of protein localization to meiotic spindle pole body

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19079]
GO:0140433    regulation of protein localization to meiotic spindle pole body

should be a descendant of

GO:0071988 | protein localization to spindle pole body

**Comment by ukemi** [comment]
Yup. There is an error in the logical definition. 
It should be:
'biological regulation'
 and (regulates some 'protein localization to meiotic spindle pole body')
not
'biological regulation'
 and (regulates some 'protein localization to meiotic spindle')
