### ISSUE TITLE
NTR G protein activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19082]
For the Molecular refactoring @thomaspd proposes to create the term "G protein activity" to represent small GTPases.  

PMID:27218782

Proposed definition: 
A GTPase activity, typically accomplished by a low molecular weight protein, that alternates between two basic states, an inactive GDP-bound, and an active, GTP-bound. This transition is facilitated by guanine nucleotide exchange factors (GEFs) that eject GDP from Ras-GDP, thus activating the G protein. GTPase activating proteins (GAPs) stimulate GTP hydrolysis, thus converting the protein fback to its inactive state.

Logical definition could be: 
'GTPase activity' 
and 'positively regulated by' some 'guanyl-nucleotide exchange factor activity' 
and 'negatively regulated by'some 'GTPase activator activity')

Synonyms: 
* small GTPase  (EXACT)
* small G-protein  (EXACT)
* Ras superfamily protein  (NARROW)

**Comment by mah11** [comment]
> ... proposes to create the term "G protein activity" to represent small GTPases.

WHAT?!? Those don't match - the heterotrimeric (aka "large") G proteins were called that before the small GTPases were even discovered.

If the name and intended scope matched, that would help a bit, but I would still be very concerned about the "typically accomplished by a low molecular weight protein" part of the definition. That describes a physical characteristic of a gene product, not any aspect of the enabled activity.

**Comment by pgaudet** [comment]
So - Should I create
- G protein activity for large GTPases (heterotrimetric G proteins) 
and 
- small GTPase activity for Ras-like ? 

This is what I understand from https://en.wikipedia.org/wiki/G_protein

Thanks, Pascale

**Comment by mah11** [comment]
Well, it would be best to get input from someone who knows this area better than I do, but my dim recollection is that "G protein" can now refer to *either* the small monomeric GTPases (ras, rho, etc.) or the large heterotrimeric ones. The introduction to that Wikipedia page seems to confirm this. So I don't favor using "G protein activity" without any additional modifier as a GO MF term name for either large or small GTPases.

(Tangent: I also still don't see the difference in *activity* ... it's GTP hydrolysis for both. "Large" and "small" are not features of activities. But if the current thinking is that MF can have additional axes of classification besides activity, I won't choose that hill to die on.)

**Comment by ValWood** [comment]
Close? What is the issue with the existing terms?

**Comment by pgaudet** [comment]
The idea was to distinguish small GTPases and heterotrimeric GTPase (note that this term used to exist: GO:0003927 obsolete heterotrimeric G-protein GTPase activity - and obsoleted because it represented a cellular component)

#1619

**Comment by pgaudet** [comment]
@thomaspd

**Comment by ValWood** [comment]
Isn't the only difference that the  heterotrimeric GTPase is a complex with other subunits, but the alpha subunit is the GTPase, the beta subunit is a scaffold and I don't know what the gamma subunit does exactly but is some sort of regulator..... so it's really no different than other multi-meric GTPase complexes.

For example the septation initiation signalling complex,
![sin](https://user-images.githubusercontent.com/7359272/107425969-913c4c80-6b17-11eb-8d79-2f427f99dd86.jpg)
has a GTPase (Spg1) on a scaffold (Cdc11) but we just call Spg1 a GTPase?

**Comment by pgaudet** [comment]
The purpose of this ticket was to create a term to allow annotating those G-proteins to something more specific than just 'GTPase activity'. This is what we currently have under GTPases: 

- 'GTPase activity'
- - 'GTPase motor activity'
- - 'membrane scission GTPase motor activity'


Thanks, Pascale

**Comment by ValWood** [comment]
signalling GTPase?

**Comment by ValWood** [comment]
or "signal transducer GTPase", would cover all, not just heterotrimeric G-proteins (most signalling GTPases aren't  G-proteins.

(I'm sure that we use to have a MF term "signal transducer" once but I could not find it recently).

**Comment by pgaudet** [comment]
well we have 'GO:0060089' molecular transducer activity

**Comment by ValWood** [comment]
Yes "signal transducer" was obsoleted - should it be some sort of synonym of "molecular transducer activity"

**Comment by pgaudet** [comment]
On the go-tickets jamboree, with @thomaspd @vanaukenk @raymond91125 
we restored 


 id: GO:0003925
-name: obsolete small monomeric GTPase activity
+name: small monomeric G protein activity
+def: "Small GTPase which cycles between active GTP-bound and inactive GDP-bound states. In its active state, binds to a variety of effector proteins to regulate cellular processes. They are involved in cell-growth regulation (RAS subfamily), membrane vesicle traffic and uncoating (RAB and ARF subfamilies), nuclear protein import (RAN subfamily) and organization of the cytoskeleton (Rho and Rac subfamilies). Intrinsic GTPase activity returns the large G protein to its GDP-bound state." [GOC:mah]


and 

 id: GO:0003927
-name: obsolete heterotrimeric G-protein GTPase activity
+name: large G-protein activity
+def: "Large GTPase which cycles between active GTP-bound and inactive GDP-bound states. In its inactive state, binds to a G protein-coupled receptor and the beta and gamma subunit of the heterotrimeric G protein. When the receptor is activated by its ligand, it exchanges GDP for GTP. In its GTP-bound state, the alpha subunit releases from the receptor and the beta and gamma subunits, and binds to and activates downstream targets. Common targets include adenylate cyclase and/or potassium ion and calcium ion channels. Intrinsic GTPase activity returns the large G protein to its GDP-bound state. Note that some large GTPases function in a receptor-independent manner." [PMID:22511245, PMID:33011291]

Thanks, Pascale

**Comment by ValWood** [comment]
This seems odd. The size or oligomerization status isn't an aspect of the molecular function?

Are you sure - we would need to reannotate to these terms (we already removed these annotations for the obsoletion, there are a lot of GTPases)

**Comment by pgaudet** [comment]
This is what we agreed on at the ontology tickets jamboree yesterday. We can certainly rediscuss. Please join today or tomorrow starting at 4PM UK - call in info is on the GO calendar. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Proposal from @ValWood : merge those 2 terms - since there is no distinction between the 2 functions - they are both MF regulators. To discuss with @thomaspd

**Comment by pgaudet** [comment]
Merged the two G protein terms (small and large) - def: 

A molecular function regulator that cycles between active GTP-bound and inactive GDP-bound states. In its active state, binds to a variety of effector proteins to regulate cellular processes. Intrinsic GTPase activity returns the G protein to its GDP-bound state. The return to the GDP-bound state can be accelerated by the action of a GTPase-activating protein (GAP).

**Comment by hattrill** [comment]
tagging @sjm41

**Comment by hattrill** [comment]
Hi @pgaudet 
I am just reopenning this one for a quick fix  - could we add small GTPase activity as a synonym (broad?) as I found it hard to find this term without help from Paul!

**Comment by pgaudet** [comment]
Added synonyms 
+synonym: "Ras superfamily protein" NARROW []
 synonym: "signaling G protein activity" EXACT []
+synonym: "small G-protein" NARROW []
+synonym: "small GTPase" NARROW []
+synonym: "small GTPase activity" NARROW []
