### ISSUE TITLE
Changes to GO:0099115 chromosome, subtelomeric region

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19086]
Discussing with @ValWood @RLovering @colinlog 

 - [x] GO:0099115 chromosome, subtelomeric region-> change definition 
OLD A heterochromatic region of the chromosome, adjacent to the telomere (on the centromeric side) that contains repetitive DNA and sometimes genes. 
NEW A region of the chromosome, adjacent to the telomere (on the centromeric side) that contains repetitive DNA and sometimes genes. This region is usually heterochromatin.

2. ~Merge
'subtelomeric heterochromatin'
'nuclear subtelomeric heterochromatin'~

- add parent: GO:0099115 chromosome, subtelomeric region

**Comment by RLovering** [comment]
Note comment from Telomere expert:
Yes I would define telomeric region/telomeric DNA as the region of uninterrupted telomeric DNA repeats (ie. TTAGGG in vertebrates).
 
Basically I agree with almost all highlighted text below, with possible exception of including the phrase ‘heterochromatic region’ in the definition of subtelomeric region – as this could imply that expression of all genes in these regions is permanently supressed?

**Comment by pgaudet** [comment]
Need to obsolete: 
*  GO:0005724  nuclear telomeric heterochromatin  - 27 EXP 
*   GO:0031933  telomeric heterochromatin - 5 EXP 


Has been inconsistently used. Should annotate to either: 
*  GO:0000781 chromosome, telomeric region 
*  GO:1990421  subtelomeric heterochromatin

I will open an annotation review ticket. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0005724 nuclear telomeric heterochromatin - 27 EXP
* GO:0031933 telomeric heterochromatin - 5 EXP

The reason for obsoletion is that there is no heterochromatin at the telomere. Annotations should be reviewed from this ticket: https://github.com/geneontology/go-annotation/issues/2883

There are no mappings to those terms; those terms are not present in any subsets. 

You can add any comments to the ticket: 
https://github.com/geneontology/go-ontology/issues/19086

We are opening a comment period for this proposed obsoletion. Since there are some annotations we’d like to propose to obsolete this term on March 31st, 2020. Unless objections are received by March 31st, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
See discussion on the annotation ticket https://github.com/geneontology/go-annotation/issues/2883

Call with @colinlog @ValWood @RLovering 

Decision is NOT to obsolete, and change the structure on the ontology 
Now: 
GO:0000781 chromosome, telomeric region and 
GO:1990421 subtelomeric heterochromatin
are siblings

---

We want to move GO:1990421 subtelomeric heterochromatin as a child of 
GO:0000781 chromosome, telomeric region 
and add a new child, 'chromosome, telomeric repeat region' 
- narrow synonym: chromosome, telomeric loop region

**Comment by pgaudet** [comment]
Added subclasses: 
 - [x] GO:0099115 chromosome, subtelomeric region
Added -> is_a: GO:0000781 ! chromosome, telomeric region

----

 - [x] GO:1990707 nuclear subtelomeric heterochromatin
Added ->  is_a: GO:0000784 ! nuclear chromosome, telomeric region

---

 - [x]  Changed definition 
GO:0000784  name: nuclear chromosome, telomeric region

OLD def: "The terminal region of a linear nuclear chromosome that includes the telomeric DNA repeats and associated proteins." [GOC:elh]
NEW def: "The end of a linear chromosome, required for the integrity and maintenance of the end. A chromosome telomere usually includes a region of telomerase-encoded repeats the length of which rarely exceeds 20 bp each and that permits the formation of a telomeric loop (T-loop). The telomeric repeat region is usually preceded by a sub-telomeric region that is gene-poor but rich in repetitive elements. Some telomeres only consist of the latter part (for eg. D. melanogaster telomeres)." [GOC:elh]

**Comment by pgaudet** [comment]
NEW TERM 

+id: GO:0140445
+name: chromosome, telomeric repeat region
+namespace: cellular_component
+def: "A complex of DNA and protein that seals the end of a chromosome. The telomeric repeat DNA consists of simple tandemly repeated sequences specific for each species. Typically one strand is G-rich and the other C-rich. The G-rich strand forms a 3'-terminal overhang, the length of which varies with species. The single strand overhang is bound by a variety of proteins, including telomere capping proteins that bind to the single-stranded DNA and seal the telomeric loop." [PMID:11352055, PMID:30208292]
+is_a: GO:0000781 ! chromosome, telomeric region
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19086 xsd:anyURI
+created_by: pg
+creation_date: 2020-03-27T13:29:16Z

**Comment by ValWood** [comment]
Hi @pgaudet 
If you did not already, could you rehouse

telomere cap complex GO:0000782
shelterin complex GO:0070187
CST complex GO:1990879
under the new term GO:0140445  chromosome, telomeric repeat region

tks

**Comment by pgaudet** [comment]
>  If you did not already, could you rehouse
telomere cap complex GO:0000782
shelterin complex GO:0070187
CST complex GO:1990879
under the new term GO:0140445 chromosome, telomeric repeat region

Now done, thanks
