### ISSUE TITLE
add parent 	negative regulation of translation in response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19092]
negative regulation of translation in response to nitrogen starvation
+ synonym negative regulation of translation in response to amino acid starvation

could this have the parent
" cellular response to amino acid starvation GO:0034198"

**Comment by pgaudet** [comment]
Isn't that some pathway that is not well defined by just being put under 'regulation of transcription'?

**Comment by ValWood** [comment]
translation....

It is a signalling pathway really 
https://www.pombase.org/term/GO:0043555
(downstream of TOR signalling)

but I have never seen it called anything except 'negative regulation of translation in response to 
nitrogen starvation/amino acid starvation.

This is just an attempt to group these, since they both exist. 
I think we could do a better job of this longer term.

**Comment by pgaudet** [comment]
@ValWood 
There are only 2 annotations to this term (negative regulation of translation in response to nitrogen starvation), both from pombase, both from the same paper: PMID:10725227. 

You annotated the B-type cyclins Cig2 and Cdc13, that are regulated by the Ded1/Sum3 translation initiation factor - they are the target of the negative regulation of translation - they should anyway not be annotated to this term, should they ? 

It seems 'cellular response to amino acid starvation' is a perfectly good term to annotate Cig2 and Cdc13 - in which case 'negative regulation of translation in response to nitrogen starvation' would not be needed anymore. 

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
yes that annotation is incorrect. I removed it.

I only read the abstract but   it seems. that Ded1/Sum3  is receiving a signal 
and 
"negative regulation of translation in response to nitrogen starvation"
would be required to annotate this pathway.

However, for others we have done precomposition with the stress term

negative regulation of cytoplasmic translational initiation in response to stress
  | gcn2 during cellular response to nitrogen starvation

So this still leaves the issue what is the difference between 
'cellular response to amino acid starvation' 
and
 cellular response to nitrogen starvation

which is what I was trying to establish, but by going around the houses!

**Comment by ValWood** [comment]
AND if we get rid of the term, we should also 'decompose' these (which look over-composed)

GO:1905287    positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation | part_of
-- | --
GO:0036278    positive regulation of transcription from RNA polymerase II promoter in response to nitrogen starvation | is_a
GO:0070321    regulation of translation in response to nitrogen starvation | is_a
GO:1901482    L-lysine import into vacuole involved in cellular response to nitrogen starvation | part_of
GO:0031142    induction of conjugation upon nitrogen starvation | is_a
GO:0010516    negative regulation of cellular response to nitrogen starvation | negatively_regulates
GO:1901481    L-glutamate import involved in cellular response to nitrogen starvation

**Comment by pgaudet** [comment]
For now I'll obsolete 
* GO:0070321 regulation of translation in response to nitrogen starvation
* GO:0070322 negative regulation of translation in response to nitrogen starvation
* GO:0070323 positive regulation of translation in response to nitrogen starvation 

OK ?

**Comment by ValWood** [comment]
OK!

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0070321 regulation of translation in response to nitrogen starvation
* GO:0070322 negative regulation of translation in response to nitrogen starvation
* GO:0070323 positive regulation of translation in response to nitrogen starvation 

The reason for obsoletion is that these terms represent 'GO:0034198' cellular response to amino acid starvation'. There were 2 annotations to these terms (by PomBase) that have now been removed (see https://github.com/geneontology/go-ontology/issues/19092#issuecomment-600508114). 

There are no mappings; this term is not present in any subset. 

You can comment in the ticket: 
https://github.com/geneontology/go-ontology/issues/19092

We are opening a comment period for this proposed obsoletion. We’d like to proceed with the obsoletion this term on March 21st, 2020. Unless objections are received by March 21st, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by tberardini** [comment]
@ukemi pointed out this paper, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3586203/, which shows that in Arabidopsis, at least one miRNA family is involved in regulating the translation of target mRNAs in response to nitrogen starvation.  Perhaps these terms should be retained. We have not (yet) annotated the miRNAs but would use at least one of the terms slated for obsoletion.

**Comment by ValWood** [comment]
I had a use for them -  but I  now post-composed using 
"cellular response to nitrogen starvation" 

happy to do it either way (although now I have changed)
My only requirement is that nitrogen starvation/amino acid starvation. are linked in some way.

**Comment by pgaudet** [comment]
> at least one miRNA family is involved in regulating the translation of target mRNAs in response to nitrogen starvation.

Shouldn't we post-compose it as:  "negative regulation of translation - has_target xx" part of "cellular response to nitrogen starvation"?
