### ISSUE TITLE
new term request: EC 5.4.4.7 - Hydroperoxy icosatetraenoate isomerase 

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#19094]
Hi,
could you please create this Go term corresponding to [Rhea:37951], [Rhea:37959] and [Rhea:37939] in PubMed=12881489,
many thanks.
Guilaine

**Comment by hdrabkin** [comment]
Please provide a term name for each of these please. (and they have to be different).

**Comment by hdrabkin** [comment]
Otherwise for a one term I will give it the EC name and use the RHEA id that closely matches the EC reaction

**Comment by hdrabkin** [comment]
never mind; too little coffee

**Comment by hdrabkin** [comment]
+id: GO:0106255
+name: hydroperoxy icosatetraenoate isomerase
I used the generic RHEA:55560 to align with the  EC number and the term name, which is generic.
