### ISSUE TITLE
Go term request: EC 4.2.1.152 - Hydroperoxy icosatetraenoate dehydratase

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#19095]
Hi,
Could you please create the Go term EC 4.2.1.152 - Hydroperoxy icosatetraenoate dehydratase corresponding to [Rhea:37943] and PubMed=12881489.
Many thanks.
Guilaine

**Comment by hdrabkin** [comment]
Parent will be GO:0016836 (hydro-lyase activity, EC:4.2.1
EC def is 
A hydroperoxy icosatetraenoate <=> an oxoicosatetraenoate + H(2)O
RHEA def will be
(12R)-hydroperoxy-(5Z,8Z,10E,14Z)-eicosatetraenoate = 12-oxo-(5Z,8Z,10E,14Z)-eicosatetraenoate + H2O
BUT RHEA:55556, also mapped to this EC, is 
a hydroperoxyeicosatetraenoate = an oxoeicosatetraenoate + H2O

Is there a reason why you mapped this to the very granular RHEA?  I assume the paper you cite measures the granular reaction specifically? If that's the case, note that the new term will bet the granular definition, ok?

--

**Comment by hdrabkin** [comment]
I will use the more granular RHEA to match the term name and EC. If you wish to have a term that specifically uses the granular term then I need a term different name

**Comment by hdrabkin** [comment]
+id: GO:0106256
+name: hydroperoxy icosatetraenoate dehydratase activity
 RHEA:55556
