### ISSUE TITLE
obsolete, possibly? positive regulation of translational initiation in response to starvation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19091]
Isn't translation negatively regulated in response to starvation? (i.e negatively regulate growth)
(3 mouse annotations but seems incorrect)

http://amigo.geneontology.org/amigo/term/GO:0071264

(I noticed I was picking up an ISS to the otholog  which is a negative regulator)

**Comment by ukemi** [comment]
Can't both positive and negative regulation of translation part of the integrated stress response? I thought some genes were up-regulated and some genes were down-regulated through the pathway. We need to be very careful about obsoleting terms that might be useful. 
@vanaukenk

**Comment by deustp01** [comment]
I don't know about starvation regulation in yeasts, but in humans there are  crucial negative and positive regulatory processes triggered by starvation. Both are essential as is cross-talk between them. The classic example is the complementary regulation of glycolysis and gluconeogenesis, coordinated with glycogen storage and breakdown, and with fatty acid synthesis and storage, and fatty acid breakdown to maintain blood glucose levels. And while this description is at the whole-organism level the processes are implemented at the level of intricate signaling processes at the molecular level.

**Comment by ValWood** [comment]
Ah yes OK, the general regulation is down in nutrient stress, but there is some specific up regulation of specific messages (e.g in neurons)

" inhibition of general protein synthesis but increased translation of specific messages, such as ATF4"

So the positive regulation  will be target gene specific. I will transfer this to be an annotation ticket so that the annotations don't get transferred to yeast.

**Comment by ukemi** [comment]
Whew!

**Comment by ValWood** [comment]
raised dispute for  fission yeast annotation in protein2go
