### ISSUE TITLE
Obsoletion GO:0075141    symbiont tolerance to host environment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19099]
GO:0075141    symbiont tolerance to host environment
Definition (GO:0075141 GONUTS page)
Any process that contributes to the maintenance of a physiologic state in which the symbiont immune system does not react destructively against the components of its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

has 1 annotation.

Seems related to  to
GO:0042783    evasion of host immune response
?

**Comment by pgaudet** [comment]
All former children were merged into this term, see #18827

**Comment by ValWood** [comment]
but should

GO:0075141    symbiont tolerance to host environment
 be a child of 
GO:0075136    response to host

but the term is a bit nonsense anyway.

What is the "symbiont immune system"

I don't understand the term and it is in a branch on it's own !

**Comment by pgaudet** [comment]
@mgiglio99 @dsiegele

**Comment by pgaudet** [comment]
Will obsolete. There are no annotations anymore (I removed the 1 MTBBASE)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0075141 symbiont tolerance to host environment. The reason for obsoletion is that it is redundant with existing terms such as 'GO:0052200 response to host defenses' or 'GO:0075136 response to host.'

There are no annotations or mappings to this term; this term is not present in any subsets. 

You can add comments to the ticket: https://github.com/geneontology/go-ontology/issues/19099

Thanks, Pascale
