### ISSUE TITLE
mitochondrion-plasma membrane adaptor PMID:31582398

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19090]
I would like a term to describe a 
mitochondrion-plasma membrane adaptor

the existing protein membrane adaptor definition does not fit:

GO:0043495    protein membrane adaptor activity
Molecular Function
Definition (GO:0043495 GONUTS page)
Interacting selectively and non-covalently with both a protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location.

Also I would like to specify 'mitochondrion" in the term, becasue I don't have any specific protein to put as has_input

**Comment by ukemi** [comment]
Can you provide parents, a proposed definition and a reference?

**Comment by ValWood** [comment]
The reference is above PMID:31582398.

 I would have spelled it out more fully but I was confused where it would be placed in the current arrangement... It seems that 
GO:0043495 protein membrane adaptor activity would need to be broadened, because it is a "protein membrane adaptor" but does not fit the definition?

**Comment by ukemi** [comment]
mitochondrion-plasma membrane bridging activity?

**Comment by ValWood** [comment]
mitochondrion-plasma membrane adaptor
Interacting selectively and non-covalently with both ~a protein or protein complex~ the mitochondrion and the plasma membrane, in order to maintain the localization of the ~protein~ mitochondrion at a specific membrane location.

It could currently only go under
GO:0030674    protein-macromolecule adaptor activity

but I  think it should be able to go under
GO:0043495    protein membrane adaptor activity
if this term was relaxed.

Or a grouping term could be created  "membrane adaptor"

If we stick with the current arrangement  "membrane adaptors" will end up annotated inconsistently.

**Comment by ValWood** [comment]
Well, we now call all  bridging activities adaptors ?

protein binding, bridging 
is an exact synonym of 
GO:0030674   protein-macromolecule adaptor activity

**Comment by pgaudet** [comment]
Yes I think so

**Comment by ValWood** [comment]
@ukemi can we steal this, will do with Pascale today as she recently reviewed the adaptors

**Comment by pgaudet** [comment]
- [x] added subclass 'protein-macromolecule adaptor activity' to 'cargo adaptor activity' (which was not done here #17553) 
- [x] fix definition 'protein membrane adaptor activity' 
**current:** Interacting selectively and non-covalently with both a protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location.
**new:**  Bringing together a protein or a protein complex with a membrane, or bringing together two membranes, either via membrane lipid binding or by interacting with a membrane protein, to establish or maintain the localization of the protein, protein complex or organelle.

**Comment by pgaudet** [comment]
New term: 

+[Term]
+id: GO:0140443
+name: mitochondrion-plasma membrane adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a protein or a protein complex with a mitochondrion either via membrane lipid binding or by interacting with a mitochondrial outer membrane protein, to establish or maintain the localization of the mitochondrion." [PMID:31582398]
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/pull/19140 xsd:anyURI
+created_by: pg
+creation_date: 2020-03-24T13:11:20Z
+

**Comment by ValWood** [comment]
This definition sounds a bit weird ;)

The binding activity of a molecule that brings together a  mitochondrion  and a plasma membrane either via membrane lipid binding or by interacting with a mitochondrial outer membrane protein, to establish or maintain the localization of the mitochondrion
