### ISSUE TITLE
GO:0099115    chromosome, subtelomeric region

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19102]
@pgaudet 
@RLovering 

I also found
GO:0099115    chromosome, subtelomeric region
which  has not been used directly by anyone

All of the EXP annotations are inherited from a process annotation:
GO:0099114    chromatin silencing at subtelomere
(which I don't think we should do because  it isn't the right evidence for localization, but that is a separate issue).

If this term is required (I'm not sure if it is), it should be a parent of
GO:1990421    subtelomeric heterochromatin
Heterochromatic regions of the chromosome found at the subtelomeric regions.

**Comment by pgaudet** [comment]
@ValWood 
We decided to keep GO:0099115 chromosome, subtelomeric region 
here #19086

**Comment by pgaudet** [comment]
Also other changed you propose have been made in that same ticket.
