### ISSUE TITLE
mutualism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19100]
Finds this term
GO:0085030 | symbiotic process benefiting host

defined
GO:0085030    JSON
Definition (GO:0085030 GONUTS page)
A process carried out by symbiont gene products that enables a symbiotic interaction with a host organism, that is beneficial to the host organism.

related 'mutualism'

So, there  isn't  a term for mutalism (both the pathogen and host benefit?)
This is probably because if you are annotating a pathogen gene it probably didn't *evolve* to benefit the host. Just wanted to check this is the reason.

@CuzickA

**Comment by ValWood** [comment]
Oh, but that would be the other way around...

So the question is now, should this term refer to the symbiont and the host?

@mgiglio99

**Comment by pgaudet** [comment]
Mutualism was merged into symbiosis, see #14807

The reason was that: 
> The following terms are not processes; they correspond to modes of interactions between organisms, but not to processes.

Is that OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
That makes sense. So this particular term should be "not for direct  annotation" because to use it you would know the specific process that benefitted the host?

The only annotation is to
http://europepmc.org/article/MED/24463512
which makes sense. This seems to be some metabolism that benefits the host.

@CuzickA  maybe we should not make a process annotation because we don't know if/how the host benefits from the interaction with this locus ? (other than not being killed, I guess !)

**Comment by ValWood** [comment]
I'm reopening this because we are annotating a gene that allows a mutualistic lifestyle to occur by manipulation of the host immune system. If the gene product is manipulated the pathogen becomes pathogenic.

The particular gene product isn't directly involved in one of the benefits provided by the pathogen to the host (i.e nutrient acquisition/availability), but is required for a mutualistic lifestyle.

We now see why we should not annotate this to the "symbiotic process benefiting the host", we should make it clearer how this term should be used. Maybe it can be made "not for direct annotation" so that only valid examples would be annotated by requesting appropriate descendants?


There are currently 10 annotations from one paper so these would be easy to fix right now.

@CuzickA

**Comment by pgaudet** [comment]
@ValWood do you still want that term? we would need a different way to capture that

**Comment by ValWood** [comment]
No it's out of scope.
