### ISSUE TITLE
CLRC ubiquitin ligase rename?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19101]
Term name  does not seem to focus on the primary activity (i.e histone H3-K9 methytransferase), or  be how this complex is usually referred to.

CLRC ubiquitin ligase complex (GO:0043494)
Definition    Parents
An cullin-dependent E3 ubiquitin ligase/histone H3-K9 methyltransferase complex essential for heterochromatin assembly by RNAi.

It should either be should it be really precise:
CLRC complex (usual most common name?)
CLRC histone H3-K9 methytransferase (primary activity?)
or
CLRC histone H3-K9 methytransferase/ H3-K14 ubiquitin ligase complex (precise?)

but not
CLRC ubiquitin ligase complex

@colinlog 
@bmeldal

**Comment by colinlog** [comment]
clr4 is the H3-K9 methyltransferase in this fungal complex.
The human and mouse paralogs SUV39H1 and SUV39H2 are not (yet) described to be in a complex with a cullin. Below I used psi-BLAST from EBI and Uniprot to investigate this further. My conclusion is that this complex is not (yet?) found in humans. For S.pombe it very probably does exist.

Answering the naming precision question: This complex has 2 demonstrated enzymes, clr4 and cul4. The better name is then *** CLRC ubiquitin ligase and Histone H3 Lysine 9 methyltransferase complex ***. ie; do not delete the cullin activity, simply add the H3K9 methyltransferase activity is my opinion. Very similar to Val's suggestion (precise)

invetigation:
cul4 in S.pombe is reported in a protein complex with clr4, pip1, raf1 en raf2.
The human orthologs of these four S.p proteins are cul4 - CUL4B, CUL4A, CUL3, CUL... (there are 10 human cullins), pip1 - RBX1 (RNF7 is the next one), raf1 (no ortholog? POC1B centriolar protein) and raf2 (DNMT1 RFD domain that targets to replication foci)- no semblance of a human ortholog. There are human cullin complexes. But they have not (yet?) been shown to harbour SUV39H1/2. The interaction of some Cullin cmplexes with transcription processes exist, and the closest I found for a co-regulator/chromatin remodelling factor is interaction with chromatin  through degradation of the histone H4 acetyltransferase KAT5/ESA1. There is more to be found in the literature, but no SUV39H1/2...

**Comment by ukemi** [comment]
But shouldn't it be just CLRC complex if this is the most common name?

**Comment by colinlog** [comment]
We were talking about its description/definition, weren't we Val? The name
is the discoverer's privilege / bane, isn't it?  Hence following the adage:
'you name it, you own it'.

**Comment by bmeldal** [comment]
The 2 functions should be in the text definition and in the logical definition. The name should be as unambiguous as possible. "CLRC complex" seems more logical than the full, long-winded name that is almost a full description ;-)

**Comment by ValWood** [comment]
Yes, just "CLRC complex"  would be best.
The definition is fine.
Sorry, I made a meal of that!

**Comment by ValWood** [comment]
I see how we got here:
 PMID: 17114925

Title: A **Cullin E3 Ubiquitin Ligase Complex** Associates with Rik1 and the Clr4
Histone H3-K9 Methyltransferase and Is Required for RNAi-Mediated
Heterochromatin Formation

abstract
TS) complex. Here we report the purification
of a novel complex that associates with the Clr4 methyltransferase, termed the **CLRC
(CLr4-Rik1-Cul4) complex**.
