### ISSUE TITLE
GO:0070816 phosphorylation of RNA polymerase II C-terminal domain

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19105]
GO:1903655    phosphorylation of RNA polymerase II C-terminal domain serine 2 residues involved in positive regulation of transcription elongation from RNA polymerase II promoter

(Used by PomBAse and Complex portal)

**Comment by ValWood** [comment]
phosphorylation of RNA polymerase II C-terminal domain serine 5 residues involved in positive regulation of transcription elongation from RNA polymerase II promoter

SGD, PomBAse and Complex portal

**Comment by hdrabkin** [comment]
it's a one sentence GO-Cam!
But it appears this is a termgenie request created by vw?

**Comment by hdrabkin** [comment]
18 annotations; 
Suggest curators re-curate using Noctua or extensions?

**Comment by ValWood** [comment]
I know! that's the way we were advised to do things in the termgenie era. Pugging together preexisting terms.

We can post-compose this easily but we don't need to use Noctua, we have a more scalable way to curate GO-CAM ;). This particular type of term we would by-pass anyway because "phosphorylation" of anything is a MF in the process ontology. So there are (at least)  a couple of problems with this term. Over pre-composition, *and* redundancy (function  in the process ontology)

**Comment by hdrabkin** [comment]
BTW, you can get a pro id for unphosphorylated and phosphorylated versions (5 and 2) to use for input/output!

**Comment by krchristie** [comment]
> BTW, you can get a pro id for unphosphorylated and phosphorylated versions (5 and 2) to use for input/output!

Interesting issue for PRO to deal correctly with RNAP II CTD phosphorylations. The CTD is a conserved but slightly variable heptapeptide repeat and the number of repeats varies from species to species, 26 in cerevisiae, 52 in humans. serine 2 and serine 5 in this context refer to serines 2 and 5 in the repeat sequence YSPTSPS. In a given "phosphorylated CTD", some/many but not all serine 2's or serine 5's could be modified.

**Comment by ValWood** [comment]
@krchristie  I was going to say the same.
The heptad repeat is the reason why we have punted the issue in this instance. Usually we do request modified forms.  But this one a 'special case' It would be interesting to hear if PRO are planning a way to deal with this particular (but important) edge case.

**Comment by krchristie** [comment]
Might be worth talking to them about this. I seem to recall asking for a term that specified any of 1, 2, or 3 modifications within a set of three positions in a specific region (can't remember enough about modification or gene to find it now). They might be able to do something similar. There would clearly be a use for terms that distinguished the modifications sets on the RNAP II CTD.

**Comment by hdrabkin** [comment]
Hi @nataled 
Can you comment on this?

**Comment by nataled** [comment]
My comment:
https://proconsortium.org/cgi-bin/textsearch_pro?search=search&field0=ALLFLDS&query0=heptad&search.x=0&search.y=0

I will add that we can easily make a species non-specific versions of these.

**Comment by ValWood** [comment]
Oh, I had already requested some of these! Totally forgot ;)

**Comment by hdrabkin** [comment]
So for this ticket
How should I proceed? Are the groups involved going to reannotate? 
Should I  put up an obsoletion notice (2 wk period)?

**Comment by ValWood** [comment]
I guess normal obsoletion.
I have fixed PomBase so it is only Complex Portal (@bmeldal )

**Comment by bmeldal** [comment]
Ok, missed this one (I wasn't tagged in original post). Will the direct child remain?

**Comment by bmeldal** [comment]
There is also the sibling:
GO:1903654 phosphorylation of RNA polymerase II C-terminal domain serine 5 residues involved in positive regulation of transcription elongation from RNA polymerase II promoter

**Comment by hdrabkin** [comment]
I think that one should GO (haha) also.

**Comment by hdrabkin** [comment]
I'll makea notice to GO-Friends anyways and wait maybe one week?

**Comment by hdrabkin** [comment]
@ValWood  just checking; will the IEA annotations via http://www.aspergillusgenome.org/cgi-bin/reference/reference.pl?dbid=ASPL0000000005
 go away also?

**Comment by ValWood** [comment]
If the term  ain't there yes ;)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete  GO:0070816 phosphorylation of RNA polymerase II C-terminal domain and children: 
GO:0071619 phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:0071620 phosphorylation of RNA polymerase II C-terminal domain serine 5 residues  
GO:1901921 phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex
GO:1901408 negative regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:1901409 positive regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:1901407 regulation of phosphorylation of RNA polymerase II C-terminal domain 
GO:2001163 regulation of phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:2001164 negative regulation of phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:2001165 positive regulation of phosphorylation of RNA polymerase II C-terminal domain serine 2 residues 

The reason for obsoletion is that these correspond to molecular functions. 

Consider changing annotations to 
GO:0140834 RNA polymerase II C-terminal domain S2 kinase activity
GO:0140836 RNA polymerase II C-terminal domain S5 kinase activity
GO:0140837 RNA polymerase II C-terminal domain S7 kinase activity
GO:0140835 RNA polymerase II C-terminal domain T4 kinase activity


There are 68 EXP annotations: see https://github.com/geneontology/go-annotation/issues/4408
Group | Number of annotations
-- | --
CACAO | 1
ComplexPortal | 14
FlyBase | 3
SGD | 47
UniProt | 3

There are no mappings; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/19105

Thanks, Pascale
