### ISSUE TITLE
GO:0032290-mistake in definition and redundant to GO:0022011

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/go-ontology#19106]
GO:0032290 peripheral nervous system myelin formation. In the definition it is incorrectly stated that  an oligodendrocyte forms myelin in the peripheral nervous system. In fact, oligodendrocytes only form myelin in central nervous system, while Schwann cells form myelin in the peripheral nervous system.

Also this term seems to be redundant to GO:0022011 myelination in peripheral nervous system.

**Comment by ukemi** [comment]
Oops. @BarbaraCzub do you want to take this one or should I assign it to myself? I think that the difference in the terms is that the formation term refers only to forming the myelin structurally, while the myelination term refers to the more global process with respect to its correct distribution etc. @BarbaraCzub could you comment on this as well?

**Comment by BarbaraCzub** [comment]
@huaiyumi is right. It should be Schwann cells in the definition and not oligodendrocytes. 
With regard to differences in the actual terms @ukemi we would probably need to review a selection of annotations to both terms to understand whether curators have been using one to capture the structural formation of myelin and the other for the global process.

**Comment by ukemi** [comment]
No worries. I will take it.

**Comment by BarbaraCzub** [comment]
Thank you!

**Comment by ValWood** [comment]
seems like a quick fix.

**Comment by pgaudet** [comment]
All genes annotated to GO:0022011  myelination in peripheral nervous system (237) are also annotated to GO:0032290 peripheral nervous system myelin formation, so the difference is probably too subtle, I will merge. 

![image](https://user-images.githubusercontent.com/4782928/98806039-de295d80-2418-11eb-93a9-d591949b0b0c.png)


Please reopen if a clearer distinction can be made. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I fixed the incorrect definition.

I cannot tell whether those other terms are redundant. Definitions could probably be improved. 

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/4782928/98807767-6f013880-241b-11eb-805d-033103dc7b82.png">

@RLovering @dosumis Can you help with this ? Otherwise maybe we just close the ticket for now. 

Thanks, Pascale

**Comment by RLovering** [comment]
not an expert on this but I can't see any glaring errors - sorry I can't help more
Ruth

**Comment by pgaudet** [comment]
Well I cannot find a paper/review that explains how myelin assembly is different from myelination - see for eg 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691794/

And looking at definitions: 
* GO:0042552  myelination: The process in which myelin sheaths are formed and maintained around neurons. Oligodendrocytes in the brain and spinal cord and Schwann cells in the peripheral nervous system wrap axons with compact layers of their plasma membrane. Adjacent myelin segments are separated by a non-myelinated stretch of axon called a node of Ranvier.
*  GO:0032288  myelin assembly : The process in which the wraps of cell membrane that constitute myelin are laid down around an axon in the central or peripheral nervous system.

Looks like myelination is a grouping class for myelin assembly and myelin maintenance. I dont know if myelin maintenance really exists; the papers annotated are IMPs with myelination defects.

**Comment by pgaudet** [comment]
I have not heard back, so I suppose this is OK.
