### ISSUE TITLE
barbed end actin filament capping is a process term?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19107]
I want to annotate the MF of "barbed-end actin filament binding"

but the term I want to use is in the BP ontology:

GO:0051016
Term name | barbed-end actin filament capping
The binding of a protein or protein complex to the barbed (or plus) end of an actin filament, thus preventing the addition, exchange or removal of further actin subunits.

clearly a function for formin
Therefore, we begin with three independent lines of evidence that Cdc12(FH1FH2)p caps the barbed ends of actin filaments with high affinity, al- lowing elongation only at pointed ends.
First, 100 nM Cdc12(FH1FH2)p increased the critical concentration (Cc) for actin assembly from 0.13 􏰂M, near the critical concentration of the barbed end, to 0.9 􏰂M, the critical concentration of the pointed end (Fig. 2 A). 10 nM Mus musculus capping protein (MmCP; Palmgren et al., 2001) shifted the critical concentration to 1.0 􏰂M (Fig. 2 A). The critical concentration depended on the concentra- tion of Cdc12(FH1FH2)p (Fig. 2 B), with the shift from the barbed to pointed end occurring between 1 and 10 nM Cdc12(FH1FH2)p. Thus, the dissociation equilibrium con- stant (Kd) for Cdc12(FH1FH2)p at barbed ends is 􏰃0.5 􏰂M (Caldwell et al., 1989).

curating an old paper PMID:12796476

**Comment by ukemi** [comment]
I thought that the formins didn't simply bind, but had to be activated in some way for 'capping' to occur. I also thought that the interaction was also quite dynamic and wasn't simply binding.  Aren't there other proteins that also interact with the barbed end in a dynamic manner during 'capping'? Of course I may also be mis-remembering all of this, but I didn't think it was as simple as just binding.

**Comment by ValWood** [comment]
I don't think so, based on these assays
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2172974/

**Comment by ValWood** [comment]
Ah what I want to annotate is
barbed-end actin filament binding

but this sounds like this:
Term name | barbed-end actin filament capping
The binding of a protein or protein complex to the barbed (or plus) end of an actin filament, thus preventing the addition, exchange or removal of further actin subunits.

profilin alone seems to be able to do this.

**Comment by pgaudet** [comment]
How about if I restored 
Accession
    GO:0003782
Name
    obsolete F-actin capping activity
Ontology
    molecular_function
Synonyms
    F-actin capping activity
Alternate IDs
    None
Definition
    OBSOLETE. (Was not defined before being made obsolete). Source: GOC:ai 
Comment
    This term was made obsolete because it describes a biological process.

Seems we now have a different view of the MF/BP division. 

Thanks, Pascale

**Comment by ValWood** [comment]
I would say so. This is more about a change in  GO philosophy.
I wonder if we can find the history? but even if it multigene it still seems to be fundamentally an MF?

The current situation is problematic for another reason. It's a child of
GO:0030835    negative regulation of actin filament depolymerization

but this isn't necessarily true because profilin appears to negatively regulate at the barbed end, but positively regulate in the pointed end.

**Comment by ValWood** [comment]
duplicate 
see
https://github.com/geneontology/go-ontology/issues/28151
