### ISSUE TITLE
Move 'regulation of x production' terms under 'regulation of gene expression'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19116]
We plan to move 'regulation of x production' terms under 'regulation of gene expression'

Current ontology structure: 
  *  GO:0008150 biological_process
     **  GO:0051239 regulation of multicellular organismal process
         *** GO:0001817 regulation of cytokine production 

Definition of cytokine production: The appearance of a cytokine due to biosynthesis or secretion following a cellular stimulus, resulting in an increase in its intracellular or extracellular levels. 

Definition of gene expression: The process in which a gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form. 

Based on those definitions,  'regulation of x production' should be is_a 'regulation of gene expression'.

**Comment by pgaudet** [comment]
- [x] Change definition of 'cytokine activity' : from "Functions to control the survival, growth, differentiation and effector function of tissues and cells." (which can describe any signaling molecule's activity)

To: "Secreted protein that binds to a signaling receptor and functions to control the survival, growth, differentiation and effector function of tissues and cells."

**Comment by ukemi** [comment]
This doesn't define the MF occurent. It defines a characteristic of the continuant. In otehr words, it defines a cytokine, not cytokine activity.

**Comment by pgaudet** [comment]
You mean, we should reformulate something like this: 

"The activity of a soluble extracellular gene product that interacts with a receptor to effect a change in the activity of the receptor to control the survival, growth, differentiation and effector function of tissues and cells."

?

**Comment by ukemi** [comment]
Yes, but a genus differentia would be even better.

**Comment by pgaudet** [comment]
Such as ?
