### ISSUE TITLE
Edits to L-seryl-tRNA(Sec) kinase activity (GO:0043915)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19111]
1. Add EC xref EC 2.7.1.164 (https://enzyme.expasy.org/EC/2.7.1.164)
2. Add additional parent of "kinase activity" (GO:0016301)?

**Comment by hdrabkin** [comment]
RHEA:25037 ; for my notes just it case it's not in term already (not logged in yet)

**Comment by hdrabkin** [comment]
Done I hope
