### ISSUE TITLE
GO:0007016 | cytoskeletal anchoring at the plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19119]
we have MF 

cytoskeletal protein-membrane adaptor activity

so we probably no longer  need:

GO:0007016 | cytoskeletal anchoring at the plasma membrane
(function in process?)

**Comment by ValWood** [comment]
@pgaudet  we can look at this today...

**Comment by pgaudet** [comment]
**3 InterPro mappings** 
InterPro:IPR015224
InterPro:IPR030691
InterPro:IPR008465

**Comment by pgaudet** [comment]
We need to also obsolete the sibling term GO:0090286 cytoskeletal anchoring at nuclear membrane

**Comment by pgaudet** [comment]
To do: 

- [ ] obsolete BP GO:0007016 cytoskeletal anchoring at the plasma membrane 
- [ ] suggest replacement by MF 'GO:0106006 cytoskeletal protein-membrane adaptor activity' and BP: GO:0007010 cytoskeleton organization or a child (actin, microtubule, etc) 
- [ ] change term label:  cytoskeletal protein-membrane ~adaptor~ **anchor** activity
- [ ] change term label:  cytoskeletal ~adaptor~ **anchor** activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0007016 cytoskeletal anchoring at the plasma membrane. The reason for obsoletion is that this term represents a molecular function, GO:0106006 cytoskeletal protein-membrane adaptor activity. 

There are 28 manual annotations (EXP + others)  and 3 InterPro mappings; see annotation ticket: 
https://github.com/geneontology/go-annotation/issues/2902

Contributor | Number of annotations
-- | --
BHF-UCL | 3
dictyBase | 1
FlyBase | 11
MGI | 2
PINC | 2 (done) 
UniProt | 7
WB | 2


This term is not present in any subsets.

**Comment by RLovering** [comment]
UCL annotations revised

**Comment by pgaudet** [comment]
Also to standardize labels, change the following: 
* GO:1990919 nuclear membrane proteasome anchor -> nuclear membrane-proteasome anchor activity
* spindle pole body anchor -> spindle pole body-nuclear membrane anchor activity

**Comment by pgaudet** [comment]
@ValWood  I did **not** change 'mitochondrion-plasma membrane adaptor activity' to anchor - seems to me anchor is more appropriate for a protein/protein complex, while an adaptor would link two organelles. Thoughts ?

**Comment by ValWood** [comment]
I agree, anchor would sound odd here...
