### ISSUE TITLE
Missing parents for ER localization terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19114]
I know that 'localization' isn't always part of 'organization'

but for 
GO:0051643    endoplasmic reticulum localization
this IS part of "endoplasmic reticulum organization"

https://linkinghub.elsevier.com/retrieve/pii/S2211124719317632

**Comment by ValWood** [comment]
can we discuss today.  Are there rules for when 'localization' can be part of 'organization'?

**Comment by ValWood** [comment]
Does this cause any issues for logical definitions ?

**Comment by pgaudet** [comment]
> Are there rules for when 'localization' can be part of 'organization'

Not that I am aware of. Maybe @ukemi knows ? 

> Does this cause any issues for logical definitions ?

I dont think so. I've added 'part of "endoplasmic reticulum organization"' as a subclass, rather than in the logical definition. 

Pascale
