### ISSUE TITLE
nuclear subtelomeric heterochromatin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19113]
Hi @pgaudet 
I think you merged
0	subtelomeric heterochromatin (GO:1990421)
into
31	nuclear subtelomeric heterochromatin (GO:1990707)	...

This is fine. We should probably only have one term, as it's the same thing. However, the chromosomes aren't always nuclear for organisms that have open mitosis, so you will need to rename 

nuclear subtelomeric heterochromatin (GO:1990707) 
to
subtelomeric heterochromatin
and remove the nuclear parent.

**Comment by pgaudet** [comment]
Wont fix until someone shows a use case
