### ISSUE TITLE
Change parent of hydroxylysine kinase activity (GO:0047992)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19121]
Hi,

Can you change the parent of "hydroxylysine kinase activity (GO:0047992)" from "kinase activity" to "amino acid kinase activity (GO:0019202)"?

hydroxylysine is classed as an amino acid (https://en.wikipedia.org/wiki/Hydroxylysine) so this change would seem correct.

[Term]
id: GO:0047992
name: hydroxylysine kinase activity
namespace: molecular_function
def: "Catalysis of the reaction: erythro-5-hydroxy-L-lysine + GTP = 5-phosphonooxy-L-lysine + GDP + 2 H(+)." [EC:2.7.1.81, RHEA:19049]
is_a: GO:0016301 ! kinase activity
is_a: GO:0016773 ! phosphotransferase activity, alcohol group as acceptor

**Comment by sjm41** [comment]
Hi David - does this request look OK to you? Steven.

**Comment by ukemi** [comment]
Yup. ChEBI agrees too.

**Comment by sjm41** [comment]
Great, thanks!
