### ISSUE TITLE
NTR peroxide sensor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19126]
NTR peroxide sensor activity
Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of hydrogen peroxide (H2O2).
PMID:20919928

parent GO:0140299    small molecule sensor activity

reference PMID:20919928
Two-component mediated peroxide sensing and signal transduction in fission yeast.

(I want this mainly so that I can purge 
"detection of oxidative stress" and standardize the F-P links in this area)

**Comment by ValWood** [comment]
@pgaudet  can we discuss/add today?

**Comment by pgaudet** [comment]
@ValWood 
Are you OK with the standard definition for this term, 'Binding to hydrogen peroxide (H2O2) and eliciting a change in the protein's activity in response to the intracellular level of that small molecule.'?

**Comment by ValWood** [comment]
Absolutely
