### ISSUE TITLE
Typos in term names for "telodendria" terms 

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#19133]
The following terms have a typo in their name:
GO:0120209 - cone teleodendria
GO:0120210 - rod teleodendria
It should be "telodendria", an not "teleodendria".

Note: the spelling of the parent term and in the definitions appear fine

**Comment by ValWood** [comment]
This is one of those weird tickets that is closed but appears in the open tickets list. I don't know what causes this?
