### ISSUE TITLE
Travis check to prevent cross references from RHEA to more than one GO term

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19146]
From #18015 (and probably other tickets). 

We need a Travis check that prevents mapping RHEA IDs to more than one GO term.

Thanks, Pascale

**Comment by hdrabkin** [comment]
BEFORE doing this we need an analysis of how many terms have this problem. Introducing a travis check now may create problems for all commits when people don't know which one to  remove, etc.

**Comment by hdrabkin** [comment]
I have asked Mary Dolan to make a report on how bad (or not) the current ontology is. Once I have that I can go in if need to fix. After that, a check to make sure it doesn't happen again will be useful.

**Comment by hdrabkin** [comment]
Ok, from Mary's report there are 14 RHEA ids in more than one GO term; I will fix. 
I will also get a report of how many GO terms have more than 1 RHEA (hopefully none).

**Comment by hdrabkin** [comment]
reports I'm working on
[1rhea2go.txt](https://github.com/geneontology/go-ontology/files/4377432/1rhea2go.txt)
[1go2rhea.txt](https://github.com/geneontology/go-ontology/files/4377433/1go2rhea.txt)

**Comment by hdrabkin** [comment]
In 1go2rhea, many are (NAD(P)) reactions (hence two separate rhea; still need to resolve

**Comment by hdrabkin** [comment]
1rhea2go will take a few days; many different issues involving either removal OR term merges.

**Comment by hdrabkin** [comment]
It seems to me that this ticket should not be where I discuss the error reports; The point is that this ticket should NOT be invoked until I fix the errors we have. I will open a separate ticket to address the problems.

**Comment by hdrabkin** [comment]
@balhoff , can I close this ticket now? The Travis check alerts us to duplicate Rhea when exact.

**Comment by balhoff** [comment]
Yes, this is done.
