### ISSUE TITLE
Fixing 1GO2rhea and 1RHEA2GO errors

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#19152]
Based on these reports:
[1rhea2go.txt](https://github.com/geneontology/go-ontology/files/4377788/1rhea2go.txt)
[1go2rhea.txt](https://github.com/geneontology/go-ontology/files/4377792/1go2rhea.txt)

**Comment by hdrabkin** [comment]
I have asked Mary Dolan to make a report on how bad (or not) the current ontology is. Once I have that I can go in if need to fix. After that, a check to make sure it doesn't happen again will be useful. From Mary's report there are 14 RHEA ids in more than one GO term; I will fix.
I will also get a report of how many GO terms have more than 1 RHEA (hopefully none). argh; no such luck,but only 15 of those.
1rhea2go will take a few days; many different issues involving either removal OR term merges.

See also ticket #19146 to make a travis check so that this does not happen again! I will be invoking several tickets to fix these associated with these reports to this ticket as base

**Comment by hdrabkin** [comment]
Discovered today that GO:0004674 protein serine/theonine  kinase activity has 2 RHEAs (EC:2.7.11.1, . creating separate terms. and remove rheas from base term.
+id: GO:0106310
+name: protein serine kinase activity
+[Term]
+id: GO:0106311
+name: protein threonine kinase activity

**Comment by pgaudet** [comment]
Should this be closed with the PR https://github.com/geneontology/go-ontology/pull/20013 ?

**Comment by hdrabkin** [comment]
No; there are several more in the reports. They are not simple. I wish there was a way to open the text files to mark the ones resolved and then resave it.

**Comment by hdrabkin** [comment]
Pasted 1go2rhea.txt to make notes for.
GO:0004489 RHEA:19817(NADP) RHEA:19821 (NAD); NAD vs NADP; DONE 2 new terms
+id: GO:0106312
+name: methylenetetrahydrofolate reductase NADH activity
+id: GO:0106313
+name: methylenetetrahydrofolate reductase NADPH activity

GO:0008942 RHEA:24628 (NAD)  RHEA:24632 (NADP; NAD vs NADP  DONE 2 new GO terms
+id: GO:0106316
+name: nitrite reductase NADH activity
+id: GO:0106314
+name: nitrite reductase NADPH activity






GO:0015049 RHEA:13637 (NAD)  RHEA:13641 (NADP); NADH vs NADPH

GO:0015420 RHEA:17873 RHEA:32831; ec onhy has ONE RHEA, RHEA:17873; remove RHEA:32831

GO:0018635 RHEA:26093(NAD) RHEA:26097(NADP); nad vs nadp

GO:0033286 RHEA:32787 RHEA:32791; in/out vs with atp; 32787 best; remove 32791

GO:0033735 RHEA:11784 RHEA:11788 nad vs nadp; we could make nad-dependent vsi nadp dependant.; same ec but different rhea; alter orginal def to mach

GO:0036190 RHEA:31899 (NADP)  RHEA:31903 nad vs nadp; RHEA: 31903 not present; NO RHEAs assigned to EC:1.14.13.137
Suggesst tweak def to remove NAD(P) since NADPH on both sides; confirm with RHEA


GO:0036191 RHEA:31919 RHEA:31923 nad vs nadp 31919 mpaed to term but is NADPH, not NAD(P) ; 31923 not present
Suggesst tweak def to remove NAD(P) since NADPH on both sides confirm with RHEA

GO:0036192 RHEA:31927 RHEA:31934 nad vs nadp
NADPH on both sides of equation; I think term def needs tweak confirm with RHEA

GO:0051903 RHEA:19981(NADp)  RHEA:19985 (nad); nad vs nadp

GO:0052601 RHEA:26085 RHEA:26089; nad vs nadp
4 RHEA; two for the 4s (this term) and the two RHEAs here
26093 and 26097 go with the 4R term (GO:0018635 above)

GO:0052662 RHEA:24084 No NAD anything  RHEA:24091; nad vs nadp
The EC for this GO term has been changed to EC 1.14.15.21; no NAD anything. One RHEA RHEA:32443; one annotation : 
See also GO:0009540



GO:0052663 RHEA:14937 RHEA:14944; nad vs nadp
EC changed to  1.14.15.21; same problems as 52662; no annotations appear to exist. 
GO:0120204 RHEA:60132 RHEA:60136; two steroisomers

**Comment by hdrabkin** [comment]
I suspect that the following need to be oboleted because if the def if based on the Ec, and the Ec was changed and there is NO NAD/NADP involved , the defs are just wrong 
GO:0052662
GO:0052663

**Comment by pgaudet** [comment]
@hdrabkin I thought we now had a check that prevented more than 1 GO<->Rhea mappings

do we need to do anything else here?

**Comment by hdrabkin** [comment]
yes, and now there are none I think. 
There is still this
 suspect that the following need to be obsoleted because if the def if based on the Ec, and the Ec was changed and there is NO NAD/NADP involved, the defs are just wrong
GO:0052662
GO:0052663 
GO:0052662 RHEA:24084 No NAD anything RHEA:24091; nad vs nadp
The EC for this GO term has been changed to EC 1.14.15.21; no NAD anything. One RHEA RHEA:32443; one annotation :
See also GO:0009540

GO:0052663 RHEA:14937 RHEA:14944; nad vs nadp
EC changed to 1.14.15.21; same problems as 52662; no annotations appear to exist.
GO:0120204 RHEA:60132 RHEA:60136; two steroisomers

Just need to recheck. these; tomorrow. Then will close

**Comment by hdrabkin** [comment]
GO:0052662  1 experimental from UniProt 
but EC now 1.14.15.21; NO NAD RHEA 14
GO:0052663  0 annotations Had RHEA:14937: NO NAD(P) i Also now EC:1.14.15.21; 
Suggest contacting UniPROT to evaluate the annotation;
THEN obsolete both terms OR using  the new rheas fix the def.

**Comment by hdrabkin** [comment]
GO:0052663 merged into GO:0052662; NAD(P) removed from defs. 
Closing.
