### ISSUE TITLE
missing parentage 'copper ion transport across blood-cerebrospinal fluid barrier'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#19156]
Right now 'copper ion transport across blood-cerebrospinal fluid barrier' does not have a 'transport across blood-cerebrospinal fluid barrier'.
![transport across blood-CSF barrier](https://user-images.githubusercontent.com/16541096/77560715-dee3a280-6ece-11ea-8c75-9bf335978748.png)
Figure 1. Ancestor Chart for 'copper ion transport across blood-cerebrospinal fluid barrier'. Accessed from QuickGO on 25th March 2020.

### Proposal
In oder to align this terms with the blood-brain barrier ontology, the following revisions are proposed:
- [x] Add a new term 'transport across blood-cerebrospinal fluid barrier'. Definition: The directed movement of substances (e.g. macromolecules, small molecules, ions) through the blood-cerebrospinal fluid barrier. PMID: 21349151. Synonyms: blood-CSF barrier; BCSFB.
- [x] Make 'transport across blood-cerebrospinal fluid barrier' an is_a parent of 'copper ion transport across blood-cerebrospinal fluid barrier', and and is_a child of 'vascular transport'.

Related to: https://github.com/geneontology/go-ontology/issues/19155

cc @RLovering

**Comment by ukemi** [comment]
Odd, it seems like this should be inferred. Did you look at the logical defs?

**Comment by BarbaraCzub** [comment]
No, I haven't yet. But the blood-CSF barrier is certainly a (great/grand)child of vasculature in uberon (unlike the BBB - https://github.com/obophenotype/uberon/issues/1579):
![Screenshot 2020-03-25 at 19 47 23](https://user-images.githubusercontent.com/16541096/77562916-ab564780-6ed1-11ea-886e-c719ae2f8bf5.png)

**Comment by BarbaraCzub** [comment]
- [ ] revise synonyms
