### ISSUE TITLE
NTR: effector-mediated suppression of effector-triggered immunity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19164]
A process mediated by a molecule secreted by a symbiont that results in the suppression of host effector-triggered immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction. 

descendant of
GO:0140403    effector-mediated suppression of host innate immune response by symbiont

PMID:31804478

@CuzickA  this sounds a bit weird. I guess it is correct as it's the third part of the zig-zag-zig model
(I.e and effector mediating a response to an effector-mediated response)

**Comment by ValWood** [comment]
@CuzickA  I don't understand this term.
How come the effector supresses  something it induced (effector-triggered immunity). This sounds  wrong

**Comment by CuzickA** [comment]
For PMID:31804478 we needed a NTR for 'pathogen suppression of ETI' for the below annotation
https://github.com/PHI-base/phipo/issues/207

![image](https://user-images.githubusercontent.com/11753634/78676958-09762800-78df-11ea-8c95-c2b7618d9b1f.png)

This is a complicated suppression assay where the ETI inducer chemical bax was added to trigger host ETI, which was then suppressed by the pathogen effector Pst_12806. 

In the above ticket link I noted that there wasn't an 'effector-mediated suppression of ETI' GO term which we would probably need in the future for logical definitions.

Hope that helps.

**Comment by ValWood** [comment]
Ah, in that case, this isn't for GO. This is more about the experimental set up than the normal process. We can discuss when we next speak.
v
