### ISSUE TITLE
NTR  Protein aggregate centre

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19172]
Name: protein aggregate center
Synonym Proten aggregate centre (exact)
Synonym: PAC (?)
Defintion: nuclear and cytosolic reversible aggregation  of misfolded  proteins and chaperones formed  to shield  thermosensitive proteins from degradation until conditions allow disaggregation and refolding.

We could not find a suitable term?

Parent:
GO:0043232 | intracellular non-membrane-bounded organelle

PMID:32075773
Title | Chaperone-Facilitated Aggregation of Thermo-Sensitive Proteins Shields Them from Degradation during Heat Stress.
Authors | Cabrera M, Boronat S, Marte L, Vega M, Pérez P, Ayté J, Hidalgo E
Cells have developed protein quality-control strategies to manage the accumulation of misfolded substrates during heat stress. Using a soluble reporter of misfolding in fission yeast, Rho1.C17R-GFP, we demonstrate that upon mild heat shock, the reporter collapses in protein aggregate centers (PACs). They contain and/or require several chaperones, such as Hsp104, Hsp16, and the Hsp40/70 couple Mas5/Ssa2. Stress granules do not assemble at mild temperatures and, therefore, are not required for PAC formation; on the contrary, PACs may serve as nucleation centers for the assembly of stress granules. In contrast to the general belief, the dominant fate of these PACs is not degradation, and the aggregated reporter can be disassembled by chaperones and recovers native structure and activity. Using mass spectrometry, we show that thermo-unstable endogenous proteins form PACs as well. In conclusion, formation of PACs during heat shock is a chaperone-mediated adaptation strategy.

**Comment by ValWood** [comment]
also

Name: protein aggregate center formation

**Comment by ValWood** [comment]
"It is worth mentioning that a shift to 37 C is a moderate heat shock for fission yeast, which does not slow growth nor exerts toxicity to wild-type cultures, but significantly affects the viability of cells lacking stress signaling components, such as the MAP kinase Sty1"

**Comment by ValWood** [comment]
Hi Pascale,

Is it possible to get these terms added? We would like to feature this paper on our front page soon, and the author did community curation so we like to get them completed fairly quickly.
Let me know if you need anything else.

Val

**Comment by ValWood** [comment]
Also required

GO:XXXXXXX | cytoplasm protein quality control 
parent of
GO:0071629 | cytoplasm protein quality control by the ubiquitin-proteasome system

This is cytoplasmic quality control, but if the proteins are reduced and refolded there is no proteasome system involvement

**Comment by ValWood** [comment]
Hi Pascale.
Is there anything else required for this one?
Cheers

Val

**Comment by pgaudet** [comment]
Are you sure of the parent 'GO:0043232 intracellular non-membrane-bounded organelle'  ? why not 'protein-containing complex'?

**Comment by pgaudet** [comment]
2. I removed 'nuclear and cytosolic ' - I suppose those can also occur in other organelles and in prokaryotes ?

**Comment by pgaudet** [comment]
3. This is different from the aggregosome, right ? 
http://amigo.geneontology.org/amigo/term/GO:0070842

Do we need a comment to avoid confusion? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140453
+name: protein aggregate center
+namespace: cellular_component
+def: "Reversible aggregate of misfolded proteins and chaperones formed to shield thermosensitive proteins from degradation until conditions allow disaggregation and refolding." [PMID:32075773]
+synonym: "PAC" BROAD []
+synonym: "protein aggregate centre" EXACT []
+is_a: GO:0043232 ! intracellular non-membrane-bounded organelle
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19172 xsd:string
+created_by: pg
+creation_date: 2020-04-20T15:21:55Z
+
+[Term]
+id: GO:0140454
+name: protein aggregate center assembly
+namespace: biological_process
+def: "The reversible aggregation of misfolded proteins and chaperones, formed to shield thermosensitive proteins from degradation until conditions allow disaggregation and refolding." [PMID:32075773]
+synonym: "PAC assembly" BROAD []
+synonym: "protein aggregate center formation" EXACT []
+synonym: "protein aggregate centre assembly" EXACT []
+is_a: GO:0022607 ! cellular component assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19172 xsd:string
+created_by: pg
+creation_date: 2020-04-20T15:43:52Z
+
+[Term]
+id: GO:0140455
+name: cytoplasm protein quality control
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the breakdown of misfolded proteins in the cytoplasm, which are either targeted to cytoplasmic proteasomes for degradation or protected by chaperones to shield thermosensitive proteins from degradation until conditions allow disaggregation and refolding." []
+is_a: GO:0006515 ! protein quality control for misfolded or incompletely synthesized proteins
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19172 xsd:string
+created_by: pg
+creation_date: 2020-04-20T15:46:20Z

**Comment by ValWood** [comment]
I don't think it can be a complex because it isn't a defined composition/stoichiometry.
The authors also described it as a "GO:0043232 intracellular non-membrane-bounded organelle' 
and that is what I would have used.

**Comment by ValWood** [comment]
> This is different from the aggregosome, right ?

Actually it weel could be the same thing. Although it is difficult to tell from the annotation and the def.

GO:0016235
An inclusion body formed by dynein-dependent retrograde transport of an aggregated protein on microtubules. Source: PMID:11121744

but other papers on "aggresome assembly" describe dynein independent formation, so this doesn't seem to be a suitable differentia.

Shouldn't "aggregosome"  be defined by what it does, rather than how it is formed?

**Comment by pgaudet** [comment]
> Shouldn't "aggregosome" be defined by what it does, rather than how it is formed?

Well, it's a CC - it should be defined by its composition ? 

Can you ask your experts whether we can use aggregosome instead, and update the definition (at least for the assembly)

**Comment by pgaudet** [comment]
Existing terms 
* GO:0070842 aggresome assembly:  The aggregation, arrangement and bonding together of a set of components to form an aggresome; requires the microtubule cytoskeleton and dynein. Source: PMID:14675537

*   GO:0016235 aggresome: An inclusion body formed by dynein-dependent retrograde transport of an aggregated protein on microtubules. Source: PMID:11121744

**Comment by ValWood** [comment]
Well the PAC  has no connection with microtubules?
I thought we usually added the function/process as part of the complex definitions?

**Comment by pgaudet** [comment]
@ValWood Can you check the changes I made ? 
https://github.com/geneontology/go-ontology/commit/b19f1ab1d71889dc4705e5b99074bfdea34f5aea

**Comment by ValWood** [comment]
I think it is OK (at least the terms above are what is needed)
