### ISSUE TITLE
NTR: fumigermin biosynthetic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#19179]
Hi,

Can I request a new GO term for fumigermin biosynthetic process please? 

Here are the details:

Accession: GO:xxxxxx
Name: fumigermin biosynthetic process
Ontology: biological_process
Synonyms: fumigermin anabolism, fumigermin biosynthesis, fumigermin formation, fumigermin synthesis
Definition: The chemical reactions and pathways resulting in the formation of fumigermin, an alpha-pyrone secondary metabolite found in some species of fungi such as Aspergillus fumigatus.
is_a: GO:0044550 ! secondary metabolite biosynthetic process
Source: CHEBI:147341, PMID:32083553

Thanks & best wishes,
Achchuthan

**Comment by pgaudet** [comment]
Hi @Achchuthan 
Should I add a taxon constraint at least for fungi?

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Yes, can you kindly add taxon constraint as well please?

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140446
+name: fumigermin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of fumigermin, an alpha-pyrone secondary metabolite found in some species of fungi such as Aspergillus fumigatus." [PMID:32083553]
+synonym: "fumigermin anabolism" EXACT []
+synonym: "fumigermin biosynthesis" EXACT []
+synonym: "fumigermin formation" EXACT []
+synonym: "fumigermin synthesis" EXACT []
+xref: CHEBI:147341
+is_a: GO:0044550 ! secondary metabolite biosynthetic process
+created_by: pg
+creation_date: 2020-03-31T12:02:29Z

**Comment by Achchuthan** [comment]
Thanks a lot @pgaudet

**Comment by pgaudet** [comment]
Added the taxon constraint. 

I've also added CHEBI fumigermin in the imports; when the imports run I'll add the logical definition.
