### ISSUE TITLE
go2rhea: 2go1rhea issues

### ISSUE THREAD

**Issue by amorgat** [geneontology/go-ontology#19174]
Related to #18549:

From http://current.geneontology.org/ontology/external2go/rhea2go
`! Generated on 2020-03-23T19:53Z from the ontology 'go' with data version: 'releases/2020-03-23'`

**RHEA:11996 > GO:2-hydroxybiphenyl 3-monooxygenase activity ; GO:0047544  DONE
 GO:2,2'-hydroxybiphenyl monooxygenase activity ; GO:0102321**  ADD RHEA:63512 done

RHEA:11996 
2-hydroxybiphenyl + H(+) + NADH + O2 = biphenyl-2,3-diol + H2O + NAD(+)

GO:0047544 Definition
_Catalysis of the reaction: biphenyl-2-ol + H(+) + NADH + O(2) = biphenyl-2,3-diol + H(2)O + NAD(+). Source: EC:1.14.13.44, RHEA:11996_ 
--> Correct mapping
`RHEA:11996 > GO:2-hydroxybiphenyl 3-monooxygenase activity ; GO:0047544`

GO:0047544 Definition
_Catalysis of the reaction: biphenyl-2,2'-diol + O2 + NADH + H+ <=> biphenyl-2,2',3-triol + H2O + NAD Source: EC:1.14.13.44, GOC:pz_
--> missing Rhea reaction
RHEA:63512 created the 2020-03-27 (publicly available mid-June release)
RHEA:63512 
biphenyl-2,2'-diol + H+ + NADH + O2 = biphenyl-2,2',3-triol + H2O + NAD+
mapping: (RHEA:63512, GO:0102321)

@hdrabkin , I also created:
- RHEA:63516  biphenyl-2,2',3-triol + H+ + NADH + O2 = biphenyl-2,2',3,3'-tetraol + H2O + NAD+
**Additional mapping (RHEA:63516, GO:0102325)**
GO:0102325 2,2',3-trihydroxybiphenyl monooxygenase activity
- RHEA:63524  2-propylphenol + H+ + NADH + O2 = 3-propylcatechol + H2O + NAD+
**Additional mapping (RHEA:63524, GO:0102322)**
GO:0102322	2-propylphenol monooxygenase activity
- RHEA:63520  2-isopropylphenol + H+ + NADH + O2 = 3-isopropylcatechol + H2O + NAD+
**Additional mapping (RHEA:63520, GO:0102323)**
GO:0102323	2-isopropylphenol monooxygenase activity

**Comment by hdrabkin** [comment]
Hi @amorgat ; I have a report generated from by Mary Dolan in our group that gives me the 2rhea1go and 2go1rhea mappings; I attached it to #19152; I fix them in chunks. 
Maybe add any comments to that ticket; no sense opening a separate ticket for each one. As #19152 indicates, I have to fix these first before any additional travis checks get added 
(#19146)

**Comment by amorgat** [comment]
ok @hdrabkin, I'll put all comments in this ticket. Especially to give you the newly Rhea Ids I created.

**Comment by hdrabkin** [comment]
I've added all rhea mentioned in this ticket thus far.

**Comment by hdrabkin** [comment]
last rhea added;  will close now.
