### ISSUE TITLE
protein quality control issues

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19171]
~I am looking for
chaperone-mediated  (protein) refolding
I can find 
GO:0061077   chaperone-mediated protein folding
bout the 'refolding' child is called
GO:0051085    chaperone cofactor-dependent protein refolding
(I don't know why the process needs to specify whether a cofacter is present or not. How would we know?)
There are other strange children here
GO:0061992    ATP-dependent chaperone mediated protein folding | is_a
GO:1990507    ATP-independent chaperone mediated protein folding | is_a
GO:0051086    chaperone mediated protein folding independent of cofactor
should these merge? whether something is ATP dependent should be part of the activity of a specific gene product rather thanthe process (which could not be known at this stage). 
For example  GO:1990507 has 4 annotation (2 genes), I think this just meant this particular chaperone does not require ATP?~

out of date

**Comment by ValWood** [comment]
GO:0051086    chaperone mediated protein folding independent of cofactor
has a single experimental annotation. This is describing chaperonin .

chaperonin is:
A multisubunit ring-shaped complex that mediates protein folding in the cytosol without a cofactor. PMID:11580267
but the 'without a cofactor' isn't a useful differentia for the process.

Pretty sure these should merge.

OR rename  GO:0051086 
CCT/TRiC- chaperonin mediated protein folding
for clarity

**Comment by ValWood** [comment]
cripes.
protein refolding
is defined as 

The process carried out by a cell that restores the biological activity of an unfolded or misfolded protein, using helper proteins such as chaperones.


There is no such thing as protein refolding without chaperones is there (or if there is its autonomous, therefore not annotatable!)

So  "protein refolding" merge with "GO:0051086    chaperone mediated protein folding independent of cofactor"
and rename "chaperone-mediated (protein) refolding"

and I kid you not, these are in different branches:

<img width="393" alt="Screenshot 2020-03-27 at 11 44 12" src="https://user-images.githubusercontent.com/7359272/77752903-5aa13480-7020-11ea-958d-cdf2b487b96d.png">


Anyone who thinks GO annotation is not inconsistent and annotation do not need to be revised is plainly bonkers !

**Comment by ValWood** [comment]
This one should be grouped in a mini project for "Protein Quality Control"
There are loads of tickets about this. 
If you create a label I can tag them.

**Comment by pgaudet** [comment]
@ValWood 
Are you sure refolding is any different from folding? I meant to merge this - there is another ticket somewhere, from @RLovering I think. See also attached paper. 

[chaperones.pdf](https://github.com/geneontology/go-ontology/files/4856951/chaperones.pdf)

**Comment by ValWood** [comment]
>Are you sure refolding is any different from folding?

No. You are right it is just the context that is  different.

**Comment by RLovering** [comment]
Hi Both

I left Rebecca to work on the ontology, but I can see that it seems odd to have refolding not by chaperones. However I am wondering if https://www.uniprot.org/uniprot/P62942 is an exception. We have curated FKBP1A as refolding but not chaperone folding based on author statements in https://pubmed.ncbi.nlm.nih.gov/11322937/ so please check this before revising the placement of this term 
Thanks
Ruth

**Comment by ValWood** [comment]
I think  the "unfolding chaperones" are different

the 'unfolding chaperones' are required for 'refolding' and are called 'disaggregases'.
I requested a term for one a while back

https://github.com/geneontology/go-ontology/issues/19173

But I don't  think we need the term I requested for refolding here.

MF disaggregase involved in "protein refolding"

we don't need to bake the chaperone part into the process term. If we are annotating a chaperone it is obvious it is chaperone-mediated.

I think we should remove "chaperone-mediated' from all process terms (unless it is used to differentiate  a specific pathway. This might be the case for 'chaperone-mediated autophagy).

**Comment by pgaudet** [comment]
I will obsolete 
GO:0061992    ATP-dependent chaperone mediated protein folding 
GO:1990507    ATP-independent chaperone mediated protein folding 

since these really should be MFs. Only 6 annotations. 

This will complete the work on ATPases. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think this one can close as out of date. Action is not clear , or is duplicate din other tickets (except
GO:0061992 ATP-dependent chaperone mediated protein folding
GO:1990507 ATP-independent chaperone mediated protein folding
part which is done.
