### ISSUE TITLE
NTR: disaggregase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19173]
Overview 
https://www.ncbi.nlm.nih.gov/pubmed/26312418
Molecular chaperones and heat shock proteins are specialized in controlling the quality of the proteins in the cell, specifically by aiding proper folding, and dissolution and clearance of already formed protein aggregates. The latter is a function of disaggregases, mainly represented by the ClpB/Hsp104 subfamily of molecular chaperones, that are ubiquitous in all organisms but, surprisingly, have no orthologs in the cytosol of metazoan cells. This review aims to describe the characteristics of disaggregases and to discuss the function of yeast Hsp104, a disaggregase that is also involved in prion propagation and inheritance.

I think it will need to be a direct child of MF , and of protein binding like 
sibling of 
GO:0044183   protein folding chaperone
Definition (GO:0044183 GONUTS page)
Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) that contributes to the process of protein folding.

unless you want to add a grouping term?

proposed definition
A ATPase chaperone activity that mediates the solubilization of ordered  protein aggregates

**Comment by ValWood** [comment]
Actually this  an ATPase so it could be housed, will tweak the def (but aren't most folding chaperones, except chaperonin-mediated T-complex ATPases?)

**Comment by ValWood** [comment]
Thre is a process for this, but it is an activity performed by some classes of chaperone:

protein unfolding
The process of assisting in the disassembly of non-covalent linkages in a protein or protein aggregate, often where the proteins are in a non-functional or denatured state.

**Comment by pgaudet** [comment]
I will also create grouping class, 'molecular chaperone activity' : 

+[Term]
+id: GO:0140551
+name: molecular chaperone activity
+namespace: molecular_function
+def: "Interacting with another protein to stabilize it or help it acquire its functionally active conformation, without being present in its final structure." [PMID:21776078]
+is_a: GO:0003674 ! molecular_function
+created_by: pg
+creation_date: 2020-11-12T17:14:10Z

**Comment by pgaudet** [comment]
Should I also remove this relation: 
GO:0032984 protein-containing complex disassembly 
is_a GO:0043933 protein-containing complex subunit organization?

**Comment by pgaudet** [comment]
also changed the definition of 'protein folding chaperone': 

OLD def: "Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) that contributes to the process of protein folding."
NEW def: "Binding to a protein or a protein-containing complex to assist the protein folding process."

**Comment by ValWood** [comment]
The problem is that chaperones group quite a few different activities. Not all are protein folding. For example preventing aggregation, preventing degradation, transporting. If we can't disambiguate these as activities, we wnd up making very convoluted annotation

chaperone, part_of  in  RNA stability, part_of positive regulation of gene expression occurs_during response to oxidative stress.
protein binding part_of  protein unfolding part_of  protein quality control  (not a real term)

We could make much more succint annotation if we didn't need to concatenate like this

We can have a grouping term but it needs to be very general - it might be better not to have a grouping term 
but have specific chaperones for the different types (easer to find?)


i) Disaggregase
ii) Folding chaperone
iii) Those chaperones that 'escort' protein to the mitochondrial IM (maybe these would be carriers in GO but they are always referred to as Tim complex chaperones)
and  others

**Comment by ValWood** [comment]
GO:0032984 protein-containing complex disassembly
is_a GO:0043933 protein-containing complex subunit organization?

sounds weird.

Is the term  "protein-containing complex subunit organization" necessary?

**Comment by ValWood** [comment]
Euuuh, or anything with "subunit organization"?

**Comment by pgaudet** [comment]
> Euuuh, or anything with "subunit organization"?

Right - assembly should be sufficient?

**Comment by ValWood** [comment]
'subunit organization' seems to cover assembly, disassembly  and other stuff, but "organization" should be sufficient why say 'subunit organization' Is there a reason?

**Comment by pgaudet** [comment]
@ValWood 
Are you saying that those 3 terms 
i) Disaggregase
ii) Folding chaperone
iii) Those chaperones that 'escort' protein to the mitochondrial IM

should not have a common parent ? 

https://github.com/geneontology/go-ontology/issues/19173#issuecomment-726296356

**Comment by ValWood** [comment]
I think I am saying a grouping term might not make sense because these different types of 'chaperones' have different activities.  Or is the common theme 'some aspect of 'protein protection' ???

**Comment by pgaudet** [comment]
I guess it's ok - I just dont want to have the top level of MF too flat.

**Comment by pgaudet** [comment]
New term: 

 
+[Term]
+id: GO:0140545
+name: protein disaggregase activity
+namespace: molecular_function
+def: "An ATP-dependent molecular chaperone activity that mediates the solubilization of ordered protein aggregates." [PMID:26312418]
+is_a: GO:0016887 ! ATPase activity
+relationship: has_part GO:0005515 ! protein binding
+relationship: part_of GO:0032984 ! protein-containing complex disassembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19173 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-10T16:57:19Z

----


Also, changed protein folding chaperone ( GO:0044183)

-OLD def: "Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) that contributes to the process of protein folding." [GOC:mtg_cambridge_2009]
+NEW def: "Binding to a protein or a protein-containing complex to assist the protein folding process." [GOC:mtg_cambridge_2009]
-intersection_of: GO:0003674 ! molecular_function
**-intersection_of: has_part GO:0005515 ! protein binding**
-intersection_of: part_of GO:0006457 ! protein folding
+is_a: GO:0003674 ! molecular_function
**+relationship: has_part GO:0051082 ! unfolded protein binding**
+relationship: part_of GO:0006457 ! protein folding


Thanks, Pascale

**Comment by ValWood** [comment]
I just used this term.
On reflection I don't think it should be  part_of
+relationship: part_of GO:0032984 ! protein-containing complex disassembly

This is resolving proteins from aggregates not 'complexes'
It seems more like "protein quality control" (although we don't yet have a general PQC term, there are other tickets about this)

**Comment by ValWood** [comment]
Just need to review parentage here...

**Comment by pgaudet** [comment]
PQC would be a process though

**Comment by ValWood** [comment]
I was thinking that this would always be part of PQC (function process link), however it can occur in other contexts I think...

close?

**Comment by pgaudet** [comment]
> it can occur in other contexts I think

I think so too
