### ISSUE TITLE
2 terms same meaning (karyogamy)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19186]
please merge
nuclear membrane fusion involved in karyogamy (GO:0048288)
Definition | Parents
The joining of 2 or more lipid bilayer membranes that surround the nucleus during the creation of a single nucleus from multiple nuclei.

into
karyogamy (GO:0000741)
Definition 
The creation of a single nucleus from multiple nuclei as a result of fusing the lipid bilayers that surround each nuclei.

the definitions are identical

**Comment by pgaudet** [comment]
It does seem like the nuclear fusion is an actual step of karyogamy, see PMID:23715006. 

There is also nuclear migration - for example those terms should probably be 'part_of karyogamy: 
GO:0000743 'nuclear migration involved in conjugation with cellular fusion' 
GO:0000745 'nuclear migration involved in conjugation with mutual genetic exchange' 

Thanks, Pascale

**Comment by ValWood** [comment]
Of course. The def of karyogamy (GO:0000741) needs to be clearer.

but remember karyogamy isn't specific to yeast but "conjugation with cellular fusion"  and "genetic exchange" are.

**Comment by ValWood** [comment]
Actually I think the current is ok

The microtubule-based movement of nuclei towards one another as a prelude to karyogamy in organisms undergoing conjugation with cellular fusion. PMID:16380440

It seems that karyogamy  is just the membrane fusion step?

@Antonialock ?

**Comment by pgaudet** [comment]
@ValWood What should I do about this one ?

**Comment by ValWood** [comment]
@Antonialock  do you think these two terms should merge?

**Comment by Antonialock** [comment]
yes they look identical 

and 'nuclear membrane fusion' seems like a reasonable parent to karyogamy!

**Comment by pgaudet** [comment]
Thanks. I merged the terms and changed the logical definition to 
> 'organelle membrane fusion'
 and (results_in_fusion_of some 'nuclear membrane')

**Comment by pgaudet** [comment]
I get an error because the logical definition is the same as 'GO:0000740 nuclear membrane fusion', which also have the same def: 

"The joining of 2 or more lipid bilayer membranes that surround the nucleus. "

Should I also merge ??? Or can this process occur outside of karyogamy ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I was thinking to add 
'part of karyogamy' but then it's circular !

**Comment by ValWood** [comment]
MAybe  the arrangment is OK as it is.
@Antonialock   more stuff must happen in karyogamy in addition to nuclear membrane fusion.?Presumably the nuclear contents need to reorganize in some way?
which is why we also have terms like
GO:0007344   pronuclear fusion
under karyogamy

Definition (GO:0007344 GONUTS page)
The merging of two pronuclei in a fertilized egg to fuse and produce a single zygotic genome.

which occur after membrane fusion? pronuclei don't seem to exist until the membranes are fused.

So instead, it seems like the original definition of karyogamy is not necessary and sufficient, because it only describes the nuclear membrane fusion part?

**Comment by Antonialock** [comment]
nuclear fusion is "what happens" during karyogamy.  
In general 
1. pheromone signaling, where mating partners recognize each other 
2. plasmogamy ('conjugation with cellular fusion') - 2 cells merge
3. karyogamy - nuclear membrane fusion, produces a zygote
4. mitosis or meiosis (carry on as a diploid or produce spores)
 

@pgaudet 
> "The joining of 2 or more lipid bilayer membranes that surround the nucleus. "
> 
> Should I also merge ??? Or can this process occur outside of karyogamy ?

I think it can...

1. This plant paper suggests that 'karyogamy' is reserved for hetero-fusion events, but that homotypic fusion also occurs

https://www.sciencedirect.com/science/article/pii/S1084952116302282
_"Nuclear fusion usually occurs only a few times throughout the life cycle. In flowering plants including A. thaliana, nuclear fusion occurs three times [71]. The first fusion occurs upon maturity of the central cell. The central cell has two polar nuclei, originating from eight haploid nuclei produced by three rounds of mitosis of the megaspore. Fusion of the homotypic polar nuclei generates a diploid nucleus designated the secondary nucleus. The remaining two are classified as nuclear fusions termed karyogamy, namely, heterotypic nuclear fusion between male and female gametes."_

2. isn't the nuclear membranes formed and maintained by fusion events?

so maybe karyogamy is part_of sexual reproduction and is_a nuclear membrane fusion and is differentiated from other fusion events in that it takes place between heterotypic (?) nuclei?

**Comment by Antonialock** [comment]
Ah yes, sorry, I think of karyogamy as two nuclei fusing but that is the ;end result' and I guess a few things need to happen before the actual fusion event (organize MT network, nuclear congression..)

close?

**Comment by ValWood** [comment]
closing!

**Comment by manulera** [comment]
Hi @ValWood I hadn't seen this. I agree with what's been said that karyogamy would comprise nuclear congression as well as fusion, but there seems not to be any link with nuclear migration in the children of this term, perhaps a missing link?

```mermaid
graph BT;
      http://purl.obolibrary.org/obo/GO_0000745["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000745>GO:0000745</a><br>nuclear migration in<br>volved in conjugatio<br>n with mutual geneti<br>c exchange"]-->|part_of|http://purl.obolibrary.org/obo/GO_0000744["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000744>GO:0000744</a><br>karyogamy involved i<br>n conjugation with m<br>utual genetic exchan<br>ge"];
      http://purl.obolibrary.org/obo/GO_0000742["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000742>GO:0000742</a><br>karyogamy involved i<br>n conjugation with c<br>ellular fusion"]-->|is_a|http://purl.obolibrary.org/obo/GO_0000741["<u><strong><a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000741>GO:0000741</a><br>karyogamy</strong></u>"];
      http://purl.obolibrary.org/obo/GO_0000744["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000744>GO:0000744</a><br>karyogamy involved i<br>n conjugation with m<br>utual genetic exchan<br>ge"]-->|is_a|http://purl.obolibrary.org/obo/GO_0000741["<u><strong><a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000741>GO:0000741</a><br>karyogamy</strong></u>"];
      http://purl.obolibrary.org/obo/GO_0010197["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0010197>GO:0010197</a><br>polar nucleus fusion<br>"]-->|is_a|http://purl.obolibrary.org/obo/GO_0000741["<u><strong><a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000741>GO:0000741</a><br>karyogamy</strong></u>"];
      http://purl.obolibrary.org/obo/GO_0007344["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0007344>GO:0007344</a><br>pronuclear fusion"]-->|is_a|http://purl.obolibrary.org/obo/GO_0000741["<u><strong><a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000741>GO:0000741</a><br>karyogamy</strong></u>"];
      http://purl.obolibrary.org/obo/GO_0032871["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0032871>GO:0032871</a><br>regulation of karyog<br>amy"]-->|regulates|http://purl.obolibrary.org/obo/GO_0000741["<u><strong><a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000741>GO:0000741</a><br>karyogamy</strong></u>"];
      http://purl.obolibrary.org/obo/GO_0048288["<a href=https://www.ebi.ac.uk/QuickGO/term/GO:0048288>GO:0048288</a><br>nuclear membrane fus<br>ion involved in kary<br>ogamy"]-->|part_of|http://purl.obolibrary.org/obo/GO_0000741["<u><strong><a href=https://www.ebi.ac.uk/QuickGO/term/GO:0000741>GO:0000741</a><br>karyogamy</strong></u>"];
```
