### ISSUE TITLE
GO:0033662   modulation by symbiont of host defense-related protein level (OBs or merge)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19194]
GO:0033662   modulation by symbiont of host defense-related protein level

is a readout of  immune system impression, not really a process

4 annotations

**Comment by RLovering** [comment]
Hi Val

I am not sure about this one. I usually steer clear of host/pathogen interactions but Simona today asked about curation of: https://www.ncbi.nlm.nih.gov/pubmed/?term=17428862. Perhaps you could help me with checking her annotations to this?
thanks
Ruth

**Comment by ValWood** [comment]
I will take a look, might be a day or so. In the queue ;)

**Comment by ValWood** [comment]
Although I don't really understand human pathogen interactions so much, but this will be a good exercise. At first glance, it looks analogous to some of the plant pathogen processes that affect cell death pathways.

**Comment by pgaudet** [comment]
Hi @RLovering @simonapanni 

It's always useful to know what figure you are trying to annotate, and what other terms were annotated. 

1. Here the best term to capture the take home message of the paper is 
GO:0019051 induction by virus of host apoptotic process  for SARS-CoV 7a

2. It would be nice to annotate Bcl-XL with some sort of 'defense response to virus', but I cannot find an appropriate term for defense to apoptosis induction. We can create it if needed. 

3.  SARS-CoV 7a and Bcl-XL should also be annotated to protein binding with  

4. SARS-CoV 7a should be annotated to GO:0033650 host cell mitochondrion. 

@pmasson55 if you have time to have a look that'd be very appreciated ! 

Pascale

**Comment by pmasson55** [comment]
Yes sounds good to me, looks like the viral protein promotes apoptosis.
7a is also found in the  endoplasmic reticulum so I would put host endoplasmic reticulum.

**Comment by ValWood** [comment]
Sounds good.

**Comment by pgaudet** [comment]
4 annotations: 

1. Genome polyprotein P27958 PMID:20162731 AgBase
-> also annotated to GO:0033663 negative regulation of acute inflammatory response-> can delete the annotation

2. E protein Q84706 PMID:23332027 CACAO
-> Shows that the E protein of the porcine epidemic diarrhea virus causes upregulation of interleukin-8. I think IL8 should be annotated to 'defense response to virus' but can we consider the viral protein an effector @ValWood ? 
If we can, then we could change the annotation to 'effector-mediated modulation of host defenses by symbiont'

3. hopAI1 Q888W0 PMID:16123135 JCVI
- This paper should be reannotated, it has a lot of data not captured. The only annotation for the viral protein is 'modulation by symbiont of host defense-related protein level' 

- Here the hopAI1 effector blocks the expression of the host (plant) NHO1 gene, which prevents - growth of the symbiont. 
- Bacterial flagellin induces NHO1 expression, which reduces growth of the symbiont.
(@ValWood I think we should annotate flagellin as an effector, since the paper states "Flagellin is a well known PAMP that induces innate immune responses") 
-> Add annotation to flagellin 'effector-mediated modulation of host innate immune response by symbiont'
- Expression of the DC3000 effectors HopS1, HopAI1, HopAF1, HopT1-1, HopT1-2, HopAA1-1, HopF2, HopC, and AvrPto in the plant cell blocks the NHO1 induction by flg22
-> Add annotation to all those genes to 'effector-mediated suppression of pattern-triggered immunity signaling'? 


4. 3. hopAI1 Q888W0 PMID:18005697 JCVI
hopA is clearly described as an effector, so we can use 'effector-mediated modulation of host innate immune response by symbiont'
- Can also annotate to 'suppression by symbiont of defense-related host MAP kinase-mediated signal transduction pathway' 

@ValWood what do you think of those suggestions ? 

Anyway I think the term 
GO:0033662 modulation by symbiont of host defense-related protein level and its regulation children should be obsoleted, the terms I propose here are much more informative. 

Thanks, Pascale

**Comment by ValWood** [comment]
> but can we consider the viral protein an effector @ValWood ?

I don't think so.  Effectors are a programme of evolved secreted proteins. I would use the parent


>Bacterial flagellin induces NHO1 expression, which reduces growth of the symbiont.
(@ValWood I think we should annotate flagellin as an effector, since the paper states "Flagellin is a well known PAMP that induces innate immune responses")
-> Add annotation to flagellin 'effector-mediated modulation of host innate immune response by symbiont'

No- PAMPs aren't effectors. They are symbiont proteins that are 'recognised by the host'. The supression of symbiont growth here is a host defense response. The symbiont isn't doing anything in an evolved way  *
This is a symbiont cell-surface  protein required for the symbiont lifestyle, not something it evolved and  secrete and do something to the host immune system. 

The only way to annotate a PAMP in GO is as a ligand for a host PAMP receptor.

v

**Comment by ValWood** [comment]
Re:
> hopAI1 Q888W0 PMID:18005697 JCVI
hopA is clearly described as an effector, so we can use 'effector-mediated modulation of host innate immune response by symbiont'
Can also annotate to 'suppression by symbiont of defense-related host MAP kinase-mediated signal transduction pathway'

This is a place where there are 2 ways of saying the same thing.
"Supression  of immune response", or "suppression of MAP kinase pathway"
because the immune response siganlling is through the MAP kinase pathway

I wonder if we should not have  "suppression of MAP kinase pathway"
because if we know that the gene product is directly  inhibiting a MAP kinase, this is a MF
and if we don't know, it's just a readout for immune signalling (i.e you often see  MAP kinase activation used as an assay for immune response along with ROS increase, and transcription/ increased level of defense related genes)


since
HopAI1 inactivates MAPKs by removing the phosphate group from phosphothreonine through a unique phosphothreonine lyase activity, which is required for HopAI1 function.


I would use
NTR MAP kinase inhibitor  activity has_input [MAP Kinase] part of "'effector-mediated modulation of host innate immune response by symbiont"

**Comment by simonapanni** [comment]
Sorry I've seen this only now

> Il giorno 01 apr 2020, alle ore 07:44, pgaudet <notifications@github.com> ha scritto:
> 
> 
> Hi @RLovering <https://github.com/RLovering> @simonapanni <https://github.com/simonapanni>
> It's always useful to know what figure you are trying to annotate, and what other terms were annotated.
> 
> 
Figures added when missing. 
> Here the best term to capture the take home message of the paper is
> GO:0019051 induction by virus of host apoptotic process for SARS-CoV 7a
> 
> It would be nice to annotate Bcl-XL with some sort of 'defense response to virus', but I cannot find an appropriate term for defense to apoptosis induction. We can create it if needed.
> 
> SARS-CoV 7a and Bcl-XL should also be annotated to protein binding with
> 
> 
Bcl-XL should be  Q07817
> 
> SARS-CoV 7a should be annotated to GO:0033650 host cell mitochondrion.
> 
> 

Term added

Thanks

**Comment by pgaudet** [comment]
Thanks @simonapanni 
So, do you agree GO:0033662 modulation by symbiont of host defense-related protein level is not needed and we can obsolete ?

Thanks, Pascale

**Comment by simonapanni** [comment]
Yes thanks

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0033662 modulation by symbiont of host defense-related protein level and its children: 
* GO:0033663 negative regulation by symbiont of host defense-related protein level
* GO:0033664 positive regulation by symbiont of host defense-related protein level 

The reason for obsoletion is that this is a readout, and annotations should be made to more informative terms. 

There are 4 annotations to this term, see https://github.com/geneontology/go-annotation/issues/2916

There are no mappings, this term is not present in any subsets. 

You can comment in the ticket: 
https://github.com/geneontology/go-ontology/issues/19194

We are opening a comment period for this proposed obsoletion. We’d like to proceed with the obsoletion this term on April 8th, 2020. Unless objections are received by April 8th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
> The only way to annotate a PAMP in GO is as a ligand for a host PAMP receptor.

How about if I created a new term, 'host immune receptor ligand', to capture this type of activity ? It looks like there is a need to capture this.

**Comment by simonapanni** [comment]
This could be used for PAMP only or in general for any heterologous ligands?

**Comment by pgaudet** [comment]
The idea was any ligand - maybe the term is too specific - we can maybe do 'host signaling receptor ligand' ?

**Comment by ValWood** [comment]
> How about if I created a new term, 'host immune receptor ligand', to capture this type of activity ? It looks like there is a need to capture this.

I really don't like this. It  isn't the activity of the pathogen protein.
We discussed recently in another ticket. I will try to find it.
@addiehl  commented on this too. Maybe you can remember ticket Alex?
If we did this it would be a floodgate to other things. It's useful information, but it's out of scope for GO.

And the ligand can be captured correctly as a substrate of a receptor.

**Comment by ValWood** [comment]
Alex mentioned some epitope database in the other ticket.

Another problem is that the PAMP is  often not usually a gene product, it can be lots of other things (fragments of chitin for example).

**Comment by ValWood** [comment]
By the way Hi Simona, I hope you and Roberto are both keeping well :)

**Comment by simonapanni** [comment]
We are fine,  thanks Val!!!
I’ ll write you privately 😉

**Comment by addiehl** [comment]
The Immune Epitope Database, http://www.iedb.org, provides a comprehensive collection of antibody and T cell epitopes curated from over 21,000 papers.  It is the appropriate resource for curating 'host immune receptor ligands' and GO needs no such term nor should attempt to replicate the 17 years of curation effort IEDB has carried out in this area.  They are a well funded resource, run by Bjoern Peters and ably assisted by Randi Vita, James Overton, and a host of scientific curators, and they have contributed significantly to the development of a range of biomedical ontologies as well in the course of their work.

**Comment by pgaudet** [comment]
Humm, we do have 'pathogen-derived receptor ligand activity', created here #16656

I think that works ?

**Comment by ValWood** [comment]
Clarification
pathogen-derived receptor ligand activity
def
The activity of a pathogen entity that interacts with a host receptor to activate effector triggered immunity

is not for PAMPS. It is for the effectors where the *evolved* activity is to act as a ligand in order to activate (for necrotrophs) or suppress (for biotrophs) the host immune system. So this is a  _bona fida_ GO MF

**Comment by pgaudet** [comment]
OK thanks for the clarification. Maybe this deserves a comment ??

**Comment by ValWood** [comment]
Yes, that would be really, really useful here.

**Comment by pgaudet** [comment]
Added this: 

Note that this term is meant to annotate effectors for which the evolved activity is to act as a ligand to activate (for necrotrophs) or suppress (for biotrophs) the host immune system. It should not be used to annotate PAMPs (pathogen-associated molecular pattern molecules) or similar types of microbial proteins recognized by the host innate immune system (for example, PAMPs are recognized by toll-like receptors (TLRs) and other pattern recognition receptors (PRRs) in both plants and animals). PAMPs activate innate immune responses, protecting the host from infection, but this is not the molecular function of PAMPs; those usually form the structure of the bacterial cell wall.

----
What do you think ?

**Comment by RLovering** [comment]
that sounds good to me

**Comment by simonapanni** [comment]
Fine thanks

**Comment by ValWood** [comment]
I would say

Note that this term is only for the annotate of pathogen/symbiont  effectors

and
but this is not the *evolved* molecular function of PAMPs;
