### ISSUE TITLE
Remove EC:1.14.11 as xref on several GO terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19193]
EC:1.14.11 is a grouping ID (https://enzyme.expasy.org/EC/1.14.11.-) and is correctly an xref on this corresponding GO term:

id: GO:0016706
name: 2-oxoglutarate-dependent dioxygenase activity
namespace: molecular_function
alt_id: GO:0010302
def: "Catalysis of the reaction: A + 2-oxoglutarate + O2 = B + succinate + CO2. This is an oxidation-reduction (redox) reaction in which hydrogen or electrons are transferred from 2-oxoglutarate and one other donor, and one atom of oxygen is incorporated into each donor." [GOC:mah]
synonym: "2-oxoglutarate dioxygenase activity" EXACT []
synonym: "oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, 2-oxoglutarate as one donor, and incorporation of one atom each of oxygen into both donors" EXACT []
xref: EC:1.14.11

But I think it should be removed as an xref on the following 7 terms:
(I didn't easily see a replacement EC xref for any of these)

id: GO:0018602
name: 2,4-dichlorophenoxyacetate alpha-ketoglutarate dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2,4-dichlorophenoxyacetate + 2-oxoglutarate + oxygen = 2,4-dichlorophenol + glyoxylate + succinate + CO2." [UM-BBD_reactionID:r0274]
xref: EC:1.14.11

id: GO:0019798
name: procollagen-proline dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: procollagen L-proline + 2-oxoglutarate + O2 = procollagen trans-hydroxy-L-proline + succinate + CO2." [EC:1.14.11.2, EC:1.14.11.7, GOC:mah]
xref: EC:1.14.11

id: GO:0034792
name: hypophosphite dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: hypophosphite + 2-oxoglutarate + O2 = succinate + phosphite + CO2." [UM-BBD_reactionID:r1058]
xref: EC:1.14.11

id: GO:0043734
name: DNA-N1-methyladenine dioxygenase activity
namespace: molecular_function
def: "Catalysis of the oxidative demethylation of N1-methyladenine and N3-methylcytosine in DNA, with concomitant decarboxylation of 2-oxoglutarate and releases oxidized methyl group on N1-methyladenine and N3-methylcytosine as formaldehyde." [PMID:19786499]
synonym: "AlkB" NARROW []
synonym: "alpha-ketoglutarate-dependent dioxygenase" NARROW []
xref: EC:1.14.11

id: GO:0000907
name: sulfonate dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: sulfonate + 2-oxoglutarate + O2 = sulfite + aminoacetaldehyde + succinate + CO2." [EC:1.14.11.-, GOC:clt, PMID:10482536]
synonym: "sulfonate/alpha-ketoglutarate dioxygenase activity" EXACT []
synonym: "sulphonate dioxygenase activity" EXACT []
xref: EC:1.14.11

id: GO:0052634
name: C-19 gibberellin 2-beta-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: a C-19 gibberellin + 2-oxoglutarate + O2 = a C-19 2-beta-hydroxygibberellin + succinate + CO2. C-19 gibberellin refers to a gibberellin with nineteen carbons." [EC:1.14.11.13, GOC:kad]
synonym: "(C-19 gibberellin-1),2-oxoglutarate:oxygen oxidoreductase (2beta-hydroxylating)" EXACT []
synonym: "C(19) gibberellin 2-oxidase activity" EXACT []
synonym: "C-19 GA 2-oxidase activity" EXACT []
synonym: "C-19 gibberellin 2-beta-hydroxylase activity" EXACT []
synonym: "C-19 gibberellin 2-oxidase activity" EXACT []
synonym: "C-19 gibberellin 2beta-dioxygenase activity" EXACT []
synonym: "C-19 gibberellin 2beta-hydroxylase activity" EXACT []
xref: EC:1.14.11

id: GO:0052635
name: C-20 gibberellin 2-beta-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: a C-20 gibberellin + 2-oxoglutarate + O2 = a C-20 2-beta-hydroxygibberellin + succinate + CO2. C-20 gibberellin refers to a gibberellin with twenty carbons." [EC:1.14.11.13, GOC:kad]
synonym: "(C-20 gibberellin-1),2-oxoglutarate:oxygen oxidoreductase (2beta-hydroxylating)" EXACT []
synonym: "C(20) gibberellin 2-oxidase activity" EXACT []
synonym: "C-20 GA 2-oxidase activity" EXACT []
synonym: "C-20 gibberellin 2-beta-hydroxylase activity" EXACT []
synonym: "C-20 gibberellin 2-oxidase activity" EXACT []
synonym: "C-20 gibberellin 2beta-dioxygenase activity" EXACT []
synonym: "C-20 gibberellin 2beta-hydroxylase activity" EXACT []
xref: EC:1.14.11

**Comment by hdrabkin** [comment]
removed the 3 digit ecs but notice other issues (dual 4 digit ecs; have to resolve those; most likely come from term merges.

**Comment by hdrabkin** [comment]
removed dual EC and added PMID for GO_0019798

**Comment by sjm41** [comment]
Thanks!
