### ISSUE TITLE
NTR: gamma-aminobutyric acid:sodium:chloride symporter activity

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#19190]
PMID:10973981 shows that GAT1 (P30531 (SC6A1_HUMAN) SLC6A1) is a Na(+)/Cl(-)/gamma-aminobutyric acid (GABA) cotransporter (Figure 5). However, it appears that during the GAT1 transport cycle, while two Na+ ions, one Cl- ion, and one GABA molecule are transported into the cell across the plasma membrane, one Cl- ion gets exported upon completion of the cycle, so there is no net flux of the Cl- ions (Figures 7 and 8).

In order to annotate this protein:
1) Should I add a new term: gamma-aminobutyric acid:sodium:chloride symporter activity ?
2) Or should I annotate using the existing term: gamma-aminobutyric acid:sodium symporter activity (GO:0005332)? (since the net flux of Cl- is estimated to be zero).

Proposal:
NTR: 
gamma-aminobutyric acid:sodium:chloride symporter activity
is_a parents: 
GO:0005332 gamma-aminobutyric acid:sodium symporter activity
GO:0015378 sodium:chloride symporter activity
Definition: 
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: gamma-aminobutyric acid(out) + Na+(out) + Cl-(out) = gamma-aminobutyric acid(in) + Na+(in) + Cl- (in).
Exact synonyms: 
4-aminobutanoic acid:sodium:chloride symporter activity
GABA:sodium:chloride symporter activity
gamma-aminobutyric acid/sodium/chloride symporter activity
4-aminobutanoic acid/sodium/chloride symporter activity
GABA/sodium/chloride symporter activity

cc @RLovering 
cc @ukemi

**Comment by pgaudet** [comment]
hi @BarbaraCzub 

Is there a typo ? The proposal 1 and 2 are the same term: 
gamma-aminobutyric acid:sodium:chloride symporter activity
gamma-aminobutyric acid:sodium:chloride symporter activity

Am I missing something ? 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Yes, there is a typo. Thanks. Correcting now!

**Comment by BarbaraCzub** [comment]
Updated comment.

**Comment by pgaudet** [comment]
@BarbaraCzub 
The existing term GO:0005332 gamma-aminobutyric acid:sodium symporter  links to TCDB http://www.tcdb.org/search/result.php?tc=2.A.22.3.2, which mentions GAT-1, which is also in the paper you are citing, so I dont think we need a new term. 

Perhaps you can add a synonym, a comment, or improve the definition ? 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi @pgaudet thanks for looking into it. I annotated to GO:0005332 gamma-aminobutyric acid:sodium symporter activity, as you advised.
Thanks, Barbara
