### ISSUE TITLE
Remove EC:1.1.1 as xref on several GO terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19195]
EC:1.1.1 is a grouping ID (https://enzyme.expasy.org/EC/1.1.1.-) and is correctly an xref on this corresponding GO term:

id: GO:0016616
name: oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
namespace: molecular_function
def: "Catalysis of an oxidation-reduction (redox) reaction in which a CH-OH group acts as a hydrogen or electron donor and reduces NAD+ or NADP." [EC:1.1.1.-, GOC:ai]
xref: EC:1.1.1

But I think it should be removed as an xref on the following 5 terms:
(I didn't easily see a replacement EC xref for any of these)

id: GO:0032866
name: D-xylose:NADP reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: D-xylitol + NADP+ = D-xylose + NADPH + H+." [PMID:12724380, PMID:15184173]
synonym: "D-xylose reductase activity" BROAD []
synonym: "xylose reductase activity" BROAD []
xref: EC:1.1.1

id: GO:0032867
name: L-arabinose:NADP reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-arabitol + NADP+ = L-arabinose + NADPH + H+." [PMID:12724380, PMID:15184173]
synonym: "arabinose reductase activity" BROAD []
synonym: "arabinose:NADP reductase activity" BROAD []
xref: EC:1.1.1

id: GO:0033765
name: steroid dehydrogenase activity, acting on the CH-CH group of donors
namespace: molecular_function
def: "Catalysis of an oxidation-reduction (redox) reaction in which a CH-CH group acts as a hydrogen or electron donor and reduces a hydrogen or electron acceptor, and in which one substrate is a sterol derivative." [GOC:mah]
xref: EC:1.1.1

id: GO:0000252
name: C-3 sterol dehydrogenase (C-4 sterol decarboxylase) activity
namespace: molecular_function
def: "Catalysis of the reaction: 3-beta-hydroxy-4-beta-methyl-5-alpha-cholesta-8,24-dien-4-alpha-carboxylate + NAD(P)+ = 4-alpha-methyl-5-alpha-cholesta-8,24-dien-3-one + CO2 + NAD(P)H." [EC:1.1.1.170, PMID:9811880]
comment: Note that zymosterol is cholesta-8,24-dien-3-ol.
synonym: "3beta-hydroxy-4alpha-methylcholestenecarboxylate 3-dehydrogenase (decarboxylating)" RELATED [EC:1.1.1.170]
synonym: "3beta-hydroxy-4beta-methyl-5alpha-cholest-7-ene-4alpha-carboxylate:NAD(P)+ 3-oxidoreductase (decarboxylating)" EXACT []
synonym: "3beta-hydroxy-4beta-methylcholestenecarboxylate 3-dehydrogenase (decarboxylating)" RELATED []
synonym: "3beta-hydroxy-4beta-methylcholestenoate dehydrogenase activity" RELATED []
synonym: "C-3 sterol dehydrogenase (C-4 decarboxylase) activity" RELATED []
synonym: "C-3 sterol dehydrogenase activity" RELATED []
synonym: "sterol 4alpha-carboxylic decarboxylase activity" RELATED []
synonym: "sterol-4-carboxylate 3-dehydrogenase (decarboxylating) activity" RELATED []
synonym: "sterol-4alpha-carboxylate 3-dehydrogenase (decarboxylating)" RELATED []
xref: EC:1.1.1

id: GO:0016229
name: steroid dehydrogenase activity
namespace: molecular_function
def: "Catalysis of an oxidation-reduction (redox) reaction in which one substrate is a sterol derivative." [GOC:mah]
xref: EC:1.1.1
_(this one has direct children in both the "acting on the CH-OH group of donors" (EC:1.1.-.-) and "acting on the CH-CH group of donors" (EC:1.3.-.-) branches)_

**Comment by hdrabkin** [comment]
argh!  Ok, removed these, added some RHEA. 
Need to think about which RHEA GO:0000252 gets (the EC used has 3). WIll add that one when figure it out ; but 3 digit ecs removed.

**Comment by pgaudet** [comment]
@hdrabkin 

I guess you saw that - GO:0000252  has def xref EC:1.1.1.170 - would that be the right xref ? 
(But EC:1.1.1.170 is also linked to 4 GO terms.... ) 

Pascale

**Comment by hdrabkin** [comment]
That's fine for now; EC is mechanism.
Based on the existence of 3 RHEAs, I might expect that EC to be associated with multiple terms

**Comment by hdrabkin** [comment]
eg
GO:0103067, looks almost like 

RHEA:33447 | 4alpha-carboxyl-4beta-methyl-5alpha-cholesta-8,24-dien-3beta-ol  + NADP(+) = 4-methyl-5alpha-cholesta-8,24-dien-3-one + CO2 + NADPH
EXCEPT that this RHEA is specific for NADP, whereas the GO reaction is NAD(P). So this could be split into 2 separate GO ids if we wanted. At the moment I won't give it a RHEA for that reason.

**Comment by hdrabkin** [comment]
Fixed; and found other error

**Comment by sjm41** [comment]
Thanks Harold
