### ISSUE TITLE
EC:2.7.7 xrefs to remove/replace

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19215]
There are 7 GO terms with the partial EC xref EC:2.7.7.
One is correct - suggestions for removals/replacements for the other six are included below.

id: GO:0016779
name: nucleotidyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of a nucleotidyl group to a reactant." [ISBN:0198506732]
xref: EC:2.7.7
**=> keep, correct**

id: GO:0003720
name: telomerase activity
namespace: molecular_function
def: "Catalysis of the reaction: deoxynucleoside triphosphate + DNA(n) = diphosphate + DNA(n+1). Catalyzes extension of the 3'- end of a DNA strand by one deoxynucleotide at a time using an internal RNA template that encodes the telomeric repeat sequence." [GOC:krc]
xref: EC:2.7.7
**=> remove (no obvious replacement)**

id: GO:0004779
name: sulfate adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of an adenylyl group from an adenosine nucleotide (ATP or ADP) to sulfate, forming adenylylsulfate." [GOC:mah, MetaCyc:SULFATE-ADENYLYLTRANS-RXN, MetaCyc:SULFATE-ADENYLYLTRANSFERASE-ADP-RXN]
synonym: "sulphate adenylyltransferase activity" EXACT []
xref: EC:2.7.7
**=> remove (more specific ECs already correctly on the 2 child terms)**

id: GO:0008905
name: mannose-phosphate guanylyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of a phosphate group from GTP or GDP to a mannose molecule." [GOC:mah]
xref: EC:2.7.7
**=> remove (more specific ECs already correctly on the child terms)**

id: GO:0043338
name: CTP:2,3-di-O-geranylgeranyl-sn-glycero-1-phosphate cytidyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: CTP + 2,3-di-O-geranylgeranyl-sn-glycero-1-phosphate = CDP-2,3-di-O-geranylgeranyl-sn-glycerol." [GOC:jl, PMID:10960477]
synonym: "CDP-2,3-di-O-geranylgeranyl-sn-glycerol synthase" BROAD []
xref: EC:2.7.7
**=> replace with 2.7.7.67**

id: GO:0043910
name: ATP:coenzyme F420 adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + factor gamma-F420-2 + H+ = coenzyme F390-A + diphosphate." [GOC:jl, MetaCyc:RXN-9385, PMID:7957247, PMID:8550473]
synonym: "ATP:coenzyme F420 adenyltransferase activity" EXACT []
synonym: "coenzyme F390-A synthetase activity" EXACT []
xref: EC:2.7.7
**=> remove (no obvious replacement)**

id: GO:0052630
name: UDP-N-acetylgalactosamine diphosphorylase activity
namespace: molecular_function
def: "Catalysis of the reaction: UTP + N-acetyl-alpha-D-galactosamine 1-phosphate = diphosphate + UDP-N-acetyl-D-galactosamine." [EC:2.7.7.23]
synonym: "N-acetylgalactosamine 1-phosphate uridylyltransferase" EXACT []
synonym: "N-acetylgalactosamine-1-phosphate uridyltransferase activity" EXACT []
synonym: "UDP-acetylgalactosamine pyrophosphorylase activity" EXACT []
synonym: "UDP-GalNAc pyrophosphorylase activity" EXACT []
synonym: "UDP-N-acetylgalactosamine pyrophosphorylase activity" EXACT []
synonym: "uridine diphosphate-N-acetylgalactosamine pyrophosphorylase activity" EXACT []
synonym: "uridine diphosphoacetylgalactosamine phosphorylase activity" EXACT []
synonym: "uridine diphosphoacetylgalactosamine pyrophosphorylase activity" EXACT []
synonym: "UTP:2-acetamido-2-deoxy-alpha-D-galactose-1-phosphate uridylyltransferase activity" EXACT []
synonym: "UTP:N-acetyl-alpha-D-galactosamine-1-phosphate uridylyltransferase activity" EXACT []
xref: EC:2.7.7
**=> replace with 2.7.7.83**
**=> also replace EC:2.7.7.23 in def - that's for UDP-N-acetyl_glucosamine_ diphosphorylase**

**Comment by hdrabkin** [comment]
All done; added RHEA where I could

**Comment by sjm41** [comment]
Thanks Harold.
