### ISSUE TITLE
New terms signaling receptor ligand precursor processing and cytokine precursor processing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19216]
Discussion with @RLovering and @addiehl 

During the review annotation to cytokine secretion (https://github.com/geneontology/go-annotation/issues/2895), there are missing processes needed to replace some annotations: 

+[Term]
+id: GO:0140448
+name: signaling receptor ligand precursor processing
+namespace: biological_process
+namespace: The cleavage of a peptide bond in a precursor form of a signaling receptor ligand, resulting in the mature (active) form of the ligand. {xref="PMID:29247995"}
+is_a: GO:0016485 ! protein processing
+created_by: pg
+creation_date: 2020-04-03T13:30:04Z

+[Term]
+id: GO:0140447
+name: cytokine precursor processing
+namespace: biological_process
+def: "The cleavage of a peptide bond in a precursor form of a cytokine, resulting in the mature (active) form of the cytokine." [PMID:29247995]
+is_a: GO:0016485 ! protein processing
+created_by: pg
+creation_date: 2020-04-03T12:49:29Z

Thanks, Pascale

**Comment by pgaudet** [comment]
ALSO for 'cytokine precursor processing', added relation
` 'part of some cytokine production'`

**Comment by pgaudet** [comment]
We had totally missed that there was a very similar term, 'signal maturation' - but it was directly under `cellular process`, so hard to spot. 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/4782928/78546706-2e469e80-77fe-11ea-974c-b1b2878effdc.png">

The term has 0 annotations. I'll merge it into the new term 'GO:0140448 signaling receptor ligand precursor processing' and rename it 'signaling receptor ligand precursor maturation'. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also: Moved `peptide hormone processing` under `signaling receptor ligand precursor processing`

**Comment by pgaudet** [comment]
Move 
'patched ligand maturation'
'epidermal growth factor receptor ligand maturation'
under 'signaling receptor ligand precursor processing'

**Comment by pgaudet** [comment]
Move 
'epidermal growth factor receptor ligand maturation'
'patched ligand maturation'

under 'peptide hormone processing'

**Comment by pgaudet** [comment]
@thomaspd 
@vanaukenk 
@ukemi 
Do we need 'signaling receptor ligand precursor processing'/ 'signal maturation' under 'positive regulation of signaling'? It seems to me like it should be 'upstream' (and hence, not in the logical definitions)? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet 
It seems that 'signaling receptor ligand precursor processing'/ 'signal maturation' _could_ be a point of regulation in some cases, but perhaps not always, so therefore shouldn't be housed under regulation in the ontology.  
@ukemi - what do you think?

**Comment by pgaudet** [comment]
OK thanks !
