### ISSUE TITLE
telomere  clustering/tethering function vs process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19229]
1. 
(GO:0090220) chromosome localization to nuclear envelope involved in homologous chromosome segregation 
I 'm not sure that we need this term. I  can't see how it differs from the  descendant
GO:0045141    meiotic telomere clustering
suggest merge.

2. GO:0045141    meiotic telomere clustering
defined
Definition (GO:0045141 GONUTS page)
The cell cycle process in which the dynamic reorganization of telomeres occurs in early meiotic prophase, during which meiotic chromosome ends are gathered in a bouquet arrangement at the inner surface of the nuclear envelope proximal to the spindle pole body. This plays an important role in progression through meiosis and precedes synapsis. PMID:10690419

revise to
Definition (GO:0045141 GONUTS page)
The cell cycle process in which the dynamic reorganization of telomeres occurs in early meiotic prophase, during which meiotic chromosome ends are gathered _together_ in a bouquet arrangement _and attached to_ ~at~ the inner surface of the nuclear envelope proximal to the spindle pole body. This plays an important role in progression through meiosis and precedes synapsis. PMID:10690419

This makes it clear this is the broader process, and includes clustering of the telomeres together, migration and attachment.

3.

meiotic attachment of telomere to nuclear envelope (GO:0070197)
and
meiotic telomere tethering at nuclear periphery (GO:0044821)

are activities (anchoring)
and I think they are saying the same thing (parent child but no siblings)

suggest
These 2 should be obsoletion and replacement by

GONEW MF  "telomere-nuclear envelope anchoring activity"

definition
Interacting selectively and non-covalently with both the telomeric repeat region and the nuclear membrane, in order to establish and maintain the telomere location. 
parent
GO:0043495 protein membrane adaptor activity

4.
GO:0032121    meiotic attachment of telomeric heterochromatin to spindle pole body
attachment is via the repeat region, not the heterochromatin.
All  EXP annotation is from PomBase

This one should also  be obsoleted  its the same thing as  GO:0070197)
and
meiotic telomere tethering at nuclear periphery (GO:0044821)

**Comment by ValWood** [comment]
Hi @pgaudet  when you have time can we look at this. I have community curation sessions   and I can't resolve fully until sorted. Happy to do it on a call some time.

**Comment by pgaudet** [comment]
> 1. 
(GO:0090220) chromosome localization to nuclear envelope involved in homologous chromosome segregation 
I 'm not sure that we need this term. I  can't see how it differs from the  descendant
GO:0045141    meiotic telomere clustering
suggest merge.

OK - (1 annotation MGI)

**Comment by pgaudet** [comment]
#1 and #2 done

**Comment by ValWood** [comment]
> (GO:0090220) chromosome localization to nuclear envelope involved in homologous chromosome segregation
I 'm not sure that we need this term. I can't see how it differs from the descendant
GO:0045141 meiotic telomere clustering
suggest merge.

This should be  a grouping term for  "meiotic telomere clustering"
and the centromere clustering that also occurs in meiosis (or at least that's why I imaging the grouping term is there, possible to mirror the mitotic branch).
meiotic centromere clustering (GO:1990571)
is not under this term, it should be...

The chromosomes do a lot of complicated choreography both during division basically the telomeres and centromeres switch locations in meiotic prometaphase I

It's all bit complicated to describe because we are annotating the gene products involved, but the processes of chromosome movement are quite macro.  We probably haven't got it totally right but it is definitely getting better, and we are keeping track with the (very active ) research.

**Comment by pgaudet** [comment]
@ValWood 
I thought you wanted to merge 'chromosome localization to nuclear envelope involved in homologous chromosome segregation' into 'GO:0045141 meiotic telomere clustering'. 

If I do that I cannot add 'meiotic centromere clustering (GO:1990571)' as a child. 

Please let me know what you want to do. 

Thanks, Pascale

**Comment by ValWood** [comment]
>I thought you wanted to merge 'chromosome localization to nuclear envelope involved in homologous chromosome segregation' into 'GO:0045141 meiotic telomere clustering'.

I think I got that wrong.It was based on the fact that 
GO:0045141 meiotic telomere clustering
was the only descendant.

I think we should keep for grouping

**Comment by pgaudet** [comment]
Do you have a reference for GONEW MF "telomere-nuclear envelope anchoring activity" ?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140473
+name: telomere-nuclear envelope anchor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together the telomeric region of a chromosome and the inner nuclear membrane by interacting with both the telomere and the nuclear membrane, in order to establish and maintain the telomeric location." []
+synonym: "nuclear envelope-telomere anchor activity" EXACT []
+synonym: "telomere-nuclear envelope anchoring activity" EXACT []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19229 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-19T15:44:44Z
+

**Comment by ValWood** [comment]
yes there are lots but use this nice new review
https://pubmed.ncbi.nlm.nih.gov/31635174/
https://pubmed.ncbi.nlm.nih.gov/31635174/#&gid=article-figures&pid=figure-2-uid-1

**Comment by ValWood** [comment]
Hi @pgaudet 
Should this term be in?
Once this is done I can reannotate and work out
https://github.com/geneontology/go-ontology/issues/18981
cheers,
v

**Comment by ValWood** [comment]
I will also be able to figure out what is required here.
I think these 2 tickets are largely overlapping
https://github.com/geneontology/go-ontology/issues/19229
and
#18981

**Comment by ValWood** [comment]
Hi @pgaudet 
I still don't see this term.
 +id: GO:0140473

should I?

**Comment by pgaudet** [comment]
I've added the term again. I'm not sure what I did with this ticket - I need to go through al the actions again.

**Comment by ValWood** [comment]
I used GO:0140473 so closing this. I have a ticket to check some telomere tethering https://github.com/geneontology/go-ontology/issues/18981 . Any problems when I di so I'll open new.
