### ISSUE TITLE
Merge GO:0038005 peptide bond cleavage involved in epidermal growth factor receptor ligand maturation	

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19224]
Hi @hattrill 
The term `GO:0038005 peptide bond cleavage involved in epidermal growth factor receptor ligand maturation`only has flybase annotations. 

It sounds like a MF; I'd like to merge it into `GO:0038004 epidermal growth factor receptor ligand maturation`; is that OK with you ? 

I looked with the Matrix tool and all 4 proteins annotated to GO:0038005 peptide bond cleavage involved in epidermal growth factor receptor ligand maturation are also annotated to peptidase activity or a child. 

<img width="882" alt="image" src="https://user-images.githubusercontent.com/4782928/78544119-f3426c00-77f9-11ea-94e6-28fea478eb56.png">

Thanks, Pascale

**Comment by hattrill** [comment]
That sounds fine to me. I will review these annotations - I expect that they are redundantly annotated.

**Comment by pgaudet** [comment]
Great, thanks for the quick reply. I saved your annotations here just in case: 
https://docs.google.com/spreadsheets/d/1ErG1I5y7nETwF3F7VI1Lu0ZkfbVSJbYUJD7dPV9aZeo/edit#gid=0

**Comment by hattrill** [comment]
All done.
