### ISSUE TITLE
ntr centromere nuclear envelope anchor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19227]
ntr centromere-nuclear envelope anchor activity
synonyms
centromere nuclear membrane anchor
centromere nuclear envelope anchor
kinetochore nuclear envelope anchor 
centromere nuclear envelope adaptor
kinetochore nuclear envelope adaptor
related centromere clustering
(I made the synonyms unhyphenated because the   searchers do not seem to cope well with hyphens)

parent
GO:0043495   protein membrane adaptor activity

@pgaudet  did n't we hyphenate this recently and make thee definition clearer wrt complexes and organelles?

definition
Interacting selectively and non-covalently with both the centromere/kinetochore complex and the nuclear membrane, in order to establish and maintain the  centromere/kinetochore location.

reference PMID: 31635174   review of nuclear membrane adaptors)

**Comment by ValWood** [comment]
This activity is part of this process:


GO:0072766   centromere clustering at the mitotic nuclear envelope
A cellular localization process in which kinetochores/centromeres are coupled together at the nuclear periphery. This process is responsible for the Rabl-like configuration of chromosomes in the interphase nuclei. In fission yeast this occurs at a location near the old mitotic spindle pole body. PMID:21965289 PMID:23166349

This term is still required because the clustering is a broader multi step, partly  microtubule based process.  We should revise the definition of this process as follows:

A cellular localization process in which kinetochores/centromeres are coupled ~together~  _to each other  ~at~ _and to_ the nuclear periphery _close to the spindle pole body/centrosome. This process _involves the interphase microtubule cytoskeleton, and nuclear terthering factors and_  is  responsible for the Rabl-like configuration of chromosomes in the interphase nuclei.  ~In fission yeast this occurs at a location near the old mitotic spindle pole body~. PMID:21965289 PMID:23166349

**Comment by ValWood** [comment]
Definition scope is wrong too:

rabl configuration | related
centromere-SPB clustering | ~related~ broad 
kinetochore clustering at SPB | ~related~ broad 
kinetochore clustering at spindle pole body | ~related~ broad 
kinetochore localization at spindle pole body | ~related~ broad 
centromere clustering at the nuclear periphery | ~related~ broad 
kinetochore clustering at the old mitotic spindle pole body | ~related~ exact

only the mitotic term is exact. The others are broad.

**Comment by pgaudet** [comment]
We hyphenated as follows: spindle pole body-nuclear membrane anchor activity
I suppose we need the opposite too (nuclear membrane-spindle pole body anchor activity)

**Comment by pgaudet** [comment]
@ValWood 
I create the term, using **inner** nuclear envelope

+[Term]
+id: GO:0140449
+name: centromere-inner nuclear envelope anchor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together the centromeric region of a chromosome and the inner nuclear membrane by interacting with both the centromere/kinetochore complex and the nuclear membrane, in order to establish and maintain the centromere/kinetochore location." [PMID:31635174]
+synonym: "centromere nuclear envelope anchor activity" EXACT []
+synonym: "centromere-nuclear envelope anchor activity" EXACT []
+synonym: "chromosome, centromeric region-nuclear envelope anchor activity" EXACT []
+synonym: "nuclear envelope-centromere anchor activity" EXACT []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+relationship: part_of GO:0072766 ! centromere clustering at the mitotic interphase nuclear envelope
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19227 xsd:anyURI
+created_by: pg
+creation_date: 2020-04-07T06:27:08Z


Let me know if that's OK 

Thanks, Pascale

**Comment by pgaudet** [comment]
On that topic, there are two regulation children with no annotations: 

* GO:1905113 positive regulation of centromere clustering at the mitotic nuclear envelope
*  GO:1905112 regulation of centromere clustering at the mitotic nuclear envelope 

Is this really a regulated process ? 

Thanks, Pascale

**Comment by ValWood** [comment]
> Is this really a regulated process ?
Probably not, but not sure. I don'\t remember requesting them (Might be term genie overkill?).
Happy for them to go.

**Comment by ValWood** [comment]
It probably is regulated. Most of the centromere movement and localization stuff is highly regulated. But I don't think we should add things until we are sure ;)

**Comment by ValWood** [comment]
> I create the term, using inner nuclear envelope

I would keep it as nuclear envelope. 
Although the centromere is positioned at the nuclear inner membrane the LINC complex spans both membranes (also acts as a mechanosensor to the cytoplasmic cytoskeleton).

Some of the other anchors ( the heterochromatin ones for example), are confined to the inner membrane

**Comment by pgaudet** [comment]
> I would keep it as nuclear envelope.

OK, changed. 


> It probably is regulated. Most of the centromere movement and localization stuff is highly regulated. 

Paper cited in the term definition is PMID:22375062
This paper is annotated with 'positive regulation of attachment of mitotic spindle microtubules to kinetochore' 
Do you want to add  'positive regulation of centromere clustering at the mitotic nuclear envelope' ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
    GO:1905113 positive regulation of centromere clustering at the mitotic nuclear envelope
    GO:1905112 regulation of centromere clustering at the mitotic nuclear envelope

The reason for obsoletion is that this represents a phenotype. There are no annotations, no mappings, and those terms are not present in any subsets. 

You can comment in the ticket:
https://github.com/geneontology/go-ontology/issues/19227

We are opening a comment period for this proposed obsoletion. We’d like to proceed with the obsoletion this term on April 10th, 2020. Unless objections are received by April 10th, 2020, we will assume that you agree to this change.

Thanks, Pascale
