### ISSUE TITLE
New Complex term: counting factor complex

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#19220]
Dicty secretes a counting factor consisting of 4 identified proteins. This counting factor limits group size during aggregation so that fruiting bodies do not get too large and fall over. PMID:10444594, PMID:12117815, PMID:12912898, PMID:16963635.
A nice review: MID:18426773

@bmeldal is also creating the complex in IntAct.

GO new: counting factor complex
is_a GO:0032991 protein-containing complex
cellular_component
Synonyms: CF complex
Definition: A secreted multiprotein complex composed of 4 proteins, regulating group size during aggregation in cooperative development. An example of this process is found in Dictyostelium discoideum. PMID:18426773

Thanks!
Petra

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140451
+name: counting factor complex
+namespace: cellular_component
+def: "A secreted multiprotein complex composed of 4 proteins, regulating group size during aggregation in cooperative development. An example of this complex is found in Dictyostelium discoideum." [PMID:10444594, PMID:12117815, PMID:12912898, PMID:16963635, PMID:18426773]
+is_a: GO:0032991 ! protein-containing complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19220 xsd:anyURI
+created_by: pg
+creation_date: 2020-04-15T08:52:26Z

**Comment by pfey03** [comment]
@pgaudet many thanks!
