### ISSUE TITLE
obsolete: signal transduction involved in regulation of aerobic respiration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19249]
obsolete: signal transduction involved in regulation of aerobic respiration 

This was requested by PomBAse via term genie, but it is clearly 

GO:0010619 | adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway

signal transduction involved in regulation of aerobic respiration

all EXP pombe except one mouse

**Comment by pgaudet** [comment]
*  GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway
has 3 children: 
* GO:0010619 adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway
* GO:0110034 negative regulation of adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway
*  GO:0110033 regulation of adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway 

All  EXPannotations are pombase so I'll obsolete.

**Comment by ValWood** [comment]
Don't we want to  keep this one

GO:0010619 | adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway

(I think this was the term name which came out of the signalling meeting wasn't it ?)

just to get rid of the 

"involved in regulation of aerobic respiration" terms

**Comment by pgaudet** [comment]
SORRY I got confused by the ID

**Comment by ValWood** [comment]
I didn't put the  title into the  requrest

"obsolete: signal transduction involved in regulation of aerobic respiration"

Possibly some weeding can be done in the cAMP signalling but it is pretty OK for now

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete
 GO:1903759 signal transduction involved in regulation of aerobic respiration

The reason for obsoletion is that this represents a GO-CAM model. 

There are 4 annotations to this term, one by UniProtKB and 3 by PomBase. 

There are no mappings to those terms; those terms are not present in any subsets.

Thanks, Pascale
