### ISSUE TITLE
changes to slims to replace 'cofactor metabolic process' (init by PomBase)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19253]
Please remove
cofactor metabolic process (GO:0051186)
from the Pombase slim set

and add instead
ubiquinone biosynthetic process (GO:0006744)) 
iron-sulfur cluster assembly
secondary metabolic process (GO:0019748))
tetrapyrrole metabolic process (GO:0033013)
pteridine-containing compound biosynthetic process (GO:0042559)

thanks

val

**Comment by ValWood** [comment]
Note that it is not possible to cover cofactor metabolic process in precision slims without these additional terms.

**Comment by deustp01** [comment]
That's effectively the Reactome patch - without the grouping term, tag the child processes according to the chemicals involved.

**Comment by ValWood** [comment]
Our aim is to broadly but usefully  slim everything which has a process. Many GPs were annotated to cofactor/coenzyme and plus other terms (lipid, carbohydrate metabolism etc.), i.e they would be in matrix intersections.

 The terms I added  were smaller gene sets than I would like  (making the slim longer) but the other option was to go with terms like
heterocycle metabolic process (GO:0046483)
which had too many annotations  (1551 for pombe), and wasn't informative.

**Comment by ValWood** [comment]
At the same time could

GO:0110134    meiotic drive

be added to the Pom Base slim too?

Thanks

**Comment by ValWood** [comment]
Hi Karen,

The removal of the cofactor term will blow  big hole in our slim coverage. Could these  changes be implemented ?
(Or maybe you didn't do this one yet?)

Thanks,

Val

**Comment by krchristie** [comment]
I'm working on it right now. I started doing it yesterday, but had a problem that I couldn't figure out what I missed, so breaking it into even smaller pieces today.

**Comment by krchristie** [comment]
combining all requested changes into one comment so I don't forget the extra one. @ValWood - please add a comment if there's anything else you want for the pombe slim since I hope to do this today.

> Please remove
> cofactor metabolic process (GO:0051186)
> from the Pombase slim set
> 
> and add instead
> ubiquinone biosynthetic process (GO:0006744))
> iron-sulfur cluster assembly
> secondary metabolic process (GO:0019748))
> tetrapyrrole metabolic process (GO:0033013)
> pteridine-containing compound biosynthetic process (GO:0042559)

> At the same time could this term be added to the Pom Base slim too?
> 
> GO:0110134 meiotic drive

**Comment by ValWood** [comment]
That's it , thanks

**Comment by krchristie** [comment]
The term `cofactor metabolic process` is also in these slims listed below. I'm trying to tag appropriate people to check if what Val has requested for the pombe slim is something others would like for their slims also. 
- goslim_chembl
- goslim_drosophila @hattrill 
- goslim_generic
- goslim_pir
- goslim_yeast @srengel 

@pgaudet - can you help me tag people for the other three slims.

**Comment by krchristie** [comment]
@ValWood - your changes are done. I reopened as it might make sense to make this a broader ticket for similar subset changes for other groups affected by this change.

**Comment by ValWood** [comment]
OK, thanks, I can check ours tomorrow.

Val

**Comment by hattrill** [comment]
Ref: https://github.com/geneontology/go-ontology/issues/19243

**Comment by hattrill** [comment]
Hi @krchristie 
We will not replace this term in our slim goslim_drosophila so if you can remove it from our set, that would be great.

**Comment by krchristie** [comment]
> Hi @krchristie
> We will not replace this term in our slim goslim_drosophila so if you can remove it from our set, that would be great.

Hi @hattrill - I've already removed it from everyone's slim as part of the obsoletion process. Thanks for letting me know you don't want any replacement.

**Comment by krchristie** [comment]
Since no one else has indicated that they want a replacement for `cofactor metabolic process` in their slim, I'm going to close this ticket.
