### ISSUE TITLE
Add Xenopus Anatomy Ontology (XAO) to go-lego for use in Noctua.

### ISSUE THREAD

**Issue by malcolmfisher103** [geneontology/go-ontology#19259]
We at Xenbase would like to have the Xenopus Anatomy Ontology (XAO) incorporated into the 'go-lego.owl'  for use in Noctua. I assume this will require a similar reconciliation process to the one the ZFA underwent geneontology/noctua#541. 

The XAO is available at http://purl.obolibrary.org/obo/xao.owl.

**Comment by kltm** [comment]
Pinging @balhoff @ukemi @goodb

**Comment by balhoff** [comment]
@malcolmfisher103 the extent of the integration we would be doing right now is:
- import XAO in go-lego
- add a mapping axiom from 'Xenopus anatomical entity' to CARO 'anatomical entity'
- map XAO cell to CL cell
  - **question:** would it be valid to put all XAO cells under CL ['native cell'](http://purl.obolibrary.org/obo/CL_0000003)

These high level mappings are sufficient to hook XAO into autocomplete and schema validation. It would nice for potential downstream applications if there were comprehensive mapping from the species-specific ontologies to Uberon, but this has required too much effort.

**Comment by malcolmfisher103** [comment]
HI @balhoff, After a brief check I don't see any problem with putting the XAO cells under 'native cell' but I've sent an email to Erik Segerdell to ask him to weigh in as our XAO developer.

**Comment by balhoff** [comment]
@malcolmfisher103 it will take a few days to appear in Noctua.

**Comment by kltm** [comment]
https://github.com/geneontology/neo/issues/59
