### ISSUE TITLE
obsoletion, sterol esterification terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19255]
GO:NEW
lanosterol esterification
Biological Process

Definition 
A lipid modification process in which a ergosterol ester is formed by the combination of a carboxylic acid (often a fatty acid) and a ergosterol molecule.
Acknowledgement

GO:NEW
ergosterol esterification
Biological Process

Definition 
A lipid modification process in which a ergosterol ester is formed by the combination of a carboxylic acid (often a fatty acid) and a ergosterol molecule.
Acknowledgement

Parent GO:0034434  sterol esterification

Ref

From the paper I am reading
cells lacking Are1p (which mainly esterifies lanosterol [5], but has limited activity in aerobic conditions) and Are2p (which mainly esterifies ergosterol [5])

5 is:
Zweytick D, Leitner E, Kohlwein SD, Yu C, Rothblatt J, Daum G. Contribution of Are1p and Are2p to steryl ester synthesis in the yeast saccharomyces cerevisiae. European Journal of Biochemistry. 2000; 267:1075–1082. [PubMed: 10672016]

**Comment by ValWood** [comment]
You could add F-P links to these

GO:0034738    lanosterol O-acyltransferase activity | is_a
GO:0034737    ergosterol O-acyltransferase activity | is_a
GO:0034736    cholesterol O-acyltransferase activity

**Comment by ValWood** [comment]
Actually, maybe we shouldn't have
GO:0034434 sterol esterification
if it's single step, it's a function in the process ontology?

**Comment by deustp01** [comment]
Would multiple parallel (rather than sequential) reactions be OK, as there are multiple sterols and multiple acyl groups, so many ways to esterify, even though any one esterification takes a single step?

**Comment by alanbridge** [comment]
Sounds more like a reaction? Here's a couple of examples (with acyl-CoA as donor, which is probably one of the most likely, but perhaps other donors are possible too?)

an acyl-CoA + ergosterol = CoA + ergosteryl ester
https://www.rhea-db.org/reaction?id=33483

an acyl-CoA + lanosterol = CoA + lanosteryl ester
https://www.rhea-db.org/reaction?id=33479

**Comment by ValWood** [comment]
>Would multiple parallel (rather than sequential) reactions be OK, as there are multiple sterols and multiple acyl groups, so many ways to esterify, even though any one esterification takes a single step?

Good point. Maybe a single esterification grouping term would. be sufficient


BP GO:0034434 sterol esterification
-- MF GO:0034738    lanosterol O-acyltransferase activity | is_a
-- MF GO:0034737    ergosterol O-acyltransferase activity | is_a
-- MF GO:0034736    cholesterol O-acyltransferase activity

If we did this, then to be consistent we would merge 
GO:0034435 cholesterol esterification into GO:0034434 sterol esterification



the advantage of the complete way is that  the yeast annotation  to 
GO:0034737    ergosterol O-acyltransferase activity
would become annotated to "ergosterol metabolism" and I would not need to make concurrent annotations.


but  GO:0034737    ergosterol O-acyltransferase activity could also have an F-P link to 
"ergosterol metabolism" so that is solvable too.
and GO:0034736    cholesterol O-acyltransferase activity part_of to cholesterol metabolic process.

**Comment by ValWood** [comment]
@hdrabkin  this can probably close?  Can do MF involved in BP

**Comment by hdrabkin** [comment]
Yes, the process terms you suggested do seem to all be one step keyed to the mf term?

**Comment by hdrabkin** [comment]
and merge
GO:0034435 cholesterol esterification into GO:0034434 sterol esterification

**Comment by hdrabkin** [comment]
BP GO:0034434 sterol esterification is stil a single step yes?

**Comment by hdrabkin** [comment]
'cholesterol esterification'
'negative regulation of cholesterol esterification'
'positive regulation of cholesterol esterification'
'regulation of cholesterol esterification'
'steroid esterification'
'sterol esterification'

**Comment by pgaudet** [comment]
Lets also obsolete     

- [ ] GO:0034207 steroid acetylation: 0 EXP
- [ ] GO:0034209 sterol acetylation 1 EXP
- [ ] GO:0034208 steroid deacetylation:  0 EXP
- [ ] GO:0034210 sterol deacetylation: 1 EXP

I added the 2 annotations to the spreadsheet

https://docs.google.com/spreadsheets/d/1nvfCX3MejcsA_OuUFH113Xlc8MOpoRB7ZDMpkwuBFkk/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Forgot to mention, the annotations are by SGD @srengel
