### ISSUE TITLE
Merge 'x biosynthesis' into 'regulation of x production'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19256]
Item 4 in #19115 

For reference - annotations as of May 15, 2020, downloaded from QuickGO, are attached. 

[biosynthesis-annotationstats.xlsx](https://github.com/geneontology/go-ontology/files/4634021/biosynthesis-annotationstats.xlsx)

**Comment by pgaudet** [comment]
Started to change labels for some terms (those did not have a 'production' equivalent to merge into): 


Term | Change label
-- | --
'regulation of CD24 biosynthetic process' | regulation of CD24 production'
'positive regulation of CD24 biosynthetic   process' | positive regulation of CD24 production'
'regulation of CD4 biosynthetic process' | regulation of CD4 production'
'negative regulation of CD4 biosynthetic   process' | negative regulation of CD4 production'
'positive regulation of CD4 biosynthetic   process' | positive regulation of CD4 production'
'regulation of CD80 biosynthetic process' | regulation of CD80 production'
'negative regulation of CD80 biosynthetic   process' | negative regulation of CD80 production'
'positive regulation of CD80 biosynthetic   process' | positive regulation of CD80 production'
'regulation of CD86 biosynthetic process' | regulation of CD86 production'
'negative regulation of CD86 biosynthetic   process' | negative regulation of CD86 production'
'positive regulation of CD86 biosynthetic   process' | positive regulation of CD86 production'
regulation of FasL biosynthetic process' | regulation of FasL production'
'negative regulation of FasL biosynthetic   process' | negative regulation of FasL production'
'positive regulation of FasL biosynthetic   process' | positive regulation of FasL production'


Question: We had said that only ‘regulation of production’ should be kept, not ‘production', if I recall correctly. But that would mean we loose the logical definition. 

Or we keep them as ‘Do not annotate’. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@RLovering Shoudl I also change 'amyloid precursor protein biosynthetic process' and regulation children to 'production'?

**Comment by RLovering** [comment]
Hi Pascale

sure, and I think that the do not annotate to the production term needs to be applied. there is only 1 annotation to the 'term' and I think this needs to be changed to regulation of production. 

Im assuming you are not going to change the metabolism/catabolism terms which are required

Thanks

Ruth

**Comment by pgaudet** [comment]
> Im assuming you are not going to change the metabolism/catabolism terms which are required

No - although presumably only catabolism is required ? Anyway, we can look at that later. 

Thanks, Pascale

**Comment by pgaudet** [comment]
We should also discuss definitions: 

We have for example: 
GO:0042253 'granulocyte macrophage colony-stimulating factor biosynthetic process' "The chemical reactions and pathways resulting in the formation of granulocyte macrophage colony-stimulating factor, cytokines that act in hemopoiesis by controlling the production, differentiation, and function of two related white cell populations, granulocytes and monocytes-macrophages."

and GO:2000559 regulation of CD24 biosynthetic process: Any process that modulates the frequency, rate or extent of CD24 biosynthetic process.


I dont think I can just change 'biosynthetic process' to 'production', it would be nice to describe what we mean in more detail.

**Comment by pgaudet** [comment]
Question for GO editors: 
‘regulation of production’ vs production: 

We dont need the 'production' terms for annotation, only for the logical definition of the regulation terms. 

Should I keep the 'production' term, and add a ‘Do not annotate’ tag, or use some relation like 
'regulates level of x' instead ? Thanks, Pascale

**Comment by pgaudet** [comment]
I think this is all done ! I attach the [list](url
[biosynthesis_production-merges.xlsx](https://github.com/geneontology/go-ontology/files/5401533/biosynthesis_production-merges.xlsx)
) of all changes made.
