### ISSUE TITLE
Produce a go-lego.json ontology product

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-ontology#19265]
In https://github.com/biolink/ontobio we use the [go.json](http://snapshot.geneontology.org/ontology/go.json) in http://snapshot.geneontology.org/ontology/index.html. 

For https://github.com/biolink/ontobio/issues/432, we are prodoucing go-cam models from GPADs, and we ideally would have the whole merged import ontology. For example, @dustine32 requires RO, in addition to GO. Having the whole ontology as a JSON would be great. 

Can we create a JSON of go-lego for ontobio and the pipeline?

**Comment by ukemi** [comment]
Hi @dougli1sqrd, to whom should this be assigned?

**Comment by balhoff** [comment]
We may as well produce `go-gaf.json` as well. I can add these.

**Comment by balhoff** [comment]
I am going to hold off on this until @dustine32's more efficient JSON export is available in a ROBOT release (https://github.com/ontodev/robot/pull/671).

**Comment by balhoff** [comment]
@dougli1sqrd the published final version of these ontologies are merged these days. Do you still need the JSON format as well?

**Comment by balhoff** [comment]
I don't believe this is needed anymore.
