### ISSUE TITLE
NTR: axonemal basal plate assembly

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#19262]
Hi,
Can I request a GO term for axonemal basal plate assembly please?

Accession: GO:xxxxxx
Name: axonemal basal plate assembly
Ontology: biological_process
Synonyms: axonemal basal plate formation, axoneme basal plate assembly, basal plate assembly
Definition: The aggregation, arrangement and bonding together of a set of components to form an axonemal basal plate.
is_a: GO:0035082! axoneme assembly
Source: GO:0097541, PMID:23352055, PMID:30810527

Thanks & best wishes,
Achchuthan

**Comment by krchristie** [comment]
This won't be 
>  is_a: GO:0035082! axoneme assembly

because the basal plate isn't a type of axoneme, but rather a part_of axoneme assembly

**Comment by Achchuthan** [comment]
Hi @krchristie 
Thanks for your correction. It makes sense to me.

Best wishes,
Achchuthan
