### ISSUE TITLE
NTR: Smp focus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19263]
NTR Smp focus
Definition
A DNA-binding  ribonucleoprotein complex that contains a lncRNA complementary to the bound chromosomal locus  and is involved in the tethering  homologous chromosomes together during chromosome pairing at meiotic prophase I.

Synonym: Smp dot

References:
Meiosis-specific noncoding RNA mediates robust pairing of homologous chromosomes in meiosis.
Ding DQ, Okamasa K, Yamane M, Tsutsumi C, Haraguchi T, Yamamoto M, Hiraoka Y.
Science. 2012 May 11;336(6082):732-6. doi: 10.1126/science.1219518.
PMID: 22582262

Chromosome-associated RNA-protein complexes promote pairing of homologous chromosomes during meiosis in Schizosaccharomyces pombe.
Ding DQ, Okamasa K, Katou Y, Oya E, Nakayama JI, Chikashige Y, Shirahige K, Haraguchi T, Hiraoka Y.
Nat Commun. 2019 Dec 6;10(1):5598. doi: 10.1038/s41467-019-13609-0.
PMID: 31811152

**Comment by ValWood** [comment]
Also, could the parentage be "nuclear chromosome"

**Comment by ValWood** [comment]
Might be useful for the logical def when added:

https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/483

**Comment by ValWood** [comment]
Fixed the above request.  This is a different focus to the mei2 focus, although mei2 also binds to sme2.

**Comment by pgaudet** [comment]
Hi @ValWood 

Can you be more specific about the composition of that complex ? 
'contains a lncRNA' - what else ? 

Thanks, Pascale

**Comment by ValWood** [comment]
well its an assortment of RNA binding proteins...

Systematic ID | Gene name | Product description
-- | -- | --
SPBC3B9.11c | ctf1 | mRNA cleavage and polyadenylation factor complex RNA-binding subunit Ctf1
SPAC3H8.09c | nab3 | poly(A) binding protein Nab3 (predicted)
SPBC16E9.12c | pab2 | poly(A) binding protein Pab2
SPAC4G9.04c | pcf11 | mRNA cleavage and polyadenylation factor RNA binding subunit Pcf11
SPBC646.04 | pla1 | poly(A) polymerase Pla1
SPAC29B12.06c | rcd1 | CCR4-Not complex RNA-binding protein subunit Rcd1
SPBC337.03 | rhn1 | RNA polymerase II transcription termination factor homolog
SPBC902.04 | rmn1 | RNA-binding protein
SPAC644.16 | rna15 | RNA-binding protein Rna15
SPAC222.09 | seb1 | RNA-binding and 3'-end processing protein Seb1
SPNCRNA.103 | sme2 | meiRNA sme2

A selection of RNA binding proteins (mainly with other  known. roles)
referred to collectively as  "Smp proteins"

"These results indicate that Smp proteins mediate the
chromosomal accumulation of sme2 RNA dots, which correlates
with robust pairing"

We probably don't want to list them all?  There are 3 complexes  lncRNA is different in each one (each complementary to its chromosomal locus) , and I am not sure that every protein is present in each complex, so I decided to 'lump' for now as a single entity until more info is available.

A nice review appeared today

Phase separation drives pairing of homologous chromosomes.
  | Hiraoka Y.
  | Curr Genet. 2020 Apr 13. doi: 10.1007/s00294-020-01077-9. [Epub ahead of print] Review.
  | PMID: 32285141

it actually  reviews a lot of new cool stuff being discovered about meiotic chromosomes that I am trying to keep up with....
figure 3 refers to this work
https://link.springer.com/article/10.1007/s00294-020-01077-9/figures/3
