### ISSUE TITLE
obsolete GO:0044035    multi-organism catabolic process branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19282]
GO:0044035    multi-organism catabolic process

Definition (GO:0044035 GONUTS page)
A catabolic process - chemical reactions and pathways resulting in the breakdown of substances - which involves more than one organism.

how can this involve more than one organism?

**Comment by mah11** [comment]
I'm neutral on whether it's worth keeping the branch, but it's for cases where one organism breaks down substances in another organism, e.g. one eating another's cell wall.

**Comment by ValWood** [comment]
it's under "interaction between species" which is where I expected to see

GO:0052353    catabolism by host of symbiont carbohydrate
and the inverse

but we don't class "interaction between species' as a multi organism process, so I wonder what the criteria is?

**Comment by ValWood** [comment]
ah  I get it.
