### ISSUE TITLE
NTR - parts of GO:0039718 double membrane vesicle viral factory

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#19287]
To annotate steps in the replication of SARS-CoV-1 and -2 corona viruses, could we have terms for parts of the double membrane vesicle

GO:new1 - outer membrane of double membrane vesicle viral factory - the outer one of the two endoplasmic reticulum-derived lipid bilayer membranes that bound a double membrane vesicle viral factory. 
GO:new2 - inner membrane of double membrane vesicle viral factory - the inner one of the two endoplasmic reticulum-derived lipid bilayer membranes that bound a double membrane vesicle viral factory. 
GO:new3 - lumen of double membrane vesicle viral factory - the space surrounded by the inner membrane of a double membrane vesicle viral factory.

PMID:22440839, especially Figure 1c, is a good reference for all three terms.

Beyond asserting that each of these is a part_of GO:0039718, I'm stuck on parentage, partly because of my confusion discussed in ticket #19286 

Thanks

**Comment by ukemi** [comment]
I'm going to go ahead and make the first two host cell membranes and the third one a host cell cytoplasm part (modeled on host cell endosomal lumen). At least this will get them in there for you to use.

**Comment by ukemi** [comment]
Also added the membrane term and made outer and inner children. I tried to do some fancy stuff with spatial relations, but couldn't get the inferences to work out. So I just added the terms with asserted relationships.
