### ISSUE TITLE
Review impact of CHEBI role hierarchy on GO classification

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#19296]
Create version of chebi_import.owl without GOCHE logical definitions. Create reasoned diff compared to current chebi_import.

**Comment by balhoff** [comment]
Here is the diff: https://docs.google.com/document/d/15aP0D1tRB5DwpiGEkj-4pgQvjCE0CjLVYRR9ee3WBnE/edit#

**Comment by krchristie** [comment]
@balhoff - I think this is done so I'm going to close it. Reopen it with details of what is needed if you need any further input.
