### ISSUE TITLE
Merge GO:0070924 heterochromatin assembly involved in chromatin silencing by small RNA + remove chromatin silencing parent

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19306]
* GO:0070924 heterochromatin assembly involved in chromatin silencing by small RNA - 13 OK, checked by @ValWood 

1. Change label to 'heterochromatin assembly involved by small RNA' 
2. Merge into GO:0031048  chromatin silencing by small RNA - 24 EXP

**Comment by pgaudet** [comment]
Remove chromatin silencing parent from 
* 
* 
*

So that we can review/merge/obsolete chromatin silencing and children more easily (since 'chromatin silencing' is a phenotype)

**Comment by mah11** [comment]
> Change label to 'heterochromatin assembly involved by small RNA'

this is a typo, right? it doesn't make sense ...

**Comment by pgaudet** [comment]
Right !!! It's 'heterochromatin assembly by small RNA' 

Thanks for noting this. 

Pascale
