### ISSUE TITLE
Obsoletion notice: GO:0035392 maintenance of chromatin silencing at telomere  and GO:0035391 maintenance of chromatin silencing at silent mating-type cassette

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19301]
Dear all, 

The proposal has been made to obsolete: 
* GO:0035391 maintenance of chromatin silencing at silent mating-type cassette: 0 annotations
* GO:0035392 maintenance of chromatin silencing at telomere: 6 EXP annotations
** 5 SGD (can probably be replaced by GO:0034398  telomere tethering at nuclear periphery)
** 1 FlyBase (NOT; can be deleted)

The reason for obsoletion is that chromatin silencing is a phenotype. The term 'maintenance of chromatin silencing at telomere' has been misused and should be reannotated. 

These terms are not present in any subsets; there are no mappings to those terms. 

You can comment in the ticket:
https://github.com/geneontology/go-ontology/issues/19301

We are opening a comment period for this proposed obsoletion. We’d like to proceed with the obsoletion this term on April 27th, 2020. Unless objections are received by April 27th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Look into GO:0140276 pericentric heterochromatin maintenance
had been merged into heterochromatin maintenance and restored as a separate term

Not sure this term is necessary ?

**Comment by pgaudet** [comment]
@colinlog

**Comment by hattrill** [comment]
FlyBase done.

**Comment by pgaudet** [comment]
Annotation review https://github.com/geneontology/go-annotation/issues/2947

**Comment by pgaudet** [comment]
pericentric heterochromatin maintenance discussion (incorrectly in the 'announcement' ticket): https://github.com/geneontology/go-announcements/issues/136

@ValWood 
>IIRC possibly some of the chaperones are post-assembly and involved only in maintenance?

> the term seems to be originally created for pombe, http://europepmc.org/article/MED/21289066
but we did not need it here.

> It currently has no annotation so maybe obsoletion ?

@colinlog 

> Yes, definitely a phenotype. If anything, that histone acetyltransferase is
an antagonist of pericentric heterochromatin formation... most likely by
promoting transcription of the pars set of genes, but who knows... it is also known to antagonise  telomeric heterochromatin formation, in the sense that the mutant makes heterochromatin more easily. No evidence that this is a 'specific' biological process in the wild type though.

----


So I will obsolete.
