### ISSUE TITLE
obsolete GO:0098649 response to peptidyl-dipeptidase A inhibitor

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#19310]
No annotations: http://amigo.geneontology.org/amigo/term/GO:0098649

```
id: GO:0098649
name: response to peptidyl-dipeptidase A inhibitor
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a peptidyl-dipeptidase A inhibitor stimulus." [GOC:dos]
synonym: "response to ACE inhibitor" NARROW []
synonym: "response to angiotensin-converting enzyme inhibitor" NARROW []
intersection_of: GO:0050896 ! response to stimulus
intersection_of: has_input GOCHE:35457 ! substance with EC 3.4.15.1 (peptidyl-dipeptidase A) inhibitor role
```

I suspect this has been used for non-GO annotation at EBI, do you recall @dosumis?

**Comment by krchristie** [comment]
I think there are 4 of these terms that use a very specific role for some kind of inhibitor, definitely one for aromatase inhibitor, and one I think for terminal transferase inhibitor. I am quite suspicious that these do not represent anything biologically normal, but a response to an synthetic drug that would never be encountered in normal biology.

They're a bit low down on my priority list though as there is only a single use of each of these very specific roles, and the terms aren't used much, if at all, for annotations.

**Comment by krchristie** [comment]
6/30/2020
- AmiGO: 0 annotations
- QuickGO: 0 annotations

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete GO:0098649 response to peptidyl-dipeptidase A inhibitor. The reason for obsoletion is that this term is unlikely to represent anything biologically normal, but a response to an synthetic drug that would never be encountered in normal biology.

There are no annotations, no mappings to this term. This term is not present in any subsets.

You can comment on the ticket here:
geneontology/go-ontology#19310

Thanks, Pascale
