### ISSUE TITLE
NCBI taxonomy in go-gaf has unsatisfiable classes

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#19316]
This is currently blocking the pipeline. I think the issue is that there was just recently a release of NCBITaxon, and go-gaf directly loads `http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl` off the web. This can be out of sync with the NCBITaxon import module in go-plus.

cc @kltm

**Comment by balhoff** [comment]
Fixed by #19317.

**Comment by kltm** [comment]
Cheers!
