### ISSUE TITLE
NTR: L-serine-phosphatidylcholine phosphatidyltransferase activity 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19311]
From PMID: 19014349:
PS (phosphatidylserine) synthesis in mammalian cells occurs through the exchange of L-serine with the choline moiety of PC (phosphatidylcholine) or the ethanolamine moiety of PE (phosphatidylethanolamine) [3–5], whereas in bacteria and yeast, PS is synthesized from CDP-diacylglycerol and L-serine [6,7]. The serine base exchange in mammalian cells is catalysed by PSS1 (PS synthase 1) and PSS2 [3–5], which, respectively, are responsible for the conversion of PC and PE into PS in intact cells [8].

Looks like we have the term for the (mammalian) activity using the phosphatidylethanolamine substrate:
id: GO:0106245
name: L-serine-phosphatidylethanolamine phosphatidyltransferase activity
def: "Catalysis of the reaction: L-1-phosphatidylethanolamine + L-serine <=> L-1-phosphatidylserine + ethanolamine." [PMID:19014349, PMID:31869331, RHEA:27606]
xref: EC:2.7.8.29
xref: RHEA:27606

And we have the term for the (bacterial/yeast) activity using CDP-diacylglycerol:
id: GO:0003882
name: CDP-diacylglycerol-serine O-phosphatidyltransferase activity
def: "Catalysis of the reaction: CDP-diacylglycerol + L-serine = CMP + O-sn-phosphatidyl-L-serine." [EC:2.7.8.8]
xref: EC:2.7.8.8
xref: MetaCyc:PHOSPHASERSYN-RXN
xref: RHEA:16913

But I can't see a term for the mammalian activity using phosphatidylcholine as as substrate.
Looks like it corresponds to this Rhea:
https://www.rhea-db.org/reaction?id=45088

This is needed to accurately annotate human PSS1 (and orthologs), as per PMID: 19014349.
(also see uniprot page: https://www.uniprot.org/uniprot/P48651

**Comment by sjm41** [comment]
Related to previous ticket - #18589

**Comment by hdrabkin** [comment]
id: GO:0106258
+name: L-serine-phosphatidylcholine phosphatidyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a 1,2-diacyl-sn-glycero-3-phosphocholine + L-serine = 1,2-diacyl-sn-glycero-3-phospho-L-serine + choline." [PMID:19014349., RHEA:45088]
+xref: RHEA:45088
+is_a: GO:0016780 ! phosphotransferase activity, for other substituted phosphate groups
+created_by: hjd
+creation_date: 2020-04-21T17:31:56Z

**Comment by sjm41** [comment]
Quick work - thanks Harold.
