### ISSUE TITLE
Merge GO:0044797 cytoplasmic transcription factor complex and O:0044798 nuclear transcription factor complex into GO:0005667 transcription factor complex

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19313]
Hello, 

GO:0005667 transcription factor complex has two children: 

GO:0044797 cytoplasmic transcription factor complex -> 0 annotations 
and O:0044798 nuclear transcription factor complex -> 11,000 annotations (EXP + non EXP). 

The distinction is not useful, I will merge the terms into their parent GO:0005667 transcription factor complex

Thanks, Pascale

**Comment by pgaudet** [comment]
ALSO

'transcription factor complex': remove LD
'protein-containing complex'
 and ('capable of' some 'DNA-binding transcription factor activity')

Since some children are RNA polymerase complex - this is a different activity

**Comment by ValWood** [comment]
I agree !

**Comment by ukemi** [comment]
Do bacteria not have transcription factor complexes?

**Comment by ValWood** [comment]
I was assuming this would just be "transcription factor complex"  with no nuclear or cytoplasmic parent. I guess that way we lose the 'nucleus' inference if it is not made explicitly, so maybe it is  better to keep it.

**Comment by pgaudet** [comment]
Change logical defintions: they are too specific: 

* transcription factor complex
'protein-containing complex'
 and ('capable of' some 'DNA-binding transcription factor activity')
-> change to 'capable of' some 'transcription regulator activity')



===

Add missing parents: 

GO:0017053 transcriptional repressor complex' add subclass 'GO:0005667 transcription factor complex'

**Comment by pgaudet** [comment]
> Do bacteria not have transcription factor complexes?

Yes they do. But is the a reason to divide the children according to the phylogeny (prok/euk?)

**Comment by pgaudet** [comment]
> 'nucleus' inference if it is not made explicitly, so maybe it is better to keep it.

No, because we still have the children

'RNA polymerase I transcription factor complex'
'RNA polymerase II transcription factor complex'
'RNA polymerase III transcription factor complex'
'RNA polymerase IV transcription factor complex'
'RNA polymerase V transcription factor complex'

**Comment by pgaudet** [comment]
Add taxon constraint: only in bacteria: 

- GO:0036411 H-NS-Cnu complex
- GO:1990198 ModE complex

**Comment by pgaudet** [comment]
Change labels + remove LD (those are too specific:) 
* GO:0000120 RNA polymerase I transcription factor complex -> RNA polymerase I transcription regulator complex 
** Remove LD: 
'protein-containing complex' and ('capable of' some 'regulation of transcription by RNA polymerase I')

**Comment by pgaudet** [comment]
GO:0090569 cytoplasmic transcriptional repressor complex -> 0 annotations 
Merge into GO:0017053 transcriptional repressor complex

**Comment by pgaudet** [comment]
GO:0090568 nuclear transcriptional repressor complex
merge into  GO:0017053 transcriptional repressor complex
