### ISSUE TITLE
GO:0016441 posttranscriptional gene silencing -> remove redundant direct parent 'gene silencing'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19329]

**Comment by RLovering** [comment]
Hi Pascale

please add the is_a child relationship between GO:0016441 posttranscriptional gene silencing and GO:0016458 'gene silencing'

ie:
GO:0016458 'gene silencing'
>is a child GO:0016441 posttranscriptional gene silencing

Thanks

Ruth

**Comment by ValWood** [comment]
I don't think you can add this parent because not all gene silencing is posttranscriptional. Some is co-transcriptional.

Check with @colinlog

**Comment by mah11** [comment]
I read the request as "add GO:0016441 is_a GO:0016458", not the other way round.

**Comment by ValWood** [comment]
ah OK, yes. It had this realtionship until recently:


2020-04-26 | Deleted | RELATION | is a GO:0016458 (gene silencing)

**Comment by RLovering** [comment]
yes  GO:0016441 posttranscriptional gene silencing is_a child of GO:0016458 'gene silencing'
Thanks
Ruth
