### ISSUE TITLE
inconsistencies in created_by field

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#19324]
In setting up Protege on my new machine, I did the settings by typing them in with the settings in the old machine open. Then I went to the guidelines at [Protege5 5 setup for GO Eds](http://wiki.geneontology.org/index.php/Protege5_5_setup_for_GO_Eds) to make sure I didn't miss anything. 

This section says this:

**Configuring User details**
* In the Protege menu, go to Preferences > User details
* User nameSelect Use supplied user name, and use your GOC identity (see your 'xref' in users.yaml). Enter the initials following GO: in the users.yaml file.

But at the workshop in Berkeley, I set my user name to be what I had always used which was based on my user name at Stanford, i.e. `kchris`. 

I grepped all the created_by lines out of the current editors version of the file and made a pivot table in Excel. There are numerous people who have used 2 or 3 different User names over the years. 

Seems we should probably clean this up. Hardest part is probably going through the go.yaml file and figuring out which ones need to be changed to what's actually in the yaml file.

Here are some that were obvious to me just in scanning down the list

user_name | #
-- | --
al | 248
Antonialock | 1
  |  
BarbaraCzub | 189
bc | 97
  |  
bhm | 288
bmeldal | 13
  |  
cjm | 75
cjmungall | 3
  |  
cls | 2
cynthia.smith | 13
  |  
dph | 2195
ukemi | 2
  |  
davidos | 83
dos | 132
dosumis | 7
  |  
dgf | 10
dianna.fisk | 21
  |  
dhl | 42
donghui | 133
  |  
GOC:mec | 1
mec | 16
melanie | 1
  |  
jane | 331
janelomax | 515
jl | 266
  |  
karen | 2
kchris | 426
krc | 83
  |  
kmv | 343
vanaukenk | 3
  |  
mah | 225
mah11 | 4
midori | 2272
  |  
maria.costanzo | 8
mcc | 59
  |  
NancyCampbell | 13
nc | 107
  |  
paola | 734
paolaroncaglia | 5
pr | 421
  |  
pg | 304
pgarmiri | 9
  |  
ramab | 8
rb | 52
  |  
rebeccafoulger | 71
rfoulger | 1760
  |  
rjd | 7
rjdodson | 1
  |  
sl | 627
slaulederkind | 29
  |  
tanyaberardini | 917
tb | 316
tberardini | 8
  |  
ValWood | 16
vw | 268

**Comment by krchristie** [comment]
Here's a tab delimited file with the pivot table listing each entry used in created_by lines and the number of occurances.

[createdBy-userNames.txt](https://github.com/geneontology/go-ontology/files/4520288/createdBy-userNames.txt)

**Comment by pgaudet** [comment]
The definition cross references also only use the two-letters abbreviations. It would be nice if this was also standardized.

**Comment by RLovering** [comment]
2 letters might not be enough, Shirin has started in my team and has the initials ss, but there is already a dbxref with ss, so she has suggested sccs, although she should use sh as this has not been used as a dbxref to date, please advise
@ShirinSaverimuttu

**Comment by ukemi** [comment]
@kltm, is this really a problem? As long as they are captured in Users.yaml aren't they all valid?

**Comment by krchristie** [comment]
> The definition cross references also only use the two-letters abbreviations. It would be nice if this was also standardized.

There are already plenty of abbreviations that use three letters, so I would say that it is not true that it is "standard" to use two letters.

**Comment by krchristie** [comment]
> 2 letters might not be enough, Shirin has started in my team and has the initials ss, but there is already a dbxref with ss, so she has suggested sccs, although she should use sh as this has not been used as a dbxref to date, please advise
> @ShirinSaverimuttu

These are the existing curator abbreviations that start with 's'. As you can see, 'sccs' does not conflict with existing ones, so that looks fine, or let me know if there is something else she would prefer.
GOC:sart
GOC:sat
GOC:sd
GOC:sdb_2009
GOC:se
GOC:sensu
GOC:sgd_curators
GOC:signaling
GOC:sj
GOC:sjc
GOC:sjp
GOC:sjw
GOC:sk
GOC:sl
GOC:sm
GOC:smb
GOC:so
GOC:sp
GOC:sr
GOC:ss
GOC:ssd
GOC:st
GOC:syr

I will need to submit a change in the Users.yaml file to make an entry for Shirin. Here is some of your entry Ruth so you can tell me what info needs to be there for Shirin with respect to what groups you want her to be in and also please give me her ORCID. 

accounts:
    github: RLovering
  authorizations:
    noctua:
      go:
        allow-edit: true
    termgenie-go:
      allow-write: true
  comment: 'formerly HGNC'
  groups:
    - 'http://www.ucl.ac.uk/functional-gene-annotation/cardiovascular'
    - 'https://www.ucl.ac.uk/functional-gene-annotation/neurological'
    - 'https://www.ucl.ac.uk/functional-gene-annotation/neurological/syngo'
  nickname: 'Ruth Lovering'
  organization: BHF-UCL
  uri: 'http://orcid.org/0000-0002-xxxx-xxxx
  xref: 'GOC:rl'

**Comment by krchristie** [comment]
> @kltm, is this really a problem? As long as they are captured in Users.yaml aren't they all valid?

@ukemi - the problem is that they are NOT all captured in the Users.yaml file. There are multiple different usages for a single person in the GO ontology file while the Users.yaml file only lists one xref. 

For example, these 3 are used for me:

* karen | 2
* kchris | 426
* krc | 83

and here is my entry in the Users.yaml file, which lists only one xref:

> accounts:
>     github: krchristie
>   authorizations:
>     noctua:
>       go:
>         allow-edit: true
>     termgenie-go:
>       allow-freeform: false
>       allow-write: true
>   groups:
>     - 'http://informatics.jax.org'
>     - 'http://geneontology.org'
>   nickname: 'Karen Christie'
>   organization: MGI
>   uri: 'http://orcid.org/0000-0001-xxxx-xxxx'
>   xref: 'GOC:krc'

**Comment by ukemi** [comment]
Got it! I think we should fix this in the ontology file then. Shall we discuss it on the call?

**Comment by ukemi** [comment]
I see you already tagged it.  :)

**Comment by krchristie** [comment]
This table shows people who either don't have a GOC name at all, or who use one or more additional other names in addition to their GOC  name.

GOC name | other/only used name(s) | # names to replace
-- | -- | --
  | brenley | 1
  | cdasilva | 1
  | gwg | 1
  | Jennifer I Deegan | 1
  | Nevila.Nouspikel | 1
dos | davidos dosumis | 2
mec | GOC:mec melanie | 2
jl | jane janelomax | 2
krc | karen kchris | 2
mah | mah11 midori | 2
pr | paola paolaroncaglia | 2
bf | rebeccafoulger rfoulger | 2
tb | tanyaberardini tberardini | 2
ae | Anne.Estreicher | 1
al | Antonialock | 1
bc | BarbaraCzub | 1
bhm | bmeldal | 1
cjm | cjmungall | 1
cls | cynthia.smith | 1
dgf | dianna.fisk | 1
dhl | donghui | 1
hal | hadil.alrohaif.14 | 1
ha | hattrill | 1
kom | klaus.mitchell.14 | 1
mcc | maria.costanzo | 1
ms | michel.schneider | 1
mr | mrice | 1
nc | NancyCampbell | 1
pga | pgarmiri | 1
rph | rachhuntley | 1
rb | ramab | 1
rjd | rjdodson | 1
rz | rozaru | 1
sl | slaulederkind | 1
tt | trudy | 1
dph | ukemi | 1
vw | ValWood | 1
kmv | vanaukenk | 1
als | zebrafishembryo | 1

These 42 other names in the created_by line match their GOC:xxxx name.

* ab
* ah
* ame
* anm
* ans
* cvs
* dgh
* di
* dl
* dsf
* dw
* ebc
* ecu
* es
* ew
* hbye
* hjd
* hp
* jh
* jp
* lb
* lr
* ml
* mls
* mm2
* pad
* pde
* pf
* pg
* pm
* ppm
* rl
* rn
* sart
* se
* sjp
* sp
* ss
* uh
* vk
* yaf
* ymb

**Comment by krchristie** [comment]
Discussed at 4/27/20 GO Editors call
* Agreed that we should fix the GO-edit.obo file
* Karen thinks she can do this quickly, will contact Jim Balhoff if not
* correction: The first five lines are not people who don't have a GO user name, but people who have never used that name in a created_by line, so there is no need for me to update the Users.yaml file to create GO users names for them.
* any current editor NOT already using their GO User name as the User info in Protege needs to change it (might just be me)
