### ISSUE TITLE
Change label: GO:0080188 RNA-directed DNA methylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19328]
The label of 'RNA-directed DNA methylation' does not mention gene silencing; I will change to 

'gene silencing by RNA-directed DNA methylation', so it fits more closely the definition.

**Comment by pgaudet** [comment]
also changed subclass relation: 
* 'DNA methylation': change from subclass to 'has part'

**Comment by pgaudet** [comment]
Created new parent: 
pre-transcriptional gene silencing by RNA

**Comment by pgaudet** [comment]
So, the structure is now: 

. 'gene silencing by RNA'
.. 'pre-transcriptional gene silencing by RNA'
... 'gene silencing by RNA-directed DNA methylation'
.. 'co-transcriptional gene silencing by RNA interference machinery'
.. 'post-transcriptional gene silencing by RNA'
... 'gene silencing by miRNA'
... 'RNA interference'

**Comment by pgaudet** [comment]
@ValWood @colinlog @RLovering Does this correspond to what we discussed yesterday?

**Comment by colinlog** [comment]
Yes. This structure is logical and concise.  

You could envisage further qualifying the top term 'gene silencing by RNA'  
by using 'gene silencing by **non-coding** RNA' ?

**Comment by ValWood** [comment]
yes!
