### ISSUE TITLE
NTR: protein demethylase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19325]
Request from @thomaspd for SignorDB annotations

+[Term]
+id: GO:0140457
+name: protein demethylase activity
+namespace: molecular_function
+def: "Catalysis of the removal of a methyl group from a protein." [PMID:24498420]
+is_a: GO:0032451 ! demethylase activity
+is_a: GO:0140096 ! catalytic activity, acting on a protein
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19325 xsd:anyURI
+created_by: pg
+creation_date: 2020-04-23T07:39:14Z
+

**Comment by pgaudet** [comment]
+ removed EC:1.14.11.27 from histone demethylase activity (H4-K20 specific) - this EC is [Histone H3]-dimethyl-L-lysine(36) demethylase.

**Comment by pgaudet** [comment]
Added 
* GO:0032454 histone demethylase activity (H3-K9 specific)
1.14.11.65   [Histone H3]-dimethyl-L-lysine(9) demethylase  
1.14.11.66   [Histone H3]-trimethyl-L-lysine(9) demethylase 
(we dont distinguish between di- and tri-methyl. 


* GO:0034647  histone demethylase activity (H3-trimethyl-K4 specific)
1.14.11.67   [Histone H3]-trimethyl-L-lysine(4) demethylase

* GO:0071558 histone demethylase activity (H3-K27 specific)
1.14.11.68   [Histone H3]-trimethyl-L-lysine(27) demethylase

**Comment by ValWood** [comment]
Maybe we need the specific terms. I think possibly some methyltransferase might be di or tri-specific. At least some dementhylases appear to be tri-specific

@colinlog  will know

**Comment by pgaudet** [comment]
There are certainly EC's for some of them- I dont have time to look more closely now, but you can open a new ticket if you have a list. 

Thanks, Pascale

**Comment by ValWood** [comment]
OK no worries, can request as required!
