### ISSUE TITLE
Review branch 'GO:0048096 chromatin-mediated maintenance of transcription' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19334]
. GO:0048096 chromatin-mediated maintenance of transcription
..   GO:1904499 regulation of chromatin-mediated maintenance of transcription 
...  GO:1904500 negative regulation of chromatin-mediated maintenance of transcription
...   GO:1904501 positive regulation of chromatin-mediated maintenance of transcription

**Comment by pgaudet** [comment]
@ValWood @RLovering 

I wonder if we really need the 'regulation' terms here: 
.. GO:1904499 regulation of chromatin-mediated maintenance of transcription
... GO:1904500 negative regulation of chromatin-mediated maintenance of transcription
... GO:1904501 positive regulation of chromatin-mediated maintenance of transcription

There are annotations to mouse Ctnnb1 by UCL (PMID:22723415) and to pombe Lid2. Both genes are annotated to other processes that seem more informative: 
- lid2: 
-  - heterochromatin assembly by small RNA
- Ctnnb1: 
-  - positive regulation of transcription by RNA polymerase II
- many others
- Near Figure 3 the authors state: "These data suggest that β-catenin actively recruits HMTs to regulate the chromatin modifications required for the initiation of Tert transcription.", so I don't understand why you used 'regulation of chromatin maintenance'. GO:0045815 positive regulation of gene expression, epigenetic or 'GO:0034401 chromatin organization involved in regulation of transcription' (those 2 sound the same) might be better, but I think these term are missing children such as 'chromatin organization involved in **positive** regulation of transcription'. 
Also, is organization right here ? or should we use 'modification'? 

Thanks, Pascale

**Comment by ValWood** [comment]
I agree. will remove.

**Comment by RLovering** [comment]
Yes, good idea, annotation removed
Thanks
Ruth

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
- GO:1904499 regulation of chromatin-mediated maintenance of transcription and children: 
- -  GO:1904500 negative regulation of chromatin-mediated maintenance of transcription
- -  GO:1904501 positive regulation of chromatin-mediated maintenance of transcription

The reason for obsoletion is that this is a readout for chromatin modification; more informative GO terms exist to capture the process. Manual annotations have been removed. There are no mappings to these terms, these terms are not present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on January 20. Unless objections are received by January 20, 2021, we will assume that you agree to this change.

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/19334


Thanks, Pascale

**Comment by pgaudet** [comment]
Done.
