### ISSUE TITLE
NTR: exocytic vesicle lumen

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#19337]
Newly formed coronavirus particles appear to to get themselves into host cell exocytic vesicles and thereby travel to the surface to be shed by exocytosis. To annotate this location, could we have:
GO: new "exocytic vesicle lumen" def: The volume enclosed within the membrane of an exocytic vesicle.
part_of:  GO:0070382 exocytic vesicle
is_a:  GO:0098566 transport vesicle lumen
PMID: 27384577, especially Figure 3 (where what they label "smooth-walled vesicle" is functioning as an exocytic vesicle with a viral particle in its lumen).

Thanks.

**Comment by pgaudet** [comment]
@deustp01 just pointed this ticket out. 
I think I this term should be 'host exocytic vesicle lumen' to be consistent with the other terms. 

@pmasson55 thoughts ?
