### ISSUE TITLE
cell-cell migration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19346]
https://science.sciencemag.org/content/359/6382/1399.long

We were looking at a paper for a gene which seems to be involved in several aspects of cell-to-cell migration

(I.e regulating  host plasma membrane conductance and  hyphal constriction).

Which term should we use?
The paper calls this "cell to cell migration".

We found
GO:0044001   migration in host
Definition 
The directional movement of an organism from one place to another within its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

which fits, but we think we need a child
the 2 children are

GO:0070360    migration of symbiont within host by polymerization of host actin | is_a
GO:0035756    transepithelial migration of symbiont in host

We think we need  a cell-to cell migration term
GO:0070360   seems to be 'intracellular migration, perhaps?)
GO:0035756 is too specific.

Other questions
GO:0052126    movement in host environment
(the parent)

has "exit from host" as a descendant, but not "entry into host". 

Should this move?

with @CuzickA

**Comment by hdrabkin** [comment]
Can you please supply
details of new term (cell-to-cell migration). Def? Ref? parent?

**Comment by hdrabkin** [comment]
I'm thinking 'entry into host' occurs outside of the host, and not 'in host environment'?

**Comment by ValWood** [comment]
I guess
cell-to-cell migration in host
child of "GO:0044001   migration in host"
def
The directional movement of a symbiont  from one host  cell to another.

ref: @CuzickA  could you supply the refernce?

Tks.

**Comment by ValWood** [comment]
that depends how "host environment' is defined. But I'm finding it hard logically to exclude 
"entry into host" from "movement of host environment", especially when "exit from host" is included....

**Comment by CuzickA** [comment]
@ValWood can you use the paper we were curating as the ref? PMID: 29567712 A single fungal MAP kinase controls plant cell-to-cell invasion by the rice blast fungus.

**Comment by ValWood** [comment]
Yes!
thanks!

**Comment by ValWood** [comment]
It is at the top of the ticket too ;)

**Comment by hdrabkin** [comment]
PMID:29567712

**Comment by hdrabkin** [comment]
[Term]
+id: GO:0106259
+name: cell-to-cell migration in host
+namespace: biological_process
+def: "The directional movement of a symbiont from one host cell to another." [GOC:vw, PMID:29567712]
+is_a: GO:0044001 ! migration in host
+created_by: hjd
+creation_date: 2020-05-01T14:09:35Z
 
and parent/child suggestion made.
