### ISSUE TITLE
histone deacetylase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19343]
I have the same gene annotated to
<img width="470" alt="Screen Shot 2020-04-24 at 15 36 52" src="https://user-images.githubusercontent.com/7359272/80408140-9c8ef600-88be-11ea-8311-5842a9aeff54.png">

are any histone deacetylases ATP independent?

I would like to standardise

**Comment by ValWood** [comment]
@colinlog do you know?

**Comment by colinlog** [comment]
Hello @ValWood 

(i) The sirtuin class of HDACs is NAD dependent. Not ATP-dependent.

(ii) There is a highly conserved chromatin remodelling complex called NuRD that harbours HDAC1/2 enzymes as well as a CHD-type ATP-dependent chromatin remodelling enzyme of the SNF2-class. However, no-one really knows why, at the mechanistic level, the HDAC and the nucleosome slider (ATP-dependent DNA translocase) reside in the same complex. When studied in vitro, the HDAC activity was found to not be affected by the presence/absence of ATP, and vice versa, the ATP-dependent nucleosome remodelling activity was not affected by HDAC inhibitors.

**Comment by ValWood** [comment]
Hi @colinlog ,
So are *any* HDACs ATP-dependent (if so which)?
and of not, what are the NAD independent HDACs?

Cheers
Val

**Comment by ValWood** [comment]
actually got it.
the sirtuin are NAD dependent  and the  "clr" family are  co-factor independent?

I can close this...

**Comment by pgaudet** [comment]
Do we need to add a comment or make the definition clearer ?
