### ISSUE TITLE
Review branch: GO:0008134 transcription factor binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19354]
Discussion with @RLovering and @colinlog 
1. We don't want to have children that state 'activator binding' and 'repressor binding', since most transcription factors can act as either. Those terms are proposed to merge up
2. Need to fix the term labels to match the labels of the transcription factor branch GO:0003700

Thanks, Pascale

**Comment by pgaudet** [comment]
Children of GO:0008134 transcription factor binding: 
Create   parent: tx regulator binding? 

Term | Number of annotation | Action
-- | -- | --
nuclear hormone receptor binding | 43 | Merge into nuclear receptor binding
steroid hormone receptor binding | 5 | Merge into nuclear receptor binding
RNA polymerase II activating   transcription factor binding | 106 | Merge into RNA polymerase II transcription factor binding
RNA polymerase II repressing   transcription factor binding | 55 | Merge into RNA polymerase II transcription factor binding
repressing transcription   factor binding | 78 | Merge into transcription factor binding
activating transcription   factor binding | 75 | Merge into transcription factor binding
DNA-binding transcription factor binding | 10 | Merge into transcription factor binding (and probably change label)
negative regulation of   estrogen receptor binding | 3 | Obsolete
regulation of estrogen   receptor binding | 0 | Obsolete
transcription factor binding | 842 |  
RNA polymerase II transcription factor   binding | 146 |  
bHLH transcription factor binding | 84 |  
STAT family protein binding | 65 |  
estrogen receptor binding | 65 |  
TBP-class protein binding | 62 |  
nuclear receptor binding | 44 |  
transcription coactivator binding | 44 |  
NF-kappaB binding | 42 |  
thyroid hormone receptor binding | 39 |  
androgen receptor binding | 38 |  
retinoid X receptor binding | 35 |  
retinoic acid receptor binding | 26 |  
glucocorticoid receptor binding | 25 |  
RNA polymerase II transcription   corepressor binding | 24 |  
transcription corepressor binding | 23 |  
RNA polymerase II-specific DNA-binding   transcription factor binding | 21 |  
TFIID-class transcription factor complex   binding | 21 |  
Tat protein binding | 15 |  
RNA polymerase II transcription   coactivator binding | 14 |  
progesterone receptor binding | 14 |  
transcription coregulator binding | 13 |  
MRF binding | 11 |  
RNA polymerase I general transcription   initiation factor binding | 11 |  
aryl hydrocarbon receptor binding | 11 |  
cAMP response element binding protein   binding | 10 |  
vitamin D receptor binding | 10 |  
TFIIB-class transcription factor binding | 9 |  
RNA polymerase II general transcription   initiation factor binding | 8 |  
RNA polymerase II sequence-specific   DNA-binding transcription factor recruiting activity | 8 |  
NFAT protein binding | 7 |  
TFIIH-class transcription factor complex   binding | 7 |  
TFIIIC-class transcription factor complex   binding | 6 |  
TFIIA-class transcription factor complex   binding | 5 |  
TFIIF-class transcription factor complex   binding | 4 |  
RNA polymerase II transcription   coregulator binding | 1 |  
TFIIE-class transcription factor complex   binding | 1 |  
TFIIIA-class transcription factor binding | 1 |  
general transcription initiation factor   binding | 1 |  
mineralocorticoid receptor binding | 1 |  

Thanks, Pascale

**Comment by ValWood** [comment]
HI,

I have a couple of mappings to

"RNA polymerase II activating transcription factor binding"
e.g.
IBA with S000002505 , PTN000816160 , S000000976
will this term disappear? If so I will block the mapping rather than reporting.

will this term disappear?

**Comment by pgaudet** [comment]
Right, we wanted to merge " GO:0001102 RNA polymerase II activating transcription factor binding" and 'GO:0001103 RNA polymerase II repressing transcription factor binding' into  GO:0061629 RNA polymerase II-specific DNA-binding transcription factor binding' 

Would that be OK for you?

**Comment by pgaudet** [comment]
The idea is that a dbTF can not be said to be activating or repressing. However one binding event may result in the BP 'positive regulation of transcription'.

**Comment by ValWood** [comment]
I never used  GO:0061629 (but I have 3 mappings, one is from "nuclear hormone receptor binding", so again I'm worried about comprehensive annotation. 

If it is required, would  "transcription coactivator activity" be a child?

**Comment by RLovering** [comment]
note that many dbTFs (including nuclear receptors) heterodimerise so not every protein that binds a dbTF is a coregulator.
I don't know if your stats are right I can find 735 EXP annotations to 469 distinct gene products
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0061629&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants
196 of these are human proteins. Not that this is comprehensively used. 

I thought there was an agreement that specific terms for the binding of a specific target was going to be maintained in GO. I agree it would be nice to have these terms fully used.

There are  over a 1000 EXP annotations to DNA-binding transcription factor binding https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0140297&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

Looking at the stats I think this term:
 GO:0001085 RNA polymerase II transcription factor binding is incorrectly placed as a child of DNA-binding transcription factor binding and is a sibling to GO:0061629 RNA polymerase II-specific DNA-binding transcription factor binding

I guess it should be:
DNA-binding transcription factor binding 
>GO:0061629 RNA polymerase II-specific DNA-binding transcription factor binding

 GO:0008134 transcription factor binding (although this has the 3 key TFs as child terms even though we are trying not to use TF term and these 3 activities are no longer grouped under a single parent term)
>GO:0001085 RNA polymerase II transcription factor binding 
>>GO:0061629 RNA polymerase II-specific DNA-binding transcription factor binding
>>GO:0001224 RNA polymerase II transcription coregulator binding

Best

Ruth

**Comment by ValWood** [comment]
Right, I was looking at 
"RNA polymerase II activating transcription factor binding"
which was the original term I was looking at. This one has 109 experimental.

I still don't know what it provides over "protein binding" part_of transcription though...
So I'll remove from PomBase (where the 3 annotations were not very useful).

Note that the definition is

"Interacting selectively and non-covalently with an RNA polymerase II transcription activating factor, a protein involved in positive regulation of transcription."

So what is a "RNA polymerase II transcription activating factor"?
It  seem these terms can be used by anything that binds any of the transcription machinery. I guess I don't understand when the terms are for... it seems they could apply to signalling molecules, transcription factors, transcription regulators etc?

**Comment by RLovering** [comment]
I am happy with the suggested merge as TF regulator may have either activating or repressing activities

**Comment by pgaudet** [comment]
I am keeping 'coactivator' 'corepressor' binding because I think those functions are less context-dependent than dbTFs - for eg Mediator is always an activator, and I think some nuclear coTFs are always repressors.

**Comment by pgaudet** [comment]
I put a 'do not annotate' tag on the parent 'GO:0008134 transcription factor binding'. 
People should be able to annotate to a descendant: 
GO:0140297 ; DNA-binding transcription factor binding, GO:0140296 ; general transcription initiation factor binding or GO:0001221 ; transcription coregulator binding.
