### ISSUE TITLE
Transcription factor complex

### ISSUE THREAD

**Issue by sandraorchard** [geneontology/go-ontology#19350]
Whilst you are reviewing transcription, can I request come more granularity in the protein complex branch. Currently there is only 'transcription regulator complex' (GO:0005667).
 I would suggest NT 'DNA-binding transcription factor complex' in which at least one of the components should bind DNA and regulate transcription. There are a few heterodimers which are currently child of RNA polymerase II transcription regulator complex which could move as (also) child of this term, but I would suggest a note suggesting annotation stops at this level, otherwise you are going to have a proliferation of 1000s of such pairs
RNA polymerase transcription regulator complex - then put the existing more specific terms I-V as children of that.
Possibly also a 'general transcription factor complex' grouping term, or they could just stay as children of RNA pol II transcription regulator complex. I don't know if used by any of the other polymerases use them - maybe ask Colin.

**Comment by pgaudet** [comment]
New grouping terms:

 
+[Term]
+id: GO:0140555
+name: DNA-binding transcription factor complex
+namespace: cellular_component
+def: "A protein complex that is capable of directly associating with DNA and regulating transcription." [GOC:pg]
+is_a: GO:0005667 ! transcription regulator complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19350 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-20T17:47:07Z
+
+[Term]
+id: GO:0140556
+name: general transcription initiation factor complex
+namespace: A component of the general transcription intiation machinery, that mediates the assembly of the RNA polymerase holoenzyme at promoter DNA to form the pre-initiation complex (PIC). {xref="GOC:pg"}
+namespace: cellular_component
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: capable_of GO:0140223 ! general transcription initiation factor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19350 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-20T17:50:56Z
+
+[Term]
+id: GO:0140557
+name: RNA polymerase I general transcription initiation factor complex
+namespace: cellular_component
+def: "A component of the RNA polymerase I general transcription intiation machinery, that mediates the assembly of the RNA polymerase holoenzyme at promoter DNA to form the pre-initiation complex (PIC)." [GOC:pg]
+intersection_of: GO:0140556 ! general transcription initiation factor complex
+intersection_of: capable_of GO:0001181 ! RNA polymerase I general transcription initiation factor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19350 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-20T18:03:01Z
+
+[Term]
+id: GO:0140558
+name: RNA polymerase II general transcription initiation factor complex
+namespace: cellular_component
+def: "A component of the RNA polymerase II general transcription intiation machinery, that mediates the assembly of the RNA polymerase holoenzyme at promoter DNA to form the pre-initiation complex (PIC)." [GOC:pg]
+intersection_of: GO:0140556 ! general transcription initiation factor complex
+intersection_of: capable_of GO:0016251 ! RNA polymerase II general transcription initiation factor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19350 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-20T18:03:13Z
+
+[Term]
+id: GO:0140559
+name: RNA polymerase III general transcription initiation factor complex
+namespace: cellular_component
+def: "A component of the RNA polymerase III general transcription intiation machinery, that mediates the assembly of the RNA polymerase holoenzyme at promoter DNA to form the pre-initiation complex (PIC)." [GOC:pg]
+intersection_of: GO:0140556 ! general transcription initiation factor complex
+intersection_of: capable_of GO:0000995 ! RNA polymerase III general transcription initiation factor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19350 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-20T18:03:26Z

**Comment by pgaudet** [comment]
- [ ] Need to review 'RNA polymerase II transcription regulator complex' annotations (116 EXP) - can be used as a do not annotate grouping class

**Comment by pgaudet** [comment]
I think this is done 

@sandraorchard please reopen if you'd like more changes. 

Thanks, Pascale
