### ISSUE TITLE
Tweak name of "mitochondrial proton-transporting ATP synthase complex, catalytic core F(1)"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19357]
Can you change the name of "mitochondrial proton-transporting ATP synthase complex, catalytic core F(1)" (GO:0000275) to "mitochondrial proton-transporting ATP synthase complex, catalytic **sector** F(1)"

Then it will match the definition, and better distinguish it from the name of its child term, which is currently very similar: "mitochondrial proton-transporting ATP synthase, catalytic core" (GO:0005754)

id: GO:0000275
name: mitochondrial proton-transporting ATP synthase complex, catalytic core F(1)
def:  The catalytic sector of the mitochondrial hydrogen-transporting ATP synthase; it comprises the catalytic core and central stalk, and is peripherally associated with the mitochondrial inner membrane when the entire ATP synthase is assembled. PMID:10838056

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks!
