### ISSUE TITLE
GO:0070816 	phosphorylation of RNA polymerase II C-terminal domain

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19365]
(Thought that a ticket for this might have been made already, but can't find one - apologies if redundant)
[what wikipedia says on this subject :) 
RNAPII can exist in two forms: RNAPII0, with a highly phosphorylated CTD, and RNAPIIA, with a nonphosphorylated CTD. Phosphorylation occurs principally on Ser2 and Ser5 of the repeats, although these positions are not equivalent. The phosphorylation state changes as RNAPII progresses through the transcription cycle: The initiating RNAPII is form IIA, and the elongating enzyme is form II0. While RNAPII0 does consist of RNAPs with hyperphosphorylated CTDs, the pattern of phosphorylation on individual CTDs can vary due to differential phosphorylation of Ser2 versus Ser5 residues and/or to differential phosphorylation of repeats along the length of the CTD. The PCTD (phosphoCTD of an RNAPII0) physically links pre-mRNA processing to transcription by tethering processing factors to elongating RNAPII, e.g., 5′-end capping, 3′-end cleavage, and polyadenylation.]

GO:0070816 	phosphorylation of RNA polymerase II C-terminal domain
is_a GO:1901407 regulation of phosphorylation of RNA polymerase II C-terminal domain

I think the way in which this has been used is to describe the transition from initiation to elongation, which is an integral part of transcription initiation.

Minimally, remove the link to GO:1901407
and make part_of
GO:0006367 transcription initiation from RNA polymerase II promoter

The children of this term:
GO:0070816	phosphorylation of RNA polymerase II C-terminal domain
GO:1901921	phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex
GO:1901408	negative regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:1901407	regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:1901409	positive regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:0071619	phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:0071620	phosphorylation of RNA polymerase II C-terminal domain serine 5 residues

Not sure whether GO:0070816 'phosphorylation of RNA polymerase II C-terminal domain' is a single-step process (we did discuss that the MF GO:0008353	'RNA polymerase II CTD heptapeptide repeat kinase activity' might be sufficient in itself) - the way it is defined it is, but it may be more nuanced than that involving some cycling of factors.

These 2 are definitely single-step processes that I think we can merge into the parent term:
GO:0071619	phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:0071620	phosphorylation of RNA polymerase II C-terminal domain serine 5 residues

For:
GO:1901921	phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex
-I don't think that this is anything outside of what happens at inititation - there are only 2 manual annotations to this.

**Comment by hattrill** [comment]
@pgaudet Is there a label we should use for TF workshop issues? I see a transcription one, but do we want a special workshop one for tracking?

**Comment by pgaudet** [comment]
@hattrill I didn't create a special project/label for the workshop; I think it's OK to use the same project. 
Thanks!

**Comment by pgaudet** [comment]
Related to #16941 and #19105

**Comment by pgaudet** [comment]
Wil get done in #19105
