### ISSUE TITLE
Rhea to MF : use of Rhea directed reactions ?

### ISSUE THREAD

**Issue by amorgat** [geneontology/go-ontology#19371]
_Convention for Rhea: UN (UNdefined direction) - LR (Left-to-Right direction) - RL (Right-to-Left direction)_

**SIB curation**:
- ENZYME: the SIB resource describing IUBMB enzyme classification
In ENZYME, EC numbers are linked to master Rhea reactions (UN) 
- UniProtKB/Swiss-Prot: UniProt entries are annotated  with UN Rhea reactions. The idea is that a catalyst doesn’t determine the direction of a reaction alone, but only influences the kinetic (speed) of the reaction. Many factors can influence the direction in which a reaction occurs.
In addition to the UN Rhea reactions annotation, and only when physiological knowledge is available, UniProt entries are also annotated with (LR | RL) Rhea reactions (up:catalyzedPhysiologicalReaction). These directional reactions are context-dependant (pathway, cellular or tissue location, etc). To date (April 2020), the context is only given by the citation/evidence (typically, the pubmed publication describing the context).

**To be discussed: What are the GO guidelines when directed reactions are organism-specific? Create only one GO term or create two GO terms?**
As an example, alcohol dehydrogenases not only oxidizes ethanol to acetaldehyde in animals but also produces ethanol from acetaldehyde in yeast. 
Would you create 
RHEA:25290     ethanol + NAD(+) = acetaldehyde + H(+) + NADH
or 
RHEA:25291     ethanol + NAD(+) => acetaldehyde + H(+) + NADH [used for annotation of ‘animals’]
RHEA:25292     acetaldehyde + H(+) + NADH => ethanol + NAD(+) [used for yeast annotation]

As a similar example,  I found, [GO:1990362](http://amigo.geneontology.org/amigo/term/GO:1990362) (butanol dehydrogenase activity).
Definition: Catalysis of the reaction: butanal + NADH + H+ => n-butanol + NAD+. Source: GOC:mengo_curators, PMID:1999395

**A related question concerns the use of GO:MF in GO-CAM/Noctua.**
Let consider GO:0004618 (phosphoglycerate kinase activity) as an example.
GO definition: Catalysis of the reaction: 3-phospho-D-glycerate + ATP = 3-phospho-D-glyceroyl phosphate + ADP + H(+). Source: RHEA:14801, EC:2.7.2.3
GO cross-ref: RHEA:14801
RHEA:14801 [UN]    (2R)-3-phosphoglycerate + ATP = (2R)-3-phospho-glyceroyl phosphate + ADP
- In a **glycolysis** GO-CAM:
GO:0004618 directly_provides_input_for GO:0004619 ((2R)-3-phospho-glyceroyl phosphate)
It corresponds to RHEA:14802 [LR]    
(2R)-3-phosphoglycerate + ATP => (2R)-3-phospho-glyceroyl phosphate + ADP
- In a **gluconeogenesis** GO-CAM:
GO:0004618 directly_provides_input_for GO:0004365 ((2R)-3-phosphoglycerate)
It corresponds to RHEA:14803 [RL]    
(2R)-3-phospho-glyceroyl phosphate + ADP => (2R)-3-phosphoglycerate + ATP

**Comment by hdrabkin** [comment]
We decided that we would use the non-directed RHEA term unless needed as the glcolysis vs gluconeogeneis example

**Comment by hdrabkin** [comment]
From GOC meeting Rhea/Reactome/GO alignment breakout:
1. Import of predicted RHEA mapping to GO- commence within about a week
2. RHEA cycle every 8 weeks to import; 
3. use RHEA to assign EC when possible using this: ftp://ftp.expasy.org/databases/rhea/tsv/rhea2ec.tsv
4. Starting to flesh out logical definitions using RHEA reactions
5. Focus on new RHEA used in UniProt- large amount of requests from UniProt
6. Flag conflicts: use of CHEBI terms in other xrefs to compare to RHEA xref (talk with Peter Karp)

**Comment by pgaudet** [comment]
to document

**Comment by pgaudet** [comment]
Documented here
https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions#catalytic_activity_and_children
