### ISSUE TITLE
merge GO:0046932 & GO:0046962

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19379]
There are no annotations to either of these terms, but they appear to be the same (same reaction, different directions) so should be merged:

[Term]
id: GO:0046932
name: sodium-transporting ATP synthase activity, rotational mechanism
namespace: molecular_function
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ADP + phosphate + Na+(out) = ATP + H2O + Na+(in), by a rotational mechanism." [EC:3.6.3.15, TC:3.A.2.1.2]
synonym: "sodium-translocating F-type ATPase activity" EXACT []
synonym: "sodium-transporting two-sector ATPase activity" EXACT []
xref: MetaCyc:3.6.3.15-RXN
is_a: GO:0015081 ! sodium ion transmembrane transporter activity
is_a: GO:0019829 ! ATPase-coupled cation transmembrane transporter activity
is_a: GO:0044769 ! ATPase activity, coupled to transmembrane movement of ions, rotational mechanism

[Term]
id: GO:0046962
name: sodium-transporting ATPase activity, rotational mechanism
namespace: molecular_function
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Na+(in) = ADP + phosphate + Na+(out), by a rotational mechanism." [EC:3.6.3.15]
synonym: "ATP phosphohydrolase (Na+-transporting) activity" EXACT [EC:3.6.3.15]
synonym: "ATP synthase, sodium ion specific activity" EXACT [EC:3.6.3.145]
synonym: "Na(+)-translocating ATPase activity" BROAD [EC:3.6.3.15]
synonym: "Na(+)-transporting two-sector ATPase activity" EXACT [EC:3.6.3.15]
synonym: "Na+-translocating ATPase activity" EXACT [EC:3.6.3.15]
synonym: "Na+-translocating F1Fo-ATPase" NARROW [EC:3.6.3.15]
synonym: "Na+-transporting two-sector ATPase" NARROW [EC:3.6.3.15]
synonym: "sodium transporting ATPase activity, rotational mechanism" EXACT []
synonym: "sodium-translocating F-type ATPase activity" NARROW []
synonym: "sodium-translocating V-type ATPase activity" NARROW []
synonym: "sodium-transporting two-sector ATPase activity" NARROW []
synonym: "vacuolar-type Na+-ATPase" NARROW [EC:3.6.3.15]
synonym: "vacuolar-type Na+-translocating ATPase" NARROW [EC:3.6.3.15]
xref: MetaCyc:3.6.3.15-RXN
is_a: GO:0015081 ! sodium ion transmembrane transporter activity
is_a: GO:0019829 ! ATPase-coupled cation transmembrane transporter activity
is_a: GO:0044769 ! ATPase activity, coupled to transmembrane movement of ions, rotational mechanism

**Comment by sjm41** [comment]
Hmmm, maybe it's intentional to have both directions as separate GO terms (I realise I'm not sure of GO policy on this....)
I see the two directions have different Rhea IDs, so can better distinguish the two GO terms that way:
GO:0046932 = RHEA:58158 (and change the '=' sign to '=>' in the GO def)
GO:0046962 = RHEA:58157 (and change the '=' sign to '=>' in the GO def)

Seems EC: 7.2.2.1 should be added to both as xref.

**Comment by hdrabkin** [comment]
I'm inclined to add the Rheas and leave the terms at this time since the terma are present

**Comment by ukemi** [comment]
+1
In the past when we did this, it was always for a reason. I don't think this policy has been changed in the transport overhaul. In this case I suspect that the direction of the sodium transport and whether ATP is being synthesized is pretty important.

**Comment by hdrabkin** [comment]
ENZYME entry: EC 3.6.3.15
Transferred entry: 7.2.2.1
EC just has 'side 1 and side 2
RHEA:58156          (APPROVED)
ATP + H2O + 4 Na(+)(in) = ADP + H(+) + 4 Na(+)(out) + phosphate 
Same participants, different directions
RHEA:58157 ATP + H2O + 4 Na(+)(in) => ADP + H(+) + 4 Na(+)(out) + phosphate
RHEA:58158 ADP + H(+) + 4 Na(+)(out) + phosphate => ATP + H2O + 4 Na(+)(in)
RHEA:58159 ATP + H2O + 4 Na(+)(in) <=> ADP + H(+) + 4 Na(+)(out) + phosphate

**Comment by sjm41** [comment]
Yeah, having seen the different Rheas (and now also seen that the much more annotated  proton-transporting ATP synthase/ATPase have two terms, GO:0046933	& GO:0046961), I agree that they should both stay.

**Comment by hdrabkin** [comment]
@ukemi  yes, I agree; they were put in for a reason (and fairly eary based on id range).
Will change EC mapping also.

**Comment by hdrabkin** [comment]
need to check parentage (ATPase vs synthase.)

**Comment by ukemi** [comment]
PMID:9315618
PMID:25593316

**Comment by pgaudet** [comment]
I also asked the same question: 
https://github.com/geneontology/go-ontology/issues/17412

This was also discussed here: https://github.com/geneontology/go-ontology/issues/17035

I suggest we add links to those tickets in the terms so we know why we have both. 

Thanks, Pascale

**Comment by sjm41** [comment]
Ah, thanks for pointing out those two tickets Pascale!  (I should have found them myself...)
(#17035 is also very relevant to #19380, and I just linked it there too.)

**Comment by ValWood** [comment]
So can this one close?

**Comment by ValWood** [comment]
Yes these are different.

**Comment by sjm41** [comment]
Just checked that the RHEA, EC xrefs and defs had been added/tweaked as requested, and these have all been done.  So, yes, good to close.  Thanks @ValWood.
