### ISSUE TITLE
Checking "proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)" parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19380]
Currently we have:

id: GO:0046933
name: proton-transporting ATP synthase activity, rotational mechanism
def: "Enables the transfer of protons from one side of a membrane to the other according to the reaction: ADP + H2O + phosphate + H+(in) = ATP + H+(out), by a rotational mechanism." [EC:7.1.2.2, TC:3.A.2.1.1]
xref: MetaCyc:ATPSYN-RXN
xref: Reactome:R-HSA-164832 "ATPase synthesizes ATP"
xref: RHEA:57722
is_a: GO:0015252 ! proton channel activity
is_a: GO:0016776 ! phosphotransferase activity, phosphate group as acceptor

So, through the second is_a relationship here, looks like the ATP synthase bit is being classified as a type of phosphotransferase (GO def: Catalysis of the transfer of a phosphorus-containing group from one compound (donor) to a phosphate group (acceptor).)
(From the QuickGO change log, that relationship was added fairly recently, 2019-08-16)

Is that relationship is correct?  I haven’t seen the ATP synthase reaction classified as a ‘transferase' elsewhere, and it seems odd to class the incorporation of phosphate and ADP as a ’transferase reaction’  - there isn't really a ‘donor’ compound’ here that remains in a dephosphorylated state following the ATP synthesis reaction....

But maybe I'm missing something....

**Comment by sjm41** [comment]
I see that adding the phosphotransferase parent was decided in #17035 

Therein, @vanaukenk  wrote: "After discussion with @ValWood and @pgaudet, we propose to add GO:0016776 'phosphotransferase activity, phosphate group as acceptor' as a parent to the 'proton-transporting ATP synthase term and remove the ATPase parent. Not having the phosphotransferase parent seems to be missing a biologically relevant MF parent."

I completely agree that removing the ATPase parent was correct.
But I don't think that ADP + phosphate => ATP classifies as a transferase reaction.

**Comment by pgaudet** [comment]
Thanks @sjm41 

What would be the correct reaction ?

**Comment by sjm41** [comment]
GO:0046933 has the correct [RHEA:57722](https://www.rhea-db.org/reaction.xhtml?id=57722) xref (though we should also add EC:7.1.2.2) and as such it already maps up to 'transporter activity (GO:0005215)'. That term is x-reffed to EC:7 = translocase activity since EC revision), so the term does have a 'catalytic activity' in that sense.  (Though I note 'transporter activity' isn't a child of 'catalytic activity' in the GO....)

I don't think there is an (existing) replacement parent term in GO to specifically cover the ATP synthase aspect of GO:0046933 - the current phosphotransferase parent just needs removing IMO.

In that respect, also note that:
- the similar term "sodium-transporting ATP synthase activity, rotational mechanism" (GO:0046932) doesn't have the phosphotransferase parent (which is correct IMO)
- the sister term "proton-transporting ATPase activity, rotational mechanism" (GO:0046961), also only maps up to 'transporter activity' within the MF aspect (it no longer has a 'hydrolase activity' parent since the EC revision of transporters/translocases)


Additional insights from @ukemi / @deustp01 / @hdrabkin / @kaxelsen appreciated!

**Comment by ValWood** [comment]
It has a relationship by has_part, but you can't see it.
I  always think this is confusing (but then has_part is confusing generally)

**Comment by sjm41** [comment]
Hi Val,
_It has a relationship by has_part, but you can't see it._
Which bit are you referring to here?

**Comment by kaxelsen** [comment]
I just saw this ticket and the closed one #17035. I have to make some corrections. In #17035 it was stated that there are three types of rotational ATPases. This is not correct, Only the F-type (FoF1 or two-sector or ATP synthase) and V-type ATPases are rotational. ATP synthases is found in two types, transporting H+ or Na+, respectively. It is correct that F-type ATPases can function both as an ATP synthase and a pump. The V-type ATPases can only pump, as can the one subunit P-type ATPase. 

Regarding the definition of id: GO:0046933
I think it is kind of back-wards since it is the proton gradient that drives the ATP synthesis, the current definition make it sound as the proton transport is the important thing (You don't say that a watermill enables the flow of water over the wheel). I would say:
"Enables the synthesis of ATP from ADP and phosphate by the transfer potons following a gradient from one side of a membrane to the other according to the reaction: ADP + H2O + phosphate + H+(in) = ATP + H+(out), by a rotational mechanism."

Regarding GO:001677
This is not an appropriate parent for ATPase reactions where ATP is hydrolysed, so phosphate is released, i.e. not transferred to anything. GO:001677 describes a phsophotransferase reaction, e.g. EC 2.7.1.30 ATP + glycerol = ADP + sn-glycerol 3-phosphate.  (RHEA;21644)
In this example phosphate is transferred from ATP to glycerol. Kinases are other examples.

According to the GONuts definition "Catalysis of the transfer of a phosphorus-containing group from one compound (donor) to a phosphate group (acceptor), it is even only a reaction of the type: ATP + phosphate = ADP + diphosphate (RHEA:29431)

**Comment by ValWood** [comment]
>Which bit are you referring to here?
ignore me, it has Is_a I was getting confused.

**Comment by sjm41** [comment]
Thanks @kaxelsen - I agree with your suggestion to reword the definition of GO:0046933 to focus on the ATP synthesis aspect.  We'll see what the editors have to say....

To be clear, would you classify the ATP synthesis direction reaction (ADP + H2O + phosphate + H+(in) = ATP + H+(out)) as a **transferase** reaction? (That's how it is in the current GO, but I don't think that's correct).  I think you're saying not, but please confirm!

**Comment by kaxelsen** [comment]
No, transport reactions are **translocase** reactions (EC 7). Before the creation of EC 7 they were listed as **hydrolase** reactions (EC 3). **Transferase** reactions are EC 2

**Comment by sjm41** [comment]
So I think the propsosal/request here boils down to:

1. Remove "is_a: GO:0016776" parent from GO:0046933

2. Add EC:7.1.2.2 as an xref to GO:0046933 (and to GO:0046961)

3. Change def of GO:0046933 to "Enables the synthesis of ATP from ADP and phosphate by the transfer of protons from one side of a membrane to the other by a rotational mechanism driven by a gradient according to the reaction: ADP + H2O + phosphate + H+(in) = ATP + H+(out)."


Open question: The ATPase term (GO:0046961) is not currently a child of "catalytic activity" (GO:0003824) in the GO.  Once we remove the incorrect phosphotransferase parent for the ATP synthase term (GO:0046933), the same will be true of that. Given both terms have EC and Rhea xrefs, it seems like they should be children of "catalytic activity" somehow, though I'm not sure where it's best to make that assertion within the GO-MF tree....  (I see "transporter activity" (GO:0005215) has EC:7 as an xref, so maybe that term should be a direct child of "catalytic activity"??)

**Comment by hdrabkin** [comment]
I've come across other instances where the activity does not appear to be under catalytic activity, or I've found binding terms under catalytic activity.

**Comment by sjm41** [comment]
Hi @pgaudet - can we implement those 3 points in my previous post, or does this require more discussion?
(The 'open question' about relating 'translocase' GO terms to the 'catalytic activity' parent is separate and I can make a different ticket for that.)

**Comment by hdrabkin** [comment]
I think relating translocase to catalytic activity should go in a separate ticket.

**Comment by sjm41** [comment]
Hi @pgaudet - can we implement those 3 points in my previous post, or does this require more discussion?

**Comment by ValWood** [comment]
- Which catalytic activity will GO:0046933 have after the changes?
-  GO:0046933   should  also have the F-P link "GO:0015986 ATP synthesis coupled proton transport"
- GO:0046933 was deleted as a parent at some point. Was that intentional?

**Comment by pgaudet** [comment]
Thanks for the reminder @sjm41

**Comment by pgaudet** [comment]
I implemented the 3 points above. 

* GO:0046961 and GO:0046933  are both children of ''proton channel activity''; is this sufficient ? Seems consistent with EC classifying them as a transporters. 

@ValWood you ask 
> GO:0046933 was deleted as a parent at some point. 

deleted as a parent of which term ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
WRT transporters as having catalytic activity  - this is a new EC class, I dont know that we want that structure in GO. One disadvantage is that it 'hides' transporters under catalytic activity when browsing. Also, I dont think we want to align exactly on EC. But if there are strong arguments to follow that structure we can consider changing. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks Pascale! All sounds good to me.

@ValWood asked "which catalytic activity will GO:0046933 have after the changes?" 
It will just map up to 'transporter activity (GO:0005215) (=EC:7), which is accurate. The question then becomes if/how do we relate (all) annotations mapping to that term to the 'catalytic activity' branch - as Pascale said, there are pros and cons to doing this...  And as we've said earlier in this thread, we'll need a separate ticket if someone wants to make a proposal.

**Comment by ValWood** [comment]
I don't understand how GO:0046933 proton-transporting ATP synthase activity, rotational mechanism can not have a catalytic activity in GO.
Its primary purpose is to synthesize ATP.

 EC is a hierarchy, GO is a graph, precisely so we can represent multiple parentage.   

I don't understand why ATP synthase can't have  a transferase parent.



>> GO:0046933 was deleted as a parent at some point.
>deleted as a parent of which term ?

I'm not sure which one this was, ignore

**Comment by kaxelsen** [comment]
@ValWood please see my comment from May 4. Chemically a transferase reaction is a reaction where you transfer a chemical group from one compound to another, e.g. kinase reactions where you transfer a phsophate group from ATP to a protein. 
GO:0046933 cannot have a transferase parent because it is NOT a transferase reaction. Moving ions across a membrane is a transLOCASE reaction.

**Comment by ValWood** [comment]
Hi  @kaxelsen I'm still concerned that the  ATP synthase part of the reaction . This is arguably the most important part biologically?
How do we capture that in the MF ?

**Comment by kaxelsen** [comment]
That is a ligase reaction ADP + Pi = ATP + H20

**Comment by sjm41** [comment]
I agree it would be good to have the "ATP synthesis" aspect of GO:0046933 under the 'catalytic activity' branch.  But as Kristian says, it's inaccurate to assert that as transferase reaction.

I hadn't thought of classing it as a ligase reaction....not sure that fits the current GO def (GO:0016874): "Catalysis of the joining of two substances, or two groups within a single molecule, **with the concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate**.[ EC:6 ]"??

Would it be useful to make a new "ATP synthase activity" MF term, and make that an additional parent of both GO:0046933 (proton-transporting ATP synthase activity, rotational mechanism) and GO:0046932 (sodium-transporting ATP synthase activity, rotational mechanism)?
Then give that new term a parent of 'ligase activity' (if that's deemed correct) or else a parent of 'catalytic activity'?

**Comment by pgaudet** [comment]
Should I make 'GO:0046933 proton-transporting ATP synthase activity, rotational mechanism' is_a ligase activity ?

**Comment by pgaudet** [comment]
About the def of (GO:0016874): "Catalysis of the joining of two substances, or two groups within a single molecule, with the concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate.[ EC:6 ]"

I think this is too restrictive - wikipedia states "ligase is an enzyme that can catalyze the joining of two large molecules by forming a new chemical bond, usually with accompanying hydrolysis of a small pendant chemical group on one of the larger molecules or the enzyme catalyzing the linking together of two compounds," (https://en.wikipedia.org/wiki/Ligase)

Should we change the definition of ligase activity ?

**Comment by sjm41** [comment]
_Should I make 'GO:0046933 proton-transporting ATP synthase activity, rotational mechanism' is_a ligase activity ?_

If @kaxelsen is happy with that, then I think that's a good solution here - assuming you relax the def of 'ligase activity' as you suggest.
(One could argue that Pi is not as a 'large molecule', so maybe leave that bit out.)
I don't think that ATP synthesis fits under any of the current children of 'ligase activity', so making it a direct child of that term seems correct to me.

I think we should treat GO:0046932 (sodium-transporting ATP synthase activity, rotational mechanism) the same as  GO:0046933 (proton-transporting ATP synthase activity, rotational mechanism) here. So that should also get the new parent.  But as mentioned above, it might be useful to have a new 'ATP synthase' term to group these, and then put that as the direct child of ligase activity?

Would be good to get @ukemi's take on this.

**Comment by kaxelsen** [comment]
I can live with that suggestion. This is a special case since it is a charge/pH gradient that fuels the ligation reaction

**Comment by pgaudet** [comment]
Is 'ligase activity, forming phosphoric ester bonds' the correct parent for 'GO:0046933 proton-transporting ATP synthase activity, rotational mechanism'  ?

**Comment by sjm41** [comment]
No, I don't think so: phosphate-phosphate bonds are "phosphoanhydride bonds" - [this article](https://watermark.silverchair.com/bio041040022.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA6UwggOhBgkqhkiG9w0BBwagggOSMIIDjgIBADCCA4cGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvJIxu_H145nErK_hAgEQgIIDWGe_KRNCnYDZpZR8BrV_cFtrcjRL_29ztnW0fLOTbiBiRVJ9W2WvfxZqTwgV5nWjwjjv1KJZvKSlUAZTSkBsQAglT6IUfa8G38z0AlbOh4C3jaheLcNDWF6WVc4MsCrphrj6wzWDdIxzBGWIFJramimuJOmEJX8GPWMuzt-H2e87sfEmXkcNrYy-Z2b_9OD_NhUec3EQrLC8Oo6ayc_jyvj907OIqSBJlbOECZVze61vZmTBGByrjT6q68axpeEGss9yGgbs1IVSUTkhmZkyCFMHdkC9D_zkeuj6hki5mFhKwTTUqVvYF4Uz6pBZGvLocmBwwuCQnCd9AMTPwrw9n25r7hwBaDS6x7VDo2MFS9bb1P0nYZESo8wTqD1dHY79ZlHa8klloJ5KA_3HGLk0uYSHY7ilTj3V1RGZdScJixAAboyX9sJ48xNhvNAosk4wC0-uMvc4PtxKuc0P_JvSNOmR47geoE4ScaqGecIDVi10qO1nFuspEUGwVVyztKnhCPSzZ7rGstd6GkE5ZZ0joyhYqmPDMAo0Dj3OvKg4nBPkyJ72_6W4gtXwXbQ8-PFj-o_Rc95wtV33uHapS786A2pvs_SnUzaFjLhX5P6dn8iOQdfYhIwRoyloU_0rk1cloTE_OQN20ZpevwnbTWvmn1aZlxEYuYsxZb_0BXauA4YexiQ1aNMeWM70Rk5B096-qVa0bfmdne0wHmEagt81ZO6D0bBweKhCZag5v1Em3BizZn9paCwvPm-kIMr3IdxYjSMRUkRMYOpJc5c2UnENWiCeBwjX63OmCUIlYkGXtMRcCFKJZvgQ-eZFT7FBTjsj6FRm-QGzaTvRpCWqQbBEegg60kYppehzFSgUUOo8p9f1s1jlbQUgimaBpqyQ8r1cMKf1HP7y7HIOFhgjviGWZAKw9J2G_v-_eRg-O-ctVY9ItWZXnDIMM36mIEoF4--qh-BG0kSUpx82V4ilhwwyJgkwHL9S6NwMIRRbc-EbQSFfoLFD6PrUaejUyZmrVdYPI9IaRxWf6Ga2k-NR_jLgtubkzRHuzCj2odtWevXemX0M5fM35j4e_s4DY81AsXADANLMOE0GxXrWLd_yzasushyK9mM9fZfojN9IhVQDPnyiPO1QZmVBtcY) is helpful.

**Comment by pgaudet** [comment]
Thanks @sjm41 

The children of ligase activity are 

*  GO:0016885 ligase activity, forming carbon-carbon bonds
*  GO:0016879 ligase activity, forming carbon-nitrogen bonds
*  GO:0016875 ligase activity, forming carbon-oxygen bonds
*  GO:0016877 ligase activity, forming carbon-sulfur bonds
*   GO:0051002 ligase activity, forming nitrogen-metal bonds
*  GO:0016886 ligase activity, forming phosphoric ester bonds 

Looks like we're missing 
-  ligase activity, forming phosphoanhydride bonds

It doesnt seem to be in EC; I dont know if we *need* this grouping term

**Comment by pgaudet** [comment]
(@sjm41 I just saw you have already made that comment; please ignore my previous comment)

**Comment by pgaudet** [comment]
New def GO:0016874 ligase activity: Catalysis of the joining of two molecules, or two groups within a single molecule, using the energy from the hydrolysis of ATP, a smilar triphosphate, or a pH gradient.

OK ?

**Comment by pgaudet** [comment]
Fixed typo : "Catalysis of the joining of two molecules, or two groups within a single molecule, using the energy from the hydrolysis of ATP, a similar triphosphate, or a pH gradient."

**Comment by sjm41** [comment]
Thanks @pgaudet - I think the new ligase def works.
