### ISSUE TITLE
dsDNA bridging

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#19385]
to annotate S. pombe ctp1 now, and its orthologs eventually:

id: GO:new
name: double-stranded DNA bridging
def: "The binding activity of a molecule that interacts selectively and non-covalently with two or more regions of double-stranded DNA simultaneously. The binding may be inter- or intramolecular with respect to the DNA." [PMID:30626735]
synonym: "dsDNA bridging" EXACT []
is_a: GO:0003690 ! double-stranded DNA binding

This is a subclass of dsDNA binding, as indicated above. I'm not sure whether it should also be is_a molecular adaptor activity (GO:0060090) because I'm not sure it fits the "permitting those molecules to function in a coordinated way" part of the adaptor def well enough. Often the bound DNA is more of a substrate than an active participant in the broader process (I'm looking at it for Ctp1's role in ds break repair). I'll leave that angle to you.

**Comment by hdrabkin** [comment]
HI @mah11 
I'm confused due to the 'abolished double-stranded DNA bridging #3688 comment.
What does that mean? Should I go ahead and make the term?

**Comment by mah11** [comment]
Hi @hdrabkin 

Yes, it would be great to have the new term.

> I'm confused due to the 'abolished double-stranded DNA bridging ... comment.

That was automagically spawned when I put a link to this ticket in one of our FYPO tracker tickets (it's pombase/fypo ticket 3688, not go-ontology 3688). Basically, pombe Ctp1 normally does the bridging-type DNA binding that the new term describes. Then there are mutants that are broken such that they don't do that binding at all. So I'll use GO:new both to annotate (wild type) ctp1 and in a logical definition for the 'abolished yada' FYPO term that we're using to annotate the mutants.

Sorry for confusion!

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106260
+name: double-stranded DNA bridging

**Comment by mah11** [comment]
lovely, thank you :)
