### ISSUE TITLE
Review phosphorylation of RNA polymerase II C-terminal domain and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19389]
'phosphorylation of RNA polymerase II C-terminal domain' children should probably be MF. 

Children terms are 
* 'phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex'
* 'phosphorylation of RNA polymerase II C-terminal domain serine 2 residues'
* 'phosphorylation of RNA polymerase II C-terminal domain serine 2 residues involved in positive  regulation of transcription elongation from RNA polymerase II promoter'
* 'phosphorylation of RNA polymerase II C-terminal domain serine 5 residues involved in recruitment of mRNA capping enzyme to RNA polymerase II holoenzyme complex'

**Comment by pgaudet** [comment]
The MF is 'RNA polymerase II CTD heptapeptide repeat kinase activity' - this should be part of 'transcription, DNA-templated'.

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/19105
