### ISSUE TITLE
GO:0000827 has an EC number as synonym

### ISSUE THREAD

**Issue by paola-scibite** [geneontology/go-ontology#19387]
Hi,
GO:0000827 inositol-1,3,4,5,6-pentakisphosphate kinase activity
has broad synonym EC:2.7.4.21
This was probably meant to be a dbxref.
Note, EC:2.7.4.21 is already a dbxref to three other terms in GO.
Thanks,
Paola

**Comment by ukemi** [comment]
Probably my bad. I will remove the synonym.

**Comment by ukemi** [comment]
Note it does satisfy one of the two reactions described in the EC entry, so I am keeping it as an xref. @hdrabkin, please correct this if I am wrong.  Rhea:10276 is a bit more specific that our def. Have you been changing these?

**Comment by hdrabkin** [comment]
RHEA maps RHEA:10276  to GO:0033857 based on the EC, (which I have not added yet ( not 
GO:0000827  There are no predictions to GO:0000827 (we would need to request)
