### ISSUE TITLE
ntr heterochromatin organization children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19396]
I need 
heterochromatin organization at subtelomere and
heterochromatin organizations at pericentric region

for GPs which organize heterochromatin spatially but are not assembly

standard definitions

PMID:26744419

**Comment by pgaudet** [comment]
Should I make this in the same phrasing as the organization terms ? 

subtelomeric heterochromatin organization 
pericentric heterochromatin organization

?? 

Thanks, Pascale

**Comment by ValWood** [comment]
yes, sorry!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140461
+name: subtelomeric heterochromatin organization
+namespace: biological_process
+def: "The organization of chromatin into heterochromatin at the subtelomeric region of a chromorome." [PMID:26744419]
+is_a: GO:0070828 ! heterochromatin organization
+intersection_of: GO:0016043 ! cellular component organization
+intersection_of: results_in_organization_of GO:0099115 ! chromosome, subtelomeric region
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19396 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-06T07:46:53Z
+
+[Term]
+id: GO:0140462
+name: pericentric heterochromatin organization
+namespace: biological_process
+def: "The organization of chromatin into heterochromatin at the pericentric region of a chromorome." [PMID:26744419]
+is_a: GO:0070828 ! heterochromatin organization
+intersection_of: GO:0016043 ! cellular component organization
+intersection_of: results_in_organization_of GO:0005721 ! pericentric heterochromatin
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19396 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-06T07:47:09Z

**Comment by ValWood** [comment]
typo
chromorome

**Comment by ValWood** [comment]
Oh also, I require
"silent-mating type cassette organization" for the same paper.

In addition, I did not see 
subtelomeric heterochromatin assembly as a descendant of
subtelomeric heterochromatin organization (the centromeric one is there)

v

**Comment by pgaudet** [comment]
> subtelomeric heterochromatin assembly as a descendant of
subtelomeric heterochromatin organization (the centromeric one is there)

I added a logical definition that should address this.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140464
+name: silent mating-type cassette heterochromatin organization
+namespace: biological_process
+def: "The organization of chromatin into heterochromatin at a silent mating-type cassette locus." [PMID:26744419]
+is_a: GO:0070828 ! heterochromatin organization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19396 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-13T05:13:24Z
