### ISSUE TITLE
NTR protein-RNA adaptor activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#19409]
child of GO:0030674  protein-macromolecule adaptor activity

I would use this term to describe how the RNA binding protein ZC3H11, mkt1 and pbp1 bring PABP (polyA binding protein) to RNAs  PMID:24470144
![rbp](https://user-images.githubusercontent.com/12727506/81288318-5115de00-905c-11ea-9633-8adc59c95d87.png)

I think it can also be used to describe how the erh1-mmi1 complex recruit CCR4-NOT and the NURS complex to targets.

Does this sound fine?

I was going to use the parent term protein-macromolecule adaptor activity + extension for PABP + SO:mRNA for 24470144, but realized SO is not allowed in P2G

**Comment by vanaukenk** [comment]
@ukemi @RLovering @pgaudet 
This sounds very much like what we are also trying to capture with a 'miRNA activity' term.
Perhaps @Antonialock 's new term could be a parent of 'miRNA activity'?

**Comment by hdrabkin** [comment]
@Antonialock 
Can you supply the proposed def for the term you are requesting?

**Comment by Antonialock** [comment]
@hdrabkin hdrabkin
Proposed def: "The binding activity of a protein that brings another protein and an RNA in contact, permitting those molecules to function in a coordinated way. "

Just to check, do you think it will be fine to use this term for complex members where several proteins contribute to the bridging with the qualifier contributes_to? In the screenshot example for example, ZC3H11 is the RNA binding protein & PBP1 contacts PABP, 


> Antonia you should be able to include SO Ids in P2G, you may have selected the wrong relation. Actually I am not sure you can use SO Ids for mRNA. Probably this should be 'occurs_at SO: UAUU element, if there isn't a SO for UAUU element then request it ;)
> How about AU_rich_element http://purl.obolibrary.org/obo/SO_0001180?
@RLovering I wanted to add two substrates so used has_input. There's
http://www.sequenceontology.org/browser/current_svn/term/SO:0001180
in SO. 
It seemed a bit odd to add 'occurs' at for an adaptor activity, but perhaps that's just in my head?

**Comment by ValWood** [comment]
I see that you used the definition of the parent

The binding activity of a protein that brings together another macromolecule in contact,

but that doesn't quite make sense does it?
@pgaudet 

it should  be just brings together a something and a something ?

**Comment by Antonialock** [comment]
yeah I thought the parent def was odd, but I thought it was because of my english xD
rephrase parent to
The binding activity of a protein that brings two other macromolecules in contact, permitting those molecules to function in a coordinated way. The adaptor can bring together two proteins, or a protein and another macromolecule such as a lipid or a nucleic acid. 
?

**Comment by Antonialock** [comment]
(it can't be 'a something and a something', it must be 'a protein and a something', since the term name states "protein-macromolecule adaptor)

**Comment by ValWood** [comment]
It's the "in contact ' part that doesn't  sound correct

it would be into contact. BUt they are not necessarily always in contact. I would get rid of the "in contact' part.

brings two molecules together?

**Comment by Antonialock** [comment]
yeah beats me what 'in contact' means. 
I like the "permitting those molecules to function in a coordinated way"

why is it limited to 2 molecules anyway? e.g. a MAPK cascade scaffold brings together many components?, allowing them to function in a coordinated way?

**Comment by ValWood** [comment]
Personally, I think that scaffolds and adaptors are slightly different, but  I was over-ruled because I'm not able to  articulate the difference. 
Maybe that is the difference . A scaffold is a platform (brings together many disparate things, often forms  the core of a complex).

An adaptor connects one thing to another thing (usually via a PTM).

A MAP kinase scaffold fits both adaptor and scaffold, but some scaffolds  (like the scaffold of a ribosome for example) aren't really adaptors because that are just a scaffold for assembly, not for connecting.

**Comment by Antonialock** [comment]
> 
> 
> Personally, I think that scaffolds and adaptors are slightly different, but I was over-ruled because I'm not able to articulate the difference.
> Maybe that is the difference . A scaffold is a platform (brings together many disparate things, often forms the core of a complex).
> 
> An adaptor connects one thing to another thing (usually via a PTM).
> 
> A MAP kinase scaffold fits both adaptor and scaffold, but some scaffolds (like the scaffold of a ribosome for example) aren't really adaptors because that are just a scaffold for assembly, not for connecting.

Ah, I think you are trying to distinguish connectors that bridges things in a pathway, as opposed to structural molecules that just glue machinery together? I'm sure lots of stuff will fall in a grey zone....would the effort put into making these distinctions be worth it?

**Comment by ValWood** [comment]
> Ah, I think you are trying to distinguish connectors that bridges things in a pathway, as opposed to structural molecules that just glue machinery together? I'm sure lots of stuff will fall in a grey zone....would the effort put into making these distinctions be worth it?

Possibly not.
But I don't think  non-signalling scaffolds sit well as adaptors.

e.g.

apc15 | anaphase-promoting complex, platform subcomplex scaffold subunit Apc15
apc2 | anaphase-promoting complex cullin family subunit Apc2
apc5 | anaphase-promoting complex, platform subcomplex scaffold TPR subunit Apc5
cut20 | anaphase-promoting complex, platform subcomplex scaffold subunit Apc4/Cut20
cut4| anaphase-promoting complex, platform subcomplex scaffold subunit Apc1

especially when the APC and other complexes like this do have dedicated adaptor subunits
apc10 | anaphase-promoting complex substrate recognition subunit Apc10

So now I have no way to describe scaffolds.

**Comment by hdrabkin** [comment]
@Antonialock is there any consensus on this?

**Comment by ValWood** [comment]
It sounds to me that this is  decision @Antonialock, it depends how GO  is going to organise these terms. At present  the distinction between a scaffold and an adaptor is fuzzy, and  the difference is not clear from the definitions.

I would just add the term requested  as @AntoniaLock suggested if you don't want to fix any exiting inconsistencies in the ontology. This is clearly a protein-RNA adaptor however GO structeres the definitions.

**Comment by ValWood** [comment]
It seems to me that this is not a decision @Antonialock can make, it depends how GO is going to organise these terms. At present the distinction between a scaffold and an adaptor is fuzzy, and the difference is not clear from the definitions.

I would just add the term requested as @Antonialock suggested if you don't want to fix any exiting inconsistencies in the ontology. This is clearly a protein-RNA adaptor however GO structures the definitions.

**Comment by Antonialock** [comment]
Thanks, yes I don't think anyone is objecting to this term per se.

protein-RNA adaptor activity 
def:
The binding activity of a protein that brings together another protein and an RNA, permitting those molecules to function in a coordinated way. "

This def sounds like it would work for @RLovering too?

**Comment by pgaudet** [comment]
@hdrabkin I'll take this since I've done most of this branch.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140517
+name: protein-RNA adaptor activity
+namespace: molecular_function
+def: "The binding activity of a protein that brings together another protein and an RNA, permitting those molecules to function in a coordinated way." [PMID:24470144]
+is_a: GO:0030674 ! protein-macromolecule adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19409 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-11T09:12:05Z

**Comment by pgaudet** [comment]
I have also updated the definition of 'GO:0030674  protein-macromolecule adaptor activity' to mention 2 or more macromolecules.

**Comment by pgaudet** [comment]
Not sure why this was left open
