### ISSUE TITLE
Invalid dbxref format on synonyms

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/go-ontology#19405]
Hello,

Thanks for the amazing gene ontology content and tools. In running my tests, I am seeing 3 GO terms with improperly formatted dbxrefs in one of their synonyms:

**WARNING: INVALID FORMAT: DBXREF(b) ON GO:0016711
**WARNING: INVALID FORMAT: DBXREF(2.1.1.319) ON GO:0035242
**WARNING: INVALID FORMAT: DBXREF(2) ON GO:0036320

Here is the full term text:

**1. What does `b` mean?**
[Term]
id: GO:0016711
name: flavonoid 3'-monooxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: a flavonoid + NADPH + H+ + O2 = 3'-hydroxyflavonoid + NADP+ + H2O." [EC:1.14.14.82]
**synonym: "flavonoid 3'-hydroxylase activity" EXACT [b]**
synonym: "flavonoid 3-hydroxylase" RELATED []
synonym: "flavonoid 3-monooxygenase" RELATED []
synonym: "flavonoid,NADPH:oxygen oxidoreductase (3'-hydroxylating)" EXACT [EC:1.14.14.82]
synonym: "NADPH:flavonoid-3'-hydroxylase activity" EXACT [EC:1.14.14.82]
xref: EC:1.14.14.82
xref: MetaCyc:FLAVONOID-3-MONOOXYGENASE-RXN
xref: RHEA:16337
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

**2. Missing `EC:`:**
[Term]
id: GO:0035242
name: protein-arginine omega-N asymmetric methyltransferase activity
namespace: molecular_function
def: "Catalysis of the addition of a second methyl group to methylated peptidyl-arginine. Methylation is on the same terminal nitrogen (omega nitrogen) residue that was previously methylated, resulting in asymmetrical peptidyl-N(omega),N(omega)-dimethylated arginine residues." [PMID:14705965, RESID:AA0068, RESID:AA0069, RHEA:48096]
comment: Note that type I protein arginine N-methyltransferase enzymes possess 'protein-arginine omega-N monomethyltransferase activity ; GO:0035241' and 'protein-arginine omega-N asymmetric methyltransferase activity ; GO:0035242'.
synonym: "S-adenosyl-L-methionine:[protein]-L-arginine N-methyltransferase ([protein]-Nomega,Nomega-dimethyl-L-arginine-forming)" RELATED [EC:2.1.1.319]
synonym: "type I PRMT activity" RELATED []
**synonym: "type I protein arginine methyltransferase activity" RELATED [2.1.1.319]**
xref: EC:2.1.1.319
xref: RESID:AA0068
xref: RESID:AA0069
xref: RHEA:48096
is_a: GO:0016274 ! protein-arginine N-methyltransferase activity

**3. What is `2`?**
[Term]
id: GO:0036320
name: mating-type P-factor pheromone receptor activity
namespace: molecular_function
def: "Combining with the mating-type peptide pheromone P-factor and transmitting the signal across the membrane to initiate a change in cell activity. P-factor is a polypeptide of 23 residues, with the sequence Thr-Tyr-Ala-Asp-Phe-Leu-Arg-Ala-Tyr-Gln-Ser-Trp-Asn-Thr-Phe-Val-Asn-Pro-Asp-Arg-Pro-Asn-Leu, and is a peptide pheromone released by Schizosaccharomyces pombe cells of the cellular mating type Plus." [GOC:al, PMID:8314086, PMID:886120]
**synonym: "P-factor mating pheromone receptor activity" EXACT [2]**
synonym: "P-factor receptor activity" EXACT []
is_a: GO:0004932 ! mating-type factor pheromone receptor activity
is_a: GO:0036318 ! peptide pheromone receptor activity

I see these in `go-basic.obo` downloaded yesterday having this at the top:
```
format-version: 1.2
data-version: releases/2020-05-02
```

Thanks again for the incredible database.

**Comment by ukemi** [comment]
2 is a bad format. 1 and 3 look like typos, but I will investigate.
