### ISSUE TITLE
synapsis rejig term

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19411]
current

The meiotic cell cycle process where side by side pairing and physical juxtaposition of homologous chromosomes is created during meiotic prophase. Synapsis begins when the chromosome arms begin to pair from the clustered telomeres and ends when synaptonemal complex or linear element assembly is complete. PMID:22582262 PMID:23117617

exact synonym
homologous chromosome pairing at meiosis

BUT
synapsis is tends to only be used for species which have synaptonemal complexes, andsome (inc pombe don't)

Can we swap the primary name for the exact synonym

"homologous chromosome pairing" 
so could we change as follows

1 rename synapsis -> homologous chromosome pairing
2. add synapsis ( narrow? synonym (it is a type of pairing)
3. revise def to

The meiotic cell cycle process where side by side pairing and physical juxtaposition of homologous chromosomes is created during meiotic prophase. ~Synapsis~ Homologous chromosome pairing begins  at the clustered telomeres and ends when homologous chromosomes are segregated at the end of meiotic metaphase I.
PMID:22582262 PMID:23117617

This is because
Fission yeast does not have synaptonemal complex and  does not do "synapsis"
Linear elements are probably not involved in pairing.
Other mechanisms of pairing are described here: https://www.pombase.org/reference/PMID:31811152
(this additional reference could be added).

**Comment by pgaudet** [comment]
- [x] swapped term label for "homologous chromosome pairing"
- [x] fix def to match the new term label
- [x] added def xref PMID:31811152

Thanks, Pascale
