### ISSUE TITLE
NTR: child of cell death for spores

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#19428]
In Dicty, sporulation occurs at the end of about 24 hours development. Spores are durable against heat, osmotic changes, detergent, many averse conditions. I have a paper where they look at the longevity of spores after sporulation, and show with propidium iodide that after 12 days a mutant  cell's spores are dead (amtA KO cells, an ammonium transporter), while wild type are still fully viable and exclude the dye. PMID: 17951519

Can I have a new child of: 
GO:0008219: cell death
GO NEW: spore death
Def.: premature degradation of spore coat or wall and abolished germination into daughter cells.

With the def I'm flexible to keep it wide for all kinds of sporulating organisms.

**Comment by ValWood** [comment]
Hi @pfey03  is this really a process though? death here is not an evolved process?  the 'evolved process' is for the spores to survive. These spores are compromised.

We would annotate as "abolished sporulation"  
https://www.pombase.org/term/FYPO:0000583
( you need a generic phenotype ontology)

If the evidence was good for a direct role in sporulation we would annotate to GO  "ascospore formation" (a..k.a sporulation for fungi)

**Comment by pfey03** [comment]
@ValWood 
It is a spore stability issue. Normally spores are resistant and durable, but mutant spores go dark in phase contrast after a few days, accumulate propidium iodide when stained when wild type are still all viable. 
If anything it is aberrant / abnormal sporulation not abolished. 
since there is a PATO term 'decreased stability' I might add a phenotype to this effect as this is the phenotype.

But I won't need the term proposed above, as I now read more into additional papers and typically this premature decline is due to problems with the spore coat (3 layers in Dicty), so I can annotate to
GO:0042244 spore wall assembly

closing the ticket
