### ISSUE TITLE
TPV GO:0042246   tissue regeneration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19437]
GO:0042246   tissue regeneration
is not always "wound healing"

**Comment by RLovering** [comment]
What regeneration are you thinking of that does not result from wound healing? Are you thinking that tissue loss is not always due to wounding?
The current definition this term is: The regrowth of lost or destroyed tissues.

**Comment by pgaudet** [comment]
Are there no other reasons to regenerate a tissue than after a wound ?

**Comment by ValWood** [comment]
regeneration of skin, hair, muscle...
or during metamorphosis?

**Comment by RLovering** [comment]
I think that the point about regeneration is that it means replacing something that was there before, ie it was taken away and then regrown. So surely for these there would need to be damage before regeneration.  
see GO:0007552 metamorphosis term. 

You might be thinking of muscle adaption? https://www.ebi.ac.uk/QuickGO/term/GO:0043500 muscle adaptation, see child terms. 

I guess you might not consider hair as wound healing. But maybe  GO:0042633 hair cycle covers this? Plus if the hair root is damaged and regenerated then this would be wound healing

**Comment by ValWood** [comment]
OK!

**Comment by ValWood** [comment]
I'm still not completely convinced. This might be clearer as "tissue repair"

**Comment by pgaudet** [comment]
Most annotations are from 
ZFIN @sabrinatoro 
MGI @ukemi  
RGD @gthayman 
UniProt @pgarmiri 
FlyBase @hattrill 
BHF-UCL @RLovering 


Maybe these people have comments/preferences ? 

Thanks, Pascale

**Comment by ukemi** [comment]
In my opinion, regeneration and repair are very different.

**Comment by sabrinatoro** [comment]
In my opinion regeneration and repair are 2 different things. 

Regeneration is when a organ or tissue is "recreated" or "regrown" after being lost. 
A LOT of regeneration studies are done in zebrafish. In these experiments. For example: 
- fin regeneration - the authors amputate the fin and it grows back
- retina regeneration-the authors injure the retina such that some cells are "gone", and the animal replace these cells
- axon regeneration: the axon of a nerve is cut and has to regrow. 

Repair or wound healing would be in the case where an injury is "patched", but an organ/tissue hasn't been lost and regrown and became functional again.

**Comment by ukemi** [comment]
Thanks @sabrinatoro. I agree that regeneration is different than repair for the reasons you enumerate. But given wound healing is defined as: The series of events that restore integrity to a damaged tissue, following an injury.
Would you agree that tissue regeneration is always a part of wound healing?

**Comment by ValWood** [comment]
To clarify, this is what you have:
<img width="388" alt="Screen Shot 2020-05-15 at 16 32 52" src="https://user-images.githubusercontent.com/7359272/82068349-c3746700-96c9-11ea-9c54-3349aeaf70b5.png">

based on the discusiion it seems that this can't be correct. Tissue regeneration is not *always* wound healing.

**Comment by ukemi** [comment]
Isn't the blue link a part_of? I think it always is. But I could be wrong.

**Comment by deustp01** [comment]
My amateur outside opinion is that the processes that make up wound healing - detection of damage, up-regulation of cell growth, migration, and division, sensing that enough has happened and down-regulating these processes - are all features of tissue regeneration, which has additional features of differentiation and morphogenesis.

**Comment by ValWood** [comment]
Yes blue is part-of
But  "tissue regeneration" part_of "wound healing" does not seem to  always be correct based on the responses?

**Comment by ukemi** [comment]
and perhaps dedifferentiation (blastema formation as well). I will let @sabrinatoro make the final call. Should we remove the part_of relationship between tissue regeneration and wound healing?

**Comment by sabrinatoro** [comment]
@ukemi : too much pressure! 
I think that  Tissue regeneration is not **_always_**  part of wound healing.
So I would remove the part_of relationship between tissue regeneration and wound healing.

**Comment by ukemi** [comment]
Thank you! I will remove the part_of.

**Comment by RLovering** [comment]
Hi All

great that a decision has been made but I am concerned about consistent annotation. How will the distinction be drawn between those genes that are involved in wound healing and those genes that are not involved in wound healing but are involved in tissue regeneration?  Perhaps there should also be a new term  tissue regeneration involved in wound healing? 

FYI UCL has 12 annotations to this term, I will now probably coannotate all of these terms to the regeneration and the wound healing term as it is not clear to me how the distinction will be made and I don't have time to read all the papers.

There are 530 exp annotations to this term, the majority created by ZFIN  (297 genes), only 27 FlyBase @hattrill and 25 MGI genes hopefully none of these need to be also associated with the wound healing term.
Best
Ruth

**Comment by ValWood** [comment]
I don't really know anything about this, but it seemed to me when   I opened the ticket that  

would healing would always be part of  tissue  regeneration, but that wouldn't work because 'tissue regeneration' is part of development and that would be incorrect for wound healing.

So is the problem that regeneration is used in different contexts?

**Comment by ValWood** [comment]
Yes...

GO:0031099    regeneration

Definition (GO:0031099 GONUTS page)
The regrowth of a lost or destroyed body part, such as an organ or tissue. This process may occur via renewal, repair, and/or growth alone (i.e. increase in size or mass).

**Comment by hattrill** [comment]
Checking where tissue regeneration has been used in annotation for flies, it all involves repair of damaged tissue. I can't think of any examples where 'regeneration' would be used in regular development or tissue maintenance.
So, if the part_of is removed, we would have to co-annotate.

**Comment by ukemi** [comment]
@sabrinatoro? 
We would have to co-annotate.

**Comment by ukemi** [comment]
Or I could put it back to the way it was.

**Comment by RLovering** [comment]
Or create a new GO term tissue regeneration involved in wound healing and transfer all existing annotations to this term

**Comment by ValWood** [comment]
> Or I could put it back to the way it was.

but the way it was is clearly incorrect?

If regeneration is 
GO:0031099  regeneration
The regrowth of a lost or destroyed body part, such as an organ or tissue. This process may occur via renewal, repair, and/or growth alone (i.e. increase in size or mass).

presumably "tissue regeneration"
 is more explicitly 
GO:0031099  regeneration
The regrowth of a lost or destroyed tissue. This process may occur via renewal, repair, and/or growth alone (i.e. increase in size or mass).

and in this case "wound healing" can't logically be a parent of "tissue regeneration"

it seems to be a conflation in multiple ways because "tissue regeneration"  isn't always part of development either, if its the  repair type of "tissue regeneration which occurs during wound healing".

**Comment by sabrinatoro** [comment]
I agree with Val: 
- "wound healing" should not be a parent of "tissue regeneration"
- "tissue regeneration" should not be part of "development"

if/when I need to annotate to "wound healing part_of tissue regeneration", I use noctua (it happened once, when the authors were clearly study the wound healing in the context of regeneration.

To reply to preview comments and for consistency's sake: 
I am wondering if we have concrete examples for BOTH:
- wound healing part_of tissue regeneration
AND
- tissue regeneration part_of wound healing
?

Most (or all?) of the ZFIN examples would be "wound healing part_of tissue regeneration". Does anyone have an example for "tissues regeneration part_of wound healing"? (would new epithelium forming to repair the injury/wound be one example?

**Comment by hattrill** [comment]
I can agree with the dev bit:
I don't see regeneration as part of a developmental process and different from what we would think of as renewal (thinking many in terms of stem cells), which is homeostasis.

I don't feel qualified to comment on wounding and tissue regen!

**Comment by ukemi** [comment]
Every time wound healing happens, it is not always part of regeneration. An example would be the formation of a scar.
I will let you discuss this issue in this ticket, but would like some concrete instructions about exactly what changes I should make in the ontology, so I can finish it and close it.

**Comment by sabrinatoro** [comment]
my suggestion: 
- remove the "is_a" relation between 'tissue regeneration' and 'tissue development'
- remove the "part_of" relation between 'tissue regeneration' and 'wound healing'

I think we could use Noctua (or AE?) in the cases when we mean tissue regeneration part of wound healing. If not, maybe we can create new terms. 
@RLovering @ValWood, what do you think?

**Comment by RLovering** [comment]
Hi Sabrina

almost all of the examples I had looked like they would be tissue regeneration as part of wound healing, a couple might be on the cusp of that. http://europepmc.org/article/MED/23918388 descibes: Cardiac-specific deletion of Yap impedes neonatal heart regeneration, resulting in a default fibrotic response. Obviously there is a lot of research into regeneration of the heart after a heart attack. Zebrafish are an amazing MOD that is able to regenerate their hearts after pieces have been removed, human and mouse post natal hearts develop fibrotic lesions rather than regeneration. Whereas neonatal mouse hearts are able to regenerate. So understanding the pathways and cell types that contribute to regeneration of heart tissues after 'wounding' which may be due to ischemia rather than an external impact to the body.

I agree that the noctua model enables us to capture this, but right now the data is not being included in the existing annotations files unless I co-annotate all the GO term information I include AE field as 'normal" annotations. 

I also think that in theory the curators should have seen the ontology structure which has been there for quite a while and so may have felt that the genes they annotated contributed to regeneration as part of the response to the wounding.

As I said I don't have that many annotations (although then I discovered the regulation annotations) so I am happy to co-annotate if this is the decision, I would prefer the child term I suggested as I am still not sure when there is regeneration of tissue that doesn't follow from some sort of injury. The word itself is "re" generation, ie generation of something that existed, has disappeared and then has been generated again. But as I don't curate zebrafish which does have much more capacity for regeneration than human I haven't had much experience of annotating these papers.

Best

Ruth

**Comment by hattrill** [comment]
I asked Nick Brown to take a look at the ticket and give his thoughts - he is an expert on cell adhesion and is well-placed to comment on what researchers expect. (No newts were harmed as a result of this email.)

--------

"Its certainly a tricky one! I think I agree with those that think that wound healing does not always involve tissue regeneration and that tissue regeneration can occur outside of wound healing. 

I cannot think of any cases where regeneration occurs without a wound or tissue damage, so I agree with your statement that regeneration does not occur unless wounding or damage has happened. However, when you cut off a limb in a newt for example, I think wound healing and regeneration are separable in time. That is the wound is healed, and then the limb slowly grows back. So the second part of the regeneration process does not involve wound healing components, and  may require unique genes. Therefore searching for regeneration I would not expect to get everything involved in wound healing.

I was trying to think of whether there is any example of wound healing that does not require some level of regeneration, in that some damaged cells are replaced in the process of wound healing. I couldnt think of one, but agree that there might be examples, so its safer to assume that if we searched for wound healing we wouldnt expect to get all the factors involved in regeneration.

With regard to your ontology tree, there should be some link between wound healing and regeneration but I am not sure how to generate the link that says that wound healing is a precursor to regeneration, but there are regenerative processes that distinct from wound healing. Its not a simple parent child relationship is it!
------------

**Comment by RLovering** [comment]
Very nicely described. let me know the decision as I guess Iwill probably have to reannotate
Best
Ruth

**Comment by ValWood** [comment]
Hi @ukemi  what was the final action here?

**Comment by ukemi** [comment]
I don't think there was one. I would be tempted to modify the ontology based on the June 1st comment.

**Comment by pgaudet** [comment]
> wound healing does not always involve tissue regeneration and that tissue regeneration can occur outside of wound healing. 

So I will do what @sabrinatoro suggests: 
* remove the "is_a" relation between 'tissue regeneration' and 'tissue development'
* remove the "part_of" relation between 'tissue regeneration' and 'wound healing'
