### ISSUE TITLE
NTR iron sensor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19433]
NTR iron sensor activity

Parent
small molecule sensor activity (GO:0140299)

Definition 
Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of iron.

PMID: 11956219 
PMID: 25806539

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140482
+name: iron sensor activity
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of iron." [PMID:11956219, PMID:25806539]
+intersection_of: GO:0140299 ! small molecule sensor activity
+intersection_of: has_input CHEBI:24875 ! iron cation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19433 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-25T20:58:02Z
