### ISSUE TITLE
propose obsoletion whole membrane (GO:0098805) problem term

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19435]
This term is problematic in oh so many ways

whole membrane (GO:0098805)
Definition	
Any lipid bilayer that completely encloses some structure, and all the proteins embedded in it or attached to it. Examples include the plasma membrane and most organelle membranes.

I'm not sure what it even means. For example 
" plasma membrane and most organelle membranes"
but "plasma membrane" is not even a descendant of this term.
and which "most organelle membranes" ?

I can't figure out why we need to  say "whole membrane",  or how this can work ontologically?

As soon as you add a part_of child to  a term under "whole membrane" term, you violate?

Any idea why it was required?

**Comment by pgaudet** [comment]
Hi @ValWood 

The term was created to make logical definition for membranes. 

For example: 

GO:0033102 acidocalcisome membrane
has logical definition: 
'whole membrane' and ('bounding layer of' some acidocalcisome)


Looks like 'plasma membrane' was forgotten? 

I agree this is very confusing for curators and users. @cmungall can we not use 'membrane' or 'organelle membrane' as the genera ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Ah right, so than the part of children will be OK, because  that will be part_of not is_a

But now I don't know how  "membrane" and "whole membrane" differ

I guess it's OK if all the membranes are under there. But yes just membrane  would be easier for curators  if "whole membrane"  could be an exact synonym of "membrane"

**Comment by pgaudet** [comment]
Discussion on ontology call: 
@cmungall useful for classification 
@thomaspd @pgaudet ask why this is different from the specific membrane 

@cmungall required for classification of some terms

To revisit at next call

**Comment by cmungall** [comment]
I agree these terms are confusing. Are they causing any immediate problems? Note 'whole membrane' is in the gocheck_do_not_annotate subset, so ideally this is hidden from curators when making selections (I don't think we have this implemented in all tools though).

There is a rationale for these. We need a system for automating the placement of X membrane terms. This is not completely straightforward. The system in place was one solution. I was never not totally happy with it for technical reasons (see for example #12926). It seems it was not even fully implemented. As @ValWood notes, it is perplexing why PM is not placed under here.

Ideally the precise use case for this class should have been documented at the time, and in the DP: https://github.com/geneontology/go-ontology/blob/7be0df46781f2e3a456a3e178def19dcdbb20ecf/src/design_patterns/bounding_membrane_of_organelle.yaml

It may be fine to simply obsolete this term but I'd rather have some time to do some digging, if this is not urgent. David OS may be able to shine some light on these decisions, but I know he is super busy just now

**Comment by ValWood** [comment]
Hi Chris, the problem is that slims are affected

not everything annotated to endoplasmic reticulum membrane (GO:0005789)
becomes annotated to endoplasmic reticulum.

549 | (endoplasmic reticulum (GO:0005783) OR endoplasmic reticulum membrane (GO:0005789)) | ...
-- | -- | --
  | 502 | endoplasmic reticulum (GO:0005783) | ...
  | 216 | endoplasmic reticulum membrane (GO:0005789)

This affects PomBAse and AmiGO, but not  QuickGO.

I

**Comment by ValWood** [comment]
See
https://github.com/geneontology/go-ontology/issues/19436

**Comment by ValWood** [comment]
Ignore. I am mixing up the s issues. I don't think this one causes any major issues other than how to interpret  what the terms were for or why PM was excluded.

**Comment by krchristie** [comment]
We should probably revise the definition of this term since it specifically mentions `plasma membrane` but the term `plasma membrane` does not classify as a type of `whole membrane`.

**Comment by pgaudet** [comment]
Decision on ontology call is to try to merge 'whole membrane' and 'membrane region' into 'membrane' and git rid of any distinction between 'whole' and 'region'. 

Make a branch and look at inferences, and look whether the plasma membrane stuff still makes sense.

**Comment by pgaudet** [comment]
I *merged* into 'membrane' (did not obsolete)

Note that I also removed `disjoint_from: GO:0098589 ! membrane region`.

**Comment by ValWood** [comment]
"whole membrane" is still there?

**Comment by pgaudet** [comment]
Merged 'membrane region' into membrane.

**Comment by ValWood** [comment]
Just to note membrane specific regions still exist, but not the non-specific grouping term because the regions are a heterogeneous set of organelle-specific regions
