### ISSUE TITLE
MISSING PARENT endoplasmic reticulum membrane (GO:0005789) (MAJOR, AFFECTS COMPONENT SLIMS)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19436]
endoplasmic reticulum membrane (GO:0005789)
Add parent endoplasmic reticulum

Because of this thread I decided to make  a pombe component slim
https://twitter.com/timisstuck/status/1258372055503962113

We need some sanity checks for things like this...

**Comment by ValWood** [comment]
Thats odd, it is there. Closing

**Comment by ValWood** [comment]
but I don't see it in PomBase 
https://www.pombase.org/term/GO:0005789
which is weird?

**Comment by pgaudet** [comment]
That's another odd one. 

ER membrane is defined as 
'organelle membrane' and ('bounding layer of' some 'endoplasmic reticulum subcompartment')

I dont know why not just  'endoplasmic reticulum '? And I am not sure we need the 'subcompartment' terms. 

Pascale

**Comment by ValWood** [comment]
I don't understand why we don't get the inference, because the relationship is there?
We just updated PomBase  after a few days with no GO update, and still "ER membrane" annotation don't propagate to ER.

**Comment by mah11** [comment]
This took a bit of eyeballing! I think I see what's happening, though not why ...

This is the stanza from go-edit.obo:

[Term]
id: GO:0005789
name: endoplasmic reticulum membrane
namespace: cellular_component
def: "The lipid bilayer surrounding the endoplasmic reticulum." [GOC:mah]
synonym: "ER membrane" EXACT []
intersection_of: GO:0031090 ! organelle membrane
intersection_of: bounding_layer_of GO:0098827 ! endoplasmic reticulum subcompartment
relationship: part_of GO:0042175 ! nuclear outer membrane-endoplasmic reticulum membrane network

The bounding_layer_of relation between GO:0005789 and GO:0098827 isn't getting translated into anything in the derived go.obo or go-basic.obo files (PomBase loads the latter); to the extent that I can tell, the same is true for the go.owl file. GO:0005789 end up with just 'is_a: GO:0031090 ! organelle membrane' and 'relationship: part_of GO:0042175 ! nuclear outer membrane-endoplasmic reticulum membrane network'.

QuickGO is somehow able to show GO:0005789 connected GO:0098827 by part_of -- I have no idea how -- but AmiGO doesn't.

**Comment by balhoff** [comment]
@cmungall if i understand this issue correctly, we should be using the expression materializing reasoner to generalize subproperties to allowed go.obo relations where possible. 'bounding layer of' is a subproperty of 'part of'. What do you think?

**Comment by pgaudet** [comment]
Could we not simplify relations instead ? Do we need 'bounding layer of? Isn't 'part_of sufficient ?

**Comment by pgaudet** [comment]
Decision on editor call is to address Jim's point about having 'bounding layer of' needing to be applying correctly the inference as a child of 'part of' (@balhoff please clarify if needed!) .

**Comment by ValWood** [comment]
Didn't this get resolved recently by another ticket?

**Comment by ValWood** [comment]
Nope it isn't fixed yet.
Is this fix  in  the pipeline? This is quite bad because it can really distort results.

See the results of a query. ALL of ER membrane annotations should be inherited by ER, but they are not. There is a big shortfall....

<img width="1105" alt="Screenshot 2020-07-20 at 17 54 31" src="https://user-images.githubusercontent.com/7359272/87964488-3c20e680-cab2-11ea-87b9-7600d06370a2.png">

**Comment by ValWood** [comment]
Any news on this?
It seems quite important to fix because it will affect analyses /results by quite large numbers. Also, it is likely that this is not the only affected term.

What needs to happen to fix this ?  It does not seem to be clear what the next required action is?
@pgaudet 
@balhoff 
@cmungall

**Comment by balhoff** [comment]
@ValWood I have not yet made the change to the ontology build to infer 'part of' from subproperties. I just made a separate ticket to track this better: #19863

**Comment by ValWood** [comment]
OK thanks, just checking it  was still on somebody's radar!
v

**Comment by pgaudet** [comment]
Should be able to close when #19863 is done.

**Comment by balhoff** [comment]
I updated the ontology build to add inferred part_of relationships. You can see the resulting changes for `go.owl` here: #19978

Some part_of links are removed, since they are now transitively redundant with one that's been added.

**Comment by ValWood** [comment]
Yay!

215 | endoplasmic reticulum (GO:0005783) AND endoplasmic reticulum membrane (GO:0005789) [details] | ...
-- | -- | --
  | 549 | endoplasmic reticulum (GO:0005783) | ...
  | 215 | endoplasmic reticulum membrane (GO:0005789)
