### ISSUE TITLE
cell adhesion mediator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19441]
cell adhesion mediator
Definition | Parents
-- | --
The binding by a cell-adhesion protein on the cell surface to an extracellular matrix component, to mediate adhesion of the cell to the external substrate or to another cell.

I have used this term for fission yeast cell adhesion mediators, but extracellular matrix is a multicellular term (providing support to surrounding cells).

In  yeast cell adhesion molecules function by binding to other adhesion molecules on  other yeast. So cell cell ahesion  is mediated by a "cell adhesion mediator" binding to another cell adhesion mediator (I.e cell adhesion molecule binding).

Is this the case for higher euks, or are the cell adhesion molecules binding to something else? Presumable whatever is bound must also be an adhesion molecule of sorts.

So, I am wondering if

  | 14 | cell adhesion mediator activity (GO:0098631) | ...
could be a descendent of 
  | 13 | cell adhesion molecule binding (GO:0050839)

This would be true for yeast but at present we get redundant annotation.

Also,  if so, could we refine the definition of 
 cell adhesion mediator activity 
to the more generic 
The binding by a cell-adhesion protein on a cell surface to an adhesion molecule on another cell surface, to mediate adhesion of the cell to the external substrate or to another cell.

**Comment by hdrabkin** [comment]
done
