### ISSUE TITLE
MP cargo receptor activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19454]
cargo receptor activity (GO:0038024)

isn't this a type of "molecular adaptor activity"

should it be?

**Comment by pgaudet** [comment]
The advantage of having it as it is, is that it's easier to spot. Otherwise it's buried under the "molecular adaptor activity" class, and people might no think to look there. 

What do you think ?

**Comment by ValWood** [comment]
I don't think we should put things as the root node just to make them easier to spot.  We should put them in the rich place and a cargo receptor should be defined logically as a type of adaptor.

And anyway most people will not locate via 'drill down'; they will search on cargo receptor and find it.


but it also fits the definition of carrier:
GO:0140104    molecular carrier activity
Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.

should it fit this definition too, or should cattier exclude this?

**Comment by RLovering** [comment]
I think cargo receptor activity (GO:0038024) should be an is_a child of GO:0140104 molecular carrier activity.
I am not convinced that cargo receptor activity (GO:0038024) should be described as a molecular adaptor activity.

for example I would have thought it would be possible for a cargo to be taken to a location and released without the cargo receptor acting as a bridge between the cargo and its new binding partners? Plus I has assumed that a molecular adaptor activity would remain as the 'bridge' rather than as a temporary scaffold. But I guess acting as a temporary scaffold is probably not excluded from the term molecular adaptor activity.

**Comment by ValWood** [comment]
I seem to remember that  the "molecular carrier activity" was *meant* to exclude cargo receptors as it mixes different types of 'carrier' (apples and oranges). 

an adaptor is defined as a 
The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way.

so this also includes vesicle/cargo adaptor/substrate. (It isn't an adaptor to the new binding partner, it's an adaptor to the vesicle)

**Comment by ValWood** [comment]
Actually I'm getting confused. We have cargo receptor and cargo adaptor. What is the difference?

**Comment by ValWood** [comment]
<img width="494" alt="Screenshot 2020-07-01 at 12 28 18" src="https://user-images.githubusercontent.com/7359272/86239007-6f004a80-bb96-11ea-8f8d-16d3d1a53e2b.png">

**Comment by RLovering** [comment]
Maybe the idea was to have apples and oranges represented by:
cargo receptor activity - not an adaptor
cargo adaptor activity -  not a transporter
;)

**Comment by ValWood** [comment]
but they are all still adaptors  according to the definition  aren't they?

One is a coat adaptor (cargo receptor activity, connecting the vesicle to the substrate adaptor)
and one is a substrate adaptor (cargo adaptor connecting the cargo receptor to the substrate)

At present, in other areas  of the ontology this activity is described as an adaptor.
If these are not really the same then we need to look at the others.

I preferred "tether" for connecting  protein or an adaptor to a membrane but I could not justify the split because they are still connecting something to something.....

I can see now why this is on it's own but a cytoskeletal membrane anchor is under adaptor,

and that is closer to a receptor than  and adaptor because it is connecting directly to the membrane.

**Comment by ValWood** [comment]
In the clathrin coated vesicles:

<img width="433" alt="Screen Shot 2020-09-21 at 11 29 40" src="https://user-images.githubusercontent.com/7359272/93756927-c9410280-fbfd-11ea-9dad-51dd4c021b38.png">

There are 2 molecules, the "receptor" which is the  one which binds to the substrate, and the adaptor which links from the 'receptor'  to the clathrin coat

**Comment by ValWood** [comment]
https://www.pombase.org/reference/PMID:32735772

**Comment by pgaudet** [comment]
@lbreuza Do you remember what we decided when we discussed cargo receptors that do not require adaptors ? They are still cargo receptors, right ?

**Comment by lbreuza** [comment]
I would say yes, provided they recruit cargos and the membrane deformation machinery to allow the cargo to be incorporated in a vesicle. Not sure that cargo receptor that directly bind to the membrane deformation machinery exist  - no example I can recall.
I noticed the definition states "Notes: (1) this term and its child terms are intended for receptors that bind to and internalize molecules by receptor-mediated endocytosis." However, one cite papers dealing with COPII vesicles that do not function in endocytosis.

**Comment by ValWood** [comment]
HI @lbreuza,
Could you look at the graphical abstract here?
https://www.pombase.org/reference/PMID:32735772
I am trying to decribe erp1.

Epr1 is a cargo receptor but the cargo is the ER!
This  is in reticulophagy.

I'm struggling whether this is an adaptor, ot a receptor. or both?

**Comment by ValWood** [comment]
The authors call it a soluable receptor, and it does recognize the cargo via the 'marker protein' Vap1
but it seems more like an adaptor in GO-speak.

**Comment by pgaudet** [comment]
Discussion with @ValWood and @lbreuza 

We need to fix the definition of cargo adaptor activity: 
Binding directly to the structural scaffolding elements of a vesicle coat (such as clathrin or COPII), and bridging the membrane, cargo **receptor**, and membrane deformation machinery.  ('receptor' is missing)
