### ISSUE TITLE
Taxon constraints on skin things

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19456]
Could you add a "never in Arthropoda"  TAXID:6656 to these skin/keratinocyte nodes? Thanks

GO:0043616	keratinocyte proliferation
GO:0043588	skin development
GO:0033561	regulation of water loss via skin
GO:0032980	keratinocyte activation
GO:0051546	keratinocyte migration
GO:0097283	keratinocyte apoptotic process

**Comment by ukemi** [comment]
#19657

**Comment by ukemi** [comment]
Looks like I did this but never closed this ticket.

**Comment by cmungall** [comment]
should all be inferred...
