### ISSUE TITLE
GPI-anchor transamidase activity (GO:0003923) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19457]
GPI-anchor transamidase activity (GO:0003923) is currently a direct child of 'hydrolase activity'.

For a couple of reasons, I think this could be moved 'down one level' to be a child of "peptidase activity (GO:0008233)":
1. The equivalent InterPro entry (IPR028361) is a child of "Peptidase C13, legumain (IPR001096)", which itself has the GO term "peptidase activity"
2. The catalytic subunit of the 'GPI-anchor transamidase' complex (PIGK) is described as being similar to cysteine proteases in the literature (e.g. PMID:19883648, PMID:24727937.)

So, in terms of the 'hydrolase' component of the transamidase reaction, it seems it could/should be a child of 'peptidase activity'.
What do you think?

**Comment by ValWood** [comment]
but it isn't a peptide bond is it?

**Comment by sjm41** [comment]
I think cleaving the signal peptide off the protein is?

GO:def: "Catalysis of the formation of the linkage between a protein and a glycosylphosphatidylinositol anchor. The reaction probably occurs by subjecting a peptide bond to nucleophilic attack by the amino group of ethanolamine-GPI, transferring the protein from a signal peptide to the GPI anchor." [ISBN:0471331309]

**Comment by ValWood** [comment]
Wow OK, I had no idea that is what this was doing. I thought it was just attaching the GPI to the protein!

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Hi Harold,

Sorry for not spotting this before, but I've just found evidence in the MEROPS database that means we can move GO:0003923 to a more specific level.  Can you change its parent from 'peptidase activity' to 'cysteine-type endopeptidase activity (GO:0004197)' based on the following?

https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=C13.005
https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=C13
https://www.ebi.ac.uk/merops/cgi-bin/clansum?clan=CD

Steven

**Comment by sjm41** [comment]
@hdrabkin - just checking you saw my last (belated) comment on this? (I don't seem able to actually re-open the ticket...)

**Comment by hdrabkin** [comment]
@sjm41 - Saw this yesterday and changed today; done

**Comment by sjm41** [comment]
Great, thanks Harold!
