### ISSUE TITLE
Confusion over use of "heart" in GO

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#19452]
See also #12223 

The term "heart" can be ambiguous w.r.t whether it refers specifically to a vertebrate heart or generically to a primary circulatory organ.

There are some advantages to lumping, and some to splitting

In Uberon we have a detailed classification of circulatory organs:

https://github.com/obophenotype/uberon/issues/1217

While it is hard to satisfy everyone with terminology, we chose to use the string "heart" for the vertebrate organ and "primary circulatory organ" for a grouping that includes vertebrate primary hearts and the dorsal vessel of insects. We use this terminology consistently throughout the ontology. 

**We are open to any suggestions for terminological change** we want to support a variety of organisms like Drosophila cc @hattrill but also support those who need to use a more specific class with specific relationships to vertebrate-specific structures. For example, currently in Uberon 'heart' traces back to neural crest cells which is obviously only applicable in vertebrates.

In GO, there is confusion about whether we refer to the more specific taxon-restricted structure

For example, compare:

```
id: GO:0007507
name: heart development
namespace: biological_process
alt_id: GO:0007511
def: "The process whose specific outcome is the progression of the heart over time, from its formation to the mature structure. The heart is a hollow, muscular organ, which, by contracting rhythmically, keeps up the circulation of the blood." [GOC:jid, UBERON:0000948]
synonym: "cardiac development" RELATED []
synonym: "dorsal vessel development" NARROW []
xref: Wikipedia:Heart_development
is_a: GO:0032502 ! developmental process
is_a: GO:0048513 ! animal organ development
intersection_of: GO:0048856 ! anatomical structure development
****intersection_of: results_in_development_of UBERON:0007100 ! primary circulatory organ
```

compare with:

```
id: GO:0003007
name: heart morphogenesis
namespace: biological_process
def: "The developmental process in which the heart is generated and organized. The heart is a hollow, muscular organ, which, by contracting rhythmically, keeps up the circulation of the blood." [GOC:dph, GOC:isa_complete]
synonym: "cardiac morphogenesis" RELATED []
is_a: GO:0009887 ! animal organ morphogenesis
intersection_of: GO:0009653 ! anatomical structure morphogenesis
***intersection_of: results_in_morphogenesis_of UBERON:0000948 ! heart
```

SUGGESTED SHORT TERM PATH:

Given that GO uses 'heart' generically, ensure all logical definitions point to the appropriate term which should be 'primary circulatory organ'. If no cognate is found, leave out the logical definition for now.

This will solve the false positive taxon constraint issues, cc @pgaudet @hattrill 

MEDIUM/LONGER TERM:

We should align both terminology and structure between Uberon and GO. This may involve changing terminology in GO, or in Uberon, or both.

We should also determine what is best for our users. What are the use cases for lumping vs splitting in GO? Which is best for homology/phylogeny based inference? This is probably too deep a topic for discussion in github so we could have a dedicated call about this.

**Comment by cmungall** [comment]
We should also adopt @balhoff's proposal to include axioms that say a structure is present in a taxon. E.g. GO:heart-development present-in Dmel. This will make implicit assumptions explicit and detect inconsistencies ahead of time rather than unpleasant surprises at time of GAF checj

**Comment by hattrill** [comment]
Thanks, Chris. That sounds a good solution.

We should dig into the original cardiac project. (Ruth and David will remember this with some fondness, I expect, but slightly before my time).

Helen

tinman <http://flybase.org/reports/FBgn0004110> 
heartless <http://flybase.org/reports/FBgn0010389>

**Comment by cmungall** [comment]
I just realized we discussed a lot of this 4 years ago #12655

**Comment by hattrill** [comment]
And here back in Jan - https://github.com/geneontology/go-ontology/issues/18657 - 'though some how you were not looped in. Must have failed to follow it up.

**Comment by cmungall** [comment]
I also want to point out the consequences of the current structure in GO is that a human/vertebrate researcher coming in with a query for "cardiovascular system development" will NOT get genes annotated to "heart development":

![image](https://user-images.githubusercontent.com/50745/82012479-ef8dda80-962c-11ea-88a6-ae2616b24c5c.png)

This is a pretty high price to pay for the grouping.

I don't like term proliferation but I think splitting the terms here makes sense

(although in this particular case, maybe we can live without a CV term and just merge it into circulatory system... but this is just one problem that may be lurking)

Grouping across metazoa is hard. An individual structure may exhibit developmental homologies in the structure itself, but it's broader context will be different, which makes maintaining the true path rule a nightmare... either you lose too many genes or you gain inappropriate ones

**Comment by hattrill** [comment]
Yes, that is problematic. You would expect "cardiovascular system development" to comprise heart and vessel dev branches, but only has vasculature child terms:
vasculature development
vascular cord development

So, yes, moving heart dev under "cardiovascular system development" seems an easy win (and the definition doesn't even have to be changed!)
"The process whose specific outcome is the progression of the cardiovascular system over time, from its formation to the mature structure. The cardiovascular system is the anatomical system that has as its parts the **heart** and **blood vessels**."

**Comment by ukemi** [comment]
Yes. Seems that the part_of is to the wrong parent here. I can assert 'heart development' (primary circulatory organ development) to be part_of 'cardiovascular system development'. 
But it seems like there is still an issue in UBERON. 'heart development' in GO refers to 'primary circulatory organ'. 'Primary circulatory organ' is_a 'circulatory organ'. 'Circulatory organ' is part_of 'circulatory system'. Based on the defs and the wide taxonomic scope desired, would it make sense to make the logical definition of cardiovascular system be 'anatomical system' and ('part of' some 'circulatory system') and ('has part' some 'primary cardiac organ') and ('has part' some 'blood vessel')?

**Comment by ukemi** [comment]
One use case for lumping is that IIRC the experts we had when we did the heart development work wanted to see all 'hearts' collected under a single term in GO. See the notes here:
http://wiki.geneontology.org/index.php/Minutes_Heart_Development_workshop_(Archived)
This doesn't mean we can't change, but at the time, that was the decision.

**Comment by RLovering** [comment]
Following Helen's comment: 'moving heart dev under "cardiovascular system development" seems an easy win'
if this is possible I would support this
Ruth

**Comment by ukemi** [comment]
Does cardiovascular work for flies; with an open circulatory system? Where is the blood vessel part? I guess we could consider the dorsal vessel a blood vessel as well as the primary cardiac organ.

**Comment by balhoff** [comment]
I don't want to add too much confusion to the discussion, but it seems like with the right axioms and only slightly fancier tools, we could infer that genes involved in heart development and *known to be in vertebrates* are also involved in cardiovascular system development.

**Comment by hattrill** [comment]
> Does cardiovascular work for flies; with an open circulatory system? Where is the blood vessel part? I guess we could consider the dorsal vessel a blood vessel as well as the primary cardiac organ.

yes, I think so - the dorsal vessel has an 'aorta' part that is non-contractile, that could be considered 'vasculature'.

**Comment by ukemi** [comment]
Perfect! I will change the heirarchy in GO.

**Comment by ukemi** [comment]
I still think @balhoff has the right idea in his comment above. I think we were always pretty clear about these kinds of terms in GO, especially when we had worked with experts. We always asked them the taxonomic scope when we did the development work. Seems that what we need is a little more sophistication when integrating with other ontologies.

**Comment by pgaudet** [comment]
To be discussed on another call, with @hattrill and @RLovering 
Suggestion on today's editors call is to create some 'sensu' types (for eg, 'vertebrate-type heart / insect-type heart)

**Comment by hattrill** [comment]
Just to back up for a minute, 
@cmungall, just looking at this example that you cited: "For example, currently in Uberon 'heart' traces back to neural crest cells which is obviously only applicable in vertebrates."
As far as I can see, cardiac neural crest cells only give rise to a subset of structures of the vert heart. The vert heart is predominantly derived from the mesoderm rather than the ectoderm.

**Comment by pgaudet** [comment]
Decisions on ontology call: 

 -[] obsolete or merge cardiovascular system development, consider circulatory system development. 

Changes will be made to uberon that will make GO and Uberon more consistent.

**Comment by ukemi** [comment]
I think based on the number of annotations, it would be better to merge. I will also correct the logical definition of heart morphogenesis, which somehow escaped the previous corrections.

**Comment by pgaudet** [comment]
@ukemi Do you have time to do this one ? I'd like to clean up the taxon problems. 

Let me know if I can help. 

Thanks, Pascale
