### ISSUE TITLE
acyltransferases - new terms

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#19465]
Dear GO annotators,

Would you please consider creating these new terms:
1. 1-acylglycerophosphoethanolamine O-acyltransferase activity
    Reaction=a 1-acyl-sn-glycero-3-phosphoethanolamine + an acyl-CoA = a 1,2-diacyl-sn-glycero- 
    3-phosphoethanolamine + CoA [Rhea:32995]
    EC=2.3.1.n7

2. 1-acylglycerophosphoserine O-acyltransferase activity
   Reaction=a 1-acyl-sn-glycero-3-phospho-L-serine + an acyl-CoA = a 1,2-diacyl-sn-glycero-3- 
   phospho-L-serine + CoA [Rhea:33191]
   EC=2.3.1.n6

  as children of 
  GO:0008374  O-acyltransferase activity

for reference please see PMID:18287005

Thank you very much for your help.

Nevila Hyka-Nouspikel

**Comment by hdrabkin** [comment]
Hi; we cannot use the EC xrefs as they  refer to possibly pending entries. However, thanks for supplying the RHEA, which is the one we would use as a def ref. 
I will make these children of the grouping term coresponding to EC.2.3.1.-

**Comment by nnouspikel** [comment]
Sounds good. Thank you Harold.

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106262
+name: 1-acylglycerophosphoethanolamine O-acyltransferase activity

+[Term]
+id: GO:0106263
+name: 1-acylglycerophosphoserine O-acyltransferase activity
