### ISSUE TITLE
EC xref issues on peptidase terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19463]
id: GO:0034701
name: tripeptidase activity
xref: EC:3.4.13
=> remove this EC (this is for **di**peptidases - GO:0016805)

id: GO:0008239
name: dipeptidyl-peptidase activity
&
id: GO:0008240
name: tripeptidyl-peptidase activity
xref: EC:3.4.14
=> either both or neither of these terms should have this EC (which is for "Dipeptidyl- and tripeptidyl-peptidases")

id: GO:0070005
name: cysteine-type aminopeptidase activity
xref: EC:3.4.18
=> remove this EC (its for cysteine-type **carboxy**peptidases - GO:0016807)

id: GO:0016920
name: pyroglutamyl-peptidase activity
xref: EC:3.4.19
=> either remove this EC (it's for the parent term, GO:0008242) or maybe put both EC:3.4.19.3 & EC:3.4.19.6??

id: GO:0070008
name: serine-type exopeptidase activity
xref: EC:3.4.21
=> remove this EC (it's for serine-type **endo**peptidases - GO:0004252)

id: GO:0042500
name: aspartic endopeptidase activity, intramembrane cleaving
xref: EC:3.4.23
=> not sure about this EC..strictly, this partial EC is for the parent "aspartic-type endopeptidase activity" GO:0004190 term

**Comment by hdrabkin** [comment]
Gathering notes
GO:0034701    EC:3.4.11.4 (Tripeptide aminopeptidase.)
This EC can be applied to this and also GO:0008240
EC:3.4.14 can be both di and tri (grouping term)
EC 3.4.19.3 suitable for GO:0016920

**Comment by sjm41** [comment]
Hi @hdrabkin 
I just came across some of these issues again - can we proceed with fixing the above?

**Comment by sjm41** [comment]
Hi @hdrabkin @pgaudet 

This ticket is ~2 years old.  Can we fix these five EC xref issues -  I think they are relatively straightforward?

**Comment by sjm41** [comment]
Excellent, thanks.
Out of interest, what you did you decide to do with GO:0016920 - no EC xref, or add  EC:3.4.19.3 & EC:3.4.19.6.  Looking at things like GO:0008239, seems like policy would be to add both those ECs?

**Comment by hdrabkin** [comment]
These were already used as dbxrefs for the definition. I have added them to the xrefs as narrow matches  I have also replaced the two ecs in the def refs with PMID:9920379, a review article covering all types of this activity.
