### ISSUE TITLE
NTR: heme transmembrane transporter activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19472]
descendant of
heme transporter activity (GO:0015232)

def: standard TM transporter + heme
parent of
GO:0015439    ATPase-coupled heme transmembrane transporter activity

(for a non ATPase heme transporter)

ref PMID:29549126

**Comment by ValWood** [comment]
Or rejig GO:0015232 if all are TM?

**Comment by pgaudet** [comment]
Looks like all proteins annotated to GO:0015232 heme transporter activity are TM transporters, except for http://amigo.geneontology.org/amigo/gene_product/GeneDB:Tb927.6.440:mRNA
which may be an endocytic receptor - can you check ? I can't access the paper. 
Thanks, Pascale

**Comment by pgaudet** [comment]
@Achchuthan Can you please check if GeneDB:Tb927.6.440:mRNA is a cargo receptor? In that case we would need to create a child of 'GO:0038024 cargo receptor activity' to capture the activity. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Changed label to 'heme transmembrane transporter activity'

**Comment by pgaudet** [comment]
@deustp01 
The following Reactome mappings could be more precise: 
*  R-HSA-917979 
*  R-HSA-5683355 
*  R-HSA-382560 
*  R-HSA-1369065 

-> Suggest to use GO:0015439 ATPase-coupled heme transmembrane transporter activity

Thanks, Pascale

**Comment by ValWood** [comment]
Yep for T. briucei  it looks like
GO:0140312   cargo adaptor activity
endocytic adaptor activity | narrow

**Comment by deustp01** [comment]
Yes, the more exact term works for all four Reactome instances. The changes will appear in our June 2020 release.
This is the sort of QA that we hoe to generalize applying GO reasoners to GO-CAM versions of Reactome pathways to detect instances where an alternative GO term looks better - here, transport plus ATP consumption suggests ATPase-coupled transport.

**Comment by pgaudet** [comment]
Now that Reactome has addressed this I will close the ticket.
