### ISSUE TITLE
cessation of reasoning over ChEBI roles, i.e. stop inferring relationships like "ATP binding" is_a "drug binding"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#19479]
**Summary of decision from ontology editors calls on 5/4/20 & 5/18/20:**

Due to the fact that reasoning over ChEBI roles and then creating relationships like "ATP binding" is_a "drug binding" or  "cocaine binding" is_a "drug binding" is creating relationships that we do not want, we are planning to stop doing this reasoning. We recognize that this is not a final solution because removing these inferences may remove relationships that we do want as well as the ones that are causing problems. However, we feel that removing these inferences now is better than waiting until we have time to work through all of the ChEBI roles we are currently utilizing in the ontology. As we work through the various ChEBI roles we use in the ontology, we will put back in any relationships that we do want to have present.

With respect to implementation, the plan is to change the logical definitions of the GOCHE terms so that we break their links to ChEBI, rather than to remove the logical definitions of the GO terms that utilize GOCHE terms (@cmungall & @balhoff - correct this if I misunderstood).

This was mentioned in the status report on the ChEBI roles project at the virtual GOC meeting on 5/13/20 and support for removing these inferences and thus the resulting errors was voiced.

**Comment by krchristie** [comment]
@balhoff - I think you've done this now and I can close this ticket. Is that correct?

**Comment by balhoff** [comment]
Done.
