### ISSUE TITLE
tripeptidyl-peptidase activity (GO:0008240) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19475]
Currently we have this:
id: GO:0008240
name: tripeptidyl-peptidase activity
def: "Catalysis of the release of an N-terminal tripeptide from a polypeptide." [GOC:mah]
is_a: GO:0008236 ! serine-type peptidase activity
is_a: GO:0008238 ! exopeptidase activity

Seems that dual parentage could be replaced with the single parent:
serine-type aminopeptidase activity (GO:0070009)

**Comment by ukemi** [comment]
Makes sense to me based on the definitions. Sanity check @deustp01?
