### ISSUE TITLE
phospholipid scramblase activity, odd comment

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19470]
It's confusing to have all the stuff about flippases and floppases, on a term which is not a flippase or a floppase.

GO:0017128    phospholipid scramblase activity

Definition (GO:0017128 GONUTS page)
Catalysis of the movement of phospholipids from one membrane bilayer leaflet to the other, by an ATP-independent mechanism. PMID:20043909 PMID:20302864

Comments
Nomenclature note. Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane. Flippases and floppases are ATP-dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature, they catalyze lipid transfer towards the inward monolayer (flippases) or towards the outward monolayer (floppases). Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements (PMID 20043909).

**Comment by RLovering** [comment]
Hi Val
having spent a considerable time making sure these terms were used appropriately perhaps some mention could be made of these sibling terms. If only to state that if there is evidence from the paper or from the domains of the protein/family members that it has ATPase activity then this term should not be used, and the siblings or parent considered?

Best

Ruth

**Comment by ValWood** [comment]
perhaps  instead

Note. Scramblases are ATP-independent, non-selective, **translocases** inducing non-specific transbilayer movements across the membrane.  **if you require  ATP-**dependent transbilayer lipid translocators i.e. Flippases (catalyze lipid transfer towards the inward monolayer) or floppases  (towards the outward monolayer) please refer to GO:0140326 and descendants. 


I think you should leave this part out:
Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements (PMID 20043909).

The precise defs and the  reinforcing comment should suffice. I don't think we should say " almost universal" we are with the consensus here.

Also  shouldn't this parent term
GO:0140303   intramembrane lipid transporter activity
have exact synonym "translocase" ? 

What do you think?  . I couldn't at first figure out what the comment was trying to tell me, but figured it out because I knew the history.

**Comment by pgaudet** [comment]
@marcfeuermann and I worked on this together. The literature is using both a bit interchangeably, which is why we added this comment. It took Marc and I a while to figure out what it all meant. 

If that comment is too confusing for users I can remove it.

**Comment by ValWood** [comment]
I think a comment here is good. It just needs a little tweaking. There were definitely some words missing too !

I understood what the information was for but only because I had followed the topic and   updated  my annotations.  It just needs to be a bit  clearer. If I haven't got it quite right we can go through it when we next speak just to make sure  we are all on the right page. Maybe we could tag it onto the end of a transcription call, so Ruth can also  approve the comment?

**Comment by ValWood** [comment]
Also  @marcfeuermann could you check my comments and suggest any revision?

**Comment by marcfeuermann** [comment]
Hi Val and all,
First of all, sorry for this late reply, busy times. I hope you are all doing fine. In the literature, the terms scramblase, flippase and floppase or often not used appropriately. Some papers use flippase (and others floppase) as a general term for all these activities. This is why we wanted to insist on the specificity of each by adding this note. 
However, I may understand that the note is a little bit long, especially since it is not mentioning scramblases. I would not have any concern to leave out the last sentence, which is indeed not essential, but keep the rest.
Regards,
Marc.

**Comment by ValWood** [comment]
I  would like to clarify. I think there **should** be a note. It's just that the note was also slightly confusing. It has a few problems . Some words are missing, and  it isn't immediately clear why the information is being provided. My solution might not be better but  it is a  slight improvement.

If we state the difference the final sentence should not be required. Adding it only points out that some people use the term incorrectly, and thereby makes the consensus definition fuzzy again.

However, if you think the final sentence

"Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements (PMID 20043909)."

 is also useful, I don't have any objection to keeping this . It's was  the first part that was particularly  unclear.  As a reader I needed to know why this information was being provided in the scramblase  comment before 2 sentences describing flippases and floppases. I lost the thread and I needed to read it twice to get why this information was there, because this wasn't given until the end.

**Comment by ValWood** [comment]
@pgaudet  this should be quick. I'm not so bothered about this, I just found the comment slightly confusing   for the term I was looking at. But if you put the missing words in I think it is fine.

**Comment by pgaudet** [comment]
New note is: 

comment: Nomenclature note. Flippases and floppases are ATP-dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature, they catalyze lipid transfer towards the inward monolayer (flippases) or towards the outward monolayer (floppases). Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane. The direction of the translocation should be taken into account for annotation.

OK ???

**Comment by ValWood** [comment]
I think this is fine. Note that the comment is on the related terms too, not just GO:0017128
so needs updating on all.
