### ISSUE TITLE
omega peptidase activity (GO:0008242) - def and children

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19473]
Currently we have this:
**id: GO:0008242
name: omega peptidase activity
def: "Catalysis of the removal of terminal peptide residues that are substituted, cyclized or linked by isopeptide bonds (peptide linkages other than those of alpha-carboxyl to alpha-amino groups)." [EC:3.4.19.-]
xref: EC:3.4.19
is_a: GO:0008238 ! exopeptidase activity**

which has these 4 children:
GO:0036374    glutathione hydrolase activity
GO:0016920    pyroglutamyl-peptidase activity
GO:0008798    beta-aspartyl-peptidase activity
GO:0034722    gamma-glutamyl-peptidase activity

But the EC page for 3.4.19- (https://enzyme.expasy.org/EC/3.4.19.-) also includes Ubiquitinyl hydrolase 1 with EC:3.4.19.12.
This suggests that "thiol-dependent ubiquitinyl hydrolase activity" (GO:0036459), that has EC:3.4.19.12 as an xref, should also be a child of "omega peptidase activity".

This is the current GO entry for that term:
**id: GO:0036459
name: thiol-dependent ubiquitinyl hydrolase activity
def: "Catalysis of the thiol-dependent hydrolysis of an ester, thioester, amide, peptide or isopeptide bond formed by the C-terminal glycine of ubiquitin." [EC:3.4.19.12, GOC:bf, GOC:ka]
xref: EC:3.4.19.12
is_a: GO:0019783 ! ubiquitin-like protein-specific protease activity
is_a: GO:0101005 ! ubiquitinyl hydrolase activity**

That def appears to be incompatible with the term being a child of "omega peptidase activity", given that latter's definition is specific to "isopeptide bonds".  But I think that's because the current "omega peptidase activity" def is too strict.
Compare it with the entry in the MEROPS database:
Omega-peptidase
_The omega-peptidases form the second group of peptidases that have no requirement for a free N-terminus or C-terminus in the substrate. Despite their lack of requirement for a charged terminal group, they often act close to one terminus or the other, and are thus totally distinct from endopeptidases. Some hydrolyse peptide bonds that are not alpha-bonds; that is, they are isopeptide bonds, in which one or both of the amino and carboxyl groups are not directly attached to the alpha-carbon of the parent amino acid. The omega-peptidases are a varied assortment of enzymes, including ubiquitinyl hydrolases (e.g. ubiquitinyl hydrolase-L3, C12.003), pyroglutamyl peptidases (C15.001, C15.010, M01.008) and gamma-glutamyl hydrolase (C26.001). The omega-peptidases are placed in sub-subclass EC 3.4.19 by NC-IUBMB._
https://www.ebi.ac.uk/merops/about/glossary.shtml#OMEGA-PEPTIDASE

Note that this description says that omega peptidases have "no requirement for a free N-terminus or C-terminus", which suggests GO:0008242 (omega peptidase activity) should not be a direct child of 'exopeptidase activity'.

So it looks like we should:
1. Add "thiol-dependent ubiquitinyl hydrolase activity" as a child of "omega peptidase activity"
2. Change the def of "omega peptidase activity", perhaps modeling it on the MEROPS entry.
3. Change the parent of "omega peptidase activity" from "exopeptidase activity" to "peptidase activity, acting on L-amino acid peptides" (GO:0070011)?

**Comment by hdrabkin** [comment]
How about 'a peptidase that does not cleave standard peptide bonds.'
Encyclopedia of Molecular Pharmacology; (I'll get an ISBN).
Maybe add some details from MEROPS .  This is a grouping term corresponding to a 3 digit EC , but I'd still like to get a reference if possible.

**Comment by hdrabkin** [comment]
https://doi.org/10.1007/978-3-540-38918-7

**Comment by sjm41** [comment]
Thanks Harold.
I also found this from PMID: 20157488:
_"Some omega peptidases (peptidases which do not cleave normal peptide bonds but release substituted amino acids such as pyroglutamate or cleave isopeptide bonds, such as many deubiquitinating enzymes)..."_
Which is consistent with the Encyclopedia of Molecular Pharmacology def, but adds some examples.

**Comment by hdrabkin** [comment]
I went with
'Catalysis of the cleavage of non-standard peptide bonds  releasing substituted amino acids such as pyroglutamate or cleave isopeptide bonds, such as many deubiquitinating enzymes.'

**Comment by hdrabkin** [comment]
everything is done here; going after the associated ticket.

**Comment by sjm41** [comment]
Thanks again Harold!
