### ISSUE TITLE
intramembrane lipid transporter activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19477]
Molecular Function GO:0140303    intramembrane lipid transporter activity
Definition Enables the transport of a lipid from a region of a membrane to a different region on the same membrane. 
PMID:16828084

add synonym.  "translocase activity" broad

translocase is used in different contexts but this is the most common context so it would be good if this term was found with a search on "translocase".

Also the definitions a little odd.
This reads to me that the movement is within one leaflet of  a membrane. 

Would

Enables the transport of a lipid from a  one surface of a lipid bilayer to the other in the same membrane.

be better?

**Comment by krchristie** [comment]
I think this term may be broader than just translocases. If so, I think it would make more sense if the translocase synonyms were placed on the actual terms for the translocase activities. Here's the tree:

![lipidTransporterTree](https://user-images.githubusercontent.com/10533218/82253400-c65b9b80-9905-11ea-9d18-52836d7c6bda.png)

**Comment by ValWood** [comment]
@pgaudet ?

I  think intramembrane transporters are all translocases (moving the lipid from one side to another), BUT because translocase is also used in other contexts it would need to. be "narrow"
(Or would that be related?)

**Comment by krchristie** [comment]
This is the nomenclature note on the term for `phospholipid scramblase activity`, which is also a child term of `intramembrane lipid transporter activity`. Thus, I think it would make more sense to put the `translocase` synonyms on the terms `flippase activity` and `floppase activity` which are types of trannslocases.

> Nomenclature note. Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane. Flippases and floppases are ATP-dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature, they catalyze lipid transfer towards the inward monolayer (flippases) or towards the outward monolayer (floppases). Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements (PMID 20043909).

**Comment by ValWood** [comment]
But phospholipid scramblase is also a tranlocase isn't it ?

@RLovering ?

**Comment by ValWood** [comment]
@krchristie see comment about the comment here:
https://github.com/geneontology/go-ontology/issues/19470

My understanding is that ALL are translocases, but some are ATP dependent and some are ATP-independent.

 I assumed that this note was missing the word "translocase"
Nomenclature note. Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane.

was missing the word "translocase"

here
Scramblases are ATP-independent, non-selective TRANSLOCASES, inducing non-specific transbilayer movements across the membrane.

because otherwise the phrase is incomplete- there is no noun.

I found the  note confusing, so I suggested a rewrite and the addition of the translocase synonym to fix this.


@RLovering  is that correct?

**Comment by krchristie** [comment]
> But phospholipid scramblase is also a tranlocase isn't it ?

If phospholipid scramblase are also callsed tranlocases, I withdraw my objection

**Comment by ValWood** [comment]
It's confusing but I think they are.

See
https://en.wikipedia.org/wiki/Phospholipid_scramblase

As I understand it  any molecule that does translocation is a translocase

**Comment by pgaudet** [comment]
'Translocase' is confusing. EC has created a new class 7 that describe *all* transporters: 

https://enzyme.expasy.org/EC/7.-.-.-

So if we go by that, we could add translocase as a synonym of any activity having to do with transport. 

If it helps I dont mind adding more synonyms. Broad makes sense.

**Comment by ValWood** [comment]
AS far as I'm aware "translocase" is only used for some subclasses of transporters. I have never managed to work out exactly which and why, but I  would probably not add it everywhere. I would only add it to the things which people often refer to as translocases. Otherwise it will hinder the searching rather than help it.

**Comment by ValWood** [comment]
In summary, I think this is OK

add synonym. "translocase activity" broad
