### ISSUE TITLE
obsolete: drug binding

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#19480]
As described in the ticket: **handling terms for xenobiotic role and removing drug role** #19460, we have decided to obsolete the term `drug binding` since referring to the role of `drug` does not provide a meaningful functional description of what kind of binding is occurring. We will request that groups that have used this term review their annotations and annotate to a chemically meaningful term instead, if possible.

**Comment by krchristie** [comment]
Based on just a couple annotations I tried to review, I think the ontology editors need to discuss what we would like to happen during reannotation of this term. I'll put some examples in.

**Example 1**
- UniProtKB:Q99720
- Sigma non-opioid intracellular receptor 1
- PINC
- NCBITaxon:9606
- TAS
- PANTHER:PTHR10868
- PMID:8954936
- 20030904

Kekuda R, et al. Cloning and functional expression of the human type 1 sigma receptor (hSigmaR1). Biochem Biophys Res Commun. 1996 Dec 13;229(2):553-8. PMID:8954936.
- paper describes cloning using Vaccinia expression system with haloperidol as the binding target since the in vivo target of sigma receptors is not known.
- haloperidol (CHEBI:5613) - a compound composed of a central piperidine structure with hydroxy and p-chlorophenyl substituents at position 4 and an N-linked p-fluorobutyrophenone moiety.
- looking at ChEBI structure and def of haloperidol, thought that `hydroxypiperidine binding`(new GO term using CHEBI:48590) would be a reasonable choice to make a replacement annotation
- BUT noticed existing GO term 
-- `thienylcyclohexylpiperidine binding` [thienylcyclohexylpiperidine = TCP = tenocyclidine (ChEBI:64610)]
-- `thienylcyclohexylpiperidine binding` has 3 annotations in AmiGO: 1 IMP (rat), 1 IEA (human), 1 ISO (mouse)
-- paper (PMID:7488117) describes cloning "a 60 kDa synaptic membrane glycoproteinthat had Gly, L-Glu, and TCP recognition sites"
-- ChEBI defines tenocyclidine as "A tertiary amino compound that consists of cyclohexane having piperidin-1-yl and thiophen-2-yl groups attached at position 1."
-- What ChEBI parent is most relevant? `tertiary amino compound`, `piperidenes`, or `thiophenes`??? I don't feel I can make a good choice about one of the three equally relevant ChEBI parent terms in order to suggest annotation to that parent term with tenocyclidine as an extension.

**Question to discuss**: We've been saying how GO is supposed to represent normal biology. Both  [haloperidol](https://en.wikipedia.org/wiki/Haloperidol) and [tenocyclidine](https://en.wikipedia.org/wiki/Tenocyclidine) appear to be synthetic compounds rather than natural ones. However, both appear to be used in this context as stand-ins for some biologically relevant binding. What do we want to have in the ontology?

**Comment by krchristie** [comment]
**Example 2**
- **Gene**: FK506 binding protein 1a (MGI:MGI:95541)
- **GO term**: drug binding (GO:0008144)
- **Contributor**: MGI
- **Taxon**: NCBITaxon:10090 
- **Evidence**: IDA
- **Panther**: PANTHER:PTHR10516
- **Reference**: PMID:15467718
- **Date**: 20081208

Jacinto et al. 2004. Mammalian TOR complex 2 controls the actin cytoskeleton and is rapamycin insensitive. Nat Cell Biol. 6(11):1122‐1128. PMID:15467718

* Paper describes use of rapamycin binding to Fkbp1a (aka Fkbp12) to determine of mammalian cells have a rapamycin-insensitive TOR2 pathway similar to that in _S. cerevisiae_.
* **rapamycin, aka sirolimus (CHEBI:9168) - ChEBI Def:** A macrolide lactam isolated from _Streptomyces hygroscopicus_ consisting of a 29-membered ring containing 4 trans double bonds, three of which are conjugated. It is an antibiotic, immunosupressive and antineoplastic agent.
* GO does not currently have a term for `macrolide lactam binding`, which seems like it would be the closest available classification from ChEBI.
* GO does have a term for `macrolide binding`, which has one child term `FK506` binding. Note that in ChEBI, FK506 (aka tacrolimus) is also classified as a `macrolide lactam`.
* Both rapamycin (aka sirolimus) and FK506 (aka tacrolimus) are natural products from different species of _Streptomyces_, they are exogenous compounds with respect to the various species from yeast to mammals that they are used to study. Although both compounds are quite similar in structure and bind to the same target, Fkbp1a (aka Fkbp12), rapamycin and FK506 have different immunosuppressive effects on T cells, with the mechanism of FK506 being similar to that of cyclosporin A (though this is structurally different from FK506). https://doi.org/10.1016/B978-012526451-8/50015-1
* GO already has a MF term for `FK507 binding` as well as two BP terms related to rapamycin that are all used for annotations.

GO term | # annots | # EXP | # SEQ | # IEAs
-- | -- | -- | -- | --
response to rapamycin (GO:1901355)  | 7 | 5 | 1 | 1
cellular response to rapamycin (GO:0072752)  | 18 | 6 | 6 | 6
FK506 binding (GO:0005528) | 91 | 12 | 26 | 46

**Question to discuss:** These are natural compounds for an organism, but not for the organisms they are used to study. However, they are widely used. For example, rapamycin is used to experimentally distinguish the TOR1 versus the TOR2 pathways. How do we want to deal with these types of compounds?

**Comment by RLovering** [comment]
HI Karen

this is very interesting. For completeness you missed these 2:

UniProtKB:Q9HAW7-1 | UGT1A7 | enables | GO:0008144                drug binding | ECO:0000314              IDA | PMID:20610558 |   | 9606 Homo sapiens | BHF-UCL | has_input                (CHEBI:27656)
UniProtKB:Q9HAW9-1 | UGT1A8 | enables | GO:0008144                drug binding | ECO:0000314              IDA | PMID:20610558 |   | 9606 Homo sapiens | BHF-UCL | has_input                (CHEBI:168396)

It looks like there are in total 11 exp drug binding annotations with AE chemicals https://www.ebi.ac.uk/QuickGO/annotations?extension=has_input(ChEBI&goId=GO:0008144&goUsageRelationships=is_a,part_of,occurs_in&goUsage=descendants but you have only listed 6?

Thanks

Ruth

**Comment by krchristie** [comment]
> It looks like there are in total 11 exp drug binding annotations with AE chemicals https://www.ebi.ac.uk/QuickGO/annotations?extension=has_input(ChEBI&goId=GO:0008144&goUsageRelationships=is_a,part_of,occurs_in&goUsage=descendants but you have only listed 6?

The table is a summary that compresses similar lines into a single row. Thus the annotations for human & pig Amiloride-sensitive amine oxidase are shown in a single line. The annotations for metallothioneins 2 & 3 with extensions to both cisplatin & transplatin are in a single line. Annotations from 2 different papers for sheep prostaglandin G/H synthase are combined in a single line.

**Comment by krchristie** [comment]
> this is very interesting. For completeness you missed these 2:
> 
> UniProtKB:Q9HAW7-1 | UGT1A7 | enables | GO:0008144 drug binding | ECO:0000314 IDA | PMID:20610558 |   | 9606 Homo sapiens | BHF-UCL | has_input (CHEBI:27656)
> UniProtKB:Q9HAW9-1 | UGT1A8 | enables | GO:0008144 drug binding | ECO:0000314 IDA | PMID:20610558 |   | 9606 Homo sapiens | BHF-UCL | has_input (CHEBI:168396)

These are not present in AmiGO. I checked both my spreadsheet of what I downloaded yesterday and went back to AmiGO today and I don't see them there. I notice that these are annotations to UniProt isoforms so it might be worth checking if AmiGO has other annotations made directly to UniProt isoforms. 

I will edit my earlier comment with updated my tables that include these two additional annotations the the referenced ChEBI compounds.

**Comment by krchristie** [comment]
**Example 3**
- **Gene**: 5-hydroxytryptamine (serotonin) receptor 1E (MGI:MGI:96279)
- **GO term**: drug binding (GO:0008144)
- **Contributor**: MGI
- **Taxon**: NCBITaxon:10090
- **Evidence**: IDA
- **Panther**: 
- **Reference**: PMID:1328180
- **Date**: 20101202


Amlaiky et al. 1992. Isolation of a Mouse “5HTlE-like” SerotoninReceptor Expressed Predominantly in Hippocampus. JBC 267(28):19761-19764. PMID:1328180
- cloning of cDNAs that hybridize in non-stringent conditions to 5HT1B-like or 5HT1D-like receptors => 1 clone = 5HT1E-beta
- transfected clone into Cos-7 cells & assayed membranes for ability to bind several serotonergic ligands => binds LSD
- pharmocological profile by testing for compounds that can displace LSD: methysergide > bufotenine > sumatriptan > 5-HT (serotonin)
- in stable cell lines (NIH-3T3 which don't express endogenous serotonin receptors), shows coupling to adenylate cyclase


**Proposed action**: It's clear that they are using a variety of serotonergic ligands: methysergide > bufotenine > sumatriptan > 5-HT (serotonin) > LSD. Though it's hard to determine from the paper, 5-HT (5-hydroxytryptamin) is a name for serotonin itself.
- change `drug binding` annotation to `serotonin binding`
- consider adding 5-HT & 5-hydroxytryptamin synonyms to serotonin terms

**Comment by krchristie** [comment]
**Example 2**
- **Gene**: glycine receptor, beta subunit (MGI:95751)
- **GO term**: drug binding (GO:0008144)
- **Contributor**: MGI
- **Taxon**: NCBITaxon:10090
- **Evidence**: IPI
- **References**: PMID:6285205 & PMID:2983837
- **Date**: 20140918 (originally 20061206)


White & Heller. 1982. Glycine receptor alteration in the mutant mouse spastic. Nature. 298 (5875) 655-7



White. 1985. The glycine receptor in the mutant mouse spastic (spa): strychnine binding characteristics and pharmacology. Brain Res. 329 (1-2) 1-6

**Comment by krchristie** [comment]
In addition to direct annotations to `drug binding`, here are the directly asserted terms that remain under `drug binding` after removal of reasoning over ChEBI roles, and counts of _**experimental**_ annotations to these terms (as of 6/11/2020).

![drugBinding-assertedChildTerms](https://user-images.githubusercontent.com/10533218/84554139-6de0a980-accb-11ea-8e5a-7074e53e4f50.png)

![directEXPannots-drugBindingNchildTerms](https://user-images.githubusercontent.com/10533218/84554147-789b3e80-accb-11ea-8ee0-ce8bd7006445.png)

**Comment by krchristie** [comment]
What do we think of terms like `[cellular] response to x` where x = 
- Aroclor 1255
- carboplatin
- cisplatin
- fluoxetine
- tacrolimus
- Thyroglobulin triiodothyronine
- topoisomerase inhibitor
- tunicamycin
- aromatase inhibitor

**Comment by deustp01** [comment]
Do any of these entities have a physiological role, e.g., as parts of normal metabolic or signaling processes, in the biological contexts in which their effects on cells are being studied?

Tacrolimus, for instance, has metabolic and, perhaps, host defense functions in the soil bacteria that make it, and perhaps annotatable functions in the soil microorganisms that are sensitive to it, but what is normal and annotatable about its effect on human T cells that isn't better captured by annotations directed at the normal function of its human target protein and maybe consequences of perturbing that function?

Even though the word "drug" is not in the term name, it looks like the function is meant to be a drug function in the context where the term would be used, except maybe sometimes for thyroglobulin.

**Comment by deustp01** [comment]
On the remaining binding terms, it seems like the distinction in the previous comment is relevant - there are times when binding penicillin or cocaine is a normal physiological function, but it looks like a matter of editorial control at the level of annotation to retrisct usage of these terms to those times.

**Comment by krchristie** [comment]
`response to tacrolimus` is not used at all for annotations. 

`response to cocaine` is used in annotations (277 total, 116 experimental). Here are the counts by organism:

![responseToCocaine-EXP-organisms](https://user-images.githubusercontent.com/10533218/84678760-3ea58480-aee5-11ea-8623-b4525233b29b.png)

**Comment by krchristie** [comment]
**Discussion at Ontology Editors Call - 6/15/2020**
- Where a compound is being applied as a proxy for a known biologically relevant substrate, e.g. Examples 1 (LSD vs serotonin) & 2 (strychnine vs glycine), we can annotate to the appropriate biologically relevant compound, e.g. serotonin or glycine.

**Comment by krchristie** [comment]
[Wikipedia entry for MTOR](https://en.wikipedia.org/wiki/MTOR)

> In 1989–90, FK506 and rapamycin were determined to inhibit T-cell receptor (TCR) and IL-2 receptor signaling pathways, respectively.[19][20] The two natural products were used to discover the FK506- and rapamycin-binding proteins, including FKBP12, and to provide evidence that **FKBP12–FK506 and FKBP12–rapamycin might act through gain-of-function mechanisms** that target distinct cellular functions.

**Comment by krchristie** [comment]
Table of annotations to `drug binding` by contributor:
![drugBinding-table-annotsByContrib](https://user-images.githubusercontent.com/10533218/85177241-90754400-b230-11ea-85fe-8907c345cefe.png)

**Comment by pgarmiri** [comment]
Hi Karen,
Is there a spreadsheet with the annotations to be checked?
Thanks,
Penelope

**Comment by bmeldal** [comment]
Complex Portal done.

**Comment by krchristie** [comment]
Yes, the link is in annotation ticket: https://github.com/geneontology/go-annotation/issues/3166

**Comment by pgaudet** [comment]
We announced we'd obsolete this term 1 year ago - I think we can go ahead?

**Comment by krchristie** [comment]
> We announced we'd obsolete this term 1 year ago - I think we can go ahead?

Yes, I can go ahead. Basically, it fell of the top of my to do list when my priorities were shifted to new tickets above the ChEBI roles project.
