### ISSUE TITLE
suggest name disambiguation of GO:0009011 / GO:0004373

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#19489]
The names of these functions clash, better differentiation would be mentioning (ADP / UDP):
```
id: GO:0009011
name: starch synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: ADP-glucose + (1,4)-alpha-D-glucosyl(n) = ADP + (1,4)-alpha-D-glucosyl(n+1)." [EC:2.4.1.21]
```
```
id: GO:0004373
name: glycogen (starch) synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-glucose + (1,4)-alpha-D-glucosyl(n) = UDP + (1,4)-alpha-D-glucosyl(n+1)." [EC:2.4.1.11]
```

**Comment by ukemi** [comment]
I'll need to check the official enzyme name.

**Comment by ukemi** [comment]
According to EC, these are the accepted names for these enzymes. I will update the synonyms to align with EC, but it is our standard practice to use the accepted names given to the enzymes to describe the activities.
