### ISSUE TITLE
COG complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19482]
COG complex current definition

Definition | Parents
-- | --
A multisubunit tethering complex of the CATCHR family (complexes associated with tethering containing helical rods) that has a role in tethering vesicles to the Golgi prior to fusion. In yeast, this complex is called the Sec34/35 complex and is composed of eight subunits (Sec34p, Sec35p, Dor1p, Cod1p, Cod2p, Cod3p, Cod4p, and Cod5p). In mammals the subunits are named COG1-8.

Please delete
In yeast, this complex is called the Sec34/35 complex and is composed of eight subunits (Sec34p, Sec35p, Dor1p, Cod1p, Cod2p, Cod3p, Cod4p, and Cod5p). In mammals the subunits are named COG1-8.

And replace with:
Composed of 8 subunits COG1-8

because S. cerevisiae  (and everyone) uses the COG  nomenclature:

e.g.   SGD 
Description
Essential component of the conserved oligomeric Golgi complex; a cytosolic tethering complex (Cog1p through Cog8p) that functions in protein trafficking to mediate fusion of transport vesicles to Golgi compartments 1

**Comment by hdrabkin** [comment]
done
