### ISSUE TITLE
neurotransmitter transport parentage, taxon violations

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#19492]
While @lreiser was reviewing TAIR's GORULE:13 taxon violation report, we found that some were due to annotations of A. thaliana genes to the following terms, which all have the parent 'neurotransmitter transport' or 'neurotransmitter transmembrane transporter activity' that are restricted to Metazoa.

GO:0051938 | L-glutamate import
GO:0015185 | gamma-aminobutyric acid transmembrane transporter activity
GO:0015183 | L-aspartate transmembrane transporter activity
GO:0015220 | choline transmembrane transporter activity
GO:0015871 | choline transport
GO:0015812 | gamma-aminobutyric acid transport
GO:0015813 | L-glutamate transmembrane transport
GO:0098712 | L-glutamate import across plasma membrane

Please consider removing that parentage for these terms. This may be covered by the whole removal of ChEBI roles umbrella. If so, please confirm.  We will leave these annotations as they are.

**Comment by lreiser** [comment]
as a follow up here is an example of choline transport in plants

https://www.nature.com/articles/ncomms5276.pdf?origin=ppub

There are likely many other cases where a compound produced in an organism serves one function in that organism but a different function in another organism, cannabinoids come to mind.

**Comment by ukemi** [comment]
This should be covered by the ChEBI roles clean-up. I'm adding it to that project so we can double check.

**Comment by lreiser** [comment]
awesome

**Comment by krchristie** [comment]
Yes, the ChEBI roles cleanup will cover this issue. I think that there are previous reports of this issue from other species as well, so it's definitely one of the major problems to fix.

**Comment by balhoff** [comment]
After merging the roles change, these all seem to work with plants now.
