### ISSUE TITLE
Obsolete  GO:0044133 growth of symbiont on or near host ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19503]
No annotations. 

@mgiglio99 @ValWood Are there uses for this term ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I  think we already mentioned that this should go. It's growth (usually viability)  + location

**Comment by ValWood** [comment]
I think it was supposed to be done anyway, pending annotation removal
see
https://github.com/geneontology/go-ontology/issues/18786

**Comment by pgaudet** [comment]
This one has no annotations.

**Comment by pgaudet** [comment]
I obsoleted GO:0044133

**Comment by pgaudet** [comment]
We still have many of those terms: 


GOID | Term label
-- | --
GO:0044150 | 'development of host on or near symbiont surface'
GO:0044134 | 'development of symbiont on or near host phyllosphere'
GO:0044136 | 'development of symbiont on or near host rhizosphere'
GO:0044132 | 'development of symbiont on or near host'
GO:0075226 | 'encysted zoospore germination on or near host'
GO:0075009 | 'germ tube formation on or near host'
GO:0075192 | 'haustorium mother cell formation on or near host'
GO:0075187 | 'hyphopodium formation on or near host'
GO:0075183 | 'infection cushion formation on or near host'
GO:0044138 | 'modulation of development of symbiont on or near host'
GO:0075227 | 'modulation of encysted zoospore germination on or near host'
GO:0075010 | 'modulation of germ tube formation on or near host'
GO:0075223 | 'modulation of sporangium germination on or near host'
GO:0075006 | 'modulation of spore germination on or near host'
GO:0044141 | 'negative regulation of development of symbiont on or near host   surface'
GO:0075229 | 'negative regulation of encysted zoospore germination on or near   host'
GO:0075012 | 'negative regulation of germ tube formation on or near host'
GO:0075195 | 'negative regulation of haustorium mother cell formation on or near   host'
GO:0075190 | 'negative regulation of hyphopodium formation on or near host'
GO:0075186 | 'negative regulation of infection cushion formation on or near host'
GO:0075225 | 'negative regulation of sporangium germination on or near host'
GO:0075008 | 'negative regulation of spore germination on or near host'
GO:0075034 | 'nuclear division involved in appressorium formation on or near   host'
GO:0044143 | 'positive regulation of development of symbiont on or near host   surface'
GO:0075228 | 'positive regulation of encysted zoospore germination on or near   host'
GO:0075011 | 'positive regulation of germ tube formation on or near host'
GO:0075194 | 'positive regulation of haustorium mother cell formation on or near   host'
GO:0075189 | 'positive regulation of hyphopodium formation on or near host'
GO:0075185 | 'positive regulation of infection cushion formation on or near host'
GO:0075224 | 'positive regulation of sporangium germination on or near host'
GO:0075007 | 'positive regulation of spore germination on or near host'
GO:0075193 | 'regulation of haustorium mother cell formation on or near host'
GO:0075188 | 'regulation of hyphopodium formation on or near host'
GO:0075184 | 'regulation of infection cushion formation on or near host'
GO:0075033 | 'septum formation involved in appressorium formation on or near   host'
GO:0075222 | 'sporangium germination on or near host'
GO:0075005 | 'spore germination on or near host'


@mgiglio99 @dsiegele

**Comment by pgaudet** [comment]
From multi org call - obsolete 'on or near' terms.

**Comment by pgaudet** [comment]
Children of ``with annotations (QuickGO): 


GO:0009878                nodule morphogenesis | 92.49 | 1,047
GO:0044111                development involved in symbiotic interaction | 4.42 | 50
GO:0044114                development of symbiont in host | 2.12 | 24
GO:0085016                dormancy exit of symbiont in host | 0.35 | 4
GO:0052096                formation by symbiont of syncytium involving giant cell for nutrient acquisition from host | 0.18 | 2
GO:0075015                formation of host infection structure | 0.18 | 2
GO:0085014                dormancy entry of symbiont in host | 0.18 | 2
GO:0075039                establishment of turgor in appressorium | 0.09 | 1

Those terms can be obsoleted - or label changed if the term without 'on or near' did not exist. 

'development   of host on or near symbiont surface'
'development   of symbiont on or near host phyllosphere'
'development   of symbiont on or near host rhizosphere'
'development   of symbiont on or near host'
'encysted   zoospore germination on or near host'
'germ   tube formation on or near host'
'haustorium   mother cell formation on or near host'
'hyphopodium   formation on or near host'
'infection   cushion formation on or near host'
'septum   formation involved in appressorium formation on or near host'
'sporangium   germination on or near host'
'spore germination on or near host'

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

GO:0044132 | development of symbiont on or near host
GO:0044134 | development of symbiont on or near host phyllosphere
GO:0044136 | development of symbiont on or near host rhizosphere 
GO:0044138 | modulation of development of symbiont on or near host 
GO:0044141 | negative regulation of development of symbiont on or near host surface 
GO:0044143 | positive regulation of development of symbiont on or near host surface
GO:0044150 | development of host on or near symbiont surface

The reason for obsoletion is that those terms represent both a process and a component. There are no annotations or mappings to those terms. Those terms are not present in any subsets. 

Comments can be added to the ticket: : https://github.com/geneontology/go-ontology/issues/19503


We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on August 27th, 2020. Unless objections are received by August 27th, 2020. we will assume that you agree to this change.

Thanks, Pascale
