### ISSUE TITLE
Additional parents for "omega peptidase" children.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19502]
The following 4 GO terms are the current children (but also see #19473) of "omega peptidase activity (GO:0008242)", but lack any additional parent to specify the catalytic type (cysteine-type etc).

I looked up fly and human proteins annotated with these 4 terms (examples below), and then cross-referenced them in the MEROPS database. Based on the MEROPS families to which they belong, I think we can add additional catalytic type parents as follows:

==

beta-aspartyl-peptidase activity (GO:0008798)
- fly CG7860 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=T02.UPW)
- human ASRGL1 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=T02.UPW)
- T2 family: https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=T2

=> ADD PARENT threonine-type peptidase activity (GO:0070003)

==

gamma-glutamyl-peptidase activity (GO:0034722)
- fly l(3)72Dp/CG32155 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=C26.A22)
- human GGH (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=C26.001)
- C26 family: https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=C26

=> ADD PARENT: cysteine-type peptidase activity (GO:0008234)

==

glutathione hydrolase activity (GO:0036374)
- fly Ggt-1 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=T03.A04)
- human GGT1 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=T03.006)
- T3 family: https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=T3

=> ADD PARENT threonine-type peptidase activity (GO:0070003)

==

pyroglutamyl-peptidase activity (GO:0016920)
- fly CG32147 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=C15.A03)
- human PGPEP1 (https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=C15.010)
- C15 family: https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=C15

=> ADD PARENT: cysteine-type peptidase activity (GO:0008234)

==

**Comment by hdrabkin** [comment]
done.

**Comment by sjm41** [comment]
Thanks Harold!
