### ISSUE TITLE
vascular associated smooth muscle cell versus vascular smooth muscle cell

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#19505]
Based on terms like "vascular associated smooth muscle cell migration" (GO:1904738)
"vascular smooth muscle cell proliferation" (GO:1990874), what is the difference between "vascular associated smooth muscle cell" and "vascular smooth muscle cell" in GO?

**Comment by ukemi** [comment]
"vascular smooth muscle cell proliferation" and "vascular associated smooth muscle cell migration" both refer to the same cell type in the cell ontology, defined as: A smooth muscle cell assocatiated with the vasculature. This term in the CL has an exact synonym 'vascular smooth muscle cell'. 
I could standardize all the term names, but essentially the terms point to the same ell type. Let me know if it would help to standardize the names and add the corresponding synonyms.

**Comment by slaulederkind** [comment]
It would definitely help to standardize the names and add the corresponding synonyms.  Thanks, David.

**Comment by ukemi** [comment]
Will do. Nice to hear from you Stan!
