### ISSUE TITLE
MP iron sulfur cluster export from the mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19504]
Can we add

"iron sulfur cluster export from the mitochondrion"

The directed movement of iron sulfur clusters from inside the mitochondrion  into the cytosol by crossing the inner mitochondrial membrane.

as a descendant of
GO:1902497    iron-sulfur cluster transport
and 
mitochondrial transmembrane transport (GO:1990542)

PMID: 31040179

(I think it is OK to label such things as export for crossing the mitochondrial membrane because the outer membrane is  permeable ?)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140466
+name: iron-sulfur cluster export from the mitochondrion
+namespace: biological_process
+def: "The directed movement of iron sulfur clusters from inside the mitochondrion into the cytosol by crossing the inner mitochondrial membrane." [PMID:31040179]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005739 ! mitochondrion
+intersection_of: transports_or_maintains_localization_of CHEBI:30408 ! iron-sulfur cluster
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19504 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-22T10:01:36Z
+

**Comment by ValWood** [comment]
This doesn't have 

GO:1990542 | mitochondrial transmembrane transport
parent?

**Comment by ValWood** [comment]
It does now
