### ISSUE TITLE
flavin-dependent halogenase that chlorinates DIF-1

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#19524]
When looking for halohenase activity I found this term
alkylhalidase activity GO:0047651

However, with the def this does not fit what we need PMID:20231486
In the process of Dicty making DIF-1 (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:90397, formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) is followed in order by dichlorination of the aromatic ring and O-methylation. The colorization step was the only one sill missing at the time of the paper and they identified chlA (DDB_G0290825 / Q54FI4) to be the halogenase that chlorinates THPH.

So I wonder, if I need a new term? Or does GO:0047651 need revision?
chloride halogenase activity
or just
chlorination activity

Right now this is only annotated to 'catalytic activity' top term and not adequate.

Thanks for any input!

**Comment by hdrabkin** [comment]
Hi @pfey03 
I note that RHEA does use that CHEBI id in one reaction
https://www.rhea-db.org/reaction?id=48396
You seem to mention multiple reactions
formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) is followed in order by dichlorination of the aromatic ring and O-methylation. 

I don't think the current term follows what you are trying to annotate (there is no brominated intermediates.

I would make two reactions, one for each of these two shown in the figure
![Screen Shot 2020-05-27 at 1 57 16 PM](https://user-images.githubusercontent.com/10440080/83055658-20551300-a022-11ea-815d-53fbebdaba4c.jpg)
![Screen Shot 2020-05-27 at 1 57 10 PM](https://user-images.githubusercontent.com/10440080/83055665-21864000-a022-11ea-97c6-abbb291f40d9.jpg)
Hopefully, there is enough info to get some RHEA ids

Do you need a term for the first step outlined in Figure 6 also?

**Comment by hdrabkin** [comment]
my notes
Substrate 1 is 
2,4,6-trihydroxyphenylhexan-1-one, which has been assigned the ChEBI identifier CHEBI:150865  requested.

product 1 is CHEBI:90396 (dichloro, 2,4,6 hydroxy
product 2 is CHEBI:90397, (dichloro ,2,6 hydroxy
Once get CHEBI for #1, then can create RHEA requests for the two reactions and also create the GO terms.

**Comment by hdrabkin** [comment]
Based on the synoymn for CHEBI:90396, I'll name the reaction 'dichloro-THPH synthase because I hate using the long chemical names for the term name. THe def will get the reaction.
For the synthesis of 90397, maybe DIF-1 synthase?
Neither use ATP, thus synthase, not synthetase.

**Comment by hdrabkin** [comment]
reaction 1
2,4,6-trihydroxyphenylhexan-1-one + O2 + FADH + Cl- = (3,5-dichloro-2,4,6-trihydroxyphenyl)hexan-1-one + FAD + H20 (?). Checking with RHEA

Reaction 2
(3,5-dichloro-2,4,6-trihydroxyphenyl)hexan-1-one + S-Ado-Met = 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one(1−) + S-Ado-homocys

Once I have the RHEA approval for the products of reaction 1, I'll create these two tems in GO.

**Comment by hdrabkin** [comment]
RHEA ids obtained; Cannot put the Rheas in until public but can create the GO terms.
Here are the reactions you requested and a little bit more so we now have all the 4 reactions necessary for the biosynthesis of DIF-1. I created two reactions for the chlorination as this takes place in two steps, and I also created the reaction for the synthesis of 2,4,6-trihydroxyphenylhexan-1-one (CHEBI:150865) that is described in pmid:16906151. The methylation is already in Rhea.

All the reactions in the pathway are:
1. RHEA:64352 3 H+ + hexanoyl-CoA + 3 malonyl-CoA =
2,4,6-trihydroxyphenylhexan-1-one + 3 CO2 + 4 CoA

2. RHEA:64356 2,4,6-trihydroxyphenylhexan-1-one + chloride + FADH2 + O2 =
(3-chloro-2,4,6-trihydroxyphenyl)hexan-1-one + FAD + H+ + 2 H2O

3. RHEA:64360 (3-chloro-2,4,6-trihydroxyphenyl)hexan-1-one + chloride + FADH2 + O2
= (3,5-dichloro-2,4,6-trihydroxyphenyl)hexan-1-one + FAD + 2 H2O

4. RHEA:48396 (3,5-dichloro-2,4,6-trihydroxyphenyl)hexan-1-one +
S-adenosyl-L-methionine =
1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one + H+ +
S-adenosyl-L-homocysteine

Reaction 4 is in public.

**Comment by hdrabkin** [comment]
For #1, to keep the name sane, I can call  i
THPH synthase (synonym of the CHEBI name

For #2 (3-chloro-2,4,6-trihydroxyphenyl)hexan-1-one synthase (no listed synonym)
  Maybe 3-chloro THPH synthase

For #3  dichloro-THPH, synthase

For #4  DIF-1 synthase

**Comment by hdrabkin** [comment]
need some parents (not just catalytic activity.
#4 can be an o-methylase activity
There is actually a DIF dechlorinase activity, a child of carbon-halide lyase activity (carbon-halide bond breakage). 

for #2 and #3, 
based on PMID:28106994 Enzymatic Halogenation and Dehalogenation Reactions: Pervasive and Mechanistically Diverse 
EC:1.14.19 (Oxidoreductases Acting on paired donors, with incorporation or reduction of molecular oxygen ); reactions adding chlorine to tryptophan are classified under this.

For Rxn 1
The Biosynthesis of Differentiation-Inducing Factor, a Chlorinated Signal Molecule Regulating DictyosteliumDevelopment, PMID:9446571, suggests that this reaction is catalyzed by a polyketide syntase. 
https://en.wikipedia.org/wiki/Polyketide_synthase#Classification
Polyketide synthases (PKSs) are a family of multi-domain enzymes or enzyme complexes that produce polyketides, a large class of secondary metabolites,

We have complex terms for such enzymes;  GO:0034081, and two children for type II and gype III complexes (I have no idea where is type 1); 
Right now for rxn 1 I think my best bet for a parent is going to be 'catalytic activity

**Comment by hdrabkin** [comment]
RXN 1
:+id: GO:0106265
+name: THPH synthase activity
RXN 2
+id: GO:0106266
+name: 3-chloro THPH synthase activity
RXN 3
+[Term]
+id: GO:0106267
+name: 3,5 dichloro-THPH synthase activity
RXN 4
+id: GO:0106268
+name: 3,5-dichloro-THPH methyl transferase activity

**Comment by hdrabkin** [comment]
reopened until the rhea ids become public

**Comment by pfey03** [comment]
@hdrabkin sorry I never responded as I was so caught up by other things. 
Thanks so much for adding these terms, when available I will return to paper and annotate the chlorination step they showed. Do the terms get released once Rhea provides IDs?

**Comment by pfey03** [comment]
Thanks so much @hdrabkin grant stuff interfering, but I'll annotate when I get a chance!

**Comment by hdrabkin** [comment]
RHEA ids still not in public

**Comment by hdrabkin** [comment]
RHEA:64356 for GO:0106266
RHEA:64352 for GO:0106265
RHEA:48396 for GO:0106268
RHEA:64360 for GO:0106267
