### ISSUE TITLE
NTR: piRNA transcription

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19530]
Could I request:

 'piRNA transcription' or 'piRNA transcription by RNA polymerase II' - depending on what your thoughts are on this @pgaudet @RLovering)
 
Def: The cellular synthesis of Piwi-interacting RNA piRNAs, Piwi-associated RNAs, a class of 24- to 30-nucleotide RNA derived from repeat or complex DNA sequence elements and processed by a Dicer-independent mechanism. (PMID:28847004).

(child of GO:0034587 | piRNA metabolic process)

Plus the regulation terms?

**Comment by pgaudet** [comment]
I assume you only need 'positively regulation of piRNA transcription' from this paper ? I created the 'regulation' parent; will add the negative regulation if there is a reference that describes it. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140541
+name: piRNA transcription
+namespace: biological_process
+def: "The cellular synthesis of Piwi-interacting RNA piRNAs, a class of 24- to 30-nucleotide RNA derived from repeat or complex DNA sequence elements and processed by a Dicer-independent mechanism." [PMID:28847004]
+synonym: "Piwi-associated RNA transcription" EXACT []
+synonym: "PIWI-interacting RNA transcription" EXACT []
+is_a: GO:0006351 ! transcription, DNA-templated
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19530 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-09T16:53:25Z
+
+[Term]
+id: GO:0140542
+name: regulation of piRNA transcription
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of the synthesis of a piRNA." [PMID:28847004]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0140541 ! piRNA transcription
+created_by: pg
+creation_date: 2020-11-09T19:08:15Z
+
+[Term]
+id: GO:0140543
+name: positive regulation of piRNA transcription
+namespace: biological_process
+def: "Any process that increases the frequency, rate or extent of the synthesis of piRNA." [PMID:28847004]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0140541 ! piRNA transcription
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19530 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-09T19:26:02Z
+

**Comment by RLovering** [comment]
great we just need the regulation of mRNA transcription ;)

**Comment by hattrill** [comment]
Thanks, @pgaudet
