### ISSUE TITLE
Request to remove taxon constraint on stem cell terms 

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#19543]
When clearing up some GO RULE 13 violations for Arabidopsis annotations we encountered 
several violations that were due to descent from GO:0017145 which is constrained to Metazoans and GO:0048863 also constrained to Metazoans.

Plants have what many consider to be stem cells, self renewing populations of cells (in meristems that produce shoot and root tissues) as well as asymmetric cell divisions that produce a differentiated daughter etc...

So to clarify- can we removed the only in Metazoa constraint on:
stem cell division GO:0017145
stem cell fate determination GO:0048863

**Comment by ukemi** [comment]
I'm doing it for all three generic stem cell terms.

**Comment by lreiser** [comment]
thanks
@tberardini tagging to loop you in.

**Comment by ukemi** [comment]
Should be done.
