### ISSUE TITLE
positive regulation child of GO:0048016 inositol phosphate-mediated signaling

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#19557]
Hi 
Please could you created the positive regulation child of GO:0048016 inositol phosphate-mediated signaling.
I would like to associate this term with PDGFB based on this paper PMID:19126672

Based on Fig 1 where addition of PDGF (P) stimulation led to PI3K signaling  demonstrated by the effect of inhibiting the signaling with 5 μM wortmannin (W) AND Fig 2 PDGF stimulated AKT phosphorylation which indicated this signaling pathway. Fig 5 also supports this, using a more specific inhibitor expt fibroblasts

Thanks

Ruth

**Comment by ukemi** [comment]
We'd like to have a look at this biology with respect to how we would model it in GO-CAM.

**Comment by RLovering** [comment]
Hi David

Thanks for looking at this. I have just realised I also requested this term in another ticket (#19455). Sorry about this, I have closed ticket 19455 as having 2 tickets is obviously not helpful. The term is being requested for an MSc student who is annotating PI3K subunits.

In the other ticket I requested
GO:0048016 inositol phosphate-mediated signaling
NTR: positively regulates child: positively regulates inositol phosphate-mediated signaling
PMID: 19126672
For the annotation of Fibronectin which is a ligand for integrin and leads to signaling within the fibroblasts when they adhere to this substrate.

Note that I should have included the is_a parent 
 GO:1902533 positive regulation of intracellular signal transduction

Many thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering 
Do you want to try modeling this, so we can decide on the creation of the term ?

**Comment by RLovering** [comment]
Hi I just looked at this again and realised that I should have used the  GO:0014068 positive regulation of phosphatidylinositol 3-kinase signaling term.

I was annotating this paper while talking to an expert and a student and obviously got distracted as the paper is not straightforward.

I will close this ticket
Ruth
