### ISSUE TITLE
recombinase activator activity

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#19555]
We've had a term request from a community curator:

id: GO:new
name: recombinase activator activity
namespace: molecular_function
def: "Binds to and increases the activity of a recombinase." [GOC:mah,PMID:32414915]
is_a: GO:0008047 ! enzyme activator activity
relationship: positively_regulates GO:0000150 ! recombinase activity

I don't have an immediate need for the generic "recombinase regulator activity" term, or for "recombinase inhibitor activity", but I also don't object to including them. Same goes for "regulation of recombinase activity" BP terms.

**Comment by krchristie** [comment]
@pgaudet - This ticket never got assigned. Since it's related to the one you just assigned me, I've taken this one as well.

**Comment by krchristie** [comment]
> I don't have an immediate need for the generic "recombinase regulator activity" term, or for "recombinase inhibitor activity", but I also don't object to including them. Same goes for "regulation of recombinase activity" BP terms.

I only put in the requested term, not any of the other possibilities in the absence of current need for annotation.

**Comment by pgaudet** [comment]
> @pgaudet - This ticket never got assigned. Since it's related to the one you just assigned me, I've taken this one as well.


Thanks @krchristie

**Comment by mah11** [comment]
> I only put in the requested term ...

That's fine; thanks
