### ISSUE TITLE
GO:0008121 | ubiquinol-cytochrome-c reductase activity  vs. GO:0045153

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19569]
I don't understand the difference between these 2 terms, is there one?

GO:0008121 | ubiquinol-cytochrome-c reductase activity |  
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: CoQH2 + 2 ferricytochrome c = CoQ + 2 ferrocytochrome c + 2 H+.

GO:0045153 | electron transporter, transferring electrons within CoQH2-cytochrome c reductase complex activity
Enables the directed movement of electrons within the CoQH2-cytochrome c reductase complex.

(the def of the fist one looks odd, but they both appear to be used for
cytochrome c1)

**Comment by hdrabkin** [comment]
GO:0045153 sounds to be a grouping term. GO:0008121 seems more specific, just looking at the def.  However, the 8121 reaction does not mention ubiquinol

**Comment by ValWood** [comment]
> However, the 8121 reaction does not mention ubiquinol

But the term name does, so presumably, it should?

**Comment by ValWood** [comment]
Isn't CoQH2 ubiquinol?

**Comment by hdrabkin** [comment]
I would think if it's important. I'll need to see what the xrefs are if they have them (I don't have protege open at the moment).

**Comment by hdrabkin** [comment]
Yes, you're right
Reduced CoQ10, unoxidized CoQ10, CoQ10H2, or dihydroquinone

**Comment by ValWood** [comment]
Hi Harold, so should this be a merge then?

**Comment by ValWood** [comment]
HI Harold,
Any news on this, should  the 2 terms be mreged?
v

**Comment by hdrabkin** [comment]
@amorgat , do  you think these refer to the same thing?

**Comment by ValWood** [comment]
pinging @amorgat
v

**Comment by sjm41** [comment]
@ValWood  - looks like this merge has already happened: 
https://www.ebi.ac.uk/QuickGO/term/GO:0008121
https://github.com/geneontology/go-ontology/issues/20616

**Comment by ValWood** [comment]
So it does! thanks @sjm41
