### ISSUE TITLE
Should PRO (Protein ontology) IDs be allowed as xref or dbxref ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19560]
Hello, 

GO:0032620 interleukin-17 production 
has defxref PR:000001092

This should rather be an annotation, correct ? I think any PR: in the dbxref or xrefs should be removed. Right @cmungall @hdrabkin 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Its a PRO id for a family (non-species specific.
https://proconsortium.org/app/entry/PR%3A000001092/
https://proconsortium.org/cgi-bin/browser_pro?ids=PR:000001092 (dag view).
It's not the sort of thing I would expect in the def. 
I guess the curator was thinking it would be to define what an interleukin-17 was.

**Comment by hdrabkin** [comment]
I've seen this before where a term had a wikipedia pointer to 'proton'.

**Comment by hdrabkin** [comment]
AND I see the def has a wiki link to 'interleukin 17'; maybe replace with
How about
Interleukin-17 and its receptor.
Spriggs MK. J Clin Immunol. 1997 Sep;17(5):366-9. doi: 10.1023/a:1027360106635. 
PMID:9327335 Review.
and/or

Interleukin 17 is a chief orchestrator of immunity.
Veldhoen M. Nat Immunol. 2017 May 18;18(6):612-621. doi: 10.1038/ni.3742. PMID 28518156 Review.

**Comment by pgaudet** [comment]
OK  - so this is similar to the ChEBI xrefs we saw before. I'll remove them. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also removed http://www.mercksource.com/

**Comment by cmungall** [comment]
Yes, by all means logically define protein binding terms using PRO (leaving
aside the question of whether they should exist for now; if they do exist
then they should have owl definitions).
