### ISSUE TITLE
ruffle (GO:0001726) please add taxon restriction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19576]
ruffle (GO:0001726)

Definition | Parents
-- | --
Projection at the leading edge of a crawling cell; the protrusions are supported by a microfilament meshwork.

add never in yeast

**Comment by pgaudet** [comment]
yeast = Ascomycota ?

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-ontology/pull/19606

**Comment by mah11** [comment]
> yeast = Ascomycota ?

Not exactly; there are Basidiomycete fungi that have yeast forms (I'm showing off that I learned this last week ;) ). But "never in Ascomycota" would not be wrong for the requested restriction.
