### ISSUE TITLE
actomyosin, actin portion (GO:0042643)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19570]
Definition 
The actin part of any complex of actin, myosin, and accessory proteins.

I don't understand this term?
Isn't this just  err, actin?

I'm picking up mappings to it which I will block. I haven't raised a PAINT ticket yet as I think the term should go? So let me know if I have missed the meaning

**Comment by ValWood** [comment]
3 EXP,

**Comment by pgaudet** [comment]
Dear all, 
The proposal has been made to obsolete GO:0042643 actomyosin, actin portion. This corresponds to actin, a gene product. 

There are 3 EXP annotations: 
1 UniProt
2 WormBase @vanaukenk 

https://docs.google.com/spreadsheets/d/19F2pmvbDY3XizQtEH2TZm79wN375f5fDcz72sCDdZXU/edit#gid=0

There are no mappings, this term is not present in any subsets. 

You can comment in the ticket:
https://github.com/geneontology/go-ontology/issues/19570

We are opening a comment period for this proposed obsoletion. We’d like to proceed with the obsoletion this term on July  1st, 2020. Unless objections are received by July  1st, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by vanaukenk** [comment]
WB annotations removed.
