### ISSUE TITLE
NEDD8-specific protease activity (GO:0019784)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19573]
Currently this term is only under 'cysteine-type peptidase activity':
 peptidase activity
 |__peptidase activity, acting on L-amino acid peptides
    |__cysteine-type peptidase activity
        |__ubiquitin-like protein-specific protease activity
            |__NEDD8-specific protease activity 

But there's at least one NEDD8 protease that is a metallopeptidase (and not a cysteine-type): human COPS5 (Q92905) (and its orthologs).

So I think we need to have separate 'NEDD8-specific cysteine-type protease activity' and 'NEDD8-specific metallopeptidase activity' terms with appropriate parentage.
Current annotations will then have to be revised as necessary.

Related to #17398.

**Comment by deustp01** [comment]
> So I think we need to have separate 'NEDD8-specific cysteine-type protease activity' and 'NEDD8-specific metallopeptidase activity' terms

This sounds wrong. The GO protease terms are intended to classify activities according to mechanism (serine protease, metalloprotease, etc.) and orthogonally according to where the cleavage site falls in the substrate (endopeptidase, aminopeptidase, carboxypeptidase), while remaining agnostic about the identity of the substrate. This classification scheme in fact displaced a number of activity terms that matched the pattern proposed here.

**Comment by sjm41** [comment]
OK, good to know.  But in that case how should we accurately annotate a metallopeptidase that hydrolyses NEDD8, as is the case for COPS5?
By using the current term "NEDD8-specific protease activity", we're asserting that COPS5 is a cysteine-type peptidase (via the current parentage), when it's not.

I guess one option is to keep the single term, but to move it out of the hierarchy leading up to 'cysteine-type peptidase activity'?

(This issue is similar to the problem with annotating JAMM-domain deubiquitinases (which are also metallopeptidases) described in #17398 - several of those proteins are currently annotated to "thiol-dependent ubiquitin-specific protease activity  (GO:0004843), which also incorrectly asserts them as cysteine-type peptidases..... but at least in that case there's the option of co-annotating with "ubiquitinyl hydrolase activity" and "metallopeptidase activity".)

**Comment by pgaudet** [comment]
Hi @deustp01 

WRT to substrates - I completely agree with you that we normally dont capture that in the ontology, however in the ubiquitin ligase branch we have a long list: 

'Atg12 ligase activity'
'FAT10 ligase activity'
'ISG15 ligase activity'
'NEDD8 ligase activity'
'Pup ligase activity'
'SUMO ligase activity'
'ubiquitin protein ligase activity'
'UFM1 ligase activity'
'URM1 ligase activity'

so @sjm41 was only proposing to keep that structure. 

Should we merge the individual substrates ? I think this is work that @ukemi and @marcfeuermann did. 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't think it is incorrect to have these terms. These are different conjugated molecules (not the substrates)

I would find it very difficult to describe these without these specific terms. Ubiquitins are not the substrates here, the protein that the conjugated molecule (ubiquitin SUMO UFM1) or whatever is attached to are the substrates. I think these are a special case and we should keep them.
Otherwise everything would become  "ubiquitin like - ligase" for. a SUMO ligase. Or even a ubiquitin ligase.

Also @ukemi  spend a long time sorting all of these out...

**Comment by ValWood** [comment]
Please don't merge they are very useful.

If these were merges it would create an annotation headache because we would need to devise a way to capture the "ubiquitin type molecule" and the actual substrate molecule and be able to differentiate them clearly.

**Comment by pgaudet** [comment]
Thanks @ValWood 
In this case we (@sjm41 ) propose to create the individual terms to capture the type of protease: for example there is a thioldependent NEDD8-hydrolase, and a metallo-dependent NEDD8-hydrolase. Right now there is a single term 'NEDD8-specific protease activity', under ''cysteine-type peptidase activity', but this is not right for all the proteins annotated to 'NEDD8-specific protease activity', as some are metallo-dependent, for example csn5, see even https://www.pombase.org/gene/SPAC1687.13c 

So, we need to sort that out.
