### ISSUE TITLE
mitotic spindle assembly checkpoint Add synonym

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19578]
GO:0007094    mitotic spindle assembly checkpoint Add synonym mitotic checkpoint

I think it will need to be "related" because we have a bunch of checkpoints under the grouping term
"mitotic cell cycle checkpoint" which sounds similar.

If this doesn't matter, it could be exact.

But, in the literature  the mitotic spindle checkpoint/mitotic checkpoint notation is used interchangably

**Comment by pgaudet** [comment]
Isn't it BROAD ? 
mitotic checkpoint could be any checkpoint, for eg 

'mitotic spindle checkpoint' <http://purl.obolibrary.org/obo/GO_0071174>
'mitotic DNA damage checkpoint' <http://purl.obolibrary.org/obo/GO_0044773>
'mitotic cell cycle checkpoint' <http://purl.obolibrary.org/obo/GO_0007093>
'mitotic cytokinesis checkpoint' <http://purl.obolibrary.org/obo/GO_0044878>
'mitotic DNA replication checkpoint' <http://purl.obolibrary.org/obo/GO_0033314>

Can't it ?

**Comment by ValWood** [comment]
no, people don't call the other checkpoints  'mitotic checkpoints'
They happen during the mitotic cell cycle but not in mitotis.

The original, common name of the spindle checkpoint is the "mitotic checkpoint",
none of the others are called this.
It could even be exact.

The others are "mitotic cell cycle checkpoints"
this is 
"the mitotic checkpoint"

**Comment by ValWood** [comment]
I wanted to add it for searching as it is quite common usage. If anyone types "mitotic checkpoint" the SAC is what they would be expecting to find.

The "mitotic stuff" around the other checkpoints is GO decoration to disambiguate from the related checkpoints in the meiotic cell cycle.

**Comment by pgaudet** [comment]
OK, changed to EXACT.
