### ISSUE TITLE
add parent to  GO:0097350 neutrophil clearance

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#19585]
Please add is_a parent  GO:0043277 apoptotic cell clearance
to GO:0097350 neutrophil clearance

as discussed with Alex @addiehl 

Thanks

Ruth

**Comment by pgaudet** [comment]
Done - added the requested parent.

**Comment by pgaudet** [comment]
Is it OK that 'neutrophil clearance' is a child of 'tissue remodeling'? I thought the immune system was not considered a tissue ? 

@addiehl @RLovering

**Comment by RLovering** [comment]
I agree this seems very odd
