### ISSUE TITLE
NTR: actin related terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19586]
PMID:12796476

GO:NEW | negative regulation of actin filament barbed end depolymerization
standard def

GO:NEW  | negative regulation of actin filament pointed-end polymerization

standard def

I also want to describe an
"actin binding inhibitor", I got "molecular function regulator" so far.

We discussed this a lot. Any decision how to. represent binding inhibitor activities?
(note sequestering seems OK for actin monomers, but  actin sequestering doesn't seem right for something that binds to a filament and inhibits further actin binding.

**Comment by pgaudet** [comment]
@ValWood 

Would 'actin filament binding inhibitor' work ?

**Comment by ValWood** [comment]
Yes if that is something that could be added !

**Comment by pgaudet** [comment]
So, I would create 'actin filament binding inhibitor' instead of the 2 terms you suggest ? 

Can you also provide papers ?

**Comment by ValWood** [comment]
PMID:12796476 is the one in the ticket so I think this would be OK.

**Comment by ValWood** [comment]
Closing. I don't need this right now.
