### ISSUE TITLE
NTR: Terms to represent mannogen metabolism

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#19582]
Hi,

Can I request the following terms please?

1. Accession: GO:xxxxxx
Name: mannogen metabolic process
Ontology: biological_process
Synonyms: mannogen metabolism, beta-1,2-mannan metabolic process
Definition: The chemical reactions and pathways involving mannogen, a mannose-containing polysaccharide that is a major energy reserve in Leishmania.
is_a: GO:0044264 ! cellular polysaccharide metabolic process
Source: CHEBI:149779, PMID:16766650, PMID:12902334, PMID:31662278, PMID:31513773

2. Accession: GO:xxxxxx
Name: mannogen biosynthetic process
Ontology: biological_process
Synonyms: mannogen anabolism, mannogen biosynthesis, mannogen formation, mannogen synthesis, beta-1,2-mannan biosynthetic process
Definition: The chemical reactions and pathways resulting in the formation of mannogen, a mannose-containing polysaccharide that is a major energy reserve in Leishmania.
is_a: GO:0033692 ! cellular polysaccharide biosynthetic process
is_a: GO:xxxxxx ! mannogen metabolic process
Source: CHEBI:149779, PMID:16766650, PMID:31662278, PMID:31513773

3. Accession: GO:xxxxxx
Name: mannogen catabolic process
Ontology: biological_process
Synonyms: mannogen breakdown, mannogen catabolism, mannogen degradation, beta-1,2-mannan catabolic process, beta-1,2-mannan catabolism
Definition: The chemical reactions and pathways resulting in the breakdown of mannogen, a mannose-containing polysaccharide that is a major energy reserve in Leishmania.
is_a: GO:0044247 ! cellular polysaccharide catabolic process
is_a: GO:xxxxxx ! mannogen metabolic process
Source: CHEBI:149779, PMID:12902334, PMID:31662278, PMID:31513773

Thank you very much for your help.

Best wishes,
Achchuthan

**Comment by pgaudet** [comment]
Hi @hdrabkin 

I have added the CHEBI term in the CHEBI import file

**Comment by Achchuthan** [comment]
Hi,
Can I ask whether there is any progress with this new term request? 

Thanks,
Achchuthan

**Comment by hdrabkin** [comment]
Sorry this fell through the cracks while waiting for sucessful addition of CHEBI id
+id: GO:0106303
+name: mannogen metabolic process
+id: GO:0106304
+name: mannogen biosynthetic process
+[Term]
+id: GO:0106305
+name: mannogen catabolic process

However, I do have a question.
Do these terms need a taxon contraint (only in Leishmania.?).

**Comment by Achchuthan** [comment]
Thanks a lot @hdrabkin. Taxon constrain to NCBI:txid5658 would be good.

Thanks,
Ach

**Comment by hdrabkin** [comment]
constraint added.
