### ISSUE TITLE
 GO:0003774 motor activity - update definition/position in hierarchy

### ISSUE THREAD

**Issue by sandraorchard** [geneontology/go-ontology#19590]
This term is a child of nucleoside-triphosphatase activity and does clearly state that the motor activity "should be coupled to the hydrolysis of a nucleoside triphosphate" but it has been used for a lot of bacterial flagellar proteins which rely on a PMF not ATP hydrolysis. Rather than create a need for a lot of reannotation, can this terms definition/parentage be made a bit more flexible.

**Comment by sandraorchard** [comment]
Just discovered GO:0120100 bacterial-type flagellum motor so the term I needed does exist, just not linked to 'motor' - I still think we need some relationship between the two as 'motor' is being incorrectly used.

**Comment by pgaudet** [comment]
Hi @sandraorchard 


Are you proposing we create a term for 'PMF-dependent motor activity'? 

I see only 12 *manual* bacterial annotations for 'motor activity': 
GENE PRODUCT DB	GENE PRODUCT ID	SYMBOL	QUALIFIER	GO TERM	GO NAME	ECO ID	GO EVIDENCE CODE	REFERENCE	WITH/FROM	TAXON ID	ASSIGNED BY	ANNOTATION EXTENSION	GO ASPECT
UniProtKB	A0A0F7RE82	GBAA_1710	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12721629	UniProtKB:Q03593	1392	TIGR		F
UniProtKB	A0A0F7RGG7	GBAA_1662	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12721629	UniProtKB:P24073	1392	TIGR		F
UniProtKB	A0A0F7RGH3	GBAA_1658	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12721629	UniProtKB:P28611	1392	TIGR		F
UniProtKB	A0A1J9VJN0	GBAA_4748	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12721629	UniProtKB:P28611	1392	TIGR		F
UniProtKB	Q5LWZ1	fliN	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:15602564	UniProtKB:Q03593	246200	TIGR		F
UniProtKB	Q74EE9	GSU1013	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:14671304	NCBI_gi:2853603	243231	TIGR		F
UniProtKB	Q74G27	fliN	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:14671304	NCBI_gi:5921671	243231	TIGR		F
UniProtKB	Q8E9J0	motA	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12368813	UniProtKB:P28611	211586	TIGR		F
UniProtKB	Q8EAG6	motX	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12368813	UniProtKB:P40608	211586	TIGR		F
UniProtKB	Q8EGR6	pomA	enables	GO:0003774	motor activity	ECO:0000250	ISS	PMID:12368813	UniProtKB:O06873	211586	TIGR		F
ComplexPortal	CPX-1082	chey-flim-cw_ecoli	enables	GO:0003774	motor activity	ECO:0005547		PMID:17050923		83333	ComplexPortal		F
ComplexPortal	CPX-1085	chey-flim-ccw_ecoli	enables	GO:0003774	motor activity	ECO:0005547		PMID:21673657		83333	ComplexPortal		F

----

However there are 115 k InterPro annotations in QuickGO, coming from those 14 mappings: 
* InterPro:IPR001609 Myosin head, motor domain > GO:motor activity ; GO:0003774
* InterPro:IPR002928 Myosin tail > GO:motor activity ; GO:0003774
* InterPro:IPR004009 Myosin, N-terminal, SH3-like > GO:motor activity ; GO:0003774
* InterPro:IPR008989 Myosin S1 fragment, N-terminal > GO:motor activity ; GO:0003774
* InterPro:IPR010926 Class I myosin tail homology domain > GO:motor activity ; GO:0003774
* InterPro:IPR028558 Unconventional myosin-IXa > GO:motor activity ; GO:0003774


* InterPro:IPR000067 Flagellar M-ring protein FliF > GO:motor activity ; GO:0003774
* InterPro:IPR000090 Flagellar motor switch protein FliG > GO:motor activity ; GO:0003774
* InterPro:IPR000527 Flagellar L-ring protein > GO:motor activity ; GO:0003774
* InterPro:IPR000563 Flagellar assembly protein FliH > GO:motor activity ; GO:0003774
* InterPro:IPR001172 Flagellar motor switch FliN/Type III secretion HrcQb > GO:motor activity ; GO:0003774
* InterPro:IPR018006 Flagellar FliJ, proteobacteria > GO:motor activity ; GO:0003774
* InterPro:IPR001624 Flagellar hook-basal body complex protein FliE > GO:motor activity ; GO:0003774
* InterPro:IPR001689 Flagellar motor switch protein FliM > GO:motor activity ; GO:0003774

Do all the flagellar proteins here use PMF ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Might be worth coordinating this with #18664

**Comment by pgaudet** [comment]
Also updated the def of 'motor activity' to 
"Generation of force resulting in movement, for example along a microfilament or microtubule, or in torque resulting in membrane scission or rotation of a flagellum. The energy required is obtained either from the hydrolysis of a nucleoside triphosphate or by an electrochemical proton gradient (proton-motive force)."

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140605
+name: proton motive force-driven motor activity
+namespace: molecular_function
+def: "A motor activity driven by an electrochemical proton gradient (proton-motive force). PMF-driven motors are used by bacterial flagella." [PMID:18216858]
+synonym: "proton motive force-driven motor activity" EXACT []
+is_a: GO:0003774 ! motor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19590 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-17T08:04:50Z

**Comment by ValWood** [comment]
Doesn't that definition also fit ATP synthase?

**Comment by pgaudet** [comment]
Ah maybe ! I can move it as as child ? or are you saying that the definition is too general and should NOT include ATP synthase? We've been having problems classifying this one, see #19380 
Right now its parent classes are: 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/4782928/108187776-1d99d100-710f-11eb-9767-d0acca20ed71.png">

**Comment by ValWood** [comment]
I'm not sure.

You. could either make
GO:0046933    proton-transporting ATP synthase activity, rotational mechanism

a child or narrow the term def to be specific for flagellar motors.

**Comment by sjm41** [comment]
#19738 is also relevant here.
