### ISSUE TITLE
NTR: serine dehydration

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#19597]
I have a paper PMID: 32474107 (Mechanism of eukaryotic serine racemase-catalyzed serine dehydration).
They show that Dicty srr / DdSR/ DDB_G0289463 / Q54HH2 a serine racemase also dehydrates serine, and interestingly D-Ser as well as L-Ser. 

If for wider interest as all organisms have SR, the specification of D-Ser and L-Ser would be great.

- protein dehydration GO:0018249
-- peptidyl-L-serine dehydration GO:NEW
-- peptidyl-D-serine dehydration GO:NEW

And to BP:
- amino acid homeostasis GO:0080144
-- serine homeostasis GO:NEW

Thanks!

**Comment by ValWood** [comment]
Isn't this happening to free amino acids, not  peptidyl?

**Comment by pgaudet** [comment]
Hi Petra, 

protein dehydration GO:0018249 seems like a 1-step BP, we wont be creating those anymore. There are only 2 EXP annotations, I think we should obsolete. 

@hdrabkin what do you think ? 

Thanks, Pascale

**Comment by pfey03** [comment]
@hdrabkin, @pgaudet 
We found these!
GO:0003941 L-serine ammonia-lyase activity
GO:0008721 D-serine ammonia-lyase activity

From the reaction, these are it. Could the simple synonyms be added so I could have found them right away?
GO:0003941
Syn: L-serine dehydration
GO:0008721
Syn: D-serine dehydration

Thanks!

**Comment by hdrabkin** [comment]
done
