### ISSUE TITLE
NTR +ve regulation of transepithelial migration of symbiont in host

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#19601]
Hi, I would like to request +ve regulation of transepithelial migration of symbiont in host

regulates
GO:0035756 transepithelial migration of symbiont in host
standard def

This is from 29113016 where it is shown that a transcription factor activates transcription of genes invovled in transepithelial migration.

Could you also please add 'transmigration' as a synonym to  'transepithelial migration' for searching?

cheers

**Comment by ValWood** [comment]
should
GO:0035756 transepithelial migration of symbiont in host
be is_a
GO:0106259    cell-to-cell migration in host

**Comment by Antonialock** [comment]
No, it seems like there could be multiple routes through the BBB for neoformans,(  and other organisms - bacteria, viruses??)

Only 1/3 potential routes in my case would be cell-cell (See fig)

In this case I don’t know which one is the one used. 

![C43D457D-EF2D-416E-8F3B-E042BCEEDB04](https://user-images.githubusercontent.com/12727506/84359090-068a0300-abc0-11ea-9c67-0b074f699535.jpeg)

**Comment by Antonialock** [comment]
Actually, Is the first scenario cell-cell?

It is lumen (outside) - cell - cell ?

**Comment by ValWood** [comment]
I'm not sure I have  been very confused by this the migration.
not to worry, the relationships between the existing terms should be sorted eventually.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140471
+name: positive regulation of transepithelial migration of symbiont in host
+namespace: Any process that activates or increases the frequency, rate or extent of transepithelial migration of symbiont in host. {xref="PMID:29113016"}
+namespace: biological_process
+synonym: "positive regulation of transmigration of symbiont in host" RELATED []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0035756 ! transepithelial migration of symbiont in host
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19601 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-11T15:32:38Z
