### ISSUE TITLE
Product missing from def of 'inositol phosphoceramide synthase activity'

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#19614]
I think the def of inositol phosphoceramide synthase activity
(Catalysis of the reaction: phytoceramide + inositol phosphate = inositol phosphoceramide)
is missing DAG
eg
Catalysis of the reaction: phytoceramide + inositol phosphate = inositol phosphoceramide + DAG

See figs here:
https://www.jbc.org/content/279/20/21144/F8.expansion.html
https://aac.asm.org/content/44/3/651/figures-only
https://patents.google.com/patent/US20070269844A1/en

**Comment by Antonialock** [comment]
meant ec 2.7.1

**Comment by Antonialock** [comment]
Think I even found the EC: 2.7.1.227

**Comment by hdrabkin** [comment]
Fixed; thanks for spotting this! 
Catalysis of the reaction: phytoceramide + inositol phosphate = inositol phosphoceramide + diacylglycerol.
also added the ec xref.
done
