### ISSUE TITLE
spindle checkpoint terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19613]
GO:0072477 signal transduction involved in mitotic spindle checkpoint
mitotic spindle checkpoint (GO:0071174)

These terms only exist as grouping terms for the spindle assembly checkpoint and the spindle orientation checkpoint.
As such, they are names that are not used and are a) confusing for users, and b) used inappropriately for annotation.

They should  definitely be blocked for direct annotation, but I think it would probably be clearer if such a grouping term did not exist (mitotic cell cycle checkpoint is sufficient as a checkpoint grouping term)

**Comment by ValWood** [comment]
Also, spindle orientation terms has not been used in annotation. I wonder if this really is a thing (it does not exist in fission yeast, it was thought to and then  later shown not to be a real checkpoint. There is a process, spindle orientation, but no separate checkpoint).
If we could get rid of this it would be a nice simplification (but it might. be required for budding yeast?). @srengel

**Comment by pgaudet** [comment]
Those terms already have a check, 'do_not_manually_annotate'. No action needed.
