### ISSUE TITLE
some obsolete CHEBI IDs used (replacements suggested)

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#19617]
```
id: GO:0070276
name: halogen metabolic process
def: "The chemical reactions and pathways involving any halogen, elements of Group VII; includes metabolism of halogen-containing compounds." [CHEBI:22473, GOC:mah]
```
ChEBI replaced CHEBI:22473 with CHEBI:32988. How this new id relates to the GO entry is not clear to me.
```
id: GO:0072745
name: cellular response to antimycin A
intersection_of: has_input CHEBI:22584 ! antimycin A

id: GO:1901325
name: response to antimycin A
intersection_of: has_input CHEBI:22584 ! antimycin A
```
ChEBI replaced CHEBI:22584 with CHEBI:2762 and this seems a proper replacement.
```
id: GO:0072728
name: response to Gentian violet
synonym: "response to {4-[Bis-(4-dimethylamino-phenyl)-methylene]-cyclohexa-2,5-dienylidene}-dimethyl-ammonium chloride" EXACT [CHEBI:198346, GOC:mah]

id: GO:0072729
name: cellular response to Gentian violet
synonym: "cellular response to {4-[Bis-(4-dimethylamino-phenyl)-methylene]-cyclohexa-2,5-dienylidene}-dimethyl-ammonium chloride" EXACT [CHEBI:198346, GOC:mah]
```
ChEBI discontinued CHEBI:198346 without redirecting but apparently Crystal Violet is a synonym for Gentian Violet, and there are two fitting IDs: 
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:41688
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:77181
```
id: GO:0072735
name: response to tert-butyl hydroperoxide
synonym: "response to 2-methyl-prop-2-yl-hydroperoxide" EXACT [CHEBI:365419]
intersection_of: has_input CHEBI:64090 ! tert-butyl hydroperoxide

id: GO:0072736
name: cellular response to tert-butyl hydroperoxide
synonym: "cellular response to 2-methyl-prop-2-yl-hydroperoxide" EXACT [CHEBI:365419]
intersection_of: has_input CHEBI:64090 ! tert-butyl hydroperoxide
```
CHEBI:365419 was discontinued without redirect but here the GO entry itself has the correct CHEBI:64090 so maybe the obsolete one can just be removed
```
id: GO:0071518
name: autoinducer-2 kinase activity
synonym: "4,5-dihydroxy-pentane-2,3-dione kinase activity" EXACT [CHEBI:425228, GOC:mah]
```
CHEBI:425228 was discontinued. Note ChEBI still has (S)-4,5-dihydroxypentane-2,3-dione (CHEBI:29484) so maybe this is the correct substrate of the enzyme.

**Comment by hdrabkin** [comment]
So for your first example
id: GO:0070276
name: halogen metabolic process
def: "The chemical reactions and pathways involving any halogen, elements of Group VII; includes metabolism of halogen-containing compounds." [CHEBI:22473, GOC:mah]
ChEBI replaced CHEBI:22473 with CHEBI:32988. How this new id relates to the GO entry is not clear to me.
CHEBI:32988 is the id for amide,, and redirects from CHEBI:22473  and shouldn't be in a def ref for any go term (will remove), and clearly has NOTHING to do with halogen metabolic process.
halogen is CHEBI:24473, so clearly this was a typo.
Fortunately, the logical def is using the correct chebi id.
I'll start looking at the others.

**Comment by rwst** [comment]
Ah, I didn't check for typos. Thanks!

**Comment by hdrabkin** [comment]
second example
logical def  still works because original CHEBI ID  term has 'term replaced by 'http://purl.obolibrary.org/obo/CHEBI_2762 so works for now
However, I will first have to get the CHEBI import to  bring in all of these new ones so this may take a few days before it can be addressed.

**Comment by rwst** [comment]
I also just see that CHEBI:26977 ! thiosulfate might be better replaced with CHEBI:16094 ! thiosulfate(2−), can I sneak that in with this ticket?

**Comment by hdrabkin** [comment]
Sure; it's better for me to do an import of a bunch of CHEBIs at once.

**Comment by hdrabkin** [comment]
Done, thanks.
