### ISSUE TITLE
Missing parent of calcium ion import into vacuole?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#19610]
shouldn't calcium ion import into vacuole
be is_a vacuolar sequestering ?

**Comment by ValWood** [comment]
Personally I think the "vacuolar sequestering" label and possibly the term is  problematic.

"sequestering" It is too ambiguous and can be interpreted as an "activity" of retaining something at a location.

In GO e "transport activity"  and "sequestering activity are distinct activities.

"vacuolar sequestering" has exact synonym "vacuolar storage"...... storage is closer to what we mean when we refer to "vacuolar sequestering" (it includes transport and sequestering)


suggest a slight rejig if we keep it
vacuolar storage.
Revised definition suggestion: The process of transporting a substance into, and confining within, a vacuole to provide reserves prevent toxicity.
related synonym "vacuolar sequestering"

**Comment by Antonialock** [comment]
Yeah I thought it was weird it has parent
" process of transporting a substance into, and confining within"

but only parent is
"maintenance of location in cell"

But I was co-annotating to  "calcium ion import into vacuole" anyway

**Comment by Antonialock** [comment]
Go, I don't know what I just said, early morning xD 

I was annotating to "calcium ion import into vacuole" anyway, and I wasn't sure whether to co-annotate or not bother with the sequestering term. - its def looks right ( The process of transporting a substance into, and confining within, a vacuole. )
but its parentage looks wrong (only has parent 'maintenance of location' - nothing about movement)

**Comment by pgaudet** [comment]
I'll take this one and do it when I do the sequestering. Hopefully it's not urgent.

Pascale

**Comment by Antonialock** [comment]
Thanks, no rush!

**Comment by ValWood** [comment]
@Antonialock Lock What is the action? Is it still "missing paretn"

**Comment by Antonialock** [comment]
Yeah I wasn't sure if it was missing a parent, maybe maybe not, 

I can't see why you owuld import calcium into a vacuole unless it was for sequestering purposes (it's just storage of it?)

I'm sure storage vs sequestering will come up again :)
