### ISSUE TITLE
usage of both "calcium cation" and "calcium(2+)"

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#19620]
Many entries refer to CHEBI:39123 ! calcium cation and some others to CHEBI:29108 ! calcium(2+). Note that the first includes Ca(1+) and Ca(2+) in ChEBI, and I'm not sure if it was intended to make statements about Ca(1+) (which is obscure to me). So maybe you want to unify usage and use only CHEBI:29108?

**Comment by rwst** [comment]
The same with magnesium(2+) (CHEBI:18420) and magnesium cation (CHEBI:39127) but the former is completely unused in GO.

**Comment by pgaudet** [comment]
@ukemi Can you have a look at this ? 

As far as I recall GOCHE takes care of this, but how can a user tell that the two form of the same chemical are considered the same in GO ?? 

@balhoff

**Comment by ukemi** [comment]
We have equivalence for the conjugate acids and bases. The charge states are in the subsumption hierarchy in ChEBI, so I don't think they are included. I suspect we should just standardize the logical defs. @balhoff?

**Comment by ukemi** [comment]
Since we are aligning to Rhea and the proposed plan was to eventually use their pH7.3 entities, I suggest we also align charge states with them. For example, they use CHEBI:29108 not CHEBI:39123.

**Comment by pgaudet** [comment]
Thanks @ukemi 
Is the list of the pH7.3 entities available somewhere, so we can check which entities we need to replace ?

**Comment by balhoff** [comment]
@pgaudet the list of pH7.3 terms is here: https://www.rhea-db.org/download (chebi_pH7_3_mapping.tsv)

I have an experiment converting all GO ChEBI references to those terms here: https://github.com/geneontology/go-ontology/pull/19355

It has a lot of problems.

**Comment by pgaudet** [comment]
I see at least 2 terms became identical - do you want me to merge them (in your branch I suppose?)

**Comment by balhoff** [comment]
I would consider that branch just an experiment—it would probably be better to make changes you want to keep somewhere else.

**Comment by ukemi** [comment]
This wouldn't be relevant for ionization states though.

**Comment by pgaudet** [comment]
Incorrect: 
CHEBI:39123 ! calcium cation

Correct: 
CHEBI:29108 ! calcium(2+)

**Comment by pgaudet** [comment]
I fixed the Calcium issue. I think others will be fixed in the other ticket @balhoff is working on. 

Thanks, Pascale
