### ISSUE TITLE
MP: GO:0032797   SMN complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19639]
GO:0120114 Sm-like protein family complex
is not an ancestor of 
GO:0032797   SMN complex

should it be? all of the other SMN complexes are under here, and it seems like it was created as a grouping term for all SMN family (not for everything that is like SMN but isn't SMN - this would be against  GO policy).

**Comment by pgaudet** [comment]
@bmeldal 

Thoughts ?

**Comment by bmeldal** [comment]
Apologies for the delay, too many hats...

From the GO defs I would think

GO:0032797 SMN complex
is_a GO:0120114 Sm-like protein family complex

and GO:0032797 SMN complex
part_of GO:0034719 SMN-Sm protein complex

**Comment by pgaudet** [comment]
Thanks @bmeldal
