### ISSUE TITLE
NTR    mitochondrion-ER membrane adaptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19634]
sibling of
GO:0140443    mitochondrion-plasma membrane adaptor activity

The binding activity of a molecule that brings together a mitochondrion and an ER membrane either via membrane lipid binding or by interacting with a mitochondrial outer membrane protein, to establish or maintain the localization of the mitochondrion. 

defs
PMID:19556461 PMID:27875684
might want to obsolete, or merge, or make a parent
GO:1990456    mitochondrion-endoplasmic reticulum membrane tethering

**Comment by ValWood** [comment]
parent protein-membrane adaptor activity;  GOid=GO:0043495

(note to self, move these down)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140474
+name: mitochondrion-endoplasmic reticulum membrane adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a mitochondrion and an ER membrane either via membrane lipid binding or by interacting with a mitochondrial outer membrane protein, to establish or maintain the localization of the mitochondrion." [PMID:19556461, PMID:27875684]
+synonym: "endoplasmic reticulum-mitochondrion membrane adaptor activity" EXACT []
+synonym: "ER-mitochondrion membrane adaptor activity" EXACT []
+synonym: "mitochondrion-ER membrane adaptor activity" EXACT []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19634 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-22T07:01:14Z

**Comment by pgaudet** [comment]
@ValWood 

If we obsolete GO:1990456 mitochondrion-endoplasmic reticulum membrane tethering, we should implement the same solution for all 'tethering' terms. What BP would you recommend instead ?

**Comment by ValWood** [comment]
I think we should look at the tethering one by one. 

If it is an activity only, then the process will sometimes be "organization" (for organelles), 
and the annotation will probably already exist.

so the current situation

GO:1990456 | mitochondrion-endoplasmic reticulum membrane tethering

will become
MF GO:NEW mitochondrion-endoplasmic reticulum membrane adaptor 
part_of BP  mitochondrion localization


But sometimes it might be part of some other process like spindle organization, or some aspect of chromosome segregation for example, and sometimes the tethering might be part of  multiple  different processes (some of the chromatin nuclear tethering).
I think we  might need different solutions for some of them, but we should be able to add F-P links that are always true.

I prefer the obsoletion, I think it will make the annotation more consistent, and more correct.

This might be easier to discuss on the call.  I can explain better, and we can open a new ticket for the changes.

**Comment by ValWood** [comment]
Also some tethering terms in biological  process may be multi-step. So far I am only making the recommendation for the ones that we now know are molecular functions and have only been used for annotating the anchors.

**Comment by ValWood** [comment]
could the "x tether activity" also be added as synonyms (exact)

and when/if  the process terms go
 "x tethering" as related

**Comment by pgaudet** [comment]
I think this is done. Other work should be a new ticket. 

Thanks, Pascale
