### ISSUE TITLE
DNA recombinase-related complexes (ntr and def edit)

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#19631]
companion to #19555 

We have had a PomBase community curator (Hideo Tsubouchi) recommend a new GO CC term, and an enhancement to an existing text definition, for complexes involved in regulating DNA recombination. There are "auxiliary factor" as well as "mediator" complexes, and the distinction is that only mediators promote the exchange of SPA for the recombinase on ssDNA. Some, but not all, complexes can act as both mediators and auxiliary factors.

id: GO:new
name: DNA recombinase auxiliary factor complex
def: "A protein complex that binds to a recombinase and incrseases its activity." [PMID:32414915]
synonym: "DNA recombinase accessory factor complex" EXACT []
synonym: "DNA recombinase activator complex" EXACT []

It would be OK to swap the name and "activator" synonym to match the MF requested in #19555; I only put it as above because the paper uses the "axuiliary factor" wording. I think the complex could also have capable_of GO:new from #19555, but I'll defer to those of you with more experience with those links.

and for GO:0033061 ! DNA recombinase mediator complex, edit the text definition to add recombinase/RPA exchange explicitly:
"A protein complex containing accessory proteins which bind a recombinase (e.g. Rad51) and bind single-stranded DNA (ssDNA), and promote nucleation of the recombinase onto ssDNA through facilitating recombinase-RPA exchange."

For this text edit, the source is mainly a personal communication from Hideo, but I think you could cite the PMID above.

**Comment by krchristie** [comment]
> It would be OK to swap the name and "activator" synonym to match the MF requested in #19555; I only put it as above because the paper uses the "axuiliary factor" wording. I think the complex could also have capable_of GO:new from #19555, but I'll defer to those of you with more experience with those links.

I put in the term name & synonyms as requested. I put in a capable_of relationship link too.

> For this text edit, the source is mainly a personal communication from Hideo, but I think you could cite the PMID above.

cited as suggested.
