### ISSUE TITLE
Create subset for Rhea 7.3 entities

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19647]

**Comment by balhoff** [comment]
@cmungall: I am ready to add these subset annotations to the ChEBI import, but I'm being thwarted by this command line which removes annotation assertions (`--remove-annotation-assertions`):

https://github.com/geneontology/go-ontology/blob/28236037fdd574cb20607f2ae001e3473c54d1d3/src/ontology/Makefile#L362-L363

Do you think it is necessary to continue excluding those?

**Comment by cmungall** [comment]
The only reason to do that was to reduce the size of the file. It gets very large, especially with all the annotation assertions.

The same thing can be achieved in a much more standard fashion with robot
