### ISSUE TITLE
Add RO version of 'acts on population of' to GO

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#19649]
@balhoff @pgaudet @ukemi 

Chris merged the PR for adding 'acts on population of' to RO.

What is the correct order of operations now for replacing the RO relation in GO?

Do we first need to re-import RO, then replace the GOREL version in logical defs, and then obsolete the GOREL term?

Please advise.  Thx.

**Comment by vanaukenk** [comment]
@pgaudet @ukemi @balhoff 

Do we need to now obsolete 'acts on population of' in gorel?

Note that we also still have the relation 'regulates o acts on population of' in gorel, but it could refer to the RO version of 'acts on population of', right?  This would be analogous to a gorel relation like 'regulates o occurs in'.

**Comment by pgaudet** [comment]
Also need to document how new relations /changes from GOREL to RO are implemented in Noctua and P2GO.
