### ISSUE TITLE
Error in 'mitochondrial processing peptidase complex' (GO:0017087) definition.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19643]
Current def:
**A protein complex that consists of a catalytic alpha subunit (alpha-MPP) and a regulatory beta subunit (beta-MPP), and catalyzes the release of N-terminal targeting peptides from precursor proteins imported into the mitochondrion. Source: BRENDA:3.4.24.64, GOC:mah, EC:3.4.24.64**

I think the given functions of the alpha and beta subunits are the wrong way round.

See PMID: 12191769 for a review.

Also see descriptions on the UniProt entries for the human/yeast proteins:
Human alpha subunit (PMPCA) - https://www.uniprot.org/uniprot/Q10713
Human beta subunit (PMPCB) - https://www.uniprot.org/uniprot/O75439
cerevisiae alpha subunit (MAS2) - https://www.uniprot.org/uniprot/P11914
cerevisiae beta subunit (MAS1) - https://www.uniprot.org/uniprot/P10507

**Comment by pgaudet** [comment]
I will also remove the EC and the BRENDA as those should be in MF (right @hdrabkin ??)

**Comment by pgaudet** [comment]
Interestingly we dont have a MF for EC:3.4.24.64. 
The closest term is 'metalloaminopeptidase activity' 

Should I add the xref there ? @hdrabkin 
Although that might mean adding all sorts of EC xrefs for various peptidases that have the same activity, such as this list: 
https://enzyme.expasy.org/EC/3.4.24.-

**Comment by sjm41** [comment]
We used to - GO:0004240 (obsolete)

**Comment by pgaudet** [comment]
Right, because the activity is no different from any metalloprotease

**Comment by hdrabkin** [comment]
The EC should be for the MFs. 
The EC:3.4.24.64 doesn't have a RHEA, most likely because the substrates would be too generic (Release of N-terminal transit peptides from precursor proteins imported into the mitochondrion, typically with Arg in position P2).

**Comment by ValWood** [comment]
I used "metalloendopeptidase activity" because it's an internal bond, but oddly this isn't a descendant of GO:0070006 metalloaminopeptidase activity?

**Comment by ValWood** [comment]
I'll open a new ticket for that...
