### ISSUE TITLE
NTR: somatic muscle contraction terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19667]
Could I have:

a set of somatic muscle contraction terms mirroring the structure for cardiac and skeletal muscles equivalents, please?
Under:
striated muscle contraction GO:0006941
-somatic muscle contraction
--regulation of somatic muscle contraction (also child of regulation striated muscle contraction GO:0006942)
---positive regulation of somatic muscle contraction (also child of positive regulation striated muscle contraction GO:0045989)
---negative regulation of somatic muscle contraction (also child of negative regulation striated muscle contraction GO:0045988)
---regulation of somatic muscle contraction by calcium ion signaling (also child of calcium-mediated signaling GO:0019722)

I think that these terms could all be referenced to: PMID:32024695
And the definitions just mirror the ones for skeletal and cardiac equivalents.

And add a comment to "somatic muscle contraction" to indicate that this term should be used for invertebrates to annotate the equivalent to vertebrate skeletal muscle.

**Comment by hattrill** [comment]
![Screenshot 2020-06-25 at 09 59 51](https://user-images.githubusercontent.com/11865746/85692601-7377bf80-b6cd-11ea-98d8-d3a46790512b.png)

**Comment by krchristie** [comment]
> And add a comment to "somatic muscle contraction" to indicate that this term should be used for invertebrates to annotate the equivalent to vertebrate skeletal muscle.

@hattrill - I've only read this ticket briefly, as well as your other one (`Taxon/guidance note for skeletal muscle organ development` **#19666**) so this is just a thought off the top of my head, but what do you think about the idea of adding additional synonyms to these terms refering to "invertebrate skeletal muscle" to help curators of flies and other invertebrates find these terms.

**Comment by hattrill** [comment]
That would definety help....I have to admit that have real trouble remembering the correct term (especially as skeletal muscle is even used in the FlyBase anatomy ontology)

**Comment by krchristie** [comment]
Hi @hattrill 

I was looking into how to fit your new terms in with respect to the structure of the UBERON terms for muscle types. I also looked at some reviews on invertebrate muscles. While it's true that the insect troponin is most related to the vertebrate fast-skeletal muscle troponin, the invertebrate muscles diverged from the vertebrate ones so long ago. It's not clear to me that the hard distinction between smooth and striated muscle in vertebrates, with some genes being unique to a specific type of muscle (smooth, cardiac, or skeletal) is relevant to invertebrate muscle. 

What to you think about the idea of having terms for `invertebrate somatic muscle contraction` directly under 'muscle contraction` rather than under `striated muscle contraction`? I think this might be more generally applicable to any invertebrate muscle from any invertebrate species.

-Karen 

Sulbarán G, Alamo L, Pinto A, et al. An invertebrate smooth muscle with striated muscle myosin filaments. Proc Natl Acad Sci U S A. 2015;112(42):E5660-E5668. 
doi:10.1073/pnas.1513439112
PMID: 26443857

Cao T, Thongam U, Jin JP. **Invertebrate troponin: Insights into the evolution and regulation of
striated muscle contraction.** Arch Biochem Biophys. 2019;666:40-45.
doi:10.1016/j.abb.2019.03.013
PMID: 30928296

Hooper SL, Hobbs KH, Thuma JB. **Invertebrate muscles: thin and thick filament structure; molecular
basis of contraction and its regulation, catch and asynchronous muscle.** Prog Neurobiol.
2008;86(2):72-127.
doi:10.1016/j.pneurobio.2008.06.004
PMID: 18616971

Hooper SL, Thuma JB. **Invertebrate muscles: muscle specific genes and proteins** [published correction
appears in Physiol Rev. 2005 Oct;85(4):1417]. Physiol Rev. 2005;85(3):1001-1060.
doi:10.1152/physrev.00019.2004
PMID: 15987801

**Comment by krchristie** [comment]
If you feel that you want a terms specifically for invertebrate striated muscle, what about calling it `invertebrate striated muscle`? I'm a little concerned that the word `somatic` might not always correlate to `striated` across all the varieties of invertebrate muscles. I don't mind putting in related synonyms that can help find things, but I think it's nice if the main term name is less ambiguous.

From this paper, here's a reorganized view of a section about the genes in vertebrate and invertebrate troponin.

Cao T, Thongam U, Jin JP. Invertebrate troponin: **Insights into the evolution and regulation of
striated muscle contraction.** Arch Biochem Biophys. 2019;666:40-45.
doi:10.1016/j.abb.2019.03.013
PMID: 30928296

**3. Evolutionary lineage of troponin subunits**

troponin - 3 subunit complex associated with sarcomeric thin filament

**vertebrate troponin**
- TnC
-- belongs to the calmodulin family of E-F hand calcium binding proteins [16,17]
-- two isoforms [15]
--- TnnC1 - slow skeletal/cardiac muscles
--- Tnnc2 - fast skeletal muscle
- TnI and TnT
-- co-evolved striated muscle-specific proteins [16,17]
-- vertebrate TnI and TnT have both diverged into three muscle type-specific isoforms:
--- Tnni1 and Tnnt1 in slow twitch skeletal muscle
--- Tnni2 and Tnnt3 in fast twitch skeletal muscle
--- Tnni3 and Tnnt2 in cardiac muscle
-- genes encoding TnI and TnT in vertebrate genomes are closely linked in three physical pairs [17]
--- Tnni1-Tnnt2
--- Tnni2-Tnnt3
--- Tnni3-Tnnt1

**invertebrate troponin**

Like that in vertebrate striated muscles, the troponin complex is associated with the sarcomeric
thin filament in invertebrate striated muscles to play a central role in the Ca2+ regulation of
contraction and relaxation.


- TpnC for TnC - 6 copies of genes (compared to 2 isoform genes in vertebrates) [18]
- TpnI for TnI - 1 isoform [19]
- TpnT for TnT - 1 isoform [19]

**Comment by hattrill** [comment]
I think that previous coversations have not favoured dividing it into invertebrate vs vertebrate muscle terms.

The most important aspect is to be consistent with its use across the ontology and with researchers expectations.

In the way that muscle development is structured in the ontology, somatic muscle is not under striated muscle tissue development, but they fall under 2 separate branches - muscle structure development and tissue development, so that doesn't help comparison.

In GO, 'somatic muscle development' The process whose specific outcome is the progression of the somatic muscle over time, from its formation to the mature structure. Somatic muscles are striated muscle structures that connect to the exoskeleton or cuticle. 
and in FBbt, somatic muscle 'Muscle cell of the body, excluding the muscles associated with the intestinal tract. It is attached at either end to the cuticle. Fibers of somatic muscles are multinucleate, with the contractile material grouped into fibrils. Somatic muscles appear striated.'

visceral muscle is also described as appearing striated.

FBbt visceral muscle: Muscle that moves the viscera and has only one or, commonly no attachment to the body wall. Visceral muscles differ from skeletal muscles in several respects: adjacent fibers are held together by desmosomes, each fiber is uninucleate and the contractile material is not grouped into fibrils but packs the whole fiber. Visceral muscles appear striated. The visceral musculature comprises circular and longitudinal fibers which surround the entire intestinal  tract, with the exception of the recurrent layer of the proventriculus, and ducts of the reproductive system. The circular fibers derive from a bilaterally symmetrical band of mesodermal cells extending continuously throughout most of the germ band. The longitudinal fibers derive from clusters of mesodermal cells which appear during stage 12 at the posterior end of the embryo and migrate anteriorly

I guess the question is whether appears striated and striated are the same? They can have somewhat looser structures.

I think that I'd better ask an expert about this - sometimes the historical terminology can hinder getting a good over-view of the current picture. I know just the one.....

**Comment by krchristie** [comment]
> The most important aspect is to be consistent with its use across the ontology and with researchers expectations.

Yes, I spent some time yesterday looking at the muscle terms in UBERON and looking at some reviews of invertebrate muscle to try to make sure I placed your requested GO terms correctly with respect to the existing  UBERON terms. Based on this comment in the paper you cited in the initial request, PMID:32024695:

> Gene structure and molecular evolution studies identified the fast skeletal muscle TnT as the ancestral form of the three vertebrate muscle-type–specific isoforms 

I thought perhaps that the existing terms in GO/UBERON for striated muscle would be appropriate parents for the terms you want. However, after looking at several reviews of invertebrate muscle (listed in my previous comment), and some other papers that came up in my searches, such as the one titles "**An invertebrate smooth muscle with striated muscle myosin filaments**" that I listed above as well, I started to feel that our distinction, which is based on what we know about vertebrate muscle, that there are 3 basic types of muscle: smooth, cardiac, & striated might just not be an appropriate way to describe invertebrate muscle. In addition to the paper I just mentioned that talks about a muscle type that seems to mix smooth & striated, I saw some papers talking about 4 types of muscle in some organism (think it was either fly or worm) which didn't clearly correlate to the vertebrate distinctions and which included two different types of striated muscle, transverse and something else. 

Combined with the info I posted in a previous comment about the differences in troponin between vertebrates & invertebrates and the fact that whether vertebrate muscle is smooth (no troponin), cardiac, or striated (slow or fast) depends entirely on which, if any, troponin complex is present, I really started to wonder whether it is appropriate to shoehorn invertebrate muscle types into the smooth/cardiac/striated classification system that is based almost entirely on what we know about vertebrate muscle. 

So, now I'm not sure where to put your terms within the existing classification, or how to make terms that are general categories for invertebrate muscle.

**Comment by krchristie** [comment]
Here's the quote from the paper that talked about oblique versus transverse striated muscle in invertebrates:

Cao T, Thongam U, Jin JP. Invertebrate troponin: Insights into the evolution and regulation of striated muscle contraction. Arch Biochem Biophys. 2019;666:40-45. doi:10.1016/j.abb.2019.03.013
PMID:30928296

> 1.1. Three types of vertebrate muscle
> 
> Three distinct types of muscle cells exist in vertebrates: Skeletal, cardiac and smooth. Skeletal muscle associates with the skeleton to power voluntary movement. Cardiac muscle in the walls of the heart chambers pumps blood through the circulatory system. Skeletal and cardiac muscles are striated muscles. While smooth muscle also contains myosin thick filament and actin thin filament based contractile machinery, the myofilaments in smooth muscle cells are not organized into sarcomeres, corresponding to its non-striated appearance [1].
> 
> 1.2. The types of invertebrate muscles
> 
> The muscle of invertebrate animals can also be divided into striated and smooth types based on the presence or absence of Z-discs as a defining structure of sarcomeres. Sarcomere structures of vertebrate and invertebrate striated muscles are similar and analogous [2]. The invertebrate striated muscles are further sub-grouped into transverse and oblique muscles according to the different patterns of striation. Invertebrate transverse striated muscle is very similar to vertebrate striated muscle with thick and thin filaments organized into sarcomeres [3]. As that in vertebrate striated muscles, the actin thin filaments in invertebrate striated muscle sarcomeres contain troponin complex that functions in the Ca2+-regulation of contraction and relaxation.

**Comment by hattrill** [comment]
Thanks for all your indepth research, Karen. That's very useful.

We have a lot of annotation to under striated muscle terms. Under 'striated muscle cell development' for example, there are terms such as 'myofibril assembly'. Not sure if we want to create a whole set of parallel branches. I will ask Nick Brown what he feels is the best course - he is generally good at getting to the crux of the issue when it comes to these sorts of things.

**Comment by hattrill** [comment]
Hi @krchristie 
Had a chat with Nick and a rethink of the issues.

I think that the upshot is that I do not need this term, so you can close this ticket.

In terms of flies, all muscles are 'striated', but as you point out, we could box ourselves into a corner by suggesting that all somatic muscle is striated and, on reflection, I think that somatic and visceral are best reserved for defining muscle organ development rather than muscle processes. I will opt to use FBbt in extensions to get the detail for the different muscle subtypes wrt troponin.

Having looked at the annotations that we have, there is a fair bit of work I need to do to make sure that they are all in the right place for flies and a few terms that I need to look at in detail. I have a fairly comprehensive list now at least :)

**Comment by krchristie** [comment]
Hi @hattrill 

Thanks for checking in with Nick on this. I'll go ahead and close this ticket. I've marked it "invalid" to track that it was withdrawn, not as a comment on the discussion which was really useful and informative. Let us know if you come across any other places where we need to consider new terms or revisions to existing ones.

Thanks,

-Karen
