### ISSUE TITLE
Taxon/guidance note for skeletal muscle organ development

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19666]
@ukemi I am tagging you here as we've talked about this in the past #18657 

Could you add a comment to GO:0060538 skeletal muscle organ development this along the lines of "For invertebrates, use terms under somatic muscle development (GO:0007525).

And could you also add a comment for somatic muscle development (GO:0007525) along the lines of "This term should be used for invertebrates to annotate the equivalent to skeletal muscle".

Perhaps adding a taxon contraint here would also be helpful.
Never in arthropods Taxonomy ID: 6656
or even Ecdysozoa Taxonomy ID: 1206794 (that covers nematodes as well @vanaukenk - don't want to mess with worm stuff, so I will check in with you!)

**Comment by ukemi** [comment]
It might be best to ask UBERON to add the taxon constraints for these types of terms? Right now the anatomical structure is restricted to eumetazoa, but this could probably be improved.

**Comment by ukemi** [comment]
Maybe only_in craniata?

**Comment by hattrill** [comment]
Maybe only_in craniata? Looks correct to me.

There are some restrictions that come in from UBERON on skeletal muscle terms, I will have to check to see where they impinge. 

Nice to have it in GO, as other tools look in go obo file for taxon rules.

The skeletal muscle terms are a bit of a trap for fly curators, as fly papers refer to skeletal muscle all the time.

**Comment by krchristie** [comment]
@ukemi @pgaudet - Would anyone object to adding the word `vertebrate` to the `skeletal muscle` terms?

Here are some options:
- `vertebrate skeletal muscle`
- `skeletal muscle (vertebrate)`
- `skeletal muscle, vertebrate`

**Comment by krchristie** [comment]
I agree with @ukemi that `skeletal muscle` should be restricted to craniata.

**Comment by pgaudet** [comment]
@krchristie you mean in GO terms ? Maybe we should discuss with editors, this sounds a lot like the sensu terms. 

Not that I mind, but I would like more general guidelines on how we want to do this.

**Comment by krchristie** [comment]
7/27/2020 - Discussion at Ontology Editors' call
- The sister ticket  NTR**: somatic muscle contraction terms #19667** was closed after @hattrill discussed the questions raised by @krchristie with her colleague.
- As discussed in **leucocyte terms for taxon constraint #17613**, the goal is to put taxon constraints at the highest level appropriate. @krchristie will check if the UBERON terms for `skeletal muscle` and `cardiac muscle` already have taxon constraints, and if not what, if any constraints, should be placed on the UBERON terms.
- This provides another example where it will be really useful to have inherited taxon constraints displayed to both ontology editors and annotators.

**Comment by raymond91125** [comment]
It appears that taxon constraints are shown in Protege but not in AmiGO (Protein2GO?). What needs to be done to make taxon constraints easily visible to curators?

Existing constraint:
UBERON:0014892 skeletal muscle organ 'only in taxon' some Eumetazoa
The taxon constraint is propagated to GO:0060538 skeletal muscle organ development
Should probably be revised to 'only in taxon' some Craniata.

UBERON:0014895 somatic muscle 'only in taxon' some Eumetazoa
Definition: "A muscle structure of invertebrates whose origin and insertion sites are in basal side of the epidermis or structures derived from it. The simplest somatic muscles consist of a single cell and associated extracellular structures."
Maybe adding 'never in taxon' some Craniata.

Separately:
UBERON:0001133 cardiac muscle tissue 'only in taxon' some Eumetazoa
This is probably appropriate as flies have FBbt:00058241 contractile cardiomyocyte that appears to be analogous to vertebrate cardiac muscles PMID:34831301.

**Comment by pgaudet** [comment]
We have a [ticket](https://github.com/geneontology/amigo/issues/56) to display this information in AmiGO, but right not we dont have any resources to work on AmiGO improvements 

Meanwhile, QuickGO shows taxon constraints
![image](https://user-images.githubusercontent.com/4782928/177470891-ea8044f3-e94b-4ff4-9249-d63dac6801c3.png)

**Comment by raymond91125** [comment]
Oh, nice.


> Meanwhile, QuickGO shows taxon constraints
