### ISSUE TITLE
annealing helicase activity (GO:0036310) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19669]
From the def and looking at the associated refs, looks like
"is_a: GO:0017111 ! nucleoside-triphosphatase activity"
could/should be changed to the more specific:
"is_a: GO:0016887! ATPase activity"

If it's not ATP-specific, then the definition needs generalising.

tagging @sylvainpoux and @ValWood as I see they were involved in previous development/queries on this term.

==
id: GO:0036310
name: annealing helicase activity
namespace: molecular_function
def: "Catalysis of the ATP-dependent rewinding of single-stranded DNA (ssDNA) to reform base pairs between strands. Often acts on ssDNA bubbles bound by replication protein A (RPA)." [GOC:bf, GOC:sp, PMID:21078962, PMID:22704558, PMID:22705370, PMID:22759634]
synonym: "annealing activity" BROAD [GOC:bf]
synonym: "ATP-dependent DNA annealing activity" RELATED [GOC:sp]
synonym: "nucleoside-triphosphatase activity involved in DNA annealing" EXACT [GOC:bf]
is_a: GO:0017111 ! nucleoside-triphosphatase activity
is_a: GO:0097617 ! annealing activity
is_a: GO:0140097 ! catalytic activity, acting on DNA

**Comment by pgaudet** [comment]
The reason it's like this is that the logical definition is
'nucleoside-triphosphatase activity'
 and ('part of' some 'DNA strand renaturation')

which seems odd ??? 

I will change it to 
'DNA helicase activity'
 and ('part of' some 'DNA strand renaturation')

if anyone can explain the former LD please let me know @cmungall @ukemi 

Thanks, Pascale

**Comment by pgaudet** [comment]
This is the new hierarchy: 

. 'ATPase activity'
.. is_a 'DNA-dependent ATPase activity'
... is_a'DNA helicase activity'
.... is_a 'annealing helicase activity'

Thanks, Pascale

**Comment by sjm41** [comment]
Previous tickets on this:
https://github.com/geneontology/go-ontology/issues/9815
https://github.com/geneontology/go-ontology/issues/12465

**Comment by pgaudet** [comment]
Thanks @sjm41 for the links to the other tickets. As far as I can tell (from scanning quickly) - I dont think what I did was inconsistent with what was discussed in the tickets, right ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Was just checking.... @ukemi said in #12465 "A helicase is defined as driving the unwinding of DNA, so despite the name, this does the opposite."
...suggesting that "annealing helicase activity" shouldn't be a child of "helicase activity" - indeed, the def of that term is "Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the unwinding of a DNA or RNA helix. "

So, it looks like we could either stick with your fix and expand the def of 'helicase activity' beyond just 'unwinding' (ie. to include this annealing activity), or leave that term alone and instead make "annealing helicase activity" a direct child of "ATPase activity".

**Comment by pgaudet** [comment]
Oh ! thanks, I did scan too quickly.

**Comment by pgaudet** [comment]
Changed as follows: 

Removed: 
- is_a GO:0003678 ! DNA helicase activity
- part_of GO:0000733 ! DNA strand renaturation

Added: 
- has_part GO:0016887 ! ATPase activity (to be consistent with other ATP-dependent enzymes)
- part_of GO:0000733 ! DNA strand renaturation

Thanks, Pascale

**Comment by sjm41** [comment]
Following the ATPase review (#20876), this term has lost any parentage to 'catalytic activity'. One option (as stated above) would be to widen the def of 'DNA helicase activity' so that we could add that as a parent.  If that's not possible/desirable, could add "GO:0008094 ATPase, acting on DNA" as parent.
