### ISSUE TITLE
Molecular function regulator children missing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19663]
I spotted this one, but I think others have also disappeared maybe?
GO:0140110   transcription regulator activity

**Comment by pgaudet** [comment]
Missing from where ? I see the term both in AmiGO and in the http://snapshot.geneontology.org/ontology/go-basic.obo file generated yesterday (2020-06-23)

Which file are you looking at ?

**Comment by ValWood** [comment]
I was looking in Quickgo... so can probably close

**Comment by ValWood** [comment]
This is how it lookd in QuickGO

<img width="509" alt="Screenshot 2020-06-24 at 13 47 19" src="https://user-images.githubusercontent.com/7359272/85559022-3c4bd480-b621-11ea-91cd-996f6317a457.png">

**Comment by mah11** [comment]
> GO:0140110 transcription regulator activity

This is not a molecular function regulator - it's a MF term itself, but the regulated thing is the process of transcription.

**Comment by ValWood** [comment]
AH OK but some of the children should be  molecular function regulators
at least
GO:0003712    transcription coregulator activity
should?

**Comment by mah11** [comment]
> GO:0003712 transcription coregulator activity

That one also says it's regulating transcription (the process).

**Comment by ValWood** [comment]
oh yes I was thinking they regulate the 
 DNA-bound DNA-binding transcription factor
but it's only a subset.
"A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators."
