### ISSUE TITLE
NTR:Protein localization to ERGIC

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#19677]
Hello,
I would like to request the following term
Name: Protein localization to ERGIC
Ontology: biological_process
Definition: A process in which a protein is transported to, or maintained in, a location within the endoplasmic reticulum-Golgi intermediate compartment (ERGIC).
is_a: GO:0034067/Protein localization to organelle/Biological Process
Source: PMID:30374053; UniProt: TMED10 (P49755)

Thank you,
Lucille

**Comment by ValWood** [comment]
We don't  refer to proteins specifically in any of the other vesicle-mediated transport  process terms, (I believe because they can also transport other molecules).
I was going to have a quick look (as likely the term you want already exists), but I can't  see TMED10 mentioned in this publication. Which section is it?

**Comment by hdrabkin** [comment]
The 'UniProt: TMED10 (P49755)' would not be used in the def anyways; the PMID is ok and enough.
What is the purpose of this? Is it because you want to annotate the new term to this protein?

**Comment by LucillePo** [comment]
Hello, 
Sorry I was referring to this paper: PMID:32272059 "A Translocation Pathway for Vesicle-Mediated Unconventional Protein Secretion" that indeed describes a new function of TMED10 consisting in transporting cytosolic proteins through the membrane of the ERGIC to further be secreted.
We already annotated the molecular function GO:0008320 "protein transmembrane transporter activity" for TMED10.
It refers as well to the NTR ticket #19680  i submitted yesterday.

**Comment by ValWood** [comment]
So proteins can be trafficked by v-m-t without ever entering the ER.. That's wild !

**Comment by hdrabkin** [comment]
So are we all good with this now that we have the right reference? I'd like to proceed?

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106272
+name: protein localization to ERGIC
