### ISSUE TITLE
NTR: ATPase-coupled iron-sulfur cluster transmembrabe transporter activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19685]
Definition | Parents
Definition | 
Catalysis of the reaction: ATP + H2O + iron-sulfur cluster(in) = ADP + phosphate + iron-sulfur cluster(out).
Synonyms  English spellings

parent
ATPase-coupled transmembrane transporter activity (GO:0042626)

PMID: 31040179

**Comment by pgaudet** [comment]
I will also change BP GO:1902497 iron-sulfur cluster transport to transmembrane transport, since it has not been annotated.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140481
+name: ATPase-coupled iron-sulfur cluster transmembrane transporter activity
+namespace: molecular_function
+synonym: "ATPase-coupled Fe-S cluster transmembrane transporter activity" EXACT []
+synonym: "Catalysis of the reaction: ATP + H2O + iron-sulfur cluster(in) = ADP + phosphate + iron-sulfur cluster(out)." BROAD [PMID:31040179]
+is_a: GO:0005215 ! transporter activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19685 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-25T17:41:01Z
