### ISSUE TITLE
NTR:cytosol to ERGIC protein transport

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#19680]
Hello,

I was wondering if we could create a new GO term describing "cytosol to ERGIC protein transport" based on the following
source: ~PMID:30374053~; UniProt: TMED10 (P49755)
It would show that TMED10 acts as a channel transporting leaderless proteins from the cytosol to the lumen of the ERGIC.

Thank you,
Lucille

**Comment by hdrabkin** [comment]
suggested def wording
suggested parent?

**Comment by pgaudet** [comment]
Can you use a pattern similar to GO:0043001 Golgi to plasma membrane protein transport?  Def = The directed movement of proteins from the Golgi to the plasma membrane in transport vesicles that move from the trans-Golgi network to the plasma membrane.

I think the parent could be 'GO:0015031 protein transport' - I dont find a more specific term. 

Thanks, Pascale

**Comment by ValWood** [comment]
It's odd  (but interesting) if this is a channel ,  because I was under the  impression the intermediate compartment was vesicles moving between the ER and the Golgi...

TMED10 is a vesicle coat protein?
It's  erv25 in yeast, there is quite a large family, they are all coat proteins:
https://www.pombase.org/gene_subset/interpro:IPR015720

Is it acting as a 'channel' or a 'cargo receptor"?

**Comment by deustp01** [comment]
> Can you use a pattern similar to GO:0043001 Golgi to plasma membrane protein transport?

That was my textbook view, that proteins are contranslationally placed in the ER membrane or ER lumen and then travel via the ERGIC to the Golgi and then to the cell surface or extracellular space. But this term request is for a function that enables an initially cytosolic protein to enter the ERGIC, which is definitely not textbook.

**Comment by ValWood** [comment]
I remember been told many years ago by John Armstrong  that proteins could get into the ER but not via the translocon, but the mechanism was not known

**Comment by ValWood** [comment]
I can't find TMED10 in this paper?

**Comment by hdrabkin** [comment]
I made a comment about ignoring the TMED10 as any part of the def, but I think I put it in the wrong ticket. Need more coffee.

**Comment by hdrabkin** [comment]
Ah, found it
The 'UniProt: TMED10 (P49755)' would not be used in the def anyways; the PMID is ok and enough.
What is the purpose of this? Is it because you want to annotate the new term to this protein?

**Comment by ValWood** [comment]
This paper doesn't appear to be about  ERGIC though?

**Comment by hdrabkin** [comment]
I just did a full scan of paper; the words ER, endoplasmic reticulum do not appear. 
This is same paper used for the other ticket on ERGIC
@LucillePo  can you check if the PMID is valid?

**Comment by LucillePo** [comment]
Sorry i was referring to this paper PMID:32272059

**Comment by LucillePo** [comment]
> 
> 
> It's odd (but interesting) if this is a channel , because I was under the impression the intermediate compartment was vesicles moving between the ER and the Golgi...
> 
> TMED10 is a vesicle coat protein?
> It's erv25 in yeast, there is quite a large family, they are all coat proteins:
> https://www.pombase.org/gene_subset/interpro:IPR015720
> 
> Is it acting as a 'channel' or a 'cargo receptor"?

It seems to have two dinstinc functions: 1) one as a cargo receptor (well characterized) and 2) a new function as channel transporting cytosolic proteins (here leaderless proteins) within the lumen of the ERGIC

**Comment by hdrabkin** [comment]
Now that have correct reference, are we good to go with this?

**Comment by pgaudet** [comment]
yes, go ahead

**Comment by hdrabkin** [comment]
+id: GO:0106273
+name: cytosol to ERGIC protein transport
