### ISSUE TITLE
MP "metalloendopeptidase activity"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19681]
"metalloendopeptidase activity"  isn't a descendant of 
GO:0070006 metalloaminopeptidase activity?

from
https://github.com/geneontology/go-ontology/issues/19643

**Comment by sjm41** [comment]
I don't think it should be - metalloaminopeptidase is in the exopeptidase branch, not endopeptidase.

**Comment by deustp01** [comment]
The intention is to classify peptide bond cleavage activiites along two orthogonal axes: mechanism (metallopeptidase, serine peptidase, etc.) and location of cleavage site (aminopeptidase, endopeptidase, carboxypeptidase).

**Comment by ValWood** [comment]
Oh I see, amino is the N-terminal cleavage, I thought it was just peptide (Durr)

This is a signal peptidase though, so isn't  "metalloendopeptidase activity" the correct term to use since it is an internal cleavage site?

**Comment by ValWood** [comment]
Closing this anyway

**Comment by pgaudet** [comment]
Yeah I never know how many residues are accepted between the end and the cleavage site to be an 'amino' or 'carboxyl' peptidase. I just thought, since the signal peptide is at the N term...

**Comment by deustp01** [comment]
My recollection is that amino- and carboxypeptidases, by definition, attack terminal residues only, so near the N-terminus is not good enough.

**Comment by pgaudet** [comment]
OK - but see for eg. https://www.sciencedirect.com/topics/neuroscience/aminopeptidase

> Most remove one amino acid at a time, but a small group cleaves two or three residues at a time; these are known as dipeptidyl and tripeptidyl aminopeptidases, respectively. 


But that would exclude signal peptides anyway.

**Comment by deustp01** [comment]
Right, that excludes signal peptide removal, but it also means the definition for aminopeptidase activity should probably be revised to allow for that annoying small group.

GO:0004177 aminopeptidase activity
Definition: now "Catalysis of the hydrolysis of N-terminal amino acid residues from in a polypeptide chain." 
instead, "Catalysis of the hydrolysis of the N-terminal amino acid residue or rarely two or three residues from a polypeptide chain."

Any evidence that a similar fix is needed for carboxypeptidase activity?

**Comment by sjm41** [comment]
Thanks for updating the amino peptidase def David - I think you could restrict it further to say hydrolysis of a single N-terminal amino acid (see below).

Generally, I think we should be following the definitions in MEROPS for the peptidase classes - looks like we already do for most, but the current defs for 'aminopeptidase activity' and 'carboxypeptidase activity' are exceptions.  So, yes, please update the 'carboxypeptidase activity' def too.

From the MEROPS glossary (https://www.ebi.ac.uk/merops/about/glossary.shtml):

**Exopeptidase**
The exopeptidases require a free N-terminal amino group, C-terminal carboxyl group or both, and hydrolyse a bond not more than three residues from the the terminus. The exopeptidases are further divided into aminopeptidases, carboxypeptidases, dipeptidyl-peptidases, peptidyl-dipeptidases, tripeptidyl-peptidases and dipeptidases.

**Aminopeptidase**
An aminopeptidase liberates a single amino acid residue from the unblocked N-terminus of its substrate....

**Carboxypeptidase**
A carboxypeptidase hydrolyses a single residue from the unblocked C-terminus of its substrate......

**Dipeptidyl-peptidase**
A dipeptidyl-peptidase hydrolyses an N-terminal dipeptide from its substrate...

**Peptidyl-dipeptidase**
A peptidyl-dipeptidase hydrolyses a dipeptide from the C-terminus of its substrate...

**Tripeptidyl-peptidase**
A tripeptidyl-peptidase hydrolyses a tripeptide from the N-terminus of its substrate...

**Dipeptidase**
A dipeptidase hydrolyses a dipeptide, and typically requires that both termini be free...

**Endopeptidase**
An endopeptidase hydrolyses internal, alpha-peptide bonds in a polypeptide chain, tending to act away from the N-terminus or C-terminus.

**Comment by sjm41** [comment]
Following on from above, I see there's a relationship issue too:

id: GO:0008239
name: dipeptidyl-peptidase activity
is_a: GO:0004177 ! aminopeptidase activity

id: GO:0008241
name: peptidyl-dipeptidase activity
is_a: GO:0008238 ! exopeptidase activity

id: GO:0008240
name: tripeptidyl-peptidase activity
is_a: GO:0070009 ! serine-type aminopeptidase activity


If we fully implement the MEROPS definitions, then the is_a relationship for "peptidyl-dipeptidase activity" is correct, but will need changing for the other two:
dipeptidyl-peptidase activity -> is_a: GO:0008238 ! exopeptidase activity
tripeptidyl-peptidase activity -> is_a: GO:0070008 ! serine-type exopeptidase activity

**Comment by pgaudet** [comment]
Hi @sjm41 
I'm adding the is_a parent 'dipeptidyl-peptidase activity' to both 'dipeptidyl-peptidase activity  and 'tripeptidyl-peptidase activity ' - right ?

**Comment by sjm41** [comment]
Hi @pgaudet 
Don't quite understand your last question....did you mean to write 'dipeptidyl-peptidase activity' twice??

If we follow MEROPS definitions, then:
1. Current parent of 'dipeptidyl-peptidase activity' should be changed from 'aminopeptidase activity' to 'exopeptidase activity'
2. Current parent of 'tripeptidyl-peptidase activity' should be changed from 'serine-type aminopeptidase activity' to 'serine-type exopeptidase activity'. (All known tripeptidyl-peptidases are serine type.)

**Comment by sjm41** [comment]
Thanks for fixing those relationships @pgaudet 
Can we also update the two defs mentioned above (to follow MEROPS):

id: GO:0004177
name: aminopeptidase activity
def: "Catalysis of the hydrolysis of N-terminal amino acid residues from in a polypeptide chain." [GOC:jl, ISBN:0198506732]
>
def: "Catalysis of the hydrolysis of a single N-terminal amino acid residue from a polypeptide chain."  [https://www.ebi.ac.uk/merops/about/glossary.shtml]

(similar edits to children defs:
id: GO:0045148 name: tripeptide aminopeptidase activity
id: GO:0070005 name: cysteine-type aminopeptidase activity
id: GO:0070006 name: metalloaminopeptidase activity
id: GO:0070009 name: serine-type aminopeptidase activity)


id: GO:0004180
name: carboxypeptidase activity
def: "Catalysis of the hydrolysis of the terminal or penultimate peptide bond at the C-terminal end of a peptide or polypeptide." [ISBN:0198506732]
>
def: "Catalysis of the hydrolysis of a single C-terminal amino acid residue from a polypeptide chain." [https://www.ebi.ac.uk/merops/about/glossary.shtml]

(similar edits to children defs:
id: GO:0004181 name: metallocarboxypeptidase activity
id: GO:0004185 name: serine-type carboxypeptidase activity
id: GO:0016807 name: cysteine-type carboxypeptidase activity)

**Comment by pgaudet** [comment]
Thanks for the detailed feedback !

**Comment by sjm41** [comment]
Thanks for making all those updates Pascale!
