### ISSUE TITLE
RNA/DNA helicase activity parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19697]
Seems RNA helicase activity (GO:0003724) should have an additional parent of "RNA-dependent ATPase activity (GO:0008186)".

Compare:

id: GO:0003724
name: RNA helicase activity
def: "Catalysis of the reaction: ATP + H2O = ADP + phosphate; this reaction drives the unwinding of an RNA helix." [EC:3.6.4.13, GOC:jl]
is_a: GO:0004386 ! helicase activity
is_a: GO:0140098 ! catalytic activity, acting on RNA

to

id: GO:0003678
name: DNA helicase activity
def: "Catalysis of the reaction: ATP + H2O = ADP + phosphate; this reaction drives the unwinding of the DNA helix." 
is_a: GO:0004386 ! helicase activity
is_a: GO:0008094 ! DNA-dependent ATPase activity
is_a: GO:0140097 ! catalytic activity, acting on DNA

**Comment by pgaudet** [comment]
Don't you consider RNA and DNA the substrates of RNA and DNA helicases, respectively ? 
If this is the case isn't it strange to have 'RNA (or DNA)-dependent' ?

**Comment by sjm41** [comment]
Yes, I would say they are the substrates, so I agree these dependent terms are a bit odd.
I came at this issue from seeing different types of result from a 'DNA helicase' vs 'RNA helicase' search, and that was explained by the difference in parentage between those two terms - I think they should be treated the same, right?
So maybe the fix here is actually to remove the "DNA-dependent ATPase activity" parent from the "DNA helicase activity" term??

**Comment by pgaudet** [comment]
I agree.

**Comment by pgaudet** [comment]
I removed the parent 'DNA-dependent ATPase activity' from 'DNA helicase activity'. 

I am not sure the other children are ok under 'DNA-dependent ATPase activity'

'ATP-dependent protein-nucleic acid complex displacement activity'
'ATP-dependent protein-DNA complex displacement activity'
'cohesin ATPase activity'
'DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity'
'DNA negative supercoiling activity'
'DNA translocase activity'
'DNA translocase activity involved in viral DNA genome packaging'
'protein-DNA loading ATPase activity'
'DNA clamp loader activity'

@ValWood @thomaspd what do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don' think we need to include ATP-dependent, but will these still all be ATPases?

also I think that  "cohesin ATPase activity" can just be "ATPase activity" maybe?

**Comment by pgaudet** [comment]
>  will these still all be ATPases?

Yes - we just need to sort out if it's is_a or 'has_part'

**Comment by sjm41** [comment]
> will these still all be ATPases?

'helicase activity' is_a 'ATPase activity' right now - hoping it will stay that way....

**Comment by pgaudet** [comment]
The has_part is also causing problems for FlyBase ?

**Comment by sjm41** [comment]
I share the same general concern as @ValWood - as I said in #17289: "I just came across this issue in trying to identify all Drosophila ATPases. Searching with "ATPase activity" (GO:0016887) in QuickGO misses lots of seemingly relevant annotations/genes - this appears to be because "ATPase-coupled transmembrane transporter activity" (GO:0042626) is not an is_a child of "ATPase activity".

**Comment by pgaudet** [comment]
Right, OK, thanks ! We'll discuss this with ontology editors.

**Comment by pgaudet** [comment]
On today's ontology call we agreed that proteins with ATPase activity will remain ATPases, see also #20498
