### ISSUE TITLE
TPV GO:2001310   gliotoxin biosynthetic process (Matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19692]
GO:2001310   gliotoxin biosynthetic process

The chemical reactions and pathways resulting in the formation of the epipolythiodioxopiperazine gliotoxin, a poisonous substance produced by some species of fungi. PMID:16333108 PMID:17574915 PMID:18272357 PMID:29966253

is a descendant of "aromatic amino acid biosynthetic process"

Gliotoxin is a sulfur-containing mycotoxin that belongs to a class of naturally occurring 2,5-diketopiperazines produced by several species of fungi, especially those of marine origin.

I'm pretty sure this is wrong....

**Comment by ValWood** [comment]
I don't see this relationship ion CHEBI.

**Comment by ValWood** [comment]
This one still has parentage to "aromatic amino acid biosynthetic process" is this instantiated by GO

**Comment by balhoff** [comment]
@pgaudet:

<img width="1201" alt="explain" src="https://user-images.githubusercontent.com/210210/100134321-07ed7600-2e56-11eb-81d8-5d97932fae4b.png">

**Comment by pgaudet** [comment]
Removed 
-intersection_of: has_primary_input CHEBI:28044 ! phenylalanine
-intersection_of: has_primary_input CHEBI:35243 ! serine zwitterion

This was creating the 'amino acid metabolic process' inference, which is not wrong but is confusing. 

Moved other axioms to subclasses: 
('has part' some 'gamma-glutamylcyclotransferase activity')
('has part' some 'glutathione transferase activity')
('has part' some 'monooxygenase activity')
('has part' some 'N-methyltransferase activity')
('has part' some 'transaminase activity')
('has part' some 'oxidoreductase activity')
('starts with' some 'acid-amino acid ligase activity')
('ends with' some 'disulfide oxidoreductase activity')
