### ISSUE TITLE
NTR: heme receptor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19699]
heme receptor
PMID:32185489
PMID:28193844

Parent
GO:0038024   cargo receptor activity
Definition (GO:0038024 GONUTS page)
Binding specifically to  heme  to deliver it to a transport vesicle.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140488
+name: heme receptor activity
+namespace: molecular_function
+def: "Binding specifically to heme to deliver it to a transport vesicle." [PMID:28193844, PMID:32185489]
+is_a: GO:0038024 ! cargo receptor activity
+intersection_of: GO:0038024 ! cargo receptor activity
+intersection_of: has_input CHEBI:30413 ! heme
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19699 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-29T14:16:16Z
+
