### ISSUE TITLE
GO:0030674    protein-macromolecule adaptor activity def has words missing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19702]
The binding activity of a protein that brings together another macromolecule in contact, permitting those molecules to function in a coordinated way. The adaptor can bring together two proteins, or a protein and another macromolecule such as a lipid or a nucleic acid.

first sentence is not complete.
" brings together another macromolecule in contact,"

**Comment by pgaudet** [comment]
How about: 

"The binding activity of a protein that brings together **two macromolecules** in contact, permitting those molecules to function in a coordinated way. The adaptor can bring together two proteins, or a protein and another macromolecule such as a lipid or a nucleic acid."
