### ISSUE TITLE
MF for Gamma tubulin activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19709]
I would like a new MF term to describe the gamma tubulin complex activity:

MF microtubule nucleation template
The action of a molecule that provides a shape mimicking the end of a microtubule to seed the formation of a new microtubule via self-assembly.

It might fit under:
GO:0005198    structural molecule activity
Definition 
The action of a molecule that contributes to the structural integrity of a complex or its assembly within or outside a cell.

Otherwise it would probably need to go directly under molecular function?

https://pubmed.ncbi.nlm.nih.gov/21993292/
Abstract:
Recent structural work has shed light on the mechanism of γTuRC-based microtubule nucleation, confirming the long-standing hypothesis that the γTuRC functions as a microtubule template.
(review)

https://pubmed.ncbi.nlm.nih.gov/20631709/
Original publication

**Comment by pgaudet** [comment]
I dont think this fits structural molecule. 
Scaffold ??? 

We do have 'DNA template activity', which is under 'binding' (used to annotate telomerase RNA component (TERC)). Should this new term be a sibling ?

**Comment by ValWood** [comment]
If it can't be under structural molecule I don't think it can be a 'scaffold" because we don't have this as an activity (except in the MAP kinase adaptors), and  it isn't an adaptor (we have scaffold complex terms).

It should be under binding too (like adaptors, binding is a component), but it is also an activity in its own right- my aim is to annotate the non-binding activities.

I guess a DNA template could go under the same grouping term.

It's quite a fundamental activity in biology to provide a template for copying, I think it deserves an MF term.

**Comment by pgaudet** [comment]
Created new term + new grouping term

+[Term]
+id: GO:0140489
+name: molecular template activity
+namespace: molecular_function
+def: "The action of a molecule that provides a shape or a sequence mimicking or complementary to the final product, providing template for copying the original molecule's shape or sequence." [GOC:pg]
+is_a: GO:0003674 ! molecular_function
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19709 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-01T08:42:18Z
+
+[Term]
+id: GO:0140490
+name: microtubule nucleation template activity
+namespace: molecular_function
+def: "The action of a molecule that provides a shape mimicking the end of a microtubule to seed the formation of a new microtubule via self-assembly." [PMID:20631709, PMID:21993292]
+is_a: GO:0140489 ! molecular template activity
+created_by: pg
+creation_date: 2020-07-01T08:47:54Z
+

**Comment by pgaudet** [comment]
@ValWood 

1. I am tempted to merge 'DNA template activity' into the child 'template for synthesis of G-rich strand of telomere DNA activity', since this is the only template, AFAIK, other than primers and the actual genomic DNA. We dont annotate those products, do we ? 


2. How about if I changed the term label 'template for synthesis of G-rich strand of telomere DNA activity' to 'telomeric repeat template activity' ? 

Thanks, Pascale

**Comment by ValWood** [comment]
This ticket is overlapping
https://github.com/geneontology/go-ontology/issues/18609

and so I am wondering if the function term might be better
nucleator activity
The activity of seeding  the formation of a new structure by providing a template 

with the template names as synonyms

'nucleator' is the action "template" is the mechanism?

**Comment by ValWood** [comment]
I spoke with an expert who works on gamma tubulin about this.

he says
> “nucleator' is the action "template" is the mechanism” is correct, I think.

so could we rejig this  term in line with my last comment?

(this would also allow us to describe actin nucleator activity in the same way #18609)

**Comment by pgaudet** [comment]
@thomaspd

**Comment by pgaudet** [comment]
Discussing with @thomaspd 

 - [ ]  agree to change the label to 'microtubule nucleator activity' 
 - [ ] looking at Fig 7 of the paper - gamma tubulin looks like it would fit under 'protein-macromolecule adaptor activity', since it bridges GCP2 and GCP3 and the the alpha and beta tubulin. Would that work for you? 
 - [ ] What function did you to annotate GCP2 and GCP3 ? That might help define gamma tubulin's role.

![image](https://user-images.githubusercontent.com/4782928/88228178-0ffe9480-cc6f-11ea-9204-ae22ac3efc9a.png)

**Comment by ValWood** [comment]
I don't see GPC 4,5,6  as a bridge/adaptor. Each member of the gamma tubulin complex is critical to creating the template shape (creating the 3 dimensional template which enables nucleation). If you take away GPC4,5,6 you would not have a template.

I annotated the entire complex with "contributes_to", this seems like a clear case where every subunit is interdependent in the activity of the complex as a functional unit. GPC4,5 and 6 are  not essential, but  we only have single knockouts (which compromise microtubule assembly) - this is most likely because they are closely related and can substitute for each other.

**Comment by ValWood** [comment]
It seems that you changed the primary term name to "mictotubule nucleator activity" so closing
