### ISSUE TITLE
NTR: outer kinetochore adaptor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19701]
NTR: outer kinetochore adaptor

Descendant of
GO:0030674   protein-macromolecule adaptor activity

Def:
The binding activity of a protein that brings the kinetochore and another into contact, permitting those molecules to function in a coordinated way. 

PMID:22521786
Abstract:
We now report that phosphorylation of the conserved MELT motifs in Spc7 by Mph1 (Mps1) recruits Bub1 and Bub3 to the kinetochore and that this is required to maintain the SAC signal.

(and many others)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140483
+name: outer kinetochore adaptor activity
+namespace: molecular_function
+def: "The binding activity of a protein that brings the kinetochore and another into contact, permitting those molecules to function in a coordinated way." [PMID:22521786]
+is_a: GO:0030674 ! protein-macromolecule adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19701 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-29T08:53:10Z

**Comment by ValWood** [comment]
missing word here:


+def: "The binding activity of a protein that brings the kinetochore and another into contact, permitting those molecules to function in a coordinated way." [PMID:22521786]

+molecule
