### ISSUE TITLE
NTR: zinc ion sequestering activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19700]
descendant of
GO:0140313   molecular sequestering activity

Definition (GO:0140313 GONUTS page)
The selective interaction of a protein with a zinc ion to preventing it from interacting with sensitive components of a biological system. 
PMID:12050156

Maybe also a metal sequestering activity superclass would be useful?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140486
+name: zinc ion sequestering activity
+namespace: molecular_function
+def: "The selective interaction of a protein with a zinc ion to prevent it from interacting with sensitive components of a biological system." [PMID:12050156]
+is_a: GO:0140313 ! molecular sequestering activity
+intersection_of: GO:0140313 ! molecular sequestering activity
+intersection_of: has_part GO:0005509 ! calcium ion binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19700 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-29T09:21:42Z
+
+[Term]
+id: GO:0140487
+name: metal ion sequestering activity
+def: "The selective interaction of a protein with a metal ion to prevent it from interacting with sensitive components of a biological system." [PMID:12050156]
+intersection_of: GO:0140313 ! molecular sequestering activity
+intersection_of: has_part GO:0046872 ! metal ion binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19700 xsd:anyURI
+created_by: pg
+creation_date: 2020-06-29T09:23:47Z
+

**Comment by ValWood** [comment]
Thank you!
