### ISSUE TITLE
taxon restriction "host cell nucleus"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19715]
Re
https://github.com/geneontology/go-annotation/issues/3170

Can we get a taxon restriction for "host cell nucleus"
There are now. 54,000 annotations in GOA for vertebrates.

Should be able to add "never vertebrates"?
Can add never in S. pombe and never in S. cerevisiae. (Cerevisiae can cause opportunistic infections, but this does not appear to be by entering cells, it is more 'immunogenic' as far as I can tell.

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0042025&taxonId=9606&taxonUsage=descendants

Question, are taxon restrictions now a hard check? do we drop violating annotations immediately?

**Comment by pgaudet** [comment]
Probably only unicellular organisms can enter other cells ? Maybe we can even use 'never in Opisthokonta' - since even if fungus can enter cells, they probably do not enter the nucleus ? 

@mgiglio99 
@dsiegele 
Any suggestions ?

**Comment by pgaudet** [comment]
@Achchuthan How about eukaryotic parasites ? Do they live/transit in specific organelles?

**Comment by addiehl** [comment]
From [PMID:26195306](https://pubmed.ncbi.nlm.nih.gov/26195306/), "Microsporidia: Eukaryotic Intracellular Parasites Shaped by Gene Loss and Horizontal Gene Transfers"
_Living inside other cells appears to have triggered many reductive changes in the genomes of microsporidia, but this lifestyle also offers unique opportunities to acquire new genetic information. Specifically, intracellular pathogens can be in physical contact with the genetic material of the host (e.g., the microsporidium Nucleospora obligatorily develops inside host nuclei, and others such as Nosema and Encephalitozoon use the nucleus as the developmental niche on occasion) or of coinfecting organisms._

So yes, eukaryotic parasites do specifically enter the host cell nucleus.

**Comment by pgaudet** [comment]
Thanks for the feedback @addiehl 

I used NCBITaxon:33154	Opisthokonta, so I think the case you mention is covered. 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet 
Sorry for the delayed response. Yes, protozoan parasites such as Plamodium and Trypanosoma do transit into specific organelles. In addition, they can also target their proteins into organelles even if they reside in parasitophorous vacuole/ cytosol.
Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Thanks @Achchuthan 

Does that include any Opisthokonta ?

**Comment by Achchuthan** [comment]
@pgaudet, they do not include Opisthokonta

**Comment by pgaudet** [comment]
Changed to 'never in Vertebrata <Metazoa>' after query #19742


Thanks, Pascale
