### ISSUE TITLE
Merge (was: Obsolete) GO:0070010 peptidase activity, acting on D-amino acid peptides and GO:0070011 peptidase activity, acting on L-amino acid peptides

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19722]
D is not used, probably not relevant biologically. 

L has a number of IEAs.

**Comment by pgaudet** [comment]
@sjm41 How about if I just merged those terms into the parent GO:0008233 peptidase activity, as narrow synonyms ? 

Thanks, Pascale

**Comment by sjm41** [comment]
works for me, thanks.

**Comment by pgaudet** [comment]
@deustp01 Note that there are Reactome mappings to GO:0070010 peptidase activity, acting on D-amino acid peptides.
