### ISSUE TITLE
propose obsoletion GO:0048310    nucleus inheritance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19725]
I don't understand this term.

It is defined

The partitioning of nuclei between daughter cells at cell division.

How does this differ from mitosis?

GO:0140014    JSON
mitotic nuclear division
Biological Process
Definition (GO:0140014 GONUTS page)
A mitotic cell cycle process comprising the steps by which the nucleus of a eukaryotic cell divides; the process involves condensation of chromosomal DNA into a highly compacted form. Canonically, mitosis produces two daughter nuclei whose chromosome complement is identical to that of the mother cell.

- [ ]  not this term should have exact synonym "mitosis"

**Comment by ValWood** [comment]
That 'inheritance' branch needs to go...
https://github.com/geneontology/go-ontology/issues/18417

**Comment by mah11** [comment]
Mitosis is the division of one nucleus into two. Partitioning is putting each nucleus into a separate cell. The two can be uncoupled ... I wonder if there should be some kind of link between GO:0048310 and GO:0007349 ! cellularization?

**Comment by ValWood** [comment]
So is this only for multi-nucleated cells?

 The only annotation is to SGD MDM1 and ER-vacuole sorting nexin

**Comment by pgaudet** [comment]
@srengel @suzialeksander 
There are 2 EXP SGD - would be OK to with obsoletion ? 

I also think this while branch should be reviewed and made sure it is consistent and annotations are consistent.

**Comment by ValWood** [comment]
The existing SGD annotation are from a  single  paper for MDM1, the  a gene involved in "mitochondrial inheritance" which we have established isn't a process, but a result of stochastic partitioning at division....

It is possible that there is a specific mechainsm for "nucleus inheritance"  during cellularization, but this could also be stochastic. I had a good search for papers that could be used to annotate genes to  to "nucleus inheritance"  but I could not find any.

If we don't have any biological examples we should obsolete. Nuclear inheritance  obsolete term could refer users to "cellularization" as a possible option.

**Comment by srengel** [comment]
sure obsoletion is fine.

**Comment by srengel** [comment]
p.s. i removed the SGD annotations just now in P2GO.

**Comment by ValWood** [comment]
Just a note. 
In pombe the term isn't required. I'm not sure in S. cerevisiae if the situation isn't slightly different because of budding. Although I would expect to see annotations if this was the case.
Goolge and pubmed searches don't find anything except MDM20 so obsoletion is probably the best option.

**Comment by pgaudet** [comment]
Should I merge into GO:0007349 ! cellularization?

**Comment by ValWood** [comment]
I'm not sure. You could but that isn't the context in which it has been used. But that might not matter if the 2 EXP annotations are gone....

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been to obsolete GO:0048310 nucleus inheritance. The reason for obsoletion is that the process is tries to capture is not clearly defined. There were 2 EXP annotations, that have now been removed. There are no mappings to this term. This term is not present in any subsets. 

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/19725

Thanks, Pascale
