### ISSUE TITLE
"molecular adaptor  activity" parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19721]
This ticket
https://github.com/geneontology/go-ontology/issues/19454
made me realise that  "molecular adaptor" is under protein binding.

This  should probably   also have a parent to "molecular function" since we are describing an "activity" something more than just 'binding'

We are trying to slim everything to 'non-binding' terms,  so that we know we have 'real activities' on everything
and we separate binding from  'real activities' on our gene pages. All of the others are under the root node  (chaperone and carrier).

This might alleviate your concerns about
https://github.com/geneontology/go-ontology/issues/19454

**Comment by ValWood** [comment]
Do you agree with this change?
It seems quite minor but it would have a big impact as we are trying to concentrate on annotation of  'non binding' activities. However this  term is still buried under binding.

**Comment by mah11** [comment]
I don't think I understand the request, or the rationale for it ...

> "molecular adaptor" is under protein binding.

Yes, this is completely consistent with its text definition. More importantly (since a text def can be edited if the need arises), I don't understand how the "adaptor" thing can be done without binding.

> This should probably also have a parent to "molecular function" since we are describing an "activity" something more than just 'binding'

This makes no sense. If "have a parent to molecular function" means "have molecular function as a direct parent" in addition to binding, then it's asking for a redundant link, because binding is_a molecular function -- molecular_function is the root of that branch of GO. If it means change "molecular adaptor" to is_a molecular function instead of is_a binding, then you're back to having to explain how an adaptor could act other than by binding.

**Comment by ValWood** [comment]
This relationship would be in addition to "protein binding".

it follows the same logic as the other binding-type activities that are immediately under molecular function.

GO:0140313    molecular sequestering activity
GO:0140104    molecular carrier activity
GO:0060089    molecular transducer activity
GO:0140299    small molecule sensor activity
(..... these should also have a binding parent)

There is no question that any of these do not function by binding, but that's the case for many molecular functions.

These terms attempt to convey the 'why' of the binding (sequestering, detection, anchoring etc).

There are many reasons for doing this:

One is so that you can provide an input to give a directionality to the binding activity which is otherwise reciprocal (useful for GO-CAM and other pathway modelling) .  
Second you can figure out why the binding is occuring (if it is also a single step activity)  and separate from generic binding
 (which we know probably should not probably  be in GO, and may not even be required in the very long term if we had all the 'binding-type activities covered, and everyone migrated to  use alternative ways to capture generic  protein-protein interaction (for example  between subunits of a if complex). 
Third it will provide a mechanism to separate 'single step binding-type  activities' from generic binding (so you can easily see which proteins are annotated with a MF that is not ONLY under protein binding

**Comment by mah11** [comment]
> This relationship would be in addition to "protein binding".

Which relationship? is_a molecular function would still be redundant.

**Comment by ValWood** [comment]
Yes but it's redundant in most of these cases.

<img width="361" alt="Screenshot 2020-07-07 at 13 26 56" src="https://user-images.githubusercontent.com/7359272/86781398-bb93cc00-c055-11ea-904d-7792a1cf5947.png">

although not always consistently so.

My understanding is that binding is slightly orthogonal to MF, so it isn't really completely redundant.

This creates a way for people to find things that would be hidden under binding by representing their activities rather than just 'binding'. 

Probably it would be more ontologically correct  if 'protein binding' had a has_part relationship to molecular function.  This would get around the "protein binding isn't an activity' and provide a better separation. I don't know what unintended consequences that would have though...

My understanding is that  'protein binding' as an artefact in the MF ontology that we have to live with in the short term, but  we can still create more useable and informative 'activity terms' that are mediated by binding and give them a dual parentage (see the molecular carrier activity eg above).

**Comment by mah11** [comment]
> My understanding is that binding is slightly orthogonal to MF, so it isn't really completely redundant.

This completely contradicts the 'binding is_a molecular_function' link that's been in GO for-basically-ever.

> My understanding is that 'protein binding' as an artefact in the MF ontology 

I agree with this - historically, the "protein binding" term is only there because GO annotation got going before the protein interaction databases did.

> but we can still create more useable and informative 'activity terms' that are mediated by binding and give them a dual parentage

Fine, but it still doesn't make sense, or add meaning, for the additional parent to be the molecular_function root.

> (see the molecular carrier activity eg above)

a. The graph shows that molecular carrier activity is not is_a binding. If it were, it would not also show up as is_a molecular_function (redundant is_a links are removed by the release pipeline).

b. what is an 'eg'?

**Comment by pgaudet** [comment]
Actually, molecular adaptor is under both 'molecular_function' and 'binding' (not 'protein binding').
It's a display issue that this is not shown (I guess because it0s redundant with 'binding'). 

Not sure what to do about that ? @alexsign @kltm 

Thanks, Pascale

**Comment by mah11** [comment]
> Actually, molecular adaptor is under both 'molecular_function' and 'binding'.

This is redundant, because binding is_a molecular function. But it's inconsequential, because ...

> It's a display issue that this is not shown.

It's not just a display issue - redundant is_a links are actually removed by the release (compare go-edit.obo with the output files, e.g. go.obo). This is correct behavior.

**Comment by pgaudet** [comment]
> This is correct behavior.

I agree but to browse this may not be optimal ? Anyhow, I think there is no issue here. Close ?

**Comment by ValWood** [comment]
I think there is quite a major  issue here.

We need a mechanism to see  (and to be able to separate out) the activities that are describing actual mechanisms but are hidden under 'binding'.

I don't know what the solution is, but I recall that part of the purpose of the MF refactoring was to  bring these 'activities' directly under molecular function.

A ditinction between "just binding" and "binding describing a activity, with directionality"  is important for GO-Cam modelling, and even for display on gene pages. Binding on it's own isn't really telling you anything about the activity- . heterochromatin-nuclear membrane anchor activity (GO:0062239) is.

Either way, we are inconsistent because "molecular carrier activity" is not under  "binding" but I don't see how this is different from "molecular adaptor"  (i.e.  in the context of position in the MF ontology. "molecular carrier activity" directly  under Molecular function, but is really a binding activity)

@thomaspd

**Comment by pgaudet** [comment]
Maybe I should change the relation from 'is_a' binding to 'has part'?

**Comment by deustp01** [comment]
> Maybe I should change the relation from 'is_a' binding to 'has part'?

That might help. Perhaps think about catalytic activity here, which always has a binding part that is ordinarily not annotated. That may be part of the difficulty here, distinguishing activities in which biologists think if binding as playing a central, defining part in the activity versus ones in which it's needed, even essential, but that makes it not useful as a differentiating feature in a definition.

**Comment by ValWood** [comment]
This sounds like it could be a solution. These types of  'binding activity' usually have another clause in addition to the binding part.

GO:0140104    JSON
molecular carrier activity
Definition (GO:0140104 GONUTS page)
Directly binding to a specific ion or molecule AND delivering it either to an acceptor molecule or to a specific location.

so binding is only part of the 'activity' BUT  logically wouldn't they need to have an additional has_part? and if so what would that be?

**Comment by ValWood** [comment]
We could obsolete 'binding'. It only has 143 million annotations in QuickGO ;)

**Comment by pgaudet** [comment]
I changed the binding to 'has part'. But then we have the other problem that not all versions of the ontology have this relation. 

@ValWood (and anyone else who's interested) - Can you please check the diff to make sure this looks OK to you ? https://github.com/geneontology/go-ontology/compare/issue-19721?expand=1

Thanks, Pascale

**Comment by ValWood** [comment]
Which terms did you change the relationship between?

**Comment by ValWood** [comment]
Let me know, and I can  follow up. At present, I can't see what changed.

**Comment by ValWood** [comment]
I do see a change now

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0140483
for example.

It looks a bit odd though that there is no visible relationship to binding.

**Comment by ValWood** [comment]
Maybe this is an issue for an editors call? It seems that there is inconsistency and problems that  need a more comprehensive decision on how to handle these types of terms.

We (PomBase)  can workaround however GO decides to do it  ( in our display) , but the different types of binding activity MF  should be handled consistently.



@cmungall 
@thomaspd

**Comment by pgaudet** [comment]
@ValWood 

I had changed to 
is_a molecular_function
has_part some binding

so it should appear as a direct child of MF in tools that dont remove the redundancy with the has_part relationship. 

Is that what you were asking ?

**Comment by pgaudet** [comment]
@ValWood 
Would you attend the ontology call if we put this on the agenda? It'd be nice to hear your point of view. 

Thanks, Pascale

**Comment by ValWood** [comment]
But won't it seem odd to people that things like "protein binding bridging" are no longer visible in the protein binding hierarchy (and how will the querying work for these?).

I would be happy with it like this  because I consider just "binding" to be a place holder, but it might be a rather large change for many.....

**Comment by ValWood** [comment]
> Would you attend the ontology call if we put this on the agenda? It'd be nice to hear your point of view.

yes sure...

**Comment by pgaudet** [comment]
Checked with @thomaspd - he agrees 'has part' binding is correct here.

**Comment by ValWood** [comment]
@thomaspd  Would it be possible at the GO meeting for  you to tell us what the long term plan is for "binding" terms.

My assumption  from talking to @pgaudet  has been that the plan was to keep   "binding activities" separate from plain "binding" (i.e that there would be a way to identify the binding activities which are linked to a specific action, adaptors, chaperones, carriers etc). However, I'm not sure if this assumption is correct?

If this *is* the case it would be useful for everyone to know what the rules are, and the long term plans for the "protein binding" branch of GO so that we can plan ahead. For instance, are there long term plans to remove "protein binding  from GO in the GO-CAM future?

One reason that I ask is that we try to separate out the "activities" from the plain binding for display and this is dependent on   the relationships.  For terms like  molecular adaptor activity, they now have has_part to protein binding and look like this in QuickGO:

<img width="469" alt="Screenshot 2020-09-08 at 18 02 51" src="https://user-images.githubusercontent.com/7359272/92506613-9cecb580-f1fd-11ea-91b2-32b82ed41144.png">

However, there are  two possible problems with this
1. Annotations to "adaptor" terms will no longer be transitively annotated to protein binding (will users find this strange?)
2. What will the other has_part part be?

**Comment by ValWood** [comment]
You can see the display inconsistence at PomBase based on the different parentages
https://github.com/pombase/website/issues/1599

**Comment by ValWood** [comment]
It acknowledged that it is an issue that  terms like "protein, binding bridging" do not display, as "protein binding" and that protein binding  will not inherit these annotations.

**Comment by ValWood** [comment]
@vanaukenk @pgaudet @cmungall @thomaspd 
Could we have an update on the long term plans for the "binding" terms at the ontology meeting. This will help the MOD resources to plan ahead. I looked on the agenda and I can't see any topic related to this or to "molecular function refactoring" in general.

**Comment by pgaudet** [comment]
Can you be more precise about what you want to discuss ?

**Comment by ValWood** [comment]
1.  You did clarify to me on our last call that  the plan is generally to create MF activities with has_part to binding (and that I had not misunderstood or misremembered this). This was part of what I wanted to know (however I'm not sure that this is more generally known by all consortium members?)

2. Also, If protein binding is  to remain in GO, how will the annotations that we lose by binding becoming "has_part" to binding activities be generated? 
Presumably as more "binding functions" are added the actual protein binding annotations will decrease. Maybe this is not an issue. If I have annotated something as a direct input the binding is implicit. Perhaps  we need to do nothing...

3. PomBase uses two methods to capture protein binding, BioGRID and GO. However  because the BioGRid methods  include  'indirect' binding, and a lot of false positive data from Masss spec, we have historically used GO for  confirmed direct protein-protein interactions.
It might be time for us to reconsider this, but it would also be useful to know the long term plans for this branch of GO.

**Comment by ValWood** [comment]
4. Also do we need to be consistent.
In PomBAse we try to separate the binding from the molecular functions. This seems to work for some terms but not for others. For example "copper chaperone activity" stirll appears under "binds" and not under "activity"

https://www.pombase.org/gene/SPBC1709.10c
because the parentage is different?

<img width="357" alt="Screenshot 2020-09-23 at 15 14 01" src="https://user-images.githubusercontent.com/7359272/94024755-b110e500-fdaf-11ea-9419-384f836f25cf.png">

**Comment by ValWood** [comment]
I knew there was another ticket about this issue somewhere:
https://github.com/geneontology/go-ontology/issues/16742
You can close this one if you like. I think it would be useful if people knew the short,medium,long term plan for protein binding, but this does not affect PomBase so much as we try not to use them, and removing the inferred ones is relatively easy to manage.

**Comment by pgaudet** [comment]
Next ontology call: Discuss Val's questions: https://github.com/geneontology/go-ontology/issues/19721#issuecomment-697417510

**Comment by pgaudet** [comment]
@ValWood I think this is resolved with the 'has part' binding implementation.

WRT your point 2 here: https://github.com/geneontology/go-ontology/issues/19721#issuecomment-697417510
@cmungall proposes that we instantiate the 'has part' into annotations, to make sure that those are picked up by legacy tools that only use is_a and part_of relations. 

Does that work for you ? Can this close ?

**Comment by ValWood** [comment]
I think that could be OK, but I'm not sure:

a) that has_part can be correctly instantiated in every ontology branch.
(I can't find examples because it is't possible for me to view the has_part relations easily, but I'm surer I remember that bing the case)

b) that we would *always * want the instantiated anotations.

For example:
if we annotated to some "adaptor" terms  with a has_input, I'm not sure we would necessarily want to generate all of the equivalent/redundant  has_part "protein binding" terms....

**Comment by pgaudet** [comment]
>a) that has_part can be correctly instantiated in every ontology branch.

not sure why not ? Or was is to do with the regulates closure? 

>b) that we would *always * want the instantiated anotations.

Can you specify in which cases you dont want them? Maybe we should consider excluding terms with low information content like 'binding' and 'protein binding'?

**Comment by ValWood** [comment]
I don't  have a good feeling for where and how has_part is used so I'm not sure.
I guess one option would be to generate them, and then sanity check them?

**Comment by pgaudet** [comment]
Will be fixed by https://github.com/geneontology/pipeline/issues/130
