### ISSUE TITLE
cell size term GO:0001559    regulation of cell growth by detection of nuclear:cytoplasmic ratio

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19736]
Hi,

I am  trying to interpret and re  annotate the cell size  at division control integrating half a century of work (it isn't as many papers as you would imagine, but it spans 50 years)

I came across this term
GO:0001559    regulation of cell growth by detection of nuclear:cytoplasmic ratio
and I'd like to find it's source.

I could not find anything in GitHub, it has no reference and no annotations. 

Any ideas ?
(It could be me but I don't know why or for what)

**Comment by pgaudet** [comment]
The parent  "GO:0016475 detection of nuclear:cytoplasmic ratio" doesn't have annotations or references either.

**Comment by pgaudet** [comment]
Looks like this is a character if aging cells: 

https://en.wikipedia.org/wiki/NC_ratio

Obsolete ??

**Comment by ValWood** [comment]
Probably originates from
https://www.pombase.org/reference/PMID:28545058
https://www.pombase.org/reference/PMID:30759079
there is clearly a mechanism to scale the size of the nucleus with the size of the cell, (in normal cells)  but we don't know enough about this to annotate to the process yet.
The major players are likey to be essential genes that would not pop up in the deletin collection screen.

So I understand GO:0016475 detection of nuclear:cytoplasmic ratio" 

I think the terms are OK.  I guess the implication is that the cell will grow to match the size of the nucleus.

**Comment by ValWood** [comment]
GO:0001559 regulation of cell growth by detection of nuclear:cytoplasmic ratio

confused me because I don't know if growth is regulated by this mechanism, or if the nucleus size  scales with cell size


I think the parent is OK but the "regulation of cell growth" child term seems a bit dodgy?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0001559 regulation of cell growth by detection of nuclear:cytoplasmic ratio', because there is no evidence that this process exists. 

There are no annotations or mappings to this term; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/19736


Thanks, Pascale
