### ISSUE TITLE
NTR: very long-chain fatty acid beta-oxidation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19735]
Hi,

Could I request:

very long-chain fatty acid beta-oxidation

is_a
GO:0042760 very long-chain fatty acid catabolic process
GO:0033540 fatty acid beta-oxidation using acyl-CoA oxidase

ref: PMID:17028011 & PMID:32169171

Def: A fatty acid beta-oxidation pathway acting on fatty acid which has a chain length greater than C22 in which the initial step, which converts an acyl-CoA to a trans-2-enoyl-CoA, is catalyzed by acyl-CoA oxidase; the electrons removed by oxidation pass directly to oxygen and produce hydrogen peroxide, which is cleaved by peroxisomal catalases. Fatty acid beta-oxidation begins with the addition of coenzyme A to a fatty acid, and ends when only two or three carbons remain (as acetyl-CoA or propionyl-CoA respectively). 

GOC:ha

**Comment by pgaudet** [comment]
isn't that a MF ? Is an oxidoreductase activity that should be annotated to 
GO:0042760 very long-chain fatty acid catabolic process?

**Comment by hattrill** [comment]
It's a multistep process, https://en.wikipedia.org/wiki/Beta_oxidation

**Comment by hattrill** [comment]
Think that very long-chain fatty acid catabolic process is not specific term for this

**Comment by deustp01** [comment]
> Think that very long-chain fatty acid catabolic process is not specific term for this

Beta-oxidation is the major way to catabolize very long-chain fatty acids, not sure whether it's the only one. There is an alpha-oxidation pathway for phytanate (ChEBI:16285) a large branched-chain fatty acid. @hdrabkin - any more ideas?

**Comment by hattrill** [comment]
Beta oxidation is the major pathway, but I think that it would be difficult to be really sure that they can't be touched by other lipolytic enzymes.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140493
+name: very long-chain fatty acid beta-oxidation
+def: "A fatty acid beta-oxidation pathway acting on fatty acid which has a chain length greater than C22 in which the initial step, which converts an acyl-CoA to a trans-2-enoyl-CoA, is catalyzed by acyl-CoA oxidase; the electrons removed by oxidation pass directly to oxygen and produce hydrogen peroxide, which is cleaved by peroxisomal catalases. Fatty acid beta-oxidation begins with the addition of coenzyme A to a fatty acid, and ends when only two or three carbons remain (as acetyl-CoA or propionyl-CoA respectively)." [GOC:ha, PMID:17028011, PMID:32169171]
+is_a: GO:0033540 ! fatty acid beta-oxidation using acyl-CoA oxidase
+is_a: GO:0042760 ! very long-chain fatty acid catabolic process
+created_by: pg
+creation_date: 2020-07-10T08:39:22Z

**Comment by hattrill** [comment]
Thanks!
