### ISSUE TITLE
Isomerase parent for ATPase-coupled motors (etc)??

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19738]
I notice that the EC has recently (?) transferred some EC:3.6 ATPase (hydrolase) terms to an isomerase classficiation: several ATPase-coupled activities are now annotated as isomerases under EC:5.6.1 ("Enzymes altering polypeptide conformation or assembly"):

5.6.1.1      Microtubule-severing ATPase (Formerly EC 3.6.4.3)
5.6.1.2      Dynein ATPase (Formerly EC 3.6.1.33 AND EC 3.6.4.2)
5.6.1.3      Plus-end-directed kinesin ATPase (Formerly EC 3.6.4.4)
5.6.1.4      Minus-end-directed kinesin ATPase (Formerly EC 3.6.4.5)
5.6.1.5      Proteasome ATPase (new)
5.6.1.6      Channel-conductance-controlling ATPase (Formerly EC 3.6.3.49)
5.6.1.7      Chaperonin ATPase (Formerly EC 3.6.4.9)
5.6.1.8      Myosin ATPase (Formerly EC 3.6.1.32 and EC 3.6.4.9)
5.6.1.9      (R)-2-hydroxyacyl-CoA dehydratase activating ATPase (new)

https://enzyme.expasy.org/EC/5.6.1.-

Looks like the GO has been updated with most (but not all) of these EC xrefs on the appropriate GO terms, though none of those terms have been put under 'isomerase activity' (GO:0016853).

Was it intentional not to add the isomerase parentage, or should we fully reflect these EC changes within the GO??

I've tried to list (some of) the possible changes below, but we may want to hive these off into separate tickets if decide to go down this road....

@kaxelsen, @ukemi, @deustp01 , @pgaudet , @hdrabkin 

==
id: GO:0008568
name: microtubule-severing ATPase activity
def: "Catalysis of the reaction: ATP + H2O = ADP + phosphate. Catalysis of the severing of a microtubule at a specific spot along its length, coupled to the hydrolysis of ATP." [EC:5.6.1.1, PMID:10910766]
xref: EC:5.6.1.1
is_a: GO:0016887 ! ATPase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein

**-> ADD "is_a: GO:0016853 ! isomerase activity" to this term?**

==

id: GO:0008574
name: ATP-dependent microtubule motor activity, plus-end-directed
namespace: molecular_function
def: "Catalysis of movement along a microtubule toward the plus end, coupled to the hydrolysis of ATP." [EC:5.6.1.3, GOC:vw]
xref: EC:5.6.1.3
is_a: GO:1990939 ! ATP-dependent microtubule motor activity

**-> ADD "is_a: GO:0016853 ! isomerase activity" to a parent term, maybe "motor activity" (GO:0003774)?**

==

id: GO:0008569
name: ATP-dependent microtubule motor activity, minus-end-directed
def: "Catalysis of movement along a microtubule toward the minus end, coupled to the hydrolysis of ATP." [EC:5.6.1.4, GOC:mah, GOC:vw]
xref: EC:5.6.1.4
xref: MetaCyc:3.6.4.5-RXN
is_a: GO:1990939 ! ATP-dependent microtubule motor activity

**-> add EC:5.6.1.2 as second xref (GO:0008567 'dynein ATPase activity' is obsolete)?
-> as above, ADD "is_a: GO:0016853 ! isomerase activity" to a parent term, maybe "motor activity" (GO:0003774)?**

==

id: GO:0030898
name: actin-dependent ATPase activity
def: "Catalysis of the reaction: ATP + H2O = ADP + phosphate. This reaction requires the presence of an actin filament to accelerate release of ADP and phosphate." [GOC:mah]
is_a: GO:0016887 ! ATPase activity

**-> consider adding EC:5.6.1.8 as xref?
-> as above, ADD "is_a: GO:0016853 ! isomerase activity" to a parent term, maybe "motor activity" (GO:0003774)?
-> (need to also consider #18664 here)**

==

id: GO:0005260
name: intracellularly ATP-gated chloride channel activity
def: "Enables passage of a chloride ion through a transmembrane channel that opens when ATP is bound by the channel complex or one of its constituent parts on the intracellular side of the plasma membrane." [PMID:24727426, PMID:9922375]
xref: EC:5.6.1.6
is_a: GO:0005254 ! chloride channel activity
is_a: GO:0099095 ! ligand-gated anion channel activity
is_a: GO:0099142 ! intracellularly ATP-gated ion channel activity

**-> ADD "is_a: GO:0016853 ! isomerase activity" to this term?? (this one seems the oddest...)**

==

id: GO:0036402
name: proteasome-activating ATPase activity
def: "Catalysis of the reaction: ATP + H2O = ADP + phosphate, which promotes unfolding of protein substrates, and channel opening of the core proteasome." [GOC:rb, PMID:11430818]
is_a: GO:0016887 ! ATPase activity

**-> ADD "is_a: GO:0016853 ! isomerase activity" to this term??**
**-> ADD EC:5.6.1.5 as an xref**

**Comment by kaxelsen** [comment]
FYI, the title of the subclass EC 5.6 is ' Isomerases altering macromolecular conformation'

**Comment by ValWood** [comment]
well these are really very multifunctional.....
This is dynein model in PMID:33230227

<img width="677" alt="Screenshot 2021-02-17 at 17 46 55" src="https://user-images.githubusercontent.com/7359272/108245400-25299c00-7148-11eb-8424-c281fe341164.png">

 ... there is tension, power strokes, linkers created, but I don't really want to curate this mechanistic  detail so I'm happy with an ATP-dependent  microtubule/microfilament  motor.... but there are may parts (it's probably more accurately a process!)

**Comment by pgaudet** [comment]
Added xref: EC:5.6.1.8 and xref: EC:5.6.1.5 as suggested

I will not add parent 'isomerase activity because as @kaxelsen said, EC:5 uses this term with a different meaning.
