### ISSUE TITLE
spindle elongation regulation terms do not match the parents.

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19745]
GO:0061804    mitotic spindle formation (spindle phase one)
defined
The cell cycle process in which the distance is lengthened between poles of the mitotic spindle during mitotic prophase.

but the regulation terms say
GO:0110159    regulation of mitotic spindle formation (spindle phase one)
Any process that modulates the frequency, rate or extent of mitotic spindle formation (spindle phase one).

could the definitions be revised to:

GO:0110159
Any process that modulates the frequency, rate or extent of the cell cycle process in which the distance is lengthened between poles of the mitotic spindle during mitotic prophase.

otherwise if you are only looking at the regulation terms it is difficut to know precisely what it means?

Also for the repsective +ve and -ve regulation terms, and for

GO:0061805    mitotic spindle elongation (spindle phase three)

**Comment by pgaudet** [comment]
Hi @ValWood 
Is/are there paper(s) we can add to the definition ?

**Comment by pgaudet** [comment]
Also, I suppose we keep the ("spindle phase one/three") in the definitions, otherwise they are identical - right ?

**Comment by pgaudet** [comment]
WRT to the reference, looks like I can use the same as for the Phase III terms, PMID:27697865

**Comment by ValWood** [comment]
Yes spindle phase I an III are important, they are 2 separate phases of 'elongation' and  seem to be used fairly universally (phase 2 is static). I would prefer also to refer to the phases in the term names too, but this became a little complicated

see
https://github.com/geneontology/go-ontology/issues/13461

> * 3. Takashi also suggests that we revise GO:0061804  name
>   from
>   mitotic spindle elongation during mitotic prophase
>   to
>   mitotic spindle elongation during prophase and prometaphase
> 
> These term names with phases might seem a bit odd so we _could_ name this
> mitotic spindle formation (spindle phase one)
> synonym mitotic spindle elongation during prophase
> synonym mitotic spindle elongation during prophase and prometaphase
> (We only need the word "mitotic" in the elongation terms/synonyms once)
> 
> and
> from
> GO:0061805 | mitotic spindle elongation during mitotic anaphase
> to
> mitotic spindle elongation (spindle phase three)
> synonym mitotic anaphase spindle elongation
> synonym mitotic spindle elongation during mitotic anaphase


in retrospect maybe the terms with phases in are better with the spindle stage as synonyms?
I thought it might sound a bit complicated with "during prophase and prometaphase" but I probably made it less clear?


===

> WRT to the reference, looks like I can use the same as for the Phase III terms, PMID:27697865.
> 
> Actually, I've added for regulation, but I am not sure the paper shows positive/negative regulation. (it actually seems more like an upstream step than actual regulation? ).


Re that paper , possibly not and I also thought this was indirect, but the author was pursuasive and  it does seem that  PIP levels directly regulate microtubule stability. There are more papers:
It does seem that these control some aspects of microtubule organization, and hence spindle elongation very directly.

PMID:29440310
--
Title: | Asp1 Bifunctional Activity Modulates Spindle Function via Controlling Cellular Inositol Pyrophosphate Levels in Schizosaccharomyces pombe.
Authors: | Pascual-Ortiz M, Saiardi A, Walla E, Jakopec V, Künzel NA, Span I, Vangala A, Fleig U
Abstract: | The generation of two daughter cells with the same genetic information requires error-free chromosome segregation during mitosis. Chromosome transmission fidelity is dependent on spindle structure/function, which requires Asp1 in the fission yeast Schizosaccharomyces pombe Asp1 belongs to the diphosphoinositol pentakisphosphate kinase (PPIP5K)/Vip1 family which generates high-energy inositol pyrophosphate (IPP) molecules. Here, we show that Asp1 is a bifunctional enzyme in vivo : Asp1 kinase generates specific IPPs which are the substrates of the Asp1 pyrophosphatase. Intracellular levels of these IPPs directly correlate with microtubule stability: pyrophosphatase loss-of-function mutants raised Asp1-made IPP levels 2-fold, thus increasing microtubule stability, while overexpression of the pyrophosphatase decreased microtubule stability. Absence of Asp1-generated IPPs resulted in an aberrant, increased spindle association of the S. pombe kinesin-5 family member Cut7, which led to spindle collapse. Thus, chromosome transmission is controlled via intracellular IPP levels. Intriguingly, identification of the mitochondrion-associated Met10 protein as the first pyrophosphatase inhibitor revealed that IPPs also regulate mitochondrial distribution.


although I agree that the regulation annotations should probably not be made from the other publication, and I might switch them to phenotypes for now...

**Comment by ValWood** [comment]
I also have a note in the curation session for PMID:27697865 that the author specified phase 3 elongation (anaphase), not initial phase 1 assembly.
