### ISSUE TITLE
modify definitions of GO:0043886 and GO:0031470

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#19743]
Hello,
GO:0043886 (structural constituent of carboxysome, an MF term) has the following definition:
"The action of a molecule that contributes to the structural integrity of a carboxysome, an organelle found in the Cyanobacteria consisting of a proteinaceous coat and enzymes for the fixation of carbon dioxide. "
--carboxysomes also exist in some chemoautotrophs, (see PMID  28934381 for a review) so the definition is too narrow. I suggest the following:

"The action of a molecule that contributes to the structural integrity of a carboxysome, an organelle found in all cyanobacteria and some chemoautotrophs, consisting of a proteinaceous coat and enzymes for the fixation of CO(2). "

There is also an improvement possible for the carboxysome term in GO (GO:0031470). It says:
"An organelle consisting of a proteinaceous coat and enzymes for the fixation of carbon dioxide including mechanisms for the concentration of carbonate to increase the efficiency of fixation under low-carbon dioxide conditions."
--which isn't quite true, they are required under atmospheric conditions, and to increase CO(2) levels (the RuBisCO substrate), not carbonate. So:
"An organelle consisting of a proteinaceous coat and enzymes for the fixation of CO(2). It augments the concentration of CO(2) in the vicinity of RuBisCO to increase the efficiency of CO(2) fixation under atmospheric conditions."

Thanks, Andrea

**Comment by pgaudet** [comment]
Hi Andrea, 

(We exchanged about this a few days ago): following that discussion - are there proteins whose function is to maintain the structure of the carboxysome? Or should that term be obsoleted ? (I see there are no annotations)

Thanks, Pascale

**Comment by AndreaAuchincloss** [comment]
Hi Pascale,

There are a number of proteins that form the carboxysome; the shells are formed by CcmK/CsoS1 paralogues, the vertices by CcmL/EutN/CsoS4/PduL proteins, probable minor shell proteins such as CcmO and cCmP, with other proteins that also help structurally and with assembly, CcmM, CcmN (note I didn't go looking for all their different names in different compartments). Do proteins that form the carboxysome also maintain the carboxysome? I'm still having problems understanding which proteins I would annotate with GO:0043886...

Thanks, Andrea
