### ISSUE TITLE
some KEGG: refs have wrong sub-ids

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#19740]
I guess the following KEGG refs were added before there was a KEGG segment for processes. `KEGG:00540` should be `KEGG:map00540`.
```
id: GO:0008917
def: "Catalysis of the reaction: UDP-N-acetyl-D-glucosamine + lipopolysaccharide = UDP + N-acetyl-D-glucosaminyl-lipopolysaccharide." [EC:2.4.1.56, GOC:mr, KEGG:00540]

id: GO:0008918
def: "Catalysis of the reaction: UDP-galactose + lipopolysaccharide = UDP + 1,3 alpha-D-galactosyl-lipopolysaccharide." [EC:2.4.1.44, GOC:mr, KEGG:00540]

id: GO:0008919
def: "Catalysis of the reaction: UDP-glucose + lipopolysaccharide = UDP + D-glucosyl-lipopolysaccharide." [EC:2.4.1.58, GOC:mr, KEGG:00540]
```
However it might be even better to move them all to GO:0009103.

**Comment by pgaudet** [comment]
Hi @rwst 
What do you mean by 

> However it might be even better to move them all to GO:0009103.

The 3 terms above are Molecular Functions, and GO:0009103  is a Biological Process. 

I can add a relation that states that the 3 MFs are part of GO:0009103 lipopolysaccharide biosynthetic process - would that work ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
* Also fixed KEGG_PATHWAY:map00440

* I will move the KEGG pathway xref to the BP (since it doesnt represent a reaction). 

Thanks, Pascale

**Comment by rwst** [comment]
Exactly, the KEGG map refs are pathways. Thanks!

**Comment by pgaudet** [comment]
I fixed the xrefs. 'part of GO:0009103 lipopolysaccharide biosynthetic process'  was already present for all 3 terms. 

Thanks for reporting this. 

Pascale
