### ISSUE TITLE
NTR: negative regulation of UDP-N-acetylglucosamine biosynthetic process (and parent) 

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#19746]
Hi,

I would like to request the following term 'negative regulation of UDP-N-acetylglucosamine biosynthetic process' be added to the process ontology. This will require an additional term be created first in the process ontology 'regulation of UDP-N-acetylglucosamine biosynthetic process' using the regulates relationship. Authors present evidence that the putative ISR1 kinase negatively regulates hexosamine biosynthesis in yeast. This is the pathway where GFA1, GNA1, PCM1, and QRI1, work to convert fructose-6-phosphate into UDP-N-acetylglucosamine, a precursor of chitin biosynthesis, GPI-anchor formation and a precursor for protein glyosylation. 

https://pathway.yeastgenome.org/YEAST/new-image?type=PATHWAY&object=UDPNAGSYN-YEAST-PWY&detail-level=2

GO:0006048 UDP-N-acetylglucosamine biosynthetic process 
----->GO:XXXXXXX	regulation of UDP-N-acetylglucosamine biosynthetic process	(regulates)
----------->GO:YYYYYYY	negative regulation of UDP-N-acetylglucosamine biosynthetic process (is_a)

GO:XXXXXXX	regulation of UDP-N-acetylglucosamine biosynthetic process
Definition: 	Any process that modulates the frequency, rate or extent of the UDP-N-acetylglucosamine biosynthetic process.
Synonyms:	regulation of UDP-GlcNAc biosynthesis
		regulation of UDP-GlcNAc biosynthetic process
		regulation of UDP-N-acetylglucosamine anabolism
		regulation of UDP-N-acetylglucosamine biosynthesis
		regulation of UDP-N-acetylglucosamine formation
		regulation of UDP-N-acetylglucosamine synthesis

GO:YYYYYYY	negative regulation of UDP-N-acetylglucosamine biosynthetic process
Definition: 	Any process that stops, prevents or reduces the frequency, rate or extent of the UDP-N-acetylglucosamine biosynthetic process.

Synonyms:	negative regulation of UDP-GlcNAc biosynthesis
		negative regulation of UDP-GlcNAc biosynthetic process
		negative regulation of UDP-N-acetylglucosamine anabolism
		negative regulation of UDP-N-acetylglucosamine biosynthesis
		negative regulation of UDP-N-acetylglucosamine formation
		negative regulation of UDP-N-acetylglucosamine synthesis

Reference:
Alme EB, et al. (2020) The kinase Isr1 negatively regulates hexosamine biosynthesis in S. cerevisiae. PLoS Genet 16(6): e1008840.
https://www.yeastgenome.org/reference/S000275105
32579556

Cheers,
Rob

**Comment by hdrabkin** [comment]
+id: GO:0106278
+name: regulation of UDP-N-acetylglucosamine biosynthetic process

+id: GO:0106279
+name: negative regulation of UDP-N-acetylglucosamine biosynthetic process
+namespace: biological_process

**Comment by hdrabkin** [comment]
Hi @robnash 
I was thinking while I'm at it to recreate the positive reg term. Do you have a reference for that or do you think the same paper is good for it?

**Comment by robnash** [comment]
Hi Harold,
I don't have another paper in mind at the moment so I think this paper could suffice for the moment. They do state in this paper: "In other organisms, including C. albicans, drosophila, and humans, phosphorylation by multiple kinases, including AMPK and PKA, has been shown to both positively and negatively regulate Gfa1 activity [19,20,22,23,37,38]." so there appears to be other evidence out there regarding positive regulation. However, I  don't see any specific yeast papers other than one on transcriptional regulation of GFA1 by a phosphatase (PMID: 10764753).  

Thanks for adding these so quickly.

Cheers,
Rob

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106280
+name: positive regulation of UDP-N-acetylglucosamine biosynthetic process
