### ISSUE TITLE
Precompute inferred taxon constraints and add to ontology release

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#19759]

**Comment by cmungall** [comment]
We can use this to show TCs in amigo, see:

https://github.com/geneontology/amigo/issues/56 https://github.com/geneontology/amigo/issues/58

The requirements are that a class should have a direct lookup to non-redundant only-in and never-in. 

E.g for cameraa-type-eye-development we may have

 - only-in vertebrata, from uberon:camera-type-eye
 - only-in metazoa from uberon:generic-eye

We only want to show the more specific one.

similarly never-ins should only be added if they add info on top of the MRCA of only-ins. Note that redundancy checking for never-ins is inverted

Things to decide

 - do using OWL reasoning/materialization vs graph walking
 - should this go in robot or a separate util?
 - note for robot, it would be nice if these would show up when we hav inferences in `export`s, see https://github.com/ontodev/robot/issues/697

**Comment by vanaukenk** [comment]
See also:  https://github.com/geneontology/noctua/issues/261
for reference to using this information in Noctua either solely for information purposes, or perhaps eventually to prioritize or restrict terms based on the taxon of an annotation entity.

**Comment by pgaudet** [comment]
Hi @balhoff 

just wondering where this stands ?

**Comment by balhoff** [comment]
I haven't made any progress here; I focused on the Protégé plugin first.

**Comment by pgaudet** [comment]
No problem, just wanted to check. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I think this is done @balhoff ?

**Comment by ValWood** [comment]
@balhoff ?

**Comment by balhoff** [comment]
This is not done. I can try to prioritize this in the next few weeks.

**Comment by ValWood** [comment]
OK, should I leave taxon constraint tickets until this is completed?

**Comment by pgaudet** [comment]
Thanks, I've added this to the next ontology call.

**Comment by kltm** [comment]
@pgaudet Unmoved in "PLANNING Phylogeny-based Taxon Constraints"; `In Progess` in "Ontology technical essentials". Issues should belong in one project, so removing mention in the one that's not being used.

**Comment by balhoff** [comment]
Done in #26180.
