### ISSUE TITLE
phytochelatin metabolic process/ siderophore metabolic process/regulation of pentose-phoshate shunt

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19750]
in GO
phytochelatin metabolic process (GO:0046937)

and 
siderophore metabolic process (GO:0009237) (including ferrichrome)

are is_a is a secondary metabolic process

Is that correct?
If not I can open a CHEBI ticket

also regulation of pentose-phoshate shunt (GO:0043456)
is_ secondary metabolic process  (although pentose-phoshate shunt  itself, is not)

**Comment by pgaudet** [comment]
Why not ? Those are not primary metabolites, are they ?

**Comment by ValWood** [comment]
I'm not sure. It seems odd.


scondary metabolism  is defined

GO:0019748    secondary metabolic process
Definition 
The chemical reactions and pathways resulting in many of the chemical changes of compounds that are not necessarily required for growth and maintenance of cells, and are often unique to a taxon. In multicellular organisms secondary metabolism is generally carried out in specific cell types, and may be useful for the organism as a whole. In unicellular organisms, secondary metabolism is often used for the production of antibiotics or for the utilization and acquisition of unusual nutrients.

regulation of pentose-phoshate shunt (GO:0043456), for sure does not seem to fit under here.
and phytochelatin metabolism is conserved from yeast to metazoa, so that does not really seem to fit either?

Ferrichrome seems to fit OK:
Ferrichromes are any of a group of growth-promoting Fe(III) chelates formed by various genera of microfungi.

But I guess the definition is a bit hand-wavy...

**Comment by marcfeuermann** [comment]
Hello,
The definition of secondary metabolic process is correct and I do not see how we could improve it. However, the distinction between primary and secondary metabolism is not always obvious. Siderophores are generally (not to say always) considered as secondary metabolites (even if necessary for growth for many organisms/cells). 

For regulation of pentose-phoshate shunt (GO:0043456), I agree with you Val, I would not consider it as a  secondary metabolic process. I think it is part of the pentose phosphate pathway which is essential and clearly a primary metabolism process.
Regards,
Marc.

**Comment by pgaudet** [comment]
So @ValWood is this a ChEBI issue ? Secondary metabolism is asserted in GO (and not coming from logical definitions).

**Comment by ValWood** [comment]
So it seems that only the " pentose phosphate pathway " needs to be fixed. The others are OK.

**Comment by hdrabkin** [comment]
also regulation of pentose-phoshate shunt (GO:0043456)
is_ secondary metabolic process (although pentose-phoshate shunt  <<<<<<<<, removed
