### ISSUE TITLE
GO:0016441 posttranscriptional gene silencing

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#19766]
Hi

please remove the relationship between this term GO:0016441 posttranscriptional gene silencing and  GO:0040029
regulation of gene expression, epigenetic.

post-transcriptional processes are not epigenetic processes

Thanks

Ruth

@ShirinSaverimuttu

**Comment by RLovering** [comment]
Hi Pascale
in wikipedia entry it explains that epigenetic silencing occurs at the level of DNA (see the first figure). In the https://en.wikipedia.org/wiki/Epigenetics#MicroRNAs section it states that miRs are epigentically regulated, not that they are part of epigenetic silencing. miRs can regulated gene expression at the DNA level however post transcriptional gene silencing is not a type of epigenetics
Thanks
Ruth

**Comment by pgaudet** [comment]
thanks @RLovering
