### ISSUE TITLE
NTR: migrasome

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#19760]
Term name: **migrasome**

Proposed definition: 
vesicular organelles of migrating cells. These organelles form on retraction fibres behind migrating cells

Ontology- proposed parent: 
organelle (GO:0043226)

Publications: 
PMID: 25342562
PMID: 31371827

Taxon: 
This structure was seen in mammalian cells and in zebrafish

Based on PMID: 25342562, we probably also need a new BP term:

**Migracytosis :**  a cell migration-dependent mechanism for releasing cellular contents

**Comment by pgaudet** [comment]
Hi @sabrinatoro 

How about this as a def: A vesicular organelle of that form on retraction fibers behind migrating cells and mediate the release of cytoplasmic contents during cell migration.

**Comment by sabrinatoro** [comment]
@pgaudet 

according to what I read, the migrasome would be found only in migrating cells. I don't know whether it is important to have in the definition... 
If not, then yes, the definition you are proposing works. 
Maybe without the "of" after 'organelle' though.

Thank you!

**Comment by gthayman** [comment]
And form -> forms and mediate -> mediates.

**Comment by pgaudet** [comment]
Taxon constraint = only in Vertebrates ?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140494
+name: migrasome
+namespace: cellular_component
+def: "A vesicular organelle that forms on retraction fibers behind migrating cells and mediates the release of cytoplasmic contents during cell migration." [PMID:25342562, PMID:31371827]
+is_a: GO:0043226 ! organelle
+created_by: pg
+creation_date: 2020-07-10T15:09:40Z
+
+[Term]
+id: GO:0140495
+name: migracytosis
+namespace: biological_process
+def: "A cell migration-dependent mechanism for releasing cellular contents." [PMID:25342562]
+is_a: GO:0016477 ! cell migration
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19760 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-10T15:13:46Z
+

**Comment by sabrinatoro** [comment]
Thank you @pgaudet
