### ISSUE TITLE
gorule-0000015 consider adding additional or new parent BP term to check

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#19768]
There are other BP terms besides 'GO:0044419 : interspecies interaction between organisms' for which curators add taxa to their annotations.

We could either update the BP term to check to be the parent of GO:0044419, GO:0051704 multi-organism process or we could include other BP terms in addition to GO:0044419, e.g. GO:0051707 response to other organism.

This would allow curators to include additional taxa for annotations to terms like 'defense response to gram-negative bacteria'.

@pgaudet

**Comment by pgaudet** [comment]
Will get fixed with #19769
