### ISSUE TITLE
definition issue ? GO:0051330    meiotic G1 phase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19765]
GO:0051330    meiotic G1 phase

Definition (GO:0051330 GONUTS page)
The cell cycle 'gap' phase which is the interval between the completion of DNA segregation by meiosis and the beginning of DNA synthesis.

I'm trying to parse this definition because I think it is the phase I need (I'm trying to describe something that occurs before premeiotic DNA synthesis)  However, is it correct?
How can DNA segregation by meiosis occur before DNA synthesis?

(It almost seems like this def got directly copied from the mitotic G1 phase term with "meiosis" inserted

**Comment by pgaudet** [comment]
> completion of DNA segregation by meiosis and the beginning of DNA synthesis.

It's a cycle.... 
I read this as G1 occurs between M and S.

**Comment by ValWood** [comment]
Oh I think it's oK (although meiosis isn't a cycle...)

but this term must refer to some gap between premeiotic DNA synthesis and the of homologoues chromosome segregation, and the second round of DNA synthesis.

It wasn't the term I needed but I found what I needed anyway.
