### ISSUE TITLE
NTR: gamma-tubulin complex binding

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-ontology#19788]
proposed term name: gamma-tubulin complex binding

proposed parent: _is_a_ protein-containing complex binding (GO:0044877)

proposed definition: Interacting selectively and non-covalently with a gamma-tubulin complex (GO:0000930)

Thank you!

**Comment by pgaudet** [comment]
@sabrinatoro I need a reference (I think I can find it in your email but generally, please make sure to have a reference for new terms). I am sure you knew this ;) Thanks !

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140496
+name: gamma-tubulin complex binding
+namespace: cellular_component
+def: "Interacting selectively and non-covalently with a gamma-tubulin complex." [PMID:30174135]
+is_a: GO:0044877 ! protein-containing complex binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19788 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-17T08:14:32Z

**Comment by sabrinatoro** [comment]
@pgaudet : sorry about the reference! yes, I know about it and forgot! 
thank you for retrieving it ! 
And thank you for creating the new term so quickly!
