### ISSUE TITLE
CoA pyrophosphatase activity (GO:0010945) definition

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19787]
Current def:
def: "Catalysis of the reaction: coenzyme A + H2O = 3',5'-ADP + 4'-phosphopantetheine." [GOC:tb]

As discussed in email, please modify def to include "CoA derivatives', specifically acyl-CoA.

From the original paper describing the yeast PCD1 gene (PMID: 10922370):
"a diphosphatase (pyrophosphatase) with specificity for coenzyme A and CoA derivatives...cleaving the diphosphate linkage in CoA to give 3′,5′-ADP and 4′-phosphopantetheine”

Also see PMID:16185196 - that describes the mouse Nudt19 enzyme as having “acyl-CoA disphosphatase activity”, and the tweak to the def should allow accurate annotation with GO:0010945.

@deustp01

**Comment by hdrabkin** [comment]
Thanks, @sjm41  I wanted you or @deustp01 to write the ticket so I would 't mistord anything.

**Comment by hdrabkin** [comment]
Eventually, may need to create another term specifically; one for CoA, another for acyl-CoA

**Comment by sjm41** [comment]
Hmmm, there may be additional child terms needed if we go down that route.

Was just looking at PMID: 11415433, as that has an annotation to mouse Nudt7 that currently uses "acetyl-CoA hydrolase activity" but should be GO:0010945 (or child?)

Abstract says:
A mouse homologue of the Saccharomyces cerevisiae Pcd1p coenzyme A diphosphatase, NUDT7alpha, has been expressed as a thioredoxin fusion protein in Escherichia coli. NUDT7alpha is also a CoA diphosphatase of the nudix hydrolase family, and hydrolyses CoA, CoA esters and oxidized CoA with similar efficiences, yielding 3',5'-ADP and the corresponding 4'-phosphopantetheine derivative as products.

**Comment by deustp01** [comment]
For now, maybe just broaden the dr=finition of the current term from "CoA" to "CoA and its thioesters". I think (but may be missing something) that broadening covers all the cases here, and we can wait for someone to argue that more fine-grained child terms are needed to make a useful functional distinction, before creating the fine-grained terms.

**Comment by hdrabkin** [comment]
Right, just broaded the def. currently in the push request stage

**Comment by sjm41** [comment]
For the record, there's also data for the worm ortholog:
https://pubmed.ncbi.nlm.nih.gov/11943069/
The Y87G2A.14 Nudix hydrolase gene product of Caenorhabditis elegans has been expressed as a thioredoxin fusion protein in Escherichia coli and shown to be a CoA diphosphatase with catalytic activity towards CoA and its derivatives. The products of CoA hydrolysis were 3',5'-ADP and 4'-phosphopantetheine with Km and kcat values of 220 microM and 13.8 s(-1) respectively. CoA esters yielded 3',5'-ADP and the corresponding acyl-phosphopantetheine.

**Comment by hdrabkin** [comment]
done. I'll close for now.

**Comment by sjm41** [comment]
Thanks Harold.
