### ISSUE TITLE
Tidying nucleoside-diphosphatase activity (GO:0017110) and children 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19786]
Suggestions as follows:

==

**GO:0017110	nucleoside-diphosphatase activity (EC:3.6.1.6, RHEA 36799)
Catalysis of the reaction: a nucleoside diphosphate + H2O = a nucleotide + phosphate.**
- remove "IDPase" synonym (that's for GO:1990003)      CHECK

==

**GO:0045134    uridine-diphosphatase activity
Catalysis of the reaction: UDP + H2O = UMP + phosphate.**
- remove EC:3.6.1.6 (this is for parent)
- (can't find specific EC or RHEA xref to add) >>>>>requesting

==

**GO:0036384    cytidine diphosphatase activity
Catalysis of the reaction: CDP + H2O = CMP + phosphate.**
- add hyphen (to be consistent with parent/sister terms) CHECK
- (can't find EC or RHEA xref to add)  requesting RHEA

==

**GO:0043262    adenosine-diphosphatase activity
Catalysis of the reaction: ADP + H2O = AMP + phosphate.**
- change current RHEA 20988 to 61436??  CHECK.
- (can't find EC)

==

**GO:0004787    thiamine-pyrophosphatase activity
Catalysis of the reaction: TDP + H2O = TMP + phosphate.**
- change name to "thiamine-diphosphatase activity" (to be consistent with sister terms) CHECK
- remove parital EC:3.6.1 (no full EC available)   REQuesting RHEA
- (can't find RHEA)

==

**GO:0004382    guanosine-diphosphatase activity (EC:3.6.1.42, RHEA 22156)
Catalysis of the reaction: GDP + H2O = GMP + phosphate.**
- all OK

==

**GO:0044715    8-oxo-dGDP phosphatase activity
Catalysis of the reaction 8-oxo-dGDP + H2O = 8-oxo-dGMP + phosphate.**
- add EC 3.6.1.58   CHECK
- add RHEA:32063   cHECK

==

**GO:0044716    8-oxo-GDP phosphatase activity
Catalysis of the reaction 8-oxo-GDP + H2O = 8-oxo-GMP + phosphate.**
- add EC 3.6.1.58  CHECK
- add RHEA:62356 CHECK

==

**GO:1990003    IDP phosphatase activity
Catalysis of the reaction: IDP + H2O = IMP + phosphate.**
- change name to "inosine-diphosphatase activity" (to be consistent with sister terms)
- add EC 3.6.1.64  CHECK and RHEA:35207

==

**GO:0044717    8-hydroxy-dADP phosphatase activity
Catalysis of the reaction8-hydroxy-dADP + H2O = 8-hydroxy-dAMP + phosphate.**
- typo in def - add ": " in "reaction8" bit of definition  CHECK

**Comment by hdrabkin** [comment]
I can request RHEAs for the specifics (UMP, etc.

**Comment by hdrabkin** [comment]
RHEA request ticket 190887
GO:0045134 uridine-diphosphatase activity
UDP + H2O = UMP + phosphate.
PMID:15102851

GO:0036384 cytidine diphosphatase activity
CDP + H2O = CMP + phosphate.
PMID:12686557	

GO:0004787 thiamine-pyrophosphatase activity
TDP + H2O = TMP + phosphate.
PMID:15292217

**Comment by alanbridge** [comment]
Hi Harold 

For RHEA request ticket 190887

Anne is gonna check these but they should be 

Rhea:64876 - UDP + H2O = UMP + phosphate
Rhea:64880 - CDP + H2O = CMP + phosphate
Rhea:64884 - TDP + H2O = TMP + phosphate

All the best, Alan

**Comment by hdrabkin** [comment]
@alanbridge ; even better for me if they are in; but searching on the numbers gives nothing back, so they might be newer than the current release.

**Comment by alanbridge** [comment]
Hi Harold, 

sorry I wasn't clear, I just created these and am waiting for Anne to give them the once over - they should be in the next Rhea release. 

All the best, Alan

**Comment by hdrabkin** [comment]
AH! Perfect!

**Comment by hdrabkin** [comment]
Comments from @amorgat 
* RHEA:64876 H2O + UDP = H+ + phosphate + UMP
RHEA:64876 is-a RHEA:36799 (EC 2.6.1.6)
* RHEA:64880 CDP + H2O = CMP + H+ + phosphate
RHEA:64880 is-a RHEA:36799 (EC 2.6.1.6)
I failed to identify the evidence of the reaction with CDP in PMID:12686557
(I'm certainly blind...). Please would you help me to find where its is? For
the moment, I'm using PMID: 11041856 (http://europepmc.org/abstract/MED/11041856)
* The last reaction (PMID:15292217) was already curated in Rhea, it is
RHEA:27998
RHEA:27998 H2O + thiamine diphosphate = H+ + phosphate + thiamine phosphate
RHEA:27998 is not related to RHEA:36799 (EC 2.6.1.6)

**Comment by amorgat** [comment]
Precision: 

According to IUBMB description for EC 2.6.1.6 (https://www.enzyme-database.org/query.php?ec=3.6.1.6)
I linked the following reactions to EC 2.6.1.6 (unofficial reactions)
RHEA:61436 ADP + H2O = AMP + H+ + phosphate
RHEA:64880 CDP + H2O = CMP + H+ + phosphate
RHEA:22156 GDP + H2O = GMP + H+ + phosphate
RHEA:35207 H2O + IDP = H+ + IMP + phosphate
RHEA:64876 H2O + UDP = H+ + phosphate + UMP
RHEA:27998 H2O + thiamine diphosphate = H+ + phosphate + thiamine phosphate 

--> RHEA:27998 is linked to EC 2.6.1.6 even it is not a child reaction of RHEA:36799

**Comment by alanbridge** [comment]
Hi Anne

EC 2.6.1.6 is: a nucleoside diphosphate + H2O = a nucleoside phosphate + phosphate

has been linked to

RHEA:27998 H2O + thiamine diphosphate = H+ + phosphate + thiamine phosphate

but thiamine isn't a nucleoside - doesn't that rule out this reaction? this looks like an error by IUBMB to me. Perhaps a misnomer in the entry? 

All the best, Alan

**Comment by amorgat** [comment]
You're right, I have been to quick to add the link to RHEA:27998 based on IUBMB enzyme names only - I need to read **all** the publications provided for this entry and discuss with @kaxelsen !

**Comment by alanbridge** [comment]
thanks Anne would be good to follow up with IUBMB - in the meantime may be evidence for the reactions involving thymidine phosphates in https://pubmed.ncbi.nlm.nih.gov/7160478/ if you can access that - Figure 1 and 2 measure TMP from TTP (where T=Thymidine)  so we probably could have 

TTP -> TDP
TDP -> TMP
TTP -> TMP

**Comment by alanbridge** [comment]
Harold, could you remove the xref to Rhea:64884 while we sort this out? The ID of this reaction (TDP -> TMP) will change as in the meantime it's been assigned to another curated reaction. Sorry for the hassle.

**Comment by hdrabkin** [comment]
@alanbridge, not a problem. I didn't add any of the RHEAs yet once I saw there was going to be problems with the assignments.

**Comment by hdrabkin** [comment]
Note: TPP is used as an abbreviation for THIAMINE diphosphate (CHEBI) ; not TDP, which is thymidine diphosphate. WIll change in GO:0004787 thiamine-pyrophosphatase activity, 
Catalysis of the reaction: TPP + H2O = TMP + phosphate. and add correct RHEA and remove EC:3.6.1.6
The GO term is used in three annotations for thiamine based reactions, not thymidine.
change parentage from nucleoside diphosphatsae activity to pyrophosphatase activity.

**Comment by hdrabkin** [comment]
one additional addition of an xref for UDP and closing.

**Comment by sjm41** [comment]
Thanks for fixing all these various bits Harold!
