### ISSUE TITLE
Issue:GO:0043913 chromosome segregation-directing complex

### ISSUE THREAD

**Issue by sandraorchard** [geneontology/go-ontology#19794]
MreB, MreC and MreD accepted as being part of the larger Elongasome/Rod complex which mediates the process of cell elongation and the maintenance of rod-shaped cell morphology (PMID: 31915748 and www.biorxiv.org/content/biorxiv/early/2019/09/16/769984.full.pdf). The chromosome segregation activity has not been mentioned for years, and is the result of one KO. Can this either be updated, or deleted and replaced.

**Comment by pgaudet** [comment]
Should I obsolete the term ? As far as I can tell those 3 proteins are not part of the same complex, see also https://pubmed.ncbi.nlm.nih.gov/15612918/

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0043913 chromosome segregation-directing complex'. The reason for obsoletion is that the three proteins mentioned in the definition are not part of the same complex. 

There are no annotations and no mappings to this term. This term is not present in any subsets. 

You can comment in the ticket: https://github.com/geneontology/go-ontology/issues/19794


Thanks, Pascale
