### ISSUE TITLE
(E)-caffeate:CoA ligase activity

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#19795]
Hi GO,

I would need a GO term for (E)-caffeate:CoA ligase activity (which catalyzes the formation of CoA esters of caffeic acid)

Thanks

Emmanuel

Term: Caffeate-CoA ligase activity
Definition:
Catalysis of the reaction:
(E)-caffeate + ATP + CoA = (E)-caffeoyl-CoA + AMP + diphosphate;

probably child of 
GO:0016405 CoA-ligase activity
GO:0016878 acid-thiol ligase activity

Xref:
RHEA:36299
EC:6.2.1.-

PMID:22649270;

**Comment by hdrabkin** [comment]
+id: GO:0106286
+name: (E)-caffeate-CoA ligase activity
