### ISSUE TITLE
Trans-ferulate:CoA ligase activity

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#19796]
Hi GO,

I would need a GO term for Trans-ferulate:CoA ligase activity (which catalyzes the formation of CoA esters of ferulic acid)

Thanks

Emmanuel

Term: Ferulate-CoA ligase activity
Definition:
Catalysis of the reaction:
ATP + CoA + trans-ferulate = (E)-feruloyl-CoA + ADP + phosphate;

probably child of 
GO:0016405 CoA-ligase activity
GO:0016878 acid-thiol ligase activity

Probably associated with:
GO:0033494 ferulate metabolic process

Xref:
RHEA:19389
EC:6.2.1.34

PMID:22649270;

**Comment by hdrabkin** [comment]
+id: GO:0106287
+name: ferulate-CoA ligase activity
done
