### ISSUE TITLE
Missing parent "GO:0140423    JSON effector-mediated suppression of pattern-triggered immunity'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19807]
I'm back on PHI base today.

This term:
GO:0140423   effector-mediated suppression of pattern-triggered immunity
still doesn't seem to be a descendant of

 GO:0140404   effector-mediated modulation of host innate immune response by symbiont

I'm sure we keep adding this?

**Comment by ValWood** [comment]
<img width="341" alt="Screen Shot 2020-07-20 at 14 22 09" src="https://user-images.githubusercontent.com/7359272/87943105-7760ec80-ca95-11ea-9067-80b5f6a48516.png">

**Comment by pgaudet** [comment]
Hi, 

I added the missing parent to the parent 
GO:0140403 effector-mediated suppression of host innate immune response by symbiont

Thanks, Pascale
