### ISSUE TITLE
obsolete GO:1990492    mitotic cell cycle checkpoint inhibiting CAR assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19808]
GO:1990492    mitotic cell cycle checkpoint inhibiting CAR assembly

single PomBase EXP annotation

(this is not a separate checkpoint)

**Comment by pgaudet** [comment]
Obsoletion notice sent July 27, 2020 

Dear all,

The proposal has been made to obsolete 'GO:1990492 mitotic cell cycle checkpoint inhibiting CAR assembly'. The reason for obsoletion is that it's not a specific process. There is a single annotation to this term (PomBase). There are no mappings to this term; this term is not present in any subsets.

You can comment on the ticket here: geneontology/go-ontology#19808

Thanks, Pascale
