### ISSUE TITLE
negative regulation of GO:0072480

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19818]
GO:0072480 | signal transduction involved in mitotic spindle assembly checkpoint
(or now mitotic spindle assembly checkpoint signalling)

for

PMID:28017606

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140499
+name: negative regulation of mitotic spindle assembly checkpoint signaling
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of negative regulation of mitotic spindle assembly checkpoint signaling." [PMID:28017606]
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0072480 ! mitotic spindle assembly checkpoint signaling
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19818 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-22T15:44:06Z
