### ISSUE TITLE
GO:0004303 estradiol 17-beta-dehydrogenase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#19811]
Dear GO curators,

Could you please consider updating the cofactor in the reaction that defines GO:0004303 estradiol 17-beta-dehydrogenase activity?

17β-estradiol 17-dehydrogenase EC=1.1.1.62
Reaction: 17-beta-estradiol + NAD(P)(+) <=> estrone + NAD(P)H
 https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=1.1.1.62 

mapped to
 
[RHEA:24612] 17beta-estradiol + NAD(+) = estrone + H(+) + NADH
[RHEA:24616] 17beta-estradiol + NADP(+) = estrone + H(+) + NADPH

Many thanks for your help,

Nevila Hyka-Nouspikel

**Comment by nnouspikel** [comment]
Hello,

Another possibility would be to have specific GO terms for  (NAD+) and  (NADP+) activities

New GO:
17β-estradiol 17-dehydrogenase (NAD+) activity 
mapped to 
[RHEA:24612] 17beta-estradiol + NAD(+) = estrone + H(+) + NADH

Thanks!

**Comment by hdrabkin** [comment]
Based on the RHEAs, the two terms already exist. will  make GO:0004303 a parent. The defs will become the RHEA defs once we push the RHEA as source of def.
