### ISSUE TITLE
new terms for Mannan polymerase complexes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19817]
Descendants of 
ID | GO:0000136
Term name | alpha-1,6-mannosyltransferase complex
Definition | A large, multiprotein complex with alpha-(1->6)-mannosyltransferase activity, located in the cis Golgi membrane; adds mannan to N-linked glycans on proteins.

To the existing term GO:0000136
1. Add exact  synonym Mannan polymerase complex
2. Remove 'large' that is relative, and 'multiprotein' that's a given

NTR: Mannan polymerase II complex
synonym : M-Pol II complex
Ref PMID: 9430634
A complex with alpha-(1->6)-mannosyltransferase activity, located in the cis Golgi membrane; adds mannan to N-linked glycans on proteins as part of the elongation of alpha 1,6-linked Man backbone. Comprises Mnn9p, Anp1p, Mnn10p, Mnn11p Hoc1p in S. cerevisiae, or orthologs in other species {change to standard wording for this part}

NTR:  Mannan polymerase I complex
synonym : M-Pol I complex
Ref PMID: 9430634
A complex with alpha-(1->6)-mannosyltransferase activity, located in the cis Golgi membrane; adds mannan to N-linked glycans on proteins as part of the priming and elongation of alpha 1,6-linked Man backbone. Comprises Mnn9p Van1p or orthologs in other species {change to standard wording for this part}

I'm using an old review for the descriptions, but annotating  PMID:32650974

**Comment by ValWood** [comment]
looking at the siblings of GO:0000136
Mannan polymerase complex
might be a better primary name

**Comment by ValWood** [comment]
@bmeldal  could you sanity check this?

**Comment by bmeldal** [comment]
Just one question: both complexes have the same function, GO:0000009 alpha-1,6-mannosyltransferase activity. The only difference is that only M-Pol I initiates the reaction by adding the first mannan while Man Pol II can only make a long polyglycan chain once the first mannan is linked to the protein. Technically, it's "simply" a different substrate (apo-protein vs mannosylated protein) and we don't tend to make different terms for each substrate. It's one of those grey zones!

**Comment by deustp01** [comment]
For other polymerization reactions, there's often a distinction between the activity that initiates polymer formation and the activity that extends the nascent structure. Would that be useful / relevant here?

**Comment by ValWood** [comment]
>. we don't tend to make different terms for each substrate

Don't we?

We have many  complexes where the activity is the same but the composition is different (all of the DNA helicases, Ubiquitin ligases etc. etc). These are 2 independent complexes (sharing one subunit), but operating  at different points in a sequential pathway (i.e they don't add the same mannose, in fact it seems the role of the II complex is not so clear, it probably has additional activities- we don't know yet).

**Comment by bmeldal** [comment]
> For other polymerization reactions, there's often a distinction between the activity that initiates polymer formation and the activity that extends the nascent structure. Would that be useful / relevant here?

Sounds like there's president for this!

> We have many complexes where the activity is the same but the composition is different (all of the DNA helicases, Ubiquitin ligases etc. etc). 

We used to, but it became really unwieldy so I was asked to stick to functional delineations rather than making child terms only based on composition. I've actually asked for some of these to be removed ;-)

Imagine I'd requested a term for each of the 31 different mammalian BAF complex variants I curated! I think we have a handful of terms, based on tissue-specificity and developmental stages.

> These are 2 independent complexes (sharing one subunit), but operating at different points in a sequential pathway (i.e they don't add the same mannose, in fact it seems the role of the II complex is not so clear, it probably has additional activities- we don't know yet).

Better argument than above and in line with what @deustp01 said.

Sounds like 2 child terms are justified in this case!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140497
+name: mannan polymerase II complex
+namespace: cellular_component
+def: "A complex with alpha-(1->6)-mannosyltransferase activity, located in the cis Golgi membrane; adds mannan to N-linked glycans on proteins as part of the elongation of alpha 1,6-linked Man backbone. In S. cerevisiae, contains Mnn9p, Anp1p, Mnn10p, Mnn11p, and Hoc1p." [PMID:9430634]
+is_a: GO:0000136 ! mannan polymerase complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19817 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-22T14:33:57Z
+
+[Term]
+id: GO:0140498
+name: mannan polymerase I complex
+namespace: cellular_component
+def: "A complex with alpha-(1->6)-mannosyltransferase activity, located in the cis Golgi membrane; adds mannan to N-linked glycans on proteins as part of the priming and elongation of alpha 1,6-linked Man backbone. In S. cerevisiae, contains Mnn9p and Van1p." [PMID:9430634]
+is_a: GO:0000136 ! mannan polymerase complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19817 xsd:anyURI
+created_by: pg
+creation_date: 2020-07-22T14:34:23Z
