### ISSUE TITLE
RuBisCO assembly, alter existing term GO:0110102 definition

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#19828]
Hello,

There is a term for the assembly of chloroplast RuBisCO (GO:0110102), but I can't use it as I am annotating cyanobacterial RuBisCO. Therefore I would either like to have non-organism specific term for its assembly, or a more economical solution, remove mention of chloroplasts from GO:0110102 and then it can be used for RuBisCO from any organism please. The latter makes more sense to me; there are other plastid types that have RuBisCO (cyanelles and organellar chromatophores, but I don't see the point of making organelle-specific assembly terms for them), and other non-cyanobacteria have RuBisCO too (although they may not need assembly factors). GO:0110102 does not have any child terms, so they are not a problem.

So I suggest altering the definition to: "The aggregation, arrangement and bonding together of a set of components to form a ribulose bisphosphate carboxylase complex.". PMID 29589905 reviews both plastid (chloroplast) and cyanobacterial RuBisCO assembly.

Thanks,   Andrea

**Comment by krchristie** [comment]
Hi @AndreaAuchincloss 

This makes sense to me. @ukemi & @cmungall - Do you have any objection to changing the existing term for `chloroplast ribulose bisphosphate carboxylase complex assembly` to a general term for assembly of any `ribulose bisphosphate carboxylase complex`. RuBisCo and its assembly pathway seem to be highly conserved, so while having multiple complex terms allows us to specify the different locations of Rubisco in plants versus cyanobacteria, it looks to me like the assembly pathway is fairly similar, so it makes sense to me to just have one assembly term. @AndreaAuchincloss - please chime in if I misunderstood anything in my brief reading of the review you mentioned (PMID 29589905).

-- ribulose bisphosphate carboxylase complex
--- chloroplast ribulose bisphosphate carboxylase complex
--- chromatophore ribulose bisphosphate carboxylase complex
---- plasma membrane-derived thylakoid ribulose bisphosphate carboxylase complex

**Comment by ukemi** [comment]
No objection here.
