### ISSUE TITLE
bile acid 7-alpha/7-beta-dehydrogenase (NAD+) activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#19825]
Dear GO curators,

Could you please consider creating these new terms:

- chenodeoxycholate 7-alpha-dehydrogenase (NAD+) activity
  [Rhea:42036] 
  chenodeoxycholate + NAD(+) = 7-oxolithocholate + H(+) + NADH

- isoursodeoxycholate 7-beta-dehydrogenase (NAD+) activity 
  [Rhea:42024] 
   3beta,7beta-dihydroxy-5beta-cholan-24-oate + NAD(+) = 3beta-hydroxy-7-oxo-5beta- 
  cholan-24-oate + H(+) + NADH 

- ursodeoxycholate 7-beta-dehydrogenase (NAD+) activity 
  [RHEA:42028] 
  NAD(+) + ursodeoxycholate = 7-oxolithocholate + H(+) + NADH

  as children of GO:0033764;  reference: PMID:12917011

 
 Thank you very much for your help.

 Nevila Hyka-Nouspikel

**Comment by hdrabkin** [comment]
+id: GO:0106281
+name: chenodeoxycholate 7-alpha-dehydrogenase (NAD+) activity

+id: GO:0106282
+name: isoursodeoxycholate 7-beta-dehydrogenase (NAD+) activity

+id: GO:0106283
+name: ursodeoxycholate 7-beta-dehydrogenase (NAD+) activity

done

**Comment by nnouspikel** [comment]
Thank you so much Harold. All the best.
