### ISSUE TITLE
NTR:acquisition of seed longevity

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#19829]
GO:new acquisition of seed longevity
part of  GO:0048316 (seed development)

Definition: "The acquisition of seed longevity is the ordered series of events during seed development, that prevent embryo deterioration and ROS damage and thus contribute to  seed viability over time or in response to adverse environmental conditions. These events include protective (e.g. production of glassy cytoplasm ) and repair (e.g. oxidative stress responses) processes."

Reference: PMID:26637538

**Comment by ukemi** [comment]
is_a response to stress?

"The acquisition of seed longevity is the response to stress during seed development, that prevents embryo deterioration and ROS damage and thus contributes to seed viability over time. These events include protective (e.g. production of glassy cytoplasm ) and repair (e.g. oxidative stress responses) processes."

**Comment by ukemi** [comment]
or is_a developmental process?

"The developmental process occurring during seed development that prevents embryo deterioration and ROS damage and thus contributes to seed viability over time. These events include protective (e.g. production of glassy cytoplasm ) and repair (e.g. oxidative stress responses) processes."

**Comment by lreiser** [comment]
I think it has elements of both. Part of the process occurs as the seed is forming. Others act during seed germination . If I understand correctly the repair occurs during germination  - that is maybe where it gets tichy for me.

**Comment by ukemi** [comment]
On the editors' call we were not opposed to having this term, but ideally we would like to see the children to which the generic terms refers. It would be nice to see a GO-CAM model made for this process.
We though the most appropriate parent would be developmental process.

**Comment by lreiser** [comment]
I agree with the call about developmental process. l

**Comment by ValWood** [comment]
To me "acquisition of seed longevity" sounded a bit like the desired outcome of the processes (or a trait?), rather than a process in itself.
Presumably when things go wrong with "repair" or "ROS " production"   seed longevity is improved or impaired.

**Comment by ukemi** [comment]
Will wait for @pgaudet 's input then.

**Comment by tberardini** [comment]
@pgaudet Thoughts on how to proceed here?  Thank you!

**Comment by tberardini** [comment]
Thanks, Pascale!

**Comment by tberardini** [comment]
Hmm,

id: GO:0140547
name: acquisition of seed longevity
namespace: biological_process
def: "The acquisition of seed longevity is the ordered series of events during seed development, that prevent embryo deterioration and ROS damage and thus contribute to seed viability over time or in response to adverse environmental conditions. These events include protective (e.g. production of glassy cytoplasm ) and repair (e.g. oxidative stress responses) processes." [PMID:26637538]
**is_a: GO:0009791 ! post-embryonic development**

What do you think about adding the originally requested 

**part of GO:0048316 seed development**

?

**Comment by pgaudet** [comment]
and is_a response to stress ? 

I made it a sibling if seed development (ie under GO:0009791 ! post-embryonic development) - is that OK ?

**Comment by tberardini** [comment]
@lreiser  What do you think about the current parentage?  The sibling status to seed development means that annotations to this term will not be pulled when looking at 'seed development'.

**Comment by lreiser** [comment]
Hm that doesn't seem right- the definition of post embryonic development: The process whose specific outcome is the progression of the organism over time, from the completion of embryonic development to the mature structure. See embryonic development. 

The developmental processes that occur here happen during seed development which includes the formation of the embryo, seed coat, endosperm.

To me it makes sense to be a  direct child (part of ) GO:0048316 seed development

**Comment by pgaudet** [comment]
> To me it makes sense to be a direct child (part of ) GO:0048316 seed development

This is already the case. What should be the is_a parent, if not GO:0009791 ! post-embryonic development ?

**Comment by lreiser** [comment]
How about GO:0032501 multicelluar organismal process

**Comment by tberardini** [comment]
Thank you, @pgaudet.
