### ISSUE TITLE
NTR: protein dissociation  activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19838]
I would like to add molecular functions to Nse3 and Nse1 the "KITE" module in this figure

<img width="456" alt="2020-07-27-32546830-nse4" src="https://user-images.githubusercontent.com/7359272/88700155-348bbe00-d100-11ea-92f2-bc8ecb3e7ffb.png">

I have annotated the Kleisin gate (Nse4) to protein adaptor activity with inputs SMC5 and SMC6

The 'kleisin gate' is opened when  Nse1 /3 are bound simultaneously to Smc5-Smc6-Nse4 with ATP.

Satisfyingly, this  the same  term I requested for  cohesin regulators pds5 and Wapl (cohesin dissociators/unloaders)
https://github.com/geneontology/go-ontology/issues/12623

At the time I wasn't able to articulate a mechanism, but I  can't see how much more detail we can get. It's basically changing the binding affinity. 
https://www.nature.com/articles/s41598-020-66647-w

Or if anyone can think of any other way to describe this activity......

The new term would probably need to be under the root node? or molecular function regulator?

NTR: protein dissociation  activity
exact protein binding inhibitor
A molecular function that directly inhibits the non-covalent interaction between two gene products, or complexes.
PMID: 32546830

**Comment by pgaudet** [comment]
@thomaspd 
> In GO-CAM, this would be represented as the binding activity of Nse4 directly negatively regulates the binding of the other partners 

Paul will comment more later.

**Comment by ValWood** [comment]
Specifically, I'd like to know what the annotation would be that I could display as a molecular function on a gene page.

**Comment by pgaudet** [comment]
Something like : 

{KITE _enables_ protein binding _has input_ Nse1 }  -> _directly negatively regulates_ {Nse1 enables protein-containing complex binding _has input_ SMC5|SMC6}


Does that makes sense ?

**Comment by ValWood** [comment]
No this doesn't work. So,

- KITE is Nse1 and Nse2
- Nse1,2,4 and SMC5,6  are all part of the SMC5/6 complex so I don't think it makes sense to say they enable  "protein-complex binding" since this is only for use with non-complex subunits.
- All subunits are constitutively part of the complex whether the Kelisin 'gate' (Nse4)  is  open or closed. I want to capture the activity of "opening the gate"
- I  can't use "protein binding' to describe the activity of nse1 and nse3 (they are bound to each other, and to Nse4, and I have curated these  interactions - but they don't capture the fact that the activity of
 the Kite proteins is to enable the dissociation of  Nse4 (the gate)  from Smc5&6:
- Crucially- it is not possible to capture this with binding combinations because Nse1&2  are not themselves  the partners in the binding that they dissociating. So I have no molecular function to assign to Nse1 or 2 that is related to this specific activity (I would need to use  the root node).

**Comment by pgaudet** [comment]
@thomaspd thoughts ?

**Comment by ValWood** [comment]
We can close this for now because I'm not sure this particular model is set in stone. I have come across other cases where I wanted to represent the "inhibition of dissociation", but it might become clearer later how to express this. It's one of the few things I can't represent as an activity.

**Comment by pgaudet** [comment]
Hi, 

On the GO tickets jamboree, we are discussing ATPases https://github.com/geneontology/go-ontology/issues/20876
and we are trying to group ATPases under a 'main' function parent. We came across 'GO:1990833 clathrin-uncoating ATPase activity', for which we cannot find a non-ATPase parent. Looking at the literature, for eg PMID:28579939, PMID:28579939, we proposed to create a new term, 'protein dissociation chaperone activity', and move 'GO:1990833 clathrin-uncoating ATPase activity' and 'GO:0140545 protein disaggregase activity' under that new term. 

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
That sounds good. They are related to Hsps.

**Comment by ValWood** [comment]
correction "related hsps"

**Comment by ValWood** [comment]
Ah, I did not realise I was commenting on this ticket. In this instance  "Kite" isn't an ATPase.
I think we should ignore this one for now. There might eventually be a simpler way to curate using mofified/unmodified forms - I'll continue to think about that.

But the grouping term for the hsp dissociation seems fine.
