### ISSUE TITLE
remove EC xref on GO:0008236

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19834]
Hi @hdrabkin ,

Can you remove this partial EC xef:

id: GO:0008236
name: serine-type peptidase activity
def: "Catalysis of the hydrolysis of peptide bonds in a polypeptide chain by a catalytic mechanism that involves a catalytic triad consisting of a serine nucleophile that is activated by a proton relay involving an acidic residue (e.g. aspartate or glutamate) and a basic residue (usually histidine)." [http://merops.sanger.ac.uk/about/glossary.htm#CATTYPE, ISBN:0716720094]
xref: EC:3

**Comment by hdrabkin** [comment]
I might be going blind; I can't find any EC exref  for GO:0008236

**Comment by hdrabkin** [comment]
Will close this now.

**Comment by sjm41** [comment]
Hmmm...
I'm seeing this in the download of the go-basic.obo file, with header "data-version: releases/2020-07-16".

Here's the full entry I see (EC xref in bold):

[Term]
id: GO:0008236
name: serine-type peptidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of peptide bonds in a polypeptide chain by a catalytic mechanism that involves a catalytic triad consisting of a serine nucleophile that is activated by a proton relay involving an acidic residue (e.g. aspartate or glutamate) and a basic residue (usually histidine)." [http://merops.sanger.ac.uk/about/glossary.htm#CATTYPE, ISBN:0716720094]
synonym: "serine protease activity" NARROW []
**xref: EC:3**
xref: Reactome:R-HSA-1461993 "pro-HD5 is cleaved by trypsin"
xref: Reactome:R-HSA-2022383 "Chymase hydrolyzes Angiotensin-(1-10) to Angiotensin-(1-8)"
xref: Reactome:R-HSA-3132753 "Pancreatic proteases degrade TCN1:Cbl"
xref: Reactome:R-HSA-6801766 "Trypsin cleaves REG3A or REG3G to generate REG3A,G(38-175)"
is_a: GO:0008233 ! peptidase activity
is_a: GO:0017171 ! serine hydrolase activity


Could this be a glitch just in the file I'm looking at??

I'm going to re-open....

**Comment by hdrabkin** [comment]
I have attached screenshot of the current working version I just downloaded. There is no xref:EC:3
![Screen Shot 2020-07-29 at 9 04 29 AM](https://user-images.githubusercontent.com/10440080/88803696-de0f9580-d17a-11ea-80e7-cec68427d1bc.jpg)

**Comment by mah11** [comment]
FWIW, I don't think either of you is going mad -- I also see the "xref: EC:3" line in go-basic.obo but not in go-edit.obo. Maybe that means a pipeline anomaly?

**Comment by sjm41** [comment]
Weird - I guess it was added very recently and then deleted even more recently, meaning I see it in the latest obo file, but you don't see it in your current working version?

I do see it on the QuickGO page here: https://www.ebi.ac.uk/QuickGO/term/GO:0008236

And the change log says it was added on 2020-07-19 (10 days ago).

But as long as it's really gone from the current working version, then I guess all is well!

**Comment by hdrabkin** [comment]
However, I just downloaded the snapshot go-basic.obo for 7/23 and I see it. 
However here is the editor's obo file stanza
[Term]
id: GO:0008236
name: serine-type peptidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of peptide bonds in a polypeptide chain by a catalytic mechanism that involves a catalytic triad consisting of a serine nucleophile that is activated by a proton relay involving an acidic residue (e.g. aspartate or glutamate) and a basic residue (usually histidine)." [http://merops.sanger.ac.uk/about/glossary.htm#CATTYPE, ISBN:0716720094]
synonym: "serine protease activity" NARROW []
is_a: GO:0008233 ! peptidase activity
is_a: GO:0017171 ! serine hydrolase activity

Not shure how this  added for this term but it IS a grouping term, but EC:3 seems too broad . I was out from 7/17 until this past Monday.  I'll ask around

**Comment by hdrabkin** [comment]
Sorry @mah11 , I was imputing the comment and didn't see  your comment. I'm going to ping Jim

**Comment by pgaudet** [comment]
From ontology call: this comes from an obsolete term. @balhoff is removing it.

**Comment by hdrabkin** [comment]
fixed.

**Comment by sjm41** [comment]
Thanks all! Glad this (small) issue is finally fixed!
