### ISSUE TITLE
NTR: regulation of premeiotic DNA replication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19835]
descendant of
GO:0006279 | premeiotic DNA replication

PMID:15805471

**Comment by krchristie** [comment]
Hi @ValWood, 

Since the paper you cite, PMID:15805471, says this:

> Diploid Δcsn1/Δcsn1 cells still responded to the meiotic conditions by accumulating in G1, but little or no **_entry_** into premeiotic DNA synthesis was apparent during the course of the experiment

I wanted to check if the existing term `initiation of premeiotic DNA replication` might be appropriate before I create a new term.

thanks,

-Karen

**Comment by ValWood** [comment]
Yes,  thanks,  closing.
