### ISSUE TITLE
NTR: effector-mediated supression of host host salicylic acid-mediated signal transduction pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19848]
NTR: effector-mediated suppression of host salicylic acid-mediated host innate immune signalling.

A process mediated by a molecule secreted by a symbiont that results in the suppression of host salicylic acid-mediated host innate immune signalling. 

descendant of
GO:0052003 suppression by symbiont of defense-related host salicylic acid-mediated signal transduction pathway
and
GO:0140404 | effector-mediated modulation of host innate immune response by symbiont

I suspect this will always be "effector-mediatedf' so we might be able to make GO:0052003 more specific

**Comment by ValWood** [comment]
PMID:30651637

and
PMID: 25438793
Kumar, D. Salicylic acid signaling in disease resistance. Plant Sci. 228, 127–134 (2014).

**Comment by ValWood** [comment]
Note that these  symbiont terms have parentage to the equivalent  host terms

**Comment by pgaudet** [comment]
Can I removed one instance of 'host'? 

effector-mediated suppression of host salicylic acid-mediated ~host~ innate immune signalling. ? 
(same in definition)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140502
+name: effector-mediated suppression of host salicylic acid-mediated innate immune signalling
+namespace: biological_process
+def: "A process mediated by a molecule secreted by a symbiont that results in the suppression of host salicylic acid-mediated innate immune signalling." [PMID:25438793, PMID:30651637]
+is_a: GO:0052003 ! suppression by symbiont of defense-related host salicylic acid-mediated signal transduction pathway
+is_a: GO:0140404 ! effector-mediated modulation of host innate immune response by symbiont
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19848 xsd:anyURI
+created_by: pg
+creation_date: 2020-08-11T06:16:36Z
