### ISSUE TITLE
defense response signaling pathway, resistance gene-dependent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19850]
here
https://github.com/geneontology/go-ontology/issues/18587

 GO:0010204 defense response signaling pathway, resistance gene-independent
merged into
into GO:0002758 innate immune response-activating signal transduction

but we did not deal with
defense response signaling pathway, resistance gene-dependent

the notes in my curation session say
"THIS TERM WILL BE RENAMED TO "effector-triggered immunity signalling"

but I can't find an open ticket for that.

**Comment by pgaudet** [comment]
You had asked for a synonym here #18586 

I guess this is not what you wanted ?

**Comment by ValWood** [comment]
I think that discussion predated a subsequent discussion with TAIR.
It was agreed that the  resistance-gene dependence and independence are  orthogonal observations
(more about the pathogen host phenotype, but not a particular process).

**Comment by pgaudet** [comment]
Discussing with @ValWood - I will merge GO:0002758 innate immune response-activating signal transduction
into GO:0009870 defense response signaling pathway, resistance gene-dependent

Thanks, Pascale

**Comment by pgaudet** [comment]
I will merge GO:0009870 defense response signaling pathway, resistance gene-dependent  
into GO:0002758 innate immune response-activating signal transduction


(same as 'resistance gene-independent' )

Thanks, Pascale

**Comment by pgaudet** [comment]
I also need to remove the taxon restriction on GO:0002758 innate immune response-activating signal transduction -> only in Viriplantea. This is now wrong: children of the merged term include 
'innate immune response activating cell surface receptor signaling pathway'
'cell surface pattern recognition receptor signaling pathway'
'stimulatory C-type lectin receptor signaling pathway'
'stimulatory killer cell immunoglobulin-like receptor signaling pathway'

Pascale
