### ISSUE TITLE
Obsolete:PMA-inducible membrane protein ectodomain proteolysis?

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19855]
Came across this term that seems to describe an experimental condiition rather than a GO BP:

PMA-inducible membrane protein ectodomain proteolysis GO:0051088

'The proteolytic cleavage of transmembrane proteins and release of their ectodomain that occurs after induction by phorbol-12-myristate-13-acetate (PMA), a protein kinase C agonist.'

Only 7 exp annotations, all to Adam proteases from BHF-UCL (tagging @RLovering)
plus ~95 manual (inc IBAs, TAS, ISO)

Think that they could all be merged into the parent term 'membrane protein ectodomain proteolysis'.

**Comment by pgaudet** [comment]
Right ! At least the paper cited should be annotated to 'cytokine processing'. 

@RLovering are you OK with obsoletion and reannotation ? 

Thanks, Pascale

**Comment by RLovering** [comment]
yes, have updated annotations and agree with removing this term
Thanks for asking
Ruth

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0051088 PMA-inducible membrane protein ectodomain proteolysis'. The reason for obsoletion is that this represents an assay to induce PKC (https://en.wikipedia.org/wiki/12-O-Tetradecanoylphorbol-13-acetate). The EXP annotations have been removed. There are no mappings to this term; this term is not present in any subsets. 

Comments can be added to the ticket: : https://github.com/geneontology/go-ontology/issues/19503

Thanks, Pascale
