### ISSUE TITLE
negative regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19858]
Hi GO,

I would need a regulation term to describe a protein that negatively regulates deadenylation-dependent decapping of nuclear-transcribed mRNA

Thanks

Sylvain

term 1:
Name: regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA
Category: Process
Definition: Any process that modulates the frequency, rate or extent of deadenylation-dependent decapping of nuclear-transcribed mRNA
child of GO:0000290 deadenylation-dependent decapping of nuclear-transcribed mRNA
PMID:32354837

term 2:
Name: negative regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA
Category: Process
Definition: Any process that stops, prevents, or reduces the frequency, rate or extent of deadenylation-dependent decapping of nuclear-transcribed mRNA
child of GO:XXXXXXX regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA
PMID:32354837

**Comment by hdrabkin** [comment]
Hi @sylvainpoux 
While I'm adding regulation terms; would the same reference be good for 'positive regulation ..'?

**Comment by pgaudet** [comment]
@hdrabkin If there is no evidence for positive regulation of the process, I suggest we don't create the term. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
+id: GO:0106288
+name: regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA

+id: GO:0106289
+name: negative regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA
