### ISSUE TITLE
cargo receptor definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19859]
I'm checking curation for  a paper PMID:32735772 describing a novel autophagy cargo receptor.
There are 3 known types of autophagy cargo receptor (types i-III)

from PMID:32735772
The connection between an autophagy receptor and a selective autophagy cargo can be classified into three types. In type 1 connection, a receptor interacts with a specific protein compo- nent of a cargo. In type 2 connection, a receptor recognizes ubiquitin modification on a cargo. For type 1 and type 2 connec- tions, receptors are soluble proteins. In type 3 connection, which is common in selective organelle autophagy, a receptor is an in- tegral membrane protein embedded in the outer membrane of a cargo organelle.

This makes the current definition of cargo receptor

GO:0038024 | cargo receptor activity 
Binding specifically to a substance (cargo) to deliver it to a transport vesicle. Cargo receptors span a membrane (either the plasma membrane or a vesicle membrane), binding simultaneously to cargo molecules and coat adaptors, to efficiently recruit soluble proteins to nascent vesicles. PMID:15239958 PMID:27903609

too restrictive.
BInding to a cargo  is OK (in this case the ER) 
delivering to a transport vesicle is OK (the autophagosome).
But, it appears that
a) not all cargo receptors span membranes
b) binding is not always to coat adaptors (in fact I'm not sure e that this definition describes the existing children).

The paper goes onto show nicely that this "autophagy receptor"  is a "cargo adaptor"
it acts as a bridge between autophagy machinery atg8 and the  ER membrane, 

so I  could choose between  2 terms to describe the SAME activity

GO:0140312 | cargo adaptor activity
Definition | Binding directly to the structural scaffolding elements of a vesicle coat (such as clathrin or COPII), and bridging the membrane, cargo, and membrane deformation machinery.
(although again this definition of the cargo adaptor is too restrictive because it excludes the autophagy cargo adaptors, here it would be binding simultaneously to the autophagy machinery and bridging the cargo)

AND
GO:0038024 | cargo receptor activity as above

<img width="370" alt="Screenshot 2020-08-07 at 13 04 15" src="https://user-images.githubusercontent.com/7359272/89643837-8675d600-d8ae-11ea-9ea6-99a56cd4c139.png">

**Comment by ValWood** [comment]
This is related to the ticket where I asked if a cargo receptor should be a type of adaptor.

I'm finding it difficult to differentiate between  cargo adaptors and cargo receptors but maybe I am missing something here?

**Comment by ValWood** [comment]
tagging @marcfeuermann  as an autophagy expert

**Comment by ValWood** [comment]
essentialy, this is the same probelm I had here:

https://github.com/geneontology/go-ontology/issues/19454

cargo receptores are not described as adaptors....

**Comment by pgaudet** [comment]
@lbreuza What do you think with respect to adaptors ?

**Comment by lbreuza** [comment]
Both terms seem to describe the same activity in different words except that receptor activity is 'associated with' endocytosis but this probably makes no sense since it is not specific of that process.

**Comment by pgaudet** [comment]
So, I should merge the terms ? Which definition should I keep ?

**Comment by lbreuza** [comment]
Are there some examples of proteins (receptors) that directly bind cargo but bind indirectly to the coat machinery via an 'adaptor' and conversely some adaptors that directly bind the coat but bind the cargo indirectly via a receptor. That could explain the existence of both terms. One should check the mode of action of the 'receptors' described as child of cargo receptor activity.

**Comment by pgaudet** [comment]
I think this is a question for @ValWood

**Comment by ValWood** [comment]
Yes there are, I was trying to find the examples. 

clathrin
for e.g
https://jcs.biologists.org/content/124/10/1613.figures-only

also possibly copII

I don't know how GO wants to handle this. Maybe the autophagy receptor I was annotating needs to be annotated as a cargo receptor, and an adaptor,  But then we have an issue about what the precise difference is...

**Comment by pgaudet** [comment]
Closing - covered by #20002 #19454
