### ISSUE TITLE
P-body assembly

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19857]
Hi GO, 

I would need a new term to describe P-body assembly

Thanks

Sylvain

Name: P-body assembly
Category: Process

child of
GO:0070925 organelle assembly
GO:0022618 ribonucleoprotein complex assembly

PMID:29510985
PMID:22966201
PMID:32354837

**Comment by ukemi** [comment]
Relation to P granules, stress granules, neuronal granules?

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0033962
cytoplasmic mRNA processing body assembly
exact synonym "P-body assembly"

(I prefer P-body assembly as common usage)

v

**Comment by krchristie** [comment]
As @ValWood just mentioned, the term already exists. I believe it's fairly old before the name P-body was commonplace. Next week, when I'm doing I'll take a look and possibly make `P-body assembly` the primary term name.

[Term]
id: GO:0033962
name: cytoplasmic mRNA processing body assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of proteins and RNA molecules to form a cytoplasmic mRNA processing body." [GOC:mah, PMID:17429074]
synonym: "P body assembly" EXACT []
synonym: "P body biogenesis" RELATED []
synonym: "P-body assembly" EXACT []
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: results_in_assembly_of GO:0000932 ! P-body

**Comment by ukemi** [comment]
P-body is also the primary name for the component (GO:0000932), indeed an old term... one of the originals I believe.

**Comment by krchristie** [comment]
> P-body is also the primary name for the component (GO:0000932), indeed an old term... one of the originals I believe.

Original terms were in the somewhat bizarre number range from around 3600 to 8400, no idea why they didn't start at 1... GO:000932 is from SGD's range, so most likely a term that either Midori or I made.

**Comment by sylvainpoux** [comment]
Hi Val, Karen and David,
many thanks for your help. I did not see the synonym for cytoplasmic mRNA processing body assembly.
As P-body was the primary name for the component, I think it would make sense to change " cytoplasmic mRNA processing body assembly" to " P-body assembly"
Thanks again
Sylvain
