### ISSUE TITLE
NTR positive regulation of  reticulophagy

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19860]
standard definitions
GO:0061709 | reticulophagy

PMID:32735772
final section
The UPR Regulator Ire1 Promotes ER-Phagy by Upregulating Epr1

**Comment by mah11** [comment]
While you're at it, could you also add synonyms to GO:0061709 and the regulation term(s) using

- ER autophagy
- endoplasmic reticulum autophagy

cheers!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140500
+name: regulation of reticulophagy
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of reticulophagy." [PMID:32735772]
+synonym: "regulation of endoplasmic reticulum autophagy" EXACT []
+synonym: "regulation of ER autophagy" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0061709 ! reticulophagy
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19860 xsd:anyURI
+created_by: pg
+creation_date: 2020-08-10T12:01:22Z
+
+[Term]
+id: GO:0140501
+name: positive regulation of reticulophagy
+namespace: biological_process
+def: "Any process that increases the frequency, rate or extent of reticulophagy." [PMID:32735772]
+synonym: "positive regulation of endoplasmic reticulum autophagy" EXACT []
+synonym: "positive regulation of ER autophagy" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0061709 ! reticulophagy
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19860 xsd:anyURI
+created_by: pg
+creation_date: 2020-08-10T12:01:35Z
+




+ added synonyms on  GO:0061709

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 

Do you want all the other synonyms for 'reticulophagy' on the 'regulation' terms:

 synonym: "autophagy of the endoplasmic reticulum" EXACT []
 synonym: "autophagy of the ER" EXACT []
 synonym: "endoplasmic reticulum degradation" RELATED []
 synonym: "ER degradation" RELATED []
 synonym: "ER-phagy" EXACT []

Thanks, Pascale

**Comment by ValWood** [comment]
please
