### ISSUE TITLE
NTR: 	 endoplasmic reticulum-autophagosome adaptor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19873]
GO:NEW endoplasmic reticulum-autophagosome adaptor
synonym: ER- autophagosome anchor
synonym:  endoplasmic reticulum-autophagosome anchor

definition:
The binding activity of a molecule that brings together an ER membrane and an autophagosome during reticulophagy.

parent: GO:0043495 | protein-membrane adaptor activity

reference: PMID:32735772

Note, VAPs are a major recruiting patform (on the ER)  for soluable cytosolic proteins, but this isn't a cargo adaptor  because the ER is the cargo. the receptor is associated with the autophagosome.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140506
+name: endoplasmic reticulum-autophagosome adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together an ER membrane and an autophagosome during reticulophagy." [PMID:32735772]
+synonym: "autophagosome-endoplasmic reticulum anchor" EXACT []
+synonym: "autophagosome-ER anchor" EXACT []
+synonym: "ER- autophagosome anchor" EXACT []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19873 xsd:anyURI
+created_by: pg
+creation_date: 2020-08-27T11:04:43Z

**Comment by ValWood** [comment]
I don't see this term yet.

**Comment by pgaudet** [comment]
It's in the latest snapshot (Aug 30)
