### ISSUE TITLE
Question about GO:0015395 ?

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#19879]
Dear GO curators,

The class GO:0015395 nucleoside transmembrane transporter activity, down a concentration gradient classified as a secondary active transporter. However, I think it enables facilitated diffusion of nucleosides, not an active transport based on this http://europepmc.org/article/MED/12446811

**Comment by pgaudet** [comment]
Thanks for pointing this out. I removed the incorrect relation. 

Pascale
