### ISSUE TITLE
Trans-cinnamate-CoA ligase activity

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#19878]
Hi GO,

I would need a GO term for Trans-cinnamate:CoA ligase activity (which catalyzes the formation of CoA esters of Trans-cinnamic acid)

Thanks

Emmanuel

Term: Trans-cinnamate-CoA ligase activity
Definition:
Catalysis of the reaction:
(E)-cinnamate + ATP + CoA = (E)-cinnamoyl-CoA + AMP + diphosphate;

probably child of
GO:0016405 CoA-ligase activity
GO:0016878 acid-thiol ligase activity

Xref:
RHEA:64788
EC:6.2.1.-

PMID:22649270;

**Comment by hdrabkin** [comment]
RHEA:64788 is not available in RHEA (public). Is this a new reaction in RHEA?

**Comment by hdrabkin** [comment]
+id: GO:0106290
+name: trans-cinnamate-CoA ligase activity

**Comment by SuperManu74** [comment]
Hi,
indeed, it is a new RHEA reaction, thanks. Manu

**Comment by hdrabkin** [comment]
yes; Rhea just verified that it will be public 10/7/2020. The GO term is available but the RHEA will not be added until then.

**Comment by hdrabkin** [comment]
RHEA:64788 now available. Added. Closing
