### ISSUE TITLE
Definition of GO:0002435 immune complex clearance by erythrocytes 

### ISSUE THREAD

**Issue by ShirinSaverimuttu** [geneontology/go-ontology#19884]
Hi, 

I'd like to request additional information for the definition of GO:0002435 immune complex clearance by erythrocytes. 
The current definition is:

> The process of immune complex clearance by erythrocytes.

Proposed additional information: 

> The process often starts with binding of complement receptor 1 (CR1) on the surface of erythrocytes to a complement coated immune complex. The complex bound to erythrocyte CR1 is then transported to the liver or spleen where it is presented to phagocytes. The process ends when the complex is removed from CR1, allowing the erythrocyte to return to  general circulation.

Ref: https://en.wikipedia.org/wiki/Immune_complex 
PMID:24022490

Thank you. 

cc
@RLovering

**Comment by pgaudet** [comment]
@addiehl Are you OK with this proposal ? If yes I will implement. 

Thanks, Pascale

**Comment by addiehl** [comment]
I am happy with adding the additional sentences as a gloss to the original definition.

Alex
