### ISSUE TITLE
More updates for mitochondrial transcription factor activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19891]
Hello, 

Working on the annotations to TFAM and the family PTHR48112, the function of the mt transcription activator is a mix of a dbTF and a GTF: the binding to the promoter is not sequence-specific, but rather binds a secondary structure (AT-rich region). Moreover, PTHR48112 contains HMG proteins, that have the same function of bending DNA and binding to bent DNA to (generally) make it more accessible to the transcriptional machinery. 

To represent this more correctly, we have made the following changes:  
- moved the term from GO:0003700 DNA binding transcription factor activity, which is defined as a sequence-specific activity) to GO:0140110 transcription regulator activity
- changed the definition from "Interacting selectively and non-covalently with a specific double-stranded mitochondrial DNA sequence in order to modulate transcription by mitochondrial RNA polymerase." 
to "Interacting with the mitochondrial promoter DNA to modulate transcription by the mitochondrial RNA polymerase." 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @tberardini 

Sorry I wasn't very clear: In animals, there are 3 factors that participate in the activation of transcription (ie recruit and activate the mt RNA polymerase): TFAM, TFB1M and TF21M. According to @colinlog, their function are a mix of dbTFs, GTF and coTFs. TFAM binds DNA directly but not the other two. 

So what we have done is (as stated in the original comment) is:

1. moved the term from GO:0003700 DNA binding transcription factor activity, which is defined as a sequence-specific activity) to GO:0140110 transcription regulator activity
2. changed the definition from "Interacting selectively and non-covalently with a specific double-stranded mitochondrial DNA sequence in order to modulate transcription by mitochondrial RNA polymerase."
    to "Interacting with the mitochondrial promoter DNA to modulate transcription by the mitochondrial RNA polymerase."

The question was, is this inconsistent with what happens in plans ? Since we made the term more general, we didn't think this would cause problems, but the question was, if you would like one (or more)  more precise term(s) please do let us know. @colinlog said that mitochondria in fungi and animals and plants are more complicated than those of animals, so if more refined function are needed for plant mt transcription factors, please let us know (and point us to some papers if possible). 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm still confused what you have moved? Have you moved a term or an annotation?

and  which term did you change the definition of? none of the terms mentioned in one mention "double-stranded mitochondrial DNA"

**Comment by pgaudet** [comment]
> I'm still confused what you have moved? Have you moved a term or an annotation?

The term, GO:0034246. The definition is (was) "Interacting selectively and non-covalently with a specific double-stranded mitochondrial DNA sequence in order to modulate transcription by mitochondrial RNA polymerase. ".

**Comment by ValWood** [comment]
Ah OK.  Pombase has not used this term. SGD has (MTF1).

I annotated  MTF1 as 
GO:0016433 | rRNA (adenine) methyltransferase activity
via InterPro https://www.pombase.org/gene/SPAC1002.08c

There is no evidence that it binds to DNA as far as I can see.

**Comment by tberardini** [comment]
We will request more specific terms should we need them for annotating A. thaliana.  As far as I can tell, there are no current annotations that would be affected.

I see that you've moved the term already so the parentage has been adjusted.  You will likely remove 'sequence-specific' from the term name when you edit the definition, correct?

http://amigo.geneontology.org/amigo/term/GO:0034246

**Comment by pgaudet** [comment]
> You will likely remove 'sequence-specific' from the term name when you edit the definition, correct?

Yes ! And remove 'DNA binding' from the term label, since this term is meant to also cover TFB1M and TF21M, that do not bind DNA. 

Thanks for the feedback. I'll make these change for this ticket, please open new tickets for any new terms. 

Thanks, Pascale
