### ISSUE TITLE
Modification of GO:1902483 cytotoxic T cell apoptotic process

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19901]
Hi,

a recent paper nicely shows that "cytotoxic T cell apoptotic process" is not related to apoptosis but pyroptosis (PMID:32299851)

Would it be possible to change the definition and hierarchy of this term?

FROM:
cytotoxic T cell apoptotic process
Any apoptotic process in a cytotoxic T cell.
Child of  GO:0070231 T cell apoptotic process
TO:
GO:1902483 cytotoxic T cell pyroptotic process
Any pyroptotic process in a cytotoxic T cell. PubMed=32299851
Child of GO:0070269 pyroptosis

Thanks

Sylvain

**Comment by pgaudet** [comment]
Done - I put the 'apoptosis' term as a RELATED synonym; does that seem right ?

**Comment by sylvainpoux** [comment]
Perfect, by the way, I just realized that another term should be modified (sorry for the late notice)

GO:0008626 granzyme-mediated apoptotic signaling pathway should also be modified. It would be safe to change apoptotic to cell death, since we now know that many cell-death pathways are not related to apoptosis. In this paper, they at least show that granzyme A mediates pyroptosis and not apoptosis. As we don't know for other Granzymes, I think that best is to stay high level with cell death instead of pyroptosis

FROM:
GO:0008626 granzyme-mediated apoptotic signaling pathway
A series of molecular signals induced by granzymes which triggers the apoptotic death of a cell. The pathway starts with reception of a granzyme signal, and ends when the execution phase of apoptosis is triggered. Granzymes are serine proteases that are secreted by cytotoxic T cells and natural killer cells to induce apoptosis in target cells.
Child of  GO:0097190 apoptotic signaling pathway
TO:
GO:0008626 granzyme-mediated cell death signaling pathway
A series of molecular signals induced by granzymes which triggers the cell death of a cell. The pathway starts with reception of a granzyme signal, and ends when the execution phase of cell death is triggered. Granzymes are serine proteases that are secreted by cytotoxic T cells and natural killer cells to induce cell death in target cells. PMID:32299851
Child of  GO:0012501 programmed cell death

**Comment by pgaudet** [comment]
@sylvainpoux some paper *do* talk about apoptosis, for eg PMID:11911826. 

Should we ADD the cell death version of the term, instead of changing the existing term ? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
It is the key question: according to PMID:32299851: "The view that granzymes induce target-cell apoptosis was proposed two decades ago, when apoptosis was thought to be the dominant form of programmed cell death and assays to ascertain apoptosis were insufficiently accurate."

Many old papers mentioning apoptosis concern different types of cell deaths. It is why I prefer to link them to programmed cell death that includes both apoptosis and other types of programmed cell death.

I think that in the granzyme case, some granzymes do mediate apoptosis and other mediate other types of cell death.

**Comment by pgaudet** [comment]
@ukemi  @paolaroncaglia 

Any idea why 
'granzyme-mediated apoptotic signaling pathway'
'hormone-mediated apoptotic signaling pathway'

are not children of 'extrinsic apoptotic signaling pathway' ? 

Seems like an omission ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140507
+name: granzyme-mediated programmed cell death signaling pathway
+namespace: biological_process
+def: "A series of molecular signals induced by granzymes which triggers the cell death of a cell. The pathway starts with reception of a granzyme signal, and ends when the execution phase of cell death is triggered. Granzymes are serine proteases that are secreted by cytotoxic T cells and natural killer cells to induce cell death in target cells." [PMID:32299851]
+synonym: "granzyme-mediated cell death signaling pathway" BROAD []
+is_a: GO:0007165 ! signal transduction
+relationship: part_of GO:0012501 ! programmed cell death
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19901 xsd:anyURI
+created_by: pg
+creation_date: 2020-08-27T13:51:40Z

I will move the annotations once the term is in P2GO. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotation review ticket for GO:0008626 granzyme-mediated apoptotic signaling pathway:
https://github.com/geneontology/go-annotation/issues/3227

**Comment by paolaroncaglia** [comment]
@pgaudet 

> Any idea why
> 'granzyme-mediated apoptotic signaling pathway'
> 'hormone-mediated apoptotic signaling pathway'
> 
> are not children of 'extrinsic apoptotic signaling pathway' ?
> 
> Seems like an omission ?
> 
> Thanks, Pascale

Please see http://wiki.geneontology.org/index.php/Apoptosis_Curation_Manual#Other_children_of_apoptotic_signaling_pathway

Thanks,
Paola

**Comment by pgaudet** [comment]
Thanks @paolaroncaglia ! I added a link to the documentation in the term.
