### ISSUE TITLE
add regulates_o_transports_or_maintains_localization_of to GO-REL?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#19909]
Although the chain relations in GO-REL will eventually be removed once annotations are imported into GO-CAM models. We have used a chain relation, regulates_o_transports_or_maintains_localization_of, that is not in GO-REL. Until the annotations are imported, they will fail new QC checks that determine if relations in extensions are in RO or GO-REL. Would it be possible to as this relation as a stop-gap to keep the annotations from being filtered?

@dougli1sqrd @kltm

**Comment by dougli1sqrd** [comment]
In order to add this relation, we need a URI to assign to the label. This also seems like something @cmungall would be interested in.

**Comment by pgaudet** [comment]
I've added this to gorel. 

Local range= GO:0032879 regulation of localization ?

**Comment by pgaudet** [comment]
Added relation in GOREL

 
+# Object Property: <http://purl.obolibrary.org/obo/GOREL_0000034> (regulates_o_transports_or_maintains_localization_of)
+
+AnnotationAssertion(<http://purl.obolibrary.org/obo/go/extensions/go_annotation_extension_relations#local_range> <http://purl.obolibrary.org/obo/GOREL_0000034> "GO:0032879"^^xsd:string)
+AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#created_by> <http://purl.obolibrary.org/obo/GOREL_0000034> "pg"^^xsd:string)
+AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#creation_date> <http://purl.obolibrary.org/obo/GOREL_0000034> "2020-08-28T07:03:28Z"^^xsd:dateTime)
+AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#inSubset> <http://purl.obolibrary.org/obo/GOREL_0000034> <http://purl.obolibrary.org/obo/go#display_for_curators>)
+AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#inSubset> <http://purl.obolibrary.org/obo/GOREL_0000034> <http://purl.obolibrary.org/obo/go#valid_for_annotation_extension>)
+AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/GOREL_0000034> "regulates_o_transports_or_maintains_localization_of"@en)
+SubObjectPropertyOf(<http://purl.obolibrary.org/obo/GOREL_0000034> <http://purl.obolibrary.org/obo/GOREL_0000015>)
+ObjectPropertyDomain(<http://purl.obolibrary.org/obo/GOREL_0000034> <http://purl.obolibrary.org/obo/BFO_0000015>)
+ObjectPropertyRange(<http://purl.obolibrary.org/obo/GOREL_0000034> <http://purl.obolibrary.org/obo/BFO_0000002>)
+

I'll let @ukemi merge to make sure this is OK.

**Comment by ukemi** [comment]
I think there is a URI clash here. GOREL_0000034 is an alt id for imports.

[Typedef]
id: imports
name: imports
namespace: go/extensions/gorel
alt_id: GOREL:0000034
def: "Holds between p and c when p is a transportation or localization process and the outcome of this process is to move c to a destination that is part of some s, where the start location of c is part of the region that surrounds s." []
xref: RO:0002340
property_value: IAO:0000117 "Chris Mungall" xsd:string
is_a: go_annotation_extension_relation ! go annotation extension relation
is_a: transports ! transports
transitive_over: has_part ! has part

**Comment by pgaudet** [comment]
@balhoff I let you merge, OK ?

**Comment by balhoff** [comment]
I removed one extra declaration line; otherwise I think it's good.
