### ISSUE TITLE
Add Histone related HGNC symbols to GO Enrichment Analysis

### ISSUE THREAD

**Issue by K-Song** [geneontology/go-ontology#19919]
Dear go team,

I don't find some of the following histone HGNC symbols in GO Enrichment Analysis
http://geneontology.org

I can only find alias.

alias | hgnc_symbol
-- | --
HIST1 | H1-1
HIST1H1A | H1-1
HIST1H1B | H1-5
HIST1H1C | H1-2
HIST1H1D | H1-3
HIST1H1E | H1-4
HIST1H1PS1 | H1-12P
HIST1H1PS2 | H3P26
HIST1H1T | H1-6
HIST1H2AA | H2AC1
HIST1H2AB | H2AC4
HIST1H2AC | H2AC6
HIST1H2AD | H2AC7
HIST1H2AE | H2AC8
HIST1H2AG | H2AC11
HIST1H2AH | H2AC12
HIST1H2AI | H2AC13
HIST1H2AJ | H2AC14
HIST1H2AK | H2AC15
HIST1H2AL | H2AC16
HIST1H2AM | H2AC17
HIST1H2APS1 | H2AC2P
HIST1H2APS2 | H2AC3P
HIST1H2APS3 | H2AC9P
HIST1H2APS4 | H2AC10P
HIST1H2APS5 | H2AC5P
HIST1H2APS6 | H2ACP1
HIST1H2BA | H2BC1
HIST1H2BB | H2BC3
HIST1H2BC | H2BC5
HIST1H2BC | H2BC4
HIST1H2BD | H2BC5
HIST1H2BE | H2BC5
HIST1H2BE | H2BC6
HIST1H2BF | H2BC5
HIST1H2BF | H2BC7
HIST1H2BG | H2BC5
HIST1H2BG | H2BC8
HIST1H2BH | H2BC9
HIST1H2BI | H2BC5
HIST1H2BI | H2BC10
HIST1H2BJ | H2BC11
HIST1H2BK | H2BC12
HIST1H2BL | H2BC13
HIST1H2BM | H2BC14
HIST1H2BN | H2BC15
HIST1H2BO | H2BC17
HIST1H2BPS1 | H2BC2P
HIST1H2BPS2 | H2BC16P
HIST1H2BPS3 | H2BP6
HIST1H3A | H3C1
HIST1H3B | H3C2
HIST1H3C | H3C3
HIST1H3D | H3C4
HIST1H3E | H3C6
HIST1H3F | H3C7
HIST1H3G | H3C8
HIST1H3H | H3C10
HIST1H3I | H3C11
HIST1H3J | H3C12
HIST1H3PS1 | H3C9P
HIST1H4A | H4C1
HIST1H4B | H4C2
HIST1H4C | H4C3
HIST1H4D | H4C4
HIST1H4E | H4C5
HIST1H4F | H4C6
HIST1H4G | H4C7
HIST1H4H | H4C8
HIST1H4I | H4C9
HIST1H4J | H4C11
HIST1H4K | H4C12
HIST1H4L | H4C13
HIST1H4PS1 | H4C10P
HIST2H2AA | H2AC18
HIST2H2AA3 | H2AC18
HIST2H2AA4 | H2AC19
HIST2H2AB | H2AC21
HIST2H2AC | H2AC20
HIST2H2BA | H2BP1
HIST2H2BB | H2BP2
HIST2H2BC | H2BC20P
HIST2H2BD | H2BC20P
HIST2H2BD | H2BC19P
HIST2H2BE | H2BC21
HIST2H2BF | H2BC18
HIST2H3A | H3C15
HIST2H3B | HIST2H3B
HIST2H3C | H3C14
HIST2H3D | H3C13
HIST2H3DP1 | H3P4
HIST2H3PS1 | HIST2H3B
HIST2H3PS2 | H3-2
HIST2H4 | H4C14
HIST2H4A | H4C14
HIST2H4B | H4C15
HIST3H2A | H2AW
HIST3H2BA | H2BU2P
HIST3H2BB | H2BU1
HIST3H3 | H3-4
HIST4H4 | H4-16

Is it possible to add them?
Have a nice day
Thank you
Kai Song

**Comment by pgaudet** [comment]
Dear @K-Song 

The histone nomenclature was recently updated, this should be reflected in upcoming GO releases. 

@sylvainpoux Please correct me if this is in accurate. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@K-Song Does this answer your question ? If not please reopen then ticket. 

Thanks, Pascale
