### ISSUE TITLE
arachidonic acid epoxygenase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#19916]
Dear GO curators,

Would it be possible to create 
new_GO: arachidonic acid 5,6-epoxygenase activity; PMID:8631948; PMID:10491410
new_GO: arachidonic acid 8,9-epoxygenase activity; PMID:10491410; PMID:8246128
as children of GO:0008392 arachidonic acid epoxygenase activity
Definition: 
Catalysis of an NADPH- and oxygen-dependent reaction that converts arachidonic acid to cis-5,6-epoxyeicosatrienoic acid.
Catalysis of an NADPH- and oxygen-dependent reaction that converts arachidonic acid to cis-8,9-epoxyeicosatrienoic acid.
review to cite: PMID: 18952572

Many thanks for your help,

Nevila Hyka-Nouspikel

**Comment by hdrabkin** [comment]
Defenitions not precise enough; need all reactants and products to make an equation.

**Comment by hdrabkin** [comment]
So from the Reactome pathway entry for the parent, I know that
aa (arachidonic acid) + NADPH + O2 + H+ = NADP(+)  + H20 + eet  (cis-epoxyeicosatrienoic acid.) 
This is a good start.

**Comment by hdrabkin** [comment]
@nnouspike, you can use these terms immediately 

+id: GO:0106301
+name: arachidonic acid 5,6-epoxygenase activity
+id: GO:0106302
+name: arachidonic acid 8,9-epoxygenase activity


RHEA ticket  [help #19274] with following def:
GO:0106301 arachidonic acid 5,6-epoxygenase activity    PMID:8631948; PMID:10491410
arachidonic acid (ChEBI15843) + NADPH + O2 + H+ = NADP(+) + H20 + 5,6 cis epoxyeicosatrienoic acid (ChEBI34450)
 
GO:0106302 arachidonic acid 8,9-epoxygenase activity  PMID:10491410; PMID:8246128
arachidonic acid (ChEBI15843) + NADPH + O2 + H+ = NADP(+) + H20 + 8,9 cis epoxyeicosatrienoic acid (ChEBI34490)

GO:0008405  arachidonic acid 11,12-epoxygenase activity PMID:10681399
arachidonic acid (ChEBI15843) + NADPH + O2 + H+ = NADP(+) + H20 + cis-11,12-epoxyeicosatrienoic acid (CHEBI:34130)


GO:0008404 arachidonic acid 14,15-epoxygenase activity  PMID:10681399
arachidonic acid (ChEBI15843) + NADPH + O2 + H+ = NADP(+) + H20 + cis-14,15-epoxyeicosatrienoic acid  (CHEBI:34157)

There is a parent term GO:0008392, arachidonic acid epoxygenase activity, where the product is "a cis-epoxyeicosatrienocid acid, which CHEBI has an id for (CHEBI:64007) but not sure if you want to make a RHEA for that one also
arachidonic acid (ChEBI15843) + NADPH + O2 + H+ = NADP(+) + H20 + a cis-epoxyeicosatrienocid acid (CHEBI:64007}
PMID:10681399 PMID:18952572

**Comment by nnouspikel** [comment]
Thank you very much Harold for the feedback.

Here is 1:1 mapping:

- GO:0106301 arachidonic acid 5,6-epoxygenase activity
  RHEA:49936 - (5Z,8Z,11Z,14Z)-eicosatetraenoate + O2 + reduced [NADPH—hemoprotein reductase] = 5,6-epoxy- (8Z,11Z,14Z)-eicosatrienoate + H+ + H2O + oxidized [NADPH—hemoprotein reductase] 

- GO:0106302 arachidonic acid 8,9-epoxygenase activity 
New RHEA:64984 (not yet public) - (5Z,8Z,11Z,14Z)-eicosatetraenoate + O2 + reduced [NADPH—hemoprotein reductase] = 8,9-epoxy-(5Z,11Z,14Z)-eicosatrienoate + H+ + H2O + oxidized [NADPH—hemoprotein reductase]

- GO:0008405 arachidonic acid 11,12-epoxygenase activity
RHEA:51480 - (5Z,8Z,11Z,14Z)-eicosatetraenoate + O2 + reduced [NADPH—hemoprotein reductase] = 11,12-epoxy-(5Z,8Z,14Z)-eicosatrienoate + H+ + H2O + oxidized [NADPH—hemoprotein reductase] 

- GO:0008404 arachidonic acid 14,15-epoxygenase activity 
RHEA:51472 - (5Z,8Z,11Z,14Z)-eicosatetraenoate + O2 + reduced [NADPH—hemoprotein reductase] = 14,15-epoxy-(5Z,8Z,11Z)-eicosatrienoate + H+ + H2O + oxidized [NADPH—hemoprotein reductase]

May consider adding in the definition : Uses molecular oxygen inserting one oxygen atom into a substrate, and reducing the second into a water molecule, with two electrons provided by NADPH via cytochrome P450 reductase (NADPH--hemoprotein reductase). 

review to cite: PMID: 18952572

At the moment there is no RHEA for the parent term GO:0008392, arachidonic acid epoxygenase activity. To be discussed.

Many thanks again,

Nevila

**Comment by hdrabkin** [comment]
Thanks @nnouspikel; I am cross-checking with RHEA.

**Comment by hdrabkin** [comment]
Added RHEAs; but have to wait for one..GO:0106302 arachidonic acid 8,9-epoxygenase activity
New RHEA:64984

**Comment by pgaudet** [comment]
Is the Rhea now available ?

**Comment by hdrabkin** [comment]
RHEA:64984 is not available yet (remember 8 week cycle, so depending on when the request is officially filled, up to two months ).  If I put in Sep 2, then Nov 2 at latest

**Comment by hdrabkin** [comment]
RHEA:64984 in now available. Adding and closing this ticket.
