### ISSUE TITLE
Switch labels/synonyms meiotic cell cycle <-> meiosis and mitotic cell cycle <-> mitosis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19910]
@ValWood 
Or anyone else who was involved in this work - would it be OK to switch labels/synonyms meiotic cell cycle <-> meiosis and mitotic cell cycle <-> mitosis ? It would be better for users if the labels were better aligned with usage by the community.

**Comment by pgaudet** [comment]
Requested by @cmungall

**Comment by ValWood** [comment]
NO!
These are not the terms for mitosis and meiosis. These are the terms for the mitotic and meiotic cell cycles (M phase + interphase).

The term for mitosis is "GO:0140014  mitotic nuclear division", although oddly it does not have the  synonym "mitosis" - it should. I would add exact  synonym to  "GO:0140014  mitotic nuclear division"

Same for meiosis.

We had lots of discussion about this change at GO meetings , I will try to find the tickets later.

**Comment by ValWood** [comment]
Sorry I did not have time to respond fully before  it seems the required actions are:

- [ ] add exact synonym "mitosis to  GO:0140014   mitotic nuclear division
- [ ] add exact synonym meiosis to GO:0140013    meiotic nuclear division
I'm not sure why these  exact synonyms are not present

- [ ] I have no objection if you want to make 'mitosis' and 'meiosis'  the primary names for the nuclear division terms. However, be aware that the alterations  were made to prevent curators using these terms incorrectly . Often researchers  will say 'during meiosis' and 'during mitosis' colloquially when they are referring to the particular cell cycle, not the nuclear division event.

- [ ] Comments might be useful in the "mitotic cell cycle" and "meiotic cell cycle terms" that  these terms are not for "mitosis" and "meiosis"

Does this make sense?

**Comment by pgaudet** [comment]
OK for me.

**Comment by pgaudet** [comment]
How's that as a comment: 

> Note that this term should not be confused for 'GO:0140014 ; mitotic nuclear division'. 'GO:0000278 ; mitotic cell cycle represents the entire mitotic cell cycle, while 'GO:0140014 ; mitotic nuclear division' specifically represents the actual nuclear division step of the mitotic cell cycle.

(and same for meiosis) ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes. We need a corresponding comment on the  GO:0140014 ; mitotic nuclear division' terms

perhaps 

Note that this term should not be confused with 'GO:0140014 ; mitotic nuclear division'. 'GO:0000278 ; mitotic cell cycle represents the entire mitotic cell cycle, while 'GO:0140014 ; mitotic nuclear division' specifically represents MITOSIS the actual nuclear division step of the mitotic cell cycle.

Also, I don't see why we should not change the  synonyms on 
GO:0000278 ; mitotic cell cycle and the meiotic term
to BROAD from RELATED
