### ISSUE TITLE
protein peptidyl-prolyl isomerization, parent missing

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#19927]
protein peptidyl-prolyl isomerization
looks like "protein peptidyl-prolyl isomerization" is missing parent "post-translational protein modification"
at least according to the ref paper:

The cis-trans isomerization of proline serves as a regulatory switch in signaling pathways. We identify the proline isomerase Fpr4, a member of the FK506 binding protein family in Saccharomyces cerevisiae, as an enzyme which binds the amino-terminal tail of histones H3 and H4 and catalyses the isomerization of H3 proline P30 and P38 in vitro. We show that P38 is necessary for methylation of K36 and that isomerization by Fpr4 inhibits the ability of Set2 to methylate H3 K36 in vitro. These results suggest that the conformational state of P38, controlled by Fpr4, is important for methylation of H3K36 by Set2. Consistent with such an antagonistic role, abrogation of Fpr4 catalytic activity in vivo results in increased levels of H3K36 methylation and delayed transcriptional induction kinetics of specific genes in yeast. These results identify proline isomerization as a novel noncovalent histone modification that regulates transcription and provides evidence for crosstalk between histone lysine methylation and proline isomerization.

**Comment by ValWood** [comment]
I agree. I tried to get this into PRO once, but it dodn't get added

This is on the old tracker
https://sourceforge.net/p/psidev/mod-controlled-vocab-changes/72/
although I know there was some follow up there does not seem to be any dialogue in the ticket. Then it just went dead.

I don't see it on the new tracker either.
https://github.com/HUPO-PSI/psi-mod-CV/issues

Although this tracker implies that it could be some time:
https://github.com/HUPO-PSI/psi-mod-CV/issues/10

**Comment by pgaudet** [comment]
@ValWood WHo can we contact to follow up on this at psi-MOD ?

**Comment by ValWood** [comment]
new ticket created:
https://github.com/HUPO-PSI/psi-mod-CV/issues/28

**Comment by Antonialock** [comment]
Another complication:
Perhaps not all proline isomerization is post-tranlsational. According to this wikipedia article (no reference supplied):

"All organisms possess prolyl isomerase enzymes to catalyze this isomerization, and some bacteria have specialized prolyl isomerases associated with the ribosome."

https://en.wikipedia.org/wiki/Proline#Cis-trans_isomerization

**Comment by Antonialock** [comment]
maybe in this case it would be better to co-annotate to non-covalent chromatin/histone modification (histone modification is currently a child of covalent modification, but I guess this shows that non-covalent modification also regulate chromatin organization)

(I'm not actually annotating the paper referenced for proline isomerization)

**Comment by pgaudet** [comment]
Sounds like there may not be an action item for this ?

**Comment by Antonialock** [comment]
maybe not...
