### ISSUE TITLE
definition of GO:0042562 hormone binding

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#19928]
... is "Interacting selectively and non-covalently with any hormone, naturally occurring substances secreted by specialized cells that affect the metabolism or behavior of **_other_** cells possessing functional receptors for the hormone." That does not work for autocrine hormones, like some eicosanoids, that can act by binding receptors on the same cells that secrete them. The definition of  GO:0048018 receptor ligand activity, "The activity of a gene product that interacts with a receptor to effect a change in the activity of the receptor. **_Ligands may be produced by the same, or different, cell that expresses the receptor._** Ligands may diffuse extracellularly from their point of origin to the receiving cell, or remain attached to an adjacent cell surface (e.g. Notch ligands)", allows for this possibility.

Could the word "other" be deleted from the hormone binding definition and a sentence added to the end of the definition, perhaps "Hormones may be produced by the same, or different, cell as express the receptor."

**Comment by pgaudet** [comment]
Fixed. It'd be nice to have a reference for this term (right now it's just curator initials). 

Thanks, Pascale
