### ISSUE TITLE
fixes to "very long chain fatty acid omega-hydroxylase activity"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#19925]
While working on **fatty acid omega-hydroxylase activity** #19899, I noticed some issues with this term:

> [Term]
> id: GO:0102207
> name: very long chain fatty acid omega-hydroxylase activity
> namespace: molecular_function
> def: "Catalysis of the reaction: behenate + NADPH + O2 + H+ = 22-hydroxydocosanoate + NADP + H2O." [EC:1.14.13.-, GOC:pz]
> xref: MetaCyc:RXN-12155
> is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

**Specificity of term name vs definition, change name to match def?**
- The definition is very specific, but the term name is general. It seems that if the term is for a very specific reaction, then the name should match. Alternatively, we could broaden the definition. 
- There is a Rhea reaction which matches the definition: **RHEA:40079** `docosanoate + O2 + reduced [NADPH--hemoprotein reductase] = 22-hydroxydocosanoate + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]`, noting that behenate is a synonym for docosanoate, see https://pubchem.ncbi.nlm.nih.gov/compound/Behenate
- The Rhea reaction lists 2 publications:
-- Sanders et al. 2005. Evidence for two enzymatic pathways for omega-oxidation of docosanoic acid in rat liver microsomes. J Lipid Res. PMID:15716582 
-- Sanders et al. 2006. Omega-oxidation of very long-chain fatty acids in human liver microsomes. Implications for X-linked adrenoleukodystrophy. J Biol Chem. 281(19):13180-7. PMID:16547005

**parentage of term**

Here is the current location of `GO:0102207 - very long chain fatty acid omega-hydroxylase activity`:
<pre>
- GO:0016491 - [EC:1] oxidoreductase activity 
-- GO:0004497 - monooxygenase activity
--- GO:0016709 - [EC:1.14.13] oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen
---- => [RHEA:40079] GO:0102207 - very long chain fatty acid omega-hydroxylase activity (def-xref: EC:1.14.13.-, GOC:pz; xref: MetaCyc:RXN-12155)
-- GO:0016705 - [EC:1.14] oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
--- GO:0016709 - [EC:1.14.13] oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen
---- => [RHEA:40079] GO:0102207 - very long chain fatty acid omega-hydroxylase activity (def-xref: EC:1.14.13.-, GOC:pz; xref: MetaCyc:RXN-12155)
--- GO:0120250 - [RHEA:39023] fatty acid omega-hydroxylase activity
---- GO:0102033 - [RHEA:56748] long-chain fatty acid omega-hydroxylase activity (xref: EC:1.14.13.205 => EC:1.14.14.80, MetaCyc:RXN-16394, RHEA:56748)
</pre>

But the Rhea says that `RHEA:40079 is a RHEA:39023`, which would place `GO:0102207 - very long chain fatty acid omega-hydroxylase activity` under `GO:0120250 - [RHEA:39023] fatty acid omega-hydroxylase activity`

It's also worth noting that the EC number of `GO:0102033 - [RHEA:56748] long-chain fatty acid omega-hydroxylase activity` changed from EC:1.14.**_13_**.205 to EC:1.14.**_14_**.80, so the current placement of `GO:0102207 - very long chain fatty acid omega-hydroxylase activity` under `GO:0016709 - [EC:1.14.13] oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen` might just be because the term is somewhat old and doesn't reflect the change from EC:1.14.13 to EC:1.14.14

Moving this term to be under the parent that Rhea indicates would give this structure:

<pre>
- GO:0016491 - [EC:1] oxidoreductase activity 
-- GO:0016705 - [EC:1.14] oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
--- GO:0120250 - [RHEA:39023] fatty acid omega-hydroxylase activity
---- GO:0102033 - [RHEA:56748] long-chain fatty acid omega-hydroxylase activity (xref: EC:1.14.13.205 => EC:1.14.14.80, MetaCyc:RXN-16394, RHEA:56748)
---- =>GO:0102207 - [RHEA:40079] very long chain fatty acid omega-hydroxylase activity (def-xref: EC:1.14.13.-, GOC:pz; xref: MetaCyc:RXN-12155)
</pre>

**reference to EC# with a dash**
- The definition contains a reference to a partial EC #: "EC:1.14.13.-". @hdrabkin - Is this OK, or do you try to remove these from definition dbxrefs too?
- Also note comment about change in EC number of similar term `GO:0102033 - [RHEA:56748] long-chain fatty acid omega-hydroxylase activity` with respect to EC number.

**Comment by krchristie** [comment]
@hdrabkin - I assigned this to both of this. I don't mind doing the work, but I need input from you since this relates to Rhea. Or you can do the work yourself, whichever you prefer.

**Comment by krchristie** [comment]
AmiGO shows no annotations to this term.

**Comment by hdrabkin** [comment]
The partial EC should be removed; It's one of the Plant ones I missed
GO:0102207 - [RHEA:40079] very long chain fatty acid omega-hydroxylase activity (def-xref: EC:1.14.13.-, GOC:pz
