### ISSUE TITLE
NTR: mitotic nuclear bridge organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19948]
NTR: mitotic nuclear bridge organization
A mitotic cell cycle process  which results in the assembly, arrangement, or disassembly of the mitotic nuclear bridge during closed mitosis

Descendant of 
GO:0101024 | nuclear membrane organization involved in mitotic nuclear division

Closed mitosis requires local disassembly of the nuclear envelope.
Dey G, Culley S, Curran S, Schmidt U, Henriques R, Kukulski W, Baum B.
Nature. 2020 Sep;585(7823):119-123. doi: 10.1038/s41586-020-2648-3. Epub 2020 Aug 26.
PMID: 32848252

**Comment by deygautam** [comment]
This one would be very useful!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140515
+name: mitotic nuclear bridge organization
+namespace: biological_process
+def: "A mitotic cell cycle process which results in the assembly, arrangement, or disassembly of the mitotic nuclear bridge during closed mitosis." [PMID:32848252]
+is_a: GO:0101024 ! nuclear membrane organization involved in mitotic nuclear division
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19948 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-09T14:04:33Z

**Comment by ValWood** [comment]
Hi Pascale. Should we see this term in the release?

**Comment by ValWood** [comment]
Hi Pascale,

I still don't see these terms. Is the release working OK?

**Comment by pgaudet** [comment]
@ValWood 
The last snapshot release is from Sept 11: 

http://snapshot.geneontology.org/metadata/release-date.json

I see the term in snapshot/go-basic: http://snapshot.geneontology.org/ontology/go-basic.obo

Thanks, Pascale

**Comment by ValWood** [comment]
there today, thanks!
