### ISSUE TITLE
autoclassification of "1,2-dichloroethane metabolic process"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#19940]
The term `1,2-dichloroethane metabolic process` is not classifying under `halogenated hydrocarbon metabolic process` even though all the relevant terms are defined with equivalence axioms referencing ChEBI terms.

Looking at ChEBI, it looks this is because they have defined `haloalkane` as a subclass of `organohalogen compound` instead of as a subclass of `halohydrocarbon`. I have submitted a suggestion to ChEBI.

> [Term]
> id: CHEBI:24469
> name: haloalkane
> subset: 3_STAR
> def: "An organohalogen compound that is an alkane in which at least one hydrogen atom has been replaced by with a halogen atom." []
> synonym: "alkyl halide" RELATED [ChEBI]
> synonym: "haloalkanes" RELATED [ChEBI]
> synonym: "alkyl halides" RELATED [ChEBI]
> is_a: CHEBI:36684
> 
> [Term]
> id: CHEBI:36684
> name: organohalogen compound
> subset: 3_STAR
> def: "A compound containing at least one carbon-halogen bond." []
> synonym: "organohalogen compounds" RELATED [ChEBI]
> is_a: CHEBI:33285
> is_a: CHEBI:37578

**Comment by krchristie** [comment]
ChEBI responded very quickly and has made the suggested change already. I will leave this open until it propagates through to GO and I can confirm that `1,2-dichloroethane metabolic process` classifies where it should.

**Comment by pgaudet** [comment]
Hi @krchristie , Is there anything that needs to be done here, or can this close ?

**Comment by krchristie** [comment]
As I said above, I'd like to leave it open until it propagates through to GO to confirm that the classification is working properly. As of today, it does not look this has occurred.

**Comment by pgaudet** [comment]
This looks fixed. Please reopen if you notice a problem.
