### ISSUE TITLE
revise definition GO:0101024 | nuclear membrane organization involved in mitotic nuclear division/ add parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19949]
GO:0101024 | nuclear membrane organization involved in mitotic nuclear division

current
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the nuclear inner or outer membrane during mitotic nuclear division. PMID:15147872

revised
A mitotic cell cycle process which results in the assembly, arrangement, or disassembly of the nuclear inner or outer membrane during mitosis. 

(the term name could be refactored to
mitotic nuclear membrane organization
now that the  annotation problems plaguing  mitotic cell cycle vs mitosis are resolved)

**Comment by ValWood** [comment]
the term name could be refactored to...


Especially if we go ahead and switch 
GO:0140014    mitotic nuclear division with exact mitosis
as discussed recently
mitotic nuclear division

**Comment by pgaudet** [comment]
> Especially if we go ahead and switch
GO:0140014 mitotic nuclear division with exact mitosis
as discussed recently
mitotic nuclear division
 
This was done in #19910
