### ISSUE TITLE
peptidyl-threonine O-acetylation

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19957]
Hi GO,

I would need new terms for peptidyl-threonine O-acetylation. There is already a term for serine acetylation but not for threonine

Thanks

Sylvain

1)
Name: peptidyl-serine acetylation
child of GO:0006473 protein acetylation
Definition: The acetylation of peptidyl-threonine. 
PMID:16728640
PMID:22802624

2)
Name: peptidyl-threonine O-acetylation
Definition: The acetylation of peptidyl-threonine to form peptidyl-O-acetyl-L-threonine 
child of peptidyl-serine acetylation (above) and  GO:0018210 peptidyl-threonine modification
PMID:16728640
PMID:22802624
RESID; AA0423.

**Comment by krchristie** [comment]
@sylvainpoux - Your terms are added. Thanks for providing references for each term. That is so helpful.
