### ISSUE TITLE
nuclear pore distribution vs localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19951]
Is there any difference ? Same number of annotations.
<img width="700" alt="Screenshot 2020-09-06 at 10 30 31" src="https://user-images.githubusercontent.com/7359272/92325062-813bb080-f03f-11ea-9a52-318d36124ac6.png">

mislocalization will result in abnormal  distribution?

**Comment by pgaudet** [comment]
Looks like it's the same genes annotated to both terms - am I reading this wrong ? 

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/4782928/92358238-83f2e000-f0e9-11ea-9a07-1dfeedfab454.png">


In this case I would merge. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Ah ! Got it - there are no direct annotations to the parent  'GO:0051664 nuclear pore localization'. So a merge would seem appropriate. 

Many annotations are to NUP proteins, suggesting a phenotype. But that can be revised separately. 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes I think so.
