### ISSUE TITLE
obsolete: GO:0043492 ATPase activity, coupled to movement of substances

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19965]
Not a necessary grouping term.
Has no children, but is labelled not for direct annotation

(note that there are probably other terms   which need the ancestor of this term as a parent)

**Comment by pgaudet** [comment]
Hi @ValWood 
I'll merge this into GO:0042626 ATPase-coupled transmembrane transporter activity

OK ?

**Comment by ValWood** [comment]
You could. The grouping was possibly established for ATPase motors and ATPase transmembrane transporters because they are both 'transport' but these types of transporters have no commonality except the use ATP for energy.

So, I agree with the merge, but it should probably be 'related' rather than broad.

**Comment by ValWood** [comment]
In fact, if it has no direct annotations, do the merge, but exclude the label as a synonym. It isn't  a helpful synonym (but the ID will be preserved)

**Comment by ValWood** [comment]
Actually, there are 2 annotations and they are both transmembrane transporters so yes go ahead and merge.
Both of these annotations are ISS/O but the with filed is empty. Shouldn't they be rejected anyway?

**Comment by pgaudet** [comment]
Those annotations are from GeneDB to the ABCF1 LmjF.03.0160:mRNA gene

@Achchuthan Can you please make sure there is a value in the 'with' field? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Done here https://github.com/geneontology/go-ontology/pull/19995/commits/cd33db36b43303785ee5f5219acb9332351dfd07
