### ISSUE TITLE
GID complex synonyms and parentage

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19980]
Please add:

C-terminal to LisH  complex
CTLH complex
(PMID:29911972)
as exact synonyms of 
GID complex GO:0034657

And could 
GID complex GO:0034657 
be placed under
ubiquitin ligase complex GO:0000151

Thanks

**Comment by hdrabkin** [comment]
moved under ubiquitin ligase complex (a child of original intracellular protein containing complex); added syns.
This slipped by me somehow.
