### ISSUE TITLE
probelm multimeric ribonuclease P complex (GO:0030681)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19982]
multimeric ribonuclease P complex (GO:0030681)
Definition | Parents
-- | --
A ribonuclease P complex that generally contains a single RNA molecule and several protein molecules. Examples of this complex are found in Archaeal species.

has the descendant
nucleolar ribonuclease P complex

so something wrong here.

Maybe just remove
"Examples of this complex are found in Archaeal species".

**Comment by mah11** [comment]
I don't see the problem ... the nucleolar term (GO:0005655) is a subclass of GO:0030681. It wouldn't be OK the other way round, but GO:0030681 isn't restricted by compartment itself; it allows for subtypes in different compartments.

The line about "found in Archaea" isn't necessary, but it also isn't wrong.

**Comment by ValWood** [comment]
Yes of course. I think it's an odd/unnecessary  example though... but will close

**Comment by ValWood** [comment]
It's found across all domains of life?
