### ISSUE TITLE
steroid 21-monooxygenase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#19996]
Dear GO curators,

Could you consider updating the definition for the electron donor :

-  GO:0103069   17-hydroxyprogesterone 21-hydroxylase activity
  definition: Reaction=17alpha-hydroxyprogesterone + O2 + reduced [NADPH--hemoprotein reductase] = 
  11-deoxycortisol + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]  [Rhea:50308; 
  https://www.rhea-db.org/reaction?id=50308]; child of GO:0004509

- GO:0004509    steroid 21-monooxygenase activity
  A C(21) steroid + [reduced NADPH--hemoprotein reductase] + O(2) = a 21-hydroxy-C(21)-steroid + 
  [oxidized NADPH--hemoprotein reductase] + H(2)O.
  EC=1.14.14.16

and create
 
- new_GO: progesterone 21-hydroxylase activity
 Reaction=O2 + progesterone + reduced [NADPH--hemoprotein reductase] = 21-hydroxyprogesterone + 
 H(+) + H2O + oxidized [NADPH--hemoprotein reductase] [Rhea:50304; https://www.rhea-db.org/reaction? id=50304]; child of GO:0004509

Thank you very much for your help.

Nevila Hyka-Nouspikel

**Comment by hdrabkin** [comment]
I've assigned the RHEA to GO:0103069; it will get the rhea def .
Requested a rhea for GO:0004509 based on EC:1.14.14.16 def

**Comment by hdrabkin** [comment]
+id: GO:0106309
+name: progesterone 21-hydroxylase activity
Can you give me a PMID for your new term? Currently using just the RHEA.

WIll keep ticket open pending rhea request for the EC.

**Comment by nnouspikel** [comment]
Ref for GO:0106309: PMID:25855791
Many thanks!

**Comment by hdrabkin** [comment]
Added PMID 
RHEA ticket [help 194259] for EC:1.14.14.16 id

**Comment by hdrabkin** [comment]
Created:  RHEA:65612 Not public as of 2/10/2021

**Comment by pgaudet** [comment]
Added [RHEA:65612] to GO:0004509
 name: steroid 21-monooxygenase activity

**Comment by hdrabkin** [comment]
I just removed the rhea pending tag and can now close the ticket.
