### ISSUE TITLE
GO:0044819   mitotic G1/S transition checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19990]
This reads as if a cell cycle checkpoint detects progression which doesn't make sense.
I'm not sure what is detected at G1/S (DNA integrity and size?)

GO:0044819   mitotic G1/S transition checkpoint
Biological Process

Definition (GO:0044819 GONUTS page)
A cell cycle checkpoint that detects and negatively regulates progression from G1 to S phase as part of a mitotic cell cycle.

**Comment by pgaudet** [comment]
What is the action ?

**Comment by mah11** [comment]
I think it's to fill in some missing words in the text def after "detects", to say what is being detected. Same goes for a few other checkpoint defs: GO:0007095, GO:0031571, GO:0031572, GO:0044773, GO:0044783, GO:0044818. For several of them just add "DNA damage" but it'll need to be a bit more generic for GO:0044818 and GO:00448189.

**Comment by ValWood** [comment]
Yes. You can assign this to me. In a couple of weeks I am going to do a final tidy of the cell cycle transition terms, because I'm going to (finally) model the G2/M transition.  This should enable us to resolve the remaining issues with the GO terms and sort many annotation issues . I will confirm all the changes with the Nurse (cell cycle) lab and others.

I have a bunch more refinements to the  DNA integrity checkpoint terms that haven't  even made it into a ticket yet. There are some logic issues. I made some progress  in resolving  with Paul Russell and Nick Rhind who both work in this area. However, when I was about to type up the ticket I found another problem. so I also postponed this.

I hope to start work on this  in late October...

**Comment by ValWood** [comment]
GO:0000075   cell cycle checkpoint

is defined

Definition (GO:0000075 GONUTS page)
A cell cycle process that controls cell cycle progression by monitoring the integrity of specific cell cycle events. A cell cycle checkpoint begins with detection of deficiencies or defects and ends with signal transduction.


So
GO:0044819 mitotic G1/S transition checkpoint

should change to
A cell cycle checkpoint that controls cell cycle progression by monitoring the integrity of specific cell cycle events at G1/S


But I would likse to further check this would some checkpoint experts.
We have currently modelled checkpoitns as  signalling pathways negatively regulating the transition. 

This is a broader  definiiton of a checkpoint  and it more analogous to the transition itself.
It isn't how te checkpoint pathways were modelled at the cell cycle meeting so I woul d nedd to confirm.

**Comment by pgaudet** [comment]
I think this was addressed here: #20935
