### ISSUE TITLE
proposed logical def for generic transporter activity

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#20001]
As part of the pathways2GO project, we noticed that transporter activity does not have a logical definition. It would be nice to somehow tie the definition with specific relations that restrict the relation. Would it make sense to make a logical definition for the generic transporter activity as 'molecular_function
and ('transports or maintains localization of' some 'chemical entity')
and ('has target start location' some 'cellular anatomical entity')
and ('has target end location' some 'cellular anatomical entity')'?
A DL query for 'molecular_function and 'transports or maintains localization of' some 'chemical entity''
Shows that almost all the transporter activities retrieved by this query identify almost things that are obvious and a few that I think are correct based on the definition: floppase, flippase, and glycolipid transfer activity. 

In fact, it may be necessary and sufficient to define the term:
'molecular_function
and ('transports or maintains localization of' some 'chemical entity')

and make
and ('has target start location' some 'cellular anatomical entity')
and ('has target end location' some 'cellular anatomical entity')' asserted subclasses.

1. Should insertase activity be classified as a transporter since they take a protein from somewhere and insert it into a membrane?

Queries for molecular_function and 'transports or maintains localization of' some cellular_component returns no results .
molecular_function and 'transports or maintains localization of' some 'anatomical entity' returns no results.
This would imply that the above logical definition is safe for the generic term.

**Comment by ValWood** [comment]
Hi David,

Shouldn't it be

and ('transports' some 'chemical entity')
rather than transports or maintains?

Localization is "transports or maintains"
transports is directed movement?

v

**Comment by ukemi** [comment]
It could be, but that isn't in line with the current logical defs. Design pattern change? As near as I can tell, we have never used transports.

**Comment by ValWood** [comment]
Transports seems most appropriate for a transporter? "localization" isn't specific enough.
v
