### ISSUE TITLE
GO:0070890 and GO:0008520 should be merged?

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#20014]
Dear GO curators,

Are these terms GO:0070890 and GO:0008520 represent the same function?

**Comment by pgaudet** [comment]
Dear @Nizal-Shammry 

Thanks for pointing this out. I merged GO:0070890  sodium-dependent L-ascorbate transmembrane transporter activity into GO:0008520. The textual definitions of the two terms were essentially identical, plus the paper that was cited for GO:0070890, PMID:18094143, clearly describes a symporter. 

Thanks, Pascale
