### ISSUE TITLE
GO:0047862 synonyms mess

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#20027]
```
id: GO:0047862
name: diisopropyl-fluorophosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: diisopropyl fluorophosphate + H(2)O = diisoprop
yl phosphate + 2 H(+) + hydrogen fluoride." [EC:3.1.8.2, RHEA:24100]
synonym: "DFPase activity" EXACT [EC:3.1.8.2]
synonym: "dialkylfluorophosphatase activity" EXACT [EC:3.1.8.2]
synonym: "diisopropyl phosphorofluoridate hydrolase activity" EXACT [EC:3.1.8.2]
synonym: "diisopropyl-fluorophosphate fluorohydrolase activity" EXACT [EC:3.1.8.
2]
synonym: "diisopropylfluorophosphonate dehalogenase activity" EXACT [EC:3.1.8.2]
synonym: "diisopropylphosphofluoridase activity" EXACT [EC:3.1.8.2]
synonym: "isopropylphosphorofluoridase activity" EXACT [EC:3.1.8.2]
synonym: "OPA anhydrase activity" EXACT [EC:3.1.8.2]
synonym: "OPAA activity" EXACT [EC:3.1.8.2]
synonym: "organophosphate acid anhydrase activity" EXACT [EC:3.1.8.2]
synonym: "organophosphorus acid anhydrolase activity" EXACT [EC:3.1.8.2]
synonym: "somanase activity" EXACT [EC:3.1.8.2]
synonym: "tabunase activity" EXACT [EC:3.1.8.2]
xref: EC:3.1.8.2
xref: KEGG_REACTION:R01533
xref: MetaCyc:DIISOPROPYL-FLUOROPHOSPHATASE-RXN
xref: RHEA:24100
is_a: GO:0016795 ! phosphoric triester hydrolase activity
```
Here all synonyms are marked EXACT but judging from the entry definition this is not so. The substrate in the definition is diisopropyl fluorophosphate, so

- OPA anhydrase activity / OPAA activity / organophosphate acid anhydrase activity / organophosphorus acid anhydrolase activity are BROAD or may be moved to GO:0016795 ! phosphoric triester hydrolase activity
- somanase activity / tabunase activity are only RELATED

Could you please have a look?

**Comment by pgaudet** [comment]
We have 14k 'EXACT' synonyms from EC (see attached file). Should we replace all by 'RELATED' ? It would be difficult to review all manually. 


[exact_ec_syn.txt](https://github.com/geneontology/go-ontology/files/5287979/exact_ec_syn.txt)

**Comment by rwst** [comment]
If you change them all to RELATED you abandon all those that were already checked and fixed.

**Comment by pgaudet** [comment]
Right - but I'm not sure how to identify those that were checked - do you have suggestions ?

**Comment by rwst** [comment]
My impression is there are not many. Possibly:

1. entries with synonyms edited after EC import can be considered checked
2. also those being subject of a github issue
3. unchecked entries may be a subset of entries that exclusively have EXACT mappings

I have no idea how to implement 2, nor how far it all gets you.

**Comment by hdrabkin** [comment]
My two cents worth;
I think that anything coming from EC should be marked related, as I was told not too long ago that EC does not attach any 'weight' to the synonyms (exact, narrow,etc.).  Note the record says 'alternative names'.
I have also been seeing that many of the synonyms given an xref to EC are NOT specified in the EC record. When I see those I strip the EC off.  AN example is the EC cited above: there appears to be only 6 
https://enzyme.expasy.org/EC/3.1.8.2
DFPase.
OPA anhydrase.
OPAA.
Organophosphorus acid anhydrolase.
Somanase.
Tabunase.

I
Checking all would be a lot of work. 

If we wanted to automate it either make all 'related' if has EC and/or strip EC xrefs from all synonyms

**Comment by pgaudet** [comment]
The ontology group has decided to change all EXACT synonyms with an EC xref to RELATED.

**Comment by rwst** [comment]
I would ask you to tag the last version of the repository before that change, so that the information can be transferred, e.g. to Wikidata, and referred to.

**Comment by pgaudet** [comment]
Hi @rwst 
The pull request is here if you want to have a look: 
https://github.com/geneontology/go-ontology/pull/20043/commits/6c14818cc4b0c16e24edfa308ed0cc76a1268473

I don't know how to tag the last version of the repository ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Do you mean this ? 
http://release.geneontology.org/2020-09-10/ontology/index.html

This is the last 'versioned' version.

**Comment by rwst** [comment]
I see you don't work with tags. It's not important as one can refer to any version by the commit hash. The only difference is that the link to the respective version on github is more readable. I can just take any commit of GO right before the pull request gets merged, no problem.

**Comment by cmungall** [comment]
@rwst - it sounds like you are using go-edit, which is the artefact tracked in github? We don't recommend this. E.g you won't be getting the reasoned results.

**Comment by rwst** [comment]
@cmungall That is true. Thanks for the hint.

**Comment by rwst** [comment]
The information is now saved at https://github.com/rwst/go-ec-synonyms as a JSON file.
