### ISSUE TITLE
NTR: regulation terms for GO:0070828 and GO:0097240 based on the paper PMID: 31118512

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#20020]
Would like to apply to MRG-1 - paper says that  "MRG-1 [A7DTF0] regulates an H3K9me-independent heterochromatin-anchoring pathway" - please take a look and see what you think. Cheers, Paul

**Comment by pgaudet** [comment]
@Pauldenny Can you please provide the PMID ? We need references to create new terms. 

Thanks, Pascale

**Comment by Pauldenny** [comment]
PMID: 31118512 

Thanks
Paul Denny, PhD
Sent from my mobile, please excuse spelling, brevity
Gene Effects, Farnham Common, Bucks., UK | M: +44-07922078038| L: +44-01753 645754

**Comment by pgaudet** [comment]
GO:0097240 is heterochromatin organization
GO:0097240 chromosome attachment to the nuclear envelope

**Comment by Pauldenny** [comment]
Correction to above: 
GO:0070828 heterochromatin organization
GO:0097240 chromosome attachment to the nuclear envelope

**Comment by krchristie** [comment]
Do you just want the plain regulation terms, e.g.
- regulation of heterochromatin organization
- regulation of chromosome attachment to the nuclear envelope

or do you need the positive and/or negative regulation terms also?

**Comment by Pauldenny** [comment]
Dear Karen,
Please include positive and negative terms, too. Thanks.

Best regards,
Paul Denny, PhD
Sent from my mobile, please excuse spelling, brevity
Gene Effects, Farnham Common, Bucks., UK | M: +44-07922078038| L: +44-01753 645754
