### ISSUE TITLE
Adding channel complex class 

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#20026]
Dear GO curators,

I suggest creating a channel complex as 'Is a' membrane protein complex GO:0098796 and 'part of' GO:0016021. 
There are four recognized classes of transporters: channels, porters, primary active transporters, and group translocators. 
see reference: PMID:10839820

**Comment by pgaudet** [comment]
Also, please change 'ion channel complex' label to 'monoatomic ion channel complex' & definition
