### ISSUE TITLE
GO:0035695    mitophagy by induced vacuole formation, definition insufficient

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20033]
I wondered precisely how this process differed from canonical autophagy  (which ends with engulfment by a lysosome/vacuole)

GO:0035695    mitophagy by induced vacuole formation
Definition (GO:0035695 GONUTS page)
The process in which cells degrade mitochondria by inducing a vacuole-like structure which directly engulfs and degrades the unhealthy mitochondria by accumulating lysosomes. PMID:21264228

and it turns out that the said 'vacuoles'  are 'intramitochondrial, apparently...
induces intramitochondrial lysosome-like organella that plays a critical role in the elimination of oxidized mitochondrial proteins (designated MALM for Mieap-induced accumulation of lysosome-like organelles within mitochondria).

so by this definition I don'tsee how this isn't what is now described as  micromitophagy?

GO:0000424  micromitophagy
Definition 
Degradation of a mitochondrion by lysosomal microautophagy.

(Also GO:0035695 has only a single experimental annotation)

**Comment by pgaudet** [comment]
@marcfeuermann @RLovering @ukemi 

Since you have done this branch, do you have suggestions to improve the definition of this term ?

**Comment by marcfeuermann** [comment]
Hello,
I think in the paper they mention 2 different mechanisms. 

1 - The first is a novel kind of process where lysosome-like organelles accumulate inside the mitochondria. This mechanism is described in PMID:21264221. It is not related to canonical autophagy, so it is an "ATG-independent" process.
The actual discovery paper is PMID:21264221.

I did not find a corresponding term on GO and would create a term like 

Mieap-induced accumulation of intramitochondrial  lysosome-like organelles
or 
Mieap-induced intramitochondrial protein degradation

MALM (synonym)

Definition:
The process in which cells degrade oxidized proteins in unhealthy mitochondria by accumulating lysosome-like organelles within mitochondria in a  Mieap-dependent manner.  PMID:21264221


2 - When MALM was inhibited, Mieap induced vacuole-like structures (designated as MIV for Mieap-induced vacuole), which engulfed and degraded the unhealthy mitochondria by accumulating lysosomes (PMID: 21264228). In my opinion, this process is clearly mitomicrophagy.  
So we could merge the terms, or, if we want to be more cautious, change the term to something like "mitophagy by Mieap-induced vacuole formation" and put it as a child of micromitophagy.

I hope this might be helpful. Some further suggestions are welcome.
Stay safe.
Regards,
Marc.

**Comment by RLovering** [comment]
it's been a long time since I thought about this and I am happy to bow to Marc's more complete knowledge of this area
Ruth

**Comment by ValWood** [comment]
I agree with the merge part.

But do we need a term which included  the gene product name for 
Mieap-induced intramitochondrial protein degradation?

why not just use
GO:0035694   mitochondrial protein catabolic process
?

**Comment by ValWood** [comment]
GO:0035694 mitochondrial protein catabolic process
has only 10 EXP annotations so far, so. new sub process seems a bit overkill right now ;)

**Comment by marcfeuermann** [comment]
MALM is a new kind of process with these intramitochondrial lysosomal-like vesicles and involving several proteins ()not only Mieap), so I thought it could be interesting to have a dedicated term. But of course "GO:0035694 mitochondrial protein catabolic process" makes the job, so yes, lets make the story simple.

**Comment by ValWood** [comment]
OK perhaps it would be useful. 

https://pubmed.ncbi.nlm.nih.gov/?term=MALM+Mieap&sort=date
But there are 7 papers though since 2011 and the first 6 are all the same authors,  but perhaps it is not well-studied. 
Do you know which gene products are involved?
I would like  to see if they are conserved, or if the process is labelled in any other way.

It might be a tricky term to add because they say
PMID: 21264228 
"Mieap, a p53-inducible protein, controls mitochondrial quality by repairing or eliminating unhealthy mitochondria"

but I think we need to look at protein quality control more generally in GO...

**Comment by marcfeuermann** [comment]
I did not get through the literature. I think it is worth to have a closer look. When I will have some time, I will study this more in details and come back to this ticket. It will for sure require more work on the protein quality control in GO.

**Comment by ValWood** [comment]
Closing for now, since a) the term is in the correct place and b) there is no specific action in this ticket.
