### ISSUE TITLE
NTR: antipodal sites

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#20036]
Hi,
Can I request a new term for the antipodal sites please? This term is required to annotate genes with cellular localisation data from the TrypTag project (http://tryptag.org/).

**Accession: GO:xxxxxx
Name: antipodal sites
Ontology: cellular_component
Synonyms: antipodal zones
Definition: The poles of the kinetoplast associated with kinetoplast DNA replication. The antipodal sites flank the kinetoplast DNA disk and are positioned approximately 180 degrees apart. In Trypanosoma brucei and Crithidia fasciculata, minicircles are attached at antipodal sites and they contain enzymes that catalyse some of the later reactions in minicircle replication.
is_a: GO:0020023 ! kinetoplast
Taxonomic restriction: NCBITaxon:5653 ## Kinetoplastea
Source: PMID:8045928, PMID:12455998, PMID:17462016**

Thanks & best wishes,
Achchuthan

**Comment by pgaudet** [comment]
I made the term singular, I hope that's OK ? This is consistent with the ontology editing guidelines. 

+[Term]
+id: GO:0140525
+name: antipodal site
+namespace: cellular_component
+def: "The pole of the kinetoplast associated with kinetoplast DNA replication. The antipodal sites flank the kinetoplast DNA disk and are positioned approximately 180 degrees apart. In Trypanosoma brucei and Crithidia fasciculata, minicircles are attached at antipodal sites and they contain enzymes that catalyse some of the later reactions in minicircle replication." [PMID:12455998, PMID:17462016, PMID:8045928]
+synonym: "antipodal zone" EXACT []
+is_a: GO:0020023 ! kinetoplast
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20036 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-29T08:01:53Z
+

**Comment by Achchuthan** [comment]
Thanks a lot @pgaudet. making it singular makes sense.
