### ISSUE TITLE
NTR: microtubule quartet

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#20035]
Hi,
Can I request a new term for the microtubule quartet please?

**Accession: GO:xxxxxx
Name: microtubule quartet
Ontology: cellular_component
Synonyms: MtQ
Definition: A set of four specialized microtubules that originates from the basal bodies and wraps around the ciliary pocket membrane, likely supporting its distinct flask shape.
is_a: GO:0005874 ! microtubule
Source: PMID:19299460, PMID:32518185, https://www.intechopen.com/books/cytoskeleton-structure-dynamics-function-and-disease/morphological-and-functional-aspects-of-cytoskeleton-of-trypanosomatids**

Thanks & best wishes,
Achchuthan

**Comment by pgaudet** [comment]
@Achchuthan Are there taxon restrictions we should add ?

**Comment by Achchuthan** [comment]
Hi @pgaudet, 
Sorry I forgot to add the taxon restriction. It should be used only for kinetoplastea.

Taxonomic restriction: NCBITaxon:5653 ## Kinetoplastea

Thanks,
Achchuthan

**Comment by krchristie** [comment]
https://www.intechopen.com/books/cytoskeleton-structure-dynamics-function-and-disease/morphological-and-functional-aspects-of-cytoskeleton-of-trypanosomatids
=> **DOI: 10.5772/66859**

**Comment by Achchuthan** [comment]
Hi @krchristie,

Thank you very much for quickly providing this new term. All your changes make sense to me. I really appreciate your help.

Best wishes,
Achchuthan

**Comment by Achchuthan** [comment]
Sorry for my ignorance. I did confuse between "is_a" and "has_part". 
Thanks,
Ach

**Comment by krchristie** [comment]
> Sorry for my ignorance. I did confuse between "is_a" and "has_part".
> Thanks,
> Ach

No worries. There are lots of subtleties. It's taken me a long time to understand some of the relationships. I just wanted to explain why I changed it.
