### ISSUE TITLE
should inositol hexakisphosphate synthase be a synonym of GO:0035299 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20032]
I am looking for a terms for
inositol hexakisphosphate synthase.

The paper I am reading says
Deleting ipk1, the yeast IP6 synthase, abolishes Csn2
interaction with Cul1 in Schizosaccharomyces pombe (Fig. 5G),

but I have ipk1 annotated as
GO:0035299 inositol 1,3,4,5,6-pentakisphosphate (IP5) kinase
by IDA from
Production of IP(6) predominately occurs through phosphorylation of inositol 1,3,4,5,6-pentakisphosphate (IP(5)) by a 2-kinase.
PMID:10960485

So, would it be correct to add
inositol hexakisphosphate synthase
as a synonym of GO:0035299?

**Comment by ValWood** [comment]
what do you think @hdrabkin ? not a big-ee, happy just to close but a synonym might be useful to others.

**Comment by hdrabkin** [comment]
Sometimes these small ones just slip by. Done
