### ISSUE TITLE
inverse parent relation in GO:0140418

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#20030]
It seems something went wrong with the #18689 creation of GO:0140418 because, as you can see, 
```
id: GO:0140418
name: effector-mediated modulation of host process by symbiont
namespace: biological_process
def: "A process mediated by a molecule secreted by a symbiont that results in th
e modulation (either activation or suppresion) of a host structure or process. T
he host is defined as the larger of the organisms involved in a symbiotic intera
ction." [PMID:21467214]
synonym: "effector mediated modulation of host process by symbiont" EXACT []
synonym: "effector triggered modulation of host process by symbiont" EXACT []
synonym: "effector-dependent modulation of host process by symbiont" EXACT []
is_a: GO:0030682 ! mitigation of host defenses by symbiont
```
GO:0140418 is defined as is_a GO:0030682 while it should be vice versa. Please fix.

**Comment by ValWood** [comment]
There is more than one issue here.

I  think work is still in progress to relabel some of these terms from "modulation" to "mitigation"

so 
GO:0140418 effector-mediated modulation of host process by symbiont 
should be
GO:0140418 effector-mediated  mitigation of host process by symbiont 

and it's descendant
GO:0140415    effector-mediated modulation of host defenses by symbiont
should be 
GO:0140415    effector-mediated mitigation of host defenses by symbiont


so  GO:0140415 should be the direct child of 

GO:0030682    mitigation of host defenses by symbiont

and GO:0140418 effector-mediated  mitigation of host process by symbiont 
 should not be an  ancestor of 
GO:0030682    mitigation of host defenses by symbiont
but it should. be a  parent of 
GO:0140418 effector-mediated  mitigation of host process by symbiont 

GO:0075136    response to host

**Comment by pgaudet** [comment]
@ValWood @rwst 
This is what I did for now: 

1. GO:0140415 effector-mediated modulation of host defenses by symbiont  -> added parent class 'GO:0052200 response to host defenses' 
2.  GO:0140418 effector-mediated modulation of host process by symbiont -> added parent class 'GO:0051707  response to other organism'

This now looks like this 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/4782928/94525563-8baf2b80-0234-11eb-97eb-8fb36f981a8e.png">



Let me know if this looks right. 

Thanks, Pascale

**Comment by rwst** [comment]
Thanks!

**Comment by ValWood** [comment]
did you do

and GO:0140418 effector-mediated mitigation of host process by symbiont
should not be an ancestor of
GO:0030682 mitigation of host defenses by symbiont

as not all mitigation of host defenses effector-mediated

@rwst there is still a LOT of consolidation, pruning and refinement  required in the multi-species  branch, but let us know if you spot any more obvious logical inconsistencies
