### ISSUE TITLE
NTR:  histone H3-R8 dimethylation

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#20037]
The modification of H3 by the addition of two methyl groups to arginine at position 8 of the histone. 

Note: There can be symmetrical and asymmetrical dimethylation of H3-R8 and this term is intended to cover both.

is_a GO:0034969 histone arginine methylation

Probably a good reference PMID: 20708585 (asymmetrical)
Pub I am curating PMID:31533925 (symmetrical)

**Comment by pgaudet** [comment]
@cerivs  - and also @colinlog @RLovering @ValWood 
Should we not make those MFs and use BP 'chromatin remodeling' or epigenetic regulation of gene expression?

**Comment by ValWood** [comment]
This should definitely be a molecular function.

However, so far we have always also added the processes to for the histone modifiers, and regulation terms, which are used a lot for complex members which affect  histone methylation levels.  I would be happy to move towards not doing this, but the process terms have a lot of annotations.

Also, this has much futher reaching implications and applies across the board (protein phosphorylation, for example).

**Comment by pgaudet** [comment]
We can add the MF "histone methyltransferase activity (H3-R8specific)" as a child of 
GO:0008469 histone-arginine N-methyltransferase activity

Note there there are 'symmetric' and 'asymmetric' terms, if we want to go to that level of details. 

We will not create the BP's (confirmed with @thomaspd ) 

I will work with @colinlog to move the histone modifications BP to MF's. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140592
+name: histone methyltransferase activity (H3-R8 specific)
+namespace: molecular_function
+def: "Catalysis of the reaction: S-adenosyl-L-methionine + (histone H3)-arginine (position 8) = S-adenosyl-L-homocysteine + (histone H3-N-methyl-arginine (position 8). This reaction is the addition of a methyl group to arginine at position 8 of histone H3." []
+is_a: GO:0008469 ! histone-arginine N-methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20037 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-09T14:13:17Z
