### ISSUE TITLE
New Term Request: DNA double-strand break immobilization

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#20047]
Hello,
In the following paper (PubMed=31548606) the authors show a biological process for IFFO1 (UniProt: Q0D2I5) of "DNA double-strand break immobilization leading to a decrease in DNA translocation".
I would like to know if a term equivalent to “DNA double-strand break immobilization” already exists, otherwise if it could be created?
Thank you,
Lucille

**Comment by ValWood** [comment]
Is this the term you need?

GO:1990683   DNA double-strand break attachment to nuclear envelope

(immobilization is the 'outcome' of the process)

**Comment by LucillePo** [comment]
I will use that GO:1990683 term, it is close enough to the function i need.
Thank you,
Lucille
