### ISSUE TITLE
NTR: bilobe structure assembly

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#20057]
Hi,
Can I request a new term for bilobe structure assembly please? 

**Accession: GO:xxxxxx
Name: bilobe structure assembly
Ontology: biological_process
Synonyms: kinetoplastid flagellar hook complex assembly, bilobe structure formation, bilobe structure biogenesis 
Definition: The assembly and organization of a bilobe structure, a cytoskeletal structure in some kinetoplastid species linking the structures of the ciliary pocket collar and the flagellum attachment zone (aka cilium attachment zone).
is_a: GO:0022607 ! cellular component assembly
part_of: GO:0007010 ! cytoskeleton organization
[RO:0002588 relation] RO:0002588: GO:0120120 ! bilobe structure
Taxonomic restriction: NCBITaxon:5653 ## Kinetoplastea
Source: PMID:18443217, PMID:32675283**

Thanks & best wishes,
Achchuthan

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140528
+name: bilobe structure assembly
+namespace: biological_process
+def: "The assembly and organization of a bilobe structure, a cytoskeletal structure in some kinetoplastid species linking the structures of the ciliary pocket collar and the flagellum attachment zone (aka cilium attachment zone)." [PMID:18443217, PMID:32675283]
+synonym: "bilobe structure biogenesis" EXACT []
+synonym: "bilobe structure formation" EXACT []
+synonym: "kinetoplastid flagellar hook complex assembly" EXACT []
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0120120 ! bilobe structure
+relationship: part_of GO:0007010 ! cytoskeleton organization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20057 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-30T08:47:39Z

**Comment by Achchuthan** [comment]
Thanks a lot @pgaudet.
