### ISSUE TITLE
NTR:paraflagellar rod assembly

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#20053]
Hi,
Can I request a new term for paraflagellar rod assembly please? 

**Accession: GO:xxxxxx
Name: paraflagellar rod assembly
Ontology: biological_process
Synonyms: PFR assembly, paraflagellar rod formation, paraflagellar rod biogenesis 
Definition: The aggregation, arrangement and bonding together of a set of components to form the paraflagellar rod, a large lattice-like axial structure found in some flagellated protists which extends alongside the axoneme.
part_of: GO:0044458 ! motile cilium assembly
is_a: GO:0022607 ! cellular component assembly
Taxonomic restriction: NCBITaxon:33682 ## Euglenozoa
Source: PMID:23787017, PMID:32295845**

Thanks & best wishes,
Achchuthan

**Comment by Achchuthan** [comment]
[RO:0002588 relation] RO:0002588: GO:0097740 ! paraflagellar rod

**Comment by krchristie** [comment]
Here's the term I'm putting in. Let me know if I missed anything.

+[Term]
+id: GO:0120268
+name: paraflagellar rod assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a paraflagellar rod, a large lattice-like axial structure found in some flagellated protists which extends alongside the axoneme." [GOC:ach, GOC:krc, PMID:23787017, PMID:32295845]
+synonym: "paraflagellar rod biogenesis" EXACT []
+synonym: "paraflagellar rod formation" EXACT []
+synonym: "PFR assembly" RELATED []
+is_a: GO:0044458 ! motile cilium assembly
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0097740 ! paraflagellar rod
+created_by: krc
+creation_date: 2020-09-30T17:46:14Z

**Comment by Achchuthan** [comment]
Thanks a lot @krchristie.
