### ISSUE TITLE
NTR: Centrin arm

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#20062]
Hi,
Can I request a new term for the cellular component "centrin arm" please? 

**Accession: GO:xxxxxx
Name: centrin arm
Ontology: cellular_component
Synonyms: antipodal zones
Definition: Rod-shaped protein complex containing Centrin4 protein. The centrin-arm flanks the FAZ filament and the quartet microtubules.
is_a: GO:0032991 ! protein-containing complex
part_of: GO:0020016 ! ciliary pocket
Taxonomic restriction: NCBITaxon:5653 ## Kinetoplastea
Source: PMID:26540076, PMID:31217284**

Thanks & best wishes,
Achchuthan

**Comment by krchristie** [comment]
Hi @Achchuthan 

Here's the term I'm putting in. 
- I thought that it would be better to name the term `ciliary centrin arm` to avoid confusion with any other possible centrin structures.
- I didn't put in the synonym `antipodal zones`. It sounded odd for a synonym for a complex, so I looked a little further and it's not mentioned in PMID:26540076, one of the references you cite for the definition. When I searched for `antipodal zone` in PubMed, it didn't seem like a synonym for `centrin arm`. I can always add it, or any other synonyms, later.
- I expanded the acronym FAZ within the definition.

+[Term]
+id: GO:0120269
+name: ciliary centrin arm
+namespace: cellular_component
+def: "A rod-shaped protein complex containing Centrin4 protein that flanks the flagellum attachment zone (FAZ) filament and the quartet microtubules." [GOC:ach, GOC:krc, PMID:26540076, PMID:31217284]
+comment: Note that cilia and eukaryotic flagella are deemed to be equivalent. In diplomonad species, such as Giardia, the axoneme may extend intracellularly up to 5um away from the plane of the plasma membrane.
+is_a: GO:0032991 ! protein-containing complex
+relationship: part_of GO:0020016 ! ciliary pocket
+created_by: krc
+creation_date: 2020-09-30T18:20:22Z

**Comment by krchristie** [comment]
@pgaudet - So that you can mark it on the rota, I self-assigned this one too and did it at the same time as  **NTR:paraflagellar rod assembly** #20053 since it looked simple.

**Comment by pgaudet** [comment]
ok thanks !

**Comment by Achchuthan** [comment]
Thanks @krchristie & @pgaudet for your help.
