### ISSUE TITLE
GO mappings to obsolete RHEA

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#20061]
This is from @amorgat 
I run my script on the Sept 29 data set
(http://snapshot.geneontology.org/ontology/external2go/rhea2go) and
noticed that we still have 5 GO terms that are mapped on OBSOLETE Rhea.
Would you mind to manage these wrong mapping

RHEA:10515    malate oxidase activity    GO:0019157
    https://beta.rhea-db.org/rhea/10512
    Not enough experimental evidence
RHEA:14252    acetylgalactosaminyl-O-glycosyl-glycoprotein
beta-1,3-N-acetylglucosaminyltransferase activity    GO:0047224
    https://beta.rhea-db.org/rhea/14249
    It duplicates RHEA:46883 / RHEA:46887
RHEA:16552    acetylgalactosaminyl-O-glycosyl-glycoprotein
beta-1,6-N-acetylglucosaminyltransferase activity    GO:0047225
    https://beta.rhea-db.org/rhea/16549
    The entry has been replaced by RHEA:56188 and RHEA:56192
RHEA:17217    glutamate 1-kinase activity    GO:0047944
    https://beta.rhea-db.org/rhea/17217
    This reaction has been shown not to exist
RHEA:21168    anthranilate 3-monooxygenase activity    GO:0050478
    https://beta.rhea-db.org/rhea/21168
    This reaction has been shown not to exist

**Comment by hdrabkin** [comment]
No annotations exist to GO:0050478
No annotations exist to GO:0047944
1 annotation (TAS) to GO:0019157
7 annotations to GO:0047225, 2 experimental, 5 IEA
2 IEA annotations to GO:0047224

**Comment by hdrabkin** [comment]
All obsolete RHEAs removed.
3 termed (with * above) marked for obsoletion

Two GO terms get two children and mapped to appropriate RHEA
+[Term]
+id: GO:0106325
+name: acetylgalactosaminyl-O-glycosyl-seryl-glycoprotein beta-1,6-N-acetylglucosaminyltransferase activity
+[Term]
+id: GO:0106326
+name: acetylgalactosaminyl-O-glycosyl-threonyl-glycoprotein beta-1,6-N-acetylglucosaminyltransferase activity
+[Term]
+id: GO:0106327
+name: acetylgalactosaminyl-O-glycosyl-threonyl-glycoprotein beta-1,3-N-acetylglucosaminyltransferase activity
+[Term]
+id: GO:0106328
+name: acetylgalactosaminyl-O-glycosyl-seryl-glycoprotein beta-1,3-N-acetylglucosaminyltransferase activity

**Comment by hdrabkin** [comment]
These terms need to be obsoleted since RHEA claims they don't exist
GO:0050478
GO:0047944
GO:0019157

**Comment by pgaudet** [comment]
Only GO:0019157 has one TAS, should be OK to obsolete 

PCK1 P05153


Thanks, Pascale

**Comment by hdrabkin** [comment]
I also found out that the existing ECs to to of those terms has also been withdrawn, but still appears in public Ec for now.

**Comment by amorgat** [comment]
2020-10-01: EC 1.14.16.3 and EC 2.7.2.13 are still available in ENZYME@ExPASy but are deleted entries in ExPlorEnz 
https://www.enzyme-database.org/query.php?ec=1.14.16.3
https://www.enzyme-database.org/query.php?ec=2.7.2.13
@kaxelsen confirmed that both deletions will become public in the next release (2020_05, Oct 7th)

**Comment by hdrabkin** [comment]
Terms obsoleted.
