### ISSUE TITLE
Some taxon contraints still incorrect

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20079]
Hello, 

In this report: 
http://release.geneontology.org/2020-05-02/reports/goa_chicken-report.html#gorule-0000013

This line is a false positive: 
ERROR - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- UniProtKB O93574 RELN GO:0021800 GO_REF:0000024 ISS UniProtKB:Q60841 P Reelin RELN protein taxon:9031 20091116 UniProt

GO:0021800 taxon constraints should allow this annotation in Chicken. 

Can you please check what's going on ? 

Thanks, Pascale

**Comment by kltm** [comment]
@dougli1sqrd If this is seen in the release, I think we're done here, yes?

**Comment by ValWood** [comment]
calling doug 
> @dougli1sqrd If this is seen in the release, I think we're done here, yes?

**Comment by dougli1sqrd** [comment]
@kltm @ValWood yes, definitely! I'll close.
