### ISSUE TITLE
Question about high-affinity and low-affinity transporter classes

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#20077]
Dear GO creators,

What are the transport system that high-affinity and low-affinity transporters perform,  active transport or carrier proteins facilitated diffusion ? 

In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations. for substances to move against their concentration gradient, primary or secondary energy is required.
In low-affinity transport the transporter is able to bind the solute only if it is present at very high concentrations. For substances to move along their concentration gradient, a facilitated diffusion transporter is required.

Does this mean all high-affinity transport processes occur through active transport and low-affinity transport process occur using carrier proteins?

Example of classes
low-affinity L-arginine transmembrane transporter activity, GO:0097626
high-affinity glutamate transmembrane transporter activity, GO:0005314

**Comment by ValWood** [comment]
I notice nobody has answered this. 
I don't think so. We have examples of high affinity transporters  in the same family.

It seems to be an open question.
These papers look interesting in this respect
https://www.frontiersin.org/articles/10.3389/fpls.2019.01797/full
https://www.nature.com/articles/s41598-018-23528-7#:~:text=We%20argue%20that%20the%20main,only%20the%20extracellular%20side%20is.
