### ISSUE TITLE
Parent term: transmembrane transport from lysosomal lumen to cytosol

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#20070]
Could I request the parent term:
"transmembrane transport from lysosomal lumen to cytosol"

for these terms?

transmembrane L-lysine transport from lysosomal lumen to cytosol
transmembrane L-histidine transport from lysosomal lumen to cytosol
transmembrane L-cystine transport from lysosomal lumen to cytosol
L-arginine transmembrane transport from lysosomal lumen to cytosol (NB this one has a term name that is inconsistent with its friends)

Suggested def: "The directed movement of a solute from the lysosomal lumen across the lysosomal membrane and into the cytosol."

Ref:PMID:26631267
GOC:ha

**Comment by hdrabkin** [comment]
Assuming 
: | GO:1902475 is parent of NT

**Comment by hattrill** [comment]
I see: GO:1902475 L-alpha-amino acid transmembrane transport 

Hmmmm.....not for what I am thinking. I am more interested in the "transport from lysosomal lumen to cytosol" rather than the substrate. 
(I am looking a weird derivative movement - not sure whether the transporter's job is to kick out aa derivatives or the big bit of modification on the side, so I am sticking to "soluble" as a sure bet and where it does its job).

These child terms listed just happen to have L-aa substrates.....

lysosomal transport GO:0007041 was parental thinking.

**Comment by edwong57** [comment]
These child terms ended up moving under the new parent term. I also renamed "L-arginine transmembrane transport from lysosomal lumen to cytosol" to "transmembrane L-arginine transport from lysosomal lumen to cytosol " so that it matched the related terms.
![image](https://github.com/user-attachments/assets/57a8eb66-2ef7-443a-a3c1-a8542ae82076)

**Comment by pgaudet** [comment]
HI @edwong57 

Thanks for pointing this out. The [Design Pattern](https://github.com/geneontology/go-ontology/blob/d449265cdcade8adbc60ea8f6161eed4b2d39553/src/design_patterns/transmembrane_transport.yaml-disabled) states that the term label should be  "%s transmembrane transport"
so "L-cysteine transmembrane transport from lysosomal lumen to cytosol' would be more consistent. 

Can you change all the non compliant terms? 

Thanks, Pascale
