### ISSUE TITLE
question about  spliceosomal complex disassembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20076]
hi @krchristie 
is there any reason why 

GO:0000390 | spliceosomal complex disassembly
isn't part of splicing?

**Comment by ValWood** [comment]
also
GO:0000395 mRNA 5'-splice site recognition

**Comment by krchristie** [comment]
`spliceosomal complex disassembly (GO:0000390)` is already part of splicing:

![20201009-spliceosomalComplexDisassembly](https://user-images.githubusercontent.com/10533218/95628946-e1a18180-0a33-11eb-91d1-03446199d85c.png)
