### ISSUE TITLE
missing ancestor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20087]
+id: GO:0140497
+name: mannan polymerase II complex

needs ancestor
alpha-1,6-mannosyltransferase complex GO:0000136;

**Comment by pgaudet** [comment]
GO:0000136 term label is   mannan polymerase complex, according to what you requested here: https://github.com/geneontology/go-ontology/issues/19817#issuecomment-662394716

So the parentage of GO:0140497 is OK. 

Thanks, Pascale

**Comment by ValWood** [comment]
term label is correct.

Ancestor is missing as per
Descendants of
ID | GO:0000136
Term name | alpha-1,6-mannosyltransferase complex

**Comment by pgaudet** [comment]
Sorry I still dont get it. 

<img width="305" alt="image" src="https://user-images.githubusercontent.com/4782928/95726476-46015280-0c79-11eb-877c-96f644d56e91.png">


Please skype me ! 

Pascale

**Comment by ValWood** [comment]
sorry its fine!
