### ISSUE TITLE
Change to "beta-alanyl-dopamine synthase activity" name & def (GO:0003833)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20086]
We have this term:
id: GO:0003833
name: beta-alanyl-dopamine synthase activity
namespace: molecular_function
def: "Catalysis of the synthesis of beta-alanyl-dopamine from the precursor dopamine (3,4-dihydroxyphenylethylamine)." [GOC:bf, ISBN:0198506732, PMID:12957543]
synonym: "N-beta-alanyl dopamine synthetase activity" EXACT []
synonym: "NBAD transferase activity" EXACT []
is_a: GO:0016874 ! ligase activity

The only annotations are IDA annotations to the D. melanogaster 'ebony' gene and IEA annotations to its orthologs in other Drosophila species. So the term only really exists to annotate this single gene/protein (at present).

Although 'ebony' was originally identified as a 'beta-alanyl-dopamine synthase', subsequent work showed that a broader variety of biogenic amines are accepted to form the relevant beta-alanyl-amine product (see PMID:12900414, 19715698, 25229196.). E.g. histamine converted to beta-alanyl-histamine.

Thus, I think the current GO:0003833 term name and definition should be broadened to something like:
name: beta‐alanyl biogenic amine synthase activity
def: "Catalysis of the synthesis of a beta‐alanyl amine conjugate from a precursor biogenic amine, such as dopamine or histamine." [PMID:12900414, PMID:25229196]

**Comment by sjm41** [comment]
Hi @hdrabkin, @pgaudet 

I realise another complication here is that "β-alanyl-biogenic amine synthetase" catalyses a two-step reaction, as shown in Fig 2 of PMID: 12900414 (screenshot attached).

First step: The A-domain of holo-Ebony activates β-alanine as aminoacyladenylate at the expense of ATP and subsequently transfers it onto the thiol group of the P-pant thiolation domain.

Second step: In the next step, the amine group of dopamine [though other substrates are accepted, as noted above] performs a nucleophilic attack onto the thioester of the Ebony-bound β-alanine that might be catalyzed by the putative amine-selecting domain. This leads to the formation of β-alanyl-dopamine.

![Screenshot 2021-11-15 at 12 21 14](https://user-images.githubusercontent.com/16306861/141781204-ad572b7c-a459-412b-83c4-5041ecc335f1.png)

First step seems to be a "ligase activity, forming carbon-sulfur bonds GO:0016877" (or child thereof)
Second step seems to be a "ligase activity, forming carbon-nitrogen bonds  GO:0016879" (or child thereof)

How is this best handled?  Similar to https://github.com/geneontology/go-ontology/issues/21024??

**Comment by hdrabkin** [comment]
Quickly looking over coffee; there is a lot of things wrong with this term I think. Definition is more akin to a process term. 

So this reminds me of aminoacyl-tRNA synthetases
overall reaction: amino acid + ATP + tRNA = aa-tRNA + AMP + PPi
In the absence of a tRNA, the reaction yields activated amino acid (aa-AMP); this is consistent with classification as a ligase. 
RHEA does not list separate reactions but just lists the 'total' reaction.  See for example Tryptophanyl-tRNA synthetase, (RHEA:24080)

Thus, 
Beta-alanine + ATP + dopamine = beta-alanyl-dopamine + AMP + PPi. 
I think the apo-ebony  to holo-ebony  step is a separate step with separate enzyme  P-pant transferase. 

I guess that, like the aa-tRNA synthetases, the question is if beta-alanyl-AMP is only 'seen' in the absence of dopamine?

**Comment by sjm41** [comment]
Thanks Harold - that's useful.

I ended up back at this ticket from looking at a related mouse protein - I was trying to annotate fly Aasdh (Q9VLL0) based on knowledge of the mouse ortholog (https://www.uniprot.org/uniprot/Q80WC9) coming from https://pubmed.ncbi.nlm.nih.gov/24467666/.  UniProt has that mouse protein annotated with EC:6.2.1.- (acid-thiol ligase activity) with the description "Covalently binds beta-alanine in an ATP-dependent manner to form a thioester bond with its phosphopantetheine group and transfers it to an as yet unknown acceptor via an amide bond. "

So both 'ebony' and 'Aasdh' seem to do the 'beta-alanine activation' thing, but the acceptor(s) is only known for ebony.

Not sure this helps....

**Comment by deustp01** [comment]
A priori, isn't the critical issue the number of distinct chemical steps involved? The fact that the acceptor is sometimes unknown would be irrelevant if, known or not, it gets converted to derivatized unknown acceptor in a single step as GO defines "single".

**Comment by hdrabkin** [comment]
@deustp01 , I was using the 'logic' as I understand RHEA using it to decide on whether to make separate reactions to argue not making a separate beta-alanine activation step.

**Comment by sjm41** [comment]
So, if we stick with one GO term for the activity of 'ebony', then it would still be classified as a ligase (as now), right?  But more specifically, it should be move to be a child of "ligase activity, forming carbon-nitrogen bonds (GO:0016879)", maybe even "acid-amino acid ligase activity (GO:0016881)"?
Then, we should generalise the name and def to cover all biogenic amines (not just dopamine) and reword the def to sound less like a process.

Sound OK?

Not sure how best to annotate the Aasdh proteins.....

**Comment by sjm41** [comment]
@hdrabkin Just to itemise my proposal/request:
1. Rename GO:0003833 term name to "beta‐alanyl amine synthase activity"
2. Change GO:0003833 def to "Catalysis of the synthesis of a beta‐alanyl amine conjugate from a precursor biogenic amine, such as dopamine or histamine." [PMID:12900414, PMID:25229196]"
3. Move GO:0003833 to be child of "ligase activity, forming carbon-nitrogen bonds (GO:0016879)"or "acid-amino acid ligase activity (GO:0016881)" (advice needed here)

Thanks.

**Comment by hdrabkin** [comment]
@pgaudet Policy: here we are changing both name and def;   Should there be an obsoletion?

**Comment by pgaudet** [comment]
There should only be an obsoletion if it makes the annotations invalid. Looks like the new definition is not *that* different from what it used to be.

**Comment by hdrabkin** [comment]
Ok, just checking

**Comment by hdrabkin** [comment]
GO:0016881 appears to ligate one amino acid or other acid to an amio acid (see children); so I would go with GO:0016879

**Comment by hdrabkin** [comment]
done.

**Comment by sjm41** [comment]
Thanks!

**Comment by sjm41** [comment]
Hi @hdrabkin Just noticed a couple of errors in the definition of this.

Current:
Catalysis of the synthesis of beta-alanyl amine conjugate from a precursor biogenetic amine, such as dopamine or histamine. PMID:12900414 PMID:12957543 PMID:25229196 

Should be:
Catalysis of the synthesis of _**a**_ beta-alanyl amine conjugate from a precursor _**biogenic**_ amine, such as dopamine or histamine.

**Comment by hdrabkin** [comment]
fixed

**Comment by sjm41** [comment]
Thanks!
