### ISSUE TITLE
'viral process' may need a different parent class

### ISSUE THREAD

**Issue by dillerm** [geneontology/go-ontology#20084]
It occurred to me that not all viral processes are going to be directly involved in a symbiotic interaction. Two examples that are child classes of 'viral process' are 'viral life cycle' (GO:0019058) and 'virus maturation' (GO:0019075). I'm not entirely sure of a better parent class for it yet, but I'm leaning toward 'biological_process' being the best one.

**Comment by pgaudet** [comment]
@pmasson55 thoughts ?

**Comment by pgaudet** [comment]
I will move 'viral process' directly under 'biological process'. 
@mgiglio99 @ValWood @dsiegele
