### ISSUE TITLE
'multi-species biofilm formation' has double inheritance

### ISSUE THREAD

**Issue by dillerm** [geneontology/go-ontology#20085]
This class currently has ‘symbiotic process’ and ‘biofilm formation’ as parent classes. I would recommend removing the **subClassOf 'symbiotic process'** axiom since this process does not directly involve the interaction between the host and the symbiont. You can always add an axiom that asserts that this is part of some ‘symbiotic process’ if you want to relate it back to that class.

**Comment by pgaudet** [comment]
@srengel @ValWood  @marekskrzypek 

Isn't this siimlar to coflocculation, that we determined a few weeks back was not a specific process, but just the consequence of many different organisms present in the same place ?  See #20192

See for example http://amigo.geneontology.org/amigo/reference/PMID:17510860

There are several terms, but only 10 EXP annotations by CGD

The terms are: 

-  GO:0044399 multi-species biofilm formation
-  GO:0090608 multi-species submerged biofilm formation
-  GO:0090607 multi-species surface biofilm formation 
- (part of)  GO:0043710 cell adhesion involved in multi-species biofilm formation


What do you think ? 

Thanks, Pascale

**Comment by marekskrzypek** [comment]
I am not an expert on multispecies biofilms, but people who study them seem to think there is a specific set of proteins involved in their formation. It doesn’t sound like simply a bunch of cells from different species stuck in the same place. See https://pubmed.ncbi.nlm.nih.gov/24736223/

Cheers,
Marek

**Comment by ValWood** [comment]
Perhaps we only need a single term under
GO:0044403    biological process involved in symbiotic interaction
along the lines of 
"cell-adhesion involved in multi-species interaction"
for all of these co-flocculating, biofilm formation terms?

It isn't totally clear that it is an evolved function, but  difficult to rule out based on current information.

**Comment by pgaudet** [comment]
Thanks everyone for the comments. I agree  there may be too many terms. The one annotated term however is 'GO:0043710 cell adhesion involved in multi-species biofilm formation'  -> probably a merge into GO:0044399 multi-species biofilm formation would be OK ? 

Thanks, Pascale

**Comment by marekskrzypek** [comment]
I agree there are too many terms here (awful amount of hair-splitting 😉).  I think it would be OK to merge those two terms. Distinguishing between them is problematic anyway..

Thanks,
Marek
