### ISSUE TITLE
Revise definition 'adhesion of symbiont to host' 

### ISSUE THREAD

**Issue by dillerm** [geneontology/go-ontology#20082]
This is currently a subclass of 'symbiotic process' and is defined as:

> The attachment of a symbiont to its host via adhesion molecules, general stickiness etc., either directly or indirectly. The host is defined as the larger of the organisms involved in a symbiotic interaction.

First, I think the proper parent class for this is either going to be 'movement in host environment' or 'interaction with host'. Whatever the decision is for where to move it, I think the definition needs to be edited to reflect what the parent class is. My recommendation is:

> An X in which a symbiont attaches to its host via adhesion molecules, general stickiness etc., either directly or indirectly. The host is defined as the larger of the organisms involved in a symbiotic interaction.

Here, 'X' represents the label for the parent class.

**Comment by pgaudet** [comment]
Need to move 'adhesion of symbiont to host' under 'biological process involved in interaction with host'
