### ISSUE TITLE
'growth of symbiont within host' has double inheritance

### ISSUE THREAD

**Issue by dillerm** [geneontology/go-ontology#20083]
This class currently has ‘symbiotic process’ and ‘growth’ as parent classes. I would recommend either making it a subclass of 'interaction with host' (see Issue #19982 ) or removing the **subClassOf 'symbiotic process'** axiom since this process does not directly involve the interaction between the host and the symbiont.

**Comment by dillerm** [comment]
'reproduction of symbiont in host' also runs into this problem.

**Comment by pgaudet** [comment]
those classes will likely be obsoleted.

**Comment by ValWood** [comment]
I thought we had a ticket about this, but I can't find it....

**Comment by pgaudet** [comment]
Hi @dillerm 

This is covered by #19431 

I'll close this one as a duplicate. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Duplicate with #20273 and #20203
