### ISSUE TITLE
EKC/KEOPS complex (GO:0000408) name/synonyms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20095]
From PMID: 25629598 (from 2014):
"we recommend naming the bacterial TsaBDE complex as well as the archeal/eukaryotic KEOPS/EKC complex to Threonyl-carbamoly Transferase Complex (TCTC), which will be in keeping with nomenclature of other members of the carbamoyl transferase family. "

- So, we should at least add "Threonyl-carbamoly Transferase Complex" and "TCTC" as synonyms to GO:0000408
- may even want to consider renaming the GO term

**Comment by hdrabkin** [comment]
Synonyms added; no name change unless @ValWood  confers (as she was the original requester on the term, or at least was added as GOC:vw

**Comment by ValWood** [comment]
I think "EKC/KEOPS complex" (or just KEOPS) should stay as the primary name because everyone calls it this.

Threonyl-carbamoly Transferase Complex 3 results Google whereas "KEOPs complex" ~15000

Also add  KEOPS/EKC for searching.

**Comment by hdrabkin** [comment]
Thanks @ValWood
