### ISSUE TITLE
Map BP to YeastPathway database

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#20091]
This will allow us to create GO-CAMs from yeastpathways

I will add more details later...

**Comment by cmungall** [comment]
- matches: https://github.com/geneontology/go-mappings/blob/main/target/obomatch-go-yeastpathway.sssom.tsv
 - unmatched: https://github.com/geneontology/go-mappings/blob/main/target/nomatches-go-yeastpathway.tsv

**Comment by cmungall** [comment]
@goodb the biopax3 files for yeastpathways (BioCyc style) are here:

https://github.com/geneontology/go-mappings/blob/main/downloads/yeastpathways.ttl.gz

Note that the biopax files by and large do not have GO xreffed. We'd supplement using the mappings I generated above. It may be best to wait til we have a pass at filtering the junk out the mappings. But if you wanted to do an experiment, we could try taking all mappings with a confidence > 0.5 and see what comes out

I think this should be an easy win

**Comment by goodb** [comment]
Would also want to map from http://brg.ai.sri.com/evidence-ontology/ to ECO .

**Comment by goodb** [comment]
And need mappings for proteins like YeastCyc:YAL054C-MONOMER  (though we can make it sort of work via the REACTO entity ontology approach).  See https://biocyc.org/gene?orgid=YEAST&id=YAL054C-MONOMER

**Comment by goodb** [comment]
@cmungall it does us chebi terms and stoichiometry for inputs/outputs of reactions.  If we had rhea-based logical definitions for GO MF we could infer MF from these.

**Comment by goodb** [comment]
@cmungall where did you get the biopax file from?  It has weirdness that is causing the paxtools loader to fail.

**Comment by cmungall** [comment]
> Would also want to map from http://brg.ai.sri.com/evidence-ontology/ to ECO .

make an eco ticket? Doesn't seem this is used in the biopax? is it used at all? Wow, it's a daml+oil ontology...

**Comment by cmungall** [comment]
> where did you get the biopax file from? It has weirdness that is causing the paxtools loader to fail.

The SGD curators made an export to a dropbox folder, I concatenated the files together with jena. I figured we could collect server questions for them at once rather than. piecemeal

**Comment by cmungall** [comment]
Proteins: yes, need to link

Note this is from yeastpathways not biocyc (I don't know if the content in synced or merged):

https://pathway.yeastgenome.org/gene?orgid=YEAST&id=YAL054C-MONOMER

There is an SGD xref there but I don't see S000000050 in the biopax... another Q for them

**Comment by goodb** [comment]
@cmungall could you point me to the original files?  It will be easier for me to zip through them then debugging the merged file for paxtools?  

There is actually a lot of use of the SRI evidence ontology in here.  If you open it up in protege and look for instances of UtilityClass/Evidence you will see them.  Using the BioPAX-specific avoidance of using IRIs for identifiers (which is just wonderful to see inside a purportedly OWL file..).  https://github.com/evidenceontology/evidenceontology/issues/263   

<img width="659" alt="Screen Shot 2020-10-08 at 1 07 56 PM" src="https://user-images.githubusercontent.com/2086122/95508150-65da0300-0967-11eb-85c5-7410c3e003b5.png">

**Comment by goodb** [comment]
It basically works.  No real problems with the biopax.  Got one MF from EC xref.  The other reaction had an EC but no xref found.  If we get the eco mapping done we will actually have better evidence for this one than for reactome - which is all just computational inference with the pathway id as the source.  

![Screen Shot 2020-10-09 at 2 56 19 PM](https://user-images.githubusercontent.com/2086122/95634887-c76da080-0a3f-11eb-90f3-ed686fc686ed.png)

**Comment by goodb** [comment]
@cmungall the status here is that the approach followed with Reactome works - as demonstrated above.  There are two paths forward from there:

1. We commit to that approach and include the YeastCyc entity ontology alongside the REACTO entity ontology 
2. We adapt the code to try to make it use NEO and chebi classes directly rather than the subclasses created in REACTO/YEASTO

Advantage to 1. is that it requires no changes to current code - just some tweaks to the pipeline commands.  Advantage to 2. is that the results will look much more like the rest of the Noctua-generated models and will thus likely be a little easier to deal with in some regards.  

Regardless we will also need to decide what the gene ids are that we want - e.g. if we want GPAD export from these models.  The BioPAX comes with yeast cyc ids like YeastCyc_YHL032C-MONOMER https://yeast.biocyc.org/gene?orgid=YEAST&id=YHL032C-MONOMER .   I'm guessing that we at least want these mapped to SGD ids like SGD:S000001024 https://www.yeastgenome.org/locus/S000001024 but we could also go all the way to UniProt.  I think this is up to SGD.  

Perhaps SGD could conduct their preferred mapping prior to or during the BioPAX generation process?  Ping @srengel ?

**Comment by goodb** [comment]
A first cut conversion has been uploaded to noctua-dev. (See commit https://github.com/geneontology/noctua-models/commit/0719078ebd46233fa4d92c92fefbcd3509e66735 ).  

We've noticed that some models seem to be missing information as compared to their equivalents on https://pathway.yeastgenome.org .  For example, we see only two reactions in http://noctua-dev.berkeleybop.org/editor/graph/gomodel:THRESYN-PWY but quite a few more in https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?object=THRESYN-PWY 
When we download the biopax file directly from the website for THRESYN-PWY it appears to have all of the missing content.  Comparing it to the THRESYN-PWY provided to start this experiment, the provided file matches what we see in the conversion and is missing the other reactions.  It looks like the files provided in the Stanford Box are either out of date with respect to the yeastgenome site or somehow something went wrong during their export.  Ping @srengel

**Comment by goodb** [comment]
FYI, to browse the converted pathways, go to  http://noctua-dev.berkeleybop.org and type Saccharomyces Genome Database into the title filter field.

**Comment by srengel** [comment]
eek, is it only the one pathway?  or is this just an example and it's actually lots of pathways?

**Comment by cmungall** [comment]
> is it only the one pathway? or is this just an example and it's actually lots of pathways?

We don't really have an automated way of telling this, we'd have to manually look at each one

**Comment by suzialeksander** [comment]
It looks like the Dropbox biopax are out of date.  Please stop using those and we'll let you know when there are updated files available @cmungall @dustine32

**Comment by srengel** [comment]
just to add numbers, of the >200 pathways, 62 were edited after the files were generated.  so we need a fresh set for sure!

**Comment by srengel** [comment]
Edith is generating a fresh set of biopax3 files for us, will let you know when we have them.

**Comment by suzialeksander** [comment]
It looks like we've added the updated files to the Dropbox.  It's the same location, just with new files.

**Comment by cmungall** [comment]
Thank you! @dustine32 will take t from here

**Comment by dustine32** [comment]
@suzialeksander @srengel Noting an issue spotted by @cmungall that the file uses the species taxon ID 4932 rather than strain taxon ID 559292 used in the SGD GAF:
```
###  http://pathway.yeastgenome.org/YEAST/pathway-biopax?type=3%38object=ACETATEUTIL2-PWY#UnificationXref778656
:UnificationXref778656 rdf:type owl:NamedIndividual ,
                                <http://www.biopax.org/release/biopax-level3.owl#UnificationXref> ;
                       <http://www.biopax.org/release/biopax-level3.owl#db> "NCBI Taxonomy" ;
                       <http://www.biopax.org/release/biopax-level3.owl#id> "4932" 
```

This will likely cause ShEx/labeling issues in Noctua because the SGD GAF and thus Neo uses the strain ID 559292 (as does uniprot).

**Comment by suzialeksander** [comment]
@dustine32 and anyone else who needs it, the biopax files are at 

https://stanford.app.box.com/s/mhywvmcgmd9s7hfqnhllzt0mpe3ypc1s

We looked through these a little more carefully, there's a URL in the header (yeastgenome.org) that needs to be cleaned up so we'll be remaking these shortly. 

We didn't see the taxon in level3 files, but did find the 4932 in the level2 file 

> XMLSchema#string">4932</bp:ID>
                        <bp:DB rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCBI Taxonomy</bp:DB>

Would it be acceptable to do a global replace in the files to simply change all taxon references to 559292?  It would take quite some digging to figure out where the 4932 is coming from and change that from the source.

**Comment by goodb** [comment]
Hi GO!  Suggest that you just pull the taxon information out of NEO based on the genes present in the pathway during the conversion process.  No other annotation is really needed and that accounts for cases where pathways may contain genes from multiple species interacting.  I think I started coded to do that but can't remember where it stands right now.

**Comment by dustine32** [comment]
Thanks @goodb for the response! Yes, it looks like with the code you have to map entities in biopax to the gene IDs in NEO (e.g. SGD) we shouldn't have to worry about parsing the taxon out of biopax. The taxon data in whatever NEO is loaded into the Noctua stack will serve up the correct taxon ID. Hopefully this makes sense but feel free to set me straight if not!

**Comment by dustine32** [comment]
@suzialeksander Don't worry about updating the taxon IDs in the biopax files (you're right, they're not present anyway in the level3 files currently in the dropbox, which is OK). But you might want to still dig into the source of the these biopax entity taxon IDs (4932) to align with the taxons used in the SGD GAF (559292) since the issue may pop up again elsewhere.

**Comment by goodb** [comment]
@dustine32 cool.  There is code in Minerva that can add taxon information to go_cams based on the genes in the go_cam.  You ought to be able to use that to get this done.

**Comment by cmungall** [comment]
OK, seeing issues with some of the models, thanks to @lpalbou for pointing this out

http://noctua-dev.berkeleybop.org/editor/graph/gomodel:YEAST-SALV-PYRMID-DNTP#

Look at URK1 - 

![image](https://user-images.githubusercontent.com/50745/112762998-79316700-8fb7-11eb-886b-45989ec928d0.png)

so many GO MFs! Doesn't this fail shex?

I suspect this is partly due to multiple ECs on the one reaction?

In 
https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=NIL&object=YEAST-SALV-PYRMID-DNTP&redirect=T
in particular, this reaction:
https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=REACTION&object=RXN-14093
there are 3 ECs for one RXN. This still doesn't explain how many we have in the GO-CAM - you you investigate @dustine32 ?

**Comment by deustp01** [comment]
Naive biochemistry/bookkeeping question: the gene product, URK1, that enables this reaction appears to have broad substrate specificity, and may pick up a different EC number for each of its possible substrates, as shown on [this SGD pathways page](https://pathway.yeastgenome.org/gene?orgid=YEAST&id=YNR012W-MONOMER). But the reaction that is annotated here involves only one of those substrates, so why is it picking up all of the EC's?

**Comment by dustine32** [comment]
@cmungall Yep, looking into this right now. But @thomaspd gets all the points for first pointing this out to me last Friday!

I've debugged some of the reaction's multiple activities to having multiple EC numbers in the BioPAX as @deustp01 suggested. But I'm not certain yet whether Ben's code was meant to select only one of these. A couple suspected reasons that can quickly be ruled out:
1. Data change - For this example model YEAST-SALV-PYRMID-DNTP, did the previous loaded model source BioPAX have multiple EC numbers per reaction? I'll check the older files I have.
2. Code change - I made a [slight change](https://github.com/geneontology/pathways2GO/commit/c7d80f236b17c238e4b15df142940ea697aee623) to help correct entity mappings. This may have shifted how the EC numbers are processed. I'll try a quick reversion test to see if this corrects it.

**Comment by ukemi** [comment]
I thought the Reactome code looked at the asserted MFs that were assigned by Reactome, not an EC xrefs.

**Comment by deustp01** [comment]
My recollection is that Ben's code expects to find only one MF in a reaction (Reactome) / activity unit (GO-CAM), and it can't rely on EC numbers because we don't provide tehm.. More concretely, I definitely spent a chunk of time working through lists of Reactome reactions that did not yield proper GO-CAM activity units because the Reactome reaction was associated with more than one catalystActivity intance (a catalystActivity instance associates a physical entity protein or complex) with a GO MF catalysis term).

**Comment by dustine32** [comment]
OK, I just ruled out suspected reason 2 from above (code change). The previous code produces the same multi-MF reaction behavior.

Thanks @ukemi and @deustp01 for confirming the single-MF intent! I see in the source BioPAX file (YEAST-SALV-PYRMID-DNTP available at https://stanford.app.box.com/s/mhywvmcgmd9s7hfqnhllzt0mpe3ypc1s?page=11) the above BiochemicalReaction controlled by URK1 has three `eCNumber` annotations: `2.7.1.-`, `2.7.1.74`, and `2.7.1.145`. I'm guessing the correct activity for this reaction should be deoxycytidine kinase activity (GO:0004137)?

**Comment by deustp01** [comment]
> I'm guessing the correct activity for this reaction should be deoxycytidine kinase activity (GO:0004137)?

Yes -  GO:0004137 deoxycytidine kinase activity "Catalysis of the reaction: NTP + deoxycytidine = NDP + CMP."

**Comment by dustine32** [comment]
Thanks @deustp01 !

**Comment by ukemi** [comment]
Note that we might also want to open an ontology ticket.
GO:0004137 deoxycytidine kinase activity "Catalysis of the reaction: NTP + deoxycytidine = NDP + CMP."

is_a

GO:0019136 deoxynucleoside kinase activity Catalysis of the reaction: ATP + 2'-deoxynucleoside = ADP + 2'-deoxynucleoside 5'-phosphate.

Unless ATP and ADP are specified in the child, this is a true path. @deustp01 do you know any cases where ATP is not the phosphate donor?

**Comment by deustp01** [comment]
> do you know any cases where ATP is not the phosphate donor?

According to [this paper](https://pubmed.ncbi.nlm.nih.gov/23215245/), they are rare but do exist, but these rarities include CK2, MEK, and BRAF according to the abstract (all I've read). Need to read more, to try to figure out whether this is physiologically relevant.

**Comment by cmungall** [comment]
@dustine32 - what is your general approach to this problem? Find the MRCA of the GO function terms mapped from EC?

I was looking at this pathway in more detail to see how well it aligned with existing GO annotations to the corresponding GO BP... it's hard...

**Comment by dustine32** [comment]
@cmungall I didn't immediately think to look at the GO annotations but that could be a way.

Could we ask SGD (@suzialeksander) to just export the one correct EC number for each reaction? But then, are EC numbers only ever mapped to just one GO term?

A cooler route would be to match input/output entities to GO term logical definitions or something, though the LDs probably aren't all in place. Or perhaps there may be some code already in place that matches these entities' labels to activity labels that is breaking down somehow (e.g. "2'-deoxycytidine" against "NTP + deoxycytidine = NDP + CMP")? Still debugging this...

**Comment by dustine32** [comment]
Oh I see. @cmungall To answer your "3 ECs vs 12 MFs" question, for RXN-14093 we have this many MFs because some EC numbers _do_ xref to multiple GO terms:

`2.7.1.74`: GO:0004137
`2.7.1.145`: GO:0019136
`2.7.1.-`: GO:0019914, GO:0008607, GO:0010276, GO:0016538, GO:0016773, GO:0032942, GO:0033785, GO:0034071, GO:0043798, GO:0052835

**Comment by cmungall** [comment]
@dustine32 - that's right, but I think your suggestion of simply fixing these at source is best! I don't know how easy this is to do. But it would probably be best for curators if we could automatically provide a list of all issues to help us get the scale of the problems, rather than doing ad hoc as we find them!

**Comment by ukemi** [comment]
@deustp01, I think these would be ok as they are not children of the nucleotide kinase term.

**Comment by deustp01** [comment]
> I think your suggestion of simply fixing these at source is best!

That was the approach that worked for the Reactome-to-GO-CAM conversion. There it was manual and depended on a close interaction between the developer doing the conversion (Ben Good) and a curator with access to the source data (me) and involved some custom analyses of unexpected and failed results. Some of this work led to better conversion procedures and QA checks that could now probably be applied generally. An important issue, though, also directly relevant to the pathways2GO project, is scaling and generalizing this work, and reducing the amount of expert human intervention needed. (Added a couple of labels to the ticket to note this issue.)

**Comment by deustp01** [comment]
> for RXN-14093 we have this many MFs because some EC numbers _do_ xref to multiple GO terms:
> 
> `2.7.1.74`: GO:0004137
> `2.7.1.145`: GO:0019136
> `2.7.1.-`: GO:0019914, GO:0008607, GO:0010276, GO:0016538, GO:0016773, GO:0032942, GO:0033785, GO:0034071, GO:0043798, GO:0052835

@hdrabkin @ukemi Isn't this use of "partial" EC's like 2.7.1- on its way to being deprecated, at least for direct annotations of gene products? And if so, is that the durable fix here, that the problem will go away of its own accord as MF definitions are cleaned up and this propagates into cleaned-up annotations at SGD and elsewhere? Or am I missing the point?

**Comment by ukemi** [comment]
I thought we did away with this multiple mapping a long time ago because gene products that were to a 3 digit EC were getting annotated to all of the MFs listed. This points to the data being automated at some point, but now very out of date.

**Comment by ukemi** [comment]
@hdrabkin, how did we fix this before, the issue of GPs getting lots of spurious annotations because of the parent EC numbers?

**Comment by hdrabkin** [comment]
I think this was an issue that cropped in in EC2GO mapping; somehow if a GO id was mapped to a 3 digit, then All of the 4 digit 'children' got mapped to it, which was wrong.

**Comment by ukemi** [comment]
Thanks @hdrabkin! I suspect this happened in this case too. I would speculate that the curators of the pathways assigned EC numbers to the reactions (much like we originally did for genes at MGI). Then the outdated method was used to assign multiple GO ids. @suzialeksander do you know if this is the right track? If so, then the EC to GO mapping needs to be updated (and then checked by a curator).

**Comment by hdrabkin** [comment]
The partial ECs can properly map with GO grouping terms, but I can't think of any case where you would annotate to them, since presumably the paper used would have the actual reaction. 
I suppose that in some cases a Trebl record may have a 3 digit ec, but an EC2GO should just have the mapping to the single grouping term anyways. 
At MGI we also do NOT use a 3 digit ec for a GO mapping term even with the IEAs .

**Comment by deustp01** [comment]
> At MGI we also do NOT use a 3 digit ec for a GO mapping term even with the IEAs .

But that's an editorial decision about scope / granularity / evidence quality. At this point in the development of model organism projects, are these editorial issues well-enough resolved to allow the MGI policy (if we can't annotate to 4-digit specificity we don't annotate at all) to be applied uniformly? What about organisms with high-quality genome sequences and predicted proteomes, maybe mutation genetic data for some aspects of their biology and not much else?

This also goes way beyond the scope of this ticket - none of these hypothetical considerations apply to SGD or, probably, other core Alliance organisms, so this out-of-scope discussion may point to a need for two sets of standards, an MGI-like one within the Alliance group of organisms, a more relaxed standard with appropriate warning flags for the rest of life?

**Comment by hdrabkin** [comment]
I suppose an annotation to the grouping term would be ok, but NOT to all of the child terms;

**Comment by deustp01** [comment]
> I suppose an annotation to the grouping term would be ok, but NOT to all of the child terms;

Yes, and that's exactly the sort of rule we could imagine for that larger group of organisms with partial data, to keep annotation practice more nearly consistent everywhere.

**Comment by suzialeksander** [comment]
It looks like these multiple ECs/activities are coming in through the Pathway Tools software so fixing at the source would be a very slow process.  If it would help, we could provide a list of the ECs we intended to use, and somehow on your end suppress all the rest?

**Comment by dustine32** [comment]
@suzialeksander That is a very good suggestion and I'd be willing to hack this RXN->EC lookup into the conversion code. Would this file would be released/updated along with any new YeastPathways BioPAX file releases?

Anyone else have thoughts on waiting/pushing for a "fix" in the Pathway Tools software?

**Comment by suzialeksander** [comment]
We'd have to make the "only intended ECs" file manually, but since we have no current plans for a next release of the pathways, it should be valid for quite some time.  And we could just make a new one if there are any Pathways updates.

**Comment by suzialeksander** [comment]
In fact, if you want more/less info here's the current EC list
[SGDIDs_to_ExPASy-ECs.txt](https://github.com/geneontology/go-ontology/files/6231197/SGDIDs_to_ExPASy-ECs.txt)

if you think you need any more/less info in this file let me know.

**Comment by dustine32** [comment]
Thanks @suzialeksander! This file might work, but since it connects to our GO-CAM reaction activities through their controller GP, the reactions that don't have a mapped controller GP in the BioPAX will get left out of the fun. For our [example pathway](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:YEAST-SALV-PYRMID-DNTP) only three rxns will get activities:

RXN-14093 - URK1 -> 2.7.1.48 -> uridine kinase activity (GO:0004849)
RXN3O-314 - URH1 -> 3.2.2.3 -> uridine nucleosidase activity (GO:0045437)
CYTIDEAM-RXN - CDD1 -> 3.5.4.5 -> cytidine deaminase activity (GO:0004126)

For the other reactions, what other methods can we use to determine the single correct EC number or GO activity term?

**Comment by dustine32** [comment]
One thing that I totally ignored is that there is a `--sssom` option for supplying a [SSSOM mapping file](https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md). Looks like this is an attempt to map BioPAX entities (Catalysis, BiochemicalReaction, etc) to GO terms by label comparison via @cmungall's [rdf_matcher](https://github.com/cmungall/rdf_matcher) tool. The file currently used is specific for the old batch of YeastPathways files (it's actually committed [here](https://raw.githubusercontent.com/geneontology/pathways2GO/master/exchange/src/main/resources/YeastCyc/obomatch-go-yeastpathway.sssom.tsv.txt)) so it needs to be regenerated for the new batch if we wish to continue mapping to GO this way.

**Comment by suzialeksander** [comment]
@dustine32 I think this ticket was derailed by MF issues above, let me know if you want me to open a clean ticket. On the latest load of YeastPathways, I still see biological_process even though I think we have a more accurate BP to map to.  I've uploaded the YeastPathways2BP file [in the shared drive](https://docs.google.com/spreadsheets/d/1TklacC5v_kFgA-iXLMjZ0-RZTnoGDgv3/edit?usp=sharing&ouid=101228681480002091893&rtpof=true&sd=true), not sure if it's already in the GDrive somewhere else but I couldn't find it.  
![Screenshot 2023-05-12 at 17 19 00](https://github.com/geneontology/go-ontology/assets/13735608/4d7fd2f2-cc87-4e89-bfa2-99f983ea026a)

**Comment by dustine32** [comment]
@suzialeksander There's also this [ticket](https://github.com/geneontology/pathways2GO/issues/159) that's currently closed but can be reopened if you think that's better. It was to add code that pulls the MetaCyc-to-GO xrefs from the GO ontology during conversion. This was mostly incomplete (46 out of 220).

It was decided on the 2023-01-23 Alliance Pathways call to just hack your YeastPathways2BP data into the conversion code as a "get done quick" solution, which I still have yet to do.

**Comment by suzialeksander** [comment]
Closing this old ticket as the mapping seems to be done. https://github.com/geneontology/pathways2GO/issues/255 is about implementing the fix.
