### ISSUE TITLE
Revise definition of  GO:0001540 amyloid-beta binding

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#20109]
Hi

please would you revise the definition for this term  GO:0001540 amyloid-beta binding as the term name is misleading. Many proteins bind amyloid precursor protein or one of the cleavage products, and they are not all binding amyloid-beta. However, the current definition would suggest that any protein binding the precursor would be annotated to this term.

current definition:Interacting selectively and non-covalently with amyloid-beta peptide/protein and/or its precursor.

Change definition to:
Interacting selectively and non-covalently with amyloid-beta peptide/protein.

Thanks

Ruth
@pgarmiri @magrane

**Comment by slaulederkind** [comment]
And how about a amyloid-beta precursor binding term if the definition of term GO:0001540 "amyloid-beta binding" gets changed?

**Comment by pgaudet** [comment]
@RLovering - what do you think ?

**Comment by RLovering** [comment]
I think it is very odd that even though APP is a precursor of Amyloid-beta we haven't really assigned a MF term to the membrane protein. one of the cleavage products seems to be involved in transcription regulation (maybe as a coTF), the full proteins may act as an 'adhesion molecule' or signaling receptor. eg the uniprot record states: Functions as a cell surface receptor and performs physiological functions on the surface of neurons relevant to neurite growth, neuronal adhesion and axonogenesis. 

APP has 2 paralogs APLP1 and APLP2 neither of which are given clear MF roles either. 

So maybe it would be helpful to have a general term for binding these proteins, my problem is that because of their range of functions the term couldn't be included under anything other than protein binding.
I think it might be better to annotate the binding of these three proteins (APP, APLP1, APLP2) based on how they are functioning, eg when they acts as a coreceptor to coreceptor binding and to include APP in the with field.

Or can you see a better way to do this

Best

Ruth
