### ISSUE TITLE
Request a new GO CC term: Z granule

### ISSUE THREAD

**Issue by draciti** [geneontology/go-ontology#20108]
Hello,
I would like  to request a new GOCC term: Z granule

It should be 
- part_of 'germ plasm' (GO:0060293) 
- is_a 'cytoplasmic ribonucleoprotein granule' (GO:0036464) 

I drafted a definition below based on these 2 references: Evidence: [PMID:29769721][PMID:31378614] but feel free to edit to conform to GO definitions. 

'Z granules are liquid-like condensates, i.e. self-assembling cellular structures that form when specific proteins and RNAs undergo liquid–liquid phase transitions from surrounding cytoplasm. The Z granules co-localize with P granules, but during the mitotic stage in the adult germline the two granules separate, while remaining adjacent to each other. Z granules contain the WAGO-4 argonaute and the ZNFX-1 protein needed for proper small RNA amplification on targeted mRNAs and for balanced epigenetic inheritance.'

Thanks,
Daniela

**Comment by pgaudet** [comment]
I think this term is fine. Note that we have rejected a similar term in #17658 , nuclear protein granule, but he definition was more vague. 

@ValWood @bmeldal thoughts ? 

Thanks, Pascale

**Comment by ValWood** [comment]
We need to be careful, but there is a precedent. However, if these structures are defined by partial contents it is going to be very difficult to know when they refer to the same compartment/structure. Especially across species.

This for example:
https://www.ebi.ac.uk/QuickGO/term/GO:0071547
looks remarkably similar and contains RNAi pathway components.

**Comment by bmeldal** [comment]
Oh, I'm no expert in these granules ;-) 
I trust Val on this 👍

**Comment by ValWood** [comment]
I'm not really sure. I think it's ok if care is taken to ensure that if the same thing exists in other species with a different name it is identified. Maybe the definitions should focus more on the processes than the physical properties. Is that possible @draciti ? It doesn't read like a normal CC term def.

**Comment by draciti** [comment]
yes @ValWood , I  will read more literature to check on other species and will write a better definition. I will then run it  by you. I am off this week (FYI), I'll look into it once back  in the office. Thanks, all!

**Comment by krchristie** [comment]
> yes @ValWood , I will read more literature to check on other species and will write a better definition. I will then run it by you. I am off this week (FYI), I'll look into it once back in the office. Thanks, all!

Awesome. This is an annotation week for me, so I won't get to this till next week anyway.

**Comment by ValWood** [comment]
I see why you are eager to capture this though. I noticed it was the Oded Rechavi paper tweeted by MC Hammer (something I  never envisaged typing into GitHub).

**Comment by draciti** [comment]
@ValWood , I read more literature - including this recent review on rna granules, which mentions Z granules but not piP-bodies: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7397151/- and wrote a more generic definition (below) but cannot determine if Z granules and piP-bodies are indeed equivalent structures in different species, although they look similar and both contain RNAi pathway components. 

I see two course of actions but I am open to thirds :)
1) Specify species in the definition, (see as another example the mutator focus definition, GO:1990633 https://www.ebi.ac.uk/QuickGO/term/GO:1990633).

Z granule: A small cytoplasmic, non-membranous RNA/protein complex aggregate in the primordial germ cells of C. elegans. Z granules are distinct from, but colocalize with or are adjacent to, P granules and mutator foci and are associated with RNA metabolism.

2) Contact the authors of the C. elegans paper asking if ok to use the term piP-bodies to annotate the  localization of ZNFX-1 and WAGO-4. That will prompt them to check the mouse paper and advise. We could then put Z granule as synonym? The  term Z granule is now adopted in the c elegans literature.

Thanks in advance for any advice.

**Comment by ValWood** [comment]
I think the def sounds fine.
I don't think GO has a policy on 'granules' but I am in favour of adding them, because  they can always be merged and refined later....

@pgaudet ?

**Comment by pgaudet** [comment]
Yes I think in this case it's fine, the definition has enough details to distinguish it from other 'fuzzy' terms.

**Comment by draciti** [comment]
great, thanks both. lmk if there' anything else you need

**Comment by krchristie** [comment]
> @ValWood , I read more literature - including this recent review on rna granules, which mentions Z granules but not piP-bodies: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7397151/- and wrote a more generic definition (below) but cannot determine if Z granules and piP-bodies are indeed equivalent structures in different species, although they look similar and both contain RNAi pathway components.
> 
> I see two course of actions but I am open to thirds :)
> 
>     1. Specify species in the definition, (see as another example the mutator focus definition, GO:1990633 https://www.ebi.ac.uk/QuickGO/term/GO:1990633).
> 
> 
> Z granule: A small cytoplasmic, non-membranous RNA/protein complex aggregate in the primordial germ cells of C. elegans. Z granules are distinct from, but colocalize with or are adjacent to, P granules and mutator foci and are associated with RNA metabolism.
> 
>     1. Contact the authors of the C. elegans paper asking if ok to use the term piP-bodies to annotate the  localization of ZNFX-1 and WAGO-4. That will prompt them to check the mouse paper and advise. We could then put Z granule as synonym? The  term Z granule is now adopted in the c elegans literature.
> 
> 
> Thanks in advance for any advice.

I think the best option is to contact the authors to see if `Z granule` is synonomous with `piP-body`. If it is, I'll add the synonym; if it's not, I'll add a new term.

@draciti - Does that sound OK; can you contact the authors?

**Comment by draciti** [comment]
@krchristie , will do. I will keep you posted on this ticket

**Comment by draciti** [comment]
@krchristie, the PI of the study just got back to me.
Here his reply:
"Hey Daniela,
I supposed it is possible that piP-bodies are analogous to Z granules, but we have no reason to believe or not believe this. Any way to just add a new category called Z granule?"

**Comment by krchristie** [comment]
> @krchristie, the PI of the study just got back to me.
> Here his reply:
> "Hey Daniela,
> I supposed it is possible that piP-bodies are analogous to Z granules, but we have no reason to believe or not believe this. Any way to just add a new category called Z granule?"

@draciti - Thanks for checking with the authors. I've put the new term in. I didn't think it was a good idea to say "in the primordial germ cells of C. elegans" because it could cause problems if people read this to mean that they are ONLY found in C. elegans and I don't think we have sufficient evidence to say that yet, so I modified the definition slightly. 

I also modified the existing term for `P granule` slightly, mostly to change synonym types because it seems odd to have an EXACT synonym of `germline granule` on this term when a `Z granule` is also a `germline granule`, so I have made it a BROAD synonym for both `P granule` and `Z granule`. 

> Term]
> id: GO:0120279
> name: Z granule
> namespace: cellular_component
> alt_id: GO:0018994
> def: "A small cytoplasmic, non-membranous RNA/protein complex aggregate in the primordial germ cells that are distinct from, but colocalize with or are adjacent to, P granules and mutator foci and are associated with RNA metabolism. Z granules have been observed in C. elegans." [GOC:dr, GOC:krc, PMID:29769721, PMID:31378614, PMID:32650583]
> synonym: "germline granule" BROAD []
> is_a: GO:0036464 ! cytoplasmic ribonucleoprotein granule
> relationship: part_of GO:0060293 ! germ plasm
> created_by: krc
> creation_date: 2020-10-21T18:27:05Z

I also changed the synonym types of the other two synonyms (polar granule) and (nuage) since my checks in PubMed and Google seemed to indicate that these synonyms may Drosophila specific names of a structure that is more broadly distributed and fixed a minor typo in the definition.

**Comment by draciti** [comment]
thanks @krchristie !
I'll also let the author know.
