### ISSUE TITLE
possible merge term (magnesium-dependent)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20106]
GO:0004724    magnesium-dependent protein serine/threonine phosphatase activity

Definition (GO:0004724 GONUTS page)
Catalysis of the reactions: protein serine phosphate + H2O = protein serine + phosphate; and protein threonine phosphate + H2O = protein threonine + phosphate. These reactions require the presence of magnesium.

weren't we going to merge these?

**Comment by pgaudet** [comment]
Right, anyhow it's the same EC. 

Please merge into 
GO:0004722 protein serine/threonine phosphatase activity

Also, we should merge 
GO:0005963 magnesium-dependent protein serine/threonine phosphatase complex
into 
GO:0008287 protein serine/threonine phosphatase complex

Thanks, Pascale
