### ISSUE TITLE
regulation of cerebral blood circulation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#20107]
I'd like to see "positive regulation of cerebral blood circulation" and "negative regulation of cerebral blood circulation" added to the GO ontology under the parent terms "positive regulation of blood circulation" (GO:1903524) and "negative regulation of blood circulation" (GO:1903523), respectively.  The definitions could be "Any process that activates or increases/stops, prevents or reduces the frequency, rate or extent of cerebral blood circulation".  Example can be found in PMID:25397684.

**Comment by vanaukenk** [comment]
@slaulederkind 
This sounds like a great process to model as a GO-CAM.  Might I entice you to attend the GO-CAM Jamboree in November and work on a model of this?  You could add it to the [proposed models spreadsheet](https://docs.google.com/spreadsheets/d/1RPyKWCsJ7SVnhBYBXJ7rIZ6H2HTtQK4rRLFMWjH9P_E/edit#gid=2104868039).

I was wondering what your thoughts are about the relationship between the 'myogenic response' described in the paper and the regulation of blood circulation.  Do we have a term in the GO BP for 'myogenic response' or is this really muscle contraction, or regulation of muscle contraction, or something else?

Also, we have terms whose labels refer to 'flow' and terms whose labels refer to 'circulation'.  Do you think we are consistent about meaning and usage here?

**Comment by krchristie** [comment]
In order to have `regulation of cerebral blood circulation`, it is necessary to have a term for `cerebral blood circulation`. Thus, I have created this term based on the existing def of the term `blood circulation` and the cited Wikipedia page for `cerebral circulation`. Let me know if you see any problems with the way I created this term, or any of the 3 regulation terms that reference it.

> +[Term]
> +id: GO:0120275
> +name: cerebral blood circulation
> +namespace: biological_process
> +def: "The flow of blood through the network of cerebral arteries and veins supplying the brain, enabling the transport of nutrients to the tissues and the removal of waste products." [GOC:krc, PMID:25397684, Wikipedia:Cerebral_circulation]
> +synonym: "brain blood circulation" EXACT []
> +xref: Wikipedia:Cerebral_circulation
> +is_a: GO:0008015 ! blood circulation
> +intersection_of: GO:0008015 ! blood circulation
> +intersection_of: occurs_in UBERON:0003499 ! brain blood vessel
> +created_by: krc
> +creation_date: 2020-10-20T19:13:51Z

**Comment by ukemi** [comment]
I think this is a necessary, but not sufficient logical definition. It would also work for cerebellar blood circulation. Wouldn't it be better to have:
+intersection_of: GO:0008015 ! blood circulation
+intersection_of: occurs_in UBERON:0001893 ! telencephalon

**Comment by krchristie** [comment]
> I think this is a necessary, but not sufficient logical definition. It would also work for cerebellar blood circulation. Wouldn't it be better to have:
> +intersection_of: GO:0008015 ! blood circulation
> +intersection_of: occurs_in UBERON:0001893 ! telencephalon

From the Google search I did and the Wiki page I used as a source, I interpreted `cerebral blood circulation` to mean blood circulation in the brain, not in any specific region of the brain. 

@slaulederkind - Could you please take a look and confirm exactly what you wanted these terms to be.

**Comment by ukemi** [comment]
Also wondering about where the process really occurs wrt blood brain barrier.

**Comment by slaulederkind** [comment]
I didn't expect "cerebral" to mean "brain" in general.  "cerebral" should refer to only the two cerebral hemispheres.

**Comment by krchristie** [comment]
@slaulederkind - I have corrected the definition of `cerebral blood circulation`. For future, be aware that the most important part of the definition of a regulation term is the definition of the non-regulation term it is based on, so if one doesn't exist, please indicate what that term should be.
