### ISSUE TITLE
6 terms with xref: EC:3.1.4 (merges/obsoletions?)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20117]
EC:3.1.4 is a grouping term for Phosphoric diester hydrolases
https://enzyme.expasy.org/EC/3.1.4.-

But there are 6 GO terms with this xref (below) - first one is correct, second one needs changing, other four probably just need removing?

id: GO:0008081
name: phosphoric diester hydrolase activity
xref: EC:3.1.4
=> correct!

id: GO:0004115
name: 3',5'-cyclic-AMP phosphodiesterase activity
xref: EC:3.1.4
- [x] change to 3.1.4.53

id: GO:0004117
name: calmodulin-dependent cyclic-nucleotide phosphodiesterase activity
xref: EC:3.1.4
- [x] remove

id: GO:0004118
name: cGMP-stimulated cyclic-nucleotide phosphodiesterase activity
xref: EC:3.1.4
- [x] remove

id: GO:0004119
name: cGMP-inhibited cyclic-nucleotide phosphodiesterase activity
xref: EC:3.1.4
- [x] remove

id: GO:0004120
name: photoreceptor cyclic-nucleotide phosphodiesterase activity
xref: EC:3.1.4
- [x] remove

**Comment by hdrabkin** [comment]
id: GO:0004117
name: calmodulin-dependent cyclic-nucleotide phosphodiesterase activity

Activity is regulated by calmodulin. I suspect this should be obsoleted? @pgaudet what do you think?

**Comment by hdrabkin** [comment]
So looking at the last 4 I wonder if they should all be removed. 
and 
 GO:0004120 seems to be a gene product? (ie, activity is enabled by a photoreceptor
I removed 3 digit ec from them and put GOC: curators as ref for last one as temporary fix while we decide what to do with these 4

**Comment by pgaudet** [comment]
GO:0004120
name: photoreceptor cyclic-nucleotide phosphodiesterase activity

-> no reference, no annotations; I would obsolete that one, it does sound like a substrate - see Q14028. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
@pgaudet what about the ' calmodulin-dependent cyclic-nucleotide phosphodiesterase activity'?
I would think this term represents what we would put in a  model now (calmodulin gp regulating gp activity of whatever is doing the activity?

**Comment by pgaudet** [comment]
> @pgaudet what about the ' calmodulin-dependent cyclic-nucleotide phosphodiesterase activity'?

Se my comment above https://github.com/geneontology/go-ontology/issues/20117#issuecomment-707746250

I suggest a merge.

**Comment by sjm41** [comment]
@pgaudet @hdrabkin Looks like there are some outstanding obsoletions/merges to do here?

**Comment by sjm41** [comment]
@pgaudet I just reviewed this ticket: it was suggested previously that that 4 GO terms mentioned above should be obsoleted/merged - below is an update on each one.

---

id: GO:0004117
name: calmodulin-activated dual specificity 3',5'-cyclic-GMP, 3',5'-cyclic-AMP phosphodiesterase activity
namespace: molecular_function
def: "Catalysis of the reactions: 3',5'-cyclic AMP + H2O = AMP + H+ and 3',5'-cyclic GMP + H2O = GMP + H+; this activity is activated by binding to calcium-bound calmodulin." [PMID:8557689, PMID:9419816]
synonym: "calmodulin-activated cyclic-nucleotide dual specificity phosphodiesterase activity" RELATED []
synonym: "calmodulin-dependent cyclic-nucleotide phosphodiesterase activity" BROAD []
is_a: GO:0004115 ! 3',5'-cyclic-AMP phosphodiesterase activity
is_a: GO:0047555 ! 3',5'-cyclic-GMP phosphodiesterase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22791" xsd:anyURI

=> this term was since discussed and updated in #22791
=> it now has 8 EXP annotations, and should be retained

---

id: GO:0004118
name: cGMP-stimulated cyclic-nucleotide phosphodiesterase activity
namespace: molecular_function
def: "Catalysis of the reaction: nucleoside 3',5'-cyclic phosphate + H2O = nucleoside 5'-phosphate; catalytic activity is increased in the presence of cGMP." [GOC:mah]
is_a: GO:0004114 ! 3',5'-cyclic-nucleotide phosphodiesterase activity

=> 6 EXP annotations to PDE2A, PDE11A and PDE10A, , but no reference/xref

- [ ] Seems to be the same as GO:0047555, so should be merged?:

id: GO:0047555
name: 3',5'-cyclic-GMP phosphodiesterase activity
namespace: molecular_function
alt_id: GO:0004116
def: "Catalysis of the reaction: 3',5'-cyclic GMP + H2O = GMP + H+." [RHEA:16957]
synonym: "3',5' cyclic-GMP phosphodiesterase activity" EXACT []
synonym: "3',5'-cyclic-GMP 5'-nucleotidohydrolase activity" RELATED [EC:3.1.4.35]
synonym: "cGMP phosphodiesterase activity" EXACT []
synonym: "cGMP-PDE" RELATED [EC:3.1.4.35]
synonym: "cGMP-specific phosphodiesterase activity" EXACT []
synonym: "cyclic 3',5'-GMP phosphodiesterase activity" RELATED [EC:3.1.4.35]
synonym: "cyclic GMP phosphodiesterase activity" EXACT []
synonym: "cyclic guanosine 3',5'-monophosphate phosphodiesterase activity" RELATED [EC:3.1.4.35]
synonym: "cyclic guanosine 3',5'-phosphate phosphodiesterase activity" RELATED [EC:3.1.4.35]
synonym: "guanosine cyclic 3',5'-phosphate phosphodiesterase activity" EXACT []
xref: EC:3.1.4.35
xref: MetaCyc:35-CYCLIC-GMP-PHOSPHODIESTERASE-RXN
xref: RHEA:16957
is_a: GO:0004114 ! 3',5'-cyclic-nucleotide phosphodiesterase activity

---

id: GO:0004119
name: cGMP-inhibited cyclic-nucleotide phosphodiesterase activity
namespace: molecular_function
def: "Catalysis of the reaction: nucleoside 3',5'-cyclic phosphate + H2O = nucleoside 5'-phosphate; catalytic activity is decreased in the presence of cGMP." [GOC:mah]
is_a: GO:0004114 ! 3',5'-cyclic-nucleotide phosphodiesterase activity

- [ ] 1 EXP annotation to human PDE3A, but no reference/xref, suggest obsoletion

---

id: GO:0004120
name: photoreceptor cyclic-nucleotide phosphodiesterase activity
namespace: molecular_function
def: "Catalysis of the reaction: nucleoside cyclic phosphate + H2O = nucleoside phosphate. This reaction is the hydrolysis of bonds in a cyclic nucleotide." [GOC:curators]
is_a: GO:0004114 ! 3',5'-cyclic-nucleotide phosphodiesterase activity

- [ ] no annotations, no reference/xref, should be obsoleted (as suggested above)

**Comment by raymond91125** [comment]
Genes annotated with GO:0004118 or GO:0004119 appear to be cAMP and cGMP dual specificity according to UniProt. Thus they fit better with EC:3.1.4.17/RHEA:14653.

**Comment by sjm41** [comment]
> Genes annotated with GO:0004118 or GO:0004119 appear to be cAMP and cGMP dual specificity according to UniProt. Thus they fit better with EC:3.1.4.17/RHEA:14653.
Instead of merge into the sibling GO:0047555 3',5'-cyclic-GMP phosphodiesterase activity, we may consider merging into the parent GO:0004114 3',5'-cyclic-nucleotide phosphodiesterase activity

Hi @raymond91125 Yes, that would also work. Thanks.

**Comment by raymond91125** [comment]
@pgaudet I wonder if you can help clarify MF guideline concerning this case: 
cGMP-stimulated cyclic-nucleotide phosphodiesterase activity vs. cGMP-inhibited cyclic-nucleotide phosphodiesterase activity.
If appears that these represent two types of PDE's (2 and 3) that carry out the same enzymatic reactions but that differ by their intrinsic regulation mechanisms (via different regulatory domains). I don't think EC or RHEA has separate classes for them. For GO, should we?

**Comment by pgaudet** [comment]
@raymond91125 

@hattrill and I have reviewed this in the context of the signaling work. We agree these should be kept. I fixed the EC xrefs. 

See useful review here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8880502/

Thanks, Pascale
