### ISSUE TITLE
Discovered today that GO:0004674 protein serine/threonine  kinase activity has 2 RHEAs (EC:2.7.11.1, . creating separate terms. and remove rheas from base term.

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20114]
Discovered today that GO:0004674 protein serine/threonine  kinase activity has 2 RHEAs (EC:2.7.11.1, . creating separate terms. and remove rheas from base term.
+id: GO:0106310
+name: protein serine kinase activity
+[Term]
+id: GO:0106311
+name: protein threonine kinase activity

have already done same for protein serine/threonine phosphatase activity for a different ticket.

_Originally posted by @hdrabkin in https://github.com/geneontology/go-ontology/issues/19152#issuecomment-696953523_

**Comment by ValWood** [comment]
I was just about to request a merge of a term that one of our users  has used (quite correctly).

<img width="567" alt="Screen Shot 2020-10-12 at 17 31 11" src="https://user-images.githubusercontent.com/7359272/95770991-32261280-0cb2-11eb-9f56-5bd83bfe8d01.png">

 I was going to request this for a number of reasons.

1. Short term reason, a  serine/threonine protein kinas has specificity for serine or threonine residues , depending on context. I did not ire this as 2 indemendent activities and I though that GO didn't eaither. But it seems that recently 
separate terms were added for serine and threonine kinases. Do you have an exampe of a kinase that  phosphorylates only serie or only threonine.

This will make it very difficult to make consistent, and specific annotations becasue, cdc for exxampele phosphorylates seringes in some proteins, threonines in csome proteins and serine and threonines in some protiens. I ask GO to seriusly consider if we really want this specificity in the MF ontology. Muuch better would be the ability to specify the modified residue on the target protein, rather than bake the residue into the kinse term (I know that we specify functoions for teh histine modifiers right now but this seems more of  a special case because many of the modifiers are histone residue specific. Kinases are are more prolific and this would  make the curaton very challenging. 

2. regardless of the ansewer  to 1, I still don't think we should have this specificity at the process level....

**Comment by hdrabkin** [comment]
Each time a enzyme phosphorylates only one or the other not both at the same time.

**Comment by ValWood** [comment]
Above edited for clarity.

Imagine how challenging it would be if I had to specify serine or threonine or both for all of these kinase activities. It would look  silly.....it's a single  activity.

<img width="1093" alt="Screenshot 2020-10-12 at 18 03 16" src="https://user-images.githubusercontent.com/7359272/95772907-63eca880-0cb5-11eb-80d9-1c4db6af1abb.png">


The kinase is a serine/threonine protein kinase. I don't think we should follow the Rhea split here. Form the GO perspective a) it does not add anything biologically  b) it makes curation harder. We would want to know the specific residue (possibly as an extension?)  but just whether it is a threonine or threonine is not useful on its own. 

At PomBase we  currently capture this information (modified residue)  as follows:

1.  Capture the modification information on the modified gene product
(for example:

<img width="773" alt="Screenshot 2020-10-12 at 18 08 12" src="https://user-images.githubusercontent.com/7359272/95773177-e7a69500-0cb5-11eb-99a2-14f06f5f934d.png">

Bear in mind that this is the modification data for just one of the hundreds of proteins phosphorylated on serines and threonines  by cdc2. Imagine the work involved in capturing these as  a serine or threonine kinase. If we used serine kinase and threonine kinase on the gene pages  consistently  (i.e cdc2 above) 

2. On the modified product , if the modification is connected to a particular causal relation we will request a PRO ID to represent the modification   (ideally the modified form would be represented more succinctly (cut12-T75,T78) 

<img width="1095" alt="Screenshot 2020-10-12 at 18 15 53" src="https://user-images.githubusercontent.com/7359272/95773762-00637a80-0cb7-11eb-96d4-14da0faee48f.png">

I urge you to merge these into a single term for serine/threonine  (whether the processes should be in GO at all is a separate issue. At PomBAse we don't really use these terms for annotation if we can make the kinase annotation as we can in this case)

Does this make sense?

@thomaspd 
@pgaudet 
@cmungall 
@dr

**Comment by ValWood** [comment]
> Each time a enzyme phosphorylates only one or the other not both at the same time.

Yes, but the definitions could cover this? Phosphorylates a threonine or a serine?

So now we would need to make 2 annotations for all of those cdc2 substrates:

cyclin-dependent protein serine/threonine kinase activity
 phosphorylates clp1 involved in negative regulation of exit from mitosis during mitotic metaphase

would need to become

cyclin-dependent protein serine kinase activity
 phosphorylates clp1 involved in negative regulation of exit from mitosis during mitotic metaphase
AND
cyclin-dependent protein threonine kinase activity
 phosphorylates clp1 involved in negative regulation of exit from mitosis during mitotic metaphase

x 200

can we be pragmatic in this case  please... we discussed this historically and always decided that this should be a single term, so why change now?

**Comment by pgaudet** [comment]
>>   Each time a enzyme phosphorylates only one or the other not both at the same time.

> Yes, but the definitions could cover this? Phosphorylates a threonine or a serine?

Yes - I thought the GO classes were not 'instance level'. I thought those terms existed because there were examples of kinases that specifically phosphorylated Ser OR Thr. I thought a normal Ser/Thr kinase should have been annotated to GO:0004674 protein serine/threonine kinase activity. 

I agree all BPs should be merged/obsoleted. 

Will check with @thomaspd 

Pascale

**Comment by ValWood** [comment]
>I thought those terms existed because there were examples of kinases that specifically phosphorylated Ser OR Thr.

Oh, I did not know that. Which ones are they? and how would we know? We don't know all of the physiological substrates of *any* kinase?

**Comment by hdrabkin** [comment]
Yes it is a rule; Because we will use them for logical defs you can't have two of them per one term. Annotating to the parent is not a problem.

**Comment by ValWood** [comment]
Can't we just not map this term to RHEA, just map to protein kinase? We don't map to CHEBI for example in situations where we need to be pragmatic about the effects on GO annotation.

Personally, I think we could capture residue specificity differently across the board if we want to do it in a scalable way, but that is a discussion for another day.

**Comment by ValWood** [comment]
> Annotating to the parent is not a problem.

This isn't a problem in that we can do it, but it is a problem in that people will not know when they should deepen.
 But if we use the parent then the term we use won't have a logical definition by Rhea route.
Presumably, a logical definition can still be crafter via another route for this term. Rhea for reaction + CHEBI for substrate?

**Comment by pgaudet** [comment]
@amorgat can you help ??

**Comment by hdrabkin** [comment]
'his isn't a problem in that we can do it, but it is a problem in that people will not know when they should deepen.'
Won't they know when reading the paper? If the paper talks about phosphorylating a ser residue, then that is the reaction being used.

**Comment by ValWood** [comment]
>his isn't a problem in that we can do it, but it is a problem in that people will not know when they should deepen.'
Won't they know when reading the paper? If the paper talks about phosphorylating a ser residue, then that is the reaction being used.

It just isn't practical to do this and we discussed in the past why  a serine/threonine  protein phosphatase would not be split into 2 term. I will look for the old discussion.

This is a problem if there are proteins that phosphorylate only serines or only threonines. Has anyone got an example of this?  but even so I think we could still use the serine/threonine term.

**Comment by ValWood** [comment]
I can't find the old discussion. Too many tickets with serine/threonine... ;)

**Comment by hdrabkin** [comment]
Does the ticket you seek pre-date RHEA?

**Comment by ValWood** [comment]
Probably but the point was that from a curational and biological point of view it did not make sense to split these in GO. This fact doesn't change because we are using Rhea.  It would be an inordinate amount of work, and additional complication, for no discernable advantage to  users?

**Comment by mah11** [comment]
> I can't find the old discussion.

could be #18460

**Comment by ValWood** [comment]
Yes thank you @mah11 !
Case argued excellently by @deustp01  and supported by me and @srengel 
and it seemed to be agreed that it wasn't necessary to follow Rhea here.

**Comment by ValWood** [comment]
Similar situation for protein phosphatases:

So we only show IEAs if they are more specific and not covered. by EXP annotation

Here we get the individual phosphatase terms.

<img width="1135" alt="Screenshot 2020-10-16 at 10 06 34" src="https://user-images.githubusercontent.com/7359272/96239717-f8962580-0f97-11eb-88ab-221a10748c5c.png">

Sowe would require
MAP kinase serine phosphatase
and MAP kinase protein phosphatase
which would be bonkers.

My interim solution is to filter these annotations as they don't add value.

**Comment by ValWood** [comment]
You can see the inconsistencies here already:

<img width="1227" alt="Screenshot 2020-10-16 at 11 27 19" src="https://user-images.githubusercontent.com/7359272/96247911-a73f6380-0fa2-11eb-8077-35cf8a680f60.png">

**Comment by hdrabkin** [comment]
I note that UniProt has annotated or UniProtKB:G4NH08 GSK1, Magnaporthe oryzae to the serine RHEA based on the paper that only looked at ser 8 (The publication used to reference  the ser residue reaction for the kinase appears to have been made because the paper only looks at ser 8; They make target mutants (HAT1) but not a thr 8). I don't know how many instances there are in the UniProt set.

**Comment by ValWood** [comment]
but that is all they tested?  (we have bazillions of examples like this). 
we would annotate as a 
serine/threonine-protein kinase phosphorylation  HAT1-S8
as a  substrate.

**Comment by ValWood** [comment]
corrected above comment

**Comment by hdrabkin** [comment]
Exactly that is ALL they were concerned with in the paper; they only looked at phosphorylation of ser 8 of hat by the kinase; and yes one could do input /output unphosphorylated HAT1 Ser8/phosphorylated Hat1 ser8 (PRO id names if pro had them for this species).

**Comment by nataled** [comment]
Just in case they are needed, I've created the following terms in PRO:

- unphosphorylated HAT1 Ser8 = PR:000050462 = "histone acetyltransferase type B catalytic subunit unphosphorylated 1 (rice blastfungus)"
- phosphorylated Hat1 ser8   = PR:000050463 = "histone acetyltransferase type B catalytic subunit phosphorylated 1 (rice blastfungus)"

Note that the names are based on UniProtKB names, but these are MoHAT1 given in the paper PMID:30776962.

**Comment by pgaudet** [comment]
We'll talk about this with @amorgat next week - if you are available Anne ?

**Comment by pgaudet** [comment]
@cmungall It would be nice to be aligned with Uniprot in terms of annotation practices. Are they adding both Rheas for S/T kinases ?

**Comment by cmungall** [comment]
@pgaudet 
> It would be nice to be aligned with Uniprot in terms of annotation practices. Are they adding both Rheas for S/T kinases ?

I compared the annotations to the two Rheas (just looking at the SwissProt subset):

 - https://www.uniprot.org/uniprot/?query=annotation:(type:%22catalytic%20activity%22%20rhea:46608)&fil=reviewed%3Ayes
 - https://www.uniprot.org/uniprot/?query=annotation:(type:%22catalytic%20activity%22%20rhea:17989)&fil=reviewed%3Ayes

G4NH08 + Q9Y2I7 + Q9Z1T6 : only in RHEA:17989
Q9VZI2 : only in RHEA:46608

3602 proteins in both lists

So it seems like SP have been consistent in always annotating to both. It's not clear if the minor discrepancy is intentional or accidental. Also not clear if the consistency is due to annotation to a different system like GO and then propagating to Rhea, and if there are rules for curators moving forward.

**Comment by ValWood** [comment]
I really really hope we don't do this (in fact I can't see a way to easily do this sustainably for all of the serine/threonine protein kinases we have already captured).

These are the 380 rows (substrates+residues) of a single kinase cyclin-dependent protein serine/threonine  kinase  cdc2 
https://docs.google.com/spreadsheets/d/1wrmpbjdUcbyempnLhZ2x2pxmoW28iacv68Cv4jDu8zI/edit?usp=sharing

As you can see cdc2 phosphorylates most proteins promiscuously on both serine and threonine. We have  a number of protein kinases with a lot of substrate data now (47 kinases have numerous substrates, most including serine and threonine residues). I don't expect any serine/threonine kinase to phosphorylate only serine or threonine....

Protein kinases phosphorylate a consensus  "motif" so the CDK family motif is Cdk1 consensus sequence (S/T*-P, or S/T*-P-x-K/R, where x represents any amino acid and the asterisk indicates the site of phosphorylation). The S/T may switch between species  but the site is biologically equivalent. It is the context  (site) that is biologically interesting here not the specific residue.
It would be a lot of work to split these (indeed the terms do not even exist for cyclin dependent/ MAPK/MAPKKK etc).

So for  fission yeast we would continue to annotate to  serine/threonine term because it would be too much work to change. I am happy to reannotate anything, but if there is value in doing so.

I don't see how we could possibly keep these annotations internally consistent.

**Comment by ValWood** [comment]
[Uploading mods_single_kinase.txt…]()

**Comment by ValWood** [comment]
[mods_single_kinase.txt](https://github.com/geneontology/go-ontology/files/5403707/mods_single_kinase.txt)

**Comment by cmungall** [comment]
@ValWood - agreed. Curious as to the Rhea/SIB strategy, how they maintain consistency; perhaps Rhea could be persuaded to have a grouping here.

We will of course keep S/T groupings in GO.

I think the options are:

 1. Rhea creates a S/T grouping and we have a equivalence mapping
 2. GO keeps S/T grouping but makes two subclasses each with 1:1 mappings; we may have a do-not-annotate tag on the subclasses and have the rule we always roll up
 3. We define the GO S/T class using OWL unionOf of the two Rheas, and we categorize these mappings as narrow rather than equivalent

My preference is for 1. I don't think anyone would be in favor of 2 but I list to be exhaustive.

Seems likely we may end up with 3. We have discussed elsewhere the need to stratify our mappings and make it explicit whether a mapping is exact/narrow/broad/related. E..g metalloendopeptidases and EC

**Comment by ValWood** [comment]
I like 1 or 3.

**Comment by alanbridge** [comment]
Hi 

sorry for the late reply, I think Anne is pretty occupied so I take the liberty of butting in. 

Most annotations in UniProt now to the two Rhea reactions 

ATP + L-seryl-[protein] = ADP + H+ + O-phospho-L-seryl-[protein]
ATP + L-threonyl-[protein] = ADP + H+ + O-phospho-L-threonyl-[protein]

will have been created based on their mapping to EC numbers and EC number annotations in UniProt. Curators annotating to Rhea now are now in theory free to add one or the other based on the experimental evidence of which sites in the known targets have been tested. We would expect them to annotate those sites in the target proteins too as part of their normal work, so enzyme and target should be consistent, and we use the same ChEBIs in our list of PTMs too at https://www.uniprot.org/docs/ptmlist, e.g.

ID   Phosphoserine
AC   PTM-0253
FT   MOD_RES
...
KW   Phosphoprotein.
DR   ChEBI; CHEBI:83421.
DR   RESID; AA0037.
DR   PSI-MOD; MOD:00046.
DR   Unimod; 21.
//

ID   Phosphothreonine
AC   PTM-0254
FT   MOD_RES
...
DR   ChEBI; CHEBI:61977.
DR   RESID; AA0038.
DR   PSI-MOD; MOD:00047.
DR   Unimod; 21.
//

So for any given modified residue you should be able to link it to the corresponding Rheas and eventually enzymes. 

I think number 3 may be the best solution, given the weight of legacy data on both sides, but @amorgat will have her say on Rhea!

All the best, Alan

**Comment by pgaudet** [comment]
On GO call, with @amorgat 

Rhea represents reactions. GO wants to keep the S/T term, so we're leaning towards @cmungall 's solution 3 https://github.com/geneontology/go-ontology/issues/20114#issuecomment-713063804

**Comment by pgaudet** [comment]
Ask Rhea for a grouping term 
@amorgat 
@kaxelsen 

Can it be done?

**Comment by amorgat** [comment]
@pgaudet, sorry but we will not create the parent reaction with Ser/Thr residues. This not the scope of Rhea. Similarly we don't create reactions with NAD(H) nor NADP(H). 
As mentioned earlier by @alanbridge, UniProt entries with the EC 2.7.11.1 enzyme are annotated with
RHEA:17989 ATP + L-seryl-[protein] = ADP + H+ + O-phospho-L-seryl-[protein]
RHEA:46608 ATP + L-threonyl-[protein] = ADP + H+ + O-phospho-L-threonyl-[protein]

Note that these 2 reactions are linked to several EC numbers (see https://www.rhea-db.org/rhea/?query=ec%3A2.7.11.1&columns=%2Crhea-id%2Cequation%2Cenzyme-class%2Cuniprot%2Cgo). 

This is typically a case where UniProt/Rhea have different annotation guidelines compared to GO. In these cases the 1:1 mapping will not be possible.

**Comment by pgaudet** [comment]
Thanks for the clarification @amorgat

**Comment by cmungall** [comment]
Some further questions for @amorgat , but more curiosity-driven so not urgent.

There is a lot of proteins annotated to both, with high overlap:

ID | num proteins
---|---
RHEA:46608 | 395357
RHEA:17989 | 386066
both | 387135
RHEA:46608 **only** | 8280
RHEA:17989 **only** | 8

this is the RHEA:17989-only set:

|id|label
|---|---|
|uniprot:G4NH08|Glycogen synthase kinase 1
|uniprot:Q3S406|Glycogen synthase kinase 1
|uniprot:P42336|Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit alpha isoform
|uniprot:P42337|Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit alpha isoform
|uniprot:Q9Y2I7|1-phosphatidylinositol 3-phosphate 5-kinase
|uniprot:Q9Z1T6|1-phosphatidylinositol 3-phosphate 5-kinase
|uniprot:P32871|Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit alpha isoform
|uniprot:A0A0G2K344|Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit alpha isoform


to what extent are these differences biologically meaningful? I assume that many of the annotations come from transference from EC, where the annotations are auto-rolled down.

**Comment by amorgat** [comment]
@cmungall, as your question concerns UniProt annotations, I forwarded it to @sylvainpoux. Below his answer:

Classical Ser/Thr protein kinases mediate 2 reactions: the Ser protein kinase activity (RHEA:17989) and the Thr protein kinase activity (RHEA:46608) 
Most proteins are able to phosphorylate both Ser and Thr and we add both reactions by default (there are bunch of EC numbers). 
BUT there might be cases where the situation is not that clear and where only one reaction is observed.
 
We have only few cases in Swiss-Prot (10 entries, corresponding to 4 protein coding genes): 
- [1 case for rhea:46608 and NO rhea:17989](http://sp.isb-sib.ch/uniprot/?query=annotation%3A%28type%3A%22catalytic+activity%22+rhea%3A46608%29+NOT+RHEA%3A17989&sort=score) 
This case might be dubious and adding the other reaction might be considered

- [9 entries with rhea:17989 and NO rhea:46608](http://sp.isb-sib.ch/uniprot/?query=annotation%3A%28type%3A%22catalytic+activity%22+rhea%3A17989%29+NOT+annotation%3A%28type%3A%22catalytic+activity%22+rhea%3A46608%29&sort=score) (corresponding to 3 protein coding genes)

The second case is more interesting because it concerns proteins with different kinase activities (lipid and glycogen kinases) that also have Ser-protein kinase activity. But these proteins are not classical members of the Ser/Thr protein-kinase activity and for these cases, it would be daring to add the other reaction because we clearly don’t have enough evidence.

**Comment by pgaudet** [comment]
Discussing with @thomaspd 

Indeed that PIK example is interesting - we could keep/modify the Ser kinase activity, but in this case it cannot be a child of Ser/Thr kinase, as it would be a TPV, since it doesn't have the Thr activity.

**Comment by hdrabkin** [comment]
Maybe too little coffe.
If ser/ thr  means either why not? Does the  ser/thr kinase term d mean that something annotated can use either or it's a grouping term (I don't know of any one gene product that can use either?)?

**Comment by pgaudet** [comment]
Ah ok - the definition or Ser/thr kinase seems to state otherwise? 

"Catalysis of the reactions: ATP + protein serine = ADP + protein serine phosphate, **and** ATP + protein threonine = ADP + protein threonine phosphate."

**Comment by hdrabkin** [comment]
Looking at the EC:2.7.11.1, it says neither but has all sorts of synonyms.
https://enzyme.expasy.org/EC/2.7.11.1

**Comment by sylvainpoux** [comment]
Hi @pgaudet,

"it cannot be a child of Ser/Thr kinase, as it would be a TPV, since it doesn't have the Thr activity." 

Actually, we don't know. We know that there is Ser kinase activity but we have NO evidence that it has Thr kinase activity, as it is not a member of the classical family. 

Sylvain

**Comment by hdrabkin** [comment]
And I think the text def should say OR, not AND

**Comment by pgaudet** [comment]
Decision on ontology call: 

- [ ] obsolete GO:0106310 protein serine kinase activity
- [ ]  obsolete GO:0106311 protein threonine kinase activity

**Comment by tberardini** [comment]
@pgaudet Could you please add a little more text about the rationale for the obsoletions for posterity and ease of reference? It made sense during the call today but my memory of that may fade.  Thanks.

**Comment by pgaudet** [comment]
The reason for obsoletion is that GO represents molecular functions at the level of specificity of known enzymes, and these terms represent specific substrates. I've added this to the documentation for creating new terms, http://wiki.geneontology.org/index.php/Principles_for_creating_a_GO_term#Out_of_scope



Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] merged 'GO:0106311 protein threonine kinase activity' into 'GO:0004674 protein serine/threonine kinase activity'
- [x] moved 'GO:0106310 protein serine kinase activity' directly under 'GO:0004672 protein kinase activity'
- [x] added comment on 'GO:0106310 protein serine kinase activity' "Note that this term is to annotate proteins the specifically phosphorylate a serine residue on a protein. An example is human PIKFYVE (UniProt:Q9Y2I7). For dual specificity protein kinases, use 'protein serine/threonine kinase activity' ; GO:0004712."

**Comment by sjm41** [comment]
@pgaudet Just checking: should EC:2.7.11.1 (Non-specific serine/threonine protein kinase) be an xref on 'GO:0004674 protein serine/threonine kinase activity'?
That EC is present as the reference for lots of the synonyms on GO:0004674, but doesn't appear as an xref (looking at the latest go-basic.obo).  Intentional?

**Comment by pgaudet** [comment]
It does look like an omission. I added the xref.

**Comment by sjm41** [comment]
@pgaudet 
Just noticed that the go-edit.obo file lists the EC xref twice on GO:0004674 - I guess one should be removed:

id: GO:0004674
name: protein serine/threonine kinase activity
namespace: molecular_function
alt_id: GO:0004695
alt_id: GO:0004696
alt_id: GO:0004700
alt_id: GO:0106311
def: "Catalysis of the reactions: ATP + protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate." [GOC:bf, PMID:2956925]
synonym: "protein kinase (phosphorylating) activity" NARROW [EC:2.7.11.1]
synonym: "protein phosphokinase activity" NARROW [EC:2.7.11.1]
synonym: "protein serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "protein serine-threonine kinase activity" RELATED [EC:2.7.11.1]
synonym: "protein threonine kinase activity" NARROW []
synonym: "protein-serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine protein kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine(threonine) protein kinase activity" RELATED [EC:2.7.11.1]
synonym: "serine-specific protein kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine/threonine protein kinase activity" RELATED [EC:2.7.11.1]
synonym: "threonine-specific protein kinase activity" NARROW [EC:2.7.11.1]
xref: EC:2.7.11.1 {source="skos:narrowMatch"}
xref: EC:2.7.11.1
is_a: GO:0004672 ! protein kinase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/20114" xsd:anyURI

**Comment by pgaudet** [comment]
Good catch!
