### ISSUE TITLE
merge: microtubule sliding involved in mitotic spindle elongation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20118]
microtubule sliding involved in mitotic spindle elongation

please merge into  "spindle elongation"

combines functions in a process term.
Only used for 2 EXP by PomBase.
Most likely requested by me.

**Comment by pgaudet** [comment]
What about the sibling 'microtubule sliding involved in mitotic metaphase chromosome recapture' ?

**Comment by pgaudet** [comment]
microtubule sliding involved in mitotic metaphase chromosome recapture -> 2 EXP, by PomBase

**Comment by pgaudet** [comment]
Also - don't you want to merge 'microtubule sliding involved in mitotic spindle elongation' into '**mitotic** spindle elongation ?
