### ISSUE TITLE
New regulation term for GO:0002330 'pre-B cell receptor expression'

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#20121]
Hi, 
Could I please request the 'negative regulation of pre-B cell receptor expression' based on  PMID:22949502 "A novel mechanism for the autonomous termination of pre-B cell receptor expression via induction of lysosome-associated protein transmembrane 5"

The authors say "LATM5 appears to induce the prompt downmodulation of surface pre-BCR expression, mainly by accelerating the lysosomal transport and degradation of the large pool of intracellular pre-BCR and, hence, limiting the new supply of pre-BCR to the cell surface."
(figures 6 and 7)

Parent term : GO:0002330    'pre-B cell receptor expression'

Thanks,
Penelope

PS. This is part of ARUK project

**Comment by addiehl** [comment]
@pgaudet See I told you we needed this term #14973

**Comment by pgaudet** [comment]
How about calling this 'pre-B cell receptor production' to be consistent with other similar terms ? 

That term is a bit lonely 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/4782928/95961386-3f074b00-0e05-11eb-8c7c-5eb0155d83aa.png">


Thanks, Pascale

**Comment by pgaudet** [comment]
> I am going to propose that the correct parent of 'pre-B cell receptor expression' is 'cellular developmental process' (not 'gene expression'), because successful expression of pre-B cell receptor 

This sounds like 'pre-B cell receptor expression' is a readout for B cell development. The pre-B cell receptor is a marker that allows to determine the identity of the cell, isn't it ? 

I'll ask GO editors for their input. 

Thanks, Pascale

**Comment by addiehl** [comment]
To explain the biology more completely, from the perspective of a human observer, expression of the pre-B cell receptor is a readout. From the perspective of the developing pro-B cell, successfully expressing the pre-B cell receptor is an essential checkpoint, a test that somatic recombination of at least one of immunoglobulin heavy chain loci has been successful in producing a recombined gene that can be transcribed and translated into a protein chain that folds properly, dimerizes properly, and forms a complex with two copies of the surrogate light chain that can be transported to the cell surface and signal properly as a survival signal to prevent apoptosis of the developing pro-B cell/pre-B cell.  A type of quality control.

So the pre-B cell receptor is more than just a marker, in that it has a unique functional role in the B cell development process.

**Comment by pgaudet** [comment]
I would like to find a solution for this, while explaining clearly why we will not do this for any gene product. 

This is on the agenda for next week's GO tickets jamboree, tagging @thomaspd to see if he has suggestions for how to handle this. 

Thanks, Pascale

**Comment by addiehl** [comment]
How does the GO tickets jamboree work?  Should I attempt to join?
-- Alex

**Comment by thomaspd** [comment]
Alex's comment makes a lot of sense to me, and is really helpful. I have three main comments/questions:

1. "pre-B cell receptor expression" means a lot more than just generic gene expression (central dogma). The GO term needs to be given a proper human-readable text definition to make this clear (that captures Alex's text above). Our goal is to bring expert knowledge to a wider community! We also need the logical definition to be correct, so I think we need to remove the is_a link to gene expression. Currently, the term is also part_of "pre-B cell differentiation" which sounds right to me-- Alex, would you agree?

2. BP terms should represent biological programs carried out by gene products, and if known, should specify the start and end points. So if we take "pre-B cell receptor expression" as a program (that presumably ends with pre-B cell receptor in the cell membrane), where does it start and end? What kinds of gene product activities or sub-processes is it composed of? Does it include the heavy chain recombination program? It clearly requires non-specific processes like transcription and translation, but does it also include specific processes for recognizing a stable complex and loading it in the transport machinery (e.g. a specific cargo receptor)? Does it include processes for controlling the amount of pre-BCR in the membrane?

3. What is the role of LAPTM5 relative to this biological program? Is it regulating the program, or is it part of the program? From the paper, it sounded to me like the amount of pre-BCR in the membrane is tightly controlled, by both a transcriptional mechanism and this new mechanism reported in the paper, mediated by LAPTM5. So if the program includes this control, then LAPTM5 acts as part of the pre-BCR expression program and would be annotated directly to that BP term.

**Comment by thomaspd** [comment]
And yes, Alex, it would be great if you could join the jamboree in some way!

**Comment by addiehl** [comment]
Responses to Paul:
1. Yes, I think that 'pre-B cell receptor expression' is appropriately part_ of 'pre-B cell differentiation'

I'll repeat from above that I believe the correct parent of 'pre-B cell receptor expression' is 'cellular developmental process' (not 'gene expression'), because successful expression of pre-B cell receptor is required for pro-B cells to develop into pre-B cells (otherwise they undergo apoptosis). This fits the definition of 'cellular developmental process':
"A biological process whose specific outcome is the progression of a cell over time from an initial condition to a later condition."

And of course, the name is accepted in the immunology field, which is why I chose it for the GO term, though I agree it is problematic from a GO-naming perspective.

2. I think there's been quite a bit of work to figure out what processes are important in the expression of the pre-B cell receptor, although I don't have time this afternoon to review them.  Certainly the overall process includes the heavy chain recombination program and expression of the surrogate light chain and the Ig-alpha and Ig-beta signaling components of the pre-BCR protein complex.

3.  Based on a quick review of the paper, I think LAPTM5 down regulates 'pre-B cell receptor expression' by causing diversion of pre-BCR protein complexes to the lysosome, as part of negative feedback from successful signaling via the pre-BCR, as a rapid way of clearing out these complexes while the pre-B cell moves on to light chain recombination and synthesis of a proper B-cell receptor complex.

**Comment by thomaspd** [comment]
Thanks Alex, just to follow up:

1. Great. There's already an inferred part_of relation between "pre-B cell receptor expression" and "cellular developmental process", from the subsumption hierarchy of "pre-B cell differentiation". According to the definition, it seems like all parts of larger cell developmental processes would fit the definition for cell development process.

2. Thanks, we should include this information in the text and logical definitions. For the logical def we might need has-part for programs that are re-used elsewhere.

3. This is really interesting. It sounds like this down regulation program involving LAPTM5 would occur after the completion of the pre-BCR expression program, and even after the next process (something we might call pre-BCR signaling, though I don't see that term in GO). I'm imagining something like:
pre-BCR expression --> pre-BCR signaling -->  pre-B cell proliferation --> immature B cell differentiation
Two questions (besides the obvious one whether this simple model makes sense):
a. Would you consider the neg reg of pre-BCR expression to be part of the pre-B cell proliferation program, or a distinct step after the pre-BCR signaling and before the pre-B cell proliferation program?
b. Would pre-BCR signaling be part of pre-B cell differentiation, or a separate process preceding pre-B cell proliferation?

**Comment by pgaudet** [comment]
Edited definition of GO:0002330 pre-B cell receptor expression to 

> The process leading up to expression of the pre-B cell receptor on the surface of pre-B cells, starting with the recombination of an immunuglobulin heavy chain locus, including expression of the surrogate light chain, the  association of the surrogate light chain with the heavy chain, and expression of the complete pre-B cell receptor on the cell surface. pre-B cell receptor expression is a key checkpoint in the transition of pro-B cell to pre-B cell.

@addiehl Please add any missing information

**Comment by pgaudet** [comment]
I think what was requested was done? Please re-open if not.

**Comment by pgarmiri** [comment]
Hi @pgaudet ,

I needed the 'negative regulation of pre-B cell receptor expression' and I can't see the term in the ontology.

Thanks,
Penelope

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140646
+name: negative regulation of pre-B cell receptor expression
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of the process leading up to expression of the pre-B cell receptor on the surface of pre-B cells." [PMID:22949502]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0002330 ! pre-B cell receptor expression
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20121 xsd:string
+created_by: pg
+creation_date: 2021-05-19T10:50:53Z
+

**Comment by pgaudet** [comment]
Sorry about the delay!

**Comment by pgarmiri** [comment]
Thank you @pgaudet !
