### ISSUE TITLE
Add F-P link (proteasome localization)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20129]
GO:1990919 | proteasome-nuclear membrane anchor activity
please add parent
GO:0031144 | proteasome localization

although I don't think this term is really required?

There are 4 EXP annotations

UniProtKB:P38637 | STS1 | involved_in | GO:0031144    proteasome localization | ECO:0000315   IMP | PMID:21075847 |   | 559292 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) | SGD |  
UniProtKB:Q02821 | SRP1 | involved_in | GO:0031144    proteasome localization | ECO:0000315   IMP | PMID:25274630 |   | 559292 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) | SGD |  
UniProtKB:Q8SXU1 | CG5199 | involved_in | GO:0031144    proteasome localization | ECO:0000315   IMP | PMID:16096059 |   | 7227 Drosophila melanogaster | FlyBase |  
UniProtKB:Q9VPF1 | CUT8 | involved_in | GO:0031144    proteasome localization | ECO:0000315   IMP | PMID:16096059 |   | 7227 Drosophila melanogaster | FlyBase

The Flybase ones are 
GO:1990919 | proteasome-nuclear membrane anchor activity

the SGD ones are
Srp1p and Sts1p couple proteasomes to nascent polypeptides emerging from the ribosome for cotranslational degradation 2 3 4
(adaptors)

**Comment by pgaudet** [comment]
All 3 annotation mention nuclear localization. How about merging 

GO:0031144 | proteasome localization
into GO:1990919 | proteasome-nuclear membrane anchor activity
? 

Thanks, Pascale

**Comment by ValWood** [comment]
We can't do that because  it seems that
Srp1p and Sts1p couple proteasomes to nascent polypeptides
rather than the proteasome to the nuclear membrane (unless the SGD description is incorrect)

**Comment by ValWood** [comment]
SRP1 is the ortholog of Cut15 in pombe. this is a importin alpha family nuclear import signal receptor

**Comment by ValWood** [comment]
sts1 is Cut8 in pombe. This is the proteasome-nuclear membrane tether

**Comment by ValWood** [comment]
That's odd that my EXP annotation does not show up in UniProt....
GO:1990919 | proteasome-nuclear membrane anchor activity | EXP | Takeda K et al. (2005)

especially since I requested the term for this Cell paper where it was first described
http://europepmc.org/article/MED/16096059

**Comment by ValWood** [comment]
It's probably because I used EXP.  At PomBase we reserve the binding for direct interactions.

caut8 interacts  with tagged mts4, rpn1 and 12 in a pulldown, but we can't be sure which the direct interaction is (or if it is even a non-tagged subunit) from this experiment. All we know is that cut8 interacts with the proteasome.

**Comment by ValWood** [comment]
@alexsign  do you not ingest EXP evidence code annotations? Actually does GO even take these? We use it a lot, I especially use it if the term and the extension are derived from different types of evidence.

**Comment by ValWood** [comment]
@alexsign  ignore!

**Comment by ValWood** [comment]
So, SRP1 would be transporter (nuclear import signal receptor activity) transport (protein import into nucleus) with the proteasome (or a specific subunit), as cargo - not localization which is broader than transport.

**Comment by krchristie** [comment]
Considering that `GO:1990919 | proteasome-nuclear membrane anchor activity` is an MF term that specifies how a gene product is involved in the BP of `GO:0031144 | proteasome localization`, I don't think these terms are redundant. I'll add the F-P link.
