### ISSUE TITLE
NTR:virus particle binding/host virus attachment protein activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#20137]
Could I request a term to describe the activity of host virus attachment proteins i.e. those that bind virus particles (via a sometimes unspecified protein) and enhance virus entry but are not the main receptor?

e.g. PMID:16051304 - ACE2 is the receptor but other cell surface proteins can augment attchment/entry.

I am thinking something like - virus particle binding or host virus attachment protein activity
 is_a
exogenous protein binding
??
Def: Combining with a virus particle component and mediating attachment of the virus to the cell.
PMID:16051304

GOC:ha

**Comment by pgaudet** [comment]
Is it considered a co-receptor ? Just wondering if we could have a more specific activity.

**Comment by hattrill** [comment]
They don't use the term co-receptor, but the GO definition of coreceptor GO:0015026 "Combining with an extracellular or intracellular messenger, and in cooperation with a nearby primary receptor, initiating a change in cell activity." is compatible with the assayed activity, so I think that 'virus coreceptor activity' would be fine.

**Comment by pgaudet** [comment]
Thanks @hattrill
