### ISSUE TITLE
NTR:Omega-hydroxyceramide transacylase activity and Omega-hydroxyceramide biosynthetic process

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#20130]
Dear GO editors,

could you please consider creating a term for the activity of PNPLA1 described in PubMed=28248318 and corresponding to RHEA:55264:
Reaction=1,2,3-tri-(9Z,12Z)-octadecadienoylglycerol + N-(30-hydroxytriacontanoyl)-sphing-4-enine = di-(9Z,12Z)-octadecadienoylglycerol + N-[30-(9Z,12Z-octadecadienoyloxy)-triacontanoyl]-sphing-4-enine [Rhea:55264]
It should be a child of GO:0016747 if I am correct.

Related to this, the reaction is part of a process that leads to the biosynthesis of omega-hydroxyceramide/acylceramide and I would like to ask you to create the term omega-hydroxyceramide biosynthetic process.
Definition : The chemical reactions and pathways resulting in the formation of omega-hydroxyceramide/acylceramide.
It should be a child of GO:0046513

Thanks in advance for your help.
Best, Lionel

**Comment by lbreuza** [comment]
Hi @pgaudet and @hdrabkin ,
is there a problem with this request for new terms? Please let me know if I can help.
Best, Lionel

**Comment by hdrabkin** [comment]
No; we are attending another workshop at the moment. Your request was Oct 14; hold on

**Comment by hdrabkin** [comment]
+id: GO:0106341
+name: omega-hydroxyceramide transacylase activity
+id: GO:0106342
+name: omega-hydroxyceramide biosynthetic process
done.
