### ISSUE TITLE
cell wall integrity MAPK cascade descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20131]
GO:0000196    cell wall integrity MAPK cascade

but the regulation descendants are

GO:1903139    positive regulation of MAPK cascade involved in cell wall organization or biogenesis | positively_regulates
GO:1903138    negative regulation of MAPK cascade involved in cell wall organization or biogenesis | negatively_regulates
GO:1903137    regulation of MAPK cascade involved in cell wall organization or biogenesis

shouldn't they use the  ancestor term label?

**Comment by pgaudet** [comment]
Is this a process, or a GO-CAM ? The definition is not specific enough to tell. "A MAPK cascade that contributes to cell wall organization or biogenesis."

**Comment by ValWood** [comment]
It is a type of MAPK cascade - one of the 3 in yeast stress,  (stress, pheromone, cell integrity)

there is another one which is not annotated
GO:1903695    MAPK cascade involved in ascospore formation
this one should be a GO-CAM  (I think all of the 3  above could somehow be involved in sporulation). So this one can merge into the parent.

**Comment by ValWood** [comment]
In case this isn't clear
1. relabel 
GO:1903139    positive regulation of MAPK cascade involved in cell wall organization or biogenesis | positively_regulates
to positive regulation of cell wall integrity MAPK cascade 

and the same for the others.
