### ISSUE TITLE
Function in process.  3'-UTR-mediated mRNA stabilization (GO:0070935)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20132]
This clearly represents an activity:

3'-UTR-mediated mRNA stabilization (GO:0070935)
Definition | 
An mRNA stabilization process in which one or more RNA-binding proteins associate with the 3'-untranslated region (UTR) of an mRNA.

How can we represent this as a MF term?

**Comment by ValWood** [comment]
and 
protein stabilization:
https://www.pombase.org/term/GO:0050821
all these are from IBA

**Comment by Antonialock** [comment]
For rnc1 (one of the proteins annotated to 3'-UTR-mediated mRNA stabilization (GO:0070935)) the exact mechanism is not known (note that it's now been shown also to destabilize RNAs)

eg https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6946801/
"How can phosphorylated Rnc1 promote either mRNA stabilization or destabilization? An attractive possibility is that alternative phosphorylation of Rnc1 by Sty1 and/or Pmk1 at one or several S/TP sites might trigger its function as an mRNA stabilizer or destabilizer depending on the environmental context. Protein-RNA interactions were initially thought to be mostly mediated by canonical RNA-binding regions, like KH domains, that form stable secondary and tertiary structures. However, recent studies including proteome-wide data have revealed unexpected roles for intrinsically disordered protein regions in RNA binding (27). Interestingly, all of the Rnc1 MAPK phosphorylation sites (T50, T45, T171, T177, S278, and S286) are excluded from KH domains and lie within predicted intrinsically disordered regions of the protein (Fig. 4A). Alternative phosphorylation at these sites might thus elicit major changes in Rnc1 conformation and affect its ability to bind mRNAs with different affinity. The stabilizer/destabilizer role for Rnc1 might also be imposed by specific structural features of its target mRNAs. Rnc1 binds to several UCAU repeats in the 3′ UTR of pmp1+ mRNA, while mutation at these sequences impedes Rnc1 binding and prompts mRNA destabilization (5, 6). These repeats belong to the consensus YCAY RNA-binding element that is bound by KH-domain RBPs like the mammalian onconeural antigen Nova-1 (28). However, in contrast to the high number of UCAU motifs found in the long pmp1+ 3′ UTR, they have a scarce presence in the shorter wak1+ (0), wis1+ (1), atf1+ (2), pyp1+ (0), and pyp2+ (3) 3′ UTRs (Fig. S4). In addition, the possibility that Rnc1 binds to those mRNAs via UCAU motifs located at their open reading frames (ORFs) or 5′ UTRs, or through other unknown motifs, cannot be discarded."

**Comment by Antonialock** [comment]
mRNA 3'-UTR AU-rich region binding, _has_substrate_ pmc1, _involved_in_  negative regulation or mRNA catabolic process (i.e. the mRNA stabilization term) 

mRNA 3'-UTR AU-rich region binding, _has_substrate_ [whatever they show in the 2020 paper cited above], _involved_in_ positive regulation or mRNA catabolic process (i.e. the mRNA destabilization term)

?

**Comment by ValWood** [comment]
I would favour a MF 
 "mRNA stabilizer" or "mRNA destabilizer" instead of process terms, if the role of the protein is to function as a stabilizer.

**Comment by RLovering** [comment]
As many users rely on BP term enrichments please could you confirm the BP term that this protein would be associated with once the term outcomes are agreed
Thanks and Happy New Year ;)

**Comment by pgaudet** [comment]
regulation of translation ?

**Comment by ValWood** [comment]
"stability" has multiple meanings. There is the very direct "binding to a protein  or mRNA to stabilize it" (MF), but stability is also used for stability of protein or mRNA is over its lifetime" which is not really determined by a single process, but is a balance between  translation, or mRNA/protein catabolism.  So, is stabilization itself really a process ?

**Comment by ValWood** [comment]
Closing, we will need to address this as part of FRNA processing branch and there are other tickets
