### ISSUE TITLE
GO:0140456 name correction

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#20158]
I reported problems with the name and parentage of GO:0140456 in https://github.com/geneontology/go-ontology/issues/17971#issuecomment-627247570. It now looks like the parentage got fixed, but the name is still wrong. It should be "initial meiotic spindle pole body separation" (or it could revert to the name originally added: "initial spindle pole body separation involved in meiosis I").

**Comment by pgaudet** [comment]
thanks for reporting this.
