### ISSUE TITLE
Platelet activating factor production/secretion misplaced ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20154]
Hi @addiehl 

GO:0002392 	platelet activating factor secretion and
GO:0002535 	platelet activating factor secretion involved in inflammatory response 	

are placed under both 'lipid export' and 'cytokine secretion (soon to be merged with 'cytokine production, as we decided in #19115) 

However I think 'cytokine' is incorrect as a parent, since a cytokine is a peptide, and PAF is a lipid - is this right ? 

If this is the case, we should also rename  GO:0002390 platelet activating factor production -> biosynthetic process. 

<img width="847" alt="image" src="https://user-images.githubusercontent.com/4782928/96542649-d86dab80-12a2-11eb-8c06-b0014df5f5bd.png">

Thanks, Pascale

**Comment by addiehl** [comment]
I agree platelet activating factor is a lipid and should not be classified as a cytokine.

Looking at the set of platelet activating factor terms and their annotations (list below), I think the interesting ones are the ones with annotations **and** GO:0002391 'platelet activating factor production involved in inflammatory response'.  All the others (GO:0002390, GO:0002392, GO:0002535) should be merged into GO:0002391.

I would also propose that GO:0002391 be given the sole parent GO:0002532 'production of molecular mediator involved in inflammatory response' and has_part GO:0006663 'platelet activating factor biosynthetic process'.  This would be analogous to the current ontology structure for the term 'arachidonic acid metabolite production involved in inflammatory response', as arachidonic acid metabolites are analogous non-peptide/protein mediators of the inflammatory response.

This solution eliminates 3/4 unannotated terms, and retains the most biologically interesting one.  Of course, when folks in some distant time actually do proper annotation of gene products involved in the inflammatory response, they will request the regulation terms for GO:0002391, and we can create them at that time.

Current annotations in QuickGO
Term	Annotations
GO:0002390    platelet activating factor production	
GO:0002392    platelet activating factor secretion	
GO:0006663    platelet activating factor biosynthetic process	172 annotations
GO:0031859    platelet activating factor receptor binding	6 annotations
GO:0047179    platelet-activating factor acetyltransferase activity	175 annotations
GO:0004992    platelet activating factor receptor activity	443 annotations
GO:0062234    platelet activating factor catabolic process	109 annotations
GO:0046469    platelet activating factor metabolic process	352 annotations
GO:0002535    platelet activating factor secretion involved in inflammatory response	
GO:0002391    platelet activating factor production involved in inflammatory response

**Comment by pgaudet** [comment]
Thanks @addiehl , this is very useful!

**Comment by pgaudet** [comment]
- [x] Merged GO:0002390, GO:0002392, GO:0002535 into GO:0002391 'platelet activating factor production involved in inflammatory response'.

 - [x] platelet activating factor production involved in inflammatory response' : Added logical definition 
 production of molecular mediator involved in inflammatory response
 has_part GO:0006663  platelet activating factor biosynthetic process

Thanks, Pascale
