### ISSUE TITLE
NTR: regulation of osmosensory signaling MAPK cascade

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20162]
Negative regulation of GO:0000161
osmosensory signaling MAPK cascade

PMID:31911490

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140531
+name: regulation of osmosensory signaling MAPK cascade
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of osmosensory signaling MAPK cascade." [PMID:31911490]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0000161 ! osmosensory signaling MAPK cascade
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20162 xsd:anyURI
+created_by: pg
+creation_date: 2020-10-20T15:38:10Z
+
+[Term]
+id: GO:0140532
+name: negative regulation of osmosensory signaling MAPK cascade
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of osmosensory signaling MAPK cascade." [PMID:31911490]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0000161 ! osmosensory signaling MAPK cascade
+property_value: term_tracker_item "biological_process" xsd:string
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20162 xsd:anyURI
+created_by: pg
+creation_date: 2020-10-20T15:39:24Z
+
