### ISSUE TITLE
taxon restrictions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20161]
Please add only in metazoa
GO:0048273    mitogen-activated protein kinase p38 binding | 190 annotations
GO:0038066    p38MAPK cascade | 635 annotations
GO:1900744    regulation of p38MAPK cascade | 2,831 annotations
GO:1903753    negative regulation of p38MAPK cascade | 451 annotations
GO:1900745    positive regulation of p38MAPK cascade

Our users are using this term for the orthologous pathway, but for historical? reason we are using the yeast label for this pathway :  "GO:0000161    osmosensory signaling MAPK cascade"

(I don't really like any of these terms, but  we only want to use one not multiple)

**Comment by pgaudet** [comment]
Fixed the taxon constraints as requested. What are you asking for "GO:0000161 osmosensory signaling MAPK cascade" ?

**Comment by ValWood** [comment]
That term  belongs with the previous sentence...

**Comment by ValWood** [comment]
So "GO:0000161 osmosensory signaling MAPK cascade" is the specific stress-cascade term used by fung

**Comment by pgaudet** [comment]
Are you saying that "GO:0000161 osmosensory signaling MAPK cascade" is the same as "GO:0038066    p38MAPK cascade"?

**Comment by ValWood** [comment]
Yes. I can't remember  the exact details of why both are kept.
@ukemi  worked on this for the signalling meeting.

I do think they could probably be merged.  .......

**Comment by pgaudet** [comment]
If I merge then the Metaza taxon constraint is wrong ?

**Comment by ValWood** [comment]
>If I merge then the Metazoa taxon constraint is wrong ?

Yes.
It's some weirdness why both terms were kept.

p38MAPK is a human gene name and there are 4 p38-type MAPKs.
I don't know if this term was meant to refer to one, or all of them, that isn't clear.

Yeast people do not **historically** call this osmolarity MAPK pathway "p38MAPK " but the younger generation are less hung up on the names and more interested in sematics and clarity. 
I do think we could probably merge although we would need to look into the history

it could be called something like "p38-type MAPK  stress cascade"
It is called osmolarity sensing because that seems to be the major stress and activates the kinase fully, but other stresses also activate it (for example cytoskeleton stress will activate to a lower degree, and also other stresses).   I think this is one example where people got hung up on the labels rather than the orthology. However, it is all terribly complicated. You have the core pathway and then different stresses feed in at different points.  I think "MAPK cascades"  are one of the places where a lot of progress was made  but there are still things to fix...
