### ISSUE TITLE
GO:0000738  functions (nucleases) in the BP ontology

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20175]
GO:0000738    DNA catabolic process, exonucleolytic
used for 14 EXP  exonucleases. Can this merge into DNA catabolic process?

Also used for PAINT mapping

**Comment by pgaudet** [comment]
But we have both

- GO:0000737 DNA catabolic process, endonucleolytic
-  GO:0000738 DNA catabolic process, exonucleolytic 

Do you suggest we merge both ? 

I think those represent functions anyway. 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes, I suspect all are already annotated to the MF as nucleases don't usually get missed which is why I suggested a merge. But obsoletion is  cleaner to ensure that no annotation is missed.

**Comment by pgaudet** [comment]
Done in  #24075
