### ISSUE TITLE
conflicting taxon constraint involving animal zygote

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#20176]
I'm trying to bring in taxon constraints from CL. I think there's an error in GO with [double fertilization forming two zygotes](http://purl.obolibrary.org/obo/GO_0009677). It is a subclass of [fertilization](http://purl.obolibrary.org/obo/GO_0009566), which references [animal zygote](http://purl.obolibrary.org/obo/CL_0000365).

However there is a taxon constraint on [double fertilization forming two zygotes](http://purl.obolibrary.org/obo/GO_0009677) restricting it to [Gnetophyta](http://purl.obolibrary.org/obo/NCBITaxon_58022):

## [double fertilization forming two zygotes](http://purl.obolibrary.org/obo/GO_0009677) EquivalentTo [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [double fertilization forming two zygotes](http://purl.obolibrary.org/obo/GO_0009677) SubClassOf [fertilization](http://purl.obolibrary.org/obo/GO_0009566)
    - [fertilization](http://purl.obolibrary.org/obo/GO_0009566) EquivalentTo [reproductive process](http://purl.obolibrary.org/obo/GO_0022414) and ([results_in_fusion_of](http://purl.obolibrary.org/obo/GOREL_0002005) some [germ cell nucleus](http://purl.obolibrary.org/obo/GO_0043073)) and ([results in formation of](http://purl.obolibrary.org/obo/RO_0002297) some [animal zygote](http://purl.obolibrary.org/obo/CL_0000365))
      - [animal zygote](http://purl.obolibrary.org/obo/CL_0000365) SubClassOf [early embryonic cell](http://purl.obolibrary.org/obo/CL_0000007)
        - [early embryonic cell](http://purl.obolibrary.org/obo/CL_0000007) SubClassOf [embryonic cell](http://purl.obolibrary.org/obo/CL_0002321)
          - [embryonic cell](http://purl.obolibrary.org/obo/CL_0002321) SubClassOf [animal cell](http://purl.obolibrary.org/obo/CL_0000548)
            - [animal cell](http://purl.obolibrary.org/obo/CL_0000548) SubClassOf [only_in_taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208)
              - [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208) SubClassOf [Opisthokonta](http://purl.obolibrary.org/obo/NCBITaxon_33154)
      - [results in formation of](http://purl.obolibrary.org/obo/RO_0002297) SubPropertyOf: [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295)
  - [double fertilization forming two zygotes](http://purl.obolibrary.org/obo/GO_0009677) SubClassOf [only_in_taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Gnetophyta](http://purl.obolibrary.org/obo/NCBITaxon_58022)
    - [Gnetophyta](http://purl.obolibrary.org/obo/NCBITaxon_58022) SubClassOf [Acrogymnospermae](http://purl.obolibrary.org/obo/NCBITaxon_1437180)
      - [Acrogymnospermae](http://purl.obolibrary.org/obo/NCBITaxon_1437180) SubClassOf [Spermatophyta](http://purl.obolibrary.org/obo/NCBITaxon_58024)
        - [Spermatophyta](http://purl.obolibrary.org/obo/NCBITaxon_58024) SubClassOf [Euphyllophyta](http://purl.obolibrary.org/obo/NCBITaxon_78536)
          - [Euphyllophyta](http://purl.obolibrary.org/obo/NCBITaxon_78536) SubClassOf [Tracheophyta](http://purl.obolibrary.org/obo/NCBITaxon_58023)
            - [Tracheophyta](http://purl.obolibrary.org/obo/NCBITaxon_58023) SubClassOf [Embryophyta](http://purl.obolibrary.org/obo/NCBITaxon_3193)
              - [Embryophyta](http://purl.obolibrary.org/obo/NCBITaxon_3193) SubClassOf [Streptophytina](http://purl.obolibrary.org/obo/NCBITaxon_131221)
                - [Streptophytina](http://purl.obolibrary.org/obo/NCBITaxon_131221) SubClassOf [Streptophyta](http://purl.obolibrary.org/obo/NCBITaxon_35493)
                  - [Streptophyta](http://purl.obolibrary.org/obo/NCBITaxon_35493) SubClassOf [Viridiplantae](http://purl.obolibrary.org/obo/NCBITaxon_33090)
    - [only_in_taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Viridiplantae](http://purl.obolibrary.org/obo/NCBITaxon_33090) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Opisthokonta](http://purl.obolibrary.org/obo/NCBITaxon_33154)

**Comment by balhoff** [comment]
Perhaps fertilization should not be linked to animal zygote?

**Comment by ukemi** [comment]
Double fertilization process that occurs in flowering plants. PMID:18650119

**Comment by balhoff** [comment]
Seems like we need a more general zygote.

**Comment by ukemi** [comment]
Even then, I think we should be careful. If I remember what @tberardini taught me some time ago, the double fertilization results in the formation of the zygote and the endosperm. But I could be mistaken. Would the above def be necessary and sufficient if we just include a generic zygote?

**Comment by ukemi** [comment]
Actually we would be ok because this definition is just for fertilization, as long as the sporophyte of a moss is considered a zygote.

**Comment by balhoff** [comment]
I don't see any other kind of zygote in CL besides 'animal zygote'. I assume we want 'fertilization' to apply to both animals and plants. PO has [plant zygote](http://purl.obolibrary.org/obo/PO_0000423). Should I make a CL issue?

**Comment by cmungall** [comment]
I agree CL should have general zygote

We'll also want to coordinate with PO to ensure we have bridging axioms PO->CL

**Comment by balhoff** [comment]
Discussed on GO call 2020-10-26: remove logical definition for now, confer with @tberardini about usefulness of generic fertilization/zygote, possibly add new term to CL.

**Comment by balhoff** [comment]
@tberardini we were hoping to get your opinion on some plant-oriented questions:

- Is it appropriate and useful for GO to have the 'fertilization' term grouping both plant and animal fertilization processes?
- If so is it sensical to have a 'zygote' term in CL that groups plant and animal zygotes?

Thanks!

**Comment by tberardini** [comment]
@lreiser : looping you in here

**Comment by ukemi** [comment]
A paper that might help decide.
PMID:29170007

**Comment by tberardini** [comment]
Yep.  That's the one I was just looking at.

https://pubmed.ncbi.nlm.nih.gov/29170007/

**Comment by balhoff** [comment]
I closed this because I made the change to the fertilization definition, but don't mean to end discussion.

**Comment by pgaudet** [comment]
Waiting on the zygote term in CL.
