### ISSUE TITLE
 merge MF in BP term GO:0051103 | DNA ligation involved in DNA repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20173]
Please can we remove this term. I am continually picking up mappings to this to the fission yeast 
DNA replicationligase because in fission yeast the functions are split between paralogs (I think- something unusual anyway), and this is a function in the process ontology

GO:0051103 | DNA ligation involved in DNA repair

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-annotation/issues/3327

**Comment by pgaudet** [comment]
There is also a child term: GO:0006288 base-excision repair, DNA ligation 

There are only 10 EXP annotations to both terms. I removed the annotations to non-DNA ligases (HMG1, HMG2 and PAXX). , so we can merge into the parent ' GO:0006266 DNA ligation'. 

OK ? 


Thanks, Pascale

**Comment by ValWood** [comment]
If these are already annotated as MF 'ligases;' isn't the "DNA repair " part more important here? (note that some ligases function in replication and repair, but some are specific for repair).
My instinct would be to merge into repair (ligation is an activity anyway, I don't  know why we need it)

GO:0006266 DNA ligation' has half a million annotation,  but if you filter the MF inferences and the non0-experimental you are left  with 35 annotations (some of which are from 'DNA ligation involved in DNA repair), so will be handled above. Most of the remaining are clearly ligases and should have a "DNA ligase" annotation.
Why not obsolete this too, and just recommend people use the ligase MF (the process is likely   either DNA replication or  DNA repair)

**Comment by ValWood** [comment]
also

UniProtKB:Q8BTF7 | Lig4 | acts_upstream_of_or_within | GO:0051102    DNA ligation involved in DNA recombination

which would merge into recombination

**Comment by pgaudet** [comment]
@cmungall would like to see fewer merges, especially when terms are not equivalent. So I will obsolete those with a 'REPLACED BY'. OK ?

**Comment by ValWood** [comment]
to me this seems like a good case for a merge.

So @cmungall  which types of change are appropriate for a merging? (I assumed it was when 
a) the meaning was identical OR 
b)  the meaning was narrower, but the concept of the narrower term did not belong in GO (I.e the old label could be a narrow synonym) ...but I see that this might be a bit confusing and getting people to check the annotations is not a bad thing here (the numbers are not so high so it won't be very onerous).

Just need to know for future....

**Comment by ValWood** [comment]
Out of date, see:
https://github.com/pombase/pombase-chado/issues/1192
