### ISSUE TITLE
what does this mean? GO:0050901    leukocyte tethering or rolling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20174]
This term is a bit crazy
GO:0050901    leukocyte tethering or rolling

seems to combine a function 'tethering" and a process "rolling" (if it is actually a process (sounds like cell migration?)

**Comment by addiehl** [comment]
The term is fine.  Please read the definition and some of the four PMIDs and the relevant textbook chapter it is based on, or at least look at the cited Wikipedia entry.  This is a very well studied process in leukocyte migration.

I would point out that there are 275 annotations to this term, so obviously annotators have it figured out.

**Comment by addiehl** [comment]
Here is the slide I use when I teach about the Gene Ontology on an annual basis, where I talk about how some GO processes are parts of other GO processes.  Also, if you want to add the synonym "rolling adhesion" to this term, I don't mind.  I based the term name on other sources.

![Screen Shot 2020-10-20 at 5 14 35 PM](https://user-images.githubusercontent.com/11201751/96645101-1648ef00-12f8-11eb-8031-b8af7578d134.png)

**Comment by ValWood** [comment]
but it combines 2 concepts? one of which (tethering) is a MF.
and t isn't ideal to have "OR"  in terms.

"leukocyte extravasation"  seems a more logical name?

**Comment by addiehl** [comment]
Leukocyte extravasation AKA 'cellular extravasation' is a multipart process.  The following four GO terms, including 'leukocyte tethering or rolling' are part of 'cellular extravasation', listed here in the order they occur temporally:  
'leukocyte tethering or rolling'
Transient adhesive interactions between leukocytes and endothelial cells lining blood vessels. Carbohydrates on circulating leukocytes bind selectins on the vessel wall causing the leukocytes to slow down and roll along the inner surface of the vessel wall. During this rolling motion, transitory bonds are formed and broken between selectins and their ligands. Typically the first step in cellular extravasation (the movement of leukocytes out of the circulatory system, towards the site of tissue damage or infection).

'leukocyte adhesive activation'
The activation of loosely bound or rolling leukocytes by signals displayed on blood vessel endothelial cells, which is typically the second step in cellular extravasation.

'leukocyte activation-dependent arrest'
The formation of an integrin-dependent strong adhesive bond between leukocytes and blood vessel endothelial cells which is dependent on prior activation of the leukocyte and leads to the firm attachment of the leukocyte to the endothelial surface, typically the third step in cellular extravasation.

'diapedesis'
The passage of a leukocyte between the tight junctions of endothelial cells lining blood vessels, typically the fourth and final step of cellular extravasation.'

The names and definitions are based on the literature circa 2004, which was already extensive on this set of processes.  If you object to 'leukocyte tethering or rolling', then we can switch the term name to 'leukocyte rolling adhesion' with the original name as an exact synonym.  This is a process that involves multiple executions of adhesive MFs, not necessarily all with the same exact receptor ligand pairs.  The overall result is to slow down a passing leukocyte as it passes by activated endothelial cells lining a blood vessel.  There are lots of great video describing the rolling of leukocytes mediated by Selectins along endothelial cells.

https://www.youtube.com/watch?v=Ys6RlglMTMg

**Comment by ValWood** [comment]
Hi @addiehl it just sounded odd with the "OR".
There is a precedent for or in GO terms but it is usually and/or

'leukocyte tethering and rolling' might be more ontologically correct and seems to match PubL+Med more closely  (the term is a composite of functions that are difficult to separate, so I can see why it is a single term).


But OK to close.

**Comment by addiehl** [comment]
Sounds good to me.

**Comment by ValWood** [comment]
Actually, I looked at the video because I was interested. The  community use  of the word 'tethering'  seemed strange,  to describe weak adhesion because tethering usually implies something more 'permanent' to 'restict movement' and this tethering is transient adhesion to enable movement.
So I checked the parent, and there seems to be a term which describes exactly this process

GO:0061756    leukocyte adhesion to vascular endothelial cell
Definition (GO:0061756 GONUTS page)
The attachment of a leukocyte to vascular endothelial cell via adhesion molecules. 

so I wondered why this was not a descendant of "cellular extravasation" and why 2 terms were required.
However, presumably the transient  binding and  the  'rolling'  must also occur outside of  the extrusion process? In which case the rolling  seems to precede the extrusion process.

There does appear to be an actual  'tethering'  step in extravasation- a  tighter adhesion when a leukocyte is immobilised before extrusion - this would  seem to be the more logical  'start' point for the process? (note that rolling is really a consequence of the balance between blood flow and weak adhesion, it stops when the blood flow is prevented, so it isn't itself part of  'migration' which refers to  'self-propelled movement'.

No worries if you don't want to reopen but I wanted to note these logical inconsistencies because they   will likely cause problems  for logical definitions somewhere down the line.

**Comment by addiehl** [comment]
Some related discussion regarding GO:0061756 in #12276.

The rolling is not accidental, but rather allows the leukocyte to probe for highly activated endothelial cells based on availability of integrin ligands.  Yes it relies on the force of the blood flow, but the system has evolved to enable tethering and slow rolling to allow for the leukocyte to find a good spot to pass through the vessel wall.  So rolling is part of the process.

**Comment by ValWood** [comment]
I didn't say 'accidental', it's clearly evolved. But it isn't a type of 'migration' because it isn't self-propelled.

**Comment by addiehl** [comment]
Not to get to win the weeds, but arguably while it isn't self-propelled on a cellular level, it is propelled by organismal processes and clearly the movement of leukocytes in blood is a key facilitator of their migration throughout the body.

**Comment by pgaudet** [comment]
I've added links to this ticket and the other mentioned #12276 - Let me know if term labels or definitions should be changed - I am assuming this is closed.
