### ISSUE TITLE
NTR response to cytoskeletal stress

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20189]
NTR: response to  actin cytoskeletal stress
def
Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of perturbations or damage to the actin  cytoskeleton.

descendent of 
cellular response to stress

~NTR regulation of mitotic actomyosin contractile ring maintenance
descendant of
GO:1904789 | regulation of mitotic actomyosin contractile ring maintenance~

(I want to use this term in conjunction with the  stress-activated MAP kinase cascade)

Note that these 4 (unused)  terms could merge into my proposed term, which represents a real biological program (latrunculin is used as a condition to disrupt the actin cytoskeleton)
GO:1903956    response to latrunculin B
GO:1904804    response to latrunculin A
GO:1903957    cellular response to latrunculin B
GO:1904805    cellular response to latrunculin A

PMID:32915139 - Stress-activated MAPK signalling controls fission yeast actomyosin ring integrity by modulating formin For3 levels.

**Comment by ValWood** [comment]
Hi Karen. Let me know if there is a problem with this one. It was one of our community  curation papers and I'd like to finalise
https://www.pombase.org/reference/PMID:32915139

**Comment by krchristie** [comment]
> NTR: response to actin cytoskeletal stress
> def: Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of perturbations or damage to the actin cytoskeleton. 
> is_a: cellular response to stress

> Note that these 4 (unused) terms could merge into my proposed term, which represents a real biological program (latrunculin is used as a condition to disrupt the actin cytoskeleton)
> GO:1903956 response to latrunculin B
> GO:1904804 response to latrunculin A
> GO:1903957 cellular response to latrunculin B
> GO:1904805 cellular response to latrunculin A

I think this term sounds fine, and I'm delighted to merge in the 4 latrunculin terms.
 

> NTR regulation of mitotic actomyosin contractile ring maintenance
> is_a: GO:1904789 | regulation of mitotic actomyosin contractile ring maintenance

I'm not sure what you're asking for here since the name of the new term you've listed is identical to the name of the suggested parent term.

> PMID:32915139 - Stress-activated MAPK signalling controls fission yeast actomyosin ring integrity by modulating formin For3 levels.

**Comment by ValWood** [comment]
I don't know why I requested
GO:1904789 | regulation of mitotic actomyosin contractile ring maintenance
I already used it for PMID:32915139

**Comment by krchristie** [comment]
So you just need a new term for `response to actin cytoskeletal stress`

**Comment by ValWood** [comment]
That's it!
