### ISSUE TITLE
"diphosphoinositol-polyphosphate diphosphatase activity" and related terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20186]
Just trying to work out the difference/relationship between these terms, which all have xref: EC:3.6.1.52.

Should the last two be children of the first one perhaps?

id: GO:0008486
name: diphosphoinositol-polyphosphate diphosphatase activity
def: "Catalysis of the reaction: diphospho-myo-inositol polyphosphate + H2O = myo-inositol polyphosphate + phosphate." [EC:3.6.1.52]
synonym: "diphospho-myo-inositol-polyphosphate diphosphohydrolase activity" RELATED [EC:3.6.1.52]
synonym: "diphosphoinositol polyphosphate phosphohydrolase activity" EXACT []
synonym: "diphosphoinositol-polyphosphate phosphohydrolase activity" RELATED [EC:3.6.1.52]
synonym: "DIPP activity" RELATED [EC:3.6.1.52]
xref: EC:3.6.1.52
xref: KEGG_REACTION:R05777
xref: MetaCyc:3.6.1.52-RXN
is_a: GO:0016462 ! pyrophosphatase activity

id: GO:0052840
name: inositol diphosphate tetrakisphosphate diphosphatase activity
def: "Catalysis of the reaction: inositol diphosphate tetrakisphosphate + H2O = inositol 1,3,4,5,6-pentakisphosphate + phosphate." [MetaCyc:RXN-10963, PMID:10827188, PMID:11502751]
xref: EC:3.6.1.52
xref: MetaCyc:RXN-10963
xref: Reactome:R-HSA-1855166 "PP-IP4 is dephosphorylated to I(1,3,4,5,6)P5 by NUDT4 in the cytosol"
is_a: GO:0016462 ! pyrophosphatase activity

id: GO:0052842
name: inositol diphosphate pentakisphosphate diphosphatase activity
def: "Catalysis of the reaction: inositol diphosphate pentakisphosphate + H2O = inositol hexakisphosphate + phosphate." [MetaCyc:RXN-10964, MetaCyc:RXN-10977, MetaCyc:RXN-10978, PMID:10827188, PMID:11502751]
xref: EC:3.6.1.52
xref: KEGG_REACTION:R05779
xref: Reactome:R-HSA-1855198 "5-PP-IP5 is dephosphorylated to IP6 by NUDT(1) in the cytosol"
xref: Reactome:R-HSA-2023971 "1/3 PP-IP5 is dephosphorylated to IP6 by NUDT(1) in the cytosol"
xref: RHEA:22384
is_a: GO:0016462 ! pyrophosphatase activity

**Comment by sjm41** [comment]
Meant to tag @hdrabkin ....

**Comment by hdrabkin** [comment]
The EC corresponds to 

RHEA:22384 | 5-diphospho-1D-myo-inositol 1,2,3,4,6-pentakisphosphate +   H2O =   1D-myo-inositol hexakisphosphate +   H+ +   phosphate | EC:3.6.1.52 Diphosphoinositol-polyphosphate diphosphatase | 1 protein(s) (UniProtKB)
-- | -- | -- | --
  | RHEA:56312 | 3,5-bis(diphospho)-1D-myo-inositol 1,2,4,6-tetrakisphosphate +   H2O =   3-diphospho-1D-myo-inositol 1,2,4,5,6-pentakisphosphate +  2 H+ +   phosphate | EC:3.6.1.52 Diphosphoinositol-polyphosphate diphosphatase | 1 protein(s) (UniProtKB)
  | RHEA:59500 | 5-diphospho-1D-myo-inositol 1,3,4,6-tetrakisphosphate +   H2O =   1D-myo-inositol 1,3,4,5,6-pentakisphosphate +   H+ +   phosphate | EC:3.6.1.52 Diphosphoinositol-polyphosphate diphosphatase

**Comment by sjm41** [comment]
@pgaudet Closing this. In #23401 we removed the EC from GO:0052840 & GO:0052842 based on the EC reaction definition ("Diphospho-myo-inositol polyphosphate + H(2)O <=> myo-inositol polyphosphate + phosphate") matching the GO:0008486 def.
