### ISSUE TITLE
Merge shikimate biosynthesis into chorismate biosynthesis?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#20182]
Shikimate is an intermediate in the chorismate biosynthesis pathway (also known as the shikimate pathway).
The end product of this pathway is chorismate. 

Therefore it seems superfluous to have terms for both "shikimate biosynthetic process" and for "chorismate biosynthetic process".

There are only 5 EXP annotations to shikimate biosynthetic process
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0033587&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

It looks like they could be merged into "chorismate biosynthetic process"

Also add synonym "shikimate pathway" to chorismate biosynthetic process"

**Comment by Antonialock** [comment]
eg

Figure 3. Genetic organization of the shikimate pathway in bacteria (first row), higher plants (second row) and fungi and Apicomplexa (last row). In bacteria, each enzyme is encoded by a single gene. Plants have a similar organization like bacteria except for DHQase and SDH which are fused to a bifunctional enzyme complex. In contrast, the genes of DHQS, EPSPS, SK, SDH and DHQase are fused to a pentafunctionals complex in fungi and certain apicomplexan species.  

![image](https://user-images.githubusercontent.com/12727506/96704319-dd5a5a00-138b-11eb-95b8-81a3d67d3c9a.png)

And

Figure 1 The aromatic amino acid pathways support the formation of numerous natural products in plants. The shikimate pathway (shown in green) produces chorismate, a common precursor for the tryptophan (Trp) pathway (blue), the phenylalanine/tyrosine (Phe/Tyr) pathways (red ), and the pathways leading to folate, phylloquinone, and salicylate. Trp, Phe, and Tyr are further converted to a diverse array of plant natural products that play crucial roles in plant physiology, some of which are essential nutrients in human diets (bold ).

![image](https://user-images.githubusercontent.com/12727506/96703729-1b0ab300-138b-11eb-85f7-ea0535d88b85.png)

**Comment by pgaudet** [comment]
@marcfeuermann Just checking that this sounds right to you

**Comment by marcfeuermann** [comment]
Shikimate is indeed a precursor of  folates and aromatic amino acids via chorismate. So the shikimate and chorismate "pathways" represent the same pathway and the BPs could be merged. In the literature, the term "shikimate pathway" is often used and should be put as a synonym (if not as the main term). So I agree with the proposal.
Best regards,
Marc.

**Comment by pgaudet** [comment]
Thanks !

**Comment by Antonialock** [comment]
don't know if you spotted this @pgaudet 
"Also add synonym "shikimate pathway" to chorismate biosynthetic process" ?

**Comment by pgaudet** [comment]
I had missed that ! thanks !

I added 'shikimate pathway' as a RELATED synonym, let me know if that's  not correct. It's always nice if people can suggest synonym types. 

Thanks, Pascale

**Comment by Antonialock** [comment]
I think it can be exact
from wikipedia:
"The pathway starts with two substrates, phosphoenol pyruvate and erythrose-4-phosphate, and ends with chorismate,"

https://en.wikipedia.org/wiki/Shikimate_pathway

**Comment by pgaudet** [comment]
OK - note that there are two similar synonyms:
* GO:0009094  L-phenylalanine biosynthetic process -> "phenylalanine biosynthetic process, shikimate pathway" RELATED 
* GO:0009073  aromatic amino acid family biosynthetic process  -> "aromatic amino acid family biosynthetic process, shikimate pathway" RELATED 

just wanted to point that out. 

Thanks, Pascale

**Comment by Antonialock** [comment]
It's upstream of aromatic aa synthesis (phenylalanine, tryptophan and tyrosine). 

e.g. google hits for "shikmate aromatic"

"The aromatic amino acids are synthesized via the shikimate pathway followed by the branched aromatic amino acid metabolic pathway,"
"The shikimate pathway consists of seven enzymatic reactions whose end product chorismate is the precursor for the synthesis of the aromatic .."

If "upstream"/"often mentioned in the same sentence" fits the def of a 'related synonym' then that should be ok?

**Comment by Antonialock** [comment]
(as theplant image above shows it's also upstream of folate and vit K1, salicylic acid biosynthesis....so it is not only upstream of aromatic aa biosynth)
