### ISSUE TITLE
NTR tryptophan binding

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#20181]
the chorismate mutase aro7 is allosterically regulated by tyrosine (inhibitor) and tryptophan (activator) 
There is a term for "tyrosine binding", so I guess it is ok to request "tryptophan binding" as well?

PMID:31498992

**Comment by ValWood** [comment]
I was thinking that when I came to annotate these cases where a substrate inhibited the activity of an enzyme I would use "sensor molecule activity" because here "chorismate mutase " is a 'sensor" for amino acid levels.


Just plain "amino acid binding" doesn't tell us much? but  tyrosine/tryptophan sensor is more informative.

What do you think @pgaudet ?

**Comment by pgaudet** [comment]
I agree about creating the specific amino acid binding terms - also there are not so many. 

However is allosteric regulation a sensor activity ? I know this has been discussed in the context of GO-CAM specifications. 

@vanaukenk @ukemi @thomaspd

**Comment by Antonialock** [comment]
if helpful; the activity of chorismate mutase steers biosynthesis towards phenylalanine and tyrosine, and away from tryptophan (it's a branch point enzyme)

Many cytoplasmic fungal chorismate mutase are activated when bound to tryptophan, and inhibited when bound to tyrosine

so in this case it seems like it fits the def 
"Binding to a small molecule and eliciting a change in the protein's activity in response to the intracellular level of that small molecule"
?

**Comment by Antonialock** [comment]
> Just plain "amino acid binding" doesn't tell us much? 
> I agree about creating the specific amino acid binding terms - also there are not so many.

Agreed in terms of understanding cell biology* :-) But I saw that one existed and not the other. 

* then again, I don't want to guess what poeple interested n more test-tubey biology might want to search on

**Comment by ValWood** [comment]
I think it is a sensor (activity)- allostery is the mechanism and we don't really capture mechanisms in GO.
I'm more familiar with TF's acting as sensors  of , for example, oxygen or iron. In these cases the  binding usually results in some confirmatory  change resulting in TF activation.

I might be wrong but this is how I have been using sensor.

**Comment by pgaudet** [comment]
Discussed this on the ontology call- 

@thomaspd says its OK to create 'sensor activity' for tryptophan and tyrosine. 
@vanaukenk says this is consistent with how they wanted to model unfolded protein-sensing activity
@deustp01 mentions we should also then create ATP-sensor activity for (gylcolytic enzymes)

Definitions would be: 
> Binding to tryptophan and eliciting a change in the protein's activity in response to the intracellular level of tryptophan.

Also - we should consider how this is related to tyrosine/tryptophan homeostasis -  sensing is often related to homeostasis - but is this always the case... ? 

Thanks, Pascale

**Comment by Antonialock** [comment]
ok I think that sounds good. In this case it is a "homeostasis" sensor
A chorismate mutase dimer has two amino acid binding sites: it can bind W, Y, WW, YY, YW, or WY

When binding W, WW, or  WY, chorismate mutase is activated and drives prephenate production (which is upstream of tyrosine and phenylalanine biosynthesis)

When binding Y or YY, chorismate mutase is inactivated and instead chorismate is channeled to tryptophan biosynthesis

see fig B here for activity assays:
![image](https://user-images.githubusercontent.com/12727506/97903927-af83f680-1d37-11eb-91f8-2d7424b32b33.png)
https://pubs.acs.org/doi/10.1021/acs.biochem.9b00721

and an overview of the pathway (from my other ticket on this protein, I think this is from a plant protein, but same overall thing)

![image](https://user-images.githubusercontent.com/12727506/97904327-3b961e00-1d38-11eb-9d7e-e2dba1f1924c.png)
https://www.annualreviews.org/doi/10.1146/annurev-arplant-042811-105439

**Comment by ValWood** [comment]
I'm always wary of inferring homeostais. For example I used to think that all zinc transport would be zinc homeostasis. But when we were curating this paper
https://www.pombase.org/reference/PMID:29529046
that author pointed out that some of the transport and homeostatic, and some was not

**Comment by ValWood** [comment]
OK, ignore - I defer to @Antonialock

**Comment by Antonialock** [comment]
I prefer 'sensor'.

homeostasis seems to be used a lot for pathways that, when you mess them up, results in unregulated X nutrient

(another example is the Fe/S biosynthesis genes, when you mutate those you get an "iron overload phenotype" where the cell thinks it is iron starved even though it has too much iron in mitochondria. I think those genes at least used to be annotated to "iron homeostasis" but they are not homeostatic genes

**Comment by pgaudet** [comment]
Thanks for the comments and details on the pathways. 

What I mean is that 
* aro7 enables chorismate mutase activity which is part_of (of upstream of) tyrosine and phenylalanine biosynthesis
* aro7 enables tryptophan sensor activity which is part_of tryptophan, tyrosine and phenylalanine homeostasis
* aro7 enables tyrosine sensor activity which is part_of tryptophan, tyrosine and phenylalanine homeostasis

This would not be in the ontology because I am not sure all trp/tyr sensing is always homeostasis. 

However the zinc paper you showed https://github.com/geneontology/go-ontology/issues/20181#issuecomment-720644526 looks like homeostasis to me (import when zinc is low, export when there is free zinc, which is probably toxic). 

Thanks, Pascale

**Comment by ValWood** [comment]
> This would not be in the ontology because I am not sure all trp/tyr sensing is always homeostasis.

I agree.

**Comment by krchristie** [comment]
Currently we have this term:
- tyrosine binding (GO:0072545) - Interacting selectively and non-covalently _with2_-amino-3-(4-hydroxyphenyl)propanoic acid.

We have no term for "**tryptophan binding**" and no "**small molecule sensor activity**" terms for either of these amino acids (or any other amino acids for that matter).

Looking at existing sensor terms, using "**cadmium ion sensor activity**" as an example, the majority have equivalence axioms like this: 
- `'small molecule sensor activity' and ('has input' some 'cadmium cation')`

and have SubClass Of relationships like this:
- `cadmium ion binding`
- `small molecule sensor activity`

So, to make the sensor terms for tryptophan and tyrosine, I also need to make the "**tryptophan binding**" term.
