### ISSUE TITLE
Add a check to ensure CHEBI pH 7.3 terms are used whenever available

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#20197]
This will need to be put in place after merging #20093.

**Comment by pgaudet** [comment]
Is this a big task ? It would be nice to have this check implemented. 

Thanks, Pascale

**Comment by balhoff** [comment]
It's done now in #20800. The PR is failing because there are a few existing violations:

```
ERROR: CHEBI IDs should be mapped to pH 7.3:
796
17549
797
27897
798
45394
799
71580
```

**Comment by balhoff** [comment]
I updated those: https://github.com/geneontology/go-ontology/pull/20800/files#diff-4f6e0296bc084cd5c8a2ab6cda4ecd3e62bdce48fa7a67b74d22ff5737c7e635

**Comment by pgaudet** [comment]
Thanks !
