### ISSUE TITLE
Merge GO:0036281 coflocculation ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20192]
Hi @srengel 
There are 3 annotations to  GO:0036281 coflocculation based on PMID:26317200. On the multiorganism call today we wondered whether this is a real process, or whether this occurs under artificial conditions. Is this term really an evolved process ? We only find 19 papers in PubMed, mostly talking about the industrial process rather than the biological process. 

Thanks, Pascale 
@ValWood @mgiglio99 @dsiegele @cmungall

**Comment by pgaudet** [comment]
maybe 'GO:0007155 cell adhesion' better captures what is happening ?

**Comment by srengel** [comment]
Hi Pascale, i agree that this isn't really a special thing.  flocculation occurs in natural conditions, and it's common (for ex. in wine fermentations) to have different species in there together (so, 'co-flocculation' according to term def), but i don't consider it to be a different biological process. i have removed the 3 annotations just now in P2GO.

**Comment by pgaudet** [comment]
OK thanks !

**Comment by pgaudet** [comment]
I'll merge into flocculation, since you mention there is not really a distinction.

**Comment by pgaudet** [comment]
Also will merge GO:1901134 negative regulation of coflocculation into GO:0060257 negative regulation of flocculation
