### ISSUE TITLE
looping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20204]
GO:0090579    dsDNA loop formation
Definition (GO:0090579 GONUTS page)
The formation and maintenance of DNA loops that juxtapose separated regions on the same dsDNA molecule. PMID:15950878

Is used for 2  different processes:

I) chromatin loop formation
Cohesin capture and extrusion  of DNA in a processive manner. 
ii) Local loop formation as  part of transcription (i.e. promoter enhancer looping)
which is represented by the child term "GO:0090202    gene looping"
and grand kids
GO:0071733    transcriptional activation by promoter-enhancer looping | is_a
GO:0090203    transcriptional activation by promoter-terminator looping

I think we need a specific term for "chromatin loop formation" as these are currently not separable from promoter -enhancer loops

**Comment by ValWood** [comment]
@colinlog  is it correct that looping can refer to different processes?

**Comment by pgaudet** [comment]
Obsolete in BP: 
- 'dsDNA loop formation' 
- 'gene looping' 
- 'transcriptional activation by promoter-enhancer looping' -> obsolete and replace by NTR promoter-enhancer loop anchoring activity : Bridging together promoter DNA and enhancer DNA sequences on the chromatin, holding two loop anchors together, maintaining a chromatin loop. 
has_part loop anchor DNA binding
- 'transcriptional activation by promoter-terminator looping'-> obsolete and replace by NTR promoter-terminator loop anchoring activity 
Bridging together promoter DNA and terminator DNA sequences on the chromatin, holding two loop anchors together, maintaining a chromatin loop. 
has_part loop anchor DNA binding

NTR parent class: chromatin loop anchoring activity
part_of some chromatin organization 

NTR BP: chromatin looping (Exact Syn: chromatin loop assembly)
A chromatin organization process that starts with the loading of an extrusion motor (SMC family complex) onto the chromatin, followed by chromatin extrusion that stops at loop anchoring sites on the chromosome. 

ADD: chromatin extrusion motor activity
part of 'chromatin loop assembly'

GO:0140564 DNA-DNA tethering activity
- [x] move up under 'molecular adaptor activity'

**Comment by pgaudet** [comment]
New terms: 

+[Term]
+id: GO:0140585
+name: promoter-enhancer loop anchoring activity
+namespace: molecular_function
+def: "Bridging together promoter DNA and enhancer DNA sequences on the chromatin, holding two loop anchors together, maintaining a chromatin loop." [PMID:32213323]
+synonym: "enhancer-promoter loop anchoring activity" EXACT []
+is_a: GO:0140587 ! chromatin loop anchoring activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20204 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-04T14:50:04Z
+
+[Term]
+id: GO:0140586
+name: promoter-terminator loop anchoring activity
+namespace: molecular_function
+def: "Bridging together promoter DNA and terminator DNA sequences on the chromatin, holding two loop anchors together, maintaining a chromatin loop." [PMID:19933151]
+synonym: "terminator-promoter loop anchoring activity" EXACT []
+is_a: GO:0140587 ! chromatin loop anchoring activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20204 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-04T14:51:44Z
+
+[Term]
+id: GO:0140587
+name: chromatin loop anchoring activity
+namespace: molecular_function
+def: "Bridging together two DNA loop anchors together, maintaining a chromatin loop." [PMID:32213323]
+is_a: GO:0106260 ! DNA-DNA tethering activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20204 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-04T14:53:13Z
+
+[Term]
+id: GO:0140588
+name: chromatin looping
+def: "A chromatin organization process that starts with the loading of an extrusion motor (by an SMC family complex) onto the chromatin, followed by chromatin extrusion that stops at loop anchoring sites on the chromosome." []
+synonym: "chromatin folding" RELATED []
+synonym: "chromatin loop assembly" EXACT []
+is_a: GO:0006325 ! chromatin organization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20204 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-04T14:55:20Z


Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

- GO:0090579 dsDNA loop formation
-  GO:0090202 gene looping
- GO:0071733 transcriptional activation by promoter-enhancer looping
- GO:0090203 transcriptional activation by promoter-terminator looping 

The reason for obsoletion is that the way those terms are defined, they are better represented by molecular functions. We have created 3 functions to replace those terms: 

GO:0140587  chromatin loop anchoring activity
GO:0140585  promoter-enhancer loop anchoring activity
GO:0140586  promoter-terminator loop anchoring activity

and a more general function: GO:0140588 chromatin looping

The concepts of transcription regulation should be captured with 'GO:0006355 regulation of transcription, DNA-templated' or a child term. 

There are 25 EXP annotations to those 4 terms. @ValWood and @colinlog have made suggestions for reannotation, see https://github.com/geneontology/go-annotation/issues/3610 (it may be a couple of days until the new terms are available). 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 18th, leaving some time to make the corrections. Unless objections are received by February 18th, 2021, we will assume that you agree to this change.
 
You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/20204
 
 
Thanks, Pascale
