### ISSUE TITLE
create new GO term 

### ISSUE THREAD

**Issue by marinakolesnichenko** [geneontology/go-ontology#20200]
suggestion for a new GO term:

New term label: SASP (Senescence associated secretory phenotype)
Definition: transcriptome of senescent cells 
position in the GO hierchy: a part of GO:0090398 
Where the term has been used: Table 1 in doi: 10.1146/annurev-pathol-121808-102144
Synonyms: SIR (senescence inflammatory response)
Crossreference: no
See excel sheet provided for list gene names for the SASP list. 
[SASP.xlsx](https://github.com/geneontology/go-ontology/files/5438890/SASP.xlsx)

**Comment by pgaudet** [comment]
Dear @marinakolesnichenko 
Unfortunately this new proposed term represents a diseased state, and it not in the scope of GO. Maybe you can check with HPO (Human Phenotype Ontology?) 

Thanks, Pascale

**Comment by marinakolesnichenko** [comment]
Dear Pascale,

senescence is not a diseased state and it is a biological process that is essential by wound healing!

Also it is not just restricted to humans.

best,

M

________________________________

**Comment by pgaudet** [comment]
OK, I understood you wanted to annotate specifically the 'secretory phenotype. Otherwise, we already have the term'     GO:0090398 cellular senescence' that may correspond to what you need ? 

Thanks, Pascale

**Comment by marinakolesnichenko** [comment]
exactly !!
senescence is the broader category which includes SASP and genes for cell cycle.
SASP belongs to senescence but can also occur independently so it needs a separate term.
________________________________

**Comment by pgaudet** [comment]
Can you propose a definition for this term ?

**Comment by marinakolesnichenko** [comment]
senescence associated secretory phenotype (SASP) - inflammatory cytokines and chemokines upregulated in cellular senescence. 
________________________________

**Comment by ValWood** [comment]
But GO does not cover 'phenotypes' Which process you are describing?
The parent term you are suggesting

GO:0090398
A cell aging process stimulated in response to cellular stress, whereby normal cells lose the ability to divide through irreversible cell cycle arrest.

this would be the starting point for the definition of a new term.
Therefore this term would be defined
"a cellular senescence process + differentia"

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Senescence-associated_secretory_phenotype

Senescence-associated secretory phenotype (SASP) is a phenotype associated with senescent cells wherein those cells secrete high levels of inflammatory cytokines, immune modulators, growth factors, and proteases

so this is clearly a phenotype. It does sound out of scope for GO unless you can describe the actual process.

Are you trying to describe the cellular  location of the gene products or the process they are involved in?

**Comment by marinakolesnichenko** [comment]
no, senescence is general term for oncogene induced senescence, replicative senescence etc.  That would be the parent term.

SASP is part of senescence usually BUT it does not have to be.  The relationship of SASP to senescence is similar to greying hair to aging. Usually a normal state and a part of it, but does not have to be and there are some exceptions.

It is important to define SASP as a separate GO term precisely because in some instances it can exist independently.

________________________________

**Comment by marinakolesnichenko** [comment]
phenotype is not accurate here, because what it actually refers to is a gene set upregulated in senescence.

This gene set is available in the paper I cited earlier by Coppe 2010.

________________________________

**Comment by ValWood** [comment]
You  seem to want to descibe a set of upregulated genes?
OK that seems to be outside of the scope of GO too. 
This is really "expression level"

GO  describes  i) molecular functions, ii) biological processes and iii) cellular components

**Comment by marinakolesnichenko** [comment]
correct. There are GO terms for inflammation and inflammatory response. This is similar.
________________________________

**Comment by addiehl** [comment]
Although there are phenotypic correlates with an ongoing inflammatory response, the GO term 'inflammatory response' is a process used for annotating gene products that contribute to or regulate an inflammatory response.  GO annotation of gene products upregulated during an inflammatory response is only appropriate if those gene products participate in the process of the inflammatory response, perhaps in an autocrine fashion, for instance.

It is not appropriate to create a GO term like SASP for genes that simply are expressed during a phenotypic condition.  If you can identify an underlying cellular process, like a signaling pathway, that drives the expression of a particular set of genes associated with secretion during senescence, then it would be appropriate to use that term to annotate the gene products involved in that process, but not the gene products that are expressed as a result of that process.

**Comment by pgaudet** [comment]
Thanks @addiehl 

@marinakolesnichenko We cannot create this term, I hope you can either find a paper where the process is defined at the molecular level, or another ontology to capture this. 

Thanks, Pascale

**Comment by marinakolesnichenko** [comment]
thank you! so the term SASP : gene expression driven by p65 (Nfkappa B) signaling and results in transcription of inflammatory factors.
Is a pre-print ok?
M
________________________________
