### ISSUE TITLE
Change text for cAMP-dependent protein kinase activity

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#20205]
id: GO:0004691
name: cAMP-dependent protein kinase activity
def: "**Catalysis of the reaction: ATP + a protein = ADP + a phosphoprotein**. This reaction requires the presence of cAMP." [EC:2.7.11.11]

The cAMP dependency should not be in the definition gloss. The part before the period must be unique

**Comment by hdrabkin** [comment]
Yes, I'd move it to a comment

**Comment by deustp01** [comment]
Is that right? It looks like the cAMP dependency is what makes this reaction different from, e.g., the reactions catalyzed by growth factor receptors that do not have any cAMP dependency, so does this mean that the cAMP should be promoted to a place before the period? "cAMP-dependent catalysis of the reaction ..." or something like that?

**Comment by hdrabkin** [comment]
I guess the reaction though 'Catalysis of the reaction: ATP + a protein = ADP + a phosphoprotein. could be applied to any protein kinase ; but 'cAMP-dependent catalysis of the reaction' would do also.

**Comment by hdrabkin** [comment]
cAMP-dependent catalysis of the reaction:  ATP + a protein = ADP + a phosphoprotein.

**Comment by pgaudet** [comment]
I thought this was a placeholder for all children of protein kinase activity. For example     GO:0010857   calcium-dependent protein kinase activity has the same issue: Catalysis of the reaction: a protein + ATP = a phosphoprotein + ADP. This reaction requires the presence of calcium.


Thanks, Pascale

**Comment by ValWood** [comment]
Isn't there a precedent for including  a non metabolised component on both sides of the reaction? I'm sure I have seen that somewhere....butI can't think where of the top of my head....

**Comment by hdrabkin** [comment]
But that's NOT what the activity is labeled. with; NOT a place holder for all protein kinases; in fact, I guess it's a class of gene product (a set of protein kinases that require cAMP to function.

**Comment by pgaudet** [comment]
What I meant is that this also affects other terms. How do you want to proceed ? Do you want to create new tickets ?

**Comment by hdrabkin** [comment]
What other terms?

**Comment by pgaudet** [comment]
See my comment above: 
https://github.com/geneontology/go-ontology/issues/20205#issuecomment-717010347

**Comment by hdrabkin** [comment]
oh I see.
You mean to fix
Catalysis of the reaction: a protein + ATP = a phosphoprotein + ADP. This reaction requires the presence of calcium.

In a similar manner?  ->>
Calcium-dependent catalysis of the reaction: ATP + a protein = ADP + a phosphoprotein.

If so, let's get a list together and put it in this ticket?

**Comment by pgaudet** [comment]
Here's the list: 

'3-phosphoinositide-dependent protein kinase activity'
'DNA-dependent protein kinase activity'
'GTP-dependent protein kinase activity'
'cAMP-dependent protein kinase activity'
'cGMP-dependent protein kinase activity'
'Rho-dependent protein serine/threonine kinase activity'

'calmodulin-dependent protein kinase activity'
'cyclic nucleotide-dependent protein kinase activity'
'cyclin-dependent protein kinase activating kinase activity'
'cyclin-dependent protein kinase activity'
'cyclin-dependent protein serine/threonine kinase activity'

'calcium-dependent protein kinase C activity'
'calcium-dependent protein kinase activity'
'calcium-dependent protein serine/threonine kinase activity'
'calcium-independent protein kinase C activity' -> would be nice to state what it depends on... On the other hand, perhaps it can just be merged into Serine/threonine kinase activity

Thanks, Pascale

**Comment by hdrabkin** [comment]
well, we can at least know it's now calcium 8-)

**Comment by hdrabkin** [comment]
'3-phosphoinositide-dependent protein kinase activity' -done
'DNA-dependent protein kinase activity' done
'GTP-dependent protein kinase activity' done
'cAMP-dependent protein kinase activity' done as above
'cGMP-dependent protein kinase activity' done
'Rho-dependent protein serine/threonine kinase activity' done

'calmodulin-dependent protein kinase activity' done
'cyclic nucleotide-dependent protein kinase activity' done 
'cyclin-dependent protein kinase activating kinase activity'-- not sure about this one yet
'cyclin-dependent protein kinase activity' done 
'cyclin-dependent protein serine/threonine kinase activity' done 
calcium-dependent protein kinase C activity' done 
'calcium-dependent protein kinase activity' done
'calcium-dependent protein serine/threonine kinase activity'

Doing merge later as well as deciding wording on cyclin-dependent protein kinase activating kinase activity

**Comment by pgaudet** [comment]
There is a separate ticket for cyclin-dependent protein kinase activating kinase activity
