### ISSUE TITLE
taxon restriction, never in yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20218]
GO:0030977      taurine binding 
GO:0015734      taurine transport 
GO:0019530      taurine metabolic process 
GO:1990205      taurine dioxygenase complex 
GO:0042412      taurine biosynthetic process 
GO:0050323      taurine dehydrogenase activity 
GO:0000908      taurine dioxygenase activity 
GO:0019529      taurine catabolic process 
GO:0031299      taurine-pyruvate aminotransferase activity 
GO:0005368      taurine transmembrane transporter activity 
GO:0015411      ATPase-coupled taurine transporter activity 
GO:0050322      taurine-2-oxoglutarate transaminase activity 
GO:0062089      regulation of taurine biosynthetic process 
GO:0005369      taurine:sodium symporter activity 
GO:0062090      positive regulation of taurine biosynthetic process 
GO:0019452      L-cysteine catabolic process to taurine 
GO:0050325      tauropine dehydrogenase activity

**Comment by ValWood** [comment]
from
https://github.com/geneontology/go-annotation/issues/3409

**Comment by pgaudet** [comment]
Maybe then 'only in Metazoa'?

**Comment by ValWood** [comment]
Probably. I didn't know enough to make that call but it seems to be.

**Comment by pgaudet** [comment]
Fixed https://github.com/geneontology/go-ontology/blob/master/src/taxon_constraints/only_in_taxon.tsv

**Comment by pgaudet** [comment]
Actually there is a mistake here - Elisabeth Coudert from SwissProt emailed: 

> Taurine is a metabolite that can be found in mammals but it seems that taurine dioxygenase activity has been so far characterized only in bacteria.

Hope this helps,
Elisabeth

**Comment by pgaudet** [comment]
Adjusted taxon constraints 
GO:0000908	taurine dioxygenase activity -> only in bacteria

**Comment by pgaudet** [comment]
Removing taxon restrictions on taurine transport, see PMID:10781534

**Comment by pgaudet** [comment]
Added 'never in yeast' for 
GO:0005368	taurine transmembrane transporter activity	NCBITaxon:33208	Metazoa
GO:0015411	ATPase-coupled taurine transporter activity	NCBITaxon:33208	Metazoa
