### ISSUE TITLE
merge core translocon into translocon

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20211]
sss1 | ↑part_of GO:0071261 | Ssh1 translocon complex | IBA with PTN000267681 , S000002493 |  

please can this merge into translocon (No need to distinguish core from entire functional complex?)

**Comment by pgaudet** [comment]
GO:0071256 translocon complex has 2 children: 
*  GO:0005784 Sec61 translocon complex - 332 annotations
* GO:0071261 Ssh1 translocon complex  - 200 annotations


The overlap seems small - I dont think we can merge ? 

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/4782928/97344488-1b261980-1889-11eb-9259-0228a7b7bd70.png">


Thanks, Pascale

**Comment by ValWood** [comment]
OK yes there are 2 translocons apparently. 
structurally similar but functionally different.

**Comment by pgaudet** [comment]
Close with no action then ?

**Comment by ValWood** [comment]
yep. I will reannotate these !
