### ISSUE TITLE
 5'-3' exodeoxyribonuclease activity involved in UV-damage excision repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20213]
please obsolete or merge
GO:1904162 | 5'-3' exodeoxyribonuclease activity involved in UV-damage excision repair

**Comment by pgaudet** [comment]
Single EXP annotation by PomBase. I will obsolete. Each part of the term is covered by other annotations. 

Thanks, Pascale

**Comment by ValWood** [comment]
I removed that annotation earlier today.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:1904162 | 5'-3' exodeoxyribonuclease activity involved in UV-damage excision repair. The reason for obsoletion is that this term represents a biological process within a molecular function. There are no annotations, no mappings to this term. This term is not present in any subsets. 

Comments may be added to the ticket https://github.com/geneontology/go-ontology/issues/20213

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 2nd, 2020. Unless objections are received by November 2nd, 2020, we will assume that you agree to this change.

Thanks, Pascale
