### ISSUE TITLE
GO:0003922 | GMP synthase (glutamine-hydrolyzing) activity missing superclass

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20214]
does not have ancestor
 | GMP synthase  activity

**Comment by hdrabkin** [comment]
And I see 'GMP synthase activity' GO:0003921, as some part :GO:0003922 | GMP synthase (glutamine-hydrolyzing) activity

I would think it's the other way around; 3922 is  type of 3921 that uses glutamine to add the amino group to XMP instead of NH4+

**Comment by hdrabkin** [comment]
In fact, since they are both different reactions I would say no parent/child relation (after I remove the part_of)

**Comment by hdrabkin** [comment]
Oh wait; for EC:6.3.5.2 GO:0003922 | GMP synthase (glutamine-hydrolyzing
'the enzyme can catalyze the second reaction alone in the presence of ammonia. '
Nutz.

**Comment by ValWood** [comment]
@hdrabkin  can this close. Was my suggestion wrong, I'm not sure?

**Comment by ValWood** [comment]
Looking at the reactions, my suggestion was wrong
