### ISSUE TITLE
sulfite reductase relationships

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20220]
GO:0016002    sulfite reductase activity
Molecular Function

Definition
Catalysis of the reaction: hydrogen sulfide + acceptor + 3 H2O = sulfite + reduced acceptor.

is not an ancestor of
GO:0004783   sulfite reductase (NADPH) activity
Definition 
Catalysis of the reaction: hydrogen sulfide + 3 NADP+ + 3 H2O = sulfite + 3 NADPH + 3 H+.

<img width="527" alt="Screenshot 2020-10-27 at 16 52 04" src="https://user-images.githubusercontent.com/7359272/97334524-c1b3ef80-1874-11eb-9889-c42105b07395.png">

**Comment by hdrabkin** [comment]
done
