### ISSUE TITLE
Obsolete GO:1901916 protein kinase activity involved in regulation of protein localization to cell division site involved in cytokinesis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20226]
Dear all, 

The proposal has been made to obsolete 'GO:1901916 protein kinase activity involved in regulation of protein localization to cell division site involved in cytokinesis'. The reason for obsoletion is that this term represents both a function and a process. 

There are 2 EXP annotations to this term, by SGD @srengel and GeneDB @Achchuthan 
This term is not present in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/20226

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 2nd, 2020. Unless objections are received by November 2nd, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by srengel** [comment]
fixed the SGD one just now.
