### ISSUE TITLE
NTR:tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#20221]
For val for PTN000317053 #3399 
term: tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity
def: Catalysis of the reaction: carboxymethyluridine34 in tRNA + S-adenosyl-L-methionine = 5-(2-methoxy-2-oxoethyl)uridine34 in tRNA + S-adenosyl-L-homocysteine
Ref: RHEA:43208; PMID: 20123966
Additional xref
EC:2.1.1.229

parent

    EC:2.1.1 Methyltransferases. (because EC is 2.1.1.220)
    'catalytic activity, acting on a tRNA'

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106335
+name: tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity

**Comment by ValWood** [comment]
closing, OK @hdrabkin
