### ISSUE TITLE
GO:0046627 | negative regulation of insulin receptor signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20243]
please add never in yeast
GO:0046627 | negative regulation of insulin receptor signaling pathway

**Comment by pgaudet** [comment]
We have 

GO:0030073 | insulin secretion | only on taxon NCBITaxon:2759 | Eukaryota

1. This seems wrong 
2. Shouldn't all the insulin terms have the same constraints ?

**Comment by ValWood** [comment]
I think they should.

**Comment by pgaudet** [comment]
Any suggestion ? Eukaryotes seem too broad ? 

@hattrill @sabrinatoro any suggestions ?

**Comment by pgaudet** [comment]
@ValWood Why not 'regulation' ? you specifically want 'negative regulation' How about insulin signaling ?

**Comment by ValWood** [comment]
I specifically want nothing ;)

we  only have this term on one gene product https://www.pombase.org/gene/SPAC22F3.13 hamartin/Trsc1

It is upstream of  TOR signalling- we already have

negative regulation of TOR signaling, and G1/S

You could make it "negative regulation of signalling" but we wouldn't really want such  general term (should probably not be allowed for direct annotation)

**Comment by ValWood** [comment]
It's. a bot of an awkward one. I don't really know what the components of this pathway are, all I know is yeast don't have insulin, and they don't use this pathway name. It might be another name for a generic pathway though?

This is the problem with the signalling pathway names, there is no control so they end up being whatever people want them to be....

**Comment by hattrill** [comment]
Seems to be lots of points here:
1. Classifying the the pathway based on the ligand is not good, as there is insulin, insulin like peptides, etc. Best grouped on receptor as that is what interfaces with the downstream components.
2. Perhaps just have "only in Eumetazoa  Taxonomy ID: 6072. 
3. The TOR is a module that sits within the insulin pathway but it is a hub for many other signaling steps. 
4. Is this a PAINT issue? Signaling pathway components are difficult in that not all ligands of a certain class can stimulate a particular pathway receptor, and some components have multiple paralogs (esp in mammals) and it can be dangerous to propagate.

**Comment by ValWood** [comment]
I agree-  this is a big problem.
I believe there might be efforts underway to standardize signalling pathway naming- it's a free for all.

I also agree that classification by ligand is problematic. Especially for GO  because a whole slew of converging and branching pathways  may be given a generic label like "insulin-mediated signalling", this becomes incompatible with 
ancestry because the partonomies will never  be universal.

This is one place where "response to" terms might be useful

TOR signalling occurs_during "response to insulin/glucose"  (this is pretty much what we do at PomBase where the same MAP kinase pathway can be activated at diffferent input branches by oxidative, osmotic, heat and cytoskeletal stresses)

**Comment by hattrill** [comment]
It's probably a good time to have a little review of the nomenclature. There are also a few issues that I could fold into this. 

It would also be good to discuss how the sub-pathways are represented - they are on my list to look at and need a good tidy. 

I would probably use a part of relationship, TOR signalling part of insulin-receptor signaling pathway or response to x.

**Comment by ValWood** [comment]
I think it is being done my the signalling databases SIGNOR or the causal interaction consortium. It has been mentioned anyway...

**Comment by pgaudet** [comment]
@hattrill Should I assign this to you ?

**Comment by hattrill** [comment]
Ok - will try to follow up on this to make sure that we are consistent with other signaling DBs.

**Comment by ValWood** [comment]
This will take years ;)
You should speak to Martin Kuiper and see what they are doing as part of the various consortia NNTU are involved in.

**Comment by ValWood** [comment]
(I would tag Martin but I can't find his GitHubID)

**Comment by hattrill** [comment]
@ValWood I have aged just thinking abnout it ;-D

**Comment by ValWood** [comment]
This ticket seems to have wandered in scope.
Caould we add the taxon constraint and  open a new ticket describing the signalling 
nomenclature/orthogonal classification issues?

**Comment by pgaudet** [comment]
Added those taxon contraints

GO:0005009	insulin-activated receptor activity	NCBITaxon:6072	Eumetazoa
GO:0005899	insulin receptor complex	NCBITaxon:6072	Eumetazoa
GO:0008286	insulin receptor signaling pathway	NCBITaxon:6072	Eumetazoa
GO:0046626	regulation of insulin receptor signaling pathway	NCBITaxon:6072	Eumetazoa

& fixed insulin secretion to NCBITaxon:6072	Eumetazoa

@hattrill or @ValWood if you want other actions, please open a new tickets. 

Thanks, Pascale
