### ISSUE TITLE
Terms with RHEA in def but missing Rhea xref

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20248]
RHEA:13637
RHEA:13641
RHEA:19817
RHEA:19821
RHEA:24628
RHEA:24632
RHEA:26297
RHEA:26414
RHEA:27834
RHEA:27986
RHEA:30291
RHEA:30815
RHEA:32995
RHEA:33191
RHEA:33447
RHEA:36440
RHEA:38568
RHEA:38584
RHEA:40027
RHEA:43112
RHEA:43120
RHEA:43532
RHEA:50364
RHEA:51468
RHEA:56832
RHEA:58808

@balhoff Can a check also be added for that ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
I already have a report about this that I'm working on .

**Comment by hdrabkin** [comment]
If this can be done automatically that  would be nice

**Comment by hdrabkin** [comment]
We also have from the autoload RHEA in xref that didn't also get put into def ref
