### ISSUE TITLE
RHEA xrefs linked to more than one term

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20247]
Hello ! 

I thought it was forbidden to have a Rhea associated with more than 1 GO term. I found those examples: 

xref: RHEA:11096
xref: RHEA:13349
xref: RHEA:13957
xref: RHEA:15793
xref: RHEA:17957
xref: RHEA:19389
xref: RHEA:20397
xref: RHEA:22640
xref: RHEA:23656
xref: RHEA:26466
xref: RHEA:30523
xref: RHEA:33983

@hdrabkin can you fix ? 
@balhoff should we add a check ? 

Thanks, Pascale

**Comment by balhoff** [comment]
> should we add a check ?

I can do this. Should be one-to-one (both directions) right? @hdrabkin I can wait until it's cleaned up and then implement the check.

**Comment by hdrabkin** [comment]
Thought I got them all. These might be more NAD(P) stuff.

**Comment by pgaudet** [comment]
> Should be one-to-one (both directions) right? 

I think so

**Comment by hdrabkin** [comment]
RHEA:11096 fixed
RHEA:13349 term merge
RHEA:13957 term merge (except stoich. is different (4 vs 5 caron)
RHEA:15793 fixed
RHEA:17957  The two reactions are different and can't even have the same EC but do.
    3-hydroxypropenoate is not the same as 3-oxopropanoate.  The RHEA belongs with GO:0050079; removed from GO:0051909.  These two terms have different metacyc ids but the EC is same; EC says "The mechanism appears to involve hydration of the acetylene to 3-hydroxypropenoate, which will spontaneously tautomerize to 3-oxopropanoate." 
   So I suspect these terms should be merged (keeping the one with the RHEA).

 RHEA:19389  suggest term merge
RHEA:20397 removed rhea from one reaction. ; new rhea for GO:0102028 requested to specifiy new substrate.
RHEA:22640 removed from one reaction; new rhea for GO:0102283 with more specific substrate requested
RHEA:23656 removed from less specific reaction; suggest merge GO:0018842 into GO:00047472
RHEA:26466 best fit to GO:0102094 keep; remove from GO:0043770; possible term merge
 RHEA:30523 maybe  term merge:  
 RHEA:33983 term merge 

Made simple fixes first; term merges to come after checks.

**Comment by hdrabkin** [comment]
These are now resolved  See 
#20722 and #20720, both closed now.
