### ISSUE TITLE
obsolete: activation of MAPK activity involved in x 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20242]
GO:0000187 | activation of MAPK activity

do we need this term? The only think that is annotated to it is

MF MAP kinase kinase activity

(its a MF in the BP ontology)

**Comment by pgaudet** [comment]
Here's my proposal: 

- [ ] obsolete 
GO:0000187 | activation of MAPK activity
and  GO:0007257 activation of JUN kinase activity
and suggest 'consider' protein kinase activator activity 

- [ ] obsolete  GO:0071883 activation of MAPK activity by adrenergic receptor signaling pathway
No annotations; corresponds to a GPCR pathway

What do you want to do with 
* GO:0000199 activation of MAPK activity involved in cell wall organization or biogenesis
* GO:0071508 activation of MAPK activity involved in conjugation with cellular fusion 
? 

Thanks, Pascale

**Comment by ValWood** [comment]
Obsolete?
These are GO-cams

**Comment by pgaudet** [comment]
ok great

**Comment by pgaudet** [comment]
I'll start with those with few annotations 
* GO:0000199 activation of MAPK activity involved in cell wall organization or biogenesis
* GO:0071508 activation of MAPK activity involved in conjugation with cellular fusion

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

* GO:0000199 activation of MAPK activity involved in cell wall organization or biogenesis and
* GO:0071508 activation of MAPK activity involved in conjugation with cellular fusion

The reason for obsoletion that those are pre-composed terms that should be captured as a GO-CAM model. There are 3 EXP annotations to 'activation of MAPK activity involved in cell wall organization or biogenesis' by AspGD, and no annotations to 'activation of MAPK activity involved in conjugation with cellular fusion'. 

There are no mappings to those terms; those terms are not in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on April 23. Unless objections are received by April 23, 2021, we will assume that you agree to this change.
You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/20242

Thanks, Pascale
 
Thanks, Pascale

**Comment by pgaudet** [comment]
@marekskrzypek Can you please look at the 3 AspGD annotations?

**Comment by marekskrzypek** [comment]
AspGD is no longer maintained. I can certainly take a look at these items, but I can't convert them to a GO-CAM model, even if it sounds reasonable to me; all I can do is to delete them.

**Comment by pgaudet** [comment]
Those terms also have no annotations: 


GO:0000198 | activation of MAPKK activity involved in cell wall organization or biogenesis' | 0
GO:0071509 | activation of MAPKK activity involved in conjugation with cellular fusion' | 0
GO:0000197 | activation of MAPKKK activity involved in cell wall organization or biogenesis' | 0
GO:0071510 | activation of MAPKKK activity involved in conjugation with cellular fusion' | 0
GO:0000200 | inactivation of MAPK activity involved in cell wall organization or biogenesis' | 0
GO:0000200 | inactivation of MAPK activity involved in conjugation with cellular fusion' | 0
GO:0035423 | inactivation of MAPK activity involved in innate immune response' | 0

**Comment by ValWood** [comment]
Hi @marekskrzypek  you would not lose any information if you use the suggested replacements.

**Comment by ValWood** [comment]
Hi Marek, you can just use
 GO:1903139 positive regulation of cell wall integrity MAPK cascade, which means essentially the same thing.

**Comment by marekskrzypek** [comment]
Oh, yes, makes sense. Thanks, Val
