### ISSUE TITLE
oxidation-reduction process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20250]
can we get rid of this meaningless term?

we are picking up quite a few  PANTHER mappings to this term (I block all others). This is a bit of a useless grouping term- all that it  means is that a gene product is an oxidoreductase. So now it looks like. some of our 'oxido eductases' of unknown physiological role are a known process,  although they aren't. And even for the known ones, this term doesn't add anything -   because it is really a MF in BP  it's an orthogonal  axis of classification:

<img width="1007" alt="Screenshot 2020-10-30 at 19 11 34" src="https://user-images.githubusercontent.com/7359272/97747876-7f90e500-1ae4-11eb-8360-6201e20fabee.png">

it really isn't useful since every single one of the  35 million oxidoreductase in GOA is annotated to it.

**Comment by ValWood** [comment]
<img width="215" alt="Screenshot 2020-10-30 at 19 20 10" src="https://user-images.githubusercontent.com/7359272/97748167-f0d09800-1ae4-11eb-919d-396cb02eb6b2.png">

I don't even think this was probably the original intent of the term...

tagging @cmungall  and @pgaudet  because the only ticket it is mentioned in is
https://github.com/geneontology/go-ontology/issues/12231

This one has been on my hit-list for a few years, normally we just filter these ...

**Comment by ValWood** [comment]
sensibly "ergosterol biosynthetic process" isn't  an oxidation-reduction process, which highlights that it is a bit of a bonkers term and only refers to the MF

<img width="1007" alt="Screenshot 2020-10-30 at 19 11 34" src="https://user-images.githubusercontent.com/7359272/97748520-7e13ec80-1ae5-11eb-82f4-af4b3c9acb61.png">

**Comment by cmungall** [comment]
Happy for it to be obsoleted

I assume all the direct experimental annotations are actually propagated from MF (recall we used to use IC here but some time ago switched to retaining the original ref + evidence, which makes provenance harder; we don't need to revisit this discuss here however)

**Comment by ValWood** [comment]
There are some direct annotation. I tried to look  but   would need to 

(direct class) oxidation-reduction process GO:0055114 evidence_subset_closure_label: experimental evidence 

and substract 
GO:0016491   oxidoreductase activity
and see what is left.


The term 
oxidation-reduction process GO:0055114 has children  which do represent meaningful processes.
like
GO:0022900    electron transport chain

but now I see thre are lots of children 
"substrate(x) oxidation" so it's not so simple to sort out.

Most if these annotation  are not required. I only looked at one "formate oxidation", has 10 annotations for e.g.
https://www.uniprot.org/uniprot/P32176
The process here is "respiration" (aerobic according to the UniProt description and anaerobic according to GO annotation).

**Comment by pgaudet** [comment]
This is relatively easy to do - most terms have other parents, except for 
- 'oxidative deethylation' -> this is probably a function ? 
- 'thioredoxin reduction' -> not sure where this should go; metabolic process? 

However that makes the parent node 'metabolic process' a bit more untidy (for a few terms, that was the only other parent). 

Specific questions: 
1. 'NAD metabolic process'
'NADP metabolic process'
'NADH metabolic process'
are children of 'metabolic process', while NADPH regeneration is a child of 'generation of precursor metabolites and energy'

Should they all be under that term ? 

2. Are demethylation, glycosylation, and methylation necessarily metabolic processes ? 

Thanks, Pascale

**Comment by ValWood** [comment]
'thioredoxin reduction' doesn't this one represent MF's too?

**Comment by deustp01** [comment]
> Specific questions:
> 
>     1. 'NAD metabolic process'
>        'NADP metabolic process'
>        'NADH metabolic process'
>        are children of 'metabolic process', while NADPH regeneration is a child of 'generation of precursor metabolites and energy'
> 
> 
> Should they all be under that term ?

The distinction, if I remember right, is between processes that mediate the synthesis of these entities from and the degradation of these entities to other molecules (metabolism / biosynthesis / catabolism) and processes that mediate the interconversion of the reduced and oxidized forms of each. The interconversions, I think we agreed, are like the generation of ADP from ATP and vice versa, and are distinct from biosynthetic / catabolic metabolism. @ukemi @hdrabkin

**Comment by hdrabkin** [comment]
Yes that was my understanding, so that not every rxn  using NAD(P)  gets tagged as NAD(P) metabolism.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

- GO:0071615 oxidative deethylation 19 EXP, AgBase
- GO:0042964 thioredoxin reduction: 2 EXP, TAIR; consider: GO:0004791 thioredoxin-disulfide reductase activity

The reason for obsoletion is that those terms represent molecular functions. There are no mappings; these terms are not present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 14th, 2020. Unless objections are received by December 14th, 2020, we will assume that you agree to this change. You can  comment on the ticket: https://github.com/geneontology/go-ontology/issues/20250


Thanks, Pascale

**Comment by pgaudet** [comment]
@tberardini FYI - you can remove the annotations. The MF are already annotated. 

Thanks, Pascale

**Comment by tberardini** [comment]
@pgaudet  You mean the annotations to 'thioredoxin reduction', right?

**Comment by pgaudet** [comment]
@tberardini yes that's what I mean, thanks for reading my mind, saves some typing ;)

**Comment by tberardini** [comment]
@pgaudet :) I was wondering if you meant the ones to 'oxidation-reduction process' but you haven't sent out an obsoletion notice for that yet.

**Comment by pgaudet** [comment]
oxidation-reduction process is used in the logical definition of 
*  GO:0006150     hypoxanthine oxidation: 3 EXP annotations to  xanthine dehydrogenase
LD is 'catabolic process' and ('has part' some 'oxidation-reduction process') and ('has primary input' some hypoxanthine)

 - [x] merge into parent GO:0009114 hypoxanthine catabolic process. 

* Similar for 
GO:0006151 xanthine oxidation - also has 3 EXP annotations to  xanthine dehydrogenase
 - [x] merge into parent 
GO:0009115 xanthine catabolic process 

* tyrosine biosynthetic process, by oxidation of phenylalanine 
also uses 'has part' some 'oxidation-reduction process' in the LD: 
'biosynthetic process' and ('has part' some 'obsolete oxidation-reduction process') and ('has input' some phenylalanine) and ('has primary output' some tyrosine)

 - [x] Removed LD and create a new ticket for the tyrosine biosynthetic process branch. 

Thanks, Pascale
