### ISSUE TITLE
cytokinesis terms site selection/ establishment of localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20256]
are

 GO:1903486 establishment of mitotic actomyosin contractile ring localization
Any establishment of actomyosin contractile ring localization that is involved in mitotic cell cycle.
and

GO:0007105   cytokinesis, site selection
Definition 
The process of marking the place where cytokinesis will occur.

the same thing?

**Comment by mah11** [comment]
No, GO:1903486 is narrower, because plants (e.g. PMID:30999231).

**Comment by ValWood** [comment]
but establishment occurs in yeast too (mid1 placement at the cortex).  I'm still struggling  to figure out how establishment or location and site-selection differ...


although I probably should have asked
GO:0032188    establishment of actomyosin contractile ring localization
and
GO:0007105 cytokinesis, site selection

**Comment by mah11** [comment]
> but establishment occurs in yeast too (mid1 placement at the cortex). 

I'm not sure how that's relevant to the fact that establishing contractile ring localization is narrower than selecting the site of cytokinesis.

> I'm still struggling to figure out how establishment or location and site-selection differ...

The difference is that in plants there's no actomyosin contractile ring. The phragmoplast and cell plate nevertheless form at a non-random site.

For organisms that do have an actomyosin contractile ring, it does indeed form at the site of cytokinesis, but that is not the only type of site selection that GO:0007105 has to cover.

**Comment by ValWood** [comment]
I still think something  is a bit odd:

<img width="509" alt="Screenshot 2020-11-02 at 18 29 23" src="https://user-images.githubusercontent.com/7359272/97905129-646ae300-1d39-11eb-9257-4488c53738b0.png">

**Comment by mah11** [comment]
But it looks basically *correct*, apart from a missing link - GO:1903486 should be is_a or part_of GO:1902408. Part_of would parallel GO:0032188 part_of GO:0007105, but perhaps both should be is_a.

Otherwise, it's only as odd as the biology it has to represent.

**Comment by ValWood** [comment]
I think I am confused by the different labels then.

If it is correct, it probably should be is_a

but then 

Since 
GO:0032188    establishment of actomyosin contractile ring localization
Biological Process
Definition 
The process in which a contractile ring is assembled in a specific location as part of a process of cell cycle cytokinesis.

is_a
GO:0007105   cytokinesis, site selection
Definition The process of marking the place where cytokinesis will occur.


It might be better to standardize the definitions and labels

i.e GO:0007105   cytokinesis, site selection and  GO:0032188     actomyosin contractile ring localization, site selection

OR

GO:0007105   establishment of  contractile ring localization and GO:0032188    establishment of actomyosin contractile ring localization


and standardizing the definitions. I think it's very confusing and I do a lot of cytokinesis annotation, so I suspect other will too. Very low number of EXP annotations seems to confirm this.

I'm still not convinced the current arrangement is the intended usage.
I'd previously assumed site selection was for things like mid1, marking the position where the ring would form, not actually building the ring- but if it was, we probably don't need this specificity.

**Comment by ValWood** [comment]
closing in favour of an older ticket that I had totally forgotten about 
https://github.com/geneontology/go-ontology/issues/16879
