### ISSUE TITLE
GO:0034050 missing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20255]
GO:0034050    JSON
host programmed cell death induced by symbiont

has no parentage to
GO:0051702   interaction with symbiont

**Comment by pgaudet** [comment]
Looking at the annotations, I put this under 'defense response to other organism' (we dont have 'defense response to symbiont', so I also added GO:0051702 (now called 'biological process involved in interaction with symbiont'). 

Should I create 'defense response to symbiont'? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also -> changed label from 'host programmed cell death induced by symbiont' to 'programmed cell death induced by symbiont' 
but I wonder if it would not be more clear to have 'programmed cell death in defense to symbiont' or something along those lines ? 

Thanks, Pascale

**Comment by ValWood** [comment]
yes,
 'programmed cell death in defense to symbiont' would be much clearer.

'defense response to symbiont'? is not a bad idea.  
It would probably be needed if  we eventually get rid of the organism specific ones in favour of some better method
