### ISSUE TITLE
NTR: nuclear corepressor activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20262]
This term is missing. It is similar to transcription corepressor activity. 

To be completed with @colinlog

**Comment by pgaudet** [comment]
Definition: 
A transcription coregulator activity that represses or decreases the transcription of specific gene sets via selective and non-covalent binding to a DNA-bound nuclear receptor. Corepressors often act by altering chromatin structure and modifications. For example, one class of transcription corepressors modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.

**Comment by pgaudet** [comment]
PMID: 7566114
PMID: 7566126

**Comment by pgaudet** [comment]
+id: GO:0140536
+name: nuclear corepressor activity
+namespace: molecular_function
+def: "A transcription corepressor activity that represses or decreases the transcription of specific gene sets via selective and non-covalent binding to a DNA-bound nuclear receptor. Corepressors often act by altering chromatin structure and modifications. For example, one class of transcription corepressors modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators." [PMID:7566114, PMID:7566126, PMID:9238851]
+comment: Curator guidance: Most transcription coregulators do not bind DNA. Those that do usually bind DNA either in a non-specific or non-direct manner. If a protein binds DNA specifically, consider annotating to GO:0003700 DNA binding transcription factor activity.
+is_a: GO:0003714 ! transcription corepressor activity
+relationship: part_of GO:0000122 ! negative regulation of transcription by RNA polymerase II
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20262 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-03T13:02:08Z

**Comment by ValWood** [comment]
did you mena to say " transcription corepressors " in the definition rather then "nuclear corepressor" in these 2 instances
For example, one class of transcription corepressors modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators."

**Comment by ValWood** [comment]
Also would  "nuclear receptor corepressor" be a better  term label?

I didn't know about these and I would immediately think this term just referred to a. nuclear version of a bog-standard  corepressor.

**Comment by pgaudet** [comment]
> Also would "nuclear receptor corepressor" be a better term label?

yes ok

**Comment by pgaudet** [comment]
Also changed nuclear receptor transcription coactivator activity -> nuclear receptor coactivator activity

**Comment by pgaudet** [comment]
Edited definition to "A transcription corepressor activity that represses or decreases the transcription of specific gene sets via selective and non-covalent binding to a DNA-bound nuclear receptor. Nuclear receptor corepressors often act by altering chromatin structure and modifications. For example, one class of transcription nuclear receptor corepressors modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators."

Thanks, Pascale
