### ISSUE TITLE
apoptotic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20269]
Please remove from the fission yeast slim set and add the taxon restriction 'never in S.pombe'
See
https://github.com/geneontology/go-annotation/issues/3474
for more detail.

**Comment by cmungall** [comment]
The linked paper (really interesting) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6069115/ suggests never-in Fungi

The paper also cites https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5864239/ "Molecular mechanisms of cell death: recommendations of the Nomenclature Committee on Cell Death 2018" which may be informative for synonyms in this part of the ontology

**Comment by pgaudet** [comment]
For 'apoptotic process ' and children, there are 52 EXP annotations to fungal proteins. 

Example papers: 
- PMID:16436509 "Yeast AMID homologue Ndi1p displays respiration-restricted apoptotic activity and is involved in chronological aging. " cerevisiae @srengel 
-   PMID:18047809 "Ectopic expression of mitochondria endonuclease Pnu1p from Schizosaccharomyces pombe induces cell death of the yeast."

Looks like this is related to apoptosis but different ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I only put "never in fission yeast"

There are papers which refer to apoptosis,. The general feeling in the pombe community is that people originally wanted to label this 'apoptosis' but it is not really apoptosis. It is also difficult to separate cause and effects here. Certainly when cells age  proteostasis breaks down (more ER overload, more ERAD etc)
proteases get released and things  get degraded.  The whole 'apoptosis' thing is part of the history of yeast researchers trying to make yeast relevant as a human model. Usually it is- but here it is still up for debate.

Current evidence it seems that there not enough to label these processes as apoptosis without any  real positive evidence that this is really regulated phenomena.  At present we just don't have any such evidence for 'apoptosis' in  fission yeast despite many people looking a lot for a long time. 

The S. cerevisiae community may feel differently.

I removed the 
PMID:18047809 "Ectopic expression of mitochondria endonuclease Pnu1p from Schizosaccharomyces pombe induces cell death of the yeast."
annotation yesterday.

The researchers removed the mitochondrial signal sequence to  ectopically express a non-specific mitochondrial nuclease  in the cytosol/nucleus.
Unsurprisingly nuclear DNA was fragmented.
I should not have annotated this to apoptosis. I now has only a phenotype annotation.

**Comment by srengel** [comment]
please do not add this constraint for all yeasts.  we need these terms for the S.cerevisiae community.

**Comment by pgaudet** [comment]
I've added Never in NCBITaxon:2	Bacteria

I think that's all we can assert confidently.

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/20312
