### ISSUE TITLE
NTR a second 4-amino-5-hydroxymethyl-2-methylpyrimidine   phosphate synthase activity 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#20274]
4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase activity (GO:0070284) has the parent "isomerase activity"

This appears to be different from (most or all) fungi which use a different mechanism from (most?) plant/bacteria see fig 1 PMID:18953358 
bacteria/plant make HMP-P from AIR, yeast from histine+ PLP

For fungal (and at least some bacterial) HMP-P synthase, the term HMP-P synthase should have "transferase activity" as parent
Kristian at RHEA adviced me that "Even though this reaction is very complex chemically, it definitely not an isomerase (EC 5) activity."
"The chemistry taking place in this reaction is to special that I have no good suggestions of more precise EC number than EC 2.-.-.-."

For Xref a new reaction was created:
[Rhea:65756]
Reaction=2 Fe(3+) + 4 H2O + L-histidyl-[4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase] + N(6)-(pyridoxal phosphate)-L-lysyl-[4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase] = (2S)-2-amino-5-hydroxy-4-oxopentanoyl-[4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase] + 3-oxopropanoate + 4-amino-2-methyl-5-(phosphooxymethyl)pyrimidine + 2 Fe(2+) + 2 H(+) + L-lysyl-[4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase]

**Comment by Antonialock** [comment]
AH shoot,, see another problem

this term is called "HMP synthase activity" but I see the def doesn't look right for fungal activity?
Catalysis of the reaction: 5-aminoimidazole ribonucleotide + S-adenosylmethionine = 4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate + 5'deoxyadenosine.

ThiC is also a synonym - bacterial and plant activity is different from fungi - bacteria/plant synthesise HMP-P from AIR, yeast from histine+ PLP ( fig 1 PMID:18953358 )

I think I need a new term?

**Comment by Antonialock** [comment]
original comment updated because I think that GO:0070284 is specific to plant and bacteria, and not for fungi

**Comment by Antonialock** [comment]
@ValWood only annotation to this is in PomBase, but I think  GO:0070284 is for bacteria

**Comment by Antonialock** [comment]
This new term should not be restricted to fungi however, it also exists in bacteria, e.g. PMID:33034117

**Comment by ValWood** [comment]
I removed the PomBAse annotation and will await the new term. weird that I had ISS'd this to SGD, but SGD has molecualr function unknown and ND.. ??!

**Comment by Antonialock** [comment]
Maybe this ref is useful for the reaction as well:
https://pubs.acs.org/doi/full/10.1021/ja302474a

**Comment by hdrabkin** [comment]
@Antonialock : The RHEA you cite above is not public yet so I cannot use it in the definition. However, I can still make the term using the J AM chem paper. However, before continuing, can you give me the suggested parent to the new term? Thanks in advance

**Comment by hdrabkin** [comment]
@Antonialock , I may be able to suggest a different name if I had the ACS paper. Jax has no subscription you attach the pdf to this ticket?

**Comment by hdrabkin** [comment]
How about  GO:new; Term: pyrimidine synthase?

**Comment by Antonialock** [comment]
but surely there are many other pyramidine-containing compounds, so would it be specific enough? 

If it is not (I don't know...) then how about 
4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase activity from AIR
4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase activity from histidine and PLP

there is precedence in GO:0102105 demethoxycurcumin synthase activity from feruloylacetyl-CoA
paper attached

[ja302474a(1).pdf](https://github.com/geneontology/go-ontology/files/5639204/ja302474a.1.pdf)

**Comment by Antonialock** [comment]
I can't attach the paper showing that at least some bacteria also have this enzyme (file too big), but it is 33034117

**Comment by Antonialock** [comment]
and the textual description is
Responsible for the formation of the pyrimidine heterocycle in the thiamine biosynthesis pathway. Catalyzes the formation of hydroxymethylpyrimidine phosphate (HMP-P) from histidine and pyridoxal phosphate (PLP). The protein uses PLP and the active site histidine to form HMP-P, generating an inactive enzyme. The enzyme can only undergo a single turnover, which suggests it is a suicide enzyme.

**Comment by hdrabkin** [comment]
Hi @Antonialock 
I shouldn't have asked; I don't know what I was thinking (not public domain). Anyway I took a shot with Pubmed and found that there was a PMC version availble, so I go it 
I think I like this one: 4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase activity from histidine and PLP

**Comment by hdrabkin** [comment]
I will use the RHEA def (which would eventually replace any other def anyways), but will mark this ticket RHEA-pending and put the xref in when it is publically available.

**Comment by hdrabkin** [comment]
+id: GO:0106344
+name: 4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase activity from histidine and PLP

**Comment by Antonialock** [comment]
great, thanks

**Comment by hdrabkin** [comment]
Rhea:65756 not yet available. will leave this open

**Comment by hdrabkin** [comment]
Rhea:65756 available; adding and will close now.
