### ISSUE TITLE
Obsolete GO:0044110 growth involved in symbiotic interaction and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20273]
Dear all, 

The proposal has been made to obsolete: 
GO:0044110 growth involved in symbiotic interaction
GO:0044117 growth of symbiont in host
GO:0044119 growth of symbiont in host cell
GO:0044121 growth of symbiont in host vacuole 

The reason for obsoletion is that these terms combine a process and a location. Moreover, most of the annotations are viability assays, not cell growth assays. Cell growth is defined as an increase in size, and this is not how these terms have been used. 

There are 11 annotations to this term by MTBASE (being reviewed). There are no mappings, those terms are not present in any slims. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 10th, 2020. Unless objections are received by November 10th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotations have been reviewed.

**Comment by marekskrzypek** [comment]
CGD will be hard hit again. Is there anything to replace these terms with? 
BTW, there is a whole bunch of terms that include "growth". Are they all going to be obsolete? In single cell microorganisms "growth" usually means growth of a culture, or multiplication of cells, not an increase in cell size.

**Comment by ValWood** [comment]
> "growth" usually means growth of a culture, or multiplication of cells, not an increase in cell size.

Yes exactly. Growth  when we are referring to growth of a culture isn't really telling us anything about the specific process.  If the culture does not grow, or grows slowly these are really viability or fitness phenotypes, not processes.

**Comment by ValWood** [comment]
@marekskrzypek just thinking, maybe there is an appropriate term in APO that you can use for these phenotypes?

**Comment by marekskrzypek** [comment]
yes, there may be

**Comment by pgaudet** [comment]
All annotations have been removed. Thanks everyone !
