### ISSUE TITLE
Simple diffusion transport

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#20282]
Hi

My question is related to the transporter activity. The classes under the grouping class "transmembrane transporter activity GO:0022857" are they simple diffusion or just general classification for narrower transport classes?  Except the classes "passive transmembrane transporter activityGO:0022803" and "active transmembrane transporter activity GO:0022804" .

**Comment by pgaudet** [comment]
Hi @Nizal-Shammry 

Simple diffusion is not in the scope of GO, because it is not enabled by any protein, but just describes substances passing through the membrane. So, the children are a  general classification for narrower transport classes. 

I hope that answers your question. 

Thanks, Pascale

**Comment by Nizal-Shammry** [comment]
Thank you for your quick reply. It is great answer
