### ISSUE TITLE
GO:0034515 proteasome storage granule - complex?

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#20297]
'proteasome storage granule' GO:0034515 is classed as a 'protein-containing complex' as it is a child of 'cytosolic proteasome complex'

But it seems to be just either a clump of inactive proteosome SUs and/or be a bit like a stress granule (rather than a complex, as we'd expect a complex to be capable of an MF) 

('protein-containing complex': A stable assembly of two or more macromolecules, i.e. proteins, nucleic acids, carbohydrates or lipids, in which at least one component is a protein and the constituent parts function together.)

Refs:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6771618/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7582879/

It's more of a yeast thing - so perhaps @ValWood @srengel have some opinions,  but it is being propagated by PAINT @pgaudet from PANTHER:PTN000101661, so is now on the fly radar:

Rather than a protein-containing complex, perhaps it is better as:

is_a intracellular non-membrane-bounded organelle
part_of cytoplasm

or just part_of cytoplasm

**Comment by ValWood** [comment]
I agree.

**Comment by krchristie** [comment]
This paper agrees that the PSG is a membrane-less organelle:

Marshall RS, Vierstra RD. **To save or degrade: balancing proteasome homeostasis to maximize cell survival.** Autophagy. 2018;14(11):2029-2031. doi:10.1080/15548627.2018.1515531. Epub 2018 Sep 11. PMID:30204036
> How membrane-less organelles such as PSGs isolate themselves from the surrounding cytoplasmic milieu is unclear,

**Comment by hattrill** [comment]
Thanks, @krchristie
