### ISSUE TITLE
Edit definition to BP transport

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#20292]
Hi

please would you change the definition for this term:
GO:0006810 transport
Definition
The directed movement of substances (such as macromolecules, small molecules, ions) or cellular components (such as complexes and organelles) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter, pore or motor protein.

Change to:
Definition
The directed movement of substances (such as macromolecules, small molecules, ions) or cellular components (such as complexes and organelles) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a pore, motor protein or transporter protein or complex.

So that it is clear that subunits of a transporter complex are transporting not regulating transport

See ticket https://github.com/geneontology/go-annotation/issues/3194

Thanks

Ruth

**Comment by ValWood** [comment]
I think this is a much more endemic issue than can be resolved with a single definition tweek unfortunately.
See  comment on
PTN000897489 (PTHR11523) geneontology/go-annotation#3194
