### ISSUE TITLE
GO:0044111 development involved in symbiotic interaction: obsolete and simplify terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20305]
From the multiorganism call Nov 4: 

GO:0044111 development involved in symbiotic interaction > propose obsoletion
GO:0044113 development in other organism involved in symbiotic interaction > propose obsoletion
GO:0044115 development of symbiont involved in interaction with host > propose obsoletion
GO:0044698 morphogenesis of symbiont in host cell > propose obsoletion - 0 annotations

GO:0052095 formation of specialized structure for nutrient acquisition from other organism involved in symbiotic interaction > propose obsoletion - 0 annotations
GO:0052098 formation by host of specialized structure for nutrient acquisition from symbiont > propose obsoletion - 0 annotations
GO:0044698 morphogenesis of symbiont in host cell : 0 annotations; obsolete, this is morphogenesis of a whole organism

 - [ ] GO:0052093 formation of specialized structure for nutrient acquisition from host - 0 annotations
 - [x] GO:0085019 formation by symbiont of a tubovesicular network for nutrient acquisition from host - 0 annotations
-> simplify to 'formation of a tubovesicular network for nutrient acquisition'
 - [x] GO:0075328 formation by symbiont of arbuscule for nutrient acquisition from host - 0 annotations
-> simplify to 'formation of arbuscule for nutrient acquisition'
 - [x] GO:0052094 formation by symbiont of haustorium for nutrient acquisition from host - 0 annotations
-> simplify to 'formation of haustorium for nutrient acquisition  '
 - [x] GO:0085001 formation by symbiont of stylet for nutrient acquisition from host - 0 annotations
-> simplify to 'formation of stylet for nutrient acquisition'
 - [x] GO:0052096 formation by symbiont of syncytium involving giant cell for nutrient acquisition from host  - 0 annotations
-> simplify to 'formation of syncytium involving giant cell for nutrient acquisition'
 - [x]  formation of symbiont germ tube hook structure for  development
-> simplify to  'formation of appressorium germ tube hook structure'
Move term from 'development involved in symbiotic interaction' 
 - [x]  GO:0075009 germ tube formation -> move as subclass of anatomical structure development 
 -  [x]   * * Merge GO:0009878 nodule morphogenesis  1 IEA  into GO:0009877 nodulation 
 - [x]  change parent 'anatomical structure formation involved in morphogenesis'   
 - [x] + add taxon constrain plant + PMID:21856632

 - [x] nuclear division involved in appressorium formation on or near host
-> remove 'on or near host' from term label
 - [x] GO:0075033 septum formation involved in appressorium formation
-> change label to 'appressorium septum formation' and change parent to 'anatomical structure formation involved in morphogenesis'   
part_of appressorium formation

 - [x] appressorium maturation
-> is_a anatomical structure maturation
See nice review for appresorium formation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4781897/

 - [x] GO:0075214 spore encystment on host  
-> change label to 'spore encystment' 
->  move to 'cell development'

 - [x] formation of host infection structure
-> change label to 'formation of infection structure' , keep as a grouping term (although @mgiglio99 proposed obsoletion in the comment below)

@mgiglio99 @dsiegele @cmungall @ValWood

**Comment by mgiglio99** [comment]
I think these obsoletions make sense.

Also - GO:0075033 'septum formation involved in appressorium formation' is already a child of GO:0075016 'appressorium formation' which is a descendant of 'developmental process' through 'formation of host infection structure'  and 'anatomical structure formation involved in morphogenesis' .
'formation of host infection structure'  should also probably be obsoleted - but it has some children that we might want to keep that involve appressorium and haustorium formation.
Without 'development involved in symbiotic interaction' to link child terms like 'nodule morphogenesis' and the appressorium and haustorium children mentioned above to 'interspecies interaction between organisms', would we make second parents for these children to interspecies interaction? (or symbiotic process?)

I'm not sure what you mean by decompose for that middle block of terms - does that mean turn them into terms like: 'arbuscule formation' with parents of 'developmental process' and 'interspecies interaction' (or 'symbiotic interaction')?

looping Suvvi in @nsuvarnaiari

**Comment by pgaudet** [comment]
Appresorium formation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4781897/

GO:0075009
![Uploading image.png…]()

**Comment by pgaudet** [comment]
0 annotations: 
*  GO:0044113  development in other organism involved in symbiotic interaction 
* GO:0044115 development of symbiont involved in interaction with host
* --- but regulation children has 37 EXP

**Comment by pgaudet** [comment]
Multi org call: 

We would like a grouping terms for 'formation of structure involved in a symbiotic process' - maybe we can repurpose '    GO:0044111 development involved in symbiotic interaction'
