### ISSUE TITLE
actin nucleation (GO:0045010) regulation parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20313]
actin nucleation (GO:0045010)
is currently 
is_a positive regulation of actin filament polymerization

but shouldn't this be part of 
actin filament polymerization

(nucleation, that activity, is the first stop in polymerization?)

**Comment by pgaudet** [comment]
So, actin nucleation should be an activity (see https://www.mechanobio.info/cytoskeleton-dynamics/what-is-the-cytoskeleton/what-are-actin-filaments/how-does-arp23-mediate-the-nucleation-of-branched-filaments/) that is part of actin filament polymerization, right ? 

I think what is confusing is that nucleation is a rate-limiting step, so it is sometimes described as 'regulation of actin polymerization', see also PMID:17477841

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
agreed
https://github.com/geneontology/go-ontology/issues/18609

This is the  question. Should we curate within process rate-limiting steps as "regulation" or "part_of" ?
We don't have guidelines for this.

**Comment by pgaudet** [comment]
I would say part of - the rate-limiting step always occurs at the same (slow) speed, doesn't it ? In that sense it does not really regulate, does it ? 

@ukemi @deustp01 Did you come across this for metabolism ?

**Comment by ValWood** [comment]
This is what I would think (i.e that in the context of regulating GO processes this isn't 'regulation').  We discussed a nice illustrative  example previously.
(part of) the signalling pathway for G2/M begins at the  plasma membrane, but  the rate-limiting 
(slowest step) is transfer of the signal through the nuclear pore. This does not really mean that the 
nuclear pore is regulating the signal transduction. There is already a commitment to the signal.

**Comment by ValWood** [comment]
Could we remove the "regulation parentage" from "actin nucleation" in anticipation of the MF refactoring? I'm trying to evaluate our use of "regulation" before we start GO-cam building to make sure that we are consistent in our use. This is one of the odd cases that doesn't fit.

**Comment by ValWood** [comment]
thanks. I only have a relatively small number of classes that are validly 'regulation'.  A few I will open tickets for and then some I want to discuss with you.
