### ISSUE TITLE
Merge cell death into programmed cell death ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20314]
From the ontology call - 

Need to look at the various terms: 
- cell death 
- programmed cell death
-  necrotic cell death
to make sure all are normal processes and  all are needed in GO. See this review: 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2744427/

Thanks, Pascale

**Comment by pgaudet** [comment]
+ create design pattern for apoptotic cell death (and others if we keep them).

**Comment by RLovering** [comment]
I am a bit confused. Obviously cell death is an essential and very normal process. Without it tissues would not be appropriately constructed/organised and we would all die from our immune system recognising our self antigens. Hopefully I am just misunderstanding the plan here
best
Ruth

**Comment by addiehl** [comment]
Also confused.  The definition of 'cell death' cites a more recent paper, from 2015, that supports the view that not all forms of regulated cell death are programmed cell death.
[https://pubmed.ncbi.nlm.nih.gov/25236395/](https://pubmed.ncbi.nlm.nih.gov/25236395/)

Didn't a group of GO editors and subject matter experts work on this area extensively already:
[http://wiki.geneontology.org/index.php/Apoptosis](http://wiki.geneontology.org/index.php/Apoptosis)

**Comment by RLovering** [comment]
yes we did

**Comment by pgaudet** [comment]
Looks like we have at least these two types of cell death: 
'necrotic cell death'
'programmed cell death'

which justifies the grouping term. 

Thanks, Pascale
