### ISSUE TITLE
taxon constraint 'ruffle' terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20311]
never in ~yeast~ fungi?
GO:0001726    ruffle | 19,898 annotations
GO:0031529    ruffle organization | 3,151 annotations
GO:0097178    ruffle assembly | 2,509 annotations
GO:0032587    ruffle membrane | 8,296 annotations
GO:1900027    regulation of ruffle assembly | 1,341 annotations
GO:1900029    positive regulation of ruffle assembly | 457 annotations
GO:1900028    negative regulation of ruffle assembly

**Comment by pgaudet** [comment]
Looks like this cannot occur in organisms with a cell wall ? @tberardini @AndreaAuchincloss

**Comment by ValWood** [comment]
That would make sense that it could not happen with a rigid cell.

**Comment by pgaudet** [comment]
Added never in bacteria, plant, fungi for 
GO:0001726    ruffle
and 
GO:1900027    regulation of ruffle assembly 

Others should be inferred. 

Thanks, Pascale
