### ISSUE TITLE
obsolete : peptide pheromone transmembrane export involved in positive regulation of conjugation with cellular fusion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20310]
please obsolete

GO:1990847 | peptide pheromone transmembrane export involved in positive regulation of conjugation with cellular fusion

to capture this we will need

NTR: ATPase-coupled oligopeptide transmembrane transporter *exporter* activity

descendant of

GO:0015421 ATPase-coupled oligopeptide transmembrane transporter activity

the pheromone cam be captured as a substrate

**Comment by pgaudet** [comment]
@ValWood 
We dont usually have the concept of 'exporter' /'importer' under MF; otherwise I really cannot see how we justify the distinction between MF and BP for transport. 

Can you use GO:0015421 ATPase-coupled oligopeptide transmembrane transporter activity + the substrate, and the BP export from cell ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I forgot that. Will do it that way.

**Comment by ValWood** [comment]
I will use
GO:0090539   peptide pheromone export by transmembrane transport

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:1990847 | peptide pheromone transmembrane export involved in positive regulation of conjugation with cellular fusion. 

The reason for obsoletion is that this represents a BP in a BP and should be represented with a GO-CAM model. There are 4 EXP annotations (PomBase; being reviewed). There is no mappings, this term is not present in any subsets.

You can add comments to the ticket: https://github.com/geneontology/go-ontology/issues/20310

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 16th, 2020. Unless objections are received by November 16th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by ValWood** [comment]
Pombase fixed
