### ISSUE TITLE
Issues with definition of "gamma-secretase complex"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#20317]
I am trying to identify the correct GO terms to use in annotations for a paper that talks about gamma-secretase complexes containing either presenilin 1 (Psen1) or presenilin 2 (Psen2). 

We have this term:

> [Term]
> id: GO:0070765
> name: **gamma-secretase complex**
> namespace: cellular_component 
> def: "A protein complex that has aspartic-type endopeptidase activity, and contains a catalytic
> subunit, **presenilin (PS)**, that is a prototypical member of the GxGD-type aspartyl peptidases. The
> complex also contains additional subunits, including nicastrin, APH-1, PEN-2, and a regulatory
> subunit, CD147. Gamma-secretase cleaves several transmembrane proteins including the cell surface
> receptor Notch and the amyloid-beta precursor protein." [GOC:mah, PMID:15286082, PMID:15890777, PMID:17047368] 
> synonym: "CD147-gamma-secretase complex (APH-1a, **PS-1**, PEN-2, NCT variant)" NARROW [CORUM:142]
> synonym: "gamma-secretase complex (APH1A, **PSEN1**, PSENEN, NCSTN variant)" NARROW [CORUM:130, CORUM:2891, CORUM:43, CORUM:45, CORUM:466]
> synonym: "gamma-secretase complex (APH1A, **PSEN2**, PSENEN, NCSTN)" NARROW [CORUM:468]
> synonym: "gamma-secretase complex (APH1B, **PSEN1**, PSENEN, NCSTN)" RELATED [CORUM:3128]
> synonym: "gamma-secretase complex (APH1B, **PSEN2**, PSENEN, NCSTN)" NARROW [CORUM:467]
> is_a: GO:0032991 ! protein-containing complex
> relationship: part_of GO:0005886 ! plasma membrane
> created_by: mah
> creation_date: 2009-06-29T01:33:19Z

Looking at synonyms cited, which contain references to specific subunit listings that include both PSEN1 and PSEN2, as well numerous papers, including the three PMIDs cited in the definition, I think it is clear that this definition is overly specific. Most illustrative are a couple sentences from this paper cited in the definition:

3: Kaether C, Haass C, Steiner H. **Assembly, trafficking and function of gamma-secretase.** Neurodegener Dis. 2006;3(4-5):275-83. doi: 10.1159/000095267. PMID:17047368.

**apparent source of def?**
>   In reconstitution experiments, γ-secretase was found to be composed of four integral membrane
>   proteins, presenilin (PS), nicastrin (NCT), PEN-2 and APH-1 that are essential and sufficient for
>   γ-secretase activity. PS, which serves as a catalytic subunit of γ-secretase, was identified as a
>   prototypic member of novel aspartyl proteases of the GxGD type.

**next sentence:**
>   In human cells, γ-secretase could be further defined as a heterogeneous activity consisting of
>   distinct complexes that are composed of PS1 or PS2 and APH-1a or APH-1b homologues together with NCT
>   and PEN-2.

Therefore, I would like to modify the existing definition to match the long time usage of the phrase **gamma-secretase complex** that it is 

def: "A protein complex that has aspartic-type endopeptidase activity and contains a presenilin catalytic subunit (either PSEN1 or PSEN2) that is a prototypical member of the GxGD-type aspartyl peptidases, an APH1 subunit (multiple genes and splice variants exist), nicastrin (NCT), and presenilin enhancer (aka PEN-2 or Psenen), as the core complex. A regulatory subunit may also be associated with the complex; known regulatory subunits include CD147, TMP1 (aka TMED2), more?.
[GOC:mah, PMID:15286082, PMID:15890777, PMID:17047368, additional references to be culled from my notes] 

To me this seems consistent with existing practice to change definitions to be consistent with intent. I don't think we want to have subclasses of gamma-secretase complexes because I think that that gets too specific for GO; there are at least 6 variants in human cells just looking at PSEN1 vs PSEN2 combined with multiple variants of APH1, nevermind multiple different possible regulatory subunits, or species variation e.g. that mouse has a third APH1 gene.

Any objections? @cmungall @ukemi @deustp01 @pgaudet - If so, please tag this with the editors-discussion tag and we'll talk about it next week. Otherwise, I'd like to proceed without taking time on a call.

**Comment by pgaudet** [comment]
I agree we can change the definition if it matches the intent. This is the typical 'cytokinesis' case that Rex was often citing.

@bmeldal does this new definition seem right to you ?

**Comment by bmeldal** [comment]
Yes, Sandra curated 4 variants in CP, APH1A or APH1B with PSEN1 or PSEN2.

Karen's suggested amendments sound right. We don't want to make child terms for each compositional variant unless we find that they have different functions (which they don't seem to have in this case).

**Comment by pgaudet** [comment]
great, thanks

**Comment by krchristie** [comment]
> Karen's suggested amendments sound right. We don't want to make child terms for each compositional variant unless we find that they have different functions (which they don't seem to have in this case).

That's what I'm seeing, all variants have the same enzymatic function with differences in location and specific substrates.

**Comment by krchristie** [comment]
Updated version of new def and some synonym updates:

**new def:** A protein complex that has aspartic-type endopeptidase activity and contains a
presenilin catalytic subunit (either PSEN1 or PSEN2), an APH1 subunit (multiple genes and
splice variants exist), nicastrin (NCT), and presenilin enhancer (aka PEN-2 or Psenen), as
the core complex. Variants of the complex with different subunit compositions differ in
localization and specific substrates. Additionally, variants of the complex also exist
that contain an additional regulutory subunit; known regulatory subunits include
γ‐secretase‐activating protein (aka gSAP), TMP1 (aka TMED10), and CD147 antigen (aka
basigin). Gamma-secretase cleaves type I transmembrane protein substrates, including the
cell surface receptor Notch and the amyloid-beta precursor protein.

existing refs: [GOC:mah, PMID:15286082, PMID:15890777, PMID:17047368]
**refs to add:** GOC:krc, PMID:22122073, PMID:25565961, PMID:32616437, PMID:28320827

**synonym to add:** "presenilin complex" [EXACT]
**synonym to add:** "PS1 complex" [RELATED]
**synonym to add:** "PS2 complex" [RELATED]


synonym: "CD147-gamma-secretase complex (APH-1a, PS-1, PEN-2, NCT variant)" NARROW [CORUM:142]
synonym: "gamma-secretase complex (APH1A, PSEN1, PSENEN, NCSTN variant)" NARROW [CORUM:130, CORUM:2891, CORUM:43, CORUM:45, CORUM:466]
synonym: "gamma-secretase complex (APH1A, PSEN2, PSENEN, NCSTN)" NARROW [CORUM:468]

synonym: "gamma-secretase complex (APH1B, PSEN1, PSENEN, NCSTN)" RELATED [CORUM:3128]
**=> change type to NARROW like all the other CORUM synonyms**

synonym: "gamma-secretase complex (APH1B, PSEN2, PSENEN, NCSTN)" NARROW [CORUM:467]
is_a: GO:0032991 ! protein-containing complex
relationship: part_of GO:0005886 ! plasma membrane
