### ISSUE TITLE
NTRs - reg terms for 'aspartic endopeptidase activity, intramembrane cleaving'

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#20341]
We have regulation terms for the very specific term `aspartic-type endopeptidase activity involved in amyloid precursor protein catabolic process`, and also for `aspartic-type peptidase activity`:

![regAspartic-typeEndopeptidaseTerms](https://user-images.githubusercontent.com/10533218/98825672-9f2fe380-23e9-11eb-9c64-09d92ee56a02.png)

but I think we need new regulation terms for the MF term `aspartic endopeptidase activity, intramembrane cleaving`. 

![Aspartic-typeEndopeptidaseTerms](https://user-images.githubusercontent.com/10533218/98825668-9dfeb680-23e9-11eb-896d-2c3ed9e01e1d.png)

**Comment by pgaudet** [comment]
Are those not all functions ?

**Comment by krchristie** [comment]
> Are those not all functions ?

@pgaudet - I don't understand what you're asking.

Basically, I need regulation terms for an existing MF term that doesn't currently have them. We have regulation terms for its sibling term (that names a specific substrate), and for an ancestor term, but not for the `aspartic endopeptidase activity, intramembrane cleaving`. I took screen shots of Protege to remind myself of the context since it was fast.
