### ISSUE TITLE
possible problem with current go snapshot

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20362]
This doesn't affect us, because it isn't the term  we need, but reporting as it is presumably a problem:
from https://github.com/geneontology/go-ontology/issues/16329

From @kimrutherford 
That took a bit of digging but it looks like it might be a problem with
the current snapshot.  We download this snapshot file and then process
it with owltools to create an OBO file that obeys the taxon
constraints:
  http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl

The OBO file from that doesn't contain GO:0060468

But if I do the same process with the release go-plus.owl:
  http://purl.obolibrary.org/obo/go/extensions/go-plus.owl
the result does contain GO:0060468

**Comment by balhoff** [comment]
When I look at `http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl`, I do see GO:0060468. Maybe if @kimrutherford can paste the owltools command I can try to replicate.

**Comment by ValWood** [comment]
ok maybe it is fixed now. I still don't see
+[Term]
+id: GO:0140538
+name: negative regulation of conjugation with zygote
+namespace: biological_process
+def: "A process that prevents a zygote from fusing with additional cells." [PMID:30089908]
+is_a: GO:0060467 ! negative regulation of fertilization
+property_value: term_tracker_item #16329 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-07T07:50:23Z

as of today- I'll try tomorrow.

cheers,
v

**Comment by pgaudet** [comment]
Weird. There was a snapshot yesterday.  I see the term in the go-basic.obo file here http://snapshot.geneontology.org/ontology/index.html

Thanks, Pascale

**Comment by ValWood** [comment]
Hmm, did anything else change at GO end?

Or at our end @kimrutherford ?

**Comment by kimrutherford** [comment]
> When I look at http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl, I do see GO:0060468. Maybe if @kimrutherford can paste the owltools command I can try to replicate.

Hi Jim.

This is the command line we use to make a pombe-only subset:

```
curl -L http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl > go-plus-snapshot-2020-11-12.owl
owltools go-plus-snapshot-2020-11-12.owl --reasoner elk  --make-species-subset --perform-macro-expansion false -t NCBITaxon:4896 -o -f obo --no-check go-plus-snapshot-2020-11-12.obo
grep GO:0060468 go-plus-snapshot-2020-11-12.obo
```

I used the 2020-04-06 release of owltools.  GO:0060468 is missing from the output.

If I do the same thing with the release go-plus.owl, GO:0060468 is in the output:

```
curl -L http://purl.obolibrary.org/obo/go/extensions/go-plus.owl > go-plus-release.owl
owltools ./go-plus-release.owl --reasoner elk  --make-species-subset --perform-macro-expansion false -t NCBITaxon:4896 -o -f obo --no-check go-plus-release.obo
grep GO:0060468 go-plus-release.obo                                                                                                                                               
```
```
go-plus-release.obo:id: GO:0060468
go-plus-release.obo:relationship: part_of GO:0060468 ! prevention of polyspermy
```

Thanks for your help.

**Comment by kimrutherford** [comment]
Sorry, I just noticed this:

> ok maybe it is fixed now. I still don't see
> +[Term]
> +id: GO:0140538

Val, in the other issue (#16329) you mention GO:0060468 but in this issue you mention GO:0140538.  Which one is the problem?  GO:0140538 is not in the taxon-restricted output OBO file for the release or the snapshot.  Should it be?

**Comment by ValWood** [comment]
Sorry, I might be conflating 2 issues, but I wondered if they were related.

I wanted to replace 
GO:0060468 ! prevention of polyspermy
in 
https://curation.pombase.org/pombe/curs/46c89f342f117ca5
by
GO:0140538: negative regulation of conjugation with zygote

So 2 unusual things occurred at the same time:

1. GO:0140538 did not  yet become available
2. GO:0060468 prevention of polyspermy became "UNKNOWN TERM"  in Canto  (so I could not re-approve the session while the new term came through) which would usually be possible.

Even though "GO:0060468 prevention of polyspermy" will *eventually*  become taxon restricted for fission yeast (might even be now) , it was not at the point when I looked. I could not see any obvious reason why this term would appear as "UNKNOWN TERM"

So, I had 2 odd things occurring in the same annotation session, I assumed there might be some connection, but it is also possibly just a coincidence......

**Comment by balhoff** [comment]
@kimrutherford thanks, that was very helpful! I think I know what is going on. This is a consequence of the way `--make-species-subset` works. GO:0060468 is not restricted from fission yeast. However some terms it relates to are connected to 'multicellular organismal process'. It's confusing because I do not mean that 'in taxon' is being inferred across these relationships. `--make-species-subset` temporarily pretends that ALL terms are in_taxon fission yeast (for example). Then it queries for all unsatisfiable classes, and removes them.

The reason this has suddenly started happening is that we recently started bringing in additional axioms from CL. The problem axiom is `'germ cell' SubClassOf 'capable of' some 'multicellular organismal reproductive process'`. Either we need to remove this, or remove the restriction `'multicellular organismal process' never_in_taxon 'Schizosaccharomyces pombe'`.

<img width="923" alt="process" src="https://user-images.githubusercontent.com/210210/99006307-40b15500-2510-11eb-9e32-aaa3aa3077f2.png">

@cmungall what do you think the fix is for this? Or @ValWood are you fine with this?

**Comment by ValWood** [comment]
It depends what  you are asking

It wouldn't be the best solution to remove
'multicellular organismal process' never_in_taxon 'Schizosaccharomyces pombe'
because this high level taxon check captures/prevents a lot of taxon violations

GO:0060468  really IS a taxon violation. It's just that when had used it, this wasn't so clear, and it did not have a flag. Now have a taxon appropriate term, I requested a taxon restriction on GO:0060468, but I could not figure why we were already being prevented from using it.  So if these inferences can tell us terms which appear to be taxon inappropriate based on the reasoning, even though they are not flagged ass such  the current behaviour is  is fine.

Did I understand correctly? In summary, I would always  rather be told that something is incorrect than not be told that something is  incorrect.

**Comment by balhoff** [comment]
@ValWood would you ever want to use 'fertilization' or 'germ cell' with S. pombe? I just googled and I guess they do a sort of fertilization (https://www.sciencedirect.com/science/article/pii/S0960982218312739).

I would expect both of these terms to be excluded by `--make-species-subset` as well.

**Comment by ValWood** [comment]
that's OK. We use the related  fungal equivalent "conjugation with cellular fusion".

Yeast people are not partial to the words 'gamete' and 'fertilization' and the processes are sufficiently different to exclude.

**Comment by balhoff** [comment]
Okay great, then it sounds like everything is good here.
