### ISSUE TITLE
NTR phosphatidylinositol-4,5-bisphosphate sensor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20361]
new term: phosphatidylinositol-4,5-bisphosphate sensor activity
definition: Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of phosphatidylinositol-4,5-bisphosphate. 
parent: GO:0106254   lipid sensor activity
exact synonym PI(4,5)P2 sensor
reference PMID: 33172987
Do these also have has_part relation to binding? Not sure?

Fission yeast Opy1 is an endogenous PI(4,5)P2 sensor that binds the PI5-kinase Its3.              Snider CE, Willet AH, Brown HT, Chen JS, Evers JM, Gould KL. J Cell Sci. 2020 Nov 10:jcs.247973. doi: 10.1242/jcs.247973. Online ahead of print. PMID: 33172987

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140550
+name: phosphatidylinositol-4,5-bisphosphate sensor activity
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of phosphatidylinositol-4,5-bisphosphate" [PMID:33172987]
+intersection_of: GO:0140299 ! small molecule sensor activity
+intersection_of: has_input CHEBI:58456 ! 1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate(5-)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20361 xsd:anyURI
+created_by: pg
+creation_date: 2020-11-12T13:01:17Z
