### ISSUE TITLE
taxon constraint: neuron death GO:0070997

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20374]
please add taxon restriction

neuron death (GO:0070997
"never in fungi"

from
https://github.com/geneontology/go-annotation/issues/3517

**Comment by pgaudet** [comment]
Wait, neuron is only in metazoa, shouldn't that exclude pombe ?

**Comment by ValWood** [comment]
I guess so, but we got an annotation through
to
GO:1903204 | negative regulation of oxidative stress-induced neuron death

**Comment by pgaudet** [comment]
ah ok 

Taxon constraints are not transitive over 'regulates'. So we need to figure out the highest level 'neuron' process in the regulation branch to avoid those.

**Comment by pgaudet** [comment]
I'll do 'regulation of neuron death' for this one.

**Comment by pgaudet** [comment]
as well as 
GO:0045664	regulation of neuron differentiation	NCBITaxon:33208	Metazoa
GO:2001222	regulation of neuron migration	NCBITaxon:33208	Metazoa
