### ISSUE TITLE
Add taxon constraints GO:0007234 | osmosensory signaling via phosphorelay pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20372]
GO:0007234 | osmosensory signaling via phosphorelay pathway

should merge into 

GO:0007231 | osmosensory signaling pathway

(MF + BP) the phosphorelay cen be described by individual BPs and is upstream of the MAPkinases.
At present, one  linear segment of this pathway has 3 different  labels.

**Comment by pgaudet** [comment]
There are 3 main children classes: 

- [part_of] GO:0000169   activation of MAPK activity involved in osmosensory signaling pathway (+ MAPKK GO:0000168 and MAPKKK GO:0000167) 
- GO:0007232 osmosensory signaling   pathway via Sho1 osmosensor
-  GO:0007234 osmosensory signaling   via phosphorelay pathway

Does that mean that there are 3 main osmosensory signaling pathways, (1) MAPK, (2) Sho1, (3) phosphorelay pathway? 
Or should all these merge ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I have a feeling they are referring to 3 parts of the same pathway
i the sensor, ii) phophorelay and iii)  the MAPK component 
I will try to find a full  pathway image, but should also check this one with SGD. @srengel

**Comment by ValWood** [comment]
https://www.semanticscholar.org/paper/Response-to-Hyperosmotic-Stress-Saito-Posas/9af0126946ebfc3f57ad66935c8213ee27926466/figure/1

There are 2 converging pathways, 
named for S. cerevisiae 

GO:0007232 osmosensory signaling pathway via Sho1 osmosensor
is odd, it should say more about the 'module' than the sensor. This seems to refer to the GTPase module (via Cdc42)

ste11 pbs2 hog1 is the MAP kinase module

ypd1 /ssk2 is the phosphorelay module

Maybe it is OK if the 
GO:0007232 osmosensory signaling pathway via Sho1 osmosensor
is renamed to 
osmosensory signaling pathway GTPase signalling module, or similar so that others can use it too?
And why name after one sensor when there seem to be multiple sensors?

Personally I woud have simplified this area to something like
regulation of MAP kinase signalling  cascade occurs_during response to osmotic stress
for everything upstream of the MAPK cascade

but I would keep as it is for now. Have we established yet that pathways should not be named after receptors or sensors?  Otherwise the same pathways end up being represented multiple times.

**Comment by pgaudet** [comment]
Right, I thought the rule was pathways were represented by receptors. Lets see what @srengel says.

**Comment by ValWood** [comment]
I think we can simplify the ticket.

Just add never in fission yeast to
GO:0007232 osmosensory signaling pathway via Sho1 osmosensor
GO:0007234 osmosensory signaling via phosphorelay pathway

fission yeast does not have Sho1 osmosensor, and I don't think that osmolarity signals through phosphorelay in fission yeast, that seems to be only oxidative stress @Antonialock is that correct?

**Comment by ValWood** [comment]
There is also 
osmosensory signaling MAPK cascade !

**Comment by Antonialock** [comment]
>  I don't think that osmolarity signals through phosphorelay in fission yeast,

From what is known today I don't think it does. But, oxidative and osmosensory signals appear to converge on the same stress activated MAPK cascade.

**Comment by ValWood** [comment]
Agreed, I was reading papers about this week.

So  if we go ahead and taxon restrict the terms, SGD  need not change anything. There are a lot of terms though!

**Comment by srengel** [comment]
> So if we go ahead and taxon restrict the terms, SGD need not change anything. 

this works for SGD :)
