### ISSUE TITLE
taxon constraint: GO:0071588    hydrogen peroxide mediated signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20373]
GO:0071588    hydrogen peroxide mediated signaling pathway

we have used this but we shouldn't have. It's just canonical stress signalling in response to oxidative stress.

the only other EXP annotations are for Arabidopsis which does have hydrogen peroxide-mediated signalling

**Comment by ValWood** [comment]
add never in fungi

**Comment by pgaudet** [comment]
Yeah I was hoping we could merge this somewhere - I'll just add the constraint for now 

@tberardini any thoughts on this pathway?

**Comment by tberardini** [comment]
No thoughts on merging, don't know enough without reading more which unfortunately I don't have the time for right now.
