### ISSUE TITLE
GO:0005078   MAP-kinase scaffold activity parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20370]
Most  adaptors now get classified as MF activities, rather than 'binding' activities. Except for this one which is still  classed as 'protein binding' GO:0005078   MAP-kinase scaffold activity

**Comment by pgaudet** [comment]
I dont understand - its parent is 'signaling adaptor activity' 

I changed 'is a kinase binding' to ''has part' some 'mitogen-activated protein kinase binding' - maybe that will fix the issue ?

**Comment by ValWood** [comment]
It's OK- we probably need to do something internally so that non-binding parentage takes precedence...

**Comment by pgaudet** [comment]
But maybe the is_a was creating issues ? I thought you were not loading has_parts ?

**Comment by ValWood** [comment]
I see this:

<img width="784" alt="Screen Shot 2020-11-17 at 14 34 02" src="https://user-images.githubusercontent.com/7359272/99403073-f8b07a80-28e1-11eb-8f6e-7305cc090450.png">


where for others (eg. chromating adaptors)
https://www.pombase.org/gene/SPAC15A10.15

I see this:

<img width="781" alt="Screen Shot 2020-11-17 at 14 35 30" src="https://user-images.githubusercontent.com/7359272/99403249-272e5580-28e2-11eb-8c2a-73a806837716.png">

so some "adaptors" appear as binding terms and some as "activities". I would like them to all appear as activities.

**Comment by pgaudet** [comment]
Right, other terms have 'has part' (for eg signaling receptor complex adaptor activity)
