### ISSUE TITLE
NTR: glutarate dioxygenase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#20386]
Definition: Catalysis of the reaction glutarate + 2-oxoglutarate + O2 = (S)-2-hydroxyglutarate + succinate + CO2.  Parent: GO:0016706.  This is EC 1.14.11.64.

Thanks,
Ingrid

**Comment by pgaudet** [comment]
* I think this could be a child of GO:0016706 2-oxoglutarate-dependent dioxygenase activity
* Rhea: 13821

**Comment by hdrabkin** [comment]
@keseler , can supply a reference also.
Rhea for this term is RHEA:13821
@pgaudet GO:0016706  does not  have a RHEA; it ihas a 3 digit ec xref (EC:1.14.11)
I think the EC should be changed to 

  | EC 1.14.11.64 Glutarate dioxygenase, and then the RHEA is valid; 
-- | --

**Comment by hdrabkin** [comment]
No; what should happen is the RHEA and EC  gets added to GO:0016706; No additional term needed.

**Comment by hdrabkin** [comment]
Ah never mind I have too many windows open.
+id: GO:0106343
+name: glutarate dioxygenase activity

**Comment by keseler** [comment]
Hi @hdrabkin,
I'm not sure I understand your shorthand.  I think you proposing that GO:0016706 should become my proposed new activity?  So would there be no mapping from the current EC parent, 1.14.11, to GO any more?  GO:0016706 already is 2-oxoglutarate-dependent dioxygenase activity.  I'm confused.

Did I cause the confusion by writing "this is EC 1.14.11.64"?  Sorry, that was meant to refer to the proposed reaction, not the parent GO term, GO:0016706.

Ah, you just created a new term. :-)

Thanks,
Ingrid

**Comment by hdrabkin** [comment]
No, never mind I had two many windows opened. However, if you do have a PMID, I could add it.

**Comment by keseler** [comment]
PMID 30498244.  Thanks!

**Comment by hdrabkin** [comment]
done
