### ISSUE TITLE
  terms combining  MF (MAPK activity) and BP involved in (osmosensory signaling pathway)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20380]
activation of MAPK activity involved in osmosensory signaling pathway
activation of MAPKK activity involved in osmosensory signaling pathway
activation of MAPKKK activity involved in osmosensory signaling pathway
inactivation of MAPK activity involved in osmosensory signaling pathway

**Comment by pgaudet** [comment]
Obsolete ? I suppose, since similar terms were obsoleted, for eg GO:0038081 obsolete MAP kinase kinase kinase activity involved in osmosensory signaling pathway

**Comment by ValWood** [comment]
Yes, slightly different reason.  these are  process terms  "regulation of MF in BP". The others  GO:0038081 was and MF involved in BP

These terms  would be outlawed by 
https://github.com/geneontology/go-ontology/issues/20513

**Comment by pgaudet** [comment]
- I changed the PINC TAS annotation to 'positive regulation of JNK cascade', which is a child of ' GO:0032872 regulation of stress-activated MAPK cascade' 
- Other annotations as by AspGD to PMID:15882418 and PMID:25597841, so I will merge into  GO:0000161 osmosensory signaling MAPK cascade. 

@marekskrzypek 

Thanks, Pascale
