### ISSUE TITLE
tyrosine binding - autoclassification issue

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#20408]
While working on this ticket:  **NTR tryptophan binding** #20181, I noticed that the term **tyrosine binding** does NOT auto-classify under **amino acid binding** based on its equivalence axiom, though many other binding terms for specific amino acids do.

These are the binding terms for specific amino acids that DO auto-classify under **amino acid binding**:

![aminoAcidBinding-children](https://user-images.githubusercontent.com/10533218/99471734-0c68da80-28fc-11eb-8d62-6407f0e9f1db.png)

Here are the equivalence axioms and resulting Inferred SubClass Of relationships for some sample terms:

![aminoAcidBinding-EA](https://user-images.githubusercontent.com/10533218/99471737-0d017100-28fc-11eb-868d-76d81083864a.png)

![serineBinding-EA](https://user-images.githubusercontent.com/10533218/99471738-0d9a0780-28fc-11eb-81e2-d9c6205603e3.png)

![TyrBinding-EA](https://user-images.githubusercontent.com/10533218/99471740-0e329e00-28fc-11eb-9fe8-871b105fbfe4.png)

@deustp01  - Do you know what form of tyrosine is the relevant form at pH 7.3?

 @balhoff - Does the 7.3 mapping file from Rhea have any info on this?

**Note**: There might be other existing binding terms for specific amino acids that are not auto-classifying, but I haven't gone through systematically to check.

**Comment by pgaudet** [comment]
This looks like its fixed 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/4782928/105817524-035c4f80-5fb6-11eb-8d03-5f949bbbe44b.png">

**Comment by krchristie** [comment]
@pgaudet - This is not fixed. The problem was the lack of autoclassification of some of the binding terms for specific amino acids NOT autoclassifying under the term `amino acid binding`. The inferred child terms under `amino acid binding` are unchanged from the picture I posted in the initial comment.

**Comment by pgaudet** [comment]
I made a PR where I changed 

intersection_of: has_input CHEBI:37022 ! amino-acid anion
to 
intersection_of: has_input CHEBI:33709 ! amino acid

and now 'tyrosine binding' classifies correctly. 

https://github.com/geneontology/go-ontology/compare/issue-20408?expand=1

Can we merge that ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I created a test term, 'valine binding', which also doesn't have a GCI, and it classifies correctly using the logical definition: 

binding 
and 'has input' some valine


So, we can close this ! 
Thanks, Pascale
