### ISSUE TITLE
Taxon constrain to GO:0031428 'box C/D snoRNP complex' and  GO:0005732 'small nucleolar ribonucleoprotein complex' 

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#20416]
Hi, 

In the paper below, they show the existence of  an archaeal functional homolog of  the eukaryotic  snoRNP core protein.

Archaeal ribosomal protein L7 is a functional homolog of the eukaryotic 15.5kD/Snu13p snoRNP core protein. 
(PMID: 11842104 )

Initially we had curated that with 
 GO:0005732 'small nucleolar ribonucleoprotein complex' that has note:

Comments
Note that 'nucleolar' in the term name is part of the RNA family designation 'small nucleolar', and does not necessarily reflect the location of the complex.

Could the restrictions to either term change so we can still capture this?

Thanks,

Penelope

**Comment by krchristie** [comment]
This makes sense to me in light of the evolutionary relationship discussed in this paper and in 3 refs it cites: 
- Dennis PP, Omer A, Lowe T. **A guided tour: small RNA function in Archaea. Mol Microbiol.** 2001 May;40(3):509-19. doi: 10.1046/j.1365-2958.2001.02381.x. PMID:11359559.
- Omer AD, Lowe TM, Russell AG, Ebhardt H, Eddy SR, Dennis PP. **Homologs of small nucleolar RNAs in Archaea.** Science. 2000 Apr 21;288(5465):517-22. doi:10.1126/science.288.5465.517. PMID:10775111.
- Gaspin C, Cavaillé J, Erauso G, Bachellerie JP. **Archaeal homologs of eukaryotic methylation guide small nucleolar RNAs: lessons from the Pyrococcus genomes.** J Mol Biol. 2000 Apr 7;297(4):895-906. doi:10.1006/jmbi.2000.3593. PMID:10736225. [Erratum in: J Mol Biol 2000 Jul 21;300(4):1017-8.]

Looking at where the taxon constraints come from, I currently think it is based on this relationship:
`small nucleolar ribonucleoprotein complex` SubClass Of  `nuclear protein-containing complex`, which got left there (or wasn't present) when I added the note about the lack of requirement for a `small nucleolar ribonucleoprotein complex` to be located in the nucleolus. 

I think it would also be good to 
- expand the definition of the box C/D term to include some mention of the presence of Archaea
- maybe change the name to be `box C/D RNP complex`, and the move the current name of `box C/D snoRNP complex` to be a narrow synonym
- add a narrow synonym of `box C/D sRNP complex`

**Comment by krchristie** [comment]
This relationship was one of the problems:

> `small nucleolar ribonucleoprotein complex` SubClass Of `nuclear protein-containing complex`, which got left there (or wasn't present) when I added the note about the lack of requirement for a `small nucleolar ribonucleoprotein complex` to be located in the nucleolus.

I also had to remove this relationship from the `box C/D snoRNP complex`
-relationship: part_of GO:0005730 ! nucleolus

**Comment by krchristie** [comment]
In addition to the changes I listed in my first comment, I have also made these changes:
- changing name of this term from: `small nucleolar ribonucleoprotein complex` to `snoRNA-containing ribonucleoprotein complex` so that it won't look like it should be restricted to the `nucleolus`.

**Comment by pgarmiri** [comment]
Thank you Karen, that's brilliant!
