### ISSUE TITLE
GO:0038066    p38MAPK cascade

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20415]
GO:0038066    p38MAPK cascade

please add positive and negative regulation terms

(I would like to move annotations down from generic GO:0051403    JSON
stress-activated MAPK cascade, but there. are not corresponding regulation term)

**Comment by pgaudet** [comment]
Terms already exist: 

- GO:1903753 negative regulation of p38MAPK cascade
- GO:1900745 positive regulation of p38MAPK cascade
- GO:1900744 regulation of p38MAPK cascade 

Closing- please reopen if I missed something.

**Comment by ValWood** [comment]
yes could you remove 

GO:0038066 | p38MAPK cascade | Only in Taxon | 33208 | Metazoa

I think this was me but I now realise it is better to use this term otherwise I can't resolve the individual pathways...

**Comment by ValWood** [comment]
need to remove only in metazoa. That might not be done?

**Comment by pgaudet** [comment]
Removed here: https://github.com/geneontology/go-ontology/commit/0145d5f8a8e2d0a48f8856c8f231bd9bc99d712d#diff-903cc23152e45e0f3c36bea1dc4b45216da7a429b3bd1ce4dfc9510fe6b20584

It's not in the main file: https://github.com/geneontology/go-ontology/blob/master/src/taxon_constraints/only_in_taxon.tsv

Maybe it takes a couple of days to get to pombase ?
