### ISSUE TITLE
NTR: parent term for  GO:0032977 membrane insertase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#20414]
Dear GO editors, @bmeldal 
it looks like we are lacking a molecular function term to describe proteins involved in insertion of transmembrane domains into membranes. GO:0032977 membrane insertase activity is too specific and cannot be applied to the co- or post-translational insertion of proteins in the endoplasmic reticulum membranes.  The EMC and the GET complexes are for instance involved in that mechanism: PubMed=30415835 , PubMed=29809151, PubMed=29242231, PubMed=32459176, PubMed=32439656, PubMed=29809151, PubMed=31263175.
Could we create a general term to describe proteins that channel and insert TMs into membranes as a child of  GO:0140104 molecular carrier activity.
Thanks,
Lionel

**Comment by pgaudet** [comment]
@lbreuza 

Can you please provide a possible definition for this term ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I wanted this term too.
I think we have something in BP that described "insertase activity" probably needs moving
https://github.com/geneontology/go-ontology/issues/16203

**Comment by ValWood** [comment]
deleting comment

**Comment by lbreuza** [comment]
I would propose something basic that fits with parent and child terms :"Binds transmembrane domain-containing proteins and mediates their integration into a membrane".  The mechanism is sophisticated but could differ depending on complexes/proteins involved in the insertion. Maybe @ValWood as a better suggestion.

**Comment by ValWood** [comment]
GO:0032977    membrane insertase activity
Molecular Function

Definition (GO:0032977 GONUTS page)
Mediates the integration of proteins into a membrane from the inner side of the membrane. Membrane insertases are highly conserved and include the bacterial YidC family, the plant chloroplast Alb3 family, and the fungal and animal mitochondrial Oxa1/Cox18 family. PMID:14739936

I annotated GET complex with

GO:0032977 | membrane insertase activity | 
part of tail-anchored membrane protein insertion into ER membrane

Does that not work for you?

**Comment by ValWood** [comment]
Ah I notice it says "from the inner side of the membrane", is that your problem?
But the definition gloss also includes Oxa1/Cox18  which inserts into the outerside of the IMM doesn't it?

@pgaudet  I don't think the definition gloss is useful here. It says the proteins are highly conserved, then lists unrelated families so it's a bit contradictory. I don't think people will need examples of insertases if  well defined?

**Comment by pgaudet** [comment]
I can change the definition to what @lbreuza proposes; I think that would address the question ?

**Comment by ValWood** [comment]
yes!

**Comment by ValWood** [comment]
Hi @lbreuza  you probably saw this already, structure for yeast and human EMC complexes...
https://pubmed.ncbi.nlm.nih.gov/33236988/

**Comment by lbreuza** [comment]
Hi @ValWood , yes I came with this NTR while curating that paper and others describing the structure and the function of the EMC.
Thx!
