### ISSUE TITLE
update children of GO:0099120 socially cooperative development

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#20428]
GO:0099120 socially cooperative development has been added when 'social behavior' was taxon restricted a while back. When checking out children, I noticed that many direct children of 
GO:0030587 sorocarp development' such as 
-- GO:0031152 aggregation involved in sorocarp development
are children of GO:0099120.

It would make sense to move also the direct parent, GO:0030587 sorocarp development as a child of GO:0099120 socially cooperative development, as it is definitely true: sorocarp development is_a socially cooperative development. Especially as all developmental stages of sorocarp development are already children.

GO:0099120 socially cooperative development
-is_a GO:0030587 sorocarp development 
-- is_a GO:0031152 aggregation involved in sorocarp development
-- is_a GO:0031153 slug development involved in sorocarp development
.
.
All children and 'grand-children that are not yet, can move under GO:0099120 ocially cooperative development.

Thanks, 
Petra

**Comment by pgaudet** [comment]
Hi @pfey03 
Some Dicty terms are under 'non-reproductive fruiting body development'; isn't that a better parent? 

The only other sibling to 'GO:0099120 socially cooperative development' is  'GO:0099135 chimeric colonial development'; this sounds very similar (term created here: https://github.com/geneontology/go-ontology/issues/12357)

<img width="570" alt="image" src="https://user-images.githubusercontent.com/4782928/99711467-17f60600-2aa2-11eb-80f2-6e1336fa2f03.png">


Just wanted to makre sure you saw that. If we move other dicty terms under 'GO:0099120 socially cooperative development' then there is no need for 'non-reproductive fruiting body development' - did I miss something ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@pfey03 Did you have a chance to look at this ?

**Comment by pfey03** [comment]
@pgaudet sorry @pgaudet , too many projects. I now looked how many direct annotations are to 'non-reproductive fruiting body development', there are 2: One IEP from UniProt to a dicty gene and one IEA to Dpur from EnsemblProtist. So from my perspective, yes, there is no need for this term, and all could better be moved directly under GO:0099120 socially cooperative development. Thanks!

**Comment by pfey03** [comment]
@pgaudet, inspecting this issue, it should be the easiest to solve. Since there are basically no annotations, just the one IEP from UniProt and one IEA, I think GO:0090702 non-reproductive fruiting body development can either go, or be merged with  GO:0099120 socially cooperative development as a related synonym.  Maybe merging is the way to go.

David OS added all these terms back then when he really got into Dicty and to give us enough options because 'social behavior' had been taxon restricted.
