### ISSUE TITLE
ntr: replication fork relocation to nuclear pore complex

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#20450]
We've received a request from community curator Sarah Lambert, to use for PMID:33159083:

name: replication fork relocation to nuclear pore complex
suggested def (cribbed from the paper intro): A cellular process in which a DNA replication fork that has stalled relocates and anchors to the nuclear periphery ~nuclear pore complex, in a poly-SUMO and STUbL-dependent manner,~ for the time necessary to complete recombination-dependent replication.
exact synonyms: replication fork relocation to NPC; stalled replication fork relocation to nuclear pore complex

I think this should be linked to GO:0031297 ! replication fork processing by is_a or part_of. Part_of might be slightly more biologically accurate, but then I would struggle to suggest a superclass, so I won't complain if the new term is is_a GO:0031297.

Please let me know if you have any problems or questions (which I'll probably have to relay to Sarah).

**Comment by mah11** [comment]
Sarah has suggested a slightly broader definition, in case not everything her lab has observed about the fission yeast case generalizes. I've edited the original, and include some of her message here:

> I have proposed a broader definition:
> 
> "the process in which a DNA replication fork that has stalled is signaled to relocate and anchor to the
nuclear periphery."
> 
> In our paper we find this process is STUBL and SUMO-dependent. I[t] cannot be excluded that other type of fork
stalling leads to different signaling.

**Comment by krchristie** [comment]
Hi @mah11 - taking a look at the ontology in Protege, I think that a good is_a parent might be `cellular localization`. If you want the new term to have a `part_of` relationship to `replication fork processing`, then I think that needs to be mentioned in the definition. Here's my attempt to merge the information you and Sarah provided with the existing definitions of the  proposed parent terms. Do you think this satisfies the term request within the known biology? Let me know if you have any other suggestions.


**id**: GO:0120290
**name**: replication fork localization to nuclear periphery for replication fork processing
**namespace**: biological_process
**def**: "A cellular localization process where a DNA replication fork that has stalled is signaled to relocate and anchor to the nuclear periphery for the time necessary to complete recombination-dependent replication." [GOC:krc, GOC:mah, PMID:33159083]
**intersection_of**: GO:0051641 ! cellular localization
**intersection_of**: transports_or_maintains_localization_of GO:0005657 ! replication fork
**intersection_of**: has_target_end_location GO:0034399 ! nuclear periphery
**intersection_of**: part_of GO:0031297 ! replication fork processing

**Comment by mah11** [comment]
Thanks for the `is_a cellular localization` suggestion - that sounds good. The text and logical definitions look fine; I do wonder whether Sarah is being a bit over-cautious in not specifying `NPC` instead of `nuclear periphery` given available evidence, but that's minor; `nuclear periphery` clearly isn't wrong.

I have a question about including `for replication fork processing` as suggested in the term name. If I understand correctly, some of the fork processing steps precede the move to the NPC, i.e. part, not all, of the fork processing process takes place at the NPC. Is there any risk that, by saying '*for* replication fork processing', we would be implying or suggesting that the entire process happens at the NPC? (I also noticed that very few term names use 'for', and it doesn't seem to have a precisely defined meaning where it is used.)

Would it suffice instead to call the term `stalled replication fork localization to nuclear periphery`? Forks that have not stalled don't relocate to the nuclear periphery, as far as I can tell.

**Comment by krchristie** [comment]
I get your point about the word "for". We could also use the phrase "involved in" instead, which would produce this:
`replication fork localization to nuclear periphery involved in replication fork processing`.

I like your suggestion of `stalled replication fork localization to nuclear periphery` too. 

We could combine them to get `stalled replication fork localization to nuclear periphery involved in replication fork processing`, though I get that this name is more cumbersome and maybe not necessary unless we become aware of another type of replication fork localization to the nuclear periphery. 

What's your preference @mah11 ?

**Comment by mah11** [comment]
Well, I still like `stalled replication fork localization to nuclear periphery` best for its simplicity, but if there's a good reason to keep the `replication fork processing` portion in the name, then I could get used to either of the other suggestions, especially if plenty of synonyms are included.

**Comment by krchristie** [comment]
@mah11 - I'll go with the simpler name, and put some of my longer names in as synonyms. I'd like to make it clear that this process is part_of replication fork processing in as many ways as possible in case some other type of "replication fork localization to nuclear periphery" is discovered. But in the absence of knowledge, I'll go with the simpler name. I do really like the addition of "stalled" in the simpler name.

**Comment by mah11** [comment]
>  I'd like to make it clear that this process is part_of replication fork processing in as many ways as possible in case some other type of "replication fork localization to nuclear periphery" is discovered.

I don't know of any, but if/when some are discovered, we can rename terms then. Thanks!
