### ISSUE TITLE
merge? two terms related to proteasome storage granule assembly or sequestration

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#20458]
These two terms look like they are meant to cover the same thing

[Term]
id: GO:1902906
name: proteasome storage granule assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of a set of components to form a proteasome storage granule." [GO_REF:0000079, GOC:di, GOC:TermGenie, PMID:23690178]
synonym: "proteasome storage granule formation" EXACT [GOC:TermGenie]
synonym: "PSG assembly" RELATED [GOC:TermGenie]
synonym: "PSG formation" RELATED [GOC:TermGenie]
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: results_in_assembly_of GO:0034515 ! proteasome storage granule
created_by: di
creation_date: 2014-04-16T01:59:41Z

[Term]
id: GO:1990237
name: sequestration of proteasome core complex in proteasome storage granule
namespace: biological_process
def: "Any process where the proteasome core particle (CP) is sequestered in the protein storage granule in the cytoplasm." [GOC:rb, PMID:23982732]
intersection_of: GO:0098544 ! maintenance of protein complex location
intersection_of: occurs_in GO:0034515 ! proteasome storage granule
intersection_of: transports_or_maintains_localization_of GO:0005839 ! proteasome core complex
created_by: rb
creation_date: 2013-11-14T23:29:41Z

**Comment by krchristie** [comment]
Looking more closely, I see that the older term is specific to the proteasome core complex (CP). As it does not use the acronym PSG anywhere within the term stanza, it might have been hard to identify when the newer term was created.

id: Karmon O, Ben Aroya S. Spatial Organization of Proteasome Aggregates in the Regulation of Proteasome Homeostasis. Front Mol Biosci. 2020 Jan 9;6:150. doi: 10.3389/fmolb.2019.00150. PMID: 31998748; PMCID: PMC6962763.
 def: "Any process where the proteasome **_core particle (CP)_** is sequestered in the protein storage granule in the cytoplasm." [GOC:rb, PMID:23982732]
creation_date: 2013-11-14

There aren't very many annotations. All of the experimental ones were made by SGD:

Contributor | Gene name | GO term | Evidence | Panther | Reference | Date
-- | -- | -- | -- | -- | -- | --
SGD | RPN11 - Metalloprotease subunit of 19S regulatory particle | proteasome storage granule assembly (GO:1902906) | IMP | PANTHER:PTHR10410 | PMID:23936414 | 20150123
SGD | VMA2 - Subunit B of V1 peripheral membrane domain of vacuolar H+-ATPase | proteasome storage granule assembly (GO:1902906) | IMP | PANTHER:PTHR43389 | PMID:23690178 | 20140426
SGD | PMA1 - Plasma membrane P2-type H+-ATPase | proteasome storage granule assembly (GO:1902906) | IMP | PANTHER:PTHR42861 | PMID:23690178 | 20140426
SGD | BLM10 - Proteasome activator | sequestration of proteasome core complex in proteasome storage granule   (GO:1990237) | IMP | PANTHER:PTHR32170 | PMID:23982732 | 20140116

Here's a quote from a very recent review: Karmon O, Ben Aroya S. **Spatial Organization of Proteasome Aggregates in the Regulation of Proteasome Homeostasis.** Front Mol Biosci. 2020 Jan 9;6:150. doi: 10.3389/fmolb.2019.00150. PMID:31998748

> Proteasome homeostasis during carbon deprivation. Upon glucose starvation, intracellular ATP levels and pH decrease. This triggers the dissociation of the proteasome holo-complex to CP and RP subcomplexes, migration to the nuclear periphery and a stepwise export from the nucleus to the cytoplasm to form PSGs, membrane-less assemblies of soluble proteins. **The first step in the CP and RP cytoplasmic delivery is mediated by Blm10 and Spg5, respectively.** This step results in transient association of proteasomes with the IPOD, together with other IPOD proteins, such as Hsp42, to form inclusions termed early PSGs. While mutated inactive proteasomes are retained in these inclusions, the functional CP and RP particles are targeted to form the mature PSGs, which protects functional proteasomes from autophagy. Mature PSG assembly requires the proteasome associated protease, Ubp6, to release free ubiquitin from branched ubiquitin chains on nuclear proteasomes, resulting in a compact granule containing RP, Blm10-CP, and free ubiquitin moieties. This process is reversible; when glucose again becomes available, PSGs disperse, allowing cells to quickly re-enter the cell cycle without waiting for new de novo proteasome assembly.

It looks to me like the more specific term is very specific to the role of BLM10, and thus perhaps an overly specific term. So, after a closer look at these two terms,  I definitely recommend merging these two terms, in this direction:

merge **sequestration of proteasome core complex in proteasome storage granule (GO:1990237)**
into => **proteasome storage granule assembly (GO:1902906)**

SGD people: @srengel @robnash - any objections? does this merge sound OK to you?

**Comment by srengel** [comment]
sounds good to me.  no objections.  thanks @krchristie .
