### ISSUE TITLE
update GO:0102136

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#20466]
It seems EC have changed opinion on this activity, it is now under 1.14.14, see also https://www.rhea-db.org/rhea/27321
Could you please update definition reference, xrefs, and parentage of this entry? Also, in the reaction the electron acceptor changed to NADPH--hemoprotein reductase.
```
id: GO:0102136
name: 3-epi-6-deoxocathasterone C-23 hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + 3-epi-6-deoxocathasterone + NADPH + O2 <=>
 6-deoxotyphasterol + NADP + H2O." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-11531
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorp
oration or reduction of molecular oxygen, NAD(P)H as one donor, and incorporatio
n of one atom of oxygen
```

**Comment by hdrabkin** [comment]
Also need to remove 3 digit EC from this leaf node anyways. May need RHEA request here.

**Comment by pgaudet** [comment]
What is the evidence for this reaction ? There are no pubmeds and only a link to a 3 digit EC.

**Comment by pgaudet** [comment]
I guess we can take from https://www.uniprot.org/uniprot/Q94IA6

**Comment by hdrabkin** [comment]
PMID: 17138693 from MetaCyc info for CYP90D1
RHEA Ticket submitted:   [help #198719] i

**Comment by rwst** [comment]
Out of curiosity, what's a Rhea ticket?

**Comment by hdrabkin** [comment]
@rwst, we use RHEA where possible to request a RHEA id to define the reaction. They specifiy specific chemicals as substrates .
I note however, now, from the UniProt ling for CYP90D1 (Q94IA6) that a RHEA has been assigned for the EC:1.14.14.147, which I can use for this so will now cancel the new rhea request.
THis is RHEA:27321

**Comment by rwst** [comment]
Yeah, I gave that rhea link in my original issue submission.

**Comment by hdrabkin** [comment]
done closed
