### ISSUE TITLE
Problems with fatty acid ligase terms 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20462]
Working on #18967 I noticed: 

- GO:0015645 fatty acid ligase activity is defined as 'Catalysis of the ligation of a fatty acid to an acceptor, coupled to the hydrolysis of ATP.' but is linked to EC:6.2.1.3, 'Long-chain-fatty-acid--CoA ligase. ' > will change xref to EC:6.2.1

- GO:0003996 acyl-CoA ligase activity is defined as 'Catalysis of the reaction: ATP + a **long-chain** carboxylic acid + CoA = AMP + diphosphate + an acyl-CoA; long-chain carboxylic acids have chain lengths of C13 to C22.'  and is linked to EC:6.2.1.3, Long-chain-fatty-acid--CoA ligase, which has 'Acyl-CoA synthetase.' as a syonyms
- has 3 EXP, all long chain FA ligases -> will merge into GO:0004467 long-chain fatty acid-CoA ligase activity

**Comment by deustp01** [comment]
@hdrabkin Two naive questions. First, GO: is the introduction of a 3-digit EC here compatible with the EC - Rhea - GO mapping / clean-up project? Second, intro biochemistry: the major textbook reaction here in mammals involves long-chain fatty acids, true, but are there cases when medium- and short-chain FAs can react in this way?

**Comment by alanbridge** [comment]
Hi Peter, 

there are cases when medium and short chain FAs react like this, as in the reactions catalyzed by ACSM1 in mitochondria (which acts on C4 to C16 FAs): https://uniprot.org/uniprot/Q08AH1

C4 - https://www.rhea-db.org/rhea/46172
C6 - https://www.rhea-db.org/rhea/43740
C8 - https://www.rhea-db.org/rhea/33631
C10 - https://www.rhea-db.org/rhea/33627
C12 - https://www.rhea-db.org/rhea/33623
C14 - https://www.rhea-db.org/rhea/33619
C16 - https://www.rhea-db.org/rhea/30751

All the best, Alan

**Comment by hdrabkin** [comment]
3 digit EC were to be used only for the grouping terms, not for leaf nodes.
GO:0015645; is not broad enough for EC:6.2.1, which encompase all
Ligases
      Forming carbon-sulfur bonds
      Acid--thiol ligases

**Comment by pgaudet** [comment]
@hdrabkin Which term are you referring to that would be a leaf with 3 digit EC ? 

> GO:0015645 fatty acid ligase activity 3 digit EC:6.2.1

is already a grouping term 

Also, you write: 

> GO:0015645; is not broad enough for EC:6.2.1, which encompase all
Ligases
Forming carbon-sulfur bonds
Acid--thiol ligases

Should I remove the EC xref ? 

Specific suggestions would be appreciated ! 

Thanks, Pascale

**Comment by hdrabkin** [comment]
If you look at all of the rections under 6.2.1., tI don't think they are all https://enzyme.expasy.org/EC/6.2.1.-
So yes it groups all fattyy acid ligases, but 6.2.2 is broader than that. @deustp01  do you agree?

**Comment by hdrabkin** [comment]
So I think the 3 digit ec should be removed in this case.

**Comment by deustp01** [comment]
EC 6.2.1 looks like it covers all reactions R-COOH + CoA-SH -> RC(O)-S-CoA, where R can be several things in addition to a fatty acid, e.g., benzoate (EC 6.2.1.25). Also, spot checking, while the textbook has this reaction consuming ATP as an additional input and generating AMP + diphosphate as additional outputs, EC 6.2.1.18 Citrate--CoA ligase produces ADP and monophosphate as additional outputs.

**Comment by pgaudet** [comment]
The EC has been removed from 'GO:0015645 fatty acid ligase activity'
