### ISSUE TITLE
Immunoglobulin maturation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#20465]
Hi Pascale

sorry about this, but wondering if immunoglobulin maturation term is required as it is not possible to include an immunoglobulin UniProt ID.

see https://pubmed.ncbi.nlm.nih.gov/12438318/ Initiation of O-glycan synthesis in IgA1 hinge region is determined by a single enzyme, UDP-N-acetyl-alpha-D-galactosamine:polypeptide N-acetylgalactosaminyltransferase 2. I guess this is not great if only one enzyme involved

Please close the ticket if you think there is no need for this, ie I should just create:
Q10471 GALNT2  GO:0051604 protein maturation part of GO:0002377 immunoglobulin production

Thanks
Ruth

**Comment by pgaudet** [comment]
Good point ! Are PRO Ids allowed ? 

https://www.ebi.ac.uk/ols/ontologies/pr/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPR_000050032

Otherwise we can create the term. That may be preferable to using terms from different vocabularies/resources.

**Comment by RLovering** [comment]
yes - perfect thanks for the advice

**Comment by deustp01** [comment]
GO logic quibble: the immunoglobulin proteins are substrates here, not gene product enablers, so is the lack of useful UniProt identifiers for them an obstacle to creating a terms with a proper definition?

**Comment by pgaudet** [comment]
The suggestion was to use an 'has input' extension, so we wanted an identifier.

**Comment by deustp01** [comment]
True. And immunoglobulin heavy chains are not gene products. Naive question about the process: is it truly restricted to act only on immunoglobulin heavy chains or would any polypeptide with the appropriate sequence motif undergo the particular type of O-glycosylation that occurs here? If the latter, then would it be acceptable to have a generic protein, e.g., from ChEBI, as input with a sentence in the definition to the effect that under physiological conditions the target of this activity is immunoglobulin heavy chains. And maybe also a taxon constraint?

**Comment by pgaudet** [comment]
@deustp01 I am not following - 

1. The term is 'protein maturation' - I dont think we can put an taxon restriction on this ? 

2. Are you suggesting we add 'has input' some protein on 'protein maturation' ? 

Thanks, Pascale

**Comment by deustp01** [comment]
True again. "protein maturation" cannot have a taxon restriction. I was thinking about a hypothetical "immunoglobulin maturation" child term. Sorry for the confusion.

**Comment by pgaudet** [comment]
Ah you mean, creating that term would have the advantage of allowing to have taxon restrictions ?

**Comment by deustp01** [comment]
Yes, right. But now I'm hesitating - would an immunoglobulin-maturation term come to close to a term that covers only a specific protein family? Would it be better instead to handle it as a GO-CAM annotation with a term like  GO:0016266 O-glycan processing or its parent  GO:0006493 protein O-linked glycosylation with attributes to indicate the enzyme enabler and the inout protein target of the process (which brings in a species by reference)?
