### ISSUE TITLE
formation of host infection structure synonym

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20472]
formation of host infection structure
please add a synonym
formation of host penetration structure, as per
https://github.com/PHI-base/phipo/issues/285

**Comment by pgaudet** [comment]
Added as RELATED synonym. 

Also changed existing synonyms from EXACT to RELATED: 
- formation by symbiont of infection structure on or near host
- formation of infection structure on or near host

Thanks, Pascale
