### ISSUE TITLE
change taxon constraint GO:0101024

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#20478]
GO:0101024 `mitotic nuclear membrane organization` has the taxon constraint `only in metazoa`. It should be changed to `only in Eukaryota`.

There was a lot of back-and-forth in #19950, and I think there was an error in the last comment that meant the taxon constraint didn't get the correct update to match merges and other work on this bit of the ontology.

**Comment by pgaudet** [comment]
Actually in #19950 we had changed 
GO:0101024 | 'nuclear membrane organization involved in mitotic nuclear division' to 'mitotic nuclear membrane organization' 

Changed both taxon constraints

GO:0101024	mitotic nuclear membrane organization NCBITaxon:2759	Eukaryota
GO:0101026	nuclear membrane biogenesis involved in mitotic nuclear division	NCBITaxon:2759	Eukaryota

+ renamed 'GO:0101026	nuclear membrane biogenesis involved in mitotic nuclear division' -> mitotic nuclear membrane biogenesis

Thanks, Pascale
