### ISSUE TITLE
Widen def for GO:0019933 cAMP-mediated signaling or new terms

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#20487]
The current def doesn't include how Dicty uses cAMP-mediated signaling, and we use this term.

"Any intracellular signal transduction in which the signal is passed on within the cell via cyclic AMP (cAMP). Includes production of cAMP, and downstream effectors that further transmit the signal within the cell. "

Context: In Dicty, the cAMP signaling is between cells when they start the development process, and even later in development. Dicty cells, when they starve produce and secrete cAMP. Other cells receive the signal, and then also start producing and secreting cAMP. Since the cells go through a refractory period when they are insensitive and also though produced Phosphodiesterase that breaks down the cAMP, in dark field you see cAMP waves.

I think the def should be complete changed

A suggestion:
Any intra- or extracellular signal transduction in which the signal is passed on via cyclic AMP (cAMP). Including production of cAMP, and downstream effectors that further transmit the signal within or between cells.

Thanks

**Comment by pgaudet** [comment]
Hi @pfey03 

We had discussed this for the GPCR work, see slide 32 here: 
https://docs.google.com/presentation/d/1xR6EFbRyCSwruXVeMYZtJfwWEbIr6U8zei8IwGG3OrA/edit#slide=id.g26be66c50c_0_86

I think we need to distinguish the extracellular with a different term, it's not the same pathway - what do you think ? 

Thanks, Pascale

**Comment by pfey03** [comment]
@pgaudet many thanks for the reminder, it's been a long time ago. In general I'm open to distinguish the extra- and intracellular pathways.

It's a mess as we have so many annotations and also phenotypes. The suggested term in the slide 'cAMP receptor signaling pathway' does not yet exist. Should this finally be created for the extracellular pathway?

Also, a related Q, you will at least understand:
You know that cAMP signaling in Dicty is in 6 min waves, so researchers often talk about cAMP waves. Car1 stimulates intracellular cAMP, through PI3K, activating ACA. Cells eventually become saturated/insensitive. Then extracellular PDE breaks down cAMP and they become sensitive again. A signal relay mechanism. Very good to see in dark field microscopy. Is it worth expressing this specifically? 'cAMP wave formation', or 'cAMP signal relay organization'? 
As a child of 'cAMP receptor signaling pathway'

Since I'm also updating phenotypes a lot for the UPHENO project, I'd like to get this cleaned up. 

Thanks for your help with this.
Petra

**Comment by pfey03** [comment]
@pgaudet I'd like yo move this ahead. How about

Add New: 'cAMP receptor signaling pathway'
is_a GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway
"An extracellular signal transduction with cyclic AMP (cAMP) produced by a cell and then accepted by extracellular cAMP receptors on other cells, where the signal is transmitted to downstream effectors within the cell.

And maybe also  a child of 'cAMP receptor signaling pathway'
New 'cAMP signal relay'
"Cells produce cAMP and receive the cAMP signal  to produce more cAMP, alternating between cAMP sensitive and insensitive stages, resulting in CAMP relays and visible cAMP waves. An example occurs in Dictyostelium"

I can also add paper refs if we move forward with this. THANKS!!

**Comment by ValWood** [comment]
this will seem a bit odd:

GO:0019933    cAMP-mediated signaling
-- GO:0007189   adenylate cyclase-activating G protein-coupled receptor signaling pathway
----GO:NEW cAMP receptor signaling pathway

**Comment by pfey03** [comment]
cAMP mediated signaling will not be the parent. It should be a separate branch, see the top. Intra and Extracellular cAMP signaling should be separate

**Comment by pgaudet** [comment]
I think the term should be a child of 'GO:0007186  G protein-coupled receptor signaling pathway', similar to 'GO:0007216  G protein-coupled glutamate receptor signaling pathway': 
- the term label could be G protein-coupled cAMP receptor signaling pathway'
- definition: A series of molecular signals initiated by cAMP binding to its receptor on the surface of the target cell, and proceeding with the activated receptor promoting the exchange of GDP for GTP on the alpha-subunit of an associated heterotrimeric G-protein complex. 
- with some comments about possibly ambiguity with the cAMP signaling term

Would that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I see.  Yes. Could this be made clearer by describing the signalling pathway as inter-cellular in the term name?

**Comment by pgaudet** [comment]
You suggest GO:0019933 cAMP-mediated signaling -> intracellular cAMP-mediated signaling? Does that not complicate the label, since this is the most common case and the Dicty extracellular cAMP signaling is the exception?

**Comment by pfey03** [comment]
Val said INTER-Cellular, but I also prefer extracellular.

@pgaudet Yes, that term, it's long but would work for Dicty. As cAMP receptor is in the term and the def is very explicit.

**Comment by ValWood** [comment]
I meant for  GO:NEW cAMP receptor signaling pathway
I just thought this might confuse people. Using a loose definition of receptor anything which binds to cAMP is a cAMP receptor (in fact PKA regulatory subunit could be described as an intracellular cAMP receptor), and there are many intracellular receptors in pathogen host interactions.

I envisage future problems if it isn't clear in the term name.

**Comment by ValWood** [comment]
OK @pfey03 got it.

What about "extracellular cAMP signaling pathway"
or "cAMP extracellular signaling pathway"
Avoiding receptor.

**Comment by pgaudet** [comment]
> extracellular cAMP signaling pathway"
or "cAMP extracellular signaling pathway" 

But  the signaling pathway is not extracellular

Same for other formulations: 

* 'extracellular G protein-coupled cAMP receptor signaling pathway'? but the signaling pathway is not extracellular
* 'G protein-coupled extracellular cAMP receptor signaling pathway' but the cAMP receptor is not extracellular

Meanwhile, I created this term: 

+[Term]
+id: GO:0140582
+name: G protein-coupled cAMP receptor signaling pathway
+namespace: molecular_function
+def: "A series of molecular signals initiated by cAMP binding to its receptor on the surface of the target cell, and proceeding with the activated receptor promoting the exchange of GDP for GTP on the alpha-subunit of an associated heterotrimeric G-protein complex." [PMID:9578623]
+is_a: GO:0007186 ! G protein-coupled receptor signaling pathway
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20487 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-18T19:30:30Z

Does that work ?

**Comment by ValWood** [comment]
Yes ignore my concerns. It will be fine if people read the definitions ;)

Could also add "never in fungi" (as far as we know currently!)

**Comment by pfey03** [comment]
Thanks @pgaudet and yes add exclusions where the def would not be true. I need to re-annotate the few that we annotated to cAMP-mediated signaling without reading the def once the term is available.

**Comment by pfey03** [comment]
@pgaudet 
Looking at annotations that I'll need to update, I noticed a direct child also annotated:
**GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway**
Def: _The series of molecular signals generated as a consequence of a G protein-coupled receptor binding to its physiological ligand, where the pathway proceeds through activation of adenylyl cyclase activity and a subsequent increase in the concentration of cyclic AMP (cAMP)._
Is_a
**GO:0019933 cAMP-mediated signaling**

GO:0007189 fits what happens in Dicty well and the Def doesn't violate what's in Dicty. Just true path rule is violated. Maybe this term should be moved?

----
There are also two PAINT annotations:

UniProtKB | P54654 | cap | involved_in | GO:0019933 | cAMP-mediated signaling | ECO:0000318 | IBA | PMID:21873635 | CGD:CAL0000183073\|PANTHER:PTN000068843\|PomBase:SPCC306.09c | 44689 | GO_Central |   | P

UniProtKB | Q03100 | acaA | involved_in | GO:0007189 | adenylate cyclase-activating G protein-coupled receptor signaling pathway | ECO:0000318 | IBA | PMID:21873635 | MGI:MGI:108450\|MGI:MGI:87917\|MGI:MGI:99673\|MGI:MGI:99675\|PANTHER:PTN002899368\|RGD:2036\|RGD:619965\|RGD:619966\|RGD:71014\|UniProtKB:O43306\|UniProtKB:O60503\|UniProtKB:O95622\|UniProtKB:P19754\|dictyBase:DDB_G0281545 | 44689 | GO_Central |   | P

**Comment by ValWood** [comment]
We use the term 

GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway
for CAMP mediated signalling pathway in pombe.

This was an outcome of the work surrounding the signalling meeting in Cambridge when it was 
decided that all 
GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway
was CAMP-mediated signalling.

I think this is correct.

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/13949
and
https://github.com/geneontology/go-ontology/issues/13903

**Comment by pfey03** [comment]
maybe this term then needs to be child of both branches?
as above from @ValWood 

a child of the new:
G protein-coupled cAMP receptor signaling pathway

**Comment by pgaudet** [comment]
@pfey03 
How about if the new term was : 

adenylate cyclase-activating G protein-coupled receptor cAMP receptor signaling pathway? 
or maybe easier to read: 
G protein-coupled receptor cAMP receptor signaling pathway, adenylate cyclase-activating?

**Comment by pgaudet** [comment]
I removed the relation: 

GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway
Is_a
GO:0019933 cAMP-mediated signaling

It's now only under 'second messenger-mediated signaling'
<img width="369" alt="image" src="https://user-images.githubusercontent.com/4782928/105002198-2d9b9380-5a31-11eb-81ec-82c0cf056463.png">
 and here's the tree for the new term 'adenylate cyclase-activating G protein-coupled receptor cAMP receptor signaling pathway'

<img width="642" alt="image" src="https://user-images.githubusercontent.com/4782928/105002284-499f3500-5a31-11eb-825d-6aeaa54ed4f8.png">

Does this now seem accurate ?

**Comment by pgaudet** [comment]
Note that 
'adenylate cyclase-modulating G protein-coupled receptor signaling pathway' 'has part' some 'cAMP-mediated signaling' 
(and 'has part' some 'regulation of cAMP-mediated signaling' - which seem inconsistent)

**Comment by pgaudet** [comment]
@pfey03 

I think the PAINT annotations are not great but OK ?

**Comment by pgaudet** [comment]
I will also add a taxon constraint on the new term 
GO:0140582 adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
only in NCBITaxon:33083 | Dictyostelids

**Comment by ValWood** [comment]
but isn't

'adenylate cyclase-modulating G protein-coupled receptor signaling pathway
always "cAMP mediated signalling pathway"?  ...it's just 2 names for the same pathway really?

With this merge our "cAMP-mediated signalling pathway will no longer be annotated to the term "cAMP-mediated signalling". We spent a lot of time  making sure this pathway is correctly annotated during the signalling meeting and since.
 see the "cAMP mediated signalling pathway" here:https://github.com/pombase/curation/issues/1699


@Antonialock

**Comment by pgaudet** [comment]
> 'adenylate cyclase-modulating G protein-coupled receptor signaling pathway
always "cAMP mediated signalling pathway"? ...it's just 2 names for the same pathway really?

I agree. I'll create a new ticket (I cannot find any existing one)

**Comment by ValWood** [comment]
I see that in the def of 
GO:0019933    cAMP-mediated signaling 
is

Definition | Parents
-- | --
Any intracellular signal transduction in which the signal is passed on within the cell via cyclic AMP (cAMP). Includes production of cAMP, and downstream effectors that further transmit the signal within the cell.

I assumed the production of camp includes receptor to adenylate cyclase?



So now we would need to annotate to both 

'adenylate cyclase-modulating G protein-coupled receptor signaling pathway
and
cAMP-mediated signalling"

So we are back to the problem of multiple orthogonal ways to describe the same pathway (the pathway is also commonly called "glucose-mediated signalling".)

Maybe cAMP mediated signalling is broader? (anything that operated "via" cAMP
https://jcs.biologists.org/content/114/11/1971

 I think we are tying ourselves in knots trying to annotated to signalling pathway terms. We need a different solution!

**Comment by pgaudet** [comment]
> I think we are tying ourselves in knots trying to annotated to signalling pathway terms. We need a different solution!

I agree. Please move the discussion to https://github.com/geneontology/go-ontology/issues/20712

**Comment by ValWood** [comment]
OK, but I don't think you can make the existing "cAMP-mediated signalling" a has_part of GO:0007189 because the annotations don't fit...

**Comment by pgaudet** [comment]
OK, right now there is no connection between 

GO:0019933 cAMP-mediated signalling and 
GO:0007189 adenylate cyclase-activating G protein-coupled receptor signaling pathway

**Comment by pfey03** [comment]
@pascale, it was a lot to read up this morning. The only qualms I have is that I don't like these very long terms and 
"adenylate cyclase-activating G protein-coupled receptor cAMP receptor signaling pathway" is such a term. Although of course it fits Dicty. Is this  GO:0140582?  Need to spend more time with this but trust you do the right thing.
