### ISSUE TITLE
MF in BP recruitment of ...

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20484]
This term is very confusing in the BP ontology - it's describing 'recruitment' (i.e. some sort of adaptor)
  
GO:0034402 | recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex | IBA with S000004410 , PTN000279609

**Comment by ValWood** [comment]
Also, gthee child term, is a little GO-CAM
GO:1901921    phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex

5 annotations in total

**Comment by pgaudet** [comment]
Obsolete 
GO:0034402 recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex
and  GO:1901921 phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex 

5 EXP SGD

**Comment by pgaudet** [comment]
This is part of #24731 19105
