### ISSUE TITLE
Simplify labels for some transferases ?

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20486]
Hello, 

Some transferases have 'user friendly' labels, such as 

GO:0042123 glucanosyltransferase activity
GO:0000031 mannosylphosphate transferase activity
GO:0042285 xylosyltransferase activity

We could simply those : 

GO:0016746 transferase activity, transferring acyl groups
=> acyltransferase

GO:0016757 transferase activity, transferring glycosyl groups
=> glycosyltransferase
~Same as GO:0046527 glucosyltransferase activity ?~ 

GO:0016769 transferase activity, transferring nitrogenous groups
=> transaminase activity

GO:0016741 transferase activity, transferring one-carbon groups
=> ~methyltransferase activity~

GO:0016772 transferase activity, transferring phosphorus-containing groups
=> kinase activity (merge into GO:0016301 kinase activity) 

GO:0016785 transferase activity, transferring selenium-containing groups
=> selenotransferase activity

GO:0016782 transferase activity, transferring sulfur-containing groups 
=> sulfurtransferase activity

GO:0016744 transferase activity, transferring aldehyde or ketonic groups
= > cannot change ? unless we split into individual substrates

GO:0016765 transferase activity, transferring alkyl or aryl (other than methyl) groups
= > cannot change ? unless we split into individual substrates

Would this be OK @hdrabkin @deustp01  @cmungall ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
I see no reason to do this as I have no problem with the current names; these are grouping terms that usually map to 3 digit (or less) ec ids, and the current names are more in line with what EC calls the groupings.

**Comment by ValWood** [comment]
I like the simpler more user friendly labels.

**Comment by ValWood** [comment]
although some of these are not possible
GO:0016741 transferase activity, transferring one-carbon groups
->methyltransferase activity

methyltransferase is narrower, there are other transferases.  So maybe not?

**Comment by hdrabkin** [comment]
IF we do this (again I think it is not needed), the old names must be synonyms. I often use these types of definitions to verifiy the 3 digit ec id (or add if needed).

**Comment by cmungall** [comment]
I agree with having the simpler names be primary, where unambiguous

of course we retain the syns. We can use systematic_synonym type

**Comment by pgaudet** [comment]
- [x] GO:0016755 ! transferase activity, transferring amino-acyl groups
-> change to aminoacyltransferase activity (same as https://enzyme.expasy.org/EC/2.3.2.-) 

- [x] GO:0016755 ! transferase activity, transferring amino-acyl groups
-> change to aminoacyltransferase activity (same as https://enzyme.expasy.org/EC/2.3.-.-) 


- [x] GO:0016747 ! transferase activity, transferring acyl groups other than amino-acyl groups
-> change to  ! acyltransferase activity, transferring groups other than amino-acyl groups  (same as https://enzyme.expasy.org/EC/2.3.1.-)

**Comment by pgaudet** [comment]
GO:0002948 archaeosine synthase activity
EC:2.6.1.97
 xref: RHEA:54084
changed parent from 
-is_a: GO:0015067 ! amidinotransferase activity
+is_a: GO:0016769 ! transferase activity, transferring nitrogenous groups

**Comment by pgaudet** [comment]
GO:0030407 formimidoyltransferase activity 
- has 2 EC: EC:2.1.2.4 and EC:2.1.2.5, which corresponds to its 2 children
- has 1 EXP, to an enzyme annotated in UniProt with EC:2.1.2.5 , which corresponds to the child, GO:0030409 glutamate formimidoyltransferase activity 
--> Merge down  GO:0030407 into GO:0030409

**Comment by pgaudet** [comment]
Merge 
GO:0016770 oximinotransaminase activity linked to EC:2.6.3.-, into its single child
 GO:0050206 oximinotransferase activity linked to 2.6.3.1
(no annotations)

**Comment by pgaudet** [comment]
**GO:0102192 neryl-diphosphate:isopentenyl-diphosphate cistransferase activity** (xref: EC 2.5.1.92 (2Z,6Z)-farnesyl diphosphate synthase; no RHEA) 
Def: Catalysis of the reaction: **neryl diphosphate(3-)** + isopentenyl diphosphate(3-) <=> diphosphoric acid + 2-cis,6-cis-farnesyl diphosphate(3-).
is identical to **GO:0102059 2-cis,6-cis-farnesyl pyrophosphate synthase activity** (RHEA:27810)  - also EC 2.5.1.92
Def: Catalysis of the reaction: **prenyl diphosphate** + 2 isopentenyl diphosphate <=> 2 diphosphoric acid + 2-cis,6-cis-farnesyl diphosphate.

CHEBI:57623 prenyl diphosphate(3−)
has synonyms: 

dimethylallyl diphosphate | UniProt
dimethylallyl pyrophosphate | ChEBI
Dimethylallyl pyrophosphate trianion | ChEBI
prenyl diphosphate trianion | ChEBI
prenyl pyrophosphate trianion
