### ISSUE TITLE
actin cortical patch internalization (GO:0044397)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20490]
actin cortical patch internalization (GO:0044397)

is just an endocytosis phenotype
PomBase has 2 annotations

SPAC4F10.15c | wsp1 | WASp homolog
SPBC24C6.10c | dip1 | WISH/DIP/SPIN90 ortholog, endocytosis protein Dip1

please merge into endocytosis

(also raises questions about "actin cortical patch assembly/localization/organization" for another day)

**Comment by pgaudet** [comment]
I'll obsolete with 'REPLACED BY'

**Comment by ValWood** [comment]
We should check this with @srengel @edwong57

**Comment by edwong57** [comment]
@ValWood @pgaudet, SGD doesn't have any annotations to this term.

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete 'GO:0044397 actin cortical patch internalization'. The reason for obsoletion is that this represents a phenotype resulting from endocytosis defects. The term will have a 'REPLACED_BY GO:0006897 endocytosis' tag. There are 2 EXP annotations by PomBase; there are no mappings; the term is not present in any subsets.

You can comment on the ticket: geneontology/go-ontology#20490

Thanks, Pascale
