### ISSUE TITLE
Update definition ATPase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20498]
From the ontology call, and the discussion on compound functions: 

We want all ATPases to have an is_a path to ATPase activity. 
To this end, we will change the definition of ATPase activity to "A molecular function that uses ATP hydrolysis as an energy source." (source: pdt). 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note also that the EC:3.6.1.3   has been deleted. 

@kaxelsen @amorgat Is there an EC/RHEA we should use in replacement ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
ATPases are now split into: 

* https://enzyme.expasy.org/EC/3.6.-.-  Hydrolases acting on acid anhydrides, which includes:
* *  3.6.1.8      ATP diphosphatase.  (AN: ATP pyrophosphatase.  ATPase.)
* *  3.6.4.6      Vesicle-fusing ATPase. 
* *  3.6.4.7      Peroxisome-assembly ATPase. 
* *  3.6.4.10     Non-chaperonin molecular chaperone ATPase. 
and
* https://enzyme.expasy.org/EC/5.6.-.- : Isomerases altering macromolecular conformation
* *  5.6.1.1      Microtubule-severing ATPase
* *  5.6.1.2      Dynein ATPase
* *  5.6.1.3      Plus-end-directed kinesin ATPase
* *  5.6.1.4      Minus-end-directed kinesin ATPase
* *  5.6.1.5      Proteasome ATPase
* *  5.6.1.6      Channel-conductance-controlling ATPase
* *  5.6.1.7      Chaperonin ATPase
* *  5.6.1.8      Myosin ATPase
* *  5.6.1.9      (R)-2-hydroxyacyl-CoA dehydratase activating ATPase
* *  5.6.2.1      DNA topoisomerase
* *  5.6.2.2      DNA topoisomerase (ATP-hydrolyzing)

**Comment by deustp01** [comment]
But none of these catagories apply to ABC transporters, which all have EC/7.# numbers (# = 2 or 3 or 4 or 5 or 6). FGrom the ontology discussion, don't we need to accommodate them also, or am I missing something here?

**Comment by kaxelsen** [comment]
> 
> 
> Note also that the EC:3.6.1.3 has been deleted.
> 
> @kaxelsen @amorgat Is there an EC/RHEA we should use in replacement ?
> 
> Thanks, Pascale

There is RHEA:13065

**Comment by ValWood** [comment]
There are many ATPases not here including:
DNA clamp loader activity 
DNA/RNA helices
DNA translocase activity (condensing cohesion)
ATP-dependent peptidases (lon,M41 and others)

presumably these are classified elsewhere in EC

**Comment by kaxelsen** [comment]
@ValWood, no the enzymes you mention are not currently part of the EC list. 
Not, that generally the EC list tries to to create a distinct reaction for each EC entry. So when the entries currently sporting the reaction "ATP + H(2)O = ADP + phosphate" (RHEA:13065) are updated, we try to add the result of hydrolysing ATP to the reaction, as can be seen in the new EC 5.6 entries. The RHEA:13065 reaction is not very informative in itself.

**Comment by pgaudet** [comment]
RHEA:13065 is ATPase activity then ? 
Is there an equivalent general EC ?

**Comment by kaxelsen** [comment]
As RHEA:13065 = "ATP + H(2)O = ADP + phosphate" it is the most basic ATPase activity. 
There is no corresponding EC number, as no enzyme hydrolyses ATP without using the generated energy to do something, and as mentioned above the EC list tries now to describe what the energy is used for in the reactions, e.g. EC 5.6.1.2, dynein ATPase, "ATP + H(2)O + a dynein associated with a microtubule at position (n) = ADP + phosphate + a dynein associated with a microtubule at position (n-1, toward the minus end)"

**Comment by ValWood** [comment]
Makes sense! Thanks @kaxelsen 

@pgaudet @cmungall @sjm41 @vanaukenk @thomaspd   this makes me think that really has_part ATPase with a procedure to infer  every  ATPase might have been a better solution, in retrospect? 

Especially since we need to be able to infer  annotations over has_part anyway for components etc.

**Comment by sjm41** [comment]
@hattrill

**Comment by ValWood** [comment]
Just playing devil's advocate. But are we sure about the dual parentage ????

**Comment by pgaudet** [comment]
> no enzyme hydrolyses ATP without using the generated energy to do something

To me the logical conclusion is that ATPase activity is not a function ;) 

In any event, it seems like there is a need to group /browse ATPases, and the only way we can support all tools doing that is with is_a (or part_of, but that doesn't work). 

Thanks, Pascale

**Comment by pgaudet** [comment]
Removed synonyms corresponding to gene products or merge terms

-synonym: "chaperonin" RELATED [EC:3.6.4.9]
-synonym: "chaperonin ATPase activity" RELATED []
-synonym: "complex V (mitochondrial electron transport)" NARROW [EC:3.6.1.3]
-synonym: "HCO3--ATPase" NARROW [EC:3.6.1.3]
-synonym: "non-chaperonin molecular chaperone ATPase activity" RELATED []
-synonym: "nucleoplasmin ATPase activity" RELATED []
-synonym: "peroxisome-assembly ATPase activity" RELATED []
-synonym: "SV40 T-antigen" RELATED [EC:3.6.1.3]
-synonym: "vesicle-fusing ATPase activity" RELATED [EC:3.6.4.6]
-synonym: "ATP phosphohydrolase (polypeptide-unfolding)" NARROW [EC:3.6.4.9]


Thanks, Pascale
