### ISSUE TITLE
IEA with 2.7.11.13 calcium dependent/independent protein kinase C

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20497]
P36582
GO:0004698 | calcium-dependent protein kinase C activity | IEA with 2.7.11.13

P36582 is

GO:0004699 | calcium-independent protein kinase C activity

not sure who to assign to?

**Comment by pgaudet** [comment]
We have 3 terms mapped to EC:2.7.11.13: 

'calcium-dependent protein kinase C activity' <http://purl.obolibrary.org/obo/GO_0004698>
'calcium-independent protein kinase C activity' <http://purl.obolibrary.org/obo/GO_0004699>
'protein kinase C activity' <http://purl.obolibrary.org/obo/GO_0004697>

While it seems desirable to align GO with external resources, I dont know if we want to merge all those terms together ?  

Interestingly P36582 has 2 only EC2GO mappings: 


UniProtKB:P36582 | pck1 | enables | GO:0004698                calcium-dependent protein kinase C activity | ECO:0000501              IEA | GO_REF:0000003 | EC:2.7.11.13 | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | UniProt |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:P36582 | pck1 | enables | GO:0004697                protein kinase C activity | ECO:0000501              IEA | GO_REF:0000003 | EC:2.7.11.13 | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | UniProt |  



The solution may be different types of xrefs, and not map 'BROAD' xrefs; however how can we do this without loosing all mappings ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think it's OK but UniProt need to remove 2.7.11.13 from P36582
Assign to @sylvainpoux ?

**Comment by sylvainpoux** [comment]
Hi Val,
we can modify the entry to remove the complete EC

Could you indicate which paper shows that pkc1 is calcium-independent? We could curate it

Thanks

Sylvain

**Comment by pgaudet** [comment]
2.7.11.13 is OK for this entry tough. 

I think what would be OK would be to keep the mapping in the parent GO:0004697 protein kinase C activity
and maybe consider merging 
- GO:0004698 calcium-dependent protein kinase C activity - 10 EXP
- GO:0004699 calcium-independent protein kinase C activity  - 3 EXP

That would also take care of the EC mapping.

**Comment by pgaudet** [comment]
The specific protein kinases activities represented in EC (and pretty much mirrored in GO) are anyway a strange selection: 

https://enzyme.expasy.org/EC/2.7.11.-

**Comment by ValWood** [comment]
From this paper
https://www.pombase.org/reference/PMID:8463273
based on assay and homology to mammalian calcium-independent PKC's

**Comment by ValWood** [comment]
It's old though.....maybe this is overturned and Ca is required physiologically?

**Comment by sylvainpoux** [comment]
Hi Val,

honestly, I am not really convinced by this paper. 

An option might be to leave the electronic annotation from 2.7.11.13 as it is and supply this annotation with experimental evidence with a NOT qualifier. I think it would be more relevant to say that it is predicted to be Calcium-dependent but that a previous paper showed that it is not the case.

Thanks

Sylvain

**Comment by pgaudet** [comment]
@sylvainpoux Do you agree that I merge 

- GO:0004698 calcium-dependent protein kinase C activity - 10 EXP
-  GO:0004699 calcium-independent protein kinase C activity - 3 EXP

into  GO:0004697 protein kinase C activity ? That would make the mapping correct. (Or I can remove the mapping to the specific children).

**Comment by sylvainpoux** [comment]
Hi Pascale,

I think it is something to discuss with Kristian (@kaxelsen) as it affects some EC to GO mapping

Thanks

Sylvain

**Comment by ValWood** [comment]
OK, I agree, when I looked again.  I had assumed that it was an accepted piece of information and a subset of pkc's were calcium independent. I don't think it does any harm to have both annotation in this case.
Unless the decision is not to have this specificity. I'm OK either way.

**Comment by kaxelsen** [comment]
I am not an expert on protein kinases. In the comment of the EC 2.7.11.13 entry (https://enzyme.expasy.org/EC/2.7.11.13) it reads: "They can be activated by calcium but have a requirement for the second messenger diacylglycerol." I understand that as saying that some are calcium-dependent others not.

**Comment by pgaudet** [comment]
@vanaukenk @ukemi From a GO-CAM perspective, are those 2 terms useful ? Or is the calcium-dependency expected to be be captured differently ?

**Comment by ValWood** [comment]
closing since 
calcium-independent protein kinase C activity
is now 
diacylglycerol-dependent, calcium-independent serine/threonine kinase activity
