### ISSUE TITLE
Sec61 translocon complex  (GO:0005784) superclass

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20491]
the definition of
endoplasmic reticulum Sec complex (GO:0031205)
An endoplasmic reticulum membrane-associated complex involved in the translocation of proteins that are targeted to the ER. In yeast, this complex consists of two subcomplexes, namely, the Sec61 complex and the Sec62/Sec63 complex.

implies that 

Sec61 translocon complex  (GO:0005784)
A translocon complex that contains a core heterotrimer of conserved alpha, beta and gamma subunits, and may contain additional proteins (translocon-associated proteins or TRAPs); in budding yeast the core proteins are Sec61p, Sbh1p, and Sss1p. The Sec61 translocon complex functions in cotranslational and posttranslational translocation events.

should be a descendant?

**Comment by mah11** [comment]
They are linked - GO:0031205 has_part GO:0005784. If the Sec61 complex can exist independently of the bigger complex -- and a quick look suggests it can, e.g. PMIDs 30545845, 30644436 -- that's correct.

**Comment by ValWood** [comment]
ah ok.
