### ISSUE TITLE
parts vs is_a parents

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#20501]
This is a follow-up to discussions we had on the 2020-11-30 ontology editors call.

Molecular functions can have different 'parts' or sub-functions, but it seems that sometimes these parts are is_a parents in the ontology and sometimes not.

For MFs like NTP-dependent molecular motors or NTP-dependent helicases (specifically I'm thinking of DEAD-box helicases), the gene products do enable an NTPase activity but NTP binding and protein or nucleic acid binding are critical parts of the overall function.

![image](https://user-images.githubusercontent.com/1730534/100676137-47283500-3336-11eb-8b2c-37e4db3e52cf.png)

From: https://pubmed.ncbi.nlm.nih.gov/19748356/

In this example of a DEAD-box helicase, could the ATP binding and dsRNA binding also legitimately be 'is a' parents for the RNA helicase MF?  

A possible GO-CAM representation of the DEAD-box helicase activity:

http://noctua.geneontology.org/editor/graph/gomodel:5fb9cc0600000424?model_id=gomodel:5fb9cc0600000424

**Comment by pgaudet** [comment]
I think (but I am not sure) that we were proposing to have all binding activities as 'has_part' of a more descriptive function; weren't we ?

**Comment by ValWood** [comment]
My understanding  (mainly from reading in between the lines, but this is what seems to be a consensus)

1. We aren't modelling 'conformations change' which is important for the activity but represents mechanistic detail below the resolution of GO MF
2. So, in the above example the activity would be a helicase?. This MF would have part ATP binding

so isn't this just 
helicase
Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the unwinding of a DNA or RNA helix.


3. I also thought the plan was for binding to be has_par of more descriptive functions.

When I was reviewing the tracker  last week I found a ticket where @thomaspd  confirmed this. I will see if I can locate it. and  I found another ticket where I asked the question.

**Comment by pgaudet** [comment]
@vanaukenk 
Can you say this is resolved with the decision to use 'is a' for ATPases'?

**Comment by pgaudet** [comment]
@thomaspd your input would be useful

**Comment by pgaudet** [comment]
Discussion on ontology jamboree
- @thomaspd Do you need to capture ATPase as evidence ? This seems 'obvious' information
- @krchristie feels is important to capture the where the data come from 
- @thomaspd for helicases, part of its activity is an ATPase
- talk about the suggestion we had previously, to have two versions of the ontology, one for function (helicase has_part ATPase), one for classification (ie a helicase is_an ATPase) - but we had decided on an ontology call a few weeks ago to make all functions using ATP is_a ATPase activity
-

**Comment by pgaudet** [comment]
May be solved with #20876 
- to be discussed again once we look at the PR

**Comment by hattrill** [comment]
tagging @sjm41

**Comment by pgaudet** [comment]
Hi @vanaukenk 

Now that we created the distinction between ATP hydrolysis activity and ATPase activity, can this close? 
#20876

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet - yes, I'll close it.  Thx.
