### ISSUE TITLE
Add is_a ATPase parent to all ATPases

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20500]
On today's ontology call we decided that proteins whose activity depend on the hydrolysis of ATP would be is_a ATPase. 

According to @sjm41 this is missing from the following terms: 

ATPase-coupled transmembrane transporter activity (GO:0042626)
ATPase-coupled intramembrane lipid transporter activity (GO:0140326)

Thanks, Pascale

**Comment by pgaudet** [comment]
See also #20500

**Comment by sjm41** [comment]
Thanks pascale!
To be clear - those are the only two ATPase MF terms lacking an 'is_a ATPase activity' relation that I found when reviewing Drosophila ATPases. It's possible (though unlikely?) there are other specific ATPase terms that lack an is_a parent that are not relevant to flies....

**Comment by pgaudet** [comment]
Right. I will do a query in protégé, but yesterday when I did it it looked like most of the terms were children of those 2 terms.

**Comment by sjm41** [comment]
Hi @pgaudet Can we go ahead and action this?

**Comment by pgaudet** [comment]
Hi @sjm41 

I started, but there are actually a lot of terms. Are there any terms that are higher priority for you ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Oh, I guess I was wrong then that just the two terms at the top of this ticket needed 'is_a ATPase activity' adding?
Those two were the priority for me, ie:
ATPase-coupled transmembrane transporter activity (GO:0042626)
ATPase-coupled intramembrane lipid transporter activity (GO:0140326)

Thanks!

**Comment by pgaudet** [comment]
Ah ok - done !

**Comment by pgaudet** [comment]
PR: https://github.com/geneontology/go-ontology/commit/565789bb6cc4e993fab5b8cda988e04d1785687a

**Comment by sjm41** [comment]
Thanks Pascale!  FYI @ValWood
