### ISSUE TITLE
NTR DNA-DNA tethering

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20503]
Definition
The Intrachromosomal links for cohesion
The binding activity of a protein or complex that connects two spatially separated regions of DNA sequence.

synonym
Intrachromosomal linking

Parents:
is_a GO:0030674   protein-macromolecule adaptor activity
has_part? DNA binding

References
Establishment of DNA-DNA Interactions by the Cohesin Ring
PMID: 29358048

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140564
+name: DNA-DNA tethering activity
+namespace: molecular_function
+def: "The binding activity of a protein or complex that connects two spatially separated regions of DNA sequence." [PMID:29358048]
+is_a: GO:0030674 ! protein-macromolecule adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20503 xsd:anyURI
+created_by: pg
+creation_date: 2020-12-03T13:50:16Z
+

**Comment by ValWood** [comment]
Oh sorry, I meant to update this ticket and I forgot. Later in the day I found
GO:0106260    JSON
double-stranded DNA bridging
Molecular Function

Definition (GO:0106260 GONUTS page)
The binding activity of a molecule that interacts selectively and non-covalently with two or more regions of double-stranded DNA simultaneously. The binding may be inter- or intramolecular with respect to the DNA. PMID:30626735

which is the same meaning.

I don't know if all "bridging/tethering" is double-stranded but in my current case it is, because the cohesin topologically entraps double-stranded DNA and connects it to other double-strsanded DNA

**Comment by pgaudet** [comment]
I just noticed you reopened this. So, I merge the 2 terms ?

**Comment by ValWood** [comment]
I think so.....
