### ISSUE TITLE
Mapping too large for UniProt keyword 'dynein'

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#20509]
The definition for UniProt keyword: Dynein [KW-0243] is:

Large multimeric complex with ATPase activity, responsible for the movement of eukaryotic cilia and flagella (axonemal dynein) and for the intracellular retrograde motility of vesicles, organelles and chromosomes along microtubules (cytosolic dynein). Constitutes the side arms of the outer microtubule doublets in the ciliary axoneme and is responsible for the sliding. Also used for the dynein-associated microtubule-binding proteins (MTBs), e.g. dynactin

But the GO mapping for this includes Motor activity [GO:0003774]
which is wrong for all proteins that are not strictly part of the dynein complex,
(the 'also used for...' part of the UniProt definition).
As a result dynactin components DCTN1 and DCTN2 are wrongly annotated with motor activity...

Reported by: alain-gateau

Original Ticket: [geneontology/annotation-issues/1295](https://sourceforge.net/p/geneontology/annotation-issues/1295)

**Comment by pgaudet** [comment]
@pgarmiri Do you still maintain the KW2GO file ? Can you remove the mapping 

UniProtKB-KW:KW-0243 Dynein > GO:motor activity ; GO:0003774


Or should the proteins that are not strictly part of the dynein complex not have the KW? @sylvainpoux ?

**Comment by sylvainpoux** [comment]
Hi,
I think we should remove the mapping between KW-0243 and Motor activity [GO:0003774 and only leave the GO:0030286; C:dynein complex mapping
Thanks
Sylvain

**Comment by pgarmiri** [comment]
Hi,

Yes, we still do this maintenance. I have removed the mapping between KW-0243 and Motor activity.

Thanks,

Penelope

**Comment by pgaudet** [comment]
Thanks !
