### ISSUE TITLE
GO:0004497	monooxygenase activity	missing parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20514]
Is applied to pombe  coq7
GO:0008682  2-octoprenyl-3-methyl-6-methoxy-1,4-benzoquinone hydroxylase activity
"Catalysis of the reaction: 2-octoprenyl-3-methyl-6-methoxy-1,4-benzoquinone + O2 = 2-octoprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinone."

which doesn't appear to fit the defintion of monoxygenase?

**Comment by pgaudet** [comment]
Since monooxygenase is_a oxidoreductase it makes sense to add the more specific parent. 

Also add EC:1.14.99.60 and rhea:50908

Thanks, Pascale

**Comment by hdrabkin** [comment]
@pgaudet, shall I try to do this now (ie, will I get the PR checked ?

**Comment by hdrabkin** [comment]
done.
