### ISSUE TITLE
 cohesin loading/ revise topological DNA entrapment activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20522]
is an  cohesin loading are activity. It is also multi-step, so it is also  a process

<img width="654" alt="Screenshot 2020-12-04 at 15 03 14" src="https://user-images.githubusercontent.com/7359272/101179497-316e8480-3642-11eb-8b2d-68f053277489.png">

image from the paper I am currently annotating:
PMID:33176147 DNA Binding by the Mis4 Scc2 Loader Promotes Topological DNA Entrapment by the Cohesin Ring.

~2 of the single-step activities are currently in the BP ontology
GO:0062022    mitotic cohesin ssDNA (lagging strand) loading 
The ATP-dependent protein localization to chromatin by which a cohesin ring complex is topologically linked to ssDNA (lagging strand) which is already linked to a dsDNA (leading strand) molecule as part of the mitotic cell cycle. PMID:29358048~

~GO:0062021    mitotic cohesin dsDNA (leading strand) loading
The protein localization to chromatin by which a cohesin ring complex is topologically linked to dsDNA (leading strand) as part of the mitotic cell cycle. PMID:29358048
Since the loading is doing this:
GO:0061776  topological DNA entrapment activity~

~Molecular Function
Definition (GO:0061776 GONUTS page)
The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring. PMID:16179255 PMID:26687354 PMID:27797071~
~I suggest.1. Move GO:0062021 and  GO:0062022 to MF
2. rename/define~
~GO:0062021    mitotic cohesin dsDNA (leading strand) loader activity
The activity which enables a cohesin ring complex to be topologically linked to dsDNA (leading strand) as part of the mitotic cell cycle. PMID:29358048~
~GO:0062022    mitotic cohesin ssDNA (lagging strand) loading 
The activity which enables a cohesin ring complex to be topologically linked to ssDNA (lagging strand) which is already linked to a dsDNA (leading strand), in a configuration referred to as 'co-entrapment' molecule as part of the mitotic cell cycle. PMID:29358048~

3. 
GO:0061776   
topological DNA entrapment activity
Molecular Function
Definition (GO:0061776 GONUTS page)
The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring. PMID:16179255 PMID:26687354 PMID:27797071

revise term name to 
topological DNA co-entrapment activity

(a single molecule or a double molecule can be entrapped. The entrapment of both sister chromtids is co-entrapment, this term describes co-entrapment)

see
<img width="414" alt="Screenshot 2020-12-04 at 14 51 06" src="https://user-images.githubusercontent.com/7359272/101178881-6dedb080-3641-11eb-8256-5aa261eb781e.png">

image from
Cell
. 2018 May 31;173(6):1508-1519.e18. doi: 10.1016/j.cell.2018.04.015. Epub 2018 May 10.
The Cohesin Ring Uses Its Hinge to Organize DNA Using Non-topological as well as Topological Mechanisms
PMID: 29754816

I won't request a term for single stranded entrapment because it seem that it is really only an intermediate step.

**Comment by ValWood** [comment]
We may want terms later to describe non-topological entrapment type DNA binding, but that isn't there paper that I am annotating.

**Comment by ValWood** [comment]
Note that the required ATPase required for the loading is in cohesin itself,   not in the loader  activity. The loader activates the cohesin ATPase activity. The loader has a number of activities : binds DNA (in 2 places), activates cohesin ATPase, catalyses entrapment.  I am annotating these as separate activities, because they are performed by different regions and there are lots of separation of function mutants.

**Comment by ValWood** [comment]
Hi @pgaudet  don't do this one yet. HAve been thinking about it some more.
Will update later

**Comment by ValWood** [comment]
After thinking about  this some more, even the ss loading and the ds loading are complex mult-funcational processes involving multiple functions of the loader and cohesin it self (some of which are still unclear). The first figure above is a simplification.

So  the loading terms need to stay in  BP.
I will use the new term requested here
https://github.com/geneontology/go-ontology/issues/20520

cohesin ATPase activator activity part_of GO:0062021 
and
cohesin ATPase activator activity part_of GO:0062022

so only point 3. needs to be addressed in this ticket

**Comment by ValWood** [comment]
This one is only the definition tweak in point 3.

**Comment by pgaudet** [comment]
I think it's a term label tweak ?
