### ISSUE TITLE
mitotic nuclear bridge terms - missing parent + new descendant

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20526]
GO:0140512    mitotic nuclear bridge midzone
Definition (GO:0140512)
The central region of a mitotic nuclear bridge, distal to the main portions of the daughter nuclei. ~The midzone forms a bulge that is enriched in nuclear pores that lack baskets~ PMID:32848252

should be part_of 

GO:0140510   mitotic nuclear bridge
Definition (GO:0140510 GONUTS page)
A narrow constricted region of the nucleus that forms around the anaphase spindle during closed mitosis, and connects the main portions of the newly forming daughter nuclei. PMID:32848252
GO:0140510   mitotic nuclear bridge

add  NTR mitotic nuclear bridge midzone membrane domain
def  A nuclear membrane part at the midzone of the mitotic nuclear bridge. The midzone forms a bulge that is enriched in nuclear pores that lack baskets.

(I think the new term is warranted because the midzone also contains the extended mitotic spindle)

PMID:32502403
i.e. We have shown that the MMD is in close proximity with the spindle midzone during anaphase B (Figure 1A). 

(move the 'gloss' about specialized nuclear pores to the new term)

e.g.

"At the center of this bridge, the NE presents a specialized domain that tightly surrounds the spindle midzone named mid-zone membrane domain (MMD) [5]"

References
5= PMID:25963819 
Lucena, R., Dephoure, N., Gygi, S.P., Kellogg, D.R., Tallada, V.A., Daga, R.R., and Jimenez, J. (2015). Nucleocytoplasmic transport in the midzone membrane domain controls yeast mitotic spindle disassembly. J. Cell Biol. 209, 387–402.

also  add  PMID:32502403 (new publication I am approving now).

**Comment by pgaudet** [comment]
Added new term: 

+[Term]
+id: GO:0140599
+name: mitotic nuclear bridge midzone membrane domain
+namespace: cellular_component
+def: "A nuclear membrane part at the midzone of the mitotic nuclear bridge. The midzone forms a bulge that is enriched in nuclear pores that lack baskets." [PMID:25963819, PMID:32502403]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0140512 ! mitotic nuclear bridge midzone
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20526 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-10T13:39:43Z

**Comment by pgaudet** [comment]
+ fixes term def and part_of parent for GO:0140512
