### ISSUE TITLE
Egg coat or Zona Pellucida ontology (GO:0035805)

### ISSUE THREAD

**Issue by ccasalsc** [geneontology/go-ontology#20537]
Hi, 
I have created the Zona Pellucida (egg coat synonym) subcellular location for UniProtKB and I see it doesn't have 'extracellular matrix' as parent in GO event it is described as ' specialized extracellular matrix' in the definition. Since 'Zona Pellucida' is considered as a child 'extracellular matrix' in UniProtKB, would it be possible to review it in GO? thank you

**Comment by pgaudet** [comment]
@ukemi @cmungall any opinion on this one ?

**Comment by ukemi** [comment]
Based on the definition it makes sense. I question whether the vitelline membrane would be considered an ECM though. I guess technically it could.

**Comment by krchristie** [comment]
https://en.wikipedia.org/wiki/Vitelline_membrane says:
> The vitelline membrane or vitelline envelope is a structure surrounding the outer surface of the plasma membrane of an ovum (the oolemma) or, in some animals (e.g., birds), the extracellular yolk and the oolemma. It is composed mostly of protein fibers, with protein receptors needed for sperm binding which, in turn, are bound to sperm plasma membrane receptors. The species-specificity between these receptors contributes to prevention of breeding between different species. **It is called zona pellucida in mammals**. 
> 
> In insects the vitelline membrane is called the vitelline envelope and is the inner lining of the chorion.

**Comment by pgaudet** [comment]
Thanks @krchristie

**Comment by pgaudet** [comment]
* Moved 'egg coat' under GO:0031012 ! extracellular matrix
* Removed GO:0031012 ! extracellular matrix part_of GO:0005576 ! extracellular region; replaced by GO:0030312 ! external encapsulating structure

**Comment by ccasalsc** [comment]
Thanks Pascale!
Best wishes

Cristina
________________________________

**Comment by pgaudet** [comment]
It's not finished yet... there are many domino effects. I also need to change 

perisynaptic extracellular matrix
part_of GO:0099544 ! perisynaptic space
=> change to 'adjacent to' some 'perisynaptic space'

**Comment by pgaudet** [comment]
Also changed 

GO:0043083 synaptic cleft
'extracellular region'
part_of some synapse 
=> changed to 'adjacent to'

(I am surprised that didn't cause problems before)

**Comment by pgaudet** [comment]
Also removed 'extracellular region' from a number of collagen terms

**Comment by pgaudet** [comment]
also extracellular matrix of synaptic cleft
changed part_of synaptic cleft to 'adjacent to'
(the synaptic cleft is defined as a 'gap', so technically it contains no parts ?
