### ISSUE TITLE
issues with & under term "sleep"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#20543]
Noticed in the process of working on this ticket: **NTR: Sleep homeostasis terms** #20499 

Currently, we have this structure:

-- multicellular organism process
--- sleep
---- circadian sleep/wake cycle, sleep
---- estivation
---- hibernation

I think this is wrong. Neither estivation or hibernation are types of sleep.

Reynolds JA. **Noncoding RNA Regulation of Dormant States in Evolutionarily Diverse Animals.** Biol Bull. 2019 Oct;237(2):192-209. PMID:31714856.

> [Abstract] Dormancy is evolutionarily widespread and can take many forms, including diapause, dauer formation, estivation, and hibernation. 
> 
> [Intro] Becoming dormant provides a means to survive changing environments and inhospitable conditions. Dormancy is widespread across all animal phyla, ranging from sponges to mammals; and it can take a number of forms that are broadly categorized as diapause, dauer, hibernation, or estivation, depending on the environmental cues (e.g., changes in photoperiod, crowding, temperature stress, desiccation, or starvation) that initiate the dormancy and the circumstances under which dormancy is terminated (e.g., endogenous mechanisms, improved food quality, or improved thermal environment). The specific characteristics that define dormancy for any given species are genetically determined but generally include some degree of metabolic depression, increased tolerance to environmental stress, and developmental arrest.

I think that estivation and hibernation need to be moved as they are not types of sleep. They need to be under a term for `dormancy` and `dormancy` should not have a relationship to `sleep` as it is an entirely different process with different reasons for it to occur.

Note that the current term `sleep` has `diapause` and `dormancy` as RELATED SYNONYMS. I not completely sure what the term `sleep` should cover but will look at annotation usage and also whether there would be any need for the current separate terms for `sleep` and `circadian sleep/wake cycle, sleep`, if there are no other children of `sleep` once once forms of dormancy are moved to an unrelated branch.

id: GO:0030431
name: sleep
namespace: biological_process
def: "Any process in which an organism enters and maintains a periodic, readily reversible state of reduced awareness and metabolic activity. Usually accompanied by physical relaxation, the onset of sleep in humans and other mammals is marked by a change in the electrical activity of the brain." [ISBN:0192800981]
subset: goslim_pir
synonym: "diapause" RELATED []
synonym: "dormancy" RELATED []
synonym: "lethargus" RELATED []
xref: Wikipedia:Sleep
is_a: GO:0032501 ! multicellular organismal process

**Comment by krchristie** [comment]
https://en.wikipedia.org/wiki/Dormancy

**Comment by krchristie** [comment]
Today, I've noticed that both "**estivation**" and "**hibernation**" are is a children of both "**sleep**" and "**dormancy process**". 

That makes it simple. I can just remove the is_a "sleep" parent and these two terms will be under "**dormancy process**" but not under "**sleep**" as is appropriate.

**Comment by raymond91125** [comment]
@krchristie I agree with you. Do you want me to effect the changes?

**Comment by krchristie** [comment]
@raymond91125 - yes thanks, that would be great. 👍

**Comment by raymond91125** [comment]
Hum, already removed. NV.
