### ISSUE TITLE
taxon constraint of term GO:0103012

### ISSUE THREAD

**Issue by laihokati** [geneontology/go-ontology#20553]
Hi,

The term GO:0103012 ferredoxin-thioredoxin reductase activity can currently only be annotated to taxon Viridiplantae. However, Cyanobacteria have this activity also, please see UniProt entry Q55389 annotated by me and for example PubMeds 14769790 and 17611542, and IPR024707 present in the UniProt entry. Even the GO term itself in QuickGO has mentioned PubMed 14769790 as reference.  I think some algae (for example Rhodophyta and Cryptophyceae) can also be annotated to this term since they have chloroplasts. Could you please check and help to widen the taxon constraint?

Thank you!

Best wishes,
Kati (from PIR)

**Comment by pgaudet** [comment]
Also added 
GO:0030386	ferredoxin:thioredoxin reductase complex	NCBITaxon:1117	Cyanobacteria

**Comment by pgaudet** [comment]
Fixed. @laihokati Do you want to check here: https://github.com/geneontology/go-ontology/blob/master/src/taxon_constraints/only_in_taxon.tsv

to see if there are terms that have only_in_ Viridiplantae that should also have cyanobacteria ? 

Thanks, Pascale
