### ISSUE TITLE
posttranscriptional regulation of gene expression | descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20568]
I am picking up mappings to
GO:0010608 | posttranscriptional regulation of gene expression |

where I have annotated to

GO:0000288 | nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay

should
GO:0010608 | posttranscriptional regulation of gene expression
be an ancestor of

GO:0000288 | nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay?

**Comment by pgaudet** [comment]
Shouldn't it ? 

I thought mRNA decay _was_ a way to regulate gene expression. 

@colinlog @RLovering

**Comment by ValWood** [comment]
I am saying that 
GO:0000288 | nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay

should have the ancestor
GO:0010608 | posttranscriptional regulation of gene expression

(currently it doesn't)

**Comment by pgaudet** [comment]
ok, thanks ! 

and not all other siblings ? 

'deadenylation-dependent decapping of nuclear-transcribed mRNA'
'histone mRNA catabolic process'
'nuclear mRNA surveillance'
'nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay'
'nuclear-transcribed mRNA catabolic process, deadenylation-independent decay'
'nuclear-transcribed mRNA catabolic process, endonucleolytic cleavage-dependent decay'
'nuclear-transcribed mRNA catabolic process, exonucleolytic'
'nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts'
'nuclear-transcribed mRNA catabolic process, no-go decay'
'nuclear-transcribed mRNA catabolic process, non-stop decay'
'nuclear-transcribed mRNA catabolic process, nonsense-mediated decay'
'nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay'
'nuclear-transcribed mRNA catabolic process, 5'-3' exonucleolytic nonsense-mediated decay'
'nuclear-transcribed mRNA poly(A) tail shortening'
'deadenylation involved in gene silencing by miRNA'
'polyadenylation-dependent mRNA catabolic process'
'polyuridylation-dependent mRNA catabolic process'

**Comment by ValWood** [comment]
I think so. I only spotted this one because I was pulling in extraneous annotations.

**Comment by pgaudet** [comment]
Discussing with @colinlog 
all those terms could be moved as children of the more specific term ->   GO:0061157 mRNA destabilization 

* GO:0000288 | nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay 
* 'GO:0098806 deadenylation involved in gene silencing by miRNA' 
*'GO:0071047 polyadenylation-dependent mRNA catabolic process' 
* GO:1990074 polyuridylation-dependent mRNA catabolic process'  

Other terms listed above are QC of the mRNA integrity, not regulation of gene expression, so I will not touch those for now.
