### ISSUE TITLE
obsolete, does not exist

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20564]
I think this term was created to mirror the  term for eukaryotic conjugation which involves morphological changes. BActerial conjugation doesn't involve any morphological changes

GO:0000759    cell morphogenesis involved in conjugation with mutual genetic exchange

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0000759 cell morphogenesis involved in conjugation with mutual genetic exchange. The reason for obsoletion is that there is no evidence that this process exists. There are no annotations or mappings to this term, this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/20564

Thanks, Pascale
