### ISSUE TITLE
ATP-dependent microfilament motor  activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20563]
I would like a term for 
ATP-dependent microfilament motor  activity
GO:0000146 | microfilament motor  activity

Which captures that it is an ATPase,  equivalent to the microtubule motors:

GO:1990939    ATP-dependent microtubule motor activity

**Comment by pgaudet** [comment]
reference please

**Comment by ValWood** [comment]
PMID:20705471

**Comment by ValWood** [comment]
this is essentially  requested in https://github.com/geneontology/go-ontology/issues/18664

closing as duplicate
