### ISSUE TITLE
GO:0090114 COPII-coated vesicle budding

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#20571]
is_a Golgi vesicle budding

but COPII is ER to golgi?

**Comment by pgaudet** [comment]
@lbreuza

**Comment by lbreuza** [comment]
Hi,
I agree with Antonia.
Lionel

**Comment by pgaudet** [comment]
OK, the problem is the CC term 

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/4782928/102263388-88af0780-3f14-11eb-8742-ba46ca44d913.png">

**Comment by pgaudet** [comment]
will remove 
ER to Golgi constitutive secretory pathway transport vesicle 
is_a 'Golgi-associated vesicle'
