### ISSUE TITLE
ntr. nucleolar ring

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20579]
def
Ring-like structures located at the nucleolar periphery where several nuclear factors are reversibly aggregated and sequestered during acute heat stress.
Synonym: NuRs
reference PMID: 33176152
Acute Heat Stress Leads to Reversible Aggregation of Nuclear Proteins into Nucleolar Rings in Fission Yeast.
is_a parent 
GO:0042405 nuclear  inclusion body

**Comment by ValWood** [comment]
hi, can this one be added? (was a community request for https://www.pombase.org/reference/PMID:33176152)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140602
+name: nucleolar ring
+namespace: cellular_component
+def: "Ring-like structures located at the nucleolar periphery where several nuclear factors are reversibly aggregated and sequestered during acute heat stress." [PMID:33176152]
+synonym: "NuRs" RELATED []
+is_a: GO:0042405 ! nuclear inclusion body
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20579 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-12T15:38:17Z
