### ISSUE TITLE
 NTR:  histone H3 containing nucleosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20585]
NTR:  histone H3 containing nucleosome
A complex comprised of DNA wound around a multisubunit core and associated proteins containing the histone H3, which forms the primary packing unit of DNA into higher order structures.

is_a
GO:0000786   nucleosome

I  have  been meaning to request this for a while so that I can differentiate canonical histones from
GO:0043505    CENP-A containing nucleosome

PMID: 33155135

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140573
+name: histone H3-containing nucleosome
+namespace: molecular_function
+def: "A complex comprised of DNA wound around a multisubunit core and associated proteins containing the histone H3, which forms the primary packing unit of DNA into higher order structures." [PMID:33155135]
+synonym: "histone H3 containing nucleosome" EXACT []
+is_a: GO:0000786 ! nucleosome
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20585 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-04T16:22:43Z
