### ISSUE TITLE
MF in BP barbed-end actin filament capping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20580]
I just used:
BP GO:0051016    barbed-end actin filament capping

but I wanted it to be a MF....

**Comment by pgaudet** [comment]
Is there a ticket already ? 
I use the label 'cytoskeleton', I would like to do all of those at once (10 issues).

**Comment by ValWood** [comment]
yes, duplicate sorry
https://github.com/geneontology/go-ontology/issues/19107

I had an old session that was part done, I didn't realise I had already submitted.
