### ISSUE TITLE
sterol  dehydrogenases

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20597]
These sterol dehydrogenases
<img width="1201" alt="Screenshot 2020-12-16 at 08 34 31" src="https://user-images.githubusercontent.com/7359272/102327492-b9775700-3f7d-11eb-8ac2-9ef020250cab.png">

ar in different branches
<img width="496" alt="Screenshot 2020-12-16 at 08 32 54" src="https://user-images.githubusercontent.com/7359272/102327424-a06ea600-3f7d-11eb-80a5-86b0b2e8fbdb.png">

It seems that they should all be grouped.

 Also the names are quite non-standardized:

4alpha-carboxy-4beta-methyl-5alpha-cholesta-8-en-3beta-ol:NAD(P)+ 3-oxidoreductase (decarboxylating) activity (GO:0103066)
Catalysis of the reaction: 4alpha-carboxy-4beta-methyl-5alpha-cholesta-8-en-3beta-ol + NAD(P) = 4alpha-methyl-5alpha-cholesta-8-en-3-one + carbon dioxide + NAD(P)H.

sterol-4-alpha-carboxylate 3-dehydrogenase (decarboxylating) activity (GO:0047012)
Catalysis of the reaction: NAD(P)+ + 3-beta-hydroxy-4-alpha-methyl-5-alpha-cholest-7-ene-4-beta-carboxylate = NAD(P)H + H+ + CO2 + 4-alpha-methyl-5-alpha-cholest-7-en-3-one.

4alpha-carboxy-5alpha-cholesta-8-en-3beta-ol:NAD(P)+ 3-dehydrogenase (decarboxylating) activity (GO:0103067)
Catalysis of the reaction: 4alpha-carboxy-5alpha-cholesta-8-en-3beta-ol + NAD(P) = 5alpha-cholesta-8-en-3-one + carbon dioxide + NAD(P)H.

3-beta-hydroxy-delta5-steroid dehydrogenase activity (GO:0003854)
Definition	Parents
Catalysis of the reaction: a 3-beta-hydroxy-delta(5)-steroid + NAD+ = a 3-oxo-delta(5)-steroid + NADH + H(+).

C-3 sterol dehydrogenase (C-4 sterol decarboxylase) activity (GO:0000252)
Catalysis of the reaction: 3-beta-hydroxy-4-beta-methyl-5-alpha-cholesta-8,24-dien-4-alpha-carboxylate + NAD(P)+ = 4-alpha-methyl-5-alpha-cholesta-8,24-dien-3-one + CO2 + NAD(P)H.

The names and definitions are not standardised.

For instance 
4alpha-carboxy-4beta-methyl-5alpha-cholesta-8-en-3beta-ol:NAD(P)+ 3-oxidoreductase (decarboxylating) activity (GO:0103066)
Looks like a superclass for but described differently.
C-3 sterol dehydrogenase (C-4 sterol decarboxylase) activity (GO:0000252)

**Comment by pgaudet** [comment]
@cmungall should this information come from adding logical definitions to MFs?

**Comment by ValWood** [comment]
These still are not classed as sterol dehydrogenases. Added to editors discussion
@balhoff 
@cmungall 
@pgaudet

**Comment by ValWood** [comment]
These are now either obsoleted or correctly positioned

except
C-3 sterol dehydrogenase (C-4 sterol decarboxylase) activity (GO:0000252)
Catalysis of the reaction: 3-beta-hydroxy-4-beta-methyl-5-alpha-cholesta-8,24-dien-4-alpha-carboxylate + NAD(P)+ = 4-alpha-methyl-5-alpha-cholesta-8,24-dien-3-one + CO2 + NAD(P)H.

Please advise is I can manually fix, or if this was missed in the obsoletions.

**Comment by pgaudet** [comment]
Thanks @ValWood , I added the parent.

**Comment by pgaudet** [comment]
After discussion with Lucila and Nevila from RHEA, about GO:0000252 C-3 sterol dehydrogenase (C-4 sterol decarboxylase) activity: 
- change name to  3-beta-hydroxysteroid dehydrogenase [NAD(P)]/C4-decarboxylase activity
- Changed def to match EC and RHEA from  "Catalysis of the reaction: 3-beta-hydroxy-4-beta-methyl-5-alpha-cholesta-8,24-dien-4-alpha-carboxylate + NAD(P)+ = 4-alpha-methyl-5-alpha-cholesta-8,24-dien-3-one + CO2 + NAD(P)H." [EC:1.1.1.170, PMID:9811880] to "Catalysis of the reaction: a 3-beta-hydroxysteroid-4-alpha-carboxylate + NADP+ = a 3-oxosteroid + CO2 + NADPH." [EC:1.1.1.170, PMID:9811880]
