### ISSUE TITLE
NTR: Transmembrane ascorbate ferrireductase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#20602]
Hi,

wouldn't is make sense to create a term describing the molecular function of Cytochrome b561 protein family based on https://www.rhea-db.org/rhea/30403, EC 7.2.1.3 and described in this papers: PubMed=16911521, PubMed=24449903.
Definition (tentative): Transmembrane ascorbate ferrireductase that that transfers electrons across a single membrane.

Reaction=Fe(3+)(out) + L-ascorbate(in) = Fe(2+)(out) + H(+) + monodehydro-L-ascorbate radical(in) [Rhea:30403]

It would be a child of GO:0016723. oxidoreductase activity, oxidizing metal ions, NAD or NADP as acceptor

It looks like thee creation of this term makes sense since the term  GO:0000293 ferric-chelate reductase activity has been curated to some members of that protein family, but the mechanism described may not fit there. 
Maybe @kaxelsen would be interested in this query too.

Best, Lionel

**Comment by pgaudet** [comment]
This is similar to 
https://enzyme.expasy.org/EC/1.10.2.1
https://www.rhea-db.org/rhea/18677
(no annotation). 

Some of those EC:7 terms are little confusing, mixing transporters and  enzymatic activities. Is this reaction to transport iron or to reduce it ? 

Thanks, Pascale

**Comment by lbreuza** [comment]
Hi Pascale,
this is why I had also added @kaxelsen  to this ticket. My understanding is that it oxidizes ascorbate on one side of the membrane while reducing iron on the other side of the membrane. Hence there is a flux of electron from in to out. This is why it is considered a transport reaction coupled to an oxido-reduction (EC.7...). The terms you mentioned are not describing reaction within a membrane and therefore there is not transport (only the oxido-reduction).
Lionel

**Comment by pgaudet** [comment]
Do we know that EC/1.10.2.1 exists ? I just wonder if two similar terms were created. Maybe we can add the other xrefs to GO:0016723. In any case you ask for this term to be under oxidoreductase activity, not under transporter activity. Looks like the membrane is a mechanism rather than true transport ?

**Comment by kaxelsen** [comment]
I'm looking at it right now, and since EC 1.10.2.1 is based on only 1 article from 1969, I suspect that it might be the same as EC 7.2.1.3

**Comment by kaxelsen** [comment]
I have now found the article (there was no abstract in PubMed) and read the abstryt (in German) and this protein IS the same as EC 7.2.1.3 because the work with the microsomal (i.e. ER membrane) fraction. I will do the necessary for this entry to be deleted from the EC list.

**Comment by pgaudet** [comment]
Thanks @kaxelsen 
@lbreuza we can change the xrefs on GO:0047063 and update the term definition.

**Comment by lbreuza** [comment]
Did you have a look at the parent term of GO:0047063? It would not match with the function I am trying to capture.

**Comment by pgaudet** [comment]
@kaxelsen To add to the confusion, https://enzyme.expasy.org/EC/7.2.1.3 states "Formerly EC 1.16.5.1. ", which is an Oxidoreductases with a quinone or similar compound as acceptor

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 
GO: 
was linking to https://www.rhea-db.org/rhea/18677
I think this also need to be merged into the new RHEA:30403

**Comment by pgaudet** [comment]
I propose this definition: 

Oxidation of Fe(3+) to Fe(2+) outside of a membrane coupled to the reduction of L-ascorbate to monodehydro-L-ascorbate radical on the inner side of a membrane. Electrons get transferred across the membrane during the reaction."

@lbreuza please let me know

I will obsolete GO:0047063  since it's too different, and incorrect.

**Comment by pgaudet** [comment]
@kaxelsen 
We should review what's in the branch here: 

https://enzyme.expasy.org/EC/1.10.3.-

>Oxidoreductases
Acting on diphenols and related substances as donors
With oxygen as acceptor

Many of those are not acting on diphenols, as far as I can tell

**Comment by kaxelsen** [comment]
> 
> 
> @kaxelsen To add to the confusion, https://enzyme.expasy.org/EC/7.2.1.3 states "Formerly EC 1.16.5.1. ", which is an Oxidoreductases with a quinone or similar compound as acceptor

Yes, and the reaction was
ascorbate[side 1] + Fe(III)[side 2] = monodehydroascorbate[side 1] + Fe(II)[side 2]


> 
> 
> @amorgat @kaxelsen
> GO:
> was linking to https://www.rhea-db.org/rhea/18677
> I think this also need to be merged into the new RHEA:30403

As we cannot merge reactions in Rhea, RHEA:18677 will be set to obsolete with a public note stating that it is now covered by RHEA:30403

**Comment by kaxelsen** [comment]
> 
> 
> @kaxelsen
> We should review what's in the branch here:
> 
> https://enzyme.expasy.org/EC/1.10.3.-
> 
> > Oxidoreductases
> > Acting on diphenols and related substances as donors
> > With oxygen as acceptor
> 
> Many of those are not acting on diphenols, as far as I can tell

I see what you mean, but they must go into the category "related substances" ;-)

**Comment by pgaudet** [comment]
ascorbate and iron are related to phenols ? OK I need to find my chemistry textbook....

**Comment by kaxelsen** [comment]
I agree, that ascorbate is really on the limit, but I think it is because it is an enol compound (or unsaturated alcohol that can loose one electron. I don't see any reactions with iron in EC 1.10.3.-

**Comment by lbreuza** [comment]
Hi,
I believe the parent term should be : GO:0016491 because non of the child matches correctly the reaction described.
Cheers, Lionel

**Comment by pgaudet** [comment]
I agree, we cannot be any more specific for now.

**Comment by pgaudet** [comment]
NTR 
+[Term]
+id: GO:0140571
+name: transmembrane ascorbate ferrireductase activity
+namespace: molecular_function
+def: "Oxidation of Fe(3+) to Fe(2+) outside of a membrane coupled to the reduction of L-ascorbate to monodehydro-L-ascorbate radical on the inner side of a membrane. Electrons get transferred across the membrane during the reaction." [PMID:16911521, PMID:24449903, RHEA:30403]
+synonym: "ascorbate-cytochrome b5 reductase activity" EXACT []
+synonym: "L-ascorbate-cytochrome-b5 reductase activity" EXACT []
+synonym: "L-ascorbate:ferricytochrome-b5 oxidoreductase activity" EXACT []
+xref: EC:7.2.1.3
+xref: MetaCyc:1.10.2.1-RXN
+xref: RHEA:30403
+is_a: GO:0016491 ! oxidoreductase activity
+created_by: pg
+creation_date: 2020-12-18T16:25:06Z

**Comment by lbreuza** [comment]
Dear Pascale,

I am now curating CYB561 which has a very similar activity except that it reduces semidebydroascorbate into ascorbate within the lumen of secretory vesicles and uses cytoplasmic ascorbate as an electron donor to replenish the lumen of vesicles with ascorbate as shown by PubMed=1623014.
Could you please consider creating a Molecular Function term to describe this activity.
It is not identical to GO:0016656 monodehydroascorbate reductase (NADH) activity that uses NADH as an electron donor.

I suggest :
NTR
+[Term]
+id: GO:xxxxxxx
+name: transmembrane monodehydroascorbate reductase activity
+namespace: molecular_function
+def: "Oxidation of monodehydroascorbate outside of a membrane coupled to the reduction of L-ascorbate to monodehydro-L-ascorbate radical on the inner side of a membrane. Electrons get transferred across the membrane during the reaction." 

L-ascorbate(in) + monodehydro-L-ascorbate radical(out)= H(+) + monodehydro-L-ascorbate radical(in) + L-ascorbate(out)

Btw I realized you did not provide the reaction in the transmembrane ascorbate ferrireductase activity term.


[PMID:1623014, RHEA:?]
+xref: EC:7.2.1.- (no specific EC)
+xref: RHEA:? (I have asked for the reaction)
+is_a: GO:0016491 ! oxidoreductase activity


Thanks for your help.
Best, Lionel

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140575
+name: transmembrane monodehydroascorbate reductase activity
+namespace: molecular_function
+def: "Oxidation of monodehydroascorbate outside of a membrane coupled to the reduction of L-ascorbate to monodehydro-L-ascorbate radical on the inner side of a membrane. Electrons get transferred across the membrane during the reaction." [PMID:1623014]
+xref: EC:7.2.1.-
+is_a: GO:0016491 ! oxidoreductase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20602 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-07T16:20:04Z

**Comment by pgaudet** [comment]
Also created the corresponding process: 

+[Term]
+id: GO:0140576
+name: cellular ascorbate homeostasis
+namespace: biological_process
+def: "Any process involved in the maintenance of an internal steady state of calcium ions at the level of a cell." [PMID:1623014, PMID:32547589]
+is_a: GO:0019725 ! cellular homeostasis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20602 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-07T16:50:44Z

**Comment by pgaudet** [comment]
@lbreuza I created the 2 new terms. Please let me know when the Rhea ID is available.

Thanks, Pascale

**Comment by kaxelsen** [comment]
It is RHEA:66524

**Comment by sjm41** [comment]
Hi @lbreuza 
Just wondering if you figured out how best to annotate the human CYB561 family members? (I'm looking at the fly orthologs, and struggling to work things out...)

Seems to be 5 relevant human genes/proteins from this page: https://www.genenames.org/data/genegroup/#!/group/497

Do you know if they all do both the reactions mentioned above, or do some do only one?

I see these manual annotations on protein2GO right now:
**CYB561 (P49447)** - transmembrane monodehydroascorbate reductase activity
**CYBRD1 (Q53TN4)** - transmembrane monodehydroascorbate reductase activity & transmembrane ascorbate ferrireductase activity
**CYB561A3 (Q8NBI2)** - transmembrane ascorbate ferrireductase activity
**CYB561D1 (Q8N8Q1)** - (neither annotation)
**CYB561D2 (O14569)** - transmembrane monodehydroascorbate reductase activity & transmembrane ascorbate ferrireductase activity


This 2013 review may be helpful:
https://pubmed.ncbi.nlm.nih.gov/23249217/

Another Q: Should 'electron transfer activity' be a parent of both terms?

**Comment by lbreuza** [comment]
Hi Steven,
I have recently updated the human proteins containing a cytochrome b561 domain (the 5 human proteins you mention in your ticket). If you have access to the most recent GO annotations, then you can see my annotations in GO for these proteins. 
The best characterized protein in human is Q53TN4 : 
Plasma membrane reductase that uses cytoplasmic ascorbate as an electron donor to reduce extracellular Fe3+ into Fe2+ (PubMed:30272000). Probably functions in dietary iron absorption at the brush border of duodenal enterocytes by producing Fe2+, the divalent form of iron that can be transported into enterocytes (PubMed:30272000). It is also able to reduce extracellular monodehydro-L-ascorbate and may be involved in extracellular ascorbate regeneration by erythrocytes in blood (PubMed:17068337). May also act as a ferrireductase in airway epithelial cells (Probable). May also function as a cupric transmembrane reductase (By similarity).

The electron donor is ascorbate but acceptors may include iron and monodehydro-L-ascorbate. This is why I curated CYBRD1 with 2 GO terms. Other proteins containing this domain have either only one acceptor demonstrated or none yet which explains why they have only reaction annotated or none like CYB561D1.

These proteins catalyse an oxido-reduction reaction which results due to the fact that they are transmembrane proteins to the transfer of an electron to one side of a membrane to the other side. 

Concerning the 'electron transfer activity' it sounds a reasonable annotation. I could add it. @pgaudet, do you have an opinion on that. I felt like it was redundant but maybe one could add it.

Lionel

**Comment by sjm41** [comment]
Thanks Lionel, that's helpful.

Since the 2 terms are related, I was thinking that a grouping term in the GO would be useful, so folks can easily find proteins annotated with either term.  Something like "oxidoreductase activity, acting on ascorbate as donor" (similar to the existing grouping term "oxidoreductase activity, acting on diphenols and related substances as donors (GO:0016679))".  What do you think?

Regarding the 'electron transfer activity' term, I was suggesting adding it as a parent to the GO term(s), rather than adding it as an extra annotation.

**Comment by lbreuza** [comment]
Hi Steven,
what you suggest make sense and I basically agree. This is something we discussed with @pgaudet while quickly revisiting this part of the ontology and for some reasons, I cannot recall, we decided to keep it simple. Maybe Pascale wants to reconsider or comment on these suggestions.
Best, Lionel
