### ISSUE TITLE
membrane adaptor parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20606]
We are picking up a mapping to
protein-membrane adaptor activity

for sad1
spindle pole body-nuclear membrane anchor activity
<img width="1007" alt="Screenshot 2020-12-16 at 09 41 48" src="https://user-images.githubusercontent.com/7359272/102346618-0e739700-3f97-11eb-9191-fb758027674d.png">

In pombe sad1 connects the SPB to the nuclear envelope. 

Shoudl this have the parent "protein membrane adaptor?"
Note that most of the other terms connecting macromolecular complexes to membranes are under  "protein membrane adaptor?"

for example, 
centromere-nuclear envelope anchor activity
cytoskeletal protein-membrane anchor activity
endoplasmic reticulum-autophagosome adaptor activity
heterochromatin-nuclear membrane anchor activity
etc.

**Comment by pgaudet** [comment]
Added missing parent
