### ISSUE TITLE
membrane and membrane fusion issues - missing logical definitions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20624]
missing parent
nuclear membrane fusion (GO:0000740)

please add

nuclear membrane organization (GO:0071763)

**Comment by ValWood** [comment]
can this be added? There is another ticket that is a bit more detailed. I will follow up on that one at the w/end

**Comment by pgaudet** [comment]
I dont understand why we dont get this from the logical definitions. 

@balhoff Can we look at this together ?

**Comment by pgaudet** [comment]
Missing LD definitiond for membrane fusion and nuclear membranes: 

**nuclear membrane fusion**
remove:
-is_a: GO:0090174 ! organelle membrane fusion

**GO:0016020 membrane**
add LD: 
+intersection_of: GO:0016020 ! membrane
+intersection_of: part_of GO:0043226 ! organelle
 
**GO:0031090 organelle membrane**
remove: 
-relationship: part_of GO:0043226 ! organelle

**nuclear membrane**
remove:
-is_a: GO:0031090 ! organelle membrane
-relationship: part_of GO:0005634 ! nucleus
add LD:
+intersection_of: GO:0016020 ! membrane
+intersection_of: part_of GO:0005634 ! nucleus

**Comment by pgaudet** [comment]
@balhoff 
I just figured out that the relation used in the LD for membrane fusion and children is 'results in fusion of'
* in the go-obo file, it looks like it's in GOREL:
* [Typedef]
id: results_in_fusion_of
name: results_in_fusion_of
namespace: external
xref: GOREL:0002005
is_a: has_participant ! has participant

However I cannot find it in GOREL. Should I add it to RO ? 

@cmungall

**Comment by cmungall** [comment]
yes, go ahead and add it!

**Comment by pgaudet** [comment]
Added relation in RO: https://github.com/oborel/obo-relations/issues/430

RO:0012008 results in fusion of

**Comment by pgaudet** [comment]
Also, added LD to some high level terms: 

GO:0043227 membrane-bounded organelle
organelle
and 'has part' some membrane


GO:0065010 extracellular membrane-bounded organelle
'membrane-bounded organelle'
and 'part of' some 'extracellular region'

GO:0043231 intracellular membrane-bounded organelle
'membrane-bounded organelle'
and 'part of' some 'intracellular anatomical structure'


GO:0043232 intracellular non-membrane-bounded organelle
'non-membrane-bounded organelle'
 and ('part of' some 'intracellular anatomical structure')

GO:0043264 extracellular non-membrane-bounded organelle
'non-membrane-bounded organelle'
 and ('part of' some 'extracellular region')

**Comment by pgaudet** [comment]
This should get fixed once the RO gets updated.

**Comment by pgaudet** [comment]
@balhoff Can we reload RO ?

**Comment by balhoff** [comment]
Sure, I started a build for the RO import.

**Comment by pgaudet** [comment]
I suppose that as long as there is no PR this has not yet gone through?

**Comment by pgaudet** [comment]
I think this is now right ? 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/4782928/110529635-c8ebe380-8119-11eb-81cd-52db1c170c1e.png">

**Comment by pgaudet** [comment]
I'll wait to see it in QuickGO
