### ISSUE TITLE
GO:0045730    respiratory burst

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20638]
This sounds like a phenotype, or a combination of process and outcome (i.e positive regulation of respiration +  production of free radicals (only has 32 annotations). Should it exist?

GO:0045730    respiratory burst

Definition (GO:0045730)
A phase of elevated metabolic activity, during which oxygen consumption increases; this leads to the production, by an NADH dependent system, of hydrogen peroxide (H2O2), superoxide anions and hydroxyl radicals.

**Comment by addiehl** [comment]
GO:0045730 respiratory burst refers to the regulated production of reactive oxygen species involved in defense responses in both animals and plants, as well as cell signaling and other processes.
https://en.wikipedia.org/wiki/Respiratory_burst

The child term, GO:0002679 respiratory burst involved in defense response represents an essential process of the innate immune system.  The respiratory burst is used a defensive mechanism in neutrophils and other leukocytes, used to kill bacteria and other pathogens via the production of reactive oxygen species.  This is a very well studied process.
https://pubmed.ncbi.nlm.nih.gov/27558335/
https://pubmed.ncbi.nlm.nih.gov/19224236/
https://pubmed.ncbi.nlm.nih.gov/10618505/

**Comment by ValWood** [comment]
Yes that makes sense, we use it for plants too. I think I was confused by the grouping but  it is also used in non defense contexts.
