### ISSUE TITLE
missing parent GO:0046467    membrane lipid biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20632]
GO:0046467    membrane lipid biosynthetic process

please add parent

GO:0008610    lipid biosynthetic process

**Comment by pgaudet** [comment]
The parent is already there - close ? 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/4782928/104934982-f71b3580-59aa-11eb-9f6c-fec9f27ad4ec.png">

**Comment by ValWood** [comment]
Weird, yes
