### ISSUE TITLE
nuclear envelope reassembly/assembly parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20636]
I expected these terms 
GO:0031468    nuclear envelope reassembly
GO:0051081    nuclear envelope disassembly

to be
GO:0071763    nuclear membrane organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of the nuclear inner or outer membrane.

so I think they should be renamed
"nuclear membrane reassembly/disassembly"

These term refer to membranes and the "nuclear envelope" also includes the intermembrane space.

**Comment by pgaudet** [comment]
But envelope is different from membrane - you think they have been misused ? 

Again we have a large number of terms, not sure they all describe different processes: 

'nuclear envelope organization'
'nuclear envelope disassembly'
'meiosis I nuclear envelope disassembly'
'meiosis II nuclear envelope disassembly'
'meiotic nuclear envelope disassembly'
'mitotic nuclear envelope disassembly'
'mitotic nuclear pore complex disassembly'
'sperm nuclear envelope removal'
'nuclear envelope reassembly'
'meiosis I nuclear envelope reassembly'
'meiosis II nuclear envelope reassembly'
'meiotic nuclear envelope reassembly'
'mitotic nuclear envelope reassembly'
'pronuclear envelope synthesis'
'male pronuclear envelope synthesis'
'nuclear membrane organization'
'mitotic nuclear membrane organization'
'nuclear fragmentation involved in apoptotic nuclear change'
'nuclear inner membrane organization'
'nuclear outer membrane organization'

**Comment by ValWood** [comment]
Well it is different, but this is tricky.

The lumen is created as a consequence of the assembly of the membranes.
I'm guessing that people refer to the "envelope" assembly or disassembly because both membranes assemble or disassemble simultaneously.  But if we call this process "nuclear envelope assembly" it is difficult to connect  the process to "nuclear membrane organization" which  is useful.


This is the problem as I see it:
<img width="573" alt="Screenshot 2021-01-06 at 13 05 45" src="https://user-images.githubusercontent.com/7359272/103771848-6cd4e800-5020-11eb-8011-0ff673032dd0.png">

I would rather the terms were "nuclear membrane assembly, which is a) more precise, and b) would allow the annotation to be correctly inherited by "nuclear membrane organization"


Perhaps there should only be a single term mentioning envelope  "nuclear envelope organization" which could be a superclass of  everything  and allows any (non membrane) organization which might occur in the luman to be grouped. But  then make the assembly/disassembly terms refer to "nuclear membrane assembly/disassemly"

that would involve
'pronuclear envelope synthesis' ->'pronuclear membrane synthesis'
nuclear envelope disassembly -> nuclear membrane disassembly (the lumen is not disassembled)
All of the other "nuclear envelope assembly/reassembly" terms would merge  or change into into their cognate "nuclear membrane assembly" terms.

I think that would work but tagging Gautam Dey to check @deygautam

In fact, I think there is a logical issue here anyway. 

organelle envelope
Definition 
A double membrane structure enclosing an organelle, including two lipid bilayers and the region between them. In some cases, an organelle envelope may have more than two membranes.

If envelope + membrane + lumen then "envelope" terms,  can't be a descendant of "membrane", it's broader.

**Comment by ValWood** [comment]
I asked @deygautam

"I agree - there is no reason to distinguish nuclear envelope from nuclear membrane terms. I think your idea makes a lot of sense! "

(note this applies to  the "assembly"  process terms, it is still fine to have envelope as a component
for IM+lumen+OM)

so I propose:

'nuclear envelope disassembly' ->   nuclear membrane disassembly
and equivalent for the descendants

'nuclear envelope reassembly'.  - > nuclear membrane reassembly
and equivalent for the descendants

I don't know enough to know if the mitotic/meiotic p use different pathways/ genes 
so I suggest we keep the terms specific  for the time being. They can be merged up later if desired. I'm more concerned about the incorrect parentage because it affects query results.

v.

**Comment by pgaudet** [comment]
So I change 'envelope' to 'membrane' in all those terms: 

'nuclear envelope organization'
'nuclear envelope disassembly'
'nuclear envelope reassembly'
'meiotic nuclear envelope reassembly'
'mitotic nuclear envelope reassembly'
?

**Comment by pgaudet** [comment]
I will not be able to keep that is_a relation: 
GO:0007077 mitotic nuclear envelope disassembly
 [is_a relation] GO:0140516 mitotic nuclear pore complex disassembly 

Any suggestions?

**Comment by pgaudet** [comment]
GO:0140516 mitotic nuclear pore complex disassembly, changed subclasses to 
+is_a: GO:0032984 ! protein-containing complex disassembly
+relationship: part_of GO:0000278 ! mitotic cell cycle
+relationship: part_of GO:0006998 ! nuclear envelope organization

**Comment by ValWood** [comment]
GO:0140516 mitotic nuclear pore complex disassembly
is part_of  mitotic nuclear envelope disassembly
(the pore complex disassembly triggers the envelope disassembly in some way. Because pombe because it does closed mitosis, this is localized disassembly  at the  spindle midzone.)

**Comment by pgaudet** [comment]
OK  in this case I dont change 'mitotic nuclear envelope disassembly' to 'mitotic nuclear **membrane** disassembly'
but then it doesn't make sense to change its parent, 'nuclear envelope disassembly', to nuclear **membrane**  disassembly

I am not clear what you are asking anymore...

**Comment by pgaudet** [comment]
You can have a look at the changes here 
https://github.com/geneontology/go-ontology/pull/21078/commits/98a04a7d2c9414ee1af5c976ea581c4a23d66fe5

**Comment by ValWood** [comment]
Sorry I typed 'envelope' I meant 'membrane'

**Comment by pgaudet** [comment]
Please reopen if you see other problems.

**Comment by ValWood** [comment]
I don't see these changes yet. They did not come through to quickgo either. Is everything working with the releases?

**Comment by pgaudet** [comment]
The latest release was on March 16th, so those should now be in.

**Comment by ValWood** [comment]
the only thing i noticed was

<img width="432" alt="Screen Shot 2021-03-18 at 12 34 10" src="https://user-images.githubusercontent.com/7359272/111626890-61ebc000-87e6-11eb-947f-ba92e58a09da.png">


GO:0031468 should be under
 GO:0071763 nuclear membrane organization

**Comment by ValWood** [comment]
Hi @pgaudet  could you add this parent (last comment), and this one can re-close (I was just about to open a new ticket for this)
