### ISSUE TITLE
NTR: vacuole fission

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20639]
Term name: vacuole fission

Definition
The division of a vacuole within a cell to form two or more separate vacuoles.

is_a descendant of 
GO:0048285 | organelle fission

PMID:19643199
Title | The dynamin-related protein Vps1 regulates vacuole fission, fusion and tubulation in the fission yeast, Schizosaccharomyces pombe.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140572
+name: vacuole fission
+namespace: biological_process
+def: "The division of a vacuole within a cell to form two or more separate vacuoles." [PMID:19643199]
+is_a: GO:0048285 ! organelle fission
+intersection_of: GO:0048285 ! organelle fission
+intersection_of: results_in_fission_of GO:0005773 ! vacuole
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20639 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-04T10:17:58Z
