### ISSUE TITLE
Term merge dATP/ATP triphosphate pyrophosphatase  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20656]
Hello, 

Working on the annotation ticket https://github.com/geneontology/go-annotation/issues/3581 NUDT1 (P36639)

I think we need to edit the ontology as follows: 

-  GO:0044714  2-hydroxy-(deoxy)adenosine-triphosphate pyrophosphatase activity (no annotations, mapped to Reactome R-HSA-2395818 "NUDT1 hydrolyses 2-OH-dATP to 2-OH-dAMP ") **should merge into**  "GO:0008828
 dATP pyrophosphohydrolase activity" : RHEA:31583; EC:3.6.1.56 (label is 2-hydroxy-dATP diphosphatase  in EC)

- GO:0044713 2-hydroxy-adenosine triphosphate pyrophosphatase activity (no annotations, mapped to Reactome R-HSA-2395872 NUDT1 hydrolyses 2-OH-ATP to 2-OH-AMP ) **should merge into** GO:0008828 dATP pyrophosphohydrolase activity (RHEA:31583; EC:3.6.1.56)

-  GO:0035539 8-oxo-7,8-dihydrodeoxyguanosine triphosphate pyrophosphatase activity: Add EC:3.6.1.55

@ukemi 
@deustp01 
Do you agree ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ukemi
@deustp01
@kaxelsen 

If there are no objections I will go ahead and implement this. 

Thanks, Pascale

**Comment by kaxelsen** [comment]
I have no objections

**Comment by deustp01** [comment]
no objections here either
