### ISSUE TITLE
NTR  mitochondrial import machinery (MIM) complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20669]
In budding yeast, Mim2 is a component of the mitochondrial import machinery (MIM) complex, which consists of Mim1 and Mim2 (Dimmer et al., 2012; Stefan Dimmer and Rapaport, 2010). 
Reciprocal immunoprecipitation experiments revealed that Mim2 also interacts with Mim1 in fission yeast (Figure 5—figure supplement 1C and D), suggesting that the MIM complex is conserved. 

I can't find this...

suggest
term mitochondrial import machinery (MIM) complex
is_a 
GO:0005742    mitochondrial outer membrane translocase complex
(this means that TOM complex can't be exact synonym of this complex, needs to be a descendant, so maybe change the label and make a common parent)

def
protein insertase which inserts  single-spanning N or C terminally anchored proteins into the mitochondrial outer membrane.

def source https://pubmed.ncbi.nlm.nih.gov/32348752/

**Comment by pgaudet** [comment]
@ValWood 
We have 
GO:0005742 mitochondrial outer membrane translocase complex
and 
GO:0005744 TIM23 mitochondrial import inner membrane translocase complex 

Are those term suitable ?

**Comment by ValWood** [comment]
non,  TIM23 is inner membrane.

TOM complex is a type of mitochondrial outer membrane translocase complex (should not be exact synonym)

mitochondrial import machinery (MIM) complex
is another mitochondrial outer membrane translocase

**Comment by pgaudet** [comment]
Are there other examples of mitochondrial outer membrane translocases? Or do you want to create a single child of GO:0005742 mitochondrial outer membrane translocase complex?

**Comment by ValWood** [comment]
It should be

mitochondrial outer membrane translocase
--TOM complex
--MIM complex

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140595
+name: MIM complex
+namespace: cellular_component
+def: "A large mitochondrial outer membrane transolcase complex that mediates transport of proteins into mitochondrial compartments. MIM constitutes the major integration site for α-helical embedded proteins. In yeast, consists oof Mim1 and Mim2." [PMID:19944477, PMID:22467864, PMID:33035511]
+synonym: "mitochondrial outer import machinery" EXACT []
+is_a: GO:0005742 ! mitochondrial outer membrane translocase complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20669 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-09T19:34:16Z
+
+[Term]
+id: GO:0140596
+name: TOM complex
+namespace: cellular_component
+def: "A large mitochondrial outer membrane transolcase complex that mediates transport of proteins into mitochondrial compartments. TOM transports β-barrel precursors across the outer membrane and the sorting and assembly machinery (SAM complex) inserts them into the target membrane." [PMID:33035511]
+synonym: "translocase of the outer mitochondrial membrane" EXACT []
+is_a: GO:0005742 ! mitochondrial outer membrane translocase complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20669 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-09T19:43:51Z

**Comment by pgaudet** [comment]
Also moved 'GO:0001401 SAM complex' under 'mitochondrial outer membrane translocase complex'

**Comment by ValWood** [comment]
Odd, I don't see this yet in Canto and commit was 6 days ago....will ask @kimrutherford  to check.

But also,  @pgaudet could you check sp.  of translocase in both defs.
+def: "A large mitochondrial outer membrane transolcase

**Comment by ValWood** [comment]
This was added 8 days ago but isn't in QUICKGO yet. Is the  snapshot working OK?

**Comment by pgaudet** [comment]
There was a snapshot yesterday.

**Comment by ValWood** [comment]
OK!
