### ISSUE TITLE
NTR. mitochondrion autophagosome adaptor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20668]
mitochondrion autophagosome adaptor
synonym exact, mitophagy receptor 
parent  GO:0043495   protein-membrane adaptor activity

def
The binding activity of a molecule that brings together a mitochondrial membrane and an autophagosome during mitophagy (adapted from sibling GO:0140506  endoplasmic reticulum-autophagosome adaptor activity

ref

PMID:33138913
Title | Atg43 tethers isolation membranes to mitochondria to promote starvation-induced mitophagy in fission yeast.
Authors | Fukuda T, Ebi Y, Saigusa T, Furukawa K, Yamashita SI, Inoue K, Kobayashi D, Yoshida Y, Kanki T
Publication date | 03 Nov 2020

**Comment by ValWood** [comment]
Hi, this is my most urgent ticket if  you are looking for a quick one ;)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140580
+name: mitochondrion autophagosome adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a mitochondrial membrane and an autophagosome during mitophagy." [PMID:33138913]
+synonym: "mitophagy receptor" EXACT []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20668 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-18T11:03:49Z
