### ISSUE TITLE
NTR: octaprenyl pyrophosphate synthase activity (EC:2.5.1.90)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20665]
Of the prenyltransferase activities listed in #20661, a GO term for this one appears to be missing:

octaprenyl pyrophosphate synthase activity

This is EC:2.5.1.90 (https://enzyme.expasy.org/EC/2.5.1.90), so can use definition from that entry. Should be child of GO:0004659 prenyltransferase activity, I think.
Rhea is https://www.rhea-db.org/rhea/27798

Relevant to UniProt P0AD57 amongst others.
(https://www.uniprot.org/uniprot/?query=ec%3A%22All-trans-octaprenyl-diphosphate+synthase+%5B2.5.1.90%5D%22&sort=score)

**Comment by hdrabkin** [comment]
+id: GO:0106350
+name: octaprenyl pyrophosphate synthase activity

Done

**Comment by sjm41** [comment]
Thanks!

**Comment by hdrabkin** [comment]
Doing the other ticket also: (#20661).
