### ISSUE TITLE
Add EC xref to GO:0097269

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20662]
id: GO:0097269
name: all-trans-decaprenyl-diphosphate synthase activity
def: "Catalysis of the reaction: 2-trans,6-trans-farnesyl diphosphate + 7 isopentenyl diphosphate = 7 diphosphate + all-trans-decaprenyl diphosphate." [EC:2.5.1.91, GOC:mw, PMID:16262699]
xref: RHEA:27802

Please add the EC xref mentioned in the def (EC:2.5.1.91) as an xref.

**Comment by hdrabkin** [comment]
I'll get this one now; note I am manually working through the list for the bulk RHEA association which added the RHEA as an xref, but did not move/replace an EC if in Def ref and move EC in def ref to regular xref.

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks!
