### ISSUE TITLE
Active GO terms with comment "This term represents a deleted EC activity and is scheduled for obsoletion."

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20664]
I see 9 GO terms with the comment "This term represents a deleted EC activity and is scheduled for obsoletion." - I think all these cases can be easily fixed and the comment removed:

- [x] id: GO:0004158    DONE
name: dihydroorotate oxidase activity
def: "Catalysis of the reaction: (S)-dihydroorotate + O(2) = H(2)O(2) + orotate." [EC:1.3.3.1, RHEA:15441]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:1.3.3.1
xref: RHEA:15441
=> update EC to 1.3.98.1, remove comment

- [x] id: GO:0004810  PENDING    Fixed in #19854
name: tRNA adenylyltransferase activity
def: "Catalysis of the reaction: ATP + tRNA(n) = diphosphate + tRNA(n+1)." [EC:2.7.7.25]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:2.7.7.25 REMOVED in #19854
=> this is a grouping term in GO, remove EC, remove comment; no; not grouping ter. EC:2.7.7.72 and correct RHEA supplied ; this is the CCA enzyme

- [x] id: GO:0008752 DONE
name: FMN reductase activity
def: "Catalysis of the reaction: FMNH2 + NAD(P)+ = FMN + NAD(P)H + H+." [EC:1.5.1.29]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
=> is this term being kept? (if so, EC:1.5.1.29 is replaced with  1.5.1.38 / 1.5.1.39 / 1.5.1.41)

- [x] id: GO:0016437  PENDING Fixed in #19854
name: tRNA cytidylyltransferase activity
def: "Catalysis of the reaction: CTP + tRNA(n) = diphosphate + tRNA(n+1)." [EC:2.7.7.21]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:2.7.7.21 Removed. 
=> 

- [x] id: GO:0016719 DONE
name: carotene 7,8-desaturase activity
def: "Catalysis of the reaction: neurosporene + donor-H2 + O2 = lycopene + acceptor + 2 H2O." [EC:1.14.99.30]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:1.14.99.30
xref: MetaCyc:1.14.99.30-RXN
xref: RHEA:15701
=> replace with 1.3.5.6 & remove comment

- [x] id: GO:0046592 Done; remove EC but leave the PMID.
name: polyamine oxidase activity
def: "Catalysis of the oxidative degradation or interconversion of polyamines." [EC:1.5.3.11, PMID:1567380]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:1.5.3.11
=> replace with  1.5.3.13 / 1.5.3.14 / 1.5.3.15 / 1.5.3.16 / 1.5.3.17 (or make new child terms??) and remove comment

- [x] id: GO:0047606  Done; used EC:4.1.2.47 after looking at general reactions in RHEA.
name: hydroxynitrilase activity
def: "Catalysis of the reaction: a hydroxynitrile = cyanide + an aldehyde or ketone." [EC:4.1.2, GOC:mah, MetaCyc:ACETONE-CYANHYDRIN-LYASE-RXN]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:4.1.2.37
=> replace with 4.1.2.46 / 4.1.2.47 and remove comment

- [x] id: GO:0048045 DONE
name: trans-pentaprenyltranstransferase activity
def: "Catalysis of the reaction: all-trans-pentaprenyl diphosphate + isopentenyl diphosphate = all-trans-hexaprenyl diphosphate + diphosphate." [RHEA:22632]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:2.5.1
xref: RHEA:22632
=> this EC number is a grouping term, so should just be removed, and remove comment (it has a RHEA)

- [x] id: GO:0050347  DONE
name: trans-octaprenyltranstransferase activity
def: "Catalysis of the reaction: all-trans-octaprenyl diphosphate + isopentenyl diphosphate = all-trans-nonaprenyl diphosphate + diphosphate." [RHEA:11324]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:2.5.1.84
xref: EC:2.5.1.85
xref: RHEA:11324
=> Both ECs appear to be active -> remove comment.

**Comment by hdrabkin** [comment]
argh! I thought I had gotten them all!

**Comment by sjm41** [comment]
Sorry to be the bearer of bad news.....  (is there an existing ticket for these things?)

**Comment by hdrabkin** [comment]
d: GO:0004810
name: tRNA adenylyltransferase activity
def: "Catalysis of the reaction: ATP + tRNA(n) = diphosphate + tRNA(n+1)." [EC:2.7.7.25]
comment: This term represents a deleted EC activity and is scheduled for obsoletion.
xref: EC:2.7.7.25
=> this is a grouping term in GO, remove EC, remove comment

This should actually be merged but there is a problem (there is a ticket on this already). 
#19854, #17855, and #11721

1. in most annotations, one monitors the enzyme activity using only the A- addition, but the enzyme is still the CCA addition enzyme.  Some use CTP also.
2. However, although most organisms have ONE enzyme, there are some that have two separate enzymes, one to add the CC, and a separate to add the A.   (PMID:18523015)
So I was going to merge all of them to just CCA, BUT, needed to know if ANY of the existing annotations were to the organisms using the two enzymes. 

Note: RHEA does not break out the CCA into 3 reactions (much like they do not split out each of the AARs into two reactions, A; creation of the aa-amp, and B: transfer from aa-amp to aa-tRNA (one can measure both reactions).
So, we actually need.
1. term for the CCA enzyme; term merge for most of these
2. a separate CC term
3. a separate A term; 
2 and 3 need a taxon restriction to only those organisms that process the tRNA 3' end with 2 separate enzyme.

I will also copy this to the other tickets.

**Comment by hdrabkin** [comment]
GO:0008752 Note: NAD(P) def; ecEC 1.5.1.38 is for NADP only
EC 1.5.1.39 is for NAD(P)   
EC 1.5.1.41 is for NAD(P) but specifies Reduced riboflavin  (FAD). 
I'll keep EC:1.5.1.39 as it is the closer match for the current def, it's really a grouping term; I'll need to get a proper reference.

**Comment by hdrabkin** [comment]
I've done most; however there are some ones that need a bit of thought.

**Comment by sjm41** [comment]
Great, thanks.  (Apologies if I over-simplified those tricky cases!)

**Comment by pgaudet** [comment]
Does that supersede the other ticket #12432 ?

**Comment by hdrabkin** [comment]
I'll need to check #12432 to see if the ones in THIS ticket are the only ones lef.

**Comment by sjm41** [comment]
@hdrabkin I think this one can be closed - agree?
