### ISSUE TITLE
Prenyltransferase term relations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20661]
I _think_ the following 11 terms should be children of 'GO:0004659 prenyltransferase activity' rather than the higher level term 'GO:0016765 transferase activity, transferring alkyl or aryl (other than methyl) groups':

id: GO:0102059   DONE
name: 2-cis,6-cis-farnesyl pyrophosphate synthase activity gene

id: GO:0044687 DONE
name: geranylfarnesyl diphosphate synthase activity

id: GO:0036423 DONE
name: hexaprenyl-diphosphate synthase ((2E,6E)-farnesyl-diphosphate specific) activity

id: GO:0052922 DONE
name: hexaprenyl diphosphate synthase (geranylgeranyl-diphosphate specific) activity

id: GO:0036422 DONE
name: heptaprenyl diphosphate synthase activity

id: GO:0000010 DONE
name: trans-hexaprenyltranstransferase activity

id: GO:0048045  DONE
name: trans-pentaprenyltranstransferase activity

id: GO:0050347 DONE
name: trans-octaprenyltranstransferase activity

id: GO:0097269 DONE
name: all-trans-decaprenyl-diphosphate synthase activity

id: GO:0052923 DONE
name: all-trans-nonaprenyl-diphosphate synthase (geranyl-diphosphate specific) activity

id: GO:0052924  DONE
name: all-trans-nonaprenyl-diphosphate synthase (geranylgeranyl-diphosphate specific) activity

==  Above Done = part 1

Based on PMID: 12135472 (figure 1), it would be appropriate and useful to add a new grouping term (under 'prenyltransferase activity'), something like "isoprenyl pyrophosphate synthase activity" or "Prenyl diphosphate synthase activity" (see PMID: 26216239), to group these 11 terms, along with 6 others (that are already children of 'prenyltransferase activity'):

id: GO:0004161
name: dimethylallyltranstransferase activity

id: GO:0004337
name: geranyltranstransferase activity

id: GO:0004311
name: farnesyltranstransferase activity

id: GO:0008834
name: di-trans,poly-cis-decaprenylcistransferase activity

id: GO:0045547
name: dehydrodolichyl diphosphate synthase activity

id: GO:0002094
name: polyprenyltransferase activity

I believe the full correspondence between the activities in PMID: 12135472 (figure 1) and the GO terms is:
- GPPS (geranyl pyrophosphate synthase) => dimethylallyltranstransferase activity (GO:0004161)
- trans-FPPS (farnesyl pyrophosphate synthase) => geranyltranstransferase activity (GO:0004337)
- cis-FPPS (farnesyl pyrophosphate synthase) => 2-cis,6-cis-farnesyl pyrophosphate synthase activity (GO:0102059)
- GGPPS (geranylgeranyl pyrophosphate synthase) => farnesyltranstransferase activity (GO:0004311)
- GFPPS (geranylfarnesyl pyrophosphate synthase) => geranylfarnesyl diphosphate synthase activity (GO:0044687)
- HEXPPS (hexaprenyl pyrophosphate synthase) => hexaprenyl-diphosphate synthase ((2E,6E)-farnesyl-diphosphate specific) activity (GO:0036423)
- HEPPPS (heptaprenyl pyrophosphate synthase) => heptaprenyl diphosphate synthase activity (GO:0036422)
- OPPS (octaprenyl pyrophosphate synthase) => not in GO
- SPPS (solanesyl pyrophosphate synthase) => trans-octaprenyltranstransferase activity (GO:0050347)
- trans-DPPS (decaprenyl pyrophosphate synthase) => all-trans-decaprenyl-diphosphate synthase activity (GO:0097269)
- cis-DPPS (decaprenyl pyrophosphate synthase) => not in GO
- UPPS (undecaprenyl pyrophosphate synthase) => di-trans,poly-cis-decaprenylcistransferase activity (GO:0008834)
- DDPPS (dehydrodolichyl pyrophosphate synthase) => dehydrodolichyl diphosphate synthase activity (GO:0045547)
- PPPS (polyprenyl pyrophosphate synthase) => polyprenyltransferase activity (GO:0002094)

**Comment by sjm41** [comment]
Hi @hdrabkin - thanks for tackling this. If I'm right about all these being related activities, it would be useful if the term names (and defs) followed a consistent pattern.
e.g. all referring to 'diphosphate' rather than 'pyrophospate'
e.g. all using 'X diphosphate synthase activity' rather than 'X transferase activity'.
(unless there's a good reason for using these different formats/perspectives....I'm no expert on these activities....)

Also, are the terms that include the string 'transtrans' correct (e.g. "**trans**-hexaprenyl**transtrans**ferase activity", or is that a typo?

**Comment by sjm41** [comment]
Hi @pgaudet 
I've reviewed this old (Jan 2021) ticket after working on #26833. There are a few tasks that I still think are worth doing:

1. Rename certain children under 'prenyltransferase activity' so that the names (and possibly defs) follow the same format, e.g. all named for their 'synthase' (rather than 'transferase') activity, use 'diphosphate' rather then 'pyrophosphate', etc. I could go ahead and do that if that's OK?

2. Make a new grouping class for 'prenyl diphosphate synthase activity':
NAME: prenyl diphosphate synthase activity
SYNONYMS: isoprenyl pyrophosphate synthase activity, IPPS
DEF: Catalysis of the transfer of a prenyl group from a prenyl diphosphate (donor) to isopentenyl diphosphate (IPP) (acceptor). [PMID: 12135472, PMID:26216239]

```
prenyltransferase activity
           |__prenyl diphosphate synthase activity **NTR**
               |__2-cis,6-cis-farnesyl pyrophosphate synthase activity gene [EC:2.5.1.92, RHEA:27810]
               |__all-trans-decaprenyl-diphosphate synthase activity [EC:2.5.1.91, RHEA:27802]
               |__all-trans-nonaprenyl-diphosphate synthase (geranyl-diphosphate specific) activity [EC:2.5.1.84, RHEA:27563]
               |__all-trans-nonaprenyl-diphosphate synthase (geranylgeranyl-diphosphate specific) activity [EC:2.5.1.85, RHEA:27594]
               |__dehydrodolichyl diphosphate synthase activity [EC:2.5.1.87, RHEA:53008]
               |__di-trans,poly-cis-undecaprenyl-diphosphate synthase activity [EC:2.5.1.31, RHEA:27551]
               |__dimethylallylcistransferase activity [EC:2.5.1.28, RHEA:11328]
               |__dimethylallyltranstransferase activity [EC:2.5.1.1, RHEA:22408]
               |__farnesyltranstransferase activity [EC:2.5.1.29, RHEA:17653]
               |__geranylfarnesyl diphosphate synthase activity [EC:2.5.1.81, RHEA:25694]
               |__geranyltranstransferase activity [EC:2.5.1.10, RHEA:19361]
               |__hexaprenyl diphosphate synthase (geranylgeranyl-diphosphate specific) activity [EC:2.5.1.82, RHEA:27555]
               |__hexaprenyl-diphosphate synthase ((2E,6E)-farnesyl-diphosphate specific) activity [EC:2.5.1.83, RHEA:27559]
               |__octaprenyl pyrophosphate synthase activity [EC:2.5.1.90, RHEA:27798]
               |__rubber cis-polyprenylcistransferase activity [EC:2.5.1.20, RHEA:18801]
               |__trans-hexaprenyltranstransferase activity [EC:2.5.1.30, RHEA:27794]
```

3. Obsolete 'polyprenyltransferase activity' ("Catalysis of the transfer of multiple prenyl groups from one compound (donor) to another (acceptor)") - I haven't seen this term used in any publication, it has no reference/xref in GO, and almost all prenyltransferase terms could go under this grouping - I don't think it's useful.

4. Decide how best to manage these two EC:2.5.1.21-related terms:

id: GO:0004310
name: farnesyl-diphosphate farnesyltransferase activity
def: "Catalysis of the reaction: 2 farnesyl diphosphate = diphosphate + presqualene diphosphate." [EC:2.5.1.21]
comment: Note that the two reactions performed by EC:2.5.1.21 are represented in GO by 'farnesyl-diphosphate farnesyltransferase activity ; GO:0004310' and 'squalene synthase activity ; GO:0051996'.
synonym: "farnesyl-diphosphate:farnesyl-diphosphate farnesyltransferase activity" RELATED [EC:2.5.1.21]
synonym: "presqualene synthase activity" RELATED [EC:2.5.1.21]
synonym: "presqualene-diphosphate synthase activity" RELATED [EC:2.5.1.21]
xref: EC:2.5.1.21
xref: MetaCyc:RXN-12263
is_a: GO:0004659 ! prenyltransferase activity

=> This is RHEA:22672, which is mapped to EC 2.5.1.103, though is also a subreaction of RHEA:32295 (EC:2.5.1.21)
=> This it not itself a prenyltransferase reaction.

id: GO:0051996
name: squalene synthase activity
def: "Catalysis of the reaction: presqualene diphosphate + NADPH = squalene + NADP+ + diphosphate." [EC:2.5.1.21]
comment: Note that the two reactions performed by EC:2.5.1.21 are represented in GO by 'farnesyl-diphosphate farnesyltransferase activity ; GO:0004310' and 'squalene synthase activity ; GO:0051996'.
synonym: "squalene synthetase activity" RELATED [EC:2.5.1.21]
xref: EC:2.5.1.21
xref: MetaCyc:RXN66-281
is_a: GO:0004659 ! prenyltransferase activity
created_by: ai
creation_date: 2010-07-16T05:10:24Z

=> This is RHEA:22232, which is mapped to EC:1.3.1.96, though it is also a subreaction of RHEA:32295 (EC:2.5.1.21)

**Comment by sjm41** [comment]
Closed this.
I did everything mentioned above except 'Obsolete 'polyprenyltransferase activity' - I'm still unclear what this represents in GO, but I'm leaving it alone for now.  I see 7 EXP annotations directly to the term, and ~8,000 non-EXP annotations directly to the term.

**Comment by pgaudet** [comment]
Hi @sjm41 
Just to confirm: 

Shouldn't [15-cis-phytoene synthase activity](http://purl.obolibrary.org/obo/GO_0046905) and [chlorophyll synthetase activity](http://purl.obolibrary.org/obo/GO_0046408) also be children of your new grouping term, [prenyl diphosphate synthase activity](http://purl.obolibrary.org/obo/GO_0120531)? 

Although I see that your grouping term specifically refers to isopentenyl diphosphate (acceptor) - is the label too general? 

I also think [polyprenyltransferase activity](http://purl.obolibrary.org/obo/GO_0002094) (no xrefs) ; but many terms in tht branch have no xrefs; we'll need to fix that.  

Thanks, Pascale

**Comment by sjm41** [comment]
But I should add a broadMatch xref to the new grouping term - EC:2.5.1.-

**Comment by sjm41** [comment]
Final arrangement and names after this clean-up, for the record:

```
prenyltransferase activity
           |__prenyl diphosphate synthase activity
               |__(2E,6E)-farnesyl diphosphate synthase activity [EC:2.5.1.10, RHEA:19361]
               |__(2Z,6Z)-farnesyl diphosphate synthase activity [EC:2.5.1.92, RHEA:27810]
               |__all-trans-decaprenyl-diphosphate synthase activity [EC:2.5.1.91, RHEA:27802]
               |__all-trans-nonaprenyl-diphosphate synthase (geranyl-diphosphate specific) activity [EC:2.5.1.84, RHEA:27563]
               |__all-trans-nonaprenyl-diphosphate synthase (geranylgeranyl-diphosphate specific) activity [EC:2.5.1.85, RHEA:27594]
               |__all-trans-octaprenyl-diphosphate synthase activity [EC:2.5.1.90, RHEA:27798]
               |__dimethylallylcistransferase activity [EC:2.5.1.28, RHEA:11328]
               |__dimethylallyltranstransferase activity [EC:2.5.1.1, RHEA:22408]
               |__ditrans,polycis-polyprenyl diphosphate synthase [(2E,6E)-farnesyl diphosphate specific] activity [EC:2.5.1.87, RHEA:53008]
               |__ditrans,polycis-undecaprenyl-diphosphate synthase [(2E,6E)-farnesyl-diphosphate specific] activity [EC:2.5.1.31, RHEA:27551]
               |__geranylfarnesyl diphosphate synthase activity [EC:2.5.1.81, RHEA:25694]
               |__geranylgeranyl diphosphate synthase activity [EC:2.5.1.29, RHEA:17653]
               |__heptaprenyl diphosphate synthase activity [EC:2.5.1.30, RHEA:27794]
               |__hexaprenyl diphosphate synthase (geranylgeranyl-diphosphate specific) activity [EC:2.5.1.82, RHEA:27555]
               |__hexaprenyl-diphosphate synthase ((2E,6E)-farnesyl-diphosphate specific) activity [EC:2.5.1.83, RHEA:27559]
               |__rubber cis-polyprenylcistransferase activity [EC:2.5.1.20, RHEA:18801]
```

**Comment by sjm41** [comment]
Noticed that a few of these prenyl diphosphate synthase activity terms needed their defs updating to match RHEA - I'll fix those now.

**Comment by sjm41** [comment]
Two more edits:

1. Should make these two terms parent-child, like so:
```
|__ditrans,polycis-polyprenyl diphosphate synthase [(2E,6E)-farnesyl diphosphate specific] activity [EC:2.5.1.87, RHEA:53008]
n isopentenyl diphosphate + (2E,6E)-farnesyl diphosphate = a di-trans,poly-cis-polyprenyl diphosphate + n diphosphate
               		|__ditrans,polycis-undecaprenyl-diphosphate synthase [(2E,6E)-farnesyl-diphosphate specific] activity [EC:2.5.1.31, RHEA:27551]
			 8 isopentenyl diphosphate + (2E,6E)-farnesyl diphosphate = di-trans,octa-cis-undecaprenyl diphosphate + 8 diphosphate
```

2. Make def of parent 'prenyl diphosphate synthase activity' term clearer - change from:
"Catalysis of the transfer of a prenyl group from a prenyl diphosphate donor to an isopentenyl diphosphate (acceptor), resulting in chain elongation of allylic diphosphate substrates." [PMID:12135472, PMID:26216239]
to:
"Catalysis of chain elongation of prenyl diphosphate substrates via one or more condensation reactions with isopentenyl diphosphate to generate linear polymers with defined chain lengths"
