### ISSUE TITLE
establishment of endoplasmic reticulum localization involved in endoplasmic reticulum polarization at cell division site

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20666]
GO:0061166 establishment of endoplasmic reticulum localization involved in endoplasmic reticulum polarization at cell division site

I think this is one of my old Term Genie terms.

Could it be merged into to

"endoplasmic reticulum polarization' 

The "establishment of localization" part will come from the "cytoskeleton-membrane anchor" and the location will be an extension.

**Comment by ValWood** [comment]
All EXP annotations are PomBase.

**Comment by pgaudet** [comment]
I also merge 'maintenance of endoplasmic reticulum location involved in endoplasmic reticulum polarization at cell division site '?

**Comment by ValWood** [comment]
I think that would be OK. The only paper which uses this is very old curation, and from a quick glance I don't see separate pathways for establishment and maintenence.

**Comment by pgaudet** [comment]
and the parent GO:0061165 endoplasmic reticulum localization involved in endoplasmic reticulum polarization at cell division site?

**Comment by pgaudet** [comment]
I dont see the difference between:  
* GO:0061164 transitional endoplasmic reticulum polarization at cell division site: The endoplasmic reticulum polarization process that results in the structure being polarized at the site of future cell division. 

and 
 
* GO:0061165 endoplasmic reticulum localization involved in endoplasmic reticulum polarization at cell division site: The process in which endoplasmic reticulum is transiently localized to the site where a cell will divide. 

Also - 
 GO:0007163 establishment or maintenance of cell polarity
is_a  GO:0061163 endoplasmic reticulum polarization 
Is this right ? Shouldn't it have to do with cell polarization for division? 

In any case - I did the 2 merges above, GO:0061165 and GO:0061167 into GO:0061163. Please reopen if you need further changes. 

Thanks, Pascale

**Comment by ValWood** [comment]
agreed, I don't even remember what transitional ER is and it is not mentioned elsewhere. Merge those too. This is really old curation (predates Canto, so over 10 yrs old)

**Comment by ValWood** [comment]
I missed this:

>Also -
GO:0007163 establishment or maintenance of cell polarity
is_a GO:0061163 endoplasmic reticulum polarization
Is this right ? Shouldn't it have to do with cell polarization for division?

Looking at other descendants I think this relation could be added.

**Comment by pgaudet** [comment]
Looking futher into it: 


There are 8 annotations from 3 papers: 
* PMID:25083872: Polarization of the endoplasmic reticulum by ER-septin tethering (2014): "Polarization of the plasma membrane (PM) into domains is an important mechanism to compartmentalize cellular activities and to establish cell polarity" 
* PMID:18184749 The actomyosin ring recruits early secretory compartments to the division site in fission yeast 
* PMID:23864681 Shootin1 acts in concert with KIF20B to promote polarization of migrating neurons -> I dont' see a mention of endoplasmic reticulum in this paper

Proposed structure: 
- [ ] Widen definition of GO:0001766 membrane raft polarization ->  from "The clustering and aggregation of membrane rafts at a single cellular pole during activation of particular cell types, such as lymphocytes." to "The clustering and aggregation of a membrane into domains. This serves as a mechanism to compartmentalize cellular activities and to establish cell polarity. "
- [ ] add synonym 'membrane polarization'
- [ ] NTR: endoplasmic reticulum membrane polarization: def: The clustering and aggregation of an endoplasmic reticulum membrane into domains. This serves as a mechanism to compartmentalize cellular activities and to establish cell polarity. 
- [ ] Widen definition of GO:0044858 plasma membrane raft polarization to "The clustering and aggregation of a plasma membrane into domains. This serves as a mechanism to compartmentalize cellular activities and to establish cell polarity." 
- [ ] Add syn: plasma membrane polarization: def: 
- [ ] Merge the 5 similar terms: into GO:0061163 
- GO:0061163	'endoplasmic reticulum polarization' -> 4 EXP
- GO:0061165	'endoplasmic reticulum localization involved in endoplasmic reticulum polarization at cell division site'  -> 0 EXP
- GO:0061164	'transitional endoplasmic reticulum polarization at cell division site' -> 1 EXP
- GO:0061167	'maintenance of endoplasmic reticulum location involved in endoplasmic reticulum polarization at cell division site'  -> 1 EXP
- GO:0061166	'establishment of endoplasmic reticulum localization involved in endoplasmic reticulum polarization at cell division site'  -> 2 EXP
- [ ] change label to 'endoplasmic reticulum membrane polarization involved in endoplasmic reticulum diffusion barrier formation at cell division site' (PMID:25083872)
- [ ] Move under NTR: endoplasmic reticulum membrane polarization + part_of 
- [ ] obsolete GO:0003424 establishment of cell polarity involved in growth plate cartilage chondrocyte division
-> too specific and not used. 







NTR: cell polarization by endoplasmic reticulum membrane polarization



SGD:S000000922	Integral ER membrane protein, regulates phospholipid metabolism		GO:0061163		SGD	NCBITaxon:559292	IDA		PANTHER:PTHR10809	protein		PMID:25083872	20140812
SGD:S000004731	Protein involved in septin-ER tethering		GO:0061163		SGD	NCBITaxon:559292	IDA			protein		PMID:25083872	20140812
SGD:S000002384	Component of the septin ring that is required for cytokinesis		GO:0061163		SGD	NCBITaxon:559292	IDA		PANTHER:PTHR18884	protein		PMID:25083872	20140812
PomBase:SPAC1565.08	AAA family ATPase involved in ubiquitin-mediated protein degradation Cdc48		GO:0061166		PomBase	NCBITaxon:4896	IMP		PANTHER:PTHR23077	protein		PMID:18184749	20100305
PomBase:SPAC24B11.11c	NDR kinase Sid2		GO:0061167		PomBase	NCBITaxon:4896	IMP		PANTHER:PTHR24356	protein		PMID:18184749	20100305
PomBase:SPAC20G8.05c	F-BAR domain protein Cdc15		GO:0061166		PomBase	NCBITaxon:4896	IMP		PANTHER:PTHR23065	protein		PMID:18184749	20100305
MGI:MGI:1918903	shootin 1		GO:0061163		UniProt	NCBITaxon:10090	IMP		PANTHER:PTHR46606	protein		MGI:MGI:5505333|PMID:23864681	20150626
PomBase:SPAC1F5.04c	formin Cdc12		GO:0061164		PomBase	NCBITaxon:4896	IMP		PANTHER:PTHR47102	protein		PMID:18184749	20100305

**Comment by pgaudet** [comment]
@ValWood Is this OK with you ?

**Comment by ValWood** [comment]
It looks OK (I think). 

I didn't understand this one:

 change label to 'endoplasmic reticulum membrane polarization involved in endoplasmic reticulum diffusion barrier formation at cell division site' (PMID:25083872)

We want to get rid of "blah involved in blah"
and I wouldn't create a term that mentions "diffusion barrier formation" because that is just describing a membrane.

**Comment by pgaudet** [comment]
Hi @ValWood thanks for the comments. I did the items that I marked; I am not sure about those I crossed out.  

- Does 'endoplasmic reticulum polarization' exist ? Or is it the same as endoplasmic reticulum **membrane** polarization'? 
- (whether they are the same or not leads to other questions - 
- -- is  'endoplasmic reticulum polarization' an endoplasmic reticulum organization? or does it serve to partition the cell - ie in that context it doesn't primarily function as an ER ? Otherwise is it OK to have 'endoplasmic reticulum (membrane) polarization under 'establishment of cell polarity'? 
- The whole process seems to have to do with cell polarization. I dont like having 'x involved in y' either, but it seems the process encompasses both aspects. 
What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
1.
well I prefer ER polarization, because the entire ER is polarized, not just the membrane.
The membrane is polarized as a result of the ER polarization:
https://www.pombase.org/reference/PMID:18184749

2. 
As defined "ER polarization" is an "ER organization"
Definition 
The endoplasmic reticulum organization process that results in the structure of the endoplasmic reticulum being oriented in the cell.

3.
>The whole process seems to have to do with cell polarization. I dont like having 'x involved in y' either, but it seems the process encompasses both aspects.

which 2 aspects?

You are correct we do need them sometimes to link to 2 process parents, but where do we still need  the "involved in" terms,  I thought we had removed them all. Can you list the remaining?

**Comment by pgaudet** [comment]
OK thanks. 

So, as things stand now we have lost all link between ER polarization and cell polarization, and in the definition. 
 * GO:0061163 'endoplasmic reticulum polarization', def: The endoplasmic reticulum organization process that results in the structure of the endoplasmic reticulum being oriented in the cell. 

* However the terms GO:0001766 membrane raft polarization (and GO:0044858 plasma membrane raft polarization) now have this def: "The clustering and aggregation of a membrane into domains. This serves as a mechanism to compartmentalize cellular activities and to establish cell polarity. "
* From what I have read, the ER polarization also serves "as a mechanism to compartmentalize cellular activities and to establish cell polarity"; should I add that to the def ? Or maybe this is not always the case?

Thanks, Pascale

**Comment by ValWood** [comment]
> From what I have read, the ER polarization also serves "as a mechanism to compartmentalize cellular activities and to establish cell polarity"; should I add that to the def ? Or maybe this is not always the case?

I think that is always true, since cell polarization is  the introduction of asymmetry and can apply to components, that part is true and it does serve as a mechanism to compartmentalize membrane domains.

**Comment by pgaudet** [comment]
OK, so I've added that bit to the definition of ER polarization. 

Thanks! 

Pascale
