### ISSUE TITLE
Cardiac conduction term revisions required

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#20671]
Hi David

I have a student (Chloe, CC'd) currently annotating proteins involved in the development of the cardiac conduction system and I now realise that there is a bit of a problem with some of these terms. The problem stems from the fact that the various parts of the conduction system are not single cells but multiple cells. 

Therefore terms such as: bundle of His cell to Purkinje myocyte communication are misleading because there is cell to cell communication going on between the bundle of His cells and then this signal is transferred to the Purkinje cells. You could argue that this term is fine because at some point a His cell is directly communicating with a Purkinje myocyte. However, it is very difficult (and I don't think we have to date found) to demonstrate that the signal is coming from a bundle of his cell to a Purkinje cell. There is data that does show that if a specific gap junction protein (for example) is missing then the signal is blocked in the right bundle branch. This would indicate that cell-cell communication within the right bundle branch and between the right bundle branch and the Purkinje fibers is not occuring, ie that gap junction protein is required for this signal.

So I was thinking that maybe we could revise the names and definitions of these terms. My suggestion I believe will make the terms more general and therefore it might be an acceptable revision, rather than requiring curators to revise all their annotations and delete these terms, what do you think?

Current term GO:0086069 bundle of His cell to Purkinje myocyte communication
Revised term: GO:0086069 bundle of His to Purkinje fiber communication

Current Definition (I have highlighed in bold the text that would need to change):
The process that mediates interactions between a bundle of His cell and its surroundings that contributes to the process of the bundle of His **cell** communicating with a Purkinje **myocyte** in cardiac conduction. Encompasses interactions such as signaling or attachment between one cell and another cell, between a cell and an extracellular matrix, or between a cell and any other aspect of its environment. 

Revised Definition:
The process that mediates interactions between a bundle of His cell and its surroundings that contributes to the process of the bundle of His communicating with a Purkinje fiber in cardiac conduction. Encompasses interactions such as signaling or attachment between one cell and another cell, between a cell and an extracellular matrix, or between a cell and any other aspect of its environment. 

There are more terms that would need to be revised but I thought I would check that you agree with this suggestion before a launch into this.

Best

Ruth

@ckyli

**Comment by ukemi** [comment]
HI @RLovering. My main concern here is that we add another 'level' of granularity to the ontology. I'm pretty sure that after consulting with the experts, we had decided that the communication would be at the level of the cells. This way we can create precise statements about how and where the gene products act on a cellular level. These processes of course could then be put into the context of anatomy. IIRC the experts were interested in knowing about about communication between the cells in the different anatomical structures that make up the cardiac conduction system. If you want to express communication between a homogeneous group of cells in a given structure, can't you make an annotation to cell communication that occurs_in that structure? But again, I really think what you want is what is happening between cells. So communication across the Bundle of His would be 'cell communication' occurs_in Bundle of His. If the ontology is changed as you suggest above, it would reflect communication at the level of the anatomical structures. I think you would still have to eventually drill down to the level of the cells when you start trying to capture the individual channels involved in electrical coupling, cell adhesion and molecules involved in signaling. Changing the terms as you suggest above would necessarily change the entire structure of the ontology where all of these terms would now have to have new parents that are not cell communication.

**Comment by RLovering** [comment]
Thanks David
I will follow your advice and close this ticket
Best
Ruth
