### ISSUE TITLE
Query GO:0050444 aquacobalamin reductase (NADPH) activity and GO:0047138 aquacobalamin reductase activity have obsolete EC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20679]
Dear all, 

The proposal has been made to obsolete:  
GO:0050444 aquacobalamin reductase (NADPH) activity (EC:1.16.1.5) and 
 GO:0047138 aquacobalamin reductase activity ((EC:1.16.1.3)
as they are obsolete in EC.  

- GO:0050444 has 1 EXP by CACAO
-  - is mapped to RHEA:20752 - linked to Q9UBK8 Methionine synthase reductase, MSR, EC:1.16.1.8 
- - In GO EC:1.16.1.8 is linked to  GO:0030586 [methionine synthase] reductase activity (RHEA:23910)
- - and to https://biocyc.org/META/NEW-IMAGE?type=NIL&object=AQUACOBALAMIN-REDUCTASE-NADPH-RXN (link does not resolve)
- GO:0047138 has no manual annotations. 

@amorgat @kaxelsen @keseler Do these reactions exist ? 
Thanks, Pascale

**Comment by kaxelsen** [comment]
It is correct that EC 1.16.1.3 and EC 1.6.1.5 have been deleted.
RHEA:20752 still exists. It was linked to EC 1.16.1.5. The corresponding reactions in MetaCyc and KEGG have been deleted together with the EC number, but Rhea is still discussing what to do about it.

**Comment by pgaudet** [comment]
Thanks @kaxelsen 
If this is a spontaneous reaction this is outside the scope of GO, so I will obsolete it. 

Thanks, Pascale

**Comment by keseler** [comment]
I asked my colleague, Ron Caspi, who may have been the instigator of deleting these EC entries.  Here are his notes, shared with his permission:

EC 1.16.1.5 :   There is no justification for this entry. The enzyme described by Watanabe (sole two references) was later found to be EC 1.2.1.51, Pyruvate dehydrogenase (NADP(+)) (see PMID  8373179). No one else found this activity, and there are no entries in UniProt. On the other hand, in PMID 10894741, Reduction of cob(III)alamin to cob(II)alamin in Salmonella enterica serovar typhimurium LT2, the authors show clearly that this reaction happens very efficiently in the absence of any enzymes, with either free dihydroflavins or non-specific reduced flavoproteins.

EC 1.16.1.3 :   There is no justification for this entry. The sole reference does not describe an enzyme. Rather, they observed the activity in extracts, and linked it to an unidentified flavoprotein. In PMID 10894741, Reduction of Cob(III)alamin to Cob(II)alamin in Salmonella enterica serovar typhimurium LT2, the authors show clearly that this reaction happens very efficiently with either free dihydroflavins or non-specific reduced flavoproteins, with no need for enzymes.

Also, Ron pointed out that some explanation is provided on the EC website, e.g.
https://www.enzyme-database.org/query.php?ec=1.16.1.5

So based on this, obsoletion of the GO terms seems warranted.

-Ingrid

**Comment by pgaudet** [comment]
Thanks @keseler !

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0050444 aquacobalamin reductase (NADPH) activity and GO:0047138 aquacobalamin reductase activity. The reason for obsoletion is that those terms represent spontaneous reactions which is outside the scope of GO. 
 * GO:0050444 has
 * * 1 EXP by CACAO
 * * link to https://biocyc.org/META/NEW-IMAGE?type=NIL&object=AQUACOBALAMIN-REDUCTASE-NADPH-RXN
 * * links to obsolete EC and spontaneous RHEA. 
 *  * Comment in obsolete 1.16.1.5: "This entry has been deleted since the enzyme the entry was based on was later shown to be EC 1.2.1.51, pyruvate dehydrogenase (NADP+). On the other hand, it has been shown that non-enzymatic reduction of cob(III)alamin to cob(II)alamin occurs efficiently in the presence of free dihydroflavins or non-specific reduced flavoproteins." (https://www.enzyme-database.org/query.php?ec=1.16.1.5)
 * GO:0047138 has 
 * * No manual annotations
 * * link to https://biocyc.org/META/NEW-IMAGE?type=NIL&object=1.6.99.12-RXN which corresponds to GO:0033787
 * * link to obsolete EC and RHEA:24472

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/20679

Thanks, Pascale

**Comment by pgaudet** [comment]
Email comment from @mah11 

> 
Hi Pascale (& other GO eds),

>A word of caution on this point ...

>>The reason for obsoletion is that those terms represent spontaneous 
reactions which is outside the scope of GO.

>If there's nothing of biological origin known to catalyze the 
"aquacobalamin reductase" activity, then I have no objection to the 
specific obsoletions proposed here.

>But more generally, the fact that a reaction *can* occur spontaneously is 
not by itself evidence that there is no gene product capable of catalyzing 
it (i.e. speeding it up/increasing its occurrence by lowering the 
activation energy barrier). There's an anecdote to this effect from Arthur 
Kornberg; I stuck it in

>https://github.com/geneontology/go-ontology/issues/12539#issuecomment-232912713

>So it would be a better GO guideline, and better obsoletion-reason comment 
for GO:0047138 and GO:0050444, to say "not known to be catalyzed by any 
gene product".

>cheers,
Midori
