### ISSUE TITLE
NTR: oxidoreductase activity, reducing metal ions

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#20675]
Hi, 
according to PMID:14499595, CYBRD1 is a ferrireductase but the electron donor is unknown. We therefore need a term similar to GO:0016722 'oxidoreductase activity, oxidizing metal ions' but that describes the opposite reaction, ie the reduction of the metal ions.
Best, Lionel

**Comment by pgaudet** [comment]
- New term: 
+[Term]
+id: GO:0140579
+name: oxidoreductase activity, reducing metal ions
+namespace: molecular_function
+def: "Catalysis of an oxidation-reduction in which the metal ion is reduced." [PMID:14499595]
+is_a: GO:0016722 ! oxidoreductase activity, acting on metal ions
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20675 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-13T06:55:01Z

Also, after discussion with @lbreuza, made the following changes: 

- GO:0004322 ferroxidase activity
- - Changed RHEA xref to the directional relation: from RHEA:11148 to RHEA:11149
- GO:0016722 oxidoreductase activity, oxidizing metal ions
- - Changed label to 'oxidoreductase activity, **acting** on metal ions' (EC:1.16.-.-) :  this is more consistent with other general oxidoreductases classes. Also, while the oxidation reactions are in theory reciprocal, when the substrate that gets oxidized or reduced is mentioned, this implies a directionality. This way the term is agnostic WRT the direction of the reaction, and consistent with its definition ("Catalysis of an oxidation-reduction in which the oxidation state of metal ion is altered."). 
-  GO:0043783 oxidoreductase activity, oxidizing metal ions with flavin as acceptor
- - - Changed label to 'oxidoreductase activity, *reducing* metal ions with flavin as acceptor
-  GO:0016723 oxidoreductase activity, oxidizing metal ions, NAD or NADP as acceptor 
- - - Changed label to 'oxidoreductase activity, *reducing* metal ions, NAD or NADP as acceptor 
to match children terms labels.
