### ISSUE TITLE
Merge GO:0001148 bacterial-type RNA polymerase termination site sequence-specific DNA binding (was obsolete)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20686]
Hello, 

Bacterial transcription termination takes place via 3 mechanisms, according to  PMID: 30978344 and other similar recent reviews: 

- intrinsic termination, an activity only of the core RNAP enzyme and transcript sequences that encode an RNA
hairpin and terminal uridine-rich segment; 
- termination by the enzyme Rho, an ATP-dependent RNA
translocase that releases RNA by forcing uncharacterized structural changes in the elongating complex; and
- Mfd-dependent termination, the activity of an ATP-dependent DNA translocase that is thought to dissociate
the elongation complex by exerting torque on a stalled RNAP

None of those processes imply binding to the promoter DNA. Therefore I will obsolete GO:0001148 bacterial-type RNA polymerase termination site sequence-specific DNA binding. 

There are no annotations, no mappings, this term is not present in any subsets. 

@AndreaAuchincloss 
@keseler 

Any comments ? 

Thanks, Pascale

**Comment by ukemi** [comment]
mitochondrial TERFs?

**Comment by pgaudet** [comment]
What about mitochondrial TERFs ? Can you be more specific ?

**Comment by krchristie** [comment]
At the time I created this term, I was under the impression that there was evidence for this type of termination, though it is rare. The review you cite seems to focus primarily on E. coli, so it might not cover a mechanism that doesn't exist in E. coli.

Also, regarding your comment:

> None of those processes imply binding to the promoter DNA. Therefore I will obsolete GO:0001148 bacterial-type RNA polymerase termination site sequence-specific DNA binding.

What does binding to promoter DNA have to do with this term? The definition of this term only talks about binding to DNA that is a terminator, not a promoter, and it's placement in the ontology is consistent with binding to a terminator sequence.

> Def: Interacting selectively and non-covalently with a sequence of DNA that is a terminator for bacterial-type RNA polymerase.

**Comment by ukemi** [comment]
Don't mitochondrial and plastid TERFs bind the termination site and are involved in termination? PMID:23087700

**Comment by ukemi** [comment]
@krchristie IIRC we decided to lump the organelle polymerases in with bacterial. That's why we have bacterial-like.

**Comment by pgaudet** [comment]
> Don't mitochondrial and plastid TERFs bind the termination site and are involved in termination? PMID:23087700

this term is 'bacterial', so we would not be able to apply it, or would you use 'bacterial-type' for mitochondrial and plastid TERFs ? In any event this term has not been used. 

Also, PMC2095818 states "The mammalian mitochondrial transcription termination factor mTERF binds with high affinity to a site within the tRNALeu(UUR) gene and regulates the amount of read through transcription from the ribosomal DNA into the remaining genes of the major coding strand of mitochondrial DNA (mtDNA). "

**Comment by pgaudet** [comment]
> What does binding to promoter DNA have to do with this term? 

You're right, I was concerned about *DNA* binding, the promoter part was not relevant. 

Thanks for the precision. I also asked Andrea, Ingrid, Julio and Ivan for input. 

Pascale

**Comment by krchristie** [comment]
> @krchristie IIRC we decided to lump the organelle polymerases in with bacterial. That's why we have bacterial-like.

Yes, SOME of the organellar RNA polymerases are structurally of the bacterial-type, i.e. alpha2 beta beta' subunit composition with a sigma subunit for promoter specificity. The plant plastid polymerases, e.g. PEP-A and PEP-B, are of this type. 

Note that mitochondrial RNA polymerases are a single subunit RNA polymerase with similarity to a specific bacteriophage (I forget whether it's T4 or a different one), not a bacterial-type multi-subunit RNA polymerase.

**Comment by krchristie** [comment]
> > Don't mitochondrial and plastid TERFs bind the termination site and are involved in termination? PMID:23087700
> 
> this term is 'bacterial', so we would not be able to apply it, or would you use 'bacterial-type' for mitochondrial and plastid TERFs ? In any event this term has not been used.

Many plant plastid RNA polymerases are bacterial-type. I believe that there may also be a single subunit RNA polymerase in plastids, but those are not in scope for this term. 

The absence of usage of a term is not in itself evidence of the absence of the existence of the process.
 
> Also, PMC2095818 states "The mammalian mitochondrial transcription termination factor mTERF binds with high affinity to a site within the tRNALeu(UUR) gene and regulates the amount of read through transcription from the ribosomal DNA into the remaining genes of the major coding strand of mitochondrial DNA (mtDNA). "

This statement about mitochondrial termination factor is not relevant to this term about bacterial-type termination.

**Comment by pgaudet** [comment]
Thanks for the feedback, this is very useful. 

Discussing with @colinlog and @RLovering we discovered that we had missed the mitochondrial term: 

- GO:0001147 transcription termination site sequence-specific DNA binding
- -  GO:0001148 bacterial-type RNA polymerase termination site sequence-specific DNA binding
- -  GO:0001145 mitochondrial RNA polymerase termination site sequence-specific DNA binding 

The GO:0001148  and GO:0001145 have no annotations. We propose to merge both terms into GO:0001147 and keep the transcription termination type (bacterial-type, mitochondrial) as BP: 
-  GO:0006393 termination of mitochondrial transcription
-  GO:0006363 termination of RNA polymerase I transcription
- GO:0006369 termination of RNA polymerase II transcription
-  GO:0006386 termination of RNA polymerase III transcription
- GO:0001125 transcription termination from bacterial-type RNA polymerase promoter

Does that seem a better solution ? 

Thanks, Pascale

**Comment by AndreaAuchincloss** [comment]
This seems okay to me, but I've not done any transcription termination annotation that I can remember in years.

You'd then put plastid transcription termination by PEP in 
GO:0001125 "transcription termination from bacterial-type RNA polymerase promoter" as well? Why does this term name have "promoter" in it? Wouldn't "transcription termination of bacterial-type RNA polymerase" be more appropriate?

There are other RNA polymerases in plant organelles (plastids and mitochondria), they are "phage and mitochondrial-type" RNA polymerases but I don't know they terminate transcription.

**Comment by pgaudet** [comment]
> You'd then put plastid transcription termination by PEP in
GO:0001125 "transcription termination from bacterial-type RNA polymerase promoter" as well? 

If we dont change anything in that branch, yes, but I think we also need to look at the BP branch. As I mentioned in the initial comment  (https://github.com/geneontology/go-ontology/issues/20686#issue-785210191) there are at least three pathways for termination in eukaryotes, and indeed we need to look at bacterial and organellar termination, maybe the terms can be improved, instead of being sensu-centric. 

Thanks, Pascale

**Comment by krchristie** [comment]
> Thanks for the feedback, this is very useful.
> 
> Discussing with @colinlog and @RLovering we discovered that we had missed the mitochondrial term:
> 
>     * GO:0001147 transcription termination site sequence-specific DNA binding 
>     * * GO:0001148 bacterial-type RNA polymerase termination site sequence-specific DNA binding
>     * * GO:0001145 mitochondrial RNA polymerase termination site sequence-specific DNA binding
> 
> The GO:0001148 and GO:0001145 have no annotations. We propose to merge both terms into GO:0001147 

I'm OK with this.

> and keep the transcription termination type (bacterial-type, mitochondrial) as BP:
> 
>     * GO:0006393 termination of mitochondrial transcription 
>     * GO:0006363 termination of RNA polymerase I transcription 
>     * GO:0006369 termination of RNA polymerase II transcription 
>     * GO:0006386 termination of RNA polymerase III transcription 
>     * GO:0001125 transcription termination from bacterial-type RNA polymerase promoter

I agree with @AndreaAuchincloss that it's quite odd to have the word "promoter" in the term name of the bacterial-type termination term. I think it would be better to have the names of all of these termination terms be structured in the same way, so I suggest modifying the names of GO:0006393 and GO:0001125 like this:

* GO:0006393 termination of mitochondrial **_RNA polymerase_** transcription 
* GO:0006363 termination of RNA polymerase I transcription 
* GO:0006369 termination of RNA polymerase II transcription 
* GO:0006386 termination of RNA polymerase III transcription 
* GO:0001125 **_termination of bacterial-type RNA polymerase transcription_**

It would also be good to have synonyms for the GO:0001125 term that help people identify that this is for eubacterial RNAP and also the plastid RNAP's such as PEP-A and -B that are structurally related to the eubacterial enzyme. 
 

> Does that seem a better solution ?
> 
> Thanks, Pascale

This would work for me.

Thanks, Karen

**Comment by keseler** [comment]
Sorry for the late reply; Rho is a can of worms I have tried to avoid opening...  But taking a tiny peek, the above solution works for me, too.

Cheers,
Ingrid
