### ISSUE TITLE
Protein aminylation

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#20685]
Hi GO,

I would need a bunch of new terms for a series of PTMs mediated by TGM2 (UniProtKB P21980)

Thanks

Sylvain

1)
Name: Peptide-glutamine serotonylation
Category: Process
Definition: The serotonylation of a glutamine residue in a protein. Serotonin (5-hydroxytryptamine) is a monoamine neurotransmitter occurring in the peripheral and central nervous systems, also having hormonal properties.
child of GO:0043543 protein acylation
PMID:14697203

2)
Name: Peptide serotonyltransferase activity
Category: Function
Definition: Catalysis of the reaction: L-glutaminyl-[protein] + serotonin = 5-serotonyl-L-glutamyl-[protein] + NH4(+) 
child of GO:0016410 N-acyltransferase activity
PMID:14697203
Rhea:66552

3)
Name: histone serotonyltransferase activity
Category: Function
Definition: Catalysis of the reaction: L-glutaminyl-[histone] + serotonin = 5-serotonyl-L-glutamyl-[histone] + NH4(+) 
child of Peptide serotonyltransferase activity
PMID:30867594

4)
Name: Peptide-glutamine dopaminylation
Category: Process
Definition: The dopaminylation of a glutamine residue in a protein. Dopamine is a monoamine neurotransmitter.
child of GO:0043543 protein acylation
PMID:22858378
PMID:32273471

5)
Name: Peptide dopaminyltransferase activity
Category: Function
Definition: Catalysis of the reaction: dopamine + L-glutaminyl-[protein] = 5-dopaminyl-L-glutamyl-[protein] + NH4(+)
child of GO:0016410 N-acyltransferase activity
PMID:22858378
PMID:32273471
Rhea:66556

6)
Name: histone dopaminyltransferase activity
Category: Function
Definition: Catalysis of the reaction: dopamine + L-glutaminyl-[histone] = 5-dopaminyl-L-glutamyl-[histone] + NH4(+)
child of Peptide dopaminyltransferase activity
PMID:32273471

7)
Name: Peptide-glutamine noradrenalinylation
Category: Process
Definition: The noradrenalinylation of a glutamine residue in a protein. Noradrenaline is a monoamine neurotransmitter.
child of GO:0043543 protein acylation
PMID:22858378

8)
Name: Peptide noradrenalinyltransferase activity
Category: Function
Definition: Catalysis of the reaction: (R)-noradrenaline + L-glutaminyl-[protein] = 5-(R)-noradrenalinyl-L-glutamyl-[protein] + NH4(+)
child of GO:0016410 N-acyltransferase activity
PMID:22858378
Rhea:66560

9)
Name: Peptide-glutamine histaminylation
Category: Process
Definition: The histaminylation of a glutamine residue in a protein.
child of GO:0043543 protein acylation
PMID:23022564
PMID:23797785

10)
Name: Peptide histaminyltransferase activity
Category: Function
Definition: Catalysis of the reaction: histamine + L-glutaminyl-[protein] = 5-histaminyl-L-glutamyl-[protein]
child of GO:0016410 N-acyltransferase activity
PMID:23022564
PMID:23797785
Rhea:66564

**Comment by pgaudet** [comment]
I am just unsure about creating the processes. I think we have decided to get rid of those single step processes, in favor of something more biologically informative such as 'protein modification' or 'protein maturation'. 

So @krchristie please go ahead and create the MF terms, and let's confirm the BP's on the next ontology call. 

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet - This is an annotation week for me, so I won't start this till next week anyway. I've added the editors-discussion label and set it to the Next call status in the Weekly meetings project.

**Comment by pgaudet** [comment]
Sure OK. Just a reminder that next week there is no ontology call.

**Comment by sylvainpoux** [comment]
Hi,

then I take the opportunity to request another pair of terms

Thanks

Sylvain

11.
Name: Peptide lactyltransferase activity
Category: Function
Definition: Catalysis of the reaction: (L-lysyl-[protein] + lactoyl-CoA = CoA + H(+) + N(6)-lactoyl-L-lysyl-[protein]
child of GO:0016410 N-acyltransferase activity
PMID:31645732
Rhea:61997

12.
Name: Histone lactyltransferase activity
Category: Function
Definition: Catalysis of the reaction: (L-lysyl-[histone] + lactoyl-CoA = CoA + H(+) + N(6)-lactoyl-L-lysyl-[histone]
child of GO:0016410 N-acyltransferase activity
PMID:31645732

**Comment by krchristie** [comment]
> Sure OK. Just a reminder that next week there is no ontology call.

@pgaudet - Thanks for the reminder. I can work on the function terms next week without needing to wait for a decision on process terms.

**Comment by pgaudet** [comment]
Discussion at ontology ticket jamboree - 
- we should be able to find a MF term for non-catalytic activities - for eg substrate adaptor activity & children: 
- - how granular do we want to be ? we need to have general guidelines on that (more widely than just enzyme adaptors; also binding, inhibitors, activators..... )
- guidelines for BP:

**Comment by pgaudet** [comment]
Checked with @sylvainpoux - for those papers/proteins, he doesn't need other MFs.
