### ISSUE TITLE
Typos in def of GO_0005903 brush border

### ISSUE THREAD

**Issue by paola-scibite** [geneontology/go-ontology#20681]
GO_0005903 brush border 
"The dense covering of microvilli on the apical surface of _a epithelial cells_ in tissues such as the intestine, kidney, and choroid plexus; the microvilli aid absorption by increasing the surface area of the cell."
should read
"...on the apical surface of _an epithelial cell_ ..."
Thanks,
Paola

**Comment by krchristie** [comment]
Thanks for reporting this @paola-scibite
