### ISSUE TITLE
Question EC 1.16.-.-

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20682]
Hi @kaxelsen 

What is it that for all other oxidase (EC 1.1.-.-, EC 1.2.-.-, etc ) the description in EC is 'oxidoreductase activity, acting on x', while for EC 1.16.-.-, it is 'oxidoreductase activity, **oxidizing** x' ? 

This is confusing because that class contains both oxidases and reductases. Is there a reason the descriptions are different from the other EC 1. grouping classes ? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
I don't think so but since these class descriptions were made long before I became involved (maybe even before I was born) I don't know.

**Comment by pgaudet** [comment]
Sounds good. Do you think they can be changed ? I will change them in GO, it only creates confusion, and I has started to create grouping classes to address it, but perhaps that's not the right approach (see #20675), I was thinking to revert that and fix the existing grouping terms to 'acting on metal ions' rather than 'oxidizing'. 

What do you think ?

**Comment by pgaudet** [comment]
OK, thanks !

**Comment by pgaudet** [comment]
Changed labels, and obsoleted 

GO:0140579
-name: oxidoreductase activity, reducing metal ions
+name: obsolete oxidoreductase activity, reducing metal ions
 namespace: molecular_function
-def: "Catalysis of an oxidation-reduction in which the metal ion is reduced." [PMID:14499595]
-is_a: GO:0016722 ! oxidoreductase activity, acting on metal ions
+def: "OBSOLETE. Catalysis of an oxidation-reduction in which the metal ion is reduced." [PMID:14499595]
+comment: This term was obsoleted because it is an unnecessary grouping class.
 property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20675 xsd:anyURI
+is_obsolete: true
+consider: GO:0016722
