### ISSUE TITLE
Rhea and EC xrefs for lipoate-protein ligase & lipoyltransferase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20691]
Hi harold,

You may well have these in hand, but I just stumbled across these missing xrefs:

**lipoate-protein ligase activity (GO:0016979)**
+ EC 6.3.1.20
+ RHEA:49288

**lipoyltransferase activity (GO:0017118)**
+ RHEA:20473

**Comment by hdrabkin** [comment]
Thanks; added.  No surprise for 17118 as there were no existing xrefs to hook ...
