### ISSUE TITLE
P-type ATPase Cu(+) transporter activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#20699]
Dear GO curators,

Would it be possible to create
new_GO: P-type ATPase Cu(+) transporter activity; EC=7.2.2.8; [Rhea:25792]; PMID:10419525
as child of GO:0060003  copper ion export

Definition:
Enables the transfer of a solute or solutes from one side of a membrane to the other according 
to the reaction:  ATP + Cu(+)(in) + H2O = ADP + Cu(+)(out) + H(+) + phosphate [Rhea:25792]

review to cite: PMID:19824702

Many thanks for your help,

Nevila Hyka-Nouspikel

**Comment by pgaudet** [comment]
Hi @nnouspikel 

I created the term as follows: 

 
+[Term]
+id: GO:0140581
+name: P-type monovalent copper transporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Cu+(in) -> ADP + phosphate + Cu+(out)." [RHEA:25792]
+comment: Note that this enzyme transports Cu(+) or Ag(+), and cannot transport the divalent ions, contrary to EC:7.2.2.9, which mainly transports the divalent copper ion (source: EC:7.2.2.8).
+xref: EC:7.2.2.8
+xref: RHEA:25792
+intersection_of: GO:0140358 ! P-type transmembrane transporter activity
+intersection_of: transports_or_maintains_localization_of CHEBI:49552 ! copper(1+)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20699 xsd:anyURI
+created_by: pg
+creation_date: 2021-01-18T11:15:13Z

I used a different term label to distinguish from 'P-type divalent copper transporter activity'. 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Thank you Pascale.

**Comment by ukemi** [comment]
Need to make sure there is not a GCI in place for Cu+ and Cu+2.

**Comment by pgaudet** [comment]
I have created the term both terms have LD with the different ion, and there is no term equivalence error, so I assume it is right ?
