### ISSUE TITLE
GO:0030010  establishment or maintenance of bipolar cell polarity regulating cell shape

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20698]
should GO:0030010 | establishment of cell polarity 
be an ancestor of 
~GO:0030010~ GO:0061245  establishment or maintenance of bipolar cell polarity regulating cell shape

(It isn't currently)

**Comment by mah11** [comment]
It can't be, because the "or maintenance" makes GO:0061245 broader (along one classification axis) than GO:0030010.

**Comment by ValWood** [comment]
oh yes. I wonder if we can be more specific. I'll check.
