### ISSUE TITLE
Vacuole inheritance  

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20697]
Vacuole inheritance please add taxon restriction for fission yeast.
There is no active mechanism for vacuole inheritance in fission yeast (in budding yeast it is a microtubule-dependent process as vacuoles need to be moved into the bud)

**Comment by ValWood** [comment]
Also the complex involved in this process
GO:0071563 Myo2p-Vac17p-Vac8p transport complex

**Comment by ValWood** [comment]
PMID:19643199
The dynamin-related protein Vps1 regulates vacuole fission, fusion and tubulation in the fission yeast, Schizosaccharomyces pombe.
First, vacuole segregation at cell division appears to be by a simple partition mechanism. By contrast, vacuolar elements in budding yeast are actively transported from mother cell to the bud by an actomyosin-based mechanism (Weisman, 2006). 

This was 2009, but since then no evidence for any other mechanism than random partitioning (similar to mitochondria-  (although the fragmentation  in mitosis is probably to increase the likelihood of some vacuoles in each new cell)

**Comment by pgaudet** [comment]
Are you saying this process does not exist ? 

There are 27 SGD and 9 CGD EXP annotations. 

@srengel @marekskrzypek

**Comment by ValWood** [comment]
No, I'm saying it does not apply to fission yeast which doesn't need it because it doesn't divide by budding.

**Comment by pgaudet** [comment]
OK, thanks for the clarification.
