### ISSUE TITLE
Xrefs for lipoate-protein ligase & lipoyltransferase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20692]
Hi harold,

You may well have these in hand, but I just stumbled across these missing xrefs:

**lipoate-protein ligase activity (GO:0016979)**
+ EC 6.3.1.20
+ RHEA:49288

**lipoyltransferase activity (GO:0017118)**
+ RHEA:20473

**Comment by hdrabkin** [comment]
Deplicate ticket. (20691). CLosing
