### ISSUE TITLE
Logic issues with GO:0034490 basic amino acid transmembrane import into vacuole -> GO:0051668 localization within membrane ?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#20700]
Making a Noctua model (gomodel:5fce9b7300002015), and tried to make an annotation that a protein with the BP "basic amino acid transmembrane import into vacuole" occurs_in "fungal-type vacuole membrane".

Annotation Preview ended up showing an annotation to "localization within membrane". @vanaukenk looked into this a little and it seems like the logical definitions for GO:0034490 basic amino acid transmembrane import into vacuole may be a little off in order to let this turn into a localization term; the entity (L-arginine) is passed through the membrane but I would not say that it is localizing to the membrane. 

if it helps, from my model: 

basic amino acid transmembrane import into vacuole#5fce9b7300002034 | type | localization within membrane | 

Asserted Triples

- basic amino acid transmembrane import into vacuole#5fce9b7300002034 type basic amino acid transmembrane import into vacuole,
- basic amino acid transmembrane import into vacuole#5fce9b7300002034 occurs_in fungal-type vacuole membrane#5fce9b7300002036,
- fungal-type vacuole membrane#5fce9b7300002036 type fungal-type vacuole membrane

Rules

- ( ?x1 type localization ) ∧ ( ?x1 occurs_in ?x2 ) ∧ ( ?x2 type membrane ) → ( ?x1 type localization within membrane ),
- ( ?x1 type transport ) → ( ?x1 type establishment of localization ),
- ( ?x1 type fungal-type vacuole membrane ) → ( ?x1 type membrane ),
- ( ?x1 type amino acid transmembrane import into vacuole ) → ( ?x1 type transport ),
- ( ?x1 type establishment of localization ) → ( ?x1 type localization ),
- ( ?x1 type basic amino acid transmembrane import into vacuole ) → ( ?x1 type amino acid transmembrane import into vacuole )

**Comment by pgaudet** [comment]
Hi @suzialeksander 
I dont think you can use `occurs_in "fungal-type vacuole membrane".`
 - did you try removing that ? I would suspect this is causing the 'location within membrane' assertion? 

The logical definition of "basic amino acid transmembrane import into vacuole" is 

'basic amino acid transport'
 and ('has target start location' some cytosol)
 and ('has target end location' some 'vacuolar lumen')
 and (imports some 'amino acid')
 and ('results in transport across' some membrane)

I wonder if, when there already is a CC in the logical definition of a BP, that doesn't cause weird results? In any event it seems to me the 'location within membrane'' is the result of your annotation occurs_in "fungal-type vacuole membrane" (this is also how I understand the explanation by the reasoner).

Thanks, Pascale

**Comment by ValWood** [comment]
can occurs_in "fungal-type vacuole membrane" be attached to the transporter instead ?(@suzialeksander I'm guessing that you are annotating a TM transporter here, because that part of the transport process does occur in the membrane)?

**Comment by suzialeksander** [comment]
@pgaudet (and actually @ValWood this answers your suggestion too) this was done in Form, so if this isn't an ontology issue maybe it's a Form problem? There doesn't seem to be an easy way to make this not be `occurs_in` unless I use CC Only Form at which point I lose the association with the F and P terms.  

I don't know if @vanaukenk saw anything in particular when we were looking at this.

**Comment by pgaudet** [comment]
I meant, the transport does not 'occur in' - it starts outside the membrane and ends outside the membrane. So, I think there is a logical inconsistency with our use of occurs_in "fungal-type vacuole membrane" for transport. Val might be right that the activity of the transporter should be OK to annotate with occurs_in "fungal-type vacuole membrane" . Have you tried that ?

**Comment by ValWood** [comment]
I would  only use occurs_at when the MF. You can say where a specific activity occurs but  often the entire process is distributed and begins in another compartment or location.
Therefore you can't annotate a process with a precise location if the logical def specifies a broader start and end location. Logical violations will happen continually if occurs_at is allowed on process?

**Comment by pgaudet** [comment]
That's probably right.

**Comment by pgaudet** [comment]
Talking with @thomaspd 

I will change the LD for 'localization within membrane' 
from: localization
 and ('occurs in' some membrane)

to: localization
 and ('has target end location' some membrane)

Let's see if that helps.

**Comment by pgaudet** [comment]
We checked with @balhoff - this fixes the unexpected inference.
