### ISSUE TITLE
GO:0036473   cell death in response to oxidative stress (tax constraint)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20734]
Could we add "never in  yeast" for this?

- [ ] GO:0036473   cell death in response to oxidative stress

In single celled organisms this wouldn't be a desired process. We would capture as a phenotype I think it's for selective cell killing of multicellular cells?

**Comment by pgaudet** [comment]
never in fungi ? 
I cannot find 'yeast' as a taxon or taxon union.

**Comment by pgaudet** [comment]
I can do NCBITaxon:Union_0000023	Fungi or Bacteria or Archaea

**Comment by ValWood** [comment]
for fung I think it might need to be
never in Schizosaccharomycetes and never in Saccharomycetes for now.
I'm not sure  what mushrooms do....

**Comment by pgaudet** [comment]
I think we have used NCBITaxon:4890 | Ascomycota for this case; would that be OK ?

**Comment by ValWood** [comment]
Ascomycota includes non yeast though, so I wasn't sure it would work for this term

**Comment by pgaudet** [comment]
But it's deeper than fungus. I'll try that.

**Comment by pgaudet** [comment]
It would also exclude Candida, but all annotations are IEAs from SGD, that would go away anyway.
