### ISSUE TITLE
various mitochondrion related taxon restrictions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20737]
Please add " never in yeast" taxon restrictions to
 - [x] GO:0020023 kinetoplast  (only in kinetoplastids?)
 - [x] GO:0016007 mitochondrial derivative (not sure  which organisms have mitochondrial derivatives)

 - [x] GO:1990843 subsarcolemmal mitochondrion (only in organisms with muscle cells, metazoa?)
 - [x] GO:1990844 interfibrillar mitochondrion (only in organisms with muscle cells, metazoa?)
The definitions of these 2 don't parse very well.

Also, these terms are strange because they only seem to be describing where the mitochondria are in a specific cell type.
. 
"In addition, mitochondria exist as two subcellular populations and based on their spatial locations have been termed subsarcolemmal (SS) and intermyofibrillar (IMF) mitochondria, creating another level of cellular compartmentalization."
It doesn't seem to make sense for gene specific annotation, unless these different populations 
have specific GPs localized to them?

**Comment by ValWood** [comment]
@pgaudet these ones can be never in fungi.

**Comment by pgaudet** [comment]
GO:0016007 mitochondrial derivative added NCBITaxon:2081351	Drosophila
I cannot find that in any other species @hattrill - any suggestions?

**Comment by pgaudet** [comment]
GO:1990843 subsarcolemmal mitochondrion
and  GO:1990844 interfibrillar mitochondrion
Both have a single RGD annotation; @gthayman is this a specific mitochondrion, or can the cell type be captured as an extension ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi @pgaudet - well, I can shed no light on this. In my world view, a mitochondrion is a mitochondrion regardless of cell type or position. So I have no objection to obsoleting these terms.

**Comment by pgaudet** [comment]
so GO:0016007 mitochondrial derivative should also go ?

**Comment by hattrill** [comment]
Yes, these seem to relate to spermatid Nebenkern and we wouldn't specifically annotate a CC to this over mitochondrion.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:1990843 subsarcolemmal mitochondrion
GO:1990844 interfibrillar mitochondrion
and GO:0016007 mitochondrial derivative

The reason for obsoletion is that these correspond to mitochondria of specific cell types and this information should be captured as an extension. 

There are 4 annotations to GO:0016007 mitochondrial derivative by Flybase, to be moved @hattrill 
and 1 annotation to each GO:1990843 subsarcolemmal mitochondrion and GO:1990844 interfibrillar mitochondrion by RDG @slaulederkind 

There are no mappings; those terms are not present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 12. Unless objections are received by February 12, 2021, we will assume that you agree to this change.
 
You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/20737
 
 
Thanks, Pascale

**Comment by gthayman** [comment]
Two RGD annotations fixed.

**Comment by hattrill** [comment]
Hi @pgaudet - have to confess that I was wrong and want to row back on the obsoletion of "GO:0016007 mitochondrial derivative". These are so morphological and structurally destinct from mitochondria (even though that they are derived from them), that I think that a better way to handle these is to put them under 'GO:0043231 intracellular membrane-bounded organelle" along with Nebenkern:

GO:0043231 intracellular membrane-bounded organelle
-GO:0016007 mitochondrial derivative
--GO:0016008 major mitochondrial derivative  
--GO:0016009 minor mitochondrial derivative 
-GO:0016006 Nebenkern

(sincerest apologies)

**Comment by pgaudet** [comment]
Do you have papers that we can attach to the terms?

**Comment by pgaudet** [comment]
I used PMID:25265054 for nebenkern
PMID:24211517 and PMID:30802236 for minor/major derivatives. 

Let me know if you have better references. 

Thanks, Pascale

**Comment by pgaudet** [comment]
'Major' and 'minor' were already linked to another paper, PMID:17123504.

**Comment by hattrill** [comment]
PMID:17123504 is a good one! Thanks.
