### ISSUE TITLE
Obsolete GO:0046808 assemblon ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20746]
Working on #20643

The term GO:0046808 assemblon has no annotations, and it represents a site of immunoreactivity rather than a well-defined CC. Few papers exist, and the most recent is 15 years old: https://pubmed.ncbi.nlm.nih.gov/?term=Assemblons&sort=date

I propose to obsolete this term. 

@pmasson55 : since the term definition mentions that "Assemblons contain the proteins for immature-capsid assembly", I wanted to know if you thought this term was useful? 

Thanks, Pascale

**Comment by pmasson55** [comment]
Hi Pascale,

Never came accross this term, and never used it. Don't think it's useful,we have better terms...
Fine for me to obsolete :)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0046808 assemblon'. The reason for obsoletion is that this does not correspond to a real cellular component, but to a site of immunoreactivity. 

There are no annotations or mappings to this term; this term is not present in any subsets. 

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/20746

Thanks, Pascale
