### ISSUE TITLE
A question for an endosome expert (possible term merge)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20747]
How does
GO:1990126   retrograde transport, endosome to plasma membrane
Definition
The directed movement of membrane-bounded vesicles from endosomes back to the plasma membrane, a trafficking pathway that promotes the recycling of internalized transmembrane proteins. PMID:23563491

differ from
GO:0032456    endocytic recycling 
Definition 
The directed movement of membrane-bounded vesicles from recycling endosomes back to the plasma membrane where they are recycled for further rounds of transport. PMID:16473635

**Comment by pgaudet** [comment]
@lbreuza can you comment on this?

**Comment by lbreuza** [comment]
These terms are basically describing the same process, but one is focused on a vesicular trafficking route (endocytic recycling) while the other was probably created to describe experiments where one measure the recycling of the proteins (retrograde transport, endosome to plasma membrane) through this route. I am not sure makes sense to have both terms but I can imagine how difference papers scope could have triggered the creation of both terms.

**Comment by pgaudet** [comment]
Sounds like we can go ahead with the merge.
