### ISSUE TITLE
tRNA surveillance

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#20752]
We'd like a new term to use with PMID:32841241:

id: GO:new
name: tRNA surveillance
namespace: biological_process
def: "The set of processes involved in identifying and degrading defective or aberrant tRNAs." [GOC:mah, PMID:32841241]
synonym: "tRNA quality control" EXACT [GOC:mah]
is_a: GO:0071025 ! RNA surveillance

I also think GO:0071038 could be moved from is_a GO:0016078 to is_a GO:new. The paper introduction describes two tRNA QC pathways in budding yeast -- "nuclear surveillance" and "rapid tRNA decay (RTD)" -- but I don't have time to look into whether GO:0071038 corresponds to one or the other of them. S. pombe appears to have the RTD pathway, but we can annotate to the more general term requested here.

**Comment by hdrabkin** [comment]
will get this in as soon as I work out an issue with my copy of the repo.

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106354
+name: tRNA surveillance
And moved  GO:0071038 to is_a GO:0071038 as suggested.

**Comment by mah11** [comment]
yay, thank you :)
