### ISSUE TITLE
GO:0097657: nucleotide or nucleoside bisphosphate phosphatase?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20771]
3',5'-nucleotide bisphosphate phosphatase activity (GO:0097657)
Has def: Catalysis of the reaction: 3',5'-**nucleotide** bisphosphate + H20 = 5'-**nucleotide** monophosphate + phosphate. (PMID:24401123)
And that PMID definitely talks about "3',5'-**nucleotide** bisphosphate phosphatases".

But xref is to RHEA:43532 (https://www.rhea-db.org/rhea/43532), which is for a **ribonucleoside** 3',5'-bisphosphatase.
And the RHEA page xrefs back to EC 3.1.3.97 (3',5'-**nucleoside** bisphosphate phosphatase).

I'm not sure if the GO term/def is incorrect, or the xref is incorrect? Any insights @hdrabkin?

**Comment by sjm41** [comment]
Original request: https://github.com/geneontology/go-ontology/issues/11366

**Comment by sjm41** [comment]
May want to check the Q80V26 mouse annotation using this term.

**Comment by deustp01** [comment]
I think the same naming confusion is operating here as in ticket 
inosine-diphosphatase activity (GO:1990003) parentage #20773

**Comment by sjm41** [comment]
Yes, thanks @deustp01 .
Looking again at this, the term placement looks ontologically correct, but I'd recommend these changes:
1. Add EC 3.1.3.97 as an xref.
2. Replace 'nucleotide' with 'nucleoside' in the GO term name and definition (to be consistent with naming conventions at EC and Rhea, and also the GO term names for GO:0017111 and GO:0017110).

**Comment by hdrabkin** [comment]
GO:0017111 already uses nucleoside triphosphate and nucleoside diphosphate in def. 
Changed output for GO:0017110 to nucleoside monophate. 
Added EC.

**Comment by sjm41** [comment]
Thanks Harold.
Sorry if I wasn't clear - I was suggesting to "Replace 'nucleotide' with 'nucleoside' in the GO term name and definition" in  **GO:0097657**, for consistency.
