### ISSUE TITLE
 GO:0016462 pyrophosphatase activity - RHEA:51724

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20777]
GO:0016462 pyrophosphatase activity has RHEA:51724 xref.
https://www.rhea-db.org/rhea/51724
**P1,P6-bis(5'-adenosyl) hexaphosphate = adenosine 5'-tetraphosphate + ADP**

That's a type of pyrophosphatase, but do we want that specific xref on this grouping term in GO?

I don't think the correct GO term exists - maybe it needs adding and this xref applied? (Rhea says the only annotated protein is pombe aps1 (Q09790) - @ValWood 

I do see these related terms (also on aps1):
bis(5'-adenosyl)-hexaphosphatase activity (GO:0034431)
bis(5'-adenosyl)-pentaphosphatase activity (GO:0034432)

**Comment by pgaudet** [comment]
EC:3.6.1.- also looks wrong for GO:0016462, as this is the same EC as the parent class GO:0016818.

**Comment by hdrabkin** [comment]
EC:3.6.1.0 should be removed from GO:0016462, AND the RHEA IS too specific. Let me see if I can find some proper xrefs.

**Comment by sjm41** [comment]
I only see EC:3.6.1.- on the def of GO:0016462.  QuickGO change log says it was removed as an xref on 2019-06-29.

**Comment by hdrabkin** [comment]
And I think the RHEA belongs with GO:0034431 more likely.
P1,P6-bis(5'-adenosyl) hexaphosphate = adenosine 5'-tetraphosphate + ADP RHEA; Actually the rhea rxn has water also
P1-P6-bis(5'-adenosyl) hexaphosphate + H2O = AMP + adenosine 5'-pentaphosphate. (GO)
Will transfer.
Meanwhile:

**Comment by sjm41** [comment]
Hi Harold
I think GO:0034431 (hexa = penta + AMP) is RHEA:32047.
I don't think RHEA:51724 (hexa = tetra + ADP) is in GO right now.

I agree we should keep the pyrophosphatase activity term!

**Comment by hdrabkin** [comment]
3.6.1.- 
Hydrolases  Acting on acid anhydrides In phosphorus-containing anhydrides
Opps; Right; GO has a 5' Ap5 product, rhea has tetra. I was looking up RHEA:51724 directly and not realizing the rhea used in GO More coffee. 
But to keep pyrophosphatase activity I'd like something better than GO:curators.

**Comment by hdrabkin** [comment]
maybe
PMID: 29362089; but most papers are about inorganic pyrophosphatases. Will keep looking

**Comment by ValWood** [comment]
For aps1 I am also getting the following mapping

GO:0050072 | m7G(5')pppN diphosphatase activity | IBA with S000005689 , PTN000290327 | Gaudet P et al. (2011)

 m7G(5')pppN diphosphatase activity
https://www.yeastgenome.org/reference/S000152147
from an in vitro assay, but I am not sure that this is physiologically relevant. I'm not sure that it should be PAINTED.....

**Comment by hdrabkin** [comment]
I could do this wiki
https://en.wikipedia.org/wiki/Pyrophosphatase

**Comment by sjm41** [comment]
The MeSH link from the wiki page looks good, if that's a permissible source:
https://meshb.nlm.nih.gov/record/ui?name=Pyrophosphatases

**Comment by hdrabkin** [comment]
Can't find any use of MESH as an xref. I think I'll go with the Wiki; since it's a grouping term I don't think there will be any real objections.

**Comment by hdrabkin** [comment]
Done.

**Comment by sjm41** [comment]
thanks!
