### ISSUE TITLE
 inosine-diphosphatase activity (GO:1990003) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20773]
inosine-diphosphatase activity (GO:1990003) currently has two parents:
1.)  nucleoside-diphosphatase activity (GO:0017110) - this looks correct, consistent with other children of GO:0017110
2.)  nucleotide phosphatase activity, acting on free nucleotides (GO:0098519) - this looks wrong - no other children of GO:0017110 have this, and inosine-diphosphate (IDP) is a **nucleoside** (not **nucleotide**)

if you agree, can you remove the GO:0098519 parent?

**Comment by sjm41** [comment]
Also see https://github.com/geneontology/go-ontology/issues/12825

**Comment by deustp01** [comment]
A nucleoside is a purine or pyrimidine bases attached to ribose or deoxyribose sugars. When one or more phosphate groups are attached, the result is a nucleotide. But names of molecules are confusing: AMP is a nucleotide, but its ChEBI name is CHEBI:16027 - adenosine 5'-monophosphate, and CHEBI:17808 - IDP has the ChEBI definition "A purine ribonucleoside 5'-diphosphate having inosine as the nucleobase."

**Comment by sjm41** [comment]
Hi Peter, are you saying the dual parentage of inosine-diphosphatase activity (GO:1990003) is correct??
I'm attaching an image that better illustrates the current discrepancy between this term and its sister terms:
![Screenshot 2021-02-01 at 13 42 18](https://user-images.githubusercontent.com/16306861/106466556-6016a900-6493-11eb-80cb-b21d0106f5d4.png)

**Comment by deustp01** [comment]
That's a question for a better enzymologist and ontologist than me - @hdrabkin ?

**Comment by hdrabkin** [comment]
note:  inosine-diphosphate (IDP) is a nucleoside (not nucleotide)
No; inosine is a nucleoside (base + sugar).; the moment you put a phosphate on it is is a nucleoide (sugar + base + phosphate)

**Comment by sjm41** [comment]
Ah, sorry, I see my confusion now...thanks Peter and Harold for explaining!
Of course, a 'nucleoside diphosphate' (or monophosphate or triphosphate) is a type of nucleotide....

Def of "nucleotide phosphatase activity, acting on free nucleotides" (GO:0098519) says "**Catalysis of the reaction: nucleotide + H2O = nucleotide + phosphate.**" and there's a comment saying "**To be used for NTP->NDP or NDP -> NMP. For nucleotide -> nucleoside (all phosphates removed) use nucleotidase.**"

I think that means all the other 8 nucleoside diphosphatase terms should also be children of GO:0098519 (like 'inosine-diphosphatase activity') right?

**Comment by deustp01** [comment]
> the moment you put a phosphate on it is is a nucleotide (sugar + base + phosphate)
That is exactly what the expert biochemists taught me, but it appears to be acceptable usage to name nucleotides (base + sugar + phosphate(s)) as "nucleoside phosphates". Maybe GO, ChEBI, and Rhea can avoid this ambiguity but the rest of the world probably won't notice.

**Comment by sjm41** [comment]
Hi @hdrabkin 

I think I've realised the main problem here: "nucleotide phosphatase activity, acting on free nucleotides" (GO:0098519) is currently a child of 'phosphatase activity' (ie. hydrolysing phosphoric ester bonds) but it should be a child of 'pyrophosphatase activity' (ie. hydrolysing the bond between 2 phosphate groups).  Right?  That should fix my ontology issue.

My previous question about treating all the nucleoside diphosphatase terms equally still stands. "nucleotide phosphatase activity, acting on free nucleotides" (GO:0098519) currently only has 2 children ('inosine-diphosphatase activity' and 'XDP phosphatase activity') - do you think that's correct?

One last thing - nucleoside-diphosphatase activity (GO:0017110) has 'inosine 5-diphosphatase' as a synonym - that should be moved to the 'inosine-diphosphatase activity (GO:1990003)' term.

**Comment by sjm41** [comment]
Hi @hdrabkin Can you respond to the 3 points in my previous post (2nd Feb) when you get chance? Thanks.

**Comment by hdrabkin** [comment]
I don't think nucleotide + H2O = nucleotide + phosphate. indicates a child of pyrophosphatase 

Term: nucleotide phosphatase activity, acting on free nucleotides
Synonyms: nucleotide phosphatase activity
Definition: Catalysis of the reaction: nucleotide + H2O = nucleotide + phosphate.
Parent Terms: is-a phosphatase activity
Comment: To be used for NTP->NDP or NDP -> NMP. For nucleotide -> nucleoside (all phosphates removed) use nucleotidase.
Category: Molecular Function
ID: GO:0098519

The def above is inconsistent with the pyrophosphatase  def in that it does not leave one phosphate on each fo the two fragments. 

Term: pyrophosphatase activity
Definition: Catalysis of the hydrolysis of a pyrophosphate bond between two phosphate groups, leaving one phosphate on each of the two fragments.

**Comment by sjm41** [comment]
OK, thanks @hdrabkin.

But I think there's still a problem with the parentage here:
- guanosine-diphosphatase activity, cytidine-diphosphatase activity, adenosine-diphosphatase activity and uridine-diphosphatase activity are asserted to be children of "nucleoside-diphosphatase activity" (which is a child of "pyrophosphatase activity" 
- in contrast, and uniquely, "inosine-diphosphatase activity" is a child of **both** "nucleoside-diphosphatase activity" and "nucleotide phosphatase activity, acting on free nucleotides".  Indeed, this is the **only** child of "nucleotide phosphatase activity, acting on free nucleotides" in the GO.

![Screenshot 2021-07-05 at 13 01 01](https://user-images.githubusercontent.com/16306861/124469256-0b54c280-dd92-11eb-8321-d71fed8c949b.png)

So, is "inosine-diphosphatase activity" really a special case?
 
As written, the definition of 'nucleoside-diphosphatase activity' ("Catalysis of the reaction: a nucleoside diphosphate + H2O = a nucleoside monophosphate  + phosphate.") sounds like it's a subtype of 'nucleotide phosphatase activity, acting on free nucleotides' ("Catalysis of the reaction: nucleotide + H2O = nucleotide + phosphate." [GOC:dos]
comment: To be used for NTP->NDP or NDP -> NMP."). But that's not how the GO tree looks.
All the EC xrefs here are 3.6.1.*, so at face value, we should just be seeing parents in the 'hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides (GO:0016818) = EC:3.6.1.-' branch here, and not in the 'phosphatase activity (GO:0016791) = EC:3.1.3.-' branch.

Am I just missing something here, or do you also see this as a discrepancy??

I'm copying the relevant go-basic.obo entries below, just showing defs, relations, EC and Rhea refs for convenience.

id: GO:0017110
name: nucleoside-diphosphatase activity
def: "Catalysis of the reaction: a nucleoside diphosphate + H2O = a nucleoside monophosphate  + phosphate." [EC:3.6.1.6]
xref: EC:3.6.1.6
xref: RHEA:36799
is_a: GO:0016462 ! pyrophosphatase activity

id: GO:0098519
name: nucleotide phosphatase activity, acting on free nucleotides
def: "Catalysis of the reaction: nucleotide + H2O = nucleotide + phosphate." [GOC:dos]
comment: To be used for NTP->NDP or NDP -> NMP. For nucleotide -> nucleoside (all phosphates removed) use nucleotidase.
is_a: GO:0016791 ! phosphatase activity

id: GO:0004382
name: guanosine-diphosphatase activity
def: "Catalysis of the reaction: GDP + H2O = GMP + phosphate." [EC:3.6.1.42, PMID:2989286, RHEA:22156]
xref: EC:3.6.1.42
xref: RHEA:22156
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:0036384
name: cytidine-diphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: CDP + H2O = CMP + phosphate." [GOC:al, RHEA:64880]
synonym: "CDPase activity" EXACT [GOC:al]
xref: RHEA:64880
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:0043262
name: adenosine-diphosphatase activity
def: "Catalysis of the reaction: ADP + H2O = AMP + phosphate." [EC:3.6.1.5, PMID:1470606]
xref: RHEA:61436
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:0044715
name: 8-oxo-dGDP phosphatase activity
def: "Catalysis of the reaction 8-oxo-dGDP + H2O = 8-oxo-dGMP + phosphate." [GOC:pde, PMID:22556419, RHEA:32063]
xref: EC:3.6.1.58
xref: RHEA:32063
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:0044716
name: 8-oxo-GDP phosphatase activity
def: "Catalysis of the reaction 8-oxo-GDP + H2O = 8-oxo-GMP + phosphate." [GOC:pde, PMID:22556419, RHEA:62356]
xref: EC:3.6.1.58
xref: RHEA:62356
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:0044717
name: 8-hydroxy-dADP phosphatase activity
def: "Catalysis of the reaction: 8-hydroxy-dADP + H2O = 8-hydroxy-dAMP + phosphate." [GOC:pde, PMID:22556419]
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:0045134
name: uridine-diphosphatase activity
def: "Catalysis of the reaction: UDP + H2O = UMP + phosphate." [RHEA:64876]
xref: EC:3.6.1.6
xref: RHEA:64876
is_a: GO:0017110 ! nucleoside-diphosphatase activity

id: GO:1990003
name: inosine-diphosphatase activity
def: "Catalysis of the reaction: IDP + H2O = IMP + phosphate." [PMID:20385596, PMID:22849572, RHEA:35207]
xref: EC:3.6.1.64
xref: Reactome:R-HSA-2509816 "NUDT16 hydrolyses IDP to IMP"
xref: RHEA:35207
is_a: GO:0017110 ! nucleoside-diphosphatase activity
is_a: GO:0098519 ! nucleotide phosphatase activity, acting on free nucleotides

**Comment by sjm41** [comment]
@hdrabkin Would be useful to clear this one up.
Do we think the dual parentage of inosine-diphosphatase activity is correct (and should apply to all  nucleoside-diphosphatase terms)
OR
that the single parentage of guanosine-diphosphatase activity, cytidine-diphosphatase activity, adenosine-diphosphatase activity and uridine-diphosphatase activity is correct (and inosine-diphosphatase activity parentage should be changed to match)
(see image in previous post)
?

**Comment by sjm41** [comment]
@hdrabkin Thoughts on my previous comment?

**Comment by sjm41** [comment]
Closing this.  Following the thorough research described in #23401, we are proposing to obsolete "nucleotide phosphatase activity, acting on free nucleotides (GO:0098519)" - see #23456.
This will fix the issue originally described here.
