### ISSUE TITLE
taxon restriction GO:0045180 basal cortex

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#20784]
This relates to the epithelium like structures in Dictyostelium development. Certain proteins, like the IQGAP and cortexillin are located opposite of the apical side (stalk side of actomyosin ring surrounding and restricting the stalk during development) at the basal cortex and they are necessary for this polarity.

Why did a simple term like basal cortex get restricted to Metazoa? Apical cortex is not restricted, or not yet? This makes no sense to me.

**Comment by ValWood** [comment]
Hi Petra,

my fault
https://github.com/geneontology/go-ontology/issues/20643
it should be "never in yeast", not "only in metazoa"

@pgaudet  could you add "never in yeast" to 
GO:0045179   apical cortex too?

@pfey03  We like to restrict these for a few reasons, but mainly
1) it prevents erroneous mappings from PAINT, InterPro etc
and
2) For our community, removing non-applicable terms makes it easier to browse the ontology during curation. Although some restrictions may seem a bit trivial these tiny things add up and can make a big difference in making curation easier- especially if these terms have descendants.


Sometimes I get it a bit wrong ;), and unfortunately Dicty often bears the brunt of this. I should tag you in the tickets where we aren't sure.
v

**Comment by pfey03** [comment]
Thanks @ValWood

**Comment by pgaudet** [comment]
Fixed, thanks for reporting.

**Comment by pfey03** [comment]
Thanks @pgaudet
