### ISSUE TITLE
Protein-arginine rhamnosyltransferase activity, Protein-arginine N-acetylglucosaminyltransferase activity and Protein-cysteine methyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#20788]
Hi GO,

I would need a bunch of terms related to enzymes (Rhea have been created) that catalyze PTMs

Thanks

Sylvain

1)
Name: Protein-arginine rhamnosyltransferase activity

Definition: Catalysis of the reaction: dTDP-beta-L-rhamnose + L-arginyl-[protein] = dTDP + H(+) + N(omega)-(L-rhamnosyl)-L-arginyl-[protein]

child of GO:0046527 glucosyltransferase activity
Xref:
PMID:25686373;
PMID:26060278;
Rhea:66692

2)
Name: Protein-arginine N-acetylglucosaminyltransferase activity

Definition: Catalysis of the reaction: L-arginyl-[protein] + UDP-N-acetyl-alpha-D-glucosamine = H(+) + N(omega)-(N-acetyl-beta-D-glucosaminyl)-L-arginyl-[protein] + UDP []

child of GO:0016262 protein N-acetylglucosaminyltransferase activity
Xref:
PMID:23955153
PMID:30619781
Rhea:66632

3)
Name: Protein-cysteine methyltransferase activity

Definition: Catalysis of the reaction: L-cysteinyl-[protein] + S-adenosyl-L-methionine = H(+) + S-adenosyl-L-homocysteine + S-methyl-L-cysteinyl-[protein] 

child of GO:0008172 S-methyltransferase activity
PMID:25412445
PMID:21481189
PMID:22158122
PMID:24235145
Rhea:66544

**Comment by hdrabkin** [comment]
Thanks @sylvainpoux for getting the RHEAs. I'll make the terms but mark this ticket RHEA-pending and leave it open untill the RHEAs become public.

**Comment by hdrabkin** [comment]
+id: GO:0106361
+name: protein-arginine rhamnosyltransferase activity

+id: GO:0106362
+name: protein-arginine N-acetylglucosaminyltransferase activity

+id: GO:0106363
+name: protein-cysteine methyltransferase activity

**Comment by sylvainpoux** [comment]
Thanks Harold!

**Comment by hdrabkin** [comment]
RHEAs not public yet as of 3/9/21

**Comment by sylvainpoux** [comment]
Hi Harold,
I know a release is scheduled soon. Anne (@amorgat) will know more about precise timeline
Thanks
Sylvain

**Comment by hdrabkin** [comment]
Thanks; I just always note in the ticket the last time I checked (I keep the ticket open until I add the RHEAs and remove 'rhea-pending' tag.

**Comment by sjm41** [comment]
@sylvainpoux @hdrabkin 
I think " GO:0008276 protein methyltransferase activity" should be added as an additional parent to "GO:0106363 protein-cysteine methyltransferase activity".

**Comment by sylvainpoux** [comment]
Hi Steven,
yes, that's correct.
Sylvain

**Comment by hdrabkin** [comment]
adding rheas now available.

**Comment by sjm41** [comment]
@hdrabkin Did you add those extra parents I mentioned on 19th March too?

**Comment by hdrabkin** [comment]
reopened because problem with pull request due to errors in other parts of the ontology not related to this ticket. Will revisit later this week.

**Comment by hdrabkin** [comment]
RHEAs and parentage additions done.
