### ISSUE TITLE
NTR: nuclear envelope budding and other issues

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#20782]
From at PMID:27236823 and PMID:32503943, it looks like there is a cellular process that underlies virus budding from the nucleus ("GO:0039674 exit of virus from host cell nucleus by nuclear egress") and the non-canonical nuclear export pathway, nuclear envelope budding.

Could I have a term for 'nuclear envelope budding':
The process by which large macromolecular complexes are budded through the inner nuclear membrane, into the perinuclear space, thus acquiring a membrane envelope. The enveloped particle fuses with the outer nuclear membrane and is released into the cytoplasm.

It would be good if this could be linked somehow with "GO:0039674 exit of virus from host cell nucleus by nuclear egress", perhaps by a common parent. 

Would be nice to link this with 'nuclear export', but I note that there has been an issue https://github.com/geneontology/go-ontology/issues/19103 with 'nuclear export' taxon constraints.

For GO:0046772 viral budding from outer nuclear membrane
the definition is incorrect - "The envelopment of a virus, in which the nucleocapsid evaginates from the host outer nuclear membrane system, thus acquiring a membrane envelope."

The naked capsid is released into the cytoplasm.

**Comment by pgaudet** [comment]
Hi @hattrill 
I created the term 

 
+[Term]
+id: GO:0140591
+name: nuclear envelope budding
+namespace: biological_process
+def: "The process by which large macromolecular complexes are budded through the inner nuclear membrane, into the perinuclear space, thus acquiring a membrane envelope. The enveloped particle fuses with the outer nuclear membrane and is released into the cytoplasm." [PMID:27236823, PMID:32503943]
+is_a: GO:0051168 ! nuclear export
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20782 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-08T08:31:06Z

However as you point out from ticket #19103 we cannot link processes that occur in host with normal processes without messing up the taxon constraints. It's too bad to have two branches, but I am reluctant to loose the benefits we gain from being able to use taxon constraints. 

OK ? Or do you have other suggestions?

**Comment by pgaudet** [comment]
Updated definition of GO:0046772 as well as GO:0046771

**Comment by hattrill** [comment]
That's good for me. Can't even to begin to think my way around taxon issues!

Thanks
