### ISSUE TITLE
Obsoletion: abortive mitotic cell cycle GO:0033277

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20786]
Please taxon restrict 
abortive mitotic cell cycle GO:0033277

There are only 2 EXP annotation based on:

http://europepmc.org/article/MED/23509158
entitled
"Megakaryocyte-specific deletion of the protein-tyrosine phosphatases Shp1 and Shp2 causes abnormal megakaryocyte development, platelet production, and function."

so this might even be a phenotype?

**Comment by pgaudet** [comment]
@hdrabkin those are mouse annotations; would you please check that they are valid?

**Comment by hdrabkin** [comment]
Are you saying it does not occur in mammals? Can you point me to a reference?

**Comment by ValWood** [comment]
Hi Harold,

My original; request was to make a taxon restriction "never in fungi" as it is never "normal" for fungi to do this, unless a gene was deleted which compromised completion of a cell cycle.

The title of this paper  seems to simple that this is not normal in mammalian cells either:

"Megakaryocyte-specific deletion of the protein-tyrosine phosphatases Shp1 and Shp2 causes abnormal megakaryocyte development, platelet production, and function."

of course, if you delete cell cycle components the cell cycle will abort, because it can't complete (even if the checkpoints are activated, if a required component is missing, aborting (i.e a non-resolvable cell -cycle block) is the only option.

 So in the situation in this paper, where the title specifies "abnormal" (because the abortive cell cycle is inflicted by a deliterous mutation), this isn't a normal process.

Presumably what would happen in a 'normal ' context if  the cell cycle cannot continue 9i.e in ageing cells or otherwise), if the cell cycle checkpoints can't deal with the problem then the outcome would usually be  senescence or apoptotic pathways.
But I'm pretty sure "abortive mitotic cell cycle" is describing a phenotype that is observed. It might be better as a 'related' synonym of some other process(s). Although I'm not sure that this paper would be annotated to any of those terms.

All you can get from this paper is "mitotic cell cycle" although they do say 
"The cause of the block in ploidy in Shp1-deficient megakaryocytes remains undefined but suggests a defect in the formation of the cleavage furrow and/or cytokinesis at the 2N/4N transition during the endomitotic process". I did not read in detail do I don't know if it is possible to annotate to a more specific cell cycle term.

To have the term "abortive cell cycle" in GO we need a term to support its existence as a biological process (as opposed to a phenotype as in this instance) , rather than a term to disprove its existence. It might exist (I don't know multicellular biology well enough), but this annotation/publication isn't an example.

**Comment by ValWood** [comment]
Hang on, I see the. comment

"Note that this term should be used only for abortive mitotic events that occur normally, e.g. during megakaryocyte differentiation; it should not be used for incomplete mitosis resulting from mutation or other abnormal occurrences. Note that this term should not be confused with 'endomitotic cell cycle ; GO:0007113', which describes a process in which no mitotic spindle forms."

but maybe this is a terminology issue.

If I search PubMed for
megakaryocyte and "abortive cell cycle" I get no results.

but if I search 
megakaryocyte and "endomitotic cell cycle" I get 20 results.

I see:
Endomitosis in megakaryocytes....PMID: 18677109 
MK achieve polyploidy by switching from a normal to an endomitotic cell cycle. PMID: 16258287
endomitosis of megakaryocytes...PMID: 19339696 
etc.

So I'm not sure that the comment is correct?

particularly
 Note that this term should not be confused with 'endomitotic cell cycle ; GO:0007113', which describes a process in which no mitotic spindle forms.

which is true, but it sounds like this term is meant to represent "endomitotic cell cycle"?

https://www.ebi.ac.uk/QuickGO/term/GO:0007113
GO:0007113    JSON
endomitotic cell cycle
Biological Process

Definition 
A mitotic cell cycle in which chromosomes are replicated and sister chromatids separate, but spindle formation, nuclear membrane breakdown and nuclear division do not occur, resulting in an increased number of chromosomes in the cell.
Comments
Note that this term should not be confused with 'abortive mitotic cell cycle ; GO:0033277'. Although abortive mitosis is sometimes called endomitosis, GO:0033277 refers to a process in which a mitotic spindle forms and chromosome separation begins.

We need to look into this more-  but  it seems that"
1. "abortive mitotic cell cycle" probably  isn't needed (It seems to refer to "endomitotic cell cycle")
2. "endomitotic cell cycle" is badly defined (this definition sound like it could be based on the cytological markers of a fission yeast endomitotic cell cycle which occurs in some mutants, which fits with the date and the fact that the cell cycle workshop had mainly fission yeast cell-cycle experts)

**Comment by ValWood** [comment]
@ukemi @hdrabkin  thoughts?

**Comment by hdrabkin** [comment]
Does this encompass things like polyploidization?

**Comment by ValWood** [comment]
I don't think so.
That is covered by
https://www.ebi.ac.uk/QuickGO/term/GO:0042023
DNA endoreduplication
Regulated re-replication of DNA within a single cell cycle, resulting in an increased cell ploidy. An example of this process occurs in the synthesis of Drosophila salivary gland cell polytene chromosomes.

To me without further information "abortive" sounds like some sort of f**k-up?

especially based on the publication title:
"Megakaryocyte-specific deletion of the protein-tyrosine phosphatases Shp1 and Shp2 causes abnormal megakaryocyte development, platelet production, and function."

We see *phenotypes" like this in yeast _All the time_  when you delete things

for example
https://www.pombase.org/term/FYPO:0001026
abnormal occurrence of normal mitotic cell cycle arrest

**Comment by ValWood** [comment]
In yeast you just get arrest, or 'catastrophe' . In metazoa I think such problems would lead to senescence or apoptosis but I don't know so much about that... anyway it seems a stretch to interpret this as some normal cell cycle event.

I don't think you can use this particular paper to annotate anything about the cell cycle (there is nothing about abortive mitotic cell cycle in the paper).
Maybe megakaryocyte development ?

**Comment by ValWood** [comment]
@hdrabkin  in the papers you used for 
abortive mitotic cell cycle,  this seems like a phenotype.

I think the annotations should be removed and the term obsoleted unless we have an actual example of "abortive mitotic cell cycle". Usually,  cessation   of the cell cycle in a normal context would be described as 'cell cycle arrest' not "abortive".

Abortive means "failing to produce the intended result." which sounds very pathological. Unless it can be renamed/defined correctly it should go.

**Comment by ValWood** [comment]
I have taken the ticket and I will proceed if you agree, and can take care of the phenotype annotations.

**Comment by ValWood** [comment]
Hi @hdrabkin  @pgaudet can I go ahead with this one?

**Comment by ValWood** [comment]
replaced by
https://github.com/geneontology/go-ontology/issues/24916
so I get the obsoletion task list
