### ISSUE TITLE
MP GO:0071038    nuclear polyadenylation-dependent tRNA catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20799]
GO:0071038    nuclear polyadenylation-dependent tRNA catabolic process

is no longer part of  GO:0016078    tRNA catabolic process 

(spotted because slim totals to "tRNA metabolism process" dropped)

**Comment by pgaudet** [comment]
This was requested here #20752

**Comment by pgaudet** [comment]
Maybe the parent 'RNA surveillance' , The set of processes involved in identifying and degrading defective or aberrant RNAs', should be part_of  GO:0006401 RNA catabolic process?

**Comment by ValWood** [comment]
I think 'RNA surveillance'  is already part_of GO:0006401 RNA catabolic process?
but "tRNA surveillance' is not part of tRNA catabolic process?
