### ISSUE TITLE
NTR:  effector-mediated supression of host defenses by symbiont

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20813]
NTR:  effector-mediated supression of host defenses by symbiont
Definition 
A process mediated by a molecule secreted by a symbiont that results in the modulation supression of a defense response. The host is defined as the larger of the organisms involved in a symbiotic interaction.

ref PMID:28082413

parents
GO:0140415    effector-mediated modulation of host defenses by symbiont
fix sp. in def suppresion -> supression
and
GO:0044414    suppression of host defenses by symbiont

**Comment by pgaudet** [comment]
> suppresion -> supression

Are you sure about that ? Is this a UK spelling ? https://en.wikipedia.org/?title=Supression&redirect=no

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140590
+name: effector-mediated suppression of host defenses by symbiont
+namespace: biological_process
+def: "A process mediated by a molecule secreted by a symbiont that results in the supression of a defense response. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:28082413]
+is_a: GO:0044414 ! suppression of host defenses by symbiont
+is_a: GO:0140415 ! effector-mediated modulation of host defenses by symbiont
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20813 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-08T07:26:05Z

**Comment by ValWood** [comment]
sorry, corrected it's fix sp. in def suppresion -> suppression. pp &ss
The def I copied has symbiont that results in the supression

**Comment by pgaudet** [comment]
Changed label from 'effector-mediated suppression of host defenses' to effector-mediated suppression of host **defense** response'
