### ISSUE TITLE
add taxon restriction to lysosomal terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20815]
In GO for fungi, lysosomes are represented by "vacuole" terms (even though the structures are equivalent.

So we should add "never in fungi' to all of the lysosomal terms (although in principle I would have no objection to a merge between the yeast-vacuole and the lysosome terms because sometimes  yeast researchers occasionally refer to vacuoles as lysosomes- and they should really be represented by the same terms in GO.

Or they will use 
https://www.nature.com/articles/s41598-019-47035-5 "Protein trafficking between the Golgi and the lysosome/vacuole"

**Comment by ValWood** [comment]
terms:

GO:0005764 | lysosome
GO:0043202 | lysosomal lumen
GO:0005765 | lysosomal membrane

**Comment by ValWood** [comment]
Also, we have this term, which is defined

"The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. In S. cerevisiae, the vacuole is the lysosomal compartment."

and appears to be used by yeast

**Comment by pgaudet** [comment]
The term you refer to is ' GO:0016237  lysosomal microautophagy' 

Should we create a new term, vacuolar autophagy, for cerevisiae ? 

@marcfeuermann @srengel 

Thanks, Pascale

**Comment by ValWood** [comment]
My feeling is that the community are fine with this being called  ' GO:0016237 lysosomal microautophagy'.

My concern is that we  are referring to the same structure  vacuole/lysosome in two ways in CC. This means that annotations are being inferred which gives us  duplicate annotation:


GO:0000329 | fungal-type vacuole membrane | IC from vacuolar proton-transporting V-type ATPase, V0 domain | GO_REF:0000111 | 120

- | GO:0005765 | lysosomal membrane | IBA with PTN000111953 , DDB_G0273071 | Gaudet P et al. (2011) | 2

so the lysosomal annotations are inconsistent and complete. We only really need to decide is it best to merge the vacuole terms into the corresponding lysosome terms, or add taxon restrictions to the lysosomal terms in the CC ontology. I was really using 
 
GO:0016237 lysosomal microautophagy
to illustrate that the yeast community seem to becoming comfortable using "lysosome" instead. Occasionally PomBase community have even used the lysosomal terms instead of the fungal vacuole branch, but I corrected these annotations to 'fungal-type vacuole'

We are supposed to indicate  orthologous structures using the same term in GO. Are there any reasons not to merge the vacuole and lysosome terms?

**Comment by pgaudet** [comment]
Again I will defer to @marcfeuermann and @srengel

**Comment by ValWood** [comment]
Maybe there are some fundamental differences that prevent a merge.
Possible from the def that the fungal vacuole has lytic and storage functions. It also might be too complicated  to merge  processes. 

If we just add the taxon restriction "never in yeast" to the "lysosome" component terms, that would be fine for now.

**Comment by pgaudet** [comment]
Yes but for logical definitions, CC and BPs need to match.

**Comment by srengel** [comment]
SGD curators are discussing; currently not loving the idea of mushing vacuole and lysosome terms together.  we do not agree that our community is comfortable using vacuole and lysosome terms interchangeably.  tagging @suzialeksander @robnash as part of convo.

**Comment by pgaudet** [comment]
Should we then split 'lysosomal microautophagy' into a yeast-specific term, 'vacuolar microautophagy'?

**Comment by ValWood** [comment]
Is it possibe to keep the vacuole and lysosome CC and add taxon restrictions,
and also keep the 'lysosomal microautophagy'  but make  the logical definition more generic  (GO:0000323   lytic vacuole) so that it applies to any vacuole. 
That seems that it would satisfy both issues. The term name is only a label.

**Comment by pgaudet** [comment]
Actually, looking at the definition of lysosomal microautophagy "The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. **In S. cerevisiae, the vacuole is the lysosomal compartment**.", I think this can stay as-is. 

I'll add the taxon restrictions on the CC's.
