### ISSUE TITLE
NTR for PTI's

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20814]
1. host cell apoplast 
standard def, define using GO:0048046    apoplast 

2. xyloglucan-specific endo-beta-1,4-glucanase inhibitor  activity

standard def using (GO:0033946 xyloglucan-specific endo-beta-1,4-glucanase activity)

ref for both:
PMID:28082413

**Comment by thomaspd** [comment]
host cell apoplast:
def: The apoplast region surrounding a host plant cell. Plants may be described as having two major compartments: the living symplast and the non-living apoplast. The apoplast is external to the plasma membrane and includes cell walls, intercellular spaces and the lumen of dead structures such as xylem vessels. Water and solutes pass freely through it. The host is defined as the larger of the organisms involved in a symbiotic interaction.
is_a parent: GO:0018995 host cellular component (in generic cellular component branch, it's under extracellular region, but the host branch doesn't have the parallel term)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140593
+name: host cell apoplast
+def: "The apoplast region surrounding a host plant cell. Plants may be described as having two major compartments: the living symplast and the non-living apoplast. The apoplast is external to the plasma membrane and includes cell walls, intercellular spaces and the lumen of dead structures such as xylem vessels. Water and solutes pass freely through it. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:28082413]
+xref: cellular_component
+is_a: GO:0033643 ! host cell part
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20814 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-09T18:56:11Z
+
+[Term]
+id: GO:0140594
+name: xyloglucan-specific endo-beta-1,4-glucanase inhibitor activity
+namespace: molecular_function
+def: "Stops, prevents or reduces the activity of xyloglucan-specific endo-beta-1,4-glucanase." [PMID:28082413]
+is_a: GO:0004857 ! enzyme inhibitor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20814 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-09T18:59:49Z
