### ISSUE TITLE
Merge 'GO:0008555 ATPase-coupled chloride transmembrane transporter activity ' into parent 'chloride transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20821]
Working on #17289

I came across GO:0008555 ATPase-coupled chloride transmembrane transporter activity links to EC:3.6.3.11, which has been deleted. Single EXP from RGD, citing a very old paper with no direct assay, but an IMP: "Application of antisense phosphorothioate oligonucleotides to cultured neurons resulted in a marked increase in the intracellular Cl(-) concentration ([Cl(-)](i)). Immunohistochemical analysis indicated that ClP55 was localized to the plasma membranes of neurons such as hippocampal pyramidal neurons and cerebellar Purkinje cells. Taken together, these results suggest that ClP55 is one of the Cl(-) pump subunits responsible for Cl(-) pump activity."

Moreover, the gene annotated is 'prenylcysteine oxidase 1', which is an enzyme, not a transporter (I suspect that it helps the transporter get to the membrane but I could not find evidence). @gthayman can you please have a look? 

- Given that this activity does not exist according to ECO, I will merge into GO:0015108 chloride transmembrane transporter activity
- There is also a cross reference to MetaCyc https://biocyc.org/META/NEW-IMAGE?type=NIL&object=3.6.3.11-RXN, which cross references EC:7.3.2.a (https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-7.3.2.a), but I cannot find that in EC. 
@kaxelsen 
@amandamackie

Thanks, Pascale

**Comment by pgaudet** [comment]
-  GO:0015407:  ATPase-coupled monosaccharide transmembrane transporter activity: There is no general (monosaccharide) transporter in EC, nor in Rhea. Keep as a grouping term.

**Comment by gthayman** [comment]
Annotation deleted.

**Comment by pgaudet** [comment]
Thanks!

**Comment by sjm41** [comment]
Hi @pgaudet 
When this merge happened, it looks like the final term (GO:0015108 chloride transmembrane transporter activity) retained the parent term "GO:0043225 ATPase-coupled inorganic anion transmembrane transporter activity".

Is that correct?  Are all chloride transporters ATPase-coupled?  The Rhea xref (https://www.rhea-db.org/rhea/29823) doesn't mention any ATP involvement. 

Maybe change parent to "GO:0015103 inorganic anion transmembrane transporter activity"?

Maybe also remove the "MetaCyc | 3.6.3.11-RXN" xref as this refers to the obsolete EC:3.6.3.11?

**Comment by sjm41** [comment]
Hi @pgaudet Can you look into my comment above?

**Comment by pgaudet** [comment]
Thanks for the reminder!

**Comment by sjm41** [comment]
Thanks @pgaudet.
I might be wrong, but seems from the 811cd7b commit that the immediate parent of GO:0015108 will end up as "GO:0022857 ! transmembrane transporter activity".
Could/should the immediate parent be "GO:0015103 inorganic anion transmembrane transporter activity" instead?

**Comment by pgaudet** [comment]
Having 'chloride' in the logical definition correctly classifies the term as 'inorganic anion transmembrane transporter activity' 

Thanks for checking!

**Comment by sjm41** [comment]
Aha, didn't know that!  Thanks!
