### ISSUE TITLE
MP: protein localization to nuclear inner membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20823]
should 
protein localization to nuclear inner membrane
have the parent
GO:0071765   nuclear inner membrane organization

**Comment by pgaudet** [comment]
Why ? Is all 'protein localization' to the inner membrane part if organization? For example I though some transcription factors localized to the inner membrane, but so that they are anchored there, and not necessarily  for organizing the inner membrane - isn't it ?

**Comment by ValWood** [comment]
yes you are right. I would not  use that term for those cases , but use the MF protein anchoring part_of the actual process (heterochromatin organization or whatever)

But I was looking at these:

nup155 | GO:0036228 | protein localization to nuclear inner membrane | IBA with S000000175 , PTN000039103 , FBgn0021761 | Gaudet P et al. (2011) | 2
nup44 |   | IBA with S000003351 , PTN000313393

which seemed odd, but there does seem to be a pathway 
https://www.yeastgenome.org/reference/S000146077
at first I thought this was just import, but  it does seem to be for the localization of inner membrane resident proteins.

It seems that the term to describe this process should be a little more specific. Is it transport?

**Comment by pgaudet** [comment]
For now this looks like an annotation question ? 

@srengel or @suzialeksander can you please have a look ? This annotation dates from 2012; it could be that the terms, annotation practices or data available have changed since ?

**Comment by ValWood** [comment]
I have asked a nuclear membrane expert how INM proteins are localized.

**Comment by srengel** [comment]
NUP57 is involved in maintaining the permeability barrier of the NPC.  it does this by placing proteins where they should go in the inner nuclear membrane.  i'm not inclined to change the annotation at this time.  it was done as part of a careful, comprehensive nuclear pore annotation revision and review.

**Comment by pgaudet** [comment]
Thanks @srengel 

I dont think there is any action needed, closing.
