### ISSUE TITLE
 GO:0034448 EGO complex  merge with GO:0071986 Ragulator complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20822]
GO:0034448 EGO complex 
only in ascomycetes (pombe and human have regulator which is  overlapping but slightly different in subunit composition)

https://github.com/geneontology/go-annotation/issues/3618

**Comment by pgaudet** [comment]
What term should human use ?

**Comment by ValWood** [comment]
Gtr1-Gtr2 GTPase complex for the GTPase  (although RAGA-RAGB might be a more generic name)
Ragulator complex for the GEF (LAMTOR1-5)

EGO complex is the GTPase plus 2 Ragulator subunits, and some other subunits that I can't find outside S. cerevisiae. They might be other LAMTORs but it is hard to tell, they are so tiny with no conservation.

**Comment by ValWood** [comment]
Actually, I was just sent a recent review:

Conserved and Divergent Mechanisms That Control TORC1 in Yeasts and Mammals
Yuichi Morozumi 1, Kazuhiro Shiozaki 1 2 PMID: 33445779
https://pubmed.ncbi.nlm.nih.gov/33445779/

EGO and Ragulator are equivalent, but  Gtr1 and Gtr2 aren't part of  Ragulator, they are a regulator substrate.

<img width="1116" alt="torc1-ragulator" src="https://user-images.githubusercontent.com/7359272/107348971-966dad00-6abf-11eb-88c8-b376d675679b.png">


<img width="1157" alt="torc1 signaling" src="https://user-images.githubusercontent.com/7359272/107349017-a1284200-6abf-11eb-9af0-aea47e041851.png">

Should we merge and label      Ragulator/EGO complex?

**Comment by ValWood** [comment]
@srengel

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/3618

**Comment by pgaudet** [comment]
Merge into 'Ragulator' and adjusted the definition as follows: 
+def: "A eukaryotic vacuolar membrane-associated protein; in humans, it is comprised of LAMTOR1, LAMTOR2, LAMTOR3, LAMTOR4, and LAMTOR5. In budding yeast, S. cerevisiae, this complex includes Gtr1p, Gtr2p, Meh1p, and Slm4p. The complex is anchored to lipid rafts in late endosome membranes via LAMTOR1, constitutes a guanine nucleotide exchange factor (GEF) for the Rag GTPases." [GOC:krc, GOC:lb, GOC:vw, PMID:15989961, PMID:16732272, PMID:19177150, PMID:19748353, PMID:20381137, PMID:22980980, PMID:29199950]

I saw paper where this part of the EGO def seems not to be valid anymore: "is required for activation of microautophagy during exit from rapamycin-induced growth arrest"

Thanks, Pascale

**Comment by ValWood** [comment]
Seems a weird thing to put in the def.

Rapamycin inhibits TOR, so this is a tool  to inhibit rather than describing the process. 

When TORC1 is active, growth/anabolic  processes are activated (protein synthesis, nucleotide synthesis, lipid synthesis)  and autophagy is inhibited. So just mentioning autophagy seems odd.
 Because TOR signalling regulates so many processes, for this complex it might be best to keep the def gloss  to the MF which is  as a scaffold to tether the RAG heterodimer to  lysosomal/vacuolar  membranes.

**Comment by pgaudet** [comment]
So, you are OK with the definition as it now is? "A eukaryotic vacuolar membrane-associated protein; in humans, it is comprised of LAMTOR1, LAMTOR2, LAMTOR3, LAMTOR4, and LAMTOR5. In budding yeast, S. cerevisiae, this complex includes Gtr1p, Gtr2p, Meh1p, and Slm4p. The complex is anchored to lipid rafts in late endosome membranes via LAMTOR1, constitutes a guanine nucleotide exchange factor (GEF) for the Rag GTPases."

**Comment by ValWood** [comment]
Small tweak, because the endosome membrane location isn't final destination

The complex is anchored to ~lipid rafts in late endosome membranes~ vacuole/lysosome membranes via LAMTOR1, constitutes a guanine nucleotide exchange factor (GEF) for the Rag GTPases (ADD as p[art of TORC1 signalling).

**Comment by pgaudet** [comment]
Thanks, changed to "The complex is anchored to lipid rafts in vacuole/lysosome membrane via LAMTOR1 and acts as a guanine nucleotide exchange factor (GEF) for the Rag GTPases."
