### ISSUE TITLE
New relationships after using equivalent Rhea reaction.

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#20839]
Dear GO curators,

As part of an ongoing research, I am rebuilding the Catalytic activity reactions using Rhea reactions.

After the use of equivalent reactions from the cross-references relation, new relationships inferred that made the glycine N-acyltransferase activity, GO:0047961 a superclass for the classes: glycine N-benzoyltransferase activity GO:0047962, and glycine N-choloyltransferase activity GO:0047963. 

My question is, are the new inferred relationships correct?

**Comment by balhoff** [comment]
Hi, as it happens we in GO have been working on possibly the very same thing. 😄 I have some code for generating OWL logical definitions for GO catalytic activities from the Rhea RDF. When I classify these reactions I get the same result as you, driven by the CHEBI classification. I can't say whether this is correct for the intent of the GO terms or not (@hdrabkin?)

I expect to be adding this into the ontology pipeline quite soon. Maybe we should compare approaches? You can see an example axiom in #20096.

**Comment by amorgat** [comment]
We (SIB) would be interested by the comparison of the two approaches because it can highlight the is-a relationships missing in the Rhea classification (missing in Rhea or missing in ChEBI). I add @muthuvenkat in the loop.

**Comment by Nizal-Shammry** [comment]
Yes it would be interesting to do the comparison once we complete all the catalytic classes.

> Hi, as it happens we in GO have been working on possibly the very same thing. 😄 I have some code for generating OWL logical definitions for GO catalytic activities from the Rhea RDF. When I classify these reactions I get the same result as you, driven by the CHEBI classification. I can't say whether this is correct for the intent of the GO terms or not (@hdrabkin?)
> 
> I expect to be adding this into the ontology pipeline quite soon. Maybe we should compare approaches? You can see an example axiom in #20096.

**Comment by balhoff** [comment]
@Nizal-Shammry @amorgat I started posting the latest rendering of our Rhea logical axioms here: `http://purl.obolibrary.org/obo/go/snapshot/extensions/rhea-reactions.ttl`

The hierarchy there is not complete unless you also import ChEBI and use an OWL reasoner. I'll close this issue if @hdrabkin or @pgaudet can answer whether it would make sense for that superclass relation to hold between those terms.

**Comment by hdrabkin** [comment]
Looking at the example, 
 glycine N-acyltransferase activity, GO:0047961 ; general; ANY N-acyl Co-A 
   glycine N-benzoyltransferase activity GO:0047962, Benzoyl-CoA; (benzoyl-CoA in CHEBI is_a acyl-Coa
    glycine N-choloyltransferase activity GO:0047963., choloyl-CoA; choloyl-CoA in CHEBI is a acyl-CoA

The classifier is that a cholic acid. vs a benzoic acid as a acid capable of forming a thioester with CoA, not overal strucure of cholic acid vs benzoiic acid (one being a steroilic acid, the other a benzoyl-acid; they both have COOH being organic acids.  I think the proposed relationships are ok.
