### ISSUE TITLE
Obsoletion notice:  GO:0072321 chaperone-mediated protein transport  and GO:0061741 chaperone-mediated protein transport involved in chaperone-mediated autophagy 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20850]
Dear all, 

The proposal has been made to obsolete 

* GO:0072321 chaperone-mediated protein transport
* GO:0061741 chaperone-mediated protein transport involved in chaperone-mediated autophagy 

The reason for obsoletion is that those represent a function within a process, and result in inconsistent annotations. 

There are 27 annotations to those terms, see https://github.com/geneontology/go-annotation/issues/3622
Suggestions have been made for reaannotation, but note that the new term has just been created, so it may not be immediately available in annotation tools. 

Contributor   (Assigned by)
--
AgBase | 1 Fixed
BHF-UCL | 10 
CACAO | 2
ComplexPortal | 3
EcoCyc | 5
FlyBase | 1
MGI | 1
PseudoCAP | 1
UniProt | 3

There are no mappings to those terms; those terms are not present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 17. Unless objections are received by February 17, 2021, we will assume that you agree to this change.
You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/20850
 
Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
please could you provide a link or information where the alternative GO term has been suggested - ie what is the alternative GO term. Also what was the problem with the chaperone-mediated protein transport term.
I have tried to follow the links to find this information but feel like I am just going round in circles. 
Thanks
Ruth

**Comment by pgaudet** [comment]
@RLovering Please check the annotation ticket: geneontology/go-annotation#3622

**Comment by pgaudet** [comment]
@RLovering (& others) - did you have a change to look at those ?

**Comment by RLovering** [comment]
Yes I have done what I can - waiting for new term
