### ISSUE TITLE
add a new GO term, beta-carotene isomerase

### ISSUE THREAD

**Issue by peifenz** [geneontology/go-ontology#20853]
GO term:  beta-carotene isomerase
definition: catalyzes the reaction: all-trans-beta-carotene = 9-cis-beta-carotene (EC 5.2.1.14)
reference: [PMID: 22422982] [PMID: 19470589]
suggested parentage:GO:0016859

Note, this new term is different from GO:0046608

Thanks, 
Peifen

**Comment by hdrabkin** [comment]
RHEA:34455

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106365
+name: beta-carotene isomerase activity
