### ISSUE TITLE
Remove logical definition for GO:0098772 'molecular function regulator'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#20854]
From discussion of the meaning of 'molecular function regulator' during the 2021 ontology jamboree, we propose to remove the current logical definition of GO:0098772 'molecular function regulator':

molecular_function 'directly regulates' some molecular_function

as this is not specific enough to define the class as it is intended to be used and results in unwanted inferences in GO-CAM models.

Note that we may still need to work on the textual definition of this term to make sure it's clearer to curators what types of activities this term encompasses.

**Comment by pgaudet** [comment]
GO:0098772 'molecular function regulator': 

- I removed the logical definition
- Fixed textual definition to "Binds to and modulates a molecular function. Examples include enzyme regulators and channel regulators."
- added Subclass "has_part GO:0005515 ! protein binding"



- Also fixed many (most?) children to (1) match the logical definition; (2) add a more precise class of protein binding when possible (for example, 'ion channel regulator activity' has part some 'ion channel binding', and (3) fixed textual definitions to start with "Binds to and modulates/increases the activity/stops, prevents or reduces the activity of some x."

Pascale
