### ISSUE TITLE
Document procedure for finding pH 7.3 version of a ChEBI term

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#20859]
Editors will need to find these when PRs fail the 7.3 check.

**Comment by balhoff** [comment]
The makefile should be updated to only update the pH 7.3 mappings when the chebi import is updated, and commit the mapping to this repo. Updates to Rhea's file currently can disrupt unrelated PRs.

**Comment by balhoff** [comment]
Page added: http://wiki.geneontology.org/index.php/Guidelines_for_using_ChEBI_terms

**Comment by pgaudet** [comment]
Thanks !
