### ISSUE TITLE
GO plus is inconsistent

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#20861]
From a brief look explanations I think the problem is the domain of regulates = biological_process but regulates is also used to define regulation of biological attributes:

![image](https://user-images.githubusercontent.com/112839/107680067-4b0cf780-6c95-11eb-9637-bc67efae68b2.png)
![image](https://user-images.githubusercontent.com/112839/107679976-257fee00-6c95-11eb-9a25-c3974db600e2.png)

The domain in RO is consistent with the defn of regulates.

Most obvious fix = add regulates_quality relationship to RO to use for regulation biological attributes.

**Comment by dosumis** [comment]
Version:

http://purl.obolibrary.org/obo/go/releases/2021-02-01/extensions/go-plus.owl

**Comment by balhoff** [comment]
I think you must be using ELK 0.5. :-) And this is probably a duplicate of #16524.

**Comment by dosumis** [comment]
You're right.  Closing.  Would be good to get a fix.
