### ISSUE TITLE
Merge 'ATP-dependent microtubule motor activity'and  'microtubule motor activity'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20878]
'microtubule motor activity' has a single child, 'ATP-dependent microtubule motor activity', check if they are all ATP-dependent. If they are, merge.

**Comment by ValWood** [comment]
I believe they are.  As far as I am aware  microtubule motors are ATP ases. There are GTPase motors involved in membrane scission like dynein. I could not find any GTPase microtubule motor (microtubule motors are all kinesin or dyneins and are all ATP dependent).

**Comment by pgaudet** [comment]
Duplicate of #18664
