### ISSUE TITLE
ATPases - proposal for having both a grouping class and an activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20876]
1. NTR: ATP hydrolysis activity: def: something like ATP + H20 = ADP + Pi
- xref: RHEA:13065
- xref:  MetaCyc:    ADENOSINETRIPHOSPHATASE-RXN

2.  GO:0016887 ATPase activity  -> change label to ATPase, move directly under MF. This is a grouping class for all reactions using ATP hydrolysis as an energy source.  
- logical def: molecular_function
and 'has part' some 'ATP hydrolysis activity'
- move all Reactome xrefs here

3. Current children of GO:0016887 ATPase activity: 
- move to 'main reaction' + add 'has part' some 'ATP hydrolysis activity'

For example: 'GO:0004176 ATP-dependent peptidase activity 
peptidase activity'
and 'has part' some 'ATP hydrolysis activity'

Thanks, Pascale

**Comment by pgaudet** [comment]
* GO:0016887 ATPase : def: A molecular function characterized by the use of ATP hydrolysis as an energy source, for example to catalyze a reaction or drive transport against a concentration gradient." [GOC:curators]

@thomaspd is this OK for describing the ATPase grouping class.

**Comment by pgaudet** [comment]
@thomaspd can you also check the def for the new term: 
GO:0140603
 name: ATP hydrolysis activity
 namespace: molecular_function
+def: "Catalysis of the reaction: ATP + H2O = ADP + H+ Pi. ATP hydrolysis is used in some reasctions as an energy source, for example to catalyze a reaction or drive transport against a concentration gradient." [RHEA:13065]

**Comment by hattrill** [comment]
tagging @sjm41

**Comment by pgaudet** [comment]
- make sure to add DO NOT annotate
- add DO NOT annotate comment

**Comment by sjm41** [comment]
Hi @pgaudet 
Can you clarify the parentage of the NTR "ATP hydrolysis activity"?  Will this basically go into the slot currently occupied by "ATPase activity" (so to be "ATPase"), i.e. child of nucleoside-triphosphatase activity (GO:0017111)?

tagging @ValWood

**Comment by sjm41** [comment]
I guess the idea here is to distinguish proteins whose primarily MF is an ATPase (assuming there are some?), from other proteins that hydrolyse ATP to perform some other primary MF (like your ATP-dependent peptidase example).  The latter would no longer get annotated as 'is a' ATPase, but would get inherit 'has part' ATPase.  Is that right? That seems different from what was agreed in the ontology editor calls at the end of last year, but maybe I'm misunderstanding.

**Comment by pgaudet** [comment]
@sjm41 

> Can you clarify the parentage of the NTR "ATP hydrolysis activity"? Will this basically go into the slot currently occupied by "ATPase activity" (so to be "ATPase"), i.e. child of nucleoside-triphosphatase activity (GO:0017111)?

Yes, and the new ATPase under molecular_function directly. 

Thanks, Pascale

**Comment by pgaudet** [comment]
> I guess the idea here is to distinguish proteins whose primarily MF is an ATPase (assuming there are some?), from other proteins that hydrolyse ATP to perform some other primary MF (like your ATP-dependent peptidase example). The latter would no longer get annotated as 'is a' ATPase, but would get inherit 'has part' ATPase. Is that right? That seems different from what was agreed in the ontology editor calls at the end of last year, but maybe I'm misunderstanding.

No, all ATPases hydrolyze ATP. AFAIK there are no proteins that hydrolyze ATP and have no other function. @thomaspd and I and looked at that, there was the futile ATPase cycle to generate heat, and even that is not solely ATPase activity, it's always coupled (see #16971) 

So the ATPase branch would not change, at least not due to this change. 

Please let me know if the is not clear. 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi @pgaudet just to confirm that FB is ok with this proposal.

**Comment by sjm41** [comment]
Thanks @pgaudet for the explanation, and thanks @hattrill for sharing the presentation.  Does make more sense now!

Just to check your example above:
_For example: 'GO:0004176 ATP-dependent peptidase activity
peptidase activity'
and 'has part' some 'ATP hydrolysis activity'_

This term would maintain its 'is_a' relationship to 'GO:0016887 ATPase', right?

**Comment by pgaudet** [comment]
Yes

**Comment by sjm41** [comment]
@pgaudet  I'm thinking that the new term "GO:0140603 ATP hydrolysis activity" should have the old term "GO:0016887 ATPase" as a parent?  It doesn't at the moment, which means anything annotated directly to "ATP hydrolysis activity" won't be classed as an "ATPase".  What do you think?

**Comment by sjm41** [comment]
Just re-opening this so that my last comment can be considered/addressed.

**Comment by pgaudet** [comment]
The whole point of having the 2 terms was to be able to state that 

ATPase
is_a molecular_function
 and ('has part' some 'ATP hydrolysis activity')

Using is_a it would defeat the purpose of what we did. Makes sense ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
to be a bit more explicit: 
The logical definition of ATPase ensure that any MF that has_part 'ATP hydrolysis activity' will be classified as an ATPase (ie with the is_a relationship). 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet. Yes, I understand the above, but I was trying to solve the following problem I've encountered while trying to review/remove FlyBase annotations to 'GO:0016887 ATPase' annotations (as we are now not supposed to use that term for direct annotation).

In many cases, the proteins annotated with 'GO:0016887 ATPase' already have (or can have) alternative/additional annotations to a more specific MF term that has_part 'ATP hydrolysis activity', so these are fine.

But I have a subset of proteins (many grouping into families - see below) where there appears to be no more specific ATPase-related term (i.e. with a "has_part ATP hydrolysis activity") to use, so I was thinking of replacing "GO:0016887 ATPase" on these with "GO:0140603 ATP hydrolysis activity" (which is available for direct annotation). But if I do that, these proteins won't get classified under 'GO:0016887 ATPase' as things stand...  Do you have an alternative suggestion of how to deal with these examples to ensure they still get classified under 'GO:0016887 ATPase'?

- STRUCTURAL MAINTENANCE OF CHROMOSOMES GENE FAMILY (https://flybase.org/reports/FBgg0000081)
- N-ETHYLMALEIMIDE-SENSITIVE FACTORS (https://flybase.org/reports/FBgg0000114)
- HEAT SHOCK PROTEIN 70 CHAPERONES (https://flybase.org/reports/FBgg0000497)
- HEAT SHOCK PROTEIN 60 CHAPERONINS (https://flybase.org/reports/FBgg0000503)
- HEAT SHOCK PROTEIN 90 CHAPERONES (https://flybase.org/reports/FBgg0000500)
- MUTL ATPASES (https://flybase.org/reports/FBgg0001598)
- other individual proteins under OTHER ATPASES (https://flybase.org/reports/FBgg0001600)

**Comment by pgaudet** [comment]
We probably need new children? 

Unless some activities **always** use ATP, like protein folding chaperone, that would cover HSP60, 70, 90, we could add 'has part' ATP hydrolysis activity. What do you think ?

**Comment by sjm41** [comment]
Making new children, or adding the ATPase relationship to existing terms, should work, at least where there are well-defined MFs that are ATP-dependent.  So, for the "protein folding chaperone (GO:0044183)" example, we could give that an additional 'ATPase' parent and tweak the definition to mention ATP-dependency, right?  That said, I see there are already "ATP-dependent chaperone mediated protein folding (GO:0061992)" and "ATP-independent chaperone mediated protein folding (GO:1990507)" BP terms, suggesting they aren't always ATPases....

But I'm not sure that approach is going to work for all cases.  There are lots of individual proteins (from all species) and InterPro2GO annotations with "GO:0016887 ATPase" that in theory now need to be re-annotated to a different term (if GO:0016887 ATPase is not to be used for direct annotation).  At least in some cases, it seems appropriate to reannotate to "GO:0140603 ATP hydrolysis activity" (because the paper shows an ATPase assay, for example), but then such annotations wouldn't get mapped up to 'ATPase'....

**Comment by bmeldal** [comment]
I didn't get a notification that GO:0016887 ATPase is now do-not-annotate. I now have 194 syntax errors for complexes! First complex includes VCP (P55072). 

UniProt def: "...Vesicle budding from the tER is an ATP-dependent process...."

CP def: "Promotes membrane fusion of nucleus-, endoplasmic reticulum-, and Golgi apparatus-derived membranes."

There is no suitable child for "acting on membranes" at the moment.

Do I move them all over to GO:0140603 ATP hydrolysis activity or do I request new child terms were required?

This is case 1 of 194. Case 2 is acting on DNA so I can move to a child. But this could take time, having to check them all individually.

Any advice? Just a case of slowly working through 194 entries?

**Comment by deustp01** [comment]
> @thomaspd can you also check the def for the new term:
> GO:0140603
> name: ATP hydrolysis activity
> namespace: molecular_function
> +def: "Catalysis of the reaction: ATP + H2O = ADP + H+ Pi. ATP hydrolysis is used in some reactions as an energy source, for example to catalyze a reaction or drive transport against a concentration gradient." [RHEA:13065]

Coming in very late. ATP hydrolysis does not really catalyze reactions that are otherwise unfavorable. Rather, some reaction mechanism magic incorporates the hydrolysis of an ATP molecule into the steps of the reaction so that it is now energetically favorable.
Possible alternative wording of the definition:
... ATP hydrolysis is used in some reactions as an energy source, for example coupled to other steps of a reaction mechanism to make the reaction energetically favorable, or to the other steps of a transport reaction to drive it against a concentration gradient."

**Comment by pgaudet** [comment]
Open issues in this tickets (and more) will be addressed at the June 2021 ATPase jamboree. See project here: 
https://github.com/orgs/geneontology/projects/64
