### ISSUE TITLE
What's the difference between 'protein-DNA loading ATPase activity' and 'DNA clamp loader activity'? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20880]
'protein-DNA loading ATPase activity' has no annotations
and 'DNA clamp loader activity'

@ValWood I think you requested those terms - can you help ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I used  protein-DNA loading ATPase activity
with TAS for 

nuclear DNA replication factor C complex
and the rfc-like complexes

GO:0031390 | Ctf18 RFC-like complex
GO:0031391 | Elg1 RFC-like complex
GO:0031389 | Rad17 RFC-like complex

but
protein-DNA loading ATPase activity
also applies to
DNA recombinase assembly
and recombinase isn't a clampbut I'm a bit vague in this area.

**Comment by ValWood** [comment]
this might help because IIRC "recombinase assembly"
 involves loading recombinase onto DNA and requires ATPase activity 

GO:0000730 | DNA recombinase assembly | IBA with Q06609 , S000002411 , rad57 , PTN001415033

**Comment by pgaudet** [comment]
There is only one paper annotated with 'protein-DNA loading ATPase activity', (pombase) PMID:17353272, using TAS, annotating 4 proteins, rad51, rad54, rad55, rad57, and all have other MFs - either DNA recombinase activity (rad51 & rad57),  DNA translocase activity (rad54), crossover junction endodeoxyribonuclease activity (rad55). 

Given that 'protein-DNA loading ATPase activity' is quite vague - should we merge or obsolete it ? Would that be OK for you ?

**Comment by ValWood** [comment]
Yeah, go ahead!

**Comment by mah11** [comment]
For future searches: GO:0033170 has been merged into GO:0003689 (despite the discussion in #14535 and the resulting decision not to merge).

It is not clear to me that "DNA clamp loader activity" applies to the gene products we've annotated to GO:0033170, so I'll delete the annotations.
