### ISSUE TITLE
Fix unicity check on Rhea xrefs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20882]
Hello, 

@balhoff has recently implemented a check that allows RHEA xrefs to only be used once in the ontology. 
We want to make the following changes: 
1. Add skos xref type = EXACT for all current Rheas
2. Fix the check so that EXACT and NARROW xrefs can only be used in a single GO term
3. Allow more than one use of a xref for BROAD xrefs

Thanks, Pascale

**Comment by pgaudet** [comment]
@balhoff I thought this was done?

**Comment by balhoff** [comment]
@pgaudet it is implemented, although I just tweaked it (to be committed) so that it enforces NARROW along with EXACT. There are 3 violations to be fixed before I commit my change:

- RHEA:17989: GO:0004674; GO:0106310; GO:0004712
- RHEA:46608: GO:0004674; GO:0004712
- RHEA:10596: GO:0004713; GO:0004712

**Comment by balhoff** [comment]
@pgaudet or @hdrabkin could you take a look at those 3 RHEA xrefs above?

**Comment by hdrabkin** [comment]
RHEA:17989 is the RHEA reaction specifically for the reaction using SERINE only; RHEA does not do either/or . It's ok to use it for GO:0106310 (only mentions serine in def) but should NOT be mapped to the other two (serine/threonine).
Likewise, RHEA:46608 is the reaction specifically for the reaction using THREONINE. There is now no longer a GO term specific to threonine only; Mapping to the serine/threonine terms seems incorrect. Remove RHEA for both.
RHEA:10596 is specific for tyrosine; mapping to GO:0004713 seems ok, but not to GO:0004712
@pgaudet do you agree?

**Comment by pgaudet** [comment]
@hdrabkin thanks for the comment - I wonder though, since RHEA doesn't represent dual specificity, do you mean to say we can only use RHEA:10596 ? (threonine?) 

Anyway, as they are, the mappings are causing bad inferences, see https://github.com/geneontology/go-annotation/issues/4021 - but I am not sure why, is it that narrowMatch should not be propagated? 

Anyway maybe these xrefs should be removed for now, although longer term we need to plan how to map GO terms to RHEA terms, and design rules that provide correct inferences. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
So the only time we could use the RHEA for the theronine is if was had a threonine only GO term, which we don't. 
IT makes more sense to me if for the dual specificity terms (ser/thr), we COULD map as narrow xref both the serine RHEA and the threonine RHEA; We obviously couldn't use them for logical defs though. 
I didn't realize two uses of a narrow xref would be trouble. However, I can remove them as I indicated above, and this ticket can be used to put them back if we need to (as narrow).

**Comment by pgaudet** [comment]
Hi @hdrabkin 

I think what you suggest works. Thanks, Pascale

**Comment by hdrabkin** [comment]
RHEA:17989 removed from GO:0004674 and GO:0004712
RHEA:46608  removed from GO:0004712 and GO:0004674
RHEA:10596 removed from GO:0004712
