### ISSUE TITLE
Query     GO:0002246 wound healing involved in inflammatory response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20900]
Hello, 

@RLovering your group has annotated to this term 
 GO:0002246 wound healing involved in inflammatory response  - definition is "The series of events that restore integrity to damaged tissue that contribute to an inflammatory response. "

This term has two 'part_of' children: 
GO:0002247 clearance of damaged tissue involved in inflammatory response wound healing
 GO:0002248 connective tissue replacement involved in inflammatory response wound healing 
(definitions are similar to the term above). 

But I think what is really meant is something like 'inflammatory injury healing' - is this right ? 

Thanks, Pascale

**Comment by RLovering** [comment]
that sounds likely

**Comment by pgaudet** [comment]
Not sure what the intended action was here
