### ISSUE TITLE
P-type manganese transporter activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#20918]
Dear GO curators,

Would it be possible to create

new_GO: P-type manganese transporter activity
as child of GO:0005384

Definition:
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Mn2+(in) = ADP + H+ + Mn2+(out) + phosphate - RHEA:66820; PMID:11134055; PMID:21187401; PMID:15831496; 
review to cite: PMID:15590060

Many thanks for your help,
Nevila Hyka-Nouspikel

**Comment by pgaudet** [comment]
The annotations for GO:0015410 are essentially all to members of the PTHR family PTHR42861. 

EC links to 7.2.2.10 P-type Ca(2+) transporter. 

Rhea:66820 doesn't exist yet ? 
I wonder if we shouldn't change the term label to P-type calcium/manganese transporter activity instead?

**Comment by nnouspikel** [comment]
Thanks Pascale for the feedback.
Rhea:66820 was recently created and it's not yet public.
As mapping GO <-> RHEA is 1:1 it will be best to keep P-type manganese transporter activity. To be discussed with RHEA team.
GO:0015410 <-> RHEA:17365; ABC-type Mn2+ transporter;  EC 7.2.2.5
A+

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140613
+name: P-type manganese transporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Mn2+(in) = ADP + H+ + Mn2+(out) + phosphate." [PMID:11134055, PMID:15590060, PMID:15831496, PMID:21187401, RHEA:66820]
+xref: RHEA:66820
+is_a: GO:0140358 ! P-type transmembrane transporter activity
+intersection_of: GO:0140358 ! P-type transmembrane transporter activity
+intersection_of: transports_or_maintains_localization_of CHEBI:25155 ! manganese cation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20918 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-03T22:11:36Z
