### ISSUE TITLE
heme-copper terminal oxidase activity (GO:0015002) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20924]
I _think_

id: GO:0015002
name: heme-copper terminal oxidase activity
namespace: molecular_function
def: "Catalysis of the four-electron reduction of dioxygen (O2) to water, coupled to generation of a proton electrochemical gradient across a membrane." [GOC:kd]
synonym: "haem-copper terminal oxidase activity" EXACT []
is_a: GO:0016491 ! oxidoreductase activity

should be a child of:

id: GO:0016676
name: oxidoreductase activity, acting on a heme group of donors, oxygen as acceptor
namespace: molecular_function
def: "Catalysis of an oxidation-reduction (redox) reaction in which a heme group acts as a hydrogen or electron donor and reduces oxygen." [GOC:jl]
synonym: "oxidoreductase activity, acting on haem group of donors, oxygen as acceptor" EXACT []
xref: EC:1.9.3.-
is_a: GO:0016675 ! oxidoreductase activity, acting on a heme group of donors

??

**Comment by pgaudet** [comment]
cytochrome o  is the same as cytochrome bo3, see for eg https://www.uniprot.org/uniprot/P0ABJ6#names_and_taxonomy, so I will merge:  

* GO:0008827  cytochrome o ubiquinol oxidase activity into GO:0009486 cytochrome bo3 ubiquinol oxidase activity

**Comment by pgaudet** [comment]
I wonder if the term 'heme-copper terminal oxidase activity (GO:0015002)' is useful WRT MF: the 'terminal' aspect just means that its the end of the pathway. 

I think I can move 'cytochrome bo3 ubiquinol oxidase activity' under 'electron transfer activity' (the other descendant, 'cytochrome-c oxidase activity', is already under that term), and obsolete  'heme-copper terminal oxidase activity (GO:0015002)' - no annotations. 

@sjm41 What do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I think 'GO:0009319 cytochrome o ubiquinol oxidase complex' should be renamed 'cytochrome bo3 ubiquinol oxidase complex' for consistency. @bmeldal Is that OK for you ? I see there is CPX-2102﻿, Cytochrome o ubiquinol oxidase complex in Complex Portal.

**Comment by pgaudet** [comment]
Also added taxon constraint: GO:0009486	cytochrome bo3 ubiquinol oxidase activity	NCBITaxon:2	Bacteria

**Comment by sjm41** [comment]
_I think I can move 'cytochrome bo3 ubiquinol oxidase activity' under 'electron transfer activity' (the other descendant, 'cytochrome-c oxidase activity', is already under that term), and obsolete 'heme-copper terminal oxidase activity (GO:0015002)' - no annotations._

That's fine from my point of view.
Note that "cytochrome-c oxidase activity" currently has 3 parents - it will still have two after the proposed obsoletion.
From that view, should probably add "oxidoreductase activity, acting on a heme group of donors, oxygen as acceptor" as second parent of "cytochrome bo3 ubiquinol oxidase activity" (assuming that's accurate).

**Comment by pgaudet** [comment]
OK thanks !

**Comment by pgaudet** [comment]
Ohhhh ! This term was obsoleted 
https://github.com/geneontology/go-ontology/issues/20923

So I will move cytochrome bo3 ubiquinol oxidase activity and 'cytochrome-c oxidase activity' under 
'oxidoreductase activity, acting on a heme group of donors'

**Comment by sjm41** [comment]
BTW, similar tweak needed on #20616

**Comment by pgaudet** [comment]
First - I added the missing parents. 

For GO:0015002 heme-copper terminal oxidase activity: There are 3 InterPro mappings to GO:0015002 heme-copper terminal oxidase activity

* InterPro:IPR000298 -> easy: change to GO:0004129 cytochrome-c oxidase activity + update EC to EC:7.1.1.9
* InterPro:IPR024791 and InterPro:IPR035973 are more complicated: those 2 entries refer to two enzymes; the InterPro entry states "Even though the cytochrome o complex oxidises quinol (ubiquinol) and does not catalyse the oxidation of reduced cytochrome c, they belong to the same haem-copper oxidase superfamily as cytochrome c oxidases. "
-> could it be mapped to a more general term such as 'electron transfer activity' ? 

@sarach06 @EBI-Hsinyu would that work? 

Thanks, Pascale

**Comment by bmeldal** [comment]
> I think 'GO:0009319 cytochrome o ubiquinol oxidase complex' should be renamed 'cytochrome bo3 ubiquinol oxidase complex' for consistency. @bmeldal Is that OK for you ? I see there is CPX-2102﻿, Cytochrome o ubiquinol oxidase complex in Complex Portal.

No problem, I've made the name change in CP.

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this. I have done the changes you mentioned and checked the related entries. For IPR024791 and IPR035973, yes, electron transfer activity is ok. The changes will be available in the next InterPro release (85.0).

Best regards,
Sara
