### ISSUE TITLE
change def of GO:0072380 TRC complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#20920]
The current def is confusing the TRC and GO:0043529 GET complex functions. TRC transfers TA proteins to GET3 which then forms GET complex at the ER membrane.

GO:0072380 TRC complex

-Def: An ER membrane insertion complex that contains subunits that recognize two types of transmembrane domain signals. In budding yeast the complex contains Get4p, Get5p, Sgt2p, and at least two heat shock proteins (HSPs).

+Def: yeast complex that transfers tail-anchored (TA) proteins to GET3 for targeting to the endoplasmic reticulum membrane. In budding yeast the complex contains GET4, MDY2 (GET5), SGT2, and at least two heat shock proteins, HSP104 and YBR137W.

This is the yeast ortholog of mammalian GO:0071818 BAT3 complex. But it looks like the mammalian complex has additional functions in ERAD. 

CP: https://www.ebi.ac.uk/complexportal/complex/CPX-1861 (I made some edits that are not yet released). 

PMID:20850366

**Comment by bmeldal** [comment]
related to: https://github.com/geneontology/go-ontology/issues/20919

**Comment by ValWood** [comment]
HIi Birgit

did you see
https://github.com/geneontology/go-ontology/issues/20889
https://github.com/geneontology/go-ontology/issues/20888
last week. I think they are separate complexes.

see
https://github.com/geneontology/go-annotation/issues/3629

human seems to have TRC?GE4 complex and BAT complex. Pombe does not seem to have the any BAT complex subunits *except * for Get4 which is shared?

**Comment by bmeldal** [comment]
Yes, they seem to be functional rather than sequence orthologs, I should have worded that better ;-)

(I don't see tickets unless I'm tagged or it comes through as announcements (e.g. obsoletions) as I never remember to look at the issues lists)

**Comment by ValWood** [comment]
sorry, I meant to tag you.
I tried to see if they merged last week, and had a good look for orthologs with jackhammer and  psi-blast, but could not find   bag6 in pombe or cerevisiae.

**Comment by pgaudet** [comment]
I reordered the definition to put the functional part at the end: "A protein complex found in yeast that contains GET4, MDY2 (GET5), SGT2, and at least two heat shock proteins, HSP104 and YBR137W. The TRC complex transfers tail-anchored (TA) proteins to GET3 for targeting to the endoplasmic reticulum membrane."

let me know if you prefer the other way around, but I think the function last is more standard.

Is that all you guys wanted? 

Thanks, Pascape
