### ISSUE TITLE
guanosine-containing compound catabolic process (GO:1901069) is not a GO:0046130 purine ribonucleoside catabolic process

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#20921]
Guanine-containing compounds can also be purine nucleotides. This may be a ChEBI issue or an issue with the choice of differentia for the equivalence axiom depending on the response we get from ChEBI.
I opened a query at ChEBI:
https://github.com/ebi-chebi/ChEBI/issues/4003
This was part of the Pathways2GO work.

**Comment by pgaudet** [comment]
So, so far there is no action for ontology editors, is this right ?

**Comment by ukemi** [comment]
Correct. We need ChEBI to clarify.

**Comment by ukemi** [comment]
Should be fixed by changes in ChEBI. We can check once the changes percolate through the system and then we can close this ticket.

**Comment by ukemi** [comment]
This should also fix the mis-classifiaction of GMP salvage (GO:0032263).

**Comment by pgaudet** [comment]
Not fixed yet

**Comment by pgaudet** [comment]
Now fixed

<img width="621" alt="image" src="https://user-images.githubusercontent.com/4782928/112183938-031bb180-8bff-11eb-9a70-e345987d0b69.png">

**Comment by pgaudet** [comment]
As well as GMP salvage

<img width="606" alt="image" src="https://user-images.githubusercontent.com/4782928/112184070-26466100-8bff-11eb-8b0a-235e41cc1fb3.png">
