### ISSUE TITLE
GO:0016676 - remove EC:1.9.3.- xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20923]
id: GO:0016676
name: oxidoreductase activity, acting on a heme group of donors, oxygen as acceptor
xref: EC:1.9.3.-

This EC grouping doesn't exist anymore - previous two 4-digit EC now map to different branches, so I think just remove xref from GO term.
https://enzyme.expasy.org/EC/1.9.3.-

**Comment by pgaudet** [comment]
I will propose to obsolete 'GO:0016676 oxidoreductase activity, acting on a heme group of donors, oxygen as acceptor'. This is now a grouping class with no children.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0016676 oxidoreductase activity, acting on a heme group of donors, oxygen as acceptor'. The reason for obsoletion is that this term was created to align with the Enzyme Commission (EC) hierarchy, but all specific children classes have been moved in EC, such that this is now an empty grouping term, see https://enzyme.expasy.org/EC/1.9.3.-. 

There are no direct annotations to this term, and no other mappings to this term; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/20923

 
Thanks, Pascale
