### ISSUE TITLE
GO:0042775   mitochondrial ATP synthesis coupled electron transport, parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20922]
GO:0042775   mitochondrial ATP synthesis coupled electron transport

shouldn't this term  be a descendant of 
GO:0009060    aerobic respiration
(not just respiration?)

**Comment by ValWood** [comment]
should we look at this one?

**Comment by pgaudet** [comment]
This seems right 
http://hyperphysics.phy-astr.gsu.edu/hbase/Biology/celres.html

**Comment by pgaudet** [comment]
oxidative phosphorylation -> 
* remove parent 'phosphorylation
* add subclass 'aerobic respiration'

**Comment by pgaudet** [comment]
* GO:0006120 mitochondrial electron transport, NADH to ubiquinone
* GO:0006121 mitochondrial electron transport, succinate to ubiquinone
* GO:0006122 mitochondrial electron transport, ubiquinol to cytochrome c 

-> move down to  GO:0019646 aerobic electron transport chain

**Comment by pgaudet** [comment]
GO:0019646 aerobic electron transport chain
add: 
'part of' some 'oxidative phosphorylation'

**Comment by pgaudet** [comment]
GO:0006119 oxidative phosphorylation
  [is_a relation] GO:0042776 mitochondrial ATP synthesis coupled proton transport 

change relation of 'part of' (also this will be consistent with  GO:0006119 oxidative phosphorylation
 [part_of relation] GO:0042773 ATP synthesis coupled electron transport
