### ISSUE TITLE
Add related  synonym : GO:0110044  regulation of cell cycle switching, mitotic to meiotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20926]
In  yeast, this is the term people. mean for the process described "loosely" as "sexual  differentiation". Could this be added as a 'related synonym'?

**Comment by pgaudet** [comment]
I added the synonym, and a couple of references I found, to show that this related to yeast: 
+synonym: "sexual differentiation" RELATED [PMID:30922219, PMID:32788233]


Let me know if there are better references. 


ALSO -  is this only valid for 'regulation', or also to the normal term 'cell cycle switching, mitotic to meiotic cell cycle'? 

Thanks, Pascale

**Comment by ValWood** [comment]
Also for the normal term.
"'cell cycle switching, mitotic to meiotic cell cycle'
