### ISSUE TITLE
GO:0007050  cell cycle arrest

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20935]
GO:0007050  cell cycle arrest
Definition 
A regulatory process that halts progression through the cell cycle during one of the normal phases (G1, S, G2, M).

arrest of cell cycle progression | exact
cessation of cell cycle | exact
termination of cell cycle | exact

This term is only for use with cell which are permanently arrested as part of a normal process, or where the cell cycle is exited  for some other reason (i.e. to enter  meiosis/ apoptosis/senescence).

~The descendant term
GO:0071850    mitotic cell cycle arrest
is equivalent. I don't think there is a meiotic equivalent 'normal ' process.~

Could we 
1. Make this term not  direct annotation ? (on its own it isn't very useful because the context is very different)
2. Add a comment that it is only for complete arrest  (not transient) or cell cycle exit and  not for cell cycle checkpoints which halt the cycle temporarily in order to fix a problem (if a problem cannot be fixed, arrest will result, but this is an undesirable phenotype).
~3. Merge GO:0007050  cell cycle arrest and GO:0071850  mitotic cell cycle arrest~

from
https://github.com/geneontology/go-annotation/issues/3647

**Comment by mah11** [comment]
1. OK, AFAIK
2. OK
3. Will not work for bigger eukaryotes.

Mammalian oocytes arrest in metaphase of meiosis II until fertilization (can be decades in humans).
[example review](https://celldiv.biomedcentral.com/articles/10.1186/1747-1028-2-4)

**Comment by ValWood** [comment]
Of course, so meiotic cell cycle arrest is needed. There is no term `at present.

**Comment by pgaudet** [comment]
@ValWood will get feedback from Jackie to make a proposal for this one.

**Comment by pgaudet** [comment]
Discussion with Jackie and @ValWood 

 - [x] Merge GO:0072450 signal transduction involved in G1 cell size control checkpoint into GO:0031568 G1 cell size control checkpoint
 - [x] change label GO:0031568 G1 cell size control checkpoint signaling
 - [ ] obsolete  GO:0072448  detection of stimulus involved in G1 cell size control checkpoint and all other 'detection' terms in this area, see #20976 20976

**Comment by pgaudet** [comment]
- [ ] Merge 'GO:0072453  signal transduction involved in G2 cell size control checkpoint' into GO:0031569 mitotic G2 cell size control checkpoint
 - [ ]   change label GO:0031569 G2 cell size control checkpoint signaling

**Comment by pgaudet** [comment]
- [ ] Merge   GO:0072471 signal transduction involved in cell size control checkpoint into     GO:0031567  mitotic cell size control checkpoint 
 - [ ]  change label  GO:0031567 mitotic cell size control checkpoint signaling

**Comment by pgaudet** [comment]
* GO:0072431 | 'signal   transduction involved in mitotic G1 DNA damage checkpoint' | -> merge into GO:0031571 mitotic G1 DNA damage checkpoint; change   label to 'mitotic G1 DNA damage checkpoint signaling'

* GO:1902400 | 'intracellular signal transduction   involved in G1 DNA damage checkpoint' | -> merge into GO:0031571   mitotic G1 DNA damage checkpoint; change label to 'mitotic G1 DNA damage   checkpoint signaling'

* GO:0072425 | 'signal transduction involved in G2   DNA damage checkpoint' | -> merge into GO:0007095   mitotic G2 DNA damage checkpoint; change label to 'mitotic G2 DNA damage   checkpoint signaling'
* GO:0072434 | 'signal transduction involved in   mitotic G2 DNA damage checkpoint' | -> merge into GO:0007095   mitotic G2 DNA damage checkpoint; change label to 'mitotic G2 DNA damage   checkpoint signaling'
* GO:1902504 | 'regulation of signal transduction   involved in mitotic G2 DNA damage checkpoint' | -> merge into GO:0007095   mitotic G2 DNA damage checkpoint; change label to 'mitotic G2 DNA damage   checkpoint signaling'
* GO:1902505 | 'negative regulation of signal   transduction involved in mitotic G2 DNA damage checkpoint' | -> merge into GO:0007095   mitotic G2 DNA damage checkpoint; change label to 'mitotic G2 DNA damage   checkpoint signaling'
* GO:1902506 | 'positive regulation of signal   transduction involved in mitotic G2 DNA damage checkpoint' | -> merge into GO:0007095   mitotic G2 DNA damage checkpoint; change label to 'mitotic G2 DNA damage   checkpoint signaling'

**Comment by pgaudet** [comment]
GO:0072437	'signal transduction involved in DNA replication checkpoint' 
GO:0072440	'signal transduction involved in meiotic DNA replication checkpoint' 
GO:0072443	'signal transduction involved in mitotic DNA replication checkpoint'

**Comment by ValWood** [comment]
Once we finish this should revisit definitions:
A cell cycle checkpoint that acts during blah and prevents blah until blah, thereby ensuring blah. An blah checkpoint begins when blah is sensed and blah is recruited to initiate checkpoint signalling and ends when effector molecules for the "response to x checkpoint* are phosphorylated.

(I also have some notes  from a discussion with Paul Russell and Nick Rhind  which revises the DNA integrity checkpoint definitions, but I never finalised it so it isn't on the tracker yet. We can look at these once the bigger structural changes are done)

**Comment by pgaudet** [comment]
- [x] Merge  'GO:0044783 G1 DNA damage checkpoint' (3 EXP, experiments done in mitotic cells) into 
'GO:0031571 mitotic G1 DNA damage checkpoint

**Comment by pgaudet** [comment]
- [x] Merge   GO:0031572  G2 DNA damage checkpoint into GO:0007095 mitotic G2 DNA damage checkpoint -> 4 EXP from a single paper, experiments done in mitotic cells

**Comment by pgaudet** [comment]
- [x] After we can check meiotic checkpoints, for example here: https://cshperspectives.cshlp.org/content/6/10/a016675.full

**Comment by pgaudet** [comment]
@ValWood Can you check the current parentage of GO:0072443 signal transduction involved in mitotic DNA replication checkpoint? 

<img width="853" alt="image" src="https://user-images.githubusercontent.com/4782928/109631518-4e81f900-7b46-11eb-959d-db590649c106.png">

**Comment by pgaudet** [comment]
Top level class: GO:0000075 cell cycle checkpoint 

 - [ ]  -> change label to cell cycle checkpoint signaling
 - [ ] Fix subclasses: 
-is_a: GO:0009987 ! cellular process
-is_a: GO:0045786 ! negative regulation of cell cycle
-relationship: ends_with GO:0007165 ! signal transduction
+is_a: GO:0035556 ! intracellular signal transduction
+relationship: negatively_regulates GO:0044770 ! cell cycle phase transition

**Comment by pgaudet** [comment]
- [x] Merge GO:0072411	signal transduction involved in meiotic cell cycle checkpoint' into GO:0033313 meiotic cell cycle checkpoint signaling
 - [x] Merge GO:0072465	'signal transduction involved in meiotic spindle assembly checkpoint'  into GO:0033316	meiotic spindle assembly checkpoint

**Comment by ValWood** [comment]
>@ValWood Can you check the current parentage of GO:0072443 signal transduction involved in mitotic DNA replication checkpoint?

That is correct. Replication checkpoint occurs in S-phase  but causes a G2 block if S-phase did not complete.

**Comment by pgaudet** [comment]
so it would be 'negatively regulates mitotic G2/M transition', and not is_a, right ?

**Comment by pgaudet** [comment]
- [x]  Merge GO:1903820 signal transduction involved in mitotic cytokinesis checkpoint  into 
GO:0044878	mitotic cytokinesis checkpoint ; change label to mitotic cytokinesis checkpoint signaling

**Comment by ValWood** [comment]
>so it would be 'negatively regulates mitotic G2/M transition', and not is_a, right ?

I think it is  really part_of

There are multiple checkpoint pathways converging (stress, cell size, DNA damage, replication), which in combination
contribute to 
negative regulation of G2/M transition of mitotic cell cycle

**Comment by pgaudet** [comment]
Merge 
GO:0072424 detection of DNA damage stimulus involved in G2 DNA damage checkpoint
into  GO:0072433 detection of DNA damage stimulus involved in mitotic G2 DNA damage checkpoint 
- No annotations to either term
- - Now equivalent, with merges already done

**Comment by pgaudet** [comment]
- [x]  Merge GO:0072483 signal transduction involved in mitotic cell cycle spindle orientation checkpoint GO:0031578 	mitotic spindle orientation checkpoint; change label to mitotic spindle orientation checkpoint signaling
 - [x]  Merge GO:0072486 signal transduction involved in spindle assembly checkpoint into GO:0071173 spindle assembly checkpoint; change label to spindle assembly checkpoint signaling
 - [x]  Merge GO:0072413 signal transduction involved in mitotic cell cycle checkpoint into	GO:0007093 mitotic cell cycle checkpoint signaling
 - [x]  Merge GO:0072416	signal transduction involved in spindle checkpoint 	into GO:0031577	spindle checkpoint signaling
 - [x]  Merge GO:0072477	signal transduction involved in mitotic spindle checkpoint	into GO:0071174	mitotic spindle checkpoint signaling
 - [x]  GO:0072462	signal transduction involved in meiotic recombination checkpoint 	GO:0051598	meiotic recombination checkpoint signaling
 - [x]  GO:1903822	signal transduction involved in morphogenesis checkpoint into GO:0044879 morphogenesis checkpoint; change label to 'mitotic morphogenesis checkpoint signaling'
 - [x]  GO:1902403	signal transduction involved in mitotic DNA integrity checkpoint into	GO:0044774  mitotic DNA integrity checkpoint'; change label to mitotic DNA integrity checkpoint signaling 	
 - [x]  GO:0072401	'signal transduction involved in DNA integrity checkpoint' into	GO:0031570	DNA integrity checkpoint
 - [x]  GO:0072395	'signal transduction involved in cell cycle checkpoint' into GO:0000075 cell cycle checkpoint signaling

**Comment by pgaudet** [comment]
Not yet done: 
- signal transduction involved in cell cycle switching, mitotic to meiotic cell cycle, child of intracellular signaling
- GO:0072398 | signal transduction involved in cytokinesis   checkpoint'; don't know what to merge into; the equivalent checkpoint term was obsoleted. The 'mitotic' version is ok, merged into GO:0044878	mitotic cytokinesis checkpoint

**Comment by pgaudet** [comment]
This is the current structure of the ontology - could use improvement but with @ValWood we agree this is enough improvement 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/4782928/109776983-7daa7000-7c03-11eb-86ea-5a70b2982d03.png">

**Comment by pgaudet** [comment]
-  GO:0000751  mitotic cell cycle G1 arrest in response to pheromone
- [x] change subclass from -GO:0071850 ! mitotic cell cycle arrest to is_a: GO:0045930 ! negative regulation of mitotic cell cycle
Conjugation should probably be revisited.

**Comment by pgaudet** [comment]
Dear all, 

The following terms will be merged into 'GO:0051726 regulation of cell cycle'.

GO:0007050 cell cycle arrest
GO:0071850 mitotic cell cycle arrest
GO:0071156 regulation of cell cycle arrest
GO:0071157 negative regulation of cell cycle arrest
GO:0071158 positive regulation of cell cycle arrest

The reason for this change is that 'cell cycle arrest' is a measure of the cell cycle status, not a process in itself. In several instances, the genes annotated to cell cycle arrest are causing a pathological situation in the cell resulting activation of a cell cycle checkpoint; this does not mean that the genes are involved in cell cycle signaling in a normal situation. We have noticed several examples where cell cycle arrest is a phenotype, and the paper lack evidence that the gene is involved in cell cycle regulation. 

There are 186 EXP annotations to the 5 terms mentioned above. 
When reviewing annotations, if there is sufficient evidence for a role in cell cycle progression or exit from the cell cycle (G0), these terms can be considered for replacement: 

GO:0000075 cell cycle checkpoint signaling or a descendant
GO:0070314 G1 to G0 transition
GO:0070315 G1 to G0 transition involved in cell differentiation 

An 'easier' option would be to use the relation 'causally upstream of or within'. 

Thanks, Pascale & Val

**Comment by pgaudet** [comment]
Opened an annotation ticket.
