### ISSUE TITLE
TPV: mitochondrial proton-transporting ATP synthase, catalytic core (GO:0005754)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20932]
mitochondrial proton-transporting ATP synthase, catalytic core (GO:0005754)

for some reason has the parent
 endoplasmic reticulum protein-containing complex?

**Comment by ValWood** [comment]
Also

GO:0005756 | mitochondrial proton-transporting ATP synthase, central stalk
has
endoplasmic reticulum protein-containing complex

**Comment by mah11** [comment]
looks like both happened because `GO:0000275 is_a GO:0140534` has been asserted, presumably by mistake
