### ISSUE TITLE
 synonyms for GO:0007189    adenylate cyclase-activating G protein-coupled receptor signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20933]
Hi Pascale, 

I thought this term was  going to have
"cAMP-mediated signalling" synonyms when the parentage/term was removed..

 GO:0007189    adenylate cyclase-activating G protein-coupled receptor signaling pathway

**Comment by pgaudet** [comment]
but cAMP-mediated signaling is still a term.... 
I need to do this first #20712

**Comment by pgaudet** [comment]
Actually this will be done here: #20712
No need to have 2 tickets.
