### ISSUE TITLE
stray characters in GO:1990483 name

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#20939]
see
```
id: GO:1990483
name: Clr6 histone deacetylase complex I''
```

**Comment by ValWood** [comment]
Unfortunately, that is the name, but I think it might be able to merge with Rpd3L complex.
I have an outstanding question about this:
https://github.com/pombase/curation/issues/2512

**Comment by pgaudet** [comment]
I will close, since there is no action needed for now. Please open a new ticket in you want a term merge. 

Thanks, Pascale
