### ISSUE TITLE
add new term for phycocyanobilin biosynthesis

### ISSUE THREAD

**Issue by peifenz** [geneontology/go-ontology#20941]
Name: phycocyanobilin biosynthetic process
Ontology: biological_process
Synonyms: phycocyanobilin biosynthesis
Definition:
The chemical reactions or pathway resulting in the formation of phycocyanobilin, which involves the oxidative cleavage of heme by a heme oxygenase (HO) to form biliverdin IX alpha.  Biliverdin IX alpha is subsequently converted to phycocyanobilin by a ferredoxin-dependent oxidoreductase (PCYA). Source: PMID:23345435
Parent: GO:0033014

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140609
+name: phycocyanobilin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions or pathway resulting in the formation of phycocyanobilin, which involves the oxidative cleavage of heme by a heme oxygenase (HO) to form biliverdin IX alpha. Biliverdin IX alpha is subsequently converted to phycocyanobilin by a ferredoxin-dependent oxidoreductase (PCYA)." [PMID:23345435]
+synonym: "phycocyanobilin biosynthesis" EXACT []
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:48863 ! phycocyanobilin
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20941 xsd:anyURI
+created_by: pg
