### ISSUE TITLE
New term request: RNA sequestering activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20945]
Ref
PMID:29084823
Title | Phosphorylation of the RNA-binding protein Zfs1 modulates sexual differentiation in fission yeast.
Authors | Navarro FJ, Chakravarty P, Nurse P

Def
The selective interaction of a protein with a specific RNA molecule to prevent it from interacting with other partners or inhibiting its localization to other areas of the cell. 

is_a
GO:0140313  molecular sequestering activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140610
+name: RNA sequestering activity
+namespace: molecular_function
+def: "The selective interaction of a protein with a specific RNA molecule to prevent it from interacting with other partners or inhibiting its localization to other areas of the cell." [PMID:29084823]
+is_a: GO:0140313 ! molecular sequestering activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20945 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-24T13:53:46Z
