### ISSUE TITLE
merge up to gamma-tubulin complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20967]
GO:0061494    gamma-tubulin large complex, mitotic spindle pole body
GO:0055032    gamma-tubulin large complex, spindle pole body
GO:0061495     gamma-tubulin small complex, mitotic spindle pole body

(not used in annotation)

**Comment by pgaudet** [comment]
And we keep 
'gamma-tubulin large complex, equatorial microtubule organizing center'
and 
'gamma-tubulin large complex, interphase microtubule organizing center'?

**Comment by pgaudet** [comment]
and what about 
'gamma-tubulin small complex, centrosomal'
'gamma-tubulin small complex, mitotic spindle pole body'
'gamma-tubulin small complex, spindle pole body'

**Comment by ValWood** [comment]
I think so. Has anyone used them  other than PomBase? I remember requesting them years ago.

**Comment by pgaudet** [comment]
SGD used 'gamma-tubulin small complex, spindle pole body' about 15 times (EXP); @srengel would you be OK merging this into the parent 'gamma-tubulin small complex'? 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi @srengel  you would probably want to annotate to both gamma tubulin complex, and SPB.

The rationale is  that it didn't make sense to have location-specific complexes. We had 
gamma tubulin complex , SPB
gamma tubulin complex , equatorial MTOC
gamma-tubulin large complex, interphase microtubule organizing center 
etc, etc
and we would not want to do this for other complexes that occur in multiple locations.

**Comment by srengel** [comment]
sure this is fine.  it's 15 annotations but only 3 genes, and they each already have some flavor of spindle pole body annotation.

do we need to do anything, or just let the merge happen and the annotations will automatically get updated?

**Comment by pgaudet** [comment]
In P2GO the merge will move the annotations automatically.
