### ISSUE TITLE
GO:0000150 recombinase activity and its regulation

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#20964]
We have some requests from a PomBase community curator, Bilge Argunhan,

- First, we'd like to rename GO:0000150. Bilge prefers `RecA-family recombinase activity`, but if a family-centric name won't do, we can use `strand exchange activity`. Whichever you choose, the other should become a synonym.

  It looks like this could effectively address the question raised in #16037 -- we now have confirmation from an active researcher that GO:0000150 corresponds to a bona fide catalytic activity ("a catalytic activity intrinsic to RecA-family recombinases that drive the pairing of single-stranded DNA with homologous double-stranded DNA and subsequent transfer of DNA strands"), and suggestions for a term name that will be less confusing.

- Second, a request for terms describing regulation of the GO:0000150 activity: `regulation of RecA-family recombinase activity` (and `negative` and `positive` subclasses)

  I'm a little unclear on the status of the "regulation of catalytic activity" branch of BP, but from the description it sounds like using `regulator` MF terms would be OK if reg-of-MF BP terms aren't on.

  > In S. pombe (and most eukaryotes), Rad51 and Dmc1 are the two RecA-family recombinases that orchestrate genetic recombination. While Rad51 and Dmc1 possess the enzymatic activity, several auxiliary factors stimulate Rad51 and Dmc1 to promote efficient recombination. Disrupting the interaction between auxiliary factors and Rad51/Dmc1 results in impaired/abolished stimulation of their activity.

If you have any questions, I'll probably have to pass them on to Bilge; I'm happy to do so.

**Comment by pgaudet** [comment]
Thanks @mah11 
Can you specify: 

1. Do you also want to change the term labels for the descendants of 
*  'site-specific recombinase activity' GO:0000150 recombinase activity
* 'tyrosine-based site-specific recombinase activity'
2. Do you have references for the new terms? Both evidence of positive and negative regulation would be nice.
Those would be x regulator activity, we dont want to create 'regulation of x activity' anymore.

**Comment by mah11** [comment]
Quick update: Bilge has sent another comment on possible names and synonyms for GO:0000150:

> If they prefer to avoid using family names, an alternative could be “homologous recombinase activity”, which not only describes the activity in a manner that is consistent with the GO term "site-specific recombinase activity”, but also avoids use of the "RecA-family” term.

And in response to @pgaudet's questions ...

> Do you also want to change the term labels for the descendants of
> 
> 'site-specific recombinase activity' GO:0000150 recombinase activity
> 'tyrosine-based site-specific recombinase activity'

The 'site-specific recombinase activity' terms should NOT be descendants of GO:0000150 (as [previously discussed](#3917)) but they do not need any other changes (names, text defs, etc.).

> Do you have references for the new terms?

Bilge requested phenotypes that would refer to the regulation/regulator terms for PMID:33493431, so I guess that paper would do for the GO terms themselves.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140619
+name: DNA strand exchange activator activity
+namespace: molecular_function
+def: "Binds to and increases a DNA strand exchange activity." [PMID:33493431]
+intersection_of: GO:0098772 ! molecular function regulator
+intersection_of: positively_regulates GO:0000150 ! DNA strand exchange activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20964 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-26T17:56:46Z
+
+[Term]
+id: GO:0140620
+name: DNA strand exchange inhibitor activity
+namespace: molecular_function
+def: "Binds to and stops, prevents or reduces a DNA strand exchange activity." [PMID:33493431]
+intersection_of: GO:0098772 ! molecular function regulator
+intersection_of: negatively_regulates GO:0000150 ! DNA strand exchange activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20964 xsd:anyURI
+created_by: pg
+creation_date: 2021-02-26T17:57:00Z

**Comment by pgaudet** [comment]
Also, removed the relation: GO:0009009 site-specific recombinase activity is_a GO:0000150 ! strand exchange activity

**Comment by mah11** [comment]
Thanks!

**Comment by mah11** [comment]
One thing that might have got a little lost in the comments: could GO:0000150 also have "RecA-family recombinase activity" as a synonym? I gather the community would think of it as `exact` but `narrow` is fine with me if mentioning a family takes it out of `exact` scope.

thanks again!

**Comment by pgaudet** [comment]
How about 'RELATED'? or is this activity only mediated by RecA familiy members?

**Comment by mah11** [comment]
I don't know this area well, but this (from an email from the community curator) sounds consistent with "activity only mediated by RecA family members":

> Homologous recombinases are related to bacterial RecA and catalyse strand exchange, which is the
activity described by [GO:0000150]

I don't understand the case for RELATED scope (tho' I have no specific reason to oppose it).
