### ISSUE TITLE
GO:0003712    transcription coregulator activity/missing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20962]
GO:0003712    transcription coregulator activity
Definition (GO:0003712 GONUTS page)
A transcription regulator activity that modulates the transcription of specific gene sets via binding to a DNA-bound DNA-binding transcription factor, either on its own or as part of a complex. Coregulators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-bound DNA-binding transcription factors with other transcription coregulators. PMID:10213677 PMID:16858867 PMID:24203923 PMID:25957681

is no longer a descendent of
GO:0140110    transcription regulator activity?

I'm guessing that is unintentional?

**Comment by pgaudet** [comment]
This was intentional, see https://github.com/geneontology/go-ontology/issues/20862#issuecomment-778089309

**Comment by ValWood** [comment]
But "transcription coregulator activity" is *defined* as a "A transcription regulator activity"?????

**Comment by ValWood** [comment]
I thought you wanted to move "transcription regulator" from under "molecular function regulator"

**Comment by pgaudet** [comment]
Right - the next parent is the root.

**Comment by pgaudet** [comment]
I've added the BP 'part of' transcription for coregulator activity. 

Is there anything else we should do? I am not sure we can always say that a regulator is a MF regulator. 
@colinlog Is this right ?

**Comment by pgaudet** [comment]
Actually transcription regulator activity IS NOT a molecular function regulator, it is part_of regulation of transcription. I did this too fast before. I will put the relation back coTF is_a GO:0140110 transcription regulator activity. 

see #20862

**Comment by ValWood** [comment]
ha ha, was just going to comment!
