### ISSUE TITLE
Change label GO:0019539    siderophore biosynthetic process from hydroxamic acid

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20975]
can we merge
GO:0019539    siderophore biosynthetic process from hydroxamic acid
The chemical reactions and pathways resulting in the formation of a siderophore from other compounds, including hydroxamic acid.

into the parent,
since it only has one child, 
GO:0031169    ferrichrome biosynthetic process
which would be easier to find without this intervening term.

and the definition  is too vague ( from other compounds, including hydroxamic acid) does not offer any specificity over the parent.

**Comment by pgaudet** [comment]
see the number of siderophores here: https://pdfs.semanticscholar.org/7946/e6339f9fbb60b054747ee4d706e53958b980.pdf?_ga=2.67985041.1432405903.1614609213-563084161.1614609213

**Comment by pgaudet** [comment]
Changed labels: 
- from: GO:0019540 ! siderophore biosynthetic process from catechol
- to: GO:0019540 ! catechol-containing siderophore biosynthetic process

and 
- from: GO:0019539 ! siderophore biosynthetic process from hydroxamic acid
- to: GO:0019539 ! hydroxymate-containing siderophore biosynthetic process
From the review PMID:20376388, those siderophores are not synthesized from hydroxamic acid or catechol directly, but those are the functional groups that bind iron. 

- Added  PMID:20376388 as a reference
- Removed 'has_primary_input CHEBI:24650 ! hydroxamic acid' and has_primary_input CHEBI:18135 ! catechol as explained above. 

Thanks, Pascale
