### ISSUE TITLE
making naphthalene?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20974]
GO:1901171     naphthalene biosynthetic process
Definition 
The chemical reactions and pathways resulting in the formation of naphthalene.

but 
GO:0018931   naphthalene metabolic process
Definition 
The chemical reactions and pathways involving naphthalene, a fused ring bicyclic aromatic hydrocarbon commonly found in crude oil and oil products. Naphthalene is familiar as the compound that gives mothballs their odor; it is used in the manufacture of plastics, dyes, solvents, and other chemicals, as well as being used as an antiseptic and insecticide.

I'm looking for the siderophore
dihydroxy naphthalene (DHN)-melanin

**Comment by pgaudet** [comment]
@ValWood Based on our discussion from yesterday, will we instantiate all siderophore syntesis processes?

**Comment by ValWood** [comment]
I don't mind really. It would be nice to be able to capture in some way  (i.e a CHEBI extension if not instantiated). @marcfeuermann  would be a good person to ask about this as I think he does quite a bit of 2ndary metabolism.

**Comment by pgaudet** [comment]
Is naphthalene a compound synthesized by living organisms? 

https://en.wikipedia.org/wiki/Naphthalene#Production

**Comment by ValWood** [comment]
I didn't think it was, hence the question, but it seems that is, randomly by magnolias, deer, and possibly termites!
https://en.wikipedia.org/wiki/Naphthalene#Other_sources_and_occurrences

**Comment by marcfeuermann** [comment]
Hello,
I've indeed curated Aspergillus fumigatus pptA a while ago. For what I know, naphthalene itself is not a product of a biological process. It is mostly found in coal tar (so probably a result from a degradation process). Some species might indeed produce trace amounts, but there is not much evidence for a biosynthesis pathway. Moreover, even if the double ring structure of naphthalene is found in some secondary metabolites such as dihydroxynaphthalene (DHN)-melanin, I would never associate their biosynthesis with GO:1901171 or GO:0018931. So in my opinion, we do not have enough evidences to keep these terms in GO (at least up to now).
I hope this will help you.
Take care and stay safe.
Best regards,
Marc.

**Comment by pgaudet** [comment]
GO:0090420 naphthalene-containing compound metabolic process -> change label & LD to naphthalene-containing compound metabolic process 

GO:0043635 methylnaphthalene catabolic process -> ok 
 GO:0018931 naphthalene metabolic process  ->  merge into GO:1901170 naphthalene catabolic process 
GO:1901171 naphthalene biosynthetic process -> obsolete 
 GO:1901170 naphthalene catabolic process -> ok 

Along the same lines: 
GO:0018917 fluorene metabolic process merge into: GO:0019429 fluorene catabolic process

**Comment by pgaudet** [comment]
Same for 
GO:0018918 gallate metabolic process - merge into GO:0019396 gallate catabolic process

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140614
+name: 1,8-dihydroxynaphthalene-melanin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of dihydroxy naphthalene (DHN)-melanin." [PMID:12788746, PMID:23998343]
+synonym: "DHN-melanin biosynthesis" EXACT []
+is_a: GO:0019290 ! siderophore biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/20974 xsd:string
+created_by: pg
+creation_date: 2021-03-04T11:54:05Z

**Comment by ValWood** [comment]
https://github.com/ebi-chebi/ChEBI/issues/4021

**Comment by ValWood** [comment]
Added to CHEBI, should be available soon.

**Comment by pgaudet** [comment]
I will add back 
http://purl.obolibrary.org/obo/CHEBI_167605 ## 1,8-dihydroxynaphthalene-melanin

in the CHEBI imports. Not sure what failed the first time.
