### ISSUE TITLE
Tweak to "retinol dehydrogenase activity" (GO:0004745) name

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#20980]
Can we change the name of "retinol dehydrogenase activity" (GO:0004745) to "NAD-retinol dehydrogenase activity"?

That would match the definition, and better distinguish it from (and make it consistent with) the related term "NADP-retinol dehydrogenase activity"  (GO:0052650).

**Comment by pgaudet** [comment]
Should the current term label, 'retinol dehydrogenase activity', be a broad synonym for "NAD-retinol dehydrogenase activity" and NADP-retinol dehydrogenase activity"?

**Comment by sjm41** [comment]
Makes sense to me, thanks.

**Comment by sjm41** [comment]
Thanks!
