### ISSUE TITLE
Obsolete cell cycle arrest in response to nitrogen starvation & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20989]
Those terms have only been used by Pombase. Some annotations can be moved to 'GO:0051728 cell cycle switching, mitotic to meiotic cell cycle' 

* GO:0071849 G1 cell cycle arrest in response to nitrogen starvation
* GO:0071851 mitotic G1 cell cycle arrest in response to nitrogen starvation
* GO:1903694 positive regulation of mitotic G1 cell cycle arrest in response to nitrogen starvation
* GO:1903693 regulation of mitotic G1 cell cycle arrest in response to nitrogen starvation

**Comment by ValWood** [comment]
All fixed, most were moved to G1 checkpoint.
