### ISSUE TITLE
GO:0140096 part_of GO:0018215 is not correct

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#20999]
Just saw this in my gaf2.2 QC.

In the ontology 'catalytic activity, acting on a protein' (GO:00140096) is asserted to be part of 'protein phosphopantetheinylation' (GO:0018215). This is not correct. Perhaps a F->P link could be made between holo-[acyl-carrier-protein] synthase activity (GO:0008897) part_of 'protein phosphopantetheinylation'?

**Comment by pgaudet** [comment]
Thanks. that was a problem with #18113
