### ISSUE TITLE
merge or obsolete GO:1902505 , no annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20991]
this would only apply to 'within' pathway negative regulation.
No annotations.

GO:1902505 negative regulation of signal transduction involved in mitotic G2 DNA damage checkpoint

**Comment by pgaudet** [comment]
I'll merge into GO:0007095 mitotic G2 DNA damage checkpoint signaling

**Comment by pgaudet** [comment]
already done in https://github.com/geneontology/go-ontology/issues/20935
