### ISSUE TITLE
GO:1990356 (sumoylated E2 ligase complex) not a complex

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21011]
As noted in #20973, in GO:1990356 (sumoylated E2 ligase complex) the SUMO is covalently bound to UBC9, so this is not a complex (and should be removed?). The definition in GO:0032991 does not contain wording of exceptions for some covalently bound units which are chemically one molecule.

**Comment by pgaudet** [comment]
@bmeldal I think you requested that ?

**Comment by bmeldal** [comment]
We have 7 complexes of E2-SUMO. You are probably right that we should consider SUMO as a substrate that is "shuffled" from E1 to E3 via E2. Probably not a proper complex. Discussing it with Sandra. Will get back to you next week.

**Comment by bmeldal** [comment]
SUMO and ubiquitin are grey area proteins... sometimes considered modifications, sometimes components...

**Comment by rwst** [comment]
I could live with a note in the description that hints at this ambiguity of usage.

**Comment by ValWood** [comment]
It's a good point though. It would be nice to exclude the modifiers from the complexes. This ticket made me check what we had at PomBase.

We have ned8 annotated as a component of SCF even though it is a modifier, and atg12 annotated as Atg12-Atg5-Atg16 complex (but  atg12 might be a complex member in additions to being a 'protein tag' ).

@vanaukenk  how would you model a protein conjugation event in GO-CAM?

**Comment by bmeldal** [comment]
We have several complexes with Atg12, too. Never thought of it as a modifier as it's not called "ubiquitin" - but it's "ubiquitin-like protein"...

**Comment by pgaudet** [comment]
@bmeldal please let us know what you would like to do about this term.

**Comment by pgaudet** [comment]
@bmeldal does the thumb up mean you will let us know ? Just checking :)

**Comment by bmeldal** [comment]
Yes, and I've been getting side-tracked about getting back to you. I need to "track down" Sandra, who is busy this week, to discuss what to do.

**Comment by pgaudet** [comment]
any news?

**Comment by bmeldal** [comment]
Yes - apologies!

We decided that SUMO should be treated like ubiquitin and not be a participant. I started to update/obsolete the entries we have last week but run into a technical problem with our editor which meant I forgot to get back to you on here - Friday afternoon last week and too many balls and all that... (Our tech issue is currently being fixed but doesn't affect the GO terms, of course.)

Anyway, it means that I have obsoleted all E2-SUMO complexes and removed SUMO as participant from E1s and E3s. 

I'd be happy for the GO term "GO:1990356 sumoylated E2 ligase complex" to be obsoleted.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:1990356 sumoylated E2 ligase complex.

The reason for obsoletion is that this does not represent a stable complex. There are 2 annotations to this term by CAFA and by BHF, see https://github.com/geneontology/go-annotation/issues/4281

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/21011

Thanks, Pascale
