### ISSUE TITLE
question about GO:0033215

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#21029]
I was just checking on the GO annotations of FhuF, a cytoplasmic ferric siderophore reductase in EcoCyc; one annotation currently is to GO:0033215.  However, the problem with that is that the current definition for that term is:
"A process in which iron is solubilized by reduction from Fe3+ to Fe2+ via a cell surface reductase and subsequent transport of the iron across the membrane by iron uptake proteins. "
The term is also a child of iron ion transport.  FhuF OTOH acts in the cytoplasm, so technically this is not the right term for it.  However, I couldn't find an equivalent term where the iron is reduced in the cytoplasm.  Do you have a suggestion for what to do?  I am not clear on why the reduction step needs to be outside the cell...

Here's a review: PMID 23443998 (note that they were really sloppy with gene names - e.g. they call FhuF FhuE and often YqjH YdjH, and those are just the ones I noticed)

**Comment by pgaudet** [comment]
Hi @keseler 

Is FhuF a transporter? I am looking for the transport pathway in which it acts - it seems it reduces iron transported as Fe3+ by siderophores, see Fig 2 in PMID: 23192658. 

So looking at that figure I would annotate it to 'siderophore-dependent iron import into cell'; what we seem to be missing is a MF to describe this, like 'ferric iron reductase activity' that would be defined as reduction of ferric iron (3+) to ferrous iron (2+). 
What do you think ? 

Thanks, Pascale

**Comment by keseler** [comment]
Hi @pgaudet,

FhuF is not a transporter.  I had actually removed the "siderophore-dependent iron import into cell" annotation that was in EcoCyc (and is still in the current GO file) - but if I interpret your comment correctly, FhuF could still be part of that process even if it is downstream of the import of the Fe3+-loaded siderophore.

As for a MF term, I think in the case of FhuF, the reduction takes place specifically in the context of siderophore-bound ferric iron, i.e. not free ferric iron.  Maybe the definition should mention something along the lines of reducing and simultaneously solubilizing iron from a carrier molecule?  I'm not sure about the question of whether reducing the iron per se removes it from the carrier, or whether those are independent events somehow.

Thinking while writing...  ;-) So now I've successfully written myself into thinking your MF term proposal is fine as is, and that the definition could just mention that the reduction can/does (?) take place in the context of Fe3+ bound to a carrier.

Cheers,
Ingrid

**Comment by ValWood** [comment]
Is this the term?
ferric-chelate reductase activity (GO:0000293)

**Comment by keseler** [comment]
Ah!  Maybe.  Two problems that I see, one mine, one in GO.  Mine is that I don't know what the electron donor for the FhuF-catalyzed reaction is.  The GO problem might be that the definition of that term is specific for NADH and EC 1.16.1.7; in the EC, there are two more enzymes/reactions, one specific for NADPH, 1.16.1.9 (which seems to be GO:0052851, but the EC number is not mentioned), and one with NAD(P)H, 1.16.1.10.  The annotations in GO for GO:0000293 seem to not distinguish between NADH and NADPH, i.e. I see lots of NADPH mentioned in the protein names.

Perhaps make a parent term for the two with an unspecified electron donor, e.g. Fe2+ + electron acceptor = Fe3+ + electron donor?

-Ingrid

**Comment by pgaudet** [comment]
The definitions are wrong for both 
* GO:0052851 ferric-chelate reductase (NADPH) activity: Catalysis of the reaction: 2 Fe3+ + NADPH = 2 Fe2+ + H+ + NADP+. -> change to  2 Fe(II)-**siderophore** + NADP(+) + H(+) <=> 2 Fe(III)-**siderophore** + NADPH
* GO:0000293 ferric-chelate reductase activity : Catalysis of the reaction: 2 Fe2+ + NAD+ = 2 Fe3+ + NADH + H(+). -> change to2 Fe(II)-**siderophore** + NAD(+) + H(+) <=> 2 Fe(III)-**siderophore** + NADH

**Comment by pgaudet** [comment]
@kaxelsen 
Is it possible that EC has the reactions the wrong way around ? Ie iron reduction goes from 3+ to 2+, not the other way around ?

**Comment by pgaudet** [comment]
GO:0000293 : 
* make more general: Catalysis of the reaction: 2 Fe3+-siderophore + electron donor -> 2 Fe3+-siderophore + electron acceptor. 
* remove EC and Rhea
* create new term to represent EC:1.16.1 ferric-chelate reductase (NADP) activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140618
+name: ferric-chelate reductase (NADH) activity
+namespace: molecular_function
+def: "Catalysis of the reaction:  2 Fe3+-siderophore + NAD(+) + H(+) <=> 2 Fe2+-siderophore + NADH." [RHEA:15061]
+synonym: "NADH:Fe(3+) oxidoreductase activity" EXACT [EC:1.16.1.7]
+synonym: "NADH:Fe3+ oxidoreductase activity" EXACT [EC:1.16.1.7]
+synonym: "ferric chelate reductase activity" BROAD []
+synonym: "iron chelate reductase activity" BROAD []
+xref: EC:1.16.1.7
+xref: MetaCyc:FERRIC-CHELATE-REDUCTASE-RXN
+xref: RHEA:15061
+is_a: GO:0000293 ! ferric-chelate reductase activity
+is_a: GO:0016723 ! oxidoreductase activity, acting on metal ions, NAD or NADP as acceptor
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21029 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-09T07:20:30Z

**Comment by kaxelsen** [comment]
@pgaudet Reactions in the EC list are always written in the same way, for oxidoreductases in the way of oxidation. They are should be seen as equations, not depictions of physiological reaction directions. So, no, the reaction is not written in the wrong direction. The name reductase does imply the reaction would run from right to left.

**Comment by pgaudet** [comment]
ok thanks ! I am sure I've asked you this many times already :)
