### ISSUE TITLE
Merge L-DOPA monooxygenase activity (GO:0036263) & L-dopa oxidase activity (GO:0102316)?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21024]
Are these two the same?
(Same as https://www.rhea-db.org/rhea/34287 ?)

[Term]
id: GO:0036263
name: L-DOPA monooxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-DOPA + O2 = ? + H2O. This reaction catalyzes the oxygenation of the dopamine precursor L-DOPA, to the corresponding o-quinone." [GOC:sart, PMID:22120533]
is_a: GO:0004097 ! catechol oxidase activity
=> 31 annotations

[Term]
id: GO:0102316
name: L-dopa oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-dopa  + 0.5 O2 = L-dopaquinone  + H2O." [EC:1.10.3.-, GOC:pz]
xref: MetaCyc:RXN-13061
is_a: GO:0016682 ! oxidoreductase activity, acting on diphenols and related substances as donors, oxygen as acceptor
=> 0 annotations

If so, I'd keep the first one.

**Comment by pgaudet** [comment]
Interesting, how we have a question mark in the definition.

**Comment by pgaudet** [comment]
I think it's also the same as GO:0004503 monophenol monooxygenase activity, based on the EC xrefed by Rhea, EC:1.14.18.1

Catalysis of the reaction: L-tyrosine + L-DOPA + O2 = L-DOPA + DOPAquinone + H2O.

**Comment by pgaudet** [comment]
although GO:0004503 seems to describe 2 reactions? 
In EC they are distinct: https://enzyme.expasy.org/EC/1.14.18.1

    L-tyrosine + O(2) <=> dopaquinone + H(2)O
    2 L-dopa + O(2) <=> 2 dopaquinone + 2 H(2)O

**Comment by sjm41** [comment]
I think we need help from some enzyme experts here.....

**Comment by pgaudet** [comment]
uh uh 

@amorgat 
@hdrabkin

**Comment by hdrabkin** [comment]
How did 
Catalysis of the reaction: L-DOPA + O2 = ? + H2O. This reaction catalyzes the oxygenation of the dopamine precursor L-DOPA, to the corresponding o-quinone." [
ever get through; and people annotated to it!

**Comment by amorgat** [comment]
According to IUBMB
https://www.enzyme-database.org/query.php?ec=1.14.18.1
EC 1.14.18.1 catalyzes 2 reactions
L-tyrosine + O2 = dopaquinone + H2O
2 L-dopa + O2 = 2 dopaquinone + 2 H2O 

both are annotated in Rhea and UniProt
see https://www.rhea-db.org/rhea?query=ec%3A1.14.18.1
RHEA:18117 | L-tyrosine +   O2 =   H2O +   L-dopaquinone 
RHEA:34287 | 2 L-dopa +   O2 =  2 H2O +  2 L-dopaquinone

**Comment by hdrabkin** [comment]
So two separate rxns; one via tyrosine, the other via L-dopa
; the current two terms: merge newer into older, assign RHEA:34287
Then make separate term using RHEA:18117; perhaps name L-tyrosine monoxygenease?

**Comment by amorgat** [comment]
The sytematic name of EC 1.14.18.1 is L-tyrosine,L-dopa:oxygen oxidoreductase

So 2 terms linked to EC 1.14.18.1
L-tyrosine:oxygen oxidoreductase RHEA:18117
L-dopa:oxygen oxidoreductase RHEA:34287

**Comment by deustp01** [comment]
For local re-annotation purposes, is it safe to expect that GO:0004503 monophenol monooxygenase activity will persist as a legal GO term when this issue is sorted out?
Thanks

**Comment by sjm41** [comment]
Just attaching an image of the 3 GO term mentioned above - if we are merging 2 or all 3 of them, we'll need to decide which parentage is correct...
![Screenshot 2021-03-06 at 07 01 05](https://user-images.githubusercontent.com/16306861/110198371-e420cf80-7e49-11eb-91dc-fb41e373edaf.png)

**Comment by kaxelsen** [comment]
id: GO:0036263:
The reference PMID:22120533 is about phenoloxidases that are annotated as EC 1.14.18.1.

There is only one pathway, as the reaction with L-tyrosine can be broken down to:
L-tyrosine + O2 = dopaquinone + H2O (overall reaction)
(a) L-tyrosine + ½ O2 = L-dopa
(b) L-dopa + ½ O2 = dopaquinone + H2O

L-dopa is thus both an intermediate in the reaction from L-tyrosine and a starting point.

So the terms GO:0036263, GO:0102316 and GO:0004503 all describe the same activity.

**Comment by hdrabkin** [comment]
Just note that if we do merge them, the merged term won't get a RHEA since can't have > 1 RHEA per GO term.

**Comment by pgaudet** [comment]
@hdrabkin Do you want to take this ? 

@balhoff I thought we could do more than 1 Rhea to a GO term if we use NARROW xref?

**Comment by sjm41** [comment]
Hi @hdrabkin Any thoughts on how to best resolve this?

**Comment by pgaudet** [comment]
Touched base with @amorgat - actually this represents a multistep reaction, with RHEA:18117 being the overall reaction. See very bottom of the page: 

Comment
Multi-step reaction: 2 RHEA:18117 = RHEA:34283 + RHEA:34287.

**Comment by sjm41** [comment]
Thanks @pgaudet !
For the record, here's a summary of the resolution:
- GO:0004503 has been retained, with name changed from "monophenol monooxygenase activity" to "tyrosinase activity", and with new def "Catalysis of the reaction: L-tyrosine + O2 = DOPAquinone + H2O." (with explanatory comments)
- GO:0102316 & GO:0036263 have been obsoleted, made alt_ids of GO:0004503

**Comment by pgaudet** [comment]
Thanks @sjm41 ! This is very useful.

**Comment by sjm41** [comment]
Looking at the final resolution here with fresh eyes, I think we should **not** have merged "L-DOPA monooxygenase activity" (GO:0036263) into "tyrosinase activity" GO:0004503. (The other merge is fine.)

For two reasons:
1. "L-DOPA monooxygenase activity" (GO:0036263) is/was a sister term to "dopamine monooxygenase activity" (GO:0036264), which we still have.  Both of those comprise the children of "catechol oxidase activity" (GO:0004097). The corresponding EC report for that term (https://enzyme.expasy.org/EC/1.10.3.1) says it "catalyzes exclusively the oxidation of catechols (i.e., o-diphenols) to the corresponding o-quinones...It is different from tyrosinase, EC 1.14.18.1, which can catalyze both the monooxygenation of monophenols and the oxidation of catechols."
So, I think the "L-DOPA monooxygenase activity" is a valid stand-alone activity that can exist independently the from multi-step "tyrosinase activity".

2. Supporting the above, FlyBase (at least) has annotations to "L-DOPA monooxygenase activity" (GO:0036263) and  "dopamine monooxygenase activity" (GO:0036264) from PMID: 22120533 where 2 enzymes (PPO2 and PPO3) were shown to have those activities but were unable to use l-tyrosine as the substrate - ie. they are "catechol oxidases" but not "tyrosinases". So the current merge will make their annotations incorrect.

So, I think we need to reinstate "L-DOPA monooxygenase activity" (GO:0036263) as a child of "catechol oxidase activity" (GO:0004097).
Then, we could decide that we don't need the specificity of "L-DOPA monooxygenase activity" (GO:0036263) and "dopamine monooxygenase activity" (GO:0036264), and merge both those terms into the parent "catechol oxidase activity" (GO:0004097). That would probably be less confusing wrt term names and alignment with EC.

![Screenshot 2021-07-09 at 14 23 25](https://user-images.githubusercontent.com/16306861/125084290-41ab7e00-e0c1-11eb-9279-a01252a72fc5.png)

**Comment by sjm41** [comment]
Also, PMID: 22198355 tested T. castaneum and A. gambiae laccase enzymes using 6 different diphenol substrates (dopamine, N-acetyldopamine (NADA), N-β-alanyldopamine (NBAD), dopa, catechol and hydroquinone), finding relatively high oxidase activity with dopamine, NADA and NBAD, and relatively low activity with dopa.

Based on this, we currently have annotations to "L-DOPA monooxygenase activity" (GO:0036263) and "dopamine monooxygenase activity" (GO:0036264) for the A. gambiae enzyme (Q58IU3), with ISS to D. melanogaster.  Tyrosine wasn't tested as a substrate, so can't annotate to "tyrosinase activity GO:0004503".

**Comment by pgaudet** [comment]
@balhoff can you revert the PR? It would be easiest to start from scratch.

**Comment by balhoff** [comment]
@pgaudet https://github.com/geneontology/go-ontology/pull/21830

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 

Why is  RHEA:34287 | 2 L-dopa +   O2 =  2 H2O +  2 L-dopaquinone
part of RHEA:18117 | L-tyrosine +   O2 =   H2O +   L-dopaquinone ? 

in EC:1.14.18.1 they seem to describe L-dopa and L-tyrosine as 2 substrates rather than 2 steps 
- L-tyrosine + O(2) <=> dopaquinone + H(2)O 
- 2 L-dopa + O(2) <=> 2 dopaquinone + 2 H(2)O


Thanks, Pascale

**Comment by pgaudet** [comment]
@sjm41 

I have looked at this again. One problem is that EC:1.14.18.1 describes 2 reactions, not 2 steps of a reaction, one using tyrosine (a monophenol) and one using catechols - 
so the parent catechol oxidase activity is not correct for L-DOPA monooxygenase activity" (GO:0036263), since in some cases the reaction is not using a catechol as a substrate. 

My understanding from EC is that for the case you describe: 
> FlyBase (at least) has annotations to "L-DOPA monooxygenase activity" (GO:0036263) and "dopamine monooxygenase activity" (GO:0036264) from PMID: 22120533 where 2 enzymes (PPO2 and PPO3) were shown to have those activities but were unable to use l-tyrosine as the substrate - ie. they are "catechol oxidases" but not "tyrosinases". So the current merge will make their annotations incorrect.

this corresponds to EC:1.10.3.1: see comment in the EC entry (https://enzyme.expasy.org/EC/1.10.3.1) "[EC:1.10.3.1] catalyzes exclusively the oxidation of catechols", and "It is different from tyrosinase, EC 1.14.18.1, which can catalyze both the monooxygenation of monophenols and the oxidation of catechols.", so the fly enzyme should not have been annotated to 'L-DOPA monooxygenase activity', but to 'catechol oxidase with L-dopa as a substrate. 

Alternatively, we can fix the terms to split along the catechol/monophenol  axis and make EC:1.14.18.1 a broad synonym of both reactions. 

What I did now is to merge GO:0102316 (L-dopa oxidase activity) into GO:0036263 (L-DOPA monooxygenase activity) and changed the def to describe the 2 reactions in EC:1.14.18.1

* **old def:** "Catalysis of the reaction: 2 L-dopa + O2 = 2 H2O + 2 L-dopaquinone. This reaction can use monophenols (such as tyrosine) and catechols (o-diphenols) as substrates." [GOC:sart, PMID:22120533]
* **new def:** "Catalysis of the reaction: 2 L-dopa + O2 = 2 H2O + 2 L-dopaquinone. This reaction can use both monophenols (such as tyrosine) and catechols (o-diphenols) as substrates." [GOC:sart, PMID:22120533, RHEA:34287]

which makes the term synonymous to GO:0004503 monophenol monooxygenase activity: L-tyrosine + L-DOPA + O2 = L-DOPA + DOPAquinone + H2O, and possibly also GO:0036264 dopamine monooxygenase activity - which is again EC:1.14.18.1, according to Q9V521, and anyway dopamine is another catechol.


Thoughts ??? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
@pgaudet Please look at my comment from March 8. I repeat:

There is only one pathway, as the reaction with L-tyrosine can be broken down to:
L-tyrosine + O2 = dopaquinone + H2O (overall reaction)
(a) L-tyrosine + ½ O2 = L-dopa
(b) L-dopa + ½ O2 = dopaquinone + H2O

L-dopa is thus both an intermediate in the reaction from L-tyrosine and a starting point.

**Comment by pgaudet** [comment]
Thanks for explaining this again @kaxelsen 

Should then RHEA:34283 (the first part of the reaction) also be mapped to EC:1.14.18.1, like the second part and the overall reaction?

**Comment by kaxelsen** [comment]
The current policy we have is to only map to overall reactions. But this EC number is a somewhat special case where the reactions specified by IUBMB look like this:
(1) L-tyrosine + O2 = dopaquinone + H2O (overall reaction)
(1a) L-tyrosine + ½ O2 = L-dopa
(1b) L-dopa + ½ O2 = dopaquinone + H2O
(2) 2 L-dopa + O2 = 2 dopaquinone + 2 H2O 
where reaction (1b) - that is the second step of reaction (1) - is actually identical to reaction (2).
In this case we have mapped RHEA reactions to IUBMB reactions (1) and (2), but do not plan to map to reaction (1a) [[[and reaction (1b)]]].

**Comment by pgaudet** [comment]
ok thanks for the clarification @kaxelsen

**Comment by sjm41** [comment]
Thanks for looking at this again @pgaudet @kaxelsen .

For me, it makes sense to align GO with EC here and keep things as simple as possible. That is, of all the terms discussed above, end up with these two GO terms:

**1. monophenol monooxygenase activity (GO:0004503) - renamed to 'Tyrosinase activity'**
xrefs: EC:1.14.18.1, RHEA:18117

**2. catechol oxidase activity (GO:0004097)**
xrefs: EC:1.10.3.1, RHEA:21632
- merge L-dopa oxidase activity (GO:0102316) into this (as you've already done)
- also merge 2 current children "dopamine monooxygenase activity (GO:0036264)" and "L-DOPA monooxygenase activity (GO:0036263)" into this term.

 How does that sound?
