### ISSUE TITLE
NTR: Iodotyrosine deiodinase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21027]
Can we make this new new term:
NAME: Iodotyrosine deiodinase activity
DEF: 2 iodide + L-tyrosine + 2 NADP+ = 3,5-diiodo-L-tyrosine + H+ + 2 NADPH
XREFS: EC:1.21.1.1, RHEA:32479
PARENT: not sure....

Needed to annotate human IYD (https://www.uniprot.org/uniprot/Q6PHW0) and fly Iyd (https://flybase.org/reports/FBgn0286980.html), at least.

Source refs:
https://pubmed.ncbi.nlm.nih.gov/27643701/ (fly)
PubMed:15289438, PubMed:25395621, PubMed:18434651 (human)

Note that "iodotyrosine deiodinase activity" (and some similar phrases) are currently synonyms of GO:0004447, but that's a different reaction and those synonyms should be moved to the new term (the synonyms are NOT shown at https://enzyme.expasy.org/EC/1.11.1.8):

id: GO:0004447
name: iodide peroxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: iodide + hydrogen peroxide = iodine + 2 H2O." [EC:1.11.1.8]
synonym: "iodide peroxidase-tyrosine iodinase activity" RELATED [EC:1.11.1.8]
synonym: "iodide:hydrogen-peroxide oxidoreductase activity" RELATED [EC:1.11.1.8]
synonym: "iodinase activity" RELATED [EC:1.11.1.8]
synonym: "iodoperoxidase (heme type)" RELATED [EC:1.11.1.8]
synonym: "iodotyrosine deiodase activity" RELATED [EC:1.11.1.8]
synonym: "iodotyrosine deiodinase activity" RELATED [EC:1.11.1.8]
synonym: "monoiodotyrosine deiodinase activity" RELATED [EC:1.11.1.8]
synonym: "thyroid peroxidase activity" RELATED [EC:1.11.1.8]
synonym: "thyroperoxidase activity" RELATED [EC:1.11.1.8]
synonym: "TPO activity" RELATED [EC:1.11.1.8]
synonym: "tyrosine iodinase activity" RELATED [EC:1.11.1.8]
xref: EC:1.11.1.8
xref: MetaCyc:IODIDE-PEROXIDASE-RXN
xref: RHEA:23336
is_a: GO:0004601 ! peroxidase activity

**Comment by pgaudet** [comment]
Should all synonyms be moved ?

**Comment by sjm41** [comment]
From https://enzyme.expasy.org/EC/1.11.1.8, I think only these synonyms should stay on "iodide peroxidase activity":
synonym: "iodinase activity" RELATED [EC:1.11.1.8]
synonym: "thyroid peroxidase activity" RELATED [EC:1.11.1.8]
synonym: "thyroperoxidase activity" RELATED [EC:1.11.1.8]
synonym: "TPO activity" RELATED [EC:1.11.1.8]


The other synonyms are not shown at https://enzyme.expasy.org/EC/1.21.1.1, and I could only guess as to which would be appropriate/accurate, so maybe better just to lose them and not have them on either term.
The only synonym for the new term shown at https://enzyme.expasy.org/EC/1.21.1.1 is:
Iodotyrosine dehalogenase 1

**Comment by pgaudet** [comment]
ok thanks

**Comment by sjm41** [comment]
Great, thanks!  Did you figure out the correct MF parent for the new term?

**Comment by pgaudet** [comment]
I used GO:0046992 ! oxidoreductase activity, acting on X-H and Y-H to form an X-Y bond, which corresponds to EC:1.21.-.-

Does that seem right to you?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140616
+name: iodotyrosine deiodinase activity
+def: "Catalyzes the reaction: 2 iodide + L-tyrosine + 2 NADP+ = 3,5-diiodo-L-tyrosine + H+ + 2 NADPH." [PMID:15289438, PMID:18434651, PMID:25395621, PMID:27643701, RHEA:32479]

**Comment by sjm41** [comment]
That looks more like algebra than enzymology, but yes, it looks like the correct parent - thanks again!
