### ISSUE TITLE
please clarify GO:0009346 citrate lyase complex

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21028]
GO:0009346 name (citrate lyase complex) is very general but its description applies only to the bacterial type.

```
id: GO:0009346
name: citrate lyase complex
namespace: cellular_component
def: "Citrate lyase is a multienzyme complex with three constituents: the alpha subunit, citrate-ACP transferase; the beta subunit, citryl-ACP lyase; and the gamma subunit, an acyl-carrier protein which also carries the prosthetic group components. All three subunits are required for citrate lyase enzyme activity." [EC:4.1.3.6, MetaCyc:ACECITLY-CPLX]
```
Indeed all the bacterial/plant/animal enzymes are complexes so the general name makes sense but you can see from the following that the description only applies to bacteria:
https://www.semanticscholar.org/paper/A-novel-architecture-of-600-kDa-bacterial-citrate-Forouhar-Lew/b467491dd6a1598d92a0a47cde0bde51cc35da7f where is stated:
`There are two types of citrate lyases, ATP-dependent and ATP-independent. The latter, which exists only in bacteria, converts citrate to acetate and oxaloacetate using a two-step reaction catalyzed by a stable heterotrimeric protein complex comprising alpha-beta-gamma subunits`. So bacteria use ACP (acyl-carrier protein) but no ATP with phosphorylation. The entry definition clearly is for bacteria. It is not for plants because there the complex is heterodimeric (PMID:12376641) nor animals where it is homotetrameric (IPR014608).

**Comment by pgaudet** [comment]
- [x] GO:0009346 citrate lyase complex: changed label to ATP-independent citrate lyase complex
- [x]  Added comment in def: "This enzyme has only been found in bacteria."
- [x]  Added taxon constraint only in bacteria: GO:0008815 citrate (pro-3S)-lyase activity and GO:0009346 ATP-independent citrate lyase complex
- [x]  Created new term ATP-dependent citrate lyase complex
+[Term]
+id: GO:0140615
+name: ATP-dependent citrate lyase complex
+namespace: cellular_component
+def: "A protein complex that catalyzes the cleavage of citrate into oxaloacetate and acetyl-CoA." [PMID:12376641]
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: capable_of GO:0003878 ! ATP citrate synthase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21028 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-08T14:15:18Z

**Comment by pgaudet** [comment]
@tberardini 
When the new term is available, can you move the 2 TAIR annotations from GO:0009346 citrate lyase complex 
to
GO:0140615 name: ATP-dependent citrate lyase complex

Thanks, Pascale

**Comment by rwst** [comment]
Thanks.

**Comment by tberardini** [comment]
@pgaudet Updating the annotations is on my to do list now.

**Comment by tberardini** [comment]
@pgaudet Annotations transferred.
