### ISSUE TITLE
NTR: transvection

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21038]
A discussed in https://github.com/geneontology/go-ontology/issues/20791
I will create a new term, transvection

* Child of 'regulation of gene expression, epigenetic' 
* Def: Regulation of transcription by interaction between an allele on one chromosome and the corresponding allele on the homologous chromosome. Transvection can lead to either gene activation or repression.
References: 

PMID:33479152
PMID:24236213

@colinlog Any comments?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140617
+name: transvection
+namespace: biological_process
+def: "Regulation of transcription by interaction between an allele on one chromosome and the corresponding allele on the homologous chromosome. Transvection can lead to either gene activation or repression." [PMID:24236213, PMID:33479152]
+is_a: GO:0040029 ! regulation of gene expression, epigenetic
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21038 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-08T18:30:47Z
+

**Comment by ValWood** [comment]
Out of curiosity, why is this 'epigenetic' ?

**Comment by pgaudet** [comment]
This is what the wikipedia page says: https://en.wikipedia.org/wiki/Transvection_(genetics)
See also for eg PMID:31611231

@colinlog please reopen if that isn't right.

**Comment by ValWood** [comment]
Clearrly I don't understand what it is.

But is this definition sufficient"

"Regulation of transcription by interaction between an allele on one chromosome and the corresponding allele on the homologous chromosome."

**Comment by pgaudet** [comment]
I think 'genetic' would be strictly driven by the DNA sequence; epigenetic is mediated by proteins (for eg histones, here, brindging of different chromosomes)

**Comment by ValWood** [comment]
So is it heritable? Isn't that the criteria?

**Comment by ValWood** [comment]
yes, Wikipedia says so! So yes, it just needs epigenetic in the def...

"Transvection is an **epigenetic** phenomenon that results from an interaction between an allele on one chromosome and the corresponding allele on the homologous chromosome."

**Comment by colinlog** [comment]
Epigenomic: protein+DNa complexes.
Epigenetic: heritable. The time scale does matter though.
I would argue that epigenetic is not necessary for the definition of
transvection. It is driven by dbTFs binding to
enhancers/silencers/promoters. Still, even though txn is driven by signal
transduction, the enhancers are defined in an epigenomic/epigenetic fashion.

**Comment by colinlog** [comment]
I am fine with epigenetic in the definition, in case that was not clear...

**Comment by colinlog** [comment]
but 'interaction' can be abstract 'genetic', even 'epistasis'. So, I would
like the 'physical' qualifier here to narrow-down scenarios

**Comment by ValWood** [comment]
> Limiting it to diptera

good plan!
