### ISSUE TITLE
GO:0007264 small GTPase mediated signal transduction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21049]
Did we talk about removing
GO:0007264 small GTPase mediated signal transduction

I ask because all of the SIN pathway is  a descendent of these terms. It seems to be orthogonal to the (many) other ways of describing signalling based on one MF (it could also be called "protein kinase mediated signal transduction, for example).

**Comment by pgaudet** [comment]
Covered in #20864
