### ISSUE TITLE
taxon constraint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21042]
GO:0035257
nuclear hormone receptor binding

please add "never in yeast"

**Comment by pgaudet** [comment]
Is only in metazo OK ? see https://www.spandidos-publications.com/10.3892/wasj.2020.30

**Comment by ValWood** [comment]
that works!

**Comment by pgaudet** [comment]
Replaced by never in GO:0035257	nuclear hormone receptor binding	NCBITaxon:Union_0000023	Fungi or Bacteria or Archaea
