### ISSUE TITLE
NTR: EGAD pathway

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#21085]
New term: EGAD pathway

Definition: The protein catabolic pathway which selectively extracts ER-resident membrane proteins exported to the Golgi and endosomes for degradation by cytosolic proteasomes. It begins with phosphorylation of the ER-resident membrane protein, which triggers export of the protein from the ER to the Golgi and endosomes, followed by polyubiquitination by the Dsc E3 ubiquitin ligase complex and extraction of the ubiquitinated target, and ends with proteasomal degradation.

reference: https://pubmed.ncbi.nlm.nih.gov/31368600/

placement: is_a child of GO:0010498 proteasomal protein catabolic process

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140624
+name: EGAD pathway
+namespace: biological_process
+def: "The protein catabolic pathway which selectively extracts ER-resident membrane proteins exported to the Golgi and endosomes for degradation by cytosolic proteasomes. It begins with phosphorylation of the ER-resident membrane protein, which triggers export of the protein from the ER to the Golgi and endosomes, followed by polyubiquitination by the Dsc E3 ubiquitin ligase complex and extraction of the ubiquitinated target, and ends with proteasomal degradation." [PMID:31368600]
+is_a: GO:0010498 ! proteasomal protein catabolic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21085 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-12T10:41:58Z
+
