### ISSUE TITLE
NTR neutrophil dispersal

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#21081]
Is_a neutrophil migration

Def:
The movement of a neutrophil away from the site of wound or infection.

PMID:  31727891

Use case:
cxcr2 -/- (dre) neutrophils migrate to the site of a wound just fine, they just don't leave at the same rate as normal neutrophils

**Comment by pgaudet** [comment]
Is this related to GO:0030595 leukocyte chemotaxis? 
@addiehl or would there not be another concept that covers this?

**Comment by addiehl** [comment]
Having looked at the paper (though not completely thoroughly), I think the zebrafish cxcr2 should definitely be annotated to 'neutrophil chemotaxis' with an IMP evidence code (currently has an IBA annotation to this term, nice to see experimental validation).  I agree the process of 'neutrophil dispersal' seems to exist, per the data in the paper, and certainly cxcr2 is involved, via a chemokine related mechanism.  But I think, following Ceri's suggestion, that making 'neutrophil dispersal' a child of 'neutrophil migration' allows for non-chemokine dispersal as well as chemokine dispersal, and cxcr2 should be co-annotated to both  'neutrophil chemotaxis' and the new term 'neutrophil dispersal'.

Alex

**Comment by addiehl** [comment]
I am wondering the definition should read something like:
The movement of a neutrophil away from the site of wound or infection following its initial migration to the site.

to reflect the temporal order of events in the movement of the neutrophil and that it is not a strict repulsion of neutrophils from wound sites prior to their in-migration.

**Comment by cerivs** [comment]
gomodel:60418ffa00000408   is waiting for this term.  I can add the chemotaxis term too. I thumbs up Alex's suggestion but wanted to say it sounds good.

**Comment by pgaudet** [comment]
Thanks for the reminder @cerivs 

+[Term]
+id: GO:0140635
+name: neutrophil dispersal
+namespace: biological_process
+def: "The movement of a neutrophil away from the site of wound or infection following its initial migration to the site." [PMID:31727891]
+is_a: GO:1990266 ! neutrophil migration
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21081 xsd:anyURI
+created_by: pg
+creation_date: 2021-04-13T07:06:25Z
