### ISSUE TITLE
CARD8 inflammasome complex assembly

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#21092]
Hi GO,

I recently updated the CARD8 inflammasome and would need a term for its inflammasome assembly.

Inflammasome assembly is a key step in the GO:0006954; P:inflammatory response.

We currently have 2 terms for Inflammasome assembly:
GO:1904784 NLRP1 inflammasome complex assembly
GO:0044546 NLRP3 inflammasome complex assembly

Would it be possible to

1) Create a parent term for the different nflammasome complex assembly terms

GO:XXXXXXX Inflammasome complex assembly
The aggregation, arrangement and bonding together of a set of components to form an inflammasome complex. 
Child of GO:0065003 protein-containing complex assembly
Child of  GO:0006954; P:inflammatory response
PMID:33420033
PMID:33420028
PMID:33542150

2) create a specific term for CARD8 inflammasome complex assembly?

GO:XXXXXXX CARD8 inflammasome complex assembly
The aggregation, arrangement and bonding together of a set of components to form a CARD8 inflammasome complex. 

PMID:33420033
PMID:33420028
PMID:33542150
Category: Biological Process
Child of GO:0065003 protein-containing complex assembly
Child of  GO:0006954; P:inflammatory response
 
You might consider that we don't want to create another gene-specific term. It is therefore up to you to create GO:XXXXXXX Inflammasome complex assembly and deprecate GO:1904784 and GO:0044546, or create both terms

Thanks

Sylvain

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

We can create new complexes if they are different - can you be more specific about composition?

**Comment by sylvainpoux** [comment]
It is difficult to be specific about composition because it differs between species. Basically, some inflammasomes need PYCARD and some not. An inflammasome is basically composed of a oligomer of a CARD-domain containing proteins (NLRP1, NLRP3, CARD8) that recruits CASP1 for activation  with or without assistance of PYCARD.

Composition:
NLRP1 HUMAN: NLRP1, PYCARD, CASP1
NlRp1a, NlRp1b MOUSE: NlRp1 Casp1
NLRP3: NLRP3, PYCARD and CASP1
CARD8: CARD8 and CASP1

The important term would be GO:XXXXXXX Inflammasome complex assembly, because it is a real process.

**Comment by sylvainpoux** [comment]
Hi Pascale,
anything new about these terms?
Thanks
Sylvain

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

Thanks for the reminder. To decide whether to create multiple terms or just use 'Inflammasome complex assembly': would the children terms describe different substrates, or are there different mechanisms that mediate the assembly of those different complexes? 

Thanks, Pascale

**Comment by pgaudet** [comment]
After looking at the annotations, I will create both terms you request.

**Comment by pgaudet** [comment]
Also created the CC term 'CARD8 inflammasome complex' to make a logical definition for 'CARD8 inflammasome complex assembly'. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+id: GO:0140632
+name: inflammasome complex assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form an inflammasome complex." [PMID:33420028, PMID:33420033, PMID:33542150]
+is_a: GO:0034622 ! cellular protein-containing complex assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21092 xsd:anyURI
+created_by: pg
+creation_date: 2021-04-09T11:11:41Z
+
+[Term]
+id: GO:0140633
+name: CARD8 inflammasome complex assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a CARD8 inflammasome complex." [PMID:33420028, PMID:33420033, PMID:33542150]
+is_a: GO:0140632 ! inflammasome complex assembly
+intersection_of: GO:0065003 ! protein-containing complex assembly
+intersection_of: results_in_assembly_of GO:0140634 ! CARD8 inflammasome complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21092 xsd:anyURI
+created_by: pg
+creation_date: 2021-04-09T11:19:51Z
+
+[Term]
+id: GO:0140634
+name: CARD8 inflammasome complex
+namespace: cellular_component
+def: "An inflammasome complex that consists of CARD8 and CASP1." [PMID:33420028, PMID:33420033, PMID:33542150]
+is_a: GO:0061702 ! inflammasome complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21092 xsd:anyURI
+created_by: pg
+creation_date: 2021-04-09T11:24:48Z

**Comment by sylvainpoux** [comment]
Thanks Pascale!

Sylvain
