### ISSUE TITLE
Two NTR for HSD17B8 (Q92506)  

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#21090]
Hi,

I would like to request two new terms for HSD17B8 (Q92506) based PMID:19571038 and PMID:25203508. 

One is actually a positive regulation of an existing term and the other one is a catalytic activity but I put them in the same request as they are based on the same papers. Please, let me know, if you would prefer to separate them.

Background information:

CBR4 (Q8N4T8) and HSD17B8 (Q92506) are the subunits of the 3-ketoacyl-[acyl-carrier-protein] reductase complex but each one appears to have a different catalytic activity, based on PMID:19571038 and PMID:25203508 which are in the entries:

CBR4 catalyses the main reaction of the mtFAS pathway:
3-oxoacyl-[acyl-carrier protein] + NADPH + H+    -> 3R-hydroxyacyl-[acyl-carrier protein] + NADP+

HSD17B8 catalyses the reaction (which corresponds to EC 1.1.1.n12):
3R-hydroxyacyl-CoA + NAD(+) ->  3-oxoacyl-CoA + NADH  (Rhea: 32711)

HSD17B8 doesn't have GO:0004316 '3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity'  but provides somehow the 3-oxoacyl-CoA for CBR4 (or help to form/stabilize the complex).

1. I would like the positive regulation of GO:0004316  '3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity' to capture the contribution of HSD17B8.

2. I would like  to request a New Term for the individual catalytic activity  of HSD17B8 

**"(3R)-hydroxyacyl-CoA dehydrogenase (NAD) activity"**

**Definition:**
Catalysis of the reaction: 3R-hydroxyacyl-CoA + NAD(+) ->  3-oxoacyl-CoA + NADH  (Rhea: 32711) (EC 1.1.1.n12)

It should be  a sibling term to GO:0004316 '3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity',
so a child term of  GO:0016616 'oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor' and  GO:0004312  'fatty acid synthase activity'.

The UniProt entries are also in the process to be revised based on the above. Please, let me know if you need any more information.

Thanks,

Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 

We are moving away from using BP regulation of MF. 

In this case there are a few options - you can use HSD17B8 'contributes_to' '3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity', but it sounds like you don't know enough. In this case I would suggest using an extension like this: 

HSD17B8 enables "(3R)-hydroxyacyl-CoA dehydrogenase (NAD) activity
and acts_upstream_of, positive effect GO:0004316 '3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity'

Does that work? @vanaukenk what do you think?

**Comment by pgarmiri** [comment]
Hi @pgaudet ,

I couldn't find a way to capture this with an annotation extension but I could add the two annotation independently.

@sjm41 what do you think?

I am attaching a schematic representation of the reactions from  PMID:25203508

![image](https://user-images.githubusercontent.com/22025005/111453888-f503f780-870b-11eb-8425-9a457495f859.png)

**Comment by sjm41** [comment]
Hi @pgarmiri 

As far as I understand these reactions and the current GO guidelines, I think @pgaudet's second suggestion makes sense - it would be good to connect these two reactions in some manner, but I don't think adding a new "positive regulation of GO:0004316" term or using the 'contributes_to' relation would be quite right here.

So, we just need the new term adding corresponding to Rhea: 32711 / EC 1.1.1.n12!

**Comment by pgaudet** [comment]
Thanks for looking at this @sjm41. 
A correction on my comment above -we dont want to have _'acts_upstream_of or within' a MF_ - this would too easily be misinterpreted. 

@pgarmiri : It looks like both genes have activities, and you want to connect them, is this right? 
If this is the case, you can do this using has_input + has output as follows: 

Reaction_1 _enabled by X_ has input CHEBI_A, has output CHEBI_B
Reaction_1 _enabled by Y_ has input CHEBI_B, (has output CHEBI_C)

The two reactions are linked by the output of the first being the same as the input of the second. 

Does that solve the issue? 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Thank you both! Yes, @pgaudet , I think that would work. :)

So, let's add the new term adding corresponding to Rhea: 32711 / EC 1.1.1.n12 in the instance and I will have a go capturing the link between the reactions and products.

Thanks,

Penelope

**Comment by hdrabkin** [comment]
Based on The RHEA, I have defined this as the 'undetermined' direction (=). https://beta.rhea-db.org/rhea/32711
+id: GO:0106386
+name: (3R)-hydroxyacyl-CoA dehydrogenase (NAD) activity
