### ISSUE TITLE
kinetochore adaptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21091]
could we add a generic
kinetochore adaptor activity
parent of
GO:0140483    outer kinetochore adaptor activity

(or make this term less specific. the inner/outer part could be specified by "occurs_at"

**Comment by ValWood** [comment]
@pgaudet  Did you broaden,  or add new (need to flag what I need to do)

**Comment by pgaudet** [comment]
I broadened to 'kinetochore adaptor activity' - the definition was anyways representing the broader concept: "The binding activity of a protein that brings the kinetochore and another molecule into contact, permitting those molecules to function in a coordinated way."
OK?

**Comment by ValWood** [comment]
yep!
