### ISSUE TITLE
sphingolipid delta-4 desaturase activity (GO:0042284) parent and xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21105]
Please add "EC 1.14.19.17" and "RHEA:46544" as xrefs, and add additional parent of "monooxygenase activity (GO:0004497)" to this term:

id: GO:0042284
name: sphingolipid delta-4 desaturase activity
namespace: molecular_function
def: "Catalysis of the introduction of a trans double bond between C4 and C5 of the long chain base region of a sphingolipid. Sphingolipids are composed of a long chain base (LCB) amide-linked to a very long chain fatty acid." [PMID:12417141]
synonym: "delta-4 sphingolipid desaturase activity" EXACT []
xref: Reactome:R-HSA-428259 "dihydroceramide + NAD(P)H + H+ + O2 => ceramide + NAD(P)+ + H2O"
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

**Comment by sjm41** [comment]
From discussion in #21108, we should NOT add the additional parent of "monooxygenase activity (GO:0004497)" here.

But please still add the xrefs.

And should probably add the EC/Rhea reaction within the def:
A dihydroceramide + 2 ferrocytochrome b5 + O(2) + 2 H(+) <=> a (4E)-sphing-4-enine ceramide + 2 ferricytochrome b5 + 2 H(2)O

And also note that reaction doesn't quite match the Reactome reaction - so something else awry here too?

**Comment by sjm41** [comment]
Assuming this is meant to be EC:1.14.19.17, then the parent should actually be changed to " GO:0016717 oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water", which is EC:1.14.19.-

**Comment by sjm41** [comment]
Thanks @pgaudet . What do you think about the Reactome xref?  "dihydroceramide + NAD(P)H + H+ + O2 => ceramide + NAD(P)+ + H2O" is not the same as "dihydroceramide + 2 ferrocytochrome b5 + O(2) + 2 H(+) <=> a (4E)-sphing-4-enine ceramide + 2 ferricytochrome b5 + 2 H(2)O"

**Comment by pgaudet** [comment]
Right - this is strange, all older definitions did not seem to include ferrichrome. The few papers I have looked at dont specially mention ferrichrome. 


@deustp01 Can you check? 
@amorgat @kaxelsen any comment on this ferrichrome issue?

**Comment by deustp01** [comment]
The quick unfortunate response for Reactome is that the papers we cited for our [reaction](https://reactome.org/PathwayBrowser/#/R-HSA-428259) mention neither ferricytochrome nor NAD(P) as a reaction participant. I will dig some more (and wait for comments from Rhea) to figure out why we annotated the reaction as we did / how we should annotate it, and meanwhile I would ignore the Reactome annotations for the purpose of this discussion.

**Comment by deustp01** [comment]
> NAD(P) as a reaction participant.

Now have found some that do (including one we cited for the Reactome reaction that is also cited for the [Rhea reaction](https://www.rhea-db.org/rhea/55808) - [Ternes et al. 2002 PMID: 11937514](https://www.sciencedirect.com/science/article/pii/S0021925819665142?via%3Dihub#bib9).
So we appear not to have misrepresented the literature, at least as far as we dug then or now, but it remains unclear what the facts are - @amorgat @kaxelsen

**Comment by kaxelsen** [comment]
EC 1.14.19.17 is created with the direct electron donor, that is reduced cytochrome b5. 
PMID:11104018 (Causeret et al 2000) about the Rat Dihydroceramide Desaturase , finds that the direct electron donor for the desaturase is cytochrome b5 (see Fig. 1). The NAD(P)H is reducing cytochrome b5 reductase that is also present in the assays.
A similar conclusion is reached by Michel et al. (PMID:9312549). Note that in both papers they work with microsomes, so it is natural the cytochrome b5 reductase is present and it is also logic to add NAD(P)H to get the assay working.

**Comment by pgaudet** [comment]
Thanks @kaxelsen 

So the physiological reaction is using ferrocytochrome b5 as described in EC and RHEA, and NAD(P)H is not a direct participant, is this right ?

**Comment by kaxelsen** [comment]
Yes, NAD(P)H accepts electrons from cytochrome b5 reductase that again accepts electrons from cytochrome b5

**Comment by pgaudet** [comment]
OK thanks - @deustp01 I dont know if you want to take that into account for the Reactome reaction?

**Comment by pgaudet** [comment]
Thanks, Changed def to "Catalysis of the reaction: a dihydroceramide + 2 ferrocytochrome b5 + O2 + 2 H+ -> a (4E)-sphing-4-enine ceramide + 2 ferricytochrome b5 + 2 H2O. NAD(P)H then reduces erricytochrome to regenerate ferrocytochrome.". 

Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet.  Typo in "erricytochrome".

**Comment by pgaudet** [comment]
For me 'the introduction of a trans double bond between C4 and C5 of the long chain base region of a sphingolipid' is easier to understand than having '(4E)-sphing-4-enine ceramide' in the reaction products, but maybe that's clear enough for annotating relevant papers?

**Comment by pgaudet** [comment]
(4E)-sphing-4-enine ceramide = sphingosine ceramide, see https://cacaocyc.cacaogenomedb.org/compound?orgid=COCOA&id=N-Acylsphingosine

**Comment by kaxelsen** [comment]
"NAD(P)H then reduces erricytochrome to regenerate ferrocytochrome" happens with the help of EC 1.6.2.2, c
ytochrome-b5 reductase.

**Comment by deustp01** [comment]
> @deustp01 I dont know if you want to take that into account for the Reactome reaction?

We will, yes

**Comment by pgaudet** [comment]
I changed the definition back to 'Catalysis of the reaction: a dihydroceramide + 2 ferrocytochrome b5 + O2 + 2 H+ -> a sphingosine ceramide (aka (4E)-sphing-4-enine ceramide) + 2 ferricytochrome b5 + 2 H2O.' 

The cyt b5 reductase is beyond the scope of the term. If Reactome removes the reference to NAD/NAPD then this wont be a problem anymore.
