### ISSUE TITLE
heme oxygenase (decyclizing) activity (GO:0004392) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21106]
I think "heme oxygenase (decyclizing) activity (GO:0004392)" should have an additional parent of "monooxygenase activity (GO:0004497)".

(e.g. https://pubmed.ncbi.nlm.nih.gov/16185651/)

**Comment by kaxelsen** [comment]
'oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen' is the full IUBMB definition of EC 1.14.14

EC 1: oxidoreductase activity, 
EC 1.14: acting on paired donors, with incorporation or reduction of molecular oxygen, The oxygen incorporated need not be derived from O(2).
EC 1.14.14: reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen

**Comment by sjm41** [comment]
@pgaudet would you be able to action this one?

**Comment by pgaudet** [comment]
Thanks for the ping @sjm41 

I also changed the definition to match RHEA, ie using reduced [NADPH-hemoprotein reductase] as a electron donor.

**Comment by sjm41** [comment]
Thanks!
