### ISSUE TITLE
GO:0008682 query

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21107]
id: GO:0008682
name: 2-octoprenyl-3-methyl-6-methoxy-1,4-benzoquinone hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-octoprenyl-3-methyl-6-methoxy-1,4-benzoquinone + O2 = 2-octoprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinone." [RHEA:50908]
synonym: "demethoxy-ubiquinone hydroxylase" RELATED [GOC:vw]
synonym: "demethoxyubiquinone monooxygenase" RELATED [GOC:vw]
xref: EC:1.14.99.60
xref: MetaCyc:OCTAPRENYL-METHYL-METHOXY-BENZOQ-OH-RXN
xref: RHEA:50908
is_a: GO:0004497 ! monooxygenase activity

===

The GO def doesn't seem to match the EC/Rhea reactions - should the GO def be updated to match, or is the GO term really for a different reaction?:

EC:1.14.99.60
6-methoxy-3-methyl-2-(all-trans-polyprenyl)-1,4-benzoquinol + a reduced acceptor + O(2) <=> 3-demethylubiquinol + acceptor + H(2)O

RHEA:50908
a 6-methoxy-3-methyl-2-all-trans-polyprenyl-1,4-benzoquinol + AH2 + O2 = A + a 3-demethylubiquinol + H2O

Also, the term should have an additional parent of:
oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)
(which is EC:1.14.-.-)

**Comment by pgaudet** [comment]
I *think* those reactions are the same, but Rhea is more generic? 
We should update to match the term label and the definitions to EC/Rhea.

**Comment by sjm41** [comment]
Thoughts on this one @hdrabkin ?

**Comment by sjm41** [comment]
Hi @hdrabkin Can you take a look at this one too please?

**Comment by hdrabkin** [comment]
Perhaps EC:1.14.99 might be better parent if we have it already.

**Comment by hdrabkin** [comment]
2-octoprenyl- is a type of polyprenyl, so the name change would be appropriate. The 2-octoprenyl  name seems to be the result of the papers used in the experimental annotations (2). 
This would allow future addition of more RHEAs as narrow xrefs to different numbers of prenyl chains if needed.

**Comment by hdrabkin** [comment]
At this time I could also make the term label  2-octoprenyl-3-methyl-6-methoxy-1,4-benzoquinone hydroxylase activity a narrow synonym too.

**Comment by hdrabkin** [comment]
Looking more closely
GO DEF: 2-octoprenyl-3-methyl-6-methoxy-1,4-benzoquinone + O2 = 2-octoprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinone."

Other defs specifiy a benzoquinol  substrate, not a  benzoquinone ; was this also an error in orginal def. 
Other defs give H2O as a product.   but GO def does not; was this an error.

**Comment by sjm41** [comment]
_Perhaps EC:1.14.99 might be better parent if we have it already._

I don't see an existing GO term corresponding to the EC:1.14.99.- grouping class
There are 23 other GO terms with an xref of EC:1.14.99.* - 22 of these have GO:0016705 as a parent, so adding that parent here would at least be consistent.  (The other term it needs adding as a parent to is "GO:0140382 tryptamine 4-monooxygenase activity".)

**Comment by sjm41** [comment]
Regarding the final GO term name:
The accepted EC name is "3-demethoxyubiquinol 3-hydroxylase", which is less of a mouthful so we could use that.  (6-methoxy-3-methyl-2-(all-trans-polyprenyl)-1,4-benzoquinol 5-hydroxylase" is a alternative name.)
https://enzyme.expasy.org/EC/1.14.99.60

**Comment by sjm41** [comment]
@hdrabkin Can we proceed with the following (based on the above):

1. Change GO:0008682 name to "3-demethoxyubiquinol 3-hydroxylase activity"
2. Change GO:0008682 def to "Catalysis of the reaction: a 6-methoxy-3-methyl-2-all-trans-polyprenyl-1,4-benzoquinol + AH2 + O2 = A + a 3-demethylubiquinol + H2O [RHEA:50908]" (to match RHEA def)
3. Add GO:0016705 as a parent to GO:0008682

**Comment by hdrabkin** [comment]
Done

**Comment by sjm41** [comment]
Thanks!
