### ISSUE TITLE
acyl-CoA desaturase activity (GO:0016215) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21108]
I think this term should have the additional parent "monooxygenase activity (GO:0004497)":

id: GO:0016215
name: acyl-CoA desaturase activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-CoA + reduced acceptor + O2 = desaturated-acyl-CoA + acceptor + 2 H2O." [EC:1.14.19.1, EC:1.14.19.5, GOC:mah]
synonym: "CoA desaturase activity" BROAD []
xref: EC:1.14.19.-
is_a: GO:0016717 ! oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water

**Comment by pgaudet** [comment]
Fixed a few xrefs in that branch (added RHEA whenever I could find them) 

I also removed the EC from acyl-CoA desaturase activity (GO:0016215) since it corresponded to specific children.

**Comment by pgaudet** [comment]
@sjm41 @kaxelsen 
Isn't ''oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water'' the same as 'monooxygenase activity' ? (Catalysis of the incorporation of one atom from molecular oxygen into a compound and the reduction of the other atom of oxygen to water.)

**Comment by kaxelsen** [comment]
monooxygenase activity (EC 1.14) is a child of oxidoreductase activity (EC 1)

**Comment by pgaudet** [comment]
Thanks @kaxelsen

**Comment by kaxelsen** [comment]
Note that I updated my comment to something that was more relevant

**Comment by pgaudet** [comment]
@kaxelsen what EC/EC grouping would 
* GO:0004497 | monooxygenase activity: Catalysis of the incorporation of one atom from molecular oxygen into a compound and the reduction of the other atom of oxygen to water. 
correspond to?

**Comment by sjm41** [comment]
@kaxelsen So am I wrong in suggesting that GO:0016215 acyl-CoA desaturase activity (EC:1.14.19.-) should be classed as a monooxygenase??  The reaction appears to fit the GO def of monooxygenase activity (see initial posting above), but I think you're saying that EC:1.14.19.- doesn't fit under that?

**Comment by kaxelsen** [comment]
As said above this statement equally well fits:
1.14.13.-    With NADH or NADPH as one donor, and incorporation of one atom of oxygen.
1.14.14.-    With reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen.
1.14.15.-    With reduced iron-sulfur protein as one donor, and incorporation of one atom of oxygen.
1.14.16.-    With reduced pteridine as one donor, and incorporation of one atom of oxygen.
1.14.17.-    With reduced ascorbate as one donor, and incorporation of one atom of oxygen.
1.14.18.-    With another compound as one donor, and incorporation of one atom of oxygen.

The difference between these sub-subclasses is the nature of the electron acceptor that participates in the reaction. This is not mentioned by GO:0004497, so we cannot be more specific.

**Comment by kaxelsen** [comment]
@sjm41 Yes, I believe it is as the reaction does not incorporate an atom of oxygen in the substrate.

**Comment by sjm41** [comment]
Ah, I see.....(I think).  I was also getting confused regarding the differences between GO:0016717 and GO:0004497 and how they relate to ECs.

Sorry @pgaudet, looks like my original suggestion here was wrong - can you reverse that?  But good that you sorted out those EC/Rhea xrefs, and clarified some relationships here.

**Comment by pgaudet** [comment]
Sure, I'll fix back.

**Comment by sjm41** [comment]
@kaxelsen Sorry, another thing to check.  You say GO "GO:0004497 | monooxygenase activity" best fits EC 1.14.13.- to 1.14.18.-.
But "GO:0004497 | monooxygenase activity" is also appropriate for certain members of [EC:1.13.-.-](https://enzyme.expasy.org/EC/1.13.-.-), right?
e.g.  lactate 2-monooxygenase activity (GO:0050040) 1.13.12.4
e.g. inositol oxygenase activity (GO:0050113) 1.13.99.1

**Comment by kaxelsen** [comment]
@sjm41 For the examples you give, yes. But for many other enzymes in subclass EC 1.13 there is no water produced, so it is not generally true .
Examples:
EC 1.13.11.3 3,4-dihydroxybenzoate + O2 = 3-carboxy-cis,cis-muconate + 2 H+ (RHEA:10084)
EC 1.13.12.13 coelenterazine + O2 = CO2 + coelenteramide + hν (RHEA:20417)
EC 1.13.12.20 noranthrone + O2 = H2O + norsolorinic acid (RHEA:35191)
EC 1.13.99.3  H+ + L-tryptophan + O2 = 3-indoleglycolaldehyde + CO2 + NH4+ (RHEA:22620)

**Comment by sjm41** [comment]
Yep, understood, thanks!
