### ISSUE TITLE
remove "family" axis of classification from cul4 ligases

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21115]
currently
GO:0080008   Cul4-RING E3 ubiquitin ligase complex
--GO:0031465    Cul4B-RING E3 ubiquitin ligase complex 
-----GO:0043494    CLRC complex
--GO:0031464    Cul4A-RING E3 ubiquitin ligase complex

note, cul4A has exact synonyms 
DCX complex | exact
CRL4 complex | exact
CDL4 complex | exact
which seems odd.

CLRC is a broadly conserved cul4 complex, first characterised in yeast, PMID:16127433
BUT yeast only have one cullin 4  which is a memeber of all of the different cullin4 complexes. So although there may be 2 cullin4's in metazoa, this criteria shouldn't be used to define the complexes.
(i.e. yeast do not have CUL4B, therefore CLRC can't be a Cul4B complex).

I would remove/merge the Cul4 a/b terms. The actual  Cul4 complexes have different compositions based on other variable subunits that would make more useful distinguishing criteria.

**Comment by pgaudet** [comment]
@bmeldal Is this OK with you ?

**Comment by bmeldal** [comment]
Yes, looks like a sensible decision. Saccharomyces cerevisiae doesn't have a gene called "cul4", but I guess some genes are in that family.

Would you keep GO:0043494 CLRC complex as child or sibling to GO:0080008 Cul4-RING E3 ubiquitin ligase complex? I have no strong feelings ;-)

We only have human and mouse cul4a and cul4b variants. Nothing annotated to GO:0080008 Cul4-RING E3 ubiquitin ligase complex for S.c.

**Comment by ValWood** [comment]
S. cerevisiae doesn't have a cullin.

**Comment by ValWood** [comment]
That should say cullin4, it has cullin 1 and cullin 3

**Comment by raymond91125** [comment]
Would it be better, more conservative by keeping existing annotations to their chosen terms, if we have:
GO:0080008 Cul4-RING E3 ubiquitin ligase complex
--GO:0031465    Cul4B-RING E3 ubiquitin ligase complex
--GO:0043494    CLRC complex
--GO:0031464    Cul4A-RING E3 ubiquitin ligase complex

**Comment by ValWood** [comment]
That would work. I still think the grouping by family  is a bit strange, this seems to be quite a heterogenous bunch of complexes. But it isn't so important right now so I would do this and close. I think my. original problem was that  I was getting mappings to the CUL4-B term, and it was difficult to suppress them based on CLRC positioning. This change will resolve that problem.
