### ISSUE TITLE
GO:0000159 synonyms and definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21111]
GO:0000159   protein phosphatase type 2A complex

I could not find this last week when searching on  PP2A (as most refer to it).

Add synonym 
PP2A complex  (exact)
PP2A-pi (narrow)
PP2a-protector (narrow)

**Comment by pgaudet** [comment]
Did you want any changes in the definition? (see ticket label)

**Comment by ValWood** [comment]
I'm not convinced this is always true. However, I am not sure where it comes from. I can't find it in the definition source?


 "that is polycation-stimulated (PCS), being directly stimulated by protamine, polylysine, or histone H1; it constitutes a subclass of several enzymes activated by different histones and polylysine, and consists of catalytic, scaffolding, and regulatory subunits"
