### ISSUE TITLE
Tweak def of  GO:0004768 stearoyl-CoA 9-desaturase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21122]
GO def:
 Catalysis of the reaction: stearoyl-CoA + 2 ferrocytochrome b5 + O2 + 2 H+ = oleoyl-CoA + 2 ferricytochrome b5 + H2O. 

EC def:
Stearoyl-CoA + 2 ferrocytochrome b5 + O(2) + 2 H(+) <=> oleoyl-CoA + 2 ferricytochrome b5 + 2 H(2)O

Can you add the "2" to the H2O in the GO def please.

**Comment by pgaudet** [comment]
How do you pick up those thing? I'm asking because we should consider having a check on GO's side... 

Thanks, Pascale

**Comment by sjm41** [comment]
_How do you pick up those thing? I'm asking because we should consider having a check on GO's side..._
Short answer - this just came out of a follow up check to some fly annotations following Kristian's comment on #21108.

Longer answer - I'm nearing the end of our project to review all the fly enzyme annotations.  As I cross-check classifications from different GO sources and any independent EC annotations, I keep finding discrepancies that end up as tickets for changes to manual GO annotations, InterPro2GO, PAINT or the GO itself (we wrote up the general approach in https://academic.oup.com/database/article/doi/10.1093/database/bay144/5298334)

Not sure it would be possible to script, but it would be great to check the GO reactions match the EC/Rhea reactions.  Maybe easiest just to delete the GO def and paste in the EC/Rhea reaction (at least where the GO def follows the pattern "Catalysis of the reaction.....".
Another scriptable thing to check would be parentage - e.g. any GO term with EC:1.2.3.4 should have the GO parent with xref EC:1.2.3.-, and any GO term with EC:1.2.3.* should have the GO parent with xref EC:1.2.-.- (etc)
