### ISSUE TITLE
GO:NEW    invasive hyphae formation 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21125]
background
Plant infection requires an infection cell, called an appressorium,
which uses a pressure-driven mechanism to breach the tough cuticle of the leaf (3, 4). Once inside plant tissue, the fungus elaborates pseudohyphalike
invasive hyphae that rapidly colonize living host cells, secreting effector molecules to suppress host immunity and facilitate infection (5).

we have plenty of terms for 'entry into host'  but only 
GO:0106259    cell-to-cell migration in host
for cell to cell invasion.

I would therefore like to request 
GO:NEW    invasive hyphae formation 
synonym cell-to-cell migration by invasive hypha (exact)
synonym host  tissue colonization  (related)
synonym plant tissue colonization (related
synonym invasive growth (related, because although it is often called 'invasive growth' here we are describing the physical process rather than a size increase)

is_a  GO:0106259    cell-to-cell migration in host

Definition
The directional movement of a hyphal filament from one host cell to another. This process involves the clearance of plant-derived plasmodesmal occlusion materials, cytoskeleton based constriction of invasive hypha to traverse plasmodesmata.  Septins and F-actin are reorganized into an hourglass shape at the point of maximum hyphal constriction.

I know there is a term
GO:0036267   invasive filamentous growth
but this isn't describing invasion of cells.

@CuzickA  does this sound OK?
Needed for
PMID:29567712
instead of
GO:0030448 | hyphal growth
and GO:0106259 | cell-to-cell migration in host

**Comment by pgaudet** [comment]
This is also different from appressorium formation & terms related to that process?

**Comment by ValWood** [comment]
Yes the appressorium is for entry into host, but not cell-to-cell migration, if I understood correctly. See the first paragraph which separates these 2 processes.

@CuzickA  is that correct?

**Comment by CuzickA** [comment]
> Yes the appressorium is for entry into host, but not cell-to-cell migration, if I understood correctly. See the first paragraph which separates these 2 processes.
> 
> @CuzickA is that correct?

Yes this is correct

**Comment by ValWood** [comment]
There  will still be some broader issues to resolve in this area. Entry into host and migration within host will be very different for different species  with different hosts (sometimes will be simultaneous), so these groupings are a little artificial.  A topic for a future call.

**Comment by pgaudet** [comment]
I will use 'cell-to-cell migration by invasive hypha' as the term label, since 'formation' would be a child of 'development', it seems confusing.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140649
+name: cell-to-cell migration by invasive hypha
+namespace: biological_process
+def: "The directional movement of a hyphal filament from one host cell to another. This process involves the clearance of plant-derived plasmodesmal occlusion materials, cytoskeleton based constriction of invasive hypha to traverse plasmodesmata. Septins and F-actin are reorganized into an hourglass shape at the point of maximum hyphal constriction." [PMID:29567712]
+synonym: "host tissue colonization" BROAD []
+synonym: "invasive growth" BROAD []
+synonym: "invasive hyphae formation" EXACT []
+synonym: "plant tissue colonization" BROAD []
+is_a: GO:0106259 ! cell-to-cell migration in host
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21125 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-25T07:42:38Z

Also added comment: "Do not confuse with GO:0036267 invasive filamentous growth, which \ndoesn't describe invasion of cells within the host."

OK? 

Thanks, Pascale
