### ISSUE TITLE
kinetochore term merges

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21126]
merge
GO:0000778    condensed nuclear chromosome kinetochore
and
GO:0000777    condensed chromosome kinetochore
into GO:0000776   kinetochore

rename
GO:0000939    condensed chromosome inner kinetochore
to
 inner kinetochore

rename
GO:0000940    condensed chromosome outer kinetochore
to
outer kinetochore

merge
 GO:0000942    condensed nuclear chromosome outer kinetochore
into  GO:0000940

merge
GO:0000941    condensed nuclear chromosome inner kinetochore
into GO:0000939

**Comment by pgaudet** [comment]
why do you want to merge those ? Just so it's documented.

**Comment by ValWood** [comment]
because 

1. it is the same kinetochore. I thought that was the plan?  
The chromosome consensation status would be covered by the cell cycle phase (occurs_during blah). 

The inner kinetochore exists throughout the cell cycle, the outer kinetochore only during mitosis.  So in actual fact, there is not outer kinetochore when a chromosome is _not_ condensed.

2. My reason for requesting  right now is very trivial though.
I want to say 
kinetochore adaptor activity  _part_of_ blah _occurs_at_ GO:0000941 inner kinetochore

not
kinetochore adaptor activity  part_of blah occurs at GO:0000941 condensed nuclear chromosome inner kinetochore

which would be annoying for users because they will  likely think "what other sort of inner kinetochore is there" (for an organism with closed mitosis).

3. It also means that we use the same terms for open and closed mitosis which makes comparison easier.

**Comment by pgaudet** [comment]
I see - if I understand correctly it's the chromosome that's condensed, not the kinetochore, so there are not 2 different kinetochores. 

@srengel notifying you because SGD has a number of annotations to those terms.

**Comment by pgaudet** [comment]
We have ' GO:0000817 COMA complex part_of 'GO:0000778 condensed nuclear chromosome kinetochore' 
that seems wrong, the definition states that "This complex bridges the subunits that are in contact with centromeric DNA and the subunits bound to microtubules during kinetochore assembly." 
So I will remove any links to kinetochore.

**Comment by pgaudet** [comment]
Also GO:0042729 DASH complex  - the definition states that "The complex forms part of the kinetochore" - but right now it has a is_a relation to GO:0000942 condensed nuclear chromosome outer kinetochore
- I will move that to 'part of' 'outer kinetochore'
- I will also change the definition to mention outer kinetochore (rather than just kinetochore)

**Comment by pgaudet** [comment]
@ValWood 

GO:0031511 Mis6-Sim4 complex  is part_of GO:0000939 condensed chromosome inner kinetochore
However the definition does not mention kinetochore: "A protein complex that forms part of the inner centromere, which is involved in the loading of the centromeric histone h3 variant CENP-A onto centromeres and in centromere specific heterochromatin formation." - should we edit the definition?

**Comment by pgaudet** [comment]
@ValWood @cmungall 
GO:0000776 kinetochore 
is both  GO:0099080 supramolecular complex
and GO:0043228 non-membrane-bounded organelle

I would expect those to be disjoint classes; what do you think?

**Comment by ValWood** [comment]
GO:0000817 COMA complex is  definitely part_of kinetochore (It seems to overlap with the complex called 
Mis6-Sim4 complex (GO:0031511)  in fission yeast and higher eukaryotes)

GO:0031511 Mis6-Sim4 complex is part_of GO:0000939 condensed chromosome inner kinetochore
we could edit.
**inner centromere** and **inner kinetochore** are analogous. Inner kinetochore aligns better with component terms, so yes that can be changed.

DASH complex part_of outer kinetochore -good

**Comment by ValWood** [comment]
is both GO:0099080 supramolecular complex
and GO:0043228 non-membrane-bounded organelle

I think it is both. The ribosome and is also described as both a complex and an organelle.

**Comment by pgaudet** [comment]
> is both GO:0099080 supramolecular complex
and GO:0043228 non-membrane-bounded organelle

OK - should inner and outer kinetochore have the same parentage then ?

**Comment by ValWood** [comment]
> OK - should inner and outer kinetochore have the same parentage then ?

only as part_of kinetochore?

**Comment by pgaudet** [comment]
Sorry my question was not direct enough: 

- are inner and outer kinetochore protein complexes, supramolecular complexes, or neither?

**Comment by ValWood** [comment]
On their own no, probably not. The inner kinetochore almost definitely not. I would  probably only class the entire kinetochore as an organelle (since that is the functional unit)
