### ISSUE TITLE
new GO term

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#21127]
Would it be possible to create a new term: response to interleukin-33?
PMID:29686383
Thank you
Rossana

**Comment by pgaudet** [comment]
Hi @rozaru 

Thanks for the suggestion. Why not use the more precise term 'GO:0038172 interleukin-33-mediated signaling pathway' ?

**Comment by rozaru** [comment]
Thanks Pascale! I should have searched with 'interleukin-33' alone. I will use the term you suggested.
