### ISSUE TITLE
NTR: Positive regulation of GO:0038160 'CXCL12-activated CXCR4 signaling pathway'

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#21129]
Hi,

I would like to request the term 'positive regulation of CXCL12-activated CXCR4 signaling pathway' based on PMID: 33097708.

The authors report, that expression of the chemoattractive receptor, CXCR4, is diminished in TREM2 knockout microglia and exposure to its ligand, SDF-1α, uncovers a significant deficit in the calcium response to this ligand (figure 5).

Definition:

Any process that activates or increases the frequency, rate or extent of CXCL12-activated CXCR4 signaling pathway.

Synonyms similar to  GO:1903082 'positive regulation of C-C chemokine receptor CCR7 signaling pathway'

Please let me know if you need any more information.

Thanks,

Penelope

**Comment by pgaudet** [comment]
Mutant evidence is not sufficient to say that a protein regulates a pathway. Can you use the relation 'acts upstream of, positive effect' + the GO term 'CXCL12-activated CXCR4 signaling pathway'?

**Comment by pgarmiri** [comment]
That could work. Thanks @pgaudet !

**Comment by pgarmiri** [comment]
Although  I am not sure if it complies with the requirement for the upstream_of ....There are no evidence that it is required for the process to occur as per the guidelines. It actually affect the levels of expression of CXCR4 mRNA and the authors believe that this is one of the ways that it regulated the pathway.

"A gene product 'acts upstream of, positive effect' of a biological process if its activity (MF) is: 1) executed before the beginning of the process, 2) is not part of the process, and 3) is required for the process to occur."

 @pgaudet , what do you think?

**Comment by pgaudet** [comment]
would 'acts upstream of or with, positive effect' work ? 

If not, maybe there just isn't enough data to annotate?

**Comment by pgarmiri** [comment]
Yes, that's more like it!
Thanks
Penelope
