### ISSUE TITLE
GO:0071174 missing links to subtypes?

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#21128]
GO:0071174 ! mitotic spindle checkpoint signaling has the `gocheck_do_not_manually_annotate` flag, but it only has one subclass (and a regulation link).

Is it correctly flagged? If so, are some links to other terms missing? The comment suggests the latter: "... it should always be possible to specify the type of spindle checkpoint (assembly, orientation or Dma1-dependent)." (But also note that  "Dma1-dependent checkpoint" is a narrow synonym for GO:0007094, not a separate term

**Comment by ValWood** [comment]
Should not have "do not annotate" this  is a 'hangover' from the term merges when detection and signalling were separated.

**Comment by ValWood** [comment]
Actually that wasn't correct.
Some terms must be missing. There should be 2 subtypes to mitotic spindle checkpoint signalling

1. mitotic spindle assembly checkpoint signalling
2. mitotic spindle orientation checkpoint signalling

**Comment by ValWood** [comment]
In QuickGO I see

GO:0031578                mitotic spindle orientation checkpoint signaling | is_a
GO:0007094                mitotic spindle assembly checkpoint signaling | is_a

**Comment by ValWood** [comment]
note that for pombe it is always 
GO:0007094 mitotic spindle assembly checkpoint signaling

because fission yeast does not have
 GO:0031578 mitotic spindle orientation checkpoint signaling

@pgaudet could a taxon restriction be added to  GO:0031578
I think the taxon restriction should be only in 'budding yeast' but I don't know how to specify that?

**Comment by mah11** [comment]
> mitotic spindle assembly checkpoint signalling
> mitotic spindle orientation checkpoint signalling

Both terms exist, but the `GO:0007094 is_a GO:0071174` link isn't visible in Canto. Perhaps it's just a timing issue; if not, we can investigate locally.

> @pgaudet could a taxon restriction be added to GO:0031578
> I think the taxon restriction should be only in 'budding yeast' but I don't know how to specify that?

Is there no orientation checkpoint in other species where spindle orientation is an issue (e.g. animal cells ... IIRC it's been studied in C. elegans)? If we don't know, it might be safer to use never in Schizosaccharomyces.

**Comment by ValWood** [comment]
OK only "never in fission yeast". It was for a short while considered to exist in fission yeast.  but that view was over-ridden. I don't  know the current status in other species.
At present the only annotations are from budding yeast.

**Comment by pgaudet** [comment]
- I confirm that GO:0007094 is_a GO:0071174 in the current (editors') version of the ontology. 
- I will add GO:0031578 never in Schizosaccharomyces
- Should I remove do not annotate from GO:0071174 ! mitotic spindle checkpoint signaling?

**Comment by pgaudet** [comment]
Actually we already have 

GO:0031578 | mitotic spindle orientation checkpoint | **ONLY IN** NCBITaxon:716545 | saccharomyceta

so, I think we're good?

**Comment by pgaudet** [comment]
RE the original comment in the ticket - I fixed the term comment that refers to 'assembly, orientation or Dma1-dependent', to remove Dma1-dependent.

**Comment by ValWood** [comment]
>Should I remove do not annotate from GO:0071174 ! mitotic spindle checkpoint signaling?

It should be possible to be more specific so I think it is OK.
