### ISSUE TITLE
missing parent, effector mediated

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21120]
GO:0140403    effector-mediated suppression of host innate immune response by symbiont

should have the parent 
GO:0042783    evasion of host immune response

**Comment by pgaudet** [comment]
I thought we said evasion was different from direct interaction/suppression
see for example discussion here: https://github.com/geneontology/go-ontology/issues/18337

Evasion is defined as "A process by which an organism **avoids** the effects of the host organism's immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction."

Based on this I would not add this parent?

**Comment by ValWood** [comment]
Right, I was just thinking that.
