### ISSUE TITLE
GO:0075202    modulation of symbiont penetration hypha formation for entry into host 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21121]
GO:0075202    modulation of symbiont penetration hypha formation for entry into host | GO:0075203    positive regulation of symbiont penetration hypha formation for entry into host

I am wondering why GO:0075202 is 'modulation' rather than 'regulation?

**Comment by pgaudet** [comment]
The whole multiorg branch is like this - modulation is used everywhere, never modulation.

**Comment by ValWood** [comment]
I thought we only used modulation when some aspect of the host was being modulated. Here it isn't, this is a pathogen specific process, albeit one that is used to infect the host. it isn't 'modulating' a host process.

Also here the children are positive/negative regulation rather than activation or suppression.

Regulation would seem to be correct to me here.

**Comment by pgaudet** [comment]
OK, and since we moved that branch out of symbiotic process that does make sense.

**Comment by pgaudet** [comment]
Changed term labels as follows: 

 id: GO:0075202
-name: modulation of symbiont penetration hypha formation for entry into host
+name: regulation of penetration hypha formation

 id: GO:0075203
-name: positive regulation of symbiont penetration hypha formation for entry into host
+name: positive regulation of penetration hypha formation

Thanks, Pascale
