### ISSUE TITLE
hechtian strand, new term request

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#21138]
Dear GO-Team,
there is a localization for enzyme 2.4.1.173: "hechtian strand". I found this definition in Wikipedia: A stretched plasma membrane extending from the plasmolysed protoplast to the cell wall in plants. (https://en.wiktionary.org/wiki/Hechtian_strand).
Could it be a new term, or would you use the term "plasma membrane" instead?
Thanks for your help.
Kind regards, Marion Gremse (from brenda-enzymes.org)

**Comment by tberardini** [comment]
Probably a candidate for a new cc term.  See: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7284614/

My 2 cents.

**Comment by pgaudet** [comment]
Thanks @tberardini !

**Comment by krchristie** [comment]
I'm going to put the term in this way. The Wikipedia page def seems a bit old, so I based the definition on the paper Tanya linked.

@brendamg @tberardini - Let me know if you have any changes or additions.

Name: Hechtian strand
Def: An extended membranous thread which firmly connects the plasma membrane to the cell wall during plasmolysis such that the plasma membrane does not separate from the cell wall completely.
Def ref: PMID:32397402
is_a: cellular anatomical entity

**Comment by krchristie** [comment]
Also, I'm going to add the taxon constraint:
only in NCBITaxon:33090	Viridiplantae

**Comment by brendamg** [comment]
Thank you for adding the term!
