### ISSUE TITLE
NTR: maternal contribution terms

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#21135]
general reference for all of these  https://www.ncbi.nlm.nih.gov/books/NBK53192/

maternal contribution of gene product to offspring
 part_of  oocyte development
is_a developmental process involved in reproduction
def: The process whose specific outcome is the contribution of maternal gene products to offspring for use until the offspring's genome is activated.

maternally deposition of RNA in oocyte
is_a maternal contribution of gene product to offspring
def: The process whose specific outcome is the deposition of maternal RNA in the developing oocyte.

maternally deposition of protein in oocyte
is_amaternal contribution of gene product to offspring
def: The process whose specific outcome is the deposition of maternal protein in the developing oocyte.

regulation of maternally deposited RNA stability
is_a  regulation of mRNA stability
def: Any process that modulates the propensity of maternally deposited RNA molecules to degradation. Includes processes that both stabilize and destabilize RNAs

regulation of maternally deposited protein stability 
is_a regulation of protein stability
def: Any process that affects the structure and integrity of a maternally deposited  protein, altering the likelihood of its degradation or aggregation. Includes processes that both stabilize and destabilize proteins.

**Comment by raymond91125** [comment]
The proposed BPs may be PART_OF  "oocyte construction" DEF "The synthesis, deposition, and organization of the materials in a cell of an ovary; where the cell can then undergo meiosis and form an ovum. An example of this is found in Drosophila melanogaster." or perhaps "oocyte maturation" DEF "A developmental process, independent of morphogenetic (shape) change, that is required for an oocyte to attain its fully functional state. Oocyte maturation commences after reinitiation of meiosis commonly starting with germinal vesicle breakdown, and continues up to the second meiotic arrest prior to fertilization."

All materials in an oocyte are maternally contributed thus I don't think there is a need to specify that. @cerivs Could you provide a paper or two that you intend to annotate with these proposed terms? Are these about "protein transport", "protein localization", "regulation of mRNA stability" in the oocyte?

Thanks. raymond

**Comment by ValWood** [comment]
closing, as these seem out of scope (GO CAM)
