### ISSUE TITLE
axopodium, lobopodium, reticulopodium, New term request

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#21139]
Dear GO-Team,
I found the terms id: GO:0031143 name: pseudopodium and id: GO:0030175 name: filopodium in the GO cellular component tree.
In the BRENDA Database we also have the terms axopodium, lobopodium and reticulopodium.

- axopodium: A long and slender, semipermanent type of locomotor pseudopodium that has a central axial filament composed of a bundle of microtubules. Dorlands Medical Dictionary. Synonym: axiopodium
- lobopodium: A wide, blunt pseudopodium composed of both ectoplasm and endoplasm. Dorlands Medical Dictionary
- reticulopodium: A filamentous pseudopodium with interconnected branches. Dorlands Medical Dictionary Synonym:rhizopodium

What do you think? Should they be added as new terms to the GO?
Best wishes,
Marion Gremse

**Comment by pgaudet** [comment]
Hi @brendamg 

Thanks for the suggestions. I am reluctant to add terms that I dont think we will annotate. I dont find any recent papers on those structures, and especially I could not find anything that specified the composition, so I dont know which gene products could be annotated to those. (I may have just missed the right papers though). 

We could add those labels as NARROW SYNONYMS of GO:0031143 pseudopodium, what do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@brendamg What do you think of my suggestion above?

**Comment by brendamg** [comment]
Hi, sorry, I don`t know if these terms are synonyms. The definitions say that the terms are a kind of pseudopodium (is_a relationship). But we`ll be happy if we could use them in our database - in accordance to the GO cellular component ontology.

**Comment by pgaudet** [comment]
Do you have references and definitions for those terms? I'll add them as synonyms for now; if you can provide more information I will create the terms. 

Thanks, Pascale
