### ISSUE TITLE
Protein-L-histidine N-pros-methyltransferase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#21146]
Hi GO,

I would need a reaction for METTL9 (Q9H1A3) that catalyzes the 1-methylhistidine modification. His can be modified at 2 positions: the pros and tele. While the enzyme that catalyzes the tele form is known for several year (GO:0018064), the enzyme for the pros form was characterized only recently.

Name: protein-L-histidine N-pros-methyltransferase activity
Definition: Catalysis of the reaction: L-histidyl-[protein] + S-adenosyl-L-methionine = N(pros)-methyl-L-histidyl-[protein] + S-adenosyl-L-homocysteine

Xref: Rhea:67076 (not yet public)
PMID:33563959
child of GO:0008757
child of GO:0008170

Please note that GO:0018064 should also be modified. This reaction, which corresponds to EC 2.1.1.85, mediates N-tele-methylation. I would modify its name and definition.

FROM:
protein-L-histidine N-tele-methyltransferase
TO:
protein-histidine N-methyltransferase activity

FROM:
Catalysis of the reaction: S-adenosyl-L-methionine + protein L-histidine = S-adenosyl-L-homocysteine + protein N-methyl-L-histidine.
TO:
atalysis of the reaction:  L-histidyl-[protein] + S-adenosyl-L-methionine = N(tele)-methyl-L-histidyl-[protein] + S-adenosyl-L-homocysteine 

RX PubMed=33563959; DOI=10.1038/s41467-020-20670-7
RA Davydova E., Shimazu T., Schuhmacher M.K., Jakobsson M.E., Willemen H.L.D.M., Liu T., Moen A., Ho A.Y.Y., Malecki J., Schroer L., Pinto R., Suzuki T., Groensberg I.A., Sohtome Y., Akakabe M., Weirich S., Kikuchi M., Olsen J.V., Dohmae N., Umehara T., Sodeoka M., Siino V., McDonough M.A., Eijkelkamp N., Schofield C.J., Jeltsch A., Shinkai Y., Falnes P.O.
RT The methyltransferase METTL9 mediates pervasive 1-methylhistidine modification in mammalian proteomes.
RL journal article: Nat. Commun. 12:891-891 (2021)

Thanks

Sylvain

**Comment by hdrabkin** [comment]
I think the older term should be named
Protein-L-histidine N-tele-methyltransferase activity instead of protein-histidine N-methyltransferase activity to indicate the specificity for the tele position.

**Comment by hdrabkin** [comment]
| RHEA:19369, which maps to the EC mentioned, uses the CHEBI for the tele position.
-- | --

**Comment by hdrabkin** [comment]
+id: GO:0106370
+name: protein-L-histidine N-pros-methyltransferase activity

**Comment by sylvainpoux** [comment]
Hi Harold,
many thanks! Regarding GO:0018064, you are right Rhea mentions the tele position, but your definition does not mention it and I think it would be worth specifying this.

The current definition of GO:0018064
Catalysis of the reaction: S-adenosyl-L-methionine + protein L-histidine = S-adenosyl-L-homocysteine + protein N-methyl-L-histidine. 

Thanks

Sylvain

**Comment by hdrabkin** [comment]
Hi Sylvain
I did change it yesterday to Catalysis of the reaction: L-histidyl-[protein] + S-adenosyl-L-methionine = N(tele)-methyl-L-histidyl-[protein] + S-adenosyl-L-homocysteine.
which parallels the new term. 
However, now today I notice that the EC assigned to the reaction specifies the TAU position, which is not on the histidine ring. Thus the RHEA does not seem appropriate to the EC RHEA maps to it. 
We may need three terms
one for tau (the existing term
one for the tele (which is where the RHEA should be for GO:0018064
one or the pros which is where the new rhea (for your requested term) will map.
I will write @amorgat at RHEA to verify the EC mapping

**Comment by hdrabkin** [comment]
Nevermind, the "TAU" seems to be the same as tele; but searching on N(tau)-methyl-histidine in chebi gave me hits to N(alpha), which is not in the ring. So tau==tele.

**Comment by sylvainpoux** [comment]
Hi Harold,
I can confirm that Tau and tele are the same. I checked with Rhea last week
Cheers
Sylvain

**Comment by hdrabkin** [comment]
whew!

**Comment by hdrabkin** [comment]
Rhea:67076 (not yet public) 5/4/2021

**Comment by sylvainpoux** [comment]
Hi Harold, 
I would suggest to contact Anne (@amorgat) for more information
Thanks
Sylvain

**Comment by hdrabkin** [comment]
@sylvainpoux 
Assuming the RHEA was made around the ticket beginning, it may be possible we have to wait a bit. (maybe this month's release).

**Comment by pgaudet** [comment]
Next public release is at the end of July, I think

**Comment by amorgat** [comment]
Hi all, sorry for the late reply - RHEA:67076 was approved the 2021-03-18, so it will be available on Rel 119 (June 2nd)

**Comment by hdrabkin** [comment]
RHEA added; closing.

**Comment by sjm41** [comment]
@sylvainpoux @hdrabkin I think 'GO:0106370 protein-L-histidine N-pros-methyltransferase activity' should have "protein methyltransferase activity (GO:0008276)" as an additional parent. Agree?

Sylvain's original ticket also requested 'GO:0008170 N-methyltransferase activity' as a parent, which I don't see.

**Comment by hdrabkin** [comment]
Since protein methyltransferase activity is a child of 'methyl transferase', I have added protein methyltransferase activity and removed 'methyl transferase' as an asserted parent.
