### ISSUE TITLE
NTR: amastigogenesis

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21156]
Hi,
Can I request a new term for amastigogenesis please?

Accession: GO:xxxxxx
Name: amastigogenesis
Ontology: biological_process
Definition: The morphological, biochemical and genetic changes that induce the differentiation of metacyclic parasites into amastigotes in some of the Trypanosomatidae species such as Leishmania parasites and Trypanosoma cruzi. This process occurs inside the cells of the mammalian hosts, particularly in macrophages and other phagocytic cells in Leishmania parasites.
is_a: GO:0044114 ! development of symbiont in host
[RO:0002224 relation] RO:0002224: OPL:0000322 ! Trypanosomatida metacyclic stage
[RO:0002230 relation] RO:0002230: OPL:0000114 ! amastigote stage
Taxonomic restriction: NCBITaxon:5654 ## Trypanosomatidae
Source: PMID:12377273, PMID:13129524, PMID:26752404, DOI:10.5772/intechopen.84639, GOC:ach

Thanks & best wishes,
Achchuthan

**Comment by krchristie** [comment]
Hi @Achchuthan 

I'm putting the term in, but I'm not sure what you were suggesting I should do with the RO terms:
- [RO:0002224 relation] RO:0002224: OPL:0000322 ! Trypanosomatida metacyclic stage
- [RO:0002230 relation] RO:0002230: OPL:0000114 ! amastigote stage

To go ahead and get the term in for you, I'm putting it with the stanza I've included below. Let me know what you are thinking with respect to the RO terms and we can update the term.

Thanks,

-Karen

[Term]
id: GO:0120310
name: amastigogenesis
namespace: biological_process
def: "The morphological, biochemical and genetic changes that induce the differentiation of metacyclic parasites into amastigotes in some of the Trypanosomatidae species such as Leishmania parasites and Trypanosoma cruzi. This process occurs inside the cells of the mammalian hosts, particularly in macrophages and other phagocytic cells for Leishmania parasites." [DOI:10.5772/intechopen.84639, GOC:ach, GOC:krc, PMID:12377273, PMID:13129524, PMID:26752404]
is_a: GO:0044114 ! development of symbiont in host
created_by: krc
creation_date: 2021-03-23T21:17:19Z

**Comment by Achchuthan** [comment]
Hi @krchristie,
Thank you so much for working on my NTRs so quickly. I really appreciate your help.

Regarding the RO relations, Amastigogenesis results in the differentiation of metacyclic stage parasites into amastigote stage parasites. So, I was proposing to include RO relation "Starts with (RO:0002224)" for "Trypanosomatida metacyclic stage" (OPL:0000322) and RO relation "ends with" (RO:0002230) for "amastigote stage" (OPL:0000114). I see that Ontology for Parsite Life Cycle (OPL) has been loaded onto GO and RO:0002230 has been added to the GO term "metacyclogenesis" (GO:0140384) with OPL term.

I am not sure whether this answers your question. Please let me know whether you need any additional clarifications.

Thanks & best wishes,
Achchuthan

**Comment by Achchuthan** [comment]
This is the issue #17941 of metacyclogenesis, where RO relation to OPL has been added.

**Comment by krchristie** [comment]
[RO:0002224 relation] starts with : OPL:0000322 ! Trypanosomatida metacyclic stage
- 'starts with' some 'Trypanosomatida metacyclic stage'

[RO:0002230 relation] ends with : OPL:0000114 ! amastigote stage
- need to import ID for OPL:0000114 ! amastigote stage

**Comment by Achchuthan** [comment]
@krchristie,
Thanks! I'll make sure that I provide the RO relations in the suggested format in the future.
-Achchuthan

**Comment by krchristie** [comment]
Hi @pgaudet @balhoff 

Yesterday (3/25/21), I followed the instructions here: http://wiki.geneontology.org/index.php/Adding_Terms_and_Regenerating_the_Import_Files to add a new OPL term to the opl_terms.txt file. I did this manually and commited at the same time as I committed a change to the go-edit.obo file (bolded line below and viewable here: https://github.com/geneontology/go-ontology/pull/21209/files ). 

 1 src/ontology/imports/opl_terms.txt
Viewed
@@ -1,3 +1,4 @@
http://purl.obolibrary.org/obo/OPL_0000149
http://purl.obolibrary.org/obo/OPL_0000006
http://purl.obolibrary.org/obo/OPL_0000322
**http://purl.obolibrary.org/obo/OPL_0000114**


I see the new line present at the end of the opl_terms.txt file, but neither the opl_import.obo or opl_import.owl files have changed since February 5th. I am still not able to use the term OPL_0000114 in Protege. 

Is there something else that needs to be done to make this term available to use?

**Comment by balhoff** [comment]
@krchristie you did everything right. The OPL import job runs weekly, so it just hadn't come around again yet. But I pressed the button to make it go ahead and start: #21219

**Comment by krchristie** [comment]
> @krchristie you did everything right. The OPL import job runs weekly, so it just hadn't come around again yet. But I pressed the button to make it go ahead and start: #21219

Thanks @balhoff 

What is the normal schedule to run the OPL import, over the weekend? 

Is weekly the typical schedule for term import jobs, or do some run more frequently?

**Comment by balhoff** [comment]
> What is the normal schedule to run the OPL import, over the weekend?

The jobs are distributed a bit randomly throughout the week so they don't all run at once.

> Is weekly the typical schedule for term import jobs, or do some run more frequently?

Right now they are all weekly, except the taxon constraints which runs every day.
