### ISSUE TITLE
missing parent effector-mediated suppression of host innate immune response by symbiont

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21158]
GO:0140403 | effector-mediated suppression of host innate immune response by symbiont
is not a descendant of
GO:0140590    effector-mediated suppression of host defenses by symbiont

Isn't that always true?

**Comment by ValWood** [comment]
@mgiglio99 

this is the one I spotted with a missing parent.

**Comment by pgaudet** [comment]
Yes it is now - maybe I've added it when we talked ? 

<img width="545" alt="image" src="https://user-images.githubusercontent.com/4782928/114177689-fefccd00-993c-11eb-81fc-a509e5769f56.png">
