### ISSUE TITLE
NTR: "Outward rectifier potassium channel inhibitor activity"

### ISSUE THREAD

**Issue by Kawatebi** [geneontology/go-ontology#21157]
Hello,

I would like to request the term 'outward rectifier potassium channel inhibitor activity' based on PMID: 28108814.

The authors report, the inhibition of a voltage-dependent outwardly rectifying potassium channel Kv1.3 by the toxin apamin (Figure 1).

Definition:

Binds to and stops, prevents, or reduces the activity of an outwardly rectifying potassium channel. 

Let me know if you require any more information.

Many thanks,

Kate

**Comment by pgaudet** [comment]
Hello @Kawatebi 

Do you annotate toxins ? Normally GO annotates gene products, so apamin would be out of scope (as far as I can tell it's not encoded by a gene?).

Thanks, Pascale

**Comment by Kawatebi** [comment]
Hi @pgaudet 

Apamin is a peptide found in bee venom https://www.uniprot.org/uniprot/P01500 and here is the mRNA sequence https://www.ebi.ac.uk/ena/browser/view/AAB34402

Cheers, Kate

**Comment by pgaudet** [comment]
Great, thanks!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140628
+name: outward rectifier potassium channel inhibitor activity
+namespace: molecular_function
+def: "Binds to and stops, prevents, or reduces the activity of an outwardly rectifying potassium channel." [PMID:28108814]
+is_a: GO:0019870 ! potassium channel inhibitor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21157 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-24T07:58:39Z

**Comment by Kawatebi** [comment]
@pgaudet 

Fantastic thanks
