### ISSUE TITLE
GO:0035516  oxidative DNA demethylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21159]
[Term]
id: GO:0035516
name: oxidative DNA demethylase activity
namespace: molecular_function
def: "Catalysis of the removal of the methyl group from one or more nucleotides within a DNA molecule involving the oxidation (i.e. electron loss) of one or more atoms." [PMID:12594517, PMID:16482161, PMID:18775698]
synonym: "2-oxoglutarate-dependent DNA demethylase" EXACT [PMID:17991826]
is_a: GO:0016491 ! oxidoreductase activity
is_a: GO:0035514 ! DNA demethylase activity

I think this is the same as https://enzyme.expasy.org/EC/1.14.11.33
DNA-base-CH(3) + 2-oxoglutarate + O(2) <=> DNA-base + formaldehyde + succinate + CO(2)
which is RHEA:30299.

If you agree, please add those two xrefs and make GO:0035516 a child of GO:0016706, 2-oxoglutarate-dependent dioxygenase activity (xref: EC:1.14.11.-) (replacing "is_a: GO:0016491 ! oxidoreductase activity)

Should also review whether 1.14.11.33 is an appropriate reference/xref on these 3 terms:
[Term]
id: GO:0103051
name: N1-methyladenine demethylase activity
namespace: molecular_function
def: "Catalysis of the reaction: 1-methyladenine + O2 + 2-oxoglutarate <=> adenine + carbon dioxide + formaldehyde + succinate." [EC:1.14.11.33, GOC:pz]
xref: MetaCyc:RXN0-984
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity

[Term]
id: GO:0103052
name: N3-methylcytosine demethylase activity
namespace: molecular_function
def: "Catalysis of the reaction: N3-methylcytosine + O2 + 2-oxoglutarate <=> H+ + cytosine + carbon dioxide + formaldehyde + succinate." [EC:1.14.11.33, GOC:pz]
xref: MetaCyc:RXN0-985
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity

[Term]
id: GO:0103053
name: 1-ethyladenine demethylase activity
namespace: molecular_function
def: "Catalysis of the reaction: 1-ethyladenine + O2 + 2-oxoglutarate(2-) <=> adenine + carbon dioxide + acetaldehyde + succinate." [GOC:pz, RHEA:30299]
xref: EC:1.14.11.33
xref: MetaCyc:RXN0-986
xref: RHEA:30299
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity

**Comment by pgaudet** [comment]
I agree GO:0103051, GO:0103052 an GO:0103053 (only IEA annotations) can merge into GO:0035516

**Comment by sjm41** [comment]
Thanks!
