### ISSUE TITLE
GO:0008933  lytic transglycosylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21167]
Something odd here:

[Term]
id: GO:0008933
name: lytic transglycosylase activity
namespace: molecular_function
def: "Catalysis of the specific cleavage of the beta-(1->4) glycosidic linkage between N-acetylmuramyl and N-acetylglucosaminyl residues in peptidoglycan, with the concomitant formation of 1,6-anhydro-N-acetylmuramyl residues." [PMID:10964424, PMID:22748813]
synonym: "murein transglycosylase B activity" NARROW []
synonym: "peptidoglycan lytic transglycosylase activity" EXACT []
xref: EC:3.2.1.-
is_a: GO:0016757 ! transferase activity, transferring glycosyl groups
is_a: GO:0061783 ! peptidoglycan muralytic activity

It has xref of EC:3.2.1.- (Hydrolases -> Glycosylases -> Glycosidases, ie. enzymes hydrolyzing O- and S-glycosyl compounds) but is has parent "is_a: GO:0016757 ! glycosyltransferase activity"

Also the only child of that term is:
[Term]
id: GO:0008932
name: lytic endotransglycosylase activity
namespace: molecular_function
def: "Catalysis of the specific cleavage of the beta-(1->4) glycosidic linkage between N-acetylmuramyl and N-acetylglucosaminyl residues in peptidoglycan, with the concomitant formation of 1,6-anhydro-N-acetylmuramyl residues. Acts on linkages within peptidoglycan chains (i.e. not at the ends) to produce shorter strands with 1,6-anhydromuramic acid ends." [PMID:10964424, PMID:9642199]
synonym: "murein lytic endotransglycosylase E activity" NARROW []
xref: EC:2.4.99.-
is_a: GO:0008933 ! lytic transglycosylase activity

This one does have a transferase EC xref of EC:2.4.99.- (Transferases -> Glycosyltransferases -> Transferring other glycosyl groups)

The EC xrefs above are for grouping terms, so both should probably be removed?  I don't easily see an existing EC for these specific reactions. (haven't checked Rhea)

From the definitions, it looks like they are both hydrolases, so the parent on GO:0008933 should be changed to "hydrolase activity, hydrolyzing O-glycosyl compounds (GO:0004553" (which correctly has EC xref 3.2.1.-)?

**Comment by hdrabkin** [comment]
So will remove 4.2.- as def ref for the GO:0016837; in general these incomplete ecs should NOT be uses as defintion xref.
I left the other parent  of GO:0008933 (GO:0061783; it's parent is just catalyic acivity)



.

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Great, thanks!

**Comment by pgaudet** [comment]
Fixed definitions to match EC. Added 'temporary' EC as def xref as this is now allowed. 

Created new term for EC:4.2.2.n1

+[Term]
+id: GO:0140100
+name: lytic exotransglycosylase activity
+namespace: molecular_function
+def: "Catalysis of the exolytic cleavage of the (1->4)-beta-glycosidic linkage between N-acetylmuramic acid (MurNAc) and N-acetylglucosamine (GlcNAc) residues in peptidoglycan, from either the reducing or the non-reducing ends of the peptidoglycan chains, with concomitant formation of a 1,6-anhydrobond in the MurNAc residue." [EC:4.2.2.n1]
+synonym: "murein lytic endotransglycosylase E activity" NARROW []
+xref: EC:4.2.2.n1 {source="skos:exactMatch"}
+is_a: GO:0008933 ! peptidoglycan lytic transglycosylase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21167" xsd:anyURI
+created_by: pg
+creation_date: 2025-02-05T12:50:17Z
