### ISSUE TITLE
wrong parent of GO:0046905 phytoene synthase activity

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21165]
```
id: GO:0046905
name: phytoene synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: prephytoene pyrophosphate = phytoene + diphosphate." [GOC:ai, PMID:12641468]
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
```
For reference, this is https://www.rhea-db.org/rhea/10916, part of a bifunctional enzyme that is EC:2.5.1.32. The first function of the enzyme is 'geranylgeranyl-diphosphate geranylgeranyltransferase activity ; GO:0016767' which is a transferase. Here however (see Rhea) the molecule is rearranged and diphosphate is cleaved from it. So this is at least a diphosphatase (GO:0016462) and probably an isomerase (GO:0016853) activity. The given reference PMID:12641468 characterizes the whole enzyme and has nothing about the second rearrangement step. I would like to add PMID: 24175570 which shows both steps.

**Comment by rwst** [comment]
Maybe the Rhea folks can give better parents for this entry?

**Comment by pgaudet** [comment]
@kaxelsen @amorgat

**Comment by pgaudet** [comment]
I wonder if this really is bifunctional, or if there are just two steps in the mechanism of the reaction. 
https://enzyme.expasy.org/EC/2.5.1.32 has synonym Phytoene synthetase

I think the intermediate is a cis product, shown here: https://en.wikipedia.org/wiki/Phytoene
and that there is an isomerization reaction that makes it all trans? 

If this is done by a single enzyme, do we want 2 reactions in GO?

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 

What is the difference between  RHEA:34475 and RHEA:22296
- RHEA:34475 links to EC:2.5.1.32, which has the same product,   15-cis-phytoene
- GO:0016767 geranylgeranyl-diphosphate geranylgeranyltransferase activity links to  EC:2.5.1.32 and RHEA:22296

I think there is some mix up somewhere. 

Thanks, Pascale

**Comment by pgaudet** [comment]
This is clearer: 
https://en.wikipedia.org/wiki/Phytoene_synthase
According to this wiki page, EC:2.5.1.32 represents the overall reaction: 

    2 geranylgeranyl diphosphate ⇌ {\displaystyle \rightleftharpoons } \rightleftharpoons 15-cis-phytoene + 2 diphosphate (overall reaction)
    (1a) 2 geranylgeranyl diphosphate ⇌ {\displaystyle \rightleftharpoons } \rightleftharpoons diphosphate + prephytoene diphosphate
    (1b) prephytoene diphosphate ⇌ {\displaystyle \rightleftharpoons } \rightleftharpoons 15-cis-phytoene + diphosphate

**Comment by rwst** [comment]
There may be spontaneous cis/trans isomerizations. I think that's why the GO entry talks about "phytoene" without specifying cis/trans configuration.

**Comment by pgaudet** [comment]
We have other examples of reactions that occur in more than 1 step, for eg GO:0035560, def: "Catalysis of the reaction: pheophorbide a + H2O = pyropheophorbide a + methanol + CO2. **The reaction occurs in two steps**; pheophoridase catalyzes the conversion of pheophorbide a to a precursor of pyropheophorbide a, C-13(2)-carboxylpyropheophorbide a, by demethylation, and then the precursor is decarboxylated non-enzymatically to yield pyropheophorbide a."

**Comment by kaxelsen** [comment]
Note that the definition of GO:0046905 is imprecise. RHEA;34479 results in 15-cis-phytoene (global reaction RHEA:34475) while RHEA:10916 results in all-trans-phytoene (global reaction RHEA:32451). Both reactions have RHEA;22296 as first step. RHEA:32451 is not linked to an EC number and is based on pmids: 12641468 and 7896759

**Comment by rwst** [comment]
Then better keep it as two steps?

**Comment by kaxelsen** [comment]
There are many reactions that occur in multiple steps. Unfortunately we do not have a part-of relationship for export, so we cannot show that the reactions are linked. Most of the multi-step reactions are based on EC numbers where there is an overall reaction and two or more steps as you show for EC 2.5.1.32 above. It is, by the way, easier to go to the source of the data instead of via wikipedia: https://www.enzyme-database.org/query.php?ec=2.5.1.32

**Comment by pgaudet** [comment]
Thanks ! I was using this link: https://enzyme.expasy.org/EC/2.5.1.32

**Comment by rwst** [comment]
What are RHEA;34479 and RHEA:10916, isomerizations?

**Comment by pgaudet** [comment]
> Note that the definition of GO:0046905 is imprecise. RHEA;34479 results in 15-cis-phytoene (overall reaction RHEA:34475) while RHEA:10916 results in all-trans-phytoene (overall reaction RHEA:32451). Both reactions have RHEA;22296 as first step. RHEA:32451 is not linked to an EC number and is based on pmids: 12641468 and 7896759

EC mentions specifically the cis isomer.

**Comment by pgaudet** [comment]
If cis/trans isomerizations are spintaneous, in GO we would not create the reaction.

**Comment by kaxelsen** [comment]
@rwst As you write yourself above, it is a diphosphatase, but some rearrangement happens at the epoxide group when the diphosphate is released.
@pgaudet ENZYME is also a good source for the data

**Comment by kaxelsen** [comment]
@pgaudet The products (15-cis or all-trans) are enzyme specific and linked to release of diphosphate so there is no spontaneous component here.

**Comment by pgaudet** [comment]
Does that mean we need 4 reactions ?

**Comment by kaxelsen** [comment]
No, only two. Release of diphosphate and rearrangement is one complex diphosphatase reaction.

**Comment by pgaudet** [comment]
Thanks @rwst !

**Comment by pgaudet** [comment]
Actually, one more question: There are 14 existing annotations - do you know if the product for those reactions is the cis or trans ? 

For example in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2259096/ I cannot see that information. 

Do we need the general term and the 2 children? Are those reactions catalyzed by the same enzyme?

**Comment by rwst** [comment]
As a curator I would not annotate this to the function, but the associated process. There is no enzyme characterization in that paper.

**Comment by kaxelsen** [comment]
There is at least one known protein from tomato that produces both (see pmid:7896759). It is currently not present in Swiss-Prot. Most known proteins produce the cis product.

**Comment by pgaudet** [comment]
OK, so it's probably safe to change the meaning of GO:0046905 phytoene synthase activity to the cis-product. BUT the papers I have looked at are not explicit about it. 

Here are the annotations https://docs.google.com/spreadsheets/d/1q-5kU98VLfvJycubuoUrfGOZyTf043ezVdU7GbcuneM/edit#gid=0

Most are by Damien and Ivo, I'll contact them to review. 

Thanks, Pascale

**Comment by dlieberherr** [comment]
@pgaudet

> OK, so it's probably safe to change the meaning of GO:0046905 phytoene synthase activity to the cis-product.

I think so, according to what I have seen in the publications of the plant entries annotated with GO:0046905 phytoene synthase activity.

They complement a bacterial mutant lacking crtB with the plant enzymes to produce 15-cis-phytoene.

If you look at CRTB_ENTAG (D5KXJ0) here are the comments:

CC FUNCTION: Involved in the biosynthesis of carotenoids. Catalyzes stereoselectively the condensation of two molecules of geranylgeranyl diphosphate (GGPP) to give prephytoene diphosphate (PPPP) and the subsequent rearrangement of the cyclopropylcarbinyl intermediate to yield 15-cis-phytoene. (PMID:12641468)

CC CAUTION: The enzyme produces 15-cis-phytoene. The conversion to all-trans-phytoene is due to photoisomerisation. (PMID:12641468)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140630
+name: all-trans-phytoene synthase activity
+def: "Catalysis of the reaction: 2 geranylgeranyl diphosphate -> all-trans-phytoene + 2 diphosphate." [PMID:12641468, PMID:7896759]
+synonym: "phytoene synthase activity" BROAD []
+is_a: GO:0016462 ! pyrophosphatase activity
+relationship: part_of GO:0016117 ! carotenoid biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21165 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-25T18:04:01Z
+
