### ISSUE TITLE
revise GO:0052034    suppression by symbiont of microbe-associated molecular pattern-induced host innate immune response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21161]
This term has a single annotation from PHi-BAse

GO:0052034    suppression by symbiont of microbe-associated molecular pattern-induced host innate immune response

as far as we know, PTI manipulation is necessarily effector-mediated, so until we find otherwise could this term be renamed

effector-mediated suppression of pattern-triggered immunity
and have
GO:0140423    effector-mediated suppression of pattern-triggered immunity signaling
as a child to follow newer pattern?

**Comment by pgaudet** [comment]
I will implement what you ask. I do have a question about the annotation though: 

The gene annotated by PHI-Base is  a polyketide synthase, right ? 
Doesn't it produce the effector, rather then being the effector ?

**Comment by pgaudet** [comment]
I also updated the definition of GO:0052034 
**from :** 
Any process that involves recognition of a microbe-associated molecular pattern, and by which a symbiont stops, prevents, or reduces the frequency, rate or extent of the innate immune response of the host organism; the innate immune response is the host's first line of defense against infection. The host is defined as the larger of the organisms involved in a symbiotic interaction.

**to:** 
A process mediated by a molecule secreted by a symbiont that results in the suppression of the innate immune response of the host organism via recognition of a microbe-associated molecular pattern. The innate immune response is the host's first line of defense against infection. The host is defined as the larger of the organisms involved in a symbiotic interaction.

**Comment by ValWood** [comment]
You are right. The annotated example is not effector-mediated.

So the term should stay as it is, and I would need
NTR effector-mediated suppression of pattern-triggered immunity

Sorry about that. I did not check the existing annotation.

**Comment by pgaudet** [comment]
But still the existing annotation is not correct even with the old term label - this would either use the relation 'acts upstream of', and/or simply be annotated to some x compound synthesis

**Comment by ValWood** [comment]
I'm not sure. The term we used eventually in this session was

GO:0052562 | suppression by symbiont of host immune response

to me that seems a pretty direct effect of producing the toxin (it is not produced for any other purpose).

The molecule is produced in response to the host  to suppress the immune system,. Otherwise there is no connection to any pathogen-host interaction?

**Comment by ValWood** [comment]
i.e there is nothing further downstream to annotate as we can't annotate the toxin?

**Comment by pgaudet** [comment]
maybe we need something along the lines of 'production of defense molecule'?

**Comment by ValWood** [comment]
Yes, that sounds useful.I wonder what PAthGO do with these ?
I can make it causally upstream if you think it should be, but I can't do that in Canto yet. (I have a list for PomBAse of about ~30 annotations that need moving to causally upstream.  it will be a few months until we get to this change.

**Comment by pgaudet** [comment]
Would 'GO:0009403 toxin biosynthetic process' work to annotate the polyketide synthase gene?

**Comment by ValWood** [comment]
I agree the annotation was incorrect. This is involved in multiple pathways.

Now has

GO:2001310 | gliotoxin biosynthetic process

**Comment by pgaudet** [comment]
@ValWood can we close this? I think it was open to review PhiBase annotations.

**Comment by ValWood** [comment]
I prresume so....
