### ISSUE TITLE
dihydropterin oxidase activity (GO:0004154) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21164]
From the EC xref on this:
[Term]
id: GO:0004154
name: dihydropterin oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: a 7,8-dihydropteridine + O2 = a pterin + hydrogen peroxide." [GOC:mah, PMID:1745247, PMID:6815189]
xref: EC:1.5.3.-
is_a: GO:0016491 ! oxidoreductase activity

it's parent should be changed to this:
[Term]
id: GO:0016645
name: oxidoreductase activity, acting on the CH-NH group of donors
namespace: molecular_function
def: "Catalysis of an oxidation-reduction (redox) reaction in which a CH-NH group acts as a hydrogen or electron donor and reduces a hydrogen or electron acceptor." [GOC:ai]
synonym: "oxidoreductase activity, acting on the CH-NH group of donors, other acceptors" NARROW []
xref: EC:1.5.-.-
is_a: GO:0016491 ! oxidoreductase activity

**Comment by hdrabkin** [comment]
will also remove 3 digit ec for 4154, as it is a grouping term.

**Comment by hdrabkin** [comment]
EC:1.5.3.- maps to GO:0016647  oxidoreductase activity, acting on the CH-NH group of donors, oxygen as acceptor, so I'll  use THAT as parent rather than : GO:0016645 name: oxidoreductase activity, acting on the CH-NH group of donors

**Comment by sjm41** [comment]
Thanks Harold.
