### ISSUE TITLE
canonical glycolysis  ancestry

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21176]
canonical glycolysis 
is a descendant of "GO:0046939	nucleotide phosphorylation"
which seems odd?

some  nucleotide phosphorylaton events are part_of glycolysis?

**Comment by deustp01** [comment]
Yes. ADP is phosphorylated to form ATP in the course of glycolysis, as shown in the screenshot from the [canonical glycolysis quickGO page](https://www.ebi.ac.uk/QuickGO/term/GO:0061621):

<img width="351" alt="Screen Shot 2021-03-23 at 12 33 15 PM" src="https://user-images.githubusercontent.com/12737623/112183094-4e6c9a80-8bd4-11eb-8a78-3174ac727deb.png">


@ukemi I think we decided there was no alternative to this, because ATP generation is a central feature of glycolysis?

**Comment by ValWood** [comment]
I would expect to see ancestry aligned with the process, but "nucleotide phosphorylation" is more like a MF that is part of the process? 

<img width="957" alt="Screen Shot 2021-03-23 at 17 15 17" src="https://user-images.githubusercontent.com/7359272/112188936-63105900-8bfb-11eb-98c8-4ef9e0027af9.png">

**Comment by ValWood** [comment]
Actually, It looks really strage to have a reaction (ATP generation from ADP) as a  parent of the entire pathway. @ukemi Does that model in Noctua OK?

**Comment by ValWood** [comment]
Should gluconeogenesis also have the parent 
'generation of precursor metabolites and energy'.?

**Comment by pgaudet** [comment]
This is a question for @ukemi and @deustp01 , but based on the definition of gluconeogenesis, "The formation of glucose _from_ noncarbohydrate precursors, such as pyruvate, amino acids and glycerol. " - I dont think so? 

Also, from the change log in QuickGO, it looks like gluconeogenesis was never is_a 'generation of precursor metabolites and energy'.

**Comment by pgaudet** [comment]
The def of 'generation of precursor metabolites' is "The chemical reactions and pathways resulting in the formation of precursor metabolites, substances from which energy is derived, and any process involved in the liberation of energy from these substances."

@ukemi @deustp01 can we have a list (even partial) of these precursor metabolites?

**Comment by deustp01** [comment]
> @ukemi  can we have a list (even partial) of these precursor metabolites?

The list, even a partial one, will be complicated, full of taxon constraints, and, unless also provided with tissue- and physiological-state- constraints, will be wildly misleading. For example, in green plants carbon dioxide, via photosynthesis, looks like a precursor. In healthy humans long chain fatty acids are precursors but mostly in the fasting state and never in red blood cells. And so on.

I think we need two preliminary discussions here. First, what are the use cases for such lists? If we find good ones, then a second one to find a strategy that real curators can apply to construct minimal lists that are accurate, maintainable, and responsive to the use cases.

And perhaps we also need to think of alternative approaches. For example, given a good set of GO-CAMs (not out of reach for eukaryotic energy metabolism), and really robust tools to identify "provides input for" relationships between activites both within a single GO-CAM / process / pathways and between them, the precursors fall out of the pathway annotations (including ones not expected per the textbooks that turn out to be real).

**Comment by ValWood** [comment]
GO:0006091  generation of precursor metabolites and energy
 has always been a bit of a problem term. Its a bit of a fudge to groups terms related to energy generation for enrichment and slimming  (many of which would not slim elsewhere). These include glycolysis, TCA cycle, respiratory chain, photosynthesis. The current children are below:


I have always been a bit confused by the "generation of precursor metabolites"  
part of the  term label (although the def does seem to restrict to "energy generation")

The chemical reactions and pathways resulting in the formation of precursor metabolites, substances from which energy is derived, and any process involved in the liberation of energy from these substances.

Although the term is clunky, it does seem to work as an "annotation bin" to collect  together energy generating processes.



GO:0015980    energy derivation by oxidation of organic compounds | is_a
-- | --
GO:0009765    photosynthesis, light harvesting | is_a
GO:0006069    ethanol oxidation | is_a
GO:0006740    NADPH regeneration | is_a
GO:0019684    photosynthesis, light reaction | is_a
GO:0061719    glucose catabolic process to pyruvate utilizing ADP | is_a
GO:0015975    energy derivation by oxidation of reduced inorganic compounds | is_a
GO:0009052    pentose-phosphate shunt, non-oxidative branch | is_a
GO:1902224    ketone body metabolic process | is_a
GO:0022900    electron transport chain | is_a
GO:0043467    regulation of generation of precursor metabolites and energy | regulates
GO:0061722    sulphoglycolysis

[GO:0015980](https://www.ebi.ac.uk/QuickGO/term/GO:0015980)    energy derivation by oxidation of organic compounds	is_a
[GO:0009765](https://www.ebi.ac.uk/QuickGO/term/GO:0009765)    photosynthesis, light harvesting	is_a
[GO:0006069](https://www.ebi.ac.uk/QuickGO/term/GO:0006069)    ethanol oxidation	is_a
[GO:0006740](https://www.ebi.ac.uk/QuickGO/term/GO:0006740)    NADPH regeneration	is_a
[GO:0019684](https://www.ebi.ac.uk/QuickGO/term/GO:0019684)    photosynthesis, light reaction	is_a
[GO:0061719](https://www.ebi.ac.uk/QuickGO/term/GO:0061719)    glucose catabolic process to pyruvate utilizing ADP	is_a
[GO:0015975](https://www.ebi.ac.uk/QuickGO/term/GO:0015975)    energy derivation by oxidation of reduced inorganic compounds	is_a
[GO:0009052](https://www.ebi.ac.uk/QuickGO/term/GO:0009052)    pentose-phosphate shunt, non-oxidative branch	is_a
[GO:1902224](https://www.ebi.ac.uk/QuickGO/term/GO:1902224)    ketone body metabolic process	is_a
[GO:0022900](https://www.ebi.ac.uk/QuickGO/term/GO:0022900)    electron transport chain	is_a
[GO:0043467](https://www.ebi.ac.uk/QuickGO/term/GO:0043467)    regulation of generation of precursor metabolites and energy	regulates
[GO:0061722](https://www.ebi.ac.uk/QuickGO/term/GO:0061722)    sulphoglycolysis
