### ISSUE TITLE
NTR: Child Term for GO:0016286 "small conductance calcium-activated potassium channel activity"

### ISSUE THREAD

**Issue by Kawatebi** [geneontology/go-ontology#21175]
Hello,

I would like to request a Child Term for GO:0016286 -  "negative regulation of small conductance calcium-activated potassium channel activity" based on PMID:  20562108.

The authors report, the inhibition of small conductance calcium-activated potassium channels by the venom toxin apamin (Figure 1). 

Definition:

Any process that stops, prevents or reduces the frequency, rate or extent of small conductance calcium-activated potassium channel activity.

Let me know if you require any more information.

Many thanks,

Kate

**Comment by pgaudet** [comment]
Hi @Kawatebi 

Does it work for you if we create "small conductance calcium-activated potassium channel inhibitor activity", similar to what we did in #21157 ? 

Thanks, Pascale

**Comment by Kawatebi** [comment]
@pgaudet 

Yes that would work. 

Many thanks, Kate

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140629
+name: small conductance calcium-activated potassium channel inhibitor activity
+namespace: molecular_function
+def: "Binds to and stops, prevents, or reduces the activity of a small conductance calcium-activated potassium channel." [PMID:20562108]
+intersection_of: GO:0098772 ! molecular function regulator
+intersection_of: negatively_regulates GO:0016286 ! small conductance calcium-activated potassium channel activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21175 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-25T09:53:57Z
