### ISSUE TITLE
Does 'regulation of MF' always result in 'regulation of BP'?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#21181]
This question came up on the GO-CAM office hours call today 

There are asserted relationships in the ontology between some 'regulation of MF' terms and a corresponding 'regulation of BP'.

If, in GO-CAMs and our standard annotations, we model MFs like 'DNA-binding transcription factor activity' as regulating the MF of the gene product resulting from transcription of a target gene, then in some cases we also get an annotation to a corresponding 'regulation of BP' when there is an is_a relation between the two regulation terms asserted in the ontology.  

So,  for example, DNA-binding transcription factor activity might positively regulate a transporter activity and, via the assertion in the ontology, that would be a 'positive regulation of transport'.  

Does this hold for all regulation of MF terms and do we want these BP assertions for things like transcription factors and miRNAs that regulate gene expression?

@RLovering @thomaspd @ukemi @pgaudet

**Comment by pgaudet** [comment]
Sounds right
