### ISSUE TITLE
Ubiquitin-dependent protein catabolic process via the destruction via C-end degron rule pathway

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#21184]
Hi GO,

I would need a new GO term for the C-end degron rule (DesCEND ) pathway, an equivalent of the N-end rule pathway but for the C-terminus of proteins

Thanks

Sylvain

Name: ubiquitin-dependent protein catabolic process via the destruction via C-end degron rule pathway
Synonym: DesCEND (exact)
Category: Biological Process
Definition: The chemical reactions and pathways resulting in the breakdown of a protein or peptide covalently tagged with ubiquitin, via the DesCEND (destruction via C-end degron) pathway. In the DesCEND pathway, C-terminal residues (C-end degrons) in substrates are recognized by Cul2-RING and Cul4-RING E3 ligases, whereupon the substrates are linked to ubiquitin and then delivered to the proteasome for degradation. C-end degrons can be present in full-length proteins, truncated proteins or proteolytically cleaved forms.

PMID:29779948
PMID:29775578

Child of GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process

**Comment by pgaudet** [comment]
Are you sure we need 2 'via' in the term name? 
how about just 'ubiquitin-dependent protein catabolic process via the C-end degron rule pathway', to model on the N-rule term?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140627
+name: ubiquitin-dependent protein catabolic process via the C-end degron rule pathway
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the breakdown of a protein or peptide covalently tagged with ubiquitin, via the DesCEND (destruction via C-end degron) pathway. In the DesCEND pathway, C-terminal residues (C-end degrons) in substrates are recognized by Cul2-RING and Cul4-RING E3 ligases, whereupon the substrates are linked to ubiquitin and then delivered to the proteasome for degradation. C-end degrons can be present in full-length proteins, truncated proteins or proteolytically cleaved forms." [PMID:29775578, PMID:29779948]
+synonym: "DesCEND" EXACT []
+is_a: GO:0043161 ! proteasome-mediated ubiquitin-dependent protein catabolic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21184 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-24T07:30:47Z

**Comment by sylvainpoux** [comment]
Hi Pascale
thanks for correcting the name
Cheers
Sylvain
