### ISSUE TITLE
NTR: fluorescent chlorophyll catabolite monooxygenase (deformylase)

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#21196]
GO new: fluorescent chlorophyll catabolite monooxygenase (deformylase)
definition: catalyzes the conversion of fluorescent chlorophyll catabolites to fluorescent dioxobilin-type chlorophyll catabolites
parent: GO:0016709
reference:PMID:23723324

consulted with Peifen Zhang on this one.

**Comment by pgaudet** [comment]
Hi @lreiser Is there an EC and/or a RHEA for this reaction?

**Comment by lreiser** [comment]
Checking based on the substrate....
I see
https://biocyc.org/compound?orgid=META&id=CPD-7064#tab=RXNS

and 
https://www.rhea-db.org/rhea/?query=chebi:77670
so I think not.

**Comment by hdrabkin** [comment]
Great; those links help because I really need to get a better def. and these point me in the right direction to figure out CHEBI IDS for substrates/products so I can request a RHEA for the reaction you request.

**Comment by hdrabkin** [comment]
CHEBI:77670 looks like the product of the reaction.  based on fig 1 
CHEBI:58719  looks like the substrate 
Note the loss of the double bond from 58719 to 77670

**Comment by hdrabkin** [comment]
I have written CHEBI as well as RHEA; the CHEBI structures are confusing in that going from the ionized form or one to it's conjugate, gains a methyl group, AND the 2- form's image appears to only have 1-.

**Comment by lreiser** [comment]
Thanks Harold
TBH I did not compare the structures in the paper exactly. ;)

**Comment by hdrabkin** [comment]
Also note that in the paper, there is a CH3 group on the lower right hands carboxylic acid group, which makes this different from https://biocyc.org/compound?orgid=META&id=CPD-7064#tab=RXNS (no methyl group ). 
Have contacted @amorgat via email (lengthy) for advise here.

**Comment by kaxelsen** [comment]
RCC = Red Chlorophyll Catabolite = CHEBI:58716
pFCC = primary Fluorescent Chlorophyll Catabolite = CHEBI:77670
RCCR = EC 1.3.7.12 = RHEA:24752
pFDCC = primary Fluorescent Dioxobilin-type Chlorophyll Catabolite = Not yet in ChEBI (or MetaCyc)
CYP89A9 = Not yet in Rhea (or MetaCyc)

**Comment by kaxelsen** [comment]
I have now created a reaction for the deformylase reaction catalysed by CYP89A9
RHEA;RHEA:67172 O2 + primary fluorescent chlorophyll catabolite + reduced [NADPH--hemoprotein reductase] = formate + 2 H+ + oxidized [NADPH--hemoprotein reductase] + primary fluorescent dioxobilin-type chlorophyll catabolite
primary fluorescent chlorophyll catabolite = pFCC = CHEBI:77670
primary fluorescent dioxobilin-type chlorophyll catabolite = pFDCC = CHEBI:167885

In pmid:23723324 they also discuss the MES16 methylesterase reaction. I have also created a reaction for this activity.
RHEA:67176 H2O + primary fluorescent dioxobilin-type chlorophyll catabolite = H+ + methanol + O13(4)-desmethyl pFCC
O13(4)-desmethyl pFCC = CHEBI:167889

**Comment by hdrabkin** [comment]
Thanks @kaxelsen ; I can use the text from the RHEA to at least create the term (Catalysis of the reaction so I can be used in annotation while we wait for the ids to become putlic

**Comment by kaxelsen** [comment]
Unfortunately, we have just had a freeze, so these reactions will only become public in release 2021_03 scheduled for June 2

**Comment by hdrabkin** [comment]
So @lreiser : you new term will look like this:
id: GO new
term:: fluorescent chlorophyll catabolite monooxygenase (deformylase)
definition: Catalysis of the reaction: O2 + primary fluorescent chlorophyll catabolite + reduced [NADPH--hemoprotein reductase] = formate + 2 H+ + oxidized [NADPH--hemoprotein reductase] + primary fluorescent dioxobilin-type chlorophyll catabolite.
parent: GO:0016709
reference:PMID:23723324
reference:RHEA:67172  (to be added when released).

+[Term]
+id: GO:0106371
+name: fluorescent chlorophyll catabolite monooxygenase (deformylase) activity

Second term 
+[Term]
+id: GO:0106372
+name: primary fluorescent dioxobilin-type chlorophyll catabolite methylesterase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: H2O + primary fluorescent dioxobilin-type chlorophyll catabolite = H+ + methanol + O13(4)-desmethyl pFCC." [PMID:23723324]
+is_a: GO:0052689 ! carboxylic ester hydrolase activity

**Comment by lreiser** [comment]
awesome, thank you..
