### ISSUE TITLE
Two concepts connected by multiple relations

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#21194]
Hello,
I noticed the following issue among two GO concepts- GO:0000919 and GO:0022402. Kindly check the hierarchy from the link below.
https://www.ebi.ac.uk/QuickGO/term/GO:0000919

It seems that these two concepts are connected by both is-a and part-of relations as follows.

It can be inferred that GO:0000919 part-of GO:0022402 by the following:
GO:0000919 part-of GO:0000911 is-a GO:0000910 is-a GO:0022402

This is based on the reasoning rules mentioned in: http://geneontology.org/docs/ontology-relations/

It can be also observed that GO:0000919 is-a GO:0022402

Is this accurate? Can two concepts be connected by such multiple relations?

**Comment by pgaudet** [comment]
Hello @rashmie 

Yes, GO has multiple inheritance. See some documentation here: http://geneontology.org/docs/ontology-documentation/

Thanks, Pascale

**Comment by rashmie** [comment]
Hello @pgaudet 

Thanks for the quick response. I apologize if I wasn't clear earlier. But, the issue I mentioned is not about multiple inheritance. In the example that I provided, GO:0000919 is both a child of and a part of GO:0022402. I feel like a concept being both a child and a part of another concept is not correct. Could you please clarify?

**Comment by balhoff** [comment]
> I feel like a concept being both a child and a part of another concept is not correct. Could you please clarify?

There is no technical problem with this, in fact it's quite common. As an outside example, think of Carnivore, which you could model as:

- Carnivore is_a Animal
- Carnivore eats Animal

If you want to take into account carnivorous plants, then it just pushes the inference farther back:

- Carnivore is_a Organism
- Carnivore eats Animal (which implies 'Carnivore eats Organism' via 'Animal is_a Organism')

**Comment by rashmie** [comment]
Hi @balhoff,
Thank you for the explanation and the nice example. It indeed makes sense.
