### ISSUE TITLE
Odd parent - child relationships for transporter MF terms

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#21210]
GO:0015424 ABC-type amino acid transporter activity and GO:0022857 transmembrane transporter activity are siblings, both is_a children of GO:0005215 transporter activity. That’s already odd because ABC-type transporters are transmembrane transporters. The oddity is compounded because GO:0072349 modified amino acid transmembrane transporter activity is_a transmembrane transporter activity.
@ukemi

**Comment by ukemi** [comment]
Logical def should change from:
'transporter activity'
 and ('transports or maintains localization of' some 'amino acid')

to:
'ABC-type transporter activity'
 and ('transports or maintains localization of' some 'amino acid')

**Comment by pgaudet** [comment]
Thanks for reporting this.
