### ISSUE TITLE
 Missing parent GO:0062209 	 spatial regulation of meiotic DNA double-strand break formation involved in reciprocal meiotic recombination 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21215]
| GO:0062209 | spatial regulation of meiotic DNA double-strand break formation involved in reciprocal meiotic recombination

is missing the correct parents to slim to
DNA recombination (GO:0006310)

**Comment by pgaudet** [comment]
Added missing relation to parent: GO:1905261 regulation of meiotic DNA double-strand break formation involved in reciprocal meiotic recombination
 intersection_of: GO:0065007 ! biological regulation
 intersection_of: regulates GO:0010780 ! meiotic DNA double-strand break formation involved in reciprocal meiotic recombination
+relationship: part_of GO:0007131 ! reciprocal meiotic recombination

**Comment by mah11** [comment]
Hmm, I thought the relation we wanted was `regulates` ... that's what used to be inferred back when the `regulates` relations were treated as transitive over `part_of`. But either would restore the slim results Val wants.

**Comment by mah11** [comment]
... and it makes sense biologically: regulating DSB formation regulates the overall recombination process
