### ISSUE TITLE
parentage: `chromosome segregation`

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#21228]
It seems odd that `chromosome separation (GO:0051304)` has these SubClass Of relationships:
* is_a `cell cycle process`
* 'part of' some 'chromosome segregation'

While `chromosome segregation (GO:0007059)` only has this SubClass Of relationship:
* is_a `cellular process` 

I would think that `chromosome segregation` should also be is_a `cell cycle process`

@ValWood - any thoughts here?

**Comment by ValWood** [comment]
I'm not sure. I wonder if historically  it is something to do with mitochondrial and or chloroplast chromosome not being  a cell cycle process? But we do not have terms for these - and as far as we know there is no "mitochondrial chromosome segregation" machinery. They just replicate and sort randomly (the mechanism for  partitioning appears to make more smaller mitochondria  (increase fission to maximise the chances of mitochondria  with multiple genomes in each cell). So I think this parent can probably be added unless anyone can think of another reason why not?

**Comment by pgaudet** [comment]
If this is the case, chromosome separation would not be a cell cycle process either?

**Comment by ValWood** [comment]
"separation" was OK. The separation part refers to the degradation of the cohesin. I think  bacterial, mitochondrial and chloroplast DNA just separate on replication?

I don't think there is any active separation of non-nuclear chromosomes?

If separation has be used maybe it should be segregation? I'm not sure. I don't really know anything about bacterial chromosome segregation....

**Comment by krchristie** [comment]
> "separation" was OK. The separation part refers to the degradation of the cohesin. I think bacterial, mitochondrial and chloroplast DNA just separate on replication?
> 
> I don't think there is any active separation of non-nuclear chromosomes?

Mitochondrial chromosomes are retained within the mitochondrion. I have no idea whether the replication of mitochondrial chromosomes is timed with respect to the cell cycle, but my understanding is that each mitochondrion has many copies of the circular mitochondrial chromosome. It seems to me that the cell cycle process relevant to mitochondria is the fissioning of large mitochondria to have larger numbers of smaller mitochondria, so that each daughter cell gets some mitochondria


> If separation has be used maybe it should be segregation? I'm not sure. I don't really know anything about bacterial chromosome segregation....

I'll think about this some more...

**Comment by pgaudet** [comment]
This paper suggests that mitochondrial DNA division (and replication) is coordinated with the cell cycle: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4250044/

**Comment by ValWood** [comment]
Well that is true, before division  the mitochondria undergo fission so there are a larger number of smaller mitochondria.

But if we followed this then almost everything in yeast is a cell cycle process. .....

However, I don't think we need to worry about the mitochondrial connection to chromosome segregation. No such term exists for "mitochondrial chromosome segregation" or  DNA inheritance:
https://github.com/geneontology/go-ontology/issues/18417

There is no special segregation machinery (as far as we know)

**Comment by pgaudet** [comment]
Indeed there are bacterial annotations to 'chromosome segregation' - but still that could be a 'cell cycle process', unless @ValWood  you think that this is limited to eukaryotes? Nothing in the definition states that: 
    GO:0022402  cell cycle process 
   The cellular process that ensures successive accurate and complete genome replication and chromosome segregation. Source: GOC:isa_complete, GOC:mtg_cell_cycle

Also, there are no taxon constraints on 'cell cycle process'. 

Bacterial cell cycle is used in the literature: 
PMID:31164753, PMID:28094092, etc (18k results in PubMed). 

So I dont see why we should no put 'chromosome segregation' is_a 'cell cycle process.

**Comment by ValWood** [comment]
agreed.

**Comment by pgaudet** [comment]
Great! 

To summarize: action is to add a new subclass, cell cycle process, to  'GO:0007059 chromosome segregation'

**Comment by ValWood** [comment]
add superclass?

**Comment by pgaudet** [comment]
- a 'child' term is a subclass of a 'parent' 
- a 'parent' is a 'superclass' of a 'child'

**Comment by ValWood** [comment]
To summarize: action is to add a new ~subclass~ superclass, cell cycle process, to 'GO:0007059

**Comment by edwong57** [comment]
From all the other comments, it sounds like GO:007059 is a subclass of 'cell cycle process', like chromosome separation (GO:0051304), not a superclass. 'cell cycle process' is_a superclass of chromosome segregation, so 'chromosome segregation' is_a subclass of 'cell cycle process'
