### ISSUE TITLE
New function of catalyzing retro-aldol activities

### ISSUE THREAD

**Issue by YueCao94** [geneontology/go-ontology#21229]
Dear GO developers,

We notice a new  function described in those papers: [1](https://science.sciencemag.org/content/319/5868/1387), [2](https://onlinelibrary.wiley.com/doi/full/10.1002/pro.2059), [3](https://www.nature.com/articles/nchem.2596) about catalyzing retro-aldol activities.  The function is very specific about the catalysis of  retroaldol reaction of methodol (shown in Fig2(A) in [1](https://science.sciencemag.org/content/319/5868/1387)).

We believe that this function is not included in the current GO Ontology.  Our current understanding is that it should be under term "aldehyde-lyase activity" (GO:0016832).  

We would like to know whether the function is actually not in the current GO and if not,  whether it will be added in the future. Thanks!

**Comment by pgaudet** [comment]
@YueCao94

Is this an activity that occurs physiologically? 

Is there EC and/or RHEA reactions for this activity? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Hi @YueCao94 
Do you have a proposed definition. Is the reaction depicted in figure 1 of 'Report
De Novo Computational Design of Retro-Aldol Enzymes'?  If so I can draw the structures into CHEBI to see if they have CHEBI ids, and with those, see if RHEA has anything.

**Comment by pgaudet** [comment]
@amorgat Would you include this type of enzyme in RHEA?

**Comment by amorgat** [comment]
hum, quick look at the first paper seems to show that the authors describe activities of **designed** enzymes... I understand the interest, but IMHO we already have so much to do with the  'physiological' ones ;-)
Need to discuss with @alanbridge , @kaxelsen

**Comment by hdrabkin** [comment]
Me too.

**Comment by pgaudet** [comment]
OK, let's close this for now. 

@YueCao94 We discussed this at the ontology editors call today. GO captures physiological reactions, we will not create this term. 

Thanks, Pascale
