### ISSUE TITLE
GO:0051235   maintenance of location parentage query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21220]
GO:0051235   maintenance of location

is a "regulation of a biological quality"

That doesn't seem right, but I don't know what.

For example, is an adfapror which maintains a protein/ complex or organelle at a specific location a  "regulation"

**Comment by ValWood** [comment]
I don't see how it fits

"Any process that modulates a qualitative or quantitative trait of a biological quality. A biological quality is a measurable attribute of an organism or part of an organism, such as size, mass, shape, color, etc."

What is the measureable attribute?

**Comment by pgaudet** [comment]
Right. The  "regulation of a biological quality" branch is a little odd anyway. With @thomaspd and @cmungall we have started to reorganize/remove some classes under it. 


Thanks, Pascale
