### ISSUE TITLE
GO:0045182    translation regulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21223]
GO:0045182    translation regulator activity

is not is_a molecular function regulator. 

Is that intentional?

**Comment by pgaudet** [comment]
yes it is. This is defined as a function that regulates a process, not a MF, so it's not a MF regulator. 

This branch needs to be revised (there are open tickets already), maybe we can pinpoint the function of translation regulators better when we look into that.
OK to close?

**Comment by ValWood** [comment]
OK
