### ISSUE TITLE
EC xref for GO:0015419 ABC-type sulfate transporter activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21236]
The EC xref on the following term should be EC:7.3.2.3

[Term]
id: GO:0015419
name: ABC-type sulfate transporter activity
namespace: molecular_function
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + sulfate(out) = ADP + phosphate + sulfate(in)." [RHEA:10192]
synonym: "ATPase-coupled sulfate transmembrane transporter activity" RELATED []
synonym: "sulfate ABC transporter" EXACT []
synonym: "sulfate transmembrane-transporting ATPase activity" RELATED []
synonym: "sulfate-transporting ATPase activity" RELATED [EC:7.3.2.3]
synonym: "sulfate/thiosulfate porter activity" BROAD []
synonym: "sulphate transporting ATPase activity" RELATED []
xref: EC:3.6.3.25
xref: MetaCyc:3.6.3.25-RXN
xref: RHEA:10192
is_a: GO:0015116 ! sulfate transmembrane transporter activity
is_a: GO:0043225 ! ATPase-coupled inorganic anion transmembrane transporter activity
is_a: GO:0140359 ! ABC-type transporter activity

**Comment by deustp01** [comment]
I think that EC recently (within the past 6 months) created a new category EC 7.- to house translocases, activities that mediate active transport, and re-classified a number of terms previously housed in various other EC categories. This looks like one of thenre-classified terms. It occurs to me, purely as a managerial time-efficiency issue, that finding and fixing such terms one at a time is terribly wasteful, and that some sort of scripted global fix is needed. @hdrabkin @cmungall

**Comment by sjm41** [comment]
HI @deustp01  The vast majority have been fixed - I'm guessing this odd one got left behind somehow...

**Comment by hdrabkin** [comment]
I'll fix this one now since We know about it. Fortunately, the RHEA is also remapped and is for the sulfate ion.

**Comment by hdrabkin** [comment]
done. We'd need a list of all the ones that did get re-mapped, what they got remapped to, and access any RHEA changes needed.

**Comment by sjm41** [comment]
I thought the bulk xrefs transfer/match-up were handled in #15712 and #17127?

**Comment by hdrabkin** [comment]
I was pressed to undo #17127 (read details.) and #15712 was closed without comment (not by me). I was lead to believe that @pgaudet took on the transporters...

**Comment by sjm41** [comment]
I'll note that **all** EC:3.6.3.- numbers were transferred to EC:7 (https://enzyme.expasy.org/EC/3.6.3.-), and the one noted above (EC:3.6.3.25) is the only one left in GO as a current xref. (So that's good!)

**Comment by pgaudet** [comment]
Is there anything that remains to be done here ? 

We reverted  #15712, ie the creation of a new term, translocase, because in GO that was equivalent to GO:0005215 transporter activity. But ECs can be added to any transporter as appropriate.

**Comment by hdrabkin** [comment]
Not that I know of.
