### ISSUE TITLE
Remove EC xref from GO:0008796 bis(5'-nucleosyl)-tetraphosphatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21231]
Can you remove the EC:3.6.1.- xref from the following term (that EC is a grouping ID for Hydrolases -> Acting on acid anhydrides -> In phosphorus-containing anhydrides (https://enzyme.expasy.org/EC/3.6.1.-) and is already correctly on GO:0016818)

[Term]
id: GO:0008796
name: bis(5'-nucleosyl)-tetraphosphatase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of P(1),P(4)-bis(5'-nucleosyl)tetraphosphate into two nucleotides." [GOC:ai]
xref: EC:3.6.1.-
is_a: GO:0004551 ! nucleotide diphosphatase activity

**Comment by hdrabkin** [comment]
So how didn't see this one. Will remove now.

**Comment by sjm41** [comment]
Thanks.
