### ISSUE TITLE
'nucleoside phosphate catabolic process' should not be a subclass of 'nucleobase-containing small molecule biosynthetic process'

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#21245]
I'm not sure why this is asserted, but it leads to weird inferences when adding participants to processes. For example if I add allantoin as a primary output of IMP catabolic process, it infers that the process is an allantion biosynthetic process.

**Comment by pgaudet** [comment]
This was generally mentioned here #19775 
We probably have more cases like that.
