### ISSUE TITLE
protein complex with Rhea xref

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21246]
[ribosomal-protein-alanine N-acetyltransferase complex](http://purl.obolibrary.org/obo/GO_0009323) has an xref to RHEA:43752.

**Comment by hdrabkin** [comment]
I don't think we should have an RHEAs on anything other than MF activities

**Comment by hdrabkin** [comment]
removed

**Comment by hdrabkin** [comment]
So the EC comes up for both an activity AND a complex. both of which also use the same EC:2.3.1.128
GO:0008999 
GO:0009323
 Removed from complex
BUT, EC however, has been re-assigned, so am replaces this.
ENZYME entry: EC 2.3.1.128 Transferred entry: 2.3.1.267
RHEA has no reaction mapping to ec:2.3.1.267

However, the activity already GO:0008999  had
RHEA:43756  associated with EC 2.3.1.266 
EC 2.3.1.266 [Ribosomal protein S18]-alanine N-acetyltransferase
Ribosomal protein S5]-alanine N-acetyltransferase. "Acetyl-CoA + an N-terminal L-alanyl-[S5 protein of 30S ribosome] <=> CoA + an N-terminal N-acetyl-L-alanyl-[S5 protein of 30S ribosome]"

RHEA:43752
EC 2.3.1.267 [Ribosomal protein S5]-alanine N-acetyltransferase

So in these cases there are separate RHEAs AND ECs: depending upon the substrate (on is S5, the other is S18
Unclear if the same complex does both reactions. If it does we coud put two ECs on the complex, which does not specifiy target substrate. 
 The GO activity term does not specify the position, so I could easily make two children using the RHEAs, and a PMID or wiki for the general term. 
For the time being I have removed both rheas for the activity terms and will save that change while I hunt down proper references. I cannot find ANY evidence at the moment for the existence of the complex. There are crystal structures; their references do not mention a complex other than with CoA /acetyl-Coa

**Comment by hdrabkin** [comment]
More info
Checking in Amigo
 GO:0009323  ribosomal-protein-alanine N-acetyltransferase complex appears to have NO annotation. 
Suggest obsoletion.

**Comment by balhoff** [comment]
@pgaudet I think this will give you the info: https://api.triplydb.com/s/Ap2SDOlvS

**Comment by pgaudet** [comment]
- [ ] 0009339	EC:1.1.3.15
 - [ ] 0009331	EC:1.1.5.3
 - [ ] 0009375	EC:1.12.7.2
 - [ ] 0009326	EC:1.17.1.9
 - [ ] 0016612	EC:1.18.6.1
 - [ ] 0016613	EC:1.18.6.1
 - [ ] 0016610	EC:1.18.6.1
 - [ ] 0016611	EC:1.18.6.1
 - [ ] 0017086	EC:1.2.4.4
 - [ ] 0009342	EC:1.4.1.13
 - [ ] 0009325	EC:1.7.99.4
 - [ ] 0009348	EC:2.1.3.3
 - [ ] 0017059	EC:2.3.1.50
 - [ ] 0000148	EC:2.4.1.34
 - [ ] 0048269	EC:2.5.1.6
 - [ ] 0009349	EC:2.5.1.9
 - [ ] 0005969	EC:2.6.1.51
 - [ ] 0009357	EC:2.7.1.69
 - [ ] 0005952	EC:2.7.11.11
 - [ ] 0005954	EC:2.7.11.17
 - [ ] 0005964	EC:2.7.11.19
 - [ ] 0009336	EC:2.7.7.4
 - [ ] 0009338	EC:3.1.11.5
 - [ ] 0009318	EC:3.1.11.6
 - [ ] 0005966	EC:3.1.4.-
 - [ ] 0016465	EC:3.6.4.9
 - [ ] 0005950	EC:4.1.3.27
 - [ ] 0009333	EC:4.2.99.8
 - [ ] 0009350	EC:4.3.1.7
 - [ ] 0009345	EC:6.1.1.14
 - [ ] 0009332	EC:6.1.1.17
 - [ ] 0009328	EC:6.1.1.20
 - [ ] 0017109	EC:6.3.2.2
 - [ ] 0009343	EC:6.3.4.14
 - [ ] 0005744	EC:7.4.2.3

**Comment by hdrabkin** [comment]
So I think these need to be removed as xrefs for complexes.

**Comment by pgaudet** [comment]
Yes, I'm trying to replace by a reference if possible

**Comment by pgaudet** [comment]
- [ ] obsolete GO:0005966 EC:3.1.4.-
No annotations, no evidence that this is a complex, see https://www.uniprot.org/uniprot/P0A8G9

**Comment by sjm41** [comment]
@pgaudet will you be obsoleting GO:0005966 as per comment above?
If not, can you remove the partial EC xref from the definition line?

[Term]
id: GO:0005966
name: cyclic-nucleotide phosphodiesterase complex
namespace: cellular_component
def: "An enzyme complex that catalyzes the hydrolysis of bonds in a cyclic nucleotide." [EC:3.1.4.-]
synonym: "photoreceptor cyclic-nucleotide phosphodiesterase complex" NARROW []
is_a: GO:1902494 ! catalytic complex

**Comment by pgaudet** [comment]
* GO:0005966 cyclic-nucleotide phosphodiesterase complex >> no annotations
* GO:0009348 ornithine carbamoyltransferase complex  >> no annotations -> homotrimer 
* GO:0009343  biotin carboxylase complex >> 2 ISM annotations by GeneDB -> homodimer https://www.uniprot.org/uniprotkb/Q00955/entry#subcellular_location
