### ISSUE TITLE
GO:0019207   kinase regulator activity parentage query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21255]
GO:0019207   kinase regulator activity
Definition (GO:0019207 GONUTS page)
Modulates the activity of a kinase, an enzyme which catalyzes of the transfer of a phosphate group, usually from ATP, to a substrate molecule.

2021-02-17 | Deleted | RELATION | is a GO:0030234 (enzyme regulator activity)

This term is for kinase regulators like cyclins? What is the history of the relationship change?

**Comment by pgaudet** [comment]
right ! I cannot find it... must be some mistake (I looked for that for the phosphtase regulator ticket)

**Comment by pgaudet** [comment]
It  may have been caused by #20854

**Comment by ValWood** [comment]
Somewhere there is a ticket about those terms like
GO:0019912 cyclin-dependent protein kinase activating kinase activity
which are currently descendants of 'protein kinase regulator'. These (GO:0019912) are kinases that phosphorylate kinases.
I think the decision was that these would merge up into the kinase term, and no longer be classed as 'regulators" because they are not constitutive 'regulatory subunits'

**Comment by pgaudet** [comment]
The ticket you are looking for is here: #20884 - let's continue the discussion there

**Comment by pgaudet** [comment]
Fixed
