### ISSUE TITLE
NTR: cellular response to free heme

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21264]
Hello, I would like to request:

Name: cellular response to free heme
Definition: Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of free heme accumulating outside the cell, usually after hemolysis in vertebrates.
Ref: PMID 26741528, 32983129
Parent: GO:0033554 Cellular response to stress

This request is for Reactome, as the other children of Cellular response to stress GO:0033554 do not fit this pathway:
https://reactome.org/PathwayBrowser/#/R-HSA-9707616&PATH=R-HSA-8953897,R-HSA-2262752

Quote:
Extracellular hemoglobin, a byproduct of hemolysis, can release its prosthetic heme groups upon oxidation. Blood plasma contains proteins that scavenge heme. It is estimated that about 2–8% of the heme released in plasma becomes ‘bioavailable’, being internalized by bystander cells. If the heme degradation capacity of a cell, represented by heme oxidase 1 and 2, cannot be ramped up sufficiently then heme signaling and reactivity puts cells under stress. Platelets are activated by heme, and macrophages switch to the inflammatory type (Donegan et al, 2019; Gouveia et al, 2019).

Free (labile) heme accumulates in the blood stream in great amounts under pathological conditions like viral infections and malaria, but also ARDS amd COPD. The locally affected cells' primary reaction is to upregulate heme oxidase 1 (HMOX1) expression. HMOX1 induction in these cells not only removes heme from circulation but also triggers a functional switch toward the anti-inflammatory phenotype (Vijayan et al, 2018). However, heme scavenging and degradation systems may get overwhelmed by the sheer amount of heme present.

Heme promotes platelet activation, complement activation, vasculitis, and thrombosis (Bourne et al, 2020; Merle et al, 2018). Heme was recognized to act as a danger signal, damage-associated molecular pattern (DAMP), or alarmin (Soares and Bozza, 2016) and was shown to activate Toll-like receptor 4 (TLR4) signaling (Figueiredo et al, 2007; Janciauskiene et al, 2020). It also has a role as corepressor in the circadian clock system (Ko and Takahashi, 2006). BACH1 is regulated by heme in a cell, thus placing heme as a signaling molecule in gene expression in higher eukaryotes. The regulation of BACH1 by heme may be important for the stress response in general (Suzuki et al, 2004).

**Comment by raymond91125** [comment]
@rwst Is it OK to generalize beyond vertebrates? e.g.
PMID: 18720983 Heme transport and detoxification in nematodes: subproteomics evidence of differential role of glutathione transferases
PMID: 16551546 Adaptations against heme toxicity in blood-feeding arthropods

**Comment by pgaudet** [comment]
'response' terms are very vague, we aim to better describe processes than just 'response to'. 

How about  for MF'heme sequestering activity', as a child of 'GO:0140313 molecular sequestering activity' , and for BP, create a child of 'GO:0098754 detoxification', 'heme detoxification'? 

Thanks, Pascale

**Comment by rwst** [comment]
Agree with both commenters, thanks.

**Comment by raymond91125** [comment]
@pgaudet Per PMID 26741528, the responses are about signalling leading to inflammation, tissue damage repair, rather than heme sequestration per se. And in invertebrates, there are anti-oxidant gene expression responses to free heme.

**Comment by pgaudet** [comment]
Again I would lean towards a more informative term. They clearly describe an adaptive immune response, detected by pattern recognition receptors (PRR). 


@rwst which gene are you annotating?

**Comment by rwst** [comment]
The gene / expression reactions specifically annotated in this pathway are HMOX1 and BACH1, with the BACH1:MAFK protein complex regulating HMOX1 expression.

**Comment by pgaudet** [comment]
For PMID:32983129 I suggest using 'GO:0034145 positive regulation of toll-like receptor 4 signaling pathway'

For PMID:26741528 could one of these work? 
- GO:0002221 pattern recognition receptor signaling pathway
- GO:0002752 cell surface pattern recognition receptor signaling pathway
- GO:0002753 cytoplasmic pattern recognition receptor signaling pathway 

Looking at the references, it looks like HMOX1 and BACH1 are involved (directly and indirectly) in heme synthesis; if this is right, annotating to 'cellular response to heme' is incorrect, as these genes are upstream of the response to heme.

**Comment by pgaudet** [comment]
Sorry I conflated the response to heme stress and the HMOX1 synthesis you mentioned after in https://github.com/geneontology/go-ontology/issues/21264#issuecomment-964924960. 

How about 'free heme detoxification' then ? 

I don't completely object to 'response to' if this is what you think describes the data best, but I would like to be more specific if possible. 

Thanks again, Pascale

**Comment by rwst** [comment]
I would agree as this fits the pathway's placement in Reactome's hierarchy. The bigger picture, i.e., heme as signaling compound, and HMOX1's role in biliverdin/bilirubin synthesis may be subject to future requests.

**Comment by rwst** [comment]
As I learn, there may be reshuffling of this pathway in a wider context by other Reactome curators. So I wouldn't mind putting this on ice until the bigger picture emerges.

**Comment by pgaudet** [comment]
Should we close until then? Or do you still need  'free heme detoxification'?

**Comment by rwst** [comment]
I think this is needed, yes. Thankis.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140725
+name: detoxification of free heme
+namespace: biological_process
+def: "Any process that reduces or removes the toxicity of free heme. These include transport of heme away from sensitive areas and to compartments or complexes whose purpose is sequestration of heme." [PMID:26741528, PMID:32983129]
+synonym: "free heme detoxification" EXACT []
+is_a: GO:0098754 ! detoxification
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21264 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-18T09:03:32Z
+
