### ISSUE TITLE
Odd equivalence axiom for 'T cell receptor binding'

### ISSUE THREAD

**Issue by addiehl** [geneontology/go-ontology#21261]
When exploring go-plus.owl in Protege, I came across an odd equivalence axiom for the class 'T cell receptor binding', GO:0042608, as well as a related subclass axiom.

binding
 and ('has input' some 'sperm motility kinase Tcr mutant form')

'has input' some 'sperm motility kinase Tcr mutant form'

The [Sperm motility kinase Tcr mutant form](https://www.uniprot.org/uniprot/A2KF29) has nothing to do with the T cell receptor, despite the fact that TCR is used as an abbreviation for the T cell receptor in many contexts.

It would be great if this equivalence axiom and the related subclass axiom could be removed from GO:0042608.

GO does contain a class 'T cell receptor complex', GO:0042101, which could perhaps be substituted in for 'sperm motility kinase Tcr mutant form' in these axioms, though I don't know if there is an active GOC policy to create logical definitions for receptor binding terms, since most of them do not have such axioms.

Thanks, Alex

**Comment by pgaudet** [comment]
@balhoff any idea where this comes from? Someone must have loaded the PRO entity to add this LD?

**Comment by pgaudet** [comment]
Maybe the confusion comes from the exact synonym 'Tcr'?

**Comment by pgaudet** [comment]
Changed EA to 

'protein-containing complex binding' 
and 'has input' some 'T cell receptor complex'

Thanks, Pascale

**Comment by addiehl** [comment]
Thanks Pascale!
