### ISSUE TITLE
NTR: negative (and positive regulation) of aldehyde dehydrogenase (NAD+) activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#21265]
Dear GO editors,
could you please consider creating the regulation terms for GO:0004029 aldehyde dehydrogenase (NAD+) activity

PubMed=33495566 shows that PRMT3 UniProtKB/O60678 interacts and inhibits the  aldehyde dehydrogenase (NAD+) activity ALDH1A1.
Thanks.

**Comment by pgaudet** [comment]
Hi @lbreuza 

We are not creating BP terms for regulation of activity anymore. I can create 'aldehyde dehydrogenase (NAD+) inhibitor activity'; I'd rather not create the other terms until we find evidence that the functions exist. 

Does that work for you?

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140631
+name: aldehyde dehydrogenase (NAD+) inhibitor activity
+namespace: molecular_function
+def: "Binds to and stops, prevents or reduces the activity of aldehyde dehydrogenase (NAD+)." [PMID:33495566]
+is_a: GO:0004857 ! enzyme inhibitor activity
+relationship: negatively_regulates GO:0004029 ! aldehyde dehydrogenase (NAD+) activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21265 xsd:anyURI
+created_by: pg
+creation_date: 2021-04-09T09:40:21Z
