### ISSUE TITLE
NTR : 3-deoxyglucosone dehydrogenase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#21268]
Hi,
could you please consider creating a new term for the following reaction:

Reaction=3-deoxyglucosone + H2O + NAD(+) = 2-dehydro-3-deoxy-D-gluconate + 2 H(+) + NADH [Rhea:67244]

as a child of GO:0004029 aldehyde dehydrogenase (NAD+) activity

ALDH1A1 has this activity as described in : PubMed=17175089

3-deoxyglucosone is a product of the fructosamine catabolic process and is itself a potent glycating agent that may react with lysine and arginine side-chains to form various AGEs.

Thanks.

**Comment by hdrabkin** [comment]
RHEA:67244 not pubic yet;
term added with PMID and mark ticket rhea-pending

+id: GO:0106373
+name: 3-deoxyglucosone dehydrogenase activity

**Comment by lbreuza** [comment]
Thanks Harold.

**Comment by hdrabkin** [comment]
RHEA:67244 not public yet 8/12/2021
