### ISSUE TITLE
New children of "GO:0015453 oxidoreduction-driven active transmembrane transporter activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21275]
I think the 4 GO terms below should get an additional parent of:

id: GO:0015453
name: oxidoreduction-driven active transmembrane transporter activity
def: "Primary active transport of a solute across a membrane, driven by exothermic flow of electrons from a reduced substrate to an oxidized substrate. Primary active transport is catalysis of the transport of a solute across a membrane, up the solute's concentration gradient, by binding the solute and undergoing a series of conformational changes. Transport works equally well in either direction and is driven by a primary energy source." [GOC:mtg_transport, ISBN:0815340729, TC:3.D.-.-.-]

This also fits with their EC xrefs of 7.-.1.-, where '1' as the third digit specifies translocases linked to oxidoreductase reactions.

(I haven't checked if there are further GO terms with EC xrefs matching '7.-.1.-')

Thoughts @kaxelsen ?

==

id: GO:0008137
name: NADH dehydrogenase (ubiquinone) activity
def: "Catalysis of the reaction: NADH + ubiquinone + 5 H(+)(in) <=> NAD(+) + ubiquinol + 4 H(+)(out)." [RHEA:29091]
xref: EC:7.1.1.2
xref: RHEA:29091
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0050136 ! NADH dehydrogenase (quinone) activity

id: GO:0008121
name: ubiquinol-cytochrome-c reductase activity
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: CoQH2 + 2 ferricytochrome c = CoQ + 2 ferrocytochrome c + 2 H+." [RHEA:11484]
xref: EC:7.1.1.8
xref: RHEA:11484
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0016679 ! oxidoreductase activity, acting on diphenols and related substances as donors

id: GO:0004129
name: cytochrome-c oxidase activity
def: "Catalysis of the reaction: 4 ferrocytochrome c + O2 + 4 H+ = 4 ferricytochrome c + 2 H2O." [RHEA:11436]
xref: EC:7.1.1.9
xref: RHEA:11436
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0015078 ! proton transmembrane transporter activity
is_a: GO:0016675 ! oxidoreductase activity, acting on a heme group of donors

id: GO:0140571
name: transmembrane ascorbate ferrireductase activity
def: "Oxidation of Fe(3+) to Fe(2+) on the outer side of a membrane coupled to the reduction of L-ascorbate to monodehydro-L-ascorbate radical on the inner side of a membrane. Electrons get transferred across the membrane during the reaction." [PMID:16911521, PMID:24449903, RHEA:30403]
xref: EC:7.2.1.3
xref: RHEA:30403
is_a: GO:0016722 ! oxidoreductase activity, acting on metal ions

**Comment by pgaudet** [comment]
Hi @sjm41 

Based on the synonyms, it looks like GO:0015453 oxidoreduction-driven active transmembrane transporter activity was created to align to TC:3.D; however the children you suggest are not children of TC:3.D: 
http://www.tcdb.org/search/result.php?tc=3.D

I wonder if we really want to align to how EC now represents transporters. For example in GO, GO:0008137 NADH dehydrogenase (ubiquinone) activity is an oxidoreductase. 

The transporters MF are defined either as 
- transmembrane transporter, in which the transporter remains in place and allows a substrate to pass though some kind of channel
- carrier activity, in which the carrier moves together with its substrate, such as karyopherin. 

For those 7.xx EC reactions, the chemistry of the reaction results in a net difference in the number of protons across the membrane, but those are not _transported_, at least not by the mechanism we describe. In the case of the reactions you give above, it would be consistent with GO to annotate to the BP 'proton transport', but not to the MF transporter activity. 

What do you think ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks for the links to TCDB!
It looks like the children I'm suggesting are (mostly) included under TC:3.D:

id: GO:0008137
name: NADH dehydrogenase (ubiquinone) activity
=> 3.D.1 The H+ or Na+-translocating NADH Dehydrogenase (NDH) Family

id: GO:0008121
name: ubiquinol-cytochrome-c reductase activity
=> 3.D.3 The Proton-translocating Quinol:Cytochrome c Reductase (QCR) Superfamily

id: GO:0004129
name: cytochrome-c oxidase activity
=> 3.D.4 The Proton-translocating Cytochrome Oxidase (COX) Superfamily

id: GO:0140571
name: transmembrane ascorbate ferrireductase activity
=> I don't immediately see this, but it seems only recently defined (see #20602), so this omission may be expected?

**Comment by sjm41** [comment]
"GO:0022857 transmembrane transporter activity" is defined as "Enables the transfer of a substance, usually a specific substance or a group of related substances, from one side of a membrane to the other."  I don't see the requirement for there being some kind of channel here?

Also, I was viewing "oxidoreduction-driven active transmembrane transporter activity" as analogous to "ATPase-coupled transmembrane transporter activity ; GO:0042626" (and they are sister terms in GO).
That is, the primary function of "ATPase-coupled transmembrane transporters" is active transporters (translocases), using ATP as energy source, so are best classified as translocases (using ATP hydrolysis) rather than hydrolases in the GO. Likewise, if the primary function of "oxidoreduction-driven active transmembrane transporters" is as active transporters/translocases using an oxidoreductase reaction as an energy source, perhaps they are best classified as translocases rather than oxidoreductases? This view seems to align OK with EC and TCDB, as well as being consistent with how the ATPases have recently been reorganised in the GO?


in GO are now organised such that the ATPase aspect is somewhat secondary

**Comment by pgaudet** [comment]
Thinking about this some more, also with @ValWood , it just seems that those are really different types of molecular functions. The difference between TM transporter, even as it is currently defined ("Enables the transfer of a substance...",), implies that the protein makes the substance go from one side of the membrane to the other. On the other hand, those oxidoreductase reactions result in a net difference in the concentration of a substance (usually a proton or an electron) across the membrane, without actually mediating transport. 

It seems this is appropriate for a BP 'proton transport' but I am not sure this is the same type of function as say an ABC transporter. 

Also - how would it differ from  GO:0009055 electron transfer activity - or would you move that under the new term you propose? (although as far as I remember not all electron transporters results in transport across the membrane, this is the difference between the first and the last step). 

Thanks, Pascale

**Comment by ValWood** [comment]
Note though that we should remove the transmembrane transporter parent from "cytochrome-c oxidase activity"

**Comment by sjm41** [comment]
Thanks for thinking about this. I agree that these 'oxidoreductase-powered transporters' are different MFs than ATP-dependent transporters (such as the ABC transporters) and should be separated from them, but I also think the literature & other databases support classifying them as a type of 'transporter (or 'translocase').

Focussing just on the 3 catalytic terms for Complex I (NADH dehydrogenase (ubiquinone) activity), III (ubiquinol-cytochrome-c reductase activity) and IV (cytochrome-c oxidase activity) of the OXPHOS system:
As I understand it, the primary function of these 3 complexes is to pump protons from one side of the membrane to the other (matrix to intermembrane space) - all the reviews/books I've looked at describe these 3 complexes as 'proton pumps'. This pumping is the end result of electron transfer initiated by an oxidoreductase reaction. (e.g. https://en.wikipedia.org/wiki/Oxidative_phosphorylation or https://pubmed.ncbi.nlm.nih.gov/26921811/)

Consistent with that view, both EC (https://enzyme.expasy.org/EC/7.1.1.-) and TC (http://www.tcdb.org/search/result.php?tc=3.D) classify these enzymes as transporters/translocases, driven by/linked to oxidoreduction (see classification/definitions below)

In GO, the current parentages for the catalytic terms for Complex I, III and IV capture the oxidoreductase and electron transfer aspect, but don't capture the primary proton pump aspect. It seems like this is an omission, which can easily be rectified by adding the existing 'GO:0015453 oxidoreduction-driven active transmembrane transporter activity' term - as you say, this was created based on TC:3.D, but the GO terms corresponding to children of TC:3.D have not so far been added as children in GO.

If we're not going to add the TC:3.D children as children in GO, then 'GO:0015453 oxidoreduction-driven active transmembrane transporter activity' may as well be obsoleted.
FYI, QuickGO (https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0015453
) says there are currently only 142 annotations to the term, the majority of which are to COX3 subunits via PANTHER:PTN000150044 (CYTOCHROME C OXIDASE SUBUNIT III (PTHR11403))

But it still seems accurate to me to add 'GO:0015453 oxidoreduction-driven active transmembrane transporter activity' as an additional parent (fine to keep current parents) to:
NADH dehydrogenase (ubiquinone) activity (GO:0008137)
ubiquinol-cytochrome-c reductase activity (GO:0008121)
cytochrome-c oxidase activity (GO:0004129)

Also seems accurate to add "GO:0015078 proton transmembrane transporter activity" to the first two terms rather than remove from the third term.


For comparision, the GO terms for proton pumps coupled to ATP synthesis or hydrolysis _are_ classified as proton transporters in the GO:

id: GO:0046933
name: proton-transporting ATP synthase activity, rotational mechanism
def: "Enables the synthesis of ATP from ADP and phosphate by the transfer of protons from one side of a membrane to the other by a rotational mechanism driven by a gradient according to the reaction: ADP + H2O + phosphate + H+(in) = ATP + H+(out)." [RHEA:57722]
is_a: GO:0015252 ! proton channel activity
is_a: GO:0016874 ! ligase activity

id: GO:0046961
name: proton-transporting ATPase activity, rotational mechanism
def: "Enables the transfer of protons from one side of a membrane to the other according to the reaction: ATP + H2O + H+(in) = ADP + phosphate + H+(out), by a rotational mechanism." [RHEA:57721]
is_a: GO:0009678 ! pyrophosphate hydrolysis-driven proton transmembrane transporter activity
is_a: GO:0019829 ! ATPase-coupled cation transmembrane transporter activity
is_a: GO:0044769 ! ATPase activity, coupled to transmembrane movement of ions, rotational mechanism

**Comment by ValWood** [comment]
Yes, based on this it does make sense to add.

**Comment by kaxelsen** [comment]
> (although as far as I remember not all electron transporters results in transport across the membrane, this is the difference between the first and the last step).
@pgaudet This is true. NADP, FAD, FMN, ferredoxin, flavodoxin etc etc can all be considered electron transporters.
I also think your suggestions make sense.

**Comment by pgaudet** [comment]
Hi @sjm41 

I've made the following changes: 

NADH dehydrogenase (ubiquinone) activity (GO:0008137)
+is_a: GO:0015078 ! proton transmembrane transporter activity
+is_a: GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity


ubiquinol-cytochrome-c reductase activity (GO:0008121)
+is_a: GO:0015078 ! proton transmembrane transporter activity
+is_a: GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity


cytochrome-c oxidase activity (GO:0004129)
+is_a: GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity

I am not fully clear if that's what you meant by 
> Also seems accurate to add "GO:0015078 proton transmembrane transporter activity" to the first two terms rather than remove from the third term.

Please let me know if this is what you had in mind. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet! Yes, that is what I meant.

My original post also suggested adding the "GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity" parent to this term, based on its definition and EC xref:

id: GO:0140571
name: transmembrane ascorbate ferrireductase activity
def: "Oxidation of Fe(3+) to Fe(2+) on the outer side of a membrane coupled to the reduction of L-ascorbate to monodehydro-L-ascorbate radical on the inner side of a membrane. Electrons get transferred across the membrane during the reaction." [PMID:16911521, PMID:24449903, RHEA:30403]
xref: EC:7.2.1.3
xref: RHEA:30403
is_a: GO:0016722 ! oxidoreductase activity, acting on metal ions

Can you add that too?

**Comment by pgaudet** [comment]
Sure. 
However I think those are involved in transport but are not transmembrane transporters.  I worry these relations might cause inconsistencies in the future.

**Comment by pgaudet** [comment]
To be more specific: cytochrome-c oxidase activity does pump protons across the membrane, as described in http://www.tcdb.org/search/result.php?tc=3.D.4


For transmembrane ascorbate ferrireductase activity my understanding was that there were 2 reactions taking place on either side of the membrane, resulting in a net difference in protons, but without actually transporting them - see discussion here: https://github.com/geneontology/go-ontology/issues/20602

Thanks, Pascale

**Comment by sjm41** [comment]
Hi pascale

I took another look at this - here's what I found:

Lionel's original proposed def for 'transmembrane ascorbate ferrireductase activity' was:
"Transmembrane ascorbate ferrireductase that that transfers electrons across a single membrane."

Lionel also said:
"My understanding is that it oxidizes ascorbate on one side of the membrane while reducing iron on the other side of the membrane. Hence there is a flux of electron from in to out. This is why it is considered a transport reaction coupled to an oxido-reduction (EC.7...). "

Also, the EC page (https://enzyme.expasy.org/EC/7.2.1.3) says:
Ascorbate ferrireductase (transmembrane).
Comments: A diheme cytochrome that transfers electrons across a single membrane, such as the outer membrane of the enterocyte, or the tonoplast membrane of the plant cell vacuole.

And the current GO def includes:
"Electrons get transferred across the membrane during the reaction."

Finally, I also found this review (https://pubmed.ncbi.nlm.nih.gov/19501649/) that is generally useful to these discussions, and also says that the mechanism is "enzyme-mediated transmembrane electron transfer"


So....I think that's all consistent with there being transport of electrons across the membrane, meaning the proposed parentage is OK?

**Comment by sjm41** [comment]
I searched for other GO terms with an xref like EC:7.*.1.* and found two more we should consider (see below) - these should also get the "GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity" parent to be consistent.

7.1.1.3      Ubiquinol oxidase (H(+)-transporting)
=>
id: GO:0009486
name: cytochrome bo3 ubiquinol oxidase activity
namespace: molecular_function
alt_id: GO:0008827
def: "Catalysis of the reaction: 2 ubiquinol + O2 + 4 H+ = 2 ubiquinone + 2 H2O + 4 H+ [periplasmic space]." [RHEA:30251]
synonym: "cytochrome bo oxidase" EXACT [EC:7.1.1.3]
synonym: "cytochrome bo(3) oxidase" EXACT [EC:7.1.1.3]
synonym: "cytochrome o ubiquinol oxidase activity" RELATED []
xref: EC:7.1.1.3
xref: MetaCyc:RXN0-5268
xref: RHEA:30251
xref: TC:3.D.4.5.1
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0016675 ! oxidoreductase activity, acting on a heme group of donors


7.1.1.6      Plastoquinol--plastocyanin reductase
=>
id: GO:0009496
name: plastoquinol--plastocyanin reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 H(+)[side 1] + 2 oxidized plastocyanin + plastoquinol-1 = 2 H(+)[side 2] + 2 reduced plastocyanin + plastoquinone. This reaction involves the concomitant transfer of 2 H+ ions across a membrane." [RHEA:22148]
synonym: "cytochrome b6f" NARROW []
synonym: "cytochrome b6f complex activity" RELATED [EC:7.1.1.6]
synonym: "plastoquinol-plastocyanin reductase activity" RELATED []
synonym: "plastoquinol/plastocyanin oxidoreductase activity" RELATED []
synonym: "plastoquinol:oxidized-plastocyanin oxidoreductase activity" RELATED []
xref: EC:7.1.1.6
xref: KEGG_REACTION:R03817
xref: MetaCyc:PLASTOQUINOL--PLASTOCYANIN-REDUCTASE-RXN
xref: RHEA:22148
is_a: GO:0052880 ! oxidoreductase activity, acting on diphenols and related substances as donors, with copper protein as acceptor

**Comment by kaxelsen** [comment]
Very soon there will also be:
EC 7.1.1.10 ferredoxin—quinone oxidoreductase (H+-translocating)
It will be linked to RHEA:67632
a plastoquinone + 6 H+(in) + 2 reduced [2Fe-2S]-[ferredoxin] = a plastoquinol + 4 H+(out) + 2 oxidized [2Fe-2S]-[ferredoxin] 
MetaCyc: RXN-22408 (the reaction is slightly different since MetaCyc uses plastoquinone-9 as substrate while Rhea uses "a plastoquinone")

**Comment by pgaudet** [comment]
@kaxelsen How soon? July release?

**Comment by pgaudet** [comment]
@kaxelsen @amorgat Can we arrange that you guys send us a list of new reactions at each release? That would be easier for us than going back to tickets.

**Comment by kaxelsen** [comment]
It will be in the next freeze just rescheduled for June 14ish. So I suspect an August release
