### ISSUE TITLE
Remove EC:7.2.2.- xref from "GO:0042626 ATPase-coupled transmembrane transporter activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21273]
EC:7.2.2.- is for "Translocases -> Catalysing the translocation of inorganic cations -> Linked to the hydrolysis of a nucleoside triphosphate" (https://enzyme.expasy.org/EC/7.2.2.-) so it should be removed from the following GO term (which is not specific to transport of inorganic cations):

id: GO:0042626
name: ATPase-coupled transmembrane transporter activity
namespace: molecular_function
alt_id: GO:0015405
alt_id: GO:0016820
alt_id: GO:0043492
def: "Primary active transporter of a solute across a membrane, via the reaction: ATP + H2O = ADP + phosphate, to directly drive the transport of a substance across a membrane. The transport protein may be transiently phosphorylated (P-type transporters), or not (ABC-type transporters and other families of transporters). Primary active transport occurs up the solute's concentration gradient and is driven by a primary energy source." [GOC:mtg_transport, ISBN:0815340729]
xref: EC:7.2.2.-
is_a: GO:0015399 ! primary active transmembrane transporter activity
is_a: GO:0016887 ! ATPase

The problem is already noted on this obsolete term:

id: GO:0106192
name: obsolete translocase activity acting on inorganic cations and their chelates linked to the hydrolysis of a nucleoside triphosphate
namespace: molecular_function
def: "OBSOLETE. Catalysis of the translocation of inorganic cations and their chelates linked to the hydrolysis of a nucleoside triphosphate." [GOC:hjd, http://www.enzyme-database.org]
**comment: This term was made obsolete because the concept of using the non-4 digit EC classes as parent terms for the transporter banch of the onotolgy was consided confusing.**
xref: EC:7.2.2.-
is_obsolete: true

**Comment by pgaudet** [comment]
Hi @sjm41 
I don't see why partial ECs are any more confusing for transporters than for any other MF ? 

Meanwhile - I removed the EC from GO:0042626 and added it to 

GO:0140359 ABC-type transporter activity and
GO:0140358 P-type transporter activity

Does that work for you ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet

_I don't see why partial ECs are any more confusing for transporters than for any other MF ?_
It's because the hierarchical classification of other enzymes in GO follows the EC classification number order, e.g. if EC has EC:1.2.3.4, GO tends to have a term hierarchy corresponding to 1 -> 2 -> 3 -> 4.

But this isn't true for transporters/translocases, e.g. if EC has EC:7.2.3.4, GO tends to have a term hierarchy corresponding to 7 -> 3 -> 2 -> 4.

That is, it's the third EC digit that specifies the 'energy source' (NTP hydrolysis, oxidoreductase etc) while the second digit specifies what's being transported (protons, other ions, peptides etc), whereas GO does it the other way round -  see children of primary active transmembrane transporter activity GO:0015399.

So....EC:7.2.2.- is specifically for translocases of **inorganic cations** via NTP hydrolysis, whereas GO:0042626 is for ATPase-coupled transporters agnostic of the substance transported.

GO:0140359 ABC-type transporter activity and GO:0140358 P-type transporter activity aren't specific to inorganic cation transport either, so I don't think EC:7.2.2.- should be added to those.
Far as I can tell, there isn't a GO term equivalent to EC:7.2.2.-

**Comment by pgaudet** [comment]
Thanks for the clarification @sjm41
