### ISSUE TITLE
GO:0008553 and GO:0046961 parentage/xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21272]
I think the "GO:0009678 ! pyrophosphate hydrolysis-driven proton transmembrane transporter activity" parent shuld be removed from GO:0008553 and GO:0046961. In both cases, their EC xref of 7.1.2.- is for "Hydron translocation linked to the hydrolysis of a nucleoside triphosphate" (https://enzyme.expasy.org/EC/7.1.2.-) - that's consistent with the other parents on these two terms, but not with "pyrophosphate hydrolysis-driven proton transmembrane transporter activity", which has EC xref of 7.1.3.1 (= Hydron translocation linked to the hydrolysis of diphosphate)

Also, it also looks like EC:7.1.2.2 has been removed as an xref on GO:0046961 - I think that should be added back. (That EC is also on GO:0046933 proton-transporting ATP synthase activity, rotational mechanism) but it's bidirectional so should be on both GO terms, right?

id: GO:0008553
name: P-type proton-exporting transporter activity
def: "Enables the transfer of protons from one side of a membrane to the other according to the reaction: ATP + H2O + H+(in) -> ADP + phosphate + H+(out). These transporters use a phosphorylative mechanism, which have a phosphorylated intermediate state during the ion transport cycle." [EC:7.1.2.1]
synonym: "H(+)-transporting ATPase activity" BROAD [EC:7.1.2.1]
synonym: "H+-exporting ATPase activity" RELATED [EC:7.1.2.1]
synonym: "H+-transporting ATPase" BROAD [EC:7.1.2.1]
synonym: "hydrogen exporting ATPase activity, phosphorylative mechanism" EXACT []
synonym: "hydrogen-/sodium-translocating ATPase activity" RELATED []
synonym: "hydrogen-exporting ATPase activity" BROAD []
synonym: "hydrogen-exporting ATPase activity, phosphorylative mechanism" RELATED []
synonym: "P-type H(+)-exporting ATPase activity" BROAD [EC:7.1.2.1]
synonym: "proton transport ATPase activity" RELATED [EC:7.1.2.1]
synonym: "proton-exporting ATPase activity" BROAD []
synonym: "proton-exporting ATPase activity, phosphorylative mechanism" RELATED []
synonym: "proton-translocating ATPase activity" RELATED [EC:7.1.2.1]
synonym: "proton-transporting ATPase activity" EXACT [GOC:bf]
xref: EC:7.1.2.1
xref: MetaCyc:3.6.3.6-RXN
xref: RHEA:20852
**is_a: GO:0009678 ! pyrophosphate hydrolysis-driven proton transmembrane transporter activity**
is_a: GO:0019829 ! ATPase-coupled cation transmembrane transporter activity
is_a: GO:0140358 ! P-type transmembrane transporter activity

id: GO:0046961
name: proton-transporting ATPase activity, rotational mechanism
def: "Enables the transfer of protons from one side of a membrane to the other according to the reaction: ATP + H2O + H+(in) = ADP + phosphate + H+(out), by a rotational mechanism." [RHEA:57721]
synonym: "ATP phosphohydrolase (H+-transporting) activity" NARROW []
synonym: "ATP synthase activity" NARROW [EC:7.1.2.2]
synonym: "chloroplast ATPase activity" NARROW [EC:7.1.2.2]
synonym: "F(0)F(1)-ATPase activity" NARROW [EC:7.1.2.2]
synonym: "F(1)-ATPase activity" NARROW [EC:7.1.2.2]
synonym: "F(o)F(1)-ATPase activity" NARROW [EC:7.1.2.2]
synonym: "F0F1-ATPase" NARROW [EC:7.1.2.2]
synonym: "F1-ATPase" NARROW []
synonym: "FoF1-ATPase" NARROW [EC:7.1.2.2]
synonym: "H(+)-transporting ATP synthase activity" NARROW [EC:7.1.2.2]
synonym: "H+-transporting ATPase activity" NARROW [EC:7.1.2.2]
synonym: "hydrogen ion translocating A-type ATPase activity" NARROW []
synonym: "hydrogen ion translocating F-type ATPase activity" NARROW []
synonym: "hydrogen ion translocating V-type ATPase activity" NARROW []
synonym: "hydrogen ion transporting ATPase activity, rotational mechanism" EXACT []
synonym: "hydrogen ion transporting two-sector ATPase activity" NARROW []
synonym: "mitochondrial ATPase activity" NARROW [EC:7.1.2.2]
xref: RHEA:57721
**is_a: GO:0009678 ! pyrophosphate hydrolysis-driven proton transmembrane transporter activity**
is_a: GO:0019829 ! ATPase-coupled cation transmembrane transporter activity
is_a: GO:0044769 ! ATPase activity, coupled to transmembrane movement of ions, rotational mechanism

**Comment by sjm41** [comment]
Hi @hdrabkin Can you help with this one?

**Comment by hdrabkin** [comment]
'it also looks like EC:7.1.2.2 has been removed as an xref on GO:0046961 - I think that should be added back. (That EC is also on GO:0046933 proton-transporting ATP synthase activity, rotational mechanism) but it's bidirectional so should be on both GO terms, right?"
@pgaudet do you know why this was removed?

**Comment by sjm41** [comment]
Just checked again:
- looking at http://snapshot.geneontology.org/ontology/go-basic.obo, EC:7.1.2.2 is missing as an xref on GO:0046961
- but looking at https://www.ebi.ac.uk/QuickGO/term/GO:0046961, EC:7.1.2.2 is present as an xref on GO:0046961

??

**Comment by pgaudet** [comment]
@hdrabkin this explain mappings to  EC:7.1.2.2  #20577
@sjm41 EC:7.1.2.2 is a NARROW xref (see ticket above), as per your request a while back to remove extraneous cross-references. I think we only export NARROW xrefs in the full go, not in the basic, to meet what we understood to be the 'simple' use case of only getting EXACT xrefs. 

Is that OK?

**Comment by pgaudet** [comment]
@hdrabkin this explain mappings to  EC:7.1.2.2  #20577
@sjm41 EC:7.1.2.2 is a NARROW xref (see ticket above), as per your request a while back to remove extraneous cross-references. I think we only export NARROW xrefs in the full go, not in the basic, to meet what we understood to be the 'simple' use case of only getting EXACT xrefs. 

Is that OK?

**Comment by sjm41** [comment]
@pgaudet Thanks for pointing us to #20577 - that does explain the situation.  Naively, it seems to me EC:7.1.2.2 should be an EXACT xref on both GO:0046961 and GO:0046933, but I think the argument in  #20577 is that having it as an EXACT xref on GO:0046961 causes problems for the EC2GO pipeline, so I guess the mapping has to be this way.

Regardless, do we agree that the parentage issue at the top of the ticket should be corrected?

**Comment by pgaudet** [comment]
Added EC:7.2.2.- to GO:0042626 'ATPase-coupled transmembrane transporter activity'

**Comment by pgaudet** [comment]
@sjm41 
Are you are the parentage is wrong between GO:0009678 ! pyrophosphate hydrolysis-driven proton transmembrane transporter activity" and GO:0008553 and GO:0046961? 

Both include pyrophosphatase reactions (right?) 
The only think is the EC hierarchy is not the same, but I think this is the case of EC being limited to 4 levels. 

Should we chat about this sometime ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet 

Looking at the 'parent' term here:
```
id: GO:0009678
name: pyrophosphate hydrolysis-driven proton transmembrane transporter activity
def: "Enables the transmembrane transport of one proton (H+), driven by the hydrolysis of pyrophosphate, and generating a proton motive force." [GOC:mtg_transport, ISBN:0815340729, Wikipedia:Proton-pumping_pyrophosphatase]
xref: EC:7.1.3.1
xref: MetaCyc:TRANS-RXN-370
xref: RHEA:13973
xref: TC:3.A.10
```

This describes transport driven specifically by the hydrolysis of "pyrophosphate" (or "diphosphate", to use the [EC:7.1.3.-](https://enzyme.expasy.org/EC/7.1.3.-) /RHEA:13973 terminology).  So, not hydrolysis of a pyrophosphate bond (as found in ATP, for example), but specifically hydrolysis of a pyrophosphate molecule (https://en.wikipedia.org/wiki/Pyrophosphate).
![Screenshot 2023-06-26 at 14 57 04](https://github.com/geneontology/go-ontology/assets/16306861/e34eb50f-e202-4cbd-a833-a12e4a357763)

I think it would be clearer (and consistent with EC/RHEA) for GO to use 'diphosphate' rather than 'pyrophosphate' in the term name and def here.

Also note the [EC:7.1.3.1](https://enzyme.expasy.org/EC/7.1.3.1) entry says that activity is specifically found in plants and fungi.


So, it's true that GO:0009678 should not be a parent of GO:0008553 and GO:0046961, where transport is driven by hydrolysis of a nucleoside triphosphate (ATP), ie. a subtype of [EC:7.1.2.1](https://enzyme.expasy.org/EC/7.1.2.1)


Happy to chat if needed!

**Comment by pgaudet** [comment]
> I think it would be clearer (and consistent with EC/RHEA) for GO to use 'diphosphate' rather than 'pyrophosphate' in the term name and def here.

I already did that https://github.com/geneontology/go-ontology/commit/98b79de24f7db318aa31b1cdf3acea2b571c48ce (but I forgot to write here)- I generally align reactions with Rhea definitions, as much as possible.

**Comment by sjm41** [comment]
Thanks! Though I see that change from 'pyrophosphate' -> 'diphosphate' in the def but not in the term name.

**Comment by pgaudet** [comment]
The problem comes from 
. 'pyrophosphatase activity'
. . 'ribonucleoside triphosphate phosphatase activity'
. . . 'ATP hydrolysis activity'

* 'ribonucleoside triphosphate phosphatase activity' is a GO:0016462 (pyrophosphatase activity) seems incorrect? should it not be is_a GO:0016791 'phosphatase activity'?

**Comment by sjm41** [comment]
Those relationships look correct to me.
'ribonucleoside triphosphate phosphatase activity' (NTP -> NDP) is hydrolysis of a pyrophosphate bond in the NTP.

**Comment by pgaudet** [comment]
Changed the logical definition of the parent term  GO:0009678 ! pyrophosphate hydrolysis-driven proton transmembrane transporter activity

intersection_of: GO:0015399 ! primary active transmembrane transporter activity
-intersection_of: has_part GO:0016462 ! pyrophosphatase activity

The bad inferences are now gone. 

Thanks @sjm41 for your help! 

Pascale
