### ISSUE TITLE
terms with Rhea xrefs and EC xrefs with dashes

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21287]
According to @hdrabkin and @pgaudet, only terms with four part EC numbers can have Rhea xrefs.

- [ ]  http://purl.obolibrary.org/obo/GO_0008826  fixed
- [ ]  http://purl.obolibrary.org/obo/GO_0008146  grouping term; RHEA:51064 removed. EC is too broad; rEC:2.8.2.-emoved.
- [ ]  http://purl.obolibrary.org/obo/GO_0050253  fixed
- [ ]  http://purl.obolibrary.org/obo/GO_0018644 fixed
- [ ]  http://purl.obolibrary.org/obo/GO_0016810  Grouping term RHEA:45456 removed
- [ ]  http://purl.obolibrary.org/obo/GO_0016491 Grouping term;; RHEA:27453 removed
- [ ]  http://purl.obolibrary.org/obo/GO_0036403; removed EC
- [ ]  http://purl.obolibrary.org/obo/GO_0008766  fixed
- [ ]  http://purl.obolibrary.org/obo/GO_0018640 fixed
- [ ]  http://purl.obolibrary.org/obo/GO_0010296 fixed
- [ ]  http://purl.obolibrary.org/obo/GO_0016793 grouping term; RHEA:46148 removed
- [ ]  http://purl.obolibrary.org/obo/GO_0047376 leaf node; 3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0043798 leaf node3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0008412 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0018660 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0008732  leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0140575 leaf node 3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0016829 grouping term (lyases). ; rhea removed 
- [ ]  http://purl.obolibrary.org/obo/GO_0018694 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0018632 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0017099 RHEA:35351 removed ; this is a more generic term. EC removed also
- [ ]  http://purl.obolibrary.org/obo/GO_0016830 grouping term; rhea removed
- [ ]  http://purl.obolibrary.org/obo/GO_0018571  leaf node3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0008483 grouping term; rhea removed
- [ ]  http://purl.obolibrary.org/obo/GO_0008688 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0018570 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0034602 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0080016 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0033785 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0080017 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0016860 grouping term ; removed
- [ ]  http://purl.obolibrary.org/obo/GO_0080011 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0018652 leaf node3 digit ec removed; 
- [ ]  http://purl.obolibrary.org/obo/GO_0042299 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0052689 rare grouping term with a full ec and rhea ( EC 3.1.1.1); removed a 3 digit ec (3.1.1.-) Leaving RHEA in place. 

- [ ]  http://purl.obolibrary.org/obo/GO_0070225 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0009974  leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0052611 leaf node3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0008495 leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0008808 leaf node3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0016402 leaf node3 digit ec removed
- [ ]  http://purl.obolibrary.org/obo/GO_0046428  leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0010276  leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0047074  leaf node3 digit ec removed; new ec added from RHEA
- [ ]  http://purl.obolibrary.org/obo/GO_0052610 leaf node3 digit ec removed

**Comment by hdrabkin** [comment]
I will go in and remove these today; I see in some cases the term is ok with the rhea but there is a 3 digit ec to be removed; i
example: GO_0052610,  beta-cryptoxanthin hydroxylase activity; EC:1.14.99.- should be removed.
In some cases we found yesterday it was GO grouping term. 
Will start now.

**Comment by hdrabkin** [comment]
@balhoff 
Can you rerun this analysis; especially checking if these two show up again. Fixed all others. Will close if you don't get the two below again.

http://purl.obolibrary.org/obo/GO_0016491 Grouping term; but do not see a rhea
 http://purl.obolibrary.org/obo/GO_0036403; no 3 digit ec found here;

**Comment by hdrabkin** [comment]
Found problem with RHEA attached to triphosphoric monoester hydrolase activity, GO:0016793; ec makes no mention of nucleoside. So, made intermediate 'deoxynucleoside triphosphate hydrolase activity and transfered the RHEA to that term, then made dGTPase activity a child of the new term.

**Comment by hdrabkin** [comment]
carbon-carbon lyase activity http://purl.obolibrary.org/obo/GO_0016830
Removed
RHEA:25355  
Request to make this reaction for annotation. RHEA has it mapped to 'interim EC 4.1.2.n2
We don't use these; however, I can make new term a child of EC:4.1.2.- which we have as GO:0016832
Also found EC:4.1.2.- mapped to 5 leaf node reactions; I will remove.

**Comment by hdrabkin** [comment]
EC:4.1.2.- leaves
GO:0018802 removed EC:4.1.2.- and found a real PMID for the activity.
GO:0034529 removed EC:4.1.2.- and found a real PMID for the activity.
GO:0034537 removed EC:4.1.2.- and found a real PMID for the activity.
GO:0034531 removed EC:4.1.2.- and found a real PMID for the activity.
GO:0103042  had RHEA; 3 digit ec removed
