### ISSUE TITLE
NTR: translation activator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21280]
we have
 GO:0045182 translation regulator activity
GO:0030371 translation repressor activity

could we have activator too?

thanks,
Val

**Comment by pgaudet** [comment]
Reference?

**Comment by ValWood** [comment]
actually it is for the ortholog of
https://www.yeastgenome.org/locus/S000004280#go
but I think this should be

GO:0003746    translation elongation factor activity part_of  mitochondrial translational elongation

rather tthan
 positive regulation of translation 
(as it is currently)

**Comment by pgaudet** [comment]
Close?

**Comment by ValWood** [comment]
I guess so. Is the nucleic acid/ non nucleic acid binding parentage necessary?
but yes  can be closed.
