### ISSUE TITLE
Taxon constraints, numerous descendants of cytoplasm 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21281]
only in metazoa?
~GO:0060417  yolk~ see  #22279
~GO:0005883   neurofilament~ #22279

~only in protists? (although single EXP is from rat?)
GO:0043265 ectoplasm~
see https://github.com/geneontology/go-ontology/issues/24424

only in bacteria
~GO:0019812 type I site-specific deoxyribonuclease complex~  see  #22279
~GO:0009359 type II site-specific deoxyribonuclease complex~  see  #22279
~GO:0019813 type III site-specific deoxyribonuclease complex~  see  #22279
~GO:00320 type IV site-specific deoxyribonuclease complex~ see  #22279

only in plants
- [x] GO:0009574 preprophase band ->A dense band of microtubules, 1-3 pm wide, that appears just beneath the cell membrane before the start of cell division in the cells of higher plants.
- [x] GO:00095 phragmoplast  see https://github.com/geneontology/go-ontology/issues/24426
- [x] GO:0009525   see phragmosome https://github.com/geneontology/go-ontology/issues/24427

~GO:0120293   dynein axonemal particle~ see  #22279 

only in metazoa? or never in yeast
~GO:0120098 procentriole~  https://github.com/geneontology/go-ontology/issues/22279
- [x] GO:0005814 centriole
~GO:0120099   procentriole replication complex~  https://github.com/geneontology/go-ontology/issues/22279
- [x]  GO:0098534  centriole assembly
(any term with centriole/procentriole)

**Comment by ValWood** [comment]
only in metazoa
GO:0045169   fusome
GO:0002096   polkadots (2 CACAO + inferences), this term probably should go? it's just a gene specific foci in a specific cell type?
GO:0036457    keratohyalin granule (organisms with keratin?)
GO:0110158  calpain complex

only in bacteria
GO:0044227    methane-oxidizing organelle

only on protazoa
GO:0042566    hydrogenosome

**Comment by ValWood** [comment]
Only in metazoa
GO:0071142    homomeric SMAD protein complex
A protein complex composed of a single type of SMAD family proteins. In the absence of Smad4, phosphorylation of R-SMADs results in their homotrimerization. However, these complexes do not appear to import into the nucleus and are assumed to be transcriptionally inactive. PMID:11779505 PMID:16322555 PMID:9670020


Probably obsolete this one as it isn't used, and doesn't seem to represent a functional complex?

**Comment by ValWood** [comment]
protazoa
GO:0020022
Term name | acidocalcisome
Definition | An electron-dense acidic membrane-bounded organelle which contains a matrix of pyrophosphate and polyphosphates with bound calcium and other cations.


only in bacteria
GO:007008
Term name | PHA granule
An inclusion body located in the cytoplasm that consists of polyhydroxyalkanoate (PHA) molecules and associated proteins, surrounded by a phospholipid monolayer; the proteins include PHA synthase, PHA depolymerase and 3HB-oligomer hydroxylase, phasins (PhaPs), which are thought to be the major structural proteins of the membrane surrounding the inclusion, and the regulator of phasin expression PhaR.

only in plant
GO:0042735 protein body
Definition
A membrane-bounded plant organelle found in the developing endosperm, contains storage proteins.
-> rename to endosperm protein body?


only in bacteria
| GO:0044222 | anammoxosome
Definition | An intracytoplasmic membrane-bounded compartment in anaerobic ammonium oxidation (anammox) bacteria, is the site of anammox catabolism.

**Comment by ValWood** [comment]
This is primarily to make it easier for our community curators to find the correct descendant terms under cytoplasm (once a taxon restriction is applied we do not see the irrelevant ones), but good for QC anyway...

**Comment by ValWood** [comment]
HI @krchristie  is this on your radar? I think I have some overlap with other tickets, so if you can let me know when this one is done I can pick up the remaining.

**Comment by krchristie** [comment]
@ValWood - You should just take this one as I am no longer doing a significant amount of ontology work. I'll assign it to you and remove myself.

**Comment by ValWood** [comment]
only in plants
GO:0009574 preprophase band

**Comment by ValWood** [comment]
@pgaudet  could you check this one. Will add tomorrow if it looks OK

**Comment by ValWood** [comment]
still to do "never in"
