### ISSUE TITLE
Obsoletion:  viral assembly intermediate ?????

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21282]
viral assembly intermediate
Specific locations and structures in the virus infected cell involved in assembling new virions.
?????

2 annotations both ISS

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obosolete 'GO:0019037 viral assembly intermediate'. The reason for obsoletion is that this term is too vague ("Specific locations and structures in the virus infected cell involved in assembling new virions."). There are no experimental annotations or mappings to this term. This term is not present in any subsets.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/21282

Thanks, Pascale
