### ISSUE TITLE
OTR: GO:0061700 GATOR2 complex add synonym, change definition

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#21296]
[GO:0061700 GATOR2 complex](https://www.ebi.ac.uk/QuickGO/term/GO:0061700)

Like GATOR1 (https://www.ebi.ac.uk/QuickGO/term/GO:1990130), GATOR2 is also in yeast but is called SEACAT - and should have the non-human subunits added to the definition.  Proposed new def: 

A multiprotein subcomplex of GATOR that regulates mTOR signaling by interacting with the Rag GTPases. **In _S. cerevisiae_ this complex contains Rtc1p, Mtc5p, Sea4p, Seh1p and Sec13p proteins**. In humans this complex consists of Mios, WDR24, WDR59, Seh1L, Sec13.

Also, GO:0061700 GATOR2 complex needs an **exact synonym of "SEACAT complex"**

From http://www.ncbi.nlm.nih.gov/pubmed/25934700

The SEA complex consists of two subcomplexes (Table 1), named SEA subcomplex inhibiting TORC1 (SEACIT, see below) and SEA subcomplex activating TORC1 (SEACAT, see below); in mammals these are termed GATOR1 and GATOR2 (Algret et al., 2014; Bar-Peled et al., 2013; Panchaud et al., 2013a; Panchaud et al., 2013b). SEACIT is composed of Sea1, Npr2 and Npr3 (Depdc5, Nprl2 and Nprl3, respectively in GATOR1), and SEACAT contains Sea2, Sea3, Sea4, Seh1 and Sec13 (Wdr24, Wdr59, Mios, Seh1L, Sec13 in GATOR2). In yeast, SEACAT and SEACIT can interact to form the full SEA complex (Algret et al., 2014). In humans, it has been suggested that GATOR1 and GATOR2 exist separately, and perhaps do not normally form a full stoichiometric GATOR complex (Bar-Peled et al., 2013); further work is required to establish whether the two mammalian subcomplexes indeed exist in a stable complex.

**Comment by ValWood** [comment]
Isn't this the SEACAT term?
https://www.ebi.ac.uk/QuickGO/term/GO:0035859

**Comment by ValWood** [comment]
Ignore, that is the parent...
