### ISSUE TITLE
NTR: copper import into the mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21294]
modelled on 

GO:0048250    iron import into the mitochondrion
The process in which iron is transported from the cytosol, into the mitochondrial matrix. PMID:12006577

please add
GO:NEW    copper import into the mitochondrion
The process in which copper is transported from the cytosol, into the mitochondrial matrix. 
https://pubmed.ncbi.nlm.nih.gov/32979421/

**Comment by mah11** [comment]
but also please remove the spurious commas from the text defs
