### ISSUE TITLE
New Term Requests: Protein-glutamic acid ligase activity, initiating and elongating

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#21309]
Hello,
I would like to request the following terms

Name: Protein-glutamic acid ligase activity, initiating
Ontology: Molecular_function
Child of GO:0070739; F:protein-glutamic acid ligase activity
Definition: Catalysis of the posttranslational transfer of a glutamate residue to the gamma-carboxyl group(s) of one or more specific glutamate residues on a target protein.
Catalytic reaction: ATP + L-glutamate + L-glutamyl-[protein] = ADP + H(+) + L-gamma-glutamyl-L-glutamyl-[protein] + phosphate [Rhea:60144]
Source: PMID: 32747782; UniProt: TTLL4 (Q80UG8)

Name:Protein-glutamic acid ligase activity, elongating
Ontology: Molecular_function
Child of GO:0070739; F:protein-glutamic acid ligase activity
Definition: 
Catalysis of the posttranslational transfer of one or more glutamate residues to a glutamate residue covalently attached to the gamma-carboxyl group of a glutamate residue on a target protein, resulting in the elongation of a polyglutamate side chain.
Catalytic reaction :(L-glutamyl)n-L-gamma-glutamyl-L-glutamyl-[protein] + ATP + L-glutamate = (L-glutamyl)n+1-L-gamma-glutamyl-L-glutamyl-[protein] + ADP + H(+) + phosphate [Rhea:60148]
Source: PMID: 32747782; UniProt: TTLL6 (A4Q9E8)

Thank you,
Lucille

**Comment by hdrabkin** [comment]
[Term]
+id: GO:0106437
+name: protein-glutamic acid ligase activity, initiating
+namespace: molecular_function
+def: "Catalytic reaction: ATP + L-glutamate + L-glutamyl-[protein] = ADP + H(+) + L-gamma-glutamyl-L-glutamyl-[protein] + phosphate." [PMID: 32747782, Rhea:60144]
+xref: Rhea:60144
+is_a: GO:0070739 ! protein-glutamic acid ligase activity
+property_value: creation_date 2022-10-21T21:11:47Z xsd:dateTime
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21309 xsd:anyURI
+created_by: hjd
+
+[Term]
+id: GO:0106438
+name: protein-glutamic acid ligase activity, elongating
+namespace: molecular_function
+def: "Catalytic reaction :(L-glutamyl)n-L-gamma-glutamyl-L-glutamyl-[protein] + ATP + L-glutamate = (L-glutamyl)n+1-L-gamma-glutamyl-L-glutamyl-[protein] + ADP + H(+) + phosphate." [PMID: 32747782, Rhea:60148]
+xref: Rhea:60148
+is_a: GO:0070739 ! protein-glutamic acid ligase activity
+property_value: creation_date 2022-10-21T21:15:15Z xsd:dateTime
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21309 xsd:anyURI
+created_by: hjd

**Comment by hdrabkin** [comment]
Appologies. Somehow this slipped by me.
