### ISSUE TITLE
GO:0016830 carbon-carbon lyase activity xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21317]
[Term]
id: GO:0016830
name: carbon-carbon lyase activity
namespace: molecular_function
def: "Catalysis of the cleavage of C-C bonds by other means than by hydrolysis or oxidation, or conversely adding a group to a double bond." [GOC:jl]
synonym: "other carbon-carbon lyase activity" NARROW []
xref: EC:4.1.-.-
xref: Reactome:R-HSA-389611 "2-hydroxyphytanoyl-CoA => pristanal + formyl-CoA"
xref: RHEA:25355
is_a: GO:0016829 ! lyase activity

The RHEA (https://www.rhea-db.org/rhea/25355) and Reactome xrefs here shouldn't be on this relatively high level grouping term.
Those xrefs might belong on a new child of  GO:0106359 2-hydroxyacyl-CoA lyase activity??

**Comment by balhoff** [comment]
I think the Rhea xref was just fixed in #21287. @hdrabkin does anything need to be done with the Reactome xrefs?

**Comment by sjm41** [comment]
Ah, excellent!  I missed that. (I was also going to mention that "EC:4.1.2.- mapped to 5 leaf node reactions" but I see that @hdrabkin is also sorting that out in that ticket.  Funny coincidence.....

**Comment by hdrabkin** [comment]
@deustp01 , how does the reactome id get linked to a grouping term? is this ok with you guys.

**Comment by deustp01** [comment]
> @deustp01 , how does the reactome id get linked to a grouping term? is this ok with you guys.

The Reactome curator used a GO term, here [carbon-carbon lyase activity (GO:0016830)](https://www.ebi.ac.uk/QuickGO/term/GO:0016830). Looking at the reaction now, I wonder if we could have used on of the children of GO:0016830 to get a better fit to the reaction we were annotating, but there are no firm curation standards for this and the use of GO:0016830 is legal. The Rhea cross-reference displayed on our [web page for the reaction](https://reactome.org/PathwayBrowser/#/R-HSA-389611) is generated somehow as part of the release process - it's not part of manual curation.

So, to answer your specific narrow question, the current arrangement is fine with us, but to answer the larger one of whether this is the optimal mapping or an optimal strategy for generating mappings, I don't know, quite possibly not.

@sjm41 If you've just reviewed this Reactome reaction and see a GO term child of GO:0016830 that would be a more exact fit to our reaction, I'm happy to make the edit; just don't have the bandwidth now to dig into this myself to sort out the chemistry.

**Comment by hdrabkin** [comment]
Thanks @deustp01 ; just wanted to be sure that this doesn't mean I have to do any comprehensive cross-checking!
