### ISSUE TITLE
NTR: Protein monoglycylation

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#21312]
Hello,
I would like to request the following term
Name: Protein monoglycylation
Ontology: Molecular_process
Definition: The addition of a single glycyl residue covalently bound to the gamma carboxyl group peptidyl-glutamic acid.
Parent GO:0018200; peptidyl-glutamic acid modification
Source: PMID: 19524510;  in Fig3. : “…we show that the human elongating glycylase TTLL10 is functionally inactive due to two mutations, resulting in the absence of polyglycylation in sperm.” ; UniProt: TTLL3_HUMAN (Q9Y4R7) and TTLL8_HUMAN (A6PVC2)

Thank you,
Lucille

**Comment by pgaudet** [comment]
Note - this is related to #21309


Hi @LucillePo 

There is no Molecular_process  ontology. From the parent you suggest, it sounds like you are looking for Biological process. 
If that's the case, we would not add this term as a process. 

I think the paper describes a glycylase activity - the GO term would be 'protein-glycine ligase activity'

Thanks, Pascale

**Comment by LucillePo** [comment]
Hello Pascale,

I am in fact requiring a Biological process, sorry for the confusion

The one currently used in GO for UniProt: TTLL3_HUMAN (Q9Y4R7) and TTLL8_HUMAN (A6PVC2)  is **GO:0018094; P:protein polyglycylation** which is wrong because human can't perform polyglycylation as mentioned in the Pubmed paper PMID: 19524510; in Fig3. : “…we show that the human elongating glycylase TTLL10 is functionally inactive due to two mutations, resulting in the absence of polyglycylation in sperm.”
A glycylase activity is in fact demonstrated but not in the context of a polyglycylation process.

Thank you,
Lucille

**Comment by hdrabkin** [comment]
So one could annotation the human protein to 
NOT GO:0018094; P:protein polyglycylation  based on missing residues (IMR
    Inferred from missing residues)?

**Comment by LucillePo** [comment]
Hello,
Thank you for the suggestion, in fact it seems to be the best way to annotate theses human monoglycylases.
Lucille

**Comment by pgaudet** [comment]
I think there is no action needed. Closing.
