### ISSUE TITLE
NTRs: 2-hydroxy-(d)ATP hydrolase activites

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#21311]
From pathways2GO mapping attempt for Reactome reactions [R-HSA-2395872](https://reactome.org/content/detail/R-HSA-2395872) and [R-HSA-2395818](https://reactome.org/content/detail/R-HSA-2395818) - see ticket https://github.com/geneontology/pathways2GO/issues/130, could we have two new terms, please:

term 2-hydroxy-ATP hydrolase activity
def: Catalysis of the reaction: 2-hydroxy-ATP + H2O = 2-hydroxy-AMP + diphosphate.
rhea: new reaction
ref: PMID:11139615
is_a parent: GO:0016818

and

term 2-hydroxy-dATP hydrolase activity
def: Catalysis of the reaction: 2-hydroxy-dATP + H2O = 2-hydroxy-dAMP + diphosphate.
RHEA:31583
ref: PMID:11139615
is_a parent: GO:0016818
MISTAKE - this term already exists: GO:0008828 "dATP pyrophosphohydrolase activity" - Catalysis of the reaction: deoxy-ATP + H2O = dAMP + diphosphate. PMID:11139615 NO - existing term is for dATP; we need 2-OH-dATP

**Comment by ukemi** [comment]
@pgaudet I'm not sure @deustp01 and I should be people assigned here. Shouldn't it be an ontology editor?

**Comment by pgaudet** [comment]
@deustp01 assigned you ; I thought you wanted to take this one. I'll remove you if you prefer.

**Comment by ukemi** [comment]
Please. I haven't actually edited in many months.

**Comment by deustp01** [comment]
> @deustp01 assigned you ; I thought you wanted to take this one. I'll remove you if you prefer.

Sorry about assigning David - my mistake. I've never edited the ontology - only perched on the sidelines and commented. I'm happy to continue to comment, and in particular if there are chores needed to get the request into shape for routine generation of a new ontology term, let me know. @ukemi should I make a request to Rhea for a new reaction to go with the first term and if so, is there a Rhea reaction request accessible someplace to use as a model?

**Comment by ukemi** [comment]
No worries. This is a good question that should be addressed at today's ontology call. To me it is part of the Rhea workflow.

**Comment by pgaudet** [comment]
Hi @deustp01 

Before creating the new term - did you see GO:0008828 dATP pyrophosphohydrolase activity 
def: Catalysis of the reaction: deoxy-ATP + H2O = dAMP + diphosphate.
RHEA:31583 
EC:3.6.1.56 2-hydroxy-dATP diphosphatase

Are those the same?

**Comment by pgaudet** [comment]
sorry - I guess not - deoxy versus hydroxyl

**Comment by pgaudet** [comment]
RHEA:31583 maps to GO:0008828 dATP pyrophosphohydrolase activity 
def: Catalysis of the reaction: deoxy-ATP + H2O = dAMP + diphosphate.

**Comment by deustp01** [comment]
In order to ask for a reaction from Rhea, we need ChEBI terms for 2-hydroxy-ATP and 2-hydroxy-AMP, and for 2-hydroxy-dATP and 2-hydroxy-dAMP, each in the correct charge state for the predominant charge species at pH 7.3 (ATP(4-) and AMP(2-)). There are ChEBI terms for CHEBI:77897 - 2-hydroxy-dATP(4−) and CHEBI:63212 - 2-hydroxy-dAMP(2−) but the only terms for 2-hydroxy-ATP  and 2-hydroxy-AMO are CHEBI:65119 - 2-hydroxy-ATP (0 charge) and CHEBI:65129 - 2-hydroxy-AMP (no charge), so first we need to get those terms.

**Comment by pgaudet** [comment]
@deustp01 

Peter - did you see my question above: for the second term you request, with xref RHEA:31583 - that xref is already assigned to  GO:0008828 (citing the same paper). Isn't it the same reaction?

**Comment by deustp01** [comment]
> Peter - did you see my question above

Yes, but that won't work (I thought there was an additional comment from you that did not make it onto this ticket. RHEA:31583 / GO:0008828 are for the pyrophosphorolysis of dATP; the new term is needed for the parallel reaction but with the 2-hydroxy derivative of dATP as input, so a sibling of GO:0008828.

BUT in trying to say what is right here, I have gotten deeply confused about the structures of all of these molecules - when I compare [CHEBI:61404 - dATP(4-)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:61404) and [CHEBI:77897 - 2-hydroxy-dATP(4−)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:77897) I'm seeing double-bonded oxygens where I expect hydroxyl groups and hydroxyl groups on the sugar moieties where I expect nothing, probably because I've forgotten some really basic feature of nucleotide chemistry, so it's back to the biochemistry 101 textbook unless @hdrabkin can sort this out.

**Comment by deustp01** [comment]
OK. Base confusion resolved, and the sugar moieties now look OK.

So back to @pgaudet , we need a new GO term corresponding to [RHEA:31583](https://www.rhea-db.org/rhea/31583) for hydrolysis of 2-hydroxy-dATP [deoxyribo], and also both a Rhea reaction and a new GO term for the hydrolysis of 2-hydroxy-ATP [ribo], once the ChEBI terms for the correct charged states of 2-hydroxy-ATP(4-) and 2-hydroxy-AMP(2-) become available.

I think I have this sorted out, finally - apologies for the missteps!

**Comment by pgaudet** [comment]
So, there will be two terms for the same RHEA? 
or is  GO:0008828 not correctly labeled/defined?

**Comment by deustp01** [comment]
> So, there will be two terms for the same RHEA?
> or is GO:0008828 not correctly labeled/defined?

No. The available RHEA reaction describes hydrolysis of hydroxy-dATP (deoxynucleotide); a new RHEA reaction is needed for the hydrolysis of 2-hydroxy-ATP (ribonucleotide). GO:0008828 is correctly defined to match RHEA:31583, so there is a mistake in the original term request. We only need a term for hydrolysis of 2-hydroxy-ATP (ribonucleotide).

ChEBI just created the needed chemical entities (https://github.com/ebi-chebi/ChEBI/issues/4071) so I will now request a RHEA reaction. Apologies for the confusion!

**Comment by alanbridge** [comment]
it's ok Peter the Rhea is in the capable hands of @amorgat

**Comment by amorgat** [comment]
RHEA:67392 created with the requested [CHEBI:169970](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:169970) and [CHEBI:169971](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:169971)
2-hydroxy-ATP + H2O = 2-hydroxy-AMP + diphosphate + H+
RHEA:67392 will be publicly available on July 28 2021 (Rhea release 120).

**Comment by deustp01** [comment]
@pgaudet putting all the pieces together -

NTR
term 2-hydroxy-ATP hydrolase activity
def: Catalysis of the reaction: 2-hydroxy-ATP + H2O = 2-hydroxy-AMP + diphosphate.
RHEA:67392
ref: PMID:11139615
is_a parent: GO:0016818

The new term should be a sibling of GO:0008828

Thanks (this ontology editing stuff is hard!)

**Comment by deustp01** [comment]
@pgaudet more confusion. GO:0008828 is Catalysis of the reaction: deoxy-ATP + H2O = dAMP + diphosphate. PMID:11139615. The two reactions that started this whole thread involve the hydrolysis of ATP and dATP where the purine has been modified by the addition of an -OH group, so in fact we need the new term in the previous comment and also this new term (copied from the top of the thread):

term 2-hydroxy-dATP hydrolase activity
def: Catalysis of the reaction: 2-hydroxy-dATP + H2O = 2-hydroxy-dAMP + diphosphate.
RHEA:31583
ref: PMID:11139615
is_a parent: GO:0016818

**Comment by hdrabkin** [comment]
RHEA:31583 is already used for GO:0044714; dATP pyrophosphohydrolase activity; Catalysis of the reaction: deoxy-ATP + H2O = dAMP + diphosphate.
BUT THE RHEA rxn has 2-hydroxy dATP; So I would remove the RHEA  from GO:0044714

RHEA:67392 is not public yet?

**Comment by deustp01** [comment]
> RHEA:67392 is not public yet?
Anne noted, when she created the Rhea reaction two days ago, "RHEA:67392 will be publicly available on July 28 2021 (Rhea release 120)."

**Comment by hdrabkin** [comment]
@deustp01 do you agree with my proposal to remove the RHEA from GO:0044714?

**Comment by hdrabkin** [comment]
NTRs
+id: GO:0106377
+name: 2-hydroxy-ATP hydrolase activity

+id: GO:0106378
+name: 2-hydroxy-dATP hydrolase activity

++++++++++
AND RHEA removed from  GO:0044714

**Comment by deustp01** [comment]
New GO terms propagated into Reactome reactions. Thanks

**Comment by lbreuza** [comment]
Hi Peter,
I was about to curate that paper in GOA and to request the missing GO terms described above. Happy to see it is already done. You said the GO terms were already propagated in Reactome but I am not sure what it implies? Does it mean you have curated the paper in the GO database and that I should not do it (it is not yet visible in Protein2GO)?
Thanks for letting me know.

**Comment by deustp01** [comment]
> the GO terms were already propagated in Reactome

What I meant is that the Reactome curation tool lets me create local versions of the two new GO terms even though these have not yet been released. This is safe for us because we have a release-time QA script that checks all the GO terms we have used against the definitive GO set, so any local errors get flagged and sent back to the curator to be fixed.
