### ISSUE TITLE
2-hydroxyacyl-CoA lyase activity (GO:0106359) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21318]
This term:

id: GO:0106360
name: 2-hydroxy-3-methylhexadecanoyl-CoA lyase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-hydroxy-3-methylhexadecanoyl-CoA = 2-methylpentadecanal + formyl-CoA." [RHEA:25379]
xref: RHEA:25379
is_a: GO:0106359 ! 2-hydroxyacyl-CoA lyase activity

is linked to EC 4.1.2.n2 (2-hydroxyphytanoyl-CoA lyase) in RHEA (https://www.rhea-db.org/rhea/25379)
Which suggests that it should be a descendent of "aldehyde-lyase activity (GO:0016832, xref: EC:4.1.2.-).
But it's not.

Maybe its immediate parent term should have its is_a parent changed to "aldehyde-lyase activity (GO:0016832)"?:
id: GO:0106359
name: 2-hydroxyacyl-CoA lyase activity
namespace: molecular_function
def: "Catalysis of the reaction: A 2-hydroxyacyl-CoA = formyl-CoA + a propanol." [PMID:21708296, PMID:28289220]
is_a: GO:0016830 ! carbon-carbon lyase activity

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks.
