### ISSUE TITLE
Term request: syncitial tegument

### ISSUE THREAD

**Issue by mberriman** [geneontology/go-ontology#21332]
Definition:
Cytoplasmic syncytium that forms the outer surface of a multicellular organism.  Found in all members of Neodermata, which includes tapeworms and flukes.

examples:
PMID: 25176442; PMID: 7376694

**Comment by krchristie** [comment]
I'm not entirely sure this is in scope as a cellular component term. For example, while we talk about hyphal development in GO, the term "hypha", another multinucleate structure, is a Fungal Anatomy Ontology (FAO) term:

> ID: FAO:00010001
Name: hypha
Def: A long, branching filamentous structure formed by a vegetatively growing fungus. 

@pgaudet @cmungall @ukemi thoughts? Discuss at next call?

**Comment by pgaudet** [comment]
Discussion on ontology call: 
- how is this intended to be used? 
- can this be requested from CL? 
- @raymond91125 could perhaps be added to Worm anatomy ontology

**Comment by krchristie** [comment]
Hi @mberriman 

We discussed your request at this morning's ontology editors' call. We were wondering if this is something you would want to use for GO cellular component annotations. 

We think this kind of structure is probably best dealt with by an anatomy vocabulary similar to the Fungal Anatomy Ontology. Towards that option, @raymond91125 said that WormBase already interacts with the parasite group, this might be something WormBase could help develop.

However, if there is a current annotation need for this term and no other place for it now, we'll go ahead and make this term in GO. If an anatomy ontology for Neodermata is developed, this term could be represented there as a component, and GO could still represent processes such as "development of syncitial tegument".

If we need to put this term in GO now, do you have any thoughts about what kind of structure it is in GO. I'm not sure where it would belong in the ontology. The most similar thing I can think of if fungal hypha, but as already stated, GO doesn't contain a cellular component term for this structure.

Thanks,

-Karen

**Comment by pgaudet** [comment]
@mberriman 

* We believe this is a type of cell; maybe this could be a child of UBERON:0002199  integument? The Uberon tracker is here: https://github.com/obophenotype/uberon/issues
* Or maybe this is a cell type? In this case you could request from the [CL ontology](https://github.com/obophenotype/cell-ontology/issues) 


Thanks, Pascale
