### ISSUE TITLE
Taxon constraint GO:0032775 | DNA methylation on adenine

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21330]
GO:0032775 | DNA methylation on adenine |

please add never in yeast

**Comment by ValWood** [comment]
Probably it should go on 
GO:0044728    DNA methylation or demethylation

(I am not sure about fungi in general, but probably applies to all...)

**Comment by pgaudet** [comment]
OK - there are only 2 annotations in Fungi, using NOT. I'll put the taxon constraint on Fungi for now. 

Maybe @thomaspd has other suggestions? 

Thanks, Pascale

**Comment by ValWood** [comment]
It seems that some phytopathogenic fungi seem to have DNA methylation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7074731

so maybe only put the taxon restriction on  the Saccharomyces and schizosaccharomyces where it is fairly conclusive that they don't.

**Comment by pgaudet** [comment]
OK, fixed.
