### ISSUE TITLE
GO:0005671 | Ada2/Gcn5/Ada3 transcription activator complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21335]
GO:0005671 | Ada2/Gcn5/Ada3 transcription activator complex
A multiprotein complex that possesses histone acetyltransferase and is involved in regulation of transcription. Contains either GCN5 or PCAF in a mutually exclusive manner. The budding yeast complex includes Gcn5p, two proteins of the Ada family, and two TBP-associate proteins (TAFs); analogous complexes in other species have analogous compositions, and usually contain homologs of the yeast proteins. Both ATAC- or SAGA (see GO:0000124, SAGA complex) are involved in the acetylation of histone H3K9 and K14 residues. PMID:10637607

From, Dom Helmlinger:

This GO annotation relates to the ATAC complex, which does not contain “two TBP-associate proteins (TAFs)”.

To answer your question, no, yeasts do not have an ATAC complex (see for example this: Helmlinger D and Tora L, Trends in Biochemical Sciences, 2017, PMID: 28964624). ATAC and SAGA share many subunits, including those forming the HAT module (Gcn5, Ada2, Ada3, and Sgf29). However, metazoans such as flies and mammals have duplicated the ada2 gene, giving rise to two paralogs, Ada2a and Ada2b. Each is specific to either the ATAC complex, which contains Ada2a, or the SAGA complex, which specifically has Ada2b.

Both S. cerevisiae and S. pombe have only one ada2 gene and no orthologs of the subunits that are specific to ATAC (eg ZZZ3, ATAC2, HCF1, WDR5,YEATS2, NC2-beta, and MBIP in humans).

 
Val: It seems  this term has been used to describe the  submodule in S. cerevisiae (which should be only SAGA?), and the ATAC complex in human 
Suggest, redefining clearly as ATAC, and adding a taxon restriction for yeast

**Comment by ValWood** [comment]
@bmeldal 

Essentially there is an 
ADA module in yeast, which contains just Gcn5, Ada2, and Ada3 of SAGA, as well as two specific components Ahc1 and Ahc2.

However, there does not seem to be any evidence of an ADA sub-complex

The ATAC is a SAG-like complex and is not present in yeast.

**Comment by bmeldal** [comment]
I had a look back at our curation as well as the above mentioned papers etc and according to

PMID:28964624 (review of all SAGA-related HAT complexes)

PMID:21734642 (evidence for scADA complex) (also very old PMID:10490601)

PMID:19936620 (evidence for hATAC/SAGA)

PMID:22426530 (review for hATAC/SAGA)

I think there are 3 distinct complexes: 

ADA: only in Saccharomyces cerevisiae

ATAC: only higher eukaryotes, incl drome, mouse, human

SAGA: pretty much everywhere from yeast to human

I think `GO:0005671 Ada2/Gcn5/Ada3 transcription activator complex` therefore needs to be split again into ADA and ATAC. If you look into the history, it was first added for yeast ADA, and then changed to include ATAC.

If you agree, I can suggest new defs.

Will require re-annotation...

NB: We also need to highlight that ATAC and SAGA can have GCN5 or PCAF as their mutually exclusive HAT. (We only have SAGA with GCN5 at the moment as the review came out after we curate this, I'll put those updates on my to do list)

**Comment by pgaudet** [comment]
I think that was a question for you @ValWood ?

**Comment by ValWood** [comment]
Yes I think you are right @bmeldal  it is 2 different complexes merged together.

I would obsolete the original, because it must be used incorrectly. If you can suggest new defs, I can get them checked by a SGA expert.

v

**Comment by bmeldal** [comment]
1.

**GO:NEW1 ADA complex**

Synonyms: 
Ada2/Gcn5/Ada3 transcription activator complex [EXACT]
ADA histone acetyltransferase complex [EXACT]
ADA HAT complex [EXACT]
scADA [NARROW]

Def:
A chromatin remodelling complex that regulates transcription via acetylation primarily of nucleosomal histones H3 and H2B. In budding yeast shares the histone acetylation (HAT) module of ADA2-GCN5-NGG1-SGF29 with the related SAGA complex (GO:0000124). 

*NB: I have the feeling, ADA is restricted to budding yeast.*

Refs:
PMID:21734642
PMID:28966424

Relationship:
is_a GO:0070461 SAGA-type complex

GOCID:bhm

2.

**GO:NEW2 ATAC complex**

Synonyms:
ADA2A-containing complex
KAT2A-containing ATAC complex
KAT2B-containing ATAC complex
G-ATAC complex [EXACT]
Ada two A containing complex [EXACT]
Ada-Two-A-containing complex [EXACT]
Ada Two-A containing complex [EXACT]

Def:

A chromatin remodelling complex that regulates transcription via acetylation primarily of nucleosomal histones H3 and possibly H4. Shares the histone acetylation (HAT) module of GCN5/PCAF-ADA2-ADA3-SGF29 (or orthologs) with the related SAGA complex (GO:0000124). Contains HAT subunits GCN5 or PCAF in a mutually exclusive manner. In addition to the HAT module contains DR1/NC2B, KAT14, MBIP, WDR5, YEATS2 and ZZZ3 or orthologs. Also regulates the activity of non-histone targets and orchestrates mitotic progression by regulating Cyclin A degradation through acetylation.

*NB: I have the feeling, ATAC is not present in fission nor budding yeast.*

Refs:
PMID:19936620
PMID:20562830
PMID:28966424

Relationship:
is_a GO:0070461 SAGA-type complex

GOCID:bhm

**Comment by bmeldal** [comment]
SAGA also needs restructuring, working on it with Sandra right now. Will open a separate ticket when we have it all detangled.

**Comment by pgaudet** [comment]
@bmeldal : and pombe would have neither?

**Comment by pgaudet** [comment]
+id: GO:0140671
+name: ADA complex
+namespace: cellular_component
+def: "A chromatin remodelling complex that regulates transcription via acetylation primarily of nucleosomal histones H3 and H2B. In budding yeast shares the histone acetylation (HAT) module of ADA2-GCN5-NGG1-SGF29 with the related SAGA complex." [GOC:bhm, PMID:21734642, PMID:28966424]
+synonym: "ADA HAT complex" EXACT []
+synonym: "ADA histone acetyltransferase complex" EXACT []
+synonym: "Ada2/Gcn5/Ada3 transcription activator complex" EXACT []
+synonym: "scADA" NARROW []
+is_a: GO:0070461 ! SAGA-type complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21335 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-25T11:02:49Z
+
+[Term]
+id: GO:0140672
+name: ATAC complex
+namespace: cellular_component
+def: "A chromatin remodelling complex that regulates transcription via acetylation primarily of nucleosomal histones H3 and possibly H4. Shares the histone acetylation (HAT) module of GCN5/PCAF-ADA2-ADA3-SGF29 (or orthologs) with the related SAGA complex (GO:0000124). Contains HAT subunits GCN5 or PCAF in a mutually exclusive manner. In addition to the HAT module contains DR1/NC2B, KAT14, MBIP, WDR5, YEATS2 and ZZZ3 or orthologs. Also regulates the activity of non-histone targets and orchestrates mitotic progression by regulating Cyclin A degradation through acetylation." [GOC:bhm, PMID:19936620, PMID:20562830, PMID:28966424]
+synonym: "Ada two A containing complex" EXACT []
+synonym: "Ada Two-A containing complex" EXACT []
+synonym: "Ada-Two-A-containing complex" EXACT []
+synonym: "ADA2A-containing complex" EXACT []
+synonym: "G-ATAC complex" EXACT []
+synonym: "KAT2A-containing ATAC complex" EXACT []
+synonym: "KAT2B-containing ATAC complex" EXACT []
+is_a: GO:0070461 ! SAGA-type complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21335 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-25T11:05:14Z

**Comment by pgaudet** [comment]
To do: 

 - [ ] add taxon restrictions on new terms
 - [ ] obsolete  GO:0005671 | Ada2/Gcn5/Ada3 transcription activator complex (next week when new terms are available)

**Comment by ValWood** [comment]
As far as I know ADA is a submodule in (both) yeast, and is not functional independently so we would not represent that in GO. We would only need SAGA for annotation.

**Comment by bmeldal** [comment]
> As far as I know ADA is a submodule in (both) yeast, and is not functional independently so we would not represent that in GO. We would only need SAGA for annotation.

ADA in budding yeast has 2 components that are not found in SAGA: AHC1 & AHC2

**Comment by ValWood** [comment]
From Dom:

    ADA: no evidence that it exists in fission yeast, although no one has specifically looked at this. ADA exists in budding yeast, in which 1-2 additional subunits (Ahc1 and Ahc2) specifically define the ADA complex, together with Gcn5/Ada2/Ada3. Ahc1 and Ahc2 have no orthologs in fission yeast. Nevertheless, a recent paper shows that ADA exists in Drosophila, in which there is also no Ahc1/2 orthologs. In that case, ADA was defined using biochemical fractionation and acetylation assays. The same type of experiments would need to be done in S. pombe to conclude about its existence.
    ATAC is absent from both yeast species (and I think from fungi).

So for now  I think we should block ADA for Schizosccharoyces  species, and ATAC for all yeast.
v

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0005671 | Ada2/Gcn5/Ada3 transcription activator complex. The reason for obsoletion is that it was split into 2 more precise terms:
GO:0140671 ADA complex
"A chromatin remodelling complex that regulates transcription via acetylation primarily of nucleosomal histones H3 and H2B. In budding yeast shares the histone acetylation (HAT) module of ADA2-GCN5-NGG1-SGF29 with the related SAGA complex."
and
GO:0140672 ATAC complex
"A chromatin remodelling complex that regulates transcription via acetylation primarily of nucleosomal histones H3 and possibly H4. Shares the histone acetylation (HAT) module of GCN5/PCAF-ADA2-ADA3-SGF29 (or orthologs) with the related SAGA complex (GO:0000124). Contains HAT subunits GCN5 or PCAF in a mutually exclusive manner. In addition to the HAT module contains DR1/NC2B, KAT14, MBIP, WDR5, YEATS2 and ZZZ3 or orthologs. Also regulates the activity of non-histone targets and orchestrates mitotic progression by regulating Cyclin A degradation through acetylation."

There are 73 EXP annotations, 
- BHF-UCL|12
- FlyBase | 27
- MGI | 16
- SGD | 18
https://github.com/geneontology/go-annotation/issues/3847

There is one InterPro mapping  to IPR037807

This term is not present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on July 26, to leave time for groups to make corrections. Unless objections are received by July 26, 2021, we will assume that you agree to this change.

You may comment on the ticket: geneontology/go-ontology#21335

Thanks, Pascale

**Comment by hattrill** [comment]
I've reviewed FBs - all are updated to ATAC complex. 
Interestly, just found a paper on ADA complex in insects (which the authors call a metazoan ADA complex) https://academic.oup.com/nar/article/47/7/3383/5304717

Tagging @phanivg on this - I've also found an insect-specific HAT complex - CHAT - we might want a new term for this - I'll hand that over to you, Phani ;-) https://pubmed.ncbi.nlm.nih.gov/32735945/

**Comment by bmeldal** [comment]
> I've reviewed FBs - all are updated to ATAC complex.
> Interestly, just found a paper on ADA complex in insects (which the authors call a metazoan ADA complex) https://academic.oup.com/nar/article/47/7/3383/5304717
> 
> Tagging @phanivg on this - I've also found an insect-specific HAT complex - CHAT - we might want a new term for this - I'll hand that over to you, Phani ;-) https://pubmed.ncbi.nlm.nih.gov/32735945/

The plot thickens... that's why I didn't suggest any taxon restraints (apart from ATAC not in yeast and ADA not in pombe). I don't have time to check all cases and the papers I reviewed were only yeast and mammalian based, with references to SAGA in "everything".
