### ISSUE TITLE
Clarify def. of 'electron transfer activity' (GO:0009055)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21334]
Based on discussions in https://github.com/geneontology/go-annotation/issues/3696, we'd like to change the definition of 'electron transfer activity' (GO:0009055) from:

_Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient._

to

_Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors._

Removing that last bit will allow the term to be accurately applied to electron carriers that don't "generate a transmembrane electrochemical gradient" (such as ferredoxins), while maintaining the requirement to act "in an electron transport chain" will continue to stop the term just being used for any dehydrogenase.

@ValWood

**Comment by sjm41** [comment]
Also from https://github.com/geneontology/go-ontology/issues/21275:
@pgaudet said "as far as I remember not all electron transporters results in transport across the membrane"
@kaxelsen replied "This is true. NADP, FAD, FMN, ferredoxin, flavodoxin etc etc can all be considered electron transporters."

**Comment by pgaudet** [comment]
I am not following - this was added on purpose. We dont want NADP, FAD, FMN, ferredoxin, flavodoxin etc to be annotated to this term. 
Otherwise this become synonymous with oxidoreductase activity (as mentioned in the other ticket). Why not annotate ferredoxin & others to oxidoreductase activity or a child? 

Can you say that ferredoxin always generate a electrochemical gradient? It doesn't seem like it, for eg in this paper: 
20547883

**Comment by pgaudet** [comment]
The previous definition (2013) was "Any molecular entity that serves as an electron acceptor and electron donor in an electron transport system." - this led to basically any oxidoreductase being annotated to this term.

**Comment by pgaudet** [comment]
Discussing with @sjm41 
Maybe one solution would be to create a BP term, such as https://en.wikipedia.org/wiki/P450-containing_systems ? 

@ValWood @sarach06

**Comment by pgaudet** [comment]
For the record, we had wanted to obsolete it at some point: #2937

**Comment by pgaudet** [comment]
TO DO: We should add a comment that explains that this term should be used for example for OXPHOS reactions.

**Comment by ValWood** [comment]
> For the record, we had wanted to obsolete it at some point: #2937
I'm not sure that is true. Further down you corrected this to 
electron transporter activity

**Comment by ValWood** [comment]
>Maybe one solution would be to create a BP term, such as https://en.wikipedia.org/wiki/P450-containing_systems ?

 I agree maybe we could lose MF  in favour of process terms.

**Comment by sjm41** [comment]
Hi @pgaudet and @ValWood 

I am thinking of making a new ticket to propose a new BP term along these lines:

name: P450-containing electron transport chain
def: A process in which one or more electron carriers operate to transfer electrons from donors to a cytochrome P450 protein or domain. Electron carriers operating in this chain include FAD-containing flavoproteins or domains, FMN domains, ferredoxins and/or cytochrome b5. The reduced cytochrome P450 functions as the terminal oxidase and participates in a wide range of biochemical pathways. (PMID:16042601, https://en.wikipedia.org/wiki/P450-containing_systems)
is_a: electron transport chain (GO:0022900)

To make the proposed relation work, we'd have to change the def of electron transport chain (GO:0022900) from:
 _A process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient._
>
 _A process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors._

That seems OK to me as the only existing child terms ('respiratory electron transport chain' & 'photosynthetic electron transport chain') specify the "to generate a transmembrane electrochemical gradient" in their defs.  But you may well see other difficulties with this.....

Anyway, shall I make the new ticket and continue the discussion therein?

**Comment by ValWood** [comment]
Sounds good.

**Comment by sjm41** [comment]
@pgaudet I think the only remaining thing to do on this ticket is to add a comment/guidance to "electron transfer activity (GO:0009055)" flagging that it should _only_ be be used for electron transfer that **generates a transmembrane electrochemical gradient**, e.g. components of the respiratory or photosynthetic electron transport chain.

**Comment by pgaudet** [comment]
Added comment: "Note that this term should only be be used for electron transfer that generates a transmembrane electrochemical gradient, e.g. components of the respiratory or photosynthetic electron transport chain."

Thanks for making this easy :)
