### ISSUE TITLE
Proposed new RHEA mappings based on exact matches of reaction to definition

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#21345]
|subject_id|subject_label|object_id|object_label|match_string|
|---|---|---|---|---|
|GO:0120136|dUMP kinase activity|RHEA:30655|ATP + dUMP = ADP + dUDP|atp + dump = adp + dudp|
|GO:1990663|dihydroorotate dehydrogenase (fumarate) activity|RHEA:30059|(S)-dihydroorotate + fumarate = orotate + succinate|(s)-dihydroorotate + fumarate = orotate + succinate|
|GO:0052886|9,9'-dicis-carotene:quinone oxidoreductase activity|RHEA:30959|9,9'-di-cis-zeta-carotene + a quinone = 7,9,9'-tri-cis-neurosporene + a quinol|9,9'-di-cis-zeta-carotene + a quinone = 7,9,9'-tri-cis-neurosporene + a quinol|
|GO:0052929|ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity|RHEA:60012|a tRNA with a 3' CC end + ATP = a tRNA with a 3' CCA end + diphosphate|a trna with a 3' cc end + atp = a trna with a 3' cca end + diphosphate|
|GO:0110153|RNA NAD-cap (NMN-forming) hydrolase activity|RHEA:60876|a 5'-end NAD(+)-phospho-ribonucleoside in mRNA + H2O = a 5'-end phospho-adenosine-phospho-ribonucleoside in mRNA + beta-nicotinamide D-ribonucleotide + 2 H(+)|a 5'-end nad(+)-phospho-ribonucleoside in mrna + h2o = a 5'-end phospho-adenosine-phospho-ribonucleoside in mrna + beta-nicotinamide d-ribonucleotide + 2 h(+)|
|GO:0016995|cholesterol oxidase activity|RHEA:32183|cholesterol + O2 = cholest-5-en-3-one + H2O2|cholesterol + o2 = cholest-5-en-3-one + h2o2|
|GO:0106363|protein-cysteine methyltransferase activity|RHEA:66544|L-cysteinyl-[protein] + S-adenosyl-L-methionine = H(+) + S-adenosyl-L-homocysteine + S-methyl-L-cysteinyl-[protein]|l-cysteinyl-[protein] + s-adenosyl-l-methionine = h(+) + s-adenosyl-l-homocysteine + s-methyl-l-cysteinyl-[protein]|

**Comment by hdrabkin** [comment]
Done
