### ISSUE TITLE
meiotic/mitotic spindle assembly, name changes and new terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21349]
~Would anyone mind  if we renamed to 
spindle assembly and mitotic spindle  assembly to mitotic spindle formation
Formation includes the assembly, but also a period (spindle phase2), when the spindle is maintained at constant length (this is an active process). It seems odd to call this phase 'assembly' but it is part of the process of spindle formation.~

Add a new descendant of 
mitotic spindle assembly
GO:NEW    mitotic spindle formation (spindle phase two)
The spindle organization process in which the spindle is maintained at a constant length during mitotic metaphase.
synonym metaphase spindle stabilization
synonym metaphase spindle stability
PMID:32723864

This is an active process.

**Comment by ValWood** [comment]
and the corresponding meiotic teerm
NEW mieotic spindle formation (spindle phase two)

**Comment by ValWood** [comment]
also

mitotic spindle formation (spindle phase one) -> mitotic spindle elongation (spindle phase one)
matches the def, clearer to describe this phase as elongation

**Comment by mah11** [comment]
> Would anyone mind if we renamed ... spindle assembly to ... spindle formation

What is the distinction between "assembly" and "formation" that this suggestion implies? It will help to make that distinction explicit -- if there is one. Many of the X assembly (where X is some cellular component) have "X formation" as EXACT synonyms, so it's not immediately obvious what swapping the words in term names achieves in general.

> [Spindle] Formation includes the assembly, but also a period (spindle phase2), when the spindle is maintained at constant length (this is an active process). It seems odd to call this phase 'assembly' but it is part of the process of spindle formation.

And specifically for spindles, what definitions of "assembly" and "formation" apply? How can any phase or sub-process be part of formation but not part of assembly? It doesn't make sense to me.


I suppose I don't really have a

**Comment by ValWood** [comment]
I think formation is broader than assembly. Assembly implied the aggregation of parts. Formation  does not necessarily. The spindle is still 'forming' during the phase when it isn't  elongating, but this phase is important for the 'formation' of the spindle.

**Comment by ValWood** [comment]
I think the distinction is that during the static phase when it is important to maintain stability  the spindle is still 'cycling' but it isn't 'elongating'. Components are constantly being added **and removed**  and stability is maintained. This is all an  important part of spindle formation. Maybe it's just me but 'formation' seems to fit better- assembly just seems wrong somehow.

**Comment by mah11** [comment]
Hm, I still don't see a meaningful difference ... to me removal of a part doesn't contradict the concept of "assembly", nor would using the word "formation" make the fit any closer.

**Comment by ValWood** [comment]
Maybe assembly is OK. I see GO defines 'assembly' quite broadly to include arrangement. 
I always think of assembly as only putting together parts, whereas formation can organise preexisting parts or structures. I think. we had this discussion before.  It can be ignored if

mitotic spindle formation (spindle phase two)
can go under "mitotic spindle assembly"

**Comment by pgaudet** [comment]
@ValWood Can you make a list of the changes you are requesting? I'm having a hard time parsing this. 

Thanks!

**Comment by ValWood** [comment]
I removed all the part about the name change, so it's just 2 new term requests.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140641
+name: mitotic spindle formation (spindle phase two)
+namespace: biological_process
+def: "The spindle organization process in which the spindle is maintained at a constant length during mitotic metaphase." [PMID:32723864]
+synonym: "metaphase spindle stability" EXACT []
+synonym: "metaphase spindle stabilization" EXACT []
+is_a: GO:0090307 ! mitotic spindle assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21349 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-11T08:15:15Z
+
+[Term]
+id: GO:0140642
+name: meiotic spindle formation (spindle phase two)
+namespace: biological_process
+def: "The spindle organization process in which the spindle is maintained at a constant length during meiotic metaphase." [PMID:32723864]
+is_a: GO:0090306 ! spindle assembly involved in meiosis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21349 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-11T08:18:16Z
