### ISSUE TITLE
GO:0015420 ABC-type vitamin B12 transporter activity, reaction update

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#21353]
I just looked at this GO and saw that the reaction does not correspond to what we have in Rhea. The Rhea reaction is RHEA:17873 (EC 7.6.2.8)
an alkylcob(III)alamin(out) + ATP + H2O = ADP + an alkylcob(III)alamin(in) + H+ + phosphate

an alkylcob(III)alamin = CHEBI:140785

@deustp01 In Reactome R-HSA-3000238.1, this GO-term is linked to LMBD1. This protein (according to Swiss-Prot Q9NUN5 is not a transporter but a chaperone that targets ABCD4 to the lysosome (pmid:27456980, pmid:25535791 and pmid:33845046). R-HSA-3000238.1 is linked to RHEA:32832, which is wrong

**Comment by alanbridge** [comment]
FYI, RHEA:17874 + EC:7.6.2.8 is now annotated in ABCD4 (internal version) and should be out next release.

**Comment by pgaudet** [comment]
Hi @kaxelsen 
Is this a Reactome issue? 

Because I think current GO mappings are OK, GO:0015420 = EC:7.6.2.8 = RHEA:17873 - right?

**Comment by kaxelsen** [comment]
The cited reaction in the definition does correspond to REHA:17873 (I looked at QuickGO) so that part is also a GO issue

**Comment by pgaudet** [comment]
I fixed the ontology issue. @deustp01 Can you please fix the Reactome annotation? 
Thanks, Pascale

**Comment by deustp01** [comment]
Right. We were relying on the earlier observation that mutations in LMBD1 prevent cobalamin transport. The later papers cited at the top of this ticket show that ABCD4 mediates the transport, which is ATP-driven, and that LMBD1 enables ABCD1 localization to the lysosome. So we need to create a new reaction for LMBD1-mediated ABCD1 localization and change the enabler on the existing cobalamin transport reaction.

**Comment by deustp01** [comment]
Some progress - the reaction that asserted a cobalamin transport function for LMBD1 has been deleted and the one asserting a cobalamin transport function for ABCD4 has been modified to show that an LMBD1:ABCD4 complex mediates this ATP-dependent transport with ABCD4 as the active unit of the complex. These changes will become publicly visible in the Reactome release in June.
Still to do - annotate the formation of the ABCD4:LMBD1 complex and its function to stabilize ABCD4 in the lysosome membrane. These changes involve creation and review of entirely new reactions so, for sanity, will not be made until processing of material for the June release is complete.

**Comment by deustp01** [comment]
The Reactome annotations, both for the normal process [R-HSA-196741](https://reactome.org/content/detail/R-HSA-196741) and a relevant disease counterpart [R-HSA-3359462](https://reactome.org/content/detail/R-HSA-3359462) were fixed a while ago and the fixes have propagated to our public web site (see links), so I will close this ticket.
