### ISSUE TITLE
NTR: sperm mitochondrial sheath assembly

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#21361]
I need a term for sperm mitochondrial sheath assembly for annotation of this paper:

He et al. 2020. Bi-allelic Loss-of-function Variants in CFAP58 Cause Flagellar Axoneme and Mitochondrial Sheath Defects and Asthenoteratozoospermia in Humans and Mice. Am J Hum Genet. 2020 Sep 3;107(3):514-526.  
PMID:32791035

Name: sperm mitochondrial sheath assembly
Def: The assembly and organization of the sperm mitochondrial sheath, the tightly packed helical sheath of ATP-producing mitochondria restricted to the midpiece of the sperm flagellum.

To place it properly, I think I'll also need a term for "sperm flagellum assembly" to be it's direct parent, and also the parent of the existing term "sperm axoneme assembly".

Name: sperm flagellum assembly
Def: The assembly and organization of the sperm flagellum, the microtubule-based axoneme and associated structures that are part of a sperm flagellum (or cilium).

**Comment by krchristie** [comment]
Additional changes:

1. These two relationships above were moved from **sperm axoneme assembly** to its new parent term **sperm flagellum assembly**
< -relationship: part_of GO:0007286 ! spermatid development
< -relationship: part_of GO:0030317 ! flagellated sperm motility

2. I also removed this relationship: **part_of GO:0005929 ! cilium** from the term **sperm mitochondrial sheath** because it is redundant with this relationship: **part_of GO:0036126 ! sperm flagellum** since a **sperm flagellum* is_a type of **cilium**

[Term]
id: GO:0097226
name: sperm mitochondrial sheath
namespace: cellular_component
def: "The tightly packed helical sheath of ATP-producing mitochondria restricted to the midpiece of the sperm flagellum." [GOC:cjm, MP:0009832]
is_a: GO:0110165 ! cellular anatomical entity
relationship: part_of CL:0000019 ! sperm
~relationship: part_of GO:0005929 ! cilium~
relationship: part_of GO:0036126 ! sperm flagellum
created_by: pr
creation_date: 2012-01-25T01:25:08Z

**Comment by krchristie** [comment]
@cmungall & @balhoff 

It seems to me that it is redundant to say this:
- relationship: part_of CL:0000019 ! sperm

in addition to this:
- relationship: part_of GO:0036126 ! sperm flagellum

since a "**sperm flagellum**" is already part_of a "sperm" by definition.

I tested removing the relationship to the CL term sperm from the term "**sperm mitochondrial sheath**", and when I reran the reasoner, I didn't see "part of sperm" as an inferred relationship, so I wasn't sure if we make inferences like this out to cell type terms as well as GO terms. 

I put the relationship back, but I wanted to ask if it is necessary or not.

[Term] 
id: GO:0097226
name: sperm mitochondrial sheath
namespace: cellular_component
def: "The tightly packed helical sheath of ATP-producing mitochondria restricted to the midpiece of the sperm flagellum." [GOC:cjm, MP:0009832]
is_a: GO:0110165 ! cellular anatomical entity
**relationship: part_of CL:0000019 ! sperm**
relationship: part_of GO:0036126 ! sperm flagellum

**Comment by balhoff** [comment]
@krchristie it is redundant, and doesn't need to be there. If you take a look at the released `go.owl` file, you'll see that it gets removed by the ontology build, because it is found to be redundant. I would delete it.
