### ISSUE TITLE
NTR:  cAMP relay during early sorocarp development

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#21369]
I would like to add a child to the new Dicty term
GO:0140582 adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway

I would like to add a child that describes the cAMP relay
cell: cAMP biosynthetic process - > cAMP export to extracellular - > binds to cAMP receptor of other cells, which then activates adenylate cyclase to produce more cAMP and the signal is relayed, visible as waves in dark field microscopy; excited cells undergo a refractory period, also external PDE breaks down cAMP. All this generates 6 minute cAMP oscillations during aggregation.

GO:0140582 adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
----  New term: cAMP relay during early sorocarp development (or cAMP signal relay...)
Def: cAMP induces other cells to produce cAMP which is part of 6 minute cAMP oscillations during aggregation in early sorocarp development. 
sensu Dictyosteliia

thanks!

**Comment by pgaudet** [comment]
Hi @pfey03 

The definition doesn't work- GO describes the function of gene products, this is phrased to describe the function of cAMP. 
Isn't the cAMP relay a part of the 'adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway' ? 

The new term is requested as a child of  GO:0140582 adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway, as if it was a type of adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway, but I think it's a part? 

(We should chat at some point to resolve your open tickets). 

Thanks, Pascale

**Comment by pfey03** [comment]
Hi @pgaudet, 
I know it's difficult and yes it's part of this signaling. Some of this is driven because I work a lot in UPHenO, and need to patternize all our phenotypes. I have already changed the pheno ontology so much, but some phenotypes I don't want to obsolete or change as phenotypes do describe these things in detail and the researchers do. And not all can be solved by new patterns. I have a new pattern to keep 'development arrests at developmental stage' (created stage ontology), as this also helped others. 

It's super challenging so I sometimes try to get a new GO term that would retain the phenotypes, but often I have to change them and obsoleted a lot that were compound processes. I'm also planning to add extensions to phenotypes in new database but it's a not coming so soon. Just so you know where I'm coming from. 

Thanks, Petra

**Comment by pfey03** [comment]
@pgaudet what about 'cAMP wave formation' and something about relay in the def?

**Comment by pfey03** [comment]
@pgaudet is this still going anywhere? there is no equivalent terms really as it's not simply the extracellular cAMP signaling and researchers differentiate

**Comment by pfey03** [comment]
@pgaudet I don't think this is going anywhere I'm now trying to solve it otherwise. closing issue

**Comment by dosumis** [comment]
> The definition doesn't work- GO describes the function of gene products, this is phrased to describe the function of cAMP.

The biological processes @pfey03 is asking for involve the action (function) of multiple gene products.  They also involve physical processes, such as the diffusion of small molecules (cAMP), but don't many GO BPs?  The overall process is more than just signalling - that ignores the oscillations within single cells and the relay between cells and the gene product activity that underly them (https://www.youtube.com/watch?v=LJ98bkWZA40).

**Comment by pfey03** [comment]
@dosumis - Yes of course it involves several gene products. And yes, it's signal and response to signal. 

So then let's do a pattern that would help.

**Comment by pgaudet** [comment]
Lets keep it open then. (Sorry @pfey03 I have on my to-do list to answer to your tickets - I'm on ATPases this week, if I cannot answer today I'll do it Monday. 

Thanks, Pascale

**Comment by pfey03** [comment]
@pgaudet, thank you!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140676
+name: cAMP oscillatory signaling
+namespace: biological_process
+def: "Fluctuation in the extracellular cAMP levels due to the alternate activation of adenylate cyclase, which produces cAMP, and phosphodiesterase, which degrades it. Occurs in Dictyostelium during early sorocarp development. Oscillation in signaling result is directional chemotaxis of cells towards the center of the aggregate." [PMID:18657484]
+synonym: "cAMP relay" EXACT []
+is_a: GO:0007267 ! cell-cell signaling
+relationship: has_part GO:0004016 ! adenylate cyclase activity
+relationship: has_part GO:0004115 ! 3',5'-cyclic-AMP phosphodiesterase activity
+relationship: has_part GO:0140582 ! adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21369 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-29T14:14:39Z
