### ISSUE TITLE
ontology error - SMAD signaling is part of TGFB signaling 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21372]
Hi 
three issues here

1. SMAD signaling GO terms ( GO:0060389 pathway-restricted SMAD protein phosphorylation and  GO:0060395 SMAD protein signal transduction) are part of TGFB signaling pathway, however I assume that TGFB1 (and TGFB receptors) should be curated as positively regulating SMAD signaling as well as being part of TGFB signaling pathway. But this then means that TGFB1 (and receptors) are curated as both involved in and regulating  GO:0007178 transmembrane receptor protein serine/threonine kinase signaling pathway.
> do the SMAD signaling terms have to be listed as part of the receptor signaling pathways?

2. The two SMAD signaling GO terms: GO:0060389 pathway-restricted SMAD protein phosphorylation and  GO:0060395 SMAD protein signal transduction are not related in the ontology (see QuickGO image attached). Isn't that a bit odd? Would it be appropraite to just change the phosphorylation term to: pathway-restricted SMAD signal transduction then add a new parent:
GO:0060395 SMAD protein signal transduction
>is_a child pathway-restricted SMAD signal transduction
And remove all the phosphorylation parents? The TGFB signaling pathway is not associated with phosphorylation.
![Comparison chart for GO 0060391,GO 0010862,GO 0007179](https://user-images.githubusercontent.com/12080010/116689902-8ffd1c00-a9b0-11eb-9ca0-20a90945c063.png)

3. The definition for  GO:0060395 SMAD protein signal transduction could be improved to add a start and end of the process, new definition eg:
The cascade of processes by which a signal interacts with a receptor, causing a change in the activity of a SMAD protein, and ultimately effecting a change in the functioning of the cell. The process starts with the activated SMAD and ends with the regulation of transcription.

Thanks

Ruth

**Comment by RLovering** [comment]
Hi
this issue was raised again by a student. It occurred to me (following all these signaling discussions) that it is more important to capture the impact on the signaling pathway rather than the modification status (which is the experimental data). I do not know if phosphorylation of SMAD always leads to activation of the pathway which maybe why these 2 child terms are not linked?
Perhaps the regulation of SMAD phosphorylation terms should be removed?
Ruth

**Comment by pgaudet** [comment]
Thanks for bringing this up. Based on our guidelines for what is a MF versus what is a BP, we should obsolete all 4 terms: 
* GO:0060389 pathway-restricted SMAD protein phosphorylation
* GO:0060393 regulation of pathway-restricted SMAD protein phosphorylation 
* GO:0060394 negative regulation of pathway-restricted SMAD protein phosphorylation
* GO:0010862 positive regulation of pathway-restricted SMAD protein phosphorylation

That's 132 EXP annotations - 
(81)	BHF-UCL
(24)	UniProt
(15)	ZFIN
(6)	ComplexPortal
(3)	FlyBase
(2)	ARUK-UCL
(1)	RGD

**Comment by RLovering** [comment]
Hi Pascale Most of the definition I suggested was already present. Based on the G protein definition

Perhaps this would be better:
The series of molecular signals initiated by a ligand binding to a TGF-B superfamily receptor, in which the activated receptor promotes the activation of a receptor-regulated SMAD (R-SMAD). The activated R-SMAD then dissociates from the receptor and binds a common partner SMAD (Co-SMAD, SMAD4 in humans). The R-SMAD/co-SMAD complex then enters the nucleus and binds to its target genes to regulate transcription. The pathway starts with the activated R-SMAD and ends with the regulation of transcription. 

Plus add the Annotation Guidance the TGF-B superfamily receptor positively regulates SMAD protein signal transduction, whereas the inhibitory SMADs (I-SMADs) negatively regulate SMAD protein signal transduction

However, according to the Annotation Guidance I have suggested above there will need to be added a lot more annotation revisions so that the TGF-B superfamily receptors are annotated as regulating SMAD protein signal transduction, currently many of these receptors are associated with the SMAD protein signal transduction term

Best

Ruth

**Comment by pgaudet** [comment]
WRT comment 1 above: 
https://github.com/geneontology/go-ontology/issues/21372#issue-872373683
SMAD protein signal transduction
'part of' some 'transmembrane receptor protein serine/threonine kinase signaling pathway' - I think this is right. 
Although the MF of the TGF receptor and it ligand regulate the activity of the first SMADs, I think we have agreed that SMAD is part of the TGF/BMP/activin pathways.

Thanks, Pascale

**Comment by pgaudet** [comment]
We are getting rid of 'pathway restricted SMAD protein phosphorylation', see https://github.com/geneontology/go-ontology/issues/25531

So, no action needed here.
