### ISSUE TITLE
NTR: 18S rRNA aminocarboxypropyltransferase activity (& children)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21373]
This is nicely defined in this InterPro entry:
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR022968/
This entry represents 18S rRNA aminocarboxypropyltransferases Tsr3 and its homologues. Tsr3 from fungi and animals are responsible for 18S rRNA hypermodification. It introduces the acp group to the hypermodified m1acp3psi nucleotide at position 1191 (yeast)/ 1248 (humans) of 18S rRNA. The crystal structure of archaeal Tsr3 homologues revealed the same fold as in SPOUT-class RNA-methyltransferases but a distinct SAM binding mode. This unique SAM binding mode explains why Tsr3 transfers the acp and not the methyl group of SAM to its substrate. Structurally, Tsr3 therefore represents a novel class of acp transferase enzymes [PMID: 27084949 ].

Yeast TSR3 is annotated with RHEA:63300
https://www.uniprot.org/uniprot/Q12094
https://www.rhea-db.org/rhea/63300

Human TSR3 is annotated with RHEA:63292
https://www.uniprot.org/uniprot/Q9UJK0
https://www.rhea-db.org/rhea/63292

I guess we'd need separate GO terms for each of those RHEAs, and then a generic parent term along the lines of:
N1-methylpseudouridine in 18S rRNA + S-adenosyl-L-methionine = H+ + N1-methyl-N3-[(3S)-3-amino-3-carboxypropyl]pseudouridine in 18S rRNA + S-methyl-5'-thioadenosine

Looking at an apparently similar term (GO:0016432 tRNA-uridine aminocarboxypropyltransferase activity), I guess the correct parents might be:
- GO:0140102 catalytic activity, acting on a rRNA
- GO:0016765 transferase activity, transferring alkyl or aryl (other than methyl) groups

**Comment by sjm41** [comment]
Hi @hdrabkin @pgaudet 
Can we proceed with adding this please?
Steven.

**Comment by sjm41** [comment]
@sarach06 @EBI-Hsinyu Once made, the new term(s) can be added to 16S/18S rRNA aminocarboxypropyltransferase Tsr3 (IPR022968)

**Comment by hdrabkin** [comment]
I'm not inclined to make a separate term for human and yeast for several reasons.  The CHEBI terms are the same for both
CHEBI:74890 + CHEBI:59789 = CHEBI:15378 + CHEBI:146234 + CHEBI:17509 
We cannot make a logical def to distinguish between these. The positional info in one is text based. The species info is text based in another.
The generic term can be equated to the rheas.

**Comment by hdrabkin** [comment]
The two RHEAs may be added as narrow xrefs

**Comment by hdrabkin** [comment]
+id: GO:0106388
+name: 18S rRNA aminocarboxypropyltransferase activity
RHEA:63296
