### ISSUE TITLE
wrong Rhea xref on GO:0090555

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#21377]
Hi,
Could you please replace the Rhea Xref [Rhea:36440] by Rhea:66132 for the go term GO:0090555.
Many thanks.
Guilaine

**Comment by pgaudet** [comment]
Fixed, thanks

This mapping is a little dubious, as this is not really a transmembrane transport reaction (the lipid moves from one side of the leaflet, not in/out). 

Thanks, Pascale
