### ISSUE TITLE
EC xref changed for ribonuclease T2 activity (GO:0033897)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21384]
EC xref for GO:0033897 was changed from EC:3.1.27.1 to EC:4.6.1.19 (see entry copied below) 

Comments at https://enzyme.expasy.org/EC/4.6.1.19 include:
- The enzyme catalyzes a two-stage endonucleolytic cleavage.
- The first reaction produces 5'-hydroxy-phosphooligonucletides and 3'-phosphooligonucleotides ending with a 2',3'-cyclic phosphodiester, which are released from the enzyme.
- The enzyme then hydrolyzes the cyclic products in a second reaction that takes place only when all the susceptible 3',5'-phosphodiester bonds have been cyclised.
- The second reaction is a reversal of the first reaction using the hydroxyl group of water instead of the 5'-hydroxyl group of ribose.
- The overall process is that of a phosphorus-oxygen lyase followed by hydrolysis to form the 3'-nucleotides. 

So, should we change the parentage in GO to reflect the change in EC? Probably from this:
is_a: GO:0016892 ! endoribonuclease activity, producing 3'-phosphomonoesters
to this:
is_a GO:0016849 ! phosphorus-oxygen lyase activity (which has EC xref of 4.6.-.-)

And also remove the references to 3.1.27.1 in the quoted synonyms?

If we do change the parentage, probably want to then re-add "GO:0004521 endoribonuclease activity" as an additional parent to GO:0033897.

==

id: GO:0033897
name: ribonuclease T2 activity
namespace: molecular_function
def: "Catalysis of the two-stage endonucleolytic cleavage to nucleoside 3'-phosphates and 3'-phosphooligonucleotides with 2',3'-cyclic phosphate intermediates." [EC:4.6.1.19]
synonym: "acid ribonuclease activity" EXACT []
synonym: "acid RNase activity" EXACT []
synonym: "base-non-specific ribonuclease activity" EXACT []
synonym: "Escherichia coli ribonuclease I' ribonuclease PP2 activity" EXACT []
synonym: "Escherichia coli ribonuclease II activity" RELATED [EC:4.6.1.19]
synonym: "non-base specific ribonuclease activity" EXACT []
synonym: "nonbase-specific RNase activity" EXACT []
synonym: "nonspecific RNase activity" EXACT []
synonym: "ribonnuclease (non-base specific) activity" EXACT []
synonym: "ribonuclease (non-base specific) activity" RELATED [EC:3.1.27.1]
synonym: "ribonuclease II activity" BROAD [EC:4.6.1.19]
synonym: "ribonuclease M activity" EXACT []
synonym: "ribonuclease N2 activity" EXACT []
synonym: "ribonuclease PP3 activity" RELATED [EC:3.1.27.1]
synonym: "ribonuclease U4 activity" EXACT []
synonym: "ribonucleate 3'-oligonucleotide hydrolase activity" EXACT []
synonym: "ribonucleate nucleotido-2'-transferase (cyclizing) activity" BROAD []
synonym: "RNAase CL activity" EXACT []
synonym: "RNase (non-base specific) activity" EXACT []
synonym: "RNase II activity" BROAD [EC:4.6.1.19]
synonym: "RNase M activity" RELATED [EC:3.1.27.1]
synonym: "RNase Ms activity" EXACT []
synonym: "RNase T2 activity" RELATED [EC:4.6.1.19]
xref: EC:4.6.1.19
xref: MetaCyc:3.1.27.1-RXN
is_a: GO:0016892 ! endoribonuclease activity, producing 3'-phosphomonoesters

**Comment by hdrabkin** [comment]
Yes when I replace the retired EC, I saw potential parentage change 
EC:3.1.27.1 to EC:4.6.1.19  (3.3.27 to 4.6.1), but decided to just keep "RNAse activity" parent 
I thought I caught all the synonyms; if the new EC does not support the synonym, I remove the xref from the synoym but leave the synonym so people might have a chance to find the term. The synonym usage might actually be ok, but EC does not use them.  Quite often the new ecs do not have as many synonyms.

**Comment by sjm41** [comment]
So, are you saying the parentage will stay as it is?
Given the EC entry says "The overall process is that of a phosphorus-oxygen lyase followed by hydrolysis to form the 3'-nucleotides.", plus the fact the EC xref is a lyase, it seems that GO:0033897 should have lyase parentage instead of/as well as the current hydrolase parentage?

(synonyms themselves seem fine - I was just wondering whether the explicit references to "3.1.27.1" should be removed from the synonyms, given that ID is obsolete - what's the policy on that?)

**Comment by hdrabkin** [comment]
- I was just wondering whether the explicit references to "3.1.27.1" should be removed from the synonyms, given that ID is obsolete - what's the policy on tha; 
 - yes the ideas in the synonym need to go.
 -

**Comment by hdrabkin** [comment]
So, are you saying the parentage will stay as it is?; no was just hesitant
 EC 4.6.1 Phosphorus-oxygen lyases but I would also want to keep a parent to a nuclease/RNAse activity also.

**Comment by sjm41** [comment]
OK, good!

Agreeing with you, my original suggestion was to replace the current "GO:0016892 ! endoribonuclease activity, producing 3'-phosphomonoesters" parent with these two:
GO:0016849 ! phosphorus-oxygen lyase activity
GO:0004521 endoribonuclease activity

- The first one has xref 4.6.-.- (note that there's no difference between 4.6.-.- and 4.6.1..-  I don't know if that means both those xrefs should go on GO:0016849?)
- The second one adds the nuclease/RNAse activity (in an EC-agnostic way)

Also, I think 4.6.1.- needs to be removed from this term:
id: GO:0036356
name: cyclic 2,3-diphosphoglycerate synthetase activity
def: "Catalysis of the reaction: 2,3-diphosphoglycerate (DPG) + ATP = cyclic 2,3-diphosphoglycerate (cDPG) + ADP + phosphate." [GOC:crds, PMID:2226838, PMID:8320225, PMID:9811660]
xref: EC:4.6.1.-
is_a: GO:0009975 ! cyclase activity

**Comment by hdrabkin** [comment]
Yes; another 3 digit ec added to a leaf node. I'll rid it later today.

**Comment by hdrabkin** [comment]
Parentage adjusted and ecs removed from synonyms and 3 digit ec removed from GO:0036356. Closing
