### ISSUE TITLE
Remove excessive EC:3.2.2.- xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21385]
EC:3.2.2.- is a grouping term for "Hydrolases -> Glycosylases -> Hydrolyzing N-glycosyl compounds":
https://enzyme.expasy.org/EC/3.2.2.-

So it's correct to be on the first term below, but I think should be removed from the other 4 terms below.

id: GO:0016799
name: hydrolase activity, hydrolyzing N-glycosyl compounds
namespace: molecular_function
def: "Catalysis of the hydrolysis of any N-glycosyl bond." [GOC:jl]
xref: EC:3.2.2.-

id: GO:0019104
name: DNA N-glycosylase activity
namespace: molecular_function
alt_id: GO:0008578
def: "Catalysis of the removal of damaged bases by cleaving the N-C1' glycosidic bond between the target damaged DNA base and the deoxyribose sugar. The reaction releases a free base and leaves an apurinic/apyrimidinic (AP) site." [GOC:elh, PMID:11554296]
synonym: "DNA glycosylase activity" EXACT []
synonym: "endonuclease VIII activity" RELATED []
xref: EC:3.2.2.-

id: GO:0043733
name: DNA-3-methylbase glycosylase activity
namespace: molecular_function
def: "Catalysis of the reaction: DNA containing 3-methylbase + H2O = DNA with abasic site + 3-methylbase. This reaction is the hydrolysis of DNA by cleavage of the N-C1' glycosidic bond between the damaged DNA 3-methylpurine or 3-methylpyrimidine base and the deoxyribose sugar to remove the methylated base, leaving an apurinic or apyrimidinic site." [PMID:10777493, PMID:14517230]
synonym: "DNA-3-methyladenine glycosylase III" RELATED []
synonym: "Mag III" NARROW []
synonym: "MagIII" NARROW []
xref: EC:3.2.2.-

id: GO:0070694
name: deoxyribonucleoside 5'-monophosphate N-glycosidase activity
namespace: molecular_function
def: "Catalysis of the reaction: a deoxyribonucleoside 5'-monophosphate + H2O = deoxyribose 5-monophosphate + a purine or pyrimidine base." [GOC:ab, PMID:17234634]
synonym: "deoxynucleoside 5'-monophosphate N-glycosidase activity" EXACT []
xref: EC:3.2.2.-
xref: Reactome:R-HSA-8953339 "DNPH1 hydrolyses dGMP"

id: GO:0000701
name: purine-specific mismatch base pair DNA N-glycosylase activity
namespace: molecular_function
def: "Catalysis of the removal of purines present in mismatches, especially opposite oxidized purines, by cleaving the N-C1' glycosidic bond between the target damaged DNA base and the deoxyribose sugar. The reaction releases a free base and leaves an apurinic (AP) site." [GOC:elh, PMID:9224623]
synonym: "A/G-specific adenine DNA glycosylase activity" NARROW []
xref: EC:3.2.2.-

**Comment by sjm41** [comment]
Good spot adding "EC 3.2.2.31" to GO:0000701! (Though did you omit the colon in that new xref?)

**Comment by pgaudet** [comment]
of course I did! thank you for spotting it ;)

**Comment by sjm41** [comment]
:-)
