### ISSUE TITLE
missing parent: enzyme activator/inhibitor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21398]
enzyme activator activity (GO:0008047) is_a enzyme regulator activity (GO:0030234)
enzyme inhibitor activity (GO:0004857) is_a enzyme regulator activity (GO:0030234)

fot
https://github.com/pombase/pombase-config/issues/66

**Comment by ValWood** [comment]
That didn't solve. The missing relation is this one:
![Uploading Screenshot 2021-09-27 at 19.38.02.png…]()

**Comment by pgaudet** [comment]
Hopefully this will fix it - adjusted logical definition
<img width="529" alt="image" src="https://user-images.githubusercontent.com/4782928/135213197-332c4fd3-73b7-4b96-97a6-2b9c06ef9dcb.png">
