### ISSUE TITLE
True path violation: helicase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21393]
noticed while fixing
https://github.com/geneontology/go-annotation/issues/3762
helicase activity
is a descendant of 
GO:0008094 ATPase, acting on DNA

but many helicases are RNA helicases?

**Comment by ValWood** [comment]
move to GO:0003678    DNA helicase activity

**Comment by pgaudet** [comment]
There are few annotations to this term. I moved some to children RNA or DNA helicase activity - In many cases it's easy to tell. I dont know if the non-specific term is really needed.

**Comment by ValWood** [comment]
for the 88 pombe helicases we do seem to know if they are RNA /DNA or both. I doubt this is always the case. Also the RNA/DNA agnostic term might be needed for some IEA mappings  for families which cover both types.

**Comment by sjm41** [comment]
I think 'helicase activity' is a useful grouping term, even if all helicases can be annotated to act DNA or RNA.

I see that FB has 27 Dmel genes annotated directly to 'helicase activity'.  Haven't checked them all, but I see some come from reviews (where I guess limited info was given).

(That said, I know all the 85 Dmel helicases can be annotated to be a DNA or RNA helicase, and we have four that are annotated to both.  But I agree with Val that that won't always be the case.)
