### ISSUE TITLE
Merge  GO:0052413 metabolism by organism of cell wall pectin in other organism involved in symbiotic interaction & related

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21396]
Pectin is only found in plants. 
~Plants are not symbionts of other organisms.~ But there are no examples I know of where a plant synthesises or degrades another plant's cell wall.
So those 4 terms should be merged or obsoleted: 

* GO:0052413 metabolism by organism of cell wall pectin in other organism involved in symbiotic interaction
* GO:0052341 catabolism by organism of cell wall pectin in other organism involved in symbiotic interaction
* GO:0052412 metabolism by host of symbiont cell wall pectin
* GO:0052357 catabolism by host of symbiont cell wall pectin

Those can remain: 
* GO:0052179 metabolism by symbiont of host cell wall pectin 
* GO:0052011 catabolism by symbiont of host cell wall pectin 

@ValWood @mgiglio99 @dsiegele any preference for merge/obsolete? 
There are no annotations (I moved annotations from GO:0052413 to GO:0052011)

Thanks, Pascale

**Comment by ValWood** [comment]
No preference.

**Comment by mgiglio99** [comment]
Hi
Just want to say that plants can be symbionts of other plants.
Sometimes these parasitic plants interact directly with a host plant and sometimes they interact through an intermediate fungus. 
I don't know if pectin metabolism is part of any of these interactions, but it could be.
Michelle

**Comment by ukemi** [comment]
Spanish moss? I miss New Orleans.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 


The reasons for obsoletions are 

a)	No evidence that those processes exist: 
GO:0052357 obsolete catabolism by host of symbiont cell wall pectin
GO:0052358 obsolete catabolism by host of symbiont glucan


b)	Unnecessary grouping classes:
GO:0044043 obsolete multi-organism glucan metabolic process
GO:0052177 obsolete metabolism by symbiont of host xylan
GO:0052229 obsolete metabolism of macromolecule in other organism involved in symbiotic interaction
GO:0052340 obsolete catabolism by organism of cell wall cellulose in other organism involved in symbiotic interaction
GO:0052341 obsolete catabolism by organism of cell wall pectin in other organism involved in symbiotic interaction
GO:0052342 obsolete catabolism by organism of cell wall chitin in other organism involved in symbiotic interaction

GO:0052359 obsolete catabolism by organism of glucan in other organism involved in symbiotic interaction
GO:0052361 obsolete catabolism by organism of macromolecule in other organism involved in symbiotic interaction
GO:0052363 obsolete catabolism by organism of protein in other organism involved in symbiotic interaction
GO:0052365 obsolete catabolism by host of symbiont xylan
GO:0052366 obsolete catabolism by organism of xylan in other organism involved in symbiotic interaction
GO:0052409 obsolete metabolism by organism of cell wall cellulose in other organism involved in symbiotic interaction
GO:0052411 obsolete metabolism by organism of cell wall chitin in other organism involved in symbiotic interaction
GO:0052412 obsolete metabolism by host of symbiont cell wall pectin
GO:0052415 obsolete metabolism by organism of glucan in other organism involved in symbiotic interaction
GO:0052418 obsolete metabolism by organism of protein in other organism involved in symbiotic interaction
GO:0052420 obsolete metabolism by host of symbiont xylan
GO:0052421 obsolete metabolism by organism of xylan in other organism involved in symbiotic interaction


There are no annotations to these terms; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/21396

Thanks, Pascale

**Comment by mgiglio99** [comment]
Hi - didn't mean to sound like I didn't agree with the merger - we can bring the pectin terms back if examples are found. I don't have any examples.
But just for information sake and because they are interesting species - here are a just a few examples of heterotrophic plants that lack chlorophyll and rely on host plants for food. 
-parasitic plants that get nutrients directly from a host plant:
--ground cones - https://en.wikipedia.org/wiki/Boschniakia
--broomrapes - https://en.wikipedia.org/wiki/Orobanche
--dodder plants - https://en.wikipedia.org/wiki/Cuscuta
-mycotrophic plants that get their nutrients from a host plant via an intermediary fungus which itself is feeding on a host plant:
--ghost plant  - https://en.wikipedia.org/wiki/Monotropa_uniflora
--sweet pinesap - https://en.wikipedia.org/wiki/Monotropsis
