### ISSUE TITLE
obsoletions: transporter activity terms for 7 specific xenobiotic compounds, also related BP transport & response to terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#21394]
At the May 2021 GOC meeting, I proposed to obsolete these MF transporter activity terms listed under "**xenobiotic transmembrane transporter activity**"

![Slide2](https://user-images.githubusercontent.com/10533218/117527482-52d0f500-af81-11eb-86f3-e031686631ba.jpeg)

There is also an MF term for "organomercurial transmembrane transporter activity" which appears to have been created by splitting the now obsolete term "carbonyl cyanide m-chlorophenylhydrazone/nalidixic acid/organomercurials:hydrogen antiporter activity" (GO:0015525) into three terms, two of which are already on my list targeted for obsoletion. 

None of these MF terms are used for any annotations present in AmiGO as of May 2021. I propose to obsolete all of them as out of scope for GO as all of these compounds appear to be synthetic and thus these terms do not represent evolved functions. Here's a table of the compounds with linkouts to pages providing info about each compound:

compound | Wiki link
-- | --
3-hydroxyphenylpropionic acid | https://pubchem.ncbi.nlm.nih.gov/compound/3-_3-Hydroxyphenyl_propanoic-acid
acridine | https://en.wikipedia.org/wiki/Acridine
acriflavine | https://en.wikipedia.org/wiki/Acriflavine
amiloride | https://en.wikipedia.org/wiki/Amiloride
benomyl | https://en.wikipedia.org/wiki/Benomyl
carbonyl cyanide   m-chlorophenylhydrazone | https://en.wikipedia.org/wiki/Carbonyl_cyanide_m-chlorophenyl_hydrazone
nalidixic acid | https://en.wikipedia.org/wiki/Nalidixic_acid

**Related BP terms** 

In identifying usages of these terms, I realized that most of the 'x transmembrane transporter activity' MF terms are used in 'part of' relationships for corresponding 'x transport' BP terms.

For some of these 7 compounds, there are also 'response to x' terms and/or 'cellular response to x' terms. Only 4 of the BP terms are used for a handful of experimental annotations. 

I propose to obsolete all of these BP terms as well. 

**Question:** In the few cases where there are annotations, do we have any concerns about reannotation to other terms that might not provide any ability to allow enrichment to an appropriate chemical class of 'x transport' or 'response to x'
Thoughts? @cmungall @pgaudet @thomaspd @deustp01  We can discuss this at our next call if needed.

Here is a table of the terms I'd like to obsolete:

![7-specificXenobiotics-table](https://user-images.githubusercontent.com/10533218/117528235-fb815380-af85-11eb-90d8-e3ee96d9a0f8.png)

**Comment by krchristie** [comment]
**5/17/21 - Discussion at Ontology Editors' call**: It was agreed that "response to" terms for synthetic compounds do not belong in GO. I will proceed with the obsoletion procedure for all MF and BP terms listed in this ticket.

**Comment by raymond91125** [comment]
It appears that 3-hydroxyphenylpropionic acid https://pubmed.ncbi.nlm.nih.gov/9098055/ is an E. coli metabolite.

**Comment by pgaudet** [comment]
Hi @raymond91125 
These seem to be degradation pathways from flavonoids producing 3-hydroxyphenylpropionic acid, see for example 
https://pubmed.ncbi.nlm.nih.gov/29981789/
https://pubmed.ncbi.nlm.nih.gov/29205863/


For the term you propose to osbolete, I think its fine to go ahead with the obsoletion, since I cannot find evidence for a specific transporter. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Actually - there seems to be an ecoli transporter: https://pubmed.ncbi.nlm.nih.gov/23934492/
(annotated by EcoCyc) 

However for the related terms 
* GO:0042889 3-phenylpropionic acid transport
*  [GO:0042890 3-phenylpropionic acid transmembrane transporter activity](http://amigo.geneontology.org/amigo/term/GO:0042890#display-lineage-tab)
there are no pubmeds, no evidence 

@amandamackie do you know about the transporters for these compounds ?

**Comment by amandamackie** [comment]
There is an experimentally characterized transporter in E. coli for 3-hydroxyphenylpropanoate (encoded by _mhpT_) but the predicted transporter for 3-phenylpropanoate (_hcaT_) has not been experimentally characterized.
There are known pathways in E. coli for the catabolism of both these compounds. 

So we require GO terms for 3-hydroxyphenylpropanoate transport but not for 3-phenylpropanoate transport.

**Comment by raymond91125** [comment]
MF terms obsoleted.

**Comment by raymond91125** [comment]
BPs to obsolete
ID Label | EXP
--|--
GO:0042909 acridine transport | 0
GO:0015894 acriflavine transport | 0
GO:0015898 amiloride transport | MGI 1
GO:0036253 response to amiloride | RGD 1
GO:0036254 cellular response to amiloride | ComplexPortal 13
GO:0015900 benomyl transport | 0
GO:1901477 benomyl transmembrane transport | 0
GO:0072755 cellular response to benomyl | UniProt 1
GO:1901561 response to benomyl | 0
GO:0015902 carbonyl cyanide m-chlorophenylhydrazone transport | 0
GO:0072727 cellular response to CCCP | 0
GO:0072726 response to CCCP | 0
GO:0015896 nalidixic acid transport | 0

**Comment by gthayman** [comment]
RGD changed its annotation.
