### ISSUE TITLE
GO:0002221    pattern recognition receptor signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21390]
GO:0002221    pattern recognition receptor signaling pathway
Add parent
GO:0002764   immune response-regulating signaling pathway

**Comment by pgaudet** [comment]
Actually I think the correct parent for both these terms is 'innate immune response activating cell surface receptor signaling pathway' 

@hattrill many fly genes annotated to this - just checking with you also- 

Thanks, Pascale

**Comment by pgaudet** [comment]
I see there are intracellular receptors - I will leave bother terms to GO:0002764   immune response-regulating signaling pathway, unless we find reason to do otherwise. 

Thanks, Pascale

**Comment by hattrill** [comment]
That sounds good to me - I was just looking and there are extracellular, TMRs and intracellular receptors.
