### ISSUE TITLE
NTR 'catalytic activity, acting on nucleic acid'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21402]
Hello, 

To group terms like 'helicase activity' (#21393 ) , for which we don't know whether the enzyme activity is specific for DNA or RNA, I will create a new grouping class, 'catalytic activity, acting on nucleic acid'

@thomaspd 

Thanks, Pascale

**Comment by ValWood** [comment]
Will 'helicase activity' continue to exist as a grouping term?
