### ISSUE TITLE
Request new term neutrophil extracellular trap (NETs) and formation.

### ISSUE THREAD

**Issue by kallia-p** [geneontology/go-ontology#21416]
'neutrophil extracellular trap' 
synonym NET
definition: Neutrophil extracellular traps (NETs) are microbicidal structures composed of nuclear chromatin, histones and granular antimicrobial proteins. Histones and several neutrophil granule proteins associated with the DNA framework damage entrapped microorganisms.
PMID:31172493
Suggested parent term 'cellular component'

'neutrophic extracellular trap formation'  
synonym NET formation
definition: Neutrophil extracellular traps (NETs) are microbicidal structures composed of nuclear chromatin, histones and granular antimicrobial proteins. The major form of NET formation, called suicidal NETosis, leads to the death of neutrophils Vital NETosis has also been described during which process neutrophils remain live and release only parts of their nuclear or mitochondrial DNA. NETs have been shown to entrap a wide variety of microbes and provide a crucial innate immune mechanism.
database cross ref http://purl.obolibrary.org/obo/TXPO_0002149 
suggested parent term 'cellular process'

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140644
+name: neutrophil extracellular trap
+namespace: cellular_component
+def: "Extracellular microbicidal structure composed of nuclear chromatin, histones and granular antimicrobial proteins. Histones and several neutrophil granule proteins associated with the DNA framework damage entrapped microorganisms." [PMID:31172493]
+is_a: GO:0043264 ! extracellular non-membrane-bounded organelle
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21416 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-12T07:03:05Z
+


Note that I used subclass = extracellular non-membrane-bounded organelle
@kallia-p please confirm that this is OK

**Comment by pgaudet** [comment]
+
+[Term]
+id: GO:0140645
+name: neutrophic extracellular trap formation
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a neutrophil extracellular trap, a network of extracellular fibers primarily composed of DNA from neutrophils, which bind and neutralizes pathogens." [PMID:28267716]
+synonym: "NET formation" BROAD []
+xref: http://purl.obolibrary.org/obo/TXPO_0002149
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_formation_of GO:0140644 ! neutrophil extracellular trap
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21416 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-12T07:08:07Z

**Comment by pgaudet** [comment]
also fixed some subclasses relations for intracellular/extracellular organelles
