### ISSUE TITLE
GO parentage query 	GO:1990276	 RNA 5'-methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21427]
For  SPBC2A9.10/Q9Y7L2 7SK RNA methyltransferase
I am picking up a  PAINT mapping  for 
O-methyltransferase activity

so, is  RNA 5'-methyltransferase activity
a O-methyltransferase activity?

**Comment by ValWood** [comment]
This is the human ortholog:
https://www.uniprot.org/uniprot/Q7L2J0
Rhea is
a 5'-triphospho-guanosine-ribonucleotide-snRNA + S-adenosyl-L-methionine = a 5'-methyltriphosphate-guanosine-ribonucleotide-snRNA + S-adenosyl-L-homocysteine

**Comment by hdrabkin** [comment]
From the PMID used for the term
'MePCE uses S-adenosyl methionine to transfer a methyl group onto the γ-phosphate of the 5' guanosine of 7SK RNA generating an unusual cap structure that protects 7SK RNA from degradation. 
So the methyl group is on the phosphate  mePPPG_7SKRNA
So when I see 'O-methyl transferase I'm thinking of the OH of the ribose.
However, the parents for the term are
RNA methyltransferase activity and
'S-adenosylmethionine-dependent methyltransferase activity
I can't find anything to link the term to O-methylation in the ontology (ran reasoner; nada;

**Comment by ValWood** [comment]
OK, in that case maybe the  underlying annotations transferred by pAINT are incorrect? Or this enzyme has multiple substrates?

It comes from this uniprot annotation
GO:0008171 | O-methyltransferase activity | IBA with PTN000267975 , Q7Z5W3




UniProtKB:Q7Z5W3 | BCDIN3D | enables | GO:0008171    O-methyltransferase activity | ECO:0000269   EXP | PMID:23063121 |   | 9606 Homo sapiens | Reactome

UniProtKB:Q7Z5W3 | BCDIN3D | enables | GO:0008171    O-methyltransferase activity | ECO:0000314   IDA | PMID:23063121


Do you think these are incorrect?

**Comment by ValWood** [comment]
Looks correct:
PMID:23063121

<img width="670" alt="Screenshot 2021-05-12 at 15 17 18" src="https://user-images.githubusercontent.com/7359272/117990610-38a66680-b335-11eb-9cdc-77225dbe7843.png">

**Comment by hdrabkin** [comment]
But not a O-methyltransferase, which means 2'O

**Comment by hdrabkin** [comment]
EC:2.1.1.- is actually a good fit for  the grouping term 'methyltransferase (GO:0008171

**Comment by hdrabkin** [comment]
2'O-methyltransfrase is a child of O-methyltransferase;  
So I guess the PAINT seems ok ;

**Comment by hdrabkin** [comment]
I can add O-methyltransferase activity as a parent

**Comment by ValWood** [comment]
so will RNA 5'-methyltransferase activity

be a descendant of 2'O-methyltransfrase

**Comment by hdrabkin** [comment]
yes 
O-methyltransferase activity will be parent to  RNA 5'-methyltransferase activity (as defined the methyl group IS being transfered to an oxygen in the phosphate group)

**Comment by hdrabkin** [comment]
done.
