### ISSUE TITLE
histone-specific chaperone activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21436]
Term name | unfolded protein binding
Matching synonym | histone-specific chaperone activity

This is weird because histone chaperones don't bind to unfolded proteins, they bind to nucleosomal histones?

**Comment by pgaudet** [comment]
Is the suggestion to remove the synonym? looks like this may have resulted from a term merge.

**Comment by ValWood** [comment]
Well - what do we use for a histone chaperone? That is what I was looking for...

**Comment by pgaudet** [comment]
do we need a specific term for each substrate of a chaperone? what are you trying to capture?

**Comment by ValWood** [comment]
A histone chaperone loads nucleosome onto DNA.
I don't see any term I can use for this.

**Comment by ValWood** [comment]
I think histone binding is used usually, but it isn't really capturing the activity

These are the terms.


GO:0016531    copper chaperone activity | 4,279 annotations
GO:0044183    protein folding chaperone | 7,148 annotations
GO:0034986    iron chaperone activity | 254 annotations
GO:0042393    histone binding | 74,539 annotations
GO:0016532    superoxide dismutase copper chaperone activity | 334 annotations
GO:0140318    protein transporter activity | 329,236 annotations
GO:0051082    unfolded protein binding

**Comment by ValWood** [comment]
histone binding has
histone-specific chaperone activity | related

@colinlog  how do you annotate this?

**Comment by pgaudet** [comment]
We should probably remove the following synonyms: 

binding unfolded ER proteins, fimbrium-specific chaperone activity, glycoprotein-specific chaperone activity, histone-specific chaperone activity, ribosomal chaperone activity, tubulin-specific chaperone activity

I dont think they add very much.

**Comment by colinlog** [comment]
Histone chaperoning is definitely a set of related molecular functions;  namely binding to histones to permit (i) deposition into nucleosomes on DNA (for chromosome replication, repair, recombination & transcription control), and/or (ii) extraction from nucleosomes / dismantling nucleosomes (again, this can be for replication, repair, recombination & transcription control). This concerns individual histones (H2A, H2B, H3, H4 and many of their variants), but also pairs of histones (H3-H4, H2A-H2B).

**Comment by pgaudet** [comment]
Nice review here: https://www.nature.com/articles/nrm.2016.159

However I dont think this is a single MF, I will go ahead and remove the synonyms of unfolded protein binding as I suggested above : https://github.com/geneontology/go-ontology/issues/21436#issuecomment-842295624
