### ISSUE TITLE
JNK cascade placement revision required

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21439]
Hi 

There is a problem with the ontology placement above the GO:0007254 JNK cascade term.
PMID: 27511108 describes the role of the JNK cascade in axon growth, but I think it is inappropriate to state that axon growth is always in response to stress, although they do also discuss neuron wounding. eg in the abstract they state: Neuronal maturation or activity deprivation activates the LZK-MKK4-JNK pathway.

Currently the ontology is:
 GO:0000165 MAPK cascade
>  is a GO:0051403 stress-activated MAPK cascade
>> is a GO:0007254 JNK cascade 

 GO:0033554 cellular response to stress
>  is a GO:0031098 stress-activated protein kinase signaling cascade
>>  is a GO:0051403 stress-activated MAPK cascade
>>> is a GO:0007254 JNK cascade 

I think the main problem is with the term stress-activated MAPK cascade which is using the name/alias of the protein stress-activated MAPK https://www.uniprot.org/uniprot/?query=stress-activated%20mapk&fil=organism%3A%22Homo+sapiens+%28Human%29+%5B9606%5D%22&sort=score to determine the ontology structure. ie it is a child of  GO:0033554 cellular response to stress,

I do not think that all stress-activated MAPK cascades are activated by stress (eg JNK cascade in axon growth). Is it necessary to group these cascades under the family 'stress-activated MAPK'. 

For human the majority of the annotations are using the more specific child terms https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in,regulates&goId=GO:0051403&taxonId=9606&taxonUsage=descendants&evidenceCode=ECO:0000352&evidenceCodeUsage=descendants and I am not convinced that these are due to evidence that 'stress' was involved but that, for example, the JNK cascade was identified and the curators did not realise that the parent term was 'cellular response to stress'. 28 human annotations using stress-activated MAPK cascade https://www.ebi.ac.uk/QuickGO/annotations?goUsage=exact&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0051403&taxonId=9606&taxonUsage=descendants

For all specieshttps://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in,regulates&goId=GO:0051403 the use of stress-activated MAPK cascade is more common

A quick fix would be to just remove the parent relation to  GO:0033554 cellular response to stress

But I wonder if the GO:0031098 stress-activated protein kinase signaling cascade and GO:0051403 stress-activated MAPK cascade should just be merged into MAPK cascade terms with curators encouraged to use 
JNK cascade 
p38MAPK cascade
 ERK5 cascade 
ERK1 and ERK2 cascade

By grouping  JNK cascade p38MAPK cascade under stress-activated MAPK cascade curators maybe missing these terms if they are just looking for more specific MAPK cascade terms.

There again maybe the whole of this part of the ontology is being revised

Best

Ruth

Ruth

**Comment by ValWood** [comment]
This no longer has a stress response parantage

**Comment by ValWood** [comment]
i.e already fixed
