### ISSUE TITLE
positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21443]
I can't locate this term.
positive regulation of transcription from RNA polymerase II promoter

Is that because we should always be able to specify initiation/elongation/termination?

**Comment by ValWood** [comment]
found it
GO:0045944   positive regulation of transcription by RNA polymerase II

This is really hard to locate in QuickGO and Canto  unless you get the precise string because of all these terms:

<img width="661" alt="Screenshot 2021-05-13 at 12 03 22" src="https://user-images.githubusercontent.com/7359272/118118068-52eb4d80-b3e4-11eb-86b4-515dac636a1b.png">

which should probably largely be removed?

**Comment by ValWood** [comment]
...and the inconsistent wording.

**Comment by pgaudet** [comment]
@ValWood I am closing this. 

The terms with the different formulation are slated for obsoletion, see  #12739

Thanks, Pascale
