### ISSUE TITLE
Rename structural constituent of carboxysome -> carboxysome shell

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#21446]
See previous discussion #19379 

```
id: GO:0043886
name: structural constituent of carboxysome
namespace: molecular_function
def: "The action of a molecule that contributes to the structural integrity of a carboxysome, an organelle found in all cyanobacteria and some chemoautotrophs, consisting of a proteinaceous coat and enzymes for the fixation of CO(2)." [GOC:jl, PMID:28934381]
is_a: GO:0005198 ! structural molecule activity
intersection_of: GO:0005198 ! structural molecule activity
intersection_of: occurs_in GO:0031470 ! carboxysome
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19743 xsd:anyURI
```

I find this odd on a number of levels.

The name is strange. I think it just means carboxysome shell

also why the lopsided structure? of all the 3 BMCs why does this one only have the structural constituent pattern instantiated?

![image](https://user-images.githubusercontent.com/50745/118203295-9956a180-b410-11eb-8f79-d022b9fc87c5.png)

It looks like we have duplicative/redundant annotations between the SC term and the CC term. I think it makes sense to have two terms to distinguish the shell from things in the shell (e.g. rubisco). But I think we need clear guidelines as to which term to annotate when.

Regarding the name:

https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22structural+constituent+of+carboxysome%22&btnG=

![image](https://user-images.githubusercontent.com/50745/118199294-9a370580-b407-11eb-9136-15c32908aad7.png)

contrast:

https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22carboxysome+shell%22&btnG=

![image](https://user-images.githubusercontent.com/50745/118199315-a7ec8b00-b407-11eb-909d-1db7c0bfdf94.png)

I realize carboxysome shell is not a MF name, but do we need MFs for these? Do we need to duplicate parts of CC in MF just so people can check the box with an MF annotation?

**Comment by cmungall** [comment]
also: isn't the 'structural constituent' a complex?

**Comment by pgaudet** [comment]
Hi @cmungall 

I also questioned this term here #19743 
but Andrea confirmed that this was the MF of some proteins. 

Close?

**Comment by cmungall** [comment]
do you think 'carboxysome shell' is a good synonym?

**Comment by deustp01** [comment]
> do you think 'carboxysome shell' is a good synonym?

Maybe this is a tangent -

Quoting from [PMID: 24006469](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3811607/), 

> Carboxysomes encapsulate the CO2-fixing enzyme within the selectively permeable protein shell and simultaneously encapsulate a carbonic anhydrase enzyme for CO2 supply from a cytoplasmic bicarbonate pool.

and

> Carboxysomes are specialized protein microcompartments composed of a polyhedral protein shell within which cyanobacteria concentrate CO2 around their primary carboxylating enzyme, d-ribulose 1,5-bisphosphate carboxylase/oxygenase (RubisCO). 

So on the one hand a carboxysome appears to have the structure of a large complex, although perhaps not one with a fully defined composition and structure, but on the other distinctive functions are mediated by shell components and inside components, so maybe two cell component terms are needed for shell and innards, and a grouping term "carboxysome" for cases where a mire precise localization is not possible? (Analogously to the usual treatment of a eukaryotic intracellular membrane-bounded vesicle?

Also, the definition of GO:0043886 structural constituent of carboxysome, "The action of a molecule that contributes to the structural integrity of a carboxysome, an organelle found in all cyanobacteria and some chemoautotrophs, consisting of a proteinaceous coat and enzymes for the fixation of CO(2)," appears not to include the transport and catalytic functions of gene products, but onluy to their role in keeping the structure intact.

**Comment by pgaudet** [comment]
@cmungall wouldn't 'carboxysome shell' be a CC?

**Comment by pgaudet** [comment]
Decision on ontology call: change label to 'structural constituent of carboxysome shell'
