### ISSUE TITLE
Missing parent: GO:1904600  actin fusion focus assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21449]
GO:1904600  actin fusion focus assembly
The aggregation, arrangement and bonding together of a set of components to form an actin fusion focus.

Actin fusion focus is defined:
A focus at the mating projection tip where the cell wall is degraded during conjugation with cellular fusion. Actin filaments form an aster-like structure from this location.

Therefore, GO:1904600  actin fusion focus assembly
Should have the parent
GO:0000747 conjugation with cellular fusion (i.e. mating)

**Comment by pgaudet** [comment]
Do you mean 'actin fusion focus assembly' **part_of** 'conjugation with cellular fusion'?

**Comment by pgaudet** [comment]
if you do, this relation is already present.

**Comment by pgaudet** [comment]
Done in #18630

**Comment by ValWood** [comment]
So it is. I menat 

GO:0061915 | actin fusion focus localization

but that seems an odd term. It is used to annotate an action capping protein, so it seems more of a phenotype than a process (presumably not an active process of the actin fusion focus localizes where it assembles)? I will look into that because I need to tidy the extensions.
https://www.pombase.org/reference/PMID:28410370

**Comment by pgaudet** [comment]
Should we obsolete GO:0061915 | actin fusion focus localization ? No annotations

Or we could merge it into     GO:1904600  actin fusion focus assembly

**Comment by ValWood** [comment]
I am happy to obsolete. It was probably   added to provide a logical definition for a phenotype, but I don't think it makes sense to add terms to GO only for this purpose. Some of  these terms (particularly the localization terms) will not be relevant for GO process annotation. I tend to avoid localization BP annotation because these are better nearly always described in other ways which are more processual (assembly or signalling- the abbormal localization is a phenotypic  consequence). The  phenotype[e  logical definitions can be made another way (using localization + component for example).

**Comment by ValWood** [comment]
obsolete GO:0061915 | actin fusion focus localization

rename  actin fusion focus terms to 
"mating projection actin fusion focus"

I also don't think we should have
[GO:1904601]    protein localization to actin fusion focus
used to annotate myosins.
