### ISSUE TITLE
wrong Rhea on GO:0015267

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21440]
GO:0015267 has xref to RHEA:29447 which is about glycolate transport. Similarly with the Reactome xrefs which are too specific on this generic entity.

**Comment by hdrabkin** [comment]
Yes, the rhea is to a specific transport, not the generic; will fix.
However, the Rectome xefs to a term should be looked at as the GO term was used to annotate the Reactome id. In that sense, I think they are still correct.  If there is a term with a better fit, Reactome should be notified.
@deustp01 would you like to chime in here.

**Comment by hdrabkin** [comment]
The RHEA should go with 
GO:1900866 glycolate transport

**Comment by hdrabkin** [comment]
the RHEA to GO mapping you cite above is not in the 'live' ontology. May have been removed under a different ticket.

**Comment by rwst** [comment]
The date of the snapshot I used:
`data-version: releases/2021-05-04`
so it was not long ago.

**Comment by hdrabkin** [comment]
Hm; It wasn't me! 
Anyway, I put it on the GO:0043879; 
Reactome has been pinged should they want to fix their annotations

**Comment by rwst** [comment]
Thanks.
