### ISSUE TITLE
Term merge: maintenance of mitotic sister chromatid cohesion, centromeric/maintenance of mitotic sister chromatid cohesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21445]
**Term to be merged:**

GO:0071960    maintenance of mitotic sister chromatid cohesion, centromeric
should merge into 

GO:0034088 maintenance of mitotic sister chromatid cohesion

**Reason for merge**

This is a single process, the maintenance (loading unloading) which is not specific to the centromeres

**Any other information**
Used only for 2 PomBase EXP

**Comment by pgaudet** [comment]
What about sibling terms 
GO:0071959 maintenance of mitotic sister chromatid cohesion, arms
and GO:0099403 maintenance of mitotic sister chromatid cohesion, telomeric  2 EXP BHF

Note that those terms also have 'regulation' subclasses. Overall there are 26 EXP annotations: 

10 EXP maintenance of mitotic sister chromatid cohesion
6 EXP	positive regulation of maintenance of mitotic sister chromatid cohesion
4 EXP	negative regulation of maintenance of mitotic sister chromatid cohesion
2 EXP 	maintenance of mitotic sister chromatid cohesion, centromeric
2 EXP  negative regulation of maintenance of mitotic sister chromatid cohesion, telomeric
1 EXP	negative regulation of maintenance of mitotic sister chromatid cohesion, centromeric
1 EXP	positive regulation of maintenance of mitotic sister chromatid cohesion, centromeric

Assigned by 
11 EXP	UniProt
7 EXP	PomBase
5 EXP	BHF-UCL
3 EXP	SGD

Can you check if those other terms are necessary?

**Comment by ValWood** [comment]
Gah there are too many terms here but this is b beginning to look  like a mini project!

I have some questions about how to use regulation, I will use these regulation terms as an example. I think we will be able to  merge a lot, but I will check with some experts.

**Comment by ValWood** [comment]
Let's ignore this for now. There are too many terms, but it is useable...
It  is possible that 
GO:0071960 maintenance of mitotic sister chromatid cohesion, centromeric
could be re-purposed for "centromeric cohesion protection"

One thing that could be done now is to merge

meiotic sister chromatid cohesion involved in meiosis I
into 
meiotic sister chromatid cohesion

I think there is some confusion between loading/unloading and positive/negative regulation of establishment/maintenance, but I can revisit the  once I have done a GOCAM. I'm a bit confused about  what we would call part_of and what we would call regulation in this pathway.
This might be a good example.

**Comment by ValWood** [comment]
Will close, pending model and new ticket.
