### ISSUE TITLE
NTR: olfactory sociosexual communication

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#21456]
We don't seem to have a process term to describe the pheromone peptides secreted by mice and other animals, e.g. 

**Kimoto et al.** 2007. Sex- and strain-specific expression and vomeronasal activity of mouse ESP family peptides. Curr Biol. 17(21):1879-84.  **PMID:17935991**
> Male mice secrete exocrine-gland-secreting peptide 1 (ESP1) from the extraorbital lacrimal gland into tear fluid [1]. Other mice detect ESP1 through sensory neurons in the vomeronasal organ (VNO), a secondary olfactory system that senses pheromonal information, including sex, strain, and species. 

Please provide as much information as you can: 

* **Suggested term label:**
olfactory sociosexual communication

* **Definition (free text)**
The use of external chemical cues called pheromones to send social and sexual information between members of the same species, leading to specific behavioral responses. Pheromones may be detected by two olfactory sensory circuits, the main olfactory pathway and the vomeronasal system.

* **Reference, in format PMID:#######**
PMID:17935991, PMID: 29519850, GOC:krc

* **Parent term(s)**
multi-multicellular organism process - GO:0044706

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @krchristie 
This seems to be indeed lacking. 

A few thoughts: 
- Shouldn't 'GO:0071444 cellular response to pheromone' and/or GO:0007635 chemosensory behavior be parents? 
- In any case I would not use multi-multicellular organism process - GO:0044706 as a parent, as this will go away (see discussion for 'regulation #21432 - for some reason there is not ticket about the non-regulatory terms, or I cannot find it right now). I suggest using 'GO:0051703 biological process involved in intraspecies interaction between organisms' and possibly GO:0019098 reproductive behavior? 

Thanks, Pascale

**Comment by krchristie** [comment]
> Hi @krchristie
> This seems to be indeed lacking.
> 
> A few thoughts:
> 
>     * Shouldn't 'GO:0071444 cellular response to pheromone' 

I don't think we want this parentage because I want to be able to annotate the pheromones to the new term as well and it doesn't seem right to annotate the pheromone itself to a "response to pheromone" term.

and/or GO:0007635 chemosensory behavior be parents?

Good point. Looking at the child terms under `chemosensory behavior`, I think that the more specific term `olfactory behavior` is even more appropriate.



>     * In any case I would not use multi-multicellular organism process - GO:0044706 as a parent, as this will go away (see discussion for 'regulation #21432 - for some reason there is not ticket about the non-regulatory terms, or I cannot find it right now). I suggest using 'GO:0051703 biological process involved in intraspecies interaction between organisms' and possibly GO:0019098 reproductive behavior?

> `GO:0051703 biological process involved in intraspecies interaction between organisms`

This term is fine.

> and possibly GO:0019098 reproductive behavior?

`reproductive behavior` would be too specific because I need the new term to cover any social behavior, for example parenting behavior, not just that leading to reproduction. I'll update the definition to include more examples.

Thanks for the great suggestions @pgaudet

**Comment by krchristie** [comment]
Actually, I'm not sure we want `olfactory behavior` as a parent either because I'm specifically trying to create a term that can be used for the pheromones. It seems odd to annotate the pheromone itself to `olfactory behavior`

**olfactory behavior:**
Def: The behavior of an organism in response to an odor.

**Comment by pgaudet** [comment]
> olfactory behavior is part_of my proposed new term olfactory sociosexual communication though, but I don't think that's true either.

sounds reasonable

**Comment by pgaudet** [comment]
> reproductive behavior would be too specific because I need the new term to cover any social behavior, for example parenting behavior,

Parenting behavior is a child of reproductive behavior (just pointing that out because it sounds like you had expected them to be separate?) I saw that recently and I was not sure that was right. 

Anyhow, just wanted to add that I am OK with your other suggestions, and the main point of my response was about 'multi-multicellular organism process - GO:0044706'. 

Thanks, Pascale

**Comment by krchristie** [comment]
> > reproductive behavior would be too specific because I need the new term to cover any social behavior, for example parenting behavior,
> 
> Parenting behavior is a child of reproductive behavior (just pointing that out because it sounds like you had expected them to be separate?) I saw that recently and I was not sure that was right.

I was indeed thinking of reproductive behavior more specifically. Looking at the structure, I don't have any problem with the position of parenting behavior under reproductive behavior. I still don't think I want to assume that the only uses of these pheromones is reproductive behavior. It seems there could be social behaviors that are not reproductive behaviors, perhaps dominance hierarchies between members of the same sex...
 
> Anyhow, just wanted to add that I am OK with your other suggestions, and the main point of my response was about 'multi-multicellular organism process - GO:0044706'.

Thanks for pointing this out. I'll use the parent term you suggested.
