### ISSUE TITLE
link between x any y recently deleted GO:0006753   nucleoside phosphate metabolic process parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21464]
GO:0055086 nucleobase-containing small molecule metabolic process
used to be a parent of
GO:0006753   nucleoside phosphate metabolic process

but was removed recently, which affects slims. 

2021-05-15 | Deleted | RELATION | is a GO:0055086 (nucleobase-containing small molecule metabolic process)

I can't see why?

<img width="619" alt="Screenshot 2021-05-18 at 13 41 23" src="https://user-images.githubusercontent.com/7359272/118652810-dccd5900-b7de-11eb-952a-dc26d28795ac.png">

**Comment by pgaudet** [comment]
I cannot see why that went either. Added back.

**Comment by deustp01** [comment]
@ukemi did we do that? Is it breaking something else?

**Comment by ukemi** [comment]
I'm not sure if it was a result of our ChEBI request. But I suspect the 'small molecule' issue creeps up here and these need to be manually asserted.

**Comment by ukemi** [comment]
I just double-checked and my assumption is correct. GO:0055086 does not have a reference to a ChEBI class, so relations need to be asserted.

**Comment by pgaudet** [comment]
Which PR is this? Can we generate a diff for all 'small molecule' subclasses?

**Comment by ValWood** [comment]
For  some context, the reason we use this term in slims, is that if you go up to the parent
nucleobase-containing compound metabolic process (GO:0006139)
it pulls in 1/3 of the fission yeast genome because it includes every nucleotide containing molecule, RNA,DNA. This is the only way to partition the 'metabolism' part.

I actually wonder why it isn't in all the slims.....
