### ISSUE TITLE
NTR: [proposed new term label] regulation terms  for control of cell size

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21475]
Please provide as much information as you can: 

* **Suggested term label:**
please could I have positive and negative regulation terms for
GO:0061387   regulation of extent of cell growth

* **Definition (free text)**
standard defs

* **Reference, in format PMID:#######**

PMID:25639242
and
PMID: 26776736
and
PMID: 27058310 

are the seminal papers for cell size control by nutrients.

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

No, but the existing children do not belong under here. The are not about regulation of cell size, they are about growth polarity.

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Actually we need to be specific

regulation of extent of cell growth at division
so that 
negative regulation of extent of cell growth at division
can go under
positive regulation of mitotic G2/M transition

and
positive regulation of extent of cell growth at division
can go under
negative regulation of mitotic G2/M transition

what are the rules about negative regulation of positive regulation?

When nutrients are plentiful cells increase their size and divide larger (do G2/M earlier)
When nutrients are scarce cells decrease their size and divide smaller (do G2/M later)
This is basically the cell 'sizer' ...

need to decide whether the specific nutrient response should be included in the term.
discuss with response to nutrient.

**Comment by ValWood** [comment]
edited above comment.

**Comment by pgaudet** [comment]
Are you still waiting for feedback on that one?

**Comment by ValWood** [comment]
This  one is on my list to discuss with JAcky.

**Comment by ValWood** [comment]
Closing, will revisit this. It is soooo complicated.
