### ISSUE TITLE
'pyramidal neuron migration' taxon specificity

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21476]
[pyramidal neuron migration](http://purl.obolibrary.org/obo/GO_0021852) has an inferred taxon constraint to Mammalia. @dustine32 reported that there was an annotation to chicken for this term, and it seems like the term 'pyramidal neuron' is used in chicken.

The taxon constraint is coming through the asserted subclass relationship to [cerebral cortex radial glia guided migration](http://purl.obolibrary.org/obo/GO_0021801). The text definition mentions cerebral cortex directly: "The migration of pyramidal a neuron precursor from the ventricular zone to the correct layer of the cerebral cortex", which is mammal-specific.

@cmungall suggested perhaps the label of this term should be updated to reflect the migration to the cerebral cortex.

**Comment by ukemi** [comment]
Yup TPV. We should change 'pyramidal neuron migration' to pyramidal neuron migration to cerebral cortex'. We should also fix the typo in the definition and put the 'a' in front of pyramidal. PMID:22192824. Should the generic pyramidal migration term also be created? I'm not sure how they come about in non-mammals but I would hypothesize that they still migrate in some way through layers of the brain, maybe along radial glial fibers. Anyone???

**Comment by pgaudet** [comment]
hello, 

* I changed the term label of GO:0021852
from: pyramidal neuron migration
to: pyramidal neuron migration to cerebral cortex
to match the definition
* I corrected the typo in the definition
* I created a new term to allow the annotation of the chicken protein: 
* +[Term]
+id: GO:0140650
+name: radial glia-guided pyramidal neuron migration
+namespace: biological_process
+def: "The radial migration of a pyramidal neuron along radial glial cells." [PMID:3760547]
+synonym: "radial glia-dependent neuronal migration" EXACT []
+is_a: GO:0001764 ! neuron migration
+intersection_of: GO:0016477 ! cell migration
+intersection_of: results_in_movement_of CL:0000598 ! pyramidal neuron
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21476 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-25T12:48:12Z

I hope this resolves the issue. 

Thanks, Pascale

**Comment by pgaudet** [comment]
When the term is available in P2GO we need to reannotate PMID:3760547.

**Comment by pgaudet** [comment]
Fixed annotation.
