### ISSUE TITLE
NTR: Frizzled Nuclear Import pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#21483]
Please provide as much information as you can: 

* **Suggested term label:**
* 
Frizzled Nuclear Import pathway

* **Definition (free text)**
The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell, followed by internalization and cleavage of the frizzled receptor to yeild a C-terminal fragment that is imported into the nucleus. The frizzled C-terminal fragment is incorporated into  large ribonucleoprotein particles and stimulates their egress via nuclear budding.

* **Reference, in format PMID:#######**
PMID:22579286
PMID:22510459

* **Parent term(s)**

GO:0035567 	non-canonical Wnt signaling pathway

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

Plus new regulation terms:
-regulation of Frizzled Nuclear Import pathway
--positive regulation of Frizzled Nuclear Import pathway
--negative regulation of Frizzled Nuclear Import pathway

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

FNI (EXACT)
Frizzled Nuclear Import Wnt Pathway (EXACT)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140709
+name: Frizzled Nuclear Import pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell, followed by internalization and cleavage of the frizzled receptor to yeild a C-terminal fragment that is imported into the nucleus. The frizzled C-terminal fragment is incorporated into large ribonucleoprotein particles and stimulates their egress via nuclear budding." [PMID:22510459, PMID:22579286]
+synonym: "FNI" BROAD []
+synonym: "Frizzled Nuclear Import Wnt Pathway" EXACT []
+is_a: GO:0035567 ! non-canonical Wnt signaling pathway
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21483 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-08T09:11:25Z
+
+[Term]
+id: GO:0140710
+name: regulation of Frizzled Nuclear Import pathway
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of a Frizzled Nuclear Import pathway." [PMID:22510459, PMID:22579286]
+synonym: "regulation of FNI" BROAD []
+synonym: "regulation of Frizzled Nuclear Import Wnt Pathway" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0140709 ! Frizzled Nuclear Import pathway
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21483 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-08T09:14:01Z
+
+[Term]
+id: GO:0140711
+name: positive regulation of Frizzled Nuclear Import pathway
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of a Frizzled Nuclear Import pathway." [PMID:22510459, PMID:22579286]
+synonym: "positive regulation of FNI" BROAD []
+synonym: "positive regulation of Frizzled Nuclear Import Wnt Pathway" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0140709 ! Frizzled Nuclear Import pathway
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21483 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-08T09:17:38Z
+
+[Term]
+id: GO:0140712
+name: negative regulation of Frizzled Nuclear Import pathway
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of a Frizzled Nuclear Import pathway." [PMID:22510459, PMID:22579286]
+synonym: "negative regulation of FNI" BROAD []
+synonym: "negative regulation of Frizzled Nuclear Import Wnt Pathway" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0140709 ! Frizzled Nuclear Import pathway
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21483 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-08T09:18:32Z

**Comment by hattrill** [comment]
Thanks!
