### ISSUE TITLE
NTRs: pyripyropene A metabolic process/ biosynthetic process/ catabolic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21496]
Can I request three new terms please?

Accession: GO:xxxxxx
Name: pyripyropene A metabolic process
Ontology: biological_process
Synonyms: pyripyropene A metabolism
Definition: The chemical reactions and pathways involving pyripyropene A.
is_a: GO:0006714 ! sesquiterpenoid metabolic process
[RO:0004007 relation] RO:0004007: CHEBI:64695 ! pyripyropene A
Source: GOC:ach

Accession: GO:xxxxxx
Name: pyripyropene A biosynthetic process
Ontology: biological_process
Synonyms: pyripyropene A anabolism, pyripyropene A biosynthesis, pyripyropene A formation, pyripyropene A synthesis
Definition: The chemical reactions and pathways resulting in the formation of pyripyropene A.
is_a: GO:0016106 ! sesquiterpenoid biosynthetic process
is_a: GO:xxxxxx ! pyripyropene A metabolic process
[RO:0004008 relation] RO:0004008: CHEBI:64695 ! pyripyropene A
Source: GOC:ach

Accession: GO:xxxxxx
Name: pyripyropene A catabolic process
Ontology: biological_process
Synonyms: pyripyropene A breakdown, pyripyropene A catabolism, pyripyropene A degradation
Definition: The chemical reactions and pathways resulting in the breakdown of pyripyropene A.
is_a: GO:0016107 ! sesquiterpenoid catabolic process
is_a: GO:xxxxxx ! pyripyropene A metabolic process
[RO:0004009 relation] RO:0004009: CHEBI:64695 ! pyripyropene A
Source: GOC:ach

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Hi @Achchuthan 

Can you please provide references for those terms?

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Here are some references: PMID:21224862, PMID:26019565, PMID:32546620, https://www.sciencedirect.com/topics/chemistry/pyripyropene-a

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Hi Ach, 

I see description of biosynthesis of pyripyropene A in PMID:21224862 and PMID:26019565, but I dont see evidence for a specific degradation pathway. 
* I dont see how PMID:25005817 and PMID:32546620 describe either biosynthesis or catabolism. 

If that's OK with you I would only create the 'biosynthesis' terms, since there is no evidence for a specific degradation pathway (and possibly also for the other similar tickets you have created). 

Does that work for you? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140652
+name: pyripyropene A biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of pyripyropene A." [GOC:ach, PMID:21224862, PMID:26019565]
+synonym: "pyripyropene A anabolism" EXACT []
+synonym: "pyripyropene A biosynthesis" EXACT []
+synonym: "pyripyropene A formation" EXACT []
+synonym: "pyripyropene A synthesis" EXACT []
+is_a: GO:0009058 ! biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21496 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-27T08:33:29Z

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Thanks a lot for the term for biosynthesis. This term is sufficient for my work.

Best wishes,
Achchuthan

**Comment by pgaudet** [comment]
I still need to add the LD, waiting for the chebi imports, as this compound was not loaded.
