### ISSUE TITLE
Term obsoletion: [GO:0031660 regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21493]
**Term to be merged: Provide GO ID and term label **

GO:0031660    regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle

**Which term do you propose this term merge into? Provide GO ID and term label **
GO:0010389    regulation of G2/M transition of mitotic cell cycle

**Reason for merge**

there  is no difference between these terms.

GO:0010389 is defined as a regulation of CDK:
Any signalling pathway that modulates the activity of a cell cycle cyclin-dependent protein kinase to modulate the switch from G2 phase to M phase of the mitotic cell cycle. 

2 EXP , FlyBase

**Comment by pgaudet** [comment]
@hattrill FYI

**Comment by pgaudet** [comment]
I will obsolete 
 GO:0031660 regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic and child
GO:0031661 negative regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle 

Since they don't make much sense as synonyms of other terms.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0031660 regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic and descendant
GO:0031661 negative regulation of cyclin-dependent protein serine/threonine kinase activity involved in G2/M transition of mitotic cell cycle

The reason for obsoletion is that these terms are MFs represented as BPs. 

There is 1 annotation to GO:0031660 by FlyBase, that can be reannotated to GO:0010389 regulation of G2/M transition of mitotic cell cycle. 

There are no mappings; these terms are not present in any subsets. 

You may comment on this ticket: https://github.com/geneontology/go-ontology/issues/21493

Thanks, Pascale

**Comment by hattrill** [comment]
Updated the FB annotation.

**Comment by pgaudet** [comment]
Thanks!
