### ISSUE TITLE
NTRs: fumitremorgin C metabolic process/ biosynthetic process/ catabolic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21494]
Can I request the following three terms please?

Accession: GO:xxxxxx
Name: fumitremorgin C metabolic process
Ontology: biological_process
Synonyms: fumitremorgin C metabolism
Definition: The chemical reactions and pathways involving fumitremorgin C.
is_a: GO:0019748 ! secondary metabolic process
is_a: GO:1901376 ! organic heteropentacyclic compound metabolic process
is_a: GO:0035834 ! indole alkaloid metabolic process
[RO:0004007 relation] RO:0004007: CHEBI:72763 ! fumitremorgin C
Source: GOC:ach

Accession: GO:xxxxxx
Name: fumitremorgin C biosynthetic process
Ontology: biological_process
Synonyms: fumitremorgin C anabolism, fumitremorgin C biosynthesis, fumitremorgin C formation, fumitremorgin C synthesis
Definition: The chemical reactions and pathways resulting in the formation of fumitremorgin C.
is_a: GO:0044550 ! secondary metabolite biosynthetic process
is_a: GO:1901378 ! organic heteropentacyclic compound biosynthetic process
is_a: GO:0035835 ! indole alkaloid biosynthetic process
is_a: GO:xxxxxx ! fumitremorgin C metabolic process
[RO:0004008 relation] RO:0004008: CHEBI:72763 ! fumitremorgin C
Source: GOC:ach

Accession: GO:xxxxxx
Name: fumitremorgin C catabolic process
Ontology: biological_process
Synonyms: fumitremorgin C breakdown, fumitremorgin C catabolism, fumitremorgin C degradation
Definition: The chemical reactions and pathways resulting in the breakdown of fumitremorgin C.
is_a: GO:0090487 ! secondary metabolite catabolic process
is_a: GO:1901377 ! organic heteropentacyclic compound catabolic process
is_a: GO:0009822 ! alkaloid catabolic process
is_a: GO:xxxxxx ! fumitremorgin C metabolic process
[RO:0004009 relation] RO:0004009: CHEBI:72763 ! fumitremorgin C
Source: GOC:ach

Thanks,
Achchuthan

**Comment by Achchuthan** [comment]
Here are some references: PMID:19226505, PMID:32546620, https://www.sciencedirect.com/topics/chemistry/fumitremorgin-c.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140653
+name: fumitremorgin C biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of fumitremorgin C." [GOC:ach, PMID:19226505]
+synonym: "fumitremorgin C anabolism" EXACT []
+synonym: "fumitremorgin C biosynthesis" EXACT []
+synonym: "fumitremorgin C formation" EXACT []
+synonym: "fumitremorgin C synthesis" EXACT []
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:72763 ! fumitremorgin C
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21494 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-27T08:37:11Z

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Thanks a lot for the term for biosynthesis. This term is sufficient for  my work.

Best wishes,
Achchuthan
