### ISSUE TITLE
NTRs: tryprostatin A metabolic process/ biosynthetic process/ catabolic process

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21495]
Can I request the following three new terms please?

Accession: GO:xxxxxx
Name: tryprostatin A metabolic process
Ontology: biological_process
Synonyms: tryprostatin A metabolism
Definition: The chemical reactions and pathways involving tryprostatin A.
is_a: GO:0035834 ! indole alkaloid metabolic process
[RO:0004007 relation] RO:0004007: CHEBI:72761 ! tryprostatin A
Source: GOC:ach

Accession: GO:xxxxxx
Name: tryprostatin A biosynthetic process
Ontology: biological_process
Synonyms: tryprostatin A anabolism, tryprostatin A biosynthesis, tryprostatin A formation, tryprostatin A synthesis
Definition: The chemical reactions and pathways resulting in the formation of tryprostatin A.
is_a: GO:0035835 ! indole alkaloid biosynthetic process
is_a: GO:xxxxxx ! tryprostatin A metabolic process
[RO:0004008 relation] RO:0004008: CHEBI:72761 ! tryprostatin A
Source: GOC:ach

Accession: GO:xxxxxx
Name: tryprostatin A catabolic process
Ontology: biological_process
Synonyms: tryprostatin A breakdown, tryprostatin A catabolism, tryprostatin A degradation
Definition: The chemical reactions and pathways resulting in the breakdown of tryprostatin A.
is_a: GO:0009822 ! alkaloid catabolic process
is_a: GO:xxxxxx ! tryprostatin A metabolic process
[RO:0004009 relation] RO:0004009: CHEBI:72761 ! tryprostatin A
Source: GOC:ach

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Hi @Achchuthan 

Can you please provide references for those terms?

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Here are some references:

- PMID:32546620 is a reference from _Aspergillus fumigatus_, where gene knockout results in increased biosynthesis of tryprostatin A.
- https://www.sciencedirect.com/topics/chemistry/tryprostatin-a - This reference mentions about the metabolism of tryprostatin A into fumitremorgin C.
- PMID:19226505 - This publication also mentions the isolation of tryprostatin A from _Aspergillus fumigatus_.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140654
+name: tryprostatin A biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of tryprostatin A." [GOC:ach, PMID:19226505]
+synonym: "tryprostatin A anabolism" EXACT []
+synonym: "tryprostatin A biosynthesis" EXACT []
+synonym: "tryprostatin A formation" EXACT []
+synonym: "tryprostatin A synthesis" EXACT []
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:72761 ! tryprostatin A
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21495 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-27T08:39:56Z
