### ISSUE TITLE
GO:0030048 actin filament-based movement

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21502]
~GO:0000916  actomyosin contractile ring contraction
Definition 
The process of an actomyosin ring getting smaller in diameter, in the context of cytokinesis that takes place as part of a cell cycle
(this definition is not great)~

~should be a child of~
GO:0030048	actin filament-based movement.  
Movement of organelles or other particles along actin filaments, or sliding of actin filaments past each other, mediated by motor proteins.

because it proceeds by "the  sliding of actin filaments past each other, mediated by motor proteins"

**Comment by pgaudet** [comment]
Are you sure about that one? Actin filament-based movement may be mediated by motor proteins, but does that imply that any process mediated by motor proteins is movement? 

GO:0006928  movement of cell or subcellular component is defined as "The directed, self-propelled movement of a cell or subcellular component without the involvement of an external agent such as a transporter or a pore. " -  Is contractile ring contraction a type of  _directed, self-propelled movement_ ?

**Comment by ValWood** [comment]
I think I misinterpreted the definition. I assumedthat anything involving sliding  actin filament past each other was 'movement' . In this case, I am not sure there is an  "actin based-movement" in fission yeast....

**Comment by ValWood** [comment]
GO:0030048 actin filament-based movement.
Movement of organelles or other particles along actin filaments, or sliding of actin filaments past each other, mediated by motor proteins.

is an odd grouping term.
The first part  Movement of organelles or other particles along actin filaments,
is describing transport, the second part is describing sliding?

**Comment by pgaudet** [comment]
We have 

**[Current term] GO:0030048 actin filament-based movement**
                 [is_a relation] GO:0070252 actin-mediated cell contraction
                 [is_a relation] GO:0034642 mitochondrion migration along actin filament
                 [is_a relation] GO:0031022 nuclear migration along microfilament
                 [positively_regulates relation] GO:1903116 positive regulation of actin filament-based movement
                 [regulates relation] GO:1903115 regulation of actin filament-based movement
                 [is_a relation] GO:0030050 vesicle transport along actin filament 


and 
**[Current term] GO:0007018 microtubule-based movement**
                 [is_a relation] GO:0051305 chromosome movement towards spindle pole
                 [is_a relation] GO:0003341 cilium movement
                 [is_a relation] GO:0034643 establishment of mitochondrion localization, microtubule-mediated
                 [is_a relation] GO:0099606 microtubule plus-end directed mitotic chromosome migration
                 [is_a relation] GO:0099098 microtubule polymerization based movement
                 [is_a relation] GO:0051012 microtubule sliding
                 [is_a relation] GO:0099111 microtubule-based transport
                 [regulates relation] GO:0060632 regulation of microtubule-based movement
                 [is_a relation] GO:0140405 spindle pole body-led chromosome movement during mitotic interphase

How do you recommend grouping?

**Comment by ValWood** [comment]
Actually based on the children, the grouping makes sense.
I was wondering what the real distinction was between the 'organization' and the 'movement' terms...but ignore. Not important. I guess logical defs will find any anomolies.
