### ISSUE TITLE
filter out Rhea xrefs that are not yet published

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21509]

**Comment by balhoff** [comment]
Obsoletion check: #21347

**Comment by ukemi** [comment]
Would it be better to just have non-valid Rhea xrefs, obsolete or typos?

**Comment by balhoff** [comment]
I thought it would make sense to fail for obsoletes, so they can be fixed, but just filter unpublished ones. Unfortunately this will kind of hide typos.

**Comment by ukemi** [comment]
It would be nice to try to catch the typos too. Could you somehow make it 'aware' of the new Rhea release and if the 'unreleased' don't go away, then there is likely a typo that needs to be addressed. Or am I making this way too difficult?
