### ISSUE TITLE
NTR: positive regulation of cell cycle switching, mitotic to meiotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21506]
Please provide as much information as you can: 

* **Suggested term label:**

positive regulation of cell cycle switching, mitotic to meiotic cell cycle ,
* **Definition (free text)**

standard

* **Reference, in format PMID:#######**

PMID:22375066

* **Parent term(s)**

GO:0110044 | regulation of cell cycle switching, mitotic to meiotic cell cycle
-- | --

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+id: GO:0140648
+name: positive regulation of cell cycle switching, mitotic to meiotic cell cycle
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of mitotic to meiotic cell cycle switching, the process in which a cell switches cell cycle mode from mitotic to meiotic division." [PMID:22375066]
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21506 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-25T06:18:49Z
+
