### ISSUE TITLE
telomere maintenance (GO:0000723) parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21504]
telomere maintenance (GO:0000723) has the parent  anatomical structure homeostasis.

I don't think this is correct because everything has a "regulation of biological quality"

but not all of the sub processes are regulatory (telomere replication for example)

This does not seem as though it should have a homeostasis parent?

**Comment by pgaudet** [comment]
The children of  'anatomical structure homeostasis'
do not provide a very logical grouping: 

'germ-line stem-cell niche homeostasis'
'maintenance of lens transparency'
'muscle cell cellular homeostasis'
'neuron cellular homeostasis'
'telomere maintenance'
'tissue homeostasis'

I am removing 'telomere maintenance' from under here. We can decide if something needs to be done about his branch at a later point. 

Thanks, Pascale

**Comment by ValWood** [comment]
Thanks. That will be helpful in my 'review' of where we use "regulation" terms.
I don't think it belongs here.  Other problems for later ;)
