### ISSUE TITLE
Broaden definition for GO:0062154 "N6-mAMP deaminase activity"

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#21501]
Current definition: Catalysis of the reaction: H(+) + H2O + N6-methyl-AMP = IMP + methylamine. (corresponds to [RHEA:16002](https://www.rhea-db.org/rhea/16002). PMID: 21755941 presents evidence that the the same enzyme that mediates this reaction acts as well on N6-methyl-dAMP, and PMID:32144205 discusses (Figure 9) plausible biological roles for reactions involving both N6-methyl-AMP and N6-methyl-dAMP.
Could we either broaden the name and definition or create a new term for the activity on N6-methyl-dAMP?
New name - N6-m(d)AMP deaminase activity
New definition - Catalysis of the reaction: H(+) + H2O + N6-methyl-(d)AMP = (d)IMP + methylamine.

**Comment by pgaudet** [comment]
Added to the definition: "Can also use N6-methyl-dAMP as a substrate." 

I could not find the exact reaction.
