### ISSUE TITLE
NTR: [futile creatine cycle]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#21517]
Please provide as much information as you can: 

* **Suggested term label:** Futile creatine cycle

* **Definition (free text)** The phosphorylation and dephosphorylation of creatine in a futile cycle, which dissipates the high energy charge of phosphocreatine as heat without performing any mechanical or chemical work. The futile creatine cycle takes place in thermogenic fat cells and is part of adaptive thermogenesis.

* **Reference, in format PMID:33597756, PMID:33981039**

* **Parent term(s)** Part_of GO:1990845; P:adaptive thermogenesis

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by deustp01** [comment]
Parentage: also is_a  GO:0006600 creatine metabolic process ?

**Comment by sylvainpoux** [comment]
Good point, yes, as it mediates both synthesis and catabolism of phosphocreatine

**Comment by pgaudet** [comment]
Created new term: 

 
+[Term]
+id: GO:0140651
+name: futile creatine cycle
+namespace: biological_process
+def: "The phosphorylation and dephosphorylation of creatine in a futile cycle, which dissipates the high energy charge of phosphocreatine as heat without performing any mechanical or chemical work. The futile creatine cycle takes place in thermogenic fat cells and is part of adaptive thermogenesis." [PMID:33597756, PMID:33981039]
+is_a: GO:0008152 ! metabolic process
+relationship: has_part GO:0004111 ! creatine kinase activity
+relationship: has_part GO:0050187 ! phosphoamidase activity
+relationship: part_of GO:1990845 ! adaptive thermogenesis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21517 xsd:anyURI
+created_by: pg
+creation_date: 2021-05-26T06:40:18Z

**Comment by pgaudet** [comment]
Added EC and RHEA xrefs to reactions part of this process (and sibling): 

- GO:0101006  protein histidine phosphatase activity
- +xref: EC:3.9.1.3
- +xref: RHEA:47964

- GO:0098627  protein arginine phosphatase activity
- +xref: EC:3.9.1.2
- +xref: RHEA:43380

Also the grouping class: GO:0016825  hydrolase activity, acting on acid phosphorus-nitrogen bonds
Changed xref: EC:3.9.-.- to  EC:3.9.1.-


Thanks, Pascale
