### ISSUE TITLE
missing parent "regulation of cytoplasmic translational initiation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21520]
GO:1990611
"regulation of cytoplasmic translational initiation in response to stress"
is not a descendant of 

GO:0002813
cytoplasmic translational initiation

**Comment by pgaudet** [comment]
Hi @ValWood 
I wonder why this is precomposed; I thought you captured 'response to' as extension?

**Comment by pgaudet** [comment]
There is no logical definition for this term (and the parents). How about, for GO:0043555 regulation of translation in response to stress: 

is_a GO:0065007 ! biological regulation
 regulates GO:0006412 ! translation
 happens_during GO:0033554 ! cellular response to stress

Note that it would then loose is_a cellular response to stress. 

Is that OK ? If so, I'll add the others on that model. 

Thanks, Pascale
+intersection_of:

**Comment by ValWood** [comment]
>  wonder why this is precomposed; I thought you captured 'response to' as extension?

I would prefer that especially for pathways that are activated in response to many different stresses (oxidative, osmotic, nitrosative etc). Or that we get rid of all the chemicals used as ways to induce these stresses .......but I think there is some room for very general stress terms.

I would be happy to do either way. We use those to be consistent. If we pick up mappings it looks odd to not have other pathway parts annotated in the same way. So I guess I use the terms if they exist, but I don't  request new  precomposed terms....
