### ISSUE TITLE
NTR: UDP-beta-L-arabinofuranose transport & transporter

### ISSUE THREAD

**Issue by jaiswalp** [geneontology/go-ontology#21524]
Please provide as much information as you can: 

* **Suggested term label:**
UDP-beta-L-arabinofuranose transport (process)
UDP-beta-L-arabinofuranose transporter activity (function)

* **Definition (free text)**

* **Reference, in format PMID:#######**
https://www.pnas.org/content/114/16/4261
PMID: 28373556

* **Parent term(s)**
GO:0015750 pentose transmembrane transport
GO:0015144 carbohydrate transmembrane transporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140819
+name: UDP-beta-L-arabinofuranose transporter activity
+namespace: molecular_function
+def: "Enables the transfer of UDP-beta-L-arabinofuranose from one side of a membrane to the other." [PMID:28373556]
+intersection_of: GO:0005215 ! transporter activity
+intersection_of: has_primary_input CHEBI:61463 ! UDP-beta-L-arabinofuranose(2-)
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+relationship: part_of GO:0055085 ! transmembrane transport
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21524 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-16T06:45:42Z
+
+[Term]
+id: GO:0140820
+name: cytosol to Golgi apparatus transport
+namespace: biological_process
+def: "The directed movement of substances from the cytosol into the Golgi apparatus of a cell." [GOC:ai]
+intersection_of: GO:0055085 ! transmembrane transport
+intersection_of: has_target_end_location GO:0005794 ! Golgi apparatus
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21524 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-16T06:59:22Z
+
+[Term]
+id: GO:0140821
+name: cytosol to Golgi apparatus UDP-beta-L-arabinofuranose transport
+namespace: biological_process
+def: "The directed movement of UDP-beta-L-arabinofuranose from the cytosol to the Golgi apparatus of a cell." [GOC:ai]
+intersection_of: GO:0055085 ! transmembrane transport
+intersection_of: has_primary_input CHEBI:61463 ! UDP-beta-L-arabinofuranose(2-)
+intersection_of: has_target_end_location GO:0005794 ! Golgi apparatus
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0016020 ! membrane

**Comment by pgaudet** [comment]
@jaiswalp Sorry about the delay in creating this term. Note that I create a more precise BP, 'cytosol to Golgi apparatus UDP-beta-L-arabinofuranose transport', since this is the pathway that the paper you cite was describing. 

Thanks, Pascale
