### ISSUE TITLE
Correct directional RHEA assignments

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#21534]
Per this file from @amorgat 
[GO2dirRhea_2021-05-30_118.xlsx](https://github.com/geneontology/go-ontology/files/6576501/GO2dirRhea_2021-05-30_118.xlsx)
Dear Harold, Pascale,
 
When we tested the search of GO terms in the new web site with Parit, we realized that we still have some GO terms (37)  that are mapped to directed Rhea IDs.
See attached excel file (GO2dirRhea_2021-05-30_118.xlsx)
The column rheaid contains the mapped Rhea ID that should be replaced by the ID of the rhea column (undefined direction).
Column direction:
  BI: bidirectional
  LR: Left-to-Right
  RL: Right-to-Left
All the best,
Anne

**Comment by hdrabkin** [comment]
Hi @amorgat 
The first on the list




<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/hjd/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/hjd/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>





27321 | 3-epi-6-deoxocathasterone C-23 hydroxylase   activity | 102136 | 27318
-- | -- | -- | --

**Comment by hdrabkin** [comment]
Spreadsheet with progress thus far; green means done; brick means 'think about it' ; black means rhea needs to recheck (see above). 
[GO2dirRhea_2021-06-04-hjd.xlsx](https://github.com/geneontology/go-ontology/files/6601238/GO2dirRhea_2021-06-04-hjd.xlsx)

**Comment by hdrabkin** [comment]
@deustp01 , @ukemi ; what do you think?

RHEA: 21252 GO:0047545 2-hydroxyglutarate dehydrogenase activity ;parent ; exp annotations; 14
     RHEA: 21254 GO:0061759  alpha-ketoglutarate reductase activity (Add "reverse reaction")  exp annotations: 6
     RHEA:21253  GO:0061758 2-hydroxyglutarate dehydrogenase activity, forward reaction; no annotations.
Should we merge these if forward reaction not used, and reverse only 6?

**Comment by ValWood** [comment]
@pgaudet  is this still current? Should it have Rhea alignment project?

**Comment by pgaudet** [comment]
Out of date.
