### ISSUE TITLE
NTR: mitochondrion activation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21538]
Hi 
It seems like the role of mitochondria in the cell is not well described in GO.

Their role in apoptosis is captured and yet the idea of increasing the activity of a mitochondria or increasing the number of mitochondria is not. see related ticket: https://github.com/geneontology/go-ontology/issues/21537

Please provide as much information as you can: 

* **Suggested term label: regulation of mitochondrion activity**

* **Definition (free text)**
A change in the activity of a mitochondrion resulting from exposure of the cell to an factor such as a cellular or soluble ligand or environmental trigger. 

* **Reference, in format PMID: 28467929**

* **Parent term(s)**
 GO:0050794 regulation of cellular process

* **Children terms (if applicable)** 
*positive regulation of mitochondrion activity*
*negative regulation of mitochondrion activity*
* **Any other information**
PMID: 28467929 https://pubmed.ncbi.nlm.nih.gov/28467929/ describes how PPARγ inhibits TGFβ1-induced mitochondrial activation. I don't want to annotate the  PPARγ and TGFβ1 pathway proteins as regulating the 'read-outs' of the activity of the mitochondria, ie positive regulation of mitochondrial membrane potential or positive regulation of glucose metabolism instead I think a term describing the regulation of the mitochondrial activity would be more useful.

I have not included the definitions of the child terms as I am not sure you will agree to the need for these terms

Ruth

**Comment by ValWood** [comment]
How would "mitochondrial activity" be defined?

**Comment by RLovering** [comment]
I guess I was going with the definition I added above: A change in the activity of a mitochondrion resulting from exposure of the cell to an factor such as a cellular or soluble ligand or environmental trigger.

maybe this is more of a phenotype.

I will close this as I don't have time to fully investigate mitochondria biology

Thanks

Ruth
