### ISSUE TITLE
NTR: regulation of oxytocin secretion

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21535]
Please provide as much information as you can: 

* **regulation of oxytocin secretion**

* **Definition (free text)** Any process that modulates the rate, frequency, or extent of the regulated release of a oxytocin.

* **Reference, in format PMID:25096581**

* **Parent term(s)**
 GO:0036162 oxytocin secretion

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
**positive regulation of oxytocin secretion**

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* need to have the regulation terms in line with the other hormone secretion terms

**Comment by pgaudet** [comment]
Hi @RLovering 
Should we treat this like the cytokines and use 'regulation of production' instead? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note that     GO:0036162  oxytocin secretion has no reference and no annotations.

**Comment by RLovering** [comment]
yes please do change to 'regulation of  oxytocin production' and create the positive regulation of oxytocin production term too

Many thanks

Ruth

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140667
+name: regulation of oxytocin production
+namespace: biological_process
+def: "Any process that modulates the frequency, rate, or extent of production of oxytocin." [PMID:25096581]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0036162 ! oxytocin production
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21535 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-24T11:28:07Z
+
+[Term]
+id: GO:0140668
+name: positive regulation of oxytocin production
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of production of oxytocin." [PMID:25096581]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0036162 ! oxytocin production
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21535 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-24T11:31:26Z
+
+[Term]
+id: GO:0140669
+name: negative regulation of oxytocin production
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the rate of production of oxytocin." [PMID:25096581]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0036162 ! oxytocin production
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21535 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-24T11:31:45Z
+

**Comment by pgaudet** [comment]
Plus changed oxytocin secretion to oxytocin production (term label + defs)
