### ISSUE TITLE
missing parent [positive regulation of mating projection formation]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21557]
This process is part_of conjugation with cellular fusion, but because annotations are not inherited over part_of these annotations are not propagated.

Could a part_of relationship be added between 
positive regulation of mating projection formation
and conjugation with cellular fusion?

Is that allowed?

**Comment by ValWood** [comment]
![Uploading Screenshot 2021-06-03 at 17.58.51.png…]()

**Comment by mah11** [comment]
>  but because annotations are not inherited over part_of

???

yes they are! (and I know you knew that)

The actual reason these two terms aren't connected any more is that GO's reasoning used to infer "regulates a whole process" from "regulates part of the process", but doesn't any more. Tickets #12344, #13926, and #20069 have info; the best summary is probably [this comment](https://github.com/geneontology/go-ontology/issues/13926#issuecomment-460278383).

> Could a part_of relationship be added between
> positive regulation of mating projection formation
> and conjugation with cellular fusion?

I'll leave it for the GO editors to answer this properly, but I suspect the best relation might be `regulates` or `positively_regulates` (i.e. positive regulation of mating projection formation regulates conjugation with cellular fusion).

**Comment by ValWood** [comment]
> but because annotations are not inherited over part_of
I meant, in this instance.

But I see now that it is because of the propagation over regulates.

I think a fix might be to add the part_of relationship between 

positive regulation of mating projection formation
and positive regulation of conjugation with cellular fusion?

**Comment by pgaudet** [comment]
Added positive regulation of mating projection formation
part_of GO:0031139 ! positive regulation of conjugation with cellular fusion
