### ISSUE TITLE
NTR: 'daytime sleep' and 'nighttime sleep'

### ISSUE THREAD

**Issue by Clare72** [geneontology/go-ontology#21550]
[PMID:22375135](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3286790/) describes quantitative differences between daytime and nighttime sleep in Drosophila and genetic factors that can differentially affect daytime and nighttime sleep.

suggested definitions:
'daytime sleep' - 'Sleep that occurs during the daytime (light period).'
'nighttime sleep' - 'Sleep that occurs during the nighttime (dark period).'

These should be subclasses of GO:0030431 'sleep'

@hattrill @arzuozturk

**Comment by arzuozturk** [comment]
Thanks Clare!

**Comment by krchristie** [comment]
Hi @Clare72 

It seems that we might want to have a taxon constraint on these terms and/or to add a bit to the definitions. Right now the definitions could apply to a human that took a nap in the daytime, which is OK if we think "daytime sleep" is a similar kind of sleep in fruit flies and humans. We should also consider if need to specify that the animal is diurnal, as a nocturnal animal would likely have a different sleep patterns with the longer sleep being in the daytime.

I'll also point out another ticket that brings up some issues in the regulation of sleep terms. :  **NTR: Sleep homeostasis terms** #20499 

So another question is whether:
1. "nighttime sleep" and "daytime sleep" are different types of sleep, **OR**
2. the same kind of sleep but there are different nighttime and daytime regulatory process controlling one kind of sleep.

Also, I normally include the GOC reference of the requester when I make new terms from their requests, but I don't see an entry for you in the GO users file. Below is a portion of the entry for Helen's entry, where her GO reference is "**GOC:ha**". To make an entry for you, I would need your full name, your preference for your GOC reference, typically initials, provided that reference isn't in use for someone else as it has to be unique. Some GOC references are just two initials as for Helen, or three initials for my GO reference (**GOC:krc**), or some people have more than 3 initials. Another option is to add a number as in this case: **GOC:jh2**.  Let me know your preference. I can also include and ORCID if you have one.

<pre>
accounts:
    github: hattrill
  email-md5:
    - 82989df351e8628287c7d71227c299cb
    - 8f2851f24e6a524cc10da6bb2a72e7eb
  groups:
    - 'http://flybase.org'
  nickname: 'Helen Attrill'
  organization: FlyBase
  uri: 'http://orcid.org/0000-0003-3212-6364'
  xref: 'GOC:ha'
</pre>

Thanks,

-Karen

**Comment by Clare72** [comment]
Yes, I was intentionally using flexible definitions. I am not an expert in this and cannot comment on how similar 'daytime sleep' (or 'sleep' in general for that matter) is across different organisms. I think most animals that sleep have different patterns of sleep in daytime and nighttime, so I thought that these terms would be useful to link genes from any species to one or the other (may help scientists answer the questions you pose).

I am not currently in that file, I suppose I don't mind being added:

```
accounts:
    github: Clare72
  groups:
    - 'http://flybase.org'
  nickname: 'Clare Pilgrim'
  organization: FlyBase
  uri: 'http://orcid.org/0000-0002-1373-1705'
  xref: 'GOC:cp'
```

**Comment by raymond91125** [comment]
I've inquired a sleep scientist who thinks that 'daytime' and 'nighttime' sleep regulation and function differences are yet to be settled. Furthermore, nocturnal organisms (e.g. rodents) would have the opposite effect thus the proposed names are not general. Is it possible to annotate to sleep with some extension to specify the time of day if needed?

**Comment by Clare72** [comment]
Ok, thanks for considering this. It might be possible to combine 'sleep' with 'light phase' and 'dark phase' from PATO instead.
