### ISSUE TITLE
GO:0004528    phosphodiesterase I activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21569]
Is defined:
Catalysis of the sequential hydrolytic removal of 5'-nucleotides from the 3'-hydroxy termini of 3'-hydroxy-terminated oligonucleotides.

but has synonyms

5'-nucleotide phosphodiesterase activity | related
5'-phosphodiesterase activity | related

these seem a bit confusing, because isn't it a  3'-phosphodiesterase?

If so could this (3'-phosphodiesterase)  synonym be added as exact?
Could the name be swapped to describe the activity rather than a gene product?

**Comment by ValWood** [comment]
I was checking annotations to this review abstract PMID:34083046

**Comment by mah11** [comment]
>  isn't it a 3'-phosphodiesterase?

No. Perhaps the def could be changed to make it clearer, but the "5'-" in the synonyms is correct, and refers to the fact that one of the products is a nucleoside 5'-monophosphate (the other is the rest of the double-stranded oligonucleotide).

In other words, it's named for which position on the released NMP product is phosphorylated, not which end of the substrate oligo it acts on.

> Could the name be swapped to describe the activity rather than a gene product?

This is a good idea.

**Comment by ValWood** [comment]
OK, also Pombase and TAIR annotate apn1 to "GO:0004528 phosphodiesterase I activity
" and this has been transferred by PAINT. I will open an annotation tracker ticket for that, but I can't find a term describing a "3'-phosphodiesterase". Apn1 is a 3'phosphodiesterase

https://www.pombase.org/reference/PMID:24559510
&
PMID:34083046

I  will update the annotation once the term exists.

**Comment by mah11** [comment]
The only things that come up easily when I search for "3'-phosphodiesterase" is 2',3'-cyclic-nucleotide 3'-phosphodiesterase activity - which is GO:0004113 - and APE2 and its orthologs. I don't think APE2 has the GO:0004113 activity, but I also don't know what they mean by 3'-phosphodiesterase in the APE2 papers.

**Comment by EricaBakker** [comment]
What does TAIR need to do? Any specific genes that need updating?

**Comment by EricaBakker** [comment]
To confirm I update those GO terms only for this gene in TAIR:  AT4G36050.1 (aka APE2:APURINIC/APYRIMIDINIC ENDONUCLEASE2

**Comment by EricaBakker** [comment]
The discussion above is not clear to me, can someone tell me which GO terms need to be changed to what?

**Comment by ValWood** [comment]
I am not sure either. The reviews  and manuscripts refer to a "3'-phosphodiesterase"
and the GO term used is a 5'-phosphodiesterase. I am hoping @hdrabkin  will  be able to help...either the publications are incorrect, or the GO term we used is incorrect but there is not a  term for the  3'-phosphodiesterase.

**Comment by hdrabkin** [comment]
Does this help?

Catalysis of the sequential hydrolytic removal of 5'-nucleotides from the 3'-hydroxy termini of 3'-hydroxy-terminated oligonucleotides.

removes 5'pNMP, (ie, what is removed)

but has synonyms

5'-nucleotide phosphodiesterase activity | related (what is removed)
5'-phosphodiesterase activity | related (what is removed)

these seem a bit confusing, because isn't it a 3'-phosphodiesterase?
* this bit refers to what end the removal is from. ?

**Comment by ValWood** [comment]
OK,  does that mean that this is a 5'phosphodiesterase, and the papers describing apn1 as 3' phosphodiesterase are incorrect? Is that right?

**Comment by hdrabkin** [comment]
If the reaction removes nucleotides from the 3 end it is  a 3- phosphodiesterase. It generates 5'-NMPs in doing to

**Comment by ValWood** [comment]
OK, so back to the first question, do these synonyms need removing?

and could the term be renamed to describe the activity rather than the gene product name?

**Comment by ValWood** [comment]
pinging @hdrabkin

**Comment by hdrabkin** [comment]
I can't seem to come up with any literature removing NTs sequentially from the 5' end (searching for 5'-phosphodiesterase', but it is a Monday. I've also reached out to my expert contact at MIT (UL RajBhandary)  for nomenclature conventions here.

**Comment by hdrabkin** [comment]
AND, my expert reminded me about 
Spleen Phosphodiesterase, which works from the 5'-end, as well as a phosphodiesterase that works after CAP removal which degrades from 5'end . So I will change the term in question here from  phosphodiesterase I to 3'-phosphodiesterase activity and make the old term name a synonym.
THEN make 5'activity .

**Comment by hdrabkin** [comment]
I think phosphodiesterase 1 is meant for the removal from the 3' end, and phosphodiesterase II is meant for removal at the 5'end. 
It seems like ec as synonyms for PDE II as 3'-phopshodiesterase, as PDE 1 has 5' phosphodiesterase to confuse things.

**Comment by ValWood** [comment]
Tracing from the mouse rat annotations
phosphdiesterase I appears to be
https://iubmb.qmul.ac.uk/enzyme/EC3/1/4/1.html
oligonucleotide 5'-nucleotidohydrolase

**Comment by ValWood** [comment]
Will close this. I'm not sure what the outcome was but the term is essentially correct. Any issue here should eventually be fixed by Rhea alignment.
