### ISSUE TITLE
missing parent [GO:0061987   negative regulation of transcription from RNA polymerase II promoter by glucose]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21568]
GO:0061987    negative regulation of transcription from RNA polymerase II promoter by glucose

is not currently a descendent of

GO:0000122
Term name | negative regulation of transcription by RNA polymerase II

<br class="Apple-interchange-newline">

**Comment by ValWood** [comment]
a template for missing parentage would be good .

**Comment by pgaudet** [comment]
Shouldn't this be obsoleted?

**Comment by ValWood** [comment]
yes, I think this ticket might have pre-dated the  decision.

**Comment by ValWood** [comment]
I think it is already in an obsoletion list. PomBase annotations are already  removed. 22 others remaining.
