### ISSUE TITLE
GO:0000139    Golgi membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21576]
shouldn't GO:0000139    Golgi membrane
be a child of
GO:0005794   Golgi apparatus
rather than
GO:0098791    Golgi apparatus subcompartment?

(not sure if GO:0098791    Golgi apparatus subcompartment is necessary?)

**Comment by pgaudet** [comment]
Changed: 

From
-intersection_of: bounding_layer_of GO:0098791 ! Golgi apparatus subcompartment
-relationship: part_of GO:0005794 ! Golgi apparatus

to: 
+intersection_of: bounding_layer_of GO:0005794 ! Golgi apparatus
