### ISSUE TITLE
NTR: [endonuclease activator activity]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21574]
Please provide as much information as you can: 

* **Suggested term label:**

endonuclease activator activity

* **Definition (free text)**

Binds to and increases the activity of an endonuclease.

* **Reference, in format PMID:33836577**

* **Parent term(s)**

GO:0008047   enzyme activator activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

should we obsolete
GO:0032075    positive regulation of nuclease activity

this is an MF in the BP, or it should be a GO-CAM
has only 29 EXP annotations

and some of those are already MF
GO:0044692    exoribonuclease activator activity

**Comment by ValWood** [comment]
actually, this should be more precise
endodeoxyribonuclease activator activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140656
+name: endodeoxyribonuclease activator activity
+namespace: Binds to and increases the activity of an endodeoxyribonuclease. {xref="PMID:33836577"}
+namespace: molecular_function
+is_a: GO:0008047 ! enzyme activator activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21574 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-10T13:31:54Z
