### ISSUE TITLE
changes to electron transport chain.

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21573]
recent changes result in

GO:0022900 | electron transport chain | IBA&nbsp;with&nbsp;S000005055&nbsp;,&nbsp;A0A1D8PQP7&nbsp;,&nbsp;PTN000451724

for oca8

https://www.pombase.org/gene/SPCC16A11.10c

this isn't correct, but the parentage (one of the slim terms) is
generation of precursor metabolites and energy 

could this parent be added instead to the descendants which are part of the mitochondrial respiratory chain?

**Comment by pgaudet** [comment]
You mean you want 'generation of precursor metabolites and energy' ? This is already in the generic subset. Close ?

**Comment by ValWood** [comment]
OK closing. I was mistaken.
