### ISSUE TITLE
NTR: purine deoxyribonucleotide salvage

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#21582]
Please provide as much information as you can: 

* **Suggested term label:**
purine deoxyribonucleotide salvage

* **Definition (free text)**
Any process which produces a purine deoxyribonucleotide from derivatives of it, without de novo synthesis.

* **Reference, in format PMID:#######**
PMID:6605343

* **Parent term(s)**
cellular metabolic compound salvage (GO:0043094) AND has_primary_output SOME purine 2’-deoxyribonucleotide (CHEBI:26390)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* @hdrabkin see @deustp01 and my notes for more detail

**Comment by pgaudet** [comment]
Can we include the specific reactions in this pathway as 'has part'? It seems you guys have done all the work to allow to do that (this also applies to related tickets). 

Thanks, Pascale

**Comment by ukemi** [comment]
We could, but this should be a separate ticket since it is much more work. We would have to expand the 'view' that we are currently taking to make sure that these activities are part of every flavor of the processes.

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106381
+name: purine deoxyribonucleotide salvage
