### ISSUE TITLE
NTR: dIMP salvage

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#21585]
Please provide as much information as you can: 

* **Suggested term label:**
dIMP salvage

* **Definition (free text)**
Any process which produces a dIMP from derivatives of it, without de novo synthesis. 

* **Reference, in format PMID:#######**
PMID:8692979

* **Parent term(s)**
cellular metabolic compound salvage (GO:0043094) AND has_primary_output SOME 2'-deoxyinosine 5'-phosphate(2−) (CHEBI:61194)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
@hdrabkin see @deustp01 and my notes for more detail

**Comment by hdrabkin** [comment]
+id: GO:0106385
+name: dIMP salvage
