### ISSUE TITLE
Rhea mappings for 3 GO terms

### ISSUE THREAD

**Issue by alanbridge** [geneontology/go-ontology#21588]
Hi, 

suggested Rhea mappings for 3 existing GO terms below. 

All the best, Alan 

GO:0102336 	
3-oxo-arachidoyl-CoA synthase activity
Catalysis of the reaction: stearoyl-CoA(4-) + malonyl-CoA(5-) + H+ <=> 3-oxoicosanoyl-CoA. + carbon dioxide + coenzyme A.
maps to
RHEA:35319 H(+) + malonyl-CoA + octadecanoyl-CoA = 3-oxoeicosanoyl-CoA + CO2 + CoA

GO:0102337    3-oxo-cerotoyl-CoA synthase activity
Catalysis of the reaction: tetracosanoyl-CoA(4-) + malonyl-CoA(5-) + H+ <=> 3-oxohexacosanoyl-CoA + carbon dioxide + coenzyme A.
maps to
RHEA:36515 H(+) + malonyl-CoA + tetracosanoyl-CoA = 3-oxohexacosanoyl-CoA + CO2 + CoA

GO:0102338    3-oxo-lignoceronyl-CoA synthase activity
Catalysis of the reaction: behenoyl-CoA(4-) + malonyl-CoA(5-) + H+ <=> 3-oxotetracosanoyl-CoA. + carbon dioxide + coenzyme A.
maps to 
Rhea: 36507 docosanoyl-CoA + H(+) + malonyl-CoA = 3-oxotetracosanoyl-CoA + CO2 + CoA

**Comment by alanbridge** [comment]
Sorry I forgot to say: 

EC 2.3.1.199 should probably map only to GO:0102756: very-long-chain 3-ketoacyl-CoA synthase activity - and not to the three child terms GO:0102336 , GO:0102337 , GO:0102338 - these should be removed (see https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=2.3.1.199 - only one of the four is needed). 

That would make GO consistent with Rhea, where EC 2.3.1.199 maps only to Rhea:32727 "a very-long-chain acyl-CoA + H(+) + malonyl-CoA = a very-long-chain 3-oxoacyl-CoA + CO2 + CoA"; Rhea:32727 and GO:0102756 are equivalent.

All the best, Alan

**Comment by hdrabkin** [comment]
done; no coffee required.
