### ISSUE TITLE
NTR: divalent cation-regulated 3',5'-cyclic-GMP phosphodiesterase activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#21586]
Please provide as much information as you can: 

* **Suggested term label: divalent cation-regulated 3',5'-cyclic-GMP phosphodiesterase activity**

* **Definition: Catalysis of the reaction: guanosine 3',5'-cyclic phosphate + H2O = guanosine 5'-phosphate. The reaction is divalent cation-sensitive.**

* **Reference, in format PMID:11171061**

* **Parent term(s) GO:0047555: 3',5'-cyclic-GMP phosphodiesterase activity**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. The parental term is EC 3.1.4.35, there is no ID for divalent cation stimulated 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Since there is GO:0048101 calcium- and calmodulin-regulated 3',5'-cyclic-GMP phosphodiesterase activity, and I need to delete 'activated_by' relation, I would like to have this term for the Dicty PDE3. Regulated by Mn2+ and Mg2+ I could add these 'has_input' with the new term.

**Comment by pgaudet** [comment]
Sorry - too much parallel processing. In any case the point stands- is the ion a cofactor?

**Comment by pfey03** [comment]
They expressed the catalytic domain of PDE3 in E.coli and tested the different cations (Fig.7). 

They also say "Enzyme preparations of Dictyostelium wild- type cells, Dictyostelium cells overexpressing DdPDE3 and Dictyostelium mutant stm F showed a similar bivalent cation dependences".

And "The amino acid sequence of DdPDE3 exhibits two putative binding sites for bivalent metal ions." That's good enough for them but they don't show direct binding.

I could argue that especially MN2+, but also Mg2+ are cofactors. 

They also mention it's similarity to mammalian PDE9 and I looked at the mouse PDE9 and it binds MG and Zn (vhttps://www.uniprot.org/uniprot/O70628), so that one could probably be annotated to the same term.

**Comment by pgaudet** [comment]
So - do we agree that you can use '3',5'-cyclic-GMP phosphodiesterase activity', since Mn is a cofactor?

**Comment by pfey03** [comment]
I think we can deduce that from the binding sites and the strong activation. There was a GO call in the past that in certain cases we can annotate to certain things even if not explicitly shown (like the binding)

**Comment by pfey03** [comment]
How do I annotate cofactors Mn and Mg? Just with has_input? I don't know why calcium-calmodulin regulated is ok but divalent cation-regulated is not. If higher organism need something it goes.

**Comment by pfey03** [comment]
in P2GO I can still use activated_by, which would be cool to keep.

**Comment by pgaudet** [comment]
Hi @pfey03 
Based on https://github.com/geneontology/go-annotation/issues/2718#issuecomment-908463802
should we close this? 

Thanks, Pascale

**Comment by pfey03** [comment]
yes
