### ISSUE TITLE
NTR: dGMP salvage

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#21584]
Please provide as much information as you can: 

* **Suggested term label:**
dGMP salvage

* **Definition (free text)**
Any process which produces a dGMP from derivatives of it, without de novo synthesis.

* **Reference, in format PMID:#######**
PMID:6605343, PMID:21829339

* **Parent term(s)**
cellular metabolic compound salvage AND has_primary_output SOME 2'-deoxyguanosine 5'-monophosphate(2−) (CHEBI:57673)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
@hdrabkin see @deustp01 and my notes for more detail

**Comment by hdrabkin** [comment]
+id: GO:0106384
+name: dGMP salvage
