### ISSUE TITLE
NTR: H3-H4 dimer loading activity

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#21580]
* **Suggested term label:**  H3-H4 dimer loading activity

* **Definition (free text):** Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the loading of a histone H3-H4 dimer onto DNA.

* **Reference:** PMID:31848341, PMID:33658433

* **Parent term(s):**

  - modeled on id: GO:0003689 ! DNA clamp loader activity:
    - is_a: GO:0140097 ! catalytic activity, acting on DNA
    - relationship: has_part GO:0042393 ! histone binding
    - relationship: has_part GO:0140603 ! ATP hydrolysis activity
  - maybe also relationship: part_of GO:0006334 ! nucleosome assembly (I doubt the activity occurs in any other context in vivo; I don't know if it's specific to any of the subtypes of nucleosome assembly)

* **Children terms (if applicable)** N/A

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED):**
  - histone H3-H4 dimer loading activity EXACT
  - histone chaperone RELATED

* **Cross-references:** N/A

* **Any other information:**
This appears to be one of the functions alluded to in #21436. The papers show that *S. pombe* Abo1 loads H3-H4 dimers onto DNA, requiring ATP hydrolysis (its orthologs likely do the same). Abo1 does not load H2A-H2B dimers, nor unload H3-H4.

**Comment by pgaudet** [comment]
Looking at this with @thomaspd 
Is this some sort of protein carrier activity (GO:0140597)?

**Comment by mah11** [comment]
I'm not 100% sure, but I'm inclined to think not. I followed the clamp loader term as a precedent because Abo1 acts to load H3-H4 dimers onto DNA; these papers don't say it does anything that obviously fits the "carrying a protein between two different cellular locations" part of the carrier definition (tho to be fair, the in vitro assays they use wouldn't be able to test for that).

**Comment by pgaudet** [comment]
I just noticed that we do have some 'loading' terms, all under BP:
 
-          'cohesin loading'
o    'protein localization to chromatin'
-          'protein-DNA complex assembly'
o    MCM complex loading

Should these be MFs? 

Thanks, Pascale

**Comment by mah11** [comment]
MCM complex loading is a multi-step phenomenon that I think belongs in BP (see #16570). I don't know enough to comment on most of the other subclasses of GO:0065004.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140665
+name: H3-H4 dimer loading activity
+namespace: molecular_function
+def: "Loading of a histone H3-H4 dimer onto DNA, driven by ATP hydrolysis." [PMID:31848341, PMID:33658433]
+synonym: "histone chaperone" RELATED []
+synonym: "histone H3-H4 dimer loading activity" EXACT []
+is_a: GO:0140097 ! catalytic activity, acting on DNA
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21580 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-22T13:57:16Z

**Comment by mah11** [comment]
thanks! :)
