### ISSUE TITLE
electron donor - GO:0050051; GO:0097258; GO:0097259 

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#21596]
Dear GO curators,

Could you please correct for the electron donor and if possible map to corresponding RHEA IDs the following GO terms:

GO:0050051   leukotriene-B4 20-monooxygenase activity
EC 1.14.14.94 - Leukotriene-B4 20-monooxygenase 
RHEA:22176 leukotriene B4 + O2 + reduced [NADPH—hemoprotein reductase] = 20-hydroxy-leukotriene B4 + H+ + H2O + oxidized [NADPH—hemoprotein reductase] 

GO:0097258   20-hydroxy-leukotriene B4 omega oxidase activity
RHEA:48668   20-hydroxy-leukotriene B4 + O2 + reduced [NADPH—hemoprotein reductase] = 20-oxo-leukotriene B4 + H+ + 2 H2O + oxidized [NADPH—hemoprotein reductase] 

GO:0097259   20-aldehyde-leukotriene B4 20-monooxygenase activity
RHEA:48672   20-oxo-leukotriene B4 + O2 + reduced [NADPH—hemoprotein reductase] = 20-carboxy-leukotriene B4 + 2 H+ + H2O + oxidized [NADPH—hemoprotein reductase]

Thank you very much for your help,
Nevila Hyka-Nouspikel

**Comment by pgaudet** [comment]
Hi @nnouspikel 

Do you have a reference for these terms? 
Are they related substrates for the same enzyme? 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Hi Pascale,
Yes they are all related substrates of Q08477_CP4F3_HUMAN -  a monooxygenase that inactivates LTB4 via three successive oxidative transformations to 20-hydroxy-LTB4, then to 20-oxo-LTB4 and to 20-carboxy-LTB4.

EC 1.14.14.94 - Leukotriene-B4 20-monooxygenase 
RHEA:22176; PMID:8486631; 9675028; 11461919; 15364545
https://enzyme.expasy.org/EC/1.14.14.94
https://www.rhea-db.org/rhea/22176

RHEA:48668; PMID:9675028
https://www.rhea-db.org/rhea/48668

RHEA:48672; PMID:9675028
https://www.rhea-db.org/rhea/48672

Thank you!
Nevila
