### ISSUE TITLE
ATPase activity - modifications

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21612]
At the Feb 2021 Ontology jamboree we created 2 terms from ATPase activity, one to describe ATPases as a class of proteins, and one to describe the catalytic activity of ATPases, ie ATP hydrolysis activity, see GitHub ticket on ATPases https://github.com/geneontology/go-ontology/issues/20876
- The logical definition of an ATPase is: 'molecular_function and ('has part' some 'ATP hydrolysis activity')'
- We also made 'ATPase' (GO:0016887), which was formerly 'ATPase activity', a 'do not annotate' term, since this is a class of proteins, and not a type of activity. However, as described in the same GH ticket, there were many direct annotations, and curators don't always know where to re-house the annotations.
- At the June 14th jamboree on ATPases, we decided on the following modifications to the ontology: 
- [x] Replace the 'ATP hydrolysis activity' term (GO:0140603) created in #20876 by a new term, 'ATPase-dependent activity' GO:0140657
- [x] GO:0016887, that was formerly ATPase activity, and had been changed to ATPase, has been relabeled 'ATP hydrolysis activity', moved under the catalytic branch (is_a: GO:0017111 ! nucleoside-triphosphatase activity), and given a 'part of' some 'ATPase-dependent activity' GO:0140657 parent. ***This means that curators do not need to reannotate genes that were directly annotated to this term*** (although annotation to a more precise term is encouraged)
- [x] Added GO subsets to new ATPase-dependent activity that were on the ATPase term
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_generic
subset: goslim_yeast

**Add annotation guidance in a comment:**
- [x] 'ATP hydrolysis activity': Note that this term is meant to specifically represent the ATPase activity of proteins using ATPase as a source of energy to drive a reaction. If possible, gene products should also be annotated to a child of 'ATPase-dependent activity ; GO:0140657', to capture their overall function. 
- [x] 'ATPase-dependent activity':  Note that this term represents a grouping class that includes all proteins that use ATP hydrolysis to drive a reaction; it is not meant to capture the ATP hydrolysis reaction itself. To annotate ATP hydrolysis, please use 'ATP hydrolysis activity ; GO:0016887''.
- [x] Edited the definition of 'ATPase-dependent activity' to take @deustp01 's feedback into account (https://github.com/geneontology/go-ontology/issues/20876#issuecomment-860684715), to "A molecular function characterized by the use of ATP hydrolysis as an energy source, coupled to other steps of a reaction mechanism to make the reaction energetically favorable, for example to catalyze a reaction or drive transport against a concentration gradient." 
- [x] Move all children under 'ATPase-dependent activity' - either directly or with the 'has part' some 'ATP hydrolysis activity relation
'annealing helicase activity'
'ATP-dependent microtubule motor activity'
'ATP-dependent peptidase activity'
'ATPase, acting on DNA'
'ATPase, acting on RNA'
'ATPase-coupled intramembrane lipid transporter activity'
'ATPase-coupled transmembrane transporter activity'
'calcium-dependent ATPase activity'
'clathrin-uncoating ATPase activity'
'fatty acid ligase activity'
'helicase activity'
'microfilament motor activity'
'microtubule-severing ATPase activity'
'nucleosome-dependent ATPase activity'
'proteasome-activating activity'
'protein disaggregase activity'
'tubulin-dependent ATPase activity'
- [x] Added synonym (RELATED), ATP-dependent activity
- [x] Added 'do not annotate' to 'ATPase-dependent activity'
- [x] Add replaced_by: GO:0016887 on GO:0140603 obsolete ATP hydrolysis activity

**Comment by pgaudet** [comment]
Open questions: 
- [ ] Do we want to remove the subsets from 'ATP hydrolysis activity'? 
- [ ] Do we want to change the definitions of children of ATPase-dependent activity to emphasize the overall reaction - for example for 'GO:0004386 helicase activity', instead of ''Catalysis of the reaction: ATP + H2O = ADP + phosphate, to drive the unwinding of a DNA or RNA helix.'' -> ''An activity that drives the unwinding of a DNA or RNA helix, driven by ATP hydrolysis'' ?

**Comment by hattrill** [comment]
I think that 'ATP-dependent activity' is more in-keeping with use in the literature. ATPase-dependent makes me stop and wonder if there is another ATPase.

**Comment by hattrill** [comment]
I vote for the change to  this pattern: ''An activity that drives the unwinding of a DNA or RNA helix, driven by ATP hydrolysis''  - but that is a lot more work for you!

**Comment by hattrill** [comment]
Can I just check about the slim - above it say:
"Added GO subsets to new ATPase-dependent activity that were on the ATPase term
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_generic
subset: goslim_yeast"

does that mean that currently the subsets are on both ATP hydrolysis activity and ATPase-dependent activity?

**Comment by pgaudet** [comment]
> does that mean that currently the subsets are on both ATP hydrolysis activity and ATPase-dependent activity?

No, currently they are just on 'ATP hydrolysis activity' (GO:0016887), the term that *used* to be ATPase activity, and then ATP activity.

**Comment by sjm41** [comment]
_I vote for the change to this pattern: ''An activity that drives the unwinding of a DNA or RNA helix, driven by ATP hydrolysis'' - but that is a lot more work for you!_

I also prefer that pattern, but given that Colin was saying that sometimes it's just the binding of ATP (rather than its hydrolysis per se) that stimulates the activity, maybe this would be better:
"An ATP-dependent activity that drives the unwinding of a DNA or RNA helix."

**Comment by bmeldal** [comment]
> I also prefer that pattern, but given that Colin was saying that sometimes it's just the binding of ATP (rather than its hydrolysis per se) that stimulates the activity, maybe this would be better:
"An ATP-dependent activity that drives the unwinding of a DNA or RNA helix."

But then the definition ("A molecular function characterized by the use of ATP hydrolysis as an energy source, coupled to other steps of a reaction mechanism to make the reaction energetically favorable, for example to catalyze a reaction or drive transport against a concentration gradient.") would be incorrect anyway, right?

**Comment by bmeldal** [comment]
A few clarifications:

- All GPs currently directly annotated to "GO:0016887 ATP hydrolysis activity" [new label, was ATPase] can remain there but if one has the time (!) they should also be annotated to a more specific child of "GO:0140657 ATPase-dependent activity" [new term]?

- Should both terms have a comment to clarify best annotation practice for these 2 terms/branches?

- "GO:0016887 ATP hydrolysis activity" won't get any children as this describes the biochemical reaction common to all ATPases?

**Comment by bmeldal** [comment]
> I think that 'ATP-dependent activity' is more in-keeping with use in the literature. ATPase-dependent makes me stop and wonder if there is another ATPase.

Argh, if there are mechanisms that only require the binding of ATP but not its hydrolysis (see @sjm41 's comment above), should the label be "ATP hydrolysis-dependent activity"???

**Comment by pgaudet** [comment]
> Argh, if there are mechanisms that only require the binding of ATP but not its hydrolysis (see @sjm41 's comment above), should the label be "ATP hydrolysis-dependent activity"???

This is why I thought we wanted the label to be 'ATPase-dependent hydrolysis activity'. We still need examples where the ATP binding (and not its hydrolysis) is relevant, to decide on that one, and create a new term if appropriate

@colinlog @deustp01 @hdrabkin @ukemi maybe you know examples?

**Comment by pgaudet** [comment]
> Should both terms have a comment to clarify best annotation practice for these 2 terms/branches?

Done, see the (long) opening comment of this ticket - but here is is again: 

**Add annotation guidance in a comment:**

* 'ATP hydrolysis activity': Note that this term is meant to specifically represent the ATPase activity of proteins using ATPase as a source of energy to drive a reaction. If possible, gene products should also be annotated to a child of 'ATPase-dependent activity ; GO:0140657', to capture their overall function.

* 'ATPase-dependent activity': Note that this term represents a grouping class that includes all proteins that use ATP hydrolysis to drive a reaction; it is not meant to capture the ATP hydrolysis reaction itself. To annotate ATP hydrolysis, please use 'ATP hydrolysis activity ; GO:0016887''.

Suggestions for improvement are welcome!

**Comment by pgaudet** [comment]
> "GO:0016887 ATP hydrolysis activity" won't get any children as this describes the biochemical reaction common to all ATPases? 

That's right.

**Comment by bmeldal** [comment]
> > Should both terms have a comment to clarify best annotation practice for these 2 terms/branches?
> 
> Done, see the (long) opening comment of this ticket - but here is is again:
> 
> **Add annotation guidance in a comment:**
> 
>     * 'ATP hydrolysis activity': Note that this term is meant to specifically represent the ATPase activity of proteins using ATPase as a source of energy to drive a reaction. If possible, gene products should also be annotated to a child of 'ATPase-dependent activity ; GO:0140657', to capture their overall function.
> 
>     * 'ATPase-dependent activity': Note that this term represents a grouping class that includes all proteins that use ATP hydrolysis to drive a reaction; it is not meant to capture the ATP hydrolysis reaction itself. To annotate ATP hydrolysis, please use 'ATP hydrolysis activity ; GO:0016887''.
> 
> 
> Suggestions for improvement are welcome!

Perfect! (There is a MD glitch in your starting post making the header for these points part of the subset action point. Sorry.)

**Comment by hattrill** [comment]
wrt: 'ATPase-dependent hydrolysis activity' vs 'ATP-dependent activity' vs  'ATP hydrolysis-dependent activity' 
'ATP hydrolysis-dependent activity' would be the least confusing. 
In many cases, the whole cycle - binding, hydrolysis, release is important. I think that for our purposes, if ATP needs to be hydrolysed in the process of completing the activity/activity cycle - even ATP/ADP binding acts allosterically as inducer of a conformational switch - then we should use the 'ATP hydrolysis-dependent activity'.

**Comment by colinlog** [comment]
Like Helen on June 15, but unlike Helen on June 17 (just above) I feel that 'ATP-dependent activity' is more in keeping with the language in the literature than 'ATPase-dependent activity' or 'ATP hydrolysis-dependent activity'. Furthermore, some fields/authors will use 'ATP-driven' or 'ATP-coupled' or 'ATP-dependent'. They are all synonyms for 'ATPase activity-dependent activity'.  Altogether I would conclude that: 'ATPase' (the collection of all the ATP-dependent MFs) would be a MF synonym for ATP-dependent, ATPase-dependent and ATP hydrolysis-dependent that is most succinctly defined as 'ATP-dependent activity' as that has 3 less letters than 'ATPase..' and does not strictly restrict the MF on the hydrolysis part, even though hydrolysis is what makes it a covalent catalytic chemical function.

**Comment by hattrill** [comment]
I do actually like 'ATP-dependent activity' the most, but hydrolysis seemed to be winning! So, agree with @colinlog 👍

**Comment by bmeldal** [comment]
Does that mean, any MF that requires ATP in some way or form also requires its hydrolysis and therefore we can use "ATP-dependent activity" as the name and stick all other names into synonyms?

I'm easy, as long as the definition makes it clear it includes hydrolysis :)

**Comment by pgaudet** [comment]
- [x] fixed term label
- [x] edited def 
from 
> A molecular function characterized by the use of ATP hydrolysis as an energy source, coupled to other steps of a reaction mechanism to make the reaction energetically favorable, for example to catalyze a reaction or drive transport against a concentration gradient.
to 
> A molecular function characterized by the coupling of ATP hydrolysis to other steps of a reaction mechanism to make the reaction energetically favorable, for example to catalyze a reaction or drive transport against a concentration gradient.
- [x] added synonyms:
- ATP hydrolysis-dependent activity
- ATPase-dependent activity
