### ISSUE TITLE
Synonyms & Term labels that only differ by case should not be allowed (was: synonym scope should be the same if the strings only differ in case (e.g. rubisco vs RuBisCO) ) 

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#21610]
id: GO:0016984
name: ribulose-bisphosphate carboxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: D-ribulose 1,5-bisphosphate + CO2 + H2O = 2 3-phospho-D-glycerate." [EC:4.1.1.39]
synonym: "3-phospho-D-glycerate carboxy-lyase (dimerizing)" RELATED [EC:4.1.1.39]
synonym: "3-phospho-D-glycerate carboxy-lyase (dimerizing; D-ribulose-1,5-bisphosphate-forming)" RELATED [EC:4.1.1.39]
synonym: "carboxydismutase activity" RELATED [EC:4.1.1.39]
synonym: "D-ribulose 1,5-diphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "D-ribulose-1,5-bisphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "diphosphoribulose carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose 1,5-bisphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose 1,5-bisphosphate carboxylase/oxygenase activity" EXACT []
synonym: "ribulose 1,5-diphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose 1,5-diphosphate carboxylase/oxygenase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose bisphosphate carboxylase/oxygenase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose diphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose diphosphate carboxylase/oxygenase activity" RELATED [EC:4.1.1.39]
**synonym: "RuBisCO activity" RELATED [EC:4.1.1.39]**
**synonym: "rubisco activity" EXACT []**
synonym: "RuBP carboxylase activity" RELATED [EC:4.1.1.39]
xref: EC:4.1.1.39
xref: MetaCyc:RIBULOSE-BISPHOSPHATE-CARBOXYLASE-RXN
xref: RHEA:23124
is_a: GO:0016831 ! carboxy-lyase activity

'RuBisCO activity' should clearly be an exact synonym.

We should have a check to make sure scope is consistent

**Comment by pgaudet** [comment]
We did this automatically, that all EC synonyms are RELATED. Any suggestion to change this automatically? Should we have a scope that checks that?

**Comment by pgaudet** [comment]
Fixed synonyms mentioned above. We still need to implement a check.

**Comment by balhoff** [comment]
This was fixed by #22009.
