### ISSUE TITLE
resolve Rhea mapping for 'allene oxide synthase activity' GO:0009978 and 'hydroperoxide dehydratase activity' GO:0047987

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21621]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/0f222d90021cbb2cc4ed41462a1dfbadd8dfe8d69d269d98edffd15bcb8ac5a5.png)

- [hydroperoxide dehydratase activity](http://purl.obolibrary.org/obo/GO_0047987) EquivalentTo [(13S)-hydroperoxy-(9Z,11E,15Z)-octadecatrienoate => (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate + H2O](http://rdf.rhea-db.org/25075)	(most probable)	0.8
- [(13S)-hydroperoxy-(9Z,11E,15Z)-octadecatrienoate = (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate + H2O](http://rdf.rhea-db.org/25074) EquivalentTo [EC:4.2.1.92](http://purl.uniprot.org/enzyme/4.2.1.92)	(most probable)	0.75
- [hydroperoxide dehydratase activity](http://purl.obolibrary.org/obo/GO_0047987) EquivalentTo [EC:4.2.1.92](http://purl.uniprot.org/enzyme/4.2.1.92)	(most probable)	0.8
- [(13S)-hydroperoxy-(9Z,11E,15Z)-octadecatrienoate => (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate + H2O](http://rdf.rhea-db.org/25075) ProperSubClassOf [METACYC:RXN1F-19](http://metacyc.org/RXN1F-19)		0.1
- [allene oxide synthase activity](http://purl.obolibrary.org/obo/GO_0009978) ProperSuperClassOf [(13S)-hydroperoxy-(9Z,11E,15Z)-octadecatrienoate = (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate + H2O](http://rdf.rhea-db.org/25074)		0.15
- [hydroperoxide dehydratase activity](http://purl.obolibrary.org/obo/GO_0047987) EquivalentTo [METACYC:HYDROPEROXIDE-DEHYDRATASE-RXN](http://metacyc.org/HYDROPEROXIDE-DEHYDRATASE-RXN)	(most probable)	0.8
- [allene oxide synthase activity](http://purl.obolibrary.org/obo/GO_0009978) EquivalentTo [METACYC:RXN1F-19](http://metacyc.org/RXN1F-19)	(most probable)	0.8

**Comment by balhoff** [comment]
Discussion on #21452 suggests merging these two GO terms. I will close that ticket in favor of this one, since this one has the picture.

**Comment by pgaudet** [comment]
I would merge 'GO:0047987 hydroperoxide dehydratase activity'  into  'GO:0009978 allene oxide synthase activity'  since this seems to be the most common label (see annotation:https://www.uniprot.org/uniprot/?query=rhea:25074)
Pascale

**Comment by hdrabkin** [comment]
OK thanks; will proceed.
