### ISSUE TITLE
Issues with GO:0061532 "primary amine secretion, neurotransmission"

### ISSUE THREAD

**Issue by gouttegd** [geneontology/go-ontology#21625]
We have the following hierarchy of terms referring to the secretion of primary amines:

* `primary amine secretion` (GO:0061531)
  * `tyramine secretion` (GO:0061545)
    * `primary amine secretion, neurotransmission` (GO:0061532)
      * `tyramine secretion, neurotransmission` (GO:0061546)

Elsewhere, we have the following hierarchy for the secretion of neurotransmitters:

* `neurotransmitter secretion` (GO:0007269)
  * `dopamine secretion, neurotransmission` (GO:0061527)
  * `epinephrine secretion, neurotransmission` (GO:0061529)
  * and so on for all other neurotransmitters, *except* `tyramine secretion, neurotransmission`

There are several (related) problems here:

* first, `primary amine secretion, neurotransmission` should not be a subclass of `tyramine secretion`, as tyramine is just one primary amine among many others;
* second, `primary amine secretion, neurotransmission` should probably be under `neurotransmitter secretion`;
* last, all classes for the secretion of neurotransmitters that happen to be primary amines should be under `primary amine secretion, neurotransmission` (instead of only tyramine).

That is, I believe we should have something like the following:

* `neurotransmitter secretion`
  * `primary amine secretion, neurotransmission`
    * `tyramine secretion, neurotransmission`
    * `aspartate secretion, neurotransmission`
    * `epinephrine secretion, neurotransmission`
    * `gamma-aminobutyric acid secretion, neurotransmission`
    * `glycine secretion, neurotransmission`
    * `histamine secretion, neurotransmission`
    * `norepinephrine secretion, neurotransmission`
    * `octopamine secretion, neurotransmission`
    * `serotonin secretion, neurotransmission`
    * `dopamine secretion, neurotransmission`

**Comment by gouttegd** [comment]
@hattrill For your information. The issue above was found when reviewing FBbt terms for some neurons (particularly `aminergic neuron`, which in FBbt is defined as `capable_of primary amine secretion, neurotransmission`).

**Comment by krchristie** [comment]
@gouttegd - Thanks for pointing this out. There are definitely problems in the neurotransmission branch. It's a bit problematic to have the ChEBI role "neurotransmission" in GO since it refers to a role and is not always compatical with direct chemical classification. I really appreciate this specific information.

**Comment by pgaudet** [comment]
I propose we obsolete ' GO:0061532 primary amine secretion, neurotransmission and ' GO:0061531 primary amine secretion as unnecessary grouping terms. (no annotations, no mappings, no subsets). 

I think this will resolve the issue brought up by @gouttegd

**Comment by pgaudet** [comment]
@hattrill @gouttegd just checking that this is OK with you.

**Comment by pgaudet** [comment]
Thanks @gouttegd 

Is 'primary amine' the correct chemical classification for these types of neurons? See children in CHEBI 
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=32877

It would be interesting to have the list of neurotransmitters you are trying to group to ensure that this is the right way to classify them. 

Thanks, Pascale

**Comment by raymond91125** [comment]
I am working on adding logical definitions to X secretion, neurotransmission terms so that we can take advantage of Chebi to infer their relationships. We would not need to obsolete primary amine secretion, neurotransmission.

**Comment by raymond91125** [comment]
We have now (all IS_A relation)
"neurotransmitter secretion"
   "primary amine secretion, neurotransmission"
      "tyramine secretion, neurotransmission"

Please reopen the ticket if this is insufficient. Thanks.

**Comment by Clare72** [comment]
>It would be interesting to have the list of neurotransmitters you are trying to group to ensure that this is the right way to classify them.

unfortunately the 'aminergic neuron' term in FBbt was created some time ago, and does not have this information, only the logical definition linking to 'primary amine secretion, neurotransmission' and it is not clear whether 'primary amine' is exactly what was intended or if this was just the closest GO term at the time.

I found a nice paper with all the insect neurotransmitters classified - https://pubmed.ncbi.nlm.nih.gov/8984507/
I suspect the 'aminergic neuron' term was supposed to encompass at least the biogenic amines, but it could be up for debate whether to include amino acids, FRMF amides or anything else.

**Comment by pgaudet** [comment]
This suggests that the 'primary amine' classification is in fact NOT a good way to define the FB term, so it's not a good term either for GO, nor for FB. 

What other types of neurons are you trying to distinguish these from? Are these also defined by GO BPs? Because the only GO BP that classifies neurotransmitters by some chemical classification is "[GO:0061544 peptide secretion, neurotransmission](http://amigo.geneontology.org/amigo/term/GO:0061544#display-lineage-tab)" - which is probably not the biologically relevant axis of classification either. 

Pascale

**Comment by Clare72** [comment]
We do have a term for 'peptidergic neuron', but this uses 'peptide secretion', which encompasses cases where the peptide acts as a hormone. There is a lot of overlap between this and 'neurosecretory neuron', which uses 'hormone secretion', but I think this is what is intended.

**Comment by hattrill** [comment]
> 

(Fine with me in terms of GO)

**Comment by raymond91125** [comment]
epinephrine is considered a biogenic amine but is it a primary amine still, given two N-attached hydrogen atoms are replaced? Furthermore, given that most amino acids are also primary amines, would primary amine not be too broad a category for neurotransmitter classification?
The current GO relationships among these neurotransmitter secretion terms, based on Chebi chemical classifications, should be correct albeit not complete.

**Comment by gouttegd** [comment]
Regarding the use of GO’s _primary amine secretion_ in the definition of FBbt’s _aminergic neuron_:

My (limited) chemical understanding is that, strictly speaking, “aminergic” should refer to _any_ amine compounds.

However, in the literature, the term seems more commonly used to refer to a smaller set of neurotransmitters.

For examples, [Dismukes, 1977](https://www.nature.com/articles/269557a0) explicitly used the term to refer to “noradrenaline, dopamine, and 5-hydroxy-tryptamine”. [Fuchs et al., 2014](https://doi.org/10.1038/srep05526) seem to use it to refer to biogenic amines only. So do [Vömel and Wegener, 2008](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0001848), who also mention GABA and glutamate neurons as “**non**-aminergic”.

([Andreatta et al., 2018](https://doi.org/10.1038/s41598-018-20407-z), on the other hand, _do_ include GABA among the neurotransmitters used in “aminergic” signalling.)

I think the FBbt term “aminergic neuron” should reflect how the term is actually used, even if chemically incorrect. This means it should probably _not_ be defined relatively to GO’s _primary amine secretion_.

**Comment by raymond91125** [comment]
That makes sense.

**Comment by gouttegd** [comment]
> I think the FBbt term “aminergic neuron” should reflect how the term is actually used, even if chemically incorrect. This means it should probably not be defined relatively to GO’s primary amine secretion.

FYI, I updated FBbt’s definition of _aminergic neuron_ so that it no longer refers to the GO term.

I think the present issue can be closed – I believe everything that needed fixing in GO has been fixed.

**Comment by raymond91125** [comment]
Thanks!
