### ISSUE TITLE
EC and Rhea mapping for GO:0004492 methylmalonyl-CoA decarboxylase activity

### ISSUE THREAD

**Issue by alanbridge** [geneontology/go-ontology#21629]
Hi GO, 

slight issue with the mapping for 

GO:0004492 methylmalonyl-CoA decarboxylase activity
Def: Catalysis of the reaction: (S)-2-methyl-3-oxopropanoyl-CoA = propanoyl-CoA + CO2.

This term is currently mapped to 

EC - 7.2.4.3 
MetaCyc - METHYLMALONYL-COA-DECARBOXYLASE-RXN 
RHEA - 21396

The MetaCyc seems OK for this GO term, but the EC and Rhea look wrong though: the EC number denotes a transporter and the Rhea also indicates transport of Na+ during the reaction:

https://www.rhea-db.org/rhea/21396 - (S)-methylmalonyl-CoA + H(+)(out) + Na(+)(in) = CO2 + Na(+)(out) + propanoyl-CoA

compare that to the GO def:

(S)-2-methyl-3-oxopropanoyl-CoA = propanoyl-CoA + CO2.

The correct Rhea for this GO term looks like https://www.rhea-db.org/rhea/61340: 

(S)-methylmalonyl-CoA + H(+) = CO2 + propanoyl-CoA

that is mapped to EC 4.1.1.94.

All the best, Alan 

EC | 7.2.4.3 | &nbsp;
-- | -- | --
MetaCyc | METHYLMALONYL-COA-DECARBOXYLASE-RXN | &nbsp;
RHEA | 21396

**Comment by pgaudet** [comment]
This term is used to annotate P52045 (SCPB_ECOLI), which is mapped to RHEA:27666

Are RHEA:27666 and RHEA:61340 different ? 
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/4782928/185637960-15a18b75-2183-4f30-909f-d7a8b4a02bc7.png">

<img width="778" alt="image" src="https://user-images.githubusercontent.com/4782928/185638038-ba295d3a-1621-4f3f-b152-669ecabd7394.png">

**Comment by pgaudet** [comment]
never mind, R and S

**Comment by pgaudet** [comment]
Possibly RHEA:27666 should also be linked to EC:4.1.1.94?

**Comment by pgaudet** [comment]
After discussion with @hdrabkin 
We decided to 

- [ ] change the label to methyl/ethyl malonyl-CoA decarboxylase activity.
- [ ] change the def: Catalysis of the reaction: (S)-methylmalonyl-CoA + H+ = CO2 + propanoyl-CoA or (2S)-ethylmalonyl-CoA + H+ = butanoyl-CoA + CO2.

**Comment by pgaudet** [comment]
Removed  RHEA:21396 & EC:7.2.4.3 

Added 
+xref: RHEA:27666 {source="skos:narrowMatch"}
+xref: RHEA:32131 {source="skos:narrowMatch"}
+xref: RHEA:59540 {source="skos:narrowMatch"}
+xref: RHEA:61340 {source="skos:narrowMatch"}
+xref: EC:4.1.1.94
