### ISSUE TITLE
resolve Rhea mapping for 'galactosylceramide sulfotransferase activity' GO:0001733

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21620]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/045fd7bce298ec1d2042aa2e2587466517acc6c3fdd3ed77caec324a7ba6051b.png)

- [galactosylceramide sulfotransferase activity](http://purl.obolibrary.org/obo/GO_0001733) EquivalentTo [METACYC:GALACTOSYLCERAMIDE-SULFOTRANSFERASE-RXN](http://metacyc.org/GALACTOSYLCERAMIDE-SULFOTRANSFERASE-RXN)	(most probable)	0.8
- [galactosylceramide sulfotransferase activity](http://purl.obolibrary.org/obo/GO_0001733) EquivalentTo [EC:2.8.2.11](http://purl.uniprot.org/enzyme/2.8.2.11)	(most probable)	0.8
- [3'-phosphoadenylyl sulfate + a 1-O-alkyl-2-acyl-3-O-(beta-D-galactosyl)-sn-glycerol = a 1-O-alkyl-2-acyl-3-(beta-D-3-sulfogalactosyl)-sn-glycerol + adenosine 3',5'-bisphosphate + H(+)](http://rdf.rhea-db.org/41744) ProperSubClassOf [EC:2.8.2.11](http://purl.uniprot.org/enzyme/2.8.2.11)		0.1
- [galactosylceramide sulfotransferase activity](http://purl.obolibrary.org/obo/GO_0001733) ProperSubClassOf [3'-phosphoadenylyl sulfate + beta-D-Gal-(1<->1')-Cer = 1-(3-O-sulfo-beta-D-galactosyl)-ceramide + adenosine 3',5'-bisphosphate + H(+)](http://rdf.rhea-db.org/43304)		0.08
- [3'-phosphoadenylyl sulfate + a beta-D-galactosyl-(1<->1')-N-acylsphing-4-enine <=> adenosine 3',5'-bisphosphate + H(+) + N-acyl-1-beta-D-(3-O-sulfo)-galactosyl-sphing-4-enine](http://rdf.rhea-db.org/20616) EquivalentTo [METACYC:GALACTOSYLCERAMIDE-SULFOTRANSFERASE-RXN](http://metacyc.org/GALACTOSYLCERAMIDE-SULFOTRANSFERASE-RXN)	(most probable)	0.75
- [3'-phosphoadenylyl sulfate + a beta-D-galactosyl-(1<->1')-N-acylsphing-4-enine = adenosine 3',5'-bisphosphate + H(+) + N-acyl-1-beta-D-(3-O-sulfo)-galactosyl-sphing-4-enine](http://rdf.rhea-db.org/20613) EquivalentTo [EC:2.8.2.11](http://purl.uniprot.org/enzyme/2.8.2.11)	(most probable)	0.75

**Comment by hdrabkin** [comment]
[GO:0001733] Catalysis of the reaction: 3'-phosphoadenosine 5'-phosphosulfate + a galactosylceramide = adenosine 3',5'-bisphosphate + a galactosylceramidesulfate.
EC: 3'-phosphoadenylyl sulfate + a galactosylceramide <=> adenosine 3',5'-bisphosphate + a galactosylceramidesulfate
*phosphoadenylyl  is phosphoadenosine ...
RHEA maps to to ids
  [RHEA:20613] and 
  RHEA:41744, which is a more narrow reaction involving a more specific substrate
RHEA:41744 could be narrow match
RHEA:43304 also seems to be a narrow match 
Make RHEA:20613 exact
IGNORE metacyc use of <=> reaction RHEA 20616
