### ISSUE TITLE
resolve Rhea mapping for 'phosphatidylglycerophosphatase activity' GO:0008962

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21635]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/1183996d3afb72a9de105d5a66b219ee1c1900ecf49e4a42b76d3eeea0d3ce1e.png)

- [1,2-diacyl-sn-glycero-3-phospho-(1'-sn-glycero-3'-phosphate) + H2O => 1,2-diacyl-sn-glycero-3-phospho-(1'-sn-glycerol) + phosphate](http://rdf.rhea-db.org/33752) EquivalentTo [METACYC:PGPPHOSPHA-RXN](http://metacyc.org/PGPPHOSPHA-RXN)	(most probable)	0.75
- [phosphatidylglycerophosphatase activity](http://purl.obolibrary.org/obo/GO_0008962) EquivalentTo [EC:3.1.3.27](http://purl.uniprot.org/enzyme/3.1.3.27)	(most probable)	0.8
- [phosphatidylglycerophosphatase activity](http://purl.obolibrary.org/obo/GO_0008962) ProperSubClassOf [a phosphatidylglycerol phosphate + H2O = a phosphatidylglycerol + phosphate](http://rdf.rhea-db.org/16725)		0.08
- [phosphatidylglycerophosphatase activity](http://purl.obolibrary.org/obo/GO_0008962) EquivalentTo [METACYC:PGPPHOSPHA-RXN](http://metacyc.org/PGPPHOSPHA-RXN)	(most probable)	0.8
- [1,2-diacyl-sn-glycero-3-phospho-(1'-sn-glycero-3'-phosphate) + H2O = 1,2-diacyl-sn-glycero-3-phospho-(1'-sn-glycerol) + phosphate](http://rdf.rhea-db.org/33751) EquivalentTo [EC:3.1.3.27](http://purl.uniprot.org/enzyme/3.1.3.27)	(most probable)	0.75

**Comment by hdrabkin** [comment]
GO term text def eactly matches RHEA:16725
The EC that the GO term uses also matches GO def.
However, RHEA uses a more narrow reaction using a more specific substrate

**Comment by hdrabkin** [comment]
@amorgat , why does RHEA NOT map RHEA:16725 to EC:3.1.3.27 when both texts defs are the same, but uses a more specific substrate. 
Should there be a relationship in RHEA between RHEA:16725 and RHEA 33752?
