### ISSUE TITLE
resolve Rhea mapping for 'dodecenoyl-CoA delta-isomerase activity' GO:0004165

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21637]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/1f508b0001d12eeddf93b427a3edc8eb562ff9da68c5c892d7248a53fc61de3f.png)

- [dodecenoyl-CoA delta-isomerase activity](http://purl.obolibrary.org/obo/GO_0004165) EquivalentTo [METACYC:ENOYL-COA-DELTA-ISOM-RXN](http://metacyc.org/ENOYL-COA-DELTA-ISOM-RXN)	(most probable)	0.8
- [a (3Z)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA](http://rdf.rhea-db.org/45900) EquivalentTo [EC:5.3.3.8](http://purl.uniprot.org/enzyme/5.3.3.8)	(most probable)	0.75
- [a (3E)-enoyl-CoA <=> a 4-saturated (2E)-enoyl-CoA](http://rdf.rhea-db.org/45231) EquivalentTo [METACYC:RXN-7836](http://metacyc.org/RXN-7836)	(most probable)	0.75
- [(3Z)-dodecenoyl-CoA <=> (2E)-dodecenoyl-CoA](http://rdf.rhea-db.org/23719) EquivalentTo [METACYC:RXN-7931](http://metacyc.org/RXN-7931)	(most probable)	0.75
- [dodecenoyl-CoA delta-isomerase activity](http://purl.obolibrary.org/obo/GO_0004165) ProperSuperClassOf [(3Z)-dodecenoyl-CoA = (2E)-dodecenoyl-CoA](http://rdf.rhea-db.org/23716)		0.08
- [(3Z)-dodecenoyl-CoA = (2E)-dodecenoyl-CoA](http://rdf.rhea-db.org/23716) ProperSubClassOf [EC:5.3.3.8](http://purl.uniprot.org/enzyme/5.3.3.8)		0.1
- [a (3E)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA](http://rdf.rhea-db.org/45228) ProperSubClassOf [EC:5.3.3.8](http://purl.uniprot.org/enzyme/5.3.3.8)		0.1
- [a (3Z)-enoyl-CoA <=> a 4-saturated (2E)-enoyl-CoA](http://rdf.rhea-db.org/45903) EquivalentTo [METACYC:ENOYL-COA-DELTA-ISOM-RXN](http://metacyc.org/ENOYL-COA-DELTA-ISOM-RXN)	(most probable)	0.75
- [dodecenoyl-CoA delta-isomerase activity](http://purl.obolibrary.org/obo/GO_0004165) EquivalentTo [EC:5.3.3.8](http://purl.uniprot.org/enzyme/5.3.3.8)	(most probable)	0.8

**Comment by pgaudet** [comment]
Actually, the EC corresponds to both RHEA:45228 and RHEA:45900 (a (3Z)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA or a (3E)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA), with dodecenoyl being a specific substrate (RHEA:23716)

So, I have added 
* EC:5.3.3.8 {source="skos:exactMatch"}
* xref: RHEA:23716 {source="skos:narrowMatch"}
*xref: RHEA:45228 {source="skos:narrowMatch"}
* xref: RHEA:45900 {source="skos:narrowMatch"}
* and the 2 RHEAs in the defxref. 

Pascale

**Comment by pgaudet** [comment]
Also, fixed other children of 'intramolecular oxidoreductase activity, transposing C=C bonds'
- [ ]  removed EC and added RHEA in def xrefs
- [ ] changed def: GO:0016159
 name: muconolactone delta-isomerase activity
 namespace: molecular_function
-def: "Catalysis of the reaction: 2,5-dihydro-5-oxofuran-2-acetate = 3,4-dihydro-5-oxofuran-2-acetate." [EC:5.3.3.4]
+def: "Catalysis of the reaction: (S)-muconolactone = (4,5-dihydro-5-oxofuran-2-yl)-acetate." [RHEA:12348]
- [ ] GO:0034018 ascopyrone tautomerase activity changed subclass
 -is_a: GO:0016863 ! intramolecular oxidoreductase activity, transposing C=C bonds
+is_a: GO:0016862 ! intramolecular oxidoreductase activity, interconverting keto- and enol-groups
