### ISSUE TITLE
NTR: ecdysteroid 22-kinase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21632]
Please provide as much information as you can: 

* **Suggested term label:**
ecdysteroid 22-kinase activity

* **Definition (free text)**
Catalysis of the reaction: an ecdysteroid + phosphate => an ecdysteroid 22-phosphate + H20

* **Reference, in format PMID:#######**
PMID: 16899460

* **Parent term(s)**
id: GO:0016773
name: phosphotransferase activity, alcohol group as acceptor

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
n/a

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
EcKinase

* **Cross-references**
RHEA:63578

* **Any other information**
Note that we already have the reciprocal reaction as a GO term:
ecdysteroid-phosphate phosphatase activity (GO:0102531)
Catalysis of the reaction: H2O + an ecdysteroid 22-phosphate <=> hydrogenphosphate + an ecdysteroid. 

BUT the definition is currently bidirectional - it should be changed to be left-to-right and map to RHEA:63577.

Useful quote from PMID: 16899460:
_The kinase data base (available on the World Wide Web at crf.medic.kumamoto-u.ac.jp/CSP/Kinase.html) has shown that 157 enzymes (or enzyme families) belong to class 2.7.1, which is composed of enzymes that target a hydroxyl group that accepts phosphotransfer from ATP. In the data base Pfam (available on the World Wide Web at www.sanger.ac.uk/Software/Pfam/index.shtml), 165 kinases (or kinase families) have been deposited. However, we could not find enzymes involved in the phosphorylation of steroid hormones in these databases. Using the DNA Data Bank of Japan (DDBJ) (available on the World Wide Web at www.ddbj.nig.ac.jp/) with tBLASTn analysis, it was revealed that the amino acid sequence of EcKinase did not show over 30% identity with any other known sequences. These results suggest that EcKinase is a novel enzyme that does not belong to an already known kinase family from the viewpoint of amino acid sequence._

Figure from same paper:
![image](https://user-images.githubusercontent.com/16306861/122238091-c38bfb00-ceb7-11eb-98c9-0bc8080cb2ba.jpeg)

**Comment by sjm41** [comment]
@sarach06 @EBI-Hsinyu Once this term gets created, it should be added to http://www.ebi.ac.uk/interpro/entry/InterPro/IPR004119/

**Comment by sjm41** [comment]
@hdrabkin If you're in the mood for doing NTRs.....

**Comment by hdrabkin** [comment]
I see GO:0102531 is a metacyc mapping project request term; however, already used for annotation of silk worm EPP. 
I will add RHEA and proper reference and fix def, while I'm adding new term.

**Comment by hdrabkin** [comment]
The suggested def needs ATP (PMID confirms inclusion in enzyme assay).

**Comment by sjm41** [comment]
OK - the suggested def was just based on https://www.rhea-db.org/rhea/63578 - does ATP need adding at Rhea too?

**Comment by hdrabkin** [comment]
I don't think so because 63578 is a phosphatase; it is NOT generating ATP (the true reverse reaction of the kinase). 
I think this sentence in the paper 
'he reciprocal conversion of free ecdysteroids and ecdysteroid 22-phosphates by two enzymes, EcKinase and ecdysteroid-phosphate phosphatase, ' 
seems a little misleading.

**Comment by alanbridge** [comment]
Hi, 

wouldn't it be more like 

ecdysteroid + ATP => an ecdysteroid 22-phosphate + ADP

All the best, Alan

**Comment by hdrabkin** [comment]
Yes exactly. 
I don't know how else the phosphate would git put onto ecdysteroid without an energy source.

**Comment by alanbridge** [comment]
Ok will make a Rhea for that and pass you the ID.

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106389
+name: ecdysteroid 22-kinase activity

**Comment by alanbridge** [comment]
Hi Harold, 

I just created 

RHEA:67972 ATP + ecdysone = ADP + ecdysone 22-phosphate + H+

and asked for a curator to review this. 

All the best, Alan

**Comment by hdrabkin** [comment]
ARGH! forgot the H+; will need to tweek this as soon as my PR goes through.

**Comment by alanbridge** [comment]
seems to be the same as https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=RXN-14755 too

**Comment by hdrabkin** [comment]
added metacyc

**Comment by alanbridge** [comment]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR004119/ actually says 

"This family also includes 4-hydroxytryptamine kinase, a psilocybin biosynthesis kinase from fungi" 

and indeed the only member in Swiss-Prot is currently a protein from magic mushrooms (see https://www.uniprot.org/uniprot/?query=ipr004119&fil=reviewed%3Ayes&sort=score) that catalyzes this reaction https://www.rhea-db.org/rhea/55564 (maps to GO:0140383) involved  in the formation of psilocybin, their active ingredient. Is it safe to add that term to the InterPro entry?

**Comment by sjm41** [comment]
Hi Alan

Hmmm, I hadn't noticed that extra line in the InterPro entry before (referenced to PMID: 28763571).
The source for  IPR004119 (http://pfam.xfam.org/family/PF02958) doesn't mention it, so I guess this extra member was added directly by InterPro?
Assuming it's correct, then I agree that the new GO term here (GO:0106389, ecdysteroid 22-kinase activity) can't be added to IPR004119 - that's a "family" entry, so maybe "domain" entries need adding here that would distinguish the different branches and could have the different GO terms associated?  Not sure how that works...can @sarach06 / @EBI-Hsinyu advise please?

**Comment by dhimmel** [comment]
Looks like there is a related PR at https://github.com/geneontology/go-ontology/pull/21840 that wasn't pickup up by [GitHub's issue linking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by sarach06** [comment]
Hi,
Yes, this is correct, picked the member in InterPro, so the term can't be added to this entry. I'll have a look and see if it could be added it to a domain entry but can't assure you that.

Best regards,
Sara

**Comment by sjm41** [comment]
Hi @hdrabkin 

If you agree, can we change the parent of "ecdysteroid 22-kinase activity" to "kinase activity  (GO:0016301)"?
Not sure why I didn't ask for this in the first place...

**Comment by hdrabkin** [comment]
done

**Comment by pgaudet** [comment]
PR was not merged

**Comment by hdrabkin** [comment]
@pgaudet what part of this didn't get merged? 
is this the part
 you agree, can we change the parent of "ecdysteroid 22-kinase activity" to "kinase activity (GO:0016301)"?
Not sure why I didn't ask for this in the first place...
'cause I don't see the kinase activity as parent now to  ecdysteroid 22-kinase activity

**Comment by hdrabkin** [comment]
fixed parentage and added synonym.
