### ISSUE TITLE
Ontology intersection questions

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#21634]
A query came in on the GO Helpdesk from @stephanielipow that I thought might be best answered here:

<hr />

I work on processing GO for inclusion in the UMLS.  I am wondering if this is correct, where the “intersection” is to the same GO id (I’m not sure if that’s the right way to explain it in English)

```
<!-- http://purl.obolibrary.org/obo/GO_0099568 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0099568">
        <owl:equivalentClass>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/GO_0005737"/>
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
                        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0005737"/>
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    </owl:Restriction>
                </owl:intersection
```

```
[Term]
id: GO:0099568
name: cytoplasmic region
namespace: cellular_component
def: "Any (proper) part of the cytoplasm of a single cell of sufficient size to still be considered cytoplasm." [GOC:dos]
is_a: GO:0005737 ! cytoplasm
intersection_of: GO:0005737 ! cytoplasm
intersection_of: part_of GO:0005737 ! cytoplasm
relationship: part_of GO:0005737 ! cytoplasm
```

There seem to be 5 cases of this:

GO:0005737|GO:0099568
GO:0005829|GO:0099522
GO:0005829|GO:0099523
GO:0005829|GO:0099524
GO:0005938|GO:0099738

Can you let me know if this makes sense?  It’s not really a problem for us, but it seems to be an outlying data condition.  

<hr/>

Tagging @cmungall @balhoff .

**Comment by cmungall** [comment]
Thanks. This is indeed intentional, but it is confusing. @pgaudet can we address this in the design pattern work

**Comment by stephanielipow** [comment]
Thanks!

While it’s on my mind, can you explain to me the difference between “deprecated” and “obsolete” concepts?  Thanks.  -- steph

    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0140016">
        <obo1:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
        <obo1:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/GO_0070779"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>


    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0140276">
        <obo1:IAO_0000115>OBSOLETE. Any heterochromatin maintenance that is involved in chromatin silencing at or near a centromere.</obo1:IAO_0000115>
        <obo1:IAO_0000233 rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://github.com/geneontology/go-ontology/issues/19301</obo1:IAO_0000233>
        <oboInOwl:created_by>bf</oboInOwl:created_by>
        <oboInOwl:creation_date>2013-08-21T10:13:39Z</oboInOwl:creation_date>
        <oboInOwl:hasAlternativeId>GO:1902368</oboInOwl:hasAlternativeId>
        <oboInOwl:hasExactSynonym>heterochromatin maintenance involved in chromatin silencing at centromeric outer repeats</oboInOwl:hasExactSynonym>
        <oboInOwl:hasOBONamespace>biological_process</oboInOwl:hasOBONamespace>
        <oboInOwl:hasRelatedSynonym>heterochromatin maintenance involved in chromatin silencing at centromere outer repeat region</oboInOwl:hasRelatedSynonym>
        <oboInOwl:hasRelatedSynonym>heterochromatin maintenance involved in chromatin silencing at pericentric region</oboInOwl:hasRelatedSynonym>
        <oboInOwl:id>GO:0140276</oboInOwl:id>
        <rdfs:comment>This term was obsoleted because it represents a phenotype.</rdfs:comment>
        <rdfs:label>obsolete pericentric heterochromatin maintenance</rdfs:label>

Etc.

**Comment by balhoff** [comment]
@stephanielipow `owl:deprecated` is the OWL property we use to denote obsolete concepts. So in general it's the same thing. But I think you might be noticing the deprecated concepts that don't have a label starting with "obsolete" (and they don't have any label or definition annotations). These are typically terms that have been "merged" with another term (they should have a `IAO:0100001` annotation with another GO concept as value. In the OBO serialization these would appear as "alt_id" for the the other term.

**Comment by stephanielipow** [comment]
Thanks, yes, that answers my question.

**Comment by pgaudet** [comment]
Other terms with same pattern: 

GO:0099522 'region of cytosol' 
GO:0099738 'cell cortex region' 
GO:0099568 'cytoplasmic region' 
GO:0098590 'plasma membrane region' 

Add 'DO NOT ANNOTATE flag on these
