### ISSUE TITLE
Remove incorrect EC:2.7.1.- xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21631]
EC:2.7.1.- is the grouping class for "Phosphotransferases with an alcohol group as acceptor" (https://enzyme.expasy.org/EC/2.7.1.-) so it's correct to have it as an xref of:

id: GO:0016773
name: phosphotransferase activity, alcohol group as acceptor
def: "Catalysis of the transfer of a phosphorus-containing group from one compound (donor) to an alcohol group (acceptor)." [GOC:jl]
xref: EC:2.7.1.-

But I think it should be removed from these six GO terms:

- [x] id: GO:0008607
name: phosphorylase kinase regulator activity
def: "Modulation of the activity of the enzyme phosphorylase kinase." [EC:2.7.11.19]
xref: EC:2.7.1.-

- [x] id: GO:0016538
name: cyclin-dependent protein serine/threonine kinase regulator activity
def: "Modulates the activity of a cyclin-dependent protein serine/threonine kinase, enzymes of the protein kinase family that are regulated through association with cyclins and other proteins." [GOC:pr, GOC:rn, PMID:7877684, PMID:9442875]
xref: EC:2.7.1.-

- [x] id: GO:0019914
name: cyclin-dependent protein kinase activating kinase regulator activity
def: "Modulation of the activity of the enzyme cyclin-dependent protein kinase activating kinase." [GOC:ai]
xref: EC:2.7.1.-

- [x] id: GO:0032942
name: inositol tetrakisphosphate 2-kinase activity
def: "Catalysis of the reaction: 1D-myo-inositol tetrakisphosphate + ATP = 1D-myo-inositol pentakisphosphate (containing 2-phosphate) + ADP." [GOC:hf]
xref: EC:2.7.1.-

- [x] id: GO:0034071
name: aminoglycoside phosphotransferase activity
def: "Catalysis of the reaction: ATP + aminoglycoside = ADP + phosphoaminoglycoside." [GOC:cb, GOC:mah]
xref: EC:2.7.1.-

- [x] id: GO:0052835
name: inositol-3,4,6-trisphosphate 1-kinase activity
def: "Catalysis of the reaction: 1D-myo-inositol 3,4,6-trisphosphate + ATP = 1D-myo-inositol 1,3,4,6-tetrakisphosphate + ADP + 2 H(+)." [EC:2.7.1.134]
xref: EC:2.7.1.-

**Comment by sjm41** [comment]
Hi @pgaudet 
I just came across these incorrect EC xrefs again.  Can you remove from the 6 cases above please (especially the 3 regulator terms!)?

**Comment by pgaudet** [comment]
* GO:0008607  phosphorylase kinase regulator activity  3 EXP -> are these right ? obsolete term? 
* GO:0019914 cyclin-dependent protein kinase activating kinase regulator activity -> grouping class, add do not annotate 
* Are 'GO:0032942 inositol tetrakisphosphate 2-kinase activity' 
Catalysis of the reaction: 1D-myo-inositol tetrakisphosphate + ATP = 1D-myo-inositol pentakisphosphate (containing 2-phosphate) + ADP.
and 'GO:0035299 inositol diphosphate tetrakisphosphate kinase activity' different?  Catalysis of the reaction: ATP + inositol diphosphate tetrakisphosphate = ADP + inositol bisdiphosphate trisphosphate.
* GO:0052835 name: inositol-3,4,6-trisphosphate 1-kinase activity -> no EC, only IEAs coming from this mapping; other EC, EC:2.7.1.134, is another reaction, Inositol-tetrakisphosphate 1-kinase (GO:0047325); obsolete?

**Comment by sjm41** [comment]
Thanks for removing those EC and making the related edits @pgaudet .
I can't usefully answer your follow-on questions, but the proposed obsoletions sound sensible.

For the record, the 3 EXP to 'GO:0008607 phosphorylase kinase regulator activity' are:
UniProtKB:Q96EB1/Human ELP4 from PMID:11818576 by UniProt
UniProtKB:Q9H9T3/Human ELP3 from PMID:11818576 by UniProt
UniProtKB:Q9UGJ0/Human PRKAG2 from PMID:15877279 by BHF-UCL

Only Reactome have annotations to 'inositol diphosphate tetrakisphosphate kinase activity' (note ID in your previous post should be 'GO:0052839'), while TAIR has and IDA to 'inositol tetrakisphosphate 2-kinase activity', so maybe those groups can help clarify if they represent the same activity.

**Comment by pgaudet** [comment]
This was done - I am not sure other issues are relevant.
