### ISSUE TITLE
resolve Rhea mapping for '4-hydroxy-tetrahydrodipicolinate synthase activity' GO:0008840

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21633]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/10739f84f5c679839fcde4e0df3033eea64aa9032a3745ec1b07f95ac8e8b210.png)

- [4-hydroxy-tetrahydrodipicolinate synthase activity](http://purl.obolibrary.org/obo/GO_0008840) EquivalentTo [EC:4.3.3.7](http://purl.uniprot.org/enzyme/4.3.3.7)	(most probable)	0.8
- [4-hydroxy-tetrahydrodipicolinate synthase activity](http://purl.obolibrary.org/obo/GO_0008840) ProperSubClassOf [L-aspartate 4-semialdehyde + pyruvate = (S)-2,3-dihydrodipicolinate + H(+) + 2 H2O](http://rdf.rhea-db.org/14845)		0.08
- [L-aspartate 4-semialdehyde + pyruvate = (2S,4S)-4-hydroxy-2,3,4,5-tetrahydrodipicolinate + H(+) + H2O](http://rdf.rhea-db.org/34171) EquivalentTo [EC:4.3.3.7](http://purl.uniprot.org/enzyme/4.3.3.7)	(most probable)	0.75
- [4-hydroxy-tetrahydrodipicolinate synthase activity](http://purl.obolibrary.org/obo/GO_0008840) EquivalentTo [METACYC:DIHYDRODIPICSYN-RXN](http://metacyc.org/DIHYDRODIPICSYN-RXN)	(most probable)	0.8
- [L-aspartate 4-semialdehyde + pyruvate <=> (2S,4S)-4-hydroxy-2,3,4,5-tetrahydrodipicolinate + H(+) + H2O](http://rdf.rhea-db.org/34174) EquivalentTo [METACYC:DIHYDRODIPICSYN-RXN](http://metacyc.org/DIHYDRODIPICSYN-RXN)	(most probable)	0.75

**Comment by hdrabkin** [comment]
Analysis: the wrong RHEA was picked for the GO reaction
EC:4.3.3.7   Pyruvate + L-aspartate-4-semialdehyde <=> (4S)-4-hydroxy-2,3,4,5-tetrahydro-(2S)-dipicolinate + H(2)O
   RHEA:34171 maps to this ec
RHEA:34171 L-aspartate 4-semialdehyde + pyruvate = (2S,4S)-4-hydroxy-2,3,4,5-tetrahydrodipicolinate + H+ + H2O
PMID: 8993314
GO uses RHEA RHEA:14845  not 34171; 14845 uses (S)-2,3-dihydrodipicolinate as product CHEBI:30620.  WRONG product.

So replace RHEA:114845 with RHEA:34171
Also change  EC Alt name: DHDPS. Dihydrodipicolinate synthetase. Using EC:4.2.1.52 used for DHDPS activity and other synonyms which was transferred to EC:4.3.3.7
Also removed EC reference to some of the synonyms not mentioned in EC record but left synonyms.
