### ISSUE TITLE
resolve Rhea mapping for 'phospholactate guanylyltransferase activity' GO:0043814

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21636]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/1307fa92b26baddb37fc765c2f4076c6dacb43b16b35b983ffccf640cfafb79b.png)

- [GTP + H(+) + phosphoenolpyruvate = diphosphate + enolpyruvoyl-2-diphospho-5'-guanosine](http://rdf.rhea-db.org/30519) EquivalentTo [EC:2.7.7.105](http://purl.uniprot.org/enzyme/2.7.7.105)	(most probable)	0.75
- [GTP + H(+) + phosphoenolpyruvate => diphosphate + enolpyruvoyl-2-diphospho-5'-guanosine](http://rdf.rhea-db.org/30520) ProperSubClassOf [METACYC:RXN-8077](http://metacyc.org/RXN-8077)		0.1
- [(2S)-2-phospholactate + GTP + H(+) => (2S)-lactyl-2-diphospho-5'-guanosine + diphosphate](http://rdf.rhea-db.org/63425) EquivalentTo [METACYC:RXN-8077](http://metacyc.org/RXN-8077)	(most probable)	0.75
- [phospholactate guanylyltransferase activity](http://purl.obolibrary.org/obo/GO_0043814) EquivalentTo [METACYC:RXN-8077](http://metacyc.org/RXN-8077)	(most probable)	0.8
- [(2S)-2-phospholactate + GTP + H(+) = (2S)-lactyl-2-diphospho-5'-guanosine + diphosphate](http://rdf.rhea-db.org/63424) EquivalentTo [EC:2.7.7.68](http://purl.uniprot.org/enzyme/2.7.7.68)	(most probable)	0.75
- [phospholactate guanylyltransferase activity](http://purl.obolibrary.org/obo/GO_0043814) EquivalentTo [EC:2.7.7.68](http://purl.uniprot.org/enzyme/2.7.7.68)	(most probable)	0.8
- [phospholactate guanylyltransferase activity](http://purl.obolibrary.org/obo/GO_0043814) ProperSuperClassOf [GTP + H(+) + phosphoenolpyruvate = diphosphate + enolpyruvoyl-2-diphospho-5'-guanosine](http://rdf.rhea-db.org/30519)		0.15

**Comment by hdrabkin** [comment]
RHEA: 30519 [GTP]() + H+ + phosphoenolpyruvate = diphosphate + enolpyruvoyl-2-diphospho-5'-guanosine is a totally different reaction; remove
Replace with RHEA: 63424 (2S)-2-phospholactate + GTP + H+ = (2S)-lactyl-2-diphospho-5'-guanosine + diphosphate; this in line with [EC 2.7.7.68]()
Metacyc:RXN-8077 is an entirely different reaction belonging with 30519 (The PEP); remove
