### ISSUE TITLE
resolve Rhea mapping for 'phosphoserine phosphatase activity' GO:0004647, 'D-phosphoserine phosphatase activity' GO:0036425, 'L-phosphoserine phosphatase activity' GO:0036424

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21638]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/35520cf941b5168d7de559952ea5aa342dad36fad5b5c12f99a14b238cde81e5.png)

- [H2O + O-phospho-L-serine = L-serine + phosphate](http://rdf.rhea-db.org/21208) ProperSubClassOf [EC:3.1.3.3](http://purl.uniprot.org/enzyme/3.1.3.3)		0.1
- [H2O + O-phospho-D-serine = D-serine + phosphate](http://rdf.rhea-db.org/24873) EquivalentTo [EC:3.1.3.3](http://purl.uniprot.org/enzyme/3.1.3.3)	(most probable)	0.75
- [H2O + O-phospho-L-serine => L-serine + phosphate](http://rdf.rhea-db.org/21209) ProperSubClassOf [METACYC:PSERPHOSPHA-RXN](http://metacyc.org/PSERPHOSPHA-RXN)		0.1
- [H2O + O-phospho-L-serine => L-serine + phosphate](http://rdf.rhea-db.org/21209) ProperSuperClassOf [REACTOME:R-HSA-977324.2](http://reactome.org/R-HSA-977324.2)	(most probable)	0.7
- [D-phosphoserine phosphatase activity](http://purl.obolibrary.org/obo/GO_0036425) ProperSubClassOf [H2O + O-phospho-D-serine = D-serine + phosphate](http://rdf.rhea-db.org/24873)		0.08
- [L-phosphoserine phosphatase activity](http://purl.obolibrary.org/obo/GO_0036424) EquivalentTo [METACYC:RXN0-5114](http://metacyc.org/RXN0-5114)	(most probable)	0.8
- [H2O + O-phospho-D-serine => D-serine + phosphate](http://rdf.rhea-db.org/24874) EquivalentTo [METACYC:PSERPHOSPHA-RXN](http://metacyc.org/PSERPHOSPHA-RXN)	(most probable)	0.75
- [H2O + O-phospho-L-serine => L-serine + phosphate](http://rdf.rhea-db.org/21209) EquivalentTo [METACYC:RXN0-5114](http://metacyc.org/RXN0-5114)	(most probable)	0.75
- [phosphoserine phosphatase activity](http://purl.obolibrary.org/obo/GO_0004647) EquivalentTo [METACYC:PSERPHOSPHA-RXN](http://metacyc.org/PSERPHOSPHA-RXN)	(most probable)	0.8
- [phosphoserine phosphatase activity](http://purl.obolibrary.org/obo/GO_0004647) EquivalentTo [EC:3.1.3.3](http://purl.uniprot.org/enzyme/3.1.3.3)	(most probable)	0.8
- [L-phosphoserine phosphatase activity](http://purl.obolibrary.org/obo/GO_0036424) EquivalentTo [H2O + O-phospho-L-serine = L-serine + phosphate](http://rdf.rhea-db.org/21208)	(most probable)	0.8

**Comment by pgaudet** [comment]
Emailed RHEA to see if they can create a grouping class for the different enantiomers.

**Comment by pgaudet** [comment]
Mappings look OK, so unless RHEA creates a grouping class for both enantiomers, no action is needed.

**Comment by balhoff** [comment]
I think it would be useful to specifically add a `skos:exactMatch` annotation to the xref here. This way when I re-run, I can boost those probabilities and it should force the RHEA:24873 xref to EC:3.1.3.3 into SubClassOf.

**Comment by balhoff** [comment]
These two both exactMatch:
- GO:0004647 xref EC:3.1.3.3
- GO:0036425 xref RHEA:24873

**Comment by pgaudet** [comment]
Can add PMID:8832224 which refers to a D-phosphoserine phosphatase

**Comment by pgaudet** [comment]
Decision on the RHEA jamboree: 
We could not find any evidence for a physiological role for D-phophoserine (unlike D-serine). So,
- D-phosphoserine phosphatase will be obsoleted
- phosphoserine phosphatase will be merged into L-phosphoserine phosphatase
- EC:3.1.1.3 will be typed as BROAD


Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0036425 D-phosphoserine phosphatase activity'. The reason for obsoletion is that there is no evidence that D-phosphoserine has a physiological role (even though a phosphatase can hydolyze the phosphate group in vitro). There are no experimental annotations to this term. This term corresponds to RHEA:24873 and KEGG:R02853. These mappings will be removed from GO as they correspond to reactions outside the scope of GO. 

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/21638

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, since the physiologically relevant compound is L-phosphoserine, 'GO:0004647 phosphoserine phosphatase activity' will be merged into 'GO:0036424 L-phosphoserine phosphatase activity' 

Annotations to GO:0004647 phosphoserine phosphatase activity are here: 
https://docs.google.com/spreadsheets/d/1oJeXHW2zNatHYTKmSY7Bbqf3XDrqnJdjtwLQ8wksnWE/edit#gid=0

Thanks, Pascale
