### ISSUE TITLE
cyclic purine nucleotide metabolic process (GO:0052652) is_a purine nucleotide biosynthetic process is incorrect

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#21645]
In the ontology cyclic purine nucleotide metabolic process is a subclass of purine nucleotide biosynthetic process. This is a TPV if purine cyclic nucleotides are ever catabolized. 
def: The chemical reactions and pathways involving a cyclic nucleotide, a nucleotide in which the phosphate group is in diester linkage to two positions on the sugar residue and the base is a purine. Source: PMID:23911318
logical def: 'biosynthetic process' and ('has primary output' some 'cyclic purine nucleotide')

We should either change the name of the term and modify the def to be a biosynthesis. Or we should change the logical def to be metabolism ('metabolic process' and ('has primary input or output' some 'cyclic purine nucleotide').

Most of the experimental annotations to this term are cyclases, but there are a few outliers. Interestingly, AMPD2 is annotated from the paper that was used for the definition of the term. I would put AMPD2 in the IMP salvage pathway. 
http://noctua.geneontology.org/editor/graph/gomodel:60897d8500000494
https://reactome.org/PathwayBrowser/#/R-HSA-8956321&SEL=R-HSA-76590&PATH=R-HSA-1430728,R-HSA-15869

@deustp01

**Comment by hdrabkin** [comment]
Cyclic-AMP is broken down by  cAMP-dependent phosphodiesterase (PDE)

**Comment by deustp01** [comment]
> Cyclic-AMP is broken down

That may be more like a turnover, like the breakdown of ATP to ADP as part of some ATP-dependent process, followed by conversion of that ADP back to ATP.
Anyway, the parentage is clearly wrong sometimes, and if there are times when it's right that need distinct fine-grained annotation, they could be handled by a new specific_form_of_cyclic_nucleotide_biosynthetic_process term.

**Comment by ukemi** [comment]
That would be safe. We can discuss more at 3.

**Comment by pgaudet** [comment]
> Cyclic-AMP is broken down

At least in Dicty, it's broken down-broken down, to stop cAMP signaling.

**Comment by pgaudet** [comment]
Changed the LD to match the metabolic process pattern: 

'metabolic process'
 and ('has primary input or output' some 'cyclic purine nucleotide')
