### ISSUE TITLE
Helicases - some questions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21644]
Hello, 

I have a couple of questions about helicases: 

 - [ ] In some papers they are referred to as 'motors' - should they be given the parent -motor activity?  That would be consistent wit hthe definition of 'motor activity': 
  > Generation of force resulting in movement, for example along a microfilament or microtubule, or in torque resulting in membrane scission or rotation of a flagellum. The energy required is obtained either from the hydrolysis of a nucleoside triphosphate or by an electrochemical proton gradient (proton-motive force).

See also PMC5477542 (2017)

>  Since helicases translocate along their substrate using the energy of NTP hydrolysis, they are molecular motors: they use chemical energy to perform mechanical work.

---

 - [x] Are helicases always ATP-dependent? A 2012 paper (PMC3409536) states that this is not always the case: 
 > Traditionally, helicases are known to unwind double-stranded DNA or RNA in an ATP-dependent manner. However, increasing evidence suggests that some helicases can rewind, or anneal, complementary strands of polynucleic acids in the presence or absence of nucleoside triphosphate (Figure 1). Moreover, two so-called human helicases that were identified recently appear to only have ATP-dependent rewinding activity [11–15].

but a 2020 review omits the ATP-independent activities (PMC7140857). 

See also PMC5477542 (2017)
> Since helicases translocate along their substrate using the energy of NTP hydrolysis, they are molecular motors: they use chemical energy to perform mechanical work.

**Comment by pgaudet** [comment]
@sjm41 @ValWood @colinlog

**Comment by sjm41** [comment]
That quote from PMC3409536 is just saying that the **annealing** activities can be ATP dependent/independent, but all helicase (unwinding) activities are ATP-dependent.
The first line of its abstract also says "Helicases are enzymes that use ATP-driven motor force to unwind double-stranded DNA or RNA.", again referring to motors - so I think having the 'motor activity' parent might well be accurate.
