### ISSUE TITLE
resolve Rhea mapping for 'ferredoxin-NAD+ reductase activity' GO:0008860, 'ferredoxin-NADP+ reductase activity' GO:0004324

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21649]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/582e13f2f06cfa38889b7e8bf259cba0db2545d378bd58c6a60d548d7d612ea4.png)

- [H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/20128) ProperSubClassOf [METACYC:RXN-14040](http://metacyc.org/RXN-14040)		0.1
- [H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] = NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/20125) EquivalentTo [EC:1.18.1.2](http://purl.uniprot.org/enzyme/1.18.1.2)	(most probable)	0.75
- [ferredoxin-NAD+ reductase activity](http://purl.obolibrary.org/obo/GO_0008860) EquivalentTo [METACYC:FERREDOXIN--NAD+-REDUCTASE-RXN](http://metacyc.org/FERREDOXIN--NAD+-REDUCTASE-RXN)	(most probable)	0.8
- [ferredoxin-NAD+ reductase activity](http://purl.obolibrary.org/obo/GO_0008860) ProperSuperClassOf [H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] = NADH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/16521)		0.15
- [H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] = NADH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/16521) EquivalentTo [EC:1.18.1.7](http://purl.uniprot.org/enzyme/1.18.1.7)	(most probable)	0.75
- [ferredoxin-NADP+ reductase activity](http://purl.obolibrary.org/obo/GO_0004324) EquivalentTo [H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] = NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/20125)	(most probable)	0.6
- [H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] = NADH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/16521) ProperSubClassOf [EC:1.18.1.3](http://purl.uniprot.org/enzyme/1.18.1.3)		0.1
- [H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/16524) EquivalentTo [METACYC:RXN-14040](http://metacyc.org/RXN-14040)	(most probable)	0.75
- [H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/16524) ProperSubClassOf [METACYC:FERREDOXIN--NAD%2b-REDUCTASE-RXN](http://metacyc.org/FERREDOXIN--NAD%2b-REDUCTASE-RXN)		0.1
- [ferredoxin-NADP+ reductase activity](http://purl.obolibrary.org/obo/GO_0004324) EquivalentTo [METACYC:1.18.1.2-RXN](http://metacyc.org/1.18.1.2-RXN)	(most probable)	0.8
- [H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] = NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/20125) ProperSubClassOf [EC:1.18.1.7](http://purl.uniprot.org/enzyme/1.18.1.7)		0.1
- [H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] => NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]](http://rdf.rhea-db.org/20126) EquivalentTo [METACYC:1.18.1.2-RXN](http://metacyc.org/1.18.1.2-RXN)	(most probable)	0.75
- [ferredoxin-NADP+ reductase activity](http://purl.obolibrary.org/obo/GO_0004324) EquivalentTo [EC:1.18.1.2](http://purl.uniprot.org/enzyme/1.18.1.2)	(most probable)	0.8
- [ferredoxin-NAD+ reductase activity](http://purl.obolibrary.org/obo/GO_0008860) EquivalentTo [EC:1.18.1.3](http://purl.uniprot.org/enzyme/1.18.1.3)	(most probable)	0.8

**Comment by hdrabkin** [comment]
Suggestion 
Merge GO:0004324 (ferredoxin-NADP+ reductase activity) and GO:0008860 (ferredoxin-NAD(+)reductase activity) into GO:0008937 (ferredoxin-NAD(P) reductase activity).
All rheas to the two merged terms become narrowMatch.
EC 1.18.1.3 ferredoxin--NAD(+) reductase. H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADH + 2 oxidized [2Fe-2S]-[ferredoxin]
 EC 1.18.1.2 ferredoxin--NADP(+) reductase. H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]

The xref 
EC 1.18.1.7 ferredoxin--NAD(P)(+) reductase (naphthalene dioxygenase ferredoxin- specific).  (alternate name NADH-ferredoxin(NAP) reductase.
    H(+) + NADP(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADPH + 2 oxidized [2Fe-2S]-[ferredoxin]
    H(+) + NAD(+) + 2 reduced [2Fe-2S]-[ferredoxin] <=> NADH + 2 oxidized [2Fe-2S]-[ferredoxin]
Appears to be somewhat unrelated in that the reactions appear identical BUT enzyme part of NAP (naphthalene dioxygenase)

**Comment by pgaudet** [comment]
Discussed with @marcfeuermann 

The GO mappings are OK. RHEA mappings seem odd @amorgat @kaxelsen  do you want to look at these? 

We will make the parent GO:0008937 'do not annotate' ferredoxin-NAD(P) reductase activity
