### ISSUE TITLE
resolve Rhea mapping for 'ABC-type taurine transporter transporter activity' GO:0015411, 'taurine transmembrane transporter activity' GO:0005368

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21640]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/451186d031e1191d1a3ec456a78d7fdb050b471ede467fb7d2d588d6df897e06.png)

- [ATP + H2O + taurine(out) => ADP + H(+) + phosphate + taurine(in)](http://rdf.rhea-db.org/14614) EquivalentTo [METACYC:3.6.3.36-RXN](http://metacyc.org/3.6.3.36-RXN)	(most probable)	0.75
- [ABC-type taurine transporter transporter activity](http://purl.obolibrary.org/obo/GO_0015411) EquivalentTo [EC:7.6.2.7](http://purl.uniprot.org/enzyme/7.6.2.7)	(most probable)	0.8
- [ABC-type taurine transporter transporter activity](http://purl.obolibrary.org/obo/GO_0015411) EquivalentTo [ATP + H2O + taurine(out) => ADP + H(+) + phosphate + taurine(in)](http://rdf.rhea-db.org/14614)	(most probable)	0.8
- [ATP + H2O + taurine(out) => ADP + H(+) + phosphate + taurine(in)](http://rdf.rhea-db.org/14614) ProperSubClassOf [METACYC:ABC-64-RXN](http://metacyc.org/ABC-64-RXN)		0.1
- [ABC-type taurine transporter transporter activity](http://purl.obolibrary.org/obo/GO_0015411) EquivalentTo [METACYC:3.6.3.36-RXN](http://metacyc.org/3.6.3.36-RXN)	(most probable)	0.8
- [ATP + H2O + taurine(out) = ADP + H(+) + phosphate + taurine(in)](http://rdf.rhea-db.org/14613) EquivalentTo [EC:7.6.2.7](http://purl.uniprot.org/enzyme/7.6.2.7)	(most probable)	0.75
- [taurine transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0005368) ProperSuperClassOf [ATP + H2O + taurine(out) = ADP + H(+) + phosphate + taurine(in)](http://rdf.rhea-db.org/14613)		0.08

**Comment by pgaudet** [comment]
- [x] Changed Rhea from RHEA:14614 (directional) to RHEA:14613 (non-directional)
 - [x] Added MetaCyc:ABC-64-RXN
