### ISSUE TITLE
resolve Rhea mappings for 'methylamine dehydrogenase (amicyanin) activity' GO:0052876, 'amine dehydrogenase activity' GO:0030058

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21650]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/5889767f61e1195e742e465a40a904d9adffff80b7428f1c00435f726757a824.png)

- [methylamine dehydrogenase (amicyanin) activity](http://purl.obolibrary.org/obo/GO_0052876) EquivalentTo [EC:1.4.9.1](http://purl.uniprot.org/enzyme/1.4.9.1)	(most probable)	0.8
- [amine dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0030058) EquivalentTo [METACYC:AMINE-DEHYDROGENASE-RXN](http://metacyc.org/AMINE-DEHYDROGENASE-RXN)	(most probable)	0.8
- [H2O + methylamine + 2 oxidized [amicyanin] = formaldehyde + 2 H(+) + NH4(+) + 2 reduced [amicyanin]](http://rdf.rhea-db.org/30207) EquivalentTo [EC:1.4.9.1](http://purl.uniprot.org/enzyme/1.4.9.1)	(most probable)	0.75
- [A + an aliphatic amine + H2O = AH2 + an aldehyde + NH4(+)](http://rdf.rhea-db.org/51128) EquivalentTo [METACYC:AMINE-DEHYDROGENASE-RXN](http://metacyc.org/AMINE-DEHYDROGENASE-RXN)	(most probable)	0.75
- [H2O + methylamine + 2 oxidized [amicyanin] => formaldehyde + 2 H(+) + NH4(+) + 2 reduced [amicyanin]](http://rdf.rhea-db.org/30208) EquivalentTo [METACYC:RXN-2841](http://metacyc.org/RXN-2841)	(most probable)	0.75
- [amine dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0030058) ProperSubClassOf [EC:1.4.9.1](http://purl.uniprot.org/enzyme/1.4.9.1)		0.08
- [2 [Fe(III)cytochrome c550] + an aliphatic amine + H2O <=> 2 [Fe(II)cytochrome c550] + an aldehyde + 2 H(+) + NH4(+)](http://rdf.rhea-db.org/21919) ProperSubClassOf [METACYC:AMINE-DEHYDROGENASE-RXN](http://metacyc.org/AMINE-DEHYDROGENASE-RXN)		0.1
- [amine dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0030058) ProperSubClassOf [H2O + methylamine + 2 oxidized [amicyanin] = formaldehyde + 2 H(+) + NH4(+) + 2 reduced [amicyanin]](http://rdf.rhea-db.org/30207)		0.08

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 

Is RHEA:30207 a more specific form of RHEA:51128? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
I have made some updates to Rhea so now:
RHEA:30207 is a RHEA:51128
RHEA:21916 is a RHEA:51128
RHEA:21917 has a cross reference to MetaCyc AMINE-DEHYDROGENASE-RXN
RHEA:51128 does not have an x-ref to MetaCyc.

**Comment by pgaudet** [comment]
- [x] Removed 'MetaCyc:AMINE-DEHYDROGENASE-RXN' as a xref to GO:0030058 amine dehydrogenase activity, since this describes a different reaction (RHEA:21919), despite its name
 - [x] Added RHEA:30207 to GO:0052876  methylamine dehydrogenase (amicyanin) activity 
 - [x] Added RHEA:51128 to GO:0030058 amine dehydrogenase activity (more general activity) 
 - [x] Removed EC:1.4.9.1 from GO:0030058 amine dehydrogenase activity, as it describes a copper-dependent activity, and GO:0030058 does not.
