### ISSUE TITLE
NTR: ATP-dependent DNA damage sensor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21662]
Please provide as much information as you can: 

* **Suggested term label:**
ATP-dependent DNA damage sensor activity

* **Definition (free text)**A molecule that recognises toxic DNA structures, and initiates a signalling response, driven by ATP hydrolysis.

* **Reference, in format PMID:#######**
PMID:33302090
PMID:33510387

* **Parent term(s)**
GO:0140612 DNA damage sensor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140662
+name: ATP-dependent protein folding chaperone
+namespace: molecular_function
+def: "Binding to a protein or a protein-containing complex to assist the protein folding process, driven by ATP hydrolysis." [PMID:27365453]
+is_a: GO:0044183 ! protein folding chaperone
+relationship: has_part GO:0016887 ! ATP hydrolysis activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21660 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-19T16:28:34Z

**Comment by ValWood** [comment]
I wonder why we are calling these ATP-dependent instead of ATPase?

**Comment by pgaudet** [comment]
This is what we had decided on the ontology call - the intention was to be very clear that we were not describing ATP hydrolysis itself.

**Comment by ValWood** [comment]
Ah right. So will all these types of terms become 'ATP-dependent blah'  instead of ATPase?

**Comment by pgaudet** [comment]
I dont know - so far I left cohesin ATPase because that's what I saw in the literature. If other terms also have common ways they are referred to, we can also edit them.

**Comment by ValWood** [comment]
cohesin ATPase might need to be obsoleted/reannotated though because it seems to provide ATP for a number of reactions. 

loading, unloading, translocase  (burning loop extrusion, but possibly not in yeast)

So it's now  more of a gene product term than a function term.
The current term describes loading and unloading activities.

**Comment by sjm41** [comment]
id: GO:0140664
name: ATP-dependent DNA damage sensor activity
namespace: molecular_function
def: "A molecule that recognises toxic DNA structures, and initiates a signalling response, driven by ATP hydrolysis." [PMID:33302090, PMID:33510387]
is_a: GO:0140612 ! DNA damage sensor activity
is_a: GO:0140657 ! ATP-dependent activity


Should the "is_a: GO:0140657 ! ATP-dependent activity" be changed to the more specific parent "ATPase, acting on DNA GO:0008094"?
