### ISSUE TITLE
Add do-not-annotate to cell wall

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#21669]
Rationale:

This creates ragged annotation whereby some things are are annotated to cell wall and sometimes to more specific such as plant cell wall, e.g.

![image](https://user-images.githubusercontent.com/50745/122819435-51d4f800-d28f-11eb-84b4-027a733d98a1.png)

This in turn leads to issues with enrichment (1) [minor] testing more hypotheses than is necessary, increasing the p-value (2) confusing duplicative results as in the enrichment here:

https://github.com/geneontology/helpdesk/issues/322

Surely in all cases it should be possible to make a more specific annotation. Presumably I know if I am making a plant vs fungal cell wall

![image](https://user-images.githubusercontent.com/50745/122819351-3538c000-d28f-11eb-972c-f01f1ac033f6.png)

Note: for cases like this where the differentia is a taxon we could auto-infer deeper placement via gaferencer. But it seems simpler just to put this back on the annotation provider.

**Comment by pgaudet** [comment]
So, we'd recommend:  
bacteria: annotate to  GO:0009274 peptidoglycan-based cell wall
plants: annotate to  GO:0009505 plant-type cell wall
fungi: GO:0009277 fungal-type cell wall
archae = ???  GO:0030115 S-layer ? (see PMID:31214995)
