### ISSUE TITLE
Obsolete GO:0061775 cohesin ATPase activity? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21672]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0061775  cohesin ATPase activity 

* **Reason for deprecation**
it seems to provide ATP for a number of reactions, so it represents a gene product more than a function 

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 6, all PomBase

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
None 

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**
See #https://github.com/geneontology/go-ontology/issues/21662#issuecomment-865289789

**Comment by pgaudet** [comment]
@ValWood There are only 2 genes annotated to this term, psm1 and psm3 (pombase) - also annotated to 'topological DNA co-entrapment activity' - should I obsolete GO:0061775 cohesin ATPase activity and suggest replacement = topological DNA co-entrapment activity? 

Thanks, Pascale

**Comment by ValWood** [comment]
topological DNA co-entrapment activity
isn't the replacememnt term for the cohesin ATPase activity.

topological DNA co-entrapment activity
describes the activity of the entire ring   topologically entrapping the DNA _after_ it is loaded onto both strands of DNA. This is a special type of DNA-binding activity.

the cohesin ATPase activity was to describe the ATPase activity required for ring loading. These represent different activities of cohesin. The loading has multiple steps and requires non-cohesin proteins in addition to cohesin itself.

cohesin ATPase activity would be a synonym of both the protein DNA loading ATPase  and unloading ATPase terms.

we have
GO:0140083    protein-DNA unloading ATPase activity -> GO:0140083    ATP-dependent protein-DNA unloading  activity

but not an equivalent loading term, as far as I can see.

**Comment by pgaudet** [comment]
We do have 'DNA clamp loader activity' (described as an ATPase) - is that what you are looking for?

**Comment by ValWood** [comment]
No because cohesin isn't a clamp......

**Comment by ValWood** [comment]
protein-DNA loading ATPase activity
I was obsoleted here, but  is really required. Either as a parent of or instead of clamp loader, cphesin loader, but also the nucleosome loading ATPases, probably?
https://github.com/geneontology/go-ontology/issues/20880

**Comment by pgaudet** [comment]
This was not quite right - we'll make another ticket
