### ISSUE TITLE
Missing parent: GO:1904600   actin fusion focus assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21688]
From PMID:11950884
The relocalisation of actin can therefore be taken
as an indicator of the onset of shmooing. This assay allows the
switch between the bipolar actin localisation seen during
vegetative growth and the tight monopolar actin localisation
seen during shmooing to be monitored.

should this term GO:1904600   actin fusion focus assembly
 therefore be part of 
GO:0031382    mating projection formation?

The actin fusion focus appears to be part_of the mating projection tip
https://www.ebi.ac.uk/QuickGO/term/GO:1990819

shouldn't the reasoner suggest this relation in BP?

@cmungall

**Comment by pgaudet** [comment]
Hi @ValWood 

I am not sure how the reasoner would know that ? 

Currently GO:1904600 actin fusion focus assembly is 'part of' some 'conjugation with cellular fusion'; do you want to add GO:0031382 mating projection formation as well?

**Comment by ValWood** [comment]
Yes, please
GO:1904600 actin fusion focus assembly is part_of GO:0031382 mating projection formation.

**Comment by pgaudet** [comment]
Now I see why you expected this relation - I think it's because in the CC this exists: 

`GO:1990819 actin fusion focus  part of  GO:0043332 mating projection tip`

Is this right?

**Comment by ValWood** [comment]
Yes! I knew there was a reason, but I could not remember when I looked yesterday.

**Comment by pgaudet** [comment]
I'm not sure we want that inference - for example - chromosome organisation part of nucleus formation? some of these assertions would end up being wrong, or at least too upstream.

**Comment by ValWood** [comment]
Is that comment in the right ticket? 
 actin fusion focus assembly
 isn't related to chromosome,e organization (or it shouldn't be...)

**Comment by pgaudet** [comment]
Right it was not related, it was just an example to explain why we dont want that inference to be created automatically - ie 
a part of b 
a formation part of b formation


Sorry about the confusion...

**Comment by ValWood** [comment]
Right, yes agreed. This is a special case.
