### ISSUE TITLE
site-specific DNA replication termination at RTS1 barrier query regulation parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21695]
Parentage https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071171
site-specific DNA replication termination at RTS1 barrier

becomes annotated to 
"GO:0031494    regulation of mating type switching"
by transitivity.

I don't think this is really regulating mating type switching, but I can't immediately see where the problem is.

GO:0071171    site-specific DNA replication termination at RTS1 barrier

 is only used by PomBase (for rtf1 &2)

**Comment by ValWood** [comment]
probably the problem is that
GO:0071515    genetic imprinting at mating-type locus
should be part_of mating type switching not
'regulation of mating type switching'

**Comment by pgaudet** [comment]
Fixed as requested

**Comment by pgaudet** [comment]
'Genetic imprinting' seems strange - first, I mostly find 'genomic imprinting' in the literature. 
Second, it is defined as a regulatory process "Any process that modulates the frequency, rate or extent of the chemical reactions and pathways involving macromolecules by a mechanism that is mediated by DNA, is mitotically or meiotically heritable, or is stably self-propagated in the cytoplasm of a resting cell, and does not entail a change in DNA sequence."

I dont know how that is different from the child 'regulation of genetic imprinting', defined as "Heritable alterations in the activity of a gene that depend on whether it passed through the paternal or the maternal germline, but that are not encoded by DNA itself."  - I though this is what 'genomic imprinting' was, see https://en.wikipedia.org/wiki/Genomic_imprinting. 

Finally, the parentage is weird - I would have expected it under 'GO:0040029 regulation of gene expression, epigenetic'. 

Looks like @mah11 created at least 'genetic imprinting'; maybe @mah11 you can help clarify the definitions of these terms? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 

I made these changes, but I think our GO-CAM guidelines would state that a transcription regulation event regulates the downstream process, not that it's a part of that process. 

What do you think ?

**Comment by ValWood** [comment]
Mating type switching is 
"Mating type switching in S. cerevisiae, which is one of the best understood programmed DNA recombination events, allows haploid yeast cells of one mating type to produce haploid cells of the other type, thereby allowing sister cells to mate and become diploid"


This 'imprint' here is a strand-specific modification that marks the DNA at the mat1 locus of switchable cells (Egel and Eie 1987; Klar 1987, 1990).

So the imprint could probably be part of  regulation of gene expression (it determines which mating factors are expressed), but it is part_of mating-type switching.

Some of these papers use 'genomic imprinting' in their keywords, so these 2 terms are probably interchangeable.

**Comment by mah11** [comment]
> Looks like @mah11 created at least 'genetic imprinting'; maybe @mah11 you can help clarify the definitions of these terms?

No, I have never had specialist knowledge of imprinting, nor do I remember all the details of work I did over a decade ago. I have found the tickets for which these terms were added: #6680 and #6820. (I think the "much older item" referred to in the latter must be #1067, but at the moment GitHub is giving me an error for links to very old tickets; also see #4410 when things are working.)
