### ISSUE TITLE
Clarify  GO:0061775 cohesin ATPase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21700]
**GO:0061775 cohesin ATPase activity** 

Change label 
- GO:0061775 ATP-dependent cohesin loading activity
- SYN: cohesin ATPase activity EXACT
- SYN: cohesin loading ATPase EXACT
Def: 
Facilitating a conformational change to load a cohesin complex around sister chromatids, driven by ATP hydrolysis.

**NTR: ATP-dependent cohesin unloading activity** 
Def: Facilitating a conformational change to unload a cohesin complex from sister chromatids, driven by ATP hydrolysis.
PMID:26687354

as a child of ATP-dependent protein-DNA unloading activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140670
+name: ATP-dependent cohesin unloading activity
+namespace: molecular_function
+def: "Facilitating a conformational change to unload a cohesin complex from sister chromatids, driven by ATP hydrolysis." [PMID:26687354]
+is_a: GO:0140083 ! ATP-dependent protein-DNA unloading activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21700 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-24T13:36:05Z

**Comment by pgaudet** [comment]
@ValWood says that the unloader is not the ATPase, so I will change the term label to 'cohesin unloader activity' and remove references to ATPase activity

**Comment by ValWood** [comment]
I think ATPase is required for cohesin unloading. BUT,

Cohesin unloader is defined as 


Definition | Parents
Facilitating a conformational change to unload a cohesin complex from sister chromatids. [PMID:26687354]


In this case,  the ATPase activity is provided by the cohesin itself.  But the molecule that is described as an "unloader" (wpl1+ pds5)  isn't itself an ATPase.

I'm not sure how we should handle this scenario in annotation.

Recently we removed the process "cohesin unloading" and have only the MF for unloader (which I used to annotate Wapl and pds5, to the "unloader activity"

I guess we will hit this issue quite a lot , when an activity is ATP-dependent, but the energy is not provided by the molecule to which the "activity" is ascribed.

Maybe we need to discuss this (especially in the context of chromatin remodelling so maybe @colinlog  has suggestions).

**Comment by ValWood** [comment]
my annotation isn't very consistent either, here!

<img width="1005" alt="Screenshot 2023-05-02 at 14 31 11" src="https://user-images.githubusercontent.com/7359272/235681667-a25bf4bd-1b1e-4d96-a81d-02726119776e.png">

**Comment by ValWood** [comment]
(Whereas we have nothing annotated to "Wpl/Pds5 cohesin loading/unloading complex"!)

This term needs updating. It was added by me at a point when the complex appeared to be used for loading and unloading. I will fix this to "Wpl/Pds5 cohesin loading/unloading complex" 

It seems that we should remove ATP-dependent from "cohesin loader activity"
if the activities are only supposed to represent the intrinsic  ATP-ase activities?

**Comment by sjm41** [comment]
Sounds good to me. So the new tasks relevant to this ticket are:

- [ ] change parent of "cohesin loader activity" (GO:0061775) to "catalytic activity, acting on DNA" (GO:0140097)
- [ ] remove the two "ATP-dependent*" synonyms on  GO:0140670 cohesin unloader activity

**Comment by pgaudet** [comment]
Also remove 'cohesin ATPase' synonym from  "cohesin loader activity" (GO:0061775).
