### ISSUE TITLE
obsoletion GO:0010796   regulation of multivesicular body size (or merge)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21719]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0010796   regulation of multivesicular body size
and children 
* **Reason for deprecation**

The genes annotated to this term (3, 1 SGD, 2 human), seem to be regulating the MVB pathway rather than the  size of the MVB, which is just a consequence of the pathway operating?

**Comment by ValWood** [comment]
@pgaudet  do you agree?

**Comment by ValWood** [comment]
ignore, it seems you already did

**Comment by pgaudet** [comment]
I think we can go ahead with the obsoletion of 

- GO:0010796 regulation of multivesicular body size
- GO:0010797 regulation of multivesicular body size involved in endosome transport
- GO:0010798 regulation of multivesicular body size involved in ubiquitin-dependent protein catabolism
I removed the 2 UniProt annotations, they were redundant with other annotations. 

@srengel Can you please look at the annotation of RSP5 SGD:S000000927 to GO:0010796 regulation of multivesicular body size? 

Thanks, Pascale

**Comment by srengel** [comment]
Hi @pgaudet i have removed the annotation of RSP5 SGD:S000000927 to GO:0010796 regulation of multivesicular body size just now in Noctua.
