### ISSUE TITLE
endocytosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21717]
The endoyctosis of  cell surface membrane proteins in fission yeast is simultaneously 

1. receptor-mediated endocytosis
2. ubiquitin-dependent endocytosis
3. clathrin-dependent endocytosis

so we have endocytosis annotated in orthogonal ways depending  which aspect the authors looked at. There are different types of endocytosis, but aren't these 3  describing parts of the same pathway (MF in BP?)

https://en.wikipedia.org/wiki/Endocytosis
Endocytosis pathways can be subdivided into four categories: namely, receptor-mediated endocytosis (also known as clathrin-mediated endocytosis), caveolae, pinocytosis, and phagocytosis.[3]

**Comment by raymond91125** [comment]
There are clathrin-independent EGFR-mediated endocytosis. PMID: 22357968
![image](https://user-images.githubusercontent.com/619520/132924260-a8a176df-4cea-471b-961c-902bd0bcb05b.png)

**Comment by raymond91125** [comment]
There may be clathrin-mediated, receptor endocytosis that is ubiquitin-independent
PMID:28011638 "Thus, our data also suggest that a ubiquitin-independent mGluR-mediated AMPAR endocytic pathway probably exists."
PMID: 30364226 The Regulation of AMPA Receptor Endocytosis by Dynamic Protein-Protein Interactions

**Comment by raymond91125** [comment]
Wikipedia is kinda wrong.

**Comment by raymond91125** [comment]
@ValWood Do you think we may not want to merge these terms given that there are exceptions? Each of these has many steps (MFs) and some are shared.

**Comment by ValWood** [comment]
Hi @raymond91125 ,

I agree - the current structure is largely OK.

These are the types:
<img width="766" alt="endocytosis" src="https://user-images.githubusercontent.com/7359272/133380661-14898509-da85-4a0c-8032-a5bc688ab6a2.png">

clathrin- dependent is the only type under receptor-mediated.  I'm not sure if this is correct because non-clathrin-mediated (caveolin-mediated endocytosis, seems that it can/is also receptor- dependent.   
Maybe the receptor-dependent term is not required, because it is describing a single step.

Also ubiquitin-mediated  is describing a single step (something which may, or may not be. rquired to happen to the endocytosed substrate). This also seems not to be required in. the BP ontology as if we had this correctly for each 'type', there would be a combinatorial explosion.

Ubiquitin-dependent has only 29 EXP annotation.
1 PomBase 
20 SGD (for 6 gene products)
1 zfin
1 FlyBase
2 Uniprot

which is a red flag that it is used inconsistently (and if curators use this term,  it is likely they did  not also use the correct term to describe the specific endocytic pathway)

@pgaudet  do you agree?

(this is a common problem, where curators  pick out a specific (often common)  MF step in a pathway and make a term 'x-dependent blah')

**Comment by ValWood** [comment]
<img width="791" alt="Screenshot 2021-09-15 at 07 35 12" src="https://user-images.githubusercontent.com/7359272/133382744-f1a19f50-add6-445c-9e32-7e3fbaf26a79.png">

**Comment by ValWood** [comment]
I just checked, all of the PomBase and SGD annotations are to arrestins.

Arrestins are
https://en.wikipedia.org/wiki/Arrestin
This is the part describing the arrestin link to endocytosis:

Mechanism
Arrestins block GPCR coupling to G proteins in two ways. First, arrestin binding to the cytoplasmic face of the receptor occludes the binding site for heterotrimeric G-protein, preventing its activation (desensitization).[13] Second, arrestin links the receptor to elements of the internalization machinery, clathrin and clathrin adaptor AP2, which promotes receptor internalization via coated pits and subsequent transport to internal compartments, called endosomes. Subsequently, the receptor could be either directed to degradation compartments (lysosomes) or recycled back to the plasma membrane where it can again signal. The strength of arrestin-receptor interaction plays a role in this choice: tighter complexes tend to increase the probability of receptor degradation (Class B), whereas more transient complexes favor recycling (Class A), although this “rule” is far from absolute.[2] More recently direct interactions between Gi/o family G proteins and Arrestin were discovered downstream of multiple receptors, regardless of canonical G protein coupling.[14] These recent findings introduce a GPCR signaling mechanism distinct from canonical G protein activation and β-arrestin desensitization in which GPCRs cause the formation of Gαi:β-arrestin signaling complexes.

I think this confirms that  this is just a single-step and should be merged or obsoleted merge. is probably OK here?

**Comment by ValWood** [comment]
i.e arrestins are just endocytic adaptors.

**Comment by pgaudet** [comment]
Hi @ValWood 

It seems to me like 'ubiquitin-dependent endocytosis' is a real process, but it should also be is_a to plasma membrane protein catabolic process 

see a more recent review, PMID:24384571

What do you think?

**Comment by ValWood** [comment]
I don't think it's a separate process, it's just a step in any of the other types isn't it? (presumably when the proteins are targeted to the vacuole/lysosome). For example in yeast the clathrin-dependent endocytosis is  ubiquitin-dependent ( at least sometimes).
Ubiquitination is just a modification of the cargo (see figure 3 in PMID:24384571 where the model is expanded to show the clathrin part).

I wouldn't include a parent to "plasma membrane catabolic process" (we don't have such a term)

**Comment by ValWood** [comment]
I see, you are trying to distinguish between the internalization of PM proteins for degradation (which yeast does), as opposed to internalization for recycling (synapsis etc), which yeast doesn't do. At least I am not aware of it.

However, we then have orthogonal ways of describing the same pathways for yeast (ubiquitin-mediated, and clathrin-mediated) . It would be neat if all ubiquitin-mediated was 'clathrin dependent'.  One would expect that recycling did not involve tagging with ubiquitin, but who knows...

This recent review  of clathrin-mediated endocytosis
https://pubmed.ncbi.nlm.nih.gov/29410531/
shows that the ubiquitin dependency of the substrate isn't a prerequisite (the cargos can be ubiquitinated or not), but presumably the destination of a vesicle is the same?

Anyway I'm not so bothered about this ticket. I thought it was a quick fix, but it isn't super important in the grand scheme of things . I have resolved  the inconsistencies internally at PomBase by making all annotations to clathrin-mediated and blocking ubiquitin-mediated which can be captured with MF terms.

I agree that this isn't connected in any way to "catabolism", but  happens anyway by connecting the specific functions involved in ubiquitin tagging and recognition to  catabolism?

This seems like more of a project than a quick fix and is probably not high priority right now.

**Comment by raymond91125** [comment]
@ValWood should we close this? Thanks.

**Comment by ValWood** [comment]
OK, closing!
v
