### ISSUE TITLE
Term merge: GO:0000125 PCAF complex into GO:0000124 SAGA complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#21726]
**Term to be merged: Provide GO ID and term label**

GO:0000125 PCAF complex

**Which term do you propose this term merge into? Provide GO ID and term label**

GO:0000124 SAGA complex

**Reason for merge**

PCAF is a subcomplex of SAGA. Classic SAGA has GCN5/KAT2A as HAT subunit but according to recent reviews (e.g. PMID:32616828, 33004486, 34112237) also exists with PCAF/KAT2B as HAT subunit. Only reliable PCAF paper I could find is PMID:10373431 in which they targeted known SAGA-type subunits after a PCAF (?) pulldown (Fig 2) but it doesn't identify the full complex. Recent reviews don't even mention it as separate complex any more.

**Any other information**

Checked with @colinlog and he concurs (I think!)

Related to https://github.com/geneontology/go-ontology/issues/21335

Also need to update Definition of SAGA complex. Still to be done.

**Comment by bmeldal** [comment]
Add: Old term name and synonyms should be come [NARROW]

**Comment by raymond91125** [comment]
There was a database_cross_reference GOC:rl associated with a PCAF synonym. I think it was a typo because I never dealt with this term. That is removed.
