### ISSUE TITLE
Update defs for GO:0070461 SAGA-type complex and GO:0000124 SAGA complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#21728]
References:
PMID:33864814 (yeast)
PMID:32616828, 33004486, 34112237 (human)

GO:0070461 SAGA-type complex

[old def] A histone acetyltransferase complex that acetylates nucleosomal H3 and H2B and is required for the expression of a subset of Pol II-transcribed genes. The budding yeast complex includes the acetyltransferase Gcn5p, several proteins of the Spt and Ada families, and several TBP-associate proteins (TAFs); analogous complexes in other species have analogous compositions, and usually contain homologs of the yeast proteins. 

[new def] A histone acetyltransferase complex that acetylates nucleosomal histones H2B, H3 or H4 and may deubiquitinate H2A or H2B and is required for the expression of a subset of Pol II-transcribed genes. Includes the acetyltransferases GCN5/KAT2A or PCAF/KAT2B, several proteins of the ADA, SGF and SPT families, and several TBP-associate proteins (TAFs). 

*NB: Considering SAGA-type complexes are found in all organisms the def shouldn't be yeast-specific and then referring to potential homologues.*

GO:0000124 SAGA complex

[old def] A SAGA-type histone acetyltransferase complex that contains Spt8 (in budding yeast) or a homolog thereof; additional polypeptides include Spt group, consisting of Spt7, Spt3, and Spt20/Ada5, which interact with the TATA-binding protein (TBP); the Ada group, consisting of Ada1, Ada2, Ada3, Ada4/Gcn5, and Ada5/Spt20, which is functionally linked to the nucleosomal HAT activity; Tra1, an ATM/PI-3 kinase-related protein that targets DNA-bound activators for recruitment to promoters; the TBP-associated factor (TAF) proteins, consisting of Taf5, Taf6, Taf9, Taf10, and Taf12, which mediate nucleosomal HAT activity and are thought to help recruit the basal transcription machinery; the ubiquitin specifc protease Ubp-8. 

[new def] A SAGA-type histone acetyltransferase complex that acetylates nucleosomal histones H3 and/or H4 and deubiquitinates H2A and/or H2B and is required for the expression of a subset of Pol II-transcribed genes. Organized into several functional submodules: a structural core including the activator binding module and consisting of ADA1 or a homolog, members of the SPT and TAF protein families as well as promotor recruitment factor TRRAP/TRA1, a histone acetyltransferase (HAT) module consisting of GCN5/KAT2A or PCAF/KAT2B, ADA2, ADA3/NGG1, and SGF29 or homologues thereof, a histone deubiquitinase (DUB) module consisting of ATXN7/SGF73, ATXN7L3/SGF11, ENY2/SUS1 and USP22/UBP8 or homologues thereof, and in some taxa a splicing module consisting of SF3B3 and SF3B5 or homologues thereof (not in fungi). In budding yeast also contains Spt8 which distinguishes it from SAGA-like (SLIK) complex (GO:0046695).

**Comment by raymond91125** [comment]
GO:0070461 SAGA-type complex
A histone acetyltransferase complex that acetylates nucleosomal histones H2B, H3 or H4 and may deubiquitinate H2A or H2B and is required for the expression of a subset of Pol II-transcribed genes, and includes the acetyltransferases GCN5/KAT2A or PCAF/KAT2B, several proteins of the ADA, SGF and SPT families, and several TBP-associate proteins (TAFs).

**Comment by raymond91125** [comment]
GO:0000124 SAGA complex
Is there a clear differentia that makes it different from all other SAGA-type complexes?

**Comment by bmeldal** [comment]
Fixed the the original post as the MD removes the - and + from the old and new def lines and turns them into paragraphs :(

**Comment by bmeldal** [comment]
They only share the HAT module. They all have different structural core modules, SAGA also has a DUB module and in some taxa (not fungi) a splicing module.

**Comment by raymond91125** [comment]
@bmeldal 
What I'm getting at is the definitions of SAGA-type complex and SAGA complex look rather similar, for the first sentence. A definition needs to be necessary and sufficient to specify that class. If deubiquitylation (DUB function) is not a necessary function of SAGA-type complex, it should not be in the definition. In general, the word 'may' is a red flag.

"that acetylates nucleosomal histones H2B, H3 or H4 and may deubiquitinate H2A or H2B and is required for the expression of a subset of Pol II-transcribed genes."
vs. 
"that acetylates nucleosomal histones H3 and/or H4 and deubiquitinates H2A and/or H2B and is required for the expression of a subset of Pol II-transcribed genes."

Thanks for the help.

**Comment by bmeldal** [comment]
Ok can we use this for SAGA-type:

"that acetylates nucleosomal histones H2B, H3 or H4 and is required for the expression of a subset of Pol II-transcribed genes."

The def for the grouping term is always going to be a part of that of its children.
