### ISSUE TITLE
Update Def for GO:0046695 SLIK (SAGA-like) complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#21727]
Acc to PMID: 33864814 the only difference to fungal SAGA is a truncated SPT7 which leads to loss of the SPT8 binding region. Need to remove RTG2 from Def and add comment about lack of SPT8 binding region of SPT7:

[OLD] A SAGA-type histone acetyltransferase complex that contains Rtg2 and a smaller form of Spt7 than the fungal SAGA complex, and lacks Spt8. The complex is involved in the yeast retrograde response pathway, which is important for gene expression changes during mitochondrial dysfunction.

[NEW] A SAGA-type histone acetyltransferase complex that contains a smaller form of Spt7 (lacking the SPT8 binding region) than the fungal SAGA complex, and consequently lacks Spt8. The complex is involved in the yeast retrograde response pathway, which is important for gene expression changes during mitochondrial dysfunction.

**Comment by raymond91125** [comment]
@bmeldal  Is the RTG2 being part of the complex still contentious? Should we remove all or some of the existing references along with the old DEF?

PMID: 33864814 author statement: "The Rtg2 protein is not present in our purified SLIK complex. In the original publication reporting the identification of SLIK, Pray-Grant et al. (14) mentioned that Rtg2 is uniquely associated with this complex. In our hands, Rtg2 could not be identified by mass spectrometry. Our purification protocol includes ammonium sulfate precipitation as well as stringent washes of IgG-bound SAGA and SLIK; in particular 25 column volumes of buffer containing 500 mM (NH4)2SO4, resulting in highly pure SAGA and SLIK. It is possible that Rtg2 is less tightly associated than the other subunits and dissociates upon purification. Pray-Grant et al. also revealed that whole-cell extracts prepared from yeast lacking RTG2 were significantly reduced in their amount of SLIK complex (as assessed by HAT assays and western blots) while maintaining similar amounts of SAGA. Therefore, they concluded that Rtg2 was an essential component of SLIK, required for its structural integrity (14). In contrast, our SLIK complex lacking Rtg2 has seemingly unaffected architecture, HAT, DUB, and DNA-binding activities, raising questions about the role of Rtg2 in the integrity of SLIK complex."

**Comment by bmeldal** [comment]
Yes, we (Sandra and I) thought it would be reasonable to go with the reference that's 16 years younger. If new data appears, it can be updated again. 

PS: I just noticed that my - and + for the old and new defs disappeared due to the markup. Replaced with words now.

**Comment by raymond91125** [comment]
@bmeldal Thanks. I'm going to assume that we don't need a new GO term and deprecate the old one here. @pgaudet Is this OK?

**Comment by pgaudet** [comment]
> I'm going to assume that we don't need a new GO term and deprecate the old one here.

Yes that's right, the meaning of the annotations is not affected, so we keep the term.

**Comment by bmeldal** [comment]
I think we need to review the annotations to RTG2 and homologues, though.

**Comment by raymond91125** [comment]
Annotation review requested geneontology/go-annotation#3837
