### ISSUE TITLE
NTR: histone loader activity and histone unloader activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21733]
Please provide as much information as you can: 

* **Suggested term label:**

- histone loading activity 
- histone unloading activity

* **Definition (free text)**
histone loading activity = Depositing a histone or a histone complex onto DNA. 
histone unloading activity = Removing a histone or a histone complex from DNA. 

* **Reference, in format PMID:#######**
PMID:26459557

* **Parent term(s)**
GO:0140597 protein carrier activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

GO:0140665 H3-H4 dimer loading activity
 - [ ] Removed 'catalytic activity, acting on DNA', since DNA is not the substrate of a catalytic reaction
 - [ ] Added 'has part' some 'ATP hydroysis activity' 
 - [ ] Changed term label to match other loaders (including DNA clam loader), also to indicate that the H3-H4 complex is ot always a dimer (can be a tetramer) =  H3-H4 histone complex loader activity 

@mah11 Hopefully this is OK with you

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
- histone chaperone = BROAD for both terms 
- histone loading activity
- histone unloading activity

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140674
+name: histone loader activity
+namespace: molecular_function
+def: "Depositing a histone or a histone complex onto DNA." [PMID:26459557]
+synonym: "histone chaperone" BROAD []
+synonym: "histone loading activity" EXACT []
+is_a: GO:0140597 ! protein carrier activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21733 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-29T12:42:57Z
+
+[Term]
+id: GO:0140675
+name: histone unloader activity
+namespace: molecular_function
+def: "Removing a histone or a histone complex from DNA." [PMID:26459557]
+synonym: "histone chaperone" BROAD []
+synonym: "histone unloading activity" EXACT []
+is_a: GO:0140597 ! protein carrier activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21733 xsd:anyURI
+created_by: pg
+creation_date: 2021-06-29T12:43:10Z

**Comment by ValWood** [comment]
These are ATPase chromatin remodellers and should be descendants of
GO:0140658    ATP-dependent chromatin remodeler activity

**Comment by ValWood** [comment]
Also I would not call these types of chaperone "carriers"

**Comment by ValWood** [comment]
...and for consistency I would include "ATP-dependent" in the term name

**Comment by pgaudet** [comment]
Discussing with @colinlog 
- agrees to remove 'carrier' parent,  to add "ATP-dependent" in the term name, and to move under GO:0140658 ATP-dependent chromatin remodeler activity

**Comment by pgaudet** [comment]
Plus remove synonym: "histone chaperone" BROAD []

**Comment by ValWood** [comment]
Why 
Plus remove synonym: "histone chaperone" BROAD []
?

**Comment by pgaudet** [comment]
@colinlog 

> Why remove synonym: "histone chaperone" BROAD []

**Comment by pgaudet** [comment]
@colinlog @hattrill @ValWood 

- [ ] Merged these terms into histone chaperone.
- [ ] Fix definition of histone chaperone to "Binding to and carrying a histone or a histone complex to unload or deposit it as a nucleosome. The histone can be newly synthesized or result from nucleosome disassembly either spontaneous, or by a histone chaperone."

**Comment by pgaudet** [comment]
Add new histone chaperone terms: 
+[Term]
+id: GO:0000510
+name: H3-H4 histone complex chaperone activity
+namespace: molecular_function
+def: "A histone chaperone that carries a H3-H4 histone complex." [PMID:28053344]
+synonym: "histone carrier activity" EXACT []
+is_a: GO:0140713 ! histone chaperone activity
+relationship: has_part GO:0042393 ! histone binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22126 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-10T15:22:31Z
+
+[Term]
+id: GO:0000511
+name: H2A-H2B histone complex chaperone activity
+namespace: molecular_function
+def: "A histone chaperone that carries a H2A-H2B histone complex." [PMID:28053344]
+synonym: "histone carrier activity" EXACT []
+is_a: GO:0140713 ! histone chaperone activity
+relationship: has_part GO:0042393 ! histone binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22126 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-10T15:22:31Z
