### ISSUE TITLE
NTR: chromatin maintenance during transcription elongation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21730]
Please provide as much information as you can: 

* **Suggested term label:**
chromatin maintenance during transcription elongation

* **Definition (free text)**
The maintenance of chromatin structure following passage of RNA polymerase II during transcription elongation, that prevents trans-histone exchange in transcribed regions.

* **Reference, in format PMID:#######**
PMID:22922743

* **Parent term(s)**
GO:0070827 ! chromatin maintenance

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
- euchromatin maintenance during transcription elongation EXACT []
- maintenance of transcriptionally active chromatin during transcription elongation EXACT []

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
I think we already have a term that was supposed to represent this:

GO:0048096    chromatin-mediated maintenance of transcription

**Comment by mah11** [comment]
That one's worded the other way round (iow, what's being retained? sounds like it's chromatin structure in the new term, but the transcriptional state in GO:0048096). The text defs also suggest that the terms apply on different timescales - GO:0048096 refers to "maintained over many cell divisions" and "heritable", whereas the new term doesn't.

**Comment by ValWood** [comment]
GO:0048096 refers to "maintained over many cell divisions" 

Can you even maintain transcription over many cell divisions?

**Comment by mah11** [comment]
I don't know if it's meant to imply that transcription is literally ongoing over successive generations. The comment does scream "multicellular organisms", though (not just metazoa; homeotic genes are all over plants too).

**Comment by ValWood** [comment]
There are also SGD annotation.
  | ELF1 | Transcription elongation factor with a conserved zinc finger domain

which is likely a better fit for the new term.

**Comment by ValWood** [comment]
from https://github.com/geneontology/go-annotation/issues/3834

..I would not read this term and think it was the correct term for the current annotations to histone exchange?

chromatin maintenance during transcriptional elongation
The maintenance of chromatin structure following passage of RNA polymerase II during transcription elongation, that prevents trans-histone exchange in transcribed regions.

The definition says it prevents trans-histone exchange so is it defined by what it isn't doing rather than what it is doing? Should it be "the maintenance of chromatin structure by blah (whatever it is doing to histones)

**Comment by ValWood** [comment]
Could you provide a list of the complexes which should be annotated to this process?

**Comment by ValWood** [comment]
Here is an example which was annotated to histone exchange:

 Swr1 complex


Definition | Parents
-- | --
A multisubunit protein complex that is involved in chromatin remodeling. It is required for the incorporation of the histone variant H2AZ into chromatin. In S. cerevisiae, the complex contains Swr1p, a Swi2/Snf2-related ATPase, and 12 additional subunits.

But if I annotate this to
"chromatin maintenance during transcriptional elongation"
the subunits  longer annotated to chromatin remodelling, even though the complex is defined as involved in chromatin remodelling ??????

**Comment by ValWood** [comment]
similarly  Ino80 complex GO:0031011

A multisubunit protein complex that contains the Ino80p ATPase; **exhibits chromatin remodeling activity** and 3' to 5' DNA helicase activity. [PMID:19355820]

Although in GO chromatin remodeling isn't an activity and I don't think this is any longer considered to be a DNA helicase?

**Comment by ValWood** [comment]
FACT complex
An abundant nuclear complex, which was originally identified in mammalian systems as a factor required for transcription elongation on chromatin templates. The FACT complex has been shown to destablilize the interaction between the H2A/H2B dimer and the H3/H4 tetramer of the nucleosome, thus reorganizing the structure of the nucleosome. In this way, the FACT complex may play a role in DNA replication and other processes that traverse the chromatin, as well as in transcription elongation. FACT is composed of two proteins that are evolutionarily conserved in all eukaryotes and homologous to mammalian Spt16 and SSRP1. In metazoans, the SSRP1 homolog contains an HMG domain; however in fungi and protists, it does not. For example, in S. cerevisiae the Pob3 protein is homologous to SSRP1, but lacks the HMG chromatin binding domain. Instead, the yFACT complex of Spt16p and Pob3p, binds to nucleosomes where multiple copies of the HMG-domain containing protein Nhp6p have already bound, but Nhp6p does not form a stable complex with the Spt16p/Pob3p heterodimer. [PMID:12934006, PMID:12934007, PMID:16678108]

phew! that one needs an edit ;)

**Comment by pgaudet** [comment]
GO:0048096 chromatin-mediated maintenance of transcription 
means that when the chromatin remodeling allows transcription (ie opens the chromatin)

while the term we have created here, chromatin maintenance during transcription elongation, rebuilds the chromatin after passage of RNA polymerase II. 

I will add a comment to that effect.

**Comment by pgaudet** [comment]
Also need to add 'part of 'GO:0006368 transcription elongation from RNA polymerase II promoter'

**Comment by ValWood** [comment]
GO:0048096 should be a descendant of chromatin remodelling too.

**Comment by pgaudet** [comment]
is GO:0048096 'remodeling'? since it's 'maintenance', I understand this to mean to does not change the chromatin structure? 
This branch will be reorganized anyway.

**Comment by ValWood** [comment]
My expert  (Karl Ekwall) says this is still considered to be 'remodelling'.

Isn't the chromatin remodelling anything which exchanges histones? Possibly 'remodelling' refers to dynamic changes that occur during maintenance. If the "chromatin maintenance during transcription elongation" does not go under remodelling then that would mean that most of the SWI/SNF family would not be classed as remodelling. I wonder how much would be left as 'chromatin remodelling' in this case?

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Chromatin_remodeling
"Chromatin remodeling is the dynamic modification of chromatin architecture to allow access of condensed genomic DNA to the regulatory transcription machinery proteins, and thereby control gene expression."

this is what I am struggling to annotate a process to:

ATP-dependent chromatin remodeling
See also: Nucleosome § ATP-dependent nucleosome remodeling
**ATP-dependent chromatin-remodeling complexes regulate gene expression by either moving, ejecting or restructuring nucleosomes.** These protein complexes have a common ATPase domain and energy from the hydrolysis of ATP allows these remodeling complexes to reposition nucleosomes (often referred to as "nucleosome sliding") along the DNA, eject or assemble histones on/off of DNA or facilitate exchange of histone variants, and thus creating nucleosome-free regions of DNA for gene activation.[13] Also, several remodelers have DNA-translocation activity to carry out specific remodeling tasks.[14]

All ATP-dependent chromatin-remodeling complexes possess a sub unit of ATPase that belongs to the SNF2 superfamily of proteins. In association to the sub unit's identity, two main groups have been classified for these proteins. These are known as the SWI2/SNF2 group and the imitation SWI (ISWI) group. The third class of ATP-dependent complexes that has been recently described contains a Snf2-like ATPase and also demonstrates deacetylase activity.[15]

I'm not completely sure why we need to get rid of the "ATP-dependent chromatin-remodeling" ? I don't know what the replacement term is? We would like to be able to distinguish between moving, ejecting or assembling histones.
I agree that the existing terms are not great but we were able to make these distinctions. 

We really need to split (i.e provide the correct new terms)  before lumping or we lose the specificity of the existing annotations.

**Comment by ValWood** [comment]
OK got it. This is not a replacement for any existing term.

**Comment by pgaudet** [comment]
Transcription workshop - @colinlog @ValWood @RLovering 

**Changed term label**
-name: chromatin maintenance during transcription elongation
+name: co-transcriptional chromatin reassembly


**Changed def**
-def: "The maintenance of chromatin structure following passage of RNA polymerase II during transcription elongation, that prevents trans-histone exchange in transcribed regions. This process rebuilds the chromatin after passage of RNA polymerase II." [PMID:22922743]
+def: "The reestablishment of chromatin structure that was disrupted upon passage of RNA polymerase II during transcription elongation. This process prevents cryptic intragenic transcription initiation." [PMID:22922743]



**Changed subclasses**
-is_a: GO:0070827 ! chromatin maintenance
-intersection_of: GO:0043954 ! cellular component maintenance
-intersection_of: part_of GO:0006368 ! transcription elongation from RNA polymerase II promoter
**+is_a: GO:0031497 ! chromatin assembly**
**+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: part_of GO:0006366 ! transcription by RNA polymerase II**
