### ISSUE TITLE
Changing ontology structure of GO:0110070 "cellularization cleavage furrow" ?

### ISSUE THREAD

**Issue by Kawatebi** [geneontology/go-ontology#21737]
I have a Drosophila protein which localizes to the "cleavage furrow" or "furrow canal" during cellularization (PubMed=33835025). 

I can use the term GO:0110070 "cellularization cleavage furrow" but my colleague noticed that this is a child of "cleavage furrow" which is part of "cell division site" which refers to cytokinesis. We were wondering if the ontology structure of GO:0110070 may need to be changed or the "cell division site" definition needs to be updated to remove the reference to cytokinesis, because although cellularization involves mitosis it is not a type of cytokinesis because it does not involve division of the cytoplasm (https://www.ncbi.nlm.nih.gov/books/NBK26831/figure/A3393/?report=objectonly). For example, the "syncytial embryo cellularization" GO term (GO:0110069) is a child of "cell division" but not of "cytokinesis" and the "cell division" term does not refer to cytokinesis. 

We would be interested to know what you thought.

**Comment by pgaudet** [comment]
The suggestion is to move 'cellularization cleavage furrow' as a sibling of 'cleavage furrow', to remove the parentage 'part of' some 'cell division site'. 

@hattrill is this OK with you? (terms were requested here: #14543)

**Comment by pgaudet** [comment]
Likewise for 'cellularization cleavage furrow invagination front'; the 'part of' some cell division site' would get removed, according to this proposal. 

Thanks, Pascale

**Comment by hattrill** [comment]
removed or moved? Latter is fine.

**Comment by pgaudet** [comment]
> the 'part of' some cell division site' would get removed,

I meant, as a parent of 'cellularization cleavage furrow invagination front' - I think that's OK for you?

**Comment by hattrill** [comment]
@pgaudet That's good for me. Thanks
