### ISSUE TITLE
Obsoletion notice: GO:0031275 regulation of lateral pseudopodium assembly & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21738]
Following up on #21600 

Please provide as much information as you can:

* **GO term ID and Label**
GO:0031275 regulation of lateral pseudopodium assembly
GO:0031276 negative regulation of lateral pseudopodium assembly
 GO:0031277 positive regulation of lateral pseudopodium assembly 

* **Reason for deprecation**
These terms were not used consistently. Negative regulation has been replaced by GO:0120320 lateral pseudopodium retraction

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation
GO:0120320 lateral pseudopodium retraction

* **Are there annotations to this term?**
- How many EXP:
- 12 dictyBase @pfey03 
- 1 RGD  @gthayman 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No 

* **Is this term in a subset? (check the AmiGO page for that term)**
No 

* **Any other information**

**Comment by pfey03** [comment]
Thanks @pgaudet I look for GO:0120320 next week if available and check the papers.

**Comment by pfey03** [comment]
BTW, we have 14 total, 2 for 'regulation of lateral pseudopodium assembly'. Added those to my table

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0031275 regulation of lateral pseudopodium assembly and descendants
GO:0031276 negative regulation of lateral pseudopodium assembly
GO:0031277 positive regulation of lateral pseudopodium assembly

The reason for obsoletion is that only some negative regulation pathway is known, and this has been replaced by the new term, lateral pseudopodium retraction (GO:0120320); see https://github.com/geneontology/go-ontology/issues/21600. 

There are 14 dictyostelium annotations and 1 rat annotation to these terms. 

There are no mappings; these terms are not present in any subsets. You may comment on the ticket: https://github.com/geneontology/go-ontology/issues/21738

Thanks, Pascale
