### ISSUE TITLE
chromatin remodelling definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21748]
GO:0006338 chromatin remodeling
has a very broad definition:

Dynamic structural changes to eukaryotic chromatin occurring throughout the cell division cycle. These changes range from the local changes necessary for transcriptional regulation to global changes necessary for chromosome segregation. 

Is this OK?

**Comment by ValWood** [comment]
Should the definition mention organization of nucleosomes? to distinguish from more macro changes to chromatin (cohesion, condensation etc).
Does 'chromatin remodelling' really include "global changes necessary for chromosome segregation'? If so we should be specific about which ones?

@colinlog

**Comment by pgaudet** [comment]
We have decided that thus term needs to remain.

**Comment by ValWood** [comment]
I changed back to my original title which was about the definition rather than it being an MF, but this will probably come up later.

**Comment by pgaudet** [comment]
Current def: "Dynamic structural changes to eukaryotic chromatin occurring throughout the cell division cycle. These changes range from the local changes necessary for transcriptional regulation to global changes necessary for chromosome segregation."

We can discuss this tomorrow.

**Comment by pgaudet** [comment]
Proposed change in definition for chromatin remodeling 

Dynamic structural changes to ~eukaryotic~ chromatin ~occurring throughout the cell division cycle~. These changes allow DNA metabolic processes such as transcriptional regulation, DNA recombination, DNA repair, DNA replication, as well as global changes necessary for chromosome segregation.

**Comment by pgaudet** [comment]
We have not addressed @ValWood 's comment 

> Should the definition mention organization of nucleosomes? to distinguish from more macro changes to chromatin (cohesion, condensation etc).
Does 'chromatin remodelling' really include "global changes necessary for chromosome segregation'? If so we should be specific about which ones?
