### ISSUE TITLE
NTR: mycofactocin-coupled metabolic process

### ISSUE THREAD

**Issue by danielhhaft** [geneontology/go-ontology#21741]
Please provide as much information as you can: 

* **Suggested term label:**
mycofactocin-coupled metabolic process

* **Definition (free text)**
The chemical reactions and pathways performed by enzymes whose activity on physiological substrates such as alcohols or aldehydes leads to a net change in the redox state of a non-exchangeable cofactor such as NAD, after which the enzyme may return to its previous redox state by electron transfer to or from the cofactor mycofactocin.

The ability of mycofactocin to transfer electrons among different nicotinoproteins that have non-exchangeable NAD cofactors allows it to couple two otherwise separate metabolic pathways, so that oxidations performed on a key substrate in one metabolic pathway may offset reductions performed on a key substrate of the other pathway.

* **Reference, in format PMID:#######**
PMID:33014324  Structure elucidation of the redox cofactor mycofactocin reveals oligo-glycosylation by MftF.
PMID:31279528   Mycofactocin is essential for the establishment of methylotrophy in Mycobacterium smegmatis
PMID:31113891   Mycofactocin Is Associated with Ethanol Metabolism in Mycobacteria.
PMID:28120876 Mycofactocin-associated mycobacterial dehydrogenases with non-exchangeable NAD cofactors
PMID:21223593   Bioinformatic evidence for a widely distributed, ribosomally produced electron carrier precursor, its maturation proteins, and its nicotinoprotein redox partners.

* **Parent term(s)**
GO:0008152 metabolic process

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
mycofactocin-dependent metabolic process       (EXACT, but imprecise, as dependency may be determined situationally).

* **Cross-references**
HMM families TIGR03971, TIGR04504, TIGR04266, and TIGR03989 all should identify enzymes deserving this GO term.

* **Any other information**

Note: This term should not apply to any protein involved in the biosynthesis or degradation of mycofactocin (see GO:0140604). It should apply only to oxidoreductases that involve mycofactocin in electron transfer processes after the cofactor has been biosynthesized.  In some Acintobacteria, such as Mycobacterium smegmatis, the number of enzymes deserving this GO term may reach 25.

**Comment by danielhhaft** [comment]
An example of text discussing the coupling of an oxidoreductase to mycofactocin (MFT)

"...functionality of MFT was strictly required for growth of free-living mycobacteria in ethanol and other primary alcohols. Among other genes encoding predicted MFT-associated dehydrogenases, MSMEG_6242 was indispensable for M. smegmatis ethanol assimilation, suggesting that it is a candidate catalytic interactor with MFT"   (PMID:31113891)

MSMEG_6242 is equivalent to WP_003897664.1 "NDMA-dependent methanol dehydrogenase"

**Comment by pgaudet** [comment]
Hi @danielhhaft 

Is this meant to be a grouping term for all enzymes using mycofactocin as a cofactor?

**Comment by danielhhaft** [comment]
It is. But the wildcard here is that all these enzymes are fully functional in the absence of mycofactocin.  There likely will be some enzymes that have a useful physiological purpose even in the absence of mycofactocin.  A formaldehyde dismutase that can turn two molecules of formaldehyde into one of methanol (reduction) and one of formate (oxidation).  But in the presence of methanol as a carbon source, and using mycofactocin to redistribute electrons, net oxidation of methanol.

So, I figure that to meet GO standards, the term should be always true for an enzyme. Coupled to mycofactocin, since the electron exchange is always possible, is true. But to say the enzyme uses mycofactocin as a cofactor - not always true, since, as I say, in some physiological situations, it won't be needed.

**Comment by pgaudet** [comment]
> these enzymes are fully functional in the absence of mycofactocin.

Maybe the solution is to add to the appropriate Molecular Function terms a comment to the effect that under certain conditions they use mycofactocin as a cofactor? 

Unless the "specific physiological situations" can be described as a process?

**Comment by danielhhaft** [comment]
| Maybe the solution is to add to the appropriate Molecular Function terms a comment to the effect that under certain conditions they use mycofactocin as a cofactor?

I don't think that can be done.  Mycofactocin research is about 10 years old, but the proposed function as cofactor with two different redox states has had solid verification only for about a year.  The fine points of which enzymes interacting with mycofactocin do it under which conditions - that's a long way off.  But the biological process - metabolic processes such as catabolism of cholesterol and conversions involving carveol, ethanol, and almost certainly a very long list of alcohols and aldehydes - mapping out most of those probably is more than 15 years away.   I tried to compose the GO term now to name the general process that is occurring, that researchers into any species that makes mycofactocin should want to track, and that could benefit researchers by helping them link together different enzymes united by the memberships of their non-exchangeable NAD cofactors into the same redox pool, for which redox potential is redistributed by mycofactocin.    The cofactor is made.  There is always a transcription factor to turn on the biosynthesis, responding to some condition in the cell.  And genomes encoding mycofactocin biosynthesis never have just one mycofactocin-dependent enzyme.  The redox exchange, the sharing of electrons between one enzyme reducing A into B, and another oxidizing C into D, is apparently the whole game.   But if M. smegmatis has 25 for more mycofactocin-dependent enzymes, establishing links more specific than simply being part of the pool - I imagine it's very hard.   

I've been trying for a decade to figure out the right name to propose for mycofactocin-dependent  processes for GO, and finally decided that calling it "coupled" rather than "dependent" had more precision.   More solidly guaranteed to not be wrong across future years as new research gets done.  The term should be useful today and should endure as well.

Meanwhile, because Reviewed Computational Analysis (mine) and IEA assignments of mycofactocin-coupled enzymes will be so different in counts (once the term exists and can be assigned), even among genomes fairly closely related in their core proteomes and their 16S RNA,  the proposed GO term should become a useful aid to researchers.   Together with the term already existing for the mycofactocin biosynthesis.      

In theory, this GO term could end up with multiple children in the biological process ontology:
mycofactocin-coupled carveol metabolic process
mycofactocin-coupled cholesterol catabolic process
mycofactocin-coupled ethanol metabolic process
mycofactocin-coupled methanol metabolic process

Maybe those never need to be built - the parent biological process, and specific molecular functions, may combine for all the expressive power needed.  But I'm pretty convinced that it's fair, today, to describe the exchange of electrons throughout the pool of connected enzymes that can give electrons to or take electrons from mycofactocin, as a metabolic process in need of a GO term, as as a current hole in GO's descriptive power in species such as Mycobacterium tuberculosis and M. smegmatis.

**Comment by danielhhaft** [comment]
One more try here.  

An enzyme participates in a "mycofactocin-coupled metabolic process" if
* it can add electrons to or receive electrons from mycofactocin, changing the redox state of a cofactor such as NAD that is permanently bound and non-exchangeable
* that change in redox state means net oxidation or reduction of the mycofactocin cofactor pool affects the activity of the enzyme and the pathway to which it belongs.

Probably there should be a biochemical function term for "mycofactocin-binding."  I think there is still zero experimental data on binding of the cofactor to mycofactocin-coupled enzymes, but  I guess the term should be created.  "mycofactocin-coupled metabolic process" will be a bit broader because it could include the roles of other enzymes in pathways that would be disabled if mycofactocin is unavailable.

**Comment by ukemi** [comment]
Have to add my favorite. Paraphrasing Lehninger (1975), he says the non-protein components of an enzyme are cofactors. They can be metal ions or organic molecules. When they are organic molecules they are coenzymes. He uses the same distinction for holoenzymes and apoenzymes.

**Comment by hdrabkin** [comment]
Interestingly, I have 
Ables, Frey, and Jencks, 1992: no mention of "prosthetic group(s)" in the index....
Also scanning my Stryer (2004) Biochemistry, no mention of prosthetic
I can find the term use in Wiki; odd that I can't find it in recent Biochemstiry texts. 
https://en.wikipedia.org/wiki/Prosthetic_group
Also found in the good old "Oxford Dictionary of Biochemistry and Molecular Biology, 1rst ed (1977) and 2000 edition
  prosthetic group a non-protein group that is combined specifically with a protein, in stoichiometric proportion.

**Comment by hdrabkin** [comment]
On the other hand, 2014 Lehninger 
However, some proteins contain **permanently associated** chemical components in addition to amino acids; these are called conjugated proteins. **The non–amino acid part of a conjugated protein is usually called its prosthetic group**
So I was worrying that the term was out of popular usage, but I guess not.

**Comment by ValWood** [comment]
I suggest we close this, it is likely this can be covered by coupling the output of "mycofactin biosynthesis" to the 
downstream processes which use it (i.e. in GO cams). We would not for example have a grouping for "all processes coupled to iron sulfurer cluster assembly, or biotinylation any other prosthetic group.

Please reopen if I misunderstood with an action item, or an explanation.

**Comment by danielhhaft** [comment]
It doesn't sound reasonable at all to apply "mycofactocin biosynthesis" to proteins that use it rather than synthesize it. So strange that someone from GO would suggest that, given how strict GO can be about other matters.

Instead, it makes sense to rename "mycofactocin-coupled metabolic process" to  "mycofactocin-dependent electron transfer".     

Or give up on process, convert to function, and name it "mycofactocin-binding activity".    It is an inference, but the indirect evidence is now super strong.

**Comment by ValWood** [comment]
Hi Daniel,
Can you provide examples of gene products that  you would like to annotate to this term? That would help me to make sense of its position in the GO.  A new term request usually requires specific example genes which would be annotated.
I am worried that we are adding a grouping term for  processes that are unrelated other than their dependence on mycofactocin.

Also, I don't see a term "mycofactocin-coupled metabolic process"?
We only have a term for [GO:0140604](https://www.ebi.ac.uk/QuickGO/term/GO:0140604)   mycofactocin biosynthetic process?
