### ISSUE TITLE
Obsolete modulation by host of symbiont adenylate cyclase activity

### ISSUE THREAD

**Issue by genegodbold** [geneontology/go-ontology#21740]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0075075 (modulation by host of symbiont adenylate cyclase activity)

* **Reason for deprecation**
It has no annotations (http://amigo.geneontology.org/amigo/term/GO:0075075) and I cannot determine that this capacity in a host has ever existed.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 0

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**
This term has two children that cover negative and positive regulation by host of symbiont adenylate cyclase activity. They have no annotations should be ditched as well.

**Comment by pgaudet** [comment]
Hello, 

I propose to obsolete all classes 'modulation by organism of other organism molecular function that are not used. 

These term have no annotations and can be obsoleted now: 

Not used, to obsolete
induction by symbiont of host catalytic activity
induction by virus of host catalytic activity
induction by virus of host endoribonuclease activity
induction of autolysin activity in other organism
modulation by host of symbiont adenylate cyclase activity
modulation by host of symbiont peptidase activity
modulation by symbiont of host adenylate cyclase activity
modulation by symbiont of host peptidase activity
modulation by virus of host catalytic activity
modulation of peptidase activity in other organism involved in symbiotic interaction
negative regulation by host of symbiont adenylate cyclase activity
negative regulation by host of symbiont catalytic activity
negative regulation by host of symbiont peptidase activity
negative regulation by symbiont of host adenylate cyclase activity
negative regulation by symbiont of host catalytic activity
negative regulation by symbiont of host peptidase activity (2 annotations; deleted)
negative regulation of catalytic activity in other organism involved in symbiotic interaction
negative regulation of peptidase activity in other organism involved in symbiotic interaction
positive regulation by host of symbiont adenylate cyclase activity
positive regulation by host of symbiont catalytic activity (1 annotation; deleted)
positive regulation by symbiont of host adenylate cyclase activity
positive regulation of catalytic activity in other organism involved in symbiotic interaction (1 annotated; deleted)
suppression by virus of host ATP-dependent RNA helicase activity
suppression by virus of host protein kinase activity
suppression by virus of host protein tyrosine kinase activity


----

I need to review the following with @pmasson55 
induction by virus of host cysteine-type endopeptidase activity involved in apoptotic process
modulation by virus of host PP1 activity
modulation by virus of host protein serine/threonine phosphatase activity
modulation by virus of host ubiquitin-protein ligase activity
negative regulation by host of viral exo-alpha-sialidase activity
suppression by virus of host catalytic activity
suppression by virus of host cysteine-type endopeptidase activity involved in apoptotic process
suppression by virus of host JAK1 activity
suppression by virus of host PKR activity
suppression by virus of host TBK1 activity
suppression by virus of host TYK2 activity


These will remain as grouping classes
modulation by host of symbiont catalytic activity
modulation by symbiont of host catalytic activity

Thanks, Pascale

**Comment by pgaudet** [comment]
Merged 
- GO:0052405 negative regulation by host of symbiont molecular function (no annotations) into
GO:0052403 negative regulation by host of symbiont catalytic activity 

and 
- GO:0052428 modulation by host of symbiont molecular function
GO:0052422  modulation by host of symbiont catalytic activity
 namespace: biological_process

**Comment by pgaudet** [comment]
After discussion with @pmasson55 , I will fix other terms under 'GO:0052205 modulation of molecular function in other organism involved in symbiotic interaction' in different tickets.
