### ISSUE TITLE
Obsoletion:  GO:0036523 induction by symbiont of host cytokine production

### ISSUE THREAD

**Issue by genegodbold** [geneontology/go-ontology#21743]
This has no (0) annotations and is not a well thought-out term. What kind of cytokines? Proinflammatory or anti-inflammatory? Is the symbiont manipulating the host immune signaling pathways to "induce" this cytokine production? Or is the host reacting via pattern-recognition receptors (PRRs/PAMPs/MAMPs) to the presence of the parasite? If so, the symbiont is doing nothing and the host is doing its "job" so this doesn't involve the symbiont/parasite at all.

**Comment by pgaudet** [comment]
Right, this term needs to be obsoleted.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0036523 induction by symbiont of host cytokine production'. The reason for obsoletion is that it is not an evolved function of an symbiont, to induce host cytokine production; this is a response by the host to the presence of a potential pathogen. 

There is a single annotation to this term by BHL @RLovering 

This term is not in any subsets. There are no mappings to this term. 

You may comment on the ticket: https://github.com/geneontology/go-ontology/issues/21743

Thanks, Pascale

**Comment by RLovering** [comment]
Hi

happy for this term to be removed, although looking at the abstract weirdly it does look like the parasite increases cytokine release to attract more of it's target cells

https://pubmed.ncbi.nlm.nih.gov/25063865/

Please confirm obsoletion still planned and I will remove the annotation

Ruth

**Comment by genegodbold** [comment]
Hey @RLovering,
You may be right about the paper, but this is the wrong term for that activity. And there should be an annotation at a lower (molecular pathway) level that gets at what GP63 is doing. Looking at the level of "cytokine production" is too high. There is a lot of signal transduction that has to occur--presumably this is where GP63 is operating, before IL-6 and TNF are made. There are lots of cases of parasites triggering (purposefully/mechanistically) a host inflammatory pathway. Inflammasome activation by a parasite protease is an example.

I'm going to also go off in the weeds here, but this paper does NOT show mechanism. What I *think* is happening is that the changes being wrought in the host macrophages by Leishmania GP63 and LPG are being detected by the host which is sensitive to membrane perturbations of the sort being perpetrated by the parasite. (This also happens with other intracellular denizens like Mycobacterium tuberculosis: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7911501/.) Then the *host* is activating the inflammasome as a result and that is what results in TNF and IL-6 production. So it really is the host activating the pathway and not Leishmania. At least that's my story until they have better molecular evidence.

**Comment by pgaudet** [comment]
It looks like maybe Leishmania GP63 cleaves synaptotagmin, which trigger the host to activate signaling that leads to cytokine release? 

Then we could perhaps consider a term in the branch GO:0052028 induction by symbiont of host signal transduction pathway?

**Comment by RLovering** [comment]
good point I have replaced it with GO:0052028 induction by symbiont of host signal transduction pathway

**Comment by genegodbold** [comment]
There are a variety of activities that parasites do that are recognized as parasitic and activate what could be called parasite-recognition pathways. Microbial toxin activities that modify host small GTPases do this, changes in membrane dynamics do this. I suspect that in this case of Leishmania, that is what is happening. The researchers are NOT showing that GP63 or LPG are doing something to a host pro-inflammatory pathway that would be thought to activate it. But the activities of GP63 and LPG, including cleaving synaptogamin, are being detected by the host which *itself* activates inflammasomes leading to the production and secretion of IL-6 and TNF in the macrophages.

So what I've just described happens a lot and is a normal part of the innate immune system. Do we want to annotate every parasite protein that triggers these processes (in theory, I'm speaking) with GO:0052028 (induction by symbiont of host signal transduction pathway). This is just a passive thing. It's mainly about the host and innate recognition, not the parasite.

**Comment by genegodbold** [comment]
I grant you that your solution does get it out of this category. So that's good.

**Comment by pgaudet** [comment]
>  This is just a passive thing. It's mainly about the host and innate recognition, not the parasite.

Is this passive, as it cleaves the host receptor?

**Comment by genegodbold** [comment]
No, synaptogamin isn't the "host receptor" that I'm referring to. It isn't part of the innate system at all, to the best of my knowledge. My contention is that the cleavage or the results​ of the cleavage OR maybe something else entirely is what is detected by the host cell and that is what leads to inflammasome activation. The researchers have no mechanism of host inflammation in their paper. It's just hand-waving.
________________________________
