### ISSUE TITLE
resolve Rhea mapping for 'beta-carotene 15,15'-monooxygenase activity' GO:0003834

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21765]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/a18637ecd1bebafd3da89b8ab5e5f5de0f3d856211ed79874ce2c49e4ad996cb.png)

- [all-trans-beta-carotene + O2 = 2 all-trans-retinal](http://rdf.rhea-db.org/32887) EquivalentTo [EC:1.13.11.63](http://purl.uniprot.org/enzyme/1.13.11.63)	(most probable)	0.75
- [beta-carotene 15,15'-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0003834) EquivalentTo [EC:1.14.99.36](http://purl.uniprot.org/enzyme/1.14.99.36)	(most probable)	0.8
- [beta-carotene 15,15'-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0003834) ProperSubClassOf [all-trans-beta-carotene + O2 = 2 all-trans-retinal](http://rdf.rhea-db.org/32887)		0.08
- [all-trans-beta-carotene + O2 => 2 all-trans-retinal](http://rdf.rhea-db.org/32888) EquivalentTo [METACYC:RXN-13374](http://metacyc.org/RXN-13374)	(most probable)	0.75
- [beta-carotene 15,15'-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0003834) EquivalentTo [METACYC:BETA-CAROTENE-1515-DIOXYGENASE-RXN](http://metacyc.org/BETA-CAROTENE-1515-DIOXYGENASE-RXN)	(most probable)	0.8

**Comment by pgaudet** [comment]
EC:1.14.99.36 has been transferred to EC:1.13.11.63; fixed mapping. 

Thanks, Pascale
