### ISSUE TITLE
resolve mapping for '1,4-dihydroxy-2-naphthoyl-CoA synthase activity' GO:0008935

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21763]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/91e267ca22dbae4e057f6d00a94526a8da0a9731f15168c106f5acfacc1ded3c.png)

- [2-succinylbenzoyl-CoA + H(+) = 1,4-dihydroxy-2-naphthoyl-CoA + H2O](http://rdf.rhea-db.org/26562) EquivalentTo [EC:4.1.3.36](http://purl.uniprot.org/enzyme/4.1.3.36)	(most probable)	0.75
- [1,4-dihydroxy-2-naphthoyl-CoA synthase activity](http://purl.obolibrary.org/obo/GO_0008935) EquivalentTo [EC:4.1.3.36](http://purl.uniprot.org/enzyme/4.1.3.36)	(most probable)	0.8
- [2-succinylbenzoyl-CoA + H(+) => 1,4-dihydroxy-2-naphthoyl-CoA + H2O](http://rdf.rhea-db.org/26563) EquivalentTo [METACYC:NAPHTHOATE-SYN-RXN](http://metacyc.org/NAPHTHOATE-SYN-RXN)	(most probable)	0.75
- [1,4-dihydroxy-2-naphthoyl-CoA synthase activity](http://purl.obolibrary.org/obo/GO_0008935) ProperSubClassOf [2-succinylbenzoyl-CoA = 1,4-dihydroxy-2-naphthoate + CoA](http://rdf.rhea-db.org/15525)		0.08
- [1,4-dihydroxy-2-naphthoyl-CoA synthase activity](http://purl.obolibrary.org/obo/GO_0008935) EquivalentTo [METACYC:NAPHTHOATE-SYN-RXN](http://metacyc.org/NAPHTHOATE-SYN-RXN)	(most probable)	0.8

**Comment by pgaudet** [comment]
I will change the mapping to RHEA:26562

and the definition to include H+ - ie from 
> 4-(2-carboxyphenyl)-4-oxobutanoyl-CoA = 1,4-dihydroxy-2-napthoyl-CoA + H2O. 

to 

> 2-succinylbenzoyl-CoA + H+ = 1,4-dihydroxy-2-naphthoyl-CoA + H2O

as in RHEA.

Thanks, Pascale
