### ISSUE TITLE
resolve Rhea mapping for 'ABC-type sulfate transporter activity' GO:0015419, 'ABC-type thiosulfate transporter activity' GO:0102025

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21764]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/9875a61c6d9f24dab0a1a9b72d412f93fd634b63349171bd126d8b84db6668a0.png)

- [ATP + H2O + sulfate(out) => ADP + H(+) + phosphate + sulfate(in)](http://rdf.rhea-db.org/10193) EquivalentTo [METACYC:3.6.3.25-RXN](http://metacyc.org/3.6.3.25-RXN)	(most probable)	0.75
- [ATP + H2O + thiosulfate(out) = ADP + H(+) + phosphate + thiosulfate(in)](http://rdf.rhea-db.org/29871) EquivalentTo [EC:7.3.2.3](http://purl.uniprot.org/enzyme/7.3.2.3)	(most probable)	0.75
- [ATP + H2O + sulfate(out) = ADP + H(+) + phosphate + sulfate(in)](http://rdf.rhea-db.org/10192) ProperSubClassOf [EC:7.3.2.3](http://purl.uniprot.org/enzyme/7.3.2.3)		0.1
- [ABC-type thiosulfate transporter activity](http://purl.obolibrary.org/obo/GO_0102025) EquivalentTo [METACYC:ABC-7-RXN](http://metacyc.org/ABC-7-RXN)	(most probable)	0.8
- [ABC-type sulfate transporter activity](http://purl.obolibrary.org/obo/GO_0015419) EquivalentTo [ATP + H2O + sulfate(out) = ADP + H(+) + phosphate + sulfate(in)](http://rdf.rhea-db.org/10192)	(most probable)	0.8
- [ABC-type sulfate transporter activity](http://purl.obolibrary.org/obo/GO_0015419) ProperSubClassOf [EC:7.3.2.3](http://purl.uniprot.org/enzyme/7.3.2.3)	(most probable)	0.8
- [ABC-type thiosulfate transporter activity](http://purl.obolibrary.org/obo/GO_0102025) ProperSubClassOf [ATP + H2O + thiosulfate(out) = ADP + H(+) + phosphate + thiosulfate(in)](http://rdf.rhea-db.org/29871)		0.15
- [ABC-type thiosulfate transporter activity](http://purl.obolibrary.org/obo/GO_0102025) ProperSubClassOf [EC:7.3.2.3](http://purl.uniprot.org/enzyme/7.3.2.3)	(most probable)	0.8
- [ABC-type sulfate transporter activity](http://purl.obolibrary.org/obo/GO_0015419) EquivalentTo [METACYC:3.6.3.25-RXN](http://metacyc.org/3.6.3.25-RXN)	(most probable)	0.8

**Comment by hdrabkin** [comment]
is there evidence that the EC transporter def can actually be either sulfate OR thiosulfate? (RHEA has 2 mapping to the one GO term (which only specifies sulfate).

**Comment by hdrabkin** [comment]
@amorgat what evidence does RHEA have that the transporter uses either sulfate OR thiosulfate?

**Comment by pgaudet** [comment]
Looking at this with @amorgat - actually the ABC transporter transports the sulfate and thiosulfate delivered by carrier proteins, see PMID:7608089

So yes, the transporter transports both.

**Comment by hdrabkin** [comment]
Ok; so vaild EC for both GO terms, with separate RHEAs for each term. Metacyc has two different rxns one for sulfate, one for sulfite. 
So what's wrong here?

**Comment by pgaudet** [comment]
So, RHEA should get EXACT match and EC BROAD.

**Comment by hdrabkin** [comment]
@balhoff , would what pascal suggests solve this? Just changing xref type?

**Comment by balhoff** [comment]
Yes, I think it would be good to add the exactMatch to the Rhea xrefs, and this ought to resolve the issue in the next run. The ECs are already broad (suggested by the thick subclass arrows). There is also a duplicate unannotated EC xref on GO:0102025 that could be deleted.

**Comment by hdrabkin** [comment]
@balhoff what do you mean 'unannotated ' EC xref?  I see it marked as broadMatch, which we agreed is ok?
Both GO terms (thiosulfate and sulfate) would have same EC.

**Comment by balhoff** [comment]
In my go-edit I see two xrefs to the same EC, one with broadMatch and one plain.

**Comment by hdrabkin** [comment]
Ok, I'll look again; I didn't see that.

**Comment by hdrabkin** [comment]
I only see one instance. 
In the list seen in the annotations panel. 
However, int he OBO annotation panel, I see both ec and rhea but no xref types are displayed.
