### ISSUE TITLE
resolve Rhea mapping for '2-acylglycerol O-acyltransferase activity' GO:0003846

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21761]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/7801c836a6f7546b83c081983173d01156a139999b14a19300977ebc7f073f87.png)

- [2-acylglycerol O-acyltransferase activity](http://purl.obolibrary.org/obo/GO_0003846) EquivalentTo [EC:2.3.1.22](http://purl.uniprot.org/enzyme/2.3.1.22)	(most probable)	0.8
- [a 2-acylglycerol + an acyl-CoA = a 1,2-diacyl-sn-glycerol + CoA](http://rdf.rhea-db.org/32947) EquivalentTo [EC:2.3.1.22](http://purl.uniprot.org/enzyme/2.3.1.22)	(most probable)	0.75
- [2-acylglycerol O-acyltransferase activity](http://purl.obolibrary.org/obo/GO_0003846) EquivalentTo [METACYC:2-ACYLGLYCEROL-O-ACYLTRANSFERASE-RXN](http://metacyc.org/2-ACYLGLYCEROL-O-ACYLTRANSFERASE-RXN)	(most probable)	0.8
- [a 2-acylglycerol + an acyl-CoA <=> a 1,2-diacyl-sn-glycerol + CoA](http://rdf.rhea-db.org/32950) EquivalentTo [METACYC:2-ACYLGLYCEROL-O-ACYLTRANSFERASE-RXN](http://metacyc.org/2-ACYLGLYCEROL-O-ACYLTRANSFERASE-RXN)	(most probable)	0.75
- [2-acylglycerol O-acyltransferase activity](http://purl.obolibrary.org/obo/GO_0003846) ProperSubClassOf [a 2-acylglycerol + an acyl-CoA = a 1,2-diacylglycerol + CoA](http://rdf.rhea-db.org/16741)		0.08

**Comment by hdrabkin** [comment]
RHEA:32947 is more specific steroisomer of RHEA:16741
EC and GO do not specify isomere.
Will make EC and 16741 exact, and RHEA:32947 a narrow

**Comment by hdrabkin** [comment]
just realized this is done. Closing
