### ISSUE TITLE
GATOR1 complex revise def

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21778]
GATOR1

Old:
A protein complex involved in regulation of non-nitrogen-starvation (NNS) autophagic process. In humans, the GATOR1 complex consists of DEPDC5, NPRL2, and NPRL3). In S. cerevisiae, this complex is referred to as SEACIT AND contains the Iml1p, Npr2p, and Npr3p proteins. [PMID:25934700, PMID:28199306, PMID:23723238, PMID:23974112, PMID:21900499]

New
Genus and differentia:
A GTPase-activating protein (GAP) complex  for the Rag GTPase  (Gtr1-Gtr2 GTPase complex GO:1990131) in the TORC1 signalling pathway.

Gloss
In humans, the GATOR1 complex consists of DEPDC5, NPRL2, and NPRL3. In S. cerevisiae, this complex is referred to as SEACIT AND contains the Iml1p, Npr2p, and Npr3p proteins. 

Add parent:
GO:1905360    GTPase complex ?
is this the correct term. It has GO:0032045    guanyl-nucleotide exchange factor complex as a descendant. Is that correct?
@mah  does that seem right to you?

**Comment by ValWood** [comment]
Here is a ref PMID:29199950 for the def change:
Ragulator and GATOR1 complexes promote fission yeast growth by attenuating TOR complex 1 through Rag GTPases.

**Comment by mah11** [comment]
> GO:1905360 GTPase complex ... has GO:0032045 guanyl-nucleotide exchange factor complex as a descendant. Is that correct?

I don't see that link/path. If you mean the `GO:0032045 is_a GO:1902773` (GTPase activator complex) link ... well, I don't think GEFs really alter GTPase activity, but that's my undergraduate old-school enzymology lectures bubbling back to the surface, and it seems my opinion does not currently prevail with GO.

**Comment by ValWood** [comment]
> I don't think GEFs really alter GTPase activity

I thought so too. I  never really know. how to annotate them though. The don't activate the GTPase as the GAP does that.

**Comment by ValWood** [comment]
the parent 
Term: | Seh1-associated complex
GATOR complex \| SEA complex
A protein complex that associates dynamically with the vacuolar membrane, and is proposed to have a role in membrane-associated trafficking or regulatory processes. In S. cerevisiae the complex contains Seh1p, Sec13p, Npr2p, Npr3p, Iml1p, Mtc5p, Rtc1p, and Sea4p. [PMID:23974112, PMID:21454883]

Also has a very. out of date definition.. It isn't in llinee with the paper cited as a reference 
PMID:23974112


SEACing the GAP that nEGOCiates TORC1 activation: evolutionary conservation of Rag GTPase regulation
Nicolas Panchaud 1, Marie-Pierre Péli-Gulli, Claudio De Virgilio
Affiliations expand
PMID: 23974112 PMCID: PMC3875668 DOI: 10.4161/cc.26000
Free PMC article
Abstract
The target of rapamycin complex 1 (TORC1) regulates eukaryotic cell growth in response to a variety of input signals. In S. cerevisiae, amino acids activate TORC1 through the Rag guanosine triphosphatase (GTPase) heterodimer composed of Gtr1 and Gtr2 found together with Ego1 and Ego3 in the EGO complex (EGOC). The GTPase activity of Gtr1 is regulated by the SEA complex (SEAC). Specifically, SEACIT, a SEAC subcomplex containing Iml1, Npr2, and Npr3 functions as a GTPase activator (GAP) for Gtr1 to decrease the activity of TORC1 and, consequently, growth, after amino acid deprivation. Here, we present genetic epistasis data, which show that SEACAT, the other SEAC subcomplex, containing Seh1, Sea2-4, and Sec13, antagonizes the GAP function of SEACIT. Orthologs of EGOC (Ragulator), SEACIT (GATOR1), and SEACAT (GATOR2) are present in higher eukaryotes, highlighting the remarkable conservation, from yeast to man, of Rag GTPase and TORC1 regulation.

The reference to membrane associated trafficking should be removed. This is a major inhibitor of TORC1 signalling (early authors were probably influenced by downstream phenotypes, the presence of  (some) sec3 in the complex, and the vacuolar location.

**Comment by ValWood** [comment]
also add parent 
extrinsic component of vacuolar membrane (GO:0000306)

**Comment by pgaudet** [comment]
@lbreuza Does this look OK to you?

**Comment by pgaudet** [comment]
New defs: 
**GO:0035859 Seh1-associated complex**
+def: "A GTPase-activating protein (GAP) complex that regulates mTOR signaling by interacting with the Rag GTPase. In S. cerevisiae the complex contains Seh1p, Sec13p, Npr2p, Npr3p, Iml1p, Mtc5p, Rtc1p, and Sea4p." [GOC:jh, PMID:21454883, PMID:23974112]
+comment: The Rag GTPase complex corresponds to Gtr1-Gtr2 GTPase complex ;  GO:1990131.


**GO:1990130 GATOR1 complex**
+def: "A GTPase-activating protein (GAP) complex that regulates mTOR signaling by interacting with the Rag GTPase. In human, the GATOR1 complex consists of DEPDC5, NPRL2, and NPRL3. In S. cerevisiae, this complex is referred to as SEACIT and contains the Iml1p, Npr2p, and Npr3p proteins." [GOC:krc, GOC:rb, PMID:21900499, PMID:23723238, PMID:23974112, PMID:25934700, PMID:28199306, PMID:29199950]
+comment: The Rag GTPase complex corresponds to Gtr1-Gtr2 GTPase complex ;  GO:1990131.

**GO:0061700 GATOR2 complex**
+def: "A multiprotein subcomplex of the GATOR complex that regulates mTOR signaling by interacting with the Rag GTPase. In human, this complex consists of WDR24, WDR59, MIOS, SEH1L, and SEC13. In S. cerevisiae, this complex is referred to as SEACAT and contains the Sea2p, Sea3p, Sea4p, Seh1p, Sec13p proteins." [GOC:krc, GOC:rb, PMID:23723238, PMID:25934700]
+comment: The Rag GTPase complex corresponds to Gtr1-Gtr2 GTPase complex ;  GO:1990131.


Thanks, Pascale

**Comment by lbreuza** [comment]
Sorry for not replying earlier.

“regulates mTOR signaling” sounds too specific now that the definition also includes the yeast complex. Maybe we could change it to “regulates TORC1 signaling”.
mTOR stands for “Mammalian target of rapamycin”.

In addition, the GATOR1 complex might not be functionally conserved in mammals and yeast. What is the GO policy in that situation?

Hope it helps, Lionel

**Comment by ValWood** [comment]
Agreed, these defs should all say TOrc1 signalling not mTOR signalling. Yeast biologist are comfortable with mTOR signalling but this is actually broader  (Equivalent to TOR signalling).

GATOR1 does appear to be functionally conserved, at least in fission yeast. There is evidence for this in this recent paper https://www.pombase.org/reference/PMID:33534698

It is slightly complicated by the fact that sea3 appears to be a shared subunit between GATOR1&2 in fission yeast,  according to PMID:33534698

It's a really complicated pathway to model, and I have had  to abandon it for  a while for other commitments, so most of this has gone out of my head.  But mammalian Gtr1-Gtr2 acts as a switch (on and off) in fission yeast it acts more as a scaler- Even in nutrient-rich condition, fission yeast Gtr1 should be a GDP form and form a complex with Gtr2 to suppress TORC1 for optimal growth. 
I think most of the  activities align, but the implementation in different species is slightly different and not fully worked out. But I think these defs generic enough to work for any species,  since we don't say anything  the direction of regulation, or the nutrient situation (and can be tweaked later, but now seem more current).

I think the current defs are probably OK- part of the way to make the necessary distinctions about how the pathway is operating  will involve this 'on hold' ticket:
https://github.com/geneontology/go-ontology/issues/21283

**Comment by lbreuza** [comment]
Thank you @ValWood for the clarification. Indeed a very complicated pathway with a lot of new data that make it difficult to follow-up.

**Comment by ValWood** [comment]
This is a mock up of the "causal model"  during starvation:
<img width="636" alt="TOR_signalling" src="https://user-images.githubusercontent.com/7359272/129691234-f2488d51-7a7c-46ce-9916-e50ae9e24c7c.png">
If I get everything right  in the annotations a GO-CAM should eventually emerge where the different activation/inhibition matches the input condition (nitrogen or amino acid level). Luckily I can check with the authors if it reflects reality - but I have no idea how we can represent this " tempering behavior" We are modelling very much as either/or in GO-CAM......it doesn't quite work for TOR or MAPK signalling.....

**Comment by pgaudet** [comment]
I fixed 'regulates mTOR signaling ' to 'regulates TORC1 signaling' for all 3 terms
GO:0035859 Seh1-associated complex
GO:1990130 GATOR1 complex
GO:0061700  GATOR2 complex 

Thanks for catching this @lbreuza
