### ISSUE TITLE
Change label and synonym scope GO:0008094     ATPase, acting on DNA and GO:0008186 ATPase, acting on RNA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21775]
GO:0008094    ATPase, acting on DNA

synonyms
DNA dependent ATPase activity | exact
adenosinetriphosphatase (DNA-dependent) | exact
DNA-dependent ATPase activity | related
ATPase activity, acting on DNA | related

I am wondering why 
DNA-dependent ATPase activity | related
ATPase activity, acting on DNA | related

are not exact?

**Comment by pgaudet** [comment]
Fixed synonym types. 

Also made term labels consistent with parent: 

GO:0008094     ATPase, acting on DNA  -> ATP-dependent activity, acting on DNA
GO:0008186 ATPase, acting on RNA -> ATP-dependent activity, acting on RNA
