### ISSUE TITLE
Fix definition and parentage Ino80 complex (GO:0031011)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21776]
Definition | 
A multisubunit protein complex that contains the Ino80p ATPase; exhibits chromatin remodeling activity ~and 3' to 5' DNA helicase activity~.

reason: Ino80 is a ATP-dependent chromatin remodelled, but not a helicase.

also remove  is_a
DNA helicase complex (GO:0033202)

@colinlog 
@bmeldal 
@pgaudet

**Comment by bmeldal** [comment]
Acc to PMID:10952318, Fig 3, it has GO:0043138 3'-5' DNA helicase activity.

**Comment by ValWood** [comment]
I think it probably has in vitro, but it isn't now considered to be a helicase. @colinlog  is that correct?

**Comment by colinlog** [comment]
10952318 Nature 2000, shows (weak?) helicase activity for the complex, but they do not pin it down to one of the ATPases (INO80, Rvb1 or Revb2). So, Birgits helicase annotation is a fine representation of the biochemistry performed by the INO80 complex (although it is perhaps a dubious report / an artifactual helicase assay activity documentation), but, I would defintely not use this paper to annotate Rvb1/2 nor Ino80 ATPases as possessing [intrinsic/physiologically relevant] helicase activity.

From https://elifesciences.org/articles/63042 (PMID:33205750) it is clear that no helicase activity is detected for Rvb1/2. Rather, Ruvb1 and RuvB2 appear to be protein complex shakers/assembly chaperones. One quote from the intro is "**_RUVBL1 and RUVBL2 are essential constituents of several large complexes. In various chromatin-remodeling complexes such as INO80 and SRCAP, these ATPases form a scaffold that organizes the architecture of other subunits in the complex (Aramayo et al., 2018; Eustermann et al., 2018; Feng et al., 2018). RUVBL1 and RUVBL2 also interact with RPAP3 and PIH1D1 proteins to form the R2TP complex, a HSP90 co-chaperone involved in the assembly and maturation of some large complexes including RNA polymerase II and members of the Phosphatidylinositol 3-kinase-related kinase (PIKK) family such as ATR, ATM, SMG1, and mTOR (Houry et al., 2018; Martino et al., 2018; Maurizy et al., 2018; Muñoz-Hernández et al., 2019; Rivera-Calzada et al., 2017)._** ". Altogether, at this point in time I do not know of other papers than the 2000 Nature paper by Carl Wu that demonstrated helicase activity either for Ino80 SNF2-type DEAD/H ATPase or for the Rvb1/2 AAA+ ATPase rings. 

A chaperone/protein complex (dis)assembly activity that I would colloquially term 'protein complex shaking' is very likely for the Rvb1/2 rings.

**Comment by bmeldal** [comment]
So, in a nutshell, although there's weak _in vitro_ evidence that a INO80 complex might have helicase activity it's not generally accepted to have it _in vivo_. 

If that's the case, I'd happily remove it from the complexes.

**Comment by colinlog** [comment]
That would be the careful conclusion, unless data to the contrary is found in the literature.

**Comment by bmeldal** [comment]
Ok, helicase annotations removed. Can always be added again if new evidence emerges.

**Comment by colinlog** [comment]
The paper to look at for Rvb1/2 (Tip49a/b) helicase activity (and hexameric ring formation!) is PMID:18234224. What puzzles me is that in that paper the 5' to 3' helicase activity is strongest whilst in the other papers (including the Nature paper from 2000 PMID:10952318 as well as in PMID:10428817 and PMID:10336418 it was 3' to 5' activity that was highlighted and 5' to 3' that was considered weak. For sure, in PMID:18234224 the 3' to 5' helicase activity is weaker, and neither the Tip49 a only nor the Tip49b only reactions show any helicase activity. 

All in all, I am still unsure what helicase activity to annotate, but from this paper (PMID:18234224), the Rvb1/Rvb2 (aka Tip49a/b) complexes would be 5' to 3' helicases.

**Comment by pgaudet** [comment]
How about "A multisubunit protein complex that contains the Ino80p ATPase; exhibits chromatin remodeling activity and in some species there is evidence for DNA helicase activity." ? 

and remove the DNA helicase parentage.

**Comment by ValWood** [comment]
I don't know so I asked  Rob DeBruin whose lab works on Ino80.

SGD description of Ino80 is
ATPase and nucleosome spacing factor; subunit of complex containing actin and actin-related proteins that has chromatin remodeling activity and 3' to 5' DNA helicase activity in vitro; promotes nucleosome shifts in the 3 prime direction; has a role in modulating stress gene transcription

It seems that the in vivo role is clearly nucleosome sliding rather than DNA unwinding.

**Comment by pgaudet** [comment]
I am assigning you, let me know if you want a different edit.

**Comment by ValWood** [comment]
OK the person that I thought works on this complex does not.
But none of the high profile newer papers even mention a helicase role....

e.g.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8163841/

**Comment by ValWood** [comment]
The most recent pombe paper that really digs into the function in vivo also does not mention helicase.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5597579/
The Ino80 complex mediates epigenetic centromere propagation via active removal of histone H3

We should go with the current consensus.
