### ISSUE TITLE
NTR: nuclear envelope adjacent to nuclear pore complex

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#21774]
Please provide as much information as you can: 

* **Suggested term label:** nuclear envelope adjacent to nuclear pore complex

* **Definition (free text):** The region of the nuclear envelope situated in close proximity to a nuclear pore complex.

* **Reference:** PMID:21802294, PMID:24184107

* **Parent term(s):**
is_a: GO:0110165 ! cellular anatomical entity
relationship: part_of GO:0005635 ! nuclear envelope

* **Synonyms:**
  - "nuclear envelope adjacent to NPC" EXACT
  - "nuclear envelope periphery of the nuclear pore complex" EXACT
  - "associated with the nuclear pore" RELATED

* **Any other information**

Two existing terms could also have the RELATED synonym "associated with the nuclear pore" (and I used them as models for the GO:new text def):
- GO:1990723 ! cytoplasmic periphery of the nuclear pore complex
- GO:1990826 ! nucleoplasmic periphery of the nuclear pore complex

Requested on behalf of Snezhka Oliferenko for *S. japonicus* (JaponicusDB) curation, to annotate some integral membrane proteins that are enriched at the nuclear pores, but are not integral NPC components.

**Comment by krchristie** [comment]
@pgaudet - This one was simple & quick so I claimed it to get it done today.
