### ISSUE TITLE
resolve Rhea mapping for 'undecaprenyl-diphosphatase activity' GO:0050380

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21789]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/a3e62fa03214d8e2393453bca48eb0ba566fa3d3a2041cc29765441c6b698067.png)

- [undecaprenyl-diphosphatase activity](http://purl.obolibrary.org/obo/GO_0050380) ProperSubClassOf [all-trans-undecaprenyl diphosphate + H2O = all-trans-undecaprenyl phosphate + H(+) + phosphate](http://rdf.rhea-db.org/17069)		0.08
- [di-trans,octa-cis-undecaprenyl diphosphate + H2O = di-trans,octa-cis-undecaprenyl phosphate + H(+) + phosphate](http://rdf.rhea-db.org/28094) EquivalentTo [EC:3.6.1.27](http://purl.uniprot.org/enzyme/3.6.1.27)	(most probable)	0.75
- [undecaprenyl-diphosphatase activity](http://purl.obolibrary.org/obo/GO_0050380) EquivalentTo [METACYC:UNDECAPRENYL-DIPHOSPHATASE-RXN](http://metacyc.org/UNDECAPRENYL-DIPHOSPHATASE-RXN)	(most probable)	0.8
- [di-trans,octa-cis-undecaprenyl diphosphate + H2O => di-trans,octa-cis-undecaprenyl phosphate + H(+) + phosphate](http://rdf.rhea-db.org/28095) EquivalentTo [METACYC:UNDECAPRENYL-DIPHOSPHATASE-RXN](http://metacyc.org/UNDECAPRENYL-DIPHOSPHATASE-RXN)	(most probable)	0.75
- [undecaprenyl-diphosphatase activity](http://purl.obolibrary.org/obo/GO_0050380) EquivalentTo [EC:3.6.1.27](http://purl.uniprot.org/enzyme/3.6.1.27)	(most probable)	0.8

**Comment by pgaudet** [comment]
I will change the RHEA mapping to RHEA:28094, since this is the RHEA that is mapped to EC:3.6.1.27
