### ISSUE TITLE
resolve Rhea mapping for '17-beta-hydroxysteroid dehydrogenase (NADP+) activity' GO:0072582, 'estradiol 17-beta-dehydrogenase activity' GO:0004303, '17-beta-hydroxysteroid dehydrogenase (NAD+) activity' GO:0044594

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21791]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/a6bc60a3c0e52341995b407dbd4176858da6f55a9694b8cfd86a017e4882d3d0.png)

- [17beta-estradiol + NADP(+) = estrone + H(+) + NADPH](http://rdf.rhea-db.org/24616) ProperSubClassOf [EC:1.1.1.62](http://purl.uniprot.org/enzyme/1.1.1.62)		0.1
- [17-beta-hydroxysteroid dehydrogenase (NADP+) activity](http://purl.obolibrary.org/obo/GO_0072582) EquivalentTo [17beta-estradiol + NADP(+) = estrone + H(+) + NADPH](http://rdf.rhea-db.org/24616)	(most probable)	0.8
- [estradiol 17-beta-dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0004303) EquivalentTo [EC:1.1.1.62](http://purl.uniprot.org/enzyme/1.1.1.62)	(most probable)	0.8
- [17-beta-hydroxysteroid dehydrogenase (NAD+) activity](http://purl.obolibrary.org/obo/GO_0044594) ProperSubClassOf [17beta-estradiol + NAD(+) = estrone + H(+) + NADH](http://rdf.rhea-db.org/24612)		0.08
- [estrone + H(+) + NADPH => 17beta-estradiol + NADP(+)](http://rdf.rhea-db.org/24618) ProperSubClassOf [METACYC:ESTRADIOL-17-BETA-DEHYDROGENASE-RXN](http://metacyc.org/ESTRADIOL-17-BETA-DEHYDROGENASE-RXN)		0.1
- [17beta-estradiol + NADP(+) => estrone + H(+) + NADPH](http://rdf.rhea-db.org/24617) ProperSuperClassOf [REACTOME:R-HSA-5696822.1](http://reactome.org/R-HSA-5696822.1)	(most probable)	0.7
- [estrone + H(+) + NADPH => 17beta-estradiol + NADP(+)](http://rdf.rhea-db.org/24618) ProperSuperClassOf [REACTOME:R-HSA-804969.2](http://reactome.org/R-HSA-804969.2)	(most probable)	0.7
- [17beta-estradiol + NADP(+) => estrone + H(+) + NADPH](http://rdf.rhea-db.org/24617) ProperSuperClassOf [REACTOME:R-HSA-8862137.2](http://reactome.org/R-HSA-8862137.2)	(most probable)	0.7
- [estrone + H(+) + NADH => 17beta-estradiol + NAD(+)](http://rdf.rhea-db.org/24614) EquivalentTo [METACYC:ESTRADIOL-17-BETA-DEHYDROGENASE-RXN](http://metacyc.org/ESTRADIOL-17-BETA-DEHYDROGENASE-RXN)	(most probable)	0.75
- [estradiol 17-beta-dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0004303) EquivalentTo [METACYC:ESTRADIOL-17-BETA-DEHYDROGENASE-RXN](http://metacyc.org/ESTRADIOL-17-BETA-DEHYDROGENASE-RXN)	(most probable)	0.8
- [17beta-estradiol + NADP(+) => estrone + H(+) + NADPH](http://rdf.rhea-db.org/24617) ProperSuperClassOf [REACTOME:R-HSA-5693390.1](http://reactome.org/R-HSA-5693390.1)	(most probable)	0.7
- [17beta-estradiol + NAD(+) = estrone + H(+) + NADH](http://rdf.rhea-db.org/24612) EquivalentTo [EC:1.1.1.62](http://purl.uniprot.org/enzyme/1.1.1.62)	(most probable)	0.75
- [17beta-estradiol + NADP(+) => estrone + H(+) + NADPH](http://rdf.rhea-db.org/24617) ProperSuperClassOf [REACTOME:R-HSA-6810594.1](http://reactome.org/R-HSA-6810594.1)	(most probable)	0.7

**Comment by pgaudet** [comment]
Move: 
 [GO:0044594 17-beta-hydroxysteroid dehydrogenase (NAD+) activity](http://amigo.geneontology.org/amigo/term/GO:0044594#display-lineage-tab)
 [GO:0072582 17-beta-hydroxysteroid dehydrogenase (NADP+) activity](http://amigo.geneontology.org/amigo/term/GO:0072582#display-lineage-tab)

under [GO:0033764 steroid dehydrogenase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor]
