### ISSUE TITLE
resolve Rhea mapping for 'sodium-transporting ATPase activity, rotational mechanism' GO:0046962, 'sodium-transporting ATP synthase activity, rotational mechanism' GO:0046932, 'P-type sodium transporter activity' GO:0008554

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21796]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/c340b2576ce844a234d4a16233edcbfb7d597d666333c26e651e1a0e731113e4.png)

- [sodium-transporting ATPase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046962) EquivalentTo [ATP + H2O + 4 Na(+)(in) => ADP + H(+) + 4 Na(+)(out) + phosphate](http://rdf.rhea-db.org/58157)	(most probable)	0.8
- [ATP + H2O + Na(+)(in) => ADP + H(+) + Na(+)(out) + phosphate](http://rdf.rhea-db.org/14634) EquivalentTo [METACYC:3.6.3.7-RXN](http://metacyc.org/3.6.3.7-RXN)	(most probable)	0.75
- [sodium-transporting ATP synthase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046932) ProperSubClassOf [METACYC:3.6.3.15-RXN](http://metacyc.org/3.6.3.15-RXN)		0.08
- [sodium-transporting ATPase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046962) EquivalentTo [EC:7.2.2.1](http://purl.uniprot.org/enzyme/7.2.2.1)	(most probable)	0.8
- [ATP + H2O + Na(+)(in) = ADP + H(+) + Na(+)(out) + phosphate](http://rdf.rhea-db.org/14633) EquivalentTo [EC:7.2.2.3](http://purl.uniprot.org/enzyme/7.2.2.3)	(most probable)	0.75
- [ATP + H2O + 4 Na(+)(in) = ADP + H(+) + 4 Na(+)(out) + phosphate](http://rdf.rhea-db.org/58156) EquivalentTo [EC:7.2.2.1](http://purl.uniprot.org/enzyme/7.2.2.1)	(most probable)	0.75
- [P-type sodium transporter activity](http://purl.obolibrary.org/obo/GO_0008554) EquivalentTo [METACYC:3.6.3.7-RXN](http://metacyc.org/3.6.3.7-RXN)	(most probable)	0.8
- [ATP + H2O + Na(+)(in) => ADP + H(+) + Na(+)(out) + phosphate](http://rdf.rhea-db.org/14634) ProperSubClassOf [METACYC:3.6.3.15-RXN](http://metacyc.org/3.6.3.15-RXN)		0.1
- [ATP + H2O + 4 Na(+)(in) <=> ADP + H(+) + 4 Na(+)(out) + phosphate](http://rdf.rhea-db.org/58159) EquivalentTo [METACYC:3.6.3.15-RXN](http://metacyc.org/3.6.3.15-RXN)	(most probable)	0.75
- [sodium-transporting ATPase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046962) EquivalentTo [METACYC:3.6.3.15-RXN](http://metacyc.org/3.6.3.15-RXN)	(most probable)	0.8
- [P-type sodium transporter activity](http://purl.obolibrary.org/obo/GO_0008554) EquivalentTo [ATP + H2O + Na(+)(in) = ADP + H(+) + Na(+)(out) + phosphate](http://rdf.rhea-db.org/14633)	(most probable)	0.8
- [ATP + H2O + Na(+)(in) = ADP + H(+) + Na(+)(out) + phosphate](http://rdf.rhea-db.org/14633) ProperSubClassOf [EC:7.2.2.4](http://purl.uniprot.org/enzyme/7.2.2.4)		0.1
- [sodium-transporting ATP synthase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046932) ProperSubClassOf [EC:7.2.2.1](http://purl.uniprot.org/enzyme/7.2.2.1)		0.08
- [P-type sodium transporter activity](http://purl.obolibrary.org/obo/GO_0008554) EquivalentTo [EC:7.2.2.3](http://purl.uniprot.org/enzyme/7.2.2.3)	(most probable)	0.8
- [ATP + H2O + Na(+)(in) => ADP + H(+) + Na(+)(out) + phosphate](http://rdf.rhea-db.org/14634) ProperSubClassOf [METACYC:RXN-19779](http://metacyc.org/RXN-19779)		0.1
- [sodium-transporting ATP synthase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046932) ProperSubClassOf [ADP + H(+) + 4 Na(+)(out) + phosphate => ATP + H2O + 4 Na(+)(in)](http://rdf.rhea-db.org/58158)		0.08

**Comment by pgaudet** [comment]
- [ ] 'sodium-transporting ATPase activity, rotational mechanism' GO:0046962 : Def is "Enables the transfer of protons from one side of a membrane to the other according to the reaction: ATP + H2O + H+(in) = ADP + phosphate + H+(out), by a rotational mechanism." - but e.g. PMID:30791207 states "under physiological conditions catalyzes the synthesis of ATP from ADP and Pi"; so the definition, while correct (because of the =), is a misleading for curators.

**Comment by pgaudet** [comment]
GO:0008554, 'P-type sodium transporter activity' -> change Rhea mapping to BROAD, as this also represents the ABC sodium transporter

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140679
+name: ABC-type sodium transporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Na(in) -> ADP + phosphate + Na(out)." [PMID:9106203]
+xref: EC:7.2.2.4 {source="skos:exactMatch"}
+xref: RHEA:14633 {source="skos:boradMatch"}
+xref: TC:3.A.1.115.1
+is_a: GO:0140359 ! ABC-type transporter activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21796 xsd:anyURI
+created_by: pg
+creation_date: 2021-07-08T11:22:56Z
