### ISSUE TITLE
NTR: 'de novo' GMP biosynthetic process

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#21798]
Please provide as much information as you can: 

* **Suggested term label:**
'de novo' GMP biosynthetic process

* **Definition (free text)**
The chemical reactions and pathways resulting in the formation of guanosine 5'-monophosphate (GMP) through an inosine 5'-monophosphate (IMP) intermediate.

* **Reference, in format PMID:#######**
PMID:25605736

* **Parent term(s)**
GMP biosynthetic process (GO:0006177)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* 'de novo' guanosine 5'-monophosphate biosynthetic process (exact)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
@hdrabkin @deustp01  do you think it would be worthwhile to create the generic 'de novo' purine nucleotide 5'-monophosphate biosynthetic process' term as well? This might allow us to create logical definitions.

**Comment by hdrabkin** [comment]
@hdrabkin @deustp01 do you think it would be worthwhile to create the generic 'de novo' purine nucleotide 5'-monophosphate biosynthetic process' term as well? 
Childe of purine nucleotide biosynthetic process (GO:0006164)?

**Comment by hdrabkin** [comment]
+id: GO:0106387
+name: 'de novo' GMP biosynthetic process

**Comment by ukemi** [comment]
Child of purine nucleotide biosynthetic process (GO:0006164)?

Yeah. Let's talk about this on the call tomorrow.
