### ISSUE TITLE
resolve Rhea mapping for 'beta-1,3-galactosyl-O-glycosyl-glycoprotein beta-1,6-N-acetylglucosaminyltransferase activity' GO:0003829

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21793]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/b2956f0b3b1acaa6b17a1b802499ad2ff859a618ab1a30ba06e69c6b5d4a1d1a.png)

- [O(3)-[beta-D-galactosyl-(1->3)-N-acetyl-alpha-D-galactosaminyl]-L-threonyl-[protein] + UDP-N-acetyl-alpha-D-glucosamine => 3-O-{beta-D-galactosyl-(1->3)-[N-acetyl-beta-D-glucosaminyl-(1->6)]-N-acetyl-alpha-D-galactosaminyl}-L-threonyl-[protein] + H(+) + UDP](http://rdf.rhea-db.org/56217) EquivalentTo [METACYC:2.4.1.102-RXN](http://metacyc.org/2.4.1.102-RXN)	(most probable)	0.75
- [beta-1,3-galactosyl-O-glycosyl-glycoprotein beta-1,6-N-acetylglucosaminyltransferase activity](http://purl.obolibrary.org/obo/GO_0003829) EquivalentTo [EC:2.4.1.102](http://purl.uniprot.org/enzyme/2.4.1.102)	(most probable)	0.8
- [beta-1,3-galactosyl-O-glycosyl-glycoprotein beta-1,6-N-acetylglucosaminyltransferase activity](http://purl.obolibrary.org/obo/GO_0003829) ProperSubClassOf [a beta-D-galactosyl-(1->3)-N-acetyl-alpha-D-galactosaminyl derivative + UDP-N-acetyl-alpha-D-glucosamine = a beta-D-galactosyl-(1->3)-[N-acetyl-beta-D-glucosaminyl-(1->6)]-N-acetyl-alpha-D-galactosaminyl derivative + H(+) + UDP](http://rdf.rhea-db.org/18705)		0.08
- [beta-1,3-galactosyl-O-glycosyl-glycoprotein beta-1,6-N-acetylglucosaminyltransferase activity](http://purl.obolibrary.org/obo/GO_0003829) EquivalentTo [METACYC:2.4.1.102-RXN](http://metacyc.org/2.4.1.102-RXN)	(most probable)	0.8
- [O(3)-[beta-D-galactosyl-(1->3)-N-acetyl-alpha-D-galactosaminyl]-L-threonyl-[protein] + UDP-N-acetyl-alpha-D-glucosamine = 3-O-{beta-D-galactosyl-(1->3)-[N-acetyl-beta-D-glucosaminyl-(1->6)]-N-acetyl-alpha-D-galactosaminyl}-L-threonyl-[protein] + H(+) + UDP](http://rdf.rhea-db.org/56216) EquivalentTo [EC:2.4.1.102](http://purl.uniprot.org/enzyme/2.4.1.102)	(most probable)	0.75
- [O(3)-[beta-D-galactosyl-(1->3)-N-acetyl-alpha-D-galactosaminyl]-L-seryl-[protein] + UDP-N-acetyl-alpha-D-glucosamine => 3-O-{beta-D-galactosyl-(1->3)-[N-acetyl-beta-D-glucosaminyl-(1->6)]-N-acetyl-alpha-D-galactosaminyl}-L-seryl-[protein] + H(+) + UDP](http://rdf.rhea-db.org/56213) ProperSubClassOf [METACYC:2.4.1.102-RXN](http://metacyc.org/2.4.1.102-RXN)		0.1
- [O(3)-[beta-D-galactosyl-(1->3)-N-acetyl-alpha-D-galactosaminyl]-L-seryl-[protein] + UDP-N-acetyl-alpha-D-glucosamine = 3-O-{beta-D-galactosyl-(1->3)-[N-acetyl-beta-D-glucosaminyl-(1->6)]-N-acetyl-alpha-D-galactosaminyl}-L-seryl-[protein] + H(+) + UDP](http://rdf.rhea-db.org/56212) ProperSubClassOf [EC:2.4.1.102](http://purl.uniprot.org/enzyme/2.4.1.102)		0.1

**Comment by pgaudet** [comment]
Mappings are OK - added xreference types.
