### ISSUE TITLE
resolve Rhea mapping for 'long-chain-(S)-2-hydroxy-long-chain-acid oxidase activity' GO:0052853, '(S)-2-hydroxy-acid oxidase activity' GO:0003973, 'glycolate oxidase activity' GO:0008891, 'medium-chain-(S)-2-hydroxy-acid oxidase activity' GO:0052854, 'very-long-chain-(S)-2-hydroxy-acid oxidase activity' GO:0052852

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21795]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/bba60a1d82d67d888bd7cd3879e601392f32074ce28132ea115312e6361f5c44.png)

- [long-chain-(S)-2-hydroxy-long-chain-acid oxidase activity](http://purl.obolibrary.org/obo/GO_0052853) ProperSubClassOf [EC:1.1.3.15](http://purl.uniprot.org/enzyme/1.1.3.15)		0.08
- [glycolate + O2 = glyoxylate + H2O2](http://rdf.rhea-db.org/25311) ProperSuperClassOf [EC:1.1.3.15](http://purl.uniprot.org/enzyme/1.1.3.15)		0.1
- [(S)-2-hydroxy-acid oxidase activity](http://purl.obolibrary.org/obo/GO_0003973) EquivalentTo [a (2S)-2-hydroxycarboxylate + O2 = a 2-oxocarboxylate + H2O2](http://rdf.rhea-db.org/16789)	(most probable)	0.6
- [glycolate oxidase activity](http://purl.obolibrary.org/obo/GO_0008891) EquivalentTo [METACYC:RXN-969](http://metacyc.org/RXN-969)	(most probable)	0.8
- [(S)-2-hydroxy-acid oxidase activity](http://purl.obolibrary.org/obo/GO_0003973) EquivalentTo [METACYC:S-2-HYDROXY-ACID-OXIDASE-RXN](http://metacyc.org/S-2-HYDROXY-ACID-OXIDASE-RXN)	(most probable)	0.8
- [glycolate + O2 => glyoxylate + H2O2](http://rdf.rhea-db.org/25312) ProperSuperClassOf [REACTOME:R-HSA-389842.5](http://reactome.org/R-HSA-389842.5)	(most probable)	0.7
- [a (2S)-2-hydroxycarboxylate + O2 => a 2-oxocarboxylate + H2O2](http://rdf.rhea-db.org/16790) EquivalentTo [METACYC:S-2-HYDROXY-ACID-OXIDASE-RXN](http://metacyc.org/S-2-HYDROXY-ACID-OXIDASE-RXN)	(most probable)	0.75
- [(S)-2-hydroxy-acid oxidase activity](http://purl.obolibrary.org/obo/GO_0003973) EquivalentTo [EC:1.1.3.15](http://purl.uniprot.org/enzyme/1.1.3.15)	(most probable)	0.8
- [medium-chain-(S)-2-hydroxy-acid oxidase activity](http://purl.obolibrary.org/obo/GO_0052854) ProperSubClassOf [EC:1.1.3.15](http://purl.uniprot.org/enzyme/1.1.3.15)		0.08
- [a (2S)-2-hydroxycarboxylate + O2 = a 2-oxocarboxylate + H2O2](http://rdf.rhea-db.org/16789) EquivalentTo [EC:1.1.3.15](http://purl.uniprot.org/enzyme/1.1.3.15)	(most probable)	0.75
- [glycolate oxidase activity](http://purl.obolibrary.org/obo/GO_0008891) ProperSubClassOf [glycolate + O2 = glyoxylate + H2O2](http://rdf.rhea-db.org/25311)		0.15
- [glycolate + O2 => glyoxylate + H2O2](http://rdf.rhea-db.org/25312) ProperSuperClassOf [METACYC:RXN-969](http://metacyc.org/RXN-969)		0.1
- [very-long-chain-(S)-2-hydroxy-acid oxidase activity](http://purl.obolibrary.org/obo/GO_0052852) ProperSubClassOf [EC:1.1.3.15](http://purl.uniprot.org/enzyme/1.1.3.15)		0.08

**Comment by pgaudet** [comment]
GO:0008891 glycolate oxidase activity (S)-2-hydroxy acid + O(2) <=> 2-oxo acid + H(2)O(2)
and GO:0003973 (S)-2-hydroxy-acid oxidase activity (S)-2-hydroxy-acid + O2 = 2-oxo acid + hydrogen peroxide

=> exactly the same definition.

Out of the other 3 children, 
.. GO:0052853 long-chain-(S)-2-hydroxy-long-chain-acid oxidase activity
.. GO:0052854 medium-chain-(S)-2-hydroxy-acid oxidase activity 
.. GO:0052852 very-long-chain-(S)-2-hydroxy-acid oxidase activity 

only one has an EXP annotation, and it's also annotated to GO:0003973 (S)-2-hydroxy-acid oxidase activity 

All 5 terms have the same EC mapping, EC:1.1.3.15

So I will merge all terms into the parent GO:0003973 (S)-2-hydroxy-acid oxidase activity.
