### ISSUE TITLE
resolve Rhea mapping for 'muconate cycloisomerase activity' GO:0018849

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21794]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/b579b29dd9d12de0e561db2a3461b7c5f49c9761d049e48e1328a43c3ef0f212.png)

- [muconate cycloisomerase activity](http://purl.obolibrary.org/obo/GO_0018849) EquivalentTo [EC:5.5.1.1](http://purl.uniprot.org/enzyme/5.5.1.1)	(most probable)	0.8
- [(S)-muconolactone = cis,cis-muconate + H(+)](http://rdf.rhea-db.org/30031) EquivalentTo [EC:5.5.1.1](http://purl.uniprot.org/enzyme/5.5.1.1)	(most probable)	0.75
- [muconate cycloisomerase activity](http://purl.obolibrary.org/obo/GO_0018849) EquivalentTo [METACYC:MUCONATE-CYCLOISOMERASE-RXN](http://metacyc.org/MUCONATE-CYCLOISOMERASE-RXN)	(most probable)	0.8
- [cis,cis-muconate + H(+) => (S)-muconolactone](http://rdf.rhea-db.org/30033) EquivalentTo [METACYC:MUCONATE-CYCLOISOMERASE-RXN](http://metacyc.org/MUCONATE-CYCLOISOMERASE-RXN)	(most probable)	0.75
- [muconate cycloisomerase activity](http://purl.obolibrary.org/obo/GO_0018849) ProperSubClassOf [muconolactone = cis,cis-muconate + H(+)](http://rdf.rhea-db.org/10640)		0.08

**Comment by pgaudet** [comment]
- Changed RHEA to RHEA:30031 for GO:0018849
- Merged     GO:0018842  3-carboxymuconate cycloisomerase type II activity into GO:00047472 as suggested in https://github.com/geneontology/go-ontology/issues/20247#issuecomment-719875647 - reaction is the same, with compounds using different labels.
