### ISSUE TITLE
resolve Rhea mapping for 'trans-feruloyl-CoA synthase activity' GO:0050563

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21805]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/f2f3c3a409427d411f859be0c476b97a5da377a100d1c10e3584c28d38cd404a.png)

- [(E)-ferulate + ATP + CoA = (E)-feruloyl-CoA + AMP + diphosphate](http://rdf.rhea-db.org/36251) EquivalentTo [EC:6.2.1.34](http://purl.uniprot.org/enzyme/6.2.1.34)	(most probable)	0.75
- [(E)-ferulate + ATP + CoA => (E)-feruloyl-CoA + AMP + diphosphate](http://rdf.rhea-db.org/36252) EquivalentTo [METACYC:6.2.1.34-RXN](http://metacyc.org/6.2.1.34-RXN)	(most probable)	0.75
- [(E)-ferulate + ATP + CoA = (E)-feruloyl-CoA + ADP + phosphate](http://rdf.rhea-db.org/19389) ProperSubClassOf [EC:6.2.1.34](http://purl.uniprot.org/enzyme/6.2.1.34)		0.1
- [trans-feruloyl-CoA synthase activity](http://purl.obolibrary.org/obo/GO_0050563) EquivalentTo [EC:6.2.1.34](http://purl.uniprot.org/enzyme/6.2.1.34)	(most probable)	0.8
- [trans-feruloyl-CoA synthase activity](http://purl.obolibrary.org/obo/GO_0050563) ProperSuperClassOf [(E)-ferulate + ATP + CoA = (E)-feruloyl-CoA + ADP + phosphate](http://rdf.rhea-db.org/19389)		0.15
- [trans-feruloyl-CoA synthase activity](http://purl.obolibrary.org/obo/GO_0050563) EquivalentTo [METACYC:6.2.1.34-RXN](http://metacyc.org/6.2.1.34-RXN)	(most probable)	0.8

**Comment by hdrabkin** [comment]
Should we make parent fo rheas because according to ec, 't has not yet been established whether AMP + diphosphate or ADP + phosphate are formed in this reaction'
Is that true. Look at refs for the two rheas to see.

**Comment by hdrabkin** [comment]
EC changed to broadMatch (unspecified ADP or AMP in reaction)
RHEA made exactMatch
