### ISSUE TITLE
resolve Rhea mapping for 'NAD glycohydrolase activity' GO:0061810, 'NAD(P)+ nucleosidase activity' GO:0050135, 'NAD+ nucleosidase activity' GO:0003953, 'NAD+ nucleotidase, cyclic ADP-ribose generating' GO:0061809

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21807]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/ff77ea66d618be59e05b4d31d791a106e96df24add67113efa5136971ecdfece.png)

- [NAD+ nucleotidase, cyclic ADP-ribose generating](http://purl.obolibrary.org/obo/GO_0061809) EquivalentTo [METACYC:NADNUCLEOSID-RXN](http://metacyc.org/NADNUCLEOSID-RXN)	(most probable)	0.8
- [NAD+ nucleotidase, cyclic ADP-ribose generating](http://purl.obolibrary.org/obo/GO_0061809) EquivalentTo [EC:3.2.2.6](http://purl.uniprot.org/enzyme/3.2.2.6)	(most probable)	0.8
- [H2O + NAD(+) => ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16302) EquivalentTo [METACYC:NADNUCLEOSID-RXN](http://metacyc.org/NADNUCLEOSID-RXN)	(most probable)	0.75
- [H2O + NAD(+) => ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16302) ProperSuperClassOf [REACTOME:R-HSA-8938076.1](http://reactome.org/R-HSA-8938076.1)	(most probable)	0.7
- [H2O + NAD(+) = ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16301) ProperSubClassOf [EC:3.2.2.5](http://purl.uniprot.org/enzyme/3.2.2.5)		0.1
- [NAD glycohydrolase activity](http://purl.obolibrary.org/obo/GO_0061810) EquivalentTo [EC:3.2.2.5](http://purl.uniprot.org/enzyme/3.2.2.5)	(most probable)	0.8
- [H2O + NAD(+) => ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16302) ProperSuperClassOf [REACTOME:R-HSA-8870346.2](http://reactome.org/R-HSA-8870346.2)	(most probable)	0.7
- [NAD(P)+ nucleosidase activity](http://purl.obolibrary.org/obo/GO_0050135) EquivalentTo [METACYC:NADP+-NUCLEOSIDASE-RXN](http://metacyc.org/NADP+-NUCLEOSIDASE-RXN)	(most probable)	0.8
- [NAD(P)+ nucleosidase activity](http://purl.obolibrary.org/obo/GO_0050135) ProperSubClassOf [EC:3.2.2.6](http://purl.uniprot.org/enzyme/3.2.2.6)		0.08
- [H2O + NAD(+) => ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16302) ProperSuperClassOf [REACTOME:R-HSA-9637699.1](http://reactome.org/R-HSA-9637699.1)	(most probable)	0.7
- [H2O + NAD(+) = ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16301) EquivalentTo [EC:3.2.2.6](http://purl.uniprot.org/enzyme/3.2.2.6)	(most probable)	0.75
- [NAD+ nucleosidase activity](http://purl.obolibrary.org/obo/GO_0003953) ProperSuperClassOf [H2O + NAD(+) = ADP-D-ribose + H(+) + nicotinamide](http://rdf.rhea-db.org/16301)		0.08

**Comment by hdrabkin** [comment]
We can find no reactions that use NADP at all; 50135 should be merged into the NAD+ reaction (ie, there is no such thing as NAD(P) in nature as far as we can tell.

**Comment by hdrabkin** [comment]
But google scholar may have papers that use both; will check

**Comment by hdrabkin** [comment]
Found paper in use for annotation that notes also uses NADP

**Comment by hdrabkin** [comment]
Modify parentage? 
remove 50135 to ec 3.2.2.6

3.2.2.5 	    NAD(+) glycohydrolase 	       						 	       						 	       				EC 3.2.2.6 	 ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase
both have same RHEA; BUT RHEA dos not have the cyclic ADP-ribose as a substrate....

**Comment by hdrabkin** [comment]
@amorgat , why do these two ecs have the same RHEA ?

**Comment by amorgat** [comment]
https://www.enzyme-database.org/query.php?ec=3.2.2.5
Reaction:  NAD+ + H2O = ADP-D-ribose + nicotinamide

https://www.enzyme-database.org/query.php?ec=3.2.2.6
Reaction:  NAD+ + H2O = ADP-D-ribose + nicotinamide (overall reaction)
(1a) NAD+ = cyclic ADP-ribose + nicotinamide
(1b) cyclic ADP-ribose + H2O = ADP-D-ribose

See the comment of RHEA:16301 (https://www.rhea-db.org/rhea/16301)
Multi-step reaction (EC 3.2.2.6 only): RHEA:38611 and RHEA:38615 EC 3.2.2.5 catalyses the hydrolysis of NAD+, without associated ADP-ribosyl cyclase activity (unlike enzyme EC 3.2.2.6, bifunctional ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase).

We have the 2 step reactions in Rhea
https://www.rhea-db.org/rhea/38611
https://www.rhea-db.org/rhea/38615

We don't export the relationships between RHEA:38611 and RHEA:38615 - it's in our to-do list...

**Comment by balhoff** [comment]
Closing; will re-run boomer and open any new issues found.
