### ISSUE TITLE
resolve Rhea mapping for 'inositol phosphorylceramide mannosyltransferase activity' GO:0103064

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21803]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/e0e718c2edcbd61187b18fe6afd5f11f0cc4b519d227d190b5d3d5f51b0b5e2b.png)

- [inositol phosphorylceramide mannosyltransferase activity](http://purl.obolibrary.org/obo/GO_0103064) ProperSubClassOf [an inositol-1-phospho-N-(2-hydroxy-very-long-chain fatty acyl)-4R-hydroxysphingoid base + GDP-alpha-D-mannose = an alpha-D-mannosyl-(1<->6)-1D-myo-inositol-1-phospho-N-(2-hydroxy-very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base + GDP + H(+)](http://rdf.rhea-db.org/61496)		0.15
- [a 1D-myo-inositol-1-phospho-N-[(R)-2-hydroxy-very-long-chain fatty acyl]-(R)-4-hydroxysphingoid base + GDP-alpha-D-mannose => an alpha-D-mannosyl-(1<->6)-1D-myo-inositol-1-phospho-N-[(R)-2-hydroxy-very-long-chain fatty acyl]-(R)-4-hydroxysphingoid base + GDP + H(+)](http://rdf.rhea-db.org/64597) EquivalentTo [METACYC:RXN3O-663](http://metacyc.org/RXN3O-663)	(most probable)	0.75
- [a 1D-myo-inositol-1-phospho-N-[(R)-2-hydroxy-very-long-chain fatty acyl]-(R)-4-hydroxysphingoid base + GDP-alpha-D-mannose = an alpha-D-mannosyl-(1<->6)-1D-myo-inositol-1-phospho-N-[(R)-2-hydroxy-very-long-chain fatty acyl]-(R)-4-hydroxysphingoid base + GDP + H(+)](http://rdf.rhea-db.org/64596) EquivalentTo [EC:2.4.1.370](http://purl.uniprot.org/enzyme/2.4.1.370)	(most probable)	0.75
- [inositol phosphorylceramide mannosyltransferase activity](http://purl.obolibrary.org/obo/GO_0103064) EquivalentTo [METACYC:RXN3O-663](http://metacyc.org/RXN3O-663)	(most probable)	0.8

**Comment by pgaudet** [comment]
Fixed to align with RHEA: 

- fix def: "Catalysis of the reaction: a 1D-myo-inositol-1-phospho-N-[(R)-2-hydroxy-very-long-chain fatty acyl]-(R)-4-hydroxysphingoid base + GDP-α-D-mannose = an α-D-mannosyl-(1,6)-1D-myo-inositol-1-phospho-N-[(R)-2-hydroxy-very-long-chain fatty acyl]-(R)-4-hydroxysphingoid base + GDP + H+." [GOC:pz, RHEA:64596]
- add xref: EC:2.4.1.370 {source="skos:exactMatch"}
- add xref: https://github.com/geneontology/go-ontology/issues/21803
- edit xref type: MetaCyc:RXN3O-663 {source="skos:exactMatch"}
- change xref: RHEA:64596 {source="skos:exactMatch"} (removed  RHEA:61496)
