### ISSUE TITLE
resolve Rhea mapping for 'CTP synthase activity' GO:0003883

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21802]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/e02ee4af9c63fd0fa7ea186205fb258c22bd8675c6ab2aa0eb24584c02cb553a.png)

- [CTP synthase activity](http://purl.obolibrary.org/obo/GO_0003883) EquivalentTo [EC:6.3.4.2](http://purl.uniprot.org/enzyme/6.3.4.2)	(most probable)	0.8
- [ATP + H2O + L-glutamine + UTP => ADP + CTP + 2 H(+) + L-glutamate + phosphate](http://rdf.rhea-db.org/26427) ProperSuperClassOf [REACTOME:R-HSA-73647.3](http://reactome.org/R-HSA-73647.3)	(most probable)	0.7
- [ATP + H2O + L-glutamine + UTP => ADP + CTP + 2 H(+) + L-glutamate + phosphate](http://rdf.rhea-db.org/26427) EquivalentTo [METACYC:CTPSYN-RXN](http://metacyc.org/CTPSYN-RXN)	(most probable)	0.75
- [CTP synthase activity](http://purl.obolibrary.org/obo/GO_0003883) ProperSubClassOf [ATP + NH4(+) + UTP = ADP + CTP + 2 H(+) + phosphate](http://rdf.rhea-db.org/16597)		0.08
- [CTP synthase activity](http://purl.obolibrary.org/obo/GO_0003883) EquivalentTo [METACYC:CTPSYN-RXN](http://metacyc.org/CTPSYN-RXN)	(most probable)	0.8
- [ATP + NH4(+) + UTP => ADP + CTP + 2 H(+) + phosphate](http://rdf.rhea-db.org/16598) EquivalentTo [METACYC:RXN-14325](http://metacyc.org/RXN-14325)	(most probable)	0.75
- [ATP + H2O + L-glutamine + UTP = ADP + CTP + 2 H(+) + L-glutamate + phosphate](http://rdf.rhea-db.org/26426) EquivalentTo [EC:6.3.4.2](http://purl.uniprot.org/enzyme/6.3.4.2)	(most probable)	0.75
- [ATP + H2O + L-glutamine + UTP => ADP + CTP + 2 H(+) + L-glutamate + phosphate](http://rdf.rhea-db.org/26427) ProperSuperClassOf [REACTOME:R-HSA-504054.3](http://reactome.org/R-HSA-504054.3)	(most probable)	0.7

**Comment by hdrabkin** [comment]
GO:0003883 uses ammonia, Not REHA:26426
Need CTP synthase glutamine hydrolyzing and map it to RHEA: 26426

**Comment by balhoff** [comment]
@hdrabkin do you like the GO:0003883 mapping to RHEA:16597 (current xref)? If so should the GO term's EC and METACYC xrefs be changed or adjusted to narrow/broad?

**Comment by hdrabkin** [comment]
It's a long story. The EC mapping covers two reactions. One uses NH4, the other one glutamine. Glutamine rxn may not be in GO that we can find.

**Comment by hdrabkin** [comment]
The EC will map to BOTH current rxn and the new one.

**Comment by pgaudet** [comment]
Do we need  2 terms? This is another multistep reaction: https://www.rhea-db.org/rhea/26426 

RHEA:15889 O2 + L-glutamine = L-glutamate  + NH4+
RHEA:26426  ATP + H2O + L-glutamine + UTP  = ADP

**Comment by deustp01** [comment]
> Do we need 2 terms?

Maybe not, at least for mammals. My recollection is that a single gene product's active site has two sub regions, one that binds glutamine and hydrolyzes it to release ammonium and an adjoining one that immediately captures that ammonium for addition to UTP to form CTP. That second part involves the cleavage of an ATP To form ADP + phosphate but for the same reason that we would not ask for a third separate term to capture the ATP breakdown, we should not need a second one for the glutamine breakdown. @ukemi ? @hdrabkin ?

**Comment by ukemi** [comment]
Your recollection is the same as mine. As long as there are no organisms that directly use the ammonium I guess this is ok. We should be careful about this since IIRC there are other enzymes where there is a distinguishing feature that separetes the MFs into different physiological processes. If we keep the single term, we should probably modify the definition of the current term to use the glutamine and changed the Rhea xref appropriately. The Reactome ones in R-HSA-73647 and R-HSA-504054 are correct (Rhea:26427), but we would use the direction agnostic one (Rhea:26426). 

new def for GO:0003883
Catalysis of the reaction: ATP + UTP + glutamine  + H20= ADP + phosphate + CTP + glutamate + phosphate.   PMID:12354108
xref: Rhea:26426

@deustp01?

**Comment by ukemi** [comment]
Are the two steps accurately reflected in Rhea?
Shouldn''t they be:
ATP + UTP + NH4 = ADP + phosphate + CTP.
glutamine + H20= glutamate + NH4?

Note I incorrectly have two phosphates in the overall reaction above. I'm not sure where the ATP is used, but I think it is the second half.
