### ISSUE TITLE
resolve Rhea mapping for 'linoleoyl-CoA desaturase activity' GO:0016213

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21804]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/e5341f271ed71499fd53de458e05c02b6e91bd417a054601e37871163495e66d.png)

- [(9Z,12Z)-octadecadienoyl-CoA + 2 [Fe(II)-cytochrome b5] + 2 H(+) + O2 = (6Z,9Z,12Z)-octadecatrienoyl-CoA + 2 [Fe(III)-cytochrome b5] + 2 H2O](http://rdf.rhea-db.org/47140) EquivalentTo [EC:1.14.19.3](http://purl.uniprot.org/enzyme/1.14.19.3)	(most probable)	0.75
- [(9Z,12Z,15Z)-octadecatrienoyl-CoA + 2 [Fe(II)-cytochrome b5] + 2 H(+) + O2 = (6Z,9Z,12Z,15Z)-octadecatetraenoyl-CoA + 2 [Fe(III)-cytochrome b5] + 2 H2O](http://rdf.rhea-db.org/47144) ProperSubClassOf [EC:1.14.19.3](http://purl.uniprot.org/enzyme/1.14.19.3)		0.1
- [(9Z,12Z)-octadecadienoyl-CoA + 2 [Fe(II)-cytochrome b5] + 2 H(+) + O2 => (6Z,9Z,12Z)-octadecatrienoyl-CoA + 2 [Fe(III)-cytochrome b5] + 2 H2O](http://rdf.rhea-db.org/47141) EquivalentTo [METACYC:1.14.19.3-RXN](http://metacyc.org/1.14.19.3-RXN)	(most probable)	0.75
- [linoleoyl-CoA desaturase activity](http://purl.obolibrary.org/obo/GO_0016213) EquivalentTo [METACYC:1.14.19.3-RXN](http://metacyc.org/1.14.19.3-RXN)	(most probable)	0.8
- [linoleoyl-CoA desaturase activity](http://purl.obolibrary.org/obo/GO_0016213) EquivalentTo [EC:1.14.19.3](http://purl.uniprot.org/enzyme/1.14.19.3)	(most probable)	0.8
- [linoleoyl-CoA desaturase activity](http://purl.obolibrary.org/obo/GO_0016213) ProperSubClassOf [(9Z,12Z)-octadecadienoyl-CoA + AH2 + O2 = (6Z,9Z,12Z)-octadecatrienoyl-CoA + A + 2 H2O](http://rdf.rhea-db.org/22196)		0.08
- [(9Z,12Z,15Z)-octadecatrienoyl-CoA + 2 [Fe(II)-cytochrome b5] + 2 H(+) + O2 => (6Z,9Z,12Z,15Z)-octadecatetraenoyl-CoA + 2 [Fe(III)-cytochrome b5] + 2 H2O](http://rdf.rhea-db.org/47145) EquivalentTo [METACYC:RXN-13426](http://metacyc.org/RXN-13426)	(most probable)	0.75

**Comment by pgaudet** [comment]
@balhoff I think METACYC:RXN-13426 and METACYC:1.14.19.3-RXN are the same? 
Do you get the MetaCyc xrefs from RHEA or from GO? I cannot find METACYC:RXN-13426 in GO.

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 
Would RHEA consider a grouping reaction for EC:1.14.19.3? 
CHEBI:139565 - octadecadienoyl-CoA(4−) is a common parent to CHEBI:57383 - linoleoyl-CoA(4−) used in RHEA:47140 and CHEBI:74034 - α-linolenoyl-CoA(4−) used in RHEA:47144

**Comment by balhoff** [comment]
> @balhoff I think METACYC:RXN-13426 and METACYC:1.14.19.3-RXN are the same?
> Do you get the MetaCyc xrefs from RHEA or from GO? I cannot find METACYC:RXN-13426 in GO.

@pgaudet MetaCyc xrefs come from both Rhea and GO.

**Comment by pgaudet** [comment]
Then I will direct my question to @amorgat and @kaxelsen 
> I think METACYC:RXN-13426 and METACYC:1.14.19.3-RXN are the same?

**Comment by kaxelsen** [comment]
They are not the same.
METACYC:RXN-13426 has alpha-linolenoyl-CoA (C18:3 = C18 fatty acid with 3 double bonds) as substrate while 
METACYC:1.14.19.3-RXN has linoleoyl-CoA (C18:2 only 2 double bonds) as substrate. 

This is the same reason we cannot group the two reactions, CHEBI:139565 only groups C18:2 fatty acids.

**Comment by pgaudet** [comment]
- [ ] Added RHEA:47144 as a xref. Both RHEA:47144 and RHEA:47140 are narrowMatch. 
- [ ] Fixed definition to "Catalysis of the reaction: (9Z,12Z)-octadecadienoyl-CoA + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = (6Z,9Z,12Z)-octadecatrienoyl-CoA + 2 Fe(III)-[cytochrome b5] + 2 H2O. Can also use a substrate with 3 double bonds (a (9Z,12Z,15Z)-octadecatrienoyl-CoA and add a fourth double bond (a (6Z,9Z,12Z,15Z)-octadecatetraenoyl-CoA)."

Note that RHEA:22196 has been replaced by RHEA:47140, so we can ignore that mapping.

**Comment by alanbridge** [comment]
linoleoyl-CoA desaturase activity is an exact match for https://www.rhea-db.org/rhea/47140 - linoleoyl-CoA is the same as (9Z,12Z)-octadecadienoyl-CoA

https://www.rhea-db.org/rhea/47144 is a different reaction, one which concerns alpha linolenoyl-CoA - i.e. (9Z,12Z,15Z)-octadecatrienoyl-CoA - so not really a narrow match


it will really confuse people if you map both to a GO term for "linoleoyl"

**Comment by pgaudet** [comment]
Hi @alanbridge 

Looking at this once again  - for GO this is the same reaction, ie the enzyme is not specific for one or the other substrate. Of course it can be annotated in two processes, depending on the product generated by the reaction.

**Comment by pgaudet** [comment]
Changed def xref from 2 narrow RHEA to exact EC:1.14.19.3
