### ISSUE TITLE
Taxon constraint: budding cell apical bud growth (GO:0007118)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21811]
Please provide as much information as you can: 

* **GO term ID label:**
budding cell apical bud growth (GO:0007118)

* **Request to add a taxon constraint:**

* * **never in taxon: **

Schizosaccharomycetes
Taxonomy ID: 147554 

* **Supporting evidence if available (e.g PMID):**

fission yeast don't do budding.

**Comment by pgaudet** [comment]
should we not do, only in Saccharomyces?

**Comment by pgaudet** [comment]
Humm, the definition mentions "A form of asexual reproduction, occurring in certain bacteria and fungi (e.g. yeasts) and some primitive animals "

**Comment by ValWood** [comment]
Yeah, I wndered about that but then I thought 'never in' was safer.
You could also add never in metazoa?

**Comment by mah11** [comment]
> should we not do, only in Saccharomyces?

no indeedy - Saccharomyces isn't the only fungal genus with budding (let alone any other kingdoms)
