### ISSUE TITLE
Add xrefs and consider name change to "RNA N1/N6-methyladenosine dioxygenase activity" terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21812]
[Term]
id: GO:1990931
name: RNA N6-methyladenosine dioxygenase activity
namespace: molecular_function
def: "Catalysis of the oxidative demethylation of N6-methyladenosine RNA, with concomitant decarboxylation of 2-oxoglutarate and releases oxidized methyl group on N6-methyladenosine as formaldehyde." [PMID:22002720, PMID:26458103]
is_a: GO:0035515 ! oxidative RNA demethylase activity

=> add xref to https://enzyme.expasy.org/EC/1.14.11.53
=> add xref to https://www.rhea-db.org/rhea/49520
=> maybe change name to "mRNA N(6)-methyladenine demethylase activity" to be more consistent with def and EC?

==

[Term]
id: GO:1990930
name: RNA N1-methyladenosine dioxygenase activity
namespace: molecular_function
def: "Catalysis of the oxidative demethylation of N1-methyladenosine RNA, with concomitant decarboxylation of 2-oxoglutarate and releases oxidized methyl group on N1-methyladenosine as formaldehyde." [PMID:26863196, PMID:26863410]
is_a: GO:0035515 ! oxidative RNA demethylase activity

=> add xref to https://enzyme.expasy.org/EC/1.14.11.54
=> add xref to https://www.rhea-db.org/rhea/49516
=> maybe change term name to "mRNA N(1)-methyladenine demethylase activity" to be more consistent with def and EC?

**Comment by pgaudet** [comment]
> => maybe change name to "mRNA N(6)-methyladenine demethylase activity" to be more consistent with def and EC?

EC (and the GO def) mention methyladenosine, not methyladenine
I added 'mRNA N(6)-methyladenine demethylase' (EC enzyme name) as an EXACT synonym

**Comment by sjm41** [comment]
Thanks @pgaudet 
I don't think I'd noticed the "methyladenosine" vs "methyladenine" difference....
My main suggestion wrt both names was to (i) use 'mRNA' instead of 'RNA', and (ii) use "demethylase" instead of "dioxygenase"
Sorry not to be clearer!
