### ISSUE TITLE
Allow 2 Rhea if they have source = skos:broadMatch

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21814]
Hi @balhoff 

1. We should be able to use the same Rhea in two different terms, if they are broadMatch
2. One term should be allowed more than 1 RHEA, but only 1 exactMatch

Can you fix the check ? 

(note to self: I will be able to add the same Rhea to the ABC-type sodium transporter activity term in #21796)

**Comment by balhoff** [comment]
@pgaudet you can give it a try now.

**Comment by pgaudet** [comment]
Thanks @balhoff !
