### ISSUE TITLE
NTR: [general amino acid control response]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21824]
Please provide as much information as you can: 

* **Suggested term label:**

I would like to use the term to describe the "general amino acid control response"

This term exists:
https://www.ebi.ac.uk/QuickGO/term/GO:0034198
GO:0034198    cellular response to amino acid starvation

with
GAAC response | narrow
general amino acid control response | narrow

I wonder if general amino acid control response is always what we mean here? Could it be anything else?
Maybe the existing term could be repurposed?

**Comment by ValWood** [comment]
Actually, GAAC pathway is a signalling pathway so we would need a more specific term


A signalling pathway that senses as deprivation of amino acids.
I will provide  better def and ref later today.

**Comment by ValWood** [comment]
Actually didn't @sylvainpoux  request  a term for this recently?
I can't find it...

**Comment by ValWood** [comment]
Thid is the ticket I was thinking of.
The term I want  is equivalent to 
+name: GCN2-mediated signaling

I will request a bit more specificity for this signalling (to capture that it is in response to amino acid starvation) and add the correct parentage.

**Comment by sylvainpoux** [comment]
Hi Val,
it is related to the Integrated Stress response (https://www.ebi.ac.uk/QuickGO/term/GO:0140467)
GCN2 should probably be a child of GO:0140467 
Sylvain

**Comment by ValWood** [comment]
Yes it already is
https://www.ebi.ac.uk/QuickGO/term/GO:0140469

So I guess the question is, should the def of 
GO:0140469   GCN2-mediated signaling
A series of reactions in which a signal is passed on to downstream proteins within the cell via GCN2 (also known as EIF2AK4), an intracellular protein kinase that is activated by stress signals, such as amino acid starvation. PMID:27629041

be made more specific?
GCN2-mediated signaling is in response to amino acid starvation, but is it also other stresses?

Otherwise it could be 
"an intracellular protein kinase that is activated by amino acid starvation"

and   add the parent GO:0034198 cellular response to amino acid starvation

move the synonyms  from GO:0034198  to GO:0140469 
GAAC response
general amino acid control response 
 (not sure what sort yet)

Juan Mata @juanmatacambridge  PomBase PI has worked on general amino acid control response  so I will add this tot he agenda for our next group meeting.

**Comment by ValWood** [comment]
mailed 2 experts, as I need to open tickets about some other terms in this area for an in progress paper.

**Comment by ValWood** [comment]
I think we can close this one. 
GAAC is not much used and proba bly works OK as a narrow synonym of 
GO:0034198 cellular response to amino acid starvation
