### ISSUE TITLE
contractile ring maintenance 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21834]
contractile ring maintenance 
mitotic contractile ring  maintenance 

This term  was coined historically to describe the period of contractile ring organization between assembly and constriction. More recently people refer to process as "maturation":

From Kathy Gould https://lab.vanderbilt.edu/gould-lab/
People have switched to maturation because it has been found that some proteins join the CR later than others so that the structure "matures" and then it constricts.

Could we repurpose the existing term, or would obsoletion and reinstantiation be preferred here?
Only has 24 EXP annotation

Any objections?

PomBase 15 
FlyBase 4 @hattrill 
Dictybase 2 @pfey03 
SGD 2 @srengel 
Cacao 1

**Comment by ValWood** [comment]
Papers from prominent cytokinesis groups using maturation.
PMID: 34133210
PMID: 25451933
PMID: 22119525 
PMID: 19225152

**Comment by pfey03** [comment]
@ValWood These were wrongly annotated anyway, I re-annotated our 2 though an exact term is not available..
Thanks!

**Comment by krchristie** [comment]
Hi @ValWood - From what you've written here, it seems that this is a shift in the nomenclature used in the literature, rather than a completely different thing. If I'm understanding that correctly, I think we could probably rename the term.

However, it's also worth noting that there are several terms we need to consider. The term you mention `contractile ring maintenance` has 2 child terms:

-- `contractile ring maintenance`
--- `actomyosin contractile ring maintenance`
---- `mitotic actomyosin contractile ring maintenance`

Plus there is a regulation term for one of the basic terms:
`regulation of mitotic actomyosin contractile ring maintenance`

There's also this term:
`maintenance of actomyosin contractile ring localization`
which is **'part of' some 'actomyosin contractile ring maintenance'**

Did you look for annotations to any of the other terms?

**Comment by ValWood** [comment]
I looked at all of the annotations (they are inherited).
All annotations should be to the mitotic term because as far as I know all of the studies are mitotic cytokinesis (and at least in yeast the process is necessarily different for cell separation during sporulation).

The non actomyosin parentage is to take care of plants, or some species where the rings are not actomyosin but the. grouping term (contractile ring maintenance)  might not even be required.

All annotations are to :
mitotic actomyosin contractile ring maintenance

except 
a) the 2 dictlybase, petra has reannotated
b) Fly scraps and vibrator 
maintenance of actomyosin contractile ring localization
actomyosin contractile ring maintenance
respectively.

I suspect   actomyosin contractile ring maintenance-> mitotic  actomyosin contractile ring maintenance

I am not sure about 
**maintenance of actomyosin contractile ring localization**
This sounds like a phenotype. The ring does not move after it is positioned *except* in mutants, where it can slide about.  This term  could probably be obsoleted? @hattrill 
It only has the single annotation.

**Comment by ValWood** [comment]
RIght, scraps is anillin, which is the pombe Mid1 ortholog ( Division Mal Foutue- literally Badly  fucked division). I have  this annotated to 
"establishment of mitotic actomyosin contractile ring localization" 
phenotypes include 
actomyosin contractile ring displaced from midpoint

This might be a better term for 'scraps' although I also have an outstanding ticket to disambiguate
this term and "cytokinesis, site selection".
https://github.com/geneontology/go-ontology/issues/16879

Suggested actions here. 
Rename
-- contractile ring maintenance
--- actomyosin contractile ring maintenance
---- mitotic actomyosin contractile ring maintenance
regulation of mitotic actomyosin contractile ring maintenance

Obsolete
maintenance of actomyosin contractile ring localization

Reannotate scraps to "cytokinesis, site selection" or "establishment of actomyosin contractile ring localization"

Deal with https://github.com/geneontology/go-ontology/issues/16879  separately

**Comment by krchristie** [comment]
> I am not sure about
> **maintenance of actomyosin contractile ring localization**
> This sounds like a phenotype. The ring does not move after it is positioned _except_ in mutants, where it can slide about. This term could probably be obsoleted? @hattrill
> It only has the single annotation.

I had similar thoughts about this term.

Thanks for all the analysis @ValWood, especially the clear listing of suggested actions in your last comment.

**Comment by hattrill** [comment]
Happy with changing those annotations - papers more like assembly/organisation/maturation processes. Just have to look more closely to decide which terms best describe it.

**Comment by hattrill** [comment]
Reannotated 'scraps' to "establishment of actomyosin contractile ring localization" as suggested by Val.
Leaning toward cleavage furrow ingression for vibrator.

**Comment by ValWood** [comment]
> Leaning toward cleavage furrow ingression for vibrator.

That would fit. Lipin has never show up for yeast in any cytokinesis screen, but is known to be involved in other membrane processes (ER and nuclear membrane), so  a role in membrane invagination makes total sense.

**Comment by ValWood** [comment]
Action,
rename "contractile ring maintenance" terms to 
"contractile ring maturation" to reflect shift in nomenclature.

**Comment by ValWood** [comment]
I also propose to massage the definition

From
The process in which the contractile ring is maintained, typically in response to an internal or external cue.
To
The process by which the cytokinetic ring attains its fully functional state.

This better reflects the process and current knowledge (the ring doesn't just appear fully formed  during this period)

Let me know if this seems OK, and I will implement next week.

**Comment by srengel** [comment]
this all seems fine to me (name and def changes). i have updated the 2 SGD annotations just now from the maintenance terms to the contraction terms, based on discussion in this ticket.

**Comment by hattrill** [comment]
good for me.

**Comment by ValWood** [comment]
I will open a new ticket for the final obsoleteions.
There are only 3 annotations  to the terms I plan to obsolete and all will have direct replacements
