### ISSUE TITLE
NTR: [NuRD complex binding]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#21845]
Please provide as much information as you can: 

* **Suggested term label:**
NuRD complex binding

* **Definition (free text)**
Binding to a NuRD complex.

* **Reference, in format PMID:#######**
PMID:25150861

* **Parent term(s)**
GO:0044877 protein-containing complex binding

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
PubMed=25150861 shows that ZNF827 interacts with the NuRD complex and is recruits it to telomeric regions. (fig 2)

**Comment by krchristie** [comment]
@pgaudet - Are we adding new binding terms for specific types of complexes? If needed, we can discuss at the next ontology editors call.

**Comment by pgaudet** [comment]
Yes let's add this.
