### ISSUE TITLE
carboxylic ester hydrolase activity (GO:0052689) / EC:3.1.1.- & EC:3.1.1.1 xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21843]
@balhoff @hdrabkin 

Looks like the EC xref on carboxylic ester hydrolase activity (GO:0052689) recently got changed from EC:3.1.1.- to EC:3.1.1.1 (maybe as part of #21287 ?).

https://enzyme.expasy.org/EC/3.1.1.- is the grouping term for "Carboxylic ester hydrolases" whereas https://enzyme.expasy.org/EC/3.1.1.1 is the specific term for "Carboxylesterase" (def:A carboxylic ester + H(2)O <=> an alcohol + a carboxylate) - which maps to RHEA:21164.

I'm not entirely sure of the practical difference between EC:3.1.1.- and EC:3.1.1.1, but since GO:0052689 is the equivalent grouping term to EC:3.1.1.-, it seems it should have the EC:3.1.1.- xref??

**Comment by sjm41** [comment]
@kaxelsen Can we also get your take on this one? Thanks.

**Comment by kaxelsen** [comment]
EC 3.1.1 is the sub-subclass of "Carboxylic ester hydrolases" that covers all the specific enzymes described in EC 3.1.1.1-3.1.1.117. EC 3.1.1.1 only covers the specific enzyme carboxylesterase (in this case an enzyme with a very broad substrate specificity). So if GO:0052689 is a 'grouping term', I would link it to EC 3.1.1.-.

Regarding the list:
id: GO:0080030: I would use EC 3.1.1.-. As a note I can add that there is no reaction in Rhea that corresponds MetaCyc:RXN-10711, 
All the other GO terms use EC 3.1.1.- correctly except for 
GO:0052768 that belongs to EC 3.2.1.-

**Comment by sjm41** [comment]
Thanks @kaxelsen

Good that we agree that the xref on GO:0052689 should be reverted to EC:3.1.1.-.

Wrt the list in my second comment, my understanding is that the GO should only have 'grouping type' EC numbers as xrefs on 'grouping type' GO terms (so EC:3.1.1.- on GO:0052689 is correct). If there's a more specific GO child term that lacks an equivalent EC number, then that GO term should have no EC xref rather than having the grouping EC xref.  That's right, isn't it @hdrabkin ?

**Comment by hdrabkin** [comment]
The 3 digit ECs should only be used for the GO terms that correspond to that EC. 
We have many records still left from the plant /metacyc requests where they were uploaded in bulk before seeing that the EC was uses as a def ref. 

As for this example (which did not come from the above project)

xref: id: GO:0052767
name: mannosyl-oligosaccharide 1,6-alpha-mannosidase activity
def: "Catalysis of the hydrolysis of the alpha-(1->6) bonds of alpha-D-mannose residues in mannosyl-oligosaccharide." [GOC:mengo_curators, PMID:1849817, PMID:2338081]
xref: EC:3.1.1.-   <<<<<< no; this is an enzyme class ( Hydrolases Acting on ester bonds. Carboxylic ester hydrolases. ) and the GO term for that  could be used as a parent (GO:0052767 is a type of EC:3.1.1.-
I can't seem to find EC:3.1.1.- as a grouping term in GO at the moment.

**Comment by sjm41** [comment]
_I can't seem to find EC:3.1.1.- as a grouping term in GO at the moment._

Right, EC:3.1.1.- used to be the xref on carboxylic ester hydrolase activity (GO:0052689), but it recently got changed from EC:3.1.1.- to EC:3.1.1.1 
The change should be reverted!

**Comment by hdrabkin** [comment]
Ah, this seems to be a problem with nomenclature?  EC:3.1.1.1 refers specifically to the enzyme ' carboxylesterase'.  
In this case, the actual enzyme has a 'specificity' as broad as it's parent 3.1.1.-
If the term is used in annotations, it may be referring specifically to that enzyme
There are 1080 exp annotations to  GO:0052689, and looking quickly, yes they catalyze the hydrolysis of a carboxyl-ester.

**Comment by sjm41** [comment]
Ah, so you're saying that while the EC differentiates between the EC:3.1.1.- grouping class and the the specific EC:3.1.1.1 enzyme, the GO just has GO:0052689 - which is used as BOTH a grouping term and to annotate specific activities (1080 exp annotations).

OK, I see the issue better now.

Given that GO:0052689 is used as BOTH a grouping term and a specific activity term, should it have both EC:3.1.1.- and EC:3.1.1.1 as xrefs?

**Comment by hdrabkin** [comment]
OR, a new grouping term to correspond to EC:3.1.1.- which would be a parent of GO:0052689 ; The grouping term should have a specific 'do not annotate' flay, the GO:0052689 would get a comment of some sort to indicate that it should be used specifically to annotate a enzyme with very broad specificity. 
RHEA:21164 is also very genetic too. really ANY kind of carboxylic ester ; 
RHEA has 130 reactions using EC:3.1.1.n (note, not -) including EC:3.1.1.1
 I'm more inclined to make a separate grouping term (that does not get a rhea).

**Comment by sjm41** [comment]
_I'm more inclined to make a separate grouping term (that does not get a rhea)._
That works for me!
If you did that, I guess all current children of GO:0052689 would get moved to be children of the new grouping term?

**Comment by hdrabkin** [comment]
There's a lot of them!

**Comment by alanbridge** [comment]
Hi Kristian, noticed a typo in first ID, should be RHEA:32919. All the best, Alan

**Comment by kaxelsen** [comment]
Thank you very much, it has been corrected!

**Comment by hdrabkin** [comment]
the EC: def for 3.1.1.1 is 'a carboxylic ester + H2O <=> a carboxylate + an alcohol + H(+)" which pretty much sounds like a grouping term. 
EC: 3.1.1.- is 'Catalysis of the hydrolysis of a carboxylic ester bond, or 'Hydrolases
 Acting on ester bonds and Carboxylic ester hydrolases

**Comment by hdrabkin** [comment]
After discussion, I will make new term for 3.1.1.1, and remove 3.1.1.1 from GO:0052689 ; transfer the synonyms where we are sure; remove other synonyms from GO:0052689 .
Then look at annotations to GO:0052689 to see which ones can be transfered to the new term (annotation ticket?).

**Comment by hdrabkin** [comment]
NTR
id: GO:0106435
name: carboxylesterase activity
def: Catalysis of the reaction: a carboxylic ester + H2O = a carboxylate + an alcohol + H(+).
is_a: GO:0052689


Clean up: should goslim annotation to GO:0052689 be transferred to new term? (@sjm4)
Disposition of all REACTOME xefs in GO:0052689  (@deustp01

**Comment by sjm41** [comment]
Hi @hdrabkin Thanks for returning to this issue.  The fix looks good to me.

_Clean up: should goslim annotation to GO:0052689 be transferred to new term? (@SJM4)_
Not sure...  But my feeling is it would be safer (and still accurate) to keep it on the parent term.

**Comment by hdrabkin** [comment]
Finished
