### ISSUE TITLE
NTR: protein targeting to chloroplast thylakoid  membrane

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#21848]
Please provide as much information as you can: 

* **Suggested term label:**
protein targeting to chloroplast thylakoid  membrane

* **Definition (free text)**
The process of directing proteins towards a chloroplast thylakoid membrane, usually using signals contained within the protein.

* **Reference, in format PMID:#######**

34021351

* **Parent term(s)**
instance of GO:0006612 protein targeting to membrane
part of: GO:0010027 thylakoid membrane organization

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Would this existing term suffice?

GO:0045038 protein import into chloroplast thylakoid membrane DEF: "The import of proteins into the chloroplast thylakoid membranes. Proteins that are destined for the thylakoid lumen require two uptake-targeting sequences: the first targets the protein to the stroma, and the second targets the protein from the stroma to the thylakoid lumen. Four separate thylakoid-import systems deal with the proteins once they are in the stroma."

**Comment by lreiser** [comment]
Probably - the protein in question seems to act in the latter (stroma to thylakoid)...
lemme look at the parent terms..
- protein import : The targeting and directed movement of proteins into a cell or organelle. Not all import involves an initial targeting event
- protein targeting: the process of targeting specific proteins to particular regions of the cell, typically membrane-bounded subcellular organelles. Usually requires an organelle specific protein sequence motif.


and then  checking the the relationships. has the same protein targeting parent- I guess i must have missed it in my searching the ontology

**Comment by raymond91125** [comment]
@lreiser If GO:0045038 works for you. Please close the ticket. Thanks.
