### ISSUE TITLE
missing parent   vesicle-mediated transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21846]
endomembrane system is defined
A collection of membranous structures involved in transport within the cell. The main components of the endomembrane system are endoplasmic reticulum, Golgi bodies, vesicles, cell membrane and nuclear envelope. Members of the endomembrane system pass materials through each other or though the use of vesicles.

In this case shouldn't

GO:0016192    vesicle-mediated transport
Definition (GO:0016192)
A cellular transport process in which transported substances are moved in membrane-bounded vesicles; transported substances are enclosed in the vesicle lumen or located in the vesicle membrane. The process begins with a step that directs a substance to the forming vesicle, and includes vesicle budding and coating. Vesicles are then targeted to, and fuse with, an acceptor membrane.

be a descendant of
GO:0010256   endomembrane system organization

(This will make a big change to the inferences, but shouldn't the reasoner pick up  things like this?)

**Comment by deustp01** [comment]
Where do lysosomes and phagosomes fit into this scheme?

**Comment by ValWood** [comment]
Good point.

Maybe only the ER through to PM e.g.
GO:0098876    vesicle-mediated transport to the plasma membrane
GO:0006888    endoplasmic reticulum to Golgi vesicle-mediated transport
etc....

**Comment by pgaudet** [comment]
Not sure what you mean - GO:0016192 vesicle-mediated transport is sometimes just transporting cargo, do you propose to consider any movement of a vesicle to be 'organization'?

**Comment by ValWood** [comment]
Let's close. I think there are issues here.... there are some parts  of vesicle-mediated ransport described as 'organization' and some not, but this is for another time. the entire branch is  quite messy. There are many tickets about this...
