### ISSUE TITLE
NTR: [lipid ubiquitination]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#21857]
Hi GO,

a very nice paper is showing that ubiquitination not only takes place on proteins, but also on lipids (PMID:34012115). 

For the moment we only know that ubiquitination takes place on the the lipid A moiety of lipopolysaccharide and we have no detail regarding the precise linkage and I cannot submit any catalytic reaction (Rhea)

I would need two new terms "lipid modification by small protein conjugation" and " lipid ubiquitination"

Thanks

Sylvain

1) 
**Suggested term label:**
lipid modification by small protein conjugation
**Definition:**
A lipid modification process in which one or more groups of a small protein, such as ubiquitin or a ubiquitin-like protein, are covalently attached to a target lipid. 
**Reference:**
PMID:34012115
**Parent term(s):**
GO:0030258 lipid modification

2)
**Suggested term label:**
 lipid ubiquitination
**Definition:**
The process in which one or more ubiquitin groups are added to a lipid. 
**Reference:**
PMID:34012115
**Parent term(s):**
GO:XXXXXX lipid protein modification by small protein conjugation

**Comment by krchristie** [comment]
@sylvainpoux - Thanks for your excellently organized and complete term requests, as usual. I've put these in today.
