### ISSUE TITLE
synonym scope of  pathogenesis in GO

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21856]
GO:0001907    killing by symbiont of host cells

has synonym 
pathogenesis | narrow

This should be related because pathogenesis is not a process it's a phenotype (or trait, or disease outcome or something else)  but definitely  orthogonal to any GO process.

Also check synonym scope of used elsewhere....

**Comment by krchristie** [comment]
It's a narrow synonym of 6 terms. I'll make it related everywhere.
