### ISSUE TITLE
Missing parent in mitotic spindle elongation terms.

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21850]
GO:0061804 mitotic spindle formation (spindle phase one)
 is part_of "GO:0000022   mitotic spindle elongation"
which is part of "GO:0000070 mitotic sister chromatid segregation"

However, annotations to 
"positive regulation of mitotic spindle formation (spindle phase one)" 
annotations do not slim to  "mitotic sister chromatid segregation"
because of the new behaviour inferring over the regulates relation.

The fix for this  is to add the missing  part_of  (or is_a?) relationships between

"regulation of mitotic spindle formation (spindle phase one)" 
and
GO:0032888   regulation of mitotic spindle elongation

and another  between
regulation  of mitotic spindle elongation 
and
regulation of  "mitotic sister chromatid segregation"

to mirror the relationships between the non-regulation terms.

Shouldn't the reasoner identify these missing relations?

<img width="569" alt="Screenshot 2021-07-15 at 14 02 18" src="https://user-images.githubusercontent.com/7359272/125792557-179b7deb-da04-4bc0-b730-ebb2682cb3fc.png">

**Comment by pgaudet** [comment]
> Shouldn't the reasoner identify these missing relations?

Well, it uses the rules we provide, and since regulates o part_of is not transitive, I think it's expected that these are not found.
