### ISSUE TITLE
add "ring constriction" synonyms for "ring contraction" (or even rename?)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21855]
Please could we add the exact synonyms "constriction" for all 
GO:0000916    actomyosin contractile ring contraction
terms.

Currently, 
GO:0000916    actomyosin contractile ring contraction
has synonym contractile ring constriction | broad

but this should be an exact synonym of  the parent term
GO:0036213    contractile ring contraction
- unless I am unaware of some plant-specific cytokinesis stuff, in which case maybe it should be related -but either way -

GO:0000916    actomyosin contractile ring contraction
should have EXACT synonym  actomyosin contractile ring constriction.

In fission yeast increasingly constriction is used in preference to contraction.

Based on this, https://www.differencebetween.com/difference-between-contraction-and-constriction/
 constriction seems more accurate to describe  actinomyosin ring closure.

**Comment by krchristie** [comment]
I'm quite happy to add all of these as EXACT synonyms. I'm not aware of any contraction occurring in plant cells either, and some quick Google searches only turned up the expected results that plant cells divide by cell wall plate construction.

Regarding the name change option, I think that the results of my PubMed searches do not support changing the names at this time.

PubMed search   string | # results
-- | --
Contraction terms | -
   actomyosin ring contraction | 241
   actomyosin contractile ring contraction | 123
   contractile ring contraction | 2409
Total | 2773
Constriction terms | -
actomyosin ring constriction | 188
actomyosin contractile ring constriction | 114
contractile ring constriction | 358
Total | 660
