### ISSUE TITLE
NTR: isoprenoid diphosphate phosphatase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#21866]
Dear GO editors,
PubMed=20110354 shows that UniProtKB/Q8IY26 catalyzes the dephosphorylation of presqualene diphosphate and the isoprenoid diphosphates :  geranyl diphosphate, geranylgeranyl diphosphate and farnesyl diphosphate that are  involved in cholesterol biosynthesis and protein prenylation. Could we create terms for these activities?

For presqualene diphosphate the reaction is (not yet public):

Reaction=H2O + presqualene diphosphate = H(+) + phosphate + presqualene monophosphate [Rhea:67968]

For farnesyl diphosphate the reaction is :

Reaction=(2E,6E)-farnesyl diphosphate + H2O = (2E,6E)-farnesyl phosphate + H(+) + phosphate [Rhea:48128]

For geranyl diphosphate the reaction is :

Reaction=(2E)-geranyl diphosphate + H2O = (2E)-geranyl phosphate + H(+) + phosphate [Rhea:47944]

Thank you for your help.
Lionel

**Comment by hdrabkin** [comment]
Hi @ibreuza 
Can you note a suggested parent. 
@pgaudet do we want to go with something more generic for the farnesyl and geranyl, as they differ by one unit or should I go ahead?

**Comment by pgaudet** [comment]
I was trying to get a more general compound here: https://github.com/geneontology/go-ontology/issues/16475
but I did not manage, or we would not have RHEA links. What do you think?

**Comment by hdrabkin** [comment]
If we don't have the rhea links then the terms are of no use;

**Comment by hdrabkin** [comment]
would 'isoprenoid diphosphate phosphatase activity' fit all of the above? Then I could make just that one, without the substrate specific reactions as children

**Comment by pgaudet** [comment]
@lbreuza 

I think this was a question for you 
> would 'isoprenoid diphosphate phosphatase activity' fit all of the above? Then I could make just that one, without the substrate specific reactions as children

Thanks, Pascale

**Comment by lbreuza** [comment]
> would 'isoprenoid diphosphate phosphatase activity' fit all of the above?

The enzyme can dephosphorylate (sequentially) diphosphate and monophosphate. I believe that a better parent term would therefore be:
"isoprenoid phosphatase activity"

**Comment by lbreuza** [comment]
> 
> 
> If we don't have the rhea links then the terms are of no use;

Here are the reactions from Rhea. Unfortunately some are not yet public but will be made public soon.
Reaction=H2O + presqualene diphosphate = H(+) + phosphate + presqualene monophosphate [Rhea:67968]
Reaction=H2O + presqualene monophosphate = phosphate + presqualene alcohol [Rhea:68024]
Reaction=(2E)-geranyl diphosphate + H2O = (2E)-geranyl phosphate + H(+) + phosphate [Rhea:47944]
Reaction=(2E)-geranyl phosphate + H2O = (2E)-geraniol + phosphate [Rhea:68020]
Reaction=(2E,6E,10E)-geranylgeranyl diphosphate + H2O = (2E,6E,10E)-geranylgeranyl phosphate + H(+) + phosphate [Rhea:68008]
Reaction=(2E,6E,10E)-geranylgeranyl phosphate + H2O = (2E,6E,10E)-geranylgeraniol + phosphate [Rhea:68016]
Reaction=(2E,6E)-farnesyl diphosphate + H2O = (2E,6E)-farnesyl phosphate + H(+) + phosphate [Rhea:48128]
Reaction=(2E,6E)-farnesyl phosphate + H2O = (2E,6E)-farnesol + phosphate [Rhea:48132]

**Comment by lbreuza** [comment]
> 
> 
> Then I could make just that one, without the substrate specific reactions as children

It is unclear to me why we can have GO terms for BP that are compound-specific "farnesyl diphosphate metabolic process

**Comment by pgaudet** [comment]
Hi @lbreuza 

GO aims to captures MFs that corresponds to the level of specificity of the enzyme, not for each substrate. In this case - does it correspond to one class of enzymes that has wide substrate specificity? 

For BPs, we aim to capture processes that are biologically relevant. For example the paper you cite mentions 'interconversion of isoprenols and isoprenoid phosphates', at which level do you think conversion of one compound into another is interesting as a GO class? Ideally GO would group functions/processes, if we go in too much detail that doesn't address this goal. 

I hope this is clear? Please let me know if it isn't. 

Thanks, Pascale

**Comment by lbreuza** [comment]
> would 'isoprenoid diphosphate phosphatase activity' fit all of the above? Then I could make just that one, without the substrate specific reactions as children

I probably inadvertently closed that ticket. The suggestion of @hdrabkin would fit to the specificity of that protein.

**Comment by hdrabkin** [comment]
Trying to close:
Term: isoprenoid diphosphate phosphatase activity
Def:Catalysis of  the dephosphorylation of isoprenoid diphosphates
Parent: isoprenoid phosphatase activity   <<<<< would need to be added as child of GO:0016462?
Def ref: PMID:33246356 

And I could add the RHEA s(when available) as narrow xrefs

**Comment by lbreuza** [comment]
Sounds good to me.
Thank you.

**Comment by lbreuza** [comment]
Just updated my annotations...Thanks.
I am closing the ticket
