### ISSUE TITLE
NTR ATP-dependent DNA (cytosine-5-)-methyltransferase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#21872]
Hello, I'd like to request
ATP-dependent DNA (cytosine-5-)-methyltransferase activity

child of
GO:0008094 ATP-dependent activity, acting on DNA
GO:0003886 DNA (cytosine-5-)-methyltransferase activity

refs: 32437639, 31955845

**Comment by pgaudet** [comment]
Hi Antonia, 

I see that there is a ATPase domain in the protein, but I dont see that the ATPase activity is needed for the methyltransferase activity - did I miss some data? 

I just want to make sure we dont create a term like for the 'annealing activity', which contains a helicase-like domain but does not hydrolyze ATP  - see #21614 

Thanks, Pascale

**Comment by Antonialock** [comment]
I think that is what is shown in 32437639 ? 


eg 

**Dnmt5 ATP hydrolysis is stimulated by hemimethylated substrates and necessary for methyltransferase activity**
.....our present results demonstrate that SNF2-mediated ATP hydrolysis by Dnmt5 is strictly required for its DNA methyltransferase activity........even in non-nucleosomal contexts.


.....What, then, is the purpose of ATP hydrolysis by Dnmt5, an expenditure of energy not fundamentally required for the transfer of a methyl group from SAM to cytosine?
Several lines of evidence suggest that the conformation the SNF2 ATPase of Dnmt5 is coupled to the detection of preferred DNA substrates by its DNMT domain. First, the catalytic parameters of SNF2-mediated ATP hydrolysis are significantly different in the presence of different DNA substrates


from discussion:
Together, these results highlight an interdomain communication within Dnmt5 that is critically required for DNMT activity. Although structural information will ultimately be required to fully understand the basis of the coupling, a simple interpretation is that protein allostery plays a major role (as opposed to interdomain communication transmitted through conformational change of the DNA substrate itself). This conclusion is supported by our finding that very subtle manipulations of the mCG/CG target site are sufficient to modulate SNF2 ATPase activity throughout its full dynamic range (e.g., Figure 4C, S4D), whereas changes in DNA substrate length, sequence, and CG site number/location have minimal effect. Furthermore, a Dnmt5 fragment consisting of only the SNF2 domain does not exhibit DNA-stimulated ATP hydrolysis, nor does it bind DNA under conditions in which the DNMT domain readily does (Figure S4E–G). A second important question for future study is to more precisely define each aspect of DNMT domain conformational change—from cytosine flipping and pre-catalytic rearrangements to methyltransfer and product release—that stimulates (or requires) ATPase activity.

**Comment by Antonialock** [comment]
Also fig 2c has kcat and km data for ATPase activity

**Comment by pgaudet** [comment]
Great, thanks for confirming!

**Comment by kaxelsen** [comment]
@hdrabkin 
We have now created a reaction in Rhea to cover this activity. It is
RHEA:68984 a 2'-deoxycytidine in DNA + ATP + H2O + S-adenosyl-L-methionine = a 5-methyl-2'-deoxycytidine in DNA + ADP + 2 H+ + phosphate + S-adenosyl-L-homocysteine

It should become public in release 2022_01 scheduled for Januar 19, 2022
