### ISSUE TITLE
subarachnoid space development should not be part of brain development

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#21883]
![image](https://user-images.githubusercontent.com/112839/127551466-a7a535cf-912a-4f2e-9b3b-3e2176c8f45c.png)

The subarachnoid space is part of brain and spinal cord

![image](https://user-images.githubusercontent.com/112839/127551512-04b5d9a8-0660-4d77-9659-7449f49d1c4d.png)

https://en.wikipedia.org/wiki/Meninges#Subarachnoid_space

Should therefore be part_of central nervous system development, not brain development

Related issue: https://github.com/obophenotype/uberon/issues/2006

(Broader issue:  A design pattern for x development with GCIs could infer the correct partonomy for development terms from Uberon)

**Comment by pgaudet** [comment]
> (Broader issue: A design pattern for x development with GCIs could infer the correct partonomy for development terms from Uberon)

Right ! Unfortunately this will not be done imminently, so it's good to correct inconsistencies as we encounter them. 

Thanks, Pascale
