### ISSUE TITLE
Change label GO:0097351 toxin-antitoxin pair type II binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21884]
GO:0097351 toxin-antitoxin pair type II binding is defined as "Binding to a toxic protein, disabling its function. There may be more than one antitoxin to a toxic protein. Instances of this activity are known only in prokaryotes, where the toxic protein may be a ribonuclease, a DNA gyrase, or other." @federicaquaglia and the DisProt group requested a term to represent "toxin sequestering activity", which is a better label for this function, and would classify this as a sequestering activity, rather than just a binding function. 

I will change the term label for GO:0097351

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, add PMID:24806488 as a cross reference.

**Comment by pgaudet** [comment]
Are the toxin always proteins in this system @federicaquaglia @genegodbold ? If not I will adjust the definition as well. 

Thanks, Pascale

**Comment by federicaquaglia** [comment]
As far as it concerns DisProt yes, the toxins and antitoxins we annotate are proteins with intrinsically disordered regions
