### ISSUE TITLE
missing parent  ATP-dependent chromatin remodeler activity (GO:0140658)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21886]
Shouldn't 
 ATP-dependent chromatin remodeler activity (GO:0140658)
be a decendant of 
GO:0015616    DNA translocase activity ?

@colinlog

**Comment by pgaudet** [comment]
Why do you say a remodeler is always a translocase? 
ping @colinlog

**Comment by ValWood** [comment]
I think both remodellers and helicases are always translocases + lots of other things. Another option  is to get rid of DNA translocase?

**Comment by ValWood** [comment]
Ah right the way "DNA translocase is defined" the remodelers aren't translocases. I thought all this class were classed as translocases but maybe not. Closing...
