### ISSUE TITLE
NTR: dihydropyrimidine dehydrogenase (NAD+) complex

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#21891]
Please provide as much information as you can: 

* **Suggested term label:**
dihydropyrimidine dehydrogenase (NAD+) complex

* **Definition (free text)**
A heteromultimeric complex containing the PreA and PreT subunits; reversibly catalyzes EC 1.3.1.1

* **Reference, in format PMID:#######**
PMID: 21169495, PMID: 34097066

* **Gene product name and ID to be annotated to this term**
PreA, UniProt P25889, EcoCyc EG11289-MONOMER
PreT, UniProt P76440, EcoCyc G7145-MONOMER

* **Parent term(s)**
GO:1902494

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
EC 1.3.1.1
EcoCyc CPLX0-7788

* **Any other information**

**Comment by pgaudet** [comment]
- EC should be on the appropriate function, not on the CC term. 
- Definition should be along these lines:
- A heteromultimeric complex capable of xx reaction; in E. coli, composed of PreA and PreT.

**Comment by pgaudet** [comment]
This enzyme is capable of GO:0004159; labelled as 'dihydrouracil dehydrogenase (NAD+) activity' - however it catalyzes both: 
-  5,6-dihydrouracil + NAD(+) <=> uracil + NADH
 - 5,6-dihydrothymine + NAD(+) <=> thymine + NADH
so I will change label to 'dihydropyrimidine dehydrogenase (NAD+) activity, and add RHEA as NARROW xref, and EC as EXACT xref.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140690
+name: dihydropyrimidine dehydrogenase (NAD+) complex
+namespace: cellular_component
+def: "A heteromultimeric complex capable of dihydropyrimidine dehydrogenase (NAD+); in E. coli, composed of PreA and PreT." [PMID:21169495, PMID:34097066]
+xref: MetaCyc:CPLX0-7788
+is_a: GO:0032991 ! protein-containing complex
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: capable_of GO:0004159 ! dihydropyrimidine dehydrogenase (NAD+) activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21891 xsd:anyURI
+created_by: pg
+creation_date: 2021-08-04T05:52:44Z

**Comment by pgaudet** [comment]
Also - add taxon constraints on these terms: 

- [ ] GO:0140690 dihydropyrimidine dehydrogenase (NAD+) complex 
- [ ] GO:0004159 dihydropyrimidine dehydrogenase (NAD+) activity
-> only in bacteria

- [ ]  GO:0017113 dihydropyrimidine dehydrogenase (NADP+) activity 
-> only in eukaryotes, according to the species distribution of PTHR43073
