### ISSUE TITLE
NTR: procyclogenesis

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21898]
Accession: GO:xxxxxx
Name: procyclogenesis
Ontology: biological_process
Definition: The morphological, biochemical and genetic changes that induce the differentiation of bloodstream form trypomastigotes into procyclic trypomastigotes in some of the Trypanosomatidae species such as Trypanosoma brucei. This process occurs inside the midgut of the tsetse fly vectors in T. brucei.
is_a: GO:0044114 ! development of symbiont in host
[RO:0002224 relation] starts with : OPL:0000022 ! bloodstream trypomastigote stage
[RO:0002230 relation] ends with : OPL:0000076 ! procyclic trypomastigote stage
Taxonomic restriction: NCBITaxon:5654 ## Trypanosomatidae
Source: PMID:1698624, PMID:3194362, PMID:3194363, PMID:10593184, PMID:17997129, https://www.cdc.gov/parasites/sleepingsickness/biology.html, GOC:ach

**Comment by pgaudet** [comment]
Added required OPL terms in imports

**Comment by krchristie** [comment]
@pgaudet - I've added the term, without the starts & ends relationships because the necessary OPL terms aren't available yet. I see though that you added the needed OPL terms, so perhaps you were working on this too, but if you like, you can leave it for me and I'll the relationships once the OPL terms are available in Protege.

**Comment by pgaudet** [comment]
Hi @krchristie please go ahead and add the term, I was just trying to save time and get these into the imports. I think these gets automatically updated weekly. 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Thanks a lot @krchristie & @pgaudet for helping with this term.
BW,
Achchuthan

**Comment by krchristie** [comment]
> Hi @krchristie please go ahead and add the term, I was just trying to save time and get these into the imports. I think these gets automatically updated weekly.
> 
> Thanks, Pascale

Yea, I think most of the imports are weekly, so it's great that you got those terms in so quickly.

**Comment by balhoff** [comment]
@krchristie see #21921
