### ISSUE TITLE
NTR: RNA folding chaperone

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21913]
Please provide as much information as you can: 

* **Suggested term label:**
RNA folding chaperone

* **Definition (free text)**
Binding to an RNA or an RNA-containing complex to assist the folding process.

* **Reference, in format PMID:#######**
PMID:31165735

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
- molecular function
- part of some RNA folding

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Requested by DisProt group

@federicaquaglia @esalladini

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140691
+name: RNA folding chaperone
+namespace: molecular_function
+def: "Binding to an RNA or an RNA-containing complex to assist the folding process." [PMID:31165735]
+is_a: GO:0003674 ! molecular_function
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21913 xsd:anyURI
+created_by: pg
+creation_date: 2021-08-04T07:48:29Z
+

**Comment by pgaudet** [comment]
Current annotations from 
- PMID:7958841 rpsL (ecocyc @keseler ) 
- PMID:30962391 PDE338 (TAIR @tberardini ) 
- PMID:17376161 RBGA5 (UniProt) could be moved/added to the new term. 
Thanks, Pascale

**Comment by tberardini** [comment]
want me to do anything here? @pgaudet

**Comment by pgaudet** [comment]
@tberardini when the new term is available, you can move/add the new term to PDE338 from PMID:30962391 - but the current annotation is not wrong. 

Thanks, Pascale

**Comment by tberardini** [comment]
Added.
