### ISSUE TITLE
synonym value = "false"

### ISSUE THREAD

**Issue by stephanielipow** [geneontology/go-ontology#21929]
There are two GO ids that have broader synonyms with the value "false" -- looks like an error?
GO:0071877|false
GO:0071878|false

**Comment by suzialeksander** [comment]
thanks @stephanielipow for reporting this.

**Comment by krchristie** [comment]
Good catch @stephanielipow 

I checked a copy of the ontology file from September 2019 and these "false" synonyms were present then. I don't have any older copies, so I'm just going to delete these two synonyms

**Comment by krchristie** [comment]
@pgaudet - I had a personal copy of a file from September 2019 and the "false" synonyms were already present then. I tried to pull an older copy from the archive, but it wasn't loading for me. I don't know if it's worth bothering to check if there was some real value there before, but thought I'd mention it.

**Comment by pgaudet** [comment]
This probably came from https://github.com/geneontology/go-ontology/issues/14733

I've added the synonyms that I think I was trying to add, 
-  "negative regulation of adrenergic receptor signaling pathway" EXACT []
- "regulation of adrenergic receptor signaling pathway" EXACT []
Thanks, Pascale
