### ISSUE TITLE
NTR: [very long-chain fatty acid omega-hydroxylase activity]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#21925]
Please provide as much information as you can: 

* **Suggested term label: very long-chain fatty acid omega-hydroxylase activity**

* **Definition (free text): Catalysis of the reaction: an ω-methyl-very-long-chain fatty acid + O2 + reduced [NADPH—hemoprotein reductase] = an ω-hydroxy-very-long-chain fatty acid + H+ + H2O + oxidized [NADPH—hemoprotein reductase]**

* **Reference, in format PMID: PMID:16547005**

* **Gene product name and ID to be annotated to this term: UniProt ID: Q08477-2**

* **Parent term(s): is a GO:0016705; is a GO:0004497 **

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED): cytochrome P450 very long-chain fatty acid omega-hydroxylase activity (related)**

* **Cross-references: RHEA:67952 – not yet public**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @nnouspikel 

Is there a corresponding EC?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140692
+name: very long-chain fatty acid omega-hydroxylase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: an omega-methyl-very-long-chain fatty acid + O2 + reduced [NADPH—hemoprotein reductase] = an omega-hydroxy-very-long-chain fatty acid + H+ + H2O + oxidized [NADPH—hemoprotein reductase]." [PMID:16547005]
+is_a: GO:0004497 ! monooxygenase activity
+is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21925 xsd:anyURI
+created_by: pg
+creation_date: 2021-08-05T07:41:17Z

**Comment by nnouspikel** [comment]
Thanks a lot Pascale.

**Comment by pgaudet** [comment]
Add RHEA:67952 when publicly available.

**Comment by nnouspikel** [comment]
Hi Pascale, Would it be possible to add GO:0140692 is a GO:0120250 as well? Thanks!

**Comment by pgaudet** [comment]
Thanks Nevila, done. 

Question: Are all fatty acid omega-hydroxylases, monooxygenases? Maybe this is where that relation goes? (I think this is right - the def of GO:0120250 is 

Catalysis of the reaction: an omega-methyl fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an omega-hydroxy fatty acid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase].

Thanks, Pascale

**Comment by nnouspikel** [comment]
Yes exactly GO:0120250 is GO:0004497 is a GO:0016705. Thanks Pascale
