### ISSUE TITLE
NTR: non-membrane-bounded organelle formation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21939]
Please provide as much information as you can: 

* **Suggested term label:**
non-membrane-bounded organelle formation

* **Definition (free text)**

**LD** 
'cellular component assembly'
 and (results_in_assembly_of some non-membrane-bounded organelle)

* **Reference, in format PMID:#######**
PMID: 28225081

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0070925 organelle assembly 

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
(inferred): 
'bacterial-type flagellum assembly'
'cellulosome assembly'
'centriole assembly'
'kinetochore assembly'
'lipid droplet formation'
'myofibril assembly'
'P granule assembly'
'P-body assembly'
'podosome assembly'
'proteasome storage granule assembly'
'ribosome assembly'
'septin ring assembly'
'spindle assembly'
'stress granule assembly'
'terminal web assembly'

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
+synonym: "non-membrane-bounded organelle assembly" EXACT []
+synonym: "non-membrane-bounded organelle formation" EXACT []
+synonym: "non-membrane-enclosed organelle assembly" EXACT []
+synonym: "non-membrane-enclosed organelle formation" EXACT []

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* For IDPO alignment - requested by DisProt @federicaquaglia @esalladini

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140694
+name: non-membrane-bounded organelle assembly
+def: "The aggregation, arrangement and bonding together of a set of components to form a non-membrane-bounded organelle." [PMID:28225081]
+synonym: "non-membrane-bounded organelle assembly" EXACT []
+synonym: "non-membrane-bounded organelle formation" EXACT []
+synonym: "non-membrane-enclosed organelle assembly" EXACT []
+synonym: "non-membrane-enclosed organelle formation" EXACT []
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0043228 ! non-membrane-bounded organelle
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21939 xsd:anyURI
+created_by: pg
+creation_date: 2021-08-09T15:30:06Z

**Comment by ValWood** [comment]
> Children terms (if applicable) Should any existing terms that should be moved underneath this new proposed term?
(inferred):


No
'bacterial-type flagellum assembly'
'centriole assembly'
'kinetochore assembly'
'myofibril assembly'
'ribosome assembly'
'septin ring assembly'
'spindle assembly'

Yes
'P granule assembly'
'P-body assembly'
'proteasome storage granule assembly'
'stress granule assembly'

Don't know
'cellulosome assembly'
'lipid droplet formation'
'podosome assembly'
'terminal web assembly'

As an aside, I worry a little about these "formation terms" being used for  phenotypes for any member of a condensate/stress granule etc which if not present the granule does not form correctly. This is a bit like annotating a mutated subunit of the proteasome to proteasome assembly. 
IMHO to use such terms something should be either a) a chaperone (not part of the final complex/condensate) or be shown to be a substrate in some regulation (i.e. modification dependent).

**Comment by pgaudet** [comment]
> As an aside, I worry a little about these "formation terms" being used for phenotypes for any member of a condensate/stress granule etc which if not present the granule does not form correctly. 


Right, we discussed this- this is a general problem for all assembly terms. In this case there is a MF, molecular condensate scaffold activity, that serves to assemble to condensate, at least in some cases. The review that @esalladini provided explains this quite nicely PMID:28225081

**Comment by pgaudet** [comment]
WRT the terms you say should not be children: 
No
'bacterial-type flagellum assembly'
'centriole assembly'
'kinetochore assembly'
'myofibril assembly'
'ribosome assembly'
'septin ring assembly'
'spindle assembly'

they classify automatically because they themselves are non-membrane-bounded organelles. Why do you think they are not relevant there?

**Comment by ValWood** [comment]
I don't think they are "condensates" at least flagellum,  ribosome, and spindle have a defined stoichiometry, or defined structure.  I'm less sure about kinetochore but I don't think it is a condensate- but perhaps it is-  I will ask.

We  already  said "condensate" is narrower than "are non-membrane-bounded organelles", so maybe we really do need to define and add the term.

**Comment by ValWood** [comment]
The flagellum, kinetochore,  ribosome, spindle have a very defined, regulated, step-wise assembly pathway.

I thought that  "condensate" formation  was more of an intrinsic property of the proteins. Although I guess this is "fuzzy".
I still think we need to be wary of calling everything  that is not membrane-bound a condensate.

**Comment by ValWood** [comment]
> Right, we discussed this- this is a general problem for all assembly terms. In this case there is a MF, molecular condensate scaffold activity, that serves to assemble to condensate, at least in some cases. The review that @esalladini provided explains this quite nicely PMID:28225081

Right. But I would not annotate a scaffold  that was part of a complex to a BP "protein complex assembly" if the complex is self-organizing. If activity needs to happen (i.e.  a modification) to make  the scaffold function as a scaffold then I think that it is part of an 'active process of assembly'. Otherwise it is only a scaffold  involved in a signalling pathway (or some other pathway).  Also we requested scaffold  terms before but these were prevented. We had to use molecular adaptor (even though I think they are slightly  different things, and some  proteins like MAP kianse scaffolds are both scaffolds and adaptors). I'll add these comments to the scaffold ticket.



By

**Comment by ValWood** [comment]
Maybe I am over-thinking this. It's just that most of the annotation I look at for these "assembly" processes the evidence is poor. In some cases the expression level drives condensate formation. However in others there is some active step-wise process.  That seems to be what the review says too. It's important only to annotate the active processes (and that it aligns with what we mean by a GO  BP). I guess in most cases I don't see a difference in the practice  that has been discussed for protein complex assembly.

For example
we don't annotate 
MAP-kinase scaffold activity
The binding activity of a molecule that functions as a physical support for the assembly of a multiprotein mitogen-activated protein kinase (MAPK) complex. Binds multiple kinases of the MAPKKK cascade, and also upstream signaling proteins, permitting those molecules to function in a coordinated way. Bringing together multiple enzymes and their substrates enables the signal to be transduced quickly and efficiently.

to a term "MAPK complex assembly" (there is no such term), but we annotate it to the signalling process.
This was decided back at the signalling meeting in 2019, but maybe we want to do it some other way? Whatever, we should be consistent -I find it very confusing that  assembly of condensates and complexes would be treated differently.  I'm also a bit disturbed that we pull in so many inferred annotations to "assembly of non membrane-bound complexes" to gene products for which there seems to be no evidence  for  a direct role in this process.
(Note that these concerns predated any of these recent  new term request in this area, I just didn't get around to reporting them yet -these changes actually make things clearer, and I think the scaffold MF term will be useful, it's the process I have a problem with in some cases).

I guess it does no harm to let this roll along for a bit but this seems to be one of those areas where everything which interacts with something within a complex or condensate  during its formation would become annotated to its "assembly".

**Comment by pgaudet** [comment]
In this specific case all I did was to create a grouping term for already existing 'non-membrane bounded organelle assembly' terms. 

But I agree evidence is often lacking, and certainly knockouts should not be used as evidence for this process.

**Comment by ValWood** [comment]
>In this specific case all I did was to create a grouping term for already existing 'non-membrane bounded organelle assembly' terms.

I know, I'll leave this for now....

**Comment by ValWood** [comment]
Based on this paper, I would include kinetochore in the condensate list
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7341897/
