### ISSUE TITLE
Add tab to set of disallowed characters in checks

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#21941]
To prevent future occurrences of #21891. 

This could go in either the perl checks or in robot/sparql

**Comment by cmungall** [comment]
I think we should also disallow double whitespace when not followed by a period.

we have many of these

* def: "The process of coupling valine to valyl-tRNA, catalyzed by valyl-tRNA synthetase. The valyl-tRNA synthetase is **a  class**-I synthetase. The activated amino acid is transferred to the 2'-OH group of a valine-accetping tRNA. The 2'-O-aminoacyl-tRNA will ultimately migrate to the 3' position via transesterification." [GOC:mcc, ISBN:0716730510]

Easy search and replace on the obo file

**Comment by pgaudet** [comment]
Thanks @cmungall 

Is this merged? Can it close?
