### ISSUE TITLE
Obsoletion notice: GO:0034419 L-2-hydroxyglutarate oxidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21950]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0034419 L-2-hydroxyglutarate oxidase activity

* **Reason for deprecation**
This activity is not believed to exist, see PMID:30498244

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
* GO:0003973 (S)-2-hydroxy-acid oxidase activity

* **Are there annotations to this term?**
- How many EXP: 1 
- by EcoWiki P37339 @dsiegele 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0034419 L-2-hydroxyglutarate oxidase activity'. The reason for obsoletion is that this function is not believed to exist, see PMID:30498244. 

There is one EXP annotation to this term; there are no mappings to this term; this term is not present in any subsets. 

You may comment on the ticket here: https://github.com/geneontology/go-ontology/issues/21950

Thanks, Pascale

**Comment by alanbridge** [comment]
could you make a new GO term for 

(S)-2-hydroxyglutarate dehydrogenase

would apply to 

https://www.uniprot.org/uniprot/P37339

and map to 

EC 1.1.5.13 (S)-2-hydroxyglutarate dehydrogenase

https://www.rhea-db.org/rhea/58664

maybe that could be the
