### ISSUE TITLE
Change term labels, parents for some children of GO:0052205 modulation of molecular function in other organism involved in symbiotic interaction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21963]
- [x] GO:0039576 suppression by virus of host JAK1 activity -> also a child of ' GO:0039514 suppression by virus of host JAK-STAT cascade'; cannot annotate the annotated proteins to 'JAK1 inhibitor activity' because it is not clear how it inhibits JAK1, so I will change the label to 'suppression by virus of host JAK-STAT cascade via inhibition of JAK1 activity', and remove the 'GO:0052053 negative regulation by symbiont of host catalytic activity' parent. 

Same for 
- [x] GO:0039562 suppression by virus of host STAT activity - change label to 'suppression by virus of host JAK-STAT cascade via inhibition of STAT activity'
- [x]  GO:0039563 suppression by virus of host STAT1 activity
- [x]  GO:0039564 suppression by virus of host STAT2 activity

**Comment by pgaudet** [comment]
We have links to these ViralZone and UniProtKW directly in the ontology - 

-  GO:0039576  suppression by virus of host JAK1 activity  VZ:784, UniProtKB-KW:KW-1096
- GO:0039563  suppression by virus of host STAT1 activity UniProtKB-KW:KW-1105, VZ:282     
-  GO:0039564  suppression by virus of host STAT2 activity VZ:257, UniProtKB-KW:KW-1106
These are already in Viral Zone and in uniprotkb_kw2go, so I will remove them from the ontology.

**Comment by pgaudet** [comment]
Hi @pmasson55 
All paper I check actually talk about IFN signaling leading to STAT activation - should we edit the term to be more precise? 

see for eg PMID:16188985 
PMID:32699158

**Comment by pgaudet** [comment]
> Hi @pmasson55
All paper I check actually talk about IFN signaling leading to STAT activation - should we edit the term to be more precise?

see for eg PMID:16188985
PMID:32699158

**Comment by dsiegele** [comment]
@pgaudet "Measles virus specifically suppresses the IFN-α induced antiviral state but not IFN-γ induced signalling [37]. Viral inhibition of JAK1 phosphorylation by IFN-α suggested that the virus was targeting the signalling pathway upstream of JAK at the level of the type 1 IFN receptor."  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5041017/

**Comment by pgaudet** [comment]
No annotations, no mappings: 
GO:0039647 suppression by virus of host poly(A)-binding protein activity
GO:0110087 suppression by virus of host protease activator activity

**Comment by pgaudet** [comment]
GO:0039516 modulation by virus of host catalytic activity
GO:0039507 suppression by virus of host molecular function

No annotations
