### ISSUE TITLE
NTR: negative regulation of pollen tube guidance

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#21965]
Please provide as much information as you can: 

* **Suggested term label:**
negative regulation of pollen tube guidance

* **Definition (free text)**
Any process that decreases the rate, frequency or extent of pollen tube guidance towards ovules. This is one mechanism to prevent polytuby, the simultaneous penetration of ovules by multiple pollen tubes.

* **Reference, in format PMID:#######**
PMID:33790463

* **Gene product name and ID to be annotated to this term**
AT1G31450 (ECS1)  
AT2G35615 (ECS2)  
* **Parent term(s)**
GO:0010183 pollen tube guidance

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
prevention of polytuby BROAD

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160068
+name: negative regulation of pollen tube guidance
+namespace: biological_process
+def: "Any process that decreases the rate, frequency or extent of pollen tube guidance towards ovules. This is one mechanism to prevent polytuby, the simultaneous penetration of ovules by multiple pollen tubes." [PMID:33790463]
+synonym: "prevention of polytuby" BROAD []
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0010183 ! pollen tube guidance
+created_by: rynl
+creation_date: 2023-03-31T21:16:03Z
