### ISSUE TITLE
NTR: regulation of the velocity of shortening of cardiac muscle modulating contraction

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#21964]
Please provide as much information as you can: 

* **Suggested term label:**
1. regulation of cardiac muscle contraction by chemo-mechanical energy conversion
2. regulation of the velocity of shortening of cardiac muscle modulating contraction

* **Definition (free text)**
1. Any process that modulates the frequency, rate or extent of cardiac muscle contraction by regulating force and velocity of shortening. The force of cardiac muscle contraction is produced by acto-myosin interaction processes through formation of cross bridges. The shortening leads to reduction of length of muscle fiber and sarcomeres.
2. Any process that modulates velocity of shortening of a cardiac muscle contraction. The shortening leads to reduction of the length of muscle fibers and sarcomeres.

* **Reference, in format PMID:#######**
PMID: 32207065

* **Gene product name and ID to be annotated to this term**
Gene: Myh7b, RGD:1307994

* **Parent term(s)**
1. regulation of cardiac muscle contraction (GO:0055117) 
2. regulation of cardiac muscle contraction by chemo-mechanical energy conversion (new term)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

2. regulation of the velocity of shortening of cardiac muscle during contraction (RELATED synonym)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @slaulederkind 

First, apologies for the long delay in the response. Looking at this term request, myosin **mediates** muscle contraction, so would you be annotating regulation to describe a phenotype? How about using GO:0060048 cardiac muscle contraction? Or if you dont think the evidence is solid enough, based on our current guidelines for gene product-to-term relation, you could use 'causally upstream of or within, positive effect'. Does that work for you ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
No problem.  We can use currently available terms.
