### ISSUE TITLE
NTR: telopode

### ISSUE THREAD

**Issue by lubianat** [geneontology/go-ontology#21973]
Please provide as much information as you can: 

* **Suggested term label:**
 telopode

* **Definition (free text)**
A telopode is a plasma membrane bounded cell projection that is present on telocytes and is tens to hundreds of microns long. Telopodes form a labyrinthine system communicating through gap junctions. 

* **Reference, in format PMID:#######**
PMID:20367664

* **Parent term(s)**
[GO:0120025](http://amigo.geneontology.org/amigo/term/GO:0120025) (plasma membrane bounded cell projection)

* **Cross-references**

Wikidata: [Q70197777](https://www.wikidata.org/wiki/Q70197777)
[MESH:D000067617](https://meshb.nlm.nih.gov/record/ui?ui=D000067617)

They are also mentioned in Wikipedia's article on telocytes: https://en.wikipedia.org/wiki/Telocyte 

* **Any other information**
Definition in MeSH is : " The very long and thin extensions of telocytes' cell surface, that have alternating thick and thin sections called podoms and podomers."

Telocytes are currently [being added to CL](https://github.com/obophenotype/cell-ontology/pull/1198/commits/713d7c0ac19ef1991928a83210f285b397c70ccb), having a GO Term would enable better logic definitions.

**Comment by krchristie** [comment]
I didn't include the Wikidata xref as we don't currently have any of those in the ontology. 

@pgaudet @cmungall - Is Wikidata a type of xref we want to be able to reference in GO?
