### ISSUE TITLE
Changes to GO:0039580 suppression by virus of host PKR activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21971]
Hi @pmasson55 

GO:0039580  suppression by virus of host PKR activity is mapped to ~KW-1223~  https://www.uniprot.org/keywords/1102 and https://viralzone.expasy.org/554

Looks like proteins annotated to that term inhibit PKR, which is a kinase that regulates eukaryotic translation initiation factor 2.

So - a mapping to 'GO:0039611 suppression by virus of host translation initiation factor activity' + GO:0030291 protein serine/threonine kinase inhibitor activity seems more appropriate, what do you think? 

Also - I think this is a type of suppression of innate immune response, also because it is mediated by interferon? 

Thanks, Pascale

**Comment by pmasson55** [comment]
Hi PAscale,

Yes we can do that. Yes it belongs to the inhibition of innate immune response by pathogens for sure...
Regards
Patrick.

**Comment by pgaudet** [comment]
Will you redo the mappings in ViralZone? 

And I think @pgarmiri and/or @Antonialock do the KW mappings - right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Changed term label and definition 

 id: GO:0039580
* **old name:** suppression by virus of host PKR activity
* **new name:** suppression by virus of host PKR signaling

* **old def:** "Any process in which a virus stops, prevents, or reduces the frequency, rate or extent of host PKR (protein kinase regulated by RNA) activity. Activation of PKR involves dsRNA binding followed by autophosphorylation. Phosphorylated PKR can then phosphorylate downstream targets such as the translation initiation factor eIF2 to inhibit protein synthesis. Viruses encode a number of mechanisms to inhibit the host antiviral response via PKR, including direct interaction with PKR, promoting degradation of PKR or altering the subcellular location of PKR." [PMID:15207627, UniProtKB-KW:KW-1102, VZ:554]

* **new def** : "Any process in which a virus stops, prevents, or reduces the frequency, rate or extent of host PKR (Protein Kinase regulated by RNA) signaling. Host PKR signaling includes targets such as the translation initiation factor eIF2alpha,  inhibiting protein synthesis as an antiviral response." [PMID:15207627]

**Comment by Antonialock** [comment]
is that the correct keyword ID?

KW-1223 is mapped to suppression by virus of host TBK1 activity GO:0039723
https://www.uniprot.org/keywords/KW-1223

**Comment by pgaudet** [comment]
Thanks @Antonialock 

The correct KW is https://www.uniprot.org/keywords/1102

**Comment by Antonialock** [comment]
I mapped kw-1102 to GO:0039611 & GO:0030291
and removed the mapping to GO:0039580

is this what was required here?

**Comment by pgaudet** [comment]
@Antonialock 
Actually I dont think mappings should have been changed. 

- [ ]  'GO:0039611 suppression by virus of host translation initiation factor activity' is not correct - the viral protein inhibits the inhibitor of the translation initiation factor - ie it is one step before. - please remove this
- [ ] please add back GO:0039580 suppression by virus of host PKR activity (now named 'suppression by virus of host PKR signaling') 

- GO:0030291 protein serine/threonine kinase inhibitor activity  is OK

Sorry about the confusion! 

Thanks, Pascale

**Comment by Antonialock** [comment]
ok! done.
