### ISSUE TITLE
Changes to viral term 'GO:0039723 suppression by virus of host TBK1 activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21970]
KW-1223 defines this keyword as  'Viral protein involved in the evasion of host innate defenses by inhibiting the TBK1 kinase. Upon viral infection, Toll-like receptors (TLRs) or DNA recognition receptors recognize foreign material and transmit the signal to TBK1 that in turn phosphorylates and activates IRF3 and IRF7. Once phosphorylated, IRF3 and/or IRF7 translocate into the nucleus to drive transcription of interferons. Several viruses including herpes simplex virus 1 or vaccinia virus interact directly with and inhibit TBK1 to prevent IRFs activation.'  (https://www.uniprot.org/keywords/KW-1223)

Should we keep this term and move it, or merge it into 'suppression by virus of host toll-like receptor signaling pathway',
AND annotate the proteins annotated to the KW to MF 'protein serine/threonine kinase inhibitor activity' ? 

If we keep the term, there are two possible parents for this term: 
- 'evasion of host immune response', defined as 'A process by which an organism avoids the effects of the host organism's immune response. 
- 'suppression by virus of host toll-like receptor signaling pathway', which is not 'evasion' but 'suppression' 

- [ ] remove comment that refers to obsolete term: "Comment: When TBK1 acts as part of a TBK1-IKBKE-DDX3 complex, consider also annotating to: suppression by virus of host TBK1-IKBKE-DDX3 complex activity ; GO:0039659."

@pmasson55 what do you think is the best solution ? 

Thanks, Pascale

**Comment by pmasson55** [comment]
Hi Pascale,

I would vote for keeping the term. Because merging it into 'suppression by virus of host toll-like receptor signaling pathway' is not very correct since it belongs to others pathways in addition to the TLR ( for example the pattern receptors such as RIG and MDA5 also promotes TBK1 kinase activity...). 
I guess 'evasion of host immune response' is good for parent.
For the comment it's better to remove it indeed...
Hope this helps
Patrick.

**Comment by pgaudet** [comment]
@pmasson55 

Inhibition of host TBK1 by virus (KW-1223)  is_a Inhibition of host TLR pathway by virus (KW-1225)  - does the VZ KW hierarchy need to be changed, if TBK1 inhibition doesn't always go through TLR?

**Comment by pgaudet** [comment]
[Term]
 id: GO:0039723
-name: suppression by virus of host TBK1 activity
+name: suppression by virus of host viral-induced cytoplasmic pattern recognition receptor signaling pathway via inhibition of TBK1 activity
-def: "Any process in which a virus stops, prevents, or reduces the activity of the host serine/threonine kinase TBK1." 
+def: "Any process in which a virus stops, prevents, or reduces host viral-induced cytoplasmic pattern recognition receptor signaling by reducing the activity of the host serine/threonine kinase TBK1." [PMID:22171259, PMID:34084167]
