### ISSUE TITLE
Change label & def GO:0039545 suppression by virus of host MAVS activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21983]
GO:0039545 suppression by virus of host MAVS activity
change to 'suppression by virus of host viral-induced cytoplasmic pattern recognition receptor signaling pathway via inhibition of MAVS activity

@pmasson55 can you please provide some PMIDs?

**Comment by pmasson55** [comment]
Hi Pascale,

here are some pubmeds : https://pubmed.ncbi.nlm.nih.gov/22674996/
and https://pubmed.ncbi.nlm.nih.gov/17438296/
Hope this helps
Patrick.
