### ISSUE TITLE
NTR: [CAT tailing]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#21987]
Please provide as much information as you can: 

* **Suggested term label:**
CAT tailing

* **Definition (free text)**
The C-terminal elongation of 60S-anchored nascent chains with untemplated Alanine and Threonine tails (CAT tails).

* **Reference, in format PMID:#######**
PubMed=25554787, PubMed=32934225
* **Gene product name and ID to be annotated to this term**
NEMF/O60524, RQC2/Q12532
* **Parent term(s)**
Could not find an appropriate one except GO:0006414 translational elongation

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @lbreuza 

PMID:32934225 states that this is a likely mechanism to target polypeptide chains for ubiquitylation and degradation, so, is this different from 'ribosome-associated ubiquitin-dependent protein catabolic process' ? 

It seems we may be lacking a MF to describe this? this is some sort of amino acid ligase reaction, isn't it?

**Comment by lbreuza** [comment]
Hi @pgaudet,

I would say it is part of ribosome-associated ubiquitin-dependent protein catabolic process.

At a molecular level it looks like normal translation elongation by the ribosome except it is not mRNA templated and is positively regulated by RQC2.

**Comment by pgaudet** [comment]
@lbreuza 

How about 

is_a co-translational protein modification ?

**Comment by lbreuza** [comment]
> 
> 
> @lbreuza
> 
> How about
> 
> is_a co-translational protein modification ?

why not but it does not align well with the definition of the term: "The process of covalently altering one or more amino acids"

**Comment by pgaudet** [comment]
OK yes, and  RQC2/Q12532 brings tRNAs to the ribosome, so this is translation elongation (although, abnormal translation elongation).

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140708
+name: CAT tailing
+namespace: biological_process
+def: "The C-terminal elongation of 60S-anchored stalled nascent polypeptide chains with untemplated alanine and threonine tails (CAT tails). CAT tails are a component of the ribosome quality control sytem." [PMID:25554787, PMID:32934225]
+is_a: GO:0006414 ! translational elongation
+relationship: part_of GO:1990116 ! ribosome-associated ubiquitin-dependent protein catabolic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21987 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-03T13:16:20Z


Hopefully this works.
