### ISSUE TITLE
NTR: [cyclic-GMP-AMP-mediated signaling]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#21980]
Hi GO,

I apologize in advance for the complex request, but cGAS-Sting signaling would need some refinement.

PMID:34261127 and PMID:34261128 demontrate that Drosophila cGLR1 (CG12970, UniProt A1ZA55) catalyzes synthesis of 3',2'cyclic-GMP-AMP.

Would it be possible to modify 2 terms and create a new one?

Thanks

Sylvain

1) Modify the Xref of GO:0061501, because there are different cyclic GMP-AMP and only one (3',3'-cGAMP) is mapped to the GO term

Modify the Xref part:
Xrefs
FROM:
RHEA:35647
TO:
RHEA:42064
RHEA:35647
RHEA:68344 (not yet public) 

Another option would be to create a GO term for every reaction (2',3', 3',2' or 3'3' cGAMP). Let me know if it is your preferred option, I can submit terms

I plan to make a GO-CAM model with them and specify which reaction is mediated using the has_output relation

2) The same for GO:0061507 cyclic-GMP-AMP binding. Drosophila Sting can bind both 2',3'-cGAMP and 3',2'-cGAMP and only 3'3' cGAMP is mapped.

GO:0061507 cyclic-GMP-AMP binding 
Xrefs
FROM:
CHEBI:71501
TO:
CHEBI:71501
CHEBI:143093
CHEBI:177334

3) cyclic-GMP-AMP-mediated signaling

There is no term for cyclic-GMP-AMP-mediated signaling and I guess it would be important to create some since for the moment, only cGMP-mediated signaling exists

Suggested term label: 
cyclic-GMP-AMP-mediated signaling
Definition:
Any intracellular signal transduction in which the signal is passed on within the cell via cyclic GMP-AMP (cGAMP).
child of  GO:0019934 cGMP-mediated signaling
Xref
PMID:23258413
PMID:28738408

**Comment by pgaudet** [comment]
@sylvainpoux are the different forms of cyclic-GMP-AMP mediating signaling in different pathways?

**Comment by sylvainpoux** [comment]
Hi Pascale,

for the moment it is not that clear, because only a limited number of cGAS members have been characterized in different species. What is clear is that these second messenger regulate immunity against pathogens.

1) CGAS in human detect dsDNA and catalyzes formation of 2'3' cGAMP
2) human MB21D2 has a nucleotidyltransferase fold but we don't know what activates its activity and its catalytic activity
3) Drosophila cGLR1 catalyzes 3'2'-cGAMP and detects dsRNA from viruses
4) Drosophila cGLR2 catalyzes 3'2'-cGAMP and 2'3'-cGAMP and we don't know its activator

In eukaryotes, both 2'3' cGAMP and 3'2'cGAMP activate STING and type I interferons (in vertebrates) and IMD pathway in Drosophila. In both cases, they activate an antiviral and antibacterial response.

5) E.coli dncV catalyzes 3'3'-cGAMP. In bacteria 3'3'cGAMP vis involved in immunity against bacteriophages.

**Comment by pgaudet** [comment]
For my own information
from https://www.nature.com/articles/s41467-018-06922-7

<img width="747" alt="image" src="https://user-images.githubusercontent.com/4782928/130079035-c9cca35e-e697-42f4-a8ca-7a8eb4c73c79.png">

**Comment by pgaudet** [comment]
WRT your requests: 

- we cannot have multiple cross references on the  same GO term - at lest not for the binding, as the binding describes which specific form of c-GMP-AMP the protein binds to. If the binding is specific for one of the two, we should create the specific terms. 

- likewise for GO:0061501 cyclic-GMP-AMP synthase activity: it looks like the enzymes are specific for one or the other form, so we should create both children. 
- Right now, GO:0061501 is linked to RHEA, suggesting that this term describes  3',3'-cGAMP synthase - do you know if existing annotations are correct? Or do we need to obsolete GO:0061501 and replace by the specific reactions? A third possibility is to keep GO:0061501 and remove xrefs, and create the 2 specific children.
- 
Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,

1) if there is no way to link multiple cross-references, then the best would be to create separate GO terms for "cyclic-GMP-AMP binding" and "cyclic-GMP-AMP synthase activity" 

I would propose to keep the existing terms as parent reaction and remove the ChEBI and Rhea mapping (I think it corresponds to your third proposition). 

2) Please note that GO policy is inconsistent here. In the past, GO didn't want to create reactions for specific reactions and only keep a parent generic reaction (for some lipid enzymes). But I'm fine with our proposition.

3) Existing annotations in eukaryotes are incorrect, since all entries annotated correspond to  2',3'-cGAMP. The prokaryote annotations are correct. Please note that initial annotation were correct only 2'3'cGAMP was known at that time. The mapping to ChEBI and Rhea is however incorrect.

Many thanks for your help! I will send you draft definitions later today.

Sylvain

**Comment by sylvainpoux** [comment]
Here we are:

1) Modify GO:0061501 cyclic-GMP-AMP synthase activity

Remove the Xref part to RHEA:35647

2) Create: 2',3' cyclic-GMP-AMP synthase activity

Catalysis of the reaction: ATP + GTP = 2',3'-cGAMP + 2 diphosphate

Xref: RHEA:42064
PMID:23258413 
child of GO:0061501 

3) Create: 3',3' cyclic-GMP-AMP synthase activity

Catalysis of the reaction: ATP + GTP = 3',3'-cGAMP + 2 diphosphate

Xref: RHEA:35647
PMID:30787435 
child of GO:0061501 

4) Create: 3',2' cyclic-GMP-AMP synthase activity

Catalysis of the reaction: ATP + GTP = 3',2'-cGAMP + 2 diphosphate

Xref: RHEA:68344 (not yet public)
PMID:34261127 
child of GO:0061501 

5) Modify GO:0061507 cyclic-GMP-AMP binding

Remove the Xref part to CHEBI:71501

6) Create: 2',3' cyclic-GMP-AMP binding

Binding to 2',3' cyclic-GMP-AMP (2',3'-cGAMP) cyclic nucleotide.

Xref: CHEBI:143093
PMID:23258412 
child of GO:0061507 

7) Create: 3',3' cyclic-GMP-AMP binding

Binding to 3',3' cyclic-GMP-AMP (3',3'-cGAMP) cyclic nucleotide.

Xref: CHEBI:71501
child of GO:0061507 

8) Create: 3',2' cyclic-GMP-AMP binding

Binding to 3',2' cyclic-GMP-AMP (3',2'-cGAMP) cyclic nucleotide.

Xref: CHEBI:177334
PMID:34261127
child of GO:0061507

**Comment by pgaudet** [comment]
@sylvainpoux I cannot find 3',3'-cGAMP in CHEBI - unless you want to capture this as the unspecified class https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:71501 ? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,

I think  https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:71501 is correct, since 3',3'-cGAMP is used as synonym.

At least it is the ChEBI we use in Rhea and UniProt. Maybe @kaxelsen can help and provide more explanation.

Thanks

Sylvain

**Comment by pgaudet** [comment]
One issue remains: 
We have GO:0140702 cyclic GMP-AMP binding as 'do not annotate', using ChEBI:71501 c-GMP-AMP(2−)
That ChEBI has synonym '3',3'-cGAMP ', which corresponds to  the child we have created, GO:0140703 3',3'-cyclic GMP-AMP binding 

Ideally ChEBI would create the 3',3'-cGAMP' child. @sylvainpoux can you please ask ChEBI for that term? 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi @sylvainpoux I wanted to just draw your attention to this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8771144/ as it relates to the question of cyclic di-nucleotide signaling. I haven't put a super amount of thought into it, but you and @pgaudet have, I thought I would just flag it as something that may be pertinent to this ticket.

So, in this paper it would appear that cyclic di-nucleotides are transported across the membrane by CNT2/FBgn0025709 and therefore activate STING (missing out cGAS bit) and NF-kappaB signaling. For me, the CNT2 activity is captured by positive regulation of the 'cGAS/STING signaling pathway' or causally upstream of 'cGAS/STING signaling pathway' but causally upstream of 'cyclic-nucleotide-mediated signaling' (the current best fit in the GO) or, if the child term existed 'cyclic di-nucleotide'.

**Comment by kaxelsen** [comment]
@pgaudet 
Note that both 3'.3'-cGAMP (CHEBI:71501), 2',3'-cGAMP (CHEBI:143093) AND 3',2'-cGAMP (CHEBI:177334) exist.
Synthesis of the three compounds are described in these reactions:
RHEA:35647  ATP + GTP = 3',3'-cGAMP + 2 diphosphate
RHEA:42064 ATP + GTP = 2',3'-cGAMP + 2 diphosphate 
RHEA:68344 ATP + GTP = 3',2'-cGAMP + 2 diphosphate

All three reactions are public and used in Swiss-Prot.
RHEA:42064 is linked to EC 2.7.7.86, the two other reactions are not represented by EC numbers.

This relates to the comment from 21 Aug 2021
>     * [x]   Create: 3',2' cyclic-GMP-AMP synthase activity
>       Catalysis of the reaction: ATP + GTP = 3',2'-cGAMP + 2 diphosphate
>       **Xref: RHEA:68344 (not yet public)**
>       PMID:34261127
>       child of GO:0061501
> 
>     * [x]  For GO:0061501 cyclic-GMP-AMP synthase activity
>       I did differently from what you requested, as all annotations were to 2,3', so I changed the label, and fixed the RHEA to the correct one,  RHEA:42064 + added EC:2.7.7.86
> 
>     * [x]  Created new parent  cyclic-GMP-AMP synthase activity
>       No Rhea link
>       DO NOT ANNOTATE

**Comment by pgaudet** [comment]
Asked CheBI to swap label and synonym for c-GMP-AMP(2−) CHEBI:71501
this will be less confusing

https://github.com/ebi-chebi/ChEBI/issues/4296
