### ISSUE TITLE
Changes to 'suppression by virus of host IRF3 activity', 'suppression by virus of host IRF7 activity' and 'suppression by virus of host IKBKE activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21985]
'suppression by virus of host IRF3 activity'
'suppression by virus of host IRF7 activity'
'suppression by virus of host IKBKE activity'

- [x] move under  GO:0039537 suppression by virus of host viral-induced cytoplasmic pattern recognition receptor signaling pathway
- [x] change labels to  'suppression by virus of host viral-induced cytoplasmic pattern recognition receptor signaling pathway via inhibition of xx activity'

**Comment by pmasson55** [comment]
Hi Pascale, 

here are some pubmeds : https://pubmed.ncbi.nlm.nih.gov/22674996/
and https://pubmed.ncbi.nlm.nih.gov/17438296/
Hope this helps
Patrick.
