### ISSUE TITLE
NTR: myocyte reprogramming involved in skeletal muscle regeneration

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#21995]
Please provide as much information as you can: 

myocyte reprogramming involved in skeletal muscle regeneration 

* **Definition (free text)**
The process during skeletal muscle regeneration whereby myocytes loose their Z-band architecture and become,  mesenchymal, re-enter the cell cycle, then proliferate. 

* **Reference, in format PMID:#######**
PMID:32320444

* **Gene product name and ID to be annotated to this term**
twist3     ZDB-GENE-000210-7 

* **Parent term(s)**
 GO:0043403 skeletal muscle tissue regeneration

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
 myocyte dedifferentiation narrow
* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information
Cell reprograming is a normal part of fish biology.  Fish naturally regenerate almost every tissue and frequently have mature fully differentiated cells become less differentiated and proliferate instead of relying on stem cells.

**Comment by cerivs** [comment]
What is the status of this ticket?  Can this ticket be reviewed by someone?

**Comment by pgaudet** [comment]
Hi @cerivs 
Sorry about the late reply! We dont create procomposed terms anymore, we recommend people annotate these as GO-CAMs as for example 'myocyte reprogramming' part of 'skeletal muscle regeneration' 

Does that work for you ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@cerivs 
You should be able to capture this in GO-CAM without the precomposed term. Please let me know if you need help making the model. 

Thanks, Pascale
