### ISSUE TITLE
GO:0140142 text-superclass discrepancy

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#21999]
The text definition of GO:0140142 includes "The cargo can be either a RNA or a protein." (as do the defs for both subclasses), but the term is is_a: GO:0140597 ! protein carrier activity. Which is correct?

#14336 has background on this term, which suggests that the "RNA or protein" text might be biologically accurate.

presumably also relevant to #20848

**Comment by pgaudet** [comment]
Thanks for pointing that out @mah11 !
