### ISSUE TITLE
add synonym to Nicalin-NOMO complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22002]
Add Nicalin-TMEM147-NOMO complex to GO:0106249

PMID: 32820719

**Comment by krchristie** [comment]
@pgaudet - grabbed this one since it looked super fast

**Comment by krchristie** [comment]
> Add Nicalin-TMEM147-NOMO complex to GO:0106249
> 
> PMID: 32820719

From quick look at paper, it seemed synonym should be EXACT. @ValWood - let me know if that's not correct. Thanks -K

**Comment by ValWood** [comment]
Yes sorry that is corrrect. I forgot scope.
