### ISSUE TITLE
Obsolete  GO:1904766  negative regulation of macroautophagy by TORC1 signaling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22004]
GO:1904766  negative regulation of macroautophagy by TORC1 signaling
has 3 EXP.

Is the plan to create terms like this?
TOTC1 signalling is involved in lots of processes, but elselwerhe we haven't combined the signalling pathway with what it regulates. 
This would be unsustainable.

For example:
negative regulation of autophage
https://www.pombase.org/results/from/id/75c4642e-7380-4e45-8602-68d1fbc14ae6

both of these are TORC1signalling  (or it's regulation)

but we would also need
to add terms for  all of the other processes TORC1  signalling regulates

+ | negative regulation of cell cycle switching, mitotic to meiotic cell cycle
-- | --
+ | negative regulation of G2/M transition of mitotic cell cycle
+ | negative regulation of induction of conjugation with cellular fusion
+ | negative regulation of macroautophagy
+ | positive regulation of cell growth
+ | positive regulation of cytoplasmic translation
+ | positive regulation of G1/S transition of mitotic cell cycle
+ | positive regulation of nuclear-transcribed mRNA catabolic process, meiosis-specific transcripts

etc,

is it generally a plan to precompose signalling pathway terms with the processes they regulate?

**Comment by pgaudet** [comment]
Hi, 

This is a Term Genie term (id starts with GO:19xxxx). We do not plan to precompose terms like this anymore, unless there is a very good reason for the exception. 

This should be obsoleted. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Precomposed term; annotations (3EXP) should be replaced by a GO-CAM model.
