### ISSUE TITLE
Scope of fungal-type cell wall biogenesis (GO:0009272)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22008]
I have been wondering about the scope of 
 fungal-type cell wall biogenesis (GO:0009272)

Definition 
A cellular process that results in the biosynthesis of constituent macromolecules, assembly, and arrangement of constituent parts of a fungal-type cell wall. The fungal-type cell wall contains beta-glucan and may contain chitin.

Is this supposed to include all of the processing that occurs in the ER? for example the glycosylation, does it include chaperones? does it include transport? (I am thinking  about ribosome biogenesis as an analogy)

I pick up quite a lot of mappings to this term from SGD to things which have cell wall compromised phenotypes, but this does seem to fit because the scope is very broad. However I would not  make these as GO annotations.

**Comment by pgaudet** [comment]
@ValWood What types of activities do you think would be relevant for this ? It may help redefine to exclude other activities.

**Comment by ValWood** [comment]
Most of the children are "biosynthetic process" which is different from "biogenesis"
And many terms in. this branch represent activities:
fungal-type cell wall (1->3)-beta-D-glucan biosynthetic process (GO:0071970
cell wall mannoprotein biosynthetic process

 I'm also not sure if we need fungal and plant specific terms...
We have organization, assembly and disassembly for the things which are making the cell wall components. Although the assembly terms are not much used.
The terms are confusing because it isn't clear what belongs to biosynthesis and what belongs to assembly, and we have a grouping term : 
cell wall organization or biogenesis (GO:0071554). 

Anyway this isn't super urgent so I would put it at low priority.

**Comment by ValWood** [comment]
There is no action here and I don't have any issues currently with he annotations
