### ISSUE TITLE
GO:1990578    perinuclear endoplasmic reticulum membrane (missing parent)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22003]
GO:1990578    perinuclear endoplasmic reticulum membrane

Definition (GO:1990578 GONUTS page)
The membrane of the perinuclear endoplasmic reticulum, which is the portion of endoplasmic reticulum, the intracellular network of tubules and cisternae, that occurs near the nucleus. PMID:25454947

is not a descendant of
GO:0005789   endoplasmic reticulum membrane

which I would expect from the text definition  "portion of endoplasmic reticulum"

**Comment by raymond91125** [comment]
endoplasmic reticulum membrane has LD 'organelle membrane'
 and ('bounding layer of' some 'endoplasmic reticulum subcompartment').
Since perinuclear endoplasmic reticulum is not really a 'bounding' layer, it should probably be PartOf endoplasmic reticulum membrane.
