### ISSUE TITLE
GO:0045815 positive regulation of gene expression, epigenetic- merge up children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22012]
Transcription workshop - @colinlog @ValWood @RLovering @pgaudet 

**Term to be merged: Provide GO ID and term label**

follow on from
https://github.com/geneontology/go-ontology/issues/19334 
trying to  better label and def for  GO:0048096    chromatin-mediated maintenance of transcription

BUT

GO:0045815    positive regulation of gene expression, epigenetic
These terms are the same as 

Child Term | Relationship toGO:0045815
~GO:0048097    long-term maintenance of gene activation | is_a~ NOW OBSOLETED
GO:0048096    chromatin-mediated maintenance of transcription

- [ ] All of these  3 (parent & 2 children) have the same meaning. MERGE
GO:0045815.    positive regulation of gene expression, epigenetic 
GO:0048097    long-term maintenance of gene activation | is_a
GO:0048096    chromatin-mediated maintenance of transcription

- [ ] The other child is a bit weird (negative regulation of positive regulation)
GO:0031936    negative regulation of chromatin silencing
We suggest obsoleting this. Not many annotations.

**Comment by ValWood** [comment]
@colinlog

**Comment by ValWood** [comment]
We changed out  minds:

We need to keep 
chromatin-mediated maintenance of transcription
(But this needs a better label and def)

We can merge 
GO:0048097    long-term maintenance of gene activation 
into
GO:0048096    chromatin-mediated maintenance of transcription

**Comment by pgaudet** [comment]
GO:0048097 long-term maintenance of gene activation was obsoleted, see #22015

**Comment by ValWood** [comment]
> Merge 'chromatin-mediated maintenance of transcription' and 'positive regulation of gene expression, epigenetic'

Do we keep the new  'chromatin-mediated maintenance of transcription'  term and definition here? or the. epigenetic parent one? Neither seems to be ideal...

**Comment by pgaudet** [comment]
New def: An epigenetic process that capacitates gene expression by remodelling of chromatin by either modifying the chromatin fiber, the nucleosomal histones, or the DNA.

**Comment by pgaudet** [comment]
Also, add synonyms: 
+synonym: "euchromatin assembly" RELATED []
+synonym: "euchromatin organisation" RELATED []
+synonym: "euchromatin organization" RELATED []
