### ISSUE TITLE
Obsoletion notice: GO:0060821 inactivation of X chromosome by DNA methylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22023]
Please provide as much information as you can:

* **GO term ID and Label**
*  GO:0060821 inactivation of X chromosome by DNA methylation

* **Reason for deprecation**
* This term represents a MF

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 2
- no action needed - genes already annotated to other BPs - see
- http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1921605
- http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1261819
- 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No 

* **Is this term in a subset? (check the AmiGO page for that term)**

No 

* **Any other information**

**Comment by pgaudet** [comment]
@hdrabkin FYI - 2 mouse annotations, no action needed.

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete GO:0060821 inactivation of X chromosome by DNA methylation. The reason for obsoletion is that this represents a molecular function. There are no annotations; this term is not present in any mappings or subsets.

You can comment on the ticket: geneontology/go-ontology#22023

Thanks, Pascale

**Comment by hdrabkin** [comment]
um. I still need to remove the annotations for the 2 mgi except I go to our interface and I can search on  GO:0060821 and get two genes returned, but then going in to remove them I can't find them.

**Comment by ukemi** [comment]
I'll take care of these.

**Comment by hdrabkin** [comment]
I found them;

**Comment by hdrabkin** [comment]
having huge pw issues this am

**Comment by ukemi** [comment]
Done.

**Comment by ukemi** [comment]
No worries @hdrabkin . I got rid of them.

**Comment by pgaudet** [comment]
Thanks!
