### ISSUE TITLE
NTR: [protein-containing complex localization to centriolar satellite]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#22020]
Please provide as much information as you can: 

* **Suggested term label:**
protein-containing complex localization to centriolar satellite

* **Definition (free text)**
A process in which a protein-containing complex is transported to, or maintained at, the centriolar satellite.

* **Reference, in format PMID:#######**
PubMed=27979967

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0031503 protein-containing complex localization

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140706
+name: protein-containing complex localization to centriolar satellite
+namespace: cellular_component
+def: "A protein-containing complex localization by which the complex is transported to, or maintained in, the centriolar satellite." [PMID:27979967]
+is_a: GO:0034629 ! cellular protein-containing complex localization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22020 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-01T05:59:13Z
