### ISSUE TITLE
GO:0048096 chromatin-mediated maintenance of transcription - change parent

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22034]

**Comment by pgaudet** [comment]
It seems odd that the parents are 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/4782928/131325702-f30d3063-757b-4d20-9ac2-85dda7bb6f46.png">


@colinlog @ValWood @RLovering @hattrill

**Comment by colinlog** [comment]
The elongation parent is a (wrong?. I think it is a spill-over from the term that we now called 'co-transcriptional chromatin assembly' or some thing like that, which we worked on at the same time? 

Basically, we did two terms: GO:0140673 that is now called 'co-transcritional ...' and we did GO:0040096 that is about promoter (and enhancer and loop anchor) nucleosomes and that will be the parent of many 'positive regulation of gene expression, epigenetic' MFs. 

The elongation parent should be for GO:0140673 but not for GO:0040096, unless I am mistaken.

**Comment by ValWood** [comment]
Agreed,  but it would be good. to review existing annotations based. on this old parentage. It was a bit confusing, and accounts, for. example, for this inference:
https://github.com/geneontology/go-annotation/issues/3888

**Comment by pgaudet** [comment]
Also, @ValWood suggests in #22089
> chromatin-mediated maintenance of transcription (GO:0048096)
should be a descendent of
chromatin organization?

**Comment by pgaudet** [comment]
This is what I did: 

*  'chromatin-mediated maintenance of transcription': Maintenance of transcription by remodelling of chromatin into an 'open configuration'. Once established, this regulation is mitotically stable and is maintained over many cell divisions. It is also heritable.
* * _removed_ is_a: GO:0045893 ! positive regulation of transcription, DNA-templated
* * _removed_  part_of GO:0006368 ! transcription elongation from RNA polymerase II promoter
* * _kept_ is_a: GO:0045815 ! positive regulation of gene expression, epigenetic

*    'co-transcriptional chromatin reassembly': The reestablishment of chromatin structure that was disrupted upon passage of RNA polymerase II during transcription elongation. This process prevents cryptic intragenic transcription initiation.
* * _added_ is_a: GO:0031497 ! chromatin assembly
* * _added_  part_of GO:0006368 ! transcription elongation from RNA polymerase II promoter
* * _removed_ part_of GO:0006366 ! transcription by RNA polymerase II

Does that see right @colinlog ? 

Thanks, Pascale

**Comment by ValWood** [comment]
It will be good for @colinlog  to confirm,but that was the decisions I remembered.

**Comment by pgaudet** [comment]
Confirmed by @colinlog transcription call

**Comment by ValWood** [comment]
paper was HULC, a histone H2B ubiquitinating complex, modulates heterochromatin independent of histone methylation in fission yeast.
https://www.pombase.org/reference/PMID:17363370
does that sound OK

(not to self, I must have curated with my Google  mail, appears as 'community' fix!)

**Comment by ValWood** [comment]
wrong ticket! deleting comment.
