### ISSUE TITLE
Rhea reactions (mapped to GO) set to OBSOLETE

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#22050]
received via email on 8/26/2021

Dear Harold, Pascale,
 
I’m using summertime to do some cleaning 😉
 
FYI, today I set the status to OBSOLETE for the following reactions
 
1. RHEA:10504       GO:0033778
                RHEA:10504 has been replaced by RHEA:46752 >>>>>> this has already been done.
                EC 1.14.13.95 has been transferred to EC 1.14.14.139   >>>>>> done 8/27/2021   Also added PMIDs to def ref.
               
2. [DONE](https://github.com/geneontology/go-ontology/issues/23472) RHEA:11760       GO:0050565    TWO annotations exists via IMP by UniProt; These need to be removed so term can be obsoleted.
                Not enough experimental evidence to support the reaction.
                6.3.2.27-RXN deleted by Ron Caspi on 2/3/12
                R04357 no more valid
 
3. RHEA:12564       GO:0050184  DONE (#23472
                RHEA:12564 has been replaced by RHEA:46332; This  RHEA:46332 already in use by GO:0102855
                EC 1.3.1.35 has been transferred to EC 1.14.19.22           This is already assigned to GO:0102855 and well as GO:0050184.
Neither GO reaction seems to fit with  RHEA:46332; further analysis /comment required. Skipping
               
4. RHEA:13393       GO:0004516 DONE
                RHEA:13393 has been replaced by RHEA:36163 (EC 6.3.4.21 update) >>>  EC was done; fixed RHEA 8/27/21 and added PMID to def ref
                R-HSA-197186.3 needs to be updated too  >>>   Reactome will be contacteted
 
5. RHEA:13533       GO:0050229    No annotations to this term in Amigo; safe to obsolete.  DONE: #23521
                status set to OBSOLETE
                EC 1.1.1.246 This activity is now known to be catalysed by two enzymes, vestitone reductase (EC 1.1.1.348) and medicarpin synthase (EC 4.2.1.139).  Never suggested rxn are in GO. 

     
Cheers, Anne
 
Additionally sent on 8-27-2021 by Anne

6. RHEA:15441       GO:0004158  DONE: #23472
                This reaction was no correct. The correct reaction is RHEA:30059.  RHEA:30059 is already in use by 
GO:1990663 which correctly mentions fumarate in the reaction to yield succinate.
 GO:0004158 does not. It yields H2O2 + Orotate. (capitalized because autocorrect changes it to 'rotate'
RHEA:15441 IS the correct reaction for GO:0004158
RHEA:15441 has no refs, etc. 
SHould  GO:0004158   be obsoleted? 
 
7. RHEA:15701       GO:0016719 Done in #23098
                This reaction created for EC 1.14.99.30 (carotene 7,8-desaturase)
                EC 1.14.99.30 (carotene 7,8-desaturase) is now EC 1.3.5.6, 9,9′-dicis-zeta-carotene desaturase.
                RHEA:15701 has been replaced by RHEA:30955
                Frame 1.14.99.30-RXN has been deleted by Ron Caspi on 6/15/11
 
8. RHEA:16681       GO:0018660 DONE #23098
                This reaction was created for EC 1.14.13.3
                EC 1.14.13.3 is now EC 1.14.14.9
                RHEA:16681 has been replaced by RHEA:30595; already in use by GO:0052881; 
               
9. **DONE in #23481** RHEA:17189       GO:0050173
                EC 2.7.7.54 (phenylalanine adenylyltransferase). Deleted entry. The activity is part of EC 6.3.2.40, cyclopeptine synthase.
                Frame PHENYLALANINE-ADENYLYLTRANSFERASE-RXN has been deleted by Anamika Kothari on 3/21/13 2:07
 
10. RHEA:17981 GO:0047786     >>>>>> Nothing annotated to this term in Amigo  Done in #23098
                Not enough evidence to support this reaction
                Was created for EC 1.3.1.4, cortisone α-reductase
 
11. **DONE**  RHEA:18713 GO:0047302
                RHEA:18713 has been replaced by RHEA:31663    >>>>>> Changed on 8/27/21
                Update of EC 2.6.1.34   EC was already updated. ; PMID added to def refs
               

________________________________

**Comment by amorgat** [comment]
RHEA:11324	GO:0050347
	RHEA:11324 has been replaced by RHEA:27563 (EC 2.5.1.84)

**Comment by amorgat** [comment]
RHEA:21872	GO:0016275
RHEA:21872 has been replaced by RHEA:48100 (EC 2.1.1.124 deleted)

**Comment by amorgat** [comment]
To check 
**GO:0050600** - EC 1.14.19.24 - RHEA:46396
https://www.enzyme-database.org/query.php?ec=1.14.19.24
**GO:0050601** - EC 1.14.19.5 - RHEA:25852
https://www.enzyme-database.org/query.php?ec=1.14.19.5

The mapping is correct but the definition should be changed (the EC numbers have been updated)

**Comment by amorgat** [comment]
RHEA:20760	**GO:0050056**
RHEA:20760 has been replaced by **RHEA:32635** according to EC 1.14.99.28 update
https://www.enzyme-database.org/query.php?ec=1.14.99.28
EC 1.14.99.28 Transferred entry: linalool 8-monooxygenase. Now EC 1.14.14.84, linalool 8-monooxygenase 
https://www.enzyme-database.org/query.php?ec=1.14.14.84

**Comment by amorgat** [comment]
RHEA:22196 **GO:0016213**
RHEA:22196 (now obsolete) has been replaced by RHEA:47140 (EC 1.14.19.3, Supersedes EC number: 1.14.99.25)

**Comment by amorgat** [comment]
RHEA:22392 **GO:0033751**
RHEA:22392, now obsolete (EC 1.13.11.44 has been deleted by the Enzyme Commission.)

**GO:0033751** (linoleate 8R-lipoxygenase)
Note that you have **GO:0052878** (linoleate 8R-lipoxygenase activity) which is correctly mapped to RHEA:25395

**Comment by amorgat** [comment]
RHEA:22412 **GO:0047671**
RHEA:22412, now obsolete (EC 2.7.7.55 has been deleted by the Enzyme Commission, Transferred entry: 6.3.2.40)

**Comment by amorgat** [comment]
RHEA:22556 **GO:0008924**
**GO:0008924** should be mapped to **RHEA:46012** - EC 1.1.5.4 Malate dehydrogenase (quinone)
RHEA:46012 (S)-malate + a quinone = a quinol + oxaloacetate

**Comment by amorgat** [comment]
RHEA:22632 **GO:0048045**
RHEA:22632, now obsolete. It was created for EC 2.5.1.33, which has been deleted by the Enzyme Commission.
EC 2.5.1.33 was transferred to EC 2.5.1.82 and EC 2.5.1.83

**Comment by amorgat** [comment]
RHEA:23528 **GO:0047370**
RHEA:23528 has been replaced by RHEA:38287
Please update GO:0047370 accordingly

**Comment by amorgat** [comment]
RHEA:21344 **GO:0047152**
RHEA:21344 (now obsolete) has been replaced by RHEA:45204  (update of EC 2.1.1.90) 
Please GO:0047152 accordingly

**Comment by amorgat** [comment]
RHEA:23740 **GO:0047085**
RHEA:23740, now obsolete. It was created for EC 1.14.13.68, which has been deleted by the Enzyme Commission and transferred to EC 1.14.14.37
RHEA:23740 has been replaced by RHEA:50732, one of the three step reaction of EC 1.14.14.37 
EC 1.14.14.37 is mapped to RHEA:18401 (multi-step reaction: RHEA:50724, RHEA:50728 and RHEA:50732)

**Comment by amorgat** [comment]
RHEA:24124 **GO:0004744**
RHEA:24124, now obsolete. It was created for EC 5.2.1.3, which has been deleted by the Enzyme Commission
Deleted entry: retinal isomerase. Now known to be catalysed by a pathway involving EC 1.1.1.300, NADP-retinol dehydrogenase; EC 2.3.1.135, phosphatidylcholine--retinol O-acyltransferase; EC 3.1.1.64, retinoid isomerohydrolase; and EC 1.1.1.315, 11-cis-retinol dehydrogenase.
[EC 5.2.1.3 created 1961, modified 1976, deleted 2011] 

_Anne_: I noticed that **GO:0004744** is used in UniProt
https://www.uniprot.org/uniprot/?query=goa:(%22retinal%20isomerase%20activity%20[4744]%22)
I will send a mail to UniProt curators to updated the corresponding entries

**Comment by amorgat** [comment]
RHEA:24532 **GO:0047119**
RHEA:24532 has been replaced by RHEA:43780
RHEA:24532 (obsolete) was created for EC:1.3.1.52 which has been deleted by the Enzyme Commission and transferred to EC 1.3.8.5
Please update GO:0047119

**Comment by harold** [comment]
Hi, @harold here- this looks intense. I imagine that you intended to @ mention a different Harold. When they arrive, let them know I think they have a tremendous name.

Good luck with everything.

**Comment by amorgat** [comment]
> Hi, @harold here- this looks intense. I imagine that you intended to @ mention a different Harold. When they arrive, let them know I think they have a tremendous name.
> 
> Good luck with everything.

You imagine correctly ;-) Sorry for the noise!

**Comment by hdrabkin** [comment]
Hi @amorgat 
my handle is @hdrabkin, not the 'at symbol harold'

**Comment by amorgat** [comment]
I added PMID:17606922 & PMID:20035867 citations to RHEA:17629
I think you could map RHEA:17629 to GO:0015574 (or GO:0015771)

**Comment by amorgat** [comment]
RHEA:20836 **GO:0000010**
RHEA:20836 (obsolete) has been replaced by RHEA:27794 (EC 2.5.1.30)
RHEA:27794 is mapped to GO:0036422

**Comment by amorgat** [comment]
RHEA:20868 **GO:0004555**
RHEA:20868 (obsolete) has been replaced by RHEA:32675 (EC 3.2.1.28)
RHEA:32675 is mapped to GO:0015927

**Comment by amorgat** [comment]
RHEA:11144 **GO:0047918**
RHEA:11144 (obsolete) has been replaced by RHEA:63800 and RHEA:63804 (EC 5.3.1.18)

**Comment by amorgat** [comment]
RHEA:25864 **GO:0052898**
H2O + N1-acetylspermidine + O2 = 4-acetamidobutanal + H2O2 + propane-1,3-diamine

We initially created  this reaction according to
Federico, R., Ercolini, L., Laurenzi, M. and Angelini, R. Oxidation of acetylpolyamines by maize polyamine oxidase. Phytochemistry 43 (1996)339-341.

A second look at the paper revealed that N1-acetylspermidine was not studied for this reaction. 
If you don't have experimental evidence on your side GO:0052898, I'll obsolete RHEA:25864

**Comment by SuperManu74** [comment]
> 
> 
> **RHEA:21872 GO:0016275**
> RHEA:21872 has been replaced by RHEA:48100 (EC 2.1.1.124 deleted)
> 
> > > > RHEA:48100 already in use for GO:0035241 protein-arginine omega-N monomethyltransferase activity
> 
> Should GO:0016275 be merged into GO:0035241?
> 
> > I guess
> 
> **RHEA:14897 GO:0033770**
> 
> > > > > 1.14.13.86 was deleted and 'replaced' with  1.14.14.87.
> > > > > So are BOTH incorrect?   Is RHEA:14897 now incorrect also?  Is GO:0033770 incorrect? 3 annotations all via UniProt.
> 
> > Sorry Harold I made a typo in my original comment.
> > RHEA:14897 was created for EC 1.14.13.86, that has now been deleted with the comment at IUBMB: "This enzyme was classified on the basis of an incorrect reaction. The activity is covered by EC 1.14.14.87, 2-hydroxyisoflavanone synthase"
> > (see https://www.enzyme-database.org/query.php?ec=1.14.13.86)
> 
> > GO:0033770 is incorrect, I will send a mail to the UniProt curators
> > Hi @amorgat ; to the new EC has two reactions and two rheas. Are these separate or sequential? If the latter then do we need a RHEA for the overall reaction.  If the reaction in GO is defined is incorrect, I would opt to obsolete the term
> 
> @hdrabkin, EC 1.14.14.87 has a borad name "2-hydroxyisoflavanone synthase" but only describes 2 separate reactions (https://www.enzyme-database.org/query.php?ec=1.14.14.87)
> [31723] liquiritigenin + O2 + reduced [NADPH—hemoprotein reductase] = (2R,3S)-2,4',7-trihydroxyisoflavanone + H+ + H2O + oxidized [NADPH—hemoprotein reductase]
> [35487] (2S)-naringenin + O2 + reduced [NADPH—hemoprotein reductase] = 2-hydroxy-2,3-dihydrogenistein + H+ + H2O + oxidized [NADPH—hemoprotein reductase]
> I would suggest that you obsolete GO:0033770 and create 2 new terms to annotate both reactions.
> Emmanuel Boutet (UniProt curator) removed the annotations with GO:0033770. He currently replaced them by GO:0016709.
Indeed, as I did not find a precise term, I used a parent one to describe the protein function ;-)

**Comment by pgaudet** [comment]
@hdrabkin 
To answer to the comment above https://github.com/geneontology/go-ontology/issues/22050#issuecomment-919859087 
RHEA:22392 GO:0033751

We should obsolete
GO:0033751 linoleate 8R-lipoxygenase - no annotations,  term is obsoleted by both EC and RHEA.

**Comment by hdrabkin** [comment]
GO:0033751 was obsoleted.
