### ISSUE TITLE
Make sure unintended inferences don't appear in go-gaf (and maybe go-lego)

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#22051]
For go-gaf, we can just merge and turn off reasoning. Or, we could add a check that no additional GO subsumptions are found after classifying go-gaf.

**Comment by pgaudet** [comment]
go-gaf imports go-lego and the reasoner is ran over the whole thing, and go-lego has not been updated in a while

**Comment by pgaudet** [comment]
* this check will make the pipeline fail when external ontologies add additional subsumptions

**Comment by pgaudet** [comment]
This was coming from a rare problem. We will close for now, and open another ticket if this becomes more pressing.
