### ISSUE TITLE
Missing parent: GO:0000220 vacuolar proton-transporting V-type ATPase, V0 domain

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#22063]
GO:0000220 vacuolar proton-transporting V-type ATPase, V0 domain

should have part_of parent

GO:0016471 vacuolar proton-transporting V-type ATPase complex

All other v-atpase domains have this type of relationship, see eg sister term GO:0000221 vacuolar proton-transporting V-type ATPase, V1 domain.

**Comment by pgaudet** [comment]
Did we not say that we would. not include subcomplexes in GO anymore ?

**Comment by bmeldal** [comment]
Correct, but these terms all predate my time by many years. I'm only asking for the one missing relationship to be added so it's the same as for all other proton-transporting V-type ATPases, all of them already have the V0 and V1 domain children terms. 

![image](https://user-images.githubusercontent.com/10517124/131478594-b26f3ca8-9686-41d2-9155-f52d37d0a81a.png)
