### ISSUE TITLE
Obsolete GO:0001301 progressive alteration of chromatin involved in cell aging and children? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22061]
GO:0001301 progressive alteration of chromatin involved in cell aging
and children 
GO:0007580 extrachromosomal circular DNA accumulation involved in cell aging
GO:0034652 extrachromosomal circular DNA localization involved in cell aging

look like phnoetypes
2 SGD annotations

**Comment by pgaudet** [comment]
@srengel Would you be OK with obsoletion of these terms ? 

Looking at a newer paper, PMID:33979898, it seems like an annotation to 'GO:0043007 maintenance of rDNA' would capture the observation? 

@colinlog thoughts? If i recall correctly, we have discussed this before. 

Thanks, Pascale

**Comment by srengel** [comment]
Hi @pgaudet we're fine with these terms being obsoleted.  thank you!
