### ISSUE TITLE
NTR: [release of heterochromatin tethering 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22088]
Please provide as much information as you can: 

* **Suggested term label:**
release of heterochromatin-nuclear membrane attachment for mitosis

* **Definition (free text)**
A process in which the heterochromatin is detached from nuclear membrane are detached in preparation for mitosis. The process is relatively uncharacterized, but involves the Vps4 ATPase and the ESCRT III complex   ~before cells enter into mitosis.~

* **Reference, in format PMID:#######**
PMID:3210938

* **Gene product name and ID to be annotated to this term**
Vps4,vps24,did4,cmp7

* **Parent term(s)**

GO:0140014  mitotic nuclear division aka mitosis 
(this is part of the preparation for division, heterochromatin detaches from the nuclear envelope, I think we should model as part of mitosis)
The definition of mitosis is fairly loose and involved chromosome reorganization:
A mitotic cell cycle process comprising the steps by which the nucleus of a eukaryotic cell divides; the process involves condensation of chromosomal DNA into a highly compacted form. Canonically, mitosis produces two daughter nuclei whose chromosome complement is identical to that of the mother cell.

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

@snezhkaoliferenko

**Comment by pgaudet** [comment]
Do we know which MFs mediate this process? This sounds too vague

Also, are you sure this is the right paper? PMID:3210938??

**Comment by ValWood** [comment]
correct PMID,
we don't know precisely how this happens yet. It involves the Vpa4 ATPase and ESCRT, but the precise mechanism is not known.
 
[ESCRT-III/Vps4 Controls Heterochromatin-Nuclear Envelope Attachments.](https://pubmed.ncbi.nlm.nih.gov/32109380/)
Pieper GH, Sprenger S, Teis D, Oliferenko S.
Dev Cell. 2020 Apr 6;53(1):27-41.e6. doi: 10.1016/j.devcel.2020.01.028. Epub 2020 Feb 27.
PMID: 32109380

**Comment by ValWood** [comment]
Closing until we know more about the mechanism
