### ISSUE TITLE
parentage: suppression by symbiont of host innate immune response

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#22091]
shouldn't 
suppression by symbiont of host innate immune response GO:0052170

be a parent of 
effector-mediated suppression of host innate immune response GO:0140403

?

**Comment by Antonialock** [comment]
![image](https://user-images.githubusercontent.com/12727506/131744229-7c4c5ccc-a9c9-49ad-b3cf-c63ef0b4cc26.png)

**Comment by pgaudet** [comment]
I think we concluded that suppression of the host immune response can occur without 'effectors'  - although I cannot find examples in children terms. 

I'll add this to a multiorg call for input by other members of the group.

**Comment by pgaudet** [comment]
Added missing parent, thanks for pointing that out
