### ISSUE TITLE
new templates requested

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22090]
for 
i) definition updates
(the definition update could be structured as genus differentia with advice on how to create a good definition as per @cmungall blog post)

ii) missing superclass

**Comment by pgaudet** [comment]
Definition update template: 
https://github.com/geneontology/go-ontology/issues/new?assignees=&labels=textual+definition&template=feature_request.md&title=Textual+definition+update%3A+


Missing superclass: https://github.com/geneontology/go-ontology/issues/new?assignees=&labels=missing+parentage&template=missing-superclass.md&title=


Please let me know if if these can be improved.  or you have other suggestions. 

Thanks, Pascale
