### ISSUE TITLE
glutathione reductases

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22101]
I can't fully disentangle
 this but at least some of these terms seem the same, or have missing parents:

<img width="787" alt="Screenshot 2021-09-03 at 18 00 26" src="https://user-images.githubusercontent.com/7359272/132042091-5e1b9e61-1387-4945-8993-cceb74de795b.png">

**Comment by ValWood** [comment]
For example:
GO:0015038   glutathione disulfide oxidoreductase activity
Catalysis of the reaction: 2 glutathione + electron acceptor = glutathione disulfide + electron donor.

is_a
GO:0015035    protein-disulfide reductase activity


so presumably it is also a
GO:0019153    protein-disulfide reductase (glutathione) activity
Catalysis of the reaction: 2 glutathione + protein-disulfide = oxidized glutathione + protein-dithiol.

and
GO:0004362    glutathione-disulfide reductase (NADPH) activity
Definition (GO:0004362 GONUTS page)
Catalysis of the reaction: 2 glutathione + NADP+ = glutathione disulfide + NADPH + H+.

does not mention protein in its def, BUT
GO:0047134   protein-disulfide reductase (NAD(P)) activity
Definition (GO:0047134 GONUTS page)
Catalysis of the reaction: protein-dithiol + NAD(P)+ = protein-disulfide + NAD(P)H + H+.\

its parent

I was trying to evaluate some mapping but it isn't possible.

Also they all have bzillions of synonyms, related, narrow , broad. I even saw one where the exact synonym was itself.....

**Comment by pgaudet** [comment]
Looks like some terms could be merged? I thought I looked at that recently, I cannot find the ticket. 
Note that I moved protein-disulfide reductase (glutathione) activity (GO:0019153) under protein-disulfide reductase activity (GO:0015035) as requested in #21148

Thanks, Pascale

**Comment by sjm41** [comment]
I think these terms and relations are OK now, following #23411, #25458, #25459, #25460, #25461, #25462, #25498 (and possibly other tickets).

QuickGO view of the same terms highlighted above now looks like this:
![Screenshot 2023-06-21 at 16 58 38](https://github.com/geneontology/go-ontology/assets/16306861/77ad860d-8465-4bf3-98a0-becc40882cca)

**Comment by sjm41** [comment]
@pgaudet  Only issue I see is that GO:0004791 thioredoxin-disulfide reductase (NADP) activity lost its "is a GO:0047134 (protein-disulfide reductase (NAD(P)) activity)" on 2023-06-13.  Not sure why?  I think that should be reinstated.

GO:0047134
protein-disulfide reductase (NAD(P)) activity
Catalysis of the reaction: protein-dithiol + NAD(P)+ = protein-disulfide + NAD(P)H + H+.

GO:0004791
thioredoxin-disulfide reductase (NADP) activity
Catalysis of the reaction: thioredoxin-dithiol + NADP+ = thioredoxin-disulfide + H+ + NADPH.

**Comment by ValWood** [comment]
I think I  can finish this one off.
