### ISSUE TITLE
synonyms for  GO:0140588    chromatin looping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22109]
GO:0140588    chromatin looping 
add exact synonym  DNA loop extrusion PMID:34309513.
add related  synonym "DNA looping"  (needs to. be related if we have used in other contexts)

**Comment by pgaudet** [comment]
Added the synonyms. I've also added a comment, "comment: To describe the molecular function associated with chromatin looping, consider 'chromatin extrusion motor activity'; GO:0140584.". 


Thanks, Pascale

**Comment by ValWood** [comment]
Hi @colinlog  
I am using this term for PMID:35333350
but the term name sounds more like a phenotype (looping) than a process.

Do you think it should be named "chromatin loop formation"
