### ISSUE TITLE
make "cellular process" not for direct annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22123]
Currently 451/2.8 million in Amigo.
Most are IEA, only a few EXP.
<img width="244" alt="Screenshot 2021-09-09 at 12 18 09" src="https://user-images.githubusercontent.com/7359272/132676811-087d9217-d2af-4643-834a-c693fc19eb99.png">

**Comment by pgaudet** [comment]
Most annotations are from MGI @hdrabkin do you want to check these ?

**Comment by pgaudet** [comment]
Also added 'cellular metabolic process' (6 EXP) and 'regulation of cellular metabolic process', 
positive regulation of cellular metabolic process (2 EXP RGD),  negative regulation of cellular metabolic process (2 EXP UniProt - removed, 1 EXP RGD)
@gthayman

**Comment by pgaudet** [comment]
+ regulation of cellular process (2 EXP UniProt, changed), 
+ positive regulation of cellular process (0 EXP)
+ negative regulation of cellular process  (3 EXP) - 2 EcoCyc @dsiegele 1 RGD @gthayman 


Thanks, Pascale

**Comment by hdrabkin** [comment]
Hi @pgaudet 
Confused: you say 'most' 
1 which term(s) exactly (it's easier for me to go in with the GO ID
2 but 450 are IEA (?). and you list UniProt and RGD.   
 Can you please clarify here; Thanks

**Comment by hdrabkin** [comment]
So I see 24 genes with GO:0009987, most are ISO from loads; I can go through these and remove.

**Comment by pgaudet** [comment]
You can find annotations to 'do not annotate' terms in the reports: 
http://snapshot.geneontology.org/reports/mgi-report.html#gorule-0000008

These terms should show up at the next run of snapshot. 

Thanks

**Comment by gthayman** [comment]
3 RGD annotations changed.

**Comment by hdrabkin** [comment]
The remaining MGI  annotations via ISO will disappear when RGD and GOA release corrected annotations
