### ISSUE TITLE
GO:0044291 cell-cell contact zone problematic for Dicty

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#22122]
I have papers, one of them PMID: 26801966 where for example a myosin I localizes to cell-cell contacts when they make contact in culture or in chemotaxis. 

However, GO:0044291 cell-cell contact zone is a child of GO:0005911 cell-cell junction with the def: A cell junction that forms a connection between two or more cells in a multicellular organism; excludes direct cytoplasmic intercellular bridges, such as ring canals in insects.

It's true that Dicty doesn't have classical cell-cell junctions but they still make good contacts through surface molecules such as glycoproteins. 

I would like to have a valid CC term to describe cell-cell contacts in Dicty. Is that possible? Thanks!

**Comment by pgaudet** [comment]
Hi @pfey03 

Would GO:0098609  cell-cell adhesion work?

**Comment by pgaudet** [comment]
This term 'GO:0044291 cell-cell contact zone' is a bit weird - it's a NIF term, I only find 7 mentions in PubMed, and it's used to annotate papers that talk about cell junctions anyway, ie there are other terms that these proteins could be annotated to.

**Comment by pgaudet** [comment]
The parent 'GO:0005911 cell-cell junction' mentions multicellular organisms, but cites papers that describe adherens junctions. Maybe we can just make that term more general by fixing the definition? 

What do you think? 

@mah11 @RLovering you have your initials associated with this term; any opinion on this one?

**Comment by mah11** [comment]
I think GO:0005911 is meant to be generic enough to group terms for any & all junctions between cells. My involvement was literally 20 years ago, so no, I don't think I have anything more specific to contribute now.

**Comment by pgaudet** [comment]
thanks @mah11

**Comment by pfey03** [comment]
@pgaudet, in Dicty users talk about cell-cell contacts but making cell-cell junction more general should work, maybe move cell-cell-contact (zone) as related synonym?

**Comment by pgaudet** [comment]
WRT cell-cell contact zone - does anyone know why we need a grouping term for 
'intercalated disc' and 'peg and socket contact'? 

@ukemi @vanaukenk @cmungall

**Comment by pgaudet** [comment]
Hi @pfey03 

I fixed the def of cell-cell junction to 

A cell junction that forms a connection between two or more cells **of an organism;** excludes direct cytoplasmic intercellular bridges, such as ring canals in insects." [GOC:aruk, GOC:bc, GOC:dgh, GOC:hb, GOC:mah, PMID:21422226, PMID:28096264]

and added synonyms:
+synonym: "cell-cell contact region" BROAD []
+synonym: "cell-cell contact zone" BROAD []

**Comment by pfey03** [comment]
Thanks @Pascale, we have 15 annotations to cell-cell contact zone so I re-annotate those then to cell cell junction
