### ISSUE TITLE
NTR: nucleosome remodeling activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22129]
Transcription refactoring discussion @colinlog @ValWood @hattrill @RLovering 

as a parent of 'ATP-dependent chromatin remodeler activity '

* **Suggested term label:**

Broad synonym: 

* **Definition (free text)**
An activity, that modulates the contacts between histones and DNA, resulting in a change in chromosome architecture within the nucleosomal array, leading to chromatin remodeling.  

* **Reference, in format PMID:#######**

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
 'ATP-dependent chromatin remodeler activity ' should be relabeled 'ATP-dependent nuclesome remodeler activity '

**Comment by pgaudet** [comment]
I think this is covered by the histone chaperone terms see #22290  #22126

I will add 'nucleosome remodeling activity' as a synonym for GO:0140713  histone chaperone atcivity

**Comment by pgaudet** [comment]
@colinlog @ValWood @hattrill @RLovering 
FYI

**Comment by ValWood** [comment]
but it was suggested as a parent for
 'ATP-dependent chromatin remodeler activity '

Should it be "related for both (if required at all)?

**Comment by pgaudet** [comment]
Ah good, point,, I can also add the synonym to 'ATP-dependent histone chaperone activity'
