### ISSUE TITLE
Change labels   DNA replication-(in)dependent nucleosome organization to chromatin xx

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22130]
* GO:0034723 DNA replication-dependent nucleosome organization -> change to  DNA replication-dependent **chromatin** organization
*  GO:0006335 DNA replication-dependent nucleosome assembly  -> change to  DNA replication-dependent **chromatin** assembly
*  GO:0034725 DNA replication-dependent nucleosome disassembly   -> change to  DNA replication-dependent **chromatin** disassembly

*  GO:0034724 DNA replication-independent nucleosome organization -> change to DNA replication-independent **chromatin** organization
*  GO:0006336 DNA replication-independent nucleosome assembly -> change to DNA replication-independent **chromatin** assembly
*  GO:0034726 DNA replication-independent nucleosome disassembly  -> change to DNA replication-independent **chromatin** disassembly

+ move under chromatin organization (and assembly/disassembly)

**Comment by pgaudet** [comment]
Question @colinlog @hattrill @ValWood @RLovering 

DNA replication-**independent** nucleosome (chromatin) organization (+ assembly): is this really different from the parent "chromatin organization"? annotations are here: https://docs.google.com/spreadsheets/d/1AgDnuZt6ARiwy6LXb4unTFL4684H7BloJqgB-_0UL-Y/edit#gid=0

There are
*  ~ 30 annotations to  DNA replication-independent nucleosome organization
* 6 to DNA replication-independent nucleosome assembly. 
* 0 to DNA replication-independent nucleosome disassembly (paper cited for the term is PMID:17510629 and annotated to DNA replication-independent nucleosome assembly by PomBase @ValWood 


Maybe these should be obsoleted?

**Comment by ValWood** [comment]
Agreed, a  lot of these were a consequence of not having the correct MF terms.

**Comment by pgaudet** [comment]
Opened new ticket to deal with GO:0034724 DNA replication-independent nucleosome organization and GO:0006336 DNA replication-independent nucleosome assembly


#22135
