### ISSUE TITLE
NTR: histone H2B conserved C-terminal lysine ubiquitin ligase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22138]
As the modifications will move from BP to MF, I need an MF term to describe
the activity corresponding to this process:

GO:0071894    histone H2B conserved C-terminal lysine ubiquitination
Definition
A histone ubiquitination process in which a ubiquitin monomer is added to a conserved lysine residue in the C-terminus of histone H2B. The conserved lysine residue is K119 in fission yeast, K123 in budding yeast, or K120 in mammals.

histone H2B conserved C-terminal lysine ubiquitin ligase
standard def,
here is one reference PMID:17363370

**Comment by pgaudet** [comment]
We need to review annotations - I dont see any ubi ligase annotated, so we need to decide where to rehouse the existing annotations https://docs.google.com/spreadsheets/d/1RWOBUXZSc8FUmASFsBQ03XE1k73Wm9ypFmiB4ivsVgQ/edit#gid=0

**Comment by ValWood** [comment]
Quite a lot of these are ligases that will go to the new  MF term.
 DTX3L, ring finger protein 8, E3 ubiquitin-protein ligase BRE1A &B,ring finger protein 40
(and the associated conjugating enzymes).

Others are scaffolds for these complexes.

Some appear to be indirect phenotypes, and most likely already have appropriate annotation to describe a role in heterochromatin assembly or similar..= The process therm that I used which probably applies to most of these is

GO:0048096 (chromatin-mediated maintenance of transcription)
which was recently renamed to 
GO:0045815    epigenetic maintenance of chromatin in transcription-competent conformation

but I don't know if this is the correct term here.

this process  correlate with increased RNA polymerase II levels at repeat elements embedded within heterochromatin domains causing heterochromatic derepression. 
@colinlog  is this the correct process for this modification?

**Comment by colinlog** [comment]
No, GO:0045815 is the euchromatin term that will describe the H3K36me3 (and
in some instance H4K20me and H3K79me2/3 regions) that are transcribed. Also
FACT (SSRP1, SPT16) and PAF1 (BRE1 CTR9 PAF1, ... )will belong there.
For "this process correlate with increased RNA polymerase II levels at
repeat elements embedded within heterochromatin domains causing
heterochromatic derepression" the RITS complex and others will link to
HP1/SWI6 GO: GO:0031507heterochromatin assembly. Sometimes the H3K9me2/3
and sometimes H3K27me/23 types will be involved. There may be one MF that
contributes to both GO"0031507 and GO:0048096, but the latter is definitely
a euchromatin process that correlates with the active (H3K27ac) and latent
(H3K4me1) transcription marks. Whenever you have H3K36me3 marks in the
transcribed region, you also have the H3K4me3 and H2BK123ubi marks at the
then active promoters, together with the H2A.Z variant, in varying
proportions.  At those regions also H3.3 variant is found. And, at these
promoters the 4 MFs we will create for SNF2-type ATPase enzyme complexes
operate, together with many readers and writers of acetylated histones of
which a select set of these protein complexes harbour histone chaperone
RBBP4/7 also known as RBAP46/48 or MSI1 in plants and in S.c and S.p HAT2.
Those two (RBBP4 and RBBP7) contribute to GO:0048096 (euchromatin) and to
GO:0031507 (heterochromatin). They are parts of many complexes by virtue of
binding nucleosomes. They contribute to both the coTF dbTF coactivator and
co-repressor MF, from different complexes.

Structurally, "histone H4 adopts a different conformation when interacting
with RbAp46 than it does in either the nucleosome or in the complex with
ASF1, another histone chaperone. Our structural and biochemical results
suggest that when a histone H3/H4 dimer (or tetramer) binds to RbAp46 or
RbAp48, helix 1 of histone H4 unfolds to interact with the histone
chaperone." from PMID:*PubMed*: 18571423
<https://www.rcsb.org/search?q=rcsb_pubmed_container_identifiers.pubmed_id:18571423>
.

**Comment by ValWood** [comment]
So what is the term that should be used? All of my annotations to this  term must be wrong. I thought I checked these to the revised term but they must have been incorrect to begin with, or, the term has changed in meaning?

This is what I have currently:
https://www.pombase.org/results/from/id/50f32fbc-85ec-4bbe-82cc-8c7c4e62b96f
Is it just HULC that need to move?

**Comment by colinlog** [comment]
That list if very fine! All promoter activities. We will add many more.

**Comment by ValWood** [comment]
OK I thought you were saying I had the wrong term here! OK! Let me know which other complexes should definitely be annotated to this term. I can compile the list of  complex->process and check it with the Term Matrix.

**Comment by ValWood** [comment]
Can we add these? Once we have the MFs we can move the existing BP annotations.
Not so many.

**Comment by pgaudet** [comment]
NTR: histone ubiquitin ligase activity (H3-K14 specific)
def: "Catalysis of the transfer of a ubiquitin molecule to a histone 2B at the lysine-14 residue. 
PMID:34010645
PMID:31468675

**Comment by pgaudet** [comment]
Grouping term: 
+[Term]
+id: GO:0140852
+name: histone ubiquitin ligase activity
+namespace: molecular_function
+def: "Catalysis of the transfer of ubiquitin to a histone substrate." [GOC:curators]
+is_a: GO:0061630 ! ubiquitin protein ligase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22138 xsd:anyURI
+created_by: pg
+creation_date: 2022-06-13T10:38:05Z



+id: GO:0140851
+name: histone ubiquitin ligase activity (H3-K14 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of a ubiquitin molecule to histone 3 at the lysine-14 residue." [PMID:31468675, PMID:34010645]
+is_a: GO:0140852 ! histone ubiquitin ligase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22138 xsd:anyURI
+created_by: pg
+creation_date: 2022-06-13T10:34:13Z
+

- [ ] Need to create the terms for H2A.

**Comment by pgaudet** [comment]
- [ ] histone H2A-K119 monoubiquitination
- [ ] histone H2A K63-linked ubiquitination
- [ ] histone H2A-K15 ubiquitination
- [ ] histone H2A-K13 ubiquitination

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140862
+name: histone ubiquitin ligase activity (H2A-K119 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of a ubiquitin molecule to histone 2 at the lysine-119 residue." [PMID:22844243, PMID:25470042]
+is_a: GO:0140852 ! histone ubiquitin ligase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22138 xsd:anyURI
+created_by: pg
+creation_date: 2022-06-20T12:45:05Z

**Comment by ValWood** [comment]
I believe this is the same as 
https://www.ebi.ac.uk/QuickGO/term/GO:0140850

(check the def)
Perhaps it is clearer to call it 
https://www.ebi.ac.uk/QuickGO/term/GO:0140850

We need to know if there are other numbering variations, maybe they are only at the end I am not surer. It also depends if people have used the convention of counting  with he methionine removed.

**Comment by pgaudet** [comment]
@ValWood 
> I believe this is the same as
https://www.ebi.ac.uk/QuickGO/term/GO:0140850


It's H2B versus H2A... a bit confusing indeed

**Comment by ValWood** [comment]
right! should the same naming convention be used, or is 2b more conserved in. numbering?
