### ISSUE TITLE
chromatin-mediated maintenance of transcription (GO:0048096)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22137]
add synonym
maintenance of transcriptionally poised chromatin

(@colinlog @pgaudet  do we prefer this as a label? it  gets the point across better that this is maintaining the chromatin and the *ability* to transcribe.)

**Comment by pgaudet** [comment]
@ValWood Can you find the paper than mentions that? Otherwise let's maybe close until we find the correct formulation and correct term this should be added to?

**Comment by ValWood** [comment]
It was the one I put in the other ticket:
paper was HULC, a histone H2B ubiquitinating complex, modulates heterochromatin independent of histone methylation in fission yeast.
https://www.pombase.org/reference/PMID:17363370

**Comment by pgaudet** [comment]
Transcription call @colinlog @ValWood @RLovering @hattrill 
- Note that 'chromatin-mediated maintenance of transcription' has been merged into 'epigenetic maintenance of chromatin in transcription-competent conformation' 
- Helen: paper https://link.springer.com/article/10.1007%2Fs00018-021-03903-w
- people use 'primed' and 'poised'
- “In addition to the ‘**primed**’ and active states, enhancers can also reside in a ‘**poised**’ state exhibiting both H3K4me1 and H3 lysine 27 trimethylation (H3K27me3) that is associated with Polycomb repressive complexes” 
- Colin: poised refers to chromatin structure in a bivalent state (see PMC4197577), "Poised (bivalent) chromatin is defined by the simultaneous presence of histone modifications associated with both gene activation and repression. " 

This terminology is a bit confusing, especially for processes, so we will not add these for now, and not on these terms. This may be more appropriate for other terms.
