### ISSUE TITLE
Fix labels & definitions: GO:0034724 DNA replication-independent nucleosome organization & GO:0006336 DNA replication-independent nucleosome assembly  (was:obsoletion notice)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22135]
Please provide as much information as you can:

* **GO term ID and Label**
* GO:0034724 DNA replication-independent nucleosome organization
* GO:0006336 DNA replication-independent nucleosome assembly
* 
* **Reason for deprecation**
These represent chromatin organization or remodeling

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

*  GO:0006325 chromatin organization
* GO:0031497 chromatin assembly
* GO:0006338 chromatin remodeling
* GO:0140713 histone chaperone activity

* **Are there annotations to this term?**
- How many EXP: 37 
- https://docs.google.com/spreadsheets/d/1AgDnuZt6ARiwy6LXb4unTFL4684H7BloJqgB-_0UL-Y/edit#gid=0

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by pgaudet** [comment]
Transcription call - we dont want to obsolete this anymore . there is a way to define the pathway in a positive manner.

**Comment by hattrill** [comment]
This seems an interesting review - [DNA Double Strand Break Repair and Its Control by Nucleosome Remodeling](https://pubmed.ncbi.nlm.nih.gov/35096025/)  - it's mainly about remodeling during repair, but has a nice classification and description of the activities contribute to the processes described.

**Comment by pgaudet** [comment]
Transcription call @colinlog @ValWood @hattrill 

- revert labels back to 'nucleosome'  - we thought "nucleosomes" should only be in MFs, but after further checks nucleosome assembly really is a process.

**Comment by pgaudet** [comment]
useful review: 
https://www.nature.com/articles/nrm.2016.159.pdf

<img width="724" alt="image" src="https://user-images.githubusercontent.com/4782928/157891482-08410d3b-04b7-4220-b5f8-9f9e8163153e.png">

**Comment by ValWood** [comment]
so do you now plan to keep
"DNA replication-independent chromatin organization"?
it seems an odd term (defining by what it is not).
If it is kept, every term that is NOT replication dependent would need to go under here.
Should we not merge the independent term into the parent (I think that is what was initially proposed during discussions)

**Comment by colinlog** [comment]
'Replication dependent' labels could be made molecularly unambiguous as to the end of replication (W-phase / G2M) and replicated chromsome 'maturation' by changing the label to 'Replication fork associated ... ' where ... is assembly / modification /

**Comment by pgaudet** [comment]
Merge: 

'DNA replication-independent chromatin organization' -> chromatin organization 
'DNA replication-independent chromatin assembly' -> chromatin assembly

**Comment by pgaudet** [comment]
Merge     GO:0034723  DNA replication-dependent chromatin organization (no direct annotations) into child 
GO:0006335 DNA replication-dependent chromatin assembly

**Comment by pgaudet** [comment]
Merge GO:0031497 chromatin assembly into 
[GO:0006325 chromatin organization](http://amigo.geneontology.org/amigo/term/GO:0006325#display-lineage-tab)
