### ISSUE TITLE
Question about 'epigenetic reader"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22136]
https://www.ebi.ac.uk/QuickGO/term/GO:0140566

This term has the parent "transcription regulator activity"
but if a  heterochromatin is the 'default state' these are not all directly regulating transcription are they?
@colinlog @pgaudet @RLovering 
I would not call the HP domain protein swi6 a "transcription regulator activity"?

**Comment by colinlog** [comment]
I would disasgree with hweterochromatin being 'the default state'.
Unmodified chromatin (nucleosomes without heterochromatin nor euchromatin marks) would be the 'default'. But even that, is not the 'default' as often more than 50% of a genome (55% in human) is potentially transcribed and thus involved in co-transcriptional chromatin asembly (H3K36me3, H3K79me, H4K20me1).  

This being said, yes, some heterochromatin structures are actively used for gene transcription repression, but not all. For example s peri-centric and sub-telomeric hetrochromatin that are repressive for transcription but that do not in fact harbour genes.

Still HP1 (S.p. Swi6) can have the function of co-repressor (GO:0003714) !!!! So it does has transcriptional regulator activity.

But, let's imagine a protein that is part of heterochromatin structure but never involved in transcription regulation. Can't we give it as activity 'heterrochromatin assembly', even though it does not appear to be important for heterochromatin assembly that leads to transcription regulation? Actually, I do not know of such an example, although perhaps the human DNA methylases DNMT1 and DNMT3A/B are like that? They methylate the entire genome (except the few percent of promoters and enhancers) and in many places there is no obvious regulatory function except to signal that this part of a chromosome IS NOT an enhancer and nor a promoter. The DNA de-methylases (TET enzymes) oppose DNA methylases at promoters and enhancers and TET enzymes are therefore transcription regulators without a doubt. But what about the DNA methylases? I would put them in [transcription regulators, epigenetic] even though they appear are only rarely subject to targeting by transcription factors.

**Comment by ValWood** [comment]
OK, that sounds fine, I just wanted to check.
I guess we will need a term for histone readers that are not epigenetic though?

**Comment by ValWood** [comment]
probably I didn't mean 'default' here. 
But I thought you said that most DNA would be heterochromatic in the absence of a mechanism to remove the heterochromatin (i.e. transcription always needs to be activated). Maybe I misinterpreted.

**Comment by colinlog** [comment]
>Val: 
> OK, that sounds fine, I just wanted to check.
> I guess we will need a term for histone readers that are not epigenetic though?

Well it is always 'epigenetic marking' if a nucleosomal histone is modified covalently, but it may be for DNA repair or DNA recombination or for signalling assembly status, rather than being transcriptional regulation. So epigenetic is not always about transcription, although much of it is...

**Comment by ValWood** [comment]
so, the definition is too narrow?
GO:0140566    JSON
Definition (GO:0140566 GONUTS page)
A transcription regulator that recognizes epigenetic marks such as methylated cytosines in CpG islands and modified histones, and modulates the accessibility of cis-regulatory regions to the transcription machinery. PMID:11498575 PMID:25688442 PMID:31082667 PMID:32260176

**Comment by pgaudet** [comment]
decision on transcription call: move under 'adaptor activity'

**Comment by pgaudet** [comment]
@ValWood @colinlog @hattrill 
Would 'chromatin-protein adaptor' be the right parent? The binding activity of a molecule that brings together a protein or a protein complex with a nucleosome, to establish or maintain the chromatin localization of the protein, or protein complex.

Given that epigenetic reader def is  'A transcription regulator that recognizes epigenetic marks such as methylated cytosines in CpG islands and modified histones, and modulates the accessibility of cis-regulatory regions to the transcription machinery.' 

Thanks, Pascale

**Comment by ValWood** [comment]
I suggest we  revise from "epegentic reader to 'histone reader'
I don't think they are all epigenetic?
For instance,  histone readers for DNA repair of chromatin biorientation/segregation activities?

We already decided on the call that histone readers are not only transcription regulators

How is this for a more generic version?

 'A histone adaptor activity ~transcription regulator~ that recognizes ~marks~ histone marks  
 (modifications) ~such as methylated cytosines in CpG islands and modified histones~, ~and modulates the accessibility of cis-regulatory regions to the transcription machinery~ in order to recruit additional chromatin-associated proteins.'

- I'm trying to make this process agnostic
- this change means this term is unsuitable for CpG island readers, is that a problem? I don't know what these consist of

**Comment by ValWood** [comment]
Another issue here to discuss next time.
https://github.com/pombase/canto/issues/2498
Although readers do act as adaptors, the 'activity' of acting as a reader isn't an adaptor (the adapting is what it does when it  recruits other chromatin components to the histone.

**Comment by pgaudet** [comment]
Decision is to change term label to 'histone reader' @colinlog @ValWood 
and change def to "A chromatin adaptor that recognizes specific forms of histones, either modified by a post-translational modification, or the unmodified form. Histone readers have roles in many processes, including in centromere function or in modulating the accessibility of cis-regulatory regions to the transcription machinery."

**Comment by ValWood** [comment]
A nice reference for the new def:

"H3K9me3 creates binding sites for HP1 family proteins Swi6 and Chp2, which in turn recruit diverse proteins to regulate transcription, recombination, and other cellular processes, such as chromosome segregation and mating-type switching"
review PMID: 34726351 
Leaving histone unturned for epigenetic inheritance
Chun-Min Shan*, Yimeng Fang and Songtao Jia

**Comment by pgaudet** [comment]
Add relations to histone reader activity: 

+relationship: has_part GO:0042393 ! histone binding
+relationship: occurs_in GO:0000786 ! nucleosome

**Comment by pgaudet** [comment]
GO:0006338 chromatin-protein adaptor activity
add part_of GO:0006338 chromatin remodeling

**Comment by ValWood** [comment]
Is this always true? Chromatin adaptors  (i.e things which recruit to chromatin) seems to be broader than just chromatin remodelling? could be other aspects of chromatin organization?

**Comment by colinlog** [comment]
You are correct and we had decided to merge with chromatin organisation. It
would appear that we do not really need remodelling as it is most likely a
synonym of organisation, hence the merge. We can discuss this further.
Right now we are reviewing the 'regulation of histone modification'...

**Comment by pgaudet** [comment]
Changed part_of GO:0006338 chromatin remodeling to part_of part_of GO:0006325 chromatin organization
