### ISSUE TITLE
NTR: serine-tRNA ligase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22145]
* **Suggested term label:**
serine-tRNA ligase complex

* **Definition (free text)**
A heterodimeric enzyme complex that catalyzes the ligation of serine to tRNA(Ser), forming L-seryl-tRNA(Ser). 

* **Reference, in format PMID:#######**
PMID:30943413

* **Gene product name and ID to be annotated to this term**
SerRS-m (Q9VF85)
Slimp (Q95T19)

* **Parent term(s)**
catalytic complex (part of)
serine-tRNA ligase activity (GO:0004828) [capable of]

* **Any other information**
Characterized/described in Fig 2 of PMID:30943413 and accompanying text (e.g. "Aminoacylation assays with purified SLIMP, DmSerRS2, and both proteins simultaneously showed that only the co-purified DmSerRS2-SLIMP complex could efficiently aminoacylate mitochondrial tRNASer").
Intro of that paper says that SLIMP is "a paralog of DmSerRS2 present in arthropods and echinoderms" so this complex is presumably only found in those groups - so maybe apply a taxon constraint?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140715
+name: serine-tRNA ligase complex
+namespace: cellular_component
+def: "A heterodimeric enzyme complex that catalyzes the ligation of serine to tRNA(Ser), forming L-seryl-tRNA(Ser)." [PMID:30943413]
+is_a: GO:1902494 ! catalytic complex
+relationship: capable_of GO:0004828 ! serine-tRNA ligase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22145 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-15T12:38:41Z
+

**Comment by pgaudet** [comment]
Hi @sjm41 

About the taxon constraints: I understand that this specific complex is only in arthropods and echinoderms, but don't you think there may be other serine-tRNA ligase complexes in other organisms? It seems risky to put this as a taxon constraint. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks for adding the term so quickly!
Fine to leave off the taxon constraint - just wanted to mention the possibility.  As you say, there may be other serine-tRNA ligase complexes (not involving this SLIMP protein) in other critters.  From that point of view, maybe I shouldn't have specified 'heterodimeric' in the def?

**Comment by pgaudet** [comment]
Since for now this is the complex we describe, I think we can leave 'heterodimeric' in the def; we can modify when other examples are described. At least this corresponds to the paper cited.

**Comment by sjm41** [comment]
OK!
Another related question (I'll make a new ticket depending on your answer):
I see we have these 4 specific terms under "regulation of aminoacyl-tRNA ligase activity":
- regulation of isoleucine-tRNA ligase activity
- regulation of methionine-tRNA ligase activity
- regulation of leucine-tRNA ligase activity
- regulation of threonine-tRNA ligase activity

For now, I've annotated SLIMP to the parent, but should I request "regulation of serine-tRNA ligase activity"?  That is, do we potentially want to add all the possible child terms here, or merge up to the "regulation of aminoacyl-tRNA ligase activity" parent?
