### ISSUE TITLE
HULC complex parents (TPV)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22142]
HULC complex has parent 'heterochromatin' but sometimes it is euchromatin?

Maybe just move up to 'chromatin?'

**Comment by pgaudet** [comment]
Also removed 
part_of GO:0005694 ! chromosome (redundant) 
and  GO:0000151 ! ubiquitin ligase complex, since it was is_a GO:0031371 ! ubiquitin conjugating enzyme complex, and is defined as a ubiquitin conjugating enzyme complex. 

Thanks, Pascale

**Comment by ValWood** [comment]
It is actually a ubiquitin ligase though. All ubiquitin ligase complexes also include a ubiquitin conjugating enzyme, but should be described as ubiquitin ligases  . So the HULC def should be revised to ligase.

**Comment by ValWood** [comment]
GO:0033503    JSON
HULC complex
Cellular Component

Definition (GO:0033503 GONUTS page)
A ubiquitin-conjugating enzyme complex that contains two RING finger proteins, which have ubiquitin ligase activity, in addition to a protein with ubiquitin-conjugating enzyme activity; catalyzes the ubiquitination of histone H2B at lysine 119 (or the equivalent residue). In Schizosaccharomyces the subunits are Rhp1, Brl2/Rfp1 and Brl1/Rfp2. PMID:17363370

the subunits are incorrect.
Should be
 In Schizosaccharomyces the subunits are Rhp6, Shf1, Brl2/Rfp1 and Brl1/Rfp2

**Comment by ValWood** [comment]
Sounds good.
