### ISSUE TITLE
Term merge: GO:0039591 suppression by virus of host tapasin activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22150]
**Term to be merged: Provide GO ID and term label**
GO:0039591 suppression by virus of host tapasin activity

**Which term do you propose this term merge into? Provide GO ID and term label**
Parent, GO:0046776 suppression by virus of host antigen processing and presentation of peptide antigen via MHC class I

**Reason for merge**
'GO:0039591 suppression by virus of host tapasin activity' represents a mechanism by which 'GO:0046776 suppression by virus of host antigen processing and presentation of peptide antigen via MHC class I' happens

**Any other information**

**Comment by pgaudet** [comment]
Hello @Antonialock @pmasson55 

Since GO:0039591 suppression by virus of host tapasin activity has been merged into its parent, 
`UniProtKB-KW:KW-1108` and `VZ:818` mappings need to be updated - is this an automated process? 

Merge is into GO:0046776 suppression by virus of host antigen processing and presentation of peptide antigen via MHC class I, so you can update mappings accordingly. 

Thanks, Pascale

**Comment by Antonialock** [comment]
I have remapped KW-1108 
from GO:0039591 
to GO:0046776

I don't know if it would have remapped post-processing without the manual fix!

**Comment by pgaudet** [comment]
@alexsign 

Do you know if KW mappings get mapped automatically if there is a term merge or obsoletion+replacedby? 

Thanks, Pascale

**Comment by alexsign** [comment]
@pgaudet UniProt KW to GO IDs is a manual process. IEA annotations created out of this list and UniProt accessions to KW mapping is automated. The automated part is taking care of merges and obsoletions.

**Comment by pgaudet** [comment]
Thanks for the info @alexsign
