### ISSUE TITLE
NTR: tRNA ligase activator activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22153]
* **Suggested term label:**
tRNA ligase activator activity

* **Definition (free text)**
Binds to and increases the activity of a tRNA ligase, an enzyme that catalyzes the formation of aminoacyl-tRNA. 

* **Reference, in format PMID:#######**
PMID:30943413

* **Gene product name and ID to be annotated to this term**
Slimp (Q95T19)

* **Parent term(s)**
enzyme regulator activity (GO:0030234)

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140733
+name: tRNA ligase activator activity
+namespace: molecular_function
+def: "Binds to and increases the activity of a tRNA ligase, an enzyme that catalyzes the formation of aminoacyl-tRNA." [PMID:30943413]
+intersection_of: GO:0030234 ! enzyme regulator activity
+intersection_of: positively_regulates GO:0004812 ! aminoacyl-tRNA ligase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22153 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-24T09:10:19Z
