### ISSUE TITLE
Obsolete GO:0000229 cytoplasmic chromosome 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22177]
2 EXP
Not used differently from 'chromosome' 
@AndreaAuchincloss 
@mgiglio99 
@dsiegele 

Does that sound reasonable?

**Comment by mgiglio99** [comment]
Then would 'cytoplasmic chromosome's children become children of 'chromosome'?

**Comment by pgaudet** [comment]
>Then would 'cytoplasmic chromosome's children become children of 'chromosome'?

Yes. That's only 2 terms (mitochondrion and plastid)

Moreover, as was pointed out on yesterday's call, the while mitochondria and chloroplasts are considered part of the cytoplasm, their lumen/matrix are not usually described as "cytoplasm".

Thanks, Pascale

**Comment by AndreaAuchincloss** [comment]
In eukaryotes (if I recall correctly) the nuclear membrane dissolves/disappears during mitosis/meiosis, so the synonym "cytoplasmic interphase chromosome" suggests this is really a cell cycle stage anyway.
The chloroplast (and other permutations of the organelle) have a stroma, while the mitochondria has a matrix, not a cytoplasm, so I'm not sure I see the need for this as a eukaryotic term.
I'm curious, where do bacterial and archaea chromosomes fall in this hierarchy? Or elements like yeast plasmids (which are in the cytoplasm but aren't really chromosomes)?

**Comment by pgaudet** [comment]
Bacteria and archae were supposed to be annotated to 'cytoplasmic chromosome', but this only makes (some) sense when looking at the entire hierarchy, nobody would think to look for bacterial annotations there. So people annotate to the parent class 'chromosome', which seem OK to me, what do you think? 

This is similar to the 'promoter/bacterial-type promoter' distinction that we recently removed.

**Comment by AndreaAuchincloss** [comment]
Yes, annotating to chromosome seems fine to me, as I said if you look at the synonym for cytoplasmic chromosome that leaves me with the impression it isn't correct for bacteria and archaea anyway.

**Comment by mgiglio99** [comment]
I agree annotating to 'chromosome' for bacteria sounds good.
And I agree that the mitochondrial and chloroplast terms should not have been under 'cytoplasmic chromosome' anyway.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0000229 cytoplasmic chromosome. The reason for obsoletion is that this is an unnecessary grouping class. There are 2 EXP annotations (now removed). There are no mappings to this term. 

This term is present in the generic GO slim, as well as in the CHEMBL GO slim, but these subsets also contain the parent class 'chromsome', so no information should be lost. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22177

Thanks, Pascale

**Comment by pgaudet** [comment]
replaced_by: GO:0005694 chromosome
