### ISSUE TITLE
GO:0062039 biofilm matrix NOT an extracellular matrix ?? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22176]
Reported as a taxon constraint prediction inconsistency https://github.com/geneontology/go-ontology/issues/16298#issuecomment-921962141

GO:0030312
We propose to move GO:0062039 biofilm matrix up to GO:0030312 external encapsulating structure

+ redefine 'extracellular matrix' -> is this an animal structure? This is what is said here: PMC7147346 - however some bacterial literature uses ECM for biofilm, for eg PMC4511925

Note that there are few direct annotations to ECM to organisms other than animals. 

**Alternatively**, we could create a new term to describe the animal ECM, and keep the current ECM as a grouping term. 

@RLovering @mgiglio99 @tberardini

**Comment by tberardini** [comment]
> Alternatively, we could create a new term to describe the animal ECM, and keep the current ECM as a grouping term.

I like this option.

**Comment by ValWood** [comment]
I'm not sure that "biofilm matrix" as defined is a valid term
A structure lying external to microbial cells. A biofilm is an **aggregate of surface-associated cells**, and the biofilm matrix is the **envelope of polymeric substances** that surrounds the cells. PMID:22571672 PMID:27129222 PMID:28516088

unless those polymeric substances are  proteins.

The term has 418 EXP annotations
130 Candida and
288 Nakaseomyces glabratus 
but he annotations are many housekeeping genes? so this isn't location of action

**Comment by mgiglio99** [comment]
Hi Val,
There are many proteins that are located in the biofilm matrix - quick search found this:
https://pmc.ncbi.nlm.nih.gov/articles/PMC4480581/
I agree that the above isn't a great definition, but the term seems valid.
Should we try to revise the definition?
Michelle

**Comment by ValWood** [comment]
Hi @mgiglio99  that makes sense.
Do you want to suggest an improved definition?
v

**Comment by mgiglio99** [comment]
How about this:
A type of extracellular matrix that surrounds the cells within a microbial biofilm. The matrix is composed of extracellular polymeric substances including exopolysaccharides, proteins, nucleic acids, lipids, and other biomolecules.
PMID:32663461

**Comment by mgiglio99** [comment]
Hi Pascale,
I see why you added this term to the do_not_annotate list, because you want people to annotate to one of the children, however, it occurs to me as I look at the children that although there are pure fungal and pure bacterial biofilms, there are also biofilms made of both. And there are archaeal biofilms and likely biofilms that have mixtures of all three. Thus maybe we should keep the parent term for annotating those situations?

**Comment by pgaudet** [comment]
Hi @mgiglio99 

Thanks for raising this point. 

Again we have inconsistencies in various branches of the ontology: 

In BP, under 'formation', we have 
<img width="279" alt="image" src="https://github.com/user-attachments/assets/70692a9b-be40-421c-996a-e61462770ea7">

Under assembly, we also have 
<img width="310" alt="image" src="https://github.com/user-attachments/assets/3cf7cc17-43a3-4e05-98e8-d88e37fd33df">

While under CC we have 
<img width="277" alt="image" src="https://github.com/user-attachments/assets/970fd47f-8b68-4dc7-9070-915c10befcfb">

It would be nice if these were aligned, but which seems the most correct? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Looking at the single EXP annotation to GO:0098786 biofilm matrix disassembly, this term should be changed to 
something along the lines of 'disruption of biofilm matrix in another organism?? 

Same for GO:1900229 negative regulation of single-species biofilm formation in or on host organism
3 EXP human, 1 EXP to Escherichia phage vB_EcoM_ECOO78
I dont know if we can use 'host-mediated disruption of biofilm matrix in symbiont' because of the phage paper, PMID:28824588
>  Dpo42  (the phage protein) degraded the capsular polysaccharides surrounding E. coli and exhibited dose-dependent biofilm-formation prevention activity. Based on these results, Dpo42 appears to be a novel phage-derived depolymerase that represents a new potential strategy for preventing E. coli biofilm formation.
