### ISSUE TITLE
Change subclass 'telomere organization' to 'chromatin organization'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22172]
and add synonym 'to 'telomeric chromatin organization'

@colinlog @RLovering @ValWood

**Comment by ValWood** [comment]
@colinlog the question here is, is the telomere capping/shelterin complex considered part of 'chromatin' or is it considered to be a separate component like the kinetochore?

**Comment by pgaudet** [comment]
Decision to leave this as-is for now.
