### ISSUE TITLE
'viral occlusion body' GO:0039679 taxon constraint issue

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#22183]
[viral occlusion body](http://purl.obolibrary.org/obo/GO_0039679) has a taxon constraint `never_in_taxon 'cellular organisms'`. However it also inherits an axiom `part_of some 'host cell'`. This implies `in_taxon some 'cellular organisms'`. This isn't a problem within GO at the moment because we don't really connect 'host cell' to anything that causes a problem. But due to some bridging to CARO it's causing an issue for Monarch: https://github.com/monarch-initiative/monarch-ontology/issues/33

**Comment by cmungall** [comment]
I would recommend other ontologies steer clear of the hostX branch in GO and don't try and hook it up to anything. I think we need a better strategy for these in GO as a whole but that may take the multiorganism group some time. For now, the recommendation should be: don't be tempted to hook host-cell up to "cell" no matter how much it "looks" like a subclass.

**Comment by pgaudet** [comment]
Right - why do they have 'biological entity SubClassOf is part of some cellular organism ' ?

**Comment by pgaudet** [comment]
@balhoff 
I remove the LD of the parent 'GO:0033643 host cell part' 
-intersection_of: GO:0018995 ! host cellular component
-intersection_of: part_of GO:0043657 ! host cell

and asserted 
+is_a: GO:0018995 ! host cellular component

Does that fix the issue? We can revert that if it doesn't work. 

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet I think that would fix the issue. I suppose they worked around it a long time ago. :-)
