### ISSUE TITLE
GO:1990849 'maintenance of vacuolar location' change label to 'vacuolar localization'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22182]
GO:1990849  'maintenance of vacuolar location'  -> no annotation, missing parent class, so will relabel and change the def

**Comment by pgaudet** [comment]
[lysosome localization](http://purl.obolibrary.org/obo/GO_0032418) should be classified under 'vacuole localization' with the logical definitions

**Comment by pfey03** [comment]
@pgaudet 
GO:0140027 establishment of contractile vacuole localization 
would also be better as 'contractile vacuole localization' and move under vacuole localization
