### ISSUE TITLE
	translation elongation factor activity parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22198]
is under 
translation regulator activity, nucleic acid binding (which has F_P link to 'regulation of translation')

but includes all translation factors, e.g:
https://www.pombase.org/term_genes/GO:0008135

**Comment by ValWood** [comment]
i.e ALL  translation factors are classed  as regulators

**Comment by pgaudet** [comment]
Removed logical definition here: 25196
