### ISSUE TITLE
Taxon constraint:  transcytosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22204]
Please provide as much information as you can: 

* **GO term ID label:**
* GO:0045056 transcytosis
* 
Seems to be multicellular phenomena?

Macromolecules are captured in vesicles on one side of the cell, drawn across the cell, and ejected on the other side. Wikipedia

* **Request to add a taxon constraint:**

* * **only in taxon: **
* * **never in taxon: **
never in yeast

(picking up a single annotation from PAINT)

* **Supporting evidence if available (e.g PMID):**

**Comment by pgaudet** [comment]
Added parent GO:0032501 ! multicellular organismal process

**Comment by pgaudet** [comment]
Fixed taxon constraint in #22336
