### ISSUE TITLE
Change label 'genetic imprinting' -> 'genomic imprinting' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22217]
@ValWood confirmed with Prof Olaf Nielsen from U of Coppenhagen - there is no difference between 'genomic imprinting' and 'genetic imprinting'. 

However in PubMed there are 8000 results with ''genomic imprinting'  and 200 with 'genetic imprinting' , so I will swap the label on these terms:

* GO:0071514 genetic imprinting
*  GO:0071515 genetic imprinting at mating-type locus
* GO:0006349 regulation of gene expression by genetic imprinting
* GO:2000653 regulation of genetic imprinting 
* GO:0060819 inactivation of X chromosome by genetic imprinting

**Comment by pgaudet** [comment]
@colinlog @ValWood @RLovering @hattrill 

Can I move 'genomic (genetic) imprinting' under 


It's currently under 
-  GO:0006139 nucleobase-containing compound metabolic process
-  GO:0060255 regulation of macromolecule metabolic process

**Comment by ValWood** [comment]
That works for me.

**Comment by pgaudet** [comment]
Actually I don't understand the difference between 

**GO:0071514 genetic imprinting:** Any process that modulates the frequency, rate or extent of the chemical reactions and pathways involving macromolecules by a mechanism that is mediated by DNA, is mitotically or meiotically heritable, or is stably self-propagated in the cytoplasm of a resting cell, and does not entail a change in DNA sequence.

and 
 GO:0006349 regulation of gene expression by genetic imprinting: Heritable alterations in the activity of a gene that depend on whether it passed through the paternal or the maternal germline, but that are not encoded by DNA itself.

**Comment by pgaudet** [comment]
How about this logical definition for 'genomic imprinting at mating-type locus'
LD 
'genomic imprinting'
and 'occurs in' some 'mating-type region heterochromatin'

**Comment by pgaudet** [comment]
Change def: 

GO:0006349 regulation of gene expression by genetic imprinting
"An epigenetic mechanism of regulation of gene expression in which imprints (epigenetic modification) are established during gametogenesis. For a given gene to show parentally biased expression, the imprint are established exclusively in one of the two parental genomes, thus generating an asymmetry between the maternal and paternal alleles."

**Comment by pgaudet** [comment]
genomic imprinting 

- [x]  move under 'heterochromatin assembly' 
- [x] Change def to 'The establishment of epigenetic modifications (imprints) during gametogenesis, leading to an asymmetry between the maternal and paternal alleles. This asymmetry results from the different epigenetic pathways acting in maternal and paternal gametes. '

**Comment by pgaudet** [comment]
@ValWood 

- [ ] GO:0071516 establishment of imprinting at mating-type locus has no annotations; can I merge into  GO:0071515 genetic imprinting at mating-type locus? 


I have moved the  GO:0071515 genetic imprinting at mating-type locus under 'heterochromatin assembly', because it's a completely different mechanism (with the endonuclease) than the mammalian/plant pathway, with DNA methylation and other chromatin modifications. 


I also changed the label to 'mating-type locus imprinting' 

OK ?

**Comment by ValWood** [comment]
GO:0071516 establishment of imprinting at mating-type locus has no annotations; can I merge into GO:0071515 genetic imprinting at mating-type locus?
GO:0071517 maintenance of imprinting at mating-type locus has no annotations either; do you want to keep ?

you can merge both -but I think there is some confusion here:

> I have moved the GO:0071515 genetic imprinting at mating-type locus under 'heterochromatin assembly',

Unless I have this completely wrong (I never annotated this area), but mating-type switching isn't part of heterochromatin assembly.

The heterochromatin silences the non expressed mating cassette. But the mating-type switching isn't part of the heterochromatin assembly. It is the process that switches (replaces)  the gene sequence that is expressed in the active locus from the silenced/donor  locus by some recombination event (a little bit like VDJ recombination).  This item does not currently have any relationship to heterochromatin assembly, and  I don't think it should, but I would need to do a lot of reading to remember exactly how it happens. @Antonialock  might be able to comment/confirm but she is away until the New Year.

**Comment by colinlog** [comment]
Mating type switching in S.c. is driven by endonuclease HO cleavage
followed by gene conversion. This is a form of (non-reciprocal) DNA
recombination, hereby the genetic information in one of the two silent
mating type loci on chromosome III are used to change the DNA at the
expressed mating type locus on that sae chromosome.
The silent copies are assembled into heterochomatin. The active locus is
euchromatin, bearing all the hallmarks of an expressed gene, always.
" Imprinting " has not been used as word in this context as it usually
refers to gender-specific methylation patterns in the gametes (sperm or
egg) of eutherians (mammals, marsupials) that influence (epigenetically)
the expression of autosomal chromosome genes that are expressed in a
parent-of-origin-specific fashion i the devloping embryo and placenta, in
hat has been term a 'war of sexes' whereby the mother must protect itself
from a too voracious embryo.

I am not sure botu mating type switching in S. pombe ...

**Comment by pgaudet** [comment]
There are still 2 open questions here: 

1. For GO:0071515 mating-type locus imprinting,  it sounds like heterochromatin assembly is OK here? 

2. Merge these two into their parent 'GO:0071515 mating-type locus imprinting' ? Only the parent has annotations
* [GO:0071516 establishment of imprinting at mating-type locus](http://amigo.geneontology.org/amigo/term/GO:0071516#display-lineage-tab)
*  [GO:0071517 maintenance of imprinting at mating-type locus](http://amigo.geneontology.org/amigo/term/GO:0071517#display-lineage-tab)

@ValWood
@Antonialock 
@srengel

**Comment by ValWood** [comment]
I don't think imprinting is part of heterochromatin assembly, I would say  Imprinting is part of 'mating-type switching' and related to heterochromatin assembly in some way (upstream?) but not part of it.  I previously tended to ignore this bit of biology because @Antonialock was our in-house expert. She explained it to me about 100 times ;)

**Comment by pgaudet** [comment]
- [x] Changed subclasses GO:0071515 mating-type locus imprinting 
-intersection_of: GO:0031507 ! heterochromatin assembly
-intersection_of: occurs_in GO:0031934 ! mating-type region heterochromatin
+is_a: GO:0022413 ! reproductive process in single-celled organism

- [ ] merge up
*  [GO:0071516 establishment of imprinting at mating-type locus](http://amigo.geneontology.org/amigo/term/GO:0071516#display-lineage-tab)
 *   [GO:0071517 maintenance of imprinting at mating-type locus](http://amigo.geneontology.org/amigo/term/GO:0071517#display-lineage-tab)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0071516 establishment of imprinting at mating-type locus
* GO:0071517 maintenance of imprinting at mating-type locus

The reason for obsoletion is that these represent molecular functions that play a role in imprinting at mating-type locus (establishment is done by an endonuclease, the maintenance by a inhibitor of DNA repair). There are no annotations or mappings to these terms; these terms are no in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22217

Thanks, Pascale
