### ISSUE TITLE
Obsolete GO:0036404 conversion of ds siRNA to ss siRNA  and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22220]
Transcription WG call 
@colinlog @RLovering @hattrill @ValWood 

GO:0036404 conversion of ds siRNA to ss siRNA 
GO:1902360  conversion of ds siRNA to ss siRNA involved in gene silencing by small RNA 
GO:0033168  conversion of ds siRNA to ss siRNA involved in RNA interference

5 EXP

**Comment by pgaudet** [comment]
![image](https://user-images.githubusercontent.com/4782928/135631593-1aad6972-7b89-4b75-907f-b8a6874e2b0e.png)

**Comment by RLovering** [comment]
Hi Pascale
so what will happen to the annotations currently associated with these terms? https://www.ebi.ac.uk/QuickGO/annotations?goId=GO:0036404,GO:0033168,GO:1902360&evidenceCode=ECO:0000352&evidenceCodeUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in,regulates&goUsage=descendants

Thanks

Ruth

**Comment by pgaudet** [comment]
Suggestions are here: 
https://docs.google.com/spreadsheets/d/1KHeAYZELMhcSatmjMmcycURQMRJ2ZfGPp16j1c6GfZw/edit#gid=0

**Comment by ValWood** [comment]
deleted PomBase this was pre Canto legacy annotation.

**Comment by pgaudet** [comment]
OK all agree to obsolete
