### ISSUE TITLE
rescue of stalled ribosome (GO:0072344) parentage query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22227]
rescue of stalled ribosome (GO:0072344)

is a descendent of 
regulation of translation
Is this really correct?

(It is also part_of translation elongation)

Although it is affecting the rate, it isn't 'regulation'?

**Comment by pgaudet** [comment]
Removed 'regulation of translation' parent. There was some discussion as to whether 'regulation' was OK as a parent even at the time, see https://github.com/geneontology/go-ontology/issues/6481.
