### ISSUE TITLE
Obsolete: [term labels and ID] GO:0098789    pre-mRNA cleavage required for polyadenylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22229]
* **Term to be merged: Provide GO ID and term label**
GO:0098789    pre-mRNA cleavage required for polyadenylation

really oddly, this term is to a descendant of polyadenylation, so it is likely that some genes are annotated inn different bins.]
I just wanted to report this as I am filtering the associated PANTHER mappings from PomBase

* **Which term do you propose this term merge into? Provide GO ID and term label**

GO:0043631   RNA polyadenylation
(or, if this is to possible immediately , at least add this term as a parent)

* **Reason for merge**

Missing superclass
MF in BP

**Comment by pgaudet** [comment]
Should active subunits be annotated to 'endoribonuclease activity, producing 3'-phosphomonoesters'? 
or maybe we need a child, 'pre-mRNA endoribonuclease activity, producing 3'-phosphomonoesters'? 
Possibly we need to obsolete and review annotations, what do you think? 

Thanks, Pascale

**Comment by ValWood** [comment]
Only 32 EXP so you could just  obsolete and recommend
MF + the appropriate polyadenylation term, (which seems to be GO:0031124   mRNA 3'-end processing)

mRNA 3'-end processing refers to 
Any process involved in forming the mature 3' end of an mRNA molecule.
and so should probably have synonyms
pre mRNA 3'-end processing 
cleavage and polyadenylation

OR merge into the parent (assuming if a MF was known it would have one already).

**Comment by ValWood** [comment]
Covered in
https://github.com/geneontology/go-ontology/issues/25259
