### ISSUE TITLE
NTR: serine-based site-specific recombinase activity

### ISSUE THREAD

**Issue by nataled** [geneontology/go-ontology#22265]
* **Suggested term label:**
serine-based site-specific recombinase activity

* **Definition (free text)**
Catalysis of the formation of new phosphodiester bonds between a pair of short, unique DNA target sequences; occurs through a phosphoseryl intermediate in which the target sequence is first cleaved by the nucleophilic attack by a serine in the active site.

Note: this is just the definition for 'tyrosine-based site-specific recombinase activity' (GO:0009037) with suitable changes. Based on https://en.wikipedia.org/wiki/Site-specific_recombination this seems okay to me.

* **Reference, in format PMID:#######**
PMID:29316791
PMID:16756503

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0009037 "integrase activity"
GO:0009037 "site-specific recombinase activity"

Note: these are the same parents given for the existing sibling term tyrosine-based site-specific recombinase activity.

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
None identified

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
"serine integrase" EXACT [PMID:28599144, PMID:29316791]

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
None identified

* Can also provide MetaCyc, KEGG, Wikipedia, and other links.
https://en.wikipedia.org/wiki/Site-specific_recombination

* **Any other information**
Serine-based site-specific recombinases have been described solely with respect to phages (PMID:28599144), but if this is not always the case (and vice versa), then this NTR should be changed to a request for synonym for GO:0008979 "prophage integrase activity".

**Comment by raymond91125** [comment]
wondering about the same question -- why aren't site-specific recombinase activity subclass_of integrase activity #22264
