### ISSUE TITLE
'integrase activity' vs 'site-specific recombinase activity'

### ISSUE THREAD

**Issue by nataled** [geneontology/go-ontology#22264]
http://purl.obolibrary.org/obo/GO_0008907 'integrase activity' def: "Catalysis of the integration of one DNA segment into another."

http://purl.obolibrary.org/obo/GO_0009009 'site-specific recombinase activity' def: "Catalysis of the formation of new phosphodiester bonds between a pair of short, unique target DNA sequences."

I have two questions (I'd break them into separate tickets, but they are too intertwined):

1) I have the sense that the definition for site-specific recombinase activity is missing a key component. Namely, that the target DNA sequences are on different molecules. 

2) Assuming the missing component was added, wouldn't that make site-specific recombinase activity a child of integrase activity? The child being a site-specific version of the parent.

I'm aware that 'integrase' is often used specifically for viruses and phages, so maybe that (now unstated) aspect is the reason for the current sibling relationship between the two terms?

**Comment by raymond91125** [comment]
Wondering about the same thing. 'integrase activity' vs 'site-specific recombinase activity' #22264

**Comment by pgaudet** [comment]
Indeed, it seems like an integrase is_a recombinase: 

https://pubmed.ncbi.nlm.nih.gov/10577069/

@raymond91125 Can you fix the parent of integrase ? 


Thanks, Pascale

**Comment by raymond91125** [comment]
> Indeed, it seems like an integrase is_a recombinase:
> 
> https://pubmed.ncbi.nlm.nih.gov/10577069/

Or is it the other way around? First sentence of Introduction of the same reference:
"Site-specific recombinases of the integrase (Int) family, named after the Int protein of phage lambda, use a common reaction pathway to mediate vastly different biological ends ([20])".
For the sake of arguments, even if integrase = recombinase, it should be site-specific recombinase ISA integrase.

**Comment by nataled** [comment]
Based on the (potential) definitions, and assuming 'integrase' isn't scoped to virus/phage, my view is as @raymond91125.

**Comment by raymond91125** [comment]
Done. Thanks @nataled @pgaudet
