### ISSUE TITLE
GO:0045814     negative regulation of gene expression, epigenetic [missing descendants]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22289]
GO:0045814    
negative regulation of gene expression, epigenetic
Biological Process
Definition (GO:0045814 GONUTS page)
An epigenetic process that stops, prevents or reduces the rate of gene expression by remodelling of chromatin by either modifying the chromatin fiber, the nucleosomal histones, or the DNA. PMID:22243696

I'm wondering why this term has a single descendant, "heterochromatin assembly"?

I recall others? what were they and where did they go?

@colinlog 
@pgaudet

**Comment by pgaudet** [comment]
Closing for now. Maybe new terms will be included here as we review other terms. No immediate action we can think of.
