### ISSUE TITLE
New Generic GO slim - BP 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22294]
Hello, 

As discussed at the[ Fall 2021 GOC meeting subsets workshop](https://docs.google.com/presentation/d/1dPmzAJGqIT-IS6I0hnGMYvREVziSk3CuIAtYNVJnYv4/edit?usp=drive_web&ouid=116162935390241629304), we propose a new generic GO slim for BP  (other aspects will be reviewed later) 

GOID | Term label
-- | --
GO:0000278 | mitotic   cell cycle
GO:0000910 | cytokinesis
GO:0002181 | cytoplasmic   translation
GO:0002376 | immune   system process
GO:0003008 | system   process
GO:0005975 | carbohydrate   metabolic process
GO:0006091 | generation of precursor metabolites and energy
GO:0006260 | DNA   replication
GO:0006281 | DNA   repair
GO:0006310 | DNA   recombination
GO:0006325 | chromatin   organization
GO:0006351 | transcription,   DNA-templated
GO:0006355 | regulation of trancription, DNA-templated
GO:0006399 | tRNA   metabolic process
GO:0006457 | protein   folding
GO:0006486 | protein   glycosylation
GO:0006520 | cellular   amino acid metabolic process
GO:0006575 | cellular modified amino acid metabolic process
GO:0006629 | lipid   metabolic process
GO:0006766 | vitamin   metabolic process
GO:0006790 | sulfur   compound metabolic process
GO:0006886 | intracellular   protein transport
GO:0006913 | nucleocytoplasmic   transport
GO:0006914 | autophagy
GO:0006954 | inflammatory   response
GO:0007005 | mitochondrion   organization
GO:0007010 | cytoskeleton   organization
GO:0007018 | microtubule-based   movement
GO:0007031 | peroxisome   organization
GO:0007040 | lysosome   organization
GO:0007059 | chromosome   segregation
GO:0007155 | cell   adhesion
GO:0007163 | establishment or maintenance of cell polarity
GO:0012501 | programmed   cell death
GO:0015979 | photosynthesis
GO:0016071 | mRNA   metabolic process
GO:0016073 | snRNA   metabolic process
GO:0016192 | vesicle-mediated   transport
GO:0022414 | reproductive   process
GO:0023052 | signaling
GO:0030163 | protein   catabolic process
GO:0030198 | extracellular   matrix organization
GO:0031047 | gene   silencing by RNA
GO:0032200 | telomere   organization
GO:0032502 | developmental   process
GO:0034330 | cell   junction organization
GO:0036211 | protein   modification process
GO:0042060 | wound   healing
GO:0042254 | ribosome   biogenesis
GO:0044782 | cilium   organization
GO:0048870 | cell   motility
GO:0051604 | protein   maturation
GO:0055065 | metal   ion homeostasis
GO:0055085 | transmembrane   transport
GO:0055086 | nucleobase-containing small molecule metabolic   process
GO:0061024 | membrane   organization
GO:0065003 | protein-containing   complex assembly
GO:0071554 | cell   wall organization or biogenesis
GO:0071941 | nitrogen   cycle metabolic process
GO:0072659 | protein localization to plasma membrane
GO:0098542 | defense   response to other organism
GO:0098754 | detoxification
GO:0140013 | meiotic   nuclear division
GO:0140053 | mitochondrial   gene expression
GO:1901135 | carbohydrate derivative metabolic process

**Comment by pgaudet** [comment]
Discussion with @hattrill and @RLovering about multicellular organism processes: 

We will replace      GO:0003008 system process 
by the more specific children: 

* GO:0003013 circulatory system process
* GO:0022600 digestive system process
* GO:0050886 endocrine process
*  GO:0061007 hepaticobiliary system process
*  GO:0003012 muscle system process
*  GO:0050877 nervous system process
*  GO:0003014 renal system process
*  GO:0003016 respiratory system process 
Thanks, Pascale

**Comment by pgaudet** [comment]
Also, replace GO:0032502 developmental process
by GO:0030154 cell differentiation and GO:0048856 anatomical structure development

**Comment by pgaudet** [comment]
New goslim_generic 2021-11-09 - 76 terms
Note that only BPs have been changed

GO:0007568	aging
GO:0048856	anatomical structure development
GO:0006914	autophagy
GO:0008150	biological_process
GO:1901135	carbohydrate derivative metabolic process
GO:0005975	carbohydrate metabolic process
GO:0007155	cell adhesion
GO:0030154	cell differentiation
GO:0034330	cell junction organization
GO:0048870	cell motility
GO:0071554	cell wall organization or biogenesis
GO:0006520	cellular amino acid metabolic process
GO:0006575	cellular modified amino acid metabolic process
GO:0006325	chromatin organization
GO:0007059	chromosome segregation
GO:0044782	cilium organization
GO:0003013	circulatory system process
GO:0000910	cytokinesis
GO:0002181	cytoplasmic translation
GO:0007010	cytoskeleton organization
GO:0098542	defense response to other organism
GO:0098754	detoxification
GO:0022600	digestive system process
GO:0006310	DNA recombination
GO:0006281	DNA repair
GO:0006260	DNA replication
GO:0050886	endocrine process
GO:0007163	establishment or maintenance of cell polarity
GO:0030198	extracellular matrix organization
GO:0031047	gene silencing by RNA
GO:0006091	generation of precursor metabolites and energy
GO:0061007	hepaticobiliary system process
GO:0002376	immune system process
GO:0006954	inflammatory response
GO:0006886	intracellular protein transport
GO:0006629	lipid metabolic process
GO:0007040	lysosome organization
GO:0140013	meiotic nuclear division
GO:0061024	membrane organization
GO:0055065	metal ion homeostasis
GO:0007018	microtubule-based movement
GO:0140053	mitochondrial gene expression
GO:0007005	mitochondrion organization
GO:0000278	mitotic cell cycle
GO:0140014	mitotic nuclear division
GO:0016071	mRNA metabolic process
GO:0003012	muscle system process
GO:0050877	nervous system process
GO:0071941	nitrogen cycle metabolic process
GO:0055086	nucleobase-containing small molecule metabolic process
GO:0006913	nucleocytoplasmic transport
GO:0007031	peroxisome organization
GO:0015979	photosynthesis
GO:0012501	programmed cell death
GO:0030163	protein catabolic process
GO:0006457	protein folding
GO:0006486	protein glycosylation
GO:0072659	protein localization to plasma membrane
GO:0051604	protein maturation
GO:0036211	protein modification process
GO:0065003	protein-containing complex assembly
GO:0006355	regulation of transcription, DNA-templated
GO:0003014	renal system process
GO:0022414	reproductive process
GO:0003016	respiratory system process
GO:0042254	ribosome biogenesis
GO:0023052	signaling
GO:0016073	snRNA metabolic process
GO:0006790	sulfur compound metabolic process
GO:0032200	telomere organization
GO:0006351	transcription, DNA-templated
GO:0055085	transmembrane transport
GO:0006399	tRNA metabolic process
GO:0016192	vesicle-mediated transport
GO:0006766	vitamin metabolic process
GO:0042060	wound healing

**Comment by pgaudet** [comment]
New goslim-generic
![Comparison chart for 76 terms](https://user-images.githubusercontent.com/4782928/140949205-c68ec94e-156b-41a4-8599-4de27482fe9c.png)

**Comment by RLovering** [comment]
FYI link to GO workshop https://docs.google.com/presentation/d/1dPmzAJGqIT-IS6I0hnGMYvREVziSk3CuIAtYNVJnYv4/edit#slide=id.gf7b8e17507_0_6

**Comment by RLovering** [comment]
Hi 
I have added a column to the list of removed terms (above) to indicate the ones that are currently on the new SLIM and were not actually removed
Ruth

**Comment by pgaudet** [comment]
Should we have root terms in the slim?

**Comment by RLovering** [comment]
Well it is there at the moment, I think Val would say no?

**Comment by hattrill** [comment]
That's a "nay" from I

**Comment by pgaudet** [comment]
Removed root terms here: #22525
