### ISSUE TITLE
histone chaperone definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22290]
GO:0140713    histone chaperone activity
Definition (GO:0140713 GONUTS page)
Binding to and carrying a histone or a histone complex until it is deposited on DNA, or degraded. PMID:26459557

This is defined as a carrier, but it isn't really a carrier.
This chaperoning activity is to prevent toxicity  (paraphrasing @colinlog )
Do these 'chaperone' activities  need to be in a different function branch?

**Comment by colinlog** [comment]
Chaperones for histones are always carriers.  They may also be involved in transport to nucleus, assembly and disassembly of chromosomal nucleosomes and degradation of histones. Except for transport (?) this aleways involve folding/refolding of individual histones or histone complexes [H2A-H2B dimers, H3-H4 tetramers, H2A-H2B-H3-H4 hexamers and octamers, H1 linker histones]. So the histone chaperones is often also a histone (re)folding chaperone , most of the time involving complexes of histones and sometimes of complexes made up of histones and DNA (nucleosome assembly/dissassembly involvment)

Schematically; histone chaperones may be involved in **ia** newly synthetised histone transport to nucleus and **ib**  post-translational histone modification prior to deposition and **ic.** deposition of -modified-histone(complex) on chromosomal DNA _or_ **iia** disassembly of chromosomal nucleosome followed by **iib** carrying and handing over nucleosome to nucleosome (re)assembly machinery or **iic** degradation of the histones it carries.

**Comment by ValWood** [comment]
OK so this is fine!

**Comment by pgaudet** [comment]
Closing this. We discussed this again last Friday and the definition is fine for the activities we aim to describe: "Binding to and carrying a histone or a histone complex to unload or deposit it as a nucleosome. The histone can be newly synthesized or result from nucleosome disassembly (either spontaneously, or by a histone chaperone)."

Thanks, Pascale
