### ISSUE TITLE
NTR: endothelial cell-matrix adhesion via collagen

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#22301]
Please provide as much information as you can: 

* **Suggested term label:**

1. endothelial cell-matrix adhesion via collagen
2. endothelial cell-matrix adhesion via laminin
3. endothelial cell-matrix adhesion via vitronectin

* **Definition (free text)**

1. The binding of an endothelial cell to the extracellular matrix via collagen.
2. The binding of an endothelial cell to the extracellular matrix via laminin.
3. The binding of an endothelial cell to the extracellular matrix via vitronectin.

* **Reference, in format PMID:#######**

PMID:8442917

* **Gene product name and ID to be annotated to this term**

Dicer1, RGD:1309381

* **Parent term(s)**

endothelial cell-matrix adhesion (GO:0090673)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

1., 2., 3. The corresponding regulation, positive, and negative regulation terms are also requested.  

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @slaulederkind 

Sorry about the long delay in looking into this - The definitions you propose dont distinguish the various 'pathways': 


    The binding of an endothelial cell to the extracellular matrix via collagen.
    The binding of an endothelial cell to the extracellular matrix via laminin.
    The binding of an endothelial cell to the extracellular matrix via vitronectin.

Can you be more specific in the definitions? as this stands, they look like annotations (to collagen, laminin, and vitronextin). 

Thanks, Pascale

**Comment by slaulederkind** [comment]
We  probably don't need such granular terms.  The requested terms are BP versions of the MF children of "cell-matrix adhesion mediator activity" (GO:0098634): collagen binding involved in cell-matrix adhesion (GO:0098639) and laminin binding involved in cell-matrix adhesion (GO:0098638).

**Comment by pgaudet** [comment]
OK, I'll close, assuming the MFs are sufficient. 

Pascale
