### ISSUE TITLE
Taxon constraint:  neuron terms

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#22312]
Please provide as much information as you can: 

* **GO term ID label:**
GO:0001764  neuron migration
GO:0007417   central nervous system development

* **Request to add a taxon constraint:**
* * **only in taxon: **
* * **never in taxon: ** 33083 all Dictyosteliia

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):** no PMID but Dicty don't have neurons. The above are IEA annotations on Q55FW9 / https://dictycr.org/gene/DDB_G0267914

**Comment by raymond91125** [comment]
only in 6072 | Eumetazoa

**Comment by raymond91125** [comment]
neuron migration and central nervous system development both already have the constraint Never in Amoebozoa. Thus it is not an issue of the ontology, I believe.

**Comment by pfey03** [comment]
That's true! np

**Comment by raymond91125** [comment]
Close this for now. Thanks @pfey03
