### ISSUE TITLE
Missing parent: [GO:0007034 vacuolar transport]

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#22316]
* **GO term ID and label for which you request a new superclass**
GO:0007034 vacuolar transport
* **New superclass (parent) suggested**
GO:0046907 intracellular transport

* **Reference(s), if appropriate**
PMID:nnnnnnn

* Not sure why this is not an intracellular transport. The def is consistent and looking at diverse children, they are all intracellular. It's currently only a child of 'transport' and 'cellular process'.

**Comment by pfey03** [comment]
@pgaudet would you mind moving this term under GO:0046907 intracellular transport intracellular transport? Or is  GO:0034486 'vacuolar transmembrane transport' a problem as a child? 
For slim it's still a bit messy if just under transport and keeping as term in slim also a bit specific in addition to others. if not possible to move it under intracellular transport please close the ticket with a comment. Thanks

**Comment by pgaudet** [comment]
Hi @pfey03 

A clarification: 
this is analogous to 'mitochondrial transport' - ie transport to and from or within a mitochondrion. 'mitochondrial transport' is not an intracellular transport. 

I think the term 'vacuolar transport' is confusing with 'GO:0016192 vesicle-mediated transport' ; is that possible?  

In any case, if we add the parent as you suggest, we should also probably add other organellar transport. 

@ValWood have you come across this before? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't know immediatly why "vacuolar transport" and "mitochondrial transport" are not both 'intracellular transport". But I think there are many issues in this area so I haven't looked in detail.

**Comment by pfey03** [comment]
Thanks @pgaudet and @ValWood and it seems all the changes you made make sense. As I also have currently mitochondrial transport as extra term since this alone has a lot of Dicty annotations but the new structure makes more sense.

**Comment by pgaudet** [comment]
Great!
