### ISSUE TITLE
Move GO:1990109 rejection of pollen from other species

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22338]
Hi 

GO:1990109 rejection of pollen from other species is a child of 'GO:0044419 biological process involved in interspecies interaction between organisms'

In the multiorg call we concluded it should be under 'GO:0048544 recognition of pollen' 

@tberardini is that OK with you? 

Thanks, Pascale

**Comment by tberardini** [comment]
from the definition of  'GO:0048544 recognition of pollen': "The process, involving the sharing and interaction of the single locus incompatibility haplotypes, **involved in the recognition or rejection of the self pollen** by cells in the stigma. "

This definition seems to exclude "rejection of pollen from **other species**". 

@lreiser  Any additional thoughts?

**Comment by lreiser** [comment]
If I recall correctly there was a whole rejiggering around compatible and incompatible interactions or sporophytic and gametophytic incompatability. 

The synonyms of  'GO:0048544 recognition of pollen': are also very specific to SI like the definition
pollen recognition, recognition or rejection of self pollen, self incompatibility


so change definition to allow for recognition of intra (self) or interspecific pollen?  
the process, involving the sharing and interaction of the single locus incompatibility haplotypes, involved in the recognition or rejection of the self pollen by cells in the stigma.

Or have terms for recognition of interspecies pollen and one for recognition of intraspecies pollen?

Example of interspecies rejection in (self compatible) Arabidopsis here:
https://www.nature.com/articles/s41477-019-0444-6

**Comment by pgaudet** [comment]
Thanks both for looking into this. 

Is there an inconsistency with the term 'acceptance of pollen', then, (a child of 'recognition of pollen') which has a related synonym 'acceptance of non-self pollen'? 

Perhaps one possibility would be to widen the definition of the parent 'recognition of pollen', and make it 'do not annotate', to ensure that we capture either 

- 'acceptance of pollen'
- 'rejection of self pollen' or 
- rejection of pollen from other species

Would that work? 

Note that 'recognition of pollen' has 2 EXP annotations. 

Thanks, Pascale

**Comment by lreiser** [comment]
Im not sure that acceptance of pollen is a thing just because I think it is the absence of something. In the absence of active barriers to self or interspecies fertilization pollination leads to fertilization.

**Comment by tberardini** [comment]
@lreiser  Should we revisit annotations to 'acceptance of pollen'?  
http://amigo.geneontology.org/amigo/term/GO:0060321

Most are from this paper:
https://www.arabidopsis.org/servlets/TairObject?accession=Publication:501766824

**Comment by lreiser** [comment]
Hm ok guess it is a 'thing' according to the experts, so leave it.

**Comment by pgaudet** [comment]
- [x] Updated the definition of 'recognition of pollen' from 'The process, involving the sharing and interaction of the single locus incompatibility haplotypes, involved in the recognition or rejection of the self pollen by cells in the stigma. This process ensures out-breeding in certain plant species.' to 'A cell recognition process in which pollen is recognized and either accepted or rejected by cells in the stigma.'
- [x] removed part_of GO:0009875 ! pollen-pistil interaction
- [x] added part_of GO:0009875 ! pollen-pistil interaction to 'acceptance of pollen'


Please let me know if that's OK or if you'd like modifications.

**Comment by pgaudet** [comment]
Updated definitions to refer to the parent class and to remove the two instances of 'involved': 
 id: GO:0060320 rejection of self pollen
Old def: "The process, involving the sharing and interaction of the single locus incompatibility haplotypes, involved in the rejection of the self pollen by cells in the stigma." [GOC:dph, GOC:tb, PMID:34848142]
New def: "The recognition and rejection of self pollen by cells in the stigma, mediated by the sharing and interaction of the single locus incompatibility haplotypes." [GOC:dph, GOC:tb, PMID:34848142]

GO:0060321 acceptance of pollen
Old def: "The process, involving the sharing and interaction of the single locus incompatibility haplotypes, involved in the acceptance of pollen by cells in the stigma." [GOC:dph, GOC:tb]
New def: "The recognition and acceptance of pollen by cells in the stigma, mediated by the sharing and interaction of the single locus incompatibility haplotypes." [GOC:dph, GOC:tb]


GO:1990109 rejection of pollen from other species
Old def: "The process involved in the rejection of pollen of one species by cells in the stigma of another species." [PMID:21205670]
New def: "The recognition and rejection of pollen of one species by cells in the stigma of another species." [PMID:21205670]
