### ISSUE TITLE
NTR: [box C/D RNA 5'-end processing]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22330]
Please provide as much information as you can: 

* **Suggested term label:**

box C/D RNA 5'-end processing

* **Definition (free text)**

Any process involved in forming the mature 5' end of a box C/D RNA molecule.

* **Reference, in format PMID:#######**

PMID:34352089
https://curation.pombase.org/pombe/curs/f5403fffd3ecaf81/ro

* **Gene product name and ID to be annotated to this term**
 
S. pombe pac1  SPBC119.11c

* **Parent term(s)**

GO:0000966    RNA 5'-end processing
and
GO:0034963 | box C/D RNA processing

**Comment by hdrabkin** [comment]
@krchristie , do you want to suggest any adjustments before I go ahead and make this term?

**Comment by krchristie** [comment]
Hi @hdrabkin 

What @ValWood  requested seems consistent with the way we've done other similar terms for processing of specific types of RNAs, and to represent accurately what the authors say about the involvement of Pac1 in the processing of some box C/D snoRNAs. I don't have any adjustments to suggest.


Quote from PMID:34352089
> Pac1 also associated with a total of 15 snoRNA genes, but only snoRNA genes expressed from independent transcription units (i.e., no intronic snoRNAs nor polycistronic snoRNA clusters) (Supplementary Figure S2B). Although Pac1 was previously shown to function in transcription termination of the snU32 snoRNA gene expressed from a plasmid-borne transgene (25), our data revealed that Pac1 nuclear exclusion did not result in widespread readthrough of RNAPII transcription at snoRNA genes (Figure 1E), with the notable exceptions of snU3, snU32 and snR88 (Figure 1E and F). Accordingly, stable RNA hairpin structures that can function as Pac1 substrates are also predicted downstream of the annotated 3′ end of snU3 and snU32 snoRNAs (Supplementary Figure S2A). While both C/D and H/ACA box snoRNA genes were bound by Pac1 (Supplementary Figure S2B), a difference between the two groups is that Pac1 nuclear exclusion specifically led to the accumulation of 5′-extended precursors of Pac1-bound C/D box snoRNAs (Supplementary Figure S3A). This accumulation was confirmed by Northern blot assays on three C/D box snoRNAs (sno16, snoU14 and snr79), whereas a control H/ACA box snoRNA (sno12) was unaffected by Pac1 nuclear exclusion (Supplementary Figure S3B). Fu thermore, stable hairpin structures were predicted either directly upstream or up to 50 nucleotides upstream of the annotated mature 5′ end of the C/D box snoRNAs that showed accumulation of 5′-extended precursors by Northern blotting (Supplementary Figure S3C). These observations are reminiscent of the role of the S. cerevisiae Pac1 ortholog Rnt1 in the co-transcriptional 5′-end processing and maturation of C/D box snoRNAs (6).

**Comment by hdrabkin** [comment]
+id: GO:0106410
+name: box C/D RNA 5'-end processing

**Comment by ValWood** [comment]
Hi Harold, did you commit? terms usually come through to Canto by now.
thanks
val

**Comment by mah11** [comment]
It's in the latest snapshot, so the delay is on our end (snapshot date 2021-11-04; we've got 2021-11-02).

**Comment by ValWood** [comment]
OK, thanks!

**Comment by hdrabkin** [comment]
Yes, the day you asked for it.
