### ISSUE TITLE
Term merge: [nuclear retention of pre-mRNA at the site of transcription] (phenotype)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22342]
* **Term to be merged: Provide GO ID and term label**
GO:0071033    nuclear retention of pre-mRNA at the site of transcription
The process involved in retention of aberrant or improperly formed mRNAs, e.g. those that are incorrectly or incompletely spliced or that have incorrectly formed 3'-ends, within the nucleus at the site of transcription. PMID:11586364 PMID:12417728 PMID:14718167 PMID:18644474

* **Which term do you propose this term merge into? Provide GO ID and term label**

parent
GO:0071028    nuclear mRNA surveillance
Definition (GO:0071028 GONUTS page)
The set of processes involved in identifying and degrading defective or aberrant mRNAs within the nucleus. PMID:18644474

* **Reason for merge**

retention is a phenotype not a process. Many of the 18 EXP annotations are to exosome. It you mutate the exosome you see a huge increase in cryptic transcripts in the cell. This is even used as a tool to increase the number of cryptic transcripts. Since the process occurs IN the nucleus, any step in the process could be 'nuclear retention' because that is where these abherrant transcripts are degraded.

* **Reference(s)**
PMID:nnnnnn

* **Any other information**
The children should merge into their respective parent surveillance terms.

**Comment by pgaudet** [comment]
What about the 2 children terms? Merge as well? 
* GO:0071049 nuclear retention of pre-mRNA with aberrant 3'-ends at the site of transcription
* GO:0071048 nuclear retention of unspliced pre-mRNA at the site of transcription

**Comment by ValWood** [comment]
Yes , for the same reason.
