### ISSUE TITLE
NTR: [Cyc8(Ssn6)-Tup1 general repressor complex ]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22346]
Please provide as much information as you can: 

* **Suggested term label:**

Cyc8(Ssn6)-Tup1 general repressor complex
synonym exact Tup11/Tup12 repressor complex
PMID:17101775
* **Definition (free text)**

A corepressor complex  containing the WD-repeat protein Tup1p (S.  cerevisiae) and Tup11/Tup12 (fission yeast) and the TPR repeat protein Cyc8p  (S.  cerevisiae) ssn6  (fission yeast) that is recruited to target genes by DNA-bound repressor proteins preferentially at regions where histones are deacetylated by the Clr6 class I HDAC, and recruits the SWI/SNF and SAGA complexes to promoters. 

* **Reference, in format PMID:#######**
PMID: 10871883 
PMID:10567571
PMID:17101775
many more

* **Gene product name and ID to be annotated to this term**

see def

* **Parent term(s)**
Child of transcription repressor complex
(Currently annotations to this term are a mixture of different complexes)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

n/a

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

We don't usually add 2-member complexes (3 in pombe), but this is a really important  conserved general repressor. I need it to compare transcription complexes to their annotated process in term matrix.

**Comment by raymond91125** [comment]
Would it be more precise to have RNA polymerase II transcription repressor complex as the parent?

**Comment by raymond91125** [comment]
@ValWood Let me know if you'd prefer to move this term to under RNA polymerase II transcription repressor complex. Thanks.

**Comment by ValWood** [comment]
Yes please, the moe specific parent makes sense.
v
