### ISSUE TITLE
NTR: [Protein decrotonylase activity] etc.

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22351]
Hi GO,

I would need a bunch of GO terms, some of them will be used for GO-CAM models. 

These terms are related to enzymes that remove acylations on lysine residues on proteins. Please note that terms for enzyme that add these modifications already exist. I also request more precise terms when histones are substrates.

Terms are related to Rhea terms, most of them are not yet public (@amorgat @kaxelsen). 

Thanks

Sylvain

1)
Protein decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[protein] = (2E)-2-butenoate + L-lysyl-[protein]
Parent term: GO:0016811 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
PMID:28497810
PMID:34608293
PMID:30279482
Xref: RHEA:69172 (not yet public)

2)
Histone decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[histone] = (2E)-2-butenoate + L-lysyl-[histone]
child of Protein decrotonylase activity
PMID:28497810

3)
Protein de-2-hydroxyisobutyrylase activity
Catalysis of the reaction: H2O + N6-(2-hydroxyisobutanoyl)-L-lysyl-[protein] = 2-hydroxy-2-methylpropanoate + L-lysyl-[protein] and
Parent term: GO:0016811 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
PMID:29192674
Xref: RHEA:69176 (not yet public)

4) 
NAD-dependent protein decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[protein] + NAD+ = 2''-O-(2E)-but-2-enoyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
child of GO:0016747 acyltransferase activity, transferring groups other than amino-acyl groups 
PMID:28497810
Xref: RHEA:69332 (not yet public)

5)
NAD-dependent histone decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[histone] + NAD+ = 2''-O-(2E)-but-2-enoyl-ADP-D-ribose + L-lysyl-[histone] + nicotinamide
child of NAD-dependent protein decrotonylase activity
PMID:28497810

6)
NAD-dependent protein de-2-hydroxyisobutyrylase activity
Catalysis of the reaction: H2O + N6-(2-hydroxyisobutanoyl)-L-lysyl-[protein] + NAD+ = 2''-O-(2-hydroxyisobutanoyl)-ADP-D-ribose + L-lysyl-[protein] + nicotinamide 
child of GO:0016747 acyltransferase activity, transferring groups other than amino-acyl groups 
PMID:31328167
Xref: RHEA:10164 (public)

7)
Last but not least, would it be possible to complete the following mappings to Rhea?

GO:0140065 peptide butyryltransferase activity
Xref: RHEA:53912

GO:0140064 peptide crotonyltransferase activity 
Xref: RHEA:53908

**Comment by raymond91125** [comment]
@sylvainpoux I've not found crotonylase MF terms but a BP GO:0140066 peptidyl-lysine crotonylation. Am I missing something? Should we add them? Thanks.

**Comment by sylvainpoux** [comment]
Hi Raymond,

This term describes protein crotonylation : GO:0140064 peptide crotonyltransferase activity. By the waxy, the Rhea Cross-link is missing, may i ask you to add [Rhea:53908] as cross-reference for  GO:0140064?

Thanks

Sylvain

**Comment by pgaudet** [comment]
@sylvainpoux RHEA:10164  is a much more general reaction: 
 (2R)-2-phosphoglycerate = H2O + phosphoenolpyruvate
and already mapped to another term, http://amigo.geneontology.org/amigo/term/GO:0004634

Can you check that this is what you meant? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
You are right Pascale,
the correct mapping is [Rhea:24364]
thank you very much for pointing this out
Sylvain
