### ISSUE TITLE
Fix issues with telomeric regions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22353]
chromosome, subtelomeric region 
-> remove parent 'heterochromatin

**Comment by pgaudet** [comment]
Add missing term, 

subtelomeric heterochromatin
is_a heterochromatin


this will be parallel to pericentromeric heterochromatin, and to the corresponding BP terms

reported by @colinlog

**Comment by ValWood** [comment]
Subtelomeric Chromatin in the Fission Yeast S. pombe
Rajesh K Yadav 1, Atsushi Matsuda 2, Brandon R Lowe 3, Yasushi Hiraoka 4, Janet F Partridge 3
PMID: 34576871

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140720
+name: subtelomeric heterochromatin
+namespace: cellular_component
+namespace: Heterochromatin that is located adjacent to the telomere, and characterized by methylated H3 histone at lysine 9 (H3K9me2/H3K9me3). {xref="PMID:34576871"}
+is_a: GO:0000792 ! heterochromatin
+intersection_of: GO:0000792 ! heterochromatin
+intersection_of: part_of GO:0099115 ! chromosome, subtelomeric region
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22353 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-05T13:19:40Z
