### ISSUE TITLE
Obsoletion notice: GO:1902649 regulation of histone H2A-H2B dimer displacement & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22358]
GO:1902649 regulation of histone H2A-H2B dimer displacement
GO:1902650 negative regulation of histone H2A-H2B dimer displacement
GO:1902651 positive regulation of histone H2A-H2B dimer displacement 

No annotations, no mappings not in any subset. This represents regulation of a MF.

**Comment by pgaudet** [comment]
Can also obsolete 
histone displacement and 
histone H2A-H2B dimer displacement

annotation review: https://docs.google.com/spreadsheets/d/1Bm3Bmll8wWFY_Q2dmFt3tNlFa0Rojz9fnMdYjh-_iOc/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete 
GO:0001207 histone displacement
GO:0001208 histone H2A-H2B dimer displacement
GO:1902649 regulation of histone H2A-H2B dimer displacement 
GO:1902650 negative regulation of histone H2A-H2B dimer displacement
GO:1902651 positive regulation of histone H2A-H2B dimer displacement

The reason for obsoletion is that these are MF, not a BP. There are 7 EXP annotations, 6 by SGD and 1 by UniProt (now fixed). Annotations are here: 
https://docs.google.com/spreadsheets/d/1Bm3Bmll8wWFY_Q2dmFt3tNlFa0Rojz9fnMdYjh-_iOc/edit#gid=0

There are no mappings; these terms are not present in any subsets. 

You can comment on the ticket here: https://github.com/geneontology/go-ontology/issues/22358


Thanks, Pascale

**Comment by pgaudet** [comment]
@srengel please have a look at SGD annotations https://docs.google.com/spreadsheets/d/1Bm3Bmll8wWFY_Q2dmFt3tNlFa0Rojz9fnMdYjh-_iOc/edit#gid=0

**Comment by srengel** [comment]
i'm on it..

**Comment by srengel** [comment]
SGD done.
