### ISSUE TITLE
NTR: [Fc receptor-mediated immune complex endocytosis]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#22350]
Please provide as much information as you can: 

* **Suggested term label: Fc receptor-mediated immune complex endocytosis**

* **Definition (free text) The Fc receptor-mediated endocytosis and delivery of antigen-bound immunoglobulin to an 
intracellular compartment where the antigen can be processed and loaded onto MHC molecules. Selectively targets antigens for presentation by MHC class I or MHC class II.
**

* **Reference, in format PMID:9143687; PMID:9463401; PMID:28389502**

* **Gene product name and ID to be annotated to this term - A0A0B4J1G0 and more**

* **Parent term(s) GO:0006898  receptor-mediated endocytosis**

* **Children terms (if applicable) ** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)
* EXACT antigen-antibody immune complex uptake via Fc receptor
  EXACT Ig-complexed antigen endocytosis via Fc receptor
  RELATED Fc receptor-mediated immune complex internalization
**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information 
 **

**Comment by nnouspikel** [comment]
Thanks a lot!

To further clarify the definition, could you please replace

Selectively targets antigens for presentation by MHC class I or MHC class II.
with
Selectively targets antigens for presentation by MHC class II or cross-presentation by MHC class I.

Thanks again for your help,
Nevila

**Comment by raymond91125** [comment]
Done. Thanks. @nnouspikel
