### ISSUE TITLE
pericentric heterochromatin assembly - change subclass

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22365]
* **GO term ID and label for which you request a new superclass**

could the parent 
GO:0031048 heterochromatin assembly by small RNA
be added (as per  working group diagram)

This would help to resolve a lot of inconsistencies at  PomBase
* **Reference(s), if appropriate**

There are 100s of fission yeast papers and reviews.
Here is one
https://pubmed.ncbi.nlm.nih.gov/15289661/

 would it be useful to have a fly an/or  human eg?
@colinlog 

Note, I think the long term plan is possibly to remove the component specific heterochromatin terms, and focus on pathway/mechanism,  and use extensions for locations, but since this might not happen for a while it would be great (and eventually help the reannotation)  if this could have the correct parentage.

**Comment by pgaudet** [comment]
Hi @ValWood 

What are you asking for exactly? You want 'heterochromatin assembly by small RNA' be a parent of 'pericentric heterochromatin assembly'?  Or do you want ta new term for 'pericentric heterochromatin assembly **by small RNA**'? 

Thanks, Pascale

**Comment by ValWood** [comment]
short term fix, add  'heterochromatin assembly by small RNA' be a parent of 'pericentric heterochromatin assembly'? 

Longer term we discussed removing component specific terms (using SO in extensions) , but in the meantime it would help if it was in the correct place.

**Comment by pgaudet** [comment]
If all 'pericentric heterochromatin assembly' is mediated by small RNA, we need to edit the definition, which currently is: 

> The assembly of chromatin located adjacent to the CENP-A rich centromere 'central core' and characterized by the modified histone H3K9me3, into heterochromatin, resulting in the repression of transcription of centromeric DNA.

Thanks, Pascale

**Comment by ValWood** [comment]
~The assembly of chromatin~ 
An siRNA-dependent facultative heterochromatin assembly located adjacent to the CENP-A rich centromere 'central core' and characterized by the modified histone H3K9me3, into heterochromatin, resulting in the repression of transcription of centromeric DNA.

@colinlog  does that work for everything?

**Comment by colinlog** [comment]
I am not sure that pericentric heterochromatin formation is *always*
siRNA-dependent. This is a tough question because it is not simple to find
evidence for absence, so as to argue for the absence of siRNA mechanisms at
the alpha satellites around human centromeres, for example. This needs a
literature survey, or an email to someone like Bill Earnshaw?
Furthermore, I am not sure this is 'facultative' heterochromatin, I thought
that pericentric heterochromatin is always ***constitutive***.

**Comment by ValWood** [comment]
I see what you mean.  Maybe we just wait if the location specific terms are going. At present I 'm struggling with annotation in both places.

('facultative' heterochromatin was a mistake -fixed)

**Comment by colinlog** [comment]
Hello, I just looked up the plant RNA-directed DNA methylation pathway for heterochromatin assembly in https://doi.org/10.1371/journal.pgen.1009034, a 2020 PLoS-Gentics paper.

Below is a quote with regards to siRNA-mediated heterochromatin formation in other kingdoms than plants, be it dependent on DNA methylation or not:

"Perhaps the most analogous pathways to [plant] RdDM in another eukaryotic kingdom are the sRNA directed transcriptional gene silencing (TGS) and co-transcriptional gene silencing (CTGS) pathways in Schizosaccharomyces pombe [149]. In S. pombe, TGS directs methylation of H3K9, leading to heterochromatin formation, and is directed by sRNAs produced from the targeted regions [150]. Similar to canonical RdDM, this pathway is a positive feedback loop: sRNAs are generated preferentially from heterochromatin-rich areas of the genome, and these sRNAs direct the addition of K3K9 methylation to maintain/spread heterochromatin. Meanwhile, CTGS is directed by AGO1-bound sRNAs, similar to PTGS within plants, and results in the inhibition of transcription by Pol II, as well as to Pol II release [151,152]. Unlike RdDM, TGS and CTGS in S. pombe do not rely on transcription from non-Pol II sources or lead to the addition of DNA methylation. However, the S. pombe pathways and RdDM share many of the same components, like RNA-directed RNA polymerases and sRNAs, and have similar functions in maintaining heterochromatin."

My conclusion is that, as there is no RNA-directed RNA polymerase in vertebrates, this mechanism is unlikely to be at work there. But, as stated above, absence of evidence is not evidence of absence. Still, I do not think we can make the statement that all pericentromeric heterochromatin forms (in particular, vertebrate animals) is siRNA dependent!

**Comment by pgaudet** [comment]
pericentric heterochromatin assembly is not always by siRNA - will revert that. 

Next steps: 
Either remove 'pericentric' 'centromeric' terms in favor of the mechanism, or create specific children. 

To be revisited.

**Comment by pgaudet** [comment]
Discussion on transcription call @colinlog @ValWood @hattrill 

pericentric heterochromatin assembly should be is_a constitutive heterochromatin assembly

**Comment by ValWood** [comment]
Since it seems that the final decision is to keep the location specific terms, could we now add 

siRNA dependent pericentric heterochromatin assembly
so that  I don't have these annotated in two branches?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140727
+name: siRNA-dependent pericentric heterochromatin assembly
+namespace: biological_process
+def: "The assembly of pericentric heterochromatin by a process mediated by a small interfering RNA." [PMID:15289661]
+synonym: "siRNA dependent pericentric heterochromatin assembly" EXACT []
+is_a: GO:0031508 ! pericentric heterochromatin assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22365 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-22T08:02:22Z
+
