### ISSUE TITLE
Add JaponicusDB species to taxon subset

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#22362]
Now that we are taking JaponicusDB into the GO pipeline, we'll want to make sure that it is exposed like other resources' species. According to the current metadata, they would be:

- NCBITaxon:402676
- NCBITaxon:4897

For https://github.com/geneontology/pipeline/issues/252

**Comment by kimrutherford** [comment]
> According to the current metadata, they would be:
>
>  - NCBITaxon:402676
>  - NCBITaxon:4897

In case it's useful: JaponicusDB always uses taxon ID 4897 so that's the only taxon ID in the GAF and GPI files.  4897 is the ID of the species, 402676 is the strain that was sequenced.

GOA uses both IDs.

**Comment by kltm** [comment]
@kimrutherford Thank you for the note. I think the question for us (GO) and our use cases is: who is the canonical holder of the data. Most critically: what species ids do we filter out of the goa_uniprot_all file (rather than what's included in the japonicusdb file).

**Comment by mah11** [comment]
@kltm In that case, I think JaponicusDB should be responsible for both taxa. It's exactly analogous to PomBase, which uses 4896 for its own *S. pombe* annotations but is also authoritative for 284812.

**Comment by kltm** [comment]
Talking to @cmungall , we discovered that this already works as intended--no further work needed here.
