### ISSUE TITLE
NTR: [mycophenolic acid biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#22374]
I would propose the creation of a BP term linked to mycophenolic acid biosynthesis.

"mycophenolic acid biosynthetic process"

I would only create the biosynthesis terms since in general there are no degradation pathways of these metabolites (only few exceptions).

Definition:
The chemical reactions and pathways resulting in the formation of mycophenolic acid (MPA), the first isolated antibiotic natural product in the world obtained from a culture of Penicillium brevicompactum in 1893.

PMID: 26751579, 31209052, 21398490

Synonyms: mycophenolic acid synthesis, MPA synthesis, mycophenolic acid biosynthesis, MPA biosynthesis, mycophenolic acid formation, MPA formation, mycophenolic acid anabolism, MPA anabolism.

Proteins to be annotated to this term:

PMID | Protein | UniProt | Type | Rhea

26751579,   31209052, 21398490 | mpaC, mpaC' | W6QL47, F1DBA9, A0A0B5KU17 | Cytosolic polyketide synthase   mpaC' | RHEA:63056

26751579, 31209052, 22544261 | mpaDE, mpaDE' | W6QRN8, I7LRH3, A0A0B5KYT4 | ER-bound cytochrome P450 monooxygenase | RHEA:66669, RHEA:66673

31209052, 25630520 | mpaA, mpaA' | W6QIT8, F1DBA7, A0A0B5L778 | Golgi apparatus-associated prenyltransferase | RHEA:66677
31209052 | mpaB, mpaB' | W6R4H8, F1DBA8, A0A0B5LB52 | ER-bound oxygenase | RHEA:66688
31209052, 25630520 | mpaG, mpaG' | W6R4H4, F1DBB3, A0A0B5L781 | O-methyltransferase | RHEA:66696
31209052 | mpaH, mpaH' | W6QL41, F1DBB4, A0A0B5LB55 | Peroxisomal acyl-CoA hydrolase | RHEA:66704
31209052 | AC891 | W6R1D9, P9WEY3 | Acyl-CoA ligase | RHEA:66700
26751579 | mpaF, mpaF' | W6QIT2 , F1DBB2, A0A0B5L585 | Inosine-5'-monophosphate dehydrogenase | RHEA:11708

Parent terms: 
GO:0030639 polyketide biosynthetic process
GO:0017000 antibiotic biosynthetic process
GO:0043386 mycotoxin biosynthetic process

Child terms: (to create)
Regulation of mycophenolic acid biosynthetic process
Negative regulation of mycophenolic acid biosynthetic process
Positive regulation of mycophenolic acid biosynthetic process

We can create the regulation of terms since regulation of secondary metabolite biosynthesis is usually well documented.

Taxon constraint: Only in taxon 4751 Fungi

has_intermediate: CHEBI:146172 5-methylorsellinate
has_intermediate: CHEBI:167385	4,6-dihydroxy-2-(hydroxymethyl)-3-methylbenzoate
has_intermediate: CHEBI:68194 5,7-dihydroxy-4-methylphthalide
has_intermediate: CHEBI:167386 4-farnesyl-3,5-dihydroxy-6-methylphthalide 
has_intermediate: CHEBI:167389 (4E,8E)- 10- (4,6- dihydroxy- 7- methyl- 3- oxo- 1,3- dihydro- 2- benzofuran- 5- yl)- 4,8- dimethyldeca- 4,8- dienoate
has_intermediate: CHEBI:167390 (4E,8E)-10-(4-hydroxy-6-methoxy-7-methyl-3-oxo-1,3-dihydro-2-benzofuran-5-yl)-4,8-dimethyldeca-4,8-dienoate
has_intermediate: CHEBI:167446 (4E,8E)-10-(4-hydroxy-6-methoxy-7-methyl-3-oxo-1,3-dihydro-2-benzofuran-5-yl)-4,8-dimethyldeca-4,8-dienoyl-CoA(4−)
has_intermediate: CHEBI:167447 mycophenolyl-CoA(4−)

has_primary_output: CHEBI:168396 mycophenolic acid

Thanks a lot,
Best regards,
Marc.

**Comment by pgaudet** [comment]
@marcfeuermann I need references for the regulation terms.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140722
+name: mycophenolic acid biosynthetic process
+def: "The chemical reactions and pathways resulting in the formation of mycophenolic acid (MPA). MPA is the first isolated antibiotic natural product in the world obtained from a culture of Penicillium brevicompactum in 1893." [PMID:21398490, PMID:26751579, PMID:31209052]
+synonym: "MPA anabolism" BROAD []
+synonym: "MPA biosynthesis" BROAD []
+synonym: "MPA formation" BROAD []
+synonym: "MPA synthesis" BROAD []
+synonym: "mycophenolic acid anabolism" EXACT []
+synonym: "mycophenolic acid biosynthesis" EXACT []
+synonym: "mycophenolic acid formation" EXACT []
+synonym: "mycophenolic acid synthesis" EXACT []
+is_a: GO:0017000 ! antibiotic biosynthetic process
+is_a: GO:0030639 ! polyketide biosynthetic process
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:168396 ! mycophenolic acid
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22374 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-18T06:12:47Z

**Comment by marcfeuermann** [comment]
There are many regulators for natural product biosynthesis. In general, there is at least one transcription factor present in the cluster containing all the enzymes required for the biosynthesis of fungal NPs (sometimes, there are up to 3). Moreover, general secondary metabolite transcription factors such as the velvet complex also positively regulate NP biosynthesis. Finally, some other proteins can regulate the subcellular location or activities of specific enzymes. However, in the case of mycophenolic acid, I did not find a specific paper. So we could cancel the creation of regulation terms for this metabolite (at least for now). 
Thanks a lot.
Marc.

**Comment by pgaudet** [comment]
OK lets wait to find evidence. Thanks!
