### ISSUE TITLE
NTR: [patulin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#22373]
I would propose the creation of several BP terms linked to secondary metabolites biosynthesis.

The first one would be:

"patulin biosynthetic process"

I would only create the biosynthesis terms since in general there are no degradation pathways of these metabolites (only few exceptions).

Definition:
The chemical reactions and pathways resulting in the formation of patulin, an acetate-derived tetraketide mycotoxin produced by several fungal species that shows antimicrobial properties against several bacteria.

PMID: 30680886, 25120234

Synonyms: Patulin synthesis, patulin biosynthesis, patulin formation, patulin anabolism

Proteins to be annotated:

PMID | Protein | UniProt | Type | Rhea

30680886 | patK | A0A075TRC0 | NR-PKS | RHEA12240
30680886, 24334092 | patG | A0A075TXZ1, A1CFL4 | 6-methylsalicylic acid decarboxylase | RHEA:23112
30680886 | patH | A0A075TRL5 | Cytochrome P450 monooxygenase | RHEA:62208
30680886 | patI | A0A075TMP8 | Cytochrome P450 monooxygenase | RHEA:62212
30680886 | patJ | A0A075TR41 | Oxydoreductase |  
30680886 | patO | A0A075TR33 | FAD-linked oxidoreductase |  
30680886 | patN | A0A075TRB3 | Isoepoxydon dehydrogenase | RHEA:62216
30680886 | patF | A0A075TR27 | ? | RHEA:62220
30680886 | paD | A0A075TMP0 | Alcohol dehydrogenase | RHEA:62224
30680886 | patE | A0A075TRK9 | Dehydrogenase | RHEA:62228
30680886 | patB | A0A075TXZ3 | Carboxylesterase | Role unknown
25120234 | patM | B6RAL1 | ABC transporter |  
25120234 | patA | A0A075TRL0 | Acetate transporter protein |  

Parent terms: 
GO:0030639 polyketide biosynthetic process
GO:0043386 mycotoxin biosynthetic process

Child terms: (to create)
Regulation of patulin biosynthetic process
Negative regulation of patulin biosynthetic process
Positive regulation of patulin biosynthetic process

Protein that can be annotated with positive regulation of patulin biosynthetic process:
PMID:25625822 | patL | A0A075TXZ8 | Transcription regulator

Taxon constraint: Only in taxon 4751 Fungi

has_intermediate: CHEBI:17637 6-methylsalicylic acid
has_intermediate: CHEBI:17231 m-cresol
has_intermediate: CHEBI:17069 m-hydroxybenzyl alcohol
has_intermediate: CHEBI:5325 gentisyl alcohol
has_intermediate: CHEBI:145109 (+)-isoepoxydon
has_intermediate: CHEBI:145110 phyllostine
has_intermediate: CHEBI:145111 neopatulin
has_intermediate: CHEBI:145112 E-ascladiol

has_primary_output: CHEBI:74926 patulin

Thanks a lot.
Best regards,
Marc.

**Comment by pgaudet** [comment]
Add xref https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-7490

**Comment by pgaudet** [comment]
- [ ] add patulin to CheBI imports

**Comment by pgaudet** [comment]
Added taxon constraint to GO:0043386 mycotoxin biosynthetic process, so it will cover all children

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140723
+name: patulin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of patulin, an acetate-derived tetraketide mycotoxin produced by several fungal species that shows antimicrobial properties against several bacteria." [PMID:25120234, PMID:30680886]
+synonym: "patulin anabolism" EXACT []
+synonym: "patulin biosynthesis" EXACT []
+synonym: "patulin formation" EXACT []
+synonym: "patulin synthesis" EXACT []
+is_a: GO:0030639 ! polyketide biosynthetic process
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22373 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-18T06:25:59Z

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140724
+name: positive regulation of patulin biosynthetic process
+namespace: biological_process
+def: "Any process that increases the rate, frequency or extent of the chemical reactions and pathways resulting in the formation of patulin." [PMID:25625822]
+synonym: "positive regulation of patulin anabolism" EXACT []
+synonym: "positive regulation of patulin formation" EXACT []
+synonym: "positive regulation of patulin synthesis" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0140723 ! patulin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22373 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-18T06:32:18Z

**Comment by pgaudet** [comment]
did not add 'regulation' or 'negative regulation' as there doesnt seem to be evidence that these processes exist.

**Comment by marcfeuermann** [comment]
Hi Pascale,
Thanks a lot for the creation of these terms. These natural products are of great interest (clinical and biotechnological purposes) and many articles are published every months. So, these BP terms are really important. 
About the regulation terms, I agree to have only the "positive regulation". I thought it was mandatory to have at least the parent 'regulation'.

**Comment by pgaudet** [comment]
> I thought it was mandatory to have at least the parent 'regulation'.


I'll check about that.
