### ISSUE TITLE
Remove incorrect MetaCyc pathway xrefs on MF terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22382]
The following MetaCyc xrefs do not correspond to single step reactions, so I think should be removed.

id: GO:0008923
name: lysine decarboxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-lysine + H(+) = cadaverine + CO(2)." [EC:4.1.1.18, RHEA:22352]
xref: EC:4.1.1.18
xref: KEGG_REACTION:R00462
xref: MetaCyc:LYSDECARBOX-RXN
xref: MetaCyc:PWY0-461
xref: RHEA:22352
**=> remove MetaCyc:PWY0-461 (L-lysine degradation I)** 

id: GO:0045300
name: acyl-[acyl-carrier-protein] desaturase activity
namespace: molecular_function
def: "Catalysis of the reaction: stearoyl-[acyl-carrier protein] + reduced acceptor + O2 = oleoyl-[acyl-carrier protein] + acceptor + H2O. The enzyme requires ferredoxin." [EC:1.14.19.2]
xref: EC:1.14.19.2
xref: MetaCyc:1.14.19.2-RXN
xref: MetaCyc:PWY-5147
**=> remove MetaCyc:PWY-5147 (oleate biosynthesis I (plants))** 

id: GO:0045543
name: gibberellin 2-beta-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: a gibberellin + 2-oxoglutarate + O2 = a 2-beta-hydroxygibberellin + succinate + CO2." [EC:1.14.11.13, GOC:kad]
xref: EC:1.14.11.13
xref: MetaCyc:PWY-102
xref: RHEA:15005
**=> remove MetaCyc:PWY-102 (gibberellin inactivation I (2β-hydroxylation))**

**Comment by deustp01** [comment]
Or is there enough value in these xrefs so they should be preserved using something like the broad/narrow synonym fix proposed for some RHEA reactions (if this is feasible)?

**Comment by sjm41** [comment]
@pgaudet Do you think these MetaCyc xrefs should be removed?

**Comment by hdrabkin** [comment]
Should these be associated with a process term if they refer to multiple steps?
Or, as Peter suggests, make them broad xrefs?

**Comment by pgaudet** [comment]
I suggest we move them to the appropriate BP.

**Comment by sjm41** [comment]
Trying to find equivalent BPs to move the MetaCyc xrefs:

MetaCyc:PWY0-461 (L-lysine degradation I)
- can't find appropriate BP under GO:0019477 L-lysine catabolic process....

MetaCyc:PWY-5147 (oleate biosynthesis I (plants))
- can't find a BP

MetaCyc:PWY-102 (gibberellin inactivation I (2β-hydroxylation))
- can't find a BP

I think we may just have to remove these MF xrefs after all.....

**Comment by cmungall** [comment]
Note we can still add these as narrow mappings, these still have value for
propagation
