### ISSUE TITLE
Add comment to explain presence of MetaCyc pathway xrefs in Molecular Function branch

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22381]
I came across 21 MetaCyc pathway (PWY) xrefs on MF terms.
- In 4 cases, the reason for this is explained in a comment (e.g. "Note that this term has a MetaCyc pathway reference as the pathway only has a single step.")
- In 14 cases, I think a similar comment needs adding - see below
- In 3 cases, I think the xref needs to be removed (it's not a single step reaction) - I'll make a separate ticket for these (#22382).

Details below:

**4 cases that already have explanatory comment:**

id: GO:0004353
name: glutamate dehydrogenase [NAD(P)+] activity
namespace: molecular_function
def: "Catalysis of the reaction: L-glutamate + H2O + NAD(P)+ = 2-oxoglutarate + NH3 + NAD(P)H + H+." [EC:1.4.1.3]
comment: Note that this term has a MetaCyc pathway reference as the pathway only has a single step.
xref: MetaCyc:GLUTAMATE-DEHYDROGENASE-NADP+-RXN
xref: MetaCyc:GLUTAMATE-SYN2-PWY

id: GO:0004355
name: glutamate synthase (NADPH) activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 L-glutamate + NADP(+) = 2-oxoglutarate + L-glutamine + H(+) + NADPH. This is a two-step reaction: (a) L-glutamate + NH3 = L-glutamine + H2O, (b) L-glutamate + NADP+ + H2O = NH3 + 2-oxoglutarate + NADPH + H+." [EC:1.4.1.13, RHEA:15501]
comment: Note that this term has a MetaCyc pathway reference as the pathway only has a single step.
xref: MetaCyc:GLUGLNSYN-PWY
xref: MetaCyc:GLUTAMATESYN-RXN
xref: MetaCyc:GLUTSYN-PWY

id: GO:0004565
name: beta-galactosidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of terminal, non-reducing beta-D-galactose residues in beta-D-galactosides." [EC:3.2.1.23]
comment: Note that the inclusion of 'MetaCyc:BGALACT-PWY' is exceptional: normally MetaCyc pathway entries are database references for biological process terms, not molecular function terms. An exception was made in this case because the MetaCyc entry 'BGALACT-PWY' describes only one reaction, that catalyzed by beta-galactosidase.
xref: MetaCyc:3.2.1.23-RXN
xref: MetaCyc:BGALACT-PWY

id: GO:0009034
name: tryptophanase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-tryptophan + H(2)O = indole + NH(4)(+) + pyruvate." [RHEA:19553]
comment: Note that this term has a MetaCyc pathway reference as the pathway only has a single step.
xref: MetaCyc:TRYPDEG-PWY
xref: MetaCyc:TRYPTOPHAN-RXN

**14 cases that lack an explanatory comment:**

id: GO:0003878 Done
name: ATP citrate synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: acetyl-CoA + ADP + H(+) + oxaloacetate + phosphate = ATP + citrate + CoA." [RHEA:21160]
xref: MetaCyc:ATP-CITRATE-PRO-S--LYASE-RXN
xref: MetaCyc:PWY-5172

id: GO:0004068  Done
name: aspartate 1-decarboxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-aspartate = beta-alanine + CO2." [EC:4.1.1.11]
xref: MetaCyc:ASPDECARBOX-RXN
xref: MetaCyc:PWY-5155

id: GO:0004320 DONE
name: oleoyl-[acyl-carrier-protein] hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: oleoyl-[acyl-carrier protein] + H2O = [acyl-carrier protein] + oleate." [EC:3.1.2.14]
xref: MetaCyc:3.1.2.14-RXN
xref: MetaCyc:PWY-5142

id: GO:0004354  Done
name: glutamate dehydrogenase (NADP+) activity
namespace: molecular_function
def: "Catalysis of the reaction: L-glutamate + H2O + NADP+ = 2-oxoglutarate + NH3 + NADPH + H+." [EC:1.4.1.4]
xref: MetaCyc:GLUTDEHYD-RXN
xref: MetaCyc:GLUTSYNIII-PWY

id: GO:0004467 Done
name: long-chain fatty acid-CoA ligase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + a long-chain fatty acid + CoA = AMP + diphosphate + an acyl-CoA; a long-chain fatty acid is a fatty acid with a chain length between C13 and C22." [RHEA:15421]
xref: MetaCyc:ACYLCOASYN-RXN
xref: MetaCyc:PWY-5143

id: GO:0004749 done
name: ribose phosphate diphosphokinase activity
namespace: molecular_function
def: "Catalysis of the reaction: D-ribose 5-phosphate + ATP = 5-phospho-alpha-D-ribose 1-diphosphate + AMP + 2 H(+)." [EC:2.7.6.1, RHEA:15609]
xref: MetaCyc:PRPPSYN-RXN
xref: MetaCyc:PWY0-662

id: GO:0008482 done
name: sulfite oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: H(2)O + O(2) + sulfite = H(2)O(2) + H(+) + sulfate." [EC:1.8.3.1, RHEA:24600]
xref: MetaCyc:PWY-5326
xref: MetaCyc:SULFITE-OXIDASE-RXN

id: GO:0016041 done
name: glutamate synthase (ferredoxin) activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 L-glutamate + 2 oxidized ferredoxin = L-glutamine + 2-oxoglutarate + 2 reduced ferredoxin + 2 H+. This is a two-step reaction: (a) L-glutamate + NH3 = L-glutamine + H2O, (b) L-glutamate + 2 oxidized ferredoxin + H2O = NH3 + 2-oxoglutarate + 2 reduced ferredoxin + 2 H+." [EC:1.4.7.1]
xref: MetaCyc:GLUTAMATE-SYNTHASE-FERREDOXIN-RXN
xref: MetaCyc:PWY-4341

id: GO:0016290 done
name: palmitoyl-CoA hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: palmitoyl-CoA + H2O = CoA + palmitate." [EC:3.1.2.2]
xref: MetaCyc:PALMITOYL-COA-HYDROLASE-RXN
xref: MetaCyc:PWY-5148

id: GO:0019139 done
name: cytokinin dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: N6-dimethylallyladenine + acceptor + H2O = adenine + 3-methylbut-2-enal + reduced electron acceptor." [EC:1.5.99.12]
xref: MetaCyc:1.5.99.12-RXN
xref: MetaCyc:PWY-2841

id: GO:0050029 done 
name: L-lysine oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-lysine + H(2)O + O(2) = 6-amino-2-oxohexanoate + H(2)O(2) + NH(4)(+)." [EC:1.4.3.14, RHEA:14437]
xref: MetaCyc:L-LYSINE-OXIDASE-RXN
xref: MetaCyc:PWY-5311

id: GO:0050065 done
name: lysine-pyruvate 6-transaminase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-lysine + pyruvate = L-alanine + L-allysine." [EC:2.6.1.71, RHEA:19393]
xref: MetaCyc:LYSINE--PYRUVATE-6-AMINOTRANSFERASE-RXN
xref: MetaCyc:PWY-5324

id: GO:0050303 done
name: lysine 6-dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + NAD+ + L-lysine = NH3 + NADH + allysine." [EC:1.4.1.18, MetaCyc:LYSINE-6-DEHYDROGENASE-RXN, RHEA:12408]
xref: MetaCyc:LYSINE-6-DEHYDROGENASE-RXN
xref: MetaCyc:PWY-5314

id: GO:0050378 done
name: UDP-glucuronate 4-epimerase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-alpha-D-glucuronate = UDP-alpha-D-galacturonate." [EC:5.1.3.6, RHEA:11404]
xref: MetaCyc:PWY-4861
xref: MetaCyc:UDP-GLUCURONATE-4-EPIMERASE-RXN

**Comment by hdrabkin** [comment]
Added all.
