### ISSUE TITLE
Merge "DNA metabolic process" terms in BP  slim

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22392]
https://github.com/geneontology/go-ontology/issues/22294
HI @pgaudet , i think for the generic slim purposes, since we are interested in modularity (reduced overlap) and we don't want the slim to get too large we should probably revert to 
DNA recombination
DNA replication
DNA repair
in the generic slim.
The individual terms have always been present in the  PomBase  slim because we have very active communities for these  3 processes but I don't think this is a valuable split for the generic slim (and we might move to the more general term for the PomBase slim).  
I  kept meaning to comment on this...

**Comment by pgaudet** [comment]
So, we'd use 'DNA metabolic process' instead of these 3 terms? 
The terms just doesn't sound very informative. 

@hattrill @RLovering

**Comment by hattrill** [comment]
I think that I would prefer the separate terms:
DNA recombination
DNA replication
DNA repair
DNA metabolic process does not seem to be very informative.

**Comment by ValWood** [comment]
OK, for pombe the existing terms are OK, but they are the most non-modular part of the cellular process terms, but if everyone wants to keep the specificity that's fine.
