### ISSUE TITLE
positive regulation of mating projection assembly (GO:1902917) parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22398]
positive regulation of mating projection assembly (GO:1902917)

could a part_of link be added to conjugation with cellular fusion?
Currently annotations are not propagating (because they do not propagate over regulation of regulation)

**Comment by raymond91125** [comment]
These two terms are already connected in the hierarchy.
Shouldn't we fix this problem in AmiGO closure as opposed to adding 'by-pass' in the ontology?
![image](https://user-images.githubusercontent.com/619520/143957105-4e717351-e9a9-4723-b7bb-e5ab389afbbc.png)

**Comment by raymond91125** [comment]
In AmiGO, the Inferred Tree View shows an open square (I don't know what it means) for the relationship between "positive regulation of mating projection assembly" and "conjugation with cellular fusion"; part_of it is not. Similarly between "regulation of mating projection assembly" and "conjugation with cellular fusion"; the relation chain is regulate->part_of->part_of.
I am confused with all these relations myself.

**Comment by ValWood** [comment]
@pgaudet  do you agree that, if you regulate a sub part of a process you don't necessarily regulate the whole process. People who study conjugation would expect that "regulation of conjugation with cellular fusion" would be the genes that start or stop the process from occurring. I think this issue has been discussed  in other contexts but I'm not sure if a definite decision was made. Is it OK to remove the inappropriate "regulation of" links and instantiate part of links in these cases?

**Comment by raymond91125** [comment]
"regulation of mating projection assembly part_of conjugation with cellular fusion"
is what's being added.

**Comment by pgaudet** [comment]
> @pgaudet do you agree that, if you regulate a sub part of a process you don't necessarily regulate the whole process. 

Hi @ValWood 

No, this is not how the relations inferences work. If you regulate part_of a process, you regulate the process. This seems right - if a step of a subprocess is rate limiting the entire process will be slowed down, won't it? 

I am not sure what you are trying to capture.

**Comment by ValWood** [comment]
I think this is a general issue with GTPases and their regulators.

Here is an example
cdc42 is regulating the assembly of the mating projection tip
https://www.pombase.org/reference/PMID:23200991
as part of the overall program of "conjugation with cellular fusion".

Users would definitely expect to  find cdc42 in the "conjugation with cellular fusion" bin for slimming and enrichment. Currently it would  not be there because it is regulating a sub process..

Some historical discussion implied that a gene product could be both regulating a process and part_of a process simultaneously. 
More recent discussions   suggested that GTPases should sometimes be annotated as
molecular function regulators and part_of processes. 
I am not sure if this is the correct  way to annotate because most GTPases are not annotated in this way.

I was hoping we could look at examples of GTPase annotations  on an annotation call.

**Comment by pgaudet** [comment]
If you annotate to MF regulator activity then this will not be transitive. We need to think carefully about how we model this, there is probably some inconsistency that leads to missing/unexpected inferences. I think making a GO-CAM would help.

**Comment by ValWood** [comment]
I think you are right. I don't even know if we have enough information yet to annotate all of the conjugation steps. I think both the annotations and the ontology need review (I won't have time to do this for a while)

@raymond91125  apologies, could you remove the relation I suggested?
Then you  can assign the ticket to me as a mini project.

**Comment by raymond91125** [comment]
I closed the PR without merging.
