### ISSUE TITLE
NTR: Muramoyltetrapeptide carboxypeptidase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22390]
* **Suggested term label:**
Muramoyltetrapeptide carboxypeptidase activity

* **Definition (free text)**
GlcNAc-MurNAc-L-alanyl-gamma-D-glutamyl-meso-diaminopimelyl-D-alanine + H(2)O <=> GlcNAc-MurNAc-L-alanyl-gamma-D-glutamyl-meso-diaminopimelate + D-alanine

* **Reference, in format PMID:#######**
PMID: 15361936
PMID: 10428950

* **Gene product name and ID to be annotated to this term**
Q9VYX7 PGRP-SA(Drosophila melanogaster)
also, E.coli ldcA & mepS (P76008 & P0AFV4)

* **Parent term(s)**
From the EC xref, parent should be GO:0004181 metallocarboxypeptidase activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* EC 3.4.17.13, RHEA:48688

* **Any other information**

**Comment by sjm41** [comment]
Hmmm...
- UniProt entry for P76008 has EC:3.4.17.13 but says its a serine-type peptidase and links to MEROPS family S66.002...
- UniProt entry for P0AFV4 EC:3.4.17.13 but says says its a cysteine-type peptidase and links to MEROPS family C40.004...

So maybe parent of this term should just be  GO:0004180 carboxypeptidase activity??

Can't easily tell  the reason/explanation for mismatch between EC annotation (which says it's a metallo-type) and the other UniProt info....

**Comment by sjm41** [comment]
Hi @hdrabkin 
Can we add this new term please?  Your insights on the correct parent to use are very welcome!

**Comment by hdrabkin** [comment]
Added new term with  GO:0004180 parent.  Could the uniprot entries be annotation issues? (I was holding off in case someone with better specific knowledge chimed in

+id: GO:0106415
+name: muramoyltetrapeptide carboxypeptidase activity
+namespace: molecular_function
+def: "GlcNAc-MurNAc-L-alanyl-gamma-D-glutamyl-meso-diaminopimelyl-D-alanine + H(2)O = GlcNAc-MurNAc-L-alanyl-gamma-D-glutamyl-meso-diaminopimelate + D-alanine." [PMID: 10428950, PMID: 15361936]
+xref: EC:3.4.17.13
+xref: RHEA:48688
+is_a: GO:0004180 ! carboxypeptidase activity

**Comment by sjm41** [comment]
Thanks Harold.
