### ISSUE TITLE
Rhea mapping to GO:0102196 can be improved

### ISSUE THREAD

**Issue by aimol** [geneontology/go-ontology#22406]
@hdrabkin I found GO:0102196 (cortisol dehydrogenase activity) is mapped to Rhea:53484 which involves 11-oxotestosterone as participant and not cortisol. We have recently created a reaction involving cortisol that is a better match for  GO:0102196, so please consider mapping to Rhea:68616

**Comment by hdrabkin** [comment]
I have removed RHEA:53484 and replaced it with RHEA:68616. Note however that the public ontology files will show no RHEA mapping until the new RHEA term is made public at RHEA.
