### ISSUE TITLE
Rhea mapping to GO:0072582 can be improved

### ISSUE THREAD

**Issue by aimol** [geneontology/go-ontology#22407]
Dear @hdrabkin,
GO:0072582 (17-beta-hydroxysteroid dehydrogenase (NADP+) activity) is currently mapped to RHEA:24616 which involves 11-beta-estradiol as participant (a specific instance of the 17-beta-hydroxysteroid class). We have recently created a reaction for the 17-beta-hydroxysteroid class that is a better match for GO:0072582, so please consider mapping to Rhea:69284.

**Comment by hdrabkin** [comment]
Done; please note that the new RHEA will not appear in public versions of the ontology until the RHEA is public. The old RHEA however is removed. 
The RHEA will appear in the editor's ontology version.

**Comment by pgaudet** [comment]
Email @aimol about the NAD+ reaction GO:0044594 17-beta-hydroxysteroid dehydrogenase (NAD+) activity, for which no RHEA was proposed. Reply: 

Dear Pascale,
Thanks for your message, I had to read the ticket to remember it, hahaha! Yes, we do have a reaction that uses NAD+:
RHEA:24612 (https://www.rhea-db.org/rhea/24612)
17beta-estradiol + NAD(+) = estrone + H(+) + NADH
It is mapped to https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0044594
Is that the term you were referring to?
All the best,
Lucila

**Comment by pgaudet** [comment]
Hi @aimol 

Thanks for the quick reply. So are you saying that 17-beta-hydroxysteroid  is the same as 17beta-estradiol? If that's the case we need to merge a few terms. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
17-beta-hydroxysteroid (CHEBI:35343)  vs. 17 beta-estradiol (CHEBI:16469). (the latter being a specific type of the former)
The structures are different. They are not the same.
