### ISSUE TITLE
Additional synonyms for GO:0038061

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#22415]
Hello,

Could I please request these additional synonyms be added to GO:0038061 NIK/NF-kappaB signaling, if appropriate?

NIK-IKK Cascade
NIK-IKK Kinase Cascade
NIK-IKK Signaling Pathway
NIK-IKK-α cascade

These synonyms are used in the literature, e.g. PMID: 10094049, PMID: 10581243, PMID: 9244310.

Thanks,
Rachael.

**Comment by krchristie** [comment]
Hi @rachhuntley - sorry so slow to get to this. 

I wasn't completely sure what type of synonym to put in, so I put them all in as "related" synonyms. Let me know if they should be a different type of synonym.

Also, for the 4th one on your list, I can't use the Greek letter, so for this one: "NIK-IKK-α cascade", I put it in as "NIK-IKK-alpha cascade"

Thanks,

-Karen

**Comment by rachhuntley** [comment]
Hi Karen,
That's great, thanks for doing this.
Rachael.
