### ISSUE TITLE
Check comment on  GO:0032810 sterol response element binding

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#22417]
Hi 
I thought it was agreed that specific dbTF motif binding sites were going to be created as new GO terms but on this record is the comment:

Note that as agreed during the transcription overhaul, terms specifying binding to specific transcription regulatory motifs are no longer being created. The level of specificity GO has decided to go to is the "core promoter", "core promoter proximal region" and "enhancer". To capture more detail, please consider using column 16.

Please confirm decision and / or remove this comment from this and any other records.

Thanks
Ruth

**Comment by pgaudet** [comment]
You're right, we have decided to actually instanciate the terms. I'll delete that, thanks
