### ISSUE TITLE
GO:1990877   Lst4-Lst7 complex term name update

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22426]
GO:1990877   Lst4-Lst7 complex

Definition (GO:1990877 GONUTS page)
A heterodimeric complex that functions as a GTPase-Activating Protein (GAP) Complex for members of the Rag family of GTPases. In the budding yeast, this complex contains Lst4 and Lst7, while the orthologous mammalian complex contains Follicular (FLCN) and either follicular interaction protein 1 (FNIP1) or FNIP2. PMID:24095279 PMID:26387955

Please could we update these labels from related to exact. These are alternative names for the human complex
FLCN-FNIP2 complex	related
FLCN-FNIP1 complex	related
FNIP-Folliculin RagC/D GAP complex	related

could we make 
FNIP-Folliculin RagC/D GAP complex the primary name (more species neutral)

also add 
exact "BFC complex" (the pombe name). I will provide PMID for this shortly, it isn't available yet.

thanks
Val

**Comment by pgaudet** [comment]
Reference for BFC complex: PMID:34805795
