### ISSUE TITLE
NTR: Function terms for RNAs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#22441]
Hi

I am not sure if this should be an ontology request or an annotation request. It depends what the decision on the discussion below is.

I think we need to have function terms for ncRNAs. The only GO functions for a miR are binding terms.  

The term GO:1903231 mRNA binding involved in posttranscriptional gene silencing was created to provide a term which describes the canonical function of a miR, but this is linked to the process and so the proposal is to remove this term.

However if we compare this to a protein activity term like  GO:0004888 transmembrane signaling receptor activity this has no process parent although its child term  GO:0004930 G protein-coupled receptor activity has the BP parent:  GO:0007186
G protein-coupled receptor signaling pathway
Really GO:0004888 transmembrane signaling receptor activity should have the BP parent  GO:0007165 signal transduction

The point I am making is that we are removing GO:1903231 mRNA binding involved in posttranscriptional gene silencing because the term name has a process in it. And yet many of the protein MF tems have a process parent (either included or implied just not listed as a parent). I am suggesting that MF terms need to be created for ncRNAs and this issue needs to be addressed before the removal of the annotations associated with the term GO:1903231 mRNA binding involved in posttranscriptional gene silencing.

1. I have not felt happy about annotating miRs that bind DNA and regulate transcription as DNA-binding transcription factors, mostly because I do not know their mechanism of action
http://europepmc.org/article/MED/25336585 suggests that let-7i should be annotated as a DNA-binding transcription factor - is this acceptable?

2. Some miRs inhibit translation via inhibition of the translational machinery, can these be associated with the MF term:
 GO:0008135 translation factor activity, RNA binding

3. Other miRs inhibit translation via degradation of the mRNA for these a new term would be needed and ideally the definition of the term  GO:0090079 translation regulator activity, nucleic acid binding (and parent terms) should be modified to enable this to be the parent of:
New term:  translation regulator activity, mRNA binding
Definition: Any selective and non-covalent interaction with an mRNA that involved in mRNA degradation and subsequent reduction in polypeptide synthesis at the ribosome.

4. LncRNAs act as sponges to miRs could we have:
New term: miRNA inhibitor activity
Definition: Binds to and stops, prevents or reduces the activity of a miRNA, a small single-stranded non-coding RNA molecule (usually containing about 22 nucleotides) that functions in gene silencing

5. Other ncRNA MF terms may also be required

Thanks

Ruth

**Comment by RLovering** [comment]
@hattrill @gantonazzo @

**Comment by pgaudet** [comment]
Discussion on miRNA call @RLovering @gantonazzo @hattrill @ValWood 
Fix the existing term 'GO:1903231 mRNA binding involved in posttranscriptional gene silencing' 
- [ ]  Change term label to 'mRNA binding translation repressor activity'
- [ ] Change def to: A translation repressor activity that acts by binding to an mRNA. The binding can result in targeting the mRNA for degradation or interfering with mRNA translation, hence resulting in posttranscriptional gene silencing.
- [ ] Add refs 
- [ ] Merge parent (no anontations)  GO:0150100  RNA binding involved in posttranscriptional gene silencing into GO:1903231

**Comment by pgaudet** [comment]
After some exchanges by email, it was proposed to change the label to 'mRNA base-pairing posttranscriptional repressor activity' to exclude proteins that bind mRNA and recruit another complex and/or interfere with directly with translation in some manner or promote any number of mRNA degradation hastening MFs such as decapping, deadenylation, etc.

**Comment by pgaudet** [comment]
+ change is_ a to 'has part' some 'mRNA binding'
