### ISSUE TITLE
NTR: [novofumigatonin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#22449]
I would propose the creation of a BP term for the biosynthesis of novofumigatonin.

"novofumigatonin biosynthetic process"

I would only create the biosynthesis terms since in general there are no degradation pathways of these metabolites (only few exceptions).

Definition:
The chemical reactions and pathways resulting in the formation of novofumigatonin, a heavily oxygenated meroterpenoid containing a unique orthoester moiety.

PMID: 29968715

Synonyms:

novofumigatonin synthesis, novofumigatonin biosynthesis, novofumigatonin formation, novofumigatonin anabolism (EXACT)

Proteins to be annotated:

nvfA A0A2I1BSV9 RHEA:49628
nvfB A0A2I1BT09 RHEA:49632
nvfC A0A2I1BSW8 RHEA:67044
nvfD A0A2I1BT15 Alpha/beta hydrolase 
nvfE A0A2I1BSW6 RHEA:67100
nvfF A0A2I1BSZ6 RHEA:67104
nvfG A0A2I1BT56 Ketoreductase 
nvfH A0A2I1BSU0  RHEA:67048, RHEA:67052
nvfI A0A2I1BSX0 RHEA:67096
nvfJ A0A2I1BSV7 RHEA:67056, RHEA:67060
nvfK A0A2I1BSV1 RHEA:67036
nvfL A0A2I1BT01 RHEA:67040
nvfM A0A2I1BSW0 RHEA:67064, RHEA:67068

Parent terms:
GO:0016114 terpenoid biosynthetic process

Child terms: (to create)
No regulation terms yet.

Taxon constraint: Only in taxon 4751 Fungi

has_primary_output: CHEBI:156460 novofumigatonin

Thanks a lot.
Best regards,
Marc

**Comment by dianeoinglis** [comment]
Hi all,

As part of the Aspergillus secondary metabolite biosynthetic gene cluster annotation project I lead at AspGD (PMID: 23617571), we made all the NTRs such as this one, children of GO:0044550 'secondary metabolite biosynthetic process.' Unfortunately, this does not happen automatically based on CheBI and was part of the process when creating terms for new secondary metabolite biosynthetic processes. It would be nice to keep things consistent. Also, plants make secondary metabolites like fungi, I'd be cautious with the "Only in fungi" taxon restriction.

I hope this is helpful. I've been out of the loop for a while and just returning to active status.
Diane Inglis

**Comment by marcfeuermann** [comment]
Hi Diane,
Thanks for your feedback. Indeed, all these terms should be children of GO:0044550 'secondary metabolite biosynthetic process. We are aware that plants as well as bacteria, also produce many secondary metabolites. So the aim is not to systematically add a taxon restriction, but to add it when the final compounds is only produced in fungi (especially some famous mycotoxins). Of course, this could be corrected in the future if it appears that other species than fungi can also produce  a certain compound.
Best regards,
Marc.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140782
+name: novofumigatonin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of novofumigatonin, a heavily oxygenated meroterpenoid containing a unique orthoester moiety." [PMID:29968715]
+synonym: "novofumigatonin anabolism" EXACT []
+synonym: "novofumigatonin biosynthesis" EXACT []
+synonym: "novofumigatonin formation" EXACT []
+synonym: "novofumigatonin synthesis" EXACT []
+is_a: GO:0016114 ! terpenoid biosynthetic process
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:156460 ! novofumigatonin
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22449 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-31T11:37:31Z
