### ISSUE TITLE
meiotic G2 phase obsolete

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22453]
Please provide as much information as you can:

* **GO term ID and Label**

meiotic G2 phase
The cell cycle 'gap' phase which is the interval between the completion of DNA synthesis and the beginning of DNA segregation by meiosis.

* **Reason for deprecation**

I had never heard of this but Googling I found:
PMID: 16546077
by A Hochwagen Angelika Amon· 2006 · Cited by 169 — ... after premeiotic DNA replication (Figure 1B), during a stage that has variably been called meiotic prophase and meiotic G2 phase.

* **"Consider" term(s) (ID and label)**

GO:0007128    meiotic prophase I

* **Are there annotations to this term?**
- How many EXP:
Not that the check here will need to be for EXTENSIONS that use this term because
there are no direct annotations to 'phase' terms.

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by pgaudet** [comment]
would all annotations be under the 'happens during' extension? or others?

**Comment by ValWood** [comment]
As far as I know, they should all be happened during.
There may also be use by phenotype ontologies.

**Comment by pgaudet** [comment]
Lets' do this with GO:0051330 meiotic G1 phase to make the same decision

#22451
