### ISSUE TITLE
Merge up GO:0106306 protein serine phosphatase activity and GO:0106307 protein threonine phosphatase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22458]
Hello, 

GO:0106306 protein serine phosphatase activity and GO:0106307 protein threonine phosphatase activity were created to match RHEA, like they counter part kinase activities. These were merged up in #20114, since they dont correspond to GO functions, ie the terms are more specific than the enzymes they describe. 

So I will merge GO:0106306 protein serine phosphatase activity and GO:0106307 protein threonine phosphatase activity into their parent 'GO:0004722 protein serine/threonine phosphatase activity', since this is the specificity of the enzyme. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Might we nice to change the rheas to narrowmatch?

**Comment by pgaudet** [comment]
I thought I did that?

**Comment by hdrabkin** [comment]
Ok, I didn't actually check today; was just wondering; I'll look later when I go in this afternoon to address some sjm ticket
