### ISSUE TITLE
Missing parent: [GO term] GO:0035064    methylated histone binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22456]
* **GO term ID and label for which you request a new superclass**

GO:0035064    methylated histone binding
should this be a descendant of
GO:0031493    nucleosomal histone binding

If this is not possible, is the term "GO:0031493    nucleosomal histone binding" very useful

(we have 2 way of annotating the same thing here)

@colinlog 
@pgaudet

**Comment by pgaudet** [comment]
Discussion on transcription call: methylated histones can be in the nucleosomes OR in the nucleoplasm, before it gets desposited, so we will not changed this.
