### ISSUE TITLE
NTR: [lovastatin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#22454]
I would propose the creation of a BP term for the biosynthesis of lovastatin:

"lovastatin biosynthetic process"

I would only create the biosynthesis terms since in general there are no degradation pathways of these metabolites (only few exceptions).

Definition:
The chemical reactions and pathways resulting in the formation of lovastatin (also known as mevinolin, mevacor or monacolin K), a hypolipidemic inhibitor of (3S)-hydroxymethylglutaryl-coenzyme A (HMG-CoA) reductase (HMGR).

PMID: 10334994, 10381407

Synonyms:
lovastatin synthesis, lovastatin biosynthesis, lovastatin formation, lovastatin anabolism (EXACT)
and
mevinolin biosynthetic process, mevinolin synthesis, mevinolin biosynthesis, mevinolin formation, mevinolin anabolism (EXACT)
and
mevacor biosynthetic process, mevacor synthesis, mevacor biosynthesis, mevacor formation, mevacor anabolism (EXACT)
and 
monacolin K biosynthetic process, monacolin K synthesis, monacolin K biosynthesis, monacolin K formation, monacolin K anabolism (EXACT)

Proteins to be annotated:
lovA, Q9Y7C8 RHEA:42368 and RHEA:29599
lovB, Q9Y8A5 RHEA:18565
lovC, Q9Y7D0 RHEA:18565
lovD, Q9Y7D1 RHEA:43064
lovF, Q9Y7D5 RHEA:42852
lovG, Q9Y7C9 RHEA:11592

Parent terms:
GO:0030639 polyketide biosynthetic process
GO:0043386 mycotoxin biosynthetic process

Child terms: (to create)
Positive regulation of lovastatin biosynthetic process

Protein that can be annotated with positive regulation of lovastatin biosynthetic process:

lovE, Q9Y7D3 transcription factor from PMID:10334994, 19781329

Taxon constraint: Only in taxon 4751 Fungi

has_primary_output: CHEBI:40303 lovastatin

BioCyc ID: PWY-7535 
KEGG: M00893

Thanks a lot.
Best regards,
Marc

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140735
+name: lovastatin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of lovastatin (also known as mevinolin, mevacor or monacolin K), a hypolipidemic inhibitor of (3S)-hydroxymethylglutaryl-coenzyme A (HMG-CoA) reductase (HMGR)." [PMID:10334994, PMID:10381407]
+synonym: "lovastatin anabolism" EXACT []
+synonym: "lovastatin biosynthesis" EXACT []
+synonym: "lovastatin formation" EXACT []
+synonym: "lovastatin synthesis" EXACT []
+synonym: "mevacor anabolism" EXACT []
+synonym: "mevacor biosynthesis" EXACT []
+synonym: "mevacor biosynthetic process" EXACT []
+synonym: "mevacor formation" EXACT []
+synonym: "mevacor synthesis" EXACT []
+synonym: "mevinolin anabolism" EXACT []
+synonym: "mevinolin biosynthesis" EXACT []
+synonym: "mevinolin biosynthetic process" EXACT []
+synonym: "mevinolin formation," EXACT []
+synonym: "mevinolin synthesis" EXACT []
+synonym: "monacolin K anabolism" EXACT []
+synonym: "monacolin K biosynthesis" EXACT []
+synonym: "monacolin K biosynthetic process" EXACT []
+synonym: "monacolin K formation" EXACT []
+synonym: "monacolin K synthesis" EXACT []
+xref: KEGG_PATHWAY:M00893
+xref: MetaCyc:PWY-7535
+is_a: GO:0030639 ! polyketide biosynthetic process
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:40303 ! lovastatin
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22454 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-26T12:23:06Z
+
+[Term]
+id: GO:0140736
+name: positive regulation of lovastatin biosynthetic process
+namespace: biological_process
+def: "Any process that increases the rate, frequency or extent of the chemical reactions and pathways resulting in the formation of lovastin." [PMID:10334994, PMID:19781329]
+synonym: "positive regulation of mevacor biosynthetic process" EXACT []
+synonym: "positive regulation of mevinolin biosynthetic process" EXACT []
+synonym: "positive regulation of monacolin K biosynthetic process" EXACT []
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0140735 ! lovastatin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22454 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-26T12:33:56Z

**Comment by pgaudet** [comment]
@marcfeuermann I suppose I can add the axon constraint  Only in taxon 4751 Fungi to the parent class  GO:0043386  mycotoxin biosynthetic process? That would also cover all children term we will create later. 


Thanks, P
ascale

**Comment by pgaudet** [comment]
In fact  this is what I did already for the last terms you requested.

**Comment by marcfeuermann** [comment]
This is indeed a very good idea. Thanks a lot for dealing with these terms.
Marc.
