### ISSUE TITLE
Remove EC reference from 'GO:0017020 myosin phosphatase regulator activity' def

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22450]
Small thing - can you remove the EC:3.1.3.16 reference from the definition line for the term below?
Thanks.

id: GO:0017020
name: myosin phosphatase regulator activity
namespace: molecular_function
def: "Binds to and modulates of the activity of myosin phosphatase." [EC:3.1.3.16, GOC:ai]
synonym: "myosin phosphatase, intrinsic regulator activity" NARROW []
is_a: GO:0019888 ! protein phosphatase regulator activity

**Comment by pgaudet** [comment]
EC:3.1.3.16 def: [a protein]-serine/threonine phosphate + H(2)O <=> [a protein]-serine/threonine + phosphate
corresponds to 
GO:0004722	protein serine/threonine phosphatase activity

Other terms mapped to EC:3.1.3.16: 

- [x] GO:0004723	calcium-dependent protein serine/threonine phosphatase activity OK same mapping in UniProt, for eg P49593
- [x]  GO:0008597	calcium-dependent protein serine/threonine phosphatase regulator activity -> remove
- [x] GO:0005963	magnesium-dependent protein serine/threonine phosphatase complex  -> remove 
- [x] GO:0017018	myosin phosphatase activity -> change EC to narrowMatch
- [x] GO:0017023	myosin phosphatase complex -> remove; no annotations, no references. Add PMID:30076859

- [ ] GO:0106306	protein serine phosphatase activity -> only IEAs   -> remove 
- [ ] GO:0106307	protein threonine phosphatase activity -> only IEAs  -> remove

**Comment by sjm41** [comment]
Thanks @pgaudet for fixing that (and all the related issues you found!)
