### ISSUE TITLE
NTR: encapsulin nanocompartment + rename a similar term

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#22465]
Hi, I'm annotating a new bacterial and archaeal organelle in UniProtKB/Swiss-Prot, which I will call the encapsulin nanocompartment. I need a cellular component GO term for this please.

My definition suggestion is :
Proteinaceous polyhedral shells that encapsulate enzymes, protecting the contents from their surrounding milieu and/or the milieu from reactants in their interior. The self-assembling, 25-42 nm nanocompartment shell, unlike larger bacterial microcompartments, is made of only 1 protein, and has only a few proteins inside. Shells about vary from about 25-42 nm in diameter. The shell protein has an HK97-like fold and probably evolved from a viral protein. Artificial encapsulin nanocompartments can be expressed and filled with cargo proteins for biotechnological uses. They are found in many bacterial and a few archaeal phyla.

A recent review is PMID 32918485.

It should be a child of GO:0043232 (intracellular non-membrane-bounded organelle), and currently I don't think there is any necessity for child terms. There are no GO terms I can see that should be under this term.

Synonyms:
protein nanocompartment (broad)

Encapsulin nanocompartment should be restricted to bacteria and archaea.

I would also like to suggest renaming the "sibling" compartment GO:0031469 (polyhedral organelle) to bacterial microcompartment (one of its synonyms). "polyhedral organelle" is a bit misleading, encapsulin nanocompartments are also polyhedral, and bacterial microcompartment is the term most used in the literature currently. The papers cited for GO:0031469 are quite old, I would add a recent review (PMID 34340100 and/or 34058518), note that most current papers are about the biotechnological uses of BMCs. New synonyms should include BMC, MCP.
This term should be restricted to bacteria.

One last thing, can @Antonialock please link the UniProtKB keyword KW-1283 and subcellular location SL-0544 (both are bacterial microcompartment) to GO:0031469 please? 
Thanks,

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140737
+name: encapsulin nanocompartment
+def: "Intracellular non-membrane bound organelle, consisting of proteinaceous polyhedral shells that encapsulate enzymes, protecting the contents from their surrounding milieu and/or the milieu from reactants in their interior. The self-assembling, 25-42 nm nanocompartment shell, unlike larger bacterial microcompartments, is made of only 1 protein, and has only a few proteins inside. Shells about vary from about 25-42 nm in diameter. The shell protein has an HK97-like fold and probably evolved from a viral protein. Artificial encapsulin nanocompartments can be expressed and filled with cargo proteins for biotechnological uses. They are found in many bacterial and a few archaeal phyla." [PMID:32918485]
+synonym: "protein nanocompartment" BROAD []
+is_a: GO:0043232 ! intracellular non-membrane-bounded organelle
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22465 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-29T09:16:25Z
