### ISSUE TITLE
FACT complex update definition

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22464]
The definition of  FACT is currently:

An abundant nuclear complex, which was originally identified in mammalian systems as a factor required for transcription elongation on chromatin templates. 

Which is not necessary and sufficient (other complexes are required for transcription elongation)

Followed by a large amount of post-punctuation  "gloss":

The FACT complex has been shown to destablilize the interaction between the H2A/H2B dimer and the H3/H4 tetramer of the nucleosome, thus reorganizing the structure of the nucleosome. In this way, the FACT complex may play a role in DNA replication and other processes that traverse the chromatin, as well as in transcription elongation. FACT is composed of two proteins that are evolutionarily conserved in all eukaryotes and homologous to mammalian Spt16 and SSRP1. In metazoans, the SSRP1 homolog contains an HMG domain; however in fungi and protists, it does not. For example, in S. cerevisiae the Pob3 protein is homologous to SSRP1, but lacks the HMG chromatin binding domain. Instead, the yFACT complex of Spt16p and Pob3p, binds to nucleosomes where multiple copies of the HMG-domain containing protein Nhp6p have already bound, but Nhp6p does not form a stable complex with the Spt16p/Pob3p heterodimer. [PMID:16678108, PMID:12934006, PMID:12934007]

all of the required part of the  definition should be before the period.

Suggest updating along the lines of
A histone chaperone complex that facilitates nucleosome reassembly after RNA polymerase II passage at transcribed genes, and facilitates heterochromatin spreading by regulating histone turnover and H3K9 methylation states  (maybe also need something about replication role?)

(Duina et al., 2007; Formosa and Winston, 2020; Lee et al., 2017; Murawska et al., 2020; Orphanides et al., 1998) + PMID:34731638

@colinlog 
@pgaudet

**Comment by pgaudet** [comment]
Def improved and made more general for other species with the help of @colinlog on transcription WG call
"A histone chaperone complex that facilitates nucleosome disassembly and reassembly after DNA or RNA polymerase passage. "
