### ISSUE TITLE
heterochromatin maintenance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22473]
I think we might need to re-create 
GO:0070829    obsolete heterochromatin maintenance

 A new term is necessary because the old term was not correctly defined.

heterochromatin maintenance means
"Heterochromatin maintenance is the process of restoring histone modification profiles after DNA replication. As the replication fork moves forward, parental histones are deposited back to the original location and intermixed with newly synthesized his- tones. Parental histones containing H3K9me3 serve as signals for the recruitment of Clr4 to modify newly synthesized histones, restoring the H3K9me3 domain"

I can provide many references, but here is a useful  (current) review:
Leaving histone unturned for epigenetic inheritance
Chun-Min Shan*, Yimeng Fang and Songtao Jia
PMID: 34726351

Maybe we already have an equivalent term but this would need to be added as a synonym (most of the papers I am reading refer to a nucleation step and a maintenance step which have different components)

@colinlog 
@pgaudet

**Comment by pgaudet** [comment]
@ValWood is this now handled by the new terms we have created ? See https://github.com/geneontology/go-ontology/issues/22135#issuecomment-1065188656

**Comment by ValWood** [comment]
I think it will be OK.
