### ISSUE TITLE
Query: [heterochromatin spreading]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22471]
In some recent revisions  "regulation of heterochromatin spreading" and heterochromatin boundary formation were merged.

However, according to 
the FACT complex does have a distinct role in "heterochromatin spreading" as opposed to "boundary formation. The 2 different components have been dissected genetically.

Abstract says:
"Heterochromatin formation requires three distinct steps: nucleation, self-propagation (spreading) along the chromosome, and faithful maintenance after each replication cycle. Impeding any of those steps induces heterochromatin defects and improper gene expression"

"Deletions of leo1+ or mst2+ did not suppress pob3Δ silencing defects at the mating-type locus, pericentromeres, and subtelomeres (Figures 3A–3D). This result is in agreement with the main functions of these factors in maintaining euchromatin by preventing spreading
of heterochromatin or the ectopic assembly beyond its natural boundaries. In contrast, deletion of epe1+ suppressed the pob3Δ silencing defects nearly to levels as in the WT
cells at all tested heterochromatic regions (Figures 3E and 3F). Moreover, epe1Δ reduced the expression of several subtelomeric genes in pob3Δ, suggesting that it also counteracts heterochromatin spreading (Figure 3G). To test this more directly, we performed the
HSS assay in the double spt16–1epe1Δ mutant. Indeed, heterochromatin spreading was completely restored (Figure 3H, compare with Figure 2D). Together, our suppressor analysis revealed that the Epe1 pathway specifically suppresses silencing and spreading defects of FACT mutants, supporting the distinct function of FACT in heterochromatin spreading."

Do we want to represent these 'sub processes of heterochromatin assembly'
(for instance the  siRNA pathways are only involved in nucelation as far as I know. We definitely seem to have a situation where different modules are involved in nucleation, spreading and boundary formation.

PMID:34731638

@colinlog 
@pgaudet

**Comment by ValWood** [comment]
<img width="586" alt="Screenshot 2021-11-26 at 17 21 16" src="https://user-images.githubusercontent.com/7359272/143614718-6339a9b8-5cbd-4538-a87b-e31112c7f0ee.png">

**Comment by ValWood** [comment]
So FACT is usually described as a histone chaperone. But I dion't think it fits the new definitions. I don't know how mechanistically, but it *prevents*  histone exchange of H2-me3 for H2Me2.

That does not fit this definition 
"Binding to and carrying a histone or a histone complex until it is deposited on DNA, or degraded"
if the histone does not leave the DNA???

Does this definition need to be broader?
Related : https://github.com/geneontology/go-ontology/issues/22290

**Comment by ValWood** [comment]
This might be helpful:

"How can a histone chaperone facilitate the transition of H3K9me2 to H3K9me3? In
contrast to mono- and dimethylation, the methylation rate of H3K9me3 by Clr4 is very
slow (Al-Sady et al., 2013). The molecular mechanism of this reaction step is not fully understood. Histone turnover rates are critical for establishing methylation states (Chory et al., 2019), and an increased histone turnover was shown in pob3Δ for the mating-type locus (Holla et al., 2020). Thus, we hypothesized that increased histone turnover in the absence of FACT impairs H3K9 trimethylation by Clr4."

**Comment by ValWood** [comment]
We made the decision specify 'spreading' because some genes are not involved in nucleation but are required to propagate the heterochromatin once it is established.  A lot of papers also mention 'establishment' and 'maintenance' which also seem to be different pathways. If I understand correctly, nucleation and spreading are spatial and establishment and maintenance are temporal. I think both of these could be important to recognise. For example some genes are dispenesible once the heterochromatin is established, but they are required to establish it. Other pathways are required to maintain over generations once it is established.

**Comment by colinlog** [comment]
I would prefer to discuss this together to come to a consensus decision.

**Comment by pgaudet** [comment]
Discussion with @ValWood @colinlog 
We decided not to restore spreading; heterochromatin assembly covers this.
