### ISSUE TITLE
Design pattern for protein-containing complex formation and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22488]
Hello, 

Last week, @ukemi @vanaukenk and I noticed a discrepancy between the relations ''results in organization of', and  its children, results in assembly of', 'results in disassembly of' 'results in remodeling of', and how these are used in the ontology. 

Results in organization of is a child of 'has anatomical participant', which is certainly wrong for protein-containing complexes (and possibly for other structures described in 'results is organization of x' terms).
<img width="357" alt="image" src="https://user-images.githubusercontent.com/4782928/143879177-474fa118-a156-424a-9377-c055432275ac.png">

(Results in assembly of is also a child of 'developmentally related to', which is even more preblematic)
<img width="418" alt="image" src="https://user-images.githubusercontent.com/4782928/143878889-f85fc1a9-00c5-4162-9ca5-38c988964965.png">

'has anatomical participant' is defined as 'p has anatomical participant c iff p has participant c, and c is an anatomical entity'; does that cover 'celluar anatomical entities we have in GO? 

----

The proposal is to change the logical definition of terms as follows: 
*  'x protein-containing complex assembly'  -> change from  'results in assembly of' to  'has output' 
*  'x protein-containing complex disassembly'  -> change from  'results in disassembly of' to  'has input' 
* 'x protein-containing complex subunit organization' -> ? 
* ' x protein-containing complex remodeling' -> ? many children are lipoprotein particles

Thanks, Pascale

**Comment by cmungall** [comment]
agreed, this is a quick fix on RO

**Comment by cmungall** [comment]
fixed in latest RO https://github.com/oborel/obo-relations/releases/tag/v2021-12-07

refreshing import will fix

**Comment by balhoff** [comment]
RO import has been refreshed: #22535
