### ISSUE TITLE
NTR: [NLRP6 inflammasome complex]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22481]
Hi GO,

I would need two new terms related to NLRP6 inflammasome. These terms should be pretty easy to get, since similar terms exist for NLRP1 and NLRP3 inflammasomes

Thanks

Sylvain

1) NLRP6 inflammasome complex
An inflammasome complex that consists of NLRP6, PYCARD/ASC and caspase-1 or caspase-4/caspase-11.
child of  GO:0061702 inflammasome complex
PMID:30674671
PMID:34678144

2) NLRP6 inflammasome complex assembly
The aggregation, arrangement and bonding together of a set of components to form a NLRP6 inflammasome complex.
Child of: GO:0140632 inflammasome complex assembly
PMID:30674671
PMID:34678144

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140738
+name: NLRP6 inflammasome complex
+namespace: cellular_component
+def: "An inflammasome complex that consists of NLRP6, PYCARD/ASC and caspase-1 or caspase-4/caspase-11." [PMID:30674671, PMID:34678144]
+is_a: GO:0061702 ! inflammasome complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22481 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-30T06:12:14Z
+
+[Term]
+id: GO:0140739
+name: NLRP6 inflammasome complex assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a NLRP6 inflammasome complex." [PMID:30674671, PMID:34678144]
+is_a: GO:0140632 ! inflammasome complex assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22481 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-30T06:13:31Z

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

I created the 2 terms. For the assembly process, it would be interesting to have more information about the differences between the different inflamasome assembly  terms that we have, other than the substrate. 

Are they different assembly pathways? Or regulated by different signaling processes? Otherwise we might consider this the same process. 

Do you have any information on this? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi @pgaudet ,

good question. Mechanisms between the different inflammasomes I curated have similarities and differences. Please note that I'm not a specialist and that I curated maybe half of inflammasomes, not all.

The basic mechanism is the following the  pattern recognition receptor component of the complex (usually NLRP) is activated by some pathogen and it homooligomerizes, sometimes in a membraneless organelle and forms a filament, the inflammasome. It then activates some caspase (CASP1, CASP4 or CASP5), leading to inflammation.

The differences are the following: some NLRP  members (NLRP3, NLRP6 human NLRP1)  need PYCARD/ASC for the formation of the inflammasome, during the homooligomerization step and formation of the filament. Some NLRP (mouse NLRP1, CARD8) can form the inflammasome without PYCARD.

The caspases that are activated by the different inflammasome complexes may also differ. In many inflammasomes, it is CASP1that is activated, but CSP4 or CAPS5 can also be activated

Sylvain
