### ISSUE TITLE
NTR: [ADP-riboxanase activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22480]
Hi GO,

I would need a new term for an enzyme that mediates a new post-translational modification. Please note that the Rhea reaction is not yet public

Thanks

Sylvain

ADP-riboxanase activity
Catalysis of the reaction: L-arginyl-[protein] + NAD(+) = ADP-riboxanated L-argininyl-[protein] + H(+) + NH4(+) + nicotinamide
RHEA:69500
PMID:34671164;
child of  GO:0016829 lyase activity

**Comment by pgaudet** [comment]
from @sylvainpoux  - this corresponds to EC:4.3.99.-

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140740
+name: ADP-riboxanase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-arginyl-[protein] + NAD(+) = ADP-riboxanated L-argininyl-[protein] + H(+) + NH4(+) + nicotinamide." [PMID:34671164, RHEA:69500]
+comment: Note that this activity has two steps: a transfer of an ADP-robose group, followed by the elimitation of an ammonia group.
+xref: EC:4.3.99.-
+xref: RHEA:69500
+is_a: GO:0016772 ! transferase activity, transferring phosphorus-containing groups
+is_a: GO:0016841 ! ammonia-lyase activity
+is_a: GO:0140096 ! catalytic activity, acting on a protein
+relationship: part_of GO:0043687 ! post-translational protein modification
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22480 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-30T08:29:49Z
+

**Comment by pgaudet** [comment]
@sylvainpoux please note I have added 
part_of GO:0043687 ! post-translational protein modification

Let me know i this is not right

Thanks

**Comment by sylvainpoux** [comment]
Hi @pgaudet , yes, it is perfect. ADP-riboxanation in a PTM

Many thanks

Sylvain
