### ISSUE TITLE
Update Drosophila subset for MF and BP

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#22493]
Hi @pgaudet 

I want to update the goslim_drosophila subset for MF and BP terms quite substantially. (Leaving the CC as is).

Would it be easier if I just supplied the new slim terms as a list or supplied one showing the removals and additions?

**Comment by pgaudet** [comment]
All 3 would be useful ;) 
- additions and removal for doing the actual work in the ontology
- your final list to compare

So, send everything you can :)

**Comment by hattrill** [comment]
For MF:
<google-sheets-html-origin><style type="text/css"></style>

GO:0019899 | enzyme binding | REMOVE
-- | -- | --

<google-sheets-html-origin><style type="text/css"></style>

GO:0016740 | transferase activity | ADD
-- | -- | --
GO:0016787 | hydrolase activity | ADD
GO:0031386 | protein tag | ADD
GO:0038024 | cargo receptor activity | ADD
GO:0044183 | protein folding chaperone | ADD
GO:0140223 | general transcription initiation factor activity | ADD
GO:0140299 | small molecule sensor activity | ADD
GO:0140313 | molecular sequestering activity | ADD

**Comment by hattrill** [comment]
Final MF slim:
<google-sheets-html-origin><style type="text/css"></style>

ID New MF Slim | Name New MF slim
-- | --
GO:0016757 | transferase activity, transferring glycosyl groups
GO:0008168 | methyltransferase activity
GO:0019787 | ubiquitin-like protein transferase activity
GO:0016746 | transferase activity, transferring acyl groups
GO:0016765 | transferase activity, transferring alkyl or aryl (other than methyl) groups
GO:0016773 | phosphotransferase activity, alcohol group as acceptor
GO:0016301 | kinase activity
GO:0016779 | nucleotidyltransferase activity
GO:0008233 | peptidase activity
GO:0016810 | hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
GO:0052689 | carboxylic ester hydrolase activity
GO:0016298 | lipase activity
GO:0004518 | nuclease activity
GO:0016791 | phosphatase activity
GO:0003924 | GTPase activity
GO:0016798 | hydrolase activity, acting on glycosyl bonds
GO:0016491 | oxidoreductase activity
GO:0016874 | ligase activity
GO:0016853 | isomerase activity
GO:0016829 | lyase activity
GO:0030234 | enzyme regulator activity
GO:0005085 | guanyl-nucleotide exchange factor activity
GO:0038023 | signaling receptor activity
GO:0048018 | receptor ligand activity
GO:0022857 | transmembrane transporter activity
GO:0042302 | structural constituent of cuticle
GO:0003735 | structural constituent of ribosome
GO:0005200 | structural constituent of cytoskeleton
GO:0005201 | extracellular matrix structural constituent
GO:0008092 | cytoskeletal protein binding
GO:0008134 | transcription factor binding
GO:0042393 | histone binding
GO:0051082 | unfolded protein binding
GO:0060090 | molecular adaptor activity
GO:0003682 | chromatin binding
GO:0030246 | carbohydrate binding
GO:0008061 | chitin binding
GO:0008289 | lipid binding
GO:0046872 | metal ion binding
GO:0003723 | RNA binding
GO:0003677 | DNA binding
GO:0045182 | translation regulator activity
GO:0003700 | DNA-binding transcription factor activity
GO:0003712 | transcription coregulator activity
GO:0016740 | transferase activity
GO:0016787 | hydrolase activity
GO:0031386 | protein tag
GO:0038024 | cargo receptor activity
GO:0044183 | protein folding chaperone
GO:0140223 | general transcription initiation factor activity
GO:0140299 | small molecule sensor activity
GO:0140313 | molecular sequestering activity
GO:0140657 | ATP-dependent activity

**Comment by hattrill** [comment]
For BP:
<google-sheets-html-origin><style type="text/css"></style>

GO:0071806 | protein transmembrane transport | REMOVE
-- | -- | --
GO:0034613 | cellular protein localization | REMOVE
GO:0032543 | mitochondrial translation | REMOVE
GO:0030036 | actin cytoskeleton organization | REMOVE
GO:0019098 | reproductive behavior | REMOVE
GO:0009306 | protein secretion | REMOVE
GO:0006605 | protein targeting | REMOVE
GO:0006401 | RNA catabolic process | REMOVE
GO:0006325 | chromatin organization | REMOVE
GO:0006308 | DNA catabolic process | REMOVE
GO:0002181 | cytoplasmic translation | REMOVE
GO:0000226 | microtubule cytoskeleton organization | REMOVE

**Comment by hattrill** [comment]
Final BP slim:
<google-sheets-html-origin><style type="text/css"></style>

ID new BP slim | Name new BP slim
-- | --
GO:0006766 | vitamin metabolic process
GO:0006744 | ubiquinone biosynthetic process
GO:0030198 | extracellular matrix organization
GO:0003012 | muscle system process
GO:0042440 | pigment metabolic process
GO:0044703 | multi-organism reproductive process
GO:0006090 | pyruvate metabolic process
GO:0055085 | transmembrane transport
GO:0006575 | cellular modified amino acid metabolic process
GO:0006595 | polyamine metabolic process
GO:0099536 | synaptic signaling
GO:0006412 | translation
GO:0006396 | RNA processing
GO:0008104 | protein localization
GO:0072359 | circulatory system development
GO:0007010 | cytoskeleton organization
GO:0007018 | microtubule-based movement
GO:0034622 | cellular protein-containing complex assembly
GO:0007059 | chromosome segregation
GO:0007033 | vacuole organization
GO:0007031 | peroxisome organization
GO:0007163 | establishment or maintenance of cell polarity
GO:0032504 | multicellular organism reproduction
GO:0007568 | aging
GO:0007498 | mesoderm development
GO:0007423 | sensory organ development
GO:0007431 | salivary gland development
GO:0006066 | alcohol metabolic process
GO:0006914 | autophagy
GO:0005975 | carbohydrate metabolic process
GO:0007155 | cell adhesion
GO:0008219 | cell death
GO:0030154 | cell differentiation
GO:0051301 | cell division
GO:0016049 | cell growth
GO:0000902 | cell morphogenesis
GO:0048870 | cell motility
GO:0008283 | cell population proliferation
GO:0045454 | cell redox homeostasis
GO:0007166 | cell surface receptor signaling pathway
GO:0006520 | cellular amino acid metabolic process
GO:0048878 | chemical homeostasis
GO:0051276 | chromosome organization
GO:0044782 | cilium organization
GO:0007623 | circadian rhythm
GO:0050890 | cognition
GO:0042335 | cuticle development
GO:0030705 | cytoskeleton-dependent intracellular transport
GO:0006310 | DNA recombination
GO:0006281 | DNA repair
GO:0006260 | DNA replication
GO:0010256 | endomembrane system organization
GO:0060429 | epithelium development
GO:0007186 | G protein-coupled receptor signaling pathway
GO:0007369 | gastrulation
GO:0031047 | gene silencing by RNA
GO:0006091 | generation of precursor metabolites and energy
GO:0009100 | glycoprotein metabolic process
GO:0006955 | immune response
GO:0002520 | immune system development
GO:0035556 | intracellular signal transduction
GO:0006811 | ion transport
GO:0006629 | lipid metabolic process
GO:0006869 | lipid transport
GO:0007626 | locomotory behavior
GO:0051321 | meiotic cell cycle
GO:0061024 | membrane organization
GO:0010586 | miRNA metabolic process
GO:0006839 | mitochondrial transport
GO:0007005 | mitochondrion organization
GO:0000278 | mitotic cell cycle
GO:0042303 | molting cycle
GO:0016071 | mRNA metabolic process
GO:0061061 | muscle structure development
GO:0007399 | nervous system development
GO:0055086 | nucleobase-containing small molecule metabolic process
GO:0006913 | nucleocytoplasmic transport
GO:0006997 | nucleus organization
GO:0007389 | pattern specification process
GO:0034587 | piRNA metabolic process
GO:0030163 | protein catabolic process
GO:0006457 | protein folding
GO:0006497 | protein lipidation
GO:0051604 | protein maturation
GO:0070647 | protein modification by small protein conjugation or removal
GO:0006355 | regulation of transcription, DNA-templated
GO:0060541 | respiratory system development
GO:0042221 | response to chemical
GO:0009605 | response to external stimulus
GO:0006950 | response to stress
GO:0042254 | ribosome biogenesis
GO:0006403 | RNA localization
GO:0016072 | rRNA metabolic process
GO:0007600 | sensory perception
GO:0016074 | sno(s)RNA metabolic process
GO:0016073 | snRNA metabolic process
GO:0006790 | sulfur compound metabolic process
GO:0050808 | synapse organization
GO:0006351 | transcription, DNA-templated
GO:0006399 | tRNA metabolic process
GO:0016192 | vesicle-mediated transport

**Comment by hattrill** [comment]
Keep CC as is:
GO:0005730	nucleolus
GO:0005739	mitochondrion
GO:0005794	Golgi apparatus
GO:0005773	vacuole
GO:0005768	endosome
GO:0005783	endoplasmic reticulum
GO:0005777	peroxisome
GO:0005886	plasma membrane
GO:0005856	cytoskeleton
GO:0005829	cytosol
GO:0005634	nucleus
GO:0005615	extracellular space
GO:0005694	chromosome
GO:0030054	cell junction
GO:0030135	coated vesicle
GO:0030312	external encapsulating structure
GO:0031012	extracellular matrix
GO:0099503	secretory vesicle
GO:0045202	synapse
GO:0005929	cilium
