### ISSUE TITLE
add synonym GO:0004751    ribose-5-phosphate isomerase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22505]
pentose phosphate isomerase (PPI), add as exact synonym to GO:0004751
PMID:9872416

Note that some  (2) synonyms are present twice

Should the existing synonyms be exact rather than related?

**Comment by pgaudet** [comment]
Which synonym is present twice ? 
synonym: "5-phosphoribose isomerase activity" RELATED [EC:5.3.1.6]
synonym: "D-ribose 5-phosphate isomerase activity" RELATED [EC:5.3.1.6]
synonym: "D-ribose-5-phosphate aldose-ketose-isomerase activity" RELATED [EC:5.3.1.6]
synonym: "D-ribose-5-phosphate ketol-isomerase activity" RELATED [EC:5.3.1.6]
synonym: "phosphopentoseisomerase activity" RELATED [EC:5.3.1.6]
synonym: "phosphopentosisomerase activity" RELATED [EC:5.3.1.6]
synonym: "phosphoriboisomerase activity" RELATED [EC:5.3.1.6]
synonym: "ribose 5-phosphate epimerase activity" RELATED [EC:5.3.1.6]
synonym: "ribose phosphate isomerase activity" RELATED [EC:5.3.1.6]

**Comment by ValWood** [comment]
I misread them!
