### ISSUE TITLE
ribulose-phosphate 3-epimerase activity add synonym

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22506]
ribulose-phosphate 3-epimerase activity
Add exact? synonym
pentose phosphate epimerase (PPE)
PMID:9872416

**Comment by raymond91125** [comment]
There already is a synonym pentose-5-phosphate 3-epimerase activity. There are two pentose phospate epmerases PMID: 4560420 "On the mechanism of the pentose phosphate epimerases".

**Comment by pgaudet** [comment]
Hi @raymond91125 - what do you mean, can "pentose phosphate epimerase (PPE)" be added as a synonym anyway?
Also, are you  saying there are 2 activities? you are referring to 5.1.3.22   L-ribulose-5-phosphate 3-epimerase maybe? 

We should also change the term label of GO:0004750 to indicate it acts on the D- form, and to be consistent with GO:0034015 (L-ribulose-5-phosphate 3-epimerase activity). 

Thanks, Pascale

**Comment by raymond91125** [comment]
pgaudet 
Does the synonym 'pentose phosphate epimerase (PPE)' cove both the D and the L substrates? If that's the case, I would make it a BROAD synonym. 
raymond91125
In the context of PMID:9872416, I believe it's only the D- form.
ValWood
I don't know. This was a really old paper, and didn't mention different isomers of
ribulose-5-phosphate 3-epimerase.

Note, should these comments move to the ticket?
This is the pull request.
Peter might know, he is very knowledgeable about glucose metabolism in general
deustp01
Sorry, no clue here.
