### ISSUE TITLE
molecular function regulator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22528]
I have used "molecular function regulator" to describe the 
activity of a GTPase with the input of the gene product that it
regulates.

 However,  "molecular function regulator" is not allowed for direct annotation.
I can't think of any other term to use here. How have others annotated this?

thanks,

Val

**Comment by vanaukenk** [comment]
@ValWood 
Can you provide some examples? 
I've never been very happy with annotating GTPases just to 'GTPase activity' but I'm not sure if we're talking about the same thing.
Thx.

**Comment by ValWood** [comment]
Because the GTPase makes the GTPase *inactive* for signalling. The GTP-bound form is the *active form*. It doesn't make sense to attach the input to the GTPase activity?

This was the annotation I was looking at yesterday. It isn't in PomBAse because I forgot to reapprove the session, it will be back tomorrow.


<img width="729" alt="Screenshot 2021-12-08 at 09 24 25" src="https://user-images.githubusercontent.com/7359272/145183366-1fecfdb3-6feb-414a-b4b4-509478cf7761.png">

PMID:21035342

Actually for the GTPase in this case, I could use 'protein kinase activator'?, it was bit1 that I was struggling with. Bit1 is part of the TORC2 signalling complex and acts on Tor1 (Tor2 is called Tor1 in pombe), in some way to allow the ryh1 GTPAse to regulate it.

So  the example I was  stuck with wasn't actually a GTPase. 

(note that this was curated a while ago,I was just dealing with the logs which reports "molecular function regulator" as a "do not annotate" term).

**Comment by vanaukenk** [comment]
@ValWood 
Yes, this is a similar curation issue.
I've been working on a GO-CAM model of the EGFR/Ras/MAPK signaling pathway and the GTPase activity MF of let-60/Ras is unsatisfying.
http://noctua.geneontology.org/editor/graph/gomodel:56d1143000000176
My understanding is that for this pathway GTP-bound Ras binds and recruits Raf to the plasma membrane, so maybe that's what I should be trying to capture better with the MF.

**Comment by ValWood** [comment]
Yes! This comes up a lot. Most recently in this thread yesterday !
https://github.com/geneontology/go-ontology/issues/22482
scroll down to 
https://github.com/geneontology/go-ontology/issues/22482#issuecomment-987885825
and then continue.

I ma vying for a term which means 
"modification-dependent recruitment activity" (could have any label).
Personally I avoid curating "localization" because although this is true,  it's a 'given' from the 'recruitment' activity and the localization isn't really the  process.

If I could I would do
"modification-dependent recruitment activity" has input XXX
part of "XXXX signalling"  occurs at "location"

the 'localization process is a bit of a red herring detracting from the actual pathway.

I have used "chromatin adaptor" in this way here:
https://www.pombase.org/term/GO:0140463
If you can say where the recruitment happens, and during which process, the  explicit localization annotation is somewhat unnecessary (everything process has a localization component at some level).

**Comment by ValWood** [comment]
I think what I am trying to say is that the 'localization' isn't an 'active'  process like transport. Things move around until they are 'recruited'

**Comment by vanaukenk** [comment]
@ValWood 
So what I currently have in my GO-CAM model for this particular Ras MF is: protein-membrane adaptor activity.
GTP-bound LET-60 recruits LIN-45/Raf to the plasma membrane.  Part of LIN-45/Raf activation, based on mammalian studies, is binding to phosphatidylserine at the plasma membrane and this is facilitated by its interaction with LET-60/Ras.

**Comment by ValWood** [comment]
That sounds right actually. People talk about the TOR GTPasses 'activating' the kinase, but this could well be through recruitment.

**Comment by pgaudet** [comment]
@ValWood What0s the action here?
