### ISSUE TITLE
NTR: [dihydrouridine synthase activity]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22529]
Please provide as much information as you can: 

* **Suggested term label:**

NTR: dihydrouridine synthase activity

Should we also add mRNA dihydrouridine synthase activity?

* **Definition (free text)**

since def of  GO:0017150   tRNA dihydrouridine synthase activity
Catalysis of the reaction: tRNA-uracil + acceptor = tRNA-dihydrouridine + reduced acceptor.

I am assuming:
Catalysis of the reaction: RNA-uracil + acceptor = RNA-dihydrouridine + reduced acceptor.

* **Reference, in format PMID:#######**

PMID:34798057 | Transcription-wide mapping of dihydrouridine reveals that mRNA dihydrouridylation is required for meiotic chromosome segregation.

* **Gene product name and ID to be annotated to this term**

PomBase:dus3 (with substrates nda2 & nda3)

* **Parent term(s)**

Current parent of   GO:0017150   tRNA dihydrouridine synthase activity
is
GO:0016627   oxidoreductase activity, acting on the CH-CH group of donors
(I am not sure if this can be improved?)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

GO:0017150   tRNA dihydrouridine synthase activity
will move under the new proposed term

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

I do not know these.

* **Any other information**

Requested by the curating author:

I could not find a way to enter the annotation that dus3 also dihydrouridilate mRNAs  (at least on the nda2 and nda3 genes); which is one of the key point of the paper.
Thank you for your work within Pombase !
Carlo

**Comment by ValWood** [comment]
Look what Carlos did:
https://curation.pombase.org/pombe/curs/d86816507d979037#
Impressive huh? I love it when the community connect functions to processes.

**Comment by pgaudet** [comment]
Is there some RHEA or EC?

**Comment by hdrabkin** [comment]
This is a more general term that only specifies that it's an RNA that is modified; not sure if RHEA would make something where the 'substrate' is not THAT specific. However, I'll do a search in RHEA on the CHEBI term for a U residue and see what falls out.

**Comment by hdrabkin** [comment]
CHEBI:74443 5,6-dihydrouridine 5'-monophosphate(1−) residue as a substrate; however, all instances in RHEA use it as a residue in a tRNA. Paper is fairly new.
So dus3 can use either tRNA or mRNA as a substrate. 
I think making the new term mRNA specific might be a better idea here.

**Comment by ValWood** [comment]
> Do you perhaps want a term that 'mRNA dihydrouridine synthase activity' This would be a sib of the tRNA term.

yes I would prefer...
hence
>Should we also add mRNA dihydrouridine synthase activity?

v

**Comment by hdrabkin** [comment]
Yes Val; this tree would be consistent with others, such as pseudouridine synthase activity (with tRNA, snRNA, rRNA children)

**Comment by hdrabkin** [comment]
+id: GO:0106413
+name: dihydrouridine synthase activity
 children: GO:0106414 (NTR) and GO:0017150

+id: GO:0106414
+name: mRNA dihydrouridine synthase activity

**Comment by ValWood** [comment]
Thanks Harold!

**Comment by ValWood** [comment]
I asked Carlo if this was the first report of  mRNA dihydrouridinylation

"Pretty close but not the first. While our Mol Cell paper was in its final review stage, another paper came out that describe DUS3-dependent mRNA dihydrouridilation in human cells: Dai et al., Activity-based RNA-modifying enzyme probing reveals DUS3L-mediated dihydrouridylation. Nat Chem Biol (2021). "

A nice paper for UniProt to curate @Antonialock ?
and then for PAINTING (good triangulation) @marcfeuermann

**Comment by sylvainpoux** [comment]
Hi @ValWood , 

PMID:34798057 is a real gold mine. I curated DUS3 in UniProtKB/Swiss-Prot, both human and S.pombe entries.
 
I would have a bunch of questions comments
1) PMID:34798057 describes the RNA-dihydrouridine synthase activity for all 4 dus paralogs (dus1, dus2, dus3 and dus4) in S.pombe. Have you curated them in GO? I will curate the human orthologs.

2) I requested Rhea reactions for the mRNA dihydrouridine synthase activity, and dus3 (as well as dus1, dus2 and dus4) can work both with NADPH and NADH. 

We therefore created 2 reactions, that are not yet public

Rhea:69851 a 5,6-dihydrouridine in mRNA + NAD+ = a uridine in mRNA + H+ + NADH
Rhea:69855 a 5,6-dihydrouridine in mRNA + NADP+ = a uridine in mRNA + H+ + NADPH

We also created generic reactions for RNAs
Rhea:69843 a 5,6-dihydrouridine in RNA + NAD+ = a uridine in RNA + H+ + NADH
Rhea:69847 a 5,6-dihydrouridine in RNA + NADP+ = a uridine in RNA + H+ + NADPH

@hdrabkin Should I can create a ticket for new GO terms that covers the mRNA dihydrouridine synthase activity, or do you have everything in hand?

Thanks

Sylvain

**Comment by hdrabkin** [comment]
Hi @sylvainpoux ; this has been created last week
I +id: GO:0106414
+name: mRNA dihydrouridine synthase activity 

Note on the RHEA reactions. 
Although these might be useful for other uses of RHEA, we won't be able to use them to create logical defs because, as you can see for the tRNA diHu activities, they all use the same CHEBI id for the U residue, so that the logiclal defs using those will be the same.

**Comment by sylvainpoux** [comment]
Thanks @hdrabkin !

**Comment by ValWood** [comment]
Hi Sylvain, nice wasn't it!

This is what I have so far:
https://www.pombase.org/reference/PMID:34798057
mainly curated by the author.

I have not been able to use 
+id: GO:0106414
+name: mRNA dihydrouridine synthase activity
yet because of a problem with the GO pipeline the term is not yet available.

but I think the pombe GO will be covered from this paper.

**Comment by ValWood** [comment]
This GO term still isn't accessible?

**Comment by sylvainpoux** [comment]
Hi Val,
apparently not. I contacted Alex (@alexsign) and Pascale (@pgaudet) before the break. Apparently, there was a problem with some Xref that is causing a failure in the GO processing
Thanks
Sylvain

**Comment by hdrabkin** [comment]
I just confirmed that GO:0106414 is in fact in the editors file. It is also in the snapshot go-basic.obo; it is displaying in MGI's go browser.
It is also available in the go-basic.obo that I just downloaded from the GO web site (public).

**Comment by ValWood** [comment]
Thanks @hdrabkin 
I will check with @kimrutherford  if Canto is updating the ontologies at PomBase...
Val
