### ISSUE TITLE
Remove function-process links to 'modification' terms in the process ontology

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22527]
This would be helpful in the short term.
For example:

GO:0006508 proteolysis AnnotationPropagation P GO:0004298 threonine-type endopeptidase activity IBA
GO:0006468 protein phosphorylation AnnotationPropagation P GO:0004674 protein serine/threonine kinase activity IBA
GO:0035335 peptidyl-tyrosine dephosphorylation AnnotationPropagation P GO:0004725 protein tyrosine phosphatase activity IBA
GO:0006470 protein dephosphorylation AnnotationPropagation P GO:0004721 phosphoprotein phosphatase activity IBA
GO:0006508 proteolysis AnnotationPropagation P GO:0004222 metalloendopeptidase activity IBA
GO:0016311 dephosphorylation AnnotationPropagation P GO:0016791 phosphatase activity IBA

there are lots.
It is difficult to weedout these annotations, because for the ones with an experimental source on the MF, they look like annotations we have made.

**Comment by pgaudet** [comment]
As a first pass, removed: 

* GO:0016301 kinase activity part_of GO:0016310 ! phosphorylation
* * GO:0004672 protein kinase activity part_of GO:0006468 ! protein phosphorylation 
* * GO:0004407 histone deacetylase activity part_of GO:0016575 ! histone deacetylation
* * all children such as histone deacetylase activity (H3-K9 specific) part_of GO:0061647 ! histone H3-K9 modification | part_of GO:1990619 ! histone H3-K9 deacetylation 
* * GO:0033550 MAP kinase tyrosine phosphatase activity part_of GO:1990264 ! peptidyl-tyrosine dephosphorylation involved in inactivation of protein kinase activity
* * GO:0004550 nucleoside diphosphate kinase activity part_of GO:0006165 ! nucleoside diphosphate phosphorylation

* GO:0016791 phosphatase activity part_of GO:0016311 ! dephosphorylatio
* * GO:0004721 phosphoprotein phosphatase activity part_of GO:0006470 ! protein dephosphorylation
* * GO:0004725 protein tyrosine phosphatase activity part_of GO:0035335 ! peptidyl-tyrosine dephosphorylation
* * GO:0098627 protein arginine phosphatase activity part_of GO:0098628 ! peptidyl-N-phospho-arginine dephosphorylation


* GO:0008233 peptidase activity part_of GO:0006508 ! proteolysis 


* GO:0032451 demethylase activity part_of  GO:0070988 ! demethylation
* * GO:0032452 histone demethylase activity GO:0016577 ! histone demethylation
* * all children such as histone demethylase activity
* * GO:0035514  DNA demethylase activity part_of GO:0080111 ! DNA demethylation
* *  GO:0035515 oxidative RNA demethylase activity
* *   GO:0035516 oxidative DNA demethylase activity part_of GO:0035511 ! oxidative DNA demethylation


* GO:0033558 protein deacetylase activity part_of GO:0006476 ! protein deacetylation
* * GO:0042903 tubulin deacetylase activity part_of GO:0090042 ! tubulin deacetylation
* * histone deacetylase activity (H4-K16 specific) part_of GO:0070933 ! histone H4 deacetylation
* * all children such as histone demethylase activity (H3-R2 specific) part_of GO:0070078 ! histone H3-R2 demethylation

* GO:0035605 peptidyl-cysteine S-nitrosylase activity part_of GO:0018119 ! peptidyl-cysteine S-nitrosylation
* GO:0003755 peptidyl-prolyl cis-trans isomerase activity part_of GO:0000413 ! protein peptidyl-prolyl isomerization


* GO:0036524 protein deglycase activity  part_of GO:0036525 ! protein deglycation


* GO:0044603 protein adenylylhydrolase activity part_of GO:0018117 ! protein adenylylation
| part_of GO:0044602 ! protein deadenylylation 

* GO:1990404 protein ADP-ribosylase activity part_of GO:0006471 ! protein ADP-ribosylation


* GO:0016279 protein-lysine N-methyltransferase activity part_of GO:0018022 ! peptidyl-lysine methylation

GO:0008417 fucosyltransferase activity part_of GO:0036065 ! fucosylation

**Comment by ValWood** [comment]
Maybe this can close?

**Comment by ValWood** [comment]
There are still 14,000 EXP, but many are from MF connections
remove links between



(645) | ubiquitin-protein transferase activity
(375) | protein tyrosine kinase activity
(568) | ubiquitin protein ligase activity
(117) | histone acetyltransferase activity
(104) | SUMO transferase activity
(98) | ubiquitin conjugating enzyme activity
(92) | histone H3K4 methyltransferase activity

**Comment by pgaudet** [comment]
I think these are now done
