### ISSUE TITLE
NTR: [negative regulation of lncRNA transcription]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22534]
Ho GO,

I would need a bunch of terms to describe the specific repression of lncRNA transcription. Two different groups report this activity, which is conserved i human and Drosophila

Thanks

Sylvain

1) lncRNA transcription
The transcription of lncRNAs, non-coding RNAs over 200 nucleotides in length, from a DNA template. 
child of GO:0098781 ncRNA transcription

2) regulation of lncRNA transcription
Any process that modulates the frequency, rate or extent of the synthesis of a lncRNA.
Child of lncRNA transcription

3) negative regulation of lncRNA transcription
Any process that decreases the frequency, rate or extent of the synthesis of a lncRNA.
PMID:33913806
PMID:33767452
Child of regulation of lncRNA transcription

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140742
+name: lncRNA transcription
+namespace: biological_process
+def: "The transcription of lncRNAs, non-coding RNAs over 200 nucleotides in length, from a DNA template." [PMID:33767452, PMID:33913806]
+is_a: GO:0006351 ! transcription, DNA-templated
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22534 xsd:anyURI
+created_by: pg
+creation_date: 2021-12-09T08:40:49Z
+
+[Term]
+id: GO:0140743
+name: regulation of lncRNA transcription
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of the synthesis of a lncRNA." [PMID:33767452, PMID:33913806]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0140742 ! lncRNA transcription
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22534 xsd:anyURI
+created_by: pg
+creation_date: 2021-12-09T08:47:54Z
+
+[Term]
+id: GO:0140744
+name: negative regulation of lncRNA transcription
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of the synthesis of a lncRNA." [PMID:33767452, PMID:33913806]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0140742 ! lncRNA transcription
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22534 xsd:anyURI
+created_by: pg
+creation_date: 2021-12-09T08:49:57Z
