### ISSUE TITLE
property range violation for 'L-cysteine catabolic process to pyruvate, using cysteine dioxygenase' GO:0019451

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#22538]
[L-cysteine catabolic process to pyruvate, using cysteine dioxygenase](http://purl.obolibrary.org/obo/GO_0019451) has logical definition:

```
'catabolic process'
 and ('has participant' some 'cysteine dioxygenase activity')
 and ('has primary output' some pyruvate)
 and ('has primary input' some 'L-cysteine zwitterion')
```

However the range of [has participant](http://purl.obolibrary.org/obo/RO_0000057) is [continuant](http://purl.obolibrary.org/obo/BFO_0000002) while [cysteine dioxygenase activity](http://purl.obolibrary.org/obo/GO_0017172) is an [occurrent](http://purl.obolibrary.org/obo/BFO_0000003).

@pgaudet could we change this expression to `'has part' some 'cysteine dioxygenase activity'`? There are a few other terms with similar problems.

**Comment by ukemi** [comment]
It should be has_part. Probably my bad from a while ago.

**Comment by pgaudet** [comment]
I see 6 terms that have the pattern 'biological_process and 'has participant' some molecular_function' 

I'll change them to 'has part'. 


'L-cysteine catabolic process to pyruvate, using cysteine dioxygenase'
'L-cysteine catabolic process via cystine, using cystine reductase'
'L-cysteine catabolic process via cystine, using glutathione-cystine transhydrogenase'
'ligand-gated ion channel signaling pathway'
'ornithine catabolic process, by decarboxylation'
'serotonin-gated cation-selective signaling pathway'

Thanks, Pascale

**Comment by pgaudet** [comment]
Also added LD for sibling 

GO:0019456  L-cysteine catabolic process via cystine, using cysteine transaminase: 
'catabolic process'
 and ('has part' some 'L-cysteine transaminase activity')
 and ('has intermediate' some 'cystine zwitterion')
 and ('has primary input' some 'L-cysteine zwitterion')


and changed term label for   id: GO:0047801
-name: L-cysteine:2-oxoglutarate aminotransferase activity
+name: L-cysteine transaminase activity

to match EC and common usage.
