### ISSUE TITLE
Inconsistency transcription inputs/outputs and GO-CAM

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22555]
Hello, 

In GO-CAM we model transcription as 
- MF: DNA binding transcription factor activity 
and 
- BP: 'regulation of transcription by RNA polymerase II' 

both use **'has input'**  and the gene product. 

However this is inconsistent with the ontology, where the few terms that do have a logical definition use 'has output' - for eg 

ncRNA transcription: 
'transcription, DNA-templated'
 and ('has output' some ncRNA)

This is also pretty much consistent with the design pattern of biosynthetic process, because we should even use 'has primary output'. 

Should we change the LD of transcription terms to use 'has primary output'? and in this case, we need to change the GO-CAM models to also use 'has primary output'? 

@thomaspd @cmungall @vanaukenk @balhoff 

Thanks, Pascale

**Comment by ValWood** [comment]
tagging myself on this discussion @ValWood

**Comment by pgaudet** [comment]
Actually, @balhoff and @cmungall say that this is not an inconsistency, as the ontology and GO-CAMs are not describing the same entities.

**Comment by pgaudet** [comment]
*. **lncRNA transcription**
'transcription, DNA-templated'
and 'has primary output' some lncRNA

**Comment by pgaudet** [comment]
By organelle:

* **plastid transcription**
'transcription, DNA-templated'
 and 'has primary output' some transcript
 and 'occurs in' some plastid


* **plastid rRNA transcription**
'plastid transcription'
 and 'has primary output' some rRNA

* **mitochondrial transcription**
'transcription, DNA-templated'
 and 'has primary output' some transcript
 and 'occurs in' some mitochondrion

+ subclass: part of some mitochondrial gene expression

* **mitochondrial rRNA transcription**
* 'mitochondrial transcription'
 and 'has primary output' some rRNA

**Comment by ValWood** [comment]
>Actually, @balhoff and @cmungall say that this is not an inconsistency, as the ontology and GO-CAMs are not describing the same entities.

Can somebody explain these differences on a future call?
