### ISSUE TITLE
NTR: platelet rolling

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#22574]
Please provide as much information as you can: 

* **Suggested term label:**

platelet rolling

* **Definition (free text)**

Platelet rolling involves transient adhesive interactions between platelets and endothelial cells lining blood vessels. Carbohydrates on circulating platelets bind selectins or other molecules on the vessel wall causing the platelets to slow down and roll along the inner surface of the vessel wall. During this rolling motion, transitory bonds are formed and broken between surface molecules of platelets and endothelium.

* **Reference, in format PMID:#######**

PMID: 29018081

* **Gene product name and ID to be annotated to this term**

SELP (P-selectin)

* **Parent term(s)**

heterotypic cell-cell adhesion (GO:0034113) 

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

1. regulation of platelet rolling
2. positive regulation of platelet rolling
3. negative regulation of platelet rolling

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

Attribution should go to ORCID:0000-0002-8037-076X.

**Comment by pgaudet** [comment]
We should make sure that the definitions of this, and the sibling term GO:0050901 leukocyte tethering or rolling, are aligned. 

- We still do attributions to GOC initials - so this term should be attributed to GOC:sl in the definition xref. 
-  @slaulederkind do you have examples for the regulation of this process? P-selectin mediates the process, according to UniProt (https://www.uniprot.org/uniprot/P98106)

Thanks, Pascale

**Comment by raymond91125** [comment]
Have not created regulation terms.

**Comment by gthayman** [comment]
A positive regulation term would be appreciated, thanks.
