### ISSUE TITLE
ELK 0.5 incompatibility with GO terms & range restrictions on 'has participant'

### ISSUE THREAD

**Issue by shawntanzk** [geneontology/go-ontology#22587]
Noticed unsats in CL: 
![Screenshot 2021-12-16 at 13 46 53](https://user-images.githubusercontent.com/76212760/146383494-3358b7f7-4edb-48cc-9b26-336963583205.png)

explanations:
![Screenshot 2021-12-16 at 11 40 37](https://user-images.githubusercontent.com/76212760/146383605-82a99fe3-8b29-4ce5-8c60-6a93b822a4d1.png)

Temp fixed by removing range restrictions on 'has participant'

Related to #16524
Related to https://github.com/obophenotype/cell-ontology/pull/1377

I can't assign anyone so tagging @balhoff & @matentzn here

**Comment by balhoff** [comment]
@shawntanzk @matentzn the first one seems like a problem with CL. There's nothing wrong with GO's 'terminal bouton'. I think you should use 'has part' instead of 'has characteristic'.

**Comment by shawntanzk** [comment]
@balhoff oh yeah, sorry about that, brains really all over the place today >.< just the GO terms - ill edit it

**Comment by balhoff** [comment]
Actually the other was recently fixed by #22539; will be out in the next release.

**Comment by shawntanzk** [comment]
Thanks so much for that @balhoff!
