### ISSUE TITLE
histone methyltransferase terms with EC:2.1.1.354 xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22588]
EC:2.1.1.354 is currently an xref on these two terms:
- histone methyltransferase activity (GO:0042054)
- histone-lysine N-methyltransferase activity (GO:0018024)

These should both be removed because EC 2.1.1.354 is for a more specific reaction:
https://enzyme.expasy.org/EC/2.1.1.354
NAME: [Histone H3]-lysine(4) N-trimethyltransferase.
REACTION: 3 S-adenosyl-L-methionine + a [histone H3]-L-lysine(4) <=> 3 S-adenosyl-L-homocysteine + a [histone H3]-N(6),N(6),N(6)-trimethyl-L-lysine(4)
COMMENTS: This entry describes several enzymes that successively methylate the L-lysine(4) residue of histone H3 (H3K4), ultimately generating a trimethylated form.

On first glance, it looks like EC:2.1.1.354 could be moved to this child GO term:
id: GO:0042800
name: histone methyltransferase activity (H3-K4 specific)
def: "Catalysis of the reaction: S-adenosyl-L-methionine + histone H3 L-lysine (position 4) = S-adenosyl-L-homocysteine + histone H3 N6-methyl-L-lysine (position 4). This reaction is the addition of a methyl group onto lysine at position 4 of the histone H3 protein."
But I think that GO term is meant to be specifically for monomethyltation (in which case it's xref should be EC:2.1.1.364), or maybe it's a superclass for all types of H3-K4 methylation (in which case it should remain without an EC xref).

==
There may be a wider revision to be done here with more specific child terms (to match EC) being adding.  I'll copy the current GO terms and relevant EC numbers below for now, but we could transfer these to a new ticket if we want to go down that road....(somewhat similar to the revision of histone demethylases in #21089)

```
histone methyltransferase activity
|__histone-arginine N-methyltransferase activity
|   |__histone methyltransferase activity (H2A-R3 specific)
|   |__histone methyltransferase activity (H3-R2 specific)
|   |__histone methyltransferase activity (H3-R8 specific)
|   |__histone methyltransferase activity (H3-R17 specific)
|   |__histone methyltransferase activity (H4-R3 specific)
|__histone-glutamine methyltransferase activity
|__histone-lysine N-methyltransferase activity
    |__histone methyltransferase activity (H3-K4 specific)
    |__histone methyltransferase activity (H3-K9 specific)
    |__histone methyltransferase activity (H3-K27 specific)
    |__histone methyltransferase activity (H3-K36 specific)
    |__histone methyltransferase activity (H3-K37 specific)
    |__histone methyltransferase activity (H3-K79 specific)
    |__histone methyltransferase activity (H4-K20 specific)
```

EC:2.1.1.364    [Histone H3]-lysine(4) N-methyltransferase
EC:2.1.1.370    [Histone H3]-lysine(4) N-dimethyltransferase
EC:2.1.1.354    [Histone H3]-lysine(4) N-trimethyltransferase

EC:2.1.1.367    [Histone H3]-lysine(9) N-methyltransferase
EC:2.1.1.368    [Histone H3]-lysine(9) N-dimethyltransferase
EC:2.1.1.366    [Histone H3]-N(6),N(6)-dimethyl-lysine(9) N-methyltransferase
EC:2.1.1.355    [Histone H3]-lysine(9) N-trimethyltransferase

EC:2.1.1.369    [Histone H3]-lysine(27) N-methyltransferase
EC:2.1.1.371    [Histone H3]-lysine(27) N-dimethyltransferase
EC:2.1.1.356    [Histone H3]-lysine(27) N-trimethyltransferase

EC:2.1.1.357    [Histone H3]-lysine(36) N-dimethyltransferase
EC:2.1.1.359    [Histone H3]-lysine(36) N-trimethyltransferase

EC:2.1.1.360    [Histone H3]-lysine(79) N-trimethyltransferase

EC:2.1.1.361    [Histone H4]-lysine(20) N-methyltransferase
EC:2.1.1.362    [Histone H4]-N-methyl-L-lysine(20) N-methyltransferase
EC:2.1.1.372    [Histone H4]-lysine(20) N-trimethyltransferase

**Comment by pgaudet** [comment]
- [ ] EC:2.1.1.364 [Histone H3]-lysine(4) N-methyltransferase

- [ ] EC:2.1.1.370 [Histone H3]-lysine(4) N-dimethyltransferase
- [ ] EC:2.1.1.354 [Histone H3]-lysine(4) N-trimethyltransferase
- [ ] EC:2.1.1.367 [Histone H3]-lysine(9) N-methyltransferase
- [ ] EC:2.1.1.368 [Histone H3]-lysine(9) N-dimethyltransferase
- [ ] EC:2.1.1.366 [Histone H3]-N(6),N(6)-dimethyl-lysine(9) N-methyltransferase
- [ ] EC:2.1.1.355 [Histone H3]-lysine(9) N-trimethyltransferase
- [ ] EC:2.1.1.369 [Histone H3]-lysine(27) N-methyltransferase
- [ ] EC:2.1.1.371 [Histone H3]-lysine(27) N-dimethyltransferase
- [ ] EC:2.1.1.356 [Histone H3]-lysine(27) N-trimethyltransferase
- [ ] EC:2.1.1.357 [Histone H3]-lysine(36) N-dimethyltransferase
- [ ] EC:2.1.1.359 [Histone H3]-lysine(36) N-trimethyltransferase
- [ ] EC:2.1.1.360 [Histone H3]-lysine(79) N-trimethyltransferase

- [ ] EC:2.1.1.361 [Histone H4]-lysine(20) N-methyltransferase
- [ ] EC:2.1.1.362 [Histone H4]-N-methyl-L-lysine(20) N-methyltransferase
- [ ] EC:2.1.1.372 [Histone H4]-lysine(20) N-trimethyltransferase

**Comment by pgaudet** [comment]
I removed the bad cross-references. 

For the others: should we create the reactions? Or create the reactions that exist as we did for the deacetylases?  for example while https://enzyme.expasy.org/EC/2.1.1.371 describes the addition of a methyl group to the monomethyl form of H3K27, but the EC entry also states that the enzyme catalyzes both mono and di-methylation, which corresponds to EC:[2.1.1.369](https://enzyme.expasy.org/EC/2.1.1.369). 


Perhaps I could add the xrefs as narrowMatches what do you think?

**Comment by pgaudet** [comment]
Didn't mean to close.

**Comment by sjm41** [comment]
Thanks for removing the bad xrefs.

As to adding new GO terms for all the specific children....I'm not sure.  On the one hand, no-one is asking for them and I haven't researched which specific proteins could accurately get these specific annotations. On the other hand, it would make sense to make the organization of the methyltransferase branch of GO mirror the demethylase branch (and get the corresponding EC/Rhea IDs in as xrefs).

From another point of view, I see we already have terms for mono/di/trimethylation for many histone lysine methylation BP terms :

```
histone lysine methylation
|_histone H3-K4 methylation
|   |__histone H3-K4 monomethylation
|   |__histone H3-K4 dimethylation
|   |__histone H3-K4 trimethylation
|__histone H3-K9 methylation
|   |__histone H3-K9 dimethylation
|   |__histone H3-K9 trimethylation
|__histone H3-K27 methylation
|   |__histone H3-K27 trimethylation
|__histone H3-K36 methylation
|   |__histone H3-K36 dimethylation
|   |__histone H3-K36 trimethylation
|__histone H3-K37 methylation
|__histone H3-K79 methylation
|   |__histone H3-K79 dimethylation
|__histone H4-K20 methylation
    |__histone H4-K20 monomethylation
    |__histone H4-K20 dimethylation
    |__histone H4-K20 trimethylation
```

Is the plan to obsolete these BP terms since they represent MFs? If so, then I guess we will need the new MF terms so that annotations can still be made at the same level of granularity.

**Comment by pgaudet** [comment]
This may help? From https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC6130214/

![Uploading image.png…]()

**Comment by pgaudet** [comment]
Created grouping classes 

+[Term]
+id: GO:0140938
+name: histone H3 methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: S-adenosyl-L-methionine + histone H3  = S-adenosyl-L-homocysteine + histone H3me. Hist
one methylation generally occurs on either an arginine or a lysine residue." [PMID:28450737]
+synonym: "histone H4 methylase activity" EXACT []
+is_a: GO:0042054 ! histone methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T08:25:30Z
+
+[Term]
+id: GO:0140939
+name: histone H4 methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: Catalysis of the reaction: S-adenosyl-L-methionine + histone H4= S-adenosyl-L-homocyst
eine + histone H4me. Histone methylation generally occurs on either an arginine or a lysine residue." [PMID:28450737]
+synonym: "histone H4 methylase activity" EXACT []
+is_a: GO:0042054 ! histone methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T08:29:21Z

**Comment by pgaudet** [comment]
H3K4 methylases

+id: GO:0140945
+name: histone H3K4 monomethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction:   L-lysyl4-[histone H3] + S-adenosyl-L-methionine = H+ + N6-methyl-L-lysyl4-[histone H3] + S-adenosyl-L-homocysteine." [RHEA:60264]
+synonym: "histone H3K4 methylase activity" EXACT []
+xref: EC:2.1.1.364
+xref: RHEA:60344
+is_a: GO:0042800 ! histone H3K4 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T09:57:25Z
+
+[Term]
+id: GO:0140946
+name: histone H3K4 dimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl4-[histone H3] + 2 S-adenosyl-L-methionine = 2 H+ + N6,N6-dimethyl-L-lysyl4-[histone H3] + 2 S-adenosyl-L-homocysteine." [RHEA:64448]
+synonym: "histone H3K4 methylase activity" EXACT []
+xref: EC:2.1.1.370
+xref: RHEA:64448
+is_a: GO:0042800 ! histone H3K4 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T10:01:55Z

**Comment by pgaudet** [comment]
H3K9 

+[Term]
+id: GO:0140942
+name: histone H3K9 mono/dimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction:  L-lysyl9-[histone H3] + 2 S-adenosyl-L-methionine = 2 H+ + N6,N6-dimethyl-L-lysyl9-[histone H3] + 2 S-adenosyl-L-homocysteine. This reaction is the successive addition of two methyl groups to the unmethylated lysine residue at position 9 of histone H3, producing histone H3K9me2." [RHEA:64444]
+synonym: "histone H3K9 mono/dimethylase activity" EXACT []
+xref: EC:2.1.1.368
+xref: RHEA:64444
+is_a: GO:0046974 ! histone H3K9 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T09:35:23Z

+[Term]
+id: GO:0140947
+name: histone H3K9me2 methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: N6,N6-dimethyl-L-lysyl9-[histone H3] + S-adenosyl-L-methionine = H+ + N6,N6,N6-trimethyl-L-lysyl9-[histone H3] + S-adenosyl-L-homocysteine. This reaction is the addition of a single methyl group to the dimethylated lysine residue at position 9 of histone H3, producing histone H3K9me3." [RHEA:60280]
+synonym: "histone H3K9me2 methylase activity" EXACT []
+xref: EC:2.1.1.366
+xref: RHEA:60280
+is_a: GO:0046974 ! histone H3K9 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T10:17:34Z
+
+[Term]
+id: GO:0140948
+name: histone H3K9 monomethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl9-[histone H3] + S-adenosyl-L-methionine = H+ + N6-methyl-L-lysyl9-[histone H3] + S-adenosyl-L-homocysteine. This reaction is the addition of a methyl group to the unmethylated lysine residue at position 9 of histone H3, producing histone H3K9me." [RHEA:60288]
+synonym: "histone H3K9 monomethylase activity" EXACT []
+xref: EC:2.1.1.367
+xref: RHEA:60288
+is_a: GO:0046974 ! histone H3K9 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T10:21:35Z
+
+[Term]
+id: GO:0140949
+name: histone H3K9 mono/di/trimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl9-[histone H3] + 3 S-adenosyl-L-methionine = 3 H+ + N6,N6,N6-trimethyl-L-lysyl9-[histone H3] + 3 S-adenosyl-L-homocysteine. This reaction is the successive addition of three methyl groups to the unmethylated lysine residue at position 9 of histone H3, producing histone H3K9me3." [RHEA:60276]
+synonym: "histone H3K9 mono/dimethylase activity" EXACT []
+xref: EC:2.1.1.355
+xref: RHEA:60276
+is_a: GO:0046974 ! histone H3K9 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T10:49:29Z

**Comment by sjm41** [comment]
Thanks Pascale!
