### ISSUE TITLE
Changes to xrefs, def and synonym on 'glucose dehydrogenase activity' (GO:0004344)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22585]
id: GO:0004344
name: glucose dehydrogenase activity
def: "Catalysis of the reaction: D-glucose + acceptor = D-glucono-1,5-lactone + reduced acceptor." [PMID:22027299]
synonym: "D-glucose:(acceptor) 1-oxidoreductase" RELATED [EC:1.1.99.10]
synonym: "D-glucose:acceptor 1-oxidoreductase" RELATED [EC:1.1.5.2]
synonym: "glucose dehydrogenase (acceptor) activity" EXACT []
synonym: "glucose dehydrogenase (Aspergillus) activity" NARROW [EC:1.1.99.10]
synonym: "glucose dehydrogenase (decarboxylating)" RELATED [EC:1.1.99.10]
xref: EC:1.1.99.10
xref: KEGG_REACTION:R00305
xref: MetaCyc:GLUCOSE-DEHYDROGENASE-ACCEPTOR-RXN
xref: RHEA:24540

=> change EC xref to EC:1.1.5.9 (EC:1.1.99.10 has been transferred to EC:1.1.5.9) & similar changes in synonyms
=> change RHEA xref to RHEA:47372 (EC:1.1.5.9 corresponds to RHEA:47372)
=> in definition, change 'acceptor' to 'a quinone' and 'reduced acceptor' to 'a quinol' to match EC and RHEA descriptions (D-glucose + a quinone <=> D-glucono-1,5-lactone + a quinol)
=> remove "D-glucose:acceptor 1-oxidoreductase" RELATED [EC:1.1.5.2] synonym (EC:1.1.5.2 = GO:0008876)

**Comment by pgaudet** [comment]
Hi @sjm41 

Here's what I did

**GO:0004344 glucose dehydrogenase activity**

- [x] change EC to EC:1.1.99.35
- [x] change RHEA to RHEA:24540

GO:0004345 glucose-6-phosphate dehydrogenase activity
Keep EC:EC:1.1.5.2
- [x] Move KEGG_REACTION:R0030 and MetaCyc:GLUCOSE-DEHYDROGENASE-ACCEPTOR-RXN (were on GO:0004344) 

- [x] Created new term for  EC:1.1.5.9

+[Term]
+id: GO:0140762
+name: glucose dehydrogenase (FAD, quinone) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a quinone + D-glucose = a quinol + D-glucono-1,5-lactone." [RHEA:47372]
+xref: EC:1.1.5.9
+xref: RHEA:47372
+is_a: GO:0004344 ! glucose dehydrogenase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22585 xsd:anyURI
+created_by: pg
+creation_date: 2022-02-04T08:02:40Z


<img width="367" alt="image" src="https://user-images.githubusercontent.com/4782928/152494577-01c6e334-3f1b-45b7-a7af-19573b75bb50.png">



Let me know if this is OK 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet  - more complicated than I first thought - your changes look good.

Just two things to check:
1. "GO:0004345 glucose-6-phosphate dehydrogenase activity Keep EC:EC:1.1.5.2". Here, you meant "GO:0008876 quinoprotein glucose dehydrogenase activity", right?
2. Did you also remove the synonyms relating to EC:1.1.99.10 & EC:1.1.5.2 from GO:0004344 glucose dehydrogenase activity?

**Comment by pgaudet** [comment]
Hi @sjm41 
I think I did all that - I edited my comment above to add that information - I put this under tags 'EDITED' and '/EDIT' - I hope it's clear. 

Thanks for checking! 

Pascale
