### ISSUE TITLE
Rho protein signal transduction (GO:0007266)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22599]
Rho protein signal transduction (GO:0007266)

A series of molecular signals within the cell that are mediated by a member of the Rho family of proteins switching to a GTP-bound active state.

(and descendants)

this does not seem to be a useful term (could happy to almost any signalling pathway as mot include or terminal on a GTPase step?)

**Comment by pgaudet** [comment]
We should look at the entire branch from     GO:0007264  small GTPase mediated signal transduction 

There has been one proposal to reannotate to the more biological meaningful  terms (vesicle fusion, cytoskeletal organization, etc). There are > 700 EXP annotations so we'll see when we want to prioritize this.

**Comment by pgaudet** [comment]
Redundant with #20864
