### ISSUE TITLE
GO_0061900 using obsolete CL term in GO base

### ISSUE THREAD

**Issue by shawntanzk** [geneontology/go-ontology#22602]
GO_0061900 in go-base.owl is uses CL_0000243 which is obsolete and is triggering a failure in CL due to imports
see https://github.com/obophenotype/cell-ontology/issues/1378 & https://github.com/obophenotype/cell-ontology/pull/1388

**Comment by shawntanzk** [comment]
@balhoff tagging you here as per https://github.com/obophenotype/cell-ontology/pull/1388#issuecomment-998159464

**Comment by pgaudet** [comment]
weird, this term is not obsolete, and has net been recently updated.

**Comment by shawntanzk** [comment]
@pgaudet hmmm, strange, i've just checked the latest release (16-12-21) of CL and CL_0000243 is definitely obsolete there

**Comment by pgaudet** [comment]
sorry I thought you meant GO_0061900 was obsolete. I'll remove the reference to CL_0000243. Do you know if there is a replacement CL ?

**Comment by shawntanzk** [comment]
Thanks so much @pgaudet - it can be replaced by CL_0000125
