### ISSUE TITLE
BP sterol regulatory element binding protein cleavage (GO:0035103)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22606]
Please provide as much information as you can:

* **GO term ID and Label**

sterol regulatory element binding protein cleavage (GO:0035103)
The proteolytic release of a transcriptionally active sterol regulatory element binding protein (SREBP) from intracellular membranes, freeing it to move to the nucleus to upregulate transcription of target genes, in response to altered levels of one or more lipids. 

* **Reason for deprecation**

This term is   describing part of the "SREBP signaling pathway"
but it is really describing an activity (proteolysis)

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**

* **Are there annotations to this term?**
- How many EXP:
24, 23 of which are PomBase, 1 Flybase

1 mapping
InterPro | IPR038967 | DSC E3 ubiquitin ligase complex subunit 4-like

* **Any other information**
I am,  moving these up to parent ""SREBP signaling pathway"
but check that they all have the correct MF

**Comment by pgaudet** [comment]
@hattrill 

Are you OK with this obsoletion  proposal? 

Thanks, Pascale

**Comment by ValWood** [comment]
@hattrill  are you OK with this?

**Comment by hattrill** [comment]
Hi @ValWood - sorry, behind on checking stuff - yes, that's fine with me

**Comment by ValWood** [comment]
There are no annotations remaining to this term. I will proceed with obsoletion

**Comment by ValWood** [comment]
closing, duplicate
