### ISSUE TITLE
cytoskeleton terms, differences

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22601]
Is there a  necessary difference between

actin cytoskeleton organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of cytoskeletal structures comprising actin filaments and their associated protein

actin filament organization (GO:0007015)
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of cytoskeletal structures comprising actin filaments. 

If you organize the actin cytoskeleton, you organize actin filaments?

**Comment by ValWood** [comment]
similar question to 
GO:0031032    actomyosin structure organization
seems to be an unnecessary parent?

**Comment by Swhistler1** [comment]
I want to Learn. I'm new

**Comment by ValWood** [comment]
Closing for now. The  distinctions are probably useful. Need more info.
