### ISSUE TITLE
regulation of endosome size (GO:0051036)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22600]
Please provide as much information as you can:

* **GO term ID and Label**
regulation of endosome size (GO:0051036)

* **Reason for deprecation**

This seems like a phenotype, not a process. Endosome size changes in different mutants as steps in endosomal trafficking are blocked. Size of endosomes is not regulated per. se.

most likely just "endocytosis" or "regulation of endocytosis"

* **Are there annotations to this term?**
- How many EXP:
31

+ | − | (23) | UniProt
+ | − | (5) | FlyBase
+ | − | (2) | RGD
+ | − | (1) | SGD

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by ValWood** [comment]
@pgaudet Do you agree with this?

**Comment by ValWood** [comment]
@hattrill  before I. open an obsoletion ticket, what do you think about  your annotations to "regulation of endosome size (GO:0051036)"?
v

**Comment by ValWood** [comment]
will be dealt with by
https://github.com/geneontology/go-ontology/issues/24125

**Comment by hattrill** [comment]
> @hattrill before I. open an obsoletion ticket, what do you think about your annotations to "regulation of endosome size (GO:0051036)"? v

I am fine with obsoletion - looks like most can be annotated to a specific process and endo size is just a readout of disruption

**Comment by ValWood** [comment]
great-  move them  now if you can, but this term obsoletion is on hold because the branch "regulation of biological quality" is problematic.

**Comment by hattrill** [comment]
All annotations to GO:0051036 have been remved.
