### ISSUE TITLE
NTR: Quercetin 3-O-β-D-glucopyranoside hydrolase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#22613]
Please provide as much information as you can: 

* **Suggested term label:**
Quercetin 3-O-β-D-glucopyranoside hydrolase activity

* **Definition (free text)**
Catalysis of the reaction: quercetin  3-O-β-D-glucopyranoside + H2O = beta-D-glucose + quercetin.

* **Reference, in format PMID:#######**
PubMed=12594539

* **Gene product name and ID to be annotated to this term**
LCT Uniprot/P09848

* **Parent term(s)**
GO:0004553 hydrolase activity, hydrolyzing O-glycosyl compounds

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
RHEA:69655 (not yet public)

* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
On hold until we have a solution to import Rhea reactions as GO terms.

**Comment by pgaudet** [comment]
Will add the RHEA as NARROW synonym of GO:0008422 beta-glucosidase activity
