### ISSUE TITLE
NTR:  D-cellobiose glucosidase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#22615]
Please provide as much information as you can: 

* **Suggested term label:**
 D-cellobiose glucosidase activity

* **Definition (free text)**
Catalysis of the reaction: D-cellobiose + H2O = beta-D-glucose + D-glucose

* **Reference, in format PMID:#######**
PubMed=3929764
* **Gene product name and ID to be annotated to this term**
 LCT - UniProt/P09848

* **Parent term(s)**
GO:0008422 beta-glucosidase activity
* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
D-cellobiose hydrolase activity

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
RHEA:30679 (not public yet)
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
On hold until we have a solution to import Rhea reactions as GO terms.

**Comment by pgaudet** [comment]
Corresponds to GO:0080079 cellobiose glucosidase activity

**Comment by pgaudet** [comment]
Need to add RHEA and fix the definition (missing a product).

**Comment by pgaudet** [comment]
@lbreuza Maybe this should merge into b-glucosidas activity?
