### ISSUE TITLE
Fix label GO:1901583 | tetrapeptide transmembrane transport (was: Term merge: GO:0140206	dipeptide import across plasma membrane (or other way to impose consistency)) 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22619]
* **Term to be merged: Provide GO ID and term label**

GO:0140207    tripeptide import across plasma membrane
GO:0140206 | dipeptide import across plasma membrane

* **Which term do you propose this term merge into? Provide GO ID and term label**

GO:0098739   import across plasma membrane
(or a new term 'peptide import across plasmamembrane)

* **Reason for merge**

I am trying g to make annotations consistent and we do not have the  same specificity for 

GO:1901583 | tetrapeptide transmembrane transport
because an 'across plasma membrane term does not exist.

I want to capture where  the transport is import across the membrane 
I can capture the  "peptide specificity"

with  the function terms
GO:1901584 | tetrapeptide transmembrane transporter activity
(these exist for all)

**Comment by pgaudet** [comment]
Should we change GO:1901583 | tetrapeptide transmembrane transport to 'tetrapeptide import across plasma membrane'? There are 2 PomBase annotations. Would that resolve the issue? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think that would work too.
