### ISSUE TITLE
NTR: quercetin 4ʼ-O-β-D-glucopyranoside hydrolase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#22612]
Please provide as much information as you can: 

* **Suggested term label:**
Quercetin 4ʼ-O-β-D-glucopyranoside hydrolase activity

* **Definition (free text)**
Catalysis of the reaction: quercetin 4'-O-beta-D-glucoside + H2O = beta-D-glucose + quercetin.

* **Reference, in format PMID:#######**
PubMed=12594539

* **Gene product name and ID to be annotated to this term**
LCT Uniprot/P09848

* **Parent term(s)**
GO:0004553  hydrolase activity, hydrolyzing O-glycosyl compounds

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 

RHEA:69647

* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

RXN-13785

* **Any other information**

**Comment by pgaudet** [comment]
On hold until we have a solution to import Rhea reactions as GO terms.

**Comment by pgaudet** [comment]
Will add the RHEA as NARROW xref of GO:0008422 beta-glucosidase activity
