### ISSUE TITLE
NTR:phlorizin hydrolase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#22611]
Please provide as much information as you can: 

* **Suggested term label:**
Phlorizin hydrolase activity

* **Definition (free text)**
Catalysis of the reaction:  phlorizin + H2O = beta-D-glucose + phloretin. 

* **Reference, in format PMID:#######**
PubMed=9762914

* **Gene product name and ID to be annotated to this term**
LCT - UniProt/P09848
* **Parent term(s)**
GO:0004553 hydrolase activity, hydrolyzing O-glycosyl compounds

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.
RHEA:69639 (not yet public)

* **Any other information**

**Comment by pgaudet** [comment]
The reaction that corresponds to this already exists - if the EC in P09848 is correct - GO:0017042  glycosylceramidase activity

I will add 'phlorizin hydrolase activity' as a synonym.

OK ?

**Comment by pgaudet** [comment]
Actually the synonyms are already there - I wonder why you didn't find the term? Maybe P2GO only lists labels and not synonyms?

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 

How come EC:3.2.1.62 does not map to RHEA:69639 ?

**Comment by lbreuza** [comment]
I found that term, but phlorizin is not a Glycosyl-N-acylsphingosine.

**Comment by kaxelsen** [comment]
Exactly, phlorizin is a dihydrochalcone glucoside.

**Comment by pgaudet** [comment]
So EC should not have these terms as a synonyms? 
https://enzyme.expasy.org/EC/3.2.1.62

**Comment by kaxelsen** [comment]
You are right. This EC entry was created before it was settled the enzyme has two glycosyl hydrolase domains with each their activity. I'm going to submit the update very soon. The phlorizin hydrolase activity belongs to the EC 3.2.1.108 (lactase) domain.
