### ISSUE TITLE
parent term missing for  GO:0003228 atrial cardiac muscle tissue development

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#22614]
Hi

please add the parent term: GO:0048738 cardiac muscle tissue development
  > new child is_a GO:0003228 atrial cardiac muscle tissue development

Note this would follow the existing relationship for the equivalent ventricular term
GO:0048738 cardiac muscle tissue development
 > existing child is_a GO:0003229 ventricular cardiac muscle tissue development

Thanks

Ruth

**Comment by balhoff** [comment]
I think [atrial cardiac muscle tissue development](http://purl.obolibrary.org/obo/GO_0003228) should be changed to reference [cardiac muscle tissue of atrium](http://purl.obolibrary.org/obo/UBERON_0004490) instead of [myocardium of atrium](http://purl.obolibrary.org/obo/UBERON_0002302).
