### ISSUE TITLE
parent term missing for  GO:1905072 cardiac jelly development

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#22616]
Hi

this one needs to have a better parent GO:1905072 cardiac jelly development, I have provided more information below, but the simplest option would be the following:
GO:0007507 heart development
> add child term part_of GO:1905072 cardiac jelly development

Also improve the definition for cardiac jelly development to:
The process whose specific outcome is the progression of cardiac jelly over time, from its formation to the mature structure. The cardiac jelly is a specialized region that will give rise to the heart septa and valves. The cardiac jelly is an acellular gelatinous matrix secreted by the myocardium which separates it from the endocardium in early heart development.

And add the narrow synonym
cardiac extracellular matrix

I think it was not GO:1905072 cardiac jelly development originally included in heart development because cardiac jelly does not exist in the final heart. However, we have heart jogging as a child of  GO:0003143 embryonic heart tube morphogenesis and thus heart jogging has a part_of child relationship to GO:0007507 heart development (via other terms). 

GO:0003197 endocardial cushion development also has a part_of child relationship to  GO:0007507 heart development, but these cushions are not present in the final heart. 

Cardiac jelly is located in the region of the heart where the heart valves will form. After cardiac jelly develops cell migration leads to the development of the endocardial cushion from the cardiac jelly, and then the cushion goes on to form the valves.

see:
https://www.researchgate.net/figure/Atrioventricular-valve-development-across-species-A-Valve-development-begins-as_fig1_341514183 which states:
Atrioventricular valve development across species. (A) Valve development begins as cardiac jelly accumulates between the myocardial (red) and endocardial cell layers. (B) Endocardial cushions (ECs, in green) are created as endocardial cells invade the cardiac jelly following epithelial to mesenchymal transition (mouse, chick) or via a local invagination of the endocardium (zebrafish). 
And see:
https://www.sciencedirect.com/topics/medicine-and-dentistry/endocardial-cushion 
Immediately following looping of the primitive heart tube, regional expansion of the extracellular matrix (cardiac jelly) separating the outer myocardial lining and the inner endothelial lining of the heart occurs to initiate endocardial cushion morphogenesis by a process called epithelial–mesenchymal transition (EMT). 

https://zfin.org/action/ontology/term-detail/ZFA:0001318 
The extracellular matrix between the myocardium and the endocardium. The cardiac jelly plays a central role in the septation of the heart and comprises most of the thickness of the heart wall at early stages, but disappears as the heart differentiates. 

Thanks

Ruth

**Comment by raymond91125** [comment]
The part_of relation makes sense.

Cardiac jelly development is already logically defined as    'anatomical structure development'
 and ('results in development of' some 'cardiac jelly')

And cardiac jelly (Uberon) has the definition "Portion of extracellular matrix between the myocardium and the endocardium. The cardiac jelly plays a central role in the septation of the heart and comprises most of the thickness of the heart wall at early stages, but disappears as the heart differentiates."

Adding description of cardiac jelly in the definition of cardiac jelly development then may be unnecessary and redundant. @RLovering Thanks.

**Comment by raymond91125** [comment]
[narrow synonym cardiac extracellular matrix] seems rather broad to me. Wouldn't there be much of extracellular matrix that is not cardiac jelly?

**Comment by raymond91125** [comment]
@RLovering please let me know if you think it's necessary to add def or syn, or we can close this ticket. Thanks much!

**Comment by RLovering** [comment]
Hi Raymond

thanks for sorting this out. The current definition for this term is: The process whose specific outcome is the progression of cardiac jelly over time, from its formation to the mature structure. 

I hadn't appreciated that if a term is definied in Uberon then it doesn't have to be included in the GO definition. If this is the case then I guess no more info needs to be added to the definition. Although I think that the information I have provided is more informative than the Uberon definition. (ie the statement that: The cardiac jelly is an acellular gelatinous matrix secreted by the myocardium which separates it from the endocardium in early heart development.)

But if you are happy with the current definition then please do close this ticket

best

Ruth

**Comment by RLovering** [comment]
ps no more synonyms required

**Comment by raymond91125** [comment]
Thanks. @RLovering
