### ISSUE TITLE
Some GO terms have disappeared?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22610]
I'm getting an error in our logs:

"8664: GOID column=5 This ID "GO:0140278" is not in the OBO file.  Is the OBO file up-to-date? Is it the correct GOID?"

as far as I can see the term is still present, at least in QuickGO
https://www.ebi.ac.uk/QuickGO/term/GO:0140278
and I can't find any ticket about merge or obsoletion?

Is this ID still in GO, or is this a problem at our end?

Thanks
Val
CC @kimrutherford

**Comment by ValWood** [comment]
Same error for
GO:0106158    glycero-3-phosphocholine acyltransferase activity
GO:0140300    serine import into mitochondrion
GO:0140275    MIB complex
GO:0106155.   peptidyl-lysine 3-dioxygenase activity

**Comment by ValWood** [comment]
GO:0062111

GO:0106166 

GO:0110129
GO:0110134

GO:0140281
GO:0140268
GO:0140273
GO:0140299

All seem to **fairly** recent terms???

@suzialeksander  @kltm

**Comment by kimrutherford** [comment]
> I'm getting an error in our logs:

Which log file is that?  I can't see an error.

**Comment by ValWood** [comment]
Should I move this ticket to GO-site? It seems like a pipeline or update failure of some sort?

**Comment by ValWood** [comment]
Just reading Kim's com,ment so the problem may have disappeared. I will check. Although I still cannot find
this new term
https://github.com/geneontology/go-ontology/issues/22529#issuecomment-1004746331

**Comment by ValWood** [comment]
I think, but I am not sure, that it was in
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-03-21-30-47.gaf-load-output
but it isn't a problem now so I will close this ticket.
