### ISSUE TITLE
Missing parent: GO:0103025 alpha-amylase activity (releasing maltohexaose)]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22621]
* **GO term ID and label for which you request a new superclass**

+	GO:0103025 alpha-amylase activity (releasing maltohexaose)

* **New superclass (parent) suggested**

Add parent
	alpha-amylase activity

?

**Comment by pgaudet** [comment]
Do you need this term? It sounds like a specific product of alpha amylase, which as far as I can tell produces various sugars, I cannot find evidence for an enzyme that specifically releases maltohexaose. 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't need it.

I only want to fix the fact that these IEA are visible:
https://www.pombase.org/term/GO:0103025
If this  term merged into "alpha-amylase activity", the missing parent, that would solve the issue too.
