### ISSUE TITLE
Definition: RNA polymerase III general transcription initiation factor activity (GO:0000995)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22622]
Ontology term: RNA polymerase III general transcription initiation factor activity (GO:0000995)

Factors required for RNA polymerase III transcription initiation include TFIIIA, TFIIIB and TFIIIC
is repeated in this definition.

**Comment by krchristie** [comment]
Both of the first two sentences are duplicated:
- A general transcription initiation factor activity that contributes to transcription start site selection and transcription initiation of genes transcribed by RNA polymerase III
- Factors required for RNA polymerase III transcription initiation include TFIIIA, TFIIIB and TFIIIC
