### ISSUE TITLE
NTR: dopaminechrome tautomerase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22620]
* **Suggested term label:**
dopaminechrome tautomerase activity

* **Definition (free text)**
Catalysis of the conversion of dopaminechrome to 5,6-dihydroxyindole

* **Reference, in format PMID:#######**
PMID: 34388859

* **Gene product name and ID to be annotated to this term**
D. melanogaster yellow-h (Q9V4C0)
D. melanogaster yellow-f (Q9VG09)

* **Parent term(s)**
intramolecular oxidoreductase activity, transposing C=C bonds (GO:0016863)

(I think that's the correct parent, based on the similar existing term 'dopachrome isomerase activity' (GO:0004167). Also see fig 6d of PMID:34388859, attached here)
![Screenshot 2022-01-05 at 15 35 22](https://user-images.githubusercontent.com/16306861/148244802-b3c877c1-c31a-4f96-917e-95c7cae76a31.png)

* **Cross-references**
I can't see any exisiting EC or Rhea for this - should this be requested?

**Comment by hdrabkin** [comment]
Is this a single step rgiht? The figure is just showing two mechanisms,  right. 
So proper GO def would be 
Catalysis of the reaction: dopaminechrome = 5,6-dihydroxyindole.
I can request a RHEA also.

**Comment by sjm41** [comment]
Yes, single step. Your def looks good. Thanks for requesting RHEA!

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106416
+name: dopaminechrome tautomerase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: dopaminechrome = 5,6-dihydroxyindole." [PMID:34388859]
+is_a: GO:0016863 ! intramolecular oxidoreductase activity, transposing C=C bonds

RHEA requested

**Comment by hdrabkin** [comment]
mistake made; aborting and will restart after a meeting

**Comment by hdrabkin** [comment]
ok after second coffee
+[Term]
+id: GO:0106417
+name: dopaminechrome tautomerase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: dopaminechrome = 5,6-dihydroxyindole." [PMID:34388859]
+is_a: GO:0016863 ! intramolecular oxidoreductase activity, transposing C=C bonds

**Comment by hdrabkin** [comment]
RHEA will be added when available.

**Comment by hdrabkin** [comment]
New RHEA created
RHEA:70199
This id has been added to the GO:0106417 and will be visible when public at RHEA

An additional RHEA was created to cover the other reaction described in the paper.
RHEA:70203 N-methyldopaminechrome = 5,6-dihydroxyindole-N-methyl
