### ISSUE TITLE
Create disjoint axiom between GO:0008152 metabolic process and GO:0051179 localization

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22647]

**Comment by pgaudet** [comment]
One issue with 'receptor internalization' which 
is_a transport
and 
is_a receptor metabolic process

Removed 'receptor metabolic process'

**Comment by pgaudet** [comment]
All problems have to do with electron transport chain: 

unsatisfiable: http://purl.obolibrary.org/obo/GO_0019646
-> aerobic electron transport chain
part_of 'oxidative phosphorylation', is_a generation of precursor metabolites and energy

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905273
-> positive regulation of proton-transporting ATP synthase activity, rotational mechanism

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905272
-> negative regulation of proton-transporting ATP synthase activity, rotational mechanism

unsatisfiable: http://purl.obolibrary.org/obo/GO_0002082
-> regulation of oxidative phosphorylation

unsatisfiable: http://purl.obolibrary.org/obo/GO_0006119
-> oxidative phosphorylation

unsatisfiable: http://purl.obolibrary.org/obo/GO_0006120
-> 'mitochondrial electron transport, NADH to ubiquinone'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0006121
-> 'mitochondrial electron transport, succinate to ubiquinone'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0006122
-> 'mitochondrial electron transport, ubiquinol to cytochrome c'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0006123
-> 'mitochondrial electron transport, cytochrome c to oxygen' 

unsatisfiable: http://purl.obolibrary.org/obo/GO_0009777
-> 'photosynthetic phosphorylation'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0009778
-> 'cyclic photosynthetic phosphorylation'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0009779
-> 'noncyclic photosynthetic phosphorylation'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0015986
-> ATP synthesis coupled proton transport

unsatisfiable: http://purl.obolibrary.org/obo/GO_0030965
-> plasma membrane electron transport, NADH to quinone

unsatisfiable: http://purl.obolibrary.org/obo/GO_0042773
-> 'ATP synthesis coupled electron transport' 

unsatisfiable: http://purl.obolibrary.org/obo/GO_0042774
-> 'plasma membrane ATP synthesis coupled electron transport' 

unsatisfiable: http://purl.obolibrary.org/obo/GO_0042775
-> 'mitochondrial ATP synthesis coupled electron transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0042776
-> 'mitochondrial ATP synthesis coupled proton transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0042777
-> 'plasma membrane ATP synthesis coupled proton transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0046933
-> proton-transporting ATP synthase activity, rotational mechanism

unsatisfiable: http://purl.obolibrary.org/obo/GO_0061078
-> positive regulation of prostaglandin secretion involved in immune response

unsatisfiable: http://purl.obolibrary.org/obo/GO_0090323
-> 'prostaglandin secretion involved in immune response'

unsatisfiable: http://purl.obolibrary.org/obo/GO_0090324
-> negative regulation of oxidative phosphorylation'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1902956
-> 'regulation of mitochondrial electron transport, NADH to ubiquinone'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1902957
-> 'negative regulation of mitochondrial electron transport, NADH to ubiquinone'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1902958
-> 'positive regulation of mitochondrial electron transport, NADH to ubiquinone'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1903862
-> positive regulation of oxidative phosphorylation

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905446
-> 'regulation of mitochondrial ATP synthesis coupled electron transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905447
-> 'negative regulation of mitochondrial ATP synthesis coupled electron transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905448
-> 'positive regulation of mitochondrial ATP synthesis coupled electron transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905706
-> 'regulation of mitochondrial ATP synthesis coupled proton transport'

unsatisfiable: http://purl.obolibrary.org/obo/GO_1905707
-> 'negative regulation of mitochondrial ATP synthesis coupled proton transport'

**Comment by ValWood** [comment]
I  know the problem without looking,  I see it in the matrix and it really bugs me. 

It is because the electron transport  genes are annotated to this term
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004129

GO:0004129    cytochrome-c oxidase activity
which has dual parentage to transport and metabolism

I don't think it should be classed a  "transmembrane transporter/transmembrane transport (part of localization)"
We have talked about it before.

**Comment by ValWood** [comment]
It violates "transmembrane transport" anyway becasue it's transferring electrons, not transporting solutes. I think removing the transmembrane transport parent will fix this.

**Comment by pgaudet** [comment]
To address this I removed the parent 'energy coupled proton transport, down electrochemical gradient'  from 
GO:0015986  ATP synthesis coupled proton transport

+ changed label to 'proton motive force-driven ATP synthesis' 

( 'energy coupled proton transport, down electrochemical gradient'  and  'energy coupled proton transport, against electrochemical gradient' can probably be obsoleted; they have 3 EXP annotations in total)

**Comment by pgaudet** [comment]
Also, removed parent 'production of molecular mediator of immune response' from 'prostaglandin secretion involved in immune response'

**Comment by pgaudet** [comment]
If we agree to these (few) changes, then localization and metabolic process could be made disjoint.

**Comment by ValWood** [comment]
>If we agree to these (few) changes, then localization and metabolic process could be made disjoint.

I think the changes above would be correct. Bit are localization and metabolism *always*
disjoint? What about the situation where a metabolic pathway occurs partly in the cytoplasm and then substrates are transported into the mitochondrion for the pathway to continue. This transport activity would be part_of the pathway model wouldn't it?

**Comment by pgaudet** [comment]
Right, right now these transport reactions have never been represented as part of the synthesis pathway. We should look at an example. I know @marcfeuermann has come across this also

**Comment by marcfeuermann** [comment]
Hello, 
There are indeed more and more studies about compartmentalization of pathways with different steps occurring in different parts of the cell (see PMID:31209052). Transporters are indeed required and I would say that the transport reactions are indeed part of the pathway in these cases. So, metabolism and localization are not always disjoint. Up to now, most of studies have been done with the enzymes and their localization, and there is a lot less data about the transporters. However, it is a hot topic and this might change in the future.
I hope this will help.
Have a nice day.
Marc.

**Comment by pgaudet** [comment]
Discussion with @thomaspd @marcfeuermann 
We dont plan to make transport reactions/processes part of metabolic pathways in the ontology. 

Annotations of transporters being part of a biosynthetic pathway, for example, would not cause any violations.

**Comment by ValWood** [comment]
That makes sense.
