### ISSUE TITLE
NTR: [Maternal-to-zygotic transition]

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/go-ontology#22659]
Please provide as much information as you can: 

* **Suggested term label:**
Maternal-to-zygotic transition

* **Definition (free text)**
The regulation of gene expression process by which developmental control passes from the maternal genome to the zygotic genome. 

* **Reference, in format PMID:#######**
PMID: 32558204
* **Gene product name and ID to be annotated to this term**
Pabpn1l  MGI:2685954 
* **Parent term(s)**
Is_a  GO:0010468 regulation of gene expression

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
EXact: MZT, mid-blastula transition, MBT
* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ukemi** [comment]
Yes, they probably shouldn't be exact synonyms (my bad).

**Comment by raymond91125** [comment]
> Yes, they probably shouldn't be exact synonyms (my bad).
@ukemi Not synonym, related synonym, or some way to indicate synonym only in mice (I am not sure how)? Thanks.

**Comment by ukemi** [comment]
Related? My knowledge is about 40 years old, from when I worked on sea urchins. My understanding was that one of the key characteristics of the MBT was the activation of the zygotic genome. PMID: 7139712  I'm pretty sure this happens in urchins too.

**Comment by raymond91125** [comment]
It seems to me that to avoid confusion, we are probably better off to make MZT, MBT, and ZGA all distinct.
From PMID19204068:
"The stage at which maternal reliance ends and control of embryo development is transferred to the zygotic genome is referred to as the MZT. The MZT, under this definition, is distinct from the stage of zygotic genome activation (ZGA), which corresponds to the onset of de novo transcription from the zygotic genome. ZGA and MZT can coincide, but this is not always the case (Table1). The MZT is also distinct from the midblastula transition (MBT), a developmental transition in
amphibians and fishes associated with cell cycle lengthening, asynchronous cleavage, and the acquisition of cell motility, which, however, does not require zygotic tran scription (Newport and Kirschner1982a). The distinction is not always clear in the literature, and the MBT and ZGA are often referred to as marking the MZT, although this is clearly not true in all organisms. In this review, we adhere to a strict distinction as defined above."
