### ISSUE TITLE
NTR: muramoyltetrapeptide carboxypeptidase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#22670]
Please provide as much information as you can: 

* **Suggested term label:**
muramoyltetrapeptide carboxypeptidase activity

* **Definition (free text)**
Hydrolysis of the bond: N-acetyl-D-glucosaminyl-N-acetylmuramoyl-L-Ala-D-glutamyl-6-carboxy-L-lysyl┼D-alanine

* **Reference, in format PMID:#######**
PMID:10428950
* **Gene product name and ID to be annotated to this term**
LdcA, P76008
* **Parent term(s)**
GO:0004180

* **Cross-references**

EC 3.4.17.13

**Comment by pgaudet** [comment]
This was created in December. 
https://github.com/geneontology/go-ontology/issues/22390

**Comment by keseler** [comment]
Interesting!  However, it does not show up in the ontology - I did search GO before submitting the ticket...  Is there some problem with releasing new terms?

-Ingrid

**Comment by pgaudet** [comment]
Hi Ingrid, 

Indeed we had problems releasing the ontology between Dec 22nd and yesterday. This is now resolved. 

Thanks, Pascale
