### ISSUE TITLE
True path violation/incorrect parent GO:0046970    NAD-dependent histone deacetylase activity (H4-K16 specific)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22676]
GO:0046970    
NAD-dependent histone deacetylase activity (H4-K16 specific)

please remove parent
GO:0046969   NAD-dependent histone deacetylase activity (H3-K9 specific)

<img width="794" alt="Screenshot 2022-01-17 at 14 16 58" src="https://user-images.githubusercontent.com/7359272/149786403-c2bebe07-56dd-4b39-9e9e-0d5532bde625.png">

**Comment by pgaudet** [comment]
Changed parent to 'GO:0017136 ! NAD-dependent histone deacetylase activity' 

Thanks, Pascale
