### ISSUE TITLE
are these enzymes the same thing? PP-InsP5 kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22677]
Hi Harold,

are these enzymes the same thing?

GO:0102092 | 5-diphosphoinositol pentakisphosphate 3-kinase activity
Catalysis of the reaction: 5-diphospho-1D-myo-inositol pentakisphosphate + ATP = 3,5-bisdiphosphoinositol-1D-myo-inositol 2,3,4,6-tetrakisphosphate + ADP.

diphosphoinositol-pentakisphosphate kinase activity (GO:0033857)
Catalysis of the reaction: ATP + 1D-myo-inositol 5-diphosphate pentakisphosphate = ADP + 1D-myo-inositol bisdiphosphate tetrakisphosphate.

they *look* the same?

**Comment by deustp01** [comment]
Tracing a path from each GO term to GO-NUTS shows that both are associated with the same EC term,  [EC:2.7.4.24](https://enzyme.expasy.org/EC/2.7.4.24). A randomly chosen UniProt entry, [CFIO01_06897](https://www.uniprot.org/uniprot/A0A010RYA6) is electronically annotated with both GO terms and the UniProt page link in both cases points to the same RHEA reaction, [RHEA:37467](https://www.rhea-db.org/rhea/37467). Meanwhile, a search in RHEA for each of these two GO terms gets no hits.
Looking at the parentage of each term in quickGO, I see that GO:0102092 is_a phosphotransferase as is GO:0033857, but the latter term also is_a kinase.
For whatever it's worth, we have created two reactions that map to RHEA:37467, both with  inositol heptakisphosphate kinase activity (GO:0000829) as the associated molecular function.
For whatever else it's worth, GO:0102092 has 6,908 annotations but none have an experimental-evidence basis, and GO:0033857 has 12,241 annotations of which 9 (two in S. pombe) have an experimental-evidence basis.

**Comment by pgaudet** [comment]
Merged the terms and kept phosphotransferase parent, as the parent EC https://enzyme.expasy.org/EC/2.7.4.-
