### ISSUE TITLE
NTR: UDP-N-acetylmuramate—L-alanyl-γ-D-glutamyl-meso-2,6-diaminoheptanedioate ligase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#22673]
Please provide as much information as you can: 

* **Suggested term label:**
UDP-N-acetylmuramate—L-alanyl-γ-D-glutamyl-meso-2,6-diaminoheptanedioate ligase activity

* **Definition (free text)**
Catalysis of the reaction: ATP + UDP-N-acetyl-α-D-muramate + L-alanyl-γ-D-glutamyl-meso-2,6-diaminoheptanedioate = ADP + phosphate + UDP-N-acetylmuramoyl-L-alanyl-γ-D-glutamyl-meso-2,6-diaminoheptanedioate

* **Reference, in format PMID:#######**
PMID: 8808921
PMID: 17384195
* **Gene product name and ID to be annotated to this term**
Mpl, P37773
* **Parent term(s)**
GO:0016881

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
EC:6.3.2.45
RHEA:29563

* **Any other information**

**Comment by hdrabkin** [comment]
+id: GO:0106418
+name: UDP-N-acetylmuramate—L-alanyl-γ-D-glutamyl-meso-2,6-diaminoheptanedioate ligase activity

Also added related synonym of murein peptide ligase from the EC record
