### ISSUE TITLE
(potential) Term merge: [lipoate-protein ligase activity GO:0016979/  lipoyltransferase activity GO:0017118 ]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22689]
* **Term to be merged: Provide GO ID and term label**

lipoate-protein ligase activity GO:0016979
Catalysis of the lipoylation of a protein in two steps: ATP + (R)-lipoate + a [lipoyl-carrier protein]-L-lysine = a [lipoyl-carrier protein]-N6-(lipoyl)lysine + AMP + diphosphate (overall reaction): (1) ATP + (R)-lipoate = lipoyl-AMP + diphosphate; (2) lipoyl-AMP + a [lipoyl-carrier protein]-L-lysine = a [lipoyl-carrier protein]-N6-(lipoyl)lysine + AMP.

 lipoyltransferase activity GO:0017118 
Catalysis of the transfer of the lipoyl group from lipoyl-AMP to the lysine residue of lipoate-dependent enzyme. [PMID:10103005]

Are these the same thing?
@hdrabkin 
@deustp01

**Comment by ValWood** [comment]
corrected 2nd def to:


Definition | Parents
-- | --
Catalysis of the transfer of the lipoyl group from lipoyl-AMP to the lysine residue of lipoate-dependent enzyme. [PMID:10103005]

**Comment by pgaudet** [comment]
These are different - different RHEAs : RHEA:20473 and RHEA:49288
The definition of GO:0017118 could be edited to be ore like RHEA's
