### ISSUE TITLE
Merge     GO:0050250  retinal oxidase activity  into GO:0004031 aldehyde oxidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22680]
Hello, 
EC has merged  EC:1.2.3.11  retinal oxidase activity (GO:0050250) into EC:1.2.3.1  aldehyde oxidase activity (GO:0004031)

There is a single EXP annotation from PMID:10190983 to mouse Aox1. That paper actually states that it is the same enzyme that catalyzes both reactions "In this study, we provide direct evidence that retinal oxidase is identical to aldehyde oxidase (EC 1.2.3.1) by cDNA cloning. Retinal oxidase and aldehyde oxidase, purified from rabbit liver cytosol using the original methods, showed completely identical HPLC patterns and amino acid sequences for three corresponding polypeptides (103 amino residues)."

So I will merge both terms. 
RHEA:22520 (xref to GO:0050250 retinal oxidase activity) would become narrowMatch to GO:0004031 aldehyde oxidase activity. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Likewise 

* GO:0102797  geranial:oxygen oxidoreductase activity 
*  GO:0102798  heptaldehyde:oxygen oxidoreductase activity
are mapped to EC:1.2.3.1

All annotations are IEAs, which is too specific, so I will obsolete these with REPLACE BY GO:0004031 aldehyde oxidase activity. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0102797 geranial:oxygen oxidoreductase activity
GO:0102798 heptaldehyde:oxygen oxidoreductase activity

The reason for obsoletion is that this represent specific substrates of GO:0004031 aldehyde oxidase activity, so they are beyond the scope of GO. 

There are no EXP annotations or mappings  to these terms; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22680

Thanks, Pascale

**Comment by alanbridge** [comment]
Hi Pascale,

the IUBMB sometimes merge EC numbers because the activities belong to the same enzyme. 
Does that necessarily mean you should merge the mapped GO terms too? 
@kaxelsen

**Comment by thomaspd** [comment]
Our current guidelines are to aim to have GO terms at the level of enzyme specificity when known, and then annotations can be made more specific using the has-input extension (or relation in GO-CAM). So I think we could go forward with this proposal, and suggest that the one experimental annotation be modified to include (has-input retinal) in the extension field.
