### ISSUE TITLE
Add Travis check on xeferences

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22697]
Hi @balhoff 

We need a check that makes sure that all cross references are of the form: 
* alphabetic character-colon-alphanumerical character (right?) 
* no spaces allowed

Thanks, Pascale

**Comment by balhoff** [comment]
I added some syntax checks in #22701. I put in some special cases for EC and Rhea so we could be more strict. We can add others if they have their own rules.

**Comment by pgaudet** [comment]
Thanks @balhoff !
