### ISSUE TITLE
Missing parent: [GO:0102555 | octanoyl transferase activity (acting on glycine-cleavage complex H protein)]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22690]
* **GO term ID and label for which you request a new superclass**

GO:0102555 | octanoyl transferase activity (acting on glycine-cleavage complex H protein)

Catalysis of the reaction: [glycine cleavage system lipoyl-carrier protein]-L-lysine + octanoyl-ACP = H+ + a [glycine-cleavage complex H protein] N6-octanoyl-L-lysine + a holo-[acyl-carrier protein].

seems that is should be is_a

GO:0033819    lipoyl(octanoyl) transferase activity
Catalysis of the reaction: octanoyl-[acyl-carrier protein] + protein = protein N6-(octanoyl)lysine + acyl-carrier protein.

and 
GO:0033819    lipoyl(octanoyl) transferase activity
that it should be is_a
GO:0016415 octanoyltransferase activity
Catalysis of the transfer of an octanoyl (CH3-[CH2]6-CO-) group to an acceptor molecule.

(maybe the gene product/cleavage complex specific version should not exist?)

**Comment by pgaudet** [comment]
Based on the xrefs, these two terms should merge, GO:0033819  links to EC:2.3.1.181 but has no RHEA, and the RHEA for GO:0102555 links to EC:2.3.1.181

octanoyl transferase activity (acting on glycine-cleavage complex H protein) specifies a substrate, which we avoid doing in GO.
