### ISSUE TITLE
NTR: hyaluronic acid secretion

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#22715]
Please provide as much information as you can: 

* **Suggested term label:**
hyaluronic acid secretion

* **Definition (free text)**
The release of hyaluronic acid from a cell.

* **Reference, in format PMID:#######**
PMID: 3671989

* **Gene product name and ID to be annotated to this term**
would CHEBI:16336 'hyaluronic acid' be appropriate?

* **Parent term(s)**
GO:0046903 secretion

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
n/a

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
hyaluronan secretion
https://en.wikipedia.org/wiki/Hyaluronic_acid

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Related to https://github.com/obophenotype/cell-ontology/pull/1427

**Comment by pgaudet** [comment]
Hi @bvarner-ebi 

Could you use GO:0030213 hyaluronan biosynthetic process for this paper? 

Thanks, Pascale

**Comment by bvarner-ebi** [comment]
Hi @pgaudet, thank you for the suggestion.

Based on the text definition, GO:0030213 does not necessarily include the scope that the product is released from the cell. Since type B (fibroblast-like) synoviocytes synthesise and release the product into the surrounding matrix / synovial fluid, I think secretion should be part of the concept. Does that make sense?

**Comment by bvarner-ebi** [comment]
@pgaudet, actually, I may be able to use GO:0030213 hyaluronan biosynthetic process + secretes UBERON:0001090 synovial fluid. I will investigate and reconfirm if that is appropriate. Thanks again for the suggestion.

**Comment by pgaudet** [comment]
OK thanks, Please reopen if this needs more discussion.
