### ISSUE TITLE
NTR : [RNA alternative polyadenylation]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22718]
_Please provide as much information as you can:_ 

* **Suggested term label:**
RNA alternative polyadenylation

parent of 
GO:0110104   mRNA alternative polyadenylation

**Comment by pgaudet** [comment]
Reference? 

Would GO:0110104 mRNA alternative polyadenylation have other siblings?

**Comment by ValWood** [comment]
Out of date.
