### ISSUE TITLE
Change relation for transporters

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22721]
Hello, 

In yesterday's ontology call, it was decided to use 'has primary input' for transporters, rather than 'transports or maintains localization of'. 

@vanaukenk @ukemi We need to discuss the plan to retrofit existing annotations 

Thanks, Pascale

**Comment by vanaukenk** [comment]
Steps needed to move forward with this:

Ontology

- [ ] Update logical definitions in the ontology that use 'transports or maintains localization of'
- [ ] Review and update logical definitions in the ontology that use 'imports' and 'exports'
- [ ] Add property chains for 'has primary input' and 'has primary output' that mirror existing chain for 'has input'?

Annotations and Curation Tools

Protein2GO

- [ ] Remove 'transports or maintains localization of', 'imports', 'exports' from gorel.obo
- [ ] Remove 'transports of maintains localization of' from Protein2GO AE list
- [ ] Add 'has primary input' and 'has primary output' to gorel.obo
- [ ] Add 'has primary input' and 'has primary output' to Protein2GO AE list
- [ ] Update existing annotations in Protein2GO

Noctua

- [ ] Reactome  - change conversion rule and re-import?
- [ ] MOD imports - add new rule to convert 'transports or maintains localization of' , 'imports', 'exports' to 'has primary input' or 'has primary output' during import
- [ ] Other imports, e.g. SynGO - change source or change existing data store?
- [ ] Update AE relations in Noctua form to include 'has primary input' and 'has primary output'
- [ ] Move 'transports or maintains localization of' out of the upper list on the Noctua graph and add 'has primary input' and 'has primary output' to the upper list
- [ ] Update existing annotations with new relation

Documentation and Curation

- [ ] Update GOC wiki documentation on relations
- [ ] Announce on an annotation call

**Comment by ukemi** [comment]
Note that we have also used this relation in 'localization' annotations. I propose we switch to 'has primary input' for those too and just make the change across the board.

**Comment by pgaudet** [comment]
'has primary input' and 'has primary output' were already in gorel.obo under 'go annotation extension relation' and in various subsets (valid_for_go_extension, display_for_curators) 

@alexsign do you know why this is not showing up in P2GO ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/compare/relations_fixes_20220325?expand=1

**Comment by alexsign** [comment]
@pgaudet Gene Ontology was not updated in P2GO for a while. I used to have the issue with secondary IDs. Now it's failing with our own safety check: "Dangerously many cross_products (1869) will be deleted. 450 are considered safe." I'm still looking for what is missing in latest GO files.

**Comment by pgaudet** [comment]
Done
