### ISSUE TITLE
GO:0090693 plant organ senescence  - change  parent from  'GO:0007568 aging' to GO:0032502 developmental process 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22725]
'part of' some 'plant organ development'

@tberardini Could we make it is_a  GO:0032502 developmental process rather than is_a  'GO:0007568 aging'? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Propose new definition: 
GO:0090693 plant organ senescence: "A plant organ development process during which the plant dismantles  cellular components to reclaims the valuable cellular building blocks that have been deposited in the leaves and other parts of the plant during growth."

**Comment by pgaudet** [comment]
Similarly for GO:0010150 leaf senescence
current def: "The process that occurs in a leaf near the end of its active life that is associated with the dismantling of cell components and membranes, loss of functional chloroplasts, and an overall decline in metabolism."

Proposed def: "A leaf development process during which the plant dismantles the cellular components of leaves to reclaims the valuable cellular building blocks."

Ref: PMID:17177638

**Comment by pgaudet** [comment]
And for GO:0080187   floral organ senescence
Proposed def: 
The last stage of flower development during which programmed degradation of macromolecules and nutrient recycling take place.

PMID:19380421

**Comment by tberardini** [comment]
> @tberardini Could we make it is_a GO:0032502 developmental process rather than is_a 'GO:0007568 aging'?

Why?

**Comment by pgaudet** [comment]
Because 'aging' is defined as a deterioration over time, and plant senescence is described as a developmental process in the literature (see the papers we propose to add as definition xrefs).

In plants, senescence of leaves and flowers serves to recycle an reuse building blocks, so it's not a general decline of the plant (on the contrary).

Also, plant organs undergo senescence during the entire life of the plant, and often multiple times (eg every year for (some) leaves) over the life of the organism, which is not consistent with 'aging' either. 

Does that answer your question? 

Thanks, Pascale

**Comment by tberardini** [comment]
Yes, that makes sense. Thank you for providing the context without which I couldn't understand the request fully.
