### ISSUE TITLE
Obsoletion notice:     GO:0007576 nucleolar fragmentation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22728]
Dear all, 

The proposal has been made to obsolete GO:0007576 nucleolar fragmentation. The reason for obsoletion is that this represents a readout; the one EXP annotation from PMID:10075651 shown nucleolar fragmentation when overexpressing a specific transcription factor, is inconsistent with the definition "The cell aging process that results in the nucleolus breaking down into fragments" 

There are no mappings; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22728

Thanks, Pascale

**Comment by pgaudet** [comment]
@gthayman the Rat annotation can be replaced by GO:0007000 nucleolus organization 

Thanks, Pascale

**Comment by pgaudet** [comment]
@gthayman @slaulederkind Did you have a chance to look at this ?

**Comment by gthayman** [comment]
RGD done.
