### ISSUE TITLE
NTR: [endoplasmic reticulum membrane biogenesis]

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#22720]
Please provide as much information as you can: 

* **Suggested term label:**

endoplasmic reticulum membrane biogenesis

* **Definition (free text)**

The process in which an endoplasmic reticulum membrane is synthesized, aggregates, and bonds together.

* **Reference, in format PMID:#######**

https://pubmed.ncbi.nlm.nih.gov/34617598/
https://pubmed.ncbi.nlm.nih.gov/24373967/
https://pubmed.ncbi.nlm.nih.gov/19825355/

* **Gene product name and ID to be annotated to this term**

ICE2, SGD:S000001352, P40499

* **Parent term(s)**

GO:0044091 membrane biogenesis

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

none

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

ER membrane biogenesis

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by robnash** [comment]
anyone able to add this one for me?

**Comment by suzialeksander** [comment]
@pgaudet

**Comment by suzialeksander** [comment]
@pgaudet

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160031
+name: endoplasmic reticulum membrane biogenesis
+namespace: biological_process
+def: "The process in which an endoplasmic reticulum membrane is synthesized, aggregates, and bonds together." [PMID:19825355, PMID:24373967, PMID:34617598]
+synonym: "ER membrane biogenesis" EXACT []
+is_a: GO:0044085 ! cellular component biogenesis
+intersection_of: GO:0044085 ! cellular component biogenesis
+intersection_of: has_output GO:0005789 ! endoplasmic reticulum membrane
+relationship: part_of GO:0090158 ! endoplasmic reticulum membrane organization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22720 xsd:anyURI
+created_by: rynl
+creation_date: 2022-06-06T22:31:36Z
