### ISSUE TITLE
Obsoletion notice: GO:0010260  animal organ senescence

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22732]
Dear all, 

The proposal has been made to obsolete 'GO:0010260  animal organ senescence'. The reason for obsoletion is that this term represents a phenotype. 
Unlike plant organ senescence, which takes place to allow plants to reuse cellular components and nutrients from shed leaves and flowers (see #22725), we cannot find 'normal'  conditions of animal organ senescence. 

There are 5 EXP annotations: 
2 SGN 
1 MGI @hdrabkin 
2 RGD @gthayman 

These look like phenotypes, we are not able to suggest a normal process to which they can be reannoated. There are no mappings; these terms are not present in any subsets. 

You can comment on the ticket: 

Thanks, Pascale

**Comment by hdrabkin** [comment]
MGI removed

**Comment by slaulederkind** [comment]
RGD annotations have been deleted.

**Comment by mlkaldunski** [comment]
Would you consider adding "ovarian senescence" to the definition of menopause, or to reproductive senescence? This was one example where having "animal organ senescence" as a child of "aging" made sense to me. 
Mary

**Comment by pgaudet** [comment]
hi @mlkaldunski, 

Thanks for the feedback, I've added this as a synonym of GO:1990636 reproductive senescence. 

Thanks, Pascale
