### ISSUE TITLE
Move  GO:0009835  fruit ripening under GO:0021700 developmental maturation? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22731]
Hi @tberardini 

GO:0009835  fruit ripening is currently a child of GO:0007568 aging

@ValWood and I propose to move it under GO:0021700 developmental maturation, "A developmental process, independent of morphogenetic (shape) change, that is required for an anatomical structure, cell or cellular component to attain its fully functional state."; what do you think? 

Also, the definition could be improved from "An aging process that has as participant a fruit. Ripening causes changes in one or more characteristics of a fruit (color, aroma, flavor, texture, hardness, cell wall structure) and may make it more attractive to animals and aid in seed dispersal." 

To "A developmental maturation process that causes a fruit to become more edible. Ripening causes changes in one or more characteristics of a fruit (color, aroma, flavor, texture, hardness, cell wall structure), coincides with seed maturation and may make it more attractive to animals and aid in seed dispersal."

PMID:35016620
PMID:32983216
PMID:32983216

Thanks, Pascale

**Comment by tberardini** [comment]
Yes, the change in parentage sounds good. For the def, I would leave out the 'causes a fruit to become more edible' part. Can you still use the 'has as participant a fruit' part? 

New:   "A developmental maturation process that has as participant a fruit. Ripening causes changes in one or more characteristics of a fruit (color, aroma, flavor, texture, hardness, cell wall structure), coincides with seed maturation and may make it more attractive to animals and aid in seed dispersal."

**Comment by pgaudet** [comment]
OK, we can do that. 

Thanks !

**Comment by pgaudet** [comment]
+ add logical definition: 

'anatomical structure maturation'
and 'results in maturation of' some fruit
