### ISSUE TITLE
GO:1990636 reproductive senescence : move under 'biological phase' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22733]
GO:1990636 reproductive senescence is defined as "A natural reduction in reproductive capacity with aging, often taking the form of a switch from regular reproductive cycles to irregular and infrequent ones. Source: PMID:24914937, PMID:25523082"

- [x] This seems to represent a 'phase', so @ValWood and I propose to move it under GO:0044848 biological phase. 

This process covers senescence of both male and female reproductive systems, in animals, including rat, fly and C. elegans. 

Other changes proposed: 

- [x] make 'menopause' a child of GO:1990636 reproductive senescence
- [x] change def to 'A life cycle stage during which the reproductive capacity and fitness of an organism declines.'  
- [ ] Review existing annotations: https://docs.google.com/spreadsheets/d/1nVu1uHT2_og_wahuInUiCiZWRCldxLqoEvkB4Th4Emg/edit#gid=0

**Comment by pgaudet** [comment]
* There are 3 annotations by RGD, MGI and UniProt (to a worm gene), see https://docs.google.com/spreadsheets/d/1nVu1uHT2_og_wahuInUiCiZWRCldxLqoEvkB4Th4Emg/edit#gid=0
* Also, there is a def xref to a fly paper (PMID:25523082)


@slaulederkind @hdrabkin @ukemi @vanaukenk @hattrill 

Are you OK with the changes proposed above? 

Thanks, Pascale

**Comment by pgaudet** [comment]
ping @slaulederkind @hdrabkin @ukemi @vanaukenk @hattrill

**Comment by pgaudet** [comment]
Useful references: 

[A synopsis on aging-Theories, mechanisms and future prospects ](https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC5991498/) - 2016
[Aging as Disease](https://pubmed.ncbi.nlm.nih.gov/25240472/) - 2014

**Comment by slaulederkind** [comment]
RGD is okay with the change

**Comment by hdrabkin** [comment]
MGI is ok with that also

**Comment by hattrill** [comment]
FB is fine with this.
