### ISSUE TITLE
Obsoletion notice: GO:0090647 modulation of age-related behavioral decline

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22736]
Hi @RLovering 

'GO:0090647 modulation of age-related behavioral decline' is mostly used by your group, and according to its definition it describes a phenotype "Any process that modulates the processes that arise as an organism progresses toward the end of its lifespan that results in a decline in behavioral activities such as locomotory behavior, and learning or memory." 

@ValWood and I have looked at several of your annotations and there was always a better process term (such as 'learning or memory' , as well as cellular processes such as 'regulation of spontaneous synaptic transmission' & several others: would you object to obsoleting GO:0090647 modulation of age-related behavioral decline ? 

Note that this was created here #11858 to get rid of a phenotypic-sounding term, but this newer term doesn't sound any more like a normal process. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Both

I have deleted all UCL annotations associated with this term, at least I hope I have. If you want to have a list of annotations deleted and also annotation AEs removed see attached tables.
Best
Ruth
[QuickGO-annotations-UCL_aging_annotations_deleted.xlsx](https://github.com/geneontology/go-ontology/files/7936763/QuickGO-annotations-UCL_aging_annotations_deleted.xlsx)
[QuickGO-annotations-aging_AE.xlsx](https://github.com/geneontology/go-ontology/files/7936795/QuickGO-annotations-aging_AE.xlsx)

**Comment by pgaudet** [comment]
Thanks @RLovering for the quick reply!

**Comment by pgaudet** [comment]
I put the annotations in a Annotation review spreadsheet

https://docs.google.com/spreadsheets/d/1Q_GzH8C9GFngSNNHHwpTEoc7rtxhZOwUpxXUvjKS2O0/edit#gid=0
