### ISSUE TITLE
GO:0033881 - fix EC and RHEA

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22749]
From @kaxelsen 

GO:0033881 bile-acid-CoA hydrolase activity
This GO term is outdated. EC 3.1.2.26 has been transferred to EC 2.8.3.25 and RHEA:17693 replaced by RHEA:49436.
I'm just about to OBSOLETE RHEA:17693.

**Comment by kaxelsen** [comment]
Note that there is no hydrolase. It in reality a transferase, so it catalyses quite a different reaction:
RHEA:49436 cholate + deoxycholoyl-CoA = choloyl-CoA + deoxycholate

**Comment by pgaudet** [comment]
right I will move the term and change the label - thanks  !

**Comment by pgaudet** [comment]
Likewise for     GO:0033792   bile-acid 7alpha-dehydroxylase activity
* EC:1.17.99.5 transferred to EC:1.1.1.395
* General Rhea reaction: RHEA:55380: a 3alpha-hydroxy bile acid CoA +   NAD+ =   a 3-oxo bile acid CoA +   H+ +   NADH
* Moved under 'oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor' (EC:1.1.1.-)
