### ISSUE TITLE
Add parent to GO:0000900 translation repressor activity, mRNA regulatory element binding

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#22747]
Hi

please add is_a parent 

GO:0003729 | mRNA binding
to
GO:0000900 translation repressor activity, mRNA regulatory element binding
Thanks
Ruth

**Comment by pgaudet** [comment]
to be consistent with other terms, we should use 'has part' DNA binding; is this OK ?

**Comment by pgaudet** [comment]
Also, I propose to change the term label to get rid of the comma, to 'mRNA regulatory element binding translation repressor activity'

**Comment by RLovering** [comment]
sure
