### ISSUE TITLE
NTR: pyridoxine 5'-phosphate oxidase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#22748]
Please provide as much information as you can: 

* **Suggested term label**
* Molecular function

* **Definition (free text)**
* Catalysis of the reaction: O2 + pyridoxine 5'-phosphate = H2O2 + pyridoxal 5'-phosphate 

* **Reference, in format PMID**
* PMID:12824491
* PMID:15182361

* **Gene product name and ID to be annotated to this term**
* Q9NVS9_PNPO_HUMAN

* **Parent term(s)**
* Child of GO:0016899
* Child of GO:0042823? by analogy to GO:0004733 pyridoxamine 5'-phosphate activity, which is a child of GO:0016641    as well?

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
  Rhea:15149
  EC=1.4.3.5
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* Thanks!

**Comment by pgaudet** [comment]
Hi @nnouspikel , 

It seems like this is another substrate of Pyridoxal 5'-phosphate synthase - could we add this as a synonym for GO:0004733  pyridoxamine-phosphate oxidase activity? 

And add the other RHEA xref. 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Thank you Pascale for the quick answer.
I am not sure we can use one GO term for two distinct catalytic activities
https://www.rhea-db.org/rhea/15149 (oxidation of the 4′-hydroxyl group of PNP; oxidoreductase activity, acting on the CH-OH group of donors, oxygen as acceptor)
https://www.rhea-db.org/rhea/15817 (oxidation of the 4′-amino group of PMP; oxidoreductase activity, acting on the CH-NH2 group of donors, oxygen as acceptor)
I suggest we create a new GO term but I might be wrong.  Maybe we need to discuss it further with the RHEA team. 
à plus

**Comment by pgaudet** [comment]
Sorry @nnouspikel I am just looking at this again now - 

actually both these RHEA are linked to the same EC, https://enzyme.expasy.org/EC/1.4.3.5, which is an oxidoreductase activity, acting on the CH-NH2 group of donors, oxygen as acceptor - if  these are not the same reactive atoms, maybe the EC should also be split ?

**Comment by nnouspikel** [comment]
Good question. I suggest we discuss this matter with Kristian.

**Comment by pgaudet** [comment]
One possibility would be to represent both reactions with the label 'Pyridoxine/pyridoxamine 5'-phosphate oxidase' (as in PMID;31506944) & change the definition to include the other substrate described in EC. But that implies that both reactions are using CH-NH2 groups as donors. 

+ need to make sure we have both RHEAs: 15149 and 15817.

**Comment by kaxelsen** [comment]
pyridoxine does not have a CH-NH2 group. I have to look into this a little further.

**Comment by kaxelsen** [comment]
I have now discussed the case with my IUBMB colleagues, and the reason there is only one EC number is that we have at some point decided to only create one EC number coorespondng to the main reaction, even when an enzyme catalyses two reactions that do not belong in the same subclass or sub-subclass.

**Comment by pgaudet** [comment]
Actually we cannot have an EXACT Rhea xref + another one, so I had to remove RHEA:15149

**Comment by nnouspikel** [comment]
Thank you Pascale for your help.
