### ISSUE TITLE
NTR: [flavinator activity]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22751]
Please provide as much information as you can: 

this term will replace GO:0018293 | protein-FAD linkage in the BP modification branch

* **Suggested term label:**

flavinator activity

* **Definition (free text)**

an activity that attaches FAD covalently to a protein

* **Reference, in format PMID:#######**
Reference: Hao HX, et al. (2009) SDH5, a gene required for flavination of succinate dehydrogenase, is mutated in paraganglioma. Science 325(5944):1139-42
PMID: 19628817

* **Gene product name and ID to be annotated to this term**

cerevisiae sdh5
pombe emi5
human SDHAF2

* **Parent term(s)**

? chaperone???

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

related 'flavination'
exact  protein-FAD linkage
-- | --

* **Any other information**
Flavinator came from https://www.ebi.ac.uk/interpro/entry/InterPro/IPR005631/
https://en.wiktionary.org/wiki/flavination

**Comment by pgaudet** [comment]
@kaxelsen Should this be a RHEA reaction?

**Comment by kaxelsen** [comment]
There is no reaction described in the paper, and in addition the role of SDH5 is not known. From pmid:19628817: "Whether Sdh5 participates in the chemistry of FAD attachment (enzymatic function) or simply maintains Sdh1 in a conformation that is susceptible to autocatalytic FAD attachment (chaperone function) is a question that remains to be addressed."

In a newer paper 2016 (pmid:27296776) they write: "At this time (...) the actual function of SDH5 is still unknown." I haven't found any more recent publications than this.

So, currently, I can't create a reaction

**Comment by pgaudet** [comment]
Thanks for checking @kaxelsen 

@ValWood Maybe you can use an existing term?

**Comment by ValWood** [comment]
Thes request was to replace the MF in BP term "protein-FAD linkage" in the 'protein modification branch' but seems a bit premature.

Based on @kaxelsen response I think we should maybe delete  "protein-FAD linkage" term from the BP ontology  in the short term until/if an actual  MF is identified. 

I only have a single GP annotated to this term (by ISO to SGD) but  the gene product  is also annotated to 
"GO:0034553 | mitochondrial respiratory chain complex II assembly"
which seems sufficient at present.

This seems to be a process that should not have been created. It was created because the MF was not certain  to exist (not a good reason!).

**Comment by kaxelsen** [comment]
This article desribes a different way of flavinylation. Where SDH5 is part of the succinate dehydrogenase complex, pmid:18793324 is about the vanillyl-alcohol oxidase. In the latter case the flavinylation is shown to be autocatalytic, but this cannot be extrapolated to the succinate dehydrogenase complex where SDH5 has an essential albeit still undefined role in flavinylation.

Regarding a reaction, I will have to discuss with @amorgat whether we want to include autocatalytic reactions in Rhea. In addition the nature of the electron acceptor has not been settled. In the paper the authors suggest that O2 is used but they can also get fully flavinylated vanillyl-alcohol oxidase under anaerobic conditions.

**Comment by ValWood** [comment]
I only wanted this term to reannotate
GO:0018293 protein-FAD linkage
This term should not be used for direct annotation.
but instead, for now I will delete PomBase ISS annotation.
Can close this until there is more information available about the mechanism
