### ISSUE TITLE
NTRs for H3K56 de/methylation

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22757]
* **Suggested term label:**
histone methyltransferase activity (H3-K56 specific)
histone H3-tri/dimethyl-lysine-56 demethylase activity

* **Definition (free text)**
histone methyltransferase activity (H3-K56 specific): Catalysis of the reaction: S-adenosyl-L-methionine + histone H3 L-lysine (position 56) = S-adenosyl-L-homocysteine + histone H3 N6-methyl-L-lysine (position 56). This reaction is the addition of a methyl group onto lysine at position 56 of the histone H3 protein."

histone H3-tri/dimethyl-lysine-56 demethylase activity: Catalysis of the removal of a methyl group from a tri or a dimethyl-lysine residue at position 56 of the histone H3 protein.

(suggested defs follow format of existing similar terms)

* **Reference, in format PMID:#######**
PMID: 23451023
PMID: 28743002 

* **Gene product name and ID to be annotated to this term**
histone methyltransferase activity (H3-K56 specific): mouse Suv39h1 (O54864) & Suv39h2 (Q9EQQ0)

histone H3-tri/dimethyl-lysine-56 demethylase activity: mouse Kdm4A-D, human Kdm4E, fly Kdm4A (Q9V333)

* **Parent term(s)**
histone methyltransferase activity (H3-K56 specific): GO:0018024 histone-lysine N-methyltransferase activity

histone H3-tri/dimethyl-lysine-56 demethylase activity:  GO:0032452 histone demethylase activity & GO:0016706 2-oxoglutarate-dependent dioxygenase activity

* **Cross-references**
I couldn't find any existing EC/Rhea for these.

* **Other information**
I'm assuming we don't want to make corresponding BP terms for these MF terms like 'histone H3-K56 methylation' and 'histone H3-K56 demethylation', even though those types of BP are in the current GO for existing histone methyltransferase/demethylase terms?

**Comment by pgaudet** [comment]
> I'm assuming we don't want to make corresponding BP terms for these MF terms like 'histone H3-K56 methylation' and 'histone H3-K56 demethylation', even though those types of BP are in the current GO for existing histone methyltransferase/demethylase terms?


Right. I'll start working on these ASAP.

**Comment by pgaudet** [comment]
@sjm41 
The demethylases you cite are already annotated to demethylation of H3K9 and in some cases others. 

Are the demethyalases specific? 

Thanks, Pascale

**Comment by pgaudet** [comment]
(sorry that was meant to apply to both the methylase and the demethlyase)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140759
+name: histone methyltransferase activity (H3-K56 specific)
+namespace: molecular_function
+def: "Catalysis of the reaction: S-adenosyl-L-methionine + histone H3 L-lysine (position 56) = S-adenosyl-L-homocysteine + histone H3 N6-methyl-L-lysine (position 56). This reaction is the addition of a methyl group onto lysine at position 56 of the histone H3 protein." [PMID:23451023, PMID:28743002]
+synonym: "histone lysine N-methyltransferase activity (H3-K56 specific)" EXACT []
+is_a: GO:0018024 ! histone-lysine N-methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22757 xsd:anyURI
+created_by: pg
+creation_date: 2022-01-28T08:39:20Z
+
+[Term]
+id: GO:0140760
+name: histone H3-tri/dimethyl-lysine-56 demethylase activity
+namespace: molecular_function
+def: "Catalysis of the removal of a methyl group from a tri or a dimethyl-lysine residue at position 56 of the histone H3 protein." [PMID:23451023, PMID:28743002]
+synonym: "histone demethylase activity (H3-K56 specific)" RELATED []
+synonym: "histone H3K56me2 demethylase activity" RELATED []
+synonym: "histone H3K56me3 demethylase activity" RELATED []
+is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
+is_a: GO:0032452 ! histone demethylase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22757 xsd:anyURI
+created_by: pg
+creation_date: 2022-01-28T08:45:09Z

**Comment by sjm41** [comment]
_The demethylases you cite are already annotated to demethylation of H3K9 and in some cases others.
(sorry that was meant to apply to both the methylase and the demethlyase)_

Ah, no. Abstract of PMID: 23451023 says "Suv39h enzymes, responsible for trimethylation of H3K9, also affect methylation of H3K56. Similarly, we demonstrate that trimethylation of H3K56 is removed by members of the JMJD2 family of demethylases that also target H3K9me3."

Does that mean we should remove the 'specific' from the term name of 'GO:0140759 histone methyltransferase activity (H3-K56 specific)'?
