### ISSUE TITLE
change mitochondrial transcription factor activity GO:0034246 to part_of regulation of mitochondrial transcription GO:1903108

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#22765]
Based on GOC Transcription Factors Annotation Guidelines (https://docs.google.com/document/d/1bqCxx7QUblrc9q4PIynbJzoCXv248UWBxJa7fguJyXs/edit?pli=1#heading=h.pwxacfdlynjn)
I think MF mitochondrial transcription factor activity GO:0034246
should be changed to 
part_of regulation of mitochondrial transcription GO:1903108
instead of
part_of mitochondrial transcription

**Comment by pgaudet** [comment]
Hi @Pauldenny 

Thanks for your message. During the transcription group discussions, we found out that mitochondria transcription is not regulated on a gene level as the nuclear genes, ie the transcription factor serves more like a nuclear GTF, this is why it's part of mitochondrial transcription and not regulating it. 

Actually we should check which genes are annotated to regulation of mt RNA transcription. There is one paper showing that methylation of mtAdenine reduces the level of mt transcription, PMID:33876744, this seems correct. 

 Does that address your question? 

Thanks, Pascale

**Comment by Pauldenny** [comment]
Yes, thanks.
I didn't know about that subtlety of regulation transcription in mitochondria.
Fast response!
