### ISSUE TITLE
NTR: [MF terms missing for BPs pending obsoletion, histone modifications]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22769]
- [x] NTR: histone deubiquitinase activity

to replace BP GO:0016578 histone deubiquitination.
Definition:
An isopeptidase activity that cleaves ubiquitin from a histone to which it is conjugated.
Parent: GO:0101005 deubiquitinase activity
Ref: PMID:16611979  PMID:29352077
Related synonym: histone deubiquitination

- [x] NTR: histone H3K14 ubiquitin ligase activity
to replace BP GO:0140373 histone H3-K14 ubiquitination
Definition:
Catalysis of the transfer of ubiquitin to a histone H3-K14  via the reaction X-ubiquitin + histone H3-K14 -> X + histone H3-K14-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the histone H3-K14-ubiquitin linkage is an amide bond: an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate or, in the linear extension of ubiquitin chains, a peptide bond the between the C-terminal glycine and N-terminal methionine of ubiquitin residues.
Parent: GO:0061630 ubiquitin protein ligase activity
Ref: PMID:31468675
Related synonym: histone H3-K14 ubiquitination

- [x] NTR: histone H2B conserved C-terminal lysine ubiquitin ligase activity   
to replace BP GO:0071894  histone H2B conserved C-terminal lysine ubiquitination
Note: that in a histone that has not had the N-terminal methionine removed  the position is K120 but most of the positioning  refers to the mature form.
Definition:
Catalysis of the transfer of ubiquitin to a  histone H2B conserved C-terminal lysine  via the reaction X-ubiquitin + histone H2B conserved C-terminal lysine -> X + histone H2B conserved C-terminal lysine-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the histone H2B conserved C-terminal lysine linkage is an amide bond: an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate or, in the linear extension of ubiquitin chains, a peptide bond the between the C-terminal glycine and N-terminal methionine of ubiquitin residues.
Parent: GO:0061630 ubiquitin protein ligase activity
Ref: PMID: 17363370
Related synonym: histone H2B conserved C-terminal lysine ubiquitination
Related synonym: ubiquitination of histone H2B at lysine 119 (H2B-K119)

- [ ] NTR: histone H4K12 deacetylase activity
to replace  BP GO:1990679	histone H4-K12 deacetylation
Definition: 
Catalysis of the reaction: histone H4 N6-acetyl-L-lysine (position 12) + H2O = histone H4 L-lysine (position12) + acetate. This reaction represents the removal of an acetyl group from lysine at position 12 of the histone H4 protein. 
Parent: GO:0004407 histone deacetylase activity
Ref: PMID:22771823
Related synonym: histone H4-K12 deacetylation

- [ ] histone H3K36 dimethylase to replace GO:0097676	histone H3-K36 dimethylation
- [ ] histone H3K36 trimethylase to replace  GO:0097198	 histone H3-K36 trimethylation

I don't know if we want/need terms specific for di/tri methylation as I am not sure if different enzymes perform these modifications, or that if  a methyl transfer are can do is methylation it can also do trimethylation
Maybe we should consult Rhea about this?

**Comment by pgaudet** [comment]
> I don't know if we want/need terms specific for di/tri methylation as I am not sure if different enzymes perform these modifications, or that if a methyl transfer are can do is methylation it can also do trimethylation

@sjm41 and I looked at that in detail here #21089

Some enzymes do more than one methylation, some do a single one. We tried to represent all known activites.

**Comment by ValWood** [comment]
Can  we get
NTR: histone deubiquitinase activity
from this ticket (then GO:0016578 histone deubiquitination can be obsoleted)

**Comment by pgaudet** [comment]
@ValWood , for 

> NTR: histone H4K12 deacetylase activity
to replace BP GO:1990679 histone H4-K12 deacetylation
Definition:
Catalysis of the reaction: histone H4 N6-acetyl-L-lysine (position 12) + H2O = histone H4 L-lysine (position12) + acetate. This reaction represents the removal of an acetyl group from lysine at position 12 of the histone H4 protein. 
Parent: GO:0004407 histone deacetylase activity
Ref: PMID:22771823
Related synonym: histone H4-K12 deacetylation


I cannot find evidence for this activity in the paper - can you please double check?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140934
+name: histone deubiquitinase activity
+namespace: molecular_function
+def: "A deubiquitinase that cleaves ubiquitin from a histone protein to which it is conjugated." [PMID:18226187]
+synonym: "histone deubiquitination" RELATED []
+is_a: GO:0101005 ! deubiquitinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22769 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T07:39:52Z
+
+[Term]
+id: GO:0140935
+name: histone H2B conserved C-terminal lysine deubiquitinase activity
+namespace: molecular_function
+def: "A histone deubiquitinase that cleaves ubiquitin from the conserved C-terminal lysine residue of a histone H2B protein to which it is conjugated. The conserved lysine residue is K119 in fission yeast, K123 in budding yeast, and K120 in mammals." []
+synonym: "histone conserved C-terminal lysine deubiquitination" RELATED []
+is_a: GO:0140936 ! histone H2B deubiquitinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22769 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T07:46:50Z
+
+[Term]
+id: GO:0140936
+name: histone H2B deubiquitinase activity
+namespace: molecular_function
+def: "A histone deubiquitinase that cleaves ubiquitin from a histone H2B protein to which it is conjugated." []
+synonym: "histone H2B deubiquitination" RELATED []
+is_a: GO:0140934 ! histone deubiquitinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22769 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T08:10:30Z



??? not sure about this one ===>>> 
+[Term]
+id: GO:0140937
+name: histone H4K12 deacetylase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: histone H4 N6-acetyl-L-lysine (position 12) + H2O = histone H4 L-lysine (position 12) + acetate. This reaction represents the removal of an acetyl group from lysine at position 12 of the histone H4 protein." [GOC:vw, PMID:22771823]
+synonym: "histone deacetylase activity (H4-K12 specific)" EXACT []
+synonym: "histone H4-K12 deacetylase activity" EXACT []
+synonym: "histone H4-K12 deacetylation" RELATED []
+is_a: GO:0004407 ! histone deacetylase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22769 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T08:12:49Z

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140950
+name: histone H2A deubiquitinase activity
+namespace: molecular_function
+def: "A histone deubiquitinase that cleaves ubiquitin from a histone H2A protein to which it is conjugated." [PMID:18226187, PMID:20436459]
+synonym: "histone H2A deubiquitination" RELATED []
+is_a: GO:0140934 ! histone deubiquitinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22769 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T11:11:26Z

**Comment by ValWood** [comment]
for 
NTR: histone H4K12 deacetylase activity
use
PMID: 15293224

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140954
+name: histone H3K36 mono/dimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl36-[histone H3] + 2 S-adenosyl-L-methionine = 2 H+ + N6,N6-dimethyl-L-lysyl36-[histone H3] + 2 S-adenosyl-L-homocysteine. This reaction is the successive addition of two methyl groups to the lysine residue at position 36 of histone H3, producing histone H3K36me2." [RHEA:60308]
+synonym: "histone H3K27 mono/dimethylase activity" EXACT []
+xref: EC:2.1.1.357
+xref: RHEA:60308
+is_a: GO:0046975 ! histone H3K36 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T15:06:50Z
+
+[Term]
+id: GO:0140955
+name: histone H3K36 mono/di/trimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl36-[histone H3] + 3 S-adenosyl-L-methionine = 3 H+ + N6,N6,N6-trimethyl-L-lysyl36-[histone H3] + 3 S-adenosyl-L-homocysteine. This reaction is the successive addition of three methyl groups to the lysine residue at position 36 of histone H3, producing histone H3K36me3." [RHEA:60324]
+synonym: "histone H3K27 mono/dimethylase activity" EXACT []
+xref: EC:2.1.1.359
+xref: RHEA:60324
+is_a: GO:0046975 ! histone H3K36 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-01T15:18:59Z
+
+[Term]
+id: GO:0140956
+name: histone H3K79 trimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl79-[histone H3] + 3 S-adenosyl-L-methionine = 3 H+ + N6,N6,N6-trimethyl-L-lysyl79-[histone H3] + 3 S-adenosyl-L-homocysteine. This reaction is the successive addition of up to three methyl group to the lysine residue at position 79 of the histone H3 protein, producing H3K79me3." [PMID:15371351, RHEA:60328]
+synonym: "histone H3K79 trimethylase activity" EXACT []
+synonym: "histone lysine N-trimethyltransferase activity (H3-K79 specific)" EXACT []
+synonym: "histone trimethylase activity (H3-K79 specific)" EXACT [GOC:mah]
+synonym: "histone trimethyltransferase activity (H3-K79 specific)" EXACT []
+synonym: "histone-H3K79 trimethyltransferase activity" EXACT []
+xref: EC:2.1.1.360
+xref: RHEA:60328
+is_a: GO:0031151 ! histone H3K79 methyltransferase activity
+created_by: pg
+creation_date: 2022-11-01T15:47:14Z

**Comment by pgaudet** [comment]
Still need to find evidence for this term: 


[Term]
id: GO:0140935
name: histone H2B conserved C-terminal lysine deubiquitinase activity
namespace: molecular_function
def: "A histone deubiquitinase that cleaves ubiquitin from the conserved C-terminal lysine residue of a histone H2B protein to which it is conjugated. The conserved lysine residue is K119 in fission yeast, K123 in budding yeast, and K120 in mammals." []
synonym: "histone conserved C-terminal lysine deubiquitination" RELATED []
is_a: GO:0140936 ! histone H2B deubiquitinase activity
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22769 xsd:anyURI
created_by: pg
creation_date: 2022-11-01T07:46:50Z

**Comment by ValWood** [comment]
see 
https://www.ebi.ac.uk/QuickGO/term/GO:0035616
for GO:0140935 (its Ubp8 SAGA complex ubiquitin C-terminal hydrolase Ubp8)
