### ISSUE TITLE
Obsoletion notice: GO:0016584 nucleosome positioning

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22764]
Dear all, 

The proposal has been made by the Transcription working group to obsolete GO:0016584 nucleosome positioning. The reason for obsoletion is that this should be captured as a molecular function, either  'GO:0140751 histone octamer slider activity'  or  'GO:0140750 nucleosome array spacer activity'. 
There are 52 EXP annotations: 

Contributor   (Assigned by) |  
-- | --
AspGD | 9 |  
CACAO | 1 |  
ComplexPortal | 8 |  
dictyBase | 1 |  
FlyBase | 4 | DONE
MGI | 3 |  
PomBase | 4 | DONE
SGD | 12 |  
TAIR | 3 |  
UniProt | 6 | DONE
ZFIN | 1 |  

You can comment on the ticket here:  https://github.com/geneontology/go-ontology/issues/22764

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 3, 2022. Unless objections are received by February 3, we will assume that you agree to this change.

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/1_cnnuzUxHQVEz5Ho34kBTESXAbBooPWGgM1wx9WUywA/edit#gid=0

**Comment by hattrill** [comment]
FB done.

**Comment by pfey03** [comment]
DDB done

**Comment by sramachand** [comment]
ZFIN done
