### ISSUE TITLE
incorrect parentage : production of siRNA involved in RNA interference

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22772]
production of siRNA involved in RNA interference

is now under
 gene silencing by RNA
posttranscriptional gene silencing

but  this is part of heterochromatin silencing, not post-transcriptional gene silencing

(I still think this is a weird term, because it can be represented as "activities", part of the broader process (in this case heterochromatin assembly)

**Comment by pgaudet** [comment]
@ValWood The definition of RNA interference clearly talks about posttranscriptional gene inactivation via either the decrease in the level of mRNA, or by negative regulation of translation. 

Do you have a reference that links RNA interference and heterochromatin assembly?

**Comment by ValWood** [comment]
Yes, ignore,my  annotation is worng.
