### ISSUE TITLE
Taxon constraint: GO:0035195 gene silencing by miRNA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22771]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0035195 gene silencing by miRNA

* **Request to add a taxon constraint:**

* * **never in taxon: **

Fission yeast
Budding yeast

(I don't well enough which RNAi based processes other yeast/fungi have to suggest further taxon restrictions)

**Comment by ValWood** [comment]
actually the constraint should be at the parent
post-transcriptional gene silencing by RNA (GO:0035194)

**Comment by pfey03** [comment]
Just to make it clear, Dicty has these BP

**Comment by pgaudet** [comment]
Looks like bateria also has some regulation of gene expression by RNAi, see PseudoCAP annotations for eg to PMID:15210934.

**Comment by ValWood** [comment]
Fission yeast
Budding yeast
was incorrect becasue some fission yeast (i.e Schizosaccharomyces  japonicus, new paper this week PMID: 35226668) has this pathway. So just to check that the taxon restriction was assed for S . pombe speccifically and not all Schizosaccharomyces.
