### ISSUE TITLE
NTR: [sneeze reflex]

### ISSUE THREAD

**Issue by magrane** [geneontology/go-ontology#22789]
Please provide as much information as you can: 

* **Suggested term label:** sneeze reflex

* **Definition (free text)** A respiratory reflex process in which a chemical irritant or allergen stimulates nasal sensory neurons, giving rise to the sneeze reflex.

* **Reference, in format PMID:#######** PMID:34133943

* **Gene product name and ID to be annotated to this term** mouse Nmb (Q9CR53) & Nmbr (O54799)

* **Parent term(s)** GO:0060004 (reflex)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Adopting a more general definition may be better?

**Comment by magrane** [comment]
A more general definition is fine by me. Would something like the following work: "A respiratory reflex process in which nasal sensory neurons are stimulated, giving rise to the sneeze reflex"?

**Comment by raymond91125** [comment]
@magrane This is what I propose. Would it work?
"A reflex process that expels air forcibly from the mouth and nose in an explosive, spasmodic involuntary action resulting chiefly from irritation of the nasal mucous membrane." [https://www.thefreedictionary.com/sneeze, PMID:34133943]

**Comment by magrane** [comment]
Sounds good to me. Thanks!
