### ISSUE TITLE
Obsoletion proposal: GO:0007569 cell aging & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22788]
Dear all, 

The proposal has been made to obsolete GO:0007569 cell aging & regulation children. The reason for obsoletion is that this represents a phenotype. Some annotations can be moved to the term 'cellular senescence'. 

There are 120 EXP annotations: [GO:0007569 cell aging & regulation children](https://docs.google.com/spreadsheets/d/1FdIe-cpZms1Qsw7wBTF5N8ep59N3wUwoOrXnZaWLLRs/edit#gid=0)

There are no mappings; these terms are not present in any subsets.

Contributor  |  (Assigned by)
--|--
BHF-UCL | 5
CAFA | 1
FlyBase | 2
MGI | 73
RGD | 10
SGD | 7
TAIR | 4
UniProt | 15 - fixed
ZFIN | 3

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22788

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on February 8th, 2022. Unless objections are received by Feb 8th, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Also moved children of cell aging: 

- [ ] GO:0090398 cellular senescence
removed  is_a: GO:0007569 ! cell aging
removed is_a: GO:0033554 ! cellular response to stress
added is_a: GO:0044237 ! cellular metabolic process part_of GO:0033554 ! cellular response to stress


- [ ] GO:0090399  replicative senescence
removed is_a: GO:0007569 ! cell aging
added is_a: GO:0044237 ! cellular metabolic process

**Comment by cmungall** [comment]
The definition of replicative senescence is still:

"cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging."

Which doesn't make any sense as the genus is gone. In any case it's pretty vague and sounds like a response term

**Comment by pgaudet** [comment]
Absolutely. I thought @ValWood had proposed to obsolete it.

**Comment by pgaudet** [comment]
See https://github.com/geneontology/go-ontology/issues/25380

**Comment by ValWood** [comment]
not according to other tickets
https://github.com/geneontology/go-ontology/issues/18632
isn't this a programmed process in metazoa (or is senescence covered by other terms? I don't know how it differs from cellular senescence?). 
Aren't there programmed pathways for both senescence and apoptosis (damaged cells undergo one or the other)
The problem might be the definition?  (i.e. it isn't restricted to ageing, at least in the sense of age-related deterioration).

**Comment by pgaudet** [comment]
moved cellular senscence under cellular process rather than metabolic process.
