### ISSUE TITLE
Obsoletion notice: GO:1903374 subarachnoid space development

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22785]
Dear all, 

The proposal has been made to obsolete GO:1903374 subarachnoid space development. The reason for obsoletion is that there is no evidence that this process exists. 'subarachnoid space' is a brain anatomical structure (https://en.wikipedia.org/wiki/Meninges#Subarachnoid_space), but there is no evidence that there is a process leading to its development; a space a left between other structures (arachnoid and the pia mater.)

There are no annotations or mappings to this term; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22785

Thanks, Pascale

**Comment by dosumis** [comment]
This seems to describe the process:  https://www.karger.com/Article/Abstract/119893

Is this issue that that it would be better to break this down into component processes affecting the bounding structures, their separation and contents of the space ?

**Comment by pgaudet** [comment]
Yes, I think this is the problem. 

As I understand it, the abstract of paper you cite describes the _establishement_ of the subarachnoid space as the results of development of surrounding structures: (ie there is no subarachnoid space development process per se?) 

the first follows closure of the neural tube and is a period of initial vascularization of the developing telencephalon; the second is a period of delineation during which the limits of the subarachnoid space are defined; the third is a period of ensheathment of pia-arachnoidal blood vessels; and the fourth includes addition of smooth muscle to larger vessels, the appearance of macrophages in the subarachnoid space, and a general increase in extracellular collagenous and elastic fibers.
