### ISSUE TITLE
incorrect link: regulation of neurogenesis part-of neurogenesis

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#22790]
![image](https://user-images.githubusercontent.com/50745/152079676-93925382-40ca-4702-b1d1-20c6b4d66a06.png)

note the part-of-is-a path. This is unusual

Here it is in obo in the edit file

id: GO:0050767
name: regulation of neurogenesis
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of neurogenesis, the generation of cells in the nervous system." [GOC:ai]
is_a: GO:0051960 ! regulation of nervous system development
is_a: GO:0060284 ! regulation of cell development
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0022008 ! neurogenesis
***relationship: part_of GO:0048699 ! generation of neurons***
relationship: regulates GO:0022008 ! neurogenesis

id: GO:0048699
name: generation of neurons
namespace: biological_process
def: "The process in which nerve cells are generated. This includes the production of neuroblasts and their differentiation into neurons." [GOC:nln]
synonym: "neuron generation" EXACT []
***is_a: GO:0022008 ! neurogenesis***

**Comment by raymond91125** [comment]
Cannot find the reasoning for the part_of relation. Also regulation of neurogenesis now covers the regulation of non-neuron cell generation thus it cannot be part of the generation of neurons, see #15272.
