### ISSUE TITLE
Change term label and  GO:0004117   calmodulin-dependent cyclic-nucleotide phosphodiesterase activity to dual specificity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22791]
Discussing with @lbreuza 

Some enzymes (including PDE1A, PDE1B and PDE1C) have dual specificity for cAMP and cGMP. All annotations to GO:0004117   calmodulin-dependent cyclic-nucleotide phosphodiesterase activity are to these proteins, probably using the broader term to represent dual specificity. 

So, we will change the label of GO:0004117 calmodulin-dependent cyclic-nucleotide phosphodiesterase activity 
to "calmodulin-activated dual specificity 3',5'-cyclic-GMP, 3',5'-cyclic-AMP phosphodiesterase activity" 
EXACT SYNONYM:"calmodulin-activated cyclic-nucleotide dual specificity phosphodiesterase activity"

And update the definition from: "Catalysis of the reaction: nucleoside 3',5'-cyclic phosphate + H2O = nucleoside 5'-phosphate; catalytic activity is regulated by calmodulin."
to "Catalysis of the reactions: 3',5'-cyclic AMP + H2O = AMP + H+ and 3',5'-cyclic GMP + H2O = GMP + H+; this activity is activated by binding to calcium-bound calmodulin..

---

To be consistent, I will also update 'GO:0048101 calcium- and calmodulin-regulated 3',5'-cyclic-GMP phosphodiesterase activity'  to 'calmodulin-activated 3',5'-cyclic-GMP phosphodiesterase activity''

**Comment by lbreuza** [comment]
HI,
we have:
GO:0048101 calcium- and calmodulin-regulated 3',5'-cyclic-GMP phosphodiesterase activity

Could you please create the corresponding term for 3',5'-cyclic-GMP as a child of GO:0004115 3',5'-cyclic-AMP phosphodiesterase activity

Thank you

**Comment by pgaudet** [comment]
Refs, dual specificity:
PMID:=9419816
PMID:8557689

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140761
+name: calmodulin-activated 3',5'-cyclic-AMP phosphodiesterase activity
+namespace: molecular_function
+def: "Catalysis of the reactions: nucleoside 3',5'-cyclic AMP + H2O = AMP + H+; this activity is activated by binding to calcium-bound calmodulin." [PMID:15901640]
+synonym: "calcium- and calmodulin-regulated 3',5'-cyclic-AMP phosphodiesterase activity" BROAD []
+synonym: "calcium- and calmodulin-regulated AMP-specific phosphodiesterase activity" EXACT []
+synonym: "calcium- and calmodulin-regulated cAMP phosphodiesterase activity" RELATED []
+synonym: "calcium- and calmodulin-regulated cyclic-AMP phosphodiesterase activity" EXACT []
+synonym: "calcium/calmodulin-regulated cAMP-specific phosphodiesterase activity" EXACT []
+is_a: GO:0004115 ! 3',5'-cyclic-AMP phosphodiesterase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22791 xsd:anyURI
+created_by: pg
+creation_date: 2022-02-02T09:34:34Z
+
