### ISSUE TITLE
Textual definition update: GO:0016246 RNA interference

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22806]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO:0016246 RNA interference

* **New proposed definition (genus-differentia pattern, plus additional information if needed) **
The process in which double-stranded RNAs silence specific target genes. Involves posttranscriptional gene inactivation ('silencing'). Can occur through a specific decrease in the level of mRNA, or by negative regulation of translation.

* **Reference(s)**
PMID:11201747 PMID:11713190 PMID:18771919
https://en.wikipedia.org/wiki/RNA_interference
Ref for RISC Figure 3. Mechanisms of siRNA Silencing [http://europepmc.org/article/MED/19239886](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Feuropepmc.org%2Farticle%2FMED%2F19239886&data=04%7C01%7Cr.lovering%40ucl.ac.uk%7C4a34cd1e82134c1458cc08d9d9bbf823%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637780223606272797%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GWzxN7Z6EMP5I3dSaHO865VdchwzZh6UqHCpDyA2TB8%3D&reserved=0)

* **Additional information**

**Comment by pgaudet** [comment]
Is RNA interefence different from GO:0035194 post-transcriptional gene silencing by RNA? 

Any process of posttranscriptional gene inactivation (silencing) mediated by small RNA molecules that may trigger RNA (often mRNA) degradation or negatively regulate mRNA translation.

**Comment by pgaudet** [comment]
Decision on microRNA call: 

- [ ] merge PTGS into RNA interference. 

- [ ] New def: A posttranscriptional gene silencing process in which regulatory RNAs elicit silencing of specific target genes, either by mRNA destabilization or inhibition of translation.

**Comment by pgaudet** [comment]
@vanaukenk @hattrill 
Most annotations to RNA interference are by your groups - just checking that you are OK with the change in def (see https://github.com/geneontology/go-ontology/issues/22806#issuecomment-1031528112)

**Comment by hattrill** [comment]
I am happy with this. Thanks
