### ISSUE TITLE
NTR: [sensory perception of itch]

### ISSUE THREAD

**Issue by magrane** [geneontology/go-ontology#22807]
Please provide as much information as you can: 

* **Suggested term label:** sensory perception of itch

* **Definition (free text)** The series of events required for an organism to receive an itch stimulus, convert it to a molecular signal, and recognize and characterize the sign.

* **Reference, in format PMID:#######** PMID:30734045

* **Gene product name and ID to be annotated to this term** mouse Nmb (Q9CR53) & Nmbr (O54799)

* **Parent term(s)** GO:0007600 (sensory perception)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)** pruritus

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Proposed definition: "A sensory perception which causes the desire or reflex to scratch. [https://en.wikipedia.org/wiki/Itch, PMID:26015312, PMID:29723501, PMID:30734045]"
Synonym EXACT "pruritus"
@magrane, @pgaudet  Do you think that's good?

**Comment by pgaudet** [comment]
Looks OK to me. 

If you add wiki xrefs it should be added as 
Wikipedia:Itch

Thanks, Pascale

**Comment by magrane** [comment]
Looks fine to me too. My suggested definition was based on other sensory perception terms which seem to follow the format of "The series of events required for an organism to receive an X stimulus, convert it to a molecular signal, and recognize and characterize the signal." But I'm also fine with what you've suggested.
