### ISSUE TITLE
Textual definition update: 

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22828]
Hi GO,

Would it be possible to modify the name, definition and cross-reference (Rhea) of the following terms? It would be consistent with other sirtuin reactions

Thanks

Sylvain

1)
GO:0061690; F:lipoamidase activity;
Change the name to:
NAD-dependent protein lipoamidase activity
New definition:
Catalysis of the reaction: (R)-N6-lipoyl-L-lysyl-[protein] + H2O + NAD+ = 2''-O-lipoyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
New Xref: RHEA:63640 (not yet public)
PMID:25525879

2)
GO:0047708; F:biotinidase activity;
Change the name to:
NAD-dependent protein biotinidase activity
New definition:
Catalysis of the reaction: H2O + N6-biotinyl-L-lysyl-[protein] + NAD+ = 2''-O-biotinyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
New Xref: RHEA:70479 (not yet public)
PMID:25525879

**Comment by hdrabkin** [comment]
GO:0061690; F:lipoamidase activity;   <<<<<< could now be synonym
Change the name to:
NAD-dependent protein lipoamidase activity
New definition:
Catalysis of the reaction: (R)-N6-lipoyl-L-lysyl-[protein] + H2O + NAD+ = 2''-O-lipoyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
New Xref: RHEA:63640 (not yet public)
PMID:25525879
Current Def is broader and does not involve NAD: note that xref  MetaCyc:RXN-13031  reaction also does NOT invoke use of NAD


GO:0047708; F:biotinidase activity;  <<< new proposed synonym 
Change the name to:
NAD-dependent protein biotinidase activity
New definition:
Catalysis of the reaction: H2O + N6-biotinyl-L-lysyl-[protein] + NAD+ = 2''-O-biotinyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
New Xref: RHEA:70479 (not yet public)
PMID:25525879

Current def Catalysis of the reaction: biotin amide + H2O = biotin + NH3 is broader 
EC xef: EC:3.5.1.12  Biotin amide + H(2)O <=> biotin + NH(3)  Broader
Current RHEA RHEA:13081 mapping to the ec is also broader and does not evoke NAD.

So there is a problem here with the renaming and def change in that I don't think these are simple replacements unless I hear that RHEA is obsoleted RHEA:13081
Would new rhea be a child? is it also mapping to the EC:

**Comment by sylvainpoux** [comment]
Hi Harold,

I guess @kaxelsen will be the appropriate person to reply to your question. 

But I think that you are right. NAD-dependent protein biotinidase activity is a different activity not related to GO:0047708; F:biotinidase activity and we should therefore request a new term.

I was confused because of some misannotation, a curator using GO:0047708; F:biotinidase activity to describe NAD-dependent protein biotinidase activity.

Would it be possible to create a new term? 

NAD-dependent protein biotinidase activity
definition:
Catalysis of the reaction: H2O + N6-biotinyl-L-lysyl-[protein] + NAD+ = 2''-O-biotinyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
New Xref: RHEA:70479 (not yet public)
PMID:25525879

Thanks

Sylvain

**Comment by kaxelsen** [comment]
This is a completely parallel discussion to the one in #22836. There seems to be two types of enzymes: a hydrolase type (EC 3.5.1.-) and an NAD-dependent transferase type (EC 2.3.1.-) (e.g. sirtuins). These two types use different chemistry and are unrelated, so there has to be terms for each.

RXN-13031 is a hydrolysis reaction. We do not have an equivalent in Rhea as it is based on an unpurified activity, for which the protein is not known. (pmid:21768091)

**Comment by hdrabkin** [comment]
This makes much more sense. I will make two terms today.

**Comment by hdrabkin** [comment]
Suggest parent? We don't seem to have the base (EC:2.3.1.-)

**Comment by hdrabkin** [comment]
will use Transferring groups other than amino-acyl groups GO:0016747 as parent

**Comment by hdrabkin** [comment]
[Term]
+id: GO:0106419
+name: NAD-dependent protein lipoamidase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: (R)-N6-lipoyl-L-lysyl-[protein] + H2O + NAD+ = 2''-O-lipoyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide." [PMID:25525879, RHEA:63640]
+xref: RHEA:63640 {source="skos:exactMatch"}
+is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups
+property_value: creation_date 2022-02-24T17:53:27Z xsd:dateTime
+created_by: hjd

[Term]
+id: GO:0106420
+name: NAD-dependent protein biotinidase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: H2O + N6-biotinyl-L-lysyl-[protein] + NAD+ = 2''-O-biotinyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide." [PMID:25525879, RHEA:70479]
+xref: RHEA:70479 {source="skos:exactMatch"}
+is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups
+property_value: creation_date 2022-02-24T17:55:29Z xsd:dateTime
+created_by: hjd
