### ISSUE TITLE
NTR: [NAD-dependent histone deacetylase activity (H3-K56 specific)]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22829]
Hi GO,

I would need a new histone deacetylation term.

Thanks

Sylvain

Name: NAD-dependent histone deacetylase activity (H3-K56 specific)
Definition:
Catalysis of the reaction: histone H3 N6-acetyl-L-lysine (position 56) + H2O = histone H3 L-lysine (position 56) + acetate. This reaction requires the presence of NAD, and represents the removal of an acetyl group from lysine at position 56 of the histone H3 protein.

child of  GO:0071572 histone H3-K56 deacetylation
child of  GO:0017136 NAD-dependent histone deacetylase activity

PMID:23911928
PMID:30374165

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140765
+name: NAD-dependent histone deacetylase activity (H3-K56 specific)
+namespace: molecular_function
+def: "Catalysis of the reaction: histone H3 N6-acetyl-L-lysine (position 56) + H2O = histone H3 L-lysine (position 56) + acetate. This reaction requires the presence of NAD, and represents the removal of an acetyl group from lysine at position 56 of the histone H3 protein." [PMID:23911928, PMID:30374165]
+is_a: GO:0017136 ! NAD-dependent histone deacetylase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22829 xsd:anyURI
+created_by: pg
+creation_date: 2022-02-09T08:00:41Z
