### ISSUE TITLE
Some histone deacetylases are hydrolases, some are transferases

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22836]
Protein deacetylases were classified as hydrolases. However, as pointed out by @kaxelsen in  #22833, not all protein deacetylases are hydrolases; the NAD-dependent are transferases. 

This is a nice review that explains the catalytic mechanism of histone deacetylases: 

https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC3970420/

Class I, II and IV are zinc-dependent (hydrolase), while class III is  NAD-dependent (ie transferases)

<img width="766" alt="image" src="https://user-images.githubusercontent.com/4782928/153220637-bd43c99d-ad4a-43ff-b685-dade669cfd18.png">

**Comment by pgaudet** [comment]
- [x] GO:0042903 'tubulin deacetylase activity':  Add missing xref RHEA:21548

**Comment by pgaudet** [comment]
- [ ]  GO:0033558  protein deacetylase activity should be obsoleted: it is used to mostly to annotate HDACs, both hydrolases (Class I, II, IV) and transferases (class III)

**Comment by pgaudet** [comment]
If we are to represent the mechanisms of the HDACs, we would need to obsolete all 'grouping' classes: 
*  [GO:0031078 histone deacetylase activity (H3-K14 specific)](http://amigo.geneontology.org/amigo/term/GO:0031078#display-lineage-tab)
*   [GO:1990162 histone deacetylase activity (H3-K4 specific)](http://amigo.geneontology.org/amigo/term/GO:1990162#display-lineage-tab)
*  [GO:0032129 histone deacetylase activity (H3-K9 specific)](http://amigo.geneontology.org/amigo/term/GO:0032129#display-lineage-tab)
*   [GO:0034739 histone deacetylase activity (H4-K16 specific)](http://amigo.geneontology.org/amigo/term/GO:0034739#display-lineage-tab)
and create 'zinc-specific hydrolases'. The problem is that the grouping terms mix both hydrolases and transferases. 

Alternatively, we can drop the mechanism and merge for example 
GO:0032041 NAD-dependent histone deacetylase activity (H3-K14 specific)  into GO:0031078 histone deacetylase activity (H3-K14 specific), and keep these under 'protein deacetylase activity', that would just be a 'catalytic activity, acting on proteins', and not have and enzyme class. 

@cmungall @hdrabkin @ValWood @sjm41 @colinlog 
do you have preferences one way or the other? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
I would be in favor of making two parents
one specifying hydrolysis, the other specifying NAD 
perhaps naming like
histone deacetylase (hydrolytic) activity 
histone deacetylase (transfer) activity

I see RHEA has the hydrolysis one for EC: 3.5.1.98;

**Comment by ValWood** [comment]
Generally, I am not interested in mechanism so much, but I guess if they are totally different enzyme classes, then it is useful.
Naive question, how can a histone deacetylase be a transferase? (and specifically which ones fall into this class). Currently histone deacetylase is under hydrolase.

(I think there are two mechanisms for histone demethylation, but neither of those is. a transferase)

**Comment by ValWood** [comment]
right it's class 3 above (i'm new to this ticket!)

**Comment by sjm41** [comment]
I agree with @hdrabkin, having two separate parent terms to group the two mechanisms.

But maybe we don't need to make new terms - do these existing terms map to the hydrolytic and transferase mechanisms?:

id: GO:0017136
name: NAD-dependent histone deacetylase activity
def: "Catalysis of the reaction: histone N6-acetyl-L-lysine + H2O = histone L-lysine + acetate. This reaction requires the presence of NAD, and represents the removal of an acetyl group from a histone." [PMID:28450737]
synonym: "SIR2" RELATED []

id: GO:0045129
name: NAD-independent histone deacetylase activity
def: "Catalysis of the reaction: histone N6-acetyl-L-lysine + H2O = histone L-lysine + acetate. This reaction does not require the presence of NAD, and represents the removal of an acetyl group from a histone." [PMID:28450737]
synonym: "AcuC" RELATED []

Both could be children of "catalytic activity -> deacetylase activity -> protein deacetylase activity (if kept) -> histone deacetylase activity".
And each would also have the appropriate parentage to 'transferase activity' and 'hydrolase activity'.

**Comment by colinlog** [comment]
Yes, that sounds right @sjm41 and if the EC classes are associated with each then we are done here with the MF parts once we make an overarching MF 'do-not-annotate-to' parent that is histone ***deacylases***''' with these two terms as its MF children with the respective EC numbers.

I would argue that the specific histone residues connect to specific 'BPs' that will require the above MFs but only work under certain circumstances (eg; chromatin assembly involves H4K5 and H4K12 acetylation in the cytoplasm, followed by their deacetylation after nucleosome assembly in a replication-coupled chromatin maturation pathway, while H4K8 and K16 acetylation/deacetylation controls gene expression and higher order folding of polynucleosomal fibres).

I am not a fan of the 'independent' label , however, as this is in fact a negative definition. That class can be positively identified as being 'Zn-dependent' and corresponds to three of the 4 phylogenetic HDAC classes (I, II and IV -- the hydrolases).

Of note, some of these enzymes (for sure in classes I and III) may be involved in removing larger groups than acetates from histone lysines such as succinyl, crotonyl, malonyl and glutaryl modifications.  (see PMID: 30940741 and 30391813). Furthermore, one of the Zn-dependent HDACs, HDAC3, appears to be stimulated by D-myo-inositol-(1,4,5,6)-tetrakisphosphate (Ins(1,4,5,6)P4).

The field is therefore moving towards calling bioth the NAD-dep and indep enzymes ***deacylases*** rather than deacetylases...

Last thing: the histones are not their unique targets, tubulin as noted by pascale (for HDAC6?) and many dbTFs and coTF are ac(et)ylated and deac(et)ylated. However the classifications based on their activity on the histone types and residues is very likely to be leading for the other substrate classifications and associated BPs.

**Comment by pgaudet** [comment]
@sjm41 

>  do these existing terms map to the hydrolytic and transferase mechanisms?:

Not really, since the NAD is a child of the non-NAD, and more importantly, the non-NAD has annotations for proteins that belong in both groups.

**Comment by pgaudet** [comment]
According to wikipedia https://en.wiktionary.org/wiki/deacylase removes an acyl group by hydrolysis

**Comment by pgaudet** [comment]
@ValWood 

> Naive question, how can a histone deacetylase be a transferase?

The acyl group is transferred, rather than just removed, so products are `[protein]-L-lysine + 2''-O-acetyl-ADP-D-ribose + nicotinamide` rather than  `acetate + L-lysyl-[histone]` for hydrolases

**Comment by colinlog** [comment]
Absolutely let's do it right. Wikipedia follows the literature and GO knowledge, not the opposite, even though it is a fantastic and immensely broad encyclopedic community-generated knowledge resource. 

It has been known for > 20 years that there are sirtuin-type (NAD-dependent) histone deacetylases; eg1 H3K56ac is deacetylated by Hst3 and Hst4 sirtuins in S.c,, eg2 H3K9ac is deacetylated by Sir2 at the S.c subtelomeric regions to enable Sir3+Sir4 - mediated heterochromatin formation *and* there are the Zn-dependent deacetylases that can remove also H3K9ac (but not H3K56ac).

Enzymatically, the NAD-dependent mechanism is different (transferase). But still functionally they are protein lysine deacetylases, as Val just pointed-
out.

**Comment by kaxelsen** [comment]
The reaction in this GO term is wrong!
> id: GO:0017136
> name: NAD-dependent histone deacetylase activity
> def: "Catalysis of the reaction: histone N6-acetyl-L-lysine + H2O = histone L-lysine + acetate. This
> reaction requires the presence of NAD, and represents the removal of an acetyl group from a 
> histone." [PMID:28450737]
> synonym: "SIR2" RELATED []

It should be catalysis of the reaction: N6-acetyl-L-lysyl-[protein] + NAD+ + H2O = 2''-O-acetyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide (RHEA:43636).

The old reaction above IS a hydrolylsis reaction. The new reaction I have just added is the transfer reaction. The lysyl group is transferred to half of a NAD+ molecule (ADP-D-ribose). The rest of the NAD+ molecule is liberated as nicotinamide. That the reaction is NAD-dependent does in this case mean that NAD+ is a part of the reaction.

**Comment by ValWood** [comment]
Aligning GO with Rhea is the best thing ever! 

I think we should definitely have  both the histone acetyltransferase grouping and then the  transferase/acetyltransferase grouping for the subtypes. Apart from being explicit and correct, if we do not do this we will spend the next decade trying to explain to function prediction pipelines why the sirtuins are not hydrolases.

**Comment by sjm41** [comment]
And RHEA:43636 = EC:2.3.1.286 (Protein acetyllysine N-acetyltransferase)

**Comment by sjm41** [comment]
We should try to finish this one.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0045129 NAD-independent histone deacetylase activity. The reason for obsoletion is that this represents the same activity as GO:0004407 histone deacetylase activity (now renamed: GO:0004407 histone deacetylase activity, hydrolytic mechanism). There are 7 annotations: 1 ComplexPortal, 1 SGD, 5 FlyBase, see https://github.com/geneontology/go-annotation/issues/5453


You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22836

Thanks, Pascale

**Comment by pgaudet** [comment]
@sjm41 
I changed the label of 

GO:0004407 'histone deacetylase activity' to  'histone deacetylase activity, hydrolytic mechanism', and added comment: 

+comment: Histone deacytylase (HDAC) enzymes are divided into four classes: the Class I Rpd3-like proteins (in human: HDAC1, HDAC2, HDAC3, and HDAC8); the Class II Hda1-like proteins (in human: HDAC4, HDAC5, HDAC6, HDAC7, HDAC9, and HDAC10); the Class III Sir2-like proteins (in human: SIRT1, SIRT2, SIRT3, SIRT4, SIRT5, SIRT6, and SIRT7); and the Class IV protein (HDAC11 in human). Except for Class III enzymes, the mechanism is a metal-dependent hydrolysis of the acetylated substrate. The Class III HDACs use NAD+ as a reactant to deacetylate acetyl lysine residues of protein substrates forming nicotinamide, the deacetylated product, and the metabolite 2′-O-acetyl-ADP-ribose. Therefore, Class III are classified as transferases (EC:2) and others are hydrolases (EC:3).

to this term and the other general grouping term [NAD-dependent histone lysine deacetylase activity](http://purl.obolibrary.org/obo/GO_0017136)


Current structure is: 

<img width="451" alt="image" src="https://github.com/user-attachments/assets/bb189da3-0a73-4a17-a8ef-35682507887c">

but I think I need to add 'hydrolytic mechanism' to the terms highlighted below 

<img width="475" alt="image" src="https://github.com/user-attachments/assets/98efa1e5-0b23-49be-9f3a-d546523c7d94">



and create a mechanism-neutral parent for H3K deacetylase activity and H4K deacetylase activity. 

What do you think ?

**Comment by pgaudet** [comment]
Created new grouping term: 
+[Term]
+id: GO:0141221
+name: histone deacetylase activity, hydrolytic mechanism
+namespace: molecular_function
+def: "Catalysis of the reaction: H2O + N6-acetyl-L-lysyl-[histone] = acetate + L-lysyl-[histone]." [PMID:24691964, PMID:28450737]
+comment: Histone deacytylase (HDAC) enzymes are divided into four classes: the Class I Rpd3-like proteins (in human: HDAC1, HDAC2, HDAC3, and HDAC8); the Class II Hda1-like proteins (in human: HDAC4, HDAC5, HDAC6, HDAC7, HDAC9, and HDAC10); the Class III Sir2-like proteins (in human: SIRT1, SIRT2, SIRT3, SIRT4, SIRT5, SIRT6, and SIRT7); and the Class IV protein (HDAC11 in human). Except for Class III enzymes, the mechanism is a metal-dependent hydrolysis of the acetylated substrate. The Class III HDACs use NAD+ as a reactant to deacetylate acetyl lysine residues of protein substrates forming nicotinamide, the deacetylated product, and the metabolite 2′-O-acetyl-ADP-ribose. Therefore, Class III are classified as transferases (EC:2) and others are hydrolases (EC:3).
+synonym: "histone deacetylase activity" BROAD []
+synonym: "histone deacetylase activity, NAD-independent" EXACT []
+xref: EC:3.5.1.98 {source="skos:exactMatch"}
+is_a: GO:0004407 ! histone deacetylase activity

**Comment by pgaudet** [comment]
So it now looks like this: 

<img width="373" alt="image" src="https://github.com/user-attachments/assets/0ff34917-0cbc-407a-875f-1c467eff0b1b">


and unfolded view: 

<img width="477" alt="image" src="https://github.com/user-attachments/assets/4a2605ac-8f35-423e-b0cf-3a3155750fbe">

**Comment by pgaudet** [comment]
@sjm41 
EC:2.3.1.286 is a broad xref on GO:0017136; (and all its childre) otherwise that term has no dbxref. 

Isn't that what we agreed on ?

**Comment by pgaudet** [comment]
Note that I also added 

+xref: EC:2.3.1.- {source="skos:broadMatch"}
+xref: EC:3.5.1.- {source="skos:broadMatch"}

on 
- GO:0004407 histone deacetylase activity
- GO:0141050  histone H3K deacetylase activity
- GO:0141051  histone H4K deacetylase activity

to make sure these terms have dbxrefs.

**Comment by sjm41** [comment]
> EC:2.3.1.286 is a broad xref on GO:0017136; (and all its childre) otherwise that term has no dbxref.

Yes, that's fine.
My main point was that both RHEA:43636/EC:2.3.1.286 should be (exactMatch) xrefs on GO:0034979, and I see from the latest go-edit-obo that that is now true, so that's all good!


Only issue I see with the new tree/terms is that "GO:0141221 histone deacetylase activity, hydrolytic mechanism" appears to lack parentage to 'hydrolase activity':

![Screenshot 2024-09-23 at 08 26 36](https://github.com/user-attachments/assets/dcdfdb57-3bec-40cc-8b09-91a9963099fa)

**Comment by pgaudet** [comment]
Thanks @sjm41 ! I've added the parent 
GO:0016811 ! hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides


Pascale

**Comment by ValWood** [comment]
I'm a bit confused. Some of my annotations have changed  in an unexpected way.

sirtuins, which are NAD dependent have become annotated as 
GO:1990162  [histone H3K4 deacetylase activity, hydrolytic mechanism](https://www.pombase.org/term/GO:1990162)
because 
histone deacetylase activity (H3-K4 specific)
is now called 
GO:1990162  histone H3K4 deacetylase activity, hydrolytic mechanism

so sir2 now has a mixture of NAD-dependent and hydrolytic
 https://www.pombase.org/gene/SPBC16D10.07c
but should these be mutually exclusive?

**Comment by pgaudet** [comment]
I see. The reason why I just renamed the term is because it fitted the definition: 

> Catalysis of the reaction: histone H3 N6-acetyl-L-lysine (position 4) + H2O = histone H3 L-lysine (position 4) + acetate. 

(still hasn't been changed in AmiGO, see below):

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/f44c23bf-a6e3-47f6-8537-83383ead24ac">

Should I have obsoleted? (I must say, since the meaning of the term didn't change, I thought I could just go ahead). 

Thanks, Pascale

**Comment by ValWood** [comment]
Ah, so in that case, I must have used the wrong term based on the definition? 
I'm not completely sure why it was wrong so maybe obsoletion would be better.
I wonder if other groups now have misannotations from using these terms?

**Comment by ValWood** [comment]
I think quite a lot of people must have used these incorrectly (because there was only one term for the particular modification, we used it  as if it was a parent without requesting NAD-dependent term)

For example
[GO:0043495](https://www.pombase.org/term/GO:0043495)
has the following intersections
<img width="907" alt="Screenshot 2024-09-25 at 16 08 33" src="https://github.com/user-attachments/assets/05ba5dbc-3d42-44c0-96a2-facbfd6d55b9">

(I didn't look at the other terms but I suspect they will be similar?)
 I think obsoletion would probably be cleaner  here but if not it will be a lot of reannotation.

**Comment by ValWood** [comment]
fixed the link in the comment above.

I guess most people didn't realise that NAD-dependent and NAD-independent were different mechanisms (I didn't)

**Comment by pgaudet** [comment]
You're making it look very scary ;) If I limit for EXP, I get this: 
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0031078&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants
There is only the one Sir2, all others are hydrolases

**Comment by ValWood** [comment]
OK! we can reannotate the sirtuins. 
@pcarme could you  read the thread and update our Sirtuin annotations  from the hydrolytic terms to the appropriate NAD-dependent term.

**Comment by PCarme** [comment]
HI all ! There is no existing NAD-dependent term for H3K4 deacetylase activity, only the hydrolytic equivalent, is it normal ?

**Comment by ValWood** [comment]
Hi @PCarme  I think it is just an oversight.  Can you request the ones we are missing in a new term ticket?
tks
v

**Comment by PCarme** [comment]
> OK! we can reannotate the sirtuins. @PCarme could you read the thread and update our Sirtuin annotations from the hydrolytic terms to the appropriate NAD-dependent term.

That's done now.

**Comment by pgaudet** [comment]
Great ! Thanks both
