### ISSUE TITLE
Add RHEA xref to GO:0033558 protein deacetylase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22833]
According to [this paper](https://www.sciencedirect.com/science/article/pii/S1570963916301169) only lysine acetytation is reversible, so I will make the term more specific for protein **lysine** deacetylase activity

Add RHEA:58108 | H2O +   N6-acetyl-L-lysyl-[protein] =   acetate +   L-lysyl-[protein]

There doesn't seem to be a corresponding EC, the closest EC I find is EC:2.3.1.286, which mentions NAD. 
@kaxelsen Are all protein lysine deacetylases NAD-dependent ?

Thanks, Pascale

**Comment by kaxelsen** [comment]
RHEA:58108 has two child reactions, RHEA:58196 for histone deacetylation and RHEA:21548 for alpha-tubulin deacetylation (see https://www.rhea-db.org/rhea/58108).
RHEA:58196 is linked to EC 3.5.1.98. Both these reactions are linked to proteins from the histone deacetylase family (e.g. HDAC1_HUMAN and HDAC6_HUMAN; GO:0000118, GO:0070932; GO; GO:0070933 among a lot of others), so this shows that at least one protein family uses a hydrolysis mechanism to liberate the acetate.
The sirtuin family all use a transferase mechanism as shown in RHEA:54172. Acetyl is only one of many lysine modifications to be removed by this mechanism, examples are biotin (RHEA:70479), succinate (RHEA:47668) and lipoate (RHEA:63640).
These are the two families mentioned in the review you cite above (see table 2).

I hope this is useful even though I can see you closed the ticket while I was still writing my answer.

**Comment by pgaudet** [comment]
Thanks @kaxelsen , sorry about closing the ticket too fast. EC:3.5.1.98 is xref for GO:0004407 histone deacetylase activity, so I think we're all good. 

Thanks, Pascale
