### ISSUE TITLE
clathrin-coated pit assembly  vs clathrin coat assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22873]
1. 
- [ ] I don't fully understand the difference between

GO:1905224 clathrin-coated pit assembly (2 EXP)
The aggregation, arrangement and bonding together of a set of components to form a clathrin-coated pit. 

( I could understand more if the term was something like 'endocytosis membrane invagination' or similar
and
GO:0048268  clathrin coat assembly (29 EXP)
The process that results in the assembly of clathrin triskelia into the ordered structure known as a clathrin cage. 

Isn't the pit just the progenitor of the clathrin coated vesicle, not a functional structure?

Also, quite a lot of the annotations to "GO:0048268  clathrin coat assembly" arre to the actual coat components. I will open a ticket for the ones I have seen.

2. should  GO:0048268  clathrin coat assembly be part of 
'clathrin -mediated endocytosis"?

**Comment by ValWood** [comment]
<img width="338" alt="Screenshot 2022-02-16 at 17 22 06" src="https://user-images.githubusercontent.com/7359272/154320786-7b06dd59-cbdd-46ed-acf5-20c3febdd958.png">

**Comment by pgaudet** [comment]
Looks like these two terms are synonymous? I suggest 

- [ ] obsoletion of GO:1905224 clathrin-coated pit assembly + replace by GO:0048268 clathrin coat assembly. 
and obsoletion of the corresponding regulation terms: 
- [ ]  [regulates relation] [GO:1905468 regulation of clathrin-coated pit assembly](http://amigo.geneontology.org/amigo/term/GO:1905468#display-lineage-tab) => 0 annotations
- [ ] [GO:1905469 negative regulation of clathrin-coated pit assembly](http://amigo.geneontology.org/amigo/term/GO:1905469#display-lineage-tab) => 1 EXP  annotation BHF -
- [ ]  [positively_regulates relation] [GO:1905470 positive regulation of clathrin-coated pit assembly](http://amigo.geneontology.org/amigo/term/GO:1905470#display-lineage-tab) => 0 annotations
- [ ] obsolete  GO:0099042 nucleation of clathrin-coated pit  + replace by GO:0048268 clathrin coat assembly (0 annotations)  >>> this term was created by @ValWood but didn't use it yet                         

Thanks, Pascale

**Comment by ValWood** [comment]
This is the history of this node: https://github.com/geneontology/go-ontology/issues/12403
I didn't request or create these terms but I was involved in the discussion.

I agree with all the suggestions so I'll proceed with this one.

**Comment by ValWood** [comment]
Ah sorry I see its assigned already to @raymond91125 ! I won't!

**Comment by raymond91125** [comment]
I guess it is hard to find any gene product that is functional intrinsic to the membrane (pit) and not the protein coat. There are proteins (e.g. FCHO initiation complex) that come to the nascent pit before any clathrin assembly but it's not clear that there is a pit to speak of without clathrin [PMID:21779028]. In other words, there does not seem to be any membrane assembly going on per se but assembly of the protein complex that brings about a membranous pit and then a vesicle.

**Comment by raymond91125** [comment]
Dear all, 

The proposal has been made to obsolete:
GO:1905224 clathrin-coated pit assembly, replace by GO:0048268 clathrin coat assembly
GO:1905468 regulation of clathrin-coated pit assembly, replace by GO:1905443 regulation of clathrin coat assembly
GO:1905469 negative regulation of clathrin-coated pit assembly, replace by GO:1905444 negative regulation of clathrin coat assembly
GO:1905470 positive regulation of clathrin-coated pit assembly, replace by GO:1905445 positive regulation of clathrin coat assembly
GO:0099042 nucleation of clathrin-coated pit, replace by GO:0048268 clathrin coat assembly

The reason for obsoletion is these terms are describing processes equivalent to that of the replacement terms.

There are 3 EXP annotations to these term by UCL (2) and UniProt (1), see https://github.com/geneontology/go-annotation/issues/4483. 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/22873.
